
= Unlock

剑桥大学原版权威教材Unlock，新版的Unlock覆盖欧盟标准CEFR的preA1-C1级别，也就是说从小学英语刚起步，到高中或者英语较高水平的阶段，基本都被覆盖到。

Unlock第二版有6个级别，除基础级外，第1-5级每个级别也是两本书：

Reading, Writing &amp; Critical Thinking 读写和批判性思维

这套教材共6个阶段，每个阶段包含听说、读写教材和音频等

Unlock Basic（基础级）：preA1，对应YLE starter-mover 剑桥少儿英语初级-中级；

Unlock L1（第一级）：A1，对应YLE mover-flyer，剑桥少儿英语中级-高级；

Unlock L2（第二级）：A2，对应KET，剑桥五级考试第一级，对应公立小学毕业时水平；

Unlock L3（第三级）：B1，对应PET，对应公立初中毕业时水平；

Unlock L4（第四级）：B2，对应FCE，对应公立高中毕业时水平；

Unlock L5（第五级）：C1，对应CAE，对应优秀高中毕业或大学生水平。

也就是说，这套书从孩子有一定英语基础开始，一直覆盖到到对标CAE考试级别，差不多是能够到国外上高中或上大学的水平。


'''

简单说，剑桥系：

1） Unlock 这套书，教材宗旨就是Unlock your knowledge，听说读写全面覆盖，第四册上完可达英语B2，大约对应雅思6.5

2）English in mind 这个也是听说读写全面覆盖，可达到B2-C1水平 （有引进版）

3）干脆来一套 剑桥英语可以从A1一直到C2 （部分有引进版。C1、C2太高端，没有引进）

Oxford也有出EFL的教材比如Oxford Discover；Oxford还有套不是教材但是超级出名的OXFORD READING TREE和书虫系列（国内引进）。剑桥也有一套小说馆，从A2-C1，国内引进了，双语，有指导。

美国教材更多了，比如National Geographic出版的reading explorer，close-up， pathways， 21st century多得是！reading explorer有引进版本，上外出版。

还有美国人自己用的加州语文，加州中学。从学生用书到练习册到教师用书都有。

美国人还有个好东西。去某宝，花50大洋买个RAZ账号，一年有效，零基础从AA读，小学生从B读，中学生么，可以从G级开始读，大学生从Q级开始读，研究生么，从T级开始读，读到Z1-Z2；什么科学，文学，什么都有了，还有林肯的葛底斯堡演讲。历史，文学，地理，人文，社会，应有尽有，还每天都能看见新文章添加进来。读完还有练习做，还有vocabulary，还有录音。找卖家要配套worksheet，或者直接百度搜搜RAZ worksheet， 词汇，写作，语法，critical thinking都练习到了。


在英語補習班中，常見的課程有分成ESL與EFL，這兩種。
**ESL 是 English as Second language 的簡寫，是以英語為媒介，學習其他知識的課程；**或是指英語為官方語言之一，通常在英語系國家教授。如:在美國開設給外國人的語言學校。
**EFL是 English as Foreign language，是將英語做外國語言教學的課程。**目的是正確學會英語，有時會以其他語言教授英語。如:在台灣義務教育中，學校教的英語。
但在小瓏英語書院，都是用全英語授課，因此這2種課程的差異在於教材、上課時數不同而已，課堂上也都會教文化、節慶等的內容喔。如Elisa老師上ESL課程時，除了使用美國小學的教材外，課堂中也會用英語教授數學、科學、社會科學等學科；而書院老師在教授EFL時，針對世足時事、新的迪士尼卡通歌曲，也會融入教學，讓小朋友可以跟上時事，活用英文。
ESL的教材為Journeys；EFL教材依程度、年紀，老師可以選用Everybody up, Explore our World, Oxford Discover或 Come on Phonics……等。附圖為教材封面。

作为一名一线城市的体制外英语老师，每几个月认知与对英语学习的理解就要被刷新一遍。比如说，上个月了解到有个三年级的娃CPE考试通过，有个五年级的娃雅思8分，还有六年级115的。这些娃无一例外都是启蒙早+大量原版阅读+系统EFL课程+剑桥考试体系上来的。

==  Think 教材