= 0673
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 673: Walking or Running as an Exercise.
This is English as a Second Language Podcast episode 673. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com, you probably know that. But did you know we also have Learning Guides for all of our current episode on our website that you can download? You knew that too, huh? Okay. You think you’re pretty smart, don’t you?!
This episode is called “Walking or Running as Exercise.” Let’s get started.
[start of dialogue]
Reina: Okay, I’m ready to walk my way to better fitness!
Lars: I’m glad you’re so enthusiastic about starting to exercise.
Reina: I’m totally psyched! Check out my new tennis shoes.
Lars: They’re brand new? You haven’t broken them in yet? I hope you don’t get blisters.
Reina: Stop worrying. Let’s go, I’m ready to work up a sweat!
Lars: Wait. There are a few things you need to know before we start. It’s a good idea to stretch and to warm up to avoid injuries.
Reina: I stretched already and as soon as we get started, I’ll warm up slowly. Let’s go!
Lars: All right, here we go, nice and slow.
Reina: Come on! How are we supposed to increase our heart rate if we walk this slowly? Pick up the pace!
Lars: I don’t want to get shin splints. It’s important that we start slowly and maintain a low-impact workout.
Reina: Forget it! I’ll race you. The last one to the park buys lunch. Ready, set, go!
Lars: Wait!
[end of dialogue]
Reina begins our dialogue by saying to Lars, “Okay, I’m ready to walk my way to better fitness!” “Fitness” is the level of your health and your strength, your ability to complete certain physical activities without a lot of difficulty. If you have problems walking up 10 stairs you may need to work on your fitness; you may need to exercise – to do exercises. Reina’s going to walk her way to better fitness, meaning she’s going to help her health and her strength by walking; that’s her way – her method.
Lars says, “I’m glad you’re so enthusiastic about starting to exercise.” To exercise,” of course, is to do some physical activity that will make your body stronger or healthier. Reina says, “I’m totally psyched!” “To be psyched” (psyched) is an informal expression meaning to be very excited about something, to be very eager and enthusiastic to do something. When it means this, it always ends in “ed” – “psyched.” The word “psych” has other meanings, which are not found in our Learning Guide – not this one anyway. Reina says, “Check out my new tennis shoes.” “Tennis” is a game, but “tennis shoes” are a kind of shoes that you can wear when playing tennis but you can also wear them for other sports. It’s a type of shoe you would wear to participate in different physical or sporting activities, so it’s not just for tennis. When spoken normally the two words run together so it sounds like “tennis-shoes.” Informally, you might even hear someone talk about their “tennies,” meaning their tennis shoes.
Lars says, “They’re brand new (referring to the tennis shoes)?” “To be brand new” means to be recently purchased; you bought them yesterday or this morning. They’ve never been used before, that’s another meaning here of “brand new.” Lars says, “You haven’t broken them in yet?” “To break (something) in,” or “to break in (something)” is a two-word phrasal verb meaning to wear something, especially shoes, for short periods of time until your feet get used to the shoes, until the shoes begin to perhaps loosen up a little bit so that it isn’t uncomfortable to walk in them. So when you buy a new pair of shoes you may wear them the first day for a couple of hours, the second and third day for a couple of hours until gradually you’re wearing them all the time, a little bit more each day. There are other meanings of this expression “to break in,” those can be found in our Learning Guide. You see, those you can actually find in the Learning Guide! Lars continues, “I hope you don’t get blisters.” A “blister” (blister) is a small, usually painful, raised area of skin that is filled usually with some sort of clear liquid. It’s caused when you rub a certain part of your body against something for a long time. So if you’re wearing shoes that are too small for you, the shoes will rub against your skin and you will get blisters.
Reina says, “Stop worrying.” She’s not going to get blisters, that’s which she’s implying. She says, “Let’s go, I’m ready to work up a sweat!” The expression “to work up a sweat” means to do very difficult physical activity that will result or that will have the cause of water coming out of your skin. When that happens, or when you’re very hot, we say you are “sweating.” That’s what Reina wants to do; she wants to sweat – to work up a sweat.
Lars says, “Wait. There are a few things you need to know before we start. It’s a good idea to stretch and to warm up to avoid injuries.” “To stretch” (stretch) here means to move the different parts of your body – your arms and your legs, for example – in sort of unusual ways so that the muscles begin to work, so that your muscles are more flexible. You might put your hands up in the air or put one hand against the other and start to pull. That would be stretching. You’ll often see athletes stretch before they participate in their sport. The theory is – and not everyone agrees this is true – but the theory is by stretching you will avoid injuries, meaning you won’t hurt yourself. For other meanings of the word “stretch” take a look at that Learning Guide. “To warm up” means to do a physical activity gently or slowly for the first few minutes. So for example, if you are going to go running you may run slowly for the first four or five minutes until your body and muscles start getting used to what you are doing, and then you may start running faster.
Reina says, “I stretched already and as soon as we get started, I’ll warm up slowly. Let’s go!” Reina just wants to start. Lars says, “All right, here we go, nice and slow,” meaning very slowly, comfortably. Reina says, “Come on!” That expression, “come on,” when shouted at someone, can mean that you are frustrated with them or it could mean that you want them to go faster. Reina probably has a little bit of both of those meanings. She says, “How are we supposed to increase our heart rate if we walk this slowly? Pick up the pace!” Your “heart rate” is the speed at which your heart “beats” (beats), which is the verb we use for the movements of the heart – the movements that the heart muscle makes. “To increase your heart rate” means that your heart will start beating faster; it will start working harder.
Reina wants Lars to pick up the pace (pace). “To pick up the pace” means to begin to do something more quickly, to move more quickly, to hurry. Lars says, “I don’t want to get shin splints.” Your “shin” (shin) is the part of your leg – the front of your leg between your knee and your foot. “Shin splints” is a condition where you experience pain in that part of your body, often caused by running on very hard surfaces or wearing shoes that are not appropriate, that aren’t good for running. Lars says, “It’s important that we start slowly and maintain a low-impact workout.” “Low-impact” is an exercise that doesn’t require that your body be moving or jumping or running on a hard surface; it’s also a general term for exercise that isn’t very difficult, it’s sort of easier than doing other kinds of exercise. The noun “workout” is a session or a short period of time of doing some sort of physical activity, especially if you do it regularly. I work out Monday through Friday by walking every morning; that’s my workout. Notice I also used “work out” (two words) as a verb, meaning to exercise. Here it’s used as a noun; it means that period of time when you are exercising.
So Lars wants to do a low-impact workout. Reina says, “Forget it!” meaning I’m frustrated with you, I’m tired of you, I’m not going to do that. Reina says, “I’ll race you.” “To race (someone)” is to see who can run, in this case, the fastest, who can do the activity the quickest. Reina says, “The last one to the park buys lunch,” meaning they’re going to race – they’re going to compete against each other, and the last person to arrive at the park where they’re going in their run or walk has to buy lunch. If you lose, in other words, you have to buy lunch. Reina says, “Ready, set, go!” These three words are traditionally used to begin a race. “Ready, set, go,” and then you begin after the word “go.” It’s sort of like “three, two, one,” but we use this expression, at least in American English, “ready, set, go.”
We’re not sure, in this dialogue, if Lars is lazy or Reina is not too smart and may injure herself!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Reina: Okay, I’m ready to walk my way to better fitness!
Lars: I’m glad you’re so enthusiastic about starting to exercise.
Reina: I’m totally psyched! Check out my new tennis shoes.
Lars: They’re brand new? You haven’t broken them in yet? I hope you don’t get blisters.
Reina: Stop worrying. Let’s go, I’m ready to work up a sweat!
Lars: Wait. There are a few things you need to know before we start. It’s a good idea to stretch and to warm up to avoid injuries.
Reina: I stretched already and as soon as we get started, I’ll warm up slowly. Let’s go!
Lars: All right, here we go, nice and slow.
Reina: Come on! How are we supposed to increase our heart rate if we walk this slowly? Pick up the pace!
Lars: I don’t want to get shin splints. It’s important that we start slowly and maintain a low-impact workout.
Reina: Forget it! I’ll race you. The last one to the park buys lunch. Ready, set, go!
Lars: Wait!
[end of dialogue]
Our dialogues are always brand new; that’s because they’re written by our own scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, won’t you, on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
fitness – one’s level of physical health and strength; one’s ability to complete physical activities without great difficulty
* Vadim spends hours at the gym each week, because fitness is really important to him.
to exercise – to do physical activities in order to make one’s body stronger and healthier
* If we want to lose weight, we need to start eating better and exercising more.
psyched – an informal term meaning very excited, enthusiastic, and eager to do something
* Marleah is psyched about starting her new job at the hospital.
tennis shoes – comfortable shoes used to participate in sports and other physical activities, closed with shoelaces
* Lauren wears high-heeled shoes at work, but she carries tennis shoes in her bag so that she can wear more comfortable shoes while walking to the subway after work.
brand new – recently bought and never before used
* Why would you wear a brand new shirt to paint the house? It’s just going to get ruined.
to break (something) in – to wear something, especially shoes, for short periods of time so that it adapts to one’s body and become more comfortable; to use something for short periods of time so that one becomes used to it
* Be sure to break your hiking boots in on some short walks before you go on any long-distance hikes.
blister – a small, painful, raised area of skin that is filled with a clear liquid, usually caused by having something rub against that area repeatedly
* After raking all the leaves, Mariah realized that she had blisters on her hands.
to work up a sweat – to do a difficult physical activity that results in a small amount of water on one’s skin, caused by the body’s efforts to stay cool
* It’s so hot outside today that we could work up a sweat just by walking around the block!
to stretch – to move one’s body parts in unusual ways, pushing them as far as they will go in a certain direction to make the muscles work and to become more flexible
* If you stretch every morning, eventually you’ll be able to touch your toes without bending your knees.
to warm up – to do a physical activity gently or slowly for a few minutes, gradually increasing one’s heart rate and breathing before beginning more difficult physical activity
* If we don’t warm up before playing basketball, we’re more likely to get injured.
heart rate – the speed at which one’s heart beats (contracts to move blood through one’s body).
* His resting heart rate is 65 beats per minute.
to pick up the pace – to begin to do something more quickly; to hurry; to move more quickly
* Let’s pick up the pace, or else we won’t get home before dark.
shin splints – a condition where one experiences pain on the front of one’s leg between one’s knee and foot, often caused by running on hard surfaces and/or wearing shoes that do not have enough padding
* Shayna’s shin splints became so painful that she had to stop running competitively.
low-impact – exercise that does not require hitting one’s body parts against hard surfaces; exercise that is not very strenuous or difficult
* The doctor recommended low-impact exercise instead of running.
workout – a session or short period of physical exercise, especially when it is something that one does regularly
* This morning Grant did a 30-minute aerobic workout at the gym, followed by 20 minutes of lifting weights.
to race – to compete to see who can do something fastest, especially to see who can run to a particular place most quickly
* Let’s race to see who can finish the test first.
ready, set, go – a phrase used to start a race, so that people prepare to do something when they hear “ready, set,” and then begin to do it when they hear “go”
* When I say, “go,” run to the fence. Ready, set, go!
Comprehension Questions
1. Why does Lars ask, “You haven’t broken them in yet?”
a) He’s surprised that this is the first time she’s wearing the shoes.
b) He’s surprised that she bought new shoes instead of used shoes.
c) He’s surprised that the shoes are still in good condition.
2. What does Reina mean when she says, “Pick up the pace”?
a) She wants Lars to run more quickly.
b) She wants Lars to take bigger steps.
c) She wants Lars to raise his legs higher.
Answers at bottom.
What Else Does It Mean?
to break (something) in
The phrase “to break (something) in,” in this podcast, means to wear something for short periods of time so that it adapts to one’s body and becomes more comfortable: “Leather jackets are stiff at first, but once you break them in, they become more comfortable.” The phrase “to break in” means to enter a building without permission, usually to steal something: “Have the police caught the man who broke into the store last night?” When talking about skin, the phrase “to break out” means for one’s skin to become covered in small red blemishes: “Is it true that eating chocolate can cause your skin to break out?” Or, “Hal’s skin breaks out whenever he eats shellfish.” Finally, the phrase “to break out” can mean to leave a prison or jail without permission: “Some of the prisoners are planning to break out next Thursday.”
to stretch
In this podcast, the verb “to stretch” means to move one’s body parts in unusual ways, pushing them as far as they will go in a certain direction to make the muscles work and to become more flexible: “Taking a yoga class is a great way to learn how to stretch.” The phrase “to stretch (one’s) legs” means to take a short walk, especially after one has been seated for a long period of time: “It isn’t good to sit in front of the computer for hours at a time. Why don’t we take a break and stretch our legs?” Finally, the phrase “to stretch the truth” means to exaggerate or to say something that isn’t entirely true: “Raymond was stretching the truth when he said that he was an expert skier. The truth is, he has skied only three times.”
Culture Note
A “walkathon” is a “fundraiser” (an event designed to collect money for a particular organization or purpose) where many people walk along a certain “route” (path). It is similar to a “marathon” (a race to run a long distance), but it isn’t “competitive,” meaning people aren’t really trying to be the first person to “cross the finish line” (finish a race by passing the final point). “Rather” (instead), the people in a walkathon enjoy walking along the entire route and supporting a “cause” (charitable purpose) they believe in.
Walkathons are often used to raise “funds” (money) for organizations that are “searching for a cure for” (conducting research to find a way to heal people who are suffering from) a particular disease, or organizations that “promote” (encourage) disease “prevention” (actions and behaviors that help one not become sick). Many of the participants walk as a way to remember “loved ones” (relatives or close friends) who suffer from the disease or have died from the disease, sometimes putting that person’s name and photo on their clothing for others to see during the walkathon.
Typically, a person pays a “fee” (an amount of money) to register for the walkathon. “Entrants” (people who participate in the walkathon) usually receive a free t-shirt that they wear during the walkathon. In other walkathons, entrants ask others to “sponsor” (financially support) them, perhaps by paying a certain amount of money when the entrant completes the race, or by paying a certain amount of money for each mile walked by the entrant. All the “proceeds” (money earned) are given to the sponsoring organization.
Comprehension Answers
1 - a
2 - a