= 0695
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 695: Being Late for an Event.
This is English as a Second Language Podcast episode 695. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in – where else – Los Angeles, beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode to help you improve your English even faster.
This episode is called “Being Late for an Event.” Let’s get started.
[start of dialogue]
Eric: Let’s get a move on or we’ll be late – again!
Carmen: Hold your horses. I’m on the verge of being ready. Rome wasn’t built in a day, you know.
Eric: A day? I’d settle for a week. Why is it that every time we have someplace to be you’re always running late?
Carmen: That’s because I march to the beat of a different drummer. Life isn’t about watching the clock; it’s about living in the moment.
Eric: Okay, at this very moment, we’re late.
Carmen: Just give me a couple of minutes more and I’ll be ready. After all, none of our friends expect us to be punctual anymore. They all know better.
Eric: Yeah, and I should, too. From now on, I’ll start getting ready when you say you’re all set. Then I’ll just have minutes to wait – not hours!
[end of dialogue]
Eric starts off, or begins our dialogue by saying to Carmen, “Let’s get a move on or we’ll be late – again!” “To get a move on” means to hurry, to rush, to do something quickly. “We better get a move on or we will be late for dinner with our friends.” Eric says to Carmen hurry up, basically.
Carmen says, “Hold your horses.” “To hold your horses” is an old expression meaning to wait, to be patient, to stop rushing or hurrying another person, probably because horses, when they are scared especially, sometimes go very fast, you have to control them. Well, Carmen is telling Eric to hold his horses, meaning stop rushing her, stop trying to make her go faster than she is. She says, “I’m on the verge of being ready.” “To be on the verge (verge) of (something)” means almost, very soon, it’s just about to happen. Because “of” is a preposition the word that comes after it, if it’s a verb, has to be changed into what’s called a gerund, making it the object of the preposition as a noun. So, you notice Carmen says, “I’m on the verge of being (being) ready,” “being” is a gerund. You could say, “I’m on the verge of going to the store.” “I’m on the verge of winning this poker game,” or whatever. “Rome wasn’t built in a day, you know,” Carmen says. This is also an old expression: “Rome wasn’t built in a day.” It means that if you are doing something important it takes time; it can take a long time, you can’t try to do it quickly. The great City of Rome, with all of its wonderful buildings and architecture, wasn’t built in a day, meaning it took many years – hundreds of years to make it what it is. Well, that’s the expression, and that’s what Carmen is saying to Eric. She’s doing something great by preparing herself, I guess.
Eric says, “A day? I’d settle for a week.” “To settle for” is an expression that means to accept something that isn’t exactly what you wanted, but is good enough “I settled for living in this apartment.” It isn’t my favorite place, but it’s good enough for me. It will be satisfactory; not great, not terrible. Eric is making a joke, saying that, in effect, he doesn’t want to build Rome in a day, he would take a week, that would be okay. Eric says, “Why is it that every time we have someplace to be you’re always running late?” “To run late” means to be behind schedule, to do things too slowly so that you can’t complete them when you are expected to complete them.
Carmen says, “That’s because I march to the beat of a different drummer.” This is another old expression: “To march to the beat (beat) of a different drummer.” A “drummer” is someone who plays a drum, usually they have two sticks and they hit the drum. The “beat” is the repeating stress that appears – that you hear in the music. It’s what you will often hear in a rock band, for example, the drummer playing. The drummer will be playing the same thing over and over again, repeating it. That is often the beat for the song. Carmen says, “I march (I walk) to the beat of a different drummer.” What she’s saying is that I do things differently than other people, I don’t follow what everyone else does. Drummers are often used especially in the military – or used to be used – to keep everyone going forward at the same speed. Carmen says, “Life isn’t about watching the clock; it’s about living in the moment.” “To watch the clock” means that you are always aware of what time it is and you try to be places on time, on schedule, you’re not late. You’re making sure that you arrive or other people arrive on time. But that’s not what Carmen says life is about, that’s not the purpose of life. Life is about living in the moment. “To live in the moment” means that you’re not thinking about or worrying about the past, you’re not worried about the future, you’re only thinking about what’s happening right now. You want to experience the present completely and fully. That’s to live in the moment, not to worry about the future or the past, but just about what you are experiencing right now.
Eric says, “Okay, at this very moment, we’re late.” “Very” has many uses in English. Here, it is used for emphasis to mean exactly or precisely. “I fell in love with my now-wife the very moment I saw her the first time.” At that exact moment, I fell in love. Doesn’t every woman want to hear that? Eric says that at this very moment, right now, we’re late.
Carmen says, “Just give me a couple of minutes more and I’ll be ready.” “To give (someone) a couple of minutes” means to give them a little more time, not to try to rush them, not to try to make them go faster, not to continue asking them to go faster. Carmen says, “After all, none of our friends expect us to be punctual anymore. They all know better.” She’s saying if you think about it, I mean in terms of what’s most important; that’s the meaning of the expression “after all.” “After all, none of our friends expect us to be punctual anymore.” “To be punctual” (punctual) means to be on time, to arrive when people are expecting you to arrive. She says that their friends all know better. The expression “to know better” means that you have enough experience of something or knowledge of something to know how it will actually be, which is different than how it should be or how someone tells you it will be. So you might say, for example, “My sister-in-law said she would be here at 5:30, but I know better. She won’t be here until six.” “I know better,” I have experience; I have knowledge about when she normally arrives, and it’s normally late. I know better.
Eric says, “Yeah, and I should, too,” meaning I should know better as well. “From now on, I’ll start getting ready when you say you’re all set.” “To be all set” means to be completely prepared, to be completely ready, you don’t need any more time. Eric says that when Carmen says that she’s all set, then he’ll start getting ready. “Then,” he says, “I’ll just have minutes to wait – not hours!” In other words, Eric is going to wait, in the future, until Carmen says she’s ready, and then he’ll get ready. That way – in that manner, he won’t have to wait hours for her to get ready, it will only be minutes.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Eric: Let’s get a move on or we’ll be late – again!
Carmen: Hold your horses. I’m on the verge of being ready. Rome wasn’t built in a day, you know.
Eric: A day? I’d settle for a week. Why is it that every time we have someplace to be you’re always running late?
Carmen: That’s because I march to the beat of a different drummer. Life isn’t about watching the clock; it’s about living in the moment.
Eric: Okay, at this very moment, we’re late.
Carmen: Just give me a couple of minutes more and I’ll be ready. After all, none of our friends expect us to be punctual anymore. They all know better.
Eric: Yeah, and I should, too. From now on, I’ll start getting ready when you say you’re all set. Then I’ll just have minutes to wait – not hours!
[end of dialogue]
She’s always punctual; she never runs late. That’s our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
emergency room – the part of a hospital that is always open for patients who have very serious, life-threatening problems and can come without an appointment
* The nurse said we should monitor the baby’s temperature, and if it reaches 105, we should take her to the emergency room.
severed – separated or detached, usually by cutting, often used to talk about a body part
* His leg was severed in a horrible car accident.
stitch – a piece of thread sewn into one’s skin to close a deep cut
* When Nate dropped a sharp knife on his toe, he had to get three stitches.
admissions desk – the table or counter where one first goes when entering a facility or office to explain why one has come and request an appointment or visit
* The man at the admissions desk gave us several forms to fill out and asked us to bring them back with a copy of our insurance card.
waiting room – a large area with many chairs where people wait until it is their turn to be seen by a doctor or dentist, often with magazines for people to read
* I was in the waiting room for more than 20 minutes, so I asked the receptionist how much longer it would be before I would see the doctor.
filled to capacity – completely full, without room for anyone else or anything else
* The auditorium was filled to capacity with people who wanted to hear her speak.
ambulance – an emergency vehicle used to transport people with serious medical problems to a hospital, filled with equipment and supplies so that they can receive medical treatment while traveling
* Do you think you can drive yourself to the hospital, or should we call an ambulance?
EMT – emergency medical technician; a person whose job is to provide medical assistance in an emergency, especially taking care of that person until he or she can be brought to a doctor or hospital
* The EMT kept Aunt Mildred alive while she was in the ambulance on her way to the hospital.
stretcher – a narrow bed on wheels used to move a sick or injured person who cannot walk or sit
* The nurses pushed Kara down the hall on a stretcher, because she was still unconscious.
pileup – a traffic accident involving many cars, each one crashing into the car in front of it
* The ice storm caused a seven-car pileup.
triage – the process of determining which patients need medical treatment immediately and which ones can wait, based on how sick or injured they are
* The nurses began performing triage as soon as they arrived at the site of the explosion.
critical – very serious, especially referring to a dangerous or life-threatening illness or injury
* The wound is very painful, but it isn’t critical.
exam room – a room where a doctor interacts with a patient to determine what is wrong and what type of treatment needs to be provided
* They asked Walt to go into the exam room, take off his shirt, and wait for the doctor to come in.
surgery – a medical procedure that requires cutting open part of one’s body so that a doctor can fix or remove something
* The doctors said surgery is the only way to fix Xavier’s knee.
to give up – to stop trying to have or do something, usually because it seems extremely difficult or impossible
* Lauren tried to be an actress for 15 years before deciding to give up and try a different career.
to bleed to death – to die from a loss of blood; to die because one has lost too much blood through a cut or wound
* Yes, you’ve cut your finger, but I don’t think you’ll bleed to death. Just put pressure on it.
total loss – something that had no useful purpose or result; something that was worthless or pointless
* Attending that conference wasn’t a total loss. Although we already knew most of the information we were given, we learned one or two new things.
voluntarily – willingly; without being forced to do something; doing something because one wants to
* Did you join Alcoholics Anonymous voluntarily, or did someone make you do it?
Comprehension Questions
1. Why does Carmen say, “Hold your horses?”
a) Because she thinks Eric is being impatient.
b) Because she thinks Eric is being rude.
c) Because she thinks Eric is a good horse rider.
2. What does Carmen mean when she says she marches to the beat of a different drummer?
a) She likes to listen to music while she’s getting ready.
b) She does things differently than other people do.
c) She can’t do things as quickly as other people do.
Answers at bottom.
What Else Does It Mean?
to settle for
The phrase “to settle for,” in this podcast, means to accept something that is not what one really wanted, but is satisfactory: “They asked for 18,000 for their used car. Do you think they’ll settle for $16,000?” The phrase “to settle down” means to become calmer and more quiet: “Hey, settle down in there! You guys are making way too much noise, and I need to study!” The phrase “to settle in” means to begin to feel comfortable and content in a new environment: “How long did it take you to settle into your new job?” Finally, the phrase “to settle up” means to pay the money one owes: “While traveling together, they agreed to put all the expenses on one credit card and then settle up at the end of the trip.”
very
In this podcast, the word “very” is used for emphasis: “She showed up to the wedding wearing the very dress that I had planned to wear! Thank goodness I changed my mind at the last minute.” Or, “This manufacturer claims to use only the very best ingredients for its dog food.” The phrase “the very thought” or “the very idea of (something)” means that even thinking of something, even though one wasn’t actually doing or having it, was enough for something else to happen: “When she was pregnant, even the thought of raw meat made her want to throw up.” Finally, the phrase “very much so” is used to show strong agreement with someone or something: A: “Do you really believe that?” B: “Yes, very much so.”
Culture Note
Etiquette for Arriving Late to a Performance
In the United States, “punctuality” (one’s ability to arrive to places on time as expected) is very important in most situations. “Arriving late” (coming later than expected) is generally considered to be “rude” (impolite) and disrespectful of others. There are some “exceptions” (instances when a rule does not apply), but it is usually best to arrive at the time stated on an invitation or announcement.
When arriving late to an event or an artistic performance, certain “etiquette” (expected behavior) should be followed. For a concert or play, it is important to wait outside the main theater area and enter only during “applause” (when people are clapping) and/or “intermission” (the break between scenes or small performances, when people move around and can drink, eat, or smoke). Often an “usher” (a person whose job is to help people find their seats) will “guard” (watch over) the door and not let “latecomers” (people who arrive late) enter the theater until intermission. Sometimes there is a “viewing area” where latecomers can watch the performance “live” (in real time) on television until they are allowed to enter the theater.
If latecomers are allowed to enter during applause, they should do so very quietly, without “calling attention to themselves” (doing things that make other people look). This means entering very quietly, without “disturbing” (bothering; interrupting) other people. If their seats are in the middle of a row “(a group of seats placed next to each other), they may want to stand in the back of the theater until there is a break on stage, because moving to those seats would require making other people stand up and would “block the view” (make it so someone cannot see) of the people behind.
Comprehension Answers
1 - c
2 - a