= 0368
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 368: A Corporate Takeover.
This is English as a Second Language Podcast episode 368. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. On it, you can download a Learning Guide for this episode. The Learning Guide contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension questions, and a complete transcript of everything we say on this episode. If you’re looking for a way to improve your English even faster, download the Learning Guide.
This episode is called “A Corporate Takeover.” It’s a dialogue between Lee and Bruce, talking about one company trying to buy another company. Let’s get started.
[start of dialogue]
Lee: Hello, Lee Williams.
Bruce: Hi, Lee. This is Bruce Eng. The reason I’m calling is to find out if there is any news about your company’s takeover bid for Shamrock Corp. It’s been a week and I was wondering what’s happening.
Lee: Hi, Bruce. I’m glad you called. I was just about to call you with an update. Here’s where we are. The offer we made to Shamrock was rejected by the board on Tuesday. Our company’s board of directors has been meeting all week to decide the next course of action.
Bruce: Is there any chance that this could turn into a hostile takeover?
Lee: There is a distinct possibility. Our company is hoping to avoid that since we had hoped to do extensive due diligence, but a hostile takeover may be the only option right now if we decide to move ahead with this.
Bruce: Would the banks go for little or no due diligence? I thought that their support of the takeover bid was contingent on getting more information about the state of Shamrock’s finances.
Lee: You’re right and that may be the stumbling block.
Bruce: Okay, well, call me if you get more information.
Lee: I will. You can count on it.
[end of dialogue]
Our dialogue begins with Lee answering the telephone; she begins by saying, “Hello,” and then her name, “Lee Williams.” Bruce says, “Hi, Lee. This is Bruce Eng. The reason I’m calling is to find out if there is any news about your company’s takeover bid for Shamrock Corp.” A “takeover bid” is when one person or one company tries to take control of another company, usually by buying its stocks. “Shamrock Corp.” is short for “Shamrock Corporation.” Bruce says, “It’s been a week and I was wondering what’s happening,” he wants to know if there has been any changes.
Lee says, “I’m glad you called,” it’s a common thing to say when someone calls you, especially for a business reason, and you have information that you want to give them and perhaps were thinking of calling them also. Lee says, “I’m glad you called. I was just about to call you with an update,” telling you the latest news. “Here’s where we are,” she says – here’s our current situation. “The offer we made to Shamrock was rejected by the board on Tuesday.” The “offer,” in this case, is what someone says they will give you in exchange for something else; usually it’s an amount of money that you’re willing to pay for something. “Offer” has a lot of different meanings in English; take look at our Learning Guide for some additional explanations.
The offer was “rejected,” meaning it was refused, it was denied; they said no to the offer, they didn’t want it. Lee says that her company’s board of directors has been meeting all week to decide the next course of action. The “board of directors” are the group of people who lead a company. They make the most important decisions, they select the president, and so forth. “The next course of action” means simply the next thing that you plan to do – the next step. It sounds a little bit more formal when you say “the next course of action.”
Bruce says, “Is there any chance that this could turn into a hostile (or hostile) takeover?” (Either pronunciation is correct.) Bruce is asking if there’s a chance that this takeover bid – this offer to buy the company may become hostile. That is, when a company is trying to buy another company but the other company doesn’t want to sell, if they have what we would call “publicly traded” stocks, meaning anyone in the public can own part of the company, then they can’t necessarily prevent another company from buying their stock and taking control of the company. That would be a hostile takeover, when the company doesn’t want to be bought.
Lee answers by saying, “There is a distinct possibility,” meaning something may happen or is likely to happen. A “distinct possibility” – it seems possible. Our company,” she says, “is hoping to avoid that (to avoid a hostile takeover) since we had hoped to do extensive due diligence.” “Extensive” means thorough, with a lot of detail, very complete. “Due (due) diligence (diligence)” is a legal or business term meaning the investigation and evaluation of a company’s financial status, about how they are doing. “Due diligence” means you do a lot of research.
“A hostile takeover,” Lee says, “may be the only option right now if we decide to move ahead with this.” “To move ahead” is a phrasal verb meaning to proceed, to continue to make progress, or simply to continue. You’ll hear in many businesses, when you are talking about a project, “let’s move ahead with this.” “Let’s move ahead” – let’s continue with this project.
Bruce then asks, “Would the banks go for little or no due diligence?” “To go for something” is a phrasal verb meaning to agree to do something, to agree with an idea, to accept something. “Will he go for it?” means will he agree with it – will he decide that it’s okay? Bruce is asking if the banks would go for little or no due diligence. He says, “I thought that their support of the takeover bid was contingent on getting more information.” “To be contingent” means to be dependent; something that will happen only if something else does or does not happen. It’s very common, when people sell their house in the United States, to make the sale of or the purchase of another property contingent upon, or contingent on the sale of their own property. So I own a house; I want to buy a different house. I make an offer to the owner of the other house, but I say, “I will only buy your house if I sell my house first.” That’s a contingency offer; it is contingent on something else.
Bruce says that the takeover bid, he thought, was contingent upon the banks getting more information about the state of Shamrock’s finances. The “state” of something is the condition of something; it’s the status, how something is doing. Every January in the United States, the president must go before the Congress (the Senate and the House of Representatives meeting together) and give a State of the Union address. This is a speech that the president is supposed to use to describe how the country is doing. The “Union” would just be the union of states – the 50 states. Governors have State of the State speeches for the same reason. “Finances,” here, means financial status, the amount of money that a company or organization is making or losing.
Lee says, “You’re right, that may be a stumbling block,” meaning the fact that they have done little or no due diligence would be a stumbling block for the banks. A “stumbling block” is an obstacle, something that makes it difficult or impossible. A stumbling block, here, is the fact that the company has not done research – done due diligence on this takeover. The banks may decide no, they will not support this takeover bid.
Bruce says, “Okay, well, call me if you get more information.” Lee says, “I will. You can count on it.” “To count on something” is a phrasal verb meaning to depend on something, or to rely on something. To know without a doubt that something will happen, that’s to count on something. I can count on you, our listener, to support us here at ESL Podcast, to tell all of your friends – I hope!
Now let’s listen to the dialogue again, this time at a normal speed.
[start of dialogue]
Lee: Hello, Lee Williams.
Bruce: Hi, Lee. This is Bruce Eng. The reason I’m calling is to find out if there is any news about your company’s takeover bid for Shamrock Corp. It’s been a week and I was wondering what’s happening.
Lee: Hi, Bruce. I’m glad you called. I was just about to call you with an update. Here’s where we are. The offer we made to Shamrock was rejected by the board on Tuesday. Our company’s board of directors has been meeting all week to decide the next course of action.
Bruce: Is there any chance that this could turn into a hostile takeover?
Lee: There is a distinct possibility. Our company is hoping to avoid that since we had hoped to do extensive due diligence, but a hostile takeover may be the only option right now if we decide to move ahead with this.
Bruce: Would the banks go for little or no due diligence? I thought that their support of the takeover bid was contingent on getting more information about the state of Shamrock’s finances.
Lee: You’re right and that may be the stumbling block.
Bruce: Okay, well, call me if you get more information.
Lee: I will. You can count on it.
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
takeover bid – a person’s or company’s willingness to buy shares or stocks to have control over a company
* Did you hear that the company received a takeover bid from its strongest competitor last week?
offer – something that one says one will give to another person in exchange for something else; the amount of money that one is willing to pay for something; what one is willing to do in exchange for something else
* They made an offer of $7,500 to buy the used car and now they are waiting to hear the seller’s decision.
to reject – to refuse; to deny; to say no; to decide not to do or accept something; to not accept
* The committee rejected our proposal to change the advertising campaign.
board of directors – the group of people who lead a company, making the most important decisions and selecting the CEO, president, and/or making other important positions
* Only the board of directors can decide whether our company should open a new office in the Southern United States.
the next course of action – the next step; the next thing that a person or company plans to do
* Our first attempt to expand toy sales to young boys didn’t work, so our next course of action is to try to expand sales to young girls.
hostile takeover – the action of taking control of a company when that company’s managers and leaders do not want it to happen
* The company president is fighting against the hostile takeover, but there’s really nothing she can do about it because the other company has enough money to buy most of the shares.
a distinct possibility – something that may happen or is likely to happen
* There is a distinct possibility that we might all lose our jobs next month if the economy continues to have problems.
extensive – thorough; with a lot of detail; vast; far-reaching
* Albertina conducted extensive research about tuberculosis, reading all the medical journals that she could find.
due diligence – the investigation and evaluation of a company’s financial status and management
* Our company is considering buying a smaller company, but we have to complete our due diligence first to make sure that we know exactly what we’ll be getting out of the purchase.
to move ahead – to continue; to proceed; to make progress
* Even though they don’t have enough money to buy a house right now, they have decided to move ahead and look at what’s available for sale so that they can know how much money they’ll need to save.
to go for (something) – to agree to do something; to agree with an idea; to accept something; to not object to something
* Sonja wants to dye her hair bright pink, but I don’t think her parents will go for it.
contingent – dependent; something that will happen only if something else does or does not happen
* Their ability to have an outdoor wedding is contingent on the weather, because if it rains, they’ll have to move everything indoors.
the state of – condition; status; quality
* The state of the natural environment seems to get worse every year.
finances – financial status; the amount of money that a company or organization is making or losing
* The company made more than four million dollars in sales last year, so its finances are very encouraging.
stumbling block – obstacle; something that makes it difficult or impossible to do something
* Shane is very religious, but his girlfriend isn’t, and that difference is a huge stumbling block in their plans to get married.
to count on (something) – to depend on something; to rely on something; to know without a doubt that something will happen or will be available
* We’re all counting on you to make a great presentation at tomorrow’s meeting.
Comprehension Questions
1. Why did the company want to do extensive due diligence?
a) To replace the board of directors.
b) To reject the takeover bid.
c) To learn about the state of Shamrock’s finances.
2. What does Lee mean by saying, “You can count on it”?
a) Bruce can count the number of stumbling blocks.
b) Bruce can do due diligence on Shamrock’s countable finances.
c) Bruce can trust her to call him when she has more information.
Answers at bottom.
What Else Does It Mean?
offer
The word “offer,” in this podcast, means something that one says one will give to another person in exchange for something else: “He will sell his boat to whomever makes the best offer on it.” As a verb, “to offer” means to indicate that one is willing to give something to someone or do something for someone: “Has anyone offered to help you drive to Wichita?” Or, “If I see a pregnant woman on the bus, I usually offer her my seat.” An “offering” is the money that a person gives to a church: “How much of an offering do you leave every Sunday?” Finally, an “offering” is something that one gives to a god: “People of this religion used to kill animals as offerings for the Lord.”
to go for
In this podcast, the phrase “to go for (something)” means to agree to do something or to accept something: “Do you think they’ll go for our suggestion to lower the price?” The phrase “go for it!” is used to encourage someone to do something that he or she isn’t sure about: “Should I apply to McQuillan University?” “Yes, go for it! I think you’ll have a very strong application.” The phrase “to go for (something)” can also mean to choose something: “I think I’ll go for the chicken and rice dish.” Finally, the phrase “to go for (someone or something)” can mean to be applicable to something: “Your sister can’t go outside to play until she finishes her homework, and that goes for you, too!”
Culture Note
A “corporate raid” is an “aggressive” (forceful and not timid) strategy that businesses use to “get rid of” (eliminate) their competition. In a normal hostile takeover, Company A buys Company B and then operates it as part of Company A. “In contrast” (showing the difference between two things), a corporate raid is a type of hostile takeover in which Company A buys Company B, but then sells Company B’s “assets” (anything that has value and can be sold). When this happens, Company A has one fewer “competitor” (a company that another company has to fight against for customers and profits). Corporate raids work well when Company B has many assets but a very low stock price.
Corporate raids were “at their height” (at a maximum and extremely common) in the 1970s and 1980s. “A handful of” (a few) investors became very good at buying other companies and selling their assets. One of the ways that they did this was through the use of “junk bonds.” A “bond” is a piece of paper that one buys for a certain amount of money and then, one year or more in the future, gets that money back, plus some additional money. Companies “issue” (give out) bonds as a way to get people to lend money to them. A “junk bond” is a bond that has a very high “yield” (financial return, the amount of interest that can be earned on an investment), but is also very risky. The person who holds a junk bond might not get their money back if the company that issued the bond does poorly.
Many people believe that corporate raids and the use of junk bonds are unfair, because they close businesses and cause “unemployment” (not enough jobs for everyone who wants to work).
Comprehension Answers
1 - c
2 - c