= 0369
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 369: Going to Happy Hour.
This is English as a Second Language Podcast episode 369. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. You can download a Learning Guide for this episode that contains all of the vocabulary, definitions, sample sentences using those new vocabulary words, additional explanations, cultural notes, comprehension checks, and a complete transcript of everything we say on this episode.
This episode is called “Going to Happy Hour.” “Happy hour” is a period of one to two hours, sometimes three hours, normally after work. So, between 4:00 and 7:00 or 5:00 and 8:00 at night where bars and restaurants often offer cheap drinks and cheap food to get people to come after their work and have a drink and eat. Let’s get started.
[start of dialogue]
Gary: Hey, over here. I’m glad you could make it. This place has a great happy hour. Let me get the waitress, Brenda, so we can order our drinks.
Shanise: Hi, Gary. You sound like a regular. Do you come here a lot?
Gary: Yeah, I like stopping by on my way home now and then to wind down.
Shanise: Is there another barstool?
Gary: Oh, sorry. Let me get another one for you. Have a seat. What will you have?
Shanise: I’ll have a scotch, straight up. I usually don’t drink very much. Alcohol sometimes doesn’t agree with me. I’ve had a tough day, though, and I need to loosen up.
Gary: Okay, one scotch coming up. Here comes the waitress. Okay, that’s one scotch for Shanise and a draft beer for me. On second thought, bring a pitcher of the draft beer, would you? Thanks, Brenda.
Shanise: I’m starving. The sign outside says that they have all-you-can-eat appetizers during happy hour. Is that right?
Gary: Right you are, and they have specials on everything on their menu.
Shanise: I don’t usually go to happy hours, but I like this place. I’m glad you invited me to come.
Gary: Would I steer you wrong? Now let’s get some grub.
[end of dialogue]
Our dialogue begins with Gary, at a bar somewhere, saying to Shanise, “Hey, over here.” He’s getting her attention; he’s already at the bar and she is coming into the bar. Gary says, “I’m glad you could make it (I’m happy you could be here). This place has a great happy hour.” A “happy hour” is a period of time usually for a few hours after work when bars have lower prices on their drinks and food. Gary says, “Let me get the waitress, Brenda, so we can order our drinks.” Gary knows the name of the waitress, so he probably goes to the bar a lot.
Shanise says, “Hi, Gary. You sound like a regular.” A “regular,” here, is a noun to refer to a person that goes to a restaurant, a bar, or a store very frequently and the people who work there know that person – they know his or her name. You’re a regular at a certain restaurant, for example, would mean that you go to that restaurant a lot; they know who you are. My wife and I go to certain restaurants here in Los Angeles and the waitress knows who we are, she even knows what we want to order – “the usual,” you would say, meaning what I normally get: “I’ll have the usual.”
Shanise says to Gary, “Do you come here a lot?” Obviously he does – Gary likes to drink! Gary says, “Yeah, I like stopping by on my way home now and then to wind down.” “To stop by somewhere” means to go to a place for a short period of time, usually because you are on your way to another place. So I’m going to the store, but I’m going to stop by at the pharmacy to pick up some drugs. Gary says that he likes to stop by at this bar on his “way home,” meaning when he is driving from work to home, “now and then,” meaning sometimes – once in awhile. He likes to stop by to wind down. “To wind (wind) down” is a phrasal verb meaning to relax, especially at the end of a long day of work. Notice that W-I-N-D can also be pronounced “wind.” When it is pronounced “wind” instead of “wind,” it’s a noun referring to air that moves quickly.
Shanise then says, “Is there another barstool?” A “barstool” (one word – barstool) is a tall seat, usually that has a cushion on the top for you to sit on, but it doesn’t have any what we would call “arms,” meaning there’s nothing on the side of the chair to put your arms on, and it doesn’t have a back, either. That’s a stool; a barstool is usually very tall. What is happening here is that Gary is sitting down and Shanise is standing up, and Shanise is asking for a place to sit; she wants a barstool.
Gary says, “Oh, sorry. Let me get another one for you,” another barstool. Then he says, “Have a seat,” which is what you say to someone when you are inviting them to sit down. “Have a seat. What will you have?” Gary asks. He’s asking what Shanise wants to drink: “What will you have?” Shanise says, “I’ll have a scotch, straight up.” “Scotch” is a type of alcohol. When you have your alcohol served to you “straight up,” we mean without any ice or any other alcohol or soda or other liquids mixed in. Whisky straight up would be just whisky, nothing else: no ice, no other alcohol, no other beverage.
Well, scotch is usually a pretty strong drink. Shanise orders a scotch straight up, which is not the most common drink for many women when they go to a bar, but Shanise says, “I usually don’t drink very much,” which I find hard to believe – difficult to believe if she’s ordering her scotch straight up! Shanise says, “Alcohol sometimes doesn’t agree with me.” When you talk about something “not agreeing with you,” we mean that it sometimes causes problems with your stomach; it sometimes makes you a little ill or sick. So, when a food or drink doesn’t agree with you, it can make you sick; that’s what you’re saying. Shanise says, “I’ve had a tough day, though, and I need to loosen up.” She doesn’t care about getting sick; she wants to have her scotch! So, she says she wants to “loosen up,” this is a phrasal verb meaning to relax, to become less stressed and more comfortable. Certainly, drinking scotch straight up will loosen Shanise up!
Gary says, “Okay, one scotch coming up.” “Coming up,” here, means it will be served very soon, in the very near future; it’s on its way. So, he tells the waitress to get Shanise her scotch. He says, “Here comes the waitress.” Then, Gary speaking to the waitress says, “Okay, that’s one scotch for Shanise and a draft beer for me.” “Draft (draft) beer” is beer that comes in a large container behind the bar, not from a bottle or a can. Draft beer is beer that a bar will have in a big case – a big container; we actually call it a “keg” (keg). That’s a big, almost like a barrel that holds the beer. The word “draft” has a couple of different meanings in English; take a look at our Learning Guide for some additional explanations.
So Gary orders a draft beer for himself. Then he says to the waitress, “On second thought,” meaning I’ve reconsidered and I want to change my mind. “On second thought, bring a pitcher of the draft beer.” A “pitcher” is a large container that is used to hold liquids. It usually has a handle on it, where you can hold it. You have beer and soda, sometimes, put in a pitcher; you can have milk in a pitcher, lemonade in a pitcher. Restaurants will sometimes put a whole pitcher of water or soda on your table so you can just pour more of the liquid into your glasses when you need it. Perhaps Gary should also get a pitcher of scotch for Shanise!
Shanise then says, “I’m starving (I’m very hungry). The sign outside says that they have all-you-can-eat appetizers.” Shanise is saying that there’s a sign outside the bar that says they have “all-you-can-eat,” meaning as much as you want to eat. Some American restaurants have all-you-can-eat food, and they put the food out and you can take as much as you want. Sometimes they have pizza, sometimes they have salad, many different kinds of all-you-can-eat. In addition to drinking a lot, apparently Shanise likes to eat a lot as well!
Gary says, “Right you are,” which means you are absolutely correct, you are right. “Right you are, and they have specials on everything on their menu.” A “special” is a lower than usual price on something. When you go to a restaurant, the waitress will often say to you, “Here are our specials for tonight” – here are some dishes that we don’t have, for example, on our menu, but they are available. Sometimes specials also have a lower price, and that’s what Gary is referring to here.
Shanise says, “I don’t usually go to happy hours (yeah, right!), but I like this place. I’m glad you invited me to come.” Gary says, “Would I steer you wrong?” “To steer (steer) someone wrong” means to mislead someone, to take them to a place that they will not like, or to tell something to them that they won’t like. Gary says, “Would I steer you wrong?” meaning I will not steer you wrong; I will take you to somewhere that you will like. Then he says, “Now let’s get some grub.” “Grub” (grub) is an informal word for food. You don’t hear it all that often anymore, but you will sometimes hear it; it’s an informal expression for food.
Now let’s listen to the dialogue again, this time at a normal speed.
[start of dialogue]
Gary: Hey, over here. I’m glad you could make it. This place has a great happy hour. Let me get the waitress, Brenda, so we can order our drinks.
Shanise: Hi, Gary. You sound like a regular. Do you come here a lot?
Gary: Yeah, I like stopping by on my way home now and then to wind down.
Shanise: Is there another barstool?
Gary: Oh, sorry. Let me get another one for you. Have a seat. What will you have?
Shanise: I’ll have a scotch, straight up. I usually don’t drink very much. Alcohol sometimes doesn’t agree with me. I’ve had a tough day, though, and I need to loosen up.
Gary: Okay, one scotch coming up. Here comes the waitress. Okay, that’s one scotch for Shanise and a draft beer for me. On second thought, bring a pitcher of the draft beer, would you? Thanks, Brenda.
Shanise: I’m starving. The sign outside says that they have all-you-can-eat appetizers during happy hour. Is that right?
Gary: Right you are, and they have specials on everything on their menu.
Shanise: I don’t usually go to happy hours, but I like this place. I’m glad you invited me to come.
Gary: Would I steer you wrong? Now let’s get some grub.
[end of dialogue]
The script for this episode was by a woman who never drinks scotch, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
happy hour – a period of time, usually for a few hours after work, when bars have lower prices and/or free food to attract customers
* There’s a little bar downtown that offers $2 beers during happy hour every day from 4:00-7:00.
regular – a person who is a frequent customer at a restaurant, bar, or store so that the people who work there know him or her
* My mother loves to shop. She’s such a regular at this store that the salespeople know her name!
to stop by – to go to a place for a short period of time because one was going to pass by it anyway on one’s way to another place
* Could you please stop by the supermarket on your way home and buy some milk and bread?
now and then – sometimes; occasionally; every once in a while, but not on a regular schedule
* Now and then they enjoy going out for fancy coffee drinks instead of making coffee at home.
to wind down – to relax, especially at the end of a long day or week
* Julie likes to wind down by listening to music and taking a long, hot bath.
barstool – a tall seat that has a cushion for one’s bottom, but nowhere to rest one’s back or arms
* Jeremiah leaned back in his barstool and almost fell off of it! I guess he forgot that there was no backrest.
straight up – without ice or any other liquids mixed into an alcoholic beverage
* Do you drink vodka straight up, or do you prefer to mix it with cranberry juice?
to loosen up – to relax; to become less stressed and more comfortable; to stop worrying about something
* A good back massage is a great way to loosen up after a long week at work.
coming up – to be served very soon in the future; to be on its way
* The waitress said, “Two orders of strawberry pancakes, coming up.”
to not drink – to not drink alcohol
* Ollie’s mother was an alcoholic, so he doesn’t drink because he is scared that the same thing might happen to him.
to agree with (someone) – for a food or drink to settle properly in one’s stomach so that one does not feel sick after eating or drinking it
* Spicy food doesn’t agree with him, so he rarely goes to Indian or Mexican restaurants.
draft – beer that comes from a large container behind the bar, not from a bottle or can
* Do you prefer draft beer or beer in a can?
pitcher – a large container that is used to hold liquids and has a handle and spout for easily pouring the liquid into glasses that people can drink from
* Wynona makes a pitcher of delicious, sweet lemonade on hot summer days.
all-you-can-eat – as much as one wants to eat; an offer at some restaurants and bars where customers can pay a single price and eat as much of something as they want to without paying more
* Troy went to an $8.99 all-you-can-eat pizza restaurant, but then he got sick from eating too much.
special – a lower-than-usual price on something; a special offer from a restaurant or store; a sale
* Our store is having a special where you can buy one sweater and get a second sweater for free.
to steer (someone) wrong – to mislead someone; to take someone to a place that he or she won’t like, or to tell someone to do something that he or she won’t like
* Keith has never steered us wrong in the past, so if he thinks that the investment is a good idea, I think we should listen to him.
grub – an informal word for food; things that can be eaten
* Earl was very hungry when he came home from work, so he quickly opened the refrigerator, looking for some grub.
Comprehension Questions
1. Why does Gary stop by the bar now and then?
a) To relax after work.
b) To avoid the windy weather.
c) To be a regular.
2. Which of these is a type of grub?
a) Scotch, straight up.
b) A pitcher of draft beer.
c) All-you-can-eat appetizers.
Answers at bottom.
What Else Does It Mean?
regular
The word “regular,” in this podcast, means a person who is a frequent customer at a restaurant, bar, or store so that the people who work there know him or her: “Zede is a regular at the coffee shop because she goes there every morning on her way to work.” The word “regular” also means normal, standard, or not unusual: “Is that his regular way of talking, or is he speaking with an accent to be funny?” Or, “Pete is too tall to shop in regular stores, so he has to go to special big-and-tall stores.” “Regular” can also mean happening often, repeatedly and on a set schedule: “You can make your heart healthier through regular physical activity for at least 30 minutes every day.”
draft
In this podcast, the word “draft” means beer that comes from a large container behind the bar, not from a bottle or can: “Many people think that draft beer tastes better than bottled beer.” The word “draft” also refers to the practice of the U.S. government requiring young men to serve in the military during a war: “During the Vietnam War, some young Americans moved to Canada to avoid the draft.” A “draft” can also be an early version of something that one has written, which needs to be edited and improved before the writing is finished: “Check your first draft for spelling and grammar errors.” A “final draft” is the final, corrected piece of writing: “The teacher will be angry if she sees errors in your final draft.”
Culture Note
American English has many “terms” (technical words) and phrases to describe people who do and don’t drink alcohol. For example, someone who drinks a lot might be called a a “drunkard” or a “lush” informally. Someone who doesn’t drink alcohol at all is known as a “tea-totaler,” even if he or she doesn’t drink tea.
A person who “can’t handle his or her alcohol” is someone who gets drunk very quickly and loses control after just one or two drinks. Sometimes people say that someone “can’t handle his or her booze,” where “booze” is an informal word for alcohol.
An “alcoholic” is a person who is addicted to alcohol and cannot stop drinking. Sometimes these people try to stop drinking. When they are not drinking, people say that they are “on the wagon.” If they have a bad day and begin to drink again, then people say that they have “fallen off the wagon.” A “wagon” is an old-fashioned wooden structure on wheels that is pulled by horses to move people and things. When an alcoholic permanently stops drinking, her or she is known as a “recovering alcoholic” and often says this to other people so that they will understand why he or she is not drinking.
When groups of friends go to a bar together, usually one of them will not drink alcohol, instead choosing coffee or soda. This person is known as the “designated driver” and is the person who will drive everyone else home at the end of the night. That way, there aren’t any problems with “drunk driving,” where someone drives a car dangerously because he or she is being influenced by alcohol.
Comprehension Answers
1 - a
2 - c