= 0372
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast episode 372: A Bully at Work.
This is English as a Second Language Podcast episode 372. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. The Learning Guide is an 8 to 10 page guide we publish for all of our current episodes that contains all of the vocabulary words, definitions, sample sentences, additional definitions that we don’t talk about on the audio portion of the podcast, cultural notes, comprehension checks, and a complete transcript of this episode.
This episode is called “A Bully at Work.” It’s a dialogue between Wanda and Dana about a problem they’re having at their job. Let’s get started.
[start of dialogue]
Wanda: I can’t take it anymore. I try to put up with Robert, but I’ve had enough!
Dana: I’m not surprised. That guy is a big bully and it’s time somebody stood up to him. What has he done now?
Wanda: This was the last straw. We’re both managers and we’re supposed to work together, but Robert looks for every opportunity to put me down in front of our employees. This morning, I presented an idea about upgrading our computer equipment and he jumped down my throat.
Dana: What did he do?
Wanda: He said that the idea was stupid and that he couldn’t understand how anyone could propose it. He said this in front of everybody. I was too stunned to respond, so I just stood there.
Dana: That’s totally inappropriate and unprofessional.
Wanda: He’s arrogant to everybody, but especially to me. He always says he’s just being honest when he makes a biting remark, but I’m realizing that that’s just his excuse to be rude. He treats everyone with contempt. I really don’t know what to do.
Dana: I know people like Robert. They’re so insecure that they have to belittle everyone else to make themselves feel better. They have really poor social skills and don’t know how to have a conversation or to disagree without being a jerk.
Wanda: That may be, but what should I do about him?
Dana: There’s only one way to handle a bully.
Wanda: How?
Dana: You have to call his bluff. If he criticizes your plan, ask him to back it up with evidence or a specific reason. If you disagree with him, keep your cool, but tell him why. Most bullies back down when someone stands up to them.
Wanda: Okay, it’s worth a try. I’ve been trying to keep calm and maintain a professional atmosphere in the office, so I haven’t confronted him, but I will if you think it’ll help.
Dana: I do. And if that doesn’t work, tell him to act his age, not his shoe size!
[end of dialogue]
Wanda begins by saying “I can’t take it anymore.” This is similar to saying “I can’t stand it,” which means I can no longer tolerate this; I can’t just stay here or sit here, it’s bothering me too much. “I can’t take it anymore,” she says, “I try to put up with Robert, but I’ve had enough!” “To put up with someone” means to tolerate someone, to take something without complaining. It’s the opposite of “I can’t take it anymore.” “I put up with you,” meaning I tolerate you, I don’t let it bother me.
Dana says, “I’m not surprised. That guy is a big bully.” A “bully” is a person who uses violence – physical violence or verbal (spoken) violence to prove his or her strength or power. It’s a person who’s mean to other people because they try to control them using this kind of violence. Normally we use the term “bully” in describing a child, for example, who tries to hit or control another child by being mean to them. But here, Dana is talking about an adult who’s a bully.
Dana says, “it’s time somebody stood up to him.” “To stand up to someone” means not to allow another person to continue, in this case, to be mean to you, not to be afraid to tell someone that he or she is not acting appropriately. You have to stand up to a bully; you have to tell them what they are doing is wrong. Dana says, “What has he done now?” What has he done to make her angry?
Wanda says, “This was the last straw.” When we say something is “the last straw” (straw), we mean it’s the last in a series of bad events, when someone decides that he or she is not going to let this situation continue. When you can no longer tolerate or put up with a situation, you say, “that’s the last straw,” meaning it’s the last negative thing that’s going to happen, now I’m going to change the situation.
Wanda says, “We’re both managers and we’re supposed to work together, but Robert looks for every opportunity to put me down in front of our employees.” “To put someone down” is another phrasal verb meaning to insult someone, to make someone feel unimportant or of less value. “To put down” has a couple of different meanings; take a look at our Learning Guide for some additional explanations.
Wanda continues, “This morning, I presented an idea about upgrading our computer equipment and he (Robert) jumped down my throat.” “To jump down someone’s throat” means to attack someone verbally, to yell at somebody for something that they said or did.
Dana asks, “What did he do?” And Wanda says, “He said that the idea was stupid and that he couldn’t understand how anyone could propose it. He said this in front of everybody.” Wanda says, “I was too stunned to respond, so I just stood there.” “To be stunned” means to be surprised, to be shocked, perhaps to be scared.
Dana says, “That’s totally inappropriate and unprofessional,” what Robert did. Wanda says Robert’s arrogant to everybody. “To be arrogant” means to think that you are more important than everyone else, that you are better than everyone else. Wanda says, “He always says he’s just being honest when he makes a biting remark.” A “biting remark” is a hurtful or cruel comment that you make to someone. “Biting” has a couple of different meanings in English; once again, look at our Learning Guide for some additional explanations of that word. Wanda says that she realizes that he’s just making excuses for being rude when he says he’s being honest, “He treats everyone with contempt.” “Contempt” means disrespect, a strong dislike of another person.
Dana says, “I know people like Robert. They’re so insecure that they have to belittle everyone else to make themselves feel better.” “To be insecure” means to be not secure, to be not confident about who you are. “To belittle” means to make someone else feel unimportant, to tell someone that he or she is less important than you are. Normally, it’s something that would happen in front of other people, but not always. Dana says that people like Robert have very poor social skills. “Social skills” refers to the ability to communicate with other people, to work effectively with other people in a friendly way. We say someone lacks social skills or they have poor social skills, we mean they don’t get along with other people, they don’t know how to have a friendly conversation with other people.
Wanda says, “That may be, but what should I do about him?” Dana says, “There’s only one way to handle (or take care of) a bully.” Wanda says, “How?” And Dana says, “You have to call his bluff.” “To call someone’s bluff” (bluff) means to make someone prove what they are saying is true, to force somebody to prove that he or she will really do what he or she says they will do. That is “to call someone’s bluff.” A “bluff” is when you say something to someone and it’s not necessarily true, in fact it usually isn’t true, but you are trying to make them believe it. Someone may say to you “You’re bluffing,” meaning you are lying, you are not telling the truth; you’re trying to make me believe something that isn’t true so that you can have an advantage over me.
Dana says, “You have to call his bluff. If he criticizes your plan, ask him to back it up with evidence.” “To back something up” means to provide evidence to support something, to prove something. Someone says to you “Back it up,” they’re saying give me evidence that this is true. “If you disagree with him,” Dana says, “keep your cool, but tell him why (you disagree).” “To keep your cool” means to stay calm, to remain relaxed and unconcerned: “The beautiful woman walked in the door, but I kept my cool.” Then she sat down and started talking to another man, so it didn’t really matter! But I kept my cool – I didn’t get excited, I stayed calm.
Dana says, “Most bullies back down when someone stands up to them.” “To back down” means to walk away from a challenge, or to give in – to give up. He’s going to back down; he’s going to say, “Okay, you win.” They’re not going to continue the fight or the argument.
Wanda says, “it’s worth a try. I’ve been trying to keep calm and maintain a professional atmosphere in the office, so I haven’t confronted him” – I haven’t said something negative to him or told him that he was wrong. “But,” she says, “I will if you think it will help. Dana says, “I do. And if that doesn’t work, tell him to act his age, not his shoe size!” “To act your age, and not your shoe size” is an expression that children sometimes use; it means act like an adult, not like a child. In the United States, the shoe sizes are usually numbers between 1 and maybe 12 or 15. So, your shoe size, even as an adult, will not be very high. My shoe size is an eight, but I don’t want to act like I’m eight years old, my shoe size. I want to act my real age, which is 21!
Now let’s listen to the dialogue again, this time at a normal speed.
[start of dialogue]
Wanda: I can’t take it anymore. I try to put up with Robert, but I’ve had enough!
Dana: I’m not surprised. That guy is a big bully and it’s time somebody stood up to him. What has he done now?
Wanda: This was the last straw. We’re both managers and we’re supposed to work together, but Robert looks for every opportunity to put me down in front of our employees. This morning, I presented an idea about upgrading our computer equipment and he jumped down my throat.
Dana: What did he do?
Wanda: He said that the idea was stupid and that he couldn’t understand how anyone could propose it. He said this in front of everybody. I was too stunned to respond, so I just stood there.
Dana: That’s totally inappropriate and unprofessional.
Wanda: He’s arrogant to everybody, but especially to me. He always says he’s just being honest when he makes a biting remark, but I’m realizing that that’s just his excuse to be rude. He treats everyone with contempt. I really don’t know what to do.
Dana: I know people like Robert. They’re so insecure that they have to belittle everyone else to make themselves feel better. They have really poor social skills and don’t know how to have a conversation or to disagree without being a jerk.
Wanda: That may be, but what should I do about him?
Dana: There’s only one way to handle a bully.
Wanda: How?
Dana: You have to call his bluff. If he criticizes your plan, ask him to back it up with evidence or a specific reason. If you disagree with him, keep your cool, but tell him why. Most bullies back down when someone stands up to them.
Wanda: Okay, it’s worth a try. I’ve been trying to keep calm and maintain a professional atmosphere in the office, so I haven’t confronted him, but I will if you think it’ll help.
Dana: I do. And if that doesn’t work, tell him to act his age, not his shoe size!
[end of dialogue]
The script for this episode was written by a woman with wonderful social skills, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
to put up with – to take without complaining; to endure; to tolerate
* Why do you put up with the child’s bad behavior?
bully – a person who uses verbal (spoken) or physical violence to prove his/her strength, power, or position over others; a person who is mean to others
* He was considered a bully in high school because he would make the weaker students give him their lunch money.
to stand up to – to not allow another person to continue to be mean to oneself anymore; to not be afraid to tell someone when he/she is acting inappropriately
* They stood up to the gang by forming a neighborhood watch program.
the last straw – the last in a series of bad events where a person decides that he or she will not let the bad events happen anymore; to not be able to stand a certain situation any longer
* When she came home drunk for the third time in four nights, it was the last straw for her boyfriend and he broke up with her.
to put (someone) down – to insult someone; to make someone feel unimportant or of less value
* The husband put his wife down when he told her in front of their friends that she wasn’t very smart.
to jump down (someone’s/one’s) throat – to verbally attack someone; to yell at someone
* The boss jumped down my throat when I arrived late to work today.
stunned – surprised; shocked; scared
* The actress was stunned when she found out she had won an award.
arrogant – believing that one is more important than all other people; thinking that one is more talented than other people.
* The soccer player is so arrogant that he will not talk to or take pictures with any fans.
biting – hurtful; cruel
* The teacher’s biting comment to her students about their lack of intelligence made them cry.
contempt – strong dislike; disrespect; scorn
* John felt contempt for his father, who abandoned his family when John was only a child.
insecure – not confident; disliking a part of your oneself
* Do you believe that most women feel insecure about their bodies?
to belittle – to make someone feel unimportant; to tell someone that he or she is less important
* The older child belittled her younger brother because she was jealous of him.
social skills – everyday communication skills with other people; one’s ability to communicate and work effectively with other people in a friendly manner
* This school is very good at teaching academic subjects, but the students graduate without good social skills.
to call (someone’s) bluff – to make someone prove that what they are saying is true; to force someone else prove that he/she will really do what he/she says he/she will do
* She called her son’s bluff when she asked him to prove that he had done his homework.
to back it up – to prove it; to provide evidence to support something
* He backed up his claim that he was the best boxer in the world by defeating the current champion.
to keep (one’s) cool – to stay calm; to remain relaxed and unconcerned
* The girl kept her cool even though the other students called her names.
to back down – to give in; to walk away from a challenge
* The driver backed down from the argument he was having with the police officer.
to act (one’s) age, and not (one’s) shoe size – to act one’s level of maturity; to act like an adult instead of a child
* When will you act your age and not your shoe size and stop fighting with the neighborhood children?
Comprehension Questions
1. What do Wanda and Dana think of Robert?
a) They think he is a good manager.
b) They think that he has great social skills.
c) They think that he is a jerk.
2. How does Dana think Wanda should fix her problem with Robert?
a) By keeping quiet and not saying anything to him.
b) By making biting remarks about him in front of the other employees.
c) By calling his bluff and standing up to him.
Answers at bottom.
What Else Does It Mean?
to put (someone) down
The expression “to put (someone) down,” in this podcast, means to insult someone or to make someone feel unimportant: “She put him down by saying that his guitar playing was the worst noise she had ever heard.” The expression “to put (someone) down” can also mean to set someone or something down onto a surface: “She lifted the baby out of the crib and put him down on the floor so that he could crawl around.” “To put down” can also mean to cause a person’s or animal’s death: “The vet put the dog down because it was so old that it couldn’t walk, see, or hear.” Finally, “to put down” can mean to write down: “Put down on our list that we need to buy bread, sugar, and cereal when we go to the grocery store.”
biting
In this podcast, the word “biting” means hurtful or cruel: “When I told my brother about my promotion at work, he only made a biting remark that I would have been promoted earlier if I weren’t so lazy.” “Biting” also means to cause a stinging or painful sensation, usual related to the weather: “When the wind blows in the winter it can be biting cold.” The word “biting” is also used to describe certain insects that can wound a person’s skin with their fangs (teeth) or with a sting: “There are many different kinds of biting flies in Alaska.” Finally, the verb “to bite” means to pierce with one’s teeth: “She bit into the apple.”
Culture Note
In the U.S., if you want to become a member of a group, you may need “to undergo” (to take part in) an activity called “hazing.” Hazing is an activity someone must perform so that he/she can either “become a member” (to be part of a group) of a group or “to retain” (to keep, to renew) their current membership with a group. Hazing usually “humiliates” (to lower the pride or self respect of someone) or causes physical or emotional “harm” (pain, danger) to the person being hazed.
Some people confuse the terms bullying and hazing. With bullying, usually a group is trying to keep a person from entering their group. With hazing, a person must pass certain “challenges” (tests of one’s abilities) in order to become a part of the group. Hazing happens most often in sports in high school and colleges. The athletes are “initiated” (brought into a group with an activity) to their new teams by “existing” (someone who is already a member of the group) team members. Often times those hazed by a group are hurt physically in some way, but usually they are hurt more emotionally. University social groups called fraternities (for men) and sororities (for women) also use some type of hazing to select its members.
There are a number of different ways a group will initiate a new member. The group may constantly “insult” (make many unkind remarks) the person; the group may cause the person not to be able to sleep for an “extended” (long) period of time; the group may physically “attack” (hit, punch, slap) the person; the group may make the person humiliate or embarrass themselves in “public“ (in front of other people); the group may make the person touch or eat a gross “substance“ (material); or the group may make the person drink a large amount of alcohol. Many times the person has to perform the acts the group wants him/her to perform even if he/she does not want to perform the activities. Some schools have tried to stop hazing because of the damage it causes, but it is often difficult to control the behavior of these types of “close-knit” (socially close) groups.
Comprehension Answers
1 - c
2 - c