= 0392
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 392: An Untrustworthy Co-worker.
This is English as a Second Language Podcast episode 392. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You can go there and download a Learning Guide for this episode that contains additional information to help you improve your English even faster.
This episode is called “An Untrustworthy Co-worker.” It’s a dialogue between Vicky and Gerard talking about someone they work with who cannot be trusted. Let’s get started.
[start of dialogue]
Vicky: Did I imagine it or did you just give Gavin the cold shoulder?
Gerard: You didn’t imagine it. I’m not too happy with him.
Vicky: Why? What did he do?
Gerard: He’s two-faced, that’s why. Last week, he told me he was going to put in a good word for me with the manager for a promotion.
Vicky: So that sounds like a nice thing to do.
Gerard: I thought so, too. But as it turns out, I heard from Elanda that he was bad-mouthing me behind my back.
Vicky: Are you sure?
Gerard: I’m sure. He told Elanda that he thought I had gone pretty far in the company for someone who had dropped out of college. That’s a backhanded compliment, if I’ve ever heard one.
Vicky: That sounds pretty nasty. At least the manager wasn’t around.
Gerard: She wasn’t, but who’s to say what he told her behind my back?
Vicky: You know, the manager is pretty sharp and nothing gets by her. I’m sure she’ll put two and two together and realize that Gavin isn’t trustworthy.
Gerard: I hope so. With friends like him, who needs enemies!
[end of dialogue]
Vicky begins our dialogue by asking Gerard, “Did I imagine it or did you just give Gavin the cold shoulder?” She’s saying “Did I imagine it,” meaning did I think that something is true but it isn’t – is it something that I made up? This is a common way of asking someone a question about something that you may find surprising that happened, but you’re not really sure, so you need to ask someone else. Vicky is asking Gerard if he gave Gavin the cold shoulder. The expression “the cold shoulder” means not being very nice to someone, not being friendly. “I gave him the cold shoulder” – I wasn’t very friendly to him.
Gerard says, “You didn’t imagine it,” meaning yes, that is what happened. “I’m not too happy with him,” he says. Vicky says, “Why? What did he do?” Gerard says, “He’s two-faced, that’s why.” Someone who is “two-faced” is a person who says one thing but does something else, or says something to one person and then tells a different person a different story. It’s an insulting term, to call someone “two-faced.” Gerard says last week, Gavin told him he was going to put in a good word for him with the manager for a promotion. To “put in a good word for someone” means to say something good about someone else, usually to help that person succeed – to become more successful. So if, for example, you are looking for a job and I work at a company that has some job openings (jobs that we are trying to hire people for), I may say, “I’ll put in a good word for you with my boss.” I will tell him good things about you so that maybe he will hire you. Gavin said he would put in a good word for Gerard with the manager for a promotion. A “promotion” is when you get a better job in your company. There are a couple of different meanings of “promotion,” take a look at our Learning Guide for some additional explanations.
Vicky says, “So that sounds like a nice thing to do.” Gerard says, “I thought so, too,” meaning that’s what I was thinking. “But as it turns out,” meaning the actual result was that he heard from Elanda that Gavin was bad-mouthing him behind his back. To “bad-mouth” someone means to say bad things about someone, to say bad things about someone often when they are not there. “Behind one’s back” means without your knowledge; usually it’s a negative thing that someone else does to you that you don’t know about right away, or that they don’t tell you about. For example: “My friend went behind his wife’s back and bought a new car.” He didn’t even tell her he was going to buy the car; he went behind her back. Well, Gerard is saying that Gavin is bad-mouthing him (saying bad things about him) when he’s not there – behind his back.
Vicky says, “Are you sure?” Gerard says, “I’m sure. He told Elanda that he thought I had gone pretty far in the company for someone who had dropped out of college.” To “drop out of college” means to leave college before you finish – before you graduate. Gerard says, “That’s a backhanded compliment, if I’ve ever heard one.” A “backhanded compliment” is when you say something about someone that seems to be nice but it’s actually not nice, it’s mean or unkind; when you say something that seems to be positive, but if you listen closely, it’s a negative. For example, you say to your girlfriend, “You look so much better today.” This is a backhanded compliment because what you’re really saying is that you didn’t look very good yesterday. Well, Gerard is saying that Gavin told Elanda that he, Gerard, had “gone far” in the company – had made a lot of progress in the company – even though he didn’t have a college education. So, he’s really sort of criticizing Gerard for not finishing college, that’s why it’s a backhanded compliment.
Vicky says, “That sounds pretty nasty.” Something that is “nasty” (nasty) means it’s mean, it’s cruel, it’s not nice. Vicky says, “At least the manager wasn’t around,” meaning at least the manager didn’t hear this. Gerard says “She wasn’t, but who’s to say what he told her behind my back?” “Who’s to say” is a phrase we use to mean that no one knows something, that it is impossible to know something, or that we can’t answer the question very easily. We don’t know what Gavin said to the manager, that’s why Gerard says “who’s to say what he told her behind my back.” We don’t know what Gavin said about Gerard to the manager.
Vicky says, “You know, the manager is pretty sharp and nothing gets by her.” When you say someone is someone is “pretty sharp,” here it means they’re intelligent, they’re smart, they’re quick to understand something – all things that I am not, for example! “Sharp” has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations. When we say “nothing gets by” someone, we mean nothing fools them, nothing tricks them. “Nothing gets by me.” That means I understand everything; I can’t be tricked.
Vicky says, “I’m sure (the manager) put two and two together and realized that Gavin isn’t trustworthy.” To “put two and two together” is an expression that means to understand something when you don’t have all of the information, but you’re smart enough – you’re sharp enough – to understand the entire situation even though you don’t have all of the information. You figure it out. Vicky says that the manager will put two and two together and realize that Gavin isn’t trustworthy. To be “trustworthy” means that you are reliable, you are dependable, people can trust you.
Finally, Gerard says, “I hope so. With friends like him, who needs enemies!” This is an old expression that is used to show that a person who you thought was a friend is actually not a friend. Someone says that he is your friend, but then does something to hurt you. “With friends like these, who needs enemies!” In other words, I don’t need enemies because the people who say they are my friends are already, really, my enemies.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Vicky: Did I imagine it or did you just give Gavin the cold shoulder?
Gerard: You didn’t imagine it. I’m not too happy with him.
Vicky: Why? What did he do?
Gerard: He’s two-faced, that’s why. Last week, he told me he was going to put in a good word for me with the manager for a promotion.
Vicky: So that sounds like a nice thing to do.
Gerard: I thought so, too. But as it turns out, I heard from Elanda that he was bad-mouthing me behind my back.
Vicky: Are you sure?
Gerard: I’m sure. He told Elanda that he thought I had gone pretty far in the company for someone who had dropped out of college. That’s a backhanded compliment, if I’ve ever heard one.
Vicky: That sounds pretty nasty. At least the manager wasn’t around.
Gerard: She wasn’t, but who’s to say what he told her behind my back?
Vicky: You know, the manager is pretty sharp and nothing gets by her. I’m sure she’ll put two and two together and realize that Gavin isn’t trustworthy.
Gerard: I hope so. With friends like him, who needs enemies!
[end of dialogue]
The script for this episode was written by the very sharp Dr. Lucy Tse. Nothing gets by her!
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
to imagine – to think about how something could or might be, but isn’t; to pretend
* Many little girls spend their time imagining that they are princesses.
the cold shoulder – unfriendliness; coldness; not being very nice to someone
* After Henrietta said all those mean things, her neighbors started giving her the cold shoulder.
two-faced – a person who says one thing but does something else; a person whose words and actions are inconsistent, or who treats people inconsistently; a person who says nice things to a person, but then says bad things about him or her to other people
* Jake is so two-faced! He told Mary that she was his best friend, but then he told everyone else that he doesn’t even like her.
to put in a good word for (someone) – to say something good about someone, usually to help that person be successful with something
* If you apply for the job at my company, I’ll put in a good word for you with my boss.
promotion – an upward movement in a company from a job with less power and lower pay to a job with more power and higher pay
* Did you hear about Jill’s promotion from senior marketing manager to vice-president of marketing?
bad-mouth – to say bad things about someone; to say bad things about someone to other people when that person is not there
* Fely is always bad-mouthing her teacher, saying that he is unfair with his students.
behind (one’s) back – without one’s knowledge; when one cannot see or hear what another person is doing
* Her husband spent more than $1,500 on a new TV behind her back, not even asking her if she thought it was a good idea.
backhanded compliment – something that seems to be nice, but is actually mean or unkind; something that seems to be positive but is actually negative
* Randy told his sister, “You look so much better today!” It was a backhanded compliment, because he really meant that she didn’t look very nice on the other days.
nasty – unkind; mean; cruel; not nice
* Jesse had a nasty smile on her face when she heard that her co-worker had lost her job.
who’s to say…? – a phrase used to mean that no one knows something, that it is impossible to know something, or that something cannot be answered clearly
* People think that modern technology is very advanced, but who’s to say what will be created in the next 10 years?
sharp – intelligent; smart; quick to understand something
* Those kids are really sharp. They’re doing well in school and I’m sure they’ll all get college scholarships.
to get by (someone) – to trick someone; to fool someone; to not be understood by someone
* When Zack was younger, if he coughed, his mom thought he was sick and kept him home from school, but he could never get by his dad with that trick.
to put two and two together – to understand something when one doesn’t have all the information, but is able to take small pieces of information and use them together to find out the truth
* No one told her the business was going to close, but she saw how nervous the owner was and saw that the store was losing customers, so she put two and two together.
trustworthy – one who can be trusted; reliable; dependable
* Olivia is very trustworthy, so if she says she’ll do something, you can be sure that she will do it.
With friends like (someone), who needs enemies – a phrase used to show that a person whom one thought was a friend is actually very unfriendly and mean
* When Fran stole Jaycie’s boyfriend, she thought, “With friends like her, who needs enemies.”
Comprehension Questions
1. What did Gerard do to Gavin?
a) He said bad things about Gavin.
b) He put cold water on Gavin’s shoulder.
c) He wasn’t friendly toward Gavin.
2. According to Vicky, which of these words could be used to describe the manager?
a) Intelligent
b) Mean
c) Reliable
Answers at bottom.
What Else Does It Mean?
promotion
The word “promotion,” in this podcast, means upward movement in a company from a job with less power and lower pay to a job with more power and higher pay: “She’s been working in the same position for almost five years, so it’s time for her to ask for a promotion.” A “promotion” is also a campaign or a special offer to try to sell more of something: “The store is having a great two-for-one promotion on those books this week.” Or, “That gym is offering a free one-month membership promotion as a way to get more new members.” Finally, the word “promotion” can mean an activity or effort to make something bigger or more popular: “The city’s promotion of energy conservation has reduced energy use by 10%.”
sharp
In this podcast, the word “sharp” means intelligent, smart, and quick to understand something: “Camilo is really sharp and always understands things immediately.” The word “sharp” also means having a pointed end or edge that might be used to cut things: “Be careful! That knife is very sharp.” When talking about food, the word “sharp” can be used to describe a very strong flavor: “Should I buy the regular cheddar cheese or the extra-sharp one?” The word “sharp” is also used to describe sounds that are very sudden and loud, but do not last for very long: “Everyone turned toward the sharp cry for help.” Finally, a “sharp turn” or a “sharp left/right” means a sudden and large turn in one direction: “After you pass the stop sign, take a sharp left onto Riverside Drive.”
Culture Note
One of the “major” (most significant or important) “challenges” (something that is difficult to do) of working in an office is learning to work with one’s co-workers. Many people “struggle” (have a difficult time) working with untrustworthy co-workers. Fortunately, people can do many things to make it easier to work with an untrustworthy co-worker and to “protect” themselves (do something to make a bad situation less bad) in this situation.
First, if you know that you are working with an untrustworthy co-worker, try to “document everything in writing” (make sure that everything is written down, instead of just being said). If you have written “records” (written documents) about projects and responsibilities, then you’re protecting yourself, because the untrustworthy co-worker cannot say that he or she didn’t know about something. You can prove that he or she saw the written document.
If your untrustworthy co-worker “has access” (can get or see) to your work documents, make sure that you keep another copy. That way, if the untrustworthy co-worker makes changes or says that the document is his or her own work, you can pull out your own copy of the document to show the truth. Protect your own documents by locking your desk and using passwords for electronic files.
Never share information about your personal life with an untrustworthy co-worker. He or she might use it to “embarrass” you (make you feel uncomfortable) or to make you seem unprofessional later. Instead, make sure that your conversations with the untrustworthy co-worker are professional and “succinct” (short), without any unnecessary information.
When you do all these things, working with an untrustworthy co-worker is still unpleasant, but your job will be more “secure” (safer).
Comprehension Answers
1 - c
2 - a