


= Sex.And.The.City s01-12
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''
My friend, Miranda, was dating Thomas John Anderson, +
an up and coming New York playwright. +
Oh, God! +
That was wonderful. +
Things were going great except for one thing. +
I'll be right back. +
Immediately after sex, +
he'd hop out of bed and shower. +
Oh, God! +
Wow! +
Be right back. +
Night after night, it was the same thing. +
Oh, God! +
-I'll be right-- -Yeah. +
She decided to confront Thomas John Anderson +
as soon as he dried off. +
So, what's with the showers? +
What do you mean? +
You always get up and shower right after we're done. +
I'm starting to feel like it's me. +
Oh, no, no, no, it's not you. +
It's just... +
What? +
Just a habit I have. +
Growing up, the nuns told us that sex was a sin, +
so I just got into the habit of taking a shower after I... +
you know, came. +
Oh, the nuns. +
Miranda suddenly realized she was dating "Catholic guy." +
So you think the water serves as +
a retro baptism kind of thing? +
Beats me, if I'd known he was Catholic, +
I never would've gone out with him in the first place. +
They should make them wear a sign. +
Single people in New York +
rarely ask about their dates' religious backgrounds +
for the same reason they don't ask +
the number of former sex partners, too scary. +
I mean, he's a rational, logical guy +
in every respect but this. +
Clean, you forgot clean. He's a clean guy. +
Leave it to me to find the only religious guy +
still left in Manhattan. +
New York is a city filled with places to worship, +
but it recently dawned on me, +
the only time I ever heard anyone mention going into one +
was for a singles mixer. +
Are relationships the religion of the 90's? +
Having been raised in the church of "Be nice to people +
and don't talk with your mouth full," +
I decided to check out some more traditional religious types +
in their natural habitat. +
As I watched people leaving church, +
I was amazed at how they looked. +
Valentino, Escada, +
Oscar de la Renta. +
What is it about God and fashion +
that go so well together? +
And suddenly, there he was wearing Armani on Sunday... +
Mr. Big. +
I admit it was kind of a shock. +
Up until that moment, I thought he only believed in the Yankees. +
Well, hello there, church-goer. +
Hey... +
What are you doing here? +
Research. +
I'm doing a column on closet Presbyterians. +
You know any? +
Actually, I'm an atheist, +
but don't tell that to the minister. +
Who's the mystery woman? +
My mother. +
I take her to church every Sunday. +
Really? +
I'm so loving that. +
How come you never told me? +
Well, you write every Sunday, so... +
So, every Sunday... church. +
Right. +
You know, I've got 20 minutes before my racquetball game. +
Why don't we have a cup of coffee? +
Oh, I can't, I'm on deadline +
and this cappuccino just kicked in, so... +
So? +
Bye. +
God bless. +
It was one of those awkward relationship moments +
where you feel like you know nothing about +
the person you thought you knew everything about. +
He goes to church with his mother? +
-That can't be good. -Oh, don't listen to her. +
A man who cares about his mother makes a wonderful husband. +
I think it's sweet. +
Sure, all religions are sweet +
until you get to that shower after sex phase. +
Oh, my God, is he still doing that? +
Please, it's amazing he has any skin left. +
Well, have you tried taking a shower with him? +
No, I'm afraid he'll pull out garlic and a cross. +
So which church does his mother go to? +
Park Avenue Presbyterian. +
Good church. +
It's one of the best on the east side. +
What are you rating churches? +
Is there a Zagat guide for that? +
Four stars, great bread, +
disappointing wine selection. +
The thing is, I'm dying to meet his mother. +
Can you imagine? +
Getting on the good side of his mother +
is like closing the deal. +
Hey, I'm sorry I'm late. +
Well, it's about time. +
I just had a five hour lunch with James. +
Five hour lunches, I remember those. +
Ladies, I have an announcement. +
Please don't laugh. +
What? +
-I'm in love. -What? +
Samantha uttering those words to us +
was an event as unfathomable +
as Moses parting the Red Sea. +
It all started a couple of weeks ago +
on a particularly blah Wednesday night. +
Samantha decided to treat herself +
to a night of great music. +
I couldn't help but notice how you move to the music. +
It's beautiful. +
Well, I love jazz. +
That's pretty clear. +
Are you a musician? +
Yeah. +
Trapped in the body of a lawyer. +
Well, we won't tell anyone. +
May I join you? +
Sure. +
After they closed the jazz joint, +
they walked and talked for blocks. +
You have to at least try one of the glazed. +
It's a little bit of heaven. +
Mmm, heavenly. +
And I never thought I'd get there. +
Why not? +
An angel like you? +
And then Samantha did something +
rather shocking for a first date. +
She didn't ask him home. +
Thanks, James. +
I had a wonderful time. +
Can I see you again? +
I'd love that. +
And with that one touch, +
Samantha, who was never a believer in relationships, +
suddenly became a convert. +
I mean, I'd totally given up on the idea +
that you could actually talk to men. +
Hey, don't spread that around. +
Before James, all my conversations +
consisted of two sentences. +
"Give it to me" and "Go home." +
And I owe it all to Charlotte. +
Me? +
What did I do? +
All that bullshit you spout +
about not sleeping with men right away actually paid off. +
I mean, if I'd fucked James already, +
who knows where we'd be. +
Wait, you haven't had sex yet? +
Soon. +
You know, +
I think he's someone I could actually marry. +
Samantha, that's great. +
The idea that Samantha +
could possibly get married before she did, +
shook Charlotte's beliefs to the core. +
She took some drastic action. +
She made an appointment to see Noanie Stein, +
psychic to the stars, and a cosmic connection +
who lived in a brownstone +
between Central Park West and Columbus. +
Is this you and Madonna? +
Yeah, we go to the same kabbalah class. +
Now... +
Pick three cards, +
face down with your left hand. +
Charlotte had heard about Noanie through a sorority sister +
whose marriage she had very accurately predicted. +
Okay, +
now is there one question in particular? +
Well, no, just... +
There is. +
When will I get married? +
Ace of wands, prosperity. +
Nine of cups, +
strength and independence. +
The hanged man, a new awakening. +
You're a strong independent woman +
with great success in your future, +
but I do not see marriage. +
Excuse me? +
I don't see it. +
What? +
I don't see marriage. +
Well, how can you just... +
say that like that? +
I mean, what about my feelings? +
Honey, I'm a psychic, I'm not a shrink. +
So, who is this fabulous mother in the hat, +
and when do I get to go to church with you two? +
You want to go to church? +
You say that like I'm the Antichrist or something. +
No, it's just I never thought of you +
as the church type. +
Oh, really? +
What type am I? +
The incredibly beautiful and intelligent type. +
What religion are you? +
I'm no one religion in particular. +
I'm open to all. +
Oh, kind of like a 7-11? +
Come on, +
I want to go to church with you and your mommy. +
How about this Sunday? +
Well, it's just a private little thing +
my mother and I do, just the two of us. +
Want to go to the Caribbean next week? +
Sure, I'll go pack my Jet Ski. +
No, I'm serious. +
We can both use a vacation, come on. +
The sun, the sand, you and me. +
You waiting on me. Can you get away? +
Yeah, but I can't afford it. +
Well, I'll tell you what. +
I'll buy the tickets, when we get to St. Barts, +
you can buy me one big margarita. +
Oh, God! +
Wait, I want to hold you. +
I'll be right back. +
Stay here a second. +
Isn't this nice? Us together? +
Yeah. +
Look, I'm just gonna go jump in the shower +
and then boom, I'm all yours. +
There's nothing sinful about sex. +
Oh, oh, really? +
Well, thanks for clearing that up. +
And what is that? The gospel according to Miranda? +
What are you gonna tell me next, that God made the body? +
And if God made the body +
and sex is an expression of that body, +
how can anything made by that God-made body +
be considered sin? +
Well, yeah. +
Oh, it's a miracle, I'm healed! +
You're free to go work with the lepers now. +
I guess this means I'm not going to hell. +
Great news! +
Thank you, Miranda. +
Thank you for saving my immortal soul. +
In her effort to help, +
Miranda had accidentally detonated some kind of +
Catholic guilt bomb. +
I'm gonna go take a shower. +
When I come out, +
I'd kind of like it if you weren't here. +
You got it. +
Six months later, that exact same speech +
would find its way into Thomas John Anderson's +
hit off-Broadway play, Shower of Shame. +
Meanwhile, downtown, +
Samantha was preparing to see God. +
I know it's only been a couple of weeks, +
but I love you, Samantha. +
Oh, I love you too. +
Oh, honey, I can't wait any longer. +
Just unzip and get over here. +
Okay, I'm ready. +
Put it in. +
It is in. +
Samantha said a little prayer that he was kidding. +
He wasn't. +
Sunday morning, +
a time for rest, a time for relaxation, +
a time for spying. +
The plan was simple, just get a look at the mother, +
then Miranda and I would go for eggs. +
Look at how crowded it is. +
What a sham. +
Will you lighten up? +
It's a Presbyterian church, not a Catholic one. +
Whatever, Catholics, Episcopalians, +
Buddhists, Shakers, Quakers, +
all the same, all designed to fuck up our sex lives. +
Here, pray. +
Oh, there they are. +
-Where? -Right there. +
As I watched Mr. Big standing quietly next to his mother, +
tall, proud, respectful, +
I think I fell a little bit more in love with him. +
Let us pray. +
We come together this day... +
We're out of here. +
...to receive your blessings... +
...Lord and Savior... +
Here they come. +
I say we make a break for it. +
No, no, they saw me, I have to say hello. +
I can't just pray and run. +
Oh, there they are. +
Okay, go, I'm fine. +
Go. +
Aren't you the young lady who made all that noise? +
Slippery gloves. +
Morning. +
-Good morning. -It's a lovely church. +
Yes, isn't it? +
Don't you think it's lovely? +
Mother, this is my friend, Carrie. +
I searched her face, +
looking for the light of recognition. +
But there was nothing. +
Carrie, Carrie. +
I'm just gonna go and say goodbye to the pastor. +
It was lovely meeting you. +
"My friend, Carrie"? +
You show up at church after I asked you not to. +
What are you trying to do, test me? +
Why all the sudden interest in meeting my mother? +
Well, has the woman ever even heard of me? +
My mother doesn't need to meet another girlfriend. +
Oh. +
I didn't mean that-- +
I mean, +
I'll introduce you as my girlfriend when I'm sure. +
Oh. +
Look, I have to do things on my time frame. +
Time frame? +
We've been going out for months. +
I really don't know what else to say to you. +
We'll get there. +
You just have to have a little faith. +
Faith? +
Yeah. +
Look, in a couple days we're going on vacation, +
we'll have plenty of time to talk this out. +
Right now I've got to get my mother home, okay? +
Well, go. +
Just go. +
Move over. +
I didn't leave. +
You didn't seem fine. +
He introduced me to his mother as a friend. +
She never heard of me. +
That isn't a good sign. +
Maybe they're not that close. +
Come on, don't lie, you're in a church. +
I can't get inside. +
I don't know what else I can do. +
Later that night, in the church of disco, +
Stanford invited everyone he knew +
to a party to introduce a new fragrance... +
Fallen Angel. +
Hi, Carrie. +
Carrie! +
Also, he wanted to show off his new boyfriend, Alanne. +
-Hi. -Isn't this fun? +
It's like hell with a cover charge. +
Carrie, this is Alanne. +
Alanne, Carrie. +
Hi, nice to meet you finally. +
You, too. +
Did I tell you that Alanne +
designed the Fallen Angel bottle? +
Yes, congratulations! +
Thank you. +
Excuse me for a second. +
I just saw someone I want to say hello to. +
So you know what we did today? +
We shopped for deco cabinet handles +
for his armoire. +
I turned into one of those couples we hate, +
and I'm loving it! +
Stanford and Alanne worshiped the same God... +
style. +
So, you all excited for the big "vacationné"? +
Oh, I don't know. +
I can't help feeling like +
it's some sort of consolation prize +
for not letting me in his life. +
Well, what is going on with you two? +
We're not in the greatest place. +
What happened? +
He wouldn't introduce me to his mother. +
Ouch. +
Thanks. +
Skipper, hi. +
It seems Stanford had invited everyone in his rolodex. +
I, uh, I was hoping I'd see you here. +
I've been totally thinking about you since we broke up. +
You have? +
Totally. +
You look great. +
Thanks. +
So do you. +
Miranda looked at Skipper, +
the months apart had shed a new light on him. +
Actually, they'd shed a new light +
on his shower-free feelings about sex. +
Later that night, +
the three of us tracked Samantha to the ladies room +
to get the lowdown on her love life with James. +
Here you are, we've been looking for you everywhere. +
So, how is everything? +
She means have you and James done it yet? +
Mm-hmm. +
And? +
It's nice. +
I'm so happy for you. +
Sweetie, what-- what? What is it? +
Nothing. +
Hey. Hey! +
What's going on? Why are you crying? +
James has a small dick. +
Oh, well, it's not the end of the world. +
-It's really small. -How small? +
-Too small. -Well, size isn't everything. +
Three inches? +
Well... +
-Hard? +
Is he a good kisser? +
Oh, who the fuck cares? +
His dick is like a gherkin! +
I feel so terrible. +
Listen to me, I'm a bad person. +
Don't beat yourself up. +
You had certain expectations and you're disappointed. +
Why? +
Why does he have to have a small dick? +
I really like him. +
I thought you loved him. +
Well... +
Oh, look, we've all been there. +
That's for sure. +
I was once with a guy the size of one of those +
little miniature golf pencils. +
I couldn't tell if he was trying to fuck me or erase me. +
I'm-- I'm sorry, it's just-- it's funny. +
Let's not lose perspective. +
There are ways to work around it. +
Well, I don't want to work around it. +
I love a big dick. +
I love it inside of me. +
I love looking at it, I love everything about it. +
When I blow him, it's like... +
Nothing. +
Can you talk to him about it? +
No. +
It's the only thing we can't talk about. +
What am I gonna do? +
How is he with his tongue? +
Charlotte left us all behind +
telling us she had another party to go to. +
She took a cab to a part of town +
never mentioned in The New Yorker. +
Will I ever get married? +
I call the power of all the saints. +
Saint Lazarus. +
Santa Rosa. +
Saint Rosa, send me your guidance. +
Send me the truth. +
Send me an answer. +
No yolk. +
What does that mean? +
You'll never be married. +
You are cursed. +
But do not worry, +
for the hundred dollars, we can remove it. +
The entire way home, +
Charlotte berated herself for being so foolish. +
She simply refused to give into the idea +
that she would never get married. +
-Sorry. -Sorry. +
All she had to do was keep believing +
and it would happen. +
It was 3:00 a.m. in the church of disco, +
and Miranda couldn't believe what she was about to say. +
You want to spend the night? +
The night? +
The whole night? +
Yeah, the whole night. +
I knew we'd get back together. +
You did, huh? +
Yup... +
Every night I'd light a candle and say a little prayer. +
You're a freak. +
Samantha tried desperately to believe +
that love was stronger than sex. +
Why are you crying? +
I'm just so happy. +
I stayed up all night +
questioning my faith in faith. +
I mean, hadn't I had faith in us all along? +
Faith that all the withholding would stop... +
Faith that he'd say, "I love you." +
Let's go! +
Hey, hurry, we're gonna miss the plane. +
Wait, wait, wait, put them down a second. +
Just put them down. +
Okay. +
What? +
I need a sign. +
I mean, you told me to have faith, but see, um, +
I'm kind of losing mine, so, so... +
I need a sign. +
What, like in those old religious movies, +
you want a voice from above? +
Just tell me I'm the one. +
Come on, you don't have to tell your mother +
or the whole world, just... +
Just tell me. +
I can't do this. +
Carrie, Carrie. +
Carrie, just get in the car, please. +
I can't. +
I love you, but I can't. +
So that's it? +
\N♪ No regrets ♪ +
\N♪ Although our love affair has gone astray ♪ +
\N♪ No regrets ♪ +
After he left, I cried for a week. +
And then I realized I do have faith... +
Faith in myself. +
Faith that I would one day meet someone +
who would be sure that I was the one. +
\N♪ Still in my heart you'll be ♪ +
\N♪ Forever mine ♪ +
\N♪ No regrets ♪ +
\N“验明正身” +
\N米兰达现正和汤马斯安德森 打得火热 +
\N他是位前途看好的剧作家 +
\N天啊 +
\N太棒了 +
\N她们进展得很顺利 只有一个问题… +
\N我很快回来 +
\N汤马斯只要一做爱完 就马上跳下床冲澡 +
\N马上回来 +
\N每天晚上情况都一样 +
\N-我马上… -好 +
\N米兰达决定等他擦干后 和他摊牌 +
\N冲澡是怎么回事？ +
\N什么意思？ +
\N每次完事后你就去冲澡 我开始觉得好像是我的问题 +
\N不是你﹐只是… +
\N-说啊 -是一种习惯 +
\N发育期时 修女说做爱是项罪恶 +
\N所以我就养成冲澡的习惯 +
\N修女 +
\N米兰达突然恍然大悟 原来她的约会对象是天主教徒 +
\N-你觉得是某种洗礼仪式？ -谁知道 +
\N如果早知道他是天主教徒 就不会和他出去 +
\N他们应该挂个牌子 +
\N纽约的单身男女 很少会问及对方的宗教信仰 +
\N就像他们不会问对方性伴侣数量 怕受到惊吓 +
\N他是个理性﹐条理分明的男人 除了这个缺点 +
\N你忘了洁癖﹐他有洁癖 +
\N我居然找到全曼哈顿 唯一有宗教信仰的男人 +
\N纽约是个充满信仰崇拜的城市 但这点我最近才注意到 +
\N而我唯一知道的教徒 居然是个单身调酒师？ +
\N难道男女关系 已成了九十年代的宗教信仰？ +
\N教会总是劝人内心和善 别道人是非 +
\N于是我决定到各教区 去深入研究宗教信仰 +
\N当我看他们走出教堂时 时髦入时的穿着真令人讶异 +
\N范伦铁诺﹐艾斯卡达﹐奥斯卡 +
\N上帝信仰与时尚流行 居然能相互应合？ +
\N突然间我看到穿着亚曼尼的… +
\N大人物 +
\N着实吓了我一跳 +
\N我居然以为他唯一的信仰 就是崇拜洋基队 +
\N-你好﹐上教堂的男士 -凯莉 +
\N-你怎么在这里？ -做研究 +
\N有关深居简出的长老会教徒 你有认识的人？ +
\N事实上我是个无神论者 但千万别告诉牧师 +
\N-那位神秘的女士是谁？ -我母亲 +
\N-我每星期天和她一起上教堂 -真的？ +
\N我真高兴﹐你怎么没告诉我？ +
\N你星期天要写作﹐所以… +
\N所以星期天就…上教堂 +
\N对 +
\N离球赛开场还有20分钟 我们去喝杯咖啡吧？ +
\N不行﹐今天是截稿日 何况我刚买了卡布奇诺 +
\N-所以… -再见了 +
\N老天保佑你 +
\N这真是两人关系中 最尴尬的时刻 +
\N当你对一个人了若指掌时 +
\N却在某个时刻 让你觉得其实你不了解他 +
\N他和老妈一起上教堂？ 这不是好现象 +
\N别听她胡扯 会关心母亲的人一定是好丈夫 +
\N-我觉得很窝心 -所有宗教都有这种特质 +
\N直到你发现完事后居然要冲澡 +
\N-天啊﹐他还这样？ -对﹐奇怪的是他居然没脱皮 +
\N你试过和他一起冲澡？ +
\N没有 我怕他拿出蒜头和十字架 +
\N他母亲上哪个教堂？ +
\N-公园大道长老教会堂 -那是东区最棒的教堂 +
\N你在为教堂评分吗？ 有教堂指南？ +
\N四颗星﹐圣餐不错 酒则令人失望 +
\N我很想见见他母亲 你们能想像吗？ +
\N多与男友母亲建立关系 那么离结婚之路就不远了 +
\N-抱歉﹐我迟到了 -你也该出现了 +
\N我刚和詹姆斯 吃了五小时的午餐 +
\N五小时的午餐？不用想也知道 +
\N姐妹们﹐我有事宣布 但不能笑 +
\N什么？ +
\N-我恋爱了 -什么？ +
\N这句话从莎曼珊口中说出来 +
\N就像摩西过红海一样 不可思议 +
\N事情发生于 几周前的星期三夜晚 +
\N莎曼珊决定一个人 好好享受音乐 +
\N我被你随音乐摇动的迷人模样 所吸引住 +
\N-我喜欢爵士乐 -看得出来 +
\N-你是音乐家？ -对 +
\N-但被困在律师的身分下 -我不会向别人说 +
\N-可以一起坐吗？ -欢迎 +
\N爵士酒吧关门后 他们沿街散步聊天 +
\N你至少吃一口浇糖的 吃了后像身处天堂 +
\N天堂？我从没想过会到天堂 +
\N为什么？ +
\N像你这样美丽的天使 +
\N接着莎曼珊做了件 她第一次约会时不会做的事 +
\N她没邀请他回家 +
\N谢谢﹐詹姆斯﹐我玩得很愉快 +
\N-我能再见到你吗？ -当然 +
\N在轻柔的触摸后 +
\N从不相信爱情的莎曼珊 突然变成虔诚的信众 +
\N我根本不觉得 女人可以和男人聊天 +
\N-别影响我们 -在詹姆斯面前 +
\N我想说的话只有两句 +
\N快上床﹐回家 +
\N-我欠你﹐夏绿蒂 -欠我？ +
\N-我做了什么？ -就是你那些荒谬理论 +
\N一切长久的等待都会有所回报 +
\N如果我已经和詹姆斯上床 谁知道我们现在会怎样 +
\N-慢着﹐你们还没上床？ -快了 +
\N我觉得他应该是我 可以托付终身的人 +
\N莎曼珊﹐太好了 +
\N莎曼珊有可能比她 更早踏入礼堂的念头 +
\N彻底震惊了夏绿蒂 +
\N她采取了激烈动作 +
\N她去找专为巨星们服务的 灵媒诺妮史坦 +
\N她住在中央公园西区 和哥伦布大道之间的高级住宅 +
\N-这是你和玛丹娜的合照？ -对﹐我们一起上秘教课程 +
\N现在 +
\N用左手选三张牌﹐牌朝下 +
\N夏绿蒂从妇女会的姐妹口中 知道灵媒诺妮 +
\N她正确预言了她们的婚姻状况 +
\N好﹐有什么特别想问的？ +
\N没有﹐只是… +
\N好吧﹐我什么时候会结婚？ +
\NA点魔杖代表成功 +
\N九点圣杯代表权力和独立 +
\N上吊者代表自我的觉醒 +
\N你是个坚强独立 事业成功的女性 +
\N但我看不到婚姻 +
\N-对不起？ -我没看到婚姻 +
\N-什么？ -我没看到婚姻 +
\N你怎么可以说这种话？ +
\N你这么说﹐不怕伤害到我？ +
\N我是灵媒﹐不是心理医生 +
\N你迷人的母亲是怎样的人？ +
\N我何时可和你们一起上教堂？ +
\N-你想上教堂？ -你好像觉得我是反基督教者 +
\N不是 只觉得你不是那种上教堂的人 +
\N是吗？那我是哪种人？ +
\N漂亮又聪明的女人 +
\N-你信仰什么宗教？ -我是什么都信﹐自由开放 +
\N-听来像便利商店 -拜托 +
\N我想和你们一起上教堂 +
\N-这星期天可以吗？ -这个… +
\N这是我和我妈之间的私人聚会 +
\N下星期想去加勒比海？ +
\N好﹐我会准备滑雪板 +
\N我说真的 我们可以好好利用假期﹐好吧 +
\N阳光﹐海滩﹐只有我们两个 +
\N-你可以去吗？ -可以﹐但我付不起 +
\N这样吧﹐机票我出 +
\N我们到圣巴托罗时 你再请我喝一杯玛格利塔 +
\N-等一下﹐我想抱你 -我马上回来 +
\N一会儿就好 +
\N-很棒吧﹐抱在一起 -对 +
\N我去冲个澡 然后就任由你处置 +
\N做爱根本不是罪恶 +
\N是吗﹐谢谢你帮我赎罪 +
\N出自米兰达福音书？ +
\N接下来你要说什么？ 上帝创造人体 +
\N性只是人体的自然呈现 +
\N人体是上帝创造的 怎么会是罪恶？ +
\N没错 +
\N是奇蹟﹐我痊愈了 你治愈了麻疯病患者 +
\N我想这代表我不用下地狱了 真是天大的好消息 +
\N谢谢你拯救了我不朽的灵魂 +
\N米兰达想帮忙的举动 +
\N却突然让她陷入 天主教的罪恶感中 +
\N我要去冲个澡 +
\N我出来时﹐希望你已不在了 +
\N没问题 +
\N六个月后﹐相同的对话出现在 +
\N汤马斯安德森大为轰动的 百老汇剧“羞耻之浴”之中 +
\N同时在市中心 莎曼珊则准备去会见上帝了 +
\N虽然我们只交往几星期 但我爱你﹐莎曼珊 +
\N我也爱你 +
\N亲爱的﹐我不能再等了 解开拉链﹐上床吧 +
\N-我准备好了﹐进来吧 -已经进去了 +
\N莎曼珊祈祷他不是在开玩笑 +
\N但他真的不是开玩笑 +
\N星期天早晨 是休息﹐放松…盯梢的日子 +
\N计划很简单﹐只要看到他母亲 +
\N我们就走人 +
\N人居然会这么多﹐一群伪君子 +
\N看清楚﹐这是长老会教堂 不是天主教堂 +
\N都一样﹐天主教﹐圣公会 佛教﹐震颤教﹐贵格教 +
\N这些宗教都一样 目的就是要破坏性生活 +
\N祈祷 +
\N他们在那边 +
\N-哪里？ -就在那边 +
\N当我看着大人物 站在他母亲身旁时 +
\N高大﹐自豪﹐彬彬有礼 +
\N觉得自己更爱他了 +
\N大家祈祷 +
\N-今天我们齐聚一堂… -走了 +
\N他们来了﹐我们走吧 +
\N他们看到我了﹐我得打声招呼 我不能这样就溜了 +
\N他们来了﹐走吧﹐我可以 +
\N这不是那位引起骚动的女士？ +
\N-手套太滑了﹐早 -早 +
\N-这教堂真漂亮 -对 +
\N-你不觉得很漂亮？ -妈﹐这是我朋友﹐凯莉 +
\N我想从她脸上找寻 对我似曾相似的印象 +
\N但什么表情都没有 凯莉… +
\N我去和牧师说声再见 很高兴见到你 +
\N-我朋友？凯莉 -我说过叫你别来 +
\N你是想考验我？ +
\N你为何这么有兴趣见我妈？ +
\N难道她没听过我？ +
\N我母亲不需见过我所有女朋友 +
\N我不是… +
\N我是说等我真正确定后 我会向她介绍你 +
\N我必须照着自己的步骤来 +
\N步骤？我们已交往几个月了 +
\N我不知道我还能说什么 +
\N我们会到那个阶段的 只需要有点信心 +
\N-信心？ -对 +
\N我们再找时间好好谈 +
\N现在我要送我母亲回家 好吗？ +
\N走吧 +
\N走 +
\N坐过去点 +
\N我没走﹐你看来很不好 +
\N他向他妈介绍我是他朋友 +
\N她根本没听过我的名字 这不是好现象 +
\N-或许他们没那么亲近 -别说谎﹐你是在教堂内 +
\N我打不进他的生活圈 +
\N我不知道还能做什么 +
\N那晚在迪斯可酒吧中 +
\N史丹佛邀请大家出席 介绍最新的香水 +
\N堕落天使 +
\N凯莉 +
\N也顺便展示一下 他的新男友亚伦 +
\N好玩吧？ 像不像要收服务费的地狱 +
\N凯莉﹐这是亚伦 +
\N-你好﹐终于见到你了 -也终于看到你了 +
\N我有说过堕落天使的香水瓶 就是由亚伦负责设计？ +
\N-恭喜 -谢谢 +
\N对不起﹐失陪一下 我要过去打声招呼 +
\N你知道我们今天做了什么？ +
\N我们去逛雕饰衣柜的把手 +
\N变成一副老夫老妻的模样 但我很喜欢这种感觉 +
\N史丹佛和亚伦崇拜相同的东西 时尚流行 +
\N到加勒比海度假很兴奋吧？ +
\N不知道 +
\N我觉得这次度假 好像有点安慰性质 +
\N-是希望我别介入他的生活 -你们俩到底怎么了？ +
\N-我们步调不一样 -怎么了？ +
\N他没把我介绍给他母亲认识 +
\N天啊 +
\N谢谢 +
\N史奇普 +
\N看来史丹佛 好像把认识的人全请来了 +
\N我希望在这里能见到你 +
\N我们分手后﹐我就一直想着你 +
\N-是吗？ -真的 +
\N-你看来很漂亮 -谢谢 +
\N你也很帅 +
\N米兰达看着史奇普 分隔后让他们重新擦出火花 +
\N事实上也重燃米兰达的希望 性爱后不用再忍受冲澡的行径 +
\N稍后我们在女化妆室 找到莎曼珊 +
\N逼她供出和詹姆斯的性爱生活 +
\N我们到处找你 +
\N情况如何？ +
\N你和詹姆斯做了没？ +
\N结果呢？ +
\N-很好 -我真为你高兴 +
\N-怎么了？ -没什么 +
\N怎么了？你为何哭？ +
\N詹姆斯有个小弟弟 +
\N-这又不是世界末日 -是非常小 +
\N-多小？ -很小 +
\N-尺寸不能代表一切 -三寸？ +
\N还没到 +
\N-他的吻功不错吧？ -谁在乎？ +
\N他的弟弟像个小黄瓜 我很难过﹐真的 +
\N别对自己失去信心 期望过高﹐失望越大 +
\N为什么？ +
\N为什么他的弟弟这么小？ 我是真的喜欢他 +
\N-我还以为你爱他？ -这… +
\N-这种事我们都经历过 -没错 +
\N我曾和个家伙交往 他的弟弟像只高尔夫铅笔一样 +
\N我根本分不清他是想和我上床 还是想把我擦掉？ +
\N对不起﹐只是蛮好笑的 +
\N别失去信心 他总有其他优点来弥补不足 +
\N我不要其他优点 我就是爱大热狗 +
\N我喜欢它在里面的感觉 喜欢看着它﹐怎样都好 +
\N当我帮他口交时… 什么反应都没有 +
\N-和他谈谈？ -不 +
\N那是我们唯一不能谈的话题 +
\N我该怎么办？ +
\N他的舌功如何？ +
\N夏绿蒂丢下我们 前往参加另一个聚会 +
\N（神灵夫人 萨泰里阿教秘密仪式） +
\N她搭计程车前往一个 纽约客杂志上从未提过的区域 +
\N我会结婚吗？ +
\N召唤众圣者们的神灵 圣者拉撒路﹐圣者罗莎 +
\N引领我﹐赐予真相 +
\N给予解答 +
\N没有蛋黄 +
\N这代表什么意思？ +
\N你这一辈子都不会结婚 +
\N你受到诅咒 +
\N别担心 只要100美元就能化解厄运 +
\N回家路上夏绿蒂痛骂自己是 天下第一号大笨蛋 +
\N她决定把不会结婚的诅咒 抛诸脑后 +
\N她只要心存信心就会美梦成真 +
\N凌晨三点的狄斯可酒吧里 +
\N米兰达对她即将要说出的话 感到不可置信 +
\N-你想一起过夜？ -过夜？一整晚？ +
\N对﹐一整晚 +
\N-我就知道我们会复合 -是吗？ +
\N每天晚上我都点上蜡蠋祷告 +
\N你是个怪胎 +
\N莎曼珊则极力说服自己 相信“爱胜于性” +
\N你怎么哭了？ +
\N我喜极而泣 +
\N我整晚睡不着﹐质疑自己 对“信心”的相信程度 +
\N难道我对这段这感情 一直没有信心？ +
\N相信所有困难会迎刃而解 +
\N-相信他会说“我爱你” -走吧 +
\N快﹐不然赶不上飞机 +
\N等等﹐先放一下﹐放下来 +
\N好﹐怎么了？ +
\N我需要一个征兆 +
\N你告诉我要有信心﹐但… +
\N我却失去信心 所以我需要一个征兆 +
\N就像传统的宗教电影一样 需要来自天上的声音？ +
\N告诉我﹐我是你的唯一 +
\N你不必告诉你母亲或任何人 但只要… +
\N只要告诉我 +
\N我做不到 +
\N凯莉 +
\N凯莉﹐上车﹐拜托 +
\N我不行 +
\N我爱你﹐但我做不到 +
\N结束了？ +
\N大人物离开后 我整整哭了一个礼拜 +
\N后来我才了解 自己并没有丧失信心 +
\N我相信自己 +
\N相信有一天会遇到白马王子 +
\N他会相信我是他的唯一 +
