= 0838
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 838: Talking About Immigration.
This is English as a Second Language Podcast episode 838. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Our website is eslpod.com. Download a Learning Guide for this episode by becoming a member of ESL Podcast.
This episode is a dialog between Ann and Chris, about a popular issue in the United States – immigration. Let’s get started!
[start of dialog]
Ann: The immigration policy in this country is ridiculous. Why are there so many illegal immigrants here? They cross the border and take American jobs! They all need to be deported.
Chris: A lot of immigrants have lived here nearly all their lives. Do you mean to tell me that you want to do some of the jobs that undocumented workers do, like picking crops and cleaning houses, and not earning minimum wage?
Ann: There’s nothing wrong with that kind of work. I wouldn’t want to do it myself...
Chris: That’s just it! You’re willing to benefit from cheap labor, but you keep complaining about immigrants. There needs to be an amnesty or work permit program so that they can stay legally and work.
Ann: And pay their taxes! These illegal immigrants dodge paying taxes, too.
Chris: But they don’t get the same social services that citizens or legal immigrants do. You can’t have it both ways. If you want them to do what citizens are required to do, then you have to give them legal status. And, by the way, when is your visitor’s visa up?
Ann: It was up last month, but I’m from Canada! Overstaying a visa is not the same thing as being an illegal alien.
Chris: That’s where you’re wrong. Where’s that number for immigration?
[end of dialog]
Our dialog begins with Ann saying to Chris, “The immigration policy in this country is ridiculous.” “Immigration” (immigration) is when people come into a country. They leave their own country and they go to a different country and typically become citizens of that country, become members of that country or that nation, if you will. Ann says the immigration policy – the laws, the rules, the guidelines for immigration in this country – is “ridiculous,” meaning it’s terrible. “Ridiculous” usually has a negative meaning, especially in an example like this.
Ann says, “Why are there so many illegal immigrants here?” “Illegal” (illegal) is something that is against the law. “Immigrant” is the person who immigrates. So, if you leave from one country to another, you are an immigrant to your new country. The United States, of course, is for the most part a country of immigrants. Ann says that these illegal immigrants “cross the border and take American jobs.” A “border” (border) is the line that divides, in this case, two countries. “To cross” means to go from one side to the other. So, “to cross the border” means to go from one country to another. Ann is talking about these illegal immigrants who are coming from another country and into the United States – they’re crossing the border. They all need to be “deported,” Ann says.
“To deport” (deport) is when the government of a country makes you leave that country. They kick you out of the country. They require that you leave. Chris responds that a lot of immigrants have “lived here nearly all their lives,” meaning many immigrants have been here since they were children. “Do you mean to tell me that you want to do some of the jobs that undocumented workers do?” The phrase, “Do you mean to tell me…” is used when you can’t really believe what the other person is telling you. “Do you mean to tell me that you have never visited New York City?” Well, a lot of people have not New York City, but if you didn’t believe what the person was telling you, if you were surprised and perhaps even a little angry, you might use this phrase. “Do you mean to tell me that you want to do some of the jobs that undocumented workers do?” What Chris is saying that the jobs that are being taken by illegal immigrants are jobs that most people probably don’t want to do themselves – most Americans.
The term “undocumented worker” refers to, basically, an illegal immigrant. But it’s a little nicer term. “Undocumented” means you don’t have legal documents, and a worker, of course, is someone who works. Chris mentions a couple of these jobs such as “picking crops” (crops). “Crops” refers to food that is grown, food that you eat – plants. “To pick” means to go out and take the food from the plant so that you can eat it, such as corn, for example. “Cleaning houses” means, of course, making sure that a house is clean by cleaning the floors and the windows and so forth. This is a job that many undocumented workers do. They work as what we would call “maids” (maids), a person who you pay to clean your house.
Chris says these undocumented workers often don’t earn or don’t receive the “minimum wage.” In the United States, the “minimum wage” (wage) is the minimum amount of money you can pay a worker each hour. I’m not sure exactly what it is in 2012. It can also be different in different states. Some states have a higher minimum wage than the national or federal minimum wage. I believe in the year we are recording this – 2012 – it’s a little more than $7 an hour.
Ann says, “There’s nothing wrong with that kind of work. I wouldn’t want to do it myself…” meaning I don’t want to do that kind of work. Chris says, “That’s just it.” “That’s just it” here means “That’s my point, that’s what I’m trying to say.” You’re saying what I’m saying. “You’re willing to benefit from cheap labor but you keep complaining about immigrants.” “Labor” (labor) here means the work that is performed by people, not machines or computers. The word “labor” can also be used to describe what happens when a woman is about to give birth to a child. When a child is about to be born, we say that the mother goes “into labor.” That, as many of you probably know from personal experience, is a lot of work indeed.
Chris says, “There needs to be an amnesty or work permit program so that they” – the undocumented workers – “can stay legally and work.” “Amnesty” (amnesty) is when the government decides they’re not going to punish you for doing something illegal. Usually, amnesty is given for a short period of time and typically, for things that are not that serious. For example, the public library system might have a week where you can return a book even if it is “overdue” – even though you were supposed to return it a long time ago and have to pay money because it’s late. If a library gives you amnesty, it’s saying, “We’re not going to punish you. You don’t have to pay anything if you return the book.” Well, here, Chris is talking about amnesty for illegal immigrants, for undocumented workers. The government would not punish them if they wanted to stay in the country.
A “work permit” (permit) is an official document – an official letter or card – that allows you to work in a country. It’s the permission that the government gives you to work in that country. In the United States, you have to have a “work permit” or some sort of permission from the government to work here, if you’re not an official resident or citizen of the U.S. Ann says, “And pay their taxes.” She’s saying that these illegal immigrants need to pay their taxes. She says, “They dodge paying taxes, too.” “To dodge” (dodge) means to avoid, to find a way not to do something. Some people try to “dodge” their taxes. They invent or create ways that will help them avoid having to pay the government money – that’s what Ann says these workers are doing. Chris says, “But they don’t get the same social services that citizens or legal immigrants do.” “Social services” refers to benefits, programs provided by the government, to help people who are poor to give them healthcare, to help people who perhaps have a drug problem – all of these could be called “social services,” helping people who need help, especially economic help, financial help, help with money.
“Citizens” (citizens) are people who are members of – or part of – a particular country, who have the rights and responsibilities of being in that country. I am a citizen of the United States. If you are born in the United States, you also become a citizen of the United States, even when your parents are from a different country. Chris says, “You can’t have it both ways,” meaning you can’t say one thing and then something that is opposite, and believe that both of those things should happen or are true. He says, “If you want them” – the undocumented workers – “to do what citizens are required to do, then you have to give them legal status.” You have to say, “Oh, it’s okay. You can stay here. You can stay in this country.” “And, by the way,” – in addition – “when is your visitor’s visa up?” A “visa” (visa) is a document that allows you to visit a certain place, usually for a short amount of time, although sometimes the visa can be for a longer period of time. If you come to the United States as a student, and you’re studying at a U.S university, you would get a “student visa.” You could stay here, perhaps four, maybe six, even 8 years, depending on how much education you get.
Chris is asking Ann about her visitor’s visa, which means she’s not even an American citizen. She herself is from some other country. Ann says, “It was up last month.” “It was up” means that it expired, it was no longer valid. “But I’m from Canada,” she says. “Overstaying a visa is not the same thing as being an illegal alien.” “To overstay” (overstay) – one word – means to stay somewhere for more time than you are supposed to or for more time than you are expected to be there. We have an expression, “He’s overstaying his welcome,” meaning he’s staying too long at someone’s house or in someone’s apartment. Now this person who owns the apartment or house is starting to get a little upset. They’ve been staying there too long. “To overstay a visa” would mean to get a visa to visit a country and then stay there longer than the visa allows you to. Ann says, “That’s not the same thing as being an illegal alien” – an illegal immigrant. The word “alien” (alien) here means a person who is not from this country. We also use that word “alien” to describe beings from outer space – creatures or life forms from other planets, if they exist.
Chris says, “That’s where you’re wrong.” He’s saying Ann is wrong. Overstaying a visa is, in fact, becoming an illegal immigrant. “Where’s that number for immigration?” “Where’s that number for the office of immigration,” or the agency in the United States government that takes care of people who are immigrants.
Now let’s listen to the dialogue this time at a normal speed.
[start of dialog]
Ann: The immigration policy in this country is ridiculous. Why are there so many illegal immigrants here? They cross the border and take American jobs! They all need to be deported.
Chris: A lot of immigrants have lived here nearly all their lives. Do you mean to tell me that you want to do some of the jobs that undocumented workers do, like picking crops and cleaning houses, and not earning minimum wage?
Ann: There’s nothing wrong with that kind of work. I wouldn’t want to do it myself...
Chris: That’s just it! You’re willing to benefit from cheap labor, but you keep complaining about immigrants. There needs to be an amnesty or work permit program so that they can stay legally and work.
Ann: And pay their taxes! These illegal immigrants dodge paying taxes, too.
Chris: But they don’t get the same social services that citizens or legal immigrants do. You can’t have it both ways. If you want them to do what citizens are required to do, then you have to give them legal status. And, by the way, when is your visitor’s visa up?
Ann: It was up last month, but I’m from Canada! Overstaying a visa is not the same thing as being an illegal alien.
Chris: That’s where you’re wrong. Where’s that number for immigration?
[end of dialog]
Our scriptwriter labors long and hard to provide us with the very best scripts on the Internet. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, here on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2012 by the Center for Educational Development.
Glossary
immigration policy – the laws, rules, guidelines, and principles a country follows in determining who should be allowed to enter and permanently live in the country
* How will all of the people coming here from countries at war affect our immigration policies?
illegal immigrant – a person who is living in a country without permission to do so
* Illegal immigrants live in constant fear that they will be sent back to their countries.
to cross the border – to go into another country by crossing over the line drawn on maps between two countries
* They crossed the border in the middle of the night, when they thought they wouldn’t be seen.
to deport – the government process of sending someone back to the country he or she came from
* Did you hear that Young was deported and didn’t even have a chance to say goodbye to his family?
do you mean to tell me – a phrase used when one does not believe what another person is saying and wants to challenge it
* Do you mean to tell me that you’ve never told a lie in your entire life?
undocumented worker – a person who is working but does not have legal permission to work and/or live in the country
* Most undocumented workers earn far less money that other workers do.
crop – a plant that is grown for food, clothing, or some other purpose
* The crops that do best in this part of the country are corn and potatoes.
minimum wage – the lowest amount of money per hour that the government allows businesses to pay their workers
* Economists argue that if we increase the minimum wage, employers will hire fewer people or raise the prices of the goods and services they sell.
labor – work performed by people, not machines
* What’s the most expensive component of making these devices: labor or materials?
amnesty – an official agreement to not punish someone for something illegal that he or she has done, especially for entering a country and living there without permission
* Some people believe than an amnesty program would encourage more people to come to the country as illegal immigrants.
work permit – an official document allowing someone to work in a particular country
* How old do you have to be to apply for a work permit?
to dodge – to avoid; to find a way to not have to do something
* For some young men, going to college was a way to dodge military service.
social service – a service provided by the government to society, such as financial assistance for low-income families, healthcare, and drug addiction treatment
* Middle-class taxpayers provide most of the money for social services, but receive relatively few of the benefits.
citizen – a person who is part of a particular country and has all the rights and responsibilities of the people who live in that country
* How long do you have to live in the United States before you can apply to become a citizen?
visa – a document that allows a person to live in a country for a particular purpose for a certain period of time
* Do we need a visa to go to Brazil?
up – ended; finished; expired; all done; all over
* Your treatment session is up. I’ll see you next week.
to overstay – to stay somewhere for more time that one is supposed to, or for more time than one is expected to
* Aunt Candie has been staying in our house for more than three weeks. How can we gently let her know that she’s overstaying her welcome?
illegal alien – a person who is not a citizen of a country and does not have permission to live there, but is living there anyway
* If an illegal alien is sent back home, do their kids have to go too?
immigration – an informal term for the part of U.S. government agency that is responsible for administering laws related to immigration and naturalization (the process of becoming a citizen)
* Many people are afraid to leave their homes because they don’t want to be caught by immigration.
Comprehension Questions
1. What does Ann think should be done with the illegal immigrants?
a) They should be killed.
b) They should be put in prison.
c) They should be sent back home.
2. According to Chris, what type of work do illegal immigrants do?
a) They harvest fruits and vegetables.
b) They fix cars and trucks.
c) They wash dishes in restaurants.
Answers at bottom.
What Else Does It Mean?
crop
The word “crop,” in this podcast, means a plant that is grown for food, clothing, or some other purpose: “Last year’s soybean crop failed, so this year they’re going to plant corn instead.” A “bumper crop” is a very large amount of something grown by farmers: “If we continue to have good weather, we should have a bumper crop this fall.” When talking about hair, a “crop” is a very short haircut: “Kelley wants to get a crop, but she’s afraid it will make her look like a boy.” Finally, as a verb, “to crop” means to change the size of a photo by cutting off one or more sides: “Can you crop this photo so that sign post isn’t there?”
dodge
In this podcast, the verb “to dodge” means to avoid or to find a way to not have to do something: “I know you don’t like doctor’s appointments, but you can’t dodge your annual exam forever.” The phrase “to dodge a question/issue” means to avoid talking about something even when asked about it directly: “Politicians are very good at dodging tough questions from reporters.” “Dodge ball” is a game played by young children in school, where teams on each side of the gym try to hit players on the other team with balls: “Lyle has really quick reactions, so he plays dodge ball very well.”
Culture Note
Border Control
In recent years, the United States has “amped up” (increased) its efforts at “border control” (knowing and limiting who enters the country). These increased efforts are “in part” (partially) due to fears that “terrorists” (people who use violence to create fear) will enter the country, but also due to concerns about the number of illegal immigrants in the United States. Border control efforts also focus on what people bring into the country, specifically trying to limit the movement of illegal drugs across the borders. Most of the focus is on the United States’ southern border with Mexico.
The U.S. Congress has looked at many “bills” (proposals for new laws) to build a “fence” (gate; wall) along the U.S./Mexican border. These tall walls and “intended” (meant) to stop people from crossing the border illegally by “funneling” (pushing toward) them through the “manned” (with people working there) crossing points. As of 2010, more than 600 miles of fence have been built, but plans to build more of the fence have been “stalled” (delayed) due to the “expense” (money required).
There has also been an increase in “vigilantism” in recent years. This refers to efforts by citizens, not law-enforcement officers, to “enforce” (make sure people follow and obey) laws. Groups of concerned citizens work together to “patrol” (walk back and forth along) border areas, looking for illegal crossings. There are many different vigilante groups. Some are helpful to law-enforcement officers, but others are “problematic” (creating trouble) – especially those that have “ties to” (connections with) “hate groups” (organizations that try to hurt people of different races or ethnicities).
Comprehension Answers
1 - c
2 - a