
= 向量组 线性相关 性质
//:stylesheet: my-stylesheet.css
:toc: left
:toclevels: 3
:sectnums:

'''


== 线性相关的 性质, 定理

==== 向量组中, 若其中有两个向量成比例, → 则该向量组中的所有成员, 就都"线性相关".

如:
\begin{align*}
	\underset{ \text{注意:\ 这两个向量成比例}}{\underbrace{(-1)\left| \begin{array}{l}
				1 \\
				2 \\
			\end{array} \right|+(-\frac{1}{2})\left| \begin{array}{l}
				2 \\
				3 \\
			\end{array} \right|}}+0\left| \begin{array}{l}
		5  \\
		19 \\
	\end{array} \right|+0\left| \begin{array}{l}
		-1 \\
		99 \\
	\end{array} \right|=0
\end{align*}

'''

==== 含有0向量的任一向量组, 必"线性相关".

如:
\begin{align*}
	0\vec{v}_1+0\vec{v}_2+0\vec{v}_3+\underset{\text{随便取值}}{\underbrace{k}}\cdot \underset{\text{零向量}}{\underbrace{\vec{0}}}=0
\end{align*}

该向量组, 最后含有一个零向量, 该零向量前的k可以随便取值, 都不影响stem:[k\vec{v}=\vec{0}]. 既然k可以随便取值, 那我们就有了一组不全为0的系数(stem:[k_1, k_2, ...k_n]) , 所以这些v向量, 就是"线性相关"的关系了.

'''

==== 只有一个零向量, 则它必"线性相关".

如:  stem:[k\vec{0}=\vec{0}] \\
k可以随便取值, 都不妨碍  stem:[ k \cdot \vec{0}= \vec{0}]. 既然k可以随便取值, 那我们就有了一组不全为0的系数( stem:[ k_1, k_2, ...k_n]) , 所以这些v向量(本例中只有一个向量), 就是"线性相关"的关系了.

'''



==== 一个向量 stem:[\vec{v}] , 线性相关的 充要条件是: 它本身就是零向量, 即 stem:[\vec{v}=0]

如: stem:[k\vec{v}=\vec{0}].  +
k可以随便取值, 我们就有了一组不全为0的系数( stem:[k_1, k_2, ...k_n]) , 所以这些v向量, 就是"线性相关"的关系了.

'''

==== stem:[	\alpha _1,...,\alpha _s] "线性相关" 的充要条件是: 至少一个向量, 可以由其余向量来表示


'''

==== stem:[\alpha _1,...,\alpha _s] 是"线性无关"的, 如果给它们再加一个向量stem:[\beta] , 即 stem:[	\alpha _1,...,\alpha _s, \beta] 变成了是"线性相关"的话, 则可以证明: stem:[\beta] 可由 stem:[	\alpha _1,...,\alpha _s] 来唯一的线性表示.



'''

==== 若 stem:[\vec{v_1}, ... \vec{v_r}] 这组向量是"线性相关"的, 则给它们添加一些新的向量, 它们整体(stem:[\vec{v_1}, ... \vec{v_r}, \vec{v_{r+1}}, ... \vec{v_s}] ) 依然是"线性相关"的.

.标题
====
证明过程, 如:  +
已知 stem:[\vec{v_1}, \vec{v_2}, \vec{v_3}] 是"线性相关"的, 即: +
stem:[k_1\vec{v}_1+k_2\vec{v}_2+k_3\vec{v}_3=0 ]

把它扩充一下, 就有: +
stem:[(k_1\vec{v}_1+k_2\vec{v}_2+k_3\vec{v}_3) +(0\vec{v}_4+0\vec{v}_5)=0] +

这5个系数k, 就是: stem:[k_1, k_2, k_3, 0, 0], 不全为0! 说明这组向量 stem:[\vec{v_1}, ... \vec{v_5}] 是"线性相关"的. 证毕.
====

即: 一个向量组中, 只要其中一部分向量是"线性相关"的, 则就可知道: 整个向量组中的全部向量, 都是"线性相关"的. +
这里的本质就是: \textbf{比如一个队伍, 有1个女的, n个男的. 它满足"有女"性质. 之后无论往队伍里添加多少人, 它依然满足"有女"性质. 因为这个性质, 在最早的队伍中, 就已经被满足了.}


即:

- 部分"线性相关"stem:[\overset{\text{能推导出}}{\rightarrow}]整体"线性相关"
- 整体"线性相关"stem:[\overset{\text{能推导出}}{\rightarrow}]部分"线性相关"

同样就是说: *整体"无女"的话, 则其中的子集部分也"无女".*


'''

==== 在一个n维空间中, 存在m个n维向量的话, 并且是stem:[m>n的]话,则这个向量组(即含有m个向量的), 一定是"线性相关"的. 即: n+1个n维向量, 一定"线性相关".

比如, 在3维空间中, 存在4个三维的向量, 则由这4个向量所组成的"向量组", 一定是"线性相关"的. 即这个向量组中, 最多只有3个向量可以做基轴, 还有一个向量是多余的.


'''
