
= 矩阵
//:stylesheet: my-stylesheet.css
:toc: left
:toclevels: 3
:sectnums:

'''

== 矩阵

矩阵一般用大写字母来表示. 比如 A, B, C, E. (D留给了行列式.)

.矩阵和行列式的区别:
[options="autowidth"]
|===
|行列式 |矩阵 Matrix

|本质是个"数"
|是张"数表"

|符号, 用竖线包围表示, 即 \|...\|
|用 [] 或 () 包围. 几乎不用大括号.

|必定是方形的, 即 行数=列数
|行列数无要求.
|===

.只有一个元素的矩阵, 书写它时可以不带矩阵括号:
如: [5]=5

'''

== #零矩阵#

元素都是0的矩阵, 叫零矩阵, 记作0.

==== ① AB=0 , 是推不出 A=0 或 B=0 的. ② AB=AC, 且 stem:[ A \ne 0 ], 是推不出 B=C 的.

\begin{align*}
	& \text{有}	A=\left[ \begin{matrix}
		2&		0\\
		-1&		0\\
	\end{matrix} \right] ,\ B=\left[ \begin{matrix}
		0&		0\\
		1&		3\\
	\end{matrix} \right] ,\ C=\left[ \begin{matrix}
		0&		0\\
		2&		4\\
	\end{matrix} \right]\\
	&  \text{则:} AB=\left[ \begin{matrix}
		0&		0\\
		0&		0\\
	\end{matrix} \right] ,\ AC=\left[ \begin{matrix}
		0&		0\\
		0&		0\\
	\end{matrix} \right]\\
\end{align*}

从上面的结果, 我们可以得出这两个结论:

- AB=0 , 是推不出 A=0 或 B=0 的.
- AB=AC, 且 stem:[ A \ne 0 ], 是推不出 B=C 的.

'''

==== 一个矩阵, 与"零矩阵"相乘, 结果就是一个"新形状"的零矩阵

如: stem:[ A_{4×3}O_{3×2}=O_{4×2}]

'''



== 负矩阵

所有元素, 都取其负数的矩阵, 叫负矩阵. 记为 -A.



'''

== #单位阵E#

即"主对角线"上元素都是1, 其他都是0的矩阵.  记作 E 或 I.

.主对角线:
记忆方法:  +
→ 主对角线, 是下坡 \ +
→ 次对角线, 是上坡 /

注意: *只有"方阵", 才有"主对角线"的概念.* 不是方阵, 就没有主对角线.
\begin{align*}
	E\text{或}I=\underset{\text{单位阵}}{\underbrace{\left[ \begin{matrix}
				1&		&		\\
				&		\ddots&		\\
				&		&		1_{}\\
			\end{matrix} \right] }}
\end{align*}

'''

==== 一个矩阵X, 与"单位阵E"相乘(无论左乘还是右乘), 结果还是矩阵X本身. 即: AE=A, EB=B

如:
\begin{align*}
\underset{A}{\underbrace{\left[ \begin{matrix}
			3&		3&		3\\
			4&		1&		1\\
			5&		9&		9\\
		\end{matrix} \right] }}×\underset{E}{\underbrace{\left[ \begin{matrix}
			1&		&		\\
			&		1&		\\
			&		&		1\\
		\end{matrix} \right] }}=\underset{A}{\underbrace{\left[ \begin{matrix}
			3&		3&		3\\
			4&		1&		1\\
			5&		9&		9\\
		\end{matrix} \right] }}
\end{align*}


'''




== 同型矩阵
即两个矩阵A,B, 若A的行数=B的行数,  A的列数也=B的列数, 则它们就叫"同型矩阵". +
如: stem:[ A_{3×5}$ 和  $B_{3×5}], 就是同型矩阵. 它们的形状是一样的. 

若同型矩阵中, 对应元素都相等, 则这两个矩阵相等. 换言之, *两个矩阵相等的前提, 是它们必须是"同型矩阵".* +
所以, 两个零矩阵, 不一定相等. 因为它们不一定是同型的. 如: stem:[ 0_{2×2}\ne 0_{2×3}]

'''

== #矩阵的转置#

stem:[ A_{m×n}], 转置后, 就是 stem:[ (A^T)_{n×m}]

==== stem:[(A^T) ^T = A ]

==== stem:[(A+B) ^T = A^T + B^T ]

==== stem:[ (kA) ^T =  kA^T]

====  ★ stem:[ (AB) ^T = B^T A^T] ← 注意AB顺序要颠倒

==== stem:[(A_1 A_2 A_3 A_4)^T = A_4^T  A_3^T  A_2^T  A_1^T ]  ← 顺序颠倒

'''

== 方阵的行列式

只需把矩阵的中括号, 改成行列式的两条竖线, 就得到了"方阵的行列式".

如, 矩阵:
\begin{align*}
A=\left[ \begin{matrix}
	1&		1&		1\\
	2&		2&		2\\
	3&		3&		3\\
\end{matrix} \right]
\end{align*}

其行列式就是:
\begin{align*}
|A|=\left| \begin{matrix}
	1&		1&		1\\
	2&		2&		2\\
	3&		3&		3\\
\end{matrix} \right|
\end{align*}

行列式和矩阵有什么关系? 其实, 行列式只是矩阵的一个"属性"而已.  +
矩阵有很多属性, 包括: 特征值, 特征向量, 行列式, 等等.

'''

=== "方阵的行列式"的性质

==== stem:[|A^T|=|A|]


'''

==== ★ stem:[|kA|=k^n|A|]

'''

==== stem:[|AB|=|A| \cdot |B|] ← A,B 是同阶方阵

因此, stem:[|ABC|=|A|\cdot |B|\cdot |C|]

.标题
====
A是5阶方阵, 且|A|=3. 求: +
stem:[\ |-A|=? = |-1\cdot A|=-1^5\underset{=3}{\underbrace{|A|}}=-3] +
stem:[|2A^T|=? = 2^5\underset{=|A|=3}{\underbrace{|A^T|}}=2^5\cdot 3=96]

\begin{align*}
\left| \underset{=3}{\underbrace{\left| A \right|}}A \right| =? = 3^5\underset{=3}{\underbrace{|A|}} =3^6
\end{align*}
====



'''



'''
