= 0610
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 610: Preparing to Travel.
This is English as a Second Language Podcast episode 610. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Blue skies, 72 degrees, another beautiful day in L.A.
If you can’t visit us here in Los Angeles, visit our website at eslpod.com. You can download the Learning Guide for this episode that includes additional information, including a complete transcript of this episode to help you improve your English even faster.
This episode is called “Preparing to Travel.” It’s a dialogue between Shannon and Ignacio using a lot of vocabulary that you would need before you go on a trip. Let’s get started.
[start of dialogue]
Shannon: It looks like you’re ready for your trip. You must be psyched.
Ignacio: Yeah, I am. I’m almost ready. I’ve gone to the post office and filled out a form so they’ll hold my mail while I’m gone.
Shannon: I could pick up your mail for you.
Ignacio: Thanks, but it’ll just be easier this way. I’ve also called the newspaper office to have my newspaper delivery suspended. Tomorrow I’ll arrange for my bank to automatically pay my bills so I won’t have my utilities cut off or accrue any late fees.
Shannon: I could pay your bills for you. I don’t mind.
Ignacio: It’s nice of you to offer, but I’ve got it covered. This morning, I took my plants over to my neighbor’s house. He agreed to water them for me while I’m gone.
Shannon: I could have come over and watered your plants. That wouldn’t have been a problem at all.
Ignacio: Thanks for being willing to do that. As always, you’re so helpful.
Shannon: Oh, I try my best…
Ignacio: I was wondering if I could ask just one favor from you.
Shannon: Of course you can. Just name it!
Ignacio: You know my dog, Rex…
Shannon: Oh, no…
Ignacio: I could board him at a kennel, but he’s had bad luck at kennels. Could you look after him while I’m gone?
Shannon: No way!
Ignacio: Why?
Shannon: Why don’t you ask the people who worked at those kennels where Rex has been? I’m willing to pitch in, but I’m no sucker!
[end of dialogue]
Shannon begins the dialogue by saying, “It looks like you’re ready for your trip. You must be psyched.” “To be psyched” (psyched) means to be very excited about something. It’s a very informal expression; it means you are mentally prepared for something, something that you want to do, that you are looking forward to do.
Ignacio says, “Yeah, I am. I’m almost ready (I’m nearly ready, not quite). I’ve gone to the post office and filled out a form (a piece of paper) so they’ll hold my mail while I’m gone.” “To hold the mail,” or “hold your mail” means not to have your mail delivered to your house for a specific period of time. In other words, the post office, the local building where the mail is taken care of, they will keep your mail at the post office while you are on vacation. The reason people do this is because they don’t want all this mail coming to their house and people would realize they weren’t there and therefore they might try to steal something. So, it’s very common for people to hold their mail when they go on a long vacation, let’s say a week or more. That’s what Ignacio is doing.
Shannon says, “I could pick up your mail for you (I could drive to your house every day or every other day – every second day, and get it for you).” Ignacio says, “Thanks, but it’ll just be easier this way. I’ve also called the newspaper office to have my newspaper delivery suspended.” “To suspend (something)” means to temporarily – for a short time – stop doing something. You plan on doing it again in the future, but for right now you don’t want it done. In this case, Ignacio is suspending his newspaper delivery, where they come every morning and bring a newspaper to your house. I have my newspaper delivered every morning. Well, Ignacio, because he’s going to be gone, doesn’t want a bunch of newspapers sitting outside his house, which is, again, something that if you were a thief – if you were someone who likes to rob or steal things from houses, you would see that and think the person is not at home and you can break into their house. It’s the same idea as we mentioned about the mail. “Suspend” has a couple of different meanings in English; you can find those in this episode’s Learning Guide.
Ignacio says, “Tomorrow I’ll arrange for my bank (I will call my bank and tell them) to automatically pay my bills so I won’t have my utilities cut off or accrue any late fees.” So, Ignacio is calling his bank and telling them to automatically pay his bills. Many banks now, on their websites, allow you to pay your bills electronically. And, you can even have it done automatically, so you don’t even have to go into the website, they will automatically pay the bill for you, and that’s what Ignacio wants. He’s especially concerned about his utilities. A “utility” (utility) is a service that is provided by typically the government to you. We are referring to your water, your gas, your electricity; these are all things that the government – the local government takes care of, but of course, you have to pay for it. Collectively – that is, as a group – we call these utilities. If you are renting an apartment sometimes it will include utilities, meaning it would be part of your rent, you don’t have to pay extra. Sometimes it doesn’t. Ignacio is concerned that they will cut off his utilities. “To cut off” is a two-word phrasal verb meaning to stop providing a service, usually because you haven’t paid for it. So if you don’t pay your phone bill, the phone company will cut off your service; you will no longer be able to use it. He’s also concerned about accruing late fees. “To accrue” (accrue) means to have something add up over time, for something to increase or become larger. Usually we use this verb when we are talking about something financial – something related to money. If you don’t pay your utilities, the utility company may charge you an extra fee – an extra amount of money for being late. That’s what a late fee is. Ignacio doesn’t want to have a bunch of late fees he has to pay, so that’s why he wants his bills paid automatically.
Shannon, again, offers to help. She says, “I could pay your bills for you. I don’t mind,” meaning it’s no problem for me. Ignacio says, “It’s nice of you to offer, but I’ve got it covered.” “To have something covered,” or “to have got something covered” is an informal way of saying that you have already fixed the problem or you have taken care of the problem; you have everything under control, we might also say. Ignacio says, “This morning, I took my plants over to my neighbor’s house,” his flowers perhaps. Ignacio says the neighbor agreed to water them for me while I’m gone. “To water,” here, means to give the plants water so that they don’t die. This is the problem I think I have; when I get a plant I forget to water it and it dies. I don’t know why the plant doesn’t ask me for the water – tell me it’s thirsty. I just don’t understand!
Anyway, back to the episode. Shannon says, “I could have come over and watered your plants (I could have come over if you had asked me)…” This is what we call a conditional clause. “That wouldn’t have been a problem at all.” Again, there’s an idea of if you do something then I would do something else. But Shannon, of course, was not asked by Ignacio, and that’s why she’s using the conditional form.
Ignacio says, “Thanks for being willing to do that. As always, you’re so helpful.” Shannon says, “Oh, I try my best (I do my best)…” Ignacio then says, “I was wondering if I could ask just one favor from you (ask you to do one thing).” Shannon says, “Of course you can. Just name it!” When someone says, “name it” they mean you are willing to do whatever the other person wants or needs. It’s an informal phrase; it’s saying I will do whatever you want me to do.
Ignacio says, “You know my dog, Rex…” Rex is the name of the dog. Shannon says, “Oh, no…” Ignacio says, “I could board him at a kennel, but he’s had bad luck at kennels.” A “kennel” is a place where you can leave your dog or your cat or other small pets while you are traveling. It’s like a hotel for animals. “To board” means, in this case, to pay for the animal to be at the kennel. Ignacio says, “Could you look after him while I’m gone?” “To look after (someone)” means to take care of someone, to keep someone safe or out of trouble: “My mother is sick, I need to go to her house to look after her.”
Shannon, however, says, “No way!” meaning absolutely not, I will not look after your dog. Ignacio says, “Why?” Shannon says, “Why don’t you ask the people who worked at those kennels where Rex has been?” In other words, if Rex had a problem at the kennel it’s probably because he’s not a good dog. Shannon says, “I’m willing to pitch in, but I’m no sucker!” “To pitch (pitch) in” is a two-word phrasal verb meaning to help someone do something, to assist with something, typically doing a small part of a larger project or job. If you have a big project at work the boss may ask everyone to pitch in – every one to help, or he may use another phrasal verb: “to help out.”
Shannon says she is willing to pitch in, but she’s no sucker – she’s not a sucker (sucker). A “sucker” is a person who is easily fooled, who is easily tricked. We might also say a “gullible” person. In Shakespeare’s play Othello, Othello was sort of a sucker. He was someone who believed everything that he was told. Well, this expression is very informal, but it means same thing: someone who believes what he or she is told and is easily fooled. The word is sometimes used as an insult: “See you later sucker!” You shouldn’t say that typically, however, it’s kind of a mean thing and someone might decide to put their fist into your face if you say that!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Shannon: It looks like you’re ready for your trip. You must be psyched.
Ignacio: Yeah, I am. I’m almost ready. I’ve gone to the post office and filled out a form so they’ll hold my mail while I’m gone.
Shannon: I could pick up your mail for you.
Ignacio: Thanks, but it’ll just be easier this way. I’ve also called the newspaper office to have my newspaper delivery suspended. Tomorrow I’ll arrange for my bank to automatically pay my bills so I won’t have my utilities cut off or accrue any late fees.
Shannon: I could pay your bills for you. I don’t mind.
Ignacio: It’s nice of you to offer, but I’ve got it covered. This morning, I took my plants over to my neighbor’s house. He agreed to water them for me while I’m gone.
Shannon: I could have come over and watered your plants. That wouldn’t have been a problem at all.
Ignacio: Thanks for being willing to do that. As always, you’re so helpful.
Shannon: Oh, I try my best…
Ignacio: I was wondering if I could ask just one favor from you.
Shannon: Of course you can. Just name it!
Ignacio: You know my dog, Rex…
Shannon: Oh, no…
Ignacio: I could board him at a kennel, but he’s had bad luck at kennels. Could you look after him while I’m gone?
Shannon: No way!
Ignacio: Why?
Shannon: Why don’t you ask the people who worked at those kennels where Rex has been? I’m willing to pitch in, but I’m no sucker!
[end of dialogue]
Don’t worry about our scripts; Dr. Lucy Tse has got it covered! Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
psyched – an informal word for being very excited about something; ready and eager to do something; mentally prepared for something that one is looking forward to
* All the actors are psyched about opening night.
to hold (one’s) mail – to not have one’s mail delivered for a specified period of time, instead having the post office collect it and deliver it all at once when one returns
* Please hold my mail for two weeks and begin delivering it again on Monday the 27th.
to suspend – to temporarily stop doing or having something, with plans to have it start again in the future
* All of their baseball games have been suspended until the weather gets better.
automatically – without one’s involvement; without needing to do anything to make something happen
* This software program includes a calendar that automatically sends me an email a few days before my friends’ birthdays, so that I don’t forget to call them.
utility – a service that is provided to the public, usually paid for each month
* When they moved into a new home, they had to set up new accounts with all the utilities, including natural gas, electricity, and water providers.
to cut off – to stop providing a service, usually because the customer has stopped paying for it; to stop supporting someone financially
* Our telephone service was cut off because we forgot to pay the bill three months in a row.
to accrue – to have something add up over time; for something to increase or become larger or more numerous over time
* Normally interest accrues from the date of the purchase, but the furniture store is offering a special deal where interest doesn’t accrue for the first six months.
to have got (something) covered – to have something under control; to have already fixed a problem or a potential problem; to have a solution
* The roof started leaking, but don’t worry. I’ve got it covered. The roofing company is fixing it right now.
to water – to pour water onto plants, especially indoor plants, to keep them alive
* If you water a cactus plant too much, it will die.
name it – an informal phrase used to show that one is willing to do whatever another person wants or needs
* - There’s one thing I really want for my birthday….
* - Name it and I’ll get it for you – as long as it doesn’t cost more than $20.
to board – to pay for an animal to stay at a business or with another person for a period of time when one is unable to be with it
* How much does it cost to board your horses on the farm each month?
kennel – a place of business where many dogs, cats, and other small pets are cared for while their owners are away
* Our kennel takes really good care of pets, making sure that they eat well and get to play outside for at least three hours each day.
to look after (someone) – to take care of someone; to keep someone safe and out of trouble
* Could you please look after my daughter for a few hours after school today? I need to work late.
to pitch in – to help someone do something; to assist someone with something, doing a small part of a larger task
* If we all pitch in and work together, it shouldn’t take more than a few hours to clean the garage.
sucker – a person who can be tricked or fooled easily; a gullible person
* Otello is such a sucker! He believes everything he hears.
Comprehension Questions
1. Why did Ignacio call the newspaper office?
a) To have his newspaper delivered to a different address while he’s traveling.
b) To cancel his newspaper subscription.
c) To make sure newspapers won’t be delivered while he’s away.
2. What does Ignacio mean when he says, “I’ve got it covered”?
a) Everything is under control.
b) He has all his bills in a binder with a special cover.
c) He has enough money to pay the bills.
Answers at bottom.
What Else Does It Mean?
to suspend
The verb “to suspend,” in this podcast, means to temporarily stop doing or having something, with plans to have it start again in the future: “Marlys suspends her lawn service each winter, asking the gardeners to come back and start cutting the grass again each spring.” Or, “Peace talks will be suspended until the bombing stops.” The phrase “to suspend (someone)” means to make someone leave school or a job for a short period of time, usually as a punishment for breaking the rules: “Can a student be suspended for hitting another student?” Or, “The police officer has been suspended until the detectives can finish their investigation of his involvement in the shooting.” Finally, “to suspend (something)” means to hang something up: “That heavy chandelier is suspended from such a thin, weak chain! I’m surprised it hasn’t fallen down.”
to water
In this podcast, the verb “to water” means to pour water onto plants, especially indoor plants, to keep them alive: “Do you water your garden by hand, or do you have sprinklers?” The phrase “to water (something) down” means to make something weaker or less powerful: “The bar tries to cut expenses by watering down its drinks.” Or, “He tried to water down his criticism so he won’t hurt her feelings.” The phrase “to make (one’s) mouth water” means to make one feel hungry and eager to eat, usually because something smells very good: “The smell of your cooking always makes my mouth water.” Finally, the phrase “to make (one’s) eyes water” means to make someone begin to cry: “The dangerous gas made the children’s eyes water and we immediately sent the students to the hospital.”
Culture Note
Americans often travel for “pleasure” (vacation) or “business” (work), leaving their home “vacant” (empty; without people staying in a place) for days, weeks, or even months “at a time” (at once). Fortunately, many services are available to help these people “maintain” (keep in good condition) their home and protect their “valuables” (the things someone owns that are worth money) while they are gone.
Holding the mail and suspending newspaper delivery is a good idea, because otherwise the mail and newspapers would be sitting on the “front porch” (the area in front of one’s front door), making it “obvious” (easy to understand or perceive) that no one is home. People can also suspend their utility services, cable, and phone services if they don’t want to pay for services that they won’t be using for an “extended” (long) period of time.
Sometimes people choose to ask their neighbors or friends “to keep an eye on” (to look after; to care for) their home “in their absence” (while they are gone). People with pets might need to hire a “dog-walker” who can take their dog on walks each day. Sometimes people choose to have a “house-sitter” live in their home while they are “away” (gone; not at home).
Other people choose to leave their home vacant, but install an “alarm system” or a “security system” that will “alert” (send information to) the police if there is an “unauthorized entry” (someone going into the home without permission). People can also “install” (put into use) “automatic timers” so that their lights turn on and off automatically, making it seem as if someone is home. They do this as a way to “deter” (prevent someone from doing something) “thieves” (people who steal things).
Comprehension Answers
1 - c
2 - a