= 0613
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast episode 613: Being a First-Time Parent.
This is English as a Second Language Podcast episode 613. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
We have a website at eslpod.com. If you go there, you can improve your English even faster by downloading one of the 8- to 10-page Learning Guides that we provide for this episode. It contains a complete transcript of everything I say, as well as lots of other good stuff: vocabulary, cultural notes, that sort of thing.
This episode is called “Being a First-Time Parent.” It is a dialogue between Ricardo and Zuly. They’re going to be talking about being parents, having a baby for the first time. Let’s get started.
[start of dialogue]
Zuly: Hello.
Ricardo: Hi, Zuly. How are you?
Zuly: Oh, Ricardo, it’s you. I’m doing okay. How are you?
Ricardo: I wanted to call and congratulate you on the birth of your new baby.
Zuly: Thanks a lot. Carla was born three weeks ago, and she was eight pounds, three ounces.
Ricardo: That’s great! How does it feel to be a first-time parent?
Zuly: It’s really overwhelming taking care of a newborn. I’m learning everything from scratch, everything from how to breastfeed and bottle-feed, to burping her, to putting her to bed, to using a car seat and a stroller.
Ricardo: You sound overwhelmed. I remember when Adam, our first child, was born. There were the feedings in the middle of the night, and all of those diapers!
Zuly: Exactly. I’m exhausted all the time. In fact, I find myself dozing off at all hours of the day.
Ricardo: I really sympathize with you, but these days will pass quickly, and then you’ll have such great memories. Have you had much sleep?
Zuly: Zzzzzzzz!
Ricardo: Zuly? Zuly?
[end of dialogue]
Ricardo calls Zuly on the telephone. Zuly answers, “Hello.” Ricardo says, “Hi, Zuly. How are you?” Zuly says, “Oh, Ricardo, it’s you (meaning she recognizes who is calling). I’m doing okay. How are you?” Ricardo says, “I wanted to call and congratulate you on the birth of your new baby.” “Birth” is when a new child is brought into the world; when a baby comes out of his or her mother’s womb – comes out of her body and begins breathing on its own, we call that birth. This is the birth of Zuly’s new baby.
Zuly says, “Thanks a lot. Carla (the name of her baby) was born three weeks ago, and she was eight pounds, three ounces.” It’s common for parents to often tell someone about their baby and include how big it was – how much it weighed. This baby weighed eight pounds, three ounces. I weighed, I think, nine pounds, four ounces. I was a big baby – mostly my head!
Ricardo says, “That’s great! How does it feel to be a first-time parent?” “First-time” means, as you can guess, that it is the first event – the first occasion for this particular thing, in this case for being a parent. So, they are first-time parents. It could mean that they are going to have more children in the future, we don’t know, but definitely it means that this is their first baby.
Zuly says, “It’s really overwhelming taking care of a newborn.” Something that is “overwhelming” (one word) is very strong, too strong, too powerful, something that makes you feel that you don’t have control, it may be something that confuses you. If you go to Phoenix, Arizona in the middle of summer – and I do not recommend it – you will be overwhelmed by the heat. It is very hot in Phoenix, Arizona in the summertime. Zuly says that it is overwhelming taking care of a newborn. “Newborn” (newborn – one word) is a baby that has been born very recently, usually within the past month or perhaps two months.
Zuly is saying that her child is a newborn; she was born recently. She says, “I’m learning everything from scratch.” The expression “from scratch” (scratch) means from the very beginning, without any preparation, or any knowledge in this case. The term is often used cooking. “I’m going to make a cake from scratch,” meaning I’m not going to use any prepared ingredients, I’m not going to go to the store and buy a box that says “lemon cake” on it. I’m going to get the lemons, get the flour get the eggs and so forth. That is to make something from scratch. You can use it for anything; you could make a table from scratch, taking a bunch of wood and putting it together, I guess. I don’t mean I could do that, but you could do that. And if you want to do that you can give the table to me because, see, I need a new table here in my room. Anyway, Zuly is learning everything from scratch, from the very beginning. By the way, “scratch” has other meanings in English, very different. Those, you can only find in our Learning Guide…and a dictionary…and on the web…but most importantly in our Learning Guide!
Zuly says she’s learning everything from how to breastfeed and bottle-feed, to burping her, to putting her to bed, to using a car seat and a stroller. Well, these are all common words when talking about taking care of a baby. Let’s begin with my favorite: “breastfeed” (breastfeed – one word). “To breastfeed” as a verb means that the mother feeds the young baby with the milk from her breasts, which are those two things that make up the chest of a woman. The end of the breast is called a “nipple” (nipple); we also use that same word when we have a bottle of milk that we are feeding the baby with. That’s the other way to feed the baby, to “bottle-feed” the baby. A “ bottle,” of course, is a small, usually glass container – could be plastic, I guess. In any case, these are the two ways of giving milk to a baby: one is to breastfeed and one is to bottle-feed. Some people believe breastfeeding is better for the baby. In any case, Zuly is learning to do both.
She’s also learning to burp her baby. The verb “to burp” here means that you take the baby, so I’m told, meaning I don’t do this, but you, again, could take the baby and you very gently, very softly hit the back of the baby after the baby has drunken milk to help the baby push air out of the stomach into his or her mouth. This usually produces what we would call “spit up” (spit up). This is something that mothers or fathers will do for their baby after they have been fed with milk. That’s one of the things Zuly is learning how to do. She’s also learning how to put the baby to bed. “To put (someone) to bed” is a phrasal verb meaning to get a baby or a child ready to sleep, try to calm him or her until he or she falls asleep. Sometimes mothers and fathers will move the child back and forth very slowly, gently. They may sing a song; we call those songs that you sing to a baby to put them to sleep a “lullaby” (lullaby). A common lullaby in English is called “Lullaby and Goodnight,” using music from the classical composer Brahms: Lullaby and goodnight. I don’t know the rest of the words; when my mother sang it to me, that’s all I needed and I fell asleep. Sorry!
Zuly is also learning how to use a car seat. In the United States it is the law in most states, you are required to place your baby in a special I guess we could call at a chair that goes inside the car. It is to keep them safe in an accident. So, Zuly is learning how to use a car seat and a stroller. A “stroller” (stroller) is also called a “baby carriage.” Basically, it’s like a small chair that has wheels on it that you can push in front of you. So, if you want to take a walk you could put the baby in the stroller. When I was growing up, strollers were very small. Nowadays, at least here in the United States, you see some parents that have strollers that are like the size of a small car – they’re huge! And they put all of these things that they think they need for the baby; it’s kind of amazing.
But anyway, getting back to our story: Zuly is learning to use a car seat and a stroller. Ricardo says, “You sound overwhelmed. I remember when Adam, our first child (Ricardo’s first baby), was born. There were the feedings in the middle of the night, and all those diapers!” “Feeding” (feeding), a noun, comes from the verb “to feed,” which means to give food to someone, in this case to give the baby milk, either from a bottle or, we would say, “nursing,” which is another term referring to breastfeeding. So there are feedings in the middle of the night; young babies wake up in the middle of the night and want to eat. You could tell them just to wait until morning, but they probably won’t be too happy, and you probably won’t sleep because they’ll be crying, you see! He also talks about all of the diapers they needed for their little child. A “diaper” (diaper) is a small piece of cloth or, more commonly in the U.S. now, paper and plastic that is wrapped around the baby’s bottom in order to hold in – to catch, really, their urine, what we would informally called their “pee” (pee) that comes out the front end; out the back end comes what we technically call their “feces” (feces), but for a baby informally we would say “poop” (poop), “poop.” Isn’t this fun?
Zuly says, “Exactly (she agrees with Ricardo). I’m exhausted all the time.” “To be exhausted” means to be extremely tired, typically from doing a lot of physical work. Zuly says, “I find myself,” meaning sometimes, “I find myself dozing off at all hours of the day.” “At all hours of the day” means anytime during the day, at different times during the day. “To doze (doze) off” means to fall asleep for a short period of time, usually something that you weren’t planning to do. You just sort of accidentally, if you will, fall asleep because you are so tired. We might also use the verb “to nap” (nap): “I was napping at my desk the other day when Lucy came into the office and woke me up and said I should start working again.”
Zuly says that she finds herself dozing off at all hours of the day. Ricardo says, “I really sympathize with you,” I really understand your problem or your difficult situation; I feel sad for you, “but,” he says, “these days (these early days) will pass quickly (they will not seem like they took very much time), and then you’ll have such great memories.” “Memories” are the things that you remember. Ricardo then asks Zuly, “Have you had much sleep?” and Zuly is sleeping; she goes, “Zzzzzzzz!” Ricardo says, “Zuly? Zuly?” trying to wake her up.
I hope you didn’t doze off during this episode. Now we’ll listen to the dialogue at a normal rate of speech.
[start of dialogue]
Zuly: Hello.
Ricardo: Hi, Zuly. How are you?
Zuly: Oh, Ricardo, it’s you. I’m doing okay. How are you?
Ricardo: I wanted to call and congratulate you on the birth of your new baby.
Zuly: Thanks a lot. Carla was born three weeks ago, and she was eight pounds, three ounces.
Ricardo: That’s great! How does it feel to be a first-time parent?
Zuly: It’s really overwhelming taking care of a newborn. I’m learning everything from scratch, everything from how to breastfeed and bottle-feed, to burping her, to putting her to bed, to using a car seat and a stroller.
Ricardo: You sound overwhelmed. I remember when Adam, our first child, was born. There were the feedings in the middle of the night, and all of those diapers!
Zuly: Exactly. I’m exhausted all the time. In fact, I find myself dozing off at all hours of the day.
Ricardo: I really sympathize with you, but these days will pass quickly, and then you’ll have such great memories. Have you had much sleep?
Zuly: Zzzzzzzz!
Ricardo: Zuly? Zuly?
[end of dialogue]
All of our scripts here at ESL Podcast are written from scratch by our very own Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
birth – when a new child is brought into the world; when a baby comes out of his or her mother’s womb and begins breathing on its own
* How many births happen in this hospital each year?
first-time parent – a person who has one child, perhaps with plans to have other children in the future
* As first-time parents, we took our son to the emergency room for every little cough or scrape, but once we had our second child, we were much calmer.
overwhelming – too strong and powerful, making one feel out of control, confused, and/or powerless
* He says his new job is overwhelming and he has to work 12 hours each day just to keep up!
newborn – a baby that has been born very recently, usually within the past one to two months
* Newborns are supposed to eat every two hours, but that means the parents don’t get very much sleep.
from scratch – from the very beginning, without any initial knowledge or preparation
* Have you ever made a cake from scratch, or do you always buy a box of pre-made mix?
to breastfeed – for a mother to feed a child with the milk from her breasts; for a child to drink a mother’s milk by sucking at her nipples
* If your baby breastfeeds in the wrong position, you might experience pain or even bleeding.
to bottle-feed – to feed a baby from a bottle (a glass or plastic container with a special nipple-like top)
* Doctors say it’s important to hold a baby close and look into his or her eyes while bottle-feeding the child.
to burp – to gently and repeatedly hit a baby’s back after he or she has drunken milk to help the baby push air that is in the stomach out of his or her mouth
* Always put a cloth over your shoulder before burping the baby, or she might throw up on you.
to put (someone) to bed – to get a baby or child ready for bed and calm him or her until he or she falls asleep
* Their routine for putting Samson to bed includes brushing his teeth, reading books, singing songs, and telling stories.
car seat – a special chair put inside a car for babies and very young children, to keep them safe in an accident
* If the car seat is installed correctly, it shouldn’t move more than one inch from side to side.
stroller – baby carriage; a small cloth seat on a plastic or metal frame with wheels, used by walking parents to push a child in front, often with room to store bags underneath the seat
* Once their daughter learned how to walk, she never wanted to ride in the stroller again.
feeding – one period of time when a baby is drinking milk from a bottle or nursing (drinking milk from a mother’s breast)
* How many feedings does a newborn need each day?
diaper – a piece of cloth or paper and plastic that is wrapped around a baby’s bottom to hold urine (pee) and feces (poop)
* It’s important to change a baby’s diaper frequently so that the skin doesn’t become irritated.
exhausted – extremely tired, usually from doing too much physical activity or from not sleeping enough
* Sandy was exhausted after running the marathon.
to doze off – to fall asleep for a short period of time, usually without planning to do so; to nap
* Professor Graves gets really angry when his students doze off during class.
to sympathize – to understand someone else’s problems or the difficult situation that another person is in, feeling sad much like the other person is feeling sad
* I really sympathized with Patty when her mother passed away, because my mother had passed away just a few months earlier.
memory – what one remembers about something that happened in the past
* Do you have any memory of when humans first walked on the moon, or were you too young then to remember it?
Comprehension Questions
1. What does Zuly mean when she says she’s “learning everything from scratch”?
a) She’s learning how to treat the baby’s cuts and scratches.
b) She’s learning how to care for her cat.
c) She’s learning everything for the first time.
2. What does Zuly mean when she says she has been “dozing off at all hours of the day”?
a) She has been sleeping longer than usual.
b) She always wants to sleep.
c) She often falls asleep throughout the day.
Answers at bottom.
What Else Does It Mean?
scratch
The phrase, “from scratch,” in this podcast, means from the very beginning, without any initial knowledge or other preparations: “Did you build that table from scratch, or was the wood already cut to the right size?” A “scratch” is normally a small cut in someone’s skin: “The cat’s claws left several scratches on Noah’s arm.” A “scratch” can also be a small scrape or mark on another surface: “The wooden floors have scratches where the furniture was dragged over it.” Or, “The music quality isn’t very good, because the CD has a scratch.” Finally, a “scratch” can be the sound of two things moving against each other: “During the power failure, we couldn’t see grandpa, but we heard the scratch as he lit a match for the candle.”
feeding
In this podcast, the word “feeding” means one period of time when a baby is drinking milk: “Do you and your husband share the nighttime feedings, or does just one of you wake up to warm the bottle each time?” The verb “to feed” also means to give food to an animal: “Each morning, the farmer wakes up early to feed the cows and pigs.” The verb “to feed” can also mean to provide enough food for a certain number of people: “This recipe is supposed to feed eight people, but our family of four finished the entire casserole at one meal.” Finally, the verb “to feed” can mean to put something into something else: “Eddy fed coins into the payphone every few minutes as he spoke with his girlfriend.”
Culture Note
First-time parents are “eager” (wanting to do something) to learn how to take care of their children. Even before the baby is born, many “expectant” (pregnant; expecting a baby) parents look for information by reading books and informational websites.
One popular “book series” (a group of related books) is called What to “Expect” (anticipate; believe will happen in the future). The first book to read is What to Expect When You’re Expecting. It is filled with information about what women should expect while they are pregnant. It “covers” (discusses; talks about) changes in the pregnant woman’s body, changes in the “fetus” (the developing baby), “potential” (possible) medical problems, and how to prepare for the process of giving birth.
The next book, What to Expect the First Year, teaches parents many of the things they need to know to take care of their babies. It includes information about “sleep schedules” (how often and for how long someone needs to sleep), breastfeeding, bottle-feeding, and bathing, as well as medical information covering “first aid” (how to treat minor injuries) and “vaccinations” (injections to prevent diseases). Other books in the series tell parents what to expect when children are in the “toddler years” (ages 2-3), what the father should expect during pregnancy, and more.
Websites are becoming increasingly popular sources of information for expectant and first-time parents. Many websites allow parents to “enter” (type information) their “due date” (the day when a baby is expected to be born) and receive weekly emails with information “applicable” (related) to their stage of pregnancy and, later, their child’s “development” (how a child changes and matures over time). These website have the “advantage” (good thing; benefit) of letting parents interact with each other, asking questions and getting answers from people who are “going through” (experiencing) the same things.
Comprehension Answers
1 - c
2 - c