= 0627
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 627: Being Spontaneous or Well-Planned.
This is English as a Second Language Podcast episode 627. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the beautiful City of Los Angeles, California.
This podcast has a website at eslpod.com. Consider supporting this podcast by becoming a member, you can get more information on our website.
This episode is called “Being Spontaneous or Well-Planned.” These are opposite things, as we will learn from Mariela and Will. Let’s get started.
[start of dialogue]
Mariela: Wow, it looks like you’re working on a big project. What are all these pages and pages of notes for?
Will: I’m preparing for my date with Christine. I want everything to be well-planned and to go without a hitch.
Mariela: Okay, but I still don’t understand why you’re making such detailed plans.
Will: I want to be ready for every contingency. For instance, I planned a picnic, but if it rains, I’ll take her to lunch at the Garden Café instead.
Mariela: Don’t you think you’re taking the spontaneity out of your date? Why don’t you play it by ear? I know you don’t like to fly by the seat of your pants, but maybe she’ll have some ideas about what she’d like to do.
Will: Oh, I’ve taken her preferences into account. If she wants to do something active, we can go bowling or take a long walk. If she prefers something more passive, we’ll go to a movie.
Mariela: Well, it sounds like you’ve mapped out every possible alternative. Hey, what’s this?
Will: Give me that!
Mariela: I see you’ve mapped out more than just your date. You mapped out the entire trajectory of your life together: Get married in two years, have your first child two years after that…
Will: That is not meant for you. And plus, it’s just a tentative plan…
Mariela: You mean Christine will have some say in it?
Will: I may let her pick our children’s names. Now, get out of here, will ya?!
[end of dialogue]
Mariela begins by saying, “Wow, it looks like you’re working on a big project (a large task). What are all these pages and pages of notes for?” “Notes” is information that you write down sort of informally when you are thinking about an idea or are listening to someone. We use the expression “to take notes,” for example at a meeting somebody takes notes – somebody writes down everything that is discussed and decided. Or a student can take notes in school, writing down what the teacher or professor says.
Well, Mariela sees pages and pages, which is a way of saying a lot of pages of notes, and wants to know what they are for – why does he have them? Will says, “I’m preparing for my date with Christine.” A “date” is, of course, a romantic appointment where you meet someone you are romantically interested in. He says, “I want everything to be well-planned and to go without a hitch.” “To be well-planned” means you know exactly what’s going to happen sometime in the future. You know what you’re going to do first, second, and third. Most people don’t think about romantic dates as being well-planned. Planned perhaps, you have an idea, but well-planned gives the idea that it’s almost going to be a schedule that you will follow. But Will says he wants his date to go without a hitch (hitch). “Without a hitch” means without any problems, without any difficulties.
Mariela says, “Okay, but I still don’t understand why you’re making such detailed plans,” plans that include exactly everything that is going to happen. Will says, “I want to be ready for every contingency.” A “contingency” is something that might happen in the future and could change your plans because it causes problems or difficulties. So if you have a contingency for rain when you are planning, say, a party outside, that means that if it rains you have something you’re going to do to prevent the party from being cancelled. Perhaps you are going to move everyone into your garage or inside of your house or inside of your neighbor’s house – you probably should ask them first! That’s a contingency, a plan for something that might go wrong in the future. Will says, “For instance, I planned a picnic, but if it rains, I’ll take her to lunch at the Garden Café instead.” See, if it rains he has a plan about what he’s going to do instead of the original plan.
Mariela says, “Don’t you think you’re taking the spontaneity out of your date?” “Spontaneity” (spontaneity) is the opposite of well-planned; it’s doing things without planning them first, just doing them right at that moment. Mariela thinks that Will is taking the spontaneity out of his date, meaning he’s eliminating. “To take out of” means to eliminate, to get rid of. She says, “Why don’t you play it by ear?” The expression “to play (something) by ear” (ear) means to be spontaneous, to have spontaneity, to decide at the moment what you’re going to do without making plans. This expression actually has another meaning in English, and that can be found in our Learning Guide for this episode. Mariela says, “I know you don’t like to fly by the seat of your pants, but maybe she’ll have some ideas about what she’d like to do.” “To fly by the seat of your pants” is another way of saying to be spontaneous, to have spontaneity, to decide without making plans in advance. Sometimes we use this expression in a negative way to describe someone who should have planned but didn’t.
Will responds, “Oh, I’ve taken her preferences into account.” “Preferences” are your desires, the things that you want. “To take (something) into account” (account) means to consider what someone else is saying or to consider that other thing. “To take someone’s preferences into account” means to think about what they want and make that part of your plan. He says, “If she wants to do something active, we can go bowling or take a long walk.” “Active” here means with a lot of physical movement; not just sitting or standing around and talking, but actually doing something, perhaps some sport or something athletic. The opposite of “active” is “passive,” this is when you just let things happen; you don’t try to change things, you don’t get up and walk around or do a lot of things. Will says if his date, the women he’s going on the date with, prefers something more passive, we’ll go to a movie. Mariela says, “Well, it sounds like you’ve mapped out every possible alternative.” By the way, I should mention that “active” can have other meanings in English, and those you can find in the Learning Guide. Now, “to map out (something)” is a two-word phrasal verb which means to decide or determine something: “I’m going to map out my plans for tomorrow.” I’m going to write them down; I’m going to make some decisions. So when Mariela says, “it sounds like you have mapped out every possible alternative,” she means that Will has planned for every possible alternative. “Alternative” is possibility, choice, or option.
Then Mariela sees something, she says, “Hey, what’s this?” Will says, “Give me that!” He’s obviously angry at Mariela for taking it. Mariela says, “I see you’ve mapped out more than just your date (what you’re going to do on your romantic date). You mapped out the entire trajectory of your life together.” A “trajectory” is the direction that something follows over time. We usually use this, for example, when talking about a ball that you throw, or a rocket – a rocket engine that goes up into the sky – a missile. The trajectory is the path that it takes. Well, it can also be used to talk about the events or things that will happen in the future in someone’s life, and Mariela sees that Will has mapped out or planned the entirety trajectory of his life together with his date: Get married in two years, have your first child two years after that. Of course this is very unusual, especially since this appears to be the first date that Will has with this woman!
Will says, “That is not meant for you.” “To be meant for” means to be intended for, with you wanting something to happen. “This is meant for you,” this is intended for you, I’m doing this for you. Well, the note is not intended for – it’s not meant for Mariela to look at; she’s not supposed to see it. Will says, “And plus (meaning in addition), it’s just a tentative plan.” “Tentative” (tentative) means possible but not yet final, not definite, not certain. This is what I think will happen but it may change – my plan may change.
Mariela says, “You mean Christine will have some say in it?” “To have a say in (something)” or “to have some say in (something)” means to be participating in a decision, to have your opinions and your ideas matter in the decision. You’re part of the decision. Will clearly thinks he will make most of the decisions. He does say, “I may (meaning it’s possible) let her pick our children’s names,” select the names for the children. That’s the decision that Will’s date Christine will be given. He then says to Mariela, “Now, get out of here, will ya?!” “Get out of here” means leave. We use this expression “will you,” often spelled and pronounced “will ya” (ya), to ask someone to do something. It’s an informal, very informal way of asking someone to do you a favor – to do something for you. “Will ya give me that pen?” meaning please give me that pen, that is what I want you to do. Will is using it at the end of the sentence, and that sometimes indicates that you are angry with the other person: “Stop talking to me, will ya?” You’re telling the person something you don’t like about what they are doing; you’re indicating, that is, that you are not happy. And Will is not happy that Mariela saw this note that he wrote for himself, planning out his entire life with his date Christine. Poor Christine!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Mariela: Wow, it looks like you’re working on a big project. What are all these pages and pages of notes for?
Will: I’m preparing for my date with Christine. I want everything to be well-planned and to go without a hitch.
Mariela: Okay, but I still don’t understand why you’re making such detailed plans.
Will: I want to be ready for every contingency. For instance, I planned a picnic, but if it rains, I’ll take her to lunch at the Garden Café instead.
Mariela: Don’t you think you’re taking the spontaneity out of your date? Why don’t you play it by ear? I know you don’t like to fly by the seat of your pants, but maybe she’ll have some ideas about what she’d like to do.
Will: Oh, I’ve taken her preferences into account. If she wants to do something active, we can go bowling or take a long walk. If she prefers something more passive, we’ll go to a movie.
Mariela: Well, it sounds like you’ve mapped out every possible alternative. Hey, what’s this?
Will: Give me that!
Mariela: I see you’ve mapped out more than just your date. You mapped out the entire trajectory of your life together: Get married in two years, have your first child two years after that…
Will: That is not meant for you. And plus, it’s just a tentative plan…
Mariela: You mean Christine will have some say in it?
Will: I may let her pick our children’s names. Now, get out of here, will ya?!
[end of dialogue]
Our scriptwriter never plays it by ear; she never flies by the seat of her pants. Oh, no, her scripts are always well-planned. That’s because she’s the one, the only, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
notes – information that is written down informally to help one develop an idea or remember something in the future, usually intended only for oneself
* Jackie always takes notes when she speaks with clients over the phone, so that she doesn’t forget what was said.
well-planned – with a clear idea of what should and will happen at a future time
* His education has been well-planned: four years getting a degree in biology, then a master’s degree in microbiology, and finally a doctorate in infectious diseases.
without a hitch – without any problems or difficulties; problem-free
* After months of planning and coordination, we were really pleased to see the conference go without a hitch.
contingency – an event that might happen in the future and could change one’s plans or create problems or difficulties
* Do you have a contingency plan for your outdoor wedding, just in case the weather is bad?
spontaneity – the ability to do things as one wants to do them in that moment, without planning or thinking about them ahead of time
* While they were dating, Mariah really appreciated Hans’ spontaneity, but once they got married, she became frustrated by the way he never wanted to plan things ahead of time.
to play (something) by ear – to be spontaneous; to decide what to do at the moment based on the information available then, but not plan anything ahead of time
* I’d like to have dinner with you tonight, but let’s play it by ear, because I’m not sure how late I’ll need to work this evening.
to fly by the seat of (one’s) pants – to be spontaneous; to decide what to do at the moment based on the information available then, but not planning ahead of time
* Their business is growing so quickly that all the employees are flying by the seat of their pants, doing their best to finish their work, but never having time to plan for the next week or even the next day.
to take (someone’s) preferences into account – to consider what someone likes and dislikes and plan accordingly
* The fashion designer took the actress’s preferences into account when making a dress for her to wear to the awards ceremony.
active – with a lot of physical movement, not just sitting or standing in one place
* Children who are active are less likely to be overweight than children who watch a lot of television.
passive – without one’s active involvement; letting things happen, observing them but not trying to control or change what happens
* People are dying of hunger! How can you be so passive and just watch it happen on the news without trying to help?
mapped out – decided and determined; with a clear plan
* Their vacation is all mapped out and they know exactly what they’ll be doing each day.
alternative – choice; option; possibility
* You have two alternatives: you can cooperate with the police and tell them everything you know, or you can be arrested.
trajectory – the direction that something follows over time
* His career is on a rapid upward trajectory, and if it continues, he’ll be CEO within a few years.
meant for – intended for; with one wanting something to happen
* That car bomb was meant for the prime minister, but fortunately it exploded when nobody was near it.
tentative – possible, but not yet finalized; a draft; not definite; not certain
* This is just a tentative budget. We’ll have more accurate numbers once the salary negotiations have ended.
to have some say in (something) – to be able to participate in a decision; to have one’s opinions and beliefs matter in a decision
* In some cultures, parents arrange marriages for their children without letting them have any say in whom they marry.
will ya? – an informal phrase used to ask someone to do something
* Bring me a beer, will ya?
Comprehension Questions
1. Which of these things would not be done by someone who is spontaneous?
a) Play it by ear.
b) Fly by the seat of his pants.
c) Map out every possible alternative.
2. What does Will mean when he says that he wants everything to go “without a hitch”?
a) He doesn’t want to have any problems.
b) He doesn’t want to get married.
c) He doesn’t want to do anything involving a trailer.
Answers at bottom.
What Else Does It Mean?
to play (something) by ear
The phrase “to play (something) by ear,” in this podcast, means to be spontaneous, or to decide what to do at the moment based on the information available then, without planning anything ahead of time: “We want to move as soon as possible, but we’ll have to play it by ear, because we can’t move until our house sells.” The phrase “to grin from ear to ear” means to have a very big smile because one is very happy: “When they offered him the job, he grinned from ear to ear.” The phrase “to be up to (one’s) ears in something” means to have a lot of something: “Billy has been up to his ears in work all week.” Finally, the phrase “to be all ears” means to really want to hear what someone is going to say: “Tell us about your date! We’re all ears.”
active
In this podcast, the word “active” means with a lot of physical movement, not just sitting or standing in one place: “Basketball is much more active than baseball, because baseball players spend a lot of their time standing in one place.” The word “active” also means involved in something: “As a college student, Marcellus was very active in student government.” The phrase “active participation” is used to describe heavy involvement in something: “We really appreciate the active participation of all our volunteers.” The word “active” can sometimes mean current, describing something that is happening at the moment: “Marlys was an active donor for years, but then she suddenly stopped sending donations.” Finally, an “active volcano” is a volcano that might explode anytime: “Is Mount Rainier an active volcano?”
Culture Note
Jack Kerouac (1922-1969) was a well-known American author and poet. Many people call him the “father of” (the man who led) the Beat movement, which describes the work of a group of American writers in the mid-1900s. They “pushed the boundaries” (tested the limits; went beyond expectations) of what was acceptable in published literature by writing about drugs, sex, and other “taboo” (not talked about in general society) topics.
Kerouac’s most well-known novel, On the Road, was published in 1957. It is about some of the “road trips” (long trips taken by car, often driving across the country) he took with his friends. The book was very “influential” (changing one’s thoughts and beliefs) for many other writers, actors, and musicians.
Kerouac often described his own writing style as “spontaneous” (done in the moment, without planning something ahead of time) “prose” (written language that is not poetry). In literature, this is often called “stream of consciousness,” which is a “technique” (way of doing something) where writers write down their thoughts as they think of them, without changing or editing them. With this style of writing, there are usually many “run-on sentences” (very long sentences that include many words like “and” and “but”) and “incomplete sentences” (phrases that are not a full sentence).
However, many people who knew Kerouac say that he didn’t actually write in spontaneous prose. They say that the way he talked about writing “didn’t match” (wasn’t the same as) the way he actually wrote. They say that “in reality” (actually) he revised what he wrote many times before it was published.
Comprehension Answers
1 - c
2 - a