= 0631
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 631: Customizing a Personal Webpage.
This is English as a Second Language Podcast episode 631. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode that will help you improve your English even faster.
This episode is called “Customizing a Personal Webpage.” Many people have their own pages – their own websites. We’ll talk about some of the vocabulary that might be related to that, especially on social networking sites such as Facebook. Let’s get started.
[start of dialogue]
Keiko: The layout of your webpage is so lame. Why don’t you customize it?
Al: Why bother? I don’t want to spend the time or the energy.
Keiko: Let me show you my page. Check out this background. Don’t you think it’s great?
Al: Yeah, it’s great. Can I get back to my book now?
Keiko: You haven’t even looked at my page. Look at this. You can add all kinds of graphics and you can use the profile editor to list information about yourself: your hometown, your likes and dislikes, your relationship status, your mood, everything! You can link to or upload photos and videos, too. I even have a custom cursor and this scrolling text across the top
Al: Yeah, it’s all great, but kind of dizzying.
Keiko: You haven’t even seen my animated gifs. This funny baby will dance across the page, look!
Al: Thanks for the suggestions, but I think I’ll stick to a simple, uncluttered page. How long did it take you to do all of that?
Keiko: How long? Maybe a few hours.
Al: I’d rather spend a few hours reading a good book.
Keiko: Suit yourself. Maybe that’s why you have 22 “friends” and I have 200.
Al: Clearly your time has been better spent.
[end of dialogue]
Our dialogue begins with Keiko saying to Al, “The layout of your webpage is so lame.” The “layout” is the position of things either on a piece of paper or here on the computer screen: where you have your photos, where you have your writing – your text. The position of things on the screen or on a page, in this case a webpage, is the layout. “Lame” (lame) used to mean, and still does, someone who has injured themselves, someone who is handicapped, who hurt their arm or their leg. Now it’s used more informally as meaning uninteresting, boring, not cool. “Lame” is a little bit dated now, it was more popular I think in the 90s, but it’s still used. Keiko says, “Why don’t you customize it?” meaning the webpage. “To customize (something)” is to change something so that it is unique; it is unlike anything else. Here it means also, I think, to personalize, to make the page reflect the person behind it. That is, the page will somehow show you who this person is.
Al says, “Why bother?” “Why bother?” is an informal phrase used to show that you think the suggestion that someone is giving you is a waste of time; you don’t want to do it. You can use it by itself, “Why bother?” or you can be more specific and say, “Why bother customizing my website?” Notice that the verb after the word “bother” is an “ing” form. “Why bother going to the movies when you can watch the movie for free here on television?” Al says, “I don’t want to spend the time or the energy.”
Keiko says, “Let me show you my page. Check out this background.” “Check out” means take a look at; investigate. “Background” is the large area of a piece of paper or a computer screen behind what you are looking at. Normally it’s just white, but you could have different colored backgrounds. The background is what everything else is on, if you will, in this case. “Background” has a couple of different meanings, however; take a look at the Learning Guide for some additional explanations. She says, “Don’t you think it’s great?” Don’t you think my page is great Keiko means. Al says, “Yeah, it’s great. Can I get back to my book now?” “Can I get back to” means I want to return to doing what I was doing before. We often say it when we are trying to indicate to the other person that they are bothering us, they are taking up our time.
Keiko says, “You haven’t even looked at my page. Look at this. You can add all kinds of graphics and you can use the profile editor to list information about yourself.” “Graphics” are small pictures or symbols that are used to makes something more interesting looking, a design, pattern that also can sometimes make the writing clearer; it indicates what is going on in the writing part of a piece of paper or a page on the web. The “profile editor” is something that you will find in social networking websites such as Facebook or Twitter that allows you to control the information that other people see about you. It will allow you to select information that you want to tell other people, and who gets to see that information. The information on this profile editor, according to Keiko, includes your hometown, your likes and dislikes, your relationship status, and your mood. Your “hometown” (one word) is the place where you were born, the place where you grew up. My hometown is St. Paul, Minnesota. Your “likes and dislikes” are, obviously, the things that you like and the things that you don’t like. Your “relationship status” is whether you are married; whether you are single; whether you are dating, you have a boyfriend or a girlfriend; it could that you are engaged, you are going to get married; it could be that you are divorced, you used to be married; or it could be that you are widowed, your husband or wife died. That’s your relationship status. Your “mood” (mood) is the way you feel at a particular moment in time. I’m in a good mood means I’m happy, I’m in a bad mood means I’m sad or angry.
Keiko says, “You can link to or upload photos and videos, too.” “To link to (something)” means to make your webpage – a part of your webpage such that when you click on it, it takes you to a different page or a different part of a page. We call these “hyperlinks,” usually they are underlined on a website, and often a different color, blue is most common. That is to link to something. “To upload” means to put a file, like a picture or a music file, onto another computer called a “server,” and that server is connected to the Internet so that other people can look at or download that file. Download is the opposite of upload. Upload you put it up to a server – you put it on a server; to download means you take it off – you make it part of your own computer.
Keiko says, “I even have a custom cursor and this scrolling text across the top.” Something that is “custom,” as we learned earlier with the verb “customize,” is something that is special to you, something that is unlike other things. A “cursor” (cursor) is a special graphic on your computer screen that tells you where the mouse is or where whatever you may be typing will appear. Keiko says she has a custom cursor and scrolling text. “Text” is just another word for words. “Scrolling” is something that moves across the screen or up and down the screen, usually somewhat slowly. At the end of a movie or a television program, for example, there are what are called “credits,” the list of names of all the people who worked on that movie or show, and these usually “scroll,” meaning they move slowly. Especially for a movie you see this more often, the names will go from the bottom of the screen slowly up to the top of the screen almost as if they were on a wheel, turning around. That’s scrolling text.
Al says, “Yeah, it’s all great, but kind of dizzying.” “Dizzying” (dizzying) means something that makes you feel dizzy. “To feel dizzy” means that your head is sort of spinning; you are not exactly sure where you are perhaps. If someone hits you on the back of the head or spins you around in a circle, around and around, you may get dizzy. You won’t be able to walk straight, at least for a few minutes. Here, “dizzying” means that it’s too complicated, it’s too much, and it is confusing to Al.
Keiko says, “You haven’t even seen my animated gifs (or jifs).” The word (gif) is actually an acronym. It is a word that comes from different words – the first letter of three different words; (gif) stands for graphics interchange format. It’s pronounced by some people as “jif,” other people pronounce it “gif.” I think “jif” is the original pronunciation. In any case, it is a small file that is a picture or a photo or a design of some type. “Animated” means that it is moving somehow; there is movement in the little picture. These were very popular when the web first got started in the 1990s. I remember in 1993 or 4 when I first started using the Internet you would see a lot of these. They are not quite as common, fortunately, anymore, but that’s what Keiko has on her webpage. She says, “This funny baby will dance across the page, look!”
Al says, “Thanks for the suggestions, but I think I’ll stick to a simple, uncluttered page.” “To stick to” means I’m going to stay with what I have right now, or I am going to only do this. He’s going to stick to an uncluttered page. “Uncluttered” means that it isn’t messy; it’s the opposite of confusing, it’s the opposite of too much, of disorder. Uncluttered would be very simple, without anything unnecessary on the page.
Al says, “How long did it take you to do all of that?” Keiko says, “How long? Maybe a few hours.” Al says, “I’d rather spend a few hours reading a good book.” Keiko says, “Suit yourself (meaning you do what you want to do; if that’s what you like). Maybe that’s why you have 22 (quote unquote) ‘friends’ and I have 200.” On Facebook you can get friends, people who are able to look at your website. A friend isn’t necessarily a friend; it’s often just somebody who knows who you are. Many people try to get as many friends as they can; that’s often a sign of what we call “narcissism,” which is the belief that you are the most important thing in the world. We have a lot of that nowadays!
Anyway, Keiko has 200 friends on her social networking site, probably Facebook, and Al only has 22. Al says, “Clearly your time has been better spent.” “Better spent” means used in a better way, in a more productive way. However, Al is being sarcastic; he’s making a joke. He means the opposite of what he says. He’s saying that Keiko has wasted her time getting these webpages customized and having all of these quote unquote friends. When we say “quote unquote” we mean in this case that they’re not really friends. Once again it’s the opposite, in some ways, of what you are saying.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Keiko: The layout of your webpage is so lame. Why don’t you customize it?
Al: Why bother? I don’t want to spend the time or the energy.
Keiko: Let me show you my page. Check out this background. Don’t you think it’s great?
Al: Yeah, it’s great. Can I get back to my book now?
Keiko: You haven’t even looked at my page. Look at this. You can add all kinds of graphics and you can use the profile editor to list information about yourself: your hometown, your likes and dislikes, your relationship status, your mood, everything! You can link to or upload photos and videos, too. I even have a custom cursor and this scrolling text across the top
Al: Yeah, it’s all great, but kind of dizzying.
Keiko: You haven’t even seen my animated gifs. This funny baby will dance across the page, look!
Al: Thanks for the suggestions, but I think I’ll stick to a simple, uncluttered page. How long did it take you to do all of that?
Keiko: How long? Maybe a few hours.
Al: I’d rather spend a few hours reading a good book.
Keiko: Suit yourself. Maybe that’s why you have 22 “friends” and I have 200.
Al: Clearly your time has been better spent.
[end of dialogue]
Why bother listening to other English podcasts when you have the wonderful scripts by Dr. Lucy Tse?
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
layout – the position of text, photos, and graphics on a piece of paper or screen; the way a page has been designed
* When Clarke was hired as the new graphic designer for the magazine, he immediately changed the layout.
lame – not cool; uninteresting and boring
* Staying home to watch TV on a Friday night is so lame! Let’s go do something else instead.
to customize (something) – to personalize; to change something so that it is unique, unlike anything else, often to reflect the characteristics of a person, company, or brand
* We can customize our software to meet your company’s specific needs.
Why bother? – an informal phrase used to show that one thinks something is a waste of time and doesn’t want to do it
* - Please make your bed.
* - Why bother? I’m just going to sleep in it again tonight.
background – the large area of a piece of paper or screen behind what one is reading or looking at, normally just white, but sometimes with other colors, designs, or photos
* It’s easiest to read black text on a white background.
graphics – small pictures, symbols, or icons used to make printed or electronic information more interesting
* Do you prefer the graphics in the old or new version of this software?
profile editor – a tool in a social networking website that allows one to control what information is displayed when people look at one’s page
* The profile editor allows you to select the information other people can see when they visit your website, such as your hobbies and your birthday.
hometown – where one is from; the town or city where one was born and raised
* Fran has lived in Atlanta for more than 10 years, but her hometown is Fairbanks, Alaska.
relationship status – whether one is single, dating, engaged, married, divorced, or widowed
* When Olivia updated her relationship status from engaged to single, she started receiving a lot of emails from men who wanted to date her.
mood – the way one feels at a particular moment in time
* Getting a parking ticket put me in a really bad mood.
to link to – to include a hyperlink (underlined words that, when clicked, take someone to another webpage) to another webpage or another part in the current page
* Let’s make sure our website includes a link to our email address so that customers know how to contact us.
to upload – to put a file on a server so that it can be accessed from a website or email and is no longer stored only on one’s own computer
* Don’t forget to upload the attachments to your email before you click “send.”
custom cursor – a special graphic that indicates where the mouse is on a webpage
* Why do you use a boring white arrow as a cursor? You could have a custom cursor instead, like a yellow happy face.
scrolling text – words that move across a screen
* I like watching CNN News, because I can read scrolling text at the bottom of the screen to learn about current events while I’m listening to the reporters talk about another story.
dizzying – making one feel dizzy or disoriented, as if one might fall down or faint
* Don’t you find it dizzying to fly up so high?
animated gifs – small graphics that change or move in a certain way on a computer screen
* She puts a lot of animated gifs in her emails, mostly using small faces that smile or blink their eyes in surprise.
uncluttered – bare; without unnecessary objects or elements; plain
* Their house is surprisingly uncluttered, considering how many people live there.
better spent – used in a better, more productive, or more fulfilling way
* Are you going to spend your entire summer vacation at the swimming pool? Your time could be better spent working on college applications.
Comprehension Questions
1. What does Al mean when he says that Keiko’s page is “kind of dizzying”?
a) There is too much to look at.
b) It is very professional.
c) It looks too childish.
2. What would you expect to see on an uncluttered page?
a) A white background.
b) Scrolling text.
c) Animated gifs.
Answers at bottom.
What Else Does It Mean?
background
The word “background,” in this podcast, means the large area of a piece of paper or screen behind what one is reading or looking at: “I like the idea of using a photograph as the background for this flyer, but I’m afraid it will make it difficult to read the text.” The word “background” also refers to one’s experiences, education, jobs, family, and more: “The company wants to hire someone with a background in international sales.” Or, “How do you feel about your son marrying someone with a different religious background?” The phrase “in the background” refers to sounds that one can hear, but are not part of what one is trying to listen to: “Could you please speak more loudly? Your cell phone is picking up a lot of other sounds in the background.”
mood
In this podcast, the word “mood” means the way one feels at a particular moment in time: “Marsha was in a good mood for weeks after she won the lottery.” The phrase “mood swings” refers to rapid, unpredictable changes in how one feels: “A lot of teenagers have big mood swings, where they’re happily laughing one minute, but then angry or depressed just a few minutes later.” The phrase “to be in the mood for (something)” means to want to do something: “I’m in the mood for Chinese food. Let’s go to that new restaurant down the street.” Finally, the phrase “mood-altering” is used to describe drugs that change the way one feels: “Mood-altering drugs might make you feel good for a while, but they can have some very dangerous long-term consequences for your health.”
Culture Note
Many young children use “social networking sites” (websites that allow people to interact with each other) to communicate with their friends and “distant” (living in another place far away) family members. However, they are not always aware of the “implications” (what can happen as a result of something) of sharing personal information on social networking sites. This makes children “vulnerable” (able to be hurt by) to “predators” (people who want to hurt children) if nobody is watching or monitoring how they use social networking sites.
Parents cannot monitor everything their children do on social networking sites, but they can use “parental controls,” or software features that allow parents to set limits on how the software can be used by their children. For example, the parental controls on many social networking sites let parents “restrict” (limit) access to the information their children put online. They can change the settings so that anyone who wants to see their child’s page must first be “approved” (saying that something is okay) by the parents. Parental controls can also let the parents limit what type of information the children can put online. For example, the settings could make it impossible to share email addresses, telephone numbers, physical addresses, or photographs.
Parental controls “can only go so far” (cannot do everything), so it is also important for parents to discuss their “concerns” (worries) with their children. Many parents find it useful to explain the “dangers” (bad things that could happen) of social networking sites and encourage their children to let them know if they “encounter” (find) people who make them feel uncomfortable online or have other problems.
Comprehension Answers
1 - a
2 - a