
:toc:
:sectnums:

---

== 重要


==== ★★ 男怕入错行 -- 专业会带来阶层固化. 所以要做“难而正确的事”.


- 品牌、运营也要想，这位演员几年来的故事，你该怎么帮助他更好地暴露给观众？(*依然是替他人做嫁衣裳, 帮别人打造人气*)

- 综艺录制现场是一个会让人发疯的地方，因为**内容产业是非标行业，每次都是依赖人的，这就很扯。**一个综艺现场涉及上百人的协同，但这些人很可能是当天组织在一起的，然后发号施令的人有无数个，没有一次现场录制是不出故障的。*我们的策略就是全部前置，所有的团队要多年磨合，在一个岗位上一直做一件事情.(把人变成了固化的螺丝钉)*

- *要做“难而正确的事”. 否则, 你有一万个理由说服自己不去做，因为它难。但最后你绕着走费的能量，远远超过你直接面对它耗费的能量，而且你的青春不就蹉跎了吗？*

- 面对这么多不同的专业岗位，你快速学习、快速成长的心得是什么？我并不是刻意要去学习一些事情，而是为了更好地理解我当时所做的事情。比如说: +
-> 我在写稿的时候，为了更好地理解我的稿子能给观众带来什么影响，那我就得去看后期； +
-> 在写的时候，你又会发现前期策划不参与的话，有些东西就会非常受限制，我就很自然地去参与前期策划； +
-> 这些都做了你就会发现，如果你不上舞台, 你就很难理解现场的气氛。
+
想把一件事做好，就只能把这个行业里所有的事情打通。即: 要像项目负责人一样思考。我哪怕只是为了写好当时的一条段子，我也得像这个节目的制片人一样思考。事实是, 如果你一直像制片人这么思考的话，你最后就是会变成制片人。
+
在职场中，只要跨部门合作，你就要像那个部门的人那样思考，这样学得更快.

- 在那个混乱的情况下，就是需要有一个人站起来说，所有人都按我说的办。*虽然我说的也不一定对，但至少统一了。* +
但这样工作非常不好，因为如果经常性地需要用情绪做武器的话，就说明你身处在非常恶劣的职场环境中，所以后来我都靠流程来解决。

- 我经常劝年轻人，*不要害怕，你的上级把任务交给你的时候，预期就是你会搞砸。你为什么觉得他会把一个绝对不能搞砸的事情交给你呢?*

- 也沮丧，我觉得这是行业的问题，我改变不了，就走了。可我仍然是学到了很多东西，很多方法，该怎么做事，该怎么磨合。



---

==== ★ 成为思考底层逻辑的人

- "看"和"观察"是不一样的。看剧, 是站在观众角度做的事. 观察, 是站在导演角度做的事. 学习永远是学思路，学他是怎么想的.  +
*你要放弃"看"的乐趣，享受"观察"的乐趣, 在面对生活中的一切时, 都应该这样做.*

- 怎么利用好脱口秀的特点？怎么做出从没有过的喜剧节目？*都是我天天会琢磨的问题。* +
*你做某事, 或某种工作的第一条，自己得兴奋。如果你自己都做得不兴奋，那成果也许还能看，但绝对不会成。*

- 写作是最好的思考方式。

- 每次看到那些拍照的人，我都感觉他在打断自己"用双眼亲身感知世界"的生活。

---


==== 知行合一, 以赛代练

- 不能实践，就等于没有学。最好的学习，也是在实践中学。 要**"以赛代练"**.

- 错得够多了，自然就会了。你的量够吗？最重要的提升写稿能力的办法：天天写。还需要一遍一遍地去修改的。 +
所有理论知识, 在创作时可能都是想不起来的. 但，在修改创作时, 也许可以提供帮助.

---

==== ★ "完成"比"完美"重要


- *"完成"比"完美"重要。* +
我们想出来的梗，肯定永远不是最好的。*观众也不需要最好的。嘉宾也不需要最好的。它本身对不对, 并不是最重要的，它能解决问题就行了。*

- 批评家不是一个体面的职业，一些批评家沾沾自喜，all about me，字里行间显示的都是他这个人的厉害之处，他的目的, 就已经脱离只评论那个作品了。 +
对于脱口秀演员，我的建议就是，**如果不知道怎么甄别，那就别看那些批评。**什么都不要看，就写就好了。

---


==== 你表达出某个价值观, 就成为了"具有与你相同想法的人群"的代言人.

- 脱口秀是现实主义创作, 我们**一定是带价值观的**。 你在台上讲自己的生活，观察，看法，归根结底，就是在讲你的价值观。

- *想要更有效的传播，主题就需要和大家日常的"生活问题", "心理问题"有关系. 这件事会在你身上发生，说明也会在很多人身上发生。那就把它说明白，说透，说好笑了，就可以了。* +
如果你只讲特例孤例，你讲得过德云社吗？所以脱口秀演员的特长不在那里，而应该去发现人们心灵共通的一些现实问题。

- 常见的脱口秀表演，应该是在表演这两个人说话的逻辑问题，两个角色的冲突，两种价值观的抉择。 +
某些相声表演，只是在"演"，并不是为了"表达"什么. 虽然也好笑，但那不是脱口秀演员该追求的。否则你就丢了自己的优势 -- 价值观输出。
+
同样, 黄段子的核心在段子(价值观)，不在黄。光黄是没用的。


- 我们呈现自己价值观的目的，是找到观众中, 那些能和你产生某种"共鸣"的人. (这并不意味着他们的这个价值观100%跟你一样). *他们也可能不是真的理解，只是理解你的一个侧面。那就足够了。*

- 人在舞台上讲话，天然具备一些煽动性. 你要想清楚，你是一个喜剧演员, 还是一个演讲者。通常, 脱口秀, 目的是为了"共鸣", 而不是去改变尽可能多的人。


---

==== ★ 先情感上接受你, 才能在理性上接纳你.

- 表演的目的, 始终是让人相信. 而要让人相信, 你就得**真诚是第一位的。** 这样才能把你真实的价值观分享给他人。 +
脱口秀表演**就是让观众从相信你开始，慢慢理解你，爱上你。**

- **要让观众接受你，心理上拉近彼此，敲门砖只能是情绪。**之后, 你的理性(价值观)才能对他人发挥作用. +
*面对一个大脑，想要影响它，只能先从情绪进入，再去理性说服。*
+
很多演员在看完别人的表演后会说，“他今天都挺好，也没啥毛病，就是没劲儿。” 那就是没有投入情绪，或者你俩没有共鸣。
+
尽量在提出一个看法之前，先讲一个故事，先在情绪上拉近彼此，唤醒你对某些困境的情绪记忆，再说出你的观点. +
**不管你有多么伟大的发现，多么愤怒的批判，多么哲学性的洞察，请不要一开始就说理。** 更不用说对脱口秀, 你是来让大家笑的. *就算你要传道，也请先给大家一个听的理由。* +
我们需要他在舒服的前提下，再把那一点真实说了。
+
检视自己 : 有没有一上来就让观众觉得我是自己人？这儿能不能举一个更津津有味的例子？ +
吐槽是不需要技巧的，是人都会说. 但幽默是需要技巧的，就是让这些话能够出口，让听的人能接受.



- 演员拼到最后, 就是拼人格. 抛开一切演技，最终你吸引观众的，就是你藏都藏不住的人格。 +
电影明星为什么那么吸引人呢？虽然他演的角色不是他，但摄影机的特写拍下他的哭，他的笑，那些情绪都是真的. 你的情绪跟着他动，很容易就会爱上他。 +

- 演角色就是演弱点. 你的弱点就是人类的弱点; 你那份情绪，是人类共有的情绪。

- “牌品见人品”. 你甚至可以不说话，我就看你的打牌的打法, 表情、动作、身体语言，就知道你是一个什么样的人。同样, 人在舞台上是什么样，他在生活中就是什么样的。

- 播音腔，舞台腔，会影响真诚感。


---

==== 你必须要当众成长

- *人天然喜欢看成长，你要用五分钟的时间成长给他看，观众也会感觉自己在"成长"(幻觉)。 也许观众过几天就忘了, 但脱口秀就是制造“改变的幻觉”, 这就是作品的魅力。他就是这么爱上你的。*

- 电影和电视剧中的人物, 是有不同的:

[options="autowidth"  cols="1a,1a"]
|===
|Header 1 |Header 2

|电视剧中的主角
|大部分电视剧，特别是情景喜剧里的人物，基本是不变化的. 观众看的就是这么一个性格的人, 面对各种状况的反应。

|电影中的主角
|而电影对主角的要求，就是他要成长. 一番历险之后，结尾的主人公与开头的自己有了不同。电影所讲的人物故事, 就是关于改变的。

- 黑帮片, 拍来拍去其实就拍一件事：一个非常厉害的人物，曾经靠着什么崛起，最终又怎么因为同样的东西陨落。这个东西往往是性格。
- 一个非常普通的人物，曾经因为什么到处碰壁、惹人嫌弃，最终又怎么因为同样的东西成为英雄。这个东西往往还是性格。
|===


- 脱口秀故事, 类似于电影中的主角. 五到十分钟的讲述之后，你需要有一个成长变化. +
成长可以是你理解了你的父亲，走出了失恋阴影，也可以是戏弄了你愚笨的老板。 +
或者, 你也可以没解决任何问题，但是，你通过这五分钟让观众知道，你意识到了人生的无解 ——这也是一种成长，这是智慧的成长。

- 你讲的故事, 可以拆解成小情境与大情境:

[options="autowidth"  cols="1a,1a"]
|===
|Header 1 |Header 2

|小情境
|就是你的一个又一个段子，你在用这些小情境, 反复证明与拓展自己的价值观。

- 如果你有个段子经常忘，我的经验就是别讲。说明你就是不喜欢它。

|大情境
|就是你对整条线的主持. +
这是三个小情境，你中间要有一个逻辑线把它串起来的。大情境就是我怎么把这些串起来，能体现你人格的完整性, 和你的"成长".

*要有"起承转合", 就是你写的不能是趣事堆积，也不能是你几个不相干的好段子联排。你在五到十分钟里要完成层层推进，要有主题有人物有冲突，最终有一个像结局的结局。*
|===

---

==== 节奏感

什么是节奏？

- 节奏，就是先同步，再引领，然后无限循环。
- 一个人的节奏感，就是这个人在一个时间线上, 对信息量松弛的一个整体把控能力。

创造和感知节奏的能力, 就是节奏感.

*一定要让观众在心理上跟你是一头儿的，首先必须先"同步"，情绪，共鸣，都是为了同步。 接着, 一定还要"引领"，让观众对你表演的预测落空。* 还要无限循环, 不停找到同步，做出一点点引领，打破，重建，再同步，再引领。 +
这过程光想一想你就知道它是有节奏的。

听段子的过程中，你在等，就是"铺垫"; 你等到了，就是"梗"。 +
没等到，就是垮了.  +
如果你等的过程中走神了，那就是他没铺好。

有的演员是梗比较密，铺垫接梗，铺垫接梗，铺垫接梗. 有的演员是会铺很长，然后出来一个特别大的梗。 这就是不同的表演节奏. +
所谓的节奏就是嗒嗒/嗒，嗒嗒/嗒，有的人就是喜欢嗒嗒嗒嗒/嗒，也有的人就是喜欢嗒/嗒，嗒/嗒。

**好的脱口秀演员，节奏都是变的。**如果是五分钟，你可以一直嗒嗒/嗒，嗒嗒/嗒，嗒嗒/嗒，但你要是超过十五分钟用一个节奏，观众会疯的。




---


==== ★ 在台上要学会保护自己, 你进入的是职业角色，但下了台要尽快抽离情感。

- 表演老师在教表演时，会强调演员在台上要学会保护自己(无论是演反派角色, 还是悲惨人物)，要记住舞台上都是假的，你进入的是角色，虽然你要用真情实感来演，但下了台要尽快抽离。

- 脱口秀演员怎么抽离呢？保护自己呢？我的办法是: +
1. 做到只保证情绪永远是真的. 其他的文本可以是编造的，对人生故事可以做修改。
2. 在日常生活中, 就尽量活得真实，没有什么要遮掩的. 这样上了台也就不怕有什么会暴露。

- *脱口秀表演中的自我暴露, 是有分寸的暴露. 暴露, 目的不是为了把真实隐私说出来，而是把那种情绪带到舞台上。是"还原"那份心情。 故事的真实性并不重要, 怎么改头换面其实都可以， 关键是从中的"情绪"是真的.* +
*讲故事，还原那个故事, 你是在"还原"那个情绪.*

-你很难喜欢上嘉宾, 可以这样操作: 别把他想象成一个真人，你们可能这辈子都不会再见面了，你就当采访一个NPC（非玩家角色），就隔离那个情感。



---

==== ★ 关键是"还原"，不要"表演". 能用演的就不要讲，能代入角色就不要冷眼旁观。

- 你肯定遇到过这样的朋友，一件事你自己亲身经历，都不如他转述时好玩. *把一件事说得津津有味，是脱口秀演员表演的基本素质。*  +
如何做到呢？方法就是**把你要说的情境, "还原"在眼前。让听你说话的人仿佛看到了一样。**在说的时候，脑子里想着那情境 ——即使那情境是编造的。 *情境本身的真假不重要, 我们的表演任务，就是让它变成真的。*
+
在台上表演，脑子里应该是画面，而不是文字. 文字只是作为你的索引之用，是目录，情境才是真正要在舞台上展现的东西。

- *能用演的就不要讲，能代入角色就不要冷眼旁观。 能动的时候, 就不要干站着; 能用故事的，就不要说理。* +
比如我说 “昨天我跟我爸说，爸，上海户口办下来了”, “啊，怎么做到的”，而不是说，“我爸就问我，那你是怎么做到的”。这句话没有必要，直接就开始表演就好。
+
一个表演很好的人，这情境就会变得很大，有情绪高低，道具、家里的桌子椅子都能演出来。
+
关键是"还原"，不是"表演"。是"还原"你的观察，你的想象，不是"表演"你超强的模仿能力. *真正的好演员都是在"还原"，而不是在"演".*

- 你一开始做不到的话没关系，最基本的依然要去做，就是**把那些啰唆的话语都删掉。你的目的是"还原"那个情境，而不是"告诉"大家发生了什么事。**

- “我是该看观众, 还是该看镜头？” *这个问题是个伪问题，因为看哪里都有演的好的，看哪里也都有演砸了的。* +
只要你注意力集中，当你在表演两个人对话时，你不会去想"我该看哪里"，你的眼神自然在看你情境中与你对话的那个人。情境也会带着你看向你在台上那小小的却无尽的世界的每个角落。
+
最简单实用的办法：伸直右臂，手握拳，放在两眼焦点处，想象这个拳头在离你三米处，就盯着那儿. 不知道该看哪儿的时候, 就看着这个自制的虚空中的焦点。不要想观众也不要想镜头，就看它。相信我，这样无论在现场, 还是在镜头里看起来，你的注意力都是集中的。


---

==== ★ 你才是你自己的目的, 你的目的不是观众. "有意义的失败", 远远比"无意义的成功"有价值

- 在写作逐字稿时，就该想象你在台上什么样，你沉浸在一种什么样的情境中。观众会作何反应, 也应该是你想象的一部分。当然也会有失败，观众当然不会完全按照你的意思来，但我还是要说，**这才是有意义的失败.** 失败后，再调整自己的想象.
+
而如果观众不笑的时候，无助的你讲起了黄段子，*你开始疯狂地互动，像溺水的人在扑腾。你感觉自己像个要饭的，只要观众能笑，磕头都可以。但可惜磕头是没用的。*
+
**我做观众时，如果发现一个演员在讨好我，我是笑不出来的。脱口秀演员与观众的关系一定是平视的，你在分享价值观，**你在聚拢茫茫人海中与你感应的那一个个心理侧面，*这种动人的关系，不是能讨来的。*
+
去讨好观众，给观众磕头，就算观众笑了，那也是无意义的成功。*而"有意义的失败", 远远比"无意义的成功"有价值。*

- 失败演出后常常会找的原因：观众冷，话筒不对，光不好，前面的演员太炸... *这些都对，都是原因，但这些都是解释那一场为什么没炸的原因。它们不能解释你为什么没有成为一个越来越强的脱口秀演员的原因。* +
要试着让徒劳的准备，得到有意义的结果。

- 写的时候不要想“我一定要写个段子，要让你们笑死”。你要以这个目的来做: “我要写比以前更好的段子”, “不知道能不能行，但是我试试”。 +
*我不会在乎这一场和那一场的观众的不一样. 我只会想今天哪里有问题，是不是可以更好。*

- 你必须思考这个问题，我们上台演出的目的是什么？是为了伺候好哪一场，哪一天的观众吗？ +
我们当然要为演出效果负责，但是**你上台的出发点不该是这个，而是要拉长时间看 ——你的目的始终是成为更强的脱口秀演员。** +
*即, 最终目的是: 通过逗笑观众来磨砺自己，而不是逗笑观众。* "逗笑"只是你利用的工具而已.
+
*不停演出的目的，是为了磨练自己，而不是为了炸场。* 不是你去找观众，而是要让观众来找你。狠狠地操练自己，你越强，找你的观众越多。而不是你能讨好的人越多，你的观众越多。 +
炸场只是副产品，名利也是副产品。
+
人是目的，不是手段。这不只是一种道德要求，也是很理性的结论。*如果你的表演是为了让观众笑的话，你就成了手段，你变成了工具。拿自己当手段，你顶多掌握二流手段。拿自己当最终目的，你才有机会掌握一流手段。 你是你自己的目的。*

- *每天睡觉前. 你唯一要考察的只有一件事：你有没有持续地变好？今
天是否获得了一点昨天没有的东西？*

- 同样, 我也不会关心这家公司的死活. 人最终是要成就你自己这个人的。你不能把自己的命运和某个公司绑在一起。*做大事的人，一定是要把自己和自己的伟大事业绑在一起去做的。*


== ---------- ----------

---

== other


==== 要学，就要学习第一流的. 因为"取法其上得其中"

- 学习一流，模仿二流，成为三流。如果你一开始就学习二流，那你是成为不了三流的。 +
《红楼梦》里香菱学诗，黛玉就说：“断不可学这样的诗。你们因不知诗，所以见了这浅近的就爱，一入了这个格局，再学不出来的。”



---


==== 你是专业的，就不要干业余的人也能轻易做到的事

- 工作是不能只靠灵感的, 灵感要是不来呢？ 专业人士追求的是不管刮风下雨，都能有一点收成。

- **你是专业的，就不要干业余的人也能轻易做到的事。**时时刻刻都做到专业，这样跟你接触的人才不会轻看你，才愿意信任你。

- 创作不痛苦，但过度创作是痛苦的. 觉得不想再写了，再写就腻了，*这个时候就是进化的时候, 你要突破的时候。这时候你退一步，你就过不去了。但如果你过去了，你的认知就不一样了.*

- 情绪低潮的时候，很难做到在每件任务上都保持专业性。对此, 你首先要自己排序，不可能每件事对你都重要。*人就是人，当有时你的情绪变成了一级响应，那你首要处理的就是自己的情绪.* +
你应该时刻想着这件事 -- 你所做的所有事情，受过的所有训练，委屈，成就，都是为了成就你这个人的。你用这个判断标准去衡量问题的时候，对事情你就知道该怎么分等级了。


---

==== 你做某个职业, 就要坚持你这个职业索要坚持的事情(价值观)

- "秀"和"综艺节目"的区别 : 某综艺节目的导演对我们说 : "我们做节目的思路是:垮掉了也好看，哭了，吵架了，都好看. 你的思路是段子都要写好练好，只许成功，这样太冒险了。”

- 我们的很多导演，都是编剧倾向的，她们都可以编段子, 改段子。 所以最终编剧和导演是一体的。 +
不过如果把它们分开, 编剧和导演是需要即合作又斗争的。**他们需要坚持他那个岗位所需要坚持的事情，**不然就顺撇，全让编剧做，内容就会太歪，太自嗨; 如果全让导演做，可能就土。 +
我们必须相互理解，*同时又坚持己见*. 脱口秀演员编剧, 就是要坚持一些脱口秀的原则，而导演们就是要从节目视角出发.

- 演员说，其实我们不应该互相改稿的，因为本身在写这个段子的时候，大家的逻辑和内核是不一样的，如果你突然提了一个意见，这个意见是来自你的逻辑和价值观，是一个嫁接的东西，可能就不那么有用。 +
没关系，*意见这个东西它叫意见，它不叫命令，也不叫决策。* 你可以不接受，但还是要多听。你自己的稿子，听完总编剧意见后，最终还是听你自己的.

- 如果并不认同改稿的取舍，那就不认同. 你再找别的人。没关系。

- 聊完了你的段子，**如果出去改完再回到屋里效率更高，就请赶紧出去改完。如果你觉得自己在会议室能发挥更多作用，或者能学到东西，就留在会议室。没人强迫你，这个要自己拿主意。 没必要一言不发在屋里听别人说跟你完全无关的事情。**早点回家永远是好选项。

- 在与外部团队合作时，我们也要帮他们理解什么是脱口秀，脱口秀的一些忌讳、底线，需要通过你让他们提前知道。他们是真的不懂脱口秀。



---


==== ★ 问事实，别直接问对方的想法。要由你自己去推导出这些信息背后意味着的结论.

新闻写作有五个W一个H. 但在采访原则里，我认为里面的 Why应该删掉。

[cols="1a,3a"]
|===
|Header 1 |原因

|-> 错误的问法："xxx你为什么决定回国？"
|这很可能让谈话陷入尴尬，更糟糕的是，这种问题常常还会让受访者产生戒心。

|-> 正确问法：你在韩国训练最苦的时候什么样？你回国第一件事是干什么？回国第一件工作是什么？
|"我想知道你为什么要做脱口秀"，也可以拆成这几个问题:

- 你是哪年开始做脱口秀的？ 第一次在哪里？ 第一次赚钱了吗？
- 什么时候开始赚钱的？那笔钱怎么花的？没钱的话坚持了多久？
- 以前一起做脱口秀的朋友还联系吗？他们现在过得怎么样？...

*问事实，别问想法。问行为，别问理由。问事，别问人。 (也就是让对方只提供客观信息, 由你自己去推导出这些信息背后意味着的结论)*

你让他直接说why，你可能得到的是一个错误的答案，他要么真的没去想过，要么你会得到一个错误的答案，或者谎言。**你必须拆解成一个个的问题，自己去推论。**之后找一些背后的逻辑，把这些串起来。
|===

---


