= 0102
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 102: Wait-Listed for a Flight.
This is English as a Second Language Podcast episode 102. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
In this podcast, we will be talking about taking an airplane flight and being put on a wait-list. Let’s get started!
[start of story]
I can't believe I made it into San Francisco, at long last! This morning, I went to the airport to catch my 10 a.m. flight. I got there early to go through security. The folks at the TSA can really slow things down sometimes. Since I had an electronic ticket, I didn't have to wait at the ticket counter to check in, but instead used a kiosk. I then went straight to the gate, but when I got there, I couldn't believe my eyes. The flight was delayed -- for two hours!
I decided to look at the flight monitors to see if there was an earlier flight to San Francisco. I thought maybe I could either switch to that flight or get wait-listed. I saw that there was another flight leaving in 40 minutes and so I bolted for the gate. When I got there, I got into the back of the long line. When I got to the front of the line, I asked the gate agent if I could get on that flight instead and she said I would be wait-listed. She said that I needed to stay in the gate area and wait for my name to be called if they have a seat available, so I waited, and waited, and waited.
The gate agent began calling out names over the PA system and guess what? The last name called was mine. What a relief! The last seat left on the plane was a middle seat and I usually prefer an aisle or window, but I was just happy to get on board. I didn't want my vacation to get delayed because of a late flight.
When the plane landed, I went out to the curb to catch a taxi to my hotel. I only had carry-on bags so I didn't need to wait in baggage claim. I was out of the airport and off on my vacation.
[end of story]
We’re traveling in today’s podcast. I began my story by saying that I couldn’t believe I made it to San Francisco “at long last.” The expression “at long last” means finally, after a long time. I said that this morning, I went to the airport to “catch” my 10:00 AM flight. “To catch a flight” means to take an airplane ride, an airplane flight, but we usually say, “I’m going to catch a flight to Cleveland,” or, “I’m going to catch a flight to San Francisco.” Either “catch” or “take” is possible. I said I got there early to go through “security.” “Security,” of course, is the guards that make sure you don’t have any bombs or anything dangerous. In the United States, now, since 9-11, the airports all have a federal agency, A U.S government organization that checks for security. It’s called the “Transportation Safety Administration,” the TSA, and people just call it the “TSA.”
I said that since I had an “electronic ticket,” I didn’t have to wait at the “ticket counter” to check in. An “electronic ticket” – most tickets now are electronic. You sign up on the Internet and they send you an email and you don’t have a physical ticket. You just have sort of a receipt if you print out your email. If you have a problem with your ticket, you may have to go to the “ticket counter” and the “ticket counter” is the desk in an airport where you buy tickets or you – sometimes, if you have a paper ticker, you “check in” at the ticket counter. “To check in” means to tell them that you’re there to – it’s kind of like registering and they give you what’s called a “boarding pass,” and a “boarding pass” is your slip – usually a piece of paper that allows you to get on the airplane. I didn’t have to do that. I used an electronic “kiosk,” and here a “kiosk” (kiosk) is a machine that you can put your credit card in and it recognizes who you are and you get your boarding pass from the electronic “kiosk.”
I then went straight to the “gate,” and the “gate” (gate) – in an airport, a “gate” is where the plane pulls up to the building and where you get on the plane and off the plane. Getting on the plane is called “boarding” the plane, and getting off the plane, we say, “deboarding.” So, I went to the gate and usually, for example, at Los Angeles International Airport, there are several different “terminals” and each “terminal” has several “gates.” A “terminal” is like a wing or a section of an airport. So, I went to the “gate” but when I got there, I discovered that my flight was “delayed.” “To be delayed” (delayed) is a verb which means that it’s late, that my flight wasn’t going to leave on time, at the time it was scheduled, but two hours later. I then decided to look at the “flight monitors” to see if there was an earlier flight to San Francisco.” The “flight monitors” are the TV screens or television screens in an airport that show you what time the plane is either arriving, coming to the airport, or departing, leaving the airport, and in most American airports, you’ll see one set of monitors for arrivals and then, usually below it or on the other side, there’s a set of flight monitors for departures.
I was hoping that I could get “wait-listed.” The verb “wait-listed” (wait) (listed) – “to be wait-listed” means they put you on a list and you have to wait to see if you can get on at a particular flight if there’s room. So, I “bolted” to the gate that was leaving, where the plane was leaving earlier. “To bolt” (bolt) – the past tense is “bolted” (bolted) – “to bolt means to go very quickly, to run, usually to run very fast. Well, when I got to the other gate, I asked the “gate agent” if I could get a flight – get on that flight – get a seat, that is, on that flight. The “gate agent” (agent) is the person from the airplane – the airline company – who works for the airline. The person who helps you at the gate is called the “gate agent.” The person who works at the ticket counter is usually called the “ticket agent.” So, I was wait-listed for the flight and I was told I had to stay in the “gate area” and wait for my name to be called. The “gate area,” of course, is the area – the part of the airport that is near that gate.
Well, the gate agent began calling out names, or “announcing” names, and she announced them over the “PA” system. The “PA” stands for the “public address” and that is the speakers that everyone can hear the announcements from. I then said, “Guess what?” The expression, “Guess what?” is something you say to someone when you’re going to tell them something surprising or maybe something they don’t expect. “I went to the store and guess what? They didn’t have any milk.” Well, I had my name called and I got the last seat on the plane. It was a “middle” seat. In most American planes – in most planes everywhere, there often are three seats on either side of a middle “aisle.” “Aisle” is spelled (aisle). That’s the walkway where you can walk back and forth on the plane, and the seats that are right on the aisle are called the “aisle seats,” and the ones near the window are logically called the “window seats,” and the other seat is called the “middle seat.” Sometimes, we don’t say “aisle seat.” We just say, “aisle,” or “window,” so the gate agent might say, “Do you want an aisle or a window?” They mean an aisle seat or a window seat.
I was happy to get on board, and we talked about the verb “to board” – means to get on an airplane, so if you are “on board,” you are on the airplane. When I got to San Francisco, I got out of the plane. The plane “landed” and, of course, “to land,” for a plane, means to arrive, to touch down on the ground. The opposite of “landing” is “taking off.” So, a plane “takes off” and it “lands.” When I got to the airport in San Francisco, I went to the “curb” to catch a taxi. The “curb” is the edge of the street. That part of the street right at the very end or edge on each side of the street is called “the curb.” So, I went to the “curb” of the street outside the airport and I “caught a taxi.” “To catch a taxi” means to ride in or to take a taxi cab. I only had “carry-on bags” so I didn’t need to wait in “baggage claim.” There are two kinds of pieces of luggage – types of luggage, and these are called either “carry-on bags” or “check-in bags.” “Carry-on,” you take with you on the airplane, put it above you or in the seat in front of you, and to “check-in” your bags, or “checked baggage,” means that you put them below the plane and then you have to get them back when you arrive at the airport by going to “baggage claim.” “Baggage claim” is where you pick up your luggage that you had checked.
Now let’s listen to the story this time at native rate of speech.
[start of story]
I can't believe I made it into San Francisco, at long last! This morning, I went to the airport to catch my 10 a.m. flight. I got there early to go through security. The folks at the TSA can really slow things down sometimes. Since I had an electronic ticket, I didn't have to wait at the ticket counter to check in, but instead used a kiosk. I then went straight to the gate, but when I got there, I couldn't believe my eyes. The flight was delayed -- for two hours!
I decided to look at the flight monitors to see if there was an earlier flight to San Francisco. I thought maybe I could either switch to that flight or get wait-listed. I saw that there was another flight leaving in 40 minutes and so I bolted for the gate. When I got there, I got into the back of the long line. When I got to the front of the line, I asked the gate agent if I could get on that flight instead and she said I would be wait-listed. She said that I needed to stay in the gate area and wait for my name to be called if they have a seat available, so I waited, and waited, and waited.
The gate agent began calling out names over the PA system and guess what? The last name called was mine. What a relief! The last seat left on the plane was a middle seat and I usually prefer an aisle or window, but I was just happy to get on board. I didn't want my vacation to get delayed because of a late flight.
When the plane landed, I went out to the curb to catch a taxi to my hotel. I only had carry-on bags so I didn't need to wait in baggage claim. I was out of the airport and off on my vacation.
[end of story]
That’s all we have time for today. I’m Jeff McQuillan from Los Angeles, California. Thanks for listening. We’ll see you next time on ESL Podcast.
ESL Podcast is a production of the Center for Educational Development in Los Angeles, California. This podcast is copyright 2005. No part of this podcast may be sold or redistributed without the expressed written permission of the Center for Educational Development.
Glossary
at long last – after waiting for a long period of time; finally
* Leah waited seven months, but at long last, she had saved enough money to buy a new computer.
flight – a journey made on an airplane; a trip made on an airplane
* Frances usually drove to Florida in a car, and this was his first time taking a flight to get there.
security – the professionals who keep people safe in a building or at an event; the group of people employed to protect people
* Many important people were meeting at the hotel, so security was increased to ensure that everyone would be safe.
TSA – Transportation Security Administration; the part of the U.S government that protects the country’s transportation systems so that people and “goods” (products) can move throughout the country
* The TSA created new rules about how to check for possible threats before people get on an airplane.
electronic ticket – a ticket purchased, usually for an airplane flight, using one’s own computer and is not printed on paper
* Camellia hated standing in long lines, so she always went onto the computer and bought an electronic ticket instead of waiting in line at the airport.
ticket counter – a place at an airport where one buys a ticket for a flight from a worker at the airport
* When Raul walked to the ticket counter, he asked the airline representative if there were any tickets available for an flight to Nevada that afternoon.
to check in – to officially tell someone that one has arrived or have come to the place one is supposed to be; to formally tell an employee or representative that one has arrived at a place where one is expected
* Mable had already reserved for a room at the hotel and went to the desk to check in after she walked through the front doors.
kiosk – a computer that one can use to get information or to check-in at the airport or other location
* The kiosk was broken, so Terrance needed to talk to an actual airport worker to claim his ticket.
gate – the door one enters or the path one walks on to get onto an airplane at an airport
* Kina went to the wrong gate and almost walked onto the wrong airplane.
delayed – put off, paused, or stopped until a later day or time; having an event or action occur at a later time than planned
* There were heavy rainstorms that day, so the baseball game was delayed until the players could play in better weather.
flight monitor – at the airport, screens that show when airplanes arrive and leave
* Jimmy looked at the flight monitor and saw that his friend’s flight would arrive 30 minutes late.
to be wait-listed – to be put on a list of people who are waiting for an empty seat on an airplane
* Tianna tried to take an earlier flight, but the airplane seemed full so she was wait-listed.
to bolt – to run or walk quickly; to move fast so that one can get to or away from something
* Corey woke up late, so he got dressed quickly and bolted to work as fast as he could go.
PA system – Public Address System; a sound system that makes sound loud enough for large groups of people to hear
* The principal’s voice came through the PA system, telling all the students in the school about that day’s special events.
curb – the edge of a sidewalk; the spot where a sidewalk ends and a street begins
* The driver of the car drove too close to the sidewalk and hit the curb.
carry-on bag – luggage that one carries onto an airplane instead of putting it into the back or bottom of the airplane
* Joanna carried the most important items in her carry-on bag, including a set of clean clothes and her laptop computer.
baggage claim – a place at an airport where one retrieves the bags and items one gave to the airline to store on the airplane during a airplane flight
* Riley went to the baggage claim to get his suitcases.
Culture Note
Annoyances While Flying
Anyone who flies a lot knows what it is like to be in an airplane with “inconsiderate” (not kind; not thinking of others) travelers. Here are a few common complaints among people who fly:
- People who talk on their cell phones at a loud “volume” (level of sound) and even after the flight attendant announces that all “portable” (able to travel) electronics should be shut off.
- While getting onto the airplane, people who stand in the “aisle” (walkway) for a long time,
“holding up” (delaying) the rest of the passengers.
- People who speak loudly and “non-stop” (without stopping), often to the “stranger” (unknown person) sitting next to them who would rather rest.
- Parents who allow their children to run up and down the aisle or to yell loudly without “checking them” (telling them to stop).
- Passengers who bring more luggage on the plane then the bags allowed, taking up valuable “overhead space” (storage space over the seats).
- People who “spread out” (take more space) from their own seat to the seat next to them or by “reclining” (leaning back) their seats all the way back.
- People who don’t keep the bathroom clean for other people.