= 0116
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 116: Holiday Travel.
You’re listening English as a Second Language Podcast episode 116. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
The topic of today’s podcast is going to be travelling, and specifically, travelling for the holidays. Let’s go!
[start of story]
It's hard to avoid traveling over the holidays, but the experience I had last week really takes the cake.
I flew back to Tucson, Arizona to be with my wife's family, as we do every Christmas. I got to the airport an hour and a half before my flight, which I thought would be plenty of time. When I got there, though, I saw that the security line was out the door. Because it was the holidays, people were traveling with a lot of extra packages. It took twice as long as it normally would to get to the front of the line. When I finally got to the gate, I found out that my flight had been oversold. The gate agent was looking for people to voluntarily give up their seats for a later flight in exchange for a $100 travel voucher. If she didn't get enough volunteers, she would have to bump people from the flight. Luckily, several people took her up on the offer and the rest of us boarded.
What a hassle! I love the holidays, but I don't love holiday travel.
[end of story]
We’re talking today about travelling, and specifically, about flying in an airplane. The title of our podcast is “Holiday Travel.” “Holiday” (holiday) means something different in the United States than in Great Britain. In American English, a “holiday” is usually an official day that the government says you don’t have to work. So, that would be a day like Independence Day, the 4th of July, or Christmas, or New Year’s Day – these are all official holidays. In Great Britain, a “holiday” is a vacation – what we would call in the United States, a “vacation” – where you go away somewhere with your family for two weeks. Now, you can take a vacation in addition to your holiday, but in the United States, “holiday” doesn’t mean a vacation necessarily. It just means a day that you don’t have to work. Now, in December we have the Christmas holiday. There are some who celebrate Hanukkah in the Jewish calendar and there are, of course, New Year’s Day celebrations. So, the “holidays” – when someone uses that plural, at least in the United States, they mean the Christmas, Hanukkah, New Years – that whole time is called the holidays. In fact, some people even include Thanksgiving, Thanksgiving Day, at the end of November as the beginning of the holidays.
Well, we are talking about holiday travelling and we begin by saying that “it’s hard to avoid travelling over the holidays.” “It’s hard to avoid” means, of course, it’s difficult not to do something. And with that particular expression – “it’s hard to avoid” – the verb that comes after is in the “ing” form. So, “it’s hard to avoid travelling.” “It’s hard to avoid talking to my sister.” “It’s hard to avoid paying your taxes.” “It’s very hard to avoid dying.” So, these are all things that take the “ing” – verbs that take the “ing.”
I also said that the experience, what happened to me last week, really “takes the cake.” The expression “to take the cake” (cake) – “to take the cake” means that it was the worst possible, or it was in addition to all of the other problems. It was even more of a problem. Something that is the worst example of an experience would really take the cake. I go to the dentist and I have to get my teeth fixed. I have to have a work done on my teeth and when I am finished, the bill is a thousand dollars. So in addition to having pain of going to the dentist, I have the pain of paying a thousand dollars – “that really takes the cake” means it’s even worse than other problems.
I flew back to Tucson. And Tucson is a small city in Arizona, which is next to California. Tucson is in the middle of the desert. Arizona is a desert state. And I was going to go back to be with my wife and her family as we do, as we always do, every Christmas. And I got to the airport early, an hour and a half before my flight, which I thought would be “plenty of time.” “Plenty” (plenty) means a lot, more than enough, so, “plenty of time.” When I got there though, the “security line was out the door.” The “security” (security) line” is the line that you have to stand in – to be in – so that you can go through the X-ray machine and make sure you don’t have any weapons or any bombs or anything else. Well, the line was “out the door.” When we say something is “out the door” we mean that people are standing outside of the building – the line is so long it goes from inside all the way outside to the building. And at Los Angeles International Airport, there are actually eight terminals – eight places where planes can pull up – eight different parts of the airport, and usually, during the holidays, the security line is out the door in many of those terminals – many of those areas.
Well, one of the reasons that it was taking so long to get through security – “to get through,” meaning to pass through security – was people had a lot of “packages.” “Packages” (packages) here means boxes, things that are gifts for other people. Usually in the holidays, that’s what the packages are. Well, it took “twice as long” as it would, normally, to get to the front of the line. “Twice as long” – three words – “twice,” meaning, of course, two. So, “twice as long” means two times the amount of time it would normally take to get to the front or the beginning of the line. When I got to the “gate” – the (gate) – the “gate” is – in the airport, that’s the door where you go out to get into the airplane. So, you go to the “gate” – that area – and I found out that my flight had been “oversold.”
“Oversold” is all one word – “over” and “sold” – (oversold). “Oversold” means that the airplane company, the airline as we would call it, has sold too many tickets and this is something that happens in the United States. I don’t know about other countries. The airline thinks that it can sell more tickets than it has seats because people are always cancelling or changing their flights. So, they’re guessing, they’re betting that you will – some people will not come to the flight. So, they have a hundred seats but they sell, for example, 110 seats. So, if all 110 people actually get on that flight or try to fly that flight, then they have oversold. And when they oversold, the gate agent – and the “agent” (agent) – is the person who works for the airplane, airline – the person working there at the gate has to ask people if they would give up their seats. “To give up your seat” means that you will volunteer. You will say, “Okay, I won’t go on this flight.” And usually, they give you something if you do that. They give you something in exchange for your seat. The expression “in exchange for” means you give me something, I give you something. “In exchange for $10, I give you, you give me your car” – that’s not a very good deal. “In exchange for a hundred dollar travel voucher” – and a “travel voucher” – a “voucher” is (voucher) - a “voucher” is like a – it’s kind of like a coupon or a certificate. It’s a piece of paper that says you have a hundred dollars. It’s not a hundred dollar bill, it’s not a hundred dollars, but it’s worth a hundred dollars. And we use that term “voucher” for travel – tickets that the airline gives you if you give up your seat.
Well, if you don’t have enough people giving up their seat then the airplane – the airline – has to “bump people.” “To bump someone from a flight” –“bump” (bump) – means to say you can’t go. And the airplane – airline – has the right, legally, to bump people if they sell too many tickets, which surprises people when it happens. It has happened to me. I was flying once from St. Paul, Minnesota to, I think it was Dallas, Texas and I was “bumped from my flight,” meaning I was told you can’t go on this flight. We have too many people. Well, luckily, several people “took up” the gate agent’s offer – “they took her up on the offer.” “To take someone up on an offer” means that you accept whatever deal, whatever idea that they present to you. So, someone says, “Why don’t we go to the beach this afternoon because it’s a beautiful day here in beautiful Los Angeles and I’ll buy you lunch.” And she says, “Oh, okay, I’ll take you up on your offer” – means I agree to do that. Well, after other people took up the gate agent’s offer for travel vouchers, the rest of us “boarded.” And “to board,” means just to get on to the airplane. I end the story by saying, “What a hassle.” “What a hassle” (hassle) – “What a hassle” means what a pain, what a problem. Something that causes a lot of problems is a hassle.
Now let’s listen to the story this time at a native rate of speech.
[start of story]
It's hard to avoid traveling over the holidays, but the experience I had last week really takes the cake.
I flew back to Tucson, Arizona to be with my wife's family, as we do every Christmas. I got to the airport an hour and a half before my flight, which I thought would be plenty of time. When I got there, though, I saw that the security line was out the door. Because it was the holidays, people were traveling with a lot of extra packages. It took twice as long as it normally would to get to the front of the line. When I finally got to the gate, I found out that my flight had been oversold. The gate agent was looking for people to voluntarily give up their seats for a later flight in exchange for a $100 travel voucher. If she didn't get enough volunteers, she would have to bump people from the flight. Luckily, several people took her up on the offer and the rest of us boarded.
What a hassle! I love the holidays, but I don't love holiday travel.
[end of story]
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
ESL Podcast is a production of the Center for Educational Development in Los Angeles, California. This podcast is copyright 2005. No part of this podcast may be sold or redistributed without the expressed written permission of the Center for Educational Development.
Glossary
the holidays – a period when people stop their normal activities and celebrate or honor special days, usually the part of the year that includes Christmas and New Year's Eve
* Shasta looked forward to the holidays because she was able to see her entire family at Christmas and spend New Year’s Eve with her closest friends.
to take the cake – to be the best example of; to be the best or worst of a pattern, idea, action, or event
* Jeremiah knew that college exams would be difficult, but Dr. Morrison’s exams were almost impossible to pass and really took the cake.
plenty – more than enough; of a larger amount or number than one needs
* There was plenty of food at the party and all the guests were told to take some of the extra food home.
security line – a line that one must wait in before getting onto an airplane, where airport workers check to see that each person and his or her items are safe and not a danger to others on the airplane
* Even though the security line was long, Miranda felt safer getting on the airplane after walking through it.
out the door – when a line or group of people is too large to fit inside the room it begins in and uses extra space through the door and outside the room
* The rock band was so popular that the crowd of people wanting to see it perform at the concert was out the door.
gate – the area near the airplane and the doors one goes through when getting on an airplane
* Jose made it to the gate to get on the plane before the airplane took off.
oversold – when too many tickets are sold for the available seats; when an airline sells tickets to more people for a flight than the airplane has seats available
* The flight was oversold, and many customers were told that they could not get on the airplane.
agent – someone who performs a job or task for a business or for the government, usually working directly with customers
* The book agent worked with the writer to help the writer sell the book to a publisher.
to give up (one's) seat – to no longer claim a seat on an airplane or other form of transportation, so that someone else may sit in that seat
* Esther gave up her seat on the bus and chose to stand so an old man could sit down.
in exchange for – traded for; giving one item away so one might get a different item instead
* Cody did his sister’s chores in exchange for his sister’s share of dessert.
voucher – a document or piece of paper that one can use instead of money, usually for a certain event, action, or purpose; a document a company gives someone which can be used instead of cash to buy something
* The store did not have the item the customer wanted, so the cashier gave the customer a $25 voucher to buy something else.
to bump – to move someone from one flight to a later flight because not enough seats are available on the first flight.
* Denise paid for a flight that left at 1:30 in the afternoon, but the flight had too many people on it and the airline bumped Denise to a later flight that would not leave until 8:15 at night.
to take (someone) up on the offer – to agree to a deal that someone makes; to make a trade suggested by someone else
* Franklin told his father that he would wash the car if his father drove him to the beach tomorow, so Franklin’s father took him up on the offer.
to board – to get onto an airplane; to walk onto an airplane for a flight
* Cheryl was running late, but she had just enough time to board the airplane before the plane left the airport.
hassle – trouble; a situation or event that is hard and unpleasant
* Dealing with busy traffic while driving home from work is always a hassle, and many people wish they could avoid it.
Culture Note
The Fruitcake
Several foods are associated with the Christmas holiday. Unfortunately, one traditional Christmas dessert has received a “bad name” (negative association; a bad reputation): the fruitcake.
A fruitcake is a cake made with “candied fruit” (fruit made into candy) or dried fruit, nuts, and “spices” (plants and vegetables used to flavor food), and, traditionally, is “soaked” (placed in liquid) in alcohol, which helps to “preserve it” (prevent it from going bad). Many fruitcakes made “commercially” (for sale by companies) don’t use alcohol, however.
The fruitcake has become “the butt of jokes” (a subject to laugh about) because many people believe that fruitcakes just aren’t very good, not very tasty. People often joke that no one wants to be given a fruitcake as a gift, so when you receive one, you try to “regift” (give someone a gift that you received as a gift) it to someone else. In fact, the famous comedian Johnny Carson once joked on his longtime talk show, the Tonight Show, that there is only one fruitcake in the world and it’s passed from one family to another.
Another “running” (continuing) joke has to do with the items put into a fruitcake. Because dried or candied fruit are baked into the cake, and because fruitcakes are sometimes “stored” (kept unused) for a long time, those pieces of fruit may become hard and difficult to eat. Some people joke that it’s easy to break a tooth while eating a fruitcake or that they discover strange and “mysterious” (unknown) pieces inside the cake that is no longer “identifiable” (known; easy to see what it is) after such a long time.