= 0134
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 134: Dating Someone’s Ex.
You’re listening to English as a Second Language Podcast episode 134. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Today’s podcast is about going on a date with someone’s ex. And here “ex” (ex) means ex-boyfriend or ex-girlfriend – former boyfriend – someone who used to be your boyfriend or your girlfriend. Let’s get started.
[start of dialog]
Marco: Hello.
Claudia: Hey, Marco? It's Claudia. Got a minute?
Marco: Sure. What's up?
Claudia: I'm just wondering what's going on with you and Beth. Are you guys still going out?
Marco: We went out for a while, but we never got serious. Why all the questions? Are you interested in Beth?
Claudia: (Laughs) No, I'm not interested but Shane is. He's been asking me about you guys. He wants to ask her out but he didn't know whether you guys were still together, or how you’d feel about him asking out your ex.
Marco: Why didn't he just ask me? Beth and I were casual and we haven't seen each other in months. He should go for it.
Claudia: Okay, I'll tell him. So, if you're not going out with Beth, who's the new girl?
Marco: Wouldn't you like to know. Actually, I've been seeing a great girl. I'm bringing her to the party on Saturday. You'll meet her then.
Claudia: Great. I'm bringing Lenny so you'll get to meet him, too. See you Saturday.
Marco: See ya!
[end of dialog]
In this podcast, we meet Claudia and Marco. Claudia calls Marco on the telephone and Marco answers, “Hello.” And Claudia says, “Hey, Marco. It’s Claudia. Got a minute?” “Hey,” (hey) you probably know is an informal way of saying hello to someone. “Hey, Marco, got a minute?” means do you have a minute to talk to me. So, if someone says to you, “Hey, you got a minute?” what they mean is I want to talk to you. Do you have time to talk to me right now? Marco says, “Sure. What’s up?” And, of course, “What’s up” again, informal, to mean what’s going on, what is happening, what do you want to talk to me about. And Claudia says, “I’m just wondering what’s going on with you and Beth. Are you guys still going out?” The expression “What’s going on” here means what is the situation, what is happening between you two. And this is sometimes used when there’s a problem. For example, a parent, a father or a mother may see their child crying, and they’ll ask him what’s going on or when they see two children fighting, “What’s going on here?” – means what is the problem, why is this happening?
But in this dialog, it’s really just what is the situation, what is the – in this case, romantic relationship or no romantic relationship between you and Beth. “Are you guys still going out?” “To go out” means here to be dating, to be romantically interested and involved with someone. Notice the use of the term “guys” (guys) which again, informal to mean you people. In English, the use of the plural “you” is not very common, at least in American English. So, when we say “you,” we could mean just one person or we could mean three or four people. In some dialects, in some variations of American English, we say, “You all” – that’s a very southern United States expression – “You all.” But most people don’t say that, most people would just say, “you” or informally they might say, “You guys,” meaning the two of you, in this case, or more.
Well, Marco says that “We went out for a while” – again, we dated for a while – “but never got serious.” And “to get serious” if you are dating someone, in a relationship – a boyfriend, girlfriend – “to get serious” means you are thinking about getting married or you are thinking about staying together for a long time. Marco then says, “Why all the questions? Are you interested in Beth?” “Why all the questions” here means why are you asking me these questions. You want to know why this person is interested and he makes a joke by saying, “Are you interested in Beth?”
Well, Claudia is not interested in Beth but she says that her friend, Shane, is. “Shane has been asking Claudia about you guys” – again, about Marco and Beth. “He wants to ask her out but he didn’t know whether you guys were still together.” “To ask someone out” means that you are going to ask someone to go on a date with you. So, you ask someone out “on a date” – is what we would say – “to ask out,” or “to ask out on a date” and if you are interested in each other, then you may start to go out together, meaning you are now dating each other, you are romantically interested in each other. Well, Shane wasn’t sure if Marco and Beth were “still together,” meaning they were still romantically involved, they were still boyfriend and girlfriend.
Shane was also uncertain about how Marco would feel about asking out his ex. And again, “ex” (ex) is short for ex-girlfriend, in this case. It can also mean, when someone says, “your ex” it can also mean your ex-husband or your ex-wife – if you divorce from that person. Marco says, “Why didn’t he just ask me?” In other words, why didn’t Shane ask me directly. “Beth and I,” Marco says, “were casual, and we haven’t seen each other for months.” “To be casual” in this context, means that they weren’t serious, that they weren’t interested in getting married, they were just dating each other. “Casual,” normally means relaxed, not serious. We also use that expression to talk about clothing. If somebody says, “Dress is casual for the party,” that means that you don’t have to wear a suit and a tie or very nice clothing. You can dress, you can come in jeans and maybe tennis shoes – that would be dressing casually. Well, Marco says that Shane should just “go for it.” “To go for it” here means he should do it. There’s a famous advertising line in the U.S. and in other English speaking countries for Nike – the company Nike that makes tennis shoes, running shoes, and it’s called “Just do it.” And it’s very similar to “go for it,” meaning that you should go ahead, make a decision and, in this case, ask Beth out.
Well, Claudia says that she will tell Shane and then asks Marco, “Who’s the new girl?”
“Who’s the new girl?” meaning who is your new girlfriend. Marco says somewhat again, as a joke, “Wouldn’t you like to know.” That expression “Wouldn’t you like to know” is when someone asks you a question and wants to get information from you, but you don’t think it is any of their concern. It’s, we would say, “It’s none of their business,” meaning they don’t need to know. And usually, it’s when someone is asking you something private or personal, or secret. So, instead of telling the person the answer, you say, “Wouldn’t you like to know,” meaning I’m not going to tell you, it’s none of your business, it’s not your concern. You shouldn’t be interested in it.
But Marco then shows that he is joking when he says, “Actually, I’ve been seeing a great girl.” “To be seeing” means that I am dating. So, if someone asks you, “Are you seeing anyone?” And it’s the verb “see” (seeing) – “Are you seeing anyone?” – they mean are you romantically involved, are you dating anyone. Do you have a boyfriend or a girlfriend? And he says – Marco says he’s been seeing a great girl and that he’s going to bring her to the party. Claudia says, “Great! I’m bringing Lenny, (her boyfriend) and you’ll get to meet him, too.”
Notice there seems to be some – we would say – some romantic or sexual tension between these two, Marco and Claudia. They’re talking on the telephone, but when we say there seems to be some romantic or sexual “tension” (tension) we mean that they seem to like each other, even though they each have their own boyfriend or girlfriend, they seem to be interested in each other. Well, that’s my interpretation of the dialog. Well, the dialog ends with Marco saying, “See ya!” And the expression “See ya!” – and here, instead of saying “You,” we say, “Ya” (ya). It’s just a short, informal way of saying, “You.” So, if somebody says, “See you,” or “See you later” – means I hope that we will see each other later.
Now let’s listen to the dialogue this time at a native rate of speech.
[start of dialog]
Marco: Hello.
Claudia: Hey, Marco? It's Claudia. Got a minute?
Marco: Sure. What's up?
Claudia: I'm just wondering what's going on with you and Beth. Are you guys still going out?
Marco: We went out for a while, but we never got serious. Why all the questions? Are you interested in Beth?
Claudia: (Laughs) No, I'm not interested but Shane is. He's been asking me about you guys. He wants to ask her out but he didn't know whether you guys were still together, or how you’d feel about him asking out your ex.
Marco: Why didn't he just ask me? Beth and I were casual and we haven't seen each other in months. He should go for it.
Claudia: Okay, I'll tell him. So, if you're not going out with Beth, who's the new girl?
Marco: Wouldn't you like to know. Actually, I've been seeing a great girl. I'm bringing her to the party on Saturday. You'll meet her then.
Claudia: Great. I'm bringing Lenny so you'll get to meet him, too. See you Saturday.
Marco: See ya!
[end of dialog]
For a script of today’s podcast, be sure to go to our website at www.eslpod.com.
From Los Angeles, California , I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
hey – an informal way of saying “hello” or “hi”
* Hey, Majel. I am happy to see you here at our meeting.
Got a minute? – Do you have enough time to talk to me?; May I ask you a question?
* Got a minute? I need to ask you about the exam we have tomorrow.
What's up? – What do you need?; What do you want to ask me?
* When William told Leonard that he had a question about work, Leonard asked, "What's up?”
what's going on with... – what is the relationship between…; what is the current situation with...; a statement one uses to ask about a person or the relationship between two people
* What's going on with Grace and Walter? It looked like they had a good relationship, but they have not spoken with each other in a few weeks.
going out – dating; in a romantic relationship
* George and Nichelle have been going out for one year and are thinking about getting married.
to get serious – to commit to a romantic relationship
* James stopped dating his girlfriend because he could not get serious about her.
Why all the questions? – Why are you asking me these questions?; Why do you want to know?
* When Kelly continued to ask questions about Scott's trip to Florida, Scott asked, "Why all the questions?"
to ask someone out – to ask someone to go somewhere for a romantic meeting; to ask someone for a date
* Hikaru thought Janice was very attractive and he wanted to ask her out.
still together – dating right now; currently in a romantic relationship
* Christine and Pavel have many arguments and have talked about ending their relationship, but they are still together right now.
ex – former girlfriend or boyfriend; former husband or wife; someone who one was in a romantic relationship with, but who one is not in that romantic relationship with now
* Zoe is still friends with her ex because the relationship ended well.
casual – not committed; not romantically serious or official
* Chris and Jennifer were in a casual relationship and had no plans of getting married.
to go for it – to try it; to do something that one wants to do; to try to achieve something one wants to achieve
* Rachel always wanted to open a flower shop, so when she had enough money, she decided to go for it.
new girl – the girl one is currently in a romantic relationship with; the girl one is in a romantic relationship with after a romantic relationship with another girl ended
* Bruce could never stay in a relationship for a long time and had a new girl every month.
Wouldn't you like to know. – I know you are curious, but I am not telling you that information.; a statement said to someone to tell them that you will not give information that he or she wants to know
* Eric asked Amanda if she thought he was attractive, she laughed and said, “Wouldn’t you like to know?”
to be seeing – to be in a romantic relationship with; to be dating
* Winona is seeing a very nice boy right now and wants to get married to him.
See ya. – an informal way of saying “good-bye” or “I will see you again”
* Ben said “See ya” when he and Anton left the office.
Culture Note
Finding Love in School
In the United States, there is a long tradition of using schools as places for making romantic connections. “Historically” (traditionally), school has been a popular place to meet future husbands or wives, as is probably true in many countries. In 1992, 23% of married Americans said that they meet their “spouse” (husband or wife) at school, such as in high school or at the university. Only 15% of people said they met their spouse at work.
Things see to have changed. In 2006, a similar survey found that only 14% of U.S. married couples first met at school, and 18% met at work. The work “figure” (number) has increased three percentage points, but the school/university number has gone down more dramatically. Why?
While schools were always seen as a place where men and women had time to meet and develop romantic relationships, both men and women “nowadays” (currently; now) are getting married at a much later age than they did 20 years ago. The average age for a man in the U.S. to marry is 27.5 years; for a woman, it’s 25.5 years.
There are many reasons for this change. Part of the reason may be “credential inflation” at work. “Credentials” are qualifications, such as a university degree or training. “Inflation” is when something continues to increase over time. Jobs nowadays require people to get higher and better qualifications, such as Master’s degrees, so that young people have to wait to marry so that they can finish this additional training.
Perhaps this is one reason why Internet dating has become more popular. As people have fewer opportunities to meet “eligible” (unmarried) men and women, they need to find other ways of meeting people. College students now believe that they need to wait to marry, and so don’t start looking for a potential spouse until after they leave school, even though college is probably the one time in their life where they will have a lot of time and opportunity to meet an eligible “mate” (spouse).