= 0147
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 147: Reading and Watching the News.
You’re listening to English as a Second Language Podcast episode 147. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Today’s podcast is about reading and watching the news. Let’s go!
[start of story]
I'm a news junkie. I like to read two newspapers every day. I don't just look at the headlines. I read most of the stories. I like the political news, the business news, the editorials, and the entertainment news. The only things I don't usually read are the sports pages and the classifieds.
I also try to catch the local TV news each day. I like to watch Channel 4 for the news reporting, but I like the weather report on Channel 9 mainly because the reporter is not only good, she's beautiful! For the national news, I like all three of the network anchors, so it doesn't matter which one I catch.
On top of that, I like to read a newsmagazine each week. I like the long feature stories that give more in-depth coverage of that week's top stories.
So, when I said I was a news junkie, I wasn't joking. When I travel to other countries, the first thing I do is look for an English-language newspaper. Then, I can relax!
[end of story]
In this podcast, we’re talking about reading and watching the news – what happens in the world. The story begins by saying, “I’m a news junkie.” A “junkie” (junkie) is a word we normally use to describe a person who is addicted to a drug like cocaine or heroin, something like that. But when we say a “news junkie,” we mean someone who is addicted to news, who likes to do something a lot. The story says that “I like to read two newspapers every day” – that’s actually true. I do like to read two newspapers every day. I don’t just look at the headlines. The “headlines” (headlines) – all one word – the headlines are the titles of the stories. Usually, they’re in bigger print and you can read them easily.
There are different types of news in a daily newspaper. There is “political news” – news about politics, government, that sort of thing. The “business news,” of course, is news about what’s happening in finance and business. The “editorials” (editorials) – an editorial is an opinion. And it’s usually someone on the newspaper, who works for the newspaper, or someone else who writes an editorial. We sometimes call these, either, opinions or editorials, or we’ll call them “Op-ed” (op-ed). “Op-ed” pieces are opinions or editorials that are written for the editorial page.
In most American newspapers, there are actually two pages of editorials every day. The newspaper writes editorials that it often doesn’t sign. But then there are individuals who have editorials and, of course, people write letters to the newspaper. And there’s also “entertainment news” – news about celebrities, about Tom Cruise or Jennifer Anniston, and so forth – that’s entertainment news. I say here that I don’t usually read the “sports pages” or “classifieds.” The “sports pages” are, of course, the section of the newspaper that talks a lot about sports. The “classifieds” in a newspaper (classified) – here it’s plural – the “classified” – “classifieds.” We sometimes call these the “classified ads.” These are advertisements for everything – jobs, cars – people who are selling things will put in a “classified” in the newspaper – that is a classified advertisement. They’re called “classifieds” in part because they are arranged in the newspaper according to a certain classification or category. So, all the ones about selling cars are in the same classification, the same section.
I say I also try to catch the “local” news. We use that verb “to catch” (catch) to mean here to watch. Someone may say to you, “Did you catch that movie on television last night?” And well, you say, “No, I didn’t catch it,” or “Yes. I watched it.” You can also say, “I caught.” “I caught a good show on last night.” It means to watch. The “local TV news” are, of course, the news broadcast that talk about things from a particular city, in a particular city – Los Angeles, of course, here. We have different channels – what we call “local channels” here in Los Angeles and every big city. Usually, there are two or three. Many times, however, there are five or six in a given city. Big cities like Los Angeles and New York have several local channels or local stations that you can watch. And, of course, the channels have a number. So, Channel 4, Channel 11, Channel 9, and so forth.
I say that I like to watch the “weather report.” The “weather report” (report) is the section of the local news where they tell you about the weather. And the story says that “I like to watch Channel 9 because the weather reporter” – and a “reporter” (reporter) is the person that gives a report or gives you certain news. “The weather reporter is not only very good, but she’s beautiful.” That’s actually true. There is a beautiful weather reporter on Channel 9 here in Los Angeles. I only watch her when my wife is not home. So, don’t tell her.
The “national” news – we talked about local news, but there are also national news programs. There are usually one of these every day, at least. They’re 30 minutes long and there are three – the three biggest television companies. We call them “networks” (networks). The three biggest networks each have their own program and the person who reads the news is called “the anchor” (anchor) – the “anchor.” That word “anchor,” we also use for a boat, when you want to stop your boat or keep your boat in one place on a lake or an ocean, you drop or put an anchor. It’s a heavy weight. Well, in a news program – a television news program – the anchor is the most important person. It’s the person that reads most of the news and there usually is one, sometimes two people who are the anchors, they could be co-anchors. I say I like them all. So, it doesn’t matter which one I catch. Notice again, “catch,” meaning to watch a television show.
I say, “On top of that, I like to read a newsmagazine each week.” That expression “On top (top)” – “On top of that” means in addition to. We usually use that expression when someone has been telling you about many different things – a lot of things – and then they say, “On top of that,” meaning even more than the many things they have told you. Well, on top of watching the news and reading the newspaper, I also read a “newsmagazine.” “Newsmagazine” is all one word – (newsmagazine) – and that is usually a weekly magazine that gives you the news – the national news for that entire previous week. The biggest newsmagazines are Time, and Newsweek, in English. But there are other newsmagazines also. Some of them are political, some of them are entertainment, some of them are sports and so forth. But a newsmagazine, usually, is a general newsmagazine like Time or Newsweek, when we say that, use that expression.
I say that “I like the longer feature stories that give more in-depth coverage.” A “feature” (feature) or a “feature story” is a longer story that gives more information. And to say something “gives more information,” means it gives “in-depth coverage. “In-depth (in-depth)” – “in-depth” means with a lot of detail – talking about something for a long time and giving very specific, detailed information. “Coverage” (coverage) is a noun we use to describe when a news story is about a certain topic. We say that the story “covers” a topic. And so the “coverage” as a noun, is what a reporter or a magazine or a newspaper says about a particular topic. So, to have “in-depth coverage” would mean to have lots of details about a particular topic. I say I like to read about the “top stories.” The “top (top) stories” are the most important stories.
Now let’s listen to the story this time at a native rate of speech.
[start of story]
I'm a news junkie. I like to read two newspapers every day. I don't just look at the headlines. I read most of the stories. I like the political news, the business news, the editorials, and the entertainment news. The only things I don't usually read are the sports pages and the classifieds.
I also try to catch the local TV news each day. I like to watch Channel 4 for the news reporting, but I like the weather report on Channel 9 mainly because the reporter is not only good, she's beautiful! For the national news, I like all three of the network anchors, so it doesn't matter which one I catch.
On top of that, I like to read a newsmagazine each week. I like the longer feature stories that give more in-depth coverage of that week's top stories.
So, when I said I was a news junkie, I wasn't joking. When I travel to other countries, the first thing I do is look for an English-language newspaper. Then, I can relax!
[end of story]
The script for today’s podcast was written by Dr. Lucy Tse. Remember to visit our website at www.eslpod.com for more information about this podcast.
From Los Angeles, California, I’m Jeff McQuillan. As always, thank you for listening. We’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
news junkie – someone who cares about current events or news very much; someone who learns about new events in the world from many different sources
* Michelle’s parents were news junkies, and they always had news playing on the television or radio when she visited.
headline – the title of a piece of news; the title of a story about new events
* The headline made it sound as though there was new information, but the story didn’t have anything new in it.
political news – new or current events about government and politicians
* Patrick was interested in political news because he wanted to become the governor of his state.
business news – new or current events about companies, earning money, and spending money
* Leilani wanted to open a new store, so she always read the business news.
editorial – an article or story in a newspaper based on the opinion of the person writing it or who controls what is printed in that newspaper (the editor)
* William agreed with the editor’s ideas and always read the editorial section.
entertainment news – new or current events about music, movies, television shows, and books
* Lula always read the entertainment news to find out more about her favorite actors.
sports pages – the section of a newspaper with news about sports, such as football, baseball, basketball, and golf
* Jackson loves football and reads the sports pages whenever his favorite team plays.
classifieds – the section of a newspaper that lists offers and requests, including offers about jobs, places to live, and cars
* Ashley needed a new job, so she checked the classifieds to learn if any nearby businesses were hiring new workers.
local TV news – a show about new or current events that one watches on the television, and is created by people who work in or near the city one lives in
* The town was small and its local TV news never had many important stories to report.
channel – a number that refers to a television station; a location in radio or television broadcasting where particular shows can be found
* Channel 8 starts its news show at 5 a.m., but Channel 3 does not start its news show until 6 a.m.
weather report – a story or description about current or future weather, with information like outdoor temperatures and conditions
* The weather report said that today should be warm and sunny, but today will be cold and cloudy.
national news – a radio or television show about new or current events available to the entire country and includes stories about different parts of the country
* Alva watched the national news because he liked to know what was happening around the rest of the country.
network anchor – the main readers and presenters of the news during a broadcast
* Sonya likes watching the network anchors on this channel because they seem more serious than those on the other channels.
newsmagazine – a publication sold every week or month that contains stories and information about new or current events, and is smaller than a book but has a cover and pages that are held together similar to a book
* Jefferson bought a copy of his favorite newsmagazine each week when he went to the store.
feature story – a story that one sees on the cover or front of a newspaper or newsmagazine; a story with more information or detail than the other stories in a newspaper or newsmagazine
* The magazine had a feature story about the president’s latest trip to Mexico.
in-depth coverage – detailed information; a story that gives more detail or information about an event
* Do you believe that newspaper stories give more in-depth coverage of a news event than a TV news story?
top story – one of the most important stories; an important piece of new or current information
* The top story was about a house that caught on fire in the center of the city.
Culture Note
Hyperlocal Blogs
We’ve all heard or read about the “decline” (becoming less popular) of newspapers “in print” (printed on paper). “Circulation” — the number of newspapers sold — is down, and advertising is down. Newspaper owners are “cutting” (eliminating) workers and printing “skimpier” (less thick; shorter) newspapers.
As newspapers “cut back on” (reduce) its “coverage” (reporting) of the news, one thing is “picking up the slack” (doing what is needed now that it is not done by someone/something else): the local neighborhood news blog.
The first thing that disappears from a newspaper as it cuts back is coverage of local news. Covering local news requires reporters to personally “investigate” (gather information) and write the articles. To pick up the slack left by skimpier newspapers, “hyperlocal” blogs are appearing across the country.
We often use the prefix “hyper” to mean very much or very intense. Hyperlocal, then, is news about this “immediate” (here or very close to here) area. The idea is that “residents” (people who live there) report on what goes on in their own community, such as issues related to local schools or to transportation. These reports may not be written by professionals, but they have the benefit of giving local residents what they want: focus on their own community.
Some of these hyperlocal blogs are even making money. Before 2010, the West Seattle Blog, for example, was supported by “donations” (giving money to an organization to support it, without expecting anything in return), but made “six figures” (between $100,000 to $999,999) last year, “presumably” (I believe, though I’m not certain) from “ad revenue” (money made from advertising).