= 0148
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 148: Paying the Bills.
You’re listening to English as a Second Language Podcast episode 148. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this podcast, we’re going to pay our bills. Let’s go!
[start of dialog]
Grace: Did you already pay the bills for this month?
Will: No, I haven't gotten around to it yet. Why?
Grace: We got a late notice from the credit card company. The notice says that they haven't received the payment yet and it's past the due date. We are being charged a late fee plus a finance charge of 15%.
Will: Let me see that. That can't be right. I paid the minimum payment on the last bill. I better call and talk to customer service tomorrow. I'm sure it's a mix-up.
Grace: I really hope so. The last time we were late with the payment, I tried calling them and telling them that the check was in the mail, but they didn't buy it.
Will: That's different. Don't worry about it. I'm sure I'll get it straightened out. Worse comes to worst, we're only a month late. They won't send the collection agency after us.
Grace: I know I can count on you to take care of it. I just don't want this late payment to affect our credit rating.
Will: Leave it to me. I'll take care of it on Monday. It's as good as done.
[end of dialog]
In this podcast, we talk about paying the “bills.” The “bills” (bills) means the expenses or the things that you have to pay such as your telephone and your electricity and your water. You have to pay the bills, the bills of your house. Well, in this dialog, Grace, the woman, says, “Did you already pay the bills for this month?” And Will says, “No. I haven’t gotten around to it yet.” “To get around to something” means that you are planning on doing it but you haven’t done it yet. Maybe because you don’t think it’s very important or maybe because you’ve been so busy that you haven’t been able to do it. So, that expression, “Have you got around to it yet?” “No. I haven’t,” means I haven’t done it yet, but I am planning on doing it.
Well, Grace says that they received a “late notice” from the credit card company. A “late notice (notice)” is when you do not pay your credit card bill or any bill on time when you are supposed to. And after maybe five, ten days, the company will send you a “late notice,” telling you that you are late in paying the bill. The notice that Grace received says they haven’t received the payment yet, and it’s past the due date. The “payment” is (payment) the money that they send to the company to pay your bill or pay their bill, in this case.
The “due date” – (due) “date” (date) – the “due date” is the day that something has to be paid. It is the deadline for when you have to pay a certain bill. To say something is “past the due date” is the same as saying it’s “past due.” “It’s past due” (past) “due” (due) – is the same as it is after the day or the date that something has to be paid. Well, they’re being charged a “late fee” plus a “finance charge.” A “late fee” (fee) is extra money they have to pay because they are late. And a “finance charge” (finance) – a “finance charge” is money – a percentage – that you have to pay on what you owe. This, of course is how credit card companies make money – one way they make money as that, if you don’t pay off or pay completely what you owe every month, you have a “finance charge.” And it’s like interest that you pay on a loan.
Well, Will says that he can’t believe what has happened. He says he paid the minimum payment on the last bill. The “minimum” (minimum) – the “minimum payment” is the least amount. So, for credit card companies – VISA, Mastercard – they will say, “Well, you spent $500. You don’t have to pay us $500. This month you can pay us just $50 and we will charge you interest on the rest of the money. So, the $50 is the least amount – the minimum payment. And if you pay the minimum payment, you don’t have a late fee. But you do have a finance charge. Will says that “I better call and talk to customer service tomorrow.” “I better call” (better) means “I ought to call.” “I should call.” And that’s a common way that we say that. For example, “You better go to school” means you should, you ought to go to school. It’s somewhat informal.
Well, Will says, “I better call and talk to customer service.” “Customer service” is the department in a company that takes care of its customers, that if you have a problem or a complaint, these are the people you call and you end up waiting on the telephone for many hours – that’s customer service. “Customers” just, of course, another word for the person who is buying the product or service. Will says that he’s sure it’s a “mix-up.” A “mix-up” (mix-up) is a mistake. When someone says there was a “mix-up,” they mean there was some confusion. There was some problem, some error. Grace says that she tried calling the credit card company the last time they were late and told them that the check was “in the mail.” That expression “The check is in the mail” is sometimes used as a joke, meaning I have already sent you the money and it is in the mail service – they haven’t delivered it yet. Many people say that, something as a joke because of course, you can always say, “Oh, yeah. I mailed the check already. You just have not received it.”
Well, according to Grace, the company – the credit card company – didn’t buy her reason, didn’t buy her excuse. She says, “They didn’t buy it.” In this case, “to buy” means to believe, not to purchase something with money – that’s also a use of the verb “to buy,” but here it means simply “to believe something,” usually something that is an excuse, perhaps or some explanation that may not be true. We will sometimes say, “Well, she told me that she loved me, but I don’t buy it. I don’t believe it.” Isn’t that one of our great problems in the world? Well, Will says that this situation here is different, that he’s sure he can get it “straightened out.” To get something “straightened out” (straightened) – “to straighten something out” or “to get it straightened out” means to get it fixed, to solve the problem, to end the confusion. If there was a mix-up, you can “straighten it out” – means you can undo or tell the person what actually happened and end the confusion.
Will then says, “Worse comes to worst, we’re only a month late.” The expression “worse (worse) comes to worst (worst)” means that in the worst possible situation. We sometimes say, “Worst case scenario.” A “scenario” (scenario) is like a situation. So, what he’s saying here is “Even if the worst thing” – and “worst,” of course, comes – bad, worse, worst, right? – something that is more bad is “worst.” We don’t say “more bad.” We say “worst” – something that is the worst situation is the most negative possible situation. So, “Worse comes to worst,” Will says, “we’re only a month late. They won’t send the collection agency after us.” A “collection (collection) agency (agency)” – a “collection agency” – these are usually private companies that are responsible for getting money that is owed to companies. So, when people don’t pay their bills, for many months, there will be a collection company that will call them, mail them, try to get them to pay their bills. These collection agencies take a percentage of how much the bill is, and that’s how they make money.
Well, Grace says that she knows she can “count on” Will. “To count on” means to rely on. She says, “I don’t want this late payment to affect our credit rating.” Your “credit (credit) rating (rating)” is the information that companies look at when they want to see if you are good with your money – if you had paid your bills on time. And if you don’t, you can get a “bad credit rating.” And in the United States, that’s very important because if you want to buy a house or buy a car, and you have a bad credit rating, many companies will not give money to you. So, it’s important to have a good credit rating by paying your bills on time. Will says to Grace, “Leave it to me,” meaning let me take care of it. I will handle it. I will solve the problem. “It’s as good as done.” “It’s as good as done” means you don’t have to worry about it. I’m going to do it and there’ll be no problems.
Now let’s listen to the dialogue this time at a native rate of speech.
[start of dialog]
Grace: Did you already pay the bills for this month?
Will: No, I haven't gotten around to it yet. Why?
Grace: We got a late notice from the credit card company. The notice says that they haven't received the payment yet and it's past the due date. We are being charged a late fee plus a finance charge of 15%.
Will: Let me see that. That can't be right. I paid the minimum payment on the last bill. I better call and talk to customer service tomorrow. I'm sure it's a mix-up.
Grace: I really hope so. The last time we were late with the payment, I tried calling them and letting them know that the check was in the mail, but they didn't buy it.
Will: That's different. Don't worry about it. I'm sure I'll get it straightened out. Worse comes to worst, we're only a month late. They won't send the collection agency after us.
Grace: I know I can count on you to take care of it. I just don't want this late payment to affect our credit rating.
Will: Leave it to me. I'll take care of it on Monday. It's as good as done.
[end of dialog]
The script for today’s podcast was written by Dr. Lucy Tse.
Remember to visit our website for a script of this dialog. You can read that on www.eslpod.com.
From Los Angeles, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
bill – a piece of paper that a company or business gives or sends someone to let that person know the amount of money he or she owes
* Joseph used a lot of electricity last month and the bill from the electricity company was very high.
not gotten around to it – not done something one was supposed to do; not finished something that one plans on finishing soon
* Cassandra needs to write an essay for her English class but she has not gotten around to it yet.
late notice – a written statement saying that a bill that should have been paid has not been paid yet; a piece of paper saying that one has not paid the money one owes to a company by the day the company was supposed to get the money
* Harrison did not pay the phone company the money he owed last month, so he was not surprised when he got a late notice.
payment – money given to a person or company to pay for an item or service
* Betsy had to make nine more payments to the bank to pay the money she owed on her car.
due date – the last day that one has to give something to someone else who is expecting it; the last day that one has to give money to a person or company
* The due date for the report was Friday, but Gina’s boss gave her until Monday to finish it.
late fee – extra or additional money that one must pay because the money one needed to give to someone else was not paid on time
* Levi did not pay the credit card company on time, so he had to pay a late fee when he sent them the money.
finance charge – a percentage of money that one must pay to a company, in addition to the money owed, because one is paying the money back a little at a time, rather than all at once
* Tara had to pay the credit card company a finance charge of 10% because she is paying it back over six months.
minimum payment – the lowest amount of money one must pay to a company that one owes a large amount of money to
* The total amount of money that needed to be paid was $500, but most people pay the minimum payment of $25 each month.
customer service – the part of a company that talks to customers about helps them to start or end services, or with problems or worries customers have
* Antonio’s cable television wasn’t working, so he called the cable company and talked with customer service.
mix-up – a mistake; an error
* There was a mix-up at the bank, and Diana’s account had less money in it than it should have.
the check is in the mail – the payment has been sent but not received; the money one owes has been sent, but the company that the money is going to has not received that money yet
* The customer claimed that the check was in the mail, but the credit card company never got it.
to buy it – to believe it; to think that someone is telling the truth
* Isis told Jack that she watched him play in the baseball game, but Isis hates baseball so Isaac didn’t buy it.
straightened out – fixed; solved; answered
* Gabriel was confused about how much he owed the credit card company, but he straightened out the problem and was able to pay them the right amount.
worst comes to worst – if the worst thing happens; if the worst outcome possible happens
* My friend is late, but if worst comes to worst, we can leave without her.
collection agency – a company hired by companies to collect money owed to them when a customer has failed to pay his or her bills
* Martha had not paid any of her telephone bills and owed a large amount of money, so the telephone company sent a collection agency to get that money.
credit rating – a score that measures one’s history and ability to pay back money that one owes
* Yvette always paid the money she owed, so she had a very good credit rating.
It's as good as done. – It will get done.; a statement one makes when telling someone that the action one plans on doing will definitely be done
* I have not made an appointment with my doctor yet, but it’s as good as done.
Culture Note
A Pretty Penny
A penny is, in American “currency” (money), the smallest possible amount (equal to 1/100 of a dollar). Since 1909, it has had the “image” (picture) of President Abraham Lincoln on it and is sometimes referred to as the “Lincoln penny.”
There are many expressions using the word “penny.” One of the most popular is “a pretty penny,” which means a lot of money or expensive. You might say: “That car cost him a pretty penny!” The origin of the term is very old: In the year 1257, the English government “issued” (began to use) a gold coin that never became very popular. People didn’t like using it, and so the government stopped making them. After that, it was quite rare to see this “attractive” (pretty) gold coin, so the coin became associated with something very valuable, something worth a lot of money. Somehow this got changed into a “penny” and became popular in the U.S. Today, a penny is actually worth very little, so it’s a little strange that “a pretty penny” actually has the opposite meaning – something quite expensive!
There are actually several expressions related to the penny, including:
“A penny for your thoughts”: This expression is used to ask someone to tell you what they are thinking, especially if the person doesn’t seem to want to talk. The expression is used typically as a complete sentence. We don’t say: “I’ll give you a penny for your thoughts,” but rather simply “A penny for your thoughts.”
“Penny pincher”: This is someone who is considered cheap or who never spends his or her money. “To pinch” here means to save, so a penny pincher is someone who saves even very small coins, like pennies.
“To turn up like a bad penny”: This one is a little “old-fashioned” (not popular today), but you may still see it. “To turn up” means to arrive or appear unexpectedly. A bad penny refers here to a bad or undesirable person who keeps returning even when they are not wanted, someone who we might describe as “pushy” (too aggressive in trying to get what he or she wants): “I told my cousin that I didn’t want to see him again, but last night he turned up like a bad penny.”