= 1072
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,072 – Working Part-Time Jobs.
This is English as a Second Language Podcast episode 1,072 I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. When you do, you can join ESL Podcast as a member and download our Learning Guide.
This episode is a dialogue between Luisa and Max about working a job less than 40 hours a week – that is, a part-time job. Let’s get started.
[start of dialogue]
Luisa: Are you still here? I thought you got off at three o’clock.
Max: I picked up a second shift. I could use the money.
Luisa: But I thought you had another part-time job in the evenings.
Max: I normally do, but the restaurant where I work has been cutting back my hours, so I’m trying to pick up as many extra shifts here as I can.
Luisa: And don’t you work at the amusement park on the weekend?
Max: I do half the year, but it’s winter and the park only keeps a skeleton crew on during these months. In the meantime, I’m working for a temp agency, which gives me short-term assignments.
Luisa: I don’t know how you juggle all these jobs.
Max: I have no choice. I have to piece together an income if I want to pay rent.
Luisa: Have you ever thought about going back to school to qualify for other work, something full-time?
Max: Sure, all the time. I’d like a better job, one with benefits and a reliable salary.
Luisa: What’s stopping you?
Max: I have to pay for something called “food,” and I haven’t met my fairy godmother yet!
[end of dialogue]
Luisa begins her dialogue by saying to Max, “Are you still here?” This is one of those questions you ask when you’re surprised about something – obviously Luisa can see that Max is still wherever they are. She says, “I thought you got off at three o’clock.” “To get off of work” means to finish your work schedule, to be able to leave the place where you work. If someone says, “What time do you get off?” they mean “What time do you get off of work?” When do you stop working? What time do you stop working?
Max says, “I picked up a second shift.” A “shift” (shift) refers to a period of time when people work. Usually this term is used for jobs when people work at that particular location more than eight hours, or that there are people working at that location for more than eight hours. It might be, for example, a place where there is someone working 24 hours a day. Well, one person is not going to work 24 hours straight, so they break up the day into shifts.
So, if you work the day shift, you’re working probably from eight in the morning until around four or five in the afternoon. If you working the night shift, you’ll be working perhaps from four or five in the afternoon to midnight. If you’re working what we call the “graveyard shift,” you’re working probably from 11:00 at night or midnight to seven or eight in the morning. Those are “shifts,” then – divisions of the workday in a place that usually is open for more than eight hours.
Max says he “picked up a second shift.” “To pick up” here means to get, to obtain. He was working one shift, and now he’s picked up a second shift – which means, of course, he’s working more than eight hours a day. Why has Max done this? Well, he says, “I could use the money.” When someone says, “I could use the money,” he means that he would be able to benefit from getting more money. He has some need of extra money.
Luisa says, “But I thought you had another part-time job in the evenings.” A “part-time job” is a job usually that is less than 40 hours per week. In the United States, 40 hours per week is considered “full-time.” If it’s less than 40 hours, we might call it “part-time.” Luisa thought that Max had another part-time job. Max says, “I normally do, but the restaurant where I work has been cutting back my hours.”
When we talk about someone “cutting back” on something, we mean that he is using less of it or he is reducing the number of something. The two-word phrasal verb “to cut back,” then, means to reduce the number of something – in this case, we’re talking about the restaurant where Max works cutting back his hours. His “hours” refers to the number of hours that he can work. Max says he’s trying to pick up “as many extra shifts here as I can.”
Luisa then asks, “And don’t you work at the amusement park on the weekend?” An “amusement (amusement) park” is a large park usually that has lots of what we would call “rides” in them – places where people, especially children, can play games and get into these machines that go really fast, for example. Disneyland is an example of an amusement park here in Southern California.
Luisa asks if Max is still working at an amusement park on the weekends. He says “I do half the year,” meaning I do work there part of the year, “but it’s winter and the park only keeps a skeleton crew on during these months.” Max is saying that that the amusement park where he normally works in the summertime only has a skeleton crew during the wintertime. The phrase “skeleton (skeleton) crew (crew)” refers to a very small number of workers – the minimum number of workers you can have at a place.
If the business doesn’t have very many customers, it might have very few employees, and we might call that a “skeleton crew” if during busy times the company has more employees. This is the case with the amusement park. It has a skeleton crew. The word “crew” just refers to a group of people. The word “skeleton” is normally used to describe the bones of your body or the bones of an animal.
Max says, “In the meantime,” meaning during this winter season, “I’m working for a temp agency, which gives me short-term assignments.” A “temp (temp) agency” is a company that finds people temporary jobs. The word “temp” is short for temporary, meaning short-term – not permanent, not for a long time. There are, of course, many companies that find workers, find people to work for companies that just need workers for a short period of time.
Max says the temp agency gives him “short-term assignments.” “Short-term” refers to a short amount of time – perhaps a week, perhaps even a day. I used to work for temp agencies when I was in college. I would call up every morning and see if they had any work for me, and they would send me to jobs that would last maybe one day, maybe two or three days, sometimes as long as a month. Temp agencies are very popular now, especially when the economy is not doing so well. Companies don’t want to hire employees full-time.
Luisa says, “I don’t know how you juggle all these jobs.” The verb “to juggle” (juggle) usually refers to throwing objects up in the air and keeping them up in the air. We refer to someone who does this as a “juggler,” but here the verb means to handle many different things at the same time, to be able to do many different things at the same time. Max says, “I have no choice” – I have no other option – “I have to piece together an income if I want to pay rent.” “To piece (piece) together” something means put together, to assemble. An “income” (income) refers to the money you get from working.
Max is saying that he has to work a little bit at this job and a little bit at that job in order to make enough money to pay for his rent. Luisa says, “Have you ever thought about going back to school to qualify for other work, something full-time?” “To qualify (qualify) for” something means you have the skills and/or education in order to be able to do something. So for example, if you want to be a doctor, you have to study for many years in order to qualify for that kind of job – at least, I hope you study many years if you’re a doctor. If not, please don’t to be my doctor.
Luisa is asking if Max has thought about going back to school to qualify for some kind of job that would be full-time, that would be 40 hours a week. Max says, “Sure, all the time,” meaning I have thought of it a lot. He says, “I’d like a better job, one with benefits and a reliable salary.” “Benefits” (benefits) refers to things such as health insurance and vacation time and sick pay – money you get when you can’t work because you’re sick. These are common benefits that you get when you have a full-time job.
“Salary” (salary) refers to money that you get to work at a certain place, usually by the month or by the year. When we talk about a salary, we’re talking about money you get regardless of how many hours you work. There are two kinds of ways of getting paid – one is by the hour, when you get paid a certain amount of money for every hour you work. Another way of getting paid is by salary. When you’re getting paid on a salary, we would say you are getting a certain amount of money and are expected to do your job, even if it takes more than the normal 40 hours a week.
Luisa says, “What’s stopping you?” What’s preventing you from going back to school? Max says, “I have to pay for something called ‘food.’” Max is making a joke here. He’s saying that he can’t afford to go back to school. He doesn’t have enough money to go back to school because in addition to paying his rent, he also has to eat, and to eat he has to buy food.
He finishes by saying, “I haven’t met my fairy godmother yet.” A “fairy (fairy) godmother (godmother)” is a character from children’s stories – stories that we tell children – usually involving a woman who has some sort of magical powers. The fairy godmother is a common character in certain fairytales that are told to children. These are made up stories about magical events. Here, Max is using the expression to mean that he hasn’t found someone who’s just going to give him money to pay for his expenses and to go to school.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Luisa: Are you still here? I thought you got off at three o’clock.
Max: I picked up a second shift. I could use the money.
Luisa: But I thought you had another part-time job in the evenings.
Max: I normally do, but the restaurant where I work has been cutting back my hours, so I’m trying to pick up as many extra shifts here as I can.
Luisa: And don’t you work at the amusement park on the weekend?
Max: I do half the year, but it’s winter and the park only keeps a skeleton crew on during these months. In the meantime, I’m working for a temp agency, which gives me short-term assignments.
Luisa: I don’t know how you juggle all these jobs.
Max: I have no choice. I have to piece together an income if I want to pay rent.
Luisa: Have you ever thought about going back to school to qualify for other work, something full-time?
Max: Sure, all the time. I’d like a better job, one with benefits and a reliable salary.
Luisa: What’s stopping you?
Max: I have to pay for something called “food,” and I haven’t met my fairy godmother yet!
[end of dialogue]
Our scriptwriter is very qualified for the job that she does here at ESL Podcast, which is, of course, writing scripts. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to get off – to finish one’s work schedule and be able to leave one’s workplace
* I get off at 7:00 tonight. Can you give me a ride home?
to pick up – to grab, get, or obtain something, especially if it is a good, favorable thing
* At the beginning of the year, the school choir was really small, but we’ve picked up a few new members.
shift – a period of time when a group of workers fill certain jobs, to be replaced by another group of works at a later time during the day, so that someone is always working
* The factory uses three eight-hour shifts to keep the machinery running nonstop.
could use – able to benefit from having or doing something
* I could use a break. Would you mind answer the phones for a few minutes?
part-time – referring to a job that is less than 40 hours per week; working for only a part of the normal workday or work week
* Part-time employees aren’t eligible for health insurance, but full-time employees are.
to cut back – to reduce the number or amount of something, especially to save money
* If you want to lose weight, try cutting back on junk food and exercising more.
(one’s) hours – the number of hours per week that one works, or the schedule that one normally works
* Ashton uses a time sheet to report his hours to the payroll office.
amusement park – a theme park; a large park with many mechanical rides designed to excite, thrill, entertain, and please paying visitors
* Most of the rides at the amusement park require riders to have a minimum height of 42 inches.
skeleton crew – minimal staffing; the smallest number of workers who can keep a business running, used to save money when business is not busy
* The university library has a skeleton crew in the summer, when there are very few students.
temp agency – a business that finds temporary (short-term) job placements for people with companies that do not want to commit to hiring workers
* We need some help with data entry for a few days next week. Do you think the temp agency could find someone to help us?
short-term – temporary; lasting only a short amount of time; not permanent
* This is only a short-term solution. We need to find a permanent solution soon.
to juggle – to handle many things at the same time, especially when it is challenging or difficult
* I don’t know how Shannon juggles school, a full-time job, and motherhood. When does she sleep?
to piece together – to make something from many smaller pieces; to get little bits of what one needs from many different sources
* Through interviews and careful research, the journalist began piecing together the story.
income – money that one receives, especially for one’s work; revenue
* Their combined income is well over $100,000 per year.
to qualify for – to meet the requirements of a job or position; to have the characteristics needed in order to have or do something
* Computer manufacturers in this country are struggling to find people who are qualified to perform technical jobs.
full-time – referring to a job that is 40 or more hours per week
* After college graduation, Jake decided to travel for a few months before settling into a full-time job.
benefits – helpful, useful, and attractive things that one receives in exchange for one’s work, not including money
* Benefits for our employees include health insurance, dental insurance, a retirement savings plan, and free bus passes.
salary – the amount of money received in a year in exchange for the work of someone who is not paid by the hour
* Jane is looking for a job with a salary of at least $65,000.
fairy godmother – in a fairy tale (fictional story for children), a woman with magical powers who brings good luck and fortune to the main character
* Pinocchio is the story of a wooden puppet brought to life by a fairy godmother.
Comprehension Questions
1. Why does the amusement park have a skeleton crew in the winter?
a) To scare visitors on Halloween.
b) To save money by having few employees.
c) To keep its operations hidden from competitors.
2. Why doesn’t Max study to get a full-time job?
a) Because he doesn’t have enough money to go to school.
b) Because he isn’t smart and doesn’t like studying.
c) Because he enjoys having many short-term jobs.
Answers at bottom.
What Else Does It Mean?
shift
The word “shift,” in this podcast, means a period of time when a group of workers fill certain jobs, to be replaced by another group of works at a later time during the day, so that someone is always working: “Can you work my shift next Saturday?” The “graveyard shift” or the “night shift” refers to the shift worked at night: “Working the graveyard shift means sleeping during the day when everyone else is at work.” A “swing shift” is a work schedule from 3:00 or 4:00 p.m. to 11:00 p.m. or midnight: “The best thing about working the swing shift is that there’s no traffic during my commute.” Finally, a “split shift” is a schedule where someone works for two blocks of time during the day: “Harvey has a split shift, so he works for a few hours early in the morning and then again in the afternoon.”
to qualify for
In this podcast, the phrase “to qualify for” means to meet the requirements of a job or position, or to have the characteristics needed in order to have or do something: “How old was Oscar when he qualified to compete in the Olympic games?” The phrase “to be qualified for (something)” means for the person to have the required skills: “David doesn’t seem qualified for an executive position in this company.” The phrase “to qualify as” means to have the characteristics to be perceived or considered in a certain way: “Just making a good sales presentation doesn’t qualify as a success. You actually have to make a sale.” The phrase “to qualify a statement” means to clarify the meaning of what one has said, usually making it less strong or limiting its affect: “The spokeswoman qualified her statement that no one would be fired to very few people would be fired.
Culture Note
The Part-Time Worker Bill of Rights Act of 2013
In February 2013, Janice “Jan” Schakowsky, a U.S. Representative for Illinois, “introduced” (ask Congress to consider “enacting” (making into a law)) the “Part-Time Worker Bill of Rights Act of 2013.” This “bill “(proposed law) would “penalize” (punish) employers for failing to provide health care to part-time employees.
One of the “unintended consequences” (things that happen as the result of something else, even though nobody planned it that way) of the “Patient Protection and Affordable Care Act” passed in 2009 was that it gave employers an “incentive” (motivation; a reason to want to do something) to “drop” (remove) employees from its health insurance programs. The Affordable Care Act includes a “fine” (money that must be paid as a punishment) for employers who do not provide health insurance benefits for full-time workers, but not for part-time workers. As a result, some employers began “cutting” (reducing) employees’ hours so that they would be part-time employees and the employer wouldn’t have to provide health insurance benefits.
Representative Schakowsky’s bill would “reverse” that (make something become the opposite) by penalizing employers for not providing health insurance benefits to part-time employees, too. The Act would also extend coverage for part-time employees under the “Family and Medical Leave Act” (a law that allows people to take “unpaid leave” (time spent away from work without receiving payment) for family and medical emergencies) and the “Employee Retirement Income Security Act” (a law that determines who can participate in “pension plans” (plans through which employers pay money to former workers in their retirement).
The Act is strongly supported by the “United Food and Commercial Workers International Union” (UFCW) and other “unions” (organized groups of laborers who advocate for workers’ rights).
Comprehension Answers
1 - b
2 - a