= 1708
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast English Café number 403.
This is English as a Second Language Podcast’s English Café episode 403. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download this episode's Learning Guide by becoming a member of ESLPod.com.
On this Café, we’re going to continue our series on famous songs, focusing on “Three Blind Mice,” a song popular for children. We’re also going to talk about another national park, this time in the state of Hawai’i. And as always, we’ll answer a few of your questions. Let's get started.
Our Café begins today with a continuation of our series on famous American songs, or at least famous songs in English. Today's song, “Three Blind Mice.” was originally an English nursery rhyme, and by “English” I mean from England. A “nursery rhyme” (rhyme) is a short poem that is often repeated or said to babies and young children. Nursery rhymes are often meant to be funny and often they are a little what we would call “silly.” Something that is “silly” is something that is funny that perhaps doesn't make a lot of sense, that isn't meant to be serious.
“Three Blind Mice” was originally published as a poem back in 1609, so it is quite old. Some people think that the author was Thomas Ravenscroft but nobody knows for sure, and really, nobody cares. Some nursery rhymes like “Three Blind Mice” are also sung with a simple melody, a simple tune, a simple set of musical notes. This particular nursery rhyme is what we call a “round.”
A “round” is a type of song that people sing together at different times. You have one person, or one group, that starts the song, then you have another group that starts the song, usually one or two lines later. And so, it almost works like a fugue in classical music. J.S. Bach, the composer, was famous for his fugues. A round is kind of a fugue. It's not really a fugue in a technical sense, but the idea is that you have this melody, this line of music, going and repeating but at different times. We’ll give an example of this in a minute. The idea is that the music, the different melodies, “harmonize,” meaning that even though the melodies are at different points, the notes, the musical notes, sound good together.
As with most children's songs, the words to nursery rhymes have changed over time, especially a nursery rhyme as old as this. Some people know different versions so the version I may talk about won't be the same as the version someone else may talk about. I'll start by singing the first part of the song and then talking about what it means.
"Three blind mice. Three blind mice.
See how they run. See how they run.
They all ran after the farmer's wife,
Who cut off their tails with a carving knife,
Did you ever see such a sight in your life,
As three blind mice?"
The song goes by very quickly. The topic of the song is three blind mice. “Mice” is the plural of “mouse” (mouse), which is a small animal. You may be familiar with the most famous mouse in the world, Mickey Mouse. Well, Mickey Mouse was not blind. “To be blind” (blind) means you can't see. You have eyes but you can't see. This children's song, this nursery rhyme, is about three mice who are blind.
I should also explain that “nursery” is the place where young children are taken care of. A “rhyme” is when two words sound similar. They have similar sounds in them like “might,” “write,” “bite,” “tight” – those are all words that rhyme. So, a nursery rhyme is a song that has rhymes in it for children in a nursery.
Back to the song then: this is about three blind mice. The song starts, “Three blind mice. Three blind mice. See how they run. See how they run.” You're being asked to look at the mice. Why? Well, they are all running after the farmer's wife. “To run after” means to chase, to try to (sometimes) catch or attack. The farmer's wife would be the wife of the person who runs the farm. A “farm” is a place where you have animals and you grow food.
So, you have this silly picture of three mice who are blind – who can't see – running after or chasing the wife of the farmer. Now, why are the mice running after the farmer's wife? We find out the reason. The next line says that the farmer's wife “cut off their tails with a carving knife.” Wow!
“To cut off” means to use scissors, a knife, or some other sharp instrument to separate a piece of something from the whole, from the main body. Your “tail,” if you're an animal, is the little thing that sticks out the back, near your butt, I guess we could say. A dog has a tail, for example. Most dogs have tails. Mice have tails. These tails, however, have been cut off by the farmer's wife using a carving knife. A “carving (carving) knife” is a special knife used usually to cut a large animal – the meat off of a large animal, for example, a turkey or a large piece of ham. You would use a carving knife, a big long knife, in order to cut the meat off of the cooked animal. I've never used a carving knife to cut off a mouse's tail. I have used it to cut turkey at Thanksgiving.
The song then asked, “Did you ever see such a sight in your life as three blind mice?” The phrase “in your life” or “in my life” would mean “ever.” It's an expression we would use when we’re surprised at something or something's unusual, or we want to emphasize that this has never happened before. “I have never in my life seen such a beautiful cat.” I have never seen a cat as beautiful as the cat that I saw yesterday – just an example of course. I don't really think most cats are beautiful, but the idea is that it doesn't happen very often.
So, the question has the implication that this is a very strange event. Did you ever see such a sight, such a scene, such a picture, in your life as three blind mice? Have you ever witnessed this before? We’re now going to listen to the song again, but I'm going to, through the magic of technology, play it as a round. So, you're going to hear my voice as you would hear different voices in an actual performance of the song, with three people. You're going to hear three parts of the song, three different voices, even though it's all my voice. Let's listen.
"Three blind mice. Three blind mice.
See how they run. See how they run.
They all ran after the farmer's wife,
Who cut off their tails with a carving knife,
Did you ever see such a sight in your life,
As three blind mice?"
Okay not perfect, but not bad either.
Nursery rhymes, I said before, are usually simple and silly. Sometimes, however, they might have some other meaning that has become obscured. Something that is “obscured” (obscured) is difficult to understand because we don't have all of the evidence. We can't see clearly the origin of the nursery rhyme.
“Three Blind Mice,” some people say, is about Queen Mary of England and how she executed or killed different enemies of hers, religious enemies of hers, and these enemies were the mice in the song. She didn't blind the leaders, of course; she killed them, as many religious leaders killed people of other religions during a certain period in European history. Most Americans don't look at the song or hear the song and think about the political and religious implications. It's just a nice little song that you sing to your child.
Now let's turn to our next topic, which is the beautiful national park located in the island state of Hawai’i called “Hawai’i Volcanoes National Park.” Hawai’i is, at least in Hawai’i, spelled with an apostrophe between the last two i’s. People who live in Hawai’i will sometimes pronounce the name of the state “Ha-VAY-ee,” but the more standard pronunciation is “Ha-WHY-ee.” In any case, the Hawai’i Volcanoes National Park is located on the biggest island in the Hawaiian islands. It's called the “Big Island” or the island of Hawai’i. The other main islands in Hawai’i are Oahu, where most of the people live, Maui, and Kawai.
Hawai’i is popular as a vacation destination – a place where people go to sit on the beach, and enjoy the beautiful weather in Hawai’i. I've had the opportunity to go several times and I absolutely love going to Hawai’i. It's a very different atmosphere, a different what we would call “pace of life.” Things are slower, more relaxed, even more relaxed than here in California, which a lot of people think is too relaxed already.
Hawai’i is famous also for its volcanoes. “Volcanoes” are mountains that have a certain kind of activity underneath them. What happens is that very hot rock called “magma” (magma) is under the surface of the mountain, and there's a lot of pressure, and when this pressure reaches a certain point, it pushes the magma out through the top of the mountain. The verb we would use here is “erupt.” “To erupt.” (erupt) means to explode out of the top of a mountain with, in this case, a lot of hot rock, a lot of what we call “lava” (lava). Lava is basically liquid rock that is thrown into the air and goes down the side of the mountain. Eventually, the lava cools and it becomes hard again. An “active volcano” is a volcano that is still erupting today. There are two volcanoes in Hawai’i that are active. One of these two volcanoes, Mauna Loa, is the biggest volcano in the world.
The Hawaiian islands are what we call a “volcanic archipelago.” “Archipelago” (archipelago) is a group of islands that were formed when volcanoes erupted underneath the ocean floor and, over time, the lava from those eruptions formed a new set of islands. The word “archipelago” is not very common in English but it is the technical term to describe a group of islands. In this case, it's used to describe the Hawaiian Islands.
The area of the national park in Hawai’i – Hawai’i Volcanoes National Park – covers more than 500 square miles. That would be about 1300 square kilometers. It was designated or named a U.S. national park way back before Hawai’i was even part of the United States, at least as a state. At that time, Hawai’i was still a territory of the United States. It was designated a national park in 1916. It was also designated as a World Heritage Site in 1987. The park includes an 11-mile road that goes around the top part of one of the mountains, around the summit of the mountain. It's called the “caldera” (caldera), which is basically a bowl-shaped area that forms around the top of a mountain after it has erupted. Usually, what happens is the top collapses or goes down lower than the area around it and that forms this bowl-like structure called a caldera. Caldera is originally a Spanish word.
The park offers a lot of opportunities for camping, and you know how much I love camping. Camping is sleeping outdoors in a tent or simply sleeping on the ground with nothing over you. We also call that activity “being crazy.” I'm just kidding. If you like to camp, that's wonderful. Just come and visit me at my hotel someday.
The park has, as I said, a lot of opportunities for camping, but seeing the volcanoes erupt is one of the most impressive experiences. Some people would describe it as an “awesome” experience. That word “awesome” (awesome) has come to mean, in the last 20 years or so, very interesting, very cool, very neat, very fascinating. People use that word a lot now, more than they did when I was growing up. The original meaning of awesome was something that was perhaps even a little frightening, a little amazing, but in a way that could scare you. Now, the word just means fantastic, great, what they might say in British English, “brilliant.”
Another verb that we might use to describe this experience is “to marvel” (marvel). “To marvel at something” is to be amazed at something, to think something is wonderful, to think something is great. “Marvel” can also be a noun to describe something that is great. You may have heard of Marvel Comics, which is a certain group of comic books published by a company called Marvel Comics. Here, we’re talking about marveling at the Hawaiian Islands and the amazing volcanoes that you can see there.
The National Park Service, the U.S. government organization that runs or takes care of all of our national parks, monitors the volcanic activity in the park. “To monitor” means to watch carefully. In case there is a big explosion, they may need to move people away from the mountain.
If you want to see some impressive photos and videos of the volcano, you can go to the National Park Service website. Just Google “National Park Service United States” or go to NPS.gov. Just search for Hawai’i Volcanoes National Park and you'll find some interesting photos and movies. I haven't, myself, ever been to the Volcanoes National Park. It is definitely on my list of places to visit the next time I go to Hawaii.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Muhamad (Muhamad) in the United Arab Emirates. The question has to do with three words, “incoming,” “oncoming” and “upcoming.” The first word, “incoming” (incoming), means something that is arriving soon or something that is in the process of arriving or being received. For example, if you have a fax machine, a facsimile machine, where you can send copies of pieces of paper to someone else with a fax machine, you might talk about an “incoming fax.” This would be a fax that is being received right now, as you're talking. “Incoming” can also mean that it is about to arrive. So, it has both possible meanings.
“Oncoming” means something is coming toward you. You're driving down the street and you see a bicyclist driving towards your car. That would be “oncoming.” You have to be careful with “oncoming traffic,” oncoming cars. You don't, of course, want to hit each other. We have the expression “oncoming traffic” to refer to cars that are moving in the opposite direction that you are.
“Upcoming” (upcoming) means something that is going to happen in the future. Usually, it's next week or next month or even next year. It doesn't mean in five minutes, although it could technically mean that as well. It means something that will happen in the future.
“Incoming” is usually used to talk about communication, such as emails, phone calls, or faxes. “Incoming emails” would be emails that you receive. Incoming is not used very often to mean “arriving soon,” unless we're talking about being in a war or in a military battle, and you have missiles or rockets that are going to arrive and hit where you are stationed, where you are standing.
Our next question comes from Belgium, from the Jeroen (Jeroen). The question has to do with the word “featured” (featured). “Featured” comes from, of course, “feature,” which can have a couple of different meanings. Feature can be a characteristic of something. “Feature” can be different parts that are available or different benefits of some product or service. You might buy a new car with lots of interesting new features. It might have a place to plug in your iPod. It might have automatic temperature control. It might have a television in the back seat. These would all be “features,” aspects or parts of some product that are desirable that you would want.
“Feature” can also describe a movie or a film. Some people would just use the word “feature” without even saying “feature film.” “Tonight's feature is a movie by Woody Allen.” “Feature” in a newspaper or magazine is an article, usually a longer article about one special topic.
The verb “to feature” means to have someone special in a performance, either a song or a movie, or a television show, or simply to have someone or something special in a presentation that you're doing. So, you might have a song that “features” some famous singer. It might be a song from a group, but they invite another singer into the group and that singer is the “featured singer.” We say “featured” because we are featuring them. We are including them and highlighting them or paying special attention to them because they are special.
As a noun then, “feature” can mean characteristics. You could talk about the “facial features” – what the eyes look like, what the nose looks like, what the mouth looks like. You could also talk about a feature as a special story in a newspaper. You can talk about a feature being a film, a feature of a product or service as some benefit, something that you can use for a benefit, something that would be useful to you. Finally, “feature” as a verb, means to pay special attention or to give special emphasis to something or some person. We often talk about films “featuring” famous stars – John Travolta or Tom Cruise or Angelina Jolie or Brad Pitt. They could be “featured” in a movie. They could be the ones that star in the movie, that we pay special attention to.
Our final question comes from Iran from Farzad (Farzad). The question has to do with the difference between “fill in” and “fill out.” This is a good question. Both of these, “fill in” and “fill out,” are phrasal verbs. Both can actually mean the same thing. The difference is when you use one versus the other. There are also some differences in definitions between the two verbs. Let's start with “to fill in.”
“To fill-in” can mean to complete something such as a form. “Fill in this form” means put all the information down on this piece of paper that it is asking for. However, “to fill out” can also mean to complete a form. So, you could say “Fill in this form.” You could say “Fill out this form.” Both are acceptable.
“Fill in” has some additional definitions, as does “fill out.” “Fill-in” can mean to replace someone temporarily. “My friend is not able to come to work today,” or “My coworker is not able to come to work today, so I'm going to fill in for her.” I'm going to do her job because she's not here. “Fill in” can also mean to give someone information about something that they missed or that they don't have. Someone who comes late to a meeting might have to be “filled in” about what happened before they got there.
“Fill out” can, in a physical sense, mean to gain weight, to get fatter, to get heavier. That would be “to fill out.” Usually, we use that when were talking about a young boy, for example, who is starting to develop his muscles. We might say he's going to “fill out.” He's going to start looking more like a man. In general, however, you should probably avoid using the term “fill out” unless you're talking about your own children or teenagers. Some people may get the wrong idea when you use that expression.
Also, I mentioned that we can use both “fill in” and “fill out” for a form, or an application. There is a special use, however, of “fill-in” when we talk about testing. When you take a test, sometimes the questions are “fill in the blank.” “Blank” would be an empty space. “Fill in the blank questions” are questions that leave a space open and you have to pick the right word or the right phrase that goes in that space. This would be common on a grammar test, perhaps. There, you can't say “fill out the blank.” You have to say “fill in the blank.” But if you're talking, in general, about a form, or some other piece of paper that ask for information, either verb is acceptable.
If you'd like to hear your question on an upcoming episode of the English Café, email us. Our e-mail addresses eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again, right here on ESL Podcast.
ESL Podcast English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2013 by the Center for Educational Development.
Glossary
nursery rhyme – a short poem that is often repeated to babies and young children
* When Jake was learning to talk, he would repeat his favorite lines from the nursery rhymes his parents taught him.
round – a type of song that several people sing together, with each person starting after the previous person had already started singing
* It’s hard to know how to end a round when everybody is singing a different part of the song.
to harmonize – for different voices or musical instruments to produce different notes that sound good together
* Do you think I should sing this part by myself, or should we harmonize to give it a fuller sound?
carving knife – a special kind of sharp, long knife that is used to cut large pieces of meat away from the bones
* Mom took out the carving knife to cut the turkey at Thanksgiving.
obscure – difficult to understand because so much time has passed and the original meaning is unclear or has been forgotten
* Mia’s attorney was able to use an obscure law to get her out of trouble in court.
volcano – a mountain that has a lot of activity happening under the surface, including the movement of very hot liquid rock
* If you walk on some parts of an active volcano, you can actually feel the heat from underground.
to erupt – for a volcano to explode and for liquid rock, steam, and gas to come out of the top of the mountain
* The townspeople were warned to get away before the volcano erupted.
lava – liquid rock coming out of a volcano
* In the movie, the hero ran down the mountain as the lava flowed down behind him.
archipelago – a group of islands
* Kyung wants to visit at least three of the islands in this archipelago.
caldera – a shallow, bowl-shaped area that forms at the top of a mountain after it has erupted, when the top of the mountain has collapsed or caved in
* The volcano in this area was active more than 500 years ago, but today, people actually live in the old caldera.
awesome – cool, neat, or interesting; causing a feeling of wonder and amazement
* It’s an awesome feeling flying in a helicopter over the Statue of Liberty.
to marvel – to feel wonder; to be amazed
* We all marveled at Sam’s ability to stay calm under stressful conditions.
incoming – expected to arrive soon; in the process of coming in
* The incoming train should arrive in less than three minutes.
oncoming – coming toward one; happening in the future
* Get out of the way of the oncoming car!
upcoming – happening soon; happening not far in the future
* What you planning to bring to the upcoming anniversary party?
featured – being an important part of or a significant characteristic of something; having a special person or object in something, such as in a movie
* Many things are on sale in our store, but our featured sale item is this TV for $200!
to fill in – to complete, such as on a form or a test; to replace someone temporarily; to give someone information they missed; to become more full, bigger, or complete
* There isn’t enough room on this insurance forms to fill in my entire name.
to fill out – to complete, such as a form; to become bigger or to gain weight
* Don’t forget to fill out the bank deposit slip before you talk to the bank teller.
What Insiders Know
Hawaii Five-O
Police shows are very popular on American television and one of the “longest-running” (with the most new episodes broadcasted) shows was Hawaii Five-O. The show first “aired” (was broadcasted; was shown on television) in 1968 and “ran” (was shown continuously) for 12 “seasons” (years).
Hawaii Five-O is a “police procedural” (following the daily investigation activities) show “set” (for a show, play, or performance to be located) in Hawaii. The show is about a special “task force” (a police group formed for a specific purpose, usually to fight a specific type of crime or group of criminals). In this case, the task force was based on an actual “unit” (group of police or military officers) that existed in Hawaii in 1940.
The “head” (leader) of the task force was a detective named Steve McGarrett. He had a team of officers who worked for him and they tried to catch some of the biggest and most “nefarious” (dangerous and evil) criminals in the State of Hawaii.
Included in Steve McGarrett’s team of officers was a young detective named Danny Williams. At the end of many shows, Steve McGarrett would tell Danny to “Book ‘em (them), Danno,” using his “nickname” (familiar or friendly name) for Danny Williams.
The show was known for many things, including its popular theme song composed by Morton Stevens. It was so popular that it reached number four on the Billboard Hot 100 pop chart, a listing of the most popular songs in the U.S.
The show was also known for “shooting” (filming) many of its episodes outdoors “on location” (in the actual location) in Hawaii. It showed many Americans who had never traveled to Hawaii what the state looked like.