= 1742
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 437.
This is English as a Second Language Podcast’s English Café episode 437. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Look at our ESL Podcast Store, where you can find some additional courses in business and daily English.
On this Café, we’re going to talk about a famous American author by the name of William Faulkner. We’re also going to talk about a popular racing event, especially among children, called the “soap box derby.” And, as always, we’ll answer a few of your questions. Let’s get started.
William Faulkner was an American author best known for his novels about the American South, or what is sometimes simply called in the U.S., “the South.” “The South” is actually the southeastern part of the United States. So, if you look at a map of the United States, if you look in the southeast corner – where Florida is, and the states around there – that 25 percent or so of the country is called “the South.” Arizona and New Mexico are in the southern part of the U.S., but no one considers that the South. The South is always the southeastern part of the U.S. Sometimes it’s called the “deep South,” but in any case, Americans know, when you refer to “the South,” what you’re talking about.
The South in many ways was defined by the central event in American history, certainly in the nineteenth century, and that would be the American Civil War. The South wanted to keep slavery legal in the United States, and the north wanted to get rid of it, to abolish it. The South lost the war, and even today, more than 150 years since the Civil War began, there is still an association in the minds of Americans with the South and the Civil War. Those two things are often connected in the American imagination, at least for those who don’t live in the South.
William Faulkner did live in the South. He was born on September 25th, 1897, in a small town in the state of Mississippi. Mississippi is located in the southeastern U.S. – in “the South,” as we call it. He was born in a small town that was about 130 kilometers southeast of Memphis, Tennessee, which is a larger city. This small town and the small towns that Faulkner lived in became the “inspirations,” or the things that gave Faulkner ideas for writing his novels, and his novels are most famously about the American South, especially the American South during the first half of the twentieth century.
Faulkner was interested in writing from an early age, when he was very young. His mother and grandmother taught him how paint and draw. By the time he was 12, he was already writing poetry. Although he loved reading and writing, he did not love school. He found school boring and eventually dropped out. “To drop (drop) out” is a phrasal verb meaning to stop going to school. We talk about people “dropping out of high school.” We’re talking about young kids, boys and girls who don’t finish their high school degree. In the U.S. nowadays, it’s required that you go to school until the age of 16 in most states, but it isn’t required that you graduate from high school, although most people do.
Faulkner did not graduate from high school. Instead, he continued to write on his own. He fell in love with a girl and was very disappointed when the girl decided to marry another man. Faulkner was so disappointed by this that he eventually moved out of Mississippi with a friend of the family and moved to Connecticut. Connecticut is a state in the northeastern part of the United States, very far from Mississippi. There, Faulkner started to write more poetry, and eventually, when World War I broke out – when World War I started – Faulkner decided that he wanted to join the effort.
However, the United States military rejected Faulkner. They said, “No, you can’t be a soldier because you’re too short.” He was only five feet, six inches, which is about 1.7 meters tall. So instead, Faulkner went to Canada, and he tried to join the British Royal Air Force by training in Canada. One of the things that Faulkner did to get accepted by the British Royal Air Force was change the spelling of his last name. We spell his last name (Faulkner), but the original spelling did not have a “u” in it. Faulkner thought that putting a “u” in it would make it sound more British, and so he changed his name.
However, the war ended before Faulkner was ever sent to Europe. He instead returned to his home state of Mississippi and went to the University of Mississippi. He, once again, was bored by school. He wasn’t a very good student. He stayed only three semesters at the university. A semester at an American university is usually around 15 weeks. There’s typically two main semesters, one in the fall and one in the spring, although many colleges and universities have summer semesters which are often shorter in terms of the number of weeks. In any case, Faulkner dropped out, this time, of college because he was bored.
He worked in a couple of different jobs. He even moved to New York City briefly. Finally, in 1924, he published his first book of poetry. It was called The Marble Faun, and it was not very successful, but it sold about a thousand copies – about a thousand books were sold. Then, the following year, in 1925, he published his first novel. This was called Soldiers’ Pay. A “soldier” (solider) is someone who fights in an army or in the military. After the book was published, Faulkner did what a lot of young writers were doing in the early part of the twentieth century – he went to Paris. He went to France and lived outside of Paris, continuing his writing.
However, one of Faulkner’s friends, another famous author, told Faulkner he should come back to the United States and write about what he knew. He should write about Mississippi. He should write about the American South. That writer’s name is Sherwood Anderson, who, as I said, was also a famous writer during his own lifetime.
Over the next 30 years, Faulkner took Anderson’s advice and wrote about the South. In particular, he wrote about social issues that were important at that time, including racism – the discrimination against someone because of the color of their skin. He also wrote about what we might call the “Southern aristocracy.” “Aristocracy” (aristocracy) refers usually to very wealthy people. “Southern aristocracy” would be the wealthy families in the south, almost all of which were, of course, white families.
Faulkner, in some of his books, created a fictional county – a place that wasn’t real, but was based on or was taken from his experiences in the towns that he did live in, in Mississippi. Many readers and critics said that Faulkner’s books did a wonderful job of really capturing or conveying or communicating the language of the way people talked in the South in those small communities during this time period. Faulkner’s first really famous book was called The Sound and the Fury, which was published in 1929. This was one of the first very successful novels that Faulkner wrote.
I said it was published in 1929. Faulkner also married in 1929. Who did he marry? He married the same girl who he was in love with more than 10 years earlier, but who had married another man. That woman divorced her first husband and married Faulkner, who had always loved her. Faulkner continued to publish novels, including Sanctuary, The Story of Temple Drake, Absalom, Absalom! and, in the late 1940s, Intruder in the Dust.
Many of the themes or topics that these novels treated or discussed were rather controversial. When we say something is “controversial” (controversial), we mean that many people disagreed about them. People would often argue and fight about these topics, especially topics related to race. Nevertheless, Faulkner became a successful novelist. He also wrote for the movies. He wrote scripts for movies. He didn’t really want to – he didn’t like writing for the movies – but he wanted the money, and so he wrote what are called “screenplays,” which are basically the scripts of movies.
Although Faulkner wrote about the South and its, in many ways, conservative ways, his writing was very modern. His style of writing was considered very modern. He used, in some of his novels, what is called “stream of consciousness” – a technique that involves a single character in the book talking for a very long time, and what is essentially a monologue – where one person is talking. “Stream of consciousness” writing often includes very long sentences. It’s almost as though the person isn’t planning in advance what they are going to say. They’re simply saying what is occurring to them at that moment – at least, that’s the impression people have when they read novels that are written in this style. Faulkner used this technique in some of his own books.
In the late 1940s, there were a couple of collections of Faulkner’s stories that were published. These collections made Faulkner’s writing more well known, especially in Europe. He was awarded the 1949 Nobel Prize in Literature, one of the most prestigious and highly sought after prizes, one might say, in the world of literature – of writing. After he won the Nobel, he continued to win other awards for his writing. He continued to write in the 1950s, but he also had some difficulties in his personal life.
He had a daughter, born in 1933, who lived to be an adult, but Faulkner wasn’t exactly the greatest father in the world. He drank too much. He had romantic relationships outside of his marriage and probably would not win any awards for his family life. However, he continued to write, and in 1962, in July, he died of a heart attack. Nowadays, when people think of William Faulkner, they definitely think of him as being perhaps the most important, one of the most important authors in the United States in the twentieth century writing about this area called the South.
Our next topic is going to be about a popular competition, usually among children, although some adults also engage in this competition. It’s called “soap box derbies.” A “soap (soap) box” is a large wooden box that used to be used in the early twentieth century for shipping, or transporting, soap. Well, soap boxes are very strong, and somehow, probably some children got the idea that you could make a little car out of the box. If you put wheels on this wooden box and you put the box at the top of a hill, the car would go down the hill and you would have basically a little car without a motor, without an engine.
The word “derby” (derby) is basically a race, and the “soap box derby” became popular in the state of Ohio in the early 1930s. Specifically, in the city of Dayton, Ohio, there was a photographer for the local newspaper who saw some boys racing their homemade soap box cars down a hill. He took pictures of the boys and decided that he would have a competition – a race to see which one was the fastest. Nineteen boys participated in that first race. It was so successful that this photographer decided to ask his newspaper to give some money to help pay for this race, this competition.
The verb we would use here would be “sponsor” (sponsor). “To sponsor” something is to pay for something, to pay for the expenses of some, in this case, event. In August of 1933, the competition became so popular that more than 300 children showed up to compete in the race, and there were estimated to be about 40,000 people watching the race. So, it became a very popular event. Soon, newspapers in other cities learned about this story, and they started sponsoring their own soap box derbies. Finally, it was decided that there would be a national competition of these children racing in their soap boxes.
So, in 1934, in the city of Dayton, there was the first All-American Soap Box Derby. Children from 34 different states showed up with their soap box cars to compete in this competition. The next year, the race moved to another city in Ohio – Akron, Ohio – and more importantly, the newspaper photographer who had started the soap box derbies, a man by the name of Scott, got a major car company, Chevrolet, to sponsor the race.
This brought even more attention to the concept of a soap box derby, and so it was decided, in 1936, that the derby should have its own place, its own location. They were going to build a track for the derby. A “track” (track) is usually a circular road that cars or horses or people run around in a race. They got the national government, actually, to pay for the construction of the track. It was built by a program called the Works Progress Administration, more popularly known as the WPA.
You’ll remember that in the late 1920s, there was a stock market crash in the United States where the value of stocks of many companies went down sharply – a lot. This was one of the things that led to a period called the “Great Depression” in the 1930s, where the economy was in a very bad way. President Roosevelt created the WPA to try to create jobs, government jobs, for people, and one of the things the WPA did was build community centers and libraries and things like this racetrack. The racetrack was called Derby Downs and was completed in 1936. Ever since then, the All-American Derby is held, or takes place, at Derby Downs.
Only boys competed in the competition for many years. However, in the 1970s, girls started to build their own soap boxes and began competing as well. In fact, in 1975, Karen Stead became the first girl to win the All-American Soap Box Derby. The cars are no longer made out of soap boxes, however. They have become much more sophisticated. Many of the cars are made out of fiberglass. “Fiberglass” is a special kind of plastic, but very light and very strong.
Although no longer as popular as it was during the middle twentieth century when I was growing up, the soapbox derbies continue today. In the year 2012, for example, there were more than 500 children who competed in the soap box derby. These children came from more than 40 different states and five different countries. So it continues to be a tradition, although not a popular one, or at least as popular as it was a few years ago.
I have to mention that when I was growing up in the 1970s, we didn’t have a soap box derby, but we did have something called the “pinewood derby.” The pinewood derby was invented in the early 1950s here in Southern California by a man whose son was too young to compete in the soap box derby, but he wanted his son to be able to have the same excitement of racing, and so he created a race where young boys would take a piece of wood and they would carve the wood – they would shape the wood into the form of a car and put wheels on it – and then race the cars down a track, down a hill.
The first races were actually organized by the local Cub Scouts. “Cub Scouts” are basically young Boy Scouts, young boys who are involved in the Scouting movement, who do crafts and games and learn about all sorts of different things. I was in the Cub Scouts in the 1970s, and we had a pinewood derby at our school where we had our Cub Scout group. I didn’t win, however. I lost, and that was pretty much the end of my racing career.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Felipe (Felipe) in Brazil. Felipe wants to know the difference between the words “deceive,” “cheat,” and “lie.” To deceive” (deceive) means to make someone believe something that isn’t true in order for you to get some sort of advantage. So, you’re not just telling someone something that isn’t true just for fun. You’re doing it usually so that you can get some advantage over that person or in a certain situation. The noun from “deceive” is “deception.” “Deception” is when you are led to believe, when someone makes you believe, something that isn’t true.
“To cheat” (cheat) means to act in a dishonest way. It’s a much more general word that would describe doing things that are dishonest, for example, in school or in your business. You could talk about someone “cheating” on his income taxes – not telling the government all the money that he’s made. So, “cheat” is to act in a dishonest way, usually to get, once again, some advantage. You can cheat, but other people might discover your cheating. When you “deceive” someone, the other person doesn’t know that you are being dishonest.
“To lie” (lie) means to say something that is false, to say something that is not true. “Cheating” and “lying” are things that you do to someone else, but the other person doesn’t necessarily have to believe you. When you “deceive” another person, you are, in effect, successfully lying. You are getting that person to believe you. If you say, “He lied and cheated,” people may or may not have believed his lies or understood that he was cheating. We don’t really know. When you “deceive” someone, however, you definitely do know.
“To deceive” can also refer to actions that you take in order to get someone to believe something that isn’t true. “Lying” is almost always verbal. If I lie, I’m saying something to you or writing something to you. “Deceiving” could be done verbally or it could be done by your actions. It could be done with words or acts. So, Felipe, don’t lie, don’t cheat, and don’t deceive anyone.
Chris (Chris) – now in Australia, originally from Korea – wants to know the meaning of the verb “to appreciate.” “To appreciate” (appreciate) means a couple of different things. The most common meaning of “to appreciate” is to be grateful for something, to thank someone for something they have done for you. “I appreciate you coming today” – I am thankful to you for coming today. “Appreciate” can also mean to understand a situation. “Do you appreciate my difficulty?” means “Do you really understand, fully and completely, my situation?”
A third meaning of “appreciate” is for something to go up in value – to become something that is worth more money, basically. We talk about houses “appreciating,” houses becoming worth more and more money. That doesn’t always happen, however. Sometimes, houses don’t appreciate; they lose their value. But many people believe that if they buy a house, it will in the future “appreciate” in value – it will increase in value.
We also use “appreciate” to make a request of someone. It’s a polite way of asking someone to do something, although you have to be careful with whom you use this particular expression. It’s often used for people who are below you in authority or below you in power. “I’d appreciate it if you would do this favor for me,” or “I would appreciate you going to the store for me.” Those are both somewhat formal ways of telling someone what to do. So, even though you’re using the word “appreciate,” it is almost as though you are commanding them to do that.
There are other ways that you can ask someone to do you a favor without using the verb “appreciate” and without sounding as though you were giving them a command. You can say, “Could you please?” “Could you please turn down your music? It’s too loud.” “Would it be possible for you to turn down your music before I hit you in the face?” That would be a nice way of saying that.
Finally, Kayo (Kayo) in Japan wants to know the meaning of an expression, “to go green.” “Green,” you already know, is a color. However, “green” has become associated with the general cause or movement of environmentalism – of trying to not waste energy or do anything that would harm or hurt our natural environment. When people use this phrase “go green,” they mean to become more conscious of the environment and to do things that would not damage the environment – that would help the environment.
So, for example, you might say, “I’m not going to take my car to work today. I’m going to bike to work” – I’m going to use my bicycle – “I’m trying to go green.” I’m trying to be more helpful to our natural environment by not driving my car. I, of course, don’t have a bike, so I can’t do that. But if I did, I would go green.
If you have a comment or question you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
inspriation – something that makes you want to do something else or gives you ideas to do something else
* John Lennon’s son, Sean, was the inspiration for the song, “Beautiful Boy.”
to drop out – to stop going to school before finishing one’s program or getting one’s degree
* Mateo dropped out of school when his father got sick so that he could work and take care of his family.
semester – half of a school year, typically four to four and a half months
* In the fall semester, students take exams before leaving for the winter vacation.
aristocracy – society’s wealthy class of people; the group of people who have the highest social position and the most money in society
* Many of the aristocracy in England have titles like duke or earl.
fictional – created in someone’s imagination; not real
* The characters in most movies are fictional and not based on real people.
theme – the main topic talked about in a book, movie, or play
* Testing one’s courage is a theme in many movies and books.
controversial – causing argument or disagreement among people
* The death penalty is a controversial topic where many people have very strong opinions about whether it is a fair or unfair punishment.
manuscript – a handwritten book, document, or script; a written version of a book before it is published
* Shakespeare’s original manuscripts are difficult to read, both because of his handwriting and because of how the pen ink has faded over time.
derby – a race that is open to anyone who wants to compete
* The horse that won the derby had never competed in a race before.
fiberglass – a very strong and lightweight plastic that is made with very thin pieces of glass
* Many boats used for rowing are now made of fiberglass, making them easier to carry and control in the water.
sponsor – a person or company who gives money or goods to pay for or support an event
* In return for being a sponsor of the Olympics, McDonalds got to put their name on signs all over the sports stadiums.
track – a circular road that people, cars, or animals move around in a race
* The cars drive around the track 500 times during the Indianapolis 500 car race.
stock market crash – a short period of time when many or most companies traded on the stock market lose a large amount of their value
* Many people lost a lot of money in the stock market crash of 1989, which occurred on just one afternoon.
to deceive – to make someone believe that something is true or not true, in order to gain an advantage
* No one was deceived by the amateur magician’s magic tricks.
to cheat – to act in a dishonest way in order to gain something
* Alan cheated on the math test, but still got a low score.
to lie – to say something that is false or not true
* Mom always knows when we’re lying, so it’s better just to tell the truth.
to appreciate – to be grateful for something; to fully recognize the full worth or value of something; to understand the situation fully
* We both really appreciated you helping us move this weekend.
to go green – to do things to protect the environment; to do things that do not damage the environment
* This store has gone green and do not use plastic bags and do not print out paper receipts.
What Insiders Know
The Underwood Typewriter Company
Before the use of computers, people typed their documents using typewriters. “Typewriters” were devices that had keys on it – the alphabet, numbers, and special characters – that produced print on paper. For many years in the U.S., one company was famous for producing these typewriters: The Underwood Typewriter Company. It was based in New York City and was considered to be the first to produce the modern typewriter.
A German American man named Franz Xaver Wagner created the first Underwood typewriter. Wagner then showed his “invention” (creation) to John Thomas Underwood, a businessman. Underwood was very interested in Wagner’s invention and decided to support Wagner. The first and second Underwood typewriters ever to be made – named Underwood No. 1 and Underwood No. 2 – were made between 1896 and 1900. However, it wasn’t until 1900, when the Underwood No. 5 was created, that people referred to it as the first truly modern typewriter.
Many writers of the early 1900’s created much of their work using Underwood typewriters, including William Faulkner. Faulkner owned an Underwood Universal Typewriter, which is now displayed at a museum at the University of Mississippi.
The Underwood No. 5 was so popular that two million had been sold by the early 1920’s. In fact, during the company’s “heyday” (period of greatest popularity), their factory produced one typewriter per minute. Before the start of World War II, as part of a promotion, The Underwood Typewriter Company built the world’s largest typewriter, attracting large crowds to see it in Atlantic City, New Jersey. However, when the war “broke out” (began), it was destroyed and turned into “scrap metal” (metal or material used to make other things).
Olivetti, another typewriter manufacturer, bought Underwood in 1959. The last time that the Underwood name appeared on one of its typewriters was on a typewriter produced in the 1980’s in Spain.