= 1752
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 447.
This is English as a Second Language Podcast’s English Café episode 447. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com and become a member of ESL Podcast. If you do, you can download a Learning Guide for this episode.
Today we’re going to talk about one of the great popular composers in American history, a man whose work almost every American knows even today: Mr. John Philip Sousa. We’ll also talk about a 1950s celebrity magazine named Confidential, and a famous 1957 court case that it was involved in. And, as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café talking about a man named John Philip Sousa. Sousa was an American musician and composer. “Composer” (composer) is a person who writes the music for a song.
Sousa was born on November 6th, 1854, in Washington, D.C., the capital of the U.S. His father, Antonio, was a member of the U.S. Marine Band. The U.S. Marine Band is an organization of musicians that plays music for the president of the United States and the commandant, or leader, of the Marine Corps. The Marine Corps is one of the five branches, or parts, of the U.S. military. The other four are the Army, Navy, Air Force, and Coast Guard. The Marine Band was created way back in 1798 and has played music for each U.S. president since then.
As he grew up, Sousa’s house was full of music – specifically, military band music, because of his father’s job as a musician for the Marine Band. When Sousa was six years old, he began studying music himself. He studied voice, or singing, and a number of instruments including violin, piano, and flute. When he was 13 years old, Sousa’s father enlisted, or signed him up, to join the Marine Band as what we would call an apprentice. An “apprentice” (apprentice) is a person who learns how to do a job by watching someone else do it, often for many years.
Sousa eventually himself became the bandmaster, or leader of the band, of the Marine Band. He led the band, or conducted it, for 12 years, from 1880 to 1892. “To conduct (conduct) a band” is to lead a band, to coordinate all the different instruments in playing complex or complicated musical pieces. Before becoming bandmaster, however, Sousa in 1879 married Jane Middlesworth Bellis.
Under Sousa’s direction, the Marine Band changed from being a very good band into one that was known all around the world as one of the best bands, especially of the kind of music that it played. Because of this reputation for excellence, the Columbia Phonograph Company asked the band to be the first military band to be recorded. “Phonographs” (phonographs) were an early type of music player where music could be recorded and listened to later. In 1890, 60 recordings of the Marine Band were made available for people to buy. They were so popular that by 1897, over 400 songs became available.
Sousa wrote many of the songs that the Marine band played. He composed many different kinds of music, but is most famous for his military marches. “Marches” (marches) are pieces of music that have a strong and repetitive rhythm that were originally used to help members of the military walk together as a group. That repetitive, strong rhythm helped the soldiers to walk together in a coordinated way. Some of the marches are serious and slow, but Sousa’s marches – especially his most famous ones – are very quick and have a very happy feel to them.
Throughout his life and career, Sousa wrote over 300 pieces of music, and of those 300, 136 were these military marches. The two most famous military marches Sousa wrote, or Sousa composed, were “Semper Fidelis” and “Stars and Stripes Forever.” Sousa wrote “Semper Fidelis” in 1888. He dedicated the composition to the men and women of the Marine Corps. “To dedicate” (dedicate) a song, or a book, or other artistic production or activity to someone means to do it in memory of them, to honor that person. The “Semper Fidelis” march later became the official, or approved, march of the Marine Corps.
In 1892, Sousa left the Marine Band to conduct his own non-military band, called – what else? – The Sousa Band. A few years later, he composed “Stars and Stripes Forever.” In 1896, Sousa and his wife were coming back to the United States from a long vacation in Europe. Souza says he missed the United States when he was away from it, and he decided to write “Stars and Stripes Forever” when he remembered the flag of the United States flying over the White House.
He thought of that image and was, we might say, “inspired” by that image. “To be inspired (inspired) by” something is to have a strong emotion that makes you want to do something because of something else – in this case, because of the memory that he had of the flag flying over the White House. The White House is where the president of the United States lives in Washington, D.C.
“Stars and Stripes” is a nickname, or informal name, for the American flag, because the American flag has both stars (50 of them) and stripes (13 of them). “Stripes” are horizontal lines that go from one side of the flag to the other. They are red and white, and the stars are against a blue background – the stars themselves are white. So, “Stars and Stripes Forever” refers to the American flag.
“Stars and Stripes Forever” is certainly the most famous of Sousa’s compositions, and it’s one that every American is familiar with, especially any American who has ever gone to a Fourth of July, or Independence Day, celebration. It’s the song that you will always hear on the Fourth of July, our national day of celebration for our independence. You’ll hear it especially during the fireworks displays, when they shoot up the fireworks into the sky. Let’s listen really briefly to this.
It’s, you’ll see, very much in the spirit of a military march. It has a very strong rhythm, but it’s a very happy song. There are no words to the song for me to sing, but I think once you listen to the song, if you’ve never heard it before, you’ll understand what I mean by a “military march” – the kind of music this is, as well as the kind of music that Sousa is famous for – this very, what we might call, “upbeat” type of music, a very happy, joyous feeling in his music.
[music from “Stars and Stripes Forever”]
There are several famous parts, or passages, of this composition that Americans would instantly or immediately recognize if you played it to them. There’s just one more little part of this song that, again, is one that is very familiar to the average American. Let’s listen.
[music from “Stars and Stripes Forever”]
If you listen during that section, you can actually hear what’s called a “piccolo.” A “piccolo” (piccolo) is a small flute, but it’s a very high-pitched instrument. The notes are very high, and even though it’s just one instrument, because the notes are so high, you can hear them above the other loud music playing during that passage or part of the composition.
Sousa and his band continued to tour, or travel around and perform, for many years. In fact, he toured around the world until 1931, when he finally retired, or stopped working. During this time, Sousa was also famous for trying to put a lot of effort into supporting music education for children. He occasionally returned to the Marine Band to be the conductor. One of his last public performances before his death was with the Marine Band at a yearly military ceremony. Sousa died of a heart attack in 1932 at the age of 77.
Today, Sousa’s music is certainly still familiar to Americans. He was honored after his death by having a bridge in Washington D.C. named after him, as well as a ship in World War II. In 1976, Sousa was added to the Hall of Fame of Great Americans at the John F. Kennedy Center for Performing Arts in Washington, D.C., and in 1987, his march “Stars and Stripes Forever” became the official march of the United States. This and many other of his marches are heard, as I mentioned earlier, on national holidays such as the Fourth of July.
You can search for “Stars and Stripes Forever” on YouTube or on the Internet, and I’m sure you can hear other recordings. It’s a short march, but as I say, it’s quite well-known by Americans.
Our next topic is perhaps less well-known nowadays by Americans, but was certainly something that people in the late 1950s knew about here in the U.S., and that is a magazine by the name of Confidential and something called the Criminal Libel Suit of 1957. “Libel” (libel) is published information that is not true and that can hurt someone by making other people think badly of that person. Libel is basically lies that you tell about someone that are printed in a newspaper or magazine, or somehow published. Nowadays, it would be on the Internet.
“Slander” (slander) is the same idea: a lie about someone that hurts their reputation, but it’s oral – it’s spoken. So, “libel” is printed. “Slander” is spoken. Both things are called “defamation” (defamation). “Defamation” is the general term we use for this idea of telling lies about someone in such a way that damages, or hurts, their reputation. We have an expression, “defamation of character.” Your “character” is, in this case, your reputation – who you are, who people think you are in terms of whether you’re a good person or a bad person, for example.
Different countries have different laws about defamation. In some countries, such as in Great Britain, these laws can be very strict. They can be very limiting. It is easy to sue someone, “to take someone to court,” we would say, in certain countries over defamation. In the United States, the laws are much looser, much less strict. So, it’s more difficult for you to accuse someone of telling lies about you in the U.S. Confidential was a magazine in the 1950s that printed stories about Hollywood celebrities – that is, famous actors, writers, directors, musicians, podcasters, and so forth. Well, not podcasters.
The word “confidential” (confidential) means secret, something that you’re not supposed to tell other people. Of course, people love to read about celebrities and secrets about celebrities, and that’s what Confidential magazine published. The Criminal Libel Suit of 1957 was a lawsuit against Confidential magazine that said that many of these stories were not true and were hurtful to celebrities’ reputations.
The publisher – the person who produced the magazine – was a man named Robert Harrison. Harrison founded Confidential magazine in 1952. Before this, none of his magazines were doing well. So, he decided to start a new magazine that printed stories about celebrities, because everyone loves to buy magazines with stories about celebrities. The stories in the magazine focused on the most popular celebrities at that time. The stories talked about their love lives and personal relationships. The stories also talked about celebrities doing certain things that perhaps they should not have been doing.
Some of the celebrities that were mentioned in Confidential magazine were, as I said, among the best known of this period, including Frank Sinatra, Marilyn Monroe, Clark Gable, Grace Kelly, and Humphrey Bogart. These topics that were covered in Confidential magazine were extremely sensational. Something that is “sensational” (sensational) is something that causes a lot of public interest. The magazine quickly became very popular with readers. In 1956, it sold more than 5 million copies around the country.
Confidential’s legal problems began in 1955. The head of the United States Post Office said that the magazine could not be delivered to people’s homes because it broke the laws against obscenity. “Obscenity” (obscenity) is something that is considered very crude, something usually involving bad language or, most often, sexual matters. Harrison fought the Post Office in court. He said no, what they were doing was not obscene, it was not obscenity, and he won against the Post Office. The Post Office was not able to stop him from mailing his magazine to people throughout the United States.
Shortly after that lawsuit, a California attorney filed private lawsuits for libel against the magazine. These lawsuits were filed by many of the celebrities about whom the magazine had written stories. Finally, in 1957, the state attorney general of California, a man named Edmund Brown, took legal action against Confidential. (Interesting side note here: Edmund Brown later became a very popular governor in California, and his son, Jerry Brown, has been governor of California twice.)
In May of 1957, several people associated with Confidential magazine were indicted. “To be indicted” (indicted) is to be accused of a serious crime; in this case, the crime was a conspiracy, a secret agreement among people, to do something illegal – in this case, to publish things in the magazine that were not true about the celebrities. Now, unfortunately for Attorney General Brown, many of the people who were indicted in this criminal libel suit did not live in California.
Normally, if someone commits a crime and then goes to another state, the state can ask this other state to return this person – to arrest them and return them – to the state where they committed the crime. So, if you break the law in California and then you fly to New York, the police in California can ask the police in New York to return that person. That process is known as “extradition.” It comes from the verb “to extradite” (extradite), which means to force someone to leave a state – or more commonly, a country – and return to a place where they are being accused of a crime.
New York was the place where many of the people who published and were associated with Confidential magazine lived, but the state of New York, somewhat unusually, said they would not extradite these people. So, only a couple of people who were indicted were actually “tried” in California – had to go to a courtroom before a judge. The lawyers defending the members of Confidential magazine subpoenaed many of the celebrities to get them to come and testify at the trial. “To subpoena” (subpoena) means to require someone to go to the courthouse, to go before the judge and give evidence or talk about what they know about this crime.
Interestingly enough, many of the celebrities who were subpoenaed left the country themselves so they didn’t have to go to trial, which makes one wonder who is really telling the truth here. The jury in the case, the group of people who decide whether someone is guilty or innocent, could not come to an agreement. They couldn’t agree amongst themselves, and so you had what was called a “mistrial” (mistrial). A “mistrial” is when the jury can’t agree on a decision on what is called the “verdict” (verdict).
After the mistrial was declared, the publisher, Harrison, and others who were indicted in this case decided to pay some money, to pay a fine, to the government for what they had done and to stop publishing these, apparently, lies about celebrities. Of course, the magazine did not survive. Nobody wanted to buy a magazine that told the truth about celebrities. And so, in 1958, the magazine was sold, and no one was interested in buying it anymore.
Now let’s answer some of the questions you have sent to us.
We have time for a couple of quick questions today. The first one is from Amer (Amer) in Jordan. Amer wants to know the meanings of the words “developer,” “programmer,” and “coder.” All three words are typically used to describe someone who does what is called “computer programming” – who writes software that works on some kind of computer. “Software” is basically a series of instructions that you give the computer, and these instructions are written in what is called “code” (code). That’s why we have these different names that mean basically the same thing.
A “programmer” is a person who writes computer software. A “coder” is a person who writes computer software. Usually, we don’t distinguish between those two terms. A “developer” can also be someone who writes computer software. Normally, the word “developer” is used to describe the person who is sort of in charge of different parts of a software development process. A developer could be someone who is in charge of, say, writing a new app for your mobile phone. The developer might hire other people – might get other programmers or coders to do the actual work. In most cases, you can use all three of these words interchangeably, one for the other.
Our final question comes Mojtaba (Mojtaba) in Iran. The question has to do with how you might describe someone whom you trust, someone who has a character that you like and want to imitate. There are a couple of different adjectives we might use in English to describe this kind of person. One of them is “upstanding.” “Upstanding” (upstanding) means honest, respectable. It’s a somewhat old-fashioned word that is used to describe someone who is a very honest person, who never lies, who doesn’t cheat.
A word with a similar meaning is “honorable” (honorable). Someone who’s “honorable” is someone who is trustworthy, someone who tells the truth, even sometimes when it’s difficult to do that – even though that person might be harmed by telling the truth. They do the right thing. They do the honorable thing.
“Principled” is a third word we might use in this situation. Someone who is “principled” (principled) is someone who has principles. “Principles” are standards of judgment, standards of conduct, rules that you follow. Someone who has principles is someone who won’t do something that is wrong, who will be honest – who will try, once again, to do the right thing. That’s why it’s also an adjective we might use to describe someone that we find honest and we trust.
If you have a question or comment, you can trust us to try to answer it. Our email address is eslpod@eslpod.com. Please be aware that we get lots of questions every week, and sometimes it takes a long time for us to answer them because we do get so many questions, but we’ll do our best.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2014 by the Center for Educational Development.
Glossary
composer – a person who writes a song’s music or music and words
* Mozart was a composer who wrote many types of music, including operas.
to conduct – to lead a group of musicians, such as an orchestra, band, or choir
* The man stood at the front of the orchestra, raised his baton, and began conducting the musicians as they played a Beethoven symphony.
march – a piece of music that has a strong and repetitive rhythm that was originally used to help members of the military walk together as a group
* Bands often play marches in parades as they walk together in front of crowds.
to dedicate – to write something in memory or honor of an event, date, or person
* Cal dedicated his song to his mother, who had recently died.
official – approved by a person in charge of an organization or government office or department
* A passport is an official document and can be used to cross borders.
to be inspire by – to be overcome with an emotion that causes a person to want to do something
* Joann was inspired by watching the runners in the marathon and decided to try to run a marathon herself.
libel – published information that is not true that can hurt someone by making other people think badly of that person
* Brad accused the newspaper of libel when it reported that he drove home from the party drunk.
obscenity – something spoken or written that is very hurtful or rude, usually involving bad language or sexual matters
* The movie was rated “R” because it contained some obscenities that were not appropriate for children.
to indict – to charge with a crime; to formally accuse someone of a crime
* The football player was indicted on charges of murder.
to extradite – to force someone to leave a country or state and return to another country or state where that person has been accused of a crime
* The United States asked Sweden to extradite an American couple accused of spying on the government.
to subpoena – to have the court demand that a person come and speak about their experiences related to a court case
* The judge subpoenaed a witness who had been at the scene of the robbery.
mistrial – a trial where the jury cannot agree on a decision
* Seven of the jurors believe the defendant is guilty and five believe he is innocent so a mistrial will be declared.
developer – a person working on the different parts of the software development process
* Several developers are working on programs that will work with our new line of computers.
programmer – a person who writes computer software, the programs that allow a computer to do different types of work
* A good programmer has good technical skills, but also understands the basics of design.
coder – a person who writes computer codes, the system of numbers and symbols that is put together to allow a computer program to work
* We need an expert coder to fix this program, allowing people to submit their work without getting errors.
upstanding – honest and respectable
* The mayor appointed three upstanding citizens to serve on this committee.
honorable – bringing or deserving a high level of respect
* Yi did an honorable thing by telling others what really happened, even though she might get into a lot of trouble.
principled – behaving in a way that is consistent with what one believes is right and wrong
* We want the lawyers we train to be skilled, but also principled.
What Insiders Know
United Service Organizations (USO)
In any organization, morale is important. “Morale” refers to how happy, confident, and satisfied someone is at a particular time, especially in their job. The United Service Organizations (USO) is a “nonprofit” (not existing to make money) organization that works “to boost” (to raise) the morale of people working in the U.S. “military” (the part of the government involved in security and fighting wars), especially “troops” (soldiers) serving or working “overseas” (out of the country).
The USO was “founded” (created) in 1941 when the president at the time – President Franklin D. Roosevelt – asked for help to boost the morale of those in the military. During World War II, the USO began a “tradition of” (activity that continued after that time) entertaining the troops, and continues to this day, especially with its “Camp Shows,” which featured live performances from famous people in the entertainment business. Many famous celebrities have performed on military “bases” (the center of operations or headquarters for the military) in the U.S., as well as overseas, sometimes even placing their own lives in danger, by performing under “hazardous” (risky; dangerous) conditions.
From 1941 to 1947, the USO featured “notable” (famous and important) performers. They included Bing Crosby, Bette Davis, Frank Sinatra, Gary Cooper, Fred Astaire, and Lucille Ball.
The USO was temporarily “disbanded” (for an organization to no longer exist or operate) after World War II, but when the U.S. entered the Korean War in 1950, government leaders requested that the USO be “reactivated” (return to its work after it had stopped for a time). Between 1952 and 1953, many celebrities or stars performed in Korea, including Bob Hope, Marilyn Monroe, Jane Russell, and Mickey Rooney.
Today, the USO continues its work. It has over 160 locations around the world in 14 countries and continues its work to boost morale and to entertain American troops.