= 0634
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast episode 634: Resembling One’s Parents.
This is English as a Second Language Podcast episode 634. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Consider supporting this podcast by becoming a member. If you do, you will learn English faster – and live a longer life!
This episode is a dialogue about how people look like their parents – seems pretty obvious. But, we’ll be using some phrases and expressions related to your family and looking like members of your family. Let’s get started.
[start of dialogue]
Khaled: Hi, what are you looking at?
Susanna: Your photo albums. Your roommate let me in and said I could make myself comfortable while I waited for you.
Khaled: There are some really incriminating pictures in there. You’d better give those back to me.
Susanna: Not yet! I’m looking at your baby pictures and your family portraits. You’re the spitting image of your mother.
Khaled: That’s not my mother. That was our neighbor.
Susanna: Oh, now that I look a little closer, I can see that you resemble your father. You’re a chip off the old block.
Khaled: That’s not my father. That’s my father’s friend. Now, why don’t I take those…
Susanna: Wait! These candids of your birthday parties are so cute! You were so adorable!
Khaled: Right. When I was a kid, I had a face only a mother could love.
Susanna: That’s not true! You have a great profile. I’d expect to see your likeness in paintings and on statues.
Khaled: Okay, enough with the brown-nosing. What do you really want?
Susanna: I don’t want anything…okay, just one little thing. My cousin is in town. I want to go out with Rick tonight and I thought we could double date. Me, Rick, my cousin…and you. What do you say?
Khaled: I knew it had to be something. Does she look like you?
Susanna: We are like two peas in a pod.
Khaled: Then, forget it!
Susanna: Hmph!
[end of dialogue]
Our dialogue opens with Khaled saying, “Hi, what are you looking at?” Susanna says, “Your photo albums.” A “photo (or photography) album” (album) is a book you use to keep your photographs in; usually they have plastic that you put over the photographs to protect them. Susanna says, “Your roommate let me in and said I could make myself comfortable while I waited for you.” “Your roommate” would be the person that Khaled lives with. He let Susanna in, meaning he opened the door and said, “Sure, come in,” and probably left. The roommate said that Susanna could make herself comfortable, meaning could sit down, could relax while she waited for Khaled.
Khaled says, “There are some really incriminating pictures in there.” “Incriminating,” literally, is when you are made to look guilty of something. If you come out of a room and there is blood on your hands and you have a gun in your pocket and someone has been killed in the next room, the gun and the blood are incriminating; they show that you did something wrong. In this case, however, Khaled means that the pictures are embarrassing, that they are ones that he does not want other people to see. He says, “You’d better give those back to me,” meaning I want them back now.
Susanna says, “Not yet! I’m looking at your baby pictures and your family portraits.” “Baby pictures” are, of course, photographs of a very young child, usually less than one year old. Many of us have baby pictures; I have a baby picture, that was the first picture my parents took of me back in 1963. They took another photograph again in 1973, and there aren’t very many photographs in between those 10 years. But I have one picture: my baby picture. Do I look cute? I won’t tell you! “Family portraits” are when your whole family gets together and they take a picture of your whole family together. This we did a couple of times when I was growing up. Unfortunately, there weren’t cameras big enough to take a picture of I and my 10 brothers and sisters!
Anyway, Susanna says to Khaled, “You’re the spitting image of your mother.” When someone says you’re the “spitting (spitting) image of (someone)” that means that you look almost exactly like that person. The other day I was at the coffee shop, someone came up to me and said, “You are these spitting image of Brad Pitt,” and I said, “No, George Clooney, not Brad Pitt!” Actually, I’m the spitting image of Chewbacca from Star Wars! By the way, the verb “to spit” usually means that you take some liquid from your mouth and you use your mouth to put it onto something else. That’s to spit. Why we say “spitting image” I’m not exactly sure.
Khaled responds to Susanna, “That’s not my mother,” meaning the picture that she’s looking at is not a picture Khaled’s mother. He says, “That was our neighbor,” who could have been your mother – you don’t know, really! Susanna says, “Oh, now that I look a little closer, I can see that you resemble your father.” “To resemble (someone)” means to look like someone: “My neighbor resembles his dog.” Susanna says, “You’re a chip off the old block.” This is an old expression; “a chip off the old block” means that you are very similar to your parents, either by the way you look or by what you do – by your actions. If your father was a good football player, and you’re a good football player, someone might say, “You’re a chip off the old block.”
Khaled says, “That’s not my father. That’s my father’s friend. Now, why don’t I take those…” Susanna says, “Wait! These candids of your birthday parties are so cute!” A “candid” picture or photograph is something that is taken without you, typically, realizing it. Someone is taking a picture of you reading or a picture of you talking and you don’t know that they are taking a picture of you, that would be a candid picture. “Candid” has a number of different meanings, some of which are found in the Learning Guide. Susanna thinks these pictures of Khaled’s birthday parties when he was younger are “cute,” meaning they’re nice to look at, attractive, pretty. We often use this word – this adjective to describe young children or small animals – or the children of small animals, or the animals of small children! All of these could be described as cute – except my neighbors’ dog, of course! Susanna then says, “You were so adorable!” “Adorable” is like “cute,” it means very pretty, very attractive to you.
Khaled says, “Right,” meaning wrong. He uses the word sarcastically: “Oh, yeah. Right!” It depends on the way it is said. Here, Khaled is saying that’s not true. He says, “I had a face only a mother could love.” This is an old expression; “to have a face only a mother could love” means that you are really ugly, that you are the opposite of cute and adorable, and that the only person who would love you because of the way that you look would be your own mother, because a mother, we usually think, loves all of her children – regardless of how ugly they are!
Susanna says, “That’s not true! You have a great profile.” Your “profile” is the way your face looks from the side – with someone looking at it from the side. “Profile” has several meanings in English, some of which are in our Learning Guide for this episode. Susanna continues, “I’d expect to see your likeness in paintings and on statues.” He’s so beautiful, Susanna is saying of Khaled, that he could be in a painting or on a statue. She says she would expect to see his likeness on a statute. “Likeness” is a similarity in the way that something appears; it’s what something looks like. A “statue” is a large piece of sculpture made of stone or metal, usually of a famous person or animal. In Minnesota, they makes sculptures out of butter for the Minnesota State Fair. Bet you didn’t know that; well it’s true!
Khaled says, “Okay, enough with the brown-nosing.” “To brown-nose (someone)” is to be very nice to someone because you want that person to help you. We use that term sometimes in school. “He’s a brown-noser with the teacher.” He says nice things to the teacher; he gives the teacher things so that the teacher will give him a good grade.
Khaled then says, “What do you really want?” Susanna says, “I don’t want anything…okay, just one little thing.” So course, Khaled was right. She says, “My cousin is in town (meaning my cousin is visiting – is in the city where I live, she’s from somewhere else). I want to go out with Rick tonight (presumably her boyfriend) and I thought we could double date,” meaning you have a man and a woman who are dating – romantically involved – and then another couple who are romantically involved, and the four of you go to dinner or to a movie or whatever. That’s “double dating.” She says, “Me, Rick, my cousin…and you.” Notice she says “me” instead of “I,” informally that’s very common. She says, “Me, Rick, my cousin…and you. What do you say?” meaning what is your opinion, what do you think. Are you interested, is what she’s asking.
Khaled said, “I knew it had to be something. Does she look like you?” meaning does your cousin have a similar physical appearance as you do. Susanna says, “We are like two peas in a pod.” “Peas” are small green vegetables that come in – or grow rather in something called a “pod” – a “peapod.” Kind of like a podcast! Actually nothing like a podcast. So, “two peas in the pod” means two things that are very similar. She’s saying that she and her cousin resemble each other; they look alike.
Khaled, when he learns that the cousin looks just like Susanna says, “Then, forget it!” Khaled is insulting Susanna, saying that she isn’t pretty enough for him to go out with someone who looks like her. That’s not nice Khaled! You shouldn’t say that sort of thing to a woman.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Khaled: Hi, what are you looking at?
Susanna: Your photo albums. Your roommate let me in and said I could make myself comfortable while I waited for you.
Khaled: There are some really incriminating pictures in there. You’d better give those back to me.
Susanna: Not yet! I’m looking at your baby pictures and your family portraits. You’re the spitting image of your mother.
Khaled: That’s not my mother. That was our neighbor.
Susanna: Oh, now that I look a little closer, I can see that you resemble your father. You’re a chip off the old block.
Khaled: That’s not my father. That’s my father’s friend. Now, why don’t I take those…
Susanna: Wait! These candids of your birthday parties are so cute! You were so adorable!
Khaled: Right. When I was a kid, I had a face only a mother could love.
Susanna: That’s not true! You have a great profile. I’d expect to see your likeness in paintings and on statues.
Khaled: Okay, enough with the brown-nosing. What do you really want?
Susanna: I don’t want anything…okay, just one little thing. My cousin is in town. I want to go out with Rick tonight and I thought we could double date. Me, Rick, my cousin…and you. What do you say?
Khaled: I knew it had to be something. Does she look like you?
Susanna: We are like two peas in a pod.
Khaled: Then, forget it!
Susanna: Hmph!
[end of dialogue]
Our scriptwriter here is so good, you should see her likeness on statues! It’s Dr. Lucy Tse, of course. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
photo album – a book with special pages that hold photographs under plastic so that they are protected and can be viewed easily
* Did you make a photo album for your baby’s first year?
incriminating – making someone seem guilty of something; showing that one has done something wrong
* We know you stole a camera from the store. We have incriminating footage of you from the security video cameras.
baby picture – a photograph taken of a very young child, usually less than one year old, to remember what he or she was like at that time
* Patricia took a lot of baby pictures of her daughter in the bathtub.
family portrait – a photograph of all the members of a family, taken in a studio by a professional photographer
* Every year they have a family portrait taken so they can send it to friends and relatives with their Christmas card.
spitting image – with a very similar physical appearance; looking almost the same
* Soren is the spitting image of his big brother.
to resemble – to look like someone or something
* This building’s architecture resembles city hall, don’t you think?
a chip off the old block – a child who is very similar to his or her father either in appearance or actions
* When I was growing up, I was a chip off the old block, always interested in fishing, carpentry, and whatever else my father liked.
candid – a photograph taken as something is happening, without asking people to stand in a certain way or look at the camera
* Candid photos are always so much more interesting than posed photos, because they show how people actually behave.
cute – attractive and pretty; pleasant, often used to describe young children and small animals
* Your baby girl would look so cute in this pink dress!
adorable – very pretty and attractive, making one love someone or something
* Those shoes are adorable! I’m going to buy a pair, too.
a face only a mother could love – a phrase used to describe an unattractive or ugly person
* Heather always tells people that when she was growing up, she had a face only a mother could love, but seeing how pretty she is now, I don’t believe her.
profile – the way one’s face appears when viewed from the side
* Soriah never realized how nice her nose looked until she saw a photograph of herself in profile.
likeness – a similarity in the way something appears; what something looks like
* Who drew the likeness of George Washington that appears on the one dollar bill?
statue – a large sculpture made of metal or stone in the shape of a famous person or an animal
* Who was the model for the Statue of Liberty?
to brown-nose – to be very nice to someone, usually because one wants him or her to do something for oneself
* Wahid always brown-noses his teachers, hoping to get better grades.
What do you say? – a phrase used to ask for one’s opinion about something or to find out if one is interested in doing something
* A group of us are going skiing this weekend. What do you say? Do you want to come?
to look like (someone) – to be similar in appearance to someone else; to share someone’s physical characteristics
* Hattie’s new boyfriend looks a lot like Mr. Taylor, but he’s younger and taller.
two peas in a pod – two things that are very similar in appearance or behavior
* Ward and his best friend are two peas in a pod – they both like watching baseball and collecting old records.
Comprehension Questions
1. What is a photo album?
a) A way to display the photos a person has chosen to keep.
b) A portfolio of professional modeling photos.
c) A collection of photos by a professional photographer.
2. What does Susanna mean when she says, “You’re the spitting image of your mother”?
a) Khaled is less attractive than his mother.
b) Khaled looks just like his mother.
c) Khaled is more attractive than his mother.
Answers at bottom.
What Else Does It Mean?
candid
The word “candid,” in this podcast, means a photograph taken as something is happening, without asking people to stand in a certain way or look at the camera: “My hair is such a mess in those candid photos! If I’d known you were taking pictures, I would have brushed my hair.” Candid Camera was a popular television show that secretly recorded people’s reactions in very strange or unusual situations and then told them they were being recorded: “Did you see the Candid Camera episode where people tried to close desk drawers, but other drawers kept opening?” Finally, the word “candid” means honest or frank: “Please give me your honest opinion. Do you think I’d look better with a beard and moustache?”
profile
In this podcast, the word “profile” means the way one’s face appears when viewed from the side: “Today the art teacher taught us how to draw better profiles.” The word “profile” also means a short written description of someone or something, especially for a social networking site: “I’m going to update my profile on LinkedIn when I accept a new job.” The phrase “high profile” describes something that is well-known and gets a lot of attention, possibly because it has a lot of power or influence: “Tina wants to work for a high-profile law firm.” Finally, the phrase “to keep a low profile” means to be unnoticed, or to do things in a way so that other people won’t notice: “Some successful investors keep a low profile, investing small amounts in many unpopular stocks that other people aren’t interested in.”
Culture Note
Many Americans like to go to professional photography “studios” (rooms or buildings where art is created) to have family portraits or children’s portraits taken. Often this is done at the end of the year so the photos can be “enclosed in” (put into) holiday cards that are mailed to friends and relatives. Children’s portraits are also taken at important “milestones” (important moments or accomplishments), such as when a child turns two months, six months, or one year old, or when a child starts going to school or graduates from high school.
Usually people choose a “standard” (normal; regular) “background” (what is seen behind the people in the photograph) like a grey or blue cloth. But sometimes people choose “themed” (with a certain idea) backgrounds, like a photograph of a living room decorated for Christmas.
Portrait studios usually advise people to wear “solid-colored” (all one color) clothing that “contrasts with” (is different from) the background. They advise avoiding “busy prints and patterns” (fabric with a lot of designs) or “stripes” (horizontal or vertical lines) because they can be a distraction from the person’s face. Sometimes people choose to have everyone in the portrait dress the same way. For example, they might all wear white shirts.
Portrait studios normally have several “props” (objects to interact with) to select from. These might include flower “petals” (the small, colored pieces of a flower), chairs, and sofas. People can also bring their own props, such as a child’s favorite toy or stuffed animal. These objects can “personalize” (make something unique) the photographs, reflecting the person’s personality.
Comprehension Answers
1 - a
2 - b