= 0648
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 648: Working on Commission.
This is English as a Second Language Podcast episode 648. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode. The Learning Guide will help you improve your English even faster – and if you eat it, save money on food!
This episode is called “Working on Commission.” Dennis and Irene are having a conversation. Dennis is a salesman; his job is to sell things to other people. Let’s get started.
[start of dialogue]
Dennis: I just got a new sales job and I’m going to be making a bundle.
Irene: What kind of job is it?
Dennis: I’ll be working strictly on commission. The more I sell, the more I earn. It’s a great opportunity for someone with my talents in sales.
Irene: I know you’re great at sales and I’m sure you’ll do well, but you can’t coast in a job based on commissions. You’ll have to work really, really hard.
Dennis: I’m not worried. For me, selling is second nature. I’ll barely have to lift a finger and the profits will come rolling in.
Irene: But isn’t your paycheck going to be in flux all the time? You’ll never know what your take-home pay will be.
Dennis: There’s no cap on how much I can earn, so the sky’s the limit.
Irene: That’s not exactly what I meant. Some weeks, it may be hard to live on what you earn, don’t you think?
Dennis: What? Do I hear a hint of uncertainty in your voice?
Irene: No, it’s just that…
Dennis: Put your mind at ease. I could sell ice to Alaskans!
[end of dialogue]
Dennis begins by saying, “I just got a new sales job and I’m going to be making a bundle.” “I just got (I was just given, in this case) a new sales job.” “Sales” is the profession of persuading people to buy something from you. Dennis says he’s going to be making bundle. The expression “to make a bundle” (bundle) means to earn a lot of money, to get a lot of money for your job. Doctors and attorneys can often make a bundle, but not all of them are making a lot of money of course.
Irene asks, “What kind of job is it?” Dennis doesn’t answer exactly, he says, “I’ll be working strictly on commission.” “To be working strictly (or only) on commission” means that you will only get money if you sell something. Many sales positions give you a certain amount of money, and then you can make more money, what’s called a “commission,” on the things that you sell, typically a percentage of the thing you are selling. So if you are selling cars you may get a salary, that is, a regular amount of money – a regular paycheck. But if you sell a lot of cars you can make even more money by getting a commission, a percentage of each car that you sell. Dennis says, “The more I sell, the more I earn. It’s a great opportunity for someone with my talents in sales,” that is, someone who is good at sales like he thinks he is.
Irene says, “I know you’re great at sales and I’m sure you’ll do well, but you can’t coast in a job based on commissions. You have to work really, really hard.” “To coast” (coast) as a verb means to relax and become a little lazy, not working very hard. Irene is saying that you cannot coast – you can’t get lazy, you have to work hard. “Coast” has a number of meanings in English, some of them are found in our Learning Guide.
Dennis says, “I’m not worried (I’m not concerned). For me, selling is second nature.” Something that is “second nature” is something that you know how to do and you do very well. We might say “it comes naturally to you,” it’s easy for you because you know how to do it or because perhaps you have some talent, some ability that allows you to do it easily. Dennis says, “I’ll barely have to lift a finger and the profits will come rolling in.” “To barely have to do (something)” means that you have to do it, but you almost don’t; you don’t have a very strong need to do it, however you do actually have to do this thing. Well, Dennis says he will barely have to lift a finger. In this case, “to lift a finger” means to perform a job or a task, to do something, to work. The expression “I barely have to lift a finger” means I’m not going to have to work very hard. “And,” Dennis says, even though he’s not going to work very hard, “the profits will come rolling in.” “Profit” (profit) is money that you make in your job or your business; it’s the difference between the money that you spend, what we would call your “expenses,” and the money that you get, your “income.” That’s profit. Dennis says, “the profits will come rolling in,” meaning they will be very large, they will come in in large amounts. There’s going to be a lot of money that he’s going to make, and he’s not going to have to work very hard. Hmm, I’d like a job like that!
Irene says, “But isn’t your paycheck going to be in flux all the time?” Your “paycheck” (one word) is the money you get for working, often received once a week, sometimes once every other week – every two weeks, that is, or, in some jobs, once a month. The paycheck is the money that your “employer,” the person who owns the company or the person you work for, give you for the work you do for them. Now, Irene says – or really asks Dennis, “isn’t your paycheck going to be in flux all the time?” Something that is “in flux” (flux) is something that is changing a lot; it is not constant, there’s a lot of variation. You’re not really sure if it’s going to be a lot or not very much. That’s when something is in flux, it’s not certain. Irene thinks that because Dennis is working strictly, or only, on commission his paycheck will be in flux; some weeks he’ll sell a lot, some weeks he won’t sell very much. She says, “You’ll never know what your take-home pay will be.” Your “take-home pay” is the actual amount that you get from your company after the taxes that you have to pay, after the other what we call “deductions,” things that the company takes out of your paycheck that it’s required to do. It may be for health insurance, it may be for taxes, it may be for your retirement savings. Your take-home pay is what you actually can put in your bank from your paycheck.
Irene says that the take-home pay will be in flux; you won’t know what it is. Dennis says, “There’s no cap on how much I can earn, so the sky’s the limit.” Notice Dennis doesn’t even really listen to what Irene is saying. Perhaps they’re married! Dennis says, “There’s no cap,” that is, there’s no maximum amount. A “cap” (cap) is the highest or largest that something can be. You might live in a city that puts a cap on the height of buildings; they can only be so tall and no taller. “Cap” has several meanings in English, and those are in the Learning Guide. Dennis says, “the sky’s the limit.” That’s an expression that means anything is possible, it has no limitations. There’s no cap; it can be as big or as high as you want – the sky’s the limit.
Irene says, “That’s not exactly what I meant. Some weeks, it may be hard to live on (to survive on) what you earn (what you make), don’t you think?” Dennis says, “What? Do I hear a hint of uncertainty in your voice?” A “hint” (hint) of something is a little bit of something, a small amount of something. Dennis thinks that Irene is doubting his abilities as a salesman. She is asking these questions and he thinks that there is “uncertainty in her voice,” meaning even though that’s not what she is saying directly to him that’s what she really means.
Irene says, “No, it’s just that…” Dennis interrupts her and says, “Put your mind at ease. I could sell ice to Alaskans!” “To put your mind at ease” (ease) means to relax, to stop worrying about something. The expression “to sell ice (which is frozen water) to Alaskans,” people who live in the state of Alaska, in the northern part of North America; Alaska is in between Canada and Russia, and is of course very cold because it is close to the North Pole. The expression “to sell ice to Alaskans” means to be able to sell anything to anyone because the idea is that Alaskans don’t need ice because it’s already very cold, but if you could sell ice to them then you could sell anything. The original expression was “to sell ice to Eskimos.” The term “Eskimo” refers to those people who were living in that area before the Europeans arrived there, what we would call in other contexts Native Americans. However, the term “Eskimo” is considered, especially in Canada, to be one that is not complimentary. That is, it’s a term, like the word “Negro” to refer to black or African Americans, that is no longer used that much. “Eskimo” is, in fact, still used in Alaska, but because it is a term that our Canadian listeners would not like, we’ve changed the expression a little bit.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Dennis: I just got a new sales job and I’m going to be making a bundle.
Irene: What kind of job is it?
Dennis: I’ll be working strictly on commission. The more I sell, the more I earn. It’s a great opportunity for someone with my talents in sales.
Irene: I know you’re great at sales and I’m sure you’ll do well, but you can’t coast in a job based on commissions. You’ll have to work really, really hard.
Dennis: I’m not worried. For me, selling is second nature. I’ll barely have to lift a finger and the profits will come rolling in.
Irene: But isn’t your paycheck going to be in flux all the time? You’ll never know what your take-home pay will be.
Dennis: There’s no cap on how much I can earn, so the sky’s the limit.
Irene: That’s not exactly what I meant. Some weeks, it may be hard to live on what you earn, don’t you think?
Dennis: What? Do I hear a hint of uncertainty in your voice?
Irene: No, it’s just that…
Dennis: Put your mind at ease. I could sell ice to Alaskans!
[end of dialogue]
Writing scripts is second nature to our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
sales – the field and profession of persuading people to buy something
* Melissa makes 10-20 sales calls per week, but usually only one or two people want to hear about the products she’s selling.
to make a bundle – to earn a lot of money for one’s work
* High-powered attorneys can make a bundle, but they have to work long hours.
to work strictly on – to receiving compensation for one’s work in only one way
* Our tour guides have to agree to work strictly on wages. They aren’t allowed to accept tips or gifts from customers.
commission – money received for one’s work as a percentage of the sales one makes, or as a certain amount of money one receives for each sale
* Yehsev receives a 5% commission for each sale he makes.
to coast – to relax and become lazy, not working very hard
* Ingrid got a perfect score on the first major test, so now she plans to coast through the rest of the course.
second nature – something that one has learned how to do and now understands well and/or does very well without trying very hard
* After living in Brazil for more than 20 years, speaking Portuguese has become second nature to Rebecca.
to barely have to – to almost not need to do something; to not have a very strong need to do something
* Amber barely has to put on any makeup because she’s very beautiful.
to lift a finger – to work; to perform a job or task; to do something
* Grant has been living with us for six weeks, but he still hasn’t lifted a finger to help us clean the house.
profits – money that one makes from one’s work or business; the difference between revenues (the money one receives) and expenses
* They’re trying to increase profits by firing unnecessary employees.
to come rolling in – for something to come or be received in large amounts
* The business really struggled for the first few years, but now new customers are rolling in.
paycheck – a payment of money one receives for one’s work, usually received once a week, two times each month, or once a month
* Franck tries to save 10% of each paycheck for retirement.
in flux – changing a lot; not constant; with a lot of variation; uncertain
* Thomas’s career goals are in flux and he doesn’t know what he wants to study at the university.
take-home pay – the amount of money one receives in one’s bank account for one’s work after all deductions for taxes, health insurance, retirement, and similar expenses have been subtracted from the total amount earned
* It’s a good idea to put as much money into our retirement savings as we can, but that means we’ll have less take-home pay.
cap – a maximum amount; the highest or largest that something can be
* The law would place a cap on how much money someone can receive on unemployment beginning in 2015.
the sky’s the limit – without limitations or restrictions; anything is possible; something can be as big or high as desired
* Now that your articles are being published in national magazines, the sky’s the limit. You’ll be famous!
a hint of – a trace; a little bit of something; a small amount of something
* These cookies have a hint of cinnamon and nutmeg.
to put (one’s) mind at ease – to relax and stop worrying about something
* It puts my mind at ease to know the kids are with your parents tonight.
to sell ice to Alaskans – to be able to sell anything to anyone, even if people don’t really need what you are selling
* Rakkei has the best sales skills I’ve ever seen! I swear he could sell ice to Alaskans.
Comprehension Questions
1. What does Irene mean when she says, “you can’t coast in a job based on commissions”?
a) You’ll have to work very hard.
b) You won’t be able to travel to the beaches.
c) You’ll have to use your brakes while driving.
2. What does Dennis mean when he says, “There’s no cap on how much I can earn”?
a) There are no limits on his income.
b) He will not have to pay taxes.
c) He doesn’t have to report his earnings to the government.
Answers at bottom.
What Else Does It Mean?
to coast
The verb “to coast,” in this podcast, means to relax and become lazy, not working very hard: “Ellery has always gotten good grades, so he thought he’d be able to coast through medical school, but it was much more difficult than he had expected.” The verb “to coast” also means to ride a bicycle without pedaling or to drive a car without using the gas pedal: “Biking up the hill is hard work, but I love the feeling of coasting down.” As a noun, “coast” refers to land next to the sea or ocean, like a beach: “Do you want to go to the coast or the mountains this weekend?” Finally, the phrase “the coast is clear” means that someone can do something without being seen: “Please tell me when Victor leaves, so I’ll know the coast is clear.”
cap
In this podcast, the word “cap” means a maximum amount, or the highest or largest that something can be: “New York City put a cap on apartment rent so that low-income people can afford to live there.” A “baseball cap” is a hat that has a slightly curved piece in the front to shade one’s eyes: “He pulled the baseball cap lower to keep the sun out of his eyes.” A “shower cap” is a piece of plastic with elastic around the edges, worn over one’s head to keep one’s hair dry: “Denise washes her hair only twice a week, so she wears a shower cap when she takes a shower on the other days.” Finally, a “cap” is also a small lid for a bottle or another container: “Where did I put the cap for the milk carton?”
Culture Note
Many salespeople work on commissions. This is because the “payment arrangement” (the way people are paid) “aligns” (makes things work together in the same direction or for the same purpose) the interests of the company and the salespeople, so that everyone tries to sell as much as possible.
Salespeople sometimes earn commission as a “flat fee” (an unchanging amount) for each sale they make. When salespeople are able to “negotiate” (reach agreements on) the sales price with their customers, they often earn a commission as a percentage of their total sales, so that they have an “incentive” (a reason to do something) to negotiate a higher sales price and help the company increase its profits. Percentage-based commissions are used with people who sell cars, for example.
“Real estate professionals” (people who help individuals buy and sell homes) work on commission, usually receiving around 2-3% of the sales price of a home. “Insurance brokers” (people who help individuals find the best insurance policies) and “mortgage brokers” (people who help individuals find the best loan to buy a home) also work on commission, receiving a percentage of the amount that their customers pay to the insurance company or “lender” (a business that makes loans).
Commission-based payment arrangements work well, because the salespeople have an incentive to work hard. However, they can also encourage dishonest or “fraudulent” (breaking the law through dishonesty and deception) practices, like when salespeople lie to customers about their products in order to “make the sale” (persuade someone to buy something). For that reason, companies sometimes make the commissions “contingent upon” (dependent on) customer satisfaction, so that the salespeople do not receive their commission if the customer complains or tries to return the product.
Comprehension Answers
1 - a
2 - a