
= 家长控制, 会造成孩子自信障碍
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css


'''

== 家长控制, 会造成孩子自信障碍


Domineering 喜欢支配别人的  parents may keep kids under their thumb 拇指 to try to protect the kids from the perils 危险 of peer 同辈 pressure. But this approach 方法 may backfire (v.)适得其反 / and actually make kids more susceptible 易受…影响的 to going with the crowd 从众. So finds (v.)  a study in the journal Child Development.

The researchers *learned about* 听到；得知；获悉 their parents’ control tactics 战术 such as using (v.) guilt to manipulate 操纵 behavior / and watched how the kids dealt with a difference of opinion or argument 争论；争吵 with a friend.

`主` The now young adults who’d had highly controlling parents `系` were less able *to stress* (v.)强调 their own viewpoints 观点 *to* a friend or partner (n.)伙伴 方式状 in confident and productive 富有成效的 ways. And the effects of that inability (n.)无能力 increased (v.) over time: poor relationship skills in an 18-year-old predicted (v.) further deficits 赤字 at 21.

Seems that /`主` resisting (v.)抵抗；忍住 parental control `系` may be how kids learn to assert (v.)坚持自己的主张 themselves, an important skill for healthy future relationships.

[.my2]
专横的父母们可能会像将孩子们捧在手心里那样照顾免他们受来自同辈的压力。但实际上这种方法可能完全适得其反,孩子们会更易受到别人影响。这是根据在《儿童发展》杂志上的研究所得出的结论。 +
研究人员对于他们父母，使用诸如内疚操控行为的控制措施进行了研究，而后观察孩子们如何应对一位朋友的不同意见或争论。 +
现在受到父母高度控制的年轻人，不能向朋友或合作伙伴自信且及富有成效地强调自己的观点。而且这种缺乏能力的影响，会随着时间增加: 比如18岁时与人的糟糕关系技能，预测在21岁时会进一步恶化。 +
似乎抵制家长控制，就可使得孩子们坚持己见，这可是对于健康未来关系不可或缺的一项重要技能。



'''


== <pure> 家长控制, 会造成孩子自信障碍

Domineering parents may keep kids under their thumb [to try to protect the kids from the perils of peer pressure. But this approach may backfire  [and actually make kids more susceptible to going with the crowd. So finds a study [in the journal Child Development.

The researchers learned about their parents’ control tactics  [such as using guilt to manipulate behavior  [and watched how the kids dealt with a difference of opinion or argument [with a friend.

The now young adults [who’d had highly controlling parents [were less able to stress their own viewpoints to a friend or partner [in confident and productive ways. And the effects of that inability [increased over time: poor relationship skills (in an 18-year-old) predicted further deficits at 21.

Seems that [resisting parental control may be how kids learn to assert themselves, an important skill for healthy future relationships.

'''
