= 1315
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café episode 10.
This is English as a Second Language Podcast’s episode 10. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. On this Café, we’re going to talk about a very popular tradition in the United States every year, what’s called the “Super Bowl party.” And finally, we’ll answer a few of your questions. Let’s get started.
Our first topic on this Café is the American tradition, I guess it has become, of a Super Bowl party. Let’s first explain what the Super Bowl is. The Super Bowl is the championship game in American professional football. Every year, the winners of the two different divisions – or “conferences,” as they’re called – of American football meet together and play again to decide who is the best team. This is the championship game.
Now, unlike other popular sports in the U.S. such as baseball and basketball and hockey, American football doesn’t have a series of games. You don’t play three or four or five or seven games to decide the winner. You play just one game, and that game is called the Super Bowl. Why do we call it a “bowl” (bowl)? Well, many of the championship games that are played by football teams are called the bowls, including those for American football teams at the college or university level.
You probably know what a “bowl” is. Normally, it’s a round container that you put food into. Well, if you think of a football stadium, some people thought it looked a little like a bowl, and so – believe it or not – we started calling these football championship games “bowls.” And because we’re talking about the professional football association – the National Football League, as it’s called – someone decided that it would be considered the biggest bowl game in football, and hence the name Super Bowl.
The Super Bowl has been going on since 1969 and takes place every year either in January or February. It takes place on a Sunday afternoon, and so we call that day “Super Bowl Sunday.” In a game of football, there are basically two halves – two parts of the game. In between the two halves, there is a time when the teams go back and rest, and people can get up and get food and so forth.
During the Super Bowl, the “halftime,” as it’s called – that time in between the two halves – is also the time for what’s called a “halftime show,” where they have entertainment, usually a famous singer, for example. I remember a few years ago at the Super Bowl, the halftime show I think included Bruce Springsteen, one of the more famous singers from the 1970s and 80s.
Because the Super Bowl is such an important game and a popular game, many Americans like to have a party – what we may call a “viewing party” – where everyone comes over to your house and you have things for them to eat and drink, and you watch the game together. Super Bowl parties are very popular and have become even more popular I think in recent years.
Now, if you are like me and you don’t like to cook, you may decide to have the food for your party delivered. To have your food “delivered” means that you call up a restaurant and you tell the restaurant what you want to eat, and the restaurant brings you your food right to your house. Well, for American football – especially for the Super Bowl – the most popular kind of food that people eat is pizza. So, if you own a pizza restaurant, Super Bowl Sunday is going to be one of your busiest days, for sure.
You could also, of course, go to the restaurant and pick up your food, especially if you wanted it more quickly. When you go to a restaurant and pick up food and take it home, that’s called “takeout.” In the United Kingdom, in British English they usually use the word “takeaway,” but in the U.S. it’s more common for people to use the expression “takeout.” So, takeout food is food that you go and pick up at the restaurant and bring back to your house.
You can also, in some restaurants, have your food delivered, as we mentioned earlier. Often, you will find people going to Super Bowl parties who don’t even like American football very much, but it becomes a social event where you get to see your friends and family and basically is just another excuse for a party.
Many people watch the Super Bowl not for the game but for, believe it or not, the commercials – the advertisements that are shown during the game. Many of the largest companies produce advertisements for this game since it is one of the most popular television events of the year. Many of the ads are considered (or try to be) innovative. Many of them are funny, and so it’s almost a kind of separate entertainment watching the commercials, or the advertisements, during the game.
A lot of people also like watching that halftime show, I mentioned, where you have popular entertainers, often singers, that perform. So, that’s one of the many uniquely American customs that we could talk about, certainly one which is very popular with millions of Americans. Not with me, however. I’m not really a big fan of football, and I don’t think I’ve watched a Super Bowl in at least 20 years, but I’m unusual in many ways. My wife tells me that often.
Now let’s answer some of the questions you have sent to us. Our first question has to do with the difference between two words, “widow” (widow) and “widower.” What are a widow and a widower, and what’s the difference? Well, a “widow” is a woman whose husband has died. And of course, in most countries, women live longer than men, and so there are usually more widows than there are widowers. A “widower,” with an “-er” at the end, is a man whose wife has died. So, a widow is a woman whose husband has died, and a widower is a man whose wife has died.
Our next question has to do with the verb “to advocate” (advocate). What does it mean to advocate something? “To advocate” means to support something. Someone who advocates ending smoking in public areas is someone who is trying to make a change in the law or the policy about a particular topic. An “advocate,” as a noun, is a person who usually tries to make some changes in the law or, again, in some policy.
Often we use the noun “advocate” to talk about someone who works for the public or who tries to make things better for the public, or for one particular group. You could be an advocate for civil rights – you could be someone who works hard to try to make sure that there is no discrimination and that everyone is treated equally. So, as a noun it describes a person who is involved usually in some organization or trying to make some sort of change in society.
As a verb, “to advocate” can mean more generally to be in favor of something and to try to get your ideas adopted or to change something so that it agrees with your ideas about how whatever that thing is should be done. You could, at your work, advocate for shorter working hours. You could go around and talk to people and maybe write letters or do other things to try to get that change in your company. You probably won’t be successful, but you can certainly try.
We have a question here from a listener about an expression that I sometimes use on the podcast, and that is “trust me.” “Trust me” means “believe me.” It’s a phrase that we use when we want someone to believe us, perhaps because it’s a situation where the other person may doubt that we’re telling the truth, or where we want to express to the other person how confident we are of what we are saying.
For example, “Trust me, you don’t want to eat at that new restaurant. I went there and the food is terrible.” “Trust me” is a way of getting the person to pay attention and to believe what you are saying. Usually you use that expression when you have some personal experience. You’ve actually, in this case, gone to the restaurant and eaten the food, and so when you say to someone, “Trust me, don’t eat that restaurant,” you’re saying, “I have personal experience that tells me that this recommendation is true” – in this case, that you should not eat at this restaurant.
Our next question is actually four questions, four words that one of our listeners wanted to know about. The words are “buddy” and “mud.” These words aren’t related to each other, but let’s start with the first one, which is “buddy” (buddy).
“Buddy” is an informal term, or can be an informal term, for a friend. However, it’s not used that way very much anymore. If it is used to mean friend, it’s probably being used when talking about young children, especially young boys – a five-year-old or a six-year-old and his buddy. You will hear adults talk about their friends as “my buddies,” but it’s not quite as common anymore – at least, not as common as when I was growing up.
In fact, in some ways “buddy” nowadays is more likely to be heard in a negative context in a situation where you are talking to someone you don’t know and who has done something wrong, and you want to get that person’s attention. “Hey buddy, stop using your cell phone in the coffee shop. You’re bothering me.” There, “buddy” does not mean “friend” in the sense that you know this person and like them. Instead, “buddy” is sort of like “Hey, you.” It’s usually used in that context in a negative way.
It might even, if used in certain circumstances, get you into a fight. So, you have to be careful about using the word “buddy,” especially if you are talking to someone you don’t know. When you do that, people are going to think that you are angry at them or that you are perhaps even interested in fighting them.
“Mud” (mud) is the next word on our list. “Mud” is pretty easy to explain. It’s basically a mixture, a putting together, of dirt and water. If you are walking in certain parts of the city where there aren’t any lawns – where there isn’t any grass, there’s just dirt – and it rains, that will create mud. So, mud is basically wet earth, wet ground, wet soil (soil). All of these things refer to the combination of water and dirt.
Our next question concerns the phrase “I bet” (bet). This is an interesting expression because we use it in situations when we’re not actually betting anything. What do I mean by “betting” something? “To bet” is a verb used normally to describe a situation where you have at least two people, often more, who make predictions about something that will happen in the future.
One person says that Horse A is going to win the race, and another person says Horse B is going to win the race. So, they bet. They each put ten dollars on the table. If Horse A wins, then the first person gets to collect his original ten dollars plus the ten dollars of the other person. Of course, if Horse B wins, the opposite happens. The person who “bet on” – notice the preposition we use, to bet “on” – the person who bet on Horse B would get twenty dollars. That’s the meaning of the verb “to bet.”
When we say, however, “I bet” in normal conversation, we’re saying “I guess – and not only am I guessing, but I’m pretty sure that I am correct.” “I bet that girl doesn’t give you her phone number.” You’re not actually betting your friend that the beautiful girl won’t give him her phone number. You are saying, “I’m pretty sure – in fact, I’m so sure of this prediction that I would actually bet money on it,” even though you aren’t actually betting any money on it.
There’s another use of the expression “I bet,” which is somewhat strangely the opposite in meaning of the first use that we just discussed. “I bet” is sometimes used to show that you don’t believe another person. If someone tells you, “Hey, I just want a million dollars,” and you don’t believe this person, you might say, “Yeah, I bet.” You say it with a certain intonation – a certain way of using your voice – that indicates that you don’t believe what the person is saying. So, strangely, “I bet” can mean two things: one, I’m absolutely sure of something, and two, I don’t believe what you’re telling me.
Our next question has to do with a word that in some ways isn’t really a word, although you will hear it in conversation, and that word is – or non-word is – “gonna” (gonna). “Gonna” is “going to.” It’s actually two words, but when we pronounce it, we combine the two words together. That happens a lot in English, where we take two words and we say them very quickly, and in doing so we often almost combine them. This is something we do in informal conversation, or casual conversation.
“Going to,” of course, refers to something that will happen in the future. So, you might say, “I bet you’re gonna go on vacation next week.” “You’re gonna go” means “you are going to go,” and if we said the sentence very slowly, you would hear each individual word.
A similar case arises, or takes place, with “want to.” “Do you want to go?” People will instead say, “Do you wanna go” (wanna). “Wanna” isn’t a word, if you look it up in the dictionary. It’s a combination of two words that’s used informally in conversation. You might read it in a book if someone is, for example, writing a dialogue about how people actually talk.
The next question refers to an expression which I sometimes use here on the Café and in our other episodes, which is “speaking of which.” “Speaking of which” is a phrase we use to introduce a new topic, a new subject, that is related to what I was just talking about.
So, for example, if I’m talking about the weather and how cold it is in my home state of Minnesota, or how hot it is in the state of Arizona, then I say, “Speaking of which, it’s really hot in this room. Could you open a window, please?” I was talking about things being hot and cold, but now I want to talk about a new topic, which is how hot it is in his room. It’s related, but of course it’s not the same. I’m not talking about the weather outside; I’m talking about the temperature.
“Speaking of which” is a way of connecting two ideas that are related but different, especially when you want to change the topic of your conversation and go in a different direction – start talking about something different.
Someone emailed a question about three words which are all related. The first word is “widow,” the second word is “widower,” and the third word is “to pass away.” Let’s start with the third word, “to pass away.” “To pass away” is a two-word phrasal verb meaning to die. Why don’t we say “he died” instead of “he passed away”? The verb “to pass away” is a little more polite – a little less direct, perhaps. It’s something you might say in conversation.
If you know someone’s father has died, you may say something like, “I’m sorry to hear about your father passing away” rather than “I’m sorry to hear your father died.” It means the same thing, and you probably won’t get into any trouble if you use “die” instead of “pass away,” but “pass away” is a little bit more common, especially if it’s someone that the person with whom you are speaking knows or is related to.
We only use this verb in talking about humans. If you’re talking about an animal, we would probably just only use the verb “to die.” Although there are other verbs we can use when animals are killed. For example, we talk about a dog being “put to sleep.” If a dog is “put to sleep,” basically someone kills the dog, often because the dog is very old or perhaps because the dog is sick. So, in talking about humans, we use this phrasal verb “to pass away.”
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
Super Bowl – a football game during which the two best teams of that year's football season compete with each other to determine which one is best
* The New York Giants beat the New England Patriots in the 2012 Super Bowl.
delivery – the act of taking a product to the person who the product is meant for; the act of ordering or buying food from a restaurant and having the restaurant bring the food to one’s home
* Emilio is expecting an important delivery to arrive at the office and wants to be informed as soon as it arrives.
take out – food one orders and picks up from a restaurant to take home to eat
* Claire wanted to eat at home, so she asked to see the restaurant’s special take out menu.
half-time show – an entertainment show or program that takes place at a football game during the break in the middle of the game
* Chase was disappointed by the game’s half-time show because the performers weren’t very good.
widow – a woman whose husband has died
* Mrs. Mccroskey is a widow whose husband died from cancer two years ago.
widower – a man whose wife has died
* Darius became a widower after losing his wife in a fatal car accident last month.
advocate – someone who actively supports a goal; someone who writes or speaks in a manner that supports a belief, ideal, or person
* Muriel is an advocate for the educational rights of disable children, and she has written many articles and books on the topic.
trust me – what you say to someone when you want him to believe what you are telling them, to emphasize that they can and should believe you
* Trust me, if you don’t read a lot of English, your vocabulary will never improve.
buddy – an informal term for a friend; a term meaning "friend" that is sometimes used in a negative way to address someone who is acting in an unfriendly or bothersome way
* When the waiter continued to neglect Hank, Hank told him, “Hey, buddy, if you don’t want to take my order, then I’ll have to talk to the manager.”
mud – a mixture of dirt and water; wet soil
* The dog ran into the house with mud on his paws after the big rainstorm.
I bet – an expression used to express disbelief or doubt about what someone claims to be a fact; a phrase used to introduce what one believes to be true or believes will be true
* After having such a mild winter, I bet this summer will be very hot.
gonna – going to, used in informal or casual speech; to do something in the future
* Daniel is gonna go to the store as soon as he finishes mowing the lawn.
speaking of which – now that you/he/she mentions it; a phrase used to introduce a new topic that is similar to, but different from the current topic
* After Tomoko briefly mentioned her mother, her uncle asked, “Speaking of which, how did your mother’s operation go?”
to pass away – to die; a polite way to refer to someone who is no longer living
* Gwyneth passed away after suffering from a major heart attack.
What Insiders Know
The Puppy Bowl
In winter of each year is one of the biggest sport events of the year: the Super Bowl. The Super Bowl is the championship game for American football and it is a “showdown” (final competition) between the two best teams of the year. Many American TVs are “tuned into” (watching) the Super Bowl and the show has among the highest “ratings” (number of people watching) each year.
Ever since the Super Bowl started being “televised” (shown on television) 42 years ago, there has been counterprogramming. “Counterprogramming” is the showing of another type of television show on a different channel to attract viewers who may not want to watch a major television event like the Super Bowl, or to “draw away” (take away) viewers from that event. Since 2005, one piece of counterprogramming that has attracted a surprising number of viewers is the Puppy Bowl.
The Puppy Bowl is a TV show shown on a “cable channel” (television channel you can get by paying for a special service) called Animal Planet, which specializes in shows about animals. The Puppy Bowl “mimics” (imitates; tries to be like, for entertainment) the Super Bowl, but instead of men playing football, the game is played by “puppies” (young dogs). All of the puppies that play in the Puppy Bowl are from “animal shelters,” places for animals without homes. Throughout the show, viewers are given information about how to “adopt” (take home and make a part of their family) a dog from a local shelter.
The first Puppy Bowl was in 2005 and 2011’s Puppy Bowl “drew” (attracted) a total of about nine million viewers. So if you’re not a football fan and are looking for something to watch while the Super Bowl is on TV, this is an “alternative” (another option)