= 1320
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 15.
This is English as a Second Language Podcast’s English Café episode 15. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com.
On this Café, we’re going to be talking about the economy in the state of California, where I live. We’re also going to talk about some ways that some people – not me – waste time at work. And, as always, we’ll answer a few of your questions. Let’s get started.
We start this Café talking a little bit about how people – “employees,” we would call them – spend their time at work. An “employee” (employee) is a person who works for another person. The person who owns the company or the organization would be called the “employer” (employer). But we’re talking about “employees” – people who work for someone else.
I saw an article recently that surveyed workers in the United States and asked them how much time they waste at work. “To survey” (survey) means to ask people questions and get their answers. There’s also a noun “survey,” which would be a piece of paper or perhaps a website that asked for information.
Well, this survey – this “questionnaire,” we might also call it – asked people how they spent their time at work, and more importantly, how they wasted their time at work. “To waste (waste) time” means to use your time in a way that you’re not supposed to or that isn’t productive. You don’t actually get anything done. Watching cat videos on YouTube, for example, would be a good example of wasting your time.
Wasting time is not something that most employers – that is, companies or organizations – want their employees to be doing. The responses from the survey, the answers from this survey, are very interesting. The survey found that 37 percent of the time that people spent at work was probably wasted, according to the employees’ own reports. So, these are the employees telling the people who gave the survey that they waste more than a third of their time at work.
One of the things that the employees said that they did was read and answer email not related to work. That would be email from your family or your friends. Another thing that people did, not surprisingly, was look at websites – news websites, social media websites like Facebook, and personal or company blogs. A “blog” (blog) is a website where people give their opinions about things or their views about things.
The problem with workers or employees wasting time isn’t just an issue here in the United States. In another article I read, it said that in a survey of nine different countries, they found that about a third of the time people should be working was spent on other things – things that were not related to their work. So that figure, that number, of about one third seems to be true in other countries as well. The answers across a variety of countries, then, are fairly consistent. When we say something is “consistent” (consistent), we mean it’s the same, or it doesn’t change over time.
Of course, listening to ESL Podcast is not a waste of time. You can tell your employer I said that.
Our second and main topic of today’s Café is the state of California, and specifically, the economy in California. When we use the word “economy” (economy), we’re referring to the businesses and the economic or financial activity in a given state, region, or country. It refers to the amount of money that a place makes, that the businesses in a place make. It refers to the money that people are spending, the money that people are earning, the money they’re getting from their jobs. All of this is part of the economy.
In Southern California, one of the most important parts of the economy is the entertainment industry. An “industry” (industry) is a kind of business. So, the “entertainment industry” would be a collection or group of businesses that are all related to producing television shows and movies and music recordings. All of these kinds of companies would be part of what we would call the “entertainment industry.”
Now, here in California – in Southern California, that is, in Los Angeles – because the entertainment industry is so important, people often just refer to it as “the industry.” If someone asked you in Los Angeles, “Do you work in the industry?” he or she is asking if you work in the entertainment industry. It’s understood. Everybody knows that’s what “the industry” is here in L.A.
The movie industry, in fact, has been in Los Angeles since the early part of the twentieth century, but it’s not the only industry in the state of California. We have other businesses here in California other than the ones that make movies – or record podcasts, for that matter. Agriculture, for example, is a major industry in California. “Agriculture” (agriculture) refers to anything related to farming and producing food.
California produces, in fact, more than half of all the fruits and vegetables that are sold and eaten in the United States. California farms produce food such as oranges, grapefruits, asparagus, tomatoes, and even rice. California is also one of the largest milk-producing states in the country. We have nearly two million cows giving milk every day. Not too far from the city of Los Angeles, in fact, there are farms with lots of cows producing lots of milk.
California is also one of the biggest producers or makers of almonds, a type of small nut that is often combined with coffee, chocolate, or other sweet flavors. I like my almonds salted. I like a little bit of salt on the almond to make it a little more flavorful. Most of California almonds, however, are not eaten in the U.S. Rather, they are sent overseas – that is, to other countries.
When you grow plants to eat, we usually use the word “crop” (crop). A crop is a plant that is grown to produce food, or perhaps to produce something that we make into something else. “Cotton,” for example, is a very popular material for clothing. Cotton is a kind of crop. Be very careful in the pronunciation of this word. You don’t want it to sound like another word in English (crap), which is “crap” – a vulgar word that you probably know.
Anyway, getting back to crops. The main area in California where you will find a lot of crops is called the Central Valley. The Central Valley is an area in the center part of the state. A “valley” (valley) is a low area between two mountains or two sets of mountains. The Central Valley is about 450 miles long by 40 miles wide. That would be 725 kilometers by 65 kilometers, approximately. It’s located between two major mountain ranges, or groups of connected mountains, in California: the Sierra Nevada in the east, and the Coastal Range in the west.
The largest problem that farmers face, or that they have to deal with, in California today, however, is drought. “Drought” (drought) is a long period of very little or no rain – and of course, you need rain. You need water for crops to grow. When there isn’t enough rain, which is often the case in California, we have to irrigate the land. “To irrigate” (irrigate) means to bring water and put that water on the land. The noun would be “irrigation.”
California has not only been trying to find ways to protect its water. It’s also been finding ways to use water itself to produce new energy, what we would call “renewable energy.” “Renewable” (renewable) comes from the verb “to renew” (renew) which means to make something again or use something again. “Renewable energy,” then, is energy that comes from a source that can be used for a very long time or repeatedly. Power or energy from the wind or the sun or certain kinds of water are all considered renewable because they can be used over and over again.
Another large industry in California is shipping. “Shipping” (shipping) is transporting or moving things across the ocean in – what else? – ships or big boats. Here in Southern California, for example, we have what’s called a “port” (port). A port is a place where the ships come in and are able to pick up things to transport or leave things that have been transported.
When we transport things on a ship, we call those things “cargo” (cargo). Cargo is the items or goods that are transported on a ship. We also use that word for things that you transport on a plane or on a train. Here in California, there are actually 11 major ports – these would be areas that have places for big ships to come in and pick up things and deliver things. The ports in California are used for sending food to other countries, but they’re also used for sending other kinds of things.
California has manufacturing and a very important technology industry as well. “Manufacturing” (manufacturing) refers to making something, usually making something involving machines. California manufactures things such as computers and chemicals and airplanes. Many of these things are sent around the world using our ports, using large ships.
The technology industry has been an important part of California since the 1970s. Most of the technology industry in California is near San Francisco in an area called Silicon Valley. Many of the most important computer companies are located in Silicon Valley, and much of what is produced in Silicon Valley is sent to other parts of the world. Of course, the most important thing produced in these companies is not physical objects, but rather what we might call “intellectual property” – ideas, things that are transmitted via computer, not using a ship.
The film industry in California also contributes to another important industry here, which is tourism. “Tourism” refers to people coming and visiting a place, and California has many places such as Disneyland, or the city of Los Angeles, or the city of San Francisco, or our many beaches that are part of our tourism industry. People come here on vacation. They come to see things, to enjoy the beautiful weather we have, at least here in Southern California.
Not too far from where I live – a couple of miles, in fact – is a place called Venice Beach. Venice Beach is one of the most popular tourist destinations, or places where people go, in Southern California. So, that’s a little bit about the economy here in California – what sort of things people do to make money in my beautiful state.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Italy, from Alessandro (Alessandro). Alessandro wants to know the meaning of a couple of expressions he has heard or read. The first word is “carpet” (carpet). A carpet is basically a big “rug” (rug). It’s a soft, thick material that you can walk on, that you put on the floor. A carpet usually covers the entire floor from one wall to another. I have some carpet in my house on my stairs, going from the first floor to the second floor.
Carpet is very popular in the United States as a flooring, especially in the northern states of the U.S. where it is colder. In Minnesota, for example, where I’m from originally, there are lots of houses with carpet in them. It used to be also that carpet was very expensive, that only very rich people had enough money for it – could “afford” it, we would say. But it’s become much less expensive and therefore much more popular.
Another question Alessandro has relates to television stations in the United States as well as radio stations. The term that Alessandro wants to know about is “call sign.” “Call (call) sign (sign)” refers to the letters that identify a particular TV or radio station. So, for example, here in Los Angeles we have a television station with the letters KCAL KCAL. “KCAL,” we call it. We also have another radio station, called “KNBC.”
Usually radio and television stations have four letters. There’s actually some interesting history about these call letters, or call signs. The United States, like most countries, is part of an international agreement about call signs. It’s called the International Telecommunications Union. Basically it’s a treaty or legal agreement among most of the countries of the world. One of the parts of this agreement is that the countries will divide up the letters of the alphabet among the different countries.
So, for example, in Mexico the letter X is used as the first letter of call signs for radio stations and television stations. In the United States, there are two letters that always begin a radio station or television station call sign: K and W. And the difference between whether a station uses a “K” or whether it uses a “W” is, interestingly enough, where it is located as it relates to the Mississippi River.
The Mississippi River is the longest river in the United States, that basically cuts the lower forty-eight – the main part of the United States, not including Alaska and Hawaii – in half. So, it sort of divides the country in two. Everything – that is, all of the stations – east of the Mississippi River use the letter W as the first letter of the call sign. All of the stations that are west of the Mississippi River use the letter K. This is interesting to me because I grew up in Minneapolis, St. Paul, the Twin Cities, which are divided by – that’s right – the Mississippi River.
So, on one side of the river, the radio and television stations begin with a W, and on the east side of the river, in St. Paul, the stations begin with a K. So, we have both “K” and “W” stations in the Twin Cities. But most places are not on the Mississippi River or divided by the Mississippi River, so you’ll just hear or see either a “W” or a “K.” I know that’s probably more information than you really wanted about call signs in the U.S., but Alessandro asked, and so we answered.
Our next question comes from Dayamic (Dayamic), who is originally from Cuba, but now living in the state of Florida. His question has to do with the difference between two small but very important words in English, “yet” (yet) and “still” (still). Let’s take two similar sounding questions to explain the difference: “Is he here still?” and “Is he here yet?” They sound the same, but they’re in fact very different questions, because these are words with very different meanings.
The word “yet” (yet) refers to a situation where something has not happened. You’re waiting for it to happen. “Is it ten o’clock yet?” That means, “Have we reached the hour of ten?” You’re waiting for it, but it hasn’t arrived (or you could say, “It hasn’t arrived yet”).
“Still” is used in situations where something is going on and you are hoping – or expecting, perhaps – that it will end or that it should have ended. So, if you ask the question, “Is he here still?” you’re saying that the person has been there and continues to be there although there’s a notion that you are expecting the person to leave soon, or perhaps you hope the person will leave soon.
You might say, for example, “It’s still raining outside.” It has been raining in the past and continues to rain right now. You are perhaps hoping it will stop raining soon. In that very same situation you could say, “It’s not sunny yet. It’s still raining.” “Still” indicates the current situation, looking back. “Yet” indicates the current situation, looking to the future.
If you still have some questions about English, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2006 by the Center for Educational Development.
Glossary
employee – worker; someone who does work for another person or company and who gets paid money for doing that work
* When the company decided to expand, the first thing the manager did was hire new employees.
to waste time – to relax, especially when one is not supposed to be relaxing; to do something else instead of what one is supposed to be doing
* Even though Gwen needed to write a paper for her English class, she was wasting time by watching movies instead.
to kill time – to relax or spend time doing something when one is waiting for something else to happen
* The movie did not start for another two hours, so Fredrick killed time by reading a book.
blog – a personal website used to post or write comments about one's thoughts, experiences, and beliefs; a Web log or online journal that is available for others to read
* Emilia had an interest in photography, so she started a photography blog to show off her pictures and write about the things she learned about taking photos.
Hollywood – a neighborhood located in Los Angeles, California, where many movies are made; a general term used to describe the movie industry or movie business
* Dean dreamed of becoming an actor and going off to Hollywood.
beach – a large area covered with sand, where the ocean or another large area of water meets the land; seashore
* One of Qiana’s favorite hobbies is going to the beach and collecting seashells.
immigrant – someone who comes to live in a country after being born in and living in another country; someone who moves to a country even though he or she is originally from another country
* Roberto was born in the United States, but his great-grandfather was an immigrant from Guatemala.
to migrate – to move from one place to another, usually inside of one country; to travel from one place to another, often with the desire to live in that new place
* For generations, our family lived in Kansas, but gradually migrated north to Nebraska.
carpet – floor rug that covers the entire floor area; a large piece of soft, thick cloth or material that covers the entire floor for people to walk on
* Lula spilled wine on the carpet, leaving a large red stain on the floor.
call sign – a set of letters used to identify a television or radio station, usually consisting of four letters
* Why did the TV new station get the call sign KLOV?
International Telecommunications Union – an agency or group that creates rules and guidelines meant to control and organize the way that information is shared through electrical technology throughout countries from across the world
* The United Nations discussed the International Telecommunications Union’s suggestions on how to improve Internet security.
to divide up – to split into multiple parts or sections; to separate something into different parts, sometimes when those parts need to be shared with multiple people
* The friends divided up the pizza evenly so that each person got two slices.
yet – at the current moment, used when something has not happened but is expected to happen; up to a certain moment or time
* Even though Miriam was supposed to arrive at 7:00 a.m., it is 7:45 p.m. and she isn’t here yet.
still – at the current moment, used when something has been happening but is expected to end; remaining
* Irving was supposed to leave for work at 6:30 a.m., but it was 6:45 a.m. and he was still at home.
What Insiders Know
Polishing Your Internet Reputation
It’s very common these days to search the Internet to find out more about people and companies. Many people talk about “Googling” or searching for the name of someone or something they know. But what if there’s something on the Internet about you that you don’t want others to see?
No problem. There are businesses that claim they can “polish” or improve search results about you on the Internet, and improve your “reputation” (what others generally feel and think about you). These companies say that they can hide or make it more difficult for those negative search results to appear.
Here’s what they do: The company you hire creates hundreds of “links” (online connections) between third-party Websites and positive content or information about you or your business. This pushes your negative search results off the first page of results; most people don’t look beyond the first page of results. This is very “labor intensive,” which means it takes a lot of time and work and the service is not cheap.
Another less expensive service finds where the negative content is stored and asks that information to be removed. These services charge by the item.
This strategy or method doesn’t always work, however. In 1996, the U.S. passed a law called the Communications Decency Act, which says that “hosts” (owners) of a website are not responsible for what users post on that website. Since many people post “anonymously” (without using their real names), it is often difficult to find the person who wrote that post, or to convince the host to remove it.