= 1313
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café episode eight.
This is English as a Second Language Podcast’s English Café number eight. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. On this Café, we’re going to talk about two famous television celebrities in the United States. We’re also going to talk about a famous film festival, also here in the United States. And, as always, we’ll answer a few of your questions. Let’s get started.
Our first topic on this Café is two famous television celebrities. A “celebrity” (celebrity) is a person who becomes famous, usually for appearing on television or in a movie or as part of a famous musical group. The term “celebrity” can be applied to anyone who is both famous and who people like. If you go out and kill 50 people, you will be famous, but you will not really be a celebrity. A celebrity is someone who has fans – people who like him and what he does.
The two television celebrities we’re going to talk about on this Café both became famous on television, although neither one is an actor or singer. Let’s start with Dr. Philip McGraw, known by most Americans as simply “Dr. Phil” (Phil), which is short for “Philip.” Phil McGraw was born in 1950 in the state of Oklahoma, which is in the central part of the U.S. He attended, or went to school at, the University of Tulsa, which is also in Oklahoma. He had a scholarship to attend the university.
A “scholarship” (scholarship) is when the university or another organization gives you money to pay for your expenses at school. There are basically two kinds of scholarships: “academic scholarships,” for students who are smart and do well in school and “athletic scholarships,” for students who are good at one or more sports.
This may seem strange to people from other countries, but in the U.S., college sports are very important, and the university spends a lot of money on sports teams, including giving money to good athletes to come to the university and, in addition to studying there, play on a sports team. There are scholarships for football, baseball, basketball, hockey, swimming – even something called soccer, which I guess is popular in other countries too.
Phil McGraw went to the University of Tulsa on an athletic scholarship because he played football, and football is very, very popular in Oklahoma and states near Oklahoma, especially Texas. But McGraw got injured, got hurt, playing football and decided to focus his attention on his studies. He decided to study psychology, and after transferring, or moving, to another university (this time in Texas), he got his BA, or bachelor’s degree, in psychology in 1975.
He then went on to get a master’s degree and a PhD, or doctorate, in psychology and eventually started a company which did motivational seminars. These are meetings where people go to try to get motivated or really interested in accomplishing certain goals or objectives in life. So, Dr. McGraw worked as a professional psychologist for many years, but decided to do something different in 1989. He started a company called “Courtroom Sciences, Inc.,” or CSI. A “courtroom” (courtroom) is a place where you go if you have to participate in some sort of legal process or case.
What McGraw’s company did was give advice to lawyers on how to select and present evidence to jurors. A “juror” (juror) is a person who, along with usually 11 other jurors, decides whether a person is guilty or innocent. In the U.S., many legal cases are decided by this group of six or twelve people. We call these people “jurors,” and we call the group a “jury” (jury).
McGraw figured correctly that if lawyers understood the psychology of jurors – how people think and react to information – the lawyers could be more successful in their cases. They could win more cases. McGraw was right. He helped a group of lawyers win some very important cases, and suddenly lawyers from all over the country were interested in his company. In 1996, a famous television celebrity by the name of Oprah Winfrey was involved in a famous court case. Her lawyers went to McGraw and got his advice, and Oprah won her case.
Winfrey was, and still is, one of the most powerful people in American television, with her own television talk show. A “talk show” is where different people, mostly other celebrities, come and talk about their latest movie or book or song with the person who runs the show, called the “host” (host). Oprah was one of the most famous talk show hosts in America, at least in the 1990s.
Oprah – most people just call her by her first name – asked Dr. McGraw to come on her television program and talk about some common problems people have in their lives. People watching the show immediately fell in love with Dr. Phil’s straightforward, or direct, style of talking. He became so popular that he got his own television show where people would come on the show and talk about their marriage problems or their work problems or some other issue bothering them, and Dr. Phil would give them advice on how to solve their problems.
The show became a national hit, or success, and later Dr. Phil started writing books with advice on how to improve your marriage, do better at work, and so forth. We call these kinds of books “self-help” books, because instead of going to a professional psychologist or doctor, you read the books and help yourself. That’s what’s supposed to happen, anyway.
Another celebrity who became famous on television, and who is not an actor or performer, is Donald Trump. Donald Trump is a very rich businessman who is famous for owning several large buildings, especially on the East Coast of the U.S., in places such as New York City. Trump was born in 1946, the son of a rich businessman who made his money from the same place Trump was to make his money: real estate. The term “real estate” refers to land, homes, and buildings.
Trump made his money building – that is, constructing – and buying large buildings and casinos. “Casinos” (casinos) are places where you can gamble, or bet money to try to win more money. However, usually you lose your money in a casino. Trump is what we might call a “real estate magnate” (magnate). A “magnate” is a person, an important person, who has a lot of power in some particular field, some area of business.
Trump began writing books about how to make “deals,” or business agreements, to buy and sell things. These were basically advice books, similar to what Dr. Phil writes for people’s personal problems. So, people began to see Trump as an author – as a writer – as well as a businessman.
In 1996, Trump purchased, or bought, the Miss Universe Organization. The Miss Universe Organization, you probably know, holds beauty contests for typically young, very attractive women in many different countries, and then all of these beautiful women come together and judges pick the most beautiful woman in the world. I’m hoping one day to be a judge at the Miss Universe contest, but they haven’t asked me yet. I’m not sure why. I think I could do a very good job.
Back to our story, a few years later, in 2004, Trump got his own television show, what we would call a “reality” (reality) television show. A reality show is usually one in which there is some sort of contest or competition, and average people (who are many times really just out-of-work young actors – actors who don’t have a job – living here in Los Angeles) try to win some prize. Trump’s show was called The Apprentice.
An “apprentice” (apprentice) is someone who is learning a job or a professional trade from someone who is already an expert, or who already knows a lot about that particular kind of job. You normally have apprentices for jobs such as plumber (someone who fixes toilets and sinks) or carpenter (someone who makes things with wood and other similar jobs). But in Trump’s TV show The Apprentice, the person who wins the competition will become Trump’s apprentice in learning how to run a big business, especially a real estate business.
The show has a lot of different tasks, or things people have to do to prove that they know enough to be Trump’s apprentice. The show was very popular a few years ago, and Trump became a real television celebrity, especially for a phrase and expression that he always uses at the end of each show. At the end of each show, or each episode, Trump has to get rid of one of the contestants, the people trying to win the contest. He does this by saying to them, “You’re fired.”
If you are “fired” (fired), you lose your job. You are told you can no longer work for the company. Trump later had another similar program called Celebrity Apprentice. As the name suggests, this show had other famous people (although really people who used to be famous, but really weren’t famous anymore) competing against each other to win. The winners did not go on later to become Donald Trump’s apprentice, however.
Trump has written several books, but now that he is a celebrity, people have written books about him – what we call “biographies.” A “biography” (biography) is the story of someone’s life. If you write your own story, we would call that an “auto (auto) – biography.” Sometimes biographies are “authorized,” meaning the person cooperates with the book’s writer and gives him or her information. Sometimes, biographies are “unauthorized,” meaning the person who is being written about does not approve of the book or give the author any information.
A few years ago, someone wrote one of these unauthorized biographies about Trump, and Trump didn’t like it. In fact, he sued the writer for saying false things about him. “To sue” (sue) someone is to go to a court, to a judge, and ask for money from this person who you think did something wrong to you. How much did he sue this writer for? The answer is five billion dollars. That’s the number five followed by nine zeros. He did not win his lawsuit, however.
Our final topic is a famous film festival that was started by – who else? – another celebrity, this one by the name of Robert Redford. Unlike Dr. Phil and Donald Trump, Robert Redford really is an actor. A film or movie “festival” (festival) is an event usually held in one city over a period of seven to ten days, where lots of new films are shown – new movies are shown.
Film festivals typically invite people who make movies, along with critics, to see the new films. “Critics” (critics) are people who give their opinion about something that at least, in theory, they know something about. A “film critic” gives you his or her opinion about how good a movie is.
Most movies in the U.S. are made by what we would call large movie “studios.” “Studios” (studios) are filmmaking companies that typically have millions and millions of dollars to make movies, but some movies are made by small companies or even individuals. We call these kinds of movies “indie” films. “Indie” (indie) comes from the word “independent,” meaning here not connected to or run by the big movie studios.
Indie films typically are made on what we would call a “low budget” (budget). A “low budget” means you don’t spend a lot of money to make the movie. This is compared to movie studios who have big budgets, or lots of money to make movies. Most of the big movie studios are located here in Los Angeles. Los Angeles is sometimes called the entertainment capital of the world. That’s because many movie studios have their headquarters, or main offices, here.
The Sundance Film Festival was started in 1978, not here in Los Angeles, but in the state of Utah, which is in the western-central part of the U.S., next to the state of Nevada and not too far from California. The original idea of the Sundance film Festival was to give indie films a chance to be seen and also to promote or advertise Utah as a place where movie companies could go and make their movies.
Now, Robert Redford, this famous actor, also lived in Utah, and so the Utah Film Commission asked him to be the first chairman of this new film Festival. Redford said yes and started to raise, or get, money for the project. In 1980, in an attempt to get more people to go to the film festival, they moved the festival to Park City, Utah. Why Park City, Utah? Well, it’s near a ski resort, a place where you can ski down a mountain. The idea, I guess, was to get people to ski as well as to see a movie, but it was still difficult for the festival to make money.
So, in 1985 Robert Redford basically took over the organization, and by 1991 it came to be called the Sundance Film Festival. It has grown over the years in popularity and is now one of the most important film festivals in the U.S., especially for independent films. More than 200 movies are shown at the festival, so you can’t possibly see them all, even in the 10-day period when the festival is held.
Like many film festivals, there are prizes for the best movies. There are also workshops and seminars, meetings at the festival which are sort of like informal classes and discussions about things related to making movies. The festival is very popular, with nearly 50,000 people attending. I’ve never been there, but then again, I’m not a celebrity.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Yuta (Yuta) in Tokyo, Japan. Yuta wants to know the difference between the words “very” (very) and “really” (really). For example, what’s the difference between “It’s very nice” and “It’s really nice,” or between the phrase “I’m very sorry” and “I’m really sorry.”
Well, to be honest, there really isn’t a difference in meaning between “very” and “really” when used in those cases. People might consider “really” to be slightly more informal, but the reality is they’re very close in meaning, if not identical in meaning. “This is very, very nice of you” means the same as, “This is really, really nice of you.”
I suppose sometimes when someone is using the word “really,” they may be trying to express a situation which is greater than “very,” especially if they say it in a certain tone or a certain intonation. “I’m really, really happy to see you,” instead of “I’m very, very happy to see you.” “Really” when said in that way might indicate even more than “very, very happy.” However, in common usage, the two words, at least in these situations, mean the same thing.
Now, there are other uses of the word “really” that don’t relate to “very.” Sometimes we use the word “really” to mean “in fact” or “in truth.” “Did this happen? Did this really happen?” When you say, “Did this really happen?” you don’t mean, “Did this very happen?” That doesn’t make any sense. You mean, “Did it actually happen?” Did it, in reality, happen? So, in those instances you must use “really.” You can’t use “very.”
Another question comes from Cleotilde (Cleotilde), writing from France – near Paris, France, I believe. The question has to do with the difference between “pretty” (pretty) and “quite” (quite). “Pretty” and “quite” used as adverbs – that is, used to modify a verb – have slightly different meanings. If you say someone is “pretty good,” you mean that they are good, but they’re not great. If you say someone is “quite good,” you mean, in fact, they are very, very good. They are, we might say, “really good.”
So, if someone asks you, “How is that new restaurant you went to last night?” and you say, “Oh, it was pretty good,” you mean it was okay. It wasn’t great. It wasn’t the best restaurant you’ve ever eaten at. If, however, you say, “Oh, it was quite good,” you mean it was very, very good. It was excellent, perhaps. Those are the differences, then, between “pretty” and “quite” when used as adverbs.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2006 by the Center for Educational Development.
Glossary
television personality – a person or entertainer who became famous through appearing on television
* Lucille Ball and Desi Arnaz are Daisy’s favorite television personalities from the 1950s.
psychologist – someone with a Ph.D. degree in the science of mental health; an expert about the human mind, especially about the way the human mind controls behavior
* Earl met regularly with a psychologist to determine the cause and best treatment for his depression and anxiety.
festival – a big party or event held to celebrate something; a series or program of activities held to celebrate or honor someone or something
* Many bands and singers performing at the rock music festival last year.
critic – an expert who judges art, music, films, and other forms of creative work or entertainment and shares his or her opinion, usually in writing
* Book critics gave the book a poor review, because they said it was poorly written.
movie studio – film studio; a large organization or company that creates movies and makes those movies available to viewers
* The movie studio produced several movies last year, but none were very popular with audiences.
headquarters – the main office of a company; the office of a company that makes all of the important decisions for all of the other offices of that company
* A new statement came from headquarters stating that the company would change its focus from creating new products to selling its current ones.
indie – independent; when an entertainment product, such as music, movies, or books, is created by an individual or small group of people instead of a large, wealthy, and/or influential company
* Rina prefers listening to music produced by indie bands instead of popular singers supported by major record labels.
budget – a plan that one creates to determine how much money one can afford to spend on various tihngs
* Dewayne did not have a very large budget for his vacation and could only afford to eat out at cheap restaurants and stay at small budget hotels.
real estate – the land, homes, or buildings that one owns; lands and structures owned by someone or by a group of people
* Jo needs to talk to an agent who can help her sell her real estate properties.
magnate – an important person who has a lot of power or control over a certain field or region of business
* The real estate magnate owned 40 different apartment complexes.
apprentice – someone who is learning a job or professional trade from someone who is already skilled at that job
* The baker’s apprentice learned how to bake bread and make cakes from the bakery owner.
biography – the true story of someone's life; a story about the events that happened in one’s life, written by someone else
* There are multiple biographies written about George Washington from many notable historians.
to sue – to go to a court of law and demand money from someone who one believes has done something wrong, causing one harm
* Eustice sued his former employer because he believed that he was fired for unfair reasons.
very – extremely; a term used to stress the trueness of a specific quality
* Bridget was very happy to see a friend she had not seen in many years.
really – extremely; a term used to stress or emphasize the trueness of a specific quality, in a way that is more casual or more extreme than “very”
* Rashid was really upset when he did not get accepted to the college he wanted to attend.
pretty – a little; somewhat; to a small degree
* The lasagna was pretty good, but Shantelle had tasted better before.
quite – very; extremely; to a great degree
* The concert was quite good and was much better than Albert ever expected it to be.
What Insiders Know
English in Numbers
Every language expresses something about its culture through “proverbs and sayings” (traditional expressions or phrases). (Proverbs are traditional sayings that teach you something or give you some “wisdom: (wise or intelligent advice).) English has several sayings related to numbers and here are just a few.
- “Two’s company, three’s a crowd”: “Two’s company” means that when you have two people together, you will not be lonely. “Three’s a crowd” means that when you have three people, you have too many. This expression is usually said when two people, especially those romantically interested in each other, are suddenly joined by a third person, who now makes it more difficult for those two people to talk and spend time together. It is another way of telling someone to “get lost” (leave immediately)!
- “To be at sixes and sevens”: This expression means to be confused or to have a situation, which is “in disorder” (disorganized; not organized well). Like a lot of sayings, it is difficult to know exactly where the expression comes from. Some people believe it is related to a complicated dice game from England.
- “Dressed to the nines”: To be dressed to the nines means to be dressed very well, very formally, such as in a suit or a nice dress. Again, the “origin” (place where it came from) is somewhat “obscure” (not well known). One tradition says that it used to take nine yards of cloth to make a suit (yard = three feet).
- “The 11th hour”: To do something at the 11th hour means to do it at the last possible minute or time before it is too late, or before some “deadline” (time by which something must be completed). The expression probably comes from the Bible, from the Gospel of Matthew, chapter 20, where there is a “parable” (story used to teach) about “hiring” (asking someone to work for you) “laborers” (people who usually do physical work) at the end of a 12-hour workday.
- “The 19th hole”: The 19th hole is on a golf course, where golfers can go to get an alcoholic drink after they finish their game. As you probably know, golf is played by getting the ball into a small hole that is a long way away. There are 18 holes in a typical game of golf, so the “19th hole” is not part of the game, but a humorous way of referring to the bar where you go after you finish.