= 0054
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to EnglishPod! My name is Marco. +
E: And I’m Erica. +
M: And we’re gonna be looking at our fifth episode of our famous love story. +
E: Yes, I’m sorry I love you. +
M: I’m sorry I love you. +
E: Part five. +
M: Okay. Hehe. Part five. So if you haven’t listened to the first four I suggest you go do that 
first, because… +
E: You’re gonna be a little bit lost. +
M: But it’s getting really good. +
E: Yeah, and so so good that I don’t think we can even say what… +
M: What’s gonna happen next. Hehe. +
E: No, we can’t say what the key language is. +
M: Oh, yeah, we can’t preview anything because it’s… we want to surprise you. +
E: Yes. +
M: But we can tell you this, wha… what’s going on? +
E: Last time we saw Veronica and Steven, um, they broke up, right? +
M: Right. +
E: And Veronica was with her friend and feeling really terrible and then Steven suddenly 
came to sing a beautiful song. +
M: So this is continuing on that. +
E: Right. +
M: Okay. So let’s listen to the dialogue and then we’ll come back and talk about some of the 
difficult vocabulary you might find. +
A: Honey, of course I forgive you! I love you so much! 
I’ve really missed you. I was wrong to get upset
over nothing. +
B: I’m sorry I haven’t called or anything, but right af- 
ter you decided you wanted a break, I was called
up north to put out some major forest fires! I was
in the middle of nowhere, working day and night,
trying to prevent the blaze from spreading! It was
pretty intense. +
A: Oh, honey, I’m glad you’re okay! But I have some 
exciting news... I think I’m pregnant! +
B: Really? Wow, that’s amazing! This is great news! 
I’ve always wanted to be a father! We’ll go to the
doctor first thing in the morning! +
C: We have your test results back and, indeed, you 
are pregnant. Let’s see here... everything seems
to be in order. Your approximate due date is
October twenty-seventh two thousand and nine,
so that means that the baby was conceived on
February third, two thousand and nine. +
B: Are you sure? Are these things accurate? +
C: Well, yes sir, they are. +
A: What’s wrong? Why are you asking these ques- 
tions? +
B: This baby isn’t mine! I was away the first week of 
February at a training seminar! +
A: I... I... no, it can’t be... 
 
M: Alright, so more drama in our love story. +
E: Oh my god. +
M: Thing were going well and now more bad news. +
E: Yeah, or good news. +
M: Or good news. +
E: I… +
M: We’re not sure yet. +
E: Yeah. +
M: Okay, let’s take a look at the vocabulary first in “language takeaway”. +
Voice: Language takeaway. +
E: Well, we’re gonna looking four words now, um, the firs one, blaze. +
M: Blaze. +
E: Blaze. +
M: Blaze. +
E: So this noun is, um, another word for a fire, right? +
M: For a big fire. +
E: A really big fire. +
M: Uhu, the blaze. +
E: Uhu. +
M: So basically it’s like a flame of the fire. +
E: Yes, this one is a little bit difficult, so I think we can use some examples to show us how 
to use this word. +
Voice: Example one. +
A: The blaze is spreading quickly, we need to evacuate these people. +
Voice: Example two. +
B: We have to go in there and save those people from the blaze. +
M: Okay, so, it’s clear now, blaze. +
E: Uhu. +
M: Let’s look at our next word, conceived. +
E: Conceived. +
M: The past of conceive. +
E: Right, conceive. +
M: Conceive is a nice fancy word. +
E: Yes, and what does it mean, Marco? +
M: To create. +
E: Oh, like how you side stepped. +
M: So, it means to create. You can conceive a baby. +
E: Yes. +
M: You can conceive an idea. +
E: Yes. +
M: So, it basically means to create. +
E: Yes, um, most commonly with the baby, okay. +
M: Yeah, yeah, conceive. So, after the baby was conceived. +
E: Yep. +
M: We have a due date. +
E: Yes. +
M: We all know that it’s nine mounts later. +
E: Yes. +
M: Approximately. +
E: Yep, due date. +
M: So, the due date is the date of birth, basically. +
E: It’s the doctor’s guess when the birth would be. +
M: Would be. +
E: Yeah. +
M: Okay. +
E: When you go to the doctor and say "when will my baby be born", he’ll… he’ll say "well, 
your due date is… bla-bla-bla". +
M: Nine mounts latter. +
E: Yeah. +
M: Okay. And our last word in language takeaway, accurate. +
E: Accurate. +
M: Accurate. +
E: Accurate. +
M: Now, the due dates aren’t accurate. +
E: Right. +
M: That means they’re not one hundred percent sure. +
E: Uhu. +
M: Or precise. +
E: Yes. So, when something is accurate it’s absolutely certain. +
M: Absolutely precise. +
E: Yes. +
M: One hundred percent. Okay, so, accurate. Let’s listen to some more examples of how we 
can use accurate. +
Voice: Example one. +
A: A blood test is the most accurate way of finding out if you’re pregnant. +
Voice: Example two. +
B: These reports are not accurate, John. We checked and discovered a lot of mistakes. +
Voice: Example three. +
C: This new software helps us calculate costs in a very accurate way. +
M: With those examples I think we’re ready to listen to this dialogue again. This time we’re 
gonna slow it down, right? +
E: Yeah, in case you, um, were so shocked by what happened that you couldn’t follow. +
A: Honey, of course I forgive you! I love you so much! 
I’ve really missed you. I was wrong to get upset
over nothing. +
B: I’m sorry I haven’t called or anything, but right af- 
ter you decided you wanted a break, I was called
up north to put out some major forest fires! I was
in the middle of nowhere, working day and night,
trying to prevent the blaze from spreading! It was
pretty intense. +
A: Oh, honey, I’m glad you’re okay! But I have some 
exciting news... I think I’m pregnant! +
B: Really? Wow, that’s amazing! This is great news! 
I’ve always wanted to be a father! We’ll go to the
doctor first thing in the morning! +
C: We have your test results back and, indeed, you 
are pregnant. Let’s see here... everything seems
to be in order. Your approximate due date is
October twenty-seventh two thousand and nine,
so that means that the baby was conceived on
February third, two thousand and nine. +
B: Are you sure? Are these things accurate? +
C: Well, yes sir, they are. +
A: What’s wrong? Why are you asking these ques- 
tions? +
B: This baby isn’t mine! I was away the first week of 
February at a training seminar! +
A: I... I... no, it can’t be... 
 
M: Alright, so continuing on without drama, let’s take a look at some interesting phrases in 
“fluency builder”. +
Voice: Fluency builder. +
E: Well, we’ve got three phrases for you, um, the first one is the middle of nowhere. +
M: Middle of nowhere. +
E: Middle of nowhere. +
M: Middle of nowhere. +
E: This is, ah, kind of a funny one, but, um, I think if we listen to some examples, it will 
help us to understand the meaning of this phrase. +
Voice: Example one. +
A: We are in the middle of nowhere. How can we find our way back home? +
Voice: Example two. +
B: I was in the middle of nowhere, so I couldn’t even use my mobile phone. +
Voice: Example three. +
C: It takes me two hours to drive to your house. It’s in the middle of nowhere! +
M: Alright, so middle of nowhere, it means that you’re lost. +
E: Yeah, you’re in a… in a place with no cities or people or anything nearby. +
M: Okay, so… just imagine yourself in the dessert. That would be the middle of nowhere. +
E: Yes, or, ah, in Canada. +
M: In Canada. Hehe. +
E: That would be the middle of nowhere. +
M: Alright, let’s take a look at our next phrase, first thing in the morning. +
E: First thing in the morning. +
M: First thing in the morning. +
E: First thing in the morning. +
M: So, when we talk about the first thing it means… +
E: Really really early in the morning. +
M: Really early. +
E: Yep. +
M: So. I can change it a little bit and say, first thing in the afternoon. +
E: Early in the afternoon. +
M: Or first thing tomorrow morning. +
E: Right. +
M: Right? +
E: So, really early tomorrow. +
M: Okay. So, it’s a very common way of referring to "very early". +
E: Yeah, it’s not like… first thing in the morning is like six o’clock in the morning, right? +
M: Right. +
E: But if you say "okay, I’ll take care of that first thing in the morning", you’ll do it right 
away in the morning. +
M: Right away. +
E: Uhu. +
M: Right when you get to the office ???. +
E: Right. +
M: Okay. Let’s look at our last phrase, seems to be in order. +
E: Seems to be in order. +
M: Everything seems to be in order. +
E: Uhu, so, everything is okay, everything’s normal. +
M: Everything seems to be normal. +
E: Yep. +
M: Everything looks okay. +
E: Yes. +
M: So, this is a very common phrase when… people check your documents… +
E: Aha, yeah, that’s true. +
M: Or the reports. +
E: Yep. +
M: Ah, they’ll say "okay, all the papers seem to be in order". +
E: Uhu. +
M: Very common. +
E: Yes, good news when you pregnant that everything seems to be in order. +
M: Exactly. +
E: Yeah. +
M: Everything is normal. Alright, so let’s listen to this dramatic dialogue one more time and 
we’ll come back and talk some more. +
A: Honey, of course I forgive you! I love you so much! 
I’ve really missed you. I was wrong to get upset
over nothing. +
B: I’m sorry I haven’t called or anything, but right af- 
ter you decided you wanted a break, I was called
up north to put out some major forest fires! I was
in the middle of nowhere, working day and night,
trying to prevent the blaze from spreading! It was
pretty intense. +
A: Oh, honey, I’m glad you’re okay! But I have some 
exciting news... I think I’m pregnant! +
B: Really? Wow, that’s amazing! This is great news! 
I’ve always wanted to be a father! We’ll go to the
doctor first thing in the morning! +
C: We have your test results back and, indeed, you 
are pregnant. Let’s see here... everything seems
to be in order. Your approximate due date is
October twenty-seventh two thousand and nine,
so that means that the baby was conceived on
February third, two thousand and nine. +
B: Are you sure? Are these things accurate? +
C: Well, yes sir, they are. +
A: What’s wrong? Why are you asking these ques- 
tions? +
B: This baby isn’t mine! I was away the first week of 
February at a training seminar! +
A: I... I... no, it can’t be... 
 
E: Well, Marco, um, what do you think about the situation? Wha… what would you do if you 
were this guy? +
M: It’s complicated. +
E: I know. +
M: Ah, I don’t know what I would do. It seems like something, ah, very typical of soap 
operas. +
E: Yes. +
M: Hehe. Well, I don’t know because she didn’t really deny it… +
E: Uhu. +
M: In the end. She didn’t say, no, right away. +
E: Yeah, and… but she didn’t say like… oh. +
M: Yeah, she didn’t really accept it. +
E: Yeah. +
M: So, it still a little bit difficult to see if maybe she cheated on him. +
E: Yes. +
M: Or something. +
E: Hey, guys, what do you think? Do you think Veronica cheated on Steven? +
M: Do you think is his baby? Maybe it’s not. Maybe the doctor is wrong. +
E: Maybe it’s the doctor’s baby. +
M: Maybe it’s… Hehe. +
E: Hehe. +
M: Anything could happen here at EnglishPod, so send us your ideas and tell us what you 
think happens next… Ah, come to englishpod.com where you can leave your questions,
your comments. +
E: Yeah, and Marco and I are always around to, ah, answer your questions, respond your 
comments. +
M: Exactly and we want to know what you think will happen next. +
E: Yes. +
M: Alright guys, so until next time… Bye! +
E: Bye! 
 
