= 0068
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Welcome back English learners! My name is Marco. And I’m joined here by the lovely… +
E: Erica. +
M: And today we’re gonna be bringing you another great lesson. One of the lessons that 
you requested. +
E: Yes, that’s right, actually Maxim, Maxim_s requested this one. +
M: Right, ah, I think he’s really into research and investigation, so, we’re bringing you a 
great lesson about this topic. +
E: Okay, so, I’m really excited to hear this dialogue all about research. So, why don’t we 
start listening to two university professors discussing an important question? +
A: We’ve been over this a thousand times. The data 
is irrefutable! Look, we’ve done extensive re-
search, built studies, and read the literature, and
there is conclusive evidence to support my theory! +
B: Horowitz, I beg to differ. Even in your most recent 
study, the investigative approach was flawed! You
know as well as I do that the collection of data
was not systematic, and there is a large margin
of error. To draw a definitive conclusion based on
that data would be misleading +
A: That is preposterous! +
B: You are trying to single-handedly solve one of the 
world’s greatest mysteries, and yet you are oblivi-
ous to the fact that you are wrong! +
A: I am not wrong! The chicken came first! +
B: No! The egg came first! 
 
M: Alright, so, interesting. Which came first, the chicken or the egg? +
E: It’s an age-old question, isn’t it? +
M: Hehe. And, apparently, they’re not going to agree any time soon. [NOTE: any time 
soon = in the near future] +
E: Alright, well, what they can agree about is this awesome language. So, why don’t we 
take a look at it now in “language takeaway”? +
Voice: Language takeaway. +
M: Okay, on Language takeaway today we have some really great words. And this first one 
is really good, irrefutable. +
E: Irrefutable. +
M: Irrefutable. +
E: The data is irrefutable. +
M: Okay, so, if the professor says, that the data is irrefutable, what does… what does he 
mean by that? +
E: He’s… he’s saying that “you cannot deny it”, “it is really really true”. +
M: It is really true, “there is no way this is a lie”. +
E: Exactly. +
M: Okay, irrefutable evidence, for example. +
E: Yeah, that’s a great phrase. Alright, so, the professor complained that Dr. Horowitz’s 
experiment was flawed. +
M: Flawed. +
E: Flawed. +
M: So, flawed. Is that an adjective or a verb or a noun? +
E: Hm, it is an adjective… +
M: Okay. +
E: Here. Now, when something is flawed, there is a problem with it, right? +
M: Okay, so, it has… +
E: Is a Mistake. +
M: An error. +
E: Yeah. +
M: Okay. So, this adjective is a way of saying that his experiment has a flaw. +
E: A mistake, exactly. +
M: A mistake. So, flawed is the adjective of a flaw. +
E: Right. +
M: Okay. +
E: Now, the reason that his study or his experiment was flawed is because that it was not 
systematic. +
M: Systematic. +
E: Systematic. +
M: So, systematic, that’s an interesting word. +
E: Uhu. Now, I think we can recognize the word system in here, right? +
M: Uhu, right. +
E: So, when something is systematic, it follows a process. +
M: A certain order. +
E: Yes, a certain system. +
M: Right, so that’s basically what systematic means “to follow a certain order”, “to be more 
organized”, right? +
E: Exactly, yeah. +
M: Okay. And what about our next word? +
E: Preposterous. +
M: Preposterous. +
E: Preposterous. +
M: That is preposterous. +
E: I love this phrase. +
M: It go… it usually goes together, right? That is preposterous. +
E: Yep. +
M: Okay, so… what does that mean when I say that? +
E: It means it’s… it’s absurd, it’s… it’s ridiculous. +
M: Right, it… it doesn’t make sense. +
E: Uhu. +
M: I can’t believe you said that. +
E: Alright, well, this is a really interesting phrase, um, but it… I think it’s a little bit more 
common, um, when it’s used by older people. +
M: Yeah, I… I don’t think… I don’t really see a young person going up to, ah, someone and 
say “hey, that’s preposterous”. +
E: Yep, but it is a wonderful phrase. +
M: Uhu. +
E: Now, our final phrase for takeaway, oblivious. +
M: Oblivious. +
E: You’re oblivious to the fact. +
M: Uhu. So, a person that is oblivious to something… +
E: They don’t know or they’re… they’re unaware. +
M: Okay, so, they ignore maybe the facts or… +
E: Exactly. +
M: They don’t see it. +
E: Yeah, “you’re oblivious to the fact that we’re in a recession”. +
M: Okay, or “he is completely oblivious”. +
E: Uhu. +
M: You can just say like that, right? +
E: Yep, he doesn’t know. +
M: Uhu. Okay, so, we took a look at some of the great vocabulary we found in the dialogue, 
but there’re also some really good phrases that, I think, we should look at. +
E: Okay, and let’s take a look at those in “putting it together”. +
Voice: Putting it together. +
E: You know, Marco, one of the things I love about English is the way that, ah, words seem 
to fit together like… like blocks coming together. And here we have a lot of great examples
of these words that fit together really nicely. Okay, so, why don’t we look at those, um, and
our first one now is extensive research. +
M: Extensive research. +
E: Extensive research. +
M: Alright, so, we know extensive means… +
E: A lot. +
M: A lot. +
E: Yeah. +
M: So, that’s really good when you put it together… extensive research. It means you 
have… +
E: A l… a lot of research. +
M: You have really studied. You have really looked things up. +
E: Uhu. +
M: Okay, extensive research. +
E: Another great research-related phrase here is conclusive evidence. +
M: Conclusive evidence. +
E: Conclusive evidence. +
M: Alright, now, the first word there, conclusive. +
E: When something is conclusive, you can’t argue with that. It’s… it’s the final decision. 
Alright, well, the professor complained that Horowitz’s… that Horowitz’s investigative
approach was flawed, right? +
M: Uhu. +
E: So, this is our next phrase, investigative approach. +
M: Investigative approach. +
E: Investigative approach. +
M: Okay, so, I remember the word investigate is a verb. +
E: Yes. +
M: But in this case it’s a… +
E: It’s an adjective. +
M: It’s an adjective. +
E: When something is investigative, it’s obviously having to do with… +
M: An investigation. +
E: Uhu. +
M: So, the approach or the… so, when he said “investigative approach”… +
E: Just a… I mean, just simply the way you investigate… +
M: Okay, the w… +
E: The problem. +
M: The way he investigate it. Okay, very interesting. What about this other phrase that I 
saw? It was really interesting, definitive conclusion. +
E: Definitive conclusion. +
M: So, a definitive conclusion. +
E: Alright, well, again, I think we know the word conclusion, right? +
M: Okay. +
E: So, it’s a final judgment or decision. +
M: Alright. +
E: When something is definitive, you can’t argue with it or change it. +
M: Okay, so, the conclusion or wha… the… the final… result… +
E: Uhu. +
M: Is… is final, like there is no way of arguing it. +
E: Exactly. +
M: Okay. +
E: Alright. +
M: Definitive conclusion. +
E: This is some great language. So, why don’t we listen to it one more time in the dialogue? +
A: We’ve been over this a thousand times. The data 
is irrefutable! Look, we’ve done extensive re-
search, built studies, and read the literature, and
there is conclusive evidence to support my theory! +
B: Horowitz, I beg to differ. Even in your most recent 
study, the investigative approach was flawed! You
know as well as I do that the collection of data
was not systematic, and there is a large margin
of error. To draw a definitive conclusion based on
that data would be misleading +
A: That is preposterous! +
B: You are trying to single-handedly solve one of the 
world’s greatest mysteries, and yet you are oblivi-
ous to the fact that you are wrong! +
A: I am not wrong! The chicken came first! +
B: No! The egg came first! 
 
M: So, an interesting question. What do you think? What came first the chicken or the 
egg? +
E: Well, if you ask me, it was the egg. +
M: It was the egg? +
E: Yeah. +
M: Interesting. What about why did the chicken cross the road? +
E: To get to the other side. +
M: Do you think that’s really the reason? +
E: Well, there’s a million different reasons. But this is great. I’m glad you brought that up, 
cause this is like the classic English joke. +
M: Hehe. The classic English joke, right? Why did the chicken cross the road? And the 
answer’s always… +
E: Well, there are a million answers… So, do you guys know any chicken jokes? +
M: Yeah, why don’t you come to our website englishpod.com and on the 'comment 
section', why don’t you leave us your thoughts on what came first the chicken or the egg?
And why do you think the chicken crossed the road? +
E: Alright, we will really look forward to hearing your ideas and, um, Marco and I will be 
around to answer your questions. So, I think we’re out if time for today, but thanks for
listening and… +
M: We’ll see you there. +
E: Good bye! +
M: Bye! 
 
