= 0085
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to EnglishPod! My name is Marco. +
E: And I’m Erica. +
M: And today we’re bringing you another lesson on our sports series. +
E: Uhu. We’re talking about baseball today. +
M: Baseball – the American national pastime. [NOTE: pastime = an activity or 
entertainment that makes time pass pleasantly] +
E: Is it? +
M: Yes, it is. +
E: Okay. +
M: So, we’re gonna be looking at this interesting sport that is played mainly in the 
Caribbean and, well, it’s actually very popular in the United States and Japan. +
E: That’s right. +
M: Korea. +
E: Yeah. So, we’re not only gonna learn a bunch of baseball language, but we’re also going 
to see how baseball has a big influence on English in general. [NOTE: a bunch of something
= a lot of something] +
M: That’s right, so, we’re gonna learn a lot of great things today. So, why don’t we start and 
listen to our dialogue? +
A: Hello baseball fans, and welcome back to today’s 
game! My name is Rick Fields and of course, I
am here, once again, with the man that seals the
deal, Bob Copeland. +
B: It’s a beautiful day to see two world class teams 
face each other and fight for their right to be called
champions. +
A: Well, the national anthem has just been sung, and 
the umpire has started the game. It’s time to play
ball! +
B: Roger Vargas is up at bat. The pitcher winds up 
and strike one! +
A: A very nice curve ball by the pitcher. The catcher 
gives him the sign, he winds up and Vargas gets
a line drive! +
B: The players are scrambling to get the ball. Vargas 
gets to first base and he’s still going! The out-
fielder throws it to second! Vargas slides! He’s
safe! +
A: Great play! +
B: We have a runner on third and up at bat is Brian 
Okami! There’s the pitch, he hits it! It’s going,
going, that ball is gone! +
A: Home run by Okami! That puts this team ahead 
by two as we are at the bottom of the fifth inning
here at Richie Stadium! +
E: Alright, well, a pretty exiting game there at Richie Stadium +
M: Exactly, and we have some interesting players: Roger Vargas and Brian Okami. +
E: Uhu. +
M: Alright, so, well, we saw some great words and, well, it’s time for us to take a look at 
them now in “language takeaway”. +
Voice: Language takeaway. +
E: Okay, we’re gonna look at some, uh, common sports and baseball words here. And the 
first phrase – we’ll hear this almost at any sort of international sports event, right? +
M: Exactly, and it’s the national anthem. +
E: National anthem. +
M: National anthem. +
E: So, this is a song, right? +
M: Exactly, it’s the song that you sing about your country. And many people confuse it, 
right? +
E: Yeah, a lot of people might say “national hymn”. +
M: Okay, hymn. Because in some languages it might be like a hymn. +
E: Uhu. +
M: Like literally translating. +
E: Yeah +
M: But in English it’s called the national anthem. +
E: The national anthem. +
M: Alright. So, what about our next word? +
E: Well, we were talking about the pitcher. +
M: Pitcher. +
E: P-I-T-C-H-E-R. +
M: The pitcher. +
E: Pitcher. +
M: Okay, and now this is one of the players on a baseball team. And his job is to… +
E: To throw the ball. +
M: To throw the ball really fast. +
E: So that the guy can’t hit it with the bat. +
M: Okay, so, that’s the pitcher. +
E: Uhu. +
M: Now, the interesting thing is that the baseball commentator said “the pitcher winds up”. +
E: Winds up. +
M: To wind up +
E: To wind up. Okay, well, let me paint you a picture. +
M: Okay. +
E: So, imagine a clock. +
M: Aha. +
E: And you’re turning, turning and turning the clock to wind it up, to get it ready to go. +
M: To make it work. +
E: Exactly. +
M: Uhu. +
E: So, imagine the pitcher doing the same sort of a thing – bringing his arm back behind 
them, getting ready to throw the ball. +
M: Okay, so, that is to wind up. +
E: Uhu. +
M: Very good. So, you can use this word not only in baseball, but for other things that 
require you to do this action. +
E: Right, to turn something and get it… get it ready to have lots of power. +
M: Like some toys. +
E: Yeah. +
M: Or maybe like a m… a music box. +
E: Uhu. +
M: Okay, wind up. What about our next phrase? +
E: Well, Roger Vargas hit a line drive. +
M: Line drive. +
E: Line drive. +
M: Okay, so, what is a line drive? +
E: Well, it’s a term from baseball and when you hit a line drive, you hit the ball sort of low… +
M: Uhu. +
E: On towards the ground and it… it travels along the outside of the field. +
M: Right, so, the ball basically travels along the foul line. +
E: Uhu, the white line. +
M: The white line. +
E: Yeah. +
M: Exactly. Very good, so, that’s a line drive. +
E: And, so, the players on the field were scrambling to get the ball. +
M: Scrambling. +
E: Scrambling. +
M: Now, we know scrambled eggs form one of our lessons. +
E: Yes, uh, but the verb to scramble means to, um, move quickly in a disorganized way to 
do something. +
M: Okay, so, the players are moving very fast, trying to get the ball, but they’re not dong it 
very well. +
E: Right. And you can use this other ways, right? Not just in baseball. +
M: Right, for example, we can say “the people are scrambling to buy their tickets for the 
concert”. +
E: Yeah, or I’m going on vacation tomorrow and I’m scrambling to get everything ready. +
M: Exactly, it’s a very good term that you can use also in your daily life. +
E: Exactly. +
M: Alright. And what about our last word for today on language takeaway? +
E: Well, they were in the fifth inning of the game. +
M: Okay, so, inning. +
E: Inning. +
M: Inning. +
E: Alright, this is another baseball term. +
M: Uhu. +
E: And, um, it… it just means the period of play. +
M: Okay, so, we learned, for example, that in soccer you have two halves. +
E: Uhu. Or in hockey, you have three periods. +
M: Alright. And in baseball you have nine innings. +
E: Okay, great, so, some interesting sports and baseball vocabulary. Now, I think it’ll help 
us to hear this again slower. So, let’s listen to the dialogue. +
A: Hello baseball fans, and welcome back to today’s 
game! My name is Rick Fields and of course, I
am here, once again, with the man that seals the
deal, Bob Copeland. +
B: It’s a beautiful day to see two world class teams 
face each other and fight for their right to be called
champions. +
A: Well, the national anthem has just been sung, and 
the umpire has started the game. It’s time to play
ball! +
B: Roger Vargas is up at bat. The pitcher winds up 
and strike one! +
A: A very nice curve ball by the pitcher. The catcher 
gives him the sign, he winds up and Vargas gets
a line drive! +
B: The players are scrambling to get the ball. Vargas 
gets to first base and he’s still going! The out-
fielder throws it to second! Vargas slides! He’s
safe! +
A: Great play! +
B: We have a runner on third and up at bat is Brian 
Okami! There’s the pitch, he hits it! It’s going,
going, that ball is gone! +
A: Home run by Okami! That puts this team ahead 
by two as we are at the bottom of the fifth inning
here at Richie Stadium! +
M: Alright, so, as we said, there’re a lot of English terms that come form baseball, but we 
use them in business context or in your daily life, right? +
E: Yeah, why don’t we look at those now in “fluency builder”? +
Voice: Fluency builder. +
M: Alright, so, the first phrase that we have is up to bat. +
E: Up to bat. +
M: Up to bat. +
E: So, literally in this dialogue it means the guy is standing on home plate ready to hit the 
ball, right? +
M: Right. He has the bat and he’s ready to hit it. +
E: But what about in other contexts? +
M: So, for example, you can be at a meeting. +
E: Uhu. +
M: And maybe it’s your turn to talk. +
E: So, you’re up to bat. +
M: So, the b… yeah, exactly. Your boss will say “okay, Erica, you’re up to bat”. +
E: Okay, so, it means sort of like it’s your tern. +
M: It’s your turn. +
E: Yeah. +
M: Very good. +
E: Uhu. +
M: Alright, so, that’s another term that is used in baseball, but very commonly used in other 
circumstances. +
E: So, we also saw, um, in the dialogue that Roger Vargas, um… he hit the ball, but he 
missed and that was strike one. +
M: Right. Strike one. +
E: Uhu. +
M: So, in baseball you have three strikes. +
E: Three tries. +
M: Three tries before you’re out. +
E: Yes. +
M: And, so, now the same thing happens in daily life. +
E: So, um, if someone says “that was strike one”. +
M: It means you made the first mistake. +
E: Yes, and if you make two more, you will be fired, for example. +
M: Maybe. +
E: Yeah. +
M: Aha. Or maybe your parents will say “okay, you… that wasn’t nice, strike one”. +
E: And then two more times and you’ll have a time out. [NOTE: a time out = sort of a 
punishment when a child must stop playing for a while] +
M: Or you’ll be grounded. [NOTE: to be grounded = sort of a punishment when a child 
must stay home for a certain period of time; i.e. they can’t go out and hang out with their
friends] +
E: Yes. +
M: Okay, so, that’s also called a strike. And the pitcher threw a curve ball. +
E: A curve ball. +
M: Curve ball. +
E: So, okay, pretty clear. A curve ball is when you throw the ball and it sort of goes on a 
curve, it doesn’t goes straight, right? +
M: Right, exactly. +
E: But how can this be used outside of baseball? +
M: So, you can say “oh, my boss threw me a curve ball today”. +
E: So, he gave you an unexpected problem. +
M: Aha, or something that was difficult to handle. +
E: Okay, um, this one is pretty interesting. I’d like to hear a few more examples. +
Voice: Example one. +
A: My boss threw me a curve ball today, so I have to stay in work late. +
Voice: Example two. +
B: It was a huge curve ball when she asked me how many kids I wanted to have. How am I 
supposed to know? +
M: Alright, so, that’s basically a curve ball. You can say a non-expected problem… +
E: Yeah. +
M: Or situation. +
E: That’s right. +
M: And our last phrase - and, well, probably one that’s you already know – home run. +
E: A home run. +
M: A home run. +
E: From baseball we know that that’s when you hit the ball really far. +
M: And you hit it outside of the… of the playing area or outside the park. +
E: Yes. +
M: And now if you use it a business context or in your daily life… +
E: Uhu. It means something similar. Why don’t we take a listen to the examples and see if 
we can figure it our. +
Voice: Example one. +
A: Great job on that sales presentation. You really hit a home run. +
Voice: Example two. +
B: Our sales team hit a home run this month by doubling our revenue. +
M: Okay, so, basically, a home run is a success. +
E: A victory. +
M: A victory. +
E: Yeah, something a big accomplishment. +
M: That’s right. So, we’ve seen a lot of these great phrases and as you can see a lot of 
them from baseball are used in your daily life and there many, many more. +
E: Okay, well, why don’t we hear them again in the baseball context and we listen to the 
dialogue one more time? +
A: Hello baseball fans, and welcome back to today’s 
game! My name is Rick Fields and of course, I
am here, once again, with the man that seals the
deal, Bob Copeland. +
B: It’s a beautiful day to see two world class teams 
face each other and fight for their right to be called
champions. +
A: Well, the national anthem has just been sung, and 
the umpire has started the game. It’s time to play
ball! +
B: Roger Vargas is up at bat. The pitcher winds up 
and strike one! +
A: A very nice curve ball by the pitcher. The catcher 
gives him the sign, he winds up and Vargas gets
a line drive! +
B: The players are scrambling to get the ball. Vargas 
gets to first base and he’s still going! The out-
fielder throws it to second! Vargas slides! He’s
safe! +
A: Great play! +
B: We have a runner on third and up at bat is Brian 
Okami! There’s the pitch, he hits it! It’s going,
going, that ball is gone! +
A: Home run by Okami! That puts this team ahead 
by two as we are at the bottom of the fifth inning
here at Richie Stadium! +
M: Alright, so, an interesting dialogue; a very interesting sport. +
E: Uhu. +
M: And, well, personally I never played this as a child. +
E: Uh, me neither, really. +
M: I don’t really like it too much, but it is kind of fun to… go to a game and especially in the 
United States have those hot dogs and all that stuff. +
E: Okay, yeah. +
M: Hehe. +
E: Well, a cultural event; a really important piece of American culture. +
M: Exactly. So, well, we encourage you to come to our website englishpod.com; tell us 
what you think and also, of course, if you have questions or doubts, be sure to tell us. +
E: If you have any other sort of baseball-related phrases, let us know about them on the 
website. +
M: Okay, so, we’ll see you guys there. +
E: Thanks for downloading and until next time… Good bye! +
M: Bye! 
 
