
= 002-1 (pure) The Pre-Revolutionary Period and the Roots of the American Political Tradition 革命前时期与美国政治传统的根源
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css


'''


[.my1]
.案例
====
== Learning Objectives


By the end of this section, you will be able to:


* Identify the origins of the core values in American political thought, including ideas regarding representational government
* Summarize Great Britain’s actions leading to the American Revolution


====


American political ideas regarding liberty and self-government did not suddenly emerge full-blown at the moment the colonists declared their independence from Britain. The varied strands of what became the American republic had many roots, reaching far back in time and across the Atlantic Ocean to Europe. Indeed, it was not new ideas but old ones that led the colonists to revolt and form a new nation.



== POLITICAL THOUGHT IN THE AMERICAN COLONIES


The beliefs and attitudes that led to the call for independence had long been an important part of colonial life. Of all the political thinkers who influenced American beliefs about government, the most important is surely John Locke (Figure 2.2). The most significant contributions of Locke, a seventeenth-century English philosopher, were his ideas regarding the relationship between government and natural rights, which were believed to be God-given rights to life, liberty, and property.







Figure 
2.2
 
John Locke was one of the most influential thinkers of the Enlightenment. His writings form the basis for many modern political ideas.

Locke was not the first Englishman to suggest that people had rights. The British government had recognized its duty to protect the lives, liberties, and property of English citizens long before the settling of its North American colonies. In 1215, King John signed Magna Carta—a promise to his subjects that he and future monarchs would refrain from certain actions that harmed, or had the potential to harm, the people of England. Prominent in Magna Carta’s many provisions are protections for life, liberty, and property. For example, one of the document’s most famous clauses promises, “No freemen shall be taken, imprisoned . . . or in any way destroyed . . . except by the lawful judgment of his peers or by the law of the land.” Although it took a long time for modern ideas regarding due process to form, this clause lays the foundation for the Fifth and Sixth Amendments to the U.S. Constitution. While Magna Carta was intended to grant protections only to the English barons who were in revolt against King John in 1215, by the time of the American Revolution, English subjects, both in England and in North America, had come to regard the document as a cornerstone of liberty for men of all stations—a right that had been recognized by King John I in 1215, but the people had actually possessed long before then.


The rights protected by Magna Carta had been granted by the king, and, in theory, a future king or queen could take them away. The natural rights Locke described, however, had been granted by God and thus could never be abolished by human beings, even royal ones, or by the institutions they created.


So committed were the British to the protection of these natural rights that when the royal Stuart dynasty began to intrude upon them in the seventeenth century, Parliament removed King James II, already disliked because he was Roman Catholic, in the Glorious Revolution and invited his Protestant daughter and her husband to rule the nation. Before offering the throne to William and Mary, however, Parliament passed the English Bill of Rights in 1689. A bill of rights is a list of the liberties and protections possessed by a nation’s citizens. The English Bill of Rights, heavily influenced by Locke’s ideas, enumerated the rights of English citizens and explicitly guaranteed rights to life, liberty, and property. This document would profoundly influence the U.S. Constitution and Bill of Rights.


American colonists also shared Locke’s concept of property rights. According to Locke, anyone who invested labor in the _commons_—the land, forests, water, animals, and other parts of nature that were free for the taking—might take as much of these as needed, by cutting trees, for example, or building a fence around a field. The only restriction was that no one could take so much that others were deprived of their right to take from the commons as well. In the colonists’ eyes, all free White males should have the right to acquire property, and once it had been acquired, government had the duty to protect it. (The rights of women remained greatly limited for many more years.)


Perhaps the most important of Locke’s ideas that influenced the British settlers of North America were those regarding the origins and purpose of government. Most Europeans of the time believed the institution of monarchy had been created by God, and kings and queens had been divinely appointed to rule. Locke, however, theorized that human beings, not God, had created government. People sacrificed a small portion of their freedom and consented to be ruled in exchange for the government’s protection of their lives, liberty, and property. Locke called this implicit agreement between a people and their government the social contract. Should government deprive people of their rights by abusing the power given to it, the contract was broken and the people were no longer bound by its terms. The people could thus withdraw their consent to obey and form another government for their protection.


The belief that government should not deprive people of their liberties and should be restricted in its power over citizens’ lives was an important factor in the controversial decision by the American colonies to declare independence from England in 1776. For Locke, withdrawing consent to be ruled by an established government and forming a new one meant replacing one monarch with another. For those colonists intent on rebelling, however, it meant establishing a new nation and creating a new government, one that would be greatly limited in the power it could exercise over the people.


The desire to limit the power of government is closely related to the belief that people should govern themselves. This core tenet of American political thought was rooted in a variety of traditions. First, the British government did allow for a degree of self-government. Laws were made by Parliament, and property-owning males were allowed to vote for representatives to Parliament. Thus, Americans were accustomed to the idea of representative government from the beginning. For instance, Virginia established its House of Burgesses in 1619. Upon their arrival in North America a year later, the English Separatists who settled the Plymouth Colony, commonly known as the Pilgrims, promptly authored the Mayflower Compact, an agreement to govern themselves according to the laws created by the male voters of the colony.1 By the eighteenth century, all the colonies had established legislatures to which men were elected to make the laws for their fellow colonists. When American colonists felt that this longstanding tradition of representative self-government was threatened by the actions of Parliament and the King, the American Revolution began.



== THE AMERICAN REVOLUTION


The American Revolution began when a small and vocal group of colonists became convinced the king and Parliament were abusing them and depriving them of their rights. By 1776, they had been living under the rule of the British government for more than a century, and England had long treated the thirteen colonies with a degree of benign neglect. Each colony had established its own legislature. Taxes imposed by England were low, and property ownership was more widespread than in England. People readily proclaimed their loyalty to the king. For the most part, American colonists were proud to be British citizens and had no desire to form an independent nation.


All this began to change in 1763 when the Seven Years War between Great Britain and France came to an end, and Great Britain gained control of most of the French territory in North America. The colonists had fought on behalf of Britain, and many colonists expected that after the war they would be allowed to settle on land west of the Appalachian Mountains that had been taken from France. However, their hopes were not realized. Hoping to prevent conflict with Indian tribes in the Ohio Valley, Parliament passed the Proclamation of 1763, which forbade the colonists to purchase land or settle west of the Appalachian Mountains.2


To pay its debts from the war and maintain the troops it left behind to protect the colonies, the British government had to take new measures to raise revenue. Among the acts passed by Parliament were laws requiring American colonists to pay British merchants with gold and silver instead of paper currency and a mandate that suspected smugglers be tried in vice-admiralty courts, without jury trials. What angered the colonists most of all, however, was the imposition of direct taxes: taxes imposed on individuals instead of on transactions.


Because the colonists had not consented to direct taxation, their primary objection was that it reduced their status as free men. The right of the people or their representatives to consent to taxation was enshrined in both Magna Carta and the English Bill of Rights. Taxes were imposed by the House of Commons, one of the two houses of the British Parliament. The North American colonists, however, were not allowed to elect representatives to that body. In their eyes, taxation by representatives they had not voted for was a denial of their rights. Members of the House of Commons and people living in England had difficulty understanding this argument. All British subjects had to obey the laws passed by Parliament, including the requirement to pay taxes. Those who were not allowed to vote, such as women and Black people, were considered to have virtual representation in the British legislature; representatives elected by those who could vote made laws on behalf of those who could not. Many colonists, however, maintained that anything except direct representation was a violation of their rights as English subjects.


The first such tax to draw the ire of colonists was the Stamp Act, passed in 1765, which required that almost all paper goods, such as diplomas, land deeds, contracts, and newspapers, have revenue stamps placed on them. The outcry was so great that the new tax was quickly withdrawn, but its repeal was soon followed by a series of other tax acts, such as the Townshend Acts (1767), which imposed taxes on many everyday objects such as glass, tea, and paint.


The taxes imposed by the Townshend Acts were as poorly received by the colonists as the Stamp Act had been. The Massachusetts legislature sent a petition to the king asking for relief from the taxes and requested that other colonies join in a boycott of British manufactured goods. British officials threatened to suspend the legislatures of colonies that engaged in a boycott and, in response to a request for help from Boston’s customs collector, sent a warship to the city in 1768. A few months later, British troops arrived, and on the evening of March 5, 1770, an altercation erupted outside the customs house. Shots rang out as the soldiers fired into the crowd (Figure 2.3). Several people were hit; three died immediately. Britain had taxed the colonists without their consent. Now, British soldiers had taken colonists’ lives.







Figure 
2.3
 
The Sons of Liberty circulated this sensationalized version of the events of March 5, 1770, in order to promote the rightness of their cause; it depicts British soldiers firing on unarmed civilians in the event that became known as the Boston Massacre. Later portrayals would more prominently feature Crispus Attucks, an African American who was one of the first to die. Eight British soldiers were tried for murder as a result of the confrontation.

Following this event, later known as the Boston Massacre, resistance to British rule grew, especially in the colony of Massachusetts. In December 1773, a group of Boston men boarded a ship in Boston harbor and threw its cargo of tea, owned by the British East India Company, into the water to protest British policies, including the granting of a monopoly on tea to the British East India Company, which many colonial merchants resented.3 This act of defiance became known as the Boston Tea Party. In the 2010s, many who did not agree with the positions of the Democratic or the Republican Party organized themselves into an oppositional group dubbed the Tea Party (Figure 2.4).







Figure 
2.4
 
Members of the modern Tea Party movement claim to represent the same spirit as their colonial forebears in the iconic lithograph _The Destruction of Tea at Boston Harbor_ (a) and protest against what they perceive as government’s interference with people’s rights. In April 2010, members of a Tea Party Express rally on the Boston Common signed a signature wall to record their protest (b). (credit b: modification of work by Tim Pierce)

In the early months of 1774, Parliament responded to this latest act of colonial defiance by passing a series of laws called the Coercive Acts, intended to punish Boston for leading resistance to British rule and to restore order in the colonies. These acts virtually abolished town meetings in Massachusetts and otherwise interfered with the colony’s ability to govern itself. This assault on Massachusetts and its economy enraged people throughout the colonies, and delegates from all the colonies except Georgia formed the First Continental Congress to create a unified opposition to Great Britain. Among other things, members of the institution developed a declaration of rights and grievances.


In May 1775, delegates met again in the Second Continental Congress. By this time, war with Great Britain had already begun, following skirmishes between colonial militiamen and British troops at Lexington and Concord, Massachusetts. Congress drafted a Declaration of Causes explaining the colonies’ reasons for rebellion. On July 2, 1776, Congress declared American independence from Britain and two days later signed the Declaration of Independence.


Drafted by Thomas Jefferson, the Declaration of Independence officially proclaimed the colonies’ separation from Britain. In it, Jefferson eloquently laid out the reasons for rebellion. God, he wrote, had given everyone the rights of life, liberty, and the pursuit of happiness. People had created governments to protect these rights and consented to be governed by them so long as government functioned as intended. However, “whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government.” Britain had deprived the colonists of their rights. The king had “establish[ed] . . . an absolute Tyranny over these States.” Just as their English forebears had removed King James II from the throne in 1689, the colonists now wished to establish a new rule.


Jefferson then proceeded to list the many ways in which the British monarch had abused his power and failed in his duties to his subjects. The king, Jefferson charged, had taxed the colonists without the consent of their elected representatives, interfered with their trade, denied them the right to trial by jury, and deprived them of their right to self-government. Such intrusions on their rights could not be tolerated. With their signing of the Declaration of Independence (Figure 2.5), the founders of the United States committed themselves to the creation of a new kind of government.







Figure 
2.5
 
The presentation of the Declaration of Independence is commemorated in a painting by John Trumbull in 1817. It was commissioned to hang in the Capitol in Washington, DC.



[.my1]
.案例
====
== Link to Learning



Thomas Jefferson explains in the Declaration of Independence why many colonists felt the need to form a new nation. His evocation of the natural rights of man and his list of grievances against the king also served as the model for the Declaration of Sentiments that was written in 1848 in favor of giving women in the United States rights equal to those of men. View both documents and compare.

====




