= 005-5 (pure) Equal Protection for Other Groups
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

[.my1]
.案例
====
== Learning Objectives


By the end of this section, you will be able to:


* Discuss the discrimination faced by Hispanic/Latino Americans and Asian Americans
* Describe the influence of the African American civil rights movement on Hispanic/Latino, Asian American, and LGBTQ civil rights movements
* Describe federal actions to improve opportunities for people with disabilities
* Describe discrimination faced by religious minorities
====


Many groups in American society have faced and continue to face challenges in achieving equality, fairness, and equal protection under the laws and policies of the federal government and/or the states. Some of these groups are often overlooked because they are not as large of a percentage of the U.S. population as women or African Americans, and because organized movements to achieve equality for them are relatively young. This does not mean, however, that the discrimination they face has not been as longstanding or as severe.



== HISPANIC/LATINO CIVIL RIGHTS


Hispanic and Latino people in the United States have faced many of the same problems as African Americans and Native Americans. Although the terms Hispanic and Latino are often used interchangeably in discussions and sometimes in research, they are not the same. _Hispanic_ usually refers to native speakers of Spanish or those descended from Spanish-speaking countries. _Latino_ refers to people who come from, or whose ancestors came from, Mexico, Central America, South America, and some of the Caribbean islands, collectively known as Latin America. Not all Hispanics are Latinos and vice versa. People from Spain are Hispanic but are not Latino, while people from Brazil are Latino but not Hispanic. Both Hispanics and Latinos may be of any race or ethnicity; they may be of European, African, Native American descent, or they may be of mixed racial or ethnic background. We will use the term "Latino" here, also noting that many people use the terms Latinx or Latine to be more inclusive.127

Many Latinos became part of the U.S. population following the annexation of Texas by the United States in 1845 and of California, Arizona, New Mexico, Nevada, Utah, and Colorado following the War with Mexico in 1848. Most were subject to discrimination and could find employment only as poorly paid migrant farm workers, railroad workers, and unskilled laborers.128 The Spanish-speaking population of the United States increased following the Spanish-American War in 1898 with the incorporation of Puerto Rico as a U.S. territory. In 1917, during World War I, the Jones Act granted U.S. citizenship to Puerto Ricans.


In the early twentieth century, waves of violence aimed at Mexicans and Mexican Americans swept the Southwest. Mexican Americans in Arizona and in parts of Texas were denied the right to vote, which they had previously possessed, and Mexican American children were barred from attending Anglo-American schools. During the Great Depression of the 1930s, Mexican immigrants and many Mexican Americans, both U.S.-born and naturalized citizens, living in the Southwest and Midwest were deported by the government so that Anglo-Americans could take the jobs that they had once held.129 When the United States entered World War II, however, Mexicans were invited to immigrate to the United States as farmworkers under the Bracero (_bracero_ meaning “manual laborer” in Spanish) Program to make it possible for these American men to enlist in the armed services.130


Mexican Americans and Puerto Ricans did not passively accept discriminatory treatment, however. In 1903, Mexican farmworkers joined with Japanese farmworkers, who were also poorly paid, to form the first union to represent agricultural laborers. In 1929, Latino civil rights activists formed the League of United Latin American Citizens (LULAC) to protest against discrimination and to fight for greater rights for Latinos.131


Just as in the case of African Americans, however, true civil rights advances for Hispanic and Latino people did not take place until the end of World War II. Hispanic and Latino activists targeted the same racist practices as did African Americans and used many of the same tactics to end them. In 1946, Mexican American parents in California, with the assistance of the NAACP, sued several California school districts that forced Mexican and Mexican American children to attend segregated schools. In the case of _Mendez v. Westminster_ (1947), the Court of Appeals for the Ninth Circuit Court held that the segregation of Mexican and Mexican American students into separate schools was unconstitutional.132


Although Latinos made some civil rights advances in the decades following World War II, discrimination continued. Alarmed by the large number of undocumented Mexicans crossing the border into the United States in the 1950s, the United States government began Operation Wetback (_wetback_ is a derogatory term for Mexicans living unofficially in the United States). From 1953 to 1958, more than three million Mexican immigrants, and some Mexican Americans as well, were deported from California, Texas, and Arizona.133 To limit the entry of Hispanic and Latino immigrants to the United States, in 1965 Congress imposed an immigration quota of 120,000 newcomers from the Western Hemisphere.


At the same time that the federal government sought to restrict Hispanic and Latino immigration to the United States, the Mexican American civil rights movement grew stronger and more radical, just as the African American civil rights movement had done. While African Americans demanded Black Power and called for Black Pride, young Mexican American civil rights activists called for Brown Power and began to refer to themselves as Chicano*s*, a term disliked by many older, conservative Mexican Americans, in order to stress their pride in their hybrid Spanish-Native American cultural identity.134 Demands by Mexican American activists often focused on improving education for their children, and they called upon school districts to hire teachers and principals who were bilingual in English and Spanish, to teach Mexican and Mexican American history, and to offer instruction in both English and Spanish for children with limited ability to communicate in English.135



[.my1]
.案例
====
== Milestone



=== East L.A. Student Walkouts


In March 1968, Chicano students at five high schools in East Los Angeles went on strike to demand better education for students of Mexican ancestry. Los Angeles schools did not allow Latino students to speak Spanish in class and gave no place to study Mexican history in the curriculum. Guidance counselors also encouraged students, regardless of their interests or ability, to pursue vocational careers instead of setting their sights on college. Some students were placed in specialized classes for people with disabilities. As a result, the dropout rate among Mexican American students was very high.

School administrators refused to meet with the student protestors to discuss their grievances. After a week, police were sent in to end the strike. Thirteen of the organizers of the walkout were arrested and charged with conspiracy to disturb the peace. After Sal Castro, a teacher who had led the striking students, was dismissed from his job, activists held a sit-in at school district headquarters until Castro was reinstated. Student protests spread across the Southwest, and in response many schools did change. That same year, Congress passed the Bilingual Education Act, which required school districts with large numbers of Hispanic or Latino students to provide instruction in Spanish.136


_Bilingual education remains controversial, even among Hispanic and Latino people. What are some arguments they might raise both for and against it? Are these different from arguments coming from non-Latinos?_
====


Mexican American civil rights leaders were active in other areas as well. Throughout the 1960s, Cesar Chavez and Dolores Huerta fought for the rights of Mexican American agricultural laborers through their organization, the United Farm Workers (UFW), a union for migrant workers they founded in 1962. Chavez, Huerta, and the UFW proclaimed their solidarity with Filipino farm workers by joining them in a strike against grape growers in Delano, California, in 1965. Chavez consciously adopted the tactics of the African American civil rights movement. In 1965, he called upon all U.S. consumers to boycott California grapes (Figure 5.18), and in 1966, he led the UFW on a 300-mile march to Sacramento, the state capital, to bring the state farm workers’ problems to the attention of the entire country. The strike finally ended in 1970 when the grape growers agreed to give the pickers better pay and benefits.137







Figure 
5.18
 
Protestors picket a grocery store in 1973, urging consumers not to buy grapes or lettuce picked by underpaid farm workers (a). The boycott, organized by Cesar Chavez and the United Farm Workers using the slogan “Sí se puede” or “Yes, it can be done!” (b), ultimately forced California growers to improve conditions for migrant laborers.

As Latino immigration to the United States increased in the late twentieth and early twenty-first centuries, discrimination also increased in many places. In 1994, California voters passed Proposition 187. The proposition sought to deny non-emergency health services, food stamps, welfare, and Medicaid to undocumented immigrants. It also banned children from attending public school unless they could present proof that they and their parents were legal residents of the United States. A federal court found it unconstitutional in 1997 on the grounds that the law’s intention was to regulate immigration, a power held only by the federal government.138


In 2005, discussion began in Congress on proposed legislation that would make it a felony to enter the United States illegally or to give assistance to anyone who had done so. Although the bill quickly died, on May 1, 2006, hundreds of thousands of people, primarily Latinos, staged public demonstrations in major U.S. cities, refusing to work or attend school for one day.139 The protestors claimed that people seeking a better life should not be treated as criminals and that undocumented immigrants already living in the United States should have the opportunity to become citizens.


Following the failure to make undocumented immigration a felony under federal law, several states attempted to impose their own sanctions on unauthorized entry. In April 2010, Arizona passed a law that made illegal immigration a state crime. The law also forbade undocumented immigrants from seeking work and allowed law enforcement officers to arrest people suspected of being in the U.S. illegally. Thousands protested the law, claiming that it encouraged racial profiling. In 2012, in _Arizona v. United States_, the U.S. Supreme Court struck down those provisions of the law that made it a state crime to reside in the United States illegally, forbade undocumented immigrants to take jobs, and allowed the police to arrest those suspected of being illegal immigrants.140
 The court, however, upheld the authority of the police to ascertain the immigration status of someone suspected of being an undocumented entrant if the person had been stopped or arrested by the police for other reasons.141


Today, Latinos constitute the largest minority group in the United States. They also have one of the highest birth rates of any ethnic group.142 Although Hispanic people lag behind non-Hispanic White people in terms of income and high school graduation rates, they are enrolling in college at higher rates than non-Hispanic White people.143 Topics at the forefront of public debate during the Biden administration included immigration reform, the DREAM Act (a proposal for granting undocumented immigrants permanent residency in stages), and court action on executive orders on immigration. The first Trump administration was very active on issues of immigration and border security. Aside from the proposal to build a border wall, other areas of action have included various travel bans and the policy of separating families at the border as they attempt to enter the country.
144


The 2024 presidential campaign between former President Donald Trump and Vice President Kamala Harris brought matters related to Latino immigration to the fore once again. Trump, who was elected to a second term and took office in January 2025, dramatized issues of safety and the border and in American communities, including Aurora, Colorado. After swearing in as president for a second four-year term of office, President Trump quickly authorized a widespread campaign by the U.S. Immigration and Customs Enforcement Service (ICE) to round up illegal immigrants across the country of Latino or Hispanic descent. ICE has been omnipresent in American communities, including state and local courts, public spaces and even schools. Some say that the sheer number of people questioned to date is well beyond lists of suspects that ICE might be reasonably expected to investigate who potentially pose a threat to public safety. While supporters of the approach say that the broad net cast by the Trump administration through ICE has led to an increase in legitimate detainments of suspects who pose such a threat, opponents argue that the sheer numbers of law-abiding persons questioned, who must prove their status or face arrest, has been overwhelming for the Latino and Hispanic communities and produced a great deal of fear.145, 146, 147



== ASIAN AMERICAN CIVIL RIGHTS


As the rash of recent violence against them has shown, Asian Americans have also often been discriminated against and denied their civil rights. Often stereotyped as the "the model minority" (because it is assumed they are generally financially successful and do well academically), the underlying reality is complex. The truth is that Asian Americans have long faced discrimination. Indeed, in the nineteenth century, Asian people were among the most despised of all immigrant groups and were often subjected to the same laws enforcing segregation and forbidding interracial marriage as were African Americans and American Indians.


The Chinese were the first large group of Asian people to immigrate to the United States. They arrived in large numbers in the mid-nineteenth century to work in the mining industry and on the Central Pacific Railroad. Others worked as servants or cooks or operated laundries. Their willingness to work for less money than White workers led White workers in California to call for a ban on Chinese immigration. In 1882, Congress passed the Chinese Exclusion Act, which prevented Chinese from immigrating to the United States for ten years and prevented Chinese already in the country from becoming citizens (Figure 5.19). In 1892, the Geary Act extended the ban on Chinese immigration for another ten years. In 1913, California passed a law preventing all Asian people, not just the Chinese, from owning land. With the passage of the Immigration Act of 1924, all Asian people, with the exception of Filipinos, were prevented from immigrating to the United States or becoming naturalized citizens. Laws in several states barred marriage between Chinese and White Americans, and some cities with large Asian populations required Asian children to attend segregated schools.148







Figure 
5.19
 
The cartoon shows a Chinese laborer, the personification of industry and sobriety, outside the “Golden Gate of Liberty.” The Chinese Exclusion Act of 1882 has barred him from entering the country, while communists and “hoodlums” are allowed in.

During World War II, citizens of Japanese descent living on the West Coast, whether naturalized immigrants or Japanese Americans born in the United States, were subjected to the indignity of being removed from their communities and interned under Executive Order 9066 (Figure 5.20). The reason was fear that they might prove disloyal to the United States and give assistance to Japan. Although Italians and Germans suspected of disloyalty were also interned by the U.S. government, only the Japanese were imprisoned solely on the basis of their ethnicity. None of the more than 110,000 Japanese and Japanese Americans internees was ever found to have committed a disloyal act against the United States, and many young Japanese American men served in the U.S. army during the war.149 Although Japanese American Fred Korematsu challenged the right of the government to imprison law-abiding citizens, the Supreme Court decision in the 1944 case of _Korematsu v. United States_ upheld the actions of the government as a necessary precaution in a time of war.150 When internees returned from the camps after the war was over, many of them discovered that the houses, cars, and businesses they had left behind, often in the care of White neighbors, had been sold or destroyed.151







Figure 
5.20
 
Japanese Americans displaced from their homes by the U.S. government during World War II stand in line outside the mess hall at a relocation center in San Bruno, California, on April 29, 1942.


[.my1]
.案例
====
== Link to Learning



Explore the resources at Japanese American Internment and Digital History to learn more about experiences of Japanese Americans during World War II.
====


The growth of the African American, Chicano, and Native American civil rights movements in the 1960s inspired many Asian Americans to demand their own rights. Discrimination against Asian Americans, regardless of national origin, increased during the Vietnam War. Ironically, violence directed indiscriminately against Chinese, Japanese, Koreans, and Vietnamese caused members of these groups to unite around a shared pan-Asian identity, much as Native Americans had in the Pan-Indian movement. In 1968, students of Asian ancestry at the University of California at Berkeley formed the Asian American Political Alliance. Asian American students also joined Chicano, Native American, and African American students to demand that colleges offer ethnic studies courses.152 In 1974, in the case of _Lau v. Nichols_, Chinese American students in San Francisco sued the school district, claiming its failure to provide them with assistance in learning English denied them equal educational opportunities.153 The Supreme Court found in favor of the students.


Until recent attacks against Asian Americans during the COVID-19 pandemic, the Asian American movement was not as active as other civil rights movements. While not keeping them free from discrimination, their educational achievement and economic success placed Asian Americans in a much better position to defend their rights. Unfortunately, racist vitriol related to the origin of COVID-19 highlighted discrimination against Asian Americans and the formerly quiet movement has become highly salient. Hate crimes against Asian Americans increased 150 percent in 2020 and rose over 800 percent in New York City.154




== THE FIGHT FOR CIVIL RIGHTS IN THE LGBTQ COMMUNITY


Laws against same-sex relations and relationships existed in most states throughout the nineteenth and twentieth centuries. By the late nineteenth century, homosexuality had come to be regarded as a form of mental illness as well as a sin, and gay men were often erroneously believed to be pedophiles.155 As a result, lesbian women, gay men, bisexual people, and transgender people, currently known as the LGBTQ community, had to keep their sexual orientation hidden or “closeted.” Secrecy became even more important in the 1950s, when fear of gay men increased and the federal government believed they could be led into disloyal acts through blackmail by Soviet agents. As a result, many men lost or were denied government jobs.156 Fears of lesbians also increased after World War II as U.S. society stressed conformity to traditional gender roles and the importance of marriage and childrearing.157


The very secrecy in which lesbian, gay, bisexual, and transgender people had to live made it difficult for them to organize to fight for their rights as other, more visible groups had done. Some organizations did exist, however. The Mattachine Society, established in 1950, was one of the first groups to champion the rights of gay men. Its goal was to unite gay men who otherwise lived in secrecy and to fight against abuse. The Mattachine Society often worked with the Daughters of Bilitis, a lesbian rights organization. Among the early issues targeted by the Mattachine Society was police entrapment of gay men in which plain-clothes police officers would enter neighborhoods or establishments known to be frequented by gay people, and act as if they were interested in a sexual encounter; then the police would arrest those they said propositioned them. Entrapment often posed serious risks, because men who were associated with homosexuality—even if never prosecuted—were at risk of losing their jobs, families, or other positions.158


Law enforcement abuses against LGBTQ people took many forms. Some of the activities were encoded in laws, while others were interpretations of older laws or simply policies of individual cities or departments. In many places, any act related to same-sex relationships, such as holding hands, kissing, or dancing, was forbidden in public. As a result, police frequently raided what were known as gay bars, often committing sexually humiliating acts against patrons. Transgender people faced some of the worst treatment. Dressing in drag would result in arrest and prosecution. Transgender people were subjected to public strip searches and were groped beneath their undergarments to determine their sex. Such treatment of LGBTQ people by law enforcement also left them unprotected from others who assaulted them.


In the 1960s, the gay and lesbian rights movements began to grow more radical, in a manner similar to other civil rights movements. In 1962, gay Philadelphians demonstrated in front of Independence Hall. In 1966, transgender sex workers who were tired of police harassment rioted in San Francisco. In June 1969, gay men, lesbians, and transgender people erupted in violence when New York City police attempted to arrest customers at a gay bar in Greenwich Village called the Stonewall Inn. The patrons’ ability to resist arrest and fend off the police inspired many members of New York’s LGBTQ community, and the riots persisted over several nights. New organizations promoting LGBTQ rights that emerged after Stonewall were more radical and confrontational than the Mattachine Society and the Daughters of Bilitis had been. These groups, like the Gay Activists Alliance and the Gay Liberation Front, called not just for equality before the law and protection against abuse but also for “liberation,” Gay Power, and Gay Pride.159


Although LGBTQ people gained their civil rights later than many other groups, changes did occur beginning in the 1970s, remarkably quickly when we consider how long other minority groups had fought for their rights. The decade saw 18 states decriminalize same-sex relations, following Illinois and Connecticut, which had done so in the 1960s. In 1973, the American Psychological Association ended its classification of homosexuality as a mental disorder. In 1994, the U.S. military adopted the policy of “Don’t ask, don’t tell.” This act, Department of Defense Directive 1304.26, officially prohibited discrimination against gay, lesbian, and bisexual people by the U.S. military. It also prohibited superior officers from asking about or investigating the sexual orientation of those below them in rank.160 However, those gay, lesbian, and bisexual people who spoke openly about their sexual orientation were still subject to dismissal because it remained illegal for anyone except straight people to serve in the armed forces. The policy ended in 2011, and now gay, lesbian, and bisexual people may serve openly in the military.161 Transgender people were banned from serving in the military in 1960. The ban lasted until 2016, when the government began a gradual process of expanding and altering the limitations on their service. In early 2021, the Biden administration announced that there would no longer be restrictions on military service by transgender individuals, that medical support for gender transition would be provided, and that procedures would be developed to change a service member's official gender marker. Upon taking office in 2025, Donald Trump signed an executive order banning transgender people from serving in the military; a judge blocked enforcement of the ban because it violated transgender people's constitutional rights. The ruling will likely undergo numerous appeals.


In 2003, in the case of _Lawrence v. Texas_, the Supreme Court ruled unconstitutional fourteen remaining states' laws that criminalized sexual intercourse between consenting adults of the same sex.162 Beginning in 2000, several states made it possible for same-sex couples to enter into legal relationships known as civil unions or domestic partnerships. These arrangements extended many of the same protections enjoyed by heterosexual married couples to same-sex couples. LGBTQ activists, however, continued to fight for the right to marry. Same-sex marriages would allow partners to enjoy exactly the same rights as married heterosexual couples and accord their relationships the same dignity and importance. In 2004, Massachusetts became the first state to grant legal status to same-sex marriage. Other states quickly followed. This development prompted a backlash among many religious conservatives, who considered homosexuality a sin and argued that allowing same-sex couples to marry would lessen the value and sanctity of heterosexual marriage. Many states passed laws banning same-sex marriage, and many gay and lesbian couples challenged these laws, successfully, in the courts. Finally, in _Obergefell v. Hodges_, the Supreme Court overturned state bans and made same-sex marriage legal throughout the United States on June 26, 2015 (Figure 5.21).163







Figure 
5.21
 
Supporters of marriage equality celebrate outside the Supreme Court on June 26, 2015, following the announcement of the Court’s decision in _Obergefell v. Hodges_ declaring same-sex marriage a constitutional right under the Fourteenth Amendment. (credit: Matt Popovich)

The legalization of same-sex marriage throughout the United States led some people to feel their religious beliefs were under attack, and many religiously conservative business owners have refused to acknowledge LBGT rights or the legitimacy of same-sex marriages. Following swiftly upon the heels of the _Obergefell_ ruling, the Indiana legislature passed a Religious Freedom Restoration Act (RFRA). Congress had already passed such a law in 1993; it was intended to extend protection to minority religions, such as by allowing rituals of the Native American Church. However, the Supreme Court in _City of Boerne v. Flores_ (1997) ruled that the 1993 law applied only to the federal government and not to state governments.164 Thus several state legislatures later passed their own Religious Freedom Restoration Acts. These laws state that the government cannot “substantially burden an individual’s exercise of religion” unless it would serve a “compelling governmental interest” to do so. They allow individuals, which also include businesses and other organizations, to discriminate against others, primarily same-sex couples and LGBTQ people, if the individual’s religious beliefs are opposed to homosexuality.


LGBTQ Americans still encounter difficulties in other areas as well. While the Supreme Court ruled in 2020 that employers cannot discriminate based on sexual orientation and transgender status, LGBTQ people are not protected from housing discrimination. The federal Department of Housing and Urban Development has indicated that refusing to rent or sell homes to transgender people may be considered sex discrimination, but there is no nationwide clarity on the law.165 Violence and law enforcement targeting members of the LGBTQ community remains a serious problem; this violence occurs on the streets and in their homes.166 The enactment of the Matthew Shepard and James Byrd Jr. Hate Crimes Prevention Act, also known as the Matthew Shepard Act, in 2009 made it a federal hate crime to attack someone based on gender, gender identity, sexual orientation, or disability and made it easier for federal, state, and local authorities to investigate hate crimes, but it has not necessarily made the world safer for LGBTQ Americans. Transgender rights have also been increasingly under scrutiny as 2021 brought a record number of pieces of anti-transgender legislation in state legislatures.167 The U.S. Supreme Court, however, gave the transgender community a win when they chose not to hear a school's appeal of a lower court decision on a transgender student bathroom case.168 Soon after, the federal government indicated that it would follow the approach of many states in including a non-binary gender marker option on official documents, such as passports.


The Supreme Court provided another win in 2020 in Bostock v. Clayton County. This case involved reconciling Federal law regarding employment discrimination in governmental (_Bostock v. Clayton County_) and private organizations (_Altitude Express, Inc. v. Zarda, R.G. & G.R. Harris Funeral Homes, Inc. v. Equal Employment Opportunity Commission_). The plaintiff, Gerald Bostock, was fired from his position with the county for raising interest in a gay softball team while at work. In a 6-3 decision, the court found that an employer that terminates an employee for being gay or transgender is in violation of Title VII of the Civil Rights Act of 1964. Importantly, the Court (with Justice Neil Gorsuch writing for the majority) specifically indicated that discrimination due to sexual orientation or gender identity is equivalent to discrimination on the basis of sex, long prohibited by Title VII.




== CIVIL RIGHTS AND THE AMERICANS WITH DISABILITIES ACT


People with disabilities make up one of the last groups whose civil rights have been recognized. For a long time, they were denied employment and access to public education. Many were institutionalized. A _eugenics_ movement in the United States in the late nineteenth and early to mid-twentieth centuries sought to encourage childbearing among White people without disabilities and discourage it among those with physical or intellectual disabilities. Many states passed laws prohibiting marriage among people who had what were believed to be hereditary “defects.” Among those affected were people who were blind or deaf, those with epilepsy, people with intellectual or developmental disabilities, and those with mental illnesses. In some states, programs existed to sterilize people considered “feeble minded” by the standards of the time, without their will or consent.169
 When this practice was challenged by a woman in a state institution in Virginia, the Supreme Court, in the 1927 case of _Buck v. Bell_, upheld the right of state governments to sterilize those people believed likely to have children who would become dependent upon public welfare.170 Some of these programs persisted into the 1970s, as Figure 5.22 shows.171







Figure 
5.22
 
The map shows the number of sterilizations performed by the state in each of the counties of North Carolina between July 1946 and June 1968. Nearly five hundred sterilizations took place during this time period in the purple county.

By the 1970s, however, concern for extending equal opportunities to all led to the passage of two important acts by Congress. In 1973, the Rehabilitation Act made it illegal to discriminate against people with disabilities in federal employment or in programs run by federal agencies or receiving federal funding. This was followed by the Education for all Handicapped Children Act of 1975, which required public schools to educate children with disabilities. The act specified that schools consult with parents to create a plan tailored for each child’s needs that would provide an educational experience as close as possible to that received by other children.


In 1990, the Americans with Disabilities Act (ADA) greatly expanded opportunities and protections for people of all ages with disabilities. It also significantly expanded the categories and definition of disability. The ADA prohibits discrimination in employment based on disability. It also requires employers to make reasonable accommodations available to workers who need them. Finally, the ADA mandates that public transportation and public accommodations be made accessible to those with disabilities. The Act was passed despite the objections of some who argued that the cost of providing accommodations would be prohibitive for small businesses. While the ADA has inarguably improved opportunities for Americans with disabilities to receive public services equally and to pursue educational opportunities, challenges continue in this space. On college campuses, disability resource centers are often slow and understaffed, causing stress for students and professors alike.172 And, in schools and colleges, full access to certain buildings and spaces remains elusive.173



[.my1]
.案例
====
== Link to Learning



The community of people with disabilities is well organized in the twenty-first century, as evidenced by the considerable network of disability rights organizations in the United States.
====




== THE RIGHTS OF RELIGIOUS MINORITIES


The right to worship as a person chooses was one of the reasons for the initial settlement of the United States. Thus, it is ironic that many people throughout U.S. history have been denied their civil rights because of their status as members of a religious minority. Beginning in the early nineteenth century with the immigration of large numbers of Irish Catholics to the United States, anti-Catholicism became a common feature of American life and remained so until the mid-twentieth century. Catholic immigrants were denied jobs, and in the 1830s and 1840s anti-Catholic literature accused Catholic priests and nuns of committing horrific acts. Anti-Mormon sentiment was also quite common, and members of the Church of Jesus Christ of Latter-day Saints were accused of kidnapping women and building armies for the purpose of dominating their neighbors. At times, these fears led to acts of violence against these religious groups. For example, a convent in Charlestown, Massachusetts, was burned to the ground in 1834.174 In 1844, Joseph Smith, the founder of the LDS Church, and his brother were murdered by a mob in Illinois.175


For many years, Jewish Americans faced discrimination in employment, education, and housing based on their religion. Many of the restrictive real estate covenants that prohibited people from selling their homes to Black people also prohibited them from selling to Jewish people, and a “gentlemen’s agreement” among the most prestigious universities in the United States limited the number of Jewish students accepted. Indeed, a tradition of confronting discrimination led many American Jews to become actively involved in the civil rights movements for women and African Americans.176


Anti-semitism remains a significant issue in the United States and worldwide. According to the FBI, Jewish people or property are the most frequent targets of hate crimes motivated by religious bias. Jewish cemeteries and places of worship are frequently attacked or defaced, and insensitive jokes and frequent references to the Holocaust are widely used. Muslims have also experienced a rise in discrimination and hate crimes, and most Americans, including non-Muslims, report a belief that significant anti-Muslim sentiment exists in the United States. Although Title VII of the Civil Rights Act of 1964 prevents employment discrimination on the basis of religion and requires employers to make reasonable accommodations so that employees can engage in religious rituals and practices, Muslim employees are often discriminated against. Often the source of controversy is the wearing of head coverings by observant Muslims, which some employers claim violates uniform policies or dress codes, even when non-Muslim coworkers are allowed to wear head coverings that are not part of work uniforms.177 Hate crimes against Muslims have also increased, and many Muslims believe they are subject to racial profiling by law enforcement officers who suspect them of being terrorists.178


Many Christians have recently argued that they are being deprived of their rights because of their religious beliefs and have used this claim to justify their refusal to acknowledge the rights of others. The owner of Hobby Lobby Stores, for example, a conservative Christian, argued that his company’s health-care plan should not have to pay for contraception because his religious beliefs are opposed to the practice. In 2014, in the case of _Burwell v. Hobby Lobby Stores, Inc._, the Supreme Court ruled in his favor.179 As discussed earlier, many conservative Christians have also argued that they should not have to recognize same-sex marriages because they consider homosexuality to be a sin.