= 005-4 (pure) Civil Rights for Indigenous Groups: Native Americans, Alaskans, and Hawaiians
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

[.my1]
.案例
====
== Learning Objectives


By the end of this section, you will be able to:


* Outline the history of discrimination against Native Americans
* Describe the expansion of Native American civil rights from 1960 to 1990
* Discuss the persistence of problems Native Americans face today
====


Native Americans have long suffered the effects of segregation and discrimination imposed by the U.S. government and the larger White society. Native Americans were not granted the full rights and protections of U.S. citizenship until long after African Americans and women were, with many having to wait until the Nationality Act of 1940 to become citizens.93 This was long after the passage of the Fourteenth Amendment in 1868, which granted citizenship to African Americans but not, the Supreme Court decided in _Elk v. Wilkins_ (1884), to Native Americans.94 White women had been citizens of the United States since its very beginning even though they were not granted the full rights of citizenship. Furthermore, Native Americans are the only group of Americans who were forcibly removed en masse from the lands on which they and their ancestors had lived so that others could claim this land and its resources. This issue remains relevant today as can be seen in the recent protests of the Dakota Access Pipeline, which have led to intense confrontations between those in charge of the pipeline and Native Americans.


== NATIVE AMERICANS LOSE THEIR LAND AND THEIR RIGHTS


From the very beginning of European settlement in North America, Native Americans were abused and exploited. Early British settlers attempted to enslave the members of various tribes, especially in the southern colonies and states.95 Following the American Revolution, the U.S. government assumed responsibility for conducting negotiations with Indian tribes, all of which were designated as sovereign nations, and regulating commerce with them. Because Native Americans were officially regarded as citizens of other nations, they were denied U.S. citizenship.96


As White settlement spread westward over the course of the nineteenth century, Indian tribes were forced to move from their homelands. Although the federal government signed numerous treaties guaranteeing tribe members the right to live in the places where they had traditionally farmed, hunted, or fished, land-hungry White settlers routinely violated these agreements and the federal government did little to enforce them.97


In 1830, Congress passed the Indian Removal Act, which forced Native Americans to move west of the Mississippi River.98 Not all tribes were willing to leave their land, however. The Cherokee in particular resisted, and in the 1820s, the state of Georgia tried numerous tactics to force them from their territory. Efforts intensified in 1829 after gold was discovered there. Wishing to remain where they were, the tribe sued the state of Georgia.99 In 1831, the Supreme Court decided in _Cherokee Nation v. Georgia_ that Indian tribes were not sovereign nations, but also that tribes were entitled to their ancestral lands and could not be forced to move from them.100


The next year, in _Worcester v. Georgia_, the Court ruled that non-Native Americans could not enter tribal lands without the tribe’s permission. White Georgians, however, refused to abide by the Court’s decision, and President Andrew Jackson, who had fought in conflicts against Native Americans, refused to enforce it.101 Between 1831 and 1838, members of several southern tribes, including the Cherokees, were forced by the U.S. Army to move west along routes shown in Figure 5.15. The forced removal of the Cherokees to Oklahoma Territory, which had been set aside for settlement by displaced tribes and designated Indian Territory, resulted in the death of one-quarter of the tribe’s population.102 The Cherokees remember this journey as the Trail of Tears.







Figure 
5.15
 
After the passage of the Indian Removal Act, the U.S. military forced the removal of the Cherokee, Chickasaw, Choctaw, Creek, and Seminole from the Southeast to the western territory (present-day Oklahoma), marching them along the routes shown here. The lines in yellow mark the routes taken by the Cherokee on the Trail of Tears.

By the time of the Civil War, most Indian tribes had been relocated west of the Mississippi. However, once large numbers of White Americans and European immigrants had also moved west after the Civil War, Native Americans once again found themselves displaced. They were confined to reservations, which are federal lands set aside for their use where non-Indians could not settle. Reservation land was usually poor, however, and attempts to farm or raise livestock, not traditional occupations for most western tribes anyway, often ended in failure. Unable to feed themselves, the tribes became dependent on the Bureau of Indian Affairs (BIA) in Washington, DC, for support. Protestant missionaries were allowed to “adopt” various tribes, to convert them to Christianity and thus speed their assimilation. In an effort to hasten this process, Native American children were taken from their parents and sent to boarding schools, many of them run by churches, where they were forced to speak English and abandon their traditional cultures.103


In 1887, the Dawes Severalty Act, another effort to assimilate Native Americans to White society, divided reservation lands into individual allotments. Native Americans who accepted these allotments and agreed to sever tribal ties were also given U.S. citizenship. All lands remaining after the division of reservations into allotments were offered for sale by the federal government to White farmers and ranchers. As a result, Native Americans swiftly lost control of reservation land.104 In 1898, the Curtis Act dealt the final blow to Indian sovereignty by abolishing all tribal governments.105




== THE FIGHT FOR NATIVE AMERICAN RIGHTS


As Native Americans were removed from their tribal lands and increasingly saw their traditional cultures being destroyed over the course of the nineteenth century, a movement to protect their rights began to grow. Sarah Winnemucca (Figure 5.16), member of the Paiute tribe, lectured throughout the east in the 1880s in order to acquaint White audiences with the injustices suffered by the western tribes.106 Lakota physician Charles Eastman (Figure 5.16) also worked for Native American rights. In 1924, the Indian Citizenship Act granted citizenship to all Native Americans born after its passage. Native Americans born before the act took effect, who had not already become citizens as a result of the Dawes Severalty Act or service in the army in World War I, had to wait until the Nationality Act of 1940 to become citizens. In 1934, Congress passed the Indian Reorganization Act, which ended the division of reservation land into allotments. It returned to Native American tribes the right to institute self-government on their reservations, write constitutions, and manage their remaining lands and resources. It also provided funds for Native Americans to start their own businesses and attain a college education.107







Figure 
5.16
 
Sarah Winnemucca (a), called the “Paiute Princess” by the press, and Dr. Charles Eastman (b), of the Lakota tribe, campaigned for Native American rights in the late nineteenth and early twentieth centuries. Winnemucca wears traditional dress for a publicity photograph.

Despite the Indian Reorganization Act, conditions on the reservations did not improve dramatically. Most tribes remained impoverished, and many Native Americans, despite the fact that they were now U.S. citizens, were denied the right to vote by the states in which they lived. States justified this violation of the Fifteenth Amendment by claiming that Native Americans might be U.S. citizens but were not state residents because they lived on reservations. Other states denied Native Americans voting rights if they did not pay taxes.108 Despite states’ actions, the federal government continued to uphold the rights of tribes to govern themselves. Federal concern for tribal sovereignty was part of an effort on the government’s part to end its control of, and obligations to, Indian tribes.109


In the 1960s, a modern Native American civil rights movement, inspired by the African American civil rights movement, began to grow. In 1969, a group of Native American activists from various tribes, part of a new Pan-Indian movement, took control of Alcatraz Island in San Francisco Bay, which had once been the site of a federal prison. Attempting to strike a blow for Red Power, a multi-faceted movement to increase the power of Native Americans united by a Pan-Indian identity and demanding federal recognition of their rights, they maintained control of the island for more than a year and a half. They claimed the land as compensation for the federal government’s violation of numerous treaties and offered to pay for it with beads and trinkets. In January 1970, some of the occupiers began to leave the island. Some may have been disheartened by the accidental death of the daughter of one of the activists. In May 1970, all electricity and telephone service to the island was cut off by the federal government, and more of the occupiers began to leave. Over the course of the next year, the conditions on the island declined steadily and public opinion in the country turned decidedly against the occupiers. By June 1971, the few people remaining on the island were removed by the government. Though the goals of the activists were not achieved, the occupation of Alcatraz had brought national attention to the concerns of Native American activists.110


In 1973, members of the American Indian Movement *(AIM)*, a more radical group than the occupiers of Alcatraz, temporarily took over the offices of the Bureau of Indian Affairs in Washington, DC. The following year, members of AIM and some two hundred Oglala Lakota supporters occupied the town of Wounded Knee on the Lakota tribe’s Pine Ridge Reservation in South Dakota, the site of an 1890 massacre of Lakota men, women, and children by the U.S. Army (Figure 5.17). Many of the Oglala were protesting the actions of their half-White tribal chieftain, who they claimed had worked too closely with the BIA. The occupiers also wished to protest the failure of the Justice Department to investigate acts of White violence against Lakota tribal members outside the bounds of the reservation.


The occupation led to a confrontation between the Native American protestors and the FBI and U.S. Marshals. Violence erupted; two Native American activists were killed, and a marshal was shot (Figure 5.17). After the second death, the Lakota called for an end to the occupation and negotiations began with the federal government. Two of AIM’s leaders, Russell Means and Dennis Banks, were arrested, but the case against them was later dismissed.111 Violence continued on the Pine Ridge Reservation for several years after the siege; the reservation had the highest per capita murder rate in the United States. Two FBI agents were among those who were killed. The Oglala blamed the continuing violence on the federal government.112







Figure 
5.17
 
A memorial stone (a) marks the spot of the mass grave of the Lakotas killed in the 1890 massacre at Wounded Knee. The bullet-riddled car (b) of FBI agent Ronald Williams reveals the level of violence reached during—and for years after—the 1973 occupation of the town.


[.my1]
.案例
====
== Link to Learning



The official website of the American Indian Movement provides information about ongoing issues in Native American communities in both North and South America.
====


The current relationship between the U.S. government and Native American tribes was established by the Indian Self-Determination and Education Assistance Act of 1975. Under the act, tribes assumed control of programs that had formerly been controlled by the BIA, such as education and resource management, and the federal government provided the funding.113 Many tribes have also used their new freedom from government control to legalize gambling and to open casinos on their reservations. Although the states in which these casinos are located have attempted to control gaming on Native American lands, the Supreme Court and the Indian Gaming Regulatory Act of 1988 have limited their ability to do so.114 The 1978 American Indian Religious Freedom Act granted tribes the right to conduct traditional ceremonies and rituals, including those that use otherwise prohibited substances like peyote cactus and eagle bones, which can be procured only from vulnerable or protected species.115 Another 1978 law, the Indian Child Welfare Act, prevented the frequent practice of removing Native American children from their homes and placing  them non-Native American families. The law stated that if a child needed to be removed from their family for reasons of welfare and safety, they would be either placed with extended family, members of their own tribe, or members of another tribe—not with non-Native American families.  (The law has been challenged, but in 2023 the Supreme Court ruled that it should remain intact.)116

In another important recent development, several federal court cases have raised standing for Native American tribes to sue to regain former reservation lands lost to the U.S. government. Through a key 5-4 decision by the Supreme Court in _McGirt v. Oklahoma_, Native Americans realized the most important advancement in rights since the reapplication of the Winters Doctrine (which led to a stronger footing for tribes in water negotiations). 117 The initial case taken up by the Court in 2019, _Carpenter v. Murphy_, which revolved around a murder case in Oklahoma, became quite salient, given the history of the Trail of Tears. At issue was whether Mr. Murphy committed murder on private land in the state of Oklahoma or on the Muscogee (Creek) reservation and who should have jurisdiction over his case. If the court decided to proclaim the land as a reservation, that would potentially lead to half the State of Oklahoma being designated as such.118 After hearing arguments in late 2018, they did not hand down a decision in 2019. However, in the follow-up case, _McGirt v. Oklahoma_, the Court took the step that strengthened Native American rights. The landmark decision held that a large part of Oklahoma is tribal land. Moreover, the court argued that crimes committed on those lands are subject to federal, not state authority. In this case, Jimcy McGirt was convicted in Oklahoma state court in 1997 of various sexual crimes. McGirt challenged the conviction on the basis that Oklahoma lacked jurisdiction to prosecute a member of the Muscogee Creek Nation tribe for crimes committed on tribal land.119


In addition to gains in water rights and land rights, Native American tribes made other gains in recent decades. Tribes have robust and well-recognized governing institutions based on democratic principles. Moreover, many tribes now have governing compacts negotiated with the states where their ancestral lands lay. The proliferation of Indian gaming has further strengthened the success and political influence of the tribes. Finally, the appointment by President Biden, and subsequent Senate confirmation, of Rep. Deb Haaland (D-NM) as Secretary of the Interior was a powerful and pathbreaking moment. She is the first Native American to hold that position at Interior, which includes the Bureau of Indian Affairs.



== ALASKA NATIVES AND NATIVE HAWAIIANS REGAIN SOME RIGHTS


Alaska Natives and Native Hawaiians endured many of the same abuses as Native Americans, including loss of land and forced assimilation. Following the discovery of oil in Alaska, however, the state, in an effort to gain undisputed title to oil rich land, settled the issue of Alaska Natives’ land claims with the passage of the Alaska Native Claims Settlement Act in 1971. According to the terms of the act, Alaska Natives received 44 million acres of resource-rich land and more than $900 million in cash in exchange for relinquishing claims to ancestral lands to which the state wanted title.120


Native Hawaiians also lost control of their land—nearly two million acres—through the overthrow of the Hawaiian monarchy in 1893 and the subsequent formal annexation of the Hawaiian Islands by the United States in 1898. The indigenous population rapidly decreased in number, and white settlers tried to erase all trace of traditional Hawaiian culture. Two acts passed by Congress in 1900 and 1959, when the territory was granted statehood, returned slightly more than one million acres of federally owned land to the state of Hawaii. The state was to hold it in trust and use profits from the land to improve the condition of Native Hawaiians.121

In September 2015, the U.S. Department of Interior, the same department that contains the Bureau of Indian Affairs, created guidelines for Native Hawaiians who wish to govern themselves in a relationship with the federal government similar to that established with Native American and Alaska Native tribes. Such a relationship would grant Native Hawaiians power to govern themselves while remaining U.S. citizens. Voting began in fall 2015 for delegates to a constitutional convention that would determine whether or not such a relationship should exist between Native Hawaiians and the federal government.122 When non-Native Hawaiians and some Native Hawaiians brought suit on the grounds that, by allowing only Native Hawaiians to vote, the process discriminated against members of other ethnic groups, a federal district court found the election to be legal. While the Supreme Court stopped the election, in September 2016 a separate ruling by the Interior Department allowed for a referendum to be held. Native Hawaiians in favor are working to create their own nation.123

Despite significant advances, American Indians, Alaska Natives, and Native Hawaiians still trail behind U.S. citizens of other ethnic backgrounds in many important areas. These groups continue to suffer widespread poverty and high unemployment. Some of the poorest counties in the United States are those in which Native American reservations are located. These minorities are also less likely than White Americans, African Americans, or Asian Americans to complete high school or college.124 Many American Indian and Alaskan tribes endure high rates of infant mortality, alcoholism, and suicide.125 Native Hawaiians are also more likely to live in poverty than White people in Hawaii, and they are more likely than White Hawaiians to be unhoused or unemployed.126