= 008-1 (pure) What Is the Media?
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

[.my1]
.案例
====
== Learning Objectives


By the end of this section, you will be able to:


* Explain what the media are and how they are organized
* Describe the main functions of the media in a free society
* Compare different media formats and their respective audiences
====


Ours is an exploding media system. What started as print journalism was subsequently supplemented by radio coverage, then network television, followed by cable television. Now, with the addition of the Internet, blogs and social media—a set of applications or web platforms that allow users to immediately communicate with one another—give citizens a wide variety of sources for instant news of all kinds. The Internet also allows citizens to initiate public discussion by uploading images and video for viewing, such as videos documenting interactions between citizens and the police, for example. Provided we are connected digitally, we have a bewildering amount of choices for finding information about the world. In fact, some might say that compared to the tranquil days of the 1970s, when we might read the morning newspaper over breakfast and take in the network news at night, there are now too many choices in today’s increasingly complex world of information. This reality may make the news media all the more important to structuring and shaping narratives about U.S. politics. Or the proliferation of competing information sources like blogs and social media may actually weaken the power of the news media relative to the days when news media monopolized our attention.



== MEDIA BASICS


The term _media_ defines a number of different communication formats from television media, which share information through broadcast airwaves, to print media, which rely on printed documents. The collection of all forms of media that communicate information to the general public is called mass media, including television, print, radio, and Internet. One of the primary reasons citizens turn to the media is for news. We expect the media to cover important political and social events and information in a concise and neutral manner.


To accomplish its work, the media employs a number of people in varied positions. Journalists and reporters are responsible for uncovering news stories by keeping an eye on areas of public interest, like politics, business, and sports. Once a journalist has a lead or a possible idea for a story, they research background information and interview people to create a complete and balanced account. Editors work in the background of the newsroom, assigning stories, approving articles or packages, and editing content for accuracy and clarity. Publishers are people or companies that own and produce print or digital media. They oversee both the content and finances of the publication, ensuring the organization turns a profit and creates a high-quality product to distribute to consumers. Producers oversee the production and finances of visual media, like television, radio, and film.


The work of the news media differs from public relations, which is communication carried out to improve the image of companies, organizations, or candidates for office. Public relations is not a neutral information form. While journalists write stories to inform the public, a public relations spokesperson is paid to help an individual or organization get positive press. Public relations materials normally appear as press releases or paid advertisements in newspapers and other media outlets. Some less reputable publications, however, publish paid articles under the news banner, blurring the line between journalism and public relations.




== MEDIA TYPES


Each form of media has its own complexities and is used by different demographics. Millennials (those born between 1981 and 1996) and Generation Z (those born between 1997 and 2012) are more likely to get news and information from digital sources and social media, such as Instagram, TikTok, Twitter, and YouTube, while Baby Boomers (born between 1946 and 1964) are most likely to get their news from television, either national broadcasts or local news (Figure 8.2). Generation X (born between 1965 and 1980) is a mix, taking in more television than Millennials or Generation Z but more digital sources than Baby Boomers.





Figure 
8.2
 
Age greatly influences the choice of news sources. Baby Boomers are more likely to get news and information from television, while members of Generation X and Millennials are more likely to use social media.
Television alone offers viewers a variety of formats. Programming may be scripted, like dramas or comedies. It may be unscripted, like game shows or reality programs, or informative, such as news programming. Although most programs are created by a television production company, national networks—like CBS or NBC—purchase the rights to programs they distribute to local stations across the United States. Most local stations are affiliated with a national network corporation, and they broadcast national network programming to their local viewers.


Before the existence of cable and fiber optics, networks needed to own local affiliates to have access to the local station’s transmission towers. Towers have a limited radius, so each network needed an affiliate in each major city to reach viewers. While cable technology has lessened networks’ dependence on aerial signals, some viewers still use antennas and receivers to view programming broadcast from local towers.


Affiliates, by agreement with the networks, give priority to network news and other programming chosen by the affiliate’s national media corporation. Local affiliate stations are told when to air programs or commercials, and they diverge only to inform the public about a local or national emergency. For example, ABC affiliates broadcast the popular television show _Black-ish_ at a specific time on a specific day. Should a fire threaten homes and businesses in a local area, the affiliate might preempt it to update citizens on the fire’s dangers and return to regularly scheduled programming after the danger has ended.


Most affiliate stations will show local news before and after network programming to inform local viewers of events and issues. Network news has a national focus on politics, international events, the economy, and more. Local news, on the other hand, is likely to focus on matters close to home, such as regional business, crime, sports, and weather.4 The _NBC Nightly News_, for example, covers presidential campaigns and the White House or skirmishes between North Korea and South Korea, while the NBC affiliate in Los Angeles (KNBC-TV) and the NBC affiliate in Dallas (KXAS-TV) report on the governor’s activities or weekend festivals in the region.


Cable programming offers national networks a second method to directly reach local viewers. As the name implies, cable stations transmit programming directly to a local cable company hub, which then sends the signals to homes through coaxial or fiber optic cables. Because cable does not broadcast programming through the airwaves, cable networks can operate across the nation directly without local affiliates. Instead they purchase broadcasting rights for the cable stations they believe their viewers want. For this reason, cable networks often specialize in different types of programming.


The Cable News Network (CNN) was the first news station to take advantage of this specialized format, creating a 24-hour news station with live coverage and interview programs. Other news stations quickly followed, such as MSNBC and FOX News. A viewer might tune in to Nickelodeon and catch family programs and movies or watch ESPN to catch up with the latest baseball or basketball scores. The Cable-Satellite Public Affairs Network, known better as C-SPAN, now has three channels covering Congress, the president, the courts, and matters of public interest.


Cable and satellite providers also offer on-demand programming for most stations. Citizens can purchase cable, satellite, and Internet subscription services (like Netflix) to find programs to watch instantly, without being tied to a schedule. Initially, on-demand programming was limited to rebroadcasting old content and was commercial-free. Yet many networks and programs now allow their new programming to be aired within a day or two of its initial broadcast. In return they often add commercials the user cannot fast-forward or avoid. Thus networks expect advertising revenues to increase.5


The on-demand nature of the Internet has created many opportunities for news outlets. While early media providers were those who could pay the high cost of printing or broadcasting, modern media require just a URL and ample server space. The ease of online publication has made it possible for more niche media outlets to form. The websites of the _New York Times_ and other newspapers often focus on matters affecting the United States, while channels like BBC America present world news. FOX News presents political commentary and news in a conservative vein, while the Internet site Daily Kos offers a liberal perspective on the news. Politico.com is perhaps the leader in niche journalism.


Unfortunately, the proliferation of online news has also increased the amount of poorly written material with little editorial oversight, and readers must be cautious when reading Internet news sources. Sites like Buzzfeed allow members to post articles without review by an editorial board, leading to articles of varied quality and accuracy. The Internet has also made publication speed a consideration for professional journalists. No news outlet wants to be the last to break a story, and the rush to publication often leads to typographical and factual errors. Even large news outlets, like the Associated Press, have published articles with errors in their haste to get a story out.


The Internet also facilitates the flow of information through social media, which allows users to instantly communicate with one another and share with audiences that can grow exponentially. Facebook and Twitter have millions of daily users. Social media changes more rapidly than the other media formats. While people in many different age groups use sites like Facebook, Twitter, and YouTube, other sites like Snapchat and TikTok appeal mostly to younger users. The platforms also serve different functions. Tumblr and Reddit facilitate discussion that is topic-based and controversial, while Instagram is mostly social. A growing number of these sites also allow users to comment anonymously, leading to increases in threats and abuse. The 2020 QAnon conspiracy, which absurdly alleged a connection between liberal elites and child sex trafficking, was promulgated in part through social media posts on many platforms, including Facebook and Twitter. Both companies attempted to kick QAnon off their platforms.6


Regardless of where we get our information, the various media avenues available today, versus years ago, make it much easier for everyone to be engaged. The question is: Who controls the media we rely on? Most media are controlled by a limited number of conglomerates. A conglomerate is a corporation made up of a number of companies, organizations, and media networks. In the 1980s, more than fifty companies owned the majority of television and radio stations and networks. By 2011, six conglomerates controlled most of the broadcast media in the United States: CBS Corporation, Comcast, Time Warner, 21st Century Fox (formerly News Corporation), Viacom, and The Walt Disney Company (Figure 8.3).7 With the Disney-Fox merger in March 2019 and the CBS-Viacom merger in December 2019, this number was reduced to four. Moreover, these conglomerates own much of the airways for television news. The Walt Disney Company also owns the ABC Television Network, ESPN, A&E, and Lifetime, in addition to the Disney Channel and Disney+, a popular streaming service. Viacom also owns BET, Comedy Central, MTV, Nickelodeon, and VH1. Warner Bros. Discovery owns Cartoon Network, CNN, HBO, Food Network, and HGTV among others. While each of these networks has its own programming, in the end, the conglomerate can make a policy that affects all stations and programming under its control.






Figure 
8.3
 
In 1983, fifty companies owned 90 percent of U.S. media. By 2021, just four conglomerates controlled the same percentage of U.S. media outlets.

Conglomerates can create a monopoly on information by controlling a sector of a market. When a media conglomerate has policies or restrictions, they will apply to all stations or outlets under its ownership, potentially limiting the information citizens receive. Conglomerate ownership also creates circumstances in which censorship may occur. iHeartMedia (formerly Clear Channel Media) owns music, radio, and billboards throughout the United States, and in 2010, the company refused to run several billboard ads for the St. Pete Pride Festival and Promenade in St. Petersburg, Florida. The festival organizers said the content of two ads, a picture of same-sex couples in close contact with one another, was the reason the ads were not run. Because iHeartMedia owns most of the billboards in the area, this limitation was problematic for the festival and decreased awareness of the event. Those in charge of the festival viewed the refusal as censorship.8


Newspapers too have experienced the pattern of concentrated ownership. Gannett Company, while also owning television media, holds a large number of newspapers and news magazines in its control. Many of these were acquired quietly, without public notice or discussion. Gannett’s 2013 acquisition of publishing giant A.H. Belo Corporation caused some concern and news coverage, however. The sale would have allowed Gannett to own both an NBC and a CBS affiliate in St. Louis, Missouri, giving it control over programming and advertising rates for two competing stations. The U.S. Department of Justice required Gannett to sell the station owned by Belo to ensure market competition and multi-ownership in St. Louis.9



[.my1]
.案例
====
== Link to Learning



If you are concerned about the lack of variety in the media and the market dominance of media conglomerates, the non-profit organization, Free Press, tracks and promotes open communication.
====


These changes in the format and ownership of media raise the question whether the media still operate as an independent source of information. Is it possible that corporations and CEOs now control the information flow, making profit more important than the impartial delivery of information? The reality is that media outlets, whether newspaper, television, radio, or Internet, are businesses. They have expenses and must raise revenues. Yet at the same time, we expect the media to entertain, inform, and alert us without bias. They must provide some public services, while following laws and regulations. Reconciling these goals may not always be possible.




== FUNCTIONS OF THE MEDIA


The media exist to fill a number of functions. Whether the medium is a newspaper, a radio, or a television newscast, a corporation behind the scenes must bring in revenue and pay for the cost of the product. Revenue comes from advertising and sponsors, like McDonald’s, Ford Motor Company, and other large corporations. But corporations will not pay for advertising if there are no viewers or readers. So all programs and publications need to entertain, inform, or interest the public and maintain a steady stream of consumers. In the end, what attracts viewers and advertisers is what survives.


The media are also watchdogs of society and of public officials. Some refer to the media as the _fourth estate_, with the branches of government being the first three estates and the media equally participating as the fourth. This role helps maintain democracy and keeps the government accountable for its actions, even if a branch of the government is reluctant to open itself to public scrutiny. As much as social scientists would like citizens to be informed and involved in politics and events, the reality is that we are not. So the media, especially journalists, keep an eye on what is happening and sounds an alarm when the public needs to pay attention.10


The media also engages in agenda setting, which is the act of choosing which issues or topics deserve public discussion. For example, in the early 1980s, famine in Ethiopia drew worldwide attention, which resulted in increased charitable giving to the country. Yet the famine had been going on for a long time before it was discovered by western media. Even after the discovery, it took video footage to gain the attention of the British and U.S. populations and start the aid flowing.11 Today, numerous examples of agenda setting show how important the media are when trying to prevent further emergencies or humanitarian crises. In the spring of 2015, when the Dominican Republic was preparing to exile Haitians and undocumented (or under documented) residents, major U.S. news outlets remained silent. However, once the story had been covered several times by Al Jazeera, a state-funded broadcast company based in Qatar, ABC, the _New York Times_, and other network outlets followed.12 With major network coverage came public pressure for the U.S. government to act on behalf of the Haitians.13



[.my1]
.案例
====
== Insider Perspective



=== Christiane Amanpour on “What Should Be News?”


The media are our connection to the world. Some events are too big to ignore, yet other events, such as the destruction of Middle Eastern monuments or the plight of foreign refugees, are far enough from our shores that they often go unnoticed. What we see is carefully selected, but who decides what should be news?


As the chief international correspondent for CNN, Christiane Amanpour is one media decision maker (Figure 8.4). Over the years, Amanpour has covered events around the world from war to genocide. In an interview with Oprah Winfrey, Amanpour explains that her duty, and that of other journalists, is to make a difference in the world. To do that, “we have to educate people and use the media responsibly.”14 Journalists cannot passively sit by and wait for stories to find them. “Words have consequences: the stories we decide to do, the stories we decide not to do . . . it all matters.”15







Figure 
8.4
 
Christiane Amanpour accepts the award for the Association for International Broadcasting’s Personality of the Year on November 4, 2015. (credit: AIB (Association for International Broadcasting))

As Amanpour points out, journalists are often “on the cutting edge of reform,” so if they fail to shed light on events, the results can be tragic. One of her biggest regrets was not covering the genocide in Rwanda in 1994, which cost nearly a million lives. She said the media ignored the event in favor of covering democratic elections in South Africa and a war in Bosnia, and ultimately she believes the media failed the people. “If we don’t respect our profession and we see it frittering away into the realm of triviality and sensationalism, we’ll lose our standing,” she said. “That won’t be good for democracy. A thriving society must have a thriving press.”


This feeling of responsibility extends to covering moral topics, like genocide. Amanpour feels there shouldn’t be equal time given to all sides. “I’m not just a stenographer or someone with a megaphone; when I report, I have to do it in context, to be aware of the moral conundrum. . . . I have to be able to draw a line between victim and aggressor.”


Amanpour also believes the media should cover more. When given the full background and details of events, society pays attention to the news. “Individual Americans had an incredible reaction to the [2004 Indian Ocean] tsunami—much faster than their government’s reaction,” she said. “Americans are a very moral and compassionate people who believe in extending a helping hand, especially when they get the full facts instead of one-minute clips.” If the news fulfills its responsibility, as she sees it, the world can show its compassion and help promote freedom.


_Why does Amanpour believe the press has a responsibility to report all that they see? Are there situations in which it is acceptable to display partiality in reporting the news? Why or why not?_
====


Before the Internet, traditional media determined whether citizen photographs or video footage would become “news.” In 1991, a private citizen’s camcorder footage showed four police officers beating an African American motorist named Rodney King in Los Angeles. After appearing on local independent television station, KTLA-TV, and then the national news, the event began a national discussion on police brutality and ignited riots in Los Angeles.16 The agenda-setting power of traditional media has begun to be appropriated by social media and smartphones, however. Twitter, Facebook, YouTube, and other Internet sites allow witnesses to instantly upload images and accounts of events and forward the link to friends. Some uploads go viral and attract the attention of the mainstream media, but large network newscasts and major newspapers are still more powerful at initiating or changing a discussion.


In summary, the traditional agenda-setting role provided by the media has become conflated with social media platforms. This trend is good from the standpoint of more exposure by the public to news topics and events than was the case before the rise of social media. However, there is reason to worry about whether fact-checking, which traditional media carry out, will be done on social media. Meta, the corporate owner of prominent social media platforms Facebook and Instagram, recently made the decision, in the name of free speech, to no longer fact-check the social media posts on their platforms.17


The media also promote the public good by offering a platform for public debate and improving citizen awareness. Network news informs the electorate about national issues, elections, and international news. The _New York Times_, _Los Angeles Times_, _NBC Nightly News_, and other outlets make sure voters can easily find out what issues affect the nation. Is terrorism on the rise? Is the dollar weakening? The network news hosts national debates during presidential elections, broadcasts major presidential addresses, and interviews political leaders during times of crisis. Cable news networks now provide coverage of all these topics as well.


Local news has a larger job, despite small budgets and fewer resources (Figure 8.5). Local government and local economic policy have a strong and immediate effect on citizens. Is the city government planning on changing property tax rates? Will the school district change the way Common Core tests are administered? When and where is the next town hall meeting or public forum to be held? Local and social media provide a forum for protest and discussion of issues that matter to the community.







Figure 
8.5
 
Meetings of local governance, such as this meeting of the Independence City Council in Missouri, are rarely attended by more than gadflies and journalists. (credit: "MoBikeFed"/Flickr)


[.my1]
.案例
====
== Link to Learning



Want a snapshot of local and state political and policy news? The magazine _Governing_ keeps an eye on what is happening in each state, offering articles and analysis on events that occur across the country.
====


While journalists reporting the news try to present information in an unbiased fashion, sometimes the public seeks opinion and analysis of complicated issues that affect various populations differently, like healthcare reform and the Affordable Care Act. This type of coverage may come in the form of editorials, commentaries, Op-Ed columns, and blogs. These forums allow the editorial staff and informed columnists to express a personal belief and attempt to persuade. If opinion writers are trusted by the public, they have influence.


Walter Cronkite, reporting from Vietnam, had a loyal following. In a broadcast following the Tet Offensive in 1968, Cronkite expressed concern that the United States was mired in a conflict that would end in a stalemate.18 His coverage was based on opinion after viewing the war from the ground.19 Although the number of people supporting the war had dwindled by this time, Cronkite’s commentary bolstered opposition. Like editorials, commentaries contain opinion and are often written by specialists in a field. Larry Sabato, a prominent political science professor at the University of Virginia, occasionally writes his thoughts for the _New York Times_. These pieces are based on his expertise in politics and elections.20 Blogs offer more personalized coverage, addressing specific concerns and perspectives for a limited group of readers. As of 2021, the most popular blog on U.S. politics was _The Daily Kos_, a liberal blog with 25 million followers each month.21