= 009-2 (pure) The Two-Party System
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

[.my1]
.案例
====
== Learning Objectives


By the end of this section, you will be able to:


* Describe the effects of winner-take-all elections
* Compare plurality and proportional representation
* Describe the institutional, legal, and social forces that limit the number of parties
* Discuss the concepts of party alignment and realignment
====


One of the cornerstones of a vibrant democracy is citizens’ ability to influence government through voting. In order for that influence to be meaningful, citizens must send clear signals to their leaders about what they wish the government to do. It only makes sense, then, that a democracy will benefit if voters have several clearly differentiated options available to them at the polls on Election Day. Having these options means voters can select a candidate who more closely represents their own preferences on the important issues of the day. It also gives individuals who are considering voting a reason to participate. After all, you are more likely to vote if you care about who wins and who loses. The existence of two major parties, especially in our present era of strong parties, leads to sharp distinctions between the candidates and between the party organizations.


Why do we have two parties? The two-party system came into being because the structure of U.S. elections, with one seat tied to a geographic district, tends to lead to dominance by two major political parties. Even when there are other options on the ballot, most voters understand that minor parties have no real chance of winning even a single office. Hence, they vote for candidates of the two major parties in order to support a potential winner. Of the 535 members of the House and Senate, only a handful identify as something other than Republican or Democrat. Third parties have fared no better in presidential elections. No third-party candidate has ever won the presidency. Some historians or political scientists might consider Abraham Lincoln to have been such a candidate, but in 1860, the Republicans were a major party that had subsumed members of earlier parties, such as the Whig Party, and they were the only major party other than the Democratic Party.



== ELECTION RULES AND THE TWO-PARTY SYSTEM


A number of reasons have been suggested to explain why the structure of U.S. elections has resulted in a two-party system. Most of the blame has been placed on the process used to select its representatives. First, most elections at the state and national levels are winner-take-all: The candidate who receives the greatest overall number of votes wins. Winner-take-all elections with one representative elected for one geographic district allow voters to develop a personal relationship with “their” representative to the government. They know exactly whom to blame, or thank, for the actions of that government. But these elections also tend to limit the number of people who run for office. Otherwise-qualified candidates might not stand for election if they feel the incumbent or another candidate has an early advantage in the race. And since voters do not like to waste votes, third parties must convince voters they have a real chance of winning races before voters will take them seriously. This is a tall order given the vast resources and mobilization tools available to the existing parties, especially if an incumbent is one of the competitors. In turn, the likelihood that third-party challengers will lose an election bid makes it more difficult to raise funds to support later attempts.16


Winner-take-all systems of electing candidates to office, which exist in several countries other than the United States, require that the winner receive either the majority of votes or a plurality of the votes. U.S. elections are based on plurality voting. Plurality voting, commonly referred to as first-past-the-post, is based on the principle that the individual candidate with the most votes wins, whether or not they gain a majority (51 percent or greater) of the total votes cast. For instance, Abraham Lincoln won the presidency in 1860 even though he clearly lacked majority support given the number of candidates in the race. In 1860, four candidates competed for the presidency: Lincoln, a Republican; two Democrats, one from the northern wing of the party and one from the southern wing; and a member of the newly formed Constitutional Union Party, a southern party that wished to prevent the nation from dividing over the issue of slavery. Votes were split among all four parties, and Lincoln became president with only 40 percent of the vote, not a majority of votes cast but more than any of the other three candidates had received, and enough to give him a majority in the Electoral College, the body that ultimately decides presidential elections. Plurality voting has been justified as the simplest and most cost-effective method for identifying a victor in a democracy. A single election can be held on a single day, and the victor of the competition is easily selected. On the other hand, systems in which people vote for a single candidate in an individual district often cost more money because drawing district lines and registering voters according to district is often expensive and cumbersome.17


In a system in which individual candidates compete for individual seats representing unique geographic districts, a candidate must receive a fairly large number of votes in order to win. A political party that appeals to only a small percentage of voters will always lose to a party that is more popular.18 Because second-place (or lower) finishers will receive no reward for their efforts, those parties that do not attract enough supporters to finish first at least some of the time will eventually disappear because their supporters realize they have no hope of achieving success at the polls.19 The failure of third parties to win and the possibility that they will draw votes away from the party the voter had favored before—resulting in a win for the party the voter liked least—makes people hesitant to vote for the third party’s candidates a second time. This has been the fate of all U.S. third parties—the Populist Party, the Progressives, the Dixiecrats, the Reform Party, and others.


In a proportional electoral system, however, parties advertise who is on their candidate list and voters pick a party. Then, legislative seats are doled out to the parties based on the proportion of support each party receives. While the Green Party in the United States might not win a single congressional seat in some years thanks to plurality voting, in a proportional system, it stands a chance to get a few seats in the legislature regardless. For example, assume the Green Party gets 7 percent of the vote. In the United States, 7 percent will never be enough to win a single seat, shutting the Green candidates out of Congress entirely, whereas in a proportional system, the Green Party will get 7 percent of the total number of legislative seats available. Hence, it could get a foothold for its issues and perhaps increase its support over time. But with plurality voting, it doesn’t stand a chance.


Third parties, often born of frustration with the current system, attract supporters from one or both of the existing parties during an election but fail to attract enough votes to win. After the election is over, supporters experience remorse when their least-favorite candidate wins instead. For example, in the 2000 election, Ralph Nader ran for president as the candidate of the Green Party. Nader, a longtime consumer activist concerned with environmental issues and social justice, attracted many votes from people who usually voted for Democratic candidates. This has caused some to claim that Democratic nominee Al Gore lost the 2000 election to Republican George W. Bush, because Nader won Democratic votes in Florida that might otherwise have gone to Gore (Figure 9.5).20







Figure 
9.5
 
Ralph Nader, a longtime consumer advocate and crusader for social justice and the environment, campaigned as an independent in 2008 (a). However, in 2000, he ran for the presidency as the Green Party candidate. He received votes from many Democrats, and some analysts claim Nader’s campaign cost Al Gore the presidency—an ironic twist for a politician who would come to be known primarily for his environmental activism, even winning the Nobel Peace Prize in 2007 (b) for his efforts to inform the public about climate change. (credit a: modification of work by “Mely-o”/Flikr”; credit b: modification of work by “kangotraveler”/Flickr)

Abandoning plurality voting, even if the winner-take-all election were kept, would almost certainly increase the number of parties from which voters could choose. The easiest switch would be to a majoritarian voting scheme, in which a candidate wins only if they enjoy the support of a majority of voters. If no candidate wins a majority in the first round of voting, a run-off election is held among the top contenders. Some states conduct their primary elections within the two major political parties in this way.


A second way to increase the number of parties in the U.S. system is to abandon the winner-take-all approach. Rather than allowing voters to pick their representatives directly, many democracies have chosen to have voters pick their preferred party and allow the party to select the individuals who serve in government. The argument for this method is that it is ultimately the party and not the individual who will influence policy. Under this model of proportional representation, legislative seats are allocated to competing parties based on the total share of votes they receive in the election. As a result, any given election can have multiple winners, and voters who might prefer a smaller party over a major one have a chance to be represented in government (Figure 9.6).







Figure 
9.6
 
While a U.S. ballot (a) for first-past-the-post elections features candidates’ names, the ballots of proportional representation countries list the parties. On this Russian ballot (b), the voter is offered a choice of Social Democratic, Nationalist, Socialist, and Communist parties, among others.

One possible way to implement proportional representation in the United States is to allocate legislative seats based on the national level of support for each party’s presidential candidate, rather than on the results of individual races. If this method had been used in the 1996 elections, 8 percent of the seats in Congress would have gone to Ross Perot’s Reform Party because he won 8 percent of the votes cast. Even though Perot himself lost, his supporters would have been rewarded for their efforts with representatives who had a real voice in government. And Perot’s party’s chances of survival would have greatly increased.


Electoral rules are probably not the only reason the United States has a two-party system. We need only look at the number of parties in the British or Canadian systems, both of which are winner-take-all plurality systems like that in the United States, to see that it is possible to have more than two parties while still directly electing representatives. The two-party system is also rooted in U.S. history. The first parties, the Federalists and the Jeffersonian Republicans, disagreed about how much power should be given to the federal government, and differences over other important issues further strengthened this divide. Over time, these parties evolved into others by inheriting, for the most part, the general ideological positions and constituents of their predecessors, but no more than two major parties ever formed. Instead of parties arising based on region or ethnicity, various regions and ethnic groups sought a place in one of the two major parties.


Scholars of voting behavior have also suggested at least three other characteristics of the U.S. system that are likely to influence party outcomes: the Electoral College, demobilized ethnicity, and campaign and election laws. First, the United States has a presidential system in which the winner is selected not directly by the popular vote but indirectly by a group of electors known collectively as the Electoral College. The winner-take-all system also applies in the Electoral College. In all but two states (Maine and Nebraska), the total of the state’s electoral votes go to the candidate who wins the plurality of the popular vote in that state. Even if a new, third party is able to win the support of a lot of voters, it must be able to do so in several states in order to win enough electoral votes to have a chance of winning the presidency.21


Besides the existence of the Electoral College, political scientist Gary W. Cox has also suggested that the relative prosperity of the United States and the relative unity of its citizens have prevented the formation of “large dissenting groups” that might give support to third parties.22 This is similar to the argument that the United States does not have viable third parties, because none of its regions is dominated by mobilized ethnic minorities that have created political parties in order to defend and to address concerns solely of interest to that ethnic group. Such parties are common in other countries.


Finally, party success is strongly influenced by local election laws. Someone has to write the rules that govern elections, and those rules help to determine outcomes. In the United States, such rules have been written to make it easy for existing parties to secure a spot for their candidates in future elections. But some states create significant burdens for candidates who wish to run as independents or who choose to represent new parties. For example, one common practice is to require a candidate who does not have the support of a major party to ask registered voters to sign a petition. Sometimes, thousands of signatures are required before a candidate’s name can be placed on the ballot (Figure 9.7), but a small third party that does have large numbers of supporters in some states may not be able to secure enough signatures for this to happen.23







Figure 
9.7
 
Costa Constantinides (right), while campaigning in 2013 to represent the 22nd District on the New York City Council, said, “Few things are more important to a campaign than the petition process to get on the ballot. We were so pumped up to get started that we went out at 12:01 a.m. on June 4 to start collecting signatures right away!” Constantinides won the election later that year. (credit: modification of work by Costa Constantinides)


[.my1]
.案例
====
== Link to Learning



Visit Fair Vote for a discussion of ballot access laws across the country.
====


Given the obstacles to the formation of third parties, it is unlikely that serious challenges to the U.S. two-party system will emerge. But this does not mean that we should view it as entirely stable either. The U.S. party system is technically a loose organization of fifty different state parties and has undergone several considerable changes since its initial consolidation after the Civil War. Third-party movements may have played a role in some of these changes, but all resulted in a shifting of party loyalties among the U.S. electorate.




== CRITICAL ELECTIONS AND REALIGNMENT


Political parties exist for the purpose of winning elections in order to influence public policy. This requires them to build coalitions across a wide range of voters who share similar preferences. Since most U.S. voters identify as moderates,24  the historical tendency has been for the two parties to compete for “the middle” while also trying to mobilize their more loyal bases. If voters’ preferences remained stable for long periods of time, and if both parties did a good job of competing for their votes, we could expect Republicans and Democrats to be reasonably competitive in any given election. Election outcomes would probably be based on the way voters compared the parties on the most important events of the day rather than on electoral strategy.


There are many reasons we would be wrong in these expectations, however. First, the electorate isn’t entirely stable. Each generation of voters has been a bit different from the last. Over time, the United States has become more socially liberal, especially on topics related to race and gender, and Millennials—those born between 1981 and 1996 are more liberal than members of older generations.25 The electorate’s economic preferences have changed, and different social groups are likely to become more engaged in politics now than they did in the past. Surveys conducted in 2016, for example, revealed that candidates’ religion is less important to voters than it once was. Also, as young Latinos reach voting age, they seem more inclined to vote than do their parents, which may raise the traditionally low voting rates among this ethnic group.26 Internal population shifts and displacements have also occurred, as various regions have taken their turn experiencing economic growth or stagnation, and as new waves of immigrants have come to U.S. shores.

Additionally, the major parties have not always been unified in their approach to contesting elections. While we think of both Congress and the presidency as national offices, the reality is that congressional elections are sometimes more like local elections. Voters may reflect on their preferences for national policy when deciding whom to send to the Senate or the House of Representatives, but they are very likely to view national policy in the context of its effects on their area, their family, or themselves, not based on what is happening to the country as a whole. For example, while many voters want to reduce the federal budget, those over sixty-five are particularly concerned that no cuts to the Medicare program be made.27 One-third of those polled reported that “senior’s issues” were most important to them when voting for national officeholders.28 If they hope to keep their jobs, elected officials must thus be sensitive to preferences in their home constituencies as well as the preferences of their national party.


Finally, it sometimes happens that over a series of elections, parties may be unable or unwilling to adapt their positions to broader socio-demographic or economic forces. Parties need to be aware when society changes. If leaders refuse to recognize that public opinion has changed, the party is unlikely to win in the next election. For example, people who describe themselves as evangelical Christians are an important Republican constituency; they are also strongly opposed to abortion.29 Thus, even though the majority of U.S. adults believe abortion should be legal in at least some instances, such as when a pregnancy is the result of rape or incest, or threatens the life of the mother, the position of many Republican presidential candidates in 2016 was to oppose abortion in all cases.30 As a result, many women view the Republican Party as unsympathetic to their interests and are more likely to support Democratic candidates.31 Similarly (or simultaneously), groups that have felt that the party has served their causes in the past may decide to look elsewhere if they feel their needs are no longer being met. Either way, the party system will be upended as a result of a party realignment, or a shifting of party allegiances within the electorate (Table 9.1).32


Periods of Party Dominance and Realignment
|===
| Era | Party Systems and Realignments
| 1796–1824 | First Party System: Federalists (urban elites, southern planters, New England) oppose Democratic-Republicans (rural, small farmers and artisans, the South and the West).
| 1828–1856 | Second Party System: Democrats (the South, cities, farmers and artisans, immigrants) oppose Whigs (former Federalists, the North, middle class, native-born Americans).
| 1860–1892 | Third Party System: Republicans (former Whigs plus African Americans) control the presidency. Only one Democrat, Grover Cleveland, is elected president (1884, 1892).
| 1896–1932 | Fourth Party System: Republicans control the presidency. Only one Democrat, Woodrow Wilson, is elected president (1912, 1916). Challenges to major parties are raised by Populists and Progressives.
| 1932–1964 | Fifth Party System. Democrats control the presidency. Only one Republican, Dwight Eisenhower, is elected president (1952, 1956). Major party realignment as African Americans become part of the Democratic coalition.
| 1964–present | Sixth Party System. No one party controls the presidency. Ongoing realignment as southern White people and many members of the working class begin to vote for Republicans. Latino and Asian people immigrate, most of whom vote for Democrats. Moderate candidates increasingly find it harder to win nomination and election and the parties diverge on diversity initiatives.
|===


Table 
9.1
 
 
There have been six distinctive periods in U.S. history when new political parties have emerged, control of the presidency has shifted from one party to another, or significant changes in a party’s makeup have occurred.


One of the best-known party realignments occurred when Democrats moved to include African Americans and other minorities into their national coalition during the Great Depression. After the Civil War, Republicans, the party of Lincoln, were viewed as the party that had freed the enslaved. Their efforts to provide Black people with greater legal rights earned them the support of African Americans in both the South, where they were newly enfranchised, and the Northeast. When the Democrats, the party of the Confederacy, lost control of the South after the Civil War, Republicans ruled the region. However, the Democrats regained control of the South after the removal of the Union army in 1877. Democrats had largely supported slavery before the Civil War, and they opposed postwar efforts to integrate African Americans into society after they were liberated. In addition, Democrats in the North and Midwest drew their greatest support from labor union members and immigrants who viewed African Americans as competitors for jobs and government resources, and who thus tended to oppose the extension of rights to African Americans as much as their southern counterparts did.33


While the Democrats’ opposition to civil rights may have provided regional advantages in southern or urban elections, it was largely disastrous for national politics. From 1868 to 1931, Democratic candidates won just four of sixteen presidential elections. Two of these victories can be explained as a result of the spoiler effect of the Progressive Party in 1912 and then Woodrow Wilson’s reelection during World War I in 1916. This rather-dismal success rate suggested that a change in the governing coalition would be needed if the party were to have a chance at once again becoming a player on the national level.


That change began with the 1932 presidential campaign of Franklin Delano Roosevelt. FDR determined that his best path toward victory was to create a new coalition based not on region or ethnicity, but on the suffering of those hurt the most during the Great Depression. This alignment sought to bring African American voters in as a means of shoring up support in major urban areas and the Midwest, where many southern Black people had migrated in the decades after the Civil War in search of jobs and better education for their children, as well as to avoid many of the legal restrictions placed on them in the South. Roosevelt accomplished this realignment by promising assistance to those hurt most by the Depression, including African Americans.


The strategy worked. Roosevelt won the election with almost 58 percent of the popular vote and 472 Electoral College votes, compared to incumbent Herbert Hoover’s 59. The 1932 election is considered an example of a critical election, one that represents a sudden, clear, and long-term shift in voter allegiances. After this election, the political parties were largely identified as being divided by differences in their members’ socio-economic status. Those who favor stability of the current political and economic system tend to vote Republican, whereas those who would most benefit from changing the system usually favor Democratic candidates. Based on this alignment, the Democratic Party won the next five consecutive presidential elections and was able to build a political machine that dominated Congress into the 1990s, including holding an uninterrupted majority in the House of Representatives from 1954 until 1994.


The realignment of the parties did have consequences for
   Democrats. African Americans became an increasingly important part of the Democratic coalition in the 1940s through the 1960s, as the party took steps to support civil rights.34 Most changes were limited to the state level at first, but as civil rights reform moved to the national stage, rifts between northern and southern Democrats began to emerge.35 Southern Democrats became increasingly convinced that national efforts to provide social welfare and encourage racial integration were violating state sovereignty and social norms. By the 1970s, many had begun to shift their allegiance to the Republican Party, whose pro-business wing shared their opposition to the growing encroachment of the national government into what they viewed as state and local matters.36


Almost fifty years after it had begun, the realignment of the two political parties resulted in the flipping of post-Civil War allegiances, with urban areas and the Northeast now solidly Democratic, and the South and rural areas overwhelmingly voting Republican. The result today is a political system that provides Republicans with considerable advantages in rural areas and most parts of the Deep South.37 Democrats dominate urban politics and those parts of the South, known as the Black Belt, where the majority of residents are African American.