= 010-2 (pure) Collective Action and Interest Group Formation
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

[.my1]
.案例
====
== Learning Objectives


By the end of this section, you will be able to:


* Explain the concept of collective action and its effect on interest group formation
* Describe free riding and the reasons it occurs
* Discuss ways to overcome collective action problems
====


In any group project in which you have participated, you may have noticed that a small number of students did the bulk of the work while others did very little. Yet everyone received the same grade. Why do some do all the work, while others do little or none? How is it possible to get people to work when there is a disincentive to do so? This situation is an example of a collective action problem, and it exists in government as well as in public and private organizations. Whether it is Congress trying to pass a budget or an interest group trying to motivate members to contact lawmakers, organizations must overcome collective action problems to be productive. This is especially true of interest groups, whose formation and survival depend on members doing the necessary work to keep the group funded and operating.



== COLLECTIVE ACTION AND FREE RIDING


Collective action problems exist when people have a disincentive to take action.17 In his classic work, _The Logic of Collective Action_, economist Mancur Olson discussed the conditions under which collective action*s* problems would exist, and he noted that they were prevalent among organized interests. People tend not to act when the perceived benefit is insufficient to justify the costs associated with engaging in the action. Many citizens may have concerns about the appropriate level of taxation, gun control, or environmental protection, but these concerns are not necessarily strong enough for them to become politically active. In fact, most people take no action on most issues, either because they do not feel strongly enough or because their action will likely have little bearing on whether a given policy is adopted. Thus, there is a disincentive to call your member of Congress, because rarely will a single phone call sway a politician on an issue.


Why do some students elect to do little on a group project? The answer is that they likely prefer to do something else and realize they can receive the same grade as the rest of the group without contributing to the effort. This result is often termed the free rider problem, because some individuals can receive benefits (get a free ride) without helping to bear the cost. When National Public Radio (NPR) engages in a fund-raising effort to help maintain the station, many listeners will not contribute. Since it is unlikely that any one listener’s donation will be decisive in whether NPR has adequate funding to continue to operate, most listeners will not contribute to the costs but instead will free ride and continue to receive the benefits of listening.


Collective action problems and free riding occur in many other situations as well. If union membership is optional and all workers will receive a salary increase regardless of whether they make the time and money commitment to join, some workers may free ride. The benefits sought by unions, such as higher wages, collective bargaining rights, and safer working conditions, are often enjoyed by all workers regardless of whether they are members. Therefore, free riders can receive the benefit of the pay increase without helping defray the cost by paying dues, attending meetings or rallies, or joining protests, like that shown in Figure 10.5.







Figure 
10.5
 
 In December 2018, in protest against working conditions such as computer tracking and being required to work at a high rate of speed, around two hundred Amazon workers, mostly of East African descent, protested outside their workplace in Shakopee, Minnesota. (credit: modification of "East African worker protest against Amazon" by Fibonacci Blue/Wikimedia Commons, CC BY)

If free riding is so prevalent, why are there so many interest groups and why is interest group membership so high in the United States? One reason is that free riding can be overcome in a variety of ways. Olson argued, for instance, that some groups are better able than others to surmount collective action problems.18 They can sometimes maintain themselves by obtaining financial support from patrons outside the group.19 Groups with financial resources have an advantage in mobilizing in that they can offer incentives or hire a lobbyist. Smaller, well-organized groups also have an advantage. For one thing, opinions within smaller groups may be more similar, making it easier to reach consensus. It is also more difficult for members to free ride in a smaller group. In comparison, larger groups have a greater number of individuals and therefore more viewpoints to consider, making consensus more difficult. It may also be easier to free ride because it is less obvious in a large group when any single person does not contribute. However, if people do not lobby for their own interests, they may find that they are ignored, especially if smaller but more active groups with interests opposed to theirs lobby on behalf of themselves. Even though the United States is a democracy, policy is often made to suit the interests of the few instead of the needs of the many.


Group leaders also play an important role in overcoming collective action problems. For instance, political scientist Robert Salisbury suggests that group leaders will offer incentives to induce activity among individuals.20 Some offer material incentives, which are tangible benefits of joining a group. AARP, for example, offers discounts on hotel accommodations and insurance rates for its members, while dues are very low, so they can actually save money by joining. Group leaders may also offer solidary incentives, which provide the benefit of joining with others who have the same concerns or are similar in other ways. Some scholars suggest that people are naturally drawn to others with similar concerns. The NAACP is a civil rights groups concerned with promoting equality and eliminating discrimination based on race, and members may join to associate with others who have dealt with issues of inequality.21


Similarly, purposive incentives focus on the issues or causes promoted by the group. Someone concerned about protecting individual rights might join a group like the American Civil Liberties Union (ACLU) because it supports the liberties guaranteed in the U.S. Constitution, even the free expression of unpopular views.22 Members of the ACLU sometimes find the messages of those they defend (including Nazis and the Ku Klux Klan) deplorable, but they argue that the principle of protecting civil liberties is critical to U.S. democracy. In many ways, the organization’s stance is analogous to James Madison’s defense of factions mentioned earlier in this chapter. A commitment to protecting rights and liberties can serve as an incentive in overcoming collective action problems, because members or potential members care enough about the issues to join or participate. Thus, interest groups and their leadership will use whatever incentives they have at their disposal to overcome collective action problems and mobilize their members.


Finally, sometimes collective action problems are overcome because there is little choice about whether to join an organization. For example, some organizations may require membership in order to participate in a profession. To practice law, individuals may be required to join the American Bar Association or a state bar association. In the past, union membership could be required of workers, particularly in urban areas controlled by political machines consisting of a combination of parties, elected representatives, and interest groups.



[.my1]
.案例
====
== Link to Learning



Visit the Free Rider Problem for a closer look at free riding as a philosophical problem. Think of a situation you have been in where a collective action problem existed or someone engaged in free riding behavior. Why did the collective action problem or free riding occur? What could have been done to overcome the problem? How will knowledge of these problems affect the way you act in future group settings?
====




== DISTURBANCE THEORY AND COLLECTIVE ACTION


In addition to the factors discussed above that can help overcome collective action problems, external events can sometimes help mobilize groups and potential members. Some scholars argue that disturbance theory can explain why groups mobilize due to an event in the political, economic, or social environment.23 For example, in 1962, Rachel Carson published _Silent Spring_, a book exposing the dangers posed by pesticides such as DDT.24 The book served as a catalyst for individuals worried about the environment and the potential dangers of pesticides. The result was an increase in both the number of environmental interest groups, such as Greenpeace and American Rivers, and the number of members within them.


More recently, several shooting deaths of unarmed young African American men have raised awareness of racial issues in the United States and potential problems in policing practices, including racial disparities in treatment by police officers.25 In 2014, Ferguson, Missouri, erupted in protests and riots26 following a decision not to indict Darren Wilson, a White police officer, in the fatal shooting of Michael Brown, who had allegedly been involved in a theft at a local convenience store and ended up in a dispute with the officer.27 The incident mobilized groups representing civil rights, such as the protestors in Figure 10.6, as well as others supporting the interests of police officers. In May 2020, George Floyd died shortly after police officer Derek Chauvin leaned his knee on Floyd's neck for nine and half minutes, while Floyd was handcuffed and laying face down on the ground.28 Chauvin was later convicted of murder for the act. The protests that followed the release of video footage of the incident occurred in cities all across the United States, including Washington DC, and were much greater—bigger, more widespread, and more significant—than the Ferguson demonstrations. (A protest is an orderly exercise of the constitutional right of free speech and peaceful assembly. Rioting involves destroying property and/or attacking other people, which are crimes.)29






Figure 
10.6
 
On May 25, 2020, in Minneapolis, George Floyd was murdered while in police custody as onlookers recorded the incident; he has since been memorialized at the site of the crime (a). His death led to massive protests and calls to divest funds from police departments across the country, including in Minneapolis (b). (credit a: modification of "George Floyd Memorial" by Fibonacci Blue/Flickr, CC BY; credit b: modification of "Minneapolis City Council Pledges to Dismantle Police Department" by Tony Webster/Flickr, CC BY)

Both the _Silent Spring_ and Ferguson examples demonstrate the idea that people will naturally join groups in response to disturbances. Some mobilization efforts develop more slowly and may require the efforts of group leaders. Sometimes political candidates can push issues to the forefront, which may result in interest group mobilization. The recent focus on immigration, for example, has resulted in the mobilization of those in support of restrictive policies as well as those opposed to them (Figure 10.7). Rather than being a single disturbance, debate about immigration policy has ebbed and flowed in recent years, creating what might best be described as a series of minor disturbances. When, during his presidential candidacy, Donald Trump made controversial statements about immigrants, many rallied both for and against him.30







Figure 
10.7
 
Protestors take to the streets on different sides of the immigration issue. Some argue that the United States is a nation of immigrants, whereas others demonstrate in support of greater restrictions on immigration. (credit "Peace": modification of "Minneapolis protest against Arizona immigrant law SB 1070" by Fibonacci Blue/Flickr, CC BY; credit "We Are Not": modification of "We Are Not Criminals" by Michael Righi/Flickr, CC BY; credit "Secure": modification of "Immigration Protest" by Travis Wise/Flickr, CC BY; credit "Stop": modification of "Protest by the Tea Parties Against Amnesty and Illegal Immigration (and counter protest) in St. Paul on November 14, 2009" by Fibonacci Blue/Flickr, CC BY)


[.my1]
.案例
====
== Finding a Middle Ground



=== Student Activism and Apathy


Student behavior is somewhat paradoxical when it comes to political participation. On one hand, students have been very active on college campuses at various times over the past half-century. Many became politically active in the 1960s as part of the civil rights movement, with some joining campus groups that promoted civil rights, while others supported groups that opposed these rights. In the late 1960s and early 1970s, college campuses were very active in opposition to the Vietnam War. More recently, in 2015, students at the University of Missouri protested against the university system president, who was accused of not taking racial issues at the university seriously. The student protests were supported by civil rights groups like the NAACP, and their efforts culminated in the president’s resignation.31 In April 2021, hundreds of students, faculty, and staff gathered at the University of Richmond to protest the names of two campus buildings, one named after an enslaver and one after a segregationist.32


Yet at the same time, students participate by voting and joining groups at lower rates than members of other age cohorts. Why is it the case that students can play such an important role in facilitating political change in some cases, while at the same time they are typically less active than other demographic groups?


_Are there groups on campus that represent issues important to you? If not, find out what you could do to start such a group._
====