= 013-3 (pure) The Federal Court System
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

[.my1]
.案例
====
== Learning Objectives


By the end of this section, you will be able to:


* Describe the differences between the U.S. district courts, circuit courts, and the Supreme Court
* Explain the significance of precedent in the courts’ operations
* Describe how judges are selected for their positions
====


Congress has made numerous changes to the federal judicial system throughout the years, but the three-tiered structure of the system is quite clear-cut today. Federal cases typically begin at the lowest federal level, the district (or trial) court. Losing parties may appeal their case to the higher courts—first to the circuit courts, or U.S. courts of appeals, and then, if chosen by the justices, to the U.S. Supreme Court. Decisions of the higher courts are binding on the lower courts. The precedent set by each ruling, particularly by the Supreme Court’s decisions, both builds on principles and guidelines set by earlier cases and frames the ongoing operation of the courts, steering the direction of the entire system. Reliance on precedent has enabled the federal courts to operate with logic and consistency that has helped validate their role as the key interpreters of the Constitution and the law—a legitimacy particularly vital in the United States where citizens do not elect federal judges and justices but are still subject to their rulings.



== THE THREE TIERS OF FEDERAL COURTS


There are ninety-four U.S. district courts in the fifty states and U.S. territories, of which eighty-nine are in the states (at least one in each state). The others are in Washington, DC; Puerto Rico; Guam; the U.S. Virgin Islands; and the Northern Mariana Islands. These are the trial courts of the national system, in which federal cases are tried, witness testimony is heard, and evidence is presented. No district court crosses state lines, and a single judge oversees each one. Some cases are heard by a jury, and some are not.


There are thirteen U.S. courts of appeals, or circuit courts, eleven across the nation and two in Washington, DC (the DC circuit and the federal circuit courts), as illustrated in Figure 13.6. Each court is overseen by a rotating panel of three judges who do not hold trials but instead review the rulings of the trial (district) courts within their geographic circuit. As authorized by Congress, there are currently 179 such judges. The circuit courts are often referred to as the _intermediate appellate courts_ of the federal system, since their rulings can be appealed to the U.S. Supreme Court. Moreover, different circuits can hold legal and cultural views, which can lead to differing outcomes on similar legal questions. In such scenarios, clarification from the U.S. Supreme Court might be needed.







Figure 
13.6
 
There are thirteen judicial circuits: eleven in the geographical areas marked on the map and two in Washington, DC.

Today’s federal court system was not an overnight creation; it has been changing and transitioning for more than two hundred years through various acts of Congress. Since district courts are not called for in Article III of the Constitution, Congress established them and narrowly defined their jurisdiction, at first limiting them to handling only cases that arose within the district. Beginning in 1789 when there were just thirteen, the district courts became the basic organizational units of the federal judicial system. Gradually over the next hundred years, Congress expanded their jurisdiction, in particular over federal questions, which enables them to review constitutional issues and matters of federal law. In the Judicial Code of 1911, Congress made the U.S. district courts the sole general-jurisdiction trial courts of the federal judiciary, a role they had previously shared with the circuit courts.37


The circuit courts started out as the trial courts for most federal criminal cases and for some civil suits, including those initiated by the United States and those involving citizens of different states. But early on, they did not have their own judges; the local district judge and two Supreme Court justices formed each circuit court panel. (That is how the name “circuit” arose—judges in the early circuit courts traveled from town to town to hear cases, following prescribed paths or circuits to arrive at destinations where they were needed.38) Circuit courts also exercised appellate jurisdiction (meaning they receive appeals on federal district court cases) over most civil suits that originated in the district courts; however, that role ended in 1891, and their appellate jurisdiction was turned over to the newly created circuit courts, or U.S. courts of appeals. The original circuit courts—the ones that did not have “of appeals” added to their name—were abolished in 1911, fully replaced by these new circuit courts of appeals.39


While we often focus primarily on the district and circuit courts of the federal system, other federal trial courts exist that have more specialized jurisdictions, such as the Court of International Trade, Court of Federal Claims, and U.S. Tax Court. Specialized federal appeals courts include the Court of Appeals for the Armed Forces and the Court of Appeals for Veterans Claims. Cases from any of these courts may also be appealed to the Supreme Court, although that result is very rare.


The U.S. Supreme Court is composed of nine justices—one chief justice and eight associate justices. Typically, all nine preside over individual cases. There are many more circuit and federal district judges spread across the country, but only a limited number of judges preside over any given case. For example, in circuit courts it is a panel of three justices, while in federal district courts there is only a single judge presiding over a case. As the national court of last resort for all other courts in the system, the Supreme Court plays a vital role in setting the standards of interpretation that the lower courts follow. The Supreme Court’s decisions are binding across the nation and establish the precedent by which future cases are resolved in all the system’s tiers.


The U.S. court system operates on the principle of _stare decisis_ (Latin for _stand by things decided_), which means that today’s decisions are based largely on rulings from the past, and tomorrow’s rulings rely on what is decided today. _Stare decisis_ is especially important in the U.S. common law system, in which the consistency of precedent ensures greater certainty and stability in law and constitutional interpretation, and it also contributes to the solidity and legitimacy of the court system itself. As former Supreme Court justice Benjamin Cardozo summarized it years ago, “Adherence to precedent must then be the rule rather than the exception if litigants are to have faith in the even-handed administration of justice in the courts.”40



[.my1]
.案例
====
== Link to Learning



With a focus on federal courts and the public, this website reveals the different ways the federal courts affect the lives of U.S. citizens and how those citizens interact with the courts.
====


When the legal facts of one case are the same as the legal facts of another, _stare decisis_ dictates that they should be decided the same way, and judges are reluctant to disregard precedent without justification. However, that does not mean there is no flexibility or that new precedents or rulings can never be created. They often are. Certainly, court interpretations can change as times and circumstances change—and as the courts themselves change when new judges are selected and take their place on the bench. For example, the membership of the Supreme Court had changed entirely between _Plessey v. Ferguson_ (1896), which brought the doctrine of “separate but equal” and _Brown v._ _Board of Education_ (1954), which required integration.41




== THE SELECTION OF JUDGES


Judges fulfill a vital role in the U.S. judicial system and are carefully selected. At the federal level, the president nominates a candidate to a judgeship or justice position, and the nominee must be confirmed by a majority vote in the U.S. Senate, a function of the Senate’s “advice and consent” role. All judges and justices in the national courts serve lifetime terms of office.


The president sometimes chooses nominees from a list of candidates maintained by the American Bar Association, a national professional organization of lawyers.42 The president’s nominee is then discussed (and sometimes hotly debated) in the Senate Judiciary Committee. After a committee vote, the candidate must be confirmed by a majority vote of the full Senate. He or she is then sworn in, taking an oath of office to uphold the Constitution and the laws of the United States.


When a vacancy occurs in a lower federal court, by custom, the president consults with that state’s U.S. senators before making a nomination. Through such senatorial courtesy, senators exert considerable influence on the selection of judges in their state, especially those senators who share a party affiliation with the president. In many cases, a senator can block a proposed nominee just by voicing opposition. Thus, a presidential nominee typically does not get far without the support of the senators from the nominee’s home state.


Most presidential appointments to the federal judiciary go unnoticed by the public, but when a president has the rarer opportunity to make a Supreme Court appointment, it draws more attention. That is particularly true now, when many people get their news primarily from the Internet and social media. It was not surprising to see not only television news coverage but also blogs and tweets about President Obama’s nominees to the high court, Sonia Sotomayor and Elena Kagan, or President Trump's nominees Neil Gorsuch, Brett Kavanaugh, and Amy Coney Barrett. (Figure 13.7).





Figure 
13.7
 
President Obama made two appointments to the U.S. Supreme Court, Justices Sonia Sotomayor in 2009 and Elena Kagan (a) in 2010. Since their appointments, both justices have made rulings consistent with a more liberal ideology. President Trump made three appointments to the U.S. Supreme Court, Justice Neil Gorsuch (b) in 2017, Justice Brett Kavanaugh in 2018, and, most recently, Amy Coney Barrett (c) in October 2020, solidifying the Court's conservative majority. President Biden made one appointment to the U.S. Supreme Court, Justice Ketanji Brown Jackson (d) in 2022. (credit a: modification of "Elena Kagan, Associate Justice of the Supreme Court of the United States" by Steve Petteway, Collection of the Supreme Court of the United States/Wikimedia Commons, Public Domain; credit b: modification of "Associate Justice Neil M. Gorsuch" by Franz Jantzen, Supreme Court of the United States/Wikimedia Commons, Public Domain; credit c: modification of "Barrett's official portrait" by United States Supreme Court/Wikimedia Commons, Public Domain; credit d: Official portrait photograph of Justice Ketanji Brown Jackson, by United States Supreme Court, Public Domain)

Presidential nominees for the courts typically reflect the chief executive’s own ideological position. With a confirmed nominee serving a lifetime appointment, a president’s ideological legacy has the potential to live on long after the end of the term.43 President Obama surely considered the ideological leanings of his two Supreme Court appointees, and both Sotomayor and Kagan have consistently ruled in a more liberal ideological direction. The timing of the two nominations also dovetailed nicely with the Democratic Party’s gaining control of the Senate in the 111th Congress of 2009–2011, which helped guarantee their confirmations. Similarly, Republican Donald Trump was able to confirm his three nominees (Neil Gorsuch, Brett Kavanaugh, and Amy Coney Barrett) while Republicans controlled the Senate.


But some nominees turn out to be surprises or end up ruling in ways that the president who nominated them did not anticipate. Democratic-appointed judges sometimes side with conservatives, just as Republican-appointed judges sometimes side with liberals. Republican Dwight D. Eisenhower reportedly called his nomination of Earl Warren as chief justice—in an era that saw substantial broadening of civil and criminal rights—“the biggest damn fool mistake” he had ever made. Sandra Day O’Connor, nominated by Republican president Ronald Reagan, often became a champion for women’s rights. David Souter, nominated by Republican George H. W. Bush, more often than not sided with the Court’s liberal wing. Anthony Kennedy, a Reagan appointee who retired in the summer of 2018, was notorious as the Court’s swing vote, sometimes siding with the more conservative justices but sometimes not. Current chief justice John Roberts, though most typically an ardent member of the Court’s more conservative wing, has twice voted to uphold provisions of the Affordable Care Act Current justice Neil Gorsuch at times votes conservatively, then at other times (including on cases related to Native Americans, such as _McGirt v. Oklahoma_) breaks away to vote with the liberal wing of the court.

One of the reasons the framers of the U.S. Constitution included the provision that federal judges would be appointed for life was to provide the judicial branch with enough independence such that it could not easily be influenced by the political winds of the time. The nomination of Brett Kavanaugh tested that notion, as the process became intensely partisan within the Senate and with the nominee himself. (Kavanaugh's previous nomination to the U.S. Court of Appeals for the D.C. Circuit by President George W. Bush in 2003 also stalled for three years over charges of partisanship.) Sharp divisions emerged early in the confirmation process and an upset Kavanaugh called out several Democratic senators in his impassioned testimony in front of the Judiciary Committee. The high partisan drama of the Kavanaugh confirmation compelled Chief Justice Roberts to express concerns about the process and decry the threat of partisanship and conflict of interest on the Court.

Once a justice has started a lifetime tenure on the Court and years begin to pass, many people simply forget which president nominated him or her. For better or worse, sometimes it is only a controversial nominee who leaves a president’s legacy behind. For example, the Reagan presidency is often remembered for two controversial nominees to the Supreme Court—Robert Bork and Douglas Ginsburg, the former accused of taking an overly conservative and “extremist view of the Constitution”44 and the latter of having used marijuana while a student and then a professor at Harvard University (Figure 13.8). President George W. Bush’s nomination of Harriet Miers was withdrawn in the face of criticism from both sides of the political spectrum, questioning her ideological leanings and especially her qualifications, suggesting she was not ready for the job.45 After Miers’ withdrawal, the Senate went on to confirm Bush’s subsequent nomination of Samuel Alito, who remains on the Court today.






Figure 
13.8
 
Presidential nominations to the Supreme Court sometimes go awry, as illustrated by the failed nominations of Robert Bork (a), Douglas Ginsburg (b), and Harriet Miers (c).

Presidential legacy and controversial nominations notwithstanding, there is one certainty about the overall look of the federal court system: What was once a predominately White, male, Protestant institution is today much more diverse. As a look at Table 13.3 reveals, the membership of the Supreme Court has changed with the passing years.


Supreme Court Justice Firsts
|===
| First Catholic | Roger B. Taney (nominated in 1836)
| First Jew | Louis J. Brandeis (1916)
| First (and only) former U.S. President | William Howard Taft (1921)
| First African American | Thurgood Marshall (1967)
| First Woman | Sandra Day O’Connor (1981)
| First Hispanic American | Sonia Sotomayor (2009)
|===


Table 
13.3
 
 


The lower courts are also more diverse today. In the past few decades, the U.S. judiciary has expanded to include more women and minorities at both the federal and state levels.46 However, the number of women and people of color on the courts still lags behind the overall number of White men. As of 2021, the federal judiciary consists of 67 percent men and 33 percent women. In terms of race and ethnicity, 74 percent of federal judges are White, 12 percent African American, 8 percent Latinx, and 4 percent Asian American.47