= 013-4 (pure) The Supreme Court
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

[.my1]
.案例
====
== Learning Objectives


By the end of this section, you will be able to:


* Analyze the structure and important features of the Supreme Court
* Explain how the Supreme Court selects cases to hear
* Discuss the Supreme Court’s processes and procedures
====


The Supreme Court of the United States, sometimes abbreviated SCOTUS, is a one-of-a-kind institution. While a look at the Supreme Court typically focuses on the nine justices themselves, they represent only the top layer of an entire branch of government that includes many administrators, lawyers, and assistants who contribute to and help run the overall judicial system. The Court has its own set of rules for choosing cases, and it follows a unique set of procedures for hearing them. Its decisions not only affect the outcome of the individual case before the justices, but they also create lasting impacts on legal and constitutional interpretation for the future.



== THE STRUCTURE OF THE SUPREME COURT


The original court in 1789 had six justices, but Congress set the number at nine in 1869, and it has remained there ever since. There is one chief justice, who is the lead or highest-ranking judge on the Court, and eight associate justice*s*. All nine serve lifetime terms, after successful nomination by the president and confirmation by the Senate. There was discussion of expanding the court during Franklin D. Roosevelt's presidency and also during the 2020 presidential election. Nothing has come of court expansion, however.


The current court is fairly diverse in terms of gender, religion (Christians and Jews), ethnicity, and ideology, as well as length of tenure. Some justices have served for three decades, whereas others were only recently appointed by President Trump. Figure 13.9 lists the names of the nine justices serving on the Court as of June 2021 along with their year of appointment and the president who nominated them.







Figure 
13.9
 
The current composition of the Supreme Court includes six conservatives and three liberals.

Currently, there are six justices who are considered part of the Court’s more conservative wing—Chief Justice Roberts and Associate Justices Thomas, Alito, Gorsuch, Kavanaugh, and Barrett—while three are considered more liberal-leaning—Justices Breyer, Sotomayor, and Kagan (Figure 13.10).







Figure 
13.10
 
Justice Sonia Sotomayor (a) is part of the liberal wing of the current Supreme Court, whereas Justice Brett Kavanaugh (b) represents the conservative wing. Chief Justice John Roberts (c) leads the court as an ardent member of its more conservative wing but has recently expressed concern over partisanship on the court. (credit a: modification of "Sonia Sotomayor, U.S. Supreme Court justice" by Collection of the Supreme Court of the United States, Steve Petteway/Wikimedia Commons, Public Domain; credit b: modification of "Associate Justice Brett M. Kavanaugh" by The Collection of the Supreme Court of the United States/Wikimedia Commons, Public Domain; credit c: modification of "John G. Roberts, Jr., Chief Justice of the United States of America (cropped version of official photo)" by Steve Petteway/Wikimedia Commons, Public Domain)


[.my1]
.案例
====
== Link to Learning



While not formally connected with the public the way elected leaders are, the Supreme Court nonetheless offers visitors a great deal of information at its official website.


For unofficial summaries of recent Supreme Court cases or news about the Court, visit the Oyez website or SCOTUS blog.
====


In fact, none of the justices works completely in an ideological bubble. While their numerous opinions have revealed certain ideological tendencies, they still consider each case as it comes to them, and they don’t always rule in a consistently predictable or expected way. Furthermore, they don’t work exclusively on their own. Each justice has three or four law clerks, recent law school graduates who temporarily work for the justice, do research, help prepare the justice with background information, and assist with the writing of opinions. The law clerks’ work and recommendations influence whether the justices will choose to hear a case, as well as how they will rule. As the profile below reveals, the role of the clerks is as significant as it is varied.



[.my1]
.案例
====
== Insider Perspective



=== Profile of a United States Supreme Court Clerk


A Supreme Court clerkship is one of the most sought-after legal positions, giving “thirty-six young lawyers each year a chance to leave their fingerprints all over constitutional law.”48 A number of current and former justices were themselves clerks, including Chief Justice John Roberts, Justices Stephen Breyer and Elena Kagan, and former chief justice William Rehnquist.


Supreme Court clerks are often reluctant to share insider information about their experiences, but it is always fascinating and informative to hear about their jobs. Former clerk Philippa Scarlett, who worked for Justice Stephen Breyer, describes four main responsibilities:49


*Review the cases:* Clerks participate in a “_cert._ pool” (short for writ of _certiorari_, a request that the lower court send up its record of the case for review) and make recommendations about which cases the Court should choose to hear.


*Prepare the justices for oral argument:* Clerks analyze the filed briefs (short arguments explaining each party’s side of the case) and the law at issue in each case waiting to be heard.


*Research and draft judicial opinions:* Clerks do detailed research to assist justices in writing an opinion, whether it is the majority opinion or a dissenting or concurring opinion.


*Help with emergencies:* Clerks also assist the justices in deciding on emergency applications to the Court, many of which are applications by incarcerated people to stay their death sentences and are sometimes submitted within hours of a scheduled execution.


_Explain the role of law clerks in the Supreme Court system. What is your opinion about the role they play and the justices’ reliance on them?_
====




== HOW THE SUPREME COURT SELECTS CASES


The Supreme Court begins its annual session on the first Monday in October and ends late the following June. Every year, there are literally thousands of people who would like to have their case heard before the Supreme Court, but the justices will select only a handful to be placed on the docket, which is the list of cases scheduled on the Court’s calendar. The Court typically accepts fewer than 2 percent of the as many as ten thousand cases it is asked to review every year.50


Case names, written in italics, list the name of a petitioner versus a respondent, as in _Roe v. Wade_, for example.51 For a case on appeal, you can tell which party lost at the lower level of court by looking at the case name: The party unhappy with the decision of the lower court is the one bringing the appeal and is thus the petitioner, or the first-named party in the case. For example, in _Brown v. Board of Education_ (1954), Oliver Brown was one of the thirteen parents who brought suit against the Topeka public schools for discrimination based on racial segregation.


Most often, the petitioner is asking the Supreme Court to grant a writ of _certiorari_, a request that the lower court send up its record of the case for review. Once a writ of _certiorari_ (_cert_. for short) has been granted, the case is scheduled on the Court’s docket. The Supreme Court exercises discretion in the cases it chooses to hear, but four of the nine justices must vote to accept a case. This is called the Rule of Four.

For decisions about _cert_., the Court’s Rule 10 (Considerations Governing Review on Writ of _Certiorari_) takes precedence.52 The Court is more likely to grant _certiorari_ when there is a conflict on an issue between or among the lower courts. Examples of conflicts include (1) conflicting decisions among different courts of appeals on the same matter, (2) decisions by an appeals court or a state court conflicting with precedent, and (3) state court decisions that conflict with federal decisions. Occasionally, the Court will fast-track a case that has special urgency, such as _Bush v. Gore_ in the wake of the 2000 election.53

Past research indicated that the amount of interest-group activity surrounding a case before it is granted _cert._ has a significant impact on whether the Supreme Court puts the case on its agenda. The more activity, the more likely the case will be placed on the docket.54 But more recent research broadens that perspective, suggesting that too much interest-group activity when the Court is considering a case for its docket may actually have diminishing impact and that external actors may have less influence on the work of the Court than they have had in the past.55 Still, the Court takes into consideration external influences, not just from interest groups but also from the public, from media attention, and from a very key governmental actor—the solicitor general.


The solicitor general is the lawyer who represents the federal government before the Supreme Court: He or she decides which cases (in which the United States is a party) should be appealed from the lower courts and personally approves each one presented (Figure 13.11). Most of the cases the solicitor general brings to the Court will be given a place on the docket. About two-thirds of all Supreme Court cases involve the federal government.56


The solicitor general determines the position the government will take on a case. The attorneys of the office prepare and file the petitions and briefs, and the solicitor general (or an assistant) presents the oral arguments before the Court.






Figure 
13.11
 
Thurgood Marshall (a), who later served on the Supreme Court, was appointed solicitor general by Lyndon Johnson and was the first African American to hold the post. Noel Francisco (b) was the forty-seventh solicitor general of the United States, starting his term of office in September 2017.
In other cases in which the United States is not the petitioner or the respondent, the solicitor general may choose to intervene or comment as a third party. Before a case is granted _cert._, the justices will sometimes ask the solicitor general to comment on or file a brief in the case, indicating their potential interest in getting it on the docket. The solicitor general may also recommend that the justices decline to hear a case. Though research has shown that the solicitor general’s special influence on the Court is not unlimited, it remains quite significant. In particular, the Court does not always agree with the solicitor general, and “while justices are not lemmings who will unwittingly fall off legal cliffs for tortured solicitor general recommendations, they nevertheless often go along with them even when we least expect them to.”57


Some have credited Donald B. Verrilli, the solicitor general under President Obama, with holding special sway over the five-justice majority ruling on same-sex marriage in June 2015. Indeed, his position that denying same-sex couples the right to marry would mean “thousands and thousands of people are going to live out their lives and go to their deaths without their states ever recognizing the equal dignity of their relationships” became a foundational point of the Court’s opinion, written by then-Justice Anthony Kennedy.58 With such power over the Court, the solicitor general is sometimes referred to as “the tenth justice.”



== SUPREME COURT PROCEDURES


Once a case has been placed on the docket, briefs, or short arguments explaining each party’s view of the case, must be submitted—first by the petitioner putting forth the case, then by the respondent. After initial briefs have been filed, both parties may file subsequent briefs in response to the first. Likewise, people and groups that are not party to the case but are interested in its outcome may file an _amicus curiae_ (“friend of the court”) brief giving their opinion, analysis, and recommendations about how the Court should rule. Interest groups in particular can become heavily involved in trying to influence the judiciary by filing _amicus_ briefs—both before and after a case has been granted _cert_. And, as noted earlier, if the United States is not party to a case, the solicitor general may file an _amicus_ brief on the government’s behalf.


With briefs filed, the Court hears oral argument*s* in cases from October through April. The proceedings are quite ceremonial. When the Court is in session, the robed justices make a formal entrance into the courtroom to a standing audience and the sound of a banging gavel. The Court’s marshal presents them with a traditional chant: “The Honorable, the Chief Justice and the Associate Justices of the Supreme Court of the United States. Oyez! Oyez! Oyez! [Hear ye!] All persons having business before the Honorable, the Supreme Court of the United States, are admonished to draw near and give their attention, for the Court is now sitting. God save the United States and this Honorable Court!”59 It has not gone unnoticed that the Court, which has defended the First Amendment’s religious protection and the traditional separation of church and state, opens its every public session with a mention of God.


During oral arguments, each side’s lawyers have thirty minutes to make their legal case, though the justices often interrupt the presentations with questions. The justices consider oral arguments not as a forum for a lawyer to restate the merits of the case as written in the briefs, but as an opportunity to get answers to any questions they may have.60 When the United States is party to a case, the solicitor general (or one of the solicitor general's assistants) will argue the government’s position; even in other cases, the solicitor general may still be given time to express the government’s position on the dispute.


When oral arguments have been concluded, the justices have to decide the case, and they do so in conference, which is held in private twice a week when the Court is in session and once a week when it is not. The conference is also a time to discuss petitions for _certiorari_, but for those cases already heard, each justice may state their views on the case, ask questions, or raise concerns. The chief justice speaks first about a case, then each justice speaks in turn, in descending order of seniority, ending with the most recently appointed justice.61 The judges take an initial vote in private before the official announcement of their decisions is made public.


Oral arguments are open to the public, but cameras are not allowed in the courtroom, so the only picture we get is one drawn by an artist’s hand, an illustration or rendering. Cameras seem to be everywhere today, especially to provide security in places such as schools, public buildings, and retail stores, so the lack of live coverage of Supreme Court proceedings may seem unusual or old-fashioned. Over the years, groups have called for the Court to let go of this tradition and open its operations to more “sunshine” and greater transparency. Nevertheless, the justices have resisted the pressure and remain neither filmed nor photographed during oral arguments.62