= 014-3 (pure) Governors and State Legislatures
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

[.my1]
.案例
====
== Learning Objectives


By the end of this section, you will be able to:


* Identify the formal powers and responsibilities of modern-day governors
* List the basic functions performed by state legislatures
* Describe how state legislatures vary in size, diversity, party composition, and professionalism
====


Public opinion regarding Congress has reached a dismal low, with more than 80 percent of those surveyed in 2014 saying they do not feel most members of Congress deserve to be reelected.28 This attitude stems from partisan rivalry, media coverage that has capitalized on the conflict, fiscal shutdowns, and the general perception that Congress is no longer engaged in lawmaking.


The picture looks quite different at the subnational level, at least where lawmaking is concerned. State representatives and senators have been actively engaged in the lawmaking function, grabbing national attention at times for their controversial and highly partisan policies. Governors have been active in promoting their own policy agendas, either in cooperation with the state legislature or in opposition to it. Among the early 2016 Republican presidential contenders, nine were current or former state governors.29 In the Democratic field in 2020, four current or former state governors pursued the nomination.30 Increasingly, governors are using their office and the policies they have signed into law as a platform to gain national attention and to give voters a sense of their priorities should they ascend to the highest office in the country, the presidency.



== GOVERNORS IN CHARGE


Anyone elected to the office of governor assumes tremendous responsibility overnight. He or she becomes the spokesperson for the entire state and their political party, accepts blame or praise for handling decision-making in times of crisis, oversees the implementation of public policy, and helps shepherd legislation through the lawmaking process. These tasks require a great deal of skill and demand that governors exhibit different strengths and personality traits. Governors must learn to work well with other lawmakers, bureaucrats, cabinet officials, and with the citizens who elected them to office in the first place. The ongoing water crisis in Flint, Michigan, provides a good case in point. The COVID-19 pandemic put every governor in the hot seat as they considered decisions on masks, social distancing, and how to allocate federal funds (Figure 14.9).







Figure 
14.9
 
Michigan governor Gretchen Whitmer is briefed by the military on the potential to convert the TCF Center, a convention venue in downtown Detroit, into a medical site to care for persons with COVID-19. (credit: "Gretchen Whitmer is briefed on the capabilities and status of converting Detroit's TCF Center into an alternate care site for COVID-19 cases" by Air Force Master Sgt. Scott Thompson/Wikimedia Commons, Public Domain)

Governors have tremendous power over the legislative branch because they serve year-round and hold office alone. They also command wide press coverage by virtue of being the leading elected official in their state. Finally, while there are variations in degree across the states, most governors have more power relative to their state legislatures than does the U.S. president relative to the U.S. Congress. State executive power flows from factors such as the propensity of state legislatures to meet for only part of the year and their resulting reliance for information on the governor and his/her administration, stronger formal tools (e.g., line-item vetoes), budget-cutting discretion, and the fact that state legislators typically hold down another job besides that of legislator.


Three of the governor’s chief functions are to influence the legislative process through an executive budget proposal, a policy agenda, and vetoes. Just as the president gives a State of the Union address once a year, so too do governors give an annual State of the State address before the state legislature (Figure 14.10). In this speech, they discuss economic and political achievements, cite data that supports their accomplishments, and overview the major items on their legislative agenda. This speech signals to members of the state legislature what priorities are high on the governor’s list. Those who share the governor’s party affiliation will work with the governor to see these goals achieved. Given that governors need the cooperation of state legislators to get their bills introduced and steered through the lawmaking process, they make developing good relationships with lawmakers a priority. This can entail helping lawmakers address the concerns of their constituents, inviting legislators to social events and meals, and scheduling weekly meetings with legislative leaders and committee chairs to discuss policy.31






Figure 
14.10
 
Then-governor Nikki Haley delivers her 2015 State of the State address from the State House in Columbia, South Carolina, on January 21, 2015.
In addition to providing a basic list of policy priorities, governors also initiate a budget proposal in most states. Here they indicate funding priorities and spell out the amounts that will be appropriated to various state agencies under their discretion. When the economy is strong, governors may find themselves in the enviable position of having a surplus of tax revenue. That allows them some flexibility to decide whether they want to reduce taxes, direct funds toward a new initiative or program, allocate more funds to current programs, restore funds that were cut during times of fiscal distress, or save surplus revenue in a rainy-day account.32 Moreover, when cuts must be made, especially when the legislature is not in session, it is typically the governor or their finance director who makes the call on what gets cut.


Having introduced their priorities, the governor will work on the sidelines to steer favored bills through the legislative process. This may entail holding meetings with committee chairs or other influential lawmakers concerning their legislative priorities, working with the media to try to get favorable coverage of legislative priorities, targeting advocacy organizations to maintain pressure on resistant lawmakers, or testifying in legislative hearings about the possible impacts of the legislation.33


Once legislation has made its way through the lawmaking process, it comes to the governor’s desk for signature. If a governor signs the bill, it becomes law, and if the governor does not like the terms of the legislation they can veto, or reject, the entire bill. The bill can then become law only if a supermajority of legislators overrides the veto by voting in favor of the bill. Since it is difficult for two-thirds or more of state legislators to come together to override a veto (it requires many members of the governor’s own party to vote against the governor), the simple act of threatening to veto can be enough to get legislators to make concessions to the governor before the governor will pass the legislation.


The ability to veto legislation is just one of the formal powers governors have at their disposal. Formal powers are powers the governor may exercise that are specifically outlined in state constitutions or state law.34 Unlike U.S. presidents, many governors also have additional veto powers at their disposal, which enhances their ability to check the actions of the legislative branch. For instance, most states provide governors the power of the line-item veto. The line-item veto gives governors the ability to strike out a line or individual portions of a bill while letting the remainder pass into law. In addition, approximately 30 percent of governors have the power of an amendatory veto, which allows them to send a bill back to the legislature and request a specific amendment to it. Finally, a small number of governors, including the governor of Texas, also have the power of a reduction veto, which allows them to reduce the budget proposed in a piece of legislation.35



[.my1]
.案例
====
== Insider Perspective



=== The Vanna White and Frankenstein Vetoes in Wisconsin


Although the line-item, reduction, and amendatory vetoes give governors tremendous power to adjust legislation and to check the legislative branch, the most powerful and controversial vetoes, which have allowed governors to make selective deletions from a bill before signing, are dubbed the “Vanna White” veto and the “Frankenstein” veto. (Vanna White hosts the popular game show “Wheel of Fortune,” in which contestants guess what a phrase is based on a limited number of letters. As they guess the letters, White indicates the correct letters within the puzzle.) These powers have a colorful history in the state of Wisconsin, where voters have limited their influence on two occasions.

The first occurred in 1990 when voters passed a provision restricting the governor’s ability to use the “Vanna White” veto to change a bill by crossing out specific letters within a given word in order to create a new word. After this restriction took effect, the “Frankenstein” veto came into practice, which allowed a governor to remove individual words, numbers, or passages from a bill and string the remaining text together (like the fictional Dr. Frankenstein’s monster) in an effort to alter the original intent of the legislation.36


As an example of the Frankenstein veto, when an appropriations bill was sent to Wisconsin governor James E. Doyle for signature in 2005, Doyle scrapped over seven hundred words from a passage that would have appropriated millions of dollars to transportation. The words that remained in the bill redirected those funds to education. Lawmakers were outraged, but they were not able to override the veto.37


Then, in 2007, Governor Doyle used the veto once again to raise property taxes almost 2 percent.38 As a result of these controversial moves, the state house and senate passed a referendum to end the ability of governors to create a new sentence by combining words from two or more other sentences. A legislative referendum is a measure passed by the state legislature, such as a constitutional amendment, that goes to the voters for final approval.39 This referendum went to the voters for approval or rejection in the 2008 election, and the voters banned the practice. Governors in Wisconsin and all the states still have tremendous power to shape legislation, however, through the other types of vetoes discussed in this chapter.


_Should any state governor have the powers referred to as the “Vanna White” and “Frankenstein” vetoes? What advantage, if any, might state residents gain from their governor’s ability to alter the intent of a bill the legislature has approved and then sign it into law?_
====


Besides the formal power to prepare the budget and veto legislation, governors also have the power to call special sessions of the legislature for a wide array of reasons. For instance, sessions may be called to address budgetary issues during an economic downturn, to put together a redistricting plan, or to focus intensively on a particular issue the governor wants rectified immediately.40 In some states, only the governor has the power to call a special session, while in other states this power is shared between the legislative and the executive branches.



[.my1]
.案例
====
== Link to Learning



For more details on the calling of legislative Special Sessions visit the National Conference of State Legislatures website.
====


Although governors have a great deal of power in the legislative arena, this is not their only area of influence. First, as leaders in their political party, governors often work to raise money for other political figures who are up for reelection. A governor who has high public approval ratings may also make campaign appearances on behalf of candidates in tough reelection fights across the state. Governors can draw in supporters, contributions, and media attention that can be beneficial to other political aspirants, and the party will expect them to do their part to ensure the greatest possible number of victories for their candidates. Second, as the spokesperson for their state, governors make every effort to sell the state’s virtues and unique characteristics, whether to the media, to other citizens across the United States, to potential business owners, or to legislative leaders in Washington, DC. Governors want to project a positive image of their state that will encourage tourism, relocation, and economic investment within its boundaries. Collectively, governors make a mark through the National Governors Association, which is a powerful lobbying force in the nation’s capital.


For example, Texas governor Greg Abbott made headlines in 2015 for writing to the CEO of General Electric (GE), urging the company to relocate its corporate headquarters from Connecticut, which had just raised its corporate tax rate, to Texas.41 As his state’s spokesperson, Abbott promoted Texas’s friendly corporate tax structure and investment in transportation and education funding in hopes of enticing GE to relocate there and bring economic opportunities with it. The company has since decided to relocate to Boston, after receiving incentives, worth up to $145 million, from Massachusetts officials.42 Another example involved Texas governor Rick Perry touring California in 2014 in order to bring prospective businesses from the Golden State to Texas. In what was arguably the biggest round of lobbying by state and local governments toward a big business, Amazon recently conducted a search for a second corporate headquarters. After months of consideration, hundreds of op-eds extolling the virtues of locating in particular communities, Amazon picked two sites—Arlington, Virginia and Long Island City, New York—where it plans to spend over $2 billion at each site.43

In March 2015, the governor of Virginia, Terry McAuliffe, and the mayor of Chicago, Rahm Emanuel, both sent letters to corporate heads in Indiana after controversy erupted around the passage of that state’s Religious Freedom Restoration Act.44 This bill is designed to restrict government intrusion into people’s religious beliefs unless there is a compelling state interest. It also provides individuals and businesses with the ability to sue if they feel their religious rights have been violated. However, opponents feared the law would be used as a means to discriminate against members of the LGBTQ community, based on business owners’ religious objections to providing services for same-sex couples.45 In the media firestorm that followed the Indiana law’s passage, several prominent companies announced they would consider taking their business elsewhere or cancelling event contracts in the state if the bill were not amended.46 This led opportunistic leaders in the surrounding area to make appeals to these companies in the hope of luring them out of Indiana. Ultimately, the bill was clarified, likely due in part to corporate pressure on the state to do so.47 The clarification made it clear that the law could not be used to refuse employment, housing, or service based on an individual’s sexual orientation or gender identity.48


Controversial legislation like the Religious Freedom Restoration Act is only one of the many environmental factors that can make or break a governor’s reputation and popularity. Other challenges and crises that may face governors include severe weather, terrorist attacks, immigration challenges, and budget shortfalls.


New Jersey governor Chris Christie gained national attention in 2012 over his handling of the aftermath of Hurricane Sandy, which caused an estimated $65 billion worth of damage and cost the lives of over 150 individuals along the East Coast of the United States.49 Christie was famously photographed with President Obama during their joint tour of the damaged areas, and the governor subsequently praised the president for his response (Figure 14.11). Some later criticized Christie for his remarks because of the close proximity between the president’s visit and Election Day, along with the fact that the Republican governor and Democratic president were from opposite sides of the political aisle. Critics felt the governor had betrayed his party and that the publicity helped the president win reelection.50 Others praised the governor for cooperating with the president and reaching across the partisan divide to secure federal support for his state in a time of crisis.51







Figure 
14.11
 
New Jersey governor Chris Christie (right) hosted President Obama (center) during the president’s visit to the state in October 2012 following the destruction brought by Hurricane Sandy (a). After viewing the damage along the coastline of Brigantine, New Jersey, Christie and Obama visited residents at the Brigantine Beach Community Center (b).

If severe winter weather is forecasted or in the event of civil unrest, governors also have the power to call upon the National Guard to assist residents and first responders or aid in storm recovery (Figure 14.12). When governors declare a state of emergency, National Guard troops can be activated to go into local areas and assist with emergency efforts in whatever capacity they are needed.52 In 2015, many governors in the New England region called press conferences, worked with snow-removal crews and local government officials, set up emergency shelters, and activated travel bans or curfews in the face of crippling snowstorms.53 When winter storms fail to bring predicted levels of snow, however, politicians can be left to field criticism that they instigated unnecessary panic.54 However, it is a potential catch-22 because if storms end up worse than expected, elected leaders get hammered. For example, a lengthy freeze in south Texas, where even one winter day below freezing is highly unusual, led to a tragic disaster when electrical capacity failed, water pipes froze, and supplies of drinking water were deemed unsafe. A total of 111 people died during the episode and the Texas power grid was within minutes of a total collapse; government officials mandated blackouts, even as people experienced below freezing temperatures.55 Governors feel the weight of their decisions as they try to balance the political risks of overreacting and the human costs of letting the state be caught unprepared for these and other major natural disasters. As the chief spokesperson, they take all the blame or all the credit for their actions. With that said, it is important to note that presidents can enlist the National Guard for federal service as well.







Figure 
14.12
 
During the record-breaking freeze of 2021, President Biden met in Houston with Texas governor Greg Abbott and other state and local leaders. (credit: "President Biden tours an emergency operations center" by U.S. White House/Facebook, Public Domain)

Governors also have the power to spare or enhance the lives of individuals convicted of crimes in their state. Although they may choose to exercise this formal power only during the closing days of their term, if at all, most governors have the authority to grant pardons just as U.S. presidents do. A pardon absolves someone of blame for a crime and can secure their release from prison. Governors can also commute sentences, reducing the time an individual must serve,56 if there are doubts about the person’s guilt, concerns about mental health, or reason to feel the punishment was inappropriately harsh. In the past ten years, the governors of New Jersey and Illinois have commuted the sentences of all inmates on death row before repealing the death penalty in their states.57


Despite the tremendous formal powers that go with the job, being governor is still personally and professionally challenging. The demands of the job are likely to restrict time with family and require forgoing privacy. In addition, governors will often face circumstances beyond their control. For instance, the state legislature may include a majority of members who do not share the governor’s party affiliation. This can make working together more challenging and lead to less cooperation during the legislative session. Another challenge for governors is the plural executive, which refers to the fact that many state officials, such as the lieutenant governor, attorney general, and secretary of state are elected independently from the governor; hence, the governor has no direct control over them the way a president might have sway over U.S. executive officials. Governors can also face spending restrictions due to the economic climate in their state. They may have to make unpopular decisions that weaken their support among voters. The federal government can mandate that states perform some function without giving them any funds to do so. Finally, as we saw above, governors can be swept up in crises or natural disasters they did not anticipate and could not have foreseen. This can drain their energy and hamper their ability to generate good public policy.58




== THE FUNCTIONS OF STATE LEGISLATURES


State legislatures serve three primary functions. They perform a lawmaking function by researching, writing, and passing legislation. Members represent their districts and work to meet requests for help from citizens within it. Finally, legislatures perform an oversight function for the executive branch.


All state representatives and senators serve on committees that examine, research, investigate, and vote on legislation that relates to the committee’s purpose, such as agriculture, transportation, or education. The number of bills introduced in any given session varies. Some state legislatures have more restrictive rules concerning the number of bills any one member can sponsor. Legislators get ideas for bills from lobbyists of various types of interest groups, ranging from corporate groups to labor unions to advocacy organizations. Ideas for bills also come from laws passed in other state legislatures, from policy that diffuses from the federal government, from constituents or citizens in the officeholder’s district who approach them with problems they would like to see addressed with new laws, and from their own personal policy agenda, which they brought to office with them. Finally, as we explored previously, legislators also work with the governor’s agenda in the course of each legislative session, and they must pass a budget for their state either every year or every two years.


Most bills die in committee and never receive a second or third reading on the floor of the legislature. Lawmaking requires frequent consensus, not just among the legislators in a given house but also between the two chambers. In order for a bill to become law, it must pass through both the state house and the state senate in identical form before going to the governor’s desk for final signature.


Besides generating public policy, state legislatures try to represent the interests of their constituents. Edmund Burke was a political philosopher who theorized that representatives are either delegates or trustees.59 A delegate legislator represents the will of those who elected the legislator to office and acts in their expressed interest, even when it goes against personal belief about what is ultimately in the constituency’s best interest. On the other hand, trustee*s* believe they were elected to exercise their own judgment and know best because they have the time and expertise to study and understand an issue. Thus, a trustee will be willing to vote against the desire of the constituency so long as the trustee believes it is in the people’s best interest. A trustee will also be more likely to vote by conscience on issues that are personal to the trustee, such as on same-sex marriage or abortion rights.


Regardless of whether representatives adopt a delegate or a trustee mentality, they will all see it as their duty to address the concerns and needs of the people they represent. Typically, this will entail helping members in the district who need assistance or have problems with the government they want addressed. For instance, a constituent may write an elected official asking for help dealing with the bureaucracy such as in a decision made by tax commission, requesting a letter of recommendation for acceptance into a military academy, or proposing a piece of legislation the member can help turn into a law.


Legislators also try to bring particularized benefits back to their district. These benefits might include money that can be spent on infrastructure improvements or grants for research. Finally, members will accept requests from local government officials or other constituents to attend parades, ribbon-cutting ceremonies, or other celebratory events within their district (Figure 14.13). They will also work with teachers and faculty to visit classes or meet with students on field trips to the state capitol.







Figure 
14.13
 
To celebrate the opening of the new Loyola Avenue streetcar line, the mayor of New Orleans, Mitch Landrieu, marched with the St. Augustine “Marching 100” on January 28, 2013. (credit: U.S. Department of Transportation)

The last primary function of state legislators is to oversee the bureaucracy’s implementation of public policy, ensuring it occurs in the manner the legislature intended. State legislatures may request that agency heads provide testimony about spending in hearings, or they may investigate particular bureaucratic agencies to ensure that funds are being disbursed as desired.60 Since legislators have many other responsibilities and some meet for only a few months each year, they may wait to investigate until a constituent or lobbyist brings a problem to their attention.




== THE COMPOSITION OF STATE LEGISLATURES


In most states, the legislative function is divided between two bodies: a state house and a state senate. The only exception is Nebraska, which has a unicameral state senate of forty-nine members. State legislatures vary a great deal in terms of the number of legislators in the house and senate, the range of diversity across the membership, the partisan composition of the chamber relative to the governor’s affiliation, and the degree of legislative professionalism. This variation can lead to differences in the type of policies passed and the amount of power legislatures wield relative to that of the governor.


According to the National Conference of State Legislatures, at forty members, Alaska’s is the smallest state (or lower) house, while New Hampshire’s is the largest at four hundred. State senates range in size from twenty members in Alaska to sixty-seven members in Minnesota. The size of the institution can have consequences for the number of citizens each member represents; larger bodies have a smaller legislator-to-constituent ratio (assuming even populations). Larger institutions can also complicate legislative business because reaching consensus is more difficult with more participants.61


The term length in the state house is frequently two years, while in the state senate it is more commonly four years. These differences have consequences, too, because representatives in the state house, with the next election always right around the corner, will need to focus on their reelection campaigns more frequently than senators. On the other hand, state senators may have more time to focus on public policy and become policy generalists because they each must serve on multiple committees due to their smaller numbers.



[.my1]
.案例
====
== Link to Learning



The number of legislators and term length varies by state.
====


In 2025, according to the National Conference of State Legislatures, women made up 32.43 percent, or nearly one-third, of the nation’s state legislators. However, the number varies a great deal across states (Figure 14.14). For instance, in Arizona and Vermont, women account for around 42 percent of the state legislative membership. However, they make up less than 20 percent of the legislatures in Alabama, Arkansas, Mississippi, South Carolina, Tennessee, and West Virginia.62







Figure 
14.14
 
In 2025, only 32 percent of state legislators across the United States were women. However, the percentage of women in state legislature varies greatly from state to state.

Data on minority representatives is more difficult to obtain, but 2019 estimates from Emory University professor Beth Reingold paired with census estimates from 2019 show that African Americans and Latinos are both underrepresented in state government relative to their percentage of the population. In 2009, African Americans made up 9.3 percent of state legislators, compared to the 13.4 percent of the population they constitute nationwide. On the other hand, Latino representatives made up 4.4 percent of state legislators, despite accounting for 18.5 percent of the total population in the United States.63 , 64 The proportion of Latinos in the legislature is highest in Arizona, California, New Mexico, and Texas, while the proportion of African Americans is highest in Alabama, Georgia, and Mississippi.


Scholars in political science have spent a great deal of time researching the impact of women and minorities on the legislative process and on voter participation and trust. Some research demonstrates that female and minority representatives are more likely to advocate for policies that are of interest to or will benefit minorities, women, and children.65 Other research suggests that the presence of African American and Latino representatives increases voter turnout by these groups.66 Thus, increased diversity in state legislatures can have consequences for voter engagement and for the type of legislation pursued and passed within these bodies.



[.my1]
.案例
====
== Link to Learning



You can compare the numbers and percentages of women in state legislature, state by state.


You can also compare the numbers and percentages of African American representatives.


Similar information about Latino representation in state legislatures is also available.
====


As of early February 2025, twenty-eight had Republican majorities in the state house and senate, while in eighteen states Democratic majorities were the norm. In three states, Michigan, Minnesota and Pennsylvania, party control was split so that the Democratic Party maintained control of one house while the Republican Party maintained control of the other.67 Figure 14.15 illustrates the partisan composition across the United States. Note that states in New England and the West Coast are more likely to be unified behind the Democratic Party, while Republicans control legislatures throughout the South and in large parts of the Midwest. This alignment largely reflects differing political ideologies, with the more liberal, urban areas of the country leaning Democratic while the more conservative, rural areas are Republican.







Figure 
14.15
 
This map illustrates which party is in control of the house and senate within each state. When one party controls the senate and another party controls the house, the partisan composition is split.

Like diversity, party composition has consequences for policymaking. Governors who are not from the same party as the one controlling the legislature can find it more difficult to achieve their agenda. This governing circumstance is popularly referred to as _divided government_. In a time of divided government, a governor may have to work harder to build relationships and to broker consensus. In addition, when state party control is divided between the legislative and executive branches, the governor may find that legislators are more likely to muster the numbers to overturn at least some of their vetoes. In contrast, when the governor’s own party controls the legislature—a situation known as _unified government_—conventional wisdom suggests that they will have a smoother and more productive relationship with the legislature.


Party composition also matters for the overall legislative agenda. The party in power will elect party members to the top leadership posts in the state house and senate, and it will determine who sits on each of the committees. Committees are chaired by members of the majority party, and the composition of these committees is skewed toward members affiliated with the party in power. This gives the majority party an advantage in meeting its policy objectives and relegates the minority party to the position of obstructionists. In addition, while Republicans and Democrats are both concerned about education, health care, transportation, and other major policy areas, the two parties have different philosophies about what is in the best interest of their citizens and where funds should be allocated to meet those needs. The result is vastly different approaches to handling pressing public policy problems across the states.


As a whole, state legislatures have become progressively more professional. Political scientist Peverill Squire, at several points throughout his career, has measured the degree of state legislative professionalism with a ranking across the fifty states.68 Legislative professionalism is assessed according to three key factors: state legislators’ salary, the length of time they are in session, and the number of staff at their disposal. Members of professional or full-time legislatures tend to consider legislative service their full-time occupation, and they are paid enough not to require a second occupation. They also have larger staffs to assist with their work, and they tend to be in session for much of the year. On the other end of the spectrum are citizen, or part-time, legislatures. Representatives and senators in these legislatures do not enjoy the same perks as their counterparts in professional legislatures. Generally, salary is much lower and so is staff assistance. Members typically need to seek outside employment to supplement their income from legislative work, and the legislature will meet for only a brief period of time during the year.


Between these two extremes are hybrid legislatures. Their members are compensated at a higher rate than in citizen legislatures, but they are still likely to need outside employment to make an income equal to what they were making prior to taking office. These representatives and senators will have some staff assistance but not as much as in a professional legislature. Finally, members in hybrid legislatures will not consider their service to constitute a full-time occupation, but they will spend more than part of their time conducting legislative business. As Figure 14.16 shows, California, New York, and Pennsylvania are home to some of the most professional legislatures in the country. On the other hand, New Hampshire, North Dakota, Wyoming, and South Dakota are among the states that rank lowest on legislative professionalism.69







Figure 
14.16
 
This map illustrates the degree of professionalism within state legislatures. States in purple and green tend to meet full-time and have larger staff and salaries, while the opposite conditions exist in states colored in orange and red. States in blue fall somewhere in the middle of these conditions.

Like the other indicators discussed above, legislative professionalism also affects the business of state legislatures. In professional legislatures, elections tend to be more competitive, and the cost of running for a seat is higher because the benefits of being elected are greater. This makes these seats more attractive, and candidates will tend not to run unless they perceive themselves as well qualified. Since the benefits are more generous, elected officials will tend to stay in office longer and develop more policy expertise as a result. This experience can give professional legislatures an edge when dealing with the governor, because they are likely to be in session for about the same amount of time per year as the governor and have the necessary staff to assist them with researching and writing public policy.70



[.my1]
.案例
====
== Link to Learning



The legislative pay varies across states.


Compare the size of legislative staffs across states for the years 1979, 1988, 1996, 2003, and 2009.
====