= 016-3 (pure) Policy Arenas
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

[.my1]
.案例
====
== Learning Objectives


By the end of this section, you will be able to:


* Identify the key domestic arenas of public policy
* Describe the major social safety net programs
* List the key agencies responsible for promoting and regulating U.S. business and industry
====


In practice, public policy consists of specific programs that provide resources to members of society, create regulations that protect U.S. citizens, and attempt to equitably fund the government. We can broadly categorize most policies based on their goals or the sector of society they affect, although many, such as food stamps, serve multiple purposes. Implementing these policies costs hundreds of billions of dollars each year, and understanding the goals of this spending and where the money goes is of vital importance to citizens and students of politics alike.



== SOCIAL WELFARE POLICY


The U.S. government began developing a social welfare policy during the Great Depression of the 1930s. By the 1960s, social welfare had become a major function of the federal government—one to which most public policy funds are devoted—and had developed to serve several overlapping functions. First, social welfare policy is designed to ensure some level of equity in a democratic political system based on competitive, free-market economics. During the Great Depression, many politicians came to fear that the high unemployment and low-income levels plaguing society could threaten the stability of democracy, as was happening in European countries like Germany and Italy. The assumption in this thinking is that democratic systems work best when poverty is minimized. In societies operating in survival mode, in contrast, people tend to focus more on short-term problem-solving than on long-term planning. Second, social welfare policy creates an automatic stimulus for a society by building a safety net that can catch members of society who are suffering economic hardship through no fault of their own. For an individual family, this safety net makes the difference between eating and starving; for an entire economy, it could prevent an economic recession from sliding into a broader and more damaging depression.


One of the oldest and largest pieces of social welfare policy is Social Security, which cost the United States about $845 billion in 2014 alone.12 These costs are offset by a 12.4 percent payroll tax on all wages up to $118,500; employers and workers who are not self-employed split the bill for each worker, whereas the self-employed pay their entire share.13 Social Security was conceived as a solution to several problems inherent to the Industrial Era economy. First, by the 1920s and 1930s, an increasing number of workers were earning their living through manual or day-wage labor that depended on their ability to engage in physical activity (Figure 16.8). As their bodies weakened with age or if they were injured, their ability to provide for themselves and their families was compromised. Second, and of particular concern, were urban widows. During their working years, most American women stayed home to raise children and maintain the household while their husbands provided income. Should their husbands die or become injured, these women had no wage-earning skills with which to support themselves or their families.







Figure 
16.8
 
In 1930, when this Ford automotive plant opened in Long Beach, California, American workers had few economic protections to rely on if they were injured or could not maintain such physical activity as they aged.

Social Security addresses these concerns with three important tools. First and best known is the retirement benefit. After completing a minimum number of years of work, American workers may claim a form of pension upon reaching retirement age. It is often called an entitlement program since it guarantees benefits to a particular group, and virtually everyone will eventually qualify for the plan given the relatively low requirements for enrollment. The amount of money a worker receives is based loosely on that worker's lifetime earnings. Full retirement age was originally set at sixty-five, although changes in legislation have increased it to sixty-seven for workers born after 1959.14 A valuable added benefit is that, under certain circumstances, this income may also be claimed by the survivors of qualifying workers, such as spouses and minor children, even if they themselves did not have a wage income.


A second Social Security benefit is a disability payout, which the government distributes to workers who become unable to work due to disability. To qualify, workers must demonstrate that the injury or incapacitation will last at least twelve months. A third and final benefit is Supplemental Security Income, which provides supplemental income to adults or children with considerable disability or to the elderly who fall below an income threshold.


During the George W. Bush administration, Social Security became a highly politicized topic as the Republican Party sought to find a way of preventing what experts predicted would be the impending collapse of the Social Security system (Figure 16.9). In 1950, the ratio of workers paying into the program to beneficiaries receiving payments was 16.5 to 1. In 2020, that number stood at 2.8 to 1, and is expected to fall to 2.3 to 1 by 2035.15 Most predictions in fact suggest that, due to continuing demographic changes including slower population growth and an aging population, by 2033, the amount of revenue generated from payroll taxes will no longer be sufficient to cover costs. The Bush administration proposed avoiding this by privatizing the program, in effect, taking it out of the government’s hands and making individuals’ benefits variable instead of defined. The effort ultimately failed, and Social Security’s long-term viability continues to remain uncertain. Numerous other plans for saving the program have been proposed, including raising the retirement age, increasing payroll taxes (especially on the wealthy) by removing the income cap ($142,800 in 2021), and reducing payouts for wealthier retirees.16 None of these proposals have been able to gain traction, however.







Figure 
16.9
 
President George W. Bush discusses Social Security in Florida at the outset of his second term in 2005.

While Social Security was designed to provide cash payments to sustain elderly people and some people with disabilities, Medicare and Medicaid were intended to ensure that vulnerable populations have access to health care. Medicare, like Social Security, is an entitlement program funded through payroll taxes. Its purpose is to make sure that senior citizens and retirees have access to low-cost health care they might not otherwise have, because most U.S. citizens get their health insurance through their employers. Medicare provides three major forms of coverage: a guaranteed insurance benefit that helps cover major hospitalization, fee-based supplemental coverage that retirees can use to lower costs for doctor visits and other health expenses, and a prescription drug benefit. Medicare faces many of the same long-term challenges as Social Security, due to the same demographic shifts. Medicare also faces the problem that health care costs are rising significantly faster than inflation. In 2019, Medicare cost the federal government approximately $796 billion.17 , 18


Medicaid is a formula-based, health insurance program, which means beneficiaries must demonstrate they fall within a particular income category. Individuals in the Medicaid program receive a fairly comprehensive set of health benefits, although access to health care may be limited because fewer providers accept payments from the program (it pays them less for services than does Medicare). Medicaid differs dramatically from Medicare in that it is partially funded by states, many of which have reduced access to the program by setting the income threshold so low that few people qualify. The ACA (2010) sought to change that by providing more federal money to the states if they agreed to raise minimum income requirements. Twelve states have refused, which has helped to keep the overall costs of Medicaid lower, even though it has also left many people without health coverage they might receive if they lived elsewhere. Total costs for Medicaid in 2020 were about $627 billion, about $405 billion of which was paid by the federal government.19


Collectively, Social Security, Medicare, and Medicaid make up the lion’s share of total federal government spending, almost 48 percent in 2019. Several other smaller programs also provide income support to families. Most of these are formula-based, or means-tested, requiring citizens to meet certain maximum income requirements in order to qualify. A few examples are TANF, SNAP (also called food stamps), the unemployment insurance program, and various housing assistance programs. Collectively, these programs add up to a little over $361 billion.20




== SCIENCE, TECHNOLOGY, AND EDUCATION


After World War II ended, the United States quickly realized that it had to address two problems to secure its fiscal and national security future. The first was that more than ten million servicemen and women needed to be reintegrated into the workforce, and many lacked appreciable work skills. The second problem was that the United States’ success in its new conflict with the Soviet Union depended on the rapid development of a new, highly technical military-industrial complex. To confront these challenges, the U.S. government passed several important pieces of legislation to provide education assistance to workers and research dollars to industry. As the needs of American workers and industry have changed, many of these programs have evolved from their original purposes, but they still remain important pieces of the public policy debate.


Much of the nation’s science and technology policy benefits its military, for instance, in the form of research and development funding for a range of defense projects. The federal government still promotes research for civilian uses, mostly through the National Science Foundation, the National Institutes of Health, the National Aeronautics and Space Administration (NASA), and the National Oceanic and Atmospheric Administration. Recent debate over these agencies has focused on whether government funding is necessary or if private entities would be better suited. For example, although NASA continues to develop a replacement for the now-defunct U.S. space shuttle program (Figure 16.10), much of its workload is currently being performed by private companies working to develop their own space launch, resupply, and tourism programs.







Figure 
16.10
 
The launch of the Perseverance rover, part of NASA's Mars 2020 mission, from Cape Canaveral Air Force Station in Florida on July 30, 2020 (a). SpaceX headquarters in Hawthorne, California, during the Iridium-4 launch operations in December 2017 (b). Should the private sector fund space exploration programs rather than the government? (credit a: modification of "Mars 2020 Mission, Perseverance Rover Launch" by NASA/mars.nasa.gov, Public Domain; credit b: modification of "Iridium-4 Mission" by Official SpaceX Photos/Wikimedia Commons, CC 0)

The problem of trying to direct and fund the education of a modern U.S. workforce is familiar to many students of American government. Educational systems exist to carry out two distinct and lofty goals. First, they educate and provide opportunity to a learned society of individuals who can together govern society and run communities. Second, our educational institutions provide practical training for students to make a living. Therefore, governments and communities must simultaneously educate young people to be creative and responsible citizens while also providing practical job training programs for the workforces that communities, states, and the country need.


Historically, education has largely been the job of the states. While they have provided a very robust K–12 public education system, the national government has never moved to create an equivalent system of national higher education academies or universities as many other countries have done. As the need to keep the nation competitive with others became more pressing, however, the U.S. government did step in to direct its education dollars toward creating greater equity and ease of access to the existing public and private systems.


The overwhelming portion of the federal government’s higher education money is spent on student loans, grants, and work-study programs. Resources are set aside to cover job-retraining programs for individuals who lack private-sector skills or who need to be retrained to meet changes in the economy’s demands for the labor force. National policy toward elementary and secondary education programs has typically focused on increasing resources available to school districts for nontraditional programs (such as preschool and special needs), or helping poorer schools stay competitive with wealthier institutions.




== BUSINESS STIMULUS AND REGULATION


A final key aspect of domestic policy is the growth and regulation of business. The size and strength of the economy is very important to politicians whose jobs depend on citizens’ believing in their own future prosperity. At the same time, people in the United States want to live in a world where they feel safe from unfair or environmentally damaging business practices. These desires have forced the government to perform a delicate balancing act between programs that help grow the economy by providing benefits to the business sector and those that protect consumers, often by curtailing or regulating the business sector.


Two of the largest recipients of government aid to business are agriculture and energy. Both are multi-billion dollar industries concentrated in rural and/or electorally influential states. Because voters are affected by the health of these sectors every time they pay their grocery or utility bill, the U.S. government has chosen to provide significant agriculture and energy subsidies to cover the risks inherent in the unpredictability of the weather and oil exploration. Government subsidies also protect these industries’ profitability. These two purposes have even overlapped in the government’s controversial decision to subsidize the production of ethanol, a fuel source similar to gasoline but generated from corn.


When it comes to regulation, the federal government has created several agencies responsible for providing for everything from worker safety (OSHA, the Occupational Safety and Health Administration), to food safety (FDA), to consumer protection, where the recently created Bureau of Consumer Protection ensures that businesses do not mislead consumers with deceptive or manipulative practices. Another prominent federal agency, the EPA, is charged with ensuring that businesses do not excessively pollute the nation’s air or waterways. A complex array of additional regulatory agencies governs specific industries such as banking and finance, which are detailed later in this chapter.



[.my1]
.案例
====
== Link to Learning



The policy areas we’ve described so far fall far short of forming an exhaustive list. This site contains the major topic categories of substantive policy in U.S. government, according to the Policy Agendas Project. View subcategories by clicking on the major topic categories.
====