= 016-1 (pure) What Is Public Policy?
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

[.my1]
.案例
====
== Learning Objectives


By the end of this section, you will be able to:


* Explain the concept of public policy
* Discuss examples of public policy in action
====


It is easy to imagine that when designers engineer a product, like a car, they do so with the intent of satisfying the consumer. But the design of any complicated product must take into account the needs of regulators, transporters, assembly line workers, parts suppliers, and myriad other participants in the manufacture and shipment process. And manufacturers must also be aware that consumer tastes are fickle: A gas-guzzling sports car may appeal to an unmarried twenty-something with no children; but what happens to product satisfaction when gas prices fluctuate, or the individual gets married and has children?


In many ways, the process of designing domestic policy isn’t that much different. The government, just like auto companies, needs to ensure that its citizen-consumers have access to an array of goods and services. And just as in auto companies, a wide range of actors is engaged in figuring out how to do it. Sometimes, this process effectively provides policies that benefit citizens. But just as often, the process of policymaking is muddied by the demands of competing interests with different opinions about society’s needs or the role that government should play in meeting them. To understand why, we begin by thinking about what we mean by the term “public policy.”



== PUBLIC POLICY DEFINED


One approach to thinking about public policy is to see it as the broad strategy government uses to do its job. More formally, it is the relatively stable set of purposive governmental actions that address matters of concern to some part of society.1 This description is useful in that it helps to explain both what public policy is and what it isn’t. First, public policy is a guide to legislative action that is more or less fixed for long periods of time, not just short-term fixes or single legislative acts. Policy also doesn’t happen by accident, and it is rarely formed simply as the result of the campaign promises of a single elected official, even the president. While elected officials are often important in shaping policy, most policy outcomes are the result of considerable debate, compromise, and refinement that happen over years and are finalized only after input from multiple institutions within government as well as from interest groups and the public.


Consider the example of health care expansion. A follower of politics in the news media may come away thinking the reforms implemented in 2010 were as sudden as they were sweeping, having been developed in the final weeks before they were enacted. The reality is that expanding health care access had actually been a priority of the Democratic Party for several decades. What may have seemed like a policy developed over a period of months was in fact formed after years of analysis, reflection upon existing policy, and even trial implementation of similar types of programs at the state level. Even before passage of the ACA (2010), which expanded health care coverage to millions, and of the HCERA (2010), more than 50 percent of all health care expenditures in the United States already came from federal government programs such as Medicare and Medicaid. Several House and Senate members from both parties along with First Lady Hillary Clinton had proposed significant expansions in federal health care policy during the Democratic administration of Bill Clinton, providing a number of different options for any eventual health care overhaul.2 Much of what became the ACA was drawn from proposals originally developed at the state level, by none other than Obama’s 2012 Republican presidential opponent Mitt Romney when he was governor of Massachusetts.3


In addition to being thoughtful and generally stable, public policy deals with issues of concern to some large segment of society, as opposed to matters of interest only to individuals or a small group of people. Governments frequently interact with individual actors like citizens, corporations, or other countries. They may even pass highly specialized pieces of legislation, known as private bills, which confer specific privileges on individual entities. But public policy covers only those issues that are of interest to larger segments of society or that directly or indirectly affect society as a whole. Paying off the loans of a specific individual would not be public policy, but creating a process for loan forgiveness available to certain types of borrowers (such as those who provide a public service by becoming teachers) would certainly rise to the level of public policy.


A final important characteristic of public policy is that it is more than just the actions of government; it also includes the behaviors or outcomes that government action creates. Policy can even be made when government refuses to act in ways that would change the status quo when circumstances or public opinion begin to shift.4 For example, much of the debate over gun safety policy in the United States has centered on the unwillingness of Congress to act, even in the face of public opinion that supports some changes to gun policy. In fact, one of the last major changes occurred in 2004, when lawmakers’ inaction resulted in the expiration of a piece of legislation known as the Federal Assault Weapons Ban (1994).5




== PUBLIC POLICY AS OUTCOMES


Governments rarely want to keep their policies a secret. Elected officials want to be able to take credit for the things they have done to help their constituents, and their opponents are all too willing to cast blame when policy initiatives fail. We can therefore think of policy as the formal expression of what elected or appointed officials are trying to accomplish. In passing the HCERA (2010), Congress declared its policy through an act that directed how it would appropriate money. The president can also implement or change policy through an executive order, which offers instructions about how to implement law under the president's discretion (Figure 16.2). Finally, policy changes can come as a result of court actions or opinions, such as _Brown v. Board of Education of Topeka_ (1954), which formally ended school segregation in the United States.6







Figure 
16.2
 
President Obama signs a 2009 executive order to accelerate the federal government’s recruitment and hiring of returning veterans. Executive orders are an expression of public policy undertaken at the discretion of the president.

Typically, elected and even high-ranking appointed officials lack either the specific expertise or tools needed to successfully create and implement public policy on their own. They turn instead to the vast government bureaucracy to provide policy guidance. For example, when Congress passed the Clean Water Act (1972), it dictated that steps should be taken to improve water quality throughout the country. But it ultimately left it to the bureaucracy to figure out exactly how ‘clean’ water needed to be. In doing so, Congress provided the Environmental Protection Agency (EPA) with discretion to determine how much pollution is allowed in U.S. waterways.


There is one more way of thinking about policy outcomes: in terms of winners and losers. Almost by definition, public policy promotes certain types of behavior while punishing others. So, the individuals or corporations that a policy favors are most likely to benefit, or win, whereas those the policy ignores or punishes are likely to lose. Even the best-intended policies can have unintended consequences and may even ultimately harm someone, if only those who must pay for the policy through higher taxes. A policy designed to encourage students to go to liberal arts colleges may cause trade school enrollment to decline. Strategies to promote diversity in higher education may make it more difficult for qualified White or male applicants to get accepted into competitive programs. Efforts to clean up drinking water supplies may make companies less competitive and cost employees their livelihood. Even something that seems to help everyone, such as promoting charitable giving through tax incentives, runs the risk of lowering tax revenues from the rich (who contribute a greater share of their income to charity) and shifting tax burdens to the poor (who must spend a higher share of their income to achieve a desired standard of living). And while policy pronouncements and bureaucratic actions are certainly meant to rationalize policy, it is whether a given policy helps or hurts constituents (or is perceived to do so) that ultimately determines how voters will react toward the government in future elections.



[.my1]
.案例
====
== Finding a Middle Ground



=== The Social Safety Net


During the Great Depression of the 1930s, the United States created a set of policies and programs that constituted a social safety net for the millions who had lost their jobs, their homes, and their savings (Figure 16.3). Under President Franklin Delano Roosevelt, the federal government began programs like the Work Progress Administration and Civilian Conservation Corps to combat unemployment and the Home Owners’ Loan Corporation to refinance Depression-related mortgage debts. As the effects of the Depression eased, the government phased out many of these programs. Other programs, like Social Security or the minimum wage, remain an important part of the way the government takes care of the vulnerable members of its population. The federal government has also added further social support programs, like Medicaid, Medicare, and the Special Supplemental Nutrition Program for Women, Infants, and Children, to ensure a baseline or minimal standard of living for all, even in the direst of times.







Figure 
16.3
 
In 1937, during the Great Depression, families in Calipatria, California, waited in line for relief checks, part of the federal government’s newly introduced social safety net. (credit: modification of work by the Library of Congress)

In recent decades, however, some have criticized these safety net programs for inefficiency and for incentivizing welfare dependence. They deride “government leeches” who use food stamps to buy lobster or other seemingly inappropriate items. Critics deeply resent the use of taxpayer money to relieve social problems like unemployment and poverty; workers who may themselves be struggling to put food on the table or pay the mortgage feel their hard-earned money should not support other families. “If I can get by without government support,” the reasoning goes, “those welfare families can do the same. Their poverty is not my problem.”


So where should the government draw the line? While there have been some instances of welfare fraud, the welfare reforms of the 1990s have made long-term dependence on the federal government less likely as the welfare safety net was pushed to the states. And with the income gap between the richest and the poorest at its highest level in history, this topic is likely to continue to receive much discussion in the coming years.


_Where is the middle ground in the public policy argument over the social safety net? How can the government protect its most vulnerable citizens without placing an undue burden on others?_
====



[.my1]
.案例
====
== Link to Learning



Explore historical data on United States budgets and spending from 1940 to the present from the Office of Management and Budget.
====