= 0181
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast Number 181, “Company Profiles”
This is English as a Second Language Podcast Episode Number 181. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Today's podcast is called, “Company Profiles.” Let's get started.
[start of story]
Roberta: What are you working on?
Lee: Oh, I'm writing the company profiles for the businesses participating in the meeting next month. Do you have a minute to give me some feedback?
Roberta: Sure, what do you have so far?
Lee: I've started to write the ones for Landrun and Max Electronics. This is what I have for Lundrun so far: “A Fortune 500 company, Lundrun is a world leader in car manufacturing. Founded in 1936, Lundrun today is a $90 billion dollar company that sets a standard in the industry.”
Roberta: That's pretty good. Don't forget to mention that their headquarters are in Chicago.
Lee: Oh, yeah, I'll make sure I add that. Okay, here's what I have for Max Electronics: “Max Electronics is a Frankfurt-based company that has been a pioneer in the manufacturing of home electronics for over 75 years. The company has a global network of 1,500 distributors and has stores in 53 countries worldwide.”
Roberta: That's a good start. Why don't you pass them by me when you're done and I can give you some more feedback?
Lee: Yeah, I'll do that. Thanks a lot.
[end of story]
The title of this podcast is, “Company Profiles.” A “profile” is a description of someone or something, usually it’s about a person, but it can also be, in this case, about a company. So, it gives basic information. It's a basic description, not detailed, usually not very, very long, but enough information to allow you to understand this person or to understand this company.
Our dialogue begins with Roberta asking Lee, "What are you working on?" “To be working on,” here means, What are you doing? What are you working on? What project are you working on? And, Lee says, "I'm writing the company profiles for the businesses participating in the meeting next month." So, they're having a meeting next month with different companies, different businesses and Lee is writing a description, a short description of each one of these companies. He's writing a profile.
He then asks Roberta, "Do you have a minute to give me some feedback?" "Do you have a minute to give me some feedback?" That expression, "Do you have a minute to do (something)" is a way of asking someone if they have time right now to help you. We sometimes use this expression without the verb at the end. We sometimes say, "Do you have a minute?" And, that means, "Do you have time right now to help me?" In this case, she says, he says rather, "Do you have a minute to give me some feedback?" “Feedback” is information, reactions that you give to someone about something that they have done. So, feedback would be, for example, if you emailed us here at ESL Podcast and said, "You're doing a great job!" or "You're doing a terrible job!" That would be feedback. You can email us about what a great job we're doing, by the way. If you don't like what we're doing, Well, that's okay. We want to hear that, too, but not as much as we want to hear about the good job.
Well, Roberta says, sure, she has time to help him. "What do you have so far?" So, she's asking him, "How much work have you done?" "Tell me what you have done up to this point, or up to this minute." That's the meaning of the expression, "so far." "So far, I have $100 saved in my bank account to buy a new computer." Up to this point, up to today, that's how much money I have saved, so far. Lee says that he started to write the profile for two companies. One of the companies called Lundrun, which is not a real company, he describes as a “Fortune 500 company.” “Fortune” is a famous business magazine in the United States, Fortunemagazine. And, every year, they have a list of the 500 biggest companies in the United States and this is called the Fortune 500. And, everyone in business knows what this means. So, if you say to an American businesswoman, "Is your company in the Fortune 500?" They say, "Yes, we're a Fortune 500 company.” “We're one of the 500 biggest companies." Well, Lundrun is a Fortune 500 company. The word “fortune,” by the way, can mean a lot of money. "He has a fortune," means he has a lot of money.
Well, Lundren is also a world leader in car manufacturing. A “world leader,” you can guess, means a company that is one of the best in the world. They're a world leader in car manufacturing. The verb, “to manufacture,” means to make. So, they are one of the world's largest car makers, or car manufacturers, that would be the noun. Someone who manufactures something is a “manufacturer.” We can also call it manufacturing, with an -ing at the end. So, they're a world leader in car manufacturing, the making of automobiles. This company was founded in 1936. When we say a company is founded, or an organization is founded, we mean this is when they began, this is when they started. You can say the United States was founded in 1789, when we had our first Constitution. Well, actually it was our second Constitution. But, we usually talk about the founding of a country, or the founding of an organization or a company. And, the people who start a company, or start in the case of the United States, a country, are called the founders. And, the founders are people who are the ones who begin something, who start something.
Well, Lundren was founded in 1936 and it's now a $90 billion dollar company which is a lot of money, I think. I have a billion or so, so $90 billion is 90 times what I have. Well, this is a Fortune 500 company, a $90 billion dollar company that sets a standard in the industry. “To set a standard” or “to set the standard,” which is another expression, maybe a little more common, means that they are the leaders and what they do, everyone else watches, everyone tries to do the same because they have a very high level of quality, they do things very well, they set the standard or they set a standard. In general, the word “standard” is, it's a goal, it's an objective, it's something that you want to do, but usually these are things that are, that many people agree on. So, in California, for example, we have standards for our schools. And, this is a list of things that children are supposed to know at each grade. That's a standard. So, in this case, this case is setting a standard, or setting the standard in the industry, means all of the other companies, the other car manufacturers are watching this company to see what they do.
Roberta says the description is pretty good that Lee has written. She says, "Don't forget to mention that their headquarters are in Chicago." A company's “headquarters” is where the company has its many offices. The Center for Educational Development has its headquarters in Los Angeles, or its world headquarters, for the entire world, here in Los Angeles. Well, there are different companies that have their headquarters here in Los Angeles. Most of the movie studios have their headquarters here, the companies that make movies. The computer companies have, many of them have their headquarters in Northern California, in San Francisco or in San Jose, in towns that are near those cities in Northern California, that's where their headquarters are. Well, Lundrun's headquarters are in Chicago. Lee says, "Oh yeah, I'll make sure I add that." I'll put that in the description.
Then he reads his description for the second company, Max Electronics. He says, "Max Electronics is a Frankfurt-based company." Frankfurt, a city in Germany, hyphen “based.” When we say that it's a Frankfurt-based or Los Angeles-based or New York-based, we mean that, it's just another way of saying that's where they're headquarters are. That's where their company is, in that city. You can say, "We're based in Los Angeles," using it as a verb. We are based here, means this is where our home is, this is where our headquarters are. Max Electronics is a Frankfurt-based company but has been a pioneer in the manufacturing of home electronics. A “pioneer” is a person who does something, one of the first people to do something, someone who is a leader, who does something that no one else has done before, usually in a particular area. So, for example, Apple Computer and Microsoft Computers are both…those companies are pioneers in the personal computer industry or the personal computer business. They were some of the first companies to do things in this area. ESL Podcast is a pioneer in language teaching podcasts. We are, not the first, but one of the first to have a podcast for teaching English. There are others, of course, and some who came before us, but we won't talk about them.
Well, we are…Max Electronics is a pioneer in the manufacturing of home electronics. “Home electronics” is a general term to describe anything that is electronic in your house, that seems clear: the television, the stereo, the…what else can be home electronics…a big screen TV, a DVD player, a cassette recorder, all of these are home electronics. Things that you would use in your home.
The company has a global network of 1,500 distributors. A “global network” is a term that you may hear in describing a company. The word “network” usually means that there are different people or different companies that are connected somehow, that are, that are connected to each other. So, if you say I have a network of people who sell my product, the things that I make, means you have a group of people and these people are connected to you, somehow. In this case, Max Electronics is a global, and “global” is just another word for in the entire world, a global network of 1,500 distributors. When we talk about a “distributor” in business, we're talking about a company that sells thing for the main company. So, its usually, for example, a store. A store could be…could sell many different things. They could sell the home electronics from Max Electronics. They would be a distributor of that particular company's products or the things that they make. So, distributors are people that sell things to you, sometimes the distributors are people who sell things to other businesses and that's also a use of that term.
Well, Max Electronics has stores in 53 countries worldwide. “Worldwide,” all one word, is the same as global, means in the entire world. Roberta says that this description is a good start. “It's a good start.” That's a polite way, a nice way of saying, "That's good, but its not good enough." So, when someone says to you, "That's a good start," they mean, "Okay, what you've done so far is a good beginning, but its not finished yet. You have to keep working on it." She says, "It's a good start. Why don't you pass these descriptions, these profiles, by me when you're done?" “To pass (something) by (someone)” means to show them that, to give them, for example, the piece of paper or send them an email and have them look at it first before you send it to someone else. So, to pass something by means to have someone else look at it, usually its your boss or someone who is going to help you make it better. Lee says, "Yeah, I'll do that. Thanks a lot."
[start of story]
Roberta: What are you working on?
Lee: Oh, I'm writing the company profiles for the businesses participating in the meeting next month. Do you have a minute to give me some feedback?
Roberta: Sure, what do you have so far?
Lee: I've started to write the ones for Landrun and Max Electronics. This is what I have for Lundrun so far: “A Fortune 500 company, Lundrun is a world leader in car manufacturing. Founded in 1936, Lundrun today is a $90 billion dollar company that sets a standard in the industry.”
Roberta: That's pretty good. Don't forget to mention that their headquarters are in Chicago.
Lee: Oh, yeah, I'll make sure I add that. Okay, here's what I have for Max Electronics: “Max Electronics is a Frankfurt-based company that has been a pioneer in the manufacturing of home electronics for over 75 years. The company has a global network of 1,500 distributors and has stores in 53 countries worldwide.”
Roberta: That's a good start. Why don't you pass them by me when you're done and I can give you some more feedback?
Lee: Yeah, I'll do that. Thanks a lot.
[end of story]
Our script today was written by Dr. Lucy Tse. Thank you, Lucy. Remember to visit our website for more information. Or, if you have questions or suggestions, you can email us at eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time, on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse. Hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
company profiles – information that gives facts about a company, such as what a company does and where it is located
* Before I applied for the job, I looked at the company profile to try and learn more about the company.
Do you have a minute? – “Do you have some time right now?”; usually meaning “Do you have some time to help me?”
* Do you have a minute? Dinner is almost ready and it would be helpful if you got drinks for everyone.
feedback – opinion or advice; someone’s reaction to something, usually given to help make something better
* I drew a plan for my art project, but I got feedback from my teacher before I began building it.
so far – as of now; often used when something is not finished, when you are still working on something
* So far, I have only called half of the parents on this list.
Fortune 500 – the top 500 public corporations in the United States, listed in order according to how much money they make
* A company must be very large and very successful to be in the Fortune 500.
world leader – a company or organization that is one of the most successful in the world in what it does
* His company became a world leader in computers by opening stores and offices in over 50 countries.
to manufacture – to make; to create or produce; usually used when talking about business or factories
* This toy factory manufactures over 100,000 toys everyday.
founded – started; to first be opened for business
* I founded this company with my brother over 25 years ago, and it has grown a lot since then.
to set a standard – to be the best in a field
* The company’s performance this year set a standard for many years to come.
headquarters – the main office of a company or business
* I traveled to the company headquarters in New York so I could meet vice president.
to be based – to be located (somewhere); usually the main office of a business
* Even though I work in San Francisco, our company is London-based, so I often visit the United Kingdom.
pioneer – a person who is the first to achieve something; a leader
* The pioneers of medicine and science changed our lives by making important discoveries.
network – in business, a group of companies that work with each other and help each other
* Our business network includes several companies in Chicago.
distributor – a company that sells products made by another company
* We make great televisions, but we are having a hard time finding enough distributors to sell them.
a good start – a good beginning; usually used to mean a good idea that can still be made even better
* You’ve made a good start on this painting. Keep working on the colors and I’m sure it will turn out beautifully.
why don’t you pass (something) by (someone)… – “why don’t you show me again”; “let me check them again”
* I want to make sure those letters are perfect. Why don’t you pass them by me again before you sent them out?
Comprehension Questions
1. Why does Lee ask Roberta for feedback?
a) He thinks she did a good job at the meeting last month.
b) He wants her opinion on the company profiles he has written.
c) She will get upset if Lee does not ask for her help.
2. Lundrun and Max Electronics are:
a) very large international companies.
b) new businesses Lee and Roberta are starting.
c) both based in Chicago.
Answers at bottom.
What Else Does It Mean?
feedback
The word “feedback,” in this podcast, means advice or opinion: “Can you give me some feedback on this song I wrote?” Feedback also means the high-pitched loud noise that microphones make. When someone is speaking into a microphone and suddenly you can’t hear them because there is a loud noise that hurts your ears coming from the speakers (where the sound comes out), that noise is called feedback: “His speech was going Well, until the feedback from the microphone made him stop in the middle.”
pioneer
In this podcast, the word “pioneer” is used as a noun meaning someone or something that is the first to do something or has made great progress in an area: “The State of California is a pioneer in making it illegal to smoke in public places.” People can be pioneers, too, like the American pioneers who first went to the western part of the United States. Another word for these people is “settlers”: the first to come and settle, or make a community, in a new place. Pioneer can also be a verb, “to pioneer,” meaning to lead the way or make discoveries for the first time.
Culture Note
The New York Stock Exchange in New York City is the center of the U.S. stock market. This stock exchange is also called “Wall Street” since the building is located on this street. Wall Street is famous for having very wealthy businesspeople and a fast pace of life. So what happens there?
Stocks and shares are the main currency of the New York Stock Exchange. “Stock” is the capital, or money, made by a corporation or company. A “share” is a small part of that stock. “Shareholders” own shares of a company’s stock, and therefore, they own a part of the company, either a small part (only a few shares) or a large part (many shares).
The purpose of the stock exchange is to provide a place where buyers and sellers of shares can meet and buy or sell their shares in an auction. An auction is where the something will be sold to the person offering the most money. The New York Stock Exchange is so fast-paced, or moves so quickly, because everyone there is competing with each other to get the best price on shares.
Comprehension Answers
1 - b
2 - a