
= 005. The psychology of inequality and political division | Keith Payne
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

You've probably heard by now  that economic inequality is historically high,  that the wealthiest one-tenth 十分之一 of one percent in the United States  have *as much wealth as* the bottom 90 percent combined,   +
or that `主` the wealthiest eight individuals in the world  `谓` have *as much wealth  as* the poorest 3.5 billion inhabitants 居民 of the planet.


[.my2]
在美国最富有的 1% 人口中，
10% 的人财富总量, 相当于最底层 90% 人群的财富总和. 或, 全球最富有的8 个人的财富总量, 相当于世界上最贫穷的35 亿人的财富总和。

But did you know that economic inequality is associated with shorter lifespans （人或动物的）寿命；使用期,  less happiness,  more crime  and more drug abuse?   +

Those *sound (v.) like* problems of poverty,  but among _wealthy, developed 发达的，高度发展的；先进的，成熟的 nations_   +
`主` those health and social problems   `谓`  are actually *more* tightly #linked (v.) to# _inequality between incomes_ 收入不平等   +
*than* #to# _absolute incomes_ 绝对收入.

[.my2]
这些听起来似乎是贫困所带来的问题，
但在富裕的发达国家，这些健康和社会问题, 实际上与"收入不平等"的关系, 比与"绝对收入"的关系, 更紧密。

And because of that,  the United States,  the wealthiest and the most unequal (a.) of nations,  actually fares (v.)成功（或不成功、更好等） worse *than* all other developed countries.

Surveys (n.)调查 show that large majorities 大部分；大多数 of Americans,  both Democrats 民主党人 and Republicans,  believe inequality is too high and want more equal pay.



And yet as a society, we don't seem to be able to find the _common ground_ （争论双方的）共同基础；一致之处,  the consensus 一致看法，共识, the _political will_ 政治意愿 to do anything about it.

[.my2]
然而，作为一个社会，我们似乎无法找到共同点，共识，政治意愿, 来做些什么。

Because, as inequality has risen in recent decades,  political polarization (n.)极化；偏振；两极分化 has risen along with it.

[.my2]
因为，随着近几十年来不平等的加剧，政治两极分化也随之加剧。

We *see* those _who disagree with us_ *as* idiots 白痴，极蠢的人 or *as* immoral.

Nearly half of Democrats and Republicans  now think (v.) that  `主` the other side is *not just* mistaken (a.)  *but* a threat to the nation.

And that animosity (n.)憎恶，仇恨，敌意 prevents (v.) us from finding the common ground  to change (v.) things.

[.my2]
我们把与我们意见相左的人, 称作“白痴”或“缺德的人”。
将近半数的民主党人和共和党人，
认为对方不只是犯错而已，
而是国家的祸患。
而那种敌意阻碍了人们寻求共同利益，
进而也阻碍了变革。

I'm a _social psychology professor_ at the University of North Carolina,  and I study (v.) the effects of inequality on people's thinking and behavior.

I'm going to argue 论证；说理；争辩 that it's *not just* an unfortunate coincidence 不幸的巧合 that inequality and political division 分歧；不和；差异 have risen together.

There are good _psychological reasons_  that inequality *drives (v.) wedges* 楔子；三角木 in our politics.

That means there are good psychological paths  to improve (v.) both *at once* 立刻，现在，马上;同时，同时进行.

[.my2]
我是北卡罗莱纳大学的一名社会心理学教授，
主要研究贫富差距对人的思想和行为的影响。
我想说的是，贫富差距和政治分歧的同时出现
不仅仅是一个不幸的巧合。
有充分的心理原因表明，
是贫富差距造成了我们政治中的裂痕。
这同时也意味着，良好的心理学方法
可以实现二者的同步改善。

[.my1]
.案例
====
wedge本是“楔子”的意思，drive a wedge into或drive a wedge between...and...字面意思是“在...中打入楔子”，实际使用中常取其比喻义，表示“离间，引起不和”。
====

To understand why inequality is so powerful,  you have to first understand that  +
we are constantly *comparing* ourselves  *to* other people,  and when we do that,  we really like *to come out on top* 获胜，取得优势,  and we find it painful *to be* on the bottom.

[.my2]
我们总是在不断地把自己和别人比较，当我们这样做的时候，我们真的很想出人头地，我们发现处于最底层是很痛苦的

Psychologists call (v.) it the "better-than-average effect."  Most people believe they're better than average  *at* just about anything they *care about*,  which isn't strictly possible, because that's just what average 平均水平，一般标准 means (v.).

(Laughter)

[.my2]
心理学家称之为“优于平均水平的效应”。大多数人认为他们在任何他们关心的事情上, 都比一般人好，但这是不可能的，因为这就是"平均水平"所代表的意思。


But that's the way people feel.

Most people think they're smarter than average,  harder working than average  and more socially skilled.

Most people think they're better drivers than average.

(Laughter)

That's true *even if* you do the study with a sample of people   +
currently hospitalized (v.)住院；入院就医 for a car accident that they caused.

(Laughter)

So we really want *to see* ourselves *as* better than average,  and if we find out 发现，查明 otherwise,  it's a painful experience that we have to cope with.

And we cope with it  +
by shifting how we see the world.

[.my2]
而我们的应对方法，就是换一套方式去看待这个世界。

To understand how this works,  my collaborators 合作者 and I ran an experiment.

We asked participants to complete a decision-making task  +
to earn (v.) some money,  and in reality, everyone earned the same amount of money.

But we randomly divided them into two groups,  and we *told* one group *that* they had done better than average,  and we told the other group they had done worse than average.

So now we have one group that feels (v.) richer and one group that feels (v.) poorer,  but for no objective 客观的，不带个人情感的；客观存在的 reason.

And then we asked them some questions.

When we asked them, "How *good* are you *at* making decisions?"  the better-than-average group said that they were more competent  能干的，能胜任的；合格的 *than* the below-average group.

The better-than-average group said that `主` their success  `系` was a fair outcome 公平的结果 of a meritocracy 精英领导体制；英才管理制度.

[.my1]
.案例
====
.meritocracy
-> merit,才能，-cracy,管理，词源同democracy.引申词义精英领导体制。
====

The below-average group thought (v.) `主` the system `系` was rigged (v.)（以不正当的手段）操纵，控制,  and in this case, of course, they were right.

(Laughter)

Even though the two groups had the same amount of money,  the group that felt richer said `主` we should cut (v.) taxes on the wealthy,  cut (v.) benefits to the poor.

Let them *work hard* and *be responsible for* themselves, they said.

[.my2]
并且表示，应该让穷人努力工作，对自己负责。

These are attitudes  后定  that we normally assume  (v.)假定，假设，认为 `宾从` #are rooted (v.) in# deeply held values  and a lifetime 一生，终生 of experience,   +
but `主` a 10-minute exercise  that made people feel richer or poorer  `系` was enough to change those views.

[.my2]
我们通常认为, 这些态度是根植于根深蒂固的价值观, 和人生的经历，
但一个让人们感受到贫富差距的10 分钟测试，就足以改变这些看法。

[.my1]
.案例
====
上面一句, 完整的其实是这样的: +
These are attitudes that we normally assume `主` #that# `谓` are rooted in deeply held values and a lifetime of experience.
====

This difference between being rich or poor and feeling rich or poor is important,  because the two don't always line up very well.

You often hear people say with nostalgia,  "We were poor, but we didn't know it."  That was the case for me growing up,  until one day,  in the fourth-grade lunch line,  we had a new cashier who didn't know the ropes,  and she asked me for 1.25 dollars.

I was taken aback, because I had never been asked to pay for my lunch before.

I didn't know what to say, because I didn't have any money.

And suddenly, I realized for the first time  that we free lunch kids were the poor ones.

That awkward moment in the school lunch line  changed so much for me,  because for the first time, I felt poor.

We didn't have any less money than the day before,  but for the first time,  I started noticing things differently.

It changed the way I saw the world.

I started noticing how the kids who paid for their lunch  seemed to dress better than the free lunch kids.

I started noticing the big yellow blocks of government cheese  that showed up at our door  and the food stamps my mother would pull out at the grocery store.

I was always a shy kid,  but I hardly talked at all after that at school.

Who was I to speak up?  For decades, social scientists looked for evidence  that feeling deprived compared to other people  would motivate political action.

They thought it would mobilize protests, strikes,  maybe even revolutions.

But again and again what they found was that it paralyzed people,  because the truth is,  feeling less than other people  brings shame.

It makes people turn away,  disgusted with the system.

Feeling better than other people, though --  now that is motivating.

It motivates us to protect that position,  and it has important consequences for our politics.

To see why, consider another experiment.

Again, we asked participants to make decisions to earn some money,  and we told one group that they had done better than average  and the other group that they had done worse than average.

And again, the better-than-average group said it's a fair meritocracy,  cut taxes on the wealthy,  cut benefits on the poor.

But this time, we also asked them what did they think  about other participants who disagree with them  on those issues.

Are they smart or incompetent?  Are they reasonable or are they biased?  The better-than-average group said anybody who disagrees with them  must be incompetent, biased,  blinded by self-interest.

The below-average group  didn't assume that about their opponents.

Now, there are lots of psychology studies  showing that when people agree with us,  we think they're brilliant,  and when people disagree with us,  we tend to think they're idiots.

(Laughter)  But this is new because we found it was driven entirely by the group  that felt better than average,  who felt entitled to dismiss those people who disagree with them.

So think about what this is doing to our politics,  as the haves and have-nots spread further and further apart.

Yes, a lot of us think that people on the other side are idiots,  but the people politically engaged enough to be yelling at each other about politics  are actually mostly the well-off.

In fact, as inequality has grown in recent decades,  political interest and participation among the poor has plummeted.

Again, we see that people who feel left behind  aren't taking to the streets to protest or organize voter registration drives.

Often, they aren't even voting.

Instead, they're turning away and dropping out.

So if we want to do something about extreme inequality,  we have to fix our politics.

And if we want to fix our politics,  we have to do something about inequality.

So what do we do?  The wonderful thing about spirals  is that you can interrupt at any point in the cycle.

I think our best bet starts with those of us  who have benefited the most from inequality's rise,  those of us who have done better than average.

If you've been successful,  it's natural to chalk up your success to your own hard work.

But, like the studies I showed you,  everybody does that,  whether or not it really was the hard work that mattered most.

Every successful person I know  can think of times when they worked hard and struggled to succeed.

They can also think of times  when they benefited from good luck or a helping hand  but that part is harder.

Psychologists Shai Davidai and Tom Gilovich  call it the "headwind-tailwind asymmetry."  When you're struggling against headwinds,  those obstacles are all you can see.

It's what you notice and remember.

But when the wind's at your back and everything's going your way,  all you notice is yourself  and our own amazing talents.

So we have to stop and think for a minute  to recognize those tailwinds helping us along.

It's so easy to see what's wrong with people  who disagree with you.

Some of you decided that I was an idiot in the first two minutes,  because I said inequality was harmful.

(Laughter)  The hard part is to recognize  that if you were in a different position,  you might see things differently,  just like the subjects in our experiments.

So if you're in the above-average group in life --  and if you're watching a TED talk, you most likely are --  (Laughter)  then I leave you with this challenge:  the next time you're tempted to dismiss someone who disagrees with you  as an idiot,  think about the tailwinds that helped you get where you are.

What lucky breaks did you get  that might have turned out differently?  What helping hands are you grateful for?  Recognizing those tailwinds gives us the humility we need  to see that disagreeing with us doesn't make people idiots.

The real hard work is in finding common ground,  because it's the well-off who have the power  and the responsibility to change things.

Thank you.

(Applause)

'''