
= 007 The Eulogy Question | Nikki Huang
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

视频 +
https://www.youtube.com/watch?v=k_97XjY4PPE&ab_channel=TEDxTalks


== 释义

Good afternoon 下午好, everyone 大家. My name is Nikki. I'm 24 years old, and I am a professional 专业的 eulogy 悼词 writer 作家. Just kidding 开玩笑—I'm not. What I actually am is a young person trying to find her way through the world and discover her purpose 目的；目标 in life. I'm someone trying to balance 平衡 my passions 激情；热情 with the obligations 义务；责任 that I have as someone who is not only a member 成员 of society but also deeply entrenched 根深蒂固的 in community 社区. I'm also someone, as I'm sure many of you are, who has gone through 经历 some significant 重大的 personal tragedy 悲剧.

You see, in several distinct 不同的 ways, 2023 to 2024 was not my year. It was a year of compounded 复合的 sudden 突然的 grief 悲伤 and loss 失去, to the point where I was not sure I was ever going to make it out all right. I lost three people I loved in pretty rapid 快速的 succession 连续, all while undergoing 经历 major 重大的 life changes. Each time, I did not get the chance to say goodbye, and I never imagined that the last time I saw each person would be exactly that—the last.

While I had previously experienced death and loss in the past, never before had I experienced the sudden, unexpected 意外的 deaths of multiple people that I loved most in this world. Now, with regards to 关于 eulogies, while I never hoped to actually be a professional eulogy writer, I have written two in my young adult life, and they stand out 突出 to me as experiences that have changed my approach 方法 and my outlook 观点 to living.

The last one that I wrote, in particular, changed me forever. It was for my paternal 父亲的 grandmother, who passed away 去世 on February 8th this year. She was someone that I never wanted to imagine my life without. As a writer, of course, I love to write, but there is an aspect 方面 of writing that is terrifying 可怕的. Ernest Hemingway put it best when he said, "There's nothing to writing. All you do is sit at a typewriter 打字机 and bleed 流血." And this, I found, is especially true for eulogy writing.

While our survival 生存 instincts 本能 in the midst of sudden grief, trauma 创伤, and loss have us desperate 绝望的 to staunch 止住 our emotional wounds 伤口 as well as possible, writing a eulogy for someone you love requires you not only to open the wounds but to tear into 撕开 them as deeply as possible, in the hopes that somehow the right words end up on your page. In many ways, writing and delivering 发表 that eulogy felt like inviting the world not only to examine 检查 my wound but also to see just how much I ripped it open for all of them.

See, going through loss is one thing, but performing 表演 your pain and eventually displaying 展示 your healing 愈合 for public consumption 消费 is another thing altogether. On the outside, I soon appeared as if everything was fine and as if I had everything under control. I'm good at that. But even when I thought my mind was strong enough and I was doing everything I needed to do, I watched my body begin to carry traces 痕迹 of what had happened to me. Eventually, it no longer felt like mine, with the way that it let me down 让我失望 on a daily basis due to the severe 严重的 stress—headaches 头痛, stomach aches 胃痛, dizziness 头晕, hair loss 脱发, constant nausea 持续恶心.

There were days where my only achievable 可实现的 task was to make it through 熬过 the next hour. And many days, I kept asking myself, "How am I going to make it through all of this? Surely, I will never be the same." And that is a harsh 残酷的, simple truth about going through very hard or very painful things: you do not make it out the same. And every time you take a step towards healing, if you've lost someone that you truly love, you wake up the next day to realize that there is yet another hill 山 to climb. In this way, life in the face of severe loss can feel futile 无意义的.

Ironically 讽刺的是, now, I've never felt so sure of myself, even as I find myself carrying more pain and grief than I ever thought I would at this point in my life. And I never thought that death and loss would be the exact things to make me want to commit to 致力于 truly living. Now, having just gone through this journey, I wanted to share with all of you today a single question.

It's a question that I ask myself over and over again, as I thought my world might truly end, only to wake up the next day and realize that life would and should go on. I call this question the "eulogy question," and by no means 绝不 is it a novel 新颖的 idea. In fact, a very common therapeutic 治疗的 exercise is to ask people to write their own eulogies, and the question they are asked goes something like this: "When you die, what do you want people to say about you at your funeral 葬礼?"

However, in thinking about this question, I realized that it lent itself 适用于, in my opinion, to thinking that relied too heavily on outward 外部的 perception 看法 and societal 社会的 approval 认可. It also involved a pretty significant time period to make big changes in life decisions—your whole life, right? In other words, I felt that it gave me a lot of time to procrastinate 拖延.

I eventually realized that if I wanted to live a life that I could be proud of, no matter when it ended, I needed to find a simple yet effective guiding 指导的 principle 原则 with which to approach it. I realized that I needed a tool not only to get by 勉强应付 but to be able to make the best of 充分利用 every moment. And this principle also needed to account for 考虑到 a few important things that I'd learned.

First, life is short. It is fragile 脆弱的, and it can end very, very suddenly. Second, in life, there is pain that demands 要求 to be felt. Pain is a powerful emotion. It tells us what matters and often shows us our moral 道德的 compass 指南针 more than moments of pleasure or elation 兴高采烈 ever will. Third, perhaps one of the greatest hopes we can ever have in our lifetimes is to eventually come to know who we are and what we are meant to be doing. Essentially 本质上, if you know exactly what it is you're living for, you will not worry too much about when your journey ends or the unexpected and unpleasant 不愉快的 things that happen along the way. You will simply have been glad to be on it.

Lastly, and perhaps most importantly, as you go through the journey of healing from loss and big trauma, there soon comes a day when you wake up and realize that no one is coming to save you—no one, that is, except for yourself.

So, armed with 带着 this new knowledge, I made myself a promise: even if my heart had been shattered 破碎 into a million pieces over and over again, I would personally pick up every single piece and stitch 缝合 it all back together, no matter how long it took or how difficult it was. Spoiler alert 剧透: I'm still working on it as we speak.

So, I decided to take the eulogy question that I first mentioned and revise 修改 it so that I could have a simple question to turn to every time I needed clarity 清晰 or direction 方向 in life—and every time I needed to make a decision. This was especially pertinent 相关的, given that I was in the middle of completing my master's degree when all this happened to me.

I've been trained as a sociologist 社会学家 and a researcher 研究人员 for the last five years at this point on my academic 学术的 journey. As I'm sure many of you know, I learned a very important lesson: often, the research question matters way more than the answers. The trajectory 轨迹 of your answers can be single-handedly 单独地 impacted by the way your research question is framed 构建.

The academics 学者 I admire most actually spend way more time than you think revising their research questions. My mentors 导师 told me over and over again that the process of developing a research question is an iterative 迭代的 one. And though they never explained this to me outright 坦率地, I realized that I was also being taught a very important life lesson: the investigative 调查的 process is not only useful for publishing 发表 research in academic journals 期刊 or books. It is, rather, a useful, flexible 灵活的 framework 框架 with which to approach any meaningful 有意义的 question we might have about life.

In fact, knowing how to ask the right question—one that leads us to the best answer—is quintessential 至关重要的 to understanding the essence 本质, purpose, and meaning behind our existence 存在. So, I realized that if I wanted to live a life I could be proud of, no matter when it ended, and learn and grow from whatever obstacles 障碍 came my way, I had to have the right question to ask myself.

I began with a big, overarching 总体的 question: "How do I live a meaningful life, given what I've learned about the fragility 脆弱性 of the human experience?" The problem with that question is that it didn't constrain 约束 me to take any significant action in the present—when the present moment is kind of all we really have.

So, I arrived at the revised research question: "If my life suddenly ended tomorrow, would I be happy with the way that I've lived it? Would I be proud of the person I was in the amount of time I was allowed—without any regrets 遗憾?"

While contemplating 思考 death can be an anxiety-inducing 引发焦虑的 and uncomfortable 不舒服的 process, I do invite all of you to consider it in this light. If there's anything I've learned, it's that the journey back to oneself often requires you to lean into 深入 uncomfortable feelings and dig into 挖掘 their mess 混乱 in order to find deeper understanding and truth.

To be able to ask yourself this question, however, I also invite you to put ego 自我 aside and let humility 谦逊 in. At the end of the day, stripped of 剥去 all our material 物质的 resources, shiny 闪亮的 career wins 胜利, and social media perfection 完美, what is a life well-lived if not one lived on a mission 使命—and with enough humility to accept that we are all simply human at the end of the day?

To conclude 总结, then, I'd like to ask you: "If your life ended tomorrow, would you be proud of the way that you've lived it—even if you did not have the amount of time you expected or planned?"

If your answer right in this very moment is not "yes," I assure you, with full confidence, that in due time 在适当的时候, it may be. The greatest questions in life are, after all, often very simple at the end of the day. Thank you.


[.my2]
====
大家下午好。我叫Nikki，今年24岁，是一名专业的悼词撰写人。开个玩笑，其实我不是。我实际上是一个正在努力寻找自己人生方向、探索人生目标的年轻人。我是一个试图在激情与义务之间找到平衡的人，这些义务不仅来自社会，也来自我深深扎根的社区。我也和你们中的许多人一样，经历过一些重大的个人悲剧。

2023到2024年对我来说并不是一个好年头。这一年充满了突如其来的悲伤和失去，以至于我曾一度怀疑自己是否能够挺过去。我在很短的时间内失去了三位我爱的人，同时自己也经历着人生的重大变化。每一次，我都没有机会告别，也从未想过与每个人的最后一次见面, 竟成了永别。

虽然我以前也经历过死亡和失去，但从未像这次一样，接连失去多个我最爱的人。关于悼词，虽然我从未想过成为一名专业的悼词撰写人，但我在年轻的生命中已经写过两篇，这些经历改变了我的生活态度和人生观。

尤其是最后一篇悼词，它彻底改变了我。那是我为我的祖母写的，她于今年2月8日去世。她是我从未想过会失去的人。作为一个热爱写作的人，我当然喜欢写作，但写作中也有一种令人恐惧的方面。**海明威说得最好：“写作没什么难的，你只需要坐在打字机前流血。”**我发现，这在撰写悼词时尤为真实。

在突如其来的悲伤、创伤和失去中，我们的生存本能让我们急于止血，但**为你所爱的人写悼词却要求你不仅要打开伤口(重新回忆逝去的爱人的一切)，还要尽可能地撕开它，希望最终能在纸上找到合适的词句。**在很多方面，撰写和发表那篇悼词的感觉, 就像是邀请世界不仅审视我的伤口，还让他们看到我为了他们而撕开伤口的过程。

**经历失去是一回事，但将你的"痛苦"和"愈合过程"公之于众则是另一回事。**表面上，我很快就表现得好像一切都没问题，好像我掌控了一切。我擅长这样做。但即使我认为自己的头脑足够坚强，做了所有该做的事情，我还是看到自己的身体开始承受这些事件的痕迹。最终，我的身体不再属于我，它因极度的压力而每天让我失望——头痛、胃痛、头晕、脱发、持续恶心。

有些日子里，我唯一能完成的任务就是熬过下一个小时。许多天里，**我不断问自己：“我该如何熬过这一切？我肯定再也不会是原来的我了。”**这是关于经历非常艰难或痛苦的事情的**一个残酷而简单的真相：你不会以同样的自己走出来。**每当你向愈合迈出一步时，如果你失去了你真正爱的人，第二天醒来你会发现还有另一座山要爬。

在这种方式下，面对严重失去的生活可能显得毫无意义。讽刺的是，现在我从未如此确信自己，即使我发现自己背负着比我想象中更多的痛苦和悲伤。我从未想过，死亡和失去会成为让我真正想要投身于生活的动力。

现在，刚刚经历了这段旅程，我想与大家分享一个问题。这是一个我反复问自己的问题，当我以为我的世界可能会真正结束时，第二天醒来却发现生活依然会继续。我称之为“悼词问题”，这绝不是一个新概念。事实上，*一个非常常见的治疗练习, 是让人们写下自己的悼词，而他们被问到的问题大致是这样的：“当你去世时，你希望人们在你的葬礼上如何评价你？”*

然而，**在思考这个问题时，我意识到它让我过分依赖于外界的看法和社会的认可，**并且它涉及一个相当长的时间段来做出重大的人生决策——你的一生，对吧？换句话说，我觉得它给了我很多拖延的时间。

最终，**我意识到，如果我想过上一种无论生命何时结束都能让我感到自豪的生活，我需要找到一个简单而有效的指导原则来应对它。我意识到，我不仅需要一个工具来生存，还需要一个工具来充分利用每一刻。**这个原则还需要考虑到我学到的一些重要事情。

*首先，#生命是短暂的。它是脆弱的，可能会非常突然地结束。# +
第二，生活中有些痛苦必须被感受到。#痛苦是一种强大的情感。它告诉我们什么才是重要的，并且往往比快乐或兴奋的时刻, 更能成为我们的指南针。# +
第三，也许我们一生中最大的希望之一就是##最终了解我们是谁，以及我们注定要做什么。##本质上，#如果你确切地知道你为了什么而活，你就不会太担心你的旅程何时结束，或者途中发生的意外和不愉快的事情。你只会庆幸自己曾经踏上过这段旅程。#*

*最后，也许##最重要的是，当你经历失去和重大创伤的愈合之旅时，总有一天你会醒来，意识到没有人会来拯救你——除了你自己。##*

因此，带着这些新知识，我对自己做出了一个承诺：**即使我的心被撕成百万片，我也会亲自捡起每一片，重新缝合它们，无论需要多长时间，或者有多么困难。**剧透一下：我仍在努力中。

于是，我决定修改最初提到的“悼词问题”，以便在我需要清晰或方向时，可以有一个简单的问题来指引自己——每当我需要做出决定时。这尤其重要，因为当这一切发生时，我正在攻读硕士学位。

在过去的五年里，我作为一名社会学家和研究人员接受了训练。正如你们中的许多人可能知道的那样，*##我学到了一个非常重要的教训：通常，研究问题比答案更重要。##你的答案轨迹可能完全取决于你的研究问题的框架。*

**我最钦佩的学者们, 实际上花费了比你想像中更多的时间, 来修改他们的研究问题。**我的导师们反复告诉我，**研究问题的过程, 是一个迭代的过程。**虽然他们从未明确地向我解释这一点，但我意识到, 我也在学习一个非常重要的人生课程：调查过程不仅对在学术期刊或书籍上发表研究有用，它更是一个有用、灵活的框架，可以用来应对我们可能对生活提出的任何有意义的问题。

事实上，知道如何提出一个能引导我们找到最佳答案的正确问题，对于理解我们存在的本质、目的和意义至关重要。因此，*我意识到，如果我想过上一种无论生命何时结束都能让我感到自豪的生活，并从任何障碍中学习和成长，我必须有一个正确的问题来问自己。*

我开始提出一个大的、总体的问题：“鉴于我对人类经验脆弱性的了解，我如何过上有意义的生活？”这个问题的问题是，它没有约束我在当下采取任何重大行动——而当下时刻几乎是我们真正拥有的一切。

于是，我得出了修改后的研究问题：“*如果我的生命突然在明天结束，我会对自己度过的方式感到满意吗？我会为自己在有限的时间内成为的那个人感到自豪吗——没有任何遗憾？*”

虽然思考死亡可能是一个引发焦虑和不适的过程，但我邀请你们以这种方式考虑它。如果我学到了什么，那就是回归自我的旅程, 往往需要你深入不适感，并在混乱中挖掘，以找到更深层次的理解和真理。

然而，为了能够问自己这个问题，我还邀请你们放下自我，让谦逊进入。在一天结束时，*剥去我们所有的物质资源、闪亮的职业胜利, 和社交媒体上的完美，什么是一个良好度过的人生*，如果不是一个以使命为驱动，并带着足够的谦逊接受我们终究只是人类的人生？

最后，我想问你：“如果你的生命在明天结束，你会对自己度过的方式感到自豪吗——即使你没有得到你预期或计划的时间？”

如果此刻你的答案不是“是”，我向你保证，随着时间的推移，它可能会是。毕竟，生活中最伟大的问题往往在一天结束时非常简单。谢谢。
====


'''


== pure

Good afternoon, everyone. My name is Nikki. I'm 24 years old, and I am a professional eulogy writer. Just kidding—I'm not. What I actually am is a young person trying to find her way through the world and discover her purpose in life. I'm someone trying to balance my passions with the obligations that I have as someone who is not only a member of society but also deeply entrenched in community. I'm also someone, as I'm sure many of you are, who has gone through some significant personal tragedy.

You see, in several distinct ways, 2023 to 2024 was not my year. It was a year of compounded sudden grief and loss, to the point where I was not sure I was ever going to make it out all right. I lost three people I loved in pretty rapid succession, all while undergoing major life changes. Each time, I did not get the chance to say goodbye, and I never imagined that the last time I saw each person would be exactly that—the last.

While I had previously experienced death and loss in the past, never before had I experienced the sudden, unexpected deaths of multiple people that I loved most in this world. Now, with regards to eulogies, while I never hoped to actually be a professional eulogy writer, I have written two in my young adult life, and they stand out to me as experiences that have changed my approach and my outlook to living.

The last one that I wrote, in particular, changed me forever. It was for my paternal grandmother, who passed away on February 8th this year. She was someone that I never wanted to imagine my life without. As a writer, of course, I love to write, but there is an aspect of writing that is terrifying. Ernest Hemingway put it best when he said, "There's nothing to writing. All you do is sit at a typewriter and bleed." And this, I found, is especially true for eulogy writing.

While our survival instincts in the midst of sudden grief, trauma, and loss have us desperate to staunch our emotional wounds as well as possible, writing a eulogy for someone you love requires you not only to open the wounds but to tear into them as deeply as possible, in the hopes that somehow the right words end up on your page. In many ways, writing and delivering that eulogy felt like inviting the world not only to examine my wound but also to see just how much I ripped it open for all of them.

See, going through loss is one thing, but performing your pain and eventually displaying your healing for public consumption is another thing altogether. On the outside, I soon appeared as if everything was fine and as if I had everything under control. I'm good at that. But even when I thought my mind was strong enough and I was doing everything I needed to do, I watched my body begin to carry traces of what had happened to me. Eventually, it no longer felt like mine, with the way that it let me down on a daily basis due to the severe stress—headaches, stomach aches, dizziness, hair loss, constant nausea.

There were days where my only achievable task was to make it through the next hour. And many days, I kept asking myself, "How am I going to make it through all of this? Surely, I will never be the same." And that is a harsh, simple truth about going through very hard or very painful things: you do not make it out the same. And every time you take a step towards healing, if you've lost someone that you truly love, you wake up the next day to realize that there is yet another hill to climb. In this way, life in the face of severe loss can feel futile.

Ironically, now, I've never felt so sure of myself, even as I find myself carrying more pain and grief than I ever thought I would at this point in my life. And I never thought that death and loss would be the exact things to make me want to commit to truly living. Now, having just gone through this journey, I wanted to share with all of you today a single question.

It's a question that I ask myself over and over again, as I thought my world might truly end, only to wake up the next day and realize that life would and should go on. I call this question the "eulogy question," and by no means is it a novel idea. In fact, a very common therapeutic exercise is to ask people to write their own eulogies, and the question they are asked goes something like this: "When you die, what do you want people to say about you at your funeral?"

However, in thinking about this question, I realized that it lent itself, in my opinion, to thinking that relied too heavily on outward perception and societal approval. It also involved a pretty significant time period to make big changes in life decisions—your whole life, right? In other words, I felt that it gave me a lot of time to procrastinate.

I eventually realized that if I wanted to live a life that I could be proud of, no matter when it ended, I needed to find a simple yet effective guiding principle with which to approach it. I realized that I needed a tool not only to get by but to be able to make the best of every moment. And this principle also needed to account for a few important things that I'd learned.

First, life is short. It is fragile, and it can end very, very suddenly. Second, in life, there is pain that demands to be felt. Pain is a powerful emotion. It tells us what matters and often shows us our moral compass more than moments of pleasure or elation ever will. Third, perhaps one of the greatest hopes we can ever have in our lifetimes is to eventually come to know who we are and what we are meant to be doing. Essentially, if you know exactly what it is you're living for, you will not worry too much about when your journey ends or the unexpected and unpleasant things that happen along the way. You will simply have been glad to be on it.

Lastly, and perhaps most importantly, as you go through the journey of healing from loss and big trauma, there soon comes a day when you wake up and realize that no one is coming to save you—no one, that is, except for yourself.

So, armed with this new knowledge, I made myself a promise: even if my heart had been shattered into a million pieces over and over again, I would personally pick up every single piece and stitch it all back together, no matter how long it took or how difficult it was. Spoiler alert: I'm still working on it as we speak.

So, I decided to take the eulogy question that I first mentioned and revise it so that I could have a simple question to turn to every time I needed clarity or direction in life—and every time I needed to make a decision. This was especially pertinent, given that I was in the middle of completing my master's degree when all this happened to me.

I've been trained as a sociologist and a researcher for the last five years at this point on my academic journey. As I'm sure many of you know, I learned a very important lesson: often, the research question matters way more than the answers. The trajectory of your answers can be single-handedly impacted by the way your research question is framed.

The academics I admire most actually spend way more time than you think revising their research questions. My mentors told me over and over again that the process of developing a research question is an iterative one. And though they never explained this to me outright, I realized that I was also being taught a very important life lesson: the investigative process is not only useful for publishing research in academic journals or books. It is, rather, a useful, flexible framework with which to approach any meaningful question we might have about life.

In fact, knowing how to ask the right question—one that leads us to the best answer—is quintessential to understanding the essence, purpose, and meaning behind our existence. So, I realized that if I wanted to live a life I could be proud of, no matter when it ended, and learn and grow from whatever obstacles came my way, I had to have the right question to ask myself.

I began with a big, overarching question: "How do I live a meaningful life, given what I've learned about the fragility of the human experience?" The problem with that question is that it didn't constrain me to take any significant action in the present—when the present moment is kind of all we really have.

So, I arrived at the revised research question: "If my life suddenly ended tomorrow, would I be happy with the way that I've lived it? Would I be proud of the person I was in the amount of time I was allowed—without any regrets?"

While contemplating death can be an anxiety-inducing and uncomfortable process, I do invite all of you to consider it in this light. If there's anything I've learned, it's that the journey back to oneself often requires you to lean into uncomfortable feelings and dig into their mess in order to find deeper understanding and truth.

To be able to ask yourself this question, however, I also invite you to put ego aside and let humility in. At the end of the day, stripped of all our material resources, shiny career wins, and social media perfection, what is a life well-lived if not one lived on a mission—and with enough humility to accept that we are all simply human at the end of the day?

To conclude, then, I'd like to ask you: "If your life ended tomorrow, would you be proud of the way that you've lived it—even if you did not have the amount of time you expected or planned?"

If your answer right in this very moment is not "yes," I assure you, with full confidence, that in due time, it may be. The greatest questions in life are, after all, often very simple at the end of the day. Thank you.

'''