
= 2025.02.28
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 解释

What's up, superstar 你好，超级明星！ It is Friday, the last day of February. Starting this _show off_ 卖弄; 炫耀 with a shout-out (n.)公开表达致意,致敬 to Mr. Mueller and my friends at North Dorchester Middle School in Hurlock, Maryland, for this awesome t-shirt. Rise up 加油！

[.my2]
节目开始前，先向马里兰州赫尔洛克的北多切斯特中学的穆勒先生和我的朋友们致敬，感谢这件超棒的T恤。加油！

I'm Coy Wire, welcome to CNN 10, your 10 minutes of news  where I simply tell you the "what," letting you decide what to think. We've got lots of news to get to today, not a lot of time to do it 时间不多了, so let's get to it 让我们开始吧.

We start in North Korea, where we previously mentioned that the reclusive (a.)隐居的；隐遁的  state 隐士国家 *is letting in* tourists for the first time in 5 years.

[.my2]
这个隐士国家五年来首次允许游客入境。

North Korea says the city of Rason 城市名, a remote economic zone 偏远经济区 in the north of the country, is the first post-pandemic 疫情后的 tourist destination 旅游目的地 *open to* Western tourists 西方游客. The country's capital, Pyongyang, though, is still closed to foreign visitors 外国游客. North Korea is a highly centralized (a.)高度集权的 one-party totalitarian  (a.)极权主义的 dictatorship (n.)专政；独裁权；独裁者职位 where three generations of one family, the Kim family, have ruled with absolute power 绝对权力, and some tourists are now _once again_ getting a firsthand (a.)一手的,亲身的;直接的；直接采购的；直接得来的, albeit 虽然，尽管 highly controlled 高度控制的, look at the hermit nation 隐士国家.

[.my2]
朝鲜表示，北部偏远经济区罗津市是疫情后首个对西方游客开放的旅游目的地。但首都平壤仍对外国游客关闭。朝鲜是一个高度集权的一党专政极权国家，金氏家族三代人以绝对权力统治，一些游客现在再次亲身感受这个高度控制的隐士国家。

At first glance 乍一看, this could be any _elementary (a.)简单的，基本的；基础的，初级的；小学的 school_ recital 朗诵，吟诵；独奏会；背诵；独唱会, until you notice the backdrop （舞台的）背景幕布；周围景物；（事件的）背景. It's not until 直到……才 moments where you see a group of seven-year-old children doing _synchronized (a.)同步的；同步化的 dancing_ 同步舞蹈 in front of a giant (a.)巨大的，伟大的, you know, LED screen 后定 showing missiles 导弹, you know, *blowing up* boats 炸毁船只, you know, and it's like, "Oh yeah, I'm in um, I'm in North Korea."

British travel influencer (n.有影响力者；有影响力的人) 旅行网红 Mike O'Kennedy, one of the first Western tourists to visit North Korea since before the pandemic, says _state-controlled 国家控制的 Western tourism_ is making a limited (a.) return 有限回归 to Rason, an isolated region 孤立地区 near China and Russia.

[.my2]
乍一看，这可能是任何小学的演出，直到你注意到背景。看到一群七岁孩子在巨大的LED屏幕前跳同步舞蹈，屏幕上显示导弹炸毁船只，你会意识到：“哦，我在朝鲜。”英国旅行网红Mike O'Kennedy是疫情后首批访问朝鲜的西方游客之一，他表示国家控制的西方旅游, 正在有限回归罗津这个靠近中俄的孤立地区。

And yet, despite 5 years of near total isolation 几乎完全隔离, North Koreans aren't entirely in the dark 完全不知情. So, they're aware that Donald Trump is now the president once again, and they are aware of the fact that talks (n.) broke down 谈判破裂, uh, last time, uh, during the first Trump presidency 总统（主席，校长）的职位（任期）. So, when I asked the question, "Would you like uh Kim Jong-un and Donald Trump to meet again?" the response I got was, "If Kim Jong-un wants to do it, then of course we support it."

He says `主` traveling to the secret state 秘密国家 `系` is not for everyone. `主` Sightseeing 观光 `谓` feels more like a school field trip 学校郊游. Itineraries 行程;旅游活动日程 are tightly controlled 严格控制. Unauthorized photos 未经授权的照片 are forbidden, but any glimpse 一瞥 of the _hermetically (ad.)密封地，不透气地；炼金术地 sealed_ (a.) nation 与世隔绝的国家 is _social media_ gold 社交媒体上的宝藏.

[.my2]
尽管经历了近五年的几乎完全隔离，朝鲜人并非完全不知情。他们知道特朗普再次成为总统，也知道上次谈判在特朗普第一任期内破裂。当我问“你希望金正恩和特朗普再次会面吗？”时，得到的回答是：“如果金正恩愿意，我们当然支持。”他表示，前往这个秘密国家并不适合所有人。观光更像学校郊游，行程严格控制，未经授权的照片被禁止，但对这个与世隔绝的国家的任何一瞥, 都是社交媒体上的宝藏。

[.my1]
.案例
====
- itinerary -> -it-行,走→itiner旅行 + -ary名词词尾
- hermetic -> 希腊神话中的赫尔墨斯（Hermes）。托特（或赫尔墨斯）的学问被分为三大分 支：炼金术、占星术和巫术.
====

"I am in North Korea," which may explain why so many social media influencers 社交媒体网红 are snatching up seats 抢座位. Ever since the death of _American college student_ Otto Warmbier in 2017, the US _State Department_ 美国国务院 has banned American tourists 禁止美国游客 from visiting North Korea, but that's not stopping some from trying.

"I do have a US passport, and I also have a German passport, so that was my ticket in," American _Wendy Arbide_ calls herself an extreme traveler 极限旅行者. North Korea is her 195th country. So, how does North Korea *stack up* 表现如何; 符合 (标准); 达到 (期望)？ "It was definitely one of the more unusual places to go. You know, I have to be honest, I was surprised how good the food was. They were very lavish 丰盛的 in the food that they gave us. There was a flaming (a.)燃烧的；火红的；激昂的 snail 火焰蜗牛 that was brought to me, and I was like, 'I don't know what to do with this, but it's cool.'"

[.my2]
“我在朝鲜”这句话可能解释了为什么这么多社交媒体网红抢着去朝鲜。自2017年美国大学生Otto Warmbier去世后，美国国务院禁止美国游客访问朝鲜，但这并未阻止一些人尝试。“我有美国护照，也有德国护照，所以这是我的入场券。”美国人Wendy Arbide自称极限旅行者，朝鲜是她到访的第195个国家。朝鲜表现如何？“这绝对是一个不寻常的地方。说实话，我对食物的美味感到惊讶。他们提供的食物非常丰盛。有人给我端来了一只火焰蜗牛，我当时想：‘我不知道该怎么处理，但这很酷。’”

'''

== pure

What's up, superstar! It is Friday, the last day of February. Starting this show off with a shout-out to Mr. Mueller and my friends at North Dorchester Middle School in Hurlock, Maryland, for this awesome t-shirt. Rise up! I'm Coy Wire, welcome to CNN 10, your 10 minutes of news where I simply tell you the "what," letting you decide what to think. We've got lots of news to get to today, not a lot of time to do it, so let's get to it.

We start in North Korea, where we previously mentioned that the reclusive state is letting in tourists for the first time in 5 years. North Korea says the city of Rason, a remote economic zone in the north of the country, is the first post-pandemic tourist destination open to Western tourists. The country's capital, Pyongyang, though, is still closed to foreign visitors. North Korea is a highly centralized one-party totalitarian dictatorship where three generations of one family, the Kim family, have ruled with absolute power, and some tourists are now once again getting a firsthand, albeit highly controlled, look at the hermit nation.

At first glance, this could be any elementary school recital, until you notice the backdrop. It's not until moments where you see a group of seven-year-old children doing synchronized dancing in front of a giant, you know, LED screen showing missiles, you know, blowing up boats, you know, and it's like, "Oh yeah, I'm in um, I'm in North Korea." British travel influencer Mike O'Kennedy, one of the first Western tourists to visit North Korea since before the pandemic, says state-controlled Western tourism is making a limited return to Rason, an isolated region near China and Russia.

And yet, despite 5 years of near total isolation, North Koreans aren't entirely in the dark. So, they're aware that Donald Trump is now the president once again, and they are aware of the fact that talks broke down, uh, last time, uh, during the first Trump presidency. So, when I asked the question, "Would you like uh Kim Jong-un and Donald Trump to meet again?" the response I got was, "If Kim Jong-un wants to do it, then of course we support it." He says traveling to the secret state is not for everyone. Sightseeing feels more like a school field trip. Itineraries are tightly controlled. Unauthorized photos are forbidden, but any glimpse of the hermetically sealed nation is social media gold.

"I am in North Korea," which may explain why so many social media influencers are snatching up seats. Ever since the death of American college student Otto Warmbier in 2017, the US State Department has banned American tourists from visiting North Korea, but that's not stopping some from trying. "I do have a US passport, and I also have a German passport, so that was my ticket in," American Wendy Arbide calls herself an extreme traveler. North Korea is her 195th country. So, how does North Korea stack up? "It was definitely one of the more unusual places to go. You know, I have to be honest, I was surprised how good the food was. They were very lavish in the food that they gave us. There was a flaming snail that was brought to me, and I was like, 'I don't know what to do with this, but it's cool.'"



'''