
= myEng说话句式套路
:toc: left
:toclevels: 3
:sectnums:

'''

==  表推测 (即表示“逻辑上的可能性”) :  can，may，must，shall, will

几乎每个情态动词(can，may，must，shall, will) 都有”推测”用法，这是情态动词的共性。

情态动词＋完成式 (如 may have done)／进行式 (如 should be doing)／完成进行式 (如must have been doing) : *都是具有”推测”意义，而没有各自的基本意义。* +
换句话说，*如果是用于”基本意义”的情态动词，其后面一般只接动词的"一般式"，而不接”完成式”、”进行式”或”完成进行式”。*

就出现的频率来说，最常用的是:

- 情态动词与"一般式"的搭配，
- 其次是与 have done 的搭配；
- 与 be doing 的搭配较少，
- 而与 have been doing 的搭配最少用到。

===  #对现在 + 推测#

==== ▶ *will 和 should*

will 和 should 可以用来表示对"现在"的推测，其肯定程度等同于must。 +
但是, *will表示对"现在"的推测很少用，主要是表示对"将来"的“预测”。*

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|will
|- Ring his home number. He'**ll** be at home now.  ← 这里用will，表示“我肯定他在家”，相当于He must be at home now.
- A: Someone is knocking at the door.
B: That'**ll** be the postman. 准是邮递员。

- It's no use asking Tom; he **won't** know. 相当于说“我肯定他不知道。”
- It **won't** rain. 天将不会下雨。
- He **won't** help us. 他不愿意帮我们。


|should
|- A: This should be State Street up here. 这应该就是国家大街了。 +
B: It's not. I think you should have turned left at the last intersection. 不是。你应该在上一个十字路口左转。

- It *shouldn't* last long. 应该不会太久的。
|===




==== ▶  *情态动词 + 一般式* ->   如: must be / do

注意: 不同的情态动词, 所表达的”可能性的程度”是不一样的。粗略是 

- A: Why isn't John in class? +
B: He **is** sick.（100％肯定，对客观事实的陈述） +
He **must** be sick.（90％肯定，很有把握的陈述） +
He **may** be sick.（50％肯定，不太有把握的陈述） +
He **could/might** be sick.（25％肯定，很没有把握的陈述，只是提供一种可能）


- A: I am thinking of something made of metal that you can find in my pocket. 我在想的东西是金属做的，你们可以在我的口袋里找到。
B: It **could** be a pen. 可能是笔。 +
C: It **could** be some keys. 可能是钥匙。 +
D: It **might** be a paper clip. 可能是曲别针。 +
E: It **may** be a small pocket-knife. 可能是小刀。 +
F: It **could** be a coin. 可能是硬币。 ← 因为是漫无目的地瞎猜，所以在这样的场合中用must这个极为确信的词就不合适了。


[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|must be
|- John isn't in class. *He must be sick*.  ← “一定是”，“准是”. 表明说话人对事情有”很有把握和信心”的推断（deduction）。
- You've been traveling all day. You **must** be tired. 你跑了一天了，一定累了。
- He must **be** dead.  +
← **在表示“推测”时，must后面的谓语动词可以是动作，也可以是状态。而如果 must 表示的是其本意“必须”时，则该must后面的谓语动词一般是表示动作（action）的.** 具体来说，就是现在的动作或将来的动作（present and future actions），**不会是表示状态。**本例, 因为这句话的谓语动词be是表示状态，所以这句话不会译成“他必须死掉”，而只能译成“他一定是死了”，即表示推测。 +
即: must + 状态/动作 ← 表”推断” +
must + 动作 ← 表”必须”

|must do
|- Carol **must** get very bored in her job. She does the same thing every day. 凯萝尔一定烦透了她的工作
- Look at that house! Those people **must** have a lot of money. 那些人一定很有钱。

|may do
|- He **may/might/could** be in the library. 他或许在图书馆。
- If a person is smiling or laughing, he **may** be telling a joke. If a person is yawning, then he **may** be tired of the conversation. 若有人在微笑或大笑，这说明他**可能**是在开玩笑；而如果有人在打哈欠，则**可能**说明他对这个交谈感到乏味。

|could  do
|

|might do
|- While this **might** explain some cases, it is not universally applicable. 这种观点或许可以解释某些情况，但它并非放之四海而皆准。
- He **might be** sick. I don't really know. He **could be** at home watching TV. He **might be** at the library. He **could be** out of town. 他有可能病了，但我真的不肯定，他也有可能是在家看电视，也有可能是在图书馆，还有可能不在城里。
- A: Do you think the plane will be on time? 你认为飞机会准时吗？
B: I don't know. It **may/might/could** be delayed by fog. 我不知道，可能会因为大雾而晚点吧。← 这里说话人B已经说明自己不知道了，所以他不会用must这样肯定的语气来推测。

|===


==== ▶  *情态动词 ＋进行式* -> 如 :  must be doing

*情态动词+ be doing 或 Have/has+been+doing 连用时，表达的意思与相应的"进行时态"或"完成进行时态"的意思差不多，只是增加了情态的意义——"推测"含义。*

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

| must be doing
|- The computer is on, so someone *must be using it*. 电脑开着，肯定是有人在用。
- He *must be using* the Internet now. 很确信他在上网 +
He *may be using* the Internet now. 不是很确信 +
He *is using* the Internet now. ← 如果知道他确实就在上网，就可以不用情态动词了

- He **must be using** the Internet now. 很确信他在上网 +
He **may be using** the Internet now. 不是很确信 +
He **is using** the Internet now. ← 如果知道他确实就在上网，就可以不用情态动词了

|should be doing
|- He **should** still **be working** right now. 他现在**应该还在**工作。

|could be doing
|- **Could** he **be waiting** for us at the station? 他**会不会**正在车站等我们呢？
- God, I don't believe this. She **could be giving** birth in the cab. 真不敢相信。她现在或许正在出租车上生产了。 +
← 这里罗斯**用了最不肯定的词could，表明他不希望他的前妻在出租车上生孩子这件事真的发生. 如果他希望这件事发生，他就会用should了。**

| can't be doing
|- They **can't be having** dinner right now. 他们现在不可能还在吃晚饭。
- You **can't/couldn't have been swimming** all day. 你不可能一整天都一直在游泳。
|===


==== ▶  *情态动词 + be able to / be allowed to / have（got）to / be supposed to/ought to  / be going to*

上面这些短语用在情态动词后面, 此时的情态动词, 往往也是只有”推测”的意义，而没有基本意义。


[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|情态动词 + be able to
|- We're supposed to do our best and we **should be able to** finish this work before the boss has to start screaming at us again. 我们得竭尽全力，在老板再次冲我们大喊大叫之前完成这项工作。

|情态动词 + be allowed to
|- He **may be able to** help. 他**或许**能够帮忙。
- If you could just concentrate on getting finished, we **might be allowed to** leave early this afternoon. 如果你们集中精力做完这项工作，**可能就会**允许我们今天下午早点走。

|情态动词 + have（got）to
| ← 在口语中，have got to 作为 have to 的口语形式更为常用

- They'**ve got to** try harder next time. 他们下次得更努力些。这里的have got to表示“必须”。 ← 注意: have to 有各种时态的变化，而 **have got to 没有时态的变化（只能表示”现在”或”将来”**，这一点同must表示“必须”意义时相同），比如不说had got to等。
- You'**ve got to** be joking! 你准是在开玩笑！这里的have got to表示“推测”。


- You **might have to** work late. The others **may be allowed to** leave early. 你**可能**得加班，其他人或许可以早走。
- Look at that house! Those people **have to** have a lot of money. ← 那些人一定很有钱。 这里的 have to 表示推测。
- He is really big; he **has to** be over seven feet tall. 他是个大块头，一定得有超过7英尺高。

|情态动词 + be supposed to
|

|情态动词 +  ought to
|

|情态动词 +  be going to
|
|===

'''

== #对过去 + 推测#

==== ▶  *情态动词 + 完成式*  -> 如 : may have done

- I think I *may have annoyed* Mary. 我想我**可能**是惹玛丽生气了。


==== ▶  *情态动词 + 完成进行式* -> 如 : must have been doing

- You look very tired. You **must have been working** all day. 你看起来很累，你**准是**忙了一整天了。
- Oh, I **must have been sitting** in the same position too long. My legs have fallen asleep. 我一定是同样一个姿势坐得太久了，我的两条腿都麻了。← 这里must的后面接”完成进行”时表示推测

=== ▶  had to

- He was really big; he **had to** be over seven feet tall. 他是个大块头，一定得有超过7英尺高。








