
= 两强如何避免战争
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 两强如何避免战争


How two traditionally friendly peoples ended up in a downward spiral of mutual hostility that led to World War I.  +
Germany’s rapid economic rise shifted the balance of power and enabled Berlin to expand its strategic reach. Some of this expansion— especially at sea—took place in areas in which Britain had profound and established strategic interests. The two powers increasingly viewed each other as ideological opposites, wildly exaggerating their differences.

两民族(英国, 德国)如何最终陷入相互敌对的螺旋式下降，从而导致第一次世界大战。德国经济的快速崛起, 改变了力量平衡，使柏林能够扩大其战略影响力。其中一些扩张——尤其是在海上——发生在英国拥有深远且既定战略利益的地区。两个大国, 日益将对方视为意识形态上的对立面，并疯狂地夸大彼此之间的差异。

As late as 1995, China’s GDP was around ten percent of U.S. GDP. By 2021, it had grown to around 75 percent of U.S. GDP.

直到1995年，中国的GDP仅相当于美国GDP的10%左右。到 2021 年，它已增长到美国 GDP 的 75% 左右。


Such generosity or perspicacity is also sorely missing in relations between China and the United States today.  Similar to the situation a century ago, profound structural factors fuel the antagonism. Economic competition, geopolitical fears, and deep mistrust work to make conflict more likely.

如今的中美关系中, 也非常缺乏这种慷慨或洞察力。与一个世纪前的情况类似，深刻的结构性因素助长了对抗。经济竞争、地缘政治恐惧, 和深度不信任, 加剧了冲突的可能性。

'''

==== 认为对方铁定是要压制自己, 就会造成冤冤相报, 进而双方关系螺旋下降

According to many Germans (and some non-Germans, too), Germany was now the strongest power on the continent and that it should be left free to rationally reorder the region according to the reality of its might.  German leaders began viewing British interference as the root cause of their country’s problems, both at home and abroad. On their side, British leaders imagined that Germany was largely responsible for the relative decline of the British Empire, even though many other powers were rising at Britain’s expense.


许多德国人（以及一些非德国人）认为，德国应该可以根据其实力的现实，自由地合理地重新安排该地区的秩序。德国领导人开始将英国的干涉, 视为德国国内外问题的根源。而英国领导人也认为，德国对大英帝国的相对衰落, 负有主要责任，尽管许多其他强国都在"以英国为代价"而崛起。

Some argue that China would have dramatically expanded its military capabilities no matter what the United States did two decades ago. After all, that is what major rising powers do as their economic clout increases. But the specific timing of Beijing’s expansion was clearly linked to its fear that the global hegemon had both the will and the capacity to contain China’s rise if it so chose. Just as Germany began fearing that it would be hemmed in both economically and strategically in the 1890s and the early 1900s— exactly when Germany’s economy was growing at its fastest clip— China began fearing it would be contained by the United States just as its own economy was soaring.


一些人认为，无论美国二十年前做什么，中国都会大幅增强其军事能力。毕竟，这就是崛起的大国在经济影响力增强时, 主要所做的事情。但北京扩张的具体时机, 显然与其担心"全球霸主(即美国)有意愿也有能力遏制中国的崛起"（如果它愿意的话）有关。正如德国在 1890 年代, 和 1900 年代初开始担心, 自己会在经济和战略上受到围堵一样——正是在德国经济增长最快的时期——中国开始担心, 在中国经济飞速发展的时候，自己会被美国遏制。


In the British-German relationship, three main conditions led from rising antagonism to war.  +

The first was that the Germans became increasingly convinced that Britain would not allow Germany to rise under any circumstances. At the same time, German leaders seemed incapable of defining to the British or anyone else how, in concrete terms, their country’s rise would or would not remake the world.

The second was that both sides feared a weakening of their future positions. This view, ironically, encouraged some leaders to believe that they should fight a war sooner rather than later.

The third was an almost total lack of strategic communication.

In 1905, Alfred von Schlieffen, chief of the German general staff, proposed a battle plan that would secure a swift victory on the continent. Crucially, the plan involved the invasion of Belgium, an act that gave Britain an immediate cause to join the war against Germany.

As Kennedy put it, “The antagonism between the two countries had emerged well before the Schlieffen Plan was made the only German military strategy; but it took the sublime genius of the Prussian General Staff to provide the occasion for turning that antagonism into war.”

在英德关系中，有三个主要条件, 导致了对立的升级, 和战争的爆发。 +
1.首先，德国人越来越相信, 英国在任何情况下都不会允许德国崛起。与此同时，德国领导人设似乎无法向英国或其他任何人具体说明, 他们国家的崛起, 将或不会重塑世界。 +
2.第二是,双方都担心自己未来的地位会被削弱。具有讽刺意味的是，这种观点鼓励一些领导人相信他们应该尽早发动战争。(先下手为强, 如同二战时日本选择在它巅峰期时, 发动对美国的战争, 以免时间拖得越久, 能源消耗殆尽, 自己就越弱.) +
3.第三是, 双方几乎完全缺乏战略沟通。 +

1905年，德国总参谋长阿尔弗雷德·冯·施利芬, 提出了一项作战计划，以确保德国在欧洲大陆上迅速取得胜利。至关重要的是，该计划涉及入侵比利时，这一行动使英国立即有理由加入了对德宣战。
正如肯尼迪所说，“早在'施利芬计划'成为德国唯一的军事战略之前，两国之间的对抗就已经出现；但正是拜普鲁士总参谋部的非凡天才所赐, 才提供了将这种对抗转变为战争的机会。”


All these conditions now seem to be in place in the U.S.-Chinese relationship. Chinese President Xi Jinping and the CCP leadership are convinced the United States’ main objective is to prevent China’s rise no matter what. China’s own statements regarding its international ambitions are so bland as to be next to meaningless.

所有这些条件, 现在在"美中关系"中似乎都已具备。中国国家主席习近平和中共领导层坚信，美国的主要目标是"无论如何都要阻止中国的崛起"。但中国自己关于其"国际野心"的声明(即自称'中国崛起不会称霸世界'), 是如此平淡，几乎毫无意义。

The potential for strategic miscommunication between China and the United States is rife because of the limited interaction between the two sides.

由于双方互动有限，中美之间存在"战略沟通不畅"的可能性。

'''

==== 老二想要颠覆现有国际秩序, 就会造成国际秩序的不稳定


Beijing has accused Washington of trying to maintain a world order that is inherently unjust—the same accusation Berlin leveled at London. “What the United States has constantly vowed to preserve is a socalled international order designed to serve the United States’ own interests and perpetuate its hegemony,” a white paper published by China’s Ministry of Foreign Affairs declared in June 2022.

北京指责华盛顿试图维持"本质上不公正的世界秩序"——柏林也对伦敦提出了同样的指控。2022年6月，中国外交部发表的一份白皮书宣称:“美国一直发誓要维护的, 所谓的国际秩序, 是旨在为美国自身利益服务，并使其霸权永久化。”

According to the Biden administration’s October 2022 National Security Strategy, “The People’s Republic of China harbors the intention and, increasingly, the capacity to reshape the international order in favor of one that tilts the global playing field to its benefit.” Although opposed to such a reshaping, the administration stressed that “We can’t let the disagreements that divide us stop us from moving forward on the priorities that demand that we work together.”

根据拜登政府2022年10月发布的《国家安全战略》，“中国怀有'重塑国际秩序'的意图，并且越来越有能力重塑国际秩序，以建立有利于其(中国自己)利益的全球竞争环境。” 尽管美国反对这种重塑，但美国政府强调“我们不能让分裂我们的分歧, 阻止我们在'需要我们共同努力的优先事项上'来取得进展。”

'''

==== 颠覆现有国际秩序(正保证'世界和平'的规则)的行为, 还包括贸易战




If the United States wants to prevent a war, it has to convince Chinese leaders that it is not hellbent on preventing China’s future economic development. At the same time, China’s industries cannot keep growing unrestricted at the expense of everyone else. If China continues to flood other markets with its cheap versions of these products, a lot of countries will begin to unilaterally restrict market access to Chinese goods.

如果美国想要阻止战争，它就必须让中国领导人相信，它并不是一心要阻止中国未来的经济发展。与此同时，中国的工业不能以牺牲其他所有国家的利益为代价, 而不受限制地持续增长。如果中国继续用廉价产品涌入其他市场，许多国家，将开始单方面限制中国商品市场准入。

Unrestricted trade wars are not in anyone’s interest. Countries are increasingly imposing higher tariffs on imports and limiting trade and the movement of capital. But if this trend turns into a deluge of tariffs, then the world is in trouble, in economic as well as political terms. The trade wars also contributed significantly to the outbreak of a real war in 1914.

无限制的贸易战, 不符合任何人的利益。各国越来越多地对"进口产品"征收更高的关税，并限制贸易和资本流动。如果这种趋势演变成"关税泛滥"，那么世界在经济和政治方面, 都会陷入困境。贸易战,也对 1914 年战争的爆发做出了重大贡献。

'''


==== 你无法证明自己的言行一致性, 你在他人眼中就会失去信任

Germany insisted on its rights as a great power, dismissing concerns about rules and norms of international behavior.  And it was difficult for Germany to claim, as it did, that it wanted to make a new, more just and inclusive world order.

德国坚持其作为大国的权利，忽视了对国际行为规则和规范的担忧。德国在威胁邻国的同时，也很难宣称自己想要建立一个新的、更公正、更包容的世界秩序.

Many in the Western camp hope that China could play a constructive role in such negotiations, since Beijing has stressed “respecting the sovereignty and territorial integrity of all countries.” China should remember that one of Germany’s major mistakes before World War I was to stand by as Austria-Hungary harassed its neighbors in the Balkans even as German leaders appealed to the high principles of international justice. This hypocrisy helped produce war in 1914. Right now, China is repeating that mistake with its treatment of Russia.

西方阵营许多人, 希望中国能够在(如俄乌战争)此类谈判中, 发挥建设性作用，因为北京强调“尊重所有国家的主权和领土完整”。中国应该记住，德国在第一次世界大战前犯下的重大错误之一，就是在德国领导人呼吁"国际正义"的崇高原则的情况下，却对奥匈帝国骚扰"巴尔干"邻国的行为袖手旁观。这种虚伪(令其他国家对德国的自我说辞, 就不信任了)导致了 1914 年的战争。现在，中国在对待俄罗斯方面, 也正在重蹈覆辙。

'''

==== 防止哪怕是小的热战, 因为很容易升级成大战


Containing trade wars is a start, but Beijing and Washington should also work to end or at least contain hot wars that could trigger a much wider conflagration. During intense great-power competition, even small conflicts could easily have disastrous consequences, as the lead-up to World War I showed.

遏制"贸易战"是一个开始，但北京和华盛顿, 还应该努力结束, 或至少遏制"可能引发更广泛战火的热战"。在激烈的大国竞争中，即使是小冲突, 也很容易造成灾难性后果，正如第一次世界大战的前兆所表明的那样。

Both China and the United States seem to be sleepwalking toward a cross-strait confrontation at some point within the next decade.  Only one possible compromise can likely help avoid disaster.   Washington could say that it will under no circumstances support Taiwan’s independence, and Beijing could declare that it will not use force unless Taiwan formally takes steps toward becoming independent. Such a compromise would not make all the problems related to Taiwan go away. But it would make a great-power war over Taiwan much less likely.

中国和美国似乎都在梦游着, 在未来十年的某个时刻, 发生(台湾问题的)两岸对抗。只有一种可能的妥协, 才能帮助避免灾难. 华盛顿可以表示，在任何情况下都不会支持台湾独立，北京可以宣布，除非台湾正式采取步骤实现独立，否则不会使用武力。这样的妥协并不能解决所有与台湾有关的问题。但这将大大降低因台湾问题爆发"大国战争"的可能性。

'''

==== 双方必须都要有意愿做出妥协, 来改善关系才行

A similar tunnel vision prevailed on the other side.  London eyed Berlin warily, interpreting all its actions as evidence of aggressive intentions. “Few seem to have possessed the generosity or the perspicacity to seek a large-scale improvement in Anglo-German relations,” Kennedy lamented.

(一战前, 除了德国的英国的敌意, )另一边也存在类似的狭隘视野。伦敦警惕地注视着柏林，将其所有行动解读为"侵略意图"的证据. 肯尼迪感叹道：“似乎很少有人有慷慨或洞察力, 来寻求大规模改善英德关系。”


When, in 1972, Soviet and U.S. leaders agreed to a set of “Basic Principles of Relations Between the United States of America and the Union of Soviet Socialist Republics,” the joint declaration achieved almost nothing concrete. But it built a modicum of trust between both sides and helped convince Soviet leader Leonid Brezhnev that the Americans were not out to get him.

1972年，当苏联和美国领导人, 同意一套“美国和苏联之间关系的基本原则”时，这个联合声明几乎没有取得任何具体成果。但至少, 这在双方之间建立了一点信任，并帮助苏联领导人列昂尼德·勃列日涅夫相信，美国人不会出手对付他。(于是防止了冷战升级成热战)

'''

==== 软硬兼施, 硬的一面就是"要保持威慑能力", 是防止战争的有效手段

The rise of great-power tensions also creates the need to maintain believable deterrence. There is a persistent myth that alliance systems led to war in 1914 and that a web of mutual defense treaties ensnared governments in a conflict that became impossible to contain. In fact, what made war almost a certainty after the European powers started mobilizing against one another in July 1914 was Germany’s ill-considered hope that Britain might not, after all, come to the assistance of its friends and allies.

For the United States, it is essential not to provide any cause for such mistakes in the decade ahead. It should concentrate its military power in the Indo-Pacific, making that force an effective deterrent against Chinese aggression. And it should reinvigorate NATO, with Europe carrying a much greater share of the burden of its own defense.

大国紧张局势的加剧, (为防止战争的爆发,) 更需要"保持可信的威慑力"的存在。有一个长期存在的误解认为，是国家间联盟体系, 导致了 1914 年(第一次世界大战)战争的爆发，因为"共同防御条约"的网络, 将各国都拉下了水( 令各国政府卷入了一场无法遏制的冲突中)。事实上，在 1914 年 7 月欧洲列强开始动员起来, 对抗彼此之后，使战争几乎成为定局的原因, 是德国盲目幻想"英国最终不会向其盟友提供军事援助"。 +
对于美国来说，在未来十年内避免此类错误至关重要(意思是不要让中国抱有幻想, 认为美国和西欧会对'中国统一台湾'置之不理)。它应该将军事力量集中在印太地区，使之成为对'中国侵略'的有效威慑。它还应该重振北约，让欧洲承担更大的自身防御负担。

'''

==== 无论两国对抗局势多紧张, 领导人个人的决定, 才是触发战争的最后点火行动



But it wasn’t structural pressures, important as they were, that sparked World War I. War broke out thanks to the contingent decisions of individuals and a profound lack of imagination on both sides. To be sure, war was always likely. But it was unavoidable only if one subscribes to the deeply ahistorical view that compromise between Germany and Britain was impossible.

但引发第一次世界大战的, 并不是结构性压力，尽管它们很重要。战争的爆发, 是由于(决策者)个人的偶然决定, 和双方都严重缺乏想象力。可以肯定的是，战争总是有可能发生。但只有当人们认同"德国和英国之间不可能达成妥协"这一根深蒂固的非历史观点时，这种情况(即战争爆发)才是不可避免的。

Structure is not destiny. The decisions that leaders make can prevent war and better manage the tensions that invariably rise from great-power competition. As with Germany and Britain, structural forces may push events to a head, but it takes human avarice and ineptitude on a colossal scale for disaster to ensue. Likewise, sound judgment and competence can prevent the worst-case scenarios.

结构不是命运。领导者做出的决定, 可以防止战争, 并更好地管理大国竞争必然引发的紧张局势。与德国和英国一样，"结构性力量"可能会将事态推向紧要关头，但人类的贪婪和无能, 才会导致灾难的发生。同样，良好的判断力和能力, 可以防止最坏的情况发生。


'''




== (pure) 两强如何避免战争


How two traditionally friendly peoples ended up in a downward spiral of mutual hostility that led to World War I.  +
Germany’s rapid economic rise shifted the balance of power and enabled Berlin to expand its strategic reach. Some of this expansion— especially at sea—took place in areas in which Britain had profound and established strategic interests. The two powers increasingly viewed each other as ideological opposites, wildly exaggerating their differences.


As late as 1995, China’s GDP was around ten percent of U.S. GDP. By 2021, it had grown to around 75 percent of U.S. GDP.


Such generosity or perspicacity is also sorely missing in relations between China and the United States today.  Similar to the situation a century ago, profound structural factors fuel the antagonism. Economic competition, geopolitical fears, and deep mistrust work to make conflict more likely.

'''

==== 认为对方铁定是要压制自己, 就会造成冤冤相报, 进而双方关系螺旋下降

According to many Germans (and some non-Germans, too), Germany was now the strongest power on the continent and that it should be left free to rationally reorder the region according to the reality of its might.  German leaders began viewing British interference as the root cause of their country’s problems, both at home and abroad. On their side, British leaders imagined that Germany was largely responsible for the relative decline of the British Empire, even though many other powers were rising at Britain’s expense.


Some argue that China would have dramatically expanded its military capabilities no matter what the United States did two decades ago. After all, that is what major rising powers do as their economic clout increases. But the specific timing of Beijing’s expansion was clearly linked to its fear that the global hegemon had both the will and the capacity to contain China’s rise if it so chose. Just as Germany began fearing that it would be hemmed in both economically and strategically in the 1890s and the early 1900s— exactly when Germany’s economy was growing at its fastest clip— China began fearing it would be contained by the United States just as its own economy was soaring.


In the British-German relationship, three main conditions led from rising antagonism to war.  +

The first was that the Germans became increasingly convinced that Britain would not allow Germany to rise under any circumstances. At the same time, German leaders seemed incapable of defining to the British or anyone else how, in concrete terms, their country’s rise would or would not remake the world.

The second was that both sides feared a weakening of their future positions. This view, ironically, encouraged some leaders to believe that they should fight a war sooner rather than later.

The third was an almost total lack of strategic communication.

In 1905, Alfred von Schlieffen, chief of the German general staff, proposed a battle plan that would secure a swift victory on the continent. Crucially, the plan involved the invasion of Belgium, an act that gave Britain an immediate cause to join the war against Germany.

As Kennedy put it, “The antagonism between the two countries had emerged well before the Schlieffen Plan was made the only German military strategy; but it took the sublime genius of the Prussian General Staff to provide the occasion for turning that antagonism into war.”


All these conditions now seem to be in place in the U.S.-Chinese relationship. Chinese President Xi Jinping and the CCP leadership are convinced the United States’ main objective is to prevent China’s rise no matter what. China’s own statements regarding its international ambitions are so bland as to be next to meaningless.

The potential for strategic miscommunication between China and the United States is rife because of the limited interaction between the two sides.


'''

==== 老二想要颠覆现有国际秩序, 就会造成国际秩序的不稳定


Beijing has accused Washington of trying to maintain a world order that is inherently unjust—the same accusation Berlin leveled at London. “What the United States has constantly vowed to preserve is a socalled international order designed to serve the United States’ own interests and perpetuate its hegemony,” a white paper published by China’s Ministry of Foreign Affairs declared in June 2022.


According to the Biden administration’s October 2022 National Security Strategy, “The People’s Republic of China harbors the intention and, increasingly, the capacity to reshape the international order in favor of one that tilts the global playing field to its benefit.” Although opposed to such a reshaping, the administration stressed that “We can’t let the disagreements that divide us stop us from moving forward on the priorities that demand that we work together.”


'''

==== 颠覆现有国际秩序(正保证'世界和平'的规则)的行为, 还包括贸易战




If the United States wants to prevent a war, it has to convince Chinese leaders that it is not hellbent on preventing China’s future economic development. At the same time, China’s industries cannot keep growing unrestricted at the expense of everyone else. If China continues to flood other markets with its cheap versions of these products, a lot of countries will begin to unilaterally restrict market access to Chinese goods.


Unrestricted trade wars are not in anyone’s interest. Countries are increasingly imposing higher tariffs on imports and limiting trade and the movement of capital. But if this trend turns into a deluge of tariffs, then the world is in trouble, in economic as well as political terms. The trade wars also contributed significantly to the outbreak of a real war in 1914.


'''


==== 你无法证明自己的言行一致性, 你在他人眼中就会失去信任

Germany insisted on its rights as a great power, dismissing concerns about rules and norms of international behavior.  And it was difficult for Germany to claim, as it did, that it wanted to make a new, more just and inclusive world order.


Many in the Western camp hope that China could play a constructive role in such negotiations, since Beijing has stressed “respecting the sovereignty and territorial integrity of all countries.” China should remember that one of Germany’s major mistakes before World War I was to stand by as Austria-Hungary harassed its neighbors in the Balkans even as German leaders appealed to the high principles of international justice. This hypocrisy helped produce war in 1914. Right now, China is repeating that mistake with its treatment of Russia.


'''

==== 防止哪怕是小的热战, 因为很容易升级成大战


Containing trade wars is a start, but Beijing and Washington should also work to end or at least contain hot wars that could trigger a much wider conflagration. During intense great-power competition, even small conflicts could easily have disastrous consequences, as the lead-up to World War I showed.


Both China and the United States seem to be sleepwalking toward a cross-strait confrontation at some point within the next decade.  Only one possible compromise can likely help avoid disaster.   Washington could say that it will under no circumstances support Taiwan’s independence, and Beijing could declare that it will not use force unless Taiwan formally takes steps toward becoming independent. Such a compromise would not make all the problems related to Taiwan go away. But it would make a great-power war over Taiwan much less likely.


'''

==== 双方必须都要有意愿做出妥协, 来改善关系才行

A similar tunnel vision prevailed on the other side.  London eyed Berlin warily, interpreting all its actions as evidence of aggressive intentions. “Few seem to have possessed the generosity or the perspicacity to seek a large-scale improvement in Anglo-German relations,” Kennedy lamented.



When, in 1972, Soviet and U.S. leaders agreed to a set of “Basic Principles of Relations Between the United States of America and the Union of Soviet Socialist Republics,” the joint declaration achieved almost nothing concrete. But it built a modicum of trust between both sides and helped convince Soviet leader Leonid Brezhnev that the Americans were not out to get him.


'''

==== 软硬兼施, 硬的一面就是"要保持威慑能力", 是防止战争的有效手段

The rise of great-power tensions also creates the need to maintain believable deterrence. There is a persistent myth that alliance systems led to war in 1914 and that a web of mutual defense treaties ensnared governments in a conflict that became impossible to contain. In fact, what made war almost a certainty after the European powers started mobilizing against one another in July 1914 was Germany’s ill-considered hope that Britain might not, after all, come to the assistance of its friends and allies.

For the United States, it is essential not to provide any cause for such mistakes in the decade ahead. It should concentrate its military power in the Indo-Pacific, making that force an effective deterrent against Chinese aggression. And it should reinvigorate NATO, with Europe carrying a much greater share of the burden of its own defense.


'''

==== 无论两国对抗局势多紧张, 领导人个人的决定, 才是触发战争的最后点火行动



But it wasn’t structural pressures, important as they were, that sparked World War I. War broke out thanks to the contingent decisions of individuals and a profound lack of imagination on both sides. To be sure, war was always likely. But it was unavoidable only if one subscribes to the deeply ahistorical view that compromise between Germany and Britain was impossible.

Structure is not destiny. The decisions that leaders make can prevent war and better manage the tensions that invariably rise from great-power competition. As with Germany and Britain, structural forces may push events to a head, but it takes human avarice and ineptitude on a colossal scale for disaster to ensue. Likewise, sound judgment and competence can prevent the worst-case scenarios.



'''














































