
= 核心词汇类记 2-1 思考判断
:toc:
---

== 思考, 分析, 评估, 估价, 高估, 低估

==== consider (仔细考虑; 认为, 觉得)
=> con-, 强调。-sider, 星，词源同star, sidereal. 古义指星相学看星占卜，并通过星辰移位来思考预测人间万事。比较disaster, 星位不正，空难。

- v. *consider sb/sth (as) sth* : 以特定的方式考虑某人[某事物]; 认为; 以为; 觉得 to think of sb/sth in a particular way
* These workers *are considered (as) a high-risk group*. 这些工人被视为属高风险人群。
* *Who do you consider* (to be) responsible for the accident? 你认为谁对这个事故负有责任？

- v. *（尤指为作出决定而）仔细考虑，细想* to think about sth carefully, especially in order to make a decision
* *She considered her options*. 她仔细考虑了自己的各种选择。
* a *carefully considered* response 经过仔细考虑的回复

- v. *仔细看某人[某事物]*; ( formal ) to look carefully at sb/sth
* He stood there, *considering the painting*. 他站在那里，凝视着那幅画。

---

==== (v.)analyse /(n.) analysis /(a.)analytic (仔细思考, 或做实验以分析)
=> 前缀ana-, 向上，向后。词根lys, 松开，同lose, loose. 即松开进行分析。

* V-T *你仔细考虑它, 或使用统计方法，以充分了解它。分析* If you analyse something, you consider it carefully or use statistical methods in order to fully understand it.
- He tried to *analyse his feelings*. 他试图分析自己的感情。
- The blood samples are sent to the laboratory *for analysis*(n.) . 血样要送往实验室进行分析。

---

==== rate (划分等级; 评价为)
* *rate sb/sth (as) sth +
rate as sth* : *认为某人[某物]具有某一特定水平的质量、价值等* to have or think that sb/sth has a particular level of quality, value, etc. 评估；评价；估价
- *They rated him highly* as a colleague. 作为同事，他们对他评价甚高。
- I'm afraid *our needs do not rate(v.) very high with this administration*. 我们的需求恐怕不会受到这届政府的多大重视。

---


==== cost (估算成本；估价)
=> co-, 强调。-st, 站。字面意思即站在旁边的，要求投入的。

* *cost(v.) sth (out)* : *估计某物需要多少钱, 或某物的价格是多少* to estimate how much money will be needed for sth or the price that should be charged for sth 估算成本；估价
- Their accountants *have costed the project at $8.1 million*. 他们的会计师估算此项工程成本为810万元。

---

==== estimate (估价；估算)
=> 来自aes, 铜，词源同ore, -tim, 砍，切，词源同anatomy. 比较同源词esteem.

- *estimate sth (at sth)* : V-T *对某物的成本、大小、价值等形成一种概念，但不精确计算* If you estimate a quantity or value, *you make an approximate judgment or calculation of it*.

* *I estimate that* total cost for treatment will go from $9,000 to $12,500.
我估计治疗费总额将在9千美元到1.25万美元之间。
* Police *estimate* the crowd *at* 30 000. 警方估计聚集的人有3万。

---

==== underestimate (低估)
* v. 认为或猜测某物的数量、成本或大小, 比实际小 to think or guess that the amount, cost or size of sth is smaller than it really is 低估；对…估计不足
- *We underestimated the time* it would take to get there. 我们低估了抵达那里所需的时间。

* v. 没有意识到一个人有多好、多坚强、多有决心等等 to not realize how good, strong, determined, etc. sb really is 对…认识不足（或重视不够）；低估；轻视
- *Never underestimate* your opponent. 决不可低估你的对手。

---

==== discount (打折价; 低估)
* *discount(v.) sth (as sth)* : ( formal ) to think or say that sth is not important or not true 认为…不重要；对…不全信；低估
- *We cannot discount the possibility of* further strikes. 我们不能低估再次发生罢工的可能性。


---

==== evaluate (估计；评价；评估)
=> e-, 向外。-val, 力量，价值，词源同value, valiant.

- v. 仔细考虑后, 对某物的数量、价值或质量, 形成意见 to form an opinion of the amount, value or quality of sth after thinking about it carefully

* Our research *attempts to evaluate the effectiveness of the different drugs*. 我们的研究试图对不同药物的疗效进行评估。
* *We need to evaluate* how well the policy is working. 我们需要对这一政策产生的效果作出评价。

---

==== appraisal (评估性质品质,数量)
=> 前缀ap-同ad-. -praise同price, 价格，即评估。

* v. 对某人[某事物] 的价值、表现或性质的判断; 评价；估价；估计；鉴定 a judgement of the value, performance or nature of sb/sth

- What is needed [in such cases] is *a calm appraisal(n.) of the situation*. 在此类情况下需要的是对形势的冷静估计。
- She was honest *in her appraisal(n.) of her team's chances*. 她对自己队获胜机会的估计是诚实的。
- staff/performance appraisal 员工╱工作表现评估
-  It may also be necessary *to get a new appraisal(n.) of the property*. 可能还需要对该房产做个新的估价。

---

==== assess (评估性质品质;估算价格数量)
=> 来源于拉丁语中由前缀ad-(临近)和动词sedere(坐)组成的复合动词assidere的过去分词词干assess-,经古法语assesser进入英语。坐在旁边 → 坐在法官旁协助其修正罚金或税收的数量 → 估价。 词根词缀： as-临近 + -sess-坐

* *assess(v.) sb/sth (as sth)* : 对某人[某事物]的性质或品质作出判断 to make a judgement about the nature or quality of sb/sth 评估，评定（性质、质量）

- It's difficult *to assess the effects of these changes*. 这些变化带来的效果难以评估。
- *I'd assess* your chances *as* low. 我估计你的机会不大。
- The test was *to assess aptitude rather than academic achievement*. 该测试将评估能力而不是学业成绩。

*  *assess sth (at sth)* : 计算出某物的数量或价值 to calculate the amount or value of sth 估算，估定，核定（数量、价值）
- Damage to the building *was assessed at ￡40 000*. 该建筑物的损失估定为4万英镑。

---

==== approximate (近似计算；概略估算)
=> 前缀ap-同ad-.词根prop, 接近，向前，pro的扩大形式。-m, 最高级后缀. / ap-加强意义 + -proxim-接近 + -ate动词词尾

* v. 大概地计算或估计某事物 to calculate or estimate sth fairly accurately 近似计算；概略估算
- The total cost *will approximate ￡15 billion*. 总费用大致为150亿英镑。
- a formula *for approximating the weight of a horse* 估算一匹马重量的公式

* V-T 与另一物相似，但又不完全相同 If something approximates something else, it is similar to it but is not exactly the same. 近似于
- The mixture described below *will approximate it, but is not exactly the same*.
下面所描述的混合物会与之近似，但不完全一样。

---

==== gauge (大概估算, 对人的情感态度做出判断)
=> 来自PIE ghalgh, 杆，棍，词源同gallows. 字母l软化成u. 词义由杆，棍引申为测量，比较canon, 词源同cane.

* v. (gauge 本意是"测量仪器（或仪表）；计量器", 动词是"（用仪器）测量") *近似地计算* to calculate sth approximately 估计；估算
- *We were able to gauge(v.) the strength of the wind* from the movement of the trees. 我们可根据树的摇动估计风力。

* v. 对…作出判断，尤指对人的感情或态度 to make a judgement about sth, especially people's feelings or attitudes 判定，判断（尤指人的感情或态度）
- They interviewed employees *to gauge their reaction to the changes*. 他们与雇员面谈以判定他们的应变能力。
- He tried to *gauge her mood*. 他试图揣摩她的心情。



---

== 预想, 推测, 预测, 预料

==== calculate (预测；推测)
=> 来源于拉丁语名词calculus(小石头),古罗马人用calculus计数,选举时用calculus计票。 词根词缀： -calcul-小石头 + -ate动词词尾

- v. 通过所有可用的信息, 来猜测某事, 或形成观点; 预测；推测 to guess sth or form an opinion by using all the information available

* It is impossible *to calculate what influence he had* on her life. 现在无法估计他对她的生活产生过多大影响。

---

==== anticipate (预料并做好准备)
=> anti（在…之前）+cip（拿、取）+ate（动词后缀）→提前取得→期望

* V-T 预期；预料未来可能发生的某事, 并做好准备  If you anticipate an event, you realize in advance that it may happen and you are prepared for it.

- At the time *we couldn't have anticipated the result of our campaigning*. 当时我们不可能预期到我们活动的结果。
- *It is anticipated that* inflation will stabilize at 3%. 据预测，通货膨胀将稳定在3%。

* v. 先于…做；早于…行动 (formal) to do sth before it can be done by sb else
- When Scott reached the South Pole he found that *Amundsen had anticipated him*. 斯科特到达南极时发现阿蒙森已先到过那里。

---

== 怀疑, 问

---

== 意识到, 觉察到, 注意到, 转移注意力

==== observe (看到,注意到; 说话; 遵守, 庆祝)
=>ob-,向前，朝向，-serve,注视，观察，保护，词源同conserve,hero.引申词义坚守，遵守，遵行等。

* v. to see or notice sb/sth 看到；注意到；观察到
- *Have you observed any changes* lately? 最近你注意到什么变化没有？

* v. 仔细观察某人[某事物]，尤指更多地了解他们 to watch sb/sth carefully, especially to learn more about them 观察；注视；监视
- I felt *he was observing everything I did*. 我觉得他正在注视着我做的每一件事。
- *The patients were observed* over a period of several months. 这些病人被观察了数月之久。

* v. ( formal ) to make a remark 说话；评论
- *She observed that* it was getting late. 她说天色晚了。

* v. to obey rules, laws, etc. 遵守（规则、法律等）
- The crowd *observed a minute's silence* (= were silent for one minute) in memory of those who had died. 众人为死者默哀一分钟。

* v. 庆祝节日、生日等 ( formal )  to celebrate festivals, birthdays, etc. 庆祝；庆贺；欢度
- *Do they observe Christmas*? 他们过不过圣诞节？

---

==== alive (意识到)
*  *alive(a.) to sth* : 意识到某事; 知道某事存在并且很重要 aware of sth; knowing sth exists and is important
- *to be alive(a.) to the dangers*/facts/possibilities 意识到危险；认识到事实；注意到可能

---


==== divert (转移注意力)
=>  di-分开 + -vert-转

v. 把某人的注意力从某事上移开  to take sb's thoughts or attention away from sth 转移（某人）的注意力；使分心
- They want to *divert* the attention of the people *from* the real issues. 他们想把人民的注意力从真正的问题上转移开。

---

== 视为, 认为, 定性, 或刻板印象

==== regard (认为是；看作为)
=>re-,再，重新，-gard,看，看护，词源同 guard,ward.引申诸相关词义。

* *regard(v.) sb/sth (with sth) +
regard sb/sth as sth* : to think about sb/sth in a particular way 将…认为；把…视为；看待
- *She is widely regarded as* the current leader's natural successor. 人们普遍认为她是现任领导的当然继任者。

* v. ( formal ) to look at sb/sth, especially in a particular way （尤指以某种方式）注视，凝视
- *He regarded us suspiciously*. 他以怀疑的眼光看着我们。

==== account (认为是；看作为)
=> 来自于拉丁语compute,来自于词根put,思考，计算。 / ac-加强意义 + -count-计算,讲故事 →账目/说明

- v. 认为某人[某事物]是某特定的对象 [ usually passive ] ( formal ) to have the opinion that sb/sth is a particular thing

* In English law *a person is accounted innocent* until they are proved guilty. 按英格兰法律，一个人未经证实有罪之前被视为无罪。

---


==== count (看做, 视为)
=> 来源于拉丁语computare(计算),传入古法语变为conter,其"加起来报账"的含义后来被引申为"讲故事",这个意义在派生词account和recount中有所体现。

- *count(v.) sb/sth (as) sb/sth +
 count as sb/sth* : 以特定的方式考虑某人[某事物];以特定的方式考虑; 认为；看作；算作；被视为  to consider sb/sth in a particular way; to be considered in a particular way
* For tax purposes *that money counts/is counted as income*. 那笔钱算作收入，需要纳税。
* *I count myself lucky* to have known him. 和他相识，我觉得很幸运。

---

==== deem (认为是；视为；相信)
=> 词源同doom，裁定，判决，后词义弱化为认为，视为。

- v.  你对某事物,有特定的看法; 认为；视为；相信 ( not usually used in the progressive tenses 通常不用于进行时 ) ( formal ) [ V (that)VN to inf ] to have a particular opinion about sth
*  *She deemed it prudent* not to say anything. 她认为什么都不说是明智的。
* They would take *any action (deemed necessary)* . 他们会采取认为必要的任何行动。

---

==== reckon (想；认为)
* v. ( informal ) ( especially BrE ) to think sth or have an opinion about sth 想；认为
- *I reckon (that)* I'm going to get that job. 我认为我会得到那份工作。

* *be reckoned* 被普遍认为是... ( not used in the progressive tenses 不用于进行时 ) to be generally considered to be sth 被普遍认为是；被看作是
- *Children are reckoned* to be more sophisticated nowadays. 人们认为今天的孩子比过去世故。

* *reckon sth (at sth)* : 计算数量、数字等 to calculate an amount, a number, etc. 估算；估计；计算
- *They reckon (that)* their profits are down by at least 20%. 他们估计利润至少下降了20%。
- The journey *was reckoned to take about two hours*. 路上估计要花大约两个小时。

* *RECKON ON STH* : 期待某事发生, 或指望某事发生 to expect sth to happen /or to rely on sth happening 指望；依赖
- *We'd reckoned on* having good weather. 我们原指望会有好天气。


---

==== esteem (把…看作；认为 old-fashioned)
=> 来自拉丁语aestimare, 估计，评估，判定价值，来自aes, 铜，词源同ore, -tim, 砍，切，词源同anatomy. 原指铸造铜币，估计并判定币值，该词义见estimate.同时，引申义尊重，尊敬，即值得一看的，值得考虑的。

- v. (esteem 本意是"尊重；敬重") 把…看作；认为 ( old-fashioned formal ) to think of sb/sth in a particular way
* *She was esteemed* the perfect novelist. 她被认为是最完美的小说家。

---


==== figure (认为，认定（某事将发生或属实）)
- v. 认为，认定（某事将发生或属实） ( informal ) to think or decide that sth will happen or is true
[ V (that) ] / If you figure that something is the case, you think or guess that it is the case.
* *We figured* the sensible thing to do was to wait. 我们认为，明智的做法是等待。
* *She figured that* both she and Ned had learned a lot from the experience. 她想她和内德都从这次经历中学到了很多。

---

==== fancy (自认为是, 误以为)
=> 缩写自fantasy, 幻想，空想。

- [ V (that) ] 认为；想象 ( literary ) to believe or imagine sth
* *She fancied (that)* she could hear footsteps. 她觉得好像听到了脚步声。

- *fancy(v.) yourself (as) sth* :  喜欢做某事的想法; 或者常常错误地认为自己是某物; 自认为是；自命为 ( BrE ) to like the idea of being sth /or to believe, often wrongly, that you are sth
* So *you fancy yourself as the boss someday*? 那么你认为自己有一天会成老板？

- *fancy(v.) yourself* : 认为自己很受欢迎，有吸引力或很聪明; 自负；自命不凡 ( BrE informal disapproving ) to think that you are very popular, attractive or intelligent
* He started to chat to me /and I could tell that *he really fancied himself*. 他和我聊起天来，我看得出他确实自以为了不起。

---

== 改进想法, 改进观点


---

== 决心, 决定

















