= 0103
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 103: Making a Sales Call.
This is English as a Second Language Podcast episode 103. I’m your host, Dr. Jeff McQuillan, from the Center for Educational Development in beautiful Los Angeles, California.
Today’s podcast is about making a telephone call for a sales person. Let’s get started!
[start of dialogue]
Last week, I was at a business luncheon and I met a woman named Dana Okri who was heading a new start up. I have been a sales rep for Eureka Corp. for three years now and our bread and butter is data management software. I told her briefly about our products over lunch and she had given me her card.
I decided to follow up with a call. I dialed her direct line and fortunately, I got a hold of her on the first try.
Dana: Hello, Dana Okri.
Kevin: Hello, Dana, this is Kevin Abrahams from Eureka Corp. I don't know if you'll remember me but we met last week at the Chamber of Commerce luncheon.
Dana: Oh, yes. Hi. How are you?
Kevin: Great. Do you have a few minutes right now for me to tell you a little bit more about the data management tools our company has to offer? It won't take long.
Dana: Actually, I'm really swamped right now and I'll be going into a meeting in a few minutes. Is there any literature you can send me?
Kevin: Oh, sure, I understand. I'd be happy to send you a promotional packet about the programs that I think might best suit a company your size. Would it be okay if I called again to see if you have any questions?
Dana: Let's do this. Since I'm not sure when I'll get a chance to read the material, why don't I give you a call if I have any questions. Now, I'm really sorry, but I have to get going to this meeting.
Kevin: No problem at all. I won't keep you any longer. I'll put a package to you in the mail and we'll go from there.
Dana: Sounds good.
Kevin: Thanks for your time.
Dana: No problem. Bye-bye.
[end of dialogue]
Our story begins with a man talking about how he was at a “business luncheon” and he met a woman named Dana who was “heading a new start up.” A “business luncheon” “luncheon” (luncheon) is a formal business lunch, usually with many people. The woman was named “Dana.” In other words, her name was “Dana,” and she was “heading a new start up.” “To be heading something” means to be the boss, the person who is organizing and leading it. A “start up” – a “start up” is two words, it’s a noun which refers to a new company. Particularly in the Internet world, we talk about “start ups,” meaning new Internet companies, but it can also just mean any new company, a “start up.”
The man says he’s a “sales rep” for Eureka Corp. A “sales rep” (rep) – “rep” stands here for “representative,” so when someone says they’re a “sales rep,” they mean they are “sales representative,” which is just another name for a salesperson, someone who sells for a company. He mentioned that the “bread and butter” of their company, his company, is data management software. The expression, “our bread and butter,” means this is where we make most of our money. This is the most important part of our business. So, a business can have many different branches or divisions or sections but usually, there’s one, what you might call “core” (core), or main principal, primary business and that’s where you make your most money. And that’s what the expression here means “our bread and butter.” It means that’s what where we earn the money to – literally, to buy our bread and butter, is the original, I’m sure, connection.
“Data management software” is a computer program that helps people organize information. The woman gives the sales rep her “card,” meaning her business card, and the man decides to follow up their conversation with a “call.” The verb, “follow up” or “to follow up,” is used when you talk to someone or have a conversation or an email and you agree to do something or you have an appointment or something that you need to continue talking about. One of the people in the conversation may “follow up,” that is I talk to you on Monday and you say you’re going to think about buying one of my products. I call back on Friday to “follow up,” in other words, to check, to see if you are still interested. And you can use this expression in lots of different places. Sometimes, for example, if you go to the doctor and the doctor says, “Hmm, well, you’re okay now but I want you to come back in two weeks for a follow-up appointment.” Here it’s used as an adjective. “This is an appointment so that I can check you again.” So, that’s the meaning of follow up. “With a call,” of course, means with a telephone call.
He says he dials her “direct line” and fortunately he got hold of her on the first try. “To dial” means, of course, to dial in a telephone. To press the numbers means “to dial.” The “direct line” -- in a company that has many different people working in it, often times, you have a general number where you call, and you get a secretary or the operator, and you have to ask for somebody in the company that you want to speak with. The “direct line” would be the number directly to that person. You don’t have to go through the operator. The man says he fortunately, “got a hold of” the woman on the first try. “To get a hold of” means to reach someone, to be able to – the other person answered the phone. “I got a hold of you,” or, “I’m trying to get a hold of you.” “I’m trying to call you so that” – when you are there to pick up your phone. The man says that he got the woman on the “first try” or on the “first attempt.” The first time he tried, he was able to reach her.
The woman answers the phone and the man says, “Hello Dana. This is Kevin Abrahams from Eureka Corp. I don’t know if you’ll remember me but we met last week at the luncheon,” at the Chamber of Commerce Luncheon. The expression, “I don’t know if you’ll remember me but,” is what you would use when you’re calling someone and you only met them once, maybe twice. They may, in fact, not remember who you are so it’s kind of a polite way of saying, “Do you remember me?” “I don’t know if you’ll remember me but we talked on the telephone last week.” Now, here, they met at a “Chamber of Commerce” luncheon – and the “Chamber of Commerce” is a private group of businesses that – it’s like an organization that businesses in a specific area, usually, can belong to. So, Los Angeles has a Chamber of Commerce and they have meetings and they do all sorts of things to help businesses in a particular area. And most American cities have a Chamber of Commerce. “Commerce,” of course, is business and a “chamber” literally is a big room where everybody sits, but here it just means an organization, a business organization. The man asked Dana if she has a few minutes right now. “Do you have a few minutes right now for me to tell you a little bit more?” meaning, “Is this a good time?” Do you have time right now to talk? Do you have a few minutes?”
The man, Kevin, says, “It won’t take long,” meaning it won’t take up a lot of your time. I won’t talk to you very long. “It won’t take long.” The woman says she’s really “swamped” right now. “To be swamped” means to be very busy, to be extremely busy. “I’m swamped right now.” She asked the man if he has any “literature” he can send her, and, here, “literature” means information, printed information, a letter, a brochure, a catalogue that he can send her. We also use “literature,” of course, to mean “books” and usually, good books, fiction books and so forth, but here it just means -- in a business setting, when someone says, “Do you have any literature on it?” they mean, “Do you have anything printed, something you can give me that I can look at?”
Kevin says, “Sure.” He will send her a “promotional packet.” A “packet” is just a collection of information, usually more than one thing in a “packet” (packet). It’s kind of like a package, a packet is. “Promotional” – “to promote something” is like to try to give people information so that they will buy it. The verb “to promote” means to advertise, to make known, to tell other people. “We’d like to promote ESL Podcast.” We want other people to come and listen to us. The adjective is “promotional packet.” It’s a packet of information, a set of pieces of information that are about that particular product. Kevin says he thinks he can send her information about what might “best suit” a company. “To suit (suit) a company” means what would be appropriate from you, what would be correct or right for you. We use this verb in a lot of different ways. You can say, for example, about a piece of clothing – a shirt, or a pair of pants. “That doesn’t suit you,” meaning it’s not right for you. It’s not appropriate for you.
The man then asks, “Would it be okay if I called again?” He’s asking permission. Is it okay? “Would it be okay if I call you again?” And the woman says, “Let’s do this.” And when someone says, “Let’s do this,” they’re proposing, they’re giving them another option, another possibility, and here, it’s clear the woman wants to get off the telephone, so she tells the sales person what she wants to happen. She says, “Lets’ do this. Why don’t I give you call if I have any questions.” That expression, “Why don’t I,” is when you are proposing something to someone and you want them to agree to you – to your idea. “Why don’t you call me tomorrow” means could you please call me tomorrow. The woman then says she’s very busy and she has to “get going,” meaning she has to leave, she has to go to her meeting. “I have to get going.” The man says, “Oh, I won’t keep you any longer.” When someone “keeps” you, that means that they are preventing you from going. You may hear someone say, “I don’t want to keep you” – means I don’t want to delay you, to make you stay here. And so he says “I don’t want to keep you any longer.” He will mail the package or the packet in the mail and “we’ll go from there.” The expression, “we’ll go from there,” means I’ll send you the package. You look at it and then we’ll see what happens, so it’s a general expression to mean “We will continue on in this conversation or this relationship,” whatever it is, after you receive, in this case, the package or some other event happens.
The woman says, “Sounds good,” meaning, “Okay I agree.” “That sounds good” means that’s something I agree with. And the man, Kevin, thanks her for her time and she says, “No problem.” And remember, when somebody thanks you in English, it’s more common, informally, for people, instead of just say, “You’re welcome,” many people say, “Oh, no problem,” meaning it did not cause me any problem. It’s okay.
Now let’s listen to the dialogue this time at native rate of speech.
[start of dialogue]
Last week, I was at a business luncheon and I met a woman named Dana Okri who was heading a new start up. I have been a sales rep for Eureka Corp. for three years now and our bread and butter is data management software. I told her briefly about our products over lunch and she had given me her card.
I decided to follow up with a call. I dialed her direct line and fortunately, I got a hold of her on the first try.
Dana: Hello, Dana Okri.
Kevin: Hello, Dana, this is Kevin Abrahams from Eureka Corp. I don't know if you'll remember me but we met last week at the Chamber of Commerce luncheon.
Dana: Oh, yes. Hi. How are you?
Kevin: Great. Do you have a few minutes right now for me to tell you a little bit more about the data management tools our company has to offer? It won't take long.
Dana: Actually, I'm really swamped right now and I'll be going into a meeting in a few minutes. Is there any literature you can send me?
Kevin: Oh, sure, I understand. I'd be happy to send you a promotional packet about the programs that I think might best suit a company your size. Would it be okay if I called again to see if you have any questions?
Dana: Let's do this. Since I'm not sure when I'll get a chance to read the material, why don't I give you a call if I have any questions. Now, I'm really sorry, but I have to get going to this meeting.
Kevin: No problem at all. I won't keep you any longer. I'll put a package to you in the mail and we'll go from there.
Dana: Sounds good.
Kevin: Thanks for your time.
Dana: No problem. Bye, bye.
[end of dialogue]
That’s all we have time for. From Los Angeles, California, I’m Jeff McQuillan. We’ll see you next time on ESL Podcast.
ESL Podcast is a production of the Center for Educational Development in Los Angeles, California. This podcast is copyright 2005. No part of this podcast may be sold or redistributed without the expressed written permission of the Center for Educational Development.
Glossary
luncheon – a formal lunch that is eaten with other people; a lunch one eats that is linked to a special event, such as an important business meeting
* Our company had a luncheon to celebrate the company’s 50th year in business.
to head – to lead; to lead something that involves other people, like a company or project
* Amita headed the recycling project at her company, but she got help from four other workers.
start up – a new company or business; a company or business that is just starting
* The small publishing company was a start up that had only been in business for two months.
sales rep – sales representative; someone who sells a product or service for a company and earns money doing it
* Geraldo was the company’s best sales rep and sold products to business across New York State.
bread and butter – the main product or service a company sells that earns the company the largest amount of money
* Even though the company sold many products, computers is its bread and butter.
data management software – a computer program that organizes large amounts of information; a computer program or application that helps a business organize information by creating lists and reports
* The manager used data management software to organize the company’s financial records and employee information.
direct line – a business telephone number that allows one to reach the person one wants to speak to directly, without talking to anyone else first
* Lashawnda had the phone number to Edmund’s direct line, so she did not need to call the company’s main phone number.
to get a hold of (someone) – to contact or be able to talk to someone, usually by using a telephone
* Gina called her professor three times, but she could not get a hold of her and was unable to ask her a question.
swamped – very busy; unable to do anything else because one has a large amount of work or a large number of tasks to complete
* Frederick was swamped with so much work that he could not take his vacation as he had planned.
literature – written information; written materials that give information about an idea, product, or service
* When Diana learned that she had a medical condition, her doctor gave her literature that she could read at home to learn about the condition.
promotional packet – a group of papers, reports, and other written information that a company sends to individuals or other companies to tell them about a product or service
* Jonas sent the company a promotional packet with information about the new cleaning products his company offers.
to suit – to be helpful or useful to someone or something
* Erika liked the way the boots looked, but they did not suit her needs because they had a high, thin heel and she needed to be able to walk in the woods.
to keep (someone) – to prevent or stop someone from doing something
* Chad talked to his manager for so that that it kept her from her other meetings.
Culture Note
Makeup for Men
Cosmetic companies make a lot of money each year selling “skin care products” (products applied to the face and body to make it look younger) and “cosmetics” (color liquid, creams, and powders applied to the face to change its appearance) to women. Now, it’s “going after” (trying to get) men.
“Grooming” (making yourself look neat and clean) products, including skin care and “makeup” (cosmetic) products, for men are nothing new. According to a 2012 Los Angeles Times article, 1 in 4 men use some kind of skin care product. According to this article, some of the “burgeoning” (beginning to grow or increase quickly) interest in men’s skin care and makeup products can “be attributed to” (is because) baby boomers are getting older and trying to compete in the workplace with younger men. Some of the new makeup products becoming more popular are “concealers,” a type of cosmetic the same color as your skin used to cover “blemishes” (imperfections) and dark circles under the eyes, and anti-shine powder, which goes on the skin to make it appear less oily.
Companies are “capitalizing on” (taking advantage of) this growing interest and are being more “aggressive” (more forceful) about marketing to men. How do you market products to men who may be “squeamish about” (having a strong view against) using products that seem too “feminine” (with characteristics traditionally associated with women)?
First, you don’t call the products “makeup.” Instead, companies are doing two things: creating “packaging” (the container that a product is placed in to be sold) that are “manly” (with characteristics traditionally associate with men, such as strength and courage), such as ones that look like cigar boxes and “liquor” (alcoholic drinks) bottles, and giving products names with manly “associations” (connections), such as “fuel” (material used to produce heat and power, such as gasoline) and “power.”