= 0109
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 109: Being an Entrepreneur.
This is English as a Second Language Podcast number 109. I’m your host, Dr. Jeff McQuillan, from the Center for Educational Development in beautiful Los Angeles, California.
Today’s podcast is about being an entrepreneur. Let’s get started!
[start of story]
I had lunch today with my friend Sam. She recently quit her job with a large company to strike out on her own. She has always been an entrepreneur in small ways, but she decided to start her own business. The start-up she launched provided technology consulting services for small- to medium-sized companies.
At first, she considered becoming partners with one or two of her co-workers. She wasn't sure if she could raise the seed money she needed for the start-up costs. But, she was able to raise the capital by taking on a silent partner, her uncle who had a lot of investment capital, but didn't want to be involved in the day-to-day operations of a business now that he's retired.
One way that Sam is able to cut down on overhead is to make this a home-based business. She converted her garage into an office where she and her employees could work. Since most of the work would be done on site at her client's office, she didn't need a lot of office space.
I asked Sam if she was nervous about quitting her job to start her own business. She said that it's a big risk, but that she was looking forward to the challenge. If she fails, she said, she can always audition for American Idol. Well, I thought, I've heard Sam sing. I really hope her business takes off!
[end of story]
The title of this podcast is “Being an Entrepreneur” and that word “entrepreneur” (entrepreneur) is originally a French word that we have borrowed in English. In English, it means someone who starts a business or organizes businesses – normally, someone who is taking a risk, someone who risks some money at the business to start it.
I had lunch, according to the story, with my friend, Sam. She had quit her job to “strike out on her own.” “To strike out on your own” – that expression means to work for yourself, to not have a boss, to have your own business or your own operation. The expression “to strike out” is very different than “to strike out on your own.” “To strike out” means to fail. It comes from the baseball expression where you swing the bat three times and miss the ball – that’s called a strike out. So, “to strike out” means to fail, but “to strike out on your own” means to go into business usually, on your own.
The story says that “the start-up she launched provides technology consulting services.” A “start-up” (start-up) is a new company, a company that is just starting up or beginning. “To launch a company” means to begin a company. “I’m going to launch a new start-up” means I’m going to begin a new business. A “consulting business” is one where you work with other companies, usually to provide some knowledge or some particular service. The expression “small and medium-sized companies” – those are two adjectives we use to describe how big a company is. “Small” is, of course, a company that’s not big. “Medium-sized” means, of course, something not big, but not small. We probably wouldn’t say a “medium company.” You can say a “small company.” You can say a “big company,” but you cannot say a “medium company.” You would have to use that word “sized” – a “medium-sized” company.
The friend that I have, thought about becoming partners with one or two of her co-workers. And “to be a partner” (partners) in a business means that you share the cost and the benefit of the business. She wasn’t sure if she could raise the “seed money” she needed for the start-up costs. The expression “seed money” – (seed) “money” – two words – means that money is given to start a company and you get this money, usually, from someone else, from a bank, or from what we call a “venture capitalist.” A “venture (venture) capitalist” is someone who has a lot of money or has an organization that has a lot of money and they give that money to start new businesses. And, of course, they get a percentage of the profits of the business. The word “seed” (seed) you may know, is a word that we use in gardening or in agriculture. The seed is what you plant or put into the ground to make something grow and that’s the idea, that this is money, like a seed, that you hope will grow a successful business. Notice too, we use the verb “raise” – “to raise money.” If you’re going to “raise” money or “raise” seed money (raise), we mean you’re going to try to get money, usually from other people.
“Start-up costs” – well, you know what a start-up is, and so the “start-up costs” (costs) – those are the expenses or the things that you need to spend money on when you are beginning a business. Sam was able to raise the “capital” by taking on a “silent partner.” “Capital” (capital) is just another word here for money, money that is going to be used for a business. And notice again, we use the verb “raise” because capital is just another word for money. A “silent partner” – two words – “silent partner” is someone who wants to give money to a business, wants to be a part of the business, but doesn’t want to be someone who actually works everyday at the business. They don’t want to be involved in the day-to-day operations. When we say the “day-to-day,” we mean the everyday running or operating a company.
It turns out that Sam has an uncle who has investment capital. Again, we know what “capital” is. “Investment” is when you give money to a company or someone and you hope to get that money back plus some percentage of that money, that profit that would be made. One way that Sam was able to “cut down on overhead” was to make it a “home-based” business. “Overhead” – all one word – (overhead) – is the cost that you have to or the money you have to spend in a business that doesn’t depend on how much you produce or how much service you provide. For example, if you have to rent an office building or an office in a building, the “overhead’ would be the rent that you pay every month – the water, the electricity, the telephone bill. All of these are “overhead.” You don’t – it doesn’t matter how much money you make or how many things you make or how much work you do, you still have to pay these, what we would call “fixed costs.” They’re fixed, they don’t change. And that is what overhead is. “To cut down on overhead” – the expression “to cut down on something” means to reduce or to have less of. “I need to cut down on all the sugar that I put in my coffee.” “I need to cut down on eating too much chocolate because I love chocolate” but it’s, of course, not good for you to eat too much chocolate. So, I have to cut down.
A “home-based business” – Sam has a “home-based” – that’s “home” – “based” – is, you can guess, a business that you run or operate out of your home. You don’t rent an office anywhere. And, of course, if you can run it or operate the business from your home, you don’t have to pay extra overhead for an office. Sam decided to “convert” her garage into an office. “To convert” (convert) means to change – to change something from one thing to another thing. She’s converting her garage where she parks her car, into an office where she can work. And in American – in many houses in the United States, there’s often a separate garage where you park your car – a small little building. Sometimes, it is attached to the house. It is connected to the house. Sometimes, as in my house, where it’s a separate garage and so, people often don’t park their car in the garage. They park it on the street and they use their garage for something else like storage or in the case of my neighbor, he has a recording studio where he records music, loud music, sometimes loud music at night, but that’s his right to do that.
Anyway, enough about my neighbors. The woman converts this garage into an office, and that way, she can save on overhead. Most of the work that she does will be done on-site at her client’s office. “On-site” means at the place of business where the client -- and the client here is a customer – where the customer works. If you’re doing consulting, you often do work “on-site” – (on site) - two words – meaning you go to someone else’s company and you do it there. A “client,” as I said, is a customer.
Well, at the end of the story, I say that if Sam fails, she says she can always audition for American Idol. American Idol is a television program and there are other similar programs in other countries. In Britain, it’s called “Pop Idol.” And it’s a show where people sing – amateurs – and you vote as the audience. You call in and you vote for the person that you want to continue and they start with, I don’t know, 12 people. And then every week, someone leaves the show. It’s what we would call a “reality show” and American Idol is very popular in the United States. It’s probably one of the most popular television programs in the last three or four years. “To audition” (audition) means the same as “to try to be on the program.” “Audition” is what you do to be part of a movie or a play. An actor or actress has to go in front of the director or go in front of someone and they get five minutes or ten minutes to sing or to act, and then they decide whether they’re going to hire that person for that job. I said at the end of the story that I really hope – since Sam cannot sing – I really hope that her business “takes off.” And here, “to take off” means to be successful.
Now let’s listen to the dialogue this time at a native rate of speech.
[start of story]
I had lunch today with my friend Sam. She recently quit her job with a large company to strike out on her own. She has always been an entrepreneur in small ways, but she decided to start her own business. The start-up she launched provided technology consulting services for small- to medium-sized companies.
At first, she considered becoming partners with one or two of her co-workers. She wasn't sure if she could raise the seed money she needed for the start-up costs. But, she was able to raise the capital by taking on a silent partner, her uncle who had a lot of investment capital, but didn't want to be involved in the day-to-day operations of a business now that he's retired.
One way that Sam is able to cut down on overhead is to make this a home-based business. She converted her garage into an office where she and her employees could work. Since most of the work would be done on site at her client's office, she didn't need a lot of office space.
I asked Sam if she was nervous about quitting her job to start her own business. She said that it's a big risk, but that she was looking forward to the challenge. If she fails, she said, she can always audition for American Idol. Well, I thought, I've heard Sam sing. I really hope her business takes off!
[end of story]
The script for today’s story was provided by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. We’ll see you next time on ESL Podcast.
ESL Podcast is a production of the Center for Educational Development in Los Angeles, California. This podcast is copyright 2005. No part of this podcast may be sold or redistributed without the expressed written permission of the Center for Educational Development.
Glossary
to strike out on one's own – to do something new by oneself, without any help from someone else
* Doug’s aunt offered him a job at her company, but Doug wanted to strike out on his own and form a new company instead.
entrepreneur – someone who owns and leads a business; someone who looks for ways to earn money without help or guidance from others
* Mallory was a true entrepreneur who had tried many different business plans before starting her own successful company.
start-up – a new company that was just recently started to operate; a new business that was created recently
* The small firm is a start-up company that began offering services two months ago and does not have many workers or much money yet.
to launch – to start something, like a business
* Eduardo launched his computer repair service three years ago, and he has built it into a strong business over the last three years.
consulting – giving advice or helping other businesses learn to get the best use out of resources, like technology, money, or workers
* Sonja knew a lot about how to make a business successful and she got a consulting job with a new company.
seed money – money one needs to start a business or project
* Frederick had a strong business plan, but without seed money, he could not afford to start his company.
capital – money one has and is able to use; money one earns or collects for a certain purpose, usually related to business
* Carmella offered to help her brother raise the capital he needed by looking for people who would be willing to loan money or invest in the company.
silent partner – someone who works with one on an equal level to meet a shared business goal, but who does not make day-to-day decisions
* Domenic had a silent partner, but Domenic was the only person who made decisions for the company.
investment capital – money one owns and can spend on a business, or another plan or action, hoping to earn more money from that business
* Kaylee had saved a large amount of investment capital and decided to spend it on a promising new business.
day-to-day operations – the normal actions and choices made every day to operate or lead a business
* Walt liked making important business decisions, but he got bored with day-to-day operations, such as hiring workers and writing paychecks.
to cut down – to reduce; to make into a smaller number or amount
* The company cut down on the number of new workers it hired once business slowed.
overhead – the costs related to owning and operating a business
* Maggie barely had enough money to pay the overhead and did not make much money the first year her restaurant was open.
home-based business – a business or company that one leads from home instead of in another building or office
* The bakery was a home-based business that the owners ran from the kitchen in their own house.
to convert – to change from one thing to another; to take something that had one purpose or use and give it a new purpose or use
* Marcus converted the extra bedroom in his house into an office by taking the bed out and putting a desk, computer, and filing cabinet in it.
client – customer; someone who buys or pays money for a service
* The client was very happy with the high-quality service the company provided and promised to hire that company the next time she needed the same type of work done.
to audition – to try to get a job that others are also trying to get, usually as an actor, singer, or other type of entertainer; to compete for a chance to earn money acting, singing, or playing music
* Stephanie auditioned for the lead actress role in the movie, but someone else got the part.
to take off – to grow quickly after starting; to do very well from the start
* The small bookstore really took off and attracted many customers in a short amount of time.
Culture Note
Black Friday In the U.S., Americans celebrate the Thanksgiving holiday on the fourth Thursday of November. We refer to the Friday after Thanksgiving as “Black Friday.” Black Friday is not an official holiday, but many people look forward to it as though it is. Black Friday is the unofficial first shopping day of the Christmas and holiday season, and it’s the busiest shopping day of the entire year. “To draw” (attract; bring) people into the stores, “retailers” (sellers; stores) have very big “bargains” (discounts; good deals) that are often available one day only. Do you want a new TV for half price? Do you want a new sofa at a 30% discount? Do you want to buy the most popular toys of the season on sale? If so, you may want to get ready for Black Friday. On Black Friday, many stores open very early in the morning, some as early as 5:00 a.m. Many people stand in line and some people even “camp out” (sleep outdoors) overnight waiting for stores to open. Some larger stores have started opening their doors at 12:00 midnight on Black Friday and staying open for 24 hours. Because Black Friday is one of the busiest shopping days of the year, many people look to Black Friday as an “indicator” (something that shows what will come in the future) of how much shoppers will spend this holiday season. If sales are good on Black Friday, then business owners can be “optimistic” (feel hopeful and confident) that shoppers will spend a lot over the holiday season. If sales are not good, business owners know that they may not turn a “profit” (earn money) that important sales season.