= 0115
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 115: New Year’s Resolution.
You’re listening to English as a Second Language Podcast episode 115. I am Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Today’s podcast is going to be about making a resolution or a promise to yourself for the New Year. Let’s go!
[start of story]
This is the time of year when people make their New Year's resolutions. At the beginning of a new year, people take stock of their lives and decide to make some changes.
A lot of people want to get into shape. They vow to go to the health club and work out every day. Many people also decide to go on a diet. After overindulging at holiday meals, people feel the need to cut back and to shed some extra pounds. Many people also promise to quit smoking or drinking to live healthier lives.
Whatever resolution you make, don't forget the most important one: Promise not to have to make the same resolution next year.
[end of story]
Well, it’s that time of the year where people often make a New Year’s resolution. A “resolution” (resolution) is basically a promise that you make, usually to yourself. You say, “Well, this year I’m going to exercise everyday” or “This year, I’m going to read more books.” Whatever the idea of improvement you have, that becomes often your New Year’s resolution.
Well, in our story, it begins by saying that people make their New Year’s resolutions. And people like to “take stock” of their lives and decide to make some changes. “To take stock” – two words – “take” and “stock” (stock) – means to examine, to look at, to step back and say, “Hmm, where is my life now?” That word “stock,” of course, is also used for – in business – for finance on – “stock” is ownership – part ownership – in a company or business. There is such a thing as the “stock exchange” like the New York Stock Exchange where they buy and sell stocks. But this is a different meaning here. “To take stock” means to think about, to examine, usually some important point of your life or in this case, for the New Year.
One thing that people often make resolutions about is getting into shape. “To get into shape” (shape) means that you are going to do some exercise so that your body is as good physically as it can be. So that you can breathe easily when you run, that your muscles are strong – this is all part of “getting into shape.” And people, for example, who run a marathon – a “marathon” (marathon) is a long race that you run and people talk about getting into shape for a marathon or getting into shape just in general – which is a good idea, of course, you should try to get into shape, whatever shape you are.
People “vow” to go to the health club to work out every day. The interesting word here, “vow,” (vow) means to promise – usually it means to make a very serious promise. “I vow to find the person that took my pen this morning.” I’m making a serious promise. We often use this word in a religious context. For example, the nun – the religious nun – “took her vows” – meaning her promises. So, it can be a very serious thing to take a vow. It’s also like –sort of like – taking an oath. An “oath” (oath) is a promise that you are going to do something, or sometimes, simply that you are telling the truth.
A “health club” – two words – is the same as a gym or gymnasium. It’s usually a private company that has treadmills and weight machines – things you can do to exercise and there are lots of health clubs in the United States. Here in Los Angeles, many people like to make sure that their bodies look good because their, well, for a lot of reasons I suppose. So, there are lots of health clubs. There’s a health club just – two or three of them – within a couple of miles where I live. So, I used to be a member of a health club that’s over in a park called “Marina Del Rey” which is close to me, but now, I have a treadmill at my own house, and so, I just run on that listening to podcasts, of course. Well, people vow to go to the health club and “work out.” And to “work out” – the verb “to work out” – two words – means to exercise, to do exercises.
People also want to “go on a diet,” meaning they want to lose weight and one reason they want to lose weight is because they have gained weight by “overindulging” at holiday meals. “To indulge” (indulge) means to enjoy something. And to “overindulge” means to enjoy something too much. And usually, that is food – you overindulge, you eat too much food. This morning, I went to dim sum which is a Chinese breakfast and I ate too much. I “overindulged.” It was good though. But it was too much. People feel a need then to “cut back and shed some extra pounds.” “To cut back” – two words – the verb here means to reduce, to make less. And you can use it about food – I’m going to cut back on the number of chocolate chip cookies I eat every day, or you can use it for money – “I’m going to make cut backs.” “I’m going to cut back my expenses.” “I’m not going to spend as much.” It’s also used as a noun – “cut backs.” “The company made “cut backs” – it means they reduced their spending, their expenses.
“To shed some extra pounds” – “to shed” (shed) means to lose here – “to lose some extra pounds,” meaning weight, of course. “I’m going to lose weight.” Another expression we use is “to drop some pounds” (drop) – “to drop some pounds” – same thing, to lose weight. And of course, people want to lose weight so they are more healthy – to be more healthy you can also say, “healthier” – “healthier” (healthier).
Many people promise to quit smoking or drinking to live healthier lives. Well, of course, quitting smoking is probably a good idea if you are concerned about your health. Drinking, of course, you don’t want to drink too much. A little bit might be okay. Doctors say, I think, that if you drink just a little bit every day, it can help your heart, but I may be wrong about that so, don’t overindulge in your drinking either.
Well, now let’s listen to the dialogue this time at a native rate of speech.
[start of story]
This is the time of year when people make their New Year's resolutions. At the beginning of a new year, people take stock of their lives and decide to make some changes.
A lot of people want to get into shape. They vow to go to the health club and work out every day. Many people also decide to go on a diet. After overindulging at holiday meals, people feel the need to cut back and to shed some extra pounds. Many people also promise to quit smoking or drinking to live healthier lives.
Whatever resolution you make, don't forget the most important one: Promise not to have to make the same resolution next year.
[end of story]
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
ESL Podcast is a production of the Center for Educational Development in Los Angeles, California. This podcast is copyright 2005. No part of this podcast may be sold or redistributed without the expressed written permission of the Center for Educational Development.
Glossary
New Year's resolution – a goal one makes at the start of a new year; a choice one makes at the start of a new year to make oneself better in some way during that year
* Deandre did not spend much time with his family last year, so his New Year’s resolution is to show his family that they are important to him.
to take stock – to judge or think about the good and bad parts of something; to think about a situation or issue seriously and to think about how to act after one knows everything one can know about that situation or issue
* Annemarie took stock of the work she still needed to finish before deciding if she could go home yet or if she should stay for another couple of hours.
to get into shape – to exercise and to make one’s body look better and more athletic
* Rory wants to get into shape, so he started running and lifting weights.
to vow – to promise; to make a committment
* Kimberly was often late to meetings, but she vowed to arrive at the right time for the next one and did everything she could to keep herself from being late.
health club – a place of business where you can find exercise machines and exercise classes, and where people can go to exercise and to make their bodies healthier
* Domingo did not have any exercise machines at home, so he joined a health club and used the machines there.
to work out – to exercise; to do physical activity so that one can prepare for an athletic event, lose weight, get healthier, or look better
* Catalina began working out so that she would be able to take part in the company baseball team by the beginning of summer.
to go on a diet – to limit the foods one can eat so that one will lose weight; to start eating food that is better for one’s body, usually with the goal of losing weight.
* Dexter developed a disease after eating too many bad foods, and he needed to go on a diet to make himself healthier.
to overindulge – to take or do too much of something that one enjoys; to take more of something that one wants but does not need, such as sweets or unhealthy food
* The family overindulged in heavy, unhealthy food when they went on vacation, and returning to their normal way of eating when they got home was difficult.
to cut back – to take less of something; to lessen or reduce the amount of something without removing it completely
* Reba spent too much money last month, so she is cutting back on how much money she spends on clothes and entertainment this month.
to shed – to slowly lose something, such as weight; to remove something from oneself slowly
* Terrence got home, took off his shoes, and shed his coat before saying hello to his family.
extra pounds – body weight that one has but does not need; extra body weight that makes one unhealthy
* Susanne and Antony both gained a few extra pounds, so the two decided to start exercising together to lose the extra weight.
healthier – in a better physical condition or state; better than one was, usually either physically or mentally
* Anja had been sick for many months and wanted to be healthier soon.
to promise – to make a statement about something one plans to do seriously; to vow
* Thaddeus promised his parents that he would come home by 10:00 at night, so his parents were very angry when he came home late at 11:30 that night.
Culture Note
Times Square and New Year’s Eve
When is it time to celebrate the arrival of the new year, the largest and the most “well-publicized” (made known to the most people) celebration in the U.S. is the one that takes place in Times Square in New York City. Times Square is a large “commercial” (with businesses, stores) area where two main streets “intersect” (cross; meet): Broadway and Seventh Avenue.
Near Times Square is the Theater District, the famous theaters, which show plays and other performances. Since the theaters are located on or near Broadway, we often refer to these theaters “collectively” (together; combined) as “Broadway,” as in “Only the best actors are in plays on Broadway.”
During the Times Square New Year’s Eve celebration on the evening of December 31st, about 1 million people gather to celebrate. In addition to the “ton of” (a lot of) falling confetti, people who are gathered there will experience the Time Square ball drop. The famous ball is made with electric lights and “crystals,” pieces of what look like glass, which is why the ball is so bright and “sparkly” (sending out flashes of light, like a diamond).
The Time Ball “sits” (is located) high up over Times Square and slowly “descends” (comes down) 77 feet (23 meters) during the last minute of the year. As the large crowd “counts down” (counting from the highest number to the lowest), the ball descends and reaches the bottom at 12:00 a.m. When it does, everyone “cheers” (shout with joy) and that’s when the “confetti” (small pieces of colored paper) falls. Those who can’t or don’t want to be in Times Square on New Year’s Eve can watch it on TV.