= 0130
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 130: Allergic to Cats.
You’re listening to English as a Second Language Podcast episode 130. My name is Dr. Jeff McQuillan, your host, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Today’s podcast is about people who have problems when they are around animals – who are allergic to cats. Let’s get started.
[start of story]
When I was little, we had a family pet. His name was Jupiter and he was a kitten. I wanted a cat more than anything else, and finally, my parents gave in and said that we could have one. We went to the pound and saw dozens of cats of different breeds. We went from cage to cage until we saw a little kitten at the back of one of the cages. He looked scared, but when I picked him up, he wouldn't stop licking my hand and I knew he was the one we would bring home.
When we got Jupiter home, I played with him all day. What I noticed when I played with him was that I would sneeze a lot and I started getting hives on my arm. My nose would also be runny and my eyes would water. I tried to hide these symptoms from my mother, but she noticed them eventually and told me that I was allergic to cats! Even worse, we couldn't keep Jupiter! That was a tragic day in my young life. I thought I would never recover.
Then, a lucky thing happened. Our neighbor down the street was willing to adopt Jupiter and I was able to visit him all the time, as long as I didn't get too close. In the end, it wasn't such a terrible tragedy after all.
[end of story]
The title of this podcast is “Allergic to Cats.” “Allergic” comes from the word “allergy” (allergy) and an allergy is when your body has a negative reaction to something. Sometimes, it’s to the hair of an animal, sometimes it’s to certain kinds of plants or flowers, and what happens is often, you will start to, perhaps, cough – all of these – your nose can have a problem, you can start sneezing – all of these are possible symptoms, indications of an allergy. And “allergic” is the adjective that comes from the word “allergy.”
Well, today’s podcast is about being allergic to cats. And cats, and dogs, of course, are very common for people to have as pets. And there are many Americans that have cats, sometimes many cats. My sister has two cats. Well, in the story, we hear about how when she was a little girl, they had a family pet. And the pet’s name was Jupiter, just like the planet “Jupiter” (Jupiter), and this pet was a kitten. And a “kitten” (kitten) is a small cat. Sometimes, we’ll say “kitty” (kitty). “Kitty,” “kitten” – these are all small, usually, baby cats.
Well, the person in the story here wanted a cat, and finally, she says, her parents “gave in.” “To give in” – two words – means that, for example, your friend is saying, “Let’s go to a movie,” and you say, “No, I don’t want to go a movie.” And they keep asking and asking, and finally, you “give in” – means you say “yes” to someone who you were saying “no” to before. So the parents in this story “give in” to their daughter. And that’s how we would say it, “to give in to someone.” They give in to their daughter and get a kitten. And they go to the “pound” and see dozens of cats of different breeds. A “pound” (pound) is, of course, can be something – a way of measuring how heavy something is. I weigh a hundred and twenty pounds, for example – not really. I wish I weighed 120 pounds. But here the word “pound” is, as a noun – doesn’t mean the weight or how heavy something is. It means a place where animals who do not have an owner are kept. And most cities have a “dog pound” or an “animal pound” so if a dog is found on the street or a cat, they can be taken and put into this pound, and the idea is that someone will then come and adopt the pet. And that’s the word we would use – “to adopt a pet.” We also can adopt children, but here, we use the same verb “to adopt.” So, they go to the pound and they see cats of different breeds. A “breed” (breed) for a dog or a cat, or most, any animal, is the type of dog. So, for example, it could be a German shepherd – that would be one type or breed of dog.
They look for a cat in the pound by going from cage to cage. A “cage” (cage) is where you keep an animal so that they don’t leave or don’t escape. And they finally found a little kitten and the girl in the story picks up the kitten and he wouldn’t stop licking her hand. “To lick” (lick) means to take your tongue and put it on, usually, for example, for a cat, it would take its tongue and lick your hand. So, its tongue would touch your hand and get it wet.
Well, when they got the cat home, the girl in the story plays with him, but she notices that when she plays with him, she starts to “sneeze” (sneeze). “To sneeze” as I said before is to go (sneezes), usually because there is something bothering your nose. Well, not only did she start to sneeze but she started to get “hives” on her arm. And “hives” (hives) are like little bumps, red bumps on your skin. And again, that’s one thing that can happen if you are allergic to something. Well, the problems were just beginning. The girl says that her nose would also be “runny” and her eyes would “water.” When we say your nose is “runny” (runny) we meant that there is liquid coming out of your nose so that you have to get a handkerchief – what we would call a – probably a Kleenex – which is a type of tissue – white tissue. So, you blow your nose to clean it out. But if your nose is running, that’s what is happening. If your eyes are “watering” – just like to “water” (water) – when your eyes “water” that means that, once again, there’s liquid – it’s wet and liquid may be coming out of your eye. It’s kind of like crying but it is because of an allergy.
Well, these are all symptoms of an allergy. And a “symptom” (symptoms) – “symptoms” – a “symptom” or “symptoms” are indications, they’re signs. They are ways that you can tell if you have sickness, an illness or some problem. Here, it would be symptoms of an allergy. Sneezing, a runny nose – and notice we can use “runny” here as an adjective – “a runny nose,” watery eyes – once again, “water” becomes an adjective with a “y” at the end – “watery eyes” – these are all symptoms and what the girl finds out is that she is allergic to cats. Well, she describes this as a “tragic day in her young life.” And “tragic” (tragic) is something that’s very sad, something that is very unfortunate, something very bad happens –we say it’s “tragic.” But it’s very serious. Well, she says this was a ”tragic day” in her life. She thought she would never “recover.” “To recover” (recover) – “to recover” means to get over, to get better. So, if you are sick, when you start to feel better, you are recovering.
Well, then a lucky thing happened in the story. The neighbor, who lived nearby, or “down the street” – “down the street” here would mean close to where they were living. He was willing to adopt Jupiter and remember that verb “to adopt” (adopt) – we use with animals as well as with children. They adopted Jupiter and took him into their house and then she could go visit the cat there. She says at the end, “It wasn’t such a terrible tragedy after all.” And “tragedy” (tragedy) is the noun of “tragic.” “Tragic” is an adjective – “It was a tragic play. It was a tragic event.” And “tragedy” would be the noun. We use that word, of course, and also talking about in the theater when a play such as “Macbeth” or “Othello” or a play by one of the great Greek playwrights – ancient Greek playwrights such as Sophocles or Euripides – has these great tragedies – plays in which something very terrible happens.
Well, nothing terrible is going to happen to you. Let’s listen instead to this story again, at a native rate of speech.
[start of story]
When I was little, we had a family pet. His name was Jupiter and he was a kitten. I wanted a cat more than anything else and finally, my parents gave in and said that we could have one. We went to the pound and saw dozens of cats of different breeds. We went from cage to cage until we saw a little kitten at the back of one of the cages. He looked scared, but when I picked him up, he wouldn't stop licking my hand and I knew he was the one we would bring home.
When we got Jupiter home, I played with him all day. What I noticed when I played with him was that I would sneeze a lot and I started getting hives on my arm. My nose would also be runny and my eyes would water. I tried to hide these symptoms from my mother, but she noticed them eventually and told me that I was allergic to cats! Even worse, we couldn't keep Jupiter! That was a tragic day in my young life. I thought I would never recover.
Then, a lucky thing happened. Our neighbor down the street was willing to adopt Jupiter and I was able to visit him all the time, as long as I didn't get too close. In the end, it wasn't such a terrible tragedy after all.
[end of story]
Remember to visit our website at www.eslpod.com for the script of this podcast and more information about our other podcasts.
From Los Angeles, California , I’m Jeff McQuillan. Thanks for listening as always and we’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
kitten – a baby cat; a young cat
* Orin’s cat gave birth to six kittens.
to give in – to agree to an action or opinion after not agreeing for a long time; to agree to do an action even though one does not want to do or have something
* Yvonne did not want to travel on an airplane, but she finally gave in because her husband wanted to take a trip to another country.
pound – a place where unwanted animals can be seen and taken home as a pet; a building where unwanted animals are kept in cages until someone decides to take it home as a pet
* The stray dog did not have a home, so it was taken to the pound until a new home could be found for it.
breed – a group of animals that share more traits, behaviors, and looks with each other than they share with other animals belonging to a larger group known as a “species”
* Tobias asked what breed his brother's dog was, and found out that the dog was a golden retriever.
cage – a box made with metal bars or poles, meant to keep an animal or person inside and to stop that person or animal from running away
* Jeanine kept her pet bird inside a large cage so that it would not fly away.
to lick – for an animal to use its tongue to pet or stroke a person or other animal in showing love, affection, or thanks; for an animal to stroke with the tongue to clean, taste, or show affection
* The dog was very friendly and licked everyone who came to the house.
to sneeze – to quickly force air out of the lungs without planning to, in order to force out dust, hair, or something else that the nose, lungs, or body does not like
* Irwin sneezed after he breathed in a large amount of dust when he went up to the attic.
hives – a patch of painful, itchy, red bumps that shows up on the skin when something bothers the skin or body
* Laura was not able to eat strawberries and got hives the first time she tasted them.
runny – dripping; when mucus (a slimy liquid that protects the inside of the nose) drips out of the nose in a large amount, usually because of an illness or medical condition
* Bryant was sick with the flu and had a runny nose and a sore throat.
to water – to form drops of water or tears; for eyes to form and force out tears (a natural mixture made of salt and water) to wet dry eyes or to force out an object that should not be in the eye
* The sun was bright and made Maria’s eyes feel dry, so her eyes began to water.
symptom – a sign, behavior, or action that suggests or proves that someone has a disease or medical condition
* Mikhail has symptoms of food poisoning, including a stomachache and a fever.
allergic – when one is not able to touch, taste, eat, or be around something that most people are able to be around because one’s body gets sick or has other negative results
* Glenna was very allergic to peanuts and cannot breathe if she touched or ate any peanuts.
tragic – very sad; very unhappy
* The tragic car accident killed two people and injured two others.
down the street – on the same street or road, but at a short distance away
* The store is just down the street from Tyler’s house, so Tyler can walk to it easily.
to adopt – to take someone or something living into one’s home and give it food, a home, affection, and care
* Vivian adopted a pet rabbit and took good care of it.
Culture Note
“Kitty-Corner” and “Copycat”
Cats are very popular “pets” (animals kept by people for pleasure) among Americans, so it’s no surprise that we use a lot of “expressions” (words and phrases) that refer to cats. In fact, there are many cat-related terms commonly used in everyday conversation in American English. If you didn’t know the two terms “kitty-corner” and “copycat,” you may think they actually have something to do with cats, but they don’t.
A “kitten,” or more informally a “kitty”, is a young or baby cat. Cats of any age can sometimes be informally called “kitty cats.” The word “kitty-corner,” however, doesn’t have anything to do with baby cats. It refers to something that is located “diagonally” (on opposite corners) across from something else, usually across an “intersection,” where two streets meet. If you have a neighbor who lives across the street in front of your house and across the street to your left or right, that neighbor lives kitty-corner to you.
“Copycat” is a word used by children to refer to someone who copies someone else’s ideas or behavior, such as the way they dress or the way they speak. Adults sometimes use it jokingly to mean the same thing.
For example, if you cut your hair short and “bleached it” (made it a lighter color), and the following week, your friend cuts his hair and bleaches it, you may say, “You are a copycat!”