= 0132
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to English as a Second Language Podcast number 132: Getting Through on the Phone.
This is English as a Second Language Podcast episode 132. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this podcast, we’re going to talk about trying to reach someone or communicate with someone on the telephone. Let’s get started!
[start of story]
I have been trying to get a meeting with the CEO of Medofact to talk about a partnership between our company and theirs. But I've had a hard time trying to get through on the phone.
First, there was the phone tree. I had to go through three menus before I got the option to speak to an operator. Even after I got through, I got the run around from the receptionist.
Receptionist: Medofact Limited. How may I direct your call?
Thomas: I would like to speak to Maureen Kennedy.
Receptionist: Please hold while I connect you with Ms. Kennedy's office. (Pause)
Secretary: Maureen Kennedy's office. How may I help you?
Thomas: Good afternoon. I am Thomas Guarini calling from Livatect. I would like to set up a meeting with Ms. Kennedy.
Secretary: Will Ms Kennedy know the subject of the meeting?
Thomas: Well, I would like to speak to her about a possible partnership.
Secretary: May I put you on hold for one moment?
Thomas: Yes, certainly. (I was on hold for a long time.)
Secretary: Mr. Guarini, I'm afraid Ms. Kennedy is traveling on business the next two weeks. Would you like to call back?
Thomas: Sure, I'll check back in a couple of weeks. Thanks for your help.
Secretary: It's my pleasure. Have a nice day.
Thomas: Thanks. You too!
I guess I'll keep trying.
[end of story]
We’re talking about trying to make an appointment with someone by calling them on the telephone. The name of the podcast is “Getting Through on the Phone.” “To get through” means that you are able to, in this case, talk to the person that you want to talk to. We also use that expression “to get through” to mean to get someone to understand us. A parent, for example, might say this about their son or daughter. “I can’t get through to him” means I can’t seem to communicate with him. He doesn’t seem to understand me, but here, “to get through” just means to be able to reach someone, or talk to someone on the telephone. Well, in this case, the person is trying to get a meeting with a CEO. “To get a meeting” is the same as to make a meeting, to make an appointment for a meeting. The “CEO” is the “Chief Executive Officer” – usually the highest person in a company. The number one person in the company is often called the “Chief Executive Officer” or “CEO.”
Well, the CEO of this company is the person they’re trying to get a meeting with. And they want to talk about a “partnership” between the two companies. A “partnership” is, of course, when two people or more people come together and have some sort of agreement where they work together. Well, unfortunately, he’s having a hard time trying to get through on the phone. First, there was the “phone tree.” And a “phone tree” (tree) – like the tree that grows in the forest. The “phone tree” is when you call a company and you get a real person – a live person – you get a message and the message says, “If you want to talk to Mr. Jones, press 1,” meaning you have to press the number 1 on your telephone. Well, that’s called a “phone tree.” And he got through, according to the story – he had to go through three menus before he got the option to speak to an operator. A “menu” is each time you have a choice of things. So, for example, you call a company, and you get the phone tree. And you press number one and then you get another message saying, “If you want to talk to this person, press 1. If you want to talk to this person, press 2,” and so forth. And so, you press another number and then you get another menu. So, these are menus in the phone tree.
Well, he had to go through three of these to get the option or the opportunity – the ability – to speak to an “operator,” meaning the person who answers your call and tells you or helps you find the person you want. The “operator” in a company is the person who directs people. So, you call and you’re not sure who to talk to, the operator will find the right person for you. Well, even after he got through, he says, he got the “run around” from the receptionist. “To get the run around” – and “run around” is two words – (run) (around) – “to get the run around” means that someone is not being very helpful. They’re not giving you the information that you need, maybe because they’re lazy or maybe because they don’t have time. If you call a government office, you won’t get, sometimes, an answer. They’ll say, “Well, you have to talk to that person.” So, you call that person and they say, “No, no. You have to talk to the other person. “ So, that’s called “getting the run around” – when people don’t answer your question or don’t do what you want to do, to have them do, not give you the information that you want.
Well, this gentleman, this person, calls and the receptionist answers the phone. This is, of course, the same, in this case, as the operator. She answers the phone but with the name of the company, “Medofact Limited.” That’s not a real company. I just made that name up, invented that name. The operator says, “How may I direct your call?” That is a very common expression you’ll hear from people – form an operator in a company. “How may I direct?” means who do you want to talk to so I can find out the right person, or I can give you the number of the person you need to talk to. So, that’s called – that expression “How may I direct your call?” – means tell me who you want to talk to and then I can connect you. And “to connect someone” means that you dial that person’s number and you connect the two people together.
Well, he says he wants to speak to Maureen Kennedy and the operator says, “Please hold,” meaning please wait while I connect you. When he gets to Ms. Kennedy’s office, the secretary answers, and again, she answers by saying, “Maureen Kennedy’s office. How may I help you?” – very common way to answer the phone in a business, is to identify, to say who you are and where you are, in this case, Maureen Kennedy’s office.
Well, the gentleman, Thomas, says his name is Thomas Guarini, calling from “Livatect” – which is the name of his company – also not a real company. Notice he says, “I’m calling from,” meaning this is the company that I am representing. This is my company I am calling from. “I would like to set up a meeting with Ms. Kennedy.” The verb “to set up” (set up) – two words – means to arrange, to make an appointment – so, to get a meeting is similar to set up a meeting. “To set up a meeting” means really to schedule, to find a day and time when you can meet. Well, the secretary says, “Will Ms. Kennedy know the subject of the meeting?” meaning will she know what this meeting is going to be about. And Thomas says, “Well, I want to speak to her about a possible partnership.” The secretary then says, “May I put you on hold for one moment?” And remember, “to put someone on hold” means that you have to wait. Usually you hear music sometimes while you are waiting on the phone, or sometimes you don’t hear anything. I prefer to hear nothing because usually, the music you hear when you are waiting on the phone is really bad. Anyway, so Thomas says, “Sure. Yes, Certainly.” And that’s an expression we use a lot – “certainly” – it’s a polite way of saying, “Yes, of course.”
Well, finally the secretary comes back and says, “I’m afraid Ms. Kennedy is travelling on business.” The expression “I’m afraid” (afraid) – “I’m afraid” – we use that in front of something that - some bad news that we are going to tell someone else. So, someone comes up to you and says, “Can you give me a thousand dollars?” And you say, “I’m afraid I can’t give you any money.” I’m afraid,” meaning I’m sorry to tell you this, that I cannot give you any money. Although, you may not be sorry to tell them, but that’s a polite way of saying that you are going to give them some bad news. Well, the gentleman in the dialogue says, “Sure, I’ll call back in a couple of weeks.” The secretary asks if he could call back. “To call back” means to call again, to call on the telephone again. To “check back” means that I’m going to call and see in two weeks, or however long, whether this person is available.
Now let’s listen to the dialogue this time at a native rate of speech.
[start of story]
I have been trying to get a meeting with the CEO of Medofact to talk about a partnership between our company and theirs. But I've had a hard time trying to get through on the phone.
First, there was the phone tree. I had to go through three menus before I got the option to speak to an operator. Even after I got through, I got the run around from the receptionist.
Receptionist: Medofact Limited. How may I direct your call?
Thomas: I would like to speak to Maureen Kennedy.
Receptionist: Please hold while I connect you with Ms. Kennedy's office. (Pause)
Secretary: Maureen Kennedy's office. How may I help you?
Thomas: Good afternoon. I am Thomas Guarini calling from Livatect. I would like to set up a meeting with Ms. Kennedy.
Secretary: Will Ms Kennedy know the subject of the meeting?
Thomas: Well, I would like to speak to her about a possible partnership.
Secretary: May I put you on hold for one moment?
Thomas: Yes, certainly. (I was on hold for a long time.)
Secretary: Mr. Guarini, I'm afraid Ms. Kennedy is traveling on business the next two weeks. Would you like to call back?
Thomas: Sure, I'll check back in a couple of weeks. Thanks for your help.
Secretary: It's my pleasure. Have a nice day.
Thomas: Thanks. You too!
I guess I'll keep trying.
[end of story]
The script for today’s podcast was written by our very own Lucy Tse – Dr. Lucy Tse, and we thank her as always. Be sure to visit our website for more information and the script of today’s podcast. You can find us at www.eslpod.com.
From Los Angeles, California , I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
CEO – chief executive officer; the leader of a company or business
* The CEO made the company successful and increased the amount of money it earned each year.
partnership – joining with another person or group to do or to accomplish something; a link or connection between two people or two groups who agree to work together
* The school formed a partnership with a book publisher to provide cheap textbooks to the students.
to get through – to reach the place one wants to reach; to be able to talk to someone one wants to talk to
* After calling the doctor four times, the patient finally got through and was able to talk to him.
phone tree – a series of phone connections that a caller (someone talking on the telephone) must go through to reach the person he or she wants to talk to
* Raquel followed the phone tree for 10 minutes before she was able to talk to someone who worked for the company.
menu – a list of choices; a list of things that one may select or choose
* The menu listed many types of food that customers could choose to order.
option – a choice; one thing out of many things that someone can choose or select
* Samuel had the option of going to the party, but he chose to stay home.
operator – someone who talks to a caller (a person calling on the telephone) and guides the caller to the person the caller wants to talk to
* The operator connected Arielle with a customer service agent, who was able to answer her questions.
the run around – a group of directions, events, or statements that lead someone away from a goal or object they want to reach
* When Shane asked to talk to the store’s manager, the workers gave him the run around instead of getting the manager.
How may I direct your call? – Who do you want to talk to?; a question that someone asks to learn who the caller wants to talk to or what the caller wants to talk about
* When the man on the phone asked Roxanne, “How may I direct your call?” she told him that she wanted to speak with someone who could talk to her about the company’s product.
please hold – please wait on the telephone; a statement one makes to politely ask someone on the telephone to wait
* The receptionist needed to get the doctor, so she said to the patient on the phone, “Please hold.”
to connect (someone) with – to help someone talk with someone else on the telephone; to make the phone link necessary for someone to talk with the person they are trying reach
* The woman on the telephone was very helpful and connected Brian with the right person very quickly.
on hold – waiting on the telephone
* Judith was kept on hold for 30 minutes before someone answered her call.
to call back – to make another telephone call to the same person at a later time or day
* Matthias was too busy to talk to her on Monday, so Natalie called back on Tuesday.
to check back – to try again; to ask or call at a later time to see if someone or something will be available at that time
* Penelope was not at home, so her sister decided to check back later in the day.
Culture Note
Walking and Talking
Have you become angry when the person in front of you is walking too slowly? Have you ever thought, “Get off your phone and walk faster!”? Congratulations! You may have PAS - Pedestrian Aggressiveness Syndrome.
What is Pedestrian Aggressiveness Syndrome? A “pedestrian” is someone who is walking; “aggressiveness” is when you are very forceful in a mean or unkind way; and a “syndrome” is a type of mental disease.
PAS, also called sidewalk “rage” (anger), is when people get really mad at other people because of the way they are walking down the street, similar to “road rage” for those in cars.
The City of New York actually measured how fast different types of people walked down the streets of Manhattan, the main business district of the city, and found the following average walking speeds, from fastest to slowest:
Headphone listeners – 4.64 feet per second (fps)
Men – 4.42 fps
People going to work – 4.41 fps
People with bags – 4.27 fps
Average person – 4.27 fps
Cell phone users – 4.20 fps
Smokers – 4.17
Women – 4.10 fps
Tourists – 3.79 fps
“Large” people (tall; fat) – 3.74 fps
Over 65 years old – 3.63 fps
The city found that people tend to walk more slowly than average when smoking (2.3% slower) and talking on a cell phone (1.6% slower), while people with headphones (for example, listening to music) walk 9% faster than average. Tourists – no surprise – walk 11% slower.