= 0143
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 143: Fighting a Parking Ticket.
You’re listening to English as a Second Language Podcast episode 143. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
This podcast is about trying to get out of or fight a parking ticket. Let’s get started!
[start of dialogue]
Mindy: Hey, where are you going?
Eric: I'm going to traffic court. I got a parking ticket and I'm going to fight it.
Mindy: How much was the fine?
Eric: It was only $40. But it's not the money. It's the principle of the thing.
Mindy: Why? Weren't you parked illegally?
Eric: No, I wasn’t. The street I live on has metered parking from 9:00 AM to 6:00 PM. After 6, you can park there with a permit. Well, I parked my car at 7:30 PM and I have a permit. But, I still got a ticket.
Mindy: Did you display the permit clearly? It isn't expired, is it?
Eric: Yeah, it's clearly displayed and it's good until June 2007.
Mindy: Well, it sounds like you have a good case. Are you representing yourself or did you hire a lawyer?
Eric: I'm going there by myself. Wish me luck.
Mindy: Good luck. If the judge locks you away, I promise to visit you in jail.
Eric: Thanks a lot. I'll remember that.
[end of dialogue]
The title of this podcast is “Fighting a Parking Ticket.” A “parking ticket,” of course, is what you get when you are parked illegally – your car is parked illegally. And to “fight (fight) a ticket” means to protest and try to avoid paying the parking ticket, the fine that comes with the ticket. And that usually means talking to a judge. And the dialog begins with Eric saying that he is going to traffic court. The “court (court) system” is another name for our legal system where you have judges and there are different kinds of courts. There are criminal courts and that’s for people who have robbed someone or murdered – those crimes go to criminal court and then there is civil court. And “civil (civil) courts” are for things like lawsuits – when you hit someone’s car and they “sue” you (sue) – they “sue” you – meaning they demand money from you. Well, traffic court is a little different. Traffic court is just for dealing with problems, crimes, and fines that are related to the driving of a car and parking is part of that. So, if you have a parking ticket and you want to fight it, you would have to go to traffic court – the court that handles or the court that deals with that issue.
Well, Eric says he got a parking ticket, which we know is a fine that you get for doing something wrong. He says, “He’s going to fight it.” Mindy asks, “How much was the fine?” And the “fine” is the money that you pay to the government. Usually it’s the city government but it could be whatever local government is there. Well, the fine is the amount he pays and Eric says the fine is “only $40,” meaning he doesn’t think it’s very expensive. It’s “only $40.” He says, “But it’s not the money. It’s the principle of the thing.” “It’s the principle” (principle) of the thing – meaning it’s not the money but it’s the idea that he was right and not wrong and so, he wants to show that he was right. A “principle” is an idea – usually something that you believe in – a “principle.” There are two words in English that sound the same – “principle.” It can also be spelled (principal), and that sort of “principal” means the primary or first. So, if you said, “The principal reason why I am going is because I need money.” Well, that would be the first or most important reason – that’s “pal” and when it is spelled (ple) it’s an idea or a value or something that – some idea that you believe in. In school, the “principal” is the director or head master or leader of the school. In most American schools, this is called – this person is called the “principal” and that’s spelled (pal).
Mindy asked why he wants – Eric wants – to fight the parking ticket. She says, “Weren’t you parked illegally?” “Illegally,” of course, (illegally) – “illegally” is not legally. And Eric says, “No.” The street he lives on has “metered parking.” “Metered parking’ (metered) is a street that has, you can guess, parking meters, and parking meters are those little machines that you put money into. Here in Los Angeles, it costs maybe – depends on where you are, but most parking meters are 50 cents or a quarter for 1 hour of parking. But if you are in a very busy area, it could be a dollar or $1.50 for one hour of parking. In many American cities, parking is a big way that the local government makes money.
So, there are special police officers that are – they’re not police officers – they’re special employees of the police department that give parking tickets. And these are sometimes – well they used to be called “Meter Maids.” “Meter Maids” (maids) – because they were mostly women – a maid is another word for a woman. And a “Meter Maid” was someone – were women who went around and checked the meters – took the money out of the meters and so forth. But now, the name that we give them – the people are part of what is called “Parking Enforcement.” “Parking Enforcement” – “to enforce (enforce) a law” – usually we use that expression with the law – “to enforce a law” – means that the government or the police will punish you if you don’t follow the law. There are many laws. Not all of them are enforced, meaning the police don’t arrest people for everything they could.
Los Angeles, like many cities has many parking meters and that’s how it makes part of its money. Well, Los Angeles in particular has a very difficult – in some areas – rules and regulations for parking and they change. Different days, you can park on certain streets at different times and it can be very confusing to someone. There are sometimes three or four different signs that you have to read to figure out whether it’s okay to park there on that day at that time. Well, going back to the story.
Eric says that he lives on a street that have metered parking from 9AM in the morning to 6 PM in the afternoon. After 6 he says, “You can park on the street with a permit.” And a “permit” (permit) is something that gives you permission to park somewhere. Some streets are so busy that only if you live on that street can you park there at certain times. That’s true in many streets here in Los Angeles. Of course, everyone has a car in Los Angeles so that’s another reason why they want to limit the parking to people who live in that area. And so, they give you a permit which you put in the window of your car so that the police or the traffic or parking enforcement, rather, knows that you have permission. Eric says he parked his car with his permit but he “still got a ticket,” meaning he got a ticket nevertheless. Even though he had a permit, he still got a ticket.
Mindy says, “Did you display the permit clearly?” meaning did you put it so that they could see it. “To display” (display) means to show someone, to make sure that it can be seen. She asked if the permit was expired and when we say something has “expired” (expired) that means it is no longer any good. You can no longer use it. Eric says, “It was clearly displayed,” and that the permit “is good until June 2007.” When something “is good until” a certain date or time, we mean that it is still okay. It is still – you can still use it until that time.
Mindy says that Eric has a “good case.” A “good case” (case) means that he has a good argument, a good chance of winning. She asked if he is representing himself or is he hiring a lawyer. “To represent yourself” means that you go to the court, in front of the judge by yourself and you tell the judge directly and you are your own lawyer, you could say. But most people would hire a lawyer. And a “lawyer” is, of course, (lawyer) the person who argues your case, argues in front of the judge – tells them why you should be let free or in this case, why you should not have to pay the ticket. Eric then tells Mindy, “Wish me luck,” meaning wish that I – tell me that I have good luck or hope that I have good luck – wish me luck. Mindy says, “Good luck. And if the judge locks you away, I promise to visit you in jail.” “To lock (lock) someone away” means to put them in prison, to put them in jail. Mindy, of course, is making a little joke.
Now let’s listen to the dialogue this time at a native rate of speech.
[start of dialogue]
Mindy: Hey, where are you going?
Eric: I'm going to traffic court. I got a parking ticket and I'm going to fight it.
Mindy: How much was the fine?
Eric: It was only $40. But it's not the money. It's the principle of the thing.
Mindy: Why? Weren't you parked illegally?
Eric: No, I wasn’t. The street I live on has metered parking from 9:00 AM to 6:00 PM. After 6, you can park there with a permit. Well, I parked my car at 7:30 PM and I have a permit. But, I still got a ticket.
Mindy: Did you display the permit clearly? It isn't expired, is it?
Eric: Yeah, it's clearly displayed and it's good until June 2007.
Mindy: Well, it sounds like you have a good case. Are you representing yourself or did you hire a lawyer?
Eric: I'm going there by myself. Wish me luck.
Mindy: Good luck. If the judge locks you away, I promise to visit you in jail.
Eric: Thanks a lot. I'll remember that.
[end of dialogue]
The script for today’s podcast was written by Dr. Lucy Tse. We thank her, as always, for her work. Remember to visit our website at www.eslpod.com for more information about this podcast.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
traffic court – a government building and department where judges listen to formal disagreements about punishments given for the breaking laws that deal with cars and other motor vehicles
* Maryann had to go to traffic court to argue against a ticket she received while driving her car.
parking ticket – a piece of paper given to a driver showing a fine (money one has to pay as punishment) for not following laws related to where one can park a car or other motor vehicle
* Christopher got a parking ticket when he parked his truck on the wrong side of the street.
to fight it – to argue against something; to formally disagree with a punishment that one believes is unfair
* The teacher punished Raquel for cheating on an exam, but Raquel fought it because she was innocent.
fine – money paid as punishment for breaking or violating a law; money one has to pay because one did not following the law
* The city requires people to keep their dogs on a leash, and anyone who does not use a leash must pay a $100 fine.
principle – beliefs about right and wrong that we one uses to judge behavior
* Mario had no interest in the reward money; it was the principle of the thing that caused him to tell to police that his friend was the one who committed the crime.
illegally – unlawfully; against the law
* The law states that Samantha is not old enough to drink alcohol, but she still drinks it illegally.
metered parking – timed parking for one's car that must be paid for before leaving the car by putting money into a machine that counts the time, called a parking meter
* There is metered parking outside of the museum, but no free parking.
permit – written permission that allows a certain action to be performed without punishment
* Gabriel did not have a permit to build his house, so the city officials would not allow him to build it.
to display – to show; to make possible for anyone to see
* Natasha displays a sign in her window that says “Warning: Dog” to warn visitors about her big pet dog.
expired – no longer valid; past the date when a certain action is allowed, making that action no longer acceptable
* Alvin was upset when he learned that his coupon for a free hamburger expired and he would have to pay the regular price.
to be good until – to be valid or allowed until a certain date and time comes, at which point the action is not allowed
* The sale was good until the end of the today, but everything returns to their normal prices by tomorrow.
a good case – an argument that one can probably win; a claim that someone can prove
* Haru can prove that he was at the library Saturday afternoon, so he has a good case against the girl who claims that he was following her.
to represent oneself – to present or argue one’s own case to a judge instead of hiring a lawyer
* Naomi had enough understanding of the law and felt confident about representing herself in court.
lawyer – a legal professional who argues cases and claims for another person
* The suspect was instructed to hire a lawyer before speaking to the judge or to the police.
jail – prison; after breaking the law, a place a person is placed as punishment where he or she cannot leave
* The bank robber was caught by police and put in jail.
Culture Note
The Value of Parking Spaces
Living in a “car-crazed” (crazy about cars; very interested in cars) city like Los Angeles, it can be very “stressful” (causing worry) to find a place to park your car in the city. Most crowded, popular streets have “parking meters,” which are machines into which you must put “anywhere from” (ranging from) 50 cents to $2.00 “per” (each) hour in order to park in that space. During the busy times of the day, people looking for a parking space will sometimes follow someone they see walking toward their parked car, “in the hopes” (with the expectation) that they will be able to park in that same space when the other person leaves.
Sometimes when someone follows you to your car hoping for your “spot” (parking space), you may ask yourself, “How much will this person pay me to get my parking spot?” What if you could “auction off” (sell to the person who will give you the highest price) your parking space? Well, if you lived in New York City, you could actually do that – sell your parking space to someone.
In New York City, many of the city’s parking spaces have no parking meters. Because they are free, there are even more people trying to find an empty one to use. Thanks to a company called StreetParkNYC (New York City), you can now advertise and sell a parking spot you are going to “vacate” (leave) through a smartphone “application” (program). Using your smartphone, you tell the program the address where your car is located and the time you are going to leave your parking space. Other people looking for a parking spot can then pay StreetParkNYC $5.00 to get that address and time – only one person can buy that information, of course. The other driver then drives to that address, waits for you to leave, and gets your parking space. You get $3.00, StreetParkNYC gets $2.00, and everyone is happy.
This type of service may seem “extreme” (go too far), but in a busy city, finding a parking space may be the difference between a good and bad day!