= 1487
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 182.
This is English as a Second Language Podcast’s English Café episode 182. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. On it, you can visit our ESL Podcast Store, which has some additional premium courses in business and daily English that you will enjoy, I think. You can also download the Learning Guide for this episode, and every one of our current episodes. The Learning Guide contains lots of additional information, including a complete transcript of this episode, vocabulary words, definitions, sample sentences, cultural notes, and a short comprehension quiz on what you’re listening to now.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech – a normal speed. We’re going to listen to them and explain what they are talking about.
Today we’re going to talk about government “corruption” in the United States, or the bad things that happen when politicians try to make extra money while doing their job. And as always, we’ll answer a few of your questions. Let’s get started.
Our topic on this Café’s Ask an American segment is related to a recent news story that you might have heard about. Until very recently, Barak Obama was a “senator,” or an elected government representative for the State of Illinois in our national group of representatives, in this case, the United States Senate. When he was elected to become the next president of the United States, a replacement senator was supposed to be chosen by the “governor,” or the political leader in a state. So, if someone wins the presidency and they were a senator, well now that state needs a new senator, and normally the head of the state – the governor – appoints someone to that position. The governor of California is Arnold Schwarzenegger. The governor Illinois, at least a few months ago, was someone named Rod Blagojevich. Unfortunately, Governor Blagojevich tried to make money by selling the Senate seat or position to the person who would pay the most for it. This is a horrible example of government corruption, or what happens when people in politics try to make money while performing their job. That doesn’t mean it is uncommon, however.
We’re going to begin by listening to President Obama talking about Governor Blagojevich and government corruption in the U.S. in general. Let’s listen first. Try to understand as much as you can, and then we’ll come back and explain.
[recording]
“I think in Illinois – as is true in American politics generally – there are two views of politics. There’s a view of politics that says you go in this for sacrifice and public service, and then there’s a view of politics that says that ‘this is a business’ and you’re wheeling and dealing and ‘What’s in it for me?’”
[end of recording]
President Obama begins by saying that he thinks there are two views or perspectives or ways of looking at things in politics in Illinois and in the United States as a whole. The first view or perspective is that people go into politics, or start working in politics, for sacrifice and public service. Sacrifice is when someone decides not to do or have something that one wants, because by not doing or not having it you can help another person. For example, you might really want to buy an expensive new camera, but you might not get it as a sacrifice so that your wife can have enough money – can afford to buy a new necklace that she really wants. Of course, you should buy the necklace – right gentlemen? Right? Yes, very good!
Obama thinks that this first view of politics is about this kind of sacrifice and public service, or working to help the public, in this case, the people who live in the United States. People who are very intelligent and well educated can make a lot of money in private business, but sometimes they decide to work in public service instead, because they want to help people. They take jobs with the government even though they know that they probably could make more money if they worked somewhere else.
Then President Obama talks about the other view of politics, where the people who work in politics think of it as a business where they can make money. He says that people are wheeling and dealing. The phrase “wheeling and dealing” is used to talk about people who are involved in activities that are not very honest that make money from, often illegally or against the law, although you can also use the expression in a more general sense to talk about someone who is negotiating things. To “deal” (deal) means to negotiate something related to business or money. Wheeling and dealing implies that this person is doing lots of negotiations, and sometimes those negotiations are illegal as is the case here. It is against the law to try to sell a government office to someone.
According to President Obama, the people who are wheeling and dealing in politics are asking themselves, “What’s in it for me?” That phrase, “What’s in it for me?” means, “How will it benefit me?” or, “What will be the advantage for me of doing this?” Obviously those aren’t the kind of questions we want our politicians to be asking. We’d rather have politicians who share the other view of politics that President Obama described, where they decide to work in politics because they believe in sacrifice and public service. No one who works in politics will say, “Oh, yes. I’m in it for the money.” They will, of course, say, “Well, I’m doing it for the people.” So, it’s not always easy to tell who is of the first view (sacrifice), and who is of the second view (financial gain).
Let’s listen to President Obama speaking once more:
[recording]
“I think in Illinois – as is true in American politics generally – there are two views of politics. There’s a view of politics that says you go in this for sacrifice and public service, and then there’s a view of politics that says that ‘this is a business’ and you’re wheeling and dealing and ‘What’s in it for me?’”
[end of recording]
I want to thank President Obama for talking to us here on ESL Podcast; I know he’s a very busy guy!
The state where Obama was senator – the state of Illinois, which is in the center part of the United States in the north, what we would call the Midwest part of the U.S., has a long history of problems with corruption. The city of Chicago is in the state of Illinois; it is the largest city in the state. It is also a city famous for corruption, especially with a mayor who had been mayor for many years and who was, apparently, someone who was part of a lot of this corruption. Well, there’s still corruption in Illinois. Most people believe, however, that what Governor Blagojevich did was much worse than what we might call normal or typical corruption. Let’s listen to Justin Phillips, a professor of political science at Columbia University in New York, as he gives his explanation about what normal, if you will, corruption is like in the United States.
[recording]
“Well, corruption in American politics has typically been trading of government contracts or government benefits for, oftentimes, just simply campaign contributions. You know: ‘Here’s some money into your campaign, and in exchange, you give me and my business a particular contract.’ Or, ‘I take you to a basketball game, give you some great seats, and in exchange, you know, you get something that my client wants. Those types of exchanges are typical, what would we see when we talk about corruption in American politics.”
[end of recording]
Professor Phillips begins by saying that corruption in American politics has typically or usually been about trading government contracts or benefits for campaign contributions. Now, the verb “to trade” means to give someone something so that you can receive something from them, each person gives something.
According to Professor Phillips, corruption in the United States has often involved trading government contracts, or legal agreements about who will receive government money to do work for the government, and other benefits for campaign contributions. That is, someone gives you campaign contributions and you, the politician, give them something in return. A “campaign contribution” is money that a person, business, or organization gives to someone who is running for office, who wants to be elected for a government job. Politicians might use campaign contributions to pay for television advertisements or create their website and try to get people to vote for them. Politics is very expensive.
The professor goes on to explain how this works. One person makes a campaign contribution, or puts some money into a politician’s campaign, and in exchange expects to receive a particular government contract. The phrase “in exchange” is used to talk about trades. You do something in exchange for something else.
Then Professor Phillips gives another example of corruption. He says that someone takes a politician, for example, to a basketball game with great seats, meaning the places where you are sitting are very good – you can see the game, probably very close to where the game is being played. In exchange for taking the politician to the basketball game, the politician gives something that the person who took him wants, often what their client wants. A “client” is someone for whom you work, someone who hires you to influence a politician. This could be a lobbyist, although there are laws saying that lobbyists can’t give money or other things to politicians, but it certainly does happen.
Let’s listen to the professor’s quote one more time:
[recording]
“Well, corruption in American politics has typically been trading of government contracts or government benefits for, oftentimes, just simply campaign contributions. You know: ‘Here’s some money into your campaign, and in exchange, you give me and my business a particular contract.’ Or, ‘I take you to a basketball game, give you some great seats, and in exchange, you know, you get something that my client wants. Those types of exchanges are typical, what would we see when we talk about corruption in American politics.”
[end of recording]
Some people might argue that this should be allowed in politics; politicians should be allowed to receive gifts and favors in exchange for giving people things. However, another professor of political science, Kent Redfield, is going to explain why he believes corruption is wrong. He is, by the way, at the University of Illinois, so he must have a lot of experience!
Let’s listen to Professor Redfield, and his views on why corruption is wrong:
[recording]
“If they are benefiting personally from bribes, extortion, campaign finance contributions, then they essentially have a conflict of interest. The question is: Are they trying to pursue the public interest to do what’s best in terms of their office, or are they shaping policy in ways that will guarantee they get the most money? So this distorts public policy. That’s really what’s wrong with it, is that if citizens ultimately believe that everything’s for sale and it’s corrupt, then they have no reason to support the political system.”
[end of recording]
This quote was a little more difficult to understand; it was recorded on a telephone. You can kind of hear that, you can tell.
At the beginning, Professor Redfield talks about politicians who benefit personally from bribes, extortions, and campaign finance contributions. A “bribe” (bribe) is money that is paid illegally to someone to get that person to do something. If a police officer, for example, tries to give you a ticket for speeding, or driving too quickly and you offer to pay him or her $100 so that you don’t get a ticket, that would be a bribe. Actually, you should give him $200 – that’s the normal price for that! Don’t confuse the word “bribe” with the word “bride” (bride). A “bride” is a woman who is getting married. Some men bribe their brides, but that’s different story! “Extortion” (extortion) happens when someone tries to force someone to do something illegally, usually to give money by threatening that person, or making him or her think that you will hurt or embarrass them if you they don’t do what you’re asking them to do. For example, if you have a photograph of your neighbor kissing a woman that is not his wife, you could go to him and tell him that he must give you $500, and if he doesn’t you are going to give the photograph to his wife. That would be an example of extortion.
If a politician is benefiting personally or getting money from bribes, extortions, and campaign contributions (the expression “campaign finance contributions” means the same as “campaign contributions”), then there is what we call a conflict of interest, or a situation where you cannot do your job fairly because you have some sort of personal interest in it that prevents you from being objective. For example, let’s say you work at a company that is looking for a new computer technician, and your sister is a computer technician. She’s not the most qualified – she’s not the best person for the job, but you offer the job to her as a favor. That is a kind of conflict of interest. You can’t be objective – you can’t be fair when the person you are hiring is a sister, that’s not fair to other people who might want the job. In politics, if the politician has the opportunity to benefit directly from bribes, extortion, or campaign contributions, there’s a similar kind of conflict of interest.
Professor Redfield asks whether the politician is trying to pursue the public interest to do what’s best in terms of his or her office. To “pursue” (pursue) means to seek or to try to get something. The public interest is what is best for the general public or ordinary people. Is the politician really trying to do what is best for ordinary Americans? Or is the politician “shaping,” or influencing and creating laws in ways that will help him or her get the most money? If a politician is motivated by money, then this “distorts” public policy, or changes it in a negative way so that it no longer serves the public. It changes public policy from something that is supposed to help people into something that helps the politician make as much money as possible.
Professor Redfield ends by saying that this is really what’s wrong with politicians benefiting personally from their work. He says that if citizens believe that everything is for sale and that everything and everyone in the government is corrupt, then there’s no reason to support the political system – there’s no reason to believe in your government. This would be bad for government in the U.S. and in any country.
Let’s listen to Professor Redfield talk about all of this one more time:
[recording]
“If they are benefiting personally from bribes, extortion, campaign finance contributions, then they essentially have a conflict of interest. The question is: Are they trying to pursue the public interest to do what’s best in terms of their office, or are they shaping policy in ways that will guarantee they get the most money? So this distorts public policy. That’s really what’s wrong with it, is that if citizens ultimately believe that everything’s for sale and it’s corrupt, then they have no reason to support the political system.”
[end of recording]
Thanks to Voice of America for these audio quotes. And, of course, to President Obama for talking to us today!
Now let’s answer a few of your questions.
Our first question is from Krista (Krista) in Estonia. The question has to do with the difference between “have to” and “must.”
Both “have to” and “must” are used to indicate that something is required or very important: “Juan has to go to work early today.” “Juan must go to work early today.” Those basically mean the same thing. However, the use of “have to” is more common when we are talking about something that is necessary, something that you have decided or someone has decided for you that it is necessary to do this thing: “My boss told me I had to be at work by 9:00 in the morning.”
“Must,” although it can also the same in the sense of obligation (something that is necessary), is often used to express what we might call an inference. That is, you are making a conclusion about something. Somebody calls your home, for example, and asks for Joe, and there’s no Joe in your house. You would say, “You must have the wrong number,” meaning “I am concluding, because you are asking for Joe, that you don’t have the right telephone number because there is no Joe here.” Another example: someone comes into your office and they’re all wet, and you say, “Oh, it must be raining,” meaning “I conclude that is raining because you are wet.” Of course, the person could have just taken a shower with their clothes on, but probably it’s raining!
Adding the word “not” changes the meaning of both of these phrases. If you add the word “not,” for example, in the sentence: “Children must not go to the meeting,” you are saying that children are not permitted – they’re not allowed to go to the meeting. If you say, “Children don’t have to go to the meeting,” that means that children can go if they want to, but if they don’t want to they don’t have to.
Our next question comes from Tekmam (Tekmam) in Ethiopia. The question has to do with the difference between the question expressions “what about” and “how about.”
Both of these phrases can be used to make suggestions, and can be used in the same way. You can say, “How about going to dinner tonight?” or “What about going to dinner tonight?” Those both can mean the same thing. There is, however, a slight difference sometimes. “How about” is often used with an action, as in: “How about going for a walk?” Notice that the verb is in the “-ing” form: “going.” You don’t say, “How about go for a walk?” you say, “How about going for a walk?” This means “What do you think about going for a walk?”
“What about” is often used when someone is asking for a response – an answer. For example, you are looking at clothes in a store and you ask your friend, “What about the blue shirt?” This is saying that you are asking for that person’s opinion – their suggestions.
Finally, we sometimes use these expressions in asking about the status or the situation of someone. If someone says, “I know that Miguel is going. How about Pete?” or “What about Pete?” that means is Pete going as well.
Finally, Edoardo (Edoaro), in Italy, wants to know the difference between “worthy” and “necessary.”
Something that is “necessary” is something that is required to be done – has to be done, or something that is needed: “Is it necessary to fix the roof my house – the top of my house because I have water coming into my house?” Yes, normally!
“Worthy” (worthy) means deserving attention or respect: “Which story do you think is worthy of the top prize in our competition?” You might also say, “We will be giving money to several worthy causes,” “worthy” meaning they are good, they are deserving, they should get this money. “Worthy” doesn’t mean “necessary,” it’s more about the quality of that thing. “Worthy” can also mean someone who is qualified, someone who has skill. A “worthy opponent” is someone you are competing against who is qualified and has skill.
If you think you have a worthy question for us here on ESL Podcast, email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I am Jeff McQuillan. I thank you for listening. Come back next time and listen to us on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2009, by the Center for Educational Development.
Glossary
public service – related to government work that helps ordinary people
* Few lawyers choose to work in public service because they know they can make a lot more money in the private sector.
wheeling and dealing – money-making activities that are sometimes not honest and may be illegal
* After years of wheeling and dealing and making millions of dollars, the man was finally caught and put in jail.
to trade – to give someone something so that one can receive something else
* Cyril traded his new bicycle for Diane’s videogame.
campaign contribution – money that a person, business, or organization gives to someone who is running for office to help him or her be elected for a government job
* What percentage of the president's campaign contributions came from individuals versus corporations?
in exchange – the way that one person gives something and another person receives something in a trade
* Becca agreed to give Harold one free piano lesson each week in exchange for his help mowing the grass in her yard.
bribe – money that is paid illegally to someone to get that person to do something
* If a city employee asks us to pay a bribe to process your application, we should report it to the manager.
extortion – when someone tries to force another person to do something illegally, usually to give one money by threatening that person
* The man was arrested for extortion when he threatened to hurt the child if her parents didn’t give him money.
conflict of interest – a situation where one cannot do one's job fairly because one has a personal interest in it
* It would be a conflict of interest for Noemi to accept the job because her mother is on the board of directors.
to pursue – to seek or to try to get something
* Why did you decide to pursue a degree in sociology?
public interest – what is best for the general public or ordinary people in a particular country; the wishes and desires of ordinary people
* Spending money on better education and healthcare is in the public interest.
to shape – to influence the way that something is made, formed, or created
* Her early family life shaped her religious beliefs.
to distort – to change something in a negative way so that it is no longer completely correct or true
* The reporter distorted the truth, changing what the interviewee said when she wrote the article.
have to – used to indicate that something is required or very important, especially for something that is necessary
* This type of plant has to be in direct sunlight to survive.
must – used to indicate that something is required or very important
* If you want to be considered for the job, you must include a list of three references with your application.
what about – used to make suggestions, especially when someone has asked for one’s opinion about a choice
* What about Thai food for dinner tonight?
how about – used to make suggestions, especially when one is suggesting an action
* How about eating out at a restaurant tonight? I don’t feel like cooking.
worthy – deserving attention or respect; having or showing qualities/characteristics that are deserving of attention; good enough
* That woman criticizes all her son’s girlfriends because she doesn’t think anyone is worthy of him.
necessary – required to be done; needed
* I don’t think it’s necessary for you to send her a birthday gift. Just a card will be enough.
What Insiders Know
Payola
In the United States, “record companies” (companies that work with artists and musicians to produce and sell music) sometimes pay radio stations to “broadcast” (put something on the radio so that it is heard by other people) their music. In most cases, this is illegal and it is called “payola,” which is a combination of the words “pay” and “Victrola” (one of the first radios). Payola is really a bribe to get a radio station to broadcast a certain type of “programming” (what is heard on the radio).
It can be legal for radio stations to accept money in exchange for playing a song, but they have to “disclose” (tell the full truth) this to their listeners by stating that the song is being played as part of its “sponsored” (paid for by a company or person) “airtime” (time on a radio station). If the radio station doesn’t do this, but accepts the money and plays a song anyway, then it is “engaging in” (involved in) illegal payola, which is a “federal” (national) crime.
Payola “matters” (is important) because most radio stations tell their listeners that they play the most popular songs, songs that have been “requested” (asked for) by listeners who call or email a station. By playing a song because a record company is paying money instead fools people into believing that a song is popular with other people when it is not.
It is also true that, in general, the more often people hear a song, the more popular it is. Therefore, if a song is played on the radio many times, more people might decide to buy that “album” (a collection of music sold on a single CD, tape, or record), which makes money for the record company and for the artist. Another problem with Payola is that it makes it more difficult for new, inexperienced artists who don’t have a lot of money to get their songs heard on the radio. They don’t have as much money to buy airtime as older, more experienced musicians do.