= 1504
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 199.
This is English as a Second Language Podcast’s English Café episode 199. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog.
On this Café, we’re going to talk about a very unusual but very popular movie, at least a few years ago, called The Rocky Horror Picture Show. We’re also going to talk about the tradition of civil disobedience and nonviolent protest in the United States, in particular. We’re going to talk about Martin Luther King and other examples of nonviolent protest against laws that you do not agree with or political situations that you oppose. We’ll also answer a few of your questions. Let’s get started.
We start this episode talking about The Rocky Horror Picture Show. This is a British movie that was made back in 1975 that became very well known and popular among Americans, at least Americans of my generation. I was in high school during the late 1970s and early 1980s when this movie was released and when it began to become popular, especially in the 1980s. The movie is actually a musical, which is a play or a movie where the actors spend a lot of time singing and dancing. There are other famous musicals you may know about, such as The Phantom of the Opera or a very famous musical here in the United States, Oklahoma.
The Rocky Horror Picture Show is also, in addition to being a musical, a parody. A “parody” (parody) is something that copies something else, but in a funny way. The Rocky Horror Picture Show is a parody of horror films and science fiction films. Horror films are films that have a lot of violence, films that try to scare you. Science fiction films are those that talk about what happens, usually, in another planet – out in space, we would say. A movie like Star Wars or Star Trek are examples of science fiction films. The Rocky Horror Picture Show takes many of the elements (many of the things) from horror and science fiction films and makes them funny, so that you laugh.
The Rocky Horror Picture Show is often called a cult film or sometimes a cult classic. A “cult” (cult) is normally a group of people who share certain beliefs (who believe in the same things) that are very different from the rest of society. Cults can often try to influence their members in such a way that many people think is harmful (things that will hurt the person). Well, here, we’re talking about cult films, and this doesn’t really have anything to do with beliefs or religion. A cult film is a movie that has many people interested in it, much more so than normal movies, and usually these people are very loyal; they will go to the movie many different times. The Rocky Horror Picture Show is a cult film because there are large groups of people that are fascinated by it, who like it very much. It’s also a cult film because, although it’s popular with a certain group of people, it was never popular with the average audience. Most people the United States have not seen The Rocky Horror Picture Show, but there are some people who are fascinated by the movie, and that makes it a cult film. We might say the movie has a “cult following,” that is, people who like to go see the movie.
The Rocky Horror Picture Show is a popular “midnight movie,” that is, it’s a movie that the theaters will show at 12 a.m. One theater in Milwaukee has shown The Rocky Horror Picture Show as a midnight movie every Saturday – every Saturday at midnight since 1978, which is more than 30 years! I don’t know what’s more amazing – the fact that the theater has shown this same movie so many times, or that there are people who still come to see it, many of them each week. Now, you might be asking well, why would somebody goes see this movie over and over and over again, and I have to say that when I was in college in the 1980s there were a couple of theaters that had The Rocky Horror Picture Show every weekend.
Well, the reason is that when The Rocky Horror Picture Show is shown in movie theaters, many people come to see it, but they also participate in the movie. They actually stand up in the front and act out the movie as they are watching it. Many people dress in the clothes that look like the “costumes,” or the special clothing that the actors wear in the movie. Audience members also shout certain responses; they answer back things that the actors ask or are saying. They also throw things like hot dogs and water and toilet paper at certain scenes in the movie. For example, when it rains in the movie, many of the viewers use “squirt guns,” or little plastic toy guns that are used to shoot water at people; usually you find these with young children. Or, for example, when an actor says, “a toast,” which is a speech given at a special event, people in the audience will throw pieces of toast. “Toast” has two meanings here: one is a special speech you give to honor a certain occasion; “toast” can also be a thin piece of cooked bread. It’s all very silly; it’s all very, comical. People also sing the songs when they are being sung in the movie. So, it’s not a typical movie experience; it’s something very difficult to describe. It’s almost as though the people who go there are trying to be part of the movie, but also, just trying to have fun with the movie. The movie is not very good, and that’s one of the reasons why it’s so easy to make fun of it. It’s also a movie that has a lot of crazy things that happen.
The title, Rocky Horror Picture Show, is a little unusual. A “picture show” is an old expression that means a movie. Rocky Horror is actually a name of one of the characters in the mother, so The Rocky Horror Picture Show is the Rocky Horror movie, a movie about this character.
The Rocky Horror Picture Show is actually the longest running movie; that is, the movie that has been in the regular theaters, not just on cassette tape or DVD, in history of movies. So, it’s quite an amazing accomplishment for the film. The film is known internationally, you may even know it in your own country or in your own language.
The second topic today is quite different; we’re going to talk about the ideas, popular in American history and other countries, of civil disobedience and nonviolent protest.
“Civil” (civil) refers to the government or to the laws of a country. “To disobey (someone)” is not to do what they tell you to do; “to obey” means to what someone tells you to do – orders you to do. “To disobey” means to say I’m not going to do that. “Disobedience” is the noun that comes from the verb “to disobey,” so “civil disobedience” (we put the two words together) means not doing what the government says you should do.
The expression “civil disobedience” was actually one that goes back a long time in American history, but it was made most popular by a writer – a very famous American writer in the 19th century named Henry David Thoreau. Thoreau wrote a book in 1849 called Civil Disobedience, and in this book he argued that when there are laws that are “unjust,” that you believe are wrong, and that this is a very serious wrong – it’s a very serious matter, then you, in order to oppose this law, can practice civil disobedience.
Normally, if you don’t like a law you try to get it changed, but some people try to change the laws, or really, change public opinion about the laws by doing acts of civil disobedience. In the case of Thoreau, he didn’t like the laws about slavery or the participation of the United States in a war against Mexico, while we call here in the U.S. the Mexican-American War. So, he suggested that people stop paying their taxes. Now, it’s illegal to stop paying your taxes, but that’s part of civil disobedience, to do something illegal in order to stop what you think is an unjust or immoral law.
Perhaps most famous modern cases of civil disobedience in U.S. history would be related to the civil rights movement of the 1950s and 60s. “Civil rights,” in this case, refer to the rights of African Americans (of blacks) to have the same laws for them as for those who are not black (for whites). There was, as you probably know, a lot of discrimination against blacks in the 1950s and 60s; there is still that discrimination, but it was much more serious back then and it was part of the law. So, some people decided that they would break these laws, that they would practice civil disobedience to stop them.
The most famous case of this is a woman by the name of Rosa Parks, who when getting on a bus in Montgomery, Alabama, where she lived (Alabama is in the southeastern part of the U.S.). She refused to move to the part of the bus that was supposed to be for black people; she sat in the part of the bus that was reserved for whites. This was a common practice, what we call “segregation,” or dividing people up based on their, in this case, race. Rosa Parks said, “No, I’m not going sit in a different part of the bus,” it was usually the back of the bus, and she was arrested. This is an act of civil disobedience; she broke the law because she thought it was wrong.
What followed then was in major movement in Montgomery to have these laws changed. There was what is called the Montgomery Bus Boycott. “To boycott” means to not buy a certain thing or to not participate in something, usually buying some product or using some service. In this case, the boycott was against the Montgomery bus system; African Americans decided they weren’t going to use the bus. This caused problems because the city needed the money from the passengers – from the people on the bus to pay for it. The law was challenged, and eventually the courts in the United States (the legal authorities) decided the law was against the Constitution and they had to change the law.
This is an example of civil disobedience. There have been other examples; people who protested, for example, the Vietnam War sometimes engaged in acts of civil disobedience, and many other political causes have used civil disobedience, usually to get public attention – to get people to realize that this is a problem.
Another form of protest – and civil disobedience can be part of this larger category – is nonviolent protest. “To protest” means to say that something is wrong, usually to say it publicly – to go into the street, to carry signs, to go on a “march,” that is, where a bunch of people walk together and let people know that there is a problem with some issue or that they disagree with something that the government is doing.
The most famous person in the U.S. that is connected to nonviolent protest is Martin Luther King, the leader of the civil rights movement in the 1950s and 60s. Martin Luther King famously organized many protests that were not violent; they didn’t try to hit the police or cause injury or harm to another person, but they did indicate that they thought these laws were wrong. Martin Luther King’s famous March on Washington is an example, in the early 1960s, of nonviolent protest.
So we have civil disobedience, which is disobeying a law you think is wrong, and we have nonviolent protest, which is not necessarily breaking a law, but letting people know that you don’t agree with this law.
There have been, of course, many cases of nonviolent protest across the world; the most famous was that protest that was led by Gandhi in India (the country of India). There have been many others. Many times, for example, when there’s an election a country and government doesn’t respect the vote – they decide to change the vote and deny people the right to have their votes counted, this is, many times, the cause of nonviolent protest; people say that the vote is fraudulent. “Fraudulent” means that it is not correct, that someone has cheated, that someone has done something wrong.
Many times, even though these protests are nonviolent, sometimes the government tries to “crack down” on protesters; it tries to repress their demonstrations. “To crack down” means to use violence, usually, to say you can no longer do this. “Repression” is when the government denies the citizens their basic rights, in this case, the right to have your vote counted, and it is a common reaction among governments who are trying to keep themselves in power. We might also say that they “suppress” the demonstrations. Once again, this means to use force to stop someone from demonstrated – to stop someone from disagreeing with you.
That, then, is a little information about civil disobedience and nonviolent protest in the U.S., as well as some general information, some general vocabulary used to describe that in other countries as well.
Now let’s answer a few of your questions.
Our first question comes from Alexander (Alexander) in Russia. Alexander wants to know the difference between the words “evening” and “night.” When do you say “evening” and when do you say “night”?
Both “evening” and “night” refer to time usually after five or six p.m. until the time that you go to bed, maybe 10-11p.m., perhaps even midnight. You can use either “evening” or “night” to talk about that. “Night” can also be used to describe the time between when you go to bed and the following morning, when the sun rises again at six or seven o’clock in the morning. “Nighttime” can refer to any time when there is no sun in the sky, so that’s why it is a little broader usage than the word “evening,” which usually refers to the time between five or six o’clock and the time that you go to bed.
As I say, you can use both of these terms however; you may ask someone, “What did you do Saturday night?” – what did you do Saturday evening? It really means the same thing. Some people say, “Well, I had dinner in the evening, and then later that night we went out dancing.” So you can use either term, and they mean really the same thing.
However, when you’re talking about after bedtime, after the time you would normally go to bed, then we would just use the word “night.” I would say that “evening” is a little more formal; nowadays if someone says “evening,” it’s a little more formal than “night,” but the differences are small.
You should also be aware that you can say “good evening” or “good night” to someone, but there are slight differences between them. “Good night” is usually when somebody is going to bed; you know they’re going to sleep. “Good evening” would be something that someone would say to you, for example, in a store; you go to a store at seven o’clock in the evening (seven o’clock at night), and the person working at the store may thank you and say, “Have a good evening,” or “Good evening,” simply. To notice that we say “in the evening” and “at night,” different prepositions for those two.
The next question comes from Andrzej (Andrzej) from Lithuanian. The question has to do with the word “starring.” For example, you’re watching a television show, and it may say this show stars (or starring) Jennifer Aniston in Friends, or George Clooney in the TV show ER. So “to star” means to be one of the main actors in a play, a film, or a television show. “Starring” is just the gerund, the present participle – the “-ing” form – of the verb “to star.”
The word is used as a verb, but it comes from the noun “star.” A “star” means someone who is very popular and well known in their profession. For example we could say, “Tom Cruise is a movie star.” There, “star” is a noun; it means somebody who is very famous. When you use it has a verb, however, it refers to someone who is acting in a play, a film, or a television show. As a noun, there can be stars, for example, in basketball or baseball. Or even, you can use the term to talk about someone who’s very well known in a particular field or area. For example, Noam Chomsky is a star in the study of linguistics; if you study linguistics you probably have heard of this famous professor.
We have another expression, also, which is “rising star.” If someone says, “She’s a rising star,” they mean that this person is just starting out in their field – just starting out in their job, but that they will one day be famous – they will one day be one of the best people in their job. For example, an actress who acts in her first movie and does a good job might be called a “rising star,” someone who will become famous soon because of their talent.
Finally, Leslie (Leslie) in China wants to know the meaning of the words “force,” “enforce,” and “reinforce.”
“To force” (force) means to, usually, make someone do something, to make something happen, often by using violence or threats, but not always. “To force” means to compel, to make someone or something do something. “The thief forced his way into the house,” he used violence to get into the house. Someone may say to you, “I can’t force you to take this job.” “To force,” there, means, again, use violence or use some sort of threat to make someone – to compel someone to do something.
“To enforce” (enforce) means to make others follow the rules or the laws, using your strength to make sure that other people do what the law or the rules say. “The police enforce the laws.” They go around and make sure that you are following the driving laws and other laws.
Finally, “to reinforce” (reinforce) means to make something stronger, to build something that has been, perhaps, weakened somehow. After a major earthquake here in Southern California back in 1994, when I first moved here, the earthquake caused many of the bridges for the freeways to collapse; that is, they fell down. So they had to go around and build new bridges, but they also reinforced the other bridges that didn’t fall; they made them stronger so that next time if there’s an earthquake – and there will be one again here in Southern California, there always is – next time the bridges – the reinforced bridges won’t fall down – at least we hope!
I can’t force you to email us with your questions and comments, but if you’d like to, you can by sending an email to eslpod@eslpod.com. We don’t have the opportunity to answer all of your questions, but we’ll do the best we can.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2009 by the Center for Educational Development.
Glossary
musical – a play or movie in which the actors spend a lot of time singing and dancing
* Siryah’s favorite musical is The Sound of Music and she knows every song from the film.
parody – something that copies something else in a funny way
* The song “Eat It” is a parody of Michael Jackson’s song “Beat It.”
cult film – a movie that has a very devoted, but small group of fans
* Some of the best cult films were made with very small budgets.
costume – special clothing that actors and other performers wear during a performance
* Jack wore a costume to play the role of Santa Claus at Christmas time.
squirt gun – a plastic toy gun used to shoot water at other people and things
* The kids ran around the backyard chasing each other trying to hit each other with water from their squirt guns.
fraudulent – accomplishing something by lying or doing something dishonest; getting something by using or doing something that does not follow the rules or the law
* I just got my credit card bill and found several fraudulent charges on it.
demonstration – a public march to show one’s political views; a meeting to show that one is against something
* Over the weekend, there was a demonstration in front of the pet store by people who didn’t like the way the store treated the animals it tries to sell.
march – an organized walk along public roads, often to show that one supports or is against something
* The citizens organized a march from the hospital to city hall to protest poor healthcare.
crack down – to take serious action against something; to use a lot of power or force to make sure people follow the rules
* The company will be cracking down starting next week and everyone is expected to be at their desks working by 8:30 a.m.
nonviolent – without violence; without using physical force to hurt, damage, or kill someone or something
* This group of prisoners is considered nonviolent and can work outside of the prison walls.
repression – using force to control people; keeping people from doing or saying certain things by using force
* We saw more repression under this leader than any other leader in history.
civil – related to ordinary people and their concerns; related to the citizens of a country
* Is this a civil airport or a military one?
disobedience – not agreeing to follow the rules; failure to do what people with authority tell one to do
* Her parents didn’t allow any disobedience in their home and punished her harshly for breaking any of their rules.
evening – the period of time between about 5:00 p.m. to bedtime
* In the evenings after dinner, Julian likes to watch TV or read.
night – the period of time between about 5:00 p.m. until bedtime; the period of time between bedtime and morning.
* We heard a loud, frightening noise in the middle of the night.
starring – indicating the main actors in a play, film, or television show
* The play is starring two actors who used to act in films.
to force – to make someone or something do something; to make something happen by the use of strength or violence
* The robbers forced the bank clerks to give them all of the money.
to enforce – to make others follow the rules or laws; to cause something to happen by using one’s power or strength
* To enforce the no-talking rules during the test, the teacher walked around the room and watched the students carefully for the entire hour.
to reinforce – to make something stronger; to make something strong again that has been weakened
* If we don’t want water to flood our houses, we need to reinforce the old walls around the river so that it doesn’t overflow when it rains.
What Insiders Know
Midnight Bowling
Bowling is a game and a sport in which players try to score points by rolling a very heavy ball (the bowling ball) along a flat surface to try to make objects, called “pins,” fall down. Generally, the more pins one knocks down, the more points one scores. The only special equipment one needs to bowl is a bowling ball and bowling shoes, both of which can be “rented” (borrowed for a short time for an amount of money) at the “bowling alley,” where the game or sport is played.
Bowling was probably more popular 30, 40, or 50 years ago. Many communities had bowling “leagues” (groups of teams) that played each other over a period of time to try to be the best team. Workplaces, churches, and social groups had bowling leagues, and it was a way to socialize with friends and other people in the community.
To attract younger players, many bowling alleys have something called “midnight bowl” or “midnight bowling.” It does not necessarily begin at “midnight” (12:00 a.m.), but it does take place later in the evening, often after 9:00 p.m., when families and children don’t typically visit the bowling alley.
There are several things that “distinguish” it (make it different) from normal bowling. Many bowling alleys try to make the place more fun and exciting by making it feel like a “nightclub” (place where adults go to drink alcohol and dance). Bowling alleys often play loud, popular music, too. To give the place a more “intimate” (private; less public) feel, the bowling alleys also turn down the “glaring” (very bright) lights, sometimes even adding colored or “flashing” (turning on and off quickly) lights. The bowling alley may also serve alcoholic drinks so that people can drink while they bowl. Finally, some places with midnight bowling may also have a “deejay,” a person who plays the music and talks to the customers to get the crowd excited and to make the place “come alive” (become fun and exciting).