= 1471
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 166.
This is English as a Second Language Podcast’s English Café episode 166. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8 to 10 page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in daily and business English, as well as our ESL Podcast Blog, where several times a week we provide even more help in improving your English.
On this Café, we’re going to talk about a very famous legal decision in the United States known as Brown vs. the Board of Education. It’s a legal decision by the highest court, the Supreme Court in the United States that most Americans are familiar with. We’ll talk about what it is and why it’s famous. Then we’ll continue talking about schools, focusing on yearbooks and some of the things that go into yearbooks. As always, we’ll answer a few of your questions as well. Let’s get started.
In this Café, we’ll begin by talking about a famous court case called Brown vs. the Board of Education. Sometimes people will just call it the Brown Decision or Brown v. the Board of Education. A “case” is a legal decision made by a court, a place where there is a judge or judges who decide whether people have done things against the law. Court cases are usually referred to by the names of the “parties,” or the people or organizations on each side of the case. We use the word “versus,” which means “against” and is abbreviated as vs. between the two names. Sometimes we just use a “v”: Brown v. the Board of Education or Brown vs. the Board of Education. I’ve been saying “versus the Board of Education,” usually when you see it written it will just say “Brown v.” or “Brown versus Board of Education.” A “Board of Education” is a group of people, usually elected, who are responsible for running the schools in a given city or area. So, the court case Brown v. Board of Education was between a person whose last name was Brown and a government organization called the Board of Education. In this case, the Board of Education in the city of Topeka, which is in the state of Kansas, which is in the central part of the United States.
Brown vs. Board of Education was what we sometimes call a “landmark decision,” or an extremely important decision of the Supreme Court, which, as I mentioned earlier, is the highest or most powerful court in the United States. Before Brown v. Board of Education, many states had separate schools for white students and black students, or African American students. These states didn’t want to have white and black students studying together in the same school. This was an “extreme,” or very strong form of racism, but the states argued that the schools were “equal,” or the same in every other way. The only difference was the color of the skin of the students. In reality, in fact however, many of the schools for black students were “inferior,” or not as good as the schools for white students.
In 1954, however, all of this changed when the Supreme Court “ruled,” or made a legal decision (we often sometimes just say “decided”) that “separate educational facilities” – places where you have education taking place: schools – “separate educational facilities are inherently (or by their very nature) unequal.” Something that is “inherently” means that it’s the very definition of what this thing is; it could not be any other way. The court said that separate but equal – separate schools but equal in other ways was not possible. This decision was seen as an important “victory,” or win for the civil rights movement in the United States. The civil rights movement refers to the people and organizations that fought for everyone to have equal rights, and continues to fight for those rights in the U.S.
The court case began when some black parents tried to enroll their children in a white school. To “enroll” (enroll) means to register so that you can attend a particular school or university. The parents lived in homes that were very close to a white school, but their children were being forced to go to a black school that was much further away. So they “filed,” or started a “lawsuit,” or a court case to fight against the idea that there could be separate but equal schools.
Once the Supreme Court ruled in favor of or in agreement with the parents, it was still very difficult to desegregate the schools. “Segregation,” means separating things, in this case by race or skin color. In a segregated society, whites and blacks rode in different parts of the bus, used different restrooms or bathrooms, and went to different schools. To “desegregate,” then, means to end segregation, to end the separation and let black and whites do the same things and go to the same schools and places.
The desegregation of American schools was very difficult and there was a lot of “resistance” (opposition) from people who didn’t want to cooperate because they thought desegregation was wrong. The State of Virginia started to close schools because it didn’t want to desegregate them. People in that state thought that it would be better to have no schools at all than to have desegregated schools.
At Little Rock High School in the state of Arkansas, which is next to the state of Kansas in the central part of the U.S., the “governor,” or the man who had political control of the state (the leader of the state) ordered the National Guard to “prevent,” or block, black students from entering a school, not letting them enroll in the high school. The National Guard is like the U.S. military, but made up of people from a single state. When that happened, the U.S. president at that time, Dwight Eisenhower, sent part of the U.S. Army to the same school to make sure that those black students were allowed to enroll (were allowed to attend). As you can imagine, this was an extremely difficult situation for these students. The first black students at desegregated high schools faced a lot of hatred and anger as they studied there.
Today, all American schools are legally desegregated. However, there are still many schools that are mostly (or all) white or mostly (or all) black, but that’s because these are schools in areas where the population is mostly white or black, and not because people are not allowed legally to study there. However, the situation is, in some ways, the same: some schools have only or mostly black students, others have only or mostly white students. Brown v. Board of Education, however, was a major, important change in American history; it helped continued the civil rights movement that began after World War II and continued on through the 60s and 70s.
When I was growing up in the 1970s desegregation was still an issue, especially in the city of Boston in the state of Massachusetts, which is located in the northeastern part of the U.S. There were still problems with desegregation. Many of these had to do with the fact that the school district – the schools were “busing” children – were putting children on buses to go from their local school to another school in order to keep the percentage of black and white students more balanced. Many parents were against this, and this policy was eventually changed in many cities.
Speaking of schools, let’s talk about something that is found in almost every American high school, a yearbook. A “yearbook” is a special book that is made at the end of every school year in many schools, but mostly in high schools. A yearbook has many different photographs and information about what happened during that year and who the students in that school were. These books are usually bought by students as “keepsakes,” or things that will help them remember what high school was like long after they had graduated. I still have my high school yearbooks, four of them. In fact, when I was in high school, my final year, or senior year, I was the editor of our yearbook; I was the person in charge of putting the yearbook together. I’m not sure if I did a good job, you’ll have to ask my fellow students!
Yearbooks have many pages that are filled with photographs of the students. These pictures are taken by professional photographers. Usually, they come into the school on a particular day in the fall – in September, October, or November – and they take everyone’s picture. This is usually known as “picture day.” On that day, students wait in line and sit down and have their picture taken one at a time. The students and their parents can then buy extra copies of the photograph if they want to. Even if they don’t buy a photo, the picture will appear in the yearbook, with your name underneath.
There are many other photos in yearbooks. Throughout the year, the students on the yearbook staff – in some places, they simply say “on yearbook” – the students who are putting the yearbook together take photographs at important events like basketball games, baseball games, hockey games, dances, musical and theater performances, holidays performances, and so forth. In some schools, there is actually a special class that you can take that is responsible for the yearbook. In smaller schools, like the one I went to, it was a club; it was something you did after school, not during school.
A yearbook has sections for many different things. It has a sports section, an academics section, usually a music and theater section. There’s often a section for clubs – pictures of everyone who’s in that club, what we would call a “group picture.” Often the popular kids in the school appear in many different photographs because they are involved in different things. I think in the yearbook that I was in charge of (that I edited) I made sure that I appeared more than any other student. Well, I was the editor, right? I’m just kidding; I didn’t really do that – or maybe I did!
During the year, students vote on which of their “peers,” or fellow students are the best at something, those who are most likely to do something. Students vote on things like who is the best-dressed student. This is not something we did in my high school because we all wore the same school uniform (the same clothing). Some schools vote on which student is the funniest or has the best sense of humor. A very common vote is to vote who is most likely to succeed, who is going to be the most successful in life. Some students also like to vote the most likely to go to “jail,” or prison, but that usually isn’t very nice and it is not part of most yearbooks; certainly not the yearbook I was in. I think I was voted the best student – or maybe I was voted the worst student, I can’t remember now!
The yearbooks are usually printed and “distributed,” or given to students who bought them the month before they graduate, usually four to six weeks before they leave school. The common custom – the common practice is for students to sign each other’s books, meaning they write their name and usually a short message to this student. So, you give them to your friends, people in your class, and you say, “Will you sign my yearbook?” – will you put your name on one of the blank pieces of paper in the yearbook and perhaps a short message? These are typically very common messages, things like: “Hey, Lucy, we had a great year in social studies class, didn’t we? See you next year! Have a good summer!” Kids are not particularly creative in their messages!
Years later, it is sort of fun to look at your old yearbook and remember who your friends were and what things you liked to do. It’s also interesting to look at the “hairdos,” or the way that people did their hair and the way that they dressed, because, of course, things change over time – fashion changes. Many of the things that we thought were cool or interesting now make us laugh.
Another fun thing about yearbooks is that if you went to school with someone who becomes famous later, you might have their autograph in your yearbook. An “autograph” is usually the signature of a famous person, a singer or an actor – a podcaster. Some people will even buy autographs or pictures that have autographs on them. You might even be able to sell an autograph in your yearbook, depending on how famous your former classmates have become! Unfortunately, I don’t think anyone in my class became very famous.
Now let’s answer a few of your questions.
Our first question comes from Aziz (Aziz), originally from Saudi Arabia, now studying in England. His question has to do with the use of the word “indeed” (indeed).
“Indeed” can mean “in fact,” “actually,” or “as a matter of fact.” These are all possible meanings of “indeed.” We can use “indeed” to emphasize the meaning of a statement (something that we say). If someone says, “Did you go to a movie last night?” you may say, “Indeed, I did go to a movie last night.” “Indeed” is used to stress the fact, to emphasize that you did go to a movie.
“Indeed” is also sometimes used to confirm a previous statement. For example: “The movie was wonderful,” and someone may say, “Indeed, it was.” You’re saying “yes, it was.” So, you use “indeed” to agree with something that was said earlier, something that someone else said.
You can also use “indeed” to express surprise or disbelief. When you can’t believe something, you may say, “Indeed, it was a very good show.” You are surprised by how good it was.
In the United Kingdom, “indeed” is often, I understand (I am told), used as an expression of surprise or disbelief. In the U.S., you see it mostly in writing in American English to mean the sorts of things we’ve talked about, as a matter of emphasis or to agree with or confirm a previous statement. It’s not common in American English daily conversation. It sounds a little strange, perhaps a little British to American ears if you use “indeed” to express surprise or agreement when you are talking to someone informally.
Jonathon (Jonathon) in Germany wants to know about the use of the word “none” or “none of them” in terms of the verb, whether it’s singular or plural. Do you say “none of them is,” or do you say “none of them are?”
Well, “none” means not one, nobody, no one. Whether you use “is” or “are,” however, depends on what the word “them” refers to. If you say “none of them,” whatever word that refers to or whatever word is substituted for that word will determine whether the verb is singular or plural. We called this the “object” of the preposition. The preposition is “of,” “them” is the object of the preposition. So, if the object is something that you can count, what we call a “count noun,” for example: eggs, or children, or airplanes, computers – these are all count nouns. You can count one chair, two chairs, three chairs, and so forth. They have a plural form and a singular form. If it’s a count noun, and it’s plural, then the verb is plural. For example: “None of the eggs are cracked” – none of the eggs have a crack in them. There, it takes the plural form of the verb. “None of the children are playing outside.” “Children” is a count noun; you can count children: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11. That would be my parents counting all of their children!
If the word (the object of the preposition) is what we call a “mass (mass) noun,” this is when you use the singular form of the verb: “is.” A mass noun is a noun that does not take a plural form; it’s a noun that we don’t normally think about as having separate units. For example, the word “furniture” refers to things in your house like chairs, couches, tables – things you use in the house. These are, or can be called simply “furniture.” But, “furniture” is a mass noun, meaning you would never say “furnitures,” with an “s” at the end. Because of that, if it’s the object of the preposition in this expression it’s going to take the singular form of the verb: “None of the furniture is going to be cleaned today.” Another word that is a mass noun, referring to people, is “personnel.” “Personnel” refers to the people who work in a company. And although you can count people, the word “personnel” is a mass noun; you would never say “personnels.” So, you could say “None of the personnel is here right now.” However, if you use the word “people”: “None of the people are here.” So, it’s a bit confusing, depending on whether you have a count noun as the object of the preposition, or a plural noun.
For those of you who are still awake, our next question is from Dimitry (Dimitry) from Russia. Dimitry heard an expression on the BBC (the British Broadcasting Corporation). It was that something was going to go “down to the wire.”
The expression “down to the wire,” or to go “right to the wire,” which is what he read or heard, means a race or a competition that will have a very close result. In other words, we won’t know until the very end of the race or competition who is going to win. If you watched the Olympics and you watched the swimming events, for example, many of the swimmers are very fast, about the same speed. The difference between them is very small. So, the winner is not determined until the very last second of the race. It goes right down to the wire – it goes right to the end before you know who won.
You’ll often hear this expression when talking about a sporting event, a game of some sort. The expression originally comes from horse races, where they would put a wire at the finish line (where the horses would end up), and whichever one crossed the wire first was the winner. The wire, of course, couldn’t be too strong otherwise it would kill the horses! So, that’s the general idea.
If you have a comment or a question, you can email us, if you want. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational
Development.
Glossary
case – a legal decision made by a court; a legal action brought before a judge to decide if anyone has broken the law
* After hearing the case, the judge decided that the man would be put in prison for two years for stealing money from his company.
party – a group of people who are doing the same activity; in law, people or groups on each side of a court case
* The two parties involved in the court case finally decided to meet outside of court and come to an agreement.
landmark decision – extremely important decision that changes history; a decision that changes how things will be done in the future
* In 2008, the government made a landmark decision to protect the environment.
inferior – not as good as something else; weaker, less powerful, or less important compared to another
* In the U.S. in the 1800s, women were considered inferior to men. Today, men and women are often given the same rights and opportunities.
to rule – to make a legal decision about something; to say that something is right or wrong according to the law
* The judge ruled that any employer who treats employees unequally based on age would be punished.
to enroll – to register; to put one’s name on a list so that one can attend a school or course of study
* Jessica wanted to learn how to fix cars, so she enrolled in a two-week course on car mechanics.
to desegregate – to end separation between people of different races, social status, or gender; to allow different kinds of people to be in the same group
* The coach forced the boys and girls to desegregate and to form sports team that were made up of both boys and girls.
yearbook – a special book that is made at the end of each school year containing photographs and information that help students remember what happened during that year in school
* At our 10-year reunion, my friends and I took out our yearbooks and talked about the old days.
keepsake – something that helps you remember a special person, event, or time in your life; a special gift that reminds you of the person who gave it to you
* Every time I am sad, I take out all the special keepsakes from my boyfriend.
peers – other students; other people of about the same age
* Many teenagers like to be part of a group, wearing the same types of clothing and doing the same types of things as their peers.
hairdos – hairstyles; the way a person wears his or her hair
* Hairdos change with time. Hairdos can be curly or straight, up or down, long or short, all depending on what the fashion is at the time.
autograph – signature by a famous person, such as a sports star, singer, or actor; a well known person’s signature or handwriting
* I’m excited about attending tonight’s basketball game because it gives me the chance to get the autographs of my favorite players.
indeed – in fact; in truth; actually, often used to emphasize the truth
* Indeed, the newspaper was right: Today was the hottest day in 10 years!
none of them is/are – not one; not any
* None of the employees are willing to stay late in the office tonight.
down to the wire – a race or competition that has or will have a very close result; not knowing the result of the race until the very end because the competitors are very close
* The two swimmers raced down to the wire, with Jake winning by less than one second.
What Insiders Know
To Kill a Mockingbird
The novel To Kill a Mockingbird was written by Harper Lee in 1960. Since then, it has become an American “classic” (a book that is considered to be very well written and that most people know about). Many school children in the United States read this book because it talks about an important issue in America: Racial differences and the need to be fair and kind to people no matter what their race or “social class” (how rich or poor someone is).
The author Harper Lee was born in the southern state of Alabama in 1926. As she grew up, she experienced the feelings of dislike between whites and blacks. Many whites during this time did not treat blacks as equals. Blacks could not attend the same schools as whites, and they had to sit separately on the bus. As Harper Lee saw the way that whites treated blacks, she realized that people needed to change their ideas and behavior and to treat all people equally.
In her award-winning novel, Harper Lee writes about a white family in Alabama that is made up of a father named Atticus, and his two children: a six-year old girl named Scout, and her older brother named Jem. Atticus, who is a lawyer, is asked to defend a black man who is accused of “rape” (the crime of forcing a sexual relationship). In this story, Atticus is an example of a white man who realizes that everyone should be treated equally and with respect. He does his best to help the black community, and he teaches his children the importance of having courage and “compassion” (kindness) to all.
The novel became so popular that it was later turned into a movie in 1962. The movie won three Academy Awards, and in 2007, it was named one of the greatest American films of all time.
Even though it has been more than 50 years since it was published, the novel continues to be very popular, not only in the United States but also around the world.