= 1757
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 452.
This is English as a Second Language Podcast’s English Café episode 452. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and support these free audio lessons today. Take a look at our special courses when you’re on the website, with Business and Daily English courses I think you’re going to like. Speaking of liking, you can also like us on Facebook at facebook.com/eslpod, and why not follow us on Twitter at @eslpod.
On this Café, we’re going to be talking about schools and entertainers. First, we’ll discuss a famous court case called “Lau v. Nichols” that changed the way the schools teach students for whom English is a second language. We’re also going to talk about a popular form of entertainment in the late 1800s and early 1900s in the U.S. called “vaudeville.” And, as always, we’ll answer a few of your questions. Let’s get started.
Each year, many people immigrate to the United States. “To immigrate” (immigrate) means to move to another country to live. For many of these people, English is not the language they grew up speaking. They have to learn English when they move to the United States. Adults often learn English through English as a Second Language classes or English as a Second Language Podcast.
Children, however, who move to the United States learn English in their regular school. Sometimes these children, called “English language learners” by teachers, are given special English as a Second Language classes in addition to their regular classes. Sometimes – until their English is good enough to understand their regular subjects like math, science, history, and so forth – these content classes are taught in their native language. This is sometimes called “bilingual education.”
“Bilingual” means two languages. If you speak two languages, you are called “bilingual,” since the prefix “bi-” means two. If you speak three languages, you are called “trilingual,” since the prefix “tri-” means three. If you speak only one language, you’re called “monolingual,” since “mono-” means one. But if you speak more than three languages, we would probably call you a “polyglot” (polyglot) – someone who speaks many tongues or languages.
The theory behind bilingual education for immigrant children who have low levels of English arriving to the United States is actually pretty simple, although there are few people who really understand it. Let’s say you’re 12 years old and you arrived to the United States speaking only Spanish or Chinese. You speak very little English. You go to school, and the school puts you in sixth grade with the other twelve-year-olds. Now, you will definitely start improving your English right away, but it will take some time.
How much time? Well, most studies find that your reading and writing skills necessary for keeping up with the other students who are native English speakers (that is, they grew up speaking English) is anywhere from four to seven years. Now, if you go into a science class or a history class in the sixth grade and you don’t speak any English, you’re not going to understand anything. Everyone else in the class will understand the language and learn science, except you. You won’t learn much of anything.
So, immediately the other kids are learning more and more about science and history, and you aren’t learning anything. You start to “fall behind.” “To fall behind” means to be behind, or to know less than, everyone else. If we wait to give you science and math and history classes until your English is good enough, you’ll be 16 – maybe 18 – years old before you can start learning those subjects again. That’s obviously too late.
I should mention here that kids are often able to communicate orally speaking informally with other kids just fine after a year or two in the U.S., but school language – what we would call “academic (academic) language” – is different. It’s harder. You need to have a good reading vocabulary to understand the textbooks and the lectures in school.
Instead of basically wasting several years for your English to improve, we can use a better approach, one which actually makes both learning English and learning all of the other regular subjects in school go much more quickly. When you go to the sixth grade, instead of putting you in a regular class full of English speakers, we instead give you instruction – that is, we teach you – in your native language, such as Spanish or Chinese.
You will learn math and science and history in your own language so that you don’t fall behind. However, we also give you English lessons, of course, to start improving your English. Now, the next year, when you’re in seventh grade, your English may have gotten good enough so that you can understand the teacher in some subjects or topics that don’t use as much language, such as math.
So, maybe in seventh grade we put you into a regular math class in English, but still give you science and history in your own language so you don’t fall behind in those topics. Since your English isn’t good enough yet to understand history – seventh-grade history – in English, we give you that same information in your own language. As your English improves, then, we gradually – slowly – move you from your own language to all-English language instruction.
Not only does this approach keep you from falling behind, but it actually helps you learn English faster. The reason is one you probably already know, but haven’t thought about much. We can usually understand what someone is saying in another language more easily if we know something about what they are talking about – if we already know something about that subject.
So, for example, if you studied chemistry in Spanish, and I give you a chemistry book in English, you will understand that book much better than someone who studied philosophy in Spanish or architecture in Spanish. You still have to understand some basic vocabulary, but if you know something about the topic that the person is talking about, you will understand more of the language that you are reading or listening to. So, by giving students classes in science and math and history in their own language first, we’re giving them the knowledge they can use to understand those topics later on in English.
Okay, now back to our story. Before the 1970s in the U.S., many states had very few classes to help children who did not speak English as their native or first language. For children who immigrated to the United States who did not speak English, or spoke only very little English, this made it difficult for them to succeed in school. Of course, they couldn’t understand what the teacher was saying.
So, in San Francisco, California, in 1970, the parents of 2,800 Chinese-American students asked their school board to find ways to help their children succeed in school. A “school board” (board) is the group of people who are responsible for making decisions about operating, or running, a school or a group of schools. The parents complained that their children did not speak enough English to be able to follow along or understand their math, science, history, and other regular classes.
The school board agreed to create an “English as a Second Language” class that met – are you ready? – for one hour each week. Yes. That’s right, one hour each week. Not each day – each week. And only a thousand of these 2,800 students would be able to attend. The other 1,800 were not allowed to go to this class.
What happened next is that the parents of the 1,800 Chinese-American students who were not able to attend an ESL, or English as a Second Language, class filed what we call a “lawsuit.” “To file a lawsuit” means to go to a judge and say that you are being hurt by these other people, and they need to stop it, or they need to give you money for the damage that they already caused you.
In this case, the lawsuit was filed against the president of the school board, Alan Nichols, and against the San Francisco Unified School District. A “school district” is a group of schools in a certain area that are all controlled by the same school board. So, these students said that the school district and school board were responsible for helping them learn English so that they could succeed in their classes. Not helping the students was, in their opinion, a violation of the Civil Rights Act of 1964. A “violation” (violation) is when you don’t follow a law – when you break a law.
What is the Civil Rights Act of 1964? Well, it was a law passed by the U.S. Congress that said that all people should be treated equally no matter what their race, color, or national origin. This meant that all people, no matter what color their skin is or where they were born – their “national origin” – are entitled or should have the same opportunities to get an education, get a job, and have somewhere to live. This law made it illegal for people to discriminate, or treat people differently because of the way they looked or the way they sounded or where they were from.
The Chinese-American students in San Francisco said that the school board was discriminating against them because of their national origin. They did not speak English as a second language in the country where they were from, and therefore were not able to get the same access to a good education as other students from other places, including here in the United States.
The students also said that not helping them learn English was a violation of another law – the 14th Amendment to the Constitution. The 14th Amendment says that states must treat every person equally, whether they were born in the United States or are naturalized. “To be naturalized” (naturalized) means to become a citizen of a country even though you were born in another country. In the United States, you can become a citizen by being naturalized. You are given official documents that say yes, you are now a citizen of the United States.
The first two courts to hear this case – to listen to the parents of these children – ruled, or decided, that it was not the school board’s responsibility to provide English education for the students. They said that every student comes to school with things that make school hard. Some students don’t have enough money. Other students have family problems. Others don’t speak English very well.
The court said that it was the school’s responsibility to provide each student with the same books, teachers, and classrooms (well, not exactly the same teachers and classrooms, but equivalent – equal in quality – teachers and classrooms). The court said that it was the school’s responsibility only to make sure that these things were equal in quality, and if they did that, then no one was being discriminated against.
The next step happened in 1973, when the Chinese-American students took their case to the United States Supreme Court, which is the highest court, the highest legal authority, in the United States. And on January 21st, 1974, the court made its ruling. Unlike the other two courts, the Supreme Court said that the Chinese students and their parents were right.
What the Supreme Court says becomes basically the rule or the law. The Supreme Court interprets the law, and their interpretation is the final word, if you will – the final say on the issue. If the other courts disagree with the Supreme Court, the Supreme Court is always right. Well, they’re not always right, but it’s their interpretation that is followed. The Supreme Court in this case said that the schools were responsible for helping all students learn enough English to understand the classes they were taking.
The Supreme Court said that even if all the students had the same books and equally qualified teachers and good classrooms, students who did not speak English who were not given help learning English were not being treated equally. The Supreme Court, however, did not say how the schools should help students learn English, only that they had to do something. They allowed the school board to decide the best way to help the students.
Now, the school board in this case decided to do bilingual education for the Chinese, Filipino, and Latino students who didn’t speak English sufficiently to understand the regular classes. Not all schools or states provide bilingual education to students in the United States, but all schools in the U.S. are required to give extra help to children who come to the U.S. not speaking English. That’s why this court decision – Lau v. Nichols – is so important to American education.
Now, if you come here as an adult, the government doesn’t have any responsibility to help you learn English, but in almost all big cities there are, in fact, free ESL classes for adults, or low-cost English as a Second Language classes for adults, who want to improve their English. The problem there is there aren’t enough of these classes, but at least the government does try to do something to help people improve their English.
Now let’s talk briefly about a popular form of entertainment in the late 1800s and early 1900s called “vaudeville.” “Vaudeville” (vaudeville) was a kind of variety show. A “variety show” is a form of entertainment that has people who perform many different kinds of acts and activities, such as singing and dancing, on the stage. The word “vaudeville” comes from a French word originally, and refers to fun, entertaining shows where people sang and had little dialogues or plays.
Most of the vaudeville shows in the late nineteenth and early twentieth centuries in the U.S. had between 10 and 15 different performances. These performances included people who did magic, or playing tricks on the audience like making objects disappear. (I would like someone to make my neighbor’s dog disappear. That would be a really cool trick.) There were also comedians – people who tell jokes and make people laugh.
Sometimes there were animals that were trained to do funny things like stand on two legs. Vaudeville shows also had “jugglers” (jugglers). Jugglers are people that can throw many objects in the air at one time and catch them all or keep them all in the air at the same time. And, of course, vaudeville shows had singers and dancers. Basically, there was something for each member of the audience to enjoy.
Because there were so many different performances, the vaudeville shows could last, or go on, for hours. This was usually okay with the audience, however, since for many of them the vaudeville shows were the main form of entertainment that they had. There was no Internet back then, no cable television, no movie theaters, no television. Going to live performances, live shows, then, was the main form of entertainment that people had, other than reading at home and perhaps listening to your grandfather tell stories.
Vaudeville shows were popular in the U.S. from the 1850s to the 1930s. The shows were performed both in cities and in small towns. When they began in the 1850s and 1860s, vaudeville shows were performed mostly in what were called “beer halls,” which were basically bars, and the performances were just for men – the men who went to these bars. Many of these performances were not meant for, shall we say, women and children to see.
However, in 1881, a vaudeville performer and singer named Tony Pastor changed the performances he organized in order to make them more, what we would call today, “family friendly.” He made them so that women and children could enjoy them, too. Basically, he cleaned them up. He took all the things that were not considered appropriate for women and children out of the show and made the show one that everyone in the family could enjoy.
This became very popular, and soon other vaudeville show organizers began to change their shows, too, so that they also became family friendly. This, of course, made a lot of economic sense. If the whole family can go to the show, that would mean more people, and more people means more money. By the 1890s, almost all of the vaudeville shows then were aimed to please, or make happy, the whole family – men, women, and children.
In 1896, movies were added to the vaudeville shows. At first, when the movies were silent and none of the actors spoke, they were simply another act in the show, another part of the show. Once actors in the movies began speaking, however, the movies became the main act, and the other performances were what we would call “side acts” – less important performances.
However, the Great Depression in the 1930s in the U.S. put an end to vaudeville shows. The Great Depression was a period when banks lost a lot of money, and people who had saved their money often lost everything or almost everything. People did not have any extra money then to spend on entertainment, so the shows quickly lost their audiences, the people who went to see them. In addition, radio and television were becoming more popular during this same period. After the end of World War II in 1945, vaudeville shows were really a thing of the past – something that was no longer possible.
Vaudeville shows may have ended, but their influence certainly continued even after the 1930s. Some of the most famous performers first started their work in vaudeville. W. C. Fields was a comedian and a juggler in vaudeville shows. Will Rogers was a cowboy and a comedian. Both later became famous actors in the theater on Broadway as well as in movies in the 1920s and ’30s. Many people say that later actors, such as Charlie Chaplin, were actually inspired by, or got ideas and motivation from, these vaudeville performances.
Now let’s answer a few of the questions you have sent to us.
Our first question comes from Mohamed (Mohamed) in Algeria. Mohamed wants to know the difference between “finally” and “ultimately.” “Finally” (finally) means after a long time, at the end of a very long period, and sometimes simply “at last.” “After many weeks of studying for this exam, I finally took the exam.” At the end of a certain period, you finally do something. That’s how we use this word “finally.” Or, “My brother has finally decided to go to Paris.” He has been wanting to go. He couldn’t make up his mind – he couldn’t decide – and finally he decided.
“Ultimately” (ultimately) also means at the end of a certain period of time. It’s used a little differently, however. When you say “ultimately,” usually you’re referring to a situation in which what has happened was going to happen no matter what. As long as certain conditions were met, you would be able to do this. If you study every day, ultimately you will be able to pass the exam. By studying, you will pass the exam. It’s almost guaranteed.
However, we could also use “ultimately” the same way that we use “finally.” “I thought about it for many months, and ultimately I decided to buy the red car instead of the blue car.” I could also say, “Finally I decided to buy the red car instead of the blue car.” They would mean the same thing in that instance. If you’re not sure which word to use, use “finally.” “Finally” is much more common than “ultimately” in conversation.
Our next question comes from Lucas (Lucas) from an unknown country, but it seems to be a country where they get a lot of rain, because this question has to do with the difference between “trickle” (trickle) and “drizzle” (drizzle).
“Trickle” is when there is a small amount of liquid, such as water, that is coming out of something. For example, if you go into your restroom, your bathroom, and you turn the water on just a little bit, you will get a trickle of water – just a little bit of water flowing or coming out of what we call the “faucet,” which is where the water comes out of in your restroom when you’re washing your hands.
“Drizzle” refers specifically to water coming out of the sky, if you will – from clouds. “Drizzle” is a very light rain. Sometimes people use the word “trickle” to talk about the rain “drizzling,” falling very lightly, but really, “drizzle” is the word that we would use most often when talking about a light rain. It’s raining, but it’s not raining very much. It’s not raining very hard, we would say.
We might even describe the amount of rain as just a “trickle,” but “trickle” is not the most common word when describing the weather. “Trickle” would be used in other situations. We would not, however, use “drizzle” to talk about water coming out of your faucet in your bathroom. That would only be “trickle.” “Drizzle” refers to a light rain.
Finally Hajar (Hajar), also from a mysterious, unknown country – somewhere here on planet Earth, I hope – wants to know the meaning of the word “coincidence.” A “coincidence” (coincidence) is when two different events happen at the same time by accident. They don’t seem to have any connection to each other, although we may see some relationship between these two events.
For example, I go to the store to buy some milk, and I see an old friend of mine there. This happened actually a couple weeks ago. I saw someone I have known for many years. It was a coincidence. We didn’t plan both to be there at the store at the same time, but when we saw each other we talked to each other. Those two things happening at the same time by accident could be called a coincidence.
You’ll often hear people say, “What a coincidence” when they see someone they didn’t expect, for example, at the store, or when two things happen at the same time that surprise you, you can also say, “What a coincidence!”
If you have a question, don’t worry, you won’t surprise us. We’ll be happy to do our best to try to answer that question here on the English Café. Just email us at eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
to immigrate – to move to another country to live; to leave one’s country and move to another permanently
* During the potato famine in Ireland in the 1800s, many Irish people immigrated to the United States.
bilingual education – a program in schools where regular classes and most subjects are taught in two languages
* In the United States, bilingual education is most often conducted in English and Spanish.
native language – the first language a person learns to speak
* Most people born in France speak French as their native language.
school board – the group of people who are responsible for making decisions about how a school operates
* When children at the local school were not passing their classes, the school board decided to hire a new principal who would manage the school differently.
school district – the group of schools in a certain area that are all controlled by the same school board (group of people who make decisions about how a school operates)
* New York Public Schools is the largest school district in the United States with almost one million students.
violation – the act of not following a law or regulation; the breaking of a law
* In many cities, it is a violation to walk down the street while drinking an alcoholic drink.
to be naturalized – to become a citizen of one country after being born in another country
* People who want to be naturalized citizens of the United States must take a long exam and answer questions about U.S. laws and history.
variety show – a form of entertainment with many different types of performances
* The variety show included a singer, a dancer, and a person who had trained his bird to speak.
magic – a form of entertainment where the performer plays tricks on the audience and makes them see or believe things that are not true
* During the magic show, the magician cut a woman in half and then put her back together again.
comedian – a person who tells jokes and tries to make other people laugh
* The comedian stood on stage and told funny stories about his family, which made the audience laugh.
juggler – a person who can throw many objects in the air at one time and catch them all, keeping several in motion at one time
* The juggler was able to keep an apple, an orange, and a banana in the air all that the same time.
to be inspire by – to be motivated by; to make someone want to do something
* After watching a great boxing match, Sylvester Stallone was inspired to write the movie Rocky.
finally – after a long time; at the end of a long period; at last
* It finally stopped snowing after two days and LeeAnn could go back to school.
ultimately – in the end; being or happening at the end
* Joanna told a long story about problems on her trip, which ultimately was fun and enjoyable.
trickle – a small flow of liquid
* Her tears trickled down her face as she watched the sad movie.
drizzle – light rain falling in very fine or small drops
* No one expected a rainstorm since the weather report said to only expect drizzle today.
coincidence – the occurrence of events happening at the same time by accident that appear to have some connection but do not
* It was an embarrassing coincidence that both our wives showed up at the party wearing the same dress.
What Insiders Know
American Cabaret
“Cabaret” was a form of entertainment very popular in the early 1900s. It features different types of performances, such as comedy, music, dance, and even drama. However, the most “notable” (significant) characteristic of cabaret is the “venue” (a place where an event occurs). Cabarets are normally held in restaurants, bars, and even “nightclubs” (a place for nighttime entertainment, including dancing and music).
Cabaret performances usually includes an “M.C.,” or a master of ceremonies, whose job is to start and end the show and to announce and introduce the performers. The audience members are seated at tables with food and drink while watching the acts on stage. Sometimes, cabaret performances have women who “mingle” (interact socially) with the audience and entertain them during performances.
Cabaret became very popular in many countries. In the United States, it was imported from French cabaret by an American motion picture producer named Jesse Louis Lasky in 1911. During this time, jazz music was also popular and soon, cabaret performances changed its style to focus on this type of American music. In Chicago, cabaret performances focused primarily on “big bands,” bands with many musicians, and was at its most popular in the 1920’s. In contrast, New York cabarets featured jazz vocalists like Nina Simone, Eartha Kitt, Bette Midler, and Peggy Lee, and less on instrumental musicians like the cabarets in Chicago.
The popularity of cabaret and its performances began to “decline” (become less popular) in the 1960s. This was mainly “attributed to” (caused by) the rise in popularity of rock concerts, television shows, and general comedy theaters. And while cabaret’s popularity has more or less “faded” (gone away) in the past 50 years, some places in Las Vegas still have cabaret performances.