
= 60年代, 70年代
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 解读

=== Politics from Camelot to Watergate 从卡米洛特到水门事件的政治

Lyndon Johnson hoped to complete Kennedy's work. +
His Great Society plan declared a "war on poverty" that produced a glut of legislation unseen since the days of Franklin Roosevelt's Hundred Days. +
Welfare benefits were increased, health care costs were defrayed, and funds were allotted for cleaning the air and water, rebuilding cities, and subsidizing the arts and humanities.

[.my2]
**林登·约翰逊希望完成肯尼迪的工作。他的伟大社会计划宣布了一场“向贫困宣战”，产生了自富兰克林·罗斯福百日执政以来从未见过的大量立法。**福利增加，医疗保健费用增加，并分配资金用于清洁空气和水、重建城市以及补贴艺术和人文学科。

A Civil Rights Act ended legal discrimination in public accommodations with regard to race.

[.my2]
"民权法案"结束了公共设施中种族方面的法律歧视。

Unfortunately for Johnson, the domestic minded president became mired in a foreign imbroglio — the war in Southeast Asia. +
Vietnam would taint his legislative successes and end the possibility of a second Johnson term.

[.my2]
对于约翰逊来说不幸的是，这位注重国内事务的总统陷入了一场外交纠纷——东南亚战争。越南战争将玷污他的立法成就，并结束约翰逊第二个任期的可能性。

By 1968, the zeal for domestic reform was squelched by an increasingly popular war. +
Families and friends across America were divided by the conflict. +
Assassinations of Martin Luther King and Robert Kennedy only fanned the flames, and by the end of the decade most Americans were weary of war, rioting, and political crusades — Americans sought a return to normalcy.

[.my2]
到了 1968 年，国内改革的热情, 被日益流行的战争所浇灭。美国各地的家人和朋友因冲突而分裂。马丁·路德·金和罗伯特·肯尼迪的暗杀只是火上浇油，到20世纪90年代末，大多数美国人厌倦了战争、骚乱和政治运动——美国人寻求回归正常。

'''

==== Kennedy's New Frontier 肯尼迪的新边疆

Domestically, Kennedy continued in the tradition of liberal Democrats Roosevelt and Truman to some extent. +
He signed legislation raising the minimum wage and increasing Social Security benefits. +
He raised money for research into mental illness and allocated funds to develop impoverished rural areas. +
He showed approval for the civil rights movement by supporting James Meredith's attempt to enroll at the University of Mississippi and by ordering his Attorney General, brother Robert Kennedy, to protect the freedom riders in the South.

[.my2]
在国内，肯尼迪在一定程度上延续了自由民主党人罗斯福和杜鲁门的传统。他签署了提高最低工资, 和增加社会保障福利的立法。他筹集资金用于精神疾病研究，并拨款发展贫困农村地区。他支持詹姆斯·梅雷迪思进入密西西比大学就读，并命令他的当司法部长弟弟罗伯特·肯尼迪, 保护南方的自由乘车者，这表明了他对民权运动的认可。


However, most of Kennedy's more revolutionary proposals languished in the conservative Congress. +
He wished to protect millions of acres of wilderness lands from developments, but the Congress refused. +
His efforts to provide federal funds to elementary and secondary schools were denied. +
His Medicare plan to provide health insurance for the nation's elderly failed to achieve the necessary support. +
Congress was dominated by a coalition of Republicans and conservative Southern Democrats who refused to expand the New Deal any further.

[.my2]
然而，肯尼迪的大多数更具革命性的提议, 在保守的"国会"中都受到了冷落。他希望保护数百万英亩的荒地免遭开发，但国会拒绝了。他为中小学提供联邦资金的努力, 遭到拒绝。他为全国老年人提供健康保险的医疗保险计划, 未能获得必要的支持。国会由"共和党"和"保守的南方民主党"联盟主导，他们拒绝进一步扩大"新政"。

In his abbreviated Presidency, Kennedy failed to accomplish all he wanted domestically. +
But the ideas and proposals he supported survived his assassination. +
Medicare, federal support for education, and wilderness protection all became part of Lyndon Johnson's Great Society.

[.my2]
在他短暂的总统任期内，肯尼迪未能在国内实现他想要的一切。但他支持的想法和建议在他遇刺后幸存下来。医疗保险、联邦政府对教育的支持, 和荒野保护, 都成为林登·约翰逊伟大社会的一部分。

Lee Harvey Oswald assassinated Kennedy in November, 1963. +
His death provided a popular mandate for these important programs. +
In the tumultuous years that followed, many yearned for the happy Kennedy years — a return to Camelot.

[.my2]
1963年11月，李·哈维·奥斯瓦尔德暗杀了肯尼迪。他的死为这些重要的项目提供了广泛的支持。在随后的动荡岁月里，许多人渴望回到卡梅洛特，回到肯尼迪的幸福岁月。


'''


==== Lyndon Johnson's "Great Society" 林登·约翰逊的《伟大社会》


Lyndon Baines Johnson moved quickly to establish himself in the office of the Presidency. +
Despite his conservative voting record in the Senate, Johnson soon reacquainted himself with his liberal roots. +
LBJ sponsored the largest reform agenda since Roosevelt's New Deal.

[.my2]
林登·贝恩斯·约翰逊, 很快就在总统职位上站稳了脚跟。尽管约翰逊他在参议院的投票记录, 属于"保守派"，但他很快就重新认识了自己的"自由派"根源。*林登·约翰逊发起了自"罗斯福新政"以来最大规模的改革议程。*

The aftershock of Kennedy's assassination provided a climate for Johnson to complete the unfinished work of JFK's New Frontier. +
He had eleven months before the election of 1964 to prove to American voters that he deserved a chance to be President in his own right.

[.my2]
肯尼迪遇刺的余震, 为约翰逊完成肯尼迪新边疆未竟的工作提供了氛围。*距离 1964 年大选还有 11 个月的时间，他需要向美国选民证明，他凭借自己的能力应该有机会担任总统。*

Two very important pieces of legislation were passed. +
First, the Civil Rights Bill that JFK promised to sign was passed into law. +
The Civil Rights Act banned discrimination based on race and gender in employment and ending segregation in all public facilities.

[.my2]
通过了两项非常重要的立法。首先，肯尼迪承诺签署的"民权法案"获得通过成为法律。 《民权法案》禁止就业中基于种族和性别的歧视，并结束所有公共设施中的种族隔离。


Johnson also signed the omnibus ECONOMIC OPPORTUNITY ACT OF 1964. +
The law created the Office of Economic Opportunity aimed at attacking the roots of American poverty. +
A Job Corps was established to provide valuable vocational training.

[.my2]
约翰逊还签署了 1964 年综合经济机会法案。该法案设立了"经济机会办公室"，旨在解决美国贫困的根源。成立了就业团来提供有价值的"职业培训"。

Head Start, a preschool program designed to help disadvantaged students arrive at kindergarten ready to learn was put into place. +
The VOLUNTEERS IN SERVICE TO AMERICA (VISTA) was set up as a domestic Peace Corps. +
Schools in impoverished American regions would now receive volunteer teaching attention. +
Federal funds were sent to struggling communities to attack unemployment and illiteracy.

[.my2]
Head Start 是一项学前计划，旨在帮助弱势学生进入幼儿园做好学习准备。美国志愿服务组织 (VISTA) 是作为国内和平队成立的。美国贫困地区的学校, 现在将得到志愿者教学的关注。联邦资金被送往陷入困境的社区，以解决失业和文盲问题。

As he campaigned in 1964, Johnson declared a "war on poverty." He challenged Americans to build a "Great Society" that eliminated the troubles of the poor. +
Johnson won a decisive victory over his archconservative Republican opponent Barry Goldwater of Arizona.

[.my2]
1964 年，约翰逊在竞选, 时宣布“向贫困宣战”。他向美国人提出挑战，要建立一个消除穷人烦恼的“伟大社会”。约翰逊赢得了对他的主要保守派共和党对手亚利桑那州的巴里·戈德华特的决定性胜利。

American liberalism was at high tide under President Johnson.

[.my2]
在约翰逊总统的领导下，美国自由主义达到了顶峰。

- The Wilderness Protection Act saved 9.1 million acres of forestland from industrial development.

[.my2]
《荒野保护法》从工业发展中拯救了 910 万英亩的林地。

- The Elementary and Secondary Education Act provided major funding for American public schools.

[.my2]
《中小学教育法》为美国公立学校提供了主要资金。

- The Voting Rights Act banned literacy tests and other discriminatory methods of denying suffrage to African Americans.

[.my2]
《投票权法》禁止识字测试, 和其他剥夺非裔美国人选举权的歧视性方法。

- Medicare was created to offset the costs of health care for the nation's elderly.

[.my2]
医疗保险的创建, 是为了抵消国家老年人的医疗保健费用。

- The National Endowment for the Arts and Humanities used public money to fund artists and galleries.

[.my2]
国家艺术与人文基金, 会使用公共资金资助艺术家和画廊。

- The Immigration Act ended discriminatory quotas based on ethnic origin.

[.my2]
《移民法》结束了基于种族的歧视性配额。

- An Omnibus Housing Act provided funds to construct low-income housing.

[.my2]
《综合住房法》为建造低收入住房提供了资金。

- Congress tightened pollution controls with stronger Air and Water Quality Acts.

[.my2]
国会通过更严格的空气和水质量法案, 加强了污染控制。

- Standards were raised for safety in consumer products.

[.my2]
消费品安全标准, 得到提高。

Lyndon B. +
Johnson signs Civil Rights Act
The Civil Rights Act of 1964 was part of Lyndon B. +
Johnson's "Great Society" reform package — the largest social improvement agenda by a President since FDR's "New Deal."

[.my2]
1964 年的"民权法案"是林登·约翰逊 (Lyndon B. +
Johnson) 的“伟大社会”改革方案的一部分，这是自罗斯福“新政”以来总统制定的最大的社会改善议程。

Johnson was an accomplished legislator and used his connections in Congress and forceful personality to pass his agenda.

[.my2]
约翰逊是一位卓有成就的立法者，利用他在国会的关系和强有力的个性, 来通过他的议程。

By 1966, Johnson was pleased with the progress he had made. +
But soon events in Southeast Asia began to overshadow his domestic achievements. +
Funds he had envisioned to fight his war on poverty were now diverted to the war in Vietnam. +
He found himself maligned by conservatives for his domestic policies and by liberals for his hawkish stance on Vietnam.

[.my2]
到 1966 年，约翰逊对自己取得的进步感到满意。但很快东南亚发生的事件(即越战), 开始掩盖他在国内取得的成就。他原本计划用于消除贫困的资金, 现在被转用于越南战争。他发现自己因国内政策而受到"保守派"的诽谤，因对越南的强硬立场而受到"自由派"的诽谤。


[.my1]
.案例
====
.自由派vs保守派

[.small]
[options="autowidth" cols="1a,1a"]
|===
|保守派(右) social liberalism |自由派(左) Conservatism

|通常指的是对资本主义传统价值观（少监管、小政府）和基督教伦理的坚持. +
(*这也是美国开国时, 开国元勋们那时持有的思想*)
|通常对社会问题的观点更加开放，经济政策有“社会主义”的影子（高福利、大政府）. +
(*自由派名字中的"自由", 其实就是对"保守派"思想的偏离.*)


|其特征包括尊重美国传统、支持共和主义、古典自由主义、*限制联邦政府权力、提倡州权、小政府。*

"共和党"的主流意识形态, 亦为保守主义.



|**是一种偏向"社会公平"及"经济干预"的自由主义，接近"社会民主主义"及"进步主义". +
其学说在经济上采取"凯恩斯主义"的消费经济学，强调政府干预市场经济；**社会哲学上它看重公平多于效率，*主张发展"福利主义"和"社会规划"。社会自由主义总是与"福利国家"相联系。*

二战后社会"自由主义"运动, 常与和工人阶级、工会运动联系在一起.

在美国，"社会自由主义"一词用于将其与"古典自由主义"或"自由放任主义"区别开来，**其中"古典自由主义"影响美国早期一百多年的政治和经济思想，直到经济大萧条和罗斯福"新政"，"社会自由主义"才逐渐发挥影响力，并成为民主党的主流。**自巴拉克·奥巴马就任总统后, "社会自由主义"在美国的影响力达到巅峰.

|
|欧洲很多国家都是"高福利"政策：全民医保，公民缴税也比较高。**凡是"高福利高税收"就意味着政府的规模和职责会比较大（“大政府”），并且政府对经济活动的干预较大（通过"高税收"进行"收入再分配"）。**这本身与亚当·斯密的“小政府”和“完全市场经济”的传统资本主义理论不符（注重“效率”），而是有一点"社会主义"的影子（注重“公平”）。

另外，西欧国家对于大麻、同性婚姻、安乐死、堕胎等问题的态度要比美国开放。

所以，西欧在经济政策上的相对高税收和高福利，与相对开放的社会环境，意味着与**西欧相比美国, 更有“自由派”（偏左）的政治倾向.** 恰美国"民主党"就代表了美国的“自由派”。所以西欧各国更偏爱民主党的拜登，而不喜欢特朗普。

拜登以及奥巴马总统时期的民主党, 推行“全民医保”……明显带有“高福利”的经济特征，属于典型“左”派的经济政策，带有“社会主义”的性质。“全民医保”意味着政府的职责、权力和规模要扩大，要建立“大政府”。而特朗普的共和党反对“全民医保”，主张减税和制造业回归，实际上恢复了“政府应减少对经济干预”的资本主义传统，属于“右”派的经济政策。所以**在美国，民主党更偏向“公平”，共和党更偏向“效率”。**

“全民医保”对弱势群体的意义更大，包括贫困人群和长期受病患折磨的人。对于健康人群，往往持反对立场，认为政府剥夺了公民选择的自由。所以，“全民医保”在美国争议很大，全国大约一半人反对，另一半支持。


|===



====

By 1968, his hopes of leaving a legacy of domestic reform were in serious jeopardy.

[.my2]
到 1968 年，他留下国内改革遗产的希望, 面临严重危险。



'''

==== Triangular Diplomacy: U.S., USSR, and China 三角外交：美国、苏联和中国

predecessor, RICHARD NIXON longed to be known for his expertise in FOREIGN POLICY. +
Although occupied with the Vietnam War, Nixon also initiated several new trends in American diplomatic relations. +
Nixon contended that the communist world consisted of two rival powers — the Soviet Union and China. +
Given the long history of animosity between those two nations, Nixon and his adviser HENRY KISSINGER, decided to exploit that rivalry to win advantages for the United States. +
That policy became known as triangular diplomacy.

[.my2]
**与他的前任不同，理查德·尼克松渴望以其在"外交政策"方面的专业知识而闻名。**尽管忙于越南战争，尼克松也开创了美国外交关系的几个新趋势。*尼克松认为，共产主义世界由两个敌对大国组成——苏联和中国。鉴于这两个国家之间长期以来的敌对历史，尼克松和他的顾问亨利·基辛格决定利用这种竞争, 为美国赢得优势。这项政策被称为"三角外交"。*

As President Nixon's national security adviser, Henry Kissinger made a secret trip to arrange the first-ever Presidential visit to China in 1972. +
He would become Nixon's secretary of state the next year.

[.my2]
作为尼克松总统的国家安全顾问，亨利·基辛格于1972年秘密出访，安排总统首次访华。次年他就任尼克松的国务卿。

As expected, this maneuver caused concern in the Soviet Union. +
Nixon hoped to establish a DÉTENTE, or an easing of tensions, with the USSR. +
In May 1972, Nixon made an equally significant trip to Moscow to support a nuclear arms agreement. +
The product of this visit was the STRATEGIC ARMS LIMITATION TREATY (SALT I). +
The United States and the Soviet Union pledged to limit the number of intercontinental ballistic missiles each side would build, and to prevent the development of anti-ballistic missile systems.

[.my2]
不出所料，这一举动引起了苏联的担忧。尼克松希望与苏联建立缓和关系，即缓和紧张局势。 1972 年 5 月，尼克松对莫斯科进行了一次同样重要的访问，以支持核武器协议。这次访问的成果是《战略武器限制条约》（SALT I）。美国和苏联承诺, 限制双方建造的洲际弹道导弹的数量，并阻止反弹道导弹系统的发展。


Arguably, Nixon may have been the only president who could have accomplished this arrangement. +
Anticommunism was raging in the United States. +
Americans would view with great suspicion any attempts to make peace with either the Soviet Union or China. +
No one would challenge Nixon's anticommunist credentials, given his reputation as a staunch red-baiter in his early career. +
His overtures were chiefly accepted by the American public. +
Although the Cold War still burned hotly across the globe, the efforts of Nixon and Kissinger led to a temporary thaw.

[.my2]
可以说，尼克松可能是唯一能够完成这一安排的总统。反共主义在美国甚嚣尘上。美国人会对任何与苏联或中国讲和的尝试, 抱有极大的怀疑。考虑到尼克松在其早期职业生涯中作为坚定的"红色诱饵者"的声誉，没有人会挑战他的反共资格。他的提议主要被美国公众接受。尽管冷战仍在全球范围内激烈进行，但尼克松和基辛格的努力使冷战暂时解冻。


'''

=== Shaping a New America 塑造新美国


As awareness was being raised across America about civil rights for African Americans, it was only natural that other groups who felt marginalized by the American mainstream to make demands of their own. +
Not since the drive for suffrage had a drive for women's rights met with much success. +
A new FEMINIST MOVEMENT emerged in the 1960s pressing for modern reforms.

[.my2]
**随着美国各地对"非裔美国人公民权利"的认识不断提高，其他感到被美国主流边缘化的群体, 自然也提出了自己的要求。**自从争取选举权以来，争取妇女权利的运动, 还没有取得太大成功。 *20 世纪 60 年代出现了一场新的女权主义运动，迫切要求现代改革。*

With few exceptions, women were excluded from the highest paying jobs, earning only a fraction of the wages of their male counterparts. +
The 1950s cult of the housewife discouraged women from holding full-time jobs and from seeking higher degrees. +
The call for legality and availability of birth control options like the pill galvanized many of feminists. +
Eventually, the right to obtain a safe, legal abortion became a new milestone. +
These demands and others led to the proposal of an Equal Rights Amendment to the Constitution, which would forever ban sex discrimination in the nation's laws and practices.

[.my2]
除了少数例外，女性被排除在薪酬最高的工作之外，其工资仅为男性同行的一小部分。 **20 世纪 50 年代对家庭主妇的崇拜, 阻碍了女性从事全职工作和寻求更高学位。**对避孕药等避孕措施的"合法性"和"可用性"的呼吁, 激励了许多女权主义者。*最终，获得安全、"合法堕胎的权利"成为一个新的里程碑。这些要求和其他要求, 导致了"宪法平等权利修正案"的提出，该修正案将永远禁止国家法律和实践中的"性别歧视"。*



LATINO AMERICANS and NATIVE AMERICANS had also languished in the bottom economic strata throughout much of the prosperous 1950s. +
Radical and moderate ethnic leaders organized to close this gap. +
By the end of the decade, the time was ripe for gay Americans to demand equality as well. +
The politics of identity dominated America as these and other disadvantaged American groups found their voices of protest.

[.my2]
在繁荣的 20 世纪 50 年代的大部分时间里，拉丁美洲人和原住民也一直处于经济底层。激进和温和的民族领导人组织起来缩小这一差距。到本世纪末，美国"同性恋者"要求平等的时机也已经成熟。当这些人和其他弱势美国群体发出抗议声音时，身份政治主导了美国。

Another battle cry was sounded to save the planet from environmental destruction. +
Toxic emissions, deadly pesticides, and fears of nuclear holocaust brought many concerned Americans together in the earth awareness movement. +
This time "GREEN" ACTIVISTS went beyond conservation of resources to demand regulation of economic activities that could hurt the nation's environment.

[.my2]
"拯救地球免遭环境破坏"的又一战斗口号响起。有毒排放、致命杀虫剂, 以及对核浩劫的恐惧, 使许多关心此事的美国人聚集在一起发起地球意识运动。这次“绿色”活动家超越了保护资源的范畴，要求对可能损害国家环境的经济活动进行监管。

In the 1960s, the first baby boomers entered college. +
These students were the largest class of young Americans ever to enter the halls of ivy. +
Unlike the "Silent Generation" of 1950s youth, the baby boomers were vocal about reforming democracy in the United States and the American presence abroad. +
College administrators were confronted with inspired students requesting reforms of the core academic curriculum, greater opportunities for free speech, and more relaxed college rules. +
A small, but highly visible segment of students withdrew from the mainstream and created a counterculture with profound impact on American values, fashion, and music.

[.my2]
**20 世纪 60 年代，第一批婴儿潮一代进入大学。这些学生是有史以来进入常春藤名校的最大一批美国年轻人。与 20 世纪 50 年代的“沉默的一代”不同，婴儿潮一代, 大声疾呼美国的民主改革和美国在海外的存在。大学管理人员面临着一些充满灵感的学生，他们要求改革核心学术课程、提供更多的言论自由机会, 和更宽松的大学规则。**一小部分学生退出了主流，创造了一种对美国价值观、时尚和音乐产生深远影响的反主流文化。


'''

=== A Time of Malaise  不适的时期 (1970年代)

Something was terribly wrong in America in the 1970s.

[.my2]
20 世纪 70 年代的美国出现了严重问题。

The United States was supposed to be a superpower, yet American forces proved powerless to stop a tiny guerrilla force in Vietnam. +
Support for Israel in the Middle East led to a rash of terrorism against American citizens traveling abroad, as well a punitive oil embargo that stifled the economy and forced American motorists to wait hours for their next tank of gasoline.

[.my2]
美国本应是一个超级大国，但事实证明，美国军队无力阻止越南的一支小规模游击队。中东对以色列的支持, 导致了针对出国旅行的美国公民的一系列恐怖主义活动，以及惩罚性的石油禁运，扼杀了经济，迫使美国驾车者等待数小时才能获得下一箱汽油。

A hostile new government in Iran held fifty-two American citizens hostage before the eyes of the incredulous world. +
The détente with the Soviet Union of the Nixon years dissolved into bitter animosity when a second arms control agreement failed in the Senate and a Soviet army of invasion marched into Afghanistan. +
The United States military juggernaut seemed to have reached its limits.

[.my2]
一个充满敌意的伊朗新政府, 在难以置信的世界面前, 劫持了52名美国公民作为人质。尼克松时代与苏联的冲突, 在参议院的第二次军备控制协议失败, 和苏联入侵军队进军阿富汗后，演变成强烈的敌意。美国强大的军事力量似乎已经达到了极限。



At home, the news was no better. +
The worst political scandal in United States history forced a president to resign before facing certain impeachment. +
Months of investigation turned into years of untangling a web of government deceit. +
Details of illegal, unethical, and immoral acts by members of the White House staff covered the nation's newspapers. +
Upon resignation, the president was granted a full and complete pardon. +
Many Americans wondered what happened to justice and accountability.

[.my2]
在家里，消息也好不到哪儿去。美国历史上最严重的政治丑闻, 迫使总统在面临弹劾之前辞职。数月的调查, 变成了多年的解开政府欺骗网络的过程。全国报纸报道了白宫工作人员非法、不道德, 和不道德行为的细节。辞职后，总统得到了完全的赦免。许多美国人想知道, 正义和问责制发生了什么。

The booming economy sputtered to a halt. +
Inflation approached 20% and unemployment neared 10% — a combination previously thought to be impossible. +
Crime rates rose as tales of the decaying inner cities fell on deaf ears. +
A nuclear disaster of unspeakable proportions was barely averted at the Three Mile Island fission plant in Pennsylvania.

[.my2]
蓬勃发展的经济, 陷入停滞。通货膨胀率接近 20%，失业率接近 10%——以前认为这是不可能实现的结合(即"滞胀")。随着内城衰败的故事被置若罔闻，犯罪率上升。宾夕法尼亚州三哩岛裂变工厂, 勉强避免了一场难以形容的核灾难。



Many Americans coped with the current ailments by turning inward. +
Outlandish fashion and outrageous fads such as streaking, mood rings, and pet rocks became common. +
Younger Americans finished their workweeks and sought escape in discotheques. +
Controversy surrounding "DECAYING MORALITY" surfaced with regard to increased drug use, sexual promiscuity, and a rising divorce rate. +
As a result, a powerful religious movement turned political in the hopes of changing directions toward a more innocent time.

[.my2]
许多美国人通过向内转, 来应对当前的疾病。奇特的时尚和令人震惊的时尚，如裸奔、情绪戒指, 和宠物石头, 变得普遍。年轻的美国年轻人结束了每周的工作，到迪斯科舞厅寻求逃避。围绕“道德败坏”的争议, 因吸毒增加、性乱, 和离婚率上升, 而浮出水面。结果，一场强大的宗教运动转向政治，希望改变方向，走向更加纯真的时代。

The United States celebrated its bicentennial anniversary in 1976 without the expected accompanying optimism. +
Instead, while many reflected on the past laurels of American success, an overarching question was on the minds of the American people: what had gone wrong?

[.my2]
1976 年，美国庆祝了建国二百周年，但并没有出现预期的乐观情绪。相反，尽管许多人反思美国过去的成功桂冠，但美国人民心中却浮现出一个首要问题：到底出了什么问题？

'''

==== Undoing a President  推翻(尼克松)总统


...By this time, the HOUSE JUDICIARY COMMITTEE had already drawn up ARTICLES OF IMPEACHMENT, and Nixon knew he did not have the votes in the Senate to save his Presidency.

[.my2]
此时，众议院司法委员会已经起草了弹劾条款，尼克松知道, 他在参议院没有足够的票数, 来挽救他的总统职位。

On August 8, 1974, Nixon resigned the office, becoming the first President to do so. +
His successor, Gerald Ford, promptly awarded Nixon a full pardon for any crimes he may have committed while in office. +
The press and the public cried foul, but Ford defended his decision by insisting the nation was better served by ending the long, national nightmare.

[.my2]
1974年8月8日，尼克松辞职，成为第一位辞职的总统。他的继任者杰拉尔德·福特, 立即授予尼克松全面赦免他在任期间可能犯下的任何罪行。媒体和公众大声疾呼，但福特为自己的决定辩护，坚称结束这场漫长的全国性噩梦, 对国家更有利。

During his years in office, Nixon had brought a controversial end to the Vietnam War, opened communication with Red China, watched NASA put astronauts on the moon, and presided over a healing period in American history in the early 1970s. +
Despite these many accomplishments, Watergate's shadow occludes Nixon's legacy.

[.my2]
尼克松在执政期间, 结束了有争议的越南战争，与红色中国建立了联系，见证了美国宇航局将宇航员送上月球，并在 20 世纪 70 年代初主持了美国历史上的一段治愈时期。尽管取得了如此多的成就，水门事件的阴影遮蔽了尼克松的遗产。

'''

==== The Sickened Economy 病态的经济


Malaise Noun. +
1) An indefinite feeling of debility or lack of health. +
2) A vague sense of mental or moral ill-being.

[.my2]
不适: 名词。 1) 一种不确定的虚弱感或缺乏健康感。 2) 模糊的精神或道德不适感。

People can feel malaise. +
Nations can feel malaise. +
Economies can feel malaise. +
In the mid-1970s much of America suffered a collective MALAISE.

[.my2]
人们会感到不适。各国都会感到不安。经济可能会感到萎靡不振。 *20 世纪 70 年代中期，美国大部分地区都遭受了集体萎靡。*

Nothing fuels a strong case of malaise like a sputtering economy. +
The United States had grown accustomed to steady economic growth since the end of World War II. +
Recessions were short and were followed by robust economic growth. +
For the first time since the Great Depression, Americans faced an economy that could result in a lower standard of living for their children.

[.my2]
没有什么比经济低迷, 更能引发强烈的不安情绪了。自二战结束以来，美国已经习惯了经济的稳定增长。经济衰退是短暂的，随后是强劲的经济增长。*自大萧条以来，美国人第一次面临可能导致其子女生活水平下降的经济形势。*

Inflation, which crept along at one to three percent for the previous two decades, exploded into double digits. +
Full employment, defined as unemployment rates of five percent or less, had been achieved in most years since 1945. +
Now the unemployment rate was nearing the dangerous ten percent line. +
Americans asked the question: what went wrong?

[.my2]
过去二十年里，通货膨胀率一直以百分之一到百分之三的速度缓慢增长，现在却飙升至两位数。自 1945 年以来，大多数年份都实现了充分就业，即失业率在 5% 或更低。现在，失业率已接近危险的 10% 线。美国人问：出了什么问题？



Economists had long held that inflation and unemployment were polar forces. +
High inflation meant a great deal of spending; therefore, many jobs would be created. +
Unemployment created jobless Americans with less money to spend; therefore, prices would stay the same or fall. +
Surprisingly, the United States experienced high unemployment and high inflation simultaneously in the 1970s — a phenomenon called stagflation. +
Experts and commoners debated the roots of this problem with differing opinions.

[.my2]
*经济学家长期以来一直认为, "通货膨胀"和"失业"是处在两极的力量。"高通胀"意味着大量支出；因此，将会创造许多就业机会。"失业"导致美国人失业，可花的钱也减少了；因此，价格将保持不变或下降。令人惊讶的是，美国在 20 世纪 70 年代同时经历了"高失业率"和"高通胀"，这种现象被称为"滞胀"。专家和民众对于这个问题的根源争论不休，意见不一。*

One possibility was the price of oil. +
When Israel defeated its Arab neighbors in the Yom Kippur War of 1973, Arab oil producers retaliated against Israel's allies by leading the ORGANIZATION OF PETROLEUM EXPORTING COUNTRIES (OPEC) to enact an embargo. +
Oil prices skyrocketed immediately in the United States as the demand outstripped the supply. +
Automobiles and drivers sat in long gas lines at service stations.

[.my2]
一种可能性是石油价格。当以色列在1973年的"赎罪日战争"中, 击败其阿拉伯邻国时，阿拉伯石油生产国通过领导"石油输出国组织"（OPEC）实施禁运, 来报复以色列的盟友。由于供不应求，美国的石油价格立即飙升。汽车和司机坐在加油站的长长的加油线上。

The price of oil is independent of other factors such as falling worker productivity and foreign competition, which led to greater unemployment. +
Oil prices also influence the prices of all consumer goods. +
Products that require oil to produce would now cost more. +
Any commodity shipped by truck or airplane would pass its new expenses off to the consumer. +
As the decade progressed, the embargo was lifted, but OPEC steadily raised prices each year. +
The price of a gallon of gasoline more than tripled from the 1970 to 1980.

[.my2]
石油价格独立于其他因素，例如工人生产率下降和外国竞争，这些因素导致了更高的失业率。石油价格还影响所有消费品的价格。需要用到石油生产的产品, 现在成本变得更高。任何通过卡车或飞机运输的商品, 都会将其新的成本费用, 转嫁给消费者。随着十年的发展，石油禁运被解除，但欧佩克每年都在稳步提高价格。从 1970 年到 1980 年，每加仑汽油的价格上涨了两倍多。

Richard Nixon tried to fight inflation first by cutting government spending, but ultimately by imposing wage and price controls on the entire nation. +
GERALD FORD watched the inflation rate soar above 11 percent in 1974. +
He enacted a huge propaganda campaign called WHIP INFLATION NOW (WIN), which asked Americans to voluntarily control spending, wage demands, and price increases. +
The economy, along with Watergate disillusionment, led Ford to suffer defeat at the hands of JIMMY CARTER in the 1976 Presidential election.

[.my2]
理查德·尼克松**试图首先通过削减政府支出来, 对抗通货膨胀，**但最终通过对整个国家实施工资和价格控制。 1974 年，杰拉尔德·福特目睹通货膨胀率飙升至 11% 以上。他发起了一场名为“立即鞭打通货膨胀”(WIN) 的大规模宣传运动，要求美国人自愿控制支出、工资要求, 和物价上涨。经济形势加上"水门事件"的幻灭，导致福特在 1976 年总统选举中, 败给吉米·卡特 (JIMMY CARTER)。



Carter tried tax and spending cuts, but the annual inflation rate topped 18 percent under his watch in the summer of 1980. +
At the same time, the unemployment rate fluctuated between 6 and 8 percent. +
Economic woes may well have been the decisive factor in Carter's defeat to Ronald Reagan in the election of 1980.

[.my2]
卡特尝试减税和削减开支，但在他领导下的1980年夏天，年通货膨胀率高达18%。与此同时，失业率在6%到8%之间波动。经济困境很可能是卡特在 1980 年大选中输给罗纳德·里根的决定性因素。


'''

==== Foreign Woes 国外的困境

America sank deeper into malaise when it looked around at what was going on in the rest of the world.

[.my2]
当美国环顾世界其他地区正在发生的事情时，它陷入了更深的不安。

The decade began with America's longest war ending in its first decisive military defeat in its 200-year-history. +
Diplomacy seemed powerless to stop the economic dependence of the United States on the volatile Middle East for a steady supply of oil. +
Terrorists from this region and others threatened heads of state and ordinary citizens around the globe. +
Despite an auspicious start, relations with the Soviet Union deteriorated by the end of the decade.

[.my2]
这十年始于美国历时最长的战争，并以 200 年历史上第一次决定性的军事失败而告终。外交似乎无力阻止美国经济对动荡的中东石油稳定供应的依赖。来自该地区和其他地区的恐怖分子, 威胁着全球的国家元首和普通公民。尽管开局良好，但到本世纪末，与苏联的关系却恶化了。



Terrorism was on the rise around the globe. +
The world watched in horror as Arab gunmen cut down eleven Israeli weightlifters at the 1972 OLYMPICS in Munich. +
The IRISH REPUBLICAN ARMY (IRA) killed thousands of English and Irish citizens attempting to receive recognition for their cause — an independent homeland. +
Americans began to see the world slipping into anarchy and felt powerless to fix the problem.

[.my2]
恐怖主义在全球范围内呈上升趋势。 1972 年慕尼黑奥运会上，阿拉伯枪手杀死了 11 名以色列举重运动员，全世界都惊恐万状。爱尔兰共和军(IRA)杀害了数千名英国和爱尔兰公民，他们试图为自己的事业——一个独立的家园——获得承认。美国人开始看到世界陷入无政府状态，并感到无力解决这个问题。

In 1979, the new Islamic fundamentalist government of Iran captured 52 Americans at the US Embassy in TEHRAN. +
They demanded the return of their former leader, SHAH MOHAMMED REZA PAHLAVI, to Iran in exchange for the lives of the hostages. +
For 444 days, Americans watched helplessly as their fellow citizens were held in confinement. +
A rescue effort ordered by President Carter crashed in the desert in April 1980.

[.my2]
1979年，伊朗新伊斯兰原教旨主义政府, 在美国驻德黑兰大使馆抓获了52名美国人。他们要求前领导人"沙阿·穆罕默德·礼萨·巴列维"返回伊朗，以换取人质的生命。 444天来，美国人无助地看着自己的同胞被关押。 1980 年 4 月，卡特总统下令进行的一次救援行动在沙漠中坠毁。

[.my1]
.案例
====
.Iran hostage crisis 伊朗人质危机
为1979年伊朗爆发伊斯兰革命后，"美国驻伊朗大使馆"被占领，66名美国外交官和平民被扣留为人质的危机。这场人质危机始于1979年11月4日，一直持续到1981年的1月20日，长达444天。很多人至今仍认为，这场人质危机导致了当时的美国总统吉米·卡特竞选连任失败。

数十年来，美国一直是伊朗国王"穆罕默德·礼萨·巴列维"的主要支持者。**前后八位美国总统为巴列维国王提供了大量的军事和经济援助，用以换取伊朗的石油供应，以及在中东的战略存在。**那些反对巴列维国王的人（因为他1960年代早期曾许诺自由及改革，后却食言）对于美国的做法非常反感乃至愤怒。而巴列维国王按照西方的生活方式生活，让国内的宗教保守人士十分愤怒。社会及宗教人士的不满情绪汇合在一起，最终爆发了伊朗革命将"巴列维"推翻。1979年1月他流亡国外。

美国曾想减少伊斯兰革命对自身的影响，并也曾尝试与伊朗的新政权建立关系。但是1979年10月，巴列维前往美国治疗淋巴瘤，此事激怒了伊朗的革命者。

发生人质事件后, **美国总统吉米·卡特立即对伊朗施加了经济和外交压力：终止从伊朗进口石油；一些伊朗人被美国驱逐出境；冻结大约价值80亿美元的伊朗人的在美资产。1980年4月，美国宣布与伊朗断交。**

伊朗向美国提出了一系列要求作为释放人质的条件，其中包括：遣返被废黜的国王，向伊朗做出一些外交姿态包括为此前美国在伊朗的一系列行为（特别是美国在1953年支持反对莫沙德哈的政变）道歉，并保证今后不再干涉伊朗。

虽然谈判似乎陷入胶着，但1980年7月27日巴列维国王在埃及逝世，9月不久两伊战争又爆发。此后，伊朗变得越来越希望能够解决人质危机。

而在美国方面，卡特在11月的总统竞选中败给罗纳德·里根，大部分分析家认为其在人质危机中表现出的无能是其失败的主要原因。但是也有传言说正是伊朗政府与里根的参谋团之间的非法交易，导致了人质释放时间的推迟。因为后者非常不想见到“十月惊喜”，也就是在大选开始前出现会导致选票大量流向卡特的事件出现，例如人质获释。

作为释放人质的交换条件，美国同意解冻此前所冻结的80亿美元资产，并保证不就此事起诉伊朗。1981年1月20日，就在里根的总统就职典礼后几分钟，所有的人质获释并交返美方。

2015年，52名扣押达444天的人质，每人能获得440万美元的赔偿，相当于1天赔偿近10,000美元。
====



Malaise, malaise, malaise.

[.my2]
不适，不适，不适。


One exception to these negative trends was the CAMP DAVID AGREEMENT, brokered by Carter in 1978. +
These accords resulted in the mutual recognition of Israel and Egypt, a giant first step toward a lasting peace.

[.my2]
这些负面趋势的一个例外是 1978 年卡特斡旋的《戴维营协议》。这些协议导致以色列和埃及相互承认，这是迈向持久和平的巨大第一步。



But the U.S.-USSR détente arranged by Nixon and Kissinger was crumbling by the end of the decade. +
A second arms limitation treaty between the superpowers known as SALT II was delivered to the Senate — only to be rejected. +
The USSR had surpassed the United States in nuclear warheads. +
The Cold War became frostier.

[.my2]
但尼克松和基辛格安排的美苏缓和关系, 在本世纪末崩溃了。超级大国之间的第二项军备限制条约（SALT II）已提交给参议院，但遭到拒绝。苏联的核弹头数量已经超过美国。冷战变得更加冷酷。



A Marxist revolution in NICARAGUA brought greater fears of communism spreading to the Western Hemisphere. +
Finally, in 1979 the Soviet Union invaded AFGHANISTAN with combat troops from the Red Army. +
Soviet Premier Leonid Brezhnev promised that Afghani leaders had requested military assistance, but American diplomats were dubious.

[.my2]
尼加拉瓜的马克思主义革命, 给共产主义蔓延到西半球带来了更大的恐惧。最后，1979年，苏联派出红军作战部队入侵阿富汗。苏联总理勃列日涅夫承诺阿富汗领导人已请求军事援助，但美国外交官对此表示怀疑。



Fearing Soviet expansion into the Middle East, the Carter Administration strongly condemned the action and levied a wheat boycott on the Soviet Union. +
The 1980 OLYMPIC GAMES held in Moscow were boycotted by the United States.

[.my2]
由于担心苏联向中东扩张，卡特政府强烈谴责这一行动，并对苏联实施小麦抵制。 1980年在莫斯科举行的奥运会遭到美国的抵制。

America's claim to dominant status in the world had been seriously challenged, by the end of the 1970s.

[.my2]
到 20 世纪 70 年代末，美国声称的世界主导地位, 受到了严重挑战。

So, Americans started looking inward, inside themselves, in the hope of feeling better.

[.my2]
因此，美国人开始向内看，向内看，希望感觉更好。


'''

== pure

=== Politics from Camelot to Watergate

Lyndon Johnson hoped to complete Kennedy's work. His Great Society plan declared a "war on poverty" that produced a glut of legislation unseen since the days of Franklin Roosevelt's Hundred Days. Welfare benefits were increased, health care costs were defrayed, and funds were allotted for cleaning the air and water, rebuilding cities, and subsidizing the arts and humanities.

A Civil Rights Act ended legal discrimination in public accommodations with regard to race.

Unfortunately for Johnson, the domestic minded president became mired in a foreign imbroglio — the war in Southeast Asia. Vietnam would taint his legislative successes and end the possibility of a second Johnson term.

By 1968, the zeal for domestic reform was squelched by an increasingly popular war. Families and friends across America were divided by the conflict. Assassinations of Martin Luther King and Robert Kennedy only fanned the flames, and by the end of the decade most Americans were weary of war, rioting, and political crusades — Americans sought a return to normalcy.

'''

==== Kennedy's New Frontier

Domestically, Kennedy continued in the tradition of liberal Democrats Roosevelt and Truman to some extent. He signed legislation raising the minimum wage and increasing Social Security benefits. He raised money for research into mental illness and allocated funds to develop impoverished rural areas. He showed approval for the civil rights movement by supporting James Meredith's attempt to enroll at the University of Mississippi and by ordering his Attorney General, brother Robert Kennedy, to protect the freedom riders in the South.


However, most of Kennedy's more revolutionary proposals languished in the conservative Congress. He wished to protect millions of acres of wilderness lands from developments, but the Congress refused. His efforts to provide federal funds to elementary and secondary schools were denied. His Medicare plan to provide health insurance for the nation's elderly failed to achieve the necessary support. Congress was dominated by a coalition of Republicans and conservative Southern Democrats who refused to expand the New Deal any further.

In his abbreviated Presidency, Kennedy failed to accomplish all he wanted domestically. But the ideas and proposals he supported survived his assassination. Medicare, federal support for education, and wilderness protection all became part of Lyndon Johnson's Great Society.

Lee Harvey Oswald assassinated Kennedy in November, 1963. His death provided a popular mandate for these important programs. In the tumultuous years that followed, many yearned for the happy Kennedy years — a return to Camelot.


'''


==== Lyndon Johnson's "Great Society"


Lyndon Baines Johnson moved quickly to establish himself in the office of the Presidency. Despite his conservative voting record in the Senate, Johnson soon reacquainted himself with his liberal roots. LBJ sponsored the largest reform agenda since Roosevelt's New Deal.

The aftershock of Kennedy's assassination provided a climate for Johnson to complete the unfinished work of JFK's New Frontier. He had eleven months before the election of 1964 to prove to American voters that he deserved a chance to be President in his own right.

Two very important pieces of legislation were passed. First, the Civil Rights Bill that JFK promised to sign was passed into law. The Civil Rights Act banned discrimination based on race and gender in employment and ending segregation in all public facilities.


Johnson also signed the omnibus ECONOMIC OPPORTUNITY ACT OF 1964. The law created the Office of Economic Opportunity aimed at attacking the roots of American poverty. A Job Corps was established to provide valuable vocational training.

Head Start, a preschool program designed to help disadvantaged students arrive at kindergarten ready to learn was put into place. The VOLUNTEERS IN SERVICE TO AMERICA (VISTA) was set up as a domestic Peace Corps. Schools in impoverished American regions would now receive volunteer teaching attention. Federal funds were sent to struggling communities to attack unemployment and illiteracy.

As he campaigned in 1964, Johnson declared a "war on poverty." He challenged Americans to build a "Great Society" that eliminated the troubles of the poor. Johnson won a decisive victory over his archconservative Republican opponent Barry Goldwater of Arizona.

American liberalism was at high tide under President Johnson.

- The Wilderness Protection Act saved 9.1 million acres of forestland from industrial development.

- The Elementary and Secondary Education Act provided major funding for American public schools.

- The Voting Rights Act banned literacy tests and other discriminatory methods of denying suffrage to African Americans.

- Medicare was created to offset the costs of health care for the nation's elderly.

- The National Endowment for the Arts and Humanities used public money to fund artists and galleries.

- The Immigration Act ended discriminatory quotas based on ethnic origin.

- An Omnibus Housing Act provided funds to construct low-income housing.

- Congress tightened pollution controls with stronger Air and Water Quality Acts.

- Standards were raised for safety in consumer products.

Lyndon B. Johnson signs Civil Rights Act
The Civil Rights Act of 1964 was part of Lyndon B. Johnson's "Great Society" reform package — the largest social improvement agenda by a President since FDR's "New Deal."

Johnson was an accomplished legislator and used his connections in Congress and forceful personality to pass his agenda.

By 1966, Johnson was pleased with the progress he had made. But soon events in Southeast Asia began to overshadow his domestic achievements. Funds he had envisioned to fight his war on poverty were now diverted to the war in Vietnam. He found himself maligned by conservatives for his domestic policies and by liberals for his hawkish stance on Vietnam.



By 1968, his hopes of leaving a legacy of domestic reform were in serious jeopardy.



'''

==== Triangular Diplomacy: U.S., USSR, and China

predecessor, RICHARD NIXON longed to be known for his expertise in FOREIGN POLICY. Although occupied with the Vietnam War, Nixon also initiated several new trends in American diplomatic relations. Nixon contended that the communist world consisted of two rival powers — the Soviet Union and China. Given the long history of animosity between those two nations, Nixon and his adviser HENRY KISSINGER, decided to exploit that rivalry to win advantages for the United States. That policy became known as triangular diplomacy.

As President Nixon's national security adviser, Henry Kissinger made a secret trip to arrange the first-ever Presidential visit to China in 1972. He would become Nixon's secretary of state the next year.

As expected, this maneuver caused concern in the Soviet Union. Nixon hoped to establish a DÉTENTE, or an easing of tensions, with the USSR. In May 1972, Nixon made an equally significant trip to Moscow to support a nuclear arms agreement. The product of this visit was the STRATEGIC ARMS LIMITATION TREATY (SALT I). The United States and the Soviet Union pledged to limit the number of intercontinental ballistic missiles each side would build, and to prevent the development of anti-ballistic missile systems.


Arguably, Nixon may have been the only president who could have accomplished this arrangement. Anticommunism was raging in the United States. Americans would view with great suspicion any attempts to make peace with either the Soviet Union or China. No one would challenge Nixon's anticommunist credentials, given his reputation as a staunch red-baiter in his early career. His overtures were chiefly accepted by the American public. Although the Cold War still burned hotly across the globe, the efforts of Nixon and Kissinger led to a temporary thaw.


'''

=== Shaping a New America

As awareness was being raised across America about civil rights for African Americans, it was only natural that other groups who felt marginalized by the American mainstream to make demands of their own. Not since the drive for suffrage had a drive for women's rights met with much success. A new FEMINIST MOVEMENT emerged in the 1960s pressing for modern reforms.

With few exceptions, women were excluded from the highest paying jobs, earning only a fraction of the wages of their male counterparts. The 1950s cult of the housewife discouraged women from holding full-time jobs and from seeking higher degrees. The call for legality and availability of birth control options like the pill galvanized many of feminists. Eventually, the right to obtain a safe, legal abortion became a new milestone. These demands and others led to the proposal of an Equal Rights Amendment to the Constitution, which would forever ban sex discrimination in the nation's laws and practices.



LATINO AMERICANS and NATIVE AMERICANS had also languished in the bottom economic strata throughout much of the prosperous 1950s. Radical and moderate ethnic leaders organized to close this gap. By the end of the decade, the time was ripe for gay Americans to demand equality as well. The politics of identity dominated America as these and other disadvantaged American groups found their voices of protest.

Another battle cry was sounded to save the planet from environmental destruction. Toxic emissions, deadly pesticides, and fears of nuclear holocaust brought many concerned Americans together in the earth awareness movement. This time "GREEN" ACTIVISTS went beyond conservation of resources to demand regulation of economic activities that could hurt the nation's environment.

In the 1960s, the first baby boomers entered college. These students were the largest class of young Americans ever to enter the halls of ivy. Unlike the "Silent Generation" of 1950s youth, the baby boomers were vocal about reforming democracy in the United States and the American presence abroad. College administrators were confronted with inspired students requesting reforms of the core academic curriculum, greater opportunities for free speech, and more relaxed college rules. A small, but highly visible segment of students withdrew from the mainstream and created a counterculture with profound impact on American values, fashion, and music.


'''

=== A Time of Malaise  不适的时期 (1970年代)

Something was terribly wrong in America in the 1970s.

The United States was supposed to be a superpower, yet American forces proved powerless to stop a tiny guerrilla force in Vietnam. Support for Israel in the Middle East led to a rash of terrorism against American citizens traveling abroad, as well a punitive oil embargo that stifled the economy and forced American motorists to wait hours for their next tank of gasoline.

A hostile new government in Iran held fifty-two American citizens hostage before the eyes of the incredulous world. The détente with the Soviet Union of the Nixon years dissolved into bitter animosity when a second arms control agreement failed in the Senate and a Soviet army of invasion marched into Afghanistan. The United States military juggernaut seemed to have reached its limits.



At home, the news was no better. The worst political scandal in United States history forced a president to resign before facing certain impeachment. Months of investigation turned into years of untangling a web of government deceit. Details of illegal, unethical, and immoral acts by members of the White House staff covered the nation's newspapers. Upon resignation, the president was granted a full and complete pardon. Many Americans wondered what happened to justice and accountability.

The booming economy sputtered to a halt. Inflation approached 20% and unemployment neared 10% — a combination previously thought to be impossible. Crime rates rose as tales of the decaying inner cities fell on deaf ears. A nuclear disaster of unspeakable proportions was barely averted at the Three Mile Island fission plant in Pennsylvania.



Many Americans coped with the current ailments by turning inward. Outlandish fashion and outrageous fads such as streaking, mood rings, and pet rocks became common. Younger Americans finished their workweeks and sought escape in discotheques. Controversy surrounding "DECAYING MORALITY" surfaced with regard to increased drug use, sexual promiscuity, and a rising divorce rate. As a result, a powerful religious movement turned political in the hopes of changing directions toward a more innocent time.

The United States celebrated its bicentennial anniversary in 1976 without the expected accompanying optimism. Instead, while many reflected on the past laurels of American success, an overarching question was on the minds of the American people: what had gone wrong?

'''

==== Undoing a President


...By this time, the HOUSE JUDICIARY COMMITTEE had already drawn up ARTICLES OF IMPEACHMENT, and Nixon knew he did not have the votes in the Senate to save his Presidency.

On August 8, 1974, Nixon resigned the office, becoming the first President to do so. His successor, Gerald Ford, promptly awarded Nixon a full pardon for any crimes he may have committed while in office. The press and the public cried foul, but Ford defended his decision by insisting the nation was better served by ending the long, national nightmare.

During his years in office, Nixon had brought a controversial end to the Vietnam War, opened communication with Red China, watched NASA put astronauts on the moon, and presided over a healing period in American history in the early 1970s. Despite these many accomplishments, Watergate's shadow occludes Nixon's legacy.

'''

==== The Sickened Economy


Malaise Noun. 1) An indefinite feeling of debility or lack of health. 2) A vague sense of mental or moral ill-being.

People can feel malaise. Nations can feel malaise. Economies can feel malaise. In the mid-1970s much of America suffered a collective MALAISE.

Nothing fuels a strong case of malaise like a sputtering economy. The United States had grown accustomed to steady economic growth since the end of World War II. Recessions were short and were followed by robust economic growth. For the first time since the Great Depression, Americans faced an economy that could result in a lower standard of living for their children.

Inflation, which crept along at one to three percent for the previous two decades, exploded into double digits. Full employment, defined as unemployment rates of five percent or less, had been achieved in most years since 1945. Now the unemployment rate was nearing the dangerous ten percent line. Americans asked the question: what went wrong?



Economists had long held that inflation and unemployment were polar forces. High inflation meant a great deal of spending; therefore, many jobs would be created. Unemployment created jobless Americans with less money to spend; therefore, prices would stay the same or fall. Surprisingly, the United States experienced high unemployment and high inflation simultaneously in the 1970s — a phenomenon called stagflation. Experts and commoners debated the roots of this problem with differing opinions.

One possibility was the price of oil. When Israel defeated its Arab neighbors in the Yom Kippur War of 1973, Arab oil producers retaliated against Israel's allies by leading the ORGANIZATION OF PETROLEUM EXPORTING COUNTRIES (OPEC) to enact an embargo. Oil prices skyrocketed immediately in the United States as the demand outstripped the supply. Automobiles and drivers sat in long gas lines at service stations.

The price of oil is independent of other factors such as falling worker productivity and foreign competition, which led to greater unemployment. Oil prices also influence the prices of all consumer goods. Products that require oil to produce would now cost more. Any commodity shipped by truck or airplane would pass its new expenses off to the consumer. As the decade progressed, the embargo was lifted, but OPEC steadily raised prices each year. The price of a gallon of gasoline more than tripled from the 1970 to 1980.

Richard Nixon tried to fight inflation first by cutting government spending, but ultimately by imposing wage and price controls on the entire nation. GERALD FORD watched the inflation rate soar above 11 percent in 1974. He enacted a huge propaganda campaign called WHIP INFLATION NOW (WIN), which asked Americans to voluntarily control spending, wage demands, and price increases. The economy, along with Watergate disillusionment, led Ford to suffer defeat at the hands of JIMMY CARTER in the 1976 Presidential election.



Carter tried tax and spending cuts, but the annual inflation rate topped 18 percent under his watch in the summer of 1980. At the same time, the unemployment rate fluctuated between 6 and 8 percent. Economic woes may well have been the decisive factor in Carter's defeat to Ronald Reagan in the election of 1980.


'''

==== Foreign Woes

America sank deeper into malaise when it looked around at what was going on in the rest of the world.

The decade began with America's longest war ending in its first decisive military defeat in its 200-year-history. Diplomacy seemed powerless to stop the economic dependence of the United States on the volatile Middle East for a steady supply of oil. Terrorists from this region and others threatened heads of state and ordinary citizens around the globe. Despite an auspicious start, relations with the Soviet Union deteriorated by the end of the decade.



Terrorism was on the rise around the globe. The world watched in horror as Arab gunmen cut down eleven Israeli weightlifters at the 1972 OLYMPICS in Munich. The IRISH REPUBLICAN ARMY (IRA) killed thousands of English and Irish citizens attempting to receive recognition for their cause — an independent homeland. Americans began to see the world slipping into anarchy and felt powerless to fix the problem.

In 1979, the new Islamic fundamentalist government of Iran captured 52 Americans at the US Embassy in TEHRAN. They demanded the return of their former leader, SHAH MOHAMMED REZA PAHLAVI, to Iran in exchange for the lives of the hostages. For 444 days, Americans watched helplessly as their fellow citizens were held in confinement. A rescue effort ordered by President Carter crashed in the desert in April 1980.




Malaise, malaise, malaise.


One exception to these negative trends was the CAMP DAVID AGREEMENT, brokered by Carter in 1978. These accords resulted in the mutual recognition of Israel and Egypt, a giant first step toward a lasting peace.



But the U.S.-USSR détente arranged by Nixon and Kissinger was crumbling by the end of the decade. A second arms limitation treaty between the superpowers known as SALT II was delivered to the Senate — only to be rejected. The USSR had surpassed the United States in nuclear warheads. The Cold War became frostier.



A Marxist revolution in NICARAGUA brought greater fears of communism spreading to the Western Hemisphere. Finally, in 1979 the Soviet Union invaded AFGHANISTAN with combat troops from the Red Army. Soviet Premier Leonid Brezhnev promised that Afghani leaders had requested military assistance, but American diplomats were dubious.



Fearing Soviet expansion into the Middle East, the Carter Administration strongly condemned the action and levied a wheat boycott on the Soviet Union. The 1980 OLYMPIC GAMES held in Moscow were boycotted by the United States.

America's claim to dominant status in the world had been seriously challenged, by the end of the 1970s.

So, Americans started looking inward, inside themselves, in the hope of feeling better.


'''
