
= 2008年
:toc:

---

== 2008-01

While *still catching-up to men* in some spheres(`=an area of activity, influence or interest; a particular section of society`) of modern life, women *appear to be way(ad.)(`=very far; by a large amount`) ahead* in at least one undesirable(`=not wanted or approved of; likely to cause trouble or problems`) category(`=a group of people or things with particular features in common`). ② “Women *are particularly susceptible(a.)(`=very likely to be influenced, harmed or affected by sb/sth`) to* developing depression and anxiety disorders(`=an illness that causes a part of the body to stop functioning correctly`) 焦虑症候群 *in response to* stress *compared to* men,” *according to* Dr. Yehuda, chief psychiatrist 精神病学家 at New York’s Veteran’s 老兵；退伍军人 Administration Hospital.

====
- *susceptible (a.) ~ (to sb/sth)* : very likely to be influenced, harmed or affected by sb/sth 易受影响（或伤害等）；敏感；过敏 +
=> sus-,在下，向上，-cept,拿，抓住，词源同 accept,capture.引申诸相关比喻义。 +
-> Young people *are the most susceptible(a.) to advertisements*. 年轻人最容易受广告影响。
====

在现代生活的某些领域，女性仍在追赶男性，但至少在一个不受欢迎的领域，女性似乎遥遥领先。“与男性相比，女性在面对压力时更容易患上抑郁症和焦虑症，”纽约退伍军人管理局医院(veterans’s Administration Hospital)的首席精神病学家耶胡达博士(Dr. Yehuda)说。

Studies of both animals and humans *have shown* that sex hormones 荷尔蒙 somehow(ad.)(`= in a way that is not known or certain`) *affect* the stress response 应激反应；压力反应, *causing* females (under stress) *to produce* more of the trigger(`=to make sth happen suddenly 触发`) chemicals *than* do males under the same conditions. ② In several of the studies, when stressed-out(a.)(`=very tense and anxious because of difficulties in their lives`) female rats *had* their ovaries 卵巢 (the female reproductive(`=connected with reproducing babies, young animals or plants`) organs) *removed*, their chemical responses *became equal to* those of the males.

对动物和人类的研究表明，性激素会以某种方式影响应激反应，导致处于压力下的女性比处于相同条件下的男性产生更多的触发化学物质。在几项研究中，当压力过大的雌鼠卵巢(女性生殖器官)被摘除时，它们的化学反应与雄鼠相同。

*Adding to* a woman’s increased dose of stress chemicals, *are* her increased “opportunities” for stress. ② “It’s *not necessarily*(ad.)(`=used to say that sth is possibly true but not definitely or always true 不一定；未必`) that women *don’t cope* as well. ③ It’s just that they *have* so much more *to cope with*,” *says* Dr. Yehuda. ④ “Their capacity for tolerating stress *may even be greater than* men’s,” she *observes*(`=to see or notice sb/sth`), “it’s just that they’re dealing with *so* many more things *that* they become *worn out*(`=to make yourself/sb feel very tired`) from it [more visibly(ad.)(`=in a way that is easily noticeable`) and sooner].”

====
- necessarily : ad. *used to say that sth cannot be avoided* 必然地；不可避免地 +
-> The number of places available *is necessarily(ad.) limited*. 可录学生的名额不可避免地很有限。

- *NOT NECESSARILY* : *used to say that sth is possibly true but not definitely or always true* 不一定；未必 +
-> The more expensive articles are *not necessarily* better. 较贵的东西不见得就较好。

- *wear yourself/sb out* : to make yourself/sb feel very tired 使疲乏；使筋疲力尽；使厌烦
====

对于女性来说，除了产生更多的导致压力的化学物质外，她们产生压力的“机会”也更多。“并不是女性要处理的事情太少(并不是说女性在众多压力之下不能应变自如)，而是她们有更多的事情要处理。”Yehuda博士说道。“她们对于压力的承受能力,有时候甚至比男性的还大”，她观察到，“她们只是需要处理的事情太多，看起来会更容易精疲力尽。”

Dr. Yehuda *notes* another difference between the sexes. “I *think* that {`主` the kinds of things (that women *are exposed to*) `谓` *tend to be* in more of a chronic(`= lasting for a long time; difficult to cure or get rid of`) or repeated nature. ② Men *go to war* /and *are exposed to* combat stress. ③ Men *are exposed to* more acts of random physical violence. ④ `主` The kinds of interpersonal(`=connected with relationships between people`) violence that women *are exposed to* `谓` *tend to be* in domestic(`=used in the home; connected with the home or family`) situations, by, unfortunately, parents or other family members, and they *tend not to be* one-shot(`=is made or happens only once`) deals. ⑤ `主` The wear-and-tear(`=the damage or change that is caused to something when it is being used normally 磨损;损耗`) that *comes from* these longer relationships `系` *can be* quite devastating(a.)(`=causing a lot of damage and destruction`).”}

====
- devastate => de-, 强调，整个的。vast, 广阔的。即整个摧毁。
====

耶胡达博士指出了另一个性别差异。“我认为，女性接触到的这些东西往往是慢性的或反复的。男人上了战场，承受着战斗的压力。男性接触到更多的随机的身体暴力行为。不幸的是，女性接触到的这种人际暴力往往是在家庭环境中，由父母或其他家庭成员实施的，而且往往不是一次性的。来自这种长期的关系的磨合是更有破坏性的。

Adeline Alvarez *married* at 18 /and *gave birth to*(`=to produce a baby or young animal`) a son, but *was determined*(a.) to finish college. ② “I *struggled a lot* to get the college degree. ③ I was living in *so* much frustration(`=the fact that sth is preventing sth/sb from succeeding`) *that* that was my escape, to go to school, and *get ahead* and do better.” ④ Later, her marriage *ended* /and she *became* a single mother. ⑤ “It’s the hardest thing *to take care of* a teenager, *have* a job, *pay* the rent(`=an amount of money that you regularly pay so that you can use a house, etc. 租金`), *pay* the car payment, and *pay* the debt. I *lived* from paycheck to paycheck.”

====
-  *GIVE BIRTH (TO SB/STH)* : to produce a baby or young animal 生孩子；产仔
- I was living in *so* much frustration *that* that was my escape... <- 这里面有个 so...that...结构
====

Adeline Alvarez 18岁结婚并生了个儿子，但她决定完成大学学业。“我尽了很大的努力拿到大学学位，因为我在实际生活中有很多的挫折，而这就是我的逃避，去学校，争取上游，做到更好。”不久后，她离了婚变成一个单亲母亲。“除了照顾一个十几岁的孩子，还要工作，付房租，养车，还债是最难的事情了。我的生活就是不停的支付自己的账单。”

Not everyone *experiences* the kinds of severe chronic stresses (Alvarez *describes*). ② But most women today *are coping with* a lot of obligations(`=the state of being forced to do sth because it is your duty, or because of a law, etc`), with few breaks(`=a short period of time when you stop what you are doing and rest, eat, etc`), and *feeling* the strain. ③ Alvarez’s experience *demonstrates*(`=to show sth clearly by giving proof or evidence`) the importance of *finding* ways *to diffuse(`= to spread sth or become spread widely in all directions`) stress* before it *threatens* your health and your ability to function.

====
- obligation => 前缀ob-这里表to，词根lig-,ligat-表示to bind即捆绑。罗马旧法中，违约的债务人要被五花大绑到债权人眼前接受惩罚。随着罗马法律的完善，这样的形式消失了，但“欠债还钱”的理念还能在这个单词中找到。参考： ligation： [laɪ'geʃən] n. 结扎
- demonstrate => de-, 向下，强调。-monster, 展示，警告，词源同monitor, monster.
====

不是每个人经历着和Alvarez describes一样的长期的压力，但是大多数女性都在处理着太多的责任，很少得到喘息，从而感到了压力。Alvarez的经历证明了，当压力威胁你的健康和正常生理功能之前，解压是非常重要的。

---


== 2008-01 纯净版

While *still catching-up to* men [in some spheres of modern life], women *appear to be way ahead* in at least one undesirable category. “Women *are particularly susceptible to* developing depression and anxiety disorders [*in response to* stress] [*compared to* men],” according to Dr. Yehuda, chief psychiatrist at New York’s Veteran’s Administration Hospital.

Studies of both animals and humans *have shown* that {sex hormones *somehow affect* the stress response, *causing* females (under stress) *to produce* more of the trigger chemicals *than* do males under the same conditions}. In several of the studies, when stressed-out female rats *had* their ovaries (the female reproductive organs) *removed*, their chemical responses *became equal to* those of the males.

*Adding to* a woman’s increased dose of stress chemicals, *are* her increased “opportunities” for stress. “It’s *not necessarily*(ad.) that {women *don’t cope* as well}. It’s just that {they *have* so much more *to cope with*},” *says* Dr. Yehuda. “Their capacity for tolerating stress *may even be greater than* men’s,” she *observes*, “it’s just that {they’re dealing with *so* many more things *that* they become *worn out* from it [more visibly and sooner]}.”

Dr. Yehuda *notes* another difference between the sexes. “I *think* that {the kinds of things (that women are exposed to) *tend to be* in more of a chronic or repeated nature. Men *go to war* and *are exposed to* combat stress. Men *are exposed to* more acts of random physical violence. The kinds of interpersonal violence (that women are exposed to) *tend to be* in domestic situations, by, unfortunately, parents or other family members, and they *tend not to be* one-shot deals. The wear-and-tear (that comes from these longer relationships) *can be* quite devastating}.”

Adeline Alvarez *married* at 18 and *gave birth to* a son, but *was determined* to finish college. “I *struggled a lot* to get the college degree. I was living in *so* much frustration *that* that was my escape, *to go to school*, and *get ahead* and *do better*.” Later, her marriage *ended* and she *became* a single mother. “It’s the hardest thing *to take care of* a teenager, *have* a job, *pay* the rent, *pay* the car payment, and *pay* the debt. I *lived* from paycheck to paycheck.”

Not everyone *experiences* the kinds of severe chronic stresses (Alvarez *describes*). But most women today *are coping with* a lot of obligations, with few breaks, and *feeling* the strain. Alvarez’s experience *demonstrates* the importance of *finding* ways *to diffuse stress* before it *threatens* your health and your ability to function.


---

== 2008-02

It *used to be* so straightforward(`=easy to do or to understand; not complicated`). ② A team of researchers (*working together* in the laboratory 实验室) *would submit* the results of their research *to* a journal(`=a newspaper or magazine that deals with a particular subject or profession`). ③ A journal editor *would then remove* the authors’ names and affiliations(`=a person's connection with a political party, religion, etc`) *from* the paper /and *send it to* their peers *for* review. ④ *Depending on* the comments (received), the editor *would accept* the paper *for* publication or *decline*(`=to refuse politely to accept or to do sth`) it. ⑤ Copyright *rested with*(`= it is their responsibility to do it`) the journal publisher, and researchers (seeking knowledge of the results) *would have to subscribe(`=to pay an amount of money regularly in order to receive or use sth 订阅`) to* the journal.

====
- *rest with sb (to do sth)* : ( formal ) if it rests with sb to do sth , it is their responsibility to do it 是…的责任（或分内的事） +
-> The final decision *rests with the doctors*. 要由医生作出最后决定。
====

原本一切都很简单。一组研究员在实验室里共同完成一个试验，把结果提交给某刊物，刊物的编辑把作者姓名及相关信息隐去，把报告交给这些研究者的同行去审阅。根据评论意见，编辑将决定是否发表。因此，版权留在刊物出版社手上，辛苦探求知识的研究者反倒要花钱订阅刊物。

No longer. `主` The Internet -- and pressure from funding agencies, who *are questioning* {why commercial publishers *are making money from* government-funded research *by restricting access to it*} -- `谓` *is making* access(n.) to scientific results 宾补 a reality. ② _The Organization for Economic Co-operation and Development_ (OECD) 经济合作与发展组织 *has just issued* a report *describing* the far-reaching(`=likely to have a lot of influence or many effects`)  consequences of this. ③ The report, by John Houghton of Victoria University in Australia and Graham Vickery of the OECD, *makes* heavy(ad.)(`=to cause sb/sth to feel uncomfortable or anxious`) reading *for* publishers who *have*, so far, *made* handsome(`=large in amount or quantity`) profits. ④ But it *goes further* than that. ⑤ It *signals*(`=to be a sign that sth exists or is likely to happen`) a change in what *has*, until now, *been* a key element of scientific endeavor(`= an attempt to do sth, especially sth new or difficult`).

====
- *heavy (ad.) ~ on sb/sth* : to cause sb/sth to feel uncomfortable or anxious 使不安；使担忧 +
-> The crime *lay heavy(ad.) on her conscience*. 那件罪行使她内疚不安。
====

现在不再是这样了。提供资金的机构施加压力，质疑为什么商业刊物可以通过限制刊载的手段，从政府投资的研究项目中牟利，互联网使得阅读科研结果成为现实。经济合作及发展组织近日发布一项调查，描述了这一现象所造成的深远影响。澳大利亚维多利亚大学的John Houghton和经合组织的Graham Vickery联合完成这一报告，内容使目前为止收入丰厚的出版商们感到汗颜。但是这项报告的意义远远不止于此，它标志着科学尝试的一项关键性因素即将发生改变。

The value of knowledge and the return(`=the amount of profit that you get from sth`) on the public investment in research *depends, in part, upon* wide distribution(`=the act of giving or delivering sth to a number of people`) and ready(a.)(`=available to be used easily and immediately`) access 轻易获取. ② It is big business. ③ In America, the core scientific publishing market *is estimated* at between $7 billion and $11 billion. ④ The International Association of Scientific, Technical and Medical Publishers *says* that {there *are* more than 2,000 publishers worldwide *specializing in* these subjects}. ⑤ They *publish* more than 1.2 million articles each year in some 16,000 journals.

在某种程度上来说，知识的价值和公共投资能否取得较高回报，取决于是否能够得到广泛的流通、人们是否能够比较容易地获取这些研究成果。这是一项很大的产业。在美国，核心科研出版市场产值, 据估计每年在70亿美元到110亿美元左右。国际科学、技术和医学出版社集团宣称，全世界专业出版本类期刊的出版商有2000多家。他们每年在16000种刊物上发表120万篇以上文章。

This *is now changing*. ② According to the OECD report, some 75% of scholarly(a.)(`=connected with academic study`) journals *are* now online. ③ Entirely new business models *are emerging*; three main ones *were identified(`=to recognize sb/sth and be able to say who or what they are`) by* the report’s authors. ④ There *is* the so-called big deal(`=you mean that it is important or significant in some way`), where institutional subscribers *pay* for access to a collection(`= a group of objects or people`) of online journal titles *through*(`=by means of; because of`) site-licensing(`=to give official permission for the person to do something or for the activity to take place`) agreements. ⑤ There *is* open-access publishing, *typically supported [by* *asking* the author (or his employer) *to pay for* the paper (to be published)]. ⑥ Finally, there *are* open-access archives(`=a collection of historical documents or records of a government, a family, a place or an organization; the place where these records are stored`), where organizations such as universities or international laboratories *support* institutional repositories(`=a place where sth is stored in large quantities`). ⑦ Other models *exist* (that *are* hybrids(`=something that is the product of mixing two or more different things`) of these three), such as delayed open-access, where journals *allow* only subscribers *to read* a paper for the first six months, before *making* it *freely available to* everyone who wishes to see it. ⑧ All this *could change* the traditional form of the peer-review process, at least for the publication of papers.

====
- 本文的主干为Other models exist…。谓语后面是由that引导的定语从句，修饰的是主语Other models。由于定语从句过长，因此该定语从句没有紧跟先行词。
====

这个数字现在有所变化。根据OECD报告，目前有75%的专业期刊在互联网上有在线阅读。全新的商务模式正在形成，报告作者总结出其中三种。 +
第一种是所谓的大订单模式，即机构团体订阅者通过签订网站许可协议,付钱购买阅读一批刊物文章题目的权限。 +
第二种为开放式出版模式，这种方式的典型特点是要求作者（或其雇主）付费发表文章。 +
最后一种为开放式档案模式，即一些组织，比如大学或者国际实验室建立和维护的一些机构数据库。 +
其他的模式都是对这三种的不同组合，比如延期开放式,是指某一些期刊在发表文章的前六个月只允许付费阅览，此后转为免费阅读。至少对论文的发表来说，这些都将颠覆传统的同行审阅模式。

---


== 2008-02 纯净版

It *used to be* so straightforward. `主` A team of researchers *working together* in the laboratory `谓` *would submit* the results of their research *to* a journal. A journal editor *would then remove* the authors’ names and affiliations *from* the paper /and *send it to* their peers *for* review. *Depending on* the comments received, the editor *would accept the paper* for publication /or *decline* it. Copyright *rested with* the journal publisher, and researchers seeking knowledge of the results *would have to subscribe to* the journal.

No longer. `主` The Internet -- and pressure from funding agencies, who *are questioning* why commercial publishers *are making money from* government-funded research *by restricting access to it* -- `谓` *is making* access(n.) (to scientific results) 宾补 a reality. The Organization for Economic Co-operation and Development (OECD) *has just issued* a report (*describing* the far-reaching consequences of this). `主` The report, by John Houghton of Victoria University in Australia and Graham Vickery of the OECD, `谓` *makes* heavy reading *for* publishers who *have, so far, made* handsome profits. But it *goes further* than that. It *signals* a change in what *has, until now, been* a key element of scientific endeavor.

The value of knowledge /and the return on the public investment in research *depends, in part, upon* wide distribution and ready access. It is big business. In America, the core scientific publishing market *is estimated* at between $7 billion and $11 billion. The International Association of Scientific, Technical and Medical Publishers *says* that {there *are* more than 2,000 publishers worldwide *specializing in* these subjects}. They *publish* more than 1.2 million articles each year in some 16,000 journals.

This *is now changing*. According to the OECD report, some 75% of scholarly journals *are* now online. Entirely new business models *are emerging*; three main ones *were identified by* the report’s authors. (1) There *is* the so-called big deal, where institutional subscribers *pay* for access to a collection of online journal titles *through* site-licensing agreements. (2) There *is* open-access publishing, *typically supported by* asking the author (or his employer) to pay for the paper to be published. (3) Finally, there *are* open-access archives, where organizations such as universities or international laboratories *support* institutional repositories. Other models *exist* that are hybrids of these three, *such as* delayed open-access, where journals *allow* only subscribers *to read a paper* for the first six months, before *making it freely available to* everyone who wishes to see it. All this *could change* the traditional form of the peer-review process, at least for the publication of papers.

---

== 2018-03

In the early 1960s Wilt Chamberlain *was* one of only three players in the National Basketball Association (NBA) *listed*(`=to mention or include sth in a list`) at over seven feet 英尺. If he *had played* last season(`=a period in which a play or show, or a series of plays or shows, is performed in one place`), however, he *would have been* one of 42. ② The bodies (*playing* major professional sports) *have changed dramatically*(`=sudden, very great and often surprising`) over the years, and managers *have been more than willing* to adjust team uniforms to fit the growing numbers of bigger, longer frames(`=the form or structure of a person or animal's body`).

在20世纪60年代早期，Wilt Chamberlain是美国国家篮球协会中仅有的身高超过7英尺的三个人之一。可是如果他参加了上个赛季的话，他就变成了42分之一了。这些年来,在较大的职业体育运动中的运动员的身体状况,发生了很大的改变，而他们的经理人也更愿意调整队员的运动服,来适应队员们更大，更高的身材。

The trend in sports, though, *may be obscuring*(`=to make it difficult to see, hear or understand sth`) an unrecognized(`=that people are not aware of or do not realize is important`) reality: Americans *have generally stopped* growing. ② Though typically about two inches taller now *than* 140 years ago, `主` today’s people -- especially those *born to* families (who *have lived in* the U.S. for many generations) -- `谓` *apparently reached their limit* in the early 1960s. ③ And they *aren’t likely to get any taller*. ④ “In the general population today, at this genetic 基因的；遗传学的, environmental level, we’*ve pretty much 几乎; 差不多 gone* as far as we can go,” *says* anthropologist 人类学家 William Cameron Chumlea of Wright State University 莱特(飞机发明者)州立大学. ⑤ In the case of NBA players, their increase in height *appears(系动词) to result(v.) from*(`=to happen because of sth else that happened first`) the increasingly common practice(`=action rather than ideas`) of *recruiting*(`=to find new people to join a company, an organization, the armed forces, etc`) players *from* all over the world.

====
- *be born of/to sb* : V-T PASSIVE When a baby *is born*, it comes out of its mother's body at the beginning of its life. In formal English, if you say that someone *is born of* someone or *to* someone, you mean that person is their parent. 出生 +
-> She was *born into* a very musical family. 她生于音乐之家。 +
-> He was *born of/to* German parents. 他的生身父母是德国人。

- *result : v. ~ (from sth)* : to happen because of sth else that happened first （因…）发生；（随…）产生 +
-> job losses *resulting from* changes in production 生产革新造成的失业

- recruit => re-,再，重新，-cru,生长，成长，词源同 crescent,crew.引申词义吸收，招募新成员。
====

虽然体育界的这种趋势可能蒙蔽了一个没有被承认的现实：美国人基本上停止生长了。虽然现在人们比140年前高了2英寸，特别是那些出生在已移民美国很多代的那些人，但是明显的，在二十世纪60年代早期，已经到达了他们的身高的极限。他们已经不可能再长得更高了。“在这个基因和环境的条件下，现在整体的人们已经长到我们能够达到的范围了，”Wright州大学的人类学家William Cameron Chumlea说道。就NBA球员而言，他们身高的增长似乎是由于从世界各地招募球员的做法越来越普遍。

`主` Growth, which *rarely continues* beyond the age of 20, `谓` *demands* calories 卡路里 (食物的热量单位) and nutrients(`=substances that help plants and animals to grow. 营养物质`) -- notably(`=used for giving a good or the most important example of sth 尤其；特别`) , protein 蛋白质 -- *to feed* expanding tissues(`= a collection of cells that form the different parts of humans, animals and plants`). ② At the start of the 20th century, under-nutrition(n.) 营养不良 and childhood infections (`=an illness that is caused by bacteria or a virus and that affects one part of the body`) *got in the way*(`=to prevent sb from doing sth; to prevent sth from happening`). ③ But *as* diet and health *improved*, `主` children and adolescents(`=a young person who is developing from a child into an adult`) `谓` *have, on average, increased* in height *by about* an inch and a half every 20 years, a pattern *known as* the secular(a.)(`=not connected with spiritual or religious matters`) trend 长期趋势 in height. ④ Yet according to the Centers for Disease Control and Prevention 美国疾病预防和控制中心, `主` average height -- 5′9″ for men, 5′4″ for women -- `谓` *hasn’t really changed* since 1960.

====
- *get in the way of* : to prevent sb from doing sth; to prevent sth from happening 挡…的路；妨碍 +
-> He wouldn't allow emotions *to get in the way of him* doing his job. 他不会让情绪妨碍自己的工作。
- adolescent => 前缀ad-, 去，往。词根ol, 成长，同adult. -esce, 起始动词后缀，即成长中的。
- secular => 词源同 seed,semen.-cul,-culum,工具格后缀，词源同 oracle,hibernacle.比喻用法，即相 比于神和宗教的永恒，种子只有一次生命过程，引申词义世俗的，非宗教的。
- *secular trend* : [经] 长期趋势
====

身高的增长一般在20岁以后就停止了，而发育是需要能量和营养的，其中的蛋白质用来供给组织的生长。在20世纪初，营养不良和儿童疾病妨碍了整体的发育。但是当饮食和健康的促进，儿童和青少年平均每20年都增长了大概1.5英寸，这就是长高的趋势。根据疾病防治中心，从1960年开始，人们的平均身高，男性5英尺9英寸，女性5英尺4英寸，就没有怎么改变了。

Genetically speaking, there *are* advantages *to avoiding* substantial(`=large in amount, value or importance`) height. ② During childbirth(`=the process of giving birth to a baby`), larger babies *have* more difficulty *passing through* the birth canal(`=a tube inside the body through which liquid, food or air can pass`). ③ Moreover, *even though* humans *have been* upright(a.)(`=not lying down, and with the back straight rather than bent`) for millions of years, our feet and back *continue to struggle with* bipedal(a.)(`=using only two legs for walking`) posture(`=the position in which you hold your body when standing or sitting`) /and *cannot easily withstand*(`=to be strong enough not to be hurt or damaged by extreme conditions, the use of force, etc`) repeated strain *imposed by* oversize(`=too big, or much bigger than usual`) limbs(`=肢；臂；腿;四肢`). ④ “There *are* some real constraints that *are set by* the genetic architecture(`=the design and structure of a computer system 体系结构`) of the individual organism(`=a living thing`) 生物个体,” says anthropologist 人类学家 William Leonard of Northwestern University.

====
-
====

总的说来，避免太高的身高是有很多优点的。在生产时，较大的婴儿通过产道是有更多的问题的。而且，就算人类已经直立行走已经几百万年了，我们的脚和背部继续对抗着巨大的压力，这些压力来源于双足直立的姿势和巨大的肢体。“有一些限制是个体器官的基因结构导致的。”西北大学的人类学家William Leonard说道。

Genetic maximums *can change*, but *don’t expect* this *to happen soon*. ② Claire C. Gordon, senior anthropologist at the Army Research Center in Natick, Mass., *ensures* that {90 percent of the uniforms and workstations *fit* recruits 新兵;新成员 without alteration(`=the act of making a change to sth`)}. ③ She *says* that, *unlike* those for basketball, the length of military uniforms *has not changed* [for some time]. ④ And if you *need to predict*(`=to say that sth will happen in the future`) human height [in the near future] *to design* a piece of equipment, Gordon *says* that [by and large 大体上，总的来说], “you *could use* today’s data /and *feel* fairly(`=to some extent but not very`) confident.”

遗传的极限可以突破，但是不要期待很快发生。Mass州的Natick的军队研究中心的高级人类学家Claire C. Gordon确信，百分之九十的入伍新兵不需要更换新的制服和工作站。她说，不像那些篮球制服，军队的制服长度很长时间都没有改变了。如果你需要在不远的将来预测人类的身高而去设计一款新的设备，Gordon说，基本上，“你都能够使用现在的数据，并且觉得非常地自信。”

---


== 2018-03 纯净版

[In the early 1960s] Wilt Chamberlain *was* one of only three players in the National Basketball Association (NBA) *listed* at over seven feet. If he *had played* last season, however, he *would have been* one of 42. The bodies *playing* major professional sports *have changed dramatically* over the years, and managers *have been more than willing to adjust* team uniforms *to fit* the growing numbers of bigger, longer frames.

The trend in sports, though, *may be obscuring* an unrecognized reality: Americans *have generally stopped* growing. Though typically about two inches taller now *than* 140 years ago, `主` today’s people -- especially those *born to* families who *have lived in* the U.S. for many generations -- `谓` *apparently reached* their limit in the early 1960s. And they *aren’t likely to get* any taller. “In the general population today, at this genetic, environmental level, we’*ve pretty much gone* as far as we can go,” *says* anthropologist William Cameron Chumlea of Wright State University. In the case of NBA players, their increase in height *appears to result from* the increasingly common practice of *recruiting* players *from* all over the world.

`主` Growth, which *rarely continues* beyond the age of 20, `谓` *demands* calories and nutrients -- notably, protein -- *to feed* expanding tissues. At the start of the 20th century, under-nutrition and childhood infections *got in the way*. But *as* diet and health *improved*, children and adolescents *have, on average, increased* in height by about an inch and a half [every 20 years], a pattern (*known as* the secular trend (in height)). Yet according to _the Centers for Disease Control and Prevention_, average height - 5′9″ for men, 5′4″ for women -- *hasn’t really* changed since 1960.

*Genetically speaking*, there *are* advantages *to avoiding* substantial height. During childbirth, larger babies *have* more difficulty *passing through* the birth canal. Moreover, even though humans *have been upright* for millions of years, our feet and back *continue to struggle with* bipedal posture /and *cannot easily withstand* repeated strain *imposed by* oversize limbs. “There *are* some real constraints that *are set by* the genetic architecture of the individual organism,” *says* anthropologist William Leonard of Northwestern University.

Genetic maximums *can change*, but *don’t expect* this *to happen soon*. Claire C. Gordon, senior anthropologist at the Army Research Center in Natick, Mass., *ensures* that {90 percent of the uniforms and workstations *fit* recruits [without alteration]}. She *says* that, *unlike* those for basketball, the length of military uniforms *has not changed* for some time. And if you *need to predict* human height [in the near future] *to design* a piece of equipment, Gordon *says* that [by and large], “you *could use* today’s data /and *feel* fairly confident.”

---

== 2008-04

In 1784, five years *before* he *became* president of the United States, George Washington, 52, *was* nearly toothless(a.)(`=having no teeth`). ② So he *hired* a dentist *to transplant*(`=to take an organ, skin, etc. from one person, animal, part of the body, etc. and put it into or onto another`) nine teeth *into* his jaw -- *having extracted* them *from* the mouths of his slaves.

1784，52岁的乔治·华盛顿在成为美国总统5年前，牙齿就几乎已经掉光了。他专门请牙医从他的奴隶口中拔出九颗牙齿种在自己的身上。

That’s a far different image *from* the cherry-tree-chopping George most people *remember* from their history books. ② But recently, many historians *have begun to focus on* the roles (slavery *played* in the lives of the founding(`=relating to the starting of a particular institution or organization`) generation). ③ They *have been spurred(`=to encourage sb to do sth /or to encourage them to try harder to achieve sth`) [in part] by* DNA evidence *made available* in 1998, which *almost certainly proved* Thomas Jefferson *had fathered*(`=to become the father of a child by making a woman pregnant`) at least one child *with* his slave Sally Hemings. ④ And [only over the past 30 years] *have* scholars *examined* history [from the bottom up]. ⑤ Works of several historians *reveal* the moral compromises (*made by* the nation’s early leaders) /and the fragile(a.)(`=easily broken or damaged`) nature(`=the basic qualities of a thing`) of the country’s infancy 婴儿期;初创期. More significantly(`=in a way that is large or important enough to have an effect on sth or to be noticed 有重大意义地；显著地`), they *argue* that {many of the Founding Fathers 开国国父 *knew* {slavery was wrong} -- and yet most *did little to fight it*}.

这跟很多人在历史书上读到过的那个砍樱桃树的华盛顿有点大相径庭。但是最近开始，历史学家开始越来越关注奴隶制在美国开国一代人的生活中所扮演的角色。他们多半是受了1998年DNA事件的影响。那个事件证明托马斯·杰弗逊至少和他的奴隶萨利·赫明思生过一个孩子。学者们从头至尾地研究历史还是近三十年的事情（仅仅在30年前学者们才开始彻底底审视那段历史）。一些历史学家揭示了早期开国者们的道德妥协，和早期国家的不稳定性。更重要的是，他们认为很多开国元勋知道奴隶制是错误的，但是大多数并没有去反抗。

More than anything 最重要的是；主要地, the historians *say*, the founders *were hampered(`=to prevent sb from easily doing or achieving sth`) by* the culture of their time. ② While Washington and Jefferson *privately expressed* distaste(n.)(`=a feeling that sb/sth is unpleasant or offensive`) for slavery, they also *understood* that {it *was* part of the political and economic bedrock(`= a strong base for sth, especially the facts or the principles on which it is based`) of the country they helped to create}.

最主要的原因，就是建国者们受到了当时文化的束缚。当华盛顿和杰弗逊私底下表示对奴隶制的不满时，他们也明白奴隶制同时也是他们努力建造的这个国家的政治经济基础的一部分。

For one thing 首先；一方面, the South *could not afford 支付得起；承担得起（后果） to part with*(`=to give sth to sb else, especially sth that you would prefer to keep`) its slaves. ② Owning slaves *was “like* having a large bank account,” *says* Wiencek, author of An Imperfect(a.)(`=containing faults or mistakes; not complete or perfect`) God: George Washington, His Slaves, and the Creation of America. ③ The southern states *would not have signed* the Constitution *without* protections for the “peculiar(`=belonging or relating to one particular place, situation, person, etc., and not to others （某人、某地、某种情况等）特有的，特殊的`) institution(`=a custom or system that has existed for a long time among a particular group of people （由来已久的）风俗习惯，制度`),” *including* a clause(`=an item in a legal document that says that a particular thing must or must not be done`) that *counted*(`=to consider sb/sth in a particular way; to be considered in a particular way`) a slave *as* three fifths of a man for purposes 目的; 用途 of congressional representation.

====
- afford : v. [ no passive ] ( usually used with can or could , especially in negative sentences and questions 通常与can或could连用，尤用于否定句或疑问句 ) if you say that you *can't afford* to do sth, you mean that *you should not do it because it will cause problems for you if you do* 承担得起（后果） +
-> *We cannot afford* to ignore this warning. 我们对这个警告绝不能等闲视之。

- *part(v.) with sth* : to give sth to sb else, especially sth that you would prefer to keep 放弃，交出（尤指不舍得的东西） +
-> Make sure you read the contract *before parting with any money*. 一定要注意先看清合约,再交钱。

- *peculiar : a. ~ (to sb/sth)* : belonging or relating to one particular place, situation, person, etc., and not to others （某人、某地、某种情况等）特有的，特殊的 +
-> He has *his own peculiar style* which you'll soon get used to. 他有自己独特的风格，你会很快习惯的。 +
=> 在古代，牛是重要的牲畜，也是家庭中最主要的私人财产。在拉丁语中，*pecu表示“牛”，由此产生了peculium（私人财产）*，本意就是“以牛为形式的私人财产”。英语单词peculiar就来自拉丁语peculium，*初始含义就是“专属于某人的，独有的”。与此同源的单词有peculate（盗用、挪用），初始含义就是“据为己有”。* peculiar：[pɪ'kjuːlɪə] adj.特殊的，独特的，奇怪的n.特权，专有财产 peculate：['pekjʊleɪt] v.盗用，挪用（公款） peculation：[,pɛkjʊ'leʃən] n.贪污，挪用公款，侵吞公款

- institution : *a custom or system that has existed for a long time among a particular group of people* （由来已久的）风俗习惯，制度 +
-> *the institution of marriage* 婚姻制度

- *count : v. ~ sb/sth (as) sb/sth +
~ as sb/sth* :  +
to consider sb/sth in a particular way; to be considered in a particular way 认为；看作；算作；被视为 +
-> For tax purposes that money *counts/is counted as income*. 那笔钱算作收入，需要纳税。 +
-> *I count myself lucky* to have known him. 和他相识，我觉得很幸运。
====

一方面，南方各州无法认同废除奴隶制度。如《不完美的上帝：乔治·华盛顿、他的奴隶和美国的建立》一书作者Wiencek所描述，拥有奴隶“就像拥有一笔巨额存款”。如果不保护他们的“特殊制度”，南方各州是不会签署联邦宪法的。“特殊制度”中有一条规定：在选举国会代表时，一个奴隶可算作五分之三个公民。

And the statesmen’s 政治家 political lives *depended on* slavery. ② The three-fifths formula(`=a particular method of doing or achieving sth 公式;方案`) *handed*(`=to pass or give sth to sb`) Jefferson his narrow victory in the presidential election of 1800 by *inflating*(`=to increase in price; to increase the price of sth`) the votes of the southern states in the Electoral College. ③ Once(`=as soon as; when 一…就`) in office, Jefferson *extended* slavery *with* the Louisiana Purchase 路易斯安那购地案 in 1803; the new land *was carved(`=to cut a large piece of cooked meat into smaller pieces for eating`) into* 13 states, *including* three slave states.

政治家的政治生命也取决于奴隶制度。正由于这个五分之三公式，南方选举团的选票扩大了，杰弗逊才在1800大选中险胜。入主白宫之后的1803年，杰弗逊通过购买路易斯安那州扩大了奴隶制度，这片土地后来被划分为了13个州，其中包括3个蓄奴州。

Still(`=continuing until a particular point in time and not finishing 仍然, 还是`), Jefferson *freed* Hemings’s children -- though 虽然；尽管 *not* Hemings herself or his approximately 大概；大约 150 other slaves. ② `主` Washington, who *had begun to believe that* all men *were created equal* after *observing* the bravery of the black soldiers during the Revolutionary War, `谓` *overcame*(`=to succeed in dealing with or controlling a problem that has been preventing you from achieving sth`) the strong opposition(`=strong, angry, or violent disagreement and disapproval`) of his relatives 亲戚;亲属 *to grant*(`=to agree to give sb what they ask for, especially formal or legal permission to do sth`) his slaves their freedom [in his will 遗嘱]. ③ Only a decade earlier, such an act *would have required* legislative approval in Virginia.

然而，杰弗逊还是解放了赫明思的孩子们，虽然没有同样解放赫明思和其他150名奴隶。华盛顿在目睹了美国独立战争中黑人士兵的英勇之后,开始相信人人生就平等。于是，不顾亲属的反对，在遗嘱当中赋予了他的奴隶以自由。而仅仅在那之前的十年，这样的行为在弗吉尼亚还需要得到立法机构的批准。

====
- Only a decade earlier, such an act *would have required* legislative approval in Virginia. <-  would have required *虚拟语气表达*
====

---


== 2008-04 纯净版

In 1784, five years before he *became* president of the United States, George Washington, 52, *was* nearly toothless. So he *hired* a dentist *to transplant* nine teeth *into* his jaw - *having extracted* them *from* the mouths of his slaves.

That’s a far different image from the cherry-tree-chopping George most people *remember* from their history books. But recently, many historians *have begun to focus on* the roles (slavery *played* in the lives of the founding generation). They *have been spurred [in part] by* DNA evidence (*made available* in 1998), which *almost certainly proved* Thomas Jefferson *had fathered* at least one child *with* his slave Sally Hemings. And only over the past 30 years *have* scholars *examined* history [from the bottom up]. Works of several historians *reveal* {the moral compromises *made by* the nation’s early leaders /and the fragile nature of the country’s infancy}. More significantly, they *argue* that {many of the Founding Fathers *knew* slavery was wrong -- and yet most *did little to fight it*}.

More than anything, the historians *say*, the founders *were hampered by* the culture of their time. While Washington and Jefferson *privately expressed distaste for* slavery, they *also understood that* it *was* part of the political and economic bedrock of the country they helped to create.

For one thing, the South *could not afford to part with* its slaves. Owning slaves *was “like* having a large bank account,” says Wiencek, author of An Imperfect God: George Washington, His Slaves, and the Creation of America. The southern states *would not have signed* the Constitution [without protections for the “peculiar institution,”] *including* a clause that *counted* a slave *as* three fifths of a man *for purposes of* congressional representation.

And the statesmen’s political lives(n.) *depended on* slavery. The three-fifths formula *handed* Jefferson his narrow victory in the presidential election of 1800 *by inflating* the votes of the southern states in the Electoral College. Once in office, Jefferson *extended* slavery [with the Louisiana Purchase in 1803]; the new land *was carved into* 13 states, *including* three slave states.

Still, Jefferson *freed* Hemings’s children -- though *not* Hemings herself or his approximately 150 other slaves. Washington, who *had begun to believe that* all men *were created equal* after *observing* the bravery of the black soldiers during the Revolutionary War, *overcame the strong opposition of* his relatives *to grant* his slaves their freedom [in his will]. Only a decade earlier, such an act *would have required* legislative approval [in Virginia].


---


