= 0253
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 253: Traveling by Train.
This is English as a Second Language Podcast episode 253. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Take a look at our website at eslpod.com. We have several new things on the website, including our ESL Podcast Store, which contains additional premium courses that we think you'll be interested in.
This episode is called “Traveling by Train.” It's a conversation between two people talking about train travel in the United States, and some of the vocabulary you need when you take a train. Let's get going!
[start of story]
Katerina: Hey, Joel. Have you ever traveled by train?
Joel: Only once, and that was a long time ago when I lived in Orlando. I’m not even sure where the train station is in this city. Why do you ask?
Katerina: I need to go to San Francisco at the end of May for a friend’s wedding, and I’m thinking about taking a train instead of flying.
Joel: That’s a long trip from Chicago, with a lot of stops. How many days does it take to get there?
Katerina: I just printed out the timetable. Let me see...It looks like it’ll take about four-and-a-half days. I would depart, say, on Tuesday morning and arrive on Saturday afternoon.
Joel: Can I see that? It looks like there are good on-board services, with a dining car and a lounge car on each train.
Katerina: Yeah, I like that. I don’t know if I should go coach or business class. I suppose that’ll depend on the fare. I’ve heard that the sleeping cars are pretty comfortable, too, so I’m glad about that.
Joel: What day of the week do you have to leave?
Katerina: Let me look at the days of operation. This service runs daily, so that’s convenient. I’m going to look online to see how much it’ll cost. It’ll be nice to take a train for a change.
Joel: Let me know what you find out and what you decide. Maybe I’ll look into it for my trip to Washington in September.
[end of story]
Our dialogue between Katerina and Joel begins by Katerina asking Joel if he has “ever traveled by train.” This is an interesting question because very few Americans regularly travel by train anymore, unless they have been on a subway train or a short train that you would use for commuting - going from your house to where you work. This is popular, especially in the eastern cities of the United States; train travel is still more popular there. People who live in the Midwest or the south or the western part of the United States have, probably, less opportunity to travel on a train. Train travel is not as common as it is in other countries.
Joel says he has only been on a train once, “and that was a long time ago when I lived in Orlando.” Orlando is a city in the state of Florida, which is in the southeast part of the United States. Orlando is famous for being the home of Disney World, the park where children go, with Mickey Mouse and Donald Duck. Here in Los Angeles, we have Disneyland, and in Orlando, Florida, they have Disney World.
Joel says that “I’m not even sure where the train station is in this city.” The train station, “station,” is a place where trains stop in a city, and the people who are riding on the train - we would call them passengers, “passengers” - get on and off of the trains at a train station.
Katerina says that she needs “to go to San Francisco” for a friend of hers wedding, and she's “thinking about taking a train instead of flying.” Now, Katerina lives in Chicago, which is in the middle of the United States. San Francisco is on the west coast, here in California.
Joel says, “That’s a long trip from Chicago, with a lot of stops.” A stop, “stop,” is a place where the train stops to let passengers off and new passengers on. How long “does it take to get there,” Joel asks - “How many days?”
Katerina says that she printed out a timetable. A timetable, “timetable,” (one word) is a list that tells you when trains leave and when they arrive at different cities. It gives you the times for the trains' departures, we would call them - when they leave - and arrivals - when they get there. You can have a timetable for a train; you can have a timetable a bus.
Katerina looks at the timetable and says it takes “four-and-a-half days” to go from Chicago to San Francisco, which is true, that is how long it takes because it is such a long distance. Katerina says that she “would depart on Tuesday morning and arrive on Saturday afternoon.” To depart, “depart,” means to leave a place. We use that verb for planes or trains, cars - mostly for planes and trains though. “I'm going to depart at four in the afternoon” - that's what time my train leaves. To arrive is to get somewhere. “What time do you arrive in New York” - what time does your plane get there?
Joel asks to take a look at the timetable, and says that there seems to be “good on-board services.” On-board, “board,” means things that are on the train that you can use on the train while you are traveling on the train. A dining car is a place where you eat. The verb to dine, “dine,” is a little more formal word meaning to eat. So, a dining car is a section in the train where you can get food. This train also has a lounge car. A lounge, “lounge,” car is a section with comfortable chairs, things to read, maybe some drinks for the passengers - it's a place to relax on the train.
Katerina says that she doesn't know if she “should go coach or business class.” Coach, “coach,” is the least expensive seat on a train or a plane. It's also, usually, the least comfortable. So, if you travel coach you can save money, but it's not the most comfortable way to travel.
Business class is the most expensive, or one of the most expensive ways to travel on a train or a plane, but it is more comfortable. In some planes, you have coach class, or the coach seats; you have business class, and then you have an even more expensive area called first class. Sometimes planes just have two classes - a coach and a first class. Different companies call them different things.
Katerina says it will “depend on the fare,” as to which class she rides. A fare, “fare,” is the price of the ticket, either for a bus, a train, or a plane. If it's a plane, we would call it airfare, but fare, in general, is the amount of money you pay for a ticket.
Katerina says that there are sleeping cars, which are pretty comfortable, on the train as well. As you can guess, a sleeping car is a section of the train where you have beds for sleeping.
Joel says, “What day of the week do you have to leave?” What day of the week means Monday, Tuesday, Wednesday, Thursday, Friday, Saturday or Sunday. So, which of those days “do you have to leave?”
Katerina says that she will “look at the days of operation” on the timetable. The days of operation are the days when a business is open - when you can use the services of the business. She says that “This service” - this train - “runs daily.” So, it leaves Chicago once a day, or at least once a day.
She says that it would “be nice to take a train for a change.” For a change means, here, as something different - as something unusual - something that you don't normally do. And, if you are traveling a long distance in the United States, you certainly do not normally take a train.
Joel says that he might want to take a train the next time he travels. He says, “Maybe I’ll look into it.” To look into something is to investigate or to research something. To learn more about something is to look into something.
Now let's listen to the dialogue, this time at a native rate of speech.
[start of story]
Katerina: Hey, Joel. Have you ever traveled by train?
Joel: Only once, and that was a long time ago when I lived in Orlando. I’m not even sure where the train station is in this city. Why do you ask?
Katerina: I need to go to San Francisco at the end of May for a friend’s wedding, and I’m thinking about taking a train instead of flying.
Joel: That’s a long trip from Chicago, with a lot of stops. How many days does it take to get there?
Katerina: I just printed out the timetable. Let me see...It looks like it’ll take about four-and-a-half days. I would depart, say, on Tuesday morning and arrive on Saturday afternoon.
Joel: Can I see that? It looks like there are good on-board services, with a dining car and a lounge car on each train.
Katerina: Yeah, I like that. I don’t know if I should go coach or business class. I suppose that’ll depend on the fare. I’ve heard that the sleeping cars are pretty comfortable, too, so I’m glad about that.
Joel: What day of the week do you have to leave?
Katerina: Let me look at the days of operation. This service runs daily, so that’s convenient. I’m going to look online to see how much it’ll cost. It’ll be nice to take a train for a change.
Joel: Let me know what you find out and what you decide. Maybe I’ll look into it for my trip to Washington in September.
[end of story]
Our dialogue was written by Dr. Lucy Tse.
If you have a question or comment, you can email us at eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
train station – the place where trains stop in a city and passengers get on and off the trains
* We have to take Keiko to the train station at 4:20 for her 5:00 train.
stop – a place where a train stops to let passengers on and off
* When you take a train from Seattle, Washington, to Eugene, Oregon, there are stops in Portland and Salem.
timetable – a chart that shows when trains leave and arrive in different cities
* According to this timetable, a train leaves for Philadelphia every hour.
to depart – to leave a place
* My travel agent told me that I should arrive at the airport two hours before my plane departs.
to arrive – to come to a place
* When Shelly arrives at the airport, we’ll be waiting for her with lots of flowers.
on-board services – things provided while one is on a train, plane, or ship, such as food, drinks, movies, and things to read
* I wish that this train’s on-board services included massages!
dining car – one section of a train that has tables and chairs and is a restaurant for the passengers
* The food in the dining car is very expensive, so I always bring a sandwich when I travel by train.
lounge car – one section of a train with comfortable chairs, things to read, and drinks for the passengers
* When they got tired of sitting in their regular seats, they went to the lounge car for a glass of wine.
coach – the least expensive, least comfortable seats on a train or plane
* Timothy is very tall, so he doesn’t like sitting in coach because there isn’t enough space for his long legs.
business class – a more expensive section of a train or plane, with comfortable seats
* Tobias paid extra to travel in business class, where he got free drinks and was able to sleep in a comfortable seat.
fare – the price of a bus, train, or plane ticket
* I’m told that airline fares are less expensive if you buy your ticket online.
sleeping car – one section of a train where passengers have beds instead of chairs
* When my friend Aaron visited Russia, he travelled from Moscow to Vladivostok by train in a sleeping car, because the trip lasted for an entire week.
day of the week – one of the seven days of the week: Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, or Saturday
* What days of the week is your exercise class? Mine is on Tuesday, Thursday, and Saturday.
days of operation – the days when a business is open or a service is available
* This store’s days of operation are Monday through Friday. It’s closed on the weekend.
for a change – as something different; as something unusual
* Tricia always brings her lunch to work, but today, she’s going to go to a restaurant for a change.
to look into (something) – to research something; to learn more about something
* Nicole wants to look into studying in another country next semester.
Comprehension Questions
1. How will Katerina decide between coach and business class?
a) It will depend on whether there are sleeping cars.
b) It will depend on the price.
c) It will depend on the on-board services.
2. How will Katerina find out how much the train costs?
a) She will print out the timetable.
b) She will go to the train station.
c) She will look on a website.
Answers at bottom.
What Else Does It Mean?
coach
The word “coach,” in this podcast, means the least expensive, least comfortable seats on a train or plane: “If you want to save your money for the rest of your trip, I suggest traveling coach.” A “coach” is also a box with four wheels that is pulled by a horse and was used to carry people in the old days before we had cars: “This coach is very noisy. Let’s try to sit in a coach with fewer people next time.” A “coach” can be a person who trains someone or who helps someone get better at doing something: “Benjamin is a coach for his son’s baseball team.” Or, “Gina now has a life coach who helps her make the right decisions about her work and her personal life.” As a verb, “to coach” means to train someone or help someone get better at doing something: “Mr. Dubois has coached many famous athletes, and some of them have competed in the Olympics.”
to look into (something)
In this podcast, the phrase “to look into (something)” means to research something or to learn more about something: “The company is looking into the costs of moving to a bigger office building.” The phrase “to look over (something)” means to review something to see how good it is: “Can you please look over my math homework and see if I did it correctly?” The phrase “to look up (something)” means to search for something in a dictionary, telephone directory, or any other kind of reference book: “I lost Cameron’s phone number, so I have to look it up in the phone book.” Finally, the phrase “to look through (something)” means to quickly read something: “I like to look through my notes right before an exam.”
Culture Note
In the United States, most people travel by car or plane. Traveling by train is not very common. However, there is a well-known company called Amtrak that has trains all over the country and even in Canada. Some people like to travel by train because they can enjoy the “scenery” or the beautiful views while they travel. The “tracks” (the pieces of metal that a train travels over) are usually far from roads for cars, which means that the scenery is nicer than what one sees from a car. However, traveling by train is very slow and often the tickets are almost as expensive as plane tickets. That’s why people with a lot of money and little time usually choose to travel by plane or car.
Sometimes Amtrak offers “special deals” or low prices on certain train “routes” or trips from one city to another. Amtrak also offers lower prices to students, children, and “senior citizens” (people who are more than 65 years old). People who travel frequently can sometimes get free train tickets. For example, if they take three “round-trips” (trips that go to a place and then come back) on a train, they can take a fourth round-trip for free.
When you travel by train, it is important to choose the right type of seat. You can choose between inexpensive coach seats or more expensive and more comfortable seats in business class. You can also choose to sit in a “quiet car” where people are not allowed to speak loudly or use cell phones or anything else that makes noise. Sometimes you can choose to sit in a section where there is “entertainment” such as movies, music, or lectures by “park rangers,” the people who work in US parks, about the scenery.
Comprehension Answers
1 - b
2 - c