= 0254
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 254: Good Hygiene.
This is English as a Second Language Podcast episode 254. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the beautiful City of Los Angeles, California.
Remember to visit our website at eslpod.com; we have some new things on our website. Of course, we have the Learning Guide, and eight to ten page guide for this episode that will help you improve your English even faster.
Our dialogue today is called “Good Hygiene,” and it's about keeping clean so that you don't get sick. Let's listen.
[start of story]
Juanita: Hey, where have you been? I was going to invite you to lunch, but you weren’t at your desk.
Bill: I was at a training.
Juanita: What was it on?
Bill: Office hygiene.
Juanita: Hygiene? You’re kidding. Your office is pretty messy but I wouldn’t say you needed hygiene training.
Bill: Very funny. Each department has to go through it. You’ll have your turn next week. Apparently, the management wants to reduce the spread of illnesses around the office. They say that people are taking too many sick days and it’s bad for productivity.
Juanita: So, we all have to sit through a training. What a pain! It’s not like we don’t know how to wash our hands.
Bill: Yeah, I know. The trainer did a pretty good job, though, explaining how germs spread around the office. It’s easy to infect other people when you have a cold or something else that’s contagious. She said that viruses get around pretty easily. She gave us some pointers on how to prevent it, though.
Juanita: Well, I use antibacterial soap all the time, so I don’t worry about it.
Bill: You know, the trainer said that those soaps may not be that effective. People think they’re sterilizing their hands, but they may be doing more harm than good.
Juanita: Really? I’ve never heard that before.
Bill: Then you’d better go to the training. I guess you need it more than I do.
Juanita: Yeah, very funny.
[end of story]
Our dialogue begins with Juanita asking Bill, “where have you been? I was going to invite you to lunch, but you weren’t at your desk.”
And, Bill says where he was. He says he “was at a training.” A training, “training,” is a class, what we might also call a workshop, “workshop,” to learn something. Usually it is something that is sponsored by or presented by your company or some business organization. We talk about trainings at your job; you go for, maybe, an hour, sometimes a whole day or longer to learn something new about your job.
Juanita asks what the training was on. She says, “What was it on?” She's asking what was the topic of the training - what was the training about.
Bill says, “Office hygiene.” Hygiene, “hygiene,” means being clean, particularly being clean to avoid sickness - being clean for health reasons. You want to be clean, and you want the area where you are eating and cooking to be clean. Good hygiene, in general, refers to making sure that you are washing your hands for example, and brushing your teeth, and combing your hair - if you have hair. I don't worry about that one! So, good hygiene is related, in general, to being clean, especially being clean so that you don't get sick.
Juanita says, “You’re kidding.” She doesn't believe Bill; she thinks Bill is joking or, at least, she thinks that it is a strange topic for a training. She then makes a joke by saying, “Your office is pretty messy but I wouldn’t say you need hygiene training.” Messy, “messy,” means dirty or disorganized. Something that is a mess is something that is not organized - it's not clean. Juanita is making a joke here, saying that because Bill has a dirty office - a messy office - he needs to have hygiene training - training to learn how to keep himself clean.
Bill says, “Very funny.” That expression, “very funny,” is when someone tells a joke, but you don't think it's funny. It's a weird expression because you are saying the opposite, but in fact, when someone says, “Very funny,” especially like that - that intonation, “very funny” - they mean that's not funny - I don't think that's funny.
Bill says that “Each department has to go through” the training, meaning each department has to have the training. “You’ll have your turn next week,” Bill says. Your turn, “turn,” means the time when you have to do something. It could be in a game or some series of events. So for example, you have to talk to your boss about how you did last year on your job, and everyone in the office has to talk to the boss. So, each person will have a turn to talk to the boss. They'll have a turn - they'll have an opportunity to go and speak with him or her.
We use that word, “turn,” in lots of different ways; take a look at the Learning Guide for this episode for more explanations about that.
Bill then says, “Apparently, the management wants to reduce the spread of illnesses around the office.” Apparently, “apparently,” is a common expression that we use to mean it appears - it seems - based on what I have seen or heard, this is my impression - this is what I think, but you're not sure. You don't have, perhaps, all of the information so you're sort of guessing.
“Apparently, the management” - the bosses - “want to reduce,” or lower, “the spread of illnesses.” Spread, “spread,” means something that grows - it's the growth of something - or, it's when something moves and becomes larger or greater in number. “The spread of the Internet around the world has been great in the last five years,” meaning the number is getting bigger - more and more people are using it.
In this dialogue, Bill says, “the spread of illnesses,” meaning that illnesses - when people are sick - can increase, and “the management wants to reduce the spread,” they want fewer people getting sick. Spread is another one of those words that has many different meanings; take a look, again, at the Learning Guide for more information.
Bill says that “people are taking too many sick days and it’s bad for productivity.” A sick, “sick,” day (two words) is a day when an employee does not go to work because she does not, or he does not, feel well - they're sick, but the company still pays them. Most companies give you a certain number of sick days every year. So for example, if you have five sick days each year, that means that you can call and say you're sick and stay home and still be paid for that day five times. After that, you may not be paid for the days you are sick.
Juanita says that the training is not going to be something she wants to do. She says, “What a pain!' What a pain, “pain,” is an expression to mean how annoying or how frustrating - that's very frustrating or that's very inconvenient - that's something that I don't want to do. You can also use that expression, “a pain,” in talking about a person. You can say, “He's such a pain,” meaning he's such an annoyance - he's someone who bothers me.
Juanita says that we already “know how to wash our hands,” so why do we need to go to this training - that's what she's trying to say. Bill says, however, that “The trainer” - the person who gives the training is called a trainer - “did a pretty good job explaining how germs spread around the office.” Germs, “germs,” are very small things in the air or in the water that you can't see, but that make people's sick. The germs are how the disease - how the illness - spreads - how more people get it.
He says that “It’s easy to infect other people when you have a cold or something else that’s contagious.” The verb, to infect, “infect,” means to make someone sick - to give your disease or illness to someone else. There are different ways of infecting people. One way is when people breathe the air or they put their hands that have germs on them in their eye, for example, and that can give you that illness. This is especially true with something like a cold. A cold, of course, is a kind of illness you have where your nose may hurt, you may have a headache, your throat may hurt.
Diseases that spread - that you can get from other people - are called contagious diseases, “contagious.” Something that is contagious is something that can be passed from one person to another, and there are many diseases like that.
Bill says that the trainer gave the people at the training “some pointers on how to prevent” being infected. Pointers, “pointers,” is another way of saying tips or advice or suggestions. You may say to someone, “Can you give me some pointers on how to use my new computer” - can you give me some advice - can you give me some tips? To prevent, “prevent,” means to stop something from happening - to stop it before it happens.
Juanita says that she uses “antibacterial soap all the time,” so she doesn't worry about getting sick. Antibacterial, “antibacterial,” soap is a kind of soap that is used to wash your hands, and it's supposed to kill the germs - kill the things that will make you sick. There's been a lot of controversy about antibacterial soap at hospitals in the United States. Some people think that it may help create new types of bacteria that we don't have drugs to treat or to help.
Juanita says that she uses antibacterial soap; Bill says that “the trainer said that those soaps may not be that effective.” He says that “People think they’re sterilizing their hands, but they may be doing more harm than good.” To sterilize, “sterilize,” in this case means to kill all of the germs on something - to use some sort of chemical or soap that you kill the germs. Notice we use that expression, “to kill germs,” mean to get rid of them.
Bill says that using these antibacterial soaps “may be doing more harm than good.” To do more harm, “harm,” than good means that something is more negative than it is positive - something has more disadvantages than advantages. Harm means something bad - something that hurts you, and is the opposite of good. So, you're saying that you are hurting yourself more than you're helping yourself.
The dialogue ends with Bill saying that Juanita needs the training more than he does, so he tells a joke back, and Juanita uses the same expression. She says, “Yeah, very funny,” meaning I don't think that's funny.
Now let's listen to the dialogue again, this time at a normal speed.
[start of story]
Juanita: Hey, where have you been? I was going to invite you to lunch, but you weren’t at your desk.
Bill: I was at a training.
Juanita: What was it on?
Bill: Office hygiene.
Juanita: Hygiene? You’re kidding. Your office is pretty messy but I wouldn’t say you needed hygiene training.
Bill: Very funny. Each department has to go through it. You’ll have your turn next week. Apparently, the management wants to reduce the spread of illnesses around the office. They say that people are taking too many sick days and it’s bad for productivity.
Juanita: So, we all have to sit through a training. What a pain! It’s not like we don’t know how to wash our hands.
Bill: Yeah, I know. The trainer did a pretty good job, though, explaining how germs spread around the office. It’s easy to infect other people when you have a cold or something else that’s contagious. She said that viruses get around pretty easily. She gave us some pointers on how to prevent it, though.
Juanita: Well, I use antibacterial soap all the time, so I don’t worry about it.
Bill: You know, the trainer said that those soaps may not be that effective. People think they’re sterilizing their hands, but they may be doing more harm than good.
Juanita: Really? I’ve never heard that before.
Bill: Then you’d better go to the training. I guess you need it more than I do.
Juanita: Yeah, very funny.
[end of story]
The script for today's podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
training – a class or workshop to learn something, usually where one works
* Everyone in that department is going to a computer training on Thursday.
hygiene – cleanliness for health; being clean to avoid sickness
* One thing the manager of the restaurant requires of its employees is very good hygiene.
messy – dirty and disorganized
* Annette won’t let her children play until they finish cleaning their messy rooms.
turn – the time when a person has to do something, usually during a game or a series of events
* In Mishka’s office, all the workers take turns bringing dessert for the department on Fridays.
apparently – it appears; seemingly; it seems; based on what one sees or hears but without detailed information.
* Apparently, the storms in Florida destroyed a lot of orange trees, because oranges are much more expensive this year.
spread – the growth of something; the movement of something that is becoming larger or greater in number
* In the last decade, there has been a surprising spread in the use of cellular phones in all countries.
sick day – a day when an employee does not come to work because he or she does not feel well, but is still paid their salary
* You’re supposed to use sick days when you feel sick, but sometimes people use them as extra vacation days.
What a pain! – an expression meaning “How annoying!” or “That’s frustrating!”
* I lost my homework, so now I have to do all the math problems again. What a pain!
germ – a very small thing in the air and water that cannot be seen by one’s eyes that can make people sick
* Washing your hands with soap and hot water can help to kill germs.
to infect – to pass a disease or illness to someone else; to cause someone else to get sick when one is sick
* If you share a glass with someone who is sick, you might get infected.
contagious – a disease or illness that can be passed from one person to another
* When you have a cold that’s contagious, the boss wants you to stay home so that you don’t make other people sick
virus – a very small thing that cannot be seen by one’s eyes that can make people sick
* AIDS is caused by a virus known as HIV.
pointer – tips, ideas, or suggestions for doing something
* Johann gave me some pointers on how I could start running faster.
to prevent – to stop something from happening; to stop something before it happens
* The police are trying to prevent crime by walking along the streets at night.
antibacterial soap – a bar of soap used to wash one’s hands and kill the things that make one sick
* This antibacterial soap is very strong and it makes my skin dry, but I use it to kill germs.
to sterilize – to kill all the germs on something
* In a hospital, doctors and nurses must sterilize all of their tools and instruments before using them on patients.
to do more harm than good – to be more negative than positive; to have more disadvantages than advantages
* Shelby tried to clean the wine from her sweater, but she did more harm than good and now the mark is bigger than before.
Comprehension Questions
1. Why doesn’t Juanita want to go through the training?
a) She thinks it will be painful.
b) She thinks the information will be too basic.
c) She thinks she’ll get infected by sick people.
2. According to Bill, why is management providing the training?
a) Because many people aren’t coming to work because they’re sick.
b) Because people aren’t using the antibacterial soap in the bathrooms.
c) Because people need to learn to point to germs and viruses.
Answers at bottom.
What Else Does It Mean?
turn
The word “turn,” in this podcast, means the time when a person has to do something, usually during a game or a series of events: “Whose turn is it to wash the dishes tonight?” We use it with the verb “to take”: “The mother asked her children to stop fighting over the new toy and take turns playing with it.” As a verb, “to turn” means to move one’s body or head to the right or left: “She turned her head toward the window to look at the people walking by the restaurant.” The verb “to turn” can also mean to move a car to the right or left: “Turn right after the library and then turn left onto 42nd Street.” Finally, “to turn” means to move one page in a book, magazine, or newspaper so that one can read the next page: “Please turn to page 17.” Or, “When I turned the page of the photo album, I saw a funny picture of Grandpa when he was young.”
spread
In this podcast, the word “spread” means the growth of something or the movement of something that is becoming larger or greater in number: “The spread of nuclear bombs is frightening.” The verb “to spread” means to grow or become greater in number: “The popularity of short skirts spread from California to everywhere in the country.” The verb “to spread” also means to use a knife to put a layer of butter, jam, or a similar food on a piece of bread: “Ivan likes to spread butter on his croissant before he eats it every morning.” The word “spread” is also used to talk about the difference in the number of points earned by the winning and losing team in a game: “The Giants won by a 14-point spread.”
Culture Note
In the United States, many people are worried about the quality of food that they buy at stores and eat in restaurants. They are worried that the food may be “contaminated” by the people who made it, meaning that the workers’ or factories’ germs are in the food. To prevent contamination, there are many state laws that try to improve the hygiene of “food service workers,” who are people who prepare food for stores or in restaurants.
The laws in most states require that food service workers wash their hands with warm water and soap after using the bathroom and before touching food or kitchen tools. Many food service workers also must wear “gloves” or pieces of plastic that cover their hands. The gloves prevent germs from moving from the workers’ hands to the food and also protect the workers’ hands from “sharp” (dangerously pointed objects) that could cut them. Most food workers are required to wear a “hair net” or a small piece of fabric that covers one’s head and prevents one’s hair from falling into the food.
Food service workers are not supposed to go to work when they are sick. If they become sick while they are working, they should go home as quickly as possible.
State “agencies” (government offices or departments) often send “health inspectors” to restaurants and other places where food is prepared. These inspectors look for “violations” or things that do not follow the laws. When they find violations, the restaurant has to pay a “fine,” giving money to the government as punishment. They also must agree to prevent the problem from happening again in the future.
Comprehension Answers
1 - b
2 - a