= 0271
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 271: Using an ATM.
Welcome to English as a Second Language Podcast episode 271. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com. Take a look at the many new features we now have on our website, including our ESL Podcast Store, where you can download additional premium courses that you may be interested in. We have daily English courses, business courses, and others.
This podcast is called “Using an ATM.” An “ATM” is an automatic teller machine. It's a machine where you get money out of by putting a bankcard in. We'll be listening to a dialogue between Robin and someone who works at the bank about using the ATM card and some problems you sometimes have. Let's get started.
[start of story]
I went to bank this morning. Instead of standing in line to talk to a bank teller, I decided to use an ATM, but it wasn’t working.
Robin: Excuse me. Could you help me? I’m trying to use this ATM machine, but it stopped working after I put in my PIN and it won’t give me back my ATM card.
Bank clerk: It looks like the machine is jammed. Step over to this teller window and I can help you. What transactions are you trying to make?
Robin: I want to make a deposit, transfer some money between my checking and savings accounts, and make a cash withdrawal.
Bank clerk: I can make those transactions for you.
Robin: Okay. Let me take this check out of the deposit envelope. And what about my card?
Bank clerk: I’ll call the technician and she should be able to retrieve it for you.
Robin: Thanks a lot. I guess that the machine just doesn’t like me.
Bank clerk: It’s not you. Those machines just act up sometimes.
Robin: In that case, I won’t take it personally.
[end of story]
Our dialogue begins with Robin saying that she went to a bank this morning, and instead of standing in line, or waiting in line, to talk to a bank teller, she decided to use an ATM. A “bank teller” (teller) is the person who works at the bank who helps you: gives you money; cashes your check. The person who helps the customers is usually called a “bank teller.” Well, she does not want to use a bank teller, so she's going to use an automatic teller machine, or what we call an “ATM” normally.
The problem with the ATM was that it wasn't working. Robin then goes up to one of the bank tellers, or bank clerks, and says, “Excuse me. Could you help me? I’m trying to use this ATM machine, but it stopped working after I put my PIN in and it won’t give me back my ATM card.” A “PIN” (PIN) stands for personal identification number, and this is your password or pass code that allows you to tell the machine that it's really you; it helps identify you. So, if someone steals your card, they can't get your money unless they know your PIN. Well, Robin entered her PIN into the machine, and the machine did not give her her card back. It also did not give her her money! The card we call an “ATM card.”
The clerk says that it looks like the machine is jammed. When we say “a machine is jammed” (jammed), we mean that something has stopped working in the machine; it doesn't do what it's supposed to do. Normally we use this verb when we are talking about papers getting caught in a machine, so that the machine doesn't work properly. For example, if you have a fax machine and you have a piece of paper that isn't perfectly straight, it may jam in the machine, or get jammed in the machine, meaning it will not go through the machine properly and cause the machine to stop working correctly. Well, this is what happened with Robin's ATM card; it got jammed in the machine, according to the teller.
The teller says, “Step over to this teller window and I can help you.” The “teller window” is the place where the individual bank teller works. Usually they are standing on the other side of a counter that separates you from the bank teller. In many banks in the United States, you will also be separated by a thick piece of glass for security reasons.
The teller asks Robin, “What transactions are you trying to make?” “Transactions” (transactions) are any time you take money out of your bank or put money into your bank, or do anything with your bank involving your money; that would be a transaction. It's a more general term to talk about anything that goes on between two people that involves money. When you buy a new car, we could call that a “transaction.” You give someone money and they give you a car. Hopefully, the car will work!
Robin says that she wants to make a deposit, transfer some money between her checking and savings accounts, and make a cash withdrawal. So, three things here: first, Robin wants to “make a deposit” (deposit), meaning she wants to put some money into her account – give the bank some of her money. “To transfer” (transfer) means to move money from one account that you have at the bank, to another. An “account” is simply the name we give the agreement that you have with the bank for them to keep your money.
Moving money from one account to another account, then, is a transfer; that's the second thing Robin is doing. She's transferring between her checking and her savings accounts. A “savings account” is when you put money into your bank, and you can only take it out if you go to the bank, normally, or you go online and transfer it. A “checking account” is an account that you can take money out of by writing a check, usually a piece of paper that you sign, and you put the amount that you want to take out of your account and the name of the person to whom you are giving the money. That would be a checking account.
The third thing Robin wants to do is make a cash withdrawal. The verb “to withdraw” (withdraw) means to take out of; to remove something. So, a “withdrawal,” as a noun, is when you take your money out. In this case, she wants to take some cash out of her account.
The bank teller says that he can help Robin. Robin says, “Okay. Let me take this check out of the deposit envelope.” The “deposit envelope” is the place where you put your check or money that you are going to put into the ATM machine. But since the ATM machine isn't working, she is going to take it out of the deposit envelope and give it to the teller. Notice here that we sometimes say “ATM machine,” even though ATM means automatic teller machine. So it's like saying, “automatic teller machine machine,” but we often say it like that.
The bank clerk says that he is going to call a technician in order to get the card out of the ATM machine – Robin's card, that is. A “technician” (technician) is a person and fixes things. Usually a person who fixes certain kinds of machines is called a “technician.” The technician is going to retrieve Robin's card. “To retrieve” (retrieve) means to take out of something, usually something that has been lost or something that is difficult to get. You can retrieve something from your closet, for example. In this case, the technician will retrieve Robin's card from the ATM machine so she can get it back.
Robin thanks the bank clerk, and says, “I guess that the machine just doesn’t like me.” She's making a joke – the machine doesn't like her. And the bank clerk says, “It’s not you. Those machines just act up sometimes.” The verb “to act up” (two words) means to cause problems. When something doesn't work correctly, we would say it's “acting up.” For additional definitions of this expression, “to act up,” take a look at the Learning Guide for this episode.
Finally Robin says, “In that case,” meaning if that is true that the machines sometimes act up, then “I won’t take it personally.” When you “take something personally,” you are offended; you believe that something happened to you, usually a negative thing, for a personal reason. In this case, Robin should not take it personally; she should not think that the machine was trying to get her in particular.
Now let's listen to the dialogue, this time at a normal speed.
[start of story]
I went to bank this morning. Instead of standing in line to talk to a bank teller, I decided to use an ATM, but it wasn’t working.
Robin: Excuse me. Could you help me? I’m trying to use this ATM machine, but it stopped working after I put in my PIN and it won’t give me back my ATM card.
Bank clerk: It looks like the machine is jammed. Step over to this teller window and I can help you. What transactions are you trying to make?
Robin: I want to make a deposit, transfer some money between my checking and savings accounts, and make a cash withdrawal.
Bank clerk: I can make those transactions for you.
Robin: Okay. Let me take this check out of the deposit envelope. And what about my card?
Bank clerk: I’ll call the technician and she should be able to retrieve it for you.
Robin: Thanks a lot. I guess that the machine just doesn’t like me.
Bank clerk: It’s not you. Those machines just act up sometimes.
Robin: In that case, I won’t take it personally.
[end of story]
The script for this podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
bank teller – a bank employee who stands behind a window and greets customers, helping them put money into or get money out of their accounts, or do other things with their accounts
* The bank teller asked to see two pieces of identification before she would cash the check.
ATM – automated teller machine; a cash machine; a machine that lets people take money from or put money into their accounts, or see how much money they have in their accounts
* This ATM charges a $2.50 fee every time you take money out of your account.
PIN – personal identification number; a secret number that is used to get money from a cash machine or to get information about one’s account over the phone or Internet
* If you forget your PIN, you’ll have to ask your bank to mail you a new four-digit code.
ATM card – a debit card; a small rectangular piece of plastic that one can use to buy things and to get money out of an ATM (cash machine)
* When you get your new ATM card, please sign the back of it.
to jam – to get stuck; to have papers or other objects get caught in a machine so that the machine can’t work properly and you cannot take the papers or other objects out again
* If you try to copy more than 20 pages at once, this photocopy machine will probably jam.
teller window – an area behind glass where a bank employee sits and helps customers on the other side of the glass to take money from or put money into their accounts, or ask for information about their accounts
* The teller windows are always being filmed by security cameras in case there is a robbery.
transaction – something that one does related to one’s bank account, such as getting money, putting money into the account, or moving money between accounts
* At this bank, customers are supposed to make only three transactions at a time. If you have more than three transactions, you need to stand in line again.
deposit – money put into one’s account
* This afternoon I need to make a $400 deposit into my account.
to transfer – to move something, especially money, from one place to another
* Transferring money between accounts online is much faster and easier than going to the bank.
checking account – where one’s money is kept in a bank so that it can be taken out by using ATMs, buying things with one’s debit card, or writing checks
* At this bank, my checking account is free if I keep at least $750 in it, but I have to pay $5 per month if I have less than $750 in the account.
savings account – where one’s money is kept in a bank so that it can earn interest, be saved for use in the future, and can be taken out as cash or by moving money to a checking account
* Manu automatically puts 10% of what he earns into his savings account each month, because he’s saving money to buy a home.
withdrawal – money taken out of a bank account
* I need to go to the bank and make a withdrawal because I don’t have any cash in my wallet.
deposit envelope – a paper envelope that is used to hold checks and put them into a cash machine so that the money is put into one’s bank account
* The bank tells customers to never put cash into a deposit envelope, because it would be very easy for someone to steal it.
technician – a person with good technical skills, usually for fixing machines
* The computer company is going to send a technician to my house to try to help me fix the computer.
to retrieve – to get back something that has been lost or stolen
* Were the police able to retrieve the stolen necklace?
to act up – to misbehave; to behave poorly or incorrectly; to not work properly
* Lately the computer has been acting up, making files disappear without warning.
to take (something) personally – to be offended, believing that something happened for personal reasons
* The other day I said that I don’t like the color red and Shauna took it personally because she was wearing a red sweater, but that’s not what I meant!
Comprehension Questions
1. What happened to the ATM machine?
a) Somebody put jam inside it.
b) The ATM card got stuck inside it.
c) The PIN got jammed inside it.
2. Why does Robin take the check out of the deposit envelope?
a) Because she’s going to give it to the bank clerk.
b) Because she has decided not to deposit it.
c) Because she needs it to make a withdrawal.
Answers at bottom.
What Else Does It Mean?
to transfer
The verb “to transfer,” in this podcast, means to move something, especially money, from one place to another: “Walter had an emergency while he was traveling in Asia, so he asked his parents to transfer money to his account.” “To transfer” can also mean to change the university where one is studying: “Mindy decided to transfer from Colorado State University to the University of Colorado.” “To transfer” can also mean to move from one train or bus to another while using public transportation: “To get from the library to the zoo, you’ll need to take bus 13 and then transfer to bus 7 when you reach the city park.” “To transfer (something)” often means to make a copy of information stored electronically so that it can be placed on another computer or music player: “The easiest way to transfer information between our computers would be to make a CD.”
to act up
In this podcast, the phrase “to act up” means to not work properly: “The CD player is acting up again, stopping every five minutes.” When we talk about children, the phrase “to act up” means to misbehave or to behave poorly: “Young children often act up when they want their parents to pay more attention to them.” “To act out” means to perform something in theater: “Gisa is acting out the role of Ophelia in tonight’s performance of Othello.” “To act on (something)” or “to act upon (something)” means to do something based on information or advice that one has received: “Acting on her parents’ wishes, Bela went to medical school, but she never really wanted to be a doctor.”
Culture Note
Banks in the United States try to get more customers by offering “convenient” (useful and easy) services. For example, many banks offer services online. “Online banking” lets customers view their account “balances” (the amount of money that they have), transfer money to other accounts, and even open new accounts online. Banks also offer “online bill pay” so that customers can pay their bills for electricity, phone, TV cable, and other services by using the Internet, without having to write and mail checks. The bank will send a check for the customer or transfer the money directly.
Banks also offer “automated services” that happen without the customer having to do anything. For example, customers can request that their “paychecks” (the money they receive from employers) have “automatic deposit,” meaning that the money appears in their bank accounts every two weeks without having to take the paycheck to the bank to deposit it. Customers can also set up “automatic transfers” so that money moves from their checking accounts to their savings accounts on the same date each month.
Many banks try to get new customers by offering free banking. For example, they might offer “no-fee accounts” where the customer doesn’t have to pay for the checking account if he or she keeps a minimum amount of money in the account. Other banks offer “no-fee ATMs” so that if customers use that bank’s ATMs, they don’t have to pay anything to take money out of their accounts.
Other banks offer convenient hours, extending the bank’s hours later in the evening or on weekends so that people who work full-time have time to go to the bank.
Comprehension Answers
1 - b
2 - a