
= 2019年
:toc:

---

== 2019-01

Financial regulations in Britain *have imposed* 引进新的法律、法规、税收等;下令使用规则、惩罚等;  推行，采用（规章制度）；强制实行 a rather unusual rule *on* the bosses of big banks.

Starting next year 从明年开始, any guaranteed(`=you are certain that it will happen`) bonus 奖金 of top executives *could be delayed* 10 years if their banks *are under investigation for* wrongdoing(n.)非法或不诚实的行为.

The main purpose of this “clawback”(n.)从收到钱的人那里拿回钱;回收款 rule `系` *is* (1)*to hold* bankers *accountable(a.)对自己的决定或行为负责，并在被要求解释的时候做出解释 for* harmful risk-taking(n.)冒险；承担风险 /and (2)*to restore* 恢复（某种情况或感受） public trust *in* financial institution.

Yet officials *also hope for* a much larger benefit: *more* long term decision-making *not only* by banks *but also* by all corporations, *to build* a stronger economy *for* future generations.

====
- *impose (v.) ~ sth (on/upon sth/sb)* : to introduce a new law, rule, tax, etc.; to order that a rule, punishment, etc. be used 推行，采用（规章制度）；强制实行 / (2) *to force sb/sth to have to deal with sth that is difficult or unpleasant* 迫使；把…强加于 +
=> im-,进入，使，-pos,放置，词源同position,compose.即放置，施压，引申词义推行，强加。 +
-> A new tax *was imposed on fuel*. 当局开始对燃油征收一项新税。 +
-> This system *imposes* additional financial burdens *on* many people. 这个制度给很多人增加了额外的经济负担。

- clawback : n. (business 商) the act of getting money back from people it has been paid to; the money that is paid back 已支付给民众钱款的收回；回收款

- accountable : ADJ If you are *accountable to someone for something* that you do, *you are responsible for it and must be prepared to justify your actions to that person*. 负有责任的 +
->  Public officials can finally *be held accountable(a.) for their actions*. 政府官员最终是要对他们的行为负责任的。
====

英国金融监管机构, 对大银行的老板们实施了一项非同寻常的规定。从明年开始，如果银行因不当行为受到调查，高管的任何保证奖金, 都可能被推迟10年发放。这一“追回”规则的主要目的, 是让银行家为有害的冒险行为负责，并恢复公众对金融机构的信任。然而，官员们还希望获得更大的好处:让不仅是银行，而且是所有企业, 都要做出更长远的决策，来为未来几代人打造更强大的经济。


“Short-termism” /or the desire for quick profits, `谓` *has worsened* （使）变得更坏，变得更糟，恶化 in publicly(adv.) traded 公开交易的, 上市的 companies, *says* the Bank of England’s top economist, Andrew Haldane.

He *quotes* a giant of classical economies 古典经济学家, Alfred Marshall, *in describing* this financial impatience(`=a lack of patience`) *as* acting like “Children who *pick* the plums 李子，梅子 *out of* their pudding 布丁;（餐末的）甜食，甜点 *to eat* them [at once]” rather than *putting them aside* to be eaten [last].

====
- short-termism : (n.) a way of thinking or planning (that *is concerned with* the advantages or profits (you could have now), *rather than* the effects in the future) 只注重短期效益的思维方式
====

英国央行(Bank of England)首席经济学家表示，上市公司的“短期主义”(Short-termism)，即对快速盈利的渴望，已经恶化。安德鲁·霍尔丹。他引用了古典经济学巨人阿尔弗雷德•马歇尔的话，将这种金融上的急躁情绪, 描述为“孩子们从布丁里拣出李子马上吃掉”，而不是把它们放在最后吃掉。

The average time for *holding* a stock *in* both the United States and Britain, he *notes*, *has dropped from* seven years *to* seven months in recent decades.

Transient(a.)在一个地方停留或工作很短的时间，然后继续前进;暂住的；过往的；临时的 investors, who *demand* high quarterly profits from companies, *can hinder* 使某人难以做某事,或使某事难以发生; 阻碍；妨碍 a firm’s efforts *to invest in* long-term research /or *to build up*(`=to create or develop sth`) customer loyalty.

This *has been dubbed* 以幽默或批评的方式给某人[某事物]起一个特定的名字;把…戏称为；给…起绰号 “quarterly(a.)季度的；每季的 capitalism”.

====
- hinder => hind,后面的，-er,比较级后缀。即更后面的，引申词义拉后腿，后由形容词变为动词，引申词义妨碍，阻挡。 +
-> a political situation *that hinders economic growth* 妨碍经济发展的政治局面 +
-> An injury *was hindering him from playing his best*. 受伤后他无法发挥出最高水平。

- dub : V-T If someone or something *is dubbed* a particular thing, *they are given that description or name*. 把…称为 +
=> 起绰号，来自古法语adober, 原义为封爵士。 2.配音，缩写自double. 即再次录制声音。
====

In addition, new digital technologies *have allowed* more rapid trading of equities （公司的）普通股, quicker use of information, and thus *shortens* attention spans 某事物持续或能够持续的时间  in financial markers.

“There *seems to be* a predominance 在数量上很大,或数量上超过其他事物或人的情况;（数量上的）优势 of short-term thinking(n.) *at the expense of* 以牺牲 (某人的利益/某物) 为代价 long-term investing,” *said* Commissioner Daniel Gallagher of the US Securities and Exchange Commission (美国)证券交易委员会(abbr: SEC) in speech this week.

====
- *AT THE EXPENSE OF SB/STH* : with loss or damage to sb/sth 在牺牲（或损害）…的情况下 +
-> He built up the business *at the expense of his health*. 他以自己的健康为代价逐步建立起这个企业。
====

他指出，近几十年来，美国和英国持有股票的平均时间, 都从7年降到了7个月。短期投资者要求从公司获得高额的季度利润，这可能会阻碍公司投资于长期研究,或建立客户忠诚度的努力。这被称为“季度资本主义”。 +
此外，新的数字技术使股票交易更加迅速，信息的使用更加迅速，从而缩短了对财务指标的关注时间。美国证券交易委员会(sec)委员丹尼尔•加拉格尔(Daniel Gallagher)在本周的一次演讲中表示:“短期思维似乎占据了主导地位，这是以牺牲长期投资为代价的。”


In the US, the Sarbanes-Oxley Act of 2002 *has pushed* 推动；促使（达到某程度或状态） most public companies *to defer* 把某事推迟到以后; 推迟；延缓；展期 performance bonuses for senior(a.)级别（或地位）高的 executives *by* about a year, *slightly helping reduce* “short-termism.”

In its latest survey of CEO pay, The Wall Street Journal *finds* that “ a substantial(a.)在数量、价值或重要性上,很大的 part” of executive pay *is now tied to*(`=to connect or link sb/sth closely with sb/sth else`) performance.

====
- substantial : ADJ Substantial means large in amount or degree. 大量的; 很大程度的 +
-> *substantial sums of* money 大笔大笔的钱 +
-> *a substantial change* 重大变化 +
-> He ate *a substantial breakfast*. 他吃了一顿丰盛的早餐。
====

Much more *could be done* to encourage “long-termism,” *such as* changes in the tax code 免税代码（指雇员收入免税部分的数字代码，由税务机关编定） and quicker disclosure(n.)把以前是秘密或秘密的事情公开或公开的行为;揭露；透露；公开 of stock acquisitions 你购买或获得某种东西，通常是为了增加你已有的东西; 收购 股份收购.

In France, `主` shareholders who *hold onto* 保留对你有利的东西;不把某物给别人或卖给别人;保住（优势）；不送（或不卖）某物 a company investment for at least two years `谓` *can sometimes earn* more voting rights 投票权;表决权 in a company.

====
- hold on to sth / hold onto sth : (1)  *to keep sth that is an advantage for you; to not give or sell sth to sb else* 保住（优势）；不送（或不卖）某物 +
-> You should *hold on to your oil shares*. 你应该继续保留住你的石油股份。 +
-> She took an early lead in the race and *held onto it* for nine laps. 赛跑一开始她便冲到了前面，并九圈一直保持领先。 +
(2) *to keep sth for sb else /or for longer than usual* （替别人或更长时间地）保存某物 +
-> *I'll hold onto your mail for you* until you get back. 你回来之前我将一直替你保管邮件。
====

在美国，2002年通过的《萨班斯-奥克斯利法》(Sarbanes-Oxley Act)已迫使多数上市公司将高管的绩效奖金推迟一年左右发放，这在一定程度上有助于减少“短期主义”。《华尔街日报》(The Wall Street Journal)在对CEO薪酬的最新调查中发现，高管薪酬的“很大一部分”与业绩挂钩。 +
在鼓励“长期主义”方面，我们可以做得更多，比如修改税法, 和加快股票收购的披露。在法国，对公司投资至少两年的股东, 有时可以获得公司更多的投票权。

Within companies, the right compensation 补偿（或赔偿）物；（尤指）赔偿金，补偿金；赔偿  design 薪酬设计 *can provide* incentives(n.)鼓励你做某事的东西;激励；刺激 for executives *to think beyond* their own time at the company /and *on behalf of* all stakeholders.

Britain’s new rule *is* a reminder *to* bankers that society *has an interest in* their performance, *not just for* the short term *but for* the long term.

====
- compensation design 薪酬设计
- incentive => in-,进入，使，-cent,唱，吟唱，词源同chant,cantor.其原义为定调，唱的节拍，引申词义鼓励，刺激，刺激因素。
====

在公司内部，正确的薪酬设计, 可以激励高管们超越自己在公司的时间，代表所有利益相关者进行思考。英国的新规定提醒银行家们，社会对他们的表现感兴趣，不仅是短期的，而且是长期的。

翻译参考:

英国突如其来的出台新的金融监管法案，要求从明年开始的未来十年内，凡涉及诚信调查的银行经理的保证红利, 一律推迟十年发放，对于银行老板们，这无异于晴天霹雳（这两句我混在一起了，因为分开会导致句子不通顺。第一句直译为英国金融法规给大银行老板们施加了异乎寻常的规则。Financial regulations金融法案；第二句是未来十年内，董事长的保证红利搁置十年发放如果他们所在的银行涉及诚信调查。Starting next year固定搭配，从明年开始，guaranteed bonus保证红利，金融术语，即无论效益如何，红利发放不受影响，top executive经理，董事长，wrongdoing错误，刑事犯罪，显然对于银行，还是发钱的问题，不会涉及到刑事犯罪，转译为诚信，下文的“对银行的信心”也说明了这个。译注）。这个紧箍咒的用意是希望银行老总们在风险（投资，补句）前好好想想，并设法重建公众对于银行的信心。而且英国政府的用意更为长远：长线投资不能仅由银行，而是应该由所有（相关，补句）公司共同决定，这样才能打造经济的美好未来。

英格兰银行首席经济分析师（字面译为首席经济学家）安德鲁·霍尔丹表示，短期效益主义或者说希望快点返现这种想法会削弱上市公司（的竞争力，补句）。他引用古典经济学大师阿尔佛雷德马歇尔（经济学大师，代表著作《经济学原理》，此书为经济学方面的必读书，译注）的话，这种急于求成就好比“把要做布丁的葡萄直接吃了”，而没有等布丁做好了再吃（意译，直译为就像一个小孩把葡萄从布丁里掏出来立刻吃了，而不是放在一边等最后再吃。布丁，西方水果甜点，类似于奶油蛋糕，意思是蛋糕还没做就先把水果吃了而不是等蛋糕做好了再吃蛋糕，相当于不懂得放长线钓大鱼，译注）。

霍尔丹指出，近十年内，无论美国或英国，平均持股时间（金融术语，即股票从购入到脱手的周期，译注）已经从七年降到了七个月。如此短的时间意味着投资人期待快速（注意high译为高字面上没问题，但语义有点不通，能快速挣钱即可，短期投资期待高收益显然不现实，转译为快速，译注）获利，这会妨碍相关公司关注长线投资和回头客（因为短期投资意味着必须在最短时间内挣钱，谁管顾客能否再来，过一年说不准这个公司都关门了呢，能挣一笔是一笔，这两句略难理解，译注）。这也被戏称为“季度资本主义”（金融术语，因为美国公司一般一季度公布一次收支状况，很多人根据这个决定是否买入卖出，译注）。

另外，数字技术的发展使得炒股更容易（equity有个国内教材上可能不怎么提的意思，股票，译注），信息获取更快，这也导致市场不愿意在一个项目上投入过多（意译，直译为减少关注时间在投资风险方面，这个地方有点绕弯，投资既然有风险，说明投资需要较多的时间进行评估，现在不花那么多时间，说明在有风险的投资领域希望尽快脱出。financial marker很冷僻的一个词组，一般字典上估计查不到，投资风险，如果倒过来就是风险投资，译注）。美国证监会委员丹尼尔加拉赫也在本周的一次访谈中表示（US Securities andExchange Commission美国证券交易监督委员会，securities可不是安全，是有价证券的意思，译注），“现在的主流就是短线投资（意译，直译为看来占多数的是短期思维在长线投资方面，short-term thinking短期思维，long-term investing长期投资，译注）。

美国（也意识到了短期投资的问题，补句），2002年，美国通过萨班斯-奥克斯利法案（著名的SOA法案，在安然公司破产后美国迅速通过了这部法案以加强对大公司监管力度，译注），要求上市公司对公司高层的绩效工资延迟一年左右发放（performance bonuses绩效工资），这在一定程度上遏制了“短期效益主义”。根据华尔街日报最新的CEO薪酬调查显示，公司高管们收入的“相当一部分”现在和公司绩效直接挂钩（a substantial part固定搭配，相当一部分）。

不过（补句），想要推动市场关注长期投资还需要做很多事情，比如税收减免（tax code税务代码，就是交税时用的公司对应编码，英式英语指免税，译注）、股票交易更便捷透明（stock acquisition股票购置），等等。像法国（这方面就需要改进，补句），股东需持股两年以上才能有更多的话语权。

对于一家公司而言，合理的薪酬有助于激励公司高管别总是盯着自己的一亩三分地（注意beyond，超越自己的时间），而是要更多为全体股东谋划。英国这项法律对银行家们是个警示，说明公众一直在关注着他们的表现，不仅在短期投资方面，还有长期的。


---

== 2019-01 纯净版

Financial regulations in Britain *have imposed* a rather unusual rule *on* the bosses of big banks. Starting next year, any guaranteed bonus of top executives *could be delayed* 10 years if their banks *are under investigation for* wrongdoing. The main purpose of this “clawback” rule *is* `表` *to hold bankers accountable for* harmful risk-taking /and *to restore* public trust *in* financial institution. Yet officials *also hope for* a much larger benefit: more long term decision-making *not only* by banks *but also* by all corporations, *to build* a stronger economy for future generations.

“Short-termism” or the desire for quick profits, *has worsened* in publicly traded companies, *says* the Bank of England’s top economist, Andrew Haldane. He *quotes* a giant of classical economies, Alfred Marshall, *in describing* this financial impatience *as* {*acting like* “Children who *pick* the plums *out of* their pudding *to eat* them at once” rather than *putting them aside* to be eaten last}.

The average time for *holding a stock* [in both the United States and Britain], he *notes*, *has dropped from* seven years *to* seven months in recent decades. Transient investors, who *demand* high quarterly profits from companies, *can hinder* a firm’s efforts *to invest in* long-term research /or *to build up* customer loyalty. This *has been dubbed* “quarterly capitalism”.

In addition, new digital technologies *have allowed* more rapid trading of equities, quicker use of information, and thus *shortens* attention spans in financial markers. “There *seems to be* a predominance of short-term thinking *at the expense of* long-term investing,” *said* Commissioner Daniel Gallagher of the US Securities and Exchange Commission in speech this week.

In the US, the Sarbanes-Oxley Act of 2002 *has pushed* most public companies *to defer* performance bonuses *for* senior executives by about a year, *slightly helping reduce* “short-termism.” In its latest survey of CEO pay, The Wall Street Journal *finds* that {“ a substantial part” of executive pay *is now tied to* performance}.

Much more *could be done* to encourage “long-termism,” *such as* changes(n.) in the tax code /and quicker disclosure of stock acquisitions. In France, shareholders who *hold onto* a company investment for at least two years *can sometimes earn* more voting rights in a company.

Within companies, the right compensation design *can provide* incentives for executives *to think beyond* their own time at the company /and *on behalf of* all stakeholders. Britain’s new rule *is* a reminder *to* bankers that society *has an interest in* their performance, *not* just for the short term *but* for the long term.


---

== 2019-02


Grade 成绩等级；评分等级 inflation -- the gradual 逐渐的 increase(n.) in average GPAs(grade-point averages （学生各科成绩）平均成绩点数) over the past few decades -- *is often considered* a product of a consumer era in higher education, in which students *are treated like* customers *to be pleased*.

But another, related force -- a policy often *buried 把（某物）掩藏在地下；埋藏 deep in* course catalogs *called* “grade forgiveness” -- *is helping raise* GPAs.

Grade forgiveness *allows* students *to retake* 重新控制某事物，如城镇;收复（失地）；恢复控制 a course in which they *received* a low grade, and the most recent grade /or the highest grade *is* the only one that *counts*(`=to be important 重要`) in *calculating* 用数字求出总数、数量、距离等 a student’s overall(a.)包括与特定情况有关的所有事物或人; 全面的；综合的；总体的 GPA.

====
- *count(v.) (for sth)* :  ( not used in the progressive tenses 不用于进行时 ) *to be important* 重要 +
-> Every point in this game *counts*. 这场比赛每一分都很重要。 +
-> The fact that she had apologized *counted for nothing with him*. 她已道歉，但他认为这是没有用的。

====

分数膨胀——过去几十年里平均绩点(gpa)的逐渐增加——通常被认为是高等教育消费时代的产物，在这个时代，学生被当作顾客来取悦。但是另一种相关的力量——一种经常深埋在课程目录中的被称为“分数宽恕”的政策——正在帮助提高平均成绩。 +
分数宽免允许学生重修一门分数较低的课程，而最近的分数或最高的分数, 对计算学生总平均成绩很重要。

The use of this little-known 鲜为人知的 practice *has accelerated* 加速；加快 in recent years, as colleges *continue to do their utmost*(`=greatest; most extreme`) *to keep* students *in* school (and *paying tuition*) /and *improve* their *graduation （大学或美国高中的）毕业 rates* 毕业率.

When this practice *first started* decades ago, it *was usually limited to* freshmen (美国中学或大学的)一年级学生, *to give them* a second chance *to take a class* 上课 in their first year if they *struggled in* their transition 从一种状态转变为另一种状态的过程或时期;过渡；转变 to college-level courses.

But now most colleges, *save for*(`=except sth`) many selective campuses, *allow* all undergraduates 正在攻读学士学位的大学生, and even graduate 有大学学士学位的人 students, *to get* their low grades forgiven.

====
- utmost : N-SING If you say that *you are doing your utmost to do something*, you are emphasizing that *you are trying as hard as you can to do it*. 最大努力
- *save / save for* :  ( also save for ) ( old use ) ( formal ) except sth 除了；除…外 +
-> They knew nothing about her *save her name*. 除名字外，他们对她一无所知。
====

近年来，这种鲜为人知的做法越来越多地被采用，因为大学仍在尽最大努力让学生留在学校(并支付学费)，提高他们的毕业率。几十年前，这种做法刚开始的时候，通常仅限于大一新生，如果他们在向大学课程过渡的过程中遇到困难，可以在第一年再给他们一次上课的机会。但是现在大多数大学，除了许多精挑细选的学校，允许所有本科生，甚至研究生，得到他们的低分数的宽恕。

College officials *tend to emphasize that* {the goal of grade forgiveness *is less about* the grade itself *and more about* {*encouraging* students *to retake* courses critical(a.)极重要的；关键的；至关紧要的 to their degree program and graduation *[without incurring 由于你行为而导致某事发生在你身上; 陷入某种必须要对付的状况; 招致;遭受;蒙受 a big penalty]*}}.

====
- incur : v. if you incur sth unpleasant, you are in a situation in which you have to deal with it 招致；遭受；引起 +
=> in-,进入，使，-cur,跑，词源同course,current.即跑进来，引申词义招致，导致。 +
-> *She had incurred the wrath of her father* by marrying without his consent 她未经父亲同意就结婚，使父亲震怒。 +
-> The government *had also incurred huge debts*.
政府也已承受了大笔债务。
====

“Untimely(a.)在不合适的时间或情况下发生的,不合时宜的” said Jack Miner, Ohio State University’s registrar 管理着学院或大学事务的高级官员;教务主任;注册主任, “we *see* students *achieve* more success because they *retake a course* and *do better* in subsequent contents /or *master* 完全学习或理解了某事物; 精通；掌握 the content that *allows* them *to graduate* 大学毕业,拿到学士学位 on time.”

高校官员往往强调，分数减免的目的不在于分数本身，而在于鼓励学生重选对他们的学位项目和毕业至关重要的课程，而不会招致重大惩罚。“突然的，”俄亥俄州立大学(Ohio State University)的注册主任杰克·米纳(Jack Miner)说，“我们看到学生取得了更大的成功，因为他们重新上了一门课，并在之后的学习内容上做得更好了，或者掌握了能让他们按时毕业的内容。”

That said, there *is* a way in which grade forgiveness *satisfies* colleges’ own needs *[as well 也；同样地]*.

For public institutions, state funds *are sometimes tied partly to* their success *on* metrics 一组数字，提供关于特定过程或活动的信息;米制的；公制的 such as *graduation rates* and *student retention*(`=the action of keeping sth 保持；维持；保留`) -- so 因此 better grades *can*, by *boosting figures* like those, *mean* more money.
====
- 最后一句是  better grades *can mean* more money. 而 by boosting figures like those 是 *状语, 插在了can 和 mean之间了!*
====


And `主` anything that *raises* GPAs `谓` *will likely make* students -- who, at the end of the day, are *paying the bill* -- *feel* {they’*ve gotten a better value* for their tuition dollars}, which *is* another big concern 一种忧虑的感觉，尤指许多人共有的担心，忧虑 for colleges.
====
- 本句其实是 anything (that raises GPAs)  will likely *make students feel* {they’ve...}. *在宾语(students)和宾补(feel...)之间, 插入了一个由who引导的定语从句.*
====

也就是说，分数减免在某种程度上, 也满足了大学自身的需求。对于公共机构来说，国家资金有时与它们在诸如毕业率和学生留校率等指标上的成功程度有关，因此，通过提高这些数据，更好的成绩意味着更多的钱。任何提高平均绩点的措施, 都有可能让那些最终支付了这笔费用的学生, 感到他们的学费得到了更好的回报，而这也是大学的另一个很关心的问题。

Indeed 用于向语句中添加信息; 其实；实际上, grade forgiveness *is* just another way that universities *are responding to* consumers’ expectations 一种某事会发生的想法,预期,期望 for higher education.

Since students and parents *expect* a college degree *to lead* 朝一个特定的方向或到一个特定的地方去; 通向；通往 a job, it is in the best interest of a school *to turn out*(`=to produce sb/sth 制造；生产；以（…装束等）出现`) graduates who are *as qualified(a.)通过考试或完成做某项工作所必需的培训；有做某项工作的经验;具备…的学历（或资历） as* possible -- or at least *appear to be*.

On this, students’ and colleges’ incentives(n.) *seem to be aligned*(v.) 把某物安排在正确的位置，或相对于它物来说处在正确的位置上，尤指在一条直线上; 排整齐；校准；（尤指）使成一条直线.

====
- *align (v.) ~ sth (with/to sth)* : to change sth slightly so that it is in the correct relationship to sth else 使对齐; 使一致 +
-> Domestic prices *have been aligned with those in world markets*. 国内价格已调整到与世界市场一致。
====

事实上，分数减免只是大学回应消费者对高等教育期望的另一种方式。既然学生和家长都希望大学文凭能找到工作，那么学校的最大利益就是尽可能地培养出合格的毕业生——或者至少看起来是合格的。在这一点上，学生和大学的动机似乎是一致的。


---

== 2019-02 纯净版

`主` Grade inflation -- the gradual(a.) increase(n.) in average GPAs(grade-point averages) over the past few decades -- `谓` *is often considered* a product of a consumer era in higher education, in which students *are treated like* customers *to be pleased*. But another, related force -- `主` a policy often *buried deep in* course catalogs *called* “grade forgiveness” -- `谓` *is helping raise* GPAs.

Grade forgiveness *allows* students *to retake a course* in which they *received* a low grade, and the most recent grade /or the highest grade *is* the only one (that *counts* in *calculating* a student’s overall GPA).

The use of this little-known practice *has accelerated* in recent years, as colleges *continue to do their utmost* *to keep* students *in* school (and *paying tuition*) and *improve* their graduation rates. When this practice *first started* decades ago, it *was usually limited to* freshmen, *to give* them a second chance *to take a class* in their first year if they *struggled in* their transition to college-level courses. But now `主` most colleges [*save for* many selective campuses], `谓` *allow* all undergraduates, and even graduate students, *to get* their low grades forgiven.

College officials *tend to emphasize that* the goal of grade forgiveness *is less about* the grade itself *and more about* {*encouraging* students *to retake courses* critical to their degree program and graduation *without incurring* a big penalty}. “Untimely,” said Jack Miner, Ohio State University’s registrar,“we *see* students *achieve more success* because they *retake a course* and *do better* in subsequent contents /or *master the content* that *allows* them *to graduate on time*.”

That said, there *is* a way in which grade forgiveness *satisfies* colleges’ own needs as well. For public institutions, state funds *are sometimes tied partly to* their success on metrics *such as* graduation rates and student retention -- so `主` better grades *can*, *by boosting* figures like those, `谓` *mean* more money. And `主` anything that *raises* GPAs `谓` *will likely make* students -- who, at the end of the day, *are paying the bill* -- *feel* {they’*ve gotten a better value* for their tuition dollars}, which *is* another big concern for colleges.

Indeed, grade forgiveness *is* just another way that universities *are responding to* consumers’ expectations for higher education. Since students and parents *expect* a college degree *to lead a job*, it *is* in the best interest of a school *to turn out* graduates who *are* as qualified as possible -- or at least *appear to be*. On this, students’ and colleges’ incentives *seem to be aligned*.


---

== 2019-03

This year *marks* exactly two centuries since the publication of Frankenstein; or, The Modern Prometheus, by Mary Shelley.

Even before the invention of *the electric light bulb*, the author *produced* a remarkable 不寻常的,或令人惊讶的，引起人们注意的 work of *speculative(a.)基于猜测的, 或建立在"在不了解全部事实的情况下就形成的"观点上的; 猜测的；推断的 fiction* that *would foreshadow*(v.)对未来会发生的事情的预示；是…的预兆 many ethical(a.)与"关于什么是对,什么是错的"信念和原则相联系的; （有关）道德的；伦理的 questions *to be raised by* technologies *yet （表示将来可能发生，尽管现在似乎没有可能）早晚，总有一天 to come*.

====
- yet : *could, might, may, etc. do sth ~* : used to say that *sth could, might, etc. happen in the future, even though it seems unlikely* （表示将来可能发生，尽管现在似乎没有可能）早晚，总有一天 +
-> We may win yet. 我们迟早会赢的。 +
-> She *could yet* surprise us all. 总有一天，她会让我们都大吃一惊。
====

Today the rapid growth of artificial intelligence （AI）*raises* fundamental questions: "What is intelligence 学习、理解和逻辑思考的能力;做好这件事的能力;智能, identify 能认出某人[某事物],并能说出他们是谁或是什么, or consciousness(`=the state of being aware of sth`)? What *makes humans* humans?"

What *is being called* artificial general intelligence, 同位 machines (that *would imitate*(`=to copy sb/sth 模仿；仿效`) the way humans think), `谓` *continues to evade*(`=to escape from sb/sth or avoid meeting sb 逃脱；躲开；躲避`) scientists.

Yet humans *remain fascinated(v.)(`=very interested`) by* the idea of robots that *would look, move, and respond like* humans, *similar to* those recently *depicted* 用文字或图片描述某事物,或对某事物的印象; 描写；描述；刻画 on popular sci-fi TV series （广播或电视上题材或角色相同的）系列节目 such as “Westworld” and “Humans”。
====
- fascinated : ADJ If you are *fascinated by* something, *you find it very interesting and attractive, and your thoughts tend to concentrate on it*. 入迷的
====

Just how people think *is still far too complex to be understood*, let alone 更不必说 *reproduced*(`=to produce sth again; to make sth happen again in the same way`), says David Eagleman, a Stanford University neuroscientist 神经系统科学家.

“*We are just in a situation* where there are no good theories *explaining* what consciousnesss *actually is* /and how you *could ever build a machine* to get there.”

斯坦福大学(Stanford University)的神经学家大卫·伊格曼(David Eagleman)表示，人们的思维方式仍然过于复杂，难以理解，更别说复制它了。“我们现在的处境是，没有好的理论来解释意识到底是什么，以及你如何才能造出一台机器来实现它。”

But that *doesn’t mean* crucial ethical issues involving AI *aren’t at hand* 在时间或距离上接近你.

The coming use of autonomous(a.)能够管理自己或控制自己的事务;自治的；有自治权的;自主的；有自主权的 vehicles, for example, *poses* 造成了必须加以解决的威胁、问题等 ;引起；产生 thorny(a.) 会引起困难或分歧的; 棘手的；麻烦的；引起争议的 ethical questions.

Human drivers sometimes *must make split-second(a.)(`=done very quickly or very accurately 一瞬间作出的；做得非常精确的`) decisions*.

Their reactions *may be* a complex combination of instant 立即的；立刻的 reflexes(n.)本能反应;下意识反应, *input from* past driving experiences, *and* what their eyes and ears *tell* them in that moment.

AI “vision” today *is not nearly as sophisticated(a.)对世界有丰富的经验;了解时尚、文化和其他人们认为对社会很重要的事情的;见多识广的；老练的；见过世面的 as* that of humans.

And `主` *to anticipate* 预料；预期未来可能会发生什么，并采取行动做好准备 every imaginable driving situation `系` *is* a difficult programming(n.)（计算机）程序设计，编程 problem.

====
-  *(close/near) at hand* : close to you in time or distance （在时间或距离上）接近; 在手边；即将到来 +
-> Help was *at hand*. 援助近在咫尺。

- pose : V-T If something poses a problem or a danger, *it is the cause of that problem or danger*. 造成 (问题或危险) +
-> The task *poses(v.) no special problems* . 这项任务不会造成特别的问题。

- thorny : ADJ If you describe a problem as thorny, you mean that *it is very complicated and difficult to solve, and that people are often unwilling to discuss it*. 棘手的 +
=> 来自 thorn,刺，引申词义棘手的，麻烦的。

- reflex => re-回 + -flex-弯曲

- sophisticated :ADJ Someone who is sophisticated *is comfortable in social situations and knows about culture, fashion, and other matters that are considered socially important*. 老练的; 久经世故的 +
=> -soph-聪明 + -ist名词词尾 + -ic形容词词尾 + -ate动词词尾
====

但这并不意味着涉及人工智能的关键伦理问题不在眼前。例如，即将使用的自动驾驶汽车提出了棘手的道德问题。人类司机有时必须在瞬间做出决定。他们的反应可能是一个复杂的组合，包括即时的反射、过去驾驶经验的输入，以及他们的眼睛和耳朵在那一刻告诉他们的东西。今天的人工智能“视觉”远不如人类的复杂。预测每一种可能的驾驶情况是一个困难的编程问题。


Whenever(`=at any time that; on any occasion that 在任何…的时候；无论何时；在任何…的情况下`) decisions *are based on* masses of(`=a large number or amount of sth`) data, “you quickly *get into* a lot of ethical questions,” *notes* Tan Kiat How, chief executive of a Singapore-based agency that *is helping* the government *develop* a voluntary(`=done willingly, not because you are forced`) code(道德准则；行为规范) 自律守则 for the ethical （有关）道德的；伦理的 use of AI.

Along with 与…一道 Singapore, other governments and mega(`=very large or impressive`)-corporations 特大企业;企业集团 *are beginning to establish* their own guidelines.

Britain *is setting up* a data ethics center. India *released* its AI ethics strategy this spring.

====
- based : (a.) ( also in compounds 亦构成复合词 ) if a person or business is based in a particular place, *that is where they live or work, or where the work of the business is done* 在…居住（或工作）；基地（或总部）在… +
-> a *Chicago-based* company 总部设在芝加哥的公司 +
-> We'*re based* in Chicago. 我们住在芝加哥。
====

[On June 7] Google *pledged* 保证给予（或做）；正式承诺 *not to “design or deploy* 把士兵或武器移动到他们准备采取军事行动的位置上;部署，调度（军队或武器） AI” that *would cause* “overall(`=including all the things or people that are involved in a particular situation; general`) harm,” or *to develop* AI-directed 控制或对某人[某事物]负责; 管理；监督；指导 weapons or *use* AI for *surveillance*(n.)（对犯罪嫌疑人或可能发生犯罪的地方的）监视 that *would violate*(`=break it`) international norms.

It also *pledged* {*not to deploy* AI whose use *would violate* international laws or human rights}.
====
- direct : v.  *to control or be in charge of sb/sth* 管理；监督；指导 +
=> dis-, 分开。-reg, 竖直，引导，词源同regulate, correct. 引申义拉直，部署，管理。 +
-> He was asked to take command and *direct(v.) operations* . 他奉命统率并指挥作战行动。 +
====

While(`=although; despite the fact that`) the statement *is* vague 无信息;或没有提供足够的信息或细节;不具体的；不详细的；粗略的, it *represents* one starting point.

So *does* the idea that `主` decisions (*made by* AI systems) `谓` *should be* explainable, transparent(`=allowing you to see the truth easily 透明的；易看穿的；显而易见的`), and fair.

虽然声明很模糊，但它代表了一个起点。人工智能系统做出的决策, 应该是可解释的、透明的和公平的，这一观点也同样适用。

To put it another way 从另一个角度说; 换言之: How can we *make sure* that {the thinking of intelligent machines *reflects* humanity’s highest values}? Only then *will* they `系` *be* useful servants /and *not* Frankenstein’s out-of-control monster.

换句话说:我们如何才能确保智能机器的思维反映出人类的最高价值?只有这样，他们才能成为有用的仆人，而不是弗兰肯斯坦失控的怪物。


---

== 2019-03 纯净版

This year *marks* exactly two countries [since the publication of Frankenstein; or, The Modern Prometheus, by Mary Shelley]. Even before the invention of the electric light bulb, the author *produced* a remarkable work of speculative fiction that *would foreshadow* many ethical questions (*to be raised by* technologies yet to come).

Today the rapid growth of artificial intelligence （AI）*raises* fundamental questions: "What *is* intelligence, identify, or consciousness? What *makes humans* humans?"

What *is being called* artificial general intelligence, machines (that *would imitate* the way humans think), *continues to evade* scientists. Yet humans *remain fascinated(a.) by* the idea of robots that *would look, move, and respond* like humans, *similar to* those recently *depicted* on popular sci-fi TV series *such as* “Westworld” and “Humans”。

Just how people think *is* still far too complex to be understood, let alone *reproduced*, says David Eagleman, a Stanford University neuroscientist. “*We are just in a situation* where there are no good theories *explaining* what consciousnesss *actually is* /and how you *could ever build* a machine to get there.”

But that *doesn’t mean* crucial ethical issues involving AI *aren’t at hand*. The coming use of autonomous vehicles, for example, *poses* thorny(a.) ethical questions. Human drivers sometimes *must make split-second decisions*. Their reactions *may be* a complex combination of instant reflexes, *input from* past driving experiences, *and* what their eyes and ears *tell them* in that moment. AI “vision” today *is not nearly as sophisticated as* that of humans. And `主` *to anticipate* every imaginable driving situation `系` *is* a difficult programming problem.

[Whenever] decisions *are based on* masses of data, “you *quickly get into* a lot of ethical questions,” *notes* Tan Kiat How, chief executive of a Singapore-based agency that *is helping* the government *develop* a voluntary code *for* the ethical use of AI. *Along with* Singapore, other governments and mega-corporations *are beginning to establish* their own guidelines. Britain *is setting up* a data ethics center. India *released* its AI ethics strategy this spring.

[On June 7] Google *pledged {not to “design or deploy* AI” that *would cause* “overall harm,” or *to develop* AI-directed weapons or *use AI for surveillance*(n.) that *would violate* international norms}. It *also pledged* {*not to deploy* AI whose use *would violate* international laws or human rights}.

While the statement *is* vague, it *represents* one starting point. So *does* the idea that decisions (*made by* AI systems) *should be* explainable, transparent, and fair.

*To put it another way*: How can we *make sure* that {the thinking of intelligent machines *reflects* humanity’s highest values}? Only then *will* they *be* useful servants /and *not* Frankenstein’s out-of-control monster.


---

== 2019-04

States *will be able to force* more people *to pay sales tax* when they *make online purchases* [under a Supreme Court decision Thursday that *will leave* shoppers *with* lighter 更轻的 wallets /but *is* a big financial win *for* states].

根据美国最高法院周四做出的一项裁决，各州将能够迫使更多的人在网上购物时缴纳销售税，这将使购物者的钱包更轻(即支出更多)，但对各州来说是一个重大的财政胜利。

The Supreme Court’s opinion Thursday *overruled* 从更有权力的位置上来改变决定,或拒绝一个想法; （以权力）否定，拒绝，更改决定 a pair(`=two things of the same type, especially when they are used or worn together`) of decades-old 几十年的 decisions (that states *said* *cost*(`=to cause the loss of sth 使丧失；使损失`) them billions of dollars in lost revenue annually).

The decisions *made* it more difficult for states *to collect* 获得某人欠的钱等，例如去他们家取钱;收（欠款）；（上门）收（账） sales tax *on* certain online purchases.

最高法院星期四的裁决推翻了几十年来的两项裁决。各州说，这两项裁决使他们每年损失了数十亿美元的收入。这些决定使得各州对网络购物征税, 更是困难。

The cases (the court *overturned*) *said* that {if a business *was shipping* 用船或其他交通工具运送或运输某人/某物 a customer’s purchase *to* a state where the business 商业组织，如公司、商店或工厂 *didn’t have* a physical presence such as a warehouse or office, the business *didn’t have to collect sales tax* for the state}.

Customers *were generally(`=in most cases`) responsible for* *paying* the sales tax *to* the state [themselves] if they *weren’t charged* 向某人索要一定数量的钱来购买商品或服务;收（费）；（向…）要价 it, but most *didn’t realize* they *owed it* and *few paid*.

被法院推翻的老的案件, 当时声称: 如果某个商家给客户发货, 如果该公司在买家所在的地方并无实体存在, 无论是仓库还是办公室, 则该公司就不需要向买家所在的地方政府缴税. 如果不预先说明, 则缴纳销售税, 由买家来承担. 不过加大多数买家都不知道这个事情, 结果就是几乎没人缴税.

Justice Anthony Kennedy *wrote* that {the previous decisions *were* flawed(a.)(`=having a flaw ; damaged or spoiled 有错误的；有缺点的；有瑕疵的`)}.

“Each year the physical presence rule *becomes further removed from* 与…大相径庭；与…不相干 economic reality /and *results in* significant revenue losses *to* the States,” he *wrote* in an opinion *joined by* four other justices.

Kennedy *wrote* that {the rule “*limited* states’ ability *to seek* long-term prosperity 成功的状态，尤指在赚钱方面;兴旺；繁荣；昌盛 /and *has prevented* market participants 参加活动或事件的人;参与者；参加者 *from competing on* an even(a.)均等的;实力相当地;(机会) 各半的 playing field 比赛场地;运动场；操场.”}

====
- *be far/further/furthest removed from sth* : to be very different from sth; to not be connected with sth 与…大相径庭；与…不相干 +
-> Many of these books *are far removed from* the reality of the children's lives. 很多这样的书都跟孩子们的现实生活严重脱节。

- even : a.  +
->  The meat *is divided evenly*(ad.)(`=each person, group, or area involved has an equal amount 均等地`) and boiled in a stew. 肉被均等地切开并在锅里炖。 +
-> It was an even(a.)(`= is equally balanced between the two sides who are taking part. 实力相当的`) game. 这是一场势均力敌的比赛。 +
->  They *have a more than even(a.)(`= the chances that it will or will not happen are equal. (机会) 各半的`) chance* of winning the next election. 他们在下次竞选中有过半的胜机。
====


最高法院大法官安东尼肯尼迪表示，以前那些裁决漏洞百出，“实体存在规则越来越不符合现实，由此导致的政府（税收，补句）损失无法计数”，所以他支持另外四位大法官的联名提案（write in签字），他还表示这个规则“限制了各级政府开发长期收益的能力，妨碍了市场公平竞争。”

The ruling *is* a victory *for* big chains(`=a group of shops/stores or hotels owned by the same company 连锁商店`) with a presence in many states, since they *usually collect sales tax* on online purchases already.

Now, rivals *will be charging sales tax* where they *hadn’t* before.

Big chains *have been collecting sales tax* nationwide(a./ad.)(`=happening or existing in all parts of a particular country`) because they *typically 通常；一般 have* physical stores *in* whatever state (a purchase *is being shipped to*).

Amazon.com, with its network of warehouses, also *collects sales tax* in every state that *charges* it, though 不过，可是，然而 third-party sellers (who *use* the site) *don’t have to*.

裁决对那些在许多地方都有实体存在的大公司而言, 是件幸事，毕竟他们在国内各地都有实体仓库 -- 只要还想发货，没法逃税。(大公司需要在全国范围内缴税, 因为在货物需要发送的地方, 一般都有实体仓库) 比如业马逊它的营销网络遍布各处，不缴税也不行，而同样也租用场地的那些竞争对手却不缴税。现在，终于轮到他们也缴税了。

Until now, `主` many sellers (that *have* a physical presence in only a single state or a few states) `谓` *have been able to avoid charging sales taxes* [when they *ship to* addresses outside those states].

`主` Sellers (that *use* eBay and Etsy, which *provide platforms for* smaller sellers,) also `谓` *haven’t been collecting sales tax* nationwide.

Under the ruling Thursday, states *can pass* laws *requiring* out-of-state sellers *to collect* the state’s sales tax *from* customers /and *send it to* the state.

直到（周四裁决）生效前，如果卖家只在一个或几个地方有实体产业，他们在给其他各地发货时就可以逃税。即使强如 Etsy（美国大型网络销售平台以手工品为主，国内可能没什么名气）这种小型商家汇聚的销售平台也存在逃税现象。不过按照周四的裁决，各地方政府就可以通过法令, 要求州外的销售者向买家征收州销售税，然后将销售税上缴给州政府。

Retail trade groups *praised* the ruling, *saying* {it *levels(v.)使平坦；使平整; 使相等；使平等 the playing field* 创造一个人人机会均等的环境 *for* local and online businesses}.

`主` The losers, *said* retail analyst 工作是分析一个问题并给出意见的人; 分析者；化验员 Neil Saunders, `系` *are* online-only retailers, especially smaller ones.

Those retailers *may face* headaches 头痛 *complying with*(`=to obey a rule, an order, etc`) various state sales tax laws.

The Small Business & Entrepreneurship 企业家的地位，或与企业家有关的活动; 企业家(身份、行为); 企业家精神 Council *advocacy(n.)(对某思想、行动方针、信念的)拥护，支持，提倡 group* 游说组织 *said* in a statement, “Small businesses and internet entrepreneurs 创业者 *are not well served [at all]* by this decision.”

====
- *level (v.) : ~ sth (off/out)* : to make sth flat or smooth 使平坦；使平整
- *playing field* : a large area of grass, usually with lines marked on it, where people play sports and games 运动场；操场
- *level the playing field* : to create a situation where everyone has the same opportunities 创造人人机会均等的局面

- comply : V-I If someone or something *complies with* an order or set of rules, *they do what is required or expected*. 遵从
====

零售商们（注意没有大写，说明并非专有名词，不必翻译成联盟）对周四的裁决也都表示认可，认为这一裁决有助于地方卖家和网络卖家的公平竞争。零售专家尼尔桑德斯表示，反对之声不是没有(loser的原意是屡屡失败者，转译为反对者，译注），但仅限于网络卖家，而且也只是很少的一部分。毕竟也们要面对多个地方（即将出台的）征税法案，这可不是件愉快的事。作为游说组织的美国小企业和企业家理事会（特别提示，这个句子在advocacy group前后应该各少了一个逗号，指游说组织，通过各种方式拉拢议会, 使之通过对某一方有利议案的组织，在美国民主政体中有其特殊地位，其能量不可低估，SBEC是美国一个拥有十多万家中小企业的松散联盟）则在一份声明中表示，“小企业和网商并未从这个裁决中得到多少好处。”


---

== 2019-04 纯净版

States *will be able to force* more people *to pay sales tax* when they *make online purchases* [under a Supreme Court decision Thursday that *will leave* shoppers *with* lighter wallets /but *is* a big financial win *for* states].

The Supreme Court’s opinion Thursday *overruled* a pair of decades-old decisions (that states said *cost* them billions of dollars in lost revenue annually). The decisions *made* it more difficult for states *to collect sales tax* on certain online purchases.

The cases (the court *overturned*) *said* that {if a business *was shipping* a customer’s purchase *to* a state (where the business *didn’t have* a physical presence such as a warehouse or office), the business *didn’t have to collect sales tax* for the state}. Customers *were generally responsible for* *paying* the sales tax *to* the state [themselves] if they *weren’t charged* it, but most *didn’t realize* they owed it /and *few paid*.

Justice Anthony Kennedy *wrote* that {the previous decisions *were* flawed}. “[Each year] the physical presence rule *becomes further removed from* economic reality /and *results in* significant revenue losses to the States,” he *wrote* in an opinion *joined by* four other justices. Kennedy *wrote* that {the rule “*limited* states’ ability *to seek* long-term prosperity /and *has prevented* market participants *from* competing(v.) on an even playing field.”}

The ruling *is* a victory for big chains (with a presence in many states), since they usually *collect sales tax* on online purchases already. Now, rivals *will be charging sales tax* [where they *hadn’t* before]. Big chains *have been collecting sales tax nationwide* because they *typically have* physical stores [in whatever state a purchase *is being shipped to*]. Amazon.com, with its network of warehouses, also *collects sales tax* [in every state that charges it], though third-party sellers (who *use* the site) *don’t have to*.

Until now, many sellers (that *have* a physical presence in only a single state or a few states) *have been able to avoid charging sales taxes* when they *ship to* addresses outside those states. Sellers (that *use* eBay and Etsy, which *provide platforms for* smaller sellers,) *also haven’t been collecting sales tax nationwide*. Under the ruling Thursday, states *can pass* laws *requiring* out-of-state sellers *to collect* the state’s sales tax *from* customers /and *send it to* the state.

Retail trade groups *praised* the ruling, *saying* {it *levels* the playing field *for* local and online businesses}. The losers, *said* retail analyst Neil Saunders, *are* online-only retailers, especially smaller ones. Those retailers *may face headaches* *complying with* various state sales tax laws. The Small Business & Entrepreneurship Council advocacy group *said* in a statement, “Small businesses and internet entrepreneurs *are not well served [at all]* by this decision.”

---





