
= 2016年
:toc:

---

## 2016-01.

France, which *prides 自豪;引以为荣；为…而骄傲 itself as* the global innovator 创新者; 革新者 of fashion, *has decided*(`=to make an official or legal judgement`) its fashion industry *has lost* an absolute right *to define* physical(`=connected with a person's body rather than their mind`) beauty *for* woman.
====
- *decide* : (v.)( law 律 ) *~ (for/against sb)* : *to make an official or legal judgement* 裁决；判决 +
-> The case will be decided by a jury. 这案件将由陪审团裁决。
====

Its lawmakers *gave* preliminary(`=happening before a more important action or event`) approval(n.)(`=agreement to sth`) last week *to* a law (that *would make* it a crime *to employ* ultra-thin 超瘦;超薄 models on runways (机场的) 跑道;T型台).

The parliament also agreed *to ban* websites that "*incite*(`=to encourage sb to do sth violent, illegal or unpleasant, especially by making them angry or excited`) excessive(`=greater than what seems reasonable or appropriate`) thinness" by *promoting*(`=to help sth to happen or develop`) extreme dieting 日常饮食.
====
- preliminary => pre-,在前，早于，-limin,界限，门槛，开端，词源同limit.引申词义初步的，初期的。
- promote :V-T If people promote something, *they help or encourage it to happen, increase, or spread*. 促进
====

Such measures *have* a couple of uplifting(`=making you feel happier or giving you more hope`) motives.

They *suggest* {beauty *should not be defined by* looks(n.)外观；相貌；外表 (that *end up with* impinging(`=affects you to some extent`) on health).}
That's a start.
====
- look : [ Cusually sing. ] *the way sb/sth looks*; the appearance of sb/sth 样子；外观；相貌；外表 +
-> *Looks* can be deceptive. 外表有时是靠不住的。

- looks : [ pl. ] *a person's appearance*, especially when the person is attractive 尤指吸引人的相貌，容貌 +
-> He *lost his looks* (`= became less attractive`) in later life. 他英俊的相貌在晚年已不复存在。

- *impinge* : V-I *~ (on/upon sth/sb)* :( formal ) *to have a noticeable effect on sth/sb, especially a bad one* 对…有明显作用或影响；妨碍；侵犯 +
=> *im-,进入，使，-pinge,固定，紧压，系紧*，词源同fang,*impact*.引申词义妨碍，侵犯。 +
->  He never allowed his work to impinge on his private life. 他从不让他的工作妨碍私生活。
====

And the ban on ultra-thin models *seems* to go beyond *protecting* models *from* starving 挨饿; 饿死 themselves to death -- as some *have done*.

It *tells* the fashion industry that it *must take responsibility for* the signal (it *sends* women), especially teenage girls, *about* the social tape-measure 卷尺；皮尺 (they must use *to determine*(`=to discover the facts about sth; to calculate sth exactly`) their individual worth 个人价值).
====
- tape measure : N-COUNT A *tape measure* is a strip of metal, plastic, or cloth which has numbers marked on it and is used for measuring. 卷尺
- determine : v. to discover the facts about sth; to calculate sth exactly 查明；测定；准确算出 +
=> de-, 向下。-term, 边界，界限，词源同term, terminal. 即划下界限，明确。 +
-> An inquiry was set up *to determine the cause of the accident*. 已展开调查以确定事故原因

====

The bans, if fully *enforced*, *would suggest to* woman (and many men) that they *should not let* others *be* arbiters 仲裁人; 裁决机构 of their beauty.

And perhaps [faintly(`=very small; possible but unlikely`)] they *hint*(`=to suggest sth in an indirect way`) that {people should *look to* 注意，考虑改进 intangible(`=that exists but that is difficult to describe, understand or measure`) qualities *like* character and intellect *rather than* *dieting*(v.)节食 their way *to* size zero 零号尺码 or wasp-waist 细腰；蜂腰 physiques(`=the size and shape of a person's body`)}.
====
- arbiter : N-COUNT An arbiter is a person or institution *that judges and settles a quarrel* between two other people or groups. 仲裁人; 裁决机构 +
=> ar同前缀ad-, 去，往。词根bain，同词根ven, 走，-t，过去分词格，见acrobat。指走来充当裁判的第三个人。

- *look to sth* : ( formal ) *to consider sth* and think about how to make it better 注意，考虑改进 +
-> We need to look to ways of improving our marketing. 我们得考虑改进营销方法。

- intangible : ADJ Something that is intangible *is abstract or is hard to define or measure*. 难以捉摸的; 难以确定的 +
=> *in-不,无 + -tang-接触* + -ible形容词词尾,被动意义 +
-> The old building *had an intangible air of sadness* about it. 那座旧建筑笼罩着一种说不出的悲凉气氛。

- physique : N-COUNT Someone's physique is *the shape and size of their body*. 体格; 体形
====

The French measures(n.), however, *rely* too much *on* severe punishment *to change* a culture (that still *regards* beauty *as* skin-deep 肤浅的; 表面的 and bone-showing).

Under the law, *using* a fashion model (that *does not meet* a government-defined index of body mass 质量) *could result in* a $85,000 fine(`=a sum of money that must be paid as punishment for breaking a law or rule`) and six months in prison.

The fashion industry *knows* {it *has* an inherent problem in *focusing on* material adornment 装饰 and idealized 理想化的 body types}.

In Denmark, the United States, and a few other countries, it is trying *to set* voluntary(a.)(`=done willingly, not because you are forced`) standard *for* models and fashion images(`= the impression that a person, an organization or a product, etc. gives to the public`) (that *rely* more *on* peer pressure *for* enforcement 强制执行).

*In contrast to* 相比之下 France's actions, Denmark's fashion industry *agreed* last month *on* rules and sanctions(`=to punish sb/sth; to impose a sanction on sth`) (*regarding* age, health, and other characteristics(`=a typical feature or quality that sth/sb has`) of models).
====
- sanction : (1) n./V-T If someone in authority sanctions an action or practice, they *officially approve of it and allow it to be done*. 批准; 认可 +
=> *sanct-,神圣的*，-ion,名词后缀。即神圣的存在，封神，祝圣，*引申正面词义"批准"，反面词义"处罚"。* +
(2) N-PLURAL Sanctions are *measures* taken by countries *to restrict trade and official contact with a country* that has broken international law. 国际制裁 +
-> *Trade sanctions*(n.) were imposed against any country that refused to sign the agreement. 凡拒签该协议的国家均受到贸易制裁。 +
====

The newly revised(`=to change sth, such as a book or an estimate, in order to correct or improve it`) Danish Fashion Ethical 有关道德的；伦理的 charter *clearly states*, we are *aware of* and *take responsibility for* the impact (the fashion industry *has*) *on* body ideals(n.)(`=an idea or standard that seems perfect, and worth trying to achieve or obtain`), especially *on* young people.
====
- revise : V-T If you revise the way you think about something, *you adjust your thoughts*, usually in order *to make them better* or more suited to how things are. 修正 (对某事的想法) +
=> re-,再，重新，-vis,看，词源同 visit,vision.引申词义改变，修改。
====

The charter's 宪章，章程 main tool of enforcement *is* 表 *to deny(`=to refuse to allow sb to have sth that they want or ask for`) access for* designers and modeling agencies 模特经纪公司 *to* Copenhagen 哥本哈根,丹麦首都 Fashion Week(CFW), which *is run by* the Danish Fashion Institute.

But [in general] it *relies on* a name-and–shame 公开指责 method of compliance(`=the practice of obeying rules or requests`).
====
- *To name and shame* is to "publicly say that a person, group or business has done something wrong".

- comply : V-I If someone or something complies with an order or set of rules, *they do what is required or expected*. 遵从 +
=> com-, 强调。-ple, 装满，满的，词源同full, fulfill. 即补足，顺从。拼写受ply影响。
====

{ *Relying on* ethical 道德上的 persuasion *rather than* law 目的状 *to address*(`=to think about a problem or a situation and decide how you are going to deal with it `) the misuse(`=the act of using sth in a dishonest way or for the wrong purpose`)) of body ideals} *may be* the best step 一步.

Even 更加 better *would be* 表 *to help* {*elevate*(`=to make the level of sth increase`) notions(`=an idea, a belief or an understanding of sth`) of beauty *beyond* the material standards of a particular industry}.
====
- *address (v.): ~ (yourself to) sth* ( formal ) : to think about a problem or a situation and *decide how you are going to deal with it* 设法解决；处理；对付 +
-> We must *address ourselves to the problem of* traffic pollution. 我们必须设法解决交通污染问题。

- notion : ~ *(that...)~ (of sth)* : *an idea, a belief or an understanding of sth* 观念；信念；理解
====

法国一向以作为全球时尚革新者为傲，如今它已决定其时尚产业已经失去了定义女性体型美的绝对权力。上周，法国的立法者初步通过了一部法律，该法律将使用超瘦模特上T型台走秀定为犯罪。法国议会还同意封禁那些推广极端的节食来诱使女性追求骨感体型的网站。

这些措施有几个积极的动机。它们表明美不应该由外貌来定义，因为追求外貌美最终会危害人的健康。这些措施只是反对追求骨感体型风气的一个开始。禁止使用超瘦模特的目的, 不仅仅是保护模特不因减肥而把自己饿死, ——有些模特就因减肥而饿死。还警告时尚产业：对于女性该用什么样的社会标尺来判定自己的个人价值这一问题，时尚产业给女性，尤其是未成年少女，传达了错误的信号，时尚产业必须为此负责。

如果完全执行该禁令，它会将向女性(以及很多男性)表明：不要让别人成为自己美的评判者。这些措施或许还隐约地暗示，人们应该注重个性和智力等无形的品质，而不是通过节食来达到“零号身材”或“黄蜂腰体型”。

然而，法国的这些举措过分依赖严厉的惩罚来改变时尚产业的文化，该文化依旧认为瘦到皮包骨是美。该法律规定，使用没有达到政府体质指数要求的时尚模特的后果是, 罚款8.5万美元, 和服刑6个月。时尚产业知道, 它们注重衣着打扮和理想体型的问题一直存在。丹麦、美国和其他一些国家的时尚产业, 试图为模特和时尚形象, 设定一个非强制性标准，该标准更多地依靠同辈压力来执行。

相比于法国的措施，上月，丹麦时尚产业同意了关于模特的年龄、健康和其他特征的规定和惩罚。最新修订的《丹麦时尚产业道德章程》明确规定：“我们已经意识到时尚产业给体型观念带来的影响，尤其是给年轻人带来的影响，我们应该对此负责。” 这个章程的主要执行方法是, 对于那些违反规定的设计师和模特经纪机构, 拒绝他们进入哥本哈根时尚周，该时尚周由丹麦时尚机构运作。

但总的来说，该举措依靠指名道姓的方法来确保该章程得到遵守。依靠道德规劝, 而不是法律手段来矫正理想体型的错误观点, 或许才是最好的办法。更好的措施就是有助于提升美的概念，使之超越某一特定产业的物质标准。

---


== 2016-01 纯净版

France，which *prides itself as* the global innovator of fashion, *has decided* {its fashion industry *has lost* an absolute right *to define* physical beauty for women}. Its lawmakers *gave preliminary approval* last week *to* a law (that *would make it a crime* to employ ultra-thin models on runways). The parliament also *agreed* *to ban* websites (that “*incite* excessive thinness” *by promoting* extreme dieting).

Such measures *have* a couple of uplifting motives. They *suggest* {beauty *should not be defined by* looks(n.) that *end up* impinging on health}. That’s a start. And the ban on ultra-thin models *seems to go beyond* protecting models from starving themselves to death -- as some have done. It *tells* the fashion industry that {it *must take responsibility for* the signal (it *sends* women, especially teenage girls), about the social tape-measure (they *must use* to determine(v.) their individual worth)}.

The bans, if *fully enforced*, *would suggest to* women (and many men) that {they *should not let* others *be* arbiters of their beauty}. And perhaps faintly, they *hint* that {people *should look to* intangible qualities (*like* character and intellect) *rather than* *dieting their way to* size zero or wasp-waist physiques}.

The French measures, however, *rely too much on* severe punishment *to change* a culture that *still regards beauty as* skin-deep-and bone-showing. Under the law, `主` *using* a fashion model that *does not meet a government-defined index* of body mass `谓` *could result in* a $85,000 fine and six months in prison.

The fashion industry *knows* {it *has* an inherent problem *in* focusing on material adornment and idealized body types}. In Denmark, the United States, and a few other countries, *it is trying to set voluntary standards for* models and fashion images that *rely more on* peer pressure for enforcement.

*In contrast to* France’s actions, Denmark’s fashion industry *agreed [last month] on* rules and sanctions (*regarding* the age, health, and other characteristics of models). The newly revised Danish Fashion Ethical Charter *clearly states*: ”*We are aware of and take responsibility for* the impact the fashion industry *has* on body ideals, especially *on* young people”. The charter’s main tool of enforcement *is* `表` *to deny access for* designers and modeling agencies *to* Copenhagen Fashion Week (CFW), which *is run by* the Danish Fashion Institute. But [in general] it *relies on* a name-and-shame method of compliance.

`主` *Relying on* ethical persuasion *rather than* law *to address* the misuse of body ideals `系` *may be* the best step. Even better *would be* `表` *to help elevate* notions of beauty *beyond* the material standards of a particular industry.

---

## 2016-02.

[For the first time in history] *more* people live in towns *than* in the country. [In Britain] this *has had* a curious result.

While polls 民意测验 *show* {Britons 英国人；不列颠人 *rate*(`=to have or think that sb/sth has a particular level of quality, value, etc`) "the countryside" *alongside* the royal family, Shakespeare and the National Health Service (NHS) *as* what makes them proudest 自豪的(proud的最高级) of their country}, this *has* limited(a.) political support.
====
- curious : ~ (that...) *strange and unusual* 稀奇古怪；奇特；不寻常 +
=>  -cur-关心 + -i- + -ous形容词词尾
- *rate : (v.) ~ sb/sth (as) sth /~ as sth* : to have or think that sb/sth has a particular level of quality, value, etc. 评估；评价；估价
====

民意调查显示，尽管英国人把“乡村”与英国皇室、莎士比亚和国民医疗服务制度一起当成英国的四大骄傲，但英国人的这种观点只得到了有限的政治支持。

A century ago Octavia Hill(人名) *launched* the National Trust 全国托管协会（负责管理并保护英格兰、威尔士及北爱尔兰的历史遗迹或自然景观） *not* to rescue(v.) stylish houses *but* to save(v.) "the beauty of natural places *for* everyone forever."
*It* was specifically(adv.)(`=connected with or intended for one particular thing only`) *to provide* city dwellers *with* spaces for leisure (where they *could experience*(`=to have and be aware of a particular emotion or physical feeling`) "a refreshing air)." Hill's pressures [later] *led to* the creation of national parks and green belts.

They *don't make* countryside any more, and [every year] concrete *consumes*(v.)(=to eat or drink sth) more of it.
It *needs* constant guardianship(`=the state or position of being responsible for sb/sth`).

====
- National Trust : 国民托管组织英国保护名胜古迹的私人组织
- stylish : a. ( approving ) *fashionable; elegant and attractive* 时髦的；新潮的；高雅的；雅致的
- dweller : ( especially in compounds 尤用于构成复合词 ) *a person* or an animal *that lives in the particular place* that is mentioned 居民；居住者；栖身者
- leisure : n. *time* that is spent *doing what you enjoy* when you are not working or studying 闲暇；空闲；休闲
- refreshing : a. *making you feel less tired or hot* 使人精力充沛的；使人凉爽的; 使人感到清爽的; 使人精神恢复的
- *pressure : n. ~ (for sth) /~ (on sb) (to do sth)* : *the act of trying to persuade or to force sb to do sth* 催促；要求；呼吁；强迫
- consume : V-T To consume an amount of fuel, energy, or time means *to use it up*. 消耗 消耗，耗费燃料、能量、时间等
- guardianship : n. ( formal ) ( law 律 ) *the state or position of being responsible for sb/sth* 监护；监护地位；监护人
====

一个世纪前，奥克塔维亚·希尔发起成立了国民托管组织，此举不是去挽救那些雅致的房屋，而是“为所有人永久保存自然之地的美”。
此举是专门为城市居民提供休闲空间，在那里他们可以呼吸新鲜空气。
后来，由于希尔的助推，促成了各种国家公园和绿化带的建立。
而现在，公园和绿化带不再造就乡村，相反，混泥土建筑每年侵占更多的乡村。
乡村需要持续的保护。


[At the next election] none of the big parties *seem likely* to endorse(v.)(`=to say publicly that you support a person, statement or course of action`) this sentiment(`=a feeling or an opinion, especially one based on emotions`).

The Conservatives' 保守的；守旧的;保守党的 planning reform ① *explicitly gives* rural development *priority(n.) 优先；优先权；重点 over* conservation(`=saving and protecting the environment`), even ② *authorizing*(`=to give official permission for sth, or for sb to do sth`) "off-plan 楼花(房屋尚未建, 只有设计图可看的)" building (where local people *might object*(`=to say that you disagree with, disapprove of or oppose sth`)).

The concept of sustainable(`=that can continue or be continued for a long time`) development 可持续发展 *has been defined as* profitable(`=gives sb an advantage`).
====
- endorse : V-T If you endorse someone or something, *you say publicly that you support or approve of them*. 公开支持; 赞同  +
=> en-, 进入，使。-dors, 背，见dorsal. 财务术语，即在背后签字。
- sentiment : n. ( formal ) *a feeling or an opinion, especially one based on emotions* 基于情感的观点，看法；情绪
- priority :(n.) PHRASE If you *give priority to* something or someone, *you treat them as more important* than anything or anyone else. 优先考虑
====

但在下一届选举中，几个大党都不太可能支持这一观点。
保守党的规划改革明确表示, 要给予乡村开发, 而不是乡村保护优先权，该改革方案甚至批准了建造项目，但遭到了当地人的反对。
可持续发展观, 已经被定义成了有利可图的发展。

Labour 英国工党 *likewise(`=the same; in a similar way`) wants* to discontinue(v.)(`=to stop doing, using or providing sth, especially sth that you have been doing, using or providing regularly`) local planning where councils(`=a group of people who are elected to govern an area such as a city or county`) *oppose*(`=to disagree strongly with sth. and try to change it or prevent it from succeeding`).

The Liberal Democrats 自由民主党 *are* silent.

Only `主` Ukip 英国独立党, *sensing*(`=to become aware of sth`) its chance, `谓` *has sided with* those (*pleading 恳求；央求 for* a more considered(`=careful thought`) approach *to using* green land).

Its Campaign (*to Protect* Rural England) *struck* terror(`=a feeling of extreme fear`) *into* many local Conservative parties.
====
- council : n. a group of people *who are elected to govern an area* such as a city or county 市、郡等的政务委员会，地方议会
- *strike fear, etc. into sb/sb's heart* : ( formal ) to make sb be afraid, etc. 使某人感到恐惧等
====

工党同样也想终止那些遭到地方议会反对的地方性规划。而自由民主党则保持沉默。只有英国独立党, 支持那些呼吁政府在使用绿地方面要深思熟虑的人，因为他们觉得自己的机会来了。该党的“保护英国乡村运动”使许多地方性保守党胆战心惊。

`主` The sensible place *to build* new houses, factories and offices `系` *is* where (people are), in cities and towns where infrastructure *is* in place(`=in the correct position; ready for sth`).

The London agents Stirling Ackroyd recently *identified* enough sites for half a million houses in the London area [alone 独自地], with no intrusion(`=the act of entering a place which is private or where you may not be wanted`) on green belt.

{What is true of London} *is* 表 even truer of the provinces省份.
====
-  *in place* :  ( also *into place* ) in the correct position; ready for sth 在正确位置；准备妥当 +
-> *All the arrangements are now in place* for their visit. 他们来访的一切都安排就绪了。

- *identify : v. ~ sb/sth (as sb/sth)* : *to recognize sb/sth* and be able to say who or what they are 确认；认出；鉴定 / (2) *to find or discover sb/sth* 找到；发现 +
-> She was able to identify her attacker. 她认出了袭击她的人。

- intrusion : the act of *entering a place* which is private or where you may not be wanted 闯入；侵入
====

乡村的新住房、工厂和办公室, 明显应该建在人聚居的地方，城镇的则要建在基础设施完善的地方。
最近，伦敦房地产中介公司“Stirling Ackroyd”在伦敦找出了足够多的建设地点，这些地方能够建设五十万套住房，且不会侵占绿化带。
如果在伦敦市都能如此，那么在其他省份就更能如此了。


The idea (that "housing crisis"  *equals* "concreted meadows") *is* pure lobby talk.
The issue *is* 表 *not* the need for more houses *but*, as always, where to put them.

*Under* lobby pressure, George Osborne *favours*(`=like or support`) rural new-build *against* urban renovation 革新；修理；恢复活力 and renewal(n.)(`=sth begins again after a pause or an interruption`).
He *favours* out-of-town 城外的; 城郊的 shopping sites *against* high streets 大街；主要街道. +
This is 表 *not* a free market *but* a biased 有偏见的 one.
Rural towns and villages *have grown* and *will always grow*.
They *do so best* [where 在…的地方；在…情况下 ① building *sticks 粘贴；粘住 to* their edges and ② *respects* their character].
====
- *lobby talk* : 噱头，游说之词
- renewal : N-SING If there is a renewal of an activity or a situation, *it starts again*. 重新开始; 恢复
====

“住房危机”等同于“混泥土草地”的这个想法是纯粹的游说说辞。 真正的问题不在于需要更多的住房，而是像以往一样，在哪里建设它们。 +
迫于游说压力，乔治·奥斯本选择支持在乡村建设新住房，而不是对城镇进行改造和翻新。他支持在远离城镇的地方, 而不是商业大街上建设购物中心。这种做法可不是自由的市场行为，而是存在偏见的市场行为。乡镇和乡村已经得到了发展，并将一直发展下去。当把高楼大厦保持在城镇和乡村的边缘，尊重它们的特色时，城镇和乡村才能发展得最好。


We *do not ruin* urban conservation(`=protecting the environment`) areas. Why *ruin* rural ones?
Development should *be planned*, not *let rip* 撕; 撕裂.

After the Netherlands 荷兰, Britain is Europe's most crowded country. Half a century of town and country planning *has enabled* it *to retain* an enviable 令人羡慕的；引起忌妒的 rural coherence(`=the situation in which all the parts of sth fit together well`), while still *permitting*(`=allow it to happen`) low-density urban living(`=a way or style of life`).

There is *no doubt* of the alternative 可供选择的事物 -- the corrupted(`=to change the original form of sth, so that it is damaged or spoiled in some way`) landscapes of southern Portugal 葡萄牙, Spain or Ireland.

{Avoiding this *rather than* promoting it} *should unite* the left and right of the political spectrum 谱；光谱.

我们没有毁坏城镇的保护区域。却为什么要去毁坏乡村的保护区域?开发前需要规划，而不任其发展。 +
英国是继荷兰之后欧洲第二拥挤的国家。但半世纪以来，合理的城乡规划使英国得以保留令其他国家羡慕的乡村协调性，同时还允许低密度的城镇人口。
不进行合理规划所带来的后果是毋庸置疑的——无序的乡村建设使得葡萄牙南部，西班牙或爱尔兰的某些地带遭到破坏就是实例。
应该联合英国的左派和右派势力, 来避免无序的乡村建设这一政策，而不是支持无序的乡村发展这一政策。

---

== 2016-02 纯净版

[For the first time in history] more people live in towns *than* in the country. [In Britain] this *has had* a curious result. While polls *show* {Britons *rate* ”the countryside” *alongside* the royal family, Shakespeare and the National Health Service (NHS) *as* what makes them proudest of their country}, this *has* limited(a.) political support.

[A century ago] Octavia Hill *Launched* the National Trust *not* to rescue stylish houses *but* to save “the beauty of natural places for everyone forever”. It *was* `表` specifically *to provide* city dwellers *with* spaces for leisure where they *could experience* “a refreshing air.” Hill’s pressure(n.) later *led to* creation of national parks and green belts. They *don’t make countryside [any more]*，and [every year] concrete *consumes* more of it . It *needs* constant guardianship.

[At the next election] none of the big parties *seem likely* to endorse(v.) this sentiment. The conservatives’ planning reform *explicitly gives* rural development *priority(n.) [over* conservation]， even *authorising* “off-plan” building where local people *might object*. The concept of sustainable development *has been defined as* profitable. Labour *likewise(ad.) wants to discontinue* local planning where councils *oppose* development. The Liberal Democrats *are* silent. Only `主` Ukip, *sensing* its chance, `谓` *has sided with* those (*pleading for* a more considered approach *to using* green land). Its Campaign (*to Protect* Rural England) *struck terror into* many local conservative parties.

`主` The sensible place *to build* new houses，factories and offices `系` *is* where people are，in cities and towns where infrastructure *is* in place. The London agents Stirling Ackroyd *recently identified* enough sites *for* half a million houses [in the London area] [*alone*]，with no intrusion on green belt. What is true of London `系` *is* even truer of the provinces.

The idea (that "housing crisis" *equals* “concreted meadows”) *is* pure lobby talk. The issue *is not* the need for more houses *but*, as always，where to put them. Under lobby pressure，George Osborne *favours* rural new-build *against* urban renovation and renewal. He *favours* out-of-town shopping sites *against* high streets . This *is not* a free market *but* a biased one. Rural towns and villages *have grown and will always grow*. They *do so best* where building *sticks to* their edges /and *respects* their character. We *do not ruin* urban conservation areas. Why *ruin* rural ones? Development *should be planned*, *not let rip*. After the Netherlands, Britain *is* Europe’s most crowed country. Half a century of town and country planning *has enabled* it *to retain* an enviable rural coherence, while *still permitting* low-density urban living. There is no doubt of the alternative -- the corrupted landscapes of southern Portugal, Spain or Ireland. `主` Avoiding this *rather than* promoting it `谓` *should unite* the left and right of the political spectrum.


---

## 2016-03.

"There *is* one and only one social responsibility of business" *wrote* Milton Friedman, a Nobel Prize-winning economist

"That is, *to use* its resources and *engage in* activities (*designed to increase* its profits)."

But [even if you ① *accept* Friedman's premise(n.)前提；假定 and ② *regard* corporate social responsibility(CSR) policies *as* a waste of shareholders's money], things *may not be* absolutely clear-cut(`=easy to recognize and quite distinct`).

New research *suggests* that {CSR *may create* monetary(a.)(`=connected with money, especially all the money in a country`) value *for* companies [时间状 at least when they *are prosecuted(`=to officially charge sb with a crime in court`) for* corruption]}.
====
- premise : (n.) ( BrE also prem·iss ) ( formal ) *a statement or an idea* that forms the basis for a reasonable line of argument 前提；假定 +
=> 来自古法语premisse,来自拉丁语premissa,前提，假设，在前面的论断，来自pre-,在前，早于，-miss,送出，提出，词源同mission,emit.在法律文件中意为前面陈述之事，描述物，通常指土地或房屋，因而引申该词义。 +
-> a false premise 错误的前提
====

诺贝尔经济学奖得主、经济学家米尔顿·弗里德曼写道，企业社会责任有且仅有一种，“那就是，利用自身资源从事能让其获利的各种活动。”
但是即使你同意弗里德曼的这种假设性的观点，并且认为企业社会责任政策是浪费股东的金钱，事情却并非完全如此清晰。
新的研究表明，至少企业因腐败而被起诉的时候，企业社会责任或许能为企业创造经济价值。

The largest firms (in America and Britain together) *spend* more than $15 billion a year *on* CSR, *according to* an estimate(`=you make an approximate judgment or calculation of it.`) *by* EPG, a consulting firm.

This *could add* value *to* their businesses [in three ways].
First, consumers *may take* CSR spending *as* a "signal" (that a company's products *are* of high quality). +
Second, customers *may be* willing *to buy* a company's products [*as* an indirect way *to donate(`=to give money, food, clothes, etc. to sb/sth, especially a charity`) to* the good causes(n.)(`=an aim or principle which a group of people supports or is fighting for.`) (it *helps*)]. +
And third, [*through* a more diffuse(a.)(`=spread over a wide area`) "*halo 绘画等中环绕圣人头上的光环，光轮 effect*"],  `主` whereby(`=by which; because of which`) its good deeds(`=a thing that sb does that is usually very good or very bad`) `谓` *earn* it greater consideration(`=the act of thinking carefully about sth`) *from* consumers and others.

Previous studies (on CSR) *have had* trouble (*differentiating* 区分；辨别 these effects) [because consumers can *be affected by* all three].
====
- causes : N-COUNT A cause is *an aim or principle* which a group of people supports or *is fighting for*. 奋斗目标; 事业 +
-> Refusing to have one leader *has not helped the cause*.  拒绝接受领导无益于该事业。

- diffuse : a./v. *spread over a wide area* 弥漫的；扩散的；漫射的 +
=> *dis-, 分开，散开。-fus, 流，涌*，词源同fusion, confuse. 即光线向不同方向流出，漫射开。 +
-> a diffuse community 居住分散的社群

- deed :N-COUNT A deed is *something that is done*, especially something that is very good or very bad. 行为

- whereby : adv. ( formal ) *by which; because of which* 凭此；借以；由于 +
-> The company operates an arrangement *whereby* employees may select any 8-hour period between 6 a.m. to 8 p.m. to go to work.
====

该公司做出了一种安排，据此员工可以在上午6点到晚上8点之间任意选择8个小时去上班。

据咨询公司“EPG”估算，英美两国的大公司每年合计在企业社会责任上的花费, 超过150亿美元。
这能从三个方面给他们的企业增加价值。
第一，消费者可能会把企业的企业社会责任开销, 当做是一个“信号”，即这一公司的产品质量上乘。
第二，消费者可能愿意购买这一公司的产品，算是间接地为该公司所支持的事业贡献力量。
第三，通过更广泛的“光环效应”，这一公司的善行, 能让消费者和其他人在有购买需求时, 能更多地考虑该公司。
因为消费者可能是受到了以上三个方式的影响，所以先前对企业社会责任的研究, 难以区分这三种方式的影响。


A recent study *attempts* *to separate* them *by looking at* bribery(n.) prosecutions(`=the process of trying to prove in court that sb is guilty of a crime`) *under* American's Foreign Corrupt Practices Act(FCPA) 反海外腐败法.
====
- prosecution => pro-前 + -secut-跟随 + -ion名词词尾
====

It *argues* that {since prosecutors 起诉人; 检察官 *do not consume*(`=to use sth, especially fuel, energy or time`) a company's products *as* part of their investigations, they could *be influenced only by* the halo effect}.

The study *found* that, among prosecuted firms, those (with the most comprehensive CSR programmes(`=a plan of things that will be done or included in the development of sth`)) *tended to get* more lenient(a.)(`=not as strict as expected when punishing sb or when making sure that rules are obeyed`) penalties.
====
- lenient => 来自拉丁语lenis,温和的，宽容的，词源同let,lassitude.
====


Their analysis *ruled out*(`= to state that sth is not possible or that sb/sth is not suitable 不考虑; 排除`) the possibility that (*it was* firm's political influence, *rather than* their CSR stand(`=an attitude towards sth or an opinion that you make clear to people), *that* accounted for 导致; 解释 the leniency(`=a lenient attitude or lenient behaviour`))): Companies (that *contributed more to* political campaigns) *did not receive* lower fines.

In all, the study *concludes* that {*whereas* 用以比较或对比两个事实; 然而，但是，尽管 prosecutors *should only evaluate*(`=consider sth in order to make a judgment`) a case *based on* its merits, they *do 的确 seem* *to be influenced by* a company's record in CSR}.
====
- prosecute : V-T/V-I If the authorities prosecute someone, *they charge them with a crime and put them on trial*. 对…提起公诉; 提起公诉 +
=> 来源于拉丁语中由前缀 *pro-(前)和动词sequi(跟随)* 组成的复合动词prosequi(追踪)。 词根词缀： pro-前 + -secut-跟随 + -e → 追踪→告发

- lenient : ADJ When someone in authority is lenient, *they are not as strict or severe as expected*. 宽大的 +
=> 来自拉丁语lenis,温和的，宽容的，词源同let,lassitude. +
-> a lenient sentence/fine 从宽的判刑╱罚款
====

最近的一项研究, 试图区分这三种方式的影响，它所用的方法就是, 研究因违反《美国反海外腐败法》而遭到行贿起诉的案例。
研究认为，由于检察官并不购买那些作为其调查部分的公司产品，因此他们只能受到“光环效应”的影响。
这项研究发现，在被起诉的公司当中，那些拥有最全面的企业社会责任项目的企业, 往往会从轻处罚。
他们的分析排除了这样的可能性，即：是当事公司的政治影响力，而非他们的企业社会责任立场, 才让它获得了较轻的处罚，因为那些支持政治运动更多的公司, 并没有得到更低的罚金。
总之，这个研究的结论是：虽然检察官在评估一个案件时，应该基于其功绩，实际上还是受到了公司企业社会责任记录的影响。


"We *estimate* that { `主` *either* ① *eliminating* a substantial(`=large in amount, value or importance`) labour-rights concern(n.), such as child labour, *or* ② *increasing* corporate giving 给予物 by about 20% `谓` *result in* fines(n.) (that generally *are* 40% lower *than* the typical punishment for *bribing*(v.)foreign officials).}" *says* one researcher.
====
- substantial =>  sub-下,低 + -st-站立,放置 + -ant形容词词尾 + -ial形容词词尾. /substance,基础，根据，-al,形容词后缀。引申比喻义大量的，重大的。拼写比较 space,spatial.
====

Researchers *admit*(`=to agree, often unwillingly, that sth is true`) that {their study ① *does not answer the question at* how much businesses *ought to spend on* CSR. Nor ② *does* it *reveal* {how much companies *are banking on*(`=to rely on sb/sth`) the halo effect, *rather than* the other possible benefits, when they *decide* their do-gooding policies}}.

But at least *they have demonstrated(`=to show sth clearly by giving proof or evidence`) that* when companies *get into trouble with* the law, evidence of good character *can win(v.) them* a less costly punishment.

其中的一位研究者说：“我们估计，要么消除一个实质性的劳工权益问题，例如童工问题，要么增加20%的企业捐赠，都会促成罚金减少，一般要比因贿赂外国官员而造成的典型罚款低40%。”
研究者们承认, 他们的研究没有解决的问题是：针对企业社会责任, 各大企业到底该支出多少费用。也没有揭露当企业做慈善方面的决策时，会有多看重“光环效应”，而非其他潜在收益。
但至少他们证明了一点，当企业遇到法律问题时，自身良好品质的证据, 将让企业付出更少的罚金。

---

== 2016-03 纯净版

“There is on and only one social responsibility of business,” wrote Milton Friedman, a Nobel prize-winning economist, “That is, *to use* its resources /and *engage in* activities *designed to increase* its profits.” But even if you *accept* Friedman’s premise /and *regard* corporate social responsibility (CSR) policies *as* a waste of shareholders’ money, things *may not be* absolutely clear-cut. New research *suggests* that {CSR *may create* monetary value for companies -- at least when they *are prosecuted for* corruption}.

The largest firms in America and Britain together *spend* more than $15 billion a year *on* CSR, *according to an estimate by* EPG, a consulting firm. This *could add value to* their businesses in three ways. First, consumers *may take* CSR spending *as* a “signal” that a company’s products *are* of high quality. Second, customers *may be willing to buy* a company’s products [as an indirect way] *to donate to* the good causes it helps. And third, through a more diffuse “halo effect,” whereby its good deeds *earn* it 双宾 greater consideration from consumers and others.

Previous studies on CSR have had trouble *differentiating* these effects because consumers *can be affected by* all three. A recent study *attempts to separate* them *by looking at* bribery prosecutions under America’s Foreign Corrupt Practices Act (FCPA). It *argues* that {since prosecutors *do not consume* a company’s products *as part of* their investigations, they *could be influenced only by* the halo effect}.

The study *found* that, among prosecuted firms, {those with the most comprehensive CSR programmes *tended to get* more lenient penalties}. Their analysis *ruled out* the possibility 同位 that *it was* firm’s political influence, *rather than* their CSR stand, that *accounted for* the leniency: `主` Companies that *contributed more to* political campaigns `谓` *did not receive* lower fines.

In all, the study *concludes* that {whereas prosecutors *should only evaluate* a case *based on* its merits, they *do seem to be influenced by* a company’s record in CSR}. “We *estimate* that {`主` *either* eliminating(v.) a substantial labour-rights concern , such as child labour, *or* increasing(v.) corporate giving(n.) [by about 20%] `谓` *results in* fines that generally *are* 40% lower *than* the typical punishment for *bribing* foreign officials}”, says one researcher}.

Researchers *admit* that {① their study *does not answer* the question of how much businesses *ought to spend on* CSR. ② *Nor does it reveal* how much companies *are banking on* the halo effect, *rather than* the other possible benefits, when they *decide* their do-gooding policies}. But at least they *have demonstrated* that when companies *get into trouble with* the law, evidence of good character *can win* them less costly punishment.


---

## 2016-04.

There *will* eventually *come a day* when The New York Times *ceases to publish stories* on newsprint.
{Exactly when that day *will be*} 表 *is* a matter of debate(`=an argument or discussion expressing different opinions`). "Sometime in the future," the paper's publisher *said* back in 2010.

*Nostalgia(n.)(`=a feeling of sadness mixed with pleasure and affection when you think of happy times in the past`) for* ink on paper *and* the rustle(n.)(`=a light dry sound like leaves or pieces of paper moving or rubbing against each other`) of pages *aside* 用于名词后,除…以外, there's plenty of incentive(n.)(`=something that encourages you to do sth`) *to ditch*(=to get rid of sth) print.

====
- nostalgia : N-UNCOUNT Nostalgia is *an affectionate feeling (you have for the past)*, especially for a particularly happy time. (尤指对幸福时光的) 怀旧 +
=> 来自希腊语*nostos,回家，家乡*，来自PIE*nes,我们，*词源同nostrum,our,us.引申词义我们的家，家园，-algia,疾痛，痛苦*，词源同neuralgia,myalgia.引申词义思乡，怀旧。

- Nostalgia(n.)怀旧；念旧 for ... *aside*. 中的aside, 意思相当于是"如果不考虑对...的怀旧因素"

- aside : adv. used after nouns *to say that except for one thing, sth is true* *用于名词后除…以外* +
-> Money worries *aside*, things are going well. *除了*钱令人发愁外，事情进展顺利。

- ditch : V-T If you ditch something that you have or are responsible for, *you abandon it or get rid of it, because you no longer want it*. 丢弃 +
-> I can't bring myself *to ditch him* and start again.
我不能说服自己抛弃他，又重新开始。
====

The infrastructure (required *to make* a physical newspaper) — printing presses 报纸, delivery(n.)(`=the act of taking goods, letters, etc. to the people they have been sent to`) trucks -- *isn't* just expensive; it's excessive(a.) *at a time* when online-only 纯网络的 competitors *don't have* the same set of financial constraints(`=a thing that limits or restricts sth, or your freedom to do sth`).
====
- constraint : N-COUNT A constraint is *something that limits or controls what you can do*. 限制
====
如今纸质印刷所需要的设施，如印刷机和运送卡车，不仅仅是十分昂贵的, 它也是过量不必要的，因为网络报纸竞争对手根本不会在这些基础设施上花费，也不会遇到此类经济困境.

Readers *are migrating away from* print [anyway (ad.)无论如何，反正]. And *though* print ad sales still *dwarf*(`=to make sth seem small or unimportant compared with sth else`) their online and mobile counterparts, revenue(`=the money that a government receives from taxes or that an organization, etc. receives from its business`) from print *is still declining*.

Overhead(`=regular costs that you have when you are running a business or an organization, such as rent, electricity, wages, etc`) *may be* high /and circulation 报刊发行量，销售量 lower, but *rushing* *to eliminate* its print edition(`=the total number of copies of a book, newspaper or magazine, etc. published at one time`) *would be* a mistake, *says* BuzzFeed CEO Jonah Peretti.

====
- overhead (美国英语用单数overhead, 英国英语用复数overheads) : a. [ only before noun ] connected with *the general costs of running a business* or an organization, for example paying for rent or electricity 经费的；管理费用的 +
-> overhead costs 营运开支

- *eliminate* : v. *~ sth/sb (from sth)* : *to remove or get rid of* sth/sb 排除；清除；消除 +
-> Credit cards *eliminate the need* to carry a lot of cash. 有了信用卡就用不着携带很多现金。
====

Peretti *says* {the Times *shouldn't* waste time *getting out of*(`=you do not want to do, you succeed in avoiding doing it`) the print business, but *only if* they *go about(`=you approach it and deal with it`) doing* it [the right way]}. +
"*Figuring out* a way (*to accelerate*(`=to happen or to make sth happen faster or earlier than expected`) that transition 转型) *would make sense* for them," he said, "but [if you *discontinue* it], you're going *have* your most loyal customers *really upset(a.)(`=unhappy or disappointed because of sth unpleasant that has happened`) with you*."
====
- go about doing sth. 着手做某事
- *have sb.+adj. 表示“使某人处于某种态”。*
====

Sometimes that's worth *making a change* anyway 不管怎样 (用以表示某陈述是事实).
Peretti *gives the example of* Netflix *discontinuing* its DVD-mailing service *to focus on* streaming. "It *was seen as* blunder(`=a stupid or careless mistake`)," he said. The move *turned out to be* foresighted(a.)(`=ability to see what is likely to happen in the future and to take appropriate action`).

And if Peretti were *in charge* at the Times?
"I *wouldn't pick* a year *to end* print," he said "I *would raise prices* and *make it into* 把…制成；使…变为 more of a legacy 遗产 product."

The most loyal(a.)(`=remaining faithful to sb/sth and supporting them or it`) customers *would still get* the product they favor, the idea *goes*, and they'd *feel like* {they *were helping* sustain(v.)(`=to provide enough of what sb/sth needs in order to live or exist`) the quality of something they *believe in*}.

"So if you'*re overpaying(`=to pay sb too much; to pay sb more than their work is worth`) for* print, you *could feel like* you *were helping*," Peretti said.
"Then *increase* it [at a higher rate] [each year] and essentially 本质上；根本上 *try to generate* additional revenue."

In other words, if you'*re going to make* a print product, *make* it *for* the people who *are* already obsessed(a.)(`= to completely fill your mind so that you cannot think of anything else, in a way that is not normal`) with it.
Which *may be* what the Times *is doing* already.
====
- obsessed : ADJ If someone is *obsessed(a.) with* a person or thing, they keep thinking about them and find it difficult to think about anything else. 受困扰的; 对…痴迷的
- obsess : V-T/V-I If *something obsesses you* or if *you obsess about something*, *you keep thinking about it* and find it difficult to think about anything else. 困扰; 心神不宁;使痴迷；使迷恋；使着迷 +
-> *ob-,在上，表强调，-sess,坐*，词源同sit,assess,session.即坐上去的，用于指传说中鬼神附体或着魔，引申词义痴迷，着迷。
====

*Getting* the print edition [seven days a week] `谓` *costs* nearly $500 a year -- more than *twice as much as* a digital -- only subscription(`=an amount of money you pay, usually once a year, to receive regular copies of a newspaper or magazine, etc.; the act of paying this money`).
====
- 表倍数: *times＋as＋形容词（或much）或副词原级＋as*... +
-> The big box is *four times as heavy as* the small one. 大箱子是小箱子的四倍重。 +
*用times表示倍数时，一般只限于表示包括基数在内的三倍或三倍以上的数。表示两倍可以用twice 或 double，一倍用once。* +
-> Ten is *twice as much as* five. 十是五的两倍。 +
-> She’s *twice/ double* my age. 她的年龄是我的两倍。
====



"It's a really hard thing *to do*/ and it's a tremendous(`=very great`) luxury(`=a pleasure or an advantage that you do not often have`) that BuzzFeed *doesn't have* a legacy(n.)遗产 business," Peretti *remarked*(`=you say something about it`).

"But we're going to *have* questions *like that* 同位语从句 where we *have* things (we're doing) (that *don't make sense*) [when the market *changes* and the world *changes*]. +
我们会遇到很多问题，例如当市场和世界变化时，我们哪些地方的努力是没有意义的。 +

In those situations, it's better *to be* more aggressive *than*  less aggressive."
====
- 同位语从句中的 主句是 where (do)we have *things*, 然后使用两个定语从句we're doing和don’t make *sense来修饰things*
====


终有那么一天，《纽约时报》会停止在报纸上出版新闻报道。但究竟会在哪天到来就需要辩论一番了。该报的出版商曾在2010年这样说道：“或许在将来的某一天吧。”
撇开对油墨字纸张和翻页的沙沙声的怀念，舍弃纸质版的动机还是很充分的。如今做一份纸质版报纸所需要的印刷机、配送卡车等硬件设施, 不只是贵。在这个只出版电子版的同行报纸, 都没有这种资金限制的时代，这些硬件设施的开支算是离谱了。反正读者正在从纸质版转移到电子版。
尽管纸质版报纸的广告销售额, 仍让在线和移动报纸相形见绌，但是纸质版报纸的收入, 仍在下滑。

“BuzzFeed”首席执行官乔纳·佩雷蒂说道：尽管日常开支会很高，同时发行量持续走低，但贸然停止纸质版, 将会铸成大错。
佩雷蒂说，《纽约时报》不该浪费时间去想着如何停止纸质版，而应该找到一种正确的方法去解决这件事。
他还说，“对《纽约时报》来说，花时间去想出一个能加快其转型的办法, 才是有意义的，但如果《纽约时报》决定不再出版纸质版，那么这将让该报的最忠诚的顾客们失望至极”

但不管怎样，有时候转型还是很值得的。
佩雷蒂给出了“Netflix”终止向顾客邮寄DVD业务，而专注去做流媒体的例子。他说，当时那被看做是愚蠢的错误。但此举证明是很有先见之明的。

如果佩雷蒂负责《纽约时报》，他会有何行动? 他说，我不会选择在某一年停止出版纸质版，相反，我不仅要提高价格，还要将它变为一种可以传承的产物。
这样，那些最忠诚的顾客们, 依旧会买他们一直喜欢的产品，产品的思想就能传播，并且他们会觉得这是在支持他们所信任的产品保持质量。
“因此，如果继续高价购买纸质报纸，人们会觉得自己是在伸出援手，”佩雷蒂说道。 “然后每年使其价格以比较高比率增长，以此获得额外收入”。
换句话说，如果你想做一份纸质版报纸，那就选择那些已经痴迷于它们的人吧。
这或许也是《纽约时报》已经在做的事。
每周七天都订一份制止报纸，一年就要花近500美元——比只订阅电子版的费用贵了一倍多。

佩雷蒂指出，要不要舍弃纸质版确实是一个艰难的决定，但BuzzFeed没有的遗产业务，这一点极其难得，
但当市场和世界形势发生变化时，我们正在做的事情就会变得没有意义，这时候我们也会面临“要不要舍弃报纸的纸质版”类似的难题。
在这种情况下，更激进的举措要好于不痛不痒之举。


---

== 2016-04 纯净版

There *will eventually come a day* when The New York Times *ceases to publish stories* on newsprint. Exactly when that day will be `系` *is* a matter of debate. “Sometime in the future”, the paper’s publisher *said* [back in 2010].

Nostalgia(n.) for ink on paper and the rustle of pages *aside*, there’s plenty of incentive *to ditch* print. The infrastructure (*required* to make a physical newspaper -- printing presses, delivery trucks -- ) *isn’t* just expensive; it’s excessive [at a time when online-only competitors *don’t have* the same set of financial constraints]. Readers *are migrating away* from print anyway. And though print ad sales *still dwarf* their online and mobile counterparts, revenue from print *is still declining*.

Overhead *may be* high and circulation lower, but *rushing* to eliminate(v.) its print edition *would be* a mistake, *says* BuzzFeed CEO Joah Peretti.

Peretti *says* {the Times *shouldn’t waste time* *getting out of* the print business, but only if they *go about* doing it the right way}. "*`主` Fighting out* a way *to accelerate* that transition `谓` *would make sense* for them," he said, “but if you *discontinue* it, you’re going to *have* your most loyal customers *really upset with you*.”

Sometimes that’s *worth* making a change [anyway]. Peretti *gives the example of* Netflix *discontinuing* its DVD-mailing service *to focus on* streaming. "It *was seen as* blunder," he said. The move *turned out to be* foresighted. And if Peretti *were in charge* at the Times? "I *wouldn't pick a year* to end print," he said "I *would raise prices* and *make it into* more of a legacy product."

The most loyal customers *would still get the product* they favor, the idea *goes*, and they’*d feel like* they *were helping sustain* the quality of something they believe in. “So if you’*re overpaying for* print, you *could feel like* you *were helping*,” Peretti said. “Then *increase* it [at a higher rate] each year /and *essentially try to generate* additional revenue.” In other words, if you’*re going to make* a print product, *make it for* the people who *are already obsessed with it*. Which *may be* what the Times is doing already. `主` *Getting* the print edition seven days a week `谓` *costs* $500 a year -- more than *twice as much as* a digital-only subscription.

“It’s a really hard thing to do /and *it*’s a tremendous luxury *that* BuzzFeed *doesn’t have* a legacy business,” Peretti *remarked*. “But *we’re going to have questions* like that {where we *have* things (we’*re doing*) (that *don’t make sense*) when the market changes and the world *changes*}. In those situations, it’s better {to be more aggressive *than* less aggressive}. ”



