
= 2013年
:toc:

---

== 2013-1

In the 2006 film version of The Devil Wears Prada, Miranda Priestly, *played by* Meryl Streep, *scold* 训斥;责骂 her unattractive assistant 助手,副手,助理 for *imagining* 猜想;认为 that high fashion(`=a popular style of clothes, hair, etc`) *doesn’t affect* her.  +
Priestly *explains* {how the deep blue color of the assistant’s sweater 毛衣;针织衫 *descended*(`=to come or go down from a higher to a lower level`) over the years *from* fashion shows 展览会 *to* department stores and *to* the bargain bin 箱子；储物箱 (in which the poor girl doubtless 无疑地, 肯定地 *found* her garment(`=a piece of clothing`))}.
====
- garment => -ment表示具体物。garment n 衣服(gar 装饰＋ment)。gar，garn=furnish，表示"装饰，供应"。garment n 衣服，外衣(gar+ment 表名词→装饰的东西→衣服)
====

在2006年电影版的《时尚女魔头》中，梅丽尔·斯特里普扮演的米兰达·普雷斯丽，责备她其貌不扬的女助手，因为她认为，高端时尚并不能影响到自己。普雷斯丽说明了她助手的深蓝色毛衣如何在数年间，从时尚秀场降到百货商店，又沦为便宜货。毫无疑问，这个贫穷的女孩肯定就是从便宜货里淘的衣服。

This top-down 自上而下的 conception 观念;想法 of the fashion business *couldn’t be* more out of date 过时的；陈旧的 or *at odds (与…)不和；(与…)有矛盾；(与…)意见不一致 with* feverish(`= done extremely quickly, often in a state of nervousness or excitement`) world (*described* in Overdressed 穿得过于正式(或讲究)的, Elizabeth Cline’s three-year indictment 控诉;控告;谴责 of “fast fashion”).  
====
- top-down : ADJ In a top-down organization, *all the important decisions are made by the most senior people in the organization*. 自上而下的
- couldn’t be more out of date 就是说再落后不过，落后得不能再落后了，*couldn’t be more 可以理解为非常非常的意思*。 
- odds：(与…)不和；(与…)有矛盾；(与…)意见不一致 If someone is *at odds* with someone else, or if two people are *at odds*, they are disagreeing or quarrelling with each other.
- indictment : N-COUNT If you say that one thing is an indictment of another thing, you mean that *it shows how bad the other thing is*. 控诉
====

这种自上而下的时尚商业观，早已过时了， 也和伊丽莎白·克莱因在《过度穿着》中描写的狂热世界不一致。《过度穿着》是伊丽莎白·克莱因花了三年时间，写成的对 “快时尚”的控诉作品。

In the last decades [or so] 大约(放在时间、数字的后面), advances in technology *have allowed* mass-market 面向大众的 labels 商标 such as Zara, H&M, and Uniqlo ① *to react （对…）作出反应 to* trends(n.)趋势 [more quickly] and ② *anticipate*(`=to expect sth`) demand需求 [more precisely].  +
Quckier turnrounds （接活到交活之间的）周转期，时限 *mean* less wasted inventory(`=all the goods in a shop`)存货，库存, more frequent releases 发布,释放, and more profit.  

在过去十年左右的时间，技术的进步已经使得诸如Zara、H&M、优衣库之类的大众市场品牌，能够对流行趋势反应得更快，并能更准确的预料到消费者的需求。更快的转变，意味着更少的存货浪费、更频繁的发布新品、更高的利润。

Those labels *encourage* style-conscious 注意打扮的 consumers *to see* clothes *as* disposal(n.)(`=available for use as you prefer`) —— meant {*to last* only a wash 洗涤 or two, although 虽然，尽管 they *don’t advertise* 为…做广告;宣传 that —— and *to renew* their wardrobe 衣柜;衣橱 every few weeks}.  
====
- disposal: 任…处理;供…任意使用;由…自由支配 If you have something *at your disposal*, *you are able to use it whenever you want*, and for whatever purpose you want. If you say that you are *at someone's disposal*, you mean that you are willing to help them in any way you can.  +
-> He will have a car *at his disposal* for the whole month. 他将有一辆汽车归他使用一个月。
====

这些品牌鼓励对时尚敏感的消费者，把衣服当成是一次性用品——洗过一两次后就不再穿了，尽管他们没在广告上明说——然后每几周就更新衣橱。

By *offering* on-trend 趋势, 倾向 items [at dirt-cheap 贱如粪土的,非常便宜的 prices], Cline *argues*, these brands *have hijacked* fashion cycles, *shaking* all industry (long *accustomed 习惯的；适应的 to* a seasonal(`= varying with the seasons`) pace 步幅,速度；节奏).

克莱因说，这些品牌通过以极其低廉的价格，销售时髦的商品，已经把持了时尚的周期，动摇了一个习惯以季节为周期的产业。

The victims 受害者 of this revolution, of course, *are not* limited(a.) to designers. For H&M *to offer* a 5.95 knit 编织；针织 miniskirt 超短裙;迷你裙 [in all its 2300-plus stores around the world], it must ① *rely on* low-wage 低工资, overseas labor, ② *order* 下命令，要求,订购 in volumes(`=the amount of it`) that *strain* 拉紧,压力,使不堪承受;使紧张 natural resources, and ③ *use* massive(`=extremely large or serious`) amount of harmful 有害的;(尤指)有损健康的 chemicals.

当然，这场变革的受害者，不仅仅是设计师们。为了能在其全世界2300多家商店里，以5.95美元的价格出售超短裙，H&M必须依赖低工资的海外劳动力、大批量采购原材料导致严重危害自然资源、并大量使用有害的化学物质。

_Overdressed_ (使)穿得太讲究 *is* the fashion world’s answer *to* consumer-activist 维护消费者权益的积极分子 bestsellers 畅销书 (like Michael Pollan’s _The Omnivore’s 杂食动物；不偏食的人 Dilemma (进退两难的)窘境，困境_).  +
Mass-produced clothing, like fast food, *fills* a hunger(`=a strong desire for sth`) and need, yet *is* non-durable 不耐用的；不持久的, and wasteful,” Cline *argues*, Americans, she *finds*, buy roughly 概略地 20 billion garments(`=a piece of clothing`) a year —— about 64 items (系列物品或清单中的)一件 per person —— and *no matter* how much they *give away* 赠送；捐赠, this excess(`=more than is necessary`) 谓 *leads to* waste.
====
- omnivore => omni 全，一切，遍及+ vor=eat,吃；
- dilemma : N-COUNT A dilemma is *a difficult situation in which you have to choose between two or more alternatives*. 进退两难的局面
- excess : n.过多;过量；无节制;无度 Excess is *behaviour that is unacceptable because it is considered too extreme or immoral*.
====

《过度穿着》就仿佛是时尚界交给像迈克尔·波伦的《杂食者的困境》一样的消费者维权畅销书的答案。 +
(《过度装扮》其实就是对像Michael Pollan’s所著的《杂食动物的困境》这一类活跃的消费类畅销书的回应。)  +
“大批量生产的服装，就好像快餐一样，充满着渴望和需求，却既不耐用也不经济”，克莱因说到。她发现，美国人每年要买大约200亿件服装——平均每人64件——无论他们捐赠多少，这种无节制的购买行为，都导致浪费。

Towards the end 在……即将结束之际 of Overdressed, Cline *introduced* her ideal(n.)理想；典范, a Brooklyn woman *named* SKB, who, since 2008 *has make* all of her own clothes —— and beautifully. But *as* Cline *is* the first *to note* 留意到;意识到, it *took* Beaumont decades *to perfect* her craft 手艺;工艺; her example, *can’t be knocked off* 偷；盗.
====
- craft : n. an activity involving a special skill at making things with your hands 手艺；工艺
- To *knock off* a house, factory, or shop means *to break into it and steal money or property*.
====
在《过度穿着》的结尾，克莱因介绍了她的理想典范，一个叫萨拉·凯特·博蒙特的布鲁克林女人，她从2008年起，就自己做所有的衣服，而且做得相当漂亮。不过正如克莱因是第一个注意到的那样，博蒙特花了几十年完善自己的手艺，她的事例不能轻易复制。

Though several fast-fashion companies *have made efforts* to curb(`=to control or limit sth, especially sth bad`) their impact 撞击;碰撞；影响;作用 on labor and the environment —— including H&M, with its green Conscious 有意识的 Collection （常为季节性推出的）系列时装（或家用品） Line(`=a type of product`) —— Cline *believes* {lasting-change 持久的变化 *can only be effected by* the customer}. 
====
- collection : *a range of new clothes or items for the home* that are designed, made and offered for sale, often for a particular season （常为季节性推出的）系列时装（或家用品） +
-> Armani's stunning *new autumn collection* 款式新颖靓丽的阿玛尼秋装系列
- Conscious Collection : "环保自觉行动系列"(Conscious Collection)是H&M于2010年推出的，所有的衣服都是由环保面料制造而成，包括有机棉、可再生涤纶、可再生聚酯以及环保大麻纤维等。

- line : *a type of product* 种类；类型 +
-> We are starting *a new line* in casual clothes. 我们将着手经营新款式的休闲装。
====

尽管几个快时尚公司都在设法控制他们对劳工和环境的影响，包括H&M推出了Conscious Collection系列衣服。Cline认为只有客户能带来持久的改变。

She *exhibits* 展示 the idealism 理想主义(common 共有的;共同的 to many advocates 拥护者；提倡者 of sustainability 持续性；能维持性), *be* it [in food] or [in energy]. Vanity 虚荣(心);自负 *is* a constant(`=happening all the time or repeatedly`)常量; people *will only start* shopping(v.) more sustainably 可持续性，支撑得住；能保持住地 when they *can’t afford to* it.
====
- be it in food or in energy : 这部分可以看做是 whether it may be in food or in energy的一种省略用法。in 是“在...方面”.
- *be it A ,B,or" C* means "*whether it is A ,B,or C,*"也就是：不管它（it）是（be）A,是B,还是C...。是一种倒装用法。 +
这个后面不一定要加名词，如：be it true or not不管是否如此.

- be后 = whether it may be in food or in energy.  +
*be+主语 = whether…or… 或 no matter how… (类似于让步状语从句)*

- If you refer to someone's *vanity*, you are critical of them because *they take great pride in their appearance or abilities*. 自负；自大；虚荣；虚荣心 +
=> van，vac，void=empty，表示"空"。
====

尽管包括H&M在内的几家快时尚公司，已经努力控制其对劳动力和环境的影响，引入了绿色环保自觉生产线，克莱因相信，只有消费者才能促成持久的变革。 +
她展示了对于无论在食物还是在能源方面都提倡可持续性的人而言,他们共存在的理想主义。虚荣是常态，人们只有在付不起钱的时候，才会开始以更加可持续的方式购物。

---

== 2013-1 纯净版

In the 2006 film version of The Devil Wears Prada, `主` Miranda Priestly, *played by* Meryl Streep, `谓` *scolds* her unattractive assistant *for* {*imagining that* high fashion doesn’t affect her}, Priestly *explains* how the deep blue color of the assistant’s sweater *descended* over the years *from* fashion shows *to* departments stores /and *to* the bargain bin in which the poor girl doubtless *found* her garment.

This top-down conception of the fashion business *couldn’t be more out of date* or *at odds with* the feverish would (*described* in Overdressed, Elizabeth Cline’s three-year indictment of “fast fashion”). ② In the last decade or so ,`主` advances in technology `谓` *have allowed* mass-market labels *such as* Zara ,H&M, and Uniqlo *to react to* trends [more quickly] /and *anticipate* demand [more precisely]. ③ Quicker turnarounds *mean* {less wasted inventory, more frequent release, and more profit}. ④ These labels *encourage* style-conscious consumers *to see* clothes *as* disposable -- *meant* {*to last* only a wash or two, although they *don’t advertise* that -- and *to renew* their wardrobe every few weeks}. ⑤ By *offering* on-trend items *at dirt-cheap prices*, Cline *argues*, these brands *have hijacked* fashion cycles, *shaking* an industry (long *accustomed to* a seasonal pace).

`主` The victims of this revolution , of course, `谓` *are not limited to* designers. ② For H&M *to offer* a $5.95 knit miniskirt *in* all its 2,300-pius stores *around* the world, it *must rely on* low-wage overseas labor, *order* [in volumes] (that *strain* natural resources), and *use* massive amounts of harmful chemicals.

Overdressed *is* the fashion world’s answer *to* consumer-activist bestsellers *like* Michael Pollan’s The Omnivore’s Dilemma. ② `主` “Mass-produced clothing , *like* fast food, *fills* a hunger and need, yet `系` *is* non-durable and wasteful,” Cline *argues*. ③ `主` Americans, she *finds*, `谓` *buy* roughly 20 billion garments a year -- about 64 items per person -- and *no matter* how much they give away, this excess *leads to* waste.

*Towards the end of* Overdressed, Cline *introduced* her ideal, a Brooklyn woman *named* Sarah Kate Beaumont, who since 2008 *has made* all of her own clothes -- and beautifully. ② But *as* Cline is the first *to note*, it *took* Beaumont decades *to perfect* her craft; her example *can’t be knocked off*.

Though several fast-fashion companies *have made efforts to curb* their impact *on* labor and the environment – *including* H&M, with its green Conscious Collection line -- Cline *believes* {lasting change *can only be effected* by the customer}. ② She *exhibits* the idealism (*common to* many advocates of sustainability), *be* it in food or in energy. ③ Vanity *is* a constant; people *will only start shopping more sustainably* when they *can’t afford to* it.

---

== 2013-2 

*An old saying 谚语;格言 has it* that ｛half of all advertising 广告的 budgets *are wasted* —— the trouble is, no one *knows* which half｝. In the internet age, at least in theory ,this fraction(`=a small part or amount of sth`) can *be much reduced* . By *watching* {what people search for, click on and say online}, companies *can aim* “behavioural 行为的；行为研究的” ads *at* those most likely to buy.

有句老话说的好，一半的广告预算都浪费了——麻烦的是，没人知道哪一半浪费了。在互联网时代，至少在理论上，可以大大减少这种浪费。通过观察人们搜索什么、点击什么、在网上说些什么，公司可以锁定目标，将“行为”广告(即，“有作为的”或“有用的”广告)投放给最有可能的购买产品的人。

[In the past couple of weeks] a quarrel(`=an angry argument or disagreement between people`) *has illustrated*(`=to show that sth is true or that a situation exists`) the value [*to* advertisers] of such fine-grained 细粒度;有细密纹理的 information: Should advertisers *assume* 假定;假设 that people *are* happy *to be tracked* and *sent* behavioural ads? Or *should* they *have* explicit(`=saying sth clearly, exactly and openly`) permission?
====
- explicit => plic,pli,ply=fold,表示"重叠，折叠"。explicit a 明白的，直爽的(ex 出+plic+it→[说话]不重叠的→直截了当的)。implicit 含蓄的，暗示的，盲从的
====
在过去几周，三次交易和一次争论，已经向广告商(以及他们的软件提供商)展示了这种经过精细处理的信息的价值：广告商应该假设人们喜欢被跟踪，并发送行为广告吗？还是他们应该先得到明确的许可才行？

[In December 2010] America's Federal Trade Cornmission (FTC) *proposed*(`=to suggest a plan, an idea, etc`) *adding* a "do not track "(DNT) option *to* internet browsers , so that users *could tell* adwertisers that they *did not want* to be followed. +
Microsoft's Internet Explorer and Apple's Safari both *offer* DNT; Google's Chrome *is due(a.)(`=arranged or expected`) to do so* this year.  +
[In February] the FTC and Digltal Advertising 广告 Alliance (国家或政党的)联盟，同盟 (DAA) *agreed* that {the industry would *get cracking*(`=to start doing something immediately`) [on responding 作出回应;作出反应 to DNT requests]}.
====
- *due ~ (to do sth) /~ (for sth)* : arranged or expected 预定；预期；预计 +
-> The band's first album *is due(a.) for release* later this month. 这个乐队的第一张唱片预定在本月下旬发行。 +
-> The next train is *due*(a.) in five minutes. 下一班火车预计在五分钟后抵达。

- If you tell someone *to get cracking 爆裂声；噼啪声*, you are telling them *to start doing something immediately*. 马上开始;加紧做 
- If you say that someone or something is moving *at a cracking pace*, you mean that they are moving very quickly. 迅速地;飞速地 
====

在2010年12月，美国联邦贸易委员会提出，应该在网络浏览器上添加“拒绝跟踪”(DNT)选项，这样一来，用户就可以告诉广告商，他们不想被追踪。微软公司的IE浏览器，和苹果公司的Safari浏览器，都提供拒绝跟踪；谷歌公司的Chrome浏览器，今年也即将要提供类似功能。在二月份，联邦贸易委员会和数字广告联盟达成一致，浏览器开发业要继续努力，以应对拒绝跟踪的要求。

[On May 31st] Microsoft *Set off* 动身;出发 the row 划船,行，排: It said that {Internet Explorer 10, the version *due(a.)(`=arranged or expected`) to appear* windows 8, *would have* DNT *as a default*}.

5月31日，微软公司率先采取行动：该公司发布公告称，在该公司的新操作系统windows8中的IE10浏览器上，将会默认附带拒绝跟踪选项。

Advertisers are horrified(`=terrified; frightened`). Human nature *being* what it is, most people *stick(`=to fix sth to sth else`) with* default settings. Few *switch* 转换;改变;转变 DNT [*on*] now, but [if tracking *is* off] it *will stay 保持;维持 off*.  +
Bob Liodice, the chief executive(`=a person who has an important job as a manager`) of the Association 协会；社团 of National Advertisers, *says* {consumers *will be* worse off 恶化，情况更坏；每况愈下的 if the industry *cannot collect information* about their preferences 喜好；偏好；偏爱}. People will *not get* fewer ads, he says. “They’ ll *get* less meaningful(`=serious, important, or useful`), less targeted 被定为攻击目标的；定向的 ads.”

广告商们诚惶诚恐。人性使然，人们总是习惯保持默认的设置。现在几乎没人打开“拒绝跟踪”按钮，可如果跟踪处于关闭状态，就会一直是关闭状态。鲍勃·利奥狄斯是数字广告联盟的成员组织之一——全国广告协会——的首席执行官。他说，如果软件业无法收集到关于消费者喜好的信息，那消费者只能境况更糟。人们不会少收到广告，他说，“他们会收到更没意义更没针对性的广告。”

It is not yet clear {how advertisers *will respond*}. 主 Getting a DNT signal信号；暗号 谓 *does not oblige*(`= to force sb to do sth`) anyone *to stop tracking*, although 虽然，尽管 some companies *have promised* to do so.  +
Unable to tell {whether someone really *objects*(`=disagree with, disapprove of or oppose sth`) to behavioural ads /or whether they *are sticking 黏附;附着在,固定不动 with* Microsoft’s default}, some *may ignore*(`=to pay no attention to sth`) a DNT signal and *press on*(`=to continue doing sth in a determined way`) anyway.
====
- press on 坚定地继续 : If you *press on* or *press ahead*, *you continue with a task or activity in a determined way*, and do not allow any problems or difficulties to delay you.
====

现在还不清楚广告商们会怎样采取行动。拒绝跟踪信号并不会强制任何人停止跟踪，尽管有些公司(包括推特公司在内)，已经承诺,收到拒绝跟踪信号就会停止跟踪。由于无法辨认人们是真正反对行为广告，还是他们只是没有改动微软的默认设置，有些公司可能会忽视拒绝跟踪信号，依然强行跟踪。

Also unclear *is* {why Microsoft *has gone it alone*}. After all, it *has* an ad business too, which(指前面的ad business) it says *will comply(`=to obey a rule, an order, etc`) with* DNT requests, though 尽管;虽然 it *is still working out* 想出，得到(解决方法);解(谜) how.  +
If it *is trying* to upset(`=to make sb/yourself feel unhappy, anxious or annoyed`) Google, which *relies* almost wholly *on* advertising, it  *has chosen* an indirect 间接的, 迂回的 method: There is no guarantee 保证，担保，使必然发生 that DNT [by default] *will become* the norm(`=standards of behaviour`)行为准则;规范.  

同样不清楚的是，微软为什么要孤军奋战。毕竟，微软自己也有广告业务，却声称自己的广告业务也要遵守拒绝跟踪要求，不过它也还在寻求解决办法。如果微软试图激怒几乎完全依赖广告业务的谷歌，那么它就已经选择了一个间接的方法：并不能保证默认拒绝跟踪模式会成为标准范例。

DNT *does not seem* an obviously huge selling point 卖点 for windows 8 —— though 尽管;虽然 the firm *has compared* some of its other products *favourably 更优的; 不逊色的 with* 比…毫不逊色 Google's [on that count(`=a point made during a discussion or an argument`)] before.  +
Brendon Lynch, Microsoft's chief privacy officer, *blogged* 博客:"we *believe* consumers *should have* more control." Could it *really be* that simple?
====
- favourable :ADJ If you *make a favourable comparison* between two things, you say that *the first is better than or as good as the second*. 更优的; 不逊色的 +
->  The film bears *favourable technical comparison* with Hollywood productions costing 10 times as much. 这部电影, 与耗资为其10倍的好莱坞作品相比, 在技术上毫不逊色。

- count : [ usually pl. ] *a point* made during a discussion or an argument （讨论或争论的）论点，观点，问题，事项 +
-> I disagree with you *on both counts*. 我对你的两个观点均不敢苟同。
====

虽然公司以前还拿自己的其他几个产品，同谷歌的产品在这方面做过比较，但拒绝跟踪也不像是windows8的巨大卖点。 +
微软首席隐私官布兰登·林奇在博客中写到：“我们相信，用户应该有更多的操控权限。”真是那么简单吗？

---

== 2013-2 纯净版

An old saying *has* it {that half of all advertising budgets *are wasted* -- the trouble is* no one *knows* which half}. ② In the internet age, at least in theory, this fraction *can be much reduced*. ③ [By *watching* what people *search for*, *click on* and *say* online], companies *can aim* “behavioral” ads *at* those most likely to buy.

[In the past couple of weeks] a quarrel *has illustrated* the value [*to* advertisers] *of* such fine-grained information: *Should* advertisers *assume* that {people *are happy to be tracked* and *sent* behavioral ads}? Or *should* they *have* explicit permission?

[In December 2010] America's Federal Trade Commission (FTC) *proposed* {*adding* a "do not track "(DNT) option *to* internet browsers}, *so that* users *could tell* advertisers {that they *did not want to be followed*}. ② Microsoft's Internet Explorer and Apple's Safari both *offer* DNT; Google's Chrome *is due to do so* this year. ③ [In February] the FTC and Digital Advertising Alliance (DAA) *agreed* that {the industry *would get cracking* on responding to DNT requests}.

[On May 31st] Microsoft *Set off* the row: It said that {Internet Explorer 10,the version *due to appear* windows 8, *would have* DNT *as* a default}.

It *is not* yet clear {how advertisers *will respond*}. ② Getting a DNT signal *does not oblige* anyone *to stop tracking*, although some companies *have promised to do so*. ③ *Unable to tell* {whether someone *really objects to* behavioral ads /or whether they *are sticking with* Microsoft’s default}, some *may ignore* a DNT signal /and *press on* anyway.

Also unclear *is* {why Microsoft *has gone* it alone}. ② After all, it has an ad business too, which it *says* will comply with DNT requests, though it *is still working out how*. ③ If it *is trying to upset* Google, which *relies almost wholly on* advertising, it *has chosen* an indirect method: There is no guarantee {that DNT by default *will become* the norm}. ④ DNT *does not seem* an obviously huge selling point *for* windows 8 -- though the firm *has compared* some of its other products *favorably with* Google's [on that count] before. ⑤ Brendon Lynch, Microsoft's chief privacy officer, *blogged* :"we *believe* consumers *should have* more control." Could it *really be* that simple?


---

== 2013-3

Up until a few decades ago, our visions 想象;展望 of the future *were* largely(`=to a great extent; mostly or mainly`) —— though *by no means* 决不 uniformly(`=not varying; the same in all parts and at all times`) —— glowingly(`=highly enthusiastic`)热情洋溢的 positive 积极乐观的；自信的. Science and technology *would cure* 治愈 all the ills of humanity, *leading to* lives of fulfillment 满足(感),成就(感) and opportunity for all.

直到几十年前，我们对未来的想象虽千奇百怪，却大都很积极乐观。科学和技术可以治愈人类所有的疾病，让人们过上满足的生活，让人人都有机会。

Now utopia 乌托邦 *has grown* unfashionable 不流行的；过时的, *as* we *have gained*(`=to obtain or win sth`) a deeper appreciation(`=an understanding of what it involves`) of the range(`=a number of different things of the same general kind`) of threats (facing us), *from* asteroid 小行星 strike *to* epidemic (疾病的)流行，传播 flu and *to* climate change. You might *even be* tempted(a.)被引诱 (而想做) 的 *to assume* 假定;以为;假设 that {humanity has little future *to look forward to* 期待；盼望}.

现如今这种空想的美好社会已经过时了，我们对面临的威胁范围有了更深刻的认识，从行星撞击到流行感冒到气候变化。你可能忍不住会想，人类都没有什么未来值得盼望了。

But such gloominess(`=a feeling of being sad and without hope`) *is* misplaced(a.)(`=not appropriate or correct in the situation`). The fossil 化石 record *shows* that many species 物种 *have endured*(`=to continue to exist for a long time`) for millions of years —— so why *shouldn't* we? *Take a broader look at* our species' place in the universe, and it *becomes clear* {that we *have* an excellent chance of surviving for tens, if not hundreds, of thousands of years}.  

但是这种沮丧的情绪也不应该。化石资料表明，很多物种存活了几百万年——那么我们怎么就不能活那么久呢？眼光放宽一点，想想我们这个物种在宇宙中的位置，就很容易发现，哪怕不能活上几十万年，我们也很可能活上几万年。

*Look up* (在参考书、列表等中)查检(事实或信息) Homo 人属 sapiens(拉)现代人的 in the "Red List红色名录，濒危物种红皮书" of threatened species of _the International Union for the Conservation(对环境的)保护 of Nature (IUCN)_ ,and you will read: "*Listed as* 被列为 Least(`=smallest in size, amount, degree, etc`) Concern 低担忧 *as* 因为 the species *is very widely distributed*(`=to spread sth over an area`), adaptable 能适应的;适应性强的, currently increasing, and there *are* no major threats *resulting in* an overall(`=including all the things or people`) population decline(`=a continuous decrease in the number, value, quality, etc`)."
====
- IUCN : International Union For Conservation Of Nature 国际自然保护联盟
====

查阅一下国际自然保护联盟发布的濒危物种红名单上，对我们人类(智人)的描述，你会读到：非危物种，因为该物种分布很广，适应性强，目前数量呈上升趋势，且没有造成其总体数量下降的主要威胁。

So what *does* our deep future *hold*(`= to own or have sth`)? A growing number of researchers and organisations  *are now thinking seriously about* that question. For example, the Long Now Foundation 基金(会)，基础;根基 *has* [as its flagship(`=the most important product, service, building, etc`) project] a medical 医学的;医疗的 clock that *is designed* to still *be marking 做记号；做标记 time* thousands of years hence(尤指未来的长时间)之后.
====
- Long Now Foundation 恒今基金会, 今日永存基金会; 万年钟基金
- *mark ~ A (with B) /~ B on A* : to write or draw a symbol, line, etc. on sth *in order to give information about it* 做记号；做标记 +
-> Prices *are marked on the goods*. 价格标在商品上。
- hence : ADV You use hence in expressions such as "*several years hence*" or "*six months hence*" to refer to a time in the future, especially a long time in the future. 此后
====

那么，我们的未来究竟承载着什么呢？越来越多的研究者和机构，现在正在仔细思考这个问题。比如，今日永存基金会的首要项目，就是设计一个今后几千年仍然可以度量时间的医疗时钟。

Perhaps willfully 任性, 固执地, it *may be* easier *to think about* such lengthy(`=very long`) timescales than *about* the more immediate 即刻的;紧迫的 future. The potential evolution of today's technology, and its social consequences, is dazzlingly(`=very impressive or beautiful`) complicated(`=it has so many parts or aspects that it is difficult to understand or deal with`), and it's perhaps best *left to* science fiction 小说 writers and futurologists 未来学家 *to explore* the many possibilities we *can envisage*(`=to imagine what will happen in the future`). That's one reason why we *have launched* 推出，发布(新产品) Arc, a new publication *dedicated 献(身);投(身);致力;专用的 to* the near future.
====
- wilful : ADJ If you describe someone as wilful, you mean that *they are determined to do what they want to do, even if it is not sensible*. 任性的
====
思考这么大跨度的时间概念，可能本来就比琢磨眼下的将来更容易许多。今日的技术如何演变，以及由此带来的社会影响，实在纷繁复杂，让人炫目。最好还是让科幻作家和未来学家，去设想那些诸多可能发生的事情吧。这也是我们为什么发行Arc的原因之一。Arc是致力于研究近期未来的全新出版物。

But *take* a longer view /and there is a surprising amount that we *can say* [with considerable(`=great in amount or degree`) assurance 保证, 担保, 确信]. As so often 正如经常发生的那样, the past *holds* (紧紧的)拿，握 the key *to* the future: we *have now identified*(`=to recognize sb/sth`)  enough of the long-term patterns *shaping* the history of the planet, and our species, *to make* evidence-based 基于证据的 forecasts 预测;预言 about the situations *in* which our descendants 后代，子孙 *will find* themselves.

但是眼光放长远些，我们能确信的事情就数量惊人了。过去是未来的关键：我们现在已经知道星球以及我们人类的历史，怎样经历长时间的变化，那么我们就能以此为依据，预知后世子孙未来身处的境地。

This long perspective(`=a way of thinking about sth`) *makes* the pessimistic 悲观的 view of our prospects *seem more likely to be* a passing(`=lasting only for a short period of time and then disappearing`) fad 一时的风尚;风靡一时之物. To be sure 诚然；的确, the future *is not* all rosy 玫瑰色的,充满希望的;前景美好的. But we are now knowledgeable 博学的；有见识的 enough *to reduce*(`=make it smaller in size or amount, or less in degree`) many of the risks that *threatened* the existence of earlier humans, and *to improve* the lot of those (*to come*).
====
- perspective : N-COUNT A particular perspective is *a particular way of thinking about something*, especially one *that is influenced by your beliefs or experiences*. 思维方式; 看法  +
=> per-,完全的，-spect,看，词源同spectate,specter.引申词义观点，看法，态度。 +
-> He says the death of his father 18 months ago *has given him a new perspective on life*. 
 他说18个月前他父亲的去世使他对人生产生了新的看法。
====

这种长远角度，使得悲观的前景预期看似更为过时。的确，未来不都那么美好。但是我们现在有足够的知识，可以减少曾威胁人类早期生存的同类威胁，并改善未来的人们的命运。


---

== 2013-3 纯净版

Up until a few decades ago, `主` our visions of the future `系` *were* largely -- though by no means uniformly -- glowingly positive. ② Science and technology *would cure* all the ills of humanity, *leading to* lives of fulfillment and opportunity for all.

Now utopia *has grown* unfashionable, *as* we *have gained* a deeper appreciation of the range of threats (facing us), *from* asteroid strike *to* epidemic flu /and *to* climate change. ② You might even *be tempted to assume that* {humanity *has* little future *to look forward to*}.

But such gloominess *is* misplaced. ② The fossil record *shows* that {many species *have endured* for millions of years} - so why shouldn't we? ③ *Take a broader look at* our species' place in the universe, and it *becomes clear* that {we *have* an excellent chance of *surviving* for tens, if not hundreds, of thousands of years}. ④ *Look up* Homo sapiens *in* the "Red List" of threatened species of the International Union for the Conversation of Nature (IUCN) ,and you *will read*: "*Listed as* Least Concern 原因状 *as* the species *is* very widely distributed, adaptable, currently increasing, and there are no major threats *resulting in* an overall population decline."

So what *does* our deep future *hold*? `主` A growing number of researchers and organizations `谓` *are now thinking seriously about* that question. ② For example, the Long Now Foundation *has* its flagship project a medical clock that *is designed to still be marking time* thousands of years hence .

Perhaps willfully , it *may be* easier {*to think about* such lengthy timescales *than* *about* the more immediate future}. ② `主` The potential evolution of today's technology, and its social consequences, `系` *is* dazzlingly complicated, and it's perhaps best *left to* science fiction writers and futurologists *to explore* the many possibilities we *can envisage*. ③ That's one reason (why we *have launched* Arc, a new publication *dedicated to* the near future).

But *take a longer view* /and there *is* a surprising amount (that we *can say* [with considerable assurance]). ② As so often, the past *holds* the key to the future: we *have now identified* enough of the long-term patterns *shaping* the history of the planet, and our species, *to make* evidence-based forecasts *about* the situations in which our descendants *will find* themselves.

This long perspective *makes* the pessimistic view of our prospects *seem more likely to be* a passing fad. ② To be sure, the future *is not* all rosy. ③ But we *are* now knowledgeable enough *to reduce* many of the risks that *threatened* the existence of earlier humans, and *to improve* the lot of those (to come).

---

== 2013-4

*On* a five *to* three vote, the Supreme Court *knocked out* 击败；淘汰；摧毁；使瘫痪 much of Arizona’s immigration law [Monday] —— a modest(`=not very large, expensive, important, etc`) policy victory for the Obama Administration. But on the more important matter of the Constitution 宪法, the decision *was* an 8-0 defeat(`=failure to win`) for the Administration’s effort *to upset*(`=to make sth fall over`) the balance of power between the federal government and the states.

周一，最高法院以5比3的投票结果，否决了亚利桑那州移民法的大部分内容——这是奥巴马政府所采取政策的一次不大不小的胜利。但是在更重要的(事关国之根本这个)国家宪法的大问题上，投票结果却是8比0。这个决定意味着，联邦政府打破联邦政府和各州政府权力平衡的努力，彻底失败了。

In Arizona v. United States, 主 the majority(`=the largest part of a group of people`) 谓 *overturned* 推翻，撤销(判决) three of the four contested 争辩;对…提出异议 provisions(`=a condition or an arrangement in a legal document`) of Arizona’s controversial(`=causing a lot of angry public discussion and disagreement`) plan (*to have* state and local police *enforce*(`=force sb to do sth`) federal immigration law).   
====
- 本句的骨架是 : the majority 谓 overturned 宾 provisions (plan to have sb enforce sth)
- provision :  a condition or an arrangement in a legal document （法律文件的）规定，条款 +
=> 来自provide,提供，规定。
====

主 {The Constitutional 宪法的;章程的 principles(`=a law, a rule or a theory that sth is based on`) ① that Washington alone *has* the power *to “establish* a uniform(`=not varying; the same in all parts and at all times`) Rule of Naturalization (外国人的)归化；(动植物的)移植 ”and ② that federal laws *precede* (顺序、位置)先于，在…前面 state laws} 系 *are* non-controversial 无争议的.  +
Arizona *had attempted* 尝试，试图  *to fashion*(`=to make or shape sth`) state policies (that *ran parallel 平行的；并列的 to* the existing 现存的，现行的 federal ones).
====
- 这句话的主干是：The Constitutional principles ①that…… and ②that…… is non-controversial. 即①和②这两条宪法原则，都是无可争议的，因此并不矛盾的。

- precede : V-T If one event or period of time *precedes* another, *it happens before it*. (某事件) 先于 (另一事件) 而发生; (某时段) 先于 (另一时段) 而存在 +
->  Intensive negotiations (between the main parties) *preceded* the vote.  投票之前，主要政党间进行了深入细致的磋商。

- *fashion (v.) ~ A (from/out of B) /~ B (into A)* : to make or shape sth, especially with your hands （尤指用手工）制作，使成形，塑造 +
-> She *fashioned a pot* from the clay. 她用黏土制成一个罐。
====

在这场亚利桑那州政府，和美国政府的对峙中，最高法院以多数票通过，推翻了亚利桑那州饱受争议的计划中，四项有争议条款中的三项。亚利桑那州，本计划让州警察和地方警察，实施联邦移民法。 +
宪法规定，华盛顿自身有权力“制定统一的移民规则”，这和联邦法律优先于州法律的规定，并不矛盾。亚利桑那州企图改变该州现行的与联邦法律一致的政策。

Justice 法官 Anthony Kennedy, *joined by* Chief Justice John Roberts and the Court’s liberals 自由主义者,  谓 *ruled*(`=to give an official decision about sth`) that 宾 {the state *flew(=fly) too close to* the federal sun}.  +
[On the overturned provisions] 主 the majority 谓 *held*(`=to have a belief or an opinion about sb/sth`) 宾 {the congress 代表大会 *had deliberately “occupied* 占领；占据；侵占 the field” /and Arizona *had thus 所以;因此 intruded 侵入,侵扰干扰;扰乱 on*  the federal’s privileged(`=having special rights or advantages`) powers}.
====
- *intrude (v.) ~ (into/on/upon sb/sth)* : to go or be somewhere where you are not wanted or are not supposed to be 闯入；侵入；打扰 +
-> *I'm sorry to intrude*, but I need to talk to someone. 对不起打扰了，不过我得找人有话要说。
====

安东尼·肯尼迪大法官，同约翰·罗伯特首席大法官，和法庭的自由派们一起，裁定州政府的做法不对。关于被推翻的条款，大多数人的观点是，州议会已经故意“占领地盘”了，也就是说，亚利桑那州侵犯了联邦的特权。

However, the Justices *said* that Arizona police *would be allowed* to verify(`=to check that sth is true or accurate`) the legal status 法律地位，法律身份，状况 of people (who come *in contact 保持联系;有联系 with* law enforcement).  +
That’s because Congress *has always envisioned*(`= to imagine what will happen in the future`) {① *joint* federal-state immigration enforcement 移民执法行动 and ② explicitly 明确地；明白地 *encourages* state officers *to share* information ③ and *cooperate with*(`=to work together with sb else`) federal colleagues 同事;同僚}.

然而，大法官们说，亚利桑那州警察有权力在执法过程中，核实人们的法律身份。因为国会一直期待，能联合联邦和各州的力量，处理移民问题，并公开鼓励州警官和联邦警官，共享信息，相互合作。

Two of the three objecting(a.)(`=dislike or disapproval of it`) Justice ——Samuel Alito and Clarence Thomas —— *agreed with* this Constitutional 宪法的,合乎宪法的 logic but *disagreed about* ｛which Arizona rules *conflicted (想法、信仰或陈述)冲突，抵触 with* the federal statute(`=a rule or law`)｝.

The only major objection 异议;反对意见 *came from* Justice Antonin Scalia, who *offered* an even more robust(`=strongly held and forcefully expressed`) defense 防卫，防护 of state privileges(`=a special right or advantage`) 伴随状 *going back to* 追溯到，回到...上来 _the alien 外国人,外侨 and Sedition 煽动反政府的言论(或文章、行为) Acts(`=a law`)_.
====
- sedition => se-表示"分开，离开，区别开"。sedition 煽动叛乱(sed=se+it 走＋ion→分开走→煽动叛乱)
====
三名持反对意见的大法官中，有两人——塞缪尔·阿利托和克拉伦斯·托马斯，赞同宪法的逻辑思路，却不同意亚利桑那州的规定违反联邦法规的说法。唯一主要的反对意见，来自安东宁·斯卡利亚大法官，他强烈维护州的权益不受联邦干预，甚至提到了客籍法和镇压叛乱法。

The 8-0 objection (to President Obama) *turns on* 依靠;取决于 {what Justice Samuel Alito *describes* [in his objection] *as* “a shocking assertion(`=a statement saying that you strongly believe sth to be true`) of federal executive power”}.
====
- assertion => sert =join,insert,表示"加入,插入",来自拉丁语 说明:(as+sert+ion强行插入观点→断言)
- If something *turns on* a particular thing, *its success or truth depends on that thing*. 依靠;取决于  +
-> The plot *turns on* whether Ilsa will choose her lover or her husband. 故事情节取决于伊尔莎会选择情人还是丈夫。
====

The White House *argued* that {Arizona’s laws *conflicted 抵触, 冲突 with* its enforcement priorities 优先；优先权；优先次序, even if state laws *complied(`=to obey a rule`) with* federal statutes(`=a rule or law`) *[to the letter]* (执行指示)毫厘不爽地，不折不扣地}. 

In effect, the White House *claimed* 声称;断言 that {it *could invalidate* 使无效;使作废 any otherwise legitimate 合法的；依法的；法律认可的 state law (that it *disagrees with*)} .
====
- priority (n.): PHRASE If something *takes priority* or *has priority over* other things, *it is regarded as being more important than them and is dealt with first*. 有优先性 +
=> prim,prin,prior: =first/chief,表示"第一,主要的;首要" 

- *to the letter* : *doing/following exactly* what sb/sth says, paying attention to every detail 丝毫不差；不折不扣；精确地 +
-> I *followed* your instructions *[to the letter]*. 我是严格遵照你的指示办的。

- invalidate => val,vail=strong，表示"强壮"。invalidate v 使….无效(in 无+valid 有效的+ate→有效变无效)
====

这次反对奥巴马总统出现8:0投票结果，是由于萨缪尔·阿里托大法官在他的反对意见中, 将高于州权的联邦权力（即，前三段观点）描述为“对联邦执行权令人震惊的维护”。 白宫声称，亚利桑那州的法律与其执法优先权相冲突，即使州法律严格遵守了联邦法律。实际上，白宫就是在声明，它将作废任何联邦不赞成的合法的州级法律。


Some powers do 的确 *belong exclusively 排他地; 独占地 to* the federal government, and control of citizenship 国籍;公民身份 and the borders *is* among them.  +
But if Congress *wanted to prevent* states *from* using their own resources *to check* immigration status(`=your social or professional position`), it *could*. It(指Congress) never did so. 

The administration *was* [in essence 本质上;实质上] *asserting*(`=state it firmly`) that {because it *didn’t want to carry out*(`=do it`) Congress’s immigration wishes, no state should *be allowed* to do so either (两者之中)任何一个}. 

Every Justice *rightly 正确地；恰当地；公正地；合适地 rejected*(`=to refuse to accept or consider sth`) this remarkable(`=is unusual or special in a way that makes people notice them and be surprised or impressed`) claim(`=to say that sth is true although it has not been proved and other people may not believe it`).

有些权力确实归联邦政府独有，控制国籍和国界就是如此。但是如果国会想阻止各州使用自己的资源查看移民身份的话，国会是可以这么做的。可国会从没有这么做过。美国政府事实上就是在宣称，因为它不想实现国会的移民主张，哪一个州也不可以这么做。每一位大法官都端正的反对了这样的主张。


== 2013-4 纯净版

On a five to three vote, the Supreme Court *knocked out* much of Arizona's immigration law [Monday] -- a modest policy victory for the Obama Administration. ② But [on the more important matter of the Constitution], the decision *was* an 8-0 defeat *for* the Administration's effort *to upset* the balance of power between the federal government and the states.

In Arizona v. United States, the majority *overturned* three of the four contested provisions of Arizona's controversial plan *to have* state and local police *enforce* federal immigration law. ② `主` The Constitutional principles (*that* Washington alone *has* the power *to "establish* a uniform Rule of Naturalization" /and *that* federal laws *precede* state laws) `系` *are* noncontroversial. ③ Arizona *had attempted to fashion* state policies that *ran parallel to* the existing federal ones.

Justice Anthony Kennedy, *joined by* Chief Justice John Roberts and the Court's liberals, *ruled* that {the state *flew too close to* the federal sun}. ② [On the overturned provisions] `主` the majority `谓` *held* `宾` {the congress *had deliberately "occupied* the field" /and Arizona *had thus intruded on* the federal's privileged powers}.

However, the Justices *said* that {Arizona police *would be allowed* {*to verify* the legal status of people who *come in contact with* law enforcement}}. ② That's because `主` Congress *has always envisioned* `宾` {*joint* federal-state immigration enforcement /and *explicitly encourages* state officers *to share* information and *cooperate with* federal colleagues}.

Two of the three objecting Justice -- Samuel Alito and Clarence Thomas -- *agreed with* this Constitutional logic /but *disagreed about* which Arizona rules *conflicted with* the federal statute. ② The only major objection *came from* Justice Antonin Scalia, who *offered* an even more robust defense (of state privileges) 伴随状 *going back to* the Alien and Sedition Acts.

The 8-0 objection (to President Obama) *turns on* {what Justice Samuel Alito *describes* in his objection *as* "a shocking assertion of federal executive power"}. ② The White House *argued* that {Arizona's laws *conflicted with* its enforcement priorities, even if state laws *complied with* federal statutes [to the letter]}. ③ In effect, the White House *claimed* that {it *could invalidate* any otherwise legitimate state law that it *disagrees with*}.

Some powers *do belong exclusively to* the federal government, and control of citizenship and the borders *is* among them. ② But [if Congress *wanted to prevent* states *from* using their own resources *to check* immigration status], it could. ③ It never did so. ④ The administration *was [in essence] asserting* that {because it *didn't want to carry out* Congress's immigration wishes, no state *should be allowed to do so* either}. Every Justice *rightly rejected* this remarkable claim.



