# 2014
:toc:

---

## 2014-01.

In order to *“change* lives *for* the better” and *reduce* “dependency” George Osborne, Chancellor(`=the head of government in Germany or Austria`) of the Exchequer(英国的)财政部, *introduced* the “upfront(`= paid [in advance]`) work search” scheme.

Only [if the jobless *arrive at* the job centre *with* a CV(= curriculum vitae)(拉丁文)履历，简历, *register for* online job search, and *start* looking for work] *will* they *be eligible 有资格的;符合条件的;有能力的 for* benefit(`=money provided by the government to people who need financial help`) and then they *should report weekly* rather than fortnightly 两星期一次的;隔周发行的.

What *could be* more reasonable (决定或行动)公平的，合理的?

为了“让生活变得更美好”以及减少“依赖”，英国财政大臣乔治·奥斯本引入了“求职预付金”计划。只有当失业者带着简历到就业中心，注册在线求职，并开始找工作，才有资格获得补助金——然后他们应该每周而非每两周报告一次。有什么比这更合理呢？

More apparent reasonableness 合理,妥当 *followed* (文章或讲演)接下来是,后面的是，下面是. There will now *be* a seven-day wait for the jobseeker’s allowance (定期发给的)津贴，补助. “Those first few days *should be spent* looking for work, not looking *to sign on* 办理失业登记(以领取失业救济金).” he claimed. “We’re doing these things because we know {they *help* people *stay off* 不在…处停留,远离 benefits 救济金，补助金 and *help* those on benefits *get into work* faster}.”

更加明显的合理性如下。现在领取求职者补贴，要等待七天。“这前几天应该用来找工作，而不是办理失业登记(以获得救济金)。”他说，“我们这样做，是因为我们知道，这样会帮助人们摆脱补助，并让依赖补助的人尽快就业。”

Help? Really? On first hearing 乍一听, this *was* the socially concerned chancellor (英国的)财政大臣, trying *to change* lives *for* the better, *complete with* 包括，含有(额外部分或特征) “reforms” *to* an obviously indulgent 纵容的;宽厚的;溺爱的 system (that *demands* too little effort [*from* the newly unemployed(a.)] *to find work*, and *subsidizes*(`=to give money to sb or an organization to help pay for sth`)资助；补助 laziness).

====
- If one thing comes *complete(a.) with* another, *it has that thing as an extra or additional part*. 包括，含有(额外部分或特征) +
-> The diary comes complete with a gold-coloured ballpoint pen. 这个日记本配有一支金色的圆珠笔。

- subsidy v.资助；补助；给…发津贴 => sub-,在下，-sid,坐下，安排，词源同 sit,settle.引申比喻义帮助，援助，后用于指补贴，津贴， 资助费等。比较其同源异义词 subside,沉降。
====

帮助？真的吗？乍一听，这是位关心社会的大臣，他努力改善人们的生活，包括对一个明显放纵的体系的“改革”，这个体系不要求新失业者付出多少努力去找工作，为其懒惰埋单。

主 What *motivated*(`= to make sb want to do sth`) him, we were to understand, 系 *was* his zeal 热情;激情;热忱 for “ fundamental(`=serious and very important`) fairness 公平;公正”— *protecting* the taxpayer, *controlling* spending 开销；花费 and *ensuring* that {only the most deserving 值得帮助的;应受支持的 claimants 申请人;要求者；领取失业救济金的人 *received* their benefits(`=money provided by the government to people who need financial help because they are unemployed, ill/sick, etc`)}.
====
- we were to understand : *在不同的语境中，“be+动词不定式”结构可以表示多种不同的语义。*
====

我们将会知道，激励他的是他对“基本的公正”的热诚——保护纳税人，控制花费，以及确保只有最值得帮助的申请者，才能得到补助金。

Losing a job is hurting 受伤害的: you don’t *skip 蹦蹦跳跳地走 down to* the jobcentre 职业介绍所 with a song in your heart, *delighted*(`= to give sb a lot of pleasure and enjoyment`) *at* the prospect of *doubling*  (使)加倍 your income *from* the generous (尤指在钱财上)慷慨的，大方的 state.

It is financially 财政上 terrifying(`=makes you very frightened`), psychologically 心理上地 embarrassing and you *know* that {support is minimal 最小的;极少的 and extraordinarily(`=extremely`) hard *to get*}.

You *are* now *not wanted* 不被需要; you *are* now *excluded 将…排除在外;不包括 from* the work environment that *offers* purpose(`=the intention, aim or function of sth`) and structure 结构体；建筑物 in your life. Worse, the crucial(`=extremely important`) income (① *to feed* yourself and your family and ② *pay* the bills) *has disappeared*. Ask anyone (newly unemployed) what they *want* /and the answer is always: a job.

失业是痛苦的：你不会内心歌唱并跳跃着到就业中心去，为从这个慷慨国度得到加倍收入的前景而欣喜。在经济上它令人生畏，在心理感到难堪，并且你还知道，那种扶持的微薄和非常难以得到。
现在没人需要你；你现在被排除在工作环境之外，那里会给予你人生的目标和体制。更糟糕的是，失去了用以养家糊口和支付账单的至关重要的收入。问任何新失业者他们想要什么，答案永远是：一份工作。

But in Osborneland, your first instinct 本能，直觉；天性 *is* 表 *to fall into* dependency —— permanent(`=lasting for a long time`)  dependency if you can *get* it —— *supported* by a state (only *too* ready *to indulge* 纵容;迁就;娇惯 your falsehood(`= the act of telling a lie`)).

It is as though 仿佛,好像 20 years of ever-tougher (政策或行动)强硬的，严厉的 reforms of ① the job search and ② benefit administration system *never happened*.
但是在奥斯本之国，你的第一反应就是坠入依赖——永远的依赖，如果你能得到的话——它由一个非常乐意放任你弄虚作假的国家所支持。好像这二十年，一直严厉的求职和补助金管理系统的改革，从未发生过。

The principle(`= a rule or a theory that sth is based on`) of British welfare 福利；社会保障金 is no longer that {① you can *insure 投保；给…保险 yourself against* the risk of unemployment and ② *receive* unconditional 无条件的；无限制的 payments if the disaster *happens*}.

Even the very phrase 短语,词组 “jobseeker’s allowance (定期发给的)津贴，补助” — *invented* in 1996 — *is* about *redefining* 重新定义 the unemployed *as* a “jobseeker” who *had no* fundamental right 基本权利 to a benefit (he or she *has earned* [through 通过；凭借 making national insurance contributions 全国保险税]).
====
- contribution : *a sum of money that you pay regularly to* your employer or *the government* in order to pay for benefits such as health insurance, a pension, etc. （给雇主或政府用作医疗保险、养老金等津贴的）定期缴款
====

Instead 作为替代;反而;相反地, the claimant 申请人;要求者 *receives* a time-limited “allowance (定期发给的)津贴，补助,” conditional 有条件的;有前提的 *on* actively 积极地；活跃地 *seeking* a job; no entitlement (拥有某物或做某事的)权利，资格 and no insurance 保险, at £71.70 a week, one of the least 最小的；最少的(little的最高级) generous (尤指在钱财上)慷慨的，大方的 in the EU.
====
- entitlement : ~ (to sth) : *the official right to have or do sth* （拥有某物或做某事的）权利，资格 +
-> This may affect *your entitlement(n.) to compensation*. 这可能影响你索赔的权利。
====

英国福利的原则不再是，如果发生灾难，你能为自己投保失业险，和得到无条件赔付。甚至是“求职者津贴”这个创造于1996年的术语，也是将失业者重新定义为没有领取救济金这一基本权利的“求职者”，而这份救济金是他或她通过缴纳国家保险费所赢得的。
作为替代，申请者得到的是一周71.70 英镑的限时“补贴”，条件是积极地找工作：没有津贴也没有保险，在欧盟这也是最小气之一了。

---

== 2014-01 纯净版

In order to “*change* lives *for* the better” and *reduce* “dependency,” George Osbome, Chancellor of the Exchequer, *introduced* the “upfront work search” scheme. ② [Only if the jobless *arrive at* the job centre *with* a CV *register for* online job search, and *start looking for* work] *will* they *be eligible for* benefit -- and then they *should report weekly* rather than fortnightly. ③ What *could be* more reasonable?

More apparent reasonableness *followed*. ② There *will now be* a seven-day wait for the jobseeker’s allowance. ③ “Those first few days *should be spent* looking for work, not looking to sign on.” he claimed. ④ “We’*re doing* these things because we *know* {they *help* people *stay off* benefits /and *help* those on benefits *get into work faster*}” ⑤ Help? Really? On first hearing, this *was* the socially concerned chancellor, *trying to change lives* for the better, *complete with* “reforms” *to* an obviously indulgent system (that *demands* too little effort *from* the newly unemployed *to* find work, and *subsides* laziness). ⑥ `主` What *motivated* him, we were to understand, `系` *was* his zeal for “fundamental fairness” -- *protecting* the taxpayer, *controlling* spending /and *ensuring* that only the most deserving claimants *received* their benefits.

Losing a job *is* hurting: you *don’t skip down to* the jobcentre *with* a song in your heart, *delighted at* the prospect of *doubling* your income from the generous state. ② It *is* financially terrifying, psychologically embarrassing and you *know* that {support is minimal /and extraordinarily hard to get}. ③ You *are now not wanted*; you *are now excluded from* the work environment that *offers* purpose and structure *in* your life. ④ Worse, the crucial income (*to feed* yourself and your family /and *pay* the bills) *has disappeared*. ⑤ *Ask* anyone newly unemployed what they want /and the answer is always: a job.

But in Osborneland, your first instinct *is* to fall into dependency -- permanent dependency if you can get it -- *supported by* a state (only *too* ready *to indulge* your falsehood). ② It is as though 20 years of ever-tougher reforms of the job search and benefit administration system *never happened*. ③ The principle of British welfare *is* no longer that {you *can insure* yourself *against* the risk of unemployment /and *receive* unconditional payments if the disaster *happens*}. ④ Even `主` the very phrase ‘jobseeker’s allowance’ -- *invented* in 1996 -- `系` *is* about {*redefining* the unemployed *as* a “jobseeker” who had no fundamental right to a benefit (he or she *has earned* through *making* national insurance contributions)}. ⑤ Instead, the claimant *receives* a time-limited “allowance,” conditional on *actively seeking* a job; no entitlement and no insurance, at £71.70 a week, one of the least generous in the EU.

---

## 2014-02.


All around the world, lawyers *generate* 造成；引起；导致 *more* hostility(`=unfriendly or aggressive feelings or behaviour`) *than* the members of any other profession (需要高等教育或训练的)职业——with the possible *exception of* journalism 新闻业. But there are few places where clients *have more grounds(`= good or true reason`) for* complaint *than* America.
====
- *ground ~ for sth/for doing sth* : a good or true reason for saying, doing or believing sth 充分的理由；根据
====

在全世界，律师比任何其他职业的人都更招憎恨——新闻业可能是个例外。但是没有多少地方能比美国更让客户有更多的理由抱怨。

During the decade before the economic crisis, spending (on legal(a.)(`= connected with the law`) services in America) *grew* twice as fast as inflation 通货膨胀. The best lawyers *made skyscrapers* ——full of money, *tempting* 引诱;诱惑;吸引 ever more students *to pile into* 拥进；挤进；摞叠 law schools.

But most law graduates 大学毕业生 *never get* a big-firm job. Many of them [instead 作为替代;反而;相反地] *become* the kind of nuisance(`=sth that is annoying or causes trouble or problems`) —— lawsuit 诉讼；官司 filer 文件编档员 / that *makes* the tort 侵权行为 system 宾补a costly nightmare.
====
- nuisance => 词源同necro-,noxious,innocent.后词义弱化，用来指妨害行为，讨厌的人。
- tort : (n.) ( law 律 ) *something wrong that sb does to sb else* that is not criminal, but that can lead to action in a civil court 侵权行为(不构成刑事犯罪但可引起民事诉讼)
====

在经济危机之前的十年间，美国法律服务费用的增长速度，是通货膨胀的两倍。最好的律师赚得盆满钵满，吸引着更多的学生争相进入法学院。但是大部分法学毕业生，从未获得一份大律所的工作。他们当中的许多人反而成为了那种妨碍民事诉讼的文件编档员，他们使得在侵权索赔制度上的花费如噩梦。

There are many reasons for this. One *is* the excessive 过度的,过分的 costs of a legal education. There is just one path for a lawyer in most American states: a four-year undergraduate(`=a university or college student who is studying for their first degree`) degree in some unrelated 无关的，不相干的 subject(`=an area of knowledge or study`), then a three-year law degree at one of 200 law schools (*authorized(`=to give official permission for sth`) by* the American Bar (美国的)律师职业，律师界 Association) and an expensive preparation 准备；预备；筹备 for the bar exam.

This *leaves*(`=to make sth happen or remain as a result`) today’s average law-school graduate with $100,000 of debt *on top of* 另外;加之;除…之外(还) undergraduate debts.
Law-school debt *means* that many *cannot afford* to go into government or non-profit work, and that they have to *work(v.) fearsomely*(`=making people feel very frightened`) hard.
- You can use *on top* or *on top of* to indicate that a particular problem exists *in addition to* a number of other problems.

这里面有很多原因。其一是法律教育的费用过高。在美国大部分州，只有一条成为律师的途径；在某个无关的专业读四年取得本科学位，然后在美国律师协会授权的200 所法学院之一，读三年取得法律学位，并为准备律师资格考试花费不菲。这给现在这些普通的法学院毕业生留下在本科债务之外，10 万美元的债务。(这让如今的法学院毕业生承担平均10万美元的债务，居本科生债务之首。)法学院的债务意味着, 许多人无法承担政府或非盈利机构的工作，他们不得不拼命工作。

Reforming the system 谓 *would help* both lawyers and their customers. Sensible (行为或决定)明智的，理智的，合理的 ideas *have been around* for a long time, but the state-level bodies 团体；机构；组织 (that *govern*(v.) the profession) *have been* too conservative 保守的;因循守旧的 *to implement*(`=to make sth. start to happen or be used`) them.

One idea is *to allow* people *to study* law *as* an undergraduate 本科生 degree. Another is to let students *sit (v.)参加(考试) for* the bar [after only two years of law school]. If the bar exam *is* truly a stern(`= serious and difficult`) enough test *for* a would-be 想要成为…的 lawyer, those (who can *sit 参加(考试) it earlier*) should *be allowed to do so*. Students (who *do not need* the extra training) *could cut* their debt mountain *by* a third 三分之一.
- *sit (v.) ~ (for) sth* : ( BrE rather formal ) to do an exam 参加考试；应试

改革这一体系，会对律师和他们的客户都有所帮助。明智的想法已经存在了好长时间，但是管理该职业的州级机构对实施它们太保守了。
一个想法是，准许人们读本科学位时学习法律。另外一个是，让学生在法学院只读两年之后，就参加律师资格考试。如果这一考试对于一名准律师来说确实是足够严格的测试，那么就应该准许那些有能力提早参加的学生们参加。不需要额外培训的学生，就可以削减他们债务大山的三分之一。

The other reason (why costs are so high) *is* the restrictive 限制性的;约束性的 guild 同业公会；行会；协会 —— like ownership(`=the fact of owning sth`) structure 所有制结构 of the business. Except in the District of Columbia, non-lawyers 非律师 *may not own* any share of a law firm. This *keeps* fees high and innovation(`=new thing or a new method of doing something`) slow.
====
- guild : (n.) an organization of people who do the same job or who have the same interests or aims （行业）协会
====

There is pressure for change(n.) [from within(`=inside sth/sb`) the profession (某一专业工作的)全体人员，业界人士，专业界], but opponents(`=a person who is against sth`) of change (among the regulators (某行业等的)监管者，监管机构 *insist* that {主 *keeping* outsiders 外人 *out of* a law firm 谓 *isolates* 使隔离 lawyers *from* the pressure (to make money) rather than *serve* clients *ethically* 伦理地，道德地}.
====
- 注意，最后一句有省略存在, 完整的语句是: rather than (*isolates* lawyers *from* the pressure *to) serve* clients ethically. 括号中的就是省略掉的内容.  即, 将局外人排除在外, 能使律师与"赚钱压力"相隔离, *而非与"有道德地来服务客户"相隔离.* 换句话说, *千万不要以为否定词rather than 否定的是 serve client ethically(那样的话，serve应该变成动名词serving)。*
====

费用如此之高的另外一个原因是，该行业限制性的同业公会式的所有权结构。除哥伦比亚特区外，非律师人员不得持有律所的任何股份。这使得费用居高不下而创新脚步缓慢。
在行业内部存在要求变革的压力，但是监管部门中的反对变革者坚称，将局外人排除在律所之外，可以让律师与赚钱的压力隔离，而合乎职业道德标准地为客户服务。

In fact, {*allowing* non-lawyers *to own shares* in law firms} 谓 *would reduce costs* and *improve services to* customers, 方式状[by ① *encouraging*(`=to give sb support, courage or hope`) law firms *to use* technology and ② *to employ* professional managers *to focus on* *improving* firms’ efficiency].

After all, other countries, such as Australia and Britain, *have started* *liberalizing*(v.)(`=to make sth less strict`) their legal professions 职业. America *should follow*.

实际上，准许非律师人员参股，通过鼓励律所采用新技术和聘请职业经理人，来致力于提高律所效率，可以降低成本并改善对顾客的服务。毕竟，其它国家如澳大利亚和英国，都已开始使其法律行业自由化。美国应该效仿。

---
== 2014-02 纯净版

All around the world, lawyers *generate* more hostility *than* the members of any other profession -- with the possible exception of journalism. But there are few places where clients *have more grounds for complaint* than America.

During the decade before the economic crisis, spending (on legal services in America) *grew* twice as fast as inflation. ② The best lawyers *made* skyscrapers-full of money, *tempting* ever more students *to pile into* law schools. ③ But most law graduates *never get* a big-firm job. ④ Many of them instead *become* the kind of nuisance -- lawsuit filer (that *makes* the tort system 宾补 a costly nightmare).

There *are* many reasons for this. ② One is the excessive costs of a legal education. ③ There is just one path for a lawyer [in most American states]: a four-year undergraduate degree at one of 200 law schools *authorized by* the American Bar Association /and an expensive preparation for the bar exam. ④ This *leaves* today’s average law-school graduate *with* $100,000 of debt *on* top of undergraduate debts. ⑤ Law-school debt *means* that they *have to work fearsomely hard*.

*Reforming* the system *would help* both lawyers and their customers. ② Sensible ideas *have been around* for a long time, but the state-level bodies (that *govern* the profession) have been *too* conservative *to implement* them. ③ One idea is `表` *to allow* people *to study* law *as* an undergraduate degree. ④ Another is `表` *to let* students *sit for* the bar after only two years of law school. ⑤ If the bar exam *is* truly a stern enough test *for* a would-be lawyer, those who *can sit* it earlier *should be allowed* to do so. ⑥ Students (who *do not need* the extra training) *could cut* their debt mountain *by* a third.

The other reason why costs are so high *is* the restrictive guild -- like ownership structure of the business. ② Except [in the District of Columbia], non-lawyers *may not own* any share of a law firm. ③ This *keeps* fees high and innovation slow. ④ There is pressure for change [from within the profession], but opponents of change among the regulators *insist* that {`主` *keeping* outsiders *out of* a law firm `谓` *isolates* lawyers *from* the pressure *to make money* rather than *serve* clients ethically}.

In fact, `主` *allowing* non-lawyers *to own* shares in law firms `谓` *would reduce* costs /and *improve* services *to* customers, by *encouraging* law firms *to use* technology /and *to employ* professional managers *to focus on* improving firms’ efficiency. ② After all, other countries, such as Australia and Britain, *have started* liberalizing their legal professions. America *should follow*.

---

## 2014-03.

The US$3-million Fundamental(`=central; forming the necessary basis of sth`) physics 基础物理学 prize *is* indeed 确实;的确 an interesting experiment 实验,试验, *as* Alexander Polyakov *said* [when he *accepted* this year’s award in March]. And it is far from 远非 the only one of its type.

*As* a News Feature(`=a special article or programme about sb/sth`) article in Nature *discusses*(`=to talk about sth with sb`), a string一系列，一连串(类似事件) of lucrative(a.)(`=making a large profit`) awards for researchers *have joined*(`=to take part in`) the Nobel Prizes in recent years.

Many, like the Fundamental Physics Prize, *are funded(`=to provide money for sth`) [from* the telephone-number-sized bank accounts of Internet entrepreneurs 企业家]. These benefactors 捐助者；赞助人；施主 *have succeeded in* their chosen fields, they say, and they *want to use* their wealth *to draw 使注意;引起…注意 attention to* those who *have succeeded in* science.
====
- News Feature 新闻特稿
- lucrative : ADJ. A lucrative activity, job, or business deal is *very profitable*. 获利丰厚的 +
=> 来自拉丁语lucrum,财富，收益，常用于贬义指不义之财。可能来自PIE*rei,撕，抢，词源同rob,rip.比较loot.
====

300 万美元的基础物理学奖，的确是一个有趣的尝试，正如亚历山大·帕里雅科夫三月份领取今年奖项时所言。而且该类奖项远非仅此一例。按照《自然》杂志新闻特写栏目一篇文章所讨论的，近年来，一系列奖金丰厚的研究奖项，已经加入诺贝尔奖的行列。许多奖项(如基础物理学奖)来自于互联网企业家的资助，其银行账户是电话号码数量级的。 据称，这些慈善家在各自从事的领域已经获得成功，想用自己的财富，去让那些有科学成就的人士受到关注。

What’s not to like? Quite 相当;很;颇 a lot, *according to* a handful 一把；几个;少数 of scientists (*quoted* 援引，引述;引用 in the News Feature). You *cannot buy* class 社会等级;阶层, *as* the old saying *goes* 正如老话所说, and these upstart(初到某地或初出茅庐却)自命不凡的家伙；暴发户, 新贵 entrepreneurs 企业家 *cannot buy* their prizes 双宾the prestige 声望；威望；威信 of the Nobles, The new awards *are* an exercise(`=the use of power, a skill, a quality or a right to make sth happen`) in self-promotion 自抬身价 for those behind them, *say* scientists. They *could distort*(`=to twist or change facts, ideas, etc`) the achievement 成就;成绩-*based* system of peer-review-led 由同行评议引导的 research.
====
- upstart : n. ( disapproving ) *a person who has just started in a new position* or job *but who behaves as if they are more important* than other people, *in a way that is annoying* 自命不凡的新上任者；狂妄自大的新手
====

They *could cement*(`=to make a relationship, an agreement, etc. stronger`) the *status quo* 现状;原状 of peer-reviewed research. They *do not fund*(`=to provide money for sth`) peer-reviewed research. They *perpetuate*(`=to make sth such as a bad situation, a belief, etc. continue for a long time`) the myth of the lone 独自的；寂寞的；单身的 genius 天才.
====
- *as the old saying goes* : 正如老话所说

- upstart : (n.)( disapproving ) a person *who has just started in a new position* or job *but who behaves as if they are more important* than other people, in a way that is annoying 自命不凡的新上任者；狂妄自大的新手

- *status quo* ：n.现状;原状 The *status quo* is *the state of affairs that exists at a particular time*, especially *in contrast与…截然不同;与…对比鲜明 to* a different possible state of affairs. +
-> They have no wish for any change *in the status quo*... 他们不想改变现状。

- perpetuate :V-T If someone or something perpetuates(v.) a situation, system, or belief, especially a bad one, *they cause it to continue*. 使继续 (尤指不好的情形、体系或信仰) +
=> per-,完全的，-pet,寻求，追寻，词源同compete,petition.引申词义持续，坚持。
====

这有什么让人不喜欢的呢？据新闻特写栏目中援引一小部分科学家所言，非常之多。古语云，有钱买不到社会地位，这些暴富的企业家并不能为他们的奖金买来诺贝尔奖的声望。科学家称，新设奖项是那些幕后人自抬身价的一种举动。它们会扭曲基于成就并由同行评议引导的研究体系。它们会巩固同行评议研究的现状。它们并不资助同行评议研究。它们延续了孤独天才的神话。

The goals of the prize-givers *seem* [as scattered as the criticism]. Some *want to shock*, others *to draw* people *into* science, or *to better reward* those who *have made* their careers in research.

奖项提供者的目标, 似乎如他们所受的批评一样散乱. 有些人是想要制造震惊，另一些人想要吸引人们关注科学，或者想更好地奖励那些以科研为己任的人。


*As* Nature *has pointed out* before, there *are* some legitimate(a.)(`=there is a fair and acceptable reason`) concerns about how science prizes —— both new and old —— *are distributed* 分发;分配;分送.
The Breakthrough 突破；重大进展 Prize in Life Sciences, *launched*(`=to start an activity`) this year, *takes* an unrepresentative 不具代表性的；不典型的 view 观点;看法;见解;态度 of what the life sciences *include*.

正如《自然》杂志以前已经指出的那样，对于科学奖项 ——新设的和原有的—— 如何分配，存在某些忧虑，是合理的。今年推出的“生命科学突破奖”，对生命科学的范畴所持观点，并不具代表性。

But 主 the Nobel Foundation’s 基金(会) limit(n.) of three recipients 接受者；领受人 per prize, each of whom *must still be living*, 谓 *has long been outgrown* 长得比…快（大），发展的比…快；过大而不适于 [by the collaborative 合作的;协作的 nature 本质;性质 of modern research] —— *as* will *be demonstrated*(`=to show sth clearly by giving proof or evidence`) [by the inevitable 不可避免的,必然发生的 row （n.）争执;争论 over who *is ignored* 忽略;忽视 [when it *comes to* acknowledging 承认（事实、局面等） the discovery of the Higgs boson 希格斯玻色子]].
====
- each of whom must still be living 是定语从句, 用来修饰前面的 recipient.
- 破折号的右边是一个由 as 引导的非限制性定语从句，我们可以把 as 替换成which，这样可能更好理解：which will be demonstrated by the inevitable row...
- 最后是一个when引导的时间状语从句.
====

The Nobles *were*, of course, themselves *set up 创建;建立 by* a very rich individual个人 who *had decided* what he *wanted to do with* his own money.
Time, rather than 而不是 intention 意图;目的;打算, *has given* them legitimacy 合法(性);正统(性).

但是诺贝尔基金会对每一奖项只能由三名仍在世者获得的限制，由于现代科学研究的协作特性而早已不再适宜——以下就是个例子：人们必将会为希格斯波色子的发现者中谁可以被忽略这件事情而争论不休。
当然，诺贝尔奖本身就是由一位富豪个人设立的，他决定了用自己的金钱去做他想要做的事。赋予诺贝尔奖合理性的是时间，而非设立的初衷。

As much as some scientists *may complain 抱怨;发牢骚 about* the new awards 奖项；判决, two things *seem* clear.
First, most researchers *would accept* such a prize if they *were offered* 提供；给予 one.
Second, *it is* surely a good thing ｛ *that* the money and attention *come to* science *rather than* go elsewhere｝,

It is fair *to criticize* and *question* the mechanism 机制，行为方式 —— that is the culture of research, after all —— but it is the prize-givers’ money (*to do with* [as they please (愿意；喜欢；认为合适) 随你的心意,如其所愿]). It is wise(`=sensible`) *to take* such gifts [with gratitude(n.)感恩之情；感谢 and grace(`=the ways of behaving and doing things which are considered polite and well-mannered`)].
====
- to do with as they please : 不定式作后置定语，修饰限定 money.
- as 引导方式状语从句，意为“按照他们所喜欢的方式”。
====

有些科学家常常会抱怨新的奖项，有两件事却是显而易见。第一，如果被授予这样的奖项，大部分研究人员会接受它。第二，金钱和关注度投向科学而不是其它地方，这无疑是好事。批评和质疑这种机制是公平合理的——毕竟这是做研究的文化——但它是奖金提供者，按照自己的意愿处置的金钱。以感谢的心情和优雅的风度接受这样的礼物是明智的。

---
== 2014-03 纯净版

The US$3-million Fundamental physics prize *is indeed* an interesting experiment, *as* Alexander Polyakov *said* when he *accepted* this year’s award in March. ② And it is far from the only one of its type. ③ As a News Feature article in Nature discusses, a string of lucrative awards for researchers *have joined* the Nobel Prizes in recent years. ④ Many, like the Fundamental Physics Prize, *are funded from* the telephone-number-sized bank accounts of Internet entrepreneurs. ⑤ These benefactors *have succeeded* in their chosen fields, they say, and they *want to use* their wealth *to draw attention to* those who *have succeeded in* science.

What’s not to like? Quite a lot, according to a handful of scientists *quoted* in the News Feature. ② You *cannot buy* class, as the old saying goes, and these upstart entrepreneurs *cannot buy* their prizes the prestige of the Nobels. ③ The new awards *are* an exercise in self-promotion *for* those behind them, say scientists. ④ They *could distort* the achievement-based system of peer-review-led research. ⑤ They *could cement* the status quo of peer-reviewed research. They *do not fund* peer-reviewed research. They *perpetuate* the myth of the lone genius.

The goals of the prize-givers *seem* [as scattered as the criticism]. Some *want to shock*, others *to draw* people *into* science, or *to better reward* those who *have made* their careers in research.

*As* Nature *has pointed out* before, there *are* some legitimate concerns about {how science prizes -- both new and old -- *are distributed*}. ② The Breakthrough Prize in Life Sciences, *launched* this year, *takes* an unrepresentative view of what the life sciences *include*. ③ But `主` the Nobel Foundation’s limit of three recipients per prize, each of whom *must still be* living, `谓` *has long been outgrown* by the collaborative nature of modern research -- as *will be demonstrated by* the inevitable row *over* {who *is ignored* [when it *comes to acknowledging* the discovery of the Higgs boson]}. ④ The Nobels *were*, of course, themselves *set up by* a very rich individual who *had decided* what he *wanted to do* with his own money. ⑤ Time, rather than intention, *has given* them legitimacy.

As much as some scientists *may complain about* the new awards, two things *seem* clear. ② First, most researchers *would accept* such a prize if they *were offered* one. ③ Second, it is surely a good thing {that the money and attention *come to* science *rather than* go elsewhere}, It is fair {*to criticize and question* the mechanism} -- that is the culture of research, after all -- but it is the prize-givers’ money (*to do with* as they please). ④ It is wise {*to take* such gifts with gratitude and grace}.

---

== 2014-04.

主 “The Heart of the Matter 事态;情况;局面,” the just-released 刚刚发布的 report by the American Academy of Arts and Sciences (AAAS), 谓 *deserves*(`=it is right that they should have it`) praise 称赞；赞扬 *for* *affirming*(v.)(`=to state firmly or publicly that sth is true`) the importance of the humanities 人文学科 and social sciences *to* the prosperity(`=the state of being successful`) and security(`=the state of feeling happy and safe from danger or worry`) of liberal democracy in America.

Regrettably(`=you are sorry about and wish had not happened`)可惜的；令人遗憾的, however, the report’s failure(n.)未成,失败 *to address*(`=try to understand it or deal with it`) the true nature of the crisis （*facing* 面对 liberal education 通识教育） （*may cause* more harm than good）.
====
- *(the) humanities* : [ pl. ] the subjects of study that are *concerned with the way people think and behave*, for example literature, language, history and philosophy 人文学科
- prosperity =>  pro-前 + -sper-希望 + -ity名词词尾
- liberal education : *concerned with increasing sb's general knowledge and experience* rather than particular skills 人文（教育）的
====

美国艺术与科学院刚发布的报告《问题的核心》，因肯定了人文和社会科学对美国自由民主的繁荣和安全的重要性，而值得赞扬。然而，遗憾的是，该报告没有论及通才教育所面临危机的真正本质，这可能造成弊大于利的结果。


In 2010, leading(`=most important or most successful`) congressional 美国国会的 Democrats 民主党人 and Republicans 拥护共和政体者 *sent letters to* the AAAS *asking* that it *identify* 确认;指认;验明 actions (that *could be taken by* “federal, state and local governments, universities, foundations 基金(会), educators, individual benefactors 捐助者；赞助人 and others” to “*maintain* national excellence(`=being extremely good`) in humanities 人文学科 and social scientific scholarship 学问;学术研究 and education.”)

In response, the American Academy *formed* 组建;建立 the Commission 委员会;调查团 on the Humanities 人文学科 and Social Sciences. [Among the commission’s 51 members] are top-tier (组织或系统的)层，级-university 一流大学 presidents(`=the person in charge of some organizations`), scholars, lawyers, judges, and business executives, as well as (除...之外)也,又 prominent(`=important or well known`) figures from diplomacy 外交, filmmaking, music and journalism 新闻业.
====
- tier: A tier is *a level in an organization or system*.
====


2010 年，首要的国会民主党人和共和党人，致函美国艺术与科学院，要求其确定可由“联邦、州和地方政府、大学、基金会、教育工作者、个人捐助者和其他人”采取的措施，以“保持国家在人文和社会科学学术和教育方面的优势”。
作为回应，美国艺术与科学院，成立了人文和社会科学委员会。该委员会51 名成员中，有顶级大学的校长、学者、律师、法官和公司执行总裁，也有来自外交、电影、音乐和新闻界的杰出人物。

The goals （*identified* in the report） *are* generally admirable(`=deserves to be praised and admired`). Because representative 由代表组成的;代议制的 government *presupposes*  预先假定；以…为前提；以…为先决条件 an informed 了解情况的;见多识广的 citizenry 全体国民;全体州居民;全体市民, the report ① *supports* full literacy(`=the ability to read and write`); *stresses*(`=to emphasize`) the study of history and government, particularly American history and American government; and ② *encourages* the use of new digital technologies.

*To encourage* innovation 创新;改革 and competition, the report *calls for* ① increased investment in research, ② the crafting 精心制作 of coherent 一致的;连贯的 curricula 课程（curriculum的复数形式） that *improve* students’ ability *to solve problems* and *communicate(`=to exchange ideas with sb`) effectively* in the 21st century, ③ increased funding 资助;为…提供资金 for teachers and ④ the encouragement of scholars *to bring* their learning 学习；学问 *to bear 承载；支撑 on*  用…处理；用…应对 the great challenges of the day.

The report also *advocates* 拥护；提倡；主张 greater study of foreign languages, international affairs 事务 and the expansion 扩张;扩充;扩大;发展 of study abroad programs.

====
- *bring sth to bear (on sb/sth)* :  ( formal ) to use energy, pressure, influence, etc. to try to achieve sth or make sb do sth 把精力用于；对…施加压力（或影响等） +
-> We must *bring all our energies to bear upon the task*. 我们必须全力以赴不辱使命。
====


这份报告中确立的目标，大体上是值得称赞的。因为代议制政府的前提是，公民知情，该报告支持全面的文化素养；强调学习历史和政治，特别是美国历史和美国政治；以及鼓励使用新的数字技术。

为了鼓励创新和竞争，报告呼吁增加研究投资，对紧密结合的课程要精益求精（它们会提高学生在21 世纪，有效地解决问题和交流沟通的能力），增加对教师的资助，和鼓励学者转化所学知识，以面对当今的巨大挑战。报告还主张加强对外语、国际事务的学习，和扩展留学计划。

Unfortunately, despite 2½ years in the making, “The Heart of the Matter” never *gets to* the heart of the matter: the illiberal(`=not allowing much freedom of opinion or action`) nature of liberal 开明的；开通的；（个人）自由主义的 education at our leading colleges and universities.

The commission 委员会 *ignores*(`=to pay no attention to sth`) that [for several decades] America's colleges and universities *have produced* graduates 毕业生 who ① *don’t know* the content and character(`=particular quality or feature`) of liberal education 通识教育 and ② *are thus deprived* 剥夺;使丧失;使不能享有 of its benefits.

Sadly, the spirit of inquiry 探究；调查；质询 （once [at home on campus (大专院校的)校园]） *has been replaced by* the use of the humanities and social sciences *as* vehicles（赖以表达思想、感情或达到目的的）手段，工具 for *publicizing*(`=to make sth known to the public`) “progressive,” or left-liberal 左派自由主义 propaganda(n.)(政治组织的）宣传.

不幸的是，尽管撰写报告用了两年半的时间，《问题的核心》却从未触及到问题的核心：我们一流院校的通才教育本质上是狭隘的。委员会忽视了几十年来美国各院校输送的毕业生不明白通才教育的内容和特点，因而丧失了它的益处。令人痛心的是，国内校园内曾有的探索精神，已经被利用人文和社会科学作为宣扬“进步的”或左翼民主的宣传工具所代替。

Today, professors ① *routinely 例行地;常规地;通常地 treat* the progressive 进步的,先进的 interpretation of history and progressive public policy *as* the proper(`=correct or most suitable`) subject(`=an area of knowledge`) of study ② while *portraying*(`=to describe sb/sth in a piece of writing`)) conservative 保守的;因循守旧的 or classical liberal ideas 自由理念 —— such as free markets and self-reliance 自主;自立;自力更生—— *as* falling outside 超出，不属于 the boundaries of routine 惯例;常规;例行公事, and sometimes legitimate 合情合理的;合法的, intellectual investigation.
====
- portray => 来自古法语portraire,描绘，描画，来自 *por-,向前，traire,拉* ，来自拉丁语trahere,拉，词源同draw,drawing,tract.字面意思即向前拉，延展，引申词义描绘，描画等。拼写可能受tray影响俗化。
====

The AAAS *displays* great enthusiasm *for* liberal education. Yet its report *may well set back* 使推迟;使延误;耽误 reform [by *obscuring*(`=to make it difficult to understand`) the depth and breadth(`=quality of consisting of or involving many different things`) of the challenge that Congress 国会 *asked* it *to illuminate*(`=to make sth clearer or easier to understand`)].
====
- obscure : 来自ob-,在上，表强调，-scurus,遮盖的，来自PIE*skeu,遮盖，隐藏，词源同sky,house,hide.引申词义使费解，模糊。

- breadth : n. The breadth of something is *its quality of consisting由…组成;由…构成 of or involving many different things*. （知识、兴趣等的）广泛, 广度 +
-> Older people *have a tremendous breadth of experience*... 年长者阅历相当丰富。
====

如今，教授们通常将进步的历史观和公共政策，视为正统的学习科目，而将保守的或古典自由主义的观点——例如：自由市场和自力更生——描述为逾越了常规、合理事物和理性调研的界限。 +
(如今，教授们习惯地把对历史渐进的解释和渐进的公共政策当作是恰当的研究主题，同时把保守或古典自由思想—比如自由市场和自力更生—描述为日常惯例范围之外的，但有时是合法的思想调查。)

美国艺术和科学研究院, 展示出了对自由教育极大的热情。然而，由于美国艺术和科学研究院的报表模糊了国会要求阐明的自由教育挑战的深度和广度，所以它阻碍了改革。


---

== 2014-04 纯净版


“The Heart of the Matter,” `主` the just-released report *by* the American Academy of Arts and Sciences (AAAS), `谓` *deserves* praise for *affirming* the importance of the humanities and social sciences *to* the prosperity and security of liberal democracy in America. ② Regrettably, however, `主` the report's *failure to address* the true nature of the crisis *facing* liberal education `谓` *may cause* more harm than good.

In 2010, leading congressional Democrats and Republicans *sent letters to* the AAAS *asking* that {it *identify*(v.) actions that *could be taken by* "federal, state and local governments, universities, foundations, educators, individual benefactors and others" *to "maintain* national excellence in humanities and social scientific scholarship and education."} ② In response, the American Academy *formed* the Commission on the Humanities and Social Sciences. ③ Among the commission's 51 members *are* top-tier-university presidents, scholars, lawyers, judges, and business executives, *as well as* prominent figures from diplomacy, filmmaking, music and journalism.

`主` The goals *identified* in the report `系` *are* generally admirable. ② Because representative government *presupposes* an informed citizenry, the report *supports* full literacy; *stresses* the study of history and government, particularly American history and American government; and *encourages* the use of new digital technologies. ③ *To encourage* innovation and competition, the report *calls for* (1)increased investment in research, (2)the crafting of coherent curricula that *improve* students' ability *to solve* problems and *communicate effectively* in the 21st century, (3)increased funding for teachers and (4)the encouragement of scholars *to bring* their learning *to bear on* the great challenges of the day. ④ The report also *advocates* greater study of foreign languages, international affairs and the expansion of study abroad programs.

Unfortunately, despite 2½ years in the making, "The Heart of the Matter" *never gets to* the heart of the matter: the illiberal nature of liberal education at our leading colleges and universities. ② The commission *ignores* that {[for several decades] America's colleges and universities *have produced* graduates who *don't know* the content and character of liberal education and *are thus deprived of* its benefits}. ③ Sadly, `主` the spirit of inquiry (once at home on campus) `谓` *has been replaced by* the use of the humanities and social sciences *as* vehicles for *publicizing* "progressive," or left-liberal propaganda.

Today, professors *routinely treat* the progressive interpretation of history and progressive public policy *as* the proper subject of study while *portraying* conservative or classical liberal ideas -- such as free markets or self-reliance -- *as* falling outside the boundaries of routine, and sometimes legitimate, intellectual investigation.

The AAAS *displays* great enthusiasm *for* liberal education. Yet its report *may well set back* reform [by *obscuring* the depth and breadth of the challenge that Congress *asked* it *to illuminate*].








