= 0551
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 551: Scheduling a Medical Appointment.
This is English as a Second Language Podcast episode 551. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
If you like this podcast and want to support it, consider becoming an ESL Podcast member. With your membership you get an 8- to 10-page Learning Guide for each of our current episodes that will help you improve your English even faster. Or if you don’t want to become a member and still want to support us, go to our website to make a donation at eslpod.com.
This episode is about how to make an appointment with your doctor or some medical professional by calling them on the phone. It’s going to give a lot of vocabulary related to hospitals and doctors and medical appointments. Let’s get started.
[start of dialogue]
I needed to make an appointment with a doctor so I called my health plan’s phone number for new patients. Before I could schedule my appointment, I had to listen to several recorded messages to be routed to the right medical office. The recording said to stay on the line for assistance.
Clerk: Hello, Western Medical Group.
Damien: Hello, I’d like to make an appointment with Dr. Gupta.
Clerk: Are you a new patient or a returning patient?
Damien: I’m a new patient.
Clerk: Who referred you to Dr. Gupta?
Damien: No one. One of the health benefits of my plan is that I can self-refer to some specialists.
Clerk: What is the name of your plan and your medical record number?
Damien: It’s Waiser and my medical record number is 23456789.
Clerk: It looks like Dr. Gupta is booked up for the next three weeks. She has an opening on March 2nd, at 4:30 p.m.
Damien: I was hoping to get an early morning appointment.
Clerk: The next morning appointment won’t be until March 18th, at 11:00. You’ll need to check in at 10:45 to fill out paperwork. Should I put you down for that?
Damien: Is it possible to get an even earlier appointment?
Clerk: Dr. Gupta doesn’t begin seeing patients until 10:30.
Damien: 10:30? Isn’t that pretty late?
Clerk: Dr. Gupta likes to play golf in the mornings.
Damien: Why do you think I want an early morning appointment? Doesn’t she know that some of her patients prefer late-morning golf?
[end of dialogue]
Our story begins with Damien saying, “I needed to make an appointment with a doctor so I called my health plan’s phone number for new patients.” An “appointment” is a scheduled meeting, a specific day and time when you are going to do something. Damien called his health plan’s phone number for new patients. A “health plan” is an insurance plan – a medical insurance plan that helps pay for your medical expenses if you are sick. “Patients” are people who receive medical treatment or medical advice from a doctor or a hospital. If you’re a patient, that means that some doctor is looking after you – is taking care of you. Damien needed a medical appointment so he called his health plan – his insurance company’s number for new patients. “Before I could schedule an appointment,” he says, “I had to listen to several recorded messages to be routed to the right medical office.” “To be routed” (routed) means to be sent to the right person or in the right direction. In this case, if you’re calling a large company you want to talk to the correct department. “The recording said to stay on the line for assistance.” “To stay on the line” means not to hang up the phone, to wait on the phone until someone answers; we also say “to hold.” If you call a company, the person answering the phone, if they’re busy, may say “please hold,” meaning I’m going to put the phone down, but don’t hang up – don’t go away.
Finally the clerk answers the phone by saying, “Hello, Western Medical Group.” A “medical group” is a group of doctors who work together in the same building, usually not a hospital. It could be a medical office building, or it could be a “clinic,” which is sort of like a small hospital. Damien says, “Hello, I’d like to make an appointment with Dr. Gupta.” The clerk says, “Are you a new patient or a returning patient (is this is the first time you’ve seen or are going to see Dr. Gupta, or have you seen Dr. Gupta before)?” “Returning,” here, means you’ve already used the services of this doctor – you’ve already seen this doctor before.
Damien says, “I’m a new patient,” and the clerk says, “Who referred you to Dr. Gupta?” “To refer” (refer) means to recommend that someone see a particular person or a particular company; in this case, a particular or specific doctor. Someone says, “Oh, my neck really hurts,” and somebody else says, “Oh, you should go see Dr. McQuillan, he is a very good neck doctor.” I’m not sure if there are neck doctors; it’s just an example! So Damien says, “No one (meaning no one referred me to Dr. Gupta). One of the health benefits of my plan is that I can self-refer to some specialists.” A “benefit” is a good thing; a “health benefit” is something that you get from your health insurance; it’s something that is included in your insurance. Damien says, “One of the health benefits of my plan (meaning my insurance) is that I can self-refer to some specialists.” “To self-refer” means to be able to request to see certain doctors without having another doctor refer you, or another doctor approve that you can go see this particular doctor. Usually, this has to do with doctors who are specialists. A “specialist” is an expert in a specific area of medicine. So if you are a hand surgeon – you work on people’s hands – you are a specialist. In many insurance plans in the United States you can’t just go see any doctor you want to; first you have to go see what’s called your “general practitioner,” or the doctor who’s a general doctor, and if you have a specific problem that doctor will refer you to a specialist. There are some health plans where you can self-refer to certain specialists.
The clerk says, “What is the name of your plan and your medical record number?” Your “medical record number,” sometimes called your “patient number,” is a number that the insurance plan gives you so that they can identify you. It’s a number that only you have. I don’t know what my medical record number is; it’s about eight or nine digits long – eight or nine numbers long. Damien says that the name of his plan (his health plan; his insurance) is Waiser and his medical record number is 23456789. Boy, that’s amazing how his medical record number are consecutive numbers between two and nine!
Anyway, the clerk says, “It looks like Dr. Gupta is booked up for the next three weeks.” “To be booked up” means to have a very busy, full schedule; you don’t have any time to see anyone for any appointments. The word “book” has a number of different meanings however; take a look at our Learning Guide for some additional explanations. The clerk says that Dr. Gupta has an opening on March 2nd, at 4:30 p.m. When we say “you have an opening,” we mean you have a period of time when you are available, when you can see someone. In this case, it’s a time that Dr. Gupta can see a new patient, such as Damien.
Damien says, “I was hoping to get an early morning appointment.” The clerk says, “The next morning appointment won’t be until March 18th, at 11:00. You’ll need to check in at 10:45 to fill out paperwork.” “To check in” means to come to the office and talk to someone and let them know that you are here. So basically it means you have to show up at 10:45; you have to be in the office at 10:45. Why so early if the appointment is not until 11:00? Because, the clerk says, Damien has to fill out, or complete, some paperwork. “Paperwork” are usually forms that you have to fill out, things that you need to write down – information – on a sheet of paper. We often use this term to indicate not very interesting but necessary information. The clerk asks, “Should I put you down for that?” “To put (someone) down,” in this case, means to schedule someone for something by writing his or her name on a calendar or an appointment book. To sign or to register someone for something means to put someone down. If the clerks says, “I’ll put you down for 11:00,” she means I will schedule you for 11:00; I will write your name down for 11:00.
Damien says, “Is it possible to get an even earlier appointment (earlier in the day)?” The clerk says, “Dr. Gupta doesn’t begin seeing patients until 10:30 (10:30 in the morning).” Damien says, “10:30? Isn’t that pretty late (isn’t that very late)?” The clerk says, “Dr. Gupta likes to play golf in the mornings.” Damien says, “Why do you think I want an early morning appointment? Doesn’t she know that some of her patients prefer late-morning golf?” In other words, the joke here is that Dr. Gupta likes to play golf in the morning so she cannot be there before 10:30; Damien is saying he likes to play golf in the late morning, say 10:30-11:00, and that’s why he wants an early appointment. The expression “to put down” also has a very different meaning; take a look at the Learning Guide for that other meaning. There’s a standard joke that doctors have a lot of free time – a lot of extra time that they can use to do things like play golf, which is, of course, a little bit expensive. This is just a joke however; most doctors, I don’t think, have very much time – at least, the majority of them.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
I needed to make an appointment with a doctor so I called my health plan’s phone number for new patients. Before I could schedule my appointment, I had to listen to several recorded messages to be routed to the right medical office. The recording said to stay on the line for assistance.
Clerk: Hello, Western Medical Group.
Damien: Hello, I’d like to make an appointment with Dr. Gupta.
Clerk: Are you a new patient or a returning patient?
Damien: I’m a new patient.
Clerk: Who referred you to Dr. Gupta?
Damien: No one. One of the health benefits of my plan is that I can self-refer to some specialists.
Clerk: What is the name of your plan and your medical record number?
Damien: It’s Waiser and my medical record number is 23456789.
Clerk: It looks like Dr. Gupta is booked up for the next three weeks. She has an opening on March 2nd, at 4:30 p.m.
Damien: I was hoping to get an early morning appointment.
Clerk: The next morning appointment won’t be until March 18th, at 11:00. You’ll need to check in at 10:45 to fill out paperwork. Should I put you down for that?
Damien: Is it possible to get an even earlier appointment?
Clerk: Dr. Gupta doesn’t begin seeing patients until 10:30.
Damien: 10:30? Isn’t that pretty late?
Clerk: Dr. Gupta likes to play golf in the mornings.
Damien: Why do you think I want an early morning appointment? Doesn’t she know that some of her patients prefer late-morning golf?
[end of dialogue]
Today’s story was written by our script specialist, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
appointment – a scheduled meeting; a specific date and time when one will do something
* Each October, Clarke makes an appointment to get his teeth cleaned at the dentist’s office.
health plan – medical insurance plan or coverage; the policy that helps a person pay for his or her medical expenses
* Stefan has a great health plan where he has to pay only $5 each time he sees his doctor.
patient – a person who receives medical advice and/or treatment from a doctor, clinic, or hospital
* The patient in room 2B is asking to see you, Doctor.
to route – to send a call to the right person or in the right direction, and especially to connect a caller with the right office when he or she is calling a large organization or business
* The receptionist is responsible for routing calls to the company’s many departments.
to stay on the line – to hold; to not hang up the phone; to wait on the phone until someone is available
* Whenever I call the bank, I have to stay on the line for at least ten minutes before I can speak with a real person. It’s very frustrating.
medical group – a clinic; a group of doctors who work together in the same building
* Could you please recommend a good medical group in the Dallas area? Our family needs a medical group with a good general practitioner and a pediatrician.
returning – a repeat client; referring to a client or patient who has used the services of a particular business or doctor before and is requesting another meeting or appointment
* More than 90% of our new patients become returning patients, so we know we’re providing good service that makes them want to come back.
to refer – to recommend that someone see a particular doctor, work with a particular company, or shop at a particular store
* Our friends referred us to you. They said you helped them buy their first home last year, and they really enjoyed working with you.
health benefit – one of the things that a medical insurance plan pays for while the individual pays little or nothing
* This insurance coverage isn’t very good. The health benefits exclude physical therapy, prenatal care, and all prescriptions.
to self-refer – to be able to request to see a certain doctor without first needing a referral (recommendation and approval) from one’s doctor or approval from one’s insurance plan
* Pyotr needs to see an ophthalmologist, but because his insurance plan doesn’t allow him to self-refer, he has to see his regular doctor first and request a referral.
specialist – a doctor who is an expert in a specific area of medicine and works only in that area
* In her third year of medical school, Yasushi decided she’s like to become a cancer specialist.
medical record number – an identifying number in a medical insurance plan or at a doctor’s office, used to find one’s papers quickly and easily
* If you don’t have your medical record number, we’ll have to look up your account information with your last name and telephone number.
booked up – with a busy, full schedule; without any unscheduled time on one’s calendar
* This restaurant is always booked up. If you want to have dinner there on Valentine’s Day, you’ll need to request a reservation months in advance.
opening – a period of time when one is available because nothing else has been scheduled yet during that time
* Dr. Te has openings on Thursday at 10:15 and 2:30. Which would you prefer?
to check in – to come to an office or conference and officially speak with someone to let people know that one has arrived and is ready for the appointment or meeting
* When you arrive at our office building, please check in with the receptionist and he’ll lead you to our office.
paperwork – uninteresting work where one must fill out many forms and documents or write reports
* I hadn’t realized how much paperwork was involved in adopting a child from another country!
Comprehension Questions
1. Why did Damien choose to see Dr. Gupta?
a) Because Dr. Gupta has always been his doctor.
b) Because Dr. Gupta was recommended by his other doctor.
c) Because visits with Dr. Gupta are allowed under his health plan.
2. What time should Damien arrive at the office on March 18th?
a) 10:30.
b) 10:45.
c) 11:00.
Answers at bottom.
What Else Does It Mean?
to be booked up
The phrase “to be booked up,” in this podcast, means to have a busy, full schedule without any unscheduled time on one’s calendar for additional appointments or meetings: “Tax accountants are really booked up in March and April of each year.” Similarly, the phrase “booked solid” means that all tickets have been sold or all openings have been filled so that nothing else is available: “Our hotel is booked solid through next March.” The phrase “to book (something)” means to make a reservation or to make arrangements for someone to do something: “Could you please book me a flight to New York for next Wednesday morning?” Finally, the phrase “to book (someone) for/on (something)” means for the police to officially record someone’s illegal activity in their records: “Did you hear that Brian was booked for stealing clothes from the department store?”
to put (one) down
In this podcast, the phrase “to put (someone) down” means to schedule someone for something by writing his or her name on a calendar or in an appointment book, or to sign someone up for something: “I’ll put you down for an appointment on Tuesday at 3:00.” Or, “Someone put me down as a volunteer for the event, but I’m not available that day.” The phrase “to put (someone) down” also means to say something that makes another person seem stupid, foolish, or less important: “Ingrid is always putting her children down in front of other people, criticizing them for not getting better grades.” A “put-down” is a bad thing that someone says to another person: “I’m tired of hearing your put-downs. Can’t you be supportive for once?”
Culture Note
In the United States, a new patient has to “fill out” (complete) a lot of paperwork before he or she can see the doctor. One of these forms is an “intake form” (a form used to gather information on a new account, patient, or client). The new patient has to write down his or her contact information, medical history, “medical concerns” (things one wants to speak about with the doctor), and “emergency contact information” (who should be called if there is a medical emergency). The new patient also has to present “proof of insurance” (a small card showing that one has health insurance) and sign a document saying that he or she will “cover the cost of” (pay for) any medical expenses that are not covered by insurance.
A new patient may also be asked to fill out a “form” (a piece of paper requesting information) that is used to request a copy of his or her “medical records” (written documents about the patient’s medical history and treatments) from the previous doctor. Finally, a new patient has to sign the clinic’s privacy policy, “indicating” (showing; agreeing) that he or she understands how medical information may be shared with “third parties” (anyone other than the patient and doctor).
A returning patient usually doesn’t have to fill out paperwork. “Upon” (when; after) checking in, the returning patient might be asked if his or her contact information or insurance coverage has changed. If everything is still the same, he or she waits to “be called” (to have one’s name called when it is time for one to be seen by the nurse and doctor). Then, a nurse will normally measure the patient’s height, weight, blood pressure, “pulse” (the number of heartbeats per minute), and temperature, adding the information to the medical records.
Comprehension Answers
1 - c
2 - b