= 0557
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 557: Applying for a Passport.
This is English as a Second Language Podcast episode 557. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there today to support this podcast by becoming a member, which allows you to download an 8- to 10-page Learning Guide for all of our current episodes.
This episode is called “Applying for a Passport.” It’s a dialogue between Orlando and someone at the passport office. It’s going to be using a lot of vocabulary related to getting a passport, at least here in the United States. Let’s get started.
[start of dialogue]
Clerk: Yes, can I help you?
Orlando: I want to get a passport.
Clerk: Have you filled out the application?
Orlando: No, I haven’t.
Clerk: Come back when you’ve filled it out.
Orlando: Okay, I’ve completed the application.
Clerk: Let me see it. You need to fill in your Social Security number here and you need to provide evidence of your citizenship. Have you ever had a passport before?
Orlando: No, I haven’t.
Clerk: In that case, you’ll need to submit a copy of your birth certificate, or if you were born outside of the country, a copy of your Naturalization Certificate or a Consular Report of Birth Abroad.
Orlando: I don’t have those documents with me.
Clerk: Come back when you do.
Orlando: Okay, I’m back. I have a copy of my birth certificate.
Clerk: All right. Let me see some identification.
Orlando: Identification?
Clerk: Yes, I need to see a valid driver’s license, a government ID, or a military ID.
Orlando: I’ll be right back.
Clerk: Yes?
Orlando: Here’s my military ID.
Clerk: Where are you passport photos?
Orlando: Passport photos?
Clerk: Yes, you need two identical passport photos.
Orlando: I’ll be right back.
[end of dialogue]
Our dialogue begins with the clerk, the person who is working at the passport office, saying to Orlando, “Yes, can I help you?” “Can I help you?” or “May I help you?” mean the same thing. I should also point out that although you can get a passport by going to the U.S. government passport office, most people get their passports at the Post Office; that’s where you submit your application.
Orlando says, “I want to get a passport,” which you probably know is a small, official book that is given to you by your government that allows you to travel to other countries. The clerk says, “Have you filled out (have you completed) the application (the form that requests all the information about you)?” Orlando says, “No, I haven’t.” The clerk says, “Come back when you’ve filled it out (when you’ve completed it).”
So Orlando goes away, he comes back, and he says, “Okay, I’ve completed the application.” The clerk says, “Let me see it,” please allow me to look at it – the clerk isn’t actually that polite. She says, “You need to fill in (to write in) your Social Security number here.” The “Social Security number” is a number that pretty much everyone in the United States has, issued by the government – the government gives you this number. Usually you get the number when you are a young child, or even a baby. It identifies you. It is a number that is typically only given to people who have legal permission to be here in the United States. Social Security is also the name of a program that provides money for those who need money to live on, especially those who are old. It’s sort of like our national retirement system – except they don’t have very much money! The Social Security number, then, is one thing that you have to put on almost every official application that you fill out in the U.S.
The clerk tells Orlando he also needs evidence of his citizenship. “Evidence,” here, means the same as proof; evidence would be a written document that supports what you are saying. In this case, Orlando is saying “I am a U.S. citizen,” and the clerk is telling him he has to prove that – he has to show that. “Citizenship” means, of course, belonging to a particular country. Some people have dual citizenship; they are citizens of more than one country – two countries if it’s dual citizenship. I suppose you could have citizenship in more than two countries, it would be a little unusual
Orlando is asked if he has ever had a passport before. Passports in the United States are typically issued, or given to you, and they are good for 10 years; every 10 years you have to get a new passport. Orlando says, “No, I haven’t (I haven’t had a passport before).” The clerk says, “In that case (in this situation), you’ll need to submit a copy of your birth certificate.” “To submit” (submit) means to officially give or send something to someone or to some organization, especially if that organization has to review or approve whatever it is that you are sending in. So for example, you could submit a job application. You could give the company an application, they would look at it and see if they want to hire you – to have you work for them. The word “submit” has a couple of different meanings in English; take a look at the Learning Guide for some more explanations.
Well, the clerk is asking Orlando for his “birth certificate.” This is an official piece of paper that shows your complete name, when and where you were born, who your parents are, and typically the name of the hospital, although that isn’t always on the birth certificate. Every state has its own birth certificate system; there is not a national birth certificate system in the U.S. If I wanted to get my birth certificate I would have to go back, or write – nowadays email – the Minnesota government office that takes care of birth certificates. Within a given state, mostly the birth certificates are arranged by county. A “county” is a smaller division within state. Minnesota, for example, has 87 counties – 87 different regions. In fact, it has more counties than any other state in the United States for some reason. I would have to go back to the county I was born in, Ramsey County, which is where St. Paul is, and ask for a copy of my birth certificate.
I actually did that when I was…I don’t know…12 years old maybe, and we discovered – I discovered that my parents had not officially put a name in for me on the birth certificate. They hadn’t decided what they were going to call me. Remember, I’m the youngest of 11 children, so they had sort of gone through all of the names that they wanted. Well, because they didn’t know my name by the time my mother left the hospital, the birth certificate simply said “Baby Boy McQuillan.” I had to then officially prove to the county that my legal name was Jeffrey – that’s my full name, and I had to provide them evidence that I have used this name all of my life. But for the first 12 years of my existence on this earth I was officially known as Baby Boy McQuillan, which is actually a good name since I was the youngest in the family, and we often call the youngest in the family the baby of the family – even if they’re 46 years old! I’m still the baby of the family.
Back to Orlando: Orlando has to get a birth certificate, or if he was born outside of the United States he needs a copy of either his Naturalization Certificate or something called a Consular Report of Birth Abroad. A “Naturalization Certificate” is an official piece of paper showing that you were once a citizen of another country, but then you became a U.S. citizen. So if you move here after 20 years of living in, say, Japan or France or South Africa – wherever, and you want to become a U.S. citizen you have to get what is called “naturalized.” You become a citizen, and that process is called “naturalization.” So, a “Naturalization Certificate” is a certificate proving that you officially became a U.S. citizen on this particular day; it’s not your birth certificate. If you have an American mother or father, or both, and you are born in another country you’re still an American citizen. However, because you will not have a birth certificate from a U.S. hospital you need to go to the local embassy or consulate and get a Consular Report of Birth Abroad. An “embassy” is the main headquarters of representatives from your government in another country. Usually the embassies are in the capital cities of the other countries; here in the United States, they would be in Washington, D.C. Many governments also have small offices called “consulates” that are in other cities in the United States or in a different country. So for example, here in Los Angeles there is a consulate for the government of Mexico, a consulate for China, a consulate for Spain. Dozens of other countries have consulates in big U.S. cities, especially cities that may have a lot of citizens from their country. The U.S. has consulates in other cities, in addition to embassies, in other countries. A “consular,” then, refers to the notion of a representative; “consul,” here, is more generally a representative of your government. Consular Report of Birth Aboad; “abroad” simply means in another country. So it’s sort of like a birth certificate but it comes from the U.S. State Department, from either an embassy or a consulate, that shows that you are, in fact, an American citizen.
Well, Orlando says he doesn’t have any of these things. He says, “I don’t have those documents (those official pieces of paper) with me.” A “document” can mean a couple of different things. Once again, take a look at the Learning Guide for some more explanations. So the clerk says to Orlando, “Come back when you do,” meaning come back here when you have one of these official documents. So he goes, and comes back again and gives his birth certificate to the clerk. The clerk then says, “Let me see some identification (let me see something that proves that you are who you are).” Usually that means either a valid driver’s license, a government ID, or a military ID. A “driver’s license” is issued, or given, by each state, that says you have permission to drive in that state, and in any other state, but you need at least one driver’s license from one state. A “valid” driver’s license just means a driver’s license that is current, that was issued recently. A “government ID” is identification that is given by the government, perhaps another government agency besides the state where you live. A “military ID (or identification)” is a card that says you are a member of the Army, the Navy, the Air Force, or the Marines, and that you work in that organization.
So Orlando has to leave again, he comes back, he says, “Here’s my military ID.” The clerk then asks, “Where are you passport photos?” In order to get a passport you have to have two pictures taken of yourself, and you need to bring them and give them with your application to the government representative in order to get a passport. Passport photos are very small, and are just of your head. Well of course, Orlando doesn’t have the passport photos. The clerk says, “Yes, you’ll need two identical (or the same) photographs.” Orlando says, “I’ll be right back,” and leaves again.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Clerk: Yes, can I help you?
Orlando: I want to get a passport.
Clerk: Have you filled out the application?
Orlando: No, I haven’t.
Clerk: Come back when you’ve filled it out.
Orlando: Okay, I’ve completed the application.
Clerk: Let me see it. You need to fill in your Social Security number here and you need to provide evidence of your citizenship. Have you ever had a passport before?
Orlando: No, I haven’t.
Clerk: In that case, you’ll need to submit a copy of your birth certificate, or if you were born outside of the country, a copy of your Naturalization Certificate or a Consular Report of Birth Abroad.
Orlando: I don’t have those documents with me.
Clerk: Come back when you do.
Orlando: Okay, I’m back. I have a copy of my birth certificate.
Clerk: All right. Let me see some identification.
Orlando: Identification?
Clerk: Yes, I need to see a valid driver’s license, a government ID, or a military ID.
Orlando: I’ll be right back.
Clerk: Yes?
Orlando: Here’s my military ID.
Clerk: Where are you passport photos?
Orlando: Passport photos?
Clerk: Yes, you need two identical passport photos.
Orlando: I’ll be right back.
[end of dialogue]
The script for this episode was written by an American citizen, who has a valid driver’s license, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
passport – a small official book, issued by a national government, that allows a person to travel to other countries and return to one’s own country
* Mojo likes to look at all of the stamps in his passport to remember the places where he has traveled.
application – a form that requests information, used when one wants to have or get something, or wants to join or participate in something
* How long does it take to fill out the application for a driver’s license?
social security number – a unique nine-digit number in the form of ###-##-####, given to U.S. citizens and people who have legal permission to live in the U.S.
* Please write your social security number on the top of each page in your tax return.
evidence – proof; a written document that supports what one has said or claimed
* After Terese got married, she carried around a copy of her marriage certificate as evidence that her last name had been changed.
citizenship – belonging legally to a particular country
* When an American gives birth to a child in another country, that child has dual citizenship, meaning that he or she is an American citizen and a citizen of the other country at the same time.
to submit – to officially give or send something to a person or organization, especially when that person or organization will review and/or approve it
* Please submit any comments or suggestions to the manager.
birth certificate – an official piece of paper that states one’s full name, when and where one was born, and the names of one’s parents.
* When Marguerite looked at her birth certificate, she was shocked to realize that she had been born before her parents were married.
naturalization certificate – an official piece of paper showing when one became a U.S. citizen
* Zola was very proud to become a U.S. citizen, so she hung her naturalization certificate in her living room where everyone could see it.
Consular Report of Birth Abroad – an official piece of paper stating that an individual was born outside of the United States and that one or both of his or her parents is a U.S. citizen
* Kati has a Consular Report of Birth Abroad, because she was born in Mongolia while her American parents were working at the U.S. Embassy there.
document – an official piece of paper that provides information about something
* When you travel, make sure you keep all your documents safe, including your passport, your itinerary, and a list of the vaccinations you’ve received.
identification / ID – documents that prove who someone is, listing the person’s full name and often a photograph and information about his or her age and physical appearance
* The bank requires at least two pieces of identification before it will cash anyone’s check.
valid driver’s license – a small card that shows one has permission to drive in a particular state
* It is illegal to drive without a valid driver’s license.
military – related to the armed forces, navy, army, air force, and marines and the people who work and serve in those organizations
* How many of this year’s high school graduates are choosing to go into military service?
passport photo – a small photograph of a person’s head, with a specific length and width, used for the photograph in one’s passport
* You can’t use this as a passport photo, because you weren’t looking directly at the camera.
identical – exactly the same, without any differences
* The sisters’ voices sound identical over the phone, so I never know which girl I’m speaking with.
Comprehension Questions
1. Where does Orlando need to write his social security number?
a) On his passport.
b) On his application.
c) On his birth certificate.
2. What is a passport photo?
a) A photo of a person holding a passport.
b) A photo of where a person has traveled with a passport.
c) A photo of the person who owns the passport.
Answers at bottom.
What Else Does It Mean?
to submit
The verb “to submit,” in this podcast, means to officially give or send something to a person or organization, especially when that person or organization will review and/or approve it: “We’re supposed to submit our essays to the professor by email by 5:00 p.m. on Thursday.” The verb “to submit” also means to accept the authority and power of another person or organization over oneself: “Do you believe that modern women should submit themselves to their husband as in the past, or should they be more independent now?” Or, “Lou doesn’t want to submit to the authorities in any way, so he refuses to pay taxes.” In a court of law, lawyers “submit evidence,” or present arguments, documents, videos, and tapes that help them argue their side of the case: “The lawyers submitted a lot of evidence to show that the man was guilty.”
document
In this podcast, the word “document” means an official piece of paper that provides information about something: “Please send us your university diploma or another document that proves you studied there.” A “document” can also be an electronic computer file: “How can I open a new Word document?” Or, “Try to save the changes to your document at least every 10 minutes.” As a verb, “to document” means to write down information about something so that it isn’t forgotten: “All the current employees were asked to document their work processes so that it would be easier for new employees to learn how to do their job.” Something that is “documented” has been written down with many details: “The development of nuclear power is well documented.”
Culture Note
The U.S. “Department of State” (the part of the U.S. government involved in international relations) “issues” (creates and shares) travel “advisories” (information and recommendations) for U.S. citizens who are considering traveling to other countries. It issues two types of travel advisories: Travel Alerts and Travel Warnings.
A “Travel Alert” is used to share information about short-term conditions that may “pose” (present) “risks” (things that may cause hurt, damage, or death if they happen) to U.S. citizens in the area. Travel Alerts might describe important conferences or sporting events, “demonstrations” (protests), elections, terrorist activity, and “natural disasters” (earthquakes, floods, tsunamis, etc.). Right now, many of the Travel Alerts are about “swine flu” (H1N1) and the “quarantine measures” (efforts to separate sick people from healthy people) that some countries are “engaged” (involved) in.
A “Travel Warning” is used to share information about long-term conditions that make it dangerous for Americans to be in a country. Travel Warnings are used when the “embassy” or “consulate” (official government presence in another country) is closed or has limited staff. When this happens, U.S. citizens in that country will not receive very much assistance from the government if something bad happens to them.
The Department of State also offers country-specific information to help U.S. citizens learn more about the country they will be traveling to. This information includes the location of the U.S. sembassy or consulate, “visa requirements” (documents needed to enter a country), local health, and “vaccination” (injections to prevent diseases) recommendations, as well as information about local crime.
Comprehension Answers
1 - b
2 - c