= 0592
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 592: Dealing With Website Hackers.
This is English as a Second Language Podcast episode 592. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download a Learning Guide for this episode that will help your improve your English even faster.
This episode is called “Dealing With Website Hackers,” people who go into a website to damage it or hurt it. Let’s get started.
[start of dialogue]
Valerie: You’ll never guess what happened over the weekend.
Bill: What?
Valerie: Our website was attacked by hackers, and nobody could access it.
Bill: You’re kidding! What did they do?
Valerie: They got access to our server and embedded some malicious code that caused the site to be redirected to their own website.
Bill: But I thought our site had really good security. Didn’t we hire a programmer last year to encrypt the database and patch any vulnerabilities?
Valerie: That’s what we should have done. So now, we’re paying the price.
Bill: The site seems to be back up, though.
Valerie: Yeah, we brought in a specialist on Friday and she’s been working on it 24/7. Let’s hope she puts in the security measures we should have had all along, and this will never happen again.
Bill: Right, at least until some creative hacker comes up with a new way to wreak havoc.
[end of dialogue]
Valerie begins the dialogue by saying, “You’ll never guess what happened over the weekend.” That phrase, “you’ll never guess,” means that you have some surprising news, some unusual news that the other person could not even imagine. Bill says, “What?” Valerie replies, “Our website was attacked by hackers, and nobody could access it.” A “hacker” (hacker) is a person who tries to go into a website to either steal secret information or to somehow destroy or make the website not work properly. “To access” means to be able to see or get something; it’s often used when we are talking about something that is private or secret. Do not let anyone get access to your bank account; they could steal your money!
Bill says, “You’re kidding! What did they do?” What did the hackers do? She says, “They got access to our server and embedded some malicious code.” The “server” (server) here means a large computer that is on the Internet, or it is a computer that is linked up to many other computers. It often has certain computer programs or software on it. All websites on the Internet are on a server; it allows you to get to the website – to access that computer where the information for the website is stored. “Server” has a couple of different meanings however; take a look at the Learning Guide for some additional explanations.
The hackers got access to Valerie’s server and embedded some malicious code. “To embed” (embed) means to put something inside of something else, to make it a part of something else. So here, the hackers have taken the good code – the good program on the website, and they have added – they have embedded some malicious code. “Malicious” means mean, cruel, something you do because you want to hurt someone. “Code” (code) is simply the computer programming language that you have to understand and know in order to use. Basically, they are instructions that tells the computer what to do or how to do something. So here, Valerie’s server was embedded with some malicious, bad code that caused the site to be redirected to their own – the hackers’ – website. “To redirect” means to send someone in a different direction. They were going to your website, you redirect them to another website so they automatically get transferred, if you will, to another website, and that’s what happened with the hackers.
Bill says, “But I thought our site had really good security.” “Security” here means protection from danger, safety. “Didn’t we hire a programmer last year to encrypt the database and patch any vulnerabilities?” A “programmer” is someone who works with computer program languages, who makes, for example, software and websites. Last year, they hired a programmer to encrypt (encrypt) the database. “To encrypt (something)” is to protect your information by using a special code or language that no one else can read or understand. In computer terms, things that are encrypted usually require that the other person has the special key – the special code that would allow them to read what you have produced. This is a case of the website having an encrypted database. A “database” is a collection of information stored on a computer in some organized way so that it is easy to find something. The programmer was also supposed to patch any vulnerabilities. “To patch” (patch) means to fix something that is broken or isn’t working correctly, usually by focusing on one part of a larger thing – one area where the main problem is. This is a term used nowadays to talk about fixing problems with computer programs on the Internet, especially problems related to security. “Patch” however has other meanings in English, and those you can find in the Learning Guide. A “vulnerability” is a weakness, something that leaves you open to attack or danger. Websites have vulnerabilities; they have weak spots – weak points where someone can enter in illegally, without permission.
Valerie says, “That’s what we should have done,” meaning they didn’t hire the programmer. “Now,” she says, “we’re paying the price.” “To pay the price” here means to have something bad happen to you, we might say to suffer negative consequences for something that you didn’t do in the past. So if you come to Los Angeles and you rent a car, and you decide Los Angeles is a safe city, I’m not going to lock my car, I’m going to leave my car open. Well, you will probably get your car stolen and you will pay the price. You will suffer the negative consequences, primarily to your insurance or to your credit card.
Bill says, “The site seems to be back up, though.” “To be back up” when describing something on the Internet – a website – means that the website is working again after a long period, or a certain period when it was not working. That is to be back up. “Is the website back up?” The opposite is the website is down. When we say a website is “down,” we mean it’s not working; you can’t access it.
Valerie says, “Yeah, we brought in a specialist on Friday and she’s been working on it 24/7.” This expression “24/7” means, literally, 24 hours a day, 7 days a week; or in other words, all the time, without any stopping. Many large companies have technical support 24/7; you can call them at any time. You may not necessarily talk to someone who knows how to help you, but you can certainly call them! Valerie says, “Let’s hope this specialist puts in the security measures we should have had all along (meaning before, in the past), and this will never happen again.”
Bill says, “Right (I agree), at least until some creative hacker comes up with (or invents; creates) a new way to wreak (wreak) havoc (havoc).” “To wreak havoc” means to create a lot of problems, to create a disaster where things are totally destroyed, or they’re a big mess.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Valerie: You’ll never guess what happened over the weekend.
Bill: What?
Valerie: Our website was attacked by hackers, and nobody could access it.
Bill: You’re kidding! What did they do?
Valerie: They got access to our server and embedded some malicious code that caused the site to be redirected to their own website.
Bill: But I thought our site had really good security. Didn’t we hire a programmer last year to encrypt the database and patch any vulnerabilities?
Valerie: That’s what we should have done. So now, we’re paying the price.
Bill: The site seems to be back up, though.
Valerie: Yeah, we brought in a specialist on Friday and she’s been working on it 24/7. Let’s hope she puts in the security measures we should have had all along, and this will never happen again.
Bill: Right, at least until some creative hacker comes up with a new way to wreak havoc.
[end of dialogue]
The script for this episode was written by someone who’s never malicious, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
hacker – a person who tries to access and/or change the information on another person’s computer or website, usually to get secret information or to destroy a competitor’s computer system
* How long would it take a hacker to break into the government’s computer network and access criminals’ records?
to access – to be able to see or obtain something; to be able to get something
* Nobody can access the personnel files unless they have the keys to the filing cabinet.
server – a large computer that controls other computers on a network, sharing information between and among the computers, and often hosting many computer programs
* Is that computer program stored on your computer, or on the server?
to embed – to put something inside something else; to lock something in place as part of something else
* Do you like the new graphics we’ve embedded on the website?
malicious – mean, cruel, and hurtful; with the intention of doing evil or hurting another person
* The other kids made such malicious comments that she came home from school in tears.
code – computer programming language that cannot be read by people who aren’t experts in that language; instructions that tell a program or computer what to do or how to do something
* They had to review more than a million lines of code to find the error in the program.
to redirect – to send someone or something in a different direction
* When we walked into the room, we all looked at the paintings on the walls, but the museum’s tour guide redirected our attention to the beautiful ceilings and floors.
security – safety; protection from danger or interference
* The office is increasing security by making all employees show identification before entering the building.
to encrypt – to protect information by writing it in a special language so that it cannot be read by other people while it is sent
* Never send your social security number via email unless you’re sure the message is encrypted.
database – a collection of information stored on a computer in an organized way so that it is easy to sort and to find pieces of data
* They created a customer database that includes each customer’s name, contact information, and past purchase information.
to patch – to fix something that is broken or isn’t working properly, usually focusing on one part of a larger thing
* Harold patched the hole in the roof to keep the rainwater out of his bedroom.
vulnerability – a weakness; something that leaves one open to attack or danger
* The army’s greatest vulnerability is on the northern side, where the mountains make it more difficult to protect the soldiers.
to pay the price – to suffer negative consequences for something one has (not) done in the past
* Now in her 50s, Greta’s health is failing and she is paying the price for all the smoking and drinking she did in her teens and 20s.
to be back up – for a program or website to be working again after a period when it was not working
* The technicians had to shut down all the computers to install an upgrade, but everything should be back up again within an hour.
24/7 – 24 hours a day, 7 days a week; all the time; without stopping
* Our telephone support center is open 24/7, so if you have questions you can call anytime.
security measure – something that one does to try to keep something safe and secure
* As a security measure, the embassy requires all its employees to be indoors after 9:00 p.m.
to wreak havoc – to create many problems; to create a disaster
* The weather is wreaking havoc on Florida’s tomato crops.
Comprehension Questions
1. Which of these would be the best way to improve website security?
a) Embed malicious code.
b) To access the server.
c) Patch any vulnerabilities.
2. What does Valerie mean when she says the specialist has been working 24/7?
a) She has been working without stopping.
b) She has been working 24 hours and seven minutes.
c) She has been working 24 hours at $7 per hour.
Answers at bottom.
What Else Does It Mean?
server
The word “server,” in this podcast, means a large computer that controls other computers on a network, sharing information between and among the computers, and often hosting many computer programs: “If your website traffic continues to grow like this, you’ll need to pay for a bigger, faster server.” A “server” is also a waiter, or a person who brings food to customers in a restaurant: “Hello, my name is Sasha and I’ll be your server this evening. Would you like to hear about our specials?” In sports, a “server” is the person who hits the ball to begin a game of tennis or volleyball: “Christine is a really strong server, so I hope she’s on our volleyball team again this year.”
patch
In this podcast, the verb “to patch” means to fix something that is broken or isn’t working properly, usually focusing on one part of a larger thing: “The politicians are trying to patch the old law by passing several related laws.” The verb “to patch” is normally used to talk about putting a small piece of something over a large hole or rip: “If you put patches over the ripped knees of your jeans, they’ll look much better.” Or, “This jacket has patches over the elbows, making the fabric stronger there.” The phrase “to patch things up” means to stop arguing with another person or to end an argument: “I don’t know if Gregory and I will ever be able to patch things up after what happened last weekend.”
Culture Note
Some American hackers have “gained” (earned; received through their actions) “notoriety” (fame for something bad that one has done) for their computer-related crimes.
Jonathan James was the first American “juvenile” (child; someone less than 18 years old) to be “incarcerated” (put in jail) for a computer-related crime. When he was 15 years old, he hacked into many computer systems, including those for the BellSouth communications company and the Miami-Dade school system. More seriously, he hacked into some of the computers that were part of the U.S. Department of Defense, downloading software worth about $1.7 million.
A man named Kevin Mitnick was “convicted” (found guilty of a crime) of “identity theft” (the crime of using another person’s name and other identifying information). He hacked into computer networks to get the “birth certificates” (official documents showing when and where someone was born) of very young children who had “passed away” (died) and then used them as his new identity.
Other people hack into computer networks to try to steal money by accessing credit card information. American hackers Adam Botbyl, Brian Salcedo, and Paul Timmins got access to the computer system for Lowe’s, which is a large “chain” (group of stores with the same name in many different locations) of home-improvement stores. They created a program to steal shoppers’ credit card information, but they were caught and convicted before they could do much damage.
Finally, some hackers create “worms,” or special computer programs that move across computer networks, causing damage to many computers. In 1988, Robert Tappan Morris created the Morris Worm, which spread across the Internet very quickly and “infected” (got into and made sick) thousands of computers. It cost $200-$53,000 to fix each damaged system.
Comprehension Answers
1 - c
2 - a