= 0595
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 595: Suffering from Allergies.
This is English as a Second Language Podcast episode 595. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Consider becoming a member of ESL Podcast and help support this effort. You can become a member by going to our website. You can also make a donation to ESL Podcast by going to that same web address.
This episode is a dialogue between Victor and his doctor; Victor is suffering from allergies. An “allergy” is a kind of illness where you eat something or you breathe something that gives you an uncomfortable reaction, basically it makes you sick. Let’s get started.
[start of dialogue]
Victor: Oh, doctor, you’ve got to help me!
Doctor: Try to relax. What seems to be the problem?
Victor: I’m sneezing all the time, and my eyes are itchy and watery.
Doctor: Tilt your head back so I can take a look at your nasal passages. You’re very congested.
Victor: My sinuses are killing me! I have headaches all the time and nothing I do seems to help.
Doctor: What is this on your skin?
Victor: I don’t know. I’ve had red spots all over my body.
Doctor: They look like hives to me. Are you experiencing any shortness of breath?
Victor: Well, my chest feels constricted and it’s hard to breathe.
Doctor: I think you may be experiencing a severe allergy attack. I’m going to refer you to an allergist. What were you doing right before you started experiencing these symptoms?
Victor: I started my first job.
Doctor: That could be your problem.
Victor: I knew it! I’m allergic to work!
[end of dialogue]
Victor says to his doctor, “Oh, doctor, you’ve got to help me (you have to help me)!” The doctor says, “Try to relax (try to be calm). What seems to be the problem?” What it is wrong with you, the doctor is asking, “What seems to be the problem?” Victor says, “I’m sneezing all the time, and my eyes are itchy and watery.” “To sneeze” (sneeze) means to have air pushed out your nose in a somewhat short and uncontrollable way. Basically, to sneeze is to go like this [sound of a sneeze]. In English, a sneeze is typically spelled “achoo” (achoo). I don’t know why, but we actually make that sound when we are imitating a sneeze. Victor is sneezing, and his eyes are itchy (itchy). “To itch” means that you have this unpleasant, uncomfortable feeling on your skin. When you say your “eyes are itchy,” you mean that you feel like rubbing them in order to get rid of this uncomfortable sensation – this uncomfortable feeling. “Watery” means with a lot of water, so if your eyes are watery there is a lot of water in your eye, perhaps even coming out of your eye. When you cry, your eyes are watery.
Victor isn’t crying, but he is in pain somewhat because he has the sneezing, the itchiness, and the watery eyes. The doctor says to Victor, “Tilt your head back so I can take a look at your nasal passages.” “To tilt” (tilt) means to move something that was straight up and down at an angle. You push something back, usually, when you tilt something, something that was straight up and down. The famous Leaning Tower of Pisa in Italy is a huge building that tilts. It is not straight up and down like you would normally expect in a building, although normally we would probably use this verb more for smaller things. For example, you have a bookcase where you keep your books but it isn’t even on the bottom, and so perhaps it tilts to the left or to the right, or tilts back. The doctor is telling Victor to put his head back – tilt his head back so he can look at his nasal (nasal) passages. “Nasal” refers to your nose – holes, two openings that connect eventually to your lungs and allow you to breathe. The doctor wants to take a look at these nasal passages. He says, “You’re very congested.” “To be congested” means that your nose and perhaps your breathing tube, which allows you to breathe in and out of your mouth, are not working correctly. There is liquid or something that is preventing you from breathing easily, especially out of your nose in this case.
Victor says, “My sinuses are killing me!” Your “sinuses” (sinuses) are two small empty spaces inside your head above your nose that are connected to your nose. Sometimes if you are sick, your sinuses fill with liquid and can give you a headache. That is what is happening to Victor. He says, “My sinuses are killing me!” When we say something is “killing me,” we mean it is hurting me or it is damaging me in some way. He says, “I have headaches all the time and nothing I do seems to help.”
The doctor then says, “What is this on your skin?” Victor says, “I don’t know. I’ve had red spots all over my body.” A “spot” (spot) is a small area that has a different color or a different feel than the surrounding area. Animals often have spots. A dog, for example, might have a very dark brown spot somewhere on its body, and the rest of his body might be light brown. That would be an example. Victor has red spots on his body – on his skin. The word “spot,” as well as the verb “to tilt,” have other meanings in English that can be found in today’s Learning Guide.
The doctor says that these red spots look like hives. “Hives” (hives) are red, uncomfortable spots on your skin that are caused either by some disease or by allergies. “Allergies” are when you have a uncomfortable reaction to something you eat, something you touch, or something you breathe. You can sometimes have problems like sneezing, itchy and watery eyes, congestion, sinus pain. All the things that Victor has could be from this negative reaction he’s having to something – that is to say, an allergy.
The doctor then asks, “Are you experiencing any shortness of breath?” “Shortness of breath” means you have difficulty breathing. Victor says, “ Well, my chest (the top part of my body, where your lungs are) feels constricted and it’s hard to breathe.” “Constricted” means limited, tightened, narrow, something that is unable to expand – to get bigger. And, if your chest feels constricted it’s like your lungs can’t work properly – you can’t breathe properly. He says, “it’s hard to breathe,” it’s hard to bring air into my lungs and out again.
The doctor says, “I think you may be experiencing (or having) a severe allergy attack.” An “allergy attack” is a period of time when you are being bothered by these allergies. “Severe” just means very strong or serious. The doctor says, “I’m going to refer you to an allergist.” “To refer (someone) to (someone else)” means you are going to recommend that person use this other person’s services. In the United States if you are sick, usually you go see what is called a “general practitioner,” a doctor who is not an expert necessarily in one thing but knows a little bit about all different kinds of medicine, and if the doctor can’t help you he’ll refer you to a “specialist,” someone who is an expert in that one area. Well, an “allergist” is someone who is an expert in allergies. I went to an allergist a couple of years ago. My allergies start bothering me seriously about two-three years ago, and the allergist gave me some pills; he gave me some other medicine to help me with my allergies. Sometimes if you hear that my voice is a little deep and it sounds like I have a cold, that’s probably because my allergies are bothering me that day, the day I record that episode – like today!
The doctor says, “What were you doing right before you started experiencing these symptoms (or these signs of illness)?” Victor says, “I started my first job.” The doctor says, “That could be your problem.” Victor says, “I knew it!” jokingly, “I’m allergic to work!” “To be allergic (allergic) to (something)” means that you have this negative physical reaction whenever you are near that thing or touch that thing. Some people are allergic to cats. If there’s a cat in the room they have this uncomfortable reaction. I am not allergic to cats, but I still have an uncomfortable reaction when they are in the room! Well, here Victor is making a joke. He’s saying, “I’m allergic to work,” it’s work that is making me sick. Sometimes we all feel that!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Victor: Oh, doctor, you’ve got to help me!
Doctor: Try to relax. What seems to be the problem?
Victor: I’m sneezing all the time, and my eyes are itchy and watery.
Doctor: Tilt your head back so I can take a look at your nasal passages. You’re very congested.
Victor: My sinuses are killing me! I have headaches all the time and nothing I do seems to help.
Doctor: What is this on your skin?
Victor: I don’t know. I’ve had red spots all over my body.
Doctor: They look like hives to me. Are you experiencing any shortness of breath?
Victor: Well, my chest feels constricted and it’s hard to breathe.
Doctor: I think you may be experiencing a severe allergy attack. I’m going to refer you to an allergist. What were you doing right before you started experiencing these symptoms?
Victor: I started my first job.
Doctor: That could be your problem.
Victor: I knew it! I’m allergic to work!
[end of dialogue]
We’re glad our scriptwriter is not allergic to work. That’s because we enjoy the scripts written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
to sneeze – to uncontrollably push air and drops of liquid from one’s nose and mouth, usually making a loud noise, often when one is sick or when the air is dirty
* Please cover your mouth and nose when you sneeze!
itchy – having an unpleasant, uncomfortable feeling on the skin that makes one want to scratch the surface with one’s fingernails
* Her skin gets itchy when the air is very dry.
watery – with a lot of water; filled with water
* His eyes were really watery and it looked like he was trying not to cry.
to tilt – to move something so that it is at an angle, not straight up and down
* They tilted their bookcase toward the wall to make it safer, so that it wouldn’t fall down if their son tried to climb up it.
nasal passage – nostril; one of the two pathways from the hole in one’s nose to the lungs
* The child put a coin up his nose, blocking his nasal passage, and had to be taken to the hospital.
congested – with a lot of congestion; with one’s nose or other body parts full of liquid and mucus or snot, making it difficult to breathe
* If you’re too congested, try taking this medicine, which should make it easier to breathe.
sinuses – the empty spaces in some of the bones connected to the inside of one’s nose
* The doctor looked at Madia’s sinuses and said she had a sinus infection.
spot – a small area that has a different color or texture than the surrounding area
* Their new puppy is light brown with dark spots on his left ear and back feet.
hives – red, uncomfortable skin caused by a disease or an allergic reaction
* Whenever Rahim eats strawberries, he breaks out in hives.
shortness of breath – difficulty breathing, so that one feels as if he or she cannot get enough oxygen, almost as if he or she had just done of lot of exercise
* If you experience shortness of breath while exercising in this class, please slow down.
constricted – with limited physical movement; narrowed and tightened; unable to expand as much as desired
* Ed hates driving small cars, because he always feels too constricted in them.
to breathe – to bring air into one’s lungs and push it back out again through the nose or mouth; to inhale and exhale
* If you feel nervous during the interview, just remember to breathe and to try to relax.
severe – very strong and serious
* We’re expecting a severe thunderstorm this afternoon.
allergy attack – a period of time when one feels sick and uncomfortable because one has been exposed to an allergen (something that one is allergic to)
* Have you ever had an allergy attack from eating peanuts?
to refer (someone) to (someone) – to officially recommend that someone use the professional services of another person, especially of a doctor
* Henrietta’s doctor referred her to a dermatologist for her skin problems.
allergist – a doctor who specializes in allergies (the physical reactions people have when they eat certain foods or touch certain substances)
* The allergist tested Craig for allergies to grass, cat hair, dog hair, and pollen.
allergic to (something) – having an uncomfortable, possibly dangerous physical reaction to something that one has eaten or touched
* Have you always been allergic to tomatoes?
Comprehension Questions
1. Which of these does not affect the nose?
a) Sneezing.
b) Congestion.
c) Hives.
2. What does the doctor mean when she says, “I’m going to refer you to an allergist”?
a) She thinks he’s suffering from the allergist disease.
b) She’s going to recommend that he see a different doctor.
c) She’s going to consult with one of her colleagues.
Answers at bottom.
What Else Does It Mean?
to tilt
The verb “to tilt,” in this podcast, means to move something so that it is at an angle, not straight up and down: “The dog tilted her head at me, as if she were asking a question.” Or, “Why are all the paintings in your apartment tilted at an angle?” The verb “to tilt” also means for people’s opinion about a situation or issue to change: “What caused public opinion to tilt against the war?” Or, “Do you remember when your interests started to tilt toward political science?” Finally, the phrase “to tilt at windmills” means to use one’s time and energy in unproductive ways, fighting against something that isn’t really the problem: “He isn’t your enemy – she is. And until you realize that, you’re just tilting at windmills.”
spot
In this podcast, the word “spot” means a small area that has a different color or texture than the surrounding area: “When Joanne spilled her wine, it left a horrible red spot on the white carpet.” A “spot” is also a place: “This coffee shop is my favorite spot in the city for relaxing and reading the newspaper on Saturday morning.” The phrase “on the spot” means immediately, without taking time to think about something: “The professor insisted that the students answer the questions on the spot, without taking the time to look anything up in their textbook.” Finally, the phrase “to put (someone) on the spot” means to put someone in a difficult, uncomfortable, or embarrassing position, usually by asking questions that he or she does not want to answer: “Reporters are very good at asking questions that put politicians on the spot.”
Culture Note
Many Americans have allergies and these are some of the most common.
Common food allergies include peanuts, “dairy” (milk and milk products), wheat, soy, and “shellfish” (fish from the ocean with hard shells, like oysters and crabs). Peanut allergies, in particular, have become so common that many “daycare facilities” (places that provide childcare) and schools have stopped serving “peanut-derived” (made from peanuts) foods. The “nutrition information panels” (information written on food packages about what is inside) on food packages often include lists of common allergens, and people with allergies read those labels carefully before deciding what to eat. Some restaurants also list allergy information in their menus.
Many people are allergic to “pet” (animals that live with people for companionship and entertainment, not to be eaten) hair, “pollen” (powder carried by the wind and insects from one plant to another for reproduction), feathers, and insects. People who are allergic to pet hair, dust, pollen, and similar allergens are advised to remove carpet from their home and instead use wood or tile floors. Sometimes these people wear “masks” (something that covers part or all of one’s face) if they must go outside when there are high “pollen counts” (the amount of pollen in the air).
Other people have very sensitive skin and “suffer” (experience something negative or painful) allergy attacks if their skin is “exposed to” (comes in contact with) certain products. These people are advised to use “hypoallergenic products,” such as skin creams and cosmetics, which are created without allergens.
Comprehension Answers
1 - c
2 - b