= 1054
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,054 – Finding a Roommate.
This is English as a Second Language Podcast episode 1,054. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there. Become a member of ESL Podcast and download a Learning Guide for this episode.
This episode is a dialogue between Carlos and Inez about finding someone to be your roommate. Let’s get started.
[start of dialogue]
Carlos: Now that your boyfriend has moved out, you need a roommate. There’s no way you can afford this apartment on your own.
Inez: I know, but I really don’t want to live with a stranger. I’d have to put up with all of their quirks.
Carlos: I don’t think you have a choice. You need someone to split the rent and the cost of utilities, not to mention your cable bill.
Inez: I’d need someone who could keep the common areas neat and clean and who can keep their hands off my stuff.
Carlos: I’m sure you’ll manage to find someone with those qualities.
Inez: They’d have to help with chores around the apartment, too, and pitch in with general upkeep.
Carlos: No doubt there’s someone out there who wouldn’t mind doing that.
Inez: Hey, aren’t you looking for a place to live? You could move in here.
Carlos: You mean share an apartment with you? No thanks.
Inez: Why not?
Carlos: I’d just rather not. I don’t think we’d suit.
Inez: Why wouldn’t we?
Carlos: Do you really want me to spell it out for you?
Inez: Yes, in fact, I insist.
Carlos: All right. Let’s just say that you’re a little bit grouchy in the mornings. You know that monster in the Alien movies?
Inez: Yes.
[silence]
Carlos: Ouch! Ouch! Stop hitting me!
[end of dialogue]
Our dialogue begins with Carlos and Inez talking about getting a new roommate. Carlos says that Inez’s old roommate – her boyfriend, apparently – has moved out. “To move out” means to leave the place where you are living and go somewhere else, go somewhere else to live. Inez is correcting her first mistake, which was to move in with her boyfriend.
Now she needs to find a “roommate” (roommate). A “roommate” is a person you live with, but someone with whom you don’t have any romantic connection. Usually a roommate is a friend or another person who helps you pay for the rent and the expenses of your house or apartment. Carlos says, “There’s no way you can afford this apartment on your own.” “To afford” (afford) means to be able to pay for something, to have enough money to pay for something.
Inez says, “I know, but I really don’t want to live with a stranger.” A “stranger” (stranger) is anyone you don’t know, anyone who is unknown to you – a person you may see on the street or in a store. If you don’t know them, they are strangers. Inez says, “I have to put up with all of their quirks.” “To put up with” something is to tolerate something, especially something that is difficult or unpleasant. To put up with a person or a situation is to have to get along with the person or to handle the situation even though it isn’t very pleasant, isn’t very nice.
Inez doesn’t want to put up with a stranger’s “quirks” (quirks). A quirk is an unusual behavior or habit – something someone does that is uncommon and not usually done by most people. All of us have quirks, things that we do that are different than most people. Carlos says, “I don’t think you have a choice. You need someone to split the rent and the cost of utilities, not to mention your cable bill.” “To split” (split) means to share – often, to divide something into two equal parts.
If you are splitting the bill at a restaurant, each of you is going to pay 50 percent of the bill. That’s normally how it works, but you could have a split that was 70 percent/30 percent. Carlos says Inez needs a roommate “to split the rent.” The “rent” (rent) is the amount of money you pay to live in your home or in your apartment if you don’t own it. “Utilities” (utilities) is a general term referring to the electricity, the water, the gas, and other services that are delivered to a home or business so that you can live or work there. These things are referred to in general as “utilities.”
Carlos also mentions Inez’s cable bill. Your “cable (cable) bill” is the amount of money you have to pay in order to get cable television into your home. Some people have satellite television as well, or instead of cable television, usually. In either case, it’s an extra expense – more money you have to pay every month.
Inez says, “I’d need someone who could keep the common areas neat and clean, and who can keep their hands off my stuff.” The “common areas” in an apartment or a building are the areas that are shared with other people, that other people use. It’s often the case that two people who are roommates in an apartment will have their own bedrooms. However, the kitchen and the living room are shared or common areas – areas both of them use.
Inez is worried about getting a roommate who is neat and clean. “Neat” means orderly. “Tidy” (tidy), we might also say. “Clean” means the opposite of dirty. Inez wants someone who can also keep his hands off her stuff. “To keep your hands off” someone’s things means to not touch it, especially something that is private, something that belongs to another person. “Keep your hands off of my wallet” – don’t touch my wallet. It doesn’t belong to you – unless you’re my wife, in which case everything belongs to you.
Carlos says, “I’m sure you’ll manage” – you’ll be able – “to find someone with those qualities,” with those characteristics. Inez says, “They’d have to help with chores around the apartment, too, and pitch in with general upkeep.” “Chores” (chores) are tasks – things you have to do, usually involving cleaning in a house.
There are lots of different chores, different things you have to do in your house in order to keep it clean. You have to wash the dishes, for example. You have to take out the garbage. Take your trash and leave it somewhere so it can be picked up. These are all chores. The word “chore” is often used to describe an unpleasant task. I guess since most people think that keeping their house clean isn’t a lot of fun.
Inez wants someone to “pitch in with general upkeep.” “To pitch in” is a two-word phrasal verb meaning to help with something, to contribute by doing something. “I want everyone to pitch in and help me clean my room.” You’re asking other people to work with you, to help you. You can also use “pitch in” in a financial sense. “We’re all going to pitch in and buy our boss a birthday present.” We’re all going to give money in order to buy the gift.
Inez wants someone to pitch in with the “general upkeep.” “Upkeep” (upkeep) – one word – is another term for maintenance. Upkeep involves keeping things clean and in good condition. If they break, you fix them. Usually the word “upkeep” is applied to some sort of property, such as a house or an apartment building. Carlos says, “No doubt there’s someone out there who wouldn’t mind doing that.” Carlos thinks that Inez can find a roommate like what she’s looking for. Inez says, “Hey, aren’t you looking for a place to live? You could move in here.” Inez is inviting Carlos to be her roommate.
Carlos says, “You mean share an apartment with you? No, thanks.” Carlos is not interested. Inez says, “Why not?” Carlos says, “I’d just rather not.” When you don’t want to give the reason why you don’t want to do something – usually because you think the other person will get mad at you or will be offended – you can say something like, “I’d rather not.” “I’d just rather not,” Carlos says. “I don’t think we’d suit.” “To suit” (suit) in this case means to be appropriate for someone or something – to meet the requirements or needs of someone.
Inez says, “Why wouldn’t we?” meaning “Why wouldn’t we be suited for each other?” we could say. Carlos says, “Do you really want me to spell it out for you?” “To spell” (spell) normally means to give the letters of the words, like I do here on the podcast. “To spell it out,” however, means to say something explicitly and directly – to give a lot of details so there’s no possibility of the person misunderstanding you.
Carlos doesn’t want to give Inez a list of reasons why he should not be her roommate. He doesn’t want to offend her. He doesn’t want to make her upset. That’s why he says, “Do you really want me to spell it out for you?” Inez says, “Yes, in fact, I insist.” “To insist” (insist) means to demand that something happen, to not accept any other alternatives.
Carlos then says, “All right. Let me just say that you’re a little bit grouchy in the mornings.” “To be grouchy” (grouchy) means to be in a bad mood, to be unpleasant, often because you’re tired or you’ve had a bad day or perhaps you didn’t sleep well, if you’re grouchy in the morning. “You know that monster in the Alien movies?” Carlos is asking Inez if she remembers the series of movies about an outer space monster, an outer space creature. Inez says, “Yes.”
And then Carlos says, “Ouch, ouch! Stop hitting me!” What happened here, of course, is Inez is hitting Carlos because she’s angry at him. She feels insulted. But to be fair to Carlos, she did ask for him to spell it out, to give her the exact reasons why she would not be a good roommate for him.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Carlos: Now that your boyfriend has moved out, you need a roommate. There’s no way you can afford this apartment on your own.
Inez: I know, but I really don’t want to live with a stranger. I’d have to put up with all of their quirks.
Carlos: I don’t think you have a choice. You need someone to split the rent and the cost of utilities, not to mention your cable bill.
Inez: I’d need someone who could keep the common areas neat and clean and who can keep their hands off my stuff.
Carlos: I’m sure you’ll manage to find someone with those qualities.
Inez: They’d have to help with chores around the apartment, too, and pitch in with general upkeep.
Carlos: No doubt there’s someone out there who wouldn’t mind doing that.
Inez: Hey, aren’t you looking for a place to live? You could move in here.
Carlos: You mean share an apartment with you? No thanks.
Inez: Why not?
Carlos: I’d just rather not. I don’t think we’d suit.
Inez: Why wouldn’t we?
Carlos: Do you really want me to spell it out for you?
Inez: Yes, in fact, I insist.
Carlos: All right. Let’s just say that you’re a little bit grouchy in the mornings. You know that monster in the Alien movies?
Inez: Yes.
[silence]
Carlos: Ouch! Ouch! Stop hitting me!
[end of dialogue]
It’s no chore to listen to the wonderful scripts by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
roommate – a person whom one lives with, without being related or in a romantic relationship, usually to reduce expenses
* Are you still in touch with any of your roommates from college?
to afford – to be able to pay for something; to have enough money to pay for something
* How can she afford to drive a Porsche on a teacher’s salary?
stranger – a person whom one does not know
* Mariah has taught her children to never speak to strangers.
to put up with – to tolerate something or someone, especially something that is challenging, difficult, and unpleasant
* This apartment is cheap, but if we live here, we’ll have to put up with all the noise from the airport.
quirk – an unusual behavior or habit that is not found among most people
* Justina as a strange quirk of always checking at least three times to make sure the door is locked before she leaves the house.
to split – to share something; to divide something into at least two parts
* Whenever they go out to dinner, they always split the bill evenly, no matter what each person has ordered.
rent – the amount of money paid each month in exchange for having a place to live
* The landlord wants to raise the rent from $1,300 to $1,500 beginning next month.
utilities – electricity, water, gas, sewage, and other services that are delivered to a home or business
* We typically spend more on utilities in the winter, when we have to pay more to heat the home.
cable bill – an invoice received each month requesting payment for receiving cable television services
* We could save a lot of money if didn’t have a cable bill each month and just watched movies and TV shows online.
common area – an area that is shared with other people who live in the same building, such as the living room and kitchen, but not the private spaces like the bedroom
* The roommates take turns cleaning the common areas.
to keep (one’s) hands off – to not touch something, especially something that is private and belongs to another person
* Keep your hands off the chocolate chips. I want to use them to make cookies tonight.
chore – a task that must be completed, especially to clean or maintain something in or around the home
* Their teenage sons have to perform a lot of chores, like washing dishes, folding laundry, and mowing the lawn.
to pitch in – to help with something; to contribute by doing something
* Could you please pitch in and help us weed the garden?
upkeep – maintenance; efforts to keep things clean, tidy, and in good working condition
* Being a responsible homeowner means managing the upkeep, such as removing leaves from the roof and repairing leaking faucets.
to suit – to be appropriate for someone or something; to meet the requirements or needs of someone or something
* An office job doesn’t suit Harry. He needs to be outdoors.
to spell (something) out for (one) – to say something explicitly; to state something very clearly, directly, and in a lot of detail so that there is no chance one’s meaning will be misunderstood
* Camilo tried to be kind, but in the end he had to spell it out for Cheryl: “You’re fired.”
to insist – to demand that something happen and not accept any other alternative
* It’s my turn to pay. Please, I insist.
grouchy – in a bad mood; grumpy; unpleasant to be around, especially if one is tired
* Francesca is really grouchy in the morning before she has a shower and drinks her coffee.
Comprehension Questions
1. According to Carlos, why does Inez need a roommate?
a) So that she doesn’t get lonely
b) So that she can to cover her expenses
c) So that her boyfriend will be jealous
2. What does Inez mean when she says she’ll need someone “who can keep their hands off my stuff”?
a) She needs someone who will do chores.
b) She needs someone who won’t touch her belongings.
c) She needs someone who likes to wear suits.
Answers at bottom.
What Else Does It Mean?
common areas
The phrase “common areas,” in this podcast, refers to areas that are shared with other people who live in the same building, such as the living room and kitchen: “They have very different ideas about how they should decorate the common areas.” The phrase “common sense” refers to one’s ability to be rational and make good decisions: “Not walking alone at night in dangerous neighborhoods is just common sense.” The phrase “the common cold” refers to a common illness where people feel sick and have congestion (blocked nose) and a sore throat: “Please don’t come to the office when you’re sick, even if it’s just the common cold.” Finally, the phrase “common denominator” refers to some characteristic that is shared by everyone or everything in a group: “The common denominator of everyone in Alcoholics Anonymous is that they want to stop drinking.”
suit
In this podcast, the verb “to suit” means to be appropriate for someone or something, or to meet the requirements or needs of someone or something: “In this neighborhood, we can find restaurants to suit all budgets.” The verb “to suit” can also mean to look good or attractive: “That color suits her very well.” The informal, slightly rude phrase “suit yourself” is used to tell a person that he or she can behave however he or she wants, but one does not think it is good or proper: “I think the dress is ugly, but you can buy it if you want to. Suit yourself.” Finally, the phrase “to be perfectly suited for (something)” means to have all the characteristics to do something: “Wayne seems perfectly suited for fatherhood.”
Culture Note
Roommate Agreements
“Taking on” (agreeing to have or do something) a roommate can present a big “liability” (something that can create financial obligations or other problems in the future), especially if the roommate does not pay the rent “on time” (when something is due). In the past, roommates had verbal agreements “governing” (covering) how they would pay the rent and “divvy up” (share and divide) chores, but now written “roommate agreements” are becoming “increasingly” (more and more) common.
Roommate agreements always “address” (deal with) the payment of rent, “specifying” (stating specifically) the amount and timing of payments, as well as “penalties” (punishments) for not paying on time. The agreements usually also address the use of “space” (rooms), indicating which bedroom(s) belong to each roommate and how common areas will be shared.
Many roommate agreements also try to “establish” (create) rules for daily living. They might specify which roommates are responsible for which chores, and how often they must be completed, as well as penalties for failing to perform those chores. And many agreements address whether and how the roommates will share the cost of buying food and preparing meals. Some roommates choose to keep everything separate. Others share only “staples” (common food items, like flour and oil), and others “alternate” (take turns) shopping and cooking “duties” (responsibilities; tasks).
Sometimes roommate agreements address “behavioral issues” (how people behave or act), such as appropriate “noise levels” (how much noise people make) and when music can be played. And sometimes agreements address whether and how often the roommates can have “guests” (people who are invited into the home for a short period of time), or have a boyfriend or girlfriend spend the night in the apartment or home.
Comprehension Answers
1 - b
2 - b