= 1083
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,083 – Types of Pants.
This is English as a Second Language Podcast episode 1,083. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast Store, which has some Business and Daily English courses that I know you will love.
On this episode, we’ll listen to a dialogue between Josh and Kayla about different kinds of pants – you know, the things you wear on your legs. Let’s get started.
[start of dialogue]
Josh: We are going to get you out of those baggy sweatpants and into some pants that fit.
Kayla: I don’t like pants that are too formfitting.
Josh: I’m not suggesting you buy skintight leggings, but some nice slacks would be slimming.
Kayla: I like pants with an elastic waistband. They’re more comfortable.
Josh: Just try these khaki chinos. They’re not too tight, they’re made of a breathable fabric, and they’re comfortable.
Kayla: I’d rather buy a pair of broken-in jeans.
Josh: You can’t wear jeans to your new job.
Kayla: I know, but these pants are too constricting. Do you think they sell dressy sweatpants?
Josh: That is the best example of an oxymoron I’ve ever heard.
[end of dialogue]
Josh begins our dialogue by saying to Kayla, “We are going to get you out of those baggy sweatpants and into some pants that fit.” “To get someone out of” something is to have them remove the clothing that they are wearing, and that’s what Josh is talking about when it comes to Kayla.
Kayla is wearing some “baggy sweatpants.” “Sweatpants” (sweatpants) are very comfortable, loose pants that are typically made with a soft material, a soft fabric – something like cotton. Sweatpants are often used for people who are exercising. If they don’t want to wear shorts, they wear sweatpants. The verb “to sweat” (sweat) refers to water coming out of your body when you are exercising or when you get hot. A lot of people wear sweatpants at home because they’re comfortable, and if you are in a cold climate, an area where the weather is somewhat cold, they are also a little warmer.
“Baggy” is an adjective we use when talking about clothing to refer to clothing that is too big for someone, that is very large for someone. I say “too big” – that’s probably not quite the way to describe it. It’s a piece of clothing that is very large, that is much larger than your body, much larger than you would normally wear. If your pants are baggy, your pants are too big for you. There’s a lot of room in between your body and the material of the pants.
Josh is telling Kayla that she is going to have to take off her baggy sweatpants and get “into some pants that fit” (fit). The verb “to fit” here means it’s the proper size or the appropriate size for someone. If you say a certain shirt “fits” you, you mean the shirt is not too big – it’s not too baggy – and it’s not too small. We would say it’s “not too tight” (tight).
Kayla says, “I don’t like pants that are too formfitting.” A piece of clothing that is “formfitting” is one that is tight up against your body. It’s not too small, but it touches your skin, typically. If you wear it, someone can see your form underneath the clothing. They can see the shape of your body very clearly. Kayla says she does not like “pants that are too formfitting.”
Josh says, “I’m not suggesting you buy skintight leggings, but some nice slacks would be slimming.” Something that is “skintight” is something that is similar to formfitting, but it’s even tighter. It’s very tight against your skin. “Leggings” (leggings) are tight pants that end at the ankles, the part that connects your leg to your foot. They are often worn underneath a skirt or a dress. They are used when the weather is cold outside, usually by women. The term “slacks” (slacks) refers to pants that are considered more formal, that you would wear to work or to some sort of professional event.
Josh is saying that he doesn’t want Kayla to buy skintight leggings, but rather some nice slacks – a nice pair of pants that he says would be “slimming” (slimming). Something that is “slimming” is something that makes you appear thinner than you actually are, that makes you appear to weigh less than you actually do. The color black is often used to this effect, to have a slimming effect, so that you don’t seem quite as fat as you really are.
Kayla says, “I like pants with an elastic waistband. They’re more comfortable.” The “waistband” (waistband) refers to the top part of a pair of pants, the part that goes around your waist. What is your “waist” (waist)? It’s the part of your body where your legs are connected to the main or torso part of your body. You can think of it as an imaginary line that goes around the middle of your body.
Usually, when you put on a pair of pants, you pull the pants up and the pants stop right around your waist. In fact, when you buy a pair of pants, typically the size is given in inches or centimeters, including the size of the waist, because of course you need a pair of pants that are not too big and not too small for your particular body. Pants sizes are also usually given in terms of the length of the individual “pant legs,” we would call them.
Kayla is talking about a waistband that is “elastic” (elastic). If a fabric or a material is “elastic,” it stretches. It is “expandable,” we could also say. So, for example, if you have a pair of sweatpants on, usually the sweatpants will have an elastic band on the top so that if you are a little skinnier or a little fatter, the pants will still fit you. This is in comparison to a pair of slacks, a more formal pair of pants, where the waistband doesn’t stretch. It doesn’t get bigger or smaller depending on your body.
Josh gives Kayla some khaki chinos to try. “Chinos” (chinos) are pants that are not formal, but not informal. They’re sort of in between. Usually they have a zipper and a button on the front of them. “Khaki (khaki) chinos” are usually a light brown or tan colored pair of pants. “Khakis” became very popular a few years ago. They’re not really formal pants. You wouldn’t wear them to a wedding or funeral probably, but they’re also not too informal, either. They’re not like a pair of sweatpants, say.
Josh says the khaki chinos are not too tight and they’re made of a “breathable fabric.” “Fabric” (fabric) refers to the material that clothing is made of. If the fabric is “breathable” (breathable), it is fabric that allows air to pass through easily. “Cotton,” for example, is considered a breathable fabric.
Kayla says, “I’d rather buy a pair of broken-in jeans.” “Jeans” (jeans) are pants usually made from a material called “denim” (denim), and they’re typically blue, although nowadays you can get jeans in other colors as well. If the clothing is “broken-in” (broken-in), it has already been worn or washed many times so that it’s more comfortable, or at least that’s one reason why people would buy jeans that are broken-in. They’re usually softer, because denim can sometimes be a little uncomfortable when it is new, when it hasn’t been worn or washed before.
We use the phrasal verb “to break in” also when we’re talking about a pair of shoes. If someone says, “I need to break in this pair of shoes,” he means that he needs to wear the shoes in order to make them softer and more comfortable. Shoes, when you first buy them, especially formal shoes – shoes that you would wear for a formal occasion – are sometimes hard and a little uncomfortable when you first start wearing them. So, we use the expression “to break-in” to refer to the process of making the shoe more comfortable by wearing it, usually a little bit every day until the shoes are broken-in.
Josh says, “You can’t wear jeans to your new job.” Jeans are considered informal pants, not the kind of thing you would wear to a job – not to any sort of formal event, either. Kayla says, “I know, but these pants are too constricting.” Kayla has put on another pair of pants that Josh has recommended and is complaining that they’re too constricting. If pants are “constricting” (constricting), they’re too tight, and that’s the problem Kayla is having.
She says, “Do you think they sell dressy sweatpants?” If clothing is “dressy” (dressy), it’s something that can be used in a formal situation or for a formal occasion. When we talk about our “dress clothes,” we’re talking about clothes that would be used for a formal event. If you’re going to a wedding, you would want to wear your dress clothes. You would want your clothes to be “dressy.”
Kayla’s asking if she can buy a pair of “dressy sweatpants.” And Josh says no, that is an “example of an oxymoron.” The term “oxymoron” (oxymoron) is used to describe two words that are put together that have the opposite meaning. If someone were to say, for example, “He’s a short giant.” Well, a “giant” (giant) is a very tall person or creature. So, you can’t have a “short giant.” That’s an oxymoron. The two words don’t go together. They have opposite meanings.
Sometimes people use this as a way of making a joke, using certain adjectives or adverbs next to nouns or verbs or other adjectives that don’t go together or that are opposite. If you said something was “beautifully ugly,” that would be an example of an oxymoron because “beautiful” and “ugly” are opposites. Kayla wants to buy some sweatpants that are dressy, and that’s not possible because sweatpants are “by definition,” we would say, by their very nature, not formal, not dressy.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Josh: We are going to get you out of those baggy sweatpants and into some pants that fit.
Kayla: I don’t like pants that are too formfitting.
Josh: I’m not suggesting you buy skintight leggings, but some nice slacks would be slimming.
Kayla: I like pants with an elastic waistband. They’re more comfortable.
Josh: Just try these khaki chinos. They’re not too tight, they’re made of a breathable fabric, and they’re comfortable.
Kayla: I’d rather buy a pair of broken-in jeans.
Josh: You can’t wear jeans to your new job.
Kayla: I know, but these pants are too constricting. Do you think they sell dressy sweatpants?
Josh: That is the best example of an oxymoron I’ve ever heard.
[end of dialogue]
We’d like to thank our scriptwriter, Dr. Lucy Tse, for her wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
baggy – with a lot of extra room; a piece of clothing that is much larger than the person’s body
* Shoplifters sometimes wear baggy clothes so they can hide items in their clothes and leave the store without paying for them.
sweatpants – very comfortable, loose pants with an elastic or tied waist and soft cotton fabric, usually used for exercise or worn in the home, not in public
* Would you wear sweatpants to go grocery shopping, or is that too informal?
formfitting – clothing that shows the shape of one’s body because it is tight and stays right next to the skin
* Are ice skaters required to wear such formfitting outfits at competitions?
skintight – clothing that is very tight and stays extremely close to the skin
* Professional swimmers wear skintight swimsuits, because any extra fabric would slow them down.
leggings – tight, stretchy pants that end at the ankles, often worn underneath a skirt or dress when the weather is cold
* This short dress would look great with leggings and a pair of boots.
slacks – dress pants that are appropriate for the workplace and professional or semi-formal events
* Are these slacks dressy enough for the party, or should I wear a dress?
slimming – making one appear thinner than one actually is; making one appear to weigh less
* Vertical strips are more slimming than horizontal stripes.
elastic waistband – the top part of a pair of pants, the part that goes around one’s waist and above one’s hips, made from a stretchy, expandable fabric
* Uncle Gary always says that the key to getting good value at an all-you-can-eat buffet is to wear pants with an elastic waistband!
khaki chinos – tan or cream-colored pants, usually with creased (with an ironed fold) legs and a zipper and button at the front
* At our software development firm, nobody wears a suit. Most people wear khaki chinos and a button-down shirt without a tie.
breathable fabric – cloth that allows air to pass through easily, often used for casual clothing
* The gym sells a lot of workout clothes that are made from breathable fabric.
broken-in jeans – pants made from denim fabric that have been worn and washed many times so that the fabric has become softer and usually a lighter color
* I’ve had these broken-in jeans for years. They’re my favorite and most comfortable pants!
constricting – tight, not allowing blood to flow freely
* The nurse put a constricting band on the patient’s arm before taking his blood.
dressy – dressed up; formal, or at least appropriate for work; not casual
* Are these shoes dressy enough to wear to a formal dinner party?
oxymoron – a phrases that uses two words with opposite meanings
* Wow, that building is pretty ugly. Of course, that’s an oxymoron.
Comprehension Questions
1. Which of these pants is the dressiest?
a) Sweatpants
b) Jeans
c) Khaki chinos
2. Which of these would be most likely to have an elastic waistband?
a) Baggy sweatpants
b) Formfitting pants
c) Skintight leggings
Answers at bottom.
What Else Does It Mean?
slacks
The word “slacks,” in this podcast, means dress pants that are appropriate for the workplace and professional or semi-formal events: “Do these slacks match this blazer?” The phrase “to pick up the slack” means to do something that needs to be done, but that no one else is doing: “Who’s going to pick up the slack at the office while Robert is on vacation next week?” The phrase “to cut (someone) some slack” means to stop criticizing someone, or to stop making a situation more difficult for someone: “I’m sorry I turned in the report late, but cut me some slack! I have way too much work to do right now.” Finally, if someone is “slack-jawed,” his or her mouth is a little bit open, usually due to surprise or shock: “When Karim announced that we’d lost the contract, we were all slack-jawed.”
broken in
In this podcast, the phrase “broken in” describes a piece of clothing that has been worn and/or washed many times so that the fabric has become softer: “These hiking boots should be a lot more comfortable once they’re broken in.” The phrase “broken (language)” describes written or spoken language that is slow and with many errors because it is not one’s first language: “His broken Spanish was really difficult to understand over the phone, but at least he’s trying.” The phrase “broken home” is a negative term that describes a family where the parents have divorced: “Matty comes from a broken home, so he lives with his mom, but spends every other weekend with his dad.” Finally, the phrase “broken heart” describes extreme sadness, usually due to a breakup or death of a loved one: “Everyone said she died of a broken heart shortly after her husband passed away.”
Culture Note
Women in Pants
In the past, women almost always wore dresses or skirts, not pants. But that changed in the early “20th century” (the 1900s). For many women, the change was a “product” (result) of World War I. While men were “on the frontlines” (fighting battles in war), women had to fill the jobs that men previously held, such as factory jobs, and many of them began wearing pants for comfort and “functionality” (meeting a particular purpose; with some use).
Beginning in the 1930s, some actresses, such as Marlene Dietrich and Katharine Hepburn, were photographed while wearing pants, increasing the popularity of the clothing. But there were still many “hurdles” (challenges; obstacles) to pass before pants would become acceptable for all women.
In official settings, the acceptance of pants for women took even longer. Hillary Clinton was the first U.S. “First Lady” (wife of the president) to wear pants in an official “portrait” (a painting of a person). And women were not allowed to wear pants on the “floor” (where speakers stand) of the U.S. Senate until 1993.
In the State of California, the “right” (official ability to do something) for women to wear pants was “codified” (made into law) in the California Fair Employment and Housing Act, which allows women to file a “discrimination complaint” (a statement that one has been treated unfairly, especially for employment) if they are “denied” (not given) the right to wear pants.
Comprehension Answers
1 - c
2 - a