= 1086
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,086 – Giving Bribes to Children for Good Behavior.
This is English as a Second Language Podcast episode 1,086. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at ESLPod.com. Become a member of ESL Podcast. Take a look at our ESL Podcast Store. You could also like us on Facebook at facebook.com/eslpod. Oh, yeah – we’re on Twitter too, at @eslpod.
This episode is a dialogue between Camille and Aaron about giving things to your children so that they will behave – so that they will not be like my neighbor’s children who are always yelling and screaming. It’s crazy. Anyway, let’s get started.
[start of dialogue]
Camille: No, you can’t have a new bike if you get an A on the test. You should study because you want to do well in school. We’ll talk about it when I get home tonight. Kids!
Aaron: What’s the matter?
Camille: My kids won’t do anything without an incentive. I know it’s my own fault for offering rewards for good behavior, but now all they want to know is what they’ll get to do what I ask.
Aaron: Rewards are okay if you use them sparingly, aren’t they?
Camille: That’s the problem. I feel like I have to bribe them to do the simplest things. I get home from work and I’m tired and frazzled. I don’t want another power struggle, so I rely on bribes. It’s backfired.
Aaron: How do you mean?
Camille: Now my kids won’t do anything without knowing what’s in it for them. And they keep upping the ante. Soon I’ll have to start forking over cash to get them to behave.
Aaron: I don’t know what to say. When I was growing up, my mother put the fear of God into us. We wouldn’t dare misbehave for fear of making her angry. We never got rewards for good behavior. It was just expected of us.
Camille: What’s your mother’s number? Is she available to babysit?
Aaron: Uh, I don’t know. I don’t think she could inspire that kind of obedience from other people’s children.
Camille: I’m desperate! At the very least, she can give me a few parenting lessons.
[end of dialogue]
Our dialogue begins with Camille saying, “No, you can’t have a new bike if you get an A on the test.” Camille is talking to her son or daughter, we guess. The child has asked his mother if he could get “a new bike” – a new bicycle – if he gets an A on his test. An A is the highest score that you can get on a test or an examination or a school assignment. Camille says to her child, “You should study because you want to do well in school.” In other words, you shouldn’t study just to get a reward, a prize. You should study because you want to be successful in school.
Camille says, “We’ll talk about it when I get home tonight.” Next we hear from Aaron, who appears to be with Camille – another adult who has been listening to Camille talk to her child. Aaron says, “What’s the matter?” meaning “What’s wrong?” What’s the problem? Camille says, “My kids” – my children – “won’t do anything without an incentive.” An “incentive” (incentive) is something that motivates you to do something, something that makes you want to do something else. For some people, an incentive might be money. They might work harder in order to get more money. The money is an incentive.
Camille says, “I know it’s my fault for offering rewards for good behavior, but now all they want to know is what they’ll get to do what I ask.” Camille is saying that it’s her “own fault,” meaning the blame is on her. She is responsible for this situation. The situation is that her children won’t do anything without a “reward” (reward). A reward is something you give to someone – sometimes to thank him or her for doing something for you, sometimes because the person has done something that you think is good and you want to encourage them to do it even more.
Camille has been giving her children rewards for good behavior. “Good behavior” is when someone acts nice, is polite, does what he or she is told. It’s a term we often use in describing the way children act. Aaron says, “Rewards are okay if you use them sparingly, aren’t they?” “To use something sparingly” (sparingly) means to use it not very often. If you use, say, salt sparingly on your food, you’re only going to put a little bit of salt, not very much, on your food.
Camille says, “That’s the problem. I feel like I have to bribe them to do the simplest things.” “To bribe” (bribe) means to give someone money to do something that he or she should do anyway. So, for example, if you need to get something from the government, some government officials – some people who work for the government – might ask you for some extra money to do what they should do anyway. That would be an example of having to bribe someone to do something. Camille feels like she has to bribe her children “to do the simplest things.”
She says, “I get home from work and I’m tired and frazzled.” “To be frazzled” (frazzled) means to be very tired, to be worn out, to not be able to think clearly about something. Camille says, “I don’t want another power struggle, so I rely on bribes.” A “struggle” (struggle) is a conflict, a fight. A “power struggle” is when you have two people who are trying to control a situation, two people who are trying to show that they have the power or the authority to control a certain situation.
Sometimes parents and children have a power struggle. The child wants to get what he wants, the parent wants to get what he or she wants, and that results in problems. Camille relies on bribes. She depends on bribes to get her children to do what she wants. However, she says, “It’s backfired” (backfired). “To backfire” means to have the opposite effect to what you wanted or planned – to do the opposite of what you think is supposed to happen.
So, for example, you may want your child to go to bed at eight o’clock at night. So, you tell the child, “You go to bed right now,” but instead, the child starts crying and crying and complaining, and eventually you let the child stay up for another hour. Your plan “backfired.” Instead of getting the child to go to bed eight o’clock, the child stayed up for another hour.
By the way, my mother tells me that I was never like this as a child. I was, I think her words were, “a perfect child” – an “angel,” she once told me. Well, I think that’s what she said. Anyway, Aaron says, “How do you mean?” “How do you mean?” is a question we use when we don’t understand exactly what the person is saying – when we want the person to give us more information or more details.
Camille says, “Now my kids won’t do anything without knowing what’s in it for them.” The expression “what’s in it for them” (or “for me”) means the advantage or the benefit that someone will receive because they do something. Someone may say to you, “I want you to go to the store and buy me a watch,” and you may be wondering, “Well, why would I do that?” So, you might say to the person, “Well, what’s in it for me?” In other words, what benefits do I get? That’s what Camille’s children tell her.
Camille says, “And they,” her children, “keep upping the ante.” “To up the ante” (ante) is a betting expression. It’s the amount of money that you bet, say, in poker or in other games before the game begins or at the beginning of the game. “To up the ante” means to increase it. Here it means to increase the risks or increase the rewards for some action. Camille says, “Soon, I’ll have to start forking over cash to get them to behave.” “To fork (fork) over” some amount of money means to give someone a large amount of money even if you don’t want to.
Camille is saying that she has to give her children money, or she fears she will have to give her children money, to get them to behave. Aaron says, “I don’t know what to say. When I was growing up, my mother put the fear of God into us.” This expression “to put the fear (fear) of God” into someone or in someone means to frighten someone, to make someone scared so that the person will do what you want him or her to do. That was certainly true with my father.
Aaron says, “We wouldn’t dare misbehave for fear of making her angry.” “Dare” (dare) means to do something that is very difficult or challenging – that is not “socially acceptable,” we might say. If you say you wouldn’t dare do something, you mean that you wouldn’t do it under any circumstances. In this case, Aaron is talking about not daring to misbehave, to act badly, for fear of making his mother angry. The expression “for fear of” means because one is afraid of.
Aaron says, “We never got rewards for good behavior. It was just expected of us.” Camille then asks Aaron, “What’s your mother’s number,” meaning her telephone number. “Is she available to babysit?” “To babysit” (babysit) means to take care of someone else’s child, usually for money. Aaron says, “Uh, I don’t know. I don’t think she could inspire that kind of obedience from other people’s children.”
Aaron is saying that his mother probably can’t help Camille because she probably could not “inspire that kind of obedience.” “To inspire” (inspire) means to create a certain feeling, want, or desire in another person. Aaron is saying he doesn’t think his mother would be able to make Camille’s children obedient. “Obedient” comes from the word “obedience” (obedience), which means an agreement to do what someone tells you to do – to follow someone else’s orders.
Camille says, “I’m desperate!” (desperate). “To be desperate” means to want something very badly, thinking that you don’t have any other choices, any other options. Camille says, “At the very least, she can give me a few parenting lessons.” Camille is asking to speak with Aaron’s mother so that “at the very least,” meaning at minimum, Aaron’s mother can give her some parenting lessons. “Parenting” (parenting) refers to the act of bringing up or raising children, how you treat your children, what sort of things you say and do with your children. That is part of parenting.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Camille: No, you can’t have a new bike if you get an A on the test. You should study because you want to do well in school. We’ll talk about it when I get home tonight. Kids!
Aaron: What’s the matter?
Camille: My kids won’t do anything without an incentive. I know it’s my own fault for offering rewards for good behavior, but now all they want to know is what they’ll get to do what I ask.
Aaron: Rewards are okay if you use them sparingly, aren’t they?
Camille: That’s the problem. I feel like I have to bribe them to do the simplest things. I get home from work and I’m tired and frazzled. I don’t want another power struggle, so I rely on bribes. It’s backfired.
Aaron: How do you mean?
Camille: Now my kids won’t do anything without knowing what’s in it for them. And they keep upping the ante. Soon I’ll have to start forking over cash to get them to behave.
Aaron: I don’t know what to say. When I was growing up, my mother put the fear of God into us. We wouldn’t dare misbehave for fear of making her angry. We never got rewards for good behavior. It was just expected of us.
Camille: What’s your mother’s number? Is she available to babysit?
Aaron: Uh, I don’t know. I don’t think she could inspire that kind of obedience from other people’s children.
Camille: I’m desperate! At the very least, she can give me a few parenting lessons.
[end of dialogue]
Your incentive for listening to the wonderful scripts by Dr. Lucy Tse is an improvement in your English – at least, we hope so.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
incentive – something that motivates someone to do something, especially money
* Elementary school teachers sometimes use stars as an incentive for students to behave well in class.
reward – a gift given to recognize one’s actions or behavior and thank him or her for it
* Ms. Andrews says that seeing her students succeed later in life is all the reward she requires.
sparingly – with a very small amount of something; not a lot or often
* If you use these jars of jam sparingly, they should last all winter.
to bribe – to pay someone money so that he or she will do what one wants, something that he or she would not normally do, or something that is illegal or wrong
* The contractors bribed the mayor to get the bridge construction project.
frazzled – very tired, worn out, and not able to think clearly
* The phones were ringing all day long and the receptionists were frazzled.
power struggle – an interaction between two people who are trying to control the situation and show that they have more authority and power than the other person
* The two vice-presidents are in a power struggle to become the company’s next president.
to backfire – to have the opposite effect to what was intended or planned; to do the opposite of what something was supposed to do
* Ricky quit smoking to save money on cigarettes, but his plan backfired when he started spending even more on candy and other snacks to distract himself from smoking.
what’s in it for (one) – the advantage or benefit that someone will receive as a result of doing something
* If I help you write your paper, what’s in it for me? Are you going to help me with my math homework?
to up the ante – a phrase taken from the card game of poker, meaning to increase the stakes or increase the risks associated with doing something
* The other stores are offering increasingly high discounts. Are we going to up the ante or stop trying to compete?
to fork over – to pay a large amount of money for something when one really doesn’t want to
* Who would fork over that much money for such a small apartment?
to put the fear of God in (someone) – to make someone feel afraid of one’s power while also respecting and admiring that person; to frighten someone
* Being in the center of that tornado really put the fear of God in us.
to dare – to do something that is very difficult or challenging, that is not socially acceptable, or that risks disapproval
* When they were teenagers, they dared their classmates to steal small items from stores.
for fear of – because one is afraid of
* Helena never eats sushi for fear of getting sick from eating raw fish.
to babysit – to take care of someone’s child as a way to make money
* Yetti was 14 years old when she started babysitting the neighbor’s children.
to inspire – to create a feeling or desire in another person
* The CEO’s speech inspired employees to work harder toward his vision for the company.
obedience – compliance with orders; agreement to follow other’s rules and recognize another’s authority
* In the past, American men demanded obedience from their wives, but now, most men view marriage as a partnership.
desperate – wanting and needing something very badly, without any other options
* We haven’t been profitable for the past eight months, so we’re desperate for some new customers!
parenting – the act of raising one’s children
* Parents often say that parenting is one of the most challenging things they’ve ever done, but that it is one of the most rewarding.
Comprehension Questions
1. What does Camille mean when she says, “Soon I’ll have to start forking over cash”?
a) Soon she’ll have to start eating money.
b) Soon she’ll have to start looking for a better-paying job.
c) Soon she’ll have to start paying large amounts of money.
2. What does Aaron mean when he says, “My mother put the fear of God into us”?
a) His mother raised them to be religious people.
b) His mother told them God would punish them if they didn’t behave.
c) His mother commanded their respect and fear so they wouldn’t misbehave.
Answers at bottom.
What Else Does It Mean?
reward
The word “reward,” in this podcast, means a gift given to recognize one’s actions or behavior and thank him or her for it: “The top salesperson will receive a one-week vacation in Mexico as a reward.” The phrase “to reap the rewards” means to get and enjoy the benefits or advantages resulting from something: “We worked hard to plant the garden in the spring, so that we’ll be able to reap the rewards of fresh fruits and vegetables in the late summer and fall.” Finally, the word “reward” can also mean money paid to thank someone for helping to solve a crime or find something that was lost: “The police are offering a reward to anyone who can provide information about the robbery.” Or, “The neighbors are offering a $100 reward to anyone who finds their missing dog.”
dare
In this podcast, the verb “to dare” means to do something that is very difficult or challenging, that is not socially acceptable, or that risks disapproval: “I dare you to kiss the next girl you see.” The phrase “how dare you” shows shock and anger related to someone’s word or actions: “How dare you steal money from my wallet!” The phrase “don’t you dare” is used to warn someone not to do something, because it will make one very angry: “Don’t you dare disobey me when I tell you to do something!” Finally, in the game “truth or dare,” people take turns deciding whether they will truthfully answer another person’s question or accept the dare or challenge and do what they’ve been dared to do.
Culture Note
Sharenting
Parents are “proud” (with feelings of pleasure and satisfaction related to something one has worked hard to do or create) of their children and often want to tell everyone about their children. In the past, people at work might show a photograph or their child or “boast” (talk about how good something is) to a neighbor about how their child is doing at school.
But things have changed with the “rise” (increasing use) of the Internet and “social media” (websites that allow people to connect and share information, such as Facebook, Instagram, and Twitter). Parents are able to tell more people than ever before about “little Johnny’s” (a generic name for a young boy) “accomplishments” (the things that one has done through hard work).
When parents “overshare” (share too much information), some people say they are “sharenting” (a “mash-up” (combination of two words) of “sharing” and “parenting”). Parents who “are guilty of” (have done something they shouldn’t have) sharenting share stories, pictures, and more about their children. Sometimes they share things that nobody else even wants to know about.
Some people argue that sharenting is a “violation” (an instance of breaking a rule or law) of a child’s “right to privacy” (the ability to keep one’s information private and not share it). They note that the sharenting activities create a “digital footprint” (all the information that is available about someone on the Internet) about children before they can even type or use a computer.
Comprehension Answers
1 - c
2 - c