= 1088
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,088 – Selling a Business.
This is English as a Second Language Podcast episode 1,088. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at ESLPod.com. Take a look at our ESL Podcast Store with additional courses in Business and Daily English – courses you can download immediately, right in the comfort of your own home.
In this episode, we have a dialogue between Andy and Robin about selling a business. Let’s get started.
[start of dialogue]
Andy: I can’t believe you’re really selling up. I thought you’d stick it out for another year.
Robin: Business has been slow for three years running and I can’t count on things to pick up anytime soon. I’m selling this business now before it’s completely worthless.
Andy: You should get a good price with all that equipment and inventory.
Robin: I’m hoping that my valuation is in line with what buyers want to pay. I plan to sweeten the pot by offering my consulting services as part of the deal. I’ll introduce the new owners to my suppliers and clients, go over the books with them, and help them set up daily operations.
Andy: That should give them a jump-start. With all that knowledge, you could start a new business on the other side of town and hope that business is better there.
Robin: I couldn’t do that. The sales contract has a non-compete clause. That’s only fair.
Andy: I guess. What are you going to do now?
Robin: I’m not sure yet. With the proceeds of the sale, I might try my hand at something entirely different.
Andy: How different?
Robin: I’ve always wanted to own an ice cream shop.
Andy: An ice cream shop in Alaska? You might want to rethink that business plan.
[end of dialogue]
Andy begins our dialogue by saying to Robin, “I can’t believe you’re really selling up.” “To sell up” is a two-word phrasal verb meaning to sell most of what you own with the plan of moving to another city or another place. Usually we use this phrasal verb in talking about a business that is selling its assets – what it owns – in order to move to a new place or perhaps simply to go out of business.
Andy says, “I thought you’d stick it out for another year.” The expression “to stick (stick) it out (out)” means to continue doing something even though it is very difficult, even though there are a lot of challenges and problems. “To stick it out” means to persist to continue working on something or doing something, even when it is difficult.
Robin says, “Business has been slow for three years running.” When we say “business has been slow,” we mean that we haven’t been making very much money. The business is not doing very well. Now, oddly enough, if the business is doing well, we don’t say, “Business has been running fast.” We only say, “Business has been running slow,” if the business has been unsuccessful. If a business is successful, we’d probably say something like, “It’s been going great.”
Robin says that “business has been slow for three years running,” meaning three years in a row – consecutively, one after the other. She says, “I can’t count on things to pick up anytime soon.” “To count on” something means to depend on something, to rely on something. “To pick up” here as a phrasal verb means to increase in speed or pace. In this case, it means to be making more money. If business is picking up, you’re getting more business.
Robin says, “I’m selling this business now before it’s completely worthless.” If something is “worthless” (worthless), it means it has no value. It is not worth any money. Andy says, “You should get a good price with all that equipment and inventory.” Andy says Robin should get a good price, meaning that she’ll get a lot of money for her business. She has “equipment and inventory” (inventory). “Inventory” refers to all of the things – the goods, the products – that a company has made or owns but hasn’t sold yet.
So if you sell, I don’t know, T-shirts, and you have a hundred T-shirts in your house that you are selling – let’s say online – your inventory of T-shirts is 100. You have 100 T-shirts in your inventory. Usually we use the word “inventory” only for physical products, not for services or digital products like downloads, for example.
Robin says, “I’m hoping that my valuation is in line with what buyers want to pay.” The “valuation” (valuation) of something is how much something is worth. If you are going to sell your business, usually you have to have someone evaluate it, tell you how much it is worth. That would give you a “valuation.”
The expression “in line (line) with” means similar to or in accordance with ?– not significantly different than. It’s used when we’re comparing two different concepts. In this case, we’re comparing the valuation – what Robin thinks or what an expert thinks her business is worth – and what buyers want to pay for the business. We want the valuation to be “in line with,” or at about the same amount as, what buyers want to pay.
She says, “I plan to sweeten the pot by offering my consulting services as part of the deal.” “To sweeten (sweeten) the pot (pot)” means to make something more attractive to buyers, especially by adding something free. So, for example, when you go to buy a new car, the salesman or saleswoman might say, “Well, if you buy the car today, I’ll give you the air-conditioning system for free,” or “I’ll give you a new CD player.” The salesperson is trying to sweeten the pot – trying to make the deal more enticing, more interesting to you so that you will go ahead and buy it.
Robin wants to sweeten the pot in selling her business by offering her consulting services. “Consulting” (consulting) here means giving advice, giving help to someone, especially another business. When you have a “consultant” – a person who consults – that person gives you help or advice with your business. Robin says, “I’ll introduce the new owners to my suppliers and clients, go over the books with them, and help them set up daily operations.” A business’s “suppliers” (suppliers) are the companies and people that the business buys things from.
So, if you’re a restaurant, your suppliers would include people who sell you food that you then prepare to sell in your restaurant. “To go over the books” (books) means to review the accounting records and financial statements for a business. “The books” refers to the accounting system or accounting information that used to be kept in a single book. Nowadays, of course, it’s in a computer program for most businesses. Robin is going to introduce the new owners to her suppliers and clients – that is, customers – go over the books with them, and help them set up or establish daily operations.
Andy says, “That should give them a jump-start.” A “jump-start” is an early beginning, an opportunity to start something more quickly than you might otherwise be able to do. Andy says, “With all that knowledge, you could start a new business on the other side of town and hope that business is better there.” But Robin says, “I couldn’t do that,” meaning she couldn’t start up a similar business in another part of the same city.
She says, “The sales contract,” the agreement to sell the business, “has a non-compete clause.” A “clause” (clause) in a contract is a section or part of a contract or agreement. “To compete” (compete) means to go up against someone for the same clients or the same customers. If you have a “non-compete clause,” that’s an agreement where you say you will not start a similar business or try to take business away from the person you are selling your business to.
So, if I own a donut shop, and I sell the donut shop to someone with a non-compete clause in the contract, I am agreeing not to open up another donut shop a mile away that would then take business away from the original donut shop. (That’s making me hungry, talking about donuts, frankly.) Robin says, “That’s only fair,” meaning that would be the fair and just way to do it. Andy says, “I guess,” meaning okay, I agree. “What are you going to do now?”
Robin says, “I’m not sure yet. With the proceeds of the sale, I might try my hand at something entirely different.” The “proceeds (proceeds) of a sale” are the profits, the money that you get from selling something. If you sell your car for a thousand dollars, the proceeds of the sale are a thousand dollars. “To try your hand (hand) at” something means to attempt to do something for the first time, not knowing whether you will be successful or not. If you have never played tennis and you say, “I’m going to try my hand at tennis,” you mean you are going to play tennis for the first time.
Robin wants to try her hand at something entirely or completely different. Andy says, “How different?” Robin says, “I’ve always wanted to own an ice cream shop” – that is, a store that sells ice cream. Andy says, “An ice cream shop in Alaska? You might want to rethink that business plan.”
So, we learn that Robin is going to be living in Alaska, which of course is a very cold state in the United States. And it’s not a place where you would expect a lot of people to be wanting to buy ice cream, since ice cream is usually more popular in hot places. That’s why Andy says he thinks that Robin should “rethink,” or think about again, her business plan. Your “business plan” is your written document including the plans that you have for starting a new business or opening a new business.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Andy: I can’t believe you’re really selling up. I thought you’d stick it out for another year.
Robin: Business has been slow for three years running and I can’t count on things to pick up anytime soon. I’m selling this business now before it’s completely worthless.
Andy: You should get a good price with all that equipment and inventory.
Robin: I’m hoping that my valuation is in line with what buyers want to pay. I plan to sweeten the pot by offering my consulting services as part of the deal. I’ll introduce the new owners to my suppliers and clients, go over the books with them, and help them set up daily operations.
Andy: That should give them a jump-start. With all that knowledge, you could start a new business on the other side of town and hope that business is better there.
Robin: I couldn’t do that. The sales contract has a non-compete clause. That’s only fair.
Andy: I guess. What are you going to do now?
Robin: I’m not sure yet. With the proceeds of the sale, I might try my hand at something entirely different.
Andy: How different?
Robin: I’ve always wanted to own an ice cream shop.
Andy: An ice cream shop in Alaska? You might want to rethink that business plan.
[end of dialogue]
Our dialogues, written by our wonderful scriptwriter, are the opposite of worthless. They’re very valuable in helping you improve your English. So, thank you to our scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to sell up – to sell most of what one owns, especially a business, often because one wants to move and/or do something else
* Why did Trenton sell up and move across the country?
to stick it out – to continue doing something even though it is very difficult or challenging and there are many obstacles
* Every marriage has hard times, but stick it out and things may get better.
running – consecutively; in a row, without any gaps or pauses
* The right lane of the freeway has been closed for three days running due to a construction project.
to count on – to depend on; to rely on
* We can count on two things in life: death and taxes.
to pick up – to increase the speed or pace of something, especially for sales and profitability to increase
* Toy stores expect sales to pick up in the weeks before Christmas.
worthless – with no value; not worth any money
* All these old, empty boxes and broken dishes are worthless. Let’s throw them away.
inventory – all the goods or products that a company owns but has not yet sold
* At first, they kept their inventory in the garage, but as their business grew, they had to start using a warehouse.
valuation – how much something is worth, especially how much a business is worth; the amount of money that one believes something can be sold for
* We can calculate the company’s valuation based on the price of its shares.
in line with – in accordance with; in alignment with; similar to; not significantly larger or smaller than
* The senator voted in line with his political party.
to sweeten the pot – to make something more attractive to buyers, especially by adding something for free
* This knife set is $150, but to sweeten the pot, we’re offering this beautiful cutting board at no additional cost.
consulting – the business and practice of giving business advice or useful services to other people
* Sheila just signed a consulting contract to help a local company improve its accounting system.
supplier – a vendor; a company that provides goods or services to another company, which uses them for its own manufacturing or product development
* If the suppliers continue to charge this much, we’ll have to raise the price of our products.
to go over the books – to review the accounting records and financial statements; to examine financial transactions to better understand the financial health of a business
* When we were going over the books, we became alarmed by the amount of money being spent on meals with clients.
jump-start – a head start; an early beginning; an opportunity to start something before other people do, or to begin more quickly than other people do
* Amelia’s parents taught her all her letters and numbers at home to give her a jump-start in preschool.
non-compete clause – part of a contract that states that a person will not create a similar business that tries to reach the same customers with a similar product or service
* We bought Mikhail’s doughnut store, and then just one month later, he opened another doughnut store across the street! I wish we had a non-compete clause, but we didn’t think of it at the time.
proceeds – profits; revenues; money received from the sale of something
* The company donates 3% of the proceeds each year to charitable organizations.
to try (one’s) hand at – to attempt to do something for the first time, not knowing whether one will be successful
* Have you ever tried your hand at woodworking? I think you’d be good at it.
business plan – a written document that describes one’s plans for opening a business
* The business plan should describe the company’s products and services, identify the target market, and project sales, expenses, and profitability for the first few years.
Comprehension Questions
1. Why is Robin selling his business?
a) Because it isn’t growing quickly enough.
b) Because there is too much competition.
c) Because he’s bored with it.
2. What will Robin do when he goes over the books with the buyer?
a) He’ll give the buyer all the instruction manuals.
b) He’ll review the company’s financial records with the buyer.
c) He’ll take the buyer to the library.
Answers at bottom.
What Else Does It Mean?
to sell up
The phrase “to sell up,” in this podcast, means to sell most of what one owns, especially a business, often because one wants to move and/or do something else: “Let’s sell up and use the money to retire on a warm, tropical island.” The phrase “to sell out” means to no longer have an item available for sale, because everything has been sold: “As the storm approached, the grocery stores sold out of bottled water and batteries.” The phrase “to sell out” can also mean to agree to do something that one does not agree with in order to receive money: “Justin always advocated for small, local businesses until he sold out and went to work for a multinational corporation that could pay him a better salary.”
to try (one’s) hand at
In this podcast, the phrase “to try (one’s) hand at” means to attempt to do something for the first time, not knowing whether one will be successful: “Have you ever tried your hand at playing poker?” The phrase “to lend a hand” means to help someone: “Could you lend a hand with these dirty dishes, please?” The phrase “to get out of hand” means to get out of control: “This party is getting out of hand. Maybe we should tell everybody to leave.” The phrase “to have a hand in (something)” means to participate or to be involved in something: “Did you have a hand in planning Waseem’s surprise party?” Finally, the phrase “hands down” means easily or clearly: “Hands down, that was the best meal I’ve ever had.”
Culture Note
Business Valuation
Business valuation “comes into play” (becomes relevant; is needed or necessary) whenever someone needs to know the “market value” (how much someone will pay for something) of a business. Obviously, business valuation is important when someone wants to sell a business. A careful “financial appraisal” (the process of determining how much something is worth) can help the seller “set” (establish; create) an “reasonable” (not too high or low) price and attract the right buyers. And buyers must also conduct a careful valuation to “assure” (make sure something is true) themselves that they are not paying too much for a new “acquisition” (something that one is buying, especially a business).
But there are other situations in which valuation is needed. For example, when a business is a “partnership” (a business with several owners) and one or more partners want to sell their “stake” (partial ownership) in the company, a valuation is needed to determine how much that partner or those partners should be paid.
When there are “disputes” (disagreements) about “estate taxes” (taxes that are collected when someone dies), an “objective” (not directly involved, so able to provide a fair assessment) “party” (person or business) must conduct a valuation.
For example, in the case of “divorce” (the official, legal end of a marriage when the two people are no longer married to each other) where one of the spouses (husband or wife) is a business owner, a valuation might be needed to determine and “equitable” (fair) “distribution” (giving something to more than one person) of “assets” (things that have value and can be sold for money) between the two spouses.
Comprehension Answers
1 - a
2 - b