= 1095
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,095 – Childhood Fitness.
This is English as a Second Language Podcast episode 1,095. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast. When you do, you can download a Learning Guide for this episode. Also, take a look at our ESL Podcast Store with additional courses in Daily and Business English.
This episode is a dialogue between a mother and her son about keeping fit – about being healthy and having a healthy body. Let’s get started.
[start of dialogue]
Mom: Hold it right there. Put that candy bar down.
Justin: Mom, I just wanted a snack to tide me over.
Mom: Don’t you remember what Dad said about this family’s need to improve our level of fitness?
Justin: Only old people have to worry about getting fat.
Mom: It’s not just about getting fat.
Justin: But I’m just a kid. I’m in great shape.
Mom: Childhood obesity is a huge problem in this country. Even if you’re not overweight, people your age lead sedentary lives.
Justin: Whatever that means.
Mom: It means that you sit around all day as couch potatoes watching TV and playing video games. In my day, kids went outside to ride their bikes, climb trees, and run around.
Justin: I don’t have that kind of energy.
Mom: Precisely! You and your brothers are lethargic because you don’t get enough exercise.
Justin: But exercise is tiring.
Mom: That’s because you’re not fit. You have no stamina or endurance.
Justin: I don’t need endurance.
Mom: Stop grumbling. It’s Saturday and you boys should be outside getting some fresh air.
Justin: In Los Angeles?
Mom: Are you smart mouthing me, young man? Get outside or you’ll all be helping me clean the house.
Justin: We’re out of here!
[end of dialogue]
Our dialogue begins with the mother saying to the son, whose name is Justin, “Hold it right there.” “Hold it right there” is a phrase we use when we want someone to stop doing what he or she is doing. Usually it’s a phrase used by someone in authority, such as a parent, or perhaps a police officer. If the police officer says to you, “Hold it right there,” he or she means you should stop doing what you’re doing and don’t move. Mom is telling Justin to hold it right there – to stop what he is doing.
She tells him, “Put that candy bar down.” “To put something down” is a two-word phrasal verb meaning to take it and put it on a table or on the floor – to remove it from your hand. A “candy bar” is, of course, a kind of sweet that is popular with children. Justin says, “Mom, I just wanted a snack to tide me over.” A “snack” (snack) is a small piece of food in between your main meals. “To tide (tide) someone over” is a phrasal verb meaning to give someone enough resources – energy, money, food – in order to survive or last until some future point at which they will get more money, energy, or food.
If you say to someone, “I need twenty dollars to tide me over until the end of the week when I get paid at my job,” you are asking the person for money that you can use until some point in the future – in this case, until the end of the week, when you will get more money.
Mom, however, says to Justin, “Don’t you remember what dad said about this family’s need to improve our level of fitness?” The mother is reminding Justin of something that his father said about the entire family needing to improve their “level of fitness” (fitness). “Fitness” refers to your physical health – whether you can walk up the stairs without running out of breath, for example. “Fitness” refers to the physical health, the bodily health of a person.
Justin says, “Only old people have to worry about getting fat.” Justin associates fitness with whether you are fat (whether you weigh too much) or thin (whether you don’t weigh a lot). Mom says, “It’s not just about getting fat.” In other words, fitness is not just related to how much you weigh. Justin says, “But I’m a kid” – that is, I’m a child. “I’m in great shape.” “Shape” (shape) here refers to your physical condition, your physical fitness.
If you’re in good shape, or as Justin describes himself, “great shape,” you are very physically fit, you are very healthy. Your body is “in good condition,” we might say. If you are in “bad shape,” your body is not in good condition. We can describe physical objects as being in good shape or bad shape as well. When we do that, we’re not referring, of course, to the health of the object, but rather to whether the object is in good condition or in poor condition.
Mom, however, says that “childhood obesity is a huge problem in this country.” “Obesity” (obesity) relates to the condition of being seriously overweight – not just being a little heavier, weighing a little more than you should, but weighing a lot more than you should, such that it affects your health. It could actually kill you or make you have a lot of physical problems. It’s sort of strange because Mom just finished saying that fitness is not about getting fat, and then she goes on to talk about getting fat (“childhood obesity” – that is, children being overweight.)
“Even if you’re not overweight,” Mom says, “people your age lead sedentary lives.” “Sedentary” (sedentary) here means not moving very much, sitting around. When someone says they live a “sedentary life,” he means he doesn’t do a lot of exercise. He watches a lot of television, perhaps. He sits in his chair and reads or surfs the Internet, but he’s not out doing physical activity. Mom is saying that children nowadays lead sedentary lives. They don’t go out and move and are not as physically active as perhaps they once were.
Justin, however, says, “Whatever that means.” In other words, Justin doesn’t understand what his mother just said. He doesn’t perhaps understand the word “sedentary.” Mom explains, “It means that you sit around all day as couch potatoes watching TV and playing video games.” The term “couch” (couch) refers to a sofa, something that you sit on – a chair for two or more people, we could also describe it as being. A “potato” is a kind of vegetable, a white vegetable – at least, when you cut it open, it’s white. A “couch potato,” however, is a term referring to someone who’s lazy, who doesn’t move around very much.
Mom explains, “In my day, kids went outside to ride their bikes, climb trees, and run around.” Mom is comparing the situation when she was a child to today’s situation where children don’t go around climbing trees and running around, at least not in this dialogue. Justin says, “I don’t have that kind of energy.” “Energy” (energy) here means strength. “To have the energy” to do something is to have the physical strength or the physical ability to do something. Justin says he doesn’t have energy to do the things his mother is talking about.
Mom responds, “Precisely” (precisely). The term “precisely” here means exactly. “That’s exactly what I’m saying,” Mom is indicating with this term “precisely.” “You and your brothers are lethargic because you don’t get enough exercise.” “To be lethargic” (lethargic) means to not have a lot of energy, to not move around, perhaps to be lazy. Mom says that her children are lethargic because they don’t get enough “exercise” (exercise).
The term “exercise” here refers to physical activity. Going out and playing a game or running or riding a bicycle – all of these are forms of exercise, physical activity that’s good for your body. Mom says, “That’s because you’re not fit.” “To be fit” (fit) means to be in good shape. Mom says, “You have no stamina or endurance.” “Stamina” (stamina) is the ability to do something that is challenging, that requires a lot of energy, for a long time. If you run a marathon, a long race, you need a lot of stamina. You need a lot of energy, a lot of strength, to complete the marathon.
“Endurance” (endurance) is the ability to do something that is very challenging although it doesn’t necessarily have to be something physically challenging. When we talk about “stamina,” we’re usually talking about your physical energy or strength. “Endurance” could relate to that also, could refer to that also, but it may also be used in a wider context to refer to your ability and what we might call “willpower” – not to give up when the situation is difficult. Justin says, “I don’t need endurance.”
Mom, however, responds, “Stop grumbling.” “To grumble” (grumble) means to complain, usually in a low, soft, or quiet voice. If your wife tells you to do the dishes, and you respond by saying, “Alright, I’ll do the dishes . . .” you’re not happy, you’re complaining, but you’re not complaining very loudly – at least, I don’t when my wife tells me to do the dishes. Mom says, “It’s Saturday and you boys should be outside getting some fresh air.”
Justin says, “In Los Angeles?” He’s making fun of his mother in a way. He’s saying that Los Angeles – because it so polluted, because the air is not very clean – is not a good place to get fresh air. The mother, however, is not happy with Justin. She says, “Are you smart mouthing me, young man?” “To smart (smart) mouth (mouth)” someone is to speak to someone disrespectfully, especially someone in authority, such as your mother or your boss. Usually it’s a term we use when children are talking back to their parents in a disrespectful way, trying to be funny when they shouldn’t be.
Mom says, “Get outside or you’ll all be helping me clean the house.” So, Mom is telling Justin that if he doesn’t go outside right now, he and his brothers are going to be helping her clean inside the house. Justin responds, “We’re out of here.” The expression “to be out (out) of here” means that we are leaving right now. It’s often used when you’re in an unpleasant or uncomfortable situation that you want to leave right away. It’s an informal expression.
You might, for example, be having an argument with your girlfriend, and your girlfriend says something or demands something of you and you don’t want to do it. You might say, “I’m out of here,” meaning I’m leaving. However, it’s a very serious thing to say in that situation. You might be saying, “I want to break up with you,” or you might be saying that you want to end the relationship. It normally is less serious than that, however. It normally means that you are leaving.
Sometimes it could mean simply that you are going to leave without any sense that the current situation is a bad one. Someone may end a meeting by saying, “Okay, well, I have another appointment, so I’m out of here” – I’m leaving here right now.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Mom: Hold it right there. Put that candy bar down.
Justin: Mom, I just wanted a snack to tide me over.
Mom: Don’t you remember what Dad said about this family’s need to improve our level of fitness?
Justin: Only old people have to worry about getting fat.
Mom: It’s not just about getting fat.
Justin: But I’m just a kid. I’m in great shape.
Mom: Childhood obesity is a huge problem in this country. Even if you’re not overweight, people your age lead sedentary lives.
Justin: Whatever that means.
Mom: It means that you sit around all day as couch potatoes watching TV and playing video games. In my day, kids went outside to ride their bikes, climb trees, and run around.
Justin: I don’t have that kind of energy.
Mom: Precisely! You and your brothers are lethargic because you don’t get enough exercise.
Justin: But exercise is tiring.
Mom: That’s because you’re not fit. You have no stamina or endurance.
Justin: I don’t need endurance.
Mom: Stop grumbling. It’s Saturday and you boys should be outside getting some fresh air.
Justin: In Los Angeles?
Mom: Are you smart mouthing me, young man? Get outside or you’ll all be helping me clean the house.
Justin: We’re out of here!
[end of dialogue]
It takes a lot of energy and endurance to write scripts every week the way our wonderful scriptwriter does. So thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. I’m out of here, but come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
hold it right there – an phrase used to tell someone to stop what he or she is doing immediately
* Hold it right there. Your shoes are muddy! Take them off before you come inside.
to tide (one) over – to satisfy someone temporarily; to meet one’s immediate needs until a more filling or thorough solution can be found
* We need to find someone who can lend us $300 to tide us over until payday.
fitness – a measure of how healthy one is, especially one’s ability to perform physically without getting too tired
* Stretching, weight-lifting, and cardiovascular exercise are all important for achieving good fitness.
shape – a measure of one’s well-being and physical health and performance
* Heidi made a New Year’s resolution to get into better shape by exercising more and eating fewer desserts.
obesity – the condition weighing much more than one should; the condition of having an unhealthy weight that is far too heavy
* Obesity is more common in communities where people depend on cars for transportation, because they aren’t getting enough exercise from walking.
sedentary – spending too much time lying down or seated, with little or no physical activity
* Office jobs tend to promote a sedentary lifestyle, because the employees are expected to sit at their desk for eight hours each day.
couch potato – a person who spends too much time sitting on a couch while watching TV and eating
* Once Hal retired, he became a couch potato because he didn’t know what else to do with so much free time.
energy – the strength, ability, and enthusiasm to do something without becoming too tired
* Raising kids takes so much energy. I’m exhausted after running after my two-year-old all day!
precisely – exactly; a phrase use to show one’s agreement with what another person has said
* Yes, college is expensive. That’s precisely why we started saving money so early.
lethargic – very tired, slow-moving, and uninterested
* Vic feels really lethargic in the morning before he’s had his first cup of coffee.
exercise – physical activity done primarily to improve one’s health and fitness, often at a gym
* Running on a treadmill is good exercise, but it’s much more fun and interesting to play sports outdoors.
fit – in good shape; healthy and with a high level of fitness; with a healthy body and the ability to do what one wants physically without becoming too tired
* Chelsea was always slender and fit, but after she had her baby, she stopped going to the gym and she started gaining weight.
stamina – the ability to do something that is challenging for a long period of time;
* The doctors fear that Deedra won’t have the physical stamina to survive three surgeries over such a short period of time.
endurance – the ability to continue to do something even though it is very challenging; the ability and willpower to not give up
* Ultra-marathons really test runners’ endurance, asking them to run 50-100 miles or even more.
to grumble – to complain, usually in a low, quiet voice
* Those old men spend all day at the park, grumbling about high taxes and the way teenagers behave.
to smart mouth – to backtalk; to speak disrespectfully to someone, especially with humorous but rude responses to what another person has said
* Students who smart mouth the teacher will be sent to the principal’s office for punishment.
out of here – gone; away; leaving a place, especially because one does not want to be there because it is unpleasant in some way
* Let’s get out of here before the storm arrives.
Comprehension Questions
1. What does she mean when she says, “Hold it right there”?
a) She wants him to stop what he is doing.
b) She wants him to hold the candy bar up in the air.
c) She wants him to pay for what he took.
2. Why does she say that people are leading sedentary lives?
a) Because they spend most of their time sitting down.
b) Because they are eating very bad foods.
c) Because they don’t know how to stick to a budget.
Answers at bottom.
What Else Does It Mean?
shape
The word “shape,” in this podcast, is a measure of one’s well-being and physical health and performance: “At the end of the season, those soccer players were in the best shape of their life.” The phrase “to whip/kick/get (someone) into shape” means to make someone do something much better: “These new employees need someone to whip them into shape before their 90-day performance evaluation.” The phrase “in no shape to do (something)” means physically and/or mentally unprepared and unqualified to do something: “After working an 80-hour week, Herbert was in no shape to drive up to Houston by himself.” Finally, the phrase “to take shape” means to become clearer and more defined: “Their wedding plans are finally starting to take shape.”
to smart mouth
In this podcast, the phrase “to smart mouth” means to backtalk, or to speak disrespectfully to someone, especially with humorous but rude responses to what another person has said: “If I had smart mouthed my mother that way, she would have grounded me for weeks!” A “smart alec” is someone who always has a quick and clever, but annoying response to what other people say: “Randall is a smart alec who always tries to appear clever by making biting comments.” The phrase “the smart money is one (someone)” means that that person is likely to win or succeed: “The smart money is on Amir. I’ve never seen anyone work as hard as he does.” Finally, the phrase “street-smart” describes someone who has a lot of common sense and knows how to survive in a big city: “Shane became street-smart when he was a homeless teenager in New York.”
Culture Note
Physical Education in Schools
Physical Education, or “PE” classes, are common in U.S. schools, although they are “increasingly” (more and more often) being shortened and “cut” (removed from the curriculum) to “free up” (make available) more time for academics. A typical PE class is designed to “get children moving” (make people get exercise) for 45 or 60 minutes per day, but the activities “vary” (are different).
A “hard-core” (very serious and challenging) PE class might start by having the students “run laps” (run around the gym or track in circles) and then completing a certain number of “sit-ups” (an exercise in which one lies down with the knees bent and then tightens muscles in the abdomen to sit up), “chin-ups” (an exercise in which one hangs from a bar and then bends the elbows to pull one’s “chin” (the part of the body below the mouth and above the neck) over the bar), and “push-ups” (an exercise in which one lies down facing the floor and pushes the body up with one’s hands and arms).
Other PE classes are based around team sports and other games, such as soccer, basketball, baseball, tennis, or “dodge ball” (a game with two teams, with members of each team trying to hit members of the other team with a large, red ball). Some PE classes even focus on dance, playing music while the students get an “aerobic workout” (exercise that increases one’s heart rate).
Students typically “change into” (put on) shorts and a t-shirt at the beginning of PE, and take a quick shower at the end of the class.
Comprehension Answers
1 - a
2 - a