= 0283
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome to EnglishPod.
My name is Marco.
My name is Catherine and as you've noticed on our website, we have a number of lessons about giving a presentation in English.
So this is one of those lessons.
Today we're talking about avoiding questions.
That's right.
Today in part five of our presentation series, we're going to try and handle some questions or avoid questions as Catherine said.
So why don't we jump into the dialogue.
Let's see what Mr.
Ford is talking about now and we'll be back in a bit.
Now as we've already discussed, there's a huge untapped market out there, both in Asia, in other developing markets and in the more mature markets for us to push into.
Now of course this represents an enormous challenge with enormous rewards for the winners.
But for any new product, we need a great marketing message and marketing campaign.
It needs to be directed and focused at our target consumer and needs to be pitched at any time.
The question we must first address is of course, who is our target consumer and secondly, what do they expect from the next generation alpha laptop?
Let's first of all tackle the first question.
Our target consumer for the X420 is the middle class white collar worker with an above average income.
However, as we mentioned before, the total number of computer owners is expanding rapidly and we need to broaden our audience for this product.
For example, the X420 is also ideally suited to the younger student sector who might use laptops both for studying and gaming.
There's no doubt that...
Mr.
Ford, if I could just interrupt a moment.
You say that the computer is suitable for students, but you don't think the price of the X420 is just too much for most students?
Well, that's a fair point.
If you don't mind, I'd like to tackle your question a little bit later in the Q&A section.
Is that okay?
Yes, sure.
Okay, so as I was saying, we have an exciting campaign planned for the X420.
Firstly, we'll have a nationwide television campaign as well as advertising on radio and also in many computer publications.
We also intend to...
I'm sorry to stop you, Mr.
Ford, but do you really think that a television campaign is cost effective?
I mean, how much is that going to cost?
Well, I don't have the figures to hand, but I'd be happy to discuss those figures with you after the presentation.
Okay, let me just go on to talk a little more about the exciting campaign we have in store.
Alright, we're back and now we can get started with Language Takeaway.
Language Takeaway.
Language Takeaway.
Okay, so Marco, a lot of the conversation today was about markets and a target consumer.
So perhaps we should start talking a little bit about who Mr.
Ford thinks this company's consumers are.
That's right.
He mentioned that the Alpha laptop could also be aimed at the middle class.
We have different classes in society, especially in America, where we talk about people who are low income, they don't make very much money, or people who make a lot of money, they're rich, they're on top.
That's the high class.
Yeah, high class.
But in the middle, we have the middle class.
And this is just average people.
They make money, they have a car.
They're not rich, but they're not poor.
Okay, so they're in the middle.
So this is the middle class.
The computer is aimed at the middle class market, but he said that it's middle class white collar worker.
Okay, so I know this phrase exists in many other languages, but a white collar worker in English refers to the color of the shirt that you wear.
So white collar workers usually work in offices.
So because they're usually wearing suits.
That's right.
They have to wear nice clothes like suits and button down shirts.
But we sometimes also talk about blue collar workers.
Who are these guys?
Blue collar workers are usually people that are in trades, like for example, a mechanic or a plumber, because usually you see them wearing those blue shirts.
Yeah, uniforms.
They're usually people who work with their hands or who are not likely to work in a big office.
So usually maybe these people are not middle class, maybe they are lower class.
They can be both.
In America right now, I think you can make quite a bit of money if you're a plumber or a construction worker.
That's right.
But he also mentioned middle class white collar worker with an above average income.
Okay, so an income is the amount of money that a person earns, usually in a year.
So we say $30,000 a year.
That's your annual income.
That's right.
So we talk about something that's average.
That means it's normal.
But in this case, we're not talking about something that's average.
What are we talking about?
It's above average.
Above average.
So if the average income of a person in America is $36,000 a year, an above average income is $70,000 a year or $65,000 a year.
Okay.
But for the middle class, maybe that's different.
So in the middle class, an average annual income is $70,000 and above average income in the middle class is $120,000 a year.
Okay.
So the phrase there, above average, you're just referring to something that's more than the normal.
That's right.
So in this case, more than the normal income for a middle class worker, you can also say below average.
So a below average income is lower than most people earn.
Okay, very good.
And while continuing on talking about markets and the demographics, who we're selling the computer to, we also talked about our target consumer.
Oh, this is something that you often hear in meetings at work or in marketing departments.
A target is something you aim for.
It's something you want to hit or achieve.
And so a target consumer is the buyer, is a customer that you aim to have.
Okay.
So maybe you have some customers that they're students and you have some customers that they're very old.
But your target consumer, the people that you really want to reach out to, in this case, the middle class white collar worker.
That's right.
So in the case of our dialogue, our target consumer is a middle class white collar worker, for example.
Okay.
So a lot of marketing stuff here talking about the computer and what Mr.
Ford was saying.
Let's take a pause.
Let's listen to the dialogue again.
And we'll be back with some phrases on how to defer questions.
Now, as we've already discussed, there's a huge untapped market out there, both in Asia, in other developing markets, and in the more mature markets for us to push into.
Now, of course, this represents an enormous challenge with enormous rewards for the winners.
But for any new product, we need a great marketing message and marketing campaign.
It needs to be directed and focused at our target consumer and needs to be pitched at exactly the right level.
The question we must first address is, of course, who is our target consumer?
And secondly, what do they expect from the next generation alpha laptop?
Let's first of all tackle the first question.
Our target consumer for the X420 is the middle class white collar worker with an above average income.
However, as we mentioned before, the total number of computer owners is expanding rapidly and we need to broaden our audience for this product.
For example, the X420 is also ideally suited to the younger student sector who might use laptops both for studying and gaming.
There's no doubt that...
Mr.
Ford, if I could just interrupt a moment.
You say that the computer is suitable for students, but you don't think the price of the X420 is just too much for most students?
Well, that's a fair point.
If you don't mind, I'd like to tackle your question a little bit later in the Q&A section.
Is that okay?
Yes, sure.
Okay.
So as I was saying, we have an exciting campaign planned for the X420.
Firstly, we'll have a nationwide television campaign as well as advertising on radio and also in many computer publications.
We also intend to...
I'm sorry to stop you, Mr.
Ford, but do you really think that a television campaign is cost effective?
I mean, how much is that going to cost?
Well, I don't have the figures to hand, but I'd be happy to discuss those figures with you after the presentation.
Okay, let me just go on to talk a little more about the exciting campaign we have in store.
Alright, we're back.
So now let's take a look at those phrases that we mentioned on Fluency Builder.
Fluency Builder So, Margo, there was a phrase that I heard twice in today's dialogue that I think we should talk about.
The verb is to tackle.
So we heard to tackle a question.
Right.
So when Mr.
Ford says, I'll tackle that question a little bit later on, he's talking about I'll answer the question or I'll talk about that question later on.
Right, but in this word to tackle, there's something kind of physical about it because, you know, in football, we say that when someone tries to hit the ball from someone else, it's a slide tackle.
Right.
And so to tackle a question means to really jump into it and try and solve it.
And it's, you know, maybe not an easy question.
So I'm going to tackle that later.
I'm going to tackle a challenge.
Okay.
It's more than just to solve a problem or to answer a question.
So maybe you can also tackle a project, a difficult project.
That's right.
So you know what?
I'm going to give us two weeks to tackle this project because it's a very difficult one.
All right.
Very good.
And well, actually, when he was getting some questions from the audience members specifically, because he was kind of being interrupted, he was very polite about it.
And to kind of defer the question, he said, you know what, that's a fair point, but I'll tackle that question later on.
Okay.
And so this is a really great phrase.
If you want to, if you want to flatter someone, make them feel good before you tell them that you're not going to answer their question.
Or maybe you disagree with someone.
So I could say, you know, Marco, chocolate cake is the only cake in the entire world that people should eat.
Okay.
And I could say something like that's a fair point, but in my opinion, vanilla cake is better.
All right.
So see what Marco did?
He made me feel good.
He said, you know, fair point.
That's a good idea.
But I disagree.
Or but, you know, in this, in the case of today's dialogue, but we'll talk about that later.
Right.
And actually, he did another smart thing in the way that he used his language skills here.
When he was interrupted again, he said, hey, you know what, I'd be happy to answer your questions at a later time or in the Q&A session.
Okay.
So this phrase, I'd be happy to, I'd be happy to talk about that at a later time.
But right now I'm trying to explain something else.
Exactly.
So these are two really, really key phrases for trying to, in a nice way, change the topic or change the conversation.
So, yeah, I guess you can say, yeah, I'd be happy to talk about that later on, or I'll tackle that question in a little bit, or that's a fair point, but we'll talk about it later on.
Okay.
So a lot of great language there.
Why don't we take a last listen to our dialogue and review everything we've just learned.
Now, as we've already discussed, there's a huge untapped market out there, both in Asia, in other developing markets, and in the more mature markets for us to push into.
Now, of course, this represents an enormous challenge with enormous rewards for the winners.
But for any new product, we need a great marketing message and marketing campaign.
It needs to be directed and focused at our target consumer, and needs to be pitched at exactly the right level.
The question we must first address is, of course, who is our target consumer, and secondly, what do they expect from the next generation alpha laptop?
Let's first of all tackle the first question.
Our target consumer for the X420 is the middle class white collar worker with an above average income.
However, as we mentioned before, the total number of computer owners is expanding rapidly, and we need to broaden our audience for this product.
For example, the X420 is also ideally suited to the younger student sector, who might use laptops both for studying and gaming.
There's no doubt that...
Mr.
Ford, if I could just interrupt a moment.
You say that the computer is suitable for students, but you don't think the price of the X420 is just too much for most students?
Well, that's a fair point.
If you don't mind, I'd like to tackle your question a little bit later in the Q&A section.
Is that okay?
Yes, sure.
Okay.
So, as I was saying, we have an exciting campaign planned for the X420.
Firstly, we'll have a nationwide television campaign, as well as advertising on radio, and also in many computer publications.
We also intend to...
I'm sorry to stop you, Mr.
Ford, but do you really think that a television campaign is cost effective?
I mean, how much is that going to cost?
Well, I don't have the figures to hand, but I'd be happy to discuss those figures with you after the presentation.
Okay, let me just go on to talk a little more about the exciting campaign we have in store.
All right, so this was part five of our presentation series.
We're halfway done with it, and so far we've seen a lot of interesting things.
And as you notice, it's an intermediate lesson, so it is a little bit more challenging and a little bit longer than your previous lessons.
That's right.
These are longer, and some of the phrases that you've learned, these words are very difficult.
But, you know, as a reminder, some of the words repeat.
So, for example, in today's dialogue, we heard a lot about developing markets and campaigns.
But we also heard about these last week in Episode 4.
So, you know, if you're confused or you want some extra practice, I would recommend listening to some of the older lessons again just to review, because you're going to hear a lot of these words and phrases over and over again.
That's right.
And, of course, if you have any questions about this or any suggestions, you can also come to our website, EnglishPod.com, where we'll see everyone there.
That's right.
So, until next week, bye, everyone.
Bye.
. +
