= 1740
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 435.
This is English as a Second Language Podcast’s English Café episode 435. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there. Become a member of ESL Podcast and download the Learning Guide for this episode. Take a look at our ESL Podcast Store as well, and our ESL Podcast Blog. If you are listening to this on iTunes, please go to iTunes in your country and give us a rating and a little review. We'd appreciate that very much.
On this Café, we’re going to talk about our fourth president of the United States, James Madison. And, as always, we’ll answer a few of your questions. Let's get started.
Our topic on this Café is one of the more famous American presidents – our fourth president, James Madison. In addition to being one of the presidents of the then young United States, Madison was one of the “Founding Fathers.” That term, “Founding (founding) Fathers,” refers to the men who helped start the United States – who helped create what is now called the United States.
Madison was born on March 16, 1751, in the state of Virginia, in the central-eastern part of the United States. He was born in the town about 75 miles, or 120 kilometers, southeast of what was to become the country’s capital city of Washington, D.C., although Washington, D.C., didn't exist when James Madison was born. He spent a lot of time in Montpelier, Virginia.
His family was very wealthy. They had a lot of money, and they owned a plantation. A “plantation” is a large piece of land where food and plants such as coffee, sugar, and tobacco are grown. Plantations were very common in the American colonies, especially in the southern United States. They often had slaves on them that did all of the difficult work.
Madison was the oldest of eight children. He went to college at what is now called Princeton University, then called the College of New Jersey. He studied history and government, and graduated in 1771. He became interested in politics, and in 1776 he became one of the delegates, or representatives of the people, to the government of Virginia.
At the time Virginia was creating its own constitution, Madison helped make sure that there were laws protecting religious freedom and other rights in that constitution. “Religious freedom” – the idea that you didn't have to belong to the official state church, which at that time in the colonies was the Church of England – was one of Madison's favorite causes. It's something that he came back to in his work with the government several times. He really believed in that issue.
After the colonies won their independence from Great Britain, he served in the national congress, the “Continental Congress,” which was the government of the new United States from 1780 to 1783. Madison, like many people, worried that the national government of the United States that was formed immediately after the revolution was too weak. He believed that the United States needed a new set of laws, a new constitution. And in 1787, other politicians agreed with Madison, and so there was a Constitutional Convention. Madison was sent as a representative from the state of Virginia to that convention, which met in Philadelphia.
Madison’s ideas were very influential. Many of his ideas were accepted and used in the Constitution. For that reason, he is sometimes called the “Father of the Constitution,” because his ideas were so important. After the Constitutional Convention finished its work, the proposal of this new Constitution was given to the individual states – the 13 states that were part of the United States at that time. Those states had to approve the new Constitution in order for it to take effect, or be used as the new law of the country.
In order to convince other states to adopt and approve the new U.S. Constitution, Madison and two other famous politicians, Alexander Hamilton and John Jay, wrote a series of essays. An “essay” (essay) is a long explanation of some concept or idea. The concept that Madison, Hamilton, and Jay were trying to explain was that of the U.S. Constitution. They wrote 85 essays that were collectively, or together, called the “Federalist Papers.” A “federalist” (federalist) was at that time a person who believed in a very strong central government – national government – for the country.
Madison wrote 28 of the 85 Federalist paper essays. The Federalist papers’ main objective was to explain the ideas behind the Constitution. Madison and his co-authors wanted to explain the importance of having a central government instead of many local and state governments as the main power in the new country. They also explained why a central government was the best government for the United States.
They gave reasons for what became known as the system of “checks and balances” in the United States’ new Constitution. “Checks and balances” refers to a system where no one part of the government has absolute, or complete, power – that the different branches, or parts, of the government would keep the other parts of the government from getting too much power. That idea is called “checks and balances.”
The essays that formed the Federalist Papers were published in newspapers mainly in the state of New York. Madison and the other authors wanted to explain the Constitution to the people of New York so that the people of New York would vote to accept the Constitution. New York at the time was one of the largest states, so it was very important that New York approve this new Constitution. New York did approve the Constitution, as did the other states, and it became the official law of the United States.
Madison was then elected to the new national House of Representatives, one of the two parts of the U.S. Congress – the part of the government that makes laws. He was elected in 1789 as a representative from the state of Virginia. Here, he continued to work for a strong central government and also pursue his interest in religious freedom. He helped write and pass what became known as the “Bill of Rights.” “The Bill of Rights” is basically the first ten amendments, or changes, to the Constitution.
These amendments include laws about some of the most important freedoms in the American system, including the freedom to choose one's own religion, an issue you'll remember that was very important to Madison, as well as the freedom of speech – the ability to say what you want to say without interference from the government.
In 1794, James Madison, who had not married before this time, decided to get married. He married a very beautiful woman from the city of Philadelphia in Pennsylvania, a woman by the name of Dolly Payne Todd. Dolly herself was a widow. A “widow” (widow) is a woman whose husband has died. A man whose wife has died is called a “widower,” with an “er” at the end.
Dolly was a widow – a beautiful widow and a young widow. She was just 26 years old when she married Madison, who was 43 at the time. Madison and Dolly did not have any children together, although Dolly had a son by her first marriage. The marriage surprised many people because Dolly was a very popular woman, a very beautiful woman, and Madison was a very quiet man. Their marriage was very successful, and they were very happy as a couple until Madison's death in 1836.
Thomas Jefferson, another one of our founding fathers, was a good friend of Madison's. He was elected to the presidency in 1800. He chose Madison to be his secretary of state. The “secretary of state” is responsible for foreign relations relationships with other countries with the United States. Madison served as secretary of state from 1801 until 1809.
Part of his job as secretary of state was to talk to other countries, and when Madison became secretary of state, there was a war going on between France and Great Britain. As a result of this war, many American ships had been captured, or taken from the United States, by Britain and France. Madison spoke to both countries many times, asking them to leave the American ships alone. Both France and Great Britain needed ships, of course, to help fight their battles.
In 1808, Madison himself was elected president, after the second term of Thomas Jefferson. He won the election very easily. He beat his opponent, the person whom he was competing against, by a very large margin. In his first year as president, one of the things he did was to say that the United States could not trade goods or items with Great Britain. This was because Great Britain was still capturing American ships at sea.
By preventing trade with Great Britain, however, he also made a lot of people angry, especially people in the northeastern part of the United States, who had a lot of contracts with Great Britain and companies in Great Britain. Madison now said no, you can't buy or sell anything to Great Britain, and that obviously meant people were going to lose money.
In 1810, Madison changed his mind and decided that he would not continue to prevent American businesses from trading with Great Britain. He tried his best to keep America neutral in this war between the two great European powers. “To be neutral” (neutral) means not to support either side in the war. However, Great Britain, especially, continued to capture American ships. So finally, in 1812, Madison decided the United States would have to go to war with Great Britain.
Once again, people in New England, in the northeastern part of the U.S., were not very happy, because this again meant an interruption in their trade with Great Britain. However, Madison felt that it was necessary that the United States stop Great Britain from capturing American ships. The British did very well against the Americans, winning several important battles.
In 1814, the British decided to attack the new American capital, Washington, D.C. They marched into the capital. They arrived at the capital and basically burnt the city down. They destroyed the Capitol Building, where Congress met, and they also burned down the White House, where the president and his wife and family lived. In the end of 1814, however, both the United States and Great Britain decided that there was no reason to continue this war, and so they signed a treaty called the “Treaty of Ghent” in Belgium on Christmas Eve of 1814 – December 24th. This ended the war.
However, apparently no one was checking their email or their Twitter accounts or even their Facebook page, because there were many British and American soldiers who didn't know the war had ended until many months later. In fact, in January of 1815, the British attacked the city of New Orleans. This was a major battle that the British lost, and lost quite badly. It took place after the war, because the message that the war was over had not yet reached the soldiers.
New Orleans is in the south-central part of the United States, on the Gulf of Mexico, and a very long distance from Belgium where the treaty was signed. The Battle of New Orleans, however, because the Americans won it, gave a lot of people the impression that the Americans were victorious in the war.
One of the most famous generals of that war, Andrew Jackson, later became president of the United States himself. However, the war ended really more as a tie than anything else. Neither country had gained a lot in terms of the things that they wanted when they started the war. However, Madison became very popular and continued to be popular until he left the presidency in 1817. By this time, he was 68 years old.
He decided to go back to his family's plantation in Montpelier, Virginia, and become a farmer again. However, he continued to be active in public life. In 1826, he became the head of the University of Virginia, which had originally been started by Thomas Jefferson. He also became involved in politics. One of the things that Madison was against was the institution of slavery, of the owning of other human beings. He tried, as many other politicians did, to stop slavery.
He was a member of something called the “American Colonization Society.” “Colonization” is normally the word we use when one country takes over part of another country or another piece of land and sends people to live there. We talk about the British colonizing North America, and the people who lived there were called “colonists.” Well, this Colonization Society was not about taking over other countries. In fact, it was about ending slavery, and that's one of the things Madison tried to do towards the end of his life.
Madison died in June of 1836. He had been very sick for number of months with two medical problems. One was called “rheumatism.” “Rheumatism” is a pain in your muscles and joints. The other was “liver failure,” when part of your body called the “liver” stops working properly. Dolly Madison, who you remember was much younger than her husband, James, continued on for several more years. She returned to Washington, D.C., and lived there.
She herself was a quite fascinating woman. She as First Lady was the first to occupy the White House. The term “First Lady” is what we call the wife of the president. People loved her, and she used her own popularity and influence several times to help her husband and her husband's political agenda as well. She’s still remembered as one of the most popular first ladies in American history.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Urim (Urim) in South Korea. The question has to do with the definitions of three words: “function,” “reception,” and “banquet.” Let’s start with “function” (function). A “function” is any large public event. It could be something that involves an official ceremony, but in general it's used to describe any large event with a lot of people. It could be a formal event – that is, an event where you have to wear nice clothing. It's often a word you will hear in relation to business events.
A “reception” (reception) is also a large public social gathering, typically associated with some sort of celebration. For example, if you are celebrating someone getting married, the party that you have after the marriage ceremony is called the “reception,” the “wedding reception.” You could also have a reception after someone graduates from college. It's basically a big party that is celebrating some event. We also use the term “reception” when we’re talking about a large public event to welcome people. For example, at the beginning of a conference, perhaps, or a beginning of some weeklong meeting, there might be a reception party at the beginning to welcome everyone to this event.
A “banquet” (banquet) is a meal with lots of food. Not just small things like sandwiches to eat, but a real dinner with lots of food and lots of drink. A “banquet” is typically for a large group of people who are getting together perhaps to celebrate something – perhaps to honor someone or to recognize the accomplishments of someone. A “banquet” is usually held in honor of someone. When we say it is “in honor of them,” we mean it is to recognize them, to give them attention. It is because of them that we have this banquet.
Our next question comes from Rene (Rene) in an unknown country, a secret country, perhaps, one that nobody else knows about. Rene wants to know the difference between “worthy” (worthy) and “worth it.” “Worthy” is an adjective that we used to describe someone who deserves our respect or deserves our attention. “I think my brother is worthy of this award,” meaning he is deserving of it. He should get this award. He has done what is necessary to get this award. He is a worthy person.
“Worth it” is an expression used to describe something that will require some work to get, but will give you a large benefit – will give you some things that are very good or of a very high value. You might say, “It's difficult getting up every morning at six o'clock and jogging for five miles, but it's worth it for your health.” You get a lot of benefits from doing that; it is worth it. Nowadays, informally, someone might say, “It's totally worth it,” meaning it's really worth it.
The adjective “worthy” is a little formal. You won't hear it all that often in general conversation. The expression “worth it,” however, is often used, and one you can use in both formal and informal situations.
Our final question comes from Bernardo (Bernardo) in Miami, in the state of Florida here in the U.S. Bernardo wants to know the meanings of two expressions: “all of a sudden” and “out of the blue.” Both of these expressions describe a similar situation. Let's start with “all of a sudden” (sudden). Something that happens “all of a sudden” is something that happens very quickly, without you expecting or without any warning that it is going to happen. It can often be a bad thing. “All of a sudden it started raining,” or “All of a sudden, I could feel the ground moving beneath me and realized we were having an earthquake.”
“Out of the blue” (blue) also describes something that isn't expected to happen, that is very surprising. “Out of the blue” means something is happening unexpectedly, but it almost always has the additional meaning of “surprising.” Something that happens “all of a sudden” isn't necessarily a surprise. It's just unexpected. Something that happens “out of the blue” would be something that you couldn't have predicted and that surprises you a great deal – at least, that's how I would use these two expressions.
“Out of the blue” is a little less common. You'll much more likely hear “all of a sudden” to describe the idea of something happening quickly and without warning.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2014 by the Center for Educational Development.
Glossary
Constitution – the document containing the basic beliefs and laws that a state or country uses to govern itself
* The judges on the Supreme Court of the United States use the Constitution to decide what is legal and what is not.
plantation – a large piece of land where food and plants like coffee, sugar, or tobacco are grown and a large number of field workers live and work on the plantation
* The plantation included 500 acres of farmland and is used to grow cotton.
delegate – representative of the people to a government, usually state or national
* Benjamin Franklin was one of the delegates from Pennsylvania to the Continental Congress.
Federalist – a person who believes in one, central government for a country, instead of many separate governments, such as state governments
* The Federalists in government tried to make laws that made the national government was more powerful than local governments.
checks and balances – a system where no one person has all the power and more than one person must agree to make important decision
* Because of the system of checks and balances, the President of the United States, the Congress, and the Supreme Court all have equal amounts of power.
amendment – additions or changes to a formal or legal document
* After the contract was finished, Yuko added some amendments that contained additional requests from both sides.
to capture – to take as prisoner; to take and keep someone against their will
* The police captured the person who stole Johann’s wallet and put him in jail.
opponent – the person whom one competes against in a game, race, election, or other kind of competition
* The soccer team scored more goals than their opponent so they won the game.
neutral – impartial; not helping or supporting either side of a fight, argument, or negotiation, especially countries at war
* Our country wants to remain neutral if neighboring countries go to war.
colonization – when one country takes over another country or place and sends people to live there
* British colonization was worldwide, with its citizens living all over the world.
rheumatism – pain in one’s muscles and joints, the parts of the body that connect one’s bones together
* Because of his rheumatism, Amir had trouble bending his fingers and standing up or sitting down.
liver failure – when one’s liver, the organ which helps clean one’s body, stops working properly
* After many years of not eating a healthy diet, Masha developed liver failure.
function – an official ceremony, or public or social event, that a large group of people participate in
* The ballrooms in our hotel can be used for functions with up to 500 people.
reception – a occasion or social function, with food and beverages, intended as a welcome or greeting to a newly married couple or before an event, such as an art opening or performance
* Professors are invited to a reception to welcome the new university president.
banquet – a lavish (with a lot of expensive and luxurious food) public, and/or official meal, to celebrate an event or to honor of a person
* What should we serve at the banquet: lobster, steak, or salmon?
worthy – someone or something that deserves respect or attention
* Anyone willing to spend years doing volunteer work is worthy of respect.
worth it – describing something that is likely to have a good reward or result and is worth the risk, effort, or expense
* I know you’ve always been interested in medicine, but is it worth it to spend eight years in school to become a doctor?
all of a sudden – something that happens quickly or without warning
* Everyone was enjoying the soccer match when, all of a sudden, it began to rain.
out of the blue – something that isn’t expected to happen
* Robert asked Carla for a date out of the blue, without ever having shown interest in her before.
What Insiders Know
Madison Avenue
Madison Avenue is a street located on the island of Manhattan, in New York City. It’s a north-south avenue that “carries traffic” (allow cars and other vehicles to move) north. It was named after the fourth president of the United States, James Madison.
Although there are many famous buildings located on this avenue, Madison Avenue is most famous for being “associated with” (connected to) the “advertising industry” (the field of work connected with using different techniques to get people to buy products) in the United States.
In the 1920’s, Madison Avenue was the place where you could find many famous advertising “agencies” (businesses). But it was really after World War II that Madison Avenue became the center of advertising.
Madison Avenue is also “the backdrop” (setting; background) for the popular TV series Mad Men. Mad Men is a series about a “fictional” (not real) advertising agency called “Sterling Cooper Advertising Agency,” and showed how the ad agencies in the 1960’s “conducted” (did) business.
The term “Mad Men” is a nickname the advertising industry people invented and called themselves in the 1950’s. Nowadays, only a few advertising agencies are still located on Madison Avenue, but they still have some of the biggest and most important U.S. companies as “clients” (customers).