= 1709
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 404.
This is English as a Second Language Podcast episode 404. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there. Become a member. Download a Learning Guide.
On this Café, we’re going to talk about a famous American doctor by the name of Benjamin Spock, who wrote one of the most important books about childraising or child care, The Common Sense Book of Baby and Child Care. We’re also going to talk about an interesting part of southern Florida in the United States, a place called the Everglades. And as always, we’ll answer a few of your questions. Let's get started.
We begin this Café with a discussion of a man named Benjamin Spock. Benjamin Spock was an American pediatrician. A “pediatrician” (pediatrician) is a doctor who specializes in or who has a lot of special knowledge about taking care of young children. Dr. Spock was born in New Haven, Connecticut, in the northeastern part of the United States, at the very beginning of the 20th century, in 1903.
In 1946, right after the Second World War, he wrote a book called Baby and Child Care. After World War II, when the US economy finally recovered from the Great Depression of the 1930’s, many Americans decided to have larger families, and we had something called the “baby boom” (boom). The baby boom was between about 1946 and 1964, when the population of the United States increased significantly because people were having children, lots of children. I was born right at the end of the baby boom. My oldest brother was born at the beginning of the baby boom. I mentioned the baby boom because the book that Dr. Spock wrote, Baby and Child Care, became a bestseller. A “bestseller” is a book that many, many people buy. It was a very popular book.
It was later published as The Common Sense Book of Baby and Child Care. “Common sense” (sense) refers to the knowledge that most people have, but isn't taught in schools. Dr. Spock was trying to help American parents take care of their children in ways that were perhaps better than their own parents took care of them. By the middle of the 1990’s, more than 50 million copies of Spock's book had been sold, and it had been translated into almost 40 languages. Perhaps, you've seen a copy in your own language.
What made Spock's book so popular? Well, the main message of the book was that mothers know more than they think they do. The book encouraged mothers to trust their instincts. “Instincts” (instincts) are things that we know how to do or that we know that we should do without being told by other people. Now technically, human beings may not have very many instincts. I don't want to get into a biological argument. The word “instincts,” when used to describe human beings, refers to things that we naturally or normally would do, things that we would feel necessary to do. For example, if someone starts hitting you, your first instinct, the first thing you do, is try to protect yourself. Dr. Spock was telling American mothers, since mothers are the ones that usually take care of the young babies, to “trust their instincts.”
“To trust” means to say, “Yes, what my instincts are telling me are correct.” Dr. Spock argued that mothers should trust their instincts, saying that they know how to raise their children just by the fact that they are mothers. They are women who have given birth. The book begins, “Trust yourself. You know more than you think you do.” This is of course sort of funny because, if I know more than I think I do and I know all I need to know, then why am I buying your book? But, I guess, no one really thought of that. Some people thought that Dr. Spock's book gave them the confidence to raise their children by trusting themselves and that's probably a good thing.
Before Dr. Spock's book was published, most books on childcare recommended that parents keep their babies on strict schedules, with very defined rules about when babies should eat and sleep. “Strict” (strict) is something that is followed very closely, very carefully. A strict schedule would be a schedule that says, “At this time, every day, you're going to do this thing, and at this time, you're going to do that thing.” Dr. Spock said that mothers did not have to keep their babies on strict schedules.
Many books also told parents, before Dr. Spock’s book, to potty train their children at a very young age. “To potty (potty) train a child” means to train a child how to use a bathroom, how to use the toilet instead of having diapers. “Diapers” are things which you put around the middle of the baby so that when the baby does what all of us to do, you don't have a big mess – if you know what I mean.
Books before Dr. Spock's book also said that parents should not show too much affection to their children. “Affection” (affection) is love and care that you show another person. Before Doctor Spock's book, hugging and kissing children and playing with them on the floor was not something that books on child care approved of. However, as a pediatrician, Spock noticed that a child's “emotional needs” were sometimes not being met, the child's emotional requirements, if you will, were not being met by these kinds of practices. He became very interested in psychology and began to encourage mothers to show more affection to their children.
He also encouraged them to breastfeed. “To breastfeed” means to give the baby human milk, milk from the woman's breasts. Some women, some mothers, feed their children milk that is not from the mother but from a cow. Dr. Spock was saying, “No, you should breastfeed your children.” Dr. Spock also said that it wasn't necessary to potty train children at a very early age. Parents instead, he said, should wait until they're ready.
He made all of these recommendations in a very friendly tone, or friendly writing style, and that was one of the reasons why the book was so popular, because it was written in a way that people could understand it.
Dr. Spock’s book addressed many stages of development. A “stage of development” is a period of development, when something is growing. Spock’s book talked about very young children – children in their “infancy” (infancy) – as well as children who were older, children who were teenagers.
Spock revised his book a couple of different times in order to include more and more topics that seemed important in American society at the time, such as how much men should take care of the children versus women, and other problems. The book, as I mentioned, was extremely popular. Spock went on to write several other books and many magazine articles. He was on television a lot during the 50’s and 60’s, and he taught courses at universities.
Spock had other interests as well. In addition to his fame or his popularity as a pediatrician, Spock was an Olympic rower. A “rower” (rower) is a person who rows. “To row” is to take two long pieces of wood, usually, what we call “paddles” (paddles), and move them back and forth in the water in order to move your boat forward. Dr. Spock was a rower and a very good one.
He also became a political activist. An “activist” (activist) is someone who goes out and tries to change the policies or the laws of one's country or one’s local government. Spock became an activist who, several times, practiced something called “civil disobedience.” “Civil (civil) disobedience” is when people don't follow the law in order to get arrested, in order to give publicity typically for their cause, in order to make sure that other people know about this law that they don't like or they don't want. Spock sometimes used civil disobedience to protest the American involvement in Vietnam during the 1960’s and early 70’s. This activism got him into some trouble. Some people didn't like his political views, but that didn't stop Dr. Spock. In fact, in 1972, he ran for president of the United States, although he only received about 75,000 votes.
Spock died in his home here in California in 1998, when he was 95 years old. When he died, the New York Times, one of the most important newspapers in the U.S., said, “Babies do not arrive with owner’s manuals, but for three generations of American parents, the next best thing was Baby and Child Care.” An “owner’s manual” is a little book that shows you how to use something that you purchased, like a television or a new refrigerator. What the Times was saying here was that, when a baby is born, the baby doesn't come with an owner’s manual, but American parents, in a sense, had an owner’s manual with Dr. Spock's book. The New York Times was trying to emphasize how important Spock's book was on child rearing in the United States. “Child rearing” refers to raising or bringing up your children.
I have to say that you shouldn't take Dr. Spock's recommendations as being true just because they were popular. Later, some pediatricians disagreed with some of Spock's recommendations. So, I'm not recommending that you follow his recommendations. They might be true or they might not. I'm not someone who has enough experience in this area to tell you one way or another.
Now let's turn to our next topic, which is the Florida Everglades. The “Everglades” (Everglades) consists of a large area in southern Florida that is basically a marsh. A “marsh” (marsh) is like a large area of land that is a swamp or is what we might call “wetlands.” It's a land that's almost always completely wet, but there are plants and other things growing in this wet area.
For many years, people tried to drain the Everglades in southern Florida. (Florida is in the southeast corner of the United States, by the way.) People tried to drain the Everglades so that they could use the land for farming and for housing. “To drain” (drain) means to remove water from an area. People tried to build systems that carry the water from one place to another so that they could use the land, but there were a lot of technical problems. Some of the land was successfully drained, and a lot of the Everglades have been damaged because of that. It would no longer be possible to bring them back. In 1947, however, the U.S. government thought that it should protect some of the Everglades, so it took about twenty percent of the Everglades area in southern Florida and made it into a national park called, of course, Everglades National Park.
The Everglades are home to a lot of plants and animals. There's a lot of what we would call “biodiversity” in the Everglades. “Biodiversity” (biodiversity) means there are a lot of different kinds of plants and animals in the area, and the government wants to protect those so that they're not destroyed. Today, the Everglades is still protected at least in the national park. However, many more people have tried to move into the area and some people say that some of the animal species – the types of animals – are endangered.
“To be endangered” (endangered) means that there is a risk that they will disappear, that they will die, that we will no longer have any more of that kind of animal, plant, or fish, because of humans coming into the area. The word “endanger,” as a verb, can be used for humans as well. If you are in danger, we could say, “These people are endangered by the violence that is taking place in their country.” Normally, it's used to describe the case that we have here, of plants and animals which may be destroyed by humans. We also use this adjective “endangered” to describe certain languages where there aren't very many people who speak it anymore and therefore, we want to protect those languages. One reason people may not speak it is because they learn other languages, more popular languages like English.
Everglades National Park tries to protect the more than 350 species of birds and the many types of fish that live in the area. There are plants that have adapted to the Everglades that are quite interesting. If you have a chance to visit southern Florida, maybe you're going to Disney World in Orlando and you have some extra time, or your visiting Miami, you can drive out to Everglades National Park. One of the more interesting trees is called a “mangrove” (mangrove). Mangrove trees have special roots that help them stand up in the wet ground, the wet soil, almost like having different legs. It's an interesting plant.
About one million people visit Everglades National Park each year. Mostly they go there for watching birds, for hiking, for walking, for boating, and for camping – all things that I would never do. The National Park Service tries to allow people in the park without damaging the natural environment that they are trying to protect.
Now let’s listen to some of the questions that you have sent to us.
Our first question comes from Kseniya (Kseniya) in Ukraine. The question has to do with two adjectives, “destroying” and “destructive.” “Destroying” comes from the verb “to destroy” (destroy), which means to cause damage. Something that is “destroying” with the -ing at the end, would be something that is causing damage or hurting something.
“Destructive” (destructive) also means to cause a lot of damage. The difference between these two is that, although destroying can be used as an adjective, it isn’t very common. You're much more likely to see “destructive” as an adjective and “destroy” as a verb, not as the adjective “destroying.” “You are destroying the furniture.” You are hurting, or ruining, or damaging the furniture. Or, “Your actions are very destructive.” “Destructive” there is an adjective, meaning “damaging.”
Although “destructive” is much more common as an adjective for this meaning, it is possible to use “destroying.” It's typically used when it is attached to another noun using a hyphen [-]. So, for example, you could say, “This is a career-destroying move,” meaning doing this will destroy or ruin or hurt your career, your job possibilities. Or “This is a love-destroying action.” It's something that will cause you to destroy or damage or hurt love for some person or some relationship.
Our next question comes from Iran from Mojtaba (Mojtaba). The question has to do with a phrasal verb, “to catch up.” “To catch (catch) up” can mean a couple of different things – several things, actually. One meaning of “to catch up” is to tell someone information that they missed because they weren’t present, they weren't there. It's similar to “fill in” as a phrasal verb, meaning to give people information about things that they missed because they weren’t present when the conversation took place or the presentation took place or whatever the situation may be. “To catch (someone) up” would be to give them that information. “Let me catch you up on what has happened since you've been gone,” or since you were on vacation.
“To catch up” can also mean to finish work that you are behind schedule on, that you you're supposed to finish before but you didn't. A student, for example, who misses a week of school will have to “catch up” on his homework. He will have to catch up on the work that he missed.
We could also say, “He has to catch up to other people,” and that's a slightly different meaning of “to catch up.” “To catch up” can also be used to refer to reaching someone who is advancing in front of you. In this case, the other students are advancing in or progressing in their knowledge and you have to run, if you will, in order to reach them. That's another possible meaning of “to catch up.”
There’s a related verb here, which is “to get caught up.” “Caught” (caught) is the past tense of “catch.” “To get caught up” is slightly different, however. “To get caught up” means to get involved in something, often something that you didn't really want to get involved in. “I don't want to get caught up in office politics, in people trying to do better than each other at my work but doing it in a way that might be dishonest or involve a lot of fighting or gossiping.” “I don't want to get caught up in this movie.” I don't want to start watching it and get emotionally involved in it because I have to leave in 10 minutes.
To be “caught up” can be a positive thing, of course. “I was reading a novel and I got caught up in it and read it for five hours straight – for five hours in a row.” That's again, a different meaning from “to catch up.”
Also, there is a noun in English pronounced the same as the phrasal verb “to catch up” which is “ketchup.” “Ketchup,” as a noun, is something that you would put on your hamburger or your hot dog. It's made of tomatoes and vinegar. It's a liquid. No relation to the phrasal verb “to catch up.”
Finally, Norbert (Norbert) originally from Poland, now living in Germany, wants to know the meaning of another phrasal verb which can also be used as a noun, “to drop off.” “To drop off” can have a couple of different meanings. One, the most common meaning, would be to deliver something to a place, to take some package or some item and bring it to another place, where you are delivering or giving it to another person. For example, if you borrow books from your public library, if you go and get a book from your city's public library (if you have one), you eventually have to return the book. You might say, “Oh, I have to go drop off my book.” I have to go bring it and leave it. When you drop something off, you're always leaving it there. You're not taking it back with you.
Sometimes, we use the phrasal verb “to drop off” to mean to bring something to an office, to some official place of businesses, and simply to leave it there without talking to anyone or giving it to a specific person. “I'm going to drop off my book at the library” could mean “I'm going to leave it in a box that they have for returning books.” I don't give it to any specific person. That’s sometimes the way the phrasal verb is used.
“To drop off” can also mean simply to decrease, to go down in size or intensity. “Our sales have dropped off this month.” The number of things that were selling at our company is decreasing. The number is getting smaller. It's “dropping off.”
As a noun, a drop off can be a place where something is dropped off or something is delivered. It can also be a place where the ground suddenly goes down very quickly, sometimes vertically. So, you're walking outside somewhere and suddenly the ground “drops” ten feet, that would be called a “drop off.” It's not quite as common as the other uses that I've mentioned, however.
If you have a question or comment for us, you can e-mail us. Our e-mail address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2013 by the Center for Educational Development.
Glossary
pediatrician – a doctor who specializes in providing healthcare for children and teenagers
* We took Elaine to the pediatrician because she had a high fever for three days.
common sense – the knowledge that most people have, but that isn't taught formally in schools
* Use your common sense! You shouldn’t put plastic containers in a hot oven!
to trust (one’s) instincts – to rely on things that we know how to do or know that we should do without being told by other people
* If you ever find yourself in an unsafe situation, trust your instincts and get out of there as quickly as you can.
strict schedule – with defined rules about when things should be done; with behaviors and actions planned for specific times
* With three young children to prepare for school in the morning, our family has a strict schedule for when to get up, when to eat breakfast, and when to leave the house.
to potty train – to teach a child to use a toilet and stop using diapers
* Letty didn’t like being potty trained and refused to go into the bathroom.
affection – care and love toward another person
* My father didn’t show affection in traditional ways, but did kind things for other people to show that he cared.
rower – a person who uses long, wooden paddles (sticks with one flat end and long handles) in the water while one is seated in a small boat to move it forward
* If we had another rower in this boat, we’d be moving a lot faster.
civil disobedience – refusing to follow certain laws or rules as a way to protest against something without participating in violence
* Jake refuses to cut his lawn as an act of civil disobedience against his housing development’s strict rules.
childrearing – the process of helping children grow up, taking care of them and giving them what they need
* When Manuel’s wife had their first child, they relied on his parents for childrearing advice.
to drain – to take the water out of an area so that the soil dries out and becomes solid and stable
* If we drain this area, do you think it can be used for farming?
endangered – at risk of disappearing forever because it is dying, usually because the place where plants and animals live is being destroyed by humans
* You can’t kill those birds! They’re endangered.
mangrove – a type of tree that has special roots that help it stand up in wet soil, almost like having many legs
* The house I grew up in had a mangrove in the fields that was over 200 years old.
destroying – causing damage; causing harm
* When the little boy is in a destroying mood, he throws his toys all over his room.
destructive – causing a lot of damage; ruining something
* The big dogs running around in the garden was destructive to the flowers and plants.
to catch up – to bring oneself to the same spot as someone who is in front of one; to do the work that should have been done by now; to be raised or pulled along by something; to give the latest details to someone
* Wait! If you don’t slow down, how will I catch up with you?
to drop-off – to leaving someone in a place; to decrease
* Every morning, Barry has to drop-off his sister at school before he goes to work.
What Insiders Know
“Monday’s Child”
Every “expectant” (with a baby about to be born) parent wants to know what kind of “character” (personality) or future the new child will have. First “published” (printed for an audience to read) in 1858, a “nursery rhyme” (poem for children) “predicts” (says will be true in the future) the personality of a child based on the day of the week he or she is born. People don’t really believe this nursery rhyme, but it is still used today to help children learn the days of the week.
“Monday’s Child”
Monday's child is fair of face
Tuesday's child is full of grace,
Wednesday's child is full of woe,
Thursday's child has far to go,
Friday's child is loving and giving,
Saturday's child works hard for a living,
But the child who is born on the Sabbath Day
Is bonny and blithe and good and gay.
According to this nursery rhyme, Monday’s child is “fair of face,” meaning either that the child will have light-colored hair, eyes, and skin, or that the child is pretty or handsome. “Fair” can be used to mean good-looking, but it is considered old-fashioned these days. Tuesday’s child is “full of grace.” This can have two meanings, too, because “grace” can mean being favored by God in the Christian religion or it can mean to move one’s body in an elegant way. We often say that someone has grace if they can move easily and attractively when they walk, run, dance, and more.
Unfortunately, Wednesday’s child is “full of woe.” “Woe” means sadness, so if you’re born on Wednesday, you’ll be full of sadness. Thursday’s child has “far to go,” which probably means that this child has to improve a lot before meeting standards set for a child. So, as you can see, you don’t want to born on a Wednesday or Thursday.
Friday’s child is loving and “giving,” meaning that he or she is generous. Saturday’s child “works hard for a living,” meaning that he or she must labor a lot to earn money to live. Finally, the child who is bon on the “Sabbath Day” – Sunday for Christians – is “bonny” (attractive) and “blithe” (cheerful and carefree) and good and “gay” (happy).