= 1710
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast English Café number 405.
This is English as a Second Language Podcast’s English Café episode 405. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Download this episode's Learning Guide, an eight to ten page guide we provide for all of our current episodes that gives you some additional help in improving your English.
On this Café, we're going to continue our series on famous movies, focusing on a movie called A Clockwork Orange. We’re also going to talk about a very famous television group called the Mickey Mouse Club. And as always, we’ll answer a few of your questions. Let's get started.
This Café begins with a continuation of our series on movies. Today we're going to talk about a movie called A Clockwork Orange. The title is a little strange and I'll describe it in a few minutes, but let me give you some background information about the film.
First, this film was made in 1971 by Stanley Kubrick. Kubrick is considered by some people to be one of the best filmmakers of his generation. You're probably familiar with a more famous movie called 2001: A Space Odyssey, one of the early popular science fiction movies. The movie, A Clockwork Orange, is based on a 1962 novel with the same name written by a British author by the name of Anthony Burgess. The film and the novel have a similar story, and that story, I think, can best be described as “disturbing.” When something is “disturbing” (disturbing), we mean it is not nice, unpleasant, but also uncomfortable, something that makes you feel uncomfortable. Disturbing news would be news that is not only bad news, but it's about something that’s strange, something that makes you very upset.
A Clockwork Orange is a disturbing film because it has a lot of very violent images in it, a lot of images, a lot of scenes, that show violence. The story is about what we would describe as a “dystopian future.” You may have heard of the word “utopia” (utopia), which describes the perfect world in the future. There was actually a story written called Utopia many years ago, many centuries ago, by St. Thomas Moore, the English writer. The opposite of a “utopia” would be a “dystopia” (dystopia). This story, A Clockwork Orange, is about a dystopian future, a future where things are terrible, where people are very unhappy.
The novel and the movie take place in a dystopia that is in Britain, in Great Britain, in the future. What happens in this dystopia is that you have young people who become very violent. The story itself focuses on a young man named Alex. Alex is the leader of a small gang. A “gang” (gang) is a group of people, usually young men, who are involved in some sort of criminal activity, who are selling drugs or stealing things and so forth. The gang that Alex is involved in does a lot of terrible things, including going on “crime sprees.” A “spree” (spree) is a short period of time or a fixed period of time when you do some activity with a lot of enthusiasm or with a lot of intensity. A spree would be doing something many different times. You can have a “shopping spree,” where you go and you spend money and you buy lots of things in a short amount of time or in a certain amount of time. This however is a crime spree that the gang is involved in. The gang members work together during these crime sprees. They beat people. They hit them. They steal things. They “rape” (rape) women. They force them to have sexual relations with them, and so forth.
Alex loves this violence. He also, strangely enough, loves classical music, especially music by the great German composer Beethoven. One night, in the story, the gang that Alex is a part of breaks into or enters illegally into a large home – what we would describe perhaps, as a “mansion” (mansion), a very large and expensive house. They beat the owners of the house. They hit them and tried to steal things.
But then something goes wrong. Alex is betrayed by the other gang members. “To be betrayed” (betrayed) means that someone that you trust does something to hurt you, someone that you thought liked you, someone who you thought was going to be loyal to you, to be committed to you, to be protective of you, suddenly does something to hurt you. You can betray another person. You can betray an organization. You could betray your country. You could give secrets, military secrets of your country to another country. That would be a kind of betrayal. Or if you're married, you could go out and have a romantic relationship with another woman. That would be betraying your wife.
In this case, Alex is betrayed by the other members of his gang. The gang members attack Alex, they hurt him and they leave him there for the police to find. Well, of course, the police eventually come to this house and they arrest Alex. They put him in jail. They put him in prison.
Alex, while he's there, participates in a government experiment. The experiment involves him sitting in a chair with his eyes open, watching very violent images, often, very violent sexual images, and right before each session, the government gives him some drugs that make him very nauseated. “To be nauseated” (nauseated) means to feel sick, sick to your stomach, like you have to vomit, like you have to throw up.
The idea, which of course we can associate with a certain type of psychological treatment, is to get Alex to associate, to connect the violent images that he’s seen with the illness that he feels so that. When he sees these violent images, he will become sick. He will become nauseous. Now, whenever Alex tries to do something violent, he gets sick. The government considers this a success, and Alex is allowed to leave prison, to leave jail and go back to his life.
I don't want to tell you what happens at the end of the movie because there is a very surprising end that I don't want to give you, but one of the main ideas of the movie, and the original book, is whether Allen's behavior after he gets this government treatment for violence is really moral, is really good, is really ethical. He isn't committing violence against other people, which of course, is a good thing, but in some ways, the government has taken away his choice, his ability to decide for himself because they've given him this psychological treatment that associates violence with illness.
Is a person who doesn't have free choice, who doesn't have the ability to choose whether they do something or not, really free and really ethical, really moral? Well, I don't want to give you the answer to that. I don't know the answer to that exactly. Well, I have an idea, but…my idea. The point is that the movie tries to raise this question. It tries to ask this question to get the people thinking about this issue now.
I said that the title of this movie, A Clockwork Orange, was a bit strange. There are several ideas about what the title means. I think it combines a couple of different ideas. Orange is, of course, a piece of fruit that’s sweet, that is of the color, orange. It's good to eat. It comes from a living plant, a living orange tree. “Clockwork” describes the inside of a clock or watch, the mechanical parts of a clock or watch, especially the old fashioned clocks that still had the mechanical parts to them. It wasn't all just a little computer inside.
One idea about the title of this novel and movie is that Alex is like an orange. On the outside, he's natural. He looks normal, but on the inside, he's not really a human being. He's like a clock. He's being controlled just like a clock. A clock doesn't have any free choice, any “free will,” we might say. The clock simply does whatever it’s designed to do, and that's what Alex is like. That's, at least, one idea about what this somewhat unusual title means.
The movie had some very famous actors of that time, most importantly, Malcolm McDowell. It also had a few others. But the person people usually think about when they think about this movie is the director, writer, and producer, Stanley Kubrick. Despite the violence of the film or maybe because of it, the film was very well received in the United States. It made a lot of money here. I saw it in the late 1970’s, not when it was originally in the movie theaters, although I think I did see it at a movie theater. I think they were showing old movies – you know, sometimes how movie theaters show movies from many years ago.
Well, the movie, as I said, was very profitable. It made a lot of money. It was nominated for an Academy Award, an Oscar for best picture, and three other Academy Awards, although it didn't win any of them.
However, in Britain, in Great Britain, the reaction was very different. Apparently, the film, the movie was referred to in a trial for a murder convicted by a young boy who had told his friends about the violence in the movie. Some people blamed the movie for this violence. Kubrick disagreed that his movie had caused this violence, what some people would call “copycat crimes.” A “copycat” (copycat) – one word – describes someone who imitates another person, does just what the other person does. “Copycat crime” would be someone reading about a crime and then going out and committing or doing that crime themselves. In Great Britain, some people thought this young murderer was inspired somehow by the film, and so Kubrick asked that the film be withdrawn in Britain, that it not be shown. And the film was withdrawn in Britain – for 27 years, during which time it was very hard for people in the United Kingdom in Great Britain to see this movie. It's kind of an interesting case of where a movie is not available in a country, especially since it is about that country.
Now let’s turn to something you might have seen on television or perhaps in the theater that is a little less disturbing than A Clockwork Orange. I'm speaking of something called the Mickey Mouse Club. You probably know who Mickey Mouse is, the little cartoon mouse created by Walt Disney who is the symbol of Disneyland and Disney World. Disneyland, of course, is here in Southern California. Disney World is in the state of Florida, on the other side of the United States, and there are other Disney parks in other countries now.
“The Mickey Mouse Club” was a television show that was shown on television “intermittently,” we might say, from 1955 to 1996. It was on a very long time, including when I was growing up. However, the show was not on continuously. It wasn't on all the time, every year. It was shown “intermittently.”
“Intermittent” (intermittent) means that there are interruptions, there are gaps. It's not continuous, not all the time. “The Mickey Mouse Club” was what we would describe as a “variety show.” A “variety” (variety) of something is a lot of different kinds of something, different types of something. A “variety show” would be a television program that had different things going on. Sometimes they would be singing, sometimes there might be dancing, sometimes there might be comedy; different things happen on a variety show. Variety shows were very popular in the United States in the 1960’s and 70’s. They are not as popular now. Now, usually if you have a singing show, it's all about singing. There aren't other things going on.
Well, “The Mickey Mouse Club” was a variety show, and it was a variety show for young children. They had information about current events, about the news. They had cartoons, they had music, they had dancing, they had jokes, and so forth. The show had very large cast. The “cast” are the group of actors who are in the show.
The child actors changed frequently, but some of the children, who became known as “Mouseketeers,” became famous actors later in their life. Probably the most famous of the original Mickey Mouse Club actors, the original “Mouseketeers”, was a woman by the name of the Anette Funicello. Funicello died in April of 2013. She was later a well-known actress.
So, sometimes you have these young children who are actors who grow up and continue to be famous. Sometimes they became famous for their acting, sometimes for their singing. There are several well-known singers that you have probably heard of that started their entertainment careers as members of the Mickey Mouse Club, as “Mouseketeers.” That would include Britney Spears, the singer; Justin Timberlake, the singer and actor (not a great actor but, okay, an actor); Christina Aguilera, a singer; Ryan Gosling, an actor, and others.
The most famous thing about “The Mickey Mouse Club” when I was growing up was the music. “The Mickey Mouse Club” wasn't that popular with the people my age in the 1970’s. There was, remember, these gaps where the show wasn't shown. It wasn't shown all that much when I was a young child. It became popular later, in the 80’s and 90’s. However, the song is something that almost everyone knows who grows up in the United States – or at least did in that period of time. The song goes:
Who's the leader of the club
That's made for you and me?
M-I-C-K-E-Y M-O-U-S-E
The song starts, “Who's the leader of the club?” – who's the person in charge of this group – “That's made for you and me,” because we were all part of the Mickey Mouse Club if you watch the show. And the answer is, of course, “Mickey Mouse.” And you hear his name spelled.
Now, at the end of the show, they would sing this song very slowly, and there was a little bit of a change in the song. They would say, “M-I-C-…see you later! K-E-Y- why? Because we love you! M-O-U-S-E.” So, “M-I-C” – “C” the letter sounds the same as the verb “to see,” and that's why they say “see you later,” because of course the show is ending. “K-E-Y – Why? Because we love you.” The letter “Y” sounds like the word, the question word, “why.” Why are we going to see you later? Because we love you. And then M-O-U-S-E. “M-I-C-K-E-Y M-O-U-S-E.”
Now, the funny part of the song also was that, during the song, Donald Duck would also sing his name, trying to take over the place of Mickey Mouse.
Who's the leader of the club
That's made for you and me?
M-I-C-K-E-Y M-O-U-S-E
Mickey Mouse (Donald Duck!)
Mickey Mouse (Donald Duck!)
And so, Donald Duck would throw his name in there. I do a terrible imitation of Donald Duck, by the way. The song however, was very “catchy” (catchy). A “catchy song” is a song that you can remember easily, a song that that you probably don't even want to sing, but because the music is so memorable, you will always remember it.
Now let's answer some of the questions you have sent to us.
Our first question comes from Kirill (Kirill) from Russia. The question is about a sentence Kirill saw in a book or perhaps heard in a movie: “He looks like a used car seller from Texas.” The original line was probably something like, “He looks like a used car salesman from Texas.” In either case, here's what this word, or rather this sentence, means.
A “salesman” is a person who sells cars. “Seller” (seller) means the same. “Used cars” are cars that are not new, that someone else has driven before. “Texas” is the large state in the south-central part of the United States. However, the expression “a used car salesman” is usually associated with the person who isn’t a very honest. Used-car salesmen, in United States at least, have the reputation of being dishonest, of lying to you, of saying, “Oh yeah, this is a great car,” and then you buy it and it turns out to be a terrible car. That's definitely a negative description of someone – “used-car salesman.”
People from Texas have the reputation of being perhaps a little loud, a little confident, overconfident, a little – we might use the adjective “flashy” (flashy), meaning wearing very bright colored clothing, perhaps a lot of jewelry. This is, as I say, a stereotype. Most people from Texas are not like this, but that's kind of the image, the popular image that people have of people who are from Texas. So, you really have two different stereotypes here, two different negative descriptions. One is the used-car salesman and the other one is the Texan. The person here is probably being described as a dishonest, perhaps loud, obnoxious man.
Our next question comes from Carlo (Carlo) in Italy. Carlo wants to know the difference between “snag” (snag) and “hitch” (hitch). “Snag,” can mean a couple of different things. One is a cut or a hole, usually in a shirt or sweater, that is caused by accidentally touching a very sharp object, like a nail. Let's say there's a nail in the wall, a short piece of metal that's sticking out of the wall, and you have a shirt on, and you accidentally touch the nail with your shirt, and you move it and the shirt rips. It creates a little hole. We could call that a “snag.” It's typically used for sweaters – for thick, if you will, shirts that you wear to keep warm.
A “snag” however, more commonly, is anything that is a problem, anything that is preventing you from being successful. “We had a great plan for the party but then we hit a snag.” Notice the verb “to hit.” We “hit” a snag. We encountered a problem. We discovered there was some reason why we couldn't continue going forward with our plans.
There's a third popular definition of “snag” which means “to grab,” “to take,” often when you go to a store and you are buying something that is very popular and there are very few items left. “I snagged the last iPhone.” “I snagged the last piece of chocolate candy that everybody else wanted,” whatever it happens to be.
“Hitch,” like “snag” can also mean an unexpected problem. This is similar to the second definition I gave of “snag.” “We have a hitch” or “there’s a hitch” in our plans – that means there's a problem. There's something that is causing us to stop progress on our plan. We are not able to go forward with our plan. In some ways, “snag” and “hitch” can be used interchangeably. They both mean an unexpected problem that is preventing you from going forward with your plans.
“Hitch,” I should also mention, also can have the meaning of a special condition that has to be met, usually, one that you didn't expect. For example, “You can have my old car to drive tonight to the movies but there's a hitch.” There's something you have to do for me. There is some condition that you have to follow that you probably weren't expecting. You have to wash my car before you bring it back to me. That's the “hitch.” That's the special thing you have to do, in this case, for me.
Our last question comes from Kahazaee (Kahazaee). There's no country listed here, I'm going to guess Iran. Kahazaee wants to know, in the title of the magazine, Reader’s Digest, what the word “digest” means. A “digest” (digest) is a collection of stories, a collection of news that is often summarized or made shorter. Reader's Digest is a famous American magazine, which is published now in many different languages, that has short interesting story, often stories taken from other places, from other newspapers or other magazines. A “digest,” as I mentioned, is sometimes a summary of many different news stories. You don't have to read the entire article. You can just read the digest.
Reader's Digest is one of the most popular magazines, or at least it used to be one of the most popular magazines, in the United States. During the last half of the 20th century, it was certainly one of the most famous magazines. Many, many millions of American families had a subscription to Reader's Digest. My mother had a subscription to Reader's Digest.
You might hear this magazine title used as an expression in a conversation in the following way. Someone wants to tell you a long story and you don't have a lot of time. You say to that person, “Just give me the Reader's Digest version of the story.” You're saying, “Don't tell me very long story, the complete story. Give me a summary of the story, just the most important facts about whatever the topic is.” That's the Reader's Digest version of a story.
Again, the reason we would use that expression is because that's what the original magazine was like, and everyone knows that that's what the magazine was like. So we use it almost as an adjective sometimes to describe something that is the shortened version of a longer story.
The company that published Reader's Digest also publish something called Reader's Digest Condensed Books. “Condensed” means made smaller or made shorter. These were actually novels that were shortened. They would take out certain chapters or they would summarize things so that you didn't have to read the whole book. You could just read the condensed version of the book! If you were busy and you didn't have time to read the entire book, you could read this shortened version of the book. These condensed books were very popular among middle-class Americans – not highly educated, not very rich, but educated enough to want to be able to read – or at least, to seem as though they knew about – the latest novels, the latest books by the most popular authors of the day.
If you have a question or comment you can e-mail us. Our e-mail address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2013 by the Center for Educational Development.
Glossary
disturbing – something that is upsetting, unpleasant, and makes one feel uncomfortable
* Do you think it’s disturbing that our neighbor never leaves his house?
dystopian – describing a place and time where everything is terrible and people are very unhappy
* Dystopian films often show what happens when the Earth is destroyed and most people are dead.
gang – a group of people, usually young men and women, who are involved in illegal activities and try to gain power and control over an area by threatening other gangs and the people who live there
* Two different gangs claim this street as their territory and they fight over it.
crime spree – a period of time when a criminal does many illegal things, often one after another
* Bonnie and Clyde went on a crime spree, killing and robbing people along the way.
to rape – to force women to have sex while hurting them
* In the film, a woman who had been raped found her attacker and put him in jail.
to betray – to do harm to someone who trusts one; to be disloyal
* I told Jimmy that I cheated on the test and he betrayed me by telling the teacher.
nauseated – feeling sick, as though one needs to vomit (throw up)
* It’s not unusual for pregnant women to feel nauseated in the first months pregnancy.
free choice – the right to decide what one wants to do in a particular situation; the right to decide for oneself
* We all have free choice to do what is right and wrong in each situation.
copycat – for someone to imitate another’s actions; for a person to do what someone else had done and in a similar way
* The police caught the art thief, but a copycat continues to steal paintings from museums using the same method.
intermittently – off-and-on; occurring for a period of time, but with some gaps in time in between each occurrence
* It’s been raining intermittently all morning. I’m waiting for it to stop temporarily so that I carry in boxes from the car.
variety show – with many different types of acts and forms of entertainment put together in one show
* The students put on a variety show to raise money for the school.
catchy – for a song or a phrase to be easy to remember
* The song in this new commercial is so catchy that I find myself singing it throughout the day.
used car salesman / seller – someone who sells previously owned cars as a job; a person who is not completely honest and is trying to convince you of something that isn’t true
* Tell the interviewer your qualifications, but try not sound like a used car salesman.
to snag – to have fabric catch on a sharp object and to cause a hole or a rip; to become tangled; to grab
* Julia ran past the tree and snagged her sweater on a branch.
to hitch – to fasten with a rope to something; to raise in a quick motion; to catch on a sharp object
* Hitch the boat to the back of the car with this hook.
Reader’s Digest – a family magazine published 10 times a year
* Did you read the article in the Reader’s Digest about the man who fell into a deep cave and survived?
What Insiders Know
The Inventor of Mickey Mouse: Ub Iwerks
Mickey Mouse is so well known to people around the world that it’s hard to remember a time when he was not part of children’s toys and entertainment. Everyone thinks of Walt Disney, the “co-founder” (one of two people who started) of The Walt Disney Company as the “creator” (inventor) of the Mickey Mouse character, but it was actually one of Walt Disney’s oldest friends, Ub Iwerks, who created him.
Both Walt Disney and Ub Iwerks worked for Universal Studios in the 1920’s. While working there, Disney asked Iwerks to come up with a new cartoon character. Iwerks drew a lot of different animals, including cats, dogs, and frogs, but none of them were “just right” (perfect). Finally, Iwerks saw an old drawing and was “inspired” (got the idea) to draw a mouse.
Disney and Iwerks worked “secretly” (without others knowing) on a new cartoon while still working for Universal. After two “shorts” (short films) “featuring” (having as the main character) Mickey Mouse were “not well-received” (did not good responses), Mickey Mouse finally made his “debut” (first appearance in front of an audience) in a short called Steamboat Willie in 1928.
Ub Iwerks was the “head” (lead; main) animator and Walt Disney was the “director” (person responsible for making a film). In this film, Mickey Mouse had a different “appearance” (look) than in his “previous” (in the past) films. His eyes were “simplified” (made simpler, with less detail) to two large dots, which would be his look for later cartoons and many Disney films.
Sadly, Disney and Iwerks later had a “falling out” (argument) that ended their friendship. Disney continued producing cartoons without Iwerks and Iwerks went on to start his own animation company in 1930.