= 1721
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 416.
This is English as a Second Language Podcast’s English Café episode 416. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there today to become a member of ESL Podcast and download the Learning Guide for this episode.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other people talking in English and then I go back and explain what they said. We’re going to listen today about taking care of your parents when they get older. And, as always, we’ll answer a few of your questions. Let's get started.
On this Café, we're going to talk about taking care of elderly parents. The word “elderly” (elderly) refers to a man or a woman who is older, usually someone over the age of 65 or 70. We wouldn't perhaps call that person elderly. The definition changes as you yourself get older, because “elderly” has an association with very old people. So, if you're 65 or 70 years old, you don't consider yourself elderly. You consider people who are 75 or 80 to be elderly, and of course, people who are 75 or 80 consider people who are 85 and 90 to be elderly. You get the idea.
Another term you'll hear connected with this idea is “senior citizen,” or simply “senior” (senior). How old do you have to be to be a senior citizen? Well, it depends. My younger nieces and nephews might think I'm a senior citizen. I'm not sure. We're talking here about taking care of elderly parents – your mother and/or your father.
We’re going to start by listening to a woman by the name of Sauk Page, who lives in our nation's capital, Washington, D.C. We’ll first listen to her talk about her mother. Her mother lives next to the house where she lives, but she lives in a special kind of house: a small building that is built especially for people who are old. It has certain features. It has certain characteristics that make it easier for an older person to live there. This little house really is connected to the main house where the woman we’re going to hear speaking, Sauk Page, lives with her family.
First we’ll listen to her talk about her mother and why it was so important for her to find a place for her mother to live that would be close to her.
[recording]
“She absolutely refuses to even consider a nursing home. That was completely out of the question, and my home is just not safe for her, so this is an alternative. She’s here, but she has her own space. It’s set up for her, it’s safe for her, and it’s not a nursing home. We are actually her primary caretakers.”
[end of recording]
Page begins by saying that her mother “absolutely refuses to even consider a nursing home.” When we say she “absolutely refuses” to do something, we mean she says no and there's no possible way of changing her mind. There is no circumstance that is going to make her decide otherwise. When someone refuses to do something, they say, “No, I'm not going to do it.” If we described them as “absolutely refusing” to do something, we’re saying that not only did they say no, but there is no possibility of them ever saying yes.
That's the case with Page’s mother. She absolutely refuses to “consider a nursing home.” “To consider” means to think about. Page’s mother will not go to a nursing home. She won't “even consider” going to a nursing home. Notice the use of the word “even” there, to give it even more emphasis. She will not think about going to a nursing home.
A “nursing home” is a special place that takes care of people who are old or people who are sick. That's a nursing home. Usually, a nursing home is for old people, for the elderly, for senior citizens. Sometimes nursing homes will also take care of people who are very sick and cannot take care of themselves but who don't have to be in a hospital. Those are often given other names as well: “care facilities” or “long-term-care facilities.”
We’re talking here about nursing homes. Nursing homes have a bad reputation in many ways in the United States. Many people don't want to go to a nursing home because they think they'll be lonely there. They won't have their family members with them, which is in some ways true. Not all nursing homes are bad, however. It's not usually a problem with the care that is given at the nursing home, but rather the environment.
Page’s mother absolutely refuses to consider going to a nursing home. Page says that nursing homes were “completely out of the question.” The idea of going to a nursing home was “completely out of the question.” When something is “out of the question,” we mean we're not even thinking about it. We're not even going to consider it. There will not be any discussion about it. It's “out of the question.” If your daughter asks if she can borrow your car and come home at three o'clock in the morning, you say, “No, that's out of the question.” Well, if you don't, you should say it's out of the question. Page says that sending her mother to a nursing home was completely out of the question. “Completely,” here, is used for emphasis.
There is no possible way that they are going to consider sending the mother to a nursing home. Page says, however, that her home, where she and her family live, is “just not safe” for the mother. When we use the word “safe” as an adjective, we are talking about a place that would be protected, where you would not hurt yourself, where you would be away from anything that could hurt you or harm you. I'm not sure exactly what Page has in her house that makes it unsafe for her mother. Maybe she has a lion in there or some sort of a dangerous cat, because you know, of course, cats can be very dangerous.
Page, however, is for whatever reason not interested in having her mother live physically in the same house where she lives. So, she has to find an alternative. An “alternative” is another option, another possibility. You may, for example, have two restaurants that you are thinking of going to. You have the restaurant you normally go to, but you also have an alternative. You have another choice – another place, in this case, you could go. Page needs another alternative for her mother – not a nursing home, but not living in her own house, either. That alternative was this special little house that she put next to her own house.
Page says that her mother is “here,” meaning near the house, “but she has her own space.” “To have your own space” means to have your own place where you can live. You could, perhaps, also use this in an office situation where you have two people who are using the same desk. One of them might say, “I need my own space.” I need a place where only I will work. Page’s mother has her own space.
Page says, “It's set up for her,” meaning it's organized for her. It's built especially for her. She says it's “safe” for her mother and “it's not a nursing home.” Finally, she says, “We” – perhaps she and her husband or she and her children – “are actually her primary caretakers.” A “caretaker” (caretaker) is someone who, you can guess, takes care of something or someone. Often, we use the word “caretaker” in talking about someone who looks after or makes sure everything is going well in a building, such as an apartment building.
“Caretaker” can also refer to someone who takes care of a person – another person or even another animal. Page, of course, has this lion in her house, so she is a caretaker to the lion, but she's also a caretaker to her mother, who hopefully is not as mean as a lion. The other word that we might use in this situation is “caregiver,” which is kind of strange because the verb “to take” is opposite of the verb “to give.” But sometimes, especially when we're talking about a situation like this where you are taking care of one of your own family members, we might use this expression or this term: “caregiver.”
Page describes herself as the “primary caregiver.” “Primary” usually means first. In this case, it's the most important caregiver or caretaker – the one who does the most work, who does the most in this situation. Now let's listen to Page one more time.
[recording]
“She absolutely refuses to even consider a nursing home. That was completely out of the question, and my home is just not safe for her, so this is an alternative. She’s here, but she has her own space. It’s set up for her, it’s safe for her, and it’s not a nursing home. We are actually her primary caretakers.”
[end of recording]
Now we’re going to listen to Ken Dupin. Ken is the person who owns the company that makes these little houses and puts them on someone's property next to another house. Ken has a company called EndoCare. He's going to talk about why he started this company – why he makes these little houses for elderly parents.
[recording]
“In virtually every other culture in the world, they would celebrate that. They would see that as a privilege, but for whatever reason, in the culture that I live in, we have resistance to that. And I . . . that’s my mission. It’s to change that.”
[end of recording]
Ken begins by saying, “In virtually every other culture in the world.” The word “virtually” has a couple of different meanings. Normally, nowadays, we use it to talk about something that might be happening online on the Internet, not something that is happening in the real world, the physical world that we live in. People play “virtual games,” for example, and spend “virtual money.” I have a “virtual girlfriend,” for example. No, I’m just kidding. I don't. I’m married. You know that. My wife is not virtual – she's real. That's one meaning of “virtual.”
Here, however, “virtual” is used to mean “almost, but not completely.” So, when we say, “In virtually every other culture,” we mean in almost every other culture – not a hundred percent, but 95 percent. Ken says, “In virtually every other culture in the world, they would celebrate that” – “that” being taking care of your elderly parents. “To celebrate” normally means to have a party or to have some sort of gathering where everyone is happy. Here, however, it just means “[to] consider it a good thing.” In other cultures, taking care of your elderly parents is something that is considered a good thing, a positive thing, something that you would want to do.
He goes on to say that in some cultures, in many other cultures, people see taking care of your elderly parents as a “privilege.” Something that is a “privilege” (privilege) is something that is an honor, something that is almost a reward for performing some action. It's not an obligation. It's not something you have to do, but it's something that you want to do. It’s an honor to do it.
Ken says that “for whatever reason,” meaning he's not sure why, “in the culture that I live in,” meaning here in the United States, “we have resistance to that.” “To have resistance” means that you are against something, or it is difficult for you to accept it or to do it. We have in our culture a resistance to taking care of elderly parents. This is probably true for many American families.
Ken says that he's on a mission to change this attitude, this situation. “To be on a mission” (mission) means to be very motivated, to really want to do something, to really want to accomplish some goal. “To have a mission to do something” is to have a purpose, a very strong reason for wanting to do something, a very specific goal that you are motivated to achieve. Let’s listen to Ken one more time.
[recording]
“In virtually every other culture in the world, they would celebrate that. They would see that as a privilege, but for whatever reason, in the culture that I live in, we have resistance to that. And I . . . that’s my mission. It’s to change that.”
[end of recording]
Finally, we’re going to hear from another woman who has written a lot about families, especially what we call “multi-generational families,” where you have more than one generation or more than one age group living in a house. You have Grandma, you have Mom, you have the children, and so forth. This woman is going to talk about the benefits – the good things – of having different generations, different age groups in your family living in the same house. Let’s listen.
[recording]
“There is a lot of richness that comes to life by having contact with different generations, having contact with your grandchildren and being part of a mix, being part of a real household. And that is something that older people in a lot of more traditional societies really benefit from.”
[end of recording]
This writer, whose name is Claudia Culker, begins by saying that there is “a lot of richness that comes to life by having contact with different generations.” “Richness” here probably refers to a number of good positive experiences. Claudia says, “There is a lot of richness that comes to life.” “To come to life” is a poetic way of saying to begin or to grow more important – to increase. This richness increases by having contact with different generations.
I mentioned the word “generation” as being people sort of the same age. Technically, however, it really refers to family relationships. You and your brothers and sisters and your cousins are all of a single generation. Your parents, your aunts, and your uncles are of another generation. Your grandparents and your grandparents’ brothers and sisters belong to another generation. Your children and your nieces and nephews are of another generation. Claudia is talking about having contact or having the ability to talk to and see people from different generations as being a positive thing for family.
She continues, “Having contact with your grandchildren and being part of a mix, being part of a real household” – these are positive things, when you have contact with your grandchildren, your children's children, when you are “part of a mix.” A “mix” here just means different people with different backgrounds and different experiences. A “household” (household) refers to people who all live in the same house, usually from the same family or relatives of that family. If you and four of your friends share an apartment, we would not call that a “household.” “Households” refer to people who are related to each other, who are part of the same family.
Claudia says that this is “something that older people in a lot of more traditional societies really benefit from.” “Traditional societies” would refer to cultures and societies that are perhaps not considered as modern as the one that she's talking about – the American culture. Of course, modern isn't always a good thing.
Now let's listen to Claudia one more time.
[recording]
“There is a lot of richness that comes to life by having contact with different generations, having contact with your grandchildren and being part of a mix, being part of a real household. And that is something that older people in a lot of more traditional societies really benefit from.”
[end of recording]
Now let's listen to some of the questions you have sent to us.
Our first question comes from Roman (Roman) in Russia. Roman from Russia wants to know why I say every week, “Our next question comes from” a certain person in a certain country, and not the past tense “Our next question came from.” Well, that's an interesting question, Roman. It's true that “came” is the past tense of the verb “to come,” but we don't always use it when we are talking about something that may have happened in the past. In this case, however, I use it because it is a description, or I'm about to describe who the person is that asked this question.
I could actually say that. I could say, “This question came from Roman from Russia.” If I did that, I would be emphasizing the action of it arriving to us in the past. But here, as we do sometimes in English, I'm using the present tense of the verb in order to make it seem a little bit more immediate. A similar situation happens when you are telling a story to someone. You are telling the person what happened to you in English. In many cases, we use what's called the “historical present,” which is the present tense but used to describe a story that happened in the past.
For example, yesterday, let's say, I went to the grocery store and I saw my friend. I start to tell you the story about what happened yesterday, but I use the present tense: “So I walk into the grocery store and I see my friend, and he comes up to me and says, ‘Hi Jeff,’ and I say, ‘Hey Bob, I haven't seen you in a long time.’” That story is told in the present tense. When you do that, it gives it a little more sense of immediacy, a little more sense of currency. It makes it seem a little bit more alive, somehow.
Our next question comes from Murillo (Murillo) in Brazil. The question has to do with the use of the word “several” (several). When do we use this word, and in what situations? “Several” can mean more than two but not a lot – not many. There are several possibilities as to why she did not arrive at work on time. Maybe she missed her bus. Maybe she slept too long. Maybe her friend is sick and she had to take her to the hospital. There are several possibilities.
“Several” is more than two, but not a thousand or not 50 – something less than that. How much less than that? It depends. There really isn't an exact rule when we would say “several” versus “many.” “Several” is often found with a word like “occasion,” which means an event – something that happened at a certain time. “We came here on several occasions.” We may have come last Tuesday, and then again last Wednesday, and maybe again on Friday. We came on several different occasions. The word “several” is sometimes used in conjunction with the word “few,” or at least, it's one of the options that you would have in describing how many times something took place.
The way that you describe something can also, of course, indicate your opinion about the situation. For example, if you take an examination at school and you made five mistakes, you could describe that as saying, “Well, I made a few mistakes.” Or, if there were only ten questions on the exam and you made five mistakes, you might say, “I made several mistakes.” The number five stays the same. It's the same number of mistakes, but you're emphasizing whether it was a positive thing, or at least not a very negative thing, when you say “few,” versus it was a serious problem when you say “several.”
If you meet a girl and you ask how many boyfriends she has had in the past, and she says, “Oh, a few,” you shouldn't be too concerned. If she says, “Oh, I've had several boyfriends,” then you might want to wonder a little bit.
Our final question comes from Norbert (Norbert) in Germany. Norbert’s question has to do with the phrase “top-down.” When used as an adjective, “top-down” usually refers to people in power – the bosses, the people at the highest levels of the organization – telling people below them what they should do. It's usually a negative thing when you use that adjective, “top-down.” “They have a very top-down management style in this company.” That means the people at the top of the company are always telling the people below them what to do.
Of course, you would expect bosses to tell people who work for them what to do, but when you say it's a “top-down management style,” you mean they are telling them too much. They are trying to interfere with decisions that the employees who work for them should be able to make themselves. Sometimes “top-down” is paired with, or used in conjunction with, “bottom-up.” “Top-down” – the direction goes from the top and then works down. “Bottom-up” is, of course, the opposite. The direction starts at the bottom and goes up.
So, if you had a bottom-up approach, for example, to solving problems in your company, that would mean that the employees – the people at the lower levels of the company – come up with good ideas and then they bring those ideas to their bosses. That might be one way of using that expression.
If you have a few questions you would like to ask us, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2013 by the Center for Educational Development.
Glossary
nursing home – a place that takes care of old people who have many special medical needs and have to be near a nurse or doctor at all times
* The people who live in the a home often become depressed if their family members don’t visit regularly.
out of the question – not under consideration; not an option; not available for discussion
* Dropping out of school is out of the question. You will earn your degree and graduate.
safe – providing protection so that one cannot be hurt
* Hundreds of people work to make the space shuttle as safe as possible, but being an astronaut is always risky.
alternative – another option; something one can do instead of something else
* If you don’t get that job, do you have any alternatives?
primary caretaker – the person who is mostly responsible for taking care of someone
* Heather’s parents died when she was a baby, so her grandmother became her primary caretaker.
virtually – most; almost all
* Virtually all of these good jobs require at least 10 years of experience.
to celebrate – to be pleased with something and be proud of it; to admire something and think it is a good thing, so that one treats it with respect
* In our family, we celebrate the beauty of the natural world.
privilege – an honor, something that we are allowed to do almost as a reward; not an obligation
* Driving is a privilege, not a right, and can be taken away if you break too many laws.
resistance – an attempt to push against something, not wanting to have it or not wanting to do it
* Clarke is showing a lot of resistance to studying medicine, but his father doesn’t want to let him to study anything else.
mission – one’s goal and purpose in life; what one is trying to do
* Our company’s mission is to organize the world's information and make it accessible to everyone.
richness – luxury and great enjoyment and appreciation for something
* Most people find richness in their friends and family, not necessarily in their jobs or possessions.
generation – a group of people who were born around the same time, such as children/parents/grandparents
* Earlier generations tended to save more money than the younger generations do.
mix – a group of different people or things interacting with each other
* Trenton already has three dogs, two cats, and a rabbit, but now he wants to throw a monkey into the mix.
household – a group of people who live together and interact with each other as a family
* How can we possibly maintain a six-person household with just $20,000 per year?
several – more than two but not many; different; separate
* Their family owns several local businesses.
top-down – a type of government or management in which decisions and actions are made at the highest levels, with little or no input from those at the lower levels
* The new CEO has a top-down management style that the employees are struggling to adapt to.
What Insiders Know
Betty White
Betty White is an American actress, “comedian” (someone who makes other people laugh) and author. She was born in 1922 in the State of Illinois and is still working over the age of 90. And she has been on television for 65 years, which is a “world record” (nobody else in the world has done for more years than she has).
Most people “associate” (think about in connection with) White with The Mary Tyler Moore Show, which we talked about in English Café 343, and The Golden Girls, but she has also been on many other shows, including her own “talk show” (a show where a host speaks with many different guests), The Betty White Show.
Many people admire White because she has continued to have a successful career as she has “aged” (become older). In Hollywood, many actresses face pressure to appear as young as possible, but White has “aged gracefully” (become older in an attractive way).
Almost 500,000 people joined an online “grassroots campaign” (an informal, mostly unorganized effort to make some change) to have Betty White host Saturday Night Live, which happened in 2010. She was 88 years old then, making her the show’s oldest host. That episode had very high “ratings” (a measure of the number of people who watched the show).
White has won many awards for her work, including six Emmy Awards and three American Comedy Awards. She has also won many awards for her “charitable work” (efforts to support nonprofit organizations that are trying to make society better) in “animal welfare” (how well animals are treated).