= 1714
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast English Café number 409.
This is English as a Second Language Podcast’s English Café episode 409. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at ESLPod.com. Download a Learning Guide for this episode – an 8- to 10-page guide we provide for all of our current episodes that gives you additional help in improving your English.
On this Café, we’re going to continue our ongoing series on American authors, American writers, focusing on Rachel Carson, who wrote an important book called Silent Spring. We’re also going to talk about one of the most popular board games of the past 50 or 75 years – “Monopoly.” And as always, we’ll answer a few of your questions. Let's get started.
We begin this Café with a continuation of our series on American authors. We’re going to talk today about Rachel Carson. Rachel Carson was a marine biologist – a scientist who studies life in the oceans, in the seas. Rachel Carson was also a conservationist. A “conservationist” is a person who tries to conserve or protect the natural environment, usually protect it from humans that might damage the environment. Rachel Carson wrote several books that were important in what became known as the environmental movement. The environmental movement attempted to and still attempts to protect the environment, to protect nature, to protect our oceans, and our forests, and our other what we might call natural resources.
Rachel Carson was born in 1907 in Pennsylvania, which is in the northeastern part of the United States. Carson grew up on a farm, and as a child she enjoyed writing stories about animals. In college she studied English and biology, and then in graduate school she studied zoology – the study of animals. She also studied genetics. So, she was a very bright, very intelligent young woman.
Later, she accepted a position. She went to work for a U.S. government agency, or organization, called the Bureau of Fisheries. A “bureau” (bureau) is a word we use to describe typically a government organization. We have, for example, the Federal Bureau of Investigation, or the FBI. This was the Bureau of Fisheries. The Bureau of Fisheries was, as you might guess, the organization in the government responsible for laws related to fishing – commercial fishing, fishing for business purposes. There is no longer a Bureau of Fisheries, I believe. It changed its name to something else now, but at the time it was called the Bureau of Fisheries, and Rachel Carson worked there as a writer. She wrote what we would call “copy,” which is another word for text that's used for some sort of publication. In this case, the text was for radio programs that talked about fish and plants and animals that live in the water.
Her copy was so successful that she began to write materials for other agencies, and soon she had a full-time job as an aquatic biologist. Remember, she studied zoology and biology when she was in college. Now she got a job as an aquatic biologist. The word “aquatic” (aquatic) relates to water. It comes from the Latin word “aqua” (aqua). Rachel Carson worked as an aquatic biologist, and combined that position with her talent as a writer to write a number of essays and articles about “underwater life,” we could call it. Over the next few years, she wrote at least three books: Under the Sea Wind, The Sea Around Us, and The Edge of the Sea. “Sea” (sea) here means the same as ocean. One of these books, The Sea Around Us, was actually made into a film, a movie. It won the Academy Award – what we more typically call the Oscar – for best documentary, but Carson wasn't very happy with it, and she decided not to have her other books made into movies.
Over time, she became increasingly interested in conservation, and she became involved in organizations such as the Nature Conservancy. Specifically, she got very interested in the use of “pesticides.” “Pesticides” (pesticides) are chemicals that are used to kill insects, usually because the insects are going to eat or harm the food that were growing. When we are growing food, we use the word “crops” (crops). “Crops” refers to food that you grow to eat, not just pretty flowers, for example. Those wouldn’t be crops. Crops refers to things that you grow that you are planning on eating: corn, wheat, tomatoes, broccoli – all of these could be considered crops. Usually the word is used, also, when we're talking about a large farm. Normally, if you just have a little garden in the back of your house, we wouldn’t refer to the food you grow as crops. “Crops” is usually used in a more commercial setting.
In any case, Rachel Carson became very interested in these pesticides, especially in the pesticide called “DDT.” “DDT” stands for a very long scientific term, which I am not going to attempt to pronounce, but basically DDT was used as a pesticide beginning in the late 1950s. People started using DDT to eradicate or kill, destroy, get rid of, a certain kind of ant. Carson began conducting a lot of research and talking to other scientists, trying to see what effect these chemicals, these pesticides, had on the humans and on the environment where they were being used.
Carson, in 1962, decided to take some of her research, some of the things that she had found out, and to publish a book called Silent Spring. The title, Silent Spring, refers to the fact that, according to Carson, these pesticides might hurt other animals such as birds, and if they did hurt the birds, if they killed the birds, then the birds wouldn’t sing and there would be no music, if you will, in the springtime, when you normally hear the birds. It would be instead a silent spring. It was a poetic way of capturing people's attention, getting their attention, about what Carson saw was a very serious problem in the use of DDT in American agriculture, in the growing of crops.
The book was very shocking for a lot of people. Many people believed, especially after World War II, that scientific progress was always a positive thing – that we were always moving forward in our scientific ideas and applications. There were a lot of people who didn't like Rachel Carson's book, but there were many more who found her research compelling. “To be compelling,” (compelling) means to be very interesting and, when we're talking about an argument, to be very convincing – something that makes you say, “Yes, I think that's correct.”
Carson argued that chemicals such as DDT were indiscriminate killers. The word “indiscriminate” (indiscriminate) means that the chemical didn't just kill the bad insects, the insects you wanted to kill – it killed almost anything that it touched. She described this concept as “bioaccumulation.” “Bioaccumulation,” according to Carson, was the idea that insects will eat the chemicals and they will have a certain amount of that chemical stay in their body. It will accumulate. It will be stored up, if you will. Since animals eat other animals, this chemical then would be passed on to other animals, such as a bird. The bird then would have this chemical inside it, and any animal that ate the bird would have that chemical, and so on.
Carson believed that eventually, of course, humans would eat some of these animals and they would get sick. They would get cancer. They would get other illnesses. Silent Spring faced a lot of criticism – a lot of people disagreed with the research that Carson presented. Nevertheless, it was a very popular book. Many people believe that this book, Silent Spring, launched or began the environmental movement of the 1960s which continues until this day.
In 1964, Carson died of a heart attack. She had also been suffering from cancer. She received many awards for her work. Many people thought that she did good work. Now, 40 years later, a lot of people, a lot of scientists, have looked at Rachel Carson's work and have found some problems with it. However, the basic idea is still with us. There are still a lot of people who are afraid of things that might poison animals and therefore hurt humans. This idea of being careful about using pesticides continues even to this day. That might be a good thing. That might not be a good thing, depending on your point of view. Certainly, one cannot deny that Rachel Carson, at least in the United States, had a great deal to do with starting people thinking about this issue.
Now let's turn to our second topic, which is one of the most popular board games in recent American history. A “board game” is a game that you play with two or more people. Usually, there is a physical board – something made out of a very thick kind of paper called “cardboard,” that you put in front of you, and then you use the board to play the game. The game we’re going to talk about today is called “Monopoly” (Monopoly).
“Monopoly” is a word that we use to describe a company that is the only company that makes and sells a certain kind of thing. Normally, you have lots of different companies who make similar items. You have what are called “competitors” – people who are making the same kind of thing. So, you have different phone makers. You have different carmakers. You have people who make different kinds of computers. No one company in those areas has a monopoly. None of them are the only company that sells that particular product. That's what the word “monopoly” means – when you are the only company, the only business, that is selling a certain thing.
“Monopoly” as a board game was first created back in the early 1930s, in 1934. The board game has the title “Monopoly” because it is based on the idea that one player, one of the people playing the game, is trying to dominate or monopolize the market. “To dominate” (dominate) means to control something, or someone, or some situation. “To dominate” means to have the most power and to be able to control everything because of that power. A “market” is a general term to describe any economic transaction or set of economic transactions. So, we could talk about the car market – what people buy, how much they buy. That buying and selling of cars would be the car market. The term “market,” then, is a general one to describe economic activity of buying and selling. “To dominate the market” would be to be the most powerful person in a certain kind of selling and buying. You may not have a monopoly in the market. You may not be the only person, but you're the most powerful person or the most powerful company that is in that particular market, in that particular area of buying and selling a certain thing.
As a board game, Monopoly is basically a large square. And around the square, you have 28 boxes which are called “properties.” A “property” is usually a piece of land with some sort of building on it, although technically “property” usually just refers to the actual land. In Monopoly, there are these different properties that each player has the opportunity to buy. When you start the game, you get a certain amount of money, and you can then use that money to buy and sell properties. What happens is that, as each player moves around the board, when they land on – when they stop on, a property that you own, they have to pay you money. They have to pay you rent, if you will.
What happens, of course, is that some people don't have enough money, and this causes them to go “bankrupt.” “To go bankrupt” (bankrupt) means you no longer have money to pay your bills, and therefore you have to leave the game because you ran out of money. The person who wins the game is the one who has the most money after everyone else goes bankrupt.
The fun thing about Monopoly is that it can last for many, many hours – even days, depending on how many people are playing it. I remember playing it when I was a boy. I used to love playing Monopoly. It would go for hours. My brothers and sisters and I would all play together. Well, not all of us, because there weren't enough pieces for all of us to play, but usually four or five of us would play together, and it could be a game that would last four or five hours, maybe even go over to the following day. Apparently, the longest game of Monopoly lasted 1,680 hours, or the equivalent of 10 weeks. I've never played a Monopoly game that lasted that long. What typically happens is, at the end, when people are getting tired of the game, they just decide that the person with the most money is the winner. But technically, according to the Monopoly rules, you're supposed to go until everyone but one person has lost all of their money or is bankrupt.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Steven (Steven) in China. Steven wants to know the meaning of some words that we use in describing cars, especially in describing cars that use a lot of gasoline. A lot of cars nowadays are very large and use a large amount of gasoline, or “gas” as we call it here. One of the words that we use to describe these kinds of cars is “gas guzzler.” “To guzzle” (guzzle) usually means to drink a lot, and to drink very quickly. “Don't guzzle your beer,” your friend might say. Don't drink it so quickly. “Guzzler” is someone who guzzles, or in this case something who guzzles – or that guzzles, I guess we'd say. The car is a gas guzzler. It drinks, if you will, a lot of gas. It uses a lot of gas very quickly. So, the most common expression to describe a big car that uses a lot of gas is a “gas guzzler.”
Interestingly enough, there really isn't a common term for the opposite kind of car. We may use a phrase such as “fuel efficient” to talk about a car that does not use a lot of gasoline. “Fuel” (fuel) is something that you use to create heat, or to create energy. In this case, it would be the gasoline. “Efficient” means you use it very effectively, only using as much as you need. “Fuel-efficient” cars would be cars that don't use a lot of gasoline. We could also say a “gas saver” (saver). “Saver” comes from the verb “to save,” which means not to use something. However, it's probably not the most common term.
Most people in describing their car will talk about its “gas mileage” (mileage). Someone may say to you, “What kind of mileage do you get with your car?” What they're referring to is the number of gallons that it uses for every mile that you drive, or really the more common calculation would be how many miles per gallon. In fact, you’ll even see that as an abbreviation: “MPG” (miles per gallon). How many miles can you drive on one gallon of gasoline? That's your mileage. People may talk about having good gas mileage or bad gas mileage. If you have good gas mileage, your car is very fuel efficient. It doesn't use a lot of gas. If you have bad gas mileage, we would say you have a gas guzzler.
Our next question comes from Jafar (Jafar) in Iran. The question has to do with the term “money order.” “Money order” is a noun referring to a kind of payment, a way that you can pay someone instead of using cash. Instead of giving them dollar bills or coins, you can use a money order. A money order is sort of like a check. A “check” is when you have money in a bank and you can write a piece of paper and give that piece of paper to someone, and that person can go to your bank and get their money. That's basically what a “check” is. A “money order” is a little different.
A “money order” is when you go to a bank – or you could even go to a post office, in the United States – and you give them cash. You give them money, typically. And they give you a piece of paper that's like a check, but we don't call it a check – we call it a money order. The reason we don't call it a check is probably because a check refers to when you have your own money in a bank, and the person gets the money from the bank. When you get a money order, you don't have to have what we call an “account” at a bank. You don't have to have your money sitting in the bank. You can just bring it to someone and they will give you this kind of check, which we call a money order, that the other person can use as if it were a check. The other person then can go to a bank and get their money.
In the United States, you can actually go to a post office, where you would normally mail a letter or a package, and buy a money order. It's possible. The maximum amount you can buy for a money order I believe is a thousand dollars, if you buy it at a U.S. post office. The thing that you have to remember about money orders is they are sort of like cash. If you lose the money order, you can't go back to the post office or back to the bank and say, “Oh sorry, I lost that one. Can you give me another one?” The answer will be “no.” If you lose a check, however, and nobody finds it, or if it burns up or whatever, there really isn't any loss. Your money will still be in the bank and you could write another check. But for a money order, once you have it, it's just like cash. It's just like a dollar bill, or a ten dollar bill. It's real money, if you will, that if you lose it, you no longer have that money.
Why do people have money orders? Well, there are a lot of people, poor people who don't have enough money to have a bank account, but they still have to send money to pay their bills. Most companies won't accept cash if you send it in the mail. You can't send them 200 dollars to pay your gas bill or your electricity bill. So, you have to send them a money order. They will accept a money order, and that's one reason why money orders are still popular in the United States. Here in Los Angeles, you can drive down the street and you will see small private companies that sell money orders, and you can stop and you can buy one of these money orders. Usually, however, it costs money to get a money order. So, you have to pay maybe two dollars or five dollars in order to get the money order.
Finally, Annie (Annie) in Brazil wants to know the meaning, or the reason, why I used a certain expression in one of our podcasts. This was from podcast number 832. One of the sentences in that podcast is, “I’d say we’re well on our way to establishing our new online store.” What is the meaning of the phrase “on our way to establishing,” and, more specifically, Annie wants to know why I use the “-ing” form of the verb “establishing” instead of just “establish.”
This is an interesting question because the word “to” (to) means a couple of different things in English, and it's easy to understand the confusion here about how we use a verb after the word “to.” Normally, if the word “to” appears before a verb form, it's what we call the “infinitive.” It's the “to” form, in fact, of the verb: “to go,” “to walk,” “to podcast,” “to drink,” “to walk” – all of these are infinitive forms of the verb. “To” plus the simple, if you will, form of the verb.
However, that's just one possible use of the word “to.” “To” could also be a preposition. “Where are you going?” “I'm going to the store.” “I'm going to give this to my friend.” That's what we call a prepositional phrase, when we use the word “to” plus some sort of noun.
There's a third use – if you want to call it a third use – of “to,” and that is in certain verbs, certain phrasal verbs that use what's called the “gerund.” A “gerund” (gerund) is a form of the verb that usually ends in “-ing” and is treated as a noun. It is considered a noun, or used like a noun, even though you form it from of a verb. There are certain phrasal verbs that always use the gerund, or -ing form, after the word “to” instead of the infinitive form. In the dialogue, we use one of those phrasal verbs, “on our way to.” “To be on your way to” means you are traveling toward or moving toward some goal, some objective.
In the dialogue, I said, “We were on our way to establishing our new online store.” “Establishing” is a gerund form of the verb, and it is the correct form. It would not be correct to say, “We are on our way to establish our new online store.” With certain kinds of phrasal verbs, you always use the “-ing.” There aren't a lot of these phrasal verbs. A couple of others you might hear are “look forward to.” “I look forward to talking to my brother on the telephone.” “Talking” is a gerund form of the verb. It is the “-ing” form. Another one would be “object to.” “I don't object to helping at the party.” “To object to” would be to disagree with. The phrasal verb “to adjust to” also uses a gerund. “I have to adjust to being at home.” That means I need to get used to being at home. In fact, there's another phrasal verb: “to get used to something.” There are other phrasal verbs that fall into the same category, but those are some of the more common ones.
If you have a question, common or uncommon, you can email us. Our email address is eslpod@eslpod.com. From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2013 by the Center for Educational Development.
Glossary
conservationist – a person who tries to protect the national environment from the damaging influence of humans
* Benoit works as a conservationist, trying to save forests and wetlands.
environmental movement – efforts to protect the planet and all living things and beings
* Getting people to recycle is one of the goals of the environmental movement.
pesticide – chemicals used to kill insects that destroy plants and crops (plants that farmers grow to sell for food or clothing)
* If you don’t want to eat fruits and vegetables with pesticides, buy organic products.
to eradicate – to kill, destroy, and get rid of completely; to put an end to something
* These researchers are trying to find ways to eradicating diseases of the eye.
compelling – causing people to become interested and to give their full attention; making people want to pay attention and listen
* The movie was so compelling that no one heard the doorbell.
indiscriminate – done at random, without carefully thinking
* You can’t fire all of the workers in this department indiscriminately! Some have worked here for over 25 years.
bioaccumulation – the idea that insects that eat a small amount of chemicals have a certain amount of it in their body, which is found in increasing amounts in the next level of animals that eat those insects
* By the time food reaches our tables, we may be eating foods with a lot of chemicals due to bioaccumulation.
board game – a game played by two or more people, with a flat piece that unfolds into a large square or rectangle placed on a table and the players move small pieces or cards across that surface as they play the game
* We can’t play this board game unless we have four or more players.
to dominate the market – to become the business that has control of most of the products of a certain type being bought and sold, or services being provided
* Big grocery stores try to dominate the market in each city, causing small, family-owned stores to close.
property – buildings or land owned by people or companies
* When I die, all of my property will go to my children.
dice – a small block with a different number of dots on each side, from one to six
* Roll the dice to see who gets the highest number and will be the player to start the game.
to go bankrupt – to not have enough money to pay one’s bills; to make a legal declaration (statement) that one cannot pay one’s debts
* Workers demanded higher salaries, which the company couldn’t pay, causing the company to go bankrupt.
gas guzzler – a car that uses a lot of gasoline; a vehicle that uses a lot of fuel
* Jerome traded in his gas guzzler and got an economy car that uses very little gas.
money order – a printed statement of payment issued by a bank, post office, or other authorized business to be paid in a specific amount
* Lorenzo paid all of his bills using money orders because he didn’t have a checking account.
What Insiders Know
The Sims
“The Sims” is a “life simulation” video game that allows players to select a character to represent them in the game, putting their own personality into that character. A “Sim” refers to a “simulation,” which is a representation of someone or something, making it look and/or act like that thing. The game was first “released” (made available for sale) in 2000 and it became a very popular video game.
In this game, players live a life just like they would in real life, “interacting” (seeing, speaking to, and doing things with) other players in the game. The game begins when a player creates a Sim and has their Sim select a house to live in. The player can even build a house for their Sim and buy things for them in a “build” and “buy” “mode” (option). How Sims interact with each other also depends on the users themselves. They can do everything a person would do in real life, such as eat and sleep. They can meet other Sims, go on “dates” (romantic meetings), get married, and have children. They can even die in the game.
The Sims was so popular that it was named the top-selling video game in history, selling 16 million “units” (items). The game released seven “expansion packs.” Each expansion pack was not a “sequel” (continuing story with the same characters) but improved the quality and content of the game.
There have been two Sims sequels and several “spin-offs” (new products or stories using only one or a few of the characters from the original). As of 2011, the entire Sims “franchise” (line or group of products sold under the same or similar name) has sold over 125 million units, earning $2.5 billion.