= 1737
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 432.
This is English as a Second Language Podcast’s English Café episode 432. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Improve your English even faster by becoming a member of ESL Podcast and downloading a Learning Guide for these episodes.
On this Café, we’re going to talk about presidential libraries and a very famous story, “The Legend of Sleepy Hollow.” And, as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café talking about presidential libraries. When I say “presidential,” I’m referring to the presidents of the United States. Normally, when we think about a library, we think about a place where you can go and look at books or, nowadays, I guess look at computers. Presidential libraries are a little different, although they are similar to a regular library in the sense that they have documents there that you can go and look at.
The story of U.S. Presidential Libraries is somewhat interesting, and fairly recent. Before 1939, when presidents left office, or stopped being president, they typically sold, gave away, or even destroyed the papers and materials from their time as president. This included photographs and recordings and, perhaps, anything they didn’t want other people to find out about that they did when they were present.
President Franklin D. Roosevelt believed that this was not a good thing to do. He was our president in 1939. He believed that the papers and materials that were created during a president’s term, or time in office, were important to American historians, to the history of the United States – to preserving the history of the United States. Since they were important, Roosevelt believed that they should be saved and kept somewhere so that the American people could see them.
So, during Roosevelt’s third term in office, from 1937 to 1941, he began collecting his papers and materials. He decided to donate the papers to the U.S. government. “To donate” (donate) means to give something to someone without having them pay for it – “for free,” that is. Roosevelt said that he wanted to donate his papers and materials of his presidency so that they could be preserved, or kept safe and in good condition for a long time, to benefit the American people and future historians.
Not only did he decide to donate his papers and materials, he also raised money, or collected money, to build a building to keep the papers in. He even included some of his own money. Roosevelt gave the government a part of his estate, or the money, land, and other possessions you own when you die that are typically given to your family or whomever you choose. Roosevelt gave part of his estate to the government so that there could be a presidential library for him. Part of the money was also raised, or collected, by the friends of Roosevelt.
President Harry Truman was Roosevelt’s vice president, and the president who succeeded, or came after, Roosevelt. Franklin D. Roosevelt, or “FDR” as we more commonly call him, died in his fourth term of office, during World War II, and the vice president (in the United States) becomes president if the president dies. The vice president for Roosevelt was Harry Truman. Truman also believed that the presidential papers should be saved for the American people, and like Roosevelt, he donated his papers and also raised money to build a library to keep these papers in.
After Truman and Roosevelt donated their papers and established presidential libraries, the Congress of the United States, our elected representatives, decided in 1955 to pass, or approve, the “Presidential Libraries Act.” The word “act” is just another word for “law.” This law said that the government would take care of these libraries, although the money for the libraries had to come from someone other than the government. The government wasn’t going to give any money to build the actual library, but the government would run the library after it was built.
The act also suggested, though it did not require, that future presidents do what Roosevelt and Truman did, and donate or give their papers to the government for the presidential library. In 1978, however, Congress decided to pass another law – the “Presidential Records Act.” This act said that all of the papers and materials a president creates or uses during his or her presidency don’t belong to him; they belong to the American people.
Before 1978, presidents believed that the material was theirs – their personal property that they could, if they wanted to, donate to the government or donate to some other place. However, this act changed that. It meant that from 1978 on, presidents didn’t have to donate their papers and materials to the government, because the government already owned them.
The most recent change to the presidential libraries came in 1986 with another law, this one called the “Presidential Libraries Act of 1986.” This act required that all presidential libraries be funded, or paid for, with private endowments. An “endowment” (endowment) is a large amount of money that an organization has to pay for everything they need in the future. The “endowments,” in other words, help pay to run the library so the government doesn’t have to pay as much money to run the libraries and keep them operating.
You may ask, “Well, how many presidential libraries are there?” Well, there are 13 presidential libraries. There are libraries for Presidents Hoover – who was the president before Roosevelt – Roosevelt, Truman, Eisenhower, Kennedy, Johnson, Nixon, Ford, Carter, Reagan, George H. W. Bush – the first George Bush – Bill Clinton, and George W. Bush – the second Bush president.
The libraries are located in different cities in the United States. Typically, they are put in the cities or states where the person is from or where the person is most associated with. For example, the John F. Kennedy Library is in Massachusetts, in Boston. That’s where Kennedy grew up. Other libraries are located in other places associated with those presidents. Bill Clinton’s library, for example, is in the capital of the state where Clinton was governor – it’s located in Little Rock, Arkansas.
The George H. W. Bush – the first Bush – library is located at Texas A and M University. It’s become more popular to find a University that would want to have the library associated with it, and that’s what the first President Bush did. His son George W. Bush also put his presidential library at a university, also in Texas. Ronald Reagan’s presidential library is right here in southern California. Reagan was the governor of California and had lived here for many years, although he was not born in California.
We also have the Richard M. Nixon Presidential Library located in California. Both of these are within about an hour’s drive of where I live. They’re both located in Southern California. I have to say, I’ve never been to either presidential library, but I will make a trip. I will definitely plan on going. The libraries are more than just libraries. They’re also, in some ways, museums for people to go and look at. Franklin Roosevelt’s library is in New York. Jimmy Carter’s library is in Georgia. President Ford’s library is in Michigan, I believe, and let’s see, Truman’s library is in Missouri.
Each library contains not just the memos, or messages, letters, and documents written by the presidents while they were in office, while they were serving as president. They also include papers that explain the different decisions that they made while in office. The libraries of more recent presidents have included emails and digital images, as well as videos.
Each library also includes certain, what we would call, “artifacts” (artifacts). An “artifact” is some object that the president used or perhaps was given while president. For example, the Kennedy library has signs and buttons from Kennedy’s presidential campaign – the effort to get him elected as president. You can also see other famous objects that presidents owned or had used when you visit these presidential libraries. The libraries are, of course, a great source for historians who want to learn more about what happened during those presidencies.
Our second topic is a very famous story written by a very famous author in the United States. The story is “The Legend of Sleepy Hollow,” and the author is Washington Irving. A “legend” (legend) is a story that has been told, typically for many years, about something in the past that probably didn’t actually happen. “The Legend of Sleepy Hollow” was published in 1820 in a collection of stories written by one of the most famous nineteenth-century American authors, Washington Irving.
The story is set, or takes place, in a small town in New York called “Sleepy Hollow.” There is an actual town of Sleepy Hollow. It’s about 30 miles, or 48 kilometers, north of New York City. Washington Irving lived in a small town that was close to Sleepy Hollow. A “hollow” (hollow) is a small valley, a space in between two hills. “The Legend of Sleepy Hollow” is about a ghost. A “ghost” is a vision, or image, of a dead person who somehow comes back to life and wanders around or moves around the world, often in the places where they died.
“The Legend of Sleepy Hollow” is about the ghost of a man who was killed during the American Revolutionary War. Remember, the American Revolutionary War took place in the late eighteenth century, and this story was written in the early nineteenth century. The farmers that live in this small town or near it are people who descended or had families that originally were Dutch – from the Netherlands or Holland. The people in the town like to tell stories about ghosts, and one of the stories is about a soldier who was killed during the American Revolution. The soldier lost his head, literally.
The ghost doesn’t have a head because this poor German soldier was killed by a bullet to the head. Well, because the man doesn’t have a head, the ghost goes around at night trying to find his head, and of course, if you happen to meet the man, you might not survive, yourself. You might die as well. In the story, there is a schoolteacher by the name of Ichabod Crane, who falls in love with one of his students, a high school student, we guess. She was very beautiful, and she was the daughter of a very rich farmer. Ichabod decides he wants to marry this beautiful woman, whose name is Katrina.
However, there’s another man in town, named Brom, who also wants to marry Katrina. Well, now we have a problem. Brom is a very strong and good-looking man who likes to play pranks. A “prank” (prank) is a joke that you play on someone else, usually to make them look foolish or stupid. This is exactly what Brom does. He tries to make Ichabod look stupid so that Katrina will not fall in love with him. One night, coming back from a party, Ichabod Crane hears what he thinks is the headless horseman. Now, is it really the headless horseman, the ghost, or is it just Brom playing a trick on him?
Ichabod doesn’t want to be another victim, another person hurt by the headless horseman, so he runs away. Later, they find his saddle. A “saddle” (saddle) is what you use to sit on a horse. I don’t want to tell you the end of the story and what happened to Ichabod Crane, or even if we know what happened to Ichabod Crane, but it’s a wonderful example of an early American short story, based upon perhaps stories that were told in small communities such as the place where Washington Irving lived and places like Sleepy Hollow.
“The Legend of Sleepy Hollow” is not only a famous story in English. It is also been made into, of course, a movie. In 1949, the Disney company made it into a cartoon, and much later, in 1999, it was made into a movie starring Johnny Depp, who looks a little like me, I think. In 2013, they made a television show called Sleepy Hollow, although it wasn’t really the same story. They use some of the characters, some of the people from the original Sleepy Hollow story.
If you like ghost stories, you might like seeing the movie or perhaps reading the original story. Remember, I was not actually in the movie of “The Legend of Sleepy Hollow,” it’s actually Johnny Depp. Even though, again, he looks a lot like me.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Marcel (Marcel) in Brazil. Marcel wants to know the difference between the word “people” and “peoples.” “People” is normally a word we use as the plural of more than one person, more than one individual. “I met five people last night.” “People” is plural. So, it’s a little confusing when you hear a word that is normally plural with an “s” on it.
Here’s why. The word “people” is also used to describe the citizens of a area or of a country. We could talk about “the people of the United States” or “the people of Canada.” When we use “people” that way, it actually has a singular meaning. It means something closer to the word “group” – the group of people that live in Canada, the group of people that live in the United States. And so, it’s treated as singular. Now, when we talk about “peoples,” we’re talking about more than one group of people who live in a certain area.
So, we could talk about the “peoples of North America.” That would include the people of Canada, the people of the United States, the people of Mexico, and so forth. We could talk about the “English-speaking peoples.” That would include the people of Great Britain, Australia, the United States, New Zealand, Canada, and so forth. So, you have to keep in mind the two different meanings of “people,” both its plural meaning and its singular meaning, when referring to a group of individuals from a particular area.
Our second question comes from Vichet (Vichet) in Cambodia. The question has to do with difference between “official” and “officer.” When do we use the term “official,” and when do we use the term “officer”? The word “officer” (officer) is usually used in American English to refer to people who work for either the police department or for the U.S. government in the armed forces: the Army, the Navy, the Marines, the Air Force, and so forth.
Normally, we think of “officer” as being someone who works in one of those kinds of government organizations that are concerned with protection and security. We have “police officers.” We have “officers” in the military. In the police, most people who work for the police are police officers. However, in the military, the officers are the leaders, the people who are in charge or in command: the generals, the admirals – those are all “officers.” Similarly, we can use the word “officer” in talking about the leaders of a corporation: the president, the vice president, the treasurer, the secretary. These are all positions in a corporation that we would also refer to as “officers.”
The word “official” (official), when used as a noun, also refers to someone in a position of authority, although we can use it for almost any kind of organization, especially government organizations. You could talk about the “officials” at the justice department, or the “officials” in the agricultural division. These are people who are in charge of, or leaders of, different government organizations.
It gets confusing sometimes because you can refer to, for example, the leaders in a military organization or any police department by that same term: “official.” You can talk about the “officials of the police department” – these would be the leaders of the police department. So, it can be a little confusing. In general, when someone just uses the word “officer,” we’re typically talking about a “police officer.” However, the term can be used, as I’ve mentioned, in many other circumstances as well, including in the business world when we’re talking about the leaders of a corporation or large company.
Finally, Oumar (Oumar), now living in France, originally from Senegal. Oumar’s question has to do with two different verbs: “to continue” and “to carry on.” These are both similar verbs in meaning, but there are some small differences. Let’s talk about those. “To continue” (continue) means to not stop some action or task that you are doing. “I’m going to continue working at my computer.” “I’m going to continue taking these pills for my allergies.”
When we use “continue” in this way, as a verb, the word that comes after “continue” usually ends in an “ing.” It’s what we call a “gerund.” So, “I’m going to continue eating” (eating). We don’t say, “I’m going to continue eat.” It is possible, however, to use what’s called the “infinitive” form of a verb after “to continue”: “I’m going to continue to eat.” “I’m going to continue to work at my computer.” “I’m going to continue to take these pills for my allergies.” So, “continue” can be followed either by what we call a “gerund” – the “ing” form of a verb, or by the “infinitive” – the “to” form of a verb.
“To carry on” means to continue also. It’s a phrasal verb with the preposition “on” at the end. That means that, unlike with the verb “to continue,” you can’t use an infinitive form of the verb after “to carry on.” You can’t say, “I’m going to carry on to speak.” You can only use the gerund form. You can only say, “I’m going to carry on speaking.” “I’m going to carry on walking,” or whatever it happens to be.
If people know what you’re talking about, you can even use these verbs without anything after them. If someone says, “What are you going to do at the university?” You say, “Well I’m going to continue for three more years.” I didn’t use an “ing” or an infinitive form after “continue.” I gave the amount of time I’m going to continue, and the person knows that I’m talking about studying or being a student.
Similarly, you can say “to carry on” without putting anything after the word “on.” You could say, “The boss said we should carry on,” or “The boss said that we should carry on with our work.” Notice, there I put a prepositional phrase after “on,” even though “on” is already a preposition. Both verbs can also be used in a command, in what we would call an “imperative.” If someone, for example, were telling you a story, you could say, “Please, continue,” meaning continue telling me your story.
“Carry on” can also be used this way. However, it sounds a little bit more formal. It’s often associated with the military. It means to continue doing what you’re doing, but it sounds a little bit more formal. You would probably not want to say to a friend or a colleague, “Carry on.” It sounds like you’re the boss. You’re in authority. It’s very formal sounding, or at least not appropriate, typically, in most situations when you really mean, “Continue.”
If you’re not sure which one to use, use “Continue” and everyone will understand what you’re saying. You also won’t make it seem as though you were an officer in the military giving someone orders.
If you have a question or comment, you can continue to send them to us at eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2013 by the Center for Educational Development.
Glossary
term – the number of years that a person serves as president; the amount of time a person is allowed to work in an elected or appointed job
* Today, United States presidents are only allowed two terms or a total of eight years in office.
to donate – to give something such as objects or money away for free, usually to help others
* Amir went through his closet and donated the clothes that he doesn’t wear anymore.
to preserve – to keep something in good condition and safe for many years
* Masha’s grandmother preserved her wedding dress so that one day, Masha could wear it at her own wedding.
estate – the money, objects, and land that a person owns when he or she dies
* Thomas had a large estate that included two houses and over $3 million.
endowment – an account held by private institutions like universities or libraries that people give money to that helps pay for creating or maintaining a building or other things
* Many former students of private universities give money to their school’s endowment to help support the school.
artifact – an object that has cultural or historical importance
* One of the many artifacts Giovanni saw on his trip to Egypt was a gold statue of Ra, the ancient Egyptian god of the sun.
legend – a story that is told for many years by many generations of people that sounds true but may not have actually happened
* The legend of Yuko’s great-grandfather, the fisherman, said that he was the best fisherman in town and had once caught 100 fish in two hours.
ghost – a vision of a dead person or animal that seems real to the person who sees it
* Some people believe that ghosts of previous owners live in old houses.
to descend – to come from or be related to a group of people
* Nim descended from Irish farmers who had moved to the U.S. in the 1800s.
prank – a mean joke or trick that someone plays on another person to make them look silly or to embarrass them
* James played a prank on Yoshi when he changed the time on Yoshi’s clock to make him think he was late for work.
saddle – the seat, usually made of leather (dried animal skin), a person sits on when riding a horse
* The saddle was tied very tightly around the horse to be sure that it would not fall off when Sanjay was riding.
victim – a person who is hurt by another person, usually while committing a crime
* Solomon was the victim of a robbery. Someone entered his home and took his television.
people – used to describe human beings collectively or as a group; plural of “person”; citizens of a country
* This museum exhibit is focused on the early peoples of the Americas.
officer – a person who holds a position of authority in the military, the police, or a large organization, such as a company
* The President is meeting with top military officers this week to discuss international security.
official – a person who holds a position in government or in large organizations
* An official of the U.S. Labor Department announced the new unemployment figures.
to continue – to go on; to not stop with a particular action, task, or condition
* We can’t continue paying for cable TV and Internet services if we don’t even have enough money for the rent.
to carry on – to continue doing, pursuing, or moving
* These are difficult times, but we just need to carry on and try to do our work.
What Insiders Know
War Memorials
A war memorial can be a building, a museum, a “plaque” (a flat carving, usually attached to a wall or the outside of a building) or any other thing that “commemorates” (remembers an important event or time period) or celebrates those who died or were injured in a war. Many U.S. war memorials “serve as” (are used for) a meeting place for special holidays such as Memorial Day, a national holiday honoring those who fought in the military. War memorials are usually found in the middle of a park or a “plaza” (open space surrounded by buildings) to make it “accessible to” (easy to get to) the public.
Two of the most visited war memorials can be found on the National Mall in Washington D.C. The National Mall is an open area with grass surrounded by museums and other important buildings.
The U.S. National World War II Memorial consists of 56 “pillars” (a tall structure, often used to hold up a part of a building) and two small “arches” (curved structures over one’s head) that surrounds a “fountain” (structure in a body of water through which water comes out) and a plaza or open area. It was opened to the public on April 29, 2004, two days before Memorial Day, on May 29, 2004, The U.S. National World War II Memorial was “dedicated by” (officially opened by) President George W. Bush. About four to five million visit the Memorial each year.
The Vietnam Veterans Memorial was built in Washington, D.C. to honor those who served in the Vietnam War. The Vietnam Veterans Memorial consists of three main parts: The Soldier’s Statue, the Vietnam Women’s Memorial, and the Vietnam Veterans Memorial Wall. The Memorial Wall has the names of the nearly 60,000 who were “killed in action” (killed while fighting) or “missing in action,” those who disappeared while fighting. The Memorial was completed in 1982 and has about three million visitors each year.