= 013
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


- (013.) Other experiments revealed (v.)  slight variations 变化，变动 in the size, number, arrangement 排列；布置, and interconnection 互连；相互连接 of the nerve cells, but *as far as* 就……而言,就……来说 _psychoneural 精神神经的 correlations_ 心理神经关联 were concerned 有关，关于；涉及, `主` the obvious similarities of these _sensory fields_ 感觉区域 to each other `谓` seemed much more remarkable (a.)引人注目的，非凡的 than any of the minute 微小的；细微的 differences. +


'''

- (013.) Other experiments revealed slight variations in the size, number, arrangement, and interconnection of the nerve cells, but as far as psychoneural correlations were concerned, the obvious similarities of these sensory fields to each other seemed much more remarkable than any of the minute differences.

其他实验揭示了神经细胞在大小、数量、排列和相互连接方面, 存在的细微差异。然而，就"心理神经关联"而言，这些感觉区域之间明显的相似性，似乎比任何微小的差异,都更加值得关注。

本句的意思是: 与其过分关注不同脑区、不同功能的微小差异，不如致力于发现那些支配整个大脑工作的、深层次的、具有普遍性的组织原则（即相似性）。

.Psychoneural Correlations 心理神经关联

指的是**特定的心理状态**、过程或功能（如看到红色、感到疼痛、产生一个想法）, 与特定的"*大脑神经活动模式*"之间的对应关系。

当我们“看到一张脸”时，大脑梭状回面孔区的神经元, 会强烈放电。*这种"神经活动模式"与识别人脸这个"心理体验"之间的对应关系，就是一种 psychoneural correlation。 具体来说，就是寻找心理现象的 “神经相关物”。*
