= 032
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''



- (032.) The hydrologic (a.) 水文的  cycle 水文循环, a major topic in this science, is the complete cycle 完整的循环 of phenomena 后定说明 through which water passes, *beginn##ing## as* _atmospheric (a.)大气（层）的 water vapor_ 水蒸气, *pass##ing## into* _liquid and solid form_ as precipitation 降水, thence (adv.)从那里；因此；从那时起 *along and into* the ground surface, and finally again *return##ing## to* the form of _atmospheric water vapor_ 大气水蒸汽 by means of 通过，借助于 evaporation 蒸发 and transpiration 蒸腾作用. +


'''

- (032.) The hydrologic cycle, a major topic in this science, is the complete cycle of phenomena through which water passes, beginning as atmospheric water vapor, passing into liquid and solid form as precipitation, thence along and into the ground surface, and finally again returning to the form of atmospheric water vapor by means of evaporation and transpiration.

水文循环，作为这门科学的一个主要课题，是水所经历的完整现象循环：它以"大气水蒸气"的形式开始，通过降水转变为液态和固态，然后沿着地表或渗入地下，最终通过蒸发和蒸腾作用再次回到大气水蒸气的形式。

水文循环，水利科学中的主要课题，是一个（水需要经历
的）完整的循环过程，循环在开始时作为大气中的水蒸气，再进入液体
和固体状态作为降雨或降雪，然后流过并进入地表，并最终通过蒸发和
气化作用重返气态的水蒸气的形式。

- beginning 开始的一系列分词, 都是修饰主语 The hydrologic cycle 的，分别是 beginning / passing / passing / returning。

- thence along and into the ground surface 这里有省略了 passing. 完整的句子是: thence *passing (v.) along and entering into* the ground surface.


