= 1676
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 371.
This is English as a Second Language Podcast’s English Café episode 371. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Our website is eslpod.com. On it, you can visit our ESL Podcast Store which has some additional courses in business and daily English I am absolutely sure you will enjoy.
On this Café, we’re going to have another one of our “Ask an American” segments, where we listen to a native speaker talking at a normal rate of speech – a normal speed. We’re going to listen to the speaker and explain what she is talking about. Today we’re going to talk about Asian Americans – immigrants who come from countries in Asia to the United States or their children. We’re going to learn a little bit more about Asian immigration to the United States and what it means for this country. And as always, we’ll answer a few of your questions. Let’s get started.
Our topic on this Café’s “Ask an American” segment is Asian immigrants. We’re going to listen to a woman named Cary Funk. She’s a senior researcher. She’s someone who does research investigation into this area. There was a recently, in 2012, published report about Asian Americans called “The Rise of Asian Americans.” The “rise” (rise) indicates the increase, in this case, of something or when some person or some group becomes popular or famous or more powerful. We could talk about the rise of a presidential candidate, someone who becomes famous and powerful. Here, we’re talking about largely the increase in the number of Asian immigrants to the United States.
We’re going to start by listening to Ms. Funk talk about the characteristics of Asians who are immigrating to the United States. Try to understand as much as you can and then we’ll go back and explain what she said. Let’s listen.
[recording]
“There is definitely a very highly skilled, highly professionalized immigration, what some have called the 'brain drain.’ But you also have, kind of a more working-class, low-skilled immigration, folks with not a whole lot of education coming as well.”
[end of recording]
In talking about Asian immigrants, Cary – Cary Funk – says that “There is definitely or certainly, a very highly-skilled, highly professionalized immigration.” “Highly-skilled” means having the ability to do different things, especially professionally for a job. She uses the word “professionalized.” “Professionalized” comes from the word “profession” (profession). A “profession” is a job. “To be professional” means to do a very good job, a job that you would expect from someone at that particular level or with those particular responsibilities.
“Professionalized” – I think, she’s referring here more to levels of education, what we sometimes call the “professions.” These are certain jobs such as engineers, computer programmers, doctors, lawyers, and other professions that require a higher level of education. Many of the immigrants from Asia to the United States have a much higher level of education than immigrants from other areas. That’s very clear when you look at the actual statistics – the numbers.
Ms. Funk says that some people refer to this professionalized immigration as the “brain drain.” “Brain” (brain) is what is in your head. It’s what you think with. Most people have a brain. My neighbor…eh? “Drain” (drain) is when liquid moves through a small hole, such as in your kitchen sink or your bathroom sink, or your bathtub. When the water goes down into the pipes – when the water leaves, we say it “drains.” “To drain,” then, means to take something out of somewhere else, in this case, liquid. “Brain drain” is when a country or an area – a region – loses the best minds. It loses the most educated, most skilled workers. They leave their country and they come to the United States. So, they go to another country. So the professionalized immigration from Asia is in many ways a “brain drain” for those countries from which the immigrants came.
Cary says, “At the same time, we see this ‘brain drain,’ we see another kind of Asian immigration.” She says, “This is a kind of working class, low skilled immigration.” “Working class” refers to people who perform physical labor, who actually use their hands, their legs, their bodies to do something that requires difficult physical work. Sitting at a computer is not difficult, physical work. “Working class” refers to those who are working in factories, on farms, in mines where they dig out coal, for example – those are all working class positions.
She refers to these as “working class, low skilled immigrants.” If “high-skilled workers” are those with a lot of abilities, a “low-skill worker” would be one who doesn’t have a lot of abilities. She says, “You also have kind of a more working class, low-skilled immigration, folks with not a whole lot of education coming as well.” The word “folks” (folks) is a very common word in conversational English, or at least, it used to be. It refers simply to people. We might more commonly now say, “guys” (guys). But “folks” can refer to people in general. It can also refer specifically to ordinary people, not rich people, not famous people – “ordinary folks,” we might say, “ordinary people.” “Folks” can also refer to your parents. “My folks are living in Minnesota,” or “My folks are going on vacation next week.” “Folks” is your father and your mother.
Now let’s listen again, as Cary talks about these different types of Asian immigrants.
[recording]
“There is definitely a very highly skilled, highly professionalized immigration, what some have called the 'brain drain.’ But you also have, kind of a more working-class, low-skilled immigration, folks with not a whole lot of education coming as well.”
[end of recording]
Next, we’re going to listen to Cary talk about Asian immigrant students, the different kinds of students there are, and how we should think about them. Let’s listen.
[recording]
“When we think of the Asian American student, whether it is pre-collegiate or in college and beyond, we should have an understanding of their, kind of, multiplicity of the Asian American student, not only by national origins, whether of themselves or their parents, for example.”
[end of recording]
Cary starts by saying, “When we think of the Asian American student, whether it is pre-collegiate or in college and beyond.” Cary uses the word “pre collegiate.” “Collegiate” (collegiate) means or refers to college, the university, where you go after high school, typically for four years or in my case, eight. “Pre” (pre) means before. So “pre-collegiate” means before college, which would probably, in most cases, be referring to kids who are in high school, those who are between the ages of, say, 13 and 18, or 14 and 18. That’s “pre-collegiate.” So, she’s talking about both students who are not yet in college or those in college and beyond. “Beyond” might be graduate school, in this case.
She says, “When we think of these students, we should have an understanding of their, kind of, multiplicity of the Asian American student.” Like a lot of cases when someone’s talking, it’s not always a complete, perfectly grammatical sentence. That happens to me every day. Cary says, “We should have an understanding of the multiplicity of Asian American students.” “Multiplicity” (multiplicity) comes from the word “multiple,” which means many. Here, she means there are many different kinds of Asian American students. They’re not all the same. That’s why she says, we need to have an understanding of their multiplicity “not only by national origins, whether of themselves or their parents, for example.” “National origins” refers to the country where you, or your parents, or your grandparents or someone in your family, came from as an immigrant.
We speak a lot about national origins in the United States since we have people from so many different countries, especially in a place like Los Angeles. My “origin” is the place I am from. So, I might also say, “I’m from Minnesota.” That’s my place of origin. If I were to talk about my national origin, it would be Ireland and Germany, mostly from Ireland. That’s where my ancestors were from.
Well, not all Asian Americans come from the same country. And even so, knowing the country is not always enough information to understand the student and their problems, whether it’s of their parents or of themselves. Let’s listen to Cary one more time.
[recording]
“When we think of the Asian American student, whether it is pre-collegiate or in college and beyond, we should have an understanding of their, kind of, multiplicity of the Asian American student, not only by national origins, whether of themselves or their parents, for example.”
[end of recording]
Finally, Cary’s going to tell us about how the U.S education system – our schools here in the U.S – should respond to the increasing number of Asian Americans. Let’s listen.
[recording]
“I think the educational system has tried to be more aware of the changing demographics and to be more culturally competent. And when I say culturally competent it gets back to the other point that I was raising earlier. We’re also talking about socio-economic differences in Asian immigration to the United States. So it’s important for us not to think of every child who is Asian American as having parents who work for a Fortune 500 company and being English-speaking and highly-educated in that way.”
[end of recording]
Cary says, “I think the educational system has tried to be more aware of the changing demographics and to be more culturally competent.” She thinks the educational system – the school system – has tried to be more aware of the changing demographics. “To be aware of” means to notice, to pay attention to. “Demographics” (demographics) here refers to the characteristics of the people. “Demographics” is a study of people and the characteristics of a certain population, usually involving some sort of statistical or numerical information. It could be information about their sex, or who’s male or who’s female, age, race, skin color, national origin and more. All of these would be topics you would find in the study of demographics. She says that the school system is more aware of the changing demographics, the fact that students in the schools are changing in terms of their backgrounds, their characteristics, and that the schools are becoming more culturally competent. “To be competent” (competent) means to be able to do something, to have the skills to do something. “Culturally” refers to understanding the different ways that people behave and the different things they believe in different cultures in different areas in the world. So, to be “culturally competent” means to have an understanding of the different cultures of your students. At least, that’s what I think she’s talking about here.
Cary then says that when she says culturally competent, “it gets back to the other point that I was raising earlier.” She’s saying that this discussion of cultural competency gets back to, or refers to, another point, another idea that she was talking about, that she was “raising” earlier. She says, “We’re also talking about socio-economic differences in Asian immigration to the United States.” “Socio-economic” refers to how much money a family makes, what their social position is in a society or in an area, what other people think of them. Their education is involved in that. “Socio-economic” is a term that we use a lot in talking about schools to refer to the backgrounds, the economic backgrounds of our students – what their parents do for a living, where they live, what kind of ideas are communicated within the family about economics and work. All of these things are related to socio-economics, but the most important thing is how much money do they have. The “economic” part is more important than the “socio” part, typically.
She says, “It’s important for us not to think of every child who is Asian American as having parents who work for a Fortune 500 company and being English speaking and highly educated in that way.” The general perception that a lot of people have of Asian Americans in the United States is that they are well educated, and that their children do very well at school. This is, in general, true, but what Cary is talking about here is that that’s not true for all Asian Americans, that there are Asian Americans who don’t come from what she calls “Fortune 500 companies,” or whose parents don’t work for a “Fortune 500” company. “Fortune” is the name of a famous business magazine in the United States. And the Fortune 500 refers to the 500 biggest companies in the U.S. She’s saying here that not every Asian American child has a parent who works for a big company and makes a lot of money, and is English speaking and highly educated. Statistically, it’s true that most Asian immigrants are more educated than non-Asian immigrants. But, as Ms. Funk is pointing out here, that’s not true for all students, and so schools have to recognize that here are differences in the Asian American population.
Now let’s listen one last time as Cary talks about this topic.
[recording]
“I think the educational system has tried to be more aware of the changing demographics and to be more culturally competent. And when I say culturally competent it gets back to the other point that I was raising earlier. We’re also talking about socio-economic differences in Asian immigration to the United States. So it’s important for us not to think of every child who is Asian American as having parents who work for a Fortune 500 company and being English-speaking and highly-educated in that way.”
[end of recording]
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Domenico (Domenico) in Italy. Domenico wants to know the meanings of three different verbs: “to note,” “to notice,” and “to notify.” Let’s begin with “to note” (note). As a verb, “to note” means to write down, usually in order to remember something. “I need to note the time for my next doctor’s appointment.” I need to write it down so I don’t forget. “To note” can also mean simply to observe, to realize what is happening. Here, it means the same as “notice.” “Note the beautiful colors used in this painting.” Pay attention to them, look at them, be aware of them – that’s what we’re saying in this definition of note. “Note” can also be a noun. It can mean a short written reminder of something. We often, in school, tell our students to take notes. “To take notes” means to write down the important information of what the teacher is saying. Of course, kids do take notes and then they write notes to their friends and pass those notes or give them to their friends. Of course, those aren’t usually about what the teacher was talking about.
The verb “to notice” (notice) means to be aware of, to realize. It’s similar to the second definition of note that I just gave you. “Notice the colors in this painting.” “Did you notice that my brother got his hair cut?” “Notice” can also be a noun, meaning an announcement, usually, a formal or more official announcement or a piece of information. We talk about giving notice or giving your notice when you decide you are going to quit your job. That’s a note or a letter you give to your boss saying that “I am going to be leaving in two weeks or in one month.”
“To notify” (notify) means to tell someone something, to give them notice. “To notify” is often used in a more formal way, when you are contacting some government office or the police, or someone who has some sort of official capacity. “I’m going to notify the police of the problems we have on this street.” “I’m going to notify my boss that there is a problem with this contract.”
Our next question comes from Zbyszek (Zbyszek) in Poland. The question is about the difference about the word “assessment” and “appraisal.” “Assessment” (assessment) is any time that you evaluate or you decide how good something is or how valuable something is. We typically use assessment in places such as school when we’re talking about “testing” students – giving them a test to see how much they’ve learned. That’s one kind of assessment. You could also make an assessment of a situation in a business. You look at it, you decide what the main problems are, what the solutions are, perhaps, how much something will cost – those are all possible assessments.
“Appraisal” (appraisal) usually refers to only an assessment of the value of some physical good or some piece of property. You could have a bracelet appraised. You could get an appraisal for the bracelet, or a watch, or a ring, or a house. These are all sort of, official, formal estimates, assessments of how much something is worth.
“Assessment” is a more general term. It can describe looking at the details and figuring out the value or the status of just about anything. “Appraisal” usually refers specifically to how much money something is worth, especially a piece of jewelry or a house. “Assessment,” however, can also be used when talking about real estate – that is, houses and buildings. We can talk about an assessment as a type of tax that the government puts on a certain piece of property. Technically, the assessment is not the tax. The assessment is the government’s guess, estimation, of how much the house is worth, how much the property is worth, and based on that assessment, you have to pay a certain amount of tax back to the government.
“Appraisals,” when we talk about real estate, are usually things done by banks or other people who are going to try to give you a loan to buy a house. You need to get it appraised. You need the bank to come out and say, “This is how much this house is worth, and therefore we will lend you this amount of money.” That’s assessment and appraisal.
Our last question comes from Mosen in Iran. The question has to do with the expression “to be full of yourself.” When we say someone is “full of himself” or “full of herself,” we mean that they have a very high opinion of themselves. They’re too confident in how good they are. They think that they’re much better than they perhaps, really are. “We interviewed someone for the job, but he was so full of himself, we decided we didn’t want to hire him, to have him work at our company.” “To be full of yourself” is usually used informally, in more conversational English, to refer to someone who is what we might call “conceited” (conceited). “To be conceited” means the same as to be full of oneself, to think that you are a great person, that you have great abilities and that you are, typically, better than other people.
There’s a very different expression that you don’t want to confuse with “to be full of yourself,” and that is “to be full of it” (it). “To be full of it” means that what a person is telling you is not true. It’s an informal expression, a very informal expression because the original version of the expression is somewhat vulgar. But the meaning is to be lying. When someone says, “You’re full of it,” they’re saying you’re not telling the truth, you’re exaggerating, you’re telling me things that are not true. “Bob has five girlfriends.” You’d say, “Oh, he’s full of it. He does not. He’s lying. He doesn’t have five girlfriends.” He may have six girlfriends, but five girlfriends? I don’t think so. That’s to be “full of it,” very different than to be “full of one’s self.” Never use the expression “to be full of it” in any sort of formal situation or with your mother.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com. From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast: English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2012 by the Center for Educational Development.
Glossary
professionalized immigration – the act of people who are highly educated (like engineers, programmers, and doctors) coming into a country to live there because of the job opportunities that are available to them
* We see a lot of professionalized immigration in areas like Silicon Valley, where there is a strong need for experienced software developers.
brain drain – a phenomenon in which large numbers of the smartest, most talented, and best educated people leave developing countries to move to more developed countries
* Economists are worried about the effects of the brain drain on developing countries’ ability to advance.
working class – the social class of people who perform physical labor and work with their hands and body
* Oliver’s parents were part of the working class, but he was determined to go the university and become a highly paid professional.
folks – people; an informal word used to talk about simple, ordinary people, especially in the southern part of the United States
* Most of the folks in the town Sheila grew up in worked in forestry and agriculture.
pre-collegiate – not yet in college, ranging from a five-year-old kindergartener to a seventeen-year-old high school senior
* Samantha studied really hard during her pre-collegiate years so that she would be accepted into a top university.
multiplicity – having many different types of something, not all the same
* The multiplicity of courses offered by the university is overwhelming for many students, who have a hard time deciding what to sign up for.
national origin – which country one is from; the country where one was born
* Please write down your national origin and your country of citizenship.
demographics – statistical information describing the characteristics of a population, such as gender, age, race, skin color, and national origin
* Economists are studying the demographics to understand why people are moving out of this city.
culturally competent – knowing enough about other cultures to adapt one's behavior in certain ways so that one doesn't offend another person
* Multinational businesses are always looking for new employees who are culturally competent and can work as part of an international team.
to raise – to bring up a point; to begin talking about something; to move a discussion toward some topic
* That question raises an interesting point.
socio-economic – related to social issues and economics or finance, such as what kind of jobs people have, how much money they make, where they live, whether they have a house or apartment, what kind of car they drive, and more
* People tend to live near people who share the same socio-economic factors.
Fortune 500 company – one of the 500 companies on a list published by “Fortune” magazine for having the highest gross revenue (the amount of money received by a company, before taking away expenses)
* How many years has Wal-Mart been listed as a Fortune 500 company?
to note – to write down in order to remember; to observe or notice
* The landlord walked around the apartment building, noting repairs and improvements that need to be made.
to notice – to observe; to be aware of
* Did you notice that our waiter was wearing bright green pants?
to notify – to tell or make aware; to let know; to give notice
* Please notify parents that students will be dismissed from school an hour earlier on Friday for a teacher’s meeting.
assessment – the act of evaluating; deciding the value or status of something
* As a professional food critic, what is your assessment of this food?
appraisal – the act of estimating value; deciding how much something is worth
* Before we can buy insurance for your mother’s jewels, we need to get an appraisal.
to be full of (oneself) – to be too confident about oneself and one’s abilities; to have too high an opinion of oneself
* I know that Carl graduated from a good university, but that’s no reason for him to be so full of himself.
What Insiders Know
The Yellow Peril and Sax Rohmer’s Fu Manchu Novels
The phrases “Yellow Peril” and “Yellow Terror” were sometimes used to describe how large numbers of Eastern Asians were immigrating to the United States and other Western countries in the late 1800s. People believed that the “yellow-skinned” Asian immigrants would take away jobs from white Americans and decrease their quality of life. They were scared of Asian Americans and wanted them to “go back home” (return to their home country).
A British author, Sax Rohmer, “played on these fears” (exaggerated and took advantage of what other people are afraid of) to write a series of books about Dr. Fu Manchu. He was an “evil” (very bad) “criminal genius” (someone who is very intelligent, but uses that intelligence for bad purposes) who was prepared to kill everyone who “stood in his way” (opposed him; fought against him). He was also “impervious to” (not affected by; not yielding to) American “assimilation” (the process of becoming part of the surrounding culture). The character had a long moustache that became known as the “Fu Manchu moustache.” It is very long and straight, and grows down on both sides of the lips and “chin” (the bottom part of one’s face, below one’s mouth).
The Fu Manchu character became strongly “associated with” (connected to) the Yellow Peril and similar characters in other books, movies, and TV shows were “modeled after him” (copied or imitated him). Of course, the character was a “stereotype” (something that people unfairly or incorrectly believe is true of a large group of people) about Asian Americans and “failed to” (did not) “account for” (consider) the true “diversity” (differences among a group) of Asian American immigrants.