= 1662
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 357.
This is English as a Second Language Podcast’s English Café episode 357. I’m your host, Dr. Jeff McQuillan coming to you from the Center for Educational Development in beautiful Los Angeles, California, United States of America.
Visit our website at eslpod.com. You can take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast blog, where several times a week – well, twice a week, we provide even more help in helping you increase your language proficiency.
On this Café, we're going to talk about Bruce Springsteen and the E Street Band. We're also going to talk about something called the Dust Bowl, a certain period of American history. And as always, we'll answer a few of your questions. Let's get started.
Our Café begins with talking about Bruuuuuce Springsteen and E Street Band. I'll explain why I pronounced his name that way in a minute. Bruce Springsteen is one of the best-known rock and roll singers and songwriters of the 20th Century. He was born in 1949 in a small town called Freehold, New Jersey. New Jersey is in the northeastern part of the United States next to the state of New York. Springsteen was born in Freehold, but he grew up in a neighboring town called Asbury Park. He got his first guitar when he was just 13 years old and was very soon playing as the “lead” (lead) or best guitarist in a band known as The Castiles.
He played with several other groups and bands, but he began to become well known for his songwriting, his ability to compose or write music for singing. Other members of his band called him “The Boss”. The boss is of course, the supervisor, the manager, the leader of a group or an organization. When Springsteen later became famous, his fans would call him “The Boss.” Springsteen was a prolific songwriter. Someone who is “prolific” (prolific) is someone who produces a lot of things, who produces a lot of work. In this case, he wrote a lot of songs.
There was, back in the early 1970s – in 1972 – there was a talent scout named John Hammond who we can say “discovered” or found Springsteen. A “talent scout” is someone whose job it is to find people who are very good at something, who are good actors or good singers or it could be someone who plays sports very well. They find people and they help them become famous and successful. This is what John Hammond did for Bruce Springsteen. He heard him perform one day and realized that Springsteen was incredibly talented. Hammond had also been one of those who had discovered a young singer named Bob Dylan. So, he was very well experienced in this area of finding new talent, new people for the music business.
Springsteen signed a “deal,” that is, he signed a contract, an agreement, with Columbia Records, and he worked with his friends, his fellow musicians that were part of his group. The group was known as the E Street Band, although they didn’t use that name for a couple of years, for the early years when they started playing together. Springsteen’s first two albums or collections of songs were well liked by music critics – the people who write for newspapers and magazines, they really like his music, but it wasn’t the most popular music. His first album was called Greetings from Asbury Park. Remember Asbury Park is where he grew up.
His second album was called The Wild, The Innocent, and The E Street Shuffle. A “shuffle” is sort of a way of walking very casually. I suppose it could be considered almost a dance. Well, those two albums were very different, in some ways, from each other, and as I say the critics liked the albums, but they weren't selling very many copies. Finally, a few years later, in 1975, Springsteen recorded his third album called Born to Run. Born to Run became a huge success. Some people say it is one of the best rock and roll albums ever. Springsteen became famous overnight. He was on the cover of some of the most popular magazines in the United States. In fact, I believe he was on the cover of Time magazine and Newsweek magazine the same week. So, he was very popular and suddenly everyone was listening to his music.
The group, Springsteen and The E Street Band, began to go around the country and play. They began touring around the country, performing songs from this new album, Born to Run. Springsteen continued to write. He had some problems, however, with his record company, especially with his producer, and for almost three years after his big album, his big success, he didn’t produce an album. He wasn’t able to legally. Finally in 1978, he produced an album called Darkness on the Edge of Town. It was, as you can tell by the title, somewhat of a darker album about the difficulties that he had had.
He continued to tour not just around the United States but around the world. He went to Europe and other countries and became popular there as well during the late 1970s. In 1980, he released what we used to call a “double album.” It was an album, but there were actually twice as many songs as you would normally find – there were two records. This was called, this album was called, The River. The River, in my opinion, is one of his best albums. It's mostly about working class life. When we talk about “working class,” we're talking about people who work in jobs, maybe a factory, maybe an office, perhaps working as a policeman or a firefighter, people who don’t make a lot of money, who usually aren't college educated.
Springsteen himself came from that environment and almost all of his music, but especially the music in his albums Darkness on the Edge of Town and The River, were very much about working class life in American cities. In 1982, Springsteen recorded his first solo album, without his band. It was an album that he recorded almost exclusively, that is, almost entirely, with an acoustic or non-electric guitar. That album, called Nebraska, was also a fairly dark album. That is, it was about very serious themes.
Somewhat surprisingly, despite the fact that Springsteen was very popular, he became most popular a few years later. He released an album called Born in the USA in 1984. It became one of the best-selling albums, with over 15 million copies sold in the United States. I happen to think it was not his best album. The title track or the title song, the song that has the same name as the entire collection, the entire album, was “Born in the USA.” “I was born in the USA.” Now, those words sound very patriotic. “Patriotic” (patriotic) means showing your love for your country, and that’s how many people who heard the song thought the song represented. That’s what they thought the song was about.
If you actually listen to the song, however, it is really a song about how the United States did not do a very good job of taking care of its own war veterans, especially those who fought in the Vietnam War. The song was actually inspired by a book, which I read in the mid ‘80s, called Born on the Fourth of July by Ron “Kovic” (Kovic). That book was later made into a movie with Tom Cruise, a few years later. Anyway, the song isn't really a song talking about how great the United States is but rather how poorly the country and the government took care of its own soldiers, its own veterans.
Springsteen continued to write songs and produce albums. None of them were quite as popular as Born in the USA. He didn’t write too much or produced too much popular music in the 1990s. He did, in the year 2002, release or produced a new album called The Rising, which was in part about the terrorist attacks of September 11th. After the terrorist attacks in 2001, one week after I believe, there was a special television program that raised money for the victims, for the people’s – the families of those who were killed in the attacks, and that show began with Bruce Springsteen singing “The Rising,” which was the name of his song, the title track of that later released album.
Springsteen is now in his 60s. He continues to perform and to write music. Some people refer to him now as an “aging rocker,” a rock and roll star who continues to perform even though he’s no longer a young man. Springsteen also got involved in politics beginning in the 1970s. He performed at a concert called the “No Nukes Concert.” I remember it was made into a film, a movie. Throughout the ‘80s and ‘90s, he continued to support political causes. In 2008, he supported a man who some people compared to a rock star, our “rock star president,” Barack Obama, and Springsteen was a supporter of Obama’s.
Springsteen’s real importance, however, was his songs that, as I mentioned earlier, were descriptions of life in American cities, working class life. Springsteen once said, “I spent most of my life as a musician measuring the distance between the American dream and American reality.” The “American dream” is the idea here in the United States that we can accomplish anything if we work hard enough, that we can have a better life than our parents had, and that we can prepare our children to have better lives than we have. Springsteen songs are often about how much people want to have the American dream, but how difficult it is for them to get it.
Springsteen was made a member of or inducted into the Rock and Roll Hall of Fame in 1999. That’s an organization that honors the best rock and roll musicians. As some of you may know from previous Cafés, I am a very big Bruce Springsteen fan, at least I was in the ‘70s and early ‘80s. It's kind of interesting, I went to a high school back in St. Paul, where most of the students were from working class families. Their parents were not college educated. They didn’t plan on going to college, and most of my high school class did not. Springsteen was extremely popular in my high school in the late ‘70s, and I myself for some reason wasn’t very interested in his music at first.
It was only after I left high school and went to the University of Minnesota where I began to appreciate Springsteen’s music. Part of the reason is, perhaps, because when I got to the University of Minnesota, I realized that most of the students who were there were richer than I was, came from better schools, better neighborhoods, better parts of the state, and perhaps I looked back and identified more with my own background. My father was college educated, so I would never call myself “working class," but certainly the neighborhood where I went to school had that atmosphere, had that feeling, that reality.
I identified with a lot of Springsteen’s music in that time and from 1981 to ’85 or ’86 I was a huge fan. I mean I had all of his albums. I had posters. I went to his concert in the early ‘80s in St. Paul. It was actually – some of you may remember, I think I've mentioned this before – he made a music video where he showed the entire stadium, the entire crowd that was there, for the concert and I was there, so I always tell people I was in a Bruce Springsteen video, which is true. I was in the crowd when he made the video.
Whenever you went to a Bruce Springsteen concert, at the beginning of the concert everyone would shout his name and they would pronounce it “Bruuuuuce,” just I suppose in a way to be funny by pronouncing his name that way. So, that’s why I pronounced it that way at the beginning of our Café, just like we were at a Bruce Springsteen concert.
Now, let's turn to our next topic which is a period of American history, not an American singer. That period was called the “Dust Bowl.” “Dust” (dust) is fine white or gray powder, a kind of dirt that appears on surfaces like your bookshelves or your tables. When people talk about the “Dust Bowl,” they're referring to a period of time in the 1930s when, especially in the central part of the United States, the part where most of our agriculture is, at least a large part of it, there were many storms. There was what was called a “drought.” A “drought” (drought) is a long period when it doesn’t rain. And, of course, if it doesn’t rain, you can't grow food.
The United States in the 1930s was already having serious economic problems in what we called the “Great Depression,” which we talked about on English Café number 327 a few months ago. Well, for a number of reasons, this drought helped make things even worse, and a lot of people had to leave these states. The states experienced “dust storms,” where the wind would come by and, because there wasn’t a lot of rain, and, as they say, for some other reasons, these large dust storms really hurt the American economy and the people living in these states.
Because of this drought and these dust storms, many people who lived there had to leave in order to find jobs. In fact, many of them came here to California. There were so many people who came from the state of Oklahoma, for example, which was in the center – is in the center of the United States – that they were given a name “Okies,” which wasn’t necessarily a good thing, but that’s what people called them. Many of the people fled or ran away from these agricultural and economic problems and they ended up becoming migrant farmers.
A “migrant farmer” is someone who doesn’t have a permanent home, but instead moves from farm to farm. These people had to make money. They didn’t want to die from not having enough food, and so they worked very hard and many of them became very poor. We might describe them as being “destitute” or falling into “destitution” (destitution). Several songwriters and novel writers wrote about the Great Depression. Woody Guthrie, one of the great singers of the early 20th Century, drew a lot of his inspiration, a lot of his ideas, from the suffering that the people endured or had to experience in the Dust Bowl. There were two novels written by John Steinbeck, who also talked about the problems of these people in the Dust Bowl - The Grapes of Wrath and Of Mice and Men, two of the great books of American literature in the 20th Century.
Now, let's answer some of the questions that you have sent to us.
Our first question comes from “Daniela” (Daniela) in Italy. Daniela wants to know the difference between the words “suggestion,” “hint,” “tip,” and “pointer.” A “suggestion” (suggestion) is an idea that someone mentions to you, someone tells you. It's an idea about what you should do. It's their opinion about something you should do. The verb is “to suggest.” So, “that was a good suggestion” – that was a good idea.
“Hint” (hint) usually means a clue, an idea that will help you find the answer. It's different from suggestion. Suggestion is: “Here’s something you should do.” A hint: “Here’s some information that will help you find an answer to your question.” Usually you would only give someone a hint if they were trying to solve some sort of problem and for some reason you couldn’t tell them the answer directly. A hint is also sometimes used in cooking to mean a small amount of something. Or someone may taste some soup and say, “Hmm, there's a hint of lemon in here,” meaning there's a little bit of lemon in here, especially if it's lemon soup!
“Tip” (tip) has a couple of different meanings. One is a good idea, a piece of suggestion. Tip is usually a small amount of information. It's not a large book, for example. So, it's a kind of suggestion. It's like a small suggestion. “Tip” can also describe the top or the end of something like a pencil – the tip of the pencil, but that’s not the meaning that I think Daniela is asking about. A tip can also be extra money that you give to a waiter or a waitress in a restaurant for good service. Tip can also be a verb meaning to push something over, but here the first meaning I discussed, a helpful suggestion, a small bit of information, is probably the one that Daniela has in mind.
Finally, “pointer” (pointer) is a useful or helpful piece of advice or information especially for someone who’s trying to do something, and you may be watching them and you may want to help them do what they're trying to do, so you give them a “pointer” or some pointers. You give them some suggestions about how to do this specific thing. So, suggestion is the most general term for this idea and then you have tip, which is a small suggestion, and pointer, which is a suggestion about accomplishing or completing some specific task or something that you are doing.
“Rafael” (Rafael) in Brazil wants to know the difference between “increase” and “raise.” To “increase,” as a verb, means to become bigger, to become greater. It might mean even to grow. To “raise” (raise) means to move something up, to lift something up, like with your hand. But raise can also mean increase, so there are some times where these two words mean the same. “I'm going to raise your salary.” That means I'm going to give you more money. I'm going to increase your salary. I'm going to pay you more money for working here.
We also use this verb raise in some special situations. For example, if we're talking about helping young children grow up in your family, helping your children, we would talk about “raising your children.” You don’t increase them. If you increase your children, you’d have more children, which you might want to do or not, but to “raise children” means to take care of children, to help them grow. We also use raise when we are talking about trying to get more money for a project or an organization. “The church is trying to raise money for its school.” The organization is trying to get more people to give money. That’s also a way of using the verb raise. Of course, by getting more money, they're increasing the amount of money, but we use that verb in a very special way when we're talking about trying to get more money for an organization or a group.
Finally, “Eugene” (Eugene) from Mystery Country Alpha – or maybe he’s from Alpha Centauri, the star far away. Ooh, that’s very exciting! Thank you for emailing Eugene. Eugene wants to know about an expression he saw in a popular movie in the 19 – must be the 1990s – called Good Will Hunting with Matt Damon and Ben Affleck. The sentence that he wants to know about is “How do you like them apples?” This is a very famous scene in the movie. Matt Damon is in a bar and there is another guy there who is trying to get the telephone number or become friends with a beautiful woman in the bar, and at the end, the guy who’s trying to get the girl’s number doesn’t, but Matt Damon does.
Later, as Damon is walking down the street, he sees the guy sitting in a restaurant and he comes up to him and he says, “Do you like apples?” And the guy says, “Yes.” And Damon shows this guy the girl’s telephone number and says, “I've got her number,” meaning she gave me her telephone number. “How do you like them apples?” Well, this expression “How do you like them apples?” is actually an old one. It doesn’t come from the movie, but Matt Damon uses it in a way that is typical of how it would normally be used. The expression “How do you like them apples?” isn't an actual question. You don’t expect the person to answer. It's used to, really to show someone else how you're better than they are, how you often have beat them or you’ve won something and you're sort of bragging, you're sort of showing off, you're sort of saying, “Look how good I am!” And that’s really what Matt Damon is doing in the movie. He’s bragging: “How do you like them apples?”
If you have questions about apples or oranges or Alpha Centauri, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on The English Café.
ESL Podcast English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2012 by the Center for Educational Development.
Glossary
songwriting – writing or composing music with lyrics (words) for performance
* Gisele has a talent for songwriting, being able to create appealing music and heartfelt lyrics.
prolific – for an artist, author, or composer to produce a lot of works; producing a large number or amount of a creative work
* Thomas Edison was a prolific inventor, inventing far more than the light bulb and movie camera.
talent scout – a person whose job is to find people who are very good at acting, singing, playing an instrument, or playing a sport
* Drew’s natural running ability got the attention of an influential talent scout.
title track – a song that shares the same name as the album
* The title track off Jeff’s new album hit number one on the music charts.
patriotic – feelings and behaviors related to one's love and support of one’s country
* On Independence Day, many people feel patriotic and display the American flag outside their homes.
nuke – nuclear weapon; a weapon that uses the energy released from nuclear fission or fusion; nuclear power
* The protestors outside of the power plant had signs that read “No Nukes!”
American dream – the idea that one can accomplish anything through hard work, having a better life than one’s parents, and preparing one’s children to have an even better life
* Jaleel is working toward the American dream by working two jobs to pay for a college education.
dust – the fine white or grey powder that appears on the ground or on surfaces
* Keeping windows and doors closed doesn’t prevent dust from getting on floors and furniture.
drought – a long period without much rain; a shortage of water because of too little rain
* During this drought, the government is asking people to take shorter showers and not to water their gardens.
to flee – to run away from a place or situation that is dangerous
* The children fled the field to get away from the angry bees.
migrant farmer – a person who doesn't have a permanent home and instead moves from farm to farm, helping with planting or harvesting when needed
* Migrant farmers bring their families with them as they travel from farm to farm.
destitution – extreme poverty and hopelessness; without the basic needs of life
* Losing a job and not getting any help can eventually lead to destitution.
suggestion – an idea that has been brought to someone’s attention; an opinion about what someone else should do
* While on vacation, we followed Louisa’s suggestion to save money on hotel, but spend money on good food.
hint – a clue; an idea that can help someone find the answer
* None of the students had the correct answer to the geography question so the teacher gave them a hint.
tip – a helpful idea; a bit of useful information; a small piece of advice
* Let me give you a tip about doing well in this company: Never come to work late and expect to stay after work hours.
pointer – advice; helpful information, especially on how to do something
* Belinda knew nothing about changing tires on cars, but after a few pointers from Julia, she was able to do it all by herself.
increase – the making of something bigger, higher, or more
* The increase in sales this year means every employee will get a bonus.
raise – an increase in pay or salary; to lift up
* Kris thought that it was unfair that he hadn’t received a raise in two years.
How do you like them apples? – a rhetorical question (question where no answer is expected or needed) used to brag that one has won, while others have lost
* No one thought that Dimitri would win the race, but when he came in first place, he said to the crowd, “How do you them apples?”
What Insiders Know
The Billboard Charts
Many radio stations in the United States have “countdowns” (songs played in order of popularity, going from the least popular to the most popular) of “hit” (successful or well-known) songs every weekend. They do not just pick these songs “at random” (by chance), however. Most of the time, the list is taken from a “Billboard Chart,” a list of the most popular music in the United States.
The Billboard Chart began as a list published in Billboard magazine in 1936. (A “billboard” is a sign above a theater or on the side of a road with advertisements, either listing performers who will be performing, or for products or services.) “Eventually” (over time), because there were so many different “genres of music” (such as jazz, rock, or pop), many more lists were produced for each of these genres of music.
In 1958, the magazine “compiled” (put together) a list of the one hundred most popular songs, regardless of category, and called it “The Hot 100.” This list is still updated every week, and all of the songs on it are played often on popular music stations. In fact, many radio stations choose the songs they play based almost “entirely” (completely) on the Billboard Charts.
There are many factors that play into the “placement” (where something is put) and the “inclusion” (whether something is included) of songs on the Billboard Chart. Song sales are “taken into account” (considered), as well as how many times a song is “requested” (asked to be played) or actually played on the radio. Based on how many copies of a song are sold and how many times it can be heard on the radio per day, the researchers at Billboard decide whether or not to put the song on their chart. For new musicians, being included on one of the Billboard charts could “make or break” (be the deciding factor of success in) their careers.