= 1693
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 388.
This is English as a Second Language Podcast’s English Café episode 388. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there to become an ESL Podcast member. When you do, you can download a Learning Guide for each of our episodes that will help you improve your English faster than ever.
On this Café, we’re going to continue our series on famous Americans, focusing on Sandra Day O’Connor. We’re also going to talk about one of the most popular sports in the United States, American football. And as always, we’ll answer a few of your questions. Let's get started.
We begin this Café by continuing our series on famous Americans. Today, we're going to talk about a famous American woman by the name of Sandra Day O'Connor. Sandra Day O'Connor is important in American history because she was the first woman to serve on the U.S. Supreme Court, which is the highest or most powerful court in the United States.
O'Connor was born in 1930 in the state of Texas, which is located in the south central part of the United States. She grew up in Texas and in Arizona. Arizona is in the southwest part of the U.S., right next to California. In between California and Texas are the states of Arizona and New Mexico. Sandra Day O'Connor grew up in Texas and Arizona but she studied economics here in California at a very famous university called Stanford University. She also received her law degree from the Stanford University Law School.
O'Connor was the assistant attorney general in the state of Arizona from 1965 to 1969. An “attorney general” is a lawyer who provides legal advice to the government. O'Connor was the assistant attorney general, meaning she helped the person who was the main lawyer, the attorney general. In 1969, she was appointed to a position in the Arizona State Senate. “To be appointed” (appointed) means that you are given the position but you are not elected typically to the position. However, O'Connor was appointed to this position and then later, she was elected in 1973. She then became a judge, and in some parts of the United States, the people vote on who becomes a judge. That's what happened with Sandra Day O'Connor. She was voted as a judge in Arizona in 1975. It's not uncommon for lawyers, if they're very good or very well known, to be made into judges, either appointed a judge or elected a judge.
There are different levels of judges, different levels of our legal system in the U.S. Sandra Day O'Connor started at the lower level. She was in what we would call a County Court. Then she moved up to the Arizona Court of Appeals in 1979. “Appeal” (appeal) refers to a request that the court reconsider a legal decision. Let’s say you have a trial, you go before a judge, a County Court judge, and you are found guilty; the government says you did something wrong. You think the court made a mistake. You can then appeal that decision to a higher court. In Arizona, as in many states, there is what is called a Court of Appeals. That's the court that you can go to after you get a decision you don't like in one of the lower courts.
In 1981, President Ronald Reagan moved O'Connor from the appeals court in Arizona to the very highest court in the United States – the U.S. Supreme Court. She was made what we would call a “Justice.” The word “justice” (justice) just means judge, but we use that special word “justice” when we’re talking about our highest court – the U.S. Supreme Court. The U.S. Supreme Court currently has nine justices. All of them are called “Associate Justice,” except the leader, who is called the “Chief Justice.” The Chief Justice has one vote just like all the other members but here she organizes the court, usually decides who's going to write the opinions for the court.
Sandra Day O'Connor was the first woman to be appointed as a justice of our Supreme Court. Some people criticized President Reagan for making this selection. They said that O'Connor wasn't the best person for the job, that she was selected because she was a woman rather than being a great judge. However, the U.S. Senate, which is part of our elected representatives in Washington, D.C., approved O'Connor, and she became a member of the Supreme Court.
Supreme Court justices are members for life. Once they’re on the court, the only way that they leave the court is by resigning, saying, “I quit,” or die. Many justices have died on the Supreme Court before they resigned. (When you die, you don't really have to resign. That is kind of taken care of for you.) Anyway, Sandra Day O'Connor was initially – at the beginning – considered a conservative justice, someone who agreed with Ronald Reagan and other conservative politicians back in the 1980’s.
However, as she remained on the court, she became more of a swing vote. A “swing (swing) vote” is a vote that could go to one side or could go to the other. The U.S. Supreme Court, just like American politics in general, has some members who are politically conservative, others who are politically liberal. Sometimes, you have a justice like O'Connor, who seems to, on some things, go to the liberal side, and on some things go to the conservative side. O'Connor was definitely a swing vote. There are nine justices, so you need five votes in order to be the winning decision, and many decisions on the Supreme Court are decided by one vote – a five to four vote. Most of them are not, but many of them are.
O'Connor was a swing vote on a couple of important issues. One of them was abortion. Abortion is a controversial topic in American politics. Even the definition of abortion is controversial, depending on your view of it. Some people refer to it as a “termination of a pregnancy,” that is, a woman is pregnant with a child and she ends the pregnancy. Other people say that it is in fact, the killing of the “unborn child.” Depending on which view you take, you may define it in one way or the other. O'Connor voted for the liberal side on several important cases, including those cases that involved abortion.
In 2005, O'Connor decided that she was going to retire. She was going to resign from the Supreme Court. She continued on the court until early 2006 when another justice was nominated – selected by the president and put on the Court. The president of the United States is the one who selects the justices, but the justices have to be approved by the U.S. Senate, part of our Congress. When O'Connor resigned, she was replaced by another justice, a conservative Justice. We would call this person who replaced her, her “successor.” A “successor” (successor) is someone who takes your position, usually some official position, after you leave. We could talk about a successor to the king or queen of the country – that would be the next king or queen, the person who will take over when the current king or queen dies. We use that same word in talking about people who are replaced in official positions, in this case, for a U.S. Supreme Court justice.
O'Connor resigned but she is still around as we record this, in 2013. She remains active in teaching. She sometimes works as a judge, what we would call a “substitute judge,” in some of our federal courts, our national courts. When someone is sick or can't be there, she sometimes will work in their place. It sounds a little strange, but it does happen.
Mostly, like a lot of retired U.S. Supreme Court justices, she goes out and gives speeches. She gives lectures to students, to others. She has also created a website to teach civics to students and teachers. “Civics” (civics) refers to the things that you are supposed to do as a citizen of the United States – your responsibilities and your rights, the importance of voting, how our government works – knowing those things is part of what we call “civics.” In many high schools, there is a class called “Civics” which is supposed to teach students about the important things related to our government, how it works, what their rights and responsibilities are, and so forth. I had a civics class. I guess when I was a senior in high school, my last year. In the 12th grade, before going to college, we had a civics class. I don't remember it very well. I might've been sleeping during that class.
Now let's turn to our next topic, which is a popular sport that you are probably familiar with – American football. Now when you use the word “football” in most countries, you're referring to what we call here in the U.S. “soccer.” But in the United States, football always means American football.
It's hard to explain all of the rules of the game of any sports game in a very short amount of time, but I'll give you some of the basic ideas. Football, as a sport, began by adapting some of the parts of another game called “rugby,” and it began to be played at colleges and universities in the United States very early in our history, in the early 19th century. By the 20th century, by the 1900s, football was the dominant sport on college campuses, on university campuses. “Dominant” (dominant) means it is the most common. It is the one that you will most often find. Football was the dominant sport, meaning it was given more importance and was more popular than other sports such as baseball, basketball, tennis, or of course, soccer.
Modern football games, whether they are college, high school, or professional, are played between two teams. Each team has 11 players on the field, 11 players playing at any given time, but usually there are other players off the field waiting to play, just like you would have on any sports team. Not everyone plays all the time.
The two teams, the two sides of the game, are referred to as the “offense” and the “defense.” The “offense” (offense) are the players who have the ball. It's the team that has the ball and is trying to move the ball down to the end of the field. The field is the rectangular area where they play that is, in most American football games, 100 yards, roughly 300 meters long. If you have the ball, if your team has the ball, you are called the offense. And the other team that is trying to prevent you from moving down the field - for that's the objective, that's the goal of the game, to bring the ball and to make it all the way to the other side of the field – you are called the “defense.” The “defense” is the team that is trying to prevent you from moving down the field.
In order to score points in American football, you have to bring the ball down to what is called the “end zone.” An “end zone” (zone) is the area on the end of the field after the 100 yards, where you must bring the ball in order to score points.
There are actually four ways that a team can score points in American football. The most obvious way is to give the ball to someone on your team and have that person run into the end zone to carry the ball over what we call the “goal line.” The “goal (goal) line” is the line you are trying to cross to get into the end zone. You can also score a point by throwing the ball to someone on your team who’s in the end zone. That also scores points.
A third way to score points is to kick the ball through what are called the “goal posts.” A “goal post” (post) is a large piece of usually metal that is sticking up in the air. You have to kick the ball so that it goes in between the two pieces of metal that are high up in the air. Those are the “goal posts.”
The fourth way you can score points is when you have the offensive team way back at their side of the field, and you tackle, or you physically hit and make fall, a person on the offense who has the ball in their own end zone. Remember that the field is 100 yards long. At each end you have an end zone. So, at any given time during the game, you have your own end zone and you have the end zone of the opposite team. You're trying to get your ball into their end zone. If, for some reason the defense tackles you – knocks you down with the ball in your own end zone – that also will score points for the defense. We call that, when that happens (and it's very rare that that happens) a “safety.”
How many points do you get for each one of these four methods of scoring points? For a safety, you get two points; that is, the defense gets two points. When you either run or throw the ball into the end zone, what's called a “touchdown,” you get six points. After the touchdown, you have another opportunity as the offense to score points. You can kick the ball between the goal posts. That would give you one point, or you can try to run or throw the ball into the end zone again for an additional two points. The other way you can get points is by being the offense going down the field deciding you're not going to try or are unable to get easily a touchdown, by running or throwing the ball into the end zone, so instead you kick the ball through the goal posts. When you do that, you get three points.
So, a touchdown – running or throwing the ball into the end zone as the offense – gives you six points. After the touchdown, you can get either one point by kicking the ball or two points by running or throwing the ball into the end zone. You can simply decide not to try to score a touchdown and kick the ball through the goal posts – what we call a “field goal,” and that will give you three points. And if you get a safety by tackling a member of the offense in its own end zone, you get two points. Confusing? Yes. I think it is.
Football is what we would call a “contact sport,” because the players are often running into each other, hitting each other, tackling each other, trying to make the other player fall down. For that reason football players have to wear a lot of protective clothing.
Football, like all sports, has a number of different levels. Kids can start playing football when they’re children. They continue on through high school. Many of them go to college and play football and then we have a professional football organization – the National Football League. I, myself, have never played football. I never had the equipment where I would dress up and try to hit people or have other people hit me. In school, you sometimes play a type of American football but you don't actually hit or tackle anyone. You just throw the ball back and forth or run the ball back and forth. I don't think I would have been a very good football player, so it's a good idea that I decided not to take that up as my favorite sport. To be honest, I don't really even watch American football very often. I'm a baseball fan. That's the sport I like to watch. Some people like to watch all kinds of sports. For me, it's pretty much just baseball.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Gerson (Gerson) in Angola, in Africa. Gerson wants to know how we use the word “draw” (draw). There are lots of different meanings of the word “draw,” too many, really, to talk about here on the Café. I'll talk about some of the main uses of this word.
When we're talking about art, “to draw” means to create a picture with lines. You can use paint, you can use pens, you can use pencils – anything that you can use to create a line on a paper can be used to draw. Of course, it's not just lines. You're making houses and animals and humans, and so forth in your picture.
Draw can also mean to choose. If you are playing a game, especially a card game like poker, “draw a card” means to take one card from the pile.
A “draw” in a sporting event or competition is when the two sides are equal. They have the same number of points and no one wins. Another word for this would be a “tie” (tie).
Yet another meaning of “draw” usually comes together with a word like “conclusion” or “distinction.” “To draw a conclusion” means to come to a conclusion, to come to some sort of decision, or to reach an opinion. “To draw a distinction” means to point out a difference between two things. “Draw” is often used in phrasal verbs. We have lots of phrasal verbs with “draw” – again, too many to go over in this short Café. One of them would be “to draw out.” “To draw out” means to make a situation take longer than it normally would or that it should. “He was drawing out the story.” He was telling us more and more than he would have to in order to communicate the message. “To draw in” means to make someone become part of something, perhaps against their will, perhaps even when they don't want to. You could draw them in. Those, then, are some of the uses of the word “draw.”
Our next question comes from Ivan (Ivan) in Ukraine. Ivan wants to know the difference between two phrases he saw. One of them is “out for lunch,” the other one is “out to lunch.” When you use the phrase “out for” followed by some sort of meal, whether it's breakfast or lunch or dinner, you mean that you have left where you normally would be – your house or where you work – and have gone (typically) to a restaurant to eat some food. “He's out for lunch” means he's not here in the office. He’s somewhere else eating his lunch.”
“Lunch,” of course, is the meal that we eat in the middle of the day, usually around 12 noon. Although “out for” can be used with any meal, it is most commonly used for lunch because it's most commonly used in a business setting. Someone will say, “Where's the boss?” “He's out for lunch.” You could also say “out for coffee,” though it's not quite as common.
“To be out to lunch” can mean the same as to be out for lunch – not to be in your office, for example, or not to be available because you are eating your mid day meal, your lunch. However, “out to lunch” is also an idiom that can mean that someone is not paying attention to what you are telling them, perhaps because they're not very smart, or perhaps because they're just not concentrating or focusing on what you are saying. So, you could have a meeting with someone and one of the people in the meeting doesn't seem to be paying attention or says something that doesn't make any sense based upon what you were just talking about. You might say, “Boy, that person was really out to lunch,” meaning that person wasn't paying attention. They almost were a little crazy because they weren't focusing on what they were supposed to focus on.
Finally, Amir (Amir) in Iran wants to know the meaning of a phrase “for crying out loud.” This is a good expression that's very common in American English, or at least it used to be. “For crying out loud” (loud) is used to show that you are annoyed, you are bothered by something, or that you were surprised by something but in a bad way, in a negative way. You could be yelling at someone for something they did wrong. You could say, “I told you to finish this report today, for crying out loud!” You're, you're angry. You're annoyed. You're maybe a little upset. Or you might say, “For crying out loud, who left these shoes here on the floor?” “For crying out loud” means you are angry. You are expressing your unhappiness with the situation. “For crying out loud” is a strong expression of emotion but it's not inappropriate, it's not something that is considered vulgar by any means. You would probably hear it more informally than formally, but it could be used by a parent with his or her child. It's not something that is considered a swear expression, a vulgar expression.
If you have a question or comment, you can e-mail us. Our e-mail address is eslpod@eslpod.com.
From Los Angeles, California. I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
English as a Second Language Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2013 by the Center for Educational Development.
Glossary
attorney general – a lawyer who provides legal advice to the government, such as a state government
* The Attorney General of our state believes that the new federal law is unfair and should be changed.
appointed – given a job by someone; assigned a position by someone in power
* Fausto has been appointed to the museum board.
court of appeals – a court that considers requests to reconsider a legal decision, to say whether the first legal decision was correct or not
* Jo was convicted of robbery, but he’s taking his case to the court of appeals.
justice – judge on the Supreme Court, the highest and most powerful court in a state or country
* Three of the five justices voted in favor of the defendant.
swing vote – tie-breaking vote; when an equal number of people have voted for each of two options, the vote that decides the result
* Jill and I want pizza for dinner, but Mom and Dante want Indian food, so you’re the swing vote.
abortion – the ending of a pregnancy; a medical procedure causing a woman to no longer have a baby growing inside of her
* Carla already has five children and can’t afford to have another baby, but she won’t consider getting an abortion.
successor – the person taking one’s position after one leaves it; the next person to have a particular job
* The chair has already named her successor and is preparing him for the job.
civics – related to the rights and responsibility of citizenship, such as the importance of voting and understanding how the government works
* Our students begin learning about civics by studying how elections work.
dominant – the most common; the most important
* The dominant opinion on the committee is that we shouldn’t have a party this year in order to save money.
offense – the players on a sports team who are focused on moving the ball forward so that the team can score points
* Why isn’t our offense more effective against the rival team?
defense – the players on a sports team who are focused on preventing the other team from moving forward with the ball to score points.
* Our defense is allowing the other team’s players to score too many points!
end zone – the area at one end of a football field, where players can move a ball and score points
* Look! The quarterback is running with the ball into the end zone!
goal posts – on a football field, a large square shape with an open top at the end of the field where a ball can be kicked to score points
* Until you can kick the ball through the goal posts, we can’t put you on our team.
to tackle – to physically hit and fall on a player from the other team to prevent the player from advancing on the field
* Georgina doesn’t want to watch her son play football because she can’t stand it when her son gets tackled.
contact sport – a sport where the players must come in physical contact with each other
* I’m too old to play any contact sports, but I’d be interested in a game of tennis.
to draw – to create a picture with lines; to pull or drag; to formulate; to choose; to end a contest with neither side winning; a tie
* The children drew pictures of their family and their pets.
out for lunch – eating the mid-day meal outside of the workplace, usually at a restaurant
* Would you rather go out for lunch or eat in the office tomorrow?
out to lunch – for someone to not be paying attention or not be informed; not in the office (or available) because of eating the mid-day meal
* Ever since Kaylie met Mike, she can’t concentrate on anything and always seems to be out to lunch.
for crying out loud – an expression used to show that one is annoyed (bothered), sad and stressed, and/or unpleasantly surprised by something
* Who left the door open and let the dog get out, for crying out loud?!
What Insiders Know
Competitive Cheerleading
During high school, college, and professional “sporting events” (games and other competitions), “fans” (people who are watching) “cheer” (shout encouragement) for their favorite team and players. There is often a group of people who start and encourage these cheers: cheerleaders. Cheerleaders are usually girls or women, though recently more boys and men are becoming cheerleaders.
Cheerleading has been part of sports since the 1800’s. At first, cheerleading was only to get the fans involved in cheering for the athletes. Over time, cheerleading started to involve “routines.” These routines included dance moves often done to music and “stunts” (difficult athletic moves).
A group of cheerleaders is called a “squad.” In the 1980’s, squads of cheerleaders started competing against each other. These competitions are judged and points are awarded. Competitive cheerleading is now a sporting event involving thousands of competitors and fans each year.
In the 1970’s the National Football League (NFL) had cheerleaders for many of their teams. The Dallas Cowboys (an American football team based in Texas) called their cheerleaders the Dallas Cowgirls. These cheerleaders wore sexy outfits and performed complicated dance moves. The Dallas Cowgirls were soon the most popular cheerleaders in the country.
The popularity of the Dallas Cowgirls led to the start of competitive cheerleading. Now, the routines that cheerleaders perform in the national and international competitions are very complicated and often dangerous. One move is called a “human pyramid.” A group of cheerleaders “kneel” (stand on their knees) or stand to form a base. On this base, more cheerleaders stand or kneel. A third or fourth level can be added to the pyramid.
There are many organizations and associations for cheerleaders at all levels. Young children often start cheering as young as five years old. However, the most common age for cheerleaders is between 15 and 25.