= 1686
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 381.
This is ESL Podcast’s English Café episode 381. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. On it, you can visit our ESL Podcast store. You can also become a member of ESL Podcast and download the Learning Guide for this episode.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers, talking at a normal rate of speech. We’ll listen in and then explain what they’re talking about. Today, we have an interesting topic, participatory science. In addition, we’ll also answer some of the questions that you have sent to us. Let’s get started.
Our topic on this Café is participatory science. “To participate” means to be involved or to be part of something. So, the word “participatory” would relate to people who are involved in something, in this case, involved in science. Basically, participatory science is when average, ordinary people like you and me, help scientists with their work, mainly by helping them gather or collect information. We’re going to start by listening to a woman named Sandra Anderson. She’s the head of or the project director of something called “Project Bud Burst,” which is a participatory science project where people share information about how plants bud or grow – how they begin to produce flowers. She’ll talk about the growing interest in participatory science. We’ll listen first. Try to understand what she said, then we’ll go back and explain it. Let’s listen.
[recording]
“Originally, it was, what? I don’t want to say limited, but it was a lot of weather data and bird data. Now what we’re seeing is more and more and more taxa, more and more interest, and as a result, there is really a citizens science project to meet just about any interest.”
[end of recording]
Sandra begins by saying, “Originally, it was, what? I don’t want to say limited, but it was a lot of weather data and bird data.” She says “originally,” meaning when they first started these projects. “Originally, it was, what?” She uses a question here – “What?” – to indicate that what she’s about to say is an estimate. She’s not exactly sure but she’s thinking about it as she’s talking. “Originally, it was, what? I don’t want to say limited.” “Limited” means it has certain restrictions. It doesn’t include everything. Originally, these projects were limited to mostly weather data and bird data. “Data” (data) is information. So, “weather data” would be information about the weather – the temperature, the clouds and so forth. People would go out and gather or get that information for scientists. “Bird data” would be information about birds – what kinds of birds you see in your area that might be useful, for example, in studying how birds move across a certain area. I don’t know. I don’t know anything about birds but that’s an example of bird data.
Sandra says that “Now, what we’re seeing is more and more and more taxa (taxa).” “Taxa” is the plural of “taxon” (taxon) which is not a word that I knew before investigating the Café. “Taxon” is a group of populations of an organism. Now, I don’t know exactly what that means but basically, it’s a unit of classifying groups of organisms – living things.
Sandra might be talking about the fact that participatory data covers more types of birds, or she might mean in general that there are more types of participatory science. The meaning isn’t really clear from what she’s saying here but that’s the general idea. She says “There is more and more interest, and as a result, there is really a citizens science project to meet just about any interest.” “Citizens” are people who are official members of a certain country, in this case, it just refers to the average person. “Citizens science projects” would be projects or organized activities that involve the average person. We don’t think of the average person as being involved in scientific research. That’s why we talk about citizens science projects to emphasize that these are not trained scientists. These are just normal people, interested in helping scientists with their work. She says that there is a citizens science project to meet just about any interest. “To meet (meet) an interest” means to go with that interest, to satisfy that interest, to match that interest. You’re interested in collecting information about cats. There’s probably a citizens science project that will meet that interest. I, for example, plan on joining a project just like that. Now let’s listen to Sandra one more time.
[recording]
“Originally, it was, what? I don’t want to say limited, but it was a lot of weather data and bird data. Now what we’re seeing is more and more and more taxa, more and more interest, and as a result, there is really a citizens science project to meet just about any interest.”
[end of recording]
Now we’ll listen to another female scientist, a woman by the name of Amanda Bruner. Bruner coordinates or organizes a project based at the University of Washington in Tacoma, Washington. Washington is located in the, what we call the “Pacific Northwest” – the very northwestern part of the United States, not including Alaska and Hawaii. The project, called “Sound Citizen,” uses participatory science to examine, to keep track of, to monitor, “pollutants” in the Puget Sound area, which is a large are of water close to the Pacific Ocean in Washington. “Pollutants” are things that make the environment dirty, that don’t belong there, that are typically put there by men and women…and children. Let’s not forget the children. They’re not always perfect, you know. Here’s Bruner talking about some of the advantages of participatory science
[recording]
“Maybe a few scientists on a boat can go out and collect 20 samples in a day. But when we involve the public, we can talk about thousands of samples, which certainly gives us much more confidence in what we’re finding.”
[end of recording]
Bruner explains that when there are just a few scientists working together on a project, they can only collect or gather a small amount of information because there just aren't very many people out there gathering the data, collecting the information. She starts by saying, "Maybe a few scientists on a boat can go out" - can leave and go into the water - "and collect 20 samples a day." A "sample (sample)” of something is a small part of something, usually for testing. Your doctor, for example, might take a blood sample from you. They may take a little bit of your blood - and a lot of your money - in order to see whether you are sick or not. Here were talking about water samples - where people take a small amount of water from different locations, probably to test for these pollutants or certain chemicals.
So, a few scientists might be able to collect 20 samples per day. But, when you involve lots of people, you can have a lot more samples. Amanda says, "When we involve the public," meaning when we ask people, normal, everyday people - because scientists are not normal, really - then they can collect a lot more information, a lot more samples. She says, "We can talk about thousands of samples," meaning we can get thousands of samples, which certainly gives us much more confidence in what we're finding. "Confidence" means you can trust your results, you can trust the conclusions you draw or you get from your results. If you just talk to three people about their opinion, you can't get a very good idea about what the average person thinks about a topic, say, in a given country or state. But if you talk to thousands of people, you have more confidence that the results that you get - the conclusions that you draw - are in fact, real, that they are correct. Let's listen to Bruner talk one more time.
[recording]
“Maybe a few scientists on a boat can go out and collect 20 samples in a day. But when we involve the public, we can talk about thousands of samples, which certainly gives us much more confidence in what we’re finding.”
[end of recording]
Finally, we're going to listen to a man by the name of Dennis Ward. Dennis Ward like our first speaker, Sandra Anderson, works for Project Bud Burst. Dennis is going to talk about the importance of technology, how he and other people in the project can take pictures of trees with their cellphones in order to identify the tree and help the project. You can imagine people with cellphones can walk around and take pictures of things. Now, there are actually apps, there are software applications, for phones like iPhones and Android phones that allow you to be part of this project. You open up the app, you can take a picture and then you can send it back to the scientists from wherever you are. Ward is going to talk about the advantages of this sort of technology for participatory science. Let's listen.
[recording]
“One of the wonderful things about using mobile technology is that, as you can see, it actually has the latitude and longitude that is taken from the phone when I took the picture.”
[end of recording]
Dennis begins by talking about the advantages of mobile technology. He talks about the wonderful things about using mobile technology. “Mobile” (mobile) refers to things that can move around from one place to another easily. We use the term “mobile phone” to talk about the cellular or cell phones that we have. They’re “mobile” because we can move them around. We also talk about “mobile devices.” “Devices” (devices) are small machines, often small computers like an iPad or another tablet computer. “Technology” refers to tools that we use to do something.
“Mobile technology,” then, refers to things like cellphones and tablet computers, iPads, iPhones, and so forth. Dennis says that one of the wonderful things about this mobile technology is that when you take a picture, say of a tree, with your phone, you can see the latitude and longitude where the picture was taken. Because of cellular technology, your phone knows exactly where that picture was taken and can transmit or send that information back along with the photograph so that the scientists know exactly where you are. You may not want the scientist to know exactly where you are so you have to be careful about that but for the scientists, it’s wonderful information.
I mentioned “latitude and longitude.” “Latitude” (latitude) refers to these imaginary lines – these lines that can draw in a map, for example, that go around the earth. Zero latitude would be the equator, right in the middle of planet Earth. We talk about degrees of latitude. So, we can go up to the top of the earth, to the North Pole, and we could count the number of degrees from 0 to 90. 45 degrees latitude would be right in the middle, between the equator and the North Pole. We talk about north latitudes and south latitudes, obviously, if you go from the equator to the South Pole, you’re talking about 45 degrees south latitude.
Another word you sometimes hear, in referring to latitude is “parallel.” We could talk about the “38th parallel.” That’s the line that divides North and South Korea. It’s 38 degrees North Latitude.
“Longitude,” (longitude) you can probably guess, are the imaginary lines that go around the earth from north to south and they tell you how far east or west you are. For example, Los Angeles is located at 38.0522 degrees north latitude, 118.2428 degrees west longitude. We talk about east and west longitude. The zero line goes through a town close to London, England. It’s called Greenwich, England, and that is the zero degree longitude line, and then you can count up to 180 degrees east and west from there. So, if you know the latitude and the longitude, you can tell exactly where anyone is in the world. Our scientist friend, Ward, then says that the fact that the pictures that he takes with his phone have the latitude and longitude, help the scientists then do their work better by being able to locate exactly where that tree is. Let’s listen to Dennis one more time.
[recording]
“One of the wonderful things about using mobile technology is that, as you can see, it actually has the latitude and longitude that is taken from the phone when I took the picture.”
[end of recording]
Now let’s answer some of the questions that you have sent to us.
Our first question comes from China from Xuesong (Xuesong). The question is about four different terms or words – “attend,” “take part in,” “participate in,” and “join.” Let’s start with “attend” (attend). “To attend” means to be present, to be physically present at some event, in some particular place. We talk about attending class. Students are supposed to attend class. They’re supposed to actually go to the classroom where the teacher is teaching. They don’t always do that. Sometimes you will find them in the bar more than in the classroom, but the general idea is that students should go, should attend class.
“To take part in” means to be a member of a group activity. It means to be participating in some activity. That leads us to the next expression, which is “participate in.” “To participate in something” is to do a certain activity with other people, typically. “To join” is the act of becoming a member of a group. So, if you are not a member of a certain group, and then you decide to join the group, after you join, you will then participate in the group’s activities, you will take part in the group’s activities. One way to participate in an activity, or “take part in” an activity, is to attend an event – to go to a party, to attend a party or attend a meeting. Those are all ways of taking part in or participating in a group after you become a member, after you join the group.
From China, we go to the country of Congo and a question from Modeste (Modeste). The question is about the difference between “standalone” (standalone) – one word – and “stand alone” – two words. “Standalone” – one word – refers to something that can work by itself, that doesn’t need any other components, any other parts for it to work. We could talk about a standalone refrigerator. It doesn’t have to be connected to any other appliance, any other machine. It does have to be connected to electricity, of course. That would be a standalone refrigerator.
The verb “to stand” means to be on your two feet, not sitting, with your body in a vertical position. “Alone” means by yourself. So, if you talk about someone standing alone, we mean simply, that the person is standing, is on their feet and there’s no one around them. It’s not a very common expression. You certainly could talk about, say, a man, standing alone on the corner. There was no one else around him, but the more common term would be standalone – one word – referring, as I said, to something that does not require a connection to or any sort of other additional help in order to function or work.
From Africa, we go back now to China, to Cheng Yu (Cheng Yu). The expression Cheng Yu wants to know about is “hair of the dog that bit me.” This is an interesting expression. “Hair (hair)” is, of course, the substance that comes out of one’s skin. A “dog” is a little animal. The word “bit” (bit) is past tense for the verb “to bite” (bite). When a dog bites you, he takes his teeth and he puts his teeth into your skin and usually causes pain.
Now, if a dog bites you and the dog has a certain disease such as rabies (rabies), which can cause you to become sick as well as the dog, you’ll probably have to go to the doctor and get some medicine so that you don’t become sick. Well, in the old days, people didn’t have modern medicine to rely on, to help when they were sick. So, they had other sorts of cures, other sorts of things that they did to make themselves feel better. Beginning, really, we think in ancient times, many thousands of years ago, but certainly in the 16th, 17th, and 18th centuries, people who got bit by a dog thought that if you took the hair of the dog that bit you, if you went and got the hair off of the dog and you put in on the dog bite, the place where the dog’s teeth went into your skin, that this would prevent you from getting sick, or at least help you get better if you did get sick.
The idea then is that you would have to go and find the dog and take some of its hair and put that hair onto your skin where the dog had bit you. Later, this same idea was used for other illnesses. The idea that if you got sick from something, the way to get better would be to have a little bit more of that something. So, if you drank too much alcohol, and the next morning you weren’t feeling very well, the cure was to drink even more alcohol. A lot of people do this still today. The general idea then of “hair of the dog that bit me,” which is more commonly just used in the form “hair of the dog,” is that you need to have more of whatever hurt you in order to get better, which doesn’t make a lot of sense but, then again, if you’re drinking a lot, it doesn’t really matter.
David (David) from Germany gets our last question. He wants to know about the pronunciation of certain words and expressions that he thinks sound alike. He’s right – he’s correct – that several of them do. Let’s start with “You are right (right),” meaning you are not wrong. The word “right” in that expression is pronounced exactly the same as “write,” which means to use your fingers to communicate with someone else. You write a letter. “To write a letter,” “you are right” – both words pronounced “right” – sound the same. The word “right” is also pronounced the same in an expression such as “Go right at the corner instead of going left.”
Two other words that David asked about, however, have slightly different pronunciations. They’re different words, spelled differently. The first one is “riots” (riots). “Riots” are when people get very loud and violent, usually coming together as a group and destroying property and causing problems for the police. That’s “riots.” “Riots” is pronounced differently than right – “riots,” “right.” The other word David wanted to know about is “ride” (ride). “I ride my bike.” Once again, a different pronunciation – “ride,” “riots,” “right.”
If you have a question or comment, you can write us. We promise not to ride away on our bike before answering your question. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2013 by the Center for Educational Development.
Glossary
limited – with restrictions; not including everything
* They have a very limited budget for the wedding, so they have to choose between flowers and live music.
taxa – the plural form of taxon, which is a group of populations of an organism that are considered as a group
* Who determines the scientific names for new taxa?
citizens science project – a science project that many people are involved in, and where those people don’t necessary have a lot of scientific training or education, but they are able to participate by collecting data and sharing it with the scientists
* Chantrelle is participating in a citizens science project that’s searching for a cure for cancer by allowing research labs to use her computer to analyze molecules via the internet.
sample – a small part of something, usually for testing
* Scientists can take a sample of skin cells from the inside of your cheek to find out which part of the world you ancestors came from.
to involve the public – to get ordinary people involved in a project, not just specialists or experts
* Our nonprofit organization tries to involve the public by offering lots of interesting volunteer opportunities.
mobile technology – devices that can be moved around easily and are able to communicate with other devices
* Mobile technology is advancing so quickly! The phone I have today is more powerful than many computers were 15 years ago.
latitude – the imaginary horizontal (side to side) lines that go around the globe, parallel to the equator, used to identify specific locations on the earth’s surface
* The Tropic of Cancer, the Tropic of Capricorn, and the Equator are three lines of latitude that have special names.
longitude – the imaginary vertical (up and down) lines that are drawn from the North Pole to the South Pole, used to identify specific locations on the earth’s surface
* At which longitude is the international date line?
to attend – to be present at, such as a meeting, class, school or special event
* How many people attended the conference?
to take part in – to be a member of a group activity
* Everyone took part in the meal preparation.
to participate in – to have a part in an activity; to share with others in an activity or benefit
* Elliot won’t be participating in the Christmas concert because he is Jewish.
to join – to become a member of; to accompany (go with) someone else
* How old were you when you joined Toastmasters?
standalone – an item that does not require any other components (parts) in order to work
* Is this a standalone system, or will we need to buy a lot of other parts?
to stand alone – to be different or independent; to be better than average at something
* As a translator, Lydia stands alone. Nobody else can express the original ideas as clearly as she does.
hair of the dog that bit me – an expression referring to curing a discomfort by the same method that caused the discomfort in the first place, now used most often to refer to drinking additional alcohol as a treatment for a hangover
* I have such a headache! I need some hair of the dog that bit me.
What Insiders Know
Popular TV Science Shows
Many Americans enjoy watching science shows on TV. One of the most popular science shows in Nova, which is broadcast on “PBS” (public broadcasting service, a public television channel). The show began in 1974, and since then, there have been almost 700 Nova episodes. The episodes explore specific scientific topics. Many of the episodes include interviews with “researchers” (people trying to gather information and answer questions about a specific topic) working in the “field” (a specific type or area of science). Sometimes the episodes focus on the history of science, “examining” (considering in detail) how the field has developed over time. The episodes have been “praised” (complimented; admired) for clear writing that allows non-scientists to “grasp” (understand and appreciate) complex scientific topics.
The Science Channel is a private channel that produces many TV programs about science. The different programs cover everything from space and technology to animals and “prehistory” (what happened before people began documenting events in writing), but there is also an “entertainment factor” (a large part of many shows is designed to entertain people more than to inform them).
Many people “have a soft spot for” (remember fondly) Bill Nye the Science Guy, a program (and the name of the main character) that was created for children. The show uses “wacky” (crazy, unusual and entertaining) songs, “sound effects” (sounds that emphasize what one sees) to teach children about science and explain “natural phenomena” (things that happen in the world around us). Between 1993 and 1998, 100 episodes were aired on PBS Kids, and some of them can still be seen on TV today.