= 1678
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 373.
This is English as a Second Language Podcast: English Café episode 373. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. You can also take a look at our ESL Podcast Store and our ESL Podcast blog.
On this Café, we’re going to talk about a group of famous Americans, some would say “infamous” Americans, called the “Chicago Seven.” We’re also going to continue our series on American authors – writers – focusing on Horatio Alger. And as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion of the “Chicago Seven.” These seven people were famous in the late 1960’s. Some would say they were “infamous.” If you say someone is “infamous” (infamous), you mean they were famous but for a bad reason. They had done something wrong. Well, depending on how you look at it, the Chicago Seven were famous or infamous. Here’s their story.
It all started with the 1968 Democratic National Convention in Chicago, Illinois. Illinois is located in the Midwest part of the United States. Chicago is one of our largest cities. Every four years, our two political parties have a large meeting, what is called a “convention.” The Democrats have their convention and the Republicans have their convention. The purpose of these conventions is to select the person who will represent the party in the presidential election of that year.
Well, 1968 was a presidential election year, and, then-President Lyndon B. Johnson had announced that he was not going to try to become president again for another term – that is, for another four years. Johnson had become president when John F. Kennedy was killed in 1963 and won election in 1964. But in 1968, in part due to the problems of the Vietnam War, Johnson decided not to run for another term as president. Instead, the convention chose a man from Minnesota, from my home state, a man by the name of Hubert Horatio Humphrey. He was called “Hubert H. Humphrey.”
In the late 1960’s, as I eluded to or mentioned earlier, the United States was involved in a war in Southeast Asia – the Vietnam War, it’s called. It was very unpopular, or at least becoming very unpopular with large sections of the population, especially among young Americans. Many young radicals decided to protest against President Johnson’s policies during the 1968 Chicago convention. A “radical” (radical) is someone with extreme political views, someone who often will do things that will get the attention of the media. Not, of course, all of the people protesting in Chicago were radicals. Most of them were not. But there were some among the protesters – the people who were trying to oppose or go against Johnson’s policies in Vietnam – who were, in fact, political radicals. The radicals requested or asked for permits – official permission – to have protests and rallies. “Rallies” are large meetings near the site of something that’s going on. This happens in American politics and probably every country of the world. You have rallies for certain political causes, and it was no different back in 1968. However, the mayor of Chicago didn’t like these radicals – one of the most famous mayors in 20th century American history, Richard Daley. Daley said no to the request by the radicals to have rallies, but they decided to have the rallies anyway, even without permission. After one very large rally, where there was about 15,000 people, some of the protesters decided to “march,” or to walk as a group, to the site of the convention.
The police stopped them and the situation very quickly became violent. The fighting between the radicals and the police lasted for five days and there were many protesters and police officers who were hurt. And of course, many people were arrested. They were taken by the police and put in jail. Once the fightings stopped, a group of eight people were charged with “crossing state lines to incite a riot.” “To cross state lines” means that you go from one state to another, and there are certain crimes in the United States that you can be arrested for, especially if you go from one state to another.
It’s kind of a strange thing, but remember the United States is a republic. It’s a collection of states that form one country, but each state has its own laws. So, if you go from one state to another for the purpose of breaking the law, that is another criminal offense. It’s a special kind of criminal offense, a special kind of crime. This crime was “inciting a riot” in the case of the Chicago Eight. “To incite” (incite) means to encourage. A “riot” (riot) is a public disturbance. It’s when people start yelling and screaming and doing violent things. So, to incite a riot is a very serious crime. There were eight people who were arrested and charged with inciting a riot. These were all radicals who the police said had organized these rallies and had organized the violence that took place after the rallies and during the rallies. They were eight of them arrested but one of them was later separated from the group. And so, the group – the main group – became known as the Chicago Seven.
There were several well-known radical groups in the late 1960’s that participated in these protests, some of whom also were involved in violent acts against the government. The Black Panthers and the Weather Underground, sometimes called the Weathermen, were two of those groups. There was a lot of interest in the trial, in the legal process against these seven people – the Chicago Seven. The lawyers or attorneys used the trial as an opportunity to speak out against the Vietnam War. The Chicago Seven were very rude and insulting to the judge, but they got a lot of publicity, a lot of media attention for the protest effort against the Vietnam War. They sort of became heroes to many people in the Vietnam War protest movement. Many famous folk singers and writers used the trial as an opportunity to speak out against the war – to oppose the war publicly.
In 1970, almost two years after the 1968 convention, the jury – the group of people who were deciding whether the Chicago Seven were guilty or innocent – reached its verdict. A “verdict” (verdict) is the decision that the jury comes to after talking about it. Typically, a jury in the United States is composed of 12 men and women. Two of the defendants were acquitted, were found not guilty of any of the charges. So, two of the seven were innocent. The other five were found guilty of “intent” (intent) or planning a riot. They were each told to pay $5,000 and spend five years in prison or jail. However, two years later, the convictions were reversed, meaning that a higher court decided they were not guilty. Later, a U.S – a national group, a national commission – determined that the violence had been, in many ways, the fault of the police, and that the police were responsible for much of the violence that the protesters and the Chicago Seven were blamed for.
The individual members of the Chicago Seven became famous, some of them quite famous. Two of them were Tom Hayden and Abbie Hoffman. Tom Hayden, after becoming famous as a member of the Chicago Seven, continued to be a political activist, fighting against the Vietnam War in the early 70’s. He later came to Southern California and became a politician. He actually represented part of Southern California very close to where I live. Hayden was also famous for marrying a famous actress – one of the most famous protesters against the Vietnam War. You probably heard of her. Her name is Jane Fonda. She was the daughter of the great actor, Henry Fonda, and later went on to marry another famous American, Ted Turner. Well, Hayden became a political activist and a government official. He also started a number of organizations for left-wing or progressive political causes. Right now, he works at a political center, about maybe five minutes from where I live, in Culver City, California.
Abbie Hoffman, the other famous member of the Chicago Seven, was an activist but later became disappointed at how the radicals and activists from the 1960’s changed as they got older. Of course, people change as they get older and many people who are politically liberal in their younger years sometimes become more politically conservative. Abbie Hoffman complained about this change in people as they got older and was famous for his complaints about that. He died in 1989, unfortunately, from drinking too much alcohol in combination with some medicine he was taking. Some people thought, and still think today that he was, in fact, trying to kill himself, to, we would say, “commit suicide.” Depending on your political views of the Vietnam War and of American politics, the Chicago Seven were a group of heroes or a group of people who were damaging American politics during the late 60’s.
Now let’s turn to our next topic which is a continuation of our series on American writers, American authors. Today we’re going to talk about one of the most famous writers that I’m guessing most Americans have heard of but have never read. His name is Horatio Alger Jr.
Horatio Alger Jr. was born in the state of Massachusetts in the northeastern part of the United States, way back in 1832. He wrote about 100 novels. Yes, you heard me correctly: 100 novels or fictional books! All of them, or most of them, had a very similar plot, a very similar story. It’s what we call the “rags to riches” story. And you’ll hear that expression still today. People will talk about a “rags to riches” story. A “rag” is a small piece of old fabric, often taken from a piece of clothing like an old shirt. You know sometimes how you have an old shirt that you’re not going to wear and you cut it up so you can use the parts of it to clean things with and so forth. That’s a rag.
Someone who dresses in rags doesn’t have enough money to buy new clothes – new nice clothes. So rags can also mean clothing that is old and dirty, probably torn, ripped, has holes in it – that sort of thing. “Riches,” obviously, is having a lot of money. So a “rags to riches” story describes someone who starts their life poor, starts their life in poverty we might say, without a lot of money, but then works very hard and is able to become successful and wealthy, or rich.
The “rags to riches” story is an important part of this larger idea that we’ve mentioned on Café’s previously called “The American Dream” – with “Dream” capitalized – a capital D. The American Dream means something different to different people, but the general idea is that the United States is the land of opportunity. It’s a place where anyone who works hard can become successful and create a better life for himself and his children. Some people say, “I’m living the American Dream;” that is, I’m doing what America is famous for, people coming from other countries and then becoming successful. They were poor and now they’re rich, or someone who is born poor here in the U.S and then works hard and becomes rich. That’s the American Dream. And “dream” here really means the goal, what everyone wants to happen for themselves. The American Dream was and is an important part of what we might call the American mythology, the American idea about themselves. Every country has their own idea about what their country represents, the values and the ideals of that country.
During the 19th century, there was a very strong entrepreneurial spirit among Americans. “Entrepreneurial” (entrepreneurial) refers to an interest in starting your own business and becoming successful. Every American wanted to have their own company, their own business. At least that was the idea of some people writing about the 19th century in the 19th century. That was the dream, part of the American Dream. And Horatio Alger’s books – for example, a book called “Ragged Dick” (“Dick” being a short form of Richard) – the main character was almost always a young man, and the young man became successful through hard work and perseverance. “Perseverance” (perseverance) is your willingness to continue working, to continue struggling even in a difficult and challenging situation. You never give up. Horatio Alger’s characters were also very honest. They always told the truth. They never lied.
Horatio Alger wrote his books mostly for young boys, not for adults. And they were extremely popular. You know how popular a book such as Harry Potter is, and has been in the last decade or so. Well, Horatio Alger’s books were like that. They were extremely popular among young boys in particular. He wrote many books with the same basic ideas – the same characters, the same people. But over time, people became less interested in reading about these perfect characters, and Alger began to change his novels to keep his readers interested. He began, for example, to add parts of the story that had murder and violence.
Overtime, the quality of his novels “deteriorated”; that is, they became worse. Alger died in 1899, but before he did, about 20 million copies of his novels were sold. Even though, as I mentioned they were generally considered to have poor literary quality. It wasn’t great writing but it was the kind of story that people wanted to read. Like most Americans, I’ve heard of Horatio Alger, mostly because of people referring to him in talking about the “rags to riches” story. They may say something like, “It’s like a Horatio Alger story, a rags to riches story.” That’s a common cultural reference, or at least, it used to be. However, I’ve never actually read one of Horatio Alger’s books. My guess is they’re probably on the Internet for free somewhere, maybe I’ll go find one and read it.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Adam (Adam) in Slovakia. Adam wants to know the meaning of the words “murderer,” “assassin” and “killer.” Wow, what a happy question, Adam! “Murderer” (murderer) is a person who murders. “To murder” is to kill another human being. “Killer” (killer) is someone who causes the death or kills something else. It could be an animal or a person. “Assassin” (assassin) is a person who kills an important member of a government or someone who is paid to kill an important person in the world.
“To kill” is killing someone no matter what you do. It could be an accident. It could be on purpose, intentionally. “To murder” is always to kill on purpose and when we use the term, we’re generally talking about things that are against the law. In fact, to murder is almost always something we can consider illegal. If it weren’t illegal, we wouldn’t call it murder. “To assassinate” is to be, typically paid to kill an important person. So, when the president of the United States is murdered – is killed – we call the person who killed him, an “assassin.” John F. Kennedy was the last American president who was assassinated, although other American presidents, such as Ronald Reagan, have had assassination attempts – people have tried to kill them.
“Killer” is also an informal word that we use as an adjective rather than a noun. Someone will say, “This is a killer car,” or “That’s a killer dress.” They usually mean it is something that is really great. Sometimes, “killer” can mean a thing that is very difficult or describes something that is very difficult. “That test was a killer,” or “That was a killer test,” meaning it was a very difficult test. So, it has taken on some other meanings, killer has, over the last several years. The word “murderer” can also be used for a very difficult situation. “This heat is murder,” meaning it’s very difficult. It’s very challenging. Or “That test was murder.” It was very tough. It was very hard.
Jet (Jet) from Korea wants to know how we use a certain phrase that is common in conversational English, “and all,” especially at the end of a sentence. For example, “She can’t meet you since she’s not feeling well and all,” or you might say, “Well, we can’t really buy that car. It’s really expensive and all.” The idea of the phrase “and all” is that there’s something more that we could say but we aren’t going to tell the other person. Perhaps the other person knows the other reasons why or knows what else the phrase “and all” refers to. Usually, the other person knows that so we don’t have to tell them. “It sounds fun and all,” meaning it sounds fun and perhaps it’s going to be a good time. It’s going to be exciting. It means that there’s something more but we don’t have to say it. We often follow a sentence that ends in “and all” with a sentence beginning with “but.” “That sounds fun and all, but I can’t go because I have to work,” or “I’d really like to go with you and all, but I have to go home and take my dog for a walk.” So, we follow with a phrase that indicates why we can’t do something or why perhaps, we don’t agree with something. Well, that’s a good idea and all but I don’t really have time for it.
Finally, Hazel (Hazel) in Hong Kong wants to know the difference between the phrase “so forth” and “so on.” “So forth” and “so on” really mean the same thing. It means et cetera – continuing in the same manner or the same way or “and more.” You’ll often hear the two phrases used together. “So forth and so on,” or “so on and so forth.” For example, “Jennifer Anniston has lots of money and good looks and so forth,” meaning she has other things too that are also good and positive, or “He started to name all of the states in the United States beginning with Hawaii, and moving east – Hawaii, Alaska, California, Oregon, Washington and so on, and so on, and so on.” Sometimes, we’ll say the phrase three times to show that the person talked for a very long time – continued in the same way or in the same manner. You could also use the word “et cetera.” And you will hear people say, “et cetera, et cetera, et cetera.” It has the same meaning.
If you have a question or comment and you would like us to try to answer it, email us. Our email address is eslpod@eslpod.com. We get too many questions to answer all of them on our Café and it may take us a while to get to your question but we’ll do our best.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast: English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2012 by the Center for Educational Development.
Glossary
defendant – a person who is defending oneself against charges or accusations in a court of law
* The defendant told the court that the police arrested the wrong person and he was not even in the area when the crime was committed.
convention – a very large meeting where members of a political party meet to hear speeches and decide whom the political party will nominate for the presidential elections
* Political leaders and celebrities gave speeches during the convention.
radical – someone with extreme beliefs who takes extreme actions to draw attention to those beliefs and try to get other people to believe the same things
* Nick is a radical who believes that technology is ruining our lives and that we should all live without it.
rally – a large meeting to show one’s political beliefs or to give support to a cause
* Are you going to the rally to protest the elimination of services for immigrants?
to incite a riot – to encourage other people to create a public disturbance and to fight against the police
* Why did you say those hateful things to the crowd? Do you want to incite a riot?
verdict – for the judge or the members of a jury to reach agreement on whether someone on trial is guilty or not guilty
* The jury reached a guilty verdict after only two hours of discussion.
intent – a plan to commit a crime; a decision to do something before taking action
* If the court believes Louise had intent to sell illegal drugs, he could go to jail for years.
rags-to-riches – describing someone who starts life without much money, but then works very hard and is able to become successful and rich
* Julia’s life is a rags-to-riches story, with her only becoming successful after twenty years living in poverty.
American Dream – the idea that the United States is a land of opportunity where anyone who works hard can become successful and create a better life for oneself and one’s family
* People come to the United States hoping for the American Dream, but only some achieve it.
entrepreneurial – a strong interest in and desire to start a business and become successful
* Kyung has always been entrepreneurial, even as a teenager when he started his own lawn mowing business.
perseverance – a willingness to continue to do something even in very difficult and challenging situations, never giving up
* The only way to succeed in a poor job market is through perseverance.
to deteriorate – to become worse; to worsen
* Dan’s condition deteriorated for several days before he began to recover.
murderer – a person who killed another human being
* In the film, the police detective caught the murderer while he was trying to kill a second person.
killer – someone or something that caused the death of someone or something; destroyer
* Our dog is very fierce and if anyone threatened the children, the dog could turn into a killer.
assassin – a person who kills an important person in politics or the government; a person who is paid to kill another, especially political or high-ranking people
* The assassin tried to kill the president by using a gun.
...and all – et cetera; and everything else
* I know it’s raining and cold and all, but I still want to go to the movies!
so forth / so on / so forth and so on – et cetera; continuing in the same manner or way; and more
* There is a lot work to do to prepare for the event: set up chairs, prepare the food, so forth and so on.
What Insiders Know
Chicago: The Musical
In 2002, a film called Chicago won many awards and received a lot of attention around the world. What some people may not know, however, is that that movie was based on a “musical” (a play in which songs and some of the actors’ lines are sung to music), also called Chicago.
Chicago is based on a play written by a reporter that “covered” (reported on) many criminal trials during the 1920s, many of which involved celebrities. The story takes place during the “Prohibition Era,” when alcohol was illegal to buy and sell in the U.S., but was still easily found in “underground” (not legal) bars and clubs. The main character in the play, Roxie Hart, goes to jail for killing the man she was having an “affair” (a romantic relationship outside of marriage) with.
Once in jail, Roxie realizes that murder can bring even more fame than being an actress or a singer would, and she and her “cellmate” (the woman with whom she shares a “cell,” small room for prisoners to live and sleep in), Velma, began to “compete” (try to win) to see who could create the most “sensational” (outrageous or surprising) news stories. It doesn’t take long for the women to realize that there are serious “consequences” (results) to their actions and their “celebrity” (being famous and well-known by many people).
The musical version of Chicago began on “Broadway” (a street full of theaters in New York, on which many famous plays have been performed) in 1975 and featured “choreography” (the style of dance created by a person or group) by Bob Fosse, one of the most famous choreographers of all time. It was so popular with audiences that there were 936 performances of it before it ended its “run” (period of time a show continues to have performances). In 1996, the show was brought back with new actors as a “revival” (the performing of an old play once again, sometimes with additional parts) and as of 2012, it is still being performed. “To date” (from the beginning to now), there have been over 6,200 performances of the revival, making it the “longest-running” (performed without stopping) Broadway musical of all time.