= 1059
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,059 – Feeling Restless and Jumpy.
This is English as a Second Language Podcast episode 1,059. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast; when you do, you can download the Learning Guides for all of our current episodes.
This episode is all about describing someone who is restless and jumpy. Let’s get started.
[start of dialogue]
Adam: Sit still and stop bouncing your leg like that!
Ellen: Sorry, I didn’t realize I was doing it. I’m just a little jittery.
Adam: Well, try to chill out. We’re supposed to be studying, and your restlessness is distracting.
Ellen: I can’t help it. I’m like this because I had a lot of coffee. That’s the only way I can do an all-nighter.
Adam: But how can you study when you’re fidgeting all the time? Stop tapping your pen on the table!
Ellen: Sorry. It’s either I’m worked up or I fall asleep, and tomorrow’s test is a make-or-break one for me. I’ve got to do well.
Adam: I don’t see how you can get any studying done when you’re strung out on caffeine. You’re so jumpy, and I think you’re starting to twitch. Why don’t you try to counteract the caffeine by drinking lots of water?
Ellen: Do you know how long it took me to get this keyed up? I’m not doing anything to reduce the effects.
Adam: Fine.
Ellen: Hey, where are you going?
Adam: Anywhere but here!
[end of dialogue]
Adam and Ellen are college students. They are studying for a test – they are preparing to take an examination. Adam says to Ellen, “Sit still and stop bouncing your leg like that!” When you tell someone to “sit still” (still), you are telling him to sit calmly, to sit without moving his arms or his legs. Usually it’s something you would say to a young child – for example, at a restaurant, when the child is moving around too much: “Sit still!” Adam is telling Ellen, however, to sit still.
He says, “Stop bouncing your leg like that!” “To bounce” (bounce) something is to move it up and down, usually against the floor or some other flat area or surface. When you think of a basketball, for example, you imagine it bouncing up and down. It goes up and down between the hand and the floor. Ellen isn’t bouncing a ball. She’s bouncing her leg up and down against the floor, and Adam is telling her to stop it.
Ellen says, “Sorry, I didn’t realize I was doing it. I’m just a little jittery.” “To be jittery” (jittery) means to be nervous, to be unable to relax. Often when you’re jittery, your hands shake a little or your body moves a little, almost involuntarily. Sometimes you’re jittery because you’re excited about something. Sometimes you’re jittery because you’re nervous about something.
Adam says, “Well, try to chill out.” The phrasal verb “to chill (chill) out” means to relax, to stop worrying, to stop feeling depressed. It’s an expression that was quite common 20, 30 years ago. I’m not sure how common it is today, but people still say it: “Chill out.” You don’t want to say this to someone you don’t know well, however. You wouldn’t want to say it to your boss, for example. The expression has something of a criticism in its tone, and so it’s something you would say to a friend, perhaps, or to your spouse or your children, but not something you would say to someone in authority over you.
Adam tells Ellen, however, to chill out. He says, “We’re supposed to be studying, and your restlessness is distracting.” “To be restless” (restless) means something similar to “to be jittery.” If you’re restless, you’re moving around all the time because you’re nervous. “Restlessness” is just the noun that refers to the state of being restless. Adam is saying that Ellen’s restlessness “is distracting.” Something that is distracting is something that makes it difficult for you to concentrate or to focus on something. It takes your attention away from where it should be.
Ellen says, however, “I can’t help it.” “I can’t help it” means I can’t stop myself from doing it; I can’t prevent it. “I’m like this,” she says, “because I had a lot of coffee.” “To have a lot of coffee” is to drink a lot of coffee. If you drink a lot of coffee, it may make you jittery because of a certain chemical in the coffee called “caffeine.” Ellen says, “That’s the only way I can do an all-nighter.” Ellen is saying the only way she can do an all-nighter is to drink a lot of coffee.
What’s an “all-nighter?” An “all (all) – nighter (nighter)” is when you study all night long for a test the next day. At least, that’s the most common use of the term. We often use the verb “to pull” with “all-nighter.” “I’m going to pull an all-nighter.” That means I’m going to study all night without sleeping for a test the next day. Now, you could also pull an all-nighter to complete a report or to complete a paper.
Generally speaking, pulling an all-nighter is not a good idea if you are studying for a test, because you’ll be so tired the next day, you’ll probably perform worse on the test than you would have if you had simply slept, even though you studied more. To pull an all-nighter to complete a paper probably doesn’t matter, since the idea is that once you complete the paper, you’re done and you can go to sleep.
I’ve pulled an all-nighter only once in my academic career. I remember it very well. I was writing a paper about the Battle of Bannockburn in Scotland, one of the most famous battles between England and Scotland, and I had to get this paper completed by the next morning. So, I stayed up all night typing, as one did, on my typewriter, since this was before the days of computers. I did finish the paper and I got a pretty good grade on it, thank you very much. But that was the only time I ever pulled an all-nighter. Anyway, it all brings back memories.
Adam says, “But how can you study when you’re fidgeting all the time?” “To fidget” (fidget) means to make small, rapid or quick movements repeatedly, possibly without even being aware of it. When you’re nervous, for example, or jittery you might move your finger up and down, or your leg up and down, without noticing that you’re doing it – without being completely aware that you’re doing it. Adam can’t understand how Ellen can study when she’s fidgeting all the time.
Then Adam says to her, “Stop tapping your pen on the table!” “To tap” (tap) something with your finger would be to hit it with your finger repeatedly. You can also tap on a wall, for example. You could use your fist to hit the wall repeatedly. That’s “tapping.” Adam is telling Ellen to stop tapping the pen on the table. Ellen says, “Sorry. It’s either I’m worked up or I fall asleep.” Ellen is saying there are one of two possibilities right now: either she falls asleep or she gets worked up. “To be worked up” means to have a lot of energy, to have a lot of nervousness or anxiety.
Ellen says, “Tomorrow’s test is a make-or-break one for me.” The phrase “make-or-break” means it’s something that is extremely important. It’s something that will decide whether you succeed or fail at something. A make-or-break test would be one that would determine, for example, if you are going to pass a class or not. Ellen says, “I’ve got to do well,” meaning “I have to do well on the test.”
Adam says, “I don’t see how you can get any studying done when you’re strung out on caffeine.” “To be strung (strung) out” on some substance or drug means to be affected in a very negative way, usually because you’ve taken a lot of a certain drug. Ellen has drunk a lot of coffee, and therefore consumed a lot of “caffeine” (caffeine). “Caffeine” is the chemical substance found in coffee, as well as other drinks, that can make you feel awake and energetic, but could also make you, if you drink too much of it, jittery and nervous.
Adam says to Ellen, “You’re so jumpy, and I think you’re starting to twitch.” “To be jumpy” (jumpy) means something similar to “to be jittery.” It means to be nervous, to be anxious, to be moving around. “To twitch” (twitch) means to move one part of your body very quickly and sometimes uncontrollably. When I have a bad allergic reaction – when my allergies are bothering me – sometimes my eye twitches. It moves involuntarily without me wanting it to. (Technically, my eyelids twitch, not my actual eyes.)
Adam then says to Ellen, “Why don’t you try to counteract the caffeine by drinking lots of water?” “To counteract” (counteract) means to try to stop or prevent something else that is happening by doing something opposite of that, or to do something that somehow balances it out. If you start to get sleepy, you could counteract your sleepiness by drinking coffee with caffeine in it. What Adam is suggesting here is that Ellen try to counteract the effects of the caffeine by doing something else: by drinking a lot of water.
I’m not sure if drinking a lot of water counteracts the effect of caffeine, but Adam seems to think so. Ellen says, “Do you know how long it took me to get this keyed up?” “To be keyed (keyed) up” is to be very excited or nervous or stressed. She says, “I’m not doing anything to reduce the effects,” meaning, in this case, to make her less jumpy, less jittery. Adam then says, “Fine,” meaning “okay.”
Ellen says, “Hey, where are you going?” Adam has started to get up and leave. Adam says, “Anywhere but here.” Adam doesn’t want to stay with Ellen because she’s distracting him. That’s why he says, “Anywhere but here.” The use of the word “but” here means “except” – anywhere except here, anywhere that isn’t here, if you will.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Adam: Sit still and stop bouncing your leg like that!
Ellen: Sorry, I didn’t realize I was doing it. I’m just a little jittery.
Adam: Well, try to chill out. We’re supposed to be studying, and your restlessness is distracting.
Ellen: I can’t help it. I’m like this because I had a lot of coffee. That’s the only way I can do an all-nighter.
Adam: But how can you study when you’re fidgeting all the time? Stop tapping your pen on the table!
Ellen: Sorry. It’s either I’m worked up or I fall asleep, and tomorrow’s test is a make-or-break one for me. I’ve got to do well.
Adam: I don’t see how you can get any studying done when you’re strung out on caffeine. You’re so jumpy, and I think you’re starting to twitch. Why don’t you try to counteract the caffeine by drinking lots of water?
Ellen: Do you know how long it took me to get this keyed up? I’m not doing anything to reduce the effects.
Adam: Fine.
Ellen: Hey, where are you going?
Adam: Anywhere but here!
[end of dialogue]
Our scriptwriter, Dr. Lucy Tse, never pulls an all-nighter to write her wonderful scripts. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
to sit still – to sit calmly without moving
* How do elementary school teachers get that many kids to sit still all day?
to bounce – to move up and down against the floor or another surface with energy
* How many times can you bounce the basketball with just one hand?
jittery – nervous with many small movements and unable to relax
* Is it normal to feel this jittery before speaking in front of an audience?
to chill out – to relax and stop worrying or feeling stressed
* Why are you working so hard? Chill out! The boss won’t be back until Thursday.
restlessness – the condition of being unable to rest or relax, often wanting to move or do something else, especially if one is very nervous or anxious
* Jack doesn’t like to work in one job for more than a few months and quits when he can’t control his restlessness.
distracting – making it difficult for someone to concentrate on something; taking someone’s attention away from where it should be
* Isn’t that music distracting when you’re trying to write a letter?
all-nighter – a study session that continues through the entire night, without allowing any time for sleep
* When Jan was in high school, she often pulled an all-nighter before an important exam, but now that she’s middle-aged, it’s difficult to stay awake past midnight.
to fidget – to make many small, quick movements repeatedly, possibly without being aware of it, especially when one is nervous or worried
* The patient’s husband is pacing and fidgeting in the waiting room, anxious to hear what the doctor will say.
to tap – to gently hit an object or body part against the surface of something, making a slight noise
* The music was so good that almost everyone was tapping his or her toes on the floor.
worked up – anxious or worried about something and unable to relax or think about something else
* Why are you so worked up about this presentation? You’ve made similar presentations before. This time you’ll just have a bigger audience.
make-or-break – something that is extremely important and decides whether a person will succeed or fail
* This audition could be a make-or-break moment in a young actor’s career.
strung out – affected in a negative way by using too much of a drug
* That man is strung out on heroin or cocaine. Should we call the police, or take him to the hospital?
caffeine – the chemical substance found in coffee, tea, soda, and chocolate that makes people feel more awake and energetic
* Wow, this energy drink has as much caffeine as four cups of black coffee!
jumpy – nervous, uneasy, and anxious
* They’re really jumpy, because they’re waiting for their realtor to call and let them know if their offer on the home has been accepted.
to twitch – to move part of one’s body quickly and unexpectedly, especially uncontrollably
* When Gregorio gets tired or stressed out, sometimes his eyebrow starts to twitch.
to counteract – to act against some other force or trend to try to make it stop; to balance out something through one’s actions
* We’ll have to run several miles to counteract all the calories in that cheesecake!
keyed up – feeling very excited, nervous, or stressed
* The bride’s mother is really keyed up for the wedding.
but – except
* We put everything but the cans of soda in the fridge.
Comprehension Questions
1. Why does Adam find Ellen distracting?
a) Because she is too beautiful
b) Because she is making too much noise
c) Because she is moving around too much
2. What is a make-or-break test?
a) A test where one has to receive a perfect score
b) A test that has a significant impact on one’s grade or ability to graduate
c) A test that requires guessing if one doesn’t know the answer
Answers at bottom.
What Else Does It Mean?
worked up
The phrase “worked up,” in this podcast, means anxious or worried about something and unable to relax or think about something else: “After the earthquake, everyone was worked up about the possibility of a tsunami.” The phrase “to work (something) up” means to develop a document, especially to create a budget or design: “Will you be able to work up the sales projections before our next meeting?” The phrase “to work up the courage to do (something)” means to make oneself feel brave and do something that is very scary or intimidating: “Do you think Saho will ever work up the courage to ask Patty out on a date?” Finally, the phrase “to work up an appetite” means to do an activity that results in one becoming hungry: “Hiking all morning worked up their appetite.”
jumpy
In this podcast, the word “jumpy” means nervous, uneasy, and anxious: “Lynn is afraid of heights and water, so she always gets jumpy when driving over a bridge.” As a verb, “to jump” can mean to increase significantly and quickly: “The mayor is concerned about the big jump in crime.” The phrase “to jump from (something) to (something)” means to change topics or activities quickly: “Clark jumps from sport to sport, but he still hasn’t found something he wants to play for more than a few weeks.” Finally, the phrase “to jump the gun” means to do something too soon: “Your baby boy is only a few weeks old. Don’t you think you’re jumping the gun by buying him a basketball?”
Culture Note
The Jitterbug
The Jitterbug was a very popular dance in the United States in the early 1900s. The name of the dance is “derived from” (based on) the word “jitters” which was a “slang term” (a word that is used by many people, especially among young people, but that is not considered proper) used to refer to alcoholics who “trembled” (moved uncontrollably and were not able to be still) uncontrollably. In the early 1900s, “jitterbug” began to be used to refer to dancers who did not seem to have control of the dance.
The term “jitterbug” was used to describe several kinds of “swing dancing” (a style of dance, usually with two people, performed with a large band and possibly jazz-style music). The jitterbug is an “acrobatic” (similar to the ways in which circus performers move their body) dance that is “physically demanding” (difficult to do with one’s body) and requires “flexibility” (the ability to move body parts further than most people can) and a lot of energy.
The jitterbug became very popular during World War II. At first, the dance was seen as “rude” (not polite) and inappropriate by many Europeans, but it soon became popular internationally. In 1957, a show called American Bandstand
made the jitterbug even more popular by showing “live” (happening in real time, not recorded previously) jitterbug dancers as they danced to live music in the “studio” (the large room where a TV show or movie is filmed).
Comprehension Answers
1 - c
2 - b