= 1071
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
This is English as a Second Language Podcast episode 1,071. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast. When you do, you can download a Learning Guide for this episode.
This episode is a dialogue between Florence and Alexander about getting new drugs, especially new drugs that need to be approved by the government. Let’s get started.
[start of dialogue]
Florence: A package came for you. I think it’s from overseas.
Alexander: Oh, those are my drugs.
Florence: You’re buying your medication from overseas?
Alexander: I have no choice. This drug isn’t FDA-approved yet.
Florence: Isn’t it dangerous to take a drug that isn’t approved?
Alexander: Not if it’s been approved in other countries. This drug is considered experimental here, but has been used in other countries safely for years.
Florence: But shouldn’t you just wait? How long could the process take anyway?
Alexander: You have no idea. It can take years for a drug to be approved here, especially those that aren’t fast-tracked.
Florence: That’s hard to believe.
Alexander: It’s true. First, it has to be tested on animals or in a lab, and then it has to go through clinical trials. Only then is it put through a rigorous review by the FDA, which alone can take years.
Florence: You’re right. I had no idea.
Alexander: In the meantime, I’m suffering needlessly.
Florence: You can’t legally import the drug for your own use, right?
Alexander: That’s right, but I feel like I have to circumvent the law to get the medicine I need.
Florence: So how does it feel to be an outlaw?
Alexander: Um, healthy?
[end of dialogue]
Florence begins our dialogue by saying to Alexander, “A package came for you.” A “package” would be like a small box or perhaps an envelope. When something “comes for you,” it arrives for you, usually in the mail. Florence says, “I think it’s from overseas.” In the United States we use the term “overseas” (overseas) to refer to other countries.
Now technically, in the U.S., Mexico and Canada are not overseas because you don’t have to go over an ocean – “sea” is another word for “ocean” – in in order to get there, but it’s a general term we use to mean from a foreign country, from another country – specifically, from Europe or Asia or Africa – if you’re in the United States, that is.
Alexander says, “Oh, those are my drugs.” “Drugs” are medication, medicine that you take because you are sick, or for some other reason. Some people take drugs even when they’re not sick. You’ll sometimes hear the word “drugs” used to mean illegal drugs (drugs like cocaine, heroin, and marijuana) but it can also be used to refer to what we call “prescription drugs” – drugs that you get from your doctor because you are sick – or simply drugs such as aspirin or other kinds of drug you can buy without the approval of a doctor.
Florence says to Alexander, “You’re buying your medication from overseas?” “Medication” is just another word for drugs – things that you take to make you feel better or to get healthy. Alexander says, “I have no choice” – I have no option. “This drug isn’t FDA-approved yet.” “To be approved” means that someone or some organization says it’s okay to use or to buy. The “FDA” is the official government organization in the United States that approves of drugs. FDA stands for “Food and Drug Administration.”
Florence says, “Isn’t it dangerous to take a drug that isn’t approved?” Alexander responds, “Not if it’s been approved in other countries.” Florence is asking if he, Alexander, thinks it is dangerous to take a drug that has not been officially approved for use in the United States. Alexander says no, it’s okay if it has been approved by other countries’ governments.
“The drug,” he continues, “is considered experimental here, but has been used in other countries safely for years.” When we say a drug is “experimental,” we mean that we are still researching it, we are still examining it. We’re not sure if it’s safe yet. It’s not ready for everyone to use. “Experimental drugs” usually are drugs that have not yet been approved for the average person to use. They can only be used in experiments that are carried out – conducted – by researchers and scientists.
Florence says, “But shouldn’t you just wait? How long could the process take anyway?” Florence thinks that Alexander should wait until the FDA approves of the drug for use here in the United States. Alexander has different ideas. He tells Florence that, in fact, in the United States, it can take many years – a very long time – for a drug to be approved.
He says, “You have no idea,” meaning you don’t really understand the situation here. “It can take years for a drug to be approved here, especially those that aren’t fast-tracked.” The expression “fast-tracked” (tracked) refers to something that is done more quickly than usual – something that would normally take a long time, especially in the approval of some plan or idea, that is instead approved very quickly. Governments sometimes, if there is a serious illness or disease that is affecting people, “fast-track” – approve something more quickly than they would normally otherwise do.
Florence says, “That’s hard to believe.” Alexander says, “It’s true. First, it has to be tested on animals or in a lab.” When we test drugs on animals, we give the drug to an animal and see if the animal dies. For something to be “tested in a lab” means that scientists and researchers look at the drug in a laboratory. The word “lab” (lab) is short for “laboratory,” which is a place where scientists conduct their experiments.
Alexander says, “Then it,” meaning the drug, “has to go through clinical trials.” “Clinical (clinical) trials (trials)” are research studies that doctors do on a small group of humans, of people who are sick, to make sure that the drug is safe. Clinical trials are required for most drugs that are approved by the FDA in the United States. You have to test the drug on a group of people to make sure that it’s safe for the average person. Many times, you can get paid to participate in these clinical trials. The government or drug companies will give you money to participate in the experiment.
Alexander says, “Only then is it” – again, the drug – “put through a rigorous review by the FDA, which alone can take years.” A “rigorous (rigorous) review (review)” is a very thorough, detailed investigation of something – when you look at something very closely to make sure that everything is okay. Alexander says that the FDA’s review alone can take years.
The word “alone” here means by itself – not including all of the other steps, all of the other things that have to happen in order for the drug to get approved. If you say a person is “alone,” you mean that the person is by him or herself. There are no other people with that person. Here, it refers to the fact that just this one thing, just this one part of the process, can take many years, not including the time it would take for all the other things to occur.
Florence says, “You’re right, I had no idea,” meaning “I wasn’t aware of this. I didn’t know this before you told me. Oh, Alexander, you’re so smart. I love you.” Oh, no – she doesn’t say that. Maybe Alexander is trying to impress Florence; maybe Alexander is interested romantically in Florence and he’s just telling her all of these things so that Florence will fall in love with his intelligence. You think? Nah. Anyway, back to our story.
Alexander says, “In the meantime” – meaning while I am waiting for the FDA to approve of this drug – “I’m suffering needlessly.” If something is done “needlessly” (needlessly), it is being done without a good reason, without a good cause. Alexander is saying that by waiting, he would be suffering. He would be in pain, say, more, without any reason to, because he could get this drug from another country.
Florence, however, reminds Alexander – or asks him, in any case – “You can’t legally import the drug for your own use, right?” “To import” (import) means to bring something into a country from another country. In the United States, normally it’s not legal for you to buy drugs in another country and bring them into the United States if those drugs are not legal already in the U.S.
Alexander says, “That’s right” – that’s correct; I can’t do that. “But,” he says, “I feel like I have to circumvent the law to get the medicine I need.” “To circumvent” (circumvent) means to go around something. Usually it’s used to mean to find a way to avoid rules and restrictions that you don’t want to follow – to do something that isn’t necessarily allowed by the rules, but allows you to do what you want to do. In the case of Alexander, he’s circumventing the law. He’s really breaking the law, going against the law, by bringing these drugs in, but it is something that he thinks is helping him.
Florence says, “So how does it feel to be an outlaw?” The word “outlaw” (outlaw) is an older term for a person who breaks the law, someone who has done something illegal, but has not yet been arrested or caught by the police. Florence is asking Alexander how it feels “to be an outlaw” – to be a criminal, in effect. Alexander says, “Um, healthy?” meaning he feels healthy. He feels better, and he feels better because, in fact, he was able to bring these drugs illegally into the United States in order to make him feel better, in order to help cure him of whatever disease he has.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Florence: A package came for you. I think it’s from overseas.
Alexander: Oh, those are my drugs.
Florence: You’re buying your medication from overseas?
Alexander: I have no choice. This drug isn’t FDA-approved yet.
Florence: Isn’t it dangerous to take a drug that isn’t approved?
Alexander: Not if it’s been approved in other countries. This drug is considered experimental here, but has been used in other countries safely for years.
Florence: But shouldn’t you just wait? How long could the process take anyway?
Alexander: You have no idea. It can take years for a drug to be approved here, especially those that aren’t fast-tracked.
Florence: That’s hard to believe.
Alexander: It’s true. First, it has to be tested on animals or in a lab, and then it has to go through clinical trials. Only then is it put through a rigorous review by the FDA, which alone can take years.
Florence: You’re right. I had no idea.
Alexander: In the meantime, I’m suffering needlessly.
Florence: You can’t legally import the drug for your own use, right?
Alexander: That’s right, but I feel like I have to circumvent the law to get the medicine I need.
Florence: So how does it feel to be an outlaw?
Alexander: Um, healthy?
[end of dialogue]
There’s no need for you to suffer needlessly in trying to improve your English. The best drug for your condition is the writings of Dr. Lucy Tse and her wonderful dialogues.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
drug – a chemical or herbal substance used to improve one’s health, reduce pain, or otherwise make one feel better, usually swallowed, injected, or smoked
* This drug has some dangerous side effects, including liver damage.
medication – a drug that is only for improving one’s health or reducing pain, especially prescribed by a doctor
* Please bring a complete list of all your medications when you come in for your next appointment with Dr. Pashtun.
FDA-approved – approved by the Food and Drug Administration, the government agency responsible for making sure that products sold to and used by Americans are safe
* Sheila is losing weight with the help of some FDA-approved diet pills.
experimental – being used as part of a research project or study to determine how something works and whether it was safe
* The astronauts volunteered to go into space in an experimental rocket.
fast-tracked – rushed; being done more quickly than usual
* They paid more to have their passport applications fast-tracked, because they need to arrive by next Friday.
to be tested on animals – to try to prove the benefits, risks, and/or safety of something by trying to use it on animals before it is used on humans
* The company promises that none of its make-up products are tested on animals.
lab – laboratory; a place where experiments are conducted and new things are created, especially for sciences and engineering
* All students in the chemistry class have to work in the lab twice a week.
clinical trial – a research study that lets doctors observe the effect of a medicine or treatment on a small group of patients before they become available for sale and/or use
* The treatment has shown promising results in clinical trials, but the researchers want to include more subjects in another clinical trial later this year.
rigorous – very thorough, detailed, challenging, and technical
* Military recruits have to complete a rigorous training program.
review – the process of observing something in detail, especially in order to determine whether it is good enough or meets some standard
* How long did it take you to conduct a review of the applications?
alone – a word used to emphasize that nothing and nobody else was involved; without including anyone or anything else
* Living in New York City is so expensive! The rent alone uses up more than 60% of my paycheck!
needlessly – without any reason for do something; with no clear purpose
* Kristof spent all weekend worrying needlessly about the presentation, only to find out on Monday that he wouldn’t have to speak at the conference after all.
to import – to bring something in from another country in order to sell it; to buy something from another country
* The United States imports many cars from Japan, Korea, and Germany
to circumvent – to go around something; to find a way to avoid the rules and restrictions against something
* Is there any way to circumvent tax laws for money earned overseas?
outlaw – a person who breaks the law and avoids being captured
* Police and investigators have been searching for that outlaw for years, but they still haven’t found him.
healthy – for one’s body to feel well and without illness or disease
* Getting a good night’s sleep, drinking a lot of water, eating fruits and vegetables, and getting enough exercise are all good ways to stay healthy.
Comprehension Questions
1. Why does Alexander receive his medications in the mail?
a) Because the pharmacy ran out of what he needs.
b) Because it’s cheaper to buy them that way.
c) Because the medications cannot be sold in the U.S.
2. What does Alexander mean when he says, “I have to circumvent the law”?
a) He has the break the law.
b) He has to change the law.
c) He has to find a way to do something that the law doesn’t normally allow.
Answers at bottom.
What Else Does It Mean?
drug
The word “drug,” in this podcast, means a chemical or herbal substance used to improve one’s help, reduce pain, or otherwise make one feel better, usually swallowed, injected, or smoked: “Does your health insurance cover the costs of these drugs?” The word “drug” also refers to narcotics, or illegal drugs like marijuana and heroin: “It’s illegal to sell drugs, especially near schools.” The phrase “to be drugged” means for someone to be given a drug secretly, usually so that the person becomes unconscious (unaware of one’s surroundings): “Hank was drugged at the bar, and when he woke up, he was in an unfamiliar place and his wallet and cell phone had been stolen.” Finally, the phrase “to be like a drug” means that an activity makes one feel very good and want to continue doing it: “For some people, running is like a drug.”
alone
In this podcast, the word “alone” means all by itself; a word used to emphasize that nothing and nobody else was involved: “If you buy that big truck, gas alone will cost hundreds of dollars each month.” The word “alone” also means by oneself, without anyone else: “At what age can a child stay home alone for a few hours?” Or, “Could you please leave me alone for a few minutes?” The phrase “to feel alone” means to feel very unhappy and wanting to be with other people: “Jessie felt alone those first few weeks in a new city.” Finally, the phrase “to leave (something) alone” means to not touch something: “Leave those packages alone! They aren’t for you.”
Culture Note
Off-Label Use of Medication
In the United States, there are two types of medications: “over-the-counter” (OTC) drugs, which can be purchased easily in stores, and “prescription medications,” which are available only with a doctor’s “prescription” (a written note from a doctor allowing a patient to buy a medicine that has restricted availability, usually because it could be dangerous or addictive). Medications are labeled with “indications” (reasons for taking the medicine) and recommended “dosages” (the amount of medicine that should be taken, and how often). All of the text on the “label” (the information found on the container in which the medicine is sold) is developed and agreed to by the “pharmaceutical company” (the company that develops, manufactures, and sells the drug) and the Food and Drug Administration (FDA), and cannot be changed.
But sometimes people “disregard” (choose not to follow or pay attention to) the information on the label. Instead, they “alter” (change) the use of the drug in what is called “off-label use of medication,” because they are using it in a way that is not described on the label. Off-label use could involve using the medicine to treat a medical condition that isn’t included in the official indications. It could also mean using the medicine for an unapproved age group, with an unapproved dosage, or with an unapproved form of “administration” (how something is given to a patient).
For example, some “stimulants” (substances that make parts of the body move more quickly or make one feel more awake) are approved for treating attention deficit disorder (ADD; a condition that makes it difficult for children to concentrate) in children. Doctors often prescribe those same stimulants to treat attention difficulties in adults, even though those the drugs have not been approved for that use with adults.
Comprehension Answers
1 - c
2 - c