= 1098
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,098 – Riding in a Limousine.
This is English as a Second Language Podcast episode 1,098. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode.
This episode is a dialogue between Theo and Mandy about riding in a very big, luxurious car called a limousine. Let’s get started.
[start of dialogue]
Mandy: Whoo! Whoo!
Theo: Hey, get down from there. You shouldn’t be sticking your head out of the sunroof.
Mandy: I just wanted to get some air. This stretch limo is amazing.
Theo: Well, I thought I’d rent one and take you to the prom in style.
Mandy: This is the height of luxury. You’ve really outdone yourself.
Theo: Thanks, but maybe we should be careful not to spill drinks on the seats.
Mandy: Everybody drinks and parties in the back of a limo. Why else would they have a wet bar?
Theo: Well, we shouldn’t be drinking out of it. We could get into trouble.
Mandy: The chauffeur doesn’t know what we’re doing back here. The partition is up and it’s soundproof.
Theo: But he could hear us on the intercom system. Let’s just relax and enjoy the ride.
Mandy: You can do that, but I’m going to blast the music and have some fun.
Theo: This isn’t a party bus.
Mandy: No, but it could be a party limo! You’re brilliant. Let’s go pick up a few of my friends. We’ll turn this into a great party.
Theo: What about the prom?
Mandy: We’ll get there, but first we’re going to have a pre-party in our own party limo. What a great idea!
Theo: Me and my big mouth.
[end of dialogue]
This episode is all about a “limousine” (limousine). A limousine is a big car, often a car that has six, eight, or even more doors on it, that is used for special events or for very special people. It’s a big car. It’s what we might call a “luxury car.” You can often put six, eight, perhaps ten or more people in a limousine, depending on how big it is.
Mandy begins our dialogue by shouting, “Whoo! Whoo!” or something like that. Theo says, “Hey, get down from there.” We tell someone to “get down” from somewhere when they have climbed up or gotten on top of something that they shouldn’t be on – or in this case, that they are standing up when they should not be standing up.
Theo says to Mandy, “You shouldn’t be sticking your head out of the sunroof.” “To stick (stick) your head out of” something is to put your head through some sort of opening, usually a window, but here Mandy is sticking her head out of a “sunroof” (sunroof). The “roof” of a car is the top of the car. We use that same word “roof” to describe the top of a house or a building. A “roof” is on the outside of a house or a building or, in this case, a car. The inside top of a room inside of a house or building is called the “ceiling” (ceiling).
We’re talking, in this dialogue, about a “sunroof.” A sunroof is basically a door that is at the top of the car – cut into the roof – that you can open and stick your head out of. Now, there is also another similar concept that is actually more popular in cars today, called a “moonroof.” A moonroof is a window at the top of the car, cut into the top of the car. You can’t stick your head out of it, but you can see out of it.
Moonroofs usually have covers on them so you can open or close the cover depending on whether you want light or not inside of the car – coming from the top, of course. Mandy says, “I just want to get some air.” People use that expression “to get some air.” It means to go outside and breathe in fresh air. You can do that in most places except here in Los Angeles, where the air is so polluted you’re probably better off staying inside.
Manny continues, “This stretch limo is amazing.” “Limo” (limo) is short for “limousine.” A “stretch (stretch) limo” is a very long limousine. Now, limousines are very long cars anyway, but a stretch limo is a really long limousine. You’ve probably seen one, or at least seen one in the movies.
Some people get a limousine for their wedding day and they like to ride in the limousine before the wedding – or I guess after the wedding, really. I don’t know. I didn’t have a limousine for my wedding. I had a bicycle. Yeah, my wife and I, after we got married, we got on a bicycle – you know, one of those bicycles for two – and then we pedaled away. We rode to the party, to the reception. Really.
Mandy is in a stretch limo and she thinks it’s amazing. Theo says, “Well, I thought I’d rent one and take you to the prom in style.” Now we learn exactly why Mandy and Theo are in a limo. They’re going to something called the “prom” (prom). The prom is a formal dance party that is popular in many American high schools, and it has been for many years. It’s usually during the spring of the school year and is primarily for the students who are in their senior or last year – the “graduating students,” we might call them.
Prom is one of the few occasions where high school students get dressed up very nicely, and it’s considered a big party night for couples. To go to the prom is considered sort of part of one’s high school experience in the United States. Not everyone goes to the prom. I didn’t go to the prom. Why? Well, I didn’t have a girlfriend. Sad, I know.
In our dialogue, Theo wants to take Mandy “to the prom in style.” “In style” means in a fashionable, popular way, often one that costs a lot of money. If you say, “I’m going to do something in style,” you mean you are going to do it in a way that other people will admire, perhaps, and that also might cost you a little money. Some children of richer parents will get a stretch limo or a limo for their prom night.
Mandy says, “This is the height of luxury.” The “height (height) of” something is an extreme example of something or the strongest example of something. It could also refer to the biggest amount of something. “Luxury” (luxury) is something that is very comfortable – often, again, something that costs a lot of money. So, “the height of luxury” would be the most luxurious situation you could imagine.
Mandy says to Theo, “You’ve really outdone yourself.” “To outdo” (outdo) – one word – “yourself” is to do something better than anyone thought you could do, to do something better than you have done it before. We might also define this verb as “to surpass expectations.”
Theo says, “Thanks, but maybe we should be careful not to spill drinks on the seats.” “To spill” (spill) means to accidentally cause a liquid to leave its container. So, for example, if you have a glass of water and you move your hand or arm too quickly, the water might spill out of the glass – it might come out of the glass. Theo is warning Mandy not to spill drinks on the seats of the car.
Mandy says, “Everybody drinks and parties in the back of a limo. Why else would they have a wet bar?” A “wet bar” is usually a small counter, a small piece of furniture that has a small sink in it, used to mix alcoholic drinks. Now remember, these kids are in high school, and of course they shouldn’t be drinking, legally, if they are in high school. Theo says, “Well we shouldn’t be drinking out of it,” meaning we shouldn’t be taking drinks out of this wet bar.
Mandy says, “The chauffeur doesn’t know what we’re doing back here. The partition is up and it’s soundproof.” The “chauffeur” (chauffeur) is the person whose job it is to drive the car – in this case, to drive the limousine. The “partition” (partition) is the thing that divides the place where the driver is and those in the other part of the limousine, in the back part of the limousine. A partition is anything that divides a room or a space into two different sections.
“The partition is up,” Mandy says, meaning that there is something like a wall between where the chauffeur is, the driver is, and where they are sitting, so the driver can’t see them. Mandy also says that this particular partition is “soundproof” (soundproof). If something is soundproof, you can’t hear what’s on the other side of it. Theo says, “But he could hear us on the intercom system.” An “intercom (intercom) system” is a system that allows you to talk to people in another room of a house or a building, usually one that is at a distance from where you are.
The house where I grew up had an intercom system. It was three stories, or three levels, and my parents wanted to be able to yell at us – I mean, talk to us – when we were on the top floor, in our bedroom, so they put in an intercom system, which also allowed them to listen to us through the intercom – and that’s what Theo is talking about here. He’s saying the chauffeur could listen to them talking through the intercom system in the limousine.
He says, “Let’s just relax and enjoy the ride.” Mandy says, “You can do that, but I’m going to blast the music and have some fun.” “To blast (blast) music” means to play it very loudly, as teenagers sometimes do. Theo reminds Mandy that “This isn’t a party bus.” A “party bus” would be a large bus, a large vehicle that has been modified so that people can have a party in it as it is moving them one place to another.
This has become popular I guess recently, at least here in Los Angeles. People have these big buses that they use for parties. Seems kind of strange to me, but then again, many things here in Los Angeles seem strange to me. Mandy says, “No” – this isn’t a party bus – “but it could be a party limo!” Then she says, “You’re brilliant,” meaning you’re very intelligent. “Let’s go pick up a few of my friends,” meaning let’s go to my friends’ houses and get them to come in to the car or ride in the car with us.
“We’ll turn this into a great party,” Mandy says. Theo says, “What about the prom?” meaning “Aren’t we going to go to the prom?” Mandy says, “We’ll get there, but first we’re going to have a pre-party in our own party limo.” A “pre (pre) – party” would, I guess, be the party that happens before the main party. “What a great idea!” Mandy says.
Theo ends the dialogue by saying, “Me and my big mouth.” This is a phrase we use when you regret what you have said, when you wish that you had not said something that you had said. The reason you regret it or feel badly about saying it is because another person took you seriously and actually did what you said or what you suggested even though that wasn’t really what you had in mind or wasn’t what you intended. It could also be used when you say something that gets you in trouble, something that you shouldn’t have said.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Mandy: Whoo! Whoo!
Theo: Hey, get down from there. You shouldn’t be sticking your head out of the sunroof.
Mandy: I just wanted to get some air. This stretch limo is amazing.
Theo: Well, I thought I’d rent one and take you to the prom in style.
Mandy: This is the height of luxury. You’ve really outdone yourself.
Theo: Thanks, but maybe we should be careful not to spill drinks on the seats.
Mandy: Everybody drinks and parties in the back of a limo. Why else would they have a wet bar?
Theo: Well, we shouldn’t be drinking out of it. We could get into trouble.
Mandy: The chauffeur doesn’t know what we’re doing back here. The partition is up and it’s soundproof.
Theo: But he could hear us on the intercom system. Let’s just relax and enjoy the ride.
Mandy: You can do that, but I’m going to blast the music and have some fun.
Theo: This isn’t a party bus.
Mandy: No, but it could be a party limo! You’re brilliant. Let’s go pick up a few of my friends. We’ll turn this into a great party.
Theo: What about the prom?
Mandy: We’ll get there, but first we’re going to have a pre-party in our own party limo. What a great idea!
Theo: Me and my big mouth.
[end of dialogue]
Here at ESL Podcast, we think our scriptwriter, Dr. Lucy Tse, is brilliant. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
sunroof – a window in the roof of a car that can be opened to let in light and/or air
* Oh no! We left the sunroof open last night, so when it rained, everything got wet.
stretch limo – a very long limousine; a luxury car with a very large seating area in the back of the car
* Most of the celebrities arrived at the award ceremony in stretch limos.
prom – a formal dance party primarily for senior (graduating) students during the spring of their final year in high school
* Prom is one of the last opportunities for students to spend time together, because just a few weeks later, they’ll graduate.
in style – fashionably; in an admirable and popular way
* They decided to announce their engagement in style, with a big picture in the newspaper.
the height of – a very strong example of something; the period when something is at its strongest or most extreme level; the biggest amount of something
* Long dresses and fancy hats were the height of fashion for women 100 years ago.
luxury – great comfort, extravagance, and expense
* Why are you spending so much money on a luxury automobile? You really just need something simple that will get you to and from work.
to outdo (oneself) – to surpass expectations; to do something better than one has done it before, and better than other people had hoped for
* Craig is an excellent chef, but he really outdid himself with that gourmet meal. It was the best food I’ve ever tasted!
to spill – to accidentally cause a liquid to leave its container, so that it unintentionally falls onto another object, especially one that was not supposed to get wet
* The little boy spilled his milk all over the dining table and floor.
wet bar – a counter with shelves and a small sink, used for serving mixed alcoholic drinks
* A wet bar should be stocked with liquors, fruit juices, soda water, and ice.
chauffeur – a person whose job is to drive a car to transport other people to their destinations
* I’ll send my chauffeur to pick you up in an hour to take you to the party.
partition – something that divides a room or another space into two or more sections, especially when referring to a temporary screen or a removable wall
* They used a partition to separate the bedroom area from the living space in their tiny studio apartment.
soundproof – not allowing sounds to pass through, so that sounds made in one area cannot be heard in another room
* Is there any way to make the childcare center soundproof? The neighbors are complaining about all the noise.
intercom system – a collection of electronic devices that allow sounds in one room to be heard in another room, often by touching a button before speaking
* The house has an intercom system, so when you get to the front gate, push the button to announce yourself and then we’ll open the gate to let you in.
to blast – to play music or other noise very loudly
* The people who live near the stadium are worried about concerts blasting music into their neighborhood late at night.
party bus – a large bus or recreational vehicle that has been modified and decorated for people to have a party while they travel from one place to another
* To create this party bus, they removed all the seats, installed carpet, painted the walls, added lighting and a disco ball, and put in a small bar.
brilliant – extremely intelligent; with very good ideas
* Dr. Stroebel is a brilliant biochemist and does ground-breaking research.
pre-party – a party that happens before the main party of the evening
* Don’t drink too much at the pre-party, or you won’t feel too good at the actual party.
me and my big mouth – a phrase used when one regrets what one has said, especially because another person took it seriously and acted upon what one said in a way that one did not anticipate or want
* I invited Karen to “come visit us anytime,” but now she’s planning to stay for three weeks! Me and my big mouth.
Comprehension Questions
1. What is a stretch limo?
a) A type of dance
b) A type of vehicle
c) A type of alcoholic drink
2. What does Mandy mean when she says, “I’m going to blast the music”?
a) She’s going to turn up the volume.
b) She’s going to start singing.
c) She’s going to change the radio station.
Answers at bottom.
What Else Does It Mean?
to spill
The verb “to spill,” in this podcast, means to accidentally cause a liquid to leave its container, so that it unintentionally falls onto another object, especially one that was not supposed to get wet: “The lab should have a cleanup kit for hazardous materials, just in case one of the students spills the chemicals used in the experiments.” Or, “If you spill red wine on a white carpet, it will stain.” The phrase “to spill the beans” means to accidentally share a secret: “Who spilled the beans and told Ahmed about the surprise birthday party we were planning?” Finally, the phrase “to spill blood” means to kill someone, especially when describing a battle: “The soldiers were young and had never spilt blood before.”
to blast
In this podcast, the verb “to blast” means to play music or other noise very loudly: “How can they concentrate with that music blasting through the office building?” The verb “to blast” also means to damage or destroy something through an explosion: “The demolition crew blasted the old apartment building until it was a pile of old wood and bricks.” The verb “to blast” can also mean for air or water to move out of something very forcefully and with a lot of pressure: “The firefighters blasted the fire with water from their hoses.” The phrase “to have a blast” means to have a lot of fun, or to have a very good time: “We had a blast at the beach last weekend.” Finally, when talking about a rocket or space shuttle, the countdown ends with the words “blast off”: “10, 9, 8, 7, 6, 5, 4, 3, 2, 1, blast off!”
Culture Note
Common Prom Traditions
At a typical prom, students “get dressed up” (wear very nice clothes). Girls often wear a “full-length” (reaching down to the ground) dress and boys wear a rented “tuxedo” (a formal suit). The boy normally goes to the girl’s house, where he “presents her with” (gives her) a “corsage” (a floral arrangement worn around the wrist or pinned to the dress at the “neckline” (the top part of the dress), and he wears a “matching” (with the same style and color) “boutonniere” (a smaller floral arrangement worn on the “lapel” (the folded part of the collar that reaches down onto the chest).
The girl’s parents usually take a lot of pictures of the couple at the house, and then they leave. Sometimes the boy drives his own car or his parents’ car, but others will rent a limousine. When they arrive at the prom, which may be held at the school gymnasium, a hotel lobby, a country club, or a similar “venue” (place), the boy and girl “hook arms” (wrap their arms around each other) or hold hands as they walk in. Dancers can rest at small tables and enjoy “refreshments” (light drinks and snacks). Often a professional photographer takes “posed” (holding one’s body in a particular position) of the couple. There may be a live band, or simply a “DJ” (disc jockey; someone whose job is to choose which songs to play).
During the prom, the “prom king” and “prom queen” are announced. These are two students, usually selected by their peers, who are popular and attractive. They are given a “crown” (a tiara; a shiny object placed on the head, like royalty) and then they dance with each other.
Comprehension Answers
1 - b
2 - a