= 0764
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 764: Being Unsure and Unready.
This is English as a Second Language Podcast episode 764. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. You can also like us on Facebook at facebook.com/eslpod, and you can follow us on Twitter @elspod, and you can…well, you get the idea!
This episode talks about not being sure, not being certain, and not being ready. Let’s get started.
[start of dialogue]
Aida: When our bigwigs from the Cleveland office arrive next week, I think we’ll have a lot to show them.
Dale: I wouldn’t be so sure about that. Giselle told me yesterday that it’s a toss up whether she’ll finish the program she’s working on by next week, but don’t quote me on that.
Aida: I thought she was already done with it.
Dale: I think that she’s still tinkering with it because she isn’t 100 percent sure she’s worked out all of the bugs.
Aida: All right. I hope she gets a move on and fast. I’ll still have Joe’s prototype to show them, right?
Dale: Well, the last time I spoke with Joe, he said that the prototype is still a work in progress. Whether it’ll actually work is iffy, at best.
Aida: Are you trying to tell me that we’re not ready for this visit at all?
Dale: I hate to be the bearer of bad news, but I wouldn’t count on having much to show them, sorry.
Aida: Then, what am I supposed to do when they want to see the progress on our work?
Dale: I suggest some fast-talking and fancy tap dancing!
[end of dialogue]
Aida says to Dale, “When our bigwigs from the Cleveland office arrive next week, I think we’ll have a lot to show them.” A “bigwig” (bigwig – one word) is an important person. A supervisor, a boss, maybe the owner of the company, those are bigwigs. Aida says that when our bigwigs from the Cleveland office – from the office in another city, in this case Cleveland, Ohio, a state in the eastern half of the United States in the northern part – when these bigwigs arrive from the Cleveland office next week, “I think we’ll have a lot to show them,” she says.
Dale says, “I wouldn’t be so sure about that,” meaning I’m not sure, you shouldn’t think that. “Giselle told me yesterday that it’s a toss up whether she’ll finish the program she’s working on by next week, but don’t quote me on that.” A “toss up” (toss up – two words) is something that may or may not happen. The verb “to toss” means to throw. And often, if we want to decide by chance or by luck some decision we may take a coin, a small piece of money, and toss it up in the air and depending on which side it lands on that will be the answer to our question – that will be the solution to our problem. That’s a toss up, but in general the term is used to express something that is not sure. We’re not sure, it could happen, it might not happen. Giselle is not sure that she’s going to finish the program, whatever that is she’s working on, “but don’t quote me on that,” Dale says. The expression “don’t quote (quote) me on that” is used to share information that is secret but you don’t want other people to know that you gave them that information – don’t tell people I told you that, that’s one use of it. It can also be used when you’re just not sure that something is going to happen; you’re making a prediction. “I think the Dodgers will win the World Series of baseball next year, but don’t quote me on that,” I could be wrong.
Aida says, “I thought she (Giselle) was already done with it.” Dale says, “I think she’s still tinkering with it because she isn’t 100 percent sure she’s worked out all of the bugs.” “To tinker (tinker) with (something)” means to make small changes in it to improve it or to make it better. Usually it’s used when those efforts – those changes aren’t really very important or perhaps aren’t even successful. “One hundred percent sure” means absolutely, completely certain, no doubt. “To work out (something)” means to fix a problem, to resolve a problem, or to resolve an issue. “Bugs” (bugs) are errors in computer programs. “Bug” has a couple of different meanings in English; take a look at our Learning Guide for some of those. Here, though, it means some sort of mistake in a computer software program. Dale says that Giselle is still tinkering with the program because she isn’t 100 percent sure she’s worked out, or fixed, all of the bugs or problems.
Aida says, “All right (okay). I hope she gets a move on and fast.” “To get a move on (something)” means to work on something quickly, to try to do it as fast as possible because you need to get it done soon. She hopes that Giselle will get a move on means she’ll start working on it fast. “I’ll still have Joe’s prototype to show them, right?” A “prototype” (prototype) is a model, it’s something you make or a company makes to decide whether they want to make more of it. You make one, and you look at it and you say, “Well, maybe we’ll change this or change that,” or maybe, “This is exactly what we want. Let’s make some more.” Prototype is like the first example of that particular thing. Aida is saying to Dale that they have a prototype – Joe’s prototype, Joe would be the person who made it – to show the bigwigs next week, even if Giselle isn’t finished with her program.
Dale said, “Well, the last time I spoke with (or I talked with) Joe, he said that the prototype is still a work in progress.” When we call something “a work in progress” (progress) we mean that it isn’t finished yet; it’s still being developed; it’s still being changed or improved. Dale says, “Whether it’ll actually work is iffy, at best.” Dale isn’t sure if Joe’s prototype, I guess of this program, will actually work. He says it’s iffy (iffy). “Iffy” is a somewhat informal word meaning uncertain, not exactly sure, questionable; it might, it might not. The expression “at best” means the most optimistic way of thinking or looking at the situation, the most positive way. So, if we think in the most positive way possible, it might work or it might not. Of course, that means it probably won’t work!
Aida says, “Are you trying to tell me that we’re not ready for this visit at all (not in any way)?” Dale says, “I hate to be the bearer of bad news.” “To bear (bear) (something),” as a verb, means to carry. The “bearer” is the person who is carrying something. At a wedding, you might have a “ring-bearer,” usually a small boy – a young boy who carries the rings of the two people getting married up to the couple that is getting married; that’s a ring-bearer. But here, the word “bearer” is part of a common expression meaning someone who brings you bad news, someone who gives you some unfortunate or sad information. Dale says, “I wouldn’t count on having much to show them, sorry.” “To count on” means to rely on, to depend on. Dale says that he wouldn’t count on – he wouldn’t rely on having very much to show the bigwigs next week.
Well, of course, Aida isn’t very happy; she says, “Then, what am I supposed to do when they see the progress on our work?” meaning, of course, they haven’t made very much progress. Dale says, “I suggest some fast-talking and tap dancing!” “Fast-talking” is when you talk in such a way as to mislead the person listening to you, or distract them. When you want to hide something, you start saying this and you start saying that and you try to sort of confuse the person so that they’re not really sure what’s happening. “Tap dancing” is a type of dancing, where you have little pieces of metal on your shoes that make noise as you hit the ground. But here, it’s used as an expression to mean something similar to “fast-talking.” You’re doing something that will distract, that will put the attention of the person listening or watching you somewhere else so that they won’t think about the real problem that you’re trying to hide. There aren’t a lot of people who do tap dancing anymore; it was popular in the 20th century. I actually took tap dancing lessons when I was in second grade. I must have been, oh, eight or nine years old. True story! Maybe someday I’ll make a video of myself tap dancing.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Aida: When our bigwigs from the Cleveland office arrive next week, I think we’ll have a lot to show them.
Dale: I wouldn’t be so sure about that. Giselle told me yesterday that it’s a toss up whether she’ll finish the program she’s working on by next week, but don’t quote me on that.
Aida: I thought she was already done with it.
Dale: I think that she’s still tinkering with it because she isn’t 100 percent sure she’s worked out all of the bugs.
Aida: All right. I hope she gets a move on and fast. I’ll still have Joe’s prototype to show them, right?
Dale: Well, the last time I spoke with Joe, he said that the prototype is still a work in progress. Whether it’ll actually work is iffy, at best.
Aida: Are you trying to tell me that we’re not ready for this visit at all?
Dale: I hate to be the bearer of bad news, but I wouldn’t count on having much to show them, sorry.
Aida: Then, what am I supposed to do when they want to see the progress on our work?
Dale: I suggest some fast-talking and fancy tap dancing!
[end of dialogue]
I’m 100 percent sure that the best scriptwriter on the Internet is our own Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
bigwig – an important person, usually in a specific field; a person with a lot of power or prestige in a particular field
* This reception is for all of the bigwigs and many of the most influential people in the advertising field will be attending.
toss up – something that may or may not happen; something that is equally likely to succeed or fail
* - Which team do you think will win?
* - I don’t know. It’s a toss up. They’re both good teams.
don’t quote me on that – a phrase used when one is sharing a secret but does not want other people to share the source of the information, because one will deny it
* The mayor is considering firing the police chief, but don’t quote me on that.
to tinker with – to make small changes to try to make something better or improve it in some way, usually when those efforts are not successful
* Grandpa spends hours in the garage tinkering with that old car, but it’s never going to run again.
100% sure – positive; absolutely certain; without any doubt
* Are you 100% sure this face cream will remove wrinkles?
to work out – to resolve, fix, or address a problem, issue, or challenge
* They’re meeting with a therapist twice a week to try to work out their problems.
bug – an error in a computer program or software; something that isn’t working properly, especially when talking about electronics and technology
* Adele volunteered to test the software and look for any bugs.
to get a move on – to work on something with urgency and try to do it quickly, especially when one has been making very slow progress
* Jake has been sitting at the computer for hours, but so far he has written only two paragraphs of his report. He’d better get a move on, because it’s due by noon!
prototype – a model showing how something will appear or operate, especially when testing an idea and deciding whether one should proceed to manufacture, implement, or sell it
* This is just a prototype, but it shows what the robotic vacuum cleaner would look like.
a work in progress – something that has not yet finished and is still being developed, changed, and implemented
* Kelly’s knitting is a work in progress. She keeps adding more rows, making the scarf longer and longer.
iffy – uncertain; questionable; with at least two possible outcomes
* The weather is iffy, so we should take an umbrella in case it rains.
at best – in the most positive, optimistic way or situation; at most
* He’s so skinny! He must weigh 100 pounds at best.
the bearer of bad news – someone who is sharing unpleasant or unwelcome information that must be shared, even though it will have negative consequences
* I hate to be the bearer of bad news, but I washed your clothes, and now your white shirt is pink.
to count on – to rely on; to depend on; to trust in; to believe that something will happen and plan accordingly
* Sheila was counting on receiving that check from her biggest customer in order to pay her employees.
fast-talking – the use of words in a way that distracts or misleads the listener, especially when one wants to hide something or when one wants to trick someone
* Drake dreads buying a car, because he doesn’t like the fast-talking salespeople.
tap dancing – the act of moving or speaking quickly, especially to distract or mislead someone, or to avoid discussing something or answering questions
* The company’s managers are tap-dancing to try to distract the journalists from the scandal.
Comprehension Questions
1. Who is coming from Cleveland?
a) Some new employees.
b) The owners of the company.
c) People who have the same kind of jobs as Aida and Dale.
2. What does Giselle need to do in order to work out all the bugs?
a) She needs to finish writing the report.
b) She needs to fix the problems.
c) She needs to get over her illness.
Answers at bottom.
What Else Does It Mean?
bug
The word “bug,” in this podcast, means an error in a computer program or software, or something that isn’t working properly in a piece of electronics and information technology: “The company was criticized for selling its software program with known bugs.” Most commonly, a “bug” is a small insect: “Look at this cool green bug with red eyes!” A “bug” can also be an illness or a virus or bacteria that causes an illness: “The best way to avoid catching a bug is to wash your hands before eating.” Finally, a “bug” can refer to one’s strong desire or interest to do something: “Each December, Yolanda gets the baking bug and spends each evening baking holiday pies and Christmas cookies.”
at best
In this podcast, the phrase “at best” means at most, or in the most positive, optimistic way or situation: “Sales have been poor this year, so our year-end bonus will probably be just $300 at best.” The phrase “the best part of (something)” means most of something: “She spent the best part of the day shopping for a new dress.” The phrase “best bet” refers to the best available option or choice: “All the flights have been grounded due to the storm, so your best bet is probably to take a train.” Finally, the phrase “the next best thing” describes one’s second choice, when one’s first choice is impossible or unavailable: “The store was out of your favorite wine, so they bought a chardonnay as the next best thing.”
Culture Note
Tap Dancing
In today’s episode, “tap dancing” referred to the act of moving or speaking quickly, especially to distract or mislead someone. But “tap dancing” is also a style of dance where the dancers wear metal “taps” on the bottom of their shoes so that they can make “sharp” (loud and sudden) noises when their feet “strike” (hit) the floor, almost like a “percussion” (related to drums) instrument.
There are two major types of tap dancing: “Jazz tap” (also known as “rhythm tap”) and “Broadway tap.” Jazz tap focuses more on the “rhythm” (repetitive beats that mark the time and how fast or slow a song is). Jazz tap dancers “primarily” (mostly) use their legs and feet, and they don’t do very much with their arms. “In contrast” (in a different way), Broadway tap dancers focus more on the dance movements and they use their arms and “torso” (upper body) to create interest and style while using their legs and feet to make noise. Many of the Broadway tap movements were “inspired” (influenced during creation) by ballet, and the female Broadway tap dancers often wear high-heeled shoes.
Tap dancers often dance “to music” (while music is playing), but sometimes they dance without music, especially in groups. Tap dancing groups have “elaborate” (detailed; fancy; complex) “choreography” (a plan for how dancers will move around or with each other). “There” (in that situation), the “challenge” (something that is difficult to do) is for all the dancers to keep the taps “in unison” (being heard at the same time).
Comprehension Answers
1 - c
2 - b