= 0767
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 767: Taking Care of Your Teeth.
This is English as a Second Language Podcast episode 767. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website – you know what it is – eslpod.com. Go there today and take look at our ESL Podcast Store, which has some additional courses in English. You can also check us out on Facebook at facebook.com/eslpod. Are you on Twitter? You can follow us @eslpod.
This episode has a dialogue between George and Martha about taking care of your teeth. Let’s get started.
[start of dialogue]
Martha: Oh, I have a toothache!
George: It sounds like you’re in for a visit to the dentist.
Martha: That would be the last resort. I hate going to the dentist. I don’t like needles and the sound of the drill scares me to death. I’m hoping the toothache will just go away.
George: You really should get that checked out. Do you want me to make an appointment for you with my dentist?
Martha: No, thanks. I haven’t seen a dentist in years and I don’t plan to now unless I have no choice.
George: Years?! You haven’t been to a dentist in years? Haven’t you ever heard of preventive care? You’re supposed to get a dental cleaning twice a year.
Martha: I don’t follow doctor and dentist guidelines like that. I brush my teeth every day. That’s good enough.
George: No, it’s not. You should be flossing every day and rinsing your mouth with mouthwash to keep your teeth and gums healthy. If you haven’t been to the dentist in years, I’m not surprised you didn’t know that.
Martha: Stop preaching! I’ll go to the dentist when I need to.
George: Like now.
Martha: Maybe. It doesn’t hurt that much anymore…
George: I never knew you were such a chicken.
Martha: [makes a chicken noise] Bwauk, bwauk…!
[end of dialogue]
Martha begins our dialogue by saying, “Oh, I have a toothache!” A “toothache” (toothache – one word) is when you have a pain in your tooth. Your “teeth,” which is the plural of “tooth,” are, of course, these white things inside your mouth that you use to eat. Martha has a toothache. You can have a toothache, you can have a headache, you can have a stomachache, depending on what part of your body hurts.
George says, “It sounds like (it seems to me) you’re in for a visit to the dentist.” “To be in for (something)” means you’re going to have to do something very soon. Often we use that expression when we’re talking about something that isn’t very nice, something isn’t very pleasant. We might even say, “You’re in for a big surprise.” That usually means you don’t understand something bad that is going to happen to you. A “dentist” (dentist) is a person who works on – a doctor who works on your teeth, a medical doctor who takes care of or specializes in taking care of teeth.
Martha says going to the doctor would be the last resort. The expression “the last resort” (resort) means it’s the last option you will choose, only after you do everything else, it’s the one that you don’t want to do and will only do because nothing else works. Perhaps it’s very expensive, perhaps it’s just very unpleasant or even embarrassing. Martha says, “I hate going to the dentist. I don’t like needles.” “Needles” are sharp objects they stick into your body to put drugs into them, usually. Martha doesn’t like the sound of the drill; she says, “the sound of the drill scares me to death,” makes me very frightened. A “drill” (drill) here refers to a machine that makes holes in something. You can use a drill to make a hole in your wall if you are putting something on your wall. Well, dentists use drills to make holes in your teeth in order to repair them. “Drill” actually has a couple of different meanings; those can be found in – where else? – our Learning Guide. Martha says, “I’m hoping the toothache will just go away,” meaning it will disappear, I will no longer have it.
George says, “You really should get that checked out.” When someone says you need to have something “checked out” they mean examined or reviewed, especially by someone who’s an expert in that area: “My foot is hurting me.” “You should really a podiatrist (a foot doctor) check that out.” “To check out” has some other meanings in English; you can say, “I’m going to check out that movie.” That means I’m going to watch it or I’m going to read about it or investigate it. Or, “Check out this guy walking down the street.” There it means simply look at this guy. There’s actually, uh, even more meanings of this two-word phrasal verb, “to check out.” You can use it to refer to taking a book out of the library: “I’m going to check out a book.” But here, it refers having someone who’s an expert examine or look at something. George says, “Do you want me to make an appointment for you with my dentist?” An “appointment” is a particular day and time that you are going to see someone. It’s like a date, but when we talk about business things or going to a doctor or dentist, having an appointment is the time and day you are going to see that person.
Martha says, “No, thanks. I haven’t seen a dentist in years and I don’t plan to now unless I have no choice.” She hasn’t gone to the dentist in many years, and she isn’t going to go unless she has to, unless she has no other option or choice. George is surprised; he says, “Years?!” He’s surprised that Martha hasn’t been to a dentist in years. “You haven’t been to a dentist in years? Haven’t you ever heard of preventive care?” “To prevent” (prevent) means to make sure something does not happen. “Preventive,” then, is an adjective. “Care,” here, is like a medical treatment or some action that you do so that you are healthy. “Preventative care” are things that you do so that you don’t get sick. So, you should wash your hands with soap and water after using the bathroom, and before eating with your hands to prevent you from getting sick later. That’s preventative care.
Martha apparently, we guess, doesn’t believe in preventative care. George says, “You’re supposed to get a dental cleaning twice a year.” The word “dental” refers to your teeth. “Dental cleaning,” then, is a process where you go and have your teeth cleaned usually by someone who works with the dentist, not actually the dentist. Usually the person who cleans your teeth is called a “dental hygienist.” This is sort of like the dentist’s assistant that cleans your teeth and makes sure that you don’t have any problems with your teeth.
Martha says, “I don’t follow doctor and dentist guidelines like that.” I don’t follow the rules that doctors and dentists give me, she’s saying. “I brush my teeth every day. That’s good enough.” That’s sufficient. “To brush (brush) your teeth” means to take a small, little tool, really, that you put something on called “toothpaste.” The tool is called a “brush” or a “toothbrush” and you put it in your mouth and you move it back and forth to clean your teeth. Or, you get one of those machines, where it moves for you. I like those; I have one of those. I forget what they’re called…Sonicare or something like that.
Anyway, Martha says she brushes her teeth every day and that should be enough. George says, “No, it’s not.” It’s not sufficient; it’s not enough; it’s not good enough. “You should be flossing every day.” “To floss” (floss) is to take a small piece of string and put it in between each of your teeth to remove any food that is stuck there – that is still there, because if it stays there it could eventually cause what is called a “cavity” (cavity). A “cavity” is like a hole in your tooth that the dentist then has to fill or fix. George says that Martha should be flossing every day and rinsing her mouth. “To rinse” (rinse) means to put some liquid in your mouth, like something like water, and move the liquid back and forth, and then usually you spit the liquid out again. The specific liquid you would use here would be mouthwash. “Mouthwash” is a special kind of liquid that is supposed to help keep your teeth healthy. He says that if you rinse your mouth with mouthwash it will keep your teeth and gums healthy. “Gums” (gums) is what your teeth are stuck into in your mouth. It’s the area of the skin on the inside of your mouth that holds your teeth in your mouth. “Gum” has a couple of different meanings in English however; take a look at the Learning Guide for some more of those.
George says, “If you haven’t been to a dentist in years, I’m not surprised you didn’t know that.” Martha says to George, “Stop preaching!” “To preach” (preach) in this context means to give someone else advice that they don’t want, usually in such a way that you are bothering them or you are acting as if you were better than them. “To preach” can also be a verb used in a religious sense, something that a minister or a rabbi or a priest might do. But here, it means to give advice that someone doesn’t want. Martha says, “Stop preaching! I’ll go to the dentist when I need to.” George says, “Like now,” meaning you need to go now. Martha says, “Maybe. It doesn’t hurt that much anymore…” George said, “I never knew you were such a chicken.” A “chicken” is an animal that you can eat. But, “chicken” here is used to describe someone who is scared of doing something, who is afraid, someone who is what we would call a “coward” (coward), someone who is not brave. George says, “I never knew you were such a chicken,” that you were so afraid. Martha makes a chicken noise that we would make in English, “Bwauk, bwauk, bwauk!” She’s saying, of course, that yes, she is a chicken.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Martha: Oh, I have a toothache!
George: It sounds like you’re in for a visit to the dentist.
Martha: That would be the last resort. I hate going to the dentist. I don’t like needles and the sound of the drill scares me to death. I’m hoping the toothache will just go away.
George: You really should get that checked out. Do you want me to make an appointment for you with my dentist?
Martha: No, thanks. I haven’t seen a dentist in years and I don’t plan to now unless I have no choice.
George: Years?! You haven’t been to a dentist in years? Haven’t you ever heard of preventive care? You’re supposed to get a dental cleaning twice a year.
Martha: I don’t follow doctor and dentist guidelines like that. I brush my teeth every day. That’s good enough.
George: No, it’s not. You should be flossing every day and rinsing your mouth with mouthwash to keep your teeth and gums healthy. If you haven’t been to the dentist in years, I’m not surprised you didn’t know that.
Martha: Stop preaching! I’ll go to the dentist when I need to.
George: Like now.
Martha: Maybe. It doesn’t hurt that much anymore…
George: I never knew you were such a chicken.
Martha: [makes a chicken noise] Bwauk, bwauk…!
[end of dialogue]
We hope you make an appointment each day to listen to a little bit of our ESL Podcast, especially to listen to the wonderful scripts by our scriptwriter Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
Glossary
toothache – a pain in one’s tooth, usually because the tooth is cracked or broken or there is decay (rot) in, under, or around the tooth
* Randall is taking aspirin for his toothache until he can get an appointment with his dentist.
in for – going to have or do something very soon; needing to have or do something, especially something unpleasant
* Melissa is pregnant and she’s in for a surprise once the baby is born! She has no idea how much work a baby can be.
dentist – a medical doctor who specializes in caring for teeth and oral (related to the mouth) health
* The dentist says I should stop eating so much sugar.
last resort – the last option one would choose or select, only after no other options are available, usually because it is very expensive, unpleasant, or embarrassing
* If the chemotherapy and radiation doesn’t stop the cancer, the doctors will try surgery as a last resort.
drill – a machine that makes holes in something
* How many oil drills operate in Texas?
checked out – examined or reviewed, especially by someone looking for problems
* If that rash doesn’t go away in a few days, you should probably have it checked out by a dermatologist.
appointment – a scheduled day and time when one will meet with someone for a particular purpose, especially with a doctor, attorney, advisor, or hair stylist
* Do you want to schedule an appointment for your next haircut?
preventive/preventative care – actions taken to keep oneself healthy and prevent or avoid health problems
* People who don’t have access to preventive care often end up with major medical problems that could have been prevented.
dental cleaning – the process in which a dental hygienist (a dentist’s assistant) cleans a patient’s teeth very thoroughly
* A dental cleaning usually takes about 40 minutes, assuming there aren’t any problems with the patient’s teeth.
to brush (one’s) teeth – to use a small brush-like tool and toothpaste to rub the surfaces of one’s teeth and gums (the skin around one’s teeth inside one’s mouth) to remove food and bacteria
* How many people brush their teeth after every meal?
to floss – to move a small piece of thin string between one’s teeth to remove food and bacteria
* If little pieces of corn get stuck between your teeth, just floss after you’ve finished eating.
to rinse – to put something under moving water to clean it and wash away whatever was on it
* Please rinse the dishes to remove the food before you put them in the dishwasher.
mouthwash – a liquid used to clean the inside of one’s mouth, but not swallowed
* Would you prefer a cherry- or mint-flavored mouthwash?
gums – the areas of skin on the inside of one’s mouth that hold one’s teeth
* Do your gums ever bleed when you brush your teeth?
to preach – to give advice, especially unwanted advice, in an annoying or superior way, telling other people what they should be doing
* It’s easy for rich people to preach about the importance of saving for retirement, but they don’t know how difficult it is to save money when you have a low-paying job.
chicken – a coward; someone who is not brave and is scared of doing something
* Are you going to walk through the cemetery with us on Halloween night, or are you chicken?
Comprehension Questions
1. What does George mean when he says, “You really should get that checked out”?
a) Martha’s tooth should be removed.
b) A dentist should look at Martha’s tooth.
c) Martha should take some medicine for the pain.
2. Why does Martha tell George to stop preaching?
a) Because she isn’t interested in religion.
b) Because she doesn’t want to hear his advice.
c) Because he’s giving her a headache.
Answers at bottom.
What Else Does It Mean?
drill
The word “drill,” in this podcast, refers to a machine that makes holes in something: “You’ll need a special drill if you want to put a nail into a concrete wall.” A “fire drill” happens when people who live, work, or study in a particular building are told to pretend that there is an actual fire, so that they can practice how they should act and where they should go: “I know fire drills are important for safety, but did the apartment manager have to do one in the middle of the night when we were all sleeping?” Finally, the phrase “the drill” refers to how things are normally done: “After a week of training, the new employees understood the drill and were able to work without help.”
gum
In this podcast, the word “gums” refers to the areas of skin on the inside of one’s mouth that hold one’s teeth: “Healthy gums are a light pink color, not red.” The phrase “chewing gum” or “bubble gum” refers to a flavored substance that one chews but does not swallow, to enjoy the flavor and/or to make one’s breath smell better: “After eating a lot of onions and garlic, it’s a good idea to chew some mint gum.” Something that is “gummy” is very chewy and a little bit sticky: “This bread wasn’t baked long enough and is too gummy to eat.” Finally, the phrase “to gum (something) up” means to affect a machine so that it cannot work properly and the parts cannot move: “Their young son gummed up their CD player when he tried to put his sandwich inside it.”
Culture Note
How to Become a Dentist
According to the “Bureau of Labor Statistics” (part of the U.S. Department of Labor), people who want to become a dentist need to have at least two years of “pre-dental education,” or “courses” (classes) related to dental work, such as biology and “human anatomy” (the study of the parts of the human body). Most people need to “obtain” (get; earn) a college degree before they apply to “dental school” where they receive specialized training.
All “aspiring” (wanting to do or have something, especially a job or position) dentists need to pass the Dental Admissions Test (DAT). Dental schools consider the applicant’s DAT score, GPA (grade-point average, a measure of one’s academic success), “recommendations” (the opinions of people who know the candidate), and performance during an interview. In 2008, there were 57 “accredited” (recognized by a leading organization as meeting certain criteria) dental schools in the United States, and it can be difficult to “get in” (be admitted; be invited to enroll in an academic program).
Dental school usually lasts four years. The first two years are spent mostly in science courses and “lab work” (conducting experiments in a laboratory). The last two years are spent in “clinics” (medical facilities) working with patients under the “supervision” (observation and guidance) of a “licensed” (having a certification) dentist. At the end of the four years, the students receive their DDS (Doctor of Dental Surgery) or DMD (Doctor of Dental Medicine) degree.
Finally, aspiring dentists need to pass written and “practical” (actually doing something) exams to receive a license from the states in which they wish to “practice” (work as a dentist). Specialization can require an additional two to four years of study and an additional licensing exam.
Comprehension Answers
1 - b
2 - b