= 0782
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 782: Expressing Bitter Feelings.
This is English as a Second Language Podcast episode 782. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to eslpod.com today, and become a member of ESL Podcast. You can download a Learning Guide for this episode, and all of our current episodes if and when you do.
This episode is a dialogue about “bitter feelings,” about being angry at someone else. Sounds like fun! Let’s get started.
[start of dialogue]
Laurent: I’m done with women! They’re liars and manipulators.
Julie: Let me guess. You’ve had a bad breakup?
Laurent: It wasn’t just bad. It was monumentally awful. I’m never going to date again.
Julie: You’re just feeling bitter right now, but you’ll get over it. You won’t always feel so jaded. Wait a second. Did you break up with Brittany?
Laurent: Yeah, I’ve told you about her before.
Julie: I remember. Don’t you guys have an on-again, off-again relationship? I mean haven’t you guys broken up before?
Laurent: Yeah, but this was the absolute end. We’re not getting back together.
Julie: But didn’t you say that three months ago? Maybe there’s still a chance for reconciliation.
Laurent: Absolutely not! Brittany walked all over me and didn’t care one iota about my feelings. I’ll never talk to her again. As far as I’m concerned, she’s persona non grata!
[Phone rings]
Julie: Hello. Oh hi, Brittany. Yes, he’s here. It’s Brittany and she wants to talk to you. Do you want to talk to her?
Laurent: Yes…no…yes! Oh, give me that phone!
[end of dialogue]
Our dialogue begins with Laurent – his name is French, I know I have a terrible French accent – Laurent says, “I’m done with women!” “To be done with (something or someone)” means you don’t want to be involved or have anything to do with that thing, or in this case, people. Laurent says he’s done with women, “They’re liars and manipulators.” “To lie” means not to tell truth. “To be a liar” (liar) is to be a person who does not tell the truth. Laurent thinks that women are liars and manipulators. A “manipulator” is someone who manipulates. “To manipulate” means to control another person by tricking or fooling them. It’s not an obvious sort of thing; it’s what we might call a “subtle” thing. “To manipulate (someone)” is to get them to do something for you that you want done. A “manipulator” would be a person who manipulates other people.
So women are liars and manipulators, at least that’s what Laurent thinks. Julie says, “Let me guess. You’ve had (or you have had) a bad breakup?” A “breakup” (one word) is when a romantic relationship ends, when two people decide they are not going to be romantically involved with each other anymore. How sad. Poor Laurent! He says, “It wasn’t just bad. It was monumentally awful.” He’s saying it was worse than bad. “Awful” is the same as terrible, very bad. “Monumentally” is here used to mean extremely, in a big way, or simply very much. He says, “I’m never going to date again.” And Julie says, “You’re just feeling bitter right now, but you’ll get over it.” “Bitter” (bitter) here means feeling that something was unfair or something was wrong. Perhaps someone did something wrong to you or you were hurt in some way, and now you don’t want to forgive the other person. You don’t want to forget how hurt you were. “Bitter” has some other meanings in English as well; take a look at our Learning Guide for those.
Julie says that Laurent is just feeling bitter, but he’ll get over it. “To get over (something)” is a phrasal verb meaning to no longer be mad or upset over something, to recover, to feel better, and no longer be so angry. Julie says, “You won’t always feel so jaded.” “Jaded” (jaded) usually is when you have a lot of experience with something and it no longer interests you, it bores you, you’re no longer enthusiastic about it. I’m not sure if that’s Laurent’s problem; I’m not sure if that’s the right word to describe how he’s feeling. Julie, I think, means that he’s feeling depressed, which I suppose could be related to being jaded.
Anyway, Julie says, “Wait a second. Did you break up with Brittany?” Laurent says, “Yes, I’ve told you about her before.” Julie says, “I remember. Don’t you guys have an on-again, off-again relationship?” “On-again, off-again” means that sometimes you do it and sometimes you don’t. That is, sometimes you, perhaps, are girlfriend and boyfriend, and then other times you’re not. A “relationship” is obviously an association or connection or involvement with another person. So, an on-again, off-again relationship would be one where you are romantically involved, and then you breakup, and then you get back together again, and so forth. Julie says, “I mean haven’t you guys broken up before?”
Laurent says, “Yeah, but this was the absolute end.” “Absolute” (absolute) here means definite or definitive, without any doubt, without any question. This is the end, that’s what Laurent is saying. He says, “We’re not getting back together.” “To get back together with (someone)” would be to end a romantic relationship, to have a breakup, and then to start the romantic relationship again two months later or a week later or whenever.
So Laurent says that he and Brittany are not going to get back together again, but Julie says, “But didn’t you say that three months ago?” meaning you’ve promised before that you weren’t going to get back together again. “Maybe there’s still a chance for reconciliation.” “Reconciliation” is when two people, or two organizations even, have some sort of disagreement and separation. “Reconciliation” tries to bring them back together again, usually it’s in a romantic relationship.
Laurent says, “Absolutely not (no)! Brittany walked all over me and didn’t care one iota about my feelings.” “To walk all over (someone)” is to take advantage of another person, to use the other person for what you want and not care about that person. Well, Laurent says that Brittany walked all over him and didn’t care one iota about his feelings. “Iota” (iota) is a very small amount of something; here, it means almost nothing. She didn’t care at all about his feelings. He says, “I’ll never talk to her again. As far as I’m concerned, she’s persona non grata!” “Persona non grata” is a Latin expression; it means that person is not welcome here. You will not talk to them, you will not let them in your house, you don’t want them in any way.
Then, suddenly, the phone rings, and Julie answers the phone. She says, “Hello. Oh hi, Brittany.” Brittany is calling on the telephone. Julie then says, “Yes, he’s here,” because Brittany has asked Julie if Laurent is here. Julie then says to Laurent, “It’s Brittany and she wants to talk to you. Do you want to talk to her?” Of course, we know that he just said he didn’t want to talk to her anymore, but of course he says yes. “Yes…no…yes!” he says, “Oh, give me that phone!” Let me talk to her on the phone.
So, that’s what happens to some men. They never learn their lesson, and they continue to go back and back and back again. Of course, maybe Laurent is in love, or maybe he’s just not very intelligent. Sometimes love can make you stupid!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Laurent: I’m done with women! They’re liars and manipulators.
Julie: Let me guess. You’ve had a bad breakup?
Laurent: It wasn’t just bad. It was monumentally awful. I’m never going to date again.
Julie: You’re just feeling bitter right now, but you’ll get over it. You won’t always feel so jaded. Wait a second. Did you break up with Brittany?
Laurent: Yeah, I’ve told you about her before.
Julie: I remember. Don’t you guys have an on-again, off-again relationship? I mean haven’t you guys broken up before?
Laurent: Yeah, but this was the absolute end. We’re not getting back together.
Julie: But didn’t you say that three months ago? Maybe there’s still a chance for reconciliation.
Laurent: Absolutely not! Brittany walked all over me and didn’t care one iota about my feelings. I’ll never talk to her again. As far as I’m concerned, she’s persona non grata!
[Phone rings]
Julie: Hello. Oh hi, Brittany. Yes, he’s here. It’s Brittany and she wants to talk to you. Do you want to talk to her?
Laurent: Yes…no…yes! Oh, give me that phone!
[end of dialogue]
She’s the absolute best scriptwriter on the Internet. I’m speaking, of course, of the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
to be done with (something) – to not want to have or do something anymore; to no longer want to try to do something, especially because it is too difficult or frustrating
* I’m done with practicing the violin! It’s just too difficult to learn to play it!
liar – a person who lies; someone who does not tell the truth.
* Don’t trust Dustin. He’s a liar.
manipulator – a person who tricks other people in subtle (hidden, barely noticeable) ways to get them to do what he or she wants
* Lorenzo realized that his coworker Bob was a manipulator and was good at getting other people to do his work, but still taking credit for it.
breakup – the end of a romantic relationship
* Adriana didn’t date for almost four months after her last breakup.
monumentally – in a big way; extremely; very much
* Choosing the right person to marry is monumentally important to your future happiness.
awful – terrible; very bad; very unpleasant
* This soup tastes awful! How much garlic did you put in it?
bitter – resentful; feeling that that something was unfair, unjust, or wrong and not willing to forget about what happened or forgive the other person
* Are you still bitter about what happened? That was more than five years ago!
to get over (something) – to no longer be upset about something that happened in the past and be able to live as if it had never happened
* Derek is really upset he didn’t get the promotion, but hopefully he’ll get over it soon.
jaded – depressed; tired; exhausted; sad and without enthusiasm or energy, usually after having too much of something
* Sheila spent months planning the wedding, but she started to feel jaded a few weeks before the big day.
on-again, off-again relationship – a romantic relationship where the couple starts and stops dating many times
* They love each other, but they often have big fights, so they’re in an on-again, off-again relationship.
absolute – definitive; definite; without question; without any doubt or hesitation
* That was the absolute worst movie I’ve ever seen!
to get back together – to renew or resume a romantic relationship; to begin dating someone whom one previously dated in the past
* After her parents’ divorce, Fatima hoped for years that they would get back together.
reconciliation – the reestablishment of a relationship; the end of an argument or fight; the point in time when two people agree on something and are no longer angry with each other
* Viktor bought his wife a beautiful sweater as an attempt at reconciliation.
to walk all over (someone) – to take advantage of another person; to use another person to get what one wants, without considering that person’s feelings
* Why is Greta still dating him? He walks all over her and never does anything nice for her.
iota – a very small amount; almost nothing; almost zero
* There isn’t even an iota of truth in that story.
persona non grata – a person who is not wanted, welcome, desired, or important
* When James lost the contract, his co-workers started treating him like a persona non grata.
Comprehension Questions
1. Why is Laurent frustrated with women?
a) Because they don’t tell the truth.
b) Because they spend too much money.
c) Because they are very selfish.
2. What does Laurent mean when he says, “Brittany walked all over me”?
a) Brittany stepped on his feet.
b) Brittany treated him badly.
c) Brittany never rode in his car.
Answers at bottom.
What Else Does It Mean?
bitter
The word “bitter,” in this podcast, means resentful, or feeling that something was unfair and not being willing to forgive or forget: “Jerry is a bitter old man who never says anything nice about anyone.” The word “bitter” can also describe something that makes one feel very unhappy: “When Wallace decided to become a musician instead of a doctor, it was a bitter disappointment for his parents.” The phrase “bitter cold” describes very cold weather: “You’ll need to buy a warm jacket for the bitter cold before you move to Minnesota.” The word “bitter” can also describe the strong taste of something that is not sweet: “Ulysses never drinks coffee because he thinks it’s too bitter.” Finally, the phase “to the bitter end” describes finishing something in a long and difficult process: “Shane and his doctors fought the cancer to the bitter end.”
absolute
In this podcast, the word “absolute” means definite or without question or doubt: “This ice cream is the absolute best I’ve ever tasted.” Or, “The landlord has the absolute right to cancel the contract at any time with 30 days’ notice.” The word “absolute” can also mean total or complete: “Your room is an absolute disaster. Clean it now.” Sometimes the word “absolute” means without limits or restrictions: “Do you believe parents should have absolute control over their children’s decisions?” The phrase “an absolute majority” refers to someone receiving more than 50% of the votes: “Four candidates were running for office, but Mitch won with an absolute majority.”
Culture Note
Classic Breakup Songs
A lot of “pop music” (popular songs) is about romantic love and relationships, but some are about breaking up. Some people believe that listening to “classic” (very popular over time) breakup songs like the ones below can help them “recover from” (feel better after) their own breakup.
Here are some of the “lyrics” (the words sung in a song) to “Breaking Up is Hard to Do,” which was recorded by Neil Sedaka in 1962 and 1975.
Don’t take your love away from me
Don’t you leave my heart in “misery” (extreme sadness)
If you go then I’ll be “blue” (depressed)
‘Cause (because) breaking up is “hard” (difficult) to do
They say that breaking up is hard to do
Now I know, I know that it’s true
Don’t say that this is the end
Instead of breaking up I wish that we were “making up” (ending an argument) again
And here are some of the lyrics to “50 Ways to Leave Your Lover,” which was recorded by Paul Simon in 1975.
She said it’s really not my “habit” (something one does regularly)
To “intrude” (interfere; interrupt)
Furthermore, I hope my meaning
Won’t be lost or “misconstrued” (misunderstood)
But I’ll repeat myself
At the risk of being “crude” (rude; rough)
There must be fifty ways
To leave your lover
Fifty ways to leave your lover
You just “slip out the back” (leave unnoticed), Jack
Make a new plan, Stan
You don’t need to be “coy” (pretending to be shy), Roy
Just get yourself free
Hop on the bus, Gus
You don’t need to discuss much
Just drop off the key, Lee
And get yourself free.
Comprehension Answers
1 - a
2 -b