= 1326
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 21.
This is English as a Second Language Podcast’s English Cafe episode 21. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we’re going to talk about the state of Minnesota, where I’m from. We’re also going to talk about interjections – those short words we use in conversation to show emotion. And as always, we’ll answer a few of your questions. Let’s get started.
We’re talking today about one of the greatest of our 50 states. Of course, it’s the state where I was born and raised, or grew up, and that is the state of Minnesota. Minnesota is located in the upper Midwest in the United States. It’s the central-northern part of the country, next to Canada.
The term “Midwest” is used to describe the states in the center part of the country, but you will get different definitions if you ask different Americans what states are in the Midwest. Most people would probably include states such as Minnesota, Wisconsin, North Dakota, South Dakota, Iowa, Illinois, Ohio perhaps, Missouri, Nebraska – those states might all be considered part of the Midwest. But there isn’t a definite line that we could draw that everyone would agree on. Basically, it’s in the middle of the country.
The capital, or most important governmental city in Minnesota, is St. Paul. And that’s my hometown. Your “hometown” (hometown) is the town where you were born. I was born in St. Paul. It’s my hometown. The state of Minnesota has a population of over five million people. The first immigrant groups, or people from other countries who went to live in Minnesota – from Europe, of course – were people from Germany, Sweden, and Norway.
Now technically, the first Europeans to be in Minnesota were the French who came with the French explorers who also went up into Canada – but if we’re talking about the immigrant groups that stayed and developed the state, we would focus on Germany, Sweden, and Norway, as well as some of the other Northern European countries. A lot of people went to Minnesota back in the nineteenth century for farming. Like other states in the Midwest, Minnesota has good “farmland” – places where you can grow plants.
Another reason people went to Minnesota was for logging. “Logging” (logging) is the business of cutting down trees and preparing the wood from the trees for building. As in many other parts of the country, the people who settled or moved to this part of the U.S. influenced the way that English was spoken. Immigrant groups often influence the vocabulary as well as the pronunciation of English in different regions in the United States.
There was a famous movie back in the mid 1990s called Fargo, and this was a movie that takes place, or is set, in Minnesota, although the town of Fargo is actually in the state next to Minnesota, North Dakota – one of the states, I should say, next to Minnesota. However the accent in the movie, and some people would say of a lot of people from Minnesota in general, is very distinctive. It’s very noticeable.
One of the things you will notice about a Minnesota accent is that it has what we would call very long O’s. People say Minnesota, “Minnesota.” The “o” is quite long. Instead of “Minnesota.” Being from Minnesota, I still have a little bit of Minnesotan in terms of my accent, although I’ve lived in California for more than 25 years, so I don’t have a strong Minnesota accent. Usually it’s only when I go back to Minnesota that I hear that accent and start speaking like the people around me.
There are also certain expressions that are popular in Minnesota in particular. One of them is “You betcha.” The word “betcha” means “bet you,” although we pronounce it as though it were spelled (betcha). “You betcha” means “yes.” It’s an informal and friendly way of saying “yes” somewhat emphatically, somewhat with emphasis. If someone says to you, “Is it raining outside?” and it’s really raining, you might say, “Oh, you betcha!”
“You betcha” can also be used to emphasize that what I’m telling you is true, that you should believe what I’m telling you. So if your wife asks why all of the food in the refrigerator is gone, and you tell her that the dog ate it, she may say to you, “That dog really ate all of the food and not you?” And you could say, “You betcha,” meaning absolutely – that’s correct.
Minnesota is famous for other things as well. It is the home of two vice presidents in the past 60 years, as well as two presidential candidates. The state of Minnesota has traditionally been a politically liberal state, similar to California. It’s difficult to give an exact definition of what Americans mean by “liberal,” or for that matter, “conservative.” “Liberal” in the United States does not mean the same as it might in other countries. Usually, we associate the politics of the Democratic Party with the liberal ideals and positions.
Liberals often believe that government should have more of a role – a more active role, shall we say – in the economy and in daily life. American conservatives tend to favor a more limited role for government. That’s one of the many differences between those who say they are liberals, and those who say they are conservatives. Minnesota has, I say, traditionally been a liberal state, although there have been more recently conservatives who have been elected to positions in the state, but for the most part, it’s still a very liberal state, a state that is mostly democratic.
The two vice presidents who’ve come from Minnesota have both been Democrats. Hubert Humphrey was the vice president for President Lyndon Johnson in the 1960s. He actually ran for president himself and lost to Richard Nixon. The other vice president from Minnesota was Walter Mondale. He was President Jimmy Carter’s vice president, and he lost in 1984 to President Ronald Reagan.
Because Minnesota is in the northern part of the country, it’s also famous for being very, very cold in the wintertime. People associate Minnesota or think of Minnesota as having a lot of cold weather, and cold weather sports are popular in the state. Hockey, in particular, is very popular in the state.
“Hockey” (hockey) is a team sport played on ice. You probably have seen it. In the Olympics, for example, there are hockey competitions. I played hockey, believe it or not, when I was very young – not too much. My older brothers all played hockey, however. It’s something that you can do outside during the winter in Minnesota because it’s so cold.
Another sport that was popular in Minnesota for some time, and I think is still popular in some areas, is the sport of curling. “Curling” (curling) is a sport where you move a big rock, a big stone, across the ice. You push it and you try to get the rock to go in a certain place to score points. I myself have never played the sport of curling, although my father played curling – or was on a curling team, I guess – when he was young. I don’t know if we use the verb “play” – “I play curling.” People would probably say, “I curl.” That’s how little I know about the sport.
Even though curling is not something that most Minnesotans have done, most Minnesotans have probably learned how to skate, and many of them have learned how to play hockey. Hockey is still a very popular sport in the state, so if you have a chance to go to Minnesota, I definitely can recommend it in the summertime or in the fall or spring. Of course, if you like cold weather, then Minnesota is a great place to go in the winter as well. The state is fairly flat, so it’s not a place where you would do a lot of skiing as you might in a state such as Colorado, or even here in California.
Minnesota is sometimes called the “Land of 10,000 Lakes.” That’s because Minnesota has a lot of lakes. In fact, it has more than 15,000. Why isn’t it the “Land of 15,000 Lakes”? Well, Minnesotans are what we call “modest.” “To be modest” (modest) means to not talk about yourself and how good you are or great you are, to not think that you are really better than anyone else around you. If you love to fish or go on a boat on a lake, Minnesota is a great place for that as well.
Our second topic today is interjections. An “interjection” (interjection) is a word or phrase that you say, often at the beginning of a sentence, that expresses some strong emotion. It could be a positive emotion. It could be a negative emotion. You might say, for example, if you touch something very hot, “Ouch!” “Ouch” (ouch) is when you hurt yourself. That’s the interjection we might use.
Another interjection you may hear that expresses a strong emotion related often to surprise or shock is “man.” The word “man,” of course, refers to a male human being like me, but it can also be used as an interjection. If it’s very cold out, you may say “Man, it’s cold.” “Man” doesn’t really mean anything. It’s just an expression of surprise or perhaps disappointment. “Man, I lost the game again.” There, “man” expresses your disappointment at something.
If you make a mistake, you might use the interjection “oops.” “Oops” (oops) is when you make a mistake, when you do something wrong. We would use this when it’s a small mistake, a minor mistake. If you, say, step on someone’s foot by accident, you may say, “Oops, I’m sorry.” You may remember the Britney Spears song back many years ago, “Oops, I Did It Again.” “Oops” means I made a mistake. And if you’re listening to Britney Spears’ music, you’re probably making a very big mistake indeed.
Another expression, another interjection, is “geez.” “Geez” (geez) is similar to “man.” It’s when you are shocked or disappointed about something. “Geez, it’s hot in here.” That would be the same as “Man, it’s hot in here” – or we could also say, “Wow, it’s hot in here.”
Yet another interjection is “ugh.” “Ugh” (ugh) is usually something that you will hear; it’s not something that would normally be written, other than perhaps as part of a dialogue in a novel. Usually we say “ugh” when we’re reacting to something we don’t like – something that’s bad, or perhaps something that’s ugly or even smells bad.
“Boo” (boo) is an interjection that we would use when you’re trying to scare someone, to frighten someone. Usually this interjection is used jokingly or playfully. If you say to someone, “Boo!” you’re trying to scare them. Perhaps they didn’t see you, and you walk up behind them – you could say “Boo!” in order to make them jump, in order to make them react with surprise.
If you are working on some problem that you’re trying to find a solution for and you finally figure it out, you can use the interjection “aha” (aha). “Aha” is when we finally learn the truth of something or we finally figure something out.
Another interjection that you will hear especially children and teenagers use is “duh” – (duh) is how it’s usually spelled, although again, these are – some of these are words that you would only hear rather than read. “Duh” is used when you don’t think the other person has said something very intelligent – when you think that what the person is saying is obvious, so obvious that you don’t even have to say it. If someone says to you, “I think the sun will rise in the east and set in the west today,” you might say, “Well, duh.” It’s obvious. That’s what happens to the sun every day.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Michelle (Michelle) in Belgium. The question has to do with the expression “smoking gun.” The phrase “smoking gun” is used to indicate that there is evidence that someone has done something wrong. The smoking gun is the actual evidence of recent wrongdoing. Why do we say “smoking gun”?
Well, a gun as you know, is a weapon, something that is used to shoot bullets – bullets that could, of course, kill someone. After you shoot a bullet from a gun, at least traditionally the idea is that there would be some smoke coming from the gun. I’m not sure if that actually happens, having never shot a gun (or at least a pistol – a handgun), but you can tell the gun has been shot from the smoke, and that’s the idea of a “smoking gun.” It’s evidence that someone has done something wrong, usually evidence that points to a particular person that indicates that a particular person has done something wrong.
Our next question comes from Patricio (Patricio) in Chile. Patricio wants to know the uses of the word “rather,” especially in the expression “would (would) rather (rather).” “Would rather” is the same as “would prefer.” It’s an expression we use to state something that we would like to happen. “I would rather go to the movies.” That’s my preference.
“Would rather” is usually paired with, or usually occurs in a sentence with, the word “than” (than). “I would rather go to the movies than go to the beach.” In other words, my preference is not to go to the beach, but to go to the movies . So you are comparing which of the two things you would rather do, or which of the two events you would prefer. “I would rather drink coffee in the morning than exercise.” That is my preference.
Now, sometimes we may say “I would rather” for something that we don’t want to do if we didn’t have to, but if we have to choose between two alternatives, between two choices, well, this would be the one that I would prefer: “I would rather exercise than listen to Britney Spears.” Exercising is less painful to me than listening to Britney Spears. That would be an example of a case where you don’t want to exercise, but you would prefer it over a worse alternative.
So, thank you for those questions.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2006 by the Center for Educational Development.
Glossary
upper Midwest – the portion of the United States typically including Minnesota, Wisconsin, Michigan, Iowa, North Dakota, and South Dakota, and parts of Illinois and Nebraska
* Marcetta has always lived in the upper Midwest, but she has lived in both Minnesota and Iowa.
distinctive – having a specific, unique quality; distinguishable or easy to tell apart from other things
* Olivier wears a very distinctive hat that makes him easy to find in a crowd.
you betcha – a shortened form of "you bet you," typically used in Minnesota; an expression used to mean “yes” or to tell someone that he or she should believe what one is saying
* When asked if she planned on going to see the new hit film, Maira replied, “You betcha! I’ve been looking forward to it for weeks.”
liberal – a political set of ideals typical to people who are part of the Democratic political party; a set of political beliefs focused on social reform or change
* Wilson is more liberal than the rest of his conservative family and usually votes for the Democrat candidates.
curling – a sport in which players from two teams, each with four players, take turns skating while pushing a large, flat stone across the ice using special brooms and aiming at a target, mark, or ring painted on the ground
* Jun isn’t good at curling, because he is not a good ice skater.
hockey – a sport in which two teams try to get a small puck (small, flat and round object) into different goals or nets by hitting that puck with sticks shaped like the capital letter "L," usually played by skating on ice or on a smooth floor
* If the pond freezes over, Billy and his friends want to start a hockey game.
interjection – an exclamation or outburst; a word or expression used to express strong emotion
* Paola likes to start her sentences with interjections, such as “Ah” and “Geez.”
man – an interjection or exclamation that expresses surprise, shock, or extreme disappointment
* Oh, man! I was supposed to leave work 30 minutes ago, but I completely lost track of time.
geez – an interjection or exclamation used to express surprise, shock, or frustration
* Geez! Malcolm is a nice guy, but he sure is irresponsible when it comes to money.
oops – an interjection or exclamation used when one has made a mistake, usually when that mistake is not serious
* When Alejandra accidentally fed her cat twice the amount it was supposed to eat, she laughed and said, “Oops!”
ugh – an interjection or exclamation that expresses one's dislike; a word used in response to something that one finds very unappealing, unattractive, ugly, disgusting, or bad
* Victor walked into the room looking pale and said, “Ugh, I think the food I ate for lunch was bad. I don’t feel very good right now.”
boo – an interjection or exclamation one uses when trying to surprise or scare someone; an exclamation used to express dislike or disapproval of a situation
* Myrtie’s four-year-old son jumped out at her from behind the door shouting, “Boo! Did I scare you, Mommy?”
aha – an interjection or exclamation used when someone finally thinks of the solution to a problem or finally learns the truth about something; an exclamation expressing a sense of triumph or victory
* After working on the difficult jigsaw puzzle for a half an hour, Hector finally finished it, shouting a joyful “Aha!” as he put the final piece in place.
duh – an interjection one uses when a statement or comment someone else made states an obvious truth or fact that does not need to be stated, often used by kids and teenagers
* When asked if she had a good time over summer break, Amada replied, “Duh, of course I did. After all, I wasn’t in school.”
smoking gun – a clue or evidence that clearly shows who was responsible for a crime or wrongdoing
* The forged documents were the smoking gun showing investigators Ed was the person responsible for tampering with the company’s financial records.
would rather – would prefer; an expression used to state one's preference, or which option one would like
* Mona is willing to have pizza for dinner, but she would rather go out to eat at a nice restaurant.
rather – very much; quite
* Jamel was in a rather cheerful mood that day and could not stop smiling.
What Insiders Know
Zero Tolerance
“Zero tolerance” is a type of “policy” (rules) where unwanted or bad behavior is punished very “severely” (harshly; very much). This type of policy is usually used in criminal matters where someone has broken the law, or where someone has “violated” (not followed; gone against) a company or organization’s rule or regulation. It usually means that even if this is a person’s “first offense” (first time breaking the law or the rule), he or she will be punished severely.
In the U.S., in many states, there are zero tolerance laws for drug offenses, such as “dealing” (selling) drugs, and for “prostitution” (selling sex). There are also zero tolerance laws in some states against “domestic abuse” (causing injury to a family member or someone else who lives in one’s home). Some businesses and organizations have zero tolerance rules against “sexual harassment,” when men or women are “subjected to” (have no choice but to see/hear/experience) unwanted sexual behavior or “obscene” (offensive; disgusting) language or behavior.
Schools are places where there are often zero tolerance policies. These days, many schools have zero tolerance policies to protect student safety. If a student brings a “weapon” (tools used for fighting, such as knives and guns) to schools, for example, that student may be “suspended” (required to stay away from school for a certain number of days) or even “expelled” (required to leave the school and never allowed to return).