= 1334
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 29.
This is English as a Second Language Podcast’s English Café episode 29. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we’ll be talking about the movie Inside Man by the famous American movie director, Spike Lee. We’ll also talk a little about how Americans buy their groceries. And, as always, we’ll answer a few of your questions. Let's get started.
Today we begin by talking about a movie directed by a very famous and influential movie director named Spike Lee. “Spike (Spike) Lee (Lee)” has been making movies for the past thirty years. He has directed several very good films. Probably his most famous movie is Do the Right Thing, about black and white people in New York City – how they get along with each other and how they don’t get along with each other.
The movie we’ll talk about today is a less well known, but still a very good movie by Spike Lee called Inside Man, starring Denzel Washington. Denzel Washington is a very famous African American actor who has been in many different movies.
Inside Man is about a bank heist. A “heist” (heist) is an armed robbery, which is when people use guns to steal things like jewelry or money. Often, a heist will occur at a bank. The robber goes in to a bank and takes out a gun and gives the “teller” – the person working behind the counter – a note that says something like, “Give me a hundred thousand dollars,” or something like that. I haven’t robbed a bank in many, many years, but I think that’s right.
Anyway, this is what is known as a “bank heist” or a “stickup” (stickup) or a “holdup” (holdup). It’s called a “stickup” or a “holdup” because the idea is that someone has a gun and tells everyone to “hold up” or “stick up” their hands in the air where the robbers can see them, so no one shoots the robbers. This movie is about a bank heist in which there are hostages. A “hostage” (hostage) is someone who is taken prisoner by the criminals. Usually the criminals use the hostage to try to escape, to get away, or to get something from the family of the hostage. This particular movie also stars Jodi Foster, who’s a very good actress, and a British actor named Clive Owen.
The movie takes place in New York City. There is also a masked bandit in the movie. A “bandit” (bandit) is another word for a thief, and a “masked (masked) bandit” is a bandit who is wearing a mask. A “mask” is something that you put over your face so that people will not recognize you or know who you are. And if you are trying to hold up a bank, you probably don’t want anyone to know who you are. Inside Man is a very exciting and entertaining movie that I think you will enjoy. It’s a few years old now, but still well worth trying to find in DVD or online.
Our next topic is about the way that Americans buy their groceries, the food they eat at home. When you are trying to understand another country and another language, it is important to know how people do everyday, common activities. Buying food is an activity that people do everywhere, all over the world, but each country does it in a slightly different way.
Los Angeles may not be a typical American city – there are many things that are different about Los Angeles – but one thing that Los Angeles has in common with most American cities is the way people do their grocery shopping. The word “groceries” (groceries) means food, as I mentioned earlier, and when we go “grocery shopping,” we are going to buy food. “Groceries” is the plural form, but we use the singular form “grocery” in the phrase “grocery shopping,” which means to buy groceries. However, as a noun, it’s always plural – “groceries.” The store where we buy groceries is called the “grocery store.”
Almost all Americans buy their food at a grocery store or what we also call a “supermarket.” A “supermarket” (supermarket) is a large store that sells many different foods. If you walk into an American supermarket, the first thing you may notice is how big it is. We have very large supermarkets now, but it wasn’t always this way. I remember many years ago, when I was a child, back before the telephone and automobiles, going to the little grocery stores in our neighborhood. You would walk maybe four or five blocks down the street and there would be a small grocery store where you could buy things like milk and meat and canned goods. “Canned” (canned) means things that come in a can, like soup, for example.
These little neighborhood grocery stores were once very popular, but in the last 30 years or so, many of these small stores have disappeared, they’ve closed. You don’t see them as much anymore. You still see them in places like neighborhoods in New York City, but in Los Angeles and elsewhere they’re not as common. Instead, now we have these very large supermarkets, and most of them are what we would call “chain stores.” A “chain (chain) store” is a store that is owned by a big company. The company might own dozens or even hundreds of these chain stores across the country or across a region.
Supermarkets are popular because you can buy all of your food in one place instead of going to a lot of different stores. In some countries, people go a bakery every day to buy bread, a butcher shop to buy meat, another store to buy milk, and so forth. But here, most people buy their bread in the supermarket, and usually the bread is already “sliced.” “To slice (slice)” something means to cut something into thin pieces. Because most people buy their bread at the supermarket, the small bakeries here don’t make much money selling bread; instead, they make their money selling things like cakes and cookies and croissants. Many bakeries have also become cafés where people can drink coffee, meet with friends, read a book, and bother other people by talking loudly on their cellphones.
Similarly, very few people these days buy their meat at a separate store like they did in the past. We used to buy meat at what was called the “butcher’s shop.” A “butcher” (butcher) is the person who cuts the meat for you in the store. There are still some independent butcher shops in the United States, but it’s not very common anymore. The same is true for fish. Most people don’t buy their fish at a fish market anymore; they usually just go to the supermarket. It is more convenient, or easier, to shop at a supermarket, but the food is often not as fresh in the big chain stores as it would be at the small, independently owned bakeries or butcher shops or fish markets.
Recently, more people in Los Angeles and other cities have started shopping at what are called “farmer’s markets.” A “farmer’s (farmer’s) market” is a place where you can buy vegetables and fruits and other things directly from the people who grow them, from the farmers. Yes, there are farmers here in California – many farmers, in fact. California produces a lot of cheese and fruit and vegetables. And some of these farmers come to the city to sell their “produce,” which is another word for fruits and vegetables. The produce is usually more fresh at the farmer’s market than at the supermarket, but it’s often a bit more expensive, as well.
The farmer’s markets move around to different parts of the city on different days. So, you might find a farmer’s market on the north side of the city on one day, and then on the west side on the next day, and so forth. I’ve been to farmer’s markets a couple of times, and I like going there. The food is often very good, better than what you can buy in the grocery store. But they’re still not the common place for people to do their grocery shopping in the United States.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Gax (Gax) in Macau, who wants to know the meaning of a “catch-22.” What is a “catch” (catch) and how is it related to the number 22? This expression originated from a novel titled “Catch-22,” by the American author Joseph Heller. A “catch-22” is basically a problem that is impossible to solve – an impossible situation. Probably the best way to explain a catch-22 is with an example.
Let’s say that you want to learn a new language called “Language X.” But say the only way to learn Language X is to go to the country where they speak Language X – we’ll call this country “X-Land.” So, you go to apply for a visa to be allowed to enter the country of X, because you want to learn Language X. But the people who live in X-Land (called “X-Men, of course!), tell you that you are only allowed to enter X-Land if you already know how to speak Language X.
This is what we call a “catch-22.” In order to learn Language X, you have to study it in X-Land, but in order to go to X-Land, you have to already know Language X, otherwise you can’t get a visa. It is an impossible situation; there is no solution to this problem. Each situation prevents the other from ever taking place. And that’s a “catch 22.”
Our next question comes from Alberto (Alberto) in Spain. Alberto wants to know when he should use “can” (can) and when he should use “to be able to.” Usually, these two expressions can be used “interchangeably,” meaning in exactly the same way. For example, “I can help you” and “I am able to help you” mean the same thing. I would say that “can” is more common, however.
You might hear someone say, “Are you able to go?” which is a little more formal than saying “Can you go?” But there isn’t really any difference in terms of their meaning. There might be some expressions in which people would use “can” more often than they would use “able to,” but I wouldn’t worry too much about which one to use. You can use either, but “can” is probably a little bit more common.
Josivan (Josivan) in Brazil wants to know what the expression “no longer” means. “No longer” means not now and possibly not in the future. For example, “He is no longer here” means that he was here earlier, but now he is not here anymore. The idea is that something that was happening in the past is not happening anymore, is not happening now. So, “I am no longer going to talk to my neighbor” means I used to talk to my neighbor in the past, but from now on, I’m not going to talk to him anymore.
Our next question comes from Luc (Luc) in Belgium. Luc wants to know about the expression “the bottom line” and if there is a difference between “the bottom line” and “period.”
The expression “bottom line” comes from accounting, from business. In business, you add up all of the money that comes in – your “income” – and subtract all of the money that goes out – your “expenses.” At the end, you are either going to have a “profit” (profit), meaning you made more money than you spent, or a “loss” (loss), meaning you spent more money than you made. The “bottom line” is the very last line in this list, and it shows the final result: whether you made money or lost money.
That’s where the expression comes from originally, but now people use it in a much more general way. For example, “The bottom line is that we can’t afford a new television.” We could talk for a long time about how much we want a new television, but talking about it further will not change the facts, and the fact – the bottom line – is that we can’t afford a new television. In this case, we could also say, “We can’t afford a new television, period.” “Period” is used to mean, “There’s no reason to talk about it any more” or “this is definitely not going to happen.”
In business or professional situations, it is more common to hear the phrase “the bottom line” than the word “period.” If you were to say, “We’re not going to sell at that price, period,” there is some hostility or anger there. In a business setting, it would be better to say, “The bottom line is, we’re not going to sell at that price.” It is a more neutral expression.
Finally, “the bottom line” usually comes at the beginning of a sentence, not at the end. For example, you would say, “I’m not going, period,” but you would never say, “I’m not going, the bottom line.” That is not correct. Instead, you would say, “The bottom line is that I’m not going.” The two sentences mean the same thing, but you put “the bottom line” in the beginning and “period” at the end.
Our last question comes from Salvador (Salvador) in Mexico City, which of course is in the country of Mexico (where else could it be?). Salvador wants to know what the expression “freak on a leash” means. A “freak” (freak) is a weird or strange person, somebody who looks or acts different from most people, someone who is not normal or who doesn’t fit in. It’s not a nice word. It is an insulting term.
A “leash” (leash) is what you use to take your dog for a walk. It’s the long rope or strap that attaches to the “collar.” The “collar” (collar) is the band that goes around the dog’s neck, and the “leash” attaches to the collar and you hold on to the other end of the leash to keep your dog from running off.
So, if we put these two items together, we’d get a “freak on a leash.” This could perhaps refer to someone in the circus a long time ago when they still had “freak shows,” in which people would pay to look at people with physical abnormalities, either real or fake. But now the expression “freak on a leash” is famous for being the name of a song by the rock group Korn, (Korn). I know, “corn” is normally (corn), but this is a rock and roll band, so they can spell their name however they want.
Many people think this particular song is about the band being under a very difficult contract or agreement with their record company. The band members didn’t feel like they had freedom; they felt like they were “on a leash.” The expression “to have someone on a leash” or “to keep someone on a short leash” means to control someone who might otherwise misbehave or do something wrong or run off.
The word “freak” has other meanings, as well. As a verb, it can mean to scare someone, as in “I freaked her out.” It can also mean to panic or lose control of yourself, as in “I freaked when I found out.”
That’s all we have time for today. If you have a question or comment, don’t freak out. Email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2006 by the Center for Educational Development.
Glossary
heist – a robbery or theft involving the threat of violence; the robbing or stealing of money or valuables, or usually by threatening violence or physical harm
* The bank would have lost more than $1,000,000 if the robbers responsible for the heist had not been caught by the police.
holdup – stick up; the act of holding or pointing a gun toward someone and threatening to shoot it, forcing that person to hold his or her arms straight up in the air and to give up his or her money or valuables
* There was a holdup at the gas station down the road, and the clerk there was shot even after he gave the robber the money.
hostage – a person who is taken against his or her will or desire, who is kept by someone else for the purpose of getting something else in exchange for the captive person's return
* The family was held as hostages inside their home and the robber threatened to start killing them one by one unless the police gave him the chance to escape.
masked bandit – a thief whose face is covered and unable to be seen
* The art thief was a masked bandit and so police were unable to determine who he was even after viewing video and photos that were taken.
groceries – food and basic supplies that are purchased every week or few weeks
* After she came home from the store, Milton helped his mother remove the groceries from the trunk of the car and place them in the kitchen.
canned good – food that is packaged in a metal can so that the food stays fresher for a longer period of time
* Tyree keeps extra canned goods in his home in case of emergencies.
chain store – a store that is owned and controlled by a large company that has many stores in many locations
* When Marjorie travels to a different city, she looks for a familiar chain store to do her shopping.
to slice – to cut something, usually into a thin, flat piece; to separate or divide something into flat pieces using a knife or other sharp blade
* Debra washed and sliced the bread before giving it to her son as a snack.
butcher – a person whose job is to cut meat for sale; a person who prepares meat to sell in a business or store
* Instead of buying prepackaged meat, Neil went to the store’s butcher to select the exact type and amount of pork he wanted to buy.
farmer's market – a small store or stand, often created outdoors in a temporary location, at which a customer can buy fruits, vegetables, and other foods that are sold directly by the people who grow or make the food
* Katherine supported the local farmers by buying all her fruits and vegetables at the farmer’s market.
catch 22 – a contradiction, inconsistency, or opposing set of circumstances
* Mitch was trapped in a catch 22: he couldn’t get hired without reliable transportation, but he couldn’t afford a car without having a job to pay for it.
no longer – having been true at one point but not true now; having stopped existing after having existed in the past
* After their big fight, Thola and Rosalee were no longer talking to one another.
period – a term used to emphasize or bring focus to the fact that a thought or decision is final and not going to change
* When Issac asked Ara out on a date for the third time, she finally said, “I’m not interested in ever going out with you, period.”
freak – someone who looks or behaves in a strange way; someone who is weird, odd, or strange in some way
* The students considered Janelle a freak because she dressed in strange clothing and never spoke, but she is just awkward and shy.
leash – a rope that is attached to something, usually an animal, so that the animal can be controlled and does not run away
* Luke was kept on a tight leash by his girlfriend and she hardly ever let him spend time with his friends or relatives.
What Insiders Know
The Song “For He’s a Jolly Good Fellow”
The word “fellow” has several meanings. One way it is used is as an informal and old-fashioned term for a boy or a man. Here are a couple of examples:
- “Look at that fellow over there. He’s going swimming in that cold lake!”
- “If you fellows will excuse me, I need to leave now.”
In fact, there is a very well known song called “For He’s a Jolly Good Fellow,” sung to congratulate someone when a significant event happens, such as a “promotion” (getting a higher-level job), “retirement” (when one reaches an age where one can stop working), or winning a competition. Like the “Happy Birthday to You” song, it’s usually sung by everyone in the room “in unison” (at the same time). The “lyrics” (words) are very simple:
For he’s a jolly good fellow, for he’s a jolly good fellow
For he’s a jolly good fellow, which nobody can deny
Which nobody can deny, which nobody can deny
For he’s a jolly good fellow, for he’s a jolly good fellow
For he’s a jolly good fellow, which nobody can deny!
In this case, “jolly” means “very,” although this is an old-fashioned usage, and “to deny” is to say that something isn’t true or to refuse to admit the truth. No one would deny that the sky is blue, would they?
Although this song is meant for men/boys, it can also be sung to women, substituting “she” for “he,” of course. So the next time you have a friend with something to celebrate, perhaps you can surprise him or her with this song!