= 0106
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to another podcast with us here at EnglishPod! 
My name is Marco. +
E: And I'm Erica. +
M: And today we're gonna be looking at a very popular topic, something that everyone has 
to do at least once in their life. +
E: That's right, we're talking about mobile phones and getting amobile phone plan. +
M: Right, so, you have a mobile phone, you need to get a plan or you need to do something 
in order to… to make it work, right? +
E: Yes! And in this lesson we're going to learn some language to help you do that. +
M: Alright, so, let's start with the language on “vocabulary preview”. +
Voice: Vocabulary preview. +
E: In the dialogue we're going to compare two types of mobile phone planes – the prepaid 
plan and the monthly rate plan. +
M: Okay, so, we have two types of plans – prepaid. +
E: Prepaid plan. +
M: Okay, a prepaid plan. +
E: Well, a prepaid plan. Basically, just like the name suggests you pay before you use the 
minutes. +
M: So, maybe you have to buy a card and then you can use maybe twenty minutes or thirty 
minutes or a hundred minutes. +
E: Exactly. +
M: And then when you run out of money or you use all your minutes, you can buy another 
card and like that. +
E: Yeah, but the monthly rate plan is different. +
M: So, the monthly rate plan – you have to pay each month. +
E: Right, at the end of each month. +
M: At the end of each month. And what do you pay? +
E: Um, you pay for everything you used. +
M: You get a bill at the end of the month. +
E: Exactly. +
M: Okay, so, very interesting. These are the ways that mobile phone plans usually work. 
And, well, now it's time for us to listen to this dialogue for the first time. We are gonna be
listening as a shopper is looking to buy maybe a mobile phone or get a mobile phone plan. +
B: Yeah, I’ve just moved here, and I’d like to activate 
my cell phone, and I’m not sure if I should go with
a prepaid plan, or a monthly rate plan. +
A: I see. Well, can I have a look at your phone? Un- 
fortunately, this phone can’t be used in the US; it’s
not compatible with our 3G network. +
B: What? Really? I don’t really want to have to buy 
a new phone. +
A: Well, you’re in luck! You see, if you sign up for our 
three-year plan, we’ll throw in a handset for free. +
B: Really? What’s the catch? +
A: There’s no catch! You just choose a plan, sign a 
three-year contract and, that’s it! Actually, we’re
running a special promotion right now, and we’re
giving away a Blackberry Curve with our special
Mega Value forty dollar plan. +
B: So what does this plan include? +
A: Well, you get nine hundred anytime minutes, and 
you can also enjoy free mobile to mobile call-
ing to other Tel-Mobile clients, one thousand text
messages per month, and unlimited evening and
weekend minutes. Oh, and we also offer a rollover
option. +
B: Wow, all this for forty dollars per month? +
A: That’s right, plus the activation fee, the emer- 
gancy services fee, the monthly service fee, oh,
and any charges for extra minutes, and... +
E: Well, it sounds like a lot more than forty dollars, doesn't it? +
M: This is very common… +
E: Yeah. +
M: They always say that it's a very low price and they always have these hidden charges. +
E: Hm. +
M: Right? +
E: Yeah, you're right, so, why don't we look at some of the language, they were using in the 
dialogue, now in “language takeaway”? +
Voice: Language takeaway. +
M: Alright, on language takeaway today we're gonna be looking at four very basic words 
that are used in this whole mobile phone context. And the first one is activate. +
E: To activate my cell phone. +
M: Alright, so, you have to activate your cell phone. +
E: That's right, um, you have to make the cell phone work. +
M: So, basically, you make it work. Now, can you only apply this to mobile phones? +
E: No, there's many things that must activate to make work. For example, you must 
activate your computer software. +
M: Okay, or maybe you have to activate your credit card. +
E: Or activate your bank account. +
M: So, usually, you do this for the first time before you start using it. +
E: Yeah, like imagine your mobile phone is 'sleeping', right? +
M: Uhu. +
E: And you need to activate it to make it start working. +
M: But you only do it once. +
E: Right, only once. +
M: Okay, we talk about a mobile phone or we say the cell phone, but this also has a specific 
name, right? +
E: That's right, a handset. +
M: Handset. +
E: A handset. +
M: So, the device, the phone… +
E: Uhu. +
M: You can call it a handset. +
E: Exactly. +
M: Alright, a very easy word, but it's kind of… a little bit more technical. +
E: Yep! Now, one of the things they were talking about with this, um, monthly rate plan was 
an… was a rollover option. +
M: Rollover. +
E: A rollover option. +
M: So, what does this rollover option about? +
E: Well, okay, I'll give you an example. Um, let's say you have five hundred minutes each 
month. +
M: Uhu. +
E: And you only use four of them in this month. +
M: Uhu. +
E: One hundred of those minutes can roll over, can move over to the next month, so, now 
you have six hundred minutes. +
M: So, basically, the minutes that you don't use you can still use the following month. +
E: Right. +
M: Okay, so, that's a rollover plan. +
E: Uhu. Now, we might recognize the verb to roll over, right? +
M: Right, so, it's very similar to physically move from one place to another. +
E: Yep. +
M: Alright, rollover. And now, at the end we talked about many types of fees. +
E: That's right, activation fee. +
M: Okay, or we also had emergency services fee. +
E: Uhu. +
M: So, what is a fee? +
E: A fee is the amount of money you must pay for a service. +
M: Okay, so, this is important, it's for a service. +
E: Yeah, you can't pay a fee for something you can touch. +
M: Okay, so, if I go to the store, I don't say “What is the fee of this bottle of water?” +
E: Right. What's the fee for filling this bottle of water? +
M: Okay, so, for a service. +
E: Yes, for an action. +
M: Alright, very good! So, I think it's time for us to listen to this dialogue again. We're 
gonna slow it down, because it was a little bit fast and then we'll come back and look at
some great phrases. +
B: Yeah, I’ve just moved here, and I’d like to activate 
my cell phone, and I’m not sure if I should go with
a prepaid plan, or a monthly rate plan. +
A: I see. Well, can I have a look at your phone? Un- 
fortunately, this phone can’t be used in the US; it’s
not compatible with our 3G network. +
B: What? Really? I don’t really want to have to buy 
a new phone. +
A: Well, you’re in luck! You see, if you sign up for our 
three-year plan, we’ll throw in a handset for free. +
B: Really? What’s the catch? +
A: There’s no catch! You just choose a plan, sign a 
three-year contract and, that’s it! Actually, we’re
running a special promotion right now, and we’re
giving away a Blackberry Curve with our special
Mega Value forty dollar plan. +
B: So what does this plan include? +
A: Well, you get nine hundred anytime minutes, and 
you can also enjoy free mobile to mobile call-
ing to other Tel-Mobile clients, one thousand text
messages per month, and unlimited evening and
weekend minutes. Oh, and we also offer a rollover
option. +
B: Wow, all this for forty dollars per month? +
A: That’s right, plus the activation fee, the emer- 
gancy services fee, the monthly service fee, oh,
and any charges for extra minutes, and... +
E: Well, you know, there're some interesting, uh, phrases in this dialogue and, you know, a 
lot of them can be used when you're talking about, uh, a negotiation or a contract or a deal. +
M: Alright, great, so, let's take a look at these phrases in “fluency builder”. +
Voice: Fluency builder. +
M: Okay, the first phrase that we have on fluency builder today was the problem that she 
had with her mobile phone was that it wasn’t compatible with a 3G network. +
E: Okay, to be compatible with. +
M: To be compatible with. +
E: To be compatible with. +
M: Now, this word compatible means that it works well with something else. +
E: Exactly, now, there's a lot of things that you can use this phrasecompatible 
with together with. Um, you know, people, things. So, why don't we hear a few examples
now? +
Voice: Example one. +
A: Our application is compatible with most smartphones. +
Voice: Example two. +
B: My roommate and I are just not compatible. All she ever does is study and I like to stay 
up late and party. +
Voice: Example three. +
C: I’m sorry, your computer is not compatible with our software. It’s too old. +
M: Okay, great examples, so, compatible with, very clear and it's very useful. +
E: That's right. +
M: Now, what about the next phrase? +
E: Well, you know, the… the girl was hearing about all of these great things that are 
included in the contract and she asked what’s the catch? +
M: What's the catch? +
E: What's the catch? +
M: So, she was asking for the catch. +
E: Uhu. +
M: What is the catch? +
E: Well, good thing you asked. A catch is something negative, something that's hidden, 
um, that makes the deal seem not so great. +
M: Okay, so, if somebody offers me a new car. +
E: Yeah. +
M: They say you can have this new… for free. +
E: Okay, well, that seems too good to be true, so, what is the catch? +
M: The catch is that I can only drive it at night. +
E: Okay. +
M: So… +
E: That's kind of annoying. +
M: Right. +
E: Yeah. +
M: So, that's the catch. There's like a condition. +
E: Yep. +
M: Now, she asked about the catch and, well, sh… he said “Well, there's no catch, you 
know, it's… you just sign the contract” and then the salesman told the lady that she is in
luck. +
E: You're in luck. +
M: To be in luck. +
E: Well, okay, I think that… I think we can really understand the meaning, right? When 
you're in luck, something lucky has happened. +
M: Right, you're having good fortune. +
E: Uhu. But how do we use it? +
M: So, maybe you were looking for a very special bottle of wine for dinner tonight. +
E: Yep, it's very rare. +
M: Okay, and you're going to this little store and all of a suddenyou're in luck, you found it 
there. +
E: Exactly. +
M: Okay. +
E: This phrase is actually most commonly used in the second person, “you’re in luck”. +
M: You are in luck. +
E: Uhu. +
M: You're in luck tonight. +
E: Yeah, and it… it… usually when someone asks you for something, then you say “You're in 
luck”. +
M: You're in luck, I have it. +
E: Uhu. +
M: Or you're in luck, I have the very last one. +
E: Exactly. +
M: Alright, and now to end a fluency builder we have one more phrase and, so, it was when 
the salesman said “We'll throw in a handset for free”. +
E: Alright, to throw something in. +
M: So, if she signs the contract, he will throw in a free handset. +
E: It means to include something for free. +
M: Okay, so, you can say “If you buy this house, I'll throw in…” +
E: The dog. +
M: The dog for free. +
E: Yeah. +
M: Right? So, to throw in – to include for free. +
E: Right. +
M: Okay, alright, so, great phrases and I think we understand them now, so, let's listen to 
this dialogue for the very last time. +
B: Yeah, I’ve just moved here, and I’d like to activate 
my cell phone, and I’m not sure if I should go with
a prepaid plan, or a monthly rate plan. +
A: I see. Well, can I have a look at your phone? Un- 
fortunately, this phone can’t be used in the US; it’s
not compatible with our 3G network. +
B: What? Really? I don’t really want to have to buy 
a new phone. +
A: Well, you’re in luck! You see, if you sign up for our 
three-year plan, we’ll throw in a handset for free. +
B: Really? What’s the catch? +
A: There’s no catch! You just choose a plan, sign a 
three-year contract and, that’s it! Actually, we’re
running a special promotion right now, and we’re
giving away a Blackberry Curve with our special
Mega Value forty dollar plan. +
B: So what does this plan include? +
A: Well, you get nine hundred anytime minutes, and 
you can also enjoy free mobile to mobile call-
ing to other Tel-Mobile clients, one thousand text
messages per month, and unlimited evening and
weekend minutes. Oh, and we also offer a rollover
option. +
B: Wow, all this for forty dollars per month? +
A: That’s right, plus the activation fee, the emer- 
gancy services fee, the monthly service fee, oh,
and any charges for extra minutes, and... +
M: Mobile phones, this is very common in the United States, right, these monthly plans. +
E: Yeah, most places where I have lived it's much more common to pay as you go, right, to 
have a p… a prepaid plan. +
M: Uhu. +
E: But in the States, um, almost everyone goes with a monthly plan. +
M: Maybe it's because in order to have a monthly plan you need to have a credit card. +
E: You might be on to something. +
M: Right? +
E: Yeah. +
M: So, if you don't have a credit card or maybe you're eighteen… +
E: Yeah. +
M: You can't get a monthly plan, so, you gotta do this prepaid plan. +
E: Yeah, you know, another interesting thing that I've noticed when, um, living in different 
countries and seeing mobile phone habits, um, Americans and North Americans respond
very differently to a ringing mobile phone than other people do. +
M: How so? +
E: Um, for example, if I was in a meeting in America and my phone rang and I answered it, 
people might think that I was very rude to answer the phone in a meeting. +
M: Uhu. +
E: But, you know, here, when we're living in China, it's totally normal, it's… you know, 
everyone does it. That's… +
M: Uhu. +
E: That's the polite thing to do - answer your phone. +
M: Right, I un… I think that's absolutely true and maybe it's because in North America you 
have this voice mail option for your mobile phone. +
E: Yeah, and everyone has it. +
M: Everyone has it. +
E: Yeah. +
M: So, if it's something very important, then the person will leave you a voice mail message 
and then you will know what it's about or you can call them back. +
E: Uhu. +
M: But here I guess or in other countries maybe they don't have that option, so, they need 
to answer every call. +
E: Yeah, it's… it's interesting… an interesting sort of cultural difference in the way we use 
our phones, but what about listeners? In your country do you answer the phone
immediately or do you let it ring? +
M: Right, or maybe do you see who's calling and maybe just not answer it? +
E: Yeah, and screen your calls. +
M: To screen a call. +
E: Yeah. +
M: So, come to our website englishpod.com, let us know what your, uh, mobile phone 
habits are and also if you have any questions or doubts. +
E: Yep, Marco and I are always there to answer your questions, so, until next time, thanks 
for listening and… Good bye! +
M: Bye! 

  
