= 0108
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to another great podcast here at EnglishPod! My 
name is Marco. +
E: And I’m Erica. +
M: And today we’re gonna be bringing you bad news. +
E: That’s right, um, actually, what we’re really gonna be bringing you is language to talk 
about bad news. +
M: Exactly, so, maybe you have to give bad news to your boss, to your parents, I don’t 
know, somebody and we’re gonna be teaching you how to do this in English. +
E: Well, obviously, it’s always difficult to tell somebody bad news, but in your second 
language it’s even harder, so, we’re gonna try and help you today with some great phrases
and vocabulary items. +
M: We’re not gonna preview anything today, let’s go directly to our dialogue where we will 
be in a company and one of the employees is gonna be giving bad news to his boss, so, let’s
listen. +
A: ... Now that we have been over the gory details 
of our disastrous first quarter, Ed! Give us some
good news. How are things looking for us in terms
of sales this month? +
B: Uh well...would you like the bad news first or the 
really bad news? +
A: What? Ed, don’t tell me you only have bad news! +
B: Well sir, our sales have dropped, no plunged, fifty 
percent in the past month alone. We are currently
overstocked and overstaffed and our profits are
falling fast. The market is in recession and we
have no way of moving our inventory, or getting
rid of our staff. If we consider redundancies, it
would cost us a fortune because of the new reg-
ulations governing compensation packages. It’s a
real mess. +
A: For crying out loud... How fast are we losing 
money? +
B: Um...how can I put this? Let’s just say that at this 
pace, we will be filing for Chapter eleven in less
than three months. +
A: What! Geez! How could this have happened? So 
what’s the bad news? +
B: Oh, that’s the really bad news. Our supplier suf- 
fered QC problems and, well, half of our produc-
tion is faulty. We’re going to have to recall all items
sold in the last quarter. And the worst part? We’re
going to have to shoulder this cost. +
A: Are you joking? Get the supplier on the line now! 
They have to assume the costs of this mess! +
B: We tried that, sir. The factory has gone under and 
the owner apparently has fled the country. +
A: We’re doomed! +
B: There is some really good news though! +
A: Really? What! +
B: I got offered a new job! +
E: Alright, it sounds like a pretty tough time for this, uh… this company, doesn’t it? +
M: But good news for the employee, he won’t be, uh, jobless. +
E: Well, I guess he knows when to get out. +
M: Hehe. +
E: But why don’t we take a look at some of the language now in “language takeaway”? +
Voice: Language takeaway. +
M: So, on language takeaway today we have five vocabulary items and, well, let’s start with 
the first one. +
E: Alright, so, the… the boss, uh, you know, he… he’s talking about “the gory details of our 
disastrous first quarter”. So, let’s look at the phrase gory details. +
M: Alright, so, gory details. +
E: Gory details. +
M: This sounds kind of strange – gory details – it seems very scary. +
E: Well, the word gory comes from gore like blood-and-guts, right? +
M: Exactly, that’s why it sounds a little bit scary to me. +
E: Yep, so, gory details, um, mean all the little, um, details of a… of a negative or shocking 
or bad situation. +
M: Okay, so, the gory details of the meeting, so… +
E: Uhu. +
M: All the nasty… +
E: Yeah. +
M: Negative stuff. +
E: All the gory details… or you could say “The newspaper reported all the gory details of the 
murder”. +
M: Okay, very good, so, gory details. +
E: Uhu. +
M: So, the employee was talking about how bad the company was doing and he mentioned 
this word redundancies. +
E: Redundancies. +
M: They’re considering redundancies. +
E: Okay, so, redundancies again, it’s based on the word to beredundant. +
M: Alright, and that means… +
E: To not be needed anymore. +
M: Okay, so, redundancies are basically firing people. +
E: It’s, well, laying people off. People that you don’t need anymore, they are redundancies. +
M: Alright, so, this is actually a British term – redundancies, to become redundant, because 
in American English we would just say layoffs. +
E: Yep. +
M: Okay, very good. +
E: Alright, so, moving on, uh, they were talking about redundancies and maybe they should 
or shouldn’t lay some people off, but one of the problems were the regulations governing
compensation packages. +
M: Okay, so, regulations governing compensation packages. +
E: Regulations governing something. +
M: So, we have a noun governing noun. +
E: Uhu. +
M: What does that mean? +
E: Alright, so, I think it would help us to understand this a little better if we listen to some 
examples of this pattern - noun governing noun. +
Voice: Example one. +
A: I don’t agree with the regulations governing income taxes. People shouldn’t have to give 
away their hard earned money. +
Voice: Example two. +
B: We need to protect the environment, therefore there will be new policies governing 
corporate levels of pollutions starting next month. +
Voice: Example three. +
C: The lack of regulations governing city transportation has led to many traffic accidents. +
M: Okay, great examples and, well, before we move on, thiscompensation packages, I 
guess it’s all the things that the company gives you when you f… when they lay you off,
right? +
E: Right, maybe, um, a certain portion of your, uh, retirement benefits or… +
M: And like a month pay. +
E: Yeah. +
M: Et cetera. +
E: Yeah. +
M: Okay, compensation packages. Alright, so, moving on to our next item on language 
takeaway we have to shoulder the cost. +
E: To shoulder the cost. +
M: Alright, so, if I shoulder something… +
E: You have to carry it. +
M: I carry it. +
E: Yeah. +
M: Uh, that’s a good one. +
E: Uhu. +
M: So, basically, it’s the same as your… the shoulder, your body. +
E: Yeah. +
M: So, you carry this cost or you carry this responsibility. +
E: Yep, um, so you might also hear shoulder the burden. +
M: To shoulder the burden. +
E: Yeah, so, it just mean[s]… to carry the responsibility. +
M: Okay, to share it. +
E: Yeah. +
M: Alright, interesting. And we have one more word on language takeaway and the factory 
has gone under. +
E: To go under. +
M: Alright, to go under. +
E: When something goes under, uh, a company goes under, it goes bankrupt. +
M: It goes bankrupt, so… +
E: Uhu. +
M: It’s not working anymore. +
E: That’s right. +
M: Alright, so, to go under. Great vocabulary items here on language takeaway today. It’s 
time for us to move on to the next segment of our show where we’re gonna look at some
phrases, so, let’s start now with “fluency builder”. +
Voice: Fluency builder. +
E: Alright, so, we’ve got some phrases that you can use, uh, when somebody’s going to tell 
you some bad news, but also some phrases you can use to deliver bad news. +
M: Alright, so, let’s start with our first phrase. +
E: So, the… you know, the boss is getting ready to prepare for this bad news and he 
says lay it on me. +
M: He’s like “Okay, lay it on me!” +
E: Lay it on me. +
M: So, if I say this “Lay it on me”, I’m just saying “Tell me”. +
E: Exactly. +
M: So, give me the bad news. +
E: Uhu. +
M: Alright, so, lay it on me. Very informal, though. +
E: Yeah, you’re right, it is kind of informal. But our next phrase, um… you know, the… the 
boss is hearing about all these bad news and he says for crying out loud. +
M: For crying out loud. +
E: For crying out loud. +
M: Alright, so, this is a very common phrase of… of frustration. +
E: Yep. +
M: Right? So, why don’t we listen to some examples to kind of understand how we use this 
phrase? +
Voice: Example one. +
A: For crying out loud, when I tell you to have the report done by Wednesday that means I 
expect it to be on my desk by the end of the day. +
Voice: Example two. +
B: We’ve got to figure out a new marketing strategy, for crying out loud. +
Voice: Example three. +
C: For crying out loud, you just got your driving license and you already got in an accident? +
E: So, it kind of reminds me of “Oh, my God!” +
M: So, you’re frustrated, you’re just saying this phrase as “Oh, my God!” or something like 
this. +
E: Yeah, it… yeah, it’s like “Huh! This is so annoying!” +
M: Exactly, for crying out loud. +
E: Yep. +
M: Alright, moving on to our third phrase – how can I put this? +
E: How can I put this? +
M: So, the boss asked him a direct question and he said “Well, how can I put this?” +
E: So, we use this phrase when we wanna say something maybe a little bit… more 
indirectly. +
M: Right, so, you’re looking for words of how you can make it softer or… +
E: Uhu. +
M: More polite. +
E: Yeah. +
M: Maybe the truth or what you’re about to say is a little bit strong, so, you wanna soften 
it up a bit. +
E: Yeah. +
M: Okay, so, you say “Uh, how can I put this?”, but then you have to complement it 
with let’s just say that. +
E: Let’s just say that. +
M: Let’s just say that. +
E: So, how do we use this phrase? +
M: So, for example, somebody asks me “Wha… what do you mean? Why can’t you come on 
vacation with us?” +
E: Uhu. +
M: And I would say “Mm, how can I put this? Let’s just say that, uh, in nine month you will 
hear the pitter patter of little feet”. +
E: Okay, so, your girlfriend’s pregnant. +
M: Exactly, so, you’re trying… you’re not saying “My girlfriend is pregnant” +
E: You… you’re giving like a metaphor. +
M: A metaphor… +
E: Yeah. +
M: Of what’s going on, but you don’t wanna say it directly. +
E: Yeah. +
M: Right? +
E: Another example, I might say, um, “Let’s just say that Michael isn’t doing a great job”. +
M: Alright, so, maybe there’re very strong reasons or he’s doing very very poorly. +
E: Right, but I’m… I’m just sort of not saying it exactly directly that he’s doing bad. +
M: Okay, very good, so, it’s a phrase that you can actually use a lot. +
E: Uhu. +
M: And to be a little bit more polite or a little bit more indirect when you’re giving somebody 
some bad news. +
E: Exactly, two, uh… two nice sort of complementing phrases for delivering bad news and 
why don’t we hear them one more time in the dialogue? +
A: ... Now that we have been over the gory details 
of our disastrous first quarter, Ed! Give us some
good news. How are things looking for us in terms
of sales this month? +
B: Uh well...would you like the bad news first or the 
really bad news? +
A: What? Ed, don’t tell me you only have bad news! +
B: Well sir, our sales have dropped, no plunged, fifty 
percent in the past month alone. We are currently
overstocked and overstaffed and our profits are
falling fast. The market is in recession and we
have no way of moving our inventory, or getting
rid of our staff. If we consider redundancies, it
would cost us a fortune because of the new reg-
ulations governing compensation packages. It’s a
real mess. +
A: For crying out loud... How fast are we losing 
money? +
B: Um...how can I put this? Let’s just say that at this 
pace, we will be filing for Chapter eleven in less
than three months. +
A: What! Geez! How could this have happened? So 
what’s the bad news? +
B: Oh, that’s the really bad news. Our supplier suf- 
fered QC problems and, well, half of our produc-
tion is faulty. We’re going to have to recall all items
sold in the last quarter. And the worst part? We’re
going to have to shoulder this cost. +
A: Are you joking? Get the supplier on the line now! 
They have to assume the costs of this mess! +
B: We tried that, sir. The factory has gone under and 
the owner apparently has fled the country. +
A: We’re doomed! +
B: There is some really good news though! +
A: Really? What! +
B: I got offered a new job! +
M: Alright, great, so, this topic of filing for Chapter Eleven (11) is actually very recent, very 
common now, because recently one of the biggest companies filed for Chapter 11 in the
U.S. +
E: Yeah, that’s right, um, but I often get confused by the phrase to file for 
Chapter Eleven versus to file for Chapter Thirteen (13). +
M: Alright, so, in the United States the bankruptcy law has different chapters or different 
sections, right? +
E: Yep. +
M: And Chapter 11 is basically for companies that run out of money, that go bankrupt, so, 
they have to declare themselves in bankruptcy… +
E: Yep. +
M: And, so, they file for Chapter 11. +
E: But what about Chapter 13? +
M: Chapter 13 is for people. +
E: Uh, okay. +
M: So, people who have large debts maybe with the car company or the telephone company 
and they can’t pay, they file for Chapter 13, they say “Hey, I don’t have money, I can’t pay” +
E: Alright, and it’s… so, I guess here it’s s… kind of a, uh… a metaphor again. You know, 
it’s… this… this phrase to file for Chapter 11 or Chapter 13 meaning bankruptcy. +
M: Right. +
E: And… and people will say personally that they… they’re filing for Chapter 11. +
M: Exactly. +
E: Yeah. +
M: Right, so, this is an interesting situation, because if you file for bankruptcy in some 
countries you can go to jail. +
E: Oh, I read recently about this happening in Dubai actually. +
M: Exactly, so… +
E: Yeah. +
M: There is prison for debts. In the U.S. you don’t go to… to prison for debts. +
E: Mm, but what about, uh… what about in your countries listeners? What happens when 
you go into debt in your country? +
M: Or what happens when a company goes into bankruptcy? +
E: Uhu. +
M: Let us know, come to our website englishpod.com, leave your questions and comments 
and, of course, Erica and I are always there to help you out. +
E: Thanks for downloading you guys and until next time… Good bye! +
M: Bye! 

 
