= 0123
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


** +
M: Hello everyone! Welcome back to another podcast here atEnglishPod! My name 
is Marco. +
E: And I’m Erica. +
M: And today we’re looking at another one of our lessons for English of the past decades 
and this time it’s the nineteen nineties (1990’s). +
E: Well, you know, the 1990’s is a little easier for most of us to remember. +
M: Yeah, I guess it’s a little bit more recent. We’re gonna be looking at a lot of language 
that is still used today. Most of these words and phrases are still used today, so, um,
they’re gonna be very useful and you’re gonna sound a lot more native. +
E: Uhu, a lot cooler as well, huh? +
M: Right, so, before we get started with this lesson, why don’t we take a look at 
“vocabulary preview”? +
Voice: Vocabulary preview. +
E: We have two words we’re going to hear in the dialogue. Now, the first one is a mall. +
M: A mall. +
E: M-A-L-L, mall. +
M: Alright, so, a mall is basically short for shopping mall. +
E: Uhu, and a shopping mall is a big building with many stores inside. +
M: Right, so, it’s like a shopping centre. +
E: Uhu. +
M: And our last word for vocabulary preview is gang. +
E: The gang. +
M: The gang. +
E: Okay, so, a gang is a group of people, right? +
M: Yeah, it’s a group of people; you can call your friends the gang. We’re gonna go 
out with the gang tonight. +
E: Yeah. Now, we sometimes hear this word, um, to have… and it has a negative meaning, 
right? +
M: Right, like street gangs. +
E: Yeah, so, people who are… who fight and deal drugs and all that sort of stuff. +
M: Right, so, it can have a negative and a positive meaning, so… but it just depends on how 
you use it. +
E: Yeah, but in the dialogue we’ll hear it with a positive meaning. +
M: Right, so, that’s all the words we have for vocabulary preview; let’s listen to this cool 
and hip dialogue from the 1990’s and we’ll come back later and explain some words. +
A: Hey four-eyes! What’s up man, how have you 
been? +
B: Not bad, just went to the mall and picked up some 
junk. Check out my new Adidas! +
A: Those are dope! You are gonna be getting mad 
props from the gang, man. Anyways, have you
seen Betty lately? +
B: Dude, don’t even go there. That girl started trip- 
pin’ cuz I went to the movies with Veronica the
other day. I was like ”look, you knew how I was
before you got with me”. +
A: That’s right! Your such a playa, man. Dude, 
there’s Mad Max. Let’s go say hi. +
B: Max! Whassup! Are you okay? You look like you 
just saw a ghost. +
C: I got an F in English class. My life is over... +
A: Dude, get over it! You need to lay off the books 
for a while and have some fun! Come on, let’s
bounce. +
C: Where are we going? Oh, crap. My dad is gonna 
go postal when he finds out about this. +
A: I’m gonna open a can of whopass on you if you 
don’t come with me now! +
C: Okay, okay. Geez... +
E: Well, it sounds like this guy has got some problems at school, huh? +
M: Yeah, he got an F on his paper, but you always can count on your friends to try 
and cheer you up by doing something. +
E: Yeah, but they used some really great phrases and vocabulary words, so why don’t we 
look at those now in “language takeaway”? +
Voice: Language takeaway. +
M: Alright, on language takeaway we’re gonna be looking at five words. And, well, let’s start 
with the first one. +
E: So, the guy was talking about his really cool new shoes, his new Adidas, right? +
M: Uhu. +
E: And his friend said “Those are dope”. +
M: Dope. +
E: Dope. +
M: Okay, so, it’s pretty easy to understand when something is dope. +
E: It’s really awesome. +
M: It’s cool. +
E: Yeah, it’s great. +
M: Right, it’s great, so, that’s dope. +
E: Uhu, and it’s an adjective, right? +
M: Uhu. +
E: So, his friend said “Those are dope” and he said “You’re goona be getting mad 
props from the gang”. +
M: Okay, so, mad props. +
E: Mad props. +
M: We can divide this word in two. So, let’s take a look at the first part – mad. +
E: Mad. +
M: So, we understand that mad is angry, right? +
E: Yeah, but it can also mean “a lot”, right? +
M: Or like “amazing”. +
E: Or “really”. +
M: So, if I say “You have mad skills”. +
E: You’re really good at something. +
M: Uhu. +
E: Or you can say “She has a mad amount of shoes”. +
M: Alright, so, he’s going to get mad props. Now, props is like respect or compliments. +
E: Yeah, so… so his shoes are so cool that he’s gonna get a lot of respect or a lot of 
compliments from his friends. +
M: Exactly, mad props. +
E: Mad props. +
M: So, they started taking about girls and he mentioned that this girl started trippin’. +
E: Trippin’. +
M: Trippin’. +
E: So, to trip. +
M: Right, as you notice it’s trippin’. It doesn’t have the G at the end, which isn’t really 
grammatically correct, but that’s kind of the way it’s pronounced. +
E: Yeah, we… we would never say the G. +
M: Right, so if somebody is trippin’… +
E: They’re, um… they’re getting really upset; they’re getting really angry. +
M: Right, they’re causing trouble. +
E: Uhu. +
M: So, why don’t we listen to a couple of examples of how we could use trippin’ for 
different situations? +
Voice: Example one. +
A: Leanne was trippin’, cause I got dirt on her car. +
Voice: Example two. +
B: Even though I apologized for calling her fat, Jenny was trippin’ all night. +
Voice: Example three. +
C: He sent me forty three text messages and called me about twenty times. That guy is 
trippin’ over me! +
E: Okay, so, that’s pretty clear, um, trippin’. +
M: Alright. Now, moving on to our next word, ah, they wanted to go somewhere and he said 
“Come on, let’s bounce”. +
E: Let’s bounce. +
M: Let’s bounce. +
E: I’m gonna bounce. +
M: Now, uh, bounce basically means “Let’s leave”. +
E: Yeah. +
M: Let’s get out of here. +
E: But we might be more familiar with this… this word as in like a ball, right? A 
ball bounces off the floor. +
M: Exactly, so, I guess it’s kind of the same you can have bounced off the floor and leave 
that place. +
E: Yeah. +
M: Let’s bounce. +
E: Okay, so, for a final word, now, this guy who got a bad mark on his… his paper, he was 
nervous about what his dad would say, right? +
M: Right. +
E: Cause his dad was going to go postal. +
M: Uhu, he said “My dad is gonna go postal”. +
E: To go postal. +
M: Now, if you go postal, it means you go crazy. +
E: Yeah, you really freak out. +
M: You go r… you get vey angry. +
E: Yeah, like REALLY angry. +
M: This word comes from the nineties, because during that time it was very common in the 
United States that post workers, mailmen… +
E: Uhu. +
M: Were going a little bit, uh, crazy and, you know, they started shooting people and, uh, 
delivering some strange packages. +
E: Well, I guess so people who work in, uh, the post office maybe don’t have the most 
exciting jobs and that drives them a little crazy. +
M: Exactly, and that’s why… but now they have a… a term named after them. Alright, so, 
why don’t we listen to our dialogue for the second time? We’re gonna slow it down a little
bit and then we’ll come back. +
A: Hey four-eyes! What’s up man, how have you 
been? +
B: Not bad, just went to the mall and picked up some 
junk. Check out my new Adidas! +
A: Those are dope! You are gonna be getting mad 
props from the gang, man. Anyways, have you
seen Betty lately? +
B: Dude, don’t even go there. That girl started trip- 
pin’ cuz I went to the movies with Veronica the
other day. I was like ”look, you knew how I was
before you got with me”. +
A: That’s right! Your such a playa, man. Dude, 
there’s Mad Max. Let’s go say hi. +
B: Max! Whassup! Are you okay? You look like you 
just saw a ghost. +
C: I got an F in English class. My life is over... +
A: Dude, get over it! You need to lay off the books 
for a while and have some fun! Come on, let’s
bounce. +
C: Where are we going? Oh, crap. My dad is gonna 
go postal when he finds out about this. +
A: I’m gonna open a can of whopass on you if you 
don’t come with me now! +
C: Okay, okay. Geez... +
E: Okay, so, I think that was a little easier to understand, you know, we’ve got a lot of 
pretty strange words and phrases, some interesting slang. +
M: Yeah, and I wanna take a look at this slang now, so let’s get started with “fluency 
builder”. +
Voice: Fluency builder. +
E: Okay, so, the guy with the new shoes, he asked his friend “Have you seen Betty lately?”, 
right? +
M: Right. +
E: And the… his friend replied don’t even go there. +
M: Right, he was like “Dude, don’t even go there”. +
E: Don’t even go there. +
M: So, what does he mean when he says don’t even go there? +
E: He means don’t talk about it, I don’t wanna talk about it. +
M: Right, don’t even touch that subject. +
E: Don’t even mention it. +
M: Right, so, if somebody wants to talk about a topic that you think is sensitive or you don’t 
wanna talk about, so say “Hey, don’t… don’t even go there”. +
E: So, Marco, what do you think about the new tax law? +
M: Uh, don’t even go there, I don’t even wanna talk about politics. +
E: Okay, so, I think that’s… that’s a really actually quite helpful phrase, um, to avoid talking 
about an uncomfortable subject. +
M: Right. So, he said “Don’t even go there” and he started talking about the girl and she 
was trippin’ and then he said something interesting. He said I was like “Look, you knew
how I was before you got with me”. +
E: Yeah, I really like this phrase. Now, I wanna focus on the first part – I was like. +
M: I was like. +
E: I was like. +
M: Now, you might hear a lot of native English speakers use these three words before they 
start telling you what they said. +
E: Uhu. +
M: So, it’s like saying “I sad” or “I told him”. +
E: Yep, so, this actually is really common, especially with people under the age of thirty. +
M: Hehe. +
E: So, why don’t we hear a few more examples of how it’s used now? +
Voice: Example one. +
A: This guy caused the car accident and I was like “You idiot! You can kill people by driving 
like that!” +
Voice: Example two. +
B: And then I was like “I hate you!” and she was all like “I hate you more!” +
Voice: Example three. +
C: I told the teacher that I didn’t finish my homework and he was like “I’ll see you after 
school”. +
M: So, if you’re telling a story or you’re maybe talking to somebody and you wanna explain 
what you said, you can say “I was like “hey, what’re you doing?” and she was like “what?”,
so, you can have a… +
E: Yeah. +
M: An entire dialogue based with I was like, she was like, we were like. +
E: Aha. Okay, so, I was like. It’s super, super useful. So, now, our next word. Now, they 
saw their friend who got the bad the mark in school and the guy said “Dude, get over it”. +
M: Get over it. +
E: Get over it. +
M: So, if somebody tells you to get over it… +
E: Stop worrying about it. +
M: Okay, or… +
E: Stop thinking about it. +
M: Alright, so, if somebody is sad, because maybe his girlfriend broke up with him, you 
would say… +
E: Get over it! +
M: Yeah, stop thinking about it. +
E: Yeah. +
M: Let it go. +
E: Yeah. +
M: It’s in the past. +
E: Yeah, and you… you commonly use this for, um, when somebody is upset about a small 
thing, something they shouldn’t worry about. +
M: Uhu, get over it. +
E: Yeah, now, why don’t we go on to our final word? At the end of the dialogue they 
said I’m gonna open a can of whoopass. +
M: Okay, so, to open a can of whoopass on somebody. +
E: To open a can of whoopass. +
M: So, again, let’s break this down before we’ll explain it. +
E: Okay, I think we have to take one step back here. To whoop someone’s ass is to 
beat them up, right? +
M: Right. +
E: To punch them and hurt them. +
M: Right, so, to whoop somebody’s ass. +
E: Uhu. +
M: So, if I open a can of whoopass, what does that mean? +
E: It means you’re gonna beat them up. +
M: So, it’s just a funny, very informal way of saying like “In this can… I’m gonna open it and 
I’m gonna start hitting you” or something like that. +
E: Some sort of small man is gonna jump out of the can and start hitting you. +
M: Exactly, but it’s never literal. It’s not like you’re actually gonna beat somebody up. It’s 
just kind of like in… +
E: It’s kind of a joke. +
M: Yeah. +
E: Yeah. +
M: It’s an empty threat. +
E: Yeah. +
M: Alright, so, some really interesting words and phrases in this dialogue. I think we should 
listen to it for the last time and then we’ll come back and talk a little bit more about this
great decade. +
A: Hey four-eyes! What’s up man, how have you 
been? +
B: Not bad, just went to the mall and picked up some 
junk. Check out my new Adidas! +
A: Those are dope! You are gonna be getting mad 
props from the gang, man. Anyways, have you
seen Betty lately? +
B: Dude, don’t even go there. That girl started trip- 
pin’ cuz I went to the movies with Veronica the
other day. I was like ”look, you knew how I was
before you got with me”. +
A: That’s right! Your such a playa, man. Dude, 
there’s Mad Max. Let’s go say hi. +
B: Max! Whassup! Are you okay? You look like you 
just saw a ghost. +
C: I got an F in English class. My life is over... +
A: Dude, get over it! You need to lay off the books 
for a while and have some fun! Come on, let’s
bounce. +
C: Where are we going? Oh, crap. My dad is gonna 
go postal when he finds out about this. +
A: I’m gonna open a can of whopass on you if you 
don’t come with me now! +
C: Okay, okay. Geez... +
E: Well, Marco, in the dialogue I heard one of the guys say “What’s up!”, but he said it in a 
really strange way, didn’t he? +
M: Yeah, exactly, he said wassup! +
E: Okay, so, what… what’s up with that? +
M: So, in the nineties it was popular instead of saying “What’s up” you would just kind of 
double the S and just say “Wassup”. And then it became very famous with a TV commercial
for a certain beer. +
E: And actually I remember this commercial. During the… the Super Bowl they had, um, this 
big commercial where everyone was saying “What’s up” in this really strange way, right? +
M: It’s still used today. Informally between friends you’ll go ahead“Hey! Wassup!” and then 
“Wassup!” +
E: Yean, and… +
M: So, you’ll use it. +
E: Yeah, so, that commercial made it actually quite cool and famous to talk like that. +
M: Actually, in SpanishPod they have a show called Que Pasa, which is like the translation 
of “what’s up” and… +
E: Alright. +
M: They start each show with like saying “Que pasa!” But it’s exactly the same, so, maybe it 
will become popular in Spanish. +
E: Maybe, but I guess only, uh… +
M: Time will tell. +
E: Yeah, that’s right. +
M: Alright, so, really cool stuff and as we heard typical music from the nineties and another 
interesting thing was the nicknames: four-eyes,Mad Max, very popular among young kids. +
E: Uhu. So, remember if you have any questions about this language or anything else about 
this lesson, come to our website atenglishpod.com. +
M: Right, you can leave all your questions and comments there and, uh, we hope to see you 
guys there. +
E: So, thanks for listening and until next time… Good bye! +
M: Bye! 
  
