= 0126
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello English learners! Welcome back to EnglishPod! My name isMarco. +
E: And I’m Erica. +
M: And today we’re gonna have a fun… funny lesson. +
E: That’s right. So, I think this lesson’s gonna be a little bit different than most of our 
lessons, right? +
M: Right, today we’re gonna be looking at jokes, which is a very important part of English 
speaking culture. +
E: Yeah, so, we’re actually… we’re gonna teach you a few, um, prettyhilarious jokes. +
M: Hehe. +
E: But we’re also gonna teach you some language related to jokes, funny things and, um, 
that sort of stuff. +
M: Alright, so, in order for us to understand a little bit better the jokes that we’re gonna be 
looking at, why don’t we take a look at “vocabulary preview”? +
Voice: Vocabulary preview. +
E: Two of these words you’ll hear in the dialogue, but one you won’t, but you still need to 
know this word, so you can understand the jokes. +
M: Alright, so, the word that we’re talking about is not really a word, it’s a sound. +
E: Yeah. +
M: Moo. +
E: Moo. +
M: So, moo is the sound that cows make. +
E: That’s right, M-O-O. +
M: Right, they go “moooo”. +
E: Very nice, Marco. +
M: Uh, I could do a good cow. +
E: Yep. Alright, so, we all know now that that’s what cows say. +
M: Exactly, so, it’s gonna be important for the joke and you’ll see why. +
E: Okay, now, another word that you need to understand is a dam. +
M: So, a dam. +
E: A dam. +
M: A dam is, uh, is… is like a big wall, right? +
E: Well, it’s a wall in water that stops the river from flowing. +
M: Okay, so, usually they’ll build dams in rivers and then the water can pass or not. +
E: Yeah, it’s something that you use to generate electricity, right? +
M: Very good, but there’s another word that sounds exactly the same way, but it’s just 
spelled a little differently. +
E: That’s right and… and we might hear someone say “Oh, damn!” +
M: And that’s an interjection which basically means… +
E: “Oh, no!” +
M: Right. +
E: “That’s terrible!” +
M: Aha. +
E: Yeah. +
M: Damn… I can say “Damn, I forgot my keys”. +
E: Uhu. “Damn, we’re late for the movie”. +
M: Okay, so, it’s an interesting interjection and we’ll also see it in one of our jokes. And 
now, let’s move on to our last word. +
E: Nostrils. +
M: Okay, nostrils. +
E: Nostrils. +
M: So, a nostril or your nostrils… +
E: Are the two holes in your nose. +
M: Right, you breathe through your nostrils. +
E: Uhu. +
M: Alright, so, now that we’ve taken a look at these three words, why don’t we listen to our 
comedian for the first time and then we’ll come back and talk a little bit more. +
Announcer:Hello everyone, and welcome to open mic night! 
You’re in for a real treat as we’ve got a lot of great
comics here with us tonight. First up, we have a
very funny man coming straight from the state of
Montana, Robert Hicks! +
A: Thank you, everyone! Well, what a lovely crowd. 
You know, there’s nothing I love better than stand-
up comedy! You know, I’ve been working on my
routine for months now, and I’ve got some real
zingers for you tonight. Let’s start out with some
short jokes, how bout that? Where do you find a
one legged dog? Where you left it. +
A: Get it? mmm Anyways... What do you call a 
sheep with no legs? A cloud ! +
A: Tough crowd... Alright, now you’re going to love 
this joke. It’s hilarious! What do cows do for en-
tertainment? They rent moooovies ! moooovies +
A: Okay, Okay, we’ve got a few hecklers in the audi- 
ence, but this one is good! What does a fish say
when it runs into a wall? DAM! +
A: Okay, Last one! Why do gorillas have big nostrils? 
Coz they got big fingers!!!!!!!!! +
Crowd:Get off the stage! You suck! +
A: Thanks everyone that was my time. +
E: Okay, so, some pretty hilarious jokes, huh? +
M: I don’t think the crowd really enjoyed them all that much. +
E: Okay, well, maybe, um, I’m just a fan of really terrible jokes. +
M: Hehe. Well, they were pretty funny, but I guess the crowd just didn’t appreciate his, uh, 
sense of humor. +
E: But you know what, they did use quite a lot of really interesting language, so why don’t 
we look at that now in “language takeaway”? +
Voice: Language takeaway. +
M: On language takeaway we’re gonna be looking at six words today, so let’s get started. 
The announcer welcomed everyone and said that, uh, it’s open mic night. +
E: Open mic night. +
M: So, an open mic night. +
E: Okay, well, we know mic is short for microphone, right? +
M: Uhu. +
E: Now, an open mic night is a chance for anyone can come up and talk into the 
microphone. +
M: So, you can come up and sing or you can tell jokes, you can do anything, basically. +
E: Yep. +
M: Alright, open mic night. +
E: So, it’s not for professionals, but for people who maybe want to be professionals. +
M: Right, amateurs. +
E: Uhu. +
M: So, it was open mic night and he said they had a lot of greatcomics there. +
E: So, comics. +
M: A comic. +
E: A comic. +
M: So, basically, a comic is a person… +
E: Uhu. +
M: That makes a living by making people laugh. +
E: Yeah, someone who… who stands up on stage and tells jokes. +
M: Alright, would you say a clown is kind of like a comic? +
E: No, they’re different. +
M: They’re different, right? +
E: A… a comic doesn’t wear a red nose and a crazy… +
M: A costume. +
E: Yeah. +
M: Alright, yeah, cause I hate clowns! Hehe. +
E: We do know that about you. +
M: Alright, so, a comic. And, well, what comics do is they performstand-up comedy. +
E: Stand-up comedy. +
M: Stand-up comedy. +
E: Okay, so, stand-up comedy is… is really exactly what its name suggests, right? +
M: Right, you stand up in front of, uh… an audience and you tell jokes and… or you make 
them laugh. +
E: Yeah, tell funny stories. +
M: It’s a very popular form of entertainment in the United States and the UK. +
E: That’s right, um, and I think we’ll talk a little bit more about that at the end of the 
lesson. But why don’t we move on to our next word which is routine. +
M: A routine. +
E: So, the guy says “I’ve been working on my routine”. +
M: So, what does he mean by his routine? +
E: Well, I guess a… a routine is like a series or a collection of jokes or maybe movements 
that you use in a performance. +
M: Alright, a routine. +
E: So, you can talk about a dance routine. +
M: Or in this case a comedy routine. +
E: Uhu. +
M: So, the series of jokes he’s gonna tell. +
E: That’s right, that he practices again and again and again. +
M: Alright, and in his routine he said he’s got a lot of zingers. +
E: Zingers. +
M: A zinger. +
E: So, what’s a zinger? +
M: Basically, a zinger is like a strong, maybe a little bit rude joke. +
E: Yeah, but like, uh, kind of a one line joke, right? +
M: Right, exactly. +
E: Yeah. +
M: And the people that were in the crowd and they were booing him, they were like “Boo”. +
E: Mm. +
M: Those we call hecklers. +
E: Exactly and that’s our last word – a heckler. +
M: A heckler. +
E: Hecklers. +
M: So, let’s listen to some hecklers in action. 
The sound of booing hecklers. +
E: Alright, well, I think that’s pretty clear. Those are definitely hecklers. +
M: Right, they’re very annoying. +
E: Uhu. +
M: So, now that we finished looking at all the words that are related to comedy and 
performances, let’s, uh, take a look at the jokes now in “fluency builder”. +
Voice: Fluency builder. +
E: Okay, well, we’re not really focusing on… on new phrases for you here, but we thought it 
would be helpful to, um, talk a little bit about the jokes to help you understand them, right?
Cause they are, well, I think pretty funny. +
M: Yeah, they’re pretty funny, but maybe sometimes they’re kind of hard to understand. 
So, why don’t we start with the first joke? So, he said where do you find a one-legged
dog? +
E: What’s a… a one-legged dog? +
M: Basically, it’s a dog that has one leg. +
E: Uh, okay, and the pronunciation here’s… is important, right? +
M: One-leggEd. +
E: Not, one-leggeD. +
M: No. +
E: One-leggEd. +
M: So, you can say “A one-legged dog, a two-legged dog or a three-legged dog”. +
E: Six-legged dog? +
M: A six-legged spider, maybe lost two legs in, you know… in a war. +
E: Oh, dear. Okay, so, uh, the dog obviously didn’t go anywhere and so that’s why you find 
it where you left it. +
M: Exactly, so, that’s why it’s kind of funny. +
E: Okay. +
M: Alright, so, then he said what do you call a sheep with no legs? +
E: I don’t know. +
M: A cloud. Basically, because, you know, sheep are fluffy add they’re white, so if you take 
away their legs, they look like a little cloud. +
E: Boo. +
M: Alright, let’s look at the next one. He asked what do cows do for entertainment? +
E: And then the answer was they rent mooovies. +
M: Exactly, so, it’s kind of funny, because he’s relating this wordmovies with what the… 
with the sound that cows make, which ismoo. +
E: Right, and actually, um, there are a million jokes in English following the same pattern, 
right? +
M: Yeah, exactly. So, I’m sure you can find a lot more of them and you can share them with 
us. +
E: Now, my personal favorite joke is the guy says what does a fish say when it runs 
into a wall? +
M: So, to run into a wall, basically, is to crash against the wall. +
E: Yeah. +
M: So, what does a fish say? +
E: Dam! +
M: So, why is this funny? Why does he say “Dam”? +
E: Well, cause it’s… I mean if you… if you… if you a person and you run into a wall… Damn! 
Like the… you know, just like “Oh, no!” +
M: Ouch… ouch. +
E: Ou… yeah. But a fish is swimming under the water and like we saw a dam is actually like 
a wall in the water. +
M: So, he’s saying like “Oh, a wall”. +
E: Yeah, yeah, yeah. So, it’s that… I like that one. +
M: Hehe. Alright, the last one was pretty good. Why do gorillas have big nostrils? +
E: Okay, so, the big holes in their nose. +
M: Right, and basically it’s because they have big fingers. +
E: So, they can put their fingers in the nose? +
M: Yeah, exactly! How… +
E: Oh, dear. +
M: If the gorilla didn’t have big nostrils, he wouldn’t be able to pick his nose. +
E: Maybe he’d have to use a stick. +
M: Yeah, but that wouldn’t be convenient, see? +
E: Alright. +
M: So, that’s why those jokes are funny. They’re very short jokes. Some… of course, some 
of them are not actually really funny, but, uh… it’s just a little bit of a taste of short
American jokes. +
E: Okay, well, I think we need to hear them one more time in context, so, um, you can all 
know how funny or maybe not so funny they are. +
Announcer:Hello everyone, and welcome to open mic night! 
You’re in for a real treat as we’ve got a lot of great
comics here with us tonight. First up, we have a
very funny man coming straight from the state of
Montana, Robert Hicks! +
A: Thank you, everyone! Well, what a lovely crowd. 
You know, there’s nothing I love better than stand-
up comedy! You know, I’ve been working on my
routine for months now, and I’ve got some real
zingers for you tonight. Let’s start out with some
short jokes, how bout that? Where do you find a
one legged dog? Where you left it. +
A: Get it? mmm Anyways... What do you call a 
sheep with no legs? A cloud ! +
A: Tough crowd... Alright, now you’re going to love 
this joke. It’s hilarious! What do cows do for en-
tertainment? They rent moooovies ! moooovies +
A: Okay, Okay, we’ve got a few hecklers in the audi- 
ence, but this one is good! What does a fish say
when it runs into a wall? DAM! +
A: Okay, Last one! Why do gorillas have big nostrils? 
Coz they got big fingers!!!!!!!!! +
Crowd:Get off the stage! You suck! +
A: Thanks everyone that was my time. +
E: And now, if you have any, uh, good jokes of your own, uh, why don’t you come to our 
website and tell us about them? +
M: Right, come to englishpod.com, share with us any jokes. Of course, they have to be 
clean. Don’t come and… +
E: No… yeah, no swears. +
M: No swearing in the… in the jokes. +
E: Yeah. +
M: Alright, so, we’ll see you guys there and until next time… +
E: Thanks for listening and… Good bye! +
M: Bye! 

 
