= 0148
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


M: Hello everyone! And welcome back to another lesson here atEnglishPod! My name 
is Marco. +
C: And my name is Catherine, so, Marco, what are we talking about today? +
M: Today we are taking a look at a guy, who is, um, a little bit too afraid of people, in 
general. +
C: There’s a good word for this in English. Someone who’s almost too afraid all the time, 
someone who is overly cautious, we call this personparanoid. +
M: Okay, so if you are paranoid, you think that everyone is, uh, wants to hurt you or that 
everyone is out to get you. +
C: Wait… did you hear that? +
M: Hehe. That’s… +
C: No… did you hear that? +
M: No, I didn’t. +
C: Someone’s out the door. +
M: Hehe. +
C: Marco, can… uh, can you check the… Okay, that’s paranoid, you know, you’re always 
hearing voices and noises and things. +
M: Yeah, so, a paranoid – somebody that is paranoid. Alright, so, why don’t we listen to 
this, uh, dialogue for the first time and see what this person is all paranoid about? +
C: There it is, again. +
A: Dan, Dan dude. You have to come over to my 
house right now! +
B: Is everything Ok? +
A: Just get over here! +
A: Come in! Quickly! +
B: So, since when is your house a bank? +
A: What do you mean? +
B: I mean, what’s up with the and locks and iron bars 
on your windows. +
A: Security Dan, security! You can never be too safe 
you know! A lot of sickos out there. Just the other
day they caught that peeping tom red handed!
Had a high power telescope and binoculars by his
window. +
B: Whats the matter with you? Why are you acting 
all paranoid? +
A: Paranoid? I’m not paranoid! I’m cautious! You 
see Dan, we have to be on guard at all time! Peo-
ple just invade your privacy as if they knew you!
Telemarketers, solicitors, even your bank! They
have way too much information! I like to keep ev-
erything on a need to know basis +
B: OK, well, what did you want to see me about? +
A: You are being watched! Be careful Dan! Be care- 
ful! +
M: Alright, we’re back, so, um… yeah, I think this guy is a little bit too, um… cautious. +
C: I would have to agree with you and I would go so far as to call him paranoid. But, uh, 
there’s a lot of great stuff in this dialogue that we can use in a lot of different situations, so
let’s take a look at some of these new words in today’s “language takeaway”. +
Voice: Language takeaway. +
M: Alright, the first word on language takeaway today is sicko. +
C: Sicko is also the name of a movie that was a documentary famous in America by Michael 
More, actually. +
M: Right. +
C: But, uh, sicko, in this context means someone who is a bit weird in a bad way. +
M: So if you tell somebody “you’re sick”, the... like in that tone, right, you’re saying “you’re 
sick”, “you’re a sick person”. +
C: You are gross. +
M: Right, you’re saying “you’re gross”. +
C: You… or inapprop… people who have inappropriate humor, who make jokes about… +
M: Make… +
C: Not so nice things. +
M: Hehe. Right. +
C: Yeah, they’re sick. +
M: Aha. +
C: But, uh, in this case, sicos are people who maybe like to hurt other people or people 
who are a little bit crazy. +
M: Uhu. +
C: Uh, people who are not normal. +
M: So it’s not a nice way of calling someone crazy, right? If you… if you say “oh, he’s a 
sicko”, it’s not really nice. +
C: Not at all. It’s a way of saying that you’re almost scared of this person… +
M: Mm. +
C: Cause they’re kind of weird and almost… they have problems. +
M: Alright, so sicko. Uh, moving on to our next word, we saw that the guy was afraid of… +
C: Telemarketers. +
M: Exactly, so what are these guys? +
C: Well, we’ve got two words being put together here: tele andmarket. So, uh, tele… +
M: Like telephone. +
C: Telephone. +
M: Uhu. +
C: Commu… over communications, so they’re not in person, that people who call you up. 
And market things, they try to sell you stuff over the phone. +
M: So this is very common. You’re… you’re… you get a phone call on your cell phone and 
they ask you if you’re… if you’re happy with your long distance calling plan or if you need
new TV cable or some[thing] like that. +
C: And they always call during dinner or late at night. +
M: Hehe. +
C: Which drive me nuts. +
M: Exactly. +
C: So these are telemarketers. These are people who call you trying to sell things to you. +
M: And very similar to… to these is, uh, solicitors. +
C: Exactly, but the big difference here with solicitors andtelemarketers is that solicitors 
actually go to your house, they knock on your door. +
M: Uhu, so they’re also called door-to-door salesmen or saleswomen. +
C: That’s right, so door-to-door salesmen, they go from door to door trying to sell things. 
But in this case a solicitor is someone who comes to your house to try and to you to do
something, to buy something. +
M: Uhu. Alright, very good. And moving on to our next word, we have a peeping tom. +
C: That’s right, we heard this a little bit earlier in the dialogue and a peeping tom is again, a 
negative thing to say about someone. S… a peeping tom… well, the word peep means to
look… +
M: Uhu. +
C: But kind of like… +
M: Quick look. +
C: Yeah, it’s a quick look. So peeping tom is a person who spies on other people. +
M: Okay, so a synonym of a peeping tom would be a voyeur. +
C: A voyeur, so someone who, um, without getting caught tries to look at other people 
while they’re in their homes and so, it’s really bad, because, uh, it’s usually inappropriate. +
M: Right. +
C: It’s usually people who are watching women get undressed or… +
M: Right, right. +
C: Yeah, yeah. +
M: So a peeping tom is just an informal way of saying a voyeur or somebody who is spying 
on people. So those are the words for today in language takeaway. Let’s listen to our
dialogue again and then we’ll be right back. +
A: Dan, Dan dude. You have to come over to my 
house right now! +
B: Is everything Ok? +
A: Just get over here! +
A: Come in! Quickly! +
B: So, since when is your house a bank? +
A: What do you mean? +
B: I mean, what’s up with the and locks and iron bars 
on your windows. +
A: Security Dan, security! You can never be too safe 
you know! A lot of sickos out there. Just the other
day they caught that peeping tom red handed!
Had a high power telescope and binoculars by his
window. +
B: Whats the matter with you? Why are you acting 
all paranoid? +
A: Paranoid? I’m not paranoid! I’m cautious! You 
see Dan, we have to be on guard at all time! Peo-
ple just invade your privacy as if they knew you!
Telemarketers, solicitors, even your bank! They
have way too much information! I like to keep ev-
erything on a need to know basis +
B: OK, well, what did you want to see me about? +
A: You are being watched! Be careful Dan! Be care- 
ful! +
M: Now we’re back and we had some interesting phrases in the dialogue. Uh, the first one 
being you can never be too safe. +
Voice: Fluency builder. +
C: Alright, so, this is, uh… this is a common “mom phrase”. You often hear mothers say this 
when they’re sending their kids off to school or whatever. +
M: Mm. +
C: They say: don’t talk to strangers. And the kid says: mm, why not? You can never be too 
safe. +
M: Alright. +
C: Right, it’s… it’s good to err on the side of caution. +
M: So it’s okay to be extra, extra, ah, safe or extra cautious. +
C: Exactly. +
M: Just in case. +
C: Exactly, you never know what’s going to happen, so it’s better to be cautious than not. +
M: Uhu. +
C: And that’s what this, um… this person’s saying. He’s saying: well, security, it’s important, 
you can never be too safe, you never know what might happen. +
M: Uhu. Is there another way that we can combine it, like you can never be too careful? +
C: Exactly, …ctly, so… +
M: It’s basically same thing. +
C: Same… same thing, yeah. +
M: Alright. What’s our next phrase? +
C: Our next phrase is about this peeping tom, this person that they caught. Uh, 
they caught him red handed. +
M: We caught you red handed. +
C: Or he’s been caught red handed. +
M: Uhu. So what does that mean? +
C: Uh, this is… it’s a big colorful phrase… +
M: Hehe. +
C: And I don’t just mean that, because we’re calling him red handed. But, um, to catch red 
handed means to catch someone while they’re doing something wrong. +
M: Uhu. +
C: So if I see you breaking into someone’s house and I say: Marco, stop! I’m catching you, 
stop now! +
M: Uhu. +
C: I just caught you red handed. +
M: You saw me doing the act. +
C: Exactly, uhu. +
M: Uh, and another way of saying this is you caught him with his hand in the cookie 
jar. +
C: Mm, okay, and this is… this is another great phrase. You can imagine a child who sees 
the cookies in a… in a very special jar on the… the counter in the kitchen. +
M: Uhu. +
C: And, uh, mom says: don’t eat the cookies. Well, the child goes into the kitchen and sees 
the cookies and opens the jar put this hand in the jar and then mom comes in and says:
caught you. +
M: Right. +
C: That’s… that’s a boy with his hand or a child with their hand in the cookie jar. +
M: So it’s the same thing. I can say: I caught you with your hand in the cookie jar. +
C: Or you were caught red handed. +
M: Uhu. Alright, and our last phrase for today is you are on a need to know basis. +
C: Alright, this is a great one. This is often said in spy movies I think. +
M: Yeah. +
C: Um, so he’s saying “you are on a need to know basis”, that means that if you really need 
to know something, then I will tell you. +
M: Right. +
C: But if not, I won’t. +
M: So you only have the information that is necessary. No more or less, right? You’re on a 
need to know basis. +
C: Right, so I say: tell me, Marco, tell me what happened, I wanna know. +
M: Right, and I can say: no, no, you’re on a need to know basis and you don’t need to know 
this. +
C: Ouh. +
M: Hehe. +
C: Hehe. +
M: Alright, so a need to know basis. As you say, very popular among spy movies and 
government movies and stuff like that. +
C: Conspiracy movies. +
M: Yeah. Hehe. Alright, so let’s listen to this dialogue for the very last time and we’ll be 
right back. +
A: Dan, Dan dude. You have to come over to my 
house right now! +
B: Is everything Ok? +
A: Just get over here! +
A: Come in! Quickly! +
B: So, since when is your house a bank? +
A: What do you mean? +
B: I mean, what’s up with the and locks and iron bars 
on your windows. +
A: Security Dan, security! You can never be too safe 
you know! A lot of sickos out there. Just the other
day they caught that peeping tom red handed!
Had a high power telescope and binoculars by his
window. +
B: Whats the matter with you? Why are you acting 
all paranoid? +
A: Paranoid? I’m not paranoid! I’m cautious! You 
see Dan, we have to be on guard at all time! Peo-
ple just invade your privacy as if they knew you!
Telemarketers, solicitors, even your bank! They
have way too much information! I like to keep ev-
erything on a need to know basis +
B: OK, well, what did you want to see me about? +
A: You are being watched! Be careful Dan! Be care- 
ful! +
M: Alright, so, um, the guy is a little bit paranoid. There’s another word for this as well, 
similar, right, a schizo. +
C: Schizophrenia is a disease and, uh, a lot of people have it and it’s not too uncommon, 
but a lot… a popular slang word to say someone’s crazy is schizo, so… +
M: So if you guys remember this movie A Beautiful Mind. +
C: Mm. +
M: It’s all about, uh, this famous mathematician named John Nash and, uh… well, he was a 
genius, he came up with game theory and, uh, a lot of subsequent usage of this for
economy, for many things. +
C: Uhu. +
M: But, um, it was proven that he was schizophrenic, right? +
C: A paranoid schizophrenic, so… +
M: Uhu. +
C: Not only did he kind of… have… experienced reality in different ways, but he’s also 
paranoid. So he was afraid that the government was trying to kill him… +
M: Uhu. +
C: And so, he… he was, um… he was irrationally afraid of everything going on around him 
and it made him very, uh, unsafe, because he could hurt himself or hurt other people. +
M: Uhu. And the interesting thing about this is that there is no actual cure for it. +
C: Uhu. +
M: You just learn to cope and live with it… +
C: Uhu. +
M: So you never really get cured. You’re just kind of live with it. +
C: Learn… learn how to understand… +
M: Yeah. +
C: What’s real and what’s not. +
M: So it’s interesting, it’s a… it’s a great movie also. By the way, if you ever… if you’ve 
never seen it, you get a chance to watch it. And, uh, that’s all the time we have for today,
so if you have any questions, doubts or comments, please come to our
website englishpod.com. +
C: Yup. +
M: And, uh, we’re there to answer them. +
C: Yeah, we hope to see you there and until next time, English poddies… +
M: Alright, bye-bye! +
C: Bye! 
  
