= 0354
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 354: Being Scared.
This is English as a Second Language Podcast episode 354. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. The Learning Guide contains all of the definitions, sample sentences, additional definitions, cultural notes, comprehension questions, and a complete transcript of this episode.
This episode is called “Being Scared.” It’s a dialogue between Emily and Stephen about going into a house that is supposed to be haunted. Let’s get started.
[start of dialogue]
Emily: I’m not going into that house. It’s supposed to be haunted.
Stephen: Come on. Don’t be a coward. You don’t believe in ghosts, do you?
Emily: I don’t, but I’m not taking any chances. Just look at that house! It’s spooky. I’m getting goosebumps just looking at it.
Stephen: You’re only freaking out because you’ve watched too many horror movies. It’s just a house. Now, come on!
Emily: Why are we doing this anyway? Just because your friends dared you to go in doesn’t mean you have to. This is stupid!
Stephen: I took the dare and I told them I’d spend the night in that house. If you’re a scaredy-cat, you can go home right now.
Emily: And let you go in there by yourself? What kind of girlfriend would I be? I’m scared to death, but I’m not going to chicken out. Okay, let’s go before I change my mind.
Stephen: Really? I didn’t think you’d have the nerve. You’re braver than I thought. Don’t worry. Nothing in there can hurt us.
Emily: Famous last words!
[end of dialogue]
Our dialogue begins with Emily saying to Stephen, “I’m not going into that house. It’s supposed to be haunted. To be “haunted” (haunted) means that there are ghosts or other spirits in a building. This is a belief that some people have that there are people who died, and then they come back and they “haunt” a place – they stay there and they try to scare you. This is something you’ll see in a movie, for example. On Halloween, we often have what are called “haunted houses,” and these are houses that people dress up in, and try to scare you.
Stephen says, “Come on. Don’t be a coward.” “Come on,” here, means be serious, don’t joke. “Don’t be a coward” (coward). “Coward” is someone who is afraid, someone who doesn’t have courage because he or she is scared. That’s a “coward,” it’s a negative term. Stephen says, “You don’t believe in ghosts, do you?” This is an example of what we call in English a “tag (tag) question.” The first part of the sentence is negative: “You don’t believe in ghosts,” the last part is “affirmative,” or positive: “do you?” The answer to this question is if you don’t believe in ghosts to say “no.” This can be very confusing; many people think that the answer would be “yes” if you don’t believe in ghosts. So, Stephen is saying to Emily “You don’t believe in ghosts.” Emily doesn’t believe in ghosts, and so she’s going to say “No, I don’t believe in ghosts.” You don’t say “Yes, I don’t believe in ghosts,” you say “No, I don’t believe in ghosts.” “Ghosts” are spirits of a dead person that can be seen and heard by living people. That’s the idea, anyway.
Emily says, “I don’t (believe in ghosts), but I’m not taking any chances.” The expression “I’m not going to take any chances” means I’m not going to take a risk, I’m not going to do something that might cause me more problems or trouble. Emily says, “Just look at that house!” The expression here, “just look,” or “just listen to this,” is a way of saying you haven’t looked or listened carefully enough, you’re not understanding what I’m saying; it’s a way of emphasizing your point.
She says, “Just look at that house. It’s spooky.” “Spooky” (spooky) means scary; something that is strange and unusual that causes you fear is “spooky.” Emily says, “I’m getting goosebumps just looking at it.” “Goosebumps” (goosebumps – one word) are little bumps that appear on your skin when you are either cold or scared. So you look at your arm, and you see these little bumps; you can feel them on your skin. “To get goosebumps” means to either be scared or to be cold, here it means to be scared. There was actually a series of books – there is a series of books very popular with elementary school children, especially boys. The series is called Goosebumps; it’s like the Harry Potter series in that it’s about some things that are scary – haunted things, spooky things. Very popular series among young boys, and the English is fairly easy. There are actually some ESL adults that read these easier novels because the English is easier for people to understand. That’s “goosebumps.”
Well, Emily says she’s “getting goosebumps just looking at the house.” She doesn’t even have to go into it, just looking at it gives her goosebumps. Stephen says, “You’re only freaking out because you’ve watched too many horror movies.” “To freak out” is a two-word phrasal verb meaning to become very scared, to act very strangely usually because you are frightened – you are scared of something. Someone says to you “don’t freak out,” means don’t get excited – don’t be scared by what I am going to tell you or show you.
Emily’s been watching too many horror movies. A “horror movie” is a scary movie that’s supposed to frighten people. Emily says, “Why are we doing this anyway? Just because your friends dared you to go in doesn’t mean you have to.” “To dare someone to do something” means to challenge someone, to get someone to do something that might be frightening, or embarrassing, or difficult. This is something that children and adolescents, teenagers sometimes do. “I dare you to go to that beautiful woman and ask her for her telephone number” – “I dare you to” can be very scary! The word “dare,” as well as the expression “to take any chances,” have a couple of different meanings; take a look at our Learning Guide for some additional explanations.
Stephen responds, “I took the dare and told them I’d spend the night in that house.” Notice “dare,” here, is used as a noun: “I took the dare” – I accepted the challenge. “I told them I would spend the night.” “To spend the night” means to sleep somewhere for one night. Stephen says to Emily, “If you’re a scaredy-cat, you can go home right now.” A “scaredy-cat” is a person who’s afraid of everything, who has no courage, who’s always scared. It’s a term that you would probably hear children use, more than anything. “Don’t be a scaredy-cat” you might say to your friend.
Emily says she’s not going home. “What kind of girlfriend would I be?” she says. “I’m scared to death, but I’m not going to chicken out.” To say you’re “scared to death” means you’re extremely scared, you’re very frightened. “To chicken out” is a two-word verb meaning to decide not to do something because you’re too scared, because you’re a coward, because you don’t have courage. Once again, it’s considered a negative thing, “to chicken out ,” to not do something because you’re too scared.
Emily says, “let’s go before I change my mind” – let’s go before I decide to do something different, to not go in the house, in this case. Stephen says, “Really? I didn’t think you would have the nerve.” “To have the nerve” (nerve) means to have courage to do something, to be able to do something even though you are scared or frightened. Stephen says to Emily, “You’re braver than I thought.” “To be brave” means to be “courageous,” to have courage. It’s the opposite of being a coward or being scared. Stephen says, “You’re braver than I thought” – you’re more brave than I thought. “Don’t worry. Nothing in that house can hurt us.
Emily says at the end, “Famous last words!” This expression, “famous last words,” is used to show that what somebody has said is probably wrong, and there will be some serious consequences – some negative things that will happen in the future. For example, you say to your friend, “My wife is going to love this new vacuum cleaner to help her clean our carpets,” and your friend says, “Famous last words!” meaning you’re probably wrong, and your wife is going to hate the vacuum cleaner. He’s right, you should never give your wife a vacuum cleaner as a gift!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Emily: I’m not going into that house. It’s supposed to be haunted.
Stephen: Come on. Don’t be a coward. You don’t believe in ghosts, do you?
Emily: I don’t, but I’m not taking any chances. Just look at that house! It’s spooky. I’m getting goosebumps just looking at it.
Stephen: You’re only freaking out because you’ve watched too many horror movies. It’s just a house. Now, come on!
Emily: Why are we doing this anyway? Just because your friends dared you to go in doesn’t mean you have to. This is stupid!
Stephen: I took the dare and I told them I’d spend the night in that house. If you’re a scaredy-cat, you can go home right now.
Emily: And let you go in there by yourself? What kind of girlfriend would I be? I’m scared to death, but I’m not going to chicken out. Okay, let’s go before I change my mind.
Stephen: Really? I didn’t think you’d have the nerve. You’re braver than I thought. Don’t worry. Nothing in there can hurt us.
Emily: Famous last words!
[end of dialogue]
The script for this episode was written by the very brave Dr. Lucy Tse!
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
haunted – with ghosts and/or spirits in a location, such as inside a building
* All the children on this street think that the old green house is haunted.
coward – someone who lacks courage and doesn’t do something because he or she is very scared
* Michelle is scared of the dark, and she’s such a coward that she has to sleep with the lights on.
ghost – the spirit of a dead person that can be seen and heard by living people
* Blake believes that he has seen the ghost of his grandmother, who died 15 years ago, walking around the old house.
to take any chances – to take a risk; to do something that may be risky; to do something that may cause problems or trouble
* Ezekiel doesn’t want to take any chances with his health during the flu season, so he washes his hands with hot water and soap every hour.
spooky – scary; eerie; frightening, creepy; strange and unusual, causing fear
* The tree branch blew in the wind, making a spooky noise each time it hit the window.
goosebumps – small bumps that appear on one’s skin when one is cold or scared
* He was so cold that he had goosebumps all over his arms and legs.
to freak out – to become very scared in an unusual way; to act oddly, often because one is frightened
* Laureline freaked out when her parents told her that she would go to a new school next year.
horror movie – a scary movie; a movie that is designed to frighten people
* A Nightmare on Elm Street is a classic horror movie.
to dare (someone to do something) – to challenge or get someone to do something that is very frightening, embarrassing, or difficult
* The girls dared each other to run around the house at night while wearing their pajamas.
to spend the night – to stay in a particular place for one night; to sleep somewhere for one night
* For her birthday, Rachel invited four friends to spend the night at her house.
scaredy-cat – a person who is scared of everything; a person who has no courage
* Don’t be such a scaredy-cat! It’s just a snake.
scared to death – extremely frightened and scared
* Luca was scared to death when he found out that for the assignment, he would have to speak in front of all of his classmates.
to chicken out – to decide not to do something because one is too scared
* The three friends were going to jump out of a plane with parachutes, but one of them chickened out at the last minute.
to change (one’s) mind – to decide not to do something that one had been planning to do; to decide to do something differently than planned
* Damian wanted to go to Oahu for vacation, but he changed his mind when he found out how expensive it would be.
to have the nerve – to have enough courage to do something; to be able to do something even though one is very scared or frightened
* I didn’t think you would have the nerve to lie to your parents about that!
brave – courageous; with courage; willing and able to do something, even though one is scared
* It was very brave of you to have gone into that burning house to save the little girl.
famous last words – a phrase used to show that what another person has said is wrong and could have very serious consequences
* Vicky said that the client would love our presentation. Famous last words! They hated everything we showed them, so now we have to start again from the beginning.
Comprehension Questions
1. What is a haunted house?
a) A house that has ghosts in it.
b) A house where scaredy-cats live.
c) A house where cowards like to go.
2. What would happen if Emily chickened out?
a) She would get goosebumps.
b) She would freak out.
c) She would decide not to enter the house.
Answers at bottom.
What Else Does It Mean?
A “slasher film” is another “term” (a word with a special technical meaning) for a “horror movie.” The verb “to slash” means to cut something violently with a sharp object. Slasher films don’t always involve cutting, but they are very violent and have many deaths, usually of teenagers. These films are created to scare people.
Slasher films have many things in common. First, the murderer usually kills teenagers or young people in their 20s who are “engaged in” (participating in) what some people would consider “immoral” (bad and wrong) behavior, such as taking drugs or entering a place they’re not supposed to. The murderer is usually a man who causes a lot of fear in other people. In general, the more “moral” (showing good behavior) the characters are, the more likely they are to survive the killer’s attacks. In most slasher movies, the “characters” (people in a movie or play) are killed one at a time, until only one girl or young woman is left alive at the end of the movie. She alone makes many “attempts” (tries) to kill the murderer. Sometimes this character succeeds in killing the murderer, but other times the murderer “escapes” (gets away) and “disappears” (leaves without anyone knowing where one went).
One famous slasher film, Halloween, was made in 1978. In this film, the murders happen among teenagers who are “babysitting” (being paid to take care of other people’s children). Friday the 13th was made two years later. In this movie, the murders happen at a summer camp. Four years later, A Nightmare on Elm Street was “released” (made available to the public). In this slasher film, children have nightmares about a murderer named Freddy Krueger. Although the murderer exists only in nightmares, he is able to hurt and even kill the people who dream about him.
Culture Note
A “slasher film” is another “term” (a word with a special technical meaning) for a “horror movie.” The verb “to slash” means to cut something violently with a sharp object. Slasher films don’t always involve cutting, but they are very violent and have many deaths, usually of teenagers. These films are created to scare people.
Slasher films have many things in common. First, the murderer usually kills teenagers or young people in their 20s who are “engaged in” (participating in) what some people would consider “immoral” (bad and wrong) behavior, such as taking drugs or entering a place they’re not supposed to. The murderer is usually a man who causes a lot of fear in other people. In general, the more “moral” (showing good behavior) the characters are, the more likely they are to survive the killer’s attacks. In most slasher movies, the “characters” (people in a movie or play) are killed one at a time, until only one girl or young woman is left alive at the end of the movie. She alone makes many “attempts” (tries) to kill the murderer. Sometimes this character succeeds in killing the murderer, but other times the murderer “escapes” (gets away) and “disappears” (leaves without anyone knowing where one went).
One famous slasher film, Halloween, was made in 1978. In this film, the murders happen among teenagers who are “babysitting” (being paid to take care of other people’s children). Friday the 13th was made two years later. In this movie, the murders happen at a summer camp. Four years later, A Nightmare on Elm Street was “released” (made available to the public). In this slasher film, children have nightmares about a murderer named Freddy Krueger. Although the murderer exists only in nightmares, he is able to hurt and even kill the people who dream about him.
Comprehension Answers
1 - a
2 - c