= 0355
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 355: Finding a Bargain.
This is English as a Second Language Podcast episode 355. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. There you can download a Learning Guide for this episode to help you improve your English even faster.
This episode is called “Finding a Bargain.” It’s a dialogue between Manuel and Georgia about Georgia’s trip to the store. Let’s get started.
[start of dialogue]
Manuel: Wow, I’ve never seen so many shopping bags in my life. I can guess where you’ve been.
Georgia: I did go overboard a bit today. I went to the outlet mall and I found some real bargains. Nearly everything was discounted. I was in shopping heaven!
Manuel: I can see that.
Georgia: My favorite store had reduced prices for all of its sweaters, so I bought five. They were already on sale, but the store knocked another $5 off the price. I got them at half-price! I was going to buy three, but the store had a special offer: If you buy four, the fifth one is free.
Manuel: But doesn’t that mean you spent more money, since you bought five sweaters when you only wanted three?
Georgia: How could I resist? They were being sold at bargain basement prices. At another store, the sale items were two for the price of one. I’ve never seen things in that store so cheap.
Manuel: Where are you going now?
Georgia: I’m going back to the outlet stores, of course. I just came home for a little breather. There’s more shopping to be done!
Manuel: Try to leave a few things for the other shoppers!
[end of dialogue]
Our dialogue begins with Manuel saying, “Wow, I’ve never seen so many shopping bags in my life,” meaning those are a lot of “shopping bags,” the bags that you use from the store to carry things back home. He says, “I can guess where you’ve been.” Georgia says, “I did go overboard a bit today.” “To go overboard” means to do too much of something, to do something to an extreme. If you go to a buffet lunch where you can eat as much food as you want, it’s important not to go overboard.
Georgia says she went to an “outlet mall.” A “mall” is a large building full of stores, where you go shopping. An “outlet mall” is where companies sell clothing and other things at a cheaper price than at the regular stores. It is usually a place where you find clothing that wasn’t very popular, or perhaps may have some small problems; these are sold at “outlet malls.” Many of the big clothing companies sell their clothes at these outlet malls when they can’t sell them in the regular stores.
Georgia said she found some real bargains. A “bargain” is something that costs less than it usually would. The word “bargain” actually has a couple of different meanings; take look at our Learning Guide for some additional explanations. Georgia says that nearly everything in the store was discounted. “To be discounted” means to be sold at a price that is lower than usual. Another expression for this would be “on sale.” This was “discounted” – this was “on sale.” Georgia says, “I was in shopping heaven!” “Heaven” is a place where everything is perfect, where one is completely happy – that’s the idea. Someone may say, “I went to the comic book convention and I was in heaven,” or, “I was in Spider-man heaven,” meaning it was a very happy place for me to be.
Manuel says, “I can see that” – I can see you were in shopping heaven. Georgia says, “My favorite store had reduced prices for all of its sweaters.” A “reduced price” is the same as a discounted price, when the price is lower than normal for a certain amount of time. She says that she bought five sweaters, “They were already on sale (they were already discounted), but the store knocked another $5 off the price.” “To knock (a certain amount) off the price” means to lower the price, to make the price less than it was before. You may say, “My mechanic knocked off $20 on my bill to fix my car.” He reduced the price $20 – he “knocked off” $20. Of course, the bill was $1,000, so it wasn’t very much!
Georgia says, “I got (the sweaters) at half-price” – at 50 percent off, or 50 percent discount. “I was going to buy three,” she says, “but the store had a special offer.” A “special offer” is sometimes called a “promotion,” when the store offers to give the customer something special or something at a lower price for a certain amount of time. The offer was if you buy four sweaters, you can get a fifth sweater for free. Georgia was only going to buy three, but she bought four, because then she would get five sweaters.
Manuel says, “doesn’t that mean you spent more money (than you were going to spend)?” Georgia says, “How could I resist?” “To resist” means to be able to stop yourself from doing something that you want to do. For example, you went to the buffet and you went overboard. Now, you’re at home, and you have a piece of apple pie in your refrigerator. You have to resist that temptation – that desire – to eat the pie; you have to stop yourself from doing it. I say you have to stop yourself – I don’t have to stop myself!
Georgia says the sweaters “were being sold at bargain basement prices.” The “basement” is the part of a building or a house that is below ground – that is underneath the ground. The term “bargain basement” refers to the fact that some stores used to sell things cheaply – put things on sale – in the basement of the store – in the bottom of the store, and so we have this expression “bargain basement.” So, these were “bargain basement prices,” they were low prices.
“At another store,” she continues, “the sale items were two for the price of one.” Sometimes we just say they were “two for one,” you buy one thing, and you get a second thing free. She says, “I’ve never seen things so cheap” – so inexpensive, with such a low price. The word “cheap” actually has a couple of different meanings, also, in English; take a look at the Learning Guide for some more explanation.
Manuel says, “Where are you going now?” Georgia says, “I’m going back to the outlet stores, of course. I just came home for a little breather.” A “breather” (breather) here means a break – a pause in an activity, a short time for you to rest. “I’m going to take a breather,” or, I’m here just for a breather.” She says, “There’s more shopping to be done,” meaning she has more shopping she wants to do. Manuel says, “Try to leave a few things for the other shoppers,” meaning don’t buy the entire store my love!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Manuel: Wow, I’ve never seen so many shopping bags in my life. I can guess where you’ve been.
Georgia: I did go overboard a bit today. I went to the outlet mall and I found some real bargains. Nearly everything was discounted. I was in shopping heaven!
Manuel: I can see that.
Georgia: My favorite store had reduced prices for all of its sweaters, so I bought five. They were already on sale, but the store knocked another $5 off the price. I got them at half-price! I was going to buy three, but the store had a special offer: If you buy four, the fifth one is free.
Manuel: But doesn’t that mean you spent more money, since you bought five sweaters when you only wanted three?
Georgia: How could I resist? They were being sold at bargain basement prices. At another store, the sale items were two for the price of one. I’ve never seen things in that store so cheap.
Manuel: Where are you going now?
Georgia: I’m going back to the outlet stores, of course. I just came home for a little breather. There’s more shopping to be done!
Manuel: Try to leave a few things for the other shoppers!
[end of dialogue]
The script for this episode was written by a woman who works so hard she could use a breather, too: Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
to go overboard – to do too much of something; to do something to an extreme
* They went overboard at the free buffet lunch, eating so much that they felt sick afterwards.
outlet mall – a large building with many stores that sell inexpensive products that either didn’t sell well in regular stores or have small problems
* If you need to get a lot of suits for work, you can get them less expensively at outlet malls than at regular malls.
bargain – a deal; something that has a very low price; something that costs much less than it normally does; a good value for the money you pay
* At just $65, the jacket was a bargain, since it normally costs almost $300.
discounted – being sold at a price that is lower than usual; on sale
* This week, all of the store’s history books are discounted 10%.
heaven – paradise; a place and time where everything is perfect and one is completely happy
* I love to eat ice cream, so working in an ice cream store would be heaven!
reduced price – a price that is lower than normal for a certain period of time
* The car dealership is advertising reduced prices on all of its cars this week.
on sale – with a lower-than-normal price for a certain period of time
* The store is putting all of its women’s shoes on sale next week.
to knock another (amount) off the price – to lower the price of something by a certain amount
* Amanda bargained at the outdoor market until the seller agreed to knock another $13 off the price of the table she wanted to buy.
half-price – 50% of the regular price
* This half-price printer was only $35. It normally costs $70.
special offer – a promotion; something that a store offers to give to a customer during a certain period of time
* The computer store has a special offer this month: if you buy a new computer, you automatically get a free scanner and web camera.
to resist – to be able to stop oneself from doing something that one wants to do
* I could lose a lot of weight if I could learn to resist eating dessert every day.
bargain basement – the underground floor of a store where things are sold very inexpensively
* Everything on the first floor of that store is very expensive, but if you go to the bargain basement you can find some great deals.
two for the price of one – a promotion where a customer pays for only one item and receives a second one for free; buy one, get one free
* Admission to the zoo is two for the price of one on Thursdays, so I am going to take my niece there next Thursday.
cheap – inexpensive; not costing very much money; with a low price
* This restaurant is really cheap! You can get a three-course meal for only $4.99.
breather – a break; a pause in an activity; a short period of time to rest
* After working in the yard all day, Hal took a 20-minute breather before starting to clean out the garage.
Comprehension Questions
1. How many sweaters did Georgia pay for?
a) Three.
b) Four.
c) Five.
2. Why did Georgia come home?
a) Because she was feeling out of breath.
b) Because the bargain basement closed.
c) Because she needed to rest a little bit.
Answers at bottom.
What Else Does It Mean?
bargain
The word “bargain,” in this podcast, means something that has a very low price and costs much less than it normally does: “Her airline ticket was a bargain! She paid only $250 to fly across the country.” A “bargain” is also an agreement between two people to do something for each other: “They made a bargain that he would cook and she would wash the dishes.” As a verb, “to bargain” means to negotiate, or to argue and discuss prices until both the seller and buyer agree on the final price: “Do you like bargaining at farmers’ markets?” Finally, the phrase “to bargain on (something)” means to believe that something will happen and to prepare for it: “They planned an outdoor wedding, bargaining on sunshine.”
cheap
In this podcast, the word “cheap” means inexpensive: “Simple cell phones are cheaper than phones that have cameras and full-color screens.” The word “cheap” also means something that is poor quality: “If you want to get a better job, you need to stop wearing such cheap suits to your interviews.” If a person is “cheap,” it means that he or she is not generous and does not like to share money with other people: “Francine is so cheap that she mixes her children’s milk with water so that it will last longer.” Finally, the phrase “on the cheap” means doing something for less money than it normally costs: “I want to learn how to travel in Western Europe on the cheap.”
Culture Note
People who want to save money while shopping have many “options” (choices) in the United States. Outlet malls, for example, are large buildings with many stores that sell things that are cheaper than usual, either because they didn’t sell well in regular stores or because they have “flaws” (small problems). “Factory stores” are stores that sell everything made for one specific brand. Factory store prices are usually much cheaper than prices for the same products at regular stores, where the items are sold “alongside” (next to) other brands.
Other people like to go to “discount stores.” These stores don’t always have the same products. Instead, the “store buyers” (store employees who buy things to sell in the stores) look for good bargains and then buy those items in “large volumes” (with many pieces of the same thing) to sell them to customers inexpensively. It can be difficult to find what you are looking for in a discount store, but sometimes it is a good idea to go there and see what is available for sale.
“Secondhand stores” offer inexpensive clothing, jewelry, and furniture that have already been used by other people. Sometimes secondhand goods are in poor condition, but other times they are almost new. This is especially true in wealthy neighborhoods, where people sometimes use things only two or three times before getting rid of them.
Finally, many stores have “sample sales” when they want to get rid of products that they no longer plan to sell. For example, many clothing stores display a sample on a “mannequin” (a statue that is used to display clothing) and then, when that item is no longer for sale, want to get rid of the sample. They do this through a sample sale, offering it at a reduced price.
Comprehension Answers
1 - b
2 - c