= 0375
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 375: A Call from a Telemarketer.
This is English as a Second Language Podcast episode 375. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
You can visit our website at eslpod.com to download a Learning Guide for this episode and all of our current episodes. You can also visit our ESL Podcast Store, which has additional courses in English you may be interested in.
This episode is called “A Call from a Telemarketer.” A “telemarketer” is someone who calls you on the telephone to sell you something. Let’s listen.
[start of dialogue]
Doris: Hello.
Telemarketer: Hello, may I speak to the lady of the house?
Doris: What is this regarding?
Telemarketer: I’m calling from Cheetam Cable Company and we have a very special offer. This month only, you can get a bundle of services for the low, low price of $69.99! This offer...
Doris: Thank you, but I’m not interested.
Telemarketer: But that’s because you haven’t heard the rest of the offer yet. If you sign up today, you will get at no extra charge, all of the equipment you’ll need to switch to our cable company.
Doris: As I said, I’m not interested. I’m also on the national do-not-call registry and I want to be taken off your call list.
Telemarketer: If you’re on my list, it means that you have a prior relationship with our company and telemarketers are allowed to call you. Now about that special offer...
Doris: I don’t want to hear your sales pitch. I demand to be taken off your call list and I don’t want to get any more calls from your company.
Telemarketer: Is that a “no” on the special offer?
Doris: Yes, that’s a “no” on the special offer and a “no” on getting any more calls from your company. Do I make myself clear?
Telemarketer: Yes, very clear. If you’re not interested in our special offer, I can tell you about our other services...
Doris: No you can’t! [Hangs up the phone]
[end of dialogue]
Doris answers the phone by saying, “Hello.” The telemarketer says, “Hello, may I speak to the lady of the house?” “The lady of the house” would be the female head of the house or the family. Usually the wife and/or mother, that would be the lady of the house. Sort of an old-fashioned expression now, but you will still hear it. The opposite would be “the man of the house,” which would be the husband or father, or head of the house who was a man. Not all houses have lady and man of the house present.
Doris says, “What is this regarding?” This is a formal way of asking for the person to tell them what they are calling for. It’s a polite way of asking why are you calling: “What is this regarding?” The telemarketer says, “I’m calling from Cheetam Cable Company and we have a very special offer.” A “cable company” is the company that brings cable television that gives you many different hundreds of channels to watch. “This month only,” the telemarketer says, “you can get a bundle of services for a low, low price of $69.99!” A “bundle” (bundle), here, means a group or a “package,” two or more things for one price; so, a bundle of services. Maybe you’ll get sports and movies and other types of television all for one price; that would be a package or a bundle. The telemarketer says, “This offer,” trying to continue to sell Doris. Doris says, “Thank you, but I’m not interested.” This is a polite way of telling someone who calls you that you don’t want to talk to them anymore, that you are not interested in buying what they are selling.
The telemarketers don’t give up easily, however. This one says, “But that’s because you haven’t heard the rest of the offer yet. If you sign up today, you will get at no extra charge, all of the equipment you need to switch to our cable company.” “If you sign up (if you become a member – if you agree to buy this) today, you will get at no extra charge (meaning for free) all of the equipment you’ll need to switch to our cable company.” “To switch,” here, means to change, to stop using this company and start using a different company’s services. Both the expression “to switch” and “bundle” have additional meanings in English; take a look at our Learning Guide for some of those explanations.
Doris says, “As I said, I’m not interested. I’m also on the national do-not-call registry and I want to be taken off your call list.” The “do-not-call registry,” or list, was created by the U.S. federal government in 2003 to allow people to say to businesses “I don’t want you to call me,” and if a business calls someone who asks not to be called, they can be “penalized,” they may have to pay a fine to the government because it is against the law for them to call you if you asked not to be called. So you call up the government, or you go on the website, and you put your telephone number in, and any company that uses telemarketers – uses salespeople who call by telephone – has to check that list first to make sure that your name is not on it. Most Americans, I think, or a very high percentage of Americans now have their telephone numbers on that list; I know I do. Unfortunately now, we have a new problem, which is spam. But that’s at least one thing we don’t have to worry about: telemarketers. Doris says, “I want to be taken off (or removed) your call list,” the list of people that you have that you call to try to sell things to. You can use that expression “take me off” also to request that someone remove your email address from their list: “Please take me off of this list” – please remove me, delete my email.
The telemarketer then says to Doris, “If you are on my list (my call list), it means that you have a prior relationship with our company and telemarketers are allowed to call you.” One of the exceptions to the rule about the do-not-call registry is that if you have a business or other relationship with the company, the company can call you, even if you are on the do-not-call registry. So for example, your telephone company, you have a relationship with them – you pay them for your telephone service – they could call you and try to sell you things. Now usually if you tell the company “I don’t want any more phone calls,” they will take you off even that list so you won’t get any more calls, at least sales calls. So, a “prior relationship” is some contact in the past between two people. Telemarketers, we’ve already mentioned, are people who are paid to call you to sell you things.
Doris says, “I don’t want to hear your sales pitch.” The “sales pitch” (pitch) is the way that someone tries to sell you something. It’s the speech that they use – the words that they use to try to get you to buy something. Doris then says, “I demand to be taken off your call list.” “To demand” means to insist, to require someone else do something; that is “to demand.”
“I don’t want to get any more calls from your company.” The telemarketer says, “Is that a ‘no’ on the special offer?” meaning “so you don’t want to buy the special offer?” Doris says, “Yes, that’s a “no’ on the special offer and a ‘no’ on getting any more calls from your company.” She’s getting a little angry here (Doris). Doris says, “Do I make myself clear?” This is a very strong, more forceful way of saying “do you understand me.” Usually it’s made when you are, perhaps, angry with someone, or you are making a demand on someone, or insisting that someone do what you are saying to them. “Do I make myself clear?” is something a parent might say to a child, for example, or you might say to some salesperson who was bothering you, and that’s what Doris is doing here.
The telemarketer says, “Yes, very clear. If you’re not interested in our special offer, I can tell you about our other services.” So, the telemarketer wants to continue to try to sell her things. Doris says, “No you can’t,” meaning “I will not let you,” and she hangs up the phone.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Doris: Hello.
Telemarketer: Hello, may I speak to the lady of the house?
Doris: What is this regarding?
Telemarketer: I’m calling from Cheetam Cable Company and we have a very special offer. This month only, you can get a bundle of services for the low, low price of $69.99! This offer...
Doris: Thank you, but I’m not interested.
Telemarketer: But that’s because you haven’t heard the rest of the offer yet. If you sign up today, you will get at no extra charge, all of the equipment you’ll need to switch to our cable company.
Doris: As I said, I’m not interested. I’m also on the national do-not-call registry and I want to be taken off your call list.
Telemarketer: If you’re on my list, it means you have a prior relationship with our company and telemarketers are allowed to call you. Now about that special offer...
Doris: I don’t want to hear your sales pitch. I demand to be taken off your call list and I don’t want to get any more calls from your company.
Telemarketer: Is that a “no” on the special offer?
Doris: Yes, that’s a “no” on the special offer and a “no” on getting any more calls from your company. Do I make myself clear?
Telemarketer: Yes, very clear. If you’re not interested in our special offer, I can tell you about our other services...
Doris: No you can’t! [Hangs up the phone]
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
Comprehension Questions
1. What does a telemarketer do?
a) Sell things over the phone.
b) Work at the check-out counter in the supermarket.
c) Fix television sets.
2. Why is Doris so unhappy to receive this phone call?
a) She doesn’t like to watch cable television.
b) The telemarketer asked her a personal question.
c) She had asked to be placed on the do-not-call registry
Answers at bottom.
What Else Does It Mean?
bundle
In this podcast, the word “bundle,” refers to a group of individual services that are offered at one price: “The new company has a bundle of services, which includes Internet, phone, and cable services for $50 a month.” A bundle can also be a number of things tied together: “Uwe untied the bundle of newspapers to look for yesterday’s business section.” A bundle is also a slang term for a large amount of money: “Going out to dinner and a movie can often end up costing a bundle!” Many American parents will refer to their small child as a “little bundle of joy”: “My little bundle of joy will celebrate his second birthday next week!” To say someone is a “bundle of laughs” is to say that they are generally happy and easy to get along with: “Everyone just loves having Natalia around. She is a real bundle of laughs.”
To switch
The phrase, “to switch,” in this podcast means to change from using one company’s services to using the services of a different company: “Mr. Kim switched phone companies just last month and has already saved $20.” To switch can also mean to change or exchange something very suddenly: “The twins quickly switched name tags to confuse their teacher.” A switch can also be a small device used to turn something on and off, most commonly lights and electronics: “Could you turn on the light? The switch is by the door.” Or: “I can’t find the switch to turn on this radio.” A switch can also be a thin stick used to hit people or animals as a punishment: “In the story, when the boy behaved badly, his father hit him with a switch.”
Culture Note
Telemarketing is a sales “technique” (way something is done; method) used by many American companies to “promote” (sell; make known) their products or services. Telemarketing, or sales by phone, is an industry that “grosses” (earns) over 200 billion dollars a year in the U.S.
Traditional businesses are not the only ones who use telemarketing; many other types of organizations in the U.S. also use this powerful tool to their advantage. “Charities” (organizations that make no profit) use phone calls as a way to raise both money and “awareness” (making something known) for their “cause” (what someone believes in and works for). Political parties and “candidates” (a person who runs for a political position) also use telemarketing to raise “campaign funds” (money for a candidate to advertise, travel, pay employees, etc.) so that they can be elected or re-elected. Often, “market research firms” (companies that make money researching what people like and dislike) will also call customers at home and ask them a series of questions known as a survey; however, these calls do not involve the sale of a product or service.
Businesses and organizations, while very different, all use similar telemarketing techniques. Most calls made by telemarketers are made by “predictive dialing,” where a computer, rather than a person, dials a phone number. After a few rings, the computer will “turn the call over” (give the phone) to an available telemarketer. The telemarketer will then ask to speak to the head of the household, and the call will go forward from there, with the telemarketer often immediately “launching” (starting; beginning) into his or her sales pitch.
Because many Americans are annoyed by “unsolicited” (unwanted) calls, there are a few rules governing telemarketing practice in the U.S. Telemarketers must give their name and the name of their company if the person on the other end requests that they do so. Telemarketing calls can only be made between the hours of 8 a.m. and 9 p.m., which unfortunately still does not prevent the unwanted phone call in the middle of dinner!
Comprehension Answers
1 - b
2 - c