= 1254
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,254 – Being Under a Corrupting Influence.
This is English as a Second Language Podcast episode 1,254. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast today – now! Do it! Just kidding. Please consider becoming a member. If you do, you can download the Learning Guide for this episode.
This episode is a dialogue between Ann and Elio about being influenced by people whose behavior, whose actions, are not always very good. Let’s get started.
[start of dialogue]
Ann: I don’t like our son watching those films and reading those books. They’re corrupting his mind.
Elio: I don’t like it either, but he’s old enough to read and watch what he likes without our interference.
Ann: But they’re brainwashing him! Those books and films are full of evil, perverted ideas.
Elio: They’re certainly blasphemous and profane. I agree with you. But what can we do? Maybe his interest in them will be short-lived.
Ann: Even if he loses interest, we’ll have to find a way to reverse the damage that’s been done. He’ll need to be deprogramed.
Elio: Maybe their effect will be short-lived, too. Deep down he’s a good kid. We both know that.
Ann: Yes, but those ideas are dangerous. I hope he doesn’t act on them.
Elio: Don’t even think it. That would spell disaster.
Ann: All right, I’ll only think good thoughts.
Elio: Good.
Ann: Where are you going?
Elio: I’m hoping for the best, but just in case, it doesn’t hurt to monitor what he’s saying on social media.
[end of dialogue]
Ann begins our dialogue by saying to Elio, “I don’t like our son watching those films and reading those books. They’re corrupting his mind.” “To corrupt” (corrupt) can have several different meanings. Here it refers to changing a person’s behavior – the way a person acts in a negative way, to influence someone so that he starts acting dishonestly, perhaps, or in a way that we don’t approve of.
Elio says, “I don’t like it either, but he’s old enough to read and watch what he likes without our interference.” “Interference” (interference) is used to describe a situation where someone is getting in our way or getting involved in our affairs, in our actions, in a way that we don’t want. The verb is “to interfere.” So, “interference” is when someone does something that either prevents someone from doing what he wants or changes what someone does in a way that that person isn’t very happy about. Elio doesn’t think that he and Ann can interfere in their son’s reading and film-watching.
Ann says, “But they’re brainwashing him!” “To brainwash” (brainwash) means to use some method of influencing the way someone thinks, usually in such a way that the person loses their own ability to think for himself. We usually associate “brainwashing” with some sort of political or religious leader who is making his followers, the people who believe in him, do things that they would not otherwise do. It’s always used in a negative sense – that is, we use the verb “to brainwash” when we are referring to someone who is influencing other people to believe things they would not otherwise believe on their own.
Ann says, “Those books and films are full of evil, perverted ideas.” “Evil” (evil) is the opposite of good. It means very bad, and is often used to refer to things that are perhaps the worst cases of some sort of ethical or moral “badness,” you might say. There is often a religious meaning to the word “evil.” “Perverted (perverted) refers to something that is unnatural, or we might say “abnormal” (abnormal). “Abnormal” is not normal, not usual. “Perverted” is often an adjective used to refer to sexual actions or sexual desires that are considered abnormal.
Elio says that these books “are certainly blasphemous and profane.” “I agree with you,” he says. “Blasphemous” (blasphemous) is an adjective used to describe something someone says against God or against religion in a very, I guess we would say, disrespectful way – in a not nice way. “Profane” (profane) can mean simply the opposite of “sacred” (sacred). “Sacred” refers to things related to God, and “profane” would refer to things related to human beings.
However, it also has another meaning which means the same as or something similar to “blasphemous,” which is not respectful of religion or religious teachings. “Blasphemous” usually refers to things said against God as a being, whereas “profane,” when it’s used in the negative sense, is something that is said against religion or religious teachings that, of course, are related to God in most belief systems. Elio says, “But what can we do? Maybe his interest in them will be short-lived.”
Elio isn’t sure what he and his wife can do about their son’s interest in these books. He says, “Maybe his interest in them will be short (short) – lived (lived).” “Short-lived” means lasting or going on for a very short amount of time – temporary. Ann says, “Even if he loses interest, we’ll have to find a way to reverse the damage that’s been done.” “To lose (lose) interest” in something is to no longer want to know more about it or no longer want to be involved with it. “To reverse” (reverse) can mean to go in the opposite direction – to go backwards instead of forwards, for example.
“Damage” (damage) is some negative effect on a person or a thing. “To reverse the damage” would be to take something that has been hurt or harmed and make it better again or return it to its previous healthy condition or state. Ann thinks their son may need to be “deprogramed.” “To deprogram” (deprogram) means to take someone who has been brainwashed, who has been convinced to believe things that he would not otherwise believe, and return that person to his original way of thinking – to reverse the damage of brainwashing, you could think of it as.
These terms, “brainwashing” and “deprogramming,” were quite popular, or at least you would hear them more often, in the 1960s and ’70s when, at least in the United States, there was a lot of news stories about “cults” (cults). “Cults” are usually religious groups that have beliefs and practices that are very different than the normal accepted common religious groups. You don’t hear people talking about “deprograming” as much anymore. In any case, Elio says, “Maybe their effect will be short-lived, too.” “Effect” here means result or consequence.
He says, “Deep down he’s a good kid.” “Deep down” is an expression we use to refer to something that is part of someone’s nature, or something that someone has even though it doesn’t look as though they have it. For example, we may describe someone as being “honest deep down” even though right now the person is lying or being dishonest. “Deep down” might also be used to describe what someone really believes or truly believes even though the person seems to be saying something different right now.
Ann says, “Those ideas are dangerous. I hope he doesn’t act on them.” “To act (act) on” something is to take something you believe and do something about it – to actually change your behavior based on something you think or believe in. Elio says, “Don’t even think it. That would spell disaster.” “To spell (spell) disaster (disaster)” means to have a very bad result or to create a very big problem. Ann says, “All right, I’ll only think good thoughts.” Elio says, “Good.”
Then Ann says, “Where are you going?” Elio responds, “I’m hoping for the best” – meaning, in this case, I hope our son is okay – “but just in case,” meaning if I am wrong about that, “it doesn’t hurt to monitor what he’s saying on social media.” “To monitor” (monitor) means to observe and watch something, especially when you are trying to make sure that nothing bad happens to that thing or even to that person. When you are in the hospital, the doctors and nurses will “monitor” your heartbeat, or perhaps your breathing, to make sure that nothing bad is happening to you.
“Social media” refers to websites and services online such as Facebook and Twitter, where people share their thoughts and photos with other people. “Social” refers to being part of a group, and “media” refers to ways of communicating or ways of transferring information or giving information, including photographs and movies, to other people.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Ann: I don’t like our son watching those films and reading those books. They’re corrupting his mind.
Elio: I don’t like it either, but he’s old enough to read and watch what he likes without our interference.
Ann: But they’re brainwashing him! Those books and films are full of evil, perverted ideas.
Elio: They’re certainly blasphemous and profane. I agree with you. But what can we do? Maybe his interest in them will be short-lived.
Ann: Even if he loses interest, we’ll have to find a way to reverse the damage that’s been done. He’ll need to be deprogramed.
Elio: Maybe their effect will be short-lived, too. Deep down he’s a good kid. We both know that.
Ann: Yes, but those ideas are dangerous. I hope he doesn’t act on them.
Elio: Don’t even think it. That would spell disaster.
Ann: All right, I’ll only think good thoughts.
Elio: Good.
Ann: Where are you going?
Elio: I’m hoping for the best, but just in case, it doesn’t hurt to monitor what he’s saying on social media.
[end of dialogue]
The effect of listening to our dialogues by our wonderful scriptwriter, Dr. Lucy Tse, will be to improve your English, and that’s a good thing.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
to corrupt – to change another person’s behavior in a negative way; to influence someone so that he or she begins behaving badly or dishonestly
* Too many politicians have been corrupted by money from large companies or organizations.
interference – unwanted involvement in one’s affairs; involving oneself in other’s business
* His parents’ interference is ruining his relationship with his new wife
to brainwash – to use powerful methods to change another person’s thoughts and opinions, especially to make that person more similar to the members of a particular group
* The school seems to be brainwashing students, filling them with values different from ours.
evil – very bad; the opposite of good; enjoying causing harm, injury, damage, and death
* Hannah believes that wearing garlic around her neck will protect her from evil spirits.
perverted – corrupted, abnormal, and sexually unacceptable
* Some men have a perverted interest in very young girls.
blasphemous – saying something against God or religion, or critical or disrespectful of God or religion
* Questioning the church’s teachings isn’t blasphemous if it’s motivated by true curiosity.
profane – not respectful of religion or religious teachings
* Our pastor considers these writings to be profane and urged members of our church to stop reading them.
short-lived – lasting for a short amount of time; temporary, not permanent
* The researchers used a new medication to improve the patient’s memory, but the effects were short-lived.
to lose interest – to stop being interested in something that one was interested in before
* Over the past few months, Kyle has lost interest in most of his old hobbies and friends. Do you think he has serious mental problems?
to reverse the damage – to undo the negative effects of something; to improve the condition of something so that it returns to its earlier condition or status
* Psychologists have tried to reverse the damage caused by his bad experiences during the war.
to deprogram – to reverse someone’s brainwashing, helping that person return to his or her original way of thinking
* In this movie, a group of rebels try to deprogram all the other humans who are being controlled by aliens.
effect – result; consequence; what happens as the result of something else
* The effects of sun exposure may include premature aging, wrinkles, and skin cancer.
deep down – felt very strongly deeply within oneself, without influence from others, often in a hidden way
* Shana pretends not to like Randall, but deep down she loves him.
to act on (something) – to have one’s behavior be motivated or controlled by something
* A lot of people dislike their husband or wife, but most of them never act on their feelings and try to hurt him or her.
to spell disaster – to be a very big problem; to have a very bad result
* If that hurricane continues on its current path, it will spell disaster for many coastal cities.
just in case – as a precaution; as a way to prepare for a possible bad situation
* We should have enough cash for the weekend, but let’s go to the bank and get some more just in case we need it.
to monitor – to observe and watch something, especially to track changes over time in an effort to keep something or someone safe
* The doctors taught Rebecca how to monitor her blood pressure and glucose levels.
social media – websites and smartphone apps that allow people to create profiles and interact with each other, such as Facebook and Twitter
* Social media can be a great way to stay in contact with old friends and classmates who live far away.
Comprehension Questions
1. What is the opposite of brainwashing?
a) Losing interest
b) Reversing the damage
c) Deprograming
2. What might be involved in monitoring what their son is saying on social media?
a) Asking his friends about their son’s words
b) Reviewing newspapers, TV, and radio for information about their son
c) Observing their son’s participation on several websites and apps.
Answers at bottom.
What Else Does It Mean?
to act on
The phrase “to act on,” in this podcast, means to have one’s behavior be motivated or controlled by something: “They’ve decided to act on the advice of their lawyer.” The phrase “to act (one’s) age” means to behave in ways that are expected or common among people of one’s biological age: “Stop whining and act your age! You sound like a four-year-old child.” The phrase “to act up” means to behave badly, especially when talking about children: “It’s so embarrassing when the children start acting up in the grocery store.” Finally, the phrase “to act (something) out” means to pretend that one is a particular person or character and act as he or she would, often as part of a play or performance: “The high school theater club will act out several popular fairy tales for young audiences.”
to monitor
In this podcast, the verb “to monitor” means to observe and watch something, especially to track changes over time in an effort to keep something or someone safe: “We need to carefully monitor sales to determine whether the marketing campaign has had any effects on sales.” The verb “to monitor” can also mean to spy on someone, or to secretly record someone’s movements, phone conversations, or Internet activity: “I think my actions are being monitored by the FBI.” As a noun, a “monitor” is a display screen, especially for a computer: “Many stock traders have computers with multiple monitors so that they can track prices of many different stocks at the same time.” Finally, a “monitor” is a person who observes an activity to make sure it is occurring correctly: “The election monitors watch out for voter fraud.”
Culture Note
Banned Movies
Although the United States “prides itself on” (is very proud of having or doing something) “freedom of speech” (the idea that there are no governmental controls over how people and the media express themselves), many movies have been “banned” (prohibited; forbidden; not allowed to be seen or sold).
Sometimes movies have been banned because people were “shocked” (surprised in a negative way) or made to feel uncomfortable by what they saw “on the screen” (in the film). For example, Scarface, a 1932 film, was banned because people thought it “glorified” (made something seem more glamorous or admirable than it actually is) “crime” (breaking the law) and “violence” (actions that hurt or kill others). And a 1954 “documentary” (a film that presents information about real life, not a movie for entertainment) called The Vanishing Prairie was banned in New York because it “depicted” (showed) the birth of a “buffalo” (a very large animal, similar to a bison or a very large bull).
Other films have been banned for religious reasons. For example, The Last Temptation of Christ was banned for six weeks because it told a very different, and for some people, very “disturbing” (troubling) story of Jesus Christ’s life and final days. And Monty Python’s Life of Brian was banned for “making fun of” (causing people to laugh at) Christianity.
A film called The Birth of a Nation is “heralded” (praised) for its “innovative” (new, better than previous versions) “cinematic” (related to movies) techniques, but it was banned for its “content” (what a movie or book is about) because it depicted the “Ku Klux Klan” (an organization of those who want only white people to have power and oppose equal rights for non-whites) as “heroes” (the good people in a story) and black people as “villains” (the bad people in a story).
Comprehension Answers
1 - c
2 - c