= 1278
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,278 – Applying to a Selective School.
This is English as a Second Language Podcast episode 1,278. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com for more information about our episodes. This episode is a dialogue between Sam and Yasmin about going to a good school. Let’s get started.
[start of dialogue]
Sam: I think our child should go to a public school. I did.
Yasmin: I went to a private prep school and I think it gave me a leg up in life.
Sam: I got where I am without a fancy prep school.
Yasmin: And that’s great, but I think we should give our daughter every advantage we can.
Sam: What do you have in mind?
Yasmin: I have information here from a few of the most selective schools. Some are parochial and some are secular. Some are day schools and some are boarding schools.
Sam: I’m not sending my daughter to a boarding school and that’s final.
Yasmin: But some of the most exclusive schools are boarding schools.
Sam: I’m not budging on that. I want her coming home every day.
Yasmin: All right. Let’s look at the admission criteria for the remaining schools. Wow, admission is really competitive. These have very low admission rates.
Sam: Really?
Yasmin: Really. They also require two aptitude tests in addition to transcripts, letters of recommendation, and an interview.
Sam: Do we really want to put our daughter through that? And look at the tuition!
Yasmin: Is that for all four years?
Sam: No, for one year.
Yasmin: You’re kidding.
Sam: I’m not. Public school is sounding better and better, isn’t it?
[end of dialogue]
Sam begins our dialogue by saying, “I think our child should go to a public school. I did.” In the United States, a “public (public) school” is a school run by and paid for by the government. When I say the “government,” I’m referring to the local government usually, but public schools in all cases are schools that are run by the government. That’s in American English. In British English, a “public school” is what we would call a “private school.”
A “private (private) school” is a school that is not run by the government. It might be run by a church or another organization. It might be run by a business. “Private schools” are any schools that are not run by the government. In British English, a “private school” is called a “public school,” and a “public school” is called a “government school.” It’s a little confusing. In U.S. English, however, “public school” refers to a school run by the government. “Private school” refers to a school run by some organization or group or businesses other than the government.
Sam says that he wants his child to go to a public school. Yasmin says, however, “I went to a private prep school and I think it gave me a leg up in life.” A “prep (prep) school” is also known as a “preparatory school.” It’s supposed to be a school that is more difficult, that prepares you better to go to college. Yasmin says she went to a “private prep school” and that school “gave her a leg (leg) up in life.” “To be given a leg up in life” means to have an advantage over other people, to have something that allows you to be more successful in life – and certainly, a good education can help you “get a leg up in life,” though not always. Look at me.
Sam says, “I got where I am without a fancy prep school.” Notice Sam uses the adjective “fancy” (fancy) here. “Fancy” refers to something that is expensive or something that is for people with a lot of money. We use that adjective “fancy” in other circumstances to mean slightly different things, but here I think Sam is using it almost as an insult to say that he doesn’t need, nor does his daughter need, a “fancy prep school.”
Yasmin says, “And that’s great,” meaning it’s great Sam was able to do well without going to a prep school. She says, however, that she thinks “we should give our daughter every advantage we can.” Sam says, “What do you have in mind?” Yasmin responds, “I have information here from a few of the most selective schools.”
A “selective (selective) school” is a school that is what we would describe as very “competitive,” meaning lots of people want to get into the school, and it is difficult to get “admitted to” or be allowed to attend that school. “Selective schools” usually only take a small percentage of the students who want to get into the school. If a school is very good – like, say, Harvard or Yale here in the United States, when referring to universities – those schools would be described as “selective” because many students want to go there but only a few are able to actually attend.
Yasmin says, “Some,” meaning some of the schools, “are parochial and some are secular.” A “parochial (parochial) school” is a school for children that is owned and run by or operated by a church, typically. The word “parochial” comes from the word “parish,” which usually refers to a local church, a church in a certain area – a Christian church, typically, and most commonly a Catholic church. A “secular (secular) school” is a school that is not related to any religion or church. It is what we might describe as “non-religious” – not religious.
Yasmin says, “Some are day schools and some are boarding schools.” A “day (day) school” is a school that you send your child to during the day and then your child comes back to your house and lives with you, typically. A “day school,” that is, doesn’t provide a place for students to sleep and eat. If it did, we would call that a “boarding (boarding) school.”
Boarding schools are places that have rooms where students live during the school year, and you, of course, send your child to a boarding school and you don’t see your child until the end of that particular term or semester. Boarding schools are not very popular in the United States, though there are still boarding schools here in the U.S. They are more popular, at least among very rich families, in places such as England. In the U.S., there is a tradition of boarding schools especially on the eastern coast of the U.S. They’re not as common here in California, but they do still exist.
Sam says, “I’m not sending my daughter to a boarding school and that’s final,” meaning he’s not going to change his mind. Yasmin responds, “But some of the most exclusive schools are boarding schools.” “Exclusive” (exclusive) means available only to a small number of people, and very desirable. “Exclusive” refers to a group, a club, or a school that only a small number of people can be a part of. Sam says, “I’m not budging on that.” “To budge” (budge) means to change your opinion or your position about something. Sam is “not budging” on his opinion, meaning he’s not going to change his opinion about sending his daughter to a boarding school. He is not going to do that.
He says, “I want her coming home every day,” meaning coming back to their house. Yasmin says, “All right. Let’s look at the admission criteria for the remaining schools.” “Admission (admission) criteria (criteria)” are the requirements that a student must meet or must have in order to get into or be admitted to a school. If you want to go to Harvard or Berkeley here in the U.S., you must meet their “admission criteria,” which usually includes having very good grades, having good test scores, and so forth.
Yasmin and Sam are looking at the admission criteria for these schools for their daughter. Yasmin says, “Wow, admission is really competitive.” “Competitive” (competitive) means many people are trying to get something or do something. A “competitive school” is a school to which many students are applying – many students want to go to that school. A school that is competitive is usually a school that is also “selective,” meaning the school only takes a certain number of students.
Yasmin notes that the schools she and Sam are looking at have “very low admission rates” (rates). The “admission rate” of a school is the percentage of students that it accepts of the students who apply. So, if a school has a 10 percent admission rate, that means that for every 100 students that want to go to that school, the school only accepts 10.
Sam says, “Really?” Yasmin says, “Really,” referring to the low admission rates. She says, “They also require two aptitude tests in addition to transcripts, letters of recommendation, and an interview.” The requirements, then, for the schools that Sam and Yasmin are interested in are two aptitude tests, transcripts, letters of recommendation, and an interview.
An “aptitude (aptitude) test” is a test that is supposed to test or give an indication of your ability to do something. We used to distinguish between “aptitude tests” and “achievement tests.” An “achievement test” is a test that looks at how much you know based on what you studied or what you have read. An “aptitude test” is supposed to somehow indicate your ability to do something even if you haven’t studied it yet.
A lot of psychologists now question whether aptitude tests are really able to test someone’s ability to do something in the future without actually having tried it, but that’s what “aptitude” is. It’s your ability to do something. Aptitude is something that, at least according to some scientists, you are born with and therefore you cannot change. In any case, these schools “require two aptitude tests, in addition to transcripts” (transcripts).
A “transcript” is an official piece of paper or document that lists, or puts down, all of the classes that you have taken as a student and the grade that you received, or the mark that you received. “Letters of recommendation” are letters written by people who know you as a student – or in this case, your daughter – and can speak to or give information about how good a student she is. An “interview” (interview) is, of course, when someone sits down and asks you questions about things.
Sam says, “Do we really want to put our daughter through that?” “To put someone through” something means to make someone do something difficult or something that might require effort or even pain. Sam then says, “Look at the tuition!” The “tuition” (tuition) of a school is how much it costs to go there, what the price is. Yasmin says, “Is that for all four years?” meaning the tuition that they are looking at. Sam says, “No, for one year.”
Many private schools in the U.S. can be very expensive. I mean, in some schools here in Los Angeles, it can cost $15,000 a year to send your child to a selective school, often more than it costs to send someone to a year of college. Yasmin and Sam are obviously very surprised at the cost, the tuition of the schools they have been looking at for their daughter. Yasmin says, “Is that for all four years?” And Sam says, “No, for one year.”
Yasmin then says, “You’re kidding,” meaning you’re joking. Sam says, “I’m not. Public school is sounding better and better, isn’t it?” He means maybe because these other schools are so expensive, it would be better to send their child – and certainly cheaper to send their child – to a public school. Public schools are supposed to be free in the United States. The government doesn’t charge you or make you pay money to send your child to a public school.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Sam: I think our child should go to a public school. I did.
Yasmin: I went to a private prep school and I think it gave me a leg up in life.
Sam: I got where I am without a fancy prep school.
Yasmin: And that’s great, but I think we should give our daughter every advantage we can.
Sam: What do you have in mind?
Yasmin: I have information here from a few of the most selective schools. Some are parochial and some are secular. Some are day schools and some are boarding schools.
Sam: I’m not sending my daughter to a boarding school and that’s final.
Yasmin: But some of the most exclusive schools are boarding schools.
Sam: I’m not budging on that. I want her coming home every day.
Yasmin: All right. Let’s look at the admission criteria for the remaining schools. Wow, admission is really competitive. These have very low admission rates.
Sam: Really?
Yasmin: Really. They also require two aptitude tests in addition to transcripts, letters of recommendation, and an interview.
Sam: Do we really want to put our daughter through that? And look at the tuition!
Yasmin: Is that for all four years?
Sam: No, for one year.
Yasmin: You’re kidding.
Sam: I’m not. Public school is sounding better and better, isn’t it?
[end of dialogue]
Knowing English will give you a leg up in life, and the best way to improve your English is to listen to the wonderful scripts by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
public school – a school designed to serve all students in a particular area, owned and operated by the government, usually free to attend
* Public schools need to emphasize science and mathematics if we want our economy to continue to grow in the next few decades.
private school – a school owned and operated by a private business or a organization, usually with families paying for their children to attend
* The private school offers excellent educational opportunities, but only the wealthiest families can attend.
prep school – preparatory school; a challenging and difficult school designed to help students prepare for college
* This prep school reports that 70% of its students have been accepted to the country’s top 10 universities.
a leg up in life – an advantage over other people; something that allows one to compete more easily and to become more successful in life
* Does being born very handsome or beautiful give people a leg up in life?
selective – very competitive, admitting only a few people into a program, or giving only the most qualified people an opportunity to have, do, or participate in something
* Our organization is very selective and only admits people who have scored at the highest levels on intelligence tests.
parochial – owned and operated by a church
* The parochial school is led by the minister.
secular – not related to religion or a church; non-religious
* Chelsea is very religious and seldom listens to secular music on Sundays.
day school – a school that provides instruction to students during the day, with students returning home in the evening
* Their day school ends at 3:20 each afternoon, but on most days, they have after-school activities until dinnertime.
boarding school – a school that provides instruction and housing to students who live on campus, not returning home very often, or maybe returning home only on weekends or holidays
* I could never send my daughter to boarding school. I would miss her too much!
exclusive – highly desired and available to only a small group of people
* This is an exclusive offer only available to current members of the military.
to budge – to change one’s position, stance, or opinion in some small way; to be flexible and willing to adapt or compromise
* We tried to negotiate a lower price, but the car salesman wouldn’t budge.
admission criteria – the requirements that students must meet in order to study at a school or university
* The admission criteria include good student grades and high test scores.
competitive – with many people trying to have or do something that will be made available only to the top performers
* Positions at the top law firms are highly competitive, with hundreds of applicants applying for each job.
admission rate – the percentage calculated by dividing the number of people who are invited into a program by the number of people who apply for it
* Our university has an admission rate of 10%, meaning that just 10 out of every 100 applicants are invited to enroll at the university.
aptitude test – an exam of one’s skills, abilities, or knowledge
* If these applicants pass our aptitude tests, they’ll be invited in for interviews.
transcript – an official document listing all the classes taken by a particular student, including when they were taken, who taught them, and what grade the student received
* Jake’s transcripts show that he failed Organic Chemistry the first time.
letter of recommendation – a written document that praises someone’s abilities and characteristics, written to support that person’s application for something
* Could you write me a letter of recommendation to help me get that job?
interview – a conversation between an applicant and one or more people representing an employer or academic institution, used to determine whether he or she should be offered the job or enrollment in a program
* A common job interview questions is, “Why did you leave your last job?”
tuition – the cost of studying for one term or one year at a particular school or university; the amount of money paid to be a student
* Tuition will be your biggest expense next year, but don’t forget about housing, food, and books, too.
Comprehension Questions
1. Which of these would probably cost the least for students to attend?
a) A public school
b) A private prep school
c) A boarding school
2. What does Yasmin mean when she says, “admission is really competitive”?
a) The school is very expensive.
b) It’s very difficult to be admitted to the school.
c) The curriculum is extremely difficult.
Answers at bottom.
What Else Does It Mean?
private
A “private school,” in this podcast, is an academic institution designed to serve a small group of students, owned and operated by a private business or a nonprofit organization, usually with families paying for their children to attend: “Private schools offer a good education, but the students rarely interact with children from poor families.” A “private eye” is a detective or an investigator hired by an individual: “Gwendolyn hired a private eye to follow her husband and determine whether he was cheating on her.” Finally, the “private sector” refers to all for-profit businesses, and not government or nonprofit organizations: “The government struggles to hire good computer programmers, because they can earn so much more money by working in the private sector.”
interview
In this podcast, the word “interview” means a conversation between an applicant and one or more people representing an employer or academic institution, used as part of the selection process: “Last week I had an interview with the hiring manager, and tomorrow I’ll have an interview with the company’s executive director.” An “informational interview” is a conversation in which a student or an inexperienced person speaks with someone working in an interesting job or industry in order to learn more about his or her experience and make appropriate educational decisions: “If you think you’re interested in consulting, try to set up a few informational interviews with consultants in your field.” Finally, an “exit interview” is a conversation between an employer and a person who is quitting: “During the exist interview, employees are asked to explain their reasons for leaving the company.”
Culture Note
Charter Schools
“Charter schools” are schools that receive “public funding” (money from the government) but operate outside of the public school system. In other words, they receive money from the government, but they are not operated or controlled by the government. The schools operate under a “charter” or agreement between the school and a group of families or a nonprofit organization that has specific educational “objectives” (goals).
Most charter schools are formed because people believe that they can better teach a particular group of students. For example, some charter schools are designed to help students who are likely to “drop out” (stop going to school before a degree is earned) of a public high school. Charter schools are able to “experiment with” (try new and different things) different “educational models” (ways of teaching) more easily than public schools can.
Charter schools invite students to “enroll” (enter an academic program) through a “lottery process,” meaning that interested students can fill out an application and they are selected “randomly” (with each person having an equal likelihood of being selected). The students applying to charter schools usually have to be “residents” (people who officially live somewhere) of the particular neighborhood that the charter school serves.
Some charter schools have reported “phenomenal” (very good and impressive) “achievements” (accomplishments), but others have been “abysmal” (very bad) “failures” (not successful). Because it is difficult to “measure” (assess and evaluate) educational “outcomes” (results), charter schools are “controversial” (with strong opinions on either side of an issue), and some people think that charter schools unfairly “drain” (take away) money from public schools.
Comprehension Answers
1 - a
2 - b