= 1294
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,294 – Chaperoning a Field Trip.
This is English as a Second Language Podcast episode 1,294. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
This episode is a dialogue between Rupi and Antonia about two people going with a group of students, two adults going with a group of younger students, to make sure that they behave, that they don’t do anything wrong on a field trip – a short trip, usually, from school to somewhere that is educationally interesting for students. Well, I’ll explain more when we get started. So let’s get started.
[start of dialogue]
Rupi: I don’t think I’m cut out for this. How am I supposed to chaperone a class of students on a field trip?
Antonia: I thought you were gung-ho about being a chaperone for Nadia and the rest of her class on their trip to the children’s museum. That’s why you volunteered.
Rupi: I was, but then I started reading this material the school sent me to prepare for the trip. I have so many duties.
Antonia: Like what?
Rupi: I’m supposed to supervise the children all the time, escorting them to the restrooms and making sure they don’t misbehave. I don’t know what to do if the kids get out of hand.
Antonia: It’s not an overnight trip, just a morning at the museum.
Rupi: I know, but I’m responsible for their safety. What if I have to give first aid?
Antonia: The teacher will be there. He’ll know what to do in a real emergency.
Rupi: But how am I supposed to keep track of so many kids?
Antonia: Not all of the students are going on the trip, just the ones with signed permission slips.
Rupi: Even so, it’s a big responsibility. There are so many things that can go wrong.
Antonia: Do you want me to go in your place?
Rupi: Yes! No, I already told Nadia I’ll be going and she’s really excited. I don’t want to disappoint her.
Antonia: You’ll be absolutely fine. I’m sure it won’t be like last time.
Rupi: Last time?
Antonia: Never mind. Forget I mentioned it.
[end of dialogue]
Rupi begins by saying, “I don’t think I’m cut out for this.” The phrasal verb “to be cut (cut) out (out) for” something means to have the right experience or preparation to deal with something or handle something. More generally, it can mean simply to be prepared for something, or perhaps to have the natural ability to do something. Rupi says he’s not cut out for this. This is, we find out, chaperoning a class of students on a field trip. “To chaperone” (chaperone) means to supervise or be responsible for another person or group, especially a group of children or teenagers.
We call the person who chaperones a “chaperone.” As a noun, it’s the person. As a verb, it’s the act of supervising or taking care of usually a group of younger students. These students are on a “field (field) trip (trip).” A “field trip” is usually when a group of students goes to a certain place in their city or town for several hours as part of their education. It might be a trip to a museum. It might be a trip to a park, or a place where they learn about nature and science. Field trips are popular in American schools – at least, they’re popular with students. It’s a time for students to leave the school and learn about their world, learn about something perhaps they’re studying in another place.
Antonia says, “I thought you were gung-ho about being a chaperone for Nadia and the rest of her class on their trip to the children’s museum.” So this field trip is to a children’s museum. Antonia says that she thought Rupi was “gung-ho.” “Gung (gung) – ho (ho)” is a somewhat unusual expression we use in American English to mean very enthusiastic or excited about doing something.
Someone who is “gung-ho” about his job or about a certain project is very excited about doing it, very “eager” (eager) about doing something. The expression apparently comes from a rather poor pronunciation of a Chinese expression that was used by some American soldiers during World War II. I believe the original expression had to do with working together. In any case, in American English, it means to be enthusiastic about doing something.
Antonia thought Rupi was enthusiastic about being a chaperone for his daughter’s class trip to a museum. She says, “That’s why you volunteered.” “To volunteer” (volunteer) is to offer to do something without being paid for it or without being required to do it. A person who volunteers is called a “volunteer.” So once again, it can be a verb or a noun. Rupi says, “I was, but then I started reading this material the school sent me to prepare for the trip.”
Rupi says he was gung-ho, but now he is not because he had to read all of this material and he discovered something. He discovered that he has a lot of duties as a chaperone. “Duties” (duties) is the plural of a “duty” (duty), which means a task or a responsibility, something that you are expected or required to do, usually as part of your job. Antonia asks Rupi for some examples of these duties. That’s what she means when she says, “Like what?” meaning give me some of these duties.
Rupi says, “I’m supposed to supervise the children all the time.” “To supervise” (supervise) a group of people or a person means to monitor or to be responsible for someone’s behavior, to be making sure that a person does what he is supposed to do – in this case, to make sure the children are doing what they are supposed to do, which of course is not easy depending on how old the children are and whether they are good children or bad children. My neighbor’s children, for example, are bad children. I would not want to supervise them. But back to our story.
Rupi has to also escort the children to the restrooms. “To escort” (escort) means to go with another person to make sure he is safe or to make sure that he does what he is supposed to do. Usually, however, “to escort” a person means to go with the person for his protection and safety. There is a noun that comes from this verb “escort.” The accent is on the first syllable. An “escort” is a person who is escorts another person to protect that person. However, the noun “escort” can also mean something different. It can also refer typically to a woman who is paid to go with a man to do certain things – to be their friend, but perhaps a little more than that, if you understand my meaning.
Well, here we’re not talking about escorts. We’re talking about “escorting” children to the restrooms or the bathrooms and making sure the children do not “misbehave.” “To misbehave” (misbehave) means not to do what you are supposed to do. That prefix “mis” (mis) means “not.” “To behave” means to do or act the way you are supposed to, following the rules. “To misbehave” means to do the opposite, not to follow the rules.
Rupi says, “I don’t know what to do if the kids get out of hand.” The expression “to get out of hand” means for a situation to not be controllable or to be unmanageable. If a situation “gets out of hand,” you are no longer able to control it or to prevent it from getting worse. Rupi is worried about what he’ll do if the kids get out of hand. Antonia says, “It’s not an overnight trip, just a morning at the museum.” “Overnight” (overnight) means from one day to another. In this case, it would involve staying with the children over the nighttime.
Antonia is saying that it is not an overnight trip. It’s just a few hours in the morning at a museum. In other words, it shouldn’t be that difficult. Rupi says, “I know, but I’m responsible for their safety.” “Safety” (safety) is the opposite of danger. It’s to be protected from bad things happening to you. “What if I have to give first aid?” Rupi asks. “First aid” (aid) is medical help you give someone that isn’t very serious but has to be done because of an accident or perhaps a sudden illness. “First aid” might include doing things to help a person until a real doctor or a paramedic arrive. Antonia says, “The teacher will be there. He’ll know what to do in a real emergency.”
Rupi says, “But how am I supposed to keep track of so many kids?” The expression “to keep track (track) of” something or someone means to pay attention to and know the location of people. In this case, the kids have to be kept track of. We have to know where they are at all times. Sometimes we use this expression “to keep track of” to mean simply to keep records of or to know about, to monitor.
Antonia says, “Not all of the students are going on the trip, just the ones with signed permission slips.” Most schools, in order to take the children on a field trip outside of the school building, get the permission of the parents. The parents have to sign a piece of paper, a “slip” (slip) of paper, that gives the school “permission” (permission). “Permission” is the same as an okay, saying yes, it’s okay for my child to go on this trip. Rupi says, “Even so,” even if we consider all of those facts, “it’s a big responsibility. There are so many things that can go wrong.”
Antonia then asks, “Do you want me to go in your place?” In other words, I will go instead of you. Rupi says, “Yes!” But then he realizes he’s made a mistake and immediately follows by saying, “No, I’ve already told Nadia,” his daughter, “I’ll be going and she’s really excited. I don’t want to disappoint her.” Antonia says, “You’ll be absolutely fine,” meaning everything will be okay. “I’m sure it won’t be like the last time.” Now, we don’t know what Antonia is referring to, what she’s talking about. Presumably, we can guess the last time there was a field trip perhaps there was some problem.
Rupi says, “Last time?” He wants to know what the problem was that happened on the last field trip, probably one that Antonia was on. Antonia says, however, “Never mind.” That phrase, which is quite common in American English, means “I don’t want to give you any more information,” “I don’t want you to keep asking me about this topic,” or simply, “I don’t want to repeat what I just said because I don’t want to talk about it anymore.” Antonia says, “Never mind. Forget I mentioned it,” meaning forget the fact that I just said that there was, or at least I suggested that there was, a problem last time.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Rupi: I don’t think I’m cut out for this. How am I supposed to chaperone a class of students on a field trip?
Antonia: I thought you were gung-ho about being a chaperone for Nadia and the rest of her class on their trip to the children’s museum. That’s why you volunteered.
Rupi: I was, but then I started reading this material the school sent me to prepare for the trip. I have so many duties.
Antonia: Like what?
Rupi: I’m supposed to supervise the children all the time, escorting them to the restrooms and making sure they don’t misbehave. I don’t know what to do if the kids get out of hand.
Antonia: It’s not an overnight trip, just a morning at the museum.
Rupi: I know, but I’m responsible for their safety. What if I have to give first aid?
Antonia: The teacher will be there. He’ll know what to do in a real emergency.
Rupi: But how am I supposed to keep track of so many kids?
Antonia: Not all of the students are going on the trip, just the ones with signed permission slips.
Rupi: Even so, it’s a big responsibility. There are so many things that can go wrong.
Antonia: Do you want me to go in your place?
Rupi: Yes! No, I already told Nadia I’ll be going and she’s really excited. I don’t want to disappoint her.
Antonia: You’ll be absolutely fine. I’m sure it won’t be like last time.
Rupi: Last time?
Antonia: Never mind. Forget I mentioned it.
[end of dialogue]
It’s hard not to be gung-ho about improving your English after listening to the wonderful scripts by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2017 by the Center for Educational Development.
Glossary
to be cut out for (something) – to be prepared for something; to have the right skills, experience, and preparation to deal with something or to handle something
* I’m not cut out to be a firefighter. It’s too stressful.
to chaperone – to supervise and be responsible for the well-being of a person or group, especially a group of children or teenagers
* The school is asking for volunteers to chaperone students at the dance.
field trip – a trip (less than one day) in which a group of students go somewhere together with their teacher to learn something educational
* The kindergarteners went on a field trip to the zoo.
gung-ho – very enthusiastic, eager, and excited about doing something
* Everyone was gun-ho about the project until they realized how much work would be required.
to volunteer – to offer to do something without receiving pay when one is not required to do it
* Meggie enjoys volunteering at the animal shelter, where she helps to feed the cats and dogs.
duty – a task or responsibility that one is expected or required to do, especially as part of a job
* The receptionist’s duties include answering the phones and distributing the mail.
to supervise – to be responsible for someone else’s performance or behavior; to monitor and guide someone’s behavior and work
* The bank manager supervises all of the loan officers, making sure that they perform their work correctly.
to escort – to walk or drive somewhere with another person, making sure that he or she is safe; to accompany someone to provide protection and security
* This laboratory has high security. When you arrive, the guards will escort you to my office.
to misbehave – to behave poorly; to break the rules; to do things that one is not supposed to do
* Students who misbehave will be sent to the principal’s office for punishment.
to get out of hand – to become out of control; for a situation to become unmanageable; to no longer be controlled or controllable
* At first Kath’s jokes were funny, but now they’re getting out of hand.
overnight – lasting one night; from one day to the next; throughout one night
* They took an overnight train and arrived in Denver early the next morning.
safety – one’s protection from danger, or a condition that keeps one protected and secure
* The university is trying to improve safety for students who live on campus.
first aid – assistance provided to someone who is injured until professional medical help is available
* Kengo saved Ayuki’s life by giving first aid until the ambulance arrived.
to keep track of – to pay attention and know the location and status of someone or something
* How do you keep track of all of your eight children’s appointments and events?
signed – with one’s signature; with one’s name written in a way that identifies the individual, especially to show acceptance or approval
* Doubara was thrilled to receive a signed copy of the latest book by her favorite author.
permission slip – a piece of paper that is signed by a parent and allows a child to participate in a particular activity
* If you don’t remember to bring a permission slip signed by your parents, you won’t be allowed to go to the farm with the rest of the class.
in (one’s) place – instead of another person; filling the role or duties of another person; switching places with another person
* I have a bad cold and have lost my voice. Could you give the sales presentation in my place?
never mind – a phrase used when one does not want to repeat what one has just said, or does not want to provide certain information, and wants the questioner to change the topic
* How much do you weigh? Oh, never mind. I shouldn't have asked.
Comprehension Questions
1. What does Rupi mean when he asks, “What if I have to give first aid?”
a) He’s worried there might be a medical emergency.
b) He’s worried the children won’t obey him.
c) He’s worried he might lose a student.
2. What does Rupi mean when he says, “I don’t know what to do if the kids get out of hand”?
a) He doesn’t know the names of the kids.
b) He doesn’t know how to punish kids for misbehavior.
c) He doesn’t know how to control the kids’ actions.
Answers at bottom.
What Else Does It Mean?
to get out of hand
The phrase “to get out of hand,” in this podcast, means to become out of control or for a situation to become unmanageable: “At first, we were excited to have snow, but these winter storms are getting out of hand.” The phrase “to have a hand in (something)” means to participate or be involved in something: “Did you have a hand in planning that surprise birthday party?” The phrase “to try (one’s) hand at doing (something)” means to try something for the first time, knowing that one might not succeed: “This year, I’m going to try my hand at cooking a Thanksgiving feast for my entire family.” Finally, the phrase “to ask for (someone’s) hand in marriage” means for a man to ask a woman to marry him: “He was only 18 when he asked for Zoe’s hand in marriage.”
signed
In this podcast, the word “signed” means with one’s signature, or with one’s name written in a way that identifies the individual, especially to show acceptance or approval: “This check is valid only if it’s signed by the account owner.” The phrase “a sure sign” is a very clear, easily understood indicator: “Those dark clouds are a sure sign that it’s going to start raining soon.” The phrase “sign of the times” refers to something that represents or emphasizes how people live now: “Unfortunately, people looking at their devices during a meal more than they look at their friends and family is a sign of the times.” Finally, the phrase “sign of life” is any sound or movement that indicates someone is alive: “The rescuers searched the collapsed building for any signs of life.”
Culture Note
Popular Types of Field Trip Destinations
Most schoolchildren “look forward to” (are excited and eager to do something) going on field trips with their classmates. Students usually don’t go very far, so the field trips vary based on where the school is located.
Probably the most common type of field trip is to go to a museum, especially a science museum or a history museum. Usually the students stay together as a group, and they “typically” (usually) have a “guide” (a person who leads a tour) who provides information about what the students are seeing. Students sometimes have lists of questions that they’re expected to answer as they learn about a particular topic.
Some field trips go to hospitals, police stations, or “fire stations” (buildings where firefighters and their trucks are when they’re not putting out a fire). These field trips allow students to learn about “first responders” (people who respond to emergencies, like police officers) and how they work to protect others.
Other field trips take children to “manufacturing facilities” (factories; places where things are made) or farms, where they can learn about the how the things that they use every day are produced or made. Many children are “fascinated by” (very interested in) how their food gets to the grocery store or how their paper is made from trees.
Still other field trips are at government offices or “state capitol” buildings (where the state government operates). Students might get to meet with their “elected representatives” (people who are voted into office) as they learn how laws are made.
Comprehension Answers
1 - a
2 - c