
= 方向
:sectnums:
:toc:

---


==== ★★ 每一个赛场对于你是否"普通"或者"别致"的判断，都有不同的判定标准。你能进入那个特定的, 能看重你你自己价值的赛场, 你就赢; 进不去, 你的才能在那个赛场都不被看中, 只能沦为泯然众人.

你到了超市，打算点个鸡。 +
售货员指着面前三只扒干净了的老母鸡, 说, 这可都不是普通鸡，老母鸡A生前下蛋比别的鸡勤快；老母鸡B生前毛色炫丽；老母鸡C生前可厉害坏了，能跟公鸡一样天天打鸣...

你要旁边没做过介绍的内个老母鸡D。售货员笑说，得加钱。

你问售货员： +
这只毛色更炫丽吗？售货员说不。
下蛋更勤快吗？售货员说不。 +
也会和公鸡一样打鸣吗？售货员说不。 +

你说这只这么普通，凭什么叫我加钱？ +
售货员笑着说，你指出来的几方面，这只鸡确实普通。可它是个精料喂出来的地走鸡啊，肉质跟另外几只不一样。你买回家煲汤不就是求个肉质鲜美？所以跟它比起来，另外几只才是普通鸡。

于是你悟了，何止是鸡，哪怕是世界上每个独一无二的人，放在特定环境里，个个都是普通鸡。

你小时候你手脚麻利勤快。街坊四邻看见你三五岁就开始帮你妈做家务，都觉得这不是个普通孩子。当时的你像极了内个下蛋勤快的鸡A。

上学以后你出落的蛮漂亮。不但仰慕者众多，历次做汇报演出你都是没有争议的舞台C位。舞台下边的校领导们交头接耳，说你不是个普通孩子。当时你像极了内个毛色炫丽的鸡B。

考验之后你发愤图强。男生能在自习室蹲8个小时，你能除了睡觉都在自习室清修。老师们知道了交口称赞谁说女子不如男，这不是个普通孩子。当时你像极了内个牝鸡司晨的鸡C。

你回忆起人生的各个阶段，你都曾经不普通过，因为每个阶段的大环境，引导环境里所有人关注到你与众不同的特质。

可是**你后来走上社会了。你发现老板才不会关注你之前的那些人生阶段里是否有勤劳，是否有绚烂，是否有努力。他只关注肉质鲜美。你没有,  你在这就只适合当个螺丝钉。**

*人的一生，每个生命从生到死，都会经历若干个赛场. 每一个赛场对于你是否普通或者别致的判断，都有不同的判定标准。 +
如果你有本事，在那个“可以证明你不普通”的赛场里浸淫一生，你就是成功的. 如果你没做到, 则泯然众人是每个人最终的归宿。*

---

我见过一个人的简历, 上学时可谓出类拔萃, 中考在学校第一名, 拿过各种作文比赛一等, 二等奖项, 可谓人才. 但工作后, 十几年, 做的却是经营公司公众号. 我看得真是很感慨.

也想起那些在中学, 大学时学习刻苦优秀的人, 工作后如果只能找到一个普通岗位的话, 那真的是"泯然众人矣". 不是我们主动"泯然"的, 是在人的最关键时刻, 在特定时间, 特定空间中, 被社会没有那么多符合你特长的优秀岗位所"泯然"的.




---

==== 一旦选错职业，随着该职业要求越来越高, 就离你真正想去的方向距离越来越远。

一旦选错职业，就像坐上了开往远离你内心向往的中心的，**朝向四面八方远去的火车，这些工作职业要求越来越高**（如设计工作的要学软件越来越多化，工具人化，大脑智慧理论学习被剥夺时间化），**就离你心中的方向距离越来越远。**

**每个职业, 就像坐上不同的火车, 会最终把你带向不同的远方, 而远离你真正想去的地方.**  当你没有及时换车时, 就会错过所有的换车年龄机会, 结果到最后只会被你乘错的火车, 带往你不想去的地方.

好的职业 (老师, 公务员, 医生, 律师), 他们的火车能将他们带往更有前景的职业未来. +
而坏的职业(私人公司中的绝大部分职业), 只会把你当做暂时零件 来看待, 并且等你年龄大了之后就等于是被报废的零件, 会被换掉.

---

==== 非"上岸"的行动, 都是幻觉

**任何你做的没上岸的工作和工作内容，那些不会改变你原有的人生轨道的行为，这些行为一切都是幻觉！** 正如古人所说，“回想过往如梦”。
**当你在不喜欢的事上一天工作下来有充实感时，这种充实感其实是幻觉.**  +

**只有为了上岸而学习的必需技能（考研，数学，英语，金融专业知识，考证，考编），才是实实在在会改变你的人生轨迹的行动！这些才不是幻觉！**

---

*学会文武艺，货卖帝王家*  +
(进入体制内, 工作有了稳定性保障, 才能在生活中做你感兴趣的事情, 而不是被失业天天困扰, 心思放不进兴趣中)

---

==== 你之所以去做某件事，是因为其方向身是对的, 还是仅仅因为有把握做成它?

常常问自己：我之所以去做，是因为这事本身是对的(是你真正想去的方向)，还是仅仅因为有把握做成它(没有门槛, 却不是你的方向)？

---

==== ★ 时间只分为两种性质: 或花在"上岸行动"上, 或花在"对上岸没有帮助的行为"上
*你的时间可以划分成两部分，一部分是用于上岸的行动的时间，另一部分是花在“其他对上岸没有帮助的行为”的时间. 所以，你的行为花在某个事情上是否具有价值，只取决于它能否能帮你上岸。*

把你每天做的事情，记录列表下来，依次分析每件事情的性质，哪些事情是对上岸密切相关的，哪些事情是对上岸没有任何帮助的。然后所有与上岸没关的事情统统砍掉不要去做， 只做所有与上岸强相关的事情！

*每一个决定不是离成功越来越远, 就是离成功越来越近。*

---


==== ★★ 人的精力和时间, 只会花在两种地方上: 1.要么是第二曲线, 第三曲线, 思维模型的升级上;  2.要么是吃喝玩乐, 电脑游戏上面.

**人的精力和时间, 只会花在两种地方上: 1.要么是第二曲线, 第三曲线, 思维模型的升级上;  2.要么是吃喝玩乐, 电脑游戏上面. **

就像种田, 人的一生无论做什么, 他的时间只可能花在种两种田上面, 要么是种"大脑思维升级"(令你一辈子收益)的田, 要么是种"吃喝玩娱"(过了就没了, 没有任何大脑学习上的积累)的田.

人的一生, 年轻时最有精力和时间, 一定要花在思维模型的升级上, 分析商业案例, 企业发展生命周期, 数学, 数理模型的学习上, 因为这些成长, 是能令你终身受益的. +
而花在电脑游戏上, 吃喝玩乐的研究上,  都不会对改变你的头脑(思维升级)有任何积累. 只会令你浪费掉人生中最有精力和黄金年龄阶段的年轻时光而已!

---

==== 思维升级的课程, 最好把它们看做是能给你启发, 就像是走在一级级的楼梯上, 让你的思维见识慢慢的升高.

第二曲线, 分两步, 第一步是技能上做到头部5%, 第二步是大脑思维模型的升级上面(创业, 商业运营, 策略的系统性思考).  有些人说看混沌学院的课即使一节不落下, 其他什么都不会, HR也不会让你入职. 就是说明了, 现做到第一步, 第二步才能产生价值. HR只看重第一步. 他们当然理解不了你第二步怎样.

而且, 学习类, 思维升级的课程, 最好把它们看做是能给你启发,  而不要把它们看做是灵丹妙药, 吃一颗就能直接让你跨一大步, 改变命运. 所以, 这些课程, 就像是走在一级级的楼梯上, 让你的思维见识慢慢的升高.



---


==== 要有超强的自律性，过人的思考，令人惊讶的行动力.

对一个在科研领域可以发顶刊，在公考领域可以上岸省考的人来说，表明**他有着超强的自律性，过人的智商，令人惊讶的行动力.**

---

==== ★ 既然那么爱学习，为何不去考研？太难？竞争太激烈？在成年人的世界里没有容易二字.

- 找工作的时候，若没有文凭，没有一技之长，却和HR说我没错过任何一期的逻辑思维或者混沌研习社么？HR会鸟你吗？

- 老板甲：一个做市场的, 居然没有看过<一个广告人的自白>。我要告诉所有的求职者，你来参加这个节目一定要问自己准备了些什么，你这样是对自己的不负责，对我们的不尊重。

- **既然那么爱学习，为何不去考研？**为何不去学一门技术？是不是**因为这些学起来太枯燥？太难？竞争太激烈？在成年人的世界里没有容易二字**，极容易又可以大幅提升命运的, 不是买彩票就是骗局。

---

==== 现在人满为患是真，但门槛也更高了

很多人认为: “四年后不知道情况会变成什么样”。2010年前后很多人说，计算机门槛这么低, 工资这么高, 早晚人满为患，然后工资会一泻千里。当时你最终放弃了进入.   **现在,  对，的确不出我所料—— 变了，只不过变得更夸张了. 现在人满为患是真，但工资也更高了，同时门槛也更高了。**

---

==== ★ 越是巨坑的陷阱入口处, 都铺满了最诱人进来的鲜花

ppt，花里胡哨的画面和功能，万恶之源，反效率工具。要让人“做得越多而价值意义收获越少”的方法是什么？---- 赋予它越多的偏离核心价值的玩法以吸引住人 ---- 创造99条貌似吸引人的道路，但它们却都不通往核心价值之处。(比如ppt, 视频编辑)

*最大的坑的边上，往往有着最迷人的花环伪装！*

---

==== ★ 任何职业, 早就被社会标好了它们的下限和上限. 它们在世人眼中的地位和价值.  职业即社会阶层

短视频，外观光鲜，毫无内涵，不会再看第二遍。真正金玉其外，败絮其中。而且后患无穷:

- 会将你肤浅化, 更多被工具人镜头技巧带歪, 而影响对故事的内核的专注程度.   +
-  这个工作直接就把人打到底层, 就是个非核心的外围服务员专业!  学的是服务员技巧, 出来做的也是服务员地位! +
- 浪费时间学这个, 纯粹浪费年龄机遇。只会减慢你学真正有价值都数英的进度！

就像茨威格所说，那时他们还年轻，不知道命运馈赠的礼物，早已在暗中标好价格。   +
*任何职业, 早就被社会标好了它们的下限和上限. 它们在世人眼中的地位和价值. 职业即社会阶层.*

---

==== ★ 最开始，大家都只有微弱的差距，似乎在一条起跑线上. 但随着时间的推移，从业年份的增长，成功概率越来越显示出它的力量!

两个骰子加起来等于5点的概率, 是 1/9. +
我们会发现2点和12点的概率最小, 是1/36. +
中间7点的概率最大, 是 1/6. +
这11种情况并不是等概率的.

**这就跟职业选择一样，最开始，大家都只有微弱的差距，似乎在一条起跑线上. 但随着时间的推移，从业年份的增长，成功概率越来越显示出它的力量! ** 成功概率更高的职业, 就是比低的职业更能上岸！


---

==== 两者(两种工作)所处的"生态位"高低就不一样. 就决定了你"社会地位"的高低也不一样.

生化环材机械土木，都是负责物质生产的。   +
计算机金融，从社会层面讲，做得是资源管理分配消费的活儿。   +
*两者所处的"生态位"高低就不一样. 就决定了你社会地位的高低也不一样.*

---

==== ★ 学乐器，当背景：学唱歌，万人迷。

学乐器，当背景：学唱歌，万人迷。c位才是王道. 阶层地位从一开始的选择中, 就注定了.   +
金字塔结构, 不站在舞台中央(C位核心圈)的人, 就不会有前途.

---

==== 人要进入一个自带磁场价值效应(刚需)的工作中

**人要进入一个自带磁场价值效应的工作中**（医生，司法，公安，律师，教师），**这些工作能获得大量资源，是所有人的刚需。** 你才能稳固。这些都是最具人生刚需的职业带给你的。这些大多是体制内工作。统治者垄断这些能具有刚需光环和终身保障的工作，说明他们的认知非常清醒看穿！

---

==== 真正的好工作要满足一个重要要求：其经验必须能够运用在你日常的实际生活中.

*真正的好工作要满足一个重要要求：你在这个工作中学到的技能与思想领悟，必须能够用在你的实际生活中，能提高你解决生活问题的能力。否则，一旦你离开原先的工作行业 (比如失业, 退休后)，它的经验对你一点价值也没有*, 它离个人的日常生活太远，你无法用它来给你带来生活上的帮助。

---

==== 让制度保障来托你的底，而不是只靠你的技能。

- 人越老，技能越过时退化，所以你必须身处一个稳定的工作单位中，**让制度保障来托你的底，而不是只靠你的技能。** 那些老干部正是处在这样的有利环境中。

---

- 许多职业都有一条通向职业生涯终结的轫线，你的职业生涯也许是20年、25年、30年或40年。不论是什么时候结束，但它总是早于你的退休年龄. 这种结束可能是体能上的限制： +
如模特的容颜老去，运动员的身体机能已衰退； +
也可能是精神上的：数学家总是出错，广告人员与设计人员的创意不再神奇也不再能挣到钱； +
还有可能与精力有关：投资银行家和律师到40岁时会因为精力衰退、离婚或者体力不支而败下阵来， +
也许三者均有。 +
但这并不意味着你不能再从事这个行业的工作，但到达顶峰的机会已然错过，你仅仅是一个仍在跑的人。

---

- *人生就就像飞机，不在于飞得多高，而在于平稳降落。*

---

==== 如何判断自己是否适合一份职业?

尽全力的把一项具体的工作先能够做到80分以上，能够胜过大多数人。

1. 去评估：对比起其他你身边同样能把这件事做到80分左右水准的人，**你是会显著比他们效率更高，完成得更加轻松，还是会更累更费劲？** +
2. 当一件事情已经能被你做到80分以上时，**你是否真的会觉得享受它、喜欢它、还是反感它？**

---

==== ★ 你做任何一件事, 若没有兴趣支撑, 你就度过不了它最艰难的时间段

愚蠢的人为了金钱放弃自己的理想和兴趣，去从事他们认为的挣钱的工作. 如果你仅仅是因为舍弃不了暂时的“高薪”（或某人）而留在一个你并不喜欢的工作与公司里，那当老板减低拿走了你的“高薪”（或某人最终离职了），你觉得以前一直呆在这里有价值吗？

**真正能令你在最艰苦时期读过难关的, 是你的兴趣支撑!  你没有兴趣, 你在创业的最艰难时期就很难坚持下去.**


---
