
= 职业生涯通关 第二曲线 (要思考和运筹帷幄背后运行逻辑, 而非做工具人)
:toc:

---

== 方向

==== -> 非"上岸"的行动, 都是幻觉

**任何你做的没上岸的工作和工作内容，那些不会改变你原有的人生轨道的行为，这些行为一切都是幻觉！** 正如古人所说，“回想过往如梦”。

**当你在不喜欢的事上一天工作下来有充实感时，这种充实感其实是幻觉.**

**只有为了上岸而学习的必需技能（考研，数学，英语，金融专业知识，考证，考编），才是实实在在会改变你的人生轨迹的行动！这些才不是幻觉！**


---

==== -> 人要进入一个自带磁场价值效应的工作中（医生，司法，公安，律师，教师），这些工作能获得大量资源，因为它们是所有人的刚需。

**人要进入一个自带磁场价值效应的工作中**（医生，司法，公安，律师，教师），**这些工作能获得大量资源，是所有人的刚需。** 你才能稳固。这些都是最具人生刚需的职业带给你的。这些大多是体制内工作。统治者垄断这些能具有刚需光环和终身保障的工作，说明他们的认知非常清醒看穿！

人越老，技能越过时退化，所以你必须身处一个稳定的工作单位中，**让制度保障来托你的底，而不是只靠你的技能。** 那些老干部正是处在这样的有利环境中。

许多职业都有一条通向职业生涯终结的轫线，你的职业生涯也许是20年、25年、30年或40年。不论是什么时候结束，但它总是早于你的退休年龄. 这种结束可能是体能上的限制：
- 如模特的容颜老去，运动员的身体机能已衰退；
- 也可能是精神上的：数学家总是出错，广告人员与设计人员的创意不再神奇也不再能挣到钱；
- 还有可能与精力有关：投资银行家和律师到40岁时会因为精力衰退、离婚或者体力不支而败下阵来，

也许三者均有。
但这并不意味着你不能再从事这个行业的工作，但到达顶峰的机会已然错过，你仅仅是一个仍在跑的人。

*人生就就像飞机，不在于飞得多高，而在于平稳降落。*

---

==== -> 真正的好工作要满足一个重要要求：其经验必须能够运用在你日常的实际生活中.

真正的好工作要满足一个重要要求：你在这个工作中学到的技能与思想领悟，必须能够用在你的实际生活中，能提高你解决生活问题的能力。否则，一旦你离开原先的工作行业 (比如失业, 退休后)，它的经验对你一点价值也没有, 它离个人的日常生活太远，你无法用它来给你带来生活上的帮助。

---

常常问自己：我之所以去做，是因为这事本身是对的(是你真正想去的方向)，还是仅仅因为有把握做成它(没有门槛, 却不是你的方向)？

---


==== ★ -> 如何判断自己是否适合一份职业?

尽全力的把一项具体的工作先能够做到80分以上，能够胜过大多数人。

1. 去评估：对比起其他你身边同样能把这件事做到80分左右水准的人，**你是会显著比他们效率更高，完成得更加轻松，还是会更累更费劲？**

2. 当一件事情已经能被你做到80分以上时，**你是否真的会觉得享受它、喜欢它、还是反感它？**


---


== ----- -----

---

== 实践是检验"真理"(知识, 所学)真伪的唯一标准


==== ★ -> 知识, 需要你在实际实践中, 来检验其真伪度

- 如果我的一生看书花了大半的时间，因为没有及时整理而也遗忘了大部分的话，也就等于我浪费了人生的大半部分时间。这些时间的投资没有能真正产生收益。

- 知识要运用, 才有实际的收益，**不用的知识即使知道，也和不知道一样。(比如你学了投资学的数学知识, 却从来没有去做过投资实践, 那么知不知道该知识, 对你的生活变化本质上没有什么不同.)**

- 而且, **不用的知识, 你没有通过实践来检验它的正确程度, 及起作用的条件范围，那么你对这个知识的 (1)可置信, 和 (2)熟练掌握程度, 就只会处在肤浅的刚接触阶段。**

你不仅要学知识，还要用 (知行合一, 才能判断你所学的东西到底是不是真实的? 才能检验真理)。
还有要不断跟社会沟通，你才能够了解周围的环境，从而知道你目前的位置在哪里。
**缺少反馈是妨碍你进步的最大问题之一.**

---

==== -> 网上公开能学到的教程，都没有门槛和护城河. 网上学不到的，才有真正门槛

**凡是b站能学到的技术，都没有门槛和护城河，** 如设计，程序员。**而公共网络中学不到的，才是真正有门槛**和非青春饭，年龄保障的，**律师的技能你在b站学得到吗？医生的技能你在b站学得到吗？** 老师的同样如此.


== ----- -----


---

== 每个人都是自己生活的"曹操", 对自己和家庭的生活要运筹帷幄, 思考底层逻辑, 验证所学真伪, 运作谋划大事. 而非只当工具人.

==== ★ -> ai自己就是操作工具最有效率的'工具人'了。所以你必须做'ai做不到的事情'的工作.

如果你老是做着靠“软件本身自带的功能”就能实现效果(比如调色)的内容的话，这性质就跟以前的工人, 工作只是在操作扳手一样，那注定将来会被机器ai所取代。*因为ai自己就能调用软件api, 来调色了，用你干嘛？* 就像智能汽车, 或自动驾驶飞机一样.

所以你必须要做创造力性质的工作，而不是当工具人，*ai自己就是操作工具最有效率的“工具人”了。所以你必须要做超越软件的事情，做ai做不到的事情。*

---

==== -> 好的工作, 就是能让你当别人的大脑!  而不是别人当你的大脑, 你只能当"手"(工具人).

老师，医生，律师，为什么赚钱？因为它们才是是真正的刚需行业！每家人在一生中都长久高重视度需要。不像卖消费品的，你得去推销，三职业是人家自己找上门来求的。

**好的工作, 就是能让你当别人的大脑 ** (老师,律师,医生, 都是你教育别人, 你为别人出谋划策, 指导别人. 内行指导外行);   **而不是别人当你的大脑** (比如设计师, 是别人来发号施令你做什么, 对你指手画脚, 外行指导内行),  **你只是手(工具人)而已.**

为什么在发达国家医生会同律师、法官一样，成为收入最高的职业。从终极意义上说，这都是主宰人的命运的人，角度不同而已。

---

==== -> 谋事者, 成大家业. 谋物者, 替他人做嫁衣裳.


兴趣分两种，一种是技术类（下棋，弹琴，画画，编程，武士）兴趣，一种是事业类兴趣（做生意，建帝国，赚大钱，诸侯之心）。
正像王立群所说, **人分为几种: 琢磨事的, 琢磨人的, 琢磨钱的, 琢磨人事钱三者的, 琢磨死物的.**

技术类兴趣是悲剧，因为小时候你在这方面努力和投资花钱，被看成是“特长”，但技术的归宿就是工具。擅长做菜是优点，当了厨师就是悲剧了。小时候是个小画家，长大当了做小广告传单的就是悲剧了。

事业类的兴趣是有前途的，比如从小就极想光宗耀祖，刘备建功立业那种类型的兴趣。看清工具，重视事业。

所以，归宿决定一个人的命运和前程。**选兴趣和职业，要看这些职业各自的终极归宿是什么。**

---

==== ★ -> 一个人如果懂得为什么去做(底层逻辑, 背后逻辑)，那么他将永远是自己的主宰。

有两种人:

- 一种人, 只关注“如何完成事务”，但对于“我在做的所有这些事情, 是如何驱动我的业务增长和发展的”,  **这个背后的底层经商逻辑**, 他们不去努力知道.

- **另一种人, 则始终关心“我如何能够更好驱动自己生意的 某项业务的某个指标发展?”. 他们所做的每一个动作, 都带着清晰的目标目的. **  你想要的KPI, 子目标 的实现目的.

即, **你脑海中已经开始形成对于业务进行管理、拆解和驱动的思维模型.**

爱默生：“**一个人如果懂得如何去做，那么他将永远不会失业。一个人如果懂得为什么去做(底层逻辑, 背后逻辑)，那么他将永远是自己的主宰。**”

---

假如你是史蒂夫鲍尔默，需要管理公司的运营，增加公司的收入，即便是很小的一部分，比如说在竞争激烈的市场中赢得 1%或 5%的份额，你会怎么做？

---

==== ★ -> 更多人缺乏的是统观行业上下游的运营思维高度，以及跳出具体岗位外，对这个职业的想象力

在与日俱增的运营大军中，**更多人缺乏的是统观行业上下游的运营思维高度，以及跳出具体岗位外，对这个职业的想象力。**

而有一些公司，他对运营的期待, 就是定期生产出标准的内容、做些活动、维护促活核心用户，**这类架构给予运营师的可操作性空间, 就非常有限。** 多数互联网大厂培养不出顶级运营。

“从我工作第一天到现在，都是为了创业做准备，包括积累人脉资源、学习行业知识，以及帮朋友做的一些项目，都是为创业做的实验和铺垫。“

---

==== -> 我不断往上爬，不是为了被世界看见，而是为了看见整个世界。

Climb mountains not so the world can see you, but so you can see the world.   +
爬上山顶并不是为了让全世界看到你，而是让你看到整个世界。

- 爬高几层，有助于看出自己的处境，从哪来，往哪去，别人的道路有何不同，等等不爬高就看不见的事。

- 居后而望前，则为前；居前而望后，则为后。 +
身在后面，望着前面(志向远大)，那是前；而在前面望着后面的，就为后。

---

==== -> 对重大利益回报的 "生态位"的抢坑竞争, 是你死我活的

真正有用的，被人需求的，看重的是“运作大事情”，如合同，项目操作，而不是做技术（如设计，搞科研）。虽然学生在学校学的都是技术，但要想成为高层领导层，必须去操作“人之事”，而不要嫌它们复杂麻烦。

**因为你嫌复杂逃避了，就等于逃避了它能带给你的不可替代性，就有其他人会来做，并且位压你头上。**

---

==== -> 你不能把这个世界，让给你所鄙视的人. 你不上, 你的命运就是交给别人控制了. 卧榻之侧, 岂容他人鼾睡?

- 他不上，别人就得上，而一旦别人上了，他搁在哪儿都是难处置的家伙. **你不上, 你的命运就是交给别人控制了. ** 你上, 你的命运才握在自己手里!  (**卧榻之侧, 岂容他人鼾睡?**)

- 对组织政治的"知觉"与"工作满意度"呈负相关。一个人如果不参与到政治活动中，就会拱手把自己的应得利益与前途（成长）, 让位给那些积极的政治活动者。

- **你不能把这个世界，让给你所鄙视的人** (所以你要升职! 在其位谋其政, 行胸怀理念)。——安·兰德
 You can't leave this world to the people you despise.

---

==== -> 人都非"生而知之", 而是"学而知之". 所有的工作都能赚钱，但工作内容的性质带给你思想头脑上的回报, 就有本质区别了。

所有的工作都能赚钱，很多工作也能赚大钱，但工作内容的性质就有本质区别了。有的赚大钱的工作本质，都是纯属欺骗他人的，比如玄学、广告。

另一类工作，也是赚大钱的，但其工作内容, 却非常能令人开阔对世界与人生本质的认识，对人际处事的更深认识。比如律师、政府官员、外交官、商业领袖等等。他们研究与处理的，都是涉及人间社会规则基石的东西：

- 法律的运用**与力量的关系**（如何运用法律作为武器工具）、
- 权力的获得方式**与利益的关系**（如何获得权力, 及通过此力量来带来利益）、
- **人际的平衡与心理感情的关系**（如何纵横捭阖把控个人与他人的关系）、
- 事业目的的达成方式, 与回报的获得（如何用各种方法做成事业与自己想要做到的事）。也就是为了获得回报，如何运用人的心理情感，并通过各种手段方式做成事情、事业，来完成、达到自己对整个所生存的世界、社会、世人的深入认识与哲学本质的认识。

见多则识广。如果你能进入世界精英的大脑，他们眼睛所看到的东西你也能看到，他们耳朵所听到的东西你也能听到，他们做过的事、成长与得到经验的历程、生存与斗争交手的细节，他们的情感动摇与意志抉择，他们的判断依据与价值观排序，你都犹如和他们一体一般经历并知晓。遍观人、事、组织的生存历程本质之后，就等于你自己经历了这些一遍一样，你和他们就是拥有完全一样的思想见识与能力影响力。

---

==== ★  -> 你满眼都是芝麻，就没有机会练就捡西瓜的能力了。

郭台铭是捡西瓜，王妈妈则是捡芝麻。一个西瓜的重量是芝麻的两万多倍，因此，*捡芝麻捡得再勤劳，也捡不出西瓜的重量。*

很多产品在线服务的流量和盈利能力非常有限，贡献的都是一些小芝麻，把它们最后加起来，还不如谷歌一个产品带来的收入高。

看看下面这些在生活中捡芝麻的行为:

- 为了省一元出租车钱，在路上多走 10 分钟。
- 为了抢几元钱的红包，每隔三五分钟就看看微信。
- 为了挣几百元的外快，上班儉偷干私活。
- 为了“双十一”抢货不睡觉。
- 为了一点折扣在网上泡两个小时，或者在北京跑五家店。
- 为了拿免费的东西打破头。

通常，人的晋级上一个台阶，贡献、职责、影响力就可能增加一个数量级，至于收入就更不用发愁了。当然，世界上捡芝麻的人多、捡西瓜的人少. 大部分人捡芝麻的思维方式一辈子也改不了，也正是因为这样，才给那些立志于捡西瓜的人足够的机会，西瓜自然就留给了你这样有智慧的人。

有人说，我没有遇到西瓜啊，其实不是没有遇到，而是**因为你满眼都是芝麻，天天为捡芝麻而忙碌，就没有机会练就捡西瓜的能力了。**

---

==== ★ -> 你心里想要找什么，你在生活中就能发现什么。你只会发现你训练的大脑想找的东西。(反过来说:即 "眼不见, 心就不会想; 心不想, 事不做")

富爸爸对我说：“大多数人离开学校是为了找工作，所以他们就发现了工作。”他解释道，你心里想要找什么，你在生活中就能发现什么。他说：“想找工作的人总能发现工作，我不想找工作，所以也没有工作。我只是训练我的头脑寻找商业机会和投资。很早以前我就知道，**你只会发现你训练的大脑想找的东西。** 假如你想富，你就需要教会你的头脑寻找能让你致富的东西(商业逻辑, 创业全流程, 树枝而非树叶)，而工作不会让你富，所以你也不会再去找工作。”

我意识到如果我不停地说“我付不起”，就是在加强我成为一个穷人的感性认识；而说“我怎样才能付得起”是在加强我成为一个富人的感性认识。分析这两句话，你会看到“我怎样才能付得起”开启了你实现目标的思维，而“我付不起”则关闭了实现你的愿望的任何可能之路。

富爸爸让我们戴上他的“眼镜”，借助《大富翁》游戏，从他的角度看到了另外一个完全不同的世界。不断地鼓励我改变思维方式，从另外一个角度思考问题。每次我透过“眼镜”，总觉得一边的世界比另一边看上去蠢笨。

我建议父母们应开始鼓励孩子寻找一条使他们在30岁时就能退休的路，是否真能在30岁退休并不很重要，但它能使孩子从不同的角度思考问题。一旦问了这个问题，他们就开始了透过“眼镜”看世界的历程。

搞清楚自己能实现"财务自由"的工作的实质是什么，不做无效的累积 (不要学工具人的技能).

---

==== -> 你的座位(职位)的高低约束, 会限制你能力的发挥

官僚体系让人发挥作用的最大上限，是这个职位所要求的最高技能，而不是这个人的最大才能（你的座位的高低约束, 会限制你能力的发挥）。所以要尽可能的往上走（《白色巨塔》财前五郎）。

志不强者智不达 +
志向不坚定的人，智慧就得不到充分的发挥。即在其位才能谋你政！要想自由地执行你的意见观点(并历练, 用实践证明, 并修炼完善 你的价值判断眼光)，必须向上爬.

---

==== -> 你所做的事，都只是暂时的。你要利用他们来进入下一个你想去的环节，而不是被他们困住迷惘自己的目标。在你拿到了前一个目标, 就要去拿后一个目标了, 而后一个目标才是你真正的目标! 前一个目标对你只不过是敲门砖而已. 你只不过是利用前一个目标, 来实现后一个目标而已.

你一生的生活中的一切经历，都要围绕你的成长来进行。你所经历的工作、现在身处的环境、地方、你所交往的人都只是外在的，都是你借以使自己成长的“过程、利用物”。他们与你的交往、你所做的事，都只是暂时的。你要利用他们来成长，而不是被他们困住迷惘自己的目标。(所以, 进入就是为了离开!)

目标（做事）的价值和意义, 也是在于帮助你锻炼能力，而不是目标本身。目标只是用来成长自己的利用物，而不是最终追求。 所以已经完成的目标，就不要再去沉浸其中，要关上身后的门，轻装前行。

**我既是一个低头做事，也是一个抬头看路的人.**

你永远都有业绩下降的压力，而比你强的人永远都有。此生你想做什么样的人？你希望离开后别人怎么评价你？当你清楚了自己想要得到的一切时，倒推到眼前，你每天该做什么, 做多少这些，你就非常清楚了。
(**奥运冠军不是为了永远比赛, 他们是为了退役后有个好安排. 所以在你拿到了前一个目标, 就要去拿后一个目标了, 而后一个目标才是你真正的目标! 前一个目标对你只不过是敲门砖而已. 你只不过是利用前一个目标, 来实现后一个目标而已.**)

(正如你看过的那个营销总监,  一开始是做设计, 后通过转文案, 内容运营, 来实现达到他做营销总监, 并自己创业的最终目标! **前面所有的环节, 都只不过是实现后面路径节点的敲门砖而已. 他并不想在前面的所有节点上都做到天下第一, 事实上也办不到.  他的最终目的是最后一个节点!! 想象三国曹操的创业路程!**)

---

==== -> 你要去的那个地方(公司)，必须要能够为你带来, 你希望三年后要获得的那些核心价值能力! 不要去积累你不想积累的经验!!

分析公司是否符合自己职业发展之路的要求：在两家公司的发展方向、核心价值、经济实力、工作氛围、对你的发展潜力, 以及该行业发展前景、该职位的晋升空间, 和转型的可行度等方面，进行综合分析比较。

你要去的那个地方，必须要能够为你带来能积累到三到五年后，实现你追求的那个核心价值，要能够提供这种机会。这是今天你的价值，**你要考虑三五年后你希望拥有什么样的核心价值。现在的价值到未来的价值如何去过渡。**

在你开始一项新工作之前，写下你今后半年或两三年之内，希望赢得怎样的职业声誉或职业形象，及行动与时间段的路线图。

- 一年之内，我希望自己的履历中包括…
- 在这个岗位上干两年之后，我想让人们都知道…
- 三年之内，我想让别人知道我是这样一个人…
- 五年之内，我希望能够实现…
- 当同事们谈论我的时候，我希望他们说…
- 在这家公司工作期间，我不希望被人知道是因为…

如果一年之内，你想让人知道你具有雄才大略，你在考虑问题时就要从全局出发，即便你所从事的不过是简单的日常事务。如果三年之内，你想让人知道你有做生意的能力，你就去请求在销售推介会上承担重要角色。

**你的成长时间路线图，能让你瞄准目标，防止你因无助于你进步的技能而出名**，比如做笔记的好手、晚会策划者（都是非核心价值工作）、ppt工具人,  美工。（亨利·艾米）

苦并不可怕，怕就怕苦得没有价值、收获。**不要去积累你不想积累的经验!**

---

==== -> 你吸引人不是最终目的，而是实现你进化目的的手段（诱饵、催化剂）

**你的形象举止, 只会产生两种影响：交往与回避。**

**他人对你的隔离与封闭, 会对你的成长造成很大阻碍：成长只有在具体的一件件事情中, 才能渐渐积累起来，而其他人不与你进行这些事情，你也就没有机会（机遇）来完成你的“进化”。**

人各方面的魅力，所起的真正作用利益，不是引人喜欢，而是通过引人喜欢来带来“成长事件”的实现！吸引人不是最终目的，而是实现你进化目的的手段（诱饵、催化剂）。
(如颜值, 魅力型很高的演员, 会带给他们主演大作的机会, 而大作会成就他们的成绩和地位.)


- 女性应该利用自己的女性资本取得对自己有利的结果。自称从没利用自己的性别魅力推销的女性，不过是还没有学会如何利用它来达到于己有利的目的。   +
"露出你的大腿"（有目的的为了自身利益）和"张开你的腿"有很大的不同.

---

==== ★ -> 要去解决更多的问题，而不是如何最好地解决一个问题。(所以不要去追求完美的方法)

什么年龄, 就要干什么年龄的事.  对职业的态度同样应该如此: 关键是40岁就要干40岁该干的活，35岁就要干35岁该干的活，你不能35岁还在干30岁干的活。

换言之, 你干一辈子底层的技术工作, 也不可能有"完美"的解决它们的能力. **单一技术的事情是永远做不完的!!   相反, 你要追求去解决"更多问题"**, 即, 不断向管理层上走, **向"上方"走, 而不是在"平行线"上走.  **

**正如你一路长大,  都不是"恋爱专家","育儿专家", "教育专家",  "父母专家", "买房专家", "买车专家", 但你却一路解决了很多人生大事. 这正是你的人生任务! 必须要完成的.**

**“60分的做完”比“95分的未完成”更重要。很多事情我们只需要赢，而并非必须做到完美。**


当尚未驻足于历史，目不暇接的新事物已经出现。还没来得及看清楚身边的环境，已经逼得继续向前走，很难多作停留。


---


== ----- -----

---

== 要当树枝, 能复制大树的成长. 而不要当树叶!

==== -> 牡丹花好空入目，枣花虽小结实成

*牡丹花好空入目，枣花虽小结实成。*   +
画水无风空作浪，绣花虽好不闻香。

牡丹花虽好但只能供观赏，枣花虽小却能结出果实。  +
画中之水空有滔天波浪，却听不见风声阵阵；   +
布上绣出的花朵虽然好看，但闻不到半点花香。   +
将年华耗在虚幻之物(电子艺术)上, 不如做实业 (要做树枝, 不要做树叶)!


---


==== ★ -> 你不掌握整个链条的话，你就没法复制这个赚钱模式！要当树枝, 能复制大树的成长. 而不要当树叶!

生活中，你真正要做的，是从头到尾，一个人掌握那种可以产生现金流的技能和产品.
然后在第一点的基础上，争取把现金流稳定下来.
然后在第二点的基础上，争取多几个这样的现金流.
第一点是最重要的，因为有了第一点，第二点迟早会到来. 有了第二点你就基本上比较自由了.

**我发现这东西的赚钱模式是这样的...
然后我发现，我做的所有的事情，都在第二个环节，我几乎接触不到第一个环节中的流程，也接触不到第三个环节里面的大头....**

**这样的话，我永远是个螺丝钉**，你接触不到第一个流程和第三个流程，你就没有议价权。 我可以把PPT做得无比完美，但你的领导永远可以找到另一个人去改你这块的内容，而你无法涉足他的那些块，找不到客户资源。

**你不掌握到整个链条的话，你就没法复制这个赚钱模式！(要当树枝, 能复制大树的成长. 而不要当树叶)**

- 很多婚庆公司为了避免策划师, 掌握过多的资源而另起炉灶，将策划环节和现场执行环节, 分开给不同的人.

---

具体的说, 在整个链条中：

- 对你所在的行业变迁, 和社会现象, 能够清晰地搞清它的前因后果，发现机会.

- 知道想做一件事，你的上下游在哪里，你的合作伙伴会是谁，你的客户是谁，你用什么验证过有效的方式去打动他们.

- 在所有关节节点上会遇到什么细节问题, 如何探寻解决方案，需要拜访哪些相关关键人. 在哪个环节需要多少成本来打点，多大的容错空间来承担风险.

- 你如何创造信心让你的客户安心付钱给你，让你的团队成员为你所用. (郭德纲说, **曹操的优点就是,  在乱世中, 可以让比自己厉害的人为自己所用. 帮自己建立起越来越大的家业. 而不像袁绍袁术那样嫉贤妒能.** )

一个人一定要有自己的核心价值，然后他一定要想办法把这个价值利用到极致。


这些就是你必须要做的 行业分析, 商业模式,  管理学, MBA, EMBA 的研究对象.

---


==== 曹操与豪族的合作借力关系

一个人要成功。有几个方法： +
① 他必须帮成功者工作(是敲门砖)。 +
② 当他们开始成功的时候，也开始跟更成功的人合作(学习高人的思维模式)。 +
③ 当你越来越成功的时候，要找成功者来帮你工作(曹操广揽天下人才和英雄)。你为什么能赚10万美金？原因有三个。你的习惯、你所交的朋友、你核心圈的人。 +

你开公司不能想着要“驾驭”人才，特别NB 的人才，也不会让你“驾驭”的。所以要像政治家一样拉拢合作, 而非控制. (曹操与豪族的合作借力关系)

将要赚到的钱应该如何分给各级参与者，让更多人能把他的资源投入到你的事业中, 来帮你 (连同他一起)做大. +
他第一次挣了100万，分出80%给手下人，结果，大家一努力，第二次挣回来就是1000万！即使他这次把90%分给大家，自己拿到的也足有100万。等到第三次的时候，大家打下的江山可能就是1个亿。

