
= 进入是为了离开. 进入现在这个阶段, 是为了得到进入下一个阶段的敲门砖
:sectnums:
:toc:

---

== *进入一个阶段, 就是为了离开这个阶段, 即以后不再进入这个阶段*

==== 你所做的事，都只是暂时的。你要利用他们来进入下一个你想去的环节. 前一个目标对你只不过是敲门砖而已.

你所做的事，都只是暂时的。你要利用他们来进入下一个你想去的环节，而不是被他们困住迷惘自己的目标。在你拿到了前一个目标, 就要去拿后一个目标了, 而后一个目标才是你真正的目标! 前一个目标对你只不过是敲门砖而已. 你只不过是利用前一个目标, 来实现后一个目标而已. +

你一生的生活中的一切经历，都要围绕你的成长来进行。你所经历的工作、现在身处的环境、地方、你所交往的人都只是外在的，都是你借以使自己成长的“过程、利用物”。他们与你的交往、你所做的事，都只是暂时的。你要利用他们来成长，而不是被他们困住迷惘自己的目标。(所以, 进入就是为了离开!) +

**目标（做事）的价值和意义, 也是在于帮助你锻炼能力，而不是目标本身。**目标只是用来成长自己的利用物，而不是最终追求。 所以已经完成的目标，就不要再去沉浸其中，要关上身后的门，轻装前行。

---


====  进入，是为了退出

进入，是为了退出 +
学习某样东西，是为了不再学习某样东西 +
得到，是为了不再次去得 +
成为，是为了不再次成为 +
进入娱乐圈，是为了退出娱乐圈 +
处理，是为了不再次处理 +
上车，是为了下车 +
早死早超生.

进入是为了离开！ 做某事, 是为了以后不再做它. +
(因为你已经得到它了, 而不需要永远重复做它. 如同学习一样,  **学习某项技能, 是为了以后不再需要学它, 而不是老是需要重复学它**).

**在某一位置获得足够的能力与预见，是为了尽早地离开那一位置层次。**  +
就像老罗早已几辈子衣食无忧，不用再进入职业市场求职工作。他们足够优秀，就是为了随时离开，而不是一辈子陷在里面，玩这种三十年河东三十年河西的赌博博弈，和被时代发展和一代代小鲜肉口味变换所淘汰的威胁。 +
这很明显地告诉我：**进入，是为了尽早地离开。** 所谓三年赚三十年的收入！这才是正解。

---


==== 不要去积累你不想积累的经验!!

技多不压身，艺多不养人  +
技艺贵在显学, 不贵多(低收入的底层技能, 学得再多也没有用!)

分析公司是否符合自己职业发展之路的要求：在两家公司的发展方向、核心价值、经济实力、工作氛围、对你的发展潜力, 以及该行业发展前景、该职位的晋升空间, 和转型的可行度等方面，进行综合分析比较。

**你要去的那个地方，必须要能够为你带来能积累到三到五年后，实现你追求的那个核心价值，**要能够提供这种机会。这是今天你的价值，**你要考虑三五年后你希望拥有什么样的核心价值。现在的价值到未来的价值如何去过渡。**

在你开始一项新工作之前，写下你今后半年或两三年之内，希望赢得怎样的职业声誉或职业形象，及行动与时间段的路线图。

-> 一年之内，我希望自己的履历中包括… +
-> 在这个岗位上干两年之后，我想让人们都知道… +
-> 三年之内，我想让别人知道我是这样一个人… +
-> 五年之内，我希望能够实现… +
-> 当同事们谈论我的时候，我希望他们说… +
-> 在这家公司工作期间，我不希望被人知道是因为…

如果一年之内，你想让人知道你具有雄才大略，你在考虑问题时就要从全局出发，即便你所从事的不过是简单的日常事务。如果三年之内，你想让人知道你有做生意的能力，你就去请求在销售推介会上承担重要角色。

**你的成长时间路线图，能让你瞄准目标，防止你因无助于你进步的技能而出名**，比如做笔记的好手、晚会策划者（都是非核心价值工作）、ppt工具人,  美工。（亨利·艾米）

苦并不可怕，怕就怕苦得没有价值、收获。**不要去积累你不想积累的经验!**

---


====  记住: 你不是来这里度假的！

每天都要在心中牢记三个问题:

1. 我为什么到这里(这个公司)来(工作)?  我的目的是什么, 我想在这里得到(学到, 掌握)什么?
2. 我何时离开, 继续到新的更高层的地方去?
3. 我在这里的这段时间中, 要如何安排阶段性进度? 三月规划,  半年规划, 一年规划, 三年规划? +
记住: 你不是来这里度假的！


我是谁？ +
我想去哪儿？路径是什么？ +
我为什么要来这儿？ +
我想从这儿得到什么？ +
我什么时候离开？ +
后辈离我有多近？ +
我离前辈有多少距离？ +
 +
我现在这阶段做的这事，符合年龄吗？ +
我的养老计划进度如何？ +
我决定什么时候隐退工作？

---




==== ★ 死早超生. 如果要走完十万八千里后, 才能有获得真经思想的质变, 那你就要把这段路径压缩在最短的时间内走完!

- 人的一生中会经历很多事，但是绝大多数都是惯性事件，而只有很少的一部分，才是令你质变的转折点事情（如果你投身于波澜壮阔的环境中，你会更多的接触到这些事件，自己也成长更快。我经历了很多事情，我也看了很多事情，我对世界与社会、人性的思考比以前更深刻成熟了）。所以，你要尽快、尽早、尽多的进入转折事件更多发生的环境。 +

**(早死早超生. 如果要走完十万八千里后, 才能有获得真经思想的质变, 那你就要把这段路径压缩在最短的时间内走完! )**

---

==== 用兵打仗，只听说计谋不足但靠神速取胜的，没有见过有计谋却要长久作战的。战争旷日持久而对国家有利这种事，从来就没有过。

兵闻拙速，未睹巧之久也

其用战也胜，久则钝兵挫锐，攻城则力屈。故兵闻拙速，未睹巧之久也。夫兵久而国利者，未之有也。故兵贵胜，不贵久。

**军队作战就要力争快速胜利，如果长久僵持，兵锋折损、锐气被挫，攻城就力竭。用兵打仗，只听说计谋不足但靠神速取胜的，没有见过有计谋却要长久作战的。** 战争旷日持久而对国家有利这种事，从来就没有过。所以，作战最重要、最有利的是速胜，最不宜的是旷日持久。

（学习数学, 英语, 考公等, 也要一鼓作气，十足投入，速战速决。慢慢吞吞，时间一长就很难保持住耐心，最终热水变冷水，反复烧，而完不成）

---


====  最对人有负面影响的是循环. 人生有小循环和大循环。循环的东西越小，停留在其中的时间越长，负面影响越大。

就像程序语言一样，人生也有一路前进，循环这样的流程。最对人有负面影响的是循环，**人生有小循环和大循环。循环的东西越小，停留在其中的时间越长，负面影响越大。** +

玩游戏，任何游戏都是一种**小循环，无论你浪费多少时间青春在上面，永远在原地转圈而不是一路向前去，所以很快会无聊。** 底层初级工作也是一种小循环，不跳出循环就是消耗青春。 +
创业是一种大循环，从头到尾所学密度很大，所以能常常保持新鲜感，而且很少能循环次数到厌倦的量变程度。 +
人生是一种更大的循环，只不过每个人只能循环一次。

---

====  我既是一个低头做事，也是一个抬头看路的人.

你永远都有业绩下降的压力，而比你强的人永远都有。此生你想做什么样的人？你希望离开后别人怎么评价你？当你清楚了自己想要得到的一切时，倒推到眼前，你每天该做什么, 做多少这些，你就非常清楚了。 +
(**奥运冠军不是为了永远比赛, 他们是为了退役后有个好安排. 所以在你拿到了前一个目标, 就要去拿后一个目标了, 而后一个目标才是你真正的目标! 前一个目标对你只不过是敲门砖而已. 你只不过是利用前一个目标, 来实现后一个目标而已.**) +

(正如你看过的那个营销总监,  一开始是做设计, 后通过转文案, 内容运营, 来实现达到他做营销总监, 并自己创业的最终目标! **前面所有的环节, 都只不过是实现后面路径节点的敲门砖而已. 他并不想在前面的所有节点上都做到天下第一, 事实上也办不到.  他的最终目的是最后一个节点!! 想象三国曹操的创业路程!**)

---


== *要借助各种资源自带的"势能", 来助你前进*

==== 你吸引人不是最终目的，而是实现你进化目的的手段（诱饵、催化剂）

**你的形象举止, 只会产生两种影响：交往与回避。**

**他人对你的隔离与封闭, 会对你的成长造成很大阻碍：成长只有在具体的一件件事情中, 才能渐渐积累起来，而其他人不与你进行这些事情，你也就没有机会（机遇）来完成你的“进化”。**

人各方面的魅力，所起的真正作用利益，不是引人喜欢，而是通过引人喜欢来带来“成长事件”的实现！吸引人不是最终目的，而是实现你进化目的的手段（诱饵、催化剂）。
(如颜值, 魅力型很高的演员, 会带给他们主演大作的机会, 而大作会成就他们的成绩和地位.)

---

==== 女性应该利用自己的女性资本, 取得对自己有利的结果。

女性应该利用自己的女性资本取得对自己有利的结果。自称从没利用自己的性别魅力推销的女性，不过是还没有学会如何利用它来达到于己有利的目的。   +
"露出你的大腿"（有目的的为了自身利益）和"张开你的腿"有很大的不同.

---

==== 别穿得跟你想表达自己的意思相矛盾或不符合 (借势, 势是一种能量)

别穿得跟你想表达自己的意思相矛盾或不符合，尤其是当你正在努力建立信誉的时候。 (*借势, 势是一种能量. 高贵的服装, 能让别人对你有地位的心理想象, 那就要利用服装带给你的这种能量 -- 势*)

如果你自己是个失败者形象，怎么可能把成功带给他人？

---

==== 借助"钱"的势能 :你的首要任务就是拼项目、签合同，你首先要想尽办法给公司挣钱，而不是只考虑替公司省钱，不能舍本逐末


花钱一定要花在明处，不要钱花了却没收到效果。 +
小薛太抠门儿了，该花的钱不花，弄得考察团怨声载道，搞得柳副总自己不仅没玩好，更觉得是在下属面前丢了面子.

你要记住你是干什么的，做销售，你的首要任务就是拼项目、签合同，**你首先要想尽办法给公司挣钱，而不是只考虑替公司省钱，不能舍本逐末。**

---


