
= 责任, 人生任务
:toc:
:sectnums:
---





==== 电子世界中的东西, 都只能是虚拟的“获得”. 数字化可以被清零. 现实世界中, 实体的东西才不会被消失. 时光会带走无形，留下的只有实体。

**在网上寻找的“圆梦”,  都是虚拟的“获得”**，其实生活中旅游等, 也是虚拟的获得( 玩完就没了, 没有任何实体财务留下)，因为你都没有实实在在的得到它们，就像你在抓捕烟雾 (**无论你在电子游戏中获得多少"财富"和"成就", 游戏从硬盘上一删, 就都没了.  如同黄粱一梦**)。只有实际的获得你真正想要的工作，购物，进到你口袋里了，你才是真正得到了它们！

所以, **人的一辈子活动, 无论你做什么, 最大的实实在在的实体物质遗留, 就是生儿育女传承下去! 其他都会化为烟云.**

*时光会带走了无形，留下了实体。*  +
只是我们更多会回想无形，而非实体。可惜的是，回想往往并不重要。
但无形只属于我们自己，而实体不属于任何一个人的，实体属于实体本身, **实体是你唯一能留给后代的东西。**所以它不以我们的情感多变而毁灭，它能够留存后世，实体才是我们唯一的珍贵之物！

---

==== ★ 人活着, 就是在对抗熵增定律

薛定谔在《生命是什么》：“**人活着就是在对抗熵增定律，生命以负熵为生。**”

对于死亡的焦虑，是人类行为产生的重要动因。小到一个人的一生，大到人类文明的沉落起伏，都是生命在死亡表层之下寻找意义的结果。

---

==== 推巨石者Sisyphus, 他知道只要他活着，无论什么生命阶段，推石头(与人斗)就是他存在的使命，并且是唯一的(想想康熙老年了还在与敌人, 敌国做政治斗争)

推巨石者Sisyphus真是一个极好的寓言，  +
他知道只有做到第一步，才能走第二步；    +
他知道前面的步不走到位，后面就会一直无限返工前面的步；  +
他知道无论推多少次，石头都会掉下来；    +
他知道无论石头推多高，它依然会掉下来；    +
他知道石头不完美，但有用就行；    +
他知道石头不会自己上山，推它是让它上山的唯一方法；    +
他知道只要他活着，无论什么生命阶段，推石头(与人斗)就是他存在的使命，并且是唯一的；  +

为死亡做准备，必须从开始就进行，且永远不会有结束点。

- 底层的人的一生，就是不断与其同一阶层的人打官司的一生。因为人的一生都是与侵犯自己的人斗争。

---

==== ★ 如果这个事情来了，你却没有勇敢地去解决掉，它一定会再来。生活就是这样，它会一次次地让你去做这个功课直到你学会为止。

一个行业发展好的时候, 所有问题基本都能被掩盖，可潮水退去后，各种没能解决的问题都会再次浮现出来。 +
人也是一样, **经济收入好时, 个人缺点都能被家庭成员容忍; 但一旦失业, 他们对你的态度就会转变, 你依然要面对自己缺陷和弱点的这些问题.**

---

==== 也许你是别人眼里的草，但你却是家人的天。

- *人无头不走，鸟无翅不飞* +
家族子孙辈中, 没有有能力的人才, 领路指引方向(导师也很重要! 必须要有高人指点), 则家族必衰败. (红楼梦四大家族的衰败)

- **也许你是别人眼里的草，但你却是家人的天。作为一个男人，要活出家的担当责任。** +

- 芸芸众生，谁不是在苦中作乐。你看那些基层百姓拼命挣扎的样子觉得拙劣好笑，却没看到每个人都在努力活着，那是如杂草般顽强的生命力，为下一代过上更好的生活而努力。 +
一代又一代，没有例外，平凡又不平凡。

- **英雄是"正在形成的事物"的捍卫者，而不是"已经形成的事物"的捍卫者，因为他就是"正在形成的事物"。** ——约瑟夫·坎贝尔

---

==== 如果你不把重心放在家庭上，又有什么家庭可言呢？你们不是一家人——你们只是同居的伴侣。

如果你不把重心放在家庭上，又有什么家庭可言呢？你们不是一家人——你们只是同居的伴侣。

家庭是你生活的核心，你的责任，是能为家庭中的每位成员都创造良好的成长（发展）环境。

对这个家，对孩子的将来，一点打算一点考虑都没有.
你没结婚你是一个人的时候，你的一切可以随着你喜不喜欢来定；你结了婚了有了家了，就得为这个家负起责来，考虑决定事情的时候，就不能只考虑你。

---

---

==== ★ 你知道如何来衡量一只蜘蛛的优劣？ 是看它的网破坏后，它重新补织的速度

- The greatest glory in life is not in never falling but in rising after falling. ——Nelson Rolihlahla Mandela  +
生命中最伟大的光辉不在于永不坠落, 而是坠落后总能再度升起

- “**你知道如何来衡量一只蜘蛛的优劣？** 不是看它的体型、力量、毒性、速度，或是它织出的网……**是看它的网破坏后，它重新补织的速度……在你叹息的时候，或许有人已经补好了！**”——“鹈鹕”先生

---
