
= 年龄 - 时间窗口
:toc:
:sectnums:
---

== *时间, 光阴似箭*

==== 尽岁有似赴壑蛇，半没去意谁能遮。三十六旬都浪过，偏从此夜惜年华

---

==== 自古美人叹迟暮，不许英雄见白头.

抬头看这位大姐   +
鱼尾暗藏，法令隐现，浓妆难掩倦色。   +
肤色渐浊，发际靠后，时尚怎盖粗糙？   +
昔年少女今少妇，徐娘半老不忍言。


---


== *青春饭*

==== 人类对疾病的治疗上, 永远都会有很多灰色地带, 需要经验来提供信用背书。表现出来就是医生职业越老越吃香。


医生职业, 经验的权重很高. 而程序员, 编程语言的发展太快, 经验很快就会过时贬值.

**医学, 一半以上是发病机制至今未完全清楚的。** 医学只是刚刚走出启蒙期。**所以现阶段医生个人在临床上经验积累带来的增益, 大过他知识过时导致的损害，表现出来就是职业越老越吃香。** 人类对疾病的治疗上, 永远都会有很多灰色地带, 需要经验来提供信用背书。

英文里"行医"，"行法律" , 都是 practice medicine, practice law 这些英文就比较直接，永远都是在"练习(practice )"自己的craft，永远都不是完美的。

而程序员是科学性/规范性非常强的职业，很多需要经验的灰色区域少，所以没法靠这个得到经验和时间的溢价。

---

==== 青春饭工作, 你不是那个年龄段的人, 你就get不到那些年龄客户的点.

游戏这个行业是青春饭职业，因为你的客户是14岁到28岁的人，你如果35岁了，你根本get不到他们的点.

而医疗不是. 我现在开始做医疗了，我的主要客户是35岁往上的，岁数越大，我对这些人的心态就越了解。


---

== *年龄*

==== 青春是块遮羞布

很多事情，跟青春绑在一起就是美好，离开青春，就是幼稚。

青春掩盖了很多问题：穷，没问题，年轻时候的穷理直气壮；缺乏保养，也OK，底子不差就行；懒得锻炼，新陈代谢高啊，不容易胖；脾气差，毒舌也挺可爱。

等青春的遮羞布拿开，穷懒丑就都掩饰不住了。青春是一滩潮水，潮水退了，才知道谁在裸泳。


---

==== ★ #无论你做不做，学不学，你总要活到那个年龄！#

即使有一万个人都在劝退你做你真正想做的事情(成为刘备, 曹操那样创大家业 志向的人)，当还是那句话，*无论你做不做，学不学，你总要活到那个年龄！*

我希望大家不要对所有事物都觉得遥远而崇高，都不碰，可是自己却在受苦。其实它们不遥远也不崇高，一处理就会有进展，自己受的苦会减少。这才是我相信的事情。

---

==== 不要去想跟下属们都打成一片. 一个人达到了这个年龄毕竟精力过很多事的，思想跟年轻人是皆然不同的.

不要去想跟下属们都打成一片. *一个人达到了这个年龄毕竟精力过很多事的，思想跟年轻人是皆然不同的. 即使同一件事，一个经历了200遍的人，和一个经历500遍的人，想法肯定不同。*

---

==== 在学校，学生每学期收到一张成绩单。而在现实生活中，大多数成年人都不会收到定期的人生成绩单。

许多人在学校里学得很好但在离开时，却没准备好在生活中成功的赢配方。 +
你的财务报表就是你离开学校后的成绩单，它是成年人的成绩单。另一张成绩单是你的年度体检报告，通过验血和其他检查程序来告诉你的健康状况及需要改进的方面。人的一生中，会有很多不同的成绩单，但个人财务报表是最重要的之一。

*在学校，学生每学期收到一张成绩单。而在现实生活中，大多数成年人都不会收到定期的人生成绩单。*

一个孩子要在一生中达到职业和财务的成功，需要学习3种基本的赢配方： ①学习赢配方 (高效学习)；不同的人有不同的学习赢配方；②职业赢配方 (事业)；③财务赢配方 (退休养老)。

---

==== 为什么你觉得越老，世界约对你温柔呢？我们必然要面对这个问题 -- 中年危机, 因为资本家是不会羞于去考虑这个问题的。

人到中年以后，时常会觉得孤独，因为他一睁开眼睛，周围都是要依靠他的人，却没有他可以依靠的人。 +
你在三四十岁的时候，都能理解啥叫年龄歧视, 靠山山倒，靠人人跑.   **为什么你觉得越老，世界约对你温柔呢？**

- 一个人的未来, 可以从app开屏广告( 天天做哪些繁杂而思想空洞的画面, 设计累死), 平台里的对各种工作的讨论中, 马路上的老年人身上, 看到未来的样子.

- 我们必然要面对这个问题 -- 中年危机, 因为资本家是不会羞于去考虑这个问题的。

---


==== 你成功的速度, 一定要超过父母变老的速度。

原谅父母曾经对我们的不能和没有，因为她们已经尽力了。我曾经抱怨父母，是我们神化了父母。
行善行孝感恩这三件事情都不能等，不然就没有机会了。

---

== *年龄 - 时间窗口*

==== 它有自己的节奏，无法让你以自己的节奏在那里冲。

她们为什么焦虑?  在单位，年龄对她们的压迫感比男人大约提前了5年。  +
虽然副科男女年龄杠子都划到35岁以下，但竞聘正科，男的划在42岁以下，女的就非得37岁以下，副处、正处、副厅…男女也都有5年的落差。   +
对于她们来说，要想实现理想，就得用比我们男人短5年的时间去跑完这段路。

**它有自己的节奏，无法让你以自己的节奏在那里冲。 **

面对新人，他们的到来，除了提醒你这里更拥挤了，更是提醒你已经不年轻了。

---

==== 窗口时间非常重要!

- 我一个朋友，在审计部门做函证工作。    +
他第一年拿了全组最高分。因为他第一年的表现突出， +
第二年又让他负责函证，又拿到了全组最高分。 +
第三年，同级小伙伴都开始能独立做一些审计项目的时候，这个朋友却发现自己“失业”了，没有哪个项目会用一个工作第三年的高级审计师，来负责函证. (窗口期已经被关闭)
+
**作为公司和领导，他们没有义务对员工的职业发展负责。**


- 第一年来公司的时候，因为表现好，就做了新的业务， +
第二年公司又搞了个类似的大项目，因为我有经验，又让我去. 结果当年度，**欣赏我的项目组组长离职了，公司的领导也换了， +
等我回到原来的岗位时, 一切都变了**，新业务线收回到总部新成立的部门，调了两个关系户上去。 回到原来的岗位，**各业务线都有了新的负责人，也没有我的位置了。**

---

==== 他们的成功, 都只是几个很重要的点（转折点）带来的，而其他很多做的事情，对公司的价值，只不过是多赚了几块钱而已。

若干年之后，当你再回头去看的时候，你会发现，其实已知的一线二线互联网公司，**他们的成功都只是几个很重要的点（转折点），那几个点就能决定他们的成功，而其他很多做的事情，最终对这个公司的价值，只不过是多赚了几块钱。**

回头去看一下腾讯、阿里，你会发现他们虽然是几千亿的公司，但是**过去十几二十年，腾讯和阿里很多工作也只是锦上添花，也许只要踩对几步，或者抓住几个个点就可以做成这样子。 ** 即, 你这个点如果踩对了(人生转折点, 上岸)，就可以成为一家伟大的公司。

从这个角度思考问题，我们就会发现，**其中最重要的是两个字——节奏，即你要在合适的时候做合适的事情。(不能错过窗口期)**

所以, 过去有很多的看法，当它过了六年八年你再去看的时候，意义并没有我们当初想象的那么大。


---
