
= 人性, 心理学
:toc:
:sectnums:
---

== *1.眼不见, 心不想; 2.心不去想, 事情就不会去做; 3.事情不做, 家业就不会成 & 自信心是被行动锻造出来的*

==== ★ 远，就会眼不见心不想，处于"视而不见"的回避状态

近, 就体验及其深刻，看得很清楚；远，就会眼不见心不想，处于迷雾认识, 或"视而不见"的回避状态。  +
所以加班越多的设计，就回越早离开这种职业。

---


==== ★ 有些重要的事情，如果你不强迫自己天天去做，你就永远不会去做！

眼不见，心不想；   +
心不想，不作为；    +
不作为，无所得；    +
无所得，事不成    +
——心想才能事成

眼不见，则心就不会去想。   +
有些重要的事情，如果你不强迫自己天天去做，你就永远不会去做！ 如，在知乎和脉脉上, 了解各种职业的生态，前景。

1.这可以防止你从一个坑, 跳进另一个坑
要当树枝（可以复制成树干），而不要当树叶（不能自己复制成独立创业）！（大部份工作都是树叶性质的）

2.可以让你不再在当前的工作上闭着眼睛，虚度光阴，而能立刻最快的速度进入更好的职业轨道上.

---

==== 星星之火，可以燎原

**星星之火，可以燎原。一个小想法只要你天天想着，就会越来越变成动力做它，然后跨出第一步, 就会跨第二步，越行越专业！**（如同你学编程的经历一样）

但前提条件是，你要心里要永远惦记着（荆轲刺秦里面，李雪健演的秦始皇说，“我没忘了统一天下”）。否则，眼不见心不想，比如你心里如果想着别的非上岸的东西（比如视频编辑学习之类），就会把你的注意力拉离上岸。那你的星星之火什么时候能实现燎原？

你天天关注考证，而不是拖到明天，明日复明日，才能越早完成这人生任务。考教师资格证要立刻行动！ 机会是给有准备的人的！机会永远存在，只是你从来没有去准备好过，你永远没去行动, 没有燃烧你的星星之火, 你永远停留在原地, 所以你永远缺乏入职条件。

机会是留给有准备的人的，即，只要你平时每天做好了准备，就随时都有"走人"和"上位"的机会.

- 你平时每天都在学习锻炼数学英语，就能随时去考研；
- 你平时每天都在针对性, 有意识的锻炼"考公"必需的能力，如演讲, 和待人接物，你就能随时去考公。

你必须对自己要锻炼的那些内容, 非常有意识！ **不要让公司来决定你要去学什么做什么，如短片拍摄之类！这不是你要取的经，只会浪费你短暂的青春人生，会拉离你的努力目标之路。**  这只能表明你对自己方向认识不清，没有目标。

---

==== 迈出第一步后, 就会正向循环有第二步, 第三步... 真正变成本行

- 人的大脑学习可塑性是很强的，**只要你都某事物真的感兴趣，你就会像八爪鱼一样涉及学习它各个延伸出去的内容，像树根一样四面八方蔓延，学习。** 在一定时间段中，你的大脑的注意力完全在这个上面了。所以对个人来说, 学习一项新的感兴趣的行业, 其实是毫无困难的。

- 即使参加奥运，也是第一次激动，第三次厌倦. 反过来看就是，**除了生和死，没什么是趟不过的。那你的转行等还有什么好担心的呢?**

---

==== 如果你的主要目标不能激发你的想象力创造力，目标的实现就会遥遥无期。

- 调高目标许多人惊奇地发现，他们之所以原先达不到自己孜孜以求的目标，是因为他们的主要目标太小、而且太模糊不清，使自己失去动力。如果你的主要目标不能激发你的想象力创造力，目标的实现就会遥遥无期。

- 学习东西，*必须要有大目标才会给你长久地干劲，如果目标太小，往往很快无聊。*   +
比如你学编程，如果你只想搞个文本整理，你肯定没学习的动力的。当你想做一个真正随自己所想的游戏时，你就会认真的读完每个章节。


---

==== 最重要和关键的是，前进是一步步做出来的

- 但**最重要和关键的是，前进是一步步做出来的，那些身有多套房的人，是一套套投资买出来的！只有向前做，才能让自己的状况逐渐变得更好。**

- **对于真正做大事(做大家业)的人来说，难, 他就会不干了吗？** 真正的懒惰，是头脑懒惰。

- 如果你感觉被困在你目前在做的的职业里面了，是因为**你日常没有把你做的每件事，都当作是你突围的学习机会. 犹如曹操创业一样，他在每一天做的每一件事（笼络能人，管理行政，战争），无论大小，都是在朝不被吞灭，不断突破自己的困境，朝一统天下的目的方向而去的。** 而不是花在纯娱乐上面的。

- I am a slow walker, but i never walk backwards.
我走得很慢，但我从不后退。—— 林肯

- **不要站在原地哭，即使哭泣，也要在移动中哭泣。**
工作、吃饭、运动、休息、社交……再难过，这些该做的事情还是要做。因为秩序生活本身会帮你复原。**走着走着，你会发现，让你掉泪的事已经在你身后了。**

- 易中天: 面对一条大河，许多人都不敢过去。我却摸着石头一步步的走了过去，**当别人嘲讽我说，你看这人弄的是一身泥泞，满身臭水的时候，打不起！我已经在河对岸了！你们还在河那边！**

- 预测未来最好的方法，就是去创造它。—— 林肯

---

==== 我们的自我定义(定位)和自信心, 是被我们的行为锻造出来的。

我们的自我定义(定位)和自信心, 并不是在自己的头脑中构造的，而是被我们的行为锻造出来的。不去做，光靠想象、心理鼓舞，没有事实支撑，你很难真正认同自己。

正如郭德纲所言, 人的自我看法和想法, 是随着环境的变化而不断变化的.

---


==== 如果一个人的“真实自我”经常遭受否定和打压，就会造成原生自我怀疑。


**一个高自尊的人，会觉得“我的存在是有意义的”“我是有能力做很多事情的”，哪怕失败了，也并会动摇他对自身价值的认知。**

一个低自尊的人，经常落入自我怀疑之中，哪怕成功了，也很容易归因于身外之物的外因，而非归因于自己的能力。这种状态的本质是什么呢？

1. 很大程度上，它跟我们成长过程中，所接受的“剥离”有关。 +
什么叫剥离呢？我们每一个人都有自己的天性，这是我们对自己的自我认知；但是在成长过程中，我们周围的人，包括家人、老师、舆论……会不断地给我们灌输一个信息：什么样的做事才是“正确”的，什么样的人的表现才是“好的”；你只有怎样做，才能成为“对“。于是，你逐渐丧失了从自我天性行为上来建立自信心的立足出发点。所以你一直在关注别人的行为，而非成为真正的自由自己。
+
**童年时期，如果一个人的“真实自我”经常遭受否定和打压，就会造成原生自我怀疑。**


2. **容易自我怀疑的人，有一个心理毛病：总是把“过去的我”的权重调得很高，却喜欢把“未来的我”的权重调得很低。** 这导致了你思维与行为惯性的固化。你在用以前的错误行为模式，来
一直延续应用在未来的事情上，结果就是不良后果的延续。


那么正确的心理态度应该是怎样的？

**变"自我沉浸"为"自我抽离"**. 自我抽离，指的是用第三人称“跳出来”，**从更高的角度看待这些场景，把自己抽离出来。这样考虑**：

- **造成这些问题的原因是什么？它的深层原因和直接原因分别是什么？其中有哪些是由于我行动不当所导致的？有哪些是我无法控制、无法决定的**？
- 如果换了别人，他是否会跟我碰到一样的问题，会做得比我更好吗？
- 这个问题有哪些可能的结果？它们发生的可能性有多高？对我有多大的实质影响？很多无论何种结果，其实对你都没有实质性影响。

---

==== ★ 每个人都偏爱自己的主张——不是因为这是他(她)想出来的，而是该主张与他(她)的潜在信仰和偏好相适应（一致）。

“异质相斥，同质相适”效应：每个人都偏爱自己的主张——不是因为这是他(她)想出来的，而是该主张与他(她)的潜在信仰和偏好相适应（一致）。

---

== ----- -----

---


== *先建立起"信任"后, 才会有"情感"*

==== ★ 做生意之前, 首先要建立起别人对自己的信任.

**做生意之前, 首先要建立起别人对自己的信任. ** 换位思考:  **你不相信别人, 你就不会放心去和别人做金钱交易.** +
如果说客户只认识到了你的价值，但是并没有建立起对你的信任，一切就不会有下一步进展。 +
双方已然失去了基本的信任，没有这个误会它也得有那个误会，没有事它也会生出事儿来。

---


==== 必须先建立情感, 然后才有可能说服对方.

在对方心中还未建立起亲和性、可信度和权威感的情况下，就想说服对方, 是很少会成功的.  -- **必须先建立情感, 然后才有可能说服.  ** +
人与人, 你与陌生人之间的关系, 肯定是从最冷, 最敌意, 再到熟悉亲近的. 所以你生活中遇到陌生人对你恶语相向, 是非常符合这个逻辑的.

某些药，是为别的药服务的，它们被叫作“药引子”；同样，某些沟通，是为了让接下来的沟通更顺畅，这种作为工具的预备性的沟通，可以叫作“工具性沟通”。 +
在开展实际对话之前，我们有很多准备工作要做；在对话从浅水区渐渐迈向深水区的过程中，我们也需要先建立起更深的情感联系, 与基本共识. 即, 步步为进. (即: 郭德纲的"闲白"所起的功能)

**所以, 那些演讲时，上台就急着煽情或者下结论的演讲者, 是不会有效果的.**

---

==== 内容有价值, 并不仅只包含"干货", 还包括让人有"启发"和"共鸣"的内容。传播的背后是情绪。

---

==== 吵架这件事本身并不严重，严重的是一方失去了申诉、辩论和判决的权利。两人的关系本是平等的，现在却有了高低。

吵架这件事本身并不严重，严重的是一方失去了申诉、辩论和判决的权利。两人的关系本是平等的，现在却有了高低。

夫妻之间应该建立一种就矛盾冲突进行讨论的机制（平等地位、就事论事, 相同权利）。如果双方用吵架去做这件事，很快地，焦点就不是本来要讨论的事情，而是“对方的态度如何不对”的问题了（**用错误的手段方法去解决问题，导致一波未平，一波又起。 手段上又产生了问题**）。

---

我并不是想跟你争个你高我低，你说咱们俩之间争这个有什么意思？夫妻之间，在人面前，还是自自然然平平和和的为好。夫妻俩非得在外人面前争个你高我低，或者展览不和，或者表演亲热，都只能让人觉着俗气。

---

==== 人与人的关系不是变热就是变冷，没有保持不变的中间的关系。

关系就如逆水行舟，如果没有得到改善、维持和发展，就会随着时间而衰退。**人与人的关系不是变热就是变冷，没有保持不变的中间的关系。**

---

==== 感情是流动的，因而必须要有不流动的合同来规范我们的行为。


---


==== ★ 人的价值，在遭受诱惑的一瞬间被显现。

---

==== ★ 称一称才知道轻重，量一量才知道长短，什麽东西都是如此，人心更是这样。

权，然后知轻重；度，然后知长短。物皆然，心为甚。::
-> 权：本指秤锤，这里用作动词，指称物。 +
-> **称一称才知道轻重，量一量才知道长短，什麽东西都是如此，人心更是这样。**

- 其实我并没有傻到每次约会都带女儿，我只是想试一下，他对我女儿的态度。
- 人的价值，在遭受诱惑的一瞬间被显现。

---

==== 人性管理更具有稳定性。而不像技术那样迭代极快，积累的经验很快就会过时无用。

作为历史长河中的一条连贯到未来的线，技术是永远在发展的，这决定了你有限的生命，不可能解决所有的技术问题。所以你只能占据这条无限的发展线上的一段时间，掌握住一段技术前沿，然后把技术交接给后来人。(任何一个奥运冠军退役,  但体育技术却不会停下脚步.)

你去哪呢？ 管理岗位。因为人性是自古不变的，更具有稳定性。历史书中的人性故事，对现在也是有启迪的。所积累的管人经验能用到老。而不像技术那样迭代极快，积累的经验很快就会过时无用。


---

==== 历史大事件不重要，每一个历史人物在大事件中发生的他们命运角度的改变，从原来的命运方向发生了锐角转折，转折点，才是你应该从中感悟到的重点。

历史是什么？每一个历史事件就是角度的转变，让人的命运直线的方向，产生角度上的偏转转变。**人生转折点，就是一个个锐角，就好像三棱镜让光线发生了偏折一样，设向了不同角度的方向。**

所以你在看史书时，**历史大事件不重要，每一个历史人物在大事件中发生的他们命运角度的改变，从原来的命运方向发生了锐角转折，转折点，才是你应该从中感悟到的重点。** 这才是正确的看史书的方式。

因为**脱离了人物命运的历史事件，是无用的信息**，是字典式的信息。和读者没有任何价值联系。**而只有从历史人物的命运转折中得到的启发，才是对你唯一真正有联系，有价值的营养内容。**

所以，这就是你读历史与官场小说时，正确的方法，与要得到的东西.

---

看历史，别记事，要看人。因为事在人为。人的个性和性格, 决定所有的历史事实走向。

---

== ----- -----


---

== *每个人自己的"个性"就是差异化的来源. 没有"个性"和"你自己独特的价值观", 你的差异性都没有了，客户怎么会选择你？*

==== ★ 话语权即政治， 表达出的话语即政治. 是你很重要的权力！

我的看法未必对别人有影响, 但对自己却很重要。这表达了你自己的价值排序, 好恶、爱憎，等等。 +
“那是他的价值观，我说的是我的！” +
*这一类问题往往并没有谁对谁错，关键要逻辑自洽.*

---

==== ★ 世上没有绝对唯的一定义, 定义内容是人赋予的, 每个人都有自己的定义

智慧是一种善于明察秋毫的能力，因此对同一概念的多种定义, 即是一种更好的观察细微差别的方法 (**对任何一个概念, 世上没有绝对唯的一定义, 定义内容是人赋予的, 每个人都有自己的定义**)。真正的智慧是把握合适的分寸而不是简单地谈论对与错。

---

==== 在公共舆论上, 少数人密集持有的观点, 能够抵消大量冷漠的人的观点（会叫的孩子有奶吃）。

当公众未能对一些事物提出观点时，这些“无所谓”(没发出声音, 沉默)（不管是主动的还是被迫的）的观点,  缺乏激情，不密集，就不能够影响政治家。因此, “炙热”的观点在任何时候都能击败“温和”的观点。 +
在许多问题上，普通大众因为缺乏相关知识, 或缺乏明确的意见，这时,  少数人的密集关心，就可能会主导民意测验的结果。 +
所以, 所谓的“公共”舆论，只不是一个小团体的观点, 而不代表大众的想法.

---

==== ★ 人最怕的是没有个性。你的差异性都没有了，客户怎么会选择你？

人最怕的是没有个性。 *没有个性，你就只能做别人的影子或者传声筒。都不用说你的优势在哪里了，你的差异性都没有了，客户怎么会选择你？* 我们要让客户知道我们的独特，这一点非常重要。成功就是成为你想成为的人。

你自己, 在家人, 朋友中, 也永远不可被别人替代. 你永远是你. 对他们来说是独一无二的你. +
*人是一个“活”的东西，有变化性，因此没有任何人能定义你！说死你.*

- 你给我留下了非常深刻、非常良好的印象，虽然具体细节我忘记了，但我记住了你。

- 做到人人都尊重你，远远比单纯的喜欢更重要。因为**敌人可以不喜欢我，但是优秀的敌人会尊重我，他们尊重我的原因来自我的人格与才智。** "喜欢"可能是情感的，而"尊重"却是理智的。（裔锦声）

- 遇到比你有钱的人，请不要自动的卑躬屈膝，除非…他有要把他的钱给你… 而**通常有钱人，并不会把钱送给随便就对他们卑躬屈膝的人。**

- 把话用你有感觉的方式讲出来，不要依赖名人讲话的套路，即使不流畅、多费字句，都没关系的。   +
**电视上每个主持人，如果都只是拷贝其他之前的主持人的讲话的方式，哪里会有这么多各式各样的主持风格来？**大家都长一个样子，分不出谁是谁了。

- *同质化艺人过多，会降低每一个偶像的不可替代性*，最终导致粉丝社群的黏性下降，缩短每一个偶像产品的变现周期。

- （**所以“设计师主不有自己的风格？“你只会变成可无缝替换的标准件螺丝！**自我阉割。这句话完全是站在资本方立场做出的，对资方有利，而不利于设计师本人）

- *如果是千篇一律的作品，有什么必要存在？总是要有点不一样的内容.*


---

==== 这些路不是用来局限住你的，而只意味着提供你一些选择的途径. 没有创新精神的人永远也只能是一个执行者。

- 事情都是人做出来的，规则（不管是公司的，还是国家的）都是人制定的，只要是人制定的，就必然是依附于某一事件段（特定时期）与特定场合的。**只要是人制定的、做出来的，就一定是有漏洞的（不完善的）、可以改进的。(否则, 人类社会中的一切就不会再发展.)** 世界上没有绝对的东西，也就意味着人在对待规则的限制、在对待事情的把握，与人的交道上，是可以自己用各种手段来更灵活多变、有效地达成目的的。 +

世界本无路，走的人多了，也就成了路。重要的是，*这些路不是用来局限住你的，而只意味着提供你一些选择的途径*（你有特立独行的自己的道路）。+

**所有伟大的真理开始都离经叛道。**权威的思想将它的某些力量赋予敢于向它挑战的人。**没有创新精神的人永远也只能是一个执行者。** +

敢于为前辈之不敢为。所有的事都是做出来的.

---

- **“理在事中”，能成事就是有理。世事往往是“以迂为直”。如果两点之间的直线阻力却最大，那么这根直线，其实是最远的路径。** +
-> 所谓效率 (投资回报率)，就是抛弃笨拙的方法，用我们知道的最好方法去工作。 +
-> 在“我是对的”和“有效果”之间，你必须做一个选择。你认为的好坏，和你的婚姻关系相比较，哪个更重要？

---

== ----- -----

---

== *因为你能保护手下的利益, 他们才愿意跟你, 因为才能不吃亏.*

==== 一个能保护自身权益的人，就一定有能力保护公司所有手下人的权益

- 他们替我加薪的主要原因, 是因为我能“舍命”保护自己的权益。“*一个能保护自身权益的人，就一定能保护公司的权益。因为你是一个不会向生活和障碍妥协的人.*" +
因为你能保护手下的利益, 他们愿意跟你, 才能不吃亏. ( 想象中国历史上的军阀节度使)

---

- 将要赚到的钱应该如何分给各级参与者，让更多人能把他的资源投入到你的事业中, 来帮你 (连同他一起)做大. +
他第一次挣了100万，分出80%给手下人，结果，大家一努力，第二次挣回来就是1000万！即使他这次把90%分给大家，自己拿到的也足有100万。等到第三次的时候，大家打下的江山可能就是1个亿。

---

==== 不要让他人形成对你不该有的条件反射. 不要让他在他的头脑中形成你不希望的负面经验：你软弱可欺。

- 如果别人对你没有善意，你就要做出反击.（*不要让他在他的头脑中形成你不希望的负面经验：你软弱可欺。不要让他人形成对你不该有的条件反射*）。 +
你应该学会为自己的权利而战，如果你做不到，你一生都将只是一个懦夫，被世界上那些恃强凌弱的人推来搡去。

- Don't give them the satisfaction of being insulted.   +
不要让他们从侮辱你中得到成就感.

---

==== 有的人总是白干活, 你不仅会失掉你应得的钱，还会贬低自己在别人眼中的价值。

不要对自己提出提高薪水的要求感到愧疚：最让我厌烦的事情之一，就是有的人总是白干活。 *不要把自己白白捐献出去，否则，你不仅会失掉你应得的钱，还会贬低自己在别人眼中的价值。*

你最低所需要的, 不等于你的价值。在研究生时，我一年12,000美元也活得很不错。可是，我会因为生存只需要12,000美元, 就只要求拿这么多的薪水吗？ *如果你只想着你需要的程度（维持最低生活的），你永远也不会得到你所值的（与你价值相符的）。*

---

==== ★ 追取晋升, 这恰恰是一个人雄心的反映

通过各种手段(与高管有联系)获得上升(晋升)没什么不好意思的,  *这恰恰是一个人雄心的反映, 当前的低下"现状"不匹配自己的真正能力!*

---

- 要是我不主动去做这件事，他们可能永远也不会给我这个机会。(你必须主动提出转岗!)

我整天坐在自己的工作隔间里，勤勤恳恳地跟踪着订票动向。全都是数据分析，我被同事们誉为“微软Excel女王”。这就是我为什么去要读研究生吗？为了以漂亮的电子数据表格而闻名吗？我都干了些什么工作？我是个喜爱与人打交道的人，我渴望直接为客户服务，提高相关的技能，可是我几乎没有机会离开自己的办公桌。

我的经理提到了美伦旅游公司的一项要求，我的大脑开始迅速运转。我离开电脑屏幕，到客户面前露脸的机会来了。

随后，在一次与我的老板面对面会谈的时候，我告诉他我想跟美伦旅游公司谈一谈，了解一下他们对应用软件的要求，看我们萨柏瑞公司能否在预算内开发出来。我告诉他我不愿意萨柏瑞公司失去这么一个大好的收益机会（注意这种巧妙的说话方式，把公司的利益放在首位），我会把这份工作当作我目前工作职责的一部分。老板说那当然好，有什么不可呢？

我主动去研究新产品, 而且不要求额外的费用。我无偿做这项工作，不过这是短期的，因为我看到了长期的回报。我也感觉到，这是我表现自己非数字密集运算才能的难得机会。毕竟，*没有人知道我具有跟客户打交道的能力，要是我不主动去做这件事，他们可能永远也不会给我这个机会。*

我给客户打电话、面谈了解技术上的规格和要求。我撰写业务计划、制定成本收益分析和收入模式，还将其呈给了高管层以取得批准。

我的努力为公司带来了收益，也为我带来了好处：萨柏瑞公司批准了这个方案，开发了那项产品，我被提拔为产品经理。我埋首于Excel表格的时代结束了。

你在讲出自己想要的工作调整的时候，无论是重新安排还是工作时间变动，**都要强调这对你的雇主会有什么影响，而不是对你自己。不要说“我需要”，或者“我想”，要在老板还没有来得及说出他们关心的问题之前，就打消他们的顾虑**：工作调整会损害到你的业绩吗？会给公司增加成本吗？你负责的客户和业务会受到损失吗？

---


==== 主管经理很少会有时间仔细地考察每个申请职位的人，他们更不会去说服沉默谨慎的人申请职位。机会的确会青睐那些积极争取机会的人。

我在谷歌工作的6年半时间里，我注意到，一般情况下，就积极争取机会而言，男性比女性行动得更快。**当我们宣布有新的空缺职位或是开始新项目时，男员工们都一个个来敲我办公室的门，毛遂自荐，向我解释为什么他们是新的领导职位的最佳人选。**

即使在一项新的空缺职位产生前，男性也更有可能去尝试获得成长的机会。

我已经和女性员工有过多次谈话，她们对我的鼓励通常作此回应：“我在这方面可能不是很擅长”，“这项新工作听上去很令人兴奋，但我没有类似的工作经验”，或“现在的工作中我还有许多要学习的”。印象中我似乎从没与男员工有过这样的对话。

- **感觉自信或假装自信，对于争取生活中的机会是必要的。机会的确会青睐那些积极争取机会的人。**

- 抓住机会尤为重要。**主管经理很少会有时间仔细地考察每个申请职位的人，他们更不会去说服沉默谨慎的人申请职位。**

- 机会正是来自一个人对某件事的全情投入，而这件事随后就会成为他们的工作内容。

- 在工作上积极主动一定会带来回报。**如果一个人总是等着别人告诉自己该做什么，我们就很难设想他能成为领导别人的人。**


---

==== ★ “面子”这种东西就不是靠别人“给”，而是靠自己“挣”的!

---


==== 拒绝，是你表达自己职业意愿的一个机会。

**你有责任心、勤奋、容易合作，也会有副作用：一旦你有了这样的声誉，就意味着人人都想把活交给你干。** 但不是每件事都对你有利，对无助于你事业发展的任务，说“不”。

你应该分清楚，什么时候工作不适当，或者不公平地侵犯了你的私人时间。所以, 说“不”会给你换来信用，会给你换来时间。

**说“不”不会让别人觉得你嫌任务重或能力差，反而会让你是一个目标明确**, 充满自信的商界女性（Amy Henry是女性）。**人们知道一个人不会说不，就证明他不能按照轻重缓急安排自己的时间。**

**明确了是非界线而且敢于去说“不”，实际上反倒会赢得更多的尊重。 你自己要尊重你的私人时间，别人也会尊重你的私人时间（在他人脑中留下你的烙印，控制你在他人眼重的形象、为人）。**

记住，说“不”的时候，语气要诚恳、明确、直截了当。 不要不好意思或者询问是不是可以说“不”。要坚定、明确。如果这样，你会受到尊重。

如果可能，还要提供一个替换方案。

我的老板要我负责我们自己公司的、不是客户方的一项大型软件执行项目。尽管我认识到这个项目与公司的目标一致，可是与我的职业目标不一致，我的职业目标是升到主管层，并与客户打交道。如果我接受这项新任务，就会减少我与客户合作的机会。

我第一次拒绝了要分配给我的一个项目。这一步有些冒险，可是在我解释了出于职业上的考虑，我为什么觉得这项工作跟我的职业道路有出入后，老板表示理解。 **拒绝，也是我表达自己职业意愿的一个好机会。**

在你的事业中及早养成这样的习惯，你才能前进、发展得更快，因为这样你才不会陷入繁忙的工作中不能自拔。


---

你可以说不的情境有：

- 可能会将你定位在一个角色上、而那个角色与你的职业目标不符的工作。（会令你职业生涯走偏，或浪费你最终抵达目标的时间）

- 不会给"有权力推动你 向理想职业路线前进的人物，留下特殊印象"的任务。（吃力不讨好的任务，不能给自己带来利益的工作）

- 不在你职责范围内的工作。

- 你不愿在自己的简历中提及的工作。（给你形象带来负面影响的工作）

- 经验不足、才智不强的人也能轻易应付的工作。对你的智力没有挑战性、但却会消耗你每天时间的工作。（对你已是垃圾工作）

- 确实不属于你份内的繁忙工作和行政事务，以及诸如定餐、送夜间邮包等应由助理处理的工作。（垃圾工作、低价值工作）

要分辨对你提出的各种要求，一定不要让自己总是接受份外的、对你的职业发展没有助益的任务。

---


== ----- -----

---


== *广揽天下豪杰为我所用*

==== 跟更成功的人合作, 学习高人的思维模式

- 一个人要成功。有几个方法： +
① 他必须帮成功者工作(是敲门砖)。 +
② 当他们开始成功的时候，也开始跟更成功的人合作(学习高人的思维模式)。 +
③ 当你越来越成功的时候，要找成功者来帮你工作(曹操广揽天下人才和英雄)。你为什么能赚10万美金？原因有三个。你的习惯、你所交的朋友、你核心圈的人。

- *你做的是啥，来的就是啥人。*   +
你做什么层次的事情和事业, 就会交接到什么层次的人. (想想曹操)

- 在道路上寻找战友，而不是拉朋友陪你上路。   +
Distance doesn't separate people,Silence does!

---

==== 不懂得如何让别人为自己做事，等于不懂得如何在乱世中生存。(曹操, 刘备)

不懂得如何让别人为自己做事，等于不懂得如何在乱世中生存。(曹操, 刘备)   +
OPT与OPM——运用别人的时间与金钱。

---

==== 要像政治家一样拉拢合作, 而非控制.

你开公司不能想着要“驾驭”人才，**特别NB 的人才，也不会让你“驾驭”的。**所以要像政治家一样拉拢合作, 而非控制. (曹操与豪族的合作借力关系)

---

== ----- -----

---

== *权力*

==== ★ 什么样的人更容易获得权力呢？答案是：外向的人。四种上位手段, 都有一个共同的核心点：找到合适的人(能支持你, 帮你上位的人)，影响他。与“高权力”关系最强的，是"政治行为"(广揽天下英雄来抬己) 和"获取个人声望行为"。

美国加州大学伯克利分校的心理学教授卡梅隆·安德森（Cameron Anderson）等人就在《美国国家科学院院刊》（PNAS）上发表了一篇论文，讨论了“坏人”和“权力”的关系.

先要定义什么是“坏”，什么是“权力”?

- 安德森等人采用大五人格, “宜人性”越低，就越“坏”。
- “权力”的衡量并不是看职位的高低, 因为职位不代表真正权力. 所以，作者测量了一个人在控制下属、操纵他人、影响决策等方面的得分.

以前, 研究者的方法是测一下受试者“坏不坏”，然后测一下“有没有权力”，再看两者之间有没有关系。但是，这种方法分不清人们是因为够坏才获得权力，还是有了权力才变坏的。

这次的研究, 从1999年跟踪到2008年.  最终收集了457人的权力指数。

得出的结果是：坏不坏跟能不能获得权力没关系。无论你是自私冷漠的坏人，还是无私热情的好人，都不会帮你获得权力。

那么什么样的人更容易获得权力呢？答案是：外向的人。
数据显示，那些在大五人格“外倾性”维度上得分更高的人，未来更容易获得权力。

获得权力, 上位有四种手段 :

1. (支配—攻击行为) : 拳头大的, 有理 ---- 这是许多动物遵循的规律。

2. (政治行为) : 权力是政治的主题，核心就是“打天下的时候人多，分天下的时候人少”。美国政治学家梅斯奎塔指出，**谁能抓住核心支持者，谁就能掌握权力。** 隋末李渊得到了关陇贵族的支持，才有了后面的盛唐。

3. (公共行为):  **“欲取先予”, “互惠原则”: 在获取权力之前，先施惠以获得别人的信任和认可。** 不管是“仁义君子”刘备、还是“散财童子”宋江，不论是真君子也好，伪君子也罢，总之都获得了权力。

4. **(声望行为) : 获取自己的声望. ** 鸫鹛这种鸟有个特性，声望最高的大首领会给小鸟喂食、给大家放哨，如果有其他鸟想代替大首领放哨，大首领就会攻击它。 **说白了就是争夺“为人民服务”的机会。对应到人类社会，如果你有能力，而这种能力又能给大家带来帮助，给自己带来声望，就更容易获得权力。**

**这四种手段都有一个共同的核心：找到合适的人(能支持你, 帮你上位的人)，影响他。**

用暴力让人害怕也好，收买人心也好,  积累自己的声望让人尊敬也好，**本质都是在"影响他人"。** 那么, 这四种手段跟“外倾性”有什么关系?

研究者发现，**与“高权力”关系最强的，是"政治行为"和"声望行为"。**
同时，那些比较“坏”的人, 更容易做出“支配—攻击行为”，但是很少做“政治行为”、“公共行为”、“声望行为”。
**而外向的人，更容易做出以上四种行为**。

也就是说，“坏人”更容易通过支配、攻击别人帮助自己获得权力，但是很少为人民服务，不在意自己的声望，这便阻碍了他们获得权力。两者抵消，优势就没了。
而外向的人，虽然也会做出支配攻击行为，但是也善于处理关系，所以更容易成功当领导。


---

==== 供需失衡, 带来权力

- 事实是，人口红利本质上并不是劳动者的红利，而是资本的红利。



---

== ----- -----

---

== *政治*

==== ★ 政治里面有非常高层次的需求，你如果能够涉及到客户内部的高层次的这种政治利益的种种冲突，能发现很多机会，而不是去简单的满足他一些基本上的需求而已。

对客户是需要引导的，你要启发。客户的需求是不一样的，不同的人他有不同的需求，三扣是低层次的客户的低层次的需求。**如果你无法启发客户的高层次的需求，那你就只好把自己混同于其他那些低层次的销售人员。人往低处走一定比人往高处走要容易**，做销售，如果你把自己混同于低层次的这种销售，最后你一定是做到了所有的客户全是低层次的客户。

**还有政治上的需求，情感上的认同需求，有很多，都需要你去启发。**    +
**政治里面有非常高层次的需求，你如果能够涉及到客户内部的高层次的这种政治利益的种种冲突，能发现很多机会(想想中国历史, 三国志里面的政治斗争和说客游说)，而不是去简单的满足他一些基本上的需求而已。**

---

==== 不是说把自己变脏，而是说把自己弄得容忍度要大一些 (亦正亦邪)，要不然你就没法运作一个很大的事情。

我虽然反感商业的暧昧、灰色的、不体面的一面，但这恰恰是做成一个事业的必经之路。**不是说把自己变脏，而是说把自己弄得容忍度要大一些 (亦正亦邪)，要不然你就没法运作一个很大的事情。**

---

==== ★ 大家都有矛盾，但是这个矛盾都有化解的可能，只要我确保你们之间的矛盾大于你们和我之间的矛盾，你们就会永远争取我的支持。

战略和战术之间的区别：

- 战术的目标，就是赢。
- 而**战略的目的，是我推动当前的均衡向下一个均衡点转化，并使自己在下一个均衡点中，那个优势稍微大一点点。**
围棋中的定式，不是教你怎么赢对方，而是达成一种两分的结果，不是你死我活，是你也活我也活，但始终我比你多几目 ，我活得比你好一丢丢 ，就是赢。

毛泽东有句话 ： “谁是我们的朋友，谁是我们的敌人， 这是革命的首要问题 。**朋友搞得多多的，把敌人搞得少少的， 革命就赢了。**” 这是一种典型的战术思维。

梅特涅讲过一句名言，他说， **我控制欧洲局势的心法其实就是一条，就是确保所有国家之间的矛盾， 要大于他们和奥地利之间的矛盾 。**

就是敌人和朋友搞清楚有那么重要吗？ **大家都有矛盾**，但是这个矛盾都有化解的可能，**只要我确保你们之间的矛盾， 大于你们和我之间的矛盾，你们就会永远争取我的支持，** 所以我奥地利虽然国力不强，但是我就是控制欧洲的局势。这就叫战略思维。

中国人经营南海，主张搁置争议，共同开发。原来的均衡是， 我要在主权这个矛盾下和菲律宾这样的国家去谈什么国际法、海洋法，没准儿还把美国招进这个格局来，这个谈法我是吃亏的。   +
**所以我搁置它，我推动这个均衡往下一个均衡去转化，转化矛盾到什么？——我们共同开发。** 开发远洋海岛这个东西你以为容易啊，**这是比拼国力，所以就能导致我的优势扩大。矛盾就转化到对我有利的那个主场上来了。** 你美国人总不能来共同开发吧，你根本不是南海的周边国家。

---

== ----- -----

---

== *教育孩子*

==== ★ 你是否在很多情况下，担心其他事物，其程度要超过对自己或孩子成长及情感关系的重视？

---


==== 美国幼儿园给家长的备忘录

这是一份《美国幼儿园给家长的备忘录》是老师以孩子的口吻，提醒父母对待孩子时的注意事项。

1.  *别溺爱我。我很清楚地知道，我不应该得到每一样我所要求的东西，我哭闹不休其实只是在试探你。*
2. 别害怕对我保持公正的态度，这样反倒让我有安全感。

3. 别让我养成坏习惯。在年幼的此刻，我得依靠你来判断好坏和对错。
4. *别让我觉得自己比实际的我还渺小*，这只会让我假装出一副和我实际年龄不符的傻样。

5. 可能的话尽量不要在人前纠正我的错误，我会感到很没面子，进而和你作对。你私下提醒效果会更好。
6. *别让我觉得犯了错误就像犯了罪*，它会消弱我对人生的希望。

7. 当我说“我恨你”的时候别往心里去。我恨的绝对不是你，我恨的是你加在我身上的那些压力。（对事不对人）
8. 别过度保护我，怕我无法接受某些“后果”。很多时候，我需要经由痛苦的经历来学习。

9. 别太在意我的小病痛。有时，我只是想得到你的关注而已。
10. 别对我唠叨不休，否则我会装聋作哑。

11. *别在匆忙中对我许诺。当你不能信守诺言时，我会难过，也会看轻你以后的许诺。*
12. 我现在还不能把事情解释的很清楚（表达能力），虽然有时我看起来挺聪明的。

13. 别太指望我的诚实，我很容易因为害怕而撒谎。
14. 请别在管教原则上前后不一，这样会让我疑惑，进而失去对你的信任。

15. *当我问你问题的时候，请别敷衍我或者拒绝我，否则我将停止发问，转向别处寻求答案。*
16. 我害怕的时候，不要觉得我很傻很可笑，如果你试着去了解，便会发现我当时有多恐惧

17. 别对我暗示你永远正确、无懈可击，当我发现你并非如此的时候，那对我将是一个多么大的打击。
18. 别以为向我道歉是没有尊严的事。一个诚实的道歉，会让我和你更接近，更尊重你，感觉更温暖

19. 别忘记我喜欢亲自尝试，而不是被你告知结果。
20. 别忘了我很快就会长大。对你来说，和我一起成长是很不容易的事，但请你尝试一下吧。



---
