
= 时间
:toc:

---

== 时间

==== -> 在学校，学生每学期收到一张成绩单。而在现实生活中，大多数成年人都不会收到定期的人生成绩单。

许多人在学校里学得很好但在离开时，却没准备好在生活中成功的赢配方。

你的财务报表就是你离开学校后的成绩单，它是成年人的成绩单。另一张成绩单是你的年度体检报告，通过验血和其他检查程序来告诉你的健康状况及需要改进的方面。人的一生中，会有很多不同的成绩单，但个人财务报表是最重要的之一。

*在学校，学生每学期收到一张成绩单。而在现实生活中，大多数成年人都不会收到定期的人生成绩单。*

一个孩子要在一生中达到职业和财务的成功，需要学习3种基本的赢配方： ①学习赢配方 (高效学习)；不同的人有不同的学习赢配方；②职业赢配方 (事业)；③财务赢配方 (退休养老)。

---

==== 为什么你觉得越老，世界约对你温柔呢？

人到中年以后，时常会觉得孤独，因为他一睁开眼睛，周围都是要依靠他的人，却没有他可以依靠的人。

你在三四十岁的时候，都能理解啥叫年龄歧视, 靠山山倒，靠人人跑.   **为什么你觉得越老，世界约对你温柔呢？**

我们必然要面对这个问题 -- 中年危机, 因为资本家是不会羞于去考虑这个问题的。

---

==== -> 你成功的速度, 一定要超过父母变老的速度。

原谅父母曾经对我们的不能和没有，因为她们已经尽力了。我曾经抱怨父母，是我们神化了父母。
行善行孝感恩这三件事情都不能等，不然就没有机会了。

---

== ----- -----

---

== 责任

==== -> 人活着, 就是在对抗熵增定律

薛定谔在《生命是什么》：“**人活着就是在对抗熵增定律，生命以负熵为生。**”

对于死亡的焦虑，是人类行为产生的重要动因。小到一个人的一生，大到人类文明的沉落起伏，都是生命在死亡表层之下寻找意义的结果。

---


==== -> 也许你是别人眼里的草，但你却是家人的天。


**也许你是别人眼里的草，但你却是家人的天。作为一个男人，要活出家的担当责任。**

芸芸众生，谁不是在苦中作乐。你看那些基层百姓拼命挣扎的样子觉得拙劣好笑，却没看到每个人都在努力活着，那是如杂草般顽强的生命力，为下一代过上更好的生活而努力。 +
一代又一代，没有例外，平凡又不平凡。

---

==== 你知道如何来衡量一只蜘蛛的优劣？ 是看它的网破坏后，它重新补织的速度

The greatest glory in life is not in never falling but in rising after falling. ——Nelson Rolihlahla Mandela  +
生命中最伟大的光辉不在于永不坠落, 而是坠落后总能再度升起


“**你知道如何来衡量一只蜘蛛的优劣？** 不是看它的体型、力量、毒性、速度，或是它织出的网……**是看它的网破坏后，它重新补织的速度……在你叹息的时候，或许有人已经补好了！**”——“鹈鹕”先生


---
