
= 政治
:toc:
:sectnums:
---


==== ★ 政治里面有非常高层次的需求，你如果能够涉及到客户内部的高层次的这种政治利益的种种冲突，能发现很多机会，而不是去简单的满足他一些基本上的需求而已。

对客户是需要引导的，你要启发。客户的需求是不一样的，不同的人他有不同的需求，三扣是低层次的客户的低层次的需求。**如果你无法启发客户的高层次的需求，那你就只好把自己混同于其他那些低层次的销售人员。人往低处走一定比人往高处走要容易**，做销售，如果你把自己混同于低层次的这种销售，最后你一定是做到了所有的客户全是低层次的客户。

**还有政治上的需求，情感上的认同需求，有很多，都需要你去启发。**    +
**政治里面有非常高层次的需求，你如果能够涉及到客户内部的高层次的这种政治利益的种种冲突，能发现很多机会(想想中国历史, 三国志里面的政治斗争和说客游说)，而不是去简单的满足他一些基本上的需求而已。**

---

==== 不是说把自己变脏，而是说把自己弄得容忍度要大一些 (亦正亦邪)，要不然你就没法运作一个很大的事情。

我虽然反感商业的暧昧、灰色的、不体面的一面，但这恰恰是做成一个事业的必经之路。**不是说把自己变脏，而是说把自己弄得容忍度要大一些 (亦正亦邪)，要不然你就没法运作一个很大的事情。**

---

==== ★ 大家都有矛盾，但是这个矛盾都有化解的可能，只要我确保你们之间的矛盾大于你们和我之间的矛盾，你们就会永远争取我的支持。

战略和战术之间的区别：

- 战术的目标，就是赢。
- 而**战略的目的，是我推动当前的均衡向下一个均衡点转化，并使自己在下一个均衡点中，那个优势稍微大一点点。**
围棋中的定式，不是教你怎么赢对方，而是达成一种两分的结果，不是你死我活，是你也活我也活，但始终我比你多几目 ，我活得比你好一丢丢 ，就是赢。

毛泽东有句话 ： “谁是我们的朋友，谁是我们的敌人， 这是革命的首要问题 。**朋友搞得多多的，把敌人搞得少少的， 革命就赢了。**” 这是一种典型的战术思维。

梅特涅讲过一句名言，他说， **我控制欧洲局势的心法其实就是一条，就是确保所有国家之间的矛盾， 要大于他们和奥地利之间的矛盾 。**

就是敌人和朋友搞清楚有那么重要吗？ **大家都有矛盾**，但是这个矛盾都有化解的可能，**只要我确保你们之间的矛盾， 大于你们和我之间的矛盾，你们就会永远争取我的支持，** 所以我奥地利虽然国力不强，但是我就是控制欧洲的局势。这就叫战略思维。

中国人经营南海，主张搁置争议，共同开发。原来的均衡是， 我要在主权这个矛盾下和菲律宾这样的国家去谈什么国际法、海洋法，没准儿还把美国招进这个格局来，这个谈法我是吃亏的。   +
**所以我搁置它，我推动这个均衡往下一个均衡去转化，转化矛盾到什么？——我们共同开发。** 开发远洋海岛这个东西你以为容易啊，**这是比拼国力，所以就能导致我的优势扩大。矛盾就转化到对我有利的那个主场上来了。** 你美国人总不能来共同开发吧，你根本不是南海的周边国家。

---

==== 胜兵先胜, 而后求战; 败兵先战, 而后求胜

胜兵先胜, 而后求战; 败兵先战, 而后求胜

有不输的把握和胜利的把握, 才开战。

---


==== 在攻城之前，先让敌人的军事能力（包括指挥能力和作战能力）严重短缺，根本无力抵抗，才算是高明中最高明的。

百战百胜，非善之善者也；/不战而屈人之兵，善之善者也。  +
故上兵伐谋（潜移默化改变势力），其次伐交（胡萝卜大棒威慑），其次伐兵，其下攻城。

只有**在攻城之前，先让敌人的军事能力（包括指挥能力和作战能力）严重短缺，根本无力抵抗**，才算是高明中最高明的。

---

==== 好的计策被执行，还要营造有利的态势，以辅助对外的行动。

计利以听，乃为之势，以佐其外。

好的计策被采纳执行，还要营造有利的态势，以辅助对外的行动。（要有先行铺垫，再实现你的核心目的）

---


==== 责难对方的言辞，是反对对方的论调，持这种论调时，目的往往是要诱出对方心中的机密。

难言者，却论也；却论者，钓几也。

责难对方的言辞，是反对对方的论调，持这种论调时，目的往往是要诱出对方心中的机密。

---

==== 想要除掉的人，就要放纵他，任其胡为，待其留下把柄时, 就乘机一举除掉他。

故去之者，从之；从之者，乘之。

想要除掉的人，就要放纵他，任其胡为，待其留下把柄时, 就乘机一举除掉他。

---

==== 替领导去得罪人是非常愚蠢的，领导比你有钱，比你有权，人脉比你广，即使这样，他都不去得罪人让你去得罪人.

有时候领导特别青睐某个新员工，其实就是把这个新员工当枪使. 无论在哪个企业，替领导去得罪人是非常愚蠢的，领导比你有钱，比你有权，人脉比你广，即使这样，他都不去得罪人让你去得罪人.

---

==== 善于指挥作战的人，总是能调动敌人而不被敌人所调动

[cols="2a,3a"]
|===
|Header 1 |

|善战者，致人而不致于人。/能使敌人自至者，利之也；/能使敌人不得至者，害之也
|**善于指挥作战的人，总是能调动敌人而不被敌人所调动。**
能使敌人自动进入我方预定区域，是以小利引诱的结果； +
能使敌人不能到达其预定地域的，是因为给敌人制造困难，设法使它别有顾忌而阻止了它的行动。

|善动敌者，形之，敌必从之；/予之，敌必取之。/以利动之，以卒待之。/故善战者，求之于势.
|善于调动敌军的人将帅，故意向敌军展示一种或真或假的军情，敌军必然据此作出相应的错误举动； +
**给予敌人一点实际利益作为诱饵，敌军必然趋利而来，从而听我调动。** +
所以， 善于用兵作战的人，总是从自己创造的有利作战态势中, 去追求胜利.


|利而诱之，怒而挠之，卑而骄之，逸而劳之，亲而离之。
|敌人贪心就用小利来引诱他上当； +
敌人容易冲动发怒，就设法挑逗他，使其失去理智； +
对于小心谨慎的敌人，要千方百计骄纵他，使其丧失警惕； +
敌人安逸就设法骚扰他，搞得他疲劳不堪； +
内部团结的敌人，要设法离间他，让他分裂。
|===

---

