
= 先建立起"信任"后, 才会有"情感"
:toc:
:sectnums:

---

== *先有信任, 后有关系*


==== ★ #做生意之前, 首先要建立起别人对自己的信任.#

**做生意之前, 首先要建立起别人对自己的信任. ** 换位思考:  **你不相信别人, 你就不会放心去和别人做金钱交易.** +
如果说客户只认识到了你的价值，但是并没有建立起对你的信任，一切就不会有下一步进展。 +
双方已然失去了基本的信任，没有这个误会它也得有那个误会，没有事它也会生出事儿来。



.标题
====
我(傅盛)当时在选择方向的时候，也考虑过电动汽车，汽车这个行业资金消耗量很大，但是有一点很好，你只要跟别人讲，大家都知道汽车是怎么回事，会有多大的规模。

我做机器人这个领域，最大的困难就是大家从来没有看见过（机器人这种产品）, 每个人脑子里的机器人都不一样。你最大的成本是达成共识的成本.

一个原本不存在的, 真正的创新东西，第一步是得获得"信任"。 对外, 市场的教育, 和用户对一个产品的认知, 是需要时间的。对内, 不能只是你一个人信，要让团队也要信，如何做到这一点? 产品数据的增长, 能给你确定性的信心往前走。即, "信心"的源泉, 要在一些事(正循环)上得到印证. 马云有一句话，「*绝大部分人不是因为相信而看见; 是因为看见后, 才相信*」。

我认为, 以用户为核心、快速迭代，不断让自己的产品跟市场需求契合，用小规模、快迭代的方式就是根本。 +
你看 Space  X 今天发射的火箭没有一枚是一样的，每一枚都在做改进、做验证. +


每个人只要想做一点事情，都会被质疑, 会看到让我自己不开心的报道。但是**你要学会怎么去克服这种压力，或者是接受这种压力，然后把它变得和你自己不太相关，**这是我这三年最大的一个修炼。
====



---

==== 不要欺骗别人，能被你骗到的都是相信你的人。

---

==== 必须先建立情感, 然后才有可能说服对方.

在对方心中还未建立起亲和性、可信度和权威感的情况下，就想说服对方, 是很少会成功的.  -- **必须先建立情感, 然后才有可能说服.  ** +
人与人, 你与陌生人之间的关系, 肯定是从最冷, 最敌意, 再到熟悉亲近的. 所以你生活中遇到陌生人对你恶语相向, 是非常符合这个逻辑的.

某些药，是为别的药服务的，它们被叫作“药引子”；同样，某些沟通，是为了让接下来的沟通更顺畅，这种作为工具的预备性的沟通，可以叫作“工具性沟通”。 +
在开展实际对话之前，我们有很多准备工作要做；在对话从浅水区渐渐迈向深水区的过程中，我们也需要先建立起更深的情感联系, 与基本共识. 即, 步步为进. (即: 郭德纲的"闲白"所起的功能)

**所以, 那些演讲时，上台就急着煽情或者下结论的演讲者, 是不会有效果的.**

---

==== 这块布擦的不是你们家地板，擦的不是你们家的机器，擦的是客户的心.

我妈从来没有买过电器，但是她说我要买海尔的电器，为什么？她说他们到家装空调, 会带一块布把这个地擦干净.   +
我说这块布要贵10％，这块布擦的不是你们家地板，擦的不是你们家的机器，擦的是客户的心。

---


==== ★ #要让所有人在任何事情中, 面子上过得去, 不让他们在任何场合难堪. 这就是会说话#


林小枫的疏忽在于不该当着孩子的面说。妈妈的话使儿子当当自尊心深受伤害。  +
有些话是不可以随便说的，即使是在夫妻之间——尤其是在夫妻之间！那是很伤人心的。

(郭德纲在三国评书, 关羽斩华雄前, 曹操和袁绍对关羽的不同态度中点评过 : *要让所有人在任何事情中, 面子上过得去. 这就是会说话.*)


---

==== ★★ #女对男，顺序首先是喜欢上对方的心, 然后才会对其肉体（性）产生兴趣，而非顺序相反。#

异性之间，顺序是先在喜欢一个人的性格特质，然后才会对其肉体（性）产生兴趣，而非顺序相反。 不首先对一个人产生心理上的喜欢，是不会对其肉体产生爱的，只会要么是单纯的性（对颜值高的），要么是恶心（对颜值低的）。

---

==== 如果一个男人的自尊心与虚荣心, 没有从妻子那里得到，他的情感, 就会转移到那个能给予他赏识与肯定的女人那里去。

我们希望对方把负面情绪不要带回家，其实这不可能做到。但是为了遵守自己的承诺，便会先找一个地方疏导，宣泄自己的情绪。如果这个地方碰巧有一个善解人意的异性，一些本来可以避免的感情关系便会发展出来.   +
**（当你对你的爱人关闭了情感交流的大门，你的爱人就会去寻找其它向她敞开的情感之门）。很多婚外情的开始, 就是源于家中的配偶不去了解另一方。  **

**如果一个男人的自尊心与虚荣心, 没有从妻子那里得到，他的情感, 就会转移到那个能给予他赏识与肯定的女人那里去。  **

先是夫妻两人的关系破裂了，第三者才会出现（第三者乘虚而入。家必自毁，而后人毁之）。

所以, 把情绪向伴侣说出来，与把情绪发泄在对方身上是两回事。

---

==== 内容有价值, 并不仅只包含"干货", 还包括让人有"启发"和"共鸣"的内容。传播的背后是情绪。

---


== ----- -----

---

== *情感是流动的*

==== 吵架这件事本身并不严重，严重的是一方失去了申诉、辩论和判决的权利。两人的关系本是平等的，现在却有了高低。

吵架这件事本身并不严重，严重的是一方失去了申诉、辩论和判决的权利。两人的关系本是平等的，现在却有了高低。

夫妻之间应该建立一种就矛盾冲突进行讨论的机制（平等地位、就事论事, 相同权利）。如果双方用吵架去做这件事，很快地，焦点就不是本来要讨论的事情，而是“对方的态度如何不对”的问题了（**用错误的手段方法去解决问题，导致一波未平，一波又起。 手段上又产生了问题**）。

---

我并不是想跟你争个你高我低，你说咱们俩之间争这个有什么意思？夫妻之间，在人面前，还是自自然然平平和和的为好。夫妻俩非得在外人面前争个你高我低，或者展览不和，或者表演亲热，都只能让人觉着俗气。

---

==== 人与人的关系不是变热就是变冷，没有保持不变的中间的关系。

关系就如逆水行舟，如果没有得到改善、维持和发展，就会随着时间而衰退。**人与人的关系不是变热就是变冷，没有保持不变的中间的关系。**

---

==== 感情是流动的，因而必须要有不流动的合同来规范我们的行为。


---


==== ★ #人的价值，在遭受诱惑的一瞬间被显现。#

---

==== ★ 称一称才知道轻重，量一量才知道长短，什麽东西都是如此，人心更是这样。

权，然后知轻重；度，然后知长短。物皆然，心为甚。::
-> 权：本指秤锤，这里用作动词，指称物。 +
-> **称一称才知道轻重，量一量才知道长短，什麽东西都是如此，人心更是这样。**

- 其实我并没有傻到每次约会都带女儿，我只是想试一下，他对我女儿的态度。
- 人的价值，在遭受诱惑的一瞬间被显现。

---

==== 人不知亲-穷知亲, 心不知近-苦知近

人不知亲-穷知亲, 心不知近-苦知近

平时你不知道谁对你好，直到你遇到困难的时候；平时你不知道谁跟你亲，直到你穷困潦倒的时候.  +
指人在穷苦的时候，才能知道谁和自己最亲近。


---

==== 相形不如论心，论心不如择术

相形/不如论心，论心/不如择术

观察人的相貌, 不如考察他的思想; 考察他的思想, 不如鉴别他立身处世的方法。

---

== ----- -----

---

== *人在当时环境下的的情感抉择, 决定其人生历史走向*

---

==== 人性管理更具有稳定性。而不像技术那样迭代极快，积累的经验很快就会过时无用。

作为历史长河中的一条连贯到未来的线，技术是永远在发展的，这决定了你有限的生命，不可能解决所有的技术问题。所以你只能占据这条无限的发展线上的一段时间，掌握住一段技术前沿，然后把技术交接给后来人。(任何一个奥运冠军退役,  但体育技术却不会停下脚步.)

你去哪呢？ 管理岗位。因为人性是自古不变的，更具有稳定性。历史书中的人性故事，对现在也是有启迪的。所积累的管人经验能用到老。而不像技术那样迭代极快，积累的经验很快就会过时无用。


---

==== 历史大事件不重要，每一个历史人物在大事件中发生的他们命运角度的改变，从原来的命运方向发生了锐角转折，转折点，才是你应该从中感悟到的重点。

历史是什么？每一个历史事件就是角度的转变，让人的命运直线的方向，产生角度上的偏转转变。**人生转折点，就是一个个锐角，就好像三棱镜让光线发生了偏折一样，设向了不同角度的方向。**

所以你在看史书时，**历史大事件不重要，每一个历史人物在大事件中发生的他们命运角度的改变，从原来的命运方向发生了锐角转折，转折点，才是你应该从中感悟到的重点。** 这才是正确的看史书的方式。

因为**脱离了人物命运的历史事件，是无用的信息**，是字典式的信息。和读者没有任何价值联系。**而只有从历史人物的命运转折中得到的启发，才是对你唯一真正有联系，有价值的营养内容。**

所以，这就是你读历史与官场小说时，正确的方法，与要得到的东西.

---

看历史，别记事，要看人。因为事在人为。人的个性和性格, 决定所有的历史事实走向。

---
