
= 政治
:toc:
:sectnums:
---


==== ★ 政治里面有非常高层次的需求，你如果能够涉及到客户内部的高层次的这种政治利益的种种冲突，能发现很多机会，而不是去简单的满足他一些基本上的需求而已。

对客户是需要引导的，你要启发。客户的需求是不一样的，不同的人他有不同的需求，三扣是低层次的客户的低层次的需求。**如果你无法启发客户的高层次的需求，那你就只好把自己混同于其他那些低层次的销售人员。人往低处走一定比人往高处走要容易**，做销售，如果你把自己混同于低层次的这种销售，最后你一定是做到了所有的客户全是低层次的客户。

**还有政治上的需求，情感上的认同需求，有很多，都需要你去启发。**    +
**政治里面有非常高层次的需求，你如果能够涉及到客户内部的高层次的这种政治利益的种种冲突，能发现很多机会(想想中国历史, 三国志里面的政治斗争和说客游说)，而不是去简单的满足他一些基本上的需求而已。**

---

==== 不是说把自己变脏，而是说把自己弄得容忍度要大一些 (亦正亦邪)，要不然你就没法运作一个很大的事情。

我虽然反感商业的暧昧、灰色的、不体面的一面，但这恰恰是做成一个事业的必经之路。**不是说把自己变脏，而是说把自己弄得容忍度要大一些 (亦正亦邪)，要不然你就没法运作一个很大的事情。**

---

==== ★ 大家都有矛盾，但是这个矛盾都有化解的可能，只要我确保你们之间的矛盾大于你们和我之间的矛盾，你们就会永远争取我的支持。

战略和战术之间的区别：

- 战术的目标，就是赢。
- 而**战略的目的，是我推动当前的均衡向下一个均衡点转化，并使自己在下一个均衡点中，那个优势稍微大一点点。**
围棋中的定式，不是教你怎么赢对方，而是达成一种两分的结果，不是你死我活，是你也活我也活，但始终我比你多几目 ，我活得比你好一丢丢 ，就是赢。

毛泽东有句话 ： “谁是我们的朋友，谁是我们的敌人， 这是革命的首要问题 。**朋友搞得多多的，把敌人搞得少少的， 革命就赢了。**” 这是一种典型的战术思维。

梅特涅讲过一句名言，他说， **我控制欧洲局势的心法其实就是一条，就是确保所有国家之间的矛盾， 要大于他们和奥地利之间的矛盾 。**

就是敌人和朋友搞清楚有那么重要吗？ **大家都有矛盾**，但是这个矛盾都有化解的可能，**只要我确保你们之间的矛盾， 大于你们和我之间的矛盾，你们就会永远争取我的支持，** 所以我奥地利虽然国力不强，但是我就是控制欧洲的局势。这就叫战略思维。

中国人经营南海，主张搁置争议，共同开发。原来的均衡是， 我要在主权这个矛盾下和菲律宾这样的国家去谈什么国际法、海洋法，没准儿还把美国招进这个格局来，这个谈法我是吃亏的。   +
**所以我搁置它，我推动这个均衡往下一个均衡去转化，转化矛盾到什么？——我们共同开发。** 开发远洋海岛这个东西你以为容易啊，**这是比拼国力，所以就能导致我的优势扩大。矛盾就转化到对我有利的那个主场上来了。** 你美国人总不能来共同开发吧，你根本不是南海的周边国家。

---

==== 利而诱之，怒而挠之，卑而骄之，逸而劳之，亲而离之。

利而诱之，怒而挠之，卑而骄之，逸而劳之，亲而离之。

敌人贪心就用小利来引诱他上当；
敌人容易冲动发怒，就设法挑逗他，使其失去理智；
对于小心谨慎的敌人，要千方百计骄纵他，使其丧失警惕；
敌人安逸就设法骚扰他，搞得他疲劳不堪；
内部团结的敌人，要设法离间他，让他分裂。

---

==== 好的计策被执行，还要营造有利的态势，以辅助对外的行动。

计利以听，乃为之势，以佐其外。

好的计策被采纳执行，还要营造有利的态势，以辅助对外的行动。（要有先行铺垫，再实现你的核心目的）

---

