
= 人性, 心理学
:toc:
---

== 先建立起"信任"后, 才会有"情感"

==== ★ ->做生意之前, 首先要建立起别人对自己的信任.

**做生意之前, 首先要建立起别人对自己的信任. ** 换位思考:  **你不相信别人, 你就不会放心去和别人做金钱交易.**

如果说客户只认识到了你的价值，但是并没有建立起对你的信任，一切就不会有下一步进展。

双方已然失去了基本的信任，没有这个误会它也得有那个误会，没有事它也会生出事儿来。

---

==== -> 必须先建立情感, 然后才有可能说服对方.

在对方心中还未建立起亲和性、可信度和权威感的情况下，就想说服对方, 是很少会成功的.  -- **必须先建立情感, 然后才有可能说服.  **

人与人, 你与陌生人之间的关系, 肯定是从最冷, 最敌意, 再到熟悉亲近的. 所以你生活中遇到陌生人对你恶语相向, 是非常符合这个逻辑的.

某些药，是为别的药服务的，它们被叫作“药引子”；同样，某些沟通，是为了让接下来的沟通更顺畅，这种作为工具的预备性的沟通，可以叫作“工具性沟通”。

在开展实际对话之前，我们有很多准备工作要做；在对话从浅水区渐渐迈向深水区的过程中，我们也需要先建立起更深的情感联系, 与基本共识. 即, 步步为进. (即: 郭德纲的"闲白"所起的功能)

**所以, 那些演讲时，上台就急着煽情或者下结论的演讲者, 是不会有效果的.**

---

==== ★ -> 人的价值，在遭受诱惑的一瞬间被显现。

---


==== -> 人性管理更具有稳定性。而不像技术那样迭代极快，积累的经验很快就会过时无用。

作为历史长河中的一条连贯到未来的线，技术是永远在发展的，这决定了你有限的生命，不可能解决所有的技术问题。所以你只能占据这条无限的发展线上的一段时间，掌握住一段技术前沿，然后把技术交接给后来人。(任何一个奥运冠军退役,  但体育技术却不会停下脚步.)

你去哪呢？ 管理岗位。因为人性是自古不变的，更具有稳定性。历史书中的人性故事，对现在也是有启迪的。所积累的管人经验能用到老。而不像技术那样迭代极快，积累的经验很快就会过时无用。

== ----- -----

---

== 每个人自己的"个性"就是差异化的来源. 没有个性, 你的差异性都没有了，客户怎么会选择你？

==== -> ★ 话语权即政治， 表达出的话语即政治. 是你很重要的权力！

我的看法未必对别人有影响, 但对自己却很重要。这表达了你自己的价值排序, 好恶、爱憎，等等。

“那是他的价值观，我说的是我的！”

*这一类问题往往并没有谁对谁错，关键要逻辑自洽.*

---

==== ★ -> 人最怕的是没有个性。你的差异性都没有了，客户怎么会选择你？

人最怕的是没有个性。 *没有个性，你就只能做别人的影子或者传声筒。都不用说你的优势在哪里了，你的差异性都没有了，客户怎么会选择你？* 我们要让客户知道我们的独特，这一点非常重要。成功就是成为你想成为的人。

你自己, 在家人, 朋友中, 也永远不可被别人替代. 你永远是你. 对他们来说是独一无二的你.

*人是一个“活”的东西，有变化性，因此没有任何人能定义你！说死你.*


- 遇到比你有钱的人，请不要自动的卑躬屈膝，除非…他有要把他的钱给你… 而通常有钱人，并不会把钱送给随便就对他们卑躬屈膝的人。

- 你给我留下了非常深刻、非常良好的印象，虽然具体细节我忘记了，但我记住了你。

---


==== -> 敌人可以不喜欢我，但是优秀的敌人会尊重我的人格与才智

做到人人都尊重你，远远比单纯的喜欢更重要。因为敌人可以不喜欢我，但是优秀的敌人会尊重我，他们尊重我的原因来自我的人格与才智。"喜欢"可能是情感的，而"尊重"却是理智的。（裔锦声）

---


==== -> 如果是千篇一律的作品，有什么必要存在？总是要有点不一样的内容.

- 把话用你有感觉的方式讲出来，不要依赖名人讲话的套路，即使不流畅、多费字句，都没关系的。   +
**电视上每个主持人，如果都只是拷贝其他之前的主持人的讲话的方式，哪里会有这么多各式各样的主持风格来？**大家都长一个样子，分不出谁是谁了。

- *同质化艺人过多，会降低每一个偶像的不可替代性*，最终导致粉丝社群的黏性下降，缩短每一个偶像产品的变现周期。

- （**所以“设计师主不有自己的风格？“你只会变成可无缝替换的标准件螺丝！**自我阉割。这句话完全是站在资本方立场做出的，对资方有利，而不利于设计师本人）

- *如果是千篇一律的作品，有什么必要存在？总是要有点不一样的内容.*

---

==== -> 这些路不是用来局限住你的，而只意味着提供你一些选择的途径. 所有的超越前人, 开始都"离经叛道"。没有创新精神的人永远也只能是一个执行者。

事情都是人做出来的，规则（不管是公司的，还是国家的）都是人制定的，只要是人制定的，就必然是依附于某一事件段（特定时期）与特定场合的。**只要是人制定的、做出来的，就一定是有漏洞的（不完善的）、可以改进的。(否则, 人类社会中的一切就不会再发展.)** 世界上没有绝对的东西，也就意味着人在对待规则的限制、在对待事情的把握，与人的交道上，是可以自己用各种手段来更灵活多变、有效地达成目的的。

世界本无路，走的人多了，也就成了路。重要的是，这些路不是用来局限住你的，而只意味着提供你一些选择的途径（你有特立独行的自己的道路）。

所有伟大的真理开始都离经叛道。权威的思想将它的某些力量赋予敢于向它挑战的人。**没有创新精神的人永远也只能是一个执行者。**

敢于为前辈之不敢为。所有的事都是做出来的.

---

==== ->  如果两点之间的直线阻力却最大，那么这根直线，其实是最远的路径

**“理在事中”，能成事就是有理。世事往往是“以迂为直”。如果两点之间的直线阻力却最大，那么这根直线，其实是最远的路径。**

- 在“我是对的”和“有效果”之间，你必须做一个选择。你认为的好坏，和你的婚姻关系相比较，哪个更重要？

- 所谓效率 (投资回报率)，就是抛弃笨拙的方法，用我们知道的最好方法去工作。

---

==== -> 在公共舆论上, 少数人密集持有的观点, 能够抵消大量冷漠的人的观点（会叫的孩子有奶吃）。

当公众未能对一些事物提出观点时，这些“无所谓”(没发出声音, 沉默)（不管是主动的还是被迫的）的观点,  缺乏激情，不密集，就不能够影响政治家。因此, “炙热”的观点在任何时候都能击败“温和”的观点。 +
在许多问题上，普通大众因为缺乏相关知识, 或缺乏明确的意见，这时,  少数人的密集关心，就可能会主导民意测验的结果。

所以, 所谓的“公共”舆论，只不是一个小团体的观点, 而不代表大众的想法.

---

== ----- -----

---

== 因为你能保护手下的利益, 他们才愿意跟你, 因为才能不吃亏.

==== -> 有的人总是白干活, 你不仅会失掉你应得的钱，还会贬低自己在别人眼中的价值。

不要对自己提出提高薪水的要求感到愧疚：最让我厌烦的事情之一，就是有的人总是白干活。 *不要把自己白白捐献出去，否则，你不仅会失掉你应得的钱，还会贬低自己在别人眼中的价值。*

你最低所需要的, 不等于你的价值。在研究生时，我一年12,000美元也活得很不错。可是，我会因为生存只需要12,000美元, 就只要求拿这么多的薪水吗？ *如果你只想着你需要的程度（维持最低生活的），你永远也不会得到你所值的（与你价值相符的）。*

---

==== ★ -> 追取晋升, 这恰恰是一个人雄心的反映

通过各种手段(与高管有联系)获得上升(晋升)没什么不好意思的,  *这恰恰是一个人雄心的反映, 当前的低下"现状"不匹配自己的真正能力!*

---

==== ★ -> 一个能保护自身权益的人，就一定有能力保护公司所有手下人的权益

他们替我加薪的主要原因, 是因为我能“舍命”保护自己的权益。“一个能保护自身权益的人，就一定能保护公司的权益。因为你是一个不会向生活和障碍妥协的人.

因为你能保护手下的利益, 他们愿意跟你, 才能不吃亏. ( 想象中国历史上的军阀节度使)

---

== ----- -----

---

== ★ 美国幼儿园给家长的备忘录

这是一份《美国幼儿园给家长的备忘录》是老师以孩子的口吻，提醒父母对待孩子时的注意事项。

1.  *别溺爱我。我很清楚地知道，我不应该得到每一样我所要求的东西，我哭闹不休其实只是在试探你。*
2. 别害怕对我保持公正的态度，这样反倒让我有安全感。

3. 别让我养成坏习惯。在年幼的此刻，我得依靠你来判断好坏和对错。
4. *别让我觉得自己比实际的我还渺小*，这只会让我假装出一副和我实际年龄不符的傻样。

5. 可能的话尽量不要在人前纠正我的错误，我会感到很没面子，进而和你作对。你私下提醒效果会更好。
6. *别让我觉得犯了错误就像犯了罪*，它会消弱我对人生的希望。

7. 当我说“我恨你”的时候别往心里去。我恨的绝对不是你，我恨的是你加在我身上的那些压力。（对事不对人）
8. 别过度保护我，怕我无法接受某些“后果”。很多时候，我需要经由痛苦的经历来学习。

9. 别太在意我的小病痛。有时，我只是想得到你的关注而已。
10. 别对我唠叨不休，否则我会装聋作哑。

11. *别在匆忙中对我许诺。当你不能信守诺言时，我会难过，也会看轻你以后的许诺。*
12. 我现在还不能把事情解释的很清楚（表达能力），虽然有时我看起来挺聪明的。

13. 别太指望我的诚实，我很容易因为害怕而撒谎。
14. 请别在管教原则上前后不一，这样会让我疑惑，进而失去对你的信任。

15. *当我问你问题的时候，请别敷衍我或者拒绝我，否则我将停止发问，转向别处寻求答案。*
16. 我害怕的时候，不要觉得我很傻很可笑，如果你试着去了解，便会发现我当时有多恐惧

17. 别对我暗示你永远正确、无懈可击，当我发现你并非如此的时候，那对我将是一个多么大的打击。
18. 别以为向我道歉是没有尊严的事。一个诚实的道歉，会让我和你更接近，更尊重你，感觉更温暖

19. 别忘记我喜欢亲自尝试，而不是被你告知结果。
20. 别忘了我很快就会长大。对你来说，和我一起成长是很不容易的事，但请你尝试一下吧。

---
