= 0219
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome to EnglishPod.
My name is Marco.
My name is Catherine and today we have an elementary level lesson for you.
This one is especially for people who are interested in babies.
That's right.
Maybe you have a baby, you will have a baby, maybe you're pregnant and this is a great lesson for that because we are talking about a baby shower.
Okay, so before we get started, let's take a look at vocabulary preview and learn what exactly a baby shower is.
Vocabulary preview.
Okay, so a baby shower.
You would think that this is about bathing the baby, about giving the baby a bath.
No, not a real shower.
A baby shower or a bridal shower, these are parties.
Okay, they're parties.
And in this case, a baby shower is a party that you throw for a woman that is pregnant, right?
That's right.
My sister is going to have a baby.
I throw her a baby shower.
It's a party where all of her friends give her gifts.
Okay.
Yeah, it's a way to celebrate having a baby.
Okay, so they give her gifts, you'll play games as well as to like maybe guess the name of the baby or guess the sex of the baby.
Exactly.
Stuff like that.
Okay, so it's a very common thing.
I think it's mostly for women.
I don't really know if men have baby showers as well.
I don't think so.
I don't think so either.
But it's a very popular tradition in the United States and many other parts of the world.
So we're going to talk about that.
Let's listen to the dialogue for the first time.
Thank you for organizing this great baby shower for me.
I've always been to baby showers but never actually had one held for me.
Let's get started.
Okay, let's start opening some presents.
Oh, look.
What a great little bib for the baby.
This will definitely come in handy.
Oh, wow.
You also got me a stroller.
That's so great.
Thank you.
This next one is from Betty.
A hot chair and a car seat?
Wow, Betty, thank you so much.
I really appreciate it.
One more from Carla.
A playpen and crib?
Thanks Carla.
This is just what I needed.
Okay, that's all of them.
No more gifts.
Now, who wants to guess when the baby is due?
Um, I think my water just broke.
Get me to a hospital.
Ahh!
All right, so very interesting.
All the gifts that they got and definitely very useful because this is a very common items that you get for babies, right?
That's right.
All of this stuff is really, really valuable because if you have a baby or if your brother or sister has a baby, you'll notice that these are very common items.
So let's go through a couple of them in today's language takeaway.
Language takeaway.
Okay, so the first word that we're going to take a look at, the most common one and useful one for a baby is a bib.
Bib.
So babies are messy.
When they eat food, they get their food on their clothes.
So to protect the clothes, babies wear bibs.
This is a piece of cloth or fabric around their neck.
Okay, a bib.
And also sometimes you want to go out with your baby to the mall, you're walking and you don't want to carry him in your arms all the time.
So you need a stroller.
Okay, so basically a stroller is a chair on wheels for a baby.
Babies are heavy and as they get older, they get heavier.
And so this is a way to push the baby around, not carry the baby.
Right.
So the baby falls asleep so they can fall asleep in the stroller.
Exactly.
Okay.
And while talking about chairs, we're going to take a look at two different types of chairs.
First one is a high chair.
Okay, a high chair.
Think about the word high.
That means tall in this case.
A high chair is a chair for babies at the table.
So if you put a baby on a regular chair, they can't eat with adults.
They're too small.
So we give them high chairs so that they can sit a little bit higher and they can be at the table with adults.
Exactly.
So they're very common.
For example, you go to a restaurant, they will have a little high chairs if you have a baby or a small child.
So if you're at a restaurant, you have a baby, you ask for a high chair.
You say, do you have a high chair, please?
Yeah, perfect.
And well, if you're going to the restaurant or you go anywhere in your car, you need to have the baby be safe.
And obviously they can't fit on a normal, you know, seat.
Right.
Well, no, I don't think so.
So that's why you get them a car seat.
Okay.
A car seat is a special chair that goes on the seat of the car.
And usually it's very, very safe.
It's protecting.
It's made to protect the baby.
Right.
So if you are ever in a car accident, the car seat will help protect the small baby.
Right.
And car seats are supposed to go in the back of the car, not the front.
Yes, always.
Very good.
And now moving on to our last two words.
If you're at home, you sometimes want to have the baby play and you get him a playpen.
So basically this is a way for parents to leave the baby playing, but not look at the baby the whole time.
Right.
A playpen is like a cage for a baby, but it's soft and it's cute and it's pretty.
And so it's basically like an open area that's protected on the sides and the baby can go inside, but the baby can't leave.
Right.
So it's a cage basically and it has little toys and that's the way you just keep them in there.
Exactly.
All right.
And now when you want to put the baby to sleep, it can't obviously sleep in a big bed because it might roll over.
It might fall off.
There's a lot of things that can go wrong.
So you get them a crib.
Right.
So a crib is a bed for babies.
This is usually high off the ground and it's usually quite small and the baby can't climb out of it.
Right.
Yeah.
So it's a safe bed so the baby can't fall out, can't climb out.
Exactly.
Very good.
So very interesting, very useful things for you if you're having a baby, planning on getting these things.
So why don't we go back, listen to the dialogue again and we'll be back with Fluency Builder.
Thank you for organizing this great baby shower for me.
I've always been to baby showers, but never actually had one held for me.
Let's get started.
Okay.
Let's start opening some presents.
Oh look, what a great little bib for the baby.
This will definitely come in handy.
Oh wow, you also got me a stroller.
That's so great.
Thank you.
This next one is from Betty.
Oh hi, chair and a car seat.
Wow, Betty, thank you so much.
I really appreciate it.
One more from Carla.
A playpen and crib.
Thanks Carla.
This is just what I needed.
Okay, that's all of them.
No more gifts.
Now, who wants to guess when the baby is due?
Um, I think my water just broke.
Get me to a hospital.
Ahh!
Alright, we're back.
So now let's take a look at two key phrases.
Fluency Builder.
Okay, so at the beginning of the dialogue, the woman receives a bib for the baby and she says, oh, this will definitely come in handy.
To come in handy.
Right, so when something comes in handy, it means it will be useful.
Okay, so something that's handy is useful.
To come in handy means to be useful.
It will be useful in the future.
So for example, you should take a flashlight with you in the car just in case because it could come in handy.
That's right, or if I know that Marco is traveling to India, I can give him a map of India.
I say, Marco, this map might come in handy.
Exactly.
Very good.
So to come in handy or in something that is handy, something that's useful.
And towards the end, a very popular phrase, you probably heard it in every movie that has like maybe a pregnant woman in there.
Oh yes.
My water just broke.
My water broke.
Okay, so the woman says, ah, my water broke.
Take me to the hospital.
Right.
Okay, so this means I'm having my baby right now.
So why do they say that the water broke?
Because actually water kind of breaks, right?
I think there's a protective water cushion.
Basically there's a sack of water protecting the baby.
It's not just water.
It's all sorts of like body fluids.
And basically when that breaks, it comes out and you know that you're going to have the baby because that means the baby has to come out now because that protective fluid is gone.
Maybe the baby just kind of kicks that water out and just like, I'm ready to come out.
I have no idea how it works.
All right, so very interesting stuff.
Why don't we listen to the dialogue for the last time?
Thank you for organizing this great baby shower for me.
I've always been to baby showers, but never actually had one held for me.
Let's get started.
Okay, let's start opening some presents.
Oh look, what a great little bib for the baby.
This will definitely come in handy.
Oh wow, you also got me a stroller.
That's so great.
Thank you.
This next one is from Betty.
Oh hi, chair and a car seat.
Wow, Betty, thank you so much.
I really appreciate it.
One more from Carla.
A playpen and crib.
Thanks Carla.
This is just what I needed.
Okay, that's all of them.
No more gifts.
Now who wants to guess when the baby is due?
I think my water just broke.
Get me to a hospital.
All right, so talking about baby things and baby showers.
It's a very interesting tradition.
I understand that in other countries they don't really celebrate baby showers like this.
Really?
Yeah, or that if they do, they do it in different ways.
I know for example that sometimes in Latin American countries, they usually do it after the baby's born.
Oh, so like a congratulations shower.
Exactly, and then obviously you know if the baby was a boy or a girl, so then you get them like pink things or blue things, so it's a little bit more.
That's what's really funny about these.
People often want to have the surprise of not knowing if the baby will be a boy or a girl, so when they have the baby shower, they say, oh, I don't know what the gender is.
So you end up buying all of these yellow things because yellow is neutral.
It's good for boys and girls.
I don't know how many yellow gifts I've gotten.
I think it's a very interesting thing because for example I know that in China, I think you can't ask the doctor for the gender of the baby before it's born, right?
I think that's a way to, I'm not sure if it's a rule or not, but it sounds right.
I mean it's a way to protect female babies.
I think it would be always great to just have it be a surprise.
You never know.
Yeah, just like, oh, you know, whatever comes out.
Can you imagine not knowing and then you have twins?
That would be great for me, I think, if I had like a boy and a girl, bam, all at once.
All at once, never have to worry about it again.
Exactly, and then you have the best of both worlds, right?
You're done.
Yeah.
All right, so a very interesting topic.
Let us know if you have baby showers in your country or how do you celebrate a baby's birth or before it's born, what do you do?
Very good question.
Let us know.
Our website is EnglishPod.com.
We hope to see you there.
All right, bye.
Bye. +
