
= Wall Street (1987)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../+ 美国高中历史教材 American History ： From Pre-Columbian to the New Millennium/myAdocCss.css

'''

== Wall Street


-(man) Easy 小心；慢些；轻点! +
- (woman) Excuse me! +

Good morning. Jackson Steinem. +
- How you doing 你好吗, 你怎么样, Buddy <非正式>朋友；<美，非正式>老兄? +
- Great, Carolyn. +
Doing any better would be a sin.  //再好的话就是罪过了 +

Morning. +
Morning, Dan. What's looking good today? //今天什么股票看好？ +
If I knew, I wouldn't be in this business. //我知道的话就不会干这行了 +
Get out 离开，逃脱 while you're young. +
I came here one day 有一天我来到这, I sat down, +
and look at me now. //看看现在的我 +
Look at you now. +

Morning, Brian. +
- Chuckie! How's the woman slayer 凶手；杀人者；屠宰者? +
- *Looking for* an 18-year-old wife. //还在找18岁的老婆啊？ +
- How you doing, pal? +
- Well, if I had your looks, better. //若我有你的脸蛋就更好了 +
Takes _years of genetics_ 遗传学,   //需要多年的遗传 +
_a Yale 耶鲁大学 education_ and _the right tailor_  （尤指男装）裁缝. +
Not that you learned anything, Chunk. //这句话的意思是带有讽刺意味的，意思是“虽然你接受了教育，但你什么也没学到。”  +
Marv, I got a feeling that we are gonna *make a killing* 大赚一笔 today. +
Yeah? Where's your _machine gun_ 机关枪? +
You can't *make a buck* (一美元)赚钱 in this market. +
The country'*s going to hell* 下地狱, 彻底毁掉，彻底失败 faster /than when Roosevelt was in charge 主管；掌管；照管；职责；责任! +
Too much _cheap money_ *sloshing (v.) around* 可大量获得；大量存在 the world. +

[.my1]
.案例
====
.slosh
[ V] ( of liquid 液体 ) to move around making a lot of noise or coming out over the edge of sth 哗啦哗啦地晃荡；撒出；溅出 +
• The water was sloshing around under our feet. 水在我们脚下哗啦哗啦地流动。

*SLOSH AˈBOUT/AˈROUND*  +
( BrE informal ) ( especially of money尤指钱 ) to be available or present in large quantities 可大量获得；大量存在

====

Worst mistake 最大的错误 we ever made `系` was letting Nixon get off the gold standard. 放弃金本位制 +
Putney Drug - you boys might wanna look at it. //你们或许可以考虑普尼药厂 +
- No. They'll take five years *to come around* 恢复知觉；苏醒;再度发生；再次出现. //不，那公司要再5年才有转机 +
- But they got a good new drug. //可是他们推出的新药不错 +
*Stick to* the fundamentals. //要坚守基本面 +
That's how lBM and Hilton were built. +
Good things sometimes take time. +

(PA) Look sharp 提高警惕, especially you rookies 新手；生手(这里是复数). +

[.my1]
.案例
====
.rookie
( especially NAmE ) a person who has just started a job or an activity and has very little experience 新手；生手;（第一年参加比赛的）新队员
====

Nikkei Index *closed up* （使）靠拢，靠紧;（尤指临时）关门停业，锁上门 90 points last night. //日经指数昨晚收盘上涨90点 +
We expect _heavy Japanese buying_ on the opening. //我们预估, 今日的日本资金在一开市, 就会大举买进 +
The firm has 200,000 steel for sale. +
A million _Big Blue_ (即 IBM). 350,000 pork 猪肉 and beans 豆类.  +
*Get on the horn* (（乐器）号)打电话 with your institutions. +

[.my1]
.案例
====
“Get on the horn with your institutions” 是一种俚语表达，其中“get on the horn” 意思是“打电话”，而“your institutions” 指的是你所联系的机构或客户。因此，这句话的意思是“马上给你们的客户或机构打电话。”
====

These utilities 公用事业 are our top priority (n.)优先事项，最重要的事 today. +

[.my1]
.案例
====
"Utilities" 是指“公用事业公司”的股票或相关证券。公用事业公司通常提供电力、天然气、水等基本服务。在金融市场中，“utilities”股票通常被视为较为稳定的投资。
====

-OK. Let's go to work. +
-And they're *off and running* 开始快速行动，迅速展开! +
(bell rings) +
We cleared up to 60,000 XGC at 48 1/2. +

[.my1]
.案例
====
- “Off and running” 是一种常用的表达，意思是“已经开始并迅速进入状态”或“顺利启动”。在这个场景中，它指的是交易员们已经开始工作，并且已经迅速投入到交易和操作中，可能意味着他们的工作已经正式开始并且进展顺利。
- 这里的 "cleared up to" 表示完成了（清算或交易了）最多60,000股XGC股票，价格为48又1/2美元（即48.5美元）。这意味着他们在这个价格点卖出了或交易了最多60,000股股票。
====

Yes, that's right. Right. +
- The market just doubled. +
- Brenner! +
Research has put thrifts 节约；节俭 on the recommended. //研究部门已经把储蓄机构的股票列入推荐名单。 +
What? Dump it for chrissake （口语）基督的缘故!  //赶紧卖掉，拜托了！ +
30,000. Three-eight top.  //30,000股。最高38 +
I *go along* 继续;进展；发展 at 23. You got it. +
Now you own it! +

Conwest Air? Let me check it.  //你要康威航空？我查查看 +
*Circle* (v.) 29,000 Niagaras *for* Templeton. //替泰普顿基金, 保留2万9千股的尼加拉瓜股票 +
Mr Harrison, are you aware that we are in the biggest _bull market_ 牛市 of our generation? +
No, sir, it's not what you think. +
If you take five minutes of your time... +
Dreyfus is looking for 50,000 Conair! +
September 50s? How about Decembers? +
Mr Zaros? Bud Fox, Jackson Steinem. +
Yes, sir, I am aware of that. +
But if I could have five minutes +
to explain the opportunities emerging... +
..in the international debt market. +
No, no... +
Bud Fox, Jackson Steinem. +
Yes, I am aware of this. But if I could just +
explain the opportunities emerging... +
- ..in the international debt market... +
- (line disconnects) +
I'm sure that... +
Yesterday concerns my future. +
I need the info now, before the close. +
No, in ten minutes it's history. +
At four I'm a dinosaur! +
Howard, I thought you were a gentleman. +
Sure it's gone down. You got the tip. I didn't. +
- Why would I tell you to sell it? +
- Give it back! +
To who? I can't give it back - you own it! +
No, he's not here. +
- (whispers) That's what you told us to say. +
- Gimme that phone. +
- Hello? +
- Hello. +
- Who am I talking to? +
- The sales manager. What's the problem? +
What? Will you gimme a break? How was +
I supposed to know you were in surgery? +
What am I - Marvin the Mindreader?! +
Uh, no, sir. l'll discuss that with the +
account executive, and l'll get back to you. +
No, no, sir. You're welcome. +
I'm closing the account. +
If he doesn't pay tomorrow, you pay. +
Mr Lynch, I swear to you, he's lying. +
We give you a rich man's account,... +
..and you tell me he's gonna DK you +
for a lousy quarter point? +
You're being unfair, sir. +
You know he's got a history for bullshit. +
Somebody's got to pay. +
Ain't gonna be me. +
Buddy, Buddy. +
A little trouble, huh, today, Buddy? +
Howard the jerk reneged on me. I gotta +
cover his losses to the tune of seven grand. +
Yeah! I'm holding! +
I'm tapped out. American Express +
got a hit man looking for me. +
lt coulda been worse, right? +
Coulda been my money. +
Here, here, rookie, let me help you out. +
I got... a C-note. +
- Thanks, Marv. l'll make it up to you. +
- Yes, I am still here! +
You know what my dream is? +
To one day be on the other end of that phone. +
Oh, you got it, baby. +
Where the real cheesecake is. +
Hey, Bud, you forgetting something? +
The Gekko phone call? +
When are you gonna realise it's the big game +
hunters who bag elephants, not guys like us. +
- Gordon Gekko, please. +
- Gekko's beautiful. +
30 seconds after the Challenger blew up, +
he's selling NASA stock short. +
Yeah, but... 47 million he made +
on the Melcore deal. +
23 on the lmperial deal before he was 40. +
The guy makes 20 times what Dave Winfield +
makes in a year, and he talks to everybody. +
And he had an ethical bypass at birth. +
- Hello, Natalie. Guess who? +
- Mr Fox. +
Right. Every day I say to myseIf that today +
could be the day. So will you marry me? +
- l'll think about it. +
- Then can you get me through to Mr Gekko? +
- He's very busy. +
- Of course he is. Five minutes is all I ask. +
Mr Fox, I'm sure you're a good broker, +
but our traders deal with the brokers. +
Mr Gekko deals with investment bankers. +
- Tell him I called. There are big changes... +
- Yes, l'll give him your message. +
Leo, I understand, but you have to realise +
there'll be major subordinated debt involved. +
- Buddy, how ya doing? +
- Great, Charlie. Any better would be a sin. +
Jesus Christ! Listen, I hear all you guys +
on Wall Street are millionaires. +
- When you gonna make us all rich? +
- You need an account to win the lottery. +
- Give me 50 grand. l'll get you a condo. +
- Sure! We'll own the airline by then! +
Why don't he make himseIf rich, +
so he can pay off his school loans? +
Nice to see you're in such a good mood, Dad. +
Did Mom give you fish for dinner? +
You smoke too much. How often you +
gotta go to the hospital to realise? +
Leave me alone. lt's the only thing that +
makes me feel good. There, Frank. All set. +
Spaghetti! +
Your mother still makes lousy spaghetti. +
- lt's pasta now. Spaghetti's out of date. +
- So am l. You want a beer? +
Billie! Bring a Molson Lite for the kid! +
- Looking good, huh? +
- He looks terrific. +
Carl, we'll be at the bar. +
- l'll catch up with you. +
- All right, Charlie. +
So... +
You look like you've grown another inch, +
but you don't look so hot, Buddy. +
- You're gonna get bags under your eyes. +
- Yeah, I had a tough day. +
- Some jerk DK'd me. I gotta cover his loss. +
- Speak English. +
DK: Didn't Know who I was +
when the options he bought took a bath. +
- Bastard reneged on me! +
- I told you not to get into that racket. +
You coulda been a doctor or a lawyer. +
If you'd stayed at Bluestar, you coulda been a +
supervisor now, instead of being a salesman. +
Dad, how many times I gotta tell you I am not +
a salesman? I'm an account executive. +
Soon I'm moving into investment banking. +
You ask strangers for money - +
you're a salesman. +
Dad, it takes time. +
You gotta build a client list. +
I can make more money in one year +
as a broker than in five at this airline. +
Thank you, Billie. +
I don't get it, kid. You borrow money to go +
to NYU. First year out, you make 35 grand. +
You made 50 grand last year, and can't +
pay off your loans. Where does it go?! +
Dad, 50K does not get you +
to first base in the Big Apple. +
I got 40% in taxes, 15 grand for rent. +
I got school loans, car loans, food - +
that's three bills a month. I need suits... +
Come back home and live rent-free +
instead of that roach-infected place. +
$50,000! Jesus Christ! +
The whole world's off its rocker! +
I made $47,000 last year. That's before taxes. +
That's Queens, Dad! A 5% mortgage +
and you rent the top room. +
I gotta live in Manhattan to be a player. +
There is no nobility in poverty any more, Dad. +
One day you'll be proud of me. You'll see. +
lt's yourseIf you gotta +
be proud of, Huckleberry. +
How much you need? +
Can you spare 300? +
l'll pay you back next month, I promise. +
- I don't know if I got that much on me. +
- Not in here. Please. +
lt adds up. 300 here, 200 there. +
Your brother... +
I always say money's something you need +
in case you don't die tomorrow. Right, Carl? +
How you doing? +
- How's work treating you? +
- Damn mandatory drug test. +
They're driving us crazy. I got flagged for my +
blood pressure pills. Can you believe that? +
The good news is we had a meeting with +
the controller about some union business. +
Remember the accident last year +
and the investigation? +
The FAA is gonna rule it was a manufacturing +
error in the door-latch mechanism. I knew it. +
I kept telling 'em it wasn't maintenance. +
lt's the greedy manufacturers in Cincinnati. +
- That's great. +
- This gets us out from under suspension. +
We can go for those new routes to Pittsburgh +
and Boston. We'll compete with the big guys. +
To Bluestar. As your broker, all I can +
advise is you hold on to that stock. +
What stock? Are you kiddin'? +
- Are you sure about this thing? +
- What? +
- The FAA announcement. +
- Sure I'm sure. +
Look at me. You got that +
mischievous look in your eye, Buddy. +
You used to smile like that +
when you were a kid sleeping. +
lt's true. Just like that. +
( computer plays "Happy Birthday") +
Morning, Gordon. +
Delivery for Mr Gekko. lt's a personal item. +
He needs you to sign for it. +
Send him in. +
Hello, Natalie. Recognise the voice? Here's +
a hint - you're thinking about marrying me. +
- Why are you here? +
- You're lovelier than I pictured. +
- Got a birthday present for Mr Gekko. +
- You can't come barging in here. +
- What makes you think it's his birthday? +
- Well, it's in the bible, see? +
You better go buy him a gift. +
Please, Natalie, let me give this to him. +
Cuban cigars. His favourite and tough to get. +
Please, Natalie? +
Stay here. l'll see what I can do. +
Wait outside. +
Yeah, l'll see you shortly, I hope. +
Five minutes. +
Well, life all comes down to a few moments. +
This is one of 'em. +
What the hell's going on? +
I'm looking at 200,000 shares move, pal. +
I wanna know if we're part of it. +
We'd better be, or I'm gonna come +
and eat your lunch for you. Back in two. +
Sorry, Jeff. Look, I loved it at 40. +
lt's an insult at 50. +
Their analysts don't know +
preferred stock from livestock. +
Wait till it heads south, then we raise the +
sperm count on the deal. Get back at ya. +
This is the kid. Calls me 59 days in a row. +
Wants to be a player. +
Oughta be in the dictionary +
under "persistence". +
Listen, Jerry, I'm looking for negative control. +
No more than 30, 35%. +
Just enough to block anybody else's merger +
plans, and find out if the books are cooked. +
If it looks as good as on paper, +
we're in the kill zone, pal. +
Lunch? You kiddin'? Lunch is for wimps. +
OK, Billy. l'll talk at ya. +
How do you do, Mr Gekko? I'm Bud Fox. +
So you say. Nice to meet you. +
Hope you're intelligent. +
- Where'd you get these? +
- I got a connection at the airport. +
So what's on your mind, kemo sabe? +
Why am I listening to you? +
I gotta monitor my blood pressure, +
so don't upset me. +
No. No, sir. +
ln 45 seconds, the microprocessor computes +
your systolic and diastolic pressure. +
Got an LCD read-out, cost-effective... +
Less than one visit to a doctor. +
I just wanna let you know l've read all about +
you at NYU Business. I think you're a genius. +
l've always dreamed of one thing and +
that's to do business with a man like you. +
- What firm you with? +
- Jackson Steinem. +
They're going places. +
Good junk-bond department. +
You the financing on +
that Jansen investment? +
Yeah. I'm working on +
some other interesting stuff. +
Cosmetic company, by any chance? +
Are you tweIfth man on the deal team? +
Last to know? +
- I can't tell you that, Mr Gekko. +
- So what you got for me, sport? +
Chart breakout on +
Whitewood-Young lndustries. +
Explosive earnings. A 30% discount from +
book. Great cash flow. Couple of 5% holders. +
- lt's a dog. +
- Strong management. +
lt's a dog, pal. What else you got +
besides connections at the airport? +
(secretary) Mr Stevenson in San Francisco. +
- He respond? +
- Lecturing on economics. +
- What?! +
- No, he's in Chicago. +
Why the hell is Cromwell giving a lecture +
tour when he's losing 60 million a quarter?! +
Guess he's giving lectures +
in how to lose money. +
If this guy owned a funeral parlour, +
no one would die! This turkey is braindead! +
OK. All right, Christmas is over, +
and business is business. +
You keep on buying. Dilute the son of a bitch! +
Ollie, I want every orifice +
in his fuckin' body flowin' red! +
He's flowin', Gordo. Piece of cake. +
This guy's the best trader on the street. +
Susan, get me the LBO analysis +
on Teldar Paper. Bring it in here, please. +
- (intercom) Mr Gekko, your wife. +
- What else you got? +
Terafly. Analysts don't like it. I do. +
The break-up value is twice the market price. +
This deal finances itseIf. +
You sell off two divisions... +
Not bad for a quant, +
but that's a dog with different fleas. +
Come on, pal. +
Tell me something I don't know. +
lt's my birthday. +
Surprise me. +
- Bluestar. +
- What? +
- Bluestar Airlines. +
- Rings a bell somewhere. So what? +
lt's a comer. 80 medium-body jets. 300 pilots. +
Flies to Florida, Canada, +
uh, Northeast, the Caribbean. +
- Great slots in major cities. +
- I don't like airlines. Lousy unions. +
Well, there was a crash last year. +
They just got a favourable +
ruling on a lawsuit. +
Even the plaintiffs don't know about it. +
Well, how do you know about it? +
I just know. +
The decision should clear the way +
for new planes and routes. +
There's only a small float. You should grab it. +
Good for a five-point pop. +
250,000 shares at 18 1/4 from Jansen. +
I can pull twice that at 18 1/2 +
from the California pensions. +
We got close to haIf a million +
shares in the bag. +
The Terminator! +
Blow 'em away, Ollie! +
We got the Beezer Brothers. +
I'm working on the Silverberg boys. +
Rip their fuckin' throats out! +
Stuff 'em in your garbage compactor! +
lnteresting. Got a card? +
Home number's on the back. +
Bud Fox, I look at a hundred +
deals a day. I choose one. +
- I hope to hear from you, sir. +
- Thanks for the cigars. +
Let's go, guys. Looks like +
we're going over 5% in Teldar. +
Start the lawyers on a tender offer and 13D. +
We buy everything in sight, +
but we don't pay over 22. +
They'll fight. They got Myers +
and Thromberg doing their legal. +
- Thanks, Natalie. +
- Have a nice day, Mr Fox. +
Mr Gekko, your conference call is ready. Mr +
Sugarman in Delaware, Mr Bernard in LA,... +
..Mr Jackson and Ms Rosco +
in London. They're all on. +
Please, I'm begging you. +
I'm in a bind down here. +
We got all these damn new computers and +
young men that are edging me out here. +
Hey, Bud! Did he see you? +
Yeah, he saw right through me. +
Cheer up. You shook Gekko's hand +
and you still got all your fingers. +
Besides, he's not the only +
elephant in the jungle. +
Holy cow! Did you get something +
from him? Teldar Paper, huh? +
Nah. lt's a dog with fleas. +
Fox, where have you been +
for the last three hours, hm? +
If I were you, and I thank +
my personal God I am not,... +
..l wouldn't be sitting around chinwagging. +
Plenty of six-figure names +
in that zip-code pile to cold-call. +
Buddy, I got tickets for the Knick game +
tonight. Cruise some chicks afterwards. +
Whaddaya say? +
- No, I gotta read my charts. +
- Forget charts, will ya? +
We're not fund managers. +
Churn 'em and burn 'em! +
I am offering you the Knicks and chicks. +
God help you before you turn +
into poor Steeples over there. +
Preferably Lou Mannheim. +
Yeah, nice guy, but he's a loser. He lost all +
his equity when the firm went belly-up in '71. +
You wanna be in your sixties still pitching? +
Hey, Buddy, whatever happened to +
that cute analyst at Thudder and Wicks? +
Cindy. Having sex with her +
was like reading the Wall Street Journal. +
- She had a heartbeat. +
- You wanna bet? +
I gotta get to work. Zs today. +
Call for you, Buddy! Pick up two! +
- Bud Fox. +
- All right, Bud Fox. +
I want you to buy 20,000 shares of Bluestar... +
..at fifteen and an eighth, +
three-eighths tops. +
And don't screw it up, sport. +
- Think you can handle that? +
- Yes, sir! Thank you. You won't regret this. +
Whoo! Marv, I just bagged the elephant! +
Gekko? +
- Hiya, sport. +
- Nice to see you again, Mr Gekko. +
Try the steak tartare. lt's off the menu. +
Louis'll make it for you. +
- (Louis) Of course, sir. Anything to drink? +
- Just an Evian, please. +
Hey, see this? Can you believe it? +
lt's got a two-inch screen. +
I can hardly see it. +
lt's for my kid - Rudy. +
Three years old, he's an electronics freak. +
We're going into a new age, pal. +
So how's business today? +
Great. Bluestar was at 17 1/4 +
when I left the office. Up from 15. +
Might spin up to 18 by the bell. +
Teldar's shooting up. +
Did you buy any for yourseIf? +
I bet you were on the phone +
two minutes after you got out of my office. +
No, sir, that wouldn't have been legal. +
Sure. Relax, pal. +
No one's gonna blow the whistle on you. +
ls that legal? Why don't you +
put that in my account? +
- Hey, Gordon! +
- Georgie! The cellular king! How you been? +
- Monique, nice to see you, my dear. +
- Hello, Gordon. +
- You look wonderful. +
- You're looking very well yourseIf. +
And Mr Davis... +
Can I get the check here, please? +
For chrissakes! +
Cover that Bluestar buy. Put 200 thou on one +
of those bow-wow stocks you mentioned. +
Pick the dog with the least fleas. +
Use a stop-loss, so your downside's 100 thou. +
And buy a decent suit. +
You can't come in here looking like this. +
Go to Morty Sills. Tell him I sent you. +
Yes, sir. Thank you, Mr Gekko. Thank you +
for the chance. You will not regret this. +
You're with a winner. +
Right... right... +
Put the rest of the money in a tax-free fund. +
I wanna see how you do before I invest it. +
And save the cheap salesman talk. +
lt's obvious. +
- Excuse me, sir? +
- You heard me. +
I don't like losses, sport. +
Nothing ruins my day more than losses. +
Now you do good... you get perks. +
Lots and lots of perks. +
- Louis, take care of my friend. +
- Thank you, sir. +
Have a good lunch, Buddy. +
Hi, Richard. +
(knock on door) +
Hi, Bud. +
Hi. +
I'm Lisa. A friend of Gordon's. +
Lisa? Gordon? Oh, oh, Mr Gekko. Sure. +
Uh, would you like to come in? +
Didn't he tell you? +
Oh, that's so like Gordon. +
Why don't you get dressed? We're going out. +
We are? +
So... where are we going? +
Wherever you like. +
Lutéce. 21. The River Café. +
Or maybe we could just... +
..drive around for a while. +
Work up an appetite. +
Want some? +
Gordon tells me that +
you're a very talented broker. +
What do you like? +
Like? (clears throat) Well... +
l've got this guy who tells me +
to buy Hewlett-Packard,... +
..but l've been burned on tips. +
Uh... Hewlett. +
Now, let's see. lt closed at 41 1/4. +
Up an eighth. Very attractive. +
About, uh... average yield. +
- Very attractive. +
- Mmm... +
- Rising profits. +
- Ooh! +
Strong balance sheet. +
You're hot on this stock. +
Uh... lt's ready to take off. +
l'd jump all over it if I were you. +
- Good morning, Carolyn. +
- Morning. You look happy. +
- Any better and l'd be guilty. +
- You were never innocent, sugar pie. +
How do you know? You wish! +
Goddamn! We sure went down +
the toilet on that ugly bitch! +
Oh, Buddy! Mr Gekko's office is looking +
for you. Be at the Wyatt Club courts at six. +
Come on, sport. You gotta try harder. +
I need some exercise, for chrissakes. +
- I don't think I can go on, Mr Gekko. +
- Push yourseIf. Finish out the game. +
lt's a very nice club, Mr Gekko. +
Yeah. +
Not bad for a City College boy. +
Bought my way in. Now all these lvy League +
schmucks are sucking my kneecaps. +
I just got on the board of the Bronx Zoo. +
lt cost me a mil. +
That's the thing you gotta +
remember about WASPs. +
They love animals, +
but they can't stand people. +
Uh, Mr Gekko,... +
..we took a little loss today. +
We got stopped out on Terafly. +
About a hundred grand. +
Well, I guess your dad's not a union +
representative of that company, huh? +
How do you know about my father? +
The most valuable commodity +
I know of is information. +
Wouldn't you agree? +
Yeah. +
The public's out there +
throwing darts at a board, sport. +
I don't throw darts at a board. +
I bet on sure things. +
Read Sun Tzu, The Art of War. +
"Every battle is won before it's ever fought." +
Think about it. +
You're not as smart as I thought you were. +
You ever wonder why fund managers +
can't beat the S&P 500? +
Cos they're sheep. +
And sheep get slaughtered. +
l've been in this business since '69. +
Most of these Harvard MBA types +
don't add up to dogshit. +
You need guys that are poor, +
smart and hungry. And no feelings. +
You win a few, you lose a few, +
but you keep on fighting. +
And if you need a friend, get a dog. +
lt's trench warfare out there, pal. +
- Hey, Georgie. +
- Hey, Gordon. +
- How's Larchmont treating you? +
- Fine. How's the Praxar deal going? +
- You should know, pal. +
- Asshole! +
And inside here, too. +
I got 20 other brokers analysing charts, pal. +
I don't need another one. +
See you around, Buddy. +
I am notjust another broker, Mr Gekko. +
If you give me another chance, l'll prove it. +
l'll go the extra yard for you. +
Just one more chance, Mr Gekko. Please! +
Want another chance? Then stop sending me +
information, and start getting me some. +
Get dressed. l'll show you my charts. +
- You know the name? +
- Larry Wildman, one of the first raiders. +
Sir Larry Wildman. Like all Brits, thinks +
he was born with a better pot to piss in. +
Bribed an old secretary of mine +
to open her mouth. +
Stole RDL Pharmaceuticals +
right from under me. +
Wildman, the "White Knight". +
I remember that deal. +
You were involved, Mr Gekko? +
Payback time, sport. +
See that building? I bought that building +
ten years ago. My first real-estate deal. +
Sold it two years later. +
Made an $800,000 profit. +
lt was better than sex. +
At the time I thought that was all the money +
in the world. Now it's a day's pay. +
Anyway, I had a mole in Wildman's operation. +
- He gave me haIf the picture, then got fired. +
- I don't think I follow you. +
Wildman's in town. +
He just became an American citizen. +
Something big is going down, OK? +
I wanna know where he goes, what he sees. +
I want you, pal, to fill out the missing picture. +
Mr Gekko, it's not exactly what I do. +
I could lose my licence. +
If the SEC found out, I could go to jail. +
That's inside information, isn't it? +
Like when a father tells his son +
about a court ruling on an airline? +
Or someone overhears I'm buying Teldar, +
and decides he's gonna buy some? +
Or the chairman of the board of XYZ +
decides it's time to blow out XYZ? +
ls that what you mean? +
Unless your father's on the board +
of directors of another company,... +
..you and I are gonna have a very +
tough time doing business together. +
- What about hard work? +
- What about it? You work hard? +
Bet you stayed up analysing that stock +
you gave me. Where'd it get you? +
My father worked like an elephant till +
he dropped dead at 49 with a heart attack. +
Wake up, will ya, pal? +
If you're not inside, you are outside, OK? +
I'm not talking about some +
$400,000-a-year Wall Street stiff,... +
..flying first class and being comfortable. +
I'm talking about liquid. +
Rich enough to have your own jet. +
Rich enough not to waste time. +
Fifty, a hundred million dollars, Buddy. +
A player,... +
..or nothing. +
Now you had what it took +
to get into my office. +
The real question is whether +
you got what it takes to stay. +
Look at that. +
You're gonna tell me the difference +
between this guy and that guy is luck? +
Mohammed, pull over. +
If you don't mind, I'm gonna +
drop you off here. I'm late. +
Buddy, it's been nice meeting you, OK? +
(Buddy taps on window) +
All right, Mr Gekko. +
You got me. +
Excuse me, please. +
Excuse me. +
I'm sorry, sir. Do you have a reservation? +
- Uh, table for one. +
- Reservations only. We're booked for a week. +
All right. Don't touch. +
Everything ready, sir. +
Excuse me! ls Mr Wildman +
on board that plane? +
Shit! My boss is gonna kill me! +
I'm supposed to give him this. +
- You know where that plane is going? +
- Erie, Pennsylvania. +
Thank you. +
After spending the morning at Kahn +
Seidelman in the junk-bond department,... +
..he had lunch at that restaurant, Le Circus, +
with some well-dressed bean counters. +
He later stopped off at Morgan. l'd say +
from all the smiling and palm-pressing... +
..Larry got himseIf some +
nice fat financing, GG. +
Bright, but not bright enough, Sherlock. +
Roll the dice and play Monopoly. +
What box is Sir Larry gonna +
land on in Erie, Pennsylvania? +
Jesus Christ! He's buying Anacott Steel. +
OK. When the market opens tomorrow, +
I want you to buy 1500 July 50 calls. +
- You hear me? +
- Yes, sir. +
And start buying 1,000-share blocks +
and take it up to $50. +
When it reaches 50, +
give out a little taste to your friends. +
Then I want you to call +
the Wall Street Chronicle, extension 1605. +
You tell the man +
"Blue Horseshoe loves Anacott Steel". +
- You got that? +
- The Wall Street Chronicle. +
Congratulations, Buddy. +
You scored. l'll talk at ya. +
Start buying Anacott Steel across the board. +
Use the offshore accounts. +
And keep it quiet. +
Frank, 10,000 ANC at 46. Let me know +
how the options are opening, OK? +
Thank you. +
Jackson Steinem! +
- How is Anacott Steel? +
- 5 3/4, 6. 2,000 up. +
- Six at 10,000. +
- l'll sell you 2,000. +
That's not what I said. I said 20,000 shares. +
(trader) Anacott trades at six. +
- 8,000 at a quarter? +
- l'll take 8,000. +
Make it six to a haIf, 2,000 up. +
(Marvin) I know what time it is, +
and this is what I'm saying. +
We have important financial news, Mr Erlich, +
that just happens to concern your future. +
- You could benefit... What's going on? +
- Anacott Steel. Put your best customers in it. +
Lou, I got a sure thing. +
Anacott Steel. +
No such thing, except death and taxes. Not +
a good company any more. No fundamentals. +
What's goin' on, Bud? +
You know something? +
Remember, there are no short cuts, son. +
Quick-buck artists come and go +
with every bull market. +
The steady players make it +
through the bear markets. +
You're a part of something here, Bud. +
The money you make for people creates +
science and research jobs. Don't sell that out. +
You're right, but you gotta get to the +
big time first, then you can do good things. +
- You can't get a little bit pregnant, son. +
- Lou, trust me. lt's a winner. Buy it. +
We'll kamikaze over to Nell's, +
chase some cotton underwear. +
I know this 18-year-old bimbette +
that's gorgeous. Hold on. +
- Play tennis Saturday? +
- Can't. Fly-fishing in Canada. Real big client. +
- Take Anacott? +
- Light snack, but good. Thanks, pal. +
You're sharking your way up. +
No, no, my dear, you've got to diversify. +
I got a sure thing. Anacott Steel. +
l've just heard the most lovely two words. +
Blue Horseshoe loves Anacott Steel. +
Anacott Steel. +
Looks like Anacott Steel's in play. +
Check the ARBs. +
Looks like it's being accumulated. +
Lou? Anacott. I buy. Yeah. +
Take it and bid it. +
Quarters won't matter. +
Keep taking Anacott. +
This is special. Anacott. Paint the tape. +
- Bet the ranch. +
- Buy 100,000 shares. +
- Wildman is sniffing around. +
- lt's on automatic pilot to the moon. +
- If it hits 75, we'll clean 24 mil. +
- (Gekko) Relax, pal. +
Don't get emotional about stock. +
lt clouds the judgment. +
Which closed at 5 1/8, up 5 1/8 from +
yesterday's close on heavy trading. +
Can I help you? +
Yes, I'm Bud Fox. I have some +
papers for Mr Gekko to sign. +
- Come in. +
- Thank you. +
- I'm sorry about this, Mr Gekko. +
- lt's all right. lt's OK. +
You wanna wait here? +
Problems? +
No problem. +
This is Bud Fox. My wife, Kate. +
- Hello. You came out from the city? +
- Yes, ma'am. +
Ah, long drive. You want a drink? +
Yeah, you want a drink? Um... sure. +
- If you'd rather not. +
- No, come on. Have a drink. +
Get to meet all the people. +
lt's a good idea. +
We got Sam Ruspoli, Carmen Winters, +
Stone Livingston. This is Bud Fox. +
His illustrious wife, Muffie. +
Candice Rogers, Dick Brady. +
Darien Taylor. All old friends. +
Hi. +
Great idea, Gordon. I know good help is hard +
to find, but can it create a dry vodka martini? +
lt doesn't talk back or steal the silverware. +
And Dick here is gonna get me +
an exemption, aren't you? +
I'm in St Kitts with this new +
Kamali leopard-skin V-cut bikini,... +
..which is gonna turn back the clock on my +
marriage five years. Know what I mean? +
Call for you, sir. Sir Lawrence Wildman. +
He says it's important. +
Thank you, Nyung. +
Would you fix Mr Livingston another +
martini? Stick around. This could be fun. +
lt's all because this Ukrainian bitch +
botched the job on my wax on my bikini line. +
How ghastly! Sue her. +
- Larry, what a surprise! +
- I want to see you, Gordon. +
Can it wait till tomorrow? I got people here. +
- No, this can't wait. lt's important. +
- OK. If you feel that way, come on over. +
Ah! There you are! +
Can I steal him for a minute? +
- Of course. +
- I want your opinion. +
So what do you see in this? +
Purity. lnnocence. +
A few thousand dollars +
down the tubes, if you ask me. +
Really? +
You can kiss your career +
as an art appraiser goodbye. +
We paid over 400,000 for it at the +
contemporary picture sale last June. +
Jesus, you could've had +
a whole beach house for that! +
Sure you could. ln Wildwood, New Jersey. +
If you sold this one, you could +
have a nice penthouse on Fifth. +
You wouldn't have much +
left over for decoration. +
lt's nice, if you're on mushrooms. +
I thought Gordon was a tough businessman. +
He sure has taken a bath on that. +
A bath? l'd say Gordon is one of +
the most astute collectors around. +
He has a great eye, and he only buys the best. +
Like this rug, for instance. +
A Bokhara. lt's the finest of its kind. +
After he bought it, a dealer +
representing the Saudi royal family... +
..offered him twice what he paid. +
lt absolutely makes the room. +
See how this bit of celadon in the border +
is picked up by these cushions? +
Although it's a sacrilege +
having that Etruscan vase on the table. +
Some dope might use it as an ashtray. +
- I guess you're a decorator? +
- You got it. +
A great spender of other people's money. +
If you're that good, I'm sure you +
can do wonders with my place. +
- Where would that be? +
- Upper West Side. +
Really? Home of the exposed +
brick wall and the houseplant? +
lt's just a rental. l'll be moving to the East +
Side soon. Some deals brewing with Gordon. +
But that's just conversation. +
What about real things? +
Like dinner? The two of us... next Friday? +
Café Santo Domingo. +
What if I have a previous engagement? +
You break it. +
There you go again, Darien. +
Talking with strange men. +
Hello. Sam, do you know Bud Fox? +
Sam is in banking. +
- Works for Gordon. +
- Nice meeting you. +
- Are you staying for dinner? +
- No, I have work to do. +
- (doorbell) +
- Ah. The bell. +
Excuse me. +
Call me next week. l'll give you an estimate. +
- Larry, how have you been? +
- Fine. Travelling, actually. +
- Can I get you a drink? +
- No, thank you. +
Larry! Excuse me. Sir Larry. +
How are ya? Goddamn, you look great! +
- Gordon. +
- So you wanna talk. +
- l'll be heading back now, Mr Gekko. +
- Stick around. +
This is one of my gang. Bud Fox. +
Shall we go upstairs? +
Yeah. +
The rarest pistol in the world, Larry. +
A .45 Luger. +
Only six of 'em were ever manufactured. +
Congratulations. +
Rarer still is your interest in Anacott Steel. +
My interest is the same as yours. Money. +
Thought it'd be a good investment for my kid. +
No, this time I'm in for the long term. lt's +
not a liquidation. I'm gonna turn it around. +
You're getting a free ride on my tail, mate. +
With the dollars you're costing me to +
buy back stock, I could modernise the plant. +
I'm not the only one who pays here, Gordon. +
We're talking about lives and jobs. +
Four generations of steelworkers... +
Correct me if I'm wrong, but when you got +
CNX Electronics, you laid off 6,000 workers. +
Jemson Fruit, 4,000. +
That airline you bought, um... +
I could break you, mate. +
ln two pieces over my knees. +
You know it. I know it. +
I could buy you six times over. +
I could dump the stockjust to burn your arse! +
But I happen to want the company, +
and I want your block of shares. +
I'm announcing +
a tender offer at 65 tomorrow. +
I'm expecting your commitment. +
Showdowns bore me, Larry. Nobody wins. +
You can have the company. +
ln fact, it'll be fun watching you and your +
giant ego trying to make a horse race of it. +
Buddy, what's a fair price for that stock? +
The break-up value is higher. lt's worth 80. +
Well, we don't want to be greedy. +
So what do you say to 72? +
You're a two-bit pirate and greenmailer. +
Nothing more,... +
..Gekko. +
Not only would you sell your mother +
to make a deal, you'd send her COD. +
My mail is the same colour as yours is, pal. +
Or at least it was until the Queen +
started calling you "Sir". +
Excuse me before I lose my temper. +
71? +
Considering you brought my mother into it,... +
..71.50. +
Done. +
You'll hear from my lawyers +
tomorrow, 8am. Good night. +
He's right, I had to sell. +
The key to the game is capital reserves. +
If you don't have enough, you can't piss +
in the tall weeds with the big dogs. +
"All warfare is based on deception." Sun Tzu. +
"If your enemy is superior, evade him." +
"If angry, irritate him." +
"If equally matched, fight. +
And if not, split. Re-evaluate." +
He's learning, huh? Buddy's learning! +
(phone ringing) +
- Yeah? +
- (Gekko) Money never sleeps, pal. +
Just made 800,000 in Hong Kong gold. +
lt's been wired to you. +
Play with it. You done good, +
but you gotta keep doing good. +
I showed you how the game works. +
Now school's out. +
Mr Gekko, I'm there for you 110%. +
No, no, no, no. You don't understand. +
I wanna be surprised. +
Astonish me, pal. New info. +
I don't care where or how you get it. +
Just get it. +
My wife tells me you made a move on Darien. +
Here's some inside info for you. +
That GQ type she's going out with +
got big bucks,... +
..but he's putting her feet to sleep. +
Exit visas are imminent. +
I don't want you losing your place in line. +
Ah, Jesus! +
I wish you could see this. +
The light's coming up. +
l've never seen a painting that +
captures the beauty of the ocean... +
..at a moment like this. +
I'm gonna make you rich, Bud Fox. +
Yeah. Rich enough +
that you can afford a girl like Darien. +
This is your wake-up call, pal. +
Go to work. +
- Fox! +
- Mr Barnes. +
Buddy D, is this déjâ vu +
|What's it been? A year, year and a haIf? +
So, I hear you're moving up in the world. +
A senior associate. Not bad. Not bad. +
How's Margie? +
I can't complain. +
I got a house in Oyster Bay, you know. +
Market treating you good? +
- Still seeing that sexy French chick? +
- No. No. She asked the wrong question. +
- What was that? +
- "What are you thinking?" +
The hours are hell, but the cash +
is starting to tumble in. +
I know this guy who has an ironclad way +
of making money. I can't lose or get hurt. +
Can't get hurt. So does this guy +
have a tip for an honest lawyer? +
Maybe. Check out Teldar Paper,... +
..but don't quote me. +
And you? I hear you're handling the Fairchild +
Foods merger, and it may not go through. +
Any surprises I haven't read about +
in the Wall Street Journal? +
Come on, that's illegal. +
You wouldn't wanna get me disbarred. +
Who's listening? +
Just one college buddy talking to another. +
- Yeah, right. +
- Oh, relax, Roger. +
Everybody's doing it now. +
But, if you don't know, +
then... you don't know. +
And if I did... +
..what's in it for moi? +
More money than you ever dreamed of. +
Nobody gets hurt. +
You think about it. +
- Let's grab a beer. What do you say? +
- Uh... too much to do. But l'll walk you out. +
The file's on the desk, Marie. +
Get inside my uncle's door +
and the secrets of the world are yours. +
Lifeblood of companies... +
Of course, you gotta go +
to law school first, but... +
Mr Panos, l've been charting +
the growth of office space. +
You're in the right business +
at the right time. +
Thank you for tell me what I already know. +
Look, I'm very impressed with your work, +
and I could use a tax break. +
Let me ask, what would you say to +
some working capital and a partner? +
Why do I need a partner? +
Look, you need more vans. 42 employees +
can't cover the buildings you got,... +
..not to mention the clients +
we'd have together. +
I am an expert at identifying undervalued +
assets such as this business. +
The good news, Gordon, +
is Rorker Electronics. +
That's right. I see it happening +
in the next two months. +
Come on, their quarterlies are for shit. +
I got a little gift for you. +
Gordon will be very pleased. +
What else have you got? +
You know Marty Weidman? +
He netted 650G off of that merger. +
26 years old, the guy's Rambo. +
- He's an asshole! +
- He is Rambo! +
He's got a Porsche Turbo +
Cabriolet, about 75 thou. +
I think if I can make a bundle of cash +
before I'm 30 and get out of this racket,... +
..l'll be able to ride +
my motorcycle across China. +
l'd like to do for furniture what +
Laura Ashley did for interior fabrics. +
Produce a line of high-quality +
antiques at a low price. +
Sounds great. l'll take you public. +
You will? +
Can I help you? +
Oh. Excuse me. ls this Bill Bates' office? +
No. +
I'm sorry. +
Hiya, Dad. +
- What brings you out here? +
- Client's got a private jet at Butler. +
- Hey, Buddy. How ya doing? +
- Mr Wall Street! +
The bozos that keep us in the air! +
- Give us a hand. +
- Do an honest day's work. +
All right. Change the oil, +
fill the tyres and park it out back. +
This kid wanna buy the plane? +
- You always light up when you see me. +
- Don't start, all right? +
All right. +
So who peed in your Cheerios? +
Goddamn fare wars are killing us! +
Management's gonna lay off +
five of my men this week. +
I'm sorry about that. +
- So how much you need? +
- I don't need anything. I'm doing great. +
New client, new ball game. +
Things are starting to happen. +
Sure. Lots of guys at the track talk like that. +
How do you know you'll have any dough +
next month? Jesus Christ, what is this? +
lt's a dividend. +
l've borrowed at least five grand +
over the years. +
Oh, stop it. +
Put this towards your school loan. +
Forget the loans. Look, Dad, things +
are good and it's gonna stay that way. +
- Buy yourseIf a new suit. +
- What do I need a suit for? +
I don't hobnob with the jet set. +
I just fix their planes. +
Then get a decent bowling jacket, so you +
don't look like the Roto-Rooter man. +
Come on, what's money for? Enjoy yourseIf. +
Money is a pain in the ass, +
if you ask me. But thanks, kid. +
- How about dinner? +
- Sure. Any night this week. +
OK. No, I'm sorry. This week's booked. +
- l'll check with my girl. l'll get back to you. +
- You do that, Huckleberry. +
I gotta run. You stop smoking, you hear? +
l'll talk at ya. +
Whoo! Oh! +
(Darien shrieks) +
(man) lt's in both our interests to put +
a safe distance between you and us. +
- You understand that, Mr Fox? +
- Sure. +
This gives you limited power of attorney +
for Mr Gekko's account. +
Every ticket you buy must be +
marked "power of attorney". +
That means that you call the shots. +
Mr Gekko has no official knowledge +
of what stocks you're buying. All right? +
Just sign it at the end, twice. +
I never knew how poor I was +
until I started making money. +
Your transactions will be +
monitored by StockWatch. +
If any trouble does arise, +
you are on your own out there. +
The trail stops with you, understand? +
Spread the buy orders over +
different accounts, you won't get burnt. +
I have friends that won't +
mind making easy money. +
- (child shrieks) +
- Rudy Gazoodi! How's my cutie?! Viens ici! +
(man) We need more votes for the +
showdown, but don't wanna go public... +
- Bonjour, Monsieur Buddy. +
- Bonjour, Monsieur Buddy. +
Oh! He speaks French already. +
Kid had the highest score in his lQ test. +
lt is so difficult to get into +
a good nursery school now. +
They even go to your home +
to make sure you're acceptable. +
That's it for you with the grown-ups. +
- Nicole, would you take him for a nap now? +
- Viens, mon petit. +
Give him a bath and put that +
cute little black suit on him. +
This is a contact at one of our offshore banks. +
On settlement day you'll open +
an account for Mr Gekko... +
..under the name Geneva Roth Holding Corp. +
Then you'll wire-transfer the money +
to this account in the Cayman lslands. +
You're gonna make a lot of money, pal. +
The stakes are going up. No mistakes. +
Piece of cake, Gordon. +
If I could have anything,... +
..this would almost do. +
Almost. +
How'd your conference go with Gordon? +
lt went fine. We reached an agreement, +
and decided to split up the world between us. +
(Darien laughs) +
You have modest wants. +
I like that in a man. +
- What do you want? +
- Let's see. +
A Turner. A perfect canary diamond. +
World peace. +
The best of everything. +
Well, why stop at that? +
I don't. +
My client wants to buy a large block +
of Teldar. He needs to spread it around. +
l'll park some money in your account. +
If it hits, you get a big cut. +
I'm telling you, this is the easiest +
money you've ever made. +
All right, Bud. +
Let's do it. +
We go way back, Harry. +
You know, l-l-l've put a lot of money +
into this firm over the years. +
- I brought in a lot of business. +
- You've taken enough out, too. +
- You should have something put aside. +
- With the divorces I haven't had a chance. +
- The bridges are burned. +
- When you fire me I'm finished. On the street. +
- How do you think I feel about this? +
- How do you think I feel? +
l've got responsibilities. l've got two kids... +
What's going on? +
Lynch is giving him the boot. +
Not pulling his quota. +
We're all one trade away from humility. +
New report on GM and a conference call +
in defence stock in my office, 7 am tomorrow. +
No RSVP required. Just be there. +
Now, on a more inspiring note, +
the new office record... +
..for a single month's gross commission +
from the wealthy individual accounts... +
..goes to Bud Fox. +
Shows cold calling does work, fellas. +
Way to go, Bud. Superjob. Come on up here. +
Bud, congrats. You just made my life +
twice as hard around here. +
You're on a roll, kid. Enjoy it +
while it lasts, cos it never does. +
Just kicking ass and taking names, Lou. +
Come along with me, Bud. +
This is yours now, Bud. +
Credenza. Tree. Windows. +
And, significantly more attractive, +
your private secretary Janet. +
- Nice to meet you, Mr Fox. +
- Hello, Janet. +
Well, I don't really know what to say. +
Thank you, Mr Lynch. +
No, I thank you, Bud. +
The minute I laid my eyes on you +
I knew that you had what it takes. +
Now you can focus on the big-ticket retail. +
Oh, this is very nice. This is very nice. +
So what is it? Mr Cocksucker now? +
Everybody hates the Upper East Side. +
They wanna live on the West Side. +
But when it's resale time +
the East Side moves all the time. +
What have you got on the West Side? +
Sean and Madonna?! Trust me. +
Massage, sauna, Jacuzzi... tanning salon. +
Best schools in the city. +
A cute young boy like you gotta think +
of a future lady friend in your life... +
..when you've finished woIfing around. +
Course, I'm taken. +
Oak strip floors. +
My husband can get you a 10% mortgage. +
I would do it myseIf, except +
I'm into four other deals right now. +
So, I got a four o'clock and a five. One's an +
all-cash type. Monique something or other. +
Look, maybe you'd like to see something +
cheaper that I got on First Avenue? +
Honey, the meter's running. Anybody home? +
All right. Offer 950. +
I got something over on Sutton Place. +
lt's a million and a haIf, +
but now we're talking duplex. +
No. +
This is it. This is home. +
(** "This Must Be the Place" +
by Talking Heads) +
That's enough gold over there. +
Like it? +
I'm having House & Garden come up next +
week to photograph it before it gets lived in. +
Do you mind? +
Hey! Jerry! Come at me. Whaddaya got? +
No, no. 37 1/2. +
Convert the bonds and check the price +
in Tokyo at eight o'clock your time. Right. +
I'm spilling everything. +
(** aria from "Rigoletto"playing on stereo) +
(Bud tries to sing along in mock ltalian) +
lsn't it perfect? +
lt's too perfect. +
Let's not even eat. +
Let's just watch it... think about it. +
Who am l? +
Bud, come to bed. +
One million six. Seven. +
On my left now. +
Against you, 1,800,000. +
1,900,000. New bidder this side. +
$2m here now. +
Not yours. At $2,100,000. $2,100,000. +
Fair warning, then. +
Selling for $2,100,000. All done. +
For you, sir. $2,100,000. +
Whaddaya say we get a suite at the Carlyle? +
Champagne, caviar...? +
Celebrate just like old times? +
Come on, Gordon. Those days are over. +
Well, you can't blame me for trying. +
You're as beautiful as +
that painting I just bought. +
Sunshine, what's wrong? +
I think you got a bad case of puppy love. +
I think I'm falling for Bud. +
Don't fall too far. He hasn't been +
around the block yet. You have. +
- Told him about us? +
- No! Are you crazy? +
- I don't want him to ever know, understand? +
- Mum is the word. +
You and I are the same, Darien. +
We are smart enough not to buy +
into the oldest myth running - love. +
Fiction created by people to keep +
them from jumping out of windows. +
You know, sometimes I miss you, Gordon. +
You're really twisted. +
For chrissake, Jack, it's easy! +
On settlement day you endorse a cheque +
to Blue Horseshoe Trading Company. +
Then l'll send you your cut. +
What? No, that's the bottom line. +
Nobody gets hurt. +
What the fuck is wrong with you? +
lt's so bad, even the liars are complaining. +
But not you. You're making big money. +
- What's the bottom line? +
- Hey, look! +
I am sick and tired of playing +
wet nurse to you! +
- Will you do your own homework, Marv! +
- What an asshole, man! +
That's a shame. +
Yeah, Frank. Work 500,000 shares Teldar +
with a limit of 26. New account. +
Don't fuck it up. +
- How's Teldar doing? +
- Back again? +
- l've got a real appetite. +
- Bring it five to a haIf. 2,000 up. +
- I gotta buy stock. What's offered at a haIf? +
- What are we looking at? +
- Make me an offer on 80. +
- 80,000 at a haIf. +
l'll take it. +
Your company, ladies and gentlemen, +
is under siege from Gordon Gekko. +
Teldar Paper is now leveraged to the hilt, +
like some piss-poor South American country! +
I strongly recommend you to see through +
Mr Gekko's shameless intention here... +
..to strip this company, +
and severely penalise the stockholders. +
I strongly recommend you +
to reject his tender... +
..by voting for management's +
restructuring of the stock. +
Well, I appreciate the opportunity +
you're giving me, Mr Cromwell,... +
..as the single largest shareholder +
in Teldar Paper, to speak. +
(laughter) +
We are not here to indulge in fantasy, +
but in political and economic reality. +
America... America +
has become a second-rate power. +
lts trade deficit and its fiscal deficit +
are at nightmare proportions. +
ln the days of the free market, when +
our country was a top industrial power,... +
..there was accountability to the stockholder. +
The Carnegies, the Mellons, the men +
that built this great empire, made sure of it... +
..because it was their money at stake. +
Today, management +
has no stake in the company! +
All together, these men sitting up here +
own less than 3% of the company. +
And where does Mr Cromwell +
put his $1,000,000 salary? +
Not in Teldar stock. He owns less than 1%. +
You own the company. +
That's right, you, the stockholder. +
And you are all being royally +
screwed over by these bureaucrats,... +
..with their steak lunches, their fishing trips, +
their corporate jets and golden parachutes. +
This is an outrage! You're out of line, Gekko! +
Teldar Paper, Mr Cromwell, +
has 33 different vice presidents,... +
..each earning over $200,000 a year. +
Now, I have spent the last two months +
analysing what all these guys do. +
- And I still can't figure it out. +
- (laughter) +
One thing I do know is that +
our paper company lost $110m last year. +
And l'll bet haIf of that was spent in all the +
paperwork between all these vice presidents! +
The new law of evolution +
in corporate America... +
..seems to be... survival of the unfittest. +
Well, in my book you either do it right, +
or you get eliminated. +
ln the last seven deals that I have been +
involved with there were 2.5m stockholders... +
..who have made a pre-tax profit +
of $12 billion. +
(applause) +
Thank you. +
I am not a destroyer of companies. +
I am a liberator of them! +
The point is, ladies and gentlemen, +
that greed, for lack of a better word,... +
..is good. +
Greed is right. Greed works. +
Greed clarifies, cuts through and captures +
the essence of the evolutionary spirit. +
Greed, in all of its forms - greed for life, +
for money, for love, knowledge - +
..has marked the upward surge of mankind. +
And greed, you mark my words, +
will not only save Teldar Paper,... +
..but that other maIfunctioning +
corporation called the USA. +
Thank you very much. +
** Fly me to the moon +
** Let me play among the stars +
Buy me 20 June eurodollar CDs,... +
..20 March gold and sell 10 September +
Deutschmarks. Right. Talk at ya, babe. +
Ah, Buddy, Buddy, I hate to tell you this, +
but you are a genius! +
Darien! Lightning has struck. +
The light bulb has been invented. +
Bluestar Airlines. +
Edison, da Vinci, Einstein. +
They're all watching me. +
Ever hear of the 60-hour work week? +
You've gotta go to work soon. I'm getting +
psychotic from a lack of REM sleep. +
I'm not gonna broker the rest of my life. +
I am gonna be a giant, an entrepreneur +
in the ltalian 16th-century sense of the word. +
A mover, a shaker. +
I'm shooting for the stars, Darien. +
You're coming along for the ride. +
Bluestar is an unpolished gem, Gordon. +
A haIf-assed management being decimated +
by a price war they cannot win. +
But the gates at La Guardia alone +
can bail us out. +
If it's worth a dime, it's worth 10 bucks +
a share. They're ripe to fall! +
Mixed emotions, Buddy. +
Like Larry Wildman going off +
a cliff... in my new Maserati! +
Guys like me have had their asses hung +
in a sling with the airlines! +
- Fuel could go up. Unions are killers. +
- Yeah, but aren't you forgetting one thing? +
Capital reserves. This company has +
75 million cash in an overfunded pension. +
That buys us a lot of credibility. +
And the beauty is, you already +
own close to 2% of this sucker. +
The insurance people are balking on the +
logging trucks. What do you want to do? +
Tell those assholes +
we'll seIf-insure if they don't write it. +
I can't believe we can fire haIf +
the management and nothing changes! +
(deep sigh) +
Gordon, what I want, +
and l've never asked you for anything,... +
..is to be your copilot on this one. +
I wanna take this airline, turn it around and +
make it work. lt's gonna make us a fortune. +
I got a stockbroker who wants an airline. lt'll +
take two years to turn Teldar Paper around. +
What do I need a dink airline for? I'm up +
to my ass in more nuts than a fruitcake! +
l've worked at Bluestar. I know my way +
around. I have friends there, inside. +
What do you mean? +
The three unions. +
lt's 43% of Bluestar's operating budget. +
The hourly cost of a flight crew is 850 +
an hour. That's the real hidden value, GG. +
If you can negotiate that out, +
get a crew down to 350, 400 an hour,... +
..this airline'll be the hottest thing +
since Texas Air. +
- What makes you think you can? +
- I can talk to these people. They trust me. +
My father can be a big help in getting cuts. +
All right. Susan, get Buckingham +
on the phone. Tell him to look into it. +
So the falcon's heard the falconer, huh? +
- Hi, Dad. +
- Sorry I'm late. +
That's OK. Overdressed as usual. +
Come on in. Everybody's here. +
I couldn't start the show without you. +
Well, l'll be a lousy Republican! +
I decorate for Democrats, too. +
Lots of them. I'm Darien Taylor. +
- Bud's told me all about you. +
- Don't believe a word. +
I never beat him or locked him in a closet. +
- I forgot about the closet. +
- He turned out OK. +
Bud's a born liar, otherwise he's a good kid. +
I hope you come here more often, +
under less formal circumstances. +
Thank you. +
- Dad, you know Duncan Wilmore. +
- Sure. How are ya? +
Pilots' union. +
Toni Carpenter, flight attendants'. +
l'd like you to meet Mr Gekko. +
Mr Fox, pleasure to meet you. +
His attorney, Mr Salt. +
l'd be proud to have a son like Buddy. +
Got a hell of a career in front of him. +
I'm glad you think so. I thought this was +
informal. What's your attorney doing here? +
Harold, you don't mind walking +
around the block, do you? +
- Of course. +
- l'll take that. +
No offence. +
None taken. +
That's OK, Gordon. Bud does it all the time. +
(Gekko) Look, I got no illusions about +
winning a popularity contest with any of you. +
I got roasted the other night. +
A friend asked "Why are we honouring this +
man? Did we run out of human beings?" +
lt's not always the most popular guy +
who gets the job done. +
You've got losses of $20-30 million, +
dividends cut to zero,... +
..and you're being squeezed +
to death by the majors. +
The management may not be the worst scum, +
but they put you on this kamikaze course,... +
..and pretty soon everybody +
is gonna be scrambling for parachutes. +
Only there's not enough to go around. +
Management has them. You don't. +
If they throw Bluestar to Chapter 11, +
which I think they will,... +
..they'll use the bankruptcy laws to break +
your unions, and throw you off the property. +
Oh, come on! With all due respect, what's +
to prevent you from doing the same thing? +
Cos I got a way around all this,... +
..where we can all make money +
and make the airline profitable. +
So what do you say we cut to the chase? +
I'm asking for a modest 20% across-the-board +
wage cut, and seven more hours a month. +
What kind of time frame? +
A year. If we're still losing money, +
the reduction stands. +
If we're in the black, l'll return part of the +
givebacks, pay goes back to current levels,... +
..and we initiate an employee +
profit-sharing programme with stock. +
- You'll own part of the airline. +
- Will you put it in writing? +
l'll have a letter of agreement +
drafted up in two days. +
What's your marketing strategy? +
How will you return us to profitability? +
Why don't I give Buddy an opportunity +
to answer that? Buddy? +
Thank you, Gordon. +
First, I want you all to know +
that my door will always be open,... +
..because I know from my dad +
it's you guys that keep Bluestar flying. +
What l've come up with here +
is a basic three-point plan. +
One: we modernise. Our computer +
software is dogshit. We update it. +
We squeeze every dollar +
out of each mile flown. +
Don't sell a seat to a guy for 79 bucks +
when he's willing to pay 379. +
Effective inventory management +
will increase our load factor by 5-20%. +
That translates to approximately +
$50-200 million in revenues. +
The point being, +
we can beat the majors at a price war. +
Two: advertising. More, and aggressive. +
We attack the majors. +
Three: expansion. We expand our hubs +
to Atlanta, North Carolina and St Louis. +
And we reorganise all +
of our feeder schedules. +
We gotta think big, guys. +
We're going after the majors. +
Well, cards on the table, guys. +
What do you say? +
Well, if you mean what you say, +
I think we're probably in the ballpark. +
- I guess I can take it to my people. +
- Good. +
You've sketched broad strokes. +
l'd like to see the fine print. +
But I like what I hear so far. +
(Carl laughs) +
I guess if a man lives long enough he gets +
to see everything, and I do mean everything. +
What else you got +
in your bag of tricks, Mr Gekko? +
Frankly, Carl, I can't see giving much more, +
but, if you have any suggestions, l'll listen. +
"There came into Egypt +
a Pharaoh who did not know." +
- I beg your pardon. ls that a proverb? +
- No, a prophecy. +
The rich have been doing it +
to the poor since time began. +
The only difference is +
the Egyptians didn't allow unions. +
I know what this guy's all about - greed. +
He don't care about Bluestar or the unions. +
He's in for the buck. He don't take prisoners. +
Wait a minute, Dad. +
Sure. What's worth doing +
is worth doing for money. +
lt's a bad bargain if nobody gains. +
And if we do this deal, everybody gains. +
Course, my son worked as a baggage handler +
and freight loader for three summers. +
With those qualifications, +
he can run an airline! +
Fine. Stay with the present management... +
..dedicated to running you and +
your airline into the ground. +
That "scum" built the company up with one +
plane and made something out of nothing. +
If that's a scum, l'll take it over a rat any day. +
You know where I stand. Good night, all. +
Excuse me. +
Congratulations, Dad! You did a greatjob +
embarrassing me, not to mention yourseIf! +
Save the "workers unite" speech. +
I heard it too much growing up! +
- Oh, yeah? +
- You'll get axed. No two ways about it. +
You and the whole shitty airline +
are going down the tubes! +
And if it isn't Gekko, +
it's gonna be some other killer! +
He's using you, kid. He's got your prick +
in his pocket, but you're too blind to see it. +
No. I see ajealous old machinist... +
..who can't stand the fact that his son's +
more successful than he is! +
What you see is a guy who never measured +
a man's success by the size of his wallet! +
That's because you never had the guts to go +
out into the world and stake your own claim! +
Boy, if that's the way you feel, +
I must've done a really lousy job as a father. +
As far as being axed, I'm still around,... +
..and I have a responsibility +
to the union membership I represent. +
Your responsibility is to present the facts, +
not opinions, to your men. +
You'll destroy their lives. +
Let them decide for themselves. +
My men will want to know what's +
going on, and I won't lie to them! +
Oh, yeah, your men! Your fuckin' men! +
All my life your men have +
been able to count on you! +
Why have you never been there for me?! +
What if you're wrong? +
What if one day the sun didn't rise in the +
east, and for once your compass was off? +
Would you be willing to wreck +
your men's future? My future? +
Dad, think for a change. Be practical. +
I'm asking you. I'm fuckin' begging you! +
I don't go to sleep with no whore +
and I don't wake up with no whore. +
That's how I live with myseIf. +
I don't know how you do it. +
I hope I'm wrong about this guy... +
but l'll let the men decide for themselves. +
That much I promise you. +
You should look at this, Chief. +
A guy at Jackson Steinem... +
..buying large chunks of Teldar Paper +
for an offshore account. +
(knock at door) +
So, what's the problema? +
- Do you know what the fuck the problem is? +
- What? +
- You don't know? +
- I don't know. +
I get a strange call from the SEC. +
They asked to see my records. +
- This is heavy, Bud. +
- Hey, hey, hey, relax! Relax, Roger. +
You're 82M in the account numbers +
and I'm the invisible man. +
Well, that's good for you, Bud. +
They're always looking for red flags. +
Gekko's always getting checked by 'em. +
They never come up with anything, Rog. +
Hey... we're invulnerable on this one. +
I just wanna slow down, Bud. +
All right? +
No more lunches, no calls, all right? +
We suspend our business, all right? +
Whatever you want, Rog. lt's cool. +
Excuse me. Hey, Rog, can you come +
back in? Bring the cost report. +
We're starting again. +
Gekko's asked us into the Bluestar deal. +
We're reviewing timetables. +
- You wanna come? +
- He didn't tell me about that. +
You're only the president of the company. +
What the hell do you know anyway, right? +
Guys, new chief of Bluestar - Bud Fox. +
- Hi. +
- Hello, Bud. +
Guys, what's the problem? lt's time to kill. +
Gekko's got 12% of the stock and climbing. +
Plus he's got the unions in his back pocket. +
Everybody knows the stock's in play. +
By next week the street will own Bluestar. +
ls the bank financing in place? +
Or are we gonna sit around and have +
more of these ridiculous meetings? +
Our firm committed weeks ago 25% +
of the total long-term debt structure. +
Unless you guys sign +
this piece of paper right now,... +
..I'm gonna pull and go to +
another bank for the 75. +
Look, we've got 30 banks ready to participate +
in a four-year revolving credit line. +
We must have your assurance you will pay +
back most of the loan in the first 12 months. +
The only way we can see this happening +
is liquidating the hangars and the planes. +
Can you people guarantee +
the liquidation of Bluestar? +
Guarantee? No sweat! +
We got the Bleezburgs lined up +
to build condos where the hangars are. +
We lay the airplanes off to the Mexicans, +
who are dumb enough to buy 'em! +
And I got the Texas boys drooling +
at my kneecaps for the routes and slots. +
What's your problem? lt's done! +
Here's the price tags +
on the 737s, gates, hangars, routes. +
We got it nailed right down +
to the typewriters. +
The beauty of this deal +
is the overfunded pension. +
Gekko makes $75m there. +
50 million buys him the minimum +
annuities for 6,000 employees,... +
..and he walks away with the rest. +
I figure he'll make... He'll clear $60-70m. +
Not bad for a month's work. +
Your boy really did his homework, Fox. +
And you'll have the shortest executive +
career since that Pope that got poisoned. +
Now he'll really start believing +
he's Gekko the Great. +
- He'd like to change that appointment. +
- Hold this. +
Bud, you can't go in! He's in a meeting! +
Alex has come up with +
an ingenious way for us to... +
I didn't know we had a meeting today, sport. +
I didn't, either. +
I think we should talk, Gordon. +
- Would you excuse us for a second? +
- Won't you come this way, gentlemen? +
Thank you, Alex. +
What do you want? +
I just found out about +
the garage sale at Bluestar. +
Why?! +
Last night I was reading Rudy +
Winnie-the-Pooh and the Honey Pot. +
You know what happened? He stuck his nose +
in the pot once too often, and he got stuck. +
Maybe you oughta read him Pinocchio. +
I thought you were gonna turn +
Bluestar around, not upside down! +
- You fuckin' used me! +
- You're walking around blind without a cane. +
A fool and his money are lucky to even meet. +
- Why do you need to wreck this company? +
- Because it's wreckable, all right?! +
I took another look. I changed my mind. +
If they lose theirjobs, +
they got nowhere to go! +
My father has worked there for 24 years! +
I gave him my word! +
lt's all about bucks, kid. +
The rest is conversation. +
Buddy, you'll still be president. +
When the time comes, +
you'll parachute out a rich man. +
With the money you'll make, +
your dad's never got to work again. +
So tell me, Gordon, +
when does it all end, huh? +
How many yachts can you water-ski behind? +
How much is enough? +
lt's not a question of enough, pal. +
lt's a zero-sum game. +
Somebody wins, somebody loses. +
Money itseIf isn't lost or made, +
it's simply transferred... +
..from one perception to another, like magic. +
This painting here. +
I bought it ten years ago for $60,000. +
I could sell it today for six hundred. +
The illusion has become real. +
And the more real it becomes, +
the more desperate they want it. +
Capitalism at its finest. +
How much is enough, Gordon? +
The richest 1% of this country owns haIf +
our country's wealth. Five trillion dollars. +
One third comes from hard work, +
two thirds from inheritance,... +
..interest on interest accumulating +
to widows and idiot sons,... +
..and what I do: +
stock and real-estate speculation. +
lt's bullshit. +
You got 90% of the American public +
with little or no net worth. +
I create nothing. +
I own. +
We make the rules, pal. +
The news, war, peace, famine, upheaval, +
the price of a paperclip. +
We pick that rabbit out of the hat while +
everybody wonders how the hell we did it. +
You're not naive enough to think we're +
living in a democracy, are you, Buddy? +
lt's the free market, and you're part of it. +
Yeah. You got that killer instinct. +
Stick around, pal. +
I still got a lot to teach you. +
Obviously. +
Oh, Buddy, come on. +
I was gonna tell you about it. +
Calm down, all right? +
We'll have dinner tonight. Bring Darien. +
No, I can't make it tonight. +
Hey, Buddy. +
Are you with me? +
I need to know if you're with me. +
I'm with you, Gordon. +
- Natalie, l'll be right there. +
- Yes, Mr Gekko. +
- Yeah? +
- Yeah, Ollie. +
Tell them I want ziplocked mouths +
on the Bluestar deal,... +
..or l'll come down there +
and rip out their fuckin' throats. +
Bud? +
What's going on? +
l've been played like a grand piano +
by the master, Gekko the Great. +
Today was the big crash,... +
..the liquidation sale. +
He's gonna carve Bluestar +
into little pieces and sell it all off. +
Bastard! +
I'm sorry. +
I was afraid something +
like this could happen. +
I handed it to him on a silver platter. +
I told my father... +
Bud! Bud, it's not your fault. +
And it's not your decision. +
I'm not gonna let it happen. +
Don't cross Gordon. He'll crush you. +
If Gordon doesn't buy Bluestar, someone else +
will. Who's to say they won't do the same? +
At least I won't be pulling the trigger. +
Why are you doing this? +
You've worked hard to get where you are. +
We're so close. +
You don't wanna throw it all away. +
Look, I can stay with the firm, +
and you're doing fine. +
We can survive without Gordon Gekko. +
I'm not looking to just survive. +
l've been doing that all my life. +
Cut this seIf-pity crap, Bud! +
What the hell's that supposed to mean? +
lt means if you make an enemy of Gordon +
Gekko, I can't be there to stand by you. +
Oh, yeah? Do you really mean that? +
What did he promise you? +
To take you public? +
Without his money and seal of approval +
I'm not such a hot investment any more. +
- You're just the best money can buy, Darien. +
- You're not exactly pure, Bud. +
You went after Gekko and me with +
the same vengeance. Look in the mirror. +
I'm looking, and I sure don't like what I see. +
Fair enough. But it's not that simple, Bud. +
When I was down and had nothing, +
it was Gordon who helped me. +
He got me all my clients - you among them - +
and he can take them away from me like that. +
You may find out that when +
you've had money and lost it,... +
- ..it's worse than never having had it at all. +
- Oh, yeah? +
That is bullshit! +
Hey! Hey! +
You step out that door +
and I am changing the locks! +
You may not believe this, Bud, +
but I really do care for you. +
We would've made a good team. +
I'm sorry. +
Get the fuck outta here! +
The market is dead right now. +
Even the rich are bitching. +
The only thing moving is the termites +
and cockroaches, and my commission... +
Look, save the rap, all right? +
Just sell the fucker, fast! +
There he is. +
Where you been the last two days? +
- Janet, get my father on the phone and... +
- Your mom's been calling. Your father's... +
- What happened? +
- He had a heart attack, but he's OK. +
- He's at St John's. +
- Oh, Christ! +
Mom? How is he? +
He was complaining +
about chest pains at work. +
The next thing I know he's collapsed. +
You gotta talk to him. +
Don't worry, he's a tough old nut. +
He's got another 20 years. +
- He's gonna be fine, Buddy. +
- ls he conscious? +
Hiya, Dad. +
You're looking younger every day. +
Didn't I tell you never +
to lift a 747 by yourseIf? +
You even got me smoking now. +
lt's your second heart attack, Dad. +
You're pushing your luck. +
I hope you know that. +
I guess I never told you,... +
..but I love you, Dad. +
I love you so much! +
I'm sorry... about the things I said. +
You're the only honest man I know. +
The best. +
I got a plan, Dad. I can save the airline. +
I know you got no reason to believe me, +
but you have to trust me, OK? +
I need to speak to the union members. +
Can I speak for you? +
Your words, not mine. +
OK. +
I gotta go. +
I'm proud of you. +
The stock's at 19 1/4, and it's going up. +
Gekko figures, by breaking up Bluestar, +
it's 30 bucks a share. +
He'll buy up to 24 and still +
think he's making money. +
How do you know it'll go up? +
You don't wanna know, Duncan. +
Let's just say I have some friends. +
OK. What happens now? +
When it hits 23, you go +
to Gekko and lower the boom. +
When he learns he has no union +
concessions, he'll jump ship. +
Yeah, but who'll buy then, and what's +
to prevent some other shark devouring us? +
We have an appointment to see Mr Wildman. +
Sir Lawrence, or can I call you Larry? +
What would you say to owning Bluestar +
Airlines, with union concessions,... +
..at $18 a share,... +
..and, in the process, hanging +
Gordon Gekko out in the wind to twist? +
I might be very interested. Why you, mate? +
What's a bloke like you +
doing mixed up with Gekko? +
Let's just say that me and Mr Gekko +
have a serious conflict of interest. +
But we all wanna see this airline work. +
These figures show that it can. +
You're prepared to take +
these large salary cuts? +
We are, but we want a contract +
agreement that's ironclad. +
So if you buy it, you can't break it up. +
I'm still listening. +
Hi. +
Oh, hi. Say, why don't you +
get the hell out of my office? +
I know l've been a schmuck lately. +
I want to apologise. +
You've been a real schmuck lately. +
So go thou and sin no more. +
I wanna make it up to you. +
Bluestar. Put all your clients in it. +
OK, Buddy-Buddy. +
We are back in business on Bluestar. +
Bluestar, Mr Mannheim. +
Put all your clients in it. lt's gonna move. +
I don't know where you get +
your information, son, but I don't like it. +
The main thing about money, Bud... +
it makes you do things you don't wanna do. +
Marty, a favour. 200,000 shares Bluestar at +
19 1/2. Can you position it in an equity fund? +
- The Chronicle is on seven. +
- Hold, Marty. +
Listen, Blue Horseshoe +
loves Bluestar Airlines. Got it? +
- Got it. +
- Right. Marty, you still there? +
Bluestar's in play. Let's check it out. +
(traders shouting) +
- 19 1/4, 3 1/2. 5,000. +
- 3 1/2 at 10,000. +
I do love it so. +
Gordon, I see it at 215 1/2. +
I don't know what to make of it. +
The word is out, pal! +
Your union buddies are talking. +
You get me in at a 45-degree angle. +
All the way in. +
You slash and burn, you buy everything +
in sight up to 22, then call me. +
When I get hold of whoever leaked this, l'll +
tear his eyes out and suck his fuckin' skull! +
- Stock's going to Pluto. +
- Start unloading. +
- What? Sell? +
- Dump it! Now! Dump it all! +
- Where's Lou? +
- Right over there. +
Ken? Marvin. Jackson Steinem. +
Dump this baby. Take the money and run. +
We're getting out. +
lt's gotta be a big hitter. +
There's some people from Bluestar +
demanding to see you. +
- What the hell do they want? +
- l'd be happy to tell you. +
We know what you're up to, Gekko, +
and you can go straight to hell! +
No way you're gonna break up our airline. +
- If that's my plan, it's the first l've heard of it. +
- Would you put that in writing? +
We have an agreement, +
which I expect you to honour. +
- Then you better have a pilot's licence. +
- Don't worry, the engines won't fall out. +
But those reservations can get screwed up +
if we don't pay attention. +
Baggage for St Petersburg +
could wind up in Pittsburgh. +
Look, somebody else +
wants to buy your airline. +
You wanna be gobbled up +
by Attila the Hun, you be my guest! +
We'll take our chances. +
Nice to see you, Gekko! +
Fox says Bluestarjust hit 23. +
What do you want him to do? +
Sell it all. +
- What the hell. So we only make 10 million. +
- Sell it. Yes, all of it. +
10,000 at 7 1/2! +
At 7 1/2, sold! +
Frank, Frank, Frank, Frank, for chrissake! +
Goddamn connection! +
Bob, we're in big trouble on BST. +
You gotta get out now. +
Another 30,000. Out! +
Gekko's selling. There's not many takers. +
The stock is plummeting. +
I guess l'll have to carry him +
a few rounds before he drops. +
Don't make a big deal of it. Buy it lightly +
on the way down. When it hits 18, buy it all. +
Piece of cake, Larry. +
(traders shouting) +
8,000 at 18. +
What is offered at 18? +
300,000... 300,000 at 18! +
18 for 500,000! +
(traders) Sold! +
- l'll sell you 50! +
- l'll take it! +
- There's gotta be a way outta this. +
- Sure. Why don't you dial 911? +
Fox is on four. +
Where the hell are you? I am losing millions. +
You sure as hell better get me out of this,... +
..or the only job you'll have +
on this street is sweeping it! +
You once told me, don't get emotional +
about stock, Gordon. Don't. +
The bid is 16 1/2 and going down. +
As your broker, I advise you to take it. +
Yeah? Well, you take it! Right in the ass, +
you fuckin' scumbag cocksucker! +
lt's two minutes to close, Gordon. +
What do you wanna do? Decide. +
Dump it. +
The big Wall Street story today +
was Bluestar Airlines. +
Fuelled by takeover rumours, the stock +
soared to an all-time high of 24 1/8. +
When rumours later surfaced +
that the takeover was unfounded,... +
..buyers ran for cover and the stock +
plummeted to 16 1/2 before closing at 17. +
Then, amidst all the scuttlebutt, +
another rumble shook the street. +
Raider Sir Lawrence Wildman has stepped in +
and bought a substantial block of Bluestar,... +
..and will announce a deal tomorrow +
that includes the support of the unions. +
We talked with a leading +
stock market analyst,... +
..in order to understand the ramifications... +
Son of a bitch! +
Smile, Carolyn. There's justice in the world. +
Good morning, folks. +
Did somebody die? +
Yeah. +
Morning, Chuckie. Morning, Lou. +
Bud... +
Bud, I like you. +
Just remember something. +
Man looks in the abyss. +
There's nothing staring back at him. +
At that moment, man finds his character. +
And that is what keeps him out of the abyss. +
I think I understand. +
Janet, get my father, will you? +
He just came in. l'll call you back. +
I guess you're not here to open an lRA. +
Henry Patterson, Postal lnspection Service. +
Mr Ebenhopper, US Attorney's office. +
Evan Morrissey, Securities and +
Exchange Enforcement office. +
You're under arrest for conspiracy +
to commit securities fraud,... +
..and for violating +
the lnsider Traders Sanction Act. +
The minute I laid eyes on you, +
I knew you were no good. +
You have the right to remain silent +
and refuse to answer questions. +
Anything you do say +
may be used against you. +
You have the right to consult an attorney... +
..and to have an attorney present +
during any questioning. +
So long, Carolyn. +
Hiya, Buddy. +
Gordon. +
Sandbagged me on Bluestar, huh? +
I guess you think you taught the teacher +
a lesson, that the tail can wag the dog, huh? +
Well, let me clue you in, pal. +
The ice is melting right underneath your feet. +
You think you could have gotten this far +
this fast with anybody else? +
And dickin' someone like Darien? +
No. You'd be cold-calling widows and +
dentists to buy fuckin' dogshit stock! +
I took you in! +
A nobody! +
I opened doors for you. +
I showed you how the system works, +
the value of information, how to get it! +
Fulham Oil, Brant Resources, Geodynamics! +
And this is how you fuckin' +
pay me back, you cockroach! +
I gave you Darien! +
I gave you your manhood! +
I gave you everything! +
You coulda been one of +
the great ones, Buddy. +
I look at you... and I see myseIf. +
Why? +
I don't know. +
I guess I realised that... +
..I'm just Bud Fox. +
As much as I wanted to be Gordon Gekko... +
..l'll always be Bud Fox. +
(tape) I showed you how the system works, +
the value of information, how to get it! +
Fulham Oil, Brant Resources... +
You did the right thing, Bud. +
(Carl) You told the truth +
and gave the money back. +
All things considered in this +
cockamamie world, you're shooting par. +
You helped save the airline, +
and they'll remember you for it. +
That's right. Think about the job +
at Bluestar that Wildman offered you. +
Dad, I'm going to jail and you know it. +
Yeah, well... maybe that's the price, son. +
lt's gonna be hard on you,... +
..but maybe in a kind of screwed-up way it's +
the best thing that coulda happened to you. +
Stop going for the easy buck +
and produce something with your life. +
Create, instead of living off +
the buying and selling of others. +
We'll park the car and catch up with you. +
All right. +
("This Must Be the Place" by Talking Heads) +

'''
