= 1902
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 597.
This is English as a Second Language Podcast’s English Café episode 597. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we’re going to talk about the symbol – or at least, one of the important symbols – of the United States: the bald eagle. And as always, we’ll answer a few of your questions. Let’s get started.
Most countries around the world have some sort of national symbol, something that represents them or reflects perhaps something about their land or culture. We sometimes call these symbols “emblems.” An “emblem” (emblem) is basically a symbolic object or image that represents a country, but it could also represent an organization or even a family.
Today we’re going to talk about an important emblem of the United States: the animal the bald eagle. An “eagle” (eagle) is a bird, and a “bald (bald) eagle” is a kind of eagle, a particular type of eagle. The bald eagle has been the national bird of the United States since the very beginning of our country, since 1782. In fact, it is called a “bird of prey” (prey) because it hunts or chases other animals for food, mainly fish.
The bald eagle has a brown body and a white head. It’s the white head that gives it its name “bald eagle.” “Bald” normally, in American English, means having no hair, but the bald eagle is not, in fact, bald. It does have feathers. The reason it’s called a “bald eagle” is because many years ago, the word “bald” meant simply having a white head, and that’s why it’s called a “bald eagle” – because the feathers on its head are white.
Now, the bald eagle is a very large bird. It can fly quite fast, up to 65 miles per hour, which is faster than some of the cars I have owned in the past. The length of the eagle, the body length, is somewhere between 28 and 40 inches (that would be 70 to about 100 centimeters), but it has a very large wingspan. The “wingspan” (wingspan) is how long the wings are if they are at their maximum extension, if the bird has them out all the way. The wingspan on a bald eagle is somewhere between six and seven and a half feet.
Bald eagles, like all eagles, can see four or five times as far as the average human can see. It’s because of this that we have the expression, in English, an “eagle eye.” Someone who has an “eagle eye” is someone who is able to either see things at a distance, but more generally to watch something very closely, to be able to see or notice many things.
The bald eagle appears in many official documents and other things that are associated with the U.S. government. It is, for example, on the flag of the president of the United States. I didn’t actually know the president of the United States had his own flag. I guess, I did – I certainly know he has his own emblem, his own symbol, and the bald eagle appears on that emblem, so when the president of the United States, for example, is giving a talk or giving a speech, there will usually be a circle on the front of his “podium” (podium). A “podium” is something that you put your pieces of paper on when you’re giving a speech or a talk. The president has his own emblem that has the bald eagle on it.
The bald eagle also appears on what are called “military insignia.” An “insignia” (insignia) is some sort of image or marking that is typically part of a military uniform that shows your, what we would call, “rank” (rank), or position within the military. You could be a general. You could be a lieutenant. You could be a captain. You could be a private. All of those are “ranks,” or positions in certain parts of the military. Well, a military insignia often appears on the uniform, the clothing that a soldier wears, and the bald eagle will often appear in some of those insignias.
The bald eagle also appears, more importantly, on billions of one dollar bills that are in circulation or use. The back, what we would normally call the “reverse (reverse) side,” of a U.S. dollar bill has the image of a bald eagle. The bald eagle also appears on the reverse side or back side of many U.S. coins. The decision to make the bald eagle an emblem of the United States was not an easy one. Believe it or not, what we call our “Founding Fathers,” the mostly men who established the United States, argued a lot about the national symbol when the country was first getting started.
In fact, for six years, the lawmakers – the people who represented the population in the U.S. government, the new U.S. government – had lots of arguments about what the national emblem should be. Some people say that the new American government saw itself similar to the Roman republic since we were, after all, founded as a republic as well. The eagle had been associated with the Romans, the Roman republic, and therefore the new American government wanted it to be associated with its own new project as a republic.
The eagle has often been seen as a symbol of strength, of courage, and of freedom, and unlike other eagles, the bald eagle is one that is indigenous only to North America. “Indigenous” (indigenous) means it is originally from a particular place or is normally or naturally found in a certain area. We sometimes use that adjective “indigenous” to refer to those who have lived in an area for a very long time, before anyone else arrived there. We talk about the “indigenous peoples of North America,” more commonly known in the United States as “American Indians” or “Native Americans.” All of those terms mean the same thing, refer to the same thing.
The bald eagle is indigenous to North America, so it was logical that if the founders of the new republic of the United States were going to pick an eagle, they would pick the bald eagle. Not everyone agreed with the symbol of the eagle as part of our national emblem. In fact, there’s a story that’s often told to American schoolchildren that most Americans believe, though many historians think is probably not correct, which is that Benjamin Franklin, one of our most famous founders, was very much against the bald eagle and instead wanted a turkey to be our national bird.
Well, the evidence is a little unclear. It’s probably not true, according to some historians, that Ben Franklin wanted a wild turkey to be our national emblem, although he did write a letter criticizing the bald eagle. He said the bald eagle was not a good choice because it was a bird of bad moral character. A person’s “moral character” (character) is how someone lives his life – whether he is honest, whether he is fair, whether he is a person who is loyal, who supports and defends his friends.
Franklin said that the eagle was an animal that lived basically by killing and stealing from other animals, and therefore he was not a good choice as the national bird. Now, Franklin apparently said this in a letter to his daughter. Now in that same letter, Franklin says that he would have preferred a wild turkey to be the national bird. He thought the turkey, which is something we normally eat during the Thanksgiving holiday, was more respectable. It was a bird that had better behavior. It was more correct and appropriate. The turkey was also native to the United States, and therefore should represent the United States.
Well, some people say that Franklin was in fact being “satirical.” He was, in a sense, joking about the idea that a wild turkey should have been our national bird. Whatever story you want to believe, to me the most surprising thing about reading the history of the bald eagle and America’s national emblem is just how much time the Founding Fathers spent on this topic, debating it back and forth.
They had something like three or four different committees, groups of men that sat around thinking about the design and arguing over exactly what it should say. I don’t know. It seems to me perhaps they had more important things to do, but they had a lot of extra time. There was no Facebook back in the 1780s, so instead of watching cat videos, they were debating our national emblem. So maybe it wasn’t such a bad idea to take their time on it.
The bald eagle was quite common as a bird back in the late eighteenth century in North America. It’s estimated there were probably 100,000 or so bald eagles back in 1782, the year we adopted the eagle as our national bird and made it as part of our national emblems. The first major decline probably began in the late 1800s, for a couple of reasons. Bald eagles ate fish primarily, but eagles also ate chickens and lambs and cows and other farm animals. For this reason, people who had farms started shooting the bald eagles, naturally, to prevent them from eating the animals that they owned.
The second reason that the number of bald eagles declined is, according to some, the introduction of pesticides. A “pesticide” (pesticide) is a chemical that you put on plants to prevent bugs and other insects from hurting the plants. Some people say this use of pesticides also caused the bald eagles to become sick and to die, mainly because this chemical or these chemicals made their way into or eventually got into the lakes and waters where the fish lived that the bald eagles ate.
These chemicals then poisoned the bald eagles in some way. “To poison” (poison) is to introduce a chemical or a substance into someone’s body that causes them to become sick or even die. By 1940, it was clear that the government had to do something to protect the bald eagle. So they passed, or approved, a law called the Bald Eagle Protection Act. This law made it a crime to kill, sell, or even own as a pet a bald eagle. By 1963, however, there were estimated to be only about 480 pairs of bald eagles left in the U.S. The bald eagle, in other words, was in danger of extinction.
“Extinction” (extinction) is when a type of animal no longer exists – the last living one dies and there are no more left. In 1967, the government, the federal or national government, included bald eagles under what was called the Endangered Species Preservation Act. “Endangered” (endangered) means that this animal – this type of animal called the “species” (species), which is a classification – is in danger of extinction, and therefore must be protected at all costs.
Listing the species as “endangered” allowed the government to work more aggressively to save the remaining bald eagles. This included helping the bald eagles breed. “To breed” (breed) means to have more babies. In this case, they captured the bald eagles. They gave them a nice bed, some soft music, perhaps a little wine, and of course what always happens – the bald eagles decided to do what was necessary and more baby bald eagles were born.
By 2007, there were about 10,000 pairs of bald eagles. So the efforts were successful. In fact, there were so many bald eagles that in 2007, the bald eagle was removed from the list of endangered species. You can now find a lot more bald eagles, many more, in North America and particularly in Florida, which is where apparently their main breeding areas are.
In addition to important documents that contain the bald eagle as part of the symbol or emblem of the United States, the bald eagle is also on what is called the “Great Seal (seal) of the United States.” The word “seal” can actually refer to another animal, perhaps even the kind of animal that a bald eagle might want to eat. A “seal” is a sea animal. However, here the word “seal” refers to an emblem – something that is usually made and put on an official document. So, it’s very similar to the word “emblem” that we’ve been using all this time.
The Great Seal of the United States has the image of the bald eagle. That image includes the bald eagle holding 13 olive branches in one, we would call, “talon” (talon), which is sort of like the hand or foot of the eagle. I guess the foot of the eagle would be a better comparison. And 13 arrows in the other talon. Why 13? Well, there were 13 original U.S. states, so each of those represented a state. The olive branch has traditionally been a symbol of peace. A “branch” is a part of a tree.
An “arrow,” of course, is a symbol of war.
So you have these two symbols, war and peace, as part of the national seal of the United States. The idea being, of course, that we want to be a peaceful country but we will protect our interests, I guess. Thirteen is a number that is important in the Great Seal not just for the number of olive branches and arrows. There are also 13 stars above the eagle in our great seal. There are 13 stripes or lines in the shield or in the Great Seal, and there are 13 letters in our national “motto” (motto). A “motto” is a short sentence or phrase that is supposed to express the beliefs or ideas of a group.
Traditionally, in many western countries, this motto has been written in Latin. Our national motto, which has 13 letters, is “E Pluribus Unum,” meaning “from many, one,” or “out of many, one.” So, out of these 13 states we have one country or one nation. That’s the idea. So that’s a little of the bald eagle and its importance in the symbolism of the U.S.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Rodrigo (Rodrigo) in Mexico. Rodrigo wants to know the difference between “to sleep (sleep) in” and “to oversleep” (oversleep).
“To sleep,” of course, means to temporarily become unconscious so that you are not aware of the world around you. We sometimes use the verb, or phrasal verb, “to fall (fall) asleep (asleep).” “To fall asleep” means to go into the state of sleeping, that state of unconsciousness. Notice that “sleep” is a verb. The adjective and adverb is “asleep.” So, I would say, “He is asleep” with an “a” at the beginning. I could also say, “He is sleeping,” but notice “sleeping” there is a form of the verb “to sleep.”
Now, “to sleep in” means to sleep longer than you normally do. Usually we use this phrasal verb when we are referring to something that you do intentionally, meaning you want to. “I’m going to sleep in tomorrow morning because it’s Saturday and I don’t have to get up early to go to work.” That’s “to sleep in.” It’s something you usually decide you’re going to do. You’re going to sleep later than you normally do or stay in your bed later than you normally do.
“To oversleep,” however, means that you sleep longer then you normally do but not because you wanted to – perhaps you were really, really tired and you wanted to get up at six o’clock in the morning, but you did not wake up or come out of your state of sleeping until eight o’clock. You “overslept.” You “overslept by two hours,” we would say. So “oversleeping” is when you sleep longer than you want to or had planned to. “To sleep in” means that you sleep longer than you normally do, but usually because you wanted to sleep that long. It was your plan to do so.
Our next question comes from Omid (Omid) from an unknown country, although I’m sure it’s a very beautiful country, as most countries are. Omid wants to know the meaning of the expression a “first cousin” and also what we mean when we use a number and the word “removed” after a cousin or relative. When we say, for example, “He’s my second cousin twice removed.” What do these numbers – “first,” “second,” and “third” – before the word “cousin” mean, and what does the word “removed” mean?
This is a good question because I’m guessing a lot of Americans or native English speakers don’t themselves understand anything beyond the concept of “first cousin.” So let’s start with that. Actually, let’s start with the word “cousin” (cousin). Your “cousin” is the son or daughter of your aunt or uncle. So, my father had several brothers and sisters, and the sons and daughters of those brothers and sisters – who are, after all, my aunts and uncles – are my cousins. Now, I would call them my “first cousins” because they are grandchildren of my grandparents.
So, your “first cousins” share grandparents with you. Obviously the parents of my father and the parents of my father’s brother were the same. Well, not necessarily the same, but in this case they were the same, so those are my “first cousins” – when we share grandparents. Now, if we go back one more generation – one more level, if you will, in time – we could talk about my great-grandparents. These would be the parents of my grandparents. Well, they also could have brothers and sisters, and did, and they could have children, and those children could have children. Well, now we’re talking about “second cousins.” We share great-grandparents.
My “third cousins” are cousins with whom I share great-great-grandparents. Now, if you sit down and draw what we would call a “family tree” (tree), where you show these relationships on a little chart on a piece of paper, you would immediately realize that just saying “second cousin” or “third cousin” isn’t really good enough, because if we’re talking about, say, great-grandparents, well, they had children, and those children had children, so there are different generations – or ages or levels, if you will – of your family tree that the word “second cousin” and “third cousin” doesn’t distinguish between.
It could be someone who is the “great-grandchild,” but it could also be a “grandchild.” Both of those have similar relatives in common. So that’s where we come in with the term “removed.” The term “once removed” means we are of a different generation. Let’s go back to first cousins. The children of my aunts and uncles are my “first cousins” and we are of the same generation. We are of basically the same ages, of the same age group, although that’s not the best definition of “generation,” but it usually works out that way, that you’re about the same ages as your cousins, within maybe 15, 20 years, let’s say, maximum.
Well, I don’t use the word “removed” in talking about my first cousins because we are of the same generation. I am the child of my parents. They are the children of my aunts and uncles. So there’s no difference in generation. However, once we start talking about second, third, and fourth cousins, then we’re talking about great-grandparents and great-great-grandparents, the parents of my grandparents and their parents and so forth. Now we have to distinguish the generation – the level at which they are removed from my generation.
For example, my mother has cousins, first cousins. Those first cousins are the children of her aunts and uncles. They’re also my first cousins, but they’re my “first cousins once removed,” meaning they’re not in my age group. They’re not in my generation. They’re in my mother’s age group, my mother’s generation. My mother’s generation is one generation younger than my grandparents, but I’m two generations younger than my grandparents. Therefore, there’s a one-generation difference and that comes out to be “once removed.”
“Twice removed” means there’s a two-generation difference and so forth. So, I’m two generations younger than the first cousin of my grandmother. So my grandmother’s first cousin is my “first cousin twice removed” because there are two generations’ difference. Are you still confused? Well yeah, a little bit, but you get the general idea, I think. There will not be a quiz on this. There will be no tests at the end of this lesson, don’t worry.
Our final question comes from Lilian (Lilian) in Brazil. Lilian wants to know the meaning of the word “wanton” (wanton). “Wanton” is an adjective that can mean a couple of different things. It could mean not showing any care for the feelings or safety of others. It’s used in this sense often in front of the word “destruction.” “There was wanton destruction by the army that came in and burned down houses and destroyed cars and other property.” The word “wanton” there refers to the fact that the army didn’t care about the rights or the safety of people when it went around and did the damage that it did.
The word is also often put before the word “disregard” (disregard). “Disregard” means not paying attention or not protecting something, perhaps doing something without worrying about how dangerous it is. “Wanton disregard,” then, is someone who doesn’t pay attention to how much damage could be done to something. Again, it’s related to that same idea of not caring or thinking about the feelings or safety of others. There’s an old definition of “wanton,” not used as much anymore, to describe a woman who has sexual relations with many different men.
This might be closer to the question that Lilian asked about, perhaps something she read in an older book, “wantonness” (wantonness). “Wantonness,” as a noun, would probably refer more to the activities of a woman having sexual relations with many men, not caring about the ethics or morality of it. “Wantonness” might describe the behavior of men as well. It’s what we might refer to as a “literary use” – something you will see in literature, in books, more than you will ever in conversation.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2017 by the Center for Educational Development.
Glossary
emblem – a symbolic object that represents a country, organization, or family
* Our organization’s emblem is the dove, which represents peace.
bird of prey – a bird that hunts or chases and other animals for food, mainly fish
* The falcon is a bird of prey often trained for hunting.
bald – for the head to have no hair; for an animal to not have fur, feathers, or hair
* Grandpa is bald, but his brother isn’t. Do you think Dad will be bald, too?
eagle eye – able to watch things carefully and see or notice many things
* Monica’s eagle eye saw the incoming airplane before anyone else did.
insignia – a marking, usually on a military uniform, that shows one’s rank or position within the military or indicating one’s membership in an association
* Based on the insignia on the police officer’s uniform, she’s a captain.
moral character – whether a person has good qualities, such as honesty, loyalty, and courage
* Our school only hires teachers whom we believe to be of good moral character.
respectable – being good and proper, behaving in a way that is correct and appropriate
* Our neighborhood is made up of respectable families and is no place for a bar.
indigenous – originally from a particular place; naturally occurring in a given area
* Many plants growing in California are not indigenous but come from as far as away as New Zealand.
pesticide – a substance used to kill insects and other living things that hurt plants
* Are you sure that this pesticide is safe for our tomato plants and won’t harm our pets?
to be poisoned – to eat, drink, or in some other way get into the body a substance that hurts or kills
* Keep these cleaners out of reach of children if you don’t want them to be poisoned accidentally.
extinction – a state in which an entire kind of animal no longer exists; for a type of animal to no longer have any living members
* The extinction of dinosaurs over a large area of the Earth occurred in a short period of time.
endangered – for a type of animal to be in danger of having no living members
* The black rhino is endangered and if we don’t do something soon, our grandchildren will never be able to see a live one.
seal – a device with an image or word cut into it so that when it is placed over hot wax, makes an impression of that image, used to show that a document is real or official
* The Great Seal of California shows a grizzly bear on one side.
motto – a short sentence or phrase that expresses the beliefs or ideas of a person or group
* Our family motto is: “We stay together no matter what.”
to sleep in – to sleep past the time when one usually gets up; to sleep to a later time than usual
* The best part of the weekend is being able to sleep in on Saturday mornings.
to oversleep – to sleep past the time when one planned to get up; to sleep to a later time than one planned or is allowed
* Paolo overslept and miss his train, so he arrived late for work.
to be (once, twice, etc.) removed – to be related by blood or marriage but separated by a certain number of generations
* Luisa is my cousin once removed, so her mother and I are about the same age.
wanton – an old-fashioned term used to describe a woman who has a sexual relationship with many men; showing no thought or care for the rights, feelings, or safety of others; not limited or controlled
* Grandpa complained about the wonton behavior of young woman today, but we told him that times have changed.
What Insiders Know
Success Stories of Animals Once Endangered
The Endangered Species Act tries to prevent “extinction” (when a type of plant or animal can no longer be found), and although saving some of the listed “species” (types of plants and animals) is “an uphill battle” (something that is extremely difficult to do), there are some “success stories” (stories about things that have been done well).
A small fish known as the Oregon Chub was listed as an endangered species in 1993, when there were only eight known “populations” (groups of the fish living together). Under the protection of the Endangered Species Act, the fish populations grew. In 2010, the Oregon Chub was reclassified as “threatened” (still in danger, but not as badly as an endangered species). Today there are 50 known populations of the Oregon Chub, and it has been “proposed” (suggested) for “delisting” (taking off the endangered species list).
In 1962, the American “alligator” (a large, long reptile that can live in the water) received protection under the Endangered Species Preservation Act, the “predecessor of” (what came before) the Endangered Species Act. Populations “rebounded” (became healthy again) and in 1987 it was relisted as a threatened species. Today, it remains on the list because the animals appear similar to other species that are “hunted” (killed for sport), but it is no longer at “imminent” (very likely to happen very soon) risk of extinction.
The population of gray whales was “devastated” (hurt very badly) by hunting from the mid-1800s to the early 1900s. In the 1930s, they were protected under a “whaling ban” (an agreement to not hunt whales) and then later listed under the Endangered Species Act. The Eastern North Pacific population has rebounded and in 1994 was delisted. However, the Western North Pacific population “comprises” (is made up of) fewer than 100 whales and is “gravely” (seriously) endangered as of 2017.