= 1897
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 592.
This is English as a Second Language Podcast’s English Café episode 592. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we’re going to talk about one of the great American authors and poets, Henry Wadsworth Longfellow. And as always, we’ll answer a few of your questions.
Let’s get started.
Henry Wadsworth Longfellow was born in February of 1807 in the town of Portland, Massachusetts. Now, I say Portland, Massachusetts, because that’s where Portland was at the time. It was part of the state of Massachusetts, which you may know is located on the East Coast of the United States, on the Atlantic Ocean, in the northeast part of the U.S. However, the state of Massachusetts split up later, and the town of Portland became part of the new state of Maine when Maine became a state, a few years after Longfellow was born in 1820.
Longfellow was a very well-educated young man. He went to a good college called Bowdoin College in the town of Brunswick, Maine. Brunswick is about 140 miles – that would be 225 kilometers – northeast of Boston, which is the largest city in Massachusetts. At college, Longfellow studied literature and showed that he was very good at translating books and other pieces of writing. “To translate” (translate) means to put something in one language into another language.
We usually use the verb “translate” when we’re talking about writing – taking a piece of writing and putting it into another language. If someone is talking and you are putting their words into another language, we usually use the verb “to interpret.” So “interpretation” is when someone is giving the message in another language orally, and “translation” is when it is done in writing. Nevertheless, the word “translation” is nowadays often used to refer to both translating and interpreting. Longfellow was very good with languages. He was quite fluent in Latin.
After he graduated in 1825, he was offered a job at Bowdoin College to be a teacher, a professor in their modern language department. Part of the job required that he actually go to Europe to learn more languages, and of course he said yes. Longfellow went to Europe and studied French, Spanish, and Italian for the next four years. He returned to Bowdoin College in 1829 and began to teach. He was also the school’s librarian. The “librarian” (librarian) is the person who takes care of the “library,” a place where books and other documents are kept, of course.
He also began writing poetry and other essays. He also wrote textbooks. “Poetry” (poetry) is a piece of writing that expresses certain ideas and emotions, usually with lines of text, one after the other. “Poetry” is different from “prose” (prose), which are sentences that are put together in paragraphs. That’s a very rough definition of “poetry” versus “prose,” but I think you understand the difference. Poetry was and still is often sung. The words of a song, what we call the “lyrics” of the song, are a form of poetry. Well, Longfellow wasn’t writing any songs, but he was writing poetry. He was also writing textbooks – books that were used for schools and other kinds of essays.
In 1831, he married a woman by the name of Mary Potter. In 1835, Longfellow got an offer to teach at a better school than the one he was at – in fact, the best school in the United States, Harvard University. He went to Harvard, and as part of his job he was supposed to learn German. Remember, I said he was very good at languages. So he traveled to Germany to learn German. Although he also studied several other languages when he was there, including Dutch, Danish, Swedish, Finnish, and Icelandic. What a guy.
In 1835, during this trip, after only about, well, less than a year into his trip to Europe, his wife, who was carrying a child – who was pregnant – had a miscarriage. The baby died, and sadly she died as well. This was, of course, a terrible tragedy, a very sad thing for Longfellow to have to experience. He remained in Germany for about a year or so and returned to the U.S. in 1836.
He began teaching at Harvard, and he stayed and taught at Harvard for the next 22 years. As a Harvard professor, Longfellow started publishing more poetry and stories. “To publish” (publish) means to take your writing and make it available for other people to read, usually in a book or in a magazine. In 1839, Longfellow published a collection or group of his poems called Voices of the Night, which was immediately popular with readers. He also published a book called Hyperion.
Hyperion was a novel. It was a piece of prose that told a story, but it was very much based on the real life of Longfellow, especially his travels to Europe. The main character, or the main person in the novel, is called Paul Flemming. Flemming travels to Germany after the death of a close friend, similar to Longfellow going to Germany and having his wife die. Flemming tries to then begin a romantic relationship with an English woman by the name of Mary Ashburton, but he is unsuccessful.
Now Ashburton, the character, is also based on a real person, a woman that Longfellow had met while traveling in Germany, a woman by the name of Fanny Appleton. Longfellow fell in love with Appleton and wanted to marry her. Longfellow began to court, or to get Fanny Appleton interested in him romantically, but Appleton wasn’t interested in Longfellow. In fact, it took almost 7 years for Appleton to say yes to Longfellow and to marry him, which she did in 1843. Together, the two had six children.
Longfellow continued to write and publish collections of poems and stories. In 1847, he published one of his most famous stories. It was called “Evangeline,” and it told the story of two young people in love, who are separated by war. They are reunited at the end of their lives, when the man is dying. “To reunite” (reunite) means to come back together again after being separated.
In 1855, Longfellow wrote perhaps his most famous work, the one that people know him by internationally. It was called “The Song of Hiawatha.” “The Song of Hiawatha” told the story of a Native American, or American Indian, boy named Hiawatha who performs many amazing things in order to bring peace and help to his people. His people are the American Indians who are part of what is called the Ojibwe tribe. A “tribe” (tribe) refers to a group of, in our case, Native Americans. In other countries they may be called Aboriginal people. These were people who were here when the European colonists arrived.
The Native American or American Indian tribe, Ojibwe, was the topic of Longfellow’s work. Longfellow wrote this poem “The Song of Hiawatha” about how this man was able to save his people, but not the woman he loves. The woman he loves is called Minnehaha. The poem is based on Native American stories that were passed on orally from one generation to another. Now interestingly, it was written with a rhythm from a Finnish poem, a poem from Finland, called Kalevala. Remember that Longfellow studied in Europe, including Finnish.
The book was extremely popular, this long “epic,” we would call it, “poem.” It was based, as I said, on Native American stories, but it was an original work by Longfellow. Interestingly enough, I have a connection to this poem. The poem takes place in the area of Minnesota, in the north central part of the U.S., which is where, of course, I grew up. There is a lake Hiawatha in the city next to the one I grew up in, in the city of Minneapolis. I grew up in the capital of Minnesota, St. Paul, which is right next to Minneapolis. We call those two cities the “Twin Cities.”
Anyway, there’s a lake in Minneapolis called Lake Hiawatha, named after the Ojibway hero Hiawatha. Through the lake, there is a small river. It’s called a “creek” (creek). The creek is called Minnehaha Creek. And eventually Minnehaha Creek goes towards the Mississippi River and creates a waterfall very near the river called Minnehaha Falls. Now, Minnehaha Falls was there long before Longfellow wrote his poem. In fact, Longfellow never actually visited Minnehaha Falls, but he had seen photographs of it and decided to use it as part of his poem.
Nowadays you can go and visit Minnehaha Falls, as I have many, many times, and you can see a statue of Hiawatha and his lover, Minnehaha, as based on Longfellow’s epic poem. The other connection to this poem is that I grew up, the house where I grew up from a young child up until my 20s, on a street called West Minnehaha. Longfellow never visited my street or my house, however.
Longfellow continued writing and publishing. In 1861, he suffered another tragedy, another sad event. In July of that year, his wife and mother of his six children, Fanny, accidentally set her dress on fire and was killed. Longfellow tried to save her but was unable to. His hands and face were badly burned because of the fire. The loss, now his second, of his wife left him unable to write. Instead of trying to create poetry, he decided to go back to translation, and he started translating the great Italian Dante and his poem “The Divine Comedy.”
“The Divine Comedy,” as you may know, is a 14th-century epic poem written in an early form of Italian. It’s considered one of the greatest works of western literature. Now, Longfellow was not unfamiliar with the form of an “epic” (epic) poem since “The Song of Hiawatha” is also an epic poem. An epic poem is a long poem that tells a very long story, usually requiring a character with great courage that is able to overcome many difficulties. Another epic poem would be “The Iliad” and “The Odyssey,” attributed to the poet Homer. The translation that Longfellow produced of “The Divine Comedy” was considered one of the best in English of his day.
By 1863, during the American Civil War, Longfellow began to write his own works, or publish his own works again, I should say. He wrote Tales of a Wayside Inn, which contained many poems. A “wayside” (wayside) is a place on the edge or side of a road. An “inn” (inn) is another word for a small hotel or place where you would stay overnight. The Tales of a Wayside Innare similar in form to another famous work of literature, The Canterbury Tales by the English writer Chaucer, another classic piece of literature.
One of the stories in Tales of a Wayside Inn was called “Paul Revere’s Ride.” Now, if you grow up in the United States, in school you learn who Paul Revere was. He was a man who famously rode his horse around Boston or near Boston in the state of Massachusetts, telling people about the beginning of the American Revolution on the 18th of April in 1775.
Longfellow wasn’t writing history, so he invented a few things in this poem, but this poem, which tells the story of Paul Revere’s ride, became instantly popular with people. It was actually first published in a magazine in 1861, in the Atlantic Monthly, which is a magazine that is still around. The poem is often memorized by young children in American schools, or at least parts of it used to be. I remember the first few lines of the poem: “Listen my children, and you shall hear of the midnight ride of Paul Revere.”
Longfellow continued writing until his death in 1882. He continues to be read here in the United States and in other countries. In fact, he was so loved in England that they put a statue of him in what is called the Poet’s Corner section of Westminster Abbey. He was the first American to be honored this way. Over his many years of writing and publishing, Longfellow helped make poetry more popular with American readers. While some critics say that Longfellow is not America’s greatest poet, many would agree that he changed the way that poetry was written and read in the U.S.
Now let’s answer a few of your questions.
Our first question comes from Rino (Rino) in Italy. The question has to do with three words, “area,” “zone,” and “region.” These three words are often used to mean roughly the same thing, but we’ll try to give you examples of when we would usually use one versus the other.
Let’s start with “area” (area). The word “area” can mean simply a part of, or a smaller section of, a larger place. So, if you have, for example, a large house, one area of the house could be on the first floor, another area could be on the second floor, or you could talk about one area of a room – a smaller section of the room. An “area,” then, is typically a smaller part of a larger division.
“Area” can also be used to refer to something that you study. For example, you may be asked, “What is your area of study?” “Well, I study psychology.” “I study sociology.” “I study physics.” Those are “areas of study.” “Area” can also refer to the surface or outside of something, such as on a person’s body.
The word “zone” (zone) can mean the same as an area. Usually it is a section of a town or a city that may be used for a particular purpose. We might talk about the “business zone” of the city – an area of the city where there are many businesses and offices and factories and so forth – or we could talk about the “industrial zone” of a certain state, the part of the state where there are a lot of big companies making things or where there are a lot of people working.
A “zone” could also refer to a part of a state or a country where certain things happen. In California, we have an “earthquake zone.” These are parts of the state where there are likely to be earthquakes, where the Earth suddenly moves, which happens quite frequently here in Los Angeles. We are in an earthquake zone.
Finally, “region” (region) is one section or one part typically of a state or country. We might talk about the southwest United States. That’s a region of the country that includes several different states: New Mexico, Arizona, parts of California, perhaps, Utah, Colorado maybe. Those are all parts of the Southwest. The Northeast is another region of the United States that includes states such as Massachusetts and New York, or New Hampshire, Maine. Those are all in the northeast region of the U.S.
Our next question comes from Andrey (Andrey) in Russia. Andrey wants to know the meaning of an expression, actually a couple of expressions, “come on a voyage with us,” as well as “come along with us.” Let me start with the second expression first. If you say to someone, “Come along (along) with me,” or “with us” if you’re in a group, you mean you want that person to go with you. You want that person to travel somewhere with you.
When I was growing up, at least in Minnesota, people often said “come with” when they were asking other people to go with them to a place. We’d always say, “Can I come with?” And someone would say, “Sure, you can come with.” The idea was that you would come with him or come with her or come with me. “Come along with” is just another way of saying or expressing that same idea.
Now, the expression “Come on a voyage with us” means something similar, except the key idea that would make it different would be “voyage” (voyage). A “voyage” is a very long trip. So, if you are asking someone to come on a voyage with you, you are asking that person to go on a long trip with you, perhaps days or weeks or months. That would be a “voyage.”
We often use “voyage” when we talk about going somewhere on water – across the ocean, for example. Nowadays we often use this word when we’re talking about going into outer space – say, to another planet. There was a famous Star Trek series called Voyager. A “voyager” is a person who goes on a long trip, on a voyage. Although I think the name of the ship was “Voyager” in that Star Trek series.
Finally, Fabio (Fabio) from Brazil wants to know the meaning of the expression “to burn (burn) your bridges (bridges).” “To burn bridges” or “to burn your bridges” means to do something that would end your relationship in such a way that you could never go back to that person or to that company or to that group. Someone who “burns his bridges” is someone who ends their association or relationship with a company or another person in a very bad way, so bad that that other person would never want to be associated or be friends with the person who had burned his bridges.
We often tell people, “Don’t burn your bridges,” meaning don’t end a relationship with a company or with a person in a bad way, because someday you may want to go back to that company or to that person, and if you are very mean or did something bad to end the relationship, you won’t have that opportunity in the future.
I should probably explain that a “bridge” is something that allows you to travel over a river or part of a body of water, such as a lake. So, if you burn your bridges, you can no longer go from, say, one side of the river to the other. That’s where we get the expression “to burn your bridges.” In a war, an army will often burn bridges to either prevent people from crossing a river, or sometimes to prevent their own soldiers from going somewhere when they need to soldiers to stay and fight.
That’s all we have time for on this Café.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
to translate – to express the words and meaning of a piece of writing in a different language
* Gio received a letter from a French company, and since he doesn’t read French, he asked Ahmed to translated it for him.
librarian – a person whose job is to work in a library (a place where books and other documents are kept) and to take care of the items there, helping people find the books and other resources they need
* Let’s ask the librarian where we can find statistics about birth and death rates.
poetry – a piece of writing that uses short lines of text and expresses feelings and ideas using a particular rhythm and rhyme
* One of the most famous pieces of American poetry is by Robert Frost and is called The Road Not Taken.
textbook – a book required when taking a particular course, with information about a topic of study
* Which chapters were we supposed to study in the history textbook for tomorrow’s test?
to publish – to print a book or piece of writing and make it available to the public to read
* When her book was finally published, she had a big party to celebrate and gave copies of it to all of her family members and friends.
to reunite – to come together again after a period of separation; to be together again after a period of time apart
* The siblings were reunited after 10 years of living in different countries.
tribe – a group of families linked together by social, economic, religious, or blood ties, with a common culture and language
* There are many different Native American tribes in the U.S., including the Hopi, the Navajo, and the Iroquois.
tragedy – an event that causes a lot of suffering, sadness, and/or destruction
* The Giarbaldi family suffered a great tragedy when their daughter died in a car accident.
to be burned – to be damaged or destroyed by fire; to be hurt by something very hot
* Keep your hands away from the cooktop if you don’t want to burned.
epic poem – a long poem telling a story about incredible actions requiring a lot of courage
* The The Iliad and The Odyssey are examples of Ancient Greek epic poems.
wayside – the edge of a road; the land next to a road or a path
* Driving through the countryside, we saw an abandoned baby by the wayside and took her to the police station.
area – a part or section within a larger place, outdoors or within a building; a part of the surface of something, such as a person's body or a piece of cloth; a field of activity or study
* We need to make sure that the children remain in the play area and don’t wander off.
zone – an area that is different from other areas in a particular way; one of the sections in a city or town that is used for a particular purpose
* This is a no-parking zone. Any cars parked here will be given a ticket and towed.
region – a large section of a country or of the world that is different or separate from other parts in some way; a place on one’s body; an area that is near a particular part of your body
* This region of the country is known for producing fine wines.
to come along – to go with a person or a group of people to a place; to make progress toward a goal
* We’re going camping next weekend. Why don’t you come along?
to burn bridges – to permanently and unpleasantly end your relationship with a person or organization so that the relationship cannot be repaired or reestablished
* Jake burned bridges when he told his boss she was the worst manager he’d ever work for. He’ll never get another job in this company.
What Insiders Know
The Ozark Folk Center
The Ozark Folk Center is a state park that “showcases” (features; shares with people in a public way) the culture and history of the people who live in and around the Ozark Mountains. It is an “outgrowth” (something that is created from something else) of the Ozark Foothills Crafts Guild, which was created in 1962 as a way to “preserve” (save for the future) the “vanishing” (disappearing) “heritage” (what is learned and passed down from previous generations) of the Ozarks. The Guild opened a “craft center” (a place for creating art and other objects with one’s hands and simple tools) that later became part of the Arkansas state park system.
Today, the mission of the Ozark Folk Center is to “perpetuate” (continue and extend), show, and “promote” (encourage others to become excited about something and/or try something) the Ozark “way of life” (how people live in a particular area or culture). The Center “emphasizes” (gives importance to) its efforts to educate visitors in an “entertaining” (fun; amusing) and enjoyable way.
The Center offers “workshops” (seminars or classes where people learn how to do things by actually doing them, not just watching someone else do it) on crafts and gardening. The Center also features the music of the Ozarks and many “traditional” (related to how things were commonly done in the past) dances that were popular among the “pioneers” (the first white people who lived in the area). It offers many special programs for “seniors” (older people, usually over the age of 65), children, and school groups.
The Center also has a restaurant where visitors can taste the foods of the Ozarks. The restaurant prepares traditional meals using “herbs” (plants with very flavorful leaves used to season foods while cooking) that are grown “on site” (at that location).