= 1875
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 570.
This is English as a Second Language Podcast’s English Café episode 570. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast Store, which has additional courses in business English, in daily English, and in a lot of other exciting topics. Why not like us on Facebook? Go to facebook.com/eslpod.
On this Café, we’re going to talk about a famous person who was famous as a child as well as an adult – Shirley Temple Black. We’re also going to talk about a famous military song called “Taps.” And as always, we’ll answer a few of your questions as well. Let’s get started.
Shirley Temple was born in April of 1928 in Santa Monica, California. Santa Monica is located just next door to the city of Los Angeles. It’s about, oh, a half a mile from my house. I can walk to Santa Monica if I want to. I don’t, of course. Nobody walks in Los Angeles. We all drive, even if it’s just a half a mile. But back to our story – Shirley Temple was born in Santa Monica. Her mother Gertrude had been a dancer, and so she enrolled or put her daughter in a dance class as soon as the daughter could walk.
Young Shirley turned out to be a very good little dancer, and by the time she was only three, she was able to dance much better than children older than she. She also had a certain talent or ability for acting, and beginning in 1931, she started acting in short comedy films that were being made here in Hollywood. It was clear from these films that Temple would eventually become an excellent dancer as well as a singer.
By 1934, just a few years later, Temple had already become a “star” – that is, someone that people recognized, someone who was famous. In 1934, she starred in 10 different movie musicals. A “musical” (musical) is a performance like a play in which the actors sing as well as act. They sing and dance, typically, as well as act. Musicals had been popular in American culture in the theater and became popular as movies as well.
Shirley Temple starred in 10 of these movie musicals including Stand Up and Cheer, Little Miss Marker, and Bright Eyes. In this last movie, Bright Eyes, Temple sang what would become one of her most famous songs, the song that made her in many ways a star – “On the Good Ship Lollipop.”
On the good ship, Lollipop
It’s a sweet trip to the candy shop.
You see, even though that song came out in 1934, I know it. That’s how famous this song was in American popular culture – in the twentieth century, anyway. I’m not sure if kids today know that song, but I remember hearing the song on television because Shirley Temple movies were often shown on Saturday mornings in between some of the animated programs, the cartoons, that children watched. A “lollipop” (lollipop) is a round piece of hard candy that is on the end of a stick. “The Good Ship Lollipop” was a song about a young child going to a candy store.
Interestingly enough, the song is actually about going on an airplane to a candy store, even though the song uses the word “ship.” Airplanes, of course, were a relatively new invention at this time, just as movies were, and people called airplanes “ships.” Nowadays, we use the word “ship” for something that would be in the water, and we would call an airplane, well, a “plane.”
Shirley Temple was so popular in that year of 1934 that she was actually given a special Oscar, a special Academy Award, for being such an outstanding personality in American film. A “personality” usually describes the qualities that a person has, but here it just means a star or a famous person. Audiences, the people who went to watch movies, like I imagine my mother and father back in the 1930s, loved Shirley Temple.
She was very cute. She had blond hair. She had these long curls, curved-shape hair. She could sing. She could dance. She could act, and she was always smiling. She was always happy in her movies. Her movies were very “optimistic,” we might say. “Optimistic” (optimistic) means having a belief that good things will happen in the future. The opposite of “optimistic” is “pessimistic” (pessimistic).
Now, you have to remember that in the 1930s the U.S., as indeed much of the world, was going through the Great Depression – a time of economic problems. Many Americans went to the movies to feel better, to have some happiness in their lives, and that’s what Shirley Temple’s movies provided – an optimistic, smiling experience. Over the next six years, from 1934 to 1940, Shirley Temple continued to make movies, and she quickly became one of the most popular actresses in Hollywood.
Her movies were even more popular than those of other famous actors at that time, including Clark Gable, Bing Crosby, and Joan Crawford. They included The Little Colonel and Curly Top in 1935, and a movie version of Heidi in 1937. People loved Shirley Temple because she was a cute, “talented” (that is, someone with a lot of abilities) person, but as a little girl grows up, she turns into a woman and the appeal that she has as a child actress, of course, will change, and unfortunately for Shirley Temple, that’s what happened.
As she grew older, especially in the 1940s, her movies became less popular, and by 1950 she had basically retired from acting, from being an actress in the movies. “To retire” (retire) means to stop working in a certain kind of job. Normally, when we say “retire,” we are referring to what happens when people get old and stop working for good – that is, for the rest of their life. Shirley Temple didn’t retire from working completely; she just decided to stop acting in movies.
She, of course, continued with her own life. She married a businessman by the name of Charles Black. Temple had actually been married once before, and in a previous marriage had a daughter. Temple and Black were married and stayed married until his death in 2005. Together Temple and Black had a son and a daughter. So Shirley Temple Black in total had three children, if you’re keeping count – that is, if you’re counting her children as you’re listening. Though I’m not sure why you would.
Temple returned to Hollywood one more time in the late 1950s and she starred in two television shows. The first one was called Shirley Temple’s Storybook, and that was on television for two years. The second show, The Shirley Temple Showwas on in 1960. However, neither show was very popular. People remembered Shirley Temple as this cute little girl, and they didn’t want to see her as a grown woman.
After leaving Hollywood for good in 1960, Temple became involved in international politics, which seems like a very strange thing for a young child actress to grow up and do, but that’s what interested Shirley Temple Black. She was an intelligent person and she got involved and interested in international affairs – things that go on between nations, between different countries. Temple decided to run for office in 1967. “To run for office” means to try to get elected to a political position.
In this case, she tried to become a representative in Congress from California, but she lost that election. Nevertheless, she continued to be active in politics. She was a representative of the United States to the United Nations in 1969 and 1970. And in 1974, she was appointed ambassador from the United States to the African nation of Ghana. After she left that job in 1976, she returned to the United States and worked for the then-president, Gerald Ford, for about a year as the Chief of Protocol.
“Protocol” (protocol) describes a system or set of rules about what is the correct way to behave or to act in a certain situation. In this case, it referred to the rules, if you will, of behavior in formal situations for government officials. However, the Chief of Protocol in the United States is actually someone who works for the U.S. Department of State and has the same level of importance as an ambassador.
The Chief of Protocol goes with the president, for example, on all international trips. His or her job is to give advice to the president and the secretary of state about certain diplomatic protocols – that is, how things are supposed to be done in dealing with other countries. The Chief of Protocol is responsible for arranging what a president will do on international trips. So, it’s a very important position. Shirley Temple Black worked in that position for about a year, year and a half, at the end of President Ford’s presidency.
In 1989, Shirley Temple Black was asked again to become an ambassador, this time to the country of Czechoslovakia. She served as ambassador to Czechoslovakia from 1989 to 1992 under President George H. W. Bush. She spent the rest of her life, after she retired as ambassador, working for a variety of international organizations. She was on the board of directors of several organizations. A “board of directors” is basically a group of people who oversee and give advice to a large company or organization.
Temple died here in California in the year 2014 at the age of 85. After her death, people remembered her for her two great accomplishments, first as a child actress – probably the most famous child actress in American film – as well as her accomplished career as a diplomat and someone involved in international politics.
We turn now to a famous military song, “Taps.” “Taps” (Taps) is a song that is usually played on a musical instrument called a “bugle.” A “bugle” (bugle) is a small brass instrument – a small musical instrument made out of the metal brass – that looks like a trumpet, and it’s associated usually with the military.
“Taps” is actually known as what’s called a “military call.” A “call” (call) in this case is an announcement that something is going to happen. “Taps” is used as an announcement that the day has ended and that everyone must turn out the lights, so at the end of a day at a military base or a place where there are soldiers, traditionally “Taps” is played to tell the soldiers they have to turn out their lights and go to bed.
In the beginning this call was called “Extinguish Lights,” which is logical if you understand that the verb “to extinguish” (extinguish) means to cause something to stop burning, usually a fire. In the old days, of course, there was no electricity, and so the only light you had was the light of a lamp or of a candle, which had a flame or a little fire. So, “to extinguish lights” meant to put out or stop the fire from burning. In 1874, however, at least in the U.S. military, this song was changed from “Extinguish Lights” to “Taps.”
Why “Taps”? Well, there are a couple of different theories about the origin of the word “Taps.” One theory is that is related to a Dutch term “tap toe” which referred to the order given to the bars to stop serving beer. We actually call, in English, the instrument you use to get beer out of a large container called a “barrel” or a “keg,” a “tap.” So, “tap toe” meant “close the taps” – that is, stop serving beer so the soldiers can go back home and sleep. Some say that the word “tattoo” in English is also related to this same Dutch expression.
Another theory of the origin of the word “Taps” goes back to before the American Civil War – that is, before 1861 – when in addition to blowing the bugle to indicate extinguish lights or extinguish the flames of the candles there was also a noise made on a small drum. Now, to take what is called a “drumstick,” a long piece of wood, and hit it against a drum is “to tap” the drum. So, you can see the connection or the possible connection there. The drummer used to tap the drum, and therefore the name of the song was changed to “Taps.”
Well, whatever the actual reason why “Taps” is called “Taps,” it was used traditionally to tell soldiers to leave the bars, turn the lights off, and go to bed. The version of “Taps” that we know today in the United States was written in the Civil War in 1862 by General Daniel Adams Butterfield and his bugle player, Oliver Norton. Before 1862, the version of “Taps” that the U.S. Army used was taken from the French military.
Butterfield wanted to make the musical call a little more casual, not quite as formal as the French version they had been using. So, he adapted or changed the call that the army was using, and with his bugler’s help made up a new call that eventually became known in the United States as “Taps.” People in other sections of the army heard the new version of this call and they began to use it themselves, and by the end of the Civil War, it became the official army bugle call for “extinguish lights.”
It also, interestingly enough, became the call or the music that was played at the end of a military funeral, when someone died and was buried. In fact, “Taps” was played at the end of the funeral of one of the most powerful generals in the losing side of the American Civil War, the Confederacy, General Stonewall Jackson. There are no words traditionally to “Taps.” It’s not a song. It’s a piece of music that is signaling or giving a message to the soldiers either to go home and go to bed, or as a way of honoring someone who has died who was in the military.
Today “Taps” is still played at the end of each day in military installations, places that have soldiers, to let people know that the day is over. It is also played at the end of military funerals. Interestingly, “Taps” is also played when the American flag is lowered from the top of a flagpole to the bottom in a non-military, or what we would call a “civilian,” event. Let’s listen, then, briefly to “Taps,” played by – who else – a member of the U.S. Army. This is First Sergeant Daniel Shannon of the 101st Airborne Division of the army.
[“Taps” plays]
Now let’s answer some of the questions you have sent to us.
Our first question comes from Robson (Robson) in Brazil. Robson wants to know the difference between “report” and “paper,” especially when we’re talking about school or school assignments – things that students have to do.
Both “report” and “paper” could refer to the same thing. A teacher tells the students they have to go home and write a long document about a certain topic. It could be two pages. It could be 20 pages. The students then have to go home or go to the library and look up, or investigate, information and then write a “paper” or a “report.” So, in many cases it means the same thing. However, there are some slight differences in other contexts.
A “report” could also be something that is done in a business setting. For example, if I am working for someone who wants to get a lot of detailed information about a certain topic, the person may tell me “to write a report.” That could be 10 pages. It could be 100 pages. That report would contain specific information about a certain topic or groups of topics.
The word “paper” (paper) can also mean a couple of different things. It can mean, as I mentioned previously, an essay or a piece of writing that is done for a school assignment – something that you have to do as part of a school class. “Paper” as a noun can also refer just to a piece of paper, a sheet of paper that has information on it. “Paper,” finally, could also refer to an official document often used to prove something. A lawyer might give you “divorce papers.” These would be official documents related to the end of your marriage. One hopes that that wouldn’t be a surprise if you received them.
I should also mention that a “report,” although normally we think of it as being written down, could in some situations be “verbal” – that is, someone could give a report to a group of people or even in a class give a report standing up and talking to the entire group of students. So, we sometimes distinguish between a “written report” and an “oral (oral) report.” An “oral report” is when you stand up and talk. A “written report,” of course, is when you write things down on a piece of paper. Although nowadays you could just write them on your computer and send them to your teacher via email.
Our next question comes from Kadhafi (Kadhafi). The question has to do with two words common in the business world, “internship” and “externship.” An “internship” (internship) is when usually a student or recent college graduate goes to work in a job for a short period of time to get experience in that kind of work. An “internship” could be a couple of months during the summertime. It could be even longer. It could be up to a year or more during the college career of the student or just after the college student graduates, finishes his studies.
Some internships are paid (that is, the person gets money for working) sometimes they are unpaid – the person works at the company just to get the experience. Young people, of course, don’t have a lot of work experience, and internships are often good ways for people to get experience in a certain kind of work. Many companies also use internships to decide on whom they want to hire – to whom they want to give a regular, full-time paid position to. The person who works in an internship is called, of course, an “intern.”
The term “externship” (externship) is much less common. An “externship” is actually very similar to an “internship,” and many people don’t even use this term “externship,” but there are apparently some differences. An “extern” – a person who works in an externship – usually works for a much shorter period of time. Sometimes an “externship” can be just one day or one week, whereas an “internship” is usually at least a month and often several months long.
An “extern” also differs from an “intern” in that, in many cases, the “extern” doesn’t really do anything at the job, but is simply watching someone else do his or her job – what we would call “job shadowing.” “To shadow” (shadow) is to go behind someone else or to be very close to someone else, observing what that person is doing. “Externships” are almost always unpaid, whereas “internships” can be paid or unpaid.
Finally, Ricardo (Ricardo) from Portugal wants to know the meaning of the verb “to march” (march). Ricardo came across or saw the sentence “He marched her up in front of the class.” “To march” someone means to take someone, often by the hand or by the arm, and lead them up to a certain place, perhaps because you are angry with that person and want the person to leave or because you want to discipline someone or somehow punish another person.
If your mother marched you out of the door, you can imagine that your mother wasn’t very happy with you. She took you by the arm or she put her hand on your back and she basically made you walk out the door. Perhaps you were doing something wrong. I don’t know. This never happened to me because I was an angel when I was a young child. Yeah, I never did anything wrong. Well, that’s what I remember anyway.
I’ve been giving you the definition of “to march” when it’s used with a direct object after it, such as a person: “I marched him out the door.” However, the verb can also be used to talk about a group of people all walking in the same direction and in the same manner.
We sometimes think of groups of soldiers, people in the military, as “marching,” especially in a formal parade, in a formal demonstration of the, perhaps, power of an army. We’ve all seen on television, or perhaps have witnessed in a parade, a group of people marching. Everyone is in a straight line and everyone is walking in the same way. That’s also another definition of the verb “to march.”
“To march” as a verb can also be used to describe a group of people who are walking, but not in an organized way but rather as a way of protesting something, as a way of complaining publicly about something. A large group may not like a certain politician, and so they will have a “march” in the capital of the country where everyone will walk through the streets with some signs and yelling certain things about the politicians or about the government. That’s also a possible use of the verb “to march.”
The noun “march” can describe that entire event of protesters walking on the streets shouting and holding signs. I’ve never been to a march myself. I have tweeted my complaints, however, about politics. I’m not sure if that’s the same thing.
In any case, if you have a question or comment, you don’t have to march all the way over here to Los Angeles. You can just email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
musical – a performance where actors sing and dance, as well as speak lines of dialogue
* The musical The Sound of Music is often shown on television in December around the holiday season.
personality – the set of qualities and ways of behaving that makes a person different from other people
* She has a very warm and kind personality so everyone immediately feels comfortable around her.
optimistic – having a feeling or belief that good things will happen in the future
* Even though Juan has had some bad luck recently, he is optimistic that things would soon get better.
to retire – to leave one’s a job or end one’s career because one has reached a certain age when one is expected to stop working
* Elisabeth is excited to retire so she will have more time to spend with her grandchildren.
international – involving two or more countries
* Ling and Dex are excited about their international trip to Central and South America.
ambassador – the highest-ranking or most powerful person representing one’s own government while living in another country
* The ambassador welcomed the government ministers at a formal reception.
protocol – a system of rules about what is required and the correct way to behave in a formal situation, especially involving government officials
* According to protocol, when government officials meet, the most senior official sits at the head of the table.
board of directors – a group of people asked to oversee and give advice to a company or organization about its activities
* The board of directors will meet this week to consider a proposal to merge with another company.
bugle – a small brass instrument that looks like a trumpet, typically used in the military
* Soldiers listened for the bugle to signal dinner.
call – an announcement that something is going to happen or is happening
* The call went out signaling an emergency so everyone got out of bed, got dressed, and ran to the main office to see if they could help.
to extinguish – to cause something to stop burning, usually a fire
* The fire fighters extinguished the fire in the apartment building before it could do any major damage.
to adapt – to change something so that it works better for a particular purpose
* How can these old textbooks be adapted to reflect current knowledge?
paper – essay; a piece of writing, usually on an academic or school topic; a piece of writing that is done for a class at school or in college
* The professor assigned a paper comparing the philosophical difference between Socrates and Aristotle.
report – a detailed piece of writing based on research done about a particular topic, either submitted in writing or given orally, usually done for a class in school or in college
* Each student is supposed to select an animal and write a two-page report about it.
internship – a paid or unpaid short-term work experience in a student’s or recent graduate’s field of study intended to help them get a job in the field
* Julia did a one-semester internship with an engineering firm and was offered a job when she graduated.
externship – an unpaid short-term experience in a private business, allowing a student or recent graduate to learn about a particular job or field of work
* Lorenzo didn’t know if he preferred to work in set design in theater or in dance, so he did two separate one-week externships to find out more about each one.
to march (someone) – to force a person to walk somewhere, usually walking beside them, guiding them to a specific place
* Mom marched Denzel to his dirty and messy room and told him to clean it.
What Insiders Know
Kennedy Center Honors
The Kennedy Center, named after former president John F. Kennedy, is a well known “performing arts center” (a place where there are many music, theater, and dance performances) in Washington, DC with approximately 2,000 performances “annually” (each year). Each year since 1978, the “Board of Trustees” (board of directors; top management of an institution or nonprofit organization) has “honored” (given recognition and admiration to) people in recognition of their “lifetime contributions (the important things that one has done over an entire career) to American culture.
Anyone can “nominate” (suggests a name) someone for the award. A “committee” (a group with the responsibility of making a decision or completing a project) selects the nominees who best “exemplify” (present an example of the best of something) excellence in music, dance, theater, opera, motion pictures, or television. “To date” (so far), more than 200 people have received the Kennedy Center Honors. Most of the awards recognize individuals, but sometimes groups and even married couples are the award recipients. In recent years, award winners have included movie filmmaker George Lucas, actor Tom Hanks, and signer Billy Joel.
The Kennedy Center Honors are awarded at an “elaborate” (fancy and detailed) weekend-long event in December. People may attend only if they have been invited. Usually, but not always, the U.S. president attends. The ceremony includes a “reception” (formal party) at the White House. Unlike the Academy Awards and many other award shows, the Kennedy Center Honors are not “aired” (shown) on television as a “live performance” (shown on television as something happens), but is edited and shown on television after the event.