


= Sex.And.The.City s02-10
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../+ 美国高中历史教材 American History ： From Pre-Columbian to the New Millennium/myAdocCss.css

'''

♪ They say it's spring ♪ +
♪ This feeling Light as a feather ♪ +
♪ They say this thing ♪ +
♪ This magic we share together ♪ +
♪ Came with the weather too ♪ +
Here are some things I love about New York. +
That week in spring when it's warm, but not hot, +
and the trees are just beginning to bloom. +
Men in suits. +
Three papers and 12 gossip columns. +
It's easy for me to say, "I love you, New York." +
It's not so easy to say, "I love you, Mr. Big." +
The first time I realized I actually loved Big +
was over toast and coffee one morning. +
What? +
You got... +
Huh? Oh. +
Thanks, honey. +
What? +
Nothing. +
The first time I actually felt like saying it +
was the night he took me to the ballet. +
And he hates the ballet. +
I don't want to disappoint you, +
but I think a couple of those dancers had on wires. +
-They were not on wires. -Oh, yeah. +
On a couple of those big leaps I saw the wires. +
You know what? +
What? +
I love your hair like that. +
Cut it out. +
And then there was the time I never expected to say it. +
Last Friday night at approximately 7:20 p.m... +
Yuck. +
...Big was picking me up to take me out to dinner. +
Hey. Hi, I just have to change my shoes. +
Well, hurry up, we don't want to be late. +
If we grab a cab on Madison, we can be there in five minutes. +
Okay. Okay. +
Here. +
Well, what's this for? +
Oh, I just saw it and thought of you. +
It was just... wrong. +
It was wrong. +
I didn't know what to say except... +
I love you. +
You told Big, "I love you," +
because he gave you that? +
What did you think it was, a large diamond duck ring? +
I think my mother has one of these +
in the shape of a squirrel. +
Note, I did not say I love the purse. +
And then what did he say? +
Well, he just sort of reacted stunned for a moment +
and then he said... +
Well... +
you're welcome. +
I'll just wait for you outside. +
Well, maybe he thought you said, "I love it." +
No, it was a very deliberate and distinct "you." +
So he just sort of pretended like you didn't say it? +
Yeah, sort of. But we both know I did. +
So, now I've laid down the gauntlet. +
He either has to say "I love you" back, +
or I guess I'm gonna have to break up with him. +
Well, how long are you gonna give him? +
Well, I didn't put an expiration date on the sentiment. +
But I figure it's got the shelf life of a dairy product. +
It's gonna start to curdle in about a week. +
You know, it's so interesting. +
You can tell a man, "I hate you," +
you have the best sex of your life. +
But tell him, "I love you," +
you'll probably never see him again. +
Well, that's just very comforting right now. +
Wait a minute. Time out. +
Did you ever think that at this very moment +
the man might be trying to find his own way to tell Carrie +
that he loves her? +
Listening to Miranda wax optimistic about love +
was more disorienting than a heat wave in February. +
- +
No. +
But it seemed that Miranda, +
formerly love's greatest skeptic, +
had recently experienced a romantic epiphany. +
Go grab us a seat outside and I'll meet you out there. +
Will you let me pay this time? +
No, no, no, your money's no good here. +
Go grab... grab us a bench. +
All right. +
How much? +
$5.90. -Ow! +
She was dating a bartender who worshiped her. +
And Miranda was so crazy about him in return +
that she let him take her out to dinner. +
But only to places she knew he could afford. +
Mmm! +
Best slices in the city, don't you think? +
Mmm. +
So... +
Saturday my firm is having its annual dinner thing. +
And I was wondering if you think that maybe the bar +
could spare you for a night, you could be my date. +
I warn you, it's going to be totally boring. +
It's not gonna be boring if I'm there with you. +
You probably should wear a suit. +
Oh! +
So it's gonna be a big fancy affair. +
You do have a suit, right? +
Sure I do. +
It's really nice. +
It's gold. +
It's gold? +
Yeah, you know, um... +
corduroy. +
What's wrong with corduroy? +
I don't have enough time to tell you what's wrong with corduroy. +
For the first time, +
Steve took Miranda back to his place. +
So... +
this is your apartment. +
Yeah. +
You like? +
It's sweet. +
I modeled it after De Niro's place in Taxi Driver . +
I'm kidding! +
Yeah, I... +
It's cheap. +
And it's near the bar. +
And you never have to come here again. +
That evening, Miranda experienced her first pangs of yuppie guilt. +
A lot of wonderful artists worked as bartenders for years. +
That doesn't mean he won't be making money someday. +
He's not an artist slash bartender. +
He's just happy being a bartender, period. +
No aspirations beyond shaking the cocktails +
and refilling the peanut bowls. +
How's he in bed? +
There are no words. +
Sounds like a dream relationship to me. +
Yeah, he can make you cum +
and then he can make you a Cosmopolitan. +
Honestly, I don't know how you can get serious with a guy +
whose entire future is based on tips. +
Wait a minute. +
Rich men date not so rich women all the time. +
I mean, come on, look at me and Big. +
It's not about money, it's about compatibility. +
Yeah, but it's normal for the guy to have more money. +
Oh, c'mon. -God. +
I know lots of women who make more money than their husbands. +
You're all missing my point. +
None of this matters to me. +
I just don't want it to matter to him. +
It's like when single men have a lot of money +
it works to their advantage. +
But when a single woman has money +
it's a problem you have to deal with. +
It's ridiculous. +
I want to enjoy my success, +
not apologize for it. +
Bravo, honey. Bravo. +
But you're talking about more than a difference in income. +
You're talking about a difference in background and education. +
This guy is working class. +
Working class? +
Yeah. -It's the millennium, sweetie. +
We don't say things like "working class" anymore. +
But you're trying to pretend that we live in +
a classless society, and we don't. +
Okay, Marie Antoinette, we get the picture. +
Thank you. +
You know, she's right. +
I'm dating a guy right now, and he's got an actual servant. +
What? +
-Really? -Yeah. +
It seems that Samantha +
was dating Harvey Terkell, +
a real estate investor +
who had just made a killing in the market +
turning Chelsea sweatshops into luxury co-ops +
for the upwardly trendy. +
Sum is a fantastic cook. +
You won't eat better Thai food in Bangkok. +
More cellophane noodles, Mr. Harvey? +
Yes, please. +
You like spicy like Mr. Harvey, miss? +
I love spicy. +
Enjoy. +
Isn't she the best? +
I tell you, I could not live without her. +
I wondered, was New York really any different from New Delhi? +
Had our class system been replaced by a caste system? +
And if so, can we date outside our caste? +
That night, Big took me out for a romantic dinner. +
I could smell it coming, +
the way you can smell a thunderstorm +
right before it hits. +
A mere two days after I had said, "I love you," +
Big had found his own way to say I love you to me. +
You're gonna love this. +
It's from a small winery in the heart of Tuscany. +
Mmm. +
Delicioso. +
I rented a villa there one summer with the ex. +
It was incredible. +
I've always wanted to go back with someone I actually liked. +
Listen... there's something I've been meaning to tell you +
ever since the night I gave you the purse. +
Yeah? +
You can take it back if you don't like it. +
That became the first night I wanted to tell Big, +
"I hate you." +
The next afternoon, Charlotte made the acquaintance +
of a member of the very highest caste. +
A caste that, from coast to coast, rich and poor, +
everyone deferred to and honored without question... +
the movie star. +
Hi. I'm Charlotte York, +
I'm the director of the gallery. +
Hi. Wylie Ford. +
Yeah. I know. +
How much for this piece? +
The fire extinguisher? +
Oh, no, no, no. +
That's a real fire extinguisher. +
You know, like for the gallery +
in case there's a fire. +
I guess I'm a total idiot. +
No, no, it happens all the time. +
You can have it. Take it. +
You can say you got it here at the gallery. +
And people will probably think it's a Jeff Koons. +
You are adorable. +
What do you think about closing up +
for the rest of the afternoon? +
Man, Charlene, you are so hot. +
I can't wait to get you to bed. +
Um... +
Charlotte. +
My name is Charlotte. +
Oh. I prefer Charlene. +
Okay. +
Oh, man, this champagne is running through me. +
Yo, bud, pull over, I need to take a leak. +
Sit tight, beautiful. +
Okay. +
Hello? +
You'll never believe where I am. +
I'm in the back of a limo about to go have sex with Wylie Ford. +
Where is he now? +
He's taking a leak out in the alley. +
Isn't that cute? +
Yeah, it's adorable. Now, Charlotte, +
listen to me. +
Get out of there immediately. +
All my rules just went right out the window. +
It's like he wants me. +
And I have to obey. +
Oh, he's zipping up, I gotta go. +
Hey, hey. -Hey. +
While Charlotte began to enjoy the perks of celebrity, +
Samantha discovered that Harvey Terkell +
came with some nice perks of his own. +
Now, you stay in bed as long as you want. +
And Sum will make you breakfast. +
Oh, that's really not necessary. +
What? No, no, no. +
Wait, please. She loves it. +
Do you like fresh orange or grapefruit? +
Hmm. Orange. +
-Orange. Eggs? +
-Coddled. +
Coming right up. +
I'll call you. +
Mm-hmm. +
While Samantha didn't believe in having servants, +
she realized she had no problem dating a man who did. +
She knew it might take some adjusting, +
but she could get used to this. +
Oh, bye, Sum. +
Now, take good care of Samantha. +
-Bye, bye, Mr. Harvey. -Oh, yes. +
Okay. +
Okay, lazy bones, out of bed. +
Excuse me? +
Up, up, must wash sheets. +
Okay. +
Should I have my breakfast in the dining room, or... +
Breakfast? I got no time to make breakfast. +
Got a lot of work to do around here. +
It was then that Samantha realized +
that Sum was not so servile after all. +
That afternoon, during her lunch break, +
Miranda took Steve shopping. +
-Thank you. -You're welcome. +
What do you think? +
I think it's kind of frightening how good I look. +
It's a beautiful suit. +
I think we should take it. +
Could you do a cuff with a nice little break? +
Will these be the shoes? +
I think we should take the shoes. +
Don't you think we should take the shoes? +
I guess we're taking the shoes. +
Uh-huh. Yeah. Just like that. +
Jesus. +
Eighteen hundred bucks. +
I guess I better not spill anything. +
Don't worry. It's my treat. +
What? +
I invited you to this thing, +
I want to pay for the suit. +
No way, you're not buying me a suit. +
But I wanted to do this for you. +
Then I start to think of you like my mother. +
And that can get a little weird for me. +
Sorry, sir, it was declined. +
Would you like to try another one? +
Why don't you try one of mine? +
No, no, no. How about this? +
Let's try $800 on the card, I'll write you a check for $1,000, +
and I'll give you the rest in cash. +
Steve, forget it. It's too expensive. +
Would you just let me buy the fucking suit? +
That Saturday, Big took me to a cocktail party +
at the home of Serena Bush. +
Great purse, fabulous. +
Careful. +
White rugs. +
An Upper East Side hostess +
famous for her husband's money +
and a close personal friendship with Tina Brown. +
I used to know her ten years ago +
when she was famous for her father's money +
and a close personal friendship with her drug dealer. +
Oh, God, I hate Park Avenue. +
It's like being in a foreign country. +
Just think of me as your passport, baby. +
As we walked through the room +
of women clutching their bejeweled swan kitten +
and asparagus purses, +
I realized, to my horror, +
that not only did Big not love me, +
he had absolutely no idea who I was. +
Can I get you a drink? +
Yeah, Tanqueray and tonic. +
Carrie, a drink? +
Oh, red wine please. +
I'm sorry, Miss Bush doesn't serve any brown food or drink. +
Can I get you something clear? +
Uh... yeah. +
Vodka on the rocks. +
No brown food? +
I think we've just encountered a mutant strain +
of Upper East Side anal. +
She's a little strange. +
I've known her for years. She's okay. +
Oh, yeah, I'm sure she's fabulous +
until you spill something. +
It's like she's consciously trying +
to cultivate an eccentricity so people won't notice +
that she's completely devoid of personality. +
Well, don't be a bitch. +
I'm not being a bitch, I'm just being myself. +
You're being a little bit of a bitch. +
Sweetheart. +
-How are you? -Hey! +
It's been forever. +
Thank you for having us. +
Serena, you know Carrie. +
Yes. +
Hey. +
Uh, darling... +
can't smoke in here. +
No, no. Terrace. +
Then that's where I'll be. +
And just like that, I was cast out of the fancy party. +
That same evening, Charlotte found herself the newest member +
of Wylie Ford's entourage. +
When did marijuana become legal in restaurants? +
It didn't. +
-Here. -Oh, no, thank you. +
I don't smoke pot. +
-You do now. +
You know... +
Sum was very rude to me the other morning. +
She practically threw me out of bed. +
No, no, no. +
You must have misunderstood. +
Her English isn't really that good. +
Shh, shh. +
More asparagus, miss? +
It was then Samantha realized she wasn't so dim, that Sum. +
That night I realized that relationships had a caste system of their own. +
There's the person who says I love you. +
And there's the person who never responds. +
Carrie. +
Hey. +
Jeremiah. +
What are you doing here? +
Purveying the beverages. +
-Just snuck out here to smoke, actually. -Ah, good. +
Are you friends with these people? +
Oh, God, no. No. +
Yeah. A little uptight. +
What's with the no brown food deal? +
Whatever. +
Jeremiah was a famous downtown performance artist +
who was best known uptown as, +
"Hey kid, let me have another scotch and soda." +
We had engaged in a mild flirtation for years. +
So, who are you here with? +
Oh, some guy. +
Hey. I just got a new tattoo, you want to see it? +
-Yeah. -Yeah? +
Sure. +
Is that real? +
Yeah, it's real. +
Wowsa. +
How far down does that go? +
Pretty far. +
Check it out. +
Oh. +
Holy moly. +
-Ahem. -Shit. +
Excuse me. +
Ah, shit. +
Uh... +
Were you really out there giving the caterer a blow job? +
First of all, he's not a caterer. +
He's a very well-known performance artist. +
Oh! +
Well, that didn't answer my question. +
Because it was offensive. +
Well, whatever you were doing, please stop. +
You're embarrassing me. +
I'm embarrassing you? +
Well, maybe if you'd join me on the terrace like a gentleman +
we wouldn't be standing here having this conversation. +
Let's just go. +
No, you go, I'm having a good time. +
And across town, Miranda was late for the firm dinner. +
Okay. +
Why are you dressed like that? +
I returned the suit. +
Frankly, I couldn't afford it. +
Then why didn't you let me pay for it? +
Miranda, you need to be with a guy who's more on your level. +
Steve. +
Being in that store with you, +
I didn't feel good about myself. +
Look, I think you're an incredible lady. +
You want to break up with me over a suit? +
Fuck the suit. +
It's not just the suit. +
There's always gonna be things out of my reach. +
So I'm being punished for being successful. +
That's not how I mean it. +
Got it. +
Well... +
thanks for the info and standing me up. +
And it's been nice knowing you. +
An hour later, +
adrift in a sea of Italian wool crepe, +
Miranda wondered what was really so wrong with corduroy anyway. +
In the space of one evening, +
Charlotte had gone from girlfriend to groupie. +
Who had the rum and Coke? +
Listen... Charlene. +
I want you to do something for me. +
I want you to go to the ladies' room, +
stick your finger in your pussy, come back, and let me smell it. +
I don't think so. +
-Excuse me. -Charlene? +
Charlotte realized another moment at the top +
and she would have become an untouchable. +
♪ Jeremiah was a bullfrog ♪ +
♪ Bah, bah, bah ♪ +
♪ Was a good friend of mine ♪ +
♪ Bah, bah, bah ♪ +
♪ I never understood A single word he said ♪ +
♪ But I helped him... ♪ +
After Jeremiah got fired, +
we celebrated downtown +
with a couple of pitchers of margaritas. +
♪ Joy to the world ♪ +
Yeah! +
♪ All the boys and girls ♪ +
♪ Joy to... ♪ +
♪ Joy to the fishes In the deep blue sea ♪ +
I don't live here. Whoa. Whoa! +
♪ Joy to you and me ♪ +
That was the last thing I could remember that night. +
♪ If I were the king of the world ♪ +
-You just relax. -I will. +
I'm gonna go grab a shower. +
Oh. +
Excuse me. +
Nasty. +
Nasty girl. +
You dirty cock-sucking whore. +
Must wash sheets right away. +
Stop it! Let go. +
You're crazy. Oh! +
What's going on out here? +
Mr. Harvey. +
I'm so sorry. +
I just tried to wash the sheets, but that lady hit me. +
Oh, come on! +
How dare you treat Sum that way. +
Let me explain. +
No! +
There's no explanation. +
Just get out of here. +
Samantha realized that there was only room +
for one woman in Harvey's life. +
Shh, shh. +
Oh, Jesus. +
Hello? +
Listen... +
I know what you're really pissed off about. +
But it's just something I've gotta do in my own time. +
Okay? +
Well, I fucking love you. +
All right? You know I do. +
Hey, good morning. +
It's just a tough thing for me to say +
because it always seems to get me in trouble when I say it. +
Okay? +
Okay. +
Are we okay? +
We're great. +
Hey, I love you too. +
I'll call you later, okay? +
Did we? +
Definitely not. +
I didn't think so. +
I felt like I was the lowest of the low. +
But I never told Mr. Big. +
I figured everything before "I love you" +
just doesn't count. +
欲望城市 +
（性爱专家凯莉布雷萧） +
阶级制度 +
我喜爱纽约的几件事如下 +
春季的暖和天气，不冷也不热 正要萌芽开花的树 +
穿西装的男人 三份报纸以及12个八卦专栏 +
“我爱你，纽约” 这句话很容易说出口 +
“我爱你，大人物” 这句话却很难 +
我第一次发现 自己真的爱大人物 +
是在某个早上 吃面包、喝咖啡的时候 +
怎么了？ +
谢了，亲爱的 +
-怎么了？ -没事 +
我第一次想对他说“我爱你” 是他带我去看芭蕾舞时 +
而他讨厌芭蕾舞 +
我不想扫你的兴 +
但是有几个舞者吊钢丝 +
他们没有吊钢丝 +
在做一些跳跃动作时我看见了 +
你知道吗？ +
我爱…你乱七八糟的头发 +
别闹了 +
然而我从未预期说出口的时机 却突然来临 +
上周五晚上，大约七点二十分 +
大人物来接我出去晚餐 +
-我只要换双鞋就好了 -动作快，迟到可不好 +
如果搭计程车 五分钟之内就可以到 +
送给你的 +
-为什么？ -我看到它便想起了你 +
这…就是不对劲 +
我不知该说什么，只好说… +
我爱你 +
你因为这玩意儿 对他说你爱他？ +
你以为这是个钻石鸭戒指吗？ +
我妈有一个松鼠形状的 +
-我不是说“我爱钱包” -他说什么？ +
他只是反应有点吃惊 然后说… +
不客气，我在外面等你 +
也许他以为你说的是 “我爱钱包” +
不，我刻意说清楚是“你” +
所以他假装你没说？ +
但我们都知道我说了 现在我已经摊牌 +
如果他不回应“我爱你” 我就得跟他分手 +
-你要给他多久时间？ -我没有设定有效期限 +
不过我想感情将会在一周内 开始凝结 +
跟男人说“我恨你” 你将会享受这辈子最棒的性爱 +
跟他说“我爱你” 却很可能再也见不到他 +
-现在说这话还真令人欣慰 -等等 +
你们有没有想过也许这男人 正试着用自己的方式 +
告诉凯莉他爱她？ +
米兰达对于爱情的乐观态度 +
比二月的热浪更令人困惑 +
但从前最大的 爱情怀疑论者米兰达 +
已亲身体验浪漫的美妙 +
去外面找位子 +
-这次让我付帐好吗？ -你的钱在这儿不管用 +
-多少钱？ -五块九 +
她正和一个崇拜她的酒保交往 +
米兰达为他疯狂 她让他带她出去吃晚餐 +
但只去她知道 他负担得起的地方 +
这是纽约最好吃的披萨 +
我的事务所 星期六要举办年度餐会 +
不知道酒吧能不能放你一天假 +
让你当我的男伴 先警告你，那场合非常无聊 +
有我陪你就不无聊 +
你可能得穿西装 +
这是一场盛大豪华的宴会？ +
-你有西装吧？ -当然有，很漂亮，是金色的 +
-金色的？ -对，而且还是灯芯绒的料子 +
灯芯绒有什么不好？ +
说都说不完 +
史蒂夫第一次带米兰达回家 +
这就是你的公寓？ +
-你喜欢吗？ -很别致 +
我模仿罗伯特迪理路在 “计程车司机”中的房子布置 +
我开玩笑的 +
这里租金便宜，离酒吧又近… +
而且你可以永远不必再来 +
当晚，米兰达第一次感到 雅痞的罪恶感 +
许多很棒的艺术家 都当过好几年酒保 +
也许有一天他会赚大钱 +
他不是艺术家型的酒保 他对当酒保乐在其中 +
除了调制鸡尾酒 +
和装满花生碗之外胸无大志 +
-他的床上功夫如何？ -无可挑剔 +
在我听来像是一段理想的恋情 +
他可以让你达到高潮 接着调一杯四海为家给你 +
你怎能对一个未来靠小费 过活的男人认真？ +
慢着，多金的男人 总是跟不怎么有钱的女人交往 +
看看我和大人物 这与金钱无关 +
是因为我们合得来 +
但男人比较有钱才正常 +
拜托 +
很多女人比老公会赚钱 +
你们没听懂我的重点 这对我一点也不重要 +
我不希望他受影响 +
如果单身的男人有钱 这是他们的优势 +
但若是单身的女人有钱 就会出问题 +
这真是太可笑了，我想要享受 事业的成功，而非为此歉疚 +
亲爱的，说得好 +
你说的不只是收入的差异 +
还有出身背景和教育程度 +
-这个男人是劳动阶级 -劳动阶级？ +
现在是千禧年 没有人说“劳动阶级”了 +
你们正假装 我们活在一个无阶级的社会中 +
但并非如此 +
好吧，玛丽皇后 我们明白了，谢谢 +
她说得对 +
我现在交往的对象 事实上就有一个仆人 +
-什么？ -真的吗？ +
莎曼珊正和哈维泰凯尔交往 +
他是个刚从不动产市场 大捞一票的投资者 +
为上流社会赶时髦的人 将工业区变成精品街 +
桑姆是个很棒的厨子，在曼谷 也吃不到这么棒的泰国菜 +
-还要面吗，哈维先生？ -好的 +
你跟哈维先生一样爱吃辣吗？ +
我最爱吃辣了 +
慢用 +
她很棒吧？我不能没有她 +
我纳闷着 纽约和新德里真的有差别吗？ +
社会的阶级制度 是否已被种姓制度取代？ +
若真如此，我们可以 和不同阶级的人交往吗？ +
当晚，大人物带我出去 享用一顿浪漫的晚餐 +
我可以感觉到就是今晚了 如同在暴风雨前察觉得到一样 +
在我说“我爱你”仅仅两天后 +
大人物已找到自己的方式 /对我说“我爱你” +
你一定会喜欢这个 它出自多斯加尼一家小酿酒厂 +
真好喝 +
我曾在那里租了一栋别墅 风景漂亮极了 +
我一直想跟真正心仪的对象 来个旧地重游 +
自从送你那个钱包 我就一直想跟你说一件事 +
如果你不喜欢可以拿去退 +
那是我第一次想对大人物说… +
“我恨你” +
隔天下午 夏绿蒂认识了最高阶级的成员 +
从东岸到西岸，不分富贵贫穷 +
人人都听从尊敬的阶级就是… +
电影明星 +
你好，我是夏绿蒂约克 画廊的经纪人 +
-我是韦利福特 -我知道 +
这幅画多少钱？ +
灭火器？ +
不…这真的是灭火器 +
画廊用的，以防发生火灾 +
-我想我真是个大白痴 -常有这种事 +
你要的话可以拿去 说你在画廊买的 +
别人搞不好会以为 那是杰夫孔斯的作品 +
你真可爱 +
你认为提早打烊怎么样？ +
夏琳，你好性感 我等不及跟你上床 +
是夏绿蒂，我的名字叫夏绿蒂 +
-我比较喜欢叫你夏琳 -好吧 +
我喝太多香槟了 +
靠边停，我要尿尿 +
坐好，美人 +
你绝不会相信我在哪里 +
在一部豪华轿车的后座 即将和韦利福特上床 +
-他现在人呢？ -在小巷子里尿尿 +
听我说，马上离开 +
我所有的原则都飞出窗外了 +
仿佛他想要我而我便得服从 +
他在拉拉练了，我得挂了 +
当夏绿蒂享受著名人的殷勤 +
莎曼珊发现 哈维也提供完善的服务 +
你想在床上待多久都可以 桑姆会为你做早餐 +
真的没有必要 +
拜托，她很乐意 +
-新鲜的柳橙还是葡萄柚？ -柳橙 +
-蛋要如何料理呢？ -半生不熟 +
马上来 +
我再打电话给你 +
她从不考虑请奴仆 +
但跟有奴仆的男人交往 却不成问题 +
经过一番调适，她已经习惯了 +
再见，桑姆，好好照顾莎曼珊 +
再见，哈维先生 +
好了，懒骨头，快起床 +
-什么？ -起来…我得洗床单 +
我应该在饭厅用早餐吗？ +
早餐？我才没空做早餐 +
我有一大堆事要做 +
那时莎曼珊才了解 桑姆并非如此温顺 +
当天下午米兰达利用午餐空档 +
带史蒂夫去买衣服 +
-你觉得怎么样？ -我真是好看得吓人 +
这套西装很漂亮 我认为应该买下来 +
裤管可以翻个边吗？ +
-要配这双鞋吗？ -我想鞋子也应该买下来 +
-应该买这双鞋吗？ -我们要买这双鞋 +
就是那样 +
老天，一千八百块 我想我最好别打翻任何东西 +
-别担心，我来付帐 -什么？ +
-是我邀请你，所以由我出钱 -不，你不能买西装给我 +
但我想买给你 +
这样我会开始觉得你像我妈 +
那感觉很怪 +
抱歉，先生，这张卡被拒绝了 你还想试另一张吗？ +
何不试试我的卡？ +
这样好了，这张卡刷八百块 +
我再开一张一千块的支票 剩下的用现金付 +
-史蒂夫，算了，太贵了 -你就让我买这该死的西装吧 +
星期六大人物带我去参加 在莎莲娜布希家中 +
举行的鸡尾酒派对… +
很美的钱包 +
小心点，这可是白地毯 +
她以丈夫的财富闻名 +
并且和蒂娜布朗交情匪浅 +
十年前我便认识她 当时她因父亲有钱 +
以及和毒贩往来密切而出名 +
我讨厌公园大道 好像到了陌生国度 +
把我当成你的护照吧，宝贝 +
当我们穿过房间 +
满屋都是拿着珠宝包的女人 +
我惊恐地发现 大人物不但不爱我 +
他根本不知道我是谁 +
-需要什么饮料吗？ -坦奎利加奎宁水，你呢？ +
请给我红酒 +
很抱歉，布希女士不供应 任何有颜色的食物或饮料 +
可以换一种透明的饮料吗？ +
那…伏特加酒加冰块 +
不供应有颜色的食物？ +
我们遇到上东城区的突变体了 +
她是有点怪，我认识她 好几年了，她人还不错 +
直到你打翻东西 她似乎刻意培养一种怪癖 +
别人才不会注意到她毫无个性 +
-嘴巴别这么坏 -我没有，我只是说出真心话 +
你嘴巴有点坏 +
亲爱的，你好吗？好久不见 +
谢谢你邀请我们 莎莲娜，你认识凯莉的 +
-是的 -你好 +
亲爱的…这里不能抽烟 +
-阳台可以 -那我过去了 +
就这样，我被逐出豪华派对了 +
夏绿蒂发现自己成了 韦利福特身边的新成员 +
大麻什么时候在餐厅合法了？ +
并没有 +
-来，吸一口 -不，谢了，我不抽大麻 +
你现在抽了 +
桑姆那天早上对我很不礼貌 +
她几乎把我赶下床 +
你一定是误会了 她的英文不太好 +
还要来一点芦笋吗？ +
莎曼珊这才意识到… +
桑姆心机有多重 +
我发现感情中的确有阶级制度 +
有人说“我爱你” +
有人却从不回应 +
-凯莉 -嗨 +
杰瑞米，你在这里做什么？ +
负责送饮料 我只是溜出来抽根烟 +
-你认识这些人吗？ -老天，才不呢 +
有点神经质，不供应 有颜色的食物，什么烂规矩 +
杰瑞米是下城著名的 表演艺术家 +
在上城以“再来一杯 威士忌和汽水”最为人知晓 +
几年前我们曾有过一段情 +
-你跟谁一起来？ -某人 +
我有一个新的刺青，你想看吗 +
-那是真的吗？ -没错 +
那有多下面？ +
很下面，你看 +
好棒 +
糟了 +
抱歉打扰 +
该死 +
你真的在外面 帮那个小弟口交吗？ +
首先，他不是小弟 他是个很有名的表演艺术家 +
-你没回答我的问题 -因为那太侮辱人 +
不管你在做什么，请你停止 +
-你会丢我的脸 -我会丢你的脸？ +
如果你像个绅士一样 陪我到阳台 +
我们就不必站在这里说这些话 +
-我们走吧 -要走你走，我玩得正开心呢 +
而在城市的另一头 米兰达参加晚宴要迟到了 +
你为什么穿这样？ +
我把西装退回去了 +
老实说，我根本买不起 +
那你为什么不让我付钱？ +
米兰达 你得跟和你比较匹配的人交往 +
和你一起在那间店里… +
我觉得不太自在 +
-你是个很棒的人 -你为了一套西装跟我分手？ +
去他的西装 +
不只是西装，总会不停有 超出我能力所及的东西出现 +
我因为事业成功而受惩罚 +
我不是这个意思 +
我懂了 +
谢谢你通知我，放我鸽子 +
很高兴认识你 +
一个小时后，在穿着意大利 羊毛西装的人海中载浮载沉 +
米兰达思考灯芯绒布料 到底有什么不好 +
同一个晚上 夏绿蒂的地位从女朋友… +
变成了跟班 +
谁点兰姆酒和可乐？ +
听着，夏琳 我要你帮我做一件事 +
你去厕所 +
把手指伸进阴道 +
然后回来让我闻一闻 +
我想这样不太好 +
-借过 -夏琳？ +
若在顶端多待一分钟 她恐怕将沦为贱民 +
（杰瑞米是只牛蛙） +
（也是我的好友） +
（他说的话 我一句都听不懂…） +
杰瑞米被开除之后 +
我们到下城 灌了好几壶玛格丽特以兹庆祝 +
（普世欢腾…所有男女…） +
我不住这里 +
那是我当晚记得的最后一件事 +
你只管休息，我去淋个浴 +
你要干嘛？ +
下流的女人 +
你这肮脏、无耻的淫妇 +
得马上洗床单 +
住手，放开，你疯了 +
这里发生什么事了？ +
哈维先生，我很抱歉 +
我只是想洗床单 +
-但小姐却打我 -有没有搞错？ +
你竟敢如此对待桑姆 +
-听我解释 -不必了，没什么好说的 +
给我滚出去 +
莎曼珊终于明白 在哈维的生命中 +
只容得下一个女人 +
老天 +
听着…我知道你在气什么 +
只不过我必须照着我的步调来 +
该死，我爱你 +
行了吗？你心知肚明 +
只是我很难说出口 +
因为每次说了之后 似乎总是惹来麻烦 +
-好吗？ -好 +
我们没事吧？ +
我们很好 +
我也爱你，我晚一点再打给你 +
我们有没有… +
-绝对没有 -我想也是 + 
我觉得自己卑劣到极点 但我从未告诉大人物 +
我想在说“我爱你”之前 一切都不算数 +

