


= Sex.And.The.City s02-11
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../+ 美国高中历史教材 American History ： From Pre-Columbian to the New Millennium/myAdocCss.css

'''

There is nothing more humiliating for a woman +
than a visit to the gynecologist. +
Do you need more Ortho-Novum? +
Unless it's having to tell your gynecologist +
that you don't need to be on the pill anymore. +
Actually, I'm going off it. +
-Are you trying to have a baby? -No! +
No, I... +
guess I sort of jumped the gun +
going on it in the first place, because Steve... +
the guy that I went on it for, +
the first real relationship I've had in years, is over and... +
I don't need a daily reminder that I'm not having sex. +
So... +
that's the story with the pill. And, uh... +
Okay, I'm quiet now. +
Just when Miranda thought she'd hit rock bottom, +
she discovered a new geological layer of humiliation. +
Well, we got your tests back and everything looks fine. +
Great! +
Just one small thing. +
It appears you have a lazy ovary. +
A lazy ovary? +
Yes. Your right ovary has stopped producing eggs. +
Is it possible it's just on strike? +
I know what this is. +
My right ovary has given up hope +
that I will ever get married and have kids. +
It's like working on a case that you know is gonna settle out of court. +
Why bother? +
Well, the left one still believes. +
I'm a biological underachiever. +
And it's ironic because that ovary went to Harvard. +
I have a tilted uterus. +
-So? -So the sperm have to jump +
over that hurdle to get to my egg. +
Yes, but once they get there, there will be an egg. +
I need a new gynecologist. Do you like yours? +
Not right now, no. +
Well, at least she's a woman. +
I tried to go to a man, but it was just too strange. +
Having a guy spend all that time down there, and then you leave +
without an orgasm and a bill. +
Here, you guys, I'm gonna get this. +
You know, +
I don't think these are accepted here. +
Oops! +
I'm spending the night at Big's. +
My God, after all this time, you don't have so much as a drawer there? +
Big is weird about stuff . +
All men are. That's why you have to just stake out some territory. +
Sweetie, it's not a land run, it's a relationship. +
Exactly, talk to him about it. +
With Big, I think it's best to +
walk softly and carry a big purse. +
Yes. She shouldn't leave anything there. +
It's important to remain a creature of mystery. +
What's the big mystery? He knows that she wears underwear. +
I never leave underwear at a guy's place +
because I never see it again. +
What happens to it? +
Nothing, I just never go back. +
Doesn't that get a little expensive? +
Disposing of lingerie every time you sleep with a guy? +
That's why I stopped wearing underwear on dates. +
And that's why I'm never borrowing a dress from you again. +
I once found another woman's underwear in a man's bed. +
-Maybe it was Samantha's! +
You know, once in Steve's bathroom, I found one of those +
hair scrunchies from the '80s. +
I'm not sure what was more disturbing, +
the fact that he had a girlfriend before me +
or the fact that he dated someone who wore a scrunchie. +
Half my music collection is left behind by past boyfriends. +
I always give that stuff back. +
Oh, I don't. I consider it a parting gift. +
Thanks for playing, and here's the latest from Hootie and the Blowfish. +
They're sexual souvenirs. +
Okay, then I want a t-shirt that says, +
"I dated a bartender and all I got was this lousy ovary." +
The next morning at Big's, I started to think... +
If the things we leave behind +
become the archaeological relics of our sexual history, +
I should be able to leave something. +
Ancient man left cave drawings to prove they existed. +
I left a Hair Pro 1200. +
And I didn't stop at that. +
Man may have discovered fire, +
but women discovered how to play with it. +
Charlotte was making history, as well. +
Tired of the Neanderthal she'd been dating, +
she was spending her Saturday night +
with a gay friend who'd catered parties for the gallery, +
dessert chef, Stephan Bodine. +
I had no idea that Betty Buckley was so talented. +
Please, she's the cat's pajamas. +
Why do people say that? +
I have no idea. Maybe because she was in Cats . +
Hey, let's start another one. +
-Like, "She's the dog's tuxedo." Okay. +
Thank you so much for inviting me. +
No, no, no, please, thank you +
for accepting my last-minute invite. +
My friend Don canceled this morning +
and we had had tickets forever. +
Well, you can call me any time. It's just so refreshing +
to go out with a man that I can actually talk to. +
You want to grab a cappuccino? +
Oh, no, I've just got to get on home. +
-Well, you're uptown? -Yeah, and you're... +
Chelsea. +
I'll hail you a cab. +
What? +
Or you could get one yourself. +
Just helps to show a little leg. +
You know, I've tried that, and nothing. +
Thank you, goodnight. +
Goodnight. +
So, what happened? What do you think? +
I am so confused. Is he gay or is he straight? +
Well, it's not that simple anymore. +
The real question is, +
is he a straight gay man? +
Or is he a gay straight man? +
The gay straight man was a new strain of heterosexual male +
spawned in Manhattan as the result of overexposure +
to fashion, exotic cuisine, musical theater, +
and antique furniture. +
Well, hopefully he's a gay straight man. +
Which means he's straight with a lot of great gay qualities. +
Whereas a straight gay guy, +
is just a gay guy who plays sports and won't fuck you. +
He must be a gay straight man +
because he asked Charlotte out for a second date. +
Unless he's a straight gay man in denial. +
But our thing Saturday night wasn't even a date. +
I didn't wash my hair and I wore my glasses. +
Are those recreational? Because this drink isn't doing it for me. +
They're hormones. I'm trying to jump-start my ovary. +
I think my mother's taking those for menopause. +
Why, does she have a tilted uterus too? +
Hey, isn't anybody going to notice my purse? +
-Aw! -Cute! +
Is it new? +
No, but it is quite small and panty-free. +
You left your underwear at Big's. +
Well, no, but I did leave a hairbrush, a hair dryer, +
razors, tampons... +
and eye makeup remover. +
Wow, good for you! +
And something else. +
What? +
For the first time at Big's... +
I did a number two. +
Oh, no! +
No! +
Yes! Now I think it's a good sign +
that I feel comfortable enough with Big to do a number two. +
It is not a good sign. +
It's the end of romance. +
This is a big deal. +
I went through an entire relationship +
never doing that at the guy's place, +
including a weekend in Bermuda where I spent the whole time +
running to the lobby. +
Yeah, it's tough in New York, you know. +
Apartments are small, there's one bathroom. +
You can hear everybody's everything. +
That's why I only date rich men. +
Money means that there's enough space +
to distance yourself from the number two. +
I have never done a number two at a boyfriend's place. +
Honey, you're so uptight, you need to do a number seven. +
Excuse me. +
It's from that guy at the end of the bar. +
Oh, really? +
Oh, my God, it's Dominic. +
Dominic Delmonaco was a publishing magnate, +
and the first and only man Samantha really loved. +
He wined and dined her, +
set the bar for hot sex, +
then dumped her for an Icelandic supermodel named Anka. +
Once on the cover of Fortune, +
he'd fallen to tabloid level due to a messy public divorce. +
I'm just gonna say hello. +
After what he did to you? +
-What did he do? -He broke her heart. +
Imagining Samantha with a broken heart +
was almost more confusing to Charlotte +
than a French kiss from a gay man. +
Ancient history. +
I'm the one with the power now. +
I've evolved past him. +
Hey, beautiful. +
Hiya, handsome. +
Hey! What's this? +
Oh, just a few things you left at my place. +
Oh... +
Thanks. +
It's like I had one too many items +
and I was being kicked out of the relationship express lane. +
What is it about Big's apartment? +
Nothing ever sticks, it's like Teflon for women. +
I meant to leave that stuff at your apartment. +
Why? +
Well... +
For one thing, I don't wake up looking like this. +
I actually need stuff to look like this. +
And it would be nice not to have to +
carry it around all day with me like a nomad. +
It's just a few things. +
And you can leave stuff here. +
I don't want to leave stuff here. +
Well, not a lot of stuff, just like... +
You know, if you want to shave in the morning. +
I shave at the gym. +
Okay, then, I don't know. +
Socks. +
You want me to leave socks here? +
Well, never mind what I want, what do you want? +
I don't know, let's save an hour. +
Why don't you just tell me what I want? +
No, really. In your mind... +
what is the ideal living situation for two people +
in a relationship? +
Exactly what we have. +
And what is that? +
I have my place, +
you have yours. +
We're together when we want to be. +
And we're apart when we want to be. +
Like Woody and Mia. +
Before Soon-Yi. +
Ever since Woody Allen described waving to Mia Farrow across the park, +
single men in Manhattan had yearned +
for that kind of separate togetherness. +
I felt like the last dinosaur. +
Was I the one who needed to adapt? +
Was my view of a relationship extinct? +
I couldn't stop thinking about it. +
This is a city where gay men are so out, they're in. +
Where women are so chronically single, +
ovaries may be the next vestigial organ. +
We can have anything delivered at any hour. +
We can have our dogs walked, our clothes cleaned, +
our food cooked. +
Who needs a husband when you have a doorman? +
Are New Yorkers evolving past relationships? +
Relationships have been on the decline +
since women came out of the cave, looked around, and said, +
"This isn't so hard." +
Okay, so you don't need a man, but do you still want one? +
Oh, honey, I want more than one. +
I can't decide whether you represent our future +
-or our demise. -I am the future. +
Seeing Dominic reminded me of how needy I was and how far I've come. +
We're going out Friday night. +
Oh, sweetie! It took you a year to get over him. +
He treated you like shit. +
Why would you want to go out with him again? +
Because he treated me like shit. +
Okay, I'm leaning towards demise. +
It's called revenge. +
I'm gonna make him want me, +
then right before we do it, +
I'm gonna drop him like he dropped me. +
As long as you got a plan. +
Not only a plan, I have a dress. +
Samantha's revenge fantasy, like all her fantasies, +
was even better live. +
Wow! +
You're more beautiful than ever. +
So successful, and I'm getting gray hair +
and Anka is taking me for everything I've got. +
I read that she got the sailboat. +
Yes, well, we had good times in that boat. +
You and Anka? +
-You and I. -Oh! +
Have I mentioned how... +
unbelievable you look in that dress? +
And since Stephan hadn't come out, +
Charlotte accepted his invitation to stay in. +
Mm... +
That's delicious. +
Grilled portobello pizzas +
topped with fresh basil and Parmigiano-Reggiano cheese. +
Mm! +
It's Martha's recipe. +
Well, I love Martha Stewart. +
She's the dog's tuxedo. +
Oh, look. +
You have these silk place mats I've been eyeing at Bergdorf's. +
You have good taste. +
Well, this is my fantasy kitchen. +
And this is my fantasy. +
Is that dress Cynthia Rowley? +
-Uh-huh. Charlotte wanted to be open-minded, +
but Stephan seemed to be making it as hard as possible. +
Meanwhile, Samantha was making Dominic as hard as possible. +
So, do you want me? +
Oh... +
do I want you. +
This was the moment Samantha had waited years and years for. +
What was another couple hours? +
Hello. +
I've been trying to call you. Were you at Big's? +
Oh, no, I was out shopping. +
My relationship is at a standstill. +
So instead, I'm evolving my look. +
Hey, how did it go with Dominic? +
I slept with him. +
Well, that wasn't part of the plan. +
It's part of the new plan. I wanted to remind him what he was missing. +
I can't believe I thought he was such a great lover. +
I'm better than him now. +
Bye. +
In order to survive two decades of dating in New York, +
Samantha had become a powerful hybrid, +
the ego of a man trapped in the body of a woman. +
Charlotte feared the opposite was true of Stephan. +
She still needed help classifying her find, +
so she brought in a team of experts. +
Uh... Carrie, Stanford, this is Stephan. +
-Hi. Hi. +
-Ciao. Oh! +
You changed your hair. +
Oh, yeah, I just... it's just straightened. +
-Have we met? -Oh, no, no, no. +
I've seen your column. And in that photo, +
your hair is, like, free-flowing and... +
Botticelli-esque. +
It's fabulous either way. +
So... +
Cannolis and cream puffs and tarts, oh my! +
I put a little bit of everything. +
Um... This one's an experiment. +
It's a date tart with a pumpkin custard. +
This is all for us? +
Sweets for my sweet. +
And her freeloading friends. +
My nutritionist will kill me, but somebody hand me a fork. +
-Can you join us? -I'd love to, +
I have got to glaze my wedding cake. +
Get back to me on the tart. +
I find him very attractive. +
Which of course means he's straight. +
Plus, he's obviously choosing to be straight +
because he seems to be head over heels about this one. +
What if he's gay and he doesn't know it yet? +
Honey, we are aware. +
When I was a boy, my father gave me a book +
about the female body to teach me about sex. +
I took one look at it and said, +
"No." +
Well, how is he in bed? +
I don't know, I haven't slept with him yet. +
Really? +
But he wants to. +
It's so not fair. +
All the good ones are straight. +
Even the gay ones. +
Give me a cannoli. +
Are you looking at my forehead? +
No, no! +
That night, Miranda went out with Joseph Adler, +
a labor relations lawyer +
who'd been after her since the firm retreat. +
The lamb is delicious. +
You can look if you want, I've got nothing to hide. +
It's actually starting to fill in. +
Mm-hm. +
She'd refused him twice before +
but since she was down to her last ovary, +
Miranda decided she was in no position to eliminate men +
on the basis of hair plugs. +
I'm telling you, I was practically bald. +
I remember. +
And now I have hair. This is a miracle. +
-Some more bastilla? -Oh, sure. +
You probably think I'm crazy. +
Actually, I was thinking you seem very happy. +
You know, the funny thing is, I never thought that I'd be the kind of guy to get plugs. +
But I've learned that you should never say never. +
I know what you mean. +
There are things that I've been considering lately +
that I never thought I would consider. +
Like what? +
Do you really want to know? +
Sure. +
Well, I recently found out that I have a lazy ovary. +
Which is no big deal. +
It just means I only produce an egg every other month. +
And I'm not even sure that I want kids, but... +
all of a sudden it hit me that if the other ovary shuts down, +
I'm out of business. So... +
I've started taking hormones, +
and now I'm actually considering freezing my eggs. +
Freezing your eggs? +
Yeah, you know, like a fertility savings account. +
I think it would take the pressure off. +
It removes the whole biological clock issue. +
Yeah, but it raises a lot of other issues. +
Such as? +
What is all this reproductive technology doing for us? +
I mean, do we want desperate women having babies at 50? +
Maybe some people aren't supposed to procreate. +
Maybe this is the world's way of weeding out the weak. You see? +
If you ask me, this is a ridiculous abuse of science. +
You have now designer sperm and these simulated wombs. +
Here's a good idea. +
-Why don't we just eliminate men altogether? -Hey! +
I don't need to be lectured about science by a man who's doing crop rotation +
on his forehead. +
Miranda went off the hormones, +
not because of what Joseph said, +
but because she was only 33, +
she still had her left ovary, +
and she wasn't ready to settle out of court. +
Maybe someday there would be eggs in her freezer. +
But not yet. +
Meanwhile, Charlotte decided to stop trying +
to figure out her creature of mystery, +
and just enjoy. +
Cher? +
I love her. +
She's such a survivor. +
Wait. +
I have to ask you something. +
Have you ever been with a man? +
No. +
Have you ever been with a woman? +
I'm sorry, it's just... +
Betty Buckley and... +
Martha Stewart and, and Cynthia Rowley! +
Are you gay? +
Charlotte, +
I'm a 35-year-old pastry chef who lives in Chelsea. +
If I were gay, +
I would be gay. +
You're the one who doesn't want to make love. +
I wouldn't be so sure about that. +
Charlotte was relieved and delighted +
to discover Stephan was definitely straight, +
or at least a gay straight man. +
Frankly, after two orgasms, who the hell cares? +
Oh, God. +
The next morning, it dawned on Samantha +
that her desire for revenge was not as strong as her desire for Dominic. +
You're awake. +
Yes. +
You're so incredibly beautiful. +
God. +
I'm gonna miss you. +
What do you mean? +
Anka and I are giving it another shot. +
It's mostly financial. +
You can't do this to me. +
-I know, I'm sorry. -No. +
No, no, no, no, no! +
I'm supposed to do this to you. +
I had a plan. This is all wrong! +
I should go. +
Get out! +
I said I was going. +
Hey! +
Stop beating me to the punch! +
As she watched history repeat itself, +
Samantha realized she couldn't do what Dominic did, +
because she hadn't evolved past having feelings. +
And in a way, +
that was nice to know. +
-Good morning. -Good morning, sleepy. +
Something smells amazing. +
It's warm cranberry buttermilk scones. +
-Mm! -And lemon curd. +
If I continue dating you, I'm gonna gain ten pounds. +
You'll still be gorgeous. +
-You want some tea? -Yes, please. +
What is that noise? +
-What noise? -It's kind of... it's like a squeaking. +
Oh my God, oh my God. +
It's a mouse. +
-Are you sure? -Yes, it's in that glue trap. +
Where? +
Uh... there. Oh, ew, ew! +
Oh! Oh, my God! +
Its legs are stuck! +
-Ew! Get it out! -Ew, do something. +
-Well, don't kick it to me! -Get it out, get it out! +
-Ah! Will you do something? -It touched my skin! +
It touched my skin! It's coming out that way! +
Ah! Get it away, away! +
Ew! +
Oh my God, oh my God, oh my God... +
At that moment, Charlotte realized her masculine side +
wasn't evolved enough for a man whose feminine side +
was as highly evolved as Stephan's. +
And I spent the night at Big's for the first time +
since my stuff was kicked out of the nest. +
Oh, God. +
Where are you going? +
-Home. -No, nope. +
That's where my hair dryer is. +
I have to dry my hair. +
I'm wearing it straight in case you didn't notice. +
I noticed. +
But I think it looks pretty amazing right now. +
Hey. +
Bring that gorgeous ass back into bed. +
I just have to make sure I didn't leave anything else. +
And suddenly I realized... +
I didn't have to worry about leaving something behind, +
because I was there. +
Okay. +
I'll stay a little longer. +
But I'm leaving this underwear here. +
Is it clean? +
Okay. +
It was a small step for mankind. +
But it was a really big step for Big. +
欲望城市 +
（性爱专家凯莉布雷萧） +
“两性进化论” +
任何事都比不上去看妇产科 更叫人难堪 +
你还需要避孕药吗？ +
除非结果显示你不需要 再服药了 +
-我暂时不想吃 -你想怀孕吗？ +
不，其实是我太操之过急了 +
我的史蒂夫…他是我的前男友 +
我们结束了长达几年的恋情 +
我不需要每天找个东西 来提醒我没有做爱 +
所以我不用吃药了 好了，我闭嘴总行了吧 +
正当米兰达处在谷底时 +
才发现她要面临另一个难堪 +
-你的测试显示一切都很好 -好极了 +
只是有件小事 你的排卵有点迟缓 +
排卵迟缓？ +
你的右卵巢停止制造卵子了 +
它有没有可能是在闹罢工？ +
我的右卵巢已经放弃了希望 认为我不可能结婚生子 +
就像庭外和解一样 何须多此一举？ +
-你的左卵巢至少还相信你 -我的生物一向不及格 +
我的右卵巢上了哈佛大学 真是讽刺 +
-我的子宫易位 -那又怎样？ +
所以精虫得跳过障碍 才能会合我的卵子 +
那里至少还有一颗卵子 +
我想另外找一家妇产科 你喜欢你的医生吗？ +
-现在不喜欢 -至少她是个女人 +
我试着去看过男医生 他却把时间全花在下面 +
结果连高潮和帐单都没给我 +
今天我请客 +
-我想餐厅大概不会收这个 -我今晚要在大人物家过夜 +
我的天，你们交往了这么久 你还没有抽屉可放东西吗？ +
-大人物对私人物品很在意 -男人都一样 +
所以你更应该声张你的地盘 +
这又不是争购土地 我们只是朋友 +
没错，你应该和他谈谈 +
对大人物而言还是提着包袱 安静的离开为妙 +
没错，她不应该留下私人物品 保持神秘感很重要 +
他都知道她穿内裤了 还有什么神秘可言？ +
我绝不会留内裤在男人家里 我绝不会再看到它 +
-你的内裤怎么了？ -没什么，我从来不吃回头草 +
每和男人上床就得丢一件内裤 是不是太浪费了？ +
所以我现在约会都不穿了 +
这也是我为什么不再向你 借衣服的原因 +
有一次我在一个男人家里 发现别的女人的内裤 +
那也许是莎曼珊的 +
有一次我在史蒂夫的浴室 +
发现一根卷曲的毛发 +
我就一直在想他是在我之前 和女友亲热过 +
还是和他约会的女人 穿了一件毛衣 +
-我有半数唱盘都是前男友的 -我会把那种东西还回去 +
我不认为那是分手的礼物 +
我是“混混与自大狂合唱团” 的忠实听众 +
-那是两性关系的纪念品 -我就向他要了一件T恤 +
上面印有“我与酒保约会 却搞得卵巢脏兮兮”的字样 +
第二天一早在大人物家里 我便开始思索 +
要是我们留下的东西 会成为交往过的纪念 +
我是该留下点东西 +
古人用壁画证明他们曾经存在 +
我则留下了吹风机 +
还乐此不疲 +
男人或许发现了火 女人却学会了玩火 +
夏绿蒂也在创造历史 +
她受够了和她交往的 那个原始人 +
竟然和一个承办酒席的同性恋 共度周六夜晚 +
而她当晚的点心就是主厨 史蒂芬鲍丁 +
真没想到蓓蒂布克鲁 这么多才多艺 +
拜托，她可是猫的睡衣 +
-大家为什么都这么说她？ -不知道 +
或许是因为她演出过“猫”吧 +
我们也来自创一句 好比“她是狗的晚礼服” +
谢谢你今晚邀请我去 +
别这么说 谢谢你接受我临时的邀约 +
我的朋友唐今早取消了约会 这张门票又退不掉 +
你随时都可以找我 能和男人这样畅谈非常难得 +
-你想喝杯咖啡吗？ -不了，我得回家了 +
-你住在住宅区？ -对，那你… +
我住在切尔西区 我帮你叫一辆计程车 +
-你也可以自己叫辆车 -露出大腿会有点帮助 +
我试过，可惜一无所获 +
谢谢，晚安 +
那出了什么问题？ +
我也搞不清了 他到底是不是同性恋？ +
问题没这么简单，问题在于… +
他是个纯粹的男同性恋？ 还是个双性恋？ +
男同性恋是个新兴的族群 +
目前大量出现在 曼哈顿的时尚圈 +
外国餐厅、音乐会 和古董家具界中 +
他最好是个双性恋的男同性恋 这表示他拥有男同性恋的特质 +
如果他是纯粹的男同性恋 表示他根本不可能碰你 +
那他一定是双性恋 因为他又约夏绿蒂出去了 +
除非他拒绝承认自己 是个百分之百的男同性恋 +
但那根本不叫约会 我没洗头，也戴着眼镜 +
那是消遣用药吗？ 这杯酒对我根本没作用 +
这是促进卵巢排卵的荷尔蒙 +
我妈停经之后才吃那种药 +
她的子宫也易位吗？ +
你们都没注意到我的皮包吗？ +
-真可爱，这是新款的吗？ -不，但它小得放不下内裤 +
-你将内裤留在大人物家了？ -没有，但我留了梳子 +
吹风机、除毛刀、月经棉条 还有眼部卸妆液 +
有进步 +
还有别的东西 +
-什么？ -你快说 +
我第一次在大人物家里上大号 +
我觉得在他家上大号很自在 这是好现象 +
才怪 +
-这是恋爱的终结 -这真的很了不起 +
我在上一段感情 都没做过这种事 +
我们周末出去度假 我还一直跑大厅的洗手间 +
这在纽约真的很不容易 在小公寓里做什么都听得到 +
所以我只和有钱人约会 +
钱能买到足够的空间 让你上大号 +
我就从未在男友家上过大号 +
你太紧张了，你应该上七号 +
抱歉 这是吧台的那位先生请的 +
是吗？ +
我的天，那是多明尼克 +
多明尼克德墨纳哥 是个出版业巨子 +
他是莎曼珊第一个 也是唯一爱过的男人 +
他曾与她有过一段炽烈的恋情 +
却为了冰岛一个叫安卡的名模 抛弃了她 +
后来又因为离婚 上“财富”杂志封面 +
-我去跟他打招呼 -你不在意他抛弃了你？ +
-他做了什么？ -让她心碎 +
你能想像莎曼珊心碎吗？ +
对夏绿蒂而言这比 和男同性恋舌吻更难以想像 +
那都过去了 我现在拥有绝对的优势 +
我早就超越他了 +
-小美人 -帅哥 +
这是什么？ +
你留在我家的几样东西 +
谢谢 +
这种感觉就像… +
我被踢出了我们之间的关系 +
大人物的家是怎么回事？ +
那里就像个所有女人的不沾锅 +
我是故意把东西留在你那里的 +
-为什么？ -因为… +
我不是一起床就画好妆的 +
我梳妆打扮需要一点东西 +
我不想整天像个游民一样 带着那些东西到处跑 +
那只是几样小东西 你也可以把东西留在这里 +
-我不想把东西放在这里 -你也不用放很多 +
你早上也许会需要刮胡子 +
-我都在健身房刮 -我一时也举不出例子 +
-好比袜子 -你要我把袜子放在这里？ +
别管我怎么说，你想放什么？ +
我们别兜圈子 你直接说你要我怎样好了 +
就你认为 +
什么是在交往的男女 最佳的状态？ +
-就是现在这样 -那是怎样？ +
我们各自有自己的住处 +
想在一起时便在一起 想独处的时候就独处 +
-就像伍迪艾伦和米亚？ -在顺宜出现之前 +
自从伍迪艾伦搬到顺宜家之后 +
一群单身汉就期待得到 这种同居的独居生活 +
我觉得我好像快绝种的恐龙 难道只有我需要适应环境吗？ +
我对两性关系不抱希望了吗？ +
在这个城市里的男同性恋 不但大张旗鼓又讲究时尚 +
单身女子的卵巢 却正濒临退化的边缘 +
我们随时可以请人代劳 +
请人带狗散步、洗衣服、煮菜 +
既然有了看门的人 谁还需要老公？ +
纽约人的男女关系 正在进化当中吗？ +
自从女人离开了洞窟 男女关系就开始疏离 +
这么说你不需要男人 但你却想拥有一个男人？ +
我想要的可不只一个 +
真不知道你该代表女人的 未来还是灭亡？ +
当然是未来 +
多明尼克让我了解到 过去的我有多么贫瘠 +
-我们星期五晚上要出去 -你花了一年时间才平复伤痛 +
他当年视你如蔽屣 你怎么还想和他出去？ +
-就因为他以前视我如蔽屣 -你这是在自掘坟墓 +
我这是在报复 我要先让他欲火焚身 +
在我们办事之前 再像他抛弃我一样丢弃他 +
-你有分寸就好 -我连礼服都买好了 +
莎曼珊的复仇计划 可谓曲折离奇 +
你比过去还要美艳 事业有成，我却已徒增白发 +
安卡把我的一切全抢走了 +
我看报上说她得到了那艘帆船 +
我们曾在船上共度过美妙时光 +
-你和安卡吗？ -我是说我们 +
我有说过你穿这件衣服 美得不可方物吗？ +
因为史蒂芬始终没有行动 +
夏绿蒂决定接受他的邀请 到他家用餐 +
-真好吃 -这是焗番茄披萨 +
撒上新鲜的罗勒叶 和巴马干酪起司 +
-这是玛莎的食谱 -我喜欢玛莎史都华 +
她就是个“狗的晚礼服” +
我在柏格朵夫家饰用品店 看过这些丝质的桌布 +
你很有品味 +
-这是我最想要的厨房 -这也是我的梦想 +
这是辛西雅罗莉的服饰吗？ +
夏绿蒂希望自己能抛弃成见 +
但史蒂芬却让情势每下愈况 +
这时候莎曼珊已经 让多明尼克心痒难耐 +
你想要我吗？ +
我当然要你 +
莎曼珊多年来就等待这一刻 +
何须再费心等待？ +
-你去大人物家了吗？ -不，我出去逛街了 +
我和他的关系正面临僵局 我就想打扮自己，你还好吗？ +
-我和他上床了 -这不在你的计划之内吧？ +
我改变主意了 我要让他知道他错过了什么 +
我以前竟然当他是个完美情人 +
我现在比他更胜一筹，再见 +
为了在纽约的男女关系中 生存二十年 +
莎曼珊变成了一种混种人 +
她那纯女性的躯体底下 包裹的是大男人的心态 +
夏绿蒂深怕史蒂芬是个 百分之百的男同性恋 +
她需要找人为她鉴定 便带来了两个专家 +
-凯莉、史丹佛，这是史蒂芬 -你好 +
-你换了发型 -对，我把头发烫直了 +
-我们见过吗？ -没有，我读过你的专栏 +
你在照片上是一头卷发 +
你两种发型都很好看 +
奶油泡芙和水果蛋糕，太棒了 +
里面有各种材料 这是我试做的成品 +
-这是水果蛋糕和南瓜冻 -这是你为我们做的？ +
-是我做给我的甜心的 -还有两个白吃的朋友 +
我的营养师一定会宰了我 快把叉子给我 +
-你也一起吃吧？ -但是我得去盯着结婚蛋糕 +
我稍后再回来吃水果蛋糕 +
他的确很吸引人 但他绝对不是同性恋 +
因为他一直在讨好夏绿蒂 +
他会不会是同性恋？ 只是他还不知道？ +
我们对这种事很清楚 我小的时候 +
我爸给我一本两性书籍 要教我男女之事 +
我只看了一眼就说：我不看 +
-他在床上的表现如何？ -我还没和他上过床 +
-是吗？ -但是他很想 +
真不公平，好男人都这么君子 连男同性恋也是 +
-你是不是在看我的额头？ -不是 +
米兰达那天晚上 和约瑟夫艾勒出去吃饭 +
这个律师自从结案之后 就一直在追她 +
-这个小羊肉很好吃 -你大可放心的看 +
我打算在这里植发 +
她拒绝过他两次 但在知道卵巢排卵延迟后 +
她认为不能因为秃发的问题 就宣判一个男人死刑 +
-我以前跟你说过我是个秃头 -我记得 +
现在能有头发真是个奇迹 再吃点蛋糕吧 +
你一定觉得我很蠢 +
我看你似乎很快乐 +
我从来没想过我会去植发 +
-天下没有不可能的事情 -我懂你的意思 +
最近我也碰到了 我从来没想过的问题 +
什么事？ +
-你真的想知道吗？ -当然 +
我最近发现我有 排卵迟缓的问题 +
这表示我每隔几个月 只会排一次卵 +
我甚至不确定我想要小孩 +
但我担心左边卵巢也罢工了 我就没本钱了 +
所以我就开始服用荷尔蒙 甚至考虑冷冻卵子 +
-冷冻卵子？ -就是给卵子开一个帐户 +
这样压力就会小一点 +
这样就能免除生理时钟的问题 +
-但这却会增加其他的问题 -好比什么？ +
好比这种生殖科技 能为我们做什么？ +
我们要让年届五十的女人 勉强生儿育女吗？ +
也许有些人本来就不该生孩子 +
也许这就是世界淘汰的方式 +
我认为这是在滥用科学 +
现在有基因改造的精子 人造子宫 +
其实我们可以集体来进行淘汰 +
我不需要一个正在植发的人… +
教我什么科学才是正确的 +
米兰达的荷尔蒙会产生作用 不是因为约瑟夫 +
是因为她年仅33还有左卵巢 还不想就此放弃希望 +
也许哪天 她会去把她的卵子冷冻 +
夏绿蒂不想再费神探究 这位神秘郎君 +
她要纵情享受 +
-雪儿？ -我喜欢她 +
她真的很耐磨 +
慢着，我得问你几件事情 +
你和男人在一起过吗？ +
没有，你和女人在一起过吗？ +
对不起，我是想到… +
蓓蒂布克鲁、玛莎史都华 和辛西雅罗莉… +
你是男同性恋吗？ +
夏绿蒂，我是个35岁 住在切尔西区的西点师父 +
我如果是个同性恋 早就是同性恋了 +
一直不想做爱的是你 +
现在我就不确定了 +
知道史蒂芬不是同性恋之后 夏绿蒂总算放心了 +
至少他不是百分之百的同性恋 +
在到达两次高潮之后 谁还会在乎那些？ +
隔天早上莎曼珊终于明白 +
她对多明尼克复仇的决心 并不如她的欲望来得强烈 +
-你醒了 -没错 +
你真是美极了 +
-我会想你的 -什么意思？ +
我和安卡决定再试一次 +
完全是为了经济的考量 +
-你不能这么对我 -我很抱歉 +
不…应该是我对你说抱歉 +
-这一切不是我的计划 -我该走了 +
-你滚 -我说过我要走了 +
你休想再击垮我 +
当历史重演的时候 +
莎曼珊才知道她无法 像多明尼克一样无情 +
因为她还没有完全的进化 +
但这也算是个好消息 +
-早安 -早安，睡美人 +
什么味道这么香？ +
蔓越莓脱脂奶烤饼和柠檬酱 +
我要再和你约会下去 准会胖个十磅 +
那你还是会很美丽 +
-想不想喝茶？ -好，谢谢 +
-这是什么声音？ -什么声音？ +
有点像老鼠的叫声 +
我的天，真的是老鼠 +
-你确定吗？ -在灭鼠毡上 +
-哪里？ -那里 +
它的腿粘住了 +
-你快想想办法，别踢给我 -拿走 +
我的天 +
这时候夏绿蒂了解到 她男性的一面还没进化成形 +
而史蒂芬的女性特质 却得到了高度的发展 +
自从我的东西被赶走之后 这是我第一晚在大人物家过夜 +
-你要去哪里？ -回家 +
-不要… -我的吹风机在我家 +
我要吹头发 我现在留的是一头直发 +
我注意到了 我觉得你现在这样很好 +
你那可爱的小屁股快回到床上 +
我得确定没有东西留下 +
我突然间觉得根本无须在意 要不要留下东西 +
因为我就在那里 +
我可以待久一点 但我要把内裤留在这里 +
它干净吗？ +
这是人类的一小步 却是大人物的一大步 +
