= 0309
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 309: Describing Distances and Giving Directions.
This is English as a Second Language Podcast episode 309. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com and go to our ESL Podcast Store where you can find several premium courses – additional courses on daily English and business English topics.
This episode is called “Describing Distances and Giving Directions.” It’s going to be a dialogue between Daniella and someone who works at a hotel – a hotel clerk – about how to get to – how to arrive at – different places in the city. Let’s get started.
[start of dialogue]
Daniella: Could you tell where I can find a drugstore?
Hotel clerk: Sure. There’s one up the street near the corner of Selma and Main. If you get to Abreu Avenue, you’ve gone too far. It’s set back from the street so it’s a little hard to find.
Daniella: Oh, that’s okay. I’ll keep an eye out for it.
Hotel clerk: You know, I just remembered that there’s a bigger and better drugstore around the block. It’s no more than a three-minute walk. Go out the main doors of the hotel, hang a left, go straight for about a quarter of a mile, and then make another left at the first street.
Daniella: Okay. I think I’ve got that. Thanks.
Hotel clerk: Now, if you want a drugstore with a pharmacy, you’ll need to walk a little farther. Go out these doors, walk roughly three blocks until you get to a dead end, turn right, cross the street, and you’ll see a bank. It’s kitty-corner from the bank. You should be able to walk there in five minutes, give or take.
Daniella: Thanks. Thanks a lot. I think I’m all set. See you later.
Hotel clerk: You know, I just remembered that there’s another drugstore...
Daniella: Thanks, but I’ve really got to get going. Bye.
Hotel clerk: Well, some people just don’t appreciate other people’s help!
[end of dialogue]
Our dialogue begins with Daniella saying to the hotel clerk – the employee at the hotel, “Could you tell me where I can find a drugstore?” The hotel clerk says, “Sure (yes). There’s one up the street near the corner of Selma and Main.” “Selma and Main” are the names of two streets in their city. The expression “up the street” means on the same street that you are on right now at a close distance, not too far. You will hear the expressions “up the street” and “down the street” often meaning the same thing. “Up the street” is sometimes used when you are up a hill – you are going up a hill; “down the street” could be going down the hill, but in general conversation they are often used to mean the same thing, a close distance to where you are now.
The clerk says that the drug store is “up the street near the corner of Selma and Main.” The “corner” is what we call the place where two streets cross each other – where they meet, that would be the “corner.” “Meet me on the corner of Hollywood and Vine” means meet me on the corner of Hollywood Boulevard and Vine Street, which happens to be in the Hollywood section of Los Angeles. Here, the drug store is on the corner of “Selma and Main.”
The clerk says, “If you get to Abreu Avenue, you’ve gone too far.” To “go too far” means to accidentally pass something, to accidentally walk or drive past the place where you wanted to go. For example, I left Minnesota driving to Colorado, but a couple of days later I found myself in Los Angeles. I asked someone, “Is this Colorado?” and they said, “No, this is California. You’ve gone too far.” But, I decided to stay in LA!
The hotel clerk says that the drugstore is “set back from the street so it’s a little hard to find.” To be “set back from” a road or a street means that the building is not next to the street – not immediately next to the street. The building is not close to the street; there is some space – some distance – between where the street ends and where the building begins. Daniella says, “Oh, that’s okay. I’ll keep an eye out for it,” meaning “I’ll be looking for it carefully.”
The hotel clerk says, “You know, I just remembered that there’s a bigger and better drugstore around the block.” A “block” is what we call the space – usually a square – where there are four streets, one on each side. That space – that area is called a “block.” When someone says “it’s around the block,” they mean that you can go up the street and take a left or a right, and it will be on the street that crosses the one where you are. Sometimes “around the block” just means it’s very close, similar to “up the street,” but when it’s on a different street.
The hotel clerk says, “It’s no more than a three-minute walk. Go out the main doors (meaning exit or leave the main doors) of the hotel, hang a left, go straight for about a quarter of a mile, and then make another left at the first street.” To “hang (hang) a left” is an informal way of saying to turn left, to make a left-hand turn. You can “hang a left,” or you can “hang a right.” When I was growing up, some kids would make a joke and say, “Hang a Louie.” Instead of saying “left,” they would say “Louie” because, I guess, it sounded funny.
The hotel clerk tells Daniella to “hang a left, go straight (continue walking straight) for about a quarter of a mile.” A “mile,” you probably know 1.61 kilometers – 5,280 feet, to be exact. Then the hotel clerk says, “make another left at the first street.” Daniella says, “Okay. I think I’ve got that (meaning I think understand). Thanks.”
The hotel clerk continues, “Now, if you want a drugstore with a pharmacy, you’ll need to go a little farther.” A “pharmacy” is a place where you can get drugs that are given to you or you are told to take by your doctor. A drugstore sometimes doesn’t have a pharmacy in it; you can buy certain kinds of drugs, but you can’t buy the drugs that your doctor gives you to take that require special permission.
The clerk says you need to walk little farther to find the drugstore with the pharmacy. “Farther” means at a greater distance – more. The clerk says to Daniella, “Go out these doors (exit these doors – through these doors), walk roughly three blocks.” “Roughly” here means about; approximately; around. “I am roughly 5 feet 10 inches” – maybe a little taller, maybe a little shorter.
The clerk says to Daniella, “walk roughly three blocks until you get to a dead end.” A “dead end” (two words) is a street that stops, it’s where the street ends – it doesn’t continue going any further, it’s a “dead end.” Sometimes a “dead end” means that the street doesn’t connect to any other streets. In our story, however, it means that the street ends, so you need to take a right, the hotel clerk says, “cross the street (to cross means to walk over to the other side of the street), and there you’ll see a bank.” To “cross” something has a couple of different meanings; take a look at our Learning Guide for some additional explanations.
So the hotel clerk is explaining to Daniella how she will see a bank after she crosses the street. The clerk says, “It’s kitty-corner from the bank.” The drugstore is “kitty (kitty) -corner from the bank.” To be “kitty-corner” from something means to be located on the other side of the street in the opposite part of an intersection. So, you have two streets that cross each other; there are four corners at the intersection. If you are in the southwest corner, to be “kitty-corner” would be on the northeast corner. So, it’s on the other side of both streets when you are at an intersection where the two streets cross. That’s “kitty-corner”; it’s diagonal from where you are. A “kitty” is normally an informal word for a cat. I don’t know why it is related to this expression, but there you have it!
The clerk says to Daniella, “You should be able to walk there in five minutes, give or take.” The expression “give or take” means more or less; approximately; about; roughly. All of those mean the same. “I’m 130 pounds (I weigh 130 pounds), give or take.” Sometimes we’ll say how much give and take: “I weigh 130 pounds, give or take 50 pounds,” meaning maybe it’s 50 pounds less, maybe it’s 50 pounds more.
Daniella says, “Thanks. Thanks a lot. I think I’m all set.” To be “all set” means to be ready to do something; to be prepared to do something. The word “set” has a couple of different meanings in English; again, take a look at the Learning Guide for additional explanations.
The clerk finally says, “You know, I just remembered there’s another drugstore...” “You know” is a very common phrase in English, sometimes used to introduce a new idea or new information that you haven’t thought about before. The clerk wants to give her more directions to another drugstore. Daniella says, “Thanks, but I’ve really got to get going. Bye.” The hotel clerk seems upset that Daniella is leaving. He says, “Well, some people just don’t appreciate other people’s help!”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Daniella: Could you tell where I can find a drugstore?
Hotel clerk: Sure. There’s one up the street near the corner of Selma and Main. If you get to Abreu Avenue, you’ve gone too far. It’s set back from the street so it’s a little hard to find.
Daniella: Oh, that’s okay. I’ll keep an eye out for it.
Hotel clerk: You know, I just remembered that there’s a bigger and better drugstore around the block. It’s no more than a three-minute walk. Go out the main doors of the hotel, hang a left, go straight for about a quarter of a mile, and then make another left at the first street.
Daniella: Okay. I think I’ve got that. Thanks.
Hotel clerk: Now, if you want a drugstore with a pharmacy, you’ll need to walk a little farther. Go out these doors, walk roughly three blocks until you get to a dead end, turn right, cross the street, and you’ll see a bank. It’s kitty-corner from the bank. You should be able to walk there in five minutes, give or take.
Daniella: Thanks. Thanks a lot. I think I’m all set. See you later.
Hotel clerk: You know, I just remembered that there’s another drugstore...
Daniella: Thanks, but I’ve really got to get going. Bye.
Hotel clerk: Well, some people just don’t appreciate other people’s help!
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
up the street – on the same street one is currently on, but uphill or further along
* The library is up the street from the Thai restaurant.
corner – the place where two streets meet each other
* Our house is on the corner of Madison Street and Deustua Avenue.
to go too far – to accidentally pass something; to accidentally walk or drive past the place where one wanted to go
* When we reached 97th Street, we realized that we had gone too far, so we had to turn around and drive back.
set back from (a road or street) – not immediately next to a street; with some space between the building and the street
* The lawyer’s office is set back from the street with a parking lot in front.
around the block – on the other side of a group of buildings that have streets on all four sides
* This street has a lot of formal restaurants, but around the block, there are some inexpensive coffee shops.
to hang a left – to turn left; to make a left-hand turn
* Hang a left on Floral Avenue, and then my house will be on the right.
mile – a measurement of distance; 1 mile = 5,280 feet = 1.61 kilometers
* Sherri runs five miles every morning before she goes to work.
farther – a greater distance
* I watched Uncle Kenny drive farther and farther away until I couldn’t see his car anymore.
roughly – about; approximately; around
* Patricio makes roughly $2,000 a month working at the restaurant.
dead end – a road that ends without connecting to any other streets
* Shannon likes living on a dead end because there aren’t very many cars and her children can play in the street.
to cross (something) – to walk or drive across something; to go from one side of something to the other side
* How long does it take to cross the Golden Gate Bridge in San Francisco?
kitty-corner – located on the opposite point of an intersection; located diagonally at an intersection; located on the opposite point of the place where two streets meet each another
* The hotel is kitty-corner from the cathedral.
give or take – more or less; approximately; about; around; roughly
* You will be able to finish the test in about 45 minutes, give or take.
all set – ready to do something; fully prepared to do something
* Are you all set for your vacation to the Bahamas?
You know,… – a phrase used to introduce a new idea; a phrase used to introduce new information that one hadn’t thought of before
* The man spent 15 minutes telling the salesperson what he wanted to buy. When she found it, he said, “You know, I think I want to get this in a different color.” She was very frustrated.
Comprehension Questions
1. Why does the hotel clerk say that the first pharmacy is a little hard to find?
a) Because it has its back to the street.
b) Because it isn’t directly on the street.
c) Because the street is next to Abreu Avenue.
2. What does it mean for the second pharmacy to be kitty-corner from the bank?
a) It’s across from a pet store that sells kittens.
b) It’s near a dead end, three blocks away.
c) It’s on the opposite corner from the bank.
Answers at bottom.
What Else Does It Mean?
cross
The verb “to cross,” in this podcast, means to go from one side to the other side of something: “Many dogs are hit by cars when they try to cross the street.” A “cross” is also the symbol made when two lines cross each other (+ or x): “Please read the agreement and then sign your name where I’ve put a cross.” When capitalized, the “Cross” is a symbol of Christianity, because Jesus Christ was hung and died on a wooden cross: “Catholics may kiss a small Cross at the church.” Catholics may also “cross themselves,” meaning that they use their hand to make the symbol of the cross on their chest. If a person is “cross,” it means that he or she is angry, frustrated, annoyed, or in a bad mood: “Gregory is cross because he didn’t get the job he applied for.”
set
In this podcast, the phrase “all set” means ready to do something: “Once I finish packing, I’ll be all set for our business trip.” The phrase “to set off” means to start a trip: “What time are you setting off for Detroit?” The phrase “to set out” means to leave a place to start a trip: “We set out from Eugene, Oregon at 6:00 a.m. so that we could get to Southern California the same day.” The phrase “to set (something) up” means to do the preparations to get something ready: “How long will it take to set up the restaurant for the party?” Finally, the phrase “to set (something) aside” means to not use something right now and instead save it for the future: “I really wanted to read that book, but I decided to set it aside until I have enough time to finish it all at once.”
Culture Note
Many Americans have “navigation systems” (machines that tell one where one is and where one needs to go) in their cars. The driver can “enter” (type in) his or her “destination” (the place one wants to go) into the navigation system. Then the navigation system gives specific “driving directions” (detailed instructions of where to go) for how to get there. Many navigation systems have color maps that “update” (display new information) as the car moves.
These navigation system use the “global positioning system” (“GPS”), which is a technology that lets people know where they are by using a small electronic device. Many “backpackers” (people who walk long distances for many days in the mountains) were the first people to use GPS, but today it is more common and is often used in cars.
One popular navigation system is OnStar. OnStar can provide driving directions for almost any U.S. destination. OnStar can also be used in emergencies. For example, if the driver has a problem, he or she can push a button and OnStar will “automatically” (without the person having to do anything) communicate with an OnStar representative. Newer cars with OnStar will automatically send a message if the car is in a “collision” (when a car hits another car or object).
People who don’t own expensive cars with OnStar have to find other ways to navigate in unfamiliar areas. Some of these people use their “personal digital assistants” (“PDAs”; small computers that can be held in one’s hand) to display driving directions. Other people use online mapping services like MapQuest.com and Maps.Yahoo.com to print out driving directions before their trip.
Comprehension Answers
1 - b
2 - c