= 0310
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 310: Shopping for Furniture.
This is English as a Second Language Podcast episode 310. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful, warm Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. Our Learning Guides contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, and a complete transcript of this episode.
This episode is called “Shopping for Furniture.” It’s a dialogue between two people who just got married, or are going to get married, and are looking for things for their new house or apartment. Let’s get started.
[start of dialogue]
Tobias: I really don’t understand why we need new furniture. After we’re married, we’ll just take the things from each of our two apartments and that should do the trick.
Renee: We each have some things we can keep and use, but it would be nice to have pieces that match. Right now, we have six dining chairs, each in a different style, and none of them are in the same style as the dining table your uncle is giving us as a wedding present.
Tobias: Yeah, that’s true. At least, we won’t have to shop for bedroom furniture. We’re lucky that your parents are giving us some hand-me-down things, including a dresser, two nightstands, a headboard, and a wardrobe. All we need is a bed.
Renee: Yeah, we got lucky when they decided to get new furniture and to give us their old pieces. That just leaves the living room.
Tobias: But we already have a couch and a love seat.
Renee: That’s true, but we still need a coffee table, two side tables, and at least two table lamps and a floor lamp.
Tobias: Do we really need all of that?
Renee: If we plan to entertain, we do.
Tobias: All right. I was just hoping to get home in time for the game this afternoon.
Renee: No problem. We only have six more stores to visit after this one.
Tobias: Six?!
Renee: Yes, now come on. How are you going to get home in time for the game if you don’t hurry up?
[end of dialogue]
Our dialogue between Tobias and Renee begins by Tobias saying, “I really don’t understand why we need new furniture.” “Furniture” is a general term that refers to things in your home or office, usually large things like a desk or a chair. A couch, bookshelves, these are all considered “furniture.” Tobias says, “After we’re married, we’ll just take the things from each of our two apartments and that should do the trick.” Tobias is saying that he and Renee both have furniture; they can combine the furniture after they get married in their new home or apartment. Tobias says that will “do the trick.” The expression “to do the trick” means to meet one’s needs, to be fast or good enough to be satisfactory. Something that is sufficient is to do the trick: “I’m having problems with my computer. I’m going to reboot it (I’m going to turn it on and off) and that should do the trick” – that should solve the problem, in this case.
Renee says, “We each have some things we can keep and use, but it would be nice to have pieces that match” – it would be nice to have pieces of furniture that match. To “match,” here, means to be in the same color and style so that they look good together. If you have a white couch and a pink chair or a red table, they may not match – they may not go together, look good together. To “match” has a couple of different meanings in English; take a look at our Learning Guide for some additional definitions.
Renee continues, “Right now (at this moment), we have six dining chairs, each in a different style.” A “dining chair” is a chair you put next to a table and sit on when you are eating. We call that part of your house the “dining room.” To “dine” (dine) means to eat. So, the dining chairs are a different style and therefore they don’t match. “None of them,” she says “are the same style as the dining table your uncle is giving us as a wedding present,” or gift. The “dining table,” you can guess, is the table on which you eat.
Tobias says, “Yeah, that’s true. At least, we don’t have to shop for bedroom furniture. We’re lucky that your parents are giving us some hand-me-down things.” The expression “hand-me-down” (hand-me-down) means used, not new, usually things that, for example, an older brother would give his younger brother. A shirt that is too small for him, he would “hand it down.” To “hand” something can mean to give something to someone, so a “hand-me-down” is something that you were given; it’s not new. When I was growing up a lot of my clothing was hand-me-downs, things that my older brothers no longer needed.
The things that Renee’s parents are giving them for the bedroom are “a dresser, two nightstands, a headboard, and a wardrobe.” A “dresser” is a piece of furniture that has little boxes that pull in and out, we call them “drawers” (drawers), and we use them for putting clothing into – to store clothing, to keep your clothes in these little boxes or drawers, and they’re usually two, three, or four of them on top of each other. That’s a “dresser.” A “nightstand” (one word) is a small, short table that you put next to your bed. I have a nightstand next to my bed with a clock and some Kleenex on it. That’s a “nightstand.” A “headboard” (one word) is a large piece of, usually, wood that is next to the wall in the bedroom and is usually attached to the bed. So it’s like the top part of the bed, but it’s against the wall – it’s vertical. Finally, a “wardrobe” (wardrobe) is a large piece of furniture that has doors on it so that you can put clothes inside, you can hang them on what we would call a “hanger.” For example, your shirt, you can put it on this triangular hanger – it’s like a little triangle – and then you can hang in on a bar, and that piece of furniture where you put that into is called a “wardrobe.” It has, usually, two doors on it.
Tobias says, “All we need (the only thing we need) is a bed.” The “bed,” of course, is what you sleep on in the bedroom. Renee says, “Yeah (yes), we got lucky (we were lucky) when they (my parents) decided to get new furniture and to give us their old pieces (their old pieces of furniture). That just leaves the living room,” meaning the only thing left we have to worry about now is the living room.
Tobias says, “But we already have a couch and a love seat.” A “couch” (couch) is a long, soft piece of furniture that is usually in the living room – the main room of the house where three, four, or more people can sit on. Usually three or four people can sit on a couch; it’s like a big chair for three or four people. A “love seat” (two words) is a small couch for two people. So, you have a chair for one person, a love seat for two people, and a couch for three or more people. If you have five or more people, you should buy some more furniture!
Renee says, “That’s true (we do have a couch and a love seat), but we still need a coffee table, two side tables, and at least two table lamps and a floor lamp.” A “coffee table” (two words) is a long, short table, usually that is put in front of a couch or a love seat where you can put your paper and your coffee and a book, for example. That is a “coffee table.” A “side table” is small round or square table that is at the end on the side of the couch or the love seat. Many people don’t have side tables; they just have coffee tables. A “table lamp” is a lamp – a light – that you put on a table, usually next to a bed or a couch. A “floor lamp” is a light that rests on the floor – it’s put on the floor and usually has a long pole so that the light goes above your head if you are, for example, sitting on the couch or in the love seat.
Tobias says, “Do we really need all of that?” and Renee says, “If we plan to entertain, we do.” To “entertain” means to invite other people to your house for a party or a dinner – a meal. Tobias says, “All right. I was just hoping to get home in time for the game this afternoon.” Tobias wants to go home and watch the sports game – the baseball game or the soccer game. Renee says, “No problem. We only have six more stores to visit after this one.” Tobias is surprised. “Six?!” he says, and Renee says, “Yes, now come on (meaning hurry up). How are we going to get home in time for the game (before the game starts) if you don’t hurry up?”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Tobias: I really don’t understand why we need new furniture. After we’re married, we’ll just take the things from each of our two apartments and that should do the trick.
Renee: We each have some things we can keep and use, but it would be nice to have pieces that match. Right now, we have six dining chairs, each in a different style, and none of them are in the same style as the dining table your uncle is giving us as a wedding present.
Tobias: Yeah, that’s true. At least, we won’t have to shop for bedroom furniture. We’re lucky that your parents are giving us some hand-me-down things, including a dresser, two nightstands, a headboard, and a wardrobe. All we need is a bed.
Renee: Yeah, we got lucky when they decided to get new furniture and to give us their old pieces. That just leaves the living room.
Tobias: But we already have a couch and a love seat.
Renee: That’s true, but we still need a coffee table, two side tables, and at least two table lamps and a floor lamp.
Tobias: Do we really need all of that?
Renee: If we plan to entertain, we do.
Tobias: All right. I was just hoping to get home in time for the game this afternoon.
Renee: No problem. We only have six more stores to visit after this one.
Tobias: Six?!
Renee: Yes, now come on. How are you going to get home in time for the game if you don’t hurry up?
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse. Thank you Lucy!
If you have a question or comment about our podcast you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
furniture – large things that are put inside one’s home or office to make it more comfortable and/or easier to live or work in
* Maude’s bedroom has only three pieces of furniture: a bed, a small table, and one chair.
to do the trick – to meet one’s need; to be good, fast, or big enough; to be satisfactory
* Becky’s bicycle made loud squeaks when she rode it, but putting a little bit of oil on the wheels did the trick, and now it doesn’t make any noise at all.
to match – to have the same color and style so that something looks good next to something else
* Does this shirt match these pants?
dining chair – a chair put next to a table and used to sit on while eating
* Their dining chairs are very uncomfortable so they never spend very much time talking around the table after they finish eating.
dining table – a large table that holds plates, silverware, and food while people are eating
* We like having dinner parties, so we have a large dining table that has room for 10 people.
hand-me-down – used; things that are used by another person and then given to oneself, because they can still be used, even though they aren’t new
* Todd wears hand-me-down clothes that used to belong to his older brothers.
dresser – a piece of furniture with drawers that are used to store folded clothing
* I use the small dresser drawers for socks and underwear, and the large dresser drawers for pants, t-shirts, and sweaters.
nightstand – a small, short table that is placed next to a bed
* Christophe keeps a small lamp, his favorite book, and a glass of water on his nightstand.
headboard – the large piece of wood that stands next to the wall and is attached to the end of the bed where one rests one’s head
* Danielle’s parents bought her a new bed and put up a large wooden headboard with flowers painted on it.
wardrobe – a large piece of furniture that has doors that open so that clothes can be hung inside
* Bjorn’s room doesn’t have a closet, so he bought a wardrobe where he can hang his suits.
bed – a piece of furniture that one sleeps on
* We stayed in a hotel with very uncomfortable beds, so we weren’t able to sleep well that night.
couch – a long, soft piece of furniture that is put in the living room for three or more people to sit on
* Alicia didn’t feel well, so she spent all afternoon sitting on the couch and watching TV.
love seat – a piece of soft furniture that is put in the living room for one person to sit on, or for two people to sit on very close to each other
* Dana and her boyfriend like to sit on the love seat, so that they can be very close to each other.
coffee table – a long, short table that is placed in front of a couch or love seat
* I set your cup of tea on the coffee table a few minutes ago. I hope it’s not cold already.
side table – a small table that is placed at one end of a couch or love seat
* Richard keeps interesting magazines on his side tables in the living room.
table lamp – a small lamp (light) that is placed on a table, usually next to a couch or bed
* Ita keeps a table lamp on the nightstand next to her bed, so that she can read before she falls asleep.
floor lamp – a tall lamp (light) that rests on the floor and reaches toward the ceiling
* This room doesn’t have any lights built into the ceiling, so we bought a few floor lamps to provide light.
to entertain – to invite other people to one’s house to eat, drink, and have fun together
* Martha likes to entertain, so she often invites people over to eat dinner at her house.
Comprehension Questions
1. Why does Renee want to buy new furniture?
a) Because the furniture pieces they have don’t look good together.
b) Because they don’t have enough pieces of furniture.
c) Because they don’t have furniture in their two apartments now.
2. How will Renee and Tobias get their bedroom furniture?
a) Their uncle will give it to them as a wedding present.
b) Renee’s parents will give them their old furniture.
c) They will buy bedroom furniture by visiting six stores.
Answers at bottom.
What Else Does It Mean?
match
The verb “to match,” in this podcast, means to have the same color and style so that something looks good next to something else: “We want to buy some bathroom towels that match the color we’ve painted the walls.” A “match” is also a small piece of wood or heavy paper that is used to start a fire: “If your matches get wet, it will be very difficult to light the candle.” In sports, a “match” is a competition or one game between two players or teams: “What time will the tennis match begin this afternoon?” Finally, if two people are “a good match,” it means that they make a good couple, or that they work well together: “Chrissie and Joseph make a good match, and I hope they get married.”
wardrobe
In this podcast, the word “wardrobe” means a large piece of furniture that has doors that open so that clothes can be hung inside: “Randy has so many clothes that they don’t all fit in his wardrobe.” A “wardrobe” can also mean all the clothes that a person has, particularly for a specific season: “When Shawn moved from Hawaii to New York, he had to buy a new winter wardrobe because he had clothes only for warm weather.” Or, “Jackie needs to buy a more professional wardrobe if she wants to get a better job.” In the theater, “wardrobe” refers to the department that creates all the clothes that the actors wear: “The wardrobe department has to make more than 100 dresses for this play.”
Culture Note
In the United States, people can choose among many popular furniture styles. Some of these popular styles include “shabby chic,” “craftsman,” and “arts and craft” furniture styles.
The word “shabby” usually means something that isn’t very nice, because it has been used too much. “Chic” means elegant and fashionable. When these words are used together, the phrase “shabby chic” is a style for “decoration” (the way that one uses furniture, paint, curtains, and other things to make a room or house appear a certain way). The “shabby chic” style uses old objects but makes an elegant “overall effect” (the impression that people have by looking at a room as a whole). Although each piece of furniture may be old and “faded” (with colors that are no longer bright because they have been in the sun too much), “shabby chic” furniture is attractive and makes the room elegant. Sometimes people take new furniture and “distress” it (try to make it look older) to achieve the same overall effect.
The “craftsman” furniture style is based on simple, large pieces of furniture that are made by individual “craftsmen” or “crafts workers” (professional woodworkers, glassworkers, or metalworkers) from wood, glass, metal, or other material. Craftsman-style furniture is made from natural materials and sometimes gives the house an overall effect of being in the country in the past, where people made their own furniture, but with very high quality.
Finally, the “arts and craft” furniture style refers to furniture that is simple and “utilitarian” (has a practical purpose or function). It uses straight lines and little “ornamentation” (fancy details that make something pretty, but don’t make it more useful). Arts and craft furniture makes a home feel comfortable and relaxed.
Comprehension Answers
1 - a
2 - b