= 0325
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 325: Describing People’s Moods.
This is English as a Second Language Podcast episode 325. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and take a look at our premium courses. We have additional special courses in business and daily English we think you’ll be interested in. You can also download the individual Learning Guide, an 8 to 10 page guide to this episode, on our website.
This episode is called “Describing People’s Moods,” the way people act or behave toward one another. It’s a dialogue between Brett and Molly talking about different people’s moods. Let’s get started.
[start of dialogue]
Brett: Do you know what kind of mood Mom is in?
Molly: Not really. Why?
Brett: I really need a raise in my allowance and I’m waiting for the right time to ask. She’ll be more likely to say “yes” if she’s not feeling too grouchy.
Molly: I wouldn’t count on this being a good time. She looked a little upset after getting off the phone with Aunt Teri.
Brett: Why?
Molly: Aunt Teri has been down in the dumps since Cousin Frank decided to take a job in Cambodia. He’s on cloud nine about this new job, but Aunt Teri is anxious about him moving so far away.
Brett: I see. Well, I’ve got to think of some way to cheer her up. It’s a lost cause if I ask her while she’s angry, on edge, or depressed.
Molly: You know that Mom is always happy to hear good news about school. Do you have anything new to report?
Brett: I hadn’t thought of that. I need to come up with something.
Molly: Be patient. Wait for the right moment and then strike. I speak from years of experience.
Brett: Right. Thanks.
[end of dialogue]
Brett begins the dialogue by saying to Molly, “Do you know what kind of mood Mom is in?” – do you know the way that Mom is feeling right now, what is her attitude – is she happy, is she sad, etc.? Molly says, “Not really. Why?”
Brett says, “I really need a raise in my allowance.” A “raise” is an increase. An “allowance” is a small amount of money that some parents give to their children each week or every two weeks that they can spend on whatever they want. Brett wants to increase his allowance; he wants his parents to give him more money. Brett says that his mother will “be more likely to say ‘yes’ if she’s not feeling too grouchy.” “Grouchy” (grouchy) means not happy, someone who’s always complaining. “I am always grouchy in the morning when I have to get up early” – I am not happy. Not normally, but sometimes I’m grouchy!
Molly says, “I wouldn’t count on this being a good time.” To “count on” is a two-word phrasal verb meaning to rely on, to depend on, to assume that something will be a certain way. There’s a common expression “don’t count on it,” meaning don’t rely upon it – don’t depend upon it, it may not happen. Molly says that her mother “looked a little upset after getting off the phone with Aunt Teri.” To “get upset” means to get angry or worried or anxious. It’s the opposite of “calm.” So, she looked a little upset after she hung up the phone – after she stopped talking on the phone with Aunt Teri; she got off the phone.
Brett says, “Why?” Molly says, “Aunt Teri has been down in the dumps.” To be “down in the dumps” (dumps) means to be very sad, to be unhappy, to be depressed. That’s to be “down in the dumps.” Why is Aunt Teri down in the dumps? Well, because her son Frank, who is Brett and Molly’s cousin, “decided to take a job in Cambodia,” a country in Southeast Asia, very far away.
Molly says Frank is “on cloud nine about this new job.” The expression to be “on cloud nine” means to be very happy, to be overjoyed, to be extremely happy: “I’m on cloud nine.” It’s not exactly clear where the expression “on cloud nine” comes from. Some people say it comes from an old way that scientists used to measure the height of clouds, and “cloud nine” was the highest level. Other people say it comes from Buddhism, in describing being very close to your final goal or destination. I’m not sure which, if either, of these explanations is correct, but everyone understands it to mean very happy. If I won the lottery today, I’d be on cloud nine – maybe cloud 99!
Molly says that her Aunt Teri is “anxious” about Frank moving away so far. To be “anxious” means to be worried, to be nervous. Brett says, “I see (I understand). Well, I’ve got to think of some way to cheer her up.” To “cheer someone up,” or to “cheer up someone,” means to make someone feel better, to make someone feel happier – to do something that will make them feel happier.
Brett says, “It’s a lost cause if I ask her while she’s angry, on edge, or depressed.” To say something is a “lost cause” means it is impossible, it can’t be done. My singing teacher tells me, “Jeff, you’re a lost cause. There’s nothing that can be done to improve your singing.” I’m a lost cause!
Brett uses some adjectives to describe his mother’s possible moods. He says she could be “angry,” meaning mad, when you don’t like something very much. She could be “on edge,” meaning she’s nervous or excited about something. The expression “on edge” has a couple of different meanings; take a look at the Learning Guide for some additional explanations. Or, Brett says, his mother could be “depressed,” meaning very unhappy.
Molly says, “You know that Mom is always happy to hear good news about school. Do you have anything new to report?” meaning do you have anything new to tell her. Brett says, “I hadn’t thought of that (I hadn’t thought of that idea). I need to come up with something.” To “come up with something” means to think of something – a new idea.
Molly says, “Be patient,” in other words, don’t rush, don’t be in a hurry; be able to wait, be patient. “Wait for the right moment and then strike.” To “strike” usually means to attack someone, to do something without warning the other person. Molly, here, is using it somewhat in a humorous sense, telling Brett to wait until the right moment and then ask his mother. Molly says, “I speak from years of experience,” meaning I have many years of dealing with and talking with our mother, I know how things work with her. Brett says, “Right. Thanks.”
Now let’s listen to the dialogue again, this time at a normal speed.
[start of dialogue]
Brett: Do you know what kind of mood Mom is in?
Molly: Not really. Why?
Brett: I really need a raise in my allowance and I’m waiting for the right time to ask. She’ll be more likely to say “yes” if she’s not feeling too grouchy.
Molly: I wouldn’t count on this being a good time. She looked a little upset after getting off the phone with Aunt Teri.
Brett: Why?
Molly: Aunt Teri has been down in the dumps since Cousin Frank decided to take a job in Cambodia. He’s on cloud nine about this new job, but Aunt Teri is anxious about him moving so far away.
Brett: I see. Well, I’ve got to think of some way to cheer her up. It’s a lost cause if I ask her while she’s angry, on edge, or depressed.
Molly: You know that Mom is always happy to hear good news about school. Do you have anything new to report?
Brett: I hadn’t thought of that. I need to come up with something.
Molly: Be patient. Wait for the right moment and then strike. I speak from years of experience.
Brett: Right. Thanks.
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
mood – the way that a person feels at a particular time
* Brianna was in a bad mood after the dentist told her that she needed surgery.
allowance – a small amount of money that some parents give to their children each week
* Do you think that a $15 weekly allowance is too much for a 13-year-old girl?
grouchy – not happy; irritable; complaining
* Pauline seems grouchy. I haven’t seen her smile all day.
to count on – to rely on; to depend on; to assume that something will be a certain way
* You can count on the fact that it will rain while you’re in Oregon next month.
upset – worried, anxious, and angry; not calm
* Was Katie upset when you told her that you didn’t want her to go to the party?
down in the dumps – depressed; unhappy; sad
* Whenever Ray is feeling down in the dumps, he eats chocolate to make himself feel better.
on cloud nine – very happy; overjoyed
* Misty was on cloud nine when she learned that her first book was going to be published.
anxious – worried and nervous
* Brandon is anxious about his date this Friday, because he really likes the girl and he wants her to like him, too.
to cheer (someone) up – to make someone feel better; to do or say something that will make a sad person feel happy
* Terrence tried to cheer his roommate up after his girlfriend broke up with him by taking him to a bar to meet some new girls.
lost cause – something that is impossible and can’t be done; something that is futile
* Colum lost his wedding ring on the subway, and it seems like finding it was a lost cause.
angry – mad; strongly feeling that one doesn’t like something or someone
* They were very angry when their car was stolen.
on edge – nervous and excited about something
* Wade is on edge because he’s waiting for a phone call about whether he got the new job.
depressed – unhappy and sad, often for no reason
* The children were depressed for months after their dog died.
happy – pleased; satisfied; content
* Elizabeth was very happy when her boyfriend asked her to marry him.
patient – not rushed; not in a hurry; able to wait for a long time
* Matt is a good teacher because he’s very patient and he doesn’t get mad if a student doesn’t understand something the first time he explains it.
to strike – to attack; to do something without warning
* The mouse was running across the field when the cat, who had been watching him, struck.
Comprehension Questions
1. What does Molly mean when she says that Uncle Frank is “on cloud nine”?
a) His new address is number 9 on Cloud Street.
b) He will be flying a lot in his new job.
c) He is very happy about his new job.
2. Who is depressed?
a) Mom.
b) Aunt Teri.
c) Cousin Frank.
Answers at bottom.
What Else Does It Mean?
allowance
The word “allowance,” in this podcast, means a small amount of money that some parents give to their children each week: “Bobby asked his parents to raise his allowance from $5 to $7.” An “allowance” can also be money given to an employee for a specific purpose: “How much of a travel allowance do managers get at this company?” Sometimes an “allowance” is the amount of something that is allowed: “The baggage allowance on this flight is 50 pounds.” The phrase “to make allowances for (someone)” means to excuse someone’s behavior, even though it is normally inappropriate, because he or she has a problem or is in a difficult situation: “We need to make allowances for Kostas’ strange behavior, because he just found out that he has a serious illness.”
on edge
In this podcast, the phrase “on edge” means nervous and excited about something: “The actress always feels on edge right before her performances.” An “edge” is the side or outside line of something: “A box has 12 edges.” Or, “They want to build a home on the edge of town.” An “edge” is also the sharp side of a knife or similar object: “Be careful with that knife, because the edge is very sharp and you might cut yourself.” A “competitive edge” is something that a company does better than other companies do, and therefore is more successful: “Our company’s competitive edge is the creativity of its employees.” If something is “cutting-edge,” it is the newest or most advanced thing, especially in technology: “We sell the most cutting-edge computers and software.”
Culture Note
A “mood ring” is a large ring worn on one’s finger that changes color with one’s body temperature. People say that each color “indicates” (shows) the wearer’s mood. The rings are sold with a small piece of paper that lists all the colors and their “associated” (corresponding, which color goes with which mood) mood. Mood rings were very popular in the United States in the 1970s, and they are still worn by children and teenagers today.
If a mood ring is black, which is caused by the coldest temperature, it means that the wearer is very “tense” and “stressed out” (under a lot of pressure). If the ring is “slightly” (a little bit) warmer, it “turns” (becomes another color) brown or grey, meaning that the wearer is nervous, anxious, or “fearful” (afraid of something). An “amber” (a golden yellow-brown color) mood ring indicates that the wearer is a little bit nervous or anxious, or “uncertain” (undecided and not sure what to do).
A green ring is the normal color, and indicates that the wearer is calm, not under stress, and not very excited. A blue-green color means that the wearer is more excited, but still “somewhat” (more or less) relaxed. If the ring turns blue, then the wearer is relaxed, calm, and in a good mood. Finally, if the ring turns very dark blue or purple, which is caused by the highest temperature, then it means that the wearer is extremely happy and/or in love with “passionate” (very strong) romantic feelings.
Most Americans don’t really believe that a mood ring can indicate the wearer’s mood, but they are fun to play with, especially for children and teenagers.
Comprehension Answers
1 - c
2 - b