= 0332
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 332: Profit and Loss.
This is English as a Second Language Podcast episode 332. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. The Learning Guide contains all of the vocabulary, definitions, sample sentences, additional definitions not found on the audio episode, cultural notes, comprehension questions, and a complete transcript of this episode.
This episode is a dialogue between Dolores and Anton. They’re talking about the money that their company makes or doesn’t make. Let’s get started.
[start of dialogue]
Dolores: Manuel in accounting is supposed to help me with this report, but he called in sick today! I can’t believe my luck. He’s supposed to be training me in and he’s left me holding the bag.
Anton: Let me see if I can help.
Dolores: I’m supposed to use the information from this profit and loss statement to make some projections about the company’s future performance for our report, but I’m not sure what I’m doing. I need to plug in some numbers here, but I can’t make heads or tails of this.
Anton: Well, if you look at the top of the statement, you’ll see the top line, which shows the revenue the company brought in in the third quarter of this year. Is that what you need?
Dolores: Yes, I think so, but I also need to know our net income.
Anton: Here is the bottom line. That takes into account all of the revenue and expenses during the third quarter.
Dolores: That’s great, but I also need to know the gross profits and operating expenses.
Anton: Those are in this column. See?
Dolores: I guess all the information is here. I just needed to know where to look. Thanks. I couldn’t have figured it out without you.
Anton: It’s not that complicated. Hopefully, Manuel will be back tomorrow.
Dolores: Manuel? Who needs him!
[end of dialogue]
Our dialogue begins with Dolores saying to Anton, “Manuel in accounting (in the accounting department) is supposed to help me with this report, but he called in sick today!” He called up and said he wasn’t coming to work, that’s “to call in sick.” Dolores says, “I can’t believe my luck. He’s supposed to be training me in and he’s left me holding the bag.” “To train someone in” is a two-word phrasal verb in English, which means to help someone learn what he or she needs to know for a new job or a new position. “He’s being trained in as a manager” – he is receiving training as a manager. Dolores says Manuel left her “holding the bag.” This is an idiomatic expression; “to hold the bag,” or “to be left holding the bag” means to be responsible for something when other people don’t do their work. You have to do something because someone else didn’t do what they were supposed to do.
So, Dolores is “left holding the bag.” Anton says, “Let me see if I can help.” Dolores then explains, “I’m supposed to use the information from this profit and loss statement to make some projections about the company’s future performance.” A “profit and loss statement” is a report that shows how much money a company has made or lost over certain amount of time. So, you take all the money the company receives from selling its products or services, and you subtract the amount of money the company has spent on expenses, and the result is either a “profit,” meaning your company made money, or a “loss,” meaning your company lost money. This is sometimes called a “PNL statement,” or a “PNL” – profit and loss – “PNL.”
Dolores says she needs “to make some projections.” A “projection,” in this sentence, means a “forecast,” an estimate of how something will change over time. It’s a guess about what will happen in the future. You can use the verb “to project” in the same way: “I project that our company will have a profit,” or, “I’m projecting a profit for our company.” Here, she uses the noun “projection.”
Dolores says that she needs “to plug in some numbers here,” but she “can’t make heads or tails” of it. “To plug in something” is another phrasal verb in English; it means to put numbers into a formula or an equation; “to fill in the blanks,” we might say. “I need to plug in the numbers in my spreadsheet – my Excel spreadsheet to figure out if our company has made money or lost money.” That expression, “to plug in,” has a couple of different meanings; take a look at our Learning Guide for some additional explanations.
Dolores says she “can’t make heads or tails” of something. “To make heads or tails” means to be able to understand something, even if it’s just a little bit – a small amount – I understand a little. But, if you say, “I can’t make heads or tails of this,” you mean you can’t understand anything. The word “heads” and “tails” comes from a coin. A coin has two sides; one side is called “heads,” usually because there’s a picture – the head of some famous ruler from that country. In Great Britain, for example, there is a picture of the Queen. That would be the “heads” side of the coin; “tails” is the backside of the coin. But the expression “to make heads or tails of something” means to be able to understand something.
Anton says, “Well, if you look at the top of the statement, you’ll see the top line.” The “top line” means the total amount of money that the company received during a certain amount of time; it’s shown at the top of a profit and loss statement. This top line “shows the revenue the company brought in in the third quarter of this year.” The word “revenue” here just means “income,” the amount of money that the company received.
Anton says the top line “shows the revenue the company brought in (or received) in the third quarter of this year.” A “quarter” is 25% (percent) of something; in this case, a quarter means one fourth of the year – three months during the year. So, a year has four quarters: January, February, March is quarter one; April, May, June, quarter two; July, August, September, quarter three; October, November, December, quarter four. The exact meaning of the word “quarter” depends on the context; take a look at our Learning Guide for some additional explanations about how to use that word.
Anton says, “Is this what you need?” Dolores says, “Yes, I think so, but I also need to know our net income.” Your “net (net) income” is the money that you received minus the money that you spent, or the money – the revenue – earned minus – or taking away – the money you spent. It’s another word, really, for “profit.”
Anton then says, “Here is the bottom line.” We just talked about the “top line,” that’s on a profit and loss statement where you see the revenue for the company. The “bottom line” is whether the company made money or not. It’s the last line on a profit and loss statement; it shows the profit or the loss. We use this expression, “the bottom line,” also in general conversation to mean what is the final conclusion, what is the most important thing here. Here, it is the last line of the PNL statement.
Anton says the bottom line “takes into account all of the revenue and expenses during the third quarter.” “To take into account,” or “to take something into account,” is, yes, another phrasal verb in English; it means to consider, it means to include, in this case. So, it includes “all of the revenue and expenses (the costs that the company paid) during the third quarter.”
Dolores says, “That’s great, but I also need to know the gross profits and operating expenses.” On a profit and loss statement, the “gross (gross) profits” are the profits that you make before paying any taxes or interest on a loan. It’s the money that you receive minus the cost of things before the taxes and interest are included. The “operating expenses” are the costs that are needed to run a business. They’re not actually part of the product, so let’s say you’re making a car. Well, you need doors and wheels, a steering wheel, glass – you put all those together to make the car. Your operating expenses would be all the other things that you need in order to have a company. You have to pay for your rent; you have to pay for electricity and the phone, and so forth.
Dolores then says, “I guess all the information is here. I just needed to know where to look. Thanks. I couldn’t have figured it out without you.” “To figure out something,” or “to figure something out,” is a two-word, or phrasal verb meaning to think about something until you understand it – to be able to understand something. “I can’t figure this computer out” means I can’t understand how to use it.
Anton says, “It’s not that complicated,” meaning it’s not that difficult – it’s not that complex. He says, “Hopefully, Manuel will be back tomorrow.” Dolores says, “Manuel? Who needs him!” meaning she can now do it by herself. So basically, what happened here is that Anton trained in Dolores on how to write this report. So, Manuel doesn’t really have to do any of the work tomorrow – good idea he called in sick!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Dolores: Manuel in accounting is supposed to help me with this report, but he called in sick today! I can’t believe my luck. He’s supposed to be training me in and he’s left me holding the bag.
Anton: Let me see if I can help.
Dolores: I’m supposed to use the information from this profit and loss statement to make some projections about the company’s future performance for our report, but I’m not sure what I’m doing. I need to plug in some numbers here, but I can’t make heads or tails of this.
Anton: Well, if you look at the top of the statement, you’ll see the top line, which shows the revenue the company brought in in the third quarter of this year. Is that what you need?
Dolores: Yes, I think so, but I also need to know our net income.
Anton: Here is the bottom line. That takes into account all of the revenue and expenses during the third quarter.
Dolores: That’s great, but I also need to know the gross profits and operating expenses.
Anton: Those are in this column. See?
Dolores: I guess all the information is here. I just needed to know where to look. Thanks. I couldn’t have figured it out without you.
Anton: It’s not that complicated. Hopefully, Manuel will be back tomorrow.
Dolores: Manuel? Who needs him!
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse. Thank you Lucy!
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
to train (someone) in – to help someone learn what he or she needs to know for a new job or position
* As the restaurant manager, you will be training in all of the new employees.
to hold the bag – to be responsible for something when others do not do their work; to have to do something
* Benny promised to help wash the dishes, but then he went outside to play after dinner and left his sister holding the bag.
profit and loss statement – a report that shows how much money a company has made or lost over a certain period of time
* Did you read the company’s profit and loss statement before you decided to invest in it?
projection – forecasts; estimates of how something will change numerically over time; guesses about how much of something there will be in the future
* The company’s sales projections for next year are almost twice as much as we’re selling right now.
to plug in (something) – to fill in the blanks; to put numbers into a formula or equation
* If your answer was x=8, try plugging in 8 wherever you see an x in the original problem. If the equation still makes sense, then your answer was correct!
to make heads or tails of (something) – to be able to understand something, even a little bit
* They were speaking Greek, so we weren’t able to make heads or tails of their conversation.
top line – the total amount of money received during a certain period of time, shown at the top of a profit and loss statement
* The company had a top line of $50 million, but that is before you consider how much it had to pay to its workers and to other companies.
revenue – money received; money earned; income
* If we sell 2,000 pieces at $45 each, we will have revenue of $90,000.
quarter – one-fourth of a year; a three-month period from January-March, April-June, July-September, or October-December
* Toy companies have their highest sales in the fourth quarter, when many people buy holiday presents for children.
net income – money earned minus money spent; profit; the money that a company makes after it has paid everything it needs to pay
* Even though we had great sales last year, our expenses were so high that we had very little net income.
bottom line – profit; net income; money earned minus money spent; the money that a company makes after it has paid everything it needs to pay
* The company president doesn’t want to know all the details. He just wants to see the bottom line and know how much money the company is making.
to take (something) into account – to consider; to think about; to include
* A South American country seems like an inexpensive place to go on vacation, but once you take airfare into account, it is actually very expensive.
expense – cost; money paid by a person or company to get something
* Our office supply expenses include money to buy paper, envelopes, and pens.
gross profits – profits before paying interest and taxes; the money that a company receives, minus the cost of the things that it makes or provides, before it pays interest and taxes
* Our gross profits were $20,000, but after we paid taxes there was almost nothing left.
operating expenses – costs that are needed to run a business, but are not actually part of the company’s products and/or services, such as rent, electricity, phone, and administrative and marketing costs
* The company president decided that operating expenses were too high, so he made the company move to a smaller, less expensive building.
to figure (something) out – to think about something until one understands it; to be able to understand something
* It took Ghiza a long time to figure out why her mother was angry with her.
complicated – complex and difficult; not simple; not easy to understand; confusing
* Which is more complicated: learning to use a computer or understanding women?
Comprehension Questions
1. What does Dolores mean by saying, “he’s left me holding the bag”?
a) She’s tired of holding her purse while Manuel is away.
b) She has to keep the bag with the company’s profits.
c) She is frustrated to have all the responsibility for the report.
2. What is at the top of the profit and loss statement?
a) Income.
b) Expenses.
c) Bottom line.
Answers at bottom.
What Else Does It Mean?
to plug in
The phrase “to plug in (something),” in this podcast, means to fill in the blanks, or to put numbers into a formula or equation: “The computer model didn’t work correctly until the scientists plugged in variables for the weather.” The phrase “to plug in (something)” also means to connect a piece of electrical equipment to an electrical outlet in a wall, so that it has power: “Is the coffee maker plugged in?” The phrase “to plug (something) up” means to clog, or to prevent liquid or something else from moving past another object: “Throw away the small pieces of food on the plates, or they’ll plug up the sink while you’re washing the dishes.” Finally the phrase “to plug away at (something)” means to continue working on something that is very difficult: “Calculus might seem difficult at first, but if you plug away at it, it will get easier.”
quarter
In this podcast, the word “quarter” means one-fourth of a year, or a three-month period: “Every American has to pay taxes in the second quarter of the year.” The word “quarter” can mean one-fourth or 25% of anything: “This restaurant sells quarter-pound hamburgers, but that’s too much meat for me.” When talking about time, a “quarter” is 15 minutes: “I’ll meet you at the park at a quarter to four, or 3:45.” A “quarter” is also a coin worth $0.25: “I can remember when telephone calls cost only a quarter.” Sometimes a “quarter” is a neighborhood, or a part of a city: “How can I get to the Italian quarter from here?” In the plural, “living quarters” are a place to live: “Are your new living quarters bigger or smaller than your old apartment?”
Culture Note
An “accountant” is a person who “records” (writes down officially) financial “transactions” (times when money received and paid out) and creates financial reports. Most working accountants in the United States are “CPAs,” or “certified public accountants” who have passed an exam known as the Uniform Certified Public Accountant Examination and meet their state’s “requirements” (things that must be done) for education and experience.
People who want to become accountants should enjoy working with numbers and be very “detail-oriented” (pay attention to small pieces of information). They need to receive an undergraduate degree in accounting, or a degree in business with many accounting courses. Depending on which state they live in, they might need to get additional education and/or work in the “field” (area) of accounting for a certain period of time. People usually need at least 150 hours of accounting education before they can take the exam. Once they meet all the requirements, then they can take the two-day exam to become “certified” (recognized by an organization as being able to work in a certain profession) .
CPAs have many “career options” (choices about where one wants to work and what one wants to do). They may choose to work in public, government, or management accounting, as well as internal “auditing,” which is the practice of checking a company’s financial records to make sure that they are correct. Some accountants specialize in “tax preparation” (helping people and companies prepare their tax forms), “estate planning” (helping people decide where and to whom their money should go when they die), “mergers and acquisitions” (helping companies when they buy other companies), or many other areas.
Comprehension Answers
1 - c
2 - a