= 0337
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 337: Reading Comic Books.
This is English as a Second Language Podcast episode 337. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
You can visit our website at eslpod.com. You can download the Learning Guide for this episode to help you learn your English even faster. You can also take a look at our ESL Podcast Blog, where several times a week we put up some additional information to help you learn English. We also have an ESL Podcast Store, where you can buy some of our specialty courses in business and daily life English.
The topic for this episode is “comic books,” things that are written with words and pictures. We’ll talk a little bit about comic books in the United States during our discussion, and who reads them, and who doesn’t. Let’s get started.
[start of dialogue]
Lee: What are you reading?
Stan: It’s a graphic novel.
Lee: Graphic novel? You mean a comic book? I thought you were too old for that sort of thing.
Stan: For your information, this is a graphic novel and it’s a literary art form. Graphic novels are written for mature audiences, not kids.
Lee: Really? I don’t know anything about comic books. I like reading the comic strips in the newspaper, but I’ve never read an entire comic book before.
Stan: You might want to check these out. Look at this bound collection, for instance. It has a storyline that’s as complex as a novel, and each panel is a work of art.
Lee: It is pretty impressive looking. I’m not that interested in superheroes, though.
Stan: The Superman and Spider-man comic books are great, but the graphic novels today are even more sophisticated. Some of them are still serialized like the old comic books, but many of them are self-contained like this one.
Lee: Are there ones without too much fighting?
Stan: There are as many genres of graphic novels as there are movies or books. I’m really surprised that someone who likes to read as much as you do knows so little about graphic novels.
Lee: I’ve come across them in bookstores before, but I had a preconceived notion that they were for kids.
Stan: I guess you were wrong.
Lee: I guess I was. There’s a first time for everything.
[end of dialogue]
Our dialogue between Stan and Lee begins by Lee saying, “What are you reading?” and Stan says, “It’s a graphic novel.” A “graphic novel” is a term we use to describe basically a comic book that is written for adults. This term became popular, in the last 15 years or so, to describe books that were written at a more sophisticated level. In the United States when you talk about comic books, people think about the things that are written for small children, and that’s American’s association with comic books. So you almost never, for example on a bus or a train, will see an adult reading a comic book. Graphic novels are types of comic books, but they’re considered more serious and more sophisticated.
Lee says, “Graphic novels? You mean a comic book? I thought you were too old for that sort of thing.” Notice this idea that comic books are for children. Stan says, “For your information” – we use that expression at the beginning of a sentence, “for your information,” to mean I am going to correct what you just said, basically. You say it when you are perhaps a little upset – a little angry. Stan says, “For your information, this is a graphic novel and it’s a literary art form.” “Literary” is an adjective meaning related to literature: “The poems of the American poet Edgar Allan Poe are considered literary masterpieces” – good poems. “Art form” is a type of art, so “literary art form” is a type of art related to literature.
Stan says, “Graphic novels are written for mature audiences, not kids.” A “mature audience” can mean a couple of different things. Here it just means adults who are older, not children. Sometimes we’ll talk about someone being “more mature” to mean that they are more emotionally and socially developed or sophisticated. “Mature” is also sometimes used to refer to certain books or movies that are not appropriate for young children or for teenagers because of the topic or the language or violence, or perhaps even sexual content of the movie or book.
So, graphic novels are written for mature audiences. Lee says, “Really? I don’t know anything about comic books. I like reading the comic strips in the paper.” A “comic strip” is a series of about four frames – four boxes – that have funny drawings and tell a very small or short joke, and in the newspaper you can see many different comic strips. They’re popular among children and adults, more among children than adults, probably. When I was younger – I’m still young, but when I was younger I used to read comic strips in the newspaper every morning while I ate my cold cereal and milk.
Stan says, “You might want to check these out (you might want to look at these). Look at this bound collection, for instance.” “To be bound” (bound) means that something is held together at one edge. Usually we are talking about a book; that part of a book where the paper is glued or somehow put together is called the “binding.” But, “bound” is, in this case, referring to the edge of the book – the book has a “binding.”
“It has a storyline that is as complex as a novel,” Stan says. The “storyline” is the main story in the book or the novel or the movie or the play. “What’s the storyline?” – what is the basic story? He says the storyline “is as complex an as a novel.” “Complex” here means complicated, the opposite of simple – not simple. Stan says, “each panel is a work of art.” The different sections in a comic book or in a comic strip are called “panels” (panels). Both the word “panel” and the word “bound” have additional meanings in English; take a look at our Learning Guide for some additional explanations.
Stan says, “each panel is a work of art.” When someone says “it’s a work of art,” they mean it’s very artistic, imaginative, creative; something that you should respect because it’s very beautiful. Lee, says, “It is pretty impressive. I’m not that interested in superheroes, though.” A “superhero” is an imaginary, made-up person with special powers: Spider-man and Superman are superheroes; that’s an example. “Jeff McQuillan is a superhero, but only in his own mind!”
Stan says that “The Superman and Spider-man comic books are great (superhero comic books), but the graphic novels today are even more sophisticated,” he says. “Sophisticated” means, again, not simple, not common, more advanced, more elegant. “Some of them are still serialized like the old comic books,” he says. Some of the comic books are serialized. When we say a book or a comic book is “serialized,” we they publish it in sections: one week will be the first chapter, the next week will be the second chapter, and so on. This was a very popular way of publishing books for many years, not as popular recently, although The New York Times Magazine on Sundays has usually one or two serialized stories – small chapters of stories over many weeks.
Stan says that many of the comic books are self-contained. “Self-contained” means all in one piece. That’s how you typically buy a book – it’s “self-contained,” it’s not serialized.
Lee says, “Are there ones without too much fighting?” – are there comic books without too much fighting? Stan says, “There are as many genres of graphic novels as there are movies or books.” A “genre” (genre) is a French word – we pronounce it “genre” in English, which means a specific type or style of literature or of movies or of music. In classical music, we have the genre of baroque music and of romantic music, and something we call classical music, which is in between the baroque and the romantic. Those are “genres.”
“There are many genres of graphic novels,” Stan says, “I’m really surprised that someone who reads as much as you do knows so little about graphic novels.” Lee says, “I’ve come across them in bookstores before.” “To come across them” means I’ve found them although I wasn’t looking for them – almost by accident. “But,” Lee says, “but I had a preconceived notion that they were for kids.” When something is “preconceived,” that means you’ve decided about it before you even have any experience with it – before you really know the truth: “He had a preconceived idea about what Los Angeles is; he thought it would be ugly and polluted and crowded.” That’s true in some places, but not in all places. She has "a preconceived notion." A “notion” is just another word for an idea, a concept, an opinion about something.
Stan says, “I guess you were wrong.” Lee says, “I guess I was. There’s a first time for everything.” We use that expression as a joke: “there’s a first time for everything” means that you shouldn’t be surprised by anything because anything is possible, even things that are very unexpected. Lee is saying here that she never has made a mistake before, so “there’s a first time for everything.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Lee: What are you reading?
Stan: It’s a graphic novel.
Lee: Graphic novel? You mean a comic book? I thought you were too old for that sort of thing.
Stan: For your information, this is a graphic novel and it’s a literary art form. Graphic novels are written for mature audiences, not kids.
Lee: Really? I don’t know anything about comic books. I like reading the comic strips in the newspaper, but I’ve never read an entire comic book before.
Stan: You might want to check these out. Look at this bound collection, for instance. It has a storyline that’s as complex as a novel, and each panel is a work of art.
Lee: It is pretty impressive looking. I’m not that interested in superheroes, though.
Stan: The Superman and Spider-man comic books are great, but the graphic novels today are even more sophisticated. Some of them are still serialized like the old comic books, but many of them are self-contained like this one.
Lee: Are there ones without too much fighting?
Stan: There are as many genres of graphic novels as there are movies or books. I’m really surprised that someone who likes to read as much as you do knows so little about graphic novels.
Lee: I’ve come across them in bookstores before, but I had a preconceived notion that they were for kids.
Stan: I guess you were wrong.
Lee: I guess I was. There’s a first time for everything.
[end of dialogue]
This episode was written by our superhero scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
graphic novel – a long and complex story where the words of the story are printed within a series of drawings that show what is happening, usually written for adults
* Some people who don’t enjoy reading regular books like to read graphic novels.
comic book – a short and simple story where the words of the story are printed within a series of drawings that show what is happening, usually written for children
* Karrie had a lot of Wonder Woman comic books when she was a child.
literary – related to literature; related to things that are written and read
* Many people think that Edgar Allen Poe was a literary genius.
art form – a type of art, such as writing, painting, drawing, music, or dance
* Do you think that rap music is an art form?
mature audience – a group of older adults whom one writes or performs for
* This movie is for mature audiences and I don’t plan to take my kids to see it.
comic strip – a series of about four boxes with funny drawings and some words that are put next to each other in a rectangular shape and published in a newspaper or magazine every day or week
* The Peanuts comic strip is very popular and is known for its characters like Charlie Brown and Snoopy.
bound – held together at one edge, especially when referring to the pages of a book
* This book wasn’t bound very well, so some of the pages are falling out.
storyline – the main story in a book, novel, movie, or play
* The teacher asked the children to read the book at home, and the next day, he asked them if they liked the general storyline.
complex – complicated; not simple
* It took the scientists several hours to explain their complex calculations.
panel – one square section with a drawing and some words in a comic book or graphic novel
* On Sundays, each Doonesbury comic strip has at least six panels.
work of art – something that is artistic, imaginative, and creative, and deserves respect for those reasons
* The Mona Lisa is one of the world’s most famous works of art.
superhero – an imaginary person with special powers, such as the ability to fly or see through walls
* Which superhero do you like better: Superman or Spider-Man?
sophisticated – elegant; refined; advanced; not simple or common
* Computer technology becomes more sophisticated every day!
serialized – in a series; as one of many parts of something, especially when referring to TV shows or books
* The movie was too long to show all at once, so the TV channel serialized it into five parts, showing one each night.
self-contained – as one piece; without additional parts; as a whole
* The lessons in this book are self-contained, so that you can study each lesson independently, without needing to refer to the other lessons for more information.
genre – a specific style of literature, movies, or music
* What genre of movies do you like? Horror or comedy?
preconceived – something that has been decided before one has all the information or experience needed to really know the truth
* I had the preconceived idea that everyone in Texas knew how to ride a horse, but when I went there, I realized that this isn’t true.
notion – idea; concept; opinion about something
* Where did you get the notion that your great-grandparents were from Germany? They were all born in the U.S.
There’s a first time for everything – a phrase used to show that one shouldn’t be surprised by anything, because anything is possible and even things that are very unexpected can happen sometimes
* Beatrice always says that she hates country music, but last night she went to a country music concert. There’s a first time for everything!
Comprehension Questions
1. According to Stan, which of the following statements is true?
a) Graphic novels are written for children.
b) Graphic novels are often violent.
c) Graphic novels are artistic.
2. Why hasn’t Lee ever bought a graphic novel?
a) Because she thought they were for children.
b) Because she didn’t like the genre.
c) Because she thought they were too sophisticated.
Answers at bottom.
What Else Does It Mean?
bound
The word “bound,” in this podcast, refers to the way that the pages of a book are held together at one end: “This book is bound in beautiful brown leather.” The phrase “bound to do (something)” or “bound to be (something)” means that something is very likely or probable: “You’re bound to see Amaru at the meeting.” The phrase “to be bound by (something)” means to have to do something, usually because of a law, rule, or regulation: “We are bound by law to pay our bills every month, or else we have to pay even more later as a penalty.” Finally, when talking about transportation, the phrase “bound for (somewhere)” is used to show where a car, train, bus, or plane is going: “This train is bound for New York City, but it will stop in Baltimore first.”
panel
In this podcast, the word “panel” means one square section with a drawing and some words in a comic book or graphic novel: “Alina thought the comic strip was so funny that she cut out the panels and taped them to her computer.” A “panel” is also a square or rectangular piece of glass or wood that forms part of a larger piece: “Their living room window has eight panels of colored glass.” Sometimes a “panel” is a group of experts who discuss a topic, often in response to questions from the audience: “The university organized a panel of six leading experts to discuss the future of Latin American economies.” Finally, a “panel” can be a large, flat piece of metal or plastic that has many controls and/or that displays information: “The car’s instrument panel is showing that we’re almost out of gas.”
Culture Note
Most U.S. comic books are “published” (printed and distributed) by large publishing companies. However, beginning in the 1960s, people began to make “underground comics,” or “comix,” which focused on the “counterculture” (things that are not generally accepted by society as a whole, but are very popular among many young people). Most comix came from artists in San Francisco, but some were made in New York, Illinois, and Texas.
Many comix are about “topics” (main ideas) related to drugs and sex, or that are against the government. In many ways, underground comics are similar to underground movies that were produced in response to Hollywood movies. They have an “anti-establishment” (against the way that society normally does things) attitude and try to cover topics that aren’t usually seen in more traditional works of art.
Normally comic books are produced by many people, including the writer, editor, drawer, “inker” (the person who colors the drawings), and “letterer” (the person who writes the words). However, comix are often made by just one person. This means that it can take a very long time for comix to be finished, so they are often shorter and/or serialized.
Many of the comix were printed only once and with a small “print run” (the number of copies printed at one time). Some of these have become “valuable” (worth a lot of money) “collector’s items” (things that people want to buy and keep, because they want to have many similar objects, like stamps or dolls). Other comix became very popular and were published in large print runs, so they are still easy to find today.
Comprehension Answers
1 - b
2 - a