= 0969
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 969 – Using Electronics on Airplanes.
This is English as a Second Language Podcast episode 969. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there and become a member of ESL Podcast. You could also take a look at our ESL Podcast Store, as well as our ESL Podcast Blog. And why not like us on Facebook at facebook.com/eslpod.
This episode is a dialogue about using electronic devices – things like phones and games and computers – on airplanes. Let’s get started.
[start of dialogue]
Flight attendant: I’m sorry, sir, but all passengers need to turn off their portable electronic devices for takeoff, so you’ll need to turn off your laptop.
Alec: I just need to finish one last email.
Flight attendant: Sir, we can’t take off until you turn that computer off.
Alec: Fine. It’s off. Why all the fuss, anyway?
Flight attendant: It’s regulations. Signals emitted by electronics may interfere with the plane’s communication systems or navigation.
Alec: All right.
Flight attendant: Sir, you’ll also need to turn off your tablet computer and your cell phone. Those are also considered portable electronic devices.
Alec: You’ve got to be kidding me. You mean I have to sit here twiddling my thumbs while I wait for the plane to take off? I thought the FAA eased up on those regulations.
Flight attendant: I’m afraid not, sir. Please power down all of your devices so we can proceed with takeoff.
Alec: Okay, fine. What am I suppose to do until we get the all clear to use our electronics again?
Flight attendant: Perhaps you could read a magazine.
Alec: That’s what I was doing on my tablet before you made me turn it off.
Flight attendant: Perhaps you could take a flying leap out the window.
Alec: What did you say?
Flight attendant: I said, “Look at that luggage heap out the window.”
[end of dialogue]
Our dialogue begins with the flight attendant talking to one of the passengers, named Alec. A “flight attendant” is an employee of the airline who brings you food and things to drink during your flight when you are traveling in a plane from one place to another. Flight attendants are also responsible for the safety of the aircraft – to make sure everyone is sitting down when the plane takes off and lands, for example. A “passenger” is a person who flies in an airplane. The flight attendant says to Alec, one of the passengers, “I’m sorry, sir, but all passengers need to turn off their portable electronic devices for takeoff, so you’ll need to turn off your laptop.”
A “portable electronic device” is something that you can bring from one place to another, something that is small and easily moved. A “device” (device) is a small piece of equipment, often an electronic piece of equipment. “Electronic” refers to things that run on electricity and often have some sort of computer inside of them – something like a cell phone or a tablet, an iPad, a computer, and so forth. All of these would be portable electronic devices. They’re things that you can take with you. You can put in a small bag and carry them.
The flight attendant is telling Alec he has to turn off his portable electronic devices for takeoff. “Takeoff” (takeoff) is when the plane leaves the ground. Although the rules are changing for this, for a long time you could not use any sort of electronic devices for the first 10 minutes or so of your flight – when the plane was taking off, and then again at the end of your flight when the plane was landing. That’s what the flight attendant is talking about here. She’s telling Alec he has to turn off his laptop. A “laptop” (laptop) is also called a “notebook computer.” It’s a very small computer that usually folds up like a book so that you can carry it more easily.
Alec says, “I just need to finish one last email.” The flight attendant says, “Sir, we can’t take off until you turn that computer off.” The flight attendant is telling Alec that the plane can’t leave until he turns off his computer. Alec says, “Fine. It’s off.” Notice the way he says “fine” indicates that he’s angry. Even though “fine” normally means okay, it’s clear Alec is not happy.
He says, “Why all the fuss anyway?” “Fuss” (fuss) can be used in a couple of different ways. Here, it means: Why all of the interest? Why all of the excitement? Why are we making such a big deal of this particular situation? “To make a fuss” means to cause problems or to get excited about something. Some people, when they complain about something, make a fuss. They yell and they get angry and they get very excited. That’s one meaning of “fuss.”
The flight attendant says, “It’s regulations,” meaning the reason is that we have rules – that is, regulations – about using portable electronic devices on airplanes. She says, “Signals emitted by electronics may interfere with the plane’s communications systems or navigation.” A “signal” (signal) is an electronic message. “Emitted” (emitted) means produced or sent out. Electronics sometimes send out signals – especially, for example, a cell phone. These signals, according to the flight attendant, “may interfere with the plane’s communications systems.” “To interfere” with something is to create problems for something, to prevent something from doing what it is supposed to do.
“Communications systems” are the radios and computers that the plane uses to communicate with other planes and with the people on the ground. “Navigation” (navigation) refers to how you get from one place to another. Your “navigation systems” are the systems that tell the plane where to go. Maps and other electronic instruments are used in navigating the plane – in getting the plane to go from one place to another, in making sure the plane goes to the right place. If you’re taking a plane to Chicago and the plane instead goes to Dallas, you won’t be very happy.
Alec says “All right,” meaning okay. The flight attendant says, “Sir, you’ll also need to turn off your tablet computer and your cell phone.” Your “tablet (tablet) computer,” more commonly nowadays called, simply, your “tablet,” is an electronic device that does a lot of the things that a computer does, but is smaller and usually doesn’t have a keyboard. It doesn’t have a place for you to type other than the actual tablet itself. It depends on the tablet you have. iPads, for example, are tablet computers. They’re computers in the form of a tablet.
The flight attendant tells Alec to turn off his tablet and his cell phone. “Those are also considered portable electronic devices,” she says. Alec says, “You’ve got to be kidding me.” That expression, “You’ve got to be kidding me,” is when you are very surprised at what someone is saying. It may even indicate that you dis agree with what a person is saying or you think that what a person is saying is wrong.
Alec says, “You mean I have to sit here twiddling my thumbs while I wait for the plane to take off?” “To twiddle (twiddle) your thumbs (thumbs)” means to be bored and have nothing to do. Literally, it means to put your hands together and move your thumbs around each other very quickly. “To twiddle your thumbs” means to sit around and do nothing, in this case.
Alec says, “I thought the FAA eased up on those regulations.” The “FAA” in the United States is the “Federal Aviation Administration.” It’s the U.S. government agency that takes care of regulating and making rules for airplanes. “To ease (ease) up on” something means to do less or use something less. The FAA easing up on regulations would mean the FAA is no longer enforcing – no longer telling people they have to follow the regulations – or changing the regulations to make things easier.
Alec is saying that the FAA has eased up on the regulations – they’ve changed the rules on things like using portable electronic devices on airplanes. The flight attendant says, however, “I’m afraid not, sir. Please power down all of your devices so we can proceed with takeoff.” “To power down” something means to turn it off, especially something that is running on electricity.
Alec says, “Okay, fine. What am I supposed to do until we get the all-clear to use our electronics again?” The term “all-clear” (clear) refers to a signal that you are given, a message that is communicated to you that indicates that what you could not do before, you can now do – that the situation has changed so that you are now able to do something that you were not able to do before – in this case, to use electronic devices. The flight attendant says, “Perhaps you could read a magazine.” Alec said, “That’s what I was doing on my tablet before you made me turn it off.” The flight attendant is referring, of course, not to an electronic magazine, but to a paper magazine.
She says, “Perhaps you could take a flying leap out the window.” “To take a flying leap” (leap) is a very rude informal expression used to tell someone to leave or to go away. “You can take a flying leap” is something you would say to someone who perhaps did something wrong or made you angry and now you want that person to leave. It’s an insulting informal phrase. Alec says, “What did you say?” He can’t believe what the flight attendant just told him, since flight attendants are not supposed to be rude to their customers.
So the attendant changes what she just said – pretends as though she had said something else. She says, “I said, look at that luggage heap out the window.” A “heap” (heap) is a large pile of something, a large number of objects that are sitting one on top of the other. When they put your luggage, your bags, into the bottom of the plane, usually they come out on a big cart, a big truck, and the bags are all put one on top of the other in a large pile or a large heap.
The flight attendant is changing what she said so that Alec doesn’t get angry. She’s pretending that she said, “Look at that luggage heap out the window” rather than “Take a flying leap out the window,” which is what, of course, she actually said. The flight attendant is not very happy with Alec, since Alec is causing all sorts of problems on the airplane.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Flight attendant: I’m sorry, sir, but all passengers need to turn off their portable electronic devices for takeoff, so you’ll need to turn off your laptop.
Alec: I just need to finish one last email.
Flight attendant: Sir, we can’t take off until you turn that computer off.
Alec: Fine. It’s off. Why all the fuss, anyway?
Flight attendant: It’s regulations. Signals emitted by electronics may interfere with the plane’s communication systems or navigation.
Alec: All right.
Flight attendant: Sir, you’ll also need to turn off your tablet computer and your cell phone. Those are also considered portable electronic devices.
Alec: You’ve got to be kidding me. You mean I have to sit here twiddling my thumbs while I wait for the plane to take off? I thought the FAA eased up on those regulations.
Flight attendant: I’m afraid not, sir. Please power down all of your devices so we can proceed with takeoff.
Alec: Okay, fine. What am I suppose to do until we get the all clear to use our electronics again?
Flight attendant: Perhaps you could read a magazine.
Alec: That’s what I was doing on my tablet before you made me turn it off.
Flight attendant: Perhaps you could take a flying leap out the window.
Alec: What did you say?
Flight attendant: I said, “Look at that luggage heap out the window.”
[end of dialogue]
Our scriptwriter does not sit around here at ESL Podcast twiddling her thumbs. No, she works hard to produce the wonderful dialogues that we listen to. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
portable electronic devices – small machines that can be carried easily, especially notebook computers, tablets, cell phones, and personal DVD players
* The kids aren’t allowed to take any portable electronic devices to summer camp, because they’re supposed to be enjoying nature.
takeoff – the moment when an airplane leaves the ground and begins to fly
* Justin was very nervous during takeoff and he gripped the armrests tightly.
laptop – a notebook computer; a portable computer where the screen folds down over the keyboard
* Small, lightweight laptops are good for traveling, but it can be difficult to use such a small keyboard and screen.
fuss – trouble; worry; excitement; involvement
* Why is there so much fuss about R-rated movies? It seems like most teenagers have seen them, and they’re fine.
regulations – rules and policies that people must follow
* The USDA has created many regulations that are supposed to keep America’s food supply as safe as possible.
signal – a message or data sent from a machine
* If these signals start flashing red, it means there’s a problem with the space shuttle.
to emit – to produce or send out, usually a sound or a light
* A weird sound is being emitted from the car’s engine, so we’re going to take it to the mechanic.
to interfere with – to become involved and create problems; to become an intrusion or obstacle
* It must be awful to have a mother-in-law who interferes with your marriage that much!
communication system – a group of processes, procedures, and networks in which people and/or machines exchange information
* This is a top-secret communication system, so everyone who connects to it has to have their own password.
navigation – the practice of reading maps and instruments to determine where one is and how to go where one wants to go
* As phone navigation systems improve, fewer people are using maps to get around big cities.
tablet – a small electronic device that performs many of the same functions as a computer, but it smaller, lightweight, and flat
* This little tablet can display the content of thousands of books, magazines, and newspapers.
to twiddle (one’s) thumbs – to be bored and have nothing to do; literally to hold one’s hands together and move one thumb (shortest and widest finger) around the other very quickly
* How can you just sit there twiddling your thumbs when there’s so much work to be done?
FAA – Federal Aviation Administration; the U.S. government agency responsible for regulating aviation (flight)
* What kind of FAA approvals would we need to expand the local airport?
to ease up – to relax and become less controlling over something
* Some of the parents are saying that the teacher should ease up and not give so much homework to the youngest students.
to power down – to shut down a computer or another machine that needs a little bit of time to turn off completely
* Normally it just takes a few seconds to power down the computer, but right not, it’s installing some new updates, so it might take awhile.
all clear – a signal showing that something is permissible, that one is allowed to do something, or that some danger has passed and everything is safe again
* The soldiers have to wait for the all clear signal from the general before they leave their positions.
to take a flying leap – a rude, informal phrase used to tell someone to leave or go away
* He is so annoying! I wish we could just tell him to take a flying leap.
heap – pile; mound; a large number of objects that are resting on top of each other in an unordered pile
* All the dirty clothes were thrown into a heap in the laundry room.
Comprehension Questions
1. Which of these devices is the largest?
a) A laptop.
b) A tablet computer.
c) A cell phone.
2. What does the flight attendant mean when she says, “Perhaps you could take a flying leap out the window”?
a) She wants him to enjoy the view during takeoff.
b) She wants him to switch to a window seat.
c) She wants him to go away and stop bothering her.
Answers at bottom.
What Else Does It Mean?
tablet
The word “tablet,” in this podcast, means a small electronic device that performs many of the same functions as a computer, but it smaller, lightweight, and flat: “Reading a book on a tablet is convenient, but it isn’t the same as holding a book and turning the pages.” The word “tablet” also refers to a pad of paper, or a stack of paper where all the pages are glued together or held together at the top: “Please pass me that tablet so I can write down the phone number before I forget it.” When talking about medicine, a “tablet” is a small, round, hard pill that one swallows, usually without chewing: “Take two of these tablets with food every four to six hours.” Finally, a “tablet” is a flat piece of stone with words “engraved” (carved) into it: “There is a beautiful stone tablet showing Mary and Jesus in the churchyard.”
to power down
In this podcast, the phrase “to power down” means to shut down a computer or another machine that needs a little bit of time to turn off completely: “If you don’t power down your computer correctly, you might lose the files you were working on.” The phrase “to power (something) up” means to turn on a machine and make it start working: “We just powered up the copier, so it needs a few minutes to warm up before it can make copies.” Finally, the phrase “power nap” refers to a short period of sleep, usually just a few minutes, that makes someone feel rested and better able to make decisions: “A quick power nap during the lunch break can make it a lot easier to focus on work during the afternoon.”
Culture Note
FAA Regulations on Electronics
For many years, the FAA has “banned” (not allowed) the use of portable electronic devices during takeoff and “landing” (the moment when an airplane leaves the air and begins traveling on the ground). But in late 2013, the FAA “issued” (released) a new “ruling” (decision; regulation) stating that passengers may use electronic devices during all parts of a flight, including takeoff and landing, even with a “Wi-Fi” (wireless Internet) connection.
In the past, the FAA believed that signals from electronic devices might interfere with airplane systems needed for the safe navigation and communication. But research was “casting doubt on” (making people question whether something was true) these ideas, and “business travelers” (people who travel for work) were becoming increasingly “discontent” (unhappy) with the restrictions on their ability to work while flying.
Under the new ruling, each airline may choose if and when it will allow passengers to use their devices during takeoff and landing, but most airlines are expected to “embrace” (be eager to have or do) the opportunity to improve customer satisfaction. Airlines may offer Wi-Fi within the airplane, which would allow passengers to use programs that require data exchange, such as email programs or web surfing.
Cell phones are still “prohibited” (not allowed) on flights. However, if the airlines offer Wi-Fi, passengers might be able to place calls using Internet-based phone programs, although there are concerns that this will make the flying experience less pleasant for the other passengers who have to listen to the calls.
Comprehension Answers
1 - a
2 - c