= 1000
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as Second Language Podcast number 1,000 – Reaching a Milestone.
This is English as a Second Language Podcast episode 1,000. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. I thought we’d do something a little special in the introduction to this one-thousandth episode. This is a dialogue between Jeff and Lucy about reaching a milestone. Let’s get started.
[start of dialogue]
Jeff: Well, we’ve reached a milestone.
Lucy: Yup, it’s been a long haul, but we’ve finally made it. Did you ever think we’d get here?
Jeff: I admit I had my doubts. At the beginning, I was really dubious that this venture would pan out. I thought that our prospects were iffy, at best.
Lucy: Me, too. We didn’t have an auspicious start, but we had a turning point after a few months of grinding out the work, day in and day out.
Jeff: So, what should we do now?
Lucy: I think we both deserve a celebratory drink, a toast to our achievements . . . so far.
Jeff: That sounds good. Then what?
Lucy: Put our noses back to the grindstone?
Jeff: I was afraid you were going to say that!
[end of dialogue]
We begin this episode with Jeff – that’s me – saying to Lucy, “Well, we’ve reached a milestone.” A “milestone” (milestone) is some significant event or achievement that indicates that you are making progress towards some goal. We often use this term in business nowadays, when talking about project management or project planning.
When you have a big project, there are many things you have to do, many things you have to accomplish. Typically, you will divide up the different things you need to do and put them on a schedule so that, for example, by next Friday you will have completed this task, and by the Friday after that you will have completed that task, and so forth. These are milestones that you are setting up, that you are establishing, that you want to reach by a certain date or day.
I begin the dialogue by saying that “we have reached a milestone.” Lucy says, “Yup.” That’s an informal way of saying “yes” or “yeah.” “Yup (yup), it’s been a long haul but we’ve finally made it.” A “long haul” (haul) is a long and difficult or challenging period of time that you have to go through in order to reach your goal, to reach your objective, or in this case, to reach your milestone of 1,000 episodes, of course.
Lucy says, “It’s been a long haul” – it’s been a difficult journey, it’s been a long journey – but we have “made it,” she says. “We’ve finally made it.” “To make it” means to achieve your goal, to accomplish what you wanted to accomplish, to reach the milestone in your project as you are making progress towards the final goal or objective.
Lucy says, “Did you ever think we’d get here?” She’s asking me if I ever thought we would get to this particular milestone, and I say, quite honestly, “I admit I had my doubts.” When we say “I admit,” we’re saying that what we are about to say is something that we may not have wanted to say or perhaps are embarrassed to say. Here, it perhaps means “to be really honest with you.”
I say, “I admit I had my doubts. At the beginning, I was really dubious that this venture would pan out.” “To be dubious” (dubious) means to be full of doubts, to be uncertain – not to be sure if something is going to happen or if something is true. I say, “I was really dubious that this venture would pan out.” A “venture” (venture) is an effort to do something that is challenging or difficult, especially as it relates to a business, for example, or an organization.
If someone talks about starting a new venture, they’re talking about starting a new organization or, more commonly, a new business. We have the expression “venture capitalists.” A “venture capitalist” is someone who goes out and invests in, gives money to, new businesses in the hope that the business will be successful and that venture capitalist will get his or her money back – plus a profit, of course.
I say I was “dubious that this venture would pan out.” “To pan (pan) out” is a two-word phrasal verb meaning to be successful, especially in making something financially successful, or in some other way successful. You could also talk about your relationship “not panning out.” “I went out on a date with this girl, but it didn’t pan out.” She didn’t like me. She had another boyfriend. You know, the usual excuses.
I say, “I thought that our prospects were iffy at best.” Your “prospects” (prospects) are the chances that you are going to do well. It’s the likelihood of future success. In sports, we sometimes talk about “prospects” to refer to young baseball players who are very talented and who we think will be successful in the future. You could also talk about your prospects for employment, for getting a job. If someone graduates with a degree in, I don’t know, ancient history, that person might not have very good prospects for the future. That’s me, by the way. I graduated with a degree in ancient history many years ago – not 2,000 years ago, but many years ago.
I say that “I thought our prospects were iffy, at best.” “Iffy” (iffy) means doubtful, not certain. It’s somewhat of an informal term that we would use when we are not sure something is going to happen, when we are doubtful something will happen. We might say, “I want to try this new restaurant, but it’s a bit iffy,” or “It seems a little iffy.” We mean it could be very good, or it could be very bad. We’re not sure.
“At best” means at the most. When I say, “Our prospects were iffy, at best,” I mean that they were, at most, doubtful – meaning they were very doubtful. The best-case scenario – the best possible outcome or situation – was in this case “iffy.” You might say, for example, “We’ll probably make $200 today at best.” “At best” there means the maximum amount, the most that we will make.
Lucy says, “Me, too.” She agrees our prospects were iffy at best. She says, “We didn’t have an auspicious start, but we had a turning point after a few months of grinding out the work, day in and day out.” When you say you have an “auspicious (auspicious) start” to something, you mean you have a good beginning, a favorable beginning – a beginning that indicates that things will turn out well. However, in our case, Lucy says we did not have an auspicious start, “but we had a turning point.”
A “turning point” is some event or situation that causes you suddenly to become very successful or not very successful. In general, it means that you have some event that causes things to change significantly from the way they were going before that event. If your girlfriend says, “We’ve reached a turning point in our relationship,” she means either things are going to get much better or they’re going to get much worse. (I don’t know. It depends on your girlfriend.)
The “turning point” would be a sudden change or significant change – something important that will affect the way things are going – or rather, the way things will go in the future. We had a turning point in this venture after a few months of “grinding out the work.” “To grind (grind) out” is a phrasal verb meaning to continue to do something, especially if it perhaps isn’t very interesting, or if it requires a lot of work, or possibly both.
“To grind out” something means to work hard and get it done, even if it isn’t always the most pleasant or pleasurable thing to do. That’s not true with our podcast, of course. But in the script, Lucy says that we had a turning point “after a few months of grinding out the work, day in and day out.”
That expression “day in and day (day) out” means day after day. It’s a phrase that we use to emphasize that something happens every day without rest. “Day in and day out, you get up in the morning, and you eat breakfast, and you go to work, and you come home, and you read a book or watch television, and you eat your dinner, and you go to bed.” That happens “day in and day out” for many people.
Jeff – that’s me again – says, “What should we do now?” Lucy says, “I think we both deserve a celebratory drink, a toast to our achievements so far.” “Celebratory” comes from the verb “to celebrate” (celebrate). “To celebrate” means to do something to mark or to remember some significant event or situation. We celebrate our birthdays – we have a party or we go out to dinner. That’s “to celebrate.” You do something that makes you happy, something that will make you remember how good this event or this situation is.
Lucy is proposing we have a “celebratory drink.” Normally when you use the word “drink” in American English, you’re talking about an alcoholic drink such as beer or wine or whiskey or rum. I like rum, personally. That’s my favorite alcohol, but I don’t drink alcohol very much anymore – hardly ever, really. But if I did, I would drink rum.
Anyway, back to the story, we’re having a celebratory drink, Lucy says, “a toast to our achievements.” A “toast” (toast) here refers to words that you say, usually while raising a glass of some alcohol or some alcoholic drink in your hand, in order to honor or to celebrate or to remember some particular person or event. When you get married in the United States, it’s common for one of the members of your, what we would call “wedding party” – the group of people who are part of the wedding celebration – to make a toast.
“To make a toast” means to stand up and say, “Here’s to the new bride and groom” – here’s to the newly married couple. They’re saluting, they’re toasting, they’re celebrating these people. Sometimes a toast is just one or two words. In English we would say, for example, “Cheers!” In other languages, there are other common words that are used when someone picks up their glass of alcohol and makes a toast.
I say, “That sounds good” – the drink sounds good, that is. Then I say, “Then what?” – then what do we do? Lucy says, “Put our noses back to the grindstone?” “To put your nose (nose) back to the grindstone (grindstone)” means to go back to your hard work, your difficult work, after taking a short break.
So, if you work eight hours every day, you might take a break for 10 or 15 minutes in the morning. After your break, you may say, “Well, now I have to put my nose back to the grindstone.” I have to continue working hard at what I was working on before I took my break.
Jeff says, “I was afraid you were going to say that.” That expression, “I was afraid you were going to say that,” is used when we knew the other person was going to say that, but we didn’t really want them to say that – perhaps because, in this case, I don’t want to put my nose back to the grindstone. But I must.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Jeff: Well, we’ve reached a milestone.
Lucy: Yup, it’s been a long haul, but we’ve finally made it. Did you ever think we’d get here?
Jeff: I admit I had my doubts. At the beginning, I was really dubious that this venture would pan out. I thought that our prospects were iffy, at best.
Lucy: Me, too. We didn’t have an auspicious start, but we had a turning point after a few months of grinding out the work, day in and day out.
Jeff: So, what should we do now?
Lucy: I think we both deserve a celebratory drink, a toast to our achievements . . . so far.
Jeff: That sounds good. Then what?
Lucy: Put our noses back to the grindstone?
Jeff: I was afraid you were going to say that!
[end of dialogue]
The script for this episode, like all of our episodes, was written by the one, the only, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. After one thousand episodes, thank you for listening. Come back and listen to the next one thousand episodes right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2014 by the Center for Educational Development.
Glossary
milestone – a significant event or achievement that indicates an important step in one’s progress
* Their 10-year anniversary was an important milestone in their marriage.
long haul – a long and challenging period of time or distance toward some goal
* It was a long haul from high school graduation to completing his doctoral degree, but it was definitely worthwhile.
to make it – to achieve one’s goals; to accomplish something; to have some success
* After years of saving, we finally feel we’ve made it by buying our first home.
dubious – full of doubts; not believing that something will happen
* When smartphones first became available, a lot of people were dubious that they would become as popular as they have.
venture – an effort to do something that is challenging or difficult, especially to start a business or make an investment
* Kian’s latest business venture is to open an amusement park that’s all about rabbits.
to pan out – to be successful; to work; to turn out well, especially to be making money
* I hope all your hard work pans out with a new client contract.
prospects – the likelihood of future success; potential for success
* Desiree realizes the prospects are poor in a bad economy, but she’s going to open her own restaurant anyway.
iffy – doubtful; not certain; with an equal possibility of succeeding or failing
* These new recipes seem iffy. Should we try to make them anyway?
at best – at the most; at the maximum value
* We’ll probably make $200 in profit at best, and maybe a lot less.
turning point – the place and time when something changes its direction or trend significantly, either from good to bad or from bad to good
* The winning of the battle marked a turning point in the war.
to grind out – to continue to do something, especially repetitive and uninteresting work that requires a lot of effort and persistence over a long period of time
* How many units can this factory grind out in a day?
day in and day out – day after day; a phrase used to emphasize that something happens repeatedly, every day, without rest
* Wynona is so tired of cooking, washing dishes, doing the laundry, and scrubbing the floors day in and day out.
celebratory – in order to celebrate something; related to expressing joy and excitement about something, especially with other people
* When the deal was successful, they went to a local restaurant and enjoyed a celebratory glass of champagne.
toast – words said to honor a person or thing while raising an alcoholic drink in one’s hand before drinking
* Before we drink this wine, let’s have a toast for the guest of honor.
to put (one’s) nose back to the grindstone – to return to one’s constant, hard work after a short break
* The college students had fun over spring break, but now it’s time for them to put their noses back to the grindstone.
Comprehension Questions
1. What does Lucy mean when she says, “it’s been a long haul.”
a) They haven’t made very much money from their work.
b) They got lost along the way, but they finally found their destination.
c) They’ve done a lot of work over a long period of time.
2. What does Lucy think they should do to celebrate?
a) They should eat a piece of toasted bread.
b) They should say some nice words and have a drink.
c) They should throw a party for their friends.
Answers at bottom.
What Else Does It Mean?
make it
The phrase “to make it,” in this podcast, means to achieve one’s goals or to accomplish something and have some success: “We didn’t think we’d ever get great publicity, but we finally made it on the cover of the New York Times.” The phrase “to make it” also means to reach some destination that was difficult to arrive at: “On their third attempt, they finally made it to the top of Mount Everest.” The phrase “to make do” means to be able to do something with the limited resources that one has: “Ideally we’d like to have a larger budget, but I guess we can make do with what has been offered.” Finally, the phrase “to make or break” means to cause something to succeed or fail: “Getting that contract could make or break our company.”
toast
In this podcast, the word “toast” means words said to honor a person or thing while raising an alcoholic drink in one’s hand before drinking: “During the rehearsal dinner, everyone made a toast to the bride and groom.” When talking about food, “toast” is a piece of bed that has been lightly cooked on both sides to make it crunchy: “Would you like butter, honey, or jam on your toast?” The informal phrase “to be toast” means to be in trouble or to be punished for one’s actions: “If Mom and Dad find out what you’ve done, you’ll be toast!” Finally, if something is “toasty” it is pleasantly warm, cozy, and comfortable: “After playing outside in the snow, they sat with their feet by the fire until their toes were toasty again.”
Culture Note
The Word “Milestone”
In this episode of ESL Podcast, a “milestone” is a significant event or achievement that marks an important step in one’s progress. The word is “derived” (taken; adapted) from “markers” (objects that indicate where something is) that are traditionally found alongside roads, because they are also known as milestones. The first milestones were “stone” (made from rock) “obelisks” (tall, four-sided towers or pillars) that showed distances along important Roman roads.
In the modern United States, most highways and other major “thoroughfares” (roads) have mileposts or “mile markers” along the side of the road. These are usually green or brown rectangular signs placed low on the side of the road with the word “mile” and then a number indicating which mile the sign is at. The miles are usually numbered from one end of the road or from where a road begins within a state.
The system in California is a little bit different. In California, markers called “postmiles” indicate the distance traveled through a “county” (one of many geographical and political subdivisions of a state). Each marker has three numbers: the route, the county, and the postmile.
The State of New York has “yet another” (emphasis that there are other systems) way of marking miles along roads: the reference markers. These are small green signs that are placed every one-tenth of a mile. Each sign has three rows of four characters. The top row indicates the route number, the middle row indicates the region, and the bottom row indicates the number of “increments” (addition of a certain amount) from where the numbering began.
Comprehension Answers
1 - c
2 - b