
= 表达感情色彩
:toc:

---

== 委婉 + 口语中 + 探询式询问 <- 一般过去时 (did)

在口语中，要表示语气委婉, 可以用"一般过去时" (did), 也可用"过去进行时" (was/were doing).
此时的"过去时"丝毫没有过去的意味，而谈的是"现在"的情况。

[cols="1a,1a"]
|===
|一般过去时 (did) |过去进行时 (was/were doing)

|- *I wondered*(v.) if you could help me. 我想知道你能否帮我。 <- 表委婉, 可以用"一般过去时"来达到
- *Could(v.) you* give me a hand? 你能帮我一下吗？
|- *I was wondering*(v.) if you could possibly lend me your car for this evening. 我想知道你今晚能否把车借给我用用。 <- 表委婉, 可以用"过去进行时"来达到
|===

---

== 委婉 + 口语中 + 探询式询问 <- 过去进行时 (was/were doing)

在口语表达中，表示委婉的请求或提建议，我们也常用"过去进行时" (was/were doing) 来实现. 这时并不表示过去时间的动作。

*这尤其适用于表示"态度"的动词，如wonder，hope和think等*，这些动词用"过去进行时"（was wondering）或"现在进行时"（is wondering），均表示现在的一种愿望或态度，给人一种探询式的、犹豫不决的印象，因而显得很礼貌。

- Excuse me, Prof. Davidson. But *I was hoping* to talk to you about my class project for economics. 我希望能和您讨论一下我经济学课上的作业。
- *I was hoping that* you'd like to lend me your car. <- 这时若说：*I wonder* if you can lend me your car. / *I hope* to borrow your car. 语气上就显得直截了当地表达自己的态度，显得欠礼貌。

- *I was wondering* if you'd like to lend me your car.
- *I was thinking that* you'd like to lend me your car.


---

== 委婉 + 客观地询问事实(对方做不做和我没关系) <- 将来进行时 (shall/will be doing) ;  | 带情感色彩的语气(请求;命令;指示;质问)(即我希望对方做) <- will do

[cols="1a,1a"]
|===
|将来进行时 (shall/will be doing) <- 客观地询问对方 (对方做不做和我没关系, 他和我之间没有利益相关) |一般将来时 (will/shall do) <- 带情感色彩 (即我希望对方做, 对方做能给我带来利益)

|will be doing用在疑问句中，可以**用来客观地询问事实，表示自己并不是想干涉别人的决定，因而显得礼貌、委婉。** +
这种礼貌的提问方式, 常出现在服务员与顾客之间，以及陌生人之间。
|但若是其他语气，比如请求或命令等，我们则用will do来提问。  +
*will do 往往带有各种感情色彩，如请求、命令、指示、质问甚或威胁等等。*

|- How *will you be paying for this*? Joe答Cash。 <- 若他说 How will you pay for this? 则显得比较生硬，会让顾客感觉对方是在质问自己。
- How long *will you be staying*? <- 前台接待员在礼貌地询问客人要住多长时间

- When *will you be paying back the money*? 这钱你什么时候能还一下呢？  +
<- 用了will be paying，则显得较为圆滑, 听起来语气委婉. (让你想象一下未来你正在还钱时的场景, 来提醒你)

新概念英语中的文章:

- Her eyes were fixed on her plate and in a short time, she was busy eating. I tried to make conversation. +
"A new play is coming to 'The Globe' soon," I said. "*Will you be seeing it?*"  +
"No," she answered. +
"*Will you be spending your holidays abroad* this year?" I asked. +
"No," she answered. +
"*Will you be staying in England?*" I asked. +
"No," she answered. +
<- 我们注意到，作者在询问Mrs. Rumbold时，所使用的句子的谓语都用了"将来进行时态" will be doing. 因为作者和Mrs. Rumbold是第一次见面，彼此还是很陌生的。既然彼此不熟悉，所以作者问起来就格外小心谨慎，以免显得自己粗鲁，于是**他都用了will be doing的动词形式来提问，显得非常礼貌和谨慎**。


- When *will she be contacting me*? 她什么时候会联系我呢？<- will be doing 表达“委婉询问”的语气

|- When *will you pay back the money*? 你什么时候才能还这钱啊？ <- 用了will pay，语气显得比较强硬，似乎是在粗鲁地讨债.

正由于 will do 往往带有各种感情色彩，所以当我们要表达诸如“请求”之类带有情感色彩的语气时，此时, 我们就得用will do.

- Will you be lending me ten dollars?* <- 错误. 因为**这里的will不是在客观地询问事实，而是表示一种请求**，所以，我们要说：*Will you lend me* ten dollars? 你能借给我10块钱吗？


所以: +
-> 如果我们是要"客观地询问事实"，宜用will be doing来提问； +
-> 而若是其他语气，比如"请求或命令"等，我们则要用will do来提问。

|- *Will you be staying* in this evening? 今晚你不出去吧？ <- 用**will be doing是表示礼貌地、客观地询问，只是想了解你今晚的打算，并没有干涉的意思。**
|- *Will you stay* in this evening? <- “今晚你别出去了，好吗？”（请求），或者“今晚你不要再出门了行不行？！”（命令） <- 用**will do，含有感情色彩，如请求、指示或命令。**
|===


---

== 命令 <- be to do (= must, should)

be to do <- *表示强烈的命令，相当于must，should*，如：父母对孩子、上级对下级或法律条文中的规定等.

- These tablets *are not to be taken orally*. 该药禁止口服。
- The parties involved *are to sign(v.) the agreement*. 有关当事人一定得签署协议。
- If he'*s to succeed* in his new profession, he must try harder. 他如果想获得新事业上的成功，就必须更加努力。


---

== 强烈的情感 (生气, 激动, 兴奋等) <- 现在进行时 (am/is/are doing)

现在进行时 <- 在口语交流中, 可以用来表达各种感情色彩。 +
在口语中，我们**要表达自己的各种强烈的感情，比如生气、激动和兴奋等等，往往会频繁使用"现在进行时(am/is/are doing)".**

这一用法**其实正是源于"现在进行时"是表示“现在正在进行的动作”有关，因此能用它来表达我们"现在正在涌现中的"的各种内心情感. **所以, 此时说话人用进行时态，并非是要强调某个正在进行的动作，而是要表达自己当下的强烈的情感。



- *What are we waiting for then?* Let's get started. 那我们还等什么？赶快开始吧。 <- 这里**用进行时表示自己的不耐烦。**
- *I'm not having this conversation with you.* 我不跟你说了。<- *生气时*
- *You're not backing out of our date*, are you? 你该不是不想和我约会吧？<- 是**用进行时态表示说话人的怀疑和惊讶.**
- The bank *is only paying me 3 percent interest* on my money. 这银行才付给我3％的利息！<- **用进行时态表示说话人的愤怒. **这里显然不是要强调说明银行“正在付给我利息”。
- *You are asking too much!* 你的要求太过分了！
- *Why are you getting so upset* just because I'm two minutes late? You're making this into a bigger deal than it is. 你干吗要生这么大的气？我只不过是迟到了两分钟而已。你可真是小题大做！


====

又例:


:hardbreaks:
- Harry: You're a very attractive person.
Sally: Thank you.
Harry: Amanda never said how attractive you were.
Sally: Well, maybe she doesn't think I'm attractive.
Harry: I don't think it's a matter of opinion, empirically you are attractive.
Sally: Amanda is my friend.
Harry: So?
Sally: So *you're going with her*. <- *这里的are going表示的动作显然不是正在发生的，而是"现阶段在持续"的活动（action happening around now），即哈里现在正在和阿曼达交往.*
Harry: So?
Sally: So *you're coming on to me*! 你却在这里和我调情！ <- are coming则表示
的是action happening exactly now，即**"此刻正在进行"的动作。**
Harry: No, I wasn't.

- Harry: You realize of course that we can never be friends.
Sally: Why not?
Harry: *What I'm saying is*... and this is not a come-on in any way, shape or form, is that /men and women can't be friends because the sex part always gets(v.)  in the way. 我是说啊——不过我这么说绝不是在故意挑逗你啊——我是说男人和女人不可能
成为朋友的，因为他们之间总会涉及性。(come-on  引诱；诱惑；劝诱 / in any shape or form 以任何形式, 任何形式的)
...
Sally: *You're saying* I'm having sex with these men without my knowledge?
Harry: No, *what I'm saying is* /they all want to have sex with you.
<- 句中的"现在进行时态"（如I'm saying... 和 you're saying I'm having...）并不是为了说明动作在说话的时刻正在进行，而是**为了强调两人在陈述和坚持自己的观点，具有强烈的感情色彩。**

- Sally: *What are you saying?* You took pity on me? 你说什么？你那天是可怜我（才和我做爱的）？
Marie: *You're missing the point*, I'm telling you what I found.
<- 以上众多例句足以证明, *"现在进行时态"这种生动的情感表达, 在口语交谈中是多么频繁地被使用。*

====

*用"现在进行时"来表达各种感情色彩时, 经常与 always, forever, continually 和 constantly 等连用，表示"多次重复"的行为。这种反复的行为, 可以是积极的、让人喜欢的事情, 也可以是负面的、消极的事情。*

- Although Steve is a teacher, in a sense he is a student as well. *He is always learning things from his students.*
- *He's continually asking me for money*. 他总是向我要钱。
- How come Joe *is always groaning about things*? 乔为什么老是在抱怨啊？

---




