
= 2025.03.06 Is Europe ready for Trump
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 释义

*When it comes to* 就……而言;涉及,当提到,一谈到 International Trade 国际贸易, President Donald Trump has a special distaste (n.)厌恶;反感，不喜欢 for trade with the European Union 欧盟. At the first cabinet meeting 内阁会议 of his second term on February 26th, the president was asked by a reporter about any import tariffs 进口关税 he had in mind for the EU.

[.my2]
在国际贸易方面，美国总统唐纳德·特朗普对与欧盟的贸易特别厌恶。在他第二任期的第一次内阁会议上，记者询问了他对欧盟的进口关税计划。

"Okay, the EU tariffs, Mr. President. If you just made a decision on what level you will seek on tariffs in the European Union?"

[.my2]
“好的，欧盟关税，总统先生。如果您已经决定对欧盟征收关税的水平，您会设定在多少？”

"We have made a decision. We'll be announcing it very soon, and it'll be 25%, generally speaking, and that'll be on cars and all of the things. The European Union is a different case than Canada, a different kind of case. They've really *taken advantage of* 利用 us in a different way. They don't accept our cars. They don't accept essentially 本质上，根本上；大体上，基本上 our farm products 农产品. They use all sorts of reasons why not, and we accept everything of them, and we have about a $300 billion deficit 赤字 with the European Union. But the European Union has been—it was formed 构成；创立 in order to screw (v.)欺骗 the United States. I mean, look, let's be honest. The European Union was formed in order to screw the United States. That's the purpose of it, and they've done a good job of it. But now I'm president."

[.my2]
“我们已经做出了决定，很快就会宣布，关税将普遍为25%，主要针对汽车和其他产品。欧盟与加拿大不同，他们以不同的方式利用了美国。他们不接受我们的汽车，也不接受我们的农产品。他们用各种理由拒绝，而我们却接受他们的一切。我们与欧盟的贸易逆差约为3000亿美元。但欧盟成立的目的是为了欺骗美国。我是说，让我们诚实一点，欧盟成立的目的是为了欺骗美国，这就是它的目的，而且他们做得很好。但现在我是总统。”


If or maybe when President Trump does impose (v.)强制推行，强制实行 tariffs on Europe, the big question becomes: How will Europe respond (v.)回应；作出反应? To help us understand Europe's position in all this 在这一切中的位置, I will be joined by a very special guest, R. Rert Schil. He is a former _European Commission_ 欧盟委员会 trade official. While he worked in the Commission 考察团，委员会 for over 30 years, for the last 5 years he was DG Trade's main official *in charge of* trade relations 贸易关系 with the United States. Hi, Rert.

[.my2]
如果或当特朗普对欧洲征收关税时，最大的问题是：欧洲将如何应对？为了帮助我们理解欧洲在这一问题上的立场，我将与一位特别嘉宾——前欧盟委员会贸易官员R. Rert Schil——进行对话。他在欧盟委员会工作了30多年，最近5年担任DG贸易的主要官员，负责与美国的贸易关系。你好，Rert。

"Hello, Chad. You are listening to an episode of _Trade Talks_ 贸易谈判, a podcast 播客 about the economics of trade and policy. I'm your host 主持人, Chad Bown, the Reginald Jones _Senior (a.)级别（或地位）高的 Fellow_ (（学术或专业团体的）会员) 资深研究员 at the Peterson Institute for International Economics in Washington. Before we get into it 参与其中, I want to provide _a quick update_ on _where things stand_ 快速更新一下目前的情况 in President Trump's latest trade war 贸易战 and a quick advertisement. If you've not already done so, do check out 调查 the Peterson Institute's new tariff tracker 关税追踪 on the PI website, titled 'Trump's Trade War Timeline 2.0: An Up-to-Date (a.)包含最新信息的 Guide.'

[.my2]
“你好，Chad。你正在收听的是《贸易对话》，一档关于贸易经济学和政策的播客。我是你的主持人Chad Bown，彼得森国际经济研究所的高级研究员。在我们深入讨论之前，我想简要介绍一下特朗普最新贸易战的现状，并做一个简短的广告。如果你还没有查看过，请务必访问彼得森研究所的网站，查看新的关税追踪工具，标题为‘特朗普贸易战时间线2.0：最新指南’。

Okay, at the moment, President Trump has tariffs 关税 后定 *coming on* 即将实施,即将生效European steel and aluminum 铝 under Section 232. This is that National Security Law 国家安全法. Those are scheduled 安排；将……列入计划表（或时间表等） to go into effect 生效 on March 12th. Trump has ordered his U.S. Trade Representative 贸易代表 to look into 调查，研究 EU member states' 欧盟成员国 Digital Services taxes 数字服务税 on American tech companies, and so we may see U.S. tariffs on Europe there sometime in the future. He also has the _reciprocal (a.)相互的，互惠的，报答的 tariffs_ investigation 互惠关税调查 ongoing (a.)仍在进行的，不断发展的. That one is due (a.)预定；预期；预计 to wrap up 结束 on April 1st, so we could see _higher U.S. tariffs_ on whatever European products 后定 have a higher _current tariff rate_ 关税税率 than their U.S. _tariff equivalent_ 关税等价 through that rationale 理由;根本原因，逻辑依据, or we could just see 25% tariffs on Europe, like President Trump said at the cabinet meeting 内阁会议.

[.my2]
目前，特朗普根据第232条国家安全法对欧洲钢铁和铝征收关税，这些关税将于3月12日生效。特朗普还命令美国贸易代表调查欧盟成员国对美国科技公司征收的数字服务税，因此未来我们可能会看到美国对欧洲征收关税。他还在进行互惠关税调查，该调查将于4月1日结束，因此我们可能会看到美国对欧洲产品征收更高的关税(因此，根据这一理论，我们可以看到美国对任何"目前关税税率高于美国同等关税"的欧洲产品, 征收更高的关税.)(通过这种逻辑，我们可能会看到美国对某些欧洲产品征收更高的关税，这些产品目前的关税比美国对同类产品征收的关税更高。)，或者像特朗普在内阁会议上所说的那样，对欧洲征收25%的关税。

[.my1]
.title
====
- reciprocal -> 来自*reco-proco,来来往往，来自 re-,向后，pro-,往 前，-cus,形容词后缀。引申词义互惠的，互利的。
====


There is obviously still a lot of uncertainty 不确定性, but what we also know is `主` #the likelihood# 可能性 of President Trump #后定 imposing# (v.) tariffs on Europe `谓` seems to be increasing by the day 随着每一天的过去. On March 4th, he put another round 一轮;阶段；轮次 of 10% tariffs on China. Much more surprising was President Trump's #decision# that day 后定 #to also impose 征收 25% tariffs# on most everything 后定 the United States *imports (v.) from* Mexico and Canada after initially pausing 暂停 _that tariff threat_ 关税威胁 for 30 days _back in February_. Apparently, tariffs on historical U.S. Military Allies 军事盟友 are *not just* threats (n.) _this time around_ 这一次. They are happening (v.) for real 正在发生.

Okay, Rert, to Europe. Before we get into anything specific (a.)明确的，具体的；特定的 about tariffs, let's *set the scene 提供背景信息 for* some of the underlying economics 基础经济学 here. How interdependent (a.)相互依存的;相互依赖的；互助的 are the U.S. and European economies?

[.my2]
显然，仍有很多不确定性，但我们知道的是，特朗普对欧洲征收关税的可能性似乎在逐日增加。3月4日，他对中国又征收了10%的关税。更令人惊讶的是，特朗普当天还决定对从墨西哥和加拿大进口的大部分商品, 征收25%的关税，此前他在2月份暂停了这一关税威胁30天。显然，这次对历史悠久的美国军事盟友征收关税, 不仅仅是威胁，而是正在发生。好的，Rert，谈到欧洲。在我们深入讨论关税问题之前，让我们先了解一下背后的经济学基础。美国和欧洲经济之间的相互依存程度如何？”


So first, the European Union is *by far* 最……的程度远超其他;远远地,显然地,无可争议地 the most important economic partner 经济伙伴 of the US. `主` The second point that I would like *to make (v.) [up front* 预先；在最前面] `系` is our relationship is balanced (a.)平衡的；和谐的；安定的. No one is *taking advantage of* 利用 each other. We actually have a shared interest 共同利益 to neutralize (v.)中和;使失效，抵消 this relationship, and it's going very well. What people also maybe don't know is that `主` our bilateral trade 双边贸易 in goods and services `谓` has doubled in the last 10 years. _Where else_ do you have that growth? American exports (n.) to the EU in the last 3 years are up 35%, so that creates (v.) jobs and prosperity 繁荣 in the US.

[.my1]
.title
====
- to make (v.) [up front] :  +
"make" 指 "提出（观点、论点）"，即 "make a point"（提出一个观点）。 +
"up front" 意思是 "开门见山地、首先、事先"，表示提前说明、在一开始就提及。 +
"to make *up front*" 其实是 "make a point"（提出观点）+ "up front"（事先、首先） 的组合，意思是**“我想先提的观点是……”**。
====

There sometimes is the idea that 有时会有这样的想法 because of a deficit 赤字 in Goods, there is an imbalance 不平衡, but let me now start (v.) with something else. Let me start with Services 服务；服务项目. The US last year *exported* (v.)$462 billion worth of services *to* the EU. That *leads (v.) to* a surplus 盈余;过剩，剩余 of 117 billion. We never talk about that. There is a _Goods deficit_ (亏损，赤字，不足额) 商品贸易逆差 of 169 billion, but if you *add up the sums* 把总数加起来, you're left with 50 billion difference 差额只有500亿美元. So that's not great, and *that's not a lot* in a 1.7 trillion relationship per year. It's about 3% on the depth 深度 and the importance of the relationship.

Again, I don't want to overload (v.)使负担过重;过度堆砌 the figures 数字 here, but be aware that `主` _over 50, almost 60%_ of what the US or the EU invest (v.) in the world `谓` goes to the partner across the Atlantic. And just to give you an example, there are _3 and a half million jobs_ *directly dependent on* EU investment in the US. So if you start (v.) messing (v.) with 干扰;弄乱 this relationship, you will actually affect (v.) jobs in the US. What people can really visualize (v.)想象 is `主` the biggest BMW plant 工厂 of the world `系` is in South Carolina. It's not in Munich 慕尼黑（德国城市）, and there are similar examples of the deep investment relationship 深厚的投资关系. So that's my first point, a deep and balanced relationship.

[.my2]
====
首先，欧盟是美国最重要的经济伙伴。我想强调的第二点是，我们的关系是平衡的。没有人利用对方。我们实际上有共同的利益来中和这种关系，而且进展非常顺利。人们可能不知道的是，过去10年，我们的双边贸易额翻了一番。美国对欧盟的出口在过去三年增长了35%，这为美国创造了就业和繁荣。有时人们认为，由于商品贸易逆差，存在不平衡，但让我从服务贸易开始说起。去年，美国向欧盟出口了价值4620亿美元的服务，这导致了1170亿美元的盈余。我们从未谈论过这一点。商品贸易逆差为1690亿美元，但如果你把两者相加，差额只有500亿美元。因此，在一个每年1.7万亿美元的关系中，这并不算多，约占3%。

关于这种关系的深度和重要性，我不想过度堆砌数据，但要知道，美国或欧盟在全球投资的50%以上，几乎60%，都流向了跨大西洋的伙伴。举个例子，美国有350万个工作岗位直接依赖于欧盟的投资。因此，如果你开始干扰这种关系，你实际上会影响美国的就业。人们可以真正想象到的是，世界上最大的宝马工厂在南卡罗来纳州，而不是在慕尼黑。类似的例子还有很多，表明我们之间的投资关系非常深厚。这是我的第一点：深厚而平衡的关系。
====

So President Trump, when he's talking and focused on the unbalanced relationship in his view, he has a very, very narrow perspective 狭隘的观点, which is just looking at Goods trade, all the cars coming in from Germany and the rest of Europe into the United States and many fewer cars going back in return. But there are a lot of cars produced by European companies in the United States, and there's an imbalance in the other direction when it comes to services. And so those services are going to be things like Netflix and the internet companies, financial services 金融服务, and when you put all those things together, the relationship is much more balanced. That being said, it looks like there's a really good chance that President Trump is going to end up putting some sort of tariffs on European Goods coming into the United States. So what I want to ask you about next is Europe's preparedness 准备 for this. Now, obviously, you were part of the commission the first time around when President Trump was in office between 2017 and early 2021. You didn't take up your job as head of the trade relationship with the United States until 2019, so you weren't there for all of it, but you got to see some of it. What can you tell us about things that happened in the trade relationship with the first Trump Administration in Europe that might be useful Lessons Learned 经验教训 for this time around? This is not the first time we are either threatened or experiencing US tariffs, and you refer to the Section 232 tariffs, which went into place on steel and aluminum and which were threatened on cars in that period. I think the experience was at the time twofold. First of all, you have极 to prepare yourself from a position where you can actually also take countermeasures 反制措施, but even more importantly, you have to try to find a way to negotiate on these issues. And this is exactly what happened in 2018. We were able to—and start me with the good news—to avert 避免 the car tariffs with a negotiation, doing a deal, which is one of the things that President Trump likes to do. So we did a deal to buy more liquid natural gas 液化天然气 and to buy more soybeans 大豆 from the United States in return for not having tariffs put on cars. We were less successful on the other threat and then implemented tariffs at the time, which were the tariffs on steel and aluminum, and here we actually took countermeasures. It took a while to do that because we have a procedure to go through, but we used a legal procedure for the non-initiated under the GATT WTO Safeguard rules 保障措施规则 to countervail 抵消 the tariffs with our own tariffs, and we did implement them. So on the Trump Administration, first Administration, we actually remain stuck with tariffs on both sides. I want to talk a little bit more about Europe's experience with countermeasures. As you mentioned, the EU was ultimately effective at being able to implement a sort of rebalancing 重新平衡 when it came to the steel and aluminum tariffs, but just having this constant threat of other tariffs that were out there, you know, during almost the entirety of that Administration, there was a threat of 25% tariffs on cars, as you mentioned, there were also threats about potential tariffs if countries did Digital Services taxes. From an outsider's view, it seems as that was happening, it looks like Europe was learning that maybe have all of the policy levers 政策杠杆 that it might want available should something like that happen again. Tell us a little bit about some of the new policy instruments 政策工具 that the European Union has developed in the meantime since that first Trump Administration.

[.my2]
因此，当特朗普谈论并关注他认为不平衡的关系时，他的观点非常狭隘，只是关注商品贸易——所有从德国和欧洲其他国家进口到美国的汽车，而返回的汽车却少得多。但美国有很多由欧洲公司生产的汽车，而在服务贸易方面，不平衡则相反。这些服务包括Netflix、互联网公司和金融服务。当你把这些因素综合起来时，这种关系要平衡得多。话虽如此，特朗普很可能会对进入美国的欧洲商品征收某种关税。因此，我想接下来问你的是，欧洲对此的准备情况如何？显然，在特朗普第一次执政期间（2017年至2021年初），你曾是欧盟委员会的一员。你直到2019年才担任与美国的贸易关系负责人，所以你没有全程参与，但你看到了一些情况。你能告诉我们一些在特朗普第一届政府期间，欧洲与美国贸易关系中发生的事情吗？这些经验对这次可能有用。这不是我们第一次受到美国关税的威胁或实际征收，你提到了在第232条下对钢铁和铝征收的关税，以及当时对汽车征收关税的威胁。我认为当时的经验是双重的。首先，你必须从能够采取反制措施的立场上做好准备，但更重要的是，你必须找到一种方式来谈判这些问题。这正是2018年发生的事情。我们通过谈判成功地避免了汽车关税，这是特朗普喜欢做的事情之一。因此，我们达成了一项协议，购买更多的液化天然气和大豆，以换取不对汽车征收关税。我们在其他威胁上不太成功，当时对钢铁和铝征收了关税。在这里，我们实际上采取了反制措施。由于我们需要走程序，这花了一些时间，但我们根据GATT WTO保障措施规则，使用法律程序来抵消这些关税，并实施了反制措施。因此，在特朗普的第一届政府期间，我们实际上陷入了双方都征收关税的僵局。我想进一步谈谈欧洲在反制措施方面的经验。正如你所提到的，欧盟最终能够在对钢铁和铝征收关税时实施某种重新平衡，但在几乎整个政府期间，都存在对其他关税的持续威胁，例如对汽车征收25%关税的威胁，以及如果国家对数字服务征税可能面临的关税威胁。从外部来看，欧洲似乎从中吸取了教训，可能已经掌握了所有可能需要的政策杠杆，以备类似情况再次发生。请告诉我们一些自特朗普第一届政府以来，欧盟开发的新政策工具。

Yes indeed, I think we learned a lesson from the first Trump Administration, and that is that we might not have all the tools for a similar situation occurring in the future. With a similar situation, I mean what we call coercion: weaponizing 武器化 of trade for any possible political objective, which was not done frequently, or at all, or a lot in the first 20 years of the WTO. So, it's actually from the experience with the car tariffs, plus certain things also happening on the other side of the globe, that we thought we need an instrument which allows us to counter any threats when we actually implement what we thought were legal, legal, non-discriminatory 非歧视的, balanced, proportionate 成比例的 policies. So, we came up with this idea of an anti-coercion instrument 反胁迫工具, which is a tool which allows us to take measures after a quite detailed procedure and within the rules-based international order 基于规则的国际秩序 against what we would define as economic coercion 经济胁迫. One thing which also led to the creation of this instrument is the fact that WTO litigation 诉讼, which is our preferred way to deal with any conflict, takes years, and there is no appellate body 上诉机构 any longer which would actually give a final ruling 最终裁决. So, we wanted to be quicker, but let's be clear: the anti-coercion instrument is not a rapid response mechanism 快速反应机制.

[.my2]
是的，我认为我们从特朗普第一届政府中学到了一个教训，那就是我们可能没有应对未来类似情况的所有工具。我所说的类似情况是指我们称之为“胁迫”的行为：将贸易武器化以实现任何可能的政治目标，这在WTO的前20年中并不常见，甚至几乎没有发生过。因此，实际上，正是由于汽车关税的经验，加上全球其他地方发生的一些事情，我们认为需要一种工具，使我们能够在实施我们认为合法、非歧视、平衡和成比例的政策时，应对任何威胁。因此，我们提出了“反胁迫工具”的概念，这是一种允许我们在经过详细程序后，在基于规则的国际秩序框架内采取措施的工具，以应对我们所定义的经济胁迫。导致这一工具创建的另一个事实是，WTO诉讼是我们解决任何冲突的首选方式，但它需要数年时间，而且不再有上诉机构来做出最终裁决。因此，我们希望更快，但需要明确的是：反胁迫工具并不是一种快速反应机制。

Let's get into some of the potential ways in which use of this new anti-coercion instrument might play out. So, let's go through a hypothetical 假设. Let's suppose President Trump decides to raise U.S. tariffs on European exports. You know, it could be for any, any number of reasons that he's proposed already, but let's suppose it's this reciprocity rationale 互惠理由 where he's basically said to countries, "If you don't lower your tariffs to my level, I'm going to raise my tariffs to your level." Let's suppose he just does that. How would the EU actually operationalize 实施 this anti-coercion instrument in practice? How does it work? It is a carefully tailored tool 精心设计的工具 which starts with an investigation to establish the facts. So, is there coercion? Then it goes into a procedure where you will try to negotiate away the issue. So, it's not immediately, even if there is a finding of coercion, that you take measures; you try to negotiate, talk softly with a big stick 大棒政策, maybe you can say that. And only when that fails, then there is the possibility to take countermeasures 反制措施. And what is also innovative here is that the countermeasures which can be authorized under this procedure are quite broad. So, it's not only goods, because that might not be effective, and in any case, with tariffs on goods, you shoot yourself in your own foot 自食其果 because you make it a tax on your own imports. So, the instrument allows also measures in other areas like services, government procurement 政府采购, or the protection of intellectual property rights 知识产权保护.

[.my2]
让我们探讨一下这种新的反胁迫工具可能发挥作用的潜在方式。我们通过一个假设来展开。假设特朗普决定提高美国对欧洲出口的关税。你知道，这可能是出于他已经提出的任何理由，但假设是基于互惠理由，即他对国家说：“如果你们不将关税降低到我的水平，我将把关税提高到你们的水平。”假设他这么做了。欧盟将如何在实际中实施这一反胁迫工具？它是如何运作的？这是一种精心设计的工具，首先通过调查来确定事实。是否存在胁迫？然后进入一个程序，试图通过谈判解决问题。因此，即使发现存在胁迫，也不会立即采取措施；你会尝试谈判，用大棒政策软硬兼施，可以这么说。只有在谈判失败时，才有可能采取反制措施。这里的创新之处在于，根据这一程序授权的反制措施范围相当广泛。因此，它不仅限于商品，因为那可能无效，而且对商品征收关税实际上是自食其果，因为这会增加自己的进口成本。因此，该工具还允许在其他领域采取措施，如服务、政府采购或知识产权保护。


Now, the European Commission has never actually utilized this anti-coercion instrument in practice; it's primarily a deterrent. So, we don't have any experience for how it would do so, but it's an interesting intellectual exercise to think through how the retaliation actually might be used. One option is, of course, just to impose tariffs on goods, but if your relationship is asymmetric and you don't have a lot of goods imports from the United States coming in that are easily replaceable, maybe that wouldn't be an effective deterrent. So, maybe you'd go with something else. The other options you suggested—maybe you try to put a discriminatory tax on U.S. services exports. Some of the versions of the original Digital Services Taxes coming from EU member states like France did seem really designed to target American big tech companies. If memory serves, French Finance Minister Bruno Le Maire called the French one the "GAFA tax" for targeting Google, Apple, Facebook, and Amazon at the time. Or the third one you mentioned is maybe the EU retaliates by going after intellectual property rights protection. That one has always been a little unclear to me how you would put that into practice. For example, suppose the EU tries to punish the United States by withholding IP protection for American companies. Maybe the idea here is to try to hurt Hollywood by giving away free rights in France to show American movies. While French consumers might like that, to my mind, where the retaliation breaks down is France's own movie industry would likely be super annoyed, and that's because French citizens are now getting free American movies, and so they're less likely to pay to watch French movies. Anyway, these are interesting ideas, but perhaps still some kinks to work out in terms of implementation, but we will be tracking them closely.

Okay, you also mentioned that the ACI is not a rapid response instrument. In response to Trump's tariffs this time around, we have seen countries like China and Canada retaliate in potentially just days. Do we have any sense at all for how long we're talking about here between when the EU begins an ACI investigation at the point at which countermeasures could be imposed? Is it four weeks, 6 months, 18 months? How long are we thinking? Well, the regulation, if you look at it, it has certain deadlines which run into several months normally. So, I think it's safe to say it's not going to take four weeks; it's going to take longer for the investigation to conclude and to do all of this. And this is the point that is difficult to verify: how much time we can spend on negotiations? Because I really want to put the cursor on the fact that we are dealing with an administration in the U.S. who likes to do deals, and we have stretched out our hand and say we're ready to do deals, which is one phase of the instrument. Ultimately, it will take quite a while, also because of the politics involved.

Let's go back to one other thing with the anti-coercion instrument. Talk us through how the European Commission thinks about this ACI instrument in a WTO context. Normally, one would say that if a country is going to do something to my trade that I don't like, my response isn't to take matters into my own hands, but it's to bring a dispute to Geneva and the WTO. And that's the line that I've understood the EU to be pushing for, um, not only for itself but for others as well, for decades. How does the ACI fit into this? Yeah, make no mistake, we still push—and this is the possibility to do a little advertisement for the WTO, which is a little bit the background now—we still are multilateralists and believe that conflicts should be solved wherever possible in the WTO, because the value, the predictability of WTO rules, is something which we cherish a lot. But we've also come to the conclusion that this is not always the only possible response to safeguard our rights, for the reasons I mentioned: the WTO dispute settlement is not functioning, it wasn't meant to look at economic coercion situations, it was meant to look at commercial, if you wish, disputes or misled legislation. So, what we did with the anti-coercion instrument to make sure that the legal basis is compatible with WTO—and this is, if you look at the explanations, the explanatory part of the regulation—it clearly sets out that this is based on international law, the UN Charter, the duties of countries to cooperate and refrain from coercion, etc., etc. So, we grounded it in public international law in order to have a solid base to react—not to act, to react—to a breach of law. And for this, we needed the public of the international law scene, because the WTO on its own doesn't provide the measures or the tools to actually react to this situation.

But just as we've never seen the Commission operationalize use of the anti-coercion instrument in practice, we also haven't seen litigation under the WTO that might challenge the legality of the anti-coercion instrument actually play out and any WTO rulings to know just how consistent or inconsistent it might be. So, that in itself is an open question. [Music] It's certainly the case that President Trump does like to do deals as well. What can you tell us about some of the other lessons learned from the EU's side from the first administration? Just reading the reporting, it seems as if some senior-level officials have already come to Washington to meet their counterparts, uh, in the Trump administration to get some of these conversations already going. You will have seen that one of the first things the new Trade and Economic Security Commissioner—meaning minister of the EU—has done was go to the United States, and you will have seen that many other leaders from the European Union, heads of state, went to Washington to also pass that message that we're open for business. I think we are serious from the EU side to try to find something which would satisfy our American friends or our American present administration. And you will have seen from the public statement that the first thing we always say is we're ready to look at your demands and negotiate. And there were actually things mentioned—cars was mentioned, passenger cars. We do have a higher tariff than the U.S., and that has been a constant feature in some of the remarks of our American counterparts. And there are other things that we can think about. I mean, obviously, we have a strong interest in any case to buy weapons; we already buy a lot of weapons in the U.S., and with the present situation, that will only increase. Let me also add that last time, the focus was on energy, where in any case we had to diversify and wean ourselves off the Russian supplies, which is now becoming even more important. And the United States is now our biggest supplier already on LNG, and there is a potential to do more. So, there are actually real-life interests here that we could maybe look at and see what can be done, and that has been, I think, a constant message from the EU side.

One of the challenges, obviously, in the timing of what's happening here with these tariff threats is, simultaneously, you have major developments taking place in the Russia-Ukraine war. President Trump clearly wants to settle the war; he had a blow-up in the Oval Office last week with Ukrainian President Zelensky, and the White House just announced it's at least temporarily suspending military aid to Ukraine. I think, as a policy matter, President Trump wants to reduce U.S. involvement in NATO and its role in providing military security to Europe. How do these other non-trade issues, but nevertheless still issues between the United States and Europe that are incredibly important—how are they likely to affect Europe's trade response to any tariffs that the Trump administration might impose? I don't have the answer to that. I mean, I think the trade officials—and I'm a former trade official—we know that we are not acting in a vacuum, so the bigger picture is always there. And it's true to say that we are at a very important and difficult point right now with the situation in the Russian aggression and the developments in the United States. The European leaders, be it from the European Commission, be it from the member states, have been quite clear to say that a firm response would be needed, so basically arguing a separation of the trade discussions from bigger political things, which was something which we were able to achieve in the last [Music] decades.

Now, I want to turn to the European Union's relationship with third countries. During President Trump's first term, there were a number of other countries out there who made a big show of being able to conclude free trade agreements in the absence of the United States, the message being something like, "Hey, we can do trade liberalization without you." The EU itself closed an important deal with Japan, for example. More recently, in December of 2024, there was news that the European Commission had agreed to a deal with Mercosur. This was one that, I think, you cover not just trade relations with the United States but everybody in the hemisphere, so it's one that you had a big role in. What do you think? Should the United States be worried that there's going to be a proliferation of free trade agreements amongst everybody else this time around? I'm not sure whether they should be worried, and I just read that they also gave up the APEP, this initiative with Latin America, if I'm correctly informed. So, they clearly don't want to do what we do. But I think it is true that those countries who are interested in maintaining an open trading system based on rules and predictable, stable relations might have more interest to work together. Let's put it simple as that. So, with a situation as it is now, there's, I think, a heightened or a better incentive to actually conclude deals built on trust with those partners that you do trust. And that, I think, means that also we, from the EU, are trying to finish the negotiations, and we have finished New Zealand, Chile, update—I think there is a good chance that we will update the Mexico agreement, because Mexico also has an interest to have partners with a predictable policy environment. And Mercosur is, of course, the biggest part, and I hasten to add that we're also restarting the discussions with India, which is, of course, also a hugely important partner. All of that, I think, in the present context, makes a lot of sense.

There's another really important third country out there that is, of course, China. Also, during the Trump administration's first term, the EU, the United States, and Japan were actually working together somewhat behind the scenes on something called the Trilateral. My understanding is you were part of this, and the goal was to think hard about potential new rules to address some areas of common concern when it comes to China, and in particular, Chinese subsidies. Tell us more about that experience of working with the first Trump administration on that area of common concern. Well, I think for much of the last years, there was no big disagreement about the analysis on what needs to be fixed in the rulebook in the WTO if you really want to address non-market economy practices as we have seen them develop over the last two decades, maybe. So, the Trilateral was one of the first attempts to look at the rulebook and say, "What would it be if we just sat together and found a way to deal with some of these practices?" And that was actually quite successful, uh, and the idea was to spread this to like-minded countries and make an initiative and find a way to implement these things later on. It didn't really go very far after this first ministerial meeting early 2020; there was no follow-up in the next couple of years. That was how the EU dealt with China with the first Trump administration.

How did things change when the Biden administration arrived in early 2021? Was there any progress there between the EU and U.S. on how to address, or at least how to think about, the China challenge in specific economic areas? We then had very long discussions in the context of the Trade and Tech Council with the United States on the China challenge, China being the predominant preoccupation of any U.S. administration the last 10 years, 15 years. And we actually were able to do a few things to coordinate and cooperate on China-related issues, be it on medical devices, where we jointly wrote to China on their practices on public procurement, be it on trying to find ways to deal with some of the cyber threats, and so on. So, what I think the difference is, is the response to these issues, because we didn't believe that putting tariffs on China—and don't forget the original justification was a 301 intellectual property case—we also have issues with that, but we tried to find other ways. We have a very active cooperation on intellectual property with China, which works or doesn't work, you can argue about that, but we wanted to stay within the rulebook, let's put it like that, which is quite complicated.

What about Chinese steel and aluminum overcapacity? That was one that President Biden and European Commission President Ursula von der Leyen promised publicly back in 2021 that the U.S. and EU would work on together. How did that work agenda go? The most promising enterprise in all of this, in my view—but maybe I'm biased because I was also involved in that—was the attempt to forge a coalition of the willing, starting with the EU and the U.S., on steel and aluminum, which was the most egregious case of overcapacity flooding the world markets. The OECD worked on it in a steel forum, and we were crafting rules, very detailed rules, again, on what kind of subsidies are allowed or not to keep your steel industry afloat, including what kind of steel you would like to favor for reasons of low carbon content. So, there was a climate aspect, and those negotiations went quite far in the level of detail, and I wouldn't say we were there to conclude, but we were close to conclude, also because we would have to make some compromises on imposing, in one way or the other, higher tariffs on China. So, while we differed sometimes on the means, I think we moved a lot closer on the analysis on what is wrong with Chinese behavior. We'll see how that goes, but it's clear that there will be further discussions on how best to deal with, in particular, overcapacity, because what we have seen on steel and aluminum is only the beginning. There is enormous overcapacity in many sectors, something which we actually knew for a long time, but nobody really has a very convincing answer how to deal with that, because there are no rules on many of the practices.

So, on that point, is it possible for policymakers and politicians to be working on both portfolios at the same time? If you're a European Commission trade official, to be dealing with the threats of tariffs coming in from the United States and how you have to respond to those, and then at the same time working with the United States on a common challenge that is China? Is it possible to segment and compartmentalize in a way that ultimately is going to allow you to make progress on that second issue in particular? I think it is on us to at least try to do that. I think we certainly were able to do this to some extent, also, I think, with the first Trump administration, because, you know, doing nothing is not the default option. I mean, the issue is there, and we are more effective if we deal with this together. I can't really speak on the present administration; I have no idea whether they want to cooperate with anyone on China. I think we're going to find out. Yeah, it's going to be complicated.

That's clear. Media reports are that China is now reaching out to Europe diplomatically, almost as if to say, "You're being bullied by your old friend, those Americans, who seem to be going in a different direction. Why don't we be better friends? Put all those projects that you were working on with the Biden people, maybe the first Trump people, put that behind you, and let's do more together." In light of all the U.S. tariff threats, what do you think are the implications for Europe's relationship with China today? Well, maybe the first thing to say is that China is already experiencing the tariffs on 10% and now 20% and so on, and that, of course, shows also that China has an interest to work with others to do something on this. But I do think, despite the charm offensive that actually did happen some months ago and maybe is continuing, we have to keep a cool head and look at our interests here. We have always been maintaining that we have to counter the unfair practices of China, but not everything China does is unfair. So, we also have to cooperate in those areas where that is not at stake. It's a big commercial partner; it will not go away. But we also have to be clear that there are limits, and the one thing which you can see in the European theater playing out is there are a lot more measures taken—anti-dumping, anti-subsidy, foreign subsidy regulation—we haven't mentioned that. So, I think we also intend to defend ourselves vis-à-vis the unfair practices of China.

As my last question for you, it's one more about China. In your view, has the European perspective on China changed over the last few years? So, Chad, let me remind you that President von der Leyen actually, at the World Economic Forum this year, talked about a "China shock" as a threat because of Chinese export subsidies. So, I think the rhetoric has changed a little bit, also because we're a little bit clearer about some of the state-sponsored policies that we all are worried about. We have certainly also taken a hard look at some of the things which happened in China, including that we were suffering from a coercion case on Lithuania. As I said, we try to separate out what is economically normal behavior and where do we have to be careful. And I do think that we are a bit more critical about the effects of the Chinese policies, the way also they treat European companies in China, without becoming paranoid. I think we really have to make a case, and this is why we took a long time to do a proper investigation on electric vehicles, for example. On the one hand, we agree that there is an issue, but on the other hand, we did a proper investigation; we came up with a differentiated response. So, we didn't slap a tariff on everyone; we really tried to keep the rules, also vis-à-vis China, where there are rules that we can assert.

Thank you very much. You're welcome, and that is all for Trade Talks. A huge thanks to Robert Schuman, a former trade official at the European Commission and now visiting professor at the College of Europe. Thanks to Melina Cobb, our supervising producer; thanks to Isabelle Robertson, our audio producer; and thanks to Sam Elizon, digital. Please subscribe to Trade Talks on Apple Podcasts, on Spotify, and Amazon Music, or wherever you get your podcasts these days. You can follow Trade Talks on Blue Sky or on X, where we are at Trade_Talks—that's not one but two underscores—at Trade_Talks. And if you do look for us there, you will see this week a special photo posted of an old friend as well as a new addition to the Trade Talks family.

'''


== pure

"When it comes to International Trade, President Donald Trump has a special distaste for trade with the European Union. At the first cabinet meeting of his second term on February 26th, the president was asked by a reporter about any import tariffs he had in mind for the EU.

"Okay, the EU tariffs, Mr. President. If you just made a decision on what level you will seek on tariffs in the European Union?"

"Uh, we have made a decision. We'll be announcing it very soon, and it'll be 25%, generally speaking, and that'll be on cars and all of the things. European Union is a different case than Canada, different kind of case. They've really taken advantage of us in a different way. They don't accept our cars. They don't accept essentially our farm products. They use all sorts of reasons why not, and we accept everything of them, and we have about a $300 billion deficit with the European Union. But European Union's been—it was formed in order to screw the United States. I mean, look, let's be honest. The European Union was formed in order to screw the United States. That's the purpose of it, and they've done a good job of it. But now I'm president."

"If or maybe when President Trump does impose tariffs on Europe, the big question becomes how will Europe respond? To help us understand Europe's position in all this, I will be joined by a very special guest, R. Rert Schil. He is a former European Commission trade official. While he worked in the commission for over 30 years, for the last 5 years he was DG Trade's main official in charge of trade relations with the United States. Hi, Rert."

"Hello, Chad. You are listening to an episode of Trade Talks, a podcast about the economics of trade and policy. I'm your host, Chad Bown, the Reginald Jones senior fellow at the Peterson Institute for International Economics in Washington. Before we get into it, I want to provide a quick update on where things stand in President Trump's latest trade war and a quick advertisement. If you've not already done so, do check out the Peterson Institute's new tariff tracker on the PI website, titled 'Trump's Trade War Timeline 2.0: An Up-to-Date Guide.' Okay, at the moment, President Trump has tariffs coming on European steel and aluminum under Section 232. This is that National Security Law. Those are scheduled to go into effect on March 12th. Trump has ordered his US Trade Representative to look into EU member states' Digital Services taxes on American tech companies, and so we may see US tariffs on Europe there sometime in the future. He also has the reciprocal tariffs investigation ongoing. That one is due to wrap up on April 1st, so we could see higher US tariffs on whatever European products have a higher current tariff rate than their US tariff equivalent through that rationale, or we could just see 25% tariffs on Europe, like President Trump said at the cabinet meeting. There is obviously still a lot of uncertainty, but what we also know is the likelihood of President Trump imposing tariffs on Europe seems to be increasing by the day. On March 4th, he put another round of 10% tariffs on China. Much more surprising was President Trump's decision that day to also impose 25% tariffs on most everything the United States imports from Mexico and Canada after initially pausing that tariff threat for 30 days back in February. Apparently, tariffs on historical US Military Allies are not just threats this time around. They are happening for real. Okay, Rert, to Europe. Before we get into anything specific about tariffs, let's set the scene for some of the underlying economics here. How interdependent are the US and European economies?"

"So first, the European Union is by far the most important economic partner of the US. The second point that I would like to make up front is our relationship is balanced. No one is taking advantage of each other. We actually have a shared interest to neutral this relationship, and it's going very well. What people also maybe don't know is that our bilateral trade in goods and services has doubled in the last 10 years. Where else do you have that growth? American exports to the EU in the last 3 years are up 35%, so that creates jobs and prosperity in the US. There sometimes is the idea that because of a deficit in Goods, there is an imbalance, but let me now start with something else. Let me start with Services. The US last year exported $462 billion worth of services to the EU. That leads to a surplus of 117 billion. We never talk about that. There is a Goods deficit of 169 billion, but if you add up the sums, you're left with 50 billion difference. So that's not great, and that's not a lot in a 1.7 trillion relationship per year. It's about 3% on the depth and the importance of the relationship. Again, I don't want to overload the figures here, but be aware that over 50, almost 60% of what the US or the EU invest in the world goes to the partner across the Atlantic. And just to give you an example, there are 3 and a half million jobs directly dependent on EU investment in the US. So if you start messing with this relationship, you will actually affect jobs in the US. What people can really visualize is the biggest BMW plant of the world is in South Carolina. It's not in Munich, and there are similar examples of the deep investment relationship. So that's my first point, a deep and balanced relationship."

"So President Trump, when he's talking and focused on the unbalanced relationship in his view, he has a very, very narrow perspective, which is just looking at Goods trade, all the cars coming in from Germany and the rest of Europe into the United States and many fewer cars going back in return. But there are a lot of cars produced by European companies in the United States, and there's an imbalance in the other direction when it comes to services. And so those services are going to be things like Netflix and the internet companies, financial services, and when you put all those things together, the relationship is much more balanced. That being said, it looks like there's a really good chance that President Trump is going to end up putting some sort of tariffs on European Goods coming into the United States. So what I want to ask you about next is Europe's preparedness for this. Now, obviously, you were part of the commission the first time around when President Trump was in office between 2017 and  early 2021. You didn't take up your job as head of the trade relationship with the United States until 2019, so you weren't there for all of it, but you got to see some of it. What can you tell us about things that happened in the trade relationship with the first Trump Administration in Europe that might be useful Lessons Learned for this time around? This is not the first time we are either threatened or experiencing US tariffs, and you refer to the Section 232 tariffs, which went into place on steel and aluminium and which were threatened on cars in that period. I think the experience was at the time twofold. First of all, you have to prepare yourself from a position where you can actually also take counter measures, but even more importantly, you have to try to find a way to negotiate on these issues. And this is what exactly what happened in 2018. We were able to—and start me with the good news—to avert the car tariffs with a negotiation, doing a deal, which is one of the things that President Trump likes to do. So we did a deal to buy more liquid natural gas and to buy more soybeans from the United States in return for not having tariffs put on cars. We were less successful on the other threat and then implemented tariffs at the time, which were the tariffs on steel and aluminium, and here we actually took countermeasures. Took a while to do that because we have a procedure to go through, but we used a legal procedure for the non-initiated under the GATT WTO Safeguard rules to countervail the tariffs with our own tariffs, and we did implement them. So on the Trump Administration, first Administration, we actually remain stuck with tariffs on both sides. I want to talk a little bit more about Europe's experience with countermeasures. As you mentioned, the EU was ultimately effective at being able to implement a sort of rebalancing when it came to the steel and aluminum tariffs, but just having this constant threat of other tariffs that were out there, you know, during almost the entirety of that Administration, there was a threat of 25% tariffs on cars, as you mentioned, there were also threats about potential tariffs if countries did Digital Services taxes. From an outsider's view, it seems as that was happening, it looks like Europe was learning that maybe have all of the policy levers that it might want available should something like that happen again. Tell us a little bit about some of the new policy instruments that the European Union has developed in the meantime since that first Trump Administration."

"Yes indeed, I think we learned a lesson from the first Trump Administration, and that is that we might not have all the tools for a similar situation occurring in the future.

With a similar situation, I mean what we call coercion: weaponizing of trade for any possible political objective, which was not done frequently, or at all, or a lot in the first 20 years of the WTO. So, it's actually from the experience with the car tariffs, plus certain things also happening on the other side of the globe, that we thought we need an instrument which allows us to counter any threats when we actually implement what we thought were legal, legal, non-discriminatory, balanced, proportionate policies. So, we came up with this idea of an anti-coercion instrument, which is a tool which allows us to take measures after a quite detailed procedure and within the rules-based international order against what we would define as economic coercion. One thing which also led to the creation of this instrument is the fact that WTO litigation, which is our preferred way to deal with any conflict, takes years, and there is no appellate body any longer which would actually give a final ruling. So, we wanted to be quicker, but let's be clear: the anti-coercion instrument is not a rapid response mechanism.

Let's get into some of the potential ways in which use of this new anti-coercion instrument might play out. So, let's go through a hypothetical. Let's suppose President Trump decides to raise U.S. tariffs on European exports. You know, it could be for any, any number of reasons that he's proposed already, but let's suppose it's this reciprocity rationale where he's basically said to countries, "Um, if you don't, you know, lower your tariffs to my level, I'm going to raise my tariffs to your level." Let's suppose he just does that. How would the EU actually operationalize this anti-coercion instrument in practice? How does it work? It is a carefully tailored tool which starts with an investigation to establish the facts. So, is there coercion? Then it goes into a procedure where you will try to negotiate away the issue. So, it's not immediately, even if there is a finding of coercion, that you take measures; you try to negotiate, talk softly with a big stick, maybe you can say that. And only when that fails, then there is the possibility to take countermeasures. And what is also innovative here is that the countermeasures which can be authorized under this procedure are quite broad. So, it's not only goods, because that might not be effective, and in any case, with tariffs on goods, you shoot yourself in your own foot because you make it a tax on your own imports. So, the instrument allows also measures in other areas like services, government procurement, or the protection of intellectual property rights.

Now, the European Commission has never actually utilized this anti-coercion instrument in practice; it's primarily a deterrent. So, we don't have any experience for how it would do so, but it's an interesting intellectual exercise to think through how the retaliation actually might be used. One option is, of course, just to impose tariffs on goods, but if your relationship is asymmetric and you don't have a lot of goods imports from the United States coming in that are easily replaceable, maybe that wouldn't be an effective deterrent. So, maybe you'd go with something else. The other options you suggested—maybe you try to put a discriminatory tax on U.S. services exports. Some of the versions of the original Digital Services Taxes coming from EU member states like France did seem really designed to target American big tech companies. If memory serves, French Finance Minister Bruno Le Maire called the French one the "GAFA tax" for targeting Google, Apple, Facebook, and Amazon at the time. Or the third one you mentioned is maybe the EU retaliates by going after intellectual property rights protection. That one has always been a little unclear to me how you would put that into practice. For example, suppose the EU tries to punish the United States by withholding IP protection for American companies. Maybe the idea here is to try to hurt Hollywood by giving away free rights in France to show American movies. While French consumers might like that, to my mind, where the retaliation breaks down is France's own movie industry would likely be super annoyed, and that's because French citizens are now getting free American movies, and so they're less likely to pay to watch French movies. Anyway, these are interesting ideas, but perhaps still some kinks to work out in terms of implementation, but we will be tracking them closely.

Okay, you also mentioned that the ACI is not a rapid response instrument. In response to Trump's tariffs this time around, we have seen countries like China and Canada retaliate in potentially just days. Do we have any sense at all for how long we're talking about here between when the EU begins an ACI investigation at the point at which countermeasures could be imposed? Is it four weeks, 6 months, 18 months? How long are we thinking? Well, the regulation, if you look at it, it has certain deadlines which run into several months normally. So, I think it's safe to say it's not going to take four weeks; it's going to take longer for the investigation to conclude and to do all of this. And this is the point that is difficult to verify: how much time we can spend on negotiations? Because I really want to put the cursor on the fact that we are dealing with an administration in the U.S. who likes to do deals, and we have stretched out our hand and say we're ready to do deals, which is one phase of the instrument. Ultimately, it will take quite a while, also because of the politics involved.

Let's go back to one other thing with the anti-coercion instrument. Talk us through how the European Commission thinks about this ACI instrument in a WTO context. Normally, one would say that if a country is going to do something to my trade that I don't like, my response isn't to take matters into my own hands, but it's to bring a dispute to Geneva and the WTO. And that's the line that I've understood the EU to be pushing for, um, not only for itself but for others as well, for decades. How does the ACI fit into this? Yeah, make no mistake, we still push—and this is the possibility to do a little advertisement for the WTO, which is a little bit the background now—we still are multilateralists and believe that conflicts should be solved wherever possible in the WTO, because the value, the predictability of WTO rules, is something which we cherish a lot. But we've also come to the conclusion that this is not always the only possible response to safeguard our rights, for the reasons I mentioned: the WTO dispute settlement is not functioning, it wasn't meant to look at economic coercion situations, it was meant to look at commercial, if you wish, disputes or misled legislation. So, what we did with the anti-coercion instrument to make sure that the legal basis is compatible with WTO—and this is, if you look at the explanations, the explanatory part of the regulation—it clearly sets out that this is based on international law, the UN Charter, the duties of countries to cooperate and refrain from coercion, etc., etc. So, we grounded it in public international law in order to have a solid base to react—not to act, to react—to a breach of law. And for this, we needed the public of the international law scene, because the WTO on its own doesn't provide the measures or the tools to actually react to this situation.

But just as we've never seen the Commission operationalize use of the anti-coercion instrument in practice, we also haven't seen litigation under the WTO that might challenge the legality of the anti-coercion instrument actually play out and any WTO rulings to know just how consistent or inconsistent it might be. So, that in itself is an open question. [Music] It's certainly the case that President Trump does like to do deals as well. What can you tell us about some of the other lessons learned from the EU's side from the first administration? Just reading the reporting, it seems as if some senior-level officials have already come to Washington to meet their counterparts, uh, in the Trump administration to get some of these conversations already going. You will have seen that one of the first things the new Trade and Economic Security Commissioner—meaning minister of the EU—has done was go to the United States, and you will have seen that many other leaders from the European Union, heads of state, went to Washington to also pass that message that we're open for business. I think we are serious from the EU side to try to find something which would satisfy our American friends or our American present administration. And you will have seen from the public statement that the first thing we always say is we're ready to look at your demands and negotiate. And there were actually things mentioned—cars was mentioned, passenger cars. We do have a higher tariff than the U.S., and that has been a constant feature in some of the remarks of our American counterparts. And there are other things that we can think about. I mean, obviously, we have a strong interest in any case to buy weapons; we already buy a lot of weapons in the U.S., and with the present situation, that will only increase. Let me also add that last time, the focus was on energy, where in any case we had to diversify and wean ourselves off the Russian supplies, which is now becoming even more important. And the United States is now our biggest supplier already on LNG, and there is a potential to do more. So, there are actually real-life interests here that we could maybe look at and see what can be done, and that has been, I think, a constant message from the EU side.

One of the challenges, obviously, in the timing of what's happening here with these tariff threats is, simultaneously, you have major developments taking place in the Russia-Ukraine war. President Trump clearly wants to settle the war; he had a blow-up in the Oval Office last week with Ukrainian President Zelensky, and the White House just announced it's at least temporarily suspending military aid to Ukraine. I think, as a policy matter, President Trump wants to reduce U.S. involvement in NATO and its role in providing military security to Europe. How do these other non-trade issues, but nevertheless still issues between the United States and Europe that are incredibly important—how are they likely to affect Europe's trade response to any tariffs that the Trump administration might impose? I don't have the answer to that. I mean, I think the trade officials—and I'm a former trade official—we know that we are not acting in a vacuum, so the bigger picture is always there. And it's true to say that we are at a very important and difficult point right now with the situation in the Russian aggression and the developments in the United States. The European leaders, be it from the European Commission, be it from the member states, have been quite clear to say that a firm response would be needed, so basically arguing a separation of the trade discussions from bigger political things, which was something which we were able to achieve in the last [Music] decades.

Now, I want to turn to the European Union's relationship with third countries. During President Trump's first term, there were a number of other countries out there who made a big show of being able to conclude free trade agreements in the absence of the United States, the message being something like, "Hey, we can do trade liberalization without you." The EU itself closed an important deal with Japan, for example. More recently, in December of 2024, there was news that the European Commission had agreed to a deal with Mercosur. This was one that, I think, you cover not just trade relations with the United States but everybody in the hemisphere, so it's one that you had a big role in. What do you think? Should the United States be worried that there's going to be a proliferation of free trade agreements amongst everybody else this time around? I'm not sure whether they should be worried, and I just read that they also gave up the APEP, this initiative with Latin America, if I'm correctly informed. So, they clearly don't want to do what we do. But I think it is true that those countries who are interested in maintaining an open trading system based on rules and predictable, stable relations might have more interest to work together. Let's put it simple as that. So, with a situation as it is now, there's, I think, a heightened or a better incentive to actually conclude deals built on trust with those partners that you do trust. And that, I think, means that also we, from the EU, are trying to finish the negotiations, and we have finished New Zealand, Chile, update—I think there is a good chance that we will update the Mexico agreement, because Mexico also has an interest to have partners with a predictable policy environment. And Mercosur is, of course, the biggest part, and I hasten to add that we're also restarting the discussions with India, which is, of course, also a hugely important partner. All of that, I think, in the present context, makes a lot of sense.

There's another really important third country out there that is, of course, China. Also, during the Trump administration's first term, the EU, the United States, and Japan were actually working together somewhat behind the scenes on something called the Trilateral. My understanding is you were part of this, and the goal was to think hard about potential new rules to address some areas of common concern when it comes to China, and in particular, Chinese subsidies. Tell us more about that experience of working with the first Trump administration on that area of common concern. Well, I think for much of the last years, there was no big disagreement about the analysis on what needs to be fixed in the rulebook in the WTO if you really want to address non-market economy practices as we have seen them develop over the last two decades, maybe. So, the Trilateral was one of the first attempts to look at the rulebook and say, "What would it be if we just sat together and found a way to deal with some of these practices?" And that was actually quite successful, uh, and the idea was to spread this to like-minded countries and make an initiative and find a way to implement these things later on. It didn't really go very far after this first ministerial meeting early 2020; there was no follow-up in the next couple of years. That was how the EU dealt with China with the first Trump administration.

How did things change when the Biden administration arrived in early 2021? Was there any progress there between the EU and U.S. on how to address, or at least how to think about, the China challenge in specific economic areas? We then had very long discussions in the context of the Trade and Tech Council with the United States on the China challenge, China being the predominant preoccupation of any U.S. administration the last 10 years, 15 years. And we actually were able to do a few things to coordinate and cooperate on China-related issues, be it on medical devices, where we jointly wrote to China on their practices on public procurement, be it on trying to find ways to deal with some of the cyber threats, and so on. So, what I think the difference is, is the response to these issues, because we didn't believe that putting tariffs on China—and don't forget the original justification was a 301 intellectual property case—we also have issues with that, but we tried to find other ways. We have a very active cooperation on intellectual property with China, which works or doesn't work, you can argue about that, but we wanted to stay within the rulebook, let's put it like that, which is quite complicated.

What about Chinese steel and aluminum overcapacity? That was one that President Biden and European Commission President Ursula von der Leyen promised publicly back in 2021 that the U.S. and EU would work on together. How did that work agenda go? The most promising enterprise in all of this, in my view—but maybe I'm biased because I was also involved in that—was the attempt to forge a coalition of the willing, starting with the EU and the U.S., on steel and aluminum, which was the most egregious case of overcapacity flooding the world markets. The OECD worked on it in a steel forum, and we were crafting rules, very detailed rules, again, on what kind of subsidies are allowed or not to keep your steel industry afloat, including what kind of steel you would like to favor for reasons of low carbon content. So, there was a climate aspect, and those negotiations went quite far in the level of detail, and I wouldn't say we were there to conclude, but we were close to conclude, also because we would have to make some compromises on imposing, in one way or the other, higher tariffs on China. So, while we differed sometimes on the means, I think we moved a lot closer on the analysis on what is wrong with Chinese behavior. We'll see how that goes, but it's clear that there will be further discussions on how best to deal with, in particular, overcapacity, because what we have seen on steel and aluminum is only the beginning. There is enormous overcapacity in many sectors, something which we actually knew for a long time, but nobody really has a very convincing answer how to deal with that, because there are no rules on many of the practices.

So, on that point, is it possible for policymakers and politicians to be working on both portfolios at the same time? If you're a European Commission trade official, to be dealing with the threats of tariffs coming in from the United States and how you have to respond to those, and then at the same time working with the United States on a common challenge that is China? Is it possible to segment and compartmentalize in a way that ultimately is going to allow you to make progress on that second issue in particular? I think it is on us to at least try to do that. I think we certainly were able to do this to some extent, also, I think, with the first Trump administration, because, you know, doing nothing is not the default option. I mean, the issue is there, and we are more effective if we deal with this together. I can't really speak on the present administration; I have no idea whether they want to cooperate with anyone on China. I think we're going to find out. Yeah, it's going to be complicated.

That's clear. Media reports are that China is now reaching out to Europe diplomatically, almost as if to say, "You're being bullied by your old friend, those Americans, who seem to be going in a different direction. Why don't we be better friends? Put all those projects that you were working on with the Biden people, maybe the first Trump people, put that behind you, and let's do more together." In light of all the U.S. tariff threats, what do you think are the implications for Europe's relationship with China today? Well, maybe the first thing to say is that China is already experiencing the tariffs on 10% and now 20% and so on, and that, of course, shows also that China has an interest to work with others to do something on this. But I do think, despite the charm offensive that actually did happen some months ago and maybe is continuing, we have to keep a cool head and look at our interests here. We have always been maintaining that we have to counter the unfair practices of China, but not everything China does is unfair. So, we also have to cooperate in those areas where that is not at stake. It's a big commercial partner; it will not go away. But we also have to be clear that there are limits, and the one thing which you can see in the European theater playing out is there are a lot more measures taken—anti-dumping, anti-subsidy, foreign subsidy regulation—we haven't mentioned that. So, I think we also intend to defend ourselves vis-à-vis the unfair practices of China.

As my last question for you, it's one more about China. In your view, has the European perspective on China changed over the last few years? So, Chad, let me remind you that President von der Leyen actually, at the World Economic Forum this year, talked about a "China shock" as a threat because of Chinese export subsidies. So, I think the rhetoric has changed a little bit, also because we're a little bit clearer about some of the state-sponsored policies that we all are worried about. We have certainly also taken a hard look at some of the things which happened in China, including that we were suffering from a coercion case on Lithuania. As I said, we try to separate out what is economically normal behavior and where do we have to be careful. And I do think that we are a bit more critical about the effects of the Chinese policies, the way also they treat European companies in China, without becoming paranoid. I think we really have to make a case, and this is why we took a long time to do a proper investigation on electric vehicles, for example. On the one hand, we agree that there is an issue, but on the other hand, we did a proper investigation; we came up with a differentiated response. So, we didn't slap a tariff on everyone; we really tried to keep the rules, also vis-à-vis China, where there are rules that we can assert.

Thank you very much. You're welcome, and that is all for Trade Talks. A huge thanks to Robert Schuman, a former trade official at the European Commission and now visiting professor at the College of Europe. Thanks to Melina Cobb, our supervising producer; thanks to Isabelle Robertson, our audio producer; and thanks to Sam Elizon, digital. Please subscribe to Trade Talks on Apple Podcasts, on Spotify, and Amazon Music, or wherever you get your podcasts these days. You can follow Trade Talks on Blue Sky or on X, where we are at Trade_Talks—that's not one but two underscores—at Trade_Talks. And if you do look for us there, you will see this week a special photo posted of an old friend as well as a new addition to the Trade Talks family.

'''

