

= 0008 China’s “maritime road”
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css



'''


== China’s “maritime road”

To measure the maritime (a.)海的；海事的 road’s impact, we tested three benefits it could offer China.

If the road were *a resource grab* 抓住,攫取, its projects should cluster in places /that sell raw materials that China imports.

If its aim were *to boost (v.) trade*, it should track the busiest routes /used by Chinese shipping today, or where *trade is likely to grow fastest*.

And if it were intended *to secure 保卫；使安全 current trade routes*, its ports should sit near *choke （掐住喉咙）使窒息 points* — areas /whose closure （永久的）停业，关闭；倒闭 would force (v.) goods *to travel circuitously* 迂回地；曲折地  — or *in places* that offer (v.) alternative routes.



[.my1]
.标题
====
.maritime
adj./ˈmærɪtaɪm/ connected with the sea or ships 海的；海事的；海运的；船舶的/靠近海的 +
-> -mar-海 + itime

[.my2]
为衡量海上丝绸之路的影响，我们检验了它可能带给中国的三个好处: +
→ 如果这条“路”是为了抢夺资源，那么项目应集中在中国进口原材料的供应地。 +
→ 如果是为了促进贸易，那么项目应紧盯中国如今最繁忙的货运航线，或是对华贸易可能增长最快的地区。 +
→ 如果是为了保护现有贸易路线，那么项目建设的港口应靠近咽喉要道（一旦封锁将迫使货物绕行）, 或备选航道上的要地。
====


We tested these explanations /by using them to predict /if countries host (v.) a BRI port. The results were conclusive 结论性的；不容置疑的；确凿的 .

[.my2]
为检验这些解释是否合理，我们利用它们来预测, 各个国家能否吸引到“一带一路”的港口项目。结论是明确的。

After holding *other factors (constant* 不变的；固定的；恒定的), *there was no statistically significant  有重大意义的；显著的 link between* having a BRI port *and* ① exporting (v.) raw materials that China wants, or ② having *high current or projected (a.)计划的，规划中的,推断的 trade* with it.

[.my2]
在其他因素不变的情况下，建设“一带一路”港口, 与出口中国所需的原材料, 在统计上没有显著关联，与"当前已存在或未来可能发生的 大笔对华贸易"的关联, 也不显著。

*In contrast* 相比之下 , 主 the “trade-protection benefit” —  #either# *the value of Chinese trade* (in a country’s waters) /#*multiplied (v.)乘以 by*# *the extra distance* (goods would have to go /*if* those routes were shut), #or# *the amount of trade* (that would be diverted to a country /*if* shipping were disrupted elsewhere) — 系 *was a good predictor*.

[.my1]
.案例
====

image:/img/0126.svg[,80%]

[.my2]
相比之下，“有利于保护贸易”是个有效的预测根据，其计算方式或者是 : 用"一国海域内的对华贸易额", 乘以"货物在现有路线封锁的情况下须绕行的额外里程数"，或是乘以"因货运在其他地区受阻, 而转移到一个国家的贸易量"。
====

Given 假设事实;考虑到 two otherwise average countries, 主 *one* with a high trade-protection benefit (like Libya) 系 *is 2.7 times likelier* to host a BRI port /#*than*# *another* with an average benefit (like Liberia).

[.my2]
在其他条件相当的两个国家之间，更“有利于保护贸易”的国家（如利比亚）, 吸引“一带一路”港口项目的可能性, 是此方面优势不明显的国家（如利比里亚）的2.7倍。


[.my1]
.标题
====
.BRI
Belt and Road Initiative 一带一路倡议

.contrast
[ CU] ~ (between A and B) | ~ (to/with sb/sth) : a difference between two or more people or things that you can see clearly when they are compared or put close together; the fact of comparing two or more things in order to show the differences between them 明显的差异；对比；对照 +
- *There is an obvious contrast between* the cultures of East *and* West. 东西方文化之间存在着明显的差异。
====


'''

== <pure> China’s “maritime road”


To measure the maritime road’s impact, we tested three benefits it could offer China.  +
If the road were a resource grab, its projects should cluster in places that sell raw materials that China imports.  +
If its aim were to boost trade, it should track the busiest routes used by Chinese shipping today, or where trade is likely to grow fastest.  +
And if it were intended to secure current trade routes, its ports should sit near choke points — areas whose closure would force goods to travel circuitously  —  or in places that offer alternative routes.


We tested these explanations by using them to predict {if countries host a BRI port}. The results were conclusive. After holding other factors (constant), there was no statistically significant link between having a BRI port and ① exporting  raw materials that China wants, or ② having high current or projected trade with it. In contrast,  the “trade-protection benefit” — either the value of Chinese trade (in a country’s waters) multiplied by the extra distance (goods would have to go if those routes were shut), or the amount of trade (that would be diverted to a country if shipping were disrupted elsewhere) —  was a good predictor. Given two otherwise average countries,  one (with a high trade-protection benefit (like Libya)) is 2.7 times likelier to host a BRI port than another (with an average benefit (like Liberia)).

'''


