= 0260
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 260: Business Trends.
This is English as a Second Language Podcast number 260. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com for more information about this podcast and to download the Learning Guide for this episode.
Our episode is called “Business Trends.” Let's get started.
[start of story]
Today, I’m going to be giving you a brief overview of the trends that are likely to affect our industry in the next ten years. It’s difficult to predict the fads that affect how the general public thinks and behaves. However, by looking at recent polls, we have a good idea about one area that is likely to have a dramatic influence on the way we do business down the line.
The trend that I’m talking about is the environment. The biggest concern right now across major business industries here and in other parts of the world is about how “going green” will affect company outlook. The growth of environmentally-friendly products has been off the charts in the past five years, and this trend is likely to continue for at least ten more years.
If you’ll look at this chart here, you’ll see what the major trend reports are forecasting. It’s my opinion that it’s time we sat up and took notice.
[end of story]
Our story today is called “Business Trends.” A trend, “trend,” is something that changes in one direction over time, so it is something that goes up or goes down. The trend for the price of gasoline in the United States has been going up - the way things are moving, either up or down.
The story begins by saying that “Today, I’m going to be giving you a brief overview of the trends that are likely to affect our industry in the next ten years.” An overview, “overview,” is a general description of something, not giving a lot of detail but just giving you the general points about something. In this case it's an “overview of the trends that are likely to affect,” or influence, “our industry.” Industry, “industry,” is another word for the companies that are involved in making a certain kind of product or service. You could have the automobile industry; these are companies that make cars or automobiles.
I go on to say that “It’s difficult to predict the fads that” will “affect how the general public thinks and behaves.” To predict, “predict,” means to say what will happen in the future. I predict that if you listen to ESL Podcast every day, your English will get better - that is what I think will happen in the future.
The fad, or the fads, “fads,” are things that are popular for a short period of time, and then they're not popular. This is true, for example, with certain kinds of dances that become popular, and then five years later nobody is doing that. So, a fad is something that is popular, but only for a short amount of time - a short period of time.
So, “It's difficult to predict the fads that affect how the general public thinks and behaves.” The expression general, “general,” public refers to the people in a society - the ordinary people - the citizens. It's a term to talk about everyone in a particular country or a particular culture or particular society. We often use this expression to contrast it or to compare it to a smaller group of people.
So, it's difficult to predict how the general public is going to behave towards certain fads. “However, by looking at recent polls, we have a good idea about one area.” Polls, “polls,” (singular is poll, “poll”) is a survey or a questionnaire that gets people's opinions about something. You could take a poll to see if the President of the United States is popular in the US. That's a poll; it's an opinion, when you ask people their opinion.
So, according to the polls, “we have a good idea about one area that” will likely “have a dramatic influence on the way we do business down the line.” Dramatic, “dramatic,” means large or important; sometimes it can mean very exciting. “It was a dramatic scene in the movie,” means it was a part of the movie where there was a lot of emotion or it was exciting.
The expression, down the line, “line,” means in the future. You could say, “Well, you're young now, and healthy, but down the line you're going to get old and sick.” That is a nice thing to think about, I guess!
I go on to say that “The trend that I’m talking about is the environment. The biggest concern” - the biggest worry - “right now across major business industries is about how 'going green' will affect company outlook.” The use of the word “across” in the sentence “The biggest concern right now across major business industries,” and so forth, means in all, or in every, or in each. So, “across major business industries” means in all of the major business industries or in each of the major business industries.
The major trend here is about, or “concern is about how 'going green' will affect company outlook.” The expression to “go green,” like the color green, means to begin doing things that are good for the natural environment - to try not to do things that will harm the air and the water and the soil or the ground. That's “going green,” and that has become more popular in many countries. Outlook, “outlook,” means the future - what you think will happen or what you believe will happen in the future. In this case, it's the future of the company - will the company make money, or will they lose money?
“The growth of environmentally-friendly products has been off the charts in the past five years.” Growth, “growth,” means increase in size or popularity, so the increasing number “of environmentally-friendly products.” The expression “environmentally-friendly” means good for the environment; something that will help the air and the water of the environment, that's the use of this word “friendly.” When we say something is “customer-friendly,” we mean that it's easy for the customer - the person buying the product - to use. So, “environmentally-friendly” are products - things - that are good for, or do not hurt, the environment.
I say that “the growth of these products has been off the charts.” The expression “off the charts,” “charts,” means very high - much higher or much bigger than what we thought - than what we predicted. A chart, “chart,” is usually a square or rectangular box that presents information for people so they can understand it more easily.
At the end of the story, I say, “If you’ll look at the chart up here,” meaning the information that I have - numbers, and so forth, on a big screen or on a big piece of paper - “you’ll see what the major trend reports are forecasting.” To forecast, “forecast,” means to predict. It's another word for saying what will happen in the future. We often use this word when we are talking about the weather. You can look in the newspaper and read the weather forecast; it's the prediction about what the weather will be. Of course, it will always be wrong!
“It’s my opinion that it’s time we sat up and took notice,” I say at the end. To “sit up and take notice,” that expression means to begin to pay attention to something important, something that you weren't paying attention to before.
I hope you were paying attention to our explanation. Now we'll listen to the story again, this time at a normal speed.
[start of story]
Today, I’m going to be giving you a brief overview of the trends that are likely to affect our industry in the next ten years. It’s difficult to predict the fads that affect how the general public thinks and behaves. However, by looking at recent polls, we have a good idea about one area that is likely to have a dramatic influence on the way we do business down the line.
The trend that I’m talking about is the environment. The biggest concern right now across major business industries here and in other parts of the world is about how “going green” will affect company outlook. The growth of environmentally-friendly products has been off the charts in the past five years, and this trend is likely to continue for at least ten more years.
If you’ll look at this chart here, you’ll see what the major trend reports are forecasting. It’s my opinion that it’s time we sat up and took notice.
[end of story]
The script for this podcast was written by Dr. Lucy Tse.
That's all we have time for. From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
overview – a general description of something without very much detail
* The first chapter of this book is an overview of US history but the rest is about what has happened in the past few years.
trend – something that changes in one direction (up or down) over time
* There is a strong upward trend in the price of cigarettes and other tobacco products.
industry – the companies that are involved in making a certain kind of product or service, such as the energy industry, technology industry, or automobile industry
* Duncan is an engineer who works in the oil industry.
to predict – to say what will happen in the future
* Some people predict that we will have flying cars by the year 2030.
fad – something that is popular for a short period of time; things that large groups of the public suddenly like to do and then suddenly forget about
* When we were children, rolling our pants up to our knees was a big fad.
general public – the people in a society; citizens; the ordinary people
* The general public doesn’t know very much about the national economy and how it works.
poll – a survey or questionnaire that collects people’s opinions about something
* According to the latest poll, the president has lost popularity among Americans.
dramatic – very exciting, large, and important
* Why did the company have such a dramatic improvement in its sales last month?
down the line – in the future
* You’re young and healthy now, so it may not seem very important to exercise regularly, but down the line you’ll be glad that you did.
across – in all; in every; in each; in every part of something
* Across most types of work, people think that they should earn more money.
to go green – to begin doing things that are better for the natural environment; to begin to do things that help to protect the environment
* Our restaurant decided to go green by using real plates instead of paper plates that have to be thrown away.
outlook – the anticipated future; what one believes will happen in the future
* In the past year, the company’s sales have fallen and most of the employees have had to quit. The outlook isn’t very good.
growth – increase in size or popularity; rise
* Recent growth in the use of personal web pages has changed the way that people communicate with each other.
environmentally-friendly – good for the environment; helpful for the protection of the natural environment
* Karen always buys environmentally-friendly paper, even though it’s more expensive than regular paper, because she knows that the manufacturers aren’t putting dangerous chemicals into the water.
off the charts – very high; much higher or bigger than what was expected
* Economic growth in parts of Asia is off the charts. China’s economy is growing much faster than anyone thought it would.
chart – a square or rectangular box that presents information as an image so that it is easier to understand
* This chart shows that 47% of Americans like the new law, 51% don’t like it, and 2% don’t know how they feel about it.
to forecast – to predict; to say what will happen in the future, especially with numbers
* The experts forecast that Acme Corporation will open at least four new offices next year.
to sit up and take notice – to begin to pay attention to something important
* Scientists have known about global climate change for years and now the general public is finally sitting up and taking notice.
Comprehension Questions
1. How is the company going to predict fads?
a) It will give an overview of the trends.
b) It will look at how the public thinks and behaves.
c) It will study recent opinion polls.
2. Why is it time to “sit up and take notice”?
a) Because people need to sit up to be able to see the chart.
b) Because people need to pay attention to the major trends.
c) Because people need to stop the growth of environmentally-friendly products.
Answers at bottom.
What Else Does It Mean?
poll
The word “poll,” in this podcast, means a survey or questionnaire that collects people’s opinions about something: “This is an interesting poll about whether people think that watching television is bad for children.” We use the word “poll” with the verb “to conduct”: “Do you know if anyone has conducted a poll to find out why country music is becoming so popular?” As a verb, “to poll” means to ask a lot of people what they think about something: “A research company is polling more than 2,000 people to find out what they think about the president’s plan to give more money to health and education.” The phrase “at the polls” means in an election: “How did your uncle do at the polls? Was he elected?”
chart
In this podcast, the word “chart” means a square or rectangular box that presents information graphically so that it is easier to understand: “This chart shows how quickly babies grow in their first year.” We often use computer programs to create bar charts, line charts, and pie charts that help us explain information more clearly. The verb “to chart” means to monitor and write down how something changes over time, or where it goes: “The director is charting their progress on the project by asking for weekly reports.” Or, “As we sailed from California to Mexico, we charted how many miles we traveled each day.” A chart is also a ranking of the popularity of music recordings: “The Beatles had a lot of number one hits on the music charts.”
Culture Note
Each year, more than 600,000 small businesses are started in the United States. Some of them do well, but many others “fail” or are unable to make money and/or stop doing business. These small businesses face many “challenges” (difficulties) in competing with larger businesses. One government agency, the US Small Business Administration (SBA), was created in 1953 to help Americans start and build their businesses.
The website for the Small Business Administration, www.sba.gov, provides a lot of information and services to help small businesses succeed. It offers “financial assistance,” which is money to help businesses get started. Some of the financial assistance is in “grants” (money that the businesses can keep) and some of it is in “loans” (money that must be paid back). The SBA also offers businesses free “training” (education) about how to manage a business, pay “taxes” (money paid to the government), plan for the future, and increase sales to customers. The SBA provides special “assistance” (help) to businesses that are owned by women or “minorities” (people who are from a minority group in the US, such as African Americans, Native Americans, Latinos, and Asian Americans).
The SBA has many offices in each state. Small business owners can go to these offices to get training or to ask the experts questions about their businesses. If you are interested in starting a small business, it’s a good idea to speak with the SBA. The people there can help you learn how to “register” (sign up) your business with the government, and what kind of financial “records,” or important papers, you need to keep.
Comprehension Answers
1 - v
2 - b