= 0263
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 263: Getting Older.
This is English as a Second Language Podcast episode 263. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com and take a look at all of the new features we have on the website. You can also download a Learning Guide for this episode that contains all of the vocabulary, definitions, cultural notes, additional explanations, and a complete transcript of this episode.
In this episode, we're going to listen to a dialogue between two people, talking about what it is like to get older—something I think about everyday! Let's get started.
[start of story]
Angelica: Oh sorry, what was I saying? I lost my train of thought.
Yann: You were telling me about the book you’re reading.
Angelica: Oh, yeah. I must have had one of those senior moments.
Yann: Welcome to the club. That’s what happens when you’re over-the-hill like we are.
Angelica: We’re not over the hill! You may be an old geezer, but I still like to think of myself as middle-aged. Isn’t 70 the new 60?
Yann: That’s what they say, but I don’t mind aging. I may be a little absent-minded now and then, but I’m not senile. What I can’t stand is being treated like I am. The other day, I sat at a table at a restaurant for 20 minutes while the waitress ignored me. She waited on all of the tables around me first, and when she finally came to take my order, she didn’t even apologize.
Angelica: Ageism is everywhere. What I hate is to be talked to like I’m a child. Some people think that if you’ve got gray hair, you’re not all there. I’m as sharp as ever.
Yann: I know, but do you know what we’re doing?
Angelica: What?
Yann: We’re griping. That’s what old people are supposed to do all the time, right?
Angelica: You’ve got a point there. Let’s go do something more productive before anyone notices!
[end of story]
Our dialogue begins with Angelica saying to her friend Yann, “Oh sorry, what was I saying? I lost my train of thought.” Angelica can't remember what she was talking about. To forget what you are saying is to “lose your train (train) of thought.” This is when you are talking to someone and sometimes in the middle of a sentence or an idea that you are expressing, you forget what you are saying. This happens to me…what was I saying? Oh, this happens to me all of the time.
Yann says, “You were telling me about the book you’re reading.” Yann is telling Angelica—reminding her what they were talking about. Angelica says, “Oh, yeah. I must have had one of those senior moments.” To have a “senior (senior) moment” means to forget something. When you forget something, as sometimes people who are getting older do, we call that a “senior moment.” The word “senior” is used in the United States to refer to those who are older. Usually over 65 years old you would be called a “senior,” sometimes a “senior citizen” is used. A “citizen” is someone who is part of a certain country, so “senior citizen” or “senior” are both used to describe someone who is older.
Yann says to Angelica, “Welcome to the club.” The expression “welcome to the club” is used to show someone that you have had the same experience that they are describing, usually a negative experience, but not always. For example, you are talking to someone about how difficult it is to raise children—to have children, and the other person says, “Welcome to the club,” meaning I have those same problems; I understand what you're saying.
Yann says that having a senior moment or losing your train of thought is “what happens when you are over the hill” (hill). To be “over the hill' means to be too old to do something well, or, simply, to be very old. We also use the expression “over the hill” to mean on the other side of a hill. A “hill” is like a small mountain or a mound, so to be “over the hill” means to be on the other side of the hill. The expression is related to this meaning about being too old, if you think of life as a hill that goes up in the beginning, and then you reach the top, and then you start going down. Being “over the hill” means you are starting to go down—you're at the last part of your life, or the last stage of your life. That's being “over the hill.”
Angelica says, “We’re not over the hill!” She then jokes with Yann by saying, “You may be an old geezer, but I still like to think of myself as middle-aged.” To be a “geezer” (geezer) is a informal word to refer to an old man, but it's a rude or insulting, word. Not a nice thing to say, to describe an old man as a “geezer.” So, Angelica says that Yann may be a “geezer,” she's saying, “You may be a geezer, but I like to think of myself as middle-aged.” “Middle-aged” means you're not too young, you're not too old.
She then says, “Isn’t 70 the new 60?” When you have a change in fashion, in clothing for example, one year everybody wears black, and black is the most popular color—I'm speaking mostly about women's clothing—and the next year everyone's wearing yellow, and you say, “Oh well, yellow is the new black,” meaning it's replaced black; we no longer wear black, we wear yellow. In this expression “Isn’t 70 the new 60,” Angelica is saying that people used to think that being 60 was old, but now being 70 is old, and being 60 is not old.
Yann says, “That’s what they say,” that's what people say, “but I don’t mind aging.” To “age” (age) as a verb means to get older. Yann says, “I may be a little absent-minded now and then, but I’m not senile.” To be “absent (absent) –minded” (minded) means to be forgetful; to often forget things. There's an expression “the absent minded professor,” because professors are so involved in their own thinking that they forget to do normal things—”the absent-minded professor.”
Yann is saying that he's “a little absent-minded” because he's getting older and he forgets things, but he is “not senile” (senile). To be “senile” means not to think clearly or to be unable to remember something because you are getting old. It's usually considered a serious case, or a serious condition of someone who is old who forgets many things.
Yann says, “What I can’t stand is being treated like I am” senile. The verb to “stand” (stand) here means to able to tolerate something; it's okay. So, the opposite, “not be ale to stand” something, means that you cannot tolerate something; you cannot—we would also the expression—”put up with” something—you really don't like something. To strongly not like something is “not to be able to stand” something.
So, Yann doesn't “like being treated like he is” senile. To be “treated” (treated) means to have someone act in a certain way toward you; to have someone behave toward you in a certain way. “I don't want to be treated like a child” means don't talk to me—don't act like I am a child. To be “treated” has a couple of meanings in English; take a look at the Learning Guide today for more information.
Yann then gives an example of how he was treated like he was senile. He said, “The other day,” meaning recently, last week for example, “I sat at a table at a restaurant for 20 minutes” and “the waitress ignored me.”
Angelica says, “Ageism is everywhere.” “Ageism” (ageism) is discrimination against old people or unfair treatment of old people because they are old. And, ageism is against the law in some countries, including in the United States, for some jobs. If you do not hire someone because they are a certain age, you might be accused of “ageism.”
Angelica says, “Some people think that if you have gray hair, you’re not all there.” To “have gray hair” means to have hair that is white or silver in color because you are getting older. So, when you get older, you often get gray hair; it's what we call your hair when it gets white. “Gray” is spelled g-r-a-y; it can also be spelled g-r-e-y, which is more common in British English.
The expression that “you are not all there” means that you're not thinking clearly—that you are senile, or even that you're a little crazy. Someone says to you, “That man over there is not all there,” they mean they have some mental problem or they're not thinking correctly.
Angelica says that she is “as sharp as ever.” “Sharp” (sharp) means intelligent; to be able to think very quickly and clearly. Angelica is saying that even though she has gray hair and she is old, she's still “sharp”—she's still smart.
Yann then says, “you know what we are doing?” And Angelica says, “What?' And Yann says, “We’re griping.” To “gripe” (gripe) means to complain; to say what is wrong with something. “That’s what old people are supposed to do all the time, right,” meaning that's old people normally do. And, Yann and Angelica are talking about how they are not old, but now they are doing what old people do, that's what people say, is to complain about things.
Angelica says, “You’ve got a point there.” To say someone “has a point” (point) means that you understand what someone said, or you agree with what someone else has said. So, Angelica is saying I agree, “You've got a point there. Let’s go do something more productive before anyone notices!” To do something “productive” (productive) means to work very well; efficiently; to do a lot to make something to be useful—all of these are part of being productive.
Now let's listen to the dialogue, this time at a native rate of speech.
[start of story]
Angelica: Oh sorry, what was I saying? I lost my train of thought.
Yann: You were telling me about the book you’re reading.
Angelica: Oh, yeah. I must have had one of those senior moments.
Yann: Welcome to the club. That’s what happens when you’re over-the-hill like we are.
Angelica: We’re not over the hill! You may be an old geezer, but I still like to think of myself as middle-aged. Isn’t 70 the new 60?
Yann: That’s what they say, but I don’t mind aging. I may be a little absent-minded now and then, but I’m not senile. What I can’t stand is being treated like I am. The other day, I sat at a table at a restaurant for 20 minutes while the waitress ignored me. She waited on all of the tables around me first, and when she finally came to take my order, she didn’t even apologize.
Angelica: Ageism is everywhere. What I hate is to be talked to like I’m a child. Some people think that if you’ve got gray hair, you’re not all there. I’m as sharp as ever.
Yann: I know, but do you know what we’re doing?
Angelica: What?
Yann: We’re griping. That’s what old people are supposed to do all the time, right?
Angelica: You’ve got a point there. Let’s go do something more productive before anyone notices!
[end of story]
The script for today's podcast was written by…by…oh! Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
to lose (one’s) train of thought – to forget what one is saying, sometimes in the middle of a sentence or idea
* The director lost her train of thought in the middle of her presentation and had to start over.
senior moment – a moment of forgetfulness; when one forgets something, as older people may do
* If your grandma has a senior moment once a week, it’s probably not a problem, but if she starts forgetting things all the time, it’s a good idea for her to see a doctor.
welcome to the club – a phrase used to show someone that one has had the same experience that he or she was just describing; a phrase used after someone describes an experience that one has had
* Bernard was talking about how difficult it is to take care of his children and I said, “Welcome to the club!” because I have three kids myself.
over-the-hill – too old to do something well; very old
* Luisa’s daughter told her that she was over the hill and shouldn’t be driving anymore, and Luisa told her daughter to mind her own business.
geezer – a rude word for an old man
* I gave Ron a dirty look when he called that man a geezer to his face.
middle-aged – not young or old; not too young nor too old
* The newspaper had a story about middle-aged men who want to change their lives completely by buying an expensive car or dating younger women.
to age – to become older
* Leticia hadn’t seen her parents in one year, so she was surprised by how much they had aged when she visited them last week.
absent-minded – forgetful; often forgetting things
* Camilo is so absent-minded that his wife has to remind him to take his keys with him every morning.
senile – not thinking clearly because one is getting older; unable to remember things
* When I become senile, I don’t want to move to a nursing home. I want to stay in my own house with a nurse to take care of me.
to not be able to stand (something) – to not tolerate something; to strongly not like something; to strongly dislike something
* Karen can’t stand to be near people who are smoking. It makes her cough.
to be treated – to have someone act a certain way around oneself; to have someone behave toward oneself in a particular way.
* Even though he’s 26 years old, he’s treated like a little child by his parents.
ageism – discrimination against old people; unfair treatment of people because they are old
* Because of ageism, it is sometimes very difficult for people older than 60 to find a job.
gray hair – hair that has become white, silver, or gray with age
* Many women think that gray hair makes them look old, but many men think it makes them look dignified.
not all there – not thinking clearly; senile; a little bit crazy
* We went to visit Wendy in the hospital, but she’s still not all there after the operation and she didn’t recognize us.
sharp – intelligent; able to think quickly and clearly
* The new vice president is very sharp and she does her job very well.
you’ve got a point – a phrase used to show that one understands what someone else has said; a phrase used to show that one agrees with what someone else has said
* When Janet told her husband that she was worried about how much television the family was watching, he said, “You’ve got a point,” and they began only watching one hour each day.
productive – doing a lot; producing something; working well, quickly, and efficiently; useful and worthwhile
* Sean had a very productive afternoon: he finished a project for work, cleaned his house, cooked dinner, called his brother, and answered three emails.
Comprehension Questions
1. Why does Yann say that they’re over the hill?
a) Because they have walked past a hill.
b) Because that’s the name of their club.
c) Because they are old.
2. When Angelica says that she is sharp, what does she mean?
a) She means that her nose is pointed.
b) She means that she thinks very clearly.
c) She means that Yann has a sharp point.
Answers at bottom.
What Else Does It Mean?
to be treated
The phrase “to be treated,” in this podcast, means to have someone act a certain way around oneself, or to have someone behave toward oneself in a particular way: “Many teenagers say that they want to be treated more like adults.” Or, “Maggie decided not to go to that university because she wasn’t treated very well when she visited the campus.” The phrase “to be treated” can also mean to receive medicine or medical care when someone is sick or injured: “Claudia has to go to the doctor’s office every week because she’s being treated for diabetes.” The phrase “to be treated to (something)” means to have someone else pay for something that one eats or drinks: “Did you know that Cynthia was treated to dinner at the nicest restaurant in town by her aunt?”
sharp
In this podcast, the word “sharp” means intelligent, or able to think quickly and clearly: “Frank is really sharp, and he’s always able to think of funny things to say in any situation.” The word “sharp” also means having a strong point or edge: “Do you have any sharper knives? This one is too dull to cut through the meat.” If someone has a “sharp face,” it means that he or she has a pointed nose and chin. If someone has a “sharp tongue,” it means that he or she says very critical things or speaks very unpleasantly. The word “sharp” can also mean a very quick and significant change: “Did you know that there was a sharp fall in the stock market last week?” Or, “There was a sharp increase in crime in New York last year.”
Culture Note
In the United States, there is a very large “nonprofit organization” (an organization that does not try to make money) called the AARP, or the American Association of Retired Persons. AARP is a “membership organization” for people who are at least 50 years old. When someone wants to be a “member” (active participant) of AARP, he or she pays $12.50 each year and receives many “benefits” (advantages).
The “mission,” or reason for existing, of the AARP is “to enhance quality of life for all as we age.” AARP “enhances” or improves the quality of life for its members by providing information and classes. Topics include healthy living, finances, “tax preparation” (filling out papers when it’s time to pay money to the government), how to live with one’s “retirement funds” (the money that people save during their lives to use after they stop working), and how to use new technology.
AARP is also a powerful “advocate” for retired people. An “advocate” is a person or organization that tries to make sure that certain types of public “policies” or laws are passed, or that tries to stop some policies from being made. For example, when the U.S. government tries to change the laws about how much it will pay for older people’s medical costs, AARP advocates for laws that require the government to pay for as much of the medical expenses as possible.
AARP also offers many “volunteer opportunities” for people to work in the community without getting paid. Many older people like to help in schools and other community organizations, so AARP helps them find organizations that need their help.
Comprehension Answers
1 - c
2 - b