= 0294
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 294: Living in a Condo or Co-op.
This is English as a Second Language Podcast episode 294. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com. You can download a Learning Guide for this episode that contains all of the vocabulary, definitions, sample sentences, additional definitions not found on the podcast, cultural notes, and a complete transcript.
This episode is about two people talking about living in a “condo,” or condominium, or a co-op. Let's get started.
[start of story]
Diane: I’m so exasperated! I’m really tired of the homeowner’s association in my condo building.
Ricardo: What’s the matter with it?
Diane: The people who sit on the condo association board are a bunch of do-nothings. I’ve filed complaint after complaint and they refuse to enforce the house rules.
Ricardo: Well, that might not be so bad. I used to live in a co-op in New York City. The board of directors in my building was constantly issuing violations to the shareholders and we were fined for the smallest infraction. It was a nightmare. What kinds of complaints have you been filing?
Diane: I’ve been complaining about my noisy neighbors. They have parties every weekend. The board said it sent letters to them, but nothing has changed.
Ricardo: That’s a tough one. It’s often hard to get people to quiet down.
Diane: That’s not all. The common areas aren’t well maintained, and they’re often dirty or in need of repair.
Ricardo: That’s too bad...
Diane: And, the clubhouse is always busy with board events when I want to reserve it.
Ricardo: That’s frustrating...
Diane: You bet it is. And, what’s more...
Ricardo: Whoa. I think I have a solution for you.
Diane: What?
Ricardo: Move!
[end of story]
Our dialogue between Diane and Ricardo begins with Diane saying, “I’m so exasperated!” To be “exasperated” means to be frustrated, to be tired of something, to be angry that something continues to happen over and over again. “My neighbor's children are always yelling and screaming outside. I am exasperated” – I don't know what to do. Move, I guess!
Diane says that “I’m really tired of the homeowner’s association in my condo building.” A “condo” (condo) is a condominium. It's like an apartment building, but each person owns their own apartment; we would probably call it their own “unit” (unit). It's not something you rent, it's something that you buy and then you own. Condominiums are very popular in big cities; they're cheaper than buying a house.
Everyone who owns a condo in the building is part of, usually, a homeowner's association. A “homeowner” is someone who owns their own house – who has their own house. An “association” is an organization or a group of people. So, a “homeowner's association” is the group of people who live in a particular building. Most condominiums have homeowner's associations, and they have rules. And, each month you have to pay money to the homeowner's association so that what are called the “common areas,” the places where everyone uses such as the stairs and the hall area, can be clean and kept up. To “keep up” something means to make sure that it is in good condition, that it doesn't get dirty, that it continues to work properly
Ricardo says, “What’s the matter with it?” meaning what is the problem – what is wrong with your homeowner's association. Diane says, “The people who sit on the condo association board are a bunch of do-nothings.” A “board” is a group of people who run an organization. Some businesses have “boards of directors.” The verb to “sit” is used to mean to be on or to be part of. Diane complains that the people who sit on her condo's association board are a “bunch” of, or a group of, do-nothings. A “do-nothing” is a person who doesn't do anything – someone who is lazy, someone who doesn't do what they are supposed to do.
Diane says she's filed a complaint. A “complaint” (complaint) is when you say that there is something wrong. A “complaint” is sometimes called a “grievance.” It's when you write something down or you talk someone to tell them that you are not happy, that there is a problem. Diane says that the condo board “refuses to enforce the house rules.” To “enforce” means to make someone do what the rules say, to make a law or a rule be obeyed. In this case, she's asking for the board “to enforce the house rules.” These are the rules, the regulations, the laws that everyone agrees on in a particular place. So, each condo association – each building – has its own rules that you have to follow. These could be about noise; they could be about where to put your trash; they could even be about the color of your door. All of these could be part of the “house rules.”
Ricardo says that he “used to live in a co-op in New York City.” A “co-op” (co-op – it can be also spelled without the hyphen – coop) stands for “cooperative.” A co-op is a little different than a condo; a co-op is almost like a business that everyone owns and is a part of. When we talk about a “housing cooperative,” everyone owns and is a part of the building where you live, and so you usually have a group of people who you elect to help “run,” or manage, the property. It's not quite the same thing as owning your own separate unit in a building; it's similar. Co-ops are sometimes less expensive than condos.
Ricardo says that the board of directors in his co-op building were “constantly issuing,” or giving, “violations to the shareholders.” A “violation” (violation) is when someone tells you that you are breaking the rules, or when you break the rules – when you do something wrong. A “shareholder” is someone who is part owner of a company. Remember, I said that co-ops are different from condos because you are like someone who owns part of a business. We call the person who owns stock, or someone who owns part of a business, a “shareholder.”
Ricardo says that in his co-op they “were fined,” they had to pay money, “for the smallest infraction.” An “infraction” (infraction) is similar to a violation – when you do something wrong. An “infraction” is usually less serious than some other sort of violation.
Diane says that she's “been complaining about her noisy neighbors” because “they have parties every weekend.” She says the board has sent them letters, “but nothing has changed.” Ricardo says, “That’s a tough one” – that's a difficult situation. “It’s hard to get people to quiet down” – not to make noise.
Diane says that the common areas aren’t well maintained. To “maintain,” remember, means to make sure that they are clean and that everything is working in them. She says that the common areas are “often dirty” and “in need of repair,” meaning they are not working properly.
She goes on to complain that “the clubhouse is always busy with board events when I want to reserve it.” A “clubhouse” (clubhouse – one word) is a building in a co-op or a condominium or other organization, where a big group can meet or do something “recreational,” something for fun. To “reserve” means to arrange for something to use in the future, to say I want to use that thing or that place on this day at this time. Both “clubhouse” and the verb to “reserve” have some additional meanings; take a look at our Learning Guide for those extra explanations.
The dialogue ends with Ricardo saying, “That’s frustrating...” and Diane says, “You bet it is. And, what’s more…” meaning she has even more things to complain about, even more problems to tell Ricardo.
Ricardo interrupts her and says, “Whoa,” which is an informal way of saying stop: “whoa” (whoa). “I have a solution for you,” Ricardo says. Diane says, “What?” and Ricardo says, “Move!” – move to a different place.
Now let's listen to the dialogue, this time at a normal speed.
[start of story]
Diane: I’m so exasperated! I’m really tired of the homeowner’s association in my condo building.
Ricardo: What’s the matter with it?
Diane: The people who sit on the condo association board are a bunch of do-nothings. I’ve filed complaint after complaint and they refuse to enforce the house rules.
Ricardo: Well, that might not be so bad. I used to live in a co-op in New York City. The board of directors in my building was constantly issuing violations to the shareholders and we were fined for the smallest infraction. It was a nightmare. What kinds of complaints have you been filing?
Diane: I’ve been complaining about my noisy neighbors. They have parties every weekend. The board said it sent letters to them, but nothing has changed.
Ricardo: That’s a tough one. It’s often hard to get people to quiet down.
Diane: That’s not all. The common areas aren’t well maintained, and they’re often dirty or in need of repair.
Ricardo: That’s too bad...
Diane: And, the clubhouse is always busy with board events when I want to reserve it.
Ricardo: That’s frustrating...
Diane: You bet it is. And, what’s more...
Ricardo: Whoa. I think I have a solution for you.
Diane: What?
Ricardo: Move!
[end of story]
The script for this episode was written by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
exasperated – frustrated; tired of something; angry that something continues to happen over time; very annoyed
* The caller became exasperated when we told her that there was nothing we could do to fix her problem.
homeowner’s association – an organization that makes rules about how a group of people living in a certain area can behave and what they can do with their homes
* The homeowner’s association requires everyone to paint their homes the same color.
condo – condominium; an apartment building or a group of apartment buildings where each person owns his or her own apartment, but the areas that people share are owned by everyone
* When our condo building’s roof needed to be replaced, everyone who lived there had to help pay for it.
What’s the matter? – What’s wrong? Why are you sad or upset?
* What’s the matter with Jenny? She has been crying all morning.
do-nothing – a person (or organization) who doesn’t do anything; a person who is lazy or inefficient; a person who doesn’t do what he or she is supposed to do
* Keanu is a do-nothing who stays at home all day watching TV while his brother works.
complaint – grievance; something that is written or said to show that one is unhappy or dissatisfied with something
* I wrote a letter of complaint and sent it to the phone company because it charged me twice as much as it should have last month.
to enforce – to make a law or rule be obeyed; to make people do something that they are supposed to do
* The police are enforcing the speed limit, stopping all cars that drive faster than 45 miles per hour on this road.
house rules – rules, regulations, or laws that are agreed upon by all the people in a specific group; rules made by the people who will be affected by them
* In Sandra’s family, the house rules are that each person has to help make dinner and wash the dishes.
co-op – housing co-op; housing cooperative; a type of housing that is owned and operated by the people who live there, sharing expenses and responsibilities
* Some college students live in co-ops because they’re cheaper than dorms or apartments.
board of directors – the group of people who make important decisions for a business or organization and are responsible for hiring the president
* The board of directors has decided to change the company’s vacation policy.
violation – infraction; an action that goes against a law, rule, or regulation; the act of breaking a law, rule, or regulation
* Driving while drinking alcohol is a violation of state law.
shareholder – a person who owns stock in a company; a person who has partial ownership of a company
* The shareholders were disappointed to hear that the company wasn’t going to make as much money as they had expected.
infraction – violation; an action that goes against a law, rule, or regulation; the act of breaking a law, rule, or regulation
* The student committed an infraction of the university’s rules when he cheated on his exam.
common area – shared area; an area that is shared by many people
* This apartment building’s common areas include a gym, computer room, laundry room, garden, and basketball court.
clubhouse – a building that can be used for group meetings and/or recreational activities
* The clubhouse has a pool table, a big-screen TV, and lots of games for people to play.
to reserve – to arrange for something to be available for one’s use at a future time
* Don’t forget to reserve a table at the restaurant for this Friday night at 7:00.
Comprehension Questions
1. What complaint has Diane filed?
a) That the condo association board members are do-nothings.
b) That the board enforces the house rules.
c) That her neighbors have too many noisy parties.
2. Why didn’t Ricardo like living in a co-op in New York City?
a) Because everyone had to pay money for breaking the rules.
b) Because the violations were issued only to the shareholders.
c) Because he had nightmares about the smallest infractions.
Answers at bottom.
What Else Does It Mean?
clubhouse
The word “clubhouse,” in this podcast, means a building that can be used for group meetings and/or recreational activities: “The children are at a holiday party at the clubhouse tonight.” It is called a “clubhouse” because it belongs to a “club,” or an organization of people with similar interests. There are clubs for sports, chess, languages, music, and much more. When a club has a clubhouse, it is usually open only to the club members, or the people who participate in the club: “Do you have to be a member of the club to use this clubhouse, or is it open to anyone?” Another use of the word “clubhouse” is in “clubhouse sandwich,” usually called a “club sandwich,” which is a type of food that has three slices of bread (not just two), turkey, bacon, lettuce, and tomato.
to reserve
In this podcast, the verb “to reserve” means to arrange for something to be available for one’s use at a future time: “Did you remember to reserve a hotel room for the 15th in New York City?” As a noun, a “reserve” can be an area of land that is protected for a specific purpose: “The nature reserve is home to many different kinds of birds.” A “reserve” is also a supply of something that can be used in the future: “The United States has a large oil reserve in Alaska.” The word “reserve” is sometimes used to talk about people who keep their feelings to themselves and have difficulty talking openly to other people: “Charles speaks to his children with such reserve that most people don’t even know they are his children!”
Culture Note
A “cooperative,” or “co-op,” is any business or organization that is owned and operated by the people who use it. This podcast talked about housing co-ops, where the people who live in the building share the expenses and responsibilities of living there. For example, they might take turns cooking, cleaning, fixing the house, mowing the “lawn” (grass), and doing other things. Two other common types of co-ops are agricultural co-ops and business co-ops.
An “agricultural co-op” is an organization where farmers share their “resources” (money, time, etc.). They work together to buy their “supplies” (the things they need to farm, like seeds and tools) and then market, sell, and distribute the things that they grow.
A “business co-op” is a business that is owned by the people who use its services. One common type of business co-op is a “credit union,” which is like a bank, but people who wish to use its services must qualify as members. Sometimes a credit union member can be anyone who works for the state government, or anyone who lives in a certain area. Another common type of business co-op is a “food co-op,” or a grocery store where the people who shop there are also the owners, and they work to make the store successful.
Sometimes business co-ops are formed when a regular business is going “bankrupt,” meaning that it doesn’t have enough money to pay its expenses. When that happens, the owner tries to sell the business. If the employees decide that they want to buy the business, it becomes a co-op, because it is owned and operated by the people who work there.
Comprehension Answers
1 - c
2 - a