= 0903
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 903: Listening to a Traffic Report.
This is English as a Second Language Podcast episode 903. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there. Become a member. Download a Learning Guide for this episode.
This episode is a story about listening to the traffic report – a report about how the traffic is on the freeways and roads in your city. Let's get started.
[start of story]
Every afternoon before I leave work, I listen to the traffic report to see if I should take my usual route home or make a detour. So today, like every day, I turned on my radio.
“It’s a tough commute today if you’re traveling on I-35 north. There’s a major slowdown due to an overturned big rig that’s blocking the number two lane.”
Oh no. That meant that I had to take the 40W instead.
“If you’re traveling on the 40W, you’ll find a lot of congestion. It’s down to one lane because of a pileup. Emergency vehicles are responding.”
Wow, that meant I might have to take surface streets all the way home.
“And if you’re thinking of taking Broadway Boulevard west from downtown, think again. There is a stalled vehicle blocking the right lane and construction all the way to Main Street.”
Well, I was in a no-win situation. Do I want to spend two hours in gridlock or two more hours at work?
[end of story]
Our story begins when I say that every afternoon before I leave work, before I leave my job, I listen to the traffic report. The “traffic report” is information about how fast cars are moving on different streets and freeways. Usually, people listen to the traffic report on the radio in their car. They turn on the radio and there are certain radio stations that frequently give you a traffic report. Here in Los Angeles, because traffic is always so bad, because we have so many cars, there are a couple of stations that give traffic reports every five to 10 minutes throughout the entire day. So, within five or 10 minutes of getting in your car, you can hear what the road conditions are. That is how much traffic there is on the road.
I said that, “I listen to the traffic report to see if I should take my usual route home” – my usual way of going from my office to my home – “or make a detour.” A “detour” (detour) is when you go a different way than you would normally go, either because there are problems on the road – there's a lot of traffic, for example – or because the road is closed due to construction, because they're fixing or building it. You can't drive on it, so you have to take a detour. You have to take another road that will get you to the same place although, usually, it will take longer. I say that “Today, like every day, I turned on my radio.”
Next, we hear the voice of the person who is giving the traffic report. I've always wanted to be the person on the radio giving the traffic report. Maybe someday I will be able to get that job. It's kind of an interesting job here in Los Angeles because the traffic reporters – the people who tell you how the traffic is doing – often are in helicopters and they’re flying around the city looking down at the freeways and the streets to see how the traffic is doing, whether it is crowded or not. So, it's kind of an exciting job, at least here in Los Angeles.
The traffic reporter says, “It's a tough” – or difficult – “commute today if you're traveling on I-35 North.” Your “commute” (commute) is the trip between your home and your office, and your office and your home. That time traveling, that act of traveling, typically in a car, is what we call your “commute.” “It's a tough commute,” the announcer, the reporter says, “if you're traveling” – if you are going on – “I-35 North.” The “I” stands for “interstate.” In the United States, we have the most important, the largest highways and freeways as part of something called the interstate highway system. I-35 North would be a freeway that I just happen to know, runs in the middle of the United States through my home state of Minnesota. I-35 North would be the people who were traveling north on that road.
The traffic announcer says there is a major, or a very serious – important – slowdown. A “slowdown” – one word – is a situation where the cars are slowing down but they're not stopped completely. They're still moving, but they're going more slowly than they normally would. I say there is a major slowdown due to, or because of, an overturned big rig. “To overturn something” is to flip it over, to make the bottom be facing the top, and the top facing the bottom. “Overturned,” when used in describing a car or a vehicle, means the car or the truck has turned over, and now it is upside down. A “big rig” (rig) is a large truck. It's an informal word we use to describe a very large truck that would, for example, carry things from one city to another. It’s a very long truck. If the big rig overturned, that would be very serious because, of course, it's a very big truck and it probably would cause problems for people trying to drive on the road. In fact, this big rig is blocking the number two lane.
“To block” (block) means not allow someone access, not allow someone to go through a certain area. If the truck is blocking traffic, it's preventing other cars from driving through that area. The truck is blocking the number two lane. A “lane” (lane) is the area on a freeway or a road where the car drives. Some freeways, most freeways, have more than one lane going in each direction so you can have two cars traveling side-by-side, next to each other, going in the same direction. In Los Angeles, some of our freeways have four, five or even six lanes of cars – six lines of cars – going in the same direction. In many cities, at least here in Los Angeles, the traffic reporters will number the lanes so you'll know which lane they’re talking about. The number one lane is the lane that is farthest to the left as you drive down the freeway. That's the lane where people go fast. So, if you don't want to go fast, you should not be in the number one lane. The number two lane, then, would be the lane next to the number one lane, to the right of the number one lane, and then, of course, number three, number four, and so forth, depending on their position on the freeway. So, this overturned big rig is blocking the number two lane. It's blocking part of the freeway.
I then say, “Oh no. That meant that I had to take the 40W instead.” I had to take another freeway. But then we hear the traffic reporter again telling us about the problems on the other freeway, on the 40W. He says, “If you're traveling on the 40W, you'll find a lot of congestion.” “Congestion” is traffic that's moving very slowly, cars that are moving very slowly. The reporters says that “its” – meaning the freeway – “it's down to one lane because of a pileup.” “To be down to,” means that it has been reduced to. It has been lowered to that number. You might say, if you only have one dollar left in your pocket, “I'm down to one dollar,” meaning the amount of money I have has been reduced to one dollar. I spent all the rest of it buying coffee at Starbucks, or wherever. The freeway is down to one lane because of a “pileup.” A “pileup” (pileup) – one word – is a crash involving more than two cars or more than two vehicles. A pileup would be three or more cars that have hit each other on the freeway or on a road somewhere, and are blocking other people from driving by, or at least that's what typically happens.
The traffic reporter says that, “Emergency vehicles are responding.” “Emergency vehicles” refers to a police car, an ambulance – for people who are injured – or a fire truck, if there's a fire. All of those are emergency vehicles – a police car, an ambulance, or fire truck. When we say the emergency vehicles are responding, we mean they're actually going to the scene, the place where the accident is, in order to help. We talk about responders being people who, in an emergency, are the first to go and help – the police men and women, the firemen and women, and so forth.
I then say, “Wow. That meant I might have to take surface streets all the way home.” Because the two freeways are congested, I say that I might have to take surface streets. “Surface (surface) streets” are any roads, any boulevards, any streets in a city, not including freeways, highways, and expressways. Those three words all mean the same thing, really. “Surface streets” is anything but the freeway. It's all of the other streets, not including the freeway or the highway.
The traffic report’s final announcement is that, “If you're thinking of taking,” of driving on, “Broadway Boulevard west of downtown, think again,” meaning you should reconsider your plans. You should come up with a better idea – “think again.” “There is a stalled vehicle blocking the right lane.” “Stalled” (stalled) is an adjective we use to describe a car that won't move because of some mechanical problem. That's a stalled car. In this case, there is a stalled vehicle, which is just a more general word for car or a truck, blocking the right lane and construction all the way to Main Street. “Construction” here means they are building a new road or fixing the road and you can't drive on it.
“Well,” I said, “I was in a no-win situation.” A “no-win situation” is a situation where no matter what happens, it's going to be bad. It's a situation where regardless of the decision you make, something bad will happen. I say, “Do I want to spend two hours in gridlock or two more hours at work?” “Gridlock” (gridlock) is a situation where there are so many cars that nobody can move or it seems like nobody can move. The cars are all stopped because there are too many cars on the road. That's “gridlock.” If I go home now, I'm going to be on the road for two hours before I get home. The other option is to stay at work and work later waiting for the traffic to die down, to reduce, to be less of a problem. Neither of those are very good options for me, and that's why I say, “This is a no-win situation.”
Now let's listen to the story, this time at a normal speed.
[start of story]
Every afternoon before I leave work, I listen to the traffic report to see if I should take my usual route home or make a detour. So today, like every day, I turned on my radio.
“It’s a tough commute today if you’re traveling on I-35 north. There’s a major slowdown due to an overturned big rig that’s blocking the number two lane.”
Oh no. That meant that I had to take the 40W instead.
“If you’re traveling on the 40W, you’ll find a lot of congestion. It’s down to one lane because of a pileup. Emergency vehicles are responding.”
Wow, that meant I might have to take surface streets all the way home.
“And if you’re thinking of taking Broadway Boulevard west from downtown, think again. There is a stalled vehicle blocking the right lane and construction all the way to Main Street.”
Well, I was in a no-win situation. Do I want to spend two hours in gridlock or two more hours at work?
[end of story]
She builds freeways to better English that are never congested, never blocked. I speak poetically of our very own Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
traffic report – information about how quickly cars are moving on different streets and freeways, especially on the radio
* According to the traffic report, it might take us two hours to get out of the city.
detour – an alternative route, especially around an area with a lot of construction
* The city is replacing sewer pipes on main street, so we’ll have to take this detour.
commute – one’s drive or travel to and from work; the route between one’s home and workplace
* Would you consider moving into a condo downtown to shorten your commute?
slowdown – a situation where cars are moving very slowly, usually because too many cars are trying to drive along the same road
* Heavy rain can cause a major slowdown on the freeway.
overturned – flipped over; with the bottom facing up and the top resting on the ground
* Their home was broken into, and when they got home they found that all the tables and chairs had been overturned.
big rig – a large truck used for transporting goods long distances; a tractor-trailer; a semi-trailer truck
* Bob drives a big rig, taking food from farms to huge warehouses.
to block – to not allow passage or access; to be in the way of something so that nothing else can get through
* Could you please sit down? You’re blocking my view of the stage.
number two lane – the line of cars immediately to the right of the left-most lane (the fast lane, where cars drive at the highest speeds)
* Why is that car in the fast lane? If it’s going to drive that slowly, it should move into the number two lane and let us pass.
congestion – traffic that is moving very slowly or not at all, because there are too many cars on a particular road
* There’s always a lot of congestion early in the morning and late in the afternoon, when people are driving to and from work.
down to – reduced to; decreased to; limited to
* It’s only the 25th, but we’re already down to our last $50 until payday.
lane – the space between two painted lines on a freeway, designed for one line of cars to travel in
* Is that driver drunk? He’s swerving in and out of the lane.
pileup – a crash involving more than two vehicles
* Did you hear about the horrible pileup caused by a speeding driver?
emergency vehicle – a police car, ambulance, or fire truck
* Where are all those emergency vehicles going? Is there a fire somewhere?
to respond – for an emergency vehicle to go to the scene of an accident or emergency
* We called 9-1-1 almost 20 minutes ago. Why haven’t the police responded yet?
surface street – a less important street where traffic moves more slowly, used to access homes and businesses; not a freeway, highway, or expressway
* When there’s a lot of traffic on the freeway, we can often get home more quickly on surface streets.
stalled – a car that will not move because something is wrong with the engine or other mechanical part
* When Sharon’s car stalled in the middle of the intersection, we had to get out and push it to the side of the road.
construction – the process of making new buildings and roads
* As soon as the city decided to host the Olympics, they started a lot of new construction projects.
no-win situation – a situation that does not have any good outcomes; a situation where one must make a decision or choice, but cannot get what one wants
* If we say yes to the client, we’ll have far too much work to do, but if we say no we risk losing them to our competitor. It’s a no-win situation.
gridlock – a traffic jam; a situation where cars are not able to move because there are too many cars on the street
* Immediately after the earthquake, the entire downtown area was in gridlock as people tried to leave the city.
Comprehension Questions
1. Why is there a slowdown on I-35 north?
a) Because there was an accident.
b) Because the road has been closed for repair.
c) Because there is heavy traffic.
2. He can spend two hours at work or two hours…
a) …looking for an alternative route.
b) …traveling in very slow traffic.
c) …complaining about the traffic report.
Answers at bottom.
What Else Does It Mean?
slowdown
The word “slowdown,” in this podcast, means a situation where cars are moving very slowly, usually because too many cars are trying to drive along the same road: “Bad weather caused a major slowdown on all the major freeways.” The word “slowdown” also means a reduction in some activity: “Will an economic slowdown really affect cell phone manufacturers?” A “slowpoke” is someone who does something too slowly, especially someone who is moving too slowly: “Come on, slowpoke, we have to be there in 10 minutes!” Finally, someone who is “slow-witted” is stupid or at least unable to understand things quickly: “Kenji is so slow-witted that we had to explain the new process to him at least five times before he understood it.”
stalled
In this podcast, the word “stalled” describes a car that will not move because something is wrong with the engine or other mechanical part: “If you see a stalled car on the side of the road, do you stop to offer assistance?” The verb “to stall” means to procrastinate or delay so that one does not have to do something right away: “Stop stalling and finish up the report so we don’t have to worry about it anymore.” The verb “to stall” also means to make something or someone wait until someone is ready: “The presenter is stuck in traffic. Can you stall the client until she gets here?” Finally, as a noun, a “stall” is a small, enclosed area inside a building: “Olivia’s horse is in the third stall in the red barn.” Or, “How many stalls are in the women’s bathroom?”
Culture Note
Traffic Information
Traffic reporters need to have “up-to-the-minute” (updated; current; timely) information about the traffic, and they have developed several “methods” (ways of doing something) to get that information.
Many TV stations and radio stations use helicopters to observe traffic from the air. This lets reporters quickly identify where traffic is stalled and which “alternative” (other) routes are available. Reporters can also “eavesdrop” (listen to something without participating) on police radio. This lets them hear about accidents and road closures as they are “occurring” (happening), in “real time” (when something happens, not later).
There are also many electronic methods that don’t rely on individuals. For example, some traffic “sensors” (electronic devices that measure something and send signals about it) are placed in the “pavement” (the hard surface of a road), and they can measure the number of cars that pass over a certain point in a certain amount of time. The sensor “reads” (information coming from the sensors) can be used to calculate the average speed and the “density” (the number of cars in a given area) of the cars on that road.
“Heavily used streets” (streets that have a lot of traffic) and busy “intersections” (places where roads cross each other) are often “monitored” (observed; watched) by traffic cameras, so reporters can view the “video footage” (recorded images) to “assess” (measure and evaluate) the current traffic conditions.
Finally, some reporters ask individuals to help them improve their reporting. Individuals are “encouraged” (asked to do something) to “call in” (call a radio station with information) when they see an accident or another source of traffic congestion. Some news programs even have “smart phone apps” (application designed for phones that can access the Internet) that people can use to report traffic “hang-ups” (problems that cause traffic to slow down).
Comprehension Answers
1 - a
2 - b