= 0906
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 906 – Using Illegal Drugs.
This is English as a Second Language Podcast number 906. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Become a member of ESL Podcast by going to our website.
This episode is a dialog between Ron and Nancy about using drugs that are illegal. Let’s get started.
[start of dialog]
Nancy: So, what do you think?
Ron: Uh, that was interesting.
Nancy: That’s all you have to say? I spent six months making this anti-drug film to show students in schools to try and deter illegal drug use.
Ron: Well, I’m not sure if it gets the point across.
Nancy: What do you mean? I show footage of people using hardcore drugs.
Ron: That’s just it. You start by showing people smoking pot, making the point that it’s a gateway drug, and then showing addicts popping pills, shooting up heroine, and snorting and freebasing cocaine.
Nancy: I’m trying to show the downhill spiral that results from illegal drug use.
Ron: But considering how incredibly explicit the film is, I’m afraid that teachers might mistake it for some other type of film.
Nancy: What do you mean? What type of film?
Ron: Well, instead of an anti-drug educational film, it seems more instructional. If kids didn’t know how to use illegal drugs before, they will after watching this film!
[end of dialog]
Nancy begins our dialogue by saying to Ron, “So what do you think?” What is your opinion (of something)? Ron says, “Uh, that was interesting.” Notice: the way that he says that indicates that he perhaps doesn't like it or disagrees with it. This is a common, polite way that people sometimes indicate to others that they have an opinion that perhaps disagrees with the person they're talking to, and that the person they're talking to won't like. Someone may ask, “What you think of my new shirt?” And you think it's really ugly. You might say, “Oh, that's interesting.” Of course, if you say it that way then they know exactly what you're really saying.
Nancy says, “That's all you have to say? I spent six months making this anti-drug film to show students in schools to try and deter illegal drug use.” So Nancy has made a movie, a film, that is an “anti-drug” film. “Anti (anti) –“ usually means against. You can be antidiscrimination. You are against discrimination. You don't like it. “Anti-drug” would be someone who is against drugs, who opposes drugs – in this case, drugs that people use for what we might call “recreational purposes,” just for fun.
Nancy made this anti-drug film “to show students in schools to try and deter illegal drug use.” “To deter” (deter) means to discourage someone from doing something. “To deter” means to try to get someone not to do something. So, if you have a law against guns, you're trying to deter violence. You're trying to prevent violence. Here, we’re trying to prevent people from using drugs illegally. “Illegal” (illegal) means “not legal” – in this case, drugs that people are not supposed to use without permission.
Ron says, “Well, I'm not sure if it gets the point across.” “To get the point across” means to make yourself clear, to make your message clear, to very clearly communicate what you're trying to say to the other person. Nancy says, “What do you mean? I show footage of people using hardcore drugs.” “Footage” (footage) refers to video or film, but usually just one part of a movie, or one part of a show, or one part of a video. The word is used generally to talk about a video or a film of something, often that is part of a larger film or larger video. “Footage” might also refer to just a short piece of video.
Nancy says, “I show footage of people using hardcore drugs.” The word “hardcore” (hardcore) – one word – means extreme, the most serious type of something, usually something that's negative. At least that was the traditional use of this word “hardcore.” If you talk about “hardcore drugs,” you are saying that these were very bad drugs, drugs that would cause perhaps an extreme reaction in the person, drugs like cocaine or heroin.
In the last 20 years or so, people, especially younger people, have started to use the word to describe a very intense or extreme experience, or someone who is really committed to or devoted to a certain kind of activity. Someone who goes swimming every day for three hours might be described as a “hardcore swimmer” – someone who's really dedicated, who’s extreme in their dedication. But here, it means drugs that are potentially very dangerous.
Ron says, “That's just it.” That's the problem. “You start by showing people smoking pot, making the point that it's a gateway drug.” “Pot” (pot) is an informal word for marijuana, the illegal drug that comes from the cannabis plant. “To smoke pot” would be to smoke a marijuana cigarette. There are lots of names for marijuana cigarettes. The most common, at least when I was growing up, was “joint” (joint). People talked about “smoking joints.” (Well, not me…other people!)
Ron says that in the movie, Nancy shows people smoking pot – “making the point” – trying to communicate the idea – “that it's a gateway drug.” The term “gateway (gateway) drug” refers to a drug that is not very harmful, that doesn't have very serious effects, but that might lead people to want more and more drugs – drugs that are more serious that do have more serious effects. Marijuana is not considered a hardcore drug. It doesn't have serious effects on people when they take it. It's not seriously addicting – at least, as much as marijuana and cocaine, I don't think. I don't know. I have not tried any of these drugs, but many people believe that if you allow people to smoke marijuana legally, that will lead them to more serious drugs.
“Gateway” is a word that comes from “gate” (gate) which is the…doors to an open space, usually a garden or the front of your house, not the door of your house but – the property of your house might have a fence around it and in order to go through the fence, you go through a “gate.” It's an entrance. So, “gateway” refers to the place where you would enter into something. In this case, you would enter into the world of more serious drugs.
So, Nancy begins her film by showing people smoking marijuana, and then showing “addicts popping pills, shooting up heroin, and snorting and freebasing cocaine.” There are several drug-related terms in that sentence, that clause. Let's go through them briefly.
The first word is “addict” (addict). An “addict” is a person who is reliant on or addicted to some sort of drug, some sort of chemical substance. Usually, we use this word in talking about someone who has a serious drug addiction, a serious drug problem with hardcore drugs such as cocaine and heroin.
“To pop (pop) pills” means to swallow a lot of pills. It's often an expression we use to indicate someone who abuses drugs, especially drugs that you may get from your doctor for legitimate reasons, for good reasons, but then you take too many of them. You start taking them just to feel good. That's to “pop pills.”
“To to shoot up heroin” means to inject an illegal drug called heroin into your skin, into your blood vessels, in order to feel the effects of the drug. People who are “shooting up” are people who are using drugs that require that you stick a needle, a sharp point, into your skin in order to put the drugs right into your body.
Finally, we talk about “snorting and freebasing cocaine.” “Cocaine” is another hardcore drug, illegal drug. “To snort” (snort) means to breathe in with your nose. This verb can be used to describe someone who may make a funny sound when they laugh like [laughs and snorts] – like that. But in talking about drugs, “to snort” is to breathe in, in order to get the drug into your body through your nose. “To freebase” (freebase) means to heat cocaine in order to prepare it to be smoked. You are converting the cocaine in order to smoke it instead of snorting it.
Nancy says, “I'm trying to show” – with her film – “the downhill spiral that results from illegal drug use.” “Downhill spiral” (spiral) is a situation that is becoming worse and worse. “To go downhill” means to go from the top of a hill to the bottom of the hill. We talk about “downhill skiing,” for example. A “spiral” is when something goes around in a circle, usually moving in addition to moving around and around. So, a “downhill spiral” would be a situation that is going to down in the sense of getting worse.
Ron says, “But considering how incredibly explicit the film is, I'm afraid that teachers might mistake it for some other type of film.” “To be explicit” (explicit) means to show something directly, with a lot of detail. This word is like hardcore, sometimes associated, for example, with pornography, for the showing of sexual acts. If we talk about a movie being very explicit, or having “explicit sexual content,” that's what we’re talking about. It could also have explicit violence. Usually, “explicit” has a somewhat negative connotation, a negative meaning.
Nancy says, “What do you mean?” What type of film? Ron is saying that teachers might think this is a different kind of film. Ron says, “Well, instead of being an anti-drug educational film, it seems more instructional.” “Instructional” means something that is designed to teach people how to do something.
Ron says, “If kids didn’t know how to use illegal drugs before,” meaning before watching the film, “they will after watching this film.” Ron is saying that the film is so explicit. It shows in detail so much about how to use drugs, that it might actually have the opposite effect. It might show children how drugs are used rather than warning them against using those drugs.
Now let’s listen to the dialog this time at a normal speed.
[start of dialog]
Nancy: So, what do you think?
Ron: Uh, that was interesting.
Nancy: That’s all you have to say? I spent six months making this anti-drug film to show students in schools to try and deter illegal drug use.
Ron: Well, I’m not sure if it gets the point across.
Nancy: What do you mean? I show footage of people using hardcore drugs.
Ron: That’s just it. You start by showing people smoking pot, making the point that it’s a gateway drug, and then showing addicts popping pills, shooting up heroine, and snorting and freebasing cocaine.
Nancy: I’m trying to show the downhill spiral that results from illegal drug use.
Ron: But considering how incredibly explicit the film is, I’m afraid that teachers might mistake it for some other type of film.
Nancy: What do you mean? What type of film?
Ron: Well, instead of an anti-drug educational film, it seems more instructional. If kids don’t know how to use illegal drugs before, they will after watching this film!
[end of dialog]
Our scriptwriter knows how to get the point across in her very instructional dialogs, and she does it all without smoking pot.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
anti-drug – against the use of illegal drugs, encouraging people to “say no to drugs”; wanting people to never use drugs and, if they already use drugs, to stop using them
* These anti-drug commercials are intended to scare teenagers by showing them how dangerous drugs can be.
to deter – to discourage someone from doing something; to encourage someone to not do something
* The risk of foreclosure should deter people from buying houses they cannot afford.
illegal drug use – the practice of taking dangerous, addictive chemicals that are not allowed under law, but that provide a pleasant or exciting feeling
* Have you ever been arrested for illegal drug use?
to get the point across – to make one’s message clear; to clearly communicate a message to another person
* Rick tried to explain his proposal to the committee three different ways, but he just couldn’t get the point across.
footage – recorded video images
* The news reporter spoke to the TV cameras as footage of the storm was shown on a screen behind her.
hardcore – extreme; the most serious type of something, especially when talking about something negative
* Last year they went through a hardcore tax audit and had to pay thousands of dollars.
to smoke pot – to smoke marijuana (an illegal drug from the cannabis plant) ; to burn marijuana leaves and breathe in the smoke for a pleasant, relaxing feeling
* What percentage of college students smoke pot, but don’t do other drugs?
gateway drug – a mild drug that is not very harmful, but whose use makes it more likely that the individual will begin using more addictive and more dangerous drugs in the future
* Some people consider alcohol and cigarettes to be gateway drugs.
addict – a person who is reliant on a chemical substance and needs greater amounts each time to feel good and feels very bad without it
* Pepe is an addict and he has spent his life savings on drugs, but he still thinks he needs more.
to pop pills – to swallow a lot of tablets or capsules that contain medicine or drugs
* We thought Bryan was popping pills, but it turns out they were just vitamins.
to shoot up heroine – to inject an illegal drug through one’s skin and into one’s blood vessels
* Edgar has a lot of bruises on his arm from shooting up heroine.
to snort – to breathe in a powder, especially an illegal drug
* People who often snort cocaine have many nosebleeds.
to freebase cocaine – to smoke a solid form of cocaine (an illegal drug) that cannot be eaten, injected, or inhaled (breathed in)
* Nobody knew that Gerald was clearly freebasing cocaine, and had lost his job and home.
downhill spiral – a situation that becomes worse and worse
* As sales fell, we had less money to invest in quality control, so our product became less attractive, sales fell even further, and so on. Our company was in a downhill spiral.
explicit – stated directly and with a lot of detail, without leaving any room for confusion or misunderstanding
* I wish these violent video games weren’t so explicit. Why do they have to show so much blood?
instructional – teaching; providing information about what happened, how something works, or how do to something
* Tiago watched some great instructional videos online to learn how to fix his garage door.
Comprehension Questions
1. Which type of drug use requires using a needle?
a) Popping pills.
b) Shooting up heroine.
c) Freebasing cocaine.
2. What is the “downhill spiral”?
a) The visions that drug users see.
b) The way that addicts need drugs regularly.
c) The bad and worsening life circumstances of drug users.
Answers at bottom.
What Else Does It Mean?
to get the point across
The phrase “to get the point across,” in this podcast, means to make one’s message clear, or to clearly communicate a message to another person: “How did your doctor get the point across about losing weight?” The phrase “a good point” is used to show that one agrees with what another person has said: “I like the proposal, but Harold make a good point about needing to wait until next year.” The phrase “that’s not the point” is used when one is frustrated because someone is focusing on the wrong part of an idea: “Yes, it’s expensive, but that’s not the point. This is a great opportunity!” Finally, the phrase “to get to the point” means to be direct or straightforward and say exactly what one means: “I wish she would hurry up and get to the point instead of wasting our time by being so indirect.”
pot
In this podcast, the phrase “to smoke pot” means to smoke marijuana: “Those kids are more interested in smoking pot that in studying, playing sports, or volunteering.” The informal phrase “to go to pot” means for something to deteriorate or to become worse and fall apart because nobody is taking care of it: “This neighborhood is going to pot, and the police don’t seem to care.” The phrase “in the pot” describes the money that one can wins by winning a card game: “How can you stop playing now? We have more than $300 in the pot, so this is a really important game.” Finally, the phrase “the pot calling the kettle black” describes someone criticizing another person when that person has the same problem: “Did you really tell Randall to stop eating at restaurants all the time? That’s like the pot calling the kettle black!”
Culture Note
Anti-Drug Campaigns
Government agencies and “nonprofit organizations” (groups that provide a public service without trying to make money) have “engaged in” (participated in) many anti-drug campaigns to discourage the use of illegal drugs, especially among kids and “teens” (teenagers; people 13-19 years old).
Probably the most famous anti-drug campaign was “Just Say No” in the 1980s and early 1990s. The “First Lady” (the wife of the President of the United States) at that time, Nancy Reagan, “championed” (was a leading advocate and supporter of) the “slogan” (a phrase repeated many times), which was supposed to encourage children to “just” (simply) “say no to drugs” (decide not to use drugs). The campaign increased “public awareness” (how much people think about something) of drug use, but they have not been able to “demonstrate” (prove; show) a “link with” (clear connection to) reduced drug use.
Now the Office of National Drug Control Policy has a campaign called “Above the Influence.” The ads try to help teens learn how to deal with the “negative pressures” (things that add stress to teenagers’ life) without “turning to” (seeking comfort or help from) drugs and alcohol. The campaign wants teens to decide that they are “above” (better than; superior to) the “influence” (how something affects one’s decisions or behavior) of illegal drugs. Many of the ads show teens talking about their experiences in choosing not to use drugs.
One of the best-known “ads” (advertisements) for an anti-drug campaign was produced by the Partnership for a Drug-Free American in 1987. In the ad, a man holds up an egg and says, “This is your brain.” Then he picks up a frying pan and says “This is drugs.” Then the egg is cracked open and “fried” (cooked over high heat in a little bit of oil) and he says, “This is your brain on drugs. Any questions?”
Comprehension Answers
1 - b
2 - c