= 0919
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 919 – Visiting Child Care Centers.
This is English as a Second Language Podcast episode 919 – or backwards: 919.
This episode, like all of our episodes, has a Learning Guide. You can find that 8- to 10-page guide on our website at ESLPod.com. You can download that guide if you become a member of ESL Podcast, which I hope you will.
This episode is a dialogue between Adam and Noelle about trying to find a place where they can put their young child while the two of them work. Let's get started.
[start of dialogue]
Adam: What’s that?
Noelle: It’s a list of questions I’m going to ask at the childcare center when we visit today. I want to be prepared.
Adam: We already know that it’s licensed and has a good reputation. What other questions are you going to ask?
Noelle: Lots. For instance, I want to know what the ratio is of children to each childcare worker and what their staff turnover rate is.
Adam: Okay, I guess those are important questions.
Noelle: And I want to know what their policies are on disciplining the kids and what kinds of meals and snacks they serve.
Adam: Also good questions.
Noelle: And I want to find out their policies on sick kids and if they allow late pick-up.
Adam: Yeah, I guess those are really good questions, too.
Noelle: And I want to know if I can observe any time I want to and if there is a secure check-in/check-out system.
Adam: Those are all good questions, but I guess I shouldn’t be surprised that you’ve done your homework.
Noelle: That’s why you married me, right? Because I’m so practical?
Adam: If that’s why I married you, wouldn’t that make me the practical one?
[end of dialogue]
Our dialogue begins with Adam asking Noelle, “What's that?” Noelle says, “It's a list of questions I'm going to ask at the childcare center when we visit today.” A “childcare center” is a place – not a school, but another place – that takes care of young children, children who are too young to be in school, usually under the age of five. So, a young baby or a one-year-old, or two-year-old, or three-year-old, or four-year-old – all of these would be the kind of children you would find in a childcare center, typically.
Traditionally, women always stayed home and took care of the children while the man went out to work. Over the last 50 years, and in many western nations in particular, there has been a change in the economy. So, now a lot more women work. Some of these women, if they have a lot of money, can hire someone, can get someone to come in and take care of their children at their home – what we might call a “nanny” (nanny). This is one woman who comes – typically it is a woman – who comes and takes care of children while the wife is working or somewhere else. This only happens, however, if you have a lot of money.
Instead, what most people do is, if the mother or father cannot stay home to take care of the child, they put the child in what's called a “childcare center.” A childcare center is a place where, usually, there are several adults and lots of young children. It's sort of like a school, but usually they're not there to teach your children. They're just there to take care of them while you are at work.
Noelle has a list of questions she wants to ask the people who work at the childcare center. Obviously, she and Adam are looking for somewhere where they can take their young child. Adam says, “We already know that it's licensed and has a good reputation.” Adam is referring to one specific childcare center that apparently Adam and Noelle are interested in. He says that this is a “licensed” facility, or a “licensed” childcare center. “Licensed” means it has official permission from the government to be a childcare center. In many places, you must get permission if you want to open up a place like this that will take care of children. Adam also says the childcare center “has a good reputation.” A “reputation” is what other people think of you. So, if it has a “good reputation,” many people think this is a good place.
Adam says, “What other questions are you going to ask?” Noelle says, “Lots,” meaning I have a lot of questions. I have many questions. “For instance” – for example – “I want to know what the ratio is of children to each childcare worker.” A “ratio” is the same as a proportion. It's how much you have of one thing compared to another thing. If you have a ratio of 10 children to 1 adult, that means you have 1 adult taking care of 10 children. The ratio is 10 to 1 – we would say, “10 to (to) 1.” Noelle wants to know the ratio of children to childcare workers.
She also wants to know what the “staff turnover rate is.” “Staff” (staff) refers to the employees – the people who work at any company, including a childcare center. “Turnover” (turnover) – one word – refers to people quitting their jobs and getting new jobs. When a company has a high turnover, it has a lot of people who come and go. People are always leaving and they’re always bringing new people in. We might refer, then, to the “turnover rate” – the percentage of people who are replaced every month or every year.
Adam says, “Okay, I guess those are important questions.” Noelle says, “And I want to know what their policies are on disciplining the kids and what kinds of meals and snacks they serve.” A “policy” (policy) is a set of rules or regulations – what you do in certain circumstances, certain situations. Noelle wants to know “what their policies are on disciplining the kids.” “To discipline” (discipline) means to do something to someone who is making a mistake or who has done something wrong – usually you try to do something so that the person doesn't do it again. That is “to discipline,” to provide some sort of negative consequence for someone's negative actions. You're trying to correct what they are doing and make sure they don't do it again.
People have different ideas about how to discipline children. Some people think you should yell at them. Some people think you should lock them in a room by themselves. My neighbors apparently don't believe in any discipline for their children. So, everyone has a different idea about how you should discipline your child.
Noelle wants to know, also, something about the food that they give the children. She wants to know the “kinds of meals and snacks they serve.” A “snack” (snack) is a small amount of food that you might eat in between meals. So, you have breakfast in the morning, and then maybe at ten o'clock in the morning you have a snack. You have an apple, or a doughnut, or an orange, and then you have your lunch, which is a meal. Then in the afternoon you might have another snack, another piece of food, and so forth.
Children are often given little snacks in between their meals, and that's what Noelle is referring to. She wants to know what kind of snacks they serve. Notice the verb “to serve” means to give someone food. Adam says that these are good questions. Noelle continues, however – she has even more questions.
She says, “I want to find out their policies on sick kids and if they allow late pickup.” “Sick kids” would be kids who are ill, kids who have some medical problem. They might have a cold or the flu, for example. Noelle wants to know what their policy is on sick kids. She wants to know, probably, whether you can bring a sick child to the childcare center. Some childcare centers do not allow you to do that because, of course, then all of the other children will get sick.
Noelle also wants to know about “late pickup.” “Pickup” is when the parent comes to get the child at the end of the day. A “late pickup” would be the ability to get your child at a time later than normal. So, normally if parents come at five o'clock, but you can't be there until seven o'clock, you would have a “late pickup.” It would be later than everyone else. Adam says, “Yeah, I guess those are really good questions, too.” Noelle continues, “And I want to know if I can observe any time I want to.” “To observe” means to watch what is happening. Noelle is probably referring here to the ability for the parent to just come in and to watch to see how the childcare workers are taking care of their children.
Noelle says she wants to know if there is “a secure check-in/check-out system.” In order to make sure that the children are safe, most childcare centers will have some sort of system where they only allow people who they know are the parents – or who the parents have sent – to pick up their children. “To check in” is the opposite of “to check out.” “To check in” is when you first arrive at a location. We talk about checking into a hotel. When you get there, you go to the desk and they give you a key, and you give them money and your name. “To check out” is when you leave. So, “to check in your children” would be to bring them to the childcare center, typically in the morning, and then check out would be to come at the end of the day and pick them up. “Secure” (secure) here just means safe.
Adam says, “Those are all good questions, but I guess I shouldn't be surprised that you’ve done your homework.” “Homework” is usually what you get in school, what a teacher gives the students to do at home and to bring back the next day. “To do your homework,” as a general expression, means to do the work required, to do the research, to investigate sufficiently.
Noelle says, “That's why you married me, right? Because I’m so practical?” Someone who is “practical” is someone who gets things done, who's concerned about the results, who’s very productive. I am the opposite of that. I am very impractical (impractical).
Adam says, “If that's why I married you, wouldn't that make me the practical one?” Adam is saying, “Well, if I was smart enough to marry you, then I’m the practical one, because I am getting things done by having you do them.” That's probably somewhat true in many marriages.
Now let's listen to the dialogue, this time at a normal speed.
[start of dialogue]
Adam: What’s that?
Noelle: It’s a list of questions I’m going to ask at the childcare center when we visit today. I want to be prepared.
Adam: We already know that it’s licensed and has a good reputation. What other questions are you going to ask?
Noelle: Lots. For instance, I want to know what the ratio is of children to each childcare worker and what their staff turnover rate is.
Adam: Okay, I guess those are important questions.
Noelle: And I want to know what their policies are on disciplining the kids and what kinds of meals and snacks they serve.
Adam: Also good questions.
Noelle: And I want to find out their policies on sick kids and if they allow late pick-up.
Adam: Yeah, I guess those are really good questions, too.
Noelle: And I want to know if I can observe any time I want to and if there is a secure check-in/check-out system.
Adam: Those are all good questions, but I guess I shouldn’t be surprised that you’ve done your homework.
Noelle: That’s why you married me, right? Because I’m so practical?
Adam: If that’s why I married you, wouldn’t that make me the practical one?
[end of dialogue]
Our scriptwriter as an excellent reputation as being a wonderful teacher. I refer, of course, to our very own Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
childcare center – a facility or institution (but not a school) that takes care of young children, usually while their parents are working
* It’s so hard to find a childcare center that has openings for very young babies!
licensed – with official permission from the government to provide a particular service or do a particular thing
* Are you licensed to operate heavy machinery in this factory?
reputation – a measure of whether a person or organization is viewed positively or negatively by most people
* Professor Williamson has a reputation for asking really difficult questions on the midterm exams.
lots – many; a lot
* We eat lots of ice cream in July and August.
ratio – proportion; the relationship between two amounts showing the number of times one value contains or is contained within the other
* If you want to have a good compost pile, you need to pay attention to the ratio of brown materials, like dead leaves, to green materials, like grass clippings.
turnover rate – a measure of how many employees leave an organization and how many new employees are hired over a period of time
* Most fast food restaurants have a really high turnover rate.
policy – an official way of doing something, usually written down and shared with all employees
* All employees have to sign a confidentiality policy, promising not to share company secrets with people outside of the company.
to discipline – to provide appropriate negative consequences for bad behavior in an effort to teach someone how to act or to improve someone’s behavior over time
* Would you ever hit your child to discipline her?
snack – a small amount of food eaten between meals
* Craig always prepares healthy snacks for his children to eat after school, like apple slices or carrot sticks.
sick – ill; not feeling well; with a cold, flu, or other illness
* Our employees have eight paid sick days each year.
late pick-up – permission to pick up a child after the regular time when a program ends and children are expected to be picked up
* This preschool charges $1 per minute for late pick-up, so it’s really important for parents and other caregivers to pick up their children before 5:30.
to observe – to monitor; to watch something as it is happening, without participating in it; to see how something is occurring or how someone is performing
* Scientists are trained to observe what occurs without influencing them.
secure check-in/check-out system – a way to place children in a program and take them out at the end of each day that guarantees their safety, making sure that a responsible adult is aware of their presence and that only authorized individuals can pick up the children
* The gym offers childcare with a secure check-in/check-out system. When you drop off your kids, they give you and your children matching bracelets, and the only way you can pick up your children is if you’re still wearing that bracelet.
to do (one’s) homework – to thoroughly research or investigate something so that one is fully prepared before something happens
* Before Wynona and Miguel started looking at homes, they did their homework by researching the neighborhood and schools.
practical – interested in results and able to get things done through a hands-on, logical, effective approach
* Sure, it would be fun to travel in a flying car, but it doesn’t seem very practical.
Comprehension Questions
1. Which of these would be a snack for children?
a) An arts-and-crafts project.
b) A field trip to a local park.
c) Nuts and dried fruit.
2. What does Adam mean by saying that Noelle has done her homework?
a) She has already completed all of the registration forms.
b) She has done a lot of research and is fully prepared for the meeting.
c) She is worrying too much about creating a list of questions.
Answers at bottom.
What Else Does It Mean?
lots
The word “lots,” in this podcast, means many or a lot: “We bought lots of clothes at the spring sales last year.” The word can also be used in the singular with the same meaning: “We spent a lot of money on car repairs.” The phrase “an awful lot” means a very large amount of something: “They’re selling an awful lot of junk at their garage sale.” Sometimes the word “lots” means very: “Thanks to the new medicine, I’m feeling lots better.” A “lot” can also be an area of land that is sold as one unit, usually so that one building can be built there: “Are there any vacant lots in your neighborhood?” Or, “They bought a home on a half-acre lot.” Finally, the phrase “thanks a lot” is an informal way to say “thank you very much.”
sick
In this podcast, the word “sick” means ill or not feeling well: “Are you sick, or do you just have allergies?” The phrase “to be out sick” means to not be at work because one is sick: “I was out sick most of last week.” The phrase “to call in sick” means to call one’s boss to say that one will be unable to work because one is sick: “I’m sorry, but I have to call in sick today.” The phrase “sick and tired” means very frustrated with something and not wanting to have or do it anymore: “I’m sick and tired of hearing the kids complain and cry at bedtime!” Sometimes the word “sick” means gross, icky, or unpleasant: “Did you really eat a worm? That’s sick!” Finally, the informal phrase “that’s sick” means that something is very good and impressive: “Did you see Hank’s new paintings? They’re sick!”
Culture Note
Licensing Requirements for Childcare Centers
Most childcare centers are “regulated” (force to follow certain rules) by state agencies, so the “licensing requirements” (the things a center must to do operate legally) “vary” (are different) by state. Licensing requirements also depend on whether the “facility” (building) is a “family childcare home,” which has a home-like environment, or a “childcare center,” which is in a commercial building.
In California, childcare providers must attend an “orientation” (a meeting that provides general, introductory information on a particular topic). At the orientation, they receive information about the requirements they must meet.
Many of the requirements are related to the size and “condition” (quality; how well something is maintained) of the facility, including the number of bathrooms, “fences” (outdoor walls) around the “yard” (outdoor area), and safe storage of “hazardous materials” (cleaning chemicals and other materials that can hurt or kill children).
Other licensing requirements affect the “staff members” (the people who work in the center). For example, they must “pass” (be approved by) a criminal background check showing that they have not been “convicted” (found guilty of) child abuse or other serious crimes. Staff members must also have a “clean” (without problems) health report. They must have completed a certain number of hours of training in health and safety and they need to have earned a certificated in “first aid” (appropriate treatment in a medical emergency).
The center also has to meet certain ratios. For example, one teacher can “supervise” (be responsible for) no more than 12 children, and that ratio is lower if “infants” (babies) are present.
Comprehension Answers
1 - c
2 - b