= 0949
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 949 – Dealing with a Contagious Disease.
This is English as a Second Language Podcast episode 949. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is also beautiful. You can find it at ESLPod.com. When you go there, become a member of ESL Podcast, if you're not already, and download the Learning Guide for this episode.
This episode is a dialogue about contagious diseases – diseases or illnesses that can spread from one person to another. Let’s get started.
[start of dialogue]
Isabelle: You can’t walk through that door with all of your clothes on!
Linus: What?! I’ve just come off of a 12-hour flight. I’m tired and I want to get into my own house and into my own bed.
Isabelle: I know, but you’ve just returned from McQuillanland, and I’ve just read that anyone who has been there may be a carrier of a communicable disease called Niebola. It can be transmitted through casual contact, so even if you don’t have it, you could spread it.
Linus: So what am I supposed to do? Stand out here for the rest of my life?
Isabelle: Of course not. Take off your clothes.
Linus: You want me to take off my clothes in front of the house? Are you crazy?!
Isabelle: No, the best way to prevent the spread of this infectious disease is to burn clothing that has been in contact with it, and to bathe you thoroughly.
Linus: I’m not stripping down to my underwear out here.
Isabelle: But aren’t you worried about transmitting Niebola to me and everyone you know? No one is immune. You could start an epidemic!
Linus: All right, but I’m going around to the back door where no one can see me, okay?
Isabelle: Great! I’ll get your bath ready. I just have to heat the mayonnaise.
Linus: What?! You want me to take a bath in mayonnaise?
Isabelle: That’s the only way to kill Niebola.
[end of dialogue]
Our dialogue begins with Isabel saying to Linus, “You can’t walk through that door with all of your clothes on!” Linus says, “What?! I've just come off of a 12-hour flight. I'm tired and I want to get into my own house and into my own bed.” So, we have a situation where Linus is coming off of a plane. He says, “I've just come off of a 12-hour flight,” which means he was on a plane for 12 hours. He got off the plane and went home, but Isabel, who we guess to be his wife, is not letting him into the house.
Isabel says, “I know” – I understand you want to get into your house – “but you’ve just returned from McQuillanland, and I've just read that anyone who has been there may be a carrier of a communicable disease called Niebola. It can be transmitted through casual contact, so even if you don't have it, you could spread it.” We learn that Linus has gone to what I think sounds like a wonderful place, McQuillanland, and unfortunately has perhaps become a carrier of a communicable disease.
A “carrier” (carrier) is a person who has a certain disease, but doesn't show any symptoms. It doesn't look like the person has any disease. However, because they have the disease, they could give it to other people. We’re talking here about diseases or illnesses that are communicable. The term “communicable” (communicable) refers to things that can be transmitted or shared or given to other people from one person to another. A disease such as “chicken pox” can be “communicated,” or transmitted, from one person to another. That makes it a communicable disease.
This “communicable disease” is called Niebola. Isabel says, “It can be transmitted through casual contact, so even if you don't have it, you could spread it.” “Transmit” here means to share, to pass from one person to another. We use the verb “transmit” in this sense when we’re talking about things like communicable diseases. We also use it in biology to talk about genetic traits or characteristics that are passed from parents to their children.
The term “casual contact” refers to you talking to someone, and not perhaps touching someone, but only for a very short amount of time. However, there are certain diseases that, even with casual contact, even though you don't have a lot of contact with that person – you're not talking to them or being with them for very long time – can still end up being a way of catching or getting a disease. Some diseases can be transmitted through casual contact. Many cannot. Many require some more “extensive,” we might say, contact with a person who has that disease.
Isabel says that even if Linus doesn't feel any of the effects of the disease, he could still spread it. “To spread (spread)” means to distribute something, to move something around so that it covers a larger area or, in this case, affects more people. If you are spreading disease, you are in a way helping other people get this disease. You are doing something that is going to increase the likelihood of other people getting the disease.
Linus says, “So what am I supposed to do? Stand out here for the rest of my life?” He's confused about what he has to do in order to get into his own house. Isabel says, “Of course not. Take off your clothes” – remove your clothing. Linus says, “You want me to take off my clothes in front of the house? Are you crazy?!” Isabel says, “No, the best way to prevent the spread of this infectious disease is to burn clothing that has been in contact with it, and to bathe you thoroughly.” So, this is something of an odd disease that apparently can be transmitted through someone's clothing.
Isabel says the best way to prevent the spread of this infectious disease is to burn clothing. “To prevent” means to not allow something to happen, to not permit something to happen. An “infectious (infectious) disease” is a disease that can be caused when some organism – some living organism such as bacteria or a virus or fungus – enters the body. Isabel says that Niebola can be prevented, or at least we can prevent the spread of this infectious disease, by burning clothing that has been in contact with it. “To burn” means to put something in a fire, to destroy something by fire.
“To be in contact with” something is to have touched something or to have touched someone. Isabel wants to burn Linus’s clothing in case it has been in contact with this disease. She also wants to bathe Linus. “To bathe” (bathe) means to wash someone, typically in a large container which we call a “tub” (tub). You put water in the tub and then you take the water and you use it to clean a person off – or to clean your dog off, I suppose.
Linus is not happy about this situation. He says, “I'm not stripping down to my underwear out here.” “To strip (strip) down to” something here usually means to remove your clothing, to get undressed. Linus doesn't want to strip down to his underwear, meaning to take off all of his clothes except his underwear. “Underwear” just refers to clothing that you wear underneath other clothing – typically, that you don't want people to see. “Underwear” protects your clothing from touching directly to certain parts of your body. Let’s put it that way.
Isabel says, “But aren't you worried about transmitting Niebola to me and everyone you know? No one is immune.” “To be immune” (immune), when we’re talking about a disease, means that you cannot get a disease. Maybe the biological makeup or composition of your body is such that you can't get a disease. It might also be that you have received a vaccination – that you've taken a pill or received a shot that prevents you from getting the disease. Isabel says that “no one is immune” to Niebola.
She says to Linus, “You could start an epidemic!” An “epidemic” (epidemic) is a situation in which a disease affects many people in a particular area. It spreads. It is transmitted to many different people. Linus says, “All right, but I’m going around to the back door where no one can see me, okay?” Linus wants to go to the back of the house so that he doesn't have to undress in front of the house.
Isabel is happy. She says, “Great. I'll get your bath ready. I just have to heat the mayonnaise.” “Mayonnaise” is a white sauce – made from eggs, vinegar, lemon juice, and other things – that is often used on bread or in preparing food. It is not something we would usually associate with medicine. Linus says, “What?! You want me to take a bath in mayonnaise?” Isabel says, “That's the only way to kill Niebola.” So, Niebola is a very strange disease. But McQuillanland is a very strange country.
Now let's listen to the dialogue, this time at a normal speed.
[start of dialogue]
Isabelle: You can’t walk through that door with all of your clothes on!
Linus: What?! I’ve just come off of a 12-hour flight. I’m tired and I want to get into my own house and into my own bed.
Isabelle: I know, but you’ve just returned from McQuillanland, and I’ve just read that anyone who has been there may be a carrier of a communicable disease called Niebola. It can be transmitted through casual contact, so even if you don’t have it, you could spread it.
Linus: So what am I supposed to do? Stand out here for the rest of my life?
Isabelle: Of course not. Take off your clothes.
Linus: You want me to take off my clothes in front of the house? Are you crazy?!
Isabelle: No, the best way to prevent the spread of this infectious disease is to burn clothing that has been in contact with it, and to bathe you thoroughly.
Linus: I’m not stripping down to my underwear out here.
Isabelle: But aren’t you worried about transmitting Niebola to me and everyone you know? No one is immune. You could start an epidemic!
Linus: All right, but I’m going around to the back door where no one can see me, okay?
Isabelle: Great! I’ll get your bath ready. I just have to heat the mayonnaise.
Linus: What?! You want me to take a bath in mayonnaise?
Isabelle: That’s the only way to kill Niebola.
[end of dialogue]
If you come in contact with the scripts of our wonderful scriptwriter, Dr. Lucy Tse, you won't get a disease. You'll get better English.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
carrier – a person who has been exposed to a disease and has the bacteria or virus and is not showing any symptoms (medical problems), but can transfer the disease to others
* You can be a carrier of the common cold for up to five days without showing symptoms.
communicable disease – a disease that is transmitted (shared) between people or between people and animals
* Washing hands is a good way to prevent the spread of communicable diseases.
transmitted – shared with another person; sent from one person to another
* Many illnesses are transmitted through blood and saliva (liquid from the mouth).
casual contact – light touch, especially when talking about diseases that are spread through touch, without spending a lot of time with the other person
* AIDS cannot be spread through casual contact, but only through the exchange of body fluids.
to spread – to increase the extent of something; to move something around so that it covers a larger area or affects more people
* If these beetles continue to spread through the forest, they could kill all the pine trees here.
to prevent – to not allow something to happen; to do something that does not permit something to happen
* How can we prevent our competitors from copying our new design?
infectious disease – a disease caused when an organism (bacteria, virus, fungus, or something similar) enters the body
* In general, hot tropical areas have more infectious diseases than areas with cooler climates.
to burn – to destroy something in fire; to make something catch on fire
* I’m a bad cook and can’t even make a grilled cheese sandwich without burning it.
in contact with – having touched something else or communicated with someone
* If his skin comes in contact with this plant, he immediately develops a painful red rash.
to bathe – to wash someone in a tub filled with water (not a shower)
* How often are you supposed to bathe a newborn baby?
to strip down – to remove one’s clothing; to get undressed
* Please strip down and put on this gown. The doctor will be in to see you in a few minutes.
underwear – undergarments; panties, boxers, briefs, bras, and other items of clothing worn underneath one’s regular clothes, generally not meant to be seen by others
* Some young men like to wear their pants so low on their hips that their underwear shows.
immune – with immunity to a disease; protected against getting a particular disease, usually because one has had it before or because one was vaccinated
* If you got a polio shot as a baby, you should be immune to the disease.
epidemic – a situation in which a disease affects many people in a particular area over a short period of time and threatens to spread quickly into other areas
* Healthcare providers are struggling to respond to the bird flu epidemic.
mayonnaise – a white condiment or sauce made from eggs, vinegar, lemon juice, and seasonings, often spread on bread to make sandwiches
* I’d like a cheeseburger with ketchup and mustard, but no mayonnaise, please.
Comprehension Questions
1. Why does Isabelle want Linus to take off his clothes?
a) Because they might be carrying germs.
b) Because they don’t look good on him.
c) Because they smell bad from his long trip.
2. What would Linus be wearing if he stripped down to his underwear?
a) Nothing at all.
b) His underwear (briefs or boxers).
c) All of his clothes.
Answers at bottom.
What Else Does It Mean?
carrier
The word “carrier,” in this podcast, means a person who has been exposed to a disease and has the bacteria or virus and is not showing any symptoms (medical problems), but can transfer the disease to others: “Be careful who you kiss, because even though people might appear to be healthy, they could be carriers of some very serious diseases.” A “mail carrier” is a person who delivers the mail: “The mail carrier usually brings the mail around 1:30 p.m.” A “pet carrier” is a special box used to transport small animals like dogs and cats: “The dog hates getting into the pet carrier, because he knows it means a trip to the veterinarian’s office.” Finally, an “aircraft carrier” is a very large military ship that airplanes can take off from and land on: “A typical aircraft carrier is as big as three to four football fields.”
to strip down
In this podcast, the phrase “to strip down” means to remove one’s clothing or to get undressed: “Vicky is overweight and very self-conscious about stripping down in front of other people at the gym.” The phrase “to strip down” can also mean to take apart an engine or another machine: “Let’s strip down this copier and replace the broken parts.” The verb “to strip” also means for a man or woman to take off their clothes while dancing in a sexy way: “Ben is too embarrassed to strip in front of his girlfriend.” Finally, the phrase “to strip (someone) of (something)” means to take something away from someone, especially as a punishment: “The court’s decision stripped Robin of her right to see her children.”
Culture Note
The Centers for Disease Control and Prevention
The Centers for Disease Control and Prevention, commonly known as the “CDC,” is the national health institute of the United States. “Founded” (created and begun) in 1946, the CDC works to protect “public health” (the health of an entire population) and safety by controlling and preventing disease, “injury” (physical damage, such as a broken bone), and “disability” (an inability to use one’s body normally, such as “deafness” (not being able to hear)). In the past, the CDC primarily focused on infectious or communicable disease, but now it also works on health issues surrounding “obesity” (being overweight) and “diabetes” (the presence of too much sugar in the blood).
The CDC “monitors” (observes) and “responds” (reacts) to disease “outbreaks” (the sudden appearance and spread of an illness) to try to slow or stop the spread of disease. The CDC also works on “food safety,” trying to ensure that the food sold and “consumed” (eaten) in the United States “is free of” (does not have) “pathogens” (organisms that cause illness). For example, when people are “sickened” (become ill) with “foodborne illnesses” (diseases found in food) such as “salmonella” (a deadly bacteria found on raw chicken, for example), “epidemiologists” (scientists who study the spread of disease) work to “trace the bacteria to its source” (understand where the bacteria first appeared) and prevent it from spreading further.
The CDC also responds to “environmental health issues” (instances where chemicals in the environment present dangers to human health) and “occupational health issues” (efforts to ensure the safety of people at work).
Comprehension Answers
1 - a
2 - b