= 1625
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 320.
This is English as a Second Language Podcast’s English Café episode 320. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download a Learning Guide for this episode by becoming a member of ESL Podcast and helping support our podcast.
On this Café, we’re going to continue our series on American Cities, focusing on Columbus, Ohio. We’ll also talk about a famous American from the 1930s, Wallis Simpson, and her relationship with the King of England, King Edward VIII. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a continuation of our series on American Cities. Today we are going to talk about Columbus, which is the capital city of Ohio and the largest city in the State of Ohio. Ohio is a Midwestern state; it’s in the Midwestern part of the United States, just south of Lake Erie. Lake Erie is one the five so-called “Great Lakes” in North America. Ohio “borders” or is next to the states of Pennsylvania, West Virginia, Kentucky, Indiana, and Michigan.
The City of Columbus was “founded” or first established in 1812. It was named after, of course, Christopher Columbus, the explorer who is generally said to have discovered North America back in 1492. And by “discovered,” we mean the first European to come here, although some people say that other Europeans had come even earlier than Columbus; we won’t talk about that now. Columbus became the capital city of Ohio in 1816 and is today considered a thriving city. “To thrive” (thrive) means to do very well, or to grow and be successful. We often talk about plants thriving, but in this case I’m talking about a city that is doing very well. Columbus is rated highly in the rankings of U.S. cities; some people say it’s one of the best cities to raise a family in or to do business in.
Columbus is sometimes called “The Arch City.” An arch” (arch) is a tall, curved shape or structure, kind of like a tunnel, but not as long. Bridges are usually arched, but we can also talk about arching our eyebrows, putting them up in this semi-circular manner. Arches have often been used as monuments or memorials to celebrate some great event or great person. In the early 1900s, there were many wooden arches over one of the main streets in Columbus, and later those arches were used to provide electric power to streetcars. “Streetcars” are sort of like buses, but they run on electrical power, and back then the electrical power was provided by lines that were over the street – “overhead,” we might say. The arches were actually taken down in Columbus in 1914, but some new arches were put up or built in 2002. You can still hear people refer to Columbus as “The Arch City,” referring to those arches way back more than or approximately 100 years ago.
Columbus has a diversified economy. We normally use the word “diversified” when we’re talking about stocks and finances. If you have diversified holdings in stocks, you own stocks from many different kinds of businesses – many different industries; it’s a way of reducing risk. If one company does poorly, well, you’ve invested in other different kinds of companies and so you are able to lower your risk in investment. In a similar way, Columbus’ economy is diversified, meaning people work in different kinds of businesses. In recent years, where the economy has slowed down in many parts of the U.S., Columbus has continued to be relatively successful because it has this diversified economy – it doesn’t just have everyone in one kind of job. Here in Los Angeles, the main economy is the entertainment industry; it used to be that we had aviation and aeronautics construction industries, but not really anymore. The other major industry for Los Angeles would probably be tourism and technology. Well, Columbus has a diversified economy. People in Columbus work in many different areas: insurance, banking, aviation (airplanes), fashion, steel, energy, education, and more.
Today, Columbus is a technologically sophisticated city. That means it has a lot of technology companies like Los Angeles and Silicon Valley and Austin and a few other places. Some “prominent” or important companies in Columbus include the Battelle Memorial Institute, which is the largest private research and development foundation in the world – who knew – and Chemical Abstracts Services, which has a lot of information that it distributes about, well, chemicals. Columbus is also the home to The Ohio State University. It’s not called technically Ohio State; the real name is The Ohio State University, where the “the” is part of the name of the university. It is one of the biggest universities in the United States, and famous for its American football team.
A lot of famous people have lived in Columbus. Jesse Owens, who won the Olympic gold medal in track and field, was a student of Ohio State – sorry, The Ohio State University, and we talked about him in English Café 298. The father and grandfather of former Presidents George Bush and George W. Bush were born in Columbus. Dave Thomas, the founder of a famous fast-food restaurant “chain” or group of restaurants called Wendy’s opened his first store in – where else – Columbus. Who knew Columbus was so famous?
Columbus has a lot of beautiful parks and interesting fairs and festivals. If you ever make it to Columbus – that is, if you ever visit the city, be sure to visit the Columbus Zoo, where you can see animals, and Aquarium, where you can see fish. “To make it to a place” as I said, means to go to a place. I’ve made it to Columbus at least once at least, many years ago. I don’t remember very much; I was giving a presentation there at a hotel. So I flew into the airport, I took a taxi to my hotel, the next morning I went down and I gave my presentation; this was to a group of teachers. Then I got back into the taxi, went to the airport, and flew to the next city where I was giving another presentation. So, I didn’t really get to visit Columbus, but maybe someday. Now that I know it has such exciting things as the Chemical Abstracts Service, maybe I’ll give it a visit when I’m in that area – or maybe not.
Now let’s turn to our next topic. We’re going to talk about a famous American woman named Wallis Simpson and her relationship with to the then-King of England, King Edward VIII. This topic was briefly touched on in a recent movie, The King’s Speech. “To touch on (something)” means to talk about something briefly, or very quickly, without giving it very much attention or detail. The 2010 movie The King’s Speech was mostly about King George VI of England, but it also touched on Wallis Simpson, and her relationship with George’s brother Edward.
Let’s start at the beginning, but unlike the movie, we’re going to look at this story from the perspective of Wallis Simpson, not of King George VI. Wallis (Wallis) is somewhat of an unusual first name; she was an unusual woman. She was born in Blue Ridge Summit, Pennsylvania in 1896. Pennsylvania is right next to the State of Ohio.
In 1916, at the age of 20, Wallis married a U.S. Navy pilot, Earl Spencer, but the two had a difficult marriage and they were often separated. When we talk about a husband and wife being separated, it means they live apart, in different homes, usually because they are having problems in their marriage and are perhaps considering getting a legal divorce. Wallis and Earl did in fact divorce in 1927. Before that divorce happened however, she became involved in a romantic relationship with another man, Ernest Aldrich Simpson, who was also married to someone else. After Wallis’ divorce, Ernest divorced his wife and then he and Wallis were married in 1928 in England. So, Ernest was Wallis’ second husband.
Around 1930, Wallis met a woman named Lady Furness, who was allegedly the mistress of Edward, the Prince of Wales. A “mistress” (mistress) is a woman who is in a sexual relationship with a man who is married to someone else. I say that Lady Furness was allegedly the Prince’s mistress; we don’t know if it is true, and the Prince himself said it was not. “Allegedly” is used when we think something is true but we’re not sure. So, Lady Furness was allegedly the mistress of Edward; this was before Edward became King. He was the Prince of Wales, which is the traditional title, I believe, of the son of the king, who is about to become king or will become king when the king or queen dies. The Prince of Wales right now, when we record this podcast, is Charles; he’s the oldest son of Elizabeth, who was the daughter of George VI. Edward VIII was Elizabeth’s uncle, which would make him the great-uncle of Charles. You got that? Good.
So, around 1930, Wallis Simpson met Lady Furness, and in 1934, Lady Furness went to New York for a period of time, and Wallis became closer – much closer – to Edward. She became Edward’s lover, and Edward soon became besotted with her. “To be besotted (besotted) with (someone)” is a sort of old expression meaning to be in love that person very deeply, to be obsessed with that person; you can’t think of anything else and you can’t behave normally. Now this was a problem, because their relationship began to interfere with Edward’s official duties as Prince of Wales. It was an even bigger problem, because Wallis Simpson was a “divorcée,” someone who had been divorced, and that was considered unacceptable to the Church of England.
In 1936, King George V, Edward’s father, died and logically his son, Edward, became King Edward VIII. He made it clear however that he wanted to marry Wallis Simpson, but as I said, the Church of England at the time did not allow divorced people to remarry if their ex-husband or ex-wife was still living. Simpson completed her divorce from her second husband in the fall of 1936, and so the new king was considering marrying the woman who was not just a divorcée but a two-time divorcée – she had been divorced twice, and both of her ex-husbands were still very much alive. This was considered scandalous. A “scandal” (scandal) is something that is considered very shocking because it breaks the rules of what is acceptable in society. There’s an expression “to give scandal,” and that really refers to doing something shocking and influencing other people into thinking that that is acceptable, and the problem is that you are setting a bad example. Well, people thought that this marriage would be scandalous.
Edward spoke with England’s Prime Minister and tried to find a way to marry Wallis Simpson, but there weren’t any while we might call “viable options.” Something that is “viable” (viable) is possible, something that is feasible, something that can happen. Around this time there was a lot of media attention; a lot of newspapers and radio stations were talking about this potentially scandalous marriage. Wallis publicly said that she would leave the king, but Edward would not allow it. He wanted to marry Wallis Simpson.
Finally in December of 1936, King Edward VIII abdicated the throne. The “throne” (throne) is technically the large chair that a king or queen sits in. Here it really means the position of king. “To abdicate” (abdicate) means to leave your position as king or queen, to say I no longer want to be king or queen. Edward abdicated his throne, or the throne of England, making his brother, who at that time was known as the Duke of York, the new king; his brother George became King George VI.
The numbers that come after the names of the British kings, of course, depend on other kings who’ve taken that same name. So, if I say I’m King George, and my son is named George and he becomes king, well, he’s King George II. And then later, maybe hundreds of years later, if somebody else is named George, and he’s king, well, he becomes George the whatever. Of course, the most famous George – King George – is George III, at least for Americans since he was king when America became independent of England. So George IV, who is the focus of the movie The King’s Speech, became king.
Edward explained his decision to the British people. He said, “I have found it impossible to carry the heavy burden (the heavy difficulty) of responsibility, and to discharge my duties as King as I wish to do, without the help and support of the woman I love.” In other words, he couldn’t “discharge” or perform the job of a king without the help of Wallis Simpson, without marrying her.
They were in fact married in France the next year, in 1937, but no members of the royal family attended their wedding. Edward and Wallis became known as the Duke and Duchess of Windsor. They spent a lot of time in France. Some people suspected that they were perhaps were sympathizers with the Nazis, the people who supported Nazi Germany, although I don’t know if that has ever really been proven.
In any case, Edward, the Duke passed away or died in 1972. Wallis spent the rest of her life as a “recluse,” someone who lives alone and doesn’t speak with other people. She died in Paris in 1986.
Now let’s answer some of the questions you have sent us.
Han (Han) from China asks our first question, which is what is the difference between “limit” (limit) and “limitation” (limitation). Well, this is a good question because these words, in addition to the word “limits” with an “s” at the end, have some similar meanings obviously. Let’s start with “limit.”
The first meaning of “limit” is the point after which something is not allowed or something cannot be done. “My limit for eating hot dogs is four.” I cannot eat more than four hot dogs; that’s my limit. Or, “The speed limit is 55 miles per hour.” You are not allowed to go faster than 55 miles an hour, although everyone does.
As a verb, “limit” can mean defining or making a rule about how big or how far or how much of something you’re going to do: “I am going to limit the number of hours my children watch television.” Or you could say, “I don’t want to limit your creativity.”
“Limits,” with an “s” at the end, is a noun meaning the boundaries or borders for a certain area. We sometimes talk about the “city limits,” with an “s,” that would refer to the boundary or the border separating the city from the area outside of the city. “Limits” can also refer to the highest level of achievement: “She reached the limits of her endurance, her ability to keep pushing her body further and further, when she ran a marathon.”
“Limitation,” as a noun, is some sort of problem that limits your abilities. For example: “One of the limitations that I have in walking is that I broke my foot, so it hurts and I can’t walk very much.” Not true, didn’t actually break my foot, but as an example. I don’t have children either, once again just an example. Anyway, “limitation” is a disability, or could be considered a disability. “Limitation” can also simply mean a rule that restricts behavior: “We have a limitation on the amount of time you can watch television.”
These meanings often “overlap,” meaning they have common things among them – common meanings among them. I could say, “The time limit is five minutes.” Or you could say, “There’s a time limitation of five minutes,” probably not as common but it’s possible. Generally speaking, the word “limitation” is used more when there is some problem or some disability. “Limit” and “limits” are used more generally for other cases where there is some sort of restriction or maximum amount of something.
Matias (Matias) in Argentina wants to know the meaning of the expression “X person undercut set targets.” “X person” is just another way of saying
someone or somebody; a certain person, could be anyone really. It’s a little more formal way of saying that, a little more, I guess, business speak, the way you might talk at a business meeting trying to impress other people. The verb “to undercut” (one word) means to make less effective, to harm, to hurt: “Our partnership was undercut by the other company’s failure to do their job.” It was hurt, it was harmed, it was made less effective. A “set target” is something that is put in a certain place or a certain position; that’s the general meaning of “set.” A “target” here just means a goal, something you are trying to reach. So a more common translation of this very businesslike language would be someone weakened our progress or hurt our progress toward our goals. “Undercut” is something that you usually hear only in talking about businesses, it’s used in a business environment. You won’t normally hear people talk about “x person,” again, it sounds very formal, something you would only hear in a business meeting or perhaps at business school – that is, if you were studying for a degree in business. Those are places that you would hear that kind of language.
Finally, Zana (Zana) from an unknown country – we’ll call it Country Z – wants to know the meaning of the two-word phrasal verb “to sponge off.” “To sponge (sponge) off (someone)” can mean to be living off of someone, having someone else pay for your expenses because you’re too lazy to get a job or for whatever reason. It’s a negative way of describing how someone else is helping you, and you don’t really deserve perhaps that help, or you’re not helping yourself when you could. It’s definitely an insulting expression.
We’re not referring here to children, for example, who have the right to expect their parents will help them. We’re talking, perhaps, about a friend or someone who’s already an adult who we expect to go out and make their own living – that is, get their own money – and they’re still living with someone who’s paying their expenses.
We have a couple of other expressions for this same idea: “to live off someone,” “to mooch (mooch) off someone,” or simply, “to freeload” (freeload). All of these are negative ways of describing someone who takes money from another person even though they could go out and get their own money.
If you have a question or a comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
to thrive – to do very well; to grow and be successful
* The new trees should thrive in this park because they’ll get a lot of water and sunlight.
arch – a tall, curved shape or structure, often used to support a bridge, wall, or roof
* The arch over the church’s doorway is two-stories high.
diversified – for a company to have a larger variety of products to sell and/or to increase operations
* In the 1980s, this company only sold food, but now it has diversified and sells clothing and toys as well.
to make it to – to be able to go to a place, usually when there is some time limit or obstacle that could stop one from reaching it
* On our vacation, we only have two days to visit London, so I’m not sure we’ll make it to all of the museums we want to see.
to touch on – to talk about something briefly without giving very much detail
* The mayor’s speech touched on his new plan to help the poor, but he gave no details.
allegedly – believed to be true, although it cannot be proven
* Dan allegedly borrowed the money and had planned to pay it back, but most people think he tried to steal it.
mistress – a woman who is in a sexual relationship with a man who is married to someone else
* How do politicians with mistresses hope to keep the relationship quiet?
besotted – loving someone very deeply, so that one cannot think about anything else and cannot behave normally
* Dan is besotted with Beatrice and talks about her all the time.
scandalous – something that is very shocking because it breaks the rules of what is acceptable in society
* The way she treats her children as servants is scandalous!
to abdicate the throne – to give up one’s position as king or queen; to say that one will no longer serve as king or queen
* If the responsibilities of being queen became too much to handle, would you consider abdicating the throne?
to discharge – to perform one’s duty; to do what is required according to one’s responsibilities
* If any officer is unable to discharge his or her duties, he or she will be removed from a position of responsibility.
recluse – a person who lives alone and does not interact or speak at all or very much with other people
* After his wife died, Quinn became a recluse and his only company is his dog.
limit – a point after which something does not, cannot, or is not allowed to go on; a number or amount that cannot be passed
* Jaime loves to eat. I don’t think there’s a limit to how many hot dogs he can eat in one meal.
limitation – a problem caused by limited abilities; a rule; something that restricts behavior or actions
* Having bad knees and not being able to bend easily is a limitation on the types of exercise Lenora can do.
to undercut – to make something less effective; to make something smaller; to harm; to sell at a lower price than one’s competitors
* Eating a lot of potato chips will definitely undercut the effectiveness of your diet.
set – having been put in a certain place or at a certain position; a determined position or condition
* Will you please set the video recorder to record my favorite show while I’m out tonight?
target – goal; a point or position one tries to reach; someone or something that is attacked
* Our sales target for this month is even higher than last month’s target.
to sponge off (someone) – to get something from someone else without paying money or doing any work; to live off someone else
* When will your brother stop sponging off you and start paying for his own living expenses?
What Insiders Know
Columbus Day Controversy
The United States “celebrates” (recognizes and honors) Christopher Columbus’ arrival to the Americas on October 12, 1492 with an official holiday each year. It is celebrated on the second Monday each October.
Columbus Day became a “federal” (national) holiday in 1937, although Americans have been recognizing Columbus’ “voyage” (long journey by sea or in space) long before that year. For example, New York City and other U.S. cities celebrated the 300th “anniversary” (a date on which an event took place in previous years) of Columbus’ arrival in 1792, and in 1892, President Benjamin Harrison encouraged Americans to celebrate the 400th anniversary.
However, not everyone believes Christopher Columbus should be honored in this way. Some “activists” (people who take actions to try to cause political or social change) “oppose” (are against) Columbus Day because of Columbus’ and other Europeans’ actions against the “indigenous” (original peoples) in America. Although Native American groups have “spearheaded” (lead a movement for change) the “elimination” (removal) of Columbus Day as a holiday, the idea has not received “widespread” (among many people) acceptance.
There are two states that do not officially recognize Columbus Day: Hawaii and South Dakota. Instead, these states recognize another holiday on that date. Hawaii celebrates Discoverers’ Day, which “commemorates” (remembers and honors) the Polynesians’ discovery of Hawaii. And in South Dakota, “residents” (people who live in an area) celebrate Native American Day instead of Columbus Day.