= 1617
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 312.
This is English as a Second Language Podcast’s English Café episode 312. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide. You can do that by becoming a member of ESL Podcast and supporting our efforts here.
On this Café, we’re going to talk about a man was very famous in the 60s and 70s, a man by the name of Jimmy Hoffa, and the organization he was associated with, the Teamsters. We’ll also talk about the National Geographic Society, something that most all Americans are familiar with. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion of Jimmy Hoffa and the Teamsters. Jimmy is typically an informal name for James. James, or Jimmy Hoffa was born in the state of Indiana in 1913. Indiana is located in the midwestern part of the United States, between the states of Illinois and Ohio. When Hoffa was a teenager, he worked for a grocery store, and at the time he was working there the employees – the other people working there – were trying to fight for their rights. They thought the company – the store was not treating them right. Even though Hoffa was very young, he became involved, as a teenager, in something called a union.
A “union” (union) is a group of people who work for a particular company, or sometimes a certain kind of company, who join together or work together to try to protect their rights. They might, for example, try to get more money, what we would call “higher wages.” So, they group together – they come together and they negotiate with the company, they sit down and try to get better pay for themselves by working together. The idea of a union is if the company says no or doesn’t agree, the workers can stop working, and then the company wouldn’t have workers unless, of course, they went and found other workers, which is quite common, or used to be quite common when unions went on strike. “To go on strike” means to stop working. So, that’s what a union is, and Jimmy Hoffa got involved in unions. The unions typically negotiate with the companies’ leaders; we would call them the “management.”
Hoffa became involved in the grocery store union when he was still a teenager, but other union members were very impressed with his work. They realized this kid was smart. He did a good job, so soon he was made a leader, and in 1932 he joined a union, or became part of a union called the Teamsters.
The Teamsters were, and in some ways still are, a powerful union in the United States. Technically, they’re known as the International Brotherhood of Teamsters, Chauffeurs, Warehousemen and Helpers of America, but we just call them the Teamsters. In other words, it’s a union of people who are involved in driving cars and trucks for companies. It’s also a union for people who work in warehouses, which are large buildings where companies put their products and materials before they sell them. That’s the Teamsters.
When Hoffa joined the Teamster Union, it only had about 75,000 members in the United States. Hoffa worked hard to consolidate or to merge the Teamsters, to make the Teamsters join other unions – to combine with other unions. Each time he did this, the Teamsters became larger and larger. By 1951 there were more than one million members of the Teamsters and it was the – or one of the most powerful unions in the United States.
In 1952, Jimmy Hoffa became vice-president of the Teamsters, and in 1957 he became the leader – the president of this powerful union. The union continued to grow with Hoffa as its president, and in 1964 he expanded the union – the Teamsters to cover almost all of the truck drivers in the United States, the, at that time, mostly men who drove large trucks, transporting things from one area of the country to another or one part of a city to another. This increased the Teamsters’ power even more, and Jimmy Hoffa’s influence on business and politics even more.
During the time that Hoffa was president of the Teamsters, the mob, what we sometimes call the “mafia,” began to have or increased their influence on unions. The “mafia” or the “mob” (mob) is a group of organized criminals. Hoffa and the Teamsters Union were thought to have close ties or close connections to some mafia leaders. In fact, the government eventually “convicted,” or found guilty, Hoffa of fraud and bribery. “Fraud” (fraud) is when you lie to people to get something, usually to get their money. “Bribery” (bribery) is when you pay someone to do something for you secretly. In this case, Hoffa tried to bribe a group of people, the jury, who were deciding whether a person was guilty or not in a criminal or court trial. This is a very serious crime when you try bribe the men and women who are making decisions in the court system, what we call the “jury.”
Hoffa was punished for what he had done, but not as much as some people would have liked. He served five years of his 13-year sentence. A “sentence,” in this case, is the length of time that you are supposed to be in jail. It’s very common in the U.S., and in other countries, for someone to be sentenced for, say, 20 years, but only actually stay in prison for maybe 10 years or 15 years; they get out early for a variety of reasons. So Hoffa only went to jail for five years of his 13-year sentence. President Nixon let him out early in 1971. The president has the power, in some cases, to let prisoners out of jail. He said that Hoffa could leave jail as long as he didn’t participate in any other union activities for the next 10 years.
However, Hoffa was still connected to the mob, and many people think it was those connections that led to his disappearance in 1975. Apparently Hoffa was supposed to meet with two mob or mafia leaders in a parking lot that day, but the two people say they were never going to meet him. Hoffa simply disappeared. No one knows what happened to him. Most people think that the mob or the mafia killed him and then got rid of his body.
I remember this time, in the mid-1970s; there was a lot of speculation – a lot of guessing about what happened to Jimmy Hoffa, a lot of jokes, quite honestly, about his disappearance. As often happens when someone disappears suddenly, there are all sorts of stories and rumors that people start talking about. We talked about the disappearance of a man named D.B. Cooper a few years ago on English Café number 151. Well, Hoffa is a similar case, someone who suddenly and unexpectedly disappeared. No one knows what happened to him; but there are some interesting stories about what happened to his body, if he were killed. Some people say that his body was put into the concrete – the cement that was used to build the football stadium for the New York Giants. Some people say that his body is buried underneath this swimming pool or in that building. Sometimes the government agencies – the police try to follow up on these leads. That is, they try to determine if these stories were true. Even recently, the police have investigated some of these stories. In 2006, the Federal Bureau of Investigation – the FBI searched a farm in Michigan where people said Hoffa’s body was buried, but of course no one was able to find anything. So if you happen to know where Jimmy Hoffa is, email us here at eslpod@eslpod.com and we’ll announce it in our next Café!
Now let’s turn to our next topic, a famous organization in the United States called the National Geographic Society. “Geographic” refers to “geography,” which is the study of where things are, the study of the characteristics of different locations. It could be their actual location, where they are; it could be the kinds of animals and plants you find there; all of these things would be part of geography.
The National Geographic Society, or organization, was started in 1888 by a group of 33 men who wanted to learn more about the world around them. Today, the organization’s mission or purpose is “to increase and diffuse geographic knowledge.” “To diffuse” (diffuse) means to spread something over a large area, so in this case the National Geographic Society wants to give people knowledge about different aspects of geography. It does this by conducting or doing research – investigations. It also does exploration; it goes to places where people have not gone before, or have only gone very infrequently, to learn more about these places.
The National Geographic Society has many different activities; the best known, however, is its magazine, National Geographic Magazine. The magazine has been around for many years. It has many interesting articles, beautiful photographs of people and places around the world. In the past, it was one of the few ways that people could learn about other cultures before the Internet, before there was widespread or popular watching of television. Today, National Geographic Magazine is still produced – still published; it’s in 32 languages and has approximately 50 million readers. Perhaps you’ve seen a copy of National Geographic Magazine in your own language.
There are additional magazines that National Geographic publishes. It has National Geographic Kids, for children; it has one called National Geographic Traveler, which talks about different trips you can take, and it has a couple others as well. National Geographic also publishes books and maps. They have a famous set of books that are atlases. An “atlas” (atlas) is a large book with very detailed maps and information about a certain place. Before the days of GPS and iPhones and Google Maps, it was quite common in most cars in the United States to find some sort of map or book of maps, and that book of maps would have been called an “atlas.” We had a road atlas in our car. In fact, I still have a road atlas, I think, in my car, but I don’t use it very often anymore because I just look at my phone and look at the map on there.
National Geographic is also famous for giving money to scientists to study things and explore things. They’ve given money to many different kinds of explorers and scientists. They’ve given money to anthropologists, scientists who study cultures and peoples. They’ve given money to primatologists, scientists who study animals like monkeys and gorillas, and many other kinds of scientists.
Right now the organization is involved in what’s called the Genographic Project. Researchers are using DNA, or genetic information to understand how human beings have moved around the planet in the past – how they have migrated, and how these different groups of people are related to each other, how we are related to other people. The organization is also involved in trying to document – to get information on what are called “dying languages,” languages that are spoken by only a small group of people, and when those people die the language will die with them. So they try to get as much information about the language as possible before the last speaker of that language dies.
In recent years, National Geographic has also produced many television programs. In fact, here in the United States there is a channel called National Geographic, where you can watch programs all day about nature and geography. It has produced one movie that became quite famous, March of the Penguins. In 2006 this movie was given a prize – an Academy Award, or simply more commonly, an Oscar for Best Documentary.
Finally, National Geographic is also involved in something in the last, oh, 20 years or so called the National Geographic Bee (bee). A “bee” is when students – schoolchildren stand up and have to answer questions. The most famous kind of bee would be a spelling bee. But now, we have a National Geographic Bee, where students stand up and answer questions about world geography, and they get scholarships – they get money for school if they answer questions correctly.
Speaking of answering questions, now let’s answer some of yours.
Our first question comes from Hendrik (Hendrik) in Germany. Hendrik wants to know the difference between “shade” (shade) and “shadow” (shadow). Let’s start with “shade.”
“Shade” can have a couple of meanings. It can be an area outside – outside of a house that is darker because there is something blocking the sun. If it’s very sunny out, you may say, “Let’s get into the shade under the tree,” where the tree is blocking the light from the sun.
A “shade” can also be something you put on your window that blocks the sun. On my windows in front of me, I have shades. I can open them and lower them if I want more or less light, or if I just don’t want anyone to see me.
Sometimes informally people will call their sunglasses their “shades.” I’m not sure if they still do that; they used to when I was younger. You might say to someone who had nice sunglasses, “Nice pair of shades, dude.”
A “shadow” can mean something similar to “shade.” In fact, we can think of “shade” when we talk about it being the area on the ground or that is darker than the area around it because there is something blocking the light of the sun. Shade is a kind of shadow. A shadow, however, can also be caused by a light bulb, where you have the light on and I stand in front of the light bulb and on the ground you can see my shadow, a shape of me. So shadow can be caused by the sun; a shadow can be caused by a light. “Shade,” in the first definition that we gave, is a kind of shadow, and you can have shadows outside as well.
Another difference is that “shadow” is usually used to describe that dark area caused by something in between a light source and the ground that has a definite shape; you can identify it, you can see that it’s a person or a dog or whatever. “Shade” is normally more general; when talking about outdoors, it’s not something that is identifiable. So, shade may be a very large area of darkness caused by something blocking the light of the sun. A “shadow” tends to be used specifically for some object whose shape you can determine by looking at the ground.
Alexey (Alexey) in Russia wants to know the difference between “rarely” (rarely) and “seldom” (seldom). Both “rarely” and “seldom” mean not often; something that doesn’t happen very much or very frequently. “I seldom read after 10 o’clock at night,” maybe once every two weeks, but usually I don’t read after 10 p.m. That’s because I go to sleep early. I’m old! You know; old people, we go to sleep early.
“Rarely” can mean exactly the same thing, and does. “It really rains in Southern California.” That’s sort of true; it does rain in Southern California, but there are certain months where it never rains or almost never rains or rarely rains.
I would say that the word “rarely” is more common in conversational English. “Seldom” is used, you will hear people say it; it might be a little more common in something you read.
Native American speakers often use the expression that might be a little confusing with “rarely,” and that’s “rarely ever.” “Rarely ever,” however, means the same as “rarely.” “I rarely ever see you anymore” means the same as “I rarely see you anymore.” It’s a little bit redundant, it’s a little bit repetitious, but you’ll hear it very frequently.
Susana (Susana) in the beautiful country of Australia wants to know the meaning of an expression we have, “every cloud has a silver lining” (lining). Well, a “cloud,” you probably know, is something that is white or gray that is up in the sky. A “cloudless” day would be a day with no clouds. Or, “It’s a very cloudy afternoon,” there are lots of clouds in the sky that are blocking the light of the sun.
“Lining” is normally what we use to describe the inside of a piece of clothing, especially a coat or a jacket. “I need a new lining for my winter coat.” That means the inside of the coat needs to be replaced. “Lining” can also refer to something you may put inside a box or container or drawer to protect it, such as plastic.
“Every cloud has a silver lining” means in every bad situation there is something good about it, there is something positive. Of course, that’s not always true, but it’s an optimistic, positive expression – “every cloud has a silver lining.” We sometimes say this to people who have problems and they are feeling depressed and we try to get them to see maybe something positive in their problems. Doesn’t usually work, but you can try.
Finally, Normando (Normando) from Italy wants to know how to pronounce a couple of words. Well, let’s start with the first word (soccer); this word in English is pronounced “soccer.” It is, of course, a game popular in almost every country in the world, with the exception of the United States. That’s not true. It is popular in some places, but not as popular as in, say, Italy.
The other word is (sucker). That word is pronounced “sucker.” I think they’re very close in my accent; I might say, “soccer, sucker, soccer, sucker.” Yeah, they’re kind of the same. “Sucker” is a word that we would use for someone who has been tricked or is easily fooled. “Don’t be a sucker” means don’t get fooled; don’t be fooled by other people. Sometimes you’ll hear the word “sucker” when people are talking about something they’re having difficulty with, especially if it’s small. I’m not sure why. For example, you have a pen and you can’t get it open, so you might say, “I can’t get this little sucker open,” something like that.
If you have a question, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
union – a group of people who work for a particular company, or in a particular type of job, who form an organization to try to protect their rights and/or to improve their salaries and working conditions
* My brother is an electrician and every electrician he knows is a member of the electricians union.
management – the top executives of a company; the leaders of the company who make the most important decisions
* Management decided to cut vacation time from two weeks a year to one week each year to save money, and the workers are very unhappy about it.
Teamsters – a very powerful union (organization of workers) formally known as the International Brotherhood of Teamsters
* The Teamsters was one of the most powerful unions in the United States.
mob – mafia; a large, organized group of criminals
* This street’s storeowners pay money to the mob to stay in business.
to convict – to be found guilty of committing a crime; to have a judge or a court decide that one has done something against the law
* Do you believe the right person was convicted for the murder?
fraud – lying to people to get something, usually money; deceiving other people to gain something for oneself
* Don’t believe the ad that promises to pay you for doing nothing. I’m sure it’s a fraud.
bribery – paying someone secretly so that he or she will do (or not do) something to benefit oneself
* The health inspector was convicted of bribery after it was discovered that she was taking money from restaurants to avoid violations.
sentence – the length of time someone is supposed to remain in jail after having been found guilty of committing a crime
* The thief received a short sentence of one year in jail because it was the first time he had been caught committing a crime.
to follow up on a lead – to do things to try to determine whether a clue, sign, or indication will lead to the truth or something one is looking for
* Police detectives followed up on a lead that the missing girl had actually run away and is staying with her friend.
to diffuse – to spread something over an area; to cause something to reach a larger area
* The power of the Internet has diffused all over the world.
atlas – a large book with detailed maps and other information about different parts of the world
* In this old atlas, you can see maps of countries that no longer exist!
dying language – a language that is spoken by very few people and is being forgotten
* Many Native American languages are considered dying languages because so few children learn it from their parents or the elders in the community.
shade – an outdoor area that is darker than the space around it because an object is between it and the sun; an object made to block sunlight
* We’ll have to get to the park early if we want to find a picnic table in the shade on the Fourth of July.
shadow – an area that is darker than the area around it because an object is between it and the light; the outline of an object on the ground or a wall, when the object is placed between the ground or wall and the light
* The dog always walks in the man’s shadow, as though they’re moving as one unit.
rarely – not often
* You will rarely see a movie as bad as the one we saw tonight!
seldom – not often
* Jamal seldom spoke of his father after his death because the memories were too painful for him.
every cloud has a silver lining – in every bad situation there is some good; even in the worst situation, there is usually something positive
* Jenise didn’t get any of the 20 jobs she interviewed for, but every cloud has a silver lining. She decided to write a book about her job application experience.
What Insiders Know
The Jersey Shore and Italian American Stereotypes
The Jersey Shore is an American “reality” television show that follows eight young adults living together and spending the summer together at the Jersey Shore. The Jersey Shore is located off the Atlantic “coast” (where the ocean meets land) of the state of New Jersey in the northeastern United States, and is a popular tourist “destination” (location to visit).
The show Jersey Shore “premiered” (was first shown) on MTV, the music cable television station, in 2009. It is now in its fourth “season” (year; period of time when a number of new episodes of the show is shown, one after another). The show “centers around” (is mainly focused on) the social life of these eight people and their interactions and relationships with each other.
One of the major criticisms of this show has been its portrayal of Italian Americans. Most of the “cast members” (people who act in a show) are of Italian “descent” (having a background or ancestors from a particular cultural group) and the terms “Guido” (for a man) and “Guidette” (for a woman) have been widely used. These terms are “derogatory” or insulting to Italian Americans and “conveys” (communicates) “stereotypes” (untrue or not accurate generalizations) about Italians and how they behave. Italian American organizations have complained to MTV, who actually used the word “Guido” in its advertising and promotion of the show. Politicians from the state of New Jersey have also criticized the show for its negative “portrayal” (showing something as the truth) of people of New Jersey, when in fact, most of the cast members are from the state of New York, not New Jersey.
Despite these “controversies” (issues that many people have strong opinions about), the show is very popular. Several of the cast members have developed their own “product lines,” selling products associated with their name, and have become quite “wealthy” (rich; with a lot of money).