= 0394
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 394: Describing Hatred and Anger.
This is English as a Second Language Podcast episode 394. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Visit it and download a Learning Guide for this episode that contains all of the vocabulary, definitions, sample sentences, additional definitions not found on the audio podcast, cultural notes, comprehension checks, and a complete transcript of every word we say on this episode.
This episode is a dialogue between Danica and Neil about anger and hatred, some common vocabulary we use when we are angry with someone. Let’s get started.
[start of dialogue]
Danica: Calm down! Stop throwing things! Have you gone berserk?
Neil: Calm down?! Calm down?! You don’t know what just happened.
Danica: I’ve never seen you lose your temper like this before. Take a deep breath and tell me what happened.
Neil: Okay, you know that I like Samantha, right? Well, I told Malik last week. I just found out today that he’s dating her.
Danica: Malik? But he’s your best friend. He wouldn’t do that.
Neil: Do you think I’d be having a fit if I weren’t absolutely certain?
Danica: How can you be so sure? Did he tell you?
Neil: He didn’t have to. I saw him with Samantha together after work. He had his arm around her! I was ready to go off the deep end when I saw the two of them together.
Danica: How do you know he wasn’t sweet-talking her for you? He could have been putting in a good word for you, you know.
Neil: That’s bull! That guy is a traitor and I despise him. And I’m such a schmuck for trusting him.
Danica: Well, I still think you may have gotten the wrong idea. Are you going to talk to him about it?
Neil: You bet I am, just as soon as I stop foaming at the mouth.
[end of dialogue]
Our dialogue begins with Danica saying to Neil, “Calm down!” This expression is used when you are asking or telling someone else to become calmer, more peaceful, to become less angry or worried. It’s usually used when someone gets angry and you are trying to get them not to be angry. “Calm down! Stop throwing things!” she says, “Have you gone berserk?” “To go berserk” (berserk) means to lose control of your emotions, to go crazy. We may say, “The little boy went berserk because his friend took his bicycle.” He went crazy; he started yelling, and crying, and getting very angry. That’s to go berserk.
Neil responds to Danica, “Calm down?! Calm down?! You don’t know what just happened.” Danica said, “I’ve never seen you lose your temper like this before.” “To lose your temper” (temper) means to lose control of your emotions. It’s similar to “to go berserk,” but it’s a little less, perhaps, serious. People who lose their temper may start shouting, may be very angry. That’s what might happen if you lose your temper. To go berserk is a little more serious; you may start throwing things, for example.
Danica says to Neil, “Take a deep breath and tell me what happened.” “To take a deep breath” means to fill up your lungs with air very slowly. It is supposed to be a way to help you become more calm when you are very angry or worried. So, the person may go (sound of a deep breath). That’s taking a deep breath; breathing air in all the way and then breathing it out, to calm you down.
Neil says, “Okay, you know that I like Samantha, right? Well, I told Malik last week. I just found out today that he’s dating her.” So, Neil likes this woman named Samantha, and he tells his friend Malik that he likes her then Malik goes and gets a date with the same girl. Not very nice!
Danica says, “Malik? But he’s your best friend. He wouldn’t do that.” Neil says, “Do you think I’d be having a fit if I weren’t absolutely certain?” “To have a fit” is similar to “to go berserk.” It means to become very upset, to be shouting perhaps, to be doing things to show that you are angry. “Absolutely,” here, means completely, totally. Neil is saying, “I am completely certain that Malik is dating Samantha.” “Absolutely” has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations.
Danica then asks Neil, “How can you be so sure? Did he tell you?” Neil says, “He didn’t have to.” It wasn’t necessary for Malik to tell Neil. He says, “I saw him with Samantha together after work. He had his arm around her!” He had his arm around her waist, for example. This is usually a sign that the two people are romantically interested in each other, but not always. Neil says, “I was ready to go off the deep end when I saw the two of them together.” “To go off the deep end” means, again, something similar to “to go berserk.” It means to lose control of your emotions, to go crazy, to get very, very angry. For example, if you are married and you forgot your wife’s birthday, she might go off the deep end – she might get very angry. You might be sleeping at a friend’s house for a few days, for example!
Danica says, “How do you know he wasn’t sweet-talking her for you?” To “sweet-talk” someone is to say something nice to someone. So, what Danica is suggesting is that Malik was talking to Samantha, but saying good things about Neil; he was trying to help Neil with this woman – to get a date with this woman. To sweet-talk a woman or to sweet-talk a girl means to say nice things to them so that, perhaps, they will go out on a date with you. I’m very bad at sweet-talking women!
Danica continues, “He could have been putting in a good word for you, you know.” To “put in a good word for someone” means to say something nice about somebody so that someone else will have a good opinion of that person. So, if you are interested in dating this woman that I know, I may say to her, “Well, Bob here, he’s a very intelligent person. He’s also very sensitive. He has a lot of money!” See, that would be putting in a good word for you, so if you ever need me to do that, just email me. But remember, I’m really bad at sweet-talking women, so it probably won’t help you very much!
Neil responds to Danica’s possible explanation by saying, “That’s bull!” (bull). “Bull,” in this case, means a lie, something that is not true. It’s actually short for a longer, vulgar expression, but in informal conversation it’s possible to say “it’s bull.” It’s a little informal; it’s not something you would say to your boss, for example – at least if you wanted to keep your job! “Bull” has a couple of different meanings; take a look at the Learning Guide for some additional explanations of that word.
So, Neil says that’s not true; Malik “is a traitor and I despise him.” A “traitor” (traitor) is a person who betrays his or her country or someone else, a person who is not trustworthy – someone you can’t trust. A traitor would, for example, takes some secrets from your government and give them to another government. That would be a traitor, someone who doesn’t remain loyal to you. In this case, Malik is a traitor because he went and started dating the woman that Neil likes.
Neil says that he despises Malik. To “despise” means to hate, to dislike very much. He says, “I’m such a schmuck for trusting him.” A “schmuck” (schmuck) is a person who is easily fooled or easily tricked; a person who believes things that aren’t true. Schmuck is one of the many Yiddish words in English. It’s used now by almost everyone, or most people at least understand the meaning of the word “schmuck.”
Danica says, “Well, I still think you may have gotten the wrong idea.” To “get the wrong idea” means to misunderstand something, to interpret something incorrectly. Sometimes when we think we will not be understood clearly we may say, “Don’t get the wrong idea” – don’t misunderstand me.
Danica asks Neil, “Are you going to talk to him about it?” Neil says, “You bet I am, just as soon as I stop foaming at the mouth.” “You bet I am” is a phrase used to say “yes” in a very strong way about something you are going to do. “Are you going to quit your job when you win the million-dollar lottery?” someone says you, and you say, “You bet I am!” To “foam (foam) at the mouth” means to be very angry, to be so angry that you cannot control your emotions, similar to some of the other expressions we used earlier in the dialogue.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Danica: Calm down! Stop throwing things! Have you gone berserk?
Neil: Calm down?! Calm down?! You don’t know what just happened.
Danica: I’ve never seen you lose your temper like this before. Take a deep breath and tell me what happened.
Neil: Okay, you know that I like Samantha, right? Well, I told Malik last week. I just found out today that he’s dating her.
Danica: Malik? But he’s your best friend. He wouldn’t do that.
Neil: Do you think I’d be having a fit if I weren’t absolutely certain?
Danica: How can you be so sure? Did he tell you?
Neil: He didn’t have to. I saw him with Samantha together after work. He had his arm around her! I was ready to go off the deep end when I saw the two of them together.
Danica: How do you know he wasn’t sweet-talking her for you? He could have been putting in a good word for you, you know.
Neil: That’s bull! That guy is a traitor and I despise him. And I’m such a schmuck for trusting him.
Danica: Well, I still think you may have gotten the wrong idea. Are you going to talk to him about it?
Neil: You bet I am, just as soon as I stop foaming at the mouth.
[end of dialogue]
The script for this episode was written by a woman who never loses her temper, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
calm down – to become calmer; to become more peaceful; to become less angry or worried
* Please calm down! It doesn’t do any good to be so upset.
to go berserk – to lose control of one’s emotions and/or actions; to go crazy
* The little boy went berserk, kicking and screaming when his friend wouldn’t share her new bicycle with him.
to lose (one’s) temper – to lose control of one’s emotions and/or actions; to become very angry very quickly
* When you were growing up, did you ever lose your temper and hit your brothers or sisters out of anger?
to take a deep breath – to fill one’s lungs with a lot of air very slowly to try to become calmer and more peaceful when one is very angry or worried
* Pete was so angry with his computer that he wanted to throw it through the window, but instead he took a deep breath and then began to feel better.
to have a fit – to become very upset for a period of time, speaking and/or acting angrily
* Your parents are going to have a fit when they find out that you used their car without asking them first.
absolutely – completely; entirely; totally
* Are you absolutely sure that you don’t want to go with us to the theater tonight?
to go off the deep end – to lose control of one’s emotions and/or actions; to go crazy
* Losing your job, home, and wife in a single week is enough to make anyone go off the deep end.
to sweet-talk – to say something very nice to someone; to say nice things to someone, usually because you want something from him or her
* Mindy is trying to sweet-talk her boss into letting her take a four-week vacation in June.
to put in a good word for (someone) – to say something good about someone so that another person will have a good opinion of him or her
* I just applied for a job at your company. Could you please put in a good word for me with your boss?
bull – something that is not true; a lie
* Ulysses said he wrote the report by himself, but that’s bull! I know that Maria did most of the work.
traitor – a person who betrays a country or someone else; a person who is not loyal or trustworthy
* He is a traitor to his country, selling national secrets to other governments.
to despise – to hate; to dislike very much
* I despise jokes about people’s skin color.
schmuck – a person who is tricked easily; a person who believes things that are not true
* What kind of schmuck would fall for that trick?
to get the wrong idea – to misunderstand something; to interpret something incorrectly
* Kevin and Becky like to spend a lot of time together, but they don’t want their friends to get the wrong idea and think that they’re dating.
you bet I am – a phrase used to answer ‘yes’ very strongly about what one is going to do
* - Are you going to quit your job when you win the lottery?
* - You bet I am!
to foam at the mouth – to be very angry; to be so angry that one is unable to control one’s emotions
* Hugo was foaming at the mouth after he learned that someone had stolen his car.
Comprehension Questions
1. Which of these phrases has the same meaning as “to go berserk”?
a) To lose one’s temper.
b) To take a deep breath.
c) To sweet-talk.
2. When will Neil talk to Malik about what happened?
a) After he has brushed his teeth.
b) After he calms down.
c) After he eats some foam.
Answers at bottom.
What Else Does It Mean?
absolutely
The word “absolutely,” in this podcast, means completely or entirely: “I won’t get married until I’m absolutely sure that I’ve found the right person.” The word “absolutely” can also mean very or extremely: “They absolutely love the opera.” “Absolutely” can also be used to provide emphasis, or to make a statement stronger: “That is absolutely the ugliest dress I’ve ever seen!” Or, “We save absolutely everything we can.” The word “absolutely” can also be used to respond positively to a question, meaning yes or that one completely agrees with something: “Do you think that’s a good price for the car?” – “Absolutely!” The opposite phrase is “absolutely not,” used to show that one does not agree with something: “Do you like flying?” – “Absolutely not! I’m scared of airplanes.”
bull
In this podcast, the word “bull” means something that is not true: “Kristoff says that he doesn’t drink, but that’s bull! I saw him having a beer at the bar last weekend.” A “bull” is also a male cow: “Be careful to stay away from the bull’s horns.” The phrase “to take the bull by the horns” means to do a difficult project or deal with a difficult situation without being scared of it: “Ibertia decided to take the bull by the horns and file her own taxes this year, without using an accountant’s services.” Finally, the phrase “like a bull in a china shop” means clumsily or not carefully, accidentally hitting and breaking many things: “The two children ran through the glass store like a bull in a china shop.”
Culture Note
Benedict Arnold was a “general” (military leader) in the army during the “Revolutionary War” when the land that would later become the United States fought for its independence from Great Britain. He worked very hard, was very successful, and was widely “admired” (very well liked) for his work as a general. Many people believe that we might have lost the Revolutionary War without his military “contributions” (the things that a person does for something, or the ways that a person helps something).
However, other generals “got credit” for many of Benedict’s successes. They “got promotions” (received better positions) for their work, but Benedict was not able to “move up” (get a better position) in the army. At this same time, Benedict began to run out of money. These are probably the reasons “behind” (explaining) what happened next.
In 1780, Benedict was “given command” (put in charge of) a “fort” (a military place for defense) called West Point in New York. Once this happened, he secretly “switched sides” (began working for the other side of the war) and tried to find a way to give the fort to the British government. In other words, Benedict became a traitor.
Fortunately, Benedict’s plan was discovered before he could “betray” (be disloyal to) the new American government. He ran away and moved to London, where he lived “in exile” (unable to return to one’s own country) for the rest of his life. Today people remember Benedict Arnold as one of the most famous traitors in American history.
Comprehension Answers
1 - a
2 - b