= 0398
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 398: Parts of a City.
This is English as a Second Language Podcast episode 398. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
We have a website at eslpod.com. Go there today and download a Learning Guide for this episode, a special 8 to 10 page guide that gives you all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of every word we say on the episode.
This episode is called “Parts of a City.” It’s a dialogue between Tanya and Darren using vocabulary that we have to describe different parts of a city. Let’s get started.
[start of dialogue]
Tanya: We’ve been here for three days and I’m still getting lost.
Darren: Here’s a map. These are the residential neighborhoods. See? This is where we’re staying.
Tanya: I know, I know. But where were we today? The tour bus went down so many alleys that I lost my bearings after 10 minutes. I thought we were going in circles.
Darren: Look, we drove through downtown first, past the financial district. Next, we drove past the housing projects to the historic district.
Tanya: I remember all that.
Darren: Okay, then. From the historic district, we drove through uptown. Got that?
Tanya: Yeah, that’s where things get a little hazy. How did we get to the outskirts of town? One minute we were in uptown, and the next minute, we were at the city limits.
Darren: We took one of the back roads along here. See? Now do you understand the lay of the land?
Tanya: Yup, definitely. Ask me anything. I know this city like the back of my hand.
Darren: No, thanks. That’s like the blind leading the blind!
[end of dialogue]
Our dialogue begins with Tanya saying to Darren, “We’ve been here for three days and I’m still getting lost.” Tanya and Darren are new to this city, perhaps visiting. They’ve been there for three days. Darren says, “Here’s a map. These are the residential neighborhoods. See?” So, Darren is pointing at the map. “Residential neighborhoods” are places where people live, an area of the city where many people live, usually with many houses and/or apartment buildings. “Residential” refers to the people who live in a particular place; the noun is “resident.”
“This is where we’re staying,” Darren says. Tanya says, “I know, I know. But where were we today? The tour bus went down so many alleys that I lost my bearings after 10 minutes.” So, they are visiting; they’re on a tour bus, or were on a tour bus that “went down so many alleys.” To “go down” just means to drive on, or drive through. An “alley” (alley) is basically a small street in between two larger streets; there are buildings on either side of the alley. The alley is not used for normal traffic; it’s where a car can go to park in the back of a building for example. Some cities have alleys in their residential neighborhoods; some cities have them in some places and not others. In my neighborhood, the block – the area I live on – doesn’t have an alley, but the next block does have an alley. A “block,” of course, is a section of a city surrounded by four streets. To “lose your bearings” means to get lost, to not know where you are. The word “bearing” has a couple of different meanings; take a look at the Learning Guide for some additional explanations.
So, poor Tanya got lost; she didn’t know where she was today on the tour bus. She says, “I thought we were going in circles.” The expression “to go in circles” means to go around a certain place, but not where you want to go. It’s like you start in one place, and you travel around, and you finally come back to that same place because you don’t know where you’re going. That’s “to go in circles.”
Darren says to Tanya, “Look, we drove through downtown first, past the financial district.” “Downtown” is the center of a city, the central part where there are many buildings and businesses. Some downtowns have a lot of people who live there, who have apartments and condominiums. In New York City, Manhattan is a place like this. In Los Angeles there are people who live downtown, but it’s not a very popular area, at least traditionally. The “financial district” is an area in the city we there are many banks, other businesses related to money; so for example, a company that buys and sells stocks, a bank, these would all be found in the financial district. “Finance” is the noun; it just means money, in this case.
Darren says, “Next, we drove past the housing projects to the historic district.” A “housing project” is an area of homes or apartments, usually apartments that are built often by the government for people who don’t have very much money to give them a place to live. Sometimes they’re just called “the projects.” When someone refers to “the projects” or a “housing project,” the idea is that the people who live there are poor. There’s also an association with the word that makes people think perhaps of crime, of a not safe area.
They drove through the housing projects to the historic district. “Historic” comes from “history,” the older part of a town. In Los Angeles, we don’t really have a historic district like cities in the eastern part of the U.S. – in Boston, Philadelphia, New York to some extent. Los Angeles is a relatively new city; at least large parts of the city are relatively new compared to other cities in the east.
Tanya says that she remembers going through to the historic district. Darren says, “Okay, then. From the historic district, we drove through uptown.” “Uptown” (one word) is a part of the city that is not close to downtown, usually where there are more expensive homes. Often a richer neighborhood might be called “uptown.” Not every city has an area that is called “uptown.” Where I’m from, Minnesota, there is an uptown in Minneapolis – an area called that because it had some, and does have some very nice, expensive houses there, and apartments. St. Paul doesn’t have an uptown; neither does Los Angeles, although we have areas, of course, with very expensive houses – just not where I live!
So Darren says, “From the historic district, we drove through uptown. Got that?” he asks, meaning do you understand. Tanya says, “Yeah, that’s where things get a little hazy” (hazy). “Hazy,” in this case, means unclear or confusing, difficult to understand. “Hazy” has a couple of different meanings; you know where you can go, to our Learning Guide for some additional explanations.
Tanya, then, is a little unclear or confused; she says, “How did we get to the outskirts of town?” The “outskirts” (outskirts – one word) is the edge of a city, far from the center. Usually, it’s where the city’s border is, where the city ends and becomes something else. “Outskirts” usually implies it is part of a less populated area; we might say, simply, “the edge of town” – the outskirts. Tanya says, “One minute we were in uptown, and the next minute, we were at the city limits.” “One minute” means at one point, and then very soon after they were at another point in the city – place in the city. “City limits” is the border of the city; it’s where the city ends. In most towns in the United States – at least if you’re on a large freeway, but even in a smaller road – as you enter the city, as you cross the city limits, there’s usually a sign with the name of the city and the population of that city. Usually those numbers don’t change very much; they change them about once every 10 years.
Darren says, “We took one of the back roads along here. See?” Once again, Darren is pointing at the map. The “back roads” are small, usually not very important roads where the cars have to drive more slowly. It’s the opposite of the main road, or it could be used to mean the opposite of a freeway – the slower, smaller roads.
Darren says, “Now do you understand the lay of the land?” The expression “lay (lay) of the land” means the geography of a place, where things are. Where things are located in an area, that’s the “lay of the land.” We can sometimes use this expression when talking about a situation or a company. If you are new to the company, it will take you a while to get the lay of the land, meaning who’s important, who’s not important, who works where, and so forth. At the Center for Educational Development, the lay of the land is very easy – I am right on the bottom!
Tanya says, “Yup (meaning ‘yes’), definitely.” She definitely understands, she understands. “Ask me anything. I know this city like the back of my hand.” This is an expression we use when we are very familiar with something, when we know exactly where everything is. I know St. Paul like the back of my hand – I know where everything is.
Darren says, “No, thanks. That’s like the blind leading the blind!” This, again, is an old expression. Someone who is “blind” cannot see, so you would not want to have someone who is blind leading another person – helping another person who was blind, because neither of them would know where to go.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Tanya: We’ve been here for three days and I’m still getting lost.
Darren: Here’s a map. These are the residential neighborhoods. See? This is where we’re staying.
Tanya: I know, I know. But where were we today? The tour bus went down so many alleys that I lost my bearings after 10 minutes. I thought we were going in circles.
Darren: Look, we drove through downtown first, past the financial district. Next, we drove past the housing projects to the historic district.
Tanya: I remember all that.
Darren: Okay, then. From the historic district, we drove through uptown. Got that?
Tanya: Yeah, that’s where things get a little hazy. How did we get to the outskirts of town? One minute we were in uptown, and the next minute, we were at the city limits.
Darren: We took one of the back roads along here. See? Now do you understand the lay of the land?
Tanya: Yup, definitely. Ask me anything. I know this city like the back of my hand.
Darren: No, thanks. That’s like the blind leading the blind!
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse, who knows Los Angeles like the back of her hand!
From Los Angeles, California, thanks for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
residential neighborhood – an area in a city where many people live, with many houses and/or apartments
* We’d like to move to a residential neighborhood closer to where my wife works.
alley – a narrow street between buildings that is not used by cars very much
* It isn’t safe to walk through the alleys alone at night. Stay on the busier streets.
to lose (one’s) bearings – to get lost; to become disoriented; to not know where one is or how to get to where one wants to go
* She was reading a book on the bus, and when she looked out the window, she realized that she had lost her bearings and didn’t know where she was.
to go in circles – to go around without getting to where one wants to go; to travel but end up back where one started
* They rode the subway all morning to try to learn how it works, but they were going in circles and always ended up back in the center.
downtown – the center of a city; the central part of a city where there are many businesses and tall buildings
* Let’s meet at the café downtown on Third Avenue and Madison Street.
financial district – an area in a city where there are many banks, investment firms, and other businesses related to money
* Wall Street is a famous financial district in New York City.
housing project – an area where houses and/or apartments are built inexpensively so that people who do not have very much money can live there, especially if they wouldn’t have enough money to live in other parts of the city
* The families living in this housing project make less than $35,000 per year.
historic district – an old part of town with many old buildings that have been preserved or kept as they used to be
* The businessman wanted to build a new restaurant in the historic district, but it isn’t allowed, so he had to change an existing old building instead.
uptown – the part of a city that is far from the center, usually where there are many homes that are bigger and more expensive than homes in the center of the city
* They bought a beautiful home in uptown, but now it will take them longer to drive to work every day.
hazy – unclear, confusing, and difficult to understand; unclear and difficult to see
* Aisha’s understanding of physics and chemistry is great, but her understanding of biology is a little hazy.
outskirts – the edge of a city, far from the center and near where the city ends
* There are a lot of trees and parks in the outskirts of the city because people haven’t begun to build there yet.
city limits – the line drawn on a map around a city where the city ends and the countryside begins
* The city ends at the river, but some people want to expand the city limits so that they can begin building on the other side of the river.
back road – a small, narrow, and unimportant road where cars drive slowly; not a main road
* You can reach our home in 15 minutes if you take the freeways, but if you aren’t in a hurry, take the back roads which are slower but much more beautiful.
lay of the land – layout; physical arrangement; the geography of a place; where things are located in an area
* How long did it take you to understand the lay of the land after you moved to Los Angeles?
like the back of (one’s) hand – a phrase used to show that one knows something well or is very familiar with something
* Drake grew up playing around in the woods, so he knows that forest like the back of his hand.
the blind leading the blind – a phrase used to show that a person who doesn’t know how to do something is trying to show other people how to do it
* I’ve never baked a cake before and neither has Shannon. When she tried to teach me how to do it, it was like the blind leading the blind.
Comprehension Questions
1. Which of these might be located downtown?
a) Alleys
b) Outskirts
c) Back roads
2. What does Tanya mean by saying that she lost her bearings?
a) She lost her tools on the tour bus.
b) She felt carsick.
c) She didn’t know where they were.
Answers at bottom.
What Else Does It Mean?
bearings
The phrase “to lose (one’s) bearings,” in this podcast, means to get lost: “I tried to pay attention to where we were going, but the driver made so many turns that I lost my bearings.” The phrase “to get (one’s) bearings” is the opposite and means to figure out where one is: “Some sailors are very good at getting their bearings by studying the stars on a clear night.” Finally, the phrase “to have a direct bearing on (something)” means to affect or influence something or to be a factor in something: “Hearing two languages when you are a child has a direct bearing on your ability to learn to speak those two languages well when you are older.”
hazy
In this podcast, the word “hazy” means unclear, confusing, and difficult to understand: “I’m a little hazy on the concept of thermodynamics. Could you please explain it again?” The phrase “to be hazy about (something)” means to describe something very generally or very poorly, without providing details, especially when one is keeping something a secret: “When we asked Sarah where she had gone last night, she was very hazy about the details, just saying that she went out to have dinner with a friend.” The word “hazy” is also used to talk about air that is cloudy or dirty and difficult to see through, often because of pollution: “The sky above the city is very hazy, but it provides beautiful sunsets!”
Culture Note
American cities are responsible for providing “basic services” (things like water, electricity and garbage pick-up) within their city limits. The city provides the basic things that people need for their homes and “maintains” (keeps in good condition) the roads. Because most people live within the city limits, businesses also find “advantages” (benefits or good things about something) to living being located within the city limits because that is where their “customers” (the people who buy things from a business) live.
However, there are “disadvantages” (bad things about something) to living being within the city limits, especially for businesses. A business that “operates” (works or does business) within the city limits must pay city “taxes” (money paid to the government). But a business that lives is located in the “unincorporated area” (the area outside of the city limits) does not have to pay city taxes. This can be a big advantage, helping businesses to be more “profitable” (making more money).
In addition, businesses in the unincorporated area are not “subject to” (do not have to follow) city “ordinances” (local laws). For example, if there is a city ordinance against smoking in bars, then a bar within the city limits cannot let its customers smoke, but a bar in the unincorporated areas can let its customers smoke. “Likewise” (in the same way), if there is a city ordinance that makes it difficult for businesses to get a “liquor license” (permission to sell alcohol), businesses outside the city limits may be able to sell alcohol more easily.
When deciding where to live or open a business, it is important to consider whether the advantages of being in a city, such as basic services and a good location, “outweigh” (are greater than) the disadvantages, such as paying higher taxes and being subject to city ordinances.
Comprehension Answers
1 - a
2 - c