
= eco 2019.12 (03-04)
:toc:

---

== 03. After half a century of success, the Asian tigers must reinvent themselves

Special report: Asian tigers

Asian tigers

After half a century of success, the Asian tigers *must reinvent*(v.)(`=~ sth/yourself (as sth) : to present yourself/sth in a new form or with a new image 以新形象示人；以新形式出现`) themselves

They *must move from* growth-obsessed(a.)(`=to completely fill your mind so that you cannot think of anything else, in a way that is not normal 使痴迷；使迷恋；使着迷`) developmental states, *to* growth-friendly welfare states, say Simon Rabinovitch and Simon Cox

====
- reinvent => re-,再，重新，invent,发明，创造。比喻用法。
====

亚洲四小虎
在半个世纪的成功之后，亚洲四小龙必须重塑自己
西蒙•拉宾诺维奇(Simon Rabinovitch)和西蒙•考克斯(Simon Cox)表示，它们必须从痴迷于增长的发展中国家，转向有利于增长的福利国家


Dec 5th 2019

THE FOUR Asian tigers -- Hong Kong, Singapore, South Korea and Taiwan -- once *fascinated*(`=to attract or interest sb very much 深深吸引；迷住`) the economic world.

*From* the early 1960s *until* the 1990s, they *regularly(`=at regular intervals or times 有规律地；间隙均匀地`) achieved* double-digit growth.

A generation （统称）一代人 that *had toiled(`=to work very hard and/or for a long time, usually doing hard physical work （长时间）苦干，辛勤劳作`) as* farmers and labourers *watched* their grandchildren *become* some of the most educated people on the planet.

====
- toil => 来自中古法语 toile,网，罗网，来自拉丁语 tela,网，来自 PIE*teks, 编织，纺织，词源同 texture,textile.拼写比较 regulate,rule.引申词义圈套。
====
亚洲四小龙——香港、新加坡、韩国和台湾 ——曾经令经济世界着迷。从上世纪60年代初到90年代，它们经常实现两位数的增长。这一代人辛勤劳作，看着他们的孙辈成为了这个星球上受教育程度最高的人。

The tigers *started* by making(v.) cotton shirts, plastic flowers and black wigs 假发.

Before long 不久以后, they *were producing* memory chips, laptops and equity(`=the value of a company's shares; the value of a property after all charges and debts have been paid （公司的）股本；资产净值; /（公司的）普通股`) derivatives(`=a word or thing that has been developed or produced from another word or thing 派生词； 衍生字 ；派生物；衍生物`).

====
- wig => 源同 bigwig 要人,权贵之人 (欧洲法官戴假发)
====
四小虎国家, 以生产棉质衬衫、塑料花和黑色假发的为起步。不久，它们就开始生产内存芯片、笔记本电脑, 和股票衍生品。


[In the process] they also *spawned*(`=to cause sth to develop or be produced 引发；引起；导致；造成; /产卵`) a boisterous(a.)(`=(of people, animals or behaviour 人、动物或行为) noisy and full of life and energy 热闹的；充满活力的；活蹦乱跳的`) academic debate about the source of their success.

Some *attributed it to* the anvil(n.)(`=an iron block on which a blacksmith puts hot pieces of metal before shaping them with a hammer 铁砧`) of government direction(`=the general position a person or thing moves or points towards 方向；方位; / the art of managing or guiding sb/sth 管理；指导; / the instructions given by sb directing a film/movie （电影导演的）指点，指示`); others *to* the furnace(`=a space surrounded on all sides by walls and a roof for heating metal or glass to very high temperatures 熔炉`) of competitive markets.

在此过程中，他们也引发了一场激烈学术辩论, 探讨他们成功来源到底是源于什么? 一些人将其归因于政府指导的铁砧；另一些人则将其归因于竞争激烈的市场熔炉。
====
- spawn => 词源同 expand.引申比喻义引发，导致等。
- boisterous => 词源不详。可能来自beast, 野兽，或boast, 吹嘘。 可能来自古法语boitous("noisy"). 助记窍门：boisterous→boil（沸腾）→人声鼎沸→喧闹
- furnace => 词源同warm, thermal,burn.
- anvil => an同on. -vil, 同词根pul, 击，打，见pulse, 脉膊。 /anvil =an（on）+ vil（撞击）→在上面敲击的东西→铁砧  +
-> His independence had been forged *on the anvil of* a harsh environment. 他的独立性是在艰苦的环境中锤炼出来的。
====

Then the world *turned away*(`=If you turn someone away, you do not allow them to enter your country, home, or other place. 把…拒之门外 / To turn away from something such as a method or an idea means to stop using it or to become different from it. 不再使用`).

The Asian financial crisis *destroyed* their mystique(n.)(`= the quality of being mysterious or secret that makes sb/sth seem interesting or attractive 神秘性`).

China became the new development star, even if, to a certain extent, it *followed* their lead.

The tigers themselves *seemed to lose their stride*(`=one long step; the distance covered by a step 大步；一步（的距离）; /an improvement in the way sth is developing 进展；进步；发展`).

This year America *is* on track *to grow more quickly than* all four of them.

然后，世界转过身去。亚洲金融危机摧毁了他们的神秘感。中国成为了新的发展之星，即使在某种程度上，中国跟随了他们的脚步。四小虎国家自己也似乎失去了前进的步伐。今年，美国的增长速度将超过这四个国家。

They all *have* seemingly intractable(`=(of a problem or a person 问题或人) very difficult to deal with 很难对付（或处理）的`) problems: stagnant(a.)(`=stagnant water or air is not moving and therefore smells unpleasant （水或空气）不流动而污浊的; / not developing, growing or changing 停滞的；不发展的；无变化的`) wages 工资；报酬 in Taiwan, the dominance of big business in South Korea, an underclass of cheap imported workers in Singapore and, most explosive(`=likely to cause violence or strong feelings of anger or hatred 易爆发的；可能引起冲动的；爆炸性的`), a government in Hong Kong that *will not, or cannot, listen to* its people.

它们都面临着看似棘手的问题:台湾工资停滞不前、韩国大企业占据主导地位、新加坡廉价进口工人构成的下层阶级，以及最具爆炸性的 ——香港政府不愿、或不能倾听其人民的呼声。
====
stagnant => 来自拉丁语 stagnare,停滞，静止，来自 stagnatum,静水，死水，可能来自 PIE stag,滴，慢渗， 词源同 instill,distill,stalactite,stalagmite.
====


But it is a mistake *to write off*(`=WRITE SB/STH OFF (AS STH) : to decide that sb/sth is a failure or not worth paying any attention to 认定…失败（或没有价值、不可救药等）; /to cancel a debt; to recognize that sth is a failure, has no value, etc. 注销，销记（账项、资产等）`) the tigers.

A closer look at their economic record *shows that*, *contrary to* the gloom that sometimes *pervades*(`=to spread through and be noticeable in every part of sth 渗透；弥漫；遍及`) them, they *have much* to boast about.

The trajectory(`=the curved path of sth that has been fired, hit or thrown into the air （射体在空中的）轨道，弹道，轨迹`) of their GDP per person, *calculated* at purchasing-power 购买力 parity （两国货币的）平价, *has remained* impressive(`=making you feel admiration, because they are very large, good, skilful, etc. 令人赞叹的；令人敬佩的`) (see chart).

They *blew*(`=blow 吹`) past the supposed middle-income trap （捕捉动物的）陷阱;（难以逃脱的）困境，牢笼 long ago.

And South Korea *will soon become* the fourth tiger *to overtake* Japan, its former imperial ruler /and economic mentor.

但是，一笔勾销老虎队是个错误。仔细观察一下他们的经济记录就会发现，与有时弥漫在他们身上的悲观情绪相反，他们有很多值得夸耀的地方。按购买力平价计算，他们的人均GDP轨迹, 仍然令人印象深刻(见图表)。他们早就越过了所谓的中等收入陷阱。韩国将很快成为第四个超越日本的国家，日本曾是韩国的帝国统治者和经济导师。
====
- pervade => per-,穿过，通过，-vad,走，词源同wade, invade.引申词义渗透，弥漫。
- trajectory =>  tra-横过,越过 + -ject-投,射 + -ory
- *purchasing-power parity* 购买力平价
====

They *have also gained ground on*(`=gain/make up ground (on sb/sth) : to gradually get closer to sb/sth that is moving or making progress in an activity 逼近，迫近（正在移动或做某事的人或物）`) America.

Singapore *passed it* in the 1990s; Hong Kong *drew level* 打平局;扳平 in 2013; and the other two *have narrowed the gap*.

Indeed, in the past five years (2013-18), the GDP per person of Singapore and Hong Kong *has grown faster than* every country (above them) in the income rankings.

With a couple of exceptions, the same is true of Taiwan and South Korea.

他们也在与美国的竞争中取得了进展。新加坡在20世纪90年代超过了它；香港在2013年与美国持平；其他两个国家缩小了差距。 +
事实上，在过去五年(2013-18年)，新加坡和香港的人均GDP增速, 超过了人均GDP排名高于它们的所有国家。 +
台湾和韩国的增速也是如此, 只除了少数几个人均GDP高于它们的国家例外。

In their economic maturity(n.)(`=(of a person, an animal, or a plant 人或动植物) the state of being fully grown or developed 成熟；成年；完全长成`), the tigers *merit*(`=to do sth to deserve praise, attention, etc. 应得；值得`) renewed(a.)(`=happening again with increased interest or strength 再次发生的；再次兴起的；更新的`) attention.

随着它们经济的成熟，“四小虎”国家值得重新关注。
====
- merit +
-> The case *does not merit(`=to do sth to deserve praise, attention, etc. 应得；值得`) further investigation*. 这个案子不值得进一步调查。
====

They *face* many of the same issues that *bedevil*(`=to cause a lot of problems for sb/sth over a long period of time 长期搅扰`) the West: *how to mitigate*(`= to make sth less harmful, serious, etc. 减轻；缓和`) inequality; how to gin up productivity; *how to cope with* ageing; and *how to strike a balance*(`=strike a balance (between A and B) : to manage to find a way of being fair to two opposing things; to find an acceptable position which is between two things （在对立二者之间）找到折中办法；平衡（对立的双方）`) *between* America *and* China.

They *do not have* all the answers, but they *do have* novel, albeit(`=although 尽管；虽然`) sometimes foolish, approaches that are in themselves instructive(a.)(`=giving a lot of useful information 富有教益的；增长知识的`).

他们也面临着许多同时困扰着西方世界的问题:如何减轻不平等;如何提高生产力;如何应对老龄化;以及如何在美国和中国之间取得平衡。他们没有全部的答案，但他们确实尝试了一些新颖的方法，尽管有时这些方法是愚蠢的，但这些方法本身就是能带来教益的。
====
- bedevil => 前缀be-, 强调。devil, 魔鬼。
- mitigate => 来自拉丁语mitigare,成熟，变软，温顺，来自mitis,成熟的，柔软的，-ig,做，词源同agent.引申词义减轻，缓和。
- albeit =>  al（though）+be + it→although it be（that）→虽然如此
====




Little dragons

This special report *will examine*(`=to consider or study an idea, a subject, etc. very carefully 审查；调查；考查；考察`) the changing nature of the tigers’ economies /and *make four big claims*.

这篇特别报道, 将探讨“四小虎”经济性质的变化，并提出四大主张。

The first *is that* many of the tigers’ problems *result from* economic success, *not* failure.

They *have defended* their global export share for years, *despite* steady increases in labour and land costs.

Now, though, they *will struggle to expand* their exports *faster than* global demand itself.

They *have also reached* the technological frontier(`= ~ (of sth) the limit of sth, especially the limit of what is known about a particular subject or activity （学科或活动的）尖端，边缘; /国界；边界；边境`) in many industries.

That *makes* further improvement *harder*: they *are no longer catching up with* global best practices *but trying to reinvent*(`=to present yourself/sth in a new form or with a new image 以新形象示人；以新形式出现`) them.


Lee Kuan Yew 李光耀, Singapore’s founding father, *once claimed that* harmony and stability *are* chief(a.)(`=most important 最重要的；首要的；主要的`) among “Asian values”.

The tigers *still cherish*(`=to love sb/sth very much and want to protect them or it 珍爱；钟爱；爱护`) these things (who doesn’t?), but many of their citizens *see* fairness *as* a precondition(`=~ (for/of sth) : something that must happen or exist before sth else can exist or be done 先决条件；前提`) for both.

新加坡国父李光耀(Lee Kuan Yew)曾宣称，和谐与稳定是“亚洲价值观”的核心。四小虎国家仍然珍视这些东西(谁不呢?)，但是他们的许多公民认为, 公平是这两者能实现的先决条件。

That observation *leads to* this report’s second big claim: when a sophisticated(a.)(`=having a lot of experience of the world and knowing about fashion, culture and other things that people think are socially important 见多识广的；老练的；见过世面的`) citizenry(n.)(`=(less formal in NAmE 在北美英语中不够正式) ( formal ) all the citizens of a particular town, country, etc. 全体市民（或公民）`) *aspires(`=~ (to sth) to have a strong desire to achieve or to become sth 渴望（成就）；有志（成为）`) to* democracy, `主` frustrating(v.)(`=to make sb feel annoyed or impatient because they cannot do or achieve what they want 使懊丧；使懊恼；使沮丧`) that aspiration(`=~ (for sth)~ (to do sth) a strong desire to have or do sth 渴望；抱负；志向`) `谓` *can be* imprudent(a.)(`= not wise or sensible 不明智的；不谨慎的`) as well as unjust.

这一观察引出了本报告的第二个重大主张:当一个成熟的公民渴望民主时，挫败这种渴望, 既可能是轻率的，也可能是不公正的。
====
- sophisticate =>  -soph-聪明 + -ist名词词尾 + -ic形容词词尾 + -ate动词词尾
- frustrate => 来自fraud, 欺骗，伤害。即被欺骗的，被伤害的，受到挫折的。
- prudent => 前缀pro-表“在前，提前”；词根vid（又写作vis）表“看”，如evident（明显的）、supervise（监督）等；本意为“提前看到的”，引申为“有先见之明的”。prudent和它同源，其中"d"是词根vid的缩略。
====

Some *argue that* the blustery(a.)(`=with strong winds 狂风大作的`) politics of Taiwan and South Korea -- *complete with* high-profile(a.)(`=receiving or involving a lot of attention and discussion on television, in newspapers, etc. 经常出镜（或见报）的；高姿态的`) corruption cases, parliamentary(a.)(`=connected with a parliament; having a parliament 议会的；国会的；设有议会的`) fisticuffs(n.)(`=a fight in which people hit each other with their fists 拳斗；互殴`) and fiercely(ad.)(`=(especially of actions or emotions 尤指动作或情感) showing strong feelings or a lot of activity, often in a way that is violent 狂热的；强烈的；猛烈的`) partisan(a.)(`=showing too much support for one person, group or idea, especially without considering it carefully （对某个人、团体或思想）过分支持的，偏护的，盲目拥护的`) media -- *have hindered*(`=to make it difficult for sb to do sth or sth to happen 阻碍；妨碍；阻挡`) their growth.

一些人认为，台湾和韩国政治上的吵闹 -- 充斥着引人注目的腐败案件、议会打斗, 和有偏袒性的党派性媒体 -- 都阻碍了它们的发展。
====
- fisticuffs => fist, 拳头。cuff, 袖口，击打。
- hinder => hind,后面的，-er,比较级后缀。即更后面的，引申词义拉后腿，后由形容词变为动词，引申词义妨碍，阻挡。
====

But a proper(a.)(`= right, appropriate or correct; according to the rules 正确的；恰当的；符合规则的/ complete 完全的；彻底的`) examination of the tigers’ record *does not support that argument*.

Instead, what has become clear in Hong Kong `系` *is that* {a lack of democracy *is* a grave(a.)(`=(of situations, feelings, etc. 形势、感情等) very serious and important; giving you a reason to feel worried 严重的；重大的；严峻的；深切的`) liability(`=the state of being legally responsible for sth （法律上对某事物的）责任，义务 / a person or thing that causes you a lot of problems 惹麻烦的人（或事）`), *sowing*(`=to plant or spread seeds in or on the ground 播种；种`) dissatisfaction(`=a feeling that you are not pleased and satisfied 不快；不悦；不满意`) and mistrust}.

但是对四小虎国家的历史记录, 进行适当的研究后会发现, 事实并不支持上面的这一观点。相反，在香港发生的事已经清楚的表明，缺乏民主责任重大，会播下不满和不信任的种子。
====
- liability =>  -li-捆 + -ability名词词尾,性状 +
-> The company *cannot accept liability(`=~ (for sth)~ (to do sth) : the state of being legally responsible for sth （法律上对某事物的）责任，义务`) for* any damage caused by natural disasters. 该公司对自然灾害造成的任何损失概不承担责任。 +
-> Since his injury, Jones *has become more of a liability(`=a person or thing that causes you a lot of problems 惹麻烦的人（或事）`) than* an asset to the team. 琼斯负伤以来，与其说他是全队的骨干倒不如说他已成为队里的累赘。 +
-> The company is reported *to have liabilities(`= the amount of money that a person or company owes 欠债；负债；债务`) of nearly $90 000*. 据说公司负债近9万元。
====

Third, the tigers’ thin welfare states *have also become* a hindrance(`=a person or thing that makes it more difficult for sb to do sth or for sth to happen 造成妨碍的人（或事物）`).

Their leaders *have traditionally worried that* redistribution 重新分配 and social spending 社会支出,社会福利 *would sap*(`=~ sth /~ sb (of sth) : to make sth/sb weaker; to destroy sth gradually 使虚弱；削弱；逐渐破坏`) their populations’ motivation to work.

But social insecurity 社会保险，社会保障 *[instead] risks* sapping(v.) their populations’ willingness *to embrace* technological change.

As the tigers’ populations *get older*, their governments *also face* more pressure *to spend on* pensions and health care.

And they *need to alleviate*(`=to make sth less severe 减轻；缓和；缓解`) the economic burdens (that *dissuade*(`=~ sb (from sth/from doing sth) to persuade sb not to do sth 劝（某人）勿做（某事）；劝阻`) young people *from* having children).

The tigers’ growth-obsessed(`=to completely fill your mind so that you cannot think of anything else, in a way that is not normal 使痴迷；使迷恋；使着迷`) “developmental states” *must, in short 总之；简言之, become* growth-friendly welfare states.

====
- dissuade => dis-, 不，非，使相反。-suade, 甜，劝说，词源同sweet, persuade. 即相反的劝说，规诫。
====
第三，四小虎国家薄弱的福利制度也成为了一个障碍。这些国家的领导人, 历来担心再分配和社会支出, 会削弱民众的工作动力。但是，对社会保障的不安全感, 反而有可能削弱这些国家民众, 拥抱新技术变革的意愿。随着四小虎国家人口的老龄化，他们的政府在养老金和医疗保健方面, 也面临着更大的压力。他们还需要减轻阻碍着年轻人生育的经济负担。总之，四小虎国家必须从对“发展型国家”的专注, 转型成必须成"增长友好型福利国家"。


Finally, the tigers *are* important as economic bellwethers(`=something that is used as a sign of what will happen in the future 征兆；前导`) for the rest of the world.

====
- bellwether => bell, 钟，铃。wether, 公羊。来自于羊群放牧，通常在头羊脖子上挂一个小铃铛，带领其它羊群前进。
====

They *are unusually exposed(v.)(`=~ sb/sth/yourself (to sth) : to put sb/sth in a place or situation where they are not protected from sth harmful or unpleasant 使面临，使遭受（危险或不快） /~ sb to sth : to let sb find out about sth by giving them experience of it or showing them what it is like 使接触；使体验`) to* deep global cycles: in technology, finance and geopolitics 地缘政治.

The manufacturing 制造业 tigers *have dominated* narrow slices(`=a part or share of sth 部分；份额; /（切下的食物）薄片，片`) of the technological supply chain, *focusing on* techniques and chips that *are vital(`=~ (for/to sth) necessary or essential in order for sth to succeed or exist 必不可少的；对…极重要的`) for* high-speed 5G telecoms networks and “big-data” processing.

最后，“四小虎”作为世界其他地区的经济领头羊, 十分重要。它们深深地身受全球的各种周期影响: 在科技、金融和地缘政治方面。这四个制造业国家, 主导着技术供应链中的一些狭窄领域 -- 专注于对高速5G电信网络和“大数据”处理, 至关重要的技术和芯片。

Hong Kong and Singapore, meanwhile, *have positioned(`=to put sb/sth in a particular position 安装；安置；使处于`) themselves as* financial bridges *between* China *and* the world, *making them highly sensitive(`=~ (to sth) reacting quickly or more than usual to sth 敏感的；过敏的`) both to* China’s success *and* its stumbles(`=to hit your foot against sth while you are walking or running and almost fall 绊脚; / 跌跌撞撞地走；蹒跚而行`).

与此同时，香港和新加坡, 将自己定位为中国与世界之间的金融桥梁，这使它们对中国的成功和失败都高度敏感。

And all four of the tigers *depend on* the maintenance 维持；保持 of geopolitical calm(n.)(`=a quiet and peaceful time or situation 平静的时期；宁静的状态`) as America, the incumbent(a.)(`=having an official position 在职的；现任的`) superpower, *adjusts to*(`=adjust (to sth/to doing sth) /adjust (yourself to sth) : to get used to a new situation by changing the way you behave and/or think 适应；习惯`) a new rival.

而这四个小, 虎都依赖于地缘政治平静的维持，因为现任超级大国美国正在适应一个新的竞争对手。
====
- incumbent =>  in-,进入，使，在上面，-cumb,躺，词源同incubate,succumb.即躺在上面的，引申词义在任者。
====

These cycles *can be difficult to manage* -- even in an upswing(n.)(`=~ (in sth) a situation in which sth improves or increases over a period of time 改进；改善；上升；进步`).

====
- upswing => swing 秋千;摇摆 +
->  an upswing(n.) in economic activity 经济活动的增加
====

Booms(n.) in finance and technology *can concentrate* wealth *in* a few hands, such as South Korea’s chaebol 韩国财团 chipmakers 芯片制造商（carmaker的复数） or Hong Kong’s property(n.)(`=land and buildings 不动产；房地产`) tycoons(`=tycoon : a person who is successful in business or industry and has become rich and powerful （企业界的）大亨，巨头，巨子`).

这些周期可能很难管理 ——即使是在经济上升时期。金融和科技的繁荣, 会将财富集中在少数人手中，例如韩国的财阀芯片制造商, 或香港的房地产大亨。

On the downside(`=the disadvantages or less positive aspects of sth 缺点；不利方面`), the threats *are even greater*.

Twice [in the past quarter-century] the tigers *have been rocked(`=to shake or to make sth shake violently （使）剧烈摇摆，猛烈晃动 /岩石`) by* financial crises.

The long boom in demand for semiconductors 半导体 in smartphones and computers *has recently turned* （使）改变方向；转弯, *hurting* South Korea and Taiwan.

But it is the geopolitical challenge that most *worries* them now: a “new cold war” between China and America *would shake* the foundations 地基；房基；基础 of the tigers’ prosperity and security.

在不利方面，威胁甚至更大。在过去的四分之一世纪中，金融危机曾两次重创四小虎国家。智能手机和电脑产业, 对半导体的长期的旺盛需求, 最近也出现了逆转，给韩国和台湾带来了冲击。但现在最让他们担心的是, 地缘政治的挑战:中美之间的“新冷战”, 将动摇四小虎赖以经济繁荣和安全的基础。

Methodologically 方法学;在方法论上, this special report *begs an obvious question*(`=*BEG THE QUESTION* : to make sb want to ask a question that has not yet been answered 令人置疑；引起疑问`). Does it *make sense* to lump(v.)(`=to put or consider different things together in the same group 把…归并一起（或合起来考虑） /（通常为无定形的）块`) the tigers together?

Two are cities; the others decent(`=of a good enough standard or quality 像样的；相当不错的；尚好的`)-sized countries (Taiwan’s population *exceeds* 20m; South Korea’s 50m).

====
- decent =>  -dec-装饰 + -ent形容词词尾, 得体，合适，词源同doctor, dignity.
====
从方法论上来说，这份特别报告, 回避了一个显而易见的问题。把四小虎归在一起来评判,有意义吗? 其中两个只是城市; 而另两个则是中等规模的国家性质(台湾省的人口超过2000万; 韩国人口超过5000万)。


Two *are* sovereign(a.)(`=(of a country or state 国家) free to govern itself; completely independent 有主权的；完全独立的`) members of the United Nations; one *is* a territory(`= land that is under the control of a particular country or ruler 领土；版图；领地`) of China; the other *exists* in a diplomatic netherworld(`=the world of the dead 阴间；冥府；地狱; / If you refer to a place as a netherworld, you mean that it is dangerous and full of poor people and criminals. 贫民和高犯罪区域`).

其中两个是联合国的主权会员国; 一个是中国领土;另一个处在于外交的阴暗面。(这里原文存疑?? 外交阴暗面明显是指台湾, 但新加坡明显不是中国领土.)
====
- sovereign => sover(super-)上,超过 + reign(-regn-)统治
- netherworld => nether- ‎(“beneath, lower”) +‎ world.
====

Taiwan and South Korea are fierce(`=(尤指动作或情感) showing strong feelings or a lot of activity, often in a way that is violent 狂热的；强烈的；猛烈的`) democracies; Hong Kong and Singapore *trust* their electorates less. Two still *rely on* manufacturing; two *are* now high-end(a.)(`=expensive and of high quality 高档的；高端的；价高质优的`) service providers 供应商.

台湾和韩国, 是情绪激烈的民主地区和国家; 香港和新加坡对选民的信任度较低。四小虎中, 其中两个仍然在依赖制造业; 另外两家如今则是高端服务的提供商。

Yet for all these differences, there is much *they have in common*.

They are among the world’s most open trading economies, with all the volatility 挥发性的；不稳定的；反覆无常的;易变 that *implies*(`=to suggest that sth is true or that you feel or think sth, without saying so directly 含有…的意思；暗示；暗指`).

They *have [nonetheless(`= despite this fact 尽管如此`)] maintained* high rates of employment and thrift(n.)节约；节俭, *even as* their living standards *have improved*.

然而，尽管存在这些差异，它们仍有许多共同之处。它们是世界上最开放的贸易经济体之一，其面临的经济政治等波动性不言而喻。尽管他们的生活水平提高了，但他们仍然保持了高就业率和高储蓄率。


They *are, to varying degrees 在不同程度上, caught*(`=to take hold of sb/sth 抓住；握住 /逮住；捕捉；捕获`) between China and America.

And all four *are faced with* complex social problems that *stem from* their remarkable growth over the past half-century.

The four tigers *have achieved* prosperity [*without complacency*](n.)(`=a feeling of satisfaction with yourself or with a situation, so that you do not think any change is necessary; the state of being complacent 自满；自得；自鸣得意`), wealth [without repose](n.)(`=a state of rest, sleep or feeling calm 休息；睡眠；平静；镇静`).

Their efforts to remain in front *are not guaranteed*(a.)肯定的; 保证的 to be successful. But they are guaranteed(a.) to be fascinating(`=extremely interesting and attractive 极有吸引力的；迷人的`).

====
- repose => 来自拉丁语 repausare,停下休息，来自 re-,表强调， pausare,停下，暂停，词源同 pause.
====
他们在不同程度上, 夹在中国和美国之间。这四个国家都面临着复杂的社会问题，这些问题源于它们在过去半个世纪的显著增长所伴随而来的。但“四小虎”经济繁荣而不自满，获得了富裕而不停下脚步。他们保持领先地位的努力不一定会成功, 但它们的努力肯定会很吸引人。

---

== 03. After half a century of success, the Asian tigers must reinvent themselves 纯净版

Special report: Asian tigers

Asian tigers

After half a century of success, the Asian tigers *must reinvent themselves*

They *must move from* growth-obsessed developmental states, *to* growth-friendly welfare states, say Simon Rabinovitch and Simon Cox



Dec 5th 2019

THE FOUR Asian tigers—Hong Kong, Singapore, South Korea and Taiwan—once *fascinated* the economic world. *From* the early 1960s *until* the 1990s, they *regularly achieved* double-digit growth. `主` A generation (that *had toiled as* farmers and labourers) `谓` *watched* their grandchildren *become* some of the most educated people on the planet. The tigers *started by* making cotton shirts, plastic flowers and black wigs. Before long, they *were producing* memory chips, laptops and equity derivatives. [In the process] they also *spawned a boisterous academic debate* about the source of their success. Some *attributed* it *to* the anvil of government direction; others *to* the furnace of competitive markets.

Then the world *turned away*. The Asian financial crisis *destroyed* their mystique. China *became* the new development star, even if, to a certain extent, it *followed* their lead. The tigers themselves *seemed to* lose their stride. [This year] America *is* on track *to grow more quickly than* all four of them.

They all *have* seemingly intractable problems: stagnant wages in Taiwan, the dominance of big business in South Korea, an underclass of cheap imported workers in Singapore and, most explosive, a government in Hong Kong that *will not, or cannot, listen to* its people.

But *it* is a mistake *to write off* the tigers. A closer look at their economic record *shows that*, *contrary to* the gloom that sometimes *pervades* them, they *have much to boast about*. The trajectory of their GDP per person, *calculated* [at *purchasing-power parity*], *has remained* impressive (see chart). They *blew past* the supposed middle-income trap long ago. And South Korea *will soon become* the fourth tiger *to overtake Japan*, its former imperial ruler and economic mentor.



They *have also gained ground on* America. Singapore *passed it* in the 1990s; Hong Kong *drew level* in 2013; and the other two *have narrowed the gap*. Indeed, in the past five years (2013-18), the GDP per person of Singapore and Hong Kong *has grown faster than* every country above them in the income rankings. With a couple of exceptions, the same is true of Taiwan and South Korea.

In their economic maturity, the tigers merit *renewed attention*. They *face* many of the same issues that *bedevil* the West: *how to mitigate* inequality; *how to gin up* productivity; *how to cope with* ageing; and *how to strike a balance* between America and China. They *do not have* all the answers, but they *do have* novel, albeit sometimes foolish, approaches(n.) that *are* in themselves instructive.

Little dragons

This special report *will examine* the changing nature of the tigers’ economies /and *make four big claims*. The first *is that* many of the tigers’ problems *result from* economic success, not failure. They *have defended their global export share* for years, despite steady increases in labour and land costs. Now, though, they *will struggle to expand their exports faster than* global demand itself. They *have also reached* the technological frontier in many industries. That *makes* further improvement *harder*: they *are no longer catching up with* global best practices but *trying to reinvent* them.

Lee Kuan Yew, Singapore’s founding father, once *claimed that* harmony and stability *are* chief among “Asian values”. The tigers *still cherish these things* (who doesn’t?), but many of their citizens *see* fairness *as* a precondition for both. That observation *leads to* this report’s second big claim: when a sophisticated citizenry *aspires to* democracy, frustrating that aspiration *can be imprudent* as well as unjust. Some *argue that* the blustery politics of Taiwan and South Korea -- *complete with* high-profile corruption cases, parliamentary fisticuffs and fiercely partisan media - *have hindered* their growth. But a proper examination of the tigers’ record *does not support* that argument. Instead, `主` what *has become clear* in Hong Kong `系` *is that* a lack of democracy *is* a grave liability, *sowing* dissatisfaction and mistrust.

Third, the tigers’ thin welfare states *have also become* a hindrance. Their leaders *have traditionally worried that* redistribution and social spending *would sap their populations’ motivation* to work. But social insecurity *instead risks* sapping(v.) their populations’ willingness *to embrace* technological change. As the tigers’ populations *get older*, their governments *also face* more pressure *to spend on* pensions and health care. And they *need to alleviate the economic burdens* that *dissuade* young people *from* having children. The tigers’ growth-obsessed “developmental states” *must, in short, become* growth-friendly welfare states.

Finally, the tigers *are important* as economic bellwethers for the rest of the world. They *are unusually exposed to* deep global cycles: in technology, finance and geopolitics. The manufacturing tigers *have dominated* narrow slices of the technological supply chain, *focusing on* techniques and chips that *are vital for* high-speed 5G telecoms networks and “big-data” processing. Hong Kong and Singapore, meanwhile, *have positioned themselves as* financial bridges between China and the world, *making them highly sensitive both to* China’s success *and* its stumbles. And all four of the tigers *depend on* the maintenance of geopolitical calm [as America, the incumbent superpower, *adjusts to* a new rival].

These cycles *can be difficult to manage* -- even in an upswing. Booms in finance and technology *can concentrate wealth in* a few hands, such as South Korea’s chaebol chipmakers or Hong Kong’s property tycoons. On the downside, the threats *are even greater*. Twice [in the past quarter-century] the tigers *have been rocked by* financial crises. The long boom in demand for semiconductors in smartphones and computers *has recently turned*, *hurting* South Korea and Taiwan. But it is the geopolitical challenge *that most worries(v.) them now*: a “new cold war” between China and America *would shake the foundations* of the tigers’ prosperity and security.

Methodologically, this special report *begs an obvious question*. *Does it make sense* to lump(v.) the tigers together? Two are cities; the others decent-sized countries (Taiwan’s population *exceeds* 20m; South Korea’s 50m). Two *are* sovereign members of the United Nations; one is a territory of China; the other *exists* in a diplomatic netherworld. Taiwan and South Korea are fierce democracies; Hong Kong and Singapore *trust* their electorates *less*. Two *still rely on* manufacturing; two *are* now high-end service providers.

Yet for all these differences, there is much *they have in common*. They are among the world’s most open trading economies, with all the volatility that implies. They *have nonetheless maintained* high rates of employment and thrift, *even as* their living standards *have improved*. They *are, to varying degrees, caught* between China and America. And all four *are faced with* complex social problems that *stem from* their remarkable growth over the past half-century. The four tigers *have achieved* prosperity [without complacency], wealth [without repose]. Their efforts to remain in front *are not guaranteed to be successful*. But they *are guaranteed to be* fascinating.

---


== 04. It has become harder for the Asian tigers to prosper through exports

*It* has become harder for the Asian tigers *to prosper(v.) [through exports]*

The trade war *has not helped*, either （两者中的）任何一个

亚洲四小龙想通过出口实现繁荣, 变得更加困难 +
贸易战对帮助也无济于事

Dec 5th 2019

BONNIE TU *IS laughing*. She just *discovered* the crisp(`=(of paper or cloth 纸张或布料) fresh and clean; new and slightly stiff without any folds in it 洁净的；挺括的`) red “*Make* America *Great Again*” hat that a colleague 同事；同僚 *left* on her desk as a joke.

邦妮笑了。她刚刚发现了一顶挺括的红色帽子，上面写着“让美国再次伟大起来”，那是一位同事作为玩笑留在她桌上的。

The chairwoman(`=a woman in charge of a meeting, a committee or an organization （会议、委员会或机构的）女主席，女主持人，女会长，女董事长`) of Giant, the world’s biggest bike manufacturer, *is* no fan of Donald Trump.

His 指特朗普 tariffs 关税 *have messed(`=to make sth dirty or untidy 使不整洁；弄脏；弄乱 / with sb/sth : to get involved with sb/sth that may be harmful 卷入有害的事；与某人有牵连`) with* her supply chains and *driven up*(`=drive sth up/down : to make sth such as prices rise or fall quickly 抬高（或压低）；使上升（或下跌）`) costs.

全球最大的自行车制造商捷安特(Giant)的女董事长, 对唐纳德•特朗普(Donald Trump)并不感冒。他的关税打乱了她的供应链，推高了成本。

“It’s a tax on biking, the healthiest activity in the world,” *bemoans*(`=to complain or say that you are not happy about sth 哀怨；悲叹`) the feisty(a.)(`=strong, determined and not afraid of arguing with people 坚决而据理力争的`) 70-year-old, an avid(`=very enthusiastic about sth (often a hobby) 热衷的；酷爱的`) cyclist(`=a person who rides a bicycle 骑自行车的人`) herself.

In response, Giant *has scaled(`= to change the size of sth 改变…的大小`) back* production in China and *ramped(`=斜坡；坡道`) up*(`=to make sth increase in amount 使…的数量增加`) in Taiwan. “We had no choice,” she says.

“这是对骑自行车的征税，而骑车是世界上最健康的活动，”这位70岁的活跃老人哀叹道，她自己也是一名狂热的自行车爱好者。作为回应，捷安特缩小了在中国大陆的生产规模，增加了在台湾的产量。“我们别无选择，”她说。
====
- bemoan => 前缀be-, 强调。moan, 抱怨，呻吟。
- feisty => 缩写自fysting curre, 臭狗，词源同fart, 拟声词，放屁。后词义褒义化。
- avid =>  av（渴望）+id（形容词后缀）→渴望的 /  avi（鸟、飞）+d（的）→恨不得像鸟一样马上飞过去→渴望的
====

Giant *is not* alone. Scores(`=very many 大量；很多; /a set or group of 20 or approximately 20 20个；约20个`) of Taiwanese companies *have come back recently*, including Compal 仁宝电脑, a computer manufacturer; Delta Electronics, a power-component supplier; and Long Chen, a paper company.

In 2018 the government *launched* the “Invest Taiwan” office, *promising* low-cost 廉价的；价格便宜的 loans(`=money that an organization such as a bank lends and sb borrows 贷款；借款`) *for* companies’ relocation expenses 费用.

It *has already accepted applications* from over 150 firms.

捷安特并非个例。数十家台湾企业最近已重返台湾，包括电脑制造商仁宝电脑(Compal);电力元件供应商达美电子;还有Long Chen，一家纸业公司。在2018年，政府推出了“投资台湾”办公室，承诺为企业的搬迁费用提供低成本贷款。它已经接受了150多家公司的申请。

All this *might make it sound like* Taiwan *has benefited from* the trade war. Singapore and South Korea *have also gained market share* in America [at China’s expense](`=*AT SB'S EXPENSE* : paid for by sb 由某人付钱；由某人负担费用. / *AT THE EXPENSE OF SB/STH* : with loss or damage to sb/sth 在牺牲（或损害）…的情况下`).

But it *would be* a mistake *to conclude 断定；推断出；得出结论 that* the trade war *is good for* the tigers. Overall, it *hurts*.

It *is disrupting* three things *on which* they *intimately(`=very close 密切的；紧密的`) depend*: an open global trading system, their Asia-based production networks and their biggest market, China.

所有这一切听起来, 好像是台湾能从中美贸易战中获益。新加坡和韩国也以牺牲中国为代价, 获得了在美国的市场份额。但如果认为贸易战对四小虎有利，那就错了。总的来说,这会对它们造成伤害。因为贸易战正在扰乱四小虎紧密依赖的三件事: 1.开放的全球贸易体系、2. 他们在亚洲的生产网络, 和 3.他们最大的市场——中国。


Goldman Sachs 高盛投资银行 analysts 分析师 *looked at* how 13 economies in Asia *were faring*(v.)(`=fare :  ~ well, badly, better, etc. : to be successful/unsuccessful in a particular situation 成功（或不成功、更好等）`) relative to their potential this year; the Asian tigers *occupied*(`=to fill or use a space, an area or an amount of time 使用，占用（空间、面积、时间等）`) four of the five bottom slots(`=a position, a time or an opportunity for sb/sth, for example in a list, a programme of events or a series of broadcasts （名单、日程安排或广播节目表中的）位置，时间，机会; / （投放或插入东西的）窄缝，扁口`).

高盛(Goldman Sachs)分析师, 研究了亚洲13个经济体今年相对于其潜力的表现；亚洲四小龙占据了五个垫底位置中的四个。
====
- fare : v. If you say that someone or something *fares well or badly*, you are referring to *the degree of success they achieve in a particular situation or activity*. 进展 +
-> The party *fared(v.) very badly* in the last election. 该党上次竞选情况很糟。 +
->  It is unlikely that the marine industry *will fare(v.) any better* in September.
海运业不大可能在9月份有所好转。

- slot : n. a position, a time or an opportunity for sb/sth, for example in a list, a programme of events or a series of broadcasts （名单、日程安排, 或广播节目表中的）位置，时间，机会 +
-> Their album *has occupied the Number One slot* for the past six weeks. 他们的唱片在最近六周占据排行榜首位。 +
-> the airport's take-off and *landing slots*(n.) 机场的起飞降落时间表 +
-> He *has a regular slot*(n.) on the late-night programme. 他在深夜节目中有一档固定栏目。
====

`主` *That* trade friction 摩擦; 争执,分歧,不和 *should unsettle them* `系` is only natural.

Exports, after all, *have been* at the heart of their post-war success.

South Korea *began with* tinplate(`=a metal material made from iron and steel and covered with a layer of tin 镀锡铁皮；马口铁`), plywood(`=board made by sticking thin layers of wood on top of each other 胶合板；压合板；夹心板`) and textiles 纺织品.

Its exporters *benefited from* cheap credit(`=money that you borrow from a bank; a loan （从银行借的）借款；贷款`), *exemptions(n.)(`=~ (from sth) official permission not to do sth or pay sth that you would normally have to do or pay 免除；豁免`) from* import duties 进口税 and a devaluation 货币贬值 of the won 韩元 in 1964 (ironically, *urged on it* by America).

====
- exemption =>  ex-出 + -empt-拿 + -ion名词词尾 → 被拿出,豁免
====
贸易摩擦使他们感到不安, 是很自然的。毕竟，出口一直是他们在二战后成功的核心。韩国的经济起家于生成马口铁、胶合板和纺织品。韩国出口商受益于低息贷款、免除进口关税, 以及1964年韩元的贬值(讽刺的是，这是美国敦促引起的)。


*From* February 1965 *until* his assassination 暗杀，行刺 in 1979, President Park Chung-hee 朴正熙 *attended nearly* 差不多，几乎 every monthly meeting of the country’s export-promotion committee 委员会, *sampling(`= to test, question, etc., part of sth or of a group of people in order to find out what the rest is like 抽样检验；取样；采样`) products* and *rallying*(`=to come together or bring people together in order to help or support sb/sth 召集；集合`) businessmen [over lunch 午餐时间, 在吃中餐的时候].

He *cried* when South Korea’s exports *exceeded* $100m in 1964, *declaring* a national holiday *known as* “export day” (later *renamed* “trade day”).

从1965年2月, 到1979年被暗杀为止，韩国总统朴正熙(Park Chung-hee)几乎参加了韩国出口促进委员会(export-promotion committee)的每一次月度会议，抽样产品，召集商人共进午餐。1964年，当韩国出口额超过1亿美元时，他大声疾呼，宣布了一个名为“出口日”(后更名为“贸易日”)的全国性节日。


Taiwan *also started with* cheap credit 低息贷款 and tax *breaks(`=to show an opening 露出缝隙；散开`) for* exporters. Entrepreneurs soon *emerged*.

Ms Tu *remembers* her uncle, King Liu, founder of Giant, *remarking*(`=to say or write a comment about sth/sb 说起；谈论；评论`) with astonishment(`=a feeling of very great surprise 惊讶；惊异`) in 1972 *that* “Americans *are bringing cash here* to buy bikes”. He soon *found that* local Taiwanese suppliers *were not reliable*: rubber tyres *had a habit of* falling off rims. So Mr Liu *travelled around* the island *to persuade* other manufacturers *that* they *would all fare better* if they *adhered to*(`=to stick firmly to sth 黏附；附着; /坚持，遵守，遵循（法律、规章、指示、信念等）`) the same dimensions(`=a measurement in space, for example the height, width or length of sth 维（构成空间的因素）；尺寸`).

捷安特的女董事长 Ms Tu, 还记得，她的叔叔、捷安特(Giant)创始人 King Liu (刘金标)在1972年曾惊讶地表示，“美国人把现金带到这里来买自行车”。但他很快发现，台湾本地的供应商并不可靠: 橡胶轮胎有从轮辋上脱落的习惯。因此，刘跑遍了台湾，说服其它制造商，如果它们坚持同样的尺寸，它们的表现都会更好。

Singapore and Hong Kong *are often seen as* entrepots(`=a port or other place where goods are brought for import and export 转口港；转运口岸`). But they, too, *were* once exemplars(`=a person or thing that is a good or typical example of sth 模范；榜样；典型；范例`) of labour-intensive 劳动密集型的 manufacturing.

For a time, in the 1970s, Hong Kong was the world’s biggest toy producer. When Singapore became independent in 1965, it *pitched(`=用力扔；投；抛; / ~ sth (at sb) /~ sth (as sth) : to aim or direct a product or service at a particular group of people （使产品或服务）针对，面向；确定销售对象（或目标市场）`) itself as* a base of production.

Rivalry(n.)竞争；竞赛；较量 with Hong Kong *was* there [from the outset(`=at/from the beginning of sth 从开始`)]: one of Singapore’s first big catches(`=catch : a person that other people see as a good person to marry, employ, etc. 理想的对象；意中人；雇用的好对象；看中的人`) was GE, which *chose to set up* a clock-radio 自动定时开关收音机；收音机闹钟 factory in the city-state, *worried that* the violence of China’s Cultural Revolution *might spill(`=spill over (into sth) : to fill a container and go over the edge 溢出；漫出`) over to* Hong Kong.

新加坡和香港, 通常被视为转口港。但它们也曾是劳动密集型制造业的典范。上世纪70年代，香港曾一度是全球最大的玩具生产商。1965年新加坡独立时，将自己定位为生产基地。它与香港的竞争从一开始就存在: 新加坡的第一批大型收购对象之一是通用电气(GE)，它选择在这个城市型国家,建立一家闹钟收音机工厂，因为担心中国文化大革命的暴力可能会蔓延到香港。

*Even as* the tigers *have grown far wealthier*, exports *have remained* part of their DNA. Their companies *became more sophisticated* over time, *prodded(`=~ sb (into sth/into doing sth) : to try to make sb do sth, especially when they are unwilling 催促；督促；鼓动 /戳；杵；捅`) by* their governments (which *were themselves often prodded by* ambitious industrialists).

In South Korea, after a decade of success in light industry, officials *promoted* heavier industries, such as shipbuilding and chemicals.

Taiwan *created* science parks *for* advanced industries *from* optoelectronics 光电子学 *to* semiconductors 半导体.

Singapore *established* a National Computer Board(`= a group of people who have power to make decisions and control a company or other organization （公司或其他机构的）董事会，委员会，理事会`) in 1981 *to train* high-tech workers.

即使四小虎国家变得更加富有，出口仍然是他们经济发展DNA的一部分。随着时间的推移，他们的公司在政府的推动下变得更加成熟(政府本身也经常受到雄心勃勃的实业家的推动)。在韩国，在轻工业取得了10年的成功后，官员们推动了造船和化工等重工业的发展。台湾, 对从光电子到半导体等的先进产业, 它都为其创建了科技园。新加坡在1981年建立了一个国家计算机委员会, 来培训高科技工人。


Much of the world *has lost ground 土地 to*(`=*give/lose ground (to sb/sth)* : to allow sb to have an advantage; to lose an advantage for yourself 退让；让步；失利`) China over the past 20 years.

Yet the tigers’ share of global merchandise(`= goods that are bought or sold; goods that are for sale in a shop/store 商品；货品`) exports *has been steady* at 10% (see chart).

Japan, their erstwhile(`=former; that until recently was the type of person or thing described but is not any more 以前的；先前的；过去的；往昔的`) mentor(`=an experienced person who advises and helps sb with less experience over a period of time 导师；顾问`), *has seen* its share *fall to* less than 4%, half *what it was* in 2000.

在过去的20年里，世界大部分地区在经济发展上都输给了中国。然而，四小虎全球商品出口中的份额, 一直稳定在10%(见图表)。而他们曾经的导师日本的份额, 已经下降到不到4%，只有2000年的一半。
====
- erstwhile => erst, 最早的，ere最高级。
- mentor => 来自希腊语Mentor,导师，指导者，来自PIE men,思考，思想，*词源同 mind*, mania.来自荷马史诗《奥德赛》，雅典娜化身Mentor指导奥德赛儿子学习和思考，后词义通用化。
====

Like other wealthy economies, they *have shifted* much of their basic manufacturing 制造业 *to* China. Most emblematic(`=that represents or is a symbol of sth 标志的；象征（性）的`) *is* Foxconn, a Taiwanese electronics company *known now as* the main assembler(`=a person who assembles a machine or its parts 装配工`) of iPhones.

====
- emblem => em-, 进入，使。-bl, 扔，掷，镶嵌，词源同ballistic, problem, symbol.
====

It *opened its first plant* in China in 1988; 30 years later it *employs roughly* 1m people there.

But as they *offloaded*(`=~ sth/sb (on/onto sb) to get rid of sth/sb that you do not need or want by passing it/them to sb else 把（担子等）转移（给别人）；减轻（负担）；卸（包袱）`) low-end work *to* China, the tigers *moved upstream*(ad.)(`= ~ (of/from sth) along a river, in the opposite direction to the way in which the water flows 向（或在）上游；逆流`).

与其他富裕经济体一样，它们也将大部分基础制造业转移到了中国。最具象征意义的是富士康(Foxconn)，这家台湾电子公司, 如今被认为是iphone的主要组装商。1988年，它在中国开设了第一家工厂; 30年后，它在那里雇佣了大约100万名员工。但是，当它们(四小虎)把低端工作转移到中国时，这些“小虎”即开始向上游转移。

South Korea is the world’s biggest maker of memory chips. Taiwan *has the biggest capacity* for *fabricating*(`=to make or produce goods, equipment, etc. from various different materials 制造；装配；组装`) semiconductors.

As a result, they each *account for* more than 12% of China’s final demand for electronic and computer products, *twice as much as* any other trade partner. They *are, put simply 简而言之, making things* that China cannot.

韩国是世界上最大的存储芯片制造商。台湾拥有最大的半导体制造能力。因此，它们各自占中国电子和电脑产品最终需求的12%以上，是其他贸易伙伴的两倍。简单地说，他们正在制造中国无法制造的东西。

They *have also ridden 骑马;搭乘；乘坐 on* China’s coat-tails （男人上衣的）后摆. As firms *have clustered together* in China, Asia as a whole *has become* a more powerful manufacturing region.

Asia’s share of the global trade (in parts and components 零部件) *rose from 19% to 30%* between 2000 and 2016. Mainland China *is home to* four of the world’s seven busiest container ports 货柜港口，集装箱货港; the others are in Singapore, Busan 釜山 and Hong Kong.

他们还搭上了中国的顺风车。随着企业在中国的聚集，整个亚洲已成为一个更强大的制造业地区。从2000年到2016年，亚洲在全球零部件贸易中的份额, 从19%上升到30%。中国大陆拥有全球7个最繁忙的集装箱港口中的4个;其余的分别在新加坡、釜山和香港。


Both Singapore and Hong Kong *have strengthened(`=to become stronger; to make sb/sth stronger 加强；增强；巩固`) their roles as* the management hubs of “Factory Asia”.

More than 4,000 companies *have chosen* Singapore *as* a regional headquarters  将（组织的）总部设在某地；设立总部, often *to oversee*  监督；监视 South-East Asia.

Hong Kong has fewer, with roughly 1,500 headquarters, but it *has been far more successful than Singapore* at *luring*(`=lure : to persuade or trick sb to go somewhere or to do sth by promising them a reward 劝诱；引诱；诱惑`) Chinese companies *to* its stock exchange. Its stockmarket *is worth(a.)(`=having a value in money, etc. 有…价值；值…钱`) more than* $4trn; Singapore’s *is closer to* $700bn.

新加坡和香, 港都加强了自己作为“亚洲工厂”管理中心的角色。超过4000家公司选择新加坡作为地区总部，通常负责监督东南亚地区。香港的总部企业较少，只有大约1500家总部，但在吸引中国企业到港上市方面，香港比新加坡成功得多。它的股票市场价值超过4万亿美元; 新加坡只接近7000亿美元。

All these connections, however enriching(`=to make sb/sth rich or richer 使富有；使富裕`), *create* vulnerabilities(`=vulnerability : 易损性；弱点`).

America’s trade war *is intended to inflict(`= to make sb/sth suffer sth unpleasant 使遭受打击；使吃苦头`) pain on* China. But the tigers *are, in many ways, more exposed to* the damage because they are smaller and more open.

In China, exports *are worth about* 20% of GDP. In South Korea it is more like 45%; in Taiwan, 65%; and in Singapore and Hong Kong, closer to 200%.

所有这些联系，无论给它们带来多少财富，同时也都会造成脆弱性。美国的贸易战, 旨在给中国带来痛苦。但在很多方面，四小虎们更容易受到伤害，因为它们体型更小，对外贸易的开放度更高。在中国，出口约占GDP的20%。在韩国，这个比例更接近45%; 在台湾, 是65%; 而在新加坡和香港，则高达接近200%。


In *tearing* supply chains *asunder*(ad.)(`= into pieces; apart 碎；散`), Mr Trump’s tactics 策略；手段；招数 *pose(`=to create a threat, problem, etc. that has to be dealt with 造成（威胁、问题等）；引起；产生`) a particular danger to* the tigers’ cosmopolitan(a.)(`=containing people of different types or from different countries, and influenced by their culture 世界性的；全球各国的；有各国人的；受各国文化影响的`) model of manufacturing.

====
- asunder => a（处于…状态）+sunder（分离的）→分离的. 来自短语on sunder . sunder, 分开，来自词根sue, 自己的，同self. /趣味记忆：sunder →谐音thunder（打雷）→用雷劈成碎片
====

They *remain highly dependent on* inputs from other countries. They also *serve* an ecumenical(`=involving or uniting members of different branches of the Christian Church 基督宗教合一的；大公的; 普遍的；世界范围的`) range of clients, *including* some whom the Americans *distrust*.

Taiwanese foundries(`=foundry : a factory where metal or glass is melted and made into different shapes or objects 铸造厂；玻璃厂`) *produce* chips *for* top American firms but also *for* Huawei, the Chinese telecoms giant that Americans *accuse of* spying. “We are everyone’s foundry. We *exclude* no one,” says an official at TSMC(`=台湾积体电路制造股份有限公司 Taiwan Semiconductor Manufacturing Company`).

在撕裂供应链的过程中，特朗普的策略, 也对“四小虎”的全球制造业模式构成了特别危险。它们仍然高度依赖其他国家的投入。他们也服务于一些普通的客户，包括一些美国人不信任的客户。台湾的芯片制造商不仅为美国的顶级公司生产芯片，也为被美国人指控从事间谍活动的中国电信巨头华为生产芯片。“我们是为每个客户服务的铸造厂。我们不排除任何客户，”台积电一位官员表示。


*Faced with* all the uncertainty, the tigers *have a couple of options*. One *is* to diversify(v.)(`=~ (sth) (into sth) ( especially of a business or company 尤指企业或公司 ) to develop a wider range of products, interests, skills, etc. in order to be more successful or reduce risk 增加…的品种；从事多种经营；扩大业务范围;（使）多样化`) their customers and their products.

Taiwan *has long pushed* its companies *to explore* emerging markets other than China.

South Korea’s government *is keen to promote* a wider range of products. On the most recent “trade day”, President Moon Jae-in 文在寅 of South Korea *applauded* new industries *such as* electrical vehicles and robots.

面对所有的不确定性，四小虎有两个选择。一是使他们的客户和产品多样化。台湾长期以来一直在推动台湾企业探索中国大陆以外的新兴市场。韩国政府热衷于推广更广泛的产品。在最近的“贸易日”，韩国总统文在寅(Moon Jae-in)称赞了电动汽车和机器人等新产业。

Another response *is* to try to *patch up*(`=to repair sth especially in a temporary way by adding a new piece of material or a patch 修理；（尤指）临时修补`) the global trading order.

Before 2000 the tigers *were party to* 参与 just five regional trade agreements; they *have since joined* 49 more. Singapore was an originator 创始人; 发明者; 提出者 of both the Trans-Pacific Partnership (a trade deal that once *aimed to join* America, Japan and ten other Pacific-Rim countries) and its supposed(`=used to show that you think that a claim, statement or way of describing sb/sth is not true or correct, although it is generally believed to be 误以为的；误信的；所谓的`) rival, the Regional Comprehensive(`=including all, or almost all, the items, details, facts, information, etc., that may be concerned 全部的；所有的；（几乎）无所不包的；详尽的`) Economic Partnership, which *includes* China.

It is also among the countries *working to broker(v.)(`=to arrange the details of an agreement, especially between different countries 安排，协商（协议的细节，尤指在两国间）`) a compromise between* China *and* America that *will keep* the World Trade Organisation *functioning*.

====
- broker => 在古代欧洲的酒吧或其他零售酒水的地方，卖酒的小贩会批发采购一桶一桶的啤酒或其他酒类，然后打开酒桶，装上龙头，然后一杯一杯地卖给喝酒的人。打开酒桶的工具在法语中叫broche，后来演变为英语单词Broach（钻头、凿子）。 +
而表示“打开酒桶”的动词brochier 则辗转演变成英语中的broker，其字面意思就是“打开酒桶的人”，原本用来表示零售酒水的小贩，后来泛指各种经销商。在金融行业中，则表示经纪人、掮客。虽然中文叫法不同，但其实都是经销商、中间人的意思。经纪人其实就是把股票、证券等金融产品贩卖给个体投资者的中间人。  +
broker： ['brəʊkə] n.经纪人，中间人，掮客v.以中间人身份来谈判、安排 broach： [brəʊtʃ] n.钻头，凿子，胸针vt.提出，给……钻孔、开口，开始讨论
====

另一种应对措施, 是试图修补全球贸易秩序。在2000年之前，四小虎只是5个区域贸易协定的缔约方；自那以后，它们已经加入了另外49个协定。新加坡既是《跨太平洋伙伴关系协定》(Trans-Pacific Partnership，简称tpp)(一项曾经旨在加入美国、日本和其他十个环太平洋国家的贸易协定)的发起人，同时也是其所谓的竞争对手《区域全面经济伙伴关系协定》(Regional Comprehensive Economic Partnership，简称rcep)的发起国。区域全面经济伙伴关系协定, 包括中国。它也是努力促成中美两国达成妥协的国家之一，这将使世界贸易组织(WTO)保持运转。


But the tigers *have little ability to dodge*(`=to move quickly and suddenly to one side in order to avoid sb/sth 闪开；躲开；避开`) a full Sino-American clash. Hong Kong is most at risk.

Its distinctiveness 特殊性；区别性；辨别性 *is recognised*(`=to accept and approve of sb/sth officially （正式）认可，接受，赞成`) in American law, which *treats it as* a separate customs  海关；关税 territory *from* the rest of China. That *means* it is a non-combatant （军队中的）非战斗人员;（战争时期的）平民，非军事人员 in the trade war.

But some companies *appear* to be exploiting(v.)(`=to treat a person or situation as an opportunity to gain an advantage for yourself 利用（…为自己谋利）`) this, *routing(`=to send sb/sth by a particular route 按某路线发送`) goods* through Hong Kong middlemen(`= A middleman is a person or company which buys things from the people who produce them and sells them to the people who want to buy them. 中间商`) *to lower the tariffs* 关税 they face.

America *might yet tighten* its scrutiny(n.)(`= careful and thorough examination 仔细检查；认真彻底的审查`) of goods from the city.

====
- dodge => 可能来自dodder, 摇摆，蹒跚，引申词义摇摇晃晃的闪开。
====
但是小虎国家几乎没有能力回避中美之间的全面冲突。香港面临的风险最大。它的独特性, 是在美国法律中得到了承认的，美国法律将其视为与中国其他地区分离的关税地区。这意味着它是贸易战中的非战斗人员。但一些公司似乎正在利用这一点，通过香港的中间商,来降低它们面临的关税。美国可能还会加强对香港的商品的审查。



Problems in Asia *can also be* home-grown(a.)(`=made, trained or educated in your own country, town, etc. 本国（或本地）制造的（或培养的、教育的）`). A political dispute between South Korea and Japan, *rooted in* Japan’s occupation of South Korea in the first half of the 20th century, *has morphed(`=（使）变形（利用电脑动画制作使图像平稳变换） /to change, or make sb/sth change into sth different （使）变化；（使）改变`) into* a 21st-century trade squall(`=a sudden strong and violent wind, often during rain or snow storms 飑（常指暴风雨或暴风雪中突起的狂风）`).

Japan *has restricted sales to* South Korea of materials *vital for* making semiconductor chips. The global division(`=the process or result of dividing into separate parts; the process or result of dividing sth or sharing it out 分开；分隔；分配；（分出来的）部分`) of labour *is [so] finely sliced* [that] it is difficult for South Korean chipmakers *to find* close substitutes  代替者；代替物；代用品.

亚洲的问题也可能是本土产生的。而韩国和日本之间的政治争端，则根源于日本在20世纪上半叶对韩国的占领，如今已演变为一场21世纪的贸易风暴。日本已限制向韩国出售那些对制造半导体芯片至关重要的材料。全球分工已经如此细化，以至于韩国芯片制造商很难找到相近的替代品。

The upshot(`=the final result of a series of events 最后结果；结局`) of all the turmoil(n.)(`=a state of great anxiety and confusion 动乱；骚动；混乱；焦虑`) *is that* it is getting harder for companies to know {where *to operate*(`=to work in a particular way or from a particular place （以某方式或从某地方）经营，营业`) and *with whom to trade*}.

At Giant Ms Tu’s conclusion *is that* companies *need to stick to* what they can control. “We *have to focus on* efficiency and automation,” she says. That quest(n.) for efficiency *is shared* [across the tigers]. Automation *is* one way to achieve it. But there are others.

====
- turmoil => 词源不详，可能改写自中古法语 tremouille,磨坊漏斗，可能来自 turn,转动，mill,石磨。
====
所有这些混乱的结果是，企业越来越不知道在哪里经营，与谁交易。在捷安特，女董事得出的结论是，企业需要坚持它们所能控制的。“我们必须关注效率和自动化，”她表示。整个小虎国家都在追求效率。自动化是实现它的一种方式。但还有其他的。 (这个回答很答非所问, 并没有解决 "where to operate /and with whom to trade" 的问题.)


---

== 04. It has become harder for the Asian tigers to prosper through exports 纯净版

The trade war has not helped, either



Dec 5th 2019

BONNIE TU *IS laughing*. She just *discovered* the crisp red “Make America Great Again” hat that a colleague *left* on her desk as a joke. The chairwoman of Giant, the world’s biggest bike manufacturer, *is* no fan of Donald Trump. His tariffs *have messed with* her supply chains and *driven up costs*. “It’s a tax on biking, the healthiest activity in the world,” *bemoans* the feisty 70-year-old, an avid cyclist herself. In response, Giant *has scaled back* production in China and *ramped up* in Taiwan. “We had no choice,” she says.

Giant *is not* alone. Scores of Taiwanese companies *have come back* recently, including Compal, a computer manufacturer; Delta Electronics, a power-component supplier; and Long Chen, a paper company. In 2018 the government *launched* the “Invest Taiwan” office, *promising low-cost loans for* companies’ relocation expenses. It *has already accepted applications* from over 150 firms.

All this *might make it sound like* Taiwan *has benefited from* the trade war. Singapore and South Korea *have also gained market share* in America at China’s expense. But it *would be* a mistake *to conclude that* the trade war *is good for* the tigers. Overall, it *hurts*. It *is disrupting* three things *on which* they *intimately depend*: an open global trading system, their Asia-based production networks and their biggest market, China. Goldman Sachs analysts *looked at* how 13 economies in Asia *were faring* relative to their potential this year; the Asian tigers *occupied* four of the five bottom slots.

`主` *That* trade friction *should unsettle* them `系` *is* only natural. Exports, after all, *have been* at the heart of their post-war success. South Korea *began with* tinplate, plywood and textiles. Its exporters *benefited from* cheap credit, exemptions from import duties and a devaluation of the won in 1964 (ironically, *urged on it* by America). From February 1965 until his assassination in 1979, President Park Chung-hee *attended* nearly every monthly meeting of the country’s export-promotion committee, *sampling products* and *rallying businessmen* over lunch. He *cried* when South Korea’s exports *exceeded $100m* in 1964, *declaring* a national holiday *known as* “export day” (later *renamed* “trade day”).

Taiwan also *started with* cheap credit and tax breaks for exporters. Entrepreneurs soon *emerged*. Ms Tu *remembers* her uncle, King Liu, founder of Giant, *remarking with astonishment* in 1972 *that* “Americans *are bringing cash here* to buy bikes”. He soon *found that* local Taiwanese suppliers *were not reliable*: rubber tyres *had a habit of* falling off rims. So Mr Liu *travelled around* the island *to persuade* other manufacturers *that* they *would all fare better* if they *adhered to* the same dimensions.

Singapore and Hong Kong *are often seen as* entrepots. But they, too, *were once exemplars of* labour-intensive manufacturing. For a time, in the 1970s, Hong Kong was the world’s biggest toy producer. When Singapore *became independent* in 1965, it *pitched itself as* a base of production. Rivalry with Hong Kong *was* there [from the outset]: one of Singapore’s first big catches *was* GE, which *chose to set up a clock-radio factory* in the city-state, *worried that* the violence of China’s Cultural Revolution *might spill over to* Hong Kong.

Even as the tigers *have grown far wealthier*, exports *have remained* part of their DNA. Their companies *became more sophisticated* over time, *prodded by* their governments (which *were themselves often prodded by* ambitious industrialists). In South Korea, after a decade of success in light industry, officials *promoted* heavier industries, such as shipbuilding and chemicals. Taiwan *created* science parks *for* advanced industries *from* optoelectronics *to* semiconductors. Singapore *established* a National Computer Board in 1981 *to train* high-tech workers.

Much of the world *has lost ground to China* over the past 20 years. Yet the tigers’ share of global merchandise exports *has been steady at 10%* (see chart). Japan, their erstwhile mentor, *has seen* its share *fall to* less than 4%, half what it was in 2000.



Like other wealthy economies, they *have shifted* much of their basic manufacturing *to* China. Most emblematic is Foxconn, a Taiwanese electronics company *known now as* the main assembler of iPhones. It *opened its first plant* in China in 1988; 30 years later it *employs* roughly 1m people there. But as they *offloaded* low-end work *to* China, the tigers *moved upstream*. South Korea is the world’s biggest maker of memory chips. Taiwan *has the biggest capacity* for *fabricating* semiconductors. As a result, they each *account for* more than 12% of China’s final demand for electronic and computer products, *twice as much as* any other trade partner. They *are, put simply, making things* that China *cannot*.

They *have also ridden on China’s coat-tails*. *As* firms *have clustered together* in China, Asia as a whole *has become* a more powerful manufacturing region. Asia’s share of the global trade in parts and components *rose from 19% to 30%* between 2000 and 2016. Mainland China *is* home to four of the world’s seven busiest container ports; the others *are* in Singapore, Busan and Hong Kong.

Both Singapore and Hong Kong *have strengthened their roles as* the management hubs of “Factory Asia”. More than 4,000 companies *have chosen* Singapore *as* a regional headquarters, often *to oversee* South-East Asia. Hong Kong *has fewer*, with roughly 1,500 headquarters, but it *has been far more successful than* Singapore *at luring* Chinese companies *to* its stock exchange. Its stockmarket *is worth* more than $4trn; Singapore’s *is closer to* $700bn.

All these connections, however *enriching*, *create* vulnerabilities. America’s trade war *is intended to inflict pain on* China. But the tigers *are, in many ways, more exposed to* the damage because they are smaller and more open. In China, exports *are worth about* 20% of GDP. In South Korea it is more like 45%; in Taiwan, 65%; and in Singapore and Hong Kong, *closer to* 200%.

In *tearing* supply chains [*asunder*], Mr Trump’s tactics *pose a particular danger to* the tigers’ cosmopolitan model of manufacturing. They *remain* highly dependent on inputs(n.) from other countries. They also *serve* an ecumenical range of clients, *including* some whom the Americans *distrust*. Taiwanese foundries *produce* chips *for* top American firms but also *for* Huawei, the Chinese telecoms giant that Americans *accuse of* spying. “We are everyone’s foundry. We *exclude* no one,” says an official at TSMC.

*Faced with* all the uncertainty, the tigers *have a couple of options*. One *is* to diversify their customers and their products. Taiwan *has long pushed its companies to explore* emerging markets other than China. South Korea’s government *is keen to promote a wider range of products*. On the most recent “trade day”, President Moon Jae-in of South Korea *applauded* new industries *such as* electrical vehicles and robots.

Another response *is* to try to *patch up* the global trading order. Before 2000 the tigers *were party to* just five regional trade agreements; they *have since joined* 49 more. Singapore was an originator of both the Trans-Pacific Partnership (a trade deal that once *aimed to join* America, Japan and ten other Pacific-Rim countries) and its supposed rival, the Regional Comprehensive Economic Partnership, which *includes* China. It is also among the countries *working to broker a compromise* between China and America that *will keep* the World Trade Organisation *functioning*.

But the tigers have little ability *to dodge* a full Sino-American clash. Hong Kong is most at risk. Its distinctiveness *is recognised* in American law, which *treats it as* a separate customs territory from the rest of China. That *means* it is a non-combatant in the trade war. But some companies appear to be exploiting this, *routing* goods *through* Hong Kong middlemen *to lower the tariffs* they face. America *might yet tighten its scrutiny of* goods from the city.

Problems in Asia *can also be* home-grown. A political dispute between South Korea and Japan, rooted in Japan’s occupation of South Korea in the first half of the 20th century, *has morphed into* a 21st-century trade squall. Japan *has restricted* sales(n.) to South Korea of materials *vital for* making semiconductor chips. The global division of labour *is [so] finely sliced* [that] it is difficult for South Korean chipmakers *to find* close substitutes.

The upshot of all the turmoil *is that* it is getting harder for companies to know *where to operate* and *with whom to trade*. At Giant Ms Tu’s conclusion *is that* companies need to stick to what they can control. “We *have to focus on* efficiency and automation,” she says. That quest for efficiency *is shared* across the tigers. Automation *is* one way *to achieve it*. But there *are* others.


---



