= 0420
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 420: Workplace Safety.
This is English as a Second Language Podcast episode 420. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. The Learning Guides contain all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension checks, and a complete transcript of everything we say on this episode.
This episode is called “Workplace Safety.” It’s a dialogue between Lon and Abigail. They’re going to be using vocabulary related to accidents at work (where you have your job). Let’s get started.
[start of dialogue]
Lon: What’s this?
Abigail: It’s a memo about a safety inspection scheduled for next week.
Lon: A safety inspection? How are we ever going to pass a safety inspection?
Abigail: What do you mean? This isn’t an unsafe workplace. We’ve had a good record. None of our employees have had on-the-job injuries this year and we’ve never had a fatality. I don’t understand why you’re so worried.
Lon: From what I’ve heard, the inspectors don’t just look at injury rates. They look for the smallest hazard that may be remotely dangerous. If we get cited, we may be shut down.
Abigail: With all due respect, I don’t think that’s how it works. Yes, the inspector will look at our work environment and our gear and machinery to make sure there are no hazards or toxic substances.
Lon: That’s what I’m worried about.
Abigail: But, if they find a violation, we’ll get a chance to fix the problem. They won’t shut us down without giving us a chance to comply with their safety standards.
Lon: I sure hope you’re right.
Abigail: Me, too. We’ll know after next week’s inspection.
[end of dialogue]
Here in the United States the state and federal government have a lot of laws to protect workers to prevent them from having injuries (to prevent them from hurting themselves) while they are working. The federal government has an entire agency called the Occupational Safety and Health Administration that is responsible for many of these laws. Individual states also have their own government agencies or organizations.
In our dialogue, Lon asks Abigail, “What’s this (what is this)?” Abigail says, “It’s a memo about a safety inspection scheduled for next week.” A “memo” is short for a memorandum. It’s usually a short, one page, maybe two or three page document that is used in offices to give someone information. Usually it’s used inside a company or inside an organization. This is a memo about safety inspections. A “safety inspection” is when the government agency comes in to where you are working and makes sure that there is nothing dangerous about your workplace (the place you work).
Abigail says that their workplace is not unsafe. Lon is worried, but Abigail says no, “This isn’t an unsafe workplace.” “Unsafe” just means not safe or dangerous. She says, “We’ve had a good record,” meaning a good history of safe environments for people to work. She says, “None of our employees have had on-the-job injuries this year.” The expression “on-the-job” means at work, at the place where they are working. So, none of the employees hurt themselves at work. She also says that we’ve never had a fatality. A “fatality” is a death. We hope that you don’t have any deaths at your workplace! That would be a fatality.
Abigail says, “I don’t understand why you are so worried.” Lon says, “From what I’ve heard, the inspectors (the people who come and look at – inspect your workplace) don’t just look at injury (or mortality) rates.” When you “injure” yourself you hurt yourself, you harm yourself. You may break your arm or somehow hurt your foot; that would be an injury. The “injury rate” would be the number of those injuries every month or every year, or perhaps based on every 100 employees, something like that.
Lon says these inspectors look for the smallest hazard (hazard). A “hazard” is something that is dangerous, something that can physically hurt you. For example, you might have some electrical cords on the floor that you could hurt yourself by tripping over. These would be considered a safety hazard, something that could hurt someone. The inspectors look for safety hazards that would be remotely dangerous. “Remotely,” here, means a little bit, slightly or barely, not very much but just enough: “remotely dangerous.”
Lon says, “If we get cited (cited), we may be shut down.” To be “cited,” here, means to be told officially that you are breaking the law, that you are doing something against the law, to be told that you are breaking a rule. It’s an official declaration – an official statement. Often, they will give you a piece of paper which is called a “citation.” To be “cited” has a couple of different in English, however; take a look at our Learning Guide for some additional explanations.
So, Lon is worried about the safety inspectors citing the company, giving them official notice that they are breaking the law, and that might lead to then being shut down. To “shut something down,” or to “shut down” something is a two-word phrasal verb meaning, in this case, to make the business or the organization close so that it can no longer operate. They would close your business, that would be to shut the business down.
Abigail says, “With all due respect.” That expression, “with all due respect,” is used when you want to say something that disagrees with what someone else has said. So, you are going to disagree with someone, but you don’t want to hurt that person’s feelings. You want to do it politely, in a nice way. This is often used when you have a more or less serious disagreement with someone: “With all due respect, I think you’re an idiot.” That’s what my professors used to say at the university!
Abigail is much nicer, she says, “With all due respect, I don’t think that’s how it works.” She’s saying that Lon is wrong. “Yes,” she says, “the inspector will look at our work environment (the place where they work) and our gear and machinery.” “Gear” (gear) is typically the equipment that you use for a job; it could also be the clothing that you wear. “Machinery” refers to equipment that’s normally used to “manufacturer,” or make something, to produce something – something physical, that would be a piece of machinery. So, gear and machinery are going to be inspected by the inspectors to make sure there are no hazards or toxic substances. Something that is “toxic” (toxic) means it is poisonous. It is a chemical usually, that is dangerous for your health; it can make you very sick.
Lon says, “That’s what I’m worried about.” He’s worried about the inspectors finding something. Abigail says, “But, if they find a violation,” an instance where they have broken the law, or broken the rules and regulations, they will have “a chance to fix the problem.” That is, the company will be able to fix the problem before the government agency tells them to shut down. She says, “They won’t shut us down without giving us a chance to comply with their safety standards.” To “comply with” something means to obey a law or a rule or a regulation, to do something that you are being told to do. They are going to have a chance to comply with the “safety standards.” Those are the actual rules that the government has for companies. Usually they are specific rules that’s say you have to do so much or you have to have a certain amount of something. A “standard” is usually the minimum that you need to do to be able to pass inspection.
Lon says, “I sure hope you’re right.” Abigail says, “Me, too (I, as well).” But we don’t normally say “I, as well,” we would say more informally, “me, too.” Abigail says, “We’ll know after next week’s inspection”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Lon: What’s this?
Abigail: It’s a memo about a safety inspection scheduled for next week.
Lon: A safety inspection? How are we ever going to pass a safety inspection?
Abigail: What do you mean? This isn’t an unsafe workplace. We’ve had a good record. None of our employees have had on-the-job injuries this year and we’ve never had a fatality. I don’t understand why you’re so worried.
Lon: From what I’ve heard, the inspectors don’t just look at injury rates. They look for the smallest hazard that may be remotely dangerous. If we get cited, we may be shut down.
Abigail: With all due respect, I don’t think that’s how it works. Yes, the inspector will look at our work environment and our gear and machinery to make sure there are no hazards or toxic substances.
Lon: That’s what I’m worried about.
Abigail: But, if they find a violation, we’ll get a chance to fix the problem. They won’t shut us down without giving us a chance to comply with their safety standards.
Lon: I sure hope you’re right.
Abigail: Me, too. We’ll know after next week’s inspection.
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
memo – memorandum; a short, one-page written document used in offices to inform someone about a situation or decision without providing very much detail
* If you have a suggestion for how our company can sell more, please write a short memo to the vice-president to describe your idea.
safety inspection – a period of time, usually one day or a few days, when people come to a business to look around and ask people questions, trying to determine whether the workers and customers are safe there
* After the safety inspection, the company made all of its employees begin to wear special glasses to protect their eyes from the machines.
unsafe – not safe; dangerous
* Sometimes it can be unsafe to mix the chemicals that people use to clean their home.
on-the-job – at work; at a place of business and while one is at work
* Will the company provide any on-the-job training, or am I expected to know how to do everything when I start working there?
fatality – death
* There were more than 300 fatalities when the boat sank in the middle of the ocean.
mortality rates – the number of people who die each year per every 1,000 people
* In countries with poor health care, the infant mortality rate is as high as 184, meaning that 184 babies die for every 1,000 babies born.
hazard – danger; something that is dangerous; something that can physically hurt people
* One of the hazards of fixing a roof is accidentally falling off.
remotely – a little bit; slightly; barely
* The teenager cleaned his room, but it still smells remotely of old pizza and dirty socks.
dangerous – not safe; able to hurt or kill someone
* That is a dangerous neighborhood, so we never walk around there at night.
to be cited – to be told officially that one has done something against the law; to be told officially that one has broken a rule
* Hank was cited for driving too quickly on the freeway.
to shut down (something) – to make a business or organization close, so that it can no longer operate
* The restaurant was shut down after customers complained that it was unclean and that there were rats in the kitchen.
with all due respect – a phrase used when one wants to say something that disagrees with another person or criticizes another person, but one does not what to hurt that person’s feelings
* With all due respect, I think what you did was wrong.
gear – the clothing that one wears for an activity, or the equipment that one uses for an activity
* Rebbi bought a lot of new outdoor gear, like a sleeping bag and tent.
machinery – the equipment used to make, manufacture, or produce something
* The factory has fast machinery that can fill 100 bottles each minute.
toxic – poisonous; with chemicals that are dangerous for one’s health and can make one very sick
* Vitamins can be toxic if you take too many of them.
violation – an instance where one has broken a rule or done something against the law
* It is considered a traffic violation when people don’t stop at a stop sign.
to comply with (something) – to obey a rule or law; to follow a rule or law; to do what one has been told to do
* To comply with U.S. tax law, people must tell the government exactly how much money they receive for working.
safety standard – a rule that one must follow to make a place or activity safe
* One of the restaurant’s safety standards is that all employees must wash their hands before touching food.
Comprehension Questions
1. Which of these would be found at an unsafe workplace?
a) On-the-job injuries.
b) Gear and machinery.
c) Safety standards.
2. What might inspectors look for during a safety inspection?
a) A memo.
b) Due respect.
c) Toxic substances.
Answers at bottom.
What Else Does It Mean?
on-the-job
The phrase “on-the-job,” in this podcast, means at work or while one is working: “We aren’t allowed to accept personal phone calls on the job.” The phrase “to be out of a job” means to not have a job or to be unemployed: “Keith is out of a job, but he’s applying for lots of positions.” The phrase “to land a job” means to get a job, especially a job that one wanted very much: “Lizzie was very happy to land a job in Hollywood.” Finally, the phrase “a nose job” means a surgery to change the shape of one’s nose so that one is more beautiful: “He has a beautiful nose. Is it natural, or did he have a nose job?”
to cite
In this podcast, the phrase “to be cited” means to be told officially that one has done something against the law or broken a rule: “The accountant was cited for stealing money from the company.” The verb “to cite” means to refer to something as an example or to show where one’s information came from: “When you write your report, don’t forget to cite the newspaper where you found that information.” Or, “The manager cited the company’s vacation policy as her reason for not letting her employees take more than one week of vacation at a time.” Finally, the verb “to cite” can mean to say or write the exact words that someone else has said or written: “The teacher smiled and said, ‘beautiful Los Angeles,’ citing Dr. Jeff McQuillan’s favorite phrase.”
Culture Note
The Occupational Safety and Health Administration (OSHA) is the part of the U.S. government that tries to keep workers safe. “Occupational safety” is safety related to the “workplace,” or where people work. OSHA was created in 1971. According to its website, since then, it has “‘cut’ (reduced) workplace ‘fatalities’ (deaths) by more than 60 percent and occupational injury and illness rates by 40 percent.”
OSHA focuses on strong and “fair” (treating everyone equally) “enforcement” (the ways that its makes sure people and organizations are following its rules). OSHA tries to help businesses improve their occupational safety. It “allocates” (spends money for a specific purpose) most of its money and efforts on the businesses that have the most hazards, injuries, and fatalities. For example, in 2006 almost 60 percent of OSHA’s inspections were in the “construction” (building) industry, where there are many occupational safety hazards.
OSHA also focuses on “prevention,” doing things to not let injuries happen. It does this through education and “outreach” (communicating with a large number of people). OSHA has a website and a “hotline” (a phone number that people can call for information at any time) with information about common workplace hazards and how they can be “mitigated” (reduced). OSHA also offers free workplace “consultations,” where businesses can ask OSHA employees to come to their business, and help them identify and mitigate occupational safety hazards.
When OSHA inspections “reveal” (show) violations of safety standards, OSHA works with the businesses to fix those problems. However, sometimes there are “willful violations,” where the employer knew about the safety problem but didn’t change the way that things were done. When an OSHA inspection reveals a willful violation, the business is “fined” (has to pay money to the government) between $5,000 and $70,000.
Comprehension Answers
1 - a
2 - c