= 0434
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 434: Using Coupons and Rebates.
This is English as a Second Language Podcast episode 434. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode and to take a look at our ESL Podcast Store and ESL Podcast Blog.
This episode is called “Using Coupons and Rebates.” Many people use coupons and rebates to save money. We’ll talk about what those are by listening to a dialogue between to Torsten and Cindy. Let’s go!
[start of dialogue]
Torsten: What are you doing, clipping coupons? That’s a waste of time.
Cindy: You can think what you like, but these days, we have to cut corners wherever we can.
Torsten: No one actually saves much money using coupons.
Cindy: That’s what you think. The last time I went to the grocery store, I saved over $20 just by using coupons.
Torsten: How can you keep track of all of the expiration dates and the terms and conditions? It’s not worth the trouble.
Cindy: Do you feel that way about rebate offers, too? A month ago, I bought our new TV and saved 20 percent. And yesterday, I bought a pack of DVDs for just $2.
Torsten: Are you putting me on? A pack of DVDs for $2?
Cindy: Yeah, it was a great offer, but it was only for one day. I had to cut out the UPC code, fill out a form, and mail it in with the receipt to the manufacturer. Then, I sent a copy of the receipt to the retailer and got another discount. That’s how I got the DVDs for next to nothing.
Torsten: You might save money with rebates, but you have to sit around forever waiting for the rebate check.
Cindy: It’s true that the turnaround is often 8-10 weeks, but some of the offers are worth the wait.
Torsten: Do what you like, but I’m too busy to mess around with coupons and rebates.
Cindy: That’s why you married a penny-pincher. If I left it up to you, we’d be in the poorhouse by now!
[end of dialogue]
Torsten begins by asking Cindy, “What are you doing, clipping coupons?” To “clip” (clip) something means to cut something, sometimes to make it shorter or smaller. Here, it means to cut something to separate it from what is around it. A “coupon” is a small piece of paper, usually, that a shopper (someone in a store) will show in order to get a discount. In the newspapers and magazines you’ll often see coupons, and you cut the coupon out (we would say you “clip” the coupon) and take it to usually a grocery store, but it could be another kind of store, and you get a “discount,” you get to pay less money for that thing.
Torsten thinks clipping coupons is a waste of time. Cindy says, “You can think what you like (meaning I don’t care what you think), but these days (nowadays), we have to cut corners wherever we can.” To “cut corners” means to save money or to save time by doing something differently, something that is not the normal or usual way. Usually cutting corners refers to saving money, but it could be saving time. You don’t want the airline pilot, for example, to cut corners when it comes to your safety; you want him to take as much time as possible – or her.
Cindy says that they have to cut corners wherever they can. Torsten says, “No one actually saves much money using coupons.” Cindy says, “That’s what you think.” The expression “that’s what you think” means you disagree with what the other person has said. Usually, this is followed by your reasons why you think that person is wrong. Notice that there’s an emphasis on the word “you”: “Well, that’s what you think, but...” and then you give your reasons why this person is wrong.
Cindy says the last time she went to the grocery store to buy food; she saved over $20 just by using coupons. Torsten says, “How can you keep track of all of the expiration dates and terms and conditions?” An “expiration date” is the data after which something cannot be used or something will no longer be valid. So, if the coupon has an expiration date of November 1st that means that you can’t use it after November 1st. “Terms and conditions,” what some people in the business world call “Ts and Cs” – terms and conditions are parts of a legal agreement that give specific details about how something will work or how something will function. So, it’s the legal information about what you are selling or what service you are providing.
Torsten says that coupons are “not worth the trouble,” meaning they are not beneficial; they don’t really help very much, especially because you have to spend time clipping them and so forth. Cindy says, “Do you feel that way about rebate offers, too?” A “rebate” is money that you get back from the company that makes or sells a product (something that you buy). After you buy it you can get, from some companies on some products, a rebate – money back. Now, often you have to do something to get that money back. A “rebate offer” is when the company says that they will give you some of your money back, or perhaps even all of the money back, if you buy this thing at a certain time or on a certain day. And, usually you have to prove that you bought it, so you have to send a form – send a piece of paper to the company with a copy of your receipt or some other what we would call “proof of purchase,” meaning evidence that you bought something.
Cindy says a month ago she bought a pack (or a set) of DVDs for just two dollars. Torsten says, “Are you putting me on?” To “put someone on” is a phrasal verb meaning to trick someone, to deceive someone, to get someone to believe something that isn’t true. Sometimes people do this just to be funny. When I say, for example, that you can find tickets to Hawaii in our Learning Guide for this episode, I’m putting you on; I’m not really serious. Really, I’m not; we don’t have tickets in our Learning Guide for this episode, I’m sorry!
Cindy says, “it was a great offer, but it was only for one day.” So, of course, she’s not putting Torsten on, she’s telling the truth. She then explains how she got the rebate. She said she had to cut out the UPC code. The “UPC” code stands for Universal Product Code; sometimes we call it simply the “bar code.” It’s a small rectangle that you will find on most packages – most things that are sold in the United States in a store – that has many vertical black lines and numbers that a machine can read. That is, the machine can detect what the price is and what the thing is. Most stores have a special machine call a “scanner” that you use with these UPCs, or bar codes.
However, Cindy is cutting out the UPC code as a proof of purchase, evidence that she bought this thing. In order to get the rebate, Cindy has to fill out a “form,” a piece of paper with her name and address on it, and mail that form in with the receipt to the manufacturer. The “receipt” is the piece of paper the store gives you to show that you bought something; it has the price of what you bought. The “manufacturer” is the company that makes a product – a physical product. Computers are manufactured by companies such as Apple and other computer companies, for example.
Cindy says, “Then, I sent a copy of the receipt to the retailer and got another discount.” The “retailer” is the store that sold the product. So we have the manufacturer that made the product, and then you have the store that sold it. Cindy is actually getting two rebates here, one from the manufacturer and one from the store – the retailer. She got another “discount,” which is a reduction in the price of something. “Discount” has a couple of different meanings in English; take a look at our Learning Guide for some additional explanations.
Torsten says, “You might save money with rebates, but you have to sit around (you have to wait) forever for the rebate check.” The “rebate check” is the money that the company is sending you back. Sometimes it will be $5, $10; it could be $500, depending on how big the rebate is, and, of course, depending on what you buy. Now, not every company offers rebates on their products. It’s something that only some companies do sometimes to get people to buy their product.
Cindy says, “It’s true that the turnaround is often 8-10 weeks.” The “turnaround” is the amount of time needed to send something, have the company look at it, take care of it, and then send, in this case, the rebate check back. So it’s the time that you send something in and then you get it back. We can use this word in talking about anything that you, for example, submit an application for and then have to wait before you get back whatever you are waiting for. If you are going to get a driver’s license in the United States, there may be a certain turnaround time. That is, it may take a few days or even a few weeks for the state government to send you your physical license. Cindy says that the offers (the rebate offers) are “worth the wait,” meaning they are good enough that one is willing to wait a long period of time to receive it.
Torsten says, “Do what you like, but I’m too busy to mess around with coupons and rebates.” To “mess around,” here, means to spend time doing something that is not productive, that is not a good use of your time. We also use this expression, to mess around, in talking about children who are misbehaving, who are playing and perhaps causing problems. It can also be used in a sexual way; to mess around may be to engage in some sort of sexual activity. I’m married, so I wouldn’t know!
Cindy says, “That’s why you married a penny-pincher.” The term “penny-pincher” refers to someone who doesn’t like to spend money, who always is looking for the lowest price for something. Cindy says, “If I left it up to you (meaning if you were in charge of the situation), we’d be in the poorhouse by now!” The “poorhouse” is a place where, many years ago, very poor people would go for help when they didn’t have enough money or they didn’t have a place to eat. Poorhouses were common, for example, in the 19th century in England. If you read a novel by Charles Dickens, he often talks about these poorhouses. They were not very nice places to be. Here, Cindy is using the expression just to mean we would be poor, we would not have very much money.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Torsten: What are you doing, clipping coupons? That’s a waste of time.
Cindy: You can think what you like, but these days, we have to cut corners wherever we can.
Torsten: No one actually saves much money using coupons.
Cindy: That’s what you think. The last time I went to the grocery store, I saved over $20 just by using coupons.
Torsten: How can you keep track of all of the expiration dates and the terms and conditions? It’s not worth the trouble.
Cindy: Do you feel that way about rebate offers, too? A month ago, I bought our new TV and saved 20 percent. And yesterday, I bought a pack of DVDs for just $2.
Torsten: Are you putting me on? A pack of DVDs for $2?
Cindy: Yeah, it was a great offer, but it was only for one day. I had to cut out the UPC code, fill out a form, and mail it in with the receipt to the manufacturer. Then, I sent a copy of the receipt to the retailer and got another discount. That’s how I got the DVDs for next to nothing.
Torsten: You might save money with rebates, but you have to sit around forever waiting for the rebate check.
Cindy: It’s true that the turnaround is often 8-10 weeks, but some of the offers are worth the wait.
Torsten: Do what you like, but I’m too busy to mess around with coupons and rebates.
Cindy: That’s why you married a penny-pincher. If I left it up to you, we’d be in the poorhouse by now!
[end of dialogue]
The script for this episode was written by someone who never cuts corners, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
to clip (something) – to cut something, making it shorter or smaller, or separating it from a larger piece of something
* The barber clipped his customer’s hair too short.
coupon – a small piece of paper that a shopper shows to the store when buying something that lets him or her have a lower price
* Tuna normally costs 97￠, but I bought a can for just 42￠ because I had a coupon for 55￠ off of one can.
to cut corners – to save money or time by doing something differently
* The store cut corners to save money by having fewer employees, but the customers didn’t like the lower level of service.
that’s what you think – an informal phrase used to show that one disagrees with what another person has said, usually followed by the reasons why one disagrees
* Luiz said that riding the bus was too expensive, but I said, “That’s what you think!” and then I told him how much money I saved by not having a car and using the bus instead.
expiration date – the date after which something is no longer valid or can no longer be used
* Milk tastes horrible after its expiration date.
terms and conditions – the parts of a legal agreement that provide all the specific details about how something will function or work
* The company advertises a cell phone for only $20 per month, but if you read all the terms and conditions you find out that you’ll have to pay a lot of money in extra fees.
rebate offer – an agreement where a company refunds part or all of the cost of something if a shopper buys the correct item on the correct day(s) and provides copies of the receipt and/or packaging information
* This computer has a $150 rebate offer, so even though I have to pay $999 today, I’ll get a check for $150 in a few weeks, meaning that the computer will cost only $849 in the end.
to put (someone) on – to trick someone; to try to get someone to believe something that isn’t true; to play a practical joke on someone
* You’re putting me on! I don’t believed that you’re going to quit your job as a lawyer to become a professional surfer.
UPC code – universal product code; a bar code; a small rectangle on the package of most things that are bought in stores, with many vertical black lines and numbers on the bottom that can be “read” by a machine, letting it know what the product is and how much it costs
* The cashier couldn’t get the computer to read the UPC code, so she had to enter the information manually.
receipt – a piece of paper that one is given after buying something, showing what one has bought, where, when, and how much it cost
* Excuse me, there’s a problem with my receipt. It shows that I was charged for two bottles of shampoo, but I bought only one.
manufacturer – the company that makes a product
* This is a well-known computer manufacturer.
retailer – a store that sells things that are made by other companies to ordinary people (not to other businesses)
* The store on our street is a low-cost retailer that is growing very quickly in the United States.
discount – a reduction in the price of something
* The store is offering a 15% discount on shoes this weekend.
rebate check – money received from a company after one has followed all the rules for a rebate offer
* When she bought the stereo with a rebate offer, she filled out all the paperwork, and then seven weeks later, she received a rebate check for $60.
turnaround – the amount of time needed to receive something, process it, and send it back
* What is the average turnaround time when someone applies for a driver’s license?
to be worth the wait – for something to be so good that one is willing to wait a long period of time to receive or use it
* Joao had to wait months to get the new cell phone, but when he finally got it, he was very happy and said that it had been worth the wait.
to mess around – to spend time doing something that is unproductive or that is not a good use of one’s time; to spend one’s time in a silly way or doing silly things
* They spent hours messing around online instead of doing their homework.
penny-pincher – a person who doesn’t spend very much money and always looks for the lowest prices for the things that he or she wants to buy
* Manny is such a penny-pincher that he hasn’t bought any new clothes in almost three years.
poorhouse – a place where very poor people used to be able to go for help when they didn’t have enough money for food or clothes
* If we eat at expensive restaurants every night, we’ll end up in the poorhouse!
Comprehension Questions
1. Which of these would not be sent to the manufacturer for a rebate offer?
a) A retailer.
b) A receipt.
c) A UPC code.
2. Which of these would have an expiration date?
a) A coupon.
b) A receipt.
c) A UPC code.
Answers at bottom.
What Else Does It Mean?
to clip
The verb “to clip (something),” in this podcast, means to cut something, making it shorter or smaller, or separating it from a larger piece of something: “I clipped an interesting article from the newspaper.” The phrase “to clip (something) to (something)” means to fasten two things together so that they are connected: “Please clip the papers together so that they don’t get separated.” As a noun, a “clip” is something that holds things together: “It’s going to be windy, so you might want to use a hair clip.” Or, “Your suit would look more professional if you used a tie clip.” Finally, a “clip” can be a short part of a movie: “We saw some clips for the new movie and it looks like it will be really entertaining.”
discount
In this podcast, the word “discount” means a reduction in the price of something: “We’re waiting to buy a dishwasher until we find a good discount.” The same word can also be used as a verb, “to discount”: “Does your store ever discount digital cameras?” A “discount (store or business)” is a store or business that offers very low prices: “Do you shop at a regular grocery store or a discount store?” Or, “You might be able to find cheaper airfare if you fly on a discount airline.” As a verb, “to discount (something)” means to think that something isn’t important or to think that something probably isn’t true: “They discounted her opinion, thinking that she didn’t really know what she was talking about.”
Culture Note
In the United States, there are many types of coupons and rebate offers. “Manufacturer’s coupons” are offered by the manufacturer, or the company that makes the product. “Store coupons” are offered by the store where the product is sold. Normally manufacturer’s coupons and store coupons can be “combined” (used together) for “added” (additional) savings.
Many coupons are “cents-off” coupons, where a certain amount of money is “subtracted” (taken away) from the normal price of a product. There are also “two-for-one” coupons or “buy-one-get-one-free” coupons where the shopper gets two items but pays for only one of them.
Some grocery stores offer to “double coupons,” meaning that they will “match” (offer the same amount off as) the cents-off coupon. For example, if you buy a can of soup that normally costs $1.35, but use a cents-off coupon for 40￠ and the store doubles the coupon, you will pay only 55￠ for the can of soup.
Rebate offers are usually offered by manufacturers, but they can also be offered by stores. With a rebate offer, the manufacturer or store offers to give the buyer a certain amount of money back if he or she “complies with” (obeys; follows all the rules) all the terms and conditions of the rebate offer. This usually means that the buyer must buy a specific type and size of product during a certain period of time. Then the buyer usually has to “fill out a form” (provide the information requested on a piece of paper) and “submit” (send to an authority) it with a copy of the receipt and the UPC code from the package. If the buyer does everything correctly, then he or she will receive a rebate check in a few weeks.
Comprehension Answers
1 - a
2 - a