= 1685
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 380.
This is English as a Second Language Podcast’s English Café episode 380. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. You can also take a look at our ESL Podcast Store, with additional courses in daily and business English, as well as our ESL Podcast Nlog.
On this Café, we’re going to continue our series on American presidents, focusing on the seventh president of the United States, Andrew Jackson. We’re also going to talk about one of my favorite national parks here in the U.S., Redwood National Park. And as always, we’ll answer a few of your questions. Let’s get started!
This Café begins with a continuation of our series on American presidents. Today we are going to talk about the seventh president of the United States, Andrew Jackson. Andrew Jackson was born in 1767, just about 10 years before the young American colonies declared their independence from Great Britain. He was born somewhere on the boarder or the dividing line between the states, or the then colonies, of North and South Carolina.
He joined the efforts of the American revolutionary army to beat the British when he was only 13 years old. He and one of his brothers were captured by the British. They were taken as prisoners during the American Revolutionary War. They were, in fact, what we would call “prisoners of war.” We sometimes use the acronym “POW” – “prisoner of war.” That experience, as a teenager, being held as a prisoner by the British, affected Andrew Jackson in a personal way. He really disliked – “hated,” we could say – the British because of that experience. Both of his brothers and his mother died during the war, and he certainly blamed their deaths on the British. That is, he thought the British were responsible for what had happened to his family.
After the war, Jackson, who is probably the first American president who was born into a fairly poor family, studied to become a lawyer, and although he didn’t have a very good legal education, he became a successful lawyer. He moved to what became the state of Tennessee, which is sort of in the central eastern part of the U.S.
At the time, it was just a territory; that is, it wasn’t an official state, but he helped in become a state and, in fact, became the first representative from Tennessee in the House of Representatives in Washington, D.C. He later became senator for the state of Tennessee, but for a variety of reasons, he didn’t see himself as being a very good politician, or at least someone who was interested in politics, and so he left the Senate to become a judge in Tennessee. He also became a very successful farmer – someone who owned a lot of land.
Jackson was what we would describe as a very “aggressive” person. Someone who’s aggressive is someone who tries to get what he wants, who may use even force or violence to get what he wants. Jackson, for example, fought in many duels. A “duel” (duel) – as a noun – is a fight where men walk away from each other and then at a certain point, they turn around at the same time and they try to shoot each other and kill each other. You’ve probably seen it in the movies. Because of this experience and because of his military service, which we’ll talk about in a moment, he was often called “Old Hickory.” “Hickory” (Hickory) is a very strong type of tree. Jackson, then, had a reputation of being a very strong man, not just physically, but in terms of his personality, in terms of his character.
Jackson became famous for his role in the War of 1812. The War of 1812 was the second war between the United States and Great Britain. It took place, as you can guess, in 1812. It was in this war that Jackson became famous as a military commander. He led a group of soldiers to defeat one of the Indian tribes which had become friends with – allies with – the British.
He’s most famous, however, for what is now called the “Battle of New Orleans.” In 1815, Jackson’s military troops defeated the British in New Orleans. It was one of the most famous battles of the war. In it, Jackson had just 5,000 soldiers fighting against 7,500 British soldiers. A “soldier” (soldier) is a man or woman who is fighting in a war. The irony, the strange thing, about what happened at the Battle of New Orleans is it actually took place after the U.S and Britain had officially signed a peace treaty, ending the war. But, of course, there was no Internet or even telephones in those days. They couldn’t just pick up their iPhone and call Jackson and tell him that the war was over. And so, the Battle of New Orleans was technically fought after the end of the war, a couple of weeks after. Nevertheless, Jackson was considered a national hero for his actions at the battle of New Orleans.
He later became involved in another war, what’s called the First Seminole War, one of the many wars against the American Indian tribes. He basically invaded Florida, which belonged to Spain at the time. He invaded Florida, technically, during the War of 1812. It became a major problem for the national government. Eventually, Spain ceded Florida to the United States. “To cede” (cede) means to give land to another party, another, in this case, country. Spain didn’t have much of a choice, of course, since the U.S had a military force there. Jackson became the military governor of Florida in 1821.
Jackson, now a war hero, a national hero, decided to run for the presidency. And in 1824, he tried to become president. He received the most votes. However, no one had a majority of the what are called “electoral votes” necessary to win the presidency. As a result of that, the election was decided by the House of Representatives. I don’t want to talk too much about that process but basically, the House of Representatives decided to elect John Quincy Adams as president and not Andrew Jackson.
Andrew Jackson wasn’t very happy about this, you can imagine. And in the next presidential election of 1828, he ran a campaign that appealed directly to the people. It was considered one of the first we might call “populist” campaigns. It was also a very ugly campaign. That is, it wasn’t a very pleasant campaign. It wasn’t a very nice campaign, or a lot of mean things were said by both candidates. “Ugly” (ugly) normally describes someone who isn’t very good looking. I have often been described as ugly, for example. But when we talk about an “ugly campaign,” we mean a campaign in which the politicians both say bad things about each other. Of course, now we’re used to those kinds of things in politics, in almost every country.
In the 1828 presidential election, Jackson and his wife were accused of bigamy. “Bigamy” (bigamy) is when you marry someone even though you haven’t divorced your first husband or wife. Now, technically, this did happen – Jackson married his wife before he completed his divorce of the previous wife. However, when they discovered the mistake (and Jackson said it was a mistake), they remarried again when they were legally able to do so. However, it was one of the many things that people criticized Jackson over. Jackson won the election. Sadly, his wife died that same year. Jackson, therefore, entered the White House, the presidency, as a widower. A “widower” (widower) is a man whose wife dies. The opposite term for a woman whose husband died is a “widow” (widow). Of course, it’s much more common to have widows than widowers, since men tend to die before women. I wonder why.
Jackson’s presidency was important in a couple of ways. He won election in 1828 by appealing to the mass of people – to the large numbers of people – as someone who was just like them, as a common man. He was also the first president to be born west of the Appalachian Mountains. The Appalachian Mountains are the mountains that go through the eastern part of the U.S. And in many ways, Jackson represented a new form of popular democracy in the United States. In fact, we have the term “Jacksonian Democracy” describing the rise of popular democracy in the U.S.
Jackson did not enter the presidency with any strong political ideas. As I mentioned before, the election of 1828 was a very ugly one and some ways, a very personal one. But in general, Jackson was a strong supporter of the rights of the individual states to make certain decisions on their own behalf. There is this constant tension, this constant pull in American politics between the national government, the federal government, and the state governments. How much power should the national government have versus the state governments? This is a constant theme in American history, and in the Jackson presidency, it’s one in which the states tended to be the winning party – tended to be favored in terms of the power they had.
One very important case of this was the state of Georgia, which had tried to get rid of the Native American tribes, the American Indian people that were living on lands. The American Indians signed a treaty, signed an agreement, with the national government allowing them to stay where they were. However, the state of Georgia wanted to move them and so, they, by force – by military force – forced them to leave their lands. The Native Americans actually went to the highest court in the United States, the Supreme Court, and won.
However, the government of Georgia and the presidency of Jackson refused to enforce, refused to make the state of Georgia obey the law. As a consequence, more than 45,000 Native Americans were moved from Georgia, in the east, to what is now the state of Oklahoma, in the western part of the U.S. This forced relocation of Native American tribes is sometimes called the “Trail of Tears.” A “trail” is a road. “Tears,” or course, are drops of water that come from your eyes when you’re sad. The reason it’s called a Trail of Tears is almost a quarter of the Native Americans died on this forced relocation. To “relocate” means to move people from one place to another. It was “forced” because the army made them move. They didn’t want to move.
Jackson’s presidency is also known for his dismantling of the Second Bank of the United States. It’s a bit complicated to go into. Basically, the American government had tried – the federal government – had tried to setup a national bank. Jackson didn’t like the idea and he decided to end the national bank. We use the verb “to dismantle” (dismantle). “To dismantle” means to take something apart piece by piece. In this case, it’s more of a metaphor. It wasn’t a physical thing that Jackson took apart but rather, this organization, this institution of the Second Bank.
In 1835, he paid off the national debt; that is, he took all of the money that the federal money owed and he paid it back. He paid it back, we would say, “in full” – 100%. This was the first and only time that that has ever been done. The United States government, like many governments, of course, has many many millions, billions of dollars in debt. “Debt” (debt) is money that you owe someone else, that someone else has lent you.
As I said, Jackson was a supporter of the rights of states, but he didn’t support what was then called “nullification.” “Nullification” comes from the verb “to nullify” (nullify). “To nullify” means to say that a certain law is no longer good. It no longer exists. It will no longer be applied. One of the states tried to “nullify” a certain federal law to say, “Well, we don’t like that federal law so we’re not going to obey it.” Once again, we have the tension between the federal and the state governments. Jackson was definitely against the state government, in this instance, and what is called the “Nullification Crisis.” He said that the national government had the right to make laws, and that the states had to obey them.
Jackson died in 1845. He was 78 years old. He created a strong political party, what we now call the “Democratic Party,” which, of course, is still one of the two major political parties in the United States.
Now let’s turn to our next topic, briefly, which is the Redwood National Forest. Redwood National Forest is located right here in California. It’s in Northern California. “Redwood” describes a kind of tree. In fact, it’s the tallest kind of tree on earth – on the entire planet. These huge, large trees, attracted many loggers, people who wanted, of course, to cut the trees down and sell them for things, especially as California was becoming populated in the middle of the 19th century. Loggers, people who cut trees down, came to California. They began cutting these trees down and over a period of more than a hundred years, almost 90% of these large, really beautiful trees were cut down.
Finally, the area where most of these trees were located became a national park in 1968. I visited Redwood National Park just a few years later, in 1972. And it was one of the most amazing experiences, to see these huge trees. One of these Redwood trees (technically known as “Coast Redwood” trees) called “Tall Tree” is thought to be the tallest tree in the world. It is 370 feet tall. That’s about 110 meters. Some people say now that other trees there are taller than what is called “Tall Tree.”
Coast Redwood trees commonly live for 500 to 700 years. Some of them, in fact, are thought to be around 2,000 years old. Imagine a tree that’s 2,000 years old, almost as old as me! Today the park provides protection for these trees and for the birds and other animals that live in and around the trees. The organization of our national government that takes care of our parks, the National Parks Service, tries to conserve or keep these plants and animals that live there, especially by making sure that they don’t get destroyed by fire.
That doesn’t mean, however, that they try to put out or stop any fires in the forest, in the park. In the past, that, in fact, was the policy – to suppress or not allow fires to burn in the forest. But, of course, they realized that you have to have a certain amount of that sort of change, including fires. If you don’t allow these smaller fires to continue, what will happen, of course, is that when there is a fire, it will become even larger and destroy the forest even more.
Many people visit the park, the Redwood National Park, for hiking and camping. Some people also like to fish in the park. I don’t like to do any of those things but I did enjoy visiting the park when I was a young boy. Walking through the park, walking through these trees and looking up at them is such an amazing experience. If you ever have a chance to visit Redwood National Park here in California, I think you’ll really enjoy it.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Norbert (Norbert) originally from Poland, now living in Germany. Norbert wants to know the difference between “safe” (safe) and “save” (save). Let’s start with “safe.” “Safe” can be an adjective, meaning to protect someone from danger or to be away from any possibility of being hurt or harmed. “My money is safe. I put it in the bank and nothing will hurt it” – except of course, if the bank closes. Or, you could talk about “My friend was in danger but now he’s safe.” He was involved a robbery, someone tried to steal something from him, but now he’s safe, now he’s away from that danger, away from that harm.
“Safe” can also be a noun, describing a box that you put something in to protect it. The bank, for example, will have a big safe, often one that you can actually walk into. The safe is large. It has a lot of locks on it. It’s made of a very strong metal to protect it. That’s a safe – as a noun.
“Save” as a verb means to keep someone from danger. “Safe” is an adjective, meaning that someone is not in danger, or away from danger. “Save” is a verb meaning to rescue or to keep someone from danger. So, you might have a cat that climbs up a tree and you want to go up and “save” the cat, for whatever reason. So, you climb up the tree and you save your cat. You rescue it. You take it away from the danger it was in.
“Save” as a verb, can also mean to keep – not to use. We talk about “saving money.” I’m going to save a hundred dollars from my pay this month. I’m going to put it in the bank and I’m not going to use it. I’m going to save it. Here, the opposite of “save” would be “spend” (spend). So, “save” as a verb can mean to rescue. “Save” as a verb can mean to keep, not to use. You could save your money in a safe. That is, you could save – keep it – in this box called a “safe.”
Our next question comes from Nesrine (Nesrine). I’m not sure where Nesrine is from. It doesn’t say here. But no doubt, they’re form planet Earth. Nesrine wants to know the difference between two phrases – “to be implicated in” and “to be involved in.” Let’s start with the first one. “To be implicated (implicated) in something” means that you participated, you had some part in, you were active in some sort of activity – usually a crime, usually something that was against the law. We might talk about someone being “implicated” in a theft – that is, stealing something from someone else. To say they’re “implicated” means that we believe they were part of it. They were involved in it.
“To be involved in” means just that you were part of something, that you participated in some activity or in some group. It doesn’t mean that you’ve done anything wrong. So, “to be involved in” is a general expression to describe your participation in something or your membership in some group. “To be implicated in” means to be involved in something that is wrong – something that typically is criminal, against the law. It’s okay to be involved in something but you definitely don’t want to be implicated in anything.
Finally, Sergio (Sergio) in Mexico wants to know the meaning of the phrase, “the one and only.” He heard this from a song by a famous British singer, at least nowadays, in 2012 – Adele. The phrase “one and only” has a couple of meanings. One is that it is the sole or only member, or only thing, that there are no others. “This is the one and only time I am going to go to Disneyland.” I am never going to go again. This is the one and only time. You could just say this is the only time. It means the same but to give a little more emphasis, we might say “the one and only,” even though they mean the same thing really.
Another use of “one and only” is to say something is the best – the most talented, the most beautiful, the most excellent. You can’t compare this person to anyone else. You’re not saying that they’re the sole or only person who can do this or who has this certain talent or quality. You’re saying that they’re the best, however. In the song by Adele, “One and Only,” “one and only” really stands for “one and only love.” This is the only person that I can ever love. This is the best person for me. I may describe Lucy Tse as our “one and only scriptwriter.” By that, I mean not just that she’s the only one, but that she’s the best possible one – the best possible scriptwriter in the world, in this case.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com. From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, right here on the English Café.
ESL Podcast: English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2012 by the Center for Educational Development.
Glossary
prisoner of war – a person who is held by the enemy and not allowed to leave during a war
* James was a prisoner of war for six months and was released when the war finally ended.
duel – a fight in which two people walk away from each other, turn around at the same time, and then try to shoot and kill the other person; a fight with deadly weapons fought to decide a matter of honor
* In the movie, the two men dueled over a woman and one of them was seriously wounded.
to cede – to give up power or land; to officially give to another person, organization, or country control over something or some area of land
* The king lost the battle and had to cede land to his enemy.
ugly – very unpleasant, involving unkind actions or words
* The sisters were angry at each other, but were able to walk away before the argument turned ugly.
bigamy – marrying someone while already being married to someone else; being married to more than one person at a time
* Did you read the newspaper article about the bigamy case in which one man was married to 12 different women?
forced relocation – using force to move a person or a group from their home to another place against their will
* Scientists are carefully watching what happens following the forced relocation of animal life in this area as a result of oil drilling.
to dismantle – to take apart completely; to take apart into pieces
* Fred likes to find out how machines work and enjoys dismantling them to see how the different parts fit together.
in full – completely; 100% of the amount owed
* After 20 years, Leona and Manuel have finally repaid their home loan in full.
to nullify – to say that a law or document does not exist or that it is not applicable to a situation
* The governor tried to nullify a law limited how many times he could be elected to office, but he failed.
logger – a person whose job is to cut down trees so they can be sold for lumber (wood that is cut into small pieces and used for building)
* In the old days, loggers used handsaws to cut down even the largest trees.
ancient – very, very old; from the distant past
* The vases in the museum are from ancient Greece.
to suppress – to prevent something from happening; to cause an action or development to not occur
* The government tried to suppress people from speaking out against its unfair policies by arresting news reporters.
safe – away from harm or hurt; not in danger; trustworthy; a steel or iron box that locks to protect valuable items or money
* It’s important that students who attend courses at night feel safe on campus.
save – an act that helps to wins a game; something done to keep from losing, usually in sports; an act that prevents something bad from happening
* Jessica’s save prevented us from losing our third game in a row.
to save – to rescue; to keep from danger; to keep; to not use
* Who will save the beautiful woman from the evil murderers?
to be implicated in – to be shown to be a part of an activity, usually a crime
* Nearly everyone in this office has been implicated in the financial scandal.
to be involved in – to be a part of an activity; to be included in a group
* Marco has been involved in a charity to help the poor for more than 10 years.
one and only – the only one; no others; the best; the most beautiful, talented, excellent, etcetera; without comparison
* Her father was the one and only person who believed in her and helped her become a professional basketball player.
What Insiders Know
Esperanto
Esperanto is a language created by a doctor and “linguist” (person who studies languages) named L. L. Zamenhof in 1880’s. Zamenhof used the “pseudonym” (false name used by writers who do not publish under their real name) Doktoro Esperanto. Esperanto means “one who hopes.”
Zamenhof wanted to create a language that was easy to learn because he believed that there was a need for an international language. In his native country, Russia, he saw the need for one “common” (shared by all) language for communication among the many different groups of people. Zamenhof created Esperanto with the hope that it would become a language used “worldwide” (all over the world). He wanted a way to discuss political, cultural, and economic issues more easily by using one “unbiased” (without showing preference to one language or culture) language. Esperanto is based on a Latin alphabet of 28 letters. It is not related to any other language, but uses parts of several of them.
While some “non-profit” (with a goal of helping others, not making money) organizations use Esperanto, no country has officially “adopted” (made it one’s own) the language. It’s unclear how many speakers there are of the language. Some “estimates” (guesses) are in the “tens of thousands” (between 10,000 and 90,000), while others say it is in the millions in over 100 countries.
There are many “critics” (people who are against something) who say the language sounds and looks “artificial” (fake; not real). Others claim that it is too closely based on European languages to be truly international. Some people even say that there is no benefit in learning this created language, and time is better spent in learning another, more commonly-used language.