= 1671
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast English Café number 366.
This is English as a Second Language Podcast’s English Café episode 366. I’m your host Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Our website is eslpod.com. Go there, become a member, download a Learning Guide, improve your English faster than you ever thought possible.
On this Café, we’re going to have another one of our “Ask an American” segments where we listen to other native speakers talking at a normal speed, then we go back and we explain what they said. Today, we’re going to be talking about space exploration in the United States – why some people think it’s important for the U.S to continue its space exploration program. And as always, we’ll answer a few of your questions. Let’s get started!
We’ll listen to astrophysicist – someone who is a scientist interested in outer space – we’re going to listen to astrophysicist Neil deGrasse, He’s going to talk about what is going on with the space exploration program in the United States in the year 2012, which is when we’re recording this episode. We’ll listen and then go back and explain what he says. Let’s start.
[recording]
“And right now, the United States has no vehicle of its own to take our astronauts to orbit. We have to hitch a ride with the Russians. In fact, if you hitched a ride it implies you got on for free. But we are riding with the Russians because we are paying for those seats. So it’s a little embarrassing, I think.”
[end of recording]
Dr. deGrasse – Neil – can I call him Neil? Yeah - Neil. Neil says that “Right now – at this time – the United States has no vehicle of its own to take our astronauts to orbit.” The word “vehicle” (vehicle) is normally word we use to describe an automobile - a car, that is. It could also describe a truck that you drive, but here it means a machine with a motor or an engine in it that takes people from one place to another. So, vehicle has a more general meaning and that’s the meaning that Neil is using here. He’s, of course, talking about a ‘space vehicle “ – a machine that will take people from Earth up into outer space such as what we used to have the space shuttle do. Neil says that “Right now, the United States doesn’t have a vehicle of its own – meaning one that belongs to the United States – to take our astronauts to orbit.” An “astronaut” (astronaut) is a word we discussed a few weeks ago on the Café. An “astronaut” is someone whose job it is to fly in a space vehicle up into outer space. “Orbit” (orbit) here refers to the circular path that a space ship takes around a planet – in this case, Earth. We can use this as a verb. We say, “The Earth orbits around the sun,” meaning the Earth goes around the sun. And “The moon orbits around Earth.” The moon goes around the Earth. Well, when you have a space vehicle, the vehicle will orbit around the earth just like a satellite. It will go around in a circular path or something close to that. I don’t think it is actually a true circle.
Neil says that because the United States doesn’t have a space vehicle of its own, we have to “hitch a ride with the Russians.” The expression “to hitch (hitch) a ride (ride)” means to ask for, and get someone else to take you – usually in their car or in their truck or in their vehicle – from one place to another. When you don’t have a car, you can go out on the street or the highway and you can “hitch a ride.” Another word we use is “hitchhike” (hike) at the end. “To hitchhike” means to travel around from place to place, city to city – when you don’t have a car – by going out and basically asking people to take you from one place to another. In the United States, the normal way of doing this is to put your hand out with your thumb extended – in the direction of where the car is going – and that indicates that you want to hitch a ride. This is not recommended in most places in the United States. It can be very dangerous. I probably would not suggest you do that here. And in some places now, I think it’s illegal to do that. You could be arrested for doing that, especially on a freeway or a highway. Well, this is the idea that Neil is talking about when he says, the U.S has to “hitch a ride with the Russians” or “hitch a ride from the Russians,” we could say. This means that the Russians still have a space vehicle and if we want to send astronauts into space, we have to, basically, ask, or pay for the astronauts to get up into outer space, going with the Russian vehicle.
He says, “In fact if you hitched a ride, it implies you got on for free” – and remember, that’s what I said, that when you hitch a ride, you get someone else to take you. The idea is that they don’t charge you any money. If you had money, you’d take a bus or some other way of getting to where you want to go. Neil reminds us, however, that hitching a ride with the Russians is not free. He says, “We are riding with the Russians because we are paying for those seats.” A “seat” (seat) is where you sit. So, when Neil says, “We’re paying for those seats,” he means – just like on an airplane, you have to pay in order to fly on the airplane. We have to pay the Russians to fly on their or in their space vehicle. He thinks it’s a little embarrassing. “To be embarrassed” means to feel a little ashamed or to feel bad because the situation isn’t very good for you and perhaps because you’ve done something wrong. That’s usually when we feel embarrassed. But Neil thinks it’s embarrassing for the United States to have to pay another country in order to send its astronauts up into outer space. I’m not sure if Neil is right about that but that’s his opinion and he’s sticking to it – he’s holding to it, he’s not going to change it. Here’s Neil again.
[recording]
“And right now, the United States has no vehicle of its own to take our astronauts to orbit. We have to hitch a ride with the Russians. In fact, if you hitched a ride it implies you got on for free. But we are riding with the Russians because we are paying for those seats. So it’s a little embarrassing, I think.”
[end of recording]
Neil thinks – not surprisingly – the United States should spend more money on space exploration. You have to understand that the United States in the last two or three years has basically decided to end its space program – at least, sending men and women up in the space shuttle. The space shuttle is no longer operating and so the U.S doesn’t have a way now to send people up into space. The U.S Government is actually spending less money now on space exploration than they used to. Let’s listen to Neil again.
[recording]
“Because it’s just that kind of adventure that stokes the health of our economy and in this, the 21st century, science and technological innovation will define who leads the century and who does not. What we have found in the golden era of space exploration here in America that even though space was driven by war, the consequence of that was a completely shifted outlook that the entire country had about what was possible for our future. And the people who bring tomorrow into today are the scientists and technologists.”
[end of recording]
Neil begins by saying, “It’s just that kind of adventure that stokes the health of our economy.” He’s talking about the adventure or the excitement of going up into space. He thinks that this kind of adventure – this kind of excitement, this kind of journey, this kind of experience – “stokes” the health of our economy. “To stoke” (stoke) usually is used to talk about fire. We use the verb “to stoke a fire,” meaning you try to make it burn more, to burn hotter, maybe adding more wood, blowing air on it – that sort of thing. I don’t know. I don’t start a lot fires personally, but that’s what the verb is used for. “Stoke” can also be used to mean to make something bigger or stronger. In this case, Neil is saying that a strong space program can “stoke” the health of our economy. “Our economy” refers to the jobs that people have – the money that we have. “To stoke the health of our economy” would mean to improve our economy. So, he thinks that having a space exploration program will cause our economy to be stronger and healthier. There’s another use I should mention of the word “stoke” when you add a ‘d’ at the end and use the verb “to be.” You can say, “I am stoked,” or “She is stoked.” That means you’re really excited about something. You’re feeling a lot of energy. You’re ready to do something. “I’m very happy about something. I’m stoked about my trip to Las Vegas. I’m going to go and I’m going to win a lot of money.” Actually, I probably will lose a lot of money. But that’s the idea of being ‘stoked” with a ‘d’ at the end.
Neil says that “Now in the 21st century – the century we’re in right now, the hundred year period we’re in – science and technological innovation will define who leads the century and who does not.” “Innovations” (innovations) are new things, new ideas for developing and creating things. Over the past few years we’ve seen a lot of technological innovations, new ideas related to technology - computers and phones and that sort of thing. Neil says that “These kinds of technological innovations will define who leads the century and who does not.” “To define” means to decide, in this case. “To lead” means, of course, to be in first place. So, whoever, whatever country – Neil means – has the most technological innovation, will be the country that leads in this 21st century. Next, Neil talks about the “golden era of space exploration” in the United States. “The golden era” (era) describes a period of time when everything is wonderful, when it is the best that it has ever been. We sometimes also refer to this as the “golden age” (age) – “the golden age of Spanish literature,” or ‘the golden age of English technology.” Is there English technology? I don’t know. “The golden age of the Hollywood musical” – the kind of film where people sing and dance – these are all ways of describing a period of time when things are at their very best. Neil talks about the “golden era of space exploration” here in America. He says, “Even though space was driven by war, the consequence of that was a completely shifted outlook.”
So, we have to explain a little context here. Neil is describing the period during the 1960’s and the 1970’s when the United States had a very active space program – Apollo 11 going to the moon, having other Apollo spacecraft go up into space and to the moon, having or helping with the International Space Station in later years – all of this was part of the golden age or golden era of space exploration, when the U.S was going out into space and sending men and women up into space.
He says that in the 60’s and 70’s, this space exploration effort was “driven by war.” “To be driven” means here to be caused. He’s saying that it was the Cold War – I think this is what he means. The Cold War between the U.S and the then Soviet Union – the competition militarily, and politically between the U.S and the U.S.S.R – caused the U.S to invest more money into space exploration because, of course, the Russians were doing the same thing – the Soviets I should say. Neil is saying that even though that was the case – despite the fact – that it was driven by war, it still had a positive consequence – a positive result. And the result was that there was a completely shifted outlook. An “outlook” (outlook) – one word – is your perspective. It’s the way you view the world or view a situation. “To shift” (shift), as a verb, means to change – often from one direction to another. So, a shifted outlook would be a changed perspective – a changed way of looking at the world. And Neil believes that our space exploration program shifted the outlook of the entire country – the United States - about what was possible for our future. So, it gave us dreams about what was possible because of the ability to go up into space.
He said that “people who bring tomorrow into today are the scientists and technologist.” So, Neil is saying that it’s people like himself – isn’t that a coincidence? – scientists and technologists – people who develop technology, such as all of those folks up in Silicon Valley here in California where all of the big technology companies are – these are the people, Neil believes, who bring tomorrow into today – that is, they help us understand and make possible our future. Neil believes that he and others like him are the key to our future – our development as an economy and perhaps as a country. Neil has a very high opinion of himself.
Now let’s listen one more time to what Neil is saying.
[recording]
“Because it’s just that kind of adventure that stokes the health of our economy and in this, the 21st century, science and technological innovation will define who leads the century and who does not. What we have found in the golden era of space exploration here in America that even though space was driven by war, the consequence of that was a completely shifted outlook that the entire country had about what was possible for our future. And the people who bring tomorrow into today are the scientists and technologists.”
[end of recording]
Now let’s answer some of the questions you have sent to us.
Our first question comes from Alexey (Alexey) from Russia. So, maybe Alexey can give me a ride into outer space! Alexey has a question about three words – “point,” “period,” and “dot.” “Point” (point) can mean a couple of different things. As a verb it can mean to indicate a certain thing – often using your hand or your finger. “I want that one over there” – you point with your finger, you move your finger to indicate where it is you are talking about or what you are talking about I should say. “Point” as a noun can mean the end, or the tip of something. We can talk about the point of a pencil or a pen that you write with. It’s the very end of it – that can be the point. “The point” can also mean something completely different, which is an idea or a purpose or the goal, the aim, the reason you’re doing something. “What is the point of this lecture?” “What is the point of this book? What is it trying to say?” “What is its goal? What is its purpose?”
“Period” (period) is, again, a couple of different things. As a noun it can be used in talking about punctuation, to refer to the end of a sentence. It’s a little small round thing that you put at the end of a sentence to end the sentence. In British English it’s called “full stop.” “Period” can also be a length of time – a certain period of time, a certain length of time.
“Dot” (dot), as a noun, is a small mark. It’s something you would make with a pen or pencil – with a point of a pen or pencil. You could make a little small round circle and fill it in – that would be a dot. You can make a dot. In fact, that’s what you do when you write a period with a pen or a pencil. You make a little dot, you make a little small, round circle that goes at the end of a sentence, and you make that with the point of a pen or a pencil.
So, now you can see the connection between “point,” “period,” and “dot.” “Dot” can also be used to describe a larger circle but normally it’s a small circle that you would write with a pen or a pencil. “Dot” is also used in talking about web addresses, and I think here the confusion comes in between “period” and “dot.” For whatever reason, in English, when we talk about a web address, we use the word “dot” instead of “period.” I think the reason is that period implies or usually refers to the end of a sentence. But in a web address, there’s always something after that little “dot” so you can’t really call it a period. So, our website address is eslpod “dot” com (com). We would not say “period” because “period” would mean that’s the end and that you’re not going to say anything after that that’s connected directly with what is before that. I’m just guessing but I think that’s probably why in web addresses we use the word “dot,” or in email addresses. Our email address is eslpod@ - and that stands for the “at” sign which is a little “a” with a circle around it – eslpod “dot” com.
When I defined “point,” I didn’t mention the geometric definition – the definition we would use it geometry for a point and a line. There the point is kind of like the idea of a dot although mathematicians I’m sure would tell me I was wrong to define it that way. So, “point” at least in math and geometry has some relationship to what we’re talking about here when it comes to dots and periods.
Our next question is also from Russia – with love I’m sure – Sevyatoslav. How do you like my pronunciation for (Sevyatoslav)? I had to look that up on the Internet. You know, you can just put in Google “how to pronounce” and then somebody’s name and there are a couple of websites that will give you pronunciation of the name. Sometimes I do that, sometimes I forget. I apologize if I mispronounce your name here on the Café. I will try to do better at that here in 2012.
Anyway, “our friend from Russia” – we’ll call him – wants to know the use of the word “no.” He wants to know about how we use “no” in expressions such as, “Where the Streets Have No Name,” which is a song by the rock group U2, or another song “I Can’t Get No Satisfaction,” by The Rolling Stones. Why do we say, “no satisfaction,” or “no name.” Well, this is a question that refers to the use of the word “no” as an adjective to mean not any. “There are no reasons for you to be here.” Another way of saying that is: there does not exist any reason for you to be here – it’s a negation of the noun that follows. “There is no reason” means there is not any reason. If you say “The streets have no name,” you mean that they don’t have any names – the streets are nameless. In The Rolling Stones song, “I can’t Get No Satisfaction” – that’s the line in the song. I think the word is – the song is just called “Satisfaction.” Anyway, there – it’s a little different because the Stones are using informal English where, as you probably know, sometimes people use two negatives in a sentence and in most English sentence you only have one negative word. So, if you use the word “no” or “not” and then you use another negative word again, it has the opposite meaning. Correct grammar would say, “They can’t get any satisfaction,” or “They can get no satisfaction.” But The Rolling Stones speaking informally in English, or singing informally in English, say, “I can’t get no,” and you’ll hear that’s used as an informal way of saying, “I cannot get any,” or “I can get no satisfaction.” So they’re not getting any satisfaction, basically.
The reason the people sometimes use the “no” in front of the noun – as an adjective – can sometimes be related to poetic use of the language, and song writers are in some ways poets. So, they might use an expression like “The streets have no name” rather than saying, “There are no names for the streets,” or “The streets are nameless’ – all those things mean the same thing. But they don’t quite sound as interesting as the U2 song or The Rolling Stones song.
If you have a question, if you can’t get no satisfaction about your English vocabulary, email us. Our email address is eslpod@eslpod.com
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on The English Café.
ESL Podcast English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2012 by the Center for Educational Development.
Glossary
vehicle – automobile; car; any machine with a motor or engine that takes people and goods from one place to another
* Frank drives a small compact car, but he says his next vehicle will be a pickup truck.
astronaut – a person whose job is to fly in a space shuttle or other space vehicles
* Most astronauts have degrees in science and engineering.
orbit – the circular path of an object around another object
* How much fuel is required to launch a satellite into orbit?
to hitch a ride – to get a ride from someone; to be a passenger in a car or vehicle that someone else is driving, without paying that person any money
* Can I hitch a ride to work with you tomorrow?
to imply – to mean something without saying it directly; to have an indirect meaning
* What do you think she was implying when she said that?
to stoke – to make something bigger and stronger; to increase something
* Growing up in poverty stoked Rashad’s desire for a high-paying job.
innovation – the process of forming new ideas and creating new things
* Some companies believe that giving their employees gifts, flexible schedules, free food, and massages makes them more creative and encourages innovation.
golden era – a period of time when things were very good and there were many advances
* In your opinion, when was the golden era of rock music?
space exploration – the process of going into space and learning as much as possible about it
* Jan became interested in space exploration because she wants to know whether there is life on other planets.
driven by – motivated or influenced by something
* The kingdom’s collapse was driven by the ruler’s selfishness and greed.
to shift – to changed one’s position; to change the position of something; to move a short distance
* The little girl shifted in her seat at the theater during the entire performance.
outlook – a person’s point of view; one’s general attitude about life
* During the economic recession, economists observed a change in people’s outlook about education.
point – a sharp end; the tip of something
* Ouch! Do you have to use a needle with such a sharp point?
period – a punctuation mark that is used to end a sentence
* If you use too many exclamation marks, they lose their impact. Try using periods more often.
dot – a small mark; a small spot
* Without his glasses, Kryzstof can’t read anything. He just sees dots and lines, not letters and words.
all the same – anyway; nevertheless; even though
* This project will probably fail, but all the same, I’d like to try to make it work.
What Insiders Know
The Jetsons
The Jetsons was an “animated” (with drawings) TV show that “aired” (was shown on TV) from 1962-1963 and 1985-1987. It “portrayed” (showed) the daily life of the Jetson family living 100 years in the future, in the year 2062.
The family “comprises” (is made up of) George, Judy, their two children, a “robot” (a human-like machine) “maid” (a woman who cleans the house), and a talking dog. The 1985-1987 show added a few other characters, too. George works only three hours a day, three days a week. Many of the scenes “take place” (happen, occur) in his workplace, where he is often blamed for things that go wrong. His boss often says, “Jetson, you’re fired!” but George always gets his job back by the end of the episode.
The Jetson family lives in an apartment built on an “adjustable” (able to be changed) “column” (a vertical structure that supports weight). They enjoy many “labor-saving devices” (machines designed to do work for humans, like washing machines and dishwashers) and live a life of “leisure” (play, not work). The devices often “fail to” (do not) work correctly, and that is often the basis of the humor in episodes. The family travels in an “aerocar,” which has a glass bubble top and flies through the air instead of being driven on a road.
The television series has been adapted into many “comic books” (books with many pictures and few words), video games, and films. It has also been adapted for other cultures and translated into other languages.
In many ways, the series now seems “quaint” (old-fashioned, but in a nice, attractive way), but it provides an interesting “glimpse” (quick view) of what people in the 1960s expected to see in the future.