= 0754
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 754: Being in a Flood.
This is English as a Second Language Podcast episode 754. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there, download the Learning Guide, and improve your English faster than ever.
This episode is called “Being in a Flood.” A “flood” is when there is too much water; the river has too much water and it goes beyond the river. Let’s get started.
[start of dialogue]
Cherise: Well, that was a rude awakening at 2:00 in the morning!
Don: At least we got out of our room before it flooded. It serves us right for planning a vacation here during the rainy season. Our luggage is probably soaked.
Cherise: Oh, no, I’d forgotten about our clothes. If the water doesn’t recede soon, everything will have mold and mildew on it.
Don: The sump pumps are working as we speak. Hopefully, we can retrieve our stuff soon.
Cherise: Maybe I should go downstairs and try to salvage what I can, before things get washed away.
Don: What?! You could drown in all that water. Forget it!
Cherise: Drown in three feet of water? Don’t be silly.
Don: I’ve seen you swim. Come on, let’s just wait until we get the go-ahead.
Cherise: I still think I should try.
Don: I have one word for you: snakes.
Cherise: Enough said!
[end of dialogue]
Cherise begins by saying, “Well, that was a rude awakening at 2:00 in the morning!” “To be awakened” means to be woken up, so an “awakening” is when you are sleeping and then you wake up. A “rude awakening” would be an awakening that was very sudden, because of a loud noise perhaps. Cherise says that she received a rude awakening at 2:00 in the morning – two a.m.
Don says, “At least we got out of our room before it flooded.” “To flood” (flood), as a verb, is when a building or an area is suddenly covered with water when it isn’t supposed to be. So if a river, for example, has too much water, it may flood the areas around the river. “To be flooded” is to be in the condition of having too much water. Don says, “It serves us right for planning a vacation here during the rainy season.” The expression “to serve (someone) right” means to get what you deserve, because of your own actions you should have expected something bad to happen. So, someone is talking on a cell phone while driving a car and suddenly they aren’t paying attention and they hit another car, we might say, “Well, that serves them right.” They should have known, but because of their own actions something bad happened to them – not to mention the other car!
Well, Don and Cherise planned a vacation somewhere during the “rainy season,” the time of year when it rains a lot, which of course will be different in different places. Los Angeles has something of a rainy season in the winter and early spring, not very much however. Don says that our “luggage” – our baggage, the things we use to put our clothes in – he says, “Our luggage is probably soaked.” “To be soaked” (soaked) is to be very wet. We might also use the term “drenched” (drenched); it’s completely full of water. If you walk out into the rain, and you have your clothing on, you will probably get soaked; your clothes will all be very wet. That’s what Don is talking about; he says, “Our luggage is probably soaked.”
Cherise says, “Oh, no, I’d forgotten about our clothes (our clothing). If the water doesn’t recede soon, everything will have mold and mildew on it.” “To recede” (recede) means for something to go back, to move backwards. If the water receded, the water will go back to where it belongs. So if a river floods, and then the water recedes, the water goes away from the places where it shouldn’t have been back into the river. You can talk about someone’s hairline receding, especially a man. Your “hairline” is where you still have hair on your head; the line, if you will, that separates the hair from the skin, the part of your head that doesn’t have hair. If you have a receding hairline that means you’re losing your hair; you have less and less of it every year. Though, they say men with receding hairlines are more intelligent than other men – I’m not really sure!
Cherise is worried that the clothes will have mold and mildew on them. “Mold” (mold) are actually very small plants that grow on objects that are a little bit wet – we would say “damp” (damp) – often food or some objects. They are green and black typically in color; sometimes mold will have a certain unpleasant smell. Mold, especially on things in your house, is almost always a bad thing. “Mildew” (mildew) are also very small plants, like mold. Usually they’re either white or green; they’re very similar to mold. Normally we associate mildew with clothing. So, if clothing gets wet and then it stays that way for a long time – it’s in a closet or some other place that’s damp, that’s slightly wet – it may become mildewed and you can’t really wear it anymore, it has a certain smell to it that you don’t want to have on your body.
Don says that the sump pumps are working as we speak. A “sump (sump) pump (pump)” is a special machine that is used to remove water, for example, from the bottom of a building or a house, from the “basement,” the floor below the ground. If you get a lot of water in your house you may need one of these sump pumps to get rid of the water. Don says, “The sump pumps are working as we speak.” The expression “as we speak” means right now, at this very moment. Don says, “Hopefully (we hope), we can retrieve our stuff soon.” “To retrieve” (retrieve) means to go somewhere and get something and bring it back. “I left my wallet on my desk at work. I need to go back and retrieve it.” To get it back, to bring it back to where I am now.
Cherise says, “Maybe I should go downstairs and try to salvage what I can, before things get washed away.” “To salvage” (salvage) means to save what can be saved from a group of things that otherwise are being destroyed or will be destroyed soon because of rain, or floods, or whatever. I’m going to try to salvage, I’m going to try to take what I can save and get rid of the rest. Cherise wants to salvage their luggage “before things get washed away.” “Washed away” would mean taken away by the water, the water that is part of the flood in this case.
Don says, “What?! You could drown in all of that water.” “To drown” (drown) means to die while you are underwater. The water fills up your lungs, you cannot breathe, and so you die. That is “to drown.” Don says, “Forget it!” Cherise says, “Drown in three feet of water? Don’t be silly.” She’s saying that the water is only three feet high and therefore she won’t drown, so she’s telling Don that he is wrong. She says, “Don’t be silly.” Don says, “I’ve seen you swim. Come on, let’s just wait until we get the go-ahead.” The “go-ahead” is a way of saying approval, when someone in authority says, “yes, you can do that.” Don is waiting for the authorities to say it’s okay for them to go back downstairs and look at their stuff – try to salvage their stuff.
But Cherise wants to go; she says, “I still think I should try.” Don says, “I have one word for you: snakes.” A “snake” (snake) is a long animal that doesn’t have any legs; it moves around on the ground. It can sometimes bite you, and it has, sometimes, poison that can kill you. Don uses an expression we sometimes use in English for emphasis; to get someone’s attention we say, “I have one word for you,” and that one word will explain everything. In this case, the word is “snakes.” Obviously Cherise is scared or frightened of snakes. She responds by saying, “Enough said!” The phrase “enough said” shows that you have heard what the person has said, and you agree or understand it completely so the other person doesn’t have to say any more. I get it; I understand, there are snakes downstairs. Why? I…I’m not really sure, but there are snakes downstairs and I don’t like snakes, therefore I am not going downstairs.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Cherise: Well, that was a rude awakening at 2:00 in the morning!
Don: At least we got out of our room before it flooded. It serves us right for planning a vacation here during the rainy season. Our luggage is probably soaked.
Cherise: Oh, no, I’d forgotten about our clothes. If the water doesn’t recede soon, everything will have mold and mildew on it.
Don: The sump pumps are working as we speak. Hopefully, we can retrieve our stuff soon.
Cherise: Maybe I should go downstairs and try to salvage what I can, before things get washed away.
Don: What?! You could drown in all that water. Forget it!
Cherise: Drown in three feet of water? Don’t be silly.
Don: I’ve seen you swim. Come on, let’s just wait until we get the go-ahead.
Cherise: I still think I should try.
Don: I have one word for you: snakes.
Cherise: Enough said!
[end of dialogue]
Our scriptwriter is writing wonderful scripts as we speak; that’s the hard-working Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
rude awakening – an abrupt, unexpected, and unpleasant way to wake up, usually by a loud noise; an unpleasant and sudden surprise
* When the fire alarm went off in our apartment building, it was a rude awakening.
to flood – for a building or area to be covered in water
* This area floods almost every year after the heavy spring rainfall.
to serve (someone) right – for someone to get what he or she deserved or should have expected; a phrase used after something bad happens, but one probably should have known that bad thing would happen
* Tom’s car stereo was stolen, but it serves him right for buying such an expensive stereo and then leaving his car door unlocked on the street all night.
rainy season – the time of year when there is a lot of rain in a particular area
* During the rainy season, it rains almost every afternoon between 2:00 and 5:00.
soaked – very wet; drenched; with a lot of water having been absorbed by something
* If you walk outside without an umbrella or a rain jacket right now, you’ll be soaked within seconds!
to recede – for something to move backwards and get further away or even disappear
* Wendy likes to think near the ocean, watching the waves come in and recede.
mold – very small plants that grow on damp (slightly wet) objects or food, usually green or black, and sometimes with an unpleasant odor
* How long has this bread been in the fridge? It’s covered in mold.
mildew – very small plants that grow on damp (slightly wet) objects or food, usually white or slightly green
* That shower is disgusting, covered with soap scum and mildew.
sump pump – a machine that uses a hose to remove water from an area, especially from the bottom floor of a home or office
* In places where flooding is common, many homeowners own sump pumps to protect their property.
as we speak – happening right now, as we are talking about it
* As we speak, hundreds of babies are being born each minute around the world.
to retrieve – to go somewhere, get something, and bring it back
* When Jenna’s wedding ring was washed down the sink, a plumber had to use a special tool to retrieve it.
to salvage – to save what can be saved from a group of objects that have been destroyed or damaged
* Do you think we’ll be able to salvage any of these photographs from the fire?
washed away – taken away by water that is flowing (moving) very quickly
* People watched in horror as the river washed away their homes.
to drown – to die while underwater, when water fills a person’s lungs
* Kuon would have drowned if he hadn’t been such a strong swimmer.
go-ahead – approval to have or to do something
* Did you hear? The boss gave us the go-ahead to start the new program!
snake – a long animal that does not have legs and moves along the ground, with long teeth, the ability to eat larger animals without chewing them, and sometimes with a poisonous bite
* Have you ever seen a snake eat a whole mouse? How can they eat such big things?
enough said – a phrase used to show that one has heard what another person says and agrees with it or understands it, so the other person does not have to continue talking about it or explaining it
* - Natural childbirth is the most painful experience in the world.
* - Enough said! I’m never having a baby!
Comprehension Questions
1. What does Cherise think will happen to their clothes?
a) The colors will fade.
b) They’ll be stolen.
c) They’ll be ruined.
2. According to Don, what is happening right now?
a) The water level is rising.
b) Hotel workers are trying to bring them their luggage.
c) Machines are being used to remove the water.
Answers at bottom.
What Else Does It Mean?
soaked
The word “soaked,” in this podcast, means very wet or drenched: “The carpet is soaked with red wine. How will we remove the stain?” As a verb, “to soak (something)” means to put something in a liquid so that it absorbs a lot of that liquid or becomes softer: “That pan will be easier to wash if you soak it in hot, soapy water for a few minutes.” Or, “Try soaking the bran in milk before you add it to the rest of the ingredients.” The phrase “to soak (something) off” means to remove something or take something off by putting it under water for a period of time: “Craig wants to soak the stamps off that envelope to add them to his stamp collection.” Finally, the phrase “to be soaked (in) something” can mean to have some characteristic or quality: “Her poetry is soaked with emotion.”
go-ahead
In this podcast, a “go-ahead” is approval to have or to do something: “Marshall’s parents gave him the go-ahead to drive their car on Friday.” Or, “The city finally gave them the go-ahead to begin construction.” The phrase “to go ahead with (something)” means to do something that one had planned to do, even though there is a problem: “I’ll be a little late, but go ahead with the meeting without me.” The phrase “to get ahead” means to be successful or have some advantage, especially financially: “Sayid is working two jobs to try to get ahead.” The phrase “ahead of the game” describes a superior person or company that has some advantage over others: “Karina is trying to get her language skills certified so that she can be ahead of the game when she applies for jobs.”
Culture Note
Biggest U.S. Floods
Most people are “familiar with” (have seen) images from the “horrific” (terrible; awful) flooding caused in and around New Orleans, Louisiana by Hurricane Katrina in 2005. But there have been many other large, “devastating” (causing a lot of damage and/or death) floods in the United States. These major floods have been devastating for communities in terms of “property loss” (destroyed buildings and farms) and deaths.
The “deadliest” (causing the greatest number of deaths) flood in U.S. history, “excluding” (not including; not considering) floods caused by “hurricanes” (a storm that moves over water with very fast winds) was the Johnstown Flood. It “occurred” (happened) on May 31st, 1889 in Johnstown, Pennsylvania. Heavy rain “led to” (caused) the “collapse” (when a building falls apart and falls down) of a “dam” (a large structure built to hold back the water in a river), killing 2,200 people.
The second-deadliest non-hurricane flood occurred in January and February, 1937; 1,100 people died and 75,000 homes were “destroyed” (ruined) when the Mississippi River “overflowed” (water went over the top of whatever was holding it) its “banks” (the dirt sides of a river).
The third-deadliest flood occurred in March, 1913, when the Ohio River flooded, killing 700 people. The government responded by creating the nation’s first “flood control programs” (programs designed to control and prevent flooding, often by building dams and/or controlling where people can build things).
Finally, the fourth-deadliest flood occurred in Santa Paula, California on March 12th, 1928. Flooding caused the St. Francis Dam to collapse and 450 people died as a result.
Comprehension Answers
1 - c
2 - c