= 1422
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 117.
This is the English Café episode 117. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download the Learning Guide for this episode. You can also take a look at our ESL Podcast Blog and our ESL Podcast Store, which has some additional specialized courses in daily and Business English.
On this Café, we’re going to talk about traveling in the United States for business. We’re going to interview someone who used to travel a lot for his work; we’ll talk about some of his experiences doing that. That’s part of our Ask an American series that we do every month or so. We’ll also, of course, answer some of your questions. Let’s get started.
On this episode, we have another Ask an American segment, where we talk to a native speaker who speaks at a normal speed, and we listen to them, go back and explain what they said, and listen to them again. The topic for today’s Ask an American is traveling in the United States, especially business travel. We’re going to interview Kevin, who travels – or used to travel a lot for his job. You may remember Kevin from English Café number 95, were he talked about how he got his “Master’s in Business Administration,” or M.B.A.
In this episode, he’s going to talk about his experiences traveling. He’s going to start by talking about his travel schedule, how long he would have to go on a trip, where he went, and what he did there. Let’s listen
[recording]
I used to travel from Sunday to Friday; leave Sunday morning, come back Friday evening. Um, just work all day where ever the location was that I was working at. Um, typically back then it was, ah, our data centers, so I would travel to these remote places when they have our data centers, um, and work out of those offices.
[end of recording]
Kevin speaks quickly, but let’s go back and listen again to what he said. He said, “I used to travel (meaning in the past I frequently traveled) from Sunday to Friday,” leaving “Sunday morning, come back Friday evening.” Now, of course, when we speak in normal conversation, we don’t always have what we would call “complete sentences”; it’s very common. You will also notice that there are a lot of what we call “filler words” in normal conversation. A “filler (filler) word” is a word we use when we are thinking about what we are going to say. Kevin uses “um” and “ah,” those sounds when he’s thinking about what to say next.
So, he says he “used to travel from Sunday to Friday; leave Sunday morning,” and “come back” (return to his house) on Friday evening. “Just work all day,” he said, “where ever the location was that I was working at,” meaning he would work the entire day at the place where he was sent to work. “Typically,” he says, meaning usually, “back then (back at the time when I used to travel) it was our data centers.” A “data center” is where computer companies have their computers that have important information on them. Kevin would travel to these data centers; he would have to “travel to these remote places.” Somewhere that is “remote” (remote) means not close to anything else – not close to a big city, for example.
Well, Kevin would travel to these remote places where they had their data centers, “and work out of those offices.” “To work out of a place” is a phrasal verb, which means to work in a certain location. Some people say, “I work out of my home,” meaning they work in their home, that’s the place they work. Someone else may say, “I work out of the office in San Francisco” – that’s the place where I work, in San Francisco. Let’s listen to Kevin again.
[recording]
I used to travel from Sunday to Friday; leave Sunday morning, come back Friday evening. Um, just work all day where ever the location was that I was working at. Um, typically back then it was, ah, our data centers, so I would travel to these remote places when they have our data centers, um, and work out of those offices.
[end of recording]
Next Kevin is going to talk about the differences in traveling before 9/11 – before September 11, 2001, when the World Trade Center in New York, among other places, was attacked, and what happened after September 11, 2001 – the change in flying in the United States. Let’s take a listen.
[recording]
Um, but the – the different experiences came before 9/11 and after 9/11. Before 9/11 was – it was awesome. Flying was great. I loved flying. Planes weren’t very full. You could get through a security line in 30 seconds. You didn’t have to undress. You didn’t have to unpack your bags and show them every little thing that you had. So, you know, travel was cool.
[end of recording]
Kevin begins by saying, “but the different experiences came before 9/11 and after 9/11. Before 9/11,” he says, “it was awesome.” The word “awesome” (awesome) means, in this case, it was great. It’s a word that was more popular in the 80s and the 90s, but it’s still used. If someone says, “that’s awesome,” they mean that’s fantastic. In Great Britain, they may say, “that’s brilliant.”
Kevin says, “Flying was great. I loved flying. Planes weren’t very full (the planes didn’t have a lot of people on them – they weren’t very full). You could get through a security line in 30 seconds.” “To get through” something is a phrasal verb meaning you could move through – you would not spend very much time in. “To get through the security line” means you would only be in the security line for that amount of time. Kevin says it used to take 30 seconds to get through a “security line,” the place where they check you and make sure that you’re not carrying anything dangerous on the plane.
He says, “You didn’t have to undress,” meaning take parts of your clothes off. “You didn’t have to unpack your bags,” meaning take things out of your luggage to show the security officers. “You didn’t have to show them (the security officers) every little thing that you had.” Notice he says “every little thing,” this is just another way of emphasizing, when you say “little” here, meaning every single thing – everything that is in your bag: “every little thing.”
He says, “So, you know, travel was cool.” We use “you know” as a way of getting people to agree with us, or to make sure they understand us. To say “travel was cool” is similar to saying it was “awesome” – it was good, it was fun. I use to travel lot myself, before 9/11/2001, and I know what Kevin is talking about. It’s true, travel was much, much easier, much more enjoyable before that time. Let’s listen to Kevin again.
[recording]
Um, but the – the different experiences came before 9/11 and after 9/11. Before 9/11 was – it was awesome. Flying was great. I loved flying. Planes weren’t very full. You could get through a security line in 30 seconds. You didn’t have to undress. You didn’t have to unpack your bags and show them every little thing that you had. So, you know, travel was cool.
[end of recording]
Now Kevin is going to talk about travel after 9/11, what he thinks about traveling, the reasons he doesn’t like to travel anymore. He’s going to talk about what you have to do now, when you go to an American airport and go through security. He’s also going to talk about his own little tricks when he travels. Let’s listen.
[recording]
Of course, after 9/11 it’s become a major pain. It’s just I hate traveling now. As much as possible, I try to avoid it ’cause I – you know, I don’t wear slippers to the (laughs) to the airport, so I have to take off my shoes. Ah, if they see that I have a belt on, I have to take off my belt. But I usually untuck my shirt so they don’t see it, ’cause it doesn’t – you know it doesn’t beep – it never beeps! (Jeff laughs) But, if they see it, they make me take it off. Yeah, so it’s just a real – it’s a real trial now to travel, and that’s why I try to keep it to a minimum.
[end of recording]
Kevin says, “Of course, after 9/11 it’s become a major pain” – air travel has “become a major pain.” When we say something is a “pain,” in this instance we mean it’s very inconvenient; it’s not pleasant. The use of the word “major” here is like the use of the word “very.” “It is very much a pain” – it is a big pain. So “major” here means big, large, something that will cause a lot of problems in this case: “a major pain.”
He says, “It’s just I hate traveling now.” We use that expression “it’s just” or “it’s just that” to mean here is what I’m trying to say, this is the most important thing. “It’s just that I hate traveling now. As much as possible, I try to avoid it” – I try not to travel. He then says, “you know, I don’t wear slippers to the airport.” “Slippers” (slippers) are things that you put on your feet. They are shoes that you don’t have to tie; they are shoes that you can just put on and take off very easily. Normally, we talk about slippers, we talk about the kinds of shoes that you wear only in your house.
Kevin says that he wears regular shoes, so he has to take them off. At most American airports when you go through security, you have to remove your shoes, and the shoes have to go through the X-ray machine. Kevin says, “if they (the security officers) see that I have a belt on, I have to take off my belt.” Again, this is true. If you have a metal belt, especially a metal belt buckle – the “buckle” is the part of the belt in front that connects the belt together – you have to often take it off and put it through the X-ray machine.
Kevin has his own little trick, however. He says, “I usually untuck my shirt so that they don’t see it.” “To tuck (tuck) your shirt in” means that, for a man in particular, you take the shirt and you put the bottom of the shirt inside your pants. So, “to untuck” your shirt is to pull your shirt out. In this case, Kevin pulls the shirt out so that they can’t see his belt buckle. He says, “’cause it doesn’t – you know, it doesn’t beep.” “B-E-E-P” means it doesn’t make a certain sound. “To beep” would be, for example, “beep beep beep beep beep beep,” that might be the sound that the security machine makes in the airport if it detects metal – some sort of metal on your body or that you are carrying something in your pocket. What Kevin is saying here is that he covers up his belt because he knows that it’s not going to make the “metal detector,” the machine that you find in the airport that you have to walk through before you can get on your plane, it doesn’t detect – it doesn’t pick up his belt.
You hear me laughing in the background, of course because this is sort of a strange thing to do, try to hide something from the security officers. He says, “it never beeps! But, if they see it, they make me take it off.” He finishes by saying, “Yeah, so it’s a real trial now to travel.” When you say something is a “trial,” in this instance – in this case, we mean that it’s a difficult thing to do, it’s a difficult experience. “That’s why” Kevin says, “I try to keep it to a minimum.” “To keep something to a minimum” means to do it as little as possible – the least amount possible. You could also say, for example, “Let’s keep the noise to a minimum,” meaning let’s be quiet, let’s not be shouting. You may say that to a group of students or a group of children, or a group of politicians – it’s all the same! Let’s listen to Kevin once more.
[recording]
Of course, after 9/11 it’s become a major pain. It’s just I hate traveling now. As much as possible, I try to avoid it ’cause I – you know, I don’t wear slippers to the (laughs) to the airport, so I have to take off my shoes. Ah, if they see that I have a belt on, I have to take off my belt. But I usually untuck my shirt so they don’t see it, ’cause it doesn’t – you know it doesn’t beep – it never beeps! (Jeff laughs) But, if they see it, they make me take it off. Yeah, so it’s just a real – it’s a real trial now to travel, and that’s why I try to keep it to a minimum.
[end of recording]
Thanks to Kevin for sitting down and having that short interview with us about how it is to travel for business now in the United States.
Now let’s answer a few of your questions.
Our first question comes from Jehudi (Jehudi) in Columbia. Jehudi wants to know the meaning of the expression “bang for your buck.”
“Bang (bang) for your buck” is used when we’re talking about how much you get from whatever you’re buying - whatever you’re purchasing. Are you getting a good value? Are you getting a lot for your money? If you say, “This car gives you a lot of bang for your buck,” we mean that you are getting a lot from this car compared to what you are paying for it. Your money, in other words, is well spent; you’re getting a good deal, a good value from your purchase. A “buck” is, you may know, slang for a dollar. The word “bang” usually describes a loud sound. So here, we’re talking about getting a lot of something from your money. For example: “I only have 30 dollars to spend on some new shoes, so I’m looking for a good bang for my buck” – something that’s good quality and looks nice, but isn’t too expensive. Not easy to do!
Our next question comes from Crane (Crane) in China. Crane has a question about the difference between “original” and “initial.”
Many times these two words mean the same thing; they mean something at the beginning, the first thing of something. For example: “My initial impression of him was that he was lazy.” “My initial impression” – my first impression, what I first thought of him. You could also say, “My original impression of him was that he was lazy.” You could say, “My original plan was to move our office to Miami, but I changed my mind.” You could also say, “My initial plan was to move our offices to Miami, but I’ve changed my mind.” Both of them mean the first thing – the first idea.
There are some differences, however. “Original” is used when we are talking about something that was used, produced, or present at the beginning of something. For example, if you are talking about a car, you can talk about the “original tires,” those are the tires that came with the car when you bought it – the first tires – but we wouldn’t say the “initial tires.” “Initial” is used more to talk about something that existed or occurred at the beginning of something. For example, my initial idea was to record today’s podcast while sitting in a café, but then I changed my mind and I had another idea – a better idea.
We also use the word “original” to meet authentic or real. For example: “Do you think this painting is an original Picasso?” – is it a real Picasso painting? “Original” is also used to describe ideas that are not like anyone else’s, that are not dependent on other people’s ideas, that are unique. “Her ideas are the most original I’ve ever seen” – she’s the most unique, it’s not like anyone else. You can’t use “initial” for either of those meanings.
“Initial” also has an additional meaning, which is the first letter of your first and last name. For example, my initials are J. M. – Jeff McQuillan. You can also use “initial” as a verb. When you sign a contract – an agreement – for a rental car, they will ask you to initial the contract in several places. That means you will write your initials – the first letter of your first name and the first letter of your last name – instead of your entire signature. If they want your full name, they’ll say “sign this,” but if they say “initial this,” they just want the first letters of your first and last name.
Finally, Jason (Jason) from China wants to know what the longest English word is, how to pronounce it, and how to spell it. Well, that’s an interesting question. Most native speakers are taught in school – at least I was – that the longest word in English is “antidisestablishmentarianism.”
“Antidisestablishmentarianism” was a movement – a political movement in the 19th century that “opposed,” or was against separating the church from the government, especially in the case of Ireland, which was, in the 19th century, part of Great Britain. There was a movement to disestablish the Church of Ireland, the official Anglican Church in Ireland. “To disestablish” would mean to say it’s no longer the official church. In many European countries especially, there is, or use to be an official church that the government would support.
So, in Ireland, because it was a largely Catholic country, there was a movement to get rid of the official “sanction,” the official support of the Anglican Church, where antidisestablishmentarians and their belief was called “antidisestablishmentarianism.” Putting the letters “ism” at the end of a word usually means it has to do with your system of beliefs about something.
Well, antidisestablishmentarianism is 28 letters long; you can look at the website or our Learning Guide to see it written. You could, of course, even make this word longer by adding “suffixes,” things at the end. For example, “antidisestablishmentarianistically” would be the adverb that you could form. English, like many languages, is one where you can add things before the word and after the word – prefixes before, suffixes after – to change the meaning of the word and, of course, to make it longer, if that is what you desire.
There are actually longer words in most major English dictionaries, however. The Oxford English Dictionary has a word that is thirty letters long; it is “pseudopseudohypoparathyroidism.” This is a medical term; I have no idea what it means! There’s an even longer word, a 45 letter word that refers a lung disease that you get by “inhaling,” or breathing in a certain substance – a certain particle near a volcano. The particle, the little thing that you’re breathing into your lungs is called “silica.” But the entire word is almost unpronounceable, at least by me; I will try. The word actually consists of a number of other words put together. The words inside of this word are “pneumono,” which has to do with your lung; “ultra,” which means very – “ultramicroscopic” means very small, something you could only see with a microscope. It also contains the word “silica,” meaning the silica particle; it contains part of the word “volcano” as well. So, here is how it is – I think – pronounced: “pneumonoultramicroscopicsilicovolcanokoniosis.” Easy, right?
If you have a question for the English Café, something a little easier, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2007, by the Center for Educational Development.
Glossary
remote – distant; far away; not near; not close
* He works in a remote part of the state that is an eight-hour drive from the nearest city.
awesome – great; wonderful; cool; impressive
* You can enjoy an awesome view of Mt. Jefferson from Jeff Park.
to work out of (somewhere) – to work from a particular location; to be based in a certain city or place
* Peter works out of Minneapolis, but he often travels to Houston for business meetings.
cool – awesome; great; wonderful; impressive
* Wouldn’t it be cool to be able to travel to Mars?
a major pain – something that is very unpleasant and/or difficult to do
* Paying taxes is a major pain, but we all have to do it.
slippers – soft, big, warm, comfortable shoes that are worn inside the house
* As soon as she comes home from work, she takes off her high-heeled shoes and puts on her comfortable pink slippers.
to tuck/untuck – to put the edges of a piece of fabric or paper inside/outside something else so that they look ordered/disordered
* Your shirt is untucked in the back. Please tuck it into your pants.
to beep – to make an electronic, high-pitched sound for a short period of time
* Do you set your alarm clock to beep in the morning, or to play the radio?
trial – a difficult experience; a difficult situation that tests one’s patience and abilities
* Their first year of marriage was a trial and they fought all the time, but they have worked out their differences and now they have been married for almost 15 years.
to keep (something) to a minimum – to maintain something at a low level; to not let something grow and become bigger
* Could you please keep the noise to a minimum? I’m trying to sleep.
bang for (one’s) buck – the value that one receives for the money, time, or effort that one has spent on something; the results after one has spent money, time, or effort on something
* You’ll get more bang for your buck if you buy a new computer when the store is having a good sale.
original – existing at the beginning of a process or time period
* This is the original wallpaper that was put on the walls when the house was built in 1847.
initial – first; at the beginning
* Our initial cost estimate for fixing the car was $2,000, but now we know that it’s going to be even more expensive.
antidisestablishmentarianism – a political position where one doesn’t want the government to stop recognizing a church
* People who believed in antidisestablishmentarianism wanted the Church of England to continue to be England’s official state church.
pneumonoultramicroscopicsilicovolcanokoniosis – the longest word in English, meaning a lung disease that people get when they breathe a certain type of dust from volcanoes
* The volcano explorer got pneumonoultramicroscopicsilicovolcanokoniosis and almost died.
What Insiders Know
Airport Codes
A “code” is a system of words, letters, numbers, and symbols that are used to represent other words and ideas, often to send secret messages. An “airport code” is a short code that is used to identify airports.
There are two international systems of airport codes. One system is “known as” (called) the “IATA airport code,” where “IATA” is an “acronym” (a word where each letter is the first letter of another word) for the International Air Transport Association. Each IATA airport code has three letters and these codes are “familiar” (recognizable and understandable) to “the public” (normal people who aren’t part of a specific industry or organization). The other system is known as the “ICAO airport code,” where ICAO is an acronym for the International Civil Aviation Organization. Each ICAO code has four letters, and although these codes aren’t very familiar to the public, they are used more commonly internationally.
People need to enter IATA codes when they make “reservations” (arrangements to use a service at a specific time in the future) or buy airline tickets online. They have to enter the three-“digit” (number or letter) codes for the airports that they wish to fly from and to. IATA airport codes are also printed on “baggage tags” (the stickers that are placed on airline passengers’ luggage so that workers know which plane the suitcases need to be put on, and when).
The ICAO codes, which are less familiar to the public, are used for more technical purposes. For example, “air traffic controllers” (people who give instructions about how and where planes should move in the sky) and airline “flight planners” (people who decide when and how often planes should fly on certain routes) use the four-digit ICAO airport codes.
Here are a few IATA airport codes for popular U.S. airports. Some major cities have more than one airport, but we’ve just included one as an example:
CityAirport Code
Los Angeles LAX (Los Angeles International Airport
New York JFK (John F. Kennedy Airport)
Chicago ORD (O’Hare Airport)
Philadelphia PHL
Atlanta ATL