= 1425
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 120.
This is the English Café episode 120. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download a Learning Guide for this episode, an 8 to 10 page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, which has some additional premium courses you might be interested in.
In this Café, we’re going to talk about a recent study I read about in the newspaper, a research study about how blondes can make men stupid. We’re also going to talk about a famous organization in the United States called the “Rotary Club,” what it is and who belongs to it. As always, we’ll answer a few of your questions. Let’s get started.
Our first topic is a story that I read in the newspaper a few weeks ago. This was a story that appeared in The Wall Street Journal newspaper, the financial newspaper in the United States – the largest financial newspaper. It’s actually about a story that appeared in another newspaper, The Sunday Times of London.
The name of the “headline,” the title of the story is “Blondes might be smart, but they make men dumb.” Apparently, there was a study – a research scientific study published in The Journal of Experimental Psychology, which discovered that when men are “in the presence of” – meaning they’re in the same room or they’re looking at pictures of a woman who is “blonde,” who has light yellow hair – that they become more stupid.
What they did in this study is they showed men pictures of blonde women – and of women with dark hair, I’m guessing – and they, after showing them the pictures, tested them – gave them a mental test to see how well they could perform, and they found that when they looked at the pictures of the blonde women their scores fell. When we say the “scores fall,” we mean they decline; you could also say they “drop” (drop).
According to the author of the study, a Professor Meyer at the University of Paris (Meyer), the men in the study (quote) “mimic the unconscious stereotype of the dumb blonde” (unquote). “To mimic” (mimic) means to copy or to behave like someone else is behaving. So, when he says the men “mimic the unconscious stereotype,” he’s saying that they behave just like this idea – this stereotype that men have of blondes, or that people have of blonde women. When we say something is a “stereotype,” we mean that everyone thinks it’s true, or many people think it’s true, but it isn’t necessarily true; it’s not necessarily based on any fact. Stereotypes are usually wrong, and they’re considered a negative thing. When someone says there are stereotypes about this type of person – this group of people, it’s usually a negative association, some sort of negative characteristic. Well, for blonde women there is a negative stereotype, a stereotype that they are not very intelligent. In fact, there are lots of jokes about blondes called “dumb blonde jokes.”
Well, what happened in this study is that the men did worse on these mental tests after they saw pictures of blonde women, and the reason is because the men seemed to be reacting to the stereotype: because the women are blonde, they behave differently. I’m not sure if this is true or not – certainly it is not true that all blondes are stupid, or even most blondes are any stupider or dumber than any other hair color – but it does talk about the importance of stereotypes and how they affect your behavior. If you think a certain thing about a different group, you may behave differently toward that group. For example other studies, scientific research has found that when people talk to the “elderly,” that is, people who are older, they tend to talk more slowly and walk more slowly, even though many elderly – many older people can understand just fine, can walk at a normal speed.
There are some cases where you do want to change your behavior. If you are talking to someone who doesn’t speak your language very well, you may slow down, use easier vocabulary. That’s not a stereotype, that’s what you might call an “accommodation” to help that person, because it really is true they will understand better if you slow down. However, many people use this stereotype incorrectly when they see someone – especially here in the United States – who looks different – who perhaps isn’t white, who looks like they might be from another country – many people assume that they don’t speak English well, and so they start behaving differently. Of course, you cannot make assumptions about people’s English proficiency based on how they look.
This whole notion of stereotypes and how it affects behavior is very interesting, and there’s been several studies about this topic in the research. This is the point where I would tell a joke, a dumb blonde joke, but I’m not going to because I don’t want to perpetuate the stereotype. “To perpetuate” means to continue, to make stronger the stereotype, to tell other people so that it continues in the future. Instead, I will tell bald jokes – jokes about men who don’t have hair, blonde or otherwise!
Our next topic is a national organization – an international organization called the “Rotary Club.” There are Rotary Clubs all over the world; they are considered to be the first what we would call in English “service clubs.” A “service club” is an organization that gets together and tries to do good things for other members of the community. There are many different kinds of clubs that do this; there’s also something called the “Elks Club,” there are religiously connected organizations such as the Knights of Columbus. All of these service organizations try to provide some sort of humanitarian service. When we say something is “humanitarian,” we mean you are trying to help other people, help others do better.
The Rotary Club got started back in 1905, in Chicago. It was originally just three people: a lawyer and a couple of businessmen. The reason they called it the “Rotary Club” is because each week they would meet to talk and to plan and to have a meal – lunch, dinner, breakfast – and they would meet at a different person’s office each week; they “rotated” offices. “To rotate” means to move from one to another and then back, so this was called the “Rotary Club.”
The Rotary Club was historically a business and professional club; they were business and professional leaders who became members of the Rotary Club. Traditionally it wasn’t something that, for example, someone who was working as a mechanic, or someone who was not a businessperson or a professional person would join, but that’s changed over the years. The Rotary Club was also an all-male organization – just men – until the 1980s, when it decided to start accepting women as part of its organization.
The motto (motto) of the Rotary Club is “Service Above Self.” A “motto” is the way that you describe your organization; usually it has some sort of connection to your goals or your objectives. The Rotary Club’s motto is “Service (helping others) Above Self,” meaning it’s more important to help others than to help yourself.
What sort of things does the Rotary Club do in most cities and states? Well, they have a couple of popular projects that they participate in. Of course, they have weekly meetings where people come together and talk, again, usually over a meal – at a meal where you’re having food. One of the most popular programs of the Rotary Club are scholarships: they give money to children in order to go to school. They also have a number of international scholarships, where they send people to other countries. This is sometimes called their “ambassadorial” scholarship, from the word “ambassador,” who is an official representative of one country in another country.
The Rotary Club also does work in helping fight against the disease of polio. So, if you’re interested in helping other people, you might try to find the Rotary Club in your area, if there is one. Now you know little bit more about them.
Now let’s answer a few of your questions.
Our first question comes from Sean (Sean) in Taiwan. Sean wants to know the difference between a “score” and a “grade.”
A “score” is the number of points that you receive on a test or on an assignment. For example, if the teacher gives you a test with 15 questions, each question is worth 1 point, and you get 11 questions correct, your score is 11, or 11 out of 15, meaning 11 of the 15 questions. That’s your score.
A “grade,” in school, is a letter that you receive. In American schools, we have the letters A for the best students, B and C for the not as good students, D and F for the worse students. In many American schools, there are certain percentages that you have to have. If you get above 90% (percent) correct of your points, you might get an A; If you get above 80, or between 80 and 90 is a B; between 70 and 80 is a C; between 60 and 70 is a D, and below 60 is an F, meaning you failed. Notice there are no E’s in this system. So, someone may say, “What score did you get on the exam?” – on the test, you could say, “I got an 87 out of 100.” Then they would ask, “Well, what grade did you get?” – “Oh, I got a B.”
The word “score” is also used in other contexts. In sports, the score is the number of points that each team has in a game. When the Los Angeles Dodgers play the San Francisco Giants – two different baseball teams – the Dodgers might win by a score of five to four. Five points for the Dodgers, four points for the Giants; that would be the score. Notice we use the expression “they win by a score of.”
A “grade” is, outside of school, a level of a standard of something. For example, you could say, “What grade of meat is this? Is it high grade (is it good quality), or is it low grade (is it poor quality)?” “Grade” also refers to the number of years you are in school – the year that you are in school, I should say: “What grade are you in?” – “I’m in 5th grade.” Americans count from 1 to 12 for their grades, so you can be in 1st grade, 2nd grade, 3rd grade. If you’re in high school, you’re in 10th grade, 11th grade, or 12th grade, and so forth.
Ryszard (Ryszard) in Poland wants to know the difference between “how can I get to” versus “where can I find.” These are both expressions you would use when asking for directions if you are trying to find or go to a certain place. They’re both used for location.
They can both be used to mean the same thing. If you are lost in a city and you stop and you ask someone, “How do I get to the airport,” you’re asking them to tell you which streets you take or which freeways you take to get to the airport. If someone says, “Where can I find the airport?” Again, they probably will give you directions: “Take this street, go right, take the next street, go left,” and so forth.
The difference between these is very small; “where can I find” might be a little more polite if you are asking for the location of something. We use “how do I get,” however, for locations only: “How do I get to the zoo?” “How do I get to the Center for Educational Development?” If you use “where can I find,” you can use that with a location: “Where can I find the zoo in Los Angeles?” – the answer is in Hollywood. Or, you can use it for things: “Where can I find the pen I’m supposed to use to sign this paper?”
Finally, Oleg (Oleg) – originally from Russia, he’s now living in Canada – wants to know the difference between the expressions “my friend” and “a friend of mine.”
Well, in English there are two different ways that you can express possession, to show who owns something or to whom something belongs. You can say, “Oleg is my friend,” you could also say, “Oleg is a friend of mine.” Either one is correct. You cannot say, “Oleg is the friend of mine,” you would say “a friend of mine,” meaning he’s one of many friends. You could also say, “My friend Oleg will be coming over to watch the game.” Or, you could say, “A friend of mine, Oleg, will be coming over to watch the game.”
Although both of these are ways of expressing possession or a relationship, it’s not always possible to use both forms. Sometimes it will sound strange if you say, for example, “this book of mine” instead of “my book.” The use of “my,” “your,” “his,” “her,” “theirs” is probably more common than saying “of them,” “of mine,” “of yours,” and so forth. But with the expressions “my friend” and “a friend of mine,” they’re both equally common.
If you have a question or comment for ESL Podcast, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational Development.
Glossary
headline – the title of an article in a newspaper or newsmagazine, written in text that has larger letters than does the text of the article
* Today’s newspaper had a front-page headline about the government scandal.
in the presence of (someone or something) – with someone or something else nearby; with someone else watching
* They were married in the presence of their closest relatives and friends.
to fall – to decrease; to decline; to become less
* Do you think the price of oil will continue to rise, or will it fall?
to mimic – to copy; to imitate; to do or say something just like another person is doing or saying it
* Ingrid is tired of her brother mimicking everything that she does.
stereotype – an idea that one has about a group of people, even if that idea isn’t necessarily true
* Some Americans believe the stereotype that everyone from that country are good at math.
to perpetuate – to make something continue for a long time; to make a belief or opinion continue over a long period of time
* Some Elvis fan clubs perpetuate the myth that Elvis Presley is still alive.
service club – an organization of people who believe in the importance of leadership and community service and often organize events and raise money to help other people in the community
* Tricia is a member of a service club that feeds the homeless every Saturday afternoon.
humanitarian – helping other people; interested in making other people’s lives better and more fair
* They are sending food and money to Appalachia as part of a humanitarian aid project.
to rotate – to change among many places or things; to go from one to the next and then returning to the first and starting again
* They rotate their meetings so that each member hosts the meeting at his or her home twice a year.
motto – a phrase that identifies an organization or institution and expresses an important value
* The motto of the United States, “In God we trust,” is written on the country’s money.
ambassador – a person who is a country’s official representative in another country
* Who is the Nepalese ambassador to the United States?
score – the number of points that one receives on an exam or homework assignment
* We need to get a score of at least 65 out of 100 points to pass the exam.
grade – a letter (A, B, C, D or F) given on an exam, homework assignment, or course to show how well one has done
* You need 90-100% of the points to get an A, 80-89% for a B, 70-79% for a C, and 60-69% for a D. Anything less than 59% is an F.
how do I get to – a phrase used to mean, “How can I get to…?” or “Where is…?”
* How do I get to the nearest subway station?
where do I find – a phrase used to mean, “Where can I find…?” or “Where is…”
* Excuse me. Where do I find the nearest pharmacy?
What Insiders Know
The Dumb-Blonde Stereotype in the Media
Many Americans believe in a “dumb-blonde stereotype,” which is the idea that women with “blonde” (yellow- or light-colored) hair are not intelligent and do stupid things. There are many jokes about dumb blondes in “popular culture” (the things that most people participate in) and also in the “media” (television, movies, songs, etc.).
For example, Marilyn Monroe was a famous American actress who was in many popular movies in the 1950s. She was beautiful and very “sexy” (attractive), and she also had blonde hair. Many people assume that she was a dumb blonde – someone with a pretty face, but no “substance” (intelligence and an interesting personality). This probably was not a fair “assessment” (evaluation), but the “notion” (idea) that blondes are “space cadets” (people who are not intelligent and cannot think deeply or seriously) is “pervasive” (common and deep-rooted) in American society.
Farrah Fawcett is an American actress who became very popular in the 1970s and 1980s. Like Marilyn Monroe, she was blonde and was seen as a “sex symbol” (a woman who is viewed as a sexual object more than as an intelligent and interesting person). Likewise, Pamela Anderson is a Canadian American actress who is known as a dumb blonde. All three of these women are attractive and sexy, and for those reasons many people “assume” (believe that something is true without knowing the facts) that they are stupid.
Like all other stereotypes, the dumb-blonde stereotype is “unfair” (not giving equal treatment to all people). “Consequently” (as a result), many blonde-haired women fight against that stereotype, working hard to show that they are intelligent and “capable” (able to do things well).