= 1440
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 135.
This is English as a Second Language Podcast’s English Café episode 135. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. You can download this episode’s Learning Guide, an 8 to 10 page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, which has additional special courses in daily and business English.
On this Café, we’re going to focus on vocational education in the United States. Then we’re going to continue our series on American cities, today talking about Miami, Florida. And as always, we’ll answer a few of your questions. Let’s get started.
Our first topic today is vocational education. “Vocational” comes from the word “vocation” (vocation), which is often used to mean the same as a job or an occupation. Sometimes we use the word “vocation” to mean something more than a job, something that is your purpose in life: “This is my vocation, to help other people,” for example.
Now, strangely enough, “vocational” as an adjective usually refers to a job or occupation that requires less education. So it has this different meaning; when you say “vocational,” you’re usually referring to someone’s job that doesn’t require a lot of additional training or education. Working as an electrician, a carpenter, or an auto mechanic (someone who fixes broken cars) are common types of jobs where you would get vocational education. Usually, vocational education is one to two years; it doesn’t require going to a four-year university for example. In fact, four-year universities that have bachelor’s degrees don’t usually have courses in vocational education. Some American high schools also offer vocational education classes to teach teenagers basic skills in some of these different areas.
Vocational education is sometimes called “career,” or when I was growing up in the 1970s, it was called “technical” education. Usually, it is focused on practical subjects, meaning things that you needs in real life, not theoretical ideas. Vocational education is also usually related to what we would call manual work. If something is “manual,” it means that you do it with your hands like an electrician or a carpenter or a mechanic might.
In the United States, as I mentioned, both junior high schools and high schools used to offer a lot of classes in vocational education; they’re not as common now as they were when I was growing up. In the past, girls, for example, were encouraged to take “home economics,” which is basically a class about cooking, sewing, and taking care of children. When I was in high school, there was a home economics class, and almost all the students were girls. There was also something called a “shop (shop) class,” and the shop class was for mostly boys, and they learned how to do things like cut wood and other practical techniques such as making things from metal or wood.
Larger high schools often had even more advanced courses in things like automobile repair. Today, however, there are very few schools that offer these kinds of courses, part of the reason is what we would call budget cuts; the money has been reduced for the schools in the U.S. in the last 25 years. Also, high schools offer less vocational education now because the governments of the states and the federal government are putting more emphasis on academic subjects, subjects that will help kids get into a regular four-year university. So, there’s less of an emphasis on vocational education. I think another reason is that we don’t have the same what we would call “gender stereotypes.” “Gender” is another word for your sex, either male or female. Many schools try to get away from this idea that girls should be cooking and boys should be working with wood, considering that a sexist notion of how boys and girls should behave, so now it is much more common to have courses that both boys and girls are part of, and that those courses be more academic in nature.
As a result, almost all of the vocational educational courses that you will find in the U.S. now are at community colleges. A “community college” is a – usually a two-year university – a two-year school. We wouldn’t call it a university; a university offers at least a bachelor’s degree for four years. Community colleges are sometimes called “junior colleges.” When I was growing up, we would call them junior colleges, “junior” meaning smaller or younger. They were also called technical colleges when I was high school, but now we call them mostly community colleges. They offer courses for people who are not necessarily interested in earning an academic or bachelor’s degree. They do offer something called an “associate degree,” which is a two-year certificate. Many students start at the community college and get a two-year associate degree, and then continue at a four-year university and get two more years of schooling to get their bachelor’s degree.
Community colleges offer many vocational courses. Students can take just a few courses to learn what they want to know, or they can earn an associate degree or a certificate in one of these jobs or occupations. A “certificate” is a document that states that you have completed a course and have a certain a certain level of knowledge. You are probably familiar with certificates of English proficiency for example; well, these are similar.
Once vocational students have earned an associate degree or a certificate, they may or may not need to complete an apprenticeship before they begin working in their chosen field – their chosen job. An “apprenticeship” is something like an internship, but it is not academic. In an apprenticeship, a student works with a professional for a few months, or sometimes a few years, in order to learn the “trade,” or the particular job well before beginning to work by him more herself. So, an electrician, for example, would study at a community college for 18 months or two years, then he or she would go to work for a regular, licensed electrician as an apprentice, learning from that electrician the things that they need to know in order to get their own job – their own employment somewhere.
Vocational education used to be looked down upon by many people. The phrase “to look down upon something” means to not respect something very much, or not to think of something very highly – not to think it is good. For example, many people look down upon people who have not studied in college. People used to look down upon vocational education, because they thought it wasn’t as good as a traditional academic education. However, I think that opinion is changing slowly with the recognition, or understanding, that there’s a strong need for technical vocations – technical jobs. In addition, jobs such as automobile mechanic are becoming more complicated and need more highly trained professionals. So many people now view vocational education more favorably than they did in the past. However, I must say that most parents, who are themselves college educated, would encourage their own children to go to a four-year university. But for many children coming out of high school, who have less opportunities or less money, or perhaps didn’t have good grades in high school, vocational education is a good place for them to start and to be able to get a job.
Now let’s change the subject and continue our series on American cities. As I said before, today we’re going to focus on Miami, Florida. Florida is a state in the southeastern part of the U.S., and Miami is in the southeastern part of Florida. The city has about 400,000 people, but the metropolitan area, the area around Miami is much bigger, it has around 5.5 million people, so it’s a big city.
Miami is home to the United States’ biggest port. A “port’ (port) is an area in a city next to an ocean where boats can come and go with products – things that they are bringing from other places. Miami’s port is used also for many cruise ships. A “cruise” is a – to some people – nice vacation on a large boat or ship, where you sleep on the ship and you, perhaps, visit different islands during the day. Miami’s port has more cruise ships than another other port in the world, so it is sometimes known as the “Cruise Capital of the World.”
The City of Miami is growing very quickly. It is experiencing what we would call a building boom. A “boom” (boom) is a period of time when something becomes very popular very quickly, or grows very quickly. There are more than 80 “high-rises,” or very tall buildings, under construction in the city of Miami now. There are lots of people who are moving to Miami, and it is growing as a city. In fact, it is growing so quickly some people call it “The Magic City,” because its growth seems magical – something extraordinary.
Because Miami is in the southeastern part of the U.S., it has a very hot “climate” – very hot weather. It also has many storms and “hurricanes,” which are large and dangerous windstorms that form over the ocean and then move across the land. You’re familiar with, perhaps, Hurricane Katrina, which hit New Orleans a few years ago. Miami has had many hurricanes.
The summers in Miami are very hot and “humid,” or damp, with lots of water in the air. I once went to Miami in August; I thought I was going to die it was so hot and so humid, very uncomfortable. I would never go back there again in the summertime! But, Miami is a nice place to go during other parts of the year. In the winter in Miami it’s very warm, very dry, and very pleasant. For that reason, there are many “retirees,” or elderly people who no longer work, who have moved to Miami during the winter to enjoy the warm weather. Sometimes these retirees live in Miami during the winter, and then go up north to a northern U.S. city during the summertime where it is cooler, because it’s so hot in Miami in the summer.
Miami has many beautiful beaches that attract tourists from throughout the United States and from other countries. Many college students like to go to Miami during their spring vacations in March or April. Other people are attracted to Miami because of its “proximity,” or closeness or nearness, to two national parks: Everglades National Park and Biscayne National Park. It’s unusual for a large U.S. city to be so close to a national park. The two parks near Miami have very interesting flora and fauna. “Flora” (flora) are different types of plants; “fauna” (fauna) means different types of animals. There are many wild alligators that live in the national parks. An “alligator” is a large lizard-like animal with very big teeth and a very big mouth – that kind of describes me, too, I guess! Alligators swim in the water and they walk on land, so if you visit the national parks in southern Florida, you have to be careful about the alligators so you don’t get eaten by one!
Miami is also home to many “immigrants,” people who come from other countries, especially countries from Latin America, meaning South America and Central America – countries such as Nicaragua, Costa Rica, Argentina, and other Spanish-speaking countries. There are also many people in Miami from the different islands around the state of Florida, in the Caribbean. Most the immigrants who have come to Miami have come from Cuba; in fact, 65% of the population of Miami is from a Latin American background, and 35% are Cuban. Spanish is very commonly spoken in Miami, just as it is here in Los Angeles. In fact, in some parts Miami, it is more common to hear Spanish than to hear English!
Miami has also become famous in the last few years as a place where people from Hollywood have gone in order to have a good time. There are famous singers and actors who have moved to Miami, so Miami has a very active social scene – lots of bars, lots of restaurants, and so forth. In the 1980s, there was a famous television show called Miami Vice, which was about the Miami Police Department and it painted, or it portrayed, as being a very sexy city – a very attractive city in many ways.
Because there are so many immigrants or children of immigrants who live in Miami from Latin America, many international businesses are located in Miami. Some people call Miami the “Gateway to Latin America.” A “gateway” is a door that lets you enter a certain place; in this case, it is an entry point to Latin America. So, if you have a chance to visit Miami during the winter, I can highly recommend it. You might want to stay away during summertime; it is very hot there!
Now let’s answer a few of your questions.
Our first question comes from Regis (Regis) in France. Regis wants to know the meaning of the expression “to have a monkey on your back.”
“To have a monkey on your back” means to have a problem. Sometimes the problem is a bad habit, something that you do a lot. For example: “I lost my job last month, and now I have a lot of bills to pay. I would love to get this monkey off my back,” this burden, this problem.
A “monkey,” of course, is an animal. Why you would have a monkey on your back, I don’t know, but that’s the expression. It means to have a difficult problem that is troubling you.
Kaorl (Kaorl) in Poland wants to know how we use the verbs “to manage,” “to administer,” and “to execute.”
“To manage” and “to administer” often have the same meaning; they mean to be in charge of or responsible for doing something, something usually related to business or work. They also can have slightly different meanings. “To manage” can also mean to be able to do something difficult. For example: “How will you manage to get your four dogs into that small car?” – how will you be able to do that?
“To administer,” in addition to meaning to be responsible for something, can also mean to give someone a drug. For example: “The nurse administered a shot to each of the school children.” She gave the shot; she took a needle and put it in their arm and put drugs in there. That’s to administer a drug. We also sometimes use this expression when we are talking about punishment: “Who will administer the punishment to the children?” – to give the punishment if you do something wrong.
“To execute” means to put something into effect. We might use the phrasal verb “to carry out” – “to carry out” or “to perform” something. “We need the best business people in order to execute this agreement,” this deal – to carry it out, to put it into effect, to make it happen.
“To execute” can also mean to kill a prisoner: “The prisoner was executed at midnight.” In the United States, many states still have what is called “capital punishment,” where you can be killed by the government for your crime. When you actually kill the prisoner, we would called that an “execution.”
Finally, Asaf (Asaf), who is originally, I believe, from Israel, now living in the U.S., has a question about the expression “to be off.” What does it mean to be off?
It can sometimes mean to be cancelled, for example: “The game is off today because of the rain” – we can’t play baseball, the game is off, it is cancelled. Or “Did you hear about Julie and Robert’s wedding? The wedding is off. Julie found out that Robert was seeing his old girlfriend, so the wedding is off.” It’s cancelled; it won’t happen.
“To be off” is also used to mean to begin or to depart from somewhere. For example: “We spent two hours getting ready for our trip, and now we’re off” – now we are leaving; now we are departing. You could also ask someone, “What time will you be off to work tomorrow?” What time are you leaving to go to work? Don’t confuse this with another expression, “to get off of work.” “What time do you get off of work” means what time do you leave work to come back home. So, you can be off to work, or off to the airport, or off to a place, meaning you are leaving for that place, or you could get off work, meaning you could leave your work.
Now it’s time for us to be off, but if you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. We’ll see you next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational
Development.
Glossary
vocation – non-academic job; non-academic occupation
* He likes to work with wood, so he has always dreamed of a vocation as a furniture-maker.
apprenticeship – a non-academic internship; a period of time, usually a few months or a few years, in which a person works with an expert in a profession to learn how it is done before beginning to work independently
* Jackie completed a 10-month apprenticeship in metalwork before she opened her own business.
trade – vocation; occupation; a physical (not academic) job
* How many years have you worked in the auto-mechanic trade?
home economics – a high school subject that teaches students how to cook, sew, care for children, and manage a home
* Becca made a beautiful dress in her home economics class.
community college – an academic institution that is smaller than a university and offers classes to community members and for two-year degrees, with some students transferring to a larger university afterward
* Ricky wants to take an algebra class at the local community college this fall.
associate degree – a two-year degree offered by a community college that can also be used to transfer to a university
* When did Albert earn his associate degree in filmmaking?
to look down upon (someone or something) – to think that one is better than someone or something; to think that someone or something is not very good and does not deserve one’s respect; to not think very highly of someone or something
* Everyone looked down on Dan when they learned that he had been arrested for stealing.
port – an area in a city next to an ocean where boats and ships come and go with products
* The port of Seattle, Washington is a good place to buy inexpensive fish.
boom – a period of time when something is very popular and increases very quickly
* The “baby boom” refers to a period of time in U.S. history when many babies were born after World War II.
retiree – an elderly person who no longer works
* Cesar can’t wait to be a retiree so that he can go golfing every day.
proximity – closeness; nearness
* Laura wants to live in Oregon’s Willamette Valley because of its proximity to the coast and the mountains.
gateway – an opening in a wall or fence through which one can reach other places, often used figuratively
* Many people view earning a college degree as a gateway to getting a good job.
to have a monkey on (one’s) back – to have a problem that won’t go away; to have a problem that worries or bothers one a lot
* She always feels like there’s a monkey on her back because she is never able to pay her bills on time.
to administer – to manage; to run a program, especially the administrative details
* How many people are involved in administering the university’s student selection process?
to execute – to implement; to control a project or program and make it happen
* The company is executing a new sales strategy to try to increase its profits.
to be off – to be cancelled
* The wedding is off! Avery decided that he didn’t want to get married after all.
to be off – to depart; to leave a place
* We packed everything into the car, locked the house, and then we were off to enjoy our two-week vacation.
What Insiders Know
Miami Vice
Miami Vice was a popular television series from 1984 to 1989. A “vice” is a bad habit, such as smoking, eating too much, or being jealous. Miami Vice was about two police “detectives” (people who investigate crimes and other mysteries) in Miami. Most “episodes” (individual shows in a series) were about drug selling and “prostitution” (selling sex). Miami Vice was one of the first popular TV shows about police and it was a model for many similar shows that were created later.
The most “impressive” (surprising in a good way) thing about the show was the way that it influenced “pop culture” (popular culture; things that are familiar and enjoyable for most people in a society). Miami Vice had a “tremendous” (very big and powerful) impact on “fashion” (popular styles). The characters often wore t-shirts under “pastel” (lightly colored) suit jackets, and the people who watched the show began to do the same. A well-known clothing store, Macy’s, even opened up a Miami Vice section in its stores, selling men’s clothing that was similar to what was seen on the show.
“Likewise” (similarly), the Miami Vice characters started the “trends” (something that is very popular during a brief period of time) of not wearing socks and rolling up the sleeves of one’s jacket. The characters also wore Rayban sunglasses, and the Rayban company’s sales of sunglasses increased “dramatically” (very much) as ordinary people tried to “imitate” (be like another person, or do something like another person does it) their favorite characters. Men also began to wear a “five o’clock shadow” (a small amount of beard left unshaven), just like the characters.
The show also increased Americans’ interest in Miami. This resulted in more tourism and “investment” (money spent on projects) in the Miami area, and especially around Miami Beach.