= 1412
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast’s English Café number 107.
This is English Café episode 107. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com, download a Learning Guide for this episode, and help yourself learn English even faster. You can also take a look at some of the new things we have on our website, which we think you’ll enjoy.
This episode is going to be another “Ask an American” episode, where we listen to another native speaker talk about a topic. The topic in this episode will be “Socially Responsible Businesses.” We’ll be listening to what some people think about the idea of socially responsible businesses and, of course, talk about what that term means. As always, we’ll answer a few of your questions as well. Let’s get started.
Our first topic today is about socially responsible businesses. The idea here is that companies, in addition to trying to make money, also try to do good things for the community, do good things for the environment – for the water and the air, for example. That’s socially responsible business.
There are many people who think that businesses do things for reasons of saving money or, perhaps, helping their public image – what people think of them – and that that is the real reason why they do these things. Other people believe that many companies are actually interested in doing things that are socially responsible.
In this episode, we’re going to listen to three different views and ideas about this idea of social responsibility. These come from, as do many of our “Ask an American” segments, the Voice of America website.
Our first quote is from a professor at Boston University by the name of James Post. He talks about the companies’ “bottom line,” meaning the amount of money they make after they spend what they need to spend. You take everything that you get from your customers – all the money – you subtract what it costs you to produce your product, and that’s the bottom line. He’s going to talk about something called a “triple bottom line” for socially responsible companies and what that means. He’s going to speak rather fast, and this is a little longer quote than we normally have. But, try to listen to it; understand as much as you can. Don’t worry, we’ll go back and explain everything he says after we listen to it.
[recording]
What they’re doing is they’re reinventing the bottom line in a way that companies refer to as “triple bottom line,” where they take careful measurement of their economic performance and their environmental performance. What is the impact on the air and the water, the land, biodiversity, and so forth, and their community impact? So the triple bottom line is economic, environmental and community impacts that a company has. That’s the bottom line that defines how sustainable a company will be over the long-term.
[end of recording]
The person being interviewed here – on the telephone, you can probably guess – starts by saying, “What they’re (what companies are) doing is they’re reinventing the bottom line.” To “reinvent” means to create again – to invent again. When you see the prefix – the letters “re” in front of a word, it often means to do again. So, the companies are creating a new idea about the bottom line. Remember, the bottom line is what a company makes – its profit, if you will.
This reinvention is something that he calls the “triple bottom line”; “triple” means three. He says, “they take careful measurement of their economic performance and their environmental performance.” So, they’re looking at how much money they make – their economic performance – as well as what they are doing to the environment – to the water and to the air, for example. These companies are asking what “the impact on the air and the water, the land, biodiversity, and so forth” is. The “impact” is the effect. You know what air and water and land are; “biodiversity” refers to the biological variety of plants and animals, for example.
So, James Post says, “What is the impact on the air and the water, the land, biodiversity, and so forth…?” That expression, “and so forth,” means et cetera; instead of naming all the other possibilities, he just says “and so forth,” meaning you’ll understand that it includes other things as well. The triple bottom line is also about the “community impact,” meaning how does your business affect the lives of the people who live around you.
He continues, “So the triple bottom line is economic, environmental and community impacts that a company has. That’s the bottom line that defines how sustainable a company will be over the long-term.” “Sustainable” means able to be maintained at a certain level – able to stay or keep at a certain level. That’s “sustainable” – can you continue doing it over and over again into the future? So, the triple bottom line “defines (or tells us) how sustainable a company will be over the long-term,” meaning over many months or many years.
Let’s listen now again:
[recording]
What they’re doing is they’re reinventing the bottom line in a way that companies refer to as “triple bottom line,” where they take careful measurement of their economic performance and their environmental performance. What is the impact on the air and the water, the land, biodiversity, and so forth, and their community impact? So the triple bottom line is economic, environmental and community impacts that a company has. That’s the bottom line that defines how sustainable a company will be over the long-term.
[end of recording]
One of the reasons that many American companies are trying to be more socially responsible is that their shareholders are demanding these changes. A “shareholder” is someone who owns part of the company; they own a “share,” or a part of the company. We usually do this with “stocks.” Someone who owns stock in a company is a shareholder
Meg Voorhes is going to tell us why the shareholders have been trying to change the way companies work “behind the scenes,” meaning not publicly but privately. Once again, let’s listen and then we’ll go back and explain.
[recording]
We’ve seen the number of shareholder proposals on environmental and social issues, at U.S. companies anyway, inching up. It’s been a generally upward trend over the last few years. But even behind the scenes, I get the sense that there is more shareholder communication and discussion with companies. Certainly a lot of the leading institutional investors, the largest pension funds, are contacting company management and discussing important issues with them behind the scenes.
[end of recording]
Don’t worry if you had difficulty understanding this; she speaks very quickly and it is harder to hear people on the telephone. But, of course, many of you communicate in English on the telephone, so it is good practice to hear a recording like this.
She begins by saying, “We’ve seen the number of shareholder proposals…” “proposals” are formal suggestions or ideas that you want someone else to listen to and to adopt. “We’ve seen the number of shareholder proposals on environmental and social issues, at U.S. companies anyway, inching up.” She’s saying here that the number of shareholder proposals concerning environmental issues has been increasing. The expression to “inch (inch) up” is a two-word verb meaning to increase slowly. An “inch,” you know, is a very small unit of measurement that we use in the U.S., so the verb to “inch up” means to increase slowly. This change has been taking place “at U.S. companies anyway,” meaning she’s not sure if it has taken place in other countries, but it has in the United States.
She continues, “It’s been a generally upward trend.” “Upward” means increasing, “trend” is the way something is changing over time. So, an “upward trend” would mean that it is increasing over time. She says, “it’s been a generally upward trend over the last few years. But even behind the scenes (remember “behind the scenes” means privately, not in public), I get the sense that there is more shareholder communication and discussion with companies.” “I get the sense that…” means I don’t know for sure, but it is what I believe based upon what I have heard, or what I have read, or what people have told me. This is a very common expression when you’re not sure about something, but you see the indications – the signs of something – and you try to identify it.
She continues, “Certainly a lot of leading institutional investors, the largest pension funds, are contacting company management.” “Institutional investors” are large companies – large organizations – that invest, or buy, for example, stocks for their organization or company. So, an institutional investor would be a large group or a large company that invest money in, for example, the stock market. “Pension funds” refers to the money – the funds – that are used for people who retire. A “pension” is money you get after you get older and you stop working. So, these institutional investors “are contacting company management (the managers of these companies) and discussing important issues with them behind the scenes.”
Let’s listen one more time.
[recording]
We’ve seen the number of shareholder proposals on environmental and social issues, at U.S. companies anyway, inching up. It’s been a generally upward trend over the last few years. But even behind the scenes, I get the sense that there is more shareholder communication and discussion with companies. Certainly a lot of the leading institutional investors, the largest pension funds, are contacting company management and discussing important issues with them behind the scenes.
[end of recording]
Finally, we listen to another university professor, Anthony Buono, who is going to talk about how this socially responsible movement or change among companies has become more common and will continue to be more common. It will become so common that it will be the way companies normally operate. It will be part of what we call the “standard business practice” of a company. Let’s listen.
[recording]
We will see this becoming more and more commonplace to the point where we may not even be talking about corporate social responsibility within the next decade. We’ll simply be talking about what is standard business practice, and standard business practice, hopefully, will be engaging a much broader array of stakeholders rather than simply focusing on shareholders.
[recording ends]
He begins by saying, “We will see this (trend toward social responsibility) becoming more and more commonplace.” The word “commonplace” (one word) means common, something that you will find in many places, hence “commonplace.” It will be “commonplace to the point (meaning to the extent) where we may not even be talking about corporate social responsibility within the next decade,” or ten years. So he’s saying here that most – or all – companies will start to do this – to be more socially responsible – so it won’t be a separate topic; it will just be considered normal. He says, “We’ll simply be talking about what is standard business practice,” or the way that businesses normally operate. That’s an expression you’ll hear in business, “standard business practice,” or “standard business practices,” the ways that a company does its business.
“Standard business practice,” he goes on to say, “hopefully (we hope), will be engaging a much broader array of stakeholders.” To “be engaging” here means to be involved with – involving “a much broader array.” “Array” (array) is a range, a large number of different types. An “array of stakeholders” are different types of people who have an interest in something common. For example, if you live in a city, the stakeholders are the people who have houses there, the businesses that operate there – these are both stakeholders. The word “stakeholder” is often used in talking about community organizations; it’s often used in political discussions to refer to the people who are affected by something or the people who are involved with something. Of course, in a company there are shareholders – people who own part of the company – but there are also people in the community who are affected by the business. Those two groups are both considered stakeholders.
Let’s listen one more time.
[recording]
We will see this becoming more and more commonplace to the point where we may not even be talking about corporate social responsibility within the next decade. We’ll simply be talking about what is standard business practice, and standard business practice, hopefully, will be engaging a much broader array of stakeholders rather than simply focusing on shareholders.
[recording ends]
Those are some views of some Americans about socially responsible businesses. Now let’s answer a few of your questions.
Our first question comes from Fahad (Fahad) in Saudi Arabia. Fahad wants to know the meaning of the term “case (case) study.”
A “case study” can mean a couple of different things. It often means, especially in business, a specific example that you use to show a principle or an idea – to demonstrate some concept, to illustrate some concept or idea. This is often done in business schools, where they study particular companies – specific companies – as examples of certain ideas, certain ways of doing business.
A “case study” can also be a way of doing research – of investigating something by recording, or putting down – writing detailed information about a specific person, group, or situation over some long period of time.
Our next question is from C-H-A-O-Z from the U.S., or at least is currently here, in Berkeley, California. The question has to do with the expression “at sea,” or “to be at sea” (sea).
A “sea” is a body of water, like an ocean is a body of water; a lake is a body of water. It’s somewhere between an ocean and a lake. The Mediterranean Sea, the Red Sea – those are examples of a sea. The expression, however, usually means to be confused, to not know what to do or to think. For example, “I was told to use a new computer program that my company bought for me, but I was at sea about how to use it.” The idea is I’m like a ship at sea – on the water – that is lost, so it means to be lost or to be confused.
The other question is about the idiom “to knock someone’s socks off.” “To knock someone socks off” means to impress someone very much; to make someone think you are very good or your work is very good. “When I used my new cell phone, it knocked my socks off” – it impressed me, it made me think “Wow, that’s great!” That’s to knock someone’s socks off.
Finally, Vladimir (Vladimir), originally from Ukraine, now in Toronto, Canada, wants to know the meaning of the expression “to take one’s time.”
“To take one’s time” means not to rush – not to hurry. If someone says, “I will take my time to do something,” they mean they’re not going to go fast, or they’re not going to let someone else try to make them go fast. My wife wants me to paint our house – the outside of our house – and I told her, “I’m going to take my time to do it,” because when I finish painting, she’ll have something else for me to do! So, that’s taking your time.
Well, take your time and listen to ESL Podcast’s English Café wherever you’d like and whenever you’d like. If you have a question or comment, email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2007, by the Center for Educational Development.
Glossary
bottom line – the most important thing; in business, the amount of money made by a company after it has paid all its expenses
* The orange growers had a much lower bottom line this year after the storm killed all of their orange trees.
impact – effect; the way that something is influenced or changed by something else; result
* Do you believe that if the government started spending more money on education, both students and teachers would benefit?
sustainable – ongoing; permanent; not temporary or short-lived; something that can be continued over time
* Giving food to poor communities isn’t sustainable, because they will always need more food. But teaching them how to grow their own food is sustainable, because once they have learned it, they can do it without help from others.
shareholder – a person who owns part of a company, known as a share or stock
* I wish we were shareholders in this company, because those shares are worth a lot of money now.
stakeholder – a person or organization who is or will be affected by something; a person or organization who has an interest in something
* The school is considering changing its schedule, but first it wants to talk to the stakeholders: the students, teachers, and parents.
to inch up – to increase or move forward slowly, almost unnoticeably, over time
* They spent all morning in a very long line, slowly inching up to the ticket window.
behind the scenes – in the background; without being seen or observed; not obvious
* When watching a play, many people focus on the actors, but I am more interested in all the people who are working behind the scenes.
pension – the money that one receives every month after retiring; the money that an old person receives every month after he or she has stopped working
* Her grandparents are having a hard time learning to live with only a $470 pension each month.
investor – a person who puts money into a project or organization, expecting to receive more money if that project or organization is successful
* The investors want to receive a monthly report about the business’s growth, or else they won’t invest any more money.
commonplace – ordinary; common; not unusual
* Unfortunately, murders are now commonplace in many large cities.
to engage – to involve; to use the services of; to do something with another person or organization
* The speaker really knew how to engage the audience and to make the speech interesting.
array – range; a group of things; an assortment of different types of things
* The team faces an array of challenges, but we believe it will succeed.
case study – a written analysis of a business or situation and how it has changed over time or how it has adapted to a changing environment
* At the McQuillan Business School, students use case studies to understand what does and doesn’t work in the business world.
to be at sea – to be on a boat on the ocean; to not know what to do; to be confused
* Oriel wanted to attend a college out of California, but he doesn’t want to leave his girlfriend behind and is at sea about what to do.
to knock (someone’s) socks off – to impress someone very favorably; to do something that makes another person positively impressed
* When we heard Nestor sing for the first time, he knocked our socks off with his beautiful voice.
to take (one’s) time – to do something slowly; to do something without being in a hurry, as if one has unlimited time to do it
* Please take your time filling out these forms. I don’t need them right away.
What Insiders Know
Socially Responsible Businesses
Many American businesses want to not only be “profitable” (making money), but also “socially responsible” (responsible to the society in which they do business). A socially responsible business is supposed to do the right thing, helping people who need help, and becoming involved in important community projects. Many companies struggle to be more socially responsible, but some businesses have “excelled” (done very well) in this area.
One example of a socially responsible business is Ben and Jerry’s. The company has become famous not only for its delicious and unusual ice cream, but also for its efforts to be a socially and environmentally responsible business.
Ben and Jerry’s “collaborates” (works with) many “NGOs” (non-governmental organizations) that are active in communities. For example, Ben and Jerry’s is working with the World Wildlife Fund, a well known environmental organization, to “increase awareness” (make people more knowledgeable about something) of “global climate change” (the increase in Earth’s temperatures due to human activities).
The company also “refuses” (won’t do something) to use milk from “hormone-treated cows” (cows that are given chemicals to make them produce more and/or better milk). It also tries to buy some of its ice cream “ingredients” (the things that are used to make a type of food) from small, family-owned farms instead of large, “corporate” (owned by large businesses) farms.
The company “donates” (gives money away) a percentage of all its sales to NGOs. It also has its own “foundation” (an organization that gives money away) that tries to make the world a better place by giving money to other organizations that are doing good work to solve environmental and social problems within communities.