= 1437
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 132.
This is the English Café episode 132. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
We have a website – oh, yes we do! Our website is eslpod.com. You can go there to download a Learning Guide for this episode to help you improve your English even faster. You can also take look at our ESL Podcast Store, which has some additional courses in business and daily English I’m sure you’ll be interested in.
On this Café, we’re going to do another “Ask an American” interview. This is where we take someone talking at a normal speed, and go back and explain what they’re saying and listen to it a couple of times. The topic today is going to be acting, how people work as actors here in Los Angeles, what it requires, what they have to do. Los Angeles, as you probably know, is the capital – the main city for entertainment, movies, and television in the United States, and very popular in other countries as well. We’ll talk about what it means to be an actor by interviewing an actor. As always, we’ll also answer a few of your questions. Let’s get started.
We’re talking about acting on this Café. I interviewed an actor here in Los Angeles, Carin Chea. She’s an actor working here in Los Angeles. I talked to her about what it means to be an actor, what it requires.
Carin is in her late 20s; she studied acting at Berkeley, a university here in California. She also studied in New York City, at a famous acting school. She has acted in many different plays and has done other television work, as well as work for commercials and advertising. We’re going to start by asking her to talk about how difficult it is to be an actor, what it requires, and what you actually do to try to get a job. First we’ll listen to Carin speaking at a normal speed, then I’ll explain what she said and we’ll listen to it again.
[recording]
An actor in Los Angeles has to be very driven. Umm, I personally believe that you have to really want it, to truly love the craft of acting, because there is so much rejection involved that if you really don’t want it, you will get crushed – your soul will wither and it will die! And you know, sometimes it felt like that. But, it’s the passion that just drives me to wake up every morning, go online to, umm, these places called, umm, break down services online where I submit my headshot and résumé to maybe a dozen or two dozen casting directors a day. And maybe, out of 50 or so submissions, maybe I’ll get two auditions.
[end of recording]
Let’s go back and talk about what Carin just said. She says that an actor in Los Angeles has to be driven. When we say someone is “driven,” we mean, in this case, someone who is very ambitious, someone who has a lot of motivation, somebody who really, really wants to do something. If you want to be president of the United States, you have to be very driven; you have to have a great deal of ambition and motivation, because it’s very difficult.
She says, “I personally believe that you have to really want it, to truly love the craft of acting.” When we use the word “craft” (craft) in talking about someone working, we usually mean the skill, the knowledge, the things that that person has to do and know in order to be able to work at that job. You could talk about the “actor’s craft,” what it means to be an actor. “Craft” has a couple of different meanings; “craft” can also means something you make with your hands. But here it means the knowledge and skills that you need in order to do a certain job. Actors often talk about their work as being a “craft.” It’s not a word that you would commonly use in most jobs, but it is one that gets used a lot to talk about acting, especially by actors!
Carin says that there is so much rejection involved. “Rejection” is when someone says no to you. I experienced this many times in high school and college, and as a young adult – mostly with women! When Carin says rejection is “involved,” that means it’s part of the process; it’s part of being an actor. She says, “if you really don’t want it (if you’re not driven), you will get crushed.” “To crush (crush) something” means to destroy it, to make something flat. For example, if you have a can of soda and you crush it, you destroy it; you put your foot on it make it flat. In this case, “to be crushed” means that you will be hurt, you will be damaged, you will feel pain.
She then uses a somewhat poetic expression: “your soul will wither.” “Your soul (your life force) will wither.” To “wither” (wither) means to slowly die. It’s a word we often use to talk about a flower that doesn’t get enough sun or water; it eventually will “wither,” it will die slowly. That won’t happen to your soul if you don’t really want to become an actor because of all of the rejection. She says, “And you know, sometimes it felt like that.” Sometimes she went through those experiences herself.
She then says, “But it’s the passion (it’s the motivation, it’s the drive, it’s the ambition) that just drives me.” Notice we used the word “driven,” here we’re using the verb “to drive” to mean to go forward, to continue to work hard at something even though it’s difficult, to motivate you. The passion drives her “to wake up every morning, go online (meaning check the Internet) to these places called break down services.” A “break down service” is a company that has jobs for actors, and you go and you register on their website, and you can find jobs as an actor. She goes to these websites – these break down services online – where she submits her headshot and résumé.
All actors, whether they are film actors or stage actors, – meaning in a play, live – have what’s called a “headshot.” This is usually an 8-inch by 10-inch photograph of their head. They give this to the people who are looking for actors, and they can look and see: “Okay, I like this person, the way he looks. I don’t like the way she looks,” and so forth. It’s sort of like your advertisement for getting a job; in acting, we usually call it a “part.” “I have a part in a play,” that means I am one of the characters; I am going to act in the play.
So, Carin has her headshot – and if you walk into any restaurant in Los Angeles and you look up on the wall, you will often see headshots of actors with their signatures. Sometimes these are famous actors that have eaten at that particular restaurant, sometimes they’re just people who go into the restaurant and give their headshot, and the owner puts it on the wall, even though they’re not particularly famous.
Well, Carin has her headshot and her résumé. A “résumé” is a list of your experience, the jobs that you’ve had, the education that you have. She “submits (she sends these electronically) to maybe a dozen or two casting directors.” A dozen is 12; so two dozen would be 24. “Casting” comes from the verb “to cast,” which, here, means to find someone for a television show, a movie, or a play – to find actors. So a “casting director” is the person responsible for finding the actors.
She says, “maybe, out of 50 or so submissions, maybe I’ll get two auditions.” “Submission” comes from the verb “to submit,” which means to send something to someone, often an application or some formal proposal. So out of 50 submissions she sends, maybe she gets two auditions. An “audition” is when you go to the casting director – you go to their place, their workplace – and you get a chance to act so they can see if they like you or not. That’s an “audition.”
Let’s listen again.
[recording]
An actor in Los Angeles has to be very driven. Umm, I personally believe that you have to really want it, to truly love the craft of acting, because there is so much rejection involved that if you really don’t want it, you will get crushed – your soul will wither and it will die! And you know, sometimes it felt like that. But, it’s the passion that just drives me to wake up every morning, go online to, umm, these places called, umm, break down services online where I submit my headshot and résumé to maybe a dozen or two dozen casting directors a day. And maybe, out of 50 or so submissions, maybe I’ll get two auditions.
[end of recording]
I then ask Carin what actually happens when an actor goes to an audition, when they go and try to get a job from the casting director. She’s going to talk about what happens when she goes, how she finds out that she has an audition, what happens when she gets there, and how long it takes.
Once more, first we’ll listen, then we’ll go back and explain.
[recording]
Usually, what happens is, umm, they’ll notify you through email or they’ll call your cell phone. And I’ll go to the casting studio, and there’ll be 10 women just like me, holding a script and their headshot, avoiding eye contact, uh, because we all want the job. We’ll go in, we’ll read for the casting director. Maybe the casting director has some adjustments for us, so we’ll, uh, read the sides – which is another word for script – another way, and then, uh, we’re off. And the whole process of getting ready to go to an audition – driving there, prepping – takes three hours, but in the actual audition with the casting director, that only takes two minutes. So, two minutes out of those three hours is spent acting.
[end of recording]
Carin says what usually happens is they’ll notify you, they’ll call you or email. Then she goes to the casting studio. A “studio” is a place where they make films or television shows. So she goes to the casting studio, the place where they make the movies, “and there’ll be 10 women just like me, holding a script and their headshot.” In other words, the casting director asks for several people to come at the same time; usually they’re looking for a particular physical type. That is, they want a woman between 25 and 30, with dark brown hair, beautiful eyes – oh wait, no, that’s what I want, well, just an example of course!
So the casting director is asking all these women to come, and they’re holding their script. The “script” are the words that the actors says during a play, or a television or movie production. All of the women have their “headshots,” pictures of themselves to give to the casting director. They avoid eye contact. “Eye contact” is when you look at someone, they look at you, and your eyes meet. You look at their eyes, they’re looking at your eyes; we call that “eye contact.” Well, the women who are trying to get this part – this job – avoid eye contact, they don’t look at each other because they all want the job.
They go in, they enter the studio, and they read for the casting director. In this case, “to read” means they say the sentences that were written for them to say. We usually call those sentences their “lines.” So they say their lines to the casting director; maybe the casting director has some “adjustments,” some changes for them. So then they have to read again. Another word for reading the “script” is reading the “sides.” This is a special term that you use in acting – in theater and in television. “To read the sides” means to read the script. They read it a different way; perhaps the casting director wants them to be louder, or softer, or more dramatic. “And then,” she says, “we’re off,” meaning we’re finished, we’re done, we leave.
The whole process of getting ready to go to an audition, which includes driving to the audition, preparing – Carin uses the word “prepping” (prepping), which means to prepare; “to prep” is another way of saying to prepare. “The whole process of getting ready takes three hours, but the actual audition with the casting director, that only takes two minutes.” So, you take all this time to get ready, but your actual audition, when you actually stand there in front of the casting director, that only lasts two minutes. “So,” she says at the end, “two minutes out of those three hours is spent acting,” meaning you spend two minutes acting out of those three hours.
Let’s listen again.
[recording]
Usually, what happens is, umm, they’ll notify you through email or they’ll call your cell phone. And I’ll go to the casting studio, and there’ll be 10 women just like me, holding a script and their headshot, avoiding eye contact, uh, because we all want the job. We’ll go in, we’ll read for the casting director. Maybe the casting director has some adjustments for us, so we’ll, uh, read the sides – which is another word for script – another way, and then, uh, we’re off. And the whole process of getting ready to go to an audition – driving there, prepping – takes three hours, but in the actual audition with the casting director, that only takes two minutes. So, two minutes out of those three hours is spent acting.
[end of recording]
Once again, I want to thank Carin Chea for coming on the podcast and doing the interview with us. Someday, when Carin is famous after becoming a movie star, you’ll remember her from ESL Podcast. We found her first!
Now let’s answer a few of your questions.
Our first question comes from Vasily (Vasily) in Russia. The question has to do with the differences among the words “nevertheless,” “despite,” and “even though.” How are these three words or expressions different? They can each mean the same thing; however each is a different part of speech, each has a different function in the sentence. Let’s start with “nevertheless.”
“Nevertheless” can mean “however” or “in spite of.” For example: “The books cost a lot of money, nevertheless, I must buy them for my college classes.” So, the books cost a lot of money, but I have to buy them for my classes. “Nevertheless,” here, connects the two sentences. It connects “the books cost a lot of money” with the sentence “I must buy them for my college classes.”
“Despite” is a preposition, for example in this sentence: “Despite the fact that he didn’t study for the test, he still received an A.” “Despite the fact” is a prepositional phrase. Once again, “despite” means the same, or very similar thing to “nevertheless,” it means “even though,” or, we might say “even in spite of,” which is another way of putting a prepositional phrase to give the same meaning. For example: “Despite the fact that he put a lot of money into his presidential campaign, he still lost the election.”
“Even though” is a conjunction; it links two phrases together. It is similar to the idea of “despite,” and sometimes can be used in the same way. For example: “Even though he didn’t study for the test, he still receive an A.” “Even though” means the same as “despite the fact that.” Another example would be: “Even though she went for a five mile run, she still gained two pounds.” I could also say, “She still gained two pounds, even though she went for a five miles run.”
So the differences among these three terms is more related to their grammatical function in the sentence than it is their actual meaning. They all have very similar meanings.
Our next question comes from Ailo (Ailo) in Brazil. The question has to do with the phrasal verb “to screw up.”
“To screw up” is an informal slang expression meaning to make a mistake or to do something bad, even to do something bad to your own mind or to someone else’s mind. For example: “The chef screwed up the recipe when he forgot to add one of the ingredients.” The chef – the cook – screwed it up, he made a mistake, he ruined it. You could also say, “I screwed up my back yesterday when I was running.” I hurt it – I “screwed it up.”
“To screw up” can also be related to your mental health. For example: “Sara is really screwed up because of her alcoholic father.” She’s “screwed up,” she has problems psychologically.
Once again, this is a slang expression, and should probably not be used in formal or business settings. There’s also a noun, a “screw up.” A “screw up” is a person who always screws up.
If you’ve screwed up on your English and want to have us help you, email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational Development.
Glossary
to be driven – to have a strong desire for and to work hard to do something; to have high motivation to achieve something
* It takes many years of schooling to become a doctor, so students must be very driven to want to enter that profession.
craft – profession; activity requiring a high level of skill or ability
* Douglas is spending the summer working with a master wood-worker to develop his craft.
rejection – dismissal or refusal because someone or something is not good enough or does not meet the requirements
* It was difficult for Mark to continue applying for jobs after getting so much rejection.
to get crushed – to be very disappointed; to have a strong feeling that one has failed
* Celia was crushed when she didn’t win the award for the best science project.
headshot – a photograph of a person’s face, usually used by actors to apply for jobs
* The photographer took these headshots of me, but I don’t think they are very high quality. What do you think?
casting – the process of selecting actors for a play, television show, commercial, or movie
* For this movie, the casting director is looking for two women in their 20s who can sing and dance.
submissions – applications; proposals
* How many submissions did we get for art contest?
studio – a movie or television company that produces shows or films
* The major Hollywood studios are making more movies this year than ever.
eye contact – looking directly at someone’s eyes while they look back at yours
* I had a fight with Dean yesterday and at today’s meeting, I tried to make eye contact with him, but he kept looking away.
to prep – to prepare; to get ready
* Let’s make this chicken for dinner tonight. Do you know how to prep it for cooking?
to be off – to be finished; to complete something and then leave
* We just need write this letter and then we’re off.
nevertheless – in spite of; however
* It’s raining very hard outside. Nevertheless, we need to find our missing dog before it gets dark!
despite – even though, in spite of
* Our city had a lot of visitors this year despite a very hot summer.
even though – despite; in spite of; although
* Even though they were friends, Bea decided not to lend a large amount of money to Josh because she didn’t think he could pay it back.
to screw up – to make a mistake; to make an error; to do something wrong
* Nick really screwed up on his class project and the teacher gave him a very poor grade.
What Insiders Know
Typecasting
When an actor plays a “memorable” (difficult to forget) role, he or she may get a lot of praise for their performance. However, there is a “downside” (problem) to playing a famous role: typecasting. “Typecasting” happens when an actor is strongly identified with a specific character and has difficulty getting other acting jobs because casting directors don’t think the audience will believe in them as a different character. For example, in the 1950s, the actor George Reeves who played the superhero Superman in a popular television series called The Adventures of Superman had a hard time finding other work in movies because of typecasting. In the 1970s, the actor, Mark Hamill, played the lead character Luke Skywalker in the very successful and popular Star Wars movies, and he also had difficulty finding other acting work.
Typecasting can also happen when an actor is identified as only good for certain acting roles because of a “character trait” (characteristic; feature) or because of their “ethnic” (related to a specific cultural or racial group) background. Beautiful blond actors may only get roles as dumb and “frivolous” (not serious; silly) women. An African American actor may easily get roles as rap singer, but has difficult getting the role of a scientist or a family man. An Asian American actor may get roles as the serious student or doctor, but gets “passed over” (dismissed; not considered) for the roles of a “leading man” (the main actor, usually in a romantic role).
Some actors, especially those who have already been successful, try to avoid typecasting. A recent example is the actor Daniel Radcliffe, who plays the character Harry Potter in the popular Harry Potter film series. After completing several Harry Potter films, he starred in a theater play where he plays a very “risqué” (surprising or shocking because of the sexual nature) role that involves adult themes and sex. By doing this play, he let people know that he was willing to move beyond the role of Harry Potter.