= 060
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''




- (060.) There have been attempts 尝试；努力 to explain these taboos 禁忌；忌讳 in terms of 就……而言 inappropriate 不适当的；不合适的 social relationships 关系 #*either*# （两者中的）任何一个,两者都（不） _between_ those who are involved 参与；卷入 _and_ those who are not simultaneously 同时地 involved in the satisfaction 满足；满意 of a bodily 身体的；肉体的 need, #*or*# _between_ those already satiated 吃饱的；满足的 _and_ those who appear to be shamelessly 不知羞耻地；无耻地 gorging 狼吞虎咽；暴食.




'''

一直存在一些尝试 (这些尝试的目的是去解释这些禁忌) 依据不恰当的社会关系 (这一概念)：要么是在那些人 (这些人是参与其中的) 与那些人 (这些人是没有同时参与其中的, 在满足一种身体需求的过程中) 之间，或者是在那些人 (这些人已经得到满足的) 与那些人 (这些人显得在不知羞耻地狼吞虎咽) 之间。



- (060.) There have been attempts to explain these taboos in terms of inappropriate social relationships either between those who are involved and those who are not simultaneously involved in the satisfaction of a bodily need, or between those already satiated and those who appear to be shamelessly gorging.

人们曾试图从不恰当的社会关系角度, 来解释这些禁忌，这种关系存在于以下两种情况：一是那些参与,和那些未同时参与身体需求满足的人之间，二是那些已经饱足,和那些似乎无耻地大吃大喝的人之间。

有一些试图［/使用不合适的社会关系/去解释这些禁忌，
（这些社会关系或者是在那些正在经历一种身体需要得到满足的人和此
时身体需要得不到满足的人之间的，或者是在那些已经吃饱的人和那些
看起来正在不知羞耻地狼吞虎咽的人之间的）］。

....
【主句】 There have been attempts
  │
  └─ 【不定式作定语】 to explain these taboos
       │
       └─ 【方式状语】 in terms of inappropriate social relationships
            │
            ├─ 【并列选择1】 either between those... and those...
            │    │
            │    ├─ 【those 的定语从句1a】 who are involved
            │    │
            │    ├─ 【those 的定语从句1b】 who are not simultaneously involved
            │    │       │
            │    │       └─ 【介词短语】 in the satisfaction of a bodily need
            │    │
            │    └─ 【并列连词】 or
            │         │
            │         └─ 【并列选择2】 between those... and those...
            │             │
            │             ├─ 【those 的定语(过去分词)】 (those) already satiated
            │             │
            │             └─ 【those 的定语从句2】 who appear to be shamelessly gorging
....

对于这些禁忌，一直存在着一些解释的尝试，其依据是认为其中存在不恰当的社会关系：要么是发生在正在满足某种身体需求的人与没有同时参与此事的人之间，要么是发生在已经酒足饭饱的人与那些显得在不知羞耻地狼吞虎咽的人之间。


.There have been attempts to explain these taboos

There have been attempts：不能翻译为“那里有尝试”。**这是一个表示“存在”的句型，意为“一直有（人）尝试”或“已有过尝试”，**暗示这是一种学术观点，不一定是作者的。

.inappropriate (a.) social relationships #either# _between_ those *who are involved* (v.) _and_ those *who are not simultaneously involved* in the satisfaction of a bodily need, #or# ...

those who are involved 和 those who are not simultaneously involved：*这里的 involved 特指参与“满足身体需求”* (in the satisfaction of a bodily need) *这个行为。必须将后面的介词短语联系起来理解，否则 involved 意义不明。翻译时必须将“在满足…过程中”这层意思整合进去。*


.inappropriate social relationships #either# ... , #or# _between_ *those already satiated* _and_ those who appear to be shamelessly gorging.

already satiated：**satiated 是正式用语，指“充分满足的”，**特指对食物或饮料的需求得到满足，即“吃饱喝足的”。不能简单译为“满意”。

shamelessly gorging： gorge 带有强烈的负面色彩，指贪婪、粗鲁地大吃大喝。shamelessly 加强了其不顾及社交礼仪的含义。翻译需体现出这种不顾形象的贪婪状态。


