= 079
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''



- (079.) `主` #An impact# 撞击；碰撞 后定说明 capable (a.)有能力的；有本领的 of *ejecting* 喷出；弹出 a fragment 碎片；碎块 of _the Martian 火星的 surface_ 表面 *into* an Earth-intersecting (交叉的，相交的)与地球相交的 orbit 轨道 `系` #is even less probable 更加不可能 than# such an event 事件 on the Moon, *in view of* 鉴于；考虑到 the Moon’s smaller size 体积 and closer proximity (n.)（时间、空间、关系的）靠近，亲近;接近；邻近 to Earth.

[.my2]
一次撞击 (这个撞击能够将火星表面的一块碎片, 弹射进入一个与地球轨道相交的轨道) 比起月球上这样一次事件, 是更加不可能的, 鉴于月球更小的尺寸,和更接近地球的距离。


[.my1]
.案例
====
- (079.) An impact capable of ejecting a fragment of the Martian surface into an Earth-intersecting orbit is even less probable than such an event on the Moon, in view of the Moon’s smaller size and closer proximity to Earth.

考虑到月球尺寸较小且离地球更近，能够将火星表面碎片 eject 到与地球相交的轨道上的撞击，比月球上发生此类事件的可能性更小。

....
【主句 (主系表结构)】
├─ 主语：An impact
│       │
│       └─ 【后置定语】 capable of ejecting a fragment
│               │
│               ├─ 【宾语】 a fragment
│               │       │
│               │       └─ 【后置定语】 of the Martian surface
│               │
│               ├─ 【方式状语】 into an Earth-intersecting orbit
│               │       │
│               │       └─ 【后置定语】 (an orbit) that intersects Earth's orbit
│               │               (Earth-intersecting 是复合形容词，意为“与地球轨道相交的”)
│               │
│               └─ 不定式短语：to eject... into...
├─ 系动词+表语：is even less probable
├─ 比较状语：than such an event
│       │
│       └─ 【后置定语】 on the Moon
└─ 【原因状语】 , in view of the Moon’s smaller size and closer proximity to Earth.
        │
        ├─ 宾语1：the Moon’s smaller size
        ├─ 连词：and
        └─ 宾语2：closer proximity
                │
                └─ 【后置定语】 to Earth
....


.`主` #An impact# 后定说明 _capable (a.)  of_ *ejecting* (v.) a fragment of the Martian surface *into* an Earth-intersecting orbit `系` #is even less probable# than such an event on the Moon, *in view of* the Moon’s smaller size /and closer proximity (n.) to Earth.


- Earth-intersecting orbit : 与地球轨道相交的轨道。指这块被抛射出的碎片运行的轨道，会在某一点,与地球绕太阳公转的轨道相交，从而存在与地球相撞 (或至少被地球引力捕获) 的可能性。这是火星陨石到达地球的必要轨道条件。

- such an event on the Moon : 月球上这样一次事件。such an event 指代前面描述的整个事件：一次能将月球碎片抛射到与地球轨道相交的撞击。

- **even less probable : 更加不可能。**even修饰比较级 less probable，表示程度的加强，强调火星发生此类事件的概率, “甚至比月球还要低得多”。


.proximity
(n.)  *~ (of sb/sth) (to sb/sth)* : ( formal ) the state of being near sb/sth in distance or time（时间或空间）接近，邻近，靠近 +

•a house *in the proximity of (= near)* the motorway 靠近高速公路的一座房子 +
•_The proximity of the college to London_ makes it very popular. 这所学院因靠近伦敦, 而备受欢迎。 +

•The area has a number of schools *in close proximity (n.) to each other*. 这个地区有许多学校比邻而立。 +
•the death of two members of her family _in close proximity_ 她的两个亲人, 在短时间内的相继去世
====

'''
