= 095
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


- (095.) Despite these vague 模糊的；不明确的 categories 类别；种类, `主` one `谓` should not claim 声称；断言 unequivocally 明确地；毫不含糊地 that /`主` hostility 敌意；敌对情绪 between recognizable 可识别的；可认出的 classes 阶级；阶层 `谓` cannot be legitimately 合理地；正当地 observed 观察到；注意到.

[.my2]
尽管存在这些模糊的范畴，人们不应明确无误地声称 (认为)：可识别的阶级之间的敌意不能被合理地观察到。

[.my1]
.案例
====
- (095.) Despite these vague categories, one should not claim unequivocally that hostility between recognizable classes cannot be legitimately observed.

尽管存在这些模糊的类别，但我们不应断然宣称，可识别阶级之间的敌意不能被合法地观察到。

尽管存在着这些模糊的分类，但是一个人仍然不应该/毫无
疑问地/说, 在可以被区分的阶级之间的敌意 不能够被合理地观察到。


.unequivocal
-> un +equivocal (模棱两可的；可疑的) = 明确的；不含糊的

equivocal -> 来自equal, 平等的。-voc, 说话，词源同voice, invoke.引申义模棱两可的。



.书作者解说

这里使用了三重否定：should not，unequivocally，和cannot。在这里，可以明显看出ETS在考查我们的阅读能力，因为如果想把句子说成肯定的语气, 而不改变句子的意思, 是很容易的：

Despite these vague categories, one may still claim definitely that
/`主` hostility between discernable (a.)可辨别的；可认识的 classes `谓` can be validly observed.

====

'''
