= 097
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


- (097.) It can be inferred 推断；推论 from the passage 段落；文章 that /the author 作者 *would be most likely to agree with* 最有可能同意 which of the following 下列的；接下来的 statements 陈述；表述 regarding 关于；至于 _socioeconomic 社会经济的 class_ 阶级；阶层 and _support 支持 for the rebel 反叛者；叛乱者 and Loyalist （美国独立战争时期的）亲英派；保皇党 causes_ 事业；目标 during the American Revolutionary War 美国独立战争（1775-1783年，英国在北美的13个殖民地反抗英国统治，最终建立美利坚合众国）?




'''

从文章中可以被推断出 (即)，本文作者最有可能同意以下哪一种陈述 (这些陈述是关于社会经济阶级, 以及对革命派和保皇派事业的支持，在美国独立战争期间的)？



- (097.) It can be inferred from the passage that the author would be most likely to agree with which of the following statements regarding socioeconomic class and support for the rebel and Loyalist causes during the American Revolutionary War?

从文章中可以推断出，关于社会经济阶层, 以及美国独立战争期间对叛军和保皇派事业的支持，作者最可能同意以下哪项陈述？

- socioeconomic class : 社会经济阶级。指根据经济地位和社会地位划分的群体，如上层阶级、中产阶级、下层阶级等。

- the _rebel and Loyalist_ causes : 革命派和保皇派的事业。rebel指美国独立战争中的革命者 (即“爱国者”)，寻求脱离英国独立；Loyalist指“效忠派”，忠于英国王室，反对独立。causes指他们各自追求的“事业”或“目标”。



