
= 0059 Tired Adults May Learn Language like Children Do 疲惫的成年人可能像孩子一样学习语言
:toc: left
:toclevels: 3
:sectnums:

'''

== Tired Adults May Learn Language like Children Do 疲惫的成年人可能像孩子一样学习语言

Lowered (v.) conscious reasoning `谓`  can aid sound-pattern recognition.

Children often learn new languages more easily than adults do, but it’s unclear why. Some hypothesize (v.)假设；假定 that /grasping a language requires (v.) absorbing subtle 不易察觉的；不明显的；微妙的 patterns unconsciously /and that adults’ superior （在级别、重要性或职位上）更高的 *conscious reasoning* interferes (v.)干涉；干预；介入. New research suggests that, indeed, grown-ups 成年人 *might just* be too smart for their own good.

... Those who tackled the difficult version /claimed greater *cognitive fatigue* 疲劳；劳累 afterward 以后，后来 —but performed (v.) better on the subsequent language task. The researchers hypothesize that /tired learners used (v.) less conscious analysis on the word rules: they were free to learn like a child.

Ghent University psychologist Eleonore Smalle, who spearheaded  (v.)领导 (一场运动或袭击) both papers, offers (v.) advice /based on her team’s findings. When beginning to learn a language, she says, immerse 使专心于 yourself in its sounds, even —or especially —while distracted 注意力分散的；思想不集中的. “Have a good glass of wine /while listening to a podcast in Italian,” she suggests with a laugh. “Why not? It could help.”


[.my1]
.标题
====

降低有意识的推理, 可以帮助声音模式识别.

儿童通常比成人更容易学习新语言，但原因尚不清楚。一些人假设掌握一种语言需要无意识地吸收微妙的模式，而成年人的高级意识推理会干扰。新的研究表明，事实上，成年人可能只是为了他们自己的利益而太聪明了。

... 那些解决了困难版本的人后来声称有更大的认知疲劳——但在随后的语言任务中表现更好。研究人员假设，疲倦的学习者对单词规则的意识分析较少：他们可以像孩子一样自由学习。

根特大学心理学家 Eleonore Smalle 是这两篇论文的带头人，她根据她团队的发现提出了建议。她说，当开始学习一门语言时，让自己沉浸在它的声音中，即使——或者尤其是——在分心的时候。 “一边听意大利语播客，一边喝一杯好酒，”她笑着建议道。 “为什么不？这可能会有所帮助。”

====






'''


== Tired Adults May Learn Language like Children Do



Lowered conscious reasoning can aid sound-pattern recognition.

Children often learn new languages more easily than adults do, but it’s unclear why. Some hypothesize that grasping a language requires absorbing subtle patterns unconsciously and that adults’ superior conscious reasoning interferes. New research suggests that, indeed, grown-ups might just be too smart for their own good.

... Those who tackled the difficult version claimed greater cognitive fatigue afterward—but performed better on the subsequent language task. The researchers hypothesize that tired learners used less conscious analysis on the word rules: they were free to learn like a child.

Ghent University psychologist Eleonore Smalle, who spearheaded both papers, offers advice based on her team’s findings. When beginning to learn a language, she says, immerse yourself in its sounds, even—or especially—while distracted. “Have a good glass of wine while listening to a podcast in Italian,” she suggests with a laugh. “Why not? It could help.”




