
= 0166. Mucus Saves Your Life Every Day 粘液每天都在拯救你的生命
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css


'''

== Mucus Saves Your Life Every Day 粘液每天都在拯救你的生命

it was just on a whim that he added some of his nasal mucus to the petri dish of bacteria. Several weeks later he noticed that the bacteria were being dissolved by something that had come from his mucus. That something, Fleming soon discovered, was a protein that would be called lysozyme, which literally means “an enzyme with power to dissolve.” It was an antibiotic—in his snot! His discovery showed that mucus, this stuff commonly thought of as just gunk and waste, was far from it.
Fleming soon found lysozyme in all sorts of human secretions: spit, blood serum and especially tears.

[.my2]
(1921年)他只是一时兴起将一些鼻粘液添加到细菌培养皿中。几周后，他注意到细菌被来自他粘液的东西溶解了。弗莱明很快发现，*这是一种被称为"溶菌酶"的蛋白质，字面意思是“一种具有溶解能力的酶”。* 那是一种抗生素——在他的鼻涕里！他的发现表明，粘液这种通常被认为只是垃圾和废物的东西远非如此。弗莱明很快**在各种人类分泌物中发现了"溶菌酶"：唾液、血清，尤其是眼泪。**

But lysozyme—and any more of mucus’s potential secrets—were overshadowed by a discovery Fleming made about seven years later: the much more potent antibiotic penicillin.

[.my2]
但是溶菌酶——以及粘液的更多潜在秘密——被弗莱明大约七年后的一项发现所掩盖：更有效的抗生素"青霉素"。


Around the same time, scientists were learning that mucus also seemed to have a potent ability to protect the body’s tissues. They experimentally tested that by placing frog legs in acid, and in the absence of mucus, they dissolved. They disintegrated, basically.


[.my2]
大约在同一时间，科学家们发现, *粘液似乎也具有保护身体组织的强大能力。他们通过将青蛙腿放入酸中进行实验测试，在没有粘液的情况下，它们会溶解。他们基本上解体了。*


We are finding mucus is compromised in a number of diseases or conditions, including inflammatory bowel disease, cystic fibrosis, certain forms of dental cavity formation, certain forms of infertility. So there are a number of conditions that could benefit, probably, from us being able to repair mucus.

[.my2]
*我们发现粘液在许多疾病或病症中受到损害，包括炎症性肠病、囊性纤维化、某些形式的牙洞形成、某些形式的不孕症。因此，我们修复粘液的能力, 可能会对许多疾病的治疗有益。*



Mucus is mighty stuff. Based on conservative estimates, it covers more than 1,000 square feet of your lungs and gut alone. It's also part of the film on your eyeballs, the saliva in your mouth and the coating of your reproductive tract. And producing it is a huge operation. Ribbeck says we replenish those surfaces by making more than a quartof mucus a day.

[.my2]
粘液是一种很强大的东西。根据保守估计，仅肺部和肠道就覆盖了 1,000 多平方英尺。它也是眼球薄膜、口腔唾液和生殖道涂层的一部分。生产它是一项巨大的工作。里贝克说，我们每天会产生超过一夸脱的粘液来补充这些表面。


The basic building blocks of mucus that give mucus its gooey nature are these threadlike molecules—they look like tiny bottlebrushes—that display lots and lots of sugar molecules on their backbone. And these sugar molecules—we call them glycans—interact with molecules from the immune system and microbes directly. And the exact configuration and density of these sugar molecules is really important for health.

[.my2]
赋予粘液"粘稠性质"的粘液的基本组成部分, 是这些线状分子——它们看起来像小瓶刷——在它们的骨架上显示出大量的糖分子。这些糖分子（我们称之为聚糖）直接与免疫系统和微生物的分子相互作用。这些糖分子的精确结构和密度, 对于健康非常重要。

in part, these sugar molecules entice microbes. These sugar molecules are special—they don’t exist in many other places in nature. That’s really important because that now allows the mucus barrier to attract microbes that can selectively eat [and] metabolize these complex sugar molecules.
And this is how mucus can really collect and select microbes that together then form a microbiota that has specific functions that will support your body. In the gut, you’ll have a different combination of microbes that grow on you than in your mouth, for example, or in the vaginal tract.
So it’s sort of advertising different things on its surface to attract the community that is most beneficial for that part of the body.


[.my2]
这些糖分子在一定程度上会吸引微生物。这些糖分子很特殊——它们在自然界的许多其他地方都不存在。这非常重要，因为现在粘液屏障可以吸引微生物，这些微生物可以选择性地吃掉[并]代谢这些复杂的糖分子。这就是粘液如何真正收集和选择微生物的方式，然后形成一个微生物群，具有特定的功能，将支持你的身体。在肠道中，生长在你身上的微生物组合, 与在口腔或阴道中生长的微生物组合不同。所以它在它的表面宣传不同的东西, 来吸引对身体那部分最有益的群体.


When mucus is not produced in the right amounts or the chemistry is not correct, then certain pathogens that otherwise are kept in check can now begin to outgrow the community and cause infections. And in other cases, the anchor points that certain microbes need to become residents are missing, and then they will no longer reside on the body surface, and a number of microbes are really, really important for our health.

[.my2]
当粘液产生的数量不正确, 或化学成分不正确时，某些原本受到控制的病原体, 现在可能会开始超出社区范围并引起感染。在其他情况下，某些微生物需要成为居民的锚点缺失了，然后它们将不再居住在身体表面，许多微生物对我们的健康非常非常重要。


'''

== (pure) Mucus Saves Your Life Every Day




it was just on a whim that he added some of his nasal mucus to the petri dish of bacteria. Several weeks later he noticed that the bacteria were being dissolved by something that had come from his mucus. That something, Fleming soon discovered, was a protein that would be called lysozyme, which literally means “an enzyme with power to dissolve.” It was an antibiotic—in his snot! His discovery showed that mucus, this stuff commonly thought of as just gunk and waste, was far from it.
Fleming soon found lysozyme in all sorts of human secretions: spit, blood serum and especially tears.


But lysozyme—and any more of mucus’s potential secrets—were overshadowed by a discovery Fleming made about seven years later: the much more potent antibiotic penicillin.


Around the same time, scientists were learning that mucus also seemed to have a potent ability to protect the body’s tissues. They experimentally tested that by placing frog legs in acid, and in the absence of mucus, they dissolved. They disintegrated, basically.



We are finding mucus is compromised in a number of diseases or conditions, including inflammatory bowel disease, cystic fibrosis, certain forms of dental cavity formation, certain forms of infertility. So there are a number of conditions that could benefit, probably, from us being able to repair mucus.




Mucus is mighty stuff. Based on conservative estimates, it covers more than 1,000 square feet of your lungs and gut alone. It's also part of the film on your eyeballs, the saliva in your mouth and the coating of your reproductive tract. And producing it is a huge operation. Ribbeck says we replenish those surfaces by making more than a quartof mucus a day.



The basic building blocks of mucus that give mucus its gooey nature are these threadlike molecules—they look like tiny bottlebrushes—that display lots and lots of sugar molecules on their backbone. And these sugar molecules—we call them glycans—interact with molecules from the immune system and microbes directly. And the exact configuration and density of these sugar molecules is really important for health.


in part, these sugar molecules entice microbes. These sugar molecules are special—they don’t exist in many other places in nature. That’s really important because that now allows the mucus barrier to attract microbes that can selectively eat [and] metabolize these complex sugar molecules.
And this is how mucus can really collect and select microbes that together then form a microbiota that has specific functions that will support your body. In the gut, you’ll have a different combination of microbes that grow on you than in your mouth, for example, or in the vaginal tract.
So it’s sort of advertising different things on its surface to attract the community that is most beneficial for that part of the body.




When mucus is not produced in the right amounts or the chemistry is not correct, then certain pathogens that otherwise are kept in check can now begin to outgrow the community and cause infections. And in other cases, the anchor points that certain microbes need to become residents are missing, and then they will no longer reside on the body surface, and a number of microbes are really, really important for our health.


'''