= 1639
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 334.
This is English as a Second Language Podcast’s English Café episode 334. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English.
On this Café, we’re going to talk about another one of our great National Parks in the United States, the Grand Teton National Park. We’ll also continue our series famous songs. We’ll be talking today about a song called “She’ll Be Coming ‘Round the Mountain.” And, as always, we’ll answer a few of your questions. Let’s get started.
Our first topic on this Café is the Grand Teton National Park. Grand Teton National Park is in the northwestern part of the State of Wyoming. Wyoming is in the central western part of the United States. It’s next to Montana; Montana is to the north. Colorado is to the south. The park is named after the Teton (Teton) Range. A “range” is a line of mountains that are connected together. The Teton Range is part of the Rocky Mountains, in the western United States and Canada.
Grand Teton National Park covers or has a size of about 310,000 acres. It includes the major or most important peaks in the Teton Range. A “peak” (peak) is the top or highest point of a mountain. Grand Teton National Park also includes a very beautiful valley. A “valley” is the low area in between two mountains. The valley is called the Jackson Hole Valley. It is, in fact, a beautiful area. I was in the Grand Teton National Park many years ago, almost 40 years ago, and it is very beautiful.
The National Park is just 10 miles south of another famous National Park, Yellowstone, which we talked about in English Café 88. The two National parks are connected by other federal or nationally owned land. It is, in fact, what is called the largest intact ecosystem of its type in the world, these two parks combined. When we say it’s “intact” (intact) we mean it is unbroken, it is one piece. This area is one of the largest intact ecosystems or biological environments in the world. It was first protected by federal law back in the late 19th century, but it didn’t become a National Park until 1929. There have been additional lands that have been added to the Park since 1929, but it is quite old.
Grand Teton National Park is home to many different plant and animal species, or types of plants and animals. There are many moose, bison, black bears, and wolves. A “moose” (moose) is the same in the singular or plural; it’s one of those words where even if you say “two” or “three, it’s still “moose,” we don’t say “mooses.” We say “three moose, two moose, one moose.” It’s a kind of large elk or a deer with very large ears; that’s what a moose is. A bison is also the same in singular and plural; we have one bison or many bison. A “bison” is like a buffalo, or a very, very large cow, you can think of it, with lots of heavy hair.
People who visit Grand Teton National Park can enjoy stunning views of the Rocky Mountains. Something that is “stunning” (stunning) is very beautiful, very impressive. You could say a woman wearing a beautiful dress looks stunning; she looks very beautiful, you stop. “To stun” (stun), as a verb, usually means to shock or surprise someone, often in a negative way. But here it’s used in a positive way to mean very, very beautiful.
The Grand Teton National Park, I mentioned, also has many lakes – or if I didn’t mention, I’ll say it now: it has many beautiful lakes. These lakes were formed or by glaciers. A “glacier” (glacier) are basically large pieces of ice – large rivers of ice that move very slowly over very long periods of time. In fact, the word “glacial,” as an adjective, means something that moves extremely slowly. These large glaciers created these lakes. These lakes, in this case, send their water into something called the Snake River, which runs through the park from north to south.
Grand Teton National Park has several visitor centers. A “visitor center” is a building where you, as a visitor, can get information about that park or that area. Grand Teton also has several large lodges. A “lodge” (lodge), as a noun, is a very large building, usually made out of wood or rock, where you can spend your time. It’s basically a big hotel – an old hotel. Several of the National Parks in the United States and in Canada have large hotels inside them that are called lodges, because they are made in a certain style, usually out of wood and rock.
Grand Teton National Park is a nice place if you like to hike – if you like to walk around in the mountains or in nature. It’s a good place if you like to bike – go on your bicycle. It’s a good place if you like to fish. You can also do horseback riding and watching birds. So these things – hiking, biking, fishing, horseback riding, and bird watching – are all things that I do not enjoy doing, so there’s really no reason for me to go to Grand Teton National Park. Actually, I did enjoy it when I was there because it’s very beautiful to look at. I’ll let everyone else do the hiking and the biking!
In the wintertime, you can also go snowshoeing in the park. “Snowshoeing” is when you put on these big – they’re not really shoes, they look more like, um, what’s the word I’m thinking of? They look more like tennis rackets that you put on your feet, and they allow you to walk in deep snow. I’ve been snowshoeing in Minnesota several times; I did so when I was younger. Can’t say I really enjoyed it, but it is good exercise
In any case, Grand Teton National Park is a beautiful part of the country, and if you’re going to the western part of the United States and you have some extra time to drive from, say, San Francisco or from Denver, Colorado, it is a beautiful area to see, both the Yellowstone and the Grand Teton National Parks.
I should probably mentioned that the word “teton” (teton) is somewhat controversial in that people have different explanations as to why the mountains are called the Teton Range and the park Grand Teton National Park. Some people believe that it comes from the Teton Indians, the Sioux Indians in that part of the country. It was the western group of Sioux Indians. The Sioux Indians were Indians – American Indians or Native Americans – that lived in the Midwest and western part of the U.S., in the northern part of the United States. That’s one explanation. Other people believe that it was a name given to these mountains by either the French or the Indians traveling with the French. “Teton” is related the French word for “teat” (teat) in English, which is a woman’s breast. You can imagine mountains perhaps reminding a lot of men, by themselves, of a woman’s breast, and so that’s another possible explanation. In English, the more common informal word for this would be “tit” (tit), however that’s considered by many people to be maybe not vulgar, but certainly very informal, not a word to use in front of your children or your boss.
Now let’s move on to our next topic, which is a famous folk song in American history. The song is called “She’ll Be Coming ‘Round the Mountain.” The phrasal verb “to come around,” in this case is abbreviated “come ‘round,” we drop the “a,” is an informal way of saying “to come,” especially when you are moving around something else. “To come around the mountain” would mean not to go to the top and then to the bottom of the mountain, not to go over the mountain, but to go in the land, the valleys in between the mountains; that would be to come around a mountain. “To come around,” as a phrasal verb, can also mean to change your mind, to change your opinion on something. But here it means the more literal definition of to move from one place to another, to come to one place.
Like a lot of great American music, or music we associate with the United States, this song comes from the African American community. It was originally what’s called an African American spiritual. A “spiritual” (spiritual) is a religious song. Spirituals were religious songs that were created and sung by black slaves in North America. The spiritual, in this case, was about the second coming of the founder of the Christian religion, Jesus Christ. According to Christian beliefs, you may know, Jesus is the Son of God, and one day he will return to Earth. You’ll remember he was born 2,000 years ago and then died, and according to Christian theology went to heaven, and he will come back to Earth someday, and when he does that will be the end of time, that will be the end of our current way of living. So, the “second coming” is the second return of Jesus, his return back to Earth – to our planet.
Now the “she” in this song is not a woman. When we say “she’ll be coming ‘round the mountain,” we’re not referring to woman or a girl; we’re referring to the vehicle in which Jesus will return to Earth. A “vehicle” is like a car or a truck, something that moves you from one place to another. Now Jesus, in the song, will be returning in a chariot. A “chariot” (chariot) is a small vehicle with two wheels that’s pulled by a horse. If you’ve ever seen movies about ancient Rome, they often have chariot races in them. A very famous movie from my youth was Ben Hur, with Charlton Heston, and in the movie there are these chariot races. I think more recently the Russell Crowe movie Gladiator might also of had a chariot race. Is that right? I don’t remember; didn’t really like that movie so don’t remember it very well. Anyway, chariot races, then, were popular among, we are told, the ancient Romans, at least according to Hollywood. Well Jesus, then, will be returning in one of these vehicles, in a chariot. One of the lines in the original song is “O, who will drive the chariot when she comes?” So the “she” is the chariot.
The modern version of “She’ll Be Coming ‘Round the Mountain,” however, is not considered by most people to be a spiritual, it’s thought of more as a children’s song. So instead of talking about Jesus’ second coming, the original meaning, now it’s more about when someone is going to visit you and stay with you. So, it could be about any person or any woman. So in the modern version it is a woman – the “she” is a woman.
The original song was written in the late 19th century, and like a lot of songs, there are many different versions of this song – I should say a lot of folk songs, there are many different versions. Here’s the song that I remember, and this is a song that most American children are taught at some point in their young lives [Jeff sings]:
She’ll be coming ‘round the mountain when she comes,
She’ll be coming ‘round the mountain when she comes,
She’ll be coming ‘round the mountain, she’ll be coming ‘round the mountain,
She’ll be coming ‘round the mountain when she comes.
Very complicated lyrics! Just one sentence repeated over and over again. “She’ll be coming ‘round the mountain when she comes,” the idea is that when she does actually arrive she’s going to arrive by coming around the mountain.
The other parts of the song are the same; they’re a repetition of one line. Here’s another verse – another part of the song [Jeff sings]:
She’ll be drivin’ six white horses when she comes,
She’ll be drivin’ six white horses when she comes,
She’ll be drivin’ six white horses, she’ll be drivin’ six white horses,
She’ll be drivin’ six white horses when she comes.
To “drive” a horse means to ride it, to lead it in a certain direction to control where it goes. So this woman, whoever she is, will be driving or riding six white horses when she arrives – when she comes here. Another verse is “Oh we’ll all come out to meet her when she comes,” we’ll all go and be there when she arrives. Or, “We’ll kill the old red rooster when she comes.” A “rooster” is a kind of chicken. I’m not sure why we’ll kill the old red rooster, I guess to eat it. I’m not sure.
Sometimes children make funny songs at the end of each line, so when they sing, for example, “Oh we’ll all come out to meet her,” they might say something like, “Howdy, ma!” which means hello mom. “Howdy” is another way – an old-fashioned way of saying hello. “Ma” (ma) is short for mom or mother. Sometimes when the song is sung with children, and they use the line “We will kill the old red rooster,” they might make a noise of a rooster – a male chicken.
It’s a fun song, and if you want to hear more of it, you can find many recordings of it online I’m sure.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Saroch (Saroch) in Thailand. The question has to do with the words “congratulations,” “thanks,” and “kudos.”
“Congratulations” is something you say to someone who has done something well, or who has achieved or accomplished something. We often say this to someone, for example, who has gotten married: “Congratulations.” Or, they had a new baby: “Congratulations.” Or they won some prize or won some contest; all these would be situations in which we would say “congratulations.” Notice that there’s an “s” at the end of the word. The same is true for the word “thanks” and “kudos.” However, “thanks,” as a noun, is used when you are expressing your appreciation to someone. It always is plural; you would say, “Many thanks for helping me,” or, “I want to give you my thanks for everything you’ve done for me.” We never say, “I want to give you a thank,” it would always be “thanks,” plural, just like “congratulations” has an “s” at the end.
The other expression, “kudos,” ends in an “s,” technically it’s a singular word, but everyone uses it as a plural word, so in real life it’s always plural. It is also an expression used, but not for thanks, but for praising someone. It’s closer to “congratulations.” “I heard you got a new job. Kudos to you.” Or, “Kudos for your good work.” You are praising them; you are saying something nice about them, perhaps congratulating them.
Edward (Edward) from Malaysia wants to know how we use the word “literally.” This is an interesting question, because the meaning of the word “literally” has changed in the last, oh, maybe 20-25 years, maybe longer. But let’s start with the actual dictionary definition, at least traditionally, of “literal.”
“Literal” means exact or factual. I have very literal mind; if you say to me, “It’s raining cats and dogs outside,” which is an expression we use to mean that it’s raining a lot – it’s raining very hard, I would think of actual cats and dogs falling down from the sky to the ground. That would be a literal interpretation, that there are actually little cats and little dogs that are falling down from the clouds. Of course, that’s not what we mean when we use that expression. But if I were to interpret it literally, that is what I would think of. The opposite here of “literal” would be “figurative” (figurative). “To speak figuratively” means to use what are called “metaphors.” “Love is a rose.” Well, love isn’t actually, literally a rose, but we can use that metaphor – that equation, that equaling, love equals rose – to speak figuratively. We might also call this “symbolic” language. “Literally” also can mean really or actually, in a way that is factually true. For example, if someone smokes a lot, and then they get cancer – lung cancer you could say, “Well, if they continue smoking they could literally kill themselves.” They would actually kill themselves; we’re not speaking figuratively, we’re not using “kill” as some sort of symbol. We mean you will actually die. That’s the traditional dictionary definition of “literally.”
However, more recently people have begun to use “literally” when they just want to add emphasis. Let’s say you eat chicken every day, and eventually you get tired of eating chicken. You might say, “If I eat another piece of chicken I will literally kill myself.” But of course, you aren’t going to actually kill yourself; you’re using “literally” to provide some sort of emphasis, to show how strongly you feel about something. In fact, you’re using “literally” in a figurative way, just the opposite of what it traditionally has meant. You hear this all time now; if you are watching television, listening to an interview, you will hear people say “literally” when, in fact, they are just trying to emphasize something, that it’s not literal at all, and that’s why it’s a little confusing when you hear this expression nowadays. It’s one of those words that has come to mean the opposite of what it used to mean, or at least what it means in a formal, traditional sense.
Finally Lucas (Lucas) in Brazil wants to know the meaning of the expression “take the time” or “to take the time.” “We need to take the time to do (something).” This means we need to do something carefully, thoroughly, without going fast, without rushing it, to be very careful about it. “I need to take the time to understand this problem if I am going to find a solution.” I can’t rush it; I can’t go quickly.
There’s a similar sounding expression, “to take your time,” or, “to take (one’s) time.” There, you’re saying that you’re going to go slowly, but you’re telling the person I’m not going to be in a hurry. “To take the time” means to spend the time necessary to do something; “to take your time” means to go slowly even if you don’t really have to go slowly. Someone may say, “Here’s a book I want you to read. You don’t need to return it to me quickly. Take your time.” In other words, there’s no rush. But if someone says, “Here’s an important document (an important piece of paper, an article) I want you to read, take the time to understand it very well so that you can explain it to everyone else.” That’s a little different, although normally “take the time” is not a command, it could be used that way, as I just did.
We try to take the time to answer your questions thoroughly here on ESL Podcast. If you have a question or comment, you can email us at eslpod@eslpod.com. No hurry, take your time! Whenever you email us will be fine.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2012 by the Center for Educational Development.
Glossary
range – a line of mountains that are connected by high land; a line of uninterrupted mountains
* In the story, no one had ever traveled over the high mountain range to see what’s on the other side.
intact – unbroken; not damaged; complete
* Jelissa saw that the high winds had blown down a few trees, but the buildings were intact.
stunning – very impressive, beautiful, or surprising
* Our team was not expected to win the championship, but at the last minute, we scored three points for a stunning victory.
glacier – very large rivers of ice that move very slowly over very long periods of time, changing the shape of the rocks and land underneath them
* While sailing in Alaska, the last thing you want is to encounter an unexpected glacier.
lodge – large buildings, usually made out of wood and/or large rocks, where people can spend the night, near areas of nature and wilderness
* Every winter we spend a week at a ski lodge in Aspen, Colorado.
snowshoeing – an activity where people wear snowshoes (device with a flat wide bottom) on the bottom of their boots so that they can walk on top of the snow without sinking into it
* Let’s go snowshoeing to the top of that hill and build a snowman.
to come around – to follow a curve in the road or path as one travels toward something or someone
* From here, we can see anyone coming around the bend in the road and stop them before they get too far.
spiritual – a religious song created and sung by the black slaves in North America
* Everyone joins in when we sing spirituals in church each Sunday.
second coming – the Christian belief that Jesus Christ, the son of God, will return to Earth at some point in the future
* Many people have tried to predict the date of the second coming based on information in the Bible.
chariot – a small vehicle with two wheels, pulled by a horse
* Chariot races were very popular in ancient Rome.
howdy – hello; hi; an informal greeting
* When we drove up to the gate, the gatekeeper asked, “Howdy, who are you here to see today?”
rooster – male chicken; cock
* If you live on a farm, you’ll hear the rooster crowing each morning.
congratulations – the act of showing happiness when someone has a good result or achievement
* Mona’s father gave her a briefcase as a gift of congratulations for getting her first job.
thanks – a feeling of gratefulness; a feeling of appreciation
* I wrote my professor a letter of thanks for his help in getting my scholarship.
kudos – praise; an expression to tell someone he or she has done well
* Kudos to Kamal for being the only one who worked overtime to finish the project on time.
literally – really; actually; in a way that is factually true; used figuratively to add emphasis (a sense of importance)
* It is literally 255 miles from Los Angeles to my hometown, but it feels like it takes literally years to drive there!
to take (the) time – to do something carefully or thoughtfully, without rushing; to make a decision to set aside time to do something when one is busy
* Let’s take the time to draw all of these lines on our map correctly, so we don’t make any mistakes and have to do it all again.
What Insiders Know
Plains Indian Sign Language
It may surprise you to know that in North America, there are “approximately” (not exactly, but close to) 300 “indigenous” languages spoken. The word “indigenous” means native, or something that originally came from or naturally belongs in a place. In the U.S., we talk about “indigenous peoples,” “indigenous foods,” “indigenous plants,” and much more.
The indigenous or Native Americans living in “The Great Plains” spoke 37 different languages. “The Great Plains” in the U.S. includes states in the central part of the country: Colorado, Kansas, Montana, Nebraska, New Mexico, North Dakota, Oklahoma, South Dakota, Texas, and Wyoming. With so many languages “coming into contact” (meeting each other), the Native American “tribes” or groups needed a way to communicate. These tribes developed and used the Plains Indian Sign Language (PISL).
“Sign languages” use the hands to communicate, rather than one’s voice. While most “sign languages” are used by the “deaf” (people who cannot hear), the Plains Indian Sign Language was used by the “hearing” (people who can hear) to communicate when two languages were “unintelligible” (not comprehensible; not able to be understood) to each other. Using the PISL, Native Americans living in the Great Plains could communicate for many purposes, including “diplomacy” (official relations between countries or groups of people) and “trading” (the exchange of things of value between people or organizations).
The PISL may have been used on the Great Plains as early as 1541. By 1885, about 100,000 people knew and used the sign language. However, only a very small number people know the language today.