= 1641
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 336.
This is ESL Podcast’s English Café episode 336. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. If you go there you can visit our ESL Podcast Store, which has some additional premium courses in business and daily English. You can also become a member of ESL Podcast and download the Learning Guide for this episode. The Learning Guide contains the complete transcript of this episode – everything we say, as well as the vocabulary words, definitions, sample sentences, cultural notes, and a short comprehension quiz. Go to our website for a sample Learning Guide to see what you’re missing.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech – at a normal speed, in other words. Today we’re going to talk about authors who publish their own books, what is called “self-publishing.” And, as always, we’ll answer a few of your questions. Let’s get started.
Our topic on this Café’s Ask an American segment is self-publishing. That’s when authors – writers – try to get their books published on their own, without using a book publishing company as authors traditionally have done.
We’re going to begin by listening to an author named Patricia Ruth. She wrote and self-published a “novel,” a fictional book called Holly Heights. We’ll listen first. Try to understand as much as you can, and then we’ll go back and explain what she said. Let’s listen:
[recording]
I did try to go the traditional publishing route by, you know, sending inquiries to agents and publishers. I’m a member of a very popular club of authors that get rejected from agents and publishers. I mean I would get rejections from agents. It would come on a strip of paper, like maybe two inches long, I mean not even the courtesy of a full page letter. I mean it’s outrageous some of the stuff that you get back.
[end of recording]
Ruth begins by saying, “I did try to go the traditional publishing route.” A “route” (route) – or a “route,” it can be pronounced either way – is usually a road or a path, a way to get somewhere. We often talk about routes when we’re discussing which way we drive. “What route do you take to get downtown from where you live?” In other words, what roads, what streets do you take, or freeways as in the case of Los Angeles. Ruth says that she tried to go the traditional publishing route by, you know, sending inquiries to agents and publishers. She tried to use the large book publishing companies to have her book published. She did that by sending inquiries to agents and publishers. An “inquiry” would be a letter asking if they were interested, in this case, in her book. An “agent,” in this case a literary agent, is a person whose job it is to help writers find a publisher, find someone who will take their writing – their manuscript – and turn it into a book. You can have an agent for acting. Actors here in Los Angeles, most of them, have their own agent, someone who goes and finds work for them. Ruth sent letters to agents and “publishers,” the companies that actually make the books.
She says that she is a member of a very popular club of authors, or writers, that gets rejected from agents and publishers – or by agents and publishers. She’s not actually a member of a group – of a club; she’s saying that she is one of the many people who have had similar experiences; in this case, the experience is getting rejected. “To be rejected” means someone says no to you. This, of course, happens to men all the time; they get rejected. And I suppose it happens to women, also, when the other person isn’t interested in you as you are in them. I have a lot of experience in this area! But, as an author you can also be rejected. A publishing company can say, “No, we don’t want to publish your book. We don’t think it’s good enough.” Rejections are very, very common in publishing, including academic publishing. When you’re a professor and you write an article, you could send it to a scientific journal, like a magazine for scientific articles, and your article will probably, in most cases, get rejected at least once. That’s quite common.
Well, Ruth was angry, I think here, because she would get rejections from agents and, she says, “It would come on a strip of paper, maybe two inches long.” A “strip of paper” is a small piece of paper. She says, “I mean not even the courtesy of a full page letter.” That is, the agents would not even send a regular piece of paper with a regular a letter; they would just send a little strip of paper, a small part of one piece of paper rejecting the manuscript. She says they did not even give her or have the courtesy. A “courtesy” (courtesy) is something nice that we do, something polite like writing a thank you letter or a thank you note after someone gives you a gift. She thinks that the agents were not very courteous to her. She says, “it’s outrageous some of the stuff you get back.” Something that is “outrageous” (outrageous) is very shocking, very surprising but in usually a very negative way, something that is very, very odd or unusual. Sometimes “outrageous” just means wild, especially if we’re talking about clothing. We may say, “He had this outrageous shirt,” or, “this outrageously crazy shirt,” something like that. But normally, “outrageous” is a negative thing meaning something that’s very shocking.
Let’s listen again as Ruth describes her experiences one more time.
[recording]
I did try to go the traditional publishing route by, you know, sending inquiries to agents and publishers. I’m a member of a very popular club of authors that get rejected from agents and publishers. I mean I would get rejections from agents. It would come on a strip of paper, like maybe two inches long, I mean not even the courtesy of a full page letter. I mean it’s outrageous some of the stuff that you get back.
[end of recording]
Next we’re going to listen to someone with a very different viewpoint – a very different opinion. His name is Lorin Rees. He is one of the agents that Patricia Ruth was referring to earlier. He represents authors and sends their manuscripts to traditional publishing companies. Let’s listen as he talks about what is involved, in his opinion, in self-publishing.
[recording]
Obviously self-publishing gives a lot more control to the author and allows them to fulfill their goals without having to go through a pretty difficult, tiresome, and lengthy process, fraught with rejection. However, there are significant limitations to self-publishing, particularly distribution, packaging, editorial support, and credibility.
[end of recording]
Rees begins by saying that obviously – clearly – self-publishing gives a lot more control to the author and allows them to fulfill their goals. To “fulfill” (fulfill) means to complete or finish something. “My goal is to exercise every day for one hour.” That’s my goal; that’s what I want to achieve or accomplish. To fulfill my goal would be to actually do that every day instead of watching television or eating potato chips – which I love to eat, by the way! Well, that’s what fulfilling a goal is.
Rees says that self-publishing gives the author a lot of control and allows them to fulfill their goals – to do what they want to do, to publish their book – without having to go through a pretty difficult, tiresome, and lengthy process, fraught with rejections. Couple of vocabulary terms there. First, “tiresome” (tiresome) is something that makes you tired, it’s exhausting, it makes you weary (weary). Something that is tiresome requires a lot of work and attention; it’s difficult. Rees says that this process can be pretty or very difficult, tiresome, and lengthy. “Lengthy” means it takes a long time. This process, he says, is fraught (fraught) with rejections. We use the phrase “fraught with” to describe something that is full of problems or worries, something that would cause us to be very concerned about something.
Rees says that there are, however, significant limitations to self-publishing, things that self-publishing cannot give you the way it can be given you by a traditional publisher. He says these things include distribution, packaging, editorial support, and credibility. “Distribution” comes from the verb “to distribute” (distribute), which is to give to other people or to send to other places. “I’m going to distribute my book.” I’m going to give everyone a copy by going to a party or standing on the street and saying, “Hey, take my book.” Well, that’s a way of distributing something. Self-publishing has more difficulty in distribution because they don’t have a big company that will send it to all the bookstores for you, for example. There’s also a problem with self-publishing when it comes to packaging. “Packaging” is actually physically producing the book and sending it to somewhere. “Editorial support” is another way of saying you have people who look at your manuscript – at what you wrote. They check for the spelling; they make sure that the grammar is correct. That’s editorial support that a traditional publisher gives an author. Finally, he says self-publishing doesn’t have the same credibility. “Credibility” (credibility) means that people take you seriously, people see you as a real writer – as a real author.
Let’s listen to Rees, who remember works for the traditional publishing industry or business, talk about self-publishing one more time.
[recording]
Obviously self-publishing gives a lot more control to the author and allows them to fulfill their goals without having to go through a pretty difficult, tiresome, and lengthy process, fraught with rejection. However, there are significant limitations to self-publishing, particularly distribution, packaging, editorial support, and credibility.
[end of recording]
Our final quote comes from Johnson McKee, the managing director of a company called CreateSpace, which is part of Amazon.com. They have a part of their company that helps people publish their own books. Let’s listen.
[recording]
Since 2002, the growth of independently published books is over 8,000 percent. So there’s really a movement in the industry and because anyone who wants to tell their story can be out there. And I think that trend of democratization of the publishing process will continue.
[end of recording]
McKee says that, since 2002 – since the year 2002 – the growth of independently published books, books that are not published by big companies, is over 8,000 percent. “So,” she says, “there’s really a movement in the industry.” A “movement” here means something that is changing in society, something that is changing in the world that affects a lot of people. She says there’s a movement in the industry and because anyone who wants to tell their story can be out there. If you want to tell your story, you want other people to hear what you have to say. “To be out there” means that people can find you. This is one of the things the Internet allows us to do now; you can find people who are not working for a big company, but you can still hear their voice, you can still read what they have to say. Obviously, ESL Podcast is an example of a small, independent publishing outfit or organization. Book publishing is also benefiting from the Internet in that way, electronic distribution of books.
McKee says, “I think that trend of democratization of the publishing process will continue.” A “trend” is the tendency of something to increase or decrease. You could talk about the trend in home prices. Are they generally getting more expensive or are they getting cheaper? “Democratization” refers to a change in the way a government or an industry or a company is organized so it becomes more like a democracy. Here, I think what McKee is saying when she says “democratization” is that more people can do it by themselves. There’s more of an equal voice because people don’t have to wait for a large company to say yes, they can just go out and do it on their own.
Let’s listen to McKee one more time.
[recording]
Since 2002, the growth of independently published books is over 8,000 percent. So there’s really a movement in the industry and because anyone who wants to tell their story can be out there. And I think that trend of democratization of the publishing process will continue.
[end of recording]
Now that we’ve heard a little bit about the world of self-publishing in the United States, let’s answers some of your questions.
Our first question comes from Yuji (Yuji) in Japan. Yuji wants to know meanings of the words “intrinsic,” “native,” “innate,” and “congenital.” Well, all of these are words you would probably see in relation to perhaps biology or psychology. There are what we would call academic terms, for the most part, things you would find in a textbook. Let’s talk about them one by one. Let’s begin with “native” (native). “Native” can mean coming from or belonging to a certain place. For example, “This plant is native to Asia, but it is also grown in other places.” It originally comes from this place. You can talk about yourself as a native, as a noun. I am a native of Minnesota; that’s where I am from, now I live in California. “Native” as an adjective can also mean something that you are born with. “He has a native ability for music,” or, “mathematics” perhaps.
“Intrinsic” (intrinsic) can mean essential or natural or necessary. Usually when we say “intrinsic,” we mean it’s part of the thing itself, it can’t be separated from it. Eating, sleeping, drinking water, these are intrinsic to living a healthy life – to living, period! “Intrinsic” can sometimes also be used to compare or contrast with “extrinsic.” “Extrinsic” would be something that comes from the outside. So in psychology, we talk about intrinsic motivation, things that make you want to do something not because someone else is telling you to or rewarding you to do it, but just because you want to do it.
“Innate” (innate) can mean, and usually means something you are born with. Some people talk about the innate ability of all human beings to acquire or pick up a language. “Innate,” it’s built into you, you were born with it.
“Congenital” (congenital) also means something you were born with, but usually we use this word to talk about some problem, some medical or physical problem you were born with. We might talk about a congenital disorder; that is something that isn’t quite right, something that isn’t quite normal with you physically that you were born with.
All four words, then, can actually describe something that is natural to a situation or a person. Americans today most likely use “native” to talk about where you are from, when I said, “I’m a native of Minnesota.” In academic – in school, these words can have somewhat different meanings depending on the area of academia, the academic area you’re talking about: science, psychology, biology, and so forth.
Sergey (Sergey) from Ukraine wants to know the difference between “recently” and “currently.” “Recently” means not long ago: maybe a few days ago, maybe a few weeks ago, maybe a few minutes ago. Something that happened in the very immediate past, we might say. “Currently” means right now, at this moment. “I am currently reading Hamlet by William Shakespeare.” I’m doing it right now or today. “Recently” would be something you did in the past, but not very far in the past. “Currently” doesn’t mean, however, that it’s happening at this very exact time as I am telling you; it could mean that. I’m currently recording this episode, that’s what I’m doing right now as I’m speaking. “Currently” can be a little more general; you could say, “I’m currently reading a novel by C.S. Lewis,” or “George Orwell.” I’m reading it now; not at this very minute, not as I’m telling you, but in general – today or this week – I’m reading this particular book.
There is a possible confusion with “recently” and “currently,” however. Sometimes we can use “recently” to talk about something that is started in the past but is still going on now. “I recently began,” or, “I recently started to read a book by George Orwell.” When you say that, you mean you are still doing it. This is especially true with a verb like “to begin” or “to start.” “I recently started watching television again late at night.” I’m still doing it now but I started in the very recent past, not too long ago.
Finally Fernando (Fernando), in Brazil, wants to know why American people – the people in the United States – call soccer “soccer” instead of “football.” Where does the word “soccer” come from? Well as you probably – many of you probably know, football in the United States, sometimes called “American football,” is a very different game than soccer in other countries and here in the U.S. American football is a game where people hit each other, and there’s a ball that is thrown back and forth or kicked. It has a lot more violence in it. Soccer is a sport played with a round ball that you, for the most part, kick and try to put into the other team’s goal.
The word “soccer” actually comes from England, where university students apparently began using this term in the late 19th century – in the late 1800s. The word actually comes from the letters (assoc) as in Football Association; (assoc) is an abbreviated way of spelling “association.” Students started calling the sport “soca,” and later it became “soccer.” So it was actually describing what the rest of the world, in their languages, call football. Although it was invented in England British speakers of English did not continue using the word, but it did become the word that was used when the sport arrived here in the United States. So when you say “football” in American English, people think you are talking about professional or high school or college football teams that have a quarterback and running backs and involve hitting the other players. “Soccer” is always what we use to refer to the game where you have great stars such as Pelé and Beckham.
If you’ve seen something recently you don’t understand in English, email us. Our email address is eslpod@eslpod.com. We’ll try to answer it here on the English Café.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2012 by the Center for Educational Development.
Glossary
route – a path; a way to get somewhere; a way of doing things
* Mathematics is interesting because we can take many routes to arrive at a single answer.
agent – a professional who represents writers, artists, actors, and other people, taking care of business matters for them; a literary agent, whose job is to help authors present their written work to publishers
* Momoko’s agent wants her to make her characters’ dialogue more realistic.
to reject – to not accept or approve; to decline; to decide not to publish something
* Khaled wants to ask Cindy out on a date, but he’s afraid of being rejected.
courtesy – something nice and polite that we expect others to do
* If you borrow my sweater, don’t you think you should wash it as a courtesy before your return it to me?
outrageous – very shocking, extreme, and maybe upsetting
* The customer’s demands and behavior was outrageous! I’m surprised the owner didn’t ask him to leave.
to fulfill – to complete or finish something; to achieve a goal or objective
* Many university students need four or five years to fulfill the requirements to earn a degree.
tiresome – wearisome; exhausting; difficult and requiring a lot of work or attention, causing one to feel tired and worn out
* Paying the bills each month is tiresome, but it has to be done.
fraught with – full of problems or worries; something that one worries about
* Their trip was fraught with canceled flights and lost luggage.
distribution – sending or giving copies or units of something to many different people from one or a few central points
* Our organization is trying to improve food distribution to the poor in this area.
editorial support – assistance with editing and proofreading; help to make written text clearer and easier to understand
* The company doesn’t have any full-time editors, but it does use a few freelancers for editorial support.
credibility – believability; a measure of how much something is respected and believed
* When the scandal became public, the presidential candidate lost her credibility.
movement – a trend or fad, or something that is changing in society and involves a lot of people
* Rachel Carson’s book Silent Spring helped start the environmental movement.
trend – a tendency for something to increase or decrease over time
* Researchers were surprised to find a decreasing trend in smoking over the past 10 years.
democratization – a change in the way a government, industry, or company is organized so that it becomes more like a democracy where everyone’s opinions and wants are represented
* When the dictator lost power, the country began its slow process of democratization.
intrinsic – essential; natural; necessary
* What are the intrinsic characteristics that distinguish Group 1 from Group 2?
native – coming from, growing in, or belonging in a certain place; having a quality or characteristic naturally
* Is Thai your native language?
innate – having a quality naturally, usually from the moment of birth
* Sarah seems to have an innate understanding of animals.
congenital – present at birth, usually used for medical conditions
* Their daughter has congenital blindness.
recently – not long ago
* We spoke on the phone recently, but I haven’t seen him in more than three years.
currently – now; at this moment
* I’m currently away from my desk, but please leave a message and I’ll return your call as soon as I can.
soccer – a sport played with eleven players on each team and two net goals on each end of a rectangular field, where players on each team score by putting the ball into the other’s goal using their feet, knees, and heads (but not hands and arms)
* Clark wants his son to play football, but his wife thinks soccer would be safer.
What Insiders Know
Self-Published Bestsellers
Most self-published books never find a large audience. They tend to be written for a “niche” (a small group of people with specific characteristics) audience. However, some “classics” (books that are very well known and respected) with a very large audience were actually self-published.
For example, Richard Nelson Bolles originally self-published his book, What Color Is Your Parachute? in 1970. It is a book that helps “job seekers” (people who are looking for a job) “assess” (identify and understand) their interests, strengths, and weaknesses, and more than 10 million copies have been sold. After his “initial” (beginning; early) self-publishing success, he began to publish it “commercially” (with traditional publishers) in 1972.
The Chicken Soup book series, which we talked about in English Café 318, was also originally self-published, as was The Joy of Cooking. That book is a large collection of recipes and of descriptions of cooking “techniques” (ways of doing things) that was written by a “homemaker” (a woman who does not work outside of the home) named Irma S. Rombauer in 1931. She originally printed 3,000 copies of the book, and five years later, a traditional publishing company “picked up the book” (began printing it). The cookbook is highly “acclaimed” (admired, praised, and respected) and is found in many home kitchens.