= 1618
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 313.
This is English as a Second Language Podcast’s English Café episode 313. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. Don’t forget about our ESL Podcast Store, which has some additional courses in business and daily English we think you will find interesting.
On this Café, we’re going to talk about a very famous event in American history – in early American history, the Salem Witch Trials. We’re also going to talk about an important organization here in the United States, the National Endowment for the Arts. And, as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café with a discussion about the Salem Witch Trials. A “witch” (witch) is a person, always a woman, who is said to have magical, supernatural powers. “Supernatural” is something that cannot be explained by the normal rules and laws, if you will, of science. The ability to know what someone else is thinking would be a supernatural power, or the ability to be at two places in one time would be supernatural; it’s above the natural. Witches are supposed to have supernatural powers, and usually witches are considered evil in most Western cultures. We think of a witch as being an ugly old woman with a large nose, maybe some green skin, a black dress – you get the idea.
Well, in the late 1600s, people were more likely to believe in these supernatural powers of witches, and we could say they believed in witches. This became especially notable, or noticeable and important in February of 1692 and May of 1693, which is when the Salem Witch Trials took place. A “trial” (trial) is the process where you have a judge and a group of people called a “jury” who decide whether someone has done something wrong, whether someone has broken the law, we would say. These particular trials were trying to determine whether certain women in the town of Salem were, in fact, witches. The trials happened in Salem Town and a few other cities in what would later become the state of Massachusetts in the northeastern part of the United States.
It all started in 1962, when the nine-year-old daughter of a church leader and her 11-year-old cousin began to have fits. A “fit” (fit) describes what happens when you lose control of your body and your actions for a short period of time; it might because by an illness such as epilepsy. Today, we also talk about a fit of laugher, describing a short period of time when you are laughing so hard, so much you can’t stop. Well, in the late 1600s, these girls started to have different kinds of fits. They screamed, they made strange noises, threw things, and did other things that people thought were strange and unexpected.
The doctors couldn’t find any physical or medical explanation for the girls’ behavior, although one has to remember this is 1692 so medicine is not as advanced as it is today. Soon after, other girls in Salem and nearby towns began to have similar fits, and people began to look for supernatural explanations. Church leaders began to say that there were witches who were afflicting the girls. “To afflict” (afflict) means to have a negative effect on someone, to hurt someone, to make someone suffer. We say that someone is afflicted with a disease. Well, in 1692, people were saying that witches were afflicting these girls, using their supernatural powers to make them suffer.
Three women were accused of being witches: Sarah Good was a woman who was poor, we would probably call her “homeless” today; Sarah Osborne was a woman who didn’t go to church or church meetings; and Tituba, who was a slave girl. She told girls wild stories and taught them about fortune telling, or how things would happen in the future – how to predict what would happen in the future. So, all three of these women could be considered outcasts. An “outcast” (outcast – one word) is someone that doesn’t really belong to a certain society. It was easier to accuse these women of being witches since they weren’t really part of the community or were not a strong part of the community.
But soon after, the accusations spread to other people, even people who were active members of the church and the community. In one Salem Town court, more than 150 people were accused of being witches and were actually put in jail – in prison. There were 26 who had a trial, and they were all convicted, or found guilty. As a result of these convictions in the two main courts, 19 people were killed by “hanging,” which means that they tie a rope around your neck, and then they make you stand perhaps on a chair or something, and they kick the chair from underneath you, and you, of course, die. Five of the 26 died in prison. There was a man who was also accused of having these supernatural powers; we might call him a “warlock” or perhaps a “sorcerer.” He was killed when the court put heavy rocks on him, trying to get him to say that he was a warlock, or a male witch, if you will.
The Salem Witch Trials are often referred to as an example of “mass hysteria.” Something that is “mass” (mass) here means widespread, that many people are involved. “Hysteria” is a period of time when people sort of go crazy; they don’t quite understand something and they all begin to react in a very negative way. The Salem Witch Trials were an example of mass hysteria, as people began to look for explanations of things that were happening, and found the easiest explanation was that there were witches in the community. People began to blame these witches not only for the young girls’ fits, but also for illnesses, poor harvests – that is, when the plants would not grow for food, and other things. Of course, anyone could be accused of being a witch, and it’s very hard to defend yourself against these accusations, when people say that you’ve done something wrong, especially if they believe the powers you have are supernatural. Today, the Salem Witch Trials are used as an example of times when people are looking for explanations and perhaps begin to accuse many people of doing things wrong, without a lot of evidence. This happens when people need an explanation of something bad that is happening in the world.
In 1953, one of the more famous American playwrights – someone who writes plays, Arthur Miller, wrote a play called The Crucible about the Salem Witch Trials. We actually talked about that back in the Learning Guide for English Café 299. It’s interesting, because it makes people think about how mass hysteria, such as what was seen at the Salem Witch Trials, could also be an explanation for the popularity of McCarthyism. McCarthyism was a period in the early 1950s when many people were accused of being Communists, something we talked about also in English Café 299.
There’s a related expression, “a witch-hunt.” A witch-hunt would be, literally, going out and looking for – trying to find witches. Today, the expression is used when people go and try to find someone guilty – try to blame someone, even though there isn’t a lot of evidence for the crime that they are being accused of. We might talk about a political witch-hunt. It’s often used to describe what is really a purge (purge). A “purge” is when you try to get rid of something; in this case, get rid of people from an organization or usually the government.
But in any case, the Salem Witch Trials are certainly a negative part of American history, but one from which we can probably learn some lessons.
Now let’s turn to our next topic, which is the National Endowment for the Arts, or the NEA. An “endowment” (endowment) is a large amount of money that is usually given to, say, a school, or perhaps another charitable organization. The endowment is sort of like a big savings account at a bank. It’s a large amount of money that is used to help people or help an organization do the things it wants to do. Typically, the endowment itself is not spent, but rather the interest on the endowment. So you invest the money in things that will give you money back, or simply give you interest as in a bank account, and then you spend that money; so the endowment doesn’t get spent itself. Theoretically, that’s what happens, although in some cases endowments actually spend part of what we might call their “capital,” their main savings.
The National Endowment for the Arts is a U.S. government agency or organization. It was created in 1965 to help support artists and their work, to bring art to the American people, and to provide leadership in arts education.
In order to do those things, the NEA makes grants to artists and art organizations. A “grant” (grant) is the amount of money that is given to someone for a particular purpose. The money in a grant does not have to be paid back, or given back. If you have to pay it back, we would call that a “loan.” But grants are like gifts; you don’t have to return them.
The National Endowment for the Arts has given away more than 4 billion dollars since it began in the mid 1960s. There are three types of grants: one is a grant for art projects; a second is called National Initiatives, these are programs that the NEA sponsors itself, I believe; and Partnership Agreements. The grant money is given to those involved in dance, design, literature, music, theater, opera, museums, and so forth.
Of course, art can be very “subjective,” meaning that different people have different ideas about what is art. It’s not really possible to say that one piece of art is good and another is bad; at least some people believe that’s true because art is subjective. There have been debates about that, of course. When the U.S. government provides financial support for artists and their work, sometimes that can be controversial, meaning people often have strong opinions for or against the money – the government money that is being given for different artistic projects. Sometimes these grant decisions have political consequences, meaning that politicians get involved.
In 1990, there were four artists, who later became known as the NEA Four, who were awarded grants by the NEA. However, the leader of the NEA – the chairman said no to the grants; he denied them because he thought their work was too controversial – the work of the artists, that is. The artists took their case to the Supreme Court; they went to the legal system and eventually got their grant money.
Some presidents have tried to get rid of the NEA altogether. In 1981, then-President Ronald Regan tried to “abolish” or end the existence of the NEA, but that failed. In 1989, several organizations attacked or criticized the NEA because they thought they were giving money to anti-Christian artists. And between 1995 and 1997, many politicians spoke out against the NEA for providing funding or money to controversial artists or for spending government dollars in wasteful ways.
The NEA is often criticized, but it does play an important role in the funding of American artists and art education in the U.S. However, it’s important to understand that it is not like it is in many, for example, European countries, where the government provides a lot more support to artists – at least in some of those countries. Here in the United States, only about 13 percent of the financial support for the arts comes from the government, and only 9 percent comes from the national or federal government; the NEA, they contribute about 1 percent. In general, many other governments provide a lot more financial support than the U.S. government does. Some people think that is wrong, that the government should give more money to artists; other people think that the artists should get money from other places, and not from the taxpayer – not from the person paying taxes.
There’s no real answer to that one, so let’s instead try to answer some of your questions.
Our first question comes from Katsuya (Katsuya) in Japan. Katsuya wants to know the difference between the phrases “in fact” and “as a matter of fact.”
Well, let’s start with the word that is in common – that is the same in the two expressions, which is “fact.” A “fact” is something that is true, something that exists. “Matter” is the subject of your thoughts or your feelings; “matter” can also be something that is physical, that takes up space, that you can feel or see.
You have this idea of truth, you have this idea of existence in the words “fact” and “matter,” so it’s not surprising that the expressions “in fact” and “as a matter of fact” both mean in truth or actually. “You don’t have a match to light my cigarette, do you?” and the person may respond, “As a matter of fact, I do,” or, “In fact, I do.”
We use these two expressions in response to a question or when someone expresses a doubt. They’re used in formal and informal situations. It’s often the case that we use these to say the opposite of what the person is telling us or what the person thinks. You might say, “You don’t speak Italian, do you?” And, if you do speak Italian, you would say, “As a matter fact, I do. I do speak Italian.” Or, “In fact, I do speak Italian.” Parlo Italiano. You see, a little Italian!
Sometimes the expressions can be used as a way of emphasizing or extending an idea. “I’m going to go to Hawaii. In fact, I’m going to go next week.” The idea that I’m going next week is related to the idea that I’m going; it provides some additional information. So that’s also a use of “in fact” or “as a matter of fact.”
Xiomara (Xiomara) from the Dominican Republic wants to know the difference between “even” (even) and “even though.”
“Even” is a word that we use often for emphasis, to make the meaning of other words stronger. It can be used in formal or informal situations. “The smell of the food made me feel even sicker,” more sick than I was going to be otherwise. So, there it means in a stronger way. “Even” can also be used to mean at the same time when it is combined with the word “as.” “Even as we stood watching, the fire destroyed the building.”
“Even though” is used more often as a conjunction, like “although” or simply “though.” “Even though her mother was sick, she still made Thanksgiving dinner for us.” Or, “I’m going to go to the store, even though it is raining,” despite the fact that it is raining.
So, “even” is used for emphasis: “He is even going to wash my car, that’s how nice he is.” “Even though” is used as a conjunction meaning “although.” “Even though it rained today, he is still going to wash my car.”
Finally Vagner (Vagner) – not spelled the same as the composer, which is (Wagner), this is a completely different Vagner. Vagner, from an unknown country, wants to know the meaning of the phrase “look at.” For example, a professor in front of his or her class might say, “Let’s look at the history of California.” “Look at” there means let’s consider, let’s talk about, let’s discuss. Or you could say, “Economics looks at the role of markets and human behavior.” Economics studies is about, considers these issues or topics.
“Look at” could also be used to mean turn your eyes and look at something in a certain direction. “Look at that guy walking down the street. He has a funny hat on. He looks like a Viking.” Or you could say, “Look at that beautiful woman.” No, you shouldn’t say that if you’re married, of course!
“Look at” can also mean to read something, but read it very quickly. You sit down and you are at a restaurant, you may say, “Let me take a look at the menu.” There, it really means let me look, let me see the menu, let me read the menu. We can even say, “Let me take a quick look at the menu,” meaning I am not going to look at it very carefully.
So there are these three meanings: to consider, to study, to examine. “Look at” can also mean to look in a certain direction or to look at something or someone specifically. And finally, it can mean to read, often very quickly and not very carefully.
If you have a question or comment, in fact, if you have anything you would like to tell us, you can email us. Our email address is eslpod@eslpod.com. We can’t answer all the questions, but we will definitely take a look at them.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Edu
Glossary
witch – a women who has magical powers
* For Halloween, Janice dressed her daughter up as a witch.
supernatural – something that cannot be explained by science and the laws of nature
* The house makes strange noises at night because it’s old, not because of something supernatural living in it.
trial – the process in which a judge or a jury decide whether someone has done something against the law and should be punished
* During the trial, it became clear that she was guilty of the crime.
fit – when one loses control of one’s body, actions, or emotions for a short period of time
* I wish you wouldn’t have a fit each time I’m a little late getting home from being with my friends.
to afflict – to have a negative effect on someone; to make someone suffer
* Our son has been afflicted with breathing problems since he was born.
outcast – a person who doesn’t belong in a particular group or community; a person who does not or is not allowed to participate in society
* In high school, some students feel like outcasts because they don’t have many friends or an active social life.
to hang – for a rope to be tied around one’s neck and the support under one’s feet to be taken away so that one dies
* In the movie we saw last week, the bank robbers were caught and hanged by the townspeople.
mass hysteria – a period of time when many people share a belief or behavior that cannot be explained and that causes fear or panic
* The TV news falsely reported that the drinking water in our city is unsafe and caused mass hysteria for weeks.
endowment – a large amount of money that is given to a university or another large nonprofit organization
* A major tobacco company offered our foundation a large endowment, but our board of directors decided against accepting it.
grant – an amount of money that is given to someone for a particular purpose, such as research or an artistic project, and the money does not have to be paid back
* Our laboratory received a government grant to continue our cancer research.
subjective – based on a person’s feelings, tastes, or opinions, not facts
* Which color is the best for painting a house? The answer is subjective.
to abolish – to formally end the existence or practice of something
* Did you hear that a new law abolishes the use of plastic bags by stores and other businesses?
in fact – in truth; actually
* Everyone thought that Dan’s new girlfriend was a teenager, but in fact, she’s 26 years old.
as a matter of fact – in truth; actually
* I know that you don’t think I can fix my own car, but as a matter of fact, my father was a mechanic and he taught me everything he knew.
even – indeed; to a larger extent, in a stronger way; at the same time
* Oscar is a great runner and won the race even after hurting his foot the night before the race.
even though – although; though
* Even though Brenda treats her husband unkindly, he still loves her.
to look at – to consider; to study; to look in a certain direction; to look toward something specific; to read, often quickly and not very carefully
* Nobody seems to have a solution to our problem, so let’s all sit down and look at it again next week.
What Insiders Know
The Blair Witch Project
The Blair Witch Project was a “horror” (scary; frightening) film released in 1999. It was a “small budget” (not expensive to make) film that was created using “amateur” (not professional) “footage” (sections of film). The film is considered the first “widely released” (shown in many theaters) film that was mainly promoted on the Internet. The film was made for about $500,000, but “grossed” (earned, before expenses are deducted) nearly $250 million worldwide.
The Blair Witch Project is a film about three student “filmmakers” (people who create films or movies) who travel into the Black Hills in Maryland, in the northeastern part of the U.S. They “hike” (walk or climb a hill or mountain) into the Black Hills to film about a local “legend” (story passed from person to person that many people know) about the Blair Witch. They interview the local people who tell a story of a “hermit” (person who lives and hides away from other people) who killed many children in the area. The hermit explained that the Blair Witch had been bothering him a lot, but had promised to leave him alone if he killed the children. The filmmakers’ footage show them traveling through the “woods” (area with many trees), but “eventually” (in the end), they “disappear” and are never seen again. Their video equipment and the footage are found about one year later.
Many of the “critics” (people who write about movies, plays, and other things and give their opinion about them) “praised” (said positive things about) the film as “innovative” (doing something new) and effective filmmaking. At the time of its release, many people considered it one of the most frightening horror movies ever made. The film received a Global Film Critics Award for Best “Screenplay” (movie script), and a popular entertainment magazine, Entertainment Weekly, “named” (called) it one of the best films from 1983 to 2008.