= 0451
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 451: Buying Car Insurance.
This is English as a Second Language Podcast episode 451. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode that contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension checks, and a complete transcript of this episode.
This episode is called “Buying Car Insurance.” It’s a dialogue between Jackie and an “agent,” someone who sells insurance for cars. In it, we’ll use a lot of common vocabulary in talking about cars and car insurance. Let’s get started.
[start of dialogue]
Agent: Hello, Krashit Insurance.
Jackie: Hi, I wanted to get a quote for car insurance.
Agent: Sure, I can help you with that. I assume you want liability insurance, but what other coverage would you like to get?
Jackie: Umm…I’m not sure. This is my first car.
Agent: In that case, let me make a few suggestions. You’ll definitely want collision insurance. It pays to fix your car if you hit another car or run into something.
Jackie: Okay, sure, I want that.
Agent: You’ll also want comprehensive insurance. It pays for damage to your car.
Jackie: How’s it different from collision insurance?
Agent: Well, it pays for damage to your car that’s not a result of an accident, like in the case of theft, weather damage, or vandalism.
Jackie: Okay, I want that, too.
Agent: You’ll want property damage insurance to pay for damage you cause to someone else’s property. On top of that, you’ll want uninsured motorist insurance in case the other driver doesn’t have insurance or doesn’t have enough insurance to pay for the damage to your car.
Jackie: Umm…I guess I’ll take that, too.
Agent: And I don’t think you can do without medical payments insurance. It pays for your medical bills and those of your passengers in case of an accident. Should I get you a quote for all of this coverage?
Jackie: Why don’t you hold off on that? I’m not sure how I’m going to pay for all that and buy gas, too!
[end of dialogue]
This is a telephone conversation between a car insurance agent, a person who sells car insurance, and Jackie. The agent answers the phone: “Hello, Krashit Insurance.” Jackie says, “Hi, I wanted to get a quote for car insurance.” A “quote” is an estimate, an approximate cost of something, how much something will cost me. So if you take your car to a mechanic to get it fixed, you may ask for an estimate – a quote on how much the repairs will be. Or if you are having someone come to your house and paint the walls, you would first ask for a quote – how much money will it be. It’s an estimate of the cost of something. “Quote” has a couple of different meanings in English, however, so take a look at Learning Guide for a complete explanation.
Jackie says she wants a quote for car insurance. “Insurance” is basically an arrangement where you give money to a company, and if you have an accident or a problem the company will pay for the repair of that accident or that problem, depending on what it is.
So, the agent says, “Sure, I can help you with that” – I can give you a quote. He says, “I assume you want liability insurance.” “I assume” means I believe that something is true; I am going to believe that it is true unless you tell it isn’t. In the United States, there are a couple of different kinds of car insurance, and usually you are required to have certain kinds of insurance, it depends on the state where you live. Liability insurance is one kind of insurance. “Liability” comes from word “liable,” which means to be responsible for something. There are two basic kinds of liability insurance. One kind is to “cover” you, to pay for any problems you cause to somebody’s health or to a person’s body. This is sometimes called “bodily liability.” If, for example, broke someone’s legs or even killed them, liability insurance would pay them some money, or if they’re dead, of course, their relatives. That’s one kind of liability insurance, “bodily injury” it’s sometimes called. The other kind is if you damage someone else’s car or someone else’s property, that’s called “property damage” insurance; it’s a different kind of liability insurance.
The agent says, “what other coverage would you like to get?” “Coverage” are the things that the insurance policy will pay for, will protect you against. So here in California, for example, in Southern California we have a lot of earthquakes, where the ground moves suddenly. You can buy special earthquake insurance for your house; you can also buy fire insurance for your house. Each kind of insurance is different. The same is true for a car; there are different kinds of insurance, the things that the insurance protects is called the coverage.
Well, Jackie says she’s not sure, this is her first car. The agent says, “In that case (in that situation), let me make a few suggestions. He says, “You definitely want collision insurance.” “Collision” means two things hit each other, two cars, for example, run into each other; that would be a collision. “Collision insurance” is money that the insurance company will give you if your car is damaged. That is, it doesn’t pay for the other person’s car; it pays for your car. Most states do not require that you have collision insurance, but it’s often a good idea. The agent explains that collision insurance pays to fix your car if you hit another car or run into something. To “run into” means to hit something else, especially when you are driving. Generally, that is not a good idea!
Jackie says, “Okay, sure, I want that.” Then the agent says, “You’ll also want comprehensive insurance. It pays for damage to your car.” “Damage” is physical harm that comes to something. If you take water and you pour it onto your laptop, as I did once, that will damage your computer; it will cause damage. The word can be both a noun and a verb.
Jackie says, “How is (comprehensive insurance) different from collision insurance?” The agent explains that comprehensive insurance pays for damage to your car that is not the result of an accident – it is not because of an accident. An “accident” is, in this case, the same as a collision or a crash, when your car hits something else. Comprehensive insurance pays for things in addition to accidents, for example in the case of theft. “In the case of (something)” means if something happens in a particular situation. “Theft” is when someone steals something from you – steals your car, in this case. Comprehensive insurance will pay for your car if someone steals it. Comprehensive insurance will also pay for “weather damage,” if you have bad weather and that damages your car. It will also pay if you are a victim of vandalism. A “victim” is someone who is hurt by someone else or something. “Vandalism” means someone tries to damage your property by throwing something on it or by doing something that would cause it to be harmed in some way. They may, for example, paint on it or take a rock and throw it at it, that would be an example of vandalism. If you don’t have comprehensive insurance and your car is vandalized or stolen, you won’t get any money for it. I discovered this when I had a car many years ago here in Los Angeles, and it was stolen. I later discovered that I did not have comprehensive insurance, and so I didn’t get any money from the insurance company.
Jackie says, “Okay, I want that, too.” The agent says, “You’ll want property damage insurance to pay for damage you cause to someone else’s property.” We already talked about liability insurance, which pays for damage you do to someone else or something else. This is a type of liability insurance: property damage insurance. The agent says, “On top of that (meaning in addition to that), you’ll want uninsured motorist insurance in case the other driver doesn’t have insurance or doesn’t have enough insurance to pay for the damage to your car” – if they hit you, and they are the ones who are responsible. So, “uninsured” means not insured. Even though the law in most states requires that all drivers have insurance, sometimes people don’t do that – they don’t buy the insurance. And, of course, if the other person hits you and it’s their fault, their insurance should pay for the damages done to your car. But if they don’t have any insurance, then you can use your own uninsured motorist insurance. A “motorist” is just another name for a person who drives a car.
Jackie says, “Umm…I guess I’ll take that, too.” Of course, the insurance agent is trying to sell her as much insurance as possible. The agent says, “And I don’t think you can do without medical payments insurance.” The expression “can’t do without” means that you must have something. “Medical payments insurance” is money that is paid for your medical expenses and for the other people who may have been in your car if there is an accident and they are injured, if they break their leg or their arm for example.
The agent says, “It pays for your medical bills and those of your passengers (the other people in the car) in case of an accident. Should I get you a quote for all of this coverage?” Jackie says, “Why don’t you hold off on that?” To “hold off on (something)” is a phrasal verb meaning to wait to do something, to delay something. So, Jackie’s saying no, I don’t want a quote right now, let’s do that later. “I’m not sure how I’m going to pay for all that and buy gas, too!” She doesn’t know if she’ll have the money to pay for all of these different kinds of insurance.
As I said previously, in most states there’s a minimum amount of insurance that you must have, but it doesn’t necessarily mean all of these kinds of insurance.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Agent: Hello, Krashit Insurance.
Jackie: Hi, I wanted to get a quote for car insurance.
Agent: Sure, I can help you with that. I assume you want liability insurance, but what other coverage would you like to get?
Jackie: Umm…I’m not sure. This is my first car.
Agent: In that case, let me make a few suggestions. You’ll definitely want collision insurance. It pays to fix your car if you hit another car or run into something.
Jackie: Okay, sure, I want that.
Agent: You’ll also want comprehensive insurance. It pays for damage to your car.
Jackie: How’s it different from collision insurance?
Agent: Well, it pays for damage to your car that’s not a result of an accident, like in the case of theft, weather damage, or vandalism.
Jackie: Okay, I want that, too.
Agent: You’ll want property damage insurance to pay for damage you cause to someone else’s property. On top of that, you’ll want uninsured motorist insurance in case the other driver doesn’t have insurance or doesn’t have enough insurance to pay for the damage to your car.
Jackie: Umm…I guess I’ll take that, too.
Agent: And I don’t think you can do without medical payments insurance. It pays for your medical bills and those of your passengers in case of an accident. Should I get you a quote for all of this coverage?
Jackie: Why don’t you hold off on that? I’m not sure how I’m going to pay for all that and buy gas, too!
[end of dialogue]
You probably assumed that the script for this episode was written by Dr. Lucy Tse, and if you did you are correct!
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2009, by the Center for Educational Development.
Glossary
quote – quotation; an estimate of how much something will cost; a prediction of the cost of something
* They’re trying to get quotes to install an electric water heater in their home.
to assume – to believe that something is true without really knowing if it is
* Let’s assume that you’ll make $20,000 in sales each month. That will give you sales of $240,000 per year.
personal liability insurance – money that is paid if your car damages property or hurts or kills someone in an accident
* Ted is a millionaire, so he needs a lot of personal liability insurance so that if he hurts someone in a car accident, they won’t be able to take away all his money.
coverage – the things that an insurance policy protects one against, and for how much
* Does your homeowner’s insurance include coverage for floods?
collision insurance – money that is paid if your car is damaged when it hits another car or object
* When Mohammed drove through a red light and hit another car, his car was damaged, but fortunately, his collision insurance paid for all of the repairs.
to run into (something) – to hit something, especially while driving
* Luigi fell asleep while driving and ran into a tree.
comprehensive insurance – money that is paid if your car is damaged by the weather, if something falls on your car, if someone steals your car, or if someone damages your car while you are not driving
* When a tree fell on Carl’s car, he had to pay to get it fixed because he didn’t have comprehensive insurance.
damage – physical harm to something; physical problems with something
* The insects caused significant damage to the house.
accident – a collision; a crash; when a moving car hits another car or an object
* What percentage of car accidents involves drunk drivers?
in the case of (something) – if something happens; in a particular situation
* It’s a good idea to save money in the bank so that in the case of unemployment, we’ll have enough money to live on while we look for another job.
theft – when something is stolen
* Did you tell the police about the theft of your car radio?
vandalism – when someone physically harms an object or building, often by hitting it very hard or by writing or painting something on it
* The school has a problem with vandalism because students are always writing things on their classroom walls and desks.
property damage insurance – money that is paid if your car damages another person’s car or property
* When I accidentally ran over my neighbor’s bicycle, I had to call the insurance company and ask them if my property damage insurance could be used to buy a new bicycle for him.
uninsured motorist insurance – money that is paid if you are hurt or your car is damaged by a driver who didn’t have insurance
* Xavier’s car was hit by someone who didn’t have any car insurance, but fortunately, his uninsured motorist insurance paid to fix everything.
medical payments insurance – money that is paid for your medical expenses and the medical expenses of other people who were in your car if the medical problems were caused by an accident that happened while you were driving
* Amelia broke her arm in the car accident, but her medical payments insurance paid all the medical bills.
passenger – a person who travels in a car while another person is driving; a person who travels in a bus, train, boat, or plane
* Olivia drives a big car with room for six passengers.
to hold off on (something) – to wait to do or have something; to delay
* They decided to hold off on their vacation to Manhattan until the spring when the weather will be nicer.
Comprehension Questions
1. Which kind of insurance would pay for the damages if an earthquake damaged your car?
a) Personal liability insurance.
b) Collision insurance.
c) Comprehensive insurance.
2. Which kind of insurance would pay some of your passenger’s expenses?
a) Property damage insurance.
b) Uninsured motorist insurance.
c) Medical payments insurance.
Answers at bottom.
What Else Does It Mean?
quote
The word “quote,” in this podcast, means an estimate or prediction of how much something will cost: “The mechanic gave her a quote of $400 to fix her car, but after he did the work, he said it actually cost $950.” The word “quote” is also short for “quotation,” which is used to refer to words that were said or written by someone else: “The most famous quote by President Kennedy was, ‘Ask not what your country can do for you; ask what you can do for your country.’” As a verb, “to quote (something or someone)” means to say or write something exactly the way someone else has said or written it: “My uncle often quotes Thomas Jefferson, saying, ‘He who knows best knows how little he knows.’”
coverage
In this podcast, the word “coverage” means the things that an insurance policy protects one against, and for how much: “Rental insurance provides coverage if the things you owned are damaged in an apartment you’re renting.” The word “coverage” also means something that is discussed in newspapers or on the television or radio: “This newspaper has excellent coverage of local events, but not very much about international events.” Or, “What can our organization do to get more coverage in the local newspapers about our community programs for children?” Finally, the word “coverage” refers to how well an electronic device works in a particular area: “Cell phone coverage in the mountains isn’t as good as it is in the center of the city.”
Culture Note
Unfortunately, there are many car insurance “scams” (or dishonest ways to get money) in the United States. Some people “make their living” (earn money, usually through a job) with car insurance scams. They try to get the car insurance companies to pay them money for accidents that never happened, or for accidents that they got into “on purpose” (intentionally; wanting something to happen).
The most dangerous car insurance scams happen when dishonest people try to get into accidents on purpose so that they can get money from the car insurance companies. For example, if you are “merging” (entering a road with many cars, as when one drives onto a freeway), another driver might “wave” (move one’s hand in the air) to offer you the “right of way” (permission to drive in front of another car). Then, as you try to merge in front of that car, the other drive might “speed up” (start to go faster) so that the two cars hit.
When the police come, the other driver “denies” (says that something didn’t happen) that he or she ever waved to you. If the car insurance company decides that you are “at fault” (the accident happened because you made a mistake), then the other driver will get money to pay for the damage to his or her car. If the other driver has a dishonest doctor as a friend, he or she might also get the car insurance companies to pay for “fake” (not real) “injuries” (damage to a person’s body) if the doctor’s office lies and says that those injuries were related to the accident.
Car insurance scams are very expensive, so car insurance companies spend a lot of time and money trying to identify and “prevent” (not let something happen) scams.
Comprehension Answers
1 - c
2 - c