= 0453
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 453: Making an Emergency Medical Call.
This is English as a Second Language Podcast number 453. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in (guess where?) beautiful Los Angeles, California.
In case you don’t know, we have a website; it’s at eslpod.com. If you go there, you can download this episode’s Learning Guide, which will help you improve your English. It will also make you stronger and more beautiful!
This episode is called “Making an Emergency Medical Call.” It’s a telephone conversation between an “emergency operator” (somebody who answers the phone calls for the government’s police and fire emergency system) and someone who has an emergency. Let’s get started.
[start of dialogue]
Operator: Emergency operator. State your emergency.
Dirk: We need an ambulance right away.
Operator: What is your name?
Dirk: Dirk, Dirk Omora.
Operator: Can you tell me what happened?
Dirk: There was a car accident.
Operator: Where are you?
Dirk: I’m not sure. I was driving in my car when I saw the pileup. I’m somewhere on Blossom Road. Can you trace my location?
Operator: Yes, we’ll try to do that. Can you see if anyone is hurt?
Dirk: One of the drivers is lying on the ground unconscious, and the other one is bleeding. There’s someone trapped in the back of her car, too. We need to rescue her before the car explodes! I’m going to see if I can help.
Operator: Sir, I need you to stay on the line. I’m sending an ambulance right now, and they’ll have the Jaws of Life and other equipment to do the job. The paramedics will be there very soon.
Dirk: Okay, but hurry!
[end of dialogue]
In the United States when you have an emergency, you dial three numbers on your telephone: 9-1-1. So, this is a case where someone calls 9-1-1 and the operator answers saying, “Emergency operator.” An “emergency” is an unexpected situation that is dangerous or very serious; it’s something that you have to react to right away. The operator says to Dirk, the person calling, “State your emergency.” To “state” here means to say something, to give the information. If you go, for example, to a court in the United States, the judge may ask you: “State your name,” meaning tell me what your name is. “State” has several meanings in English; take a look at our Learning Guide for a complete explanation.
Dirk says, “We need an ambulance right away.” An “ambulance” is a special car (a van) that is driven usually very quickly, with loud noises and bright lights, to help people who have urgent or emergency medical conditions. The ambulance goes and picks the person up and takes them to the nearest hospital. The ambulance is allowed to go faster than anyone else, and if you hear or see an ambulance that has its lights on and is making noises with what we would call the “sirens” of the ambulance, you are required in the U.S. to stop your car, to move it to the side of the road so the ambulance can go through.
Well, Dirk says they need an ambulance right away. The operator says, “What is your name?” Dirk says, “Dirk, Dirk Omora.” The operator then says, “Can you tell me what happened?” The operator is asking for more specific information. Dirk says, “There was a car accident.” A “car accident” is a collision (or a crash) between two or more cars, when one car hits another car or when one car hits an object, like a tree for example.
The operator says, “Where are you?” Dirk says, “I’m not sure. I was driving in my car when I saw the pileup.” A “pileup” is a large, serious car accident that involves many different cars. For example, if it is very icy on the freeway, or if there is a lot of fog and it is difficult for drivers to see, one car could hit the car in front of it, then the car behind it hits that car, then another car, then another car. Sometimes these pileups can be 20, 30, 50, or more cars. Usually this is caused in part because people are driving too close to each other, but sometimes it’s simply because of bad weather.
Dirk says that he was driving in his car when he saw this pileup. He says he’s somewhere on Blossom Road. He then asks the operator, “Can you trace my location?” To “trace” (trace) means to figure out where something is or where something is coming from. In the U.S., if you are calling from a phone that is in your house or at a building and you call 9-1-1, usually they know exactly where you are – they can tell where you are. If you have a cell phone it is, of course, much more difficult, although now in many places they can also figure out approximately where you are, even when you have a cell phone.
The operator says, “Yes, we’ll try to do that” (we can trace your location). She says, “Can you see if anyone is hurt?” To be “hurt” means to be injured. You break your leg, you break your arm, maybe you hit your head; those would be “injuries.” Dirk says, “One of the drivers is lying on the ground unconscious, and the other one is bleeding.” To be “unconscious” means that you’re not aware of what is around you. Usually your eyes are closed, you can’t hear anyone; it’s basically like being asleep, but it’s often caused because you hit your head hard against something.
Well, one person is unconscious on the road (on the ground), and one is bleeding. To “bleed” (bleed) means to lose blood, when blood is coming out of your body – that red liquid that comes out of your body if you cut yourself, for example. Dirk says, “There’s someone trapped in the back of her car, too.” To be “trapped” means to be somewhere where you can’t move, you can’t get out, you can’t leave a place usually because something is in your way – a person or a thing. “Trap” can also be a noun. If somebody says, “this is a trap,” they mean someone is trying to get us in trouble or cause us problems on purpose in order to do something bad to us afterwards. Here, it means to be unable to move, not to be able to leave a place.
So, there’s someone trapped in the back of the car. Dirk says, “We need to rescue her before the car explodes!” Sounds like a television program! “We need to rescue her.” To “rescue” someone means to save someone, to help someone get out of a difficult or dangerous situation. The person is trapped in the back of the car, and because there is gasoline in the car, when there’s an accident there’s a danger that the car might catch on fire – might explode. To “explode” means to make a large noise and to break into smaller pieces usually with fire, and in this case, that’s what would be the situation: the car could catch on fire.
Dirk says, “I’m going to see if I can help.” The operator then says, “Sir, I need you to stay on the line.” To “stay on the line” means not to hang up the phone, not to stop or disconnect your phone connection, to continue to talk to someone and not leave to do something else. So, the operator is saying I need you to stay on your phone – to stay on the line. “I’m sending an ambulance right now, and they’ll have the Jaws of Life and other equipment to do the job.” The “Jaws of Life” is a large machine that can cut a hole in something to help people get out of a car, for example, after a serious accident. So, it’s a special machine. The operator is sending this machine and other equipment to do the job. “To do the job” means to do something well, to do something correctly. The operator says, “The paramedics will be there very soon.” A “paramedic” is a person who is not a nurse or a doctor, but who is trained to help people in medical emergencies, someone who picks them up in the ambulance and then takes them back to the hospital. One of my brother-in-laws is a paramedic (works in an ambulance).
Finally Dirk says, “Okay, but hurry!” To “hurry” means to do something quickly, to rush, to get it done right away.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Operator: Emergency operator. State your emergency.
Dirk: We need an ambulance right away.
Operator: What is your name?
Dirk: Dirk, Dirk Omora.
Operator: Can you tell me what happened?
Dirk: There was a car accident.
Operator: Where are you?
Dirk: I’m not sure. I was driving in my car when I saw the pileup. I’m somewhere on Blossom Road. Can you trace my location?
Operator: Yes, we’ll try to do that. Can you see if anyone is hurt?
Dirk: One of the drivers is lying on the ground unconscious, and the other one is bleeding. There’s someone trapped in the back of her car, too. We need to rescue her before the car explodes! I’m going to see if I can help.
Operator: Sir, I need you to stay on the line. I’m sending an ambulance right now, and they’ll have the Jaws of Life and other equipment to do the job. The paramedics will be there very soon.
Dirk: Okay, but hurry!
[end of dialogue]
I will now state the name of the person who wrote this episode: Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2009, by the Center for Educational Development.
Glossary
emergency – an unexpected situation that is dangerous or very serious and makes one act immediately
* Is anyone here a doctor? It’s an emergency! My wife is giving birth!
to state – to say something; to give information
* Please leave a message, stating your name, telephone number, and your reason for calling, and we’ll return your call as soon as we can.
ambulance – a special van that is driven very quickly, with loud noise and bright lights, to help people with urgent medical problems, taking them to the hospital
* When Heather broke her leg while she was home alone, she wasn’t able to drive herself to the hospital, so she called an ambulance.
car accident – a collision between two or more cars; when a car hits another car or another object, usually hurting or killing people
* Car accidents are more likely when the roads are covered in ice and snow.
pileup – a big, serious car accident where many cars hit each other
* When the truck rolled over on the freeway, it caused a pileup because all the cars behind it ran into each other.
to trace – to find something; to figure out where something is
* They traced the bad smell in the house to their son’s dirty socks.
hurt – injured; in pain because something is wrong with one’s body
* Claudia got hurt when she fell off her bicycle.
unconscious – not aware of what is happening around oneself and appearing to be asleep, usually because one was hit very hard on the head
* Hideya was unconscious for a few minutes after he hit his head.
to bleed – to lose blood; to have a red liquid come of out one’s body because one has an injury or is hurt in some other way
* Nicky accidentally cut her finger with the scissors and it bled on the carpet.
trapped – unable to move or leave a place, usually because one or more objects are in one’s way
* We were trapped in the elevator for four hours, waiting for someone to fix it.
to rescue – to save someone; to help someone get out of a difficult or dangerous situation
* The firefighters rescued two little girls from a burning building.
to explode – to make a loud noise and break into many small pieces, usually with fire
* It’s dangerous to smoke in a gas station because the gas tanks might explode.
to stay on the line – to not hang up the phone; to continue to talk with someone on the phone and not leave to do something else
* Please stay on the line, and our next available representative will be with you as soon as possible.
Jaws of Life – a large, strong machine that cuts a hole in something to help people get out of a car or building after a serious accident
* After the earthquake, the city used its Jaws of Life to help people get out of the library, which had collapsed.
to do the job – to be able to do something well; to work correctly
* You have a lot of furniture to move, so we’ll need at least four strong people to do the job.
paramedics – a person who is not a nurse or doctor, but whose job is to help people with medical problems, especially in an emergency
* The paramedics saved that man’s life, helping him breathe until they could get him to the hospital.
to hurry – to rush; to do something quickly
* Please hurry and finish the project as quickly as you can. The client is waiting!
Comprehension Questions
1. What will the Jaws of Life do?
a) It will bring food to the people who were hurt in the accident.
b) It will help the people want to continue living.
c) It will get the people out of their damaged cars.
2. What will the paramedics do?
a) They’ll help the people who have been hurt.
b) They’ll trace Dirk’s location.
c) They’ll make the car explode.
Answers at bottom.
What Else Does It Mean?
state
The verb “to state,” in this podcast, means to say something or to give information: “Let’s start this meeting with introductions. Please state your name, your age, and your hometown.” The phrase “to be in a good/bad state of repair” means to be in good/bad condition: “The painting is in a bad state of repair, but I think we can fix it.” The phrase “state of affairs” is used to talk about a situation: “They were in a sad state of affairs after their house was destroyed by the hurricane.” Finally, the phrase “to lie in state” describes when a politician or another important person dies and his or her body is put somewhere for a few days so that people can go there and show their respect for what that person did in life: “Where did Ronald Reagan lie in state?”
trace
In this podcast, the verb “to trace” means to find something or to figure out where something is: “The police officers traced the path of the bullet.” The phrase “to trace a call” means to use special technology to determine where someone is calling from: “The police traced the call to a public telephone in downtown Cincinnati.” The verb “to trace” also means to copy a drawing by putting a thin piece of paper on top of it and drawing the same lines: “Did you draw that yourself, or did you trace it from someone else’s work?” Finally, the verb “to trace” can mean to explain how something has changed over time: “This magazine article traces the development of the Internet over the past 10 years.”
Culture Note
In the United States, there are many government “agencies” (offices) and services that try to help people in emergencies or rescue people when they need help. When someone has an emergency, he or she should call the emergency number (usually 9-1-1) and the “dispatcher” (a person who answers the phone and tells other people where to go in response to the request) will decide which emergency “crews” (groups of people who work together) should go to help.
Almost all cities have police departments and fire departments to help people in emergencies. When they are responding to an emergency, the police cars and fire trucks are driven with “sirens” (loud noises) and flashing lights so that they can move through traffic quickly and get to the “scene of the accident” (where an accident happens). Paramedics are usually the first people to arrive, and they “administer” (perform; give) basic medical treatment until the injured person can be taken to the hospital.
There are also specialized services for other types of emergencies and rescues. For example, if someone is trapped on a boat that is no longer working, the Coast Guard might “come to the rescue” (help a person in a difficult or dangerous situation). If someone is “lost” (doesn’t know where one is), maybe because he or she was “hiking” (walking long distances outdoors) when a storm came, search-and-rescue crews will drive and walk throughout the area, looking for that person. Also, if there is a “bomb threat” (when someone says that an explosive device is in a certain place), a bomb disposal crew will come to find and “dismantle” (take something apart) the bomb.
Comprehension Answers
1 - c
2 - a