= 0470
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 470: Avoiding Show and Movie Spoilers.
This is English as a Second Language Podcast number 470. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode. The Learning Guide contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension checks, and a complete transcript of everything we say on this episode.
This episode is a dialogue between Lee and Kira about something called a “spoiler,” which is when you tell someone how a movie or a television show ends – what its conclusion is. Let’s get started.
[start of dialogue]
Lee: I’m reading this article about the new season of our favorite show. It’s premiering next week.
Kira: Don’t tell me anything about it, especially spoilers.
Lee: But don’t you want to know which guest stars will be making appearances and the plot twists that are coming up?
Kira: No, I don’t! I don’t watch movie trailers and I don’t read reviews. It spoils the fun when you already know what’s going to happen. Where’s the suspense?
Lee: The blogs and reviews I read all have “spoiler alerts” and I avoid reading those sections. Let me just tell you one thing I read…
Kira: Stop right there! I’m covering my ears. I want to stay in the dark, completely in the dark. Got it?
Lee: Okay, I won’t let the cat out of the bag, but we’re in for a wild ride this season.
Kira: I’m not listening! I’m not listening!
[end of dialogue]
Lee begins our dialogue by saying, “I’m reading this article about the new season of our favorite show.” A “season” (season) here means a period of time when a series of television programs are being shown. There’s usually, in the United States, a fall and spring television season, when television programs begin. The word “season,” however, has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations.
Lee says that the television show that he and Kira like is premiering next week. “To premiere” means to be shown for the very first time. If the television show premieres tomorrow, that means that it is the first time you have seen that show or that series of shows on television; it’s the first time. You can also have a movie that premieres; we have lots of movies that premiere here in Los Angeles. The noun is, simply, “ premiere.”
Kira says, “Don’t tell me anything about it, especially the spoilers.” A “spoiler” is something that is said or written that lets other people know what happens at the end of a book, a movie, or a television show. Most of us don’t want to know how the show ends or the movie ends, and if you do that it’s called a “spoiler.” “Spoil” has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations.
Lee says, “But don’t you want to know which guest stars will be making appearances and the plot twists that are coming up?” A “guest star” is an actor who appears on just one or two, maybe three shows, but is someone who is not a regular part of the television program. “To make an appearance” means to be present, to come to an event or to be on a show. “He made an appearance on the television show” means he was on the TV show, probably not for a very long time however. A “plot twist” (twist) is something unexpected that happens in the story, especially in a book or a movie. A boy falls in love with a girl, and then halfway through the book the boy sees the girl’s sister and falls in love with her sister. That would be a “plot twist.” That would also probably end his first relationship with the other sister, but that’s too complicated to talk about here! “Plot” is simply the story, so a “plot twist” is a change in the story. When we use the expression “coming up,” we mean it will happen in the near future, it will happen soon. This is an expression you often see on television: “Coming up next, we’ll learn if Rachel and Ross actually kiss!” That’s the next thing that we will see on the program. Often that happens right before a commercial or advertising break to get you to come back, to stay with the program to see what happens.
Kira answers Lee’s question: “No, I don’t!” meaning I don’t want to know which guest stars will be making appearances and the plot twists that are coming up. She says, “I don’t watch movie trailers and I don’t read reviews.” A “movie trailer” (trailer) is an advertisement for a movie, often shown in the movie theater before the movie you are going to see begins. So, you sit down to watch a movie, but first they show you advertisements for other movies. These are called “movie trailers.” You can also see movie trailers on the Web now. A “review” means, in this case, a written opinion about a movie, a book, or a television show; really anything, someone’s opinion about some product or some movie, something that is entertaining or interesting. It could be in a newspaper; it could be on a website. Many newspapers have “movie reviewers,” who every week, give their opinion about a movie and whether you should go to see it.
Well, Kira doesn’t read reviews. She says that they spoil the fun when you already know what’s going to happen. “To spoil,” as a verb, means to ruin something, to make something less fun or less useful, or perhaps even less helpful: “I went out to dinner with my wife last night, but the evening was spoiled because there was a crying child in the table next to me.” My evening was spoiled – it was ruined. Kira says, “It spoils the fun when you already know what’s going to happen. Where’s the suspense?” “Suspense” is this feeling of anticipation or excitement before something happens. Alfred Hitchcock was a famous movie director who made a lot of movies with suspense; you didn’t know what was going to happen next, or you were waiting for it with excitement.
Lee says, “The blogs and reviews I read all have “spoiler alerts” and I avoid reading those sections.” A “spoiler alert” is when someone tells you, usually on a website or in a newspaper article, that they are going to give you information about the movie and how it ends, so if you don’t want to know that, you can stop reading right now. So if a review says “spoiler alert,” then don’t read any more because you’ll find out more about the movie, unless, of course, you don’t care about reading a spoiler.
So Lee says that he doesn’t read after he sees a spoiler alert, but he also wants to tell Kira something else. He says, “Let me just tell you one thing I read,” and Kira says, “Stop right there!” meaning stop immediately. “I’m covering my ears,” so she can’t hear. “I want to stay in the dark, completely in the dark.” “To stay in the dark” or “be in the dark” means not to know something, not to be told something, to be ignorant. “I was in the dark about why my girlfriend left me” – I didn’t know why; it was a mystery to me. It’s always a mystery to me! Well, Kira wants to stay in the dark, she doesn’t want to know anything more about the television show, and then she says to Lee, “Got it?” “Got it?” here is an informal expression asking if the person understands you: “Do you understand? Am I clear?”
Lee says, “Okay, I won’t let the cat out of the bag.” “To let the cat out of the bag” means to accidentally tell someone a secret, to tell someone something that they’re not supposed to know. “He let the cat out of the bag when he told his son that he was going to get a new bicycle for his birthday.” He didn’t mean to tell him, but he accidentally did – he let the cat out of the bag. I’m not sure why the cat was in the bag; I would keep the cat in the bag if it were me, but that’s the expression. Lee says, “we’re in for a wild ride this season.” “To be in for a wild ride” means we’re going to have a lot of fun or excitement or surprises for a certain amount of time; many unexpected things are going to happen.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Lee: I’m reading this article about the new season of our favorite show. It’s premiering next week.
Kira: Don’t tell me anything about it, especially spoilers.
Lee: But don’t you want to know which guest stars will be making appearances and the plot twists that are coming up?
Kira: No, I don’t! I don’t watch movie trailers and I don’t read reviews. It spoils the fun when you already know what’s going to happen. Where’s the suspense?
Lee: The blogs and reviews I read all have “spoiler alerts” and I avoid reading those sections. Let me just tell you one thing I read…
Kira: Stop right there! I’m covering my ears. I want to stay in the dark, completely in the dark. Got it?
Lee: Okay, I won’t let the cat out of the bag, but we’re in for a wild ride this season.
Kira: I’m not listening! I’m not listening!
[end of dialogue]
Don’t stay in the dark about who wrote today’s script. It was Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
disorganized – messy and being very difficult to find things; with things not grouped by type, so that one doesn’t know where things are
* She owns hundreds of CDs, but they’re very disorganized, so she can never find the ones she wants to listen to.
to crack down – to become very strict; to begin to make someone follow rules
* The police used to just give people a warning when they drove too fast, but now, the department is cracking down and giving people very expensive tickets.
pack rat – a person who saves everything and never wants to throw things away, even if they aren’t very useful anymore
* What a pack rat! His house is filled with old papers, like movie tickets from three years ago and newspapers dating back to the early 1990s!
to turn over a new leaf – to have a new beginning; to begin a new phase in one’s life, usually to try to change one’s habits and do something better
* Each year, on January 1st, she says she wants to turn over a new leaf and start exercising, but she never goes to the gym for more than a few weeks.
to accumulate – to increase in quantity over a period of time in a particular place; to add more and more of something to a given space
* A lot of snow accumulated around our house last winter.
to put (one’s) mind to (something) – to commit to something; to decide that one will do something, especially if it is difficult or unpleasant
* Playing the violin can be difficult, but if you put your mind to it, I’m sure you can succeed.
clutter – a mess; many things that are in an area where they do not belong and need to be put away
* There’s so much clutter on the floor that we can’t even walk into our teenage son’s room!
pile – a group of many objects that are on top of each other
* They threw their dirty white clothes into one pile, and their other dirty clothes into another pile.
file – a group of papers related to a particular project or client, usually kept together in a folder
* Do you have the file for our most recent sale to the Acme Corporation?
to sort – to organize objects, grouping them by size, type, age, color, or some other characteristic
* He sorted his unwanted clothes into three groups: too small, too old, and too ugly.
to purge – to throw something away; to get rid of something; to remove or destroy something
* When he started his new diet, he purged his kitchen of all foods with added sugar, fat, or salt.
filing cabinet – a piece of furniture made of metal or wood with large drawers that can be locked and are designed so that special folders hang from the top to hold files
* This filing cabinet has all our files for the past year. Anything older is sent to storage.
to make room for (something) – to make space for something; to move one’s things so that something else can be put in its place
* They had to sell some of their office furniture to make room for the new baby in their small apartment.
to triage – to decide which things are most important and must be handled immediately, and which ones are less important and can be handled later
* When the bus hit a large truck, many people needed medical care, so the nurses had to triage them.
overflowing – with too much of something, so that it cannot all be held inside a box or another container
* Whenever it rains a lot, the swimming pool in their backyard starts overflowing.
to label – to put a small piece of paper with a written description onto another object, so that it is easy to know what that object is
* Before you put food in the freezer, please label it with today’s date.
essential – very important; critical
* The ability to work calmly in stressful situations is essential for a surgeon.
to-do list – a piece of paper where one has written down the things that one needs to do
* Each morning, she makes a to-do list, and then draws lines through each item as she finishes them during the day.
task – something that one must do, especially when it is part of a large project
* If we’re going to clean the kitchen, our first task is to wash the dishes. Then we can clean the counters and floors.
Comprehension Questions
1. Which of these things belongs in a filing cabinet?
a) A new leaf.
b) Files.
c) An inbox.
2. What does he need to purge?
a) All the things that are essential.
b) All the papers on his desk.
c) All the old files.
Answers at bottom.
What Else Does It Mean?
file
The word “file,” in this podcast, means a group of papers related to a particular project or client, usually kept together in a folder: “After he pays the bills, he puts them in files – one for each company.” The verb “to file” means to put things into folders so that one can find them easily later: “Where did you file the papers that were on my desk?” The phrase “to file (one’s nails)” means to rub a rough piece of heavy paper or metal against one’s fingernails to make them shorter and/or to change the shape of them: “She filed her nails and then painted them bright red.” The verb “to file” can also mean to give an official form or other document to an agency or organization: “When did you file your taxes last year?”
to label
In this podcast, the verb “to label” means to put a small piece of paper with a written description onto another object, so that it is easy to know what that object is: “She labeled all her children’s school supplies with a sticker that said: ‘Property of Melina’.” The phrase “to label (someone) as (something)” means to describe someone in a way that may not be true: “As a child, he was always labeled as a poor student, but the truth was that he just needed glasses.” When talking about clothing, a “label” is the small piece of fabric sewn on the inside that has the name of the manufacturer and washing instructions: “According to the label, this sweater needs to be washed by hand.”
Culture Note
In the United States, many businesspeople use “PDAs” (personal digital assistants) or other “electronic organizers” (small computers with calendars and lists) to help them “manage their time” (know what they need to do and when in order to meet deadlines and be successful). But some people still prefer to manage their time “on paper” (in writing).
The FranklinCovey company makes a popular “planner” (a special book with calendars and other sections) called the Franklin Planner. The planner is named after Benjamin Franklin, who was a very famous early American who kept a small book with all the information he needed. Today, the Franklin Planner is a “ring binder” (a special book-like cover that has metal rings that open and close to hold papers inside) with many “loose-leaf pages” (individual pieces of paper that are not connected to each other). Each page might be a calendar with one day, week, or month. People use those pages to write down important events and appointments.
These types of planners also include an “address book,” where people can write down “contact information” (phone number, email address, mailing address) for the people and organizations they need to communicate with. Other sections of the planners include a place to make to-do lists, “ledgers” (lined rows and columns) for tracking expenses, “diary” (a book where people write their private thoughts and descriptions of their day) pages, and more.
Many other companies sell similar planners under different names. “Generically,” (referring to the general name for a product, not a brand name) these are known as “day planners.” Some people thought that day planners would disappear as computers became more common, but they “remain” (are still) popular because they are small and “portable” (can be moved easily from place to place).
Comprehension Answers
1 - b
2 - c