= 0484
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 484: Getting a Performance Evaluation.
This is English as a Second Language Podcast episode 484. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode; it will help you improve your English even faster
This episode is called “Getting a Performance Evaluation,” this is related to your job or work, where your boss sits down with you and talks to you about how you have been doing – how your work has been, how your performance has been. Let’s get started.
[start of dialogue]
Emil: Have a seat. As you know, we need to talk about your annual performance evaluation. Is there anything you’d like to say before we get started?
Sandra: Yes, there is. I’ve tried really hard this year to improve on some of the shortcomings identified in my evaluation last year.
Emil: Hmm, I’m afraid that’s not reflected in this year’s evaluation. Your supervisor noted on the report that you’ve been performing below par for several months now, and your productivity is down, too.
Sandra: I can’t imagine why she would say that. If I haven’t excelled on the new project, I’ve at least pulled my weight. I don’t think she can fault me on that.
Emil: On the contrary, she thinks that you’ve been slacking off and not giving 100 percent.
Sandra: I have had some personal issues, but I didn’t think they had been affecting my work. I guess I’ve let them bring down my performance.
Emil: This was a hard decision, but we’re putting you on probation for the next three months. You’ll have another evaluation at the end of that time. If your performance isn’t up to par by that time, we’ll have to think about letting you go.
Sandra: That won’t happen. I’m going to pull out all the stops to prove myself.
Emil: Good. That’s what I wanted to hear.
[end of dialogue]
Our dialogue begins with the Emil saying, “Have a seat,” meaning please sit down. He’s talking to Sandra, who is one of his employees (someone who works for him). Emil says, “As you know, we need to talk about your annual performance evaluation.” The “performance evaluation” is a written or spoken report about how well you have done on your job, usually done every six months or one year; “annual” would be every year.
Emil says, “Is there anything you’d like to say before we get started?” Sandra says, “Yes, there is. I’ve tried really hard this year to improve on some of the shortcomings identified in my evaluation last year.” “Shortcomings” are things that you don’t do very well, things that you should be able to do better, something that is less than perfect. Not always are shortcomings things that you can change, but here I think Sandra is talking about things that she can do better, things that are less than perfect.
Emil says, “Hmm, I’m afraid that’s not reflected in this year’s evaluation.” “To be reflected,” here, means to, in this case, to be seen; something that is obvious, something that he is able to see and look at, that her changes, in other words, have not really been seen in the evaluation. The evaluation says she hasn’t changed. The verb “reflect” has a number of different meanings; take a look at our Learning Guide for some additional explanations. Emil says, “Your supervisor (your immediate boss) noted on the report that you’ve been performing below par for several months now, and your productivity is down, too.” The expression “below par” (par) comes from the sport of golfing; in general usage, it means less than expected, less than average, not as good as it should be. There’s a similar expression, “on par,” which means that it is as good as it should be, it’s right where it ought to be. But “below par” means that it is less than what it should be. Emil says that Sandra’s productivity is down. “Productivity” is, in general, the ability to do a certain amount of work in a certain period of time. If we say that someone’s productivity is down, we mean they are not doing as much work, they are not as productive.
Sandra says, “I can’t imagine why she (her supervisor) would say that.” She’s surprised, in other words. Sandra says, “If I haven’t excelled on the new project, I’ve at least pulled my weight.” “To excel” (excel) means to do something very well, better than anyone expected. She’s saying that even if she did not excel on the project she’s working on, she at least pulled her weight. “To pull your weight” means to do the work that you are expected to do as part of a group – as part of a team. Everyone has their job to do in the group; “to pull your weight” means to do what you are supposed to do. Sandra is saying that well yes, I haven’t done a great job, but I’ve done what I was supposed to do. She says, “I don’t think she can fault me on that.” To fault (someone) on (something)” means to criticize or say negative things about something that someone has done. To fault someone means to blame someone. She’s saying here that she did her work so that her supervisor can’t criticize her for that – can’t fault her on that.
Emil says, “On the contrary, she thinks that you’ve been slacking off and not giving 100 percent.” So Sandra’s supervisor, who is not at the meeting (Sandra is meeting with her higher boss, Emil), says that Sandra has been slacking off. “To slack (slack) off” is a two-word phrasal verb meaning to be lazy, not to work very hard, not to do what you are supposed to do. A phrasal verb is a verb that has more than one word, so “slack off” is a two-word verb. That’s a phrasal verb, in case you were wondering.
In this case, Sandra has been slacking off according to her supervisor, being lazy and not giving 100 percent. “To give 100 percent” means to work as hard as you can, to do your very best. Sandra now tries to provide an excuse, a reason perhaps why her supervisor might have said what she did. She says, “I have had some personal issues,” things that are not related to work such as family or friends. She’s had some personal issues – some personal problems, but she didn’t think they had been affecting her work. She says, “I guess I’ve let them bring down my performance.” “To bring down” is a two-word phrasal verb meaning to reduce, to decrease, to make something less or perhaps smaller. “To bring down your productivity” means to lower it, to make it less than it was before. “To bring down” can also mean to depress another person, to make another person feel sad. There was a song in the late 70s, Don’t Bring Me Down – don’t depress me.
Emil says, “This was a hard decision, but we’re putting you on probation for the next three months.” “Probation” is a period when you are being tested to decide whether or not they are going to keep you or let you go – fire you, in this case. A probationary period is a trial period; it’s when you are testing someone. In this case, she is going to be on probation for three months. Then, Emil says, “You’ll have another evaluation at the end of that time (at the end of three months). If your performance isn’t up to par by that time, we’ll have to think about letting you go.” “Up to par” is another one of those expressions coming from golf, meaning to be at the level we expect. It’s the same as “on par.” So she must improve her performance, if not, they may have to let her go. “To let (someone) go” is a nice way of saying to fire someone. Another way to say that would be “to lay (someone) off,” causing someone to lose their job.
Sandra says, “That won’t happen,” meaning she will improve her performance; it will not be below par. “I’m going to pull out all the stops to prove myself.” “To pull out all the stops (or ‘all of the stops’)” means to do something as hard as possible, as much as possible, as quickly as possible, to put all your effort into something. The term, I believe, originally comes from the playing of the organ, which is a instrument that is very loud, often found in churches. “To pull out all the stops” means to make the organ as loud as possible. Here it means that Sandra is going to work as hard she can to prove herself. “To prove yourself” means to show that you can do something well, to show that you are worth something, that you should be considered for something. Sandra needs to prove herself, she needs to demonstrate – to show her boss that they should keep her and not let her go.
Emil says, “Good. That’s what I wanted to hear,” I want to hear that you’re going to try to improve.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Emil: Have a seat. As you know, we need to talk about your annual performance evaluation. Is there anything you’d like to say before we get started?
Sandra: Yes, there is. I’ve tried really hard this year to improve on some of the shortcomings identified in my evaluation last year.
Emil: Hmm, I’m afraid that’s not reflected in this year’s evaluation. Your supervisor noted on the report that you’ve been performing below par for several months now, and your productivity is down, too.
Sandra: I can’t imagine why she would say that. If I haven’t excelled on the new project, I’ve at least pulled my weight. I don’t think she can fault me on that.
Emil: On the contrary, she thinks that you’ve been slacking off and not giving 100 percent.
Sandra: I have had some personal issues, but I didn’t think they had been affecting my work. I guess I’ve let them bring down my performance.
Emil: This was a hard decision, but we’re putting you on probation for the next three months. You’ll have another evaluation at the end of that time. If your performance isn’t up to par by that time, we’ll have to think about letting you go.
Sandra: That won’t happen. I’m going to pull out all the stops to prove myself.
Emil: Good. That’s what I wanted to hear.
[end of dialogue]
The script for this episode was written by someone who excels at writing good scripts, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
performance evaluation – a written or spoken report of how well one has done one’s job over a certain period of time, usually done every six months or once a year
* Employees who do well on their performance evaluation can receive a 5% raise.
shortcoming – something that is not as good as it should be; something that is less than perfect
* Tom is a wonderful guy and I’d like to keep dating him, but he has a major shortcoming: he doesn’t like children.
reflected – seen; apparent; a sign of something
* Her dislike of country music is reflected in the way that she changes the radio station every time she hears a country song.
below par – less than expected; less than average; not as good as something should be
* Tomo didn’t get enough sleep last night, so his performance on the tennis court has been below par all day.
productivity – one’s ability to do a certain amount of work in a certain period of time
* Shaina’s productivity increased when she learned how to type more quickly.
to excel – to do something very well, better than anyone had expected
* Liliana excels in math and science, but she doesn’t do very well in her history classes.
to pull (one’s) weight – to do the work that one is expected to do as part of a group; to contribute to a group’s effort or project
* Chuong never pulls his weight and always waits for the other team members to do his work for him. It’s very frustrating.
to fault (someone) on (something) – to criticize someone or say negative things about something that he or she has done or not done
* We agreed to buy that old house together, so you can’t fault me if everything is falling apart.
to slack off – to be lazy; to not work hard; to not do what one should be doing
* Makiko has really been slacking off, watching TV instead of studying.
to give 100 percent – to do one’s best; to do something as well as one can possibly do it
* She’s giving 100 percent in her new business, but it still isn’t making very much money yet.
to bring down – to decrease; to reduce; to make something less or smaller
* The poor economy has brought down sales of new cars.
probation – a trial period; a period when something is being tested to decide whether or not it should continue to be done or used
* All new employees are put on a six-month probation before they become regular, full-time employees.
up to par – meeting expectations; doing something well
* We went to eat at an expensive restaurant last night, but the food wasn’t up to par with all the good things we had heard about it.
to let (someone) go – to fire someone; to lay someone off; to take away one’s job, often because the company does not have enough money or because one hasn’t done his or her job well
* The school had to let its librarian go because there wasn’t enough money to pay for him and all the regular teachers.
to pull out all the stops – to do everything as well or as quickly as possible, without any delay or hesitation
* Gerome pulled out all the stops at his last concert. I’ve never heard him play the drums so well before!
to prove (oneself) – to show that one can do something well; to show that one has worth; to show that one should be considered for something
* Camilo has been working 12-hour days to prove himself to his new employer.
Comprehension Questions
1. Which of these phrases has the same meaning as “to give 100 percent”?
a) To pull one’s weight.
b) To let someone go.
c) To pull out all the stops.
2. Why might someone be put on probation?
a) Because one’s performance is below par.
b) Because one has excelled at work.
c) Because one’s performance is up to par.
Answers at bottom.
What Else Does It Mean?
reflected
The word “reflected,” in this podcast, means seen or apparent, or a sign of something: “Economic difficulties are reflected in the high unemployment rate.” Or, “Your education and experience are reflected in your ability to get a good job.” The verb “to reflect” means for an image to be shown in a mirror or a piece of glass, or on the surface of water: “The tall trees were reflected on the lake’s surface.” The verb “to reflect on (something)” means to think about something or to concentrate on something: “She sent her son to his room to reflect on what he had done.” Or, “Let’s take a moment to reflect on the people who have died in this war.” Finally, the phrase “to reflect on (someone)” means to change people’s opinions about someone: “The way we dress reflects on our parents and the way that they raised us.”
fault
In this podcast, the phrase “to fault (someone) on (something)” means to criticize someone or say negative things about something that one has done or not done: “You can fault him for deciding to hold the event outdoors, but you can’t fault him for the bad weather.” As a noun, a “fault” is something bad that happened because of something that one did or didn’t do: “It’s Maggie’s own fault that she doesn’t have any money. She spent way too much money while shopping last week.” A “fault” is also a problem: “There’s a major fault in the politician’s logic.” Finally, a “fault” can be a large crack in the ground where two large pieces of the Earth move against each other, creating earthquakes: “Have you ever visited the San Andreas Fault in southern California?”
Culture Note
When Americans receive a poor performance evaluation, they might be put on probation, as described in today’s podcast, but many other things can happen too, depending on why the employee is not performing well.
If the employee’s performance is below par because he or she does not know how to do the job well, he or she might get additional “training” (education to help one do one’s job better). For example, an employee who needs to learn a new computer program might be sent to training so that he or she can work better or faster using that program.
Other poorly performing employees might be “assigned” (matched) to a “mentor,” or a person who can provide guidance and support. The mentor is usually someone else in the company who is doing the same job or a similar job very well. The mentor provides “advice” (recommendations) on how to do the job better or how to improve productivity. The employee should feel comfortable asking the mentor for specific advice in improving his or her work.
If the employee simply isn’t a good “match” (the right person) for the job, then he or she might be “reassigned” to a different job, meaning that he or she begins working in a different job for the same company. For example, if an employee is underperforming because he or she is not very good at speaking with customers, then he or she might be reassigned to a “back-office” job that doesn’t require “interacting” (communicating) with the public. The same employee might also be “transferred” (moved) to a different “office” or “division” (department) within the same company, especially if the poor performance is caused by the employee’s inability to “get along with” (work well with) another employee in that office.
Comprehension Answers
1 - c
2 - a