= 0491
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 491: Having a Temper Tantrum.
This is English as a Second Language Podcast episode 491. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode that contains all the information you need to improve your English even faster.
This episode is called “Having a Temper Tantrum.” When someone gets very angry, especially a young child, we often say they have a “temper tantrum.” This is a dialogue between Alberto and Melissa using a number of different words you might use to describe this unfortunate situation. Let’s get started.
[start of dialogue]
Alberto: What was that ear-splitting scream?!
Melissa: That little girl over there is having a temper tantrum.
Alberto: Oh, great! The movie hasn’t even started and that kid is already acting up.
Melissa: I hope she’s okay. She looks miserable. Maybe her parents can distract her somehow.
Alberto: She’s fine. She’s just looking for attention or frustrated she didn’t get what she wanted. If parents didn’t give in every time their child wanted something, kids wouldn’t throw tantrums.
Melissa: I don’t know. When my son was little, he used to throw tantrums when he didn’t know how to tell us what he needed. He got frustrated and sometimes, he would start kicking and screaming.
Alberto: Well, I don’t think that’s the case here. Look at those parents. They’re going to buy the girl some candy to quiet her down. That’s just rewarding her for her misbehavior.
Melissa: What would you do instead?
Alberto: I would set limits so that things like this never happened. In this case, I would give that girl a spanking. It’s all about having consequences for bad behavior.
Melissa: Oh, yeah? Did that work with your children?
Alberto: Uh, I don’t have any kids.
Melissa: That’s what I thought!
[end of dialogue]
We begin with Alberto saying, “What was that ear-splitting scream?!” “To scream” is to yell or shout very loudly. “Ear-splitting” means that it is a very loud sound, perhaps a sound that is very high pitched, like “Ah!” That would be a high-pitched scream. That might also be a bird; it’s hard to say! In any case, an ear-splitting scream would be a scream that was very loud, very high pitched, something that would hurt your ears. That’s the meaning of “ear splitting.” “To split” something means to cut it in half.
Melissa says, “That little girl over there is having a temper tantrum.” Your “temper” is how you get mad or don’t get mad. Usually when we say somebody has a temper, we mean that they get mad very easily – they get angry very easily. A “temper tantrum” is a short period of time when a child loses control of his or her emotions by screaming, crying, perhaps even kicking; this would be a “temper tantrum.”
Alberto says, “Oh, great! The movie hasn’t even started and that kid is already acting up.” Alberto and Melissa are at a movie theater, and Alberto is complaining that this child is already acting up. “To act up” is a two-word phrasal verb meaning to do or say things that are inappropriate. Usually, it’s a verb we use to describe children who are behaving badly, who are talking or doing something that they shouldn’t be doing. We use the same expression, also, to describe things that aren’t working properly. You might say, “My computer is acting up,” meaning it’s not working the way it should. But here, when referring especially to children, it means that they are making noise or doing things that they shouldn’t be doing.
Melissa says, “I hope she’s okay. She looks miserable.” “Miserable” means very unhappy, but also very uncomfortable. If you are walking in the sun and you are sweating and it is very uncomfortable, you might say, “I’m miserable.” Or if you’re listening to me singing and your ears are splitting, you would say, “I’m miserable.” Or if you have to listen to my neighbor’s children screaming, you would be miserable – trust me!
Melissa says, “Maybe her parents can distract her somehow.” “To distract (someone)” means to do something to change what that person is thinking about. If you are feeling sad, you might go and see a happy movie to distract you, to get you to stop thinking about the bad things.
Alberto says, “She’s fine. She’s just looking for attention or frustrated she didn’t get what she wanted.” “To look for attention” means to do something to get other people to notice you – to look at you. Certain people, adults and children, want other people to pay attention, to look at them, to think that they are important, and Alberto is saying that this little girl is just looking for attention, doing something so other people will pay attention to her. Or, he says, perhaps she’s frustrated. “To be frustrated” means to be upset, to be mad, to be angry because you cannot do what you want to do, something is preventing you from doing what you want to do. Alberto says, “If parents didn’t give in every time their child wanted something, kids wouldn’t throw tantrums.” “To give in,” here, means to suddenly decide to do what someone is asking you to do. So a child says to his mother, “Mom, I want some candy,” and the mother says, “No,” and the child says, “Mom, I really want some candy,” and the mother says, “No. If you keep bothering me you’re going to have to listen to Jeff McQuillan singing.” But the child continues to say, “Mom, I really want some candy,” and finally the parent, the mother in this case, gives in. She says, “Okay, here’s some candy,” that’s to give in. Alberto also uses the expression “throw tantrums,” that’s the verb we often use; “he’s throwing a temper tantrum,” meaning having a temper tantrum.
Melissa says, “I don’t know. When my son was little, he used to throw tantrums when he didn’t know how to tell us what he needed. He got frustrated and sometimes, he would start kicking and screaming.” “To kick” means to move your legs in such a way that you try to hit someone or something. “To scream” means to yell. The expression “kicking and screaming” is used to describe someone who is out of control, when they don’t want to do something, someone who is behaving very badly, who is acting like a child.
Alberto says, “Well, I don’t think that’s the case here,” meaning I don’t think that is the situation here, that’s not what is happening. “Look at those parents,” he says, “They’re going to buy the girl some candy to quiet her down.” “To quiet (someone) down” means to do something so that the person is calmer, the person stops screaming and yelling. Alberto says, “That’s just rewarding her for her misbehavior.” “To reward (someone)” means do something nice or give someone something as a way to thank her for doing something that was good. But of course, this girl didn’t do something that was; she did something that was bad. Bad behavior is called “misbehavior.” Alberto is saying that the parents are rewarding their child for doing something wrong – for misbehaving, which, of course, will just cause her to misbehave again in the future.
Melissa says, “What would you do instead?” Alberto says, “I would set limits so that things like this never happened.” “To set limits” means to make rules and tell, in this case, the child what they can and cannot do. The word “limit” has several different meanings in English; take a look at our Learning Guide for some additional explanations. Alberto says, “In this case, I would give that girl a spanking.” “To spank (spank) (someone)” is to hit someone, usually a child, lightly when they have done something wrong, usually on their bottom (on their butt; on their rear). A parent would take their hand and hit the child in their buttocks (in their rear) lightly, we hope – not too strong, it is a child after all. Spanking is very controversial; some parents believe that you should never do that to your child, other parents don’t agree. Alberto says, “It’s all about having consequences for bad behavior.” “Consequence” is a result, something that happens because of something else. So, Alberto is saying that if the child does something wrong, something bad has to happen to the child; there must be consequences.
Melissa says, “Oh, yeah? Did that work for your children?” Alberto says, “Uh, I don’t have any kids (I don’t have any children).” So he’s giving advice about how to take care of children even though he doesn’t have any himself. Melissa says, “That’s what I thought!” meaning I knew that, I knew that what you were saying was not based on any experience.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Alberto: What was that ear-splitting scream?!
Melissa: That little girl over there is having a temper tantrum.
Alberto: Oh, great! The movie hasn’t even started and that kid is already acting up.
Melissa: I hope she’s okay. She looks miserable. Maybe her parents can distract her somehow.
Alberto: She’s fine. She’s just looking for attention or frustrated she didn’t get what she wanted. If parents didn’t give in every time their child wanted something, kids wouldn’t throw tantrums.
Melissa: I don’t know. When my son was little, he used to throw tantrums when he didn’t know how to tell us what he needed. He got frustrated and sometimes, he would start kicking and screaming.
Alberto: Well, I don’t think that’s the case here. Look at those parents. They’re going to buy the girl some candy to quiet her down. That’s just rewarding her for her misbehavior.
Melissa: What would you do instead?
Alberto: I would set limits so that things like this never happened. In this case, I would give that girl a spanking. It’s all about having consequences for bad behavior.
Melissa: Oh, yeah? Did that work with your children?
Alberto: Uh, I don’t have any kids.
Melissa: That’s what I thought!
[end of dialogue]
The script for this episode was written by someone who never makes us miserable, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
ear-splitting – very loud, high-pitched, and hurting one’s ears
* Their teenage son calls it music, but they just hear ear-splitting noise.
temper tantrum – a short period of time when a child loses control of his or her emotions and actions, usually screaming, crying, and kicking
* The little girl had a temper tantrum when her mother took away her favorite toy.
to act up – to do and say inappropriate things; to engage in inappropriate behavior
* The new employee is already acting up, asking for more money and thinking he’s the most important person in the office.
miserable – very unhappy, sad, and uncomfortable
* I would be miserable if I had to listen to people complain all day long.
to distract (someone) – to do something to change what another person is thinking about; to capture one’s attention with something else
* The teacher closed the curtains so that the students wouldn’t be distracted by what was happening outside.
to look for attention – to do something, especially a bad thing, to try to get other people to look at oneself and interact with oneself
* Why do teenagers color their hair purple and pink? Are they just looking for attention?
frustrated – upset and angry because one cannot do what one wants to do, or because something is not happening the way that one would like, and one feels helpless to change it
* They felt very frustrated when their stove, refrigerator, and washing machine all broke in the same week and they didn’t have enough money to fix them.
to give in – to suddenly decide to do what one is being asked to do, even though one does not think it is a good idea and was trying not to do it
* Have you ever given in and done something you didn’t really want to do, just because all your friends were doing it?
kicking and screaming – moving one’s legs to hurt other people or things, and yelling; a phrase use to describe one’s out-of-control behavior when one does not want to do something
* The little boy began kicking and screaming when it was time to go home, shouting, “I don’t want to leave yet!”
to quiet (someone) down – to do or say something to make another person feel calmer and stop yelling
* Sometimes the best way to quiet a baby down is to take him or her outside for a few minutes.
to reward – to do something nice or give someone something as a way to thank him or her for something good that he or she has done
* Jacek’s boss rewarded him for finishing the project early by letting him take the day off.
misbehavior – bad behavior; a way of acting that is not appropriate
* Chen is well known for her misbehavior at school, because she is always hitting other students and lying to the teachers.
to set limits – to make rules and clearly say what one can or cannot do
* Did your parents set limits on how much TV you could watch while you were growing up?
to spank – to hit someone (usually a child) lightly when he or she has done something wrong, usually hitting one’s bottom (the part of the body one sits on) with one’s hand
* When Tara saw her daughter hit the dog, she spanked her and told her to never do it again.
consequence – result; something that happens as a result of something else
* Air pollution is a consequence of driving our cars too much.
Comprehension Questions
1. What might the girl’s parents do to distract her?
a) Buy her some candy.
b) Kick and scream.
c) Spank her.
2. What does Alberto say he would do if the girl were his daughter?
a) He would buy her some candy.
b) He would yell at her.
c) He would hit her.
Answers at bottom.
What Else Does It Mean?
to give in
The phrase “to give in,” in this podcast, means to suddenly decide to do what one is being asked to do, even though one does not think it is a good idea and was trying not to do it: “She was trying to lose weight, but when she saw her family eating ice cream, she gave in and joined them.” The phrase “to give off (something)” means to make a smell or sound: “Their fridge is giving off the smell of fish.” The phrase “to give (oneself) over to (something)” means to spend a lot of time doing something: “He’s giving himself over to his work, spending less and less time with his family.” Finally, the phrase “to give up” means to stop trying to do something, usually because it is too difficult: “Marybeth has been trying to learn to play the violin for years, but she finally gave up.”
to set limits
In this podcast, the phrase “to set limits” means to make rules and clearly say what one can or cannot do: “If we don’t set limits with our children now, they’ll be horrible as teenagers.” The phrase “within limits” means up to a certain acceptable amount: “Please make yourself at home and eat anything in the kitchen – within limits.” The phrase “to have (one’s) limits” is used to show another person that he or she has done something that one thinks is unacceptable: “I’ve let you live in my house for months, but I have my limits. I want you to move out by next week.” Finally, the phrase “off limits” means “forbidden,” and is used to talk about something that one cannot touch or should not do: “These files are off limits to everyone except the detective.”
Culture Note
In the United States, there are many “unwritten rules” (rules that are not written or spoken, but everyone knows them) about how parents should “deal with” (interact with) their children “in public” (outside the home, in places where there are other people). Parents who don’t follow these rules often receive “glares” (mean or angry facial expressions) from other people – especially from people who do not have children of their own.
One of the unwritten rules is that parents should not leave their children “unattended” (without supervision) in stores. Children who are left alone in stores “tend to” (have a tendency to; are likely to) pull things off of bottom shelves. An unattended child might break things, or at least “ruin” (destroy) the store’s “display” (the way that things are arranged).
When a child begins crying or screaming in public, parents are expected to try to calm the child down and/or remove the child from the situation. If a child has a temper tantrum in a restaurant, the parent is expected to try to end the meal and leave as soon as possible. If a child begins crying in a movie theater or at a library, the parent is likely to take the child outside until he or she calms down.
In outdoor areas, like parks, children are more free to “just be children” (do things that are appropriate for their age), running around and playing. But even in a park there are unwritten rules. For example, children are expected to “take turns,” allowing other children who are waiting to play or use games and equipment to use them, and not “hog” (use only for oneself) those things.
Comprehension Answers
1 - a
2 - c