= 0500
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 500: Taking Minutes of a Meeting.
This is English as a Second Language Podcast episode 500. Can you believe it, 500 episodes of ESL Podcast! Actually, if you include our English Cafés, there’s been more than 700 episodes. Thanks to all of you for listening. I’m Jeff McQuillan, your host, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode to help you improve your English even faster.
This episode is called “Taking Minutes of a Meeting.” It’s a business related episode that will use vocabulary connected to taking notes – official notes at a business meeting. This will not be a dialogue, just me telling a short story. Let’s get started.
[start of story]
I was absent at last month’s meeting, so imagine my surprise when I found out that I had been elected the committee’s secretary! As part of my duties, I have to take minutes at each meeting. Taking minutes means I have to pay attention and try my best to transcribe what each person says, or at least do my best to summarize.
At yesterday’s meeting, the chair called the meeting to order and I conducted a roll call. Then, the chair went over the agenda and we discussed old business. We needed to vote on a couple of proposals from the past meeting, and it was my job to ask for a show of hands of those in favor of and those opposed to each one.
After that was done, we went on to new business. We talked about the first item of business for 20 minutes when someone suggested that we table the topic until the following meeting, and the participants agreed. After another long discussion about the second agenda item, we ran out of time. The chair adjourned the meeting.
Phew! That first meeting taught me a very good lesson. Never miss a meeting when new officers are being chosen!
[end of story]
I begin our story by saying that I was absent at last month’s meeting. “Absent” is the opposite of “present,” it means you’re not there. If you’re present, you are there. For example: “I was present at my wedding.” I was actually there at my own wedding – amazing, I know! “Absent” would be the opposite, that you were not there: “I was often absent from school.” I say, “I was absent at last month’s meeting,” meaning I wasn’t there, “so imagine my surprise when I found out that I had been elected the committee’s secretary!” “To be elected” means chosen, usually through a vote for a particular job or position. In the United States, we elect our president; we vote for him or her.
In this case, I got elected when I wasn’t at the meeting, meaning I didn’t know they were going to vote for me, for the committee position of secretary. A “secretary” is normally a person at a meeting who writes down notes about what happened, and then types up those notes, puts them in a Word document or prints them out, and gives them to people, usually at the next meeting. Those notes are called “minutes.” “Minutes” also refers to time; 60 seconds is one minute. But here, when we use “minutes” (plural) in talking about a meeting, we’re talking about notes from the last meeting that say what we did, what we decided, and so forth.
I say as part of my duties, I have to take minutes at each meeting. We use the verb “to take” when we talk about writing down notes about the meeting: “to take minutes.” I then say that taking minutes means I have to pay attention and try my best to transcribe what each person says, or at least do my best to summarize. “To transcribe” means to write down everything that is said, or to record everything that is said. Normally, “transcribe” means to write it; you could record it first and then write it down. When we do these episodes of ESL Podcast, after we finish we go back and we transcribe them; we write down everything that is said, and then we put that in our Learning Guide. That is what is happening here, I’m supposed to transcribe what people say at the meeting. Now of course, it would be impossible to write down everything that everyone says, so normally what we do in writing up minutes is to summarize. “To summarize” means to just say what was important, give the basic information without necessarily writing down everything that everyone said, so that’s what I have to do as the committee secretary.
At yesterday’s meeting, the chair called the meeting to order and I conducted a roll call. The “chair” is the person who leads the meeting; you can also call them the “chairperson,” or the “chairwoman,” or the “chairman.” Sometimes they’re just called “the chair.” This is the person who runs the meeting – who leads the meeting. “Chair” has a few other meanings in English; take a look at our Learning Guide for some additional explanations. So, the chair called the meeting to order. “To call a meeting to order” means to formally start a meeting, to ask everyone to be quiet so that they can begin the meeting. That’s “to call the meeting to order,” it’s what the chair does, or the person who is running the meeting – who is the boss of the meeting, you could say.
So, the chair called the meeting to order – the chair began the meeting, and I, as secretary, conducted a roll call. A “roll (roll) call” is a way to determine who is present at the meeting by calling out or naming each person: “Jeff McQuillan…Rob Smith…Barack Obama,” and so forth. If the person is there, you write down that they are there. Usually in a classroom, for example, if you take roll, or conduct a roll call (notice, once again, we use the verb “to take” – “to take roll”), you would say “present.” So, Jeff McQuillan would say “present,” Barack Obama would say “present,” and so forth, meaning you are there. Sometimes, if it’s a small meeting, you just look around and see who’s there and you write down everyone who is at the meeting.
Then, the chair went over the agenda. “To go over,” here, means to review, to talk about, to give the main information. The “agenda” is the list of things that you are going to talk about in the meeting and the order in which you will talk about them: first we’re going to talk about the budget – finances, then we’re going to talk about making technology changes in our office, then we’re going to talk about getting rid of Jeff McQuillan – because he doesn’t do his work! Those would be items on an agenda, things that you would talk about. So, the agenda is a list of the things you are going to talk about at that meeting. The agenda is usually divided between old business and new business. “Old business” are things that you’ve talked about before but you need to continue talking about, or perhaps make a decision about. “New business” are new topics, things that have not been discussed before in your meeting. Usually, you start with old business.
We needed to vote on a couple of “proposals” (a couple of ideas) from the past meeting, and it was my job to ask for a show of hands of those in favor and those opposed to each one. Let’s talk about what that means. We needed to vote (to take a vote) on a couple of proposals from the past meeting; it was my job to ask for a show of hands. A “show of hands” is a way that you can vote, with a small group of people usually. Each person who wants to say “yes” raises their hand. This, of course, is not a secret vote because you can see – indeed, you must see who is raising their hand in order to count the votes. So, a show of hands is a way of taking a vote. Usually they ask people who are “in favor,” meaning who want to vote “yes,” to raise their hands first, then they say those that are opposed should raise their hands. So, “All those in favor, raise your hand. All those opposed, raise your hand,” and then you count and you see which one is more. If you are going to just say your vote out loud, we use the words “aye” (aye) and “nay” (nay): “All those in favor, say ‘aye’.” That means if you are wanting to vote “yes,” instead of raising your hand you would just say the word “aye.” “All those in favor – aye.” Those “opposed,” those that want to vote “no” then say the word “nay.” That, then, is if you are going to take what we would call a “voice vote,” voting by people just speaking. In my meeting, however, we are voting by raising our hands.
After the vote was done, we went on to new business. We talked about the first “item” (the first thing) for 20 minutes when someone suggested that we table the topic until the following meeting, and the “participants” (the people at the meeting) agreed. “To table,” as a verb, means to delay or postpone, to stop talking about something now but agree to talk about it again at a future meeting.
After another long discussion about the second agenda item, we “ran out of time,” meaning we didn’t have any more time left to talk more. The chair adjourned the meeting. “To adjourn” means to officially end the meeting, to let people know that the meeting is over and they can now leave.
Finally I say, “Phew!” (phew). That sound means that something is over, or that you are relieved; you are happy that some difficult thing has ended. I say, “That first meeting taught me a very good lesson. Never miss a meeting when new officers are being chosen!” An “officer” is someone who has an official position in an organization. Usually, organizations have a president, a vice president, a “treasurer” (someone who takes care of the money), and a “secretary” (someone who does the paperwork, including taking minutes at a meeting). I’m saying here that I don’t ever want to miss a meeting when the group is going to elect new officers, so I can avoid being elected.
If you’re interested in business meetings, we have a special course called “English for Business Meetings,” which you can find on our website at eslpod.com.
Now let’s listen to the story, this time at a normal speed.
[start of story]
I was absent at last month’s meeting, so imagine my surprise when I found out that I had been elected the committee’s secretary! As part of my duties, I have to take minutes at each meeting. Taking minutes means I have to pay attention and try my best to transcribe what each person says, or at least do my best to summarize.
At yesterday’s meeting, the chair called the meeting to order and I conducted a roll call. Then, the chair went over the agenda and we discussed old business. We needed to vote on a couple of proposals from the past meeting, and it was my job to ask for a show of hands of those in favor of and those opposed to each one.
After that was done, we went on to new business. We talked about the first item of business for 20 minutes when someone suggested that we table the topic until the following meeting, and the participants agreed. After another long discussion about the second agenda item, we ran out of time. The chair adjourned the meeting.
Phew! That first meeting taught me a very good lesson. Never miss a meeting when new officers are being chosen!
[end of story]
We’re lucky that our scriptwriter was not absent today; she is Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
absent – not present; not there; not participating in something, especially in a class or a meeting
* Three students were absent yesterday, apparently because they were sick.
elected -– chosen through a vote for a particular role, job, or position
* Is the Secretary of State elected by Americans or chosen by the President?
secretary – a person whose job is to write notes during meetings and provide other administrative, typing, and clerical support
* Michelle types very slowly, so she hired a secretary to type everything for her.
to take minutes – to create a short report about what happens and what is talked about during a meeting
* Did anyone take minutes for the last meeting? I wasn’t there, but I’d like to read about what was discussed.
to transcribe – to write down something that is said or recorded
* The doctor records his notes on a small mp3 player, and his assistant transcribes them for the written records.
to summarize – to say or write the most important parts of something, without including all the details
* Please summarize the problem when we present it to the vice-president. He won’t want to hear all the specific details.
chair – chairperson; the person who leads a meeting, deciding who can speak, for how long, and on which topics
* The chair welcomed everyone to the meeting and then asked Nimia to speak about her project.
to call the meeting to order – to formally start a meeting; to ask everyone to be quiet so that a meeting can begin
* They called the meeting to order at 9:34 a.m. and it lasted for almost two hours.
roll call – a way to determine who is present or at a meeting, calling out each person’s name and waiting for that person to say “present” or “here” if he or she is in the room
* It was very difficult to pronounce some of the names during the roll call!
agenda – a written plan for what will be discussed in a meeting and when
* The agenda shows that we have 20 minutes to talk about sales, 30 minutes to discuss marketing, and 10 minutes for questions.
old business – topics that have been discussed in the past but need to be discussed again; ongoing topics or issues
* We discussed five things in last week’s meeting, and we’re going to talk about three of them again today as part of old business.
a show of hands – having people hold up their hand in the air if they agree with something or are interested in something
* The teacher asked for a show of hands to see which students had finished the assignment.
in favor of – wanting something to happen; voting “yes” for something; liking or approving something
* Very few people are in favor of tax increases.
opposed to – not wanting something to happen; disliking something; rejecting something
* Why are you opposed to opening a new library? I think it’s a good idea.
new business – topics that have not been discussed in the past; topics that are being discussed now for the first time
* If you have a new idea for the neighborhood association, you should talk about it when everyone is discussing new business.
to table – to delay or postpone; to stop discussing something before the conversation is finished, planning to continue discussing it at a later time
* We’ve been arguing about this for hours. Let’s table the discussion and come back to it later after we’ve had some time to think about the issue.
to adjourn – to officially end a meeting and let people know they can leave
* The president didn’t adjourn the meeting until almost 11:00 p.m. last night, so we’re all really tired today.
officer – someone who has an official position in an organization, often an elected position
* The organization has four officers: the president, vice-president, secretary, and treasurer.
Comprehension Questions
1. What should the secretary do at the meeting?
a) Watch the clock to make sure the meeting doesn’t run late.
b) Decide when the meeting should begin and end.
c) Write down what everyone says and does.
2. What does it mean to “table” a topic?
a) To describe it on a piece of paper and place it on a table.
b) To decide to talk about it at another time.
c) To sit around the table and discuss it.
Answers at bottom.
What Else Does It Mean?
chair
The word “chair,” in this podcast, means the person who leads a meeting, deciding who can speak, for how long, and on which topics: “Who’s going to be the chair for our meeting next month?” Normally a “chair” is a piece of furniture that has four legs and a small surface for one to sit on: “How many chairs can fit around your dining table?” Or, “Which chair should I sit in?” When Americans say “the chair,” they’re referring to the electric chair, which is used to kill people as a punishment for something criminal they have done: “The judge sent the murderer to the chair.” In a university, a “chair” is the head or leader of a department: “Have you met the new chair of biophysics?”
in favor of
In this podcast, the phrase “in favor of” means wanting something to happen, or voting “yes” for something: “Which senators are in favor of stronger gun control?” The phrase “to fall out of favor” means to stop being popular or to lose approval: “The idea that women should stay at home all day fell out of favor in the U.S. in the mid-1900s.” Normally a “favor” is something nice that one does for another person, often trying to help that person in some way: “Could you please do me a favor and buy some milk on your way home from work?” Or, “No, you don’t need to pay me back. I did it as a favor.” The phrase “the odds are stacked in (one’s) favor” means that someone has an advantage and is likely to win or be successful: “That team has really strong players, so the odds are stacked in its favor.”
Culture Note
Most American organizations have “certain” (specific; defined) officers or leaders, such as the president, vice-president, and secretary. But there are many other “roles” (positions; jobs) that might be “less familiar” (less well-known) to you.
The “treasurer” is the person who is responsible for the organization’s money and “budget” (a written plan for how money will be spent). The treasurer controls the bank account, writes “checks” (pieces of paper that one can take to the bank to get money), and pays the organization’s bills. The treasurer reports on the organization’s “assets” (money and other things that are owned) at each meeting.
An “ombudsperson” (also known as an “ombudsman”) is someone who “handles” (deal with; responds to) “complaints” (negative comments) from people outside the organization. For example, if someone writes a letter stating that the organization treated him or her unfairly, the ombudsperson leads the organization in deciding how to respond to that complaint.
“Nowadays” (in these times; in modern times), many organizations have a “webmaster” who is responsible for creating and/or maintaining the organization’s website. The webmaster might also read and respond to emails received from people outside the organization.
A “historian” is someone who “keeps records” (writes things down) of what the organization has done, possibly taking photographs of the organization’s activities and “storing” (putting in a safe place for the future) copies of brochures or newspaper articles.
Other organizations have “editors” (people who create newsletters), “volunteer coordinators” (people who try to get other people to work for the organization for free), and “social chairs” (people who create fun events for the organization’s members). Most of these positions are elected by the organization’s members.
Comprehension Answers
1 - c
2 - b