= 0622
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 622: Having Well- and Badly-Behaved Children.
This is English as a Second Language Podcast episode 622. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Become a member of ESL Podcast and help support our efforts. When you become a member you can download a Learning Guide, an 8- to 10-page guide we make for all of our current episodes that will help you improve your English even faster.
This episode is a dialogue between Josephine and Ray talking about children who behave – who act in a nice way, and sometimes in a not nice way. Let’s get started.
[start of dialogue]
Josephine: Hello.
Ray: Hi, Josephine, it’s Ray. We have a meeting today at 10 a.m. and I was wondering if you would mind if I brought my kids with me. Their babysitter didn’t show up.
Josephine: Oh, sure. That’s no problem. Your children are so well-behaved. Even at their age, they have impeccable manners.
Ray: Well, they’re not always little angels, but they’re not too much of a handful, thank goodness.
Josephine: You know what they say: Girls are made of sugar and spice and everything nice…
Ray: It is probably a little easier with two girls. I feel sorry for my mother who raised six boys.
Josephine: Six boys!
Ray: Yeah, and before we were born, my father thought that children should be seen but not heard. Was he in for a rude awakening! We were all very unruly. Imagine six boys only one year apart. We got yelled at a lot for being naughty.
Josephine: But that’s how boys are, aren’t they? Girls are different. They’re quiet, sweet, and even-tempered. What’s that noise?
Ray: That noise is my daughters creating a ruckus fighting tooth and nail over a toy. So much for quiet, sweet, and even-tempered!
[end of dialogue]
Our dialogue begins with Josephine answering the telephone, “Hello.” Ray says, “Hi, Josephine, it’s Ray (meaning this is Ray calling you). We have a meeting today at 10 a.m. (10 o’clock in the morning) and I was wondering if you would mind if I brought my kids with me.” “I was wondering (I wasn’t sure) if you would mind (meaning if you care; if it’s important to you; if it bothers you) if I brought my kids (my children) with me. Their babysitter didn’t show up.” A “babysitter” is someone who watches your children while you go and have a nice dinner and a movie. The expression “to show up” means to arrive, to go to some appointment that you have, to be somewhere that you are supposed to be.
Well, the babysitter didn’t show up, didn’t come to Ray’s house, and so now he needs to bring the children to his business meeting. Josephine says, “Oh, sure. That’s no problem. Your children are so well-behaved.” To be “well-behaved” (behaved) means that you act in a way that is nice, that follows the rules, that doesn’t bother other people. Typically, it’s a way that we would describe children, not adults. But, you can say “That child is very well-behaved,” meaning they don’t yell, they don’t scream, they are very polite. Josephine says that Ray’s children are well-behaved. “Even at their age,” she says, “they have impeccable manners.” “Even at” in this case means surprisingly. Their age is obviously young, and yet they still have good manners. “Manners” describes the way that you act, the way that you behave. “Impeccable” means perfect, no problems. Someone with impeccable manners is someone who always says the right thing, who does the right thing, who’s never rude, who is always polite.
Ray says, “Well, they’re not always little angels, but they’re not too much of a handful, thank goodness.” Ray says his children are not always “little angels,” that would be a child who behaved perfectly. An “angel” is a spirit in many religions that is usually described as being good, as being perfect. Unless, of course, it’s a bad angel, that would be what we would call a devil. That’s also what we call some of the children who live near my house! But, back to the story: Ray says his children are not always perfect, “they’re not always little angels, but they’re not too much of a handful.” When we say something is a “handful” (handful) we mean they are a lot of work or it is a lot of work, something that is difficult to manage. They’re not much – or too much of a handful, thank goodness. By the way, “handful” has some other meanings that you can find in our Learning Guide. The expression “thank goodness” is used to show your appreciation, your gratitude when you want to thank someone. Often we use it to express relief, meaning you think something bad is going to happen, and then it doesn’t. We say you are relieved, you are happy the bad thing didn’t happen. Well here, Ray says, “thank goodness,” thank goodness that his children are well-behaved. He’s appreciating, or he is thankful for that.
Josephine says, “You know what they say: Girls are made of sugar and spice and everything nice.” “Girls are made of sugar and spice and everything nice” means that little girls never cause problems. Ray says, “It is probably a little easier with two girls.” Ray obviously has two girls. He says, “I feel sorry for my mother who raised six boys.” “To feel sorry for (someone)” means that you are sympathetic; you feel sympathy, you feel sad or bad about a difficult situation that this other person is in.
Josephine says, “Six boys!” Ray says, “Yeah, and before we were born, my father thought that children should be seen but not heard.” This is an old expression: “Children should be seen (you can see them) but not heard (you shouldn’t be able to hear them.” In other words, the children should be quiet; they should not talk. Ray says that his father, unfortunately, was in for a rude awakening. Something that is “rude” is something that is not nice, something that is unpleasant. An “awakening” is when, literally, you wake up; you’re sleeping and then you wake up. A “rude awakening,” then, would be something that surprises you, something very negative. You thought it was going to be positive, but then suddenly you find out that it is very unpleasant. It’s an unpleasant surprise, a not nice surprise.
Ray says that he and his brothers were all very unruly. “To be unruly” (unruly) means difficult to manage, difficult to keep calm, uncontrollable. Again, it’s a way you might describe children, but you could also use this adjective to describe a group of adults who are acting or behaving very badly, yelling and shouting and so forth. It’s often used to describe a crowd – a large group of people who are behaving badly, kind of like at a British soccer game – something like that! Ray says, “Imagine six boys only one year apart,” meaning that one was born, for example, in 1955, the next one was born in 1956, the next one was born in 1957, and so forth. They’re only one year apart – one-year difference in their ages. He says that he and his brothers got yelled at a lot for being naughty. “To yell (yell) at (someone)” means to shout at them, to say very negative things to them. “Naughty” (naughty) is a somewhat old-fashioned word in American English; it means to behave badly. Typically we use this in describing children – small children who are not well-behaved.
Josephine says, “But that’s how boys are, aren’t they? Girls are different. They’re quiet, sweet, and even-tempered.” “To be sweet,” in describing a person, could mean that they are nice, they are kind, they are pleasant. “Sweet” has several other meanings in English, those can be found in the Learning Guide. “To be even-tempered” means that you are very calm, you don’t get very excited. You’re not very happy, you’re not very sad; you’re sort of very calm and relaxed. That’s even-tempered (tempered).
Then Josephine says, “What’s that noise?” Ray says, “That noise is my daughters creating a ruckus fighting tooth and nail over a toy.” So the two daughters are making noise; they’re creating a ruckus (ruckus). A “ruckus” is a noisy, confusing situation. Often it’s related to an argument – a fight that two people are having. It could be used to describe adults as well as children. “What’s all this ruckus in here?” a father might say to his sons who are in their room fighting about something. That never happened to me, of course!
Ray says that the girls are fighting tooth and nail (nail). This expression, “tooth and nail,” means very strongly, perhaps violently, maybe they’re hitting each, but with a lot of strength – a lot of effort. Usually it’s used with the verb “to fight.” It could be used to describe, for example, a company that is fighting tooth and nail to survive. They’re fighting very hard – they’re working very hard to survive. Ray finally says, “So much for quiet, sweet, and even-tempered!” “So much for (something)” is a phrase that we use jokingly to show that something that you thought that was true is not true, or that there isn’t very much of something when you expected there to be a lot of something. It’s used, we would say, sarcastically. Ray is saying here that the daughters are not the way Josephine described girls, they’re not quiet, sweet, and even-tempered. Right after they finished talking about how nice girls are, of course, the girls have a fight.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Josephine: Hello.
Ray: Hi, Josephine, it’s Ray. We have a meeting today at 10 a.m. and I was wondering if you would mind if I brought my kids with me. Their babysitter didn’t show up.
Josephine: Oh, sure. That’s no problem. Your children are so well-behaved. Even at their age, they have impeccable manners.
Ray: Well, they’re not always little angels, but they’re not too much of a handful, thank goodness.
Josephine: You know what they say: Girls are made of sugar and spice and everything nice…
Ray: It is probably a little easier with two girls. I feel sorry for my mother who raised six boys.
Josephine: Six boys!
Ray: Yeah, and before we were born, my father thought that children should be seen but not heard. Was he in for a rude awakening! We were all very unruly. Imagine six boys only one year apart. We got yelled at a lot for being naughty.
Josephine: But that’s how boys are, aren’t they? Girls are different. They’re quiet, sweet, and even-tempered. What’s that noise?
Ray: That noise is my daughters creating a ruckus fighting tooth and nail over a toy. So much for quiet, sweet, and even-tempered!
[end of dialogue]
Our scriptwriter today was that made of sugar and spice and everything nice, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
well-behaved – acting in ways that are socially appropriate and pleasing to other people; following all the rules and meeting people’s expectations
* Why can’t you be well-behaved like Janet’s children? They never argue or fight with each other.
impeccable manners – acting in ways that are perfect, with nothing to criticize; following all the rules for socially acceptable behavior
* Jeremiah has impeccable manners, always saying “excuse me,” “please,” and “thank you.”
little angel – a young child who behaves very well and is a joy to spend time with
* As long as Noah gets enough sleep, he’s a little angel. But when he gets tired, watch out!
handful – a lot of work; or something that is challenging to deal with and manage
* It’s quite a handful to go grocery shopping with three little kids under the age of five!
thank goodness – an expression used to show one’s relief, gratitude, and appreciation for something
* Thank goodness that tree didn’t hit our house when it fell down!
girls are made of sugar and spice and everything nice – part of a poem meaning that little girls are very nice to spend time with, much nicer than little boys
* We’re hoping to have a girl, because you know what they say: Girls are made of sugar and spice and everything nice…
to feel sorry for (someone) – to feel sympathy for a person; to feel sad or bad about the situation another person is in
* I feel sorry for Burt. It isn’t his fault he lost his job, but his wife seems to blame him.
children should be seen but not heard – an old-fashioned belief and expression meaning that children should be silent, not making any noise when adults are nearby
* Their parents encourage them to talk and play, but their grandparents believe that children should be seen but not heard, so that creates problems when they go to stay with their grandparents.
rude awakening – an unpleasant surprise; a negative experience that shows how much reality differs from what one had believed or hoped for
* Sherri thought her new job would be easy, but she was in for a rude awakening.
unruly – uncontrollable; difficult to manage or keep calm
* The teacher walked into the unruly classroom and told the students to be quiet and to do their work.
(#) year(s) apart – with a certain number of years of difference between two people’s ages; with a certain period of time between two events
* My brother and I are 13 years apart, so we weren’t really friends when we were growing up.
to yell at (someone) – to shout at a person; to speak to someone in a very loud voice, saying negative things, often when one is angry and wants to criticize the other person
* Jayden never cleans his room, no matter how much his father yells at him.
naughty – behaving poorly; doing bad things that are against the rules, used primarily with children
* Why did you take that toy away from the other little girl? That was a very naughty thing to do.
sweet – nice, kind, gentle, pleasant, and calm
* Ling is a sweet girl, but I just don’t feel attracted to her romantically.
even-tempered – without rapidly changing emotions; calm; without moments of extreme happiness, sadness, or anger
* How does Eugene stay so even-tempered? Even when everyone else is upset, he always seems calm.
ruckus – a noisy, completely confusing situation often involving an argument
* The falling stock prices caused a ruckus on Wall Street.
tooth and nail – with a lot of strength and effort; very strongly, perhaps violently
* They’re fighting tooth and nail to increase the budget for next year.
so much for (something) – a phrase used sarcastically to show that something does not apply, or that there is not very much of something
* City taxes have increased 15% since he was elected mayor. So much for his campaign promise to lower taxes!
Comprehension Questions
1. What does Josephine mean when she says that Ray’s daughters have “impeccable manners”?
a) They are always very polite.
b) They are always very well-dressed.
c) They are always very quiet.
2. What does Ray mean when he says that his father was “in for a rude awakening”?
a) His father experienced an unpleasant surprise.
b) His father was always woken up by his children too early in the morning.
c) His father thought the children were very impolite.
Answers at bottom.
What Else Does It Mean?
handful
The word “handful,” in this podcast, means a lot of work, or something that is challenging to deal with and manage: “Young children can be a handful, but they’re also a source of so much joy and happiness.” A “handful” is also the amount of something that one can hold in one hand: “She added a handful of sliced carrots to the stew.” Or, “He often eats a handful of almonds as a snack in the afternoon.” Finally, a “handful” can be used to describe a small amount of something or a small number of something: “They reserved a large conference room because they thought a lot of people would attend, but only a handful of people came to the meeting.”
sweet
In this podcast, the word “sweet” means nice, kind, gentle, pleasant, and calm: “It was very sweet of you to send flowers to my grandmother while she was in the hospital.” The word “sweet” is also used to describe the taste of sugar: “This tea is really sweet! How much honey did you put in here?” The phrase “to have a sweet tooth” means to enjoy desserts and other sweet foods: “Wally has a sweet tooth and eats chocolate at least once a day.” The phrase “a sweet deal” is used to describe a bargain, or a transaction where one paid a very low price: “We got a sweet deal on a used car.” Finally, “sweet nothings” are loving phrases that people whisper or say to each other: “She loves it when her husband whispers sweet nothings into her ear.”
Culture Note
One popular “nursery rhyme” (a short poem that is often said or sung to babies and young children) “dates back to” (was created in) the early 1800s. It is called What Are Little Boys Made Of and it is about the differences between little girls and little boys.
What are little boys made of?
What are little boys made of?
Snakes and “snails” (small animals that carry their spiral shell homes on their back)
And “puppy-dogs'” (baby dogs) tails,
That's what little boys are made of.
In other words, boys are “associated with” (thought about in connection with) “slimy” (slightly wet and slippery) animals that most people don’t want to touch, as well as young dogs that are very active and never stop moving. Little boys enjoy getting dirty, moving around, and making a lot of noise. The nursery rhyme doesn’t mean that little boys are bad, but “rather” (instead), that they are different from little girls.
The nursery rhyme “goes on” (continues) this way:
What are little girls made of?
What are little girls made of?
Sugar and “spice” (powders made from plants that have strong smells and flavors and are used to make food taste better)
And all that's nice,
That's what little girls are made of.
According to the nursery rhyme, girls are sweet and smell good, and they’re very pleasant to be around.
This is a popular, well-known nursery rhyme and Americans sometimes “make reference to” (mention; talk about) it. You can also see the phrases printed on babies’ clothing. Sometimes a little boy’s shirt will say “snakes, snails, and puppy-dog tails” and a little girl’s shirt will say “sugar, spice, and all that’s nice.”
Comprehension Answers
1 - a
2 - a