= 0633
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 633: Moving Out of a Home.
This is English as a Second Language Podcast episode 633. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful – and I do mean beautiful – Los Angeles, California.
Our website is eslpod.com, but you know that already. Did you know that you can download a Learning Guide for this episode on our website? That’s right. Go there today and get more information about becoming an ESL Podcast member. If you become a member, you will be healthy, wealthy, and wise. Well, wise at least!
This episode is called “Moving Out of a Home.” It’s a dialogue between Andre and Ellie. Let’s get started.
[start of dialogue]
[A knock on door.]
Andre: Hello. Is anyone here?
Ellie: Yes, can I help you?
Andre: I saw your door open and I just wanted to make sure everything was okay. Did you just move in?
Ellie: No, I’m moving out. As you can see, I’m doing last-minute packing. I think I’ve used up 10 rolls of packing tape!
Andre: This looks like a major undertaking. Are you moving yourself?
Ellie: No, the movers are coming with the moving van tomorrow morning. I’m moving a few things into storage, and I’ll take a few of the perishables and essentials in my car, but they’ll be doing the heavy lifting. No loading for me. Before they come, though, I need to disassemble this desk and this bookcase. It’ll be a long afternoon.
Andre: I can see that. Are you moving far?
Ellie: No, I’m only moving about a mile from here to another apartment.
Andre: Oh, so you’re not moving out of the area.
Ellie: No, I’m not.
Andre: I’m glad to hear that. Let’s make a deal: I’ll help you disassemble your furniture if you’ll promise to invite me over to your new place sometime.
Ellie: Really? Are you sure you’re willing to do that?
Andre: Sure. Hand me those tools and I’ll have it done in no time.
Ellie: Boy, am I glad I left my door open.
Andre: Yeah, so am I.
[end of dialogue]
Our dialogue begins with Andre knocking on a door. He says, “Hello. Is anyone here?” Ellie says, “Yes, can I help you?” Andre says, “I saw your door open and I just wanted to make sure everything was okay.” Andre apparently lives near this house, saw the door open, and for some weird reason decided to go and find out who was there. He says, “Did you just move in?” “To move in” is a two-word phrasal verb that means to begin living in a new place, when you move all of your things to a new apartment or a new house. Ellie says, “No, I’m moving out.” “To move out” is the opposite of “to move in,” it’s when you are leaving a place: your apartment or your house.
Okay, so Andre doesn’t know this woman, and he doesn’t know that she’s been living there, so maybe Andre isn’t from the neighborhood. Maybe Andre is a thief – a crook, a criminal. Let’s find out!
Ellie continues, “As you can see, I’m doing last-minute packing.” To do anything “at the last minute” means to do it right before the deadline, right before it has to be done, to wait until there is no more time left. “To pack” (pack) means to put your things in boxes, in suitcases so you can move them. So, “last-minute packing” (“packing” here is a noun) means the process of putting all your things in boxes to move them at the very last possible opportunity. Ellie says, “I think I’ve used up 10 rolls of packing tape!” “To use up” means to complete, to finish, to have no more of. In this case, she’s used up 10 rolls of packing tape. “Packing tape” is wide, thin plastic tape – tape is sticky on one side – and you use it to close a box to make sure it stays closed. The tape typically comes on a “roll,” that’s a circle that you can then pull the tape off of.
Andre says, “This looks like a major undertaking.” Anything that is “major” is large or important, big. An “undertaking” is a task, a job to do, often a long and difficult one. So you will often see these words together, “a major undertaking,” meaning a big job to do. “Are you moving yourself?” Andre says, meaning are you doing this alone, is no one helping you. Of course, we think Andre is interested in stealing her stuff and so, of course, he wants to know if anyone else is coming over.
Ellie, unhappily, says, “No, the movers are coming with the moving van tomorrow morning.” The “movers” are the people whose job it is to come and help you pack. You can actually hire people, pay them to come to your house and help you put all your things into boxes if you have a lot of things, or perhaps if you’re old and don’t have the strength – or if you’re just lazy! Ellie is having the movers come over tomorrow with the moving van. By the way, I should mention “mover” has a couple of different meanings in English, and those are in the Learning Guide. A “van” is a large truck that is used usually to move things from one place to another. A “moving van” is usually a large what we would call “semi” or “semi truck.” She says, “I’m moving a few things into storage, and I’ll take a few of the perishables and essentials in my car, but they’ll be doing the heavy lifting.” “Storage” is a place where you can keep your boxes and other things, perhaps because you don’t have room in your house, perhaps because you are moving to a smaller house, or because you just hate to throw anything away – to get rid of anything – and you have too much stuff. We all have too much stuff I think!
Ellie says, “I’ll take a few of the perishables and essentials in my car.” Something that is “perishable” (perishable) is something, usually food, that you need to keep in a freezer or refrigerator. If you don’t, the food will, we would say, go bad; you won’t be able to eat it anymore. So meat, for example: you can’t keep the meat outside of a refrigerator for two days, the meat will go bad. In fact, the recommended amount of time I think is two hours maximum. So, she’s taking these perishable with her. She’s also taking other “essentials,” things that she absolutely must have, things that she can’t wait to use: her toothbrush, or perhaps her favorite pillow. The movers, however, will be doing the heavy lifting. “To lift” (lift) means to take something very heavy and move it off of the ground or off of a table. You are picking it up; you are lifting it. So, “heavy lifting” as a noun is when you have a lot of very heavy things – things that weigh a lot that need to be moved. Sometimes we use this expression just to mean a difficult task, something that is difficult or hard to do. She says, “No loading for me.” “To load” (load) means to put the boxes into the moving van; “to load” is usually use when you are moving or going from one place to another and you are taking things with you. If you are going to the airport, you will need to load your luggage – load your suitcases into your car. She needs to load the boxes into the moving van but she’s not going to do it herself, that’s why she says, “No loading for me.” “Before they come,” she says, “I need to disassemble this desk and this bookcase.” “To disassemble” is the opposite of “assemble.” “To assemble” is to put something together; “to disassemble” is to take something apart.
Ellie says, “It’ll be a long afternoon,” meaning I have a lot of work to do Andre, what do you want. Andre says, “I can see that. Are you moving far?” Ellie says, “It’s none of your business buddy!” No, she doesn’t say that, does she? No, she says, “No, I’m only moving about a mile from here to another apartment.” Andre says, “Oh, so you’re not moving out of the area,” meaning away from this city. She says, “No, I’m not.” Andre says, “I’m glad to hear that. Let’s make a deal.” “To make a deal” means to reach an agreement with someone, when both people get something out of your agreement. Well here’s the agreement: Andre says, “I’ll help you disassemble your furniture (your desk and bookcase) if you’ll promise to invite me over to your new place sometime.” Now we see that Andre is not a criminal; he’s someone who is trying to start a romantic relationship with Ellie, you see. He says, “I’ll disassemble your furniture if you invite me over,” meaning if you ask me to come to your house for dinner, and Ellie says, “Really? Are you sure you’re willing to do that?” So Ellie obviously likes Andre. She probably shouldn’t since she has a boyfriend. Oh, you didn’t know that? Yeah, she does!
Andre says, “Sure. Hand me those tools (meaning give me those tools) and I’ll have it done in no time.” “Tools” are things that you use to help you do something else. You could have a hammer, you could have a screwdriver; those are tools that you would use, perhaps to disassemble something. Andre says, “I’ll have it done in no time,” meaning very quickly, very soon. Ellie says, “Boy, am I glad I left my door open so that any strange man could come in and start talking to me.” She really just said, “Boy, am I glad I left my door open,” but she meant what I said! Andre says, not surprisingly, “Yeah, so am I.” Nice job Andre – if that’s your real name!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
[A knock on door.]
Andre: Hello. Is anyone here?
Ellie: Yes, can I help you?
Andre: I saw your door open and I just wanted to make sure everything was okay. Did you just move in?
Ellie: No, I’m moving out. As you can see, I’m doing last-minute packing. I think I’ve used up 10 rolls of packing tape!
Andre: This looks like a major undertaking. Are you moving yourself?
Ellie: No, the movers are coming with the moving van tomorrow morning. I’m moving a few things into storage, and I’ll take a few of the perishables and essentials in my car, but they’ll be doing the heavy lifting. No loading for me. Before they come, though, I need to disassemble this desk and this bookcase. It’ll be a long afternoon.
Andre: I can see that. Are you moving far?
Ellie: No, I’m only moving about a mile from here to another apartment.
Andre: Oh, so you’re not moving out of the area.
Ellie: No, I’m not.
Andre: I’m glad to hear that. Let’s make a deal: I’ll help you disassemble your furniture if you’ll promise to invite me over to your new place sometime.
Ellie: Really? Are you sure you’re willing to do that?
Andre: Sure. Hand me those tools and I’ll have it done in no time.
Ellie: Boy, am I glad I left my door open.
Andre: Yeah, so am I.
[end of dialogue]
How do you learn English in no time? Keep listening to these wonderful scripts by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Come back and listen to us again, if you have a chance, here at ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
to move in – to begin living in a new place; to move all of one’s belongings into a home so that one can begin living there
* Don’t forget to call the electricity and gas companies to set up your accounts before you move into the new apartment.
to move out – to stop living in a place; to move all of one’s belongings out of a home so that one can go somewhere else to live
* Quincy is really excited about moving out of his parents’ home to go to college.
last-minute packing – the process of putting things in boxes immediately before one is leaving, often because one has waited too long
* Ermin hates the stress of last-minute packing, so he usually has everything ready at least four days before he goes on a trip.
packing tape – a roll of wide, thin plastic that is sticky on one side and is used to close cardboard boxes by taping together the sides of the tops and bottoms
* You can buy boxes and packing tape at the post office if you need to send a package.
major undertaking – a large and/or difficult task or project that requires a lot of planning and work
* Painting the exterior of a three-story home is a major undertaking. Why don’t you hire someone else to do it, instead of trying to do it yourself?
mover – a person whose job is to help people pack their belongings, put them into a large truck, drive them to a new location, and then take them out of the truck and into the new building, possibly unpacking the belongings, too
* Write “bedroom,” “bathroom,” or “kitchen” on each box, so the movers know where to put them.
moving van – a large truck used to carry furniture and boxes from one apartment, home, or office to another
* If you have a one-bedroom apartment, a 10-foot moving van is probably big enough, but if you have a five-bedroom home, you might need a 27-foot moving van.
storage – facilities where one can keep one’s belongings until they are needed
* They’re moving out of their home on the 7th, but their new home won’t be ready until the 30th, so they have to put all their things in storage for a few weeks.
perishables – things that will go bad and be unusable if they are not used within a short period of time
* When Ken moved overseas, he left all his perishables with his neighbor, like milk, eggs, bread, mayonnaise, and other groceries.
essentials – things that one must have and cannot live without
* It’s just an overnight trip, so I packed only the essentials: clean underwear, a toothbrush, and a comb.
to lift – to raise heavy things off the ground or another surface, usually so they can be taken somewhere else
* If you need to lift heavy boxes, use your knees, not your back.
to load – to put boxes or bags into a vehicle so they can be taken somewhere
* Packing everything into boxes took hours, but loading them into the truck was quick and easy.
to disassemble – to take something apart; to separate the pieces of something
* Have you ever tried to disassemble a computer or cell phone to learn how it works?
to make a deal – to reach an agreement with someone, usually with both parties receiving some benefit
* Let’s make a deal: I’ll cook if you’ll wash the dishes.
to invite (someone) over – to ask someone to come into one’s home, usually for fun or for a social event
* The Sissons have invited us over for dinner next Friday.
tool – something that is used to do a job or to make something easier, usually held in one’s hand
* The only tool you’ll need to assemble this bookcase is a screwdriver.
in no time – very soon; very quickly
* I know you’re scared of needles, but you need this shot. Just close your eyes and take a deep breath, and it’ll be done in no time.
Comprehension Questions
1. Which of these is an example of a perishable?
a) A bookcase.
b) A blanket.
c) A banana.
2. What does Ellie need to do with her desk and bookcase before the movers come?
a) She needs to empty them.
b) She needs to take them apart.
c) She needs to sell them.
Answers at bottom.
What Else Does It Mean?
mover
The word “mover,” in this podcast, means a person whose job is to help people pack their belongings, put them into a large truck, drive them to a new location, and then take them out of the truck and into the new building: “When the movers dropped the box, we could hear all the glasses breaking.” An “earth mover” is a large machine that moves soil and rocks: “The little boy loves watching earth movers at work.” The phrase “movers and shakers” is used to describe people who have a lot of power, money, and influence in society: “When Joanna received her promotion, she started spending a lot of time with other movers and shakers who were well-known in the city.”
to load
In this podcast, the verb “to load” means to put boxes or bags into a vehicle so they can be taken somewhere: “When you’re loading the truck, put the heaviest things at the bottom and the lightest things on top.” The verb “to load” can also mean to put bullets into a gun or to put film into a camera: “I need a new roll of film. Can you show me how to load it?” When talking about computer programs, the verb “to load” means for a program to start: “Sometimes it takes a long time for the program to load on this computer, because there isn’t enough memory.” Finally, the phrase “to be loaded down with (something)” means to have too much work or too many problems: “Ever since Michel took the new job, he has felt loaded down with too much work.”
Culture Note
Using the services of a moving company can make a move less “stressful” (causing anxiety and worry), but it’s important to hire a good, “reliable” (something one can depend on) moving company. People need to know that their goods will arrive at their new home “on time” (as scheduled; before the deadline) and in good condition.
Fortunately, there are many moving companies to choose among. When “selecting” (choosing) one, first ask to see the company’s “license,” or official permission to operate as a moving company in a particular city or state. Also, ask for proof of the moving company’s “insurance,” or a policy that will pay money if the moving company makes a mistake and damages or “misplaces” (loses) one’s belongings. A moving company should also have “liability insurance,” which would pay money if someone gets hurt while moving one’s belongings.
It’s also a good idea to ask for a list of the moving company’s “recent” (not long ago) customers with “contact information” (addresses, phone numbers, email addresses, etc.). Then you can “check references,” calling the company’s past customers and asking them about their experience with the moving company, as well as whether they would “recommend” (tell someone else to use or do something) the company’s services.
Finally, it is important to call the “Better Business Bureau” and find out whether anyone has “filed” (submitted) “complaints” (written or spoken reports of problems) about their experience with the moving company.
Then, once you have a list of moving companies that seem good and reliable, you can base your selection on price and “availability” (when something can be used).
Comprehension Answers
1 - c
2 - b