= 0647
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 647: Using a Smartphone.
This is English as a Second Language Podcast episode 647. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you the complete transcript of this episode, as well as cultural notes, vocabulary, definitions, sample sentences – well, just about everything you want in a Learning Guide!
This dialogue is between Hitomi and Jason. They’re talking about using a smartphone. Let’s get started.
[start of dialogue]
Hitomi: What are you unboxing?
Jason: This is my new smartphone. It has every feature under the sun!
Hitomi: Every feature?
Jason: It has a high quality camera and video camera, and it’s a videophone. It has a great GPS program, too. The touch-screen and the keyboard are easy to use and everything is so intuitive. Even a child could use it.
Hitomi: Yeah, but a child couldn’t afford the expensive price tag, right?
Jason: True enough, but it has a removable SIM card and is Bluetooth compatible. I can even use it as an e-book reader, and download apps for just about anything I want to do. No child’s toy could do all of those things.
Hitomi: Yes, that’s true, but I have just one question.
Jason: What?
Hitomi: Can you make a telephone call on it?
Jason: A telephone call? You mean a regular phone call? Yes, I think so.
[end of dialogue]
Hitomi begins by asking Jason, “What are you unboxing?” “To unbox” (unbox) is to take something that you bought out of the box that it came in, to open something that is brand new. This verb is relatively new, I think. It became popular when people started filming the unboxing and putting the video on YouTube, so you could see what was like to buy a new iPhone or to buy a new Android phone, whatever the thing that you were buying.
Well, Jason is unboxing his new smartphone. The term “smartphone” (one word) is a cell phone – a mobile or cellular phone – that can also do email, usually has an Internet connection, and often other things as well. The Android is an example of a smartphone; Blackberry makes a number of smartphones. The most popular smartphone, or least the most well known, is probably the iPhone by Apple. All of these are smartphones.
Jason says that his smartphone has every feature under the sun. A “feature” is a characteristic, something special about that product. Our Learning Guides have several features: vocabulary, definitions, sample sentences. All of those are things that are special, that are included. Software, a new car, a television – just about anything can have different features – different characteristics. This smartphone has every feature under the sun. To say that it “has every (something) under the sun” means it has many different types of that thing; in this case, it has many different features.
So, Jason thinks his smartphone has every feature under the sun, all of those that you could possibly want. Hitomi says, “Every feature?” Jason says, “It has a high quality camera and video camera.” A “camera” is a device that you use, a machine, that takes pictures – that takes photographs. There are many different, however, uses of that word “camera.” Take a look at the Learning Guide for some more of those. One use is a “video camera,” this is a camera that records video, obviously. Jason says that his smartphone is also a videophone. A “videophone” is a telephone that allows you to see the person that you are calling. That is something that, for example, you can do, I know, on the iPhone with other people who have iPhones. That’s a videophone. Jason says his phone also has a great GPS program. “GPS” stands for global positioning system. It’s a technology that allows you to use typically a satellite to know exactly where you are, and you can look at a map and see where you are. Many cars nowadays have a GPS system in them that will help you find your way to wherever you’re going. This is especially useful if you are in a place that you are not familiar with. Jason says that the phone has a touch-screen and keyboard that are easy to use. A “touch-screen” is a flat panel of an electronic device that can tell – that senses when you touch it, and allows you to do different things. Again, many of the Android phones and the iPhone allow you to use your finger to move something from one side of the screen to the other for example, or to “tap” on the screen, to place your finger quickly once or twice on the screen in order to perform some action. A “keyboard” is what you use for typing – what you use for putting letters, numbers, punctuation. It’s what you use on your computer all the time. I should also mention that “touch” can be used in a number of different ways, and those can be found in our Learning Guide as well.
Jason says that the touch-screen and keyboard are easy to use and everything is so intuitive. When we say something is “intuitive” (intuitive) we mean it’s very easy for you to understand; you can make sense of it even though you may not have used it before. Usually when we say “intuitive,” we mean that it is similar to something else that we do know how to use. Jason says it is so easy, it is so intuitive to use even a child could use it. Hitomi says, “Yeah, but a child couldn’t afford the expensive price tag, right?” “To afford” means to have enough money. The “price tag” (tag) is how much something costs. Often when you go into a store, you are looking at for example a new chair or some other object, you look for the price tag. You look for the little piece of paper that says how much it costs. It can sometimes be used to mean more generally the price. “So, what’s the price tag on that new car?” You’re not talking about the actual piece of paper – which would probably be called the sticker price, anyway, for a car – you’re talking about what the price is.
Hitomi says that a child would not have enough money – couldn’t afford the expensive price tag of the smartphone. Jason says, “True enough.” We use this phrase “true enough” to show that you agree with what another person has said. Often you are agreeing with some sort of perhaps critical or negative comment, although not always. Jason says, “True enough, but it has a removable SIM card and is Bluetooth compatible.” A “SIM (SIM) card” is a subscriber identity module card. Basically it’s the small card that has your electronic information that you put into a phone to use it. Many phones have SIM cards you can remove and put in a different phone, and sometimes people who travel to different countries are getting different SIM cards to use in their phone. “Bluetooth” is a technology that allows two electronic devices to communicate, to send signals from one to the other. Bluetooth is a technology that only works for small distances. For example, I have a Bluetooth mouse and a Bluetooth keyboard for my computer. There are no wires that connect the keyboard to the computer; it is wireless – without wires – because it is a Bluetooth keyboard. And we take the keyboard, and we – we use the verb “pair it” with the computer. Bluetooth devices are paired to each other; they’re connected. “To be compatible” means that it can use that thing. So, Bluetooth compatible is a phone that can be used with Bluetooth microphones or Bluetooth keyboards, etc.
Jason says, “I can even use (my smartphone) as an e-book reader, and download apps for just about anything I want to do.” “E-book” stands for electronic book; an “E-book reader” is a small portable electronic device that you can use to read text – to read books, magazines, newspapers, blogs, that sort of thing. There are lots e-book of readers out there. The Kindle by Amazon is a popular one. Now, the iPad by Apple also has an e-book reader on it. An “app” (app) is an application; it’s a software program that you use, in this case on your smartphone, that allows you to do different things. There are apps for many, many different functions. There are ones that you can play games on; there are apps that you can use as a map; there are apps that allow you to translate from one language to another; apps that have the entire dictionary on them. So, lots of things you can do with apps.
Jason says, “No child’s toy could do all of those things.” Hitomi says, “Yes, that’s true, but I have just one question.” Jason says, “What?” Hitomi says, “Can you make a telephone call on it?” Jason says, “A telephone call? You mean a regular phone call? Yes, I think so.” He’s not sure. Of course, we think of cell phones first as being phones, and second as being these other things. But Jason is so excited about the things that his smartphone can do he doesn’t even talk about the fact that it is also a regular phone.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Hitomi: What are you unboxing?
Jason: This is my new smartphone. It has every feature under the sun!
Hitomi: Every feature?
Jason: It has a high quality camera and video camera, and it’s a videophone. It has a great GPS program, too. The touch-screen and the keyboard are easy to use and everything is so intuitive. Even a child could use it.
Hitomi: Yeah, but a child couldn’t afford the expensive price tag, right?
Jason: True enough, but it has a removable SIM card and is Bluetooth compatible. I can even use it as an e-book reader, and download apps for just about anything I want to do. No child’s toy could do all of those things.
Hitomi: Yes, that’s true, but I have just one question.
Jason: What?
Hitomi: Can you make a telephone call on it?
Jason: A telephone call? You mean a regular phone call? Yes, I think so.
[end of dialogue]
We have scripts on almost every topic under the sun, brought to you by our own Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
to unbox – to take something out of its box for the first time; to open a new product
* When you unbox the microwave, be sure to save the packaging so we can reuse it when we move.
smartphone – a cell phone that can access email and other information on the Internet
* If we had a smartphone, we wouldn’t need to stop to ask for directions while driving.
every (something) under the sun – having many different types of something; having a lot of something or all of something
* This kitchen has every upgrade under the sun: stainless steel appliances, granite countertops, an eight-burner gas stove, and more!
feature – characteristic; something special that a product offers
* This printer has a lot of features, including high-speed printing, wireless connections, and a built-in fax machine.
camera – a device used to take photographs
* Do you need to buy film for your camera, or is it a digital camera?
video camera – a device used to record videos
* They bring their video camera to all their kids’ sports games and dance recitals.
videophone – a telephone that has a small screen that allows the callers to see each other while they are speaking
* Sharon uses a videophone when she calls her grandchildren so that she can see how much they are growing and changing even though she lives far away.
GPS – global positioning system; technology that uses satellites to know exactly where a device or person is at all times
* When they got lost in the woods, they were able to use the GPS on their cell phone to find the way back home.
touch-screen – a flat panel on an electronic device that can sense where one touches it, allowing the user to select things on the screen with one’s finger
* This is a touch-screen map, so if you want to zoom closer, just touch the part you’re interested in with your finger.
keyboard – small keys marked with numbers, letters, and punctuation, used to enter information into a computer or other electronic device
* Are you able to touch-type, or do you have to look at the keyboard?
intuitive – easy to understand; making sense to a person so that one does not need to read the instructions in order to use or do something
* Graphic computer programs that use icons are more intuitive than computer programs where the user has to type commands in a programming language.
price tag – the sales price; how much something costs
* We dreamed of buying a new home until we started looking at the price tags and realized we didn’t have enough savings.
true enough – a phrase used to show that one agrees with what another person has said
* - This special milk is too expensive!
* - True enough, but it’s better for your health.
SIM card – a subscriber identity module card; a small card that contains electronic information used for a telephone
* If you store all your friends’ phone numbers on a SIM card, you can just use that same SIM card when you get a new phone, and you won’t have to enter all the numbers again.
Bluetooth compatible – able to work with the technology that allows devices to communicate with each other without wires, especially when referring to cell phones, headsets, and car radios
* This car is Bluetooth compatible, so when your cell phone rings, a voice on your car’s radio will announce who is calling you.
e-book reader – a small, portable electronic device that can download the text of books or newspapers from the Internet and display it on a screen
* This e-book reader is great, because it’s easier to carry than a big, heavy novel, but sometimes I miss the feeling of holding an actual book in my hands.
app – application; a program that can be installed on a smartphone or other electronic device to make it do something else
* Our bank offers an app that lets customers check their account balance and pay bills on a smartphone.
Comprehension Questions
1. What does Jason mean when he says, “it has every feature under the sun”?
a) The smartphone is solar-powered.
b) You can see the smartphone’s screen in full sunshine.
c) The smartphone does a lot of different things.
2. Which smartphone feature could help you if you got lost?
a) A video camera.
b) A GPS program.
c) A SIM card.
Answers at bottom.
What Else Does It Mean?
camera
The word “camera,” in this podcast, means a device used to take photographs: “Don’t forget to bring your camera when you go on vacation.” A person who is “camera-shy” is someone who doesn’t like to be in photographs, so he or she hides from the camera: “Please don’t be camera-shy. Your grandmother really enjoys seeing pictures of you.” The phrase “on camera” means while a video was being recorded: “The police watched tapes of the man stealing stereos on camera.” The phrase “off camera” means without being recorded by a video camera: “They say their dog can bark ‘I love you,’ but that it only ever happens off camera, so they can’t prove it.” Finally, when talking about printing and graphic design, “camera-ready” describes a document that is ready to be printed: “This is a camera-ready version, so please don’t make any revisions unless they’re absolutely necessary.”
touch
In this podcast, a “touch-screen” is a flat panel on an electronic device that can sense where one touches it, allowing the user to select things on the screen with one’s finger: “Please tap the map on the touch-screen to indicate which state you’re in.” The phrase “in touch” means communicating with another person: “While they were physically apart, they stayed in touch with letters, emails, and phone calls.” The phrase “to lose touch” means to stop being aware of something, or to not have current, accurate information about something: “The politician promised to help the middle class, but after he won the election, he seemed to lose touch with their concerns.” Finally, the phrase “to put the finishing touches on (something)” means to do the final steps or to address the last details: “We just need to put the finishing touches around the windows and then we’ll be done painting.”
Culture Note
Whenever an American “consumer” (customer) makes a telephone call, “data” (information) about that call is added to the consumer proprietary network information (CPNI). All the “telecommunications companies” (companies that provide services for communication) keep track of when calls occur, which “parties” (people or organizations) participate in the call, and the “duration” (how long something lasts) of the call.
Telecommunications companies would like to use that information to “market” (increase sales through promotion) their services to consumers who might “benefit” (receive advantages) from them. Americans can choose to “opt in” (choose to participate in) or “opt out of” (choose not to participate in) programs where their CPNI data is used for marketing.
Although many people are uncomfortable with the idea that businesses and other individuals can have detailed information about all the phone calls they make, telecommunications companies need to have and “retain” (keep) the information so that they can “bill” (charge) consumers correctly.
The Telecommunications “Act” (Law) of 1996 “limits” (puts restrictions on) how the CPNI data can be shared. For example, telecommunications companies cannot share the data with “third parties” (other people or organizations) without the consumer’s “consent” (agreement).
When a consumer “requests” (asks for) information about his or her own calling history, the telecommunications company normally asks for the consumer’s password before sharing any data. This protects the consumer from having other people “pose as” (pretend to be) the person who made the calls.
Americans who think their calling information has been used “inappropriately” (in bad or wrong ways) can “file a complaint” (submit a statement that something is bad or wrong) with the government’s Federal Communications Commission.
Comprehension Answers
1 - c
2 - b