= 0649
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 649: Disliking a Sibling’s Boyfriend or Girlfriend.
This is English as a Second Language Podcast episode 649. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website – you know what it is – is eslpod.com. Go there to download a Learning Guide for this episode, which will help you improve your English – and your love life!
This episode is all about love and hate. It’s called “Disliking (or not liking) a Sibling’s (that is, brother or sister’s) Boyfriend or Girlfriend.” Let’s get started.
[start of dialogue]
Georgia: So I thought Carla was nice.
Andy: You did? I didn’t get that impression at all. I don’t know what Brian sees in her.
Georgia: Really? I thought she was really trying to make a good impression.
Andy: Yeah, she was trying too hard. She laughed too loudly at my jokes and complimented you too much on your cooking.
Georgia: Maybe she was a little too eager, but that just shows that she really likes our brother. What’s wrong with that?
Andy: Nothing is wrong with that, but did you see how clingy she was? She wouldn’t leave Brian’s side for a minute, spoke for him, and finished his sentences. I just found that really annoying.
Georgia: Brian didn’t seem to mind and that’s what really counts. Maybe he likes having an attentive girlfriend.
Andy: There’s attentive and there’s smothering. She just seemed really possessive, that’s all.
Georgia: Methinks the gentleman doth protest too much.
Andy: What do you mean by that?
Georgia: I think you might like Carla a little too much for your own good. Shame on you, being interested in your own brother’s girlfriend.
Andy: Are you crazy?! Didn’t I just tell you that I didn’t like her at all?
Georgia: Yes, but you said it with such passion!
[end of dialogue]
Georgia says to Andy, her brother, “So I thought Carla was nice.” Andy is surprised, he says, “You did? I didn’t get that impression at all.” “To get an impression” means to understand a situation in a particular way, usually different from the way someone else understood the situation. You and your friend could have a conversation with someone, and then later the two of you talk about that conversation and each of you had a very different view about what happened; you didn’t get the same impression. Andy says, “I don’t know what Brian sees in her.” When we talk about what someone “sees in” someone else, we mean what are the things that the one person likes about the other, what are the things that they are attracted to in the other person. Now, Brian is the brother of Andy and Georgia, and Brian’s girlfriend is named Carla. So, Andy doesn’t like Carla; he doesn’t see what Brian sees in her.
Georgia says, “Really? I thought she was really trying to make a good impression.” “To make a good impression” – that word again, “impression” – means to do or say things that will make another person like you, and will say and think good things about you. There’s an old expression: “You only have one chance to make a first impression.” That is, there’s only one opportunity for someone to meet you for the first time, logically, so you always want to present yourself well.
Georgia thought that Carla was trying to make a good impression. Andy says, “Yeah, she was trying too hard (too much). She laughed too loudly at my jokes (that is, she laughed more than she should have) and complimented you too much on your cooking.” “To compliment” (compliment) means to say something nice to make someone feel good about some action that they did. A husband should always compliment his wife on her beautiful face, on her hair, on her shoes – even if he doesn’t notice that they are new shoes that she just bought last weekend, and would have no way of knowing that they were new because he doesn’t normally look at her shoes for example!
Andy says that Carla is trying too hard. Georgia says, “Maybe she was a little too eager (eager).” “To be eager” means to be excited about something, really looking forward to doing something. “The students were eager to go to lunch.” They really wanted to eat and get out of the terrible math class they were in or something. Well, Georgia says that Carla was a little too eager, “but that just shows that she really likes our brother. What’s wrong with that?” Andy says, “Nothing is wrong with that (that’s okay), but did you see how clingy she was?” “Clingy” (clingy) means that a person depends on someone else too much; they want to spend all of their time with them. Sometimes when you get a new boyfriend or a new girlfriend one person wants to spend more time with the other – calling her day and night, wanting to be with her all the time – so that you might think the person is being clingy. They’re trying to be too close and too dependent on the other person. “Clingy” has a couple of different meanings in English, and those are found in the Learning Guide.
Andy says, “She (meaning Carla) wouldn’t leave Brian’s side for a minute.” “Brian’s side” meaning she wouldn’t leave Brian. She spoke for him, and she finished his sentences. “To speak for (someone)” is to answer questions that someone else is asking that person. So, someone will ask a question of Brian but Brian doesn’t respond; Carla gives the answer. That’s to speak for someone. You can also speak for someone in the sense that you have the authority to give someone else’s opinion about a topic who isn’t there. But in this case, it’s just Carla answering questions that people are asking Brian. She also finishes his sentences. This is when you are talking and before you finish your sentence the person you’re talking to, right in the middle, will interrupt you – will finish the sentence for you. That can be very annoying! Andy says, “I just found that really annoying,” meaning irritating, makes you sort of angry – a little angry.
Georgia does not agree; she says, “Brian didn’t seem to mind (meaning it didn’t bother him) and that’s what really counts (meaning that’s what’s really important).” “Count” has a couple of other meanings in English; you can find those, well, in the Learning Guide. Georgia says that maybe Brian likes to have an attentive girlfriend. Someone who is “attentive” pays attention to the other person, tries to do what that other person wants or needs.
Of course, Andy does not agree. He says, “There’s attentive and there’s smothering.” There are a couple of things here. “To smother” (smother) means to pay too much attention to someone, so that the person doesn’t feel they can be free. Literally, you can use the verb “to smother” to kill someone, usually by putting a piece of clothing in their face so they can’t breathe, or a pillow. If you ever read Shakespeare’s Othello, this is what happens to one of the main characters. If you haven’t, of course, I won’t tell you the rest of the story! Here, “smother” just means that the person doesn’t feel free, feels the other person is being too attentive. Andy says, “There’s attentive and there’s smothering.” This construction, “there’s (something) and there’s (something else),” is an informal way to show that two things are very different, that there is a big contrast between them. Andy says that Carla just seemed really possessive.” Someone who is “possessive” wants to have something and no one else can have it, no one else can share it.
Georgia thinks now that there is some other reason why Andy doesn’t like – or says he doesn’t like Carla. She then uses, speaking of Shakespeare, a famous line partially from Shakespeare, from the play Hamlet: “Methinks the gentleman doth protest too much.” “Methinks” is an old English way of saying “I think,” no one says that anymore. “Doth” is an old form of “does.” “To protest” means to argue against something. The original expression was “The lady doth protest too much, methinks,” but the more common usage is to put “methinks” first. “Methinks the (in this case) gentlemen (since Andy is a man) doth protest too much.” Well, what does this mean? It means that someone is denying something. They’re saying they don’t like something, but in fact they really do like someone or something. So, that you try to pretend that you don’t like this person or this thing when the reality is – when in fact you like that person very much but you don’t want anyone else to know about it.
Andy says, “What do you mean by that?” Georgia says, “I think you might like Carla a little too much for your own good.” The expression “too much for your own good” means that you have so much of something that it becomes a bad thing. If you like candy that’s great, but if you eat two pounds of candy a day, that’s too much for your own good. In this case, Georgia thinks that Andy really likes Carla, likes her in a romantic way. She says, “Shame on you, being interested in your own brother’s girlfriend.” The expression “shame on you,” or “shame on Andy,” is used to make someone feel bad about something they have said or done. “Shame on you for criticizing your grandmothers cooking.” You should never do that, shame on you!
Well, Georgia is saying shame on you, Andy, because she thinks Andy actually likes Carla and would like Carla to be, I guess, his girlfriend – assuming he doesn’t have a girlfriend. Of course, Andy denies this – doesn’t agree with Georgia. He says, “Are you crazy?! Didn’t I just tell you that I didn’t like her at all (not even a little bit)?” Georgia says, “Yes, but you said it with such passion (passion)!” “Passion” is a strong emotion, a strong feeling, a strong opinion often about a romantic interest. So, Georgia is saying yes, you said you don’t like her, but you said it in such a way that makes me think that you really do like her.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Georgia: So I thought Carla was nice.
Andy: You did? I didn’t get that impression at all. I don’t know what Brian sees in her.
Georgia: Really? I thought she was really trying to make a good impression.
Andy: Yeah, she was trying too hard. She laughed too loudly at my jokes and complimented you too much on your cooking.
Georgia: Maybe she was a little too eager, but that just shows that she really likes our brother. What’s wrong with that?
Andy: Nothing is wrong with that, but did you see how clingy she was? She wouldn’t leave Brian’s side for a minute, spoke for him, and finished his sentences. I just found that really annoying.
Georgia: Brian didn’t seem to mind and that’s what really counts. Maybe he likes having an attentive girlfriend.
Andy: There’s attentive and there’s smothering. She just seemed really possessive, that’s all.
Georgia: Methinks the gentleman doth protest too much.
Andy: What do you mean by that?
Georgia: I think you might like Carla a little too much for your own good. Shame on you, being interested in your own brother’s girlfriend.
Andy: Are you crazy?! Didn’t I just tell you that I didn’t like her at all?
Georgia: Yes, but you said it with such passion!
[end of dialogue]
We don’t compliment our scriptwriter enough here on ESL Podcast, so thank you Lucy Tse – Dr. Lucy Tse, for your wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on ESL Podcast.
Glossary
to get that impression – to understand or perceive something in a particular way, usually when contrasting one’s own understanding or perception with that of another person
* - This is going to be the best course ever!
* - Really? I didn’t get that impression. I think it’s going to be boring.
what (someone) sees in (someone) – the things that attract one person to another person; the things that one person admires or respects in another person
* What does Troy see in Hilda? She’s one of the rudest people I’ve ever met, but he seems to like her a lot.
to make a good impression – to do or say things that make another person like oneself and think good things about oneself
* During the interview, you can make a good impression by offering a firm handshake, sitting up straight, and looking into the interviewer’s eyes.
to compliment (someone) – to say something nice; to make someone feel good about a particular characteristic or action
* Shane was pleasantly surprised when a stranger on the bus complimented him on his haircut.
eager – excited and enthusiastic; ready to do something and looking forward to it
* We are really eager to see the new movie. We already have tickets for the first showing this weekend.
clingy – needing and depending on someone too much, trying to spend a lot of time with that person and touching him or her all the time
* Is it normal for a child to be so clingy, always holding onto her mother’s leg?
to speak for (someone) – to answer questions that are directed at another person, not giving that person time to answer the questions by himself or herself
* Why do you let your boss speak for you during the meetings? You need to learn to present your own ideas.
to finish (one’s) sentence – to interrupt another person in the middle of a sentence and say the rest of it for him or her
* Sean and Ryan are identical twins who always finish each other’s sentences.
annoying – irritating; making one feel uncomfortable and slightly angry
* It’s so annoying to hear people talking on their cell phones in restaurants!
to count – to be important; to matter; to be relevant
* Our good intentions don’t count if we don’t act on them.
attentive – paying attention to another person and trying to meet his or her needs
* All of the nurses in this small hospital are attentive and ready to do anything to make patients more comfortable.
there’s (something) and there’s (something) – an informal phrase used to show a strong contrast or difference between two things
* There’s pride and there’s arrogance. I don’t think Jim knows the difference.
to smother – to pay so much attention to someone that he or she feels unable to breathe or do things on their own
* Scott is embarrassed by the way his mother smothers him with kisses when she drops him off at school.
possessive – wanting to have or own something or someone, without sharing it with other people
* Don’t touch anything in her room! She’s really possessive and doesn’t like it when other people touch her things.
methinks the (lady/gentleman) doth protest too much – a phrase misquoted from Shakespeare’s play, Hamlet, meaning that someone is denying something, but that the denial actually shows that the thing is really true (the actual quote is “The lady doth protest too much, methinks.”)
* Nancy keeps saying she doesn’t want to go out with Patrick, but methinks the lady doth protest too much.
too (much of something) for (one’s) own good – so much of something that it becomes a bad thing and creates problems for someone
* You’re too nice for your own good, saying ‘yes’ to anyone who asks you for a favor. Other people are starting to take advantage of you.
shame on (someone) – a phrase used to make someone feel bad about something he or she has said or done
* Shame on you! What you said really hurt his feelings.
passion – strong feelings, opinions, and/or emotions
* Trent and his wife share a passion for good food and wine.
Comprehension Questions
1. Why does Andy say, “I don’t know what Brian sees in her”?
a) He doesn’t understand what Brian likes about her.
b) He doesn’t understand why Brian thinks she’s pretty.
c) He doesn’t understand how Brian can know her feelings.
2. What did Carla say about Georgia’s cooking?
a) She said she had never tasted food like that before.
b) She said it was very good food.
c) She said it was the same type of food served in restaurants.
Answers at bottom.
What Else Does It Mean?
clingy
The word “clingy,” in this podcast, means needing and depending on someone too much, trying to spend a lot of time with that person and touching him or her all the time: “In the days immediately after the earthquake, Wanda was more clingy than usual, probably because she was scared.” If clothing is “clingy,” it stays very close to one’s body, revealing its shape: “You’d have to have a perfect body to wear such a clingy dress.” Finally, the phrase “to cling to (something)” means to continue to believe or have something even though it is no longer helpful, useful, or true: “Even though there’s no scientific proof, many people cling to the belief that there is life on other planets.”
to count
In this podcast, the verb “to count” means to be important and relevant, or to matter: “Your first kiss doesn’t count if it was with a relative.” The phrase “to count (one’s) blessings” is used to tell someone to be grateful for the things he or she has: “You have a house, a loving wife, and three beautiful children. You should count your blessings and stop complaining about unimportant things.” The phrase “to count sheep” refers to the practice of trying to fall asleep by imagining sheep jumping over a fence and counting them: “She has tried drinking warm milk, taking sleeping pills, and counting sheep, but she still isn’t able to fall asleep at night.” Finally, the phrase “to count on (someone or something)” means to rely or depend on someone or something: “Don’t worry about it. You can count on me!”
Culture Note
In the United States, “siblings” (brothers and sisters) are expected to love each other, but also to fight with each other and have many arguments. This isn’t necessarily because they don’t like each other. Most researchers agree that sibling rivalries “arise” (appear; happen) because siblings are competing for their parents’ attention and love.
American literature, television, and movies “are filled with” (have many) “sibling rivalries” (tense relationships between brothers and sisters). For example, one popular television show, The Simpsons, is often about the sibling rivalry between Bart and Lisa. Episodes of Malcolm in the Middle and Rugrats are also often about sibling rivalry. And episodes of The Brady Bunch are often about sibling rivalry among the “step-siblings” (brothers and sisters who are in the same family because their parents remarried after their birth).
Most people “grow out of” (are no longer interested in something as adults) their sibling rivalries by the time they are adults, often developing close relationships with their siblings. But some television shows explore sibling rivalries that continue even when the siblings are adults, such as Ross and Monica in Friends, and Frasier and Niles in Frasier. In these shows, the characters “appear” (seem) “quite” (very) childish when they are involved in sibling rivalries, but it is funny.
Some “real-life” (happening to real people; not made up for TV or movies) sibling rivalries are talked about in the media, especially in sports and entertainment. For example, there are tennis stars Venus and Serena Williams, musicians Michael and Janet Jackson, and musicians and actresses Britney and Jamie Lynn Spears. It is possible that having media attention “exacerbates” (makes stronger or worse) these sibling rivalries.
Comprehension Answers
1 - a
2 - b