= 0278
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 278: Meeting the Future In-laws.
This is English as a Second Language Podcast episode 278. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com, and download a Learning Guide for this episode.
This episode is called “Meeting the Future In-laws.” Your “in-laws” are the relatives of your wife or husband. Let's get started.
[start of story]
Atsushi: I don’t mind telling you that I’m really nervous about meeting your parents.
Scarlet: You look like you’re about to face the firing squad. It’s not going to be that bad.
Atsushi: I wish I could believe that. I’m going to try to make a good first impression, but I don’t think they’re going to like the fact that I’m a professional musician.
Scarlet: I’ve already told them about you, so there won’t be any surprises.
Atsushi: It doesn’t help that your last boyfriend was a straight-laced college student. Couldn’t you have dated a convict before me? I’d look pretty good to your parents in comparison.
Scarlet: How do you know I didn’t? You don’t know everything about me.
Atsushi: Very funny. Maybe we should postpone this visit with your parents for a little while.
Scarlet: No!
Atsushi: I’m just putting it out there.
Scarlet: We’ve put off this visit for months and my parents are really starting to wonder if you really exist. Let’s not blow this visit out of proportion. They’re only my parents.
Atsushi: I know, but they may also be my in-laws soon.
Scarlet: I know, but it’s not like our whole relationship is riding on this visit. I’ll still like you no matter what. And plus, my parents know that I have good taste in men.
Atsushi: At least I know that’s true!
[end of story]
This dialogue between Atsushi and Scarlet is about the in-laws. Your “in-laws” (in-laws) are the mother, father, brothers, and sisters of your spouse – of the person you are marrying, so your husband or your wife. The term “in-laws” can be used for all of these relatives. You can say, “my father in-law,” “my mother in-law,” “my brother in-law,” “my sister in-law”; all of those are possible.
In the dialogue, Atsushi begins by saying that “I don't mind telling you that I’m really nervous about meeting your parents.” Atsushi and Scarlet are obviously going to be married, and Atsushi begins with a common phrase to mean “I want to tell you,” or, “I'm not embarrassed to tell you this.” That's the meaning of the expression “I don't mind telling you.” Atsushi is nervous about meeting Scarlet's parents. “Nervous” means anxious, worried, perhaps scared of something.
Scarlet says, “You look like you’re going to face the firing squad” (squad). “To face (face) the firing squad” means to be in a very difficult or dangerous situation. Literally, the expression refers to a group of people with guns, usually working for the government perhaps, or the Army, and they get together in a small group – a squad is a small group – and are supposed to kill one of the people – one of the people, perhaps, who is a prisoner in a war. There's a famous painting by the Spanish painter Goya about a firing squad, a group of men, who have guns and they are going to all shoot their guns to kill this prisoner – this person. That's what a “firing squad” is. “To face something” means to go in front of something or to confront something – to have to deal with something. Scarlet says Atsushi looks like he's about to face the firing squad – to be put in a very dangerous situation. Scarlet says, “It's not going to be that bad,” meaning it's not going to be as bad as you think.
Atsushi says, “I wish I could believe that. I’m going to try to make a good first impression, but I don’t think they” – your parents – “are going to like the fact that I’m a professional musician.” Atsushi wants to make a good first impression. The “first impression” is the way that you feel about or what you think about someone the first time you meet them. For additional explanations of that expression, “first impression,” take a look at the Learning Guide for today.
Atsushi is a “musician,” someone who plays or writes music professionally, meaning he gets paid for it, that's what his job is. Someone says, “I'm a professional musician,” they mean “I get paid to be a musician.” You could be a professional dancer. You could be a professional baseball player, You could be a professional podcaster!
Scarlet says that she has already told her parents about Atsushi and that he is a musician, “so won't will be any surprises” – the parents already know that he's a musician. Musicians sometimes have the reputation of being not very reliable, someone that you don't want your daughter to marry. That's kind of a joke about musicians, in part, or partly because it is difficult to get work as a professional musician. I have been trying to get work as a professional singer for many years, and I have not been very successful. I don't know why!
Atsushi says that “It doesn’t help that your last boyfriend was a straight-laced college student.” The adjective “straight (straight) -laced (laced)” means someone who is very traditional or conservative – someone who doesn't do anything very risky; someone who is very safe, we would say they were “straight-laced.” Scarlet's other boyfriend was a “straight-laced,” or conservative, college student.
Atsushi says, “Couldn’t you have dated a convict before me? I’d look pretty good to your parents in comparison.” Atsushi is making a joke here. A “convict” (convict) is someone who has been arrested and put in prison – a criminal, someone who has done something against the law. Atsushi is saying that Scarlet should have dated someone with a worse reputation than a musician and then he would look good by comparison, or in comparison to someone else. “In comparison,” or “by comparison,” means compared to something else.
Scarlet says, “How do you know I didn’t?” Again, she's joking; she means “how do you know I didn't date a convict, you don't know everything about me.” Atsushi says, “Very funny.” When you think someone is making a joke but you don't think it's funny, you say, “Oh, very funny,” meaning “I don't think that's very funny.” It's a strange way of saying that, but that's the way we use that expression usually.
Atsushi says, “Maybe we should postpone this visit with your parents for a little while.” “To postpone” (postpone) means to delay – to decide to do something at a later time.
Scarlet says, “No!”
Atsushi says, 'I’m just putting it out there.” The expression “to put something out there” means to present an idea for consideration by other people – to ask people to think about something. It's a suggestion; it's an idea that you would bring to someone and say, “Think about this.”
Atsushi wants to postpone the visit to Scarlet's parents, and Scarlet says, “No.” Scarlet says, “We’ve put off this visit for months.” “To put off something,” or, “to put something off,” means to delay something. It's the same as to postpone.
She says, “My parents are really starting to wonder if you really exist,” meaning if you're real – if you are alive. “Let’s not blow this visit out of proportion.” “To blow something out of proportion” means to make it more important or more dramatic than it really is – to believe that it is more important than it really is.
Atsushi says, “I know, but they” – the parents of Scarlet – “may also be my in-laws soon,” meaning the two of them could be getting married.
Scarlet says, “I know, but it’s not like our whole relationship is riding on this visit.” “To ride (ride) on something” means to depend on something – that everything is depending on this thing. Scarlet says, “I’ll still like you no matter what.” “No matter what” means regardless, without giving importance to anything else. It doesn't matter – “no matter what.”
Scarlet ends by saying, “my parents know that I have good taste in men.” “To have good taste (taste) in something” means to be very good at identifying the good things from the bad things – to be at choosing something. You could have good taste in shoes or good taste in cars – you pick the best, you know what's good. Good taste in podcasts, for example, would mean listening to ESL Podcast, of course!
Now let's listen to the dialogue, this time at a normal speed.
[start of story]
Atsushi: I don’t mind telling you that I’m really nervous about meeting your parents.
Scarlet: You look like you’re going to face the firing squad. It’s not going to be that bad.
Atsushi: I wish I could believe that. I’m going to try to make a good first impression, but I don’t think they’re going to like the fact that I’m a professional musician.
Scarlet: I’ve already told them about you, so there won’t be any surprises.
Atsushi: It doesn’t help that your last boyfriend was a straight-laced college student. Couldn’t you have dated a convict before me? I’d look pretty good to your parents in comparison.
Scarlet: How do you know I didn’t? You don’t know everything about me.
Atsushi: Very funny. Maybe we should postpone this visit with your parents for a little while.
Scarlet: No!
Atsushi: I’m just putting it out there.
Scarlet: We’ve put off this visit for months and my parents are really starting to wonder if you really exist. Let’s not blow this visit out of proportion. They’re only my parents.
Atsushi: I know, but they may also be my in-laws soon.
Scarlet: I know, but it’s not like our whole relationship is riding on this visit. I’ll still like you no matter what. And plus, my parents know I have good taste in men.
Atsushi: At least I know that’s true!
[end of story]
The script for today's podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
I don’t mind telling you… – a phrase used to mean “I want to tell you …” or “I’m not embarrassed or frightened to tell you…”
* We’ve always told each other our secrets, so I don’t mind telling you about the embarrassing thing that happened to me last weekend.
nervous – anxious; worried or scared about what is going to happen
* Most people get very nervous when they have to make a presentation in front of their coworkers.
to face the firing squad – to enter a very difficult and/or dangerous situation; to stand in front of a group of soldiers who are going to shoot one for having committed a crime
* Antonio felt like he was facing the firing squad when he had to tell his employees that the factory was closing and they were going to lose their jobs.
first impression – the way that one feels about someone the first time that one meets him or her
* My first impression of Jewel was that she was very shy, but now I know that she’s only like that when she first meets someone.
musician – a person who writes or makes music
* Everyone in this band – the singer, pianist, drummer, and guitar player – have been musicians most of their lives.
straight-laced – conservative; having traditional and strict beliefs about how people should behave; not doing anything risky or unacceptable
* Mandy has never been to a party, stayed out past 10:30, or drank alcohol. She is the most straight-laced person I know!
convict – a criminal; a person who committed a crime and was or is in prison
* Everyone was scared when they heard that a convict had escaped from prison.
in comparison – compared to something else; looking at the similarities and differences between two people or things
* In comparison with California, Oregon is a rainy, cold state, but in comparison with Washington, Oregon is warm and sunny.
to postpone – to delay; to decide to do something later than originally planned
* The meeting has been postponed until next Thursday because the director had to travel unexpectedly.
to put (something) out there – to present an idea for consideration by other people; to ask other people to think about something
* I don’t think Josh meant that he didn’t like your report. He was just putting the idea out there that the report might be better if it had more detailed information.
to put (something) off – to delay; to postpone; to plan to do something later
* If you put off doing your homework until the day before it’s due, you’ll have to stay awake all night to finish it.
exist – to be alive or real; to not be part of one’s imagination
* Do you think that life exists on other planets?
to blow (something) out of proportion – to believe or act as if something is much more important than it actually is
* Dasha got into a small car accident and her parents blew it out of proportion, deciding that she shouldn’t drive again until she graduates from college.
in-law – the mother, father, brother, or sister of one’s husband or wife
* Vanessa likes her mother-in-law, but she and her sister-in-law aren’t very good friends.
to ride on (something) – to depend on something
* They plan to have an outdoor wedding, so they’re riding on having good weather.
no matter what – regardless; without giving importance to anything else
* No matter what Janice says about your chances, you should try out for the team. You’re a great player and I think you’ll make it.
to have good taste in (something) – to be very good at identifying the good among the bad; to be good at choosing something
* Patricia has very good taste in clothing and she is always dressed professionally.
Comprehension Questions
1. Why is Atsushi nervous about meeting Scarlet’s parents?
a) Because he is straight-laced.
b) Because he’s a musician.
c) Because he is a convict
2. Why doesn’t Scarlet want to postpone the visit again?
a) Because she wants her parents to meet her boyfriend.
b) Because her parents will blow it out of proportion.
c) Because the relationship is riding on this visit.
Answers at bottom.
What Else Does It Mean?
impression
The phrase “first impression,” in this podcast, means the way that one feels about someone the first time that one meets him or her: “It’s important to make a good first impression during a job interview.” In general, an “impression” is the way that something seems to you: “I have the impression that it is very difficult for English speakers to learn Japanese.” The verb “to impress” means to make one like or admire something or someone: “Many men try to impress women by driving expensive cars.” The phrase “to be impressed by (something)” means to have a positive opinion about something: “I was impressed by Dr. Chomsky’s presentation.” If someone is “impressionable,” it means that someone is easily influenced to think a certain way: “Young children are too impressionable to watch movies with lots of violence.”
convict
In this podcast, the word “convict” means a person who has committed a crime and was or is in prison: “The dangerous convicts are allowed to have visitors only once a week, speaking through a glass window.” As a verb, “to convict (someone)” means to officially decide that someone has committed a crime: “Today the court will decide whether or not to convict Paul for the murder.” A “conviction” is the decision that someone has committed a crime: “To apply for this job, you must list any past convictions.” A “conviction” is also a very strong belief or opinion, especially a religious belief: “Mormons do not drink alcohol because of their religious convictions.” Or, “He has a sincere conviction that there is life on Mars.”
Culture Note
In many countries, multiple “generations” (people who are the same age in a family, such as children, parents, and grandparents) often live together in one home. In the United States, this is unusual and most grandparents do not live with their children and grandchildren. When they become “elderly” (old), their children often need to consider their “options” (choices) for taking care of their elderly parents.
One option for taking care of elderly parents is “assisted living.” “Assisted living” lets the elderly parent live in his or her home, but a nurse or a “caregiver” (a person whose job is to take care of another person) may live with him or her, or visit regularly. “Assisted living” is good for elderly parents who have “minor” (not very serious) health problems and want their “independence” (the ability to live alone, without very much help from other people).
Elderly people who have serious health problems may need to live in a “nursing home.” A “nursing home” is a building where many elderly people live. Each person has a bedroom and bathroom, but the living room and dining room are shared. Meals are cooked for the “residents” (the people who live in a place) and nurses and/or doctors are available.
Finally, some families choose to have a “mother-in-law unit” in their homes. This means that part of the house is “set aside” (used for a special purpose) for the elderly parent. A mother-in-law unit has a separate bedroom, bathroom, living room, and kitchen so that the elderly parent and the family are independent, but they live close to each other and can spend time together. However, most homes in the U.S. do not have a mother-in-law unit and it can be expensive to build one.
Comprehension Answers
1 - b
2 - a