= 0298
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 298: Visiting a Museum.
This is English as a Second Language Podcast episode 298. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com. You can download a Learning Guide for this episode that contains all of the vocabulary, definitions, sample sentences, additional definitions not found on the podcast, cultural notes, and a complete transcript.
This episode is called “Visiting a Museum,” and we’re going to follow Rudy as he goes to a museum, asks some questions of the guard that is working there. Let’s get started.
[start of story]
I wanted to visit the National Museum, but when I arrived, it was closed.
Rudy: Can you tell me the hours of operation for the Museum?
Guard: It’s open from 10 a.m. to 5 p.m., Monday through Saturday. It’s closed on Sunday.
Rudy: Thanks. I’ll be back tomorrow.
---------
The next day, I arrived at the Museum at 10 a.m. and the same guard was there.
Rudy: Hello, again. Can you tell me if the Museum has any tours?
Guard: The Museum has a self-guided tour. You can get information at the ticket window.
Rudy: Oh, thanks. Do you know if I can use my flash to take photos in the Museum?
Guard: You can take pictures, but flash photography is prohibited. Food and drinks are prohibited, too.
Rudy: Oh, I guess I need to get rid of this bottle of juice before I go in. Do you know if all of the exhibits are open to the public today?
Guard: The east wing is under construction, but the rest of the galleries are open. The sculpture and painting galleries are to your left, and the artifacts are to your right.
Rudy: Thanks a lot. How much is the admission charge?
Guard: It’s $10.00 for adults, $3.00 for children, and $5.00 for seniors and students with picture ID. The people at the ticket window can help you with that.
Rudy: Thanks. Just one more question.
Guard: Yes?
Rudy: If I leave after I pay, can I come back in?
Guard: Yes. You just have to show your stub. Anything else?
Rudy: Oh, no. Thanks a lot. Sorry to have bothered you.
Guard: No trouble at all.
[end of story]
Our dialogue, in this episode, covers some basic vocabulary you would need if you were going to visit a museum. Here in Los Angeles, we have a couple of good museums. We have the Los Angeles County Museum of Art; we also have two museums called “Getty”: the Getty Center and the Getty Villa. Of course, there are also great museums in New York and in Washington, D.C., in Boston – several cities have very nice museums.
This episode begins with Rudy saying that he “wanted to visit the National Museum.” That's not a real museum; here in the U.S., the national museum is the Smithsonian Museum, and that's what we would call it, in Washington, D.C. Actually, there are several museums there.
Rudy goes to the museum, but when he gets there (when he arrives) it is closed. So, he asks the "guard," or the security guard (the person who is like a police officer who is protecting the museum), Rudy asks the guard, “Can you tell me the hours of operation for the Museum?” The expression “hours of operation” means the time that the building is open to the public; we call them the “hours of operation.” For example, a bank's hours of operation are usually Monday through Friday, 9:00 in the morning to 5:30 in the afternoon.
The guard says that the museum is “open from 10 a.m. to 5 p.m., Monday through Saturday. It’s closed on Sunday.” This would be somewhat unusual; museums are normally open on Sunday. Some museums are open seven days a week; other museums are closed one day.
Rudy says, “I’ll be back tomorrow.” So, he goes back the next day and sees the same guard there, and says to the guard, “Can you tell me if the Museum has any tours?” (where they take you around and explain different parts of the museum).
The guard says, “The Museum has a self-guided tour.” A “self-guided tour” is when you don't have a “guide” (a person who goes with you and explains things). They usually give you either a piece of paper that explains things, or, now, you can get audio receivers. They are kind of like iPods that you walk around with, and when you come in front of a piece of art you will hear an explanation through your headphones. The guard says that “You can get information (about the self-guided tours) at the ticket window.”
Rudy says, “Oh, thanks. Do you know if I can use my flash to take photos in the Museum?” The “flash” is what is on a camera that produces a very bright light; in case it is dark, the light will make a better picture for you. “Flash” has a couple of different meanings; take a look at our Learning Guide for some additional explanations.
The guard says, “You can take pictures, but flash photography is prohibited.” “Prohibited” means not allowed, against the rules. You could also say “forbidden.” So, like in most museums, you can't use a camera with flash; there are some museums where you can't use a camera at all. The guard says, “Food and drinks are prohibited, too.” Again, that's pretty typical of a museum.
Rudy says, “Oh, I guess I need to get rid of this bottle of juice.” To “get rid (rid) of” something means to throw it away, to do something so that you no longer have it with you. Usually it means throwing it away. Rudy says I have “to get rid of this bottle of juice before I go in.”
He then asks another question of the guard: “Do you know if all of the exhibits are open to the public today?” An “exhibit” is, in a museum, a group of objects that are similar. Usually museums have different exhibits – different themes, different topics, perhaps even different time periods. Sometimes they have special exhibits; these are usually pieces of art from other museums. Rudy asks if “the exhibits are open to the public,” meaning anyone can visit; you don't need any special permission.
The guard says, “The east wing is under construction, but the rest of the galleries are open.” The “wing” of a building is one section or one part of a building. The White House in Washington, D.C., where the president of the United States lives, is divided into an east wing and a west wing. In fact, there was a famous TV show called The West Wing that refers to that side of the White House – that side of the building. There are other meanings of this word, “wing,” take a look at our Learning Guide for some additional explanations.
The guard says, “The east wing is under construction,” meaning they're doing work on it. It's not finished yet; they're still building or changing it. The guard says, “the rest of the galleries are open.” The “rest of the galleries” are the other rooms in the building. A “gallery” is just a name of a large room in a museum. We also use this same word, “gallery,” to talk about a place were you can go and buy art; these are called “art galleries.” That's different; that's more like a store where you can go look at and buy pieces of art. In a museum, a gallery is simply a room of the museum, or a collection of rooms.
The guard continues by saying that “The sculpture and painting galleries are to your left, and the artifacts are to your right.” “Sculpture” is a solid object of art, usually made from stone such as marble, or metal, possibly wood, or even clay. These are all possible materials for sculpture. Michelangelo’s famous sculpture is of David, in Florence, Italy; that's an example of a piece of sculpture. Notice that when we are talking about one work of art – one sculpture – we say, typically, “a piece of sculpture.” We use the same for art: “a piece of art.”
“Painting” is, of course, when you have colors, either what we would call “oil-based” or “water-based” colors (different kinds of paint) that you put on a piece of (again, typically) white fabric (a white material): we call that a “canvas” (canvas). A painter paints on a “canvas,” that's the white piece of material that they use to paint their painting (their picture). We don't say “a piece of painting,” however; we just say “a painting.” “Artifacts” (artifacts) are things that were made by humans many years ago that were not necessarily meant to be pieces of art, but are now put in museums so that you can look at them, and some people consider them pieces of art.
Rudy then asks the guard, because Rudy has lots of questions, “How much is the admission charge?” The “admission charge” is how much it costs to get into the museum. You could use that same expression for a park or a zoo, or a similar place: the “admission charge.” In Los Angeles, the admission charge for most museums is around 10, maybe $15. Some museums, such as the Getty Museum, are free.
The guard tells Rudy how much it costs to get into the museum. He says, “It’s $10.00 for adults, $3.00 for children, and $5.00 for seniors and students with picture ID.” A “senior” is someone who is, normally, more than 65 years old. “Picture ID” is short for “picture identification,” and this is something like a driver’s license that has your picture on it, and your name. Your passport is also a picture ID. Many schools give their students IDs (little cards with their name and picture on it) so they can prove that they are a student.
Rudy then finally asks, “If I leave after I pay, can I come back in?” And the Guard says, “Yes. You just have to show your stub” (stub). Your “stub” is the small part of the ticket that you keep. Usually, when you buy a ticket for a museum or a movie theater, they give you a ticket and they rip it in half, or they give you one part and they keep the other part. The part that you keep is called the “stub,” the “ticket stub.”
Now let's listen to the dialogue, this time at a normal speed.
[start of story]
I wanted to visit the National Museum, but when I arrived, it was closed.
Rudy: Can you tell me the hours of operation for the Museum?
Guard: It’s open from 10 a.m. to 5 p.m., Monday through Saturday. It’s closed on Sunday.
Rudy: Thanks. I’ll be back tomorrow.
---------
The next day, I arrived at the Museum at 10 a.m. and the same guard was there.
Rudy: Hello, again. Can you tell me if the Museum has any tours?
Guard: The Museum has a self-guided tour. You can get information at the ticket window.
Rudy: Oh, thanks. Do you know if I can use my flash to take photos in the Museum?
Guard: You can take pictures, but flash photography is prohibited. Food and drinks are prohibited, too.
Rudy: Oh, I guess I need to get rid of this bottle of juice before I go in. Do you know if all of the exhibits are open to the public today?
Guard: The east wing is under construction, but the rest of the galleries are open. The sculpture and painting galleries are to your left, and the artifacts are to your right.
Rudy: Thanks a lot. How much is the admission charge?
Guard: It’s $10.00 for adults, $3.00 for children, and $5.00 for seniors and students with picture ID. The people at the ticket window can help you with that.
Rudy: Thanks. Just one more question.
Guard: Yes?
Rudy: If I leave after I pay, can I come back in?
Guard: Yes. You just have to show your stub. Anything else?
Rudy: Oh, no. Thanks a lot. Sorry to have bothered you.
Guard: No trouble at all.
[end of story]
The script for this podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
hours of operation – the time when a building is open; the hours when something is open
* The bank’s hours of operation are Monday through Friday, from 9:00 a.m. to 5:30 p.m.
self-guided – without a guide; able to see something by oneself, without following another person around
* You can do a self-guided tour of the ruins, but it helps to have a detailed map.
flash – the quick, bright light that a camera produces to take a picture when it is dark
* The flash was so bright that we all saw white spots after she took the picture.
prohibited – forbidden; not allowed; against the rules
* Touching that sculpture is prohibited.
to get rid of – to throw something away; to do something so that one no longer has something with oneself; to separate oneself from something
* I need to get rid of these old clothes that are too small for me.
exhibit – a group of things related to one topic that are put in a museum or another place for people to look at
* This month, the National Geographic Museum has an interesting exhibit about Mount Everest.
open to the public – available for anyone to visit; not limited to a small group of people
* The White House is open to the public, but you have to get a special ticket to enter.
wing – one part of a large building that goes in a different direction than the rest of the building
* The hospital is building a new wing for cancer patients.
under construction – being built; not yet finished
* The library has been under construction for almost two years!
gallery – a room or a building for showing art, especially in a museum
* Gabriella thought that the Asian art gallery was more interesting than the modern art gallery.
sculpture – a solid object of art that is made by shaping clay, metal, stone, or wood
* Michelangelo’s most famous sculpture is his statue of David.
painting – a painted picture; a picture made with oil- or water-based colors, usually painted onto a piece of white fabric known as a “canvas”
* Leonardo DaVinci’s “Mona Lisa” is a very well known painting.
artifact – something that was made by humans in the past and is interesting today for historical or cultural reasons
* Many of the gold artifacts of the Incas were taken by Spanish explorers.
admission charge – the cost of entering a museum, zoo, park, or a similar place
* The zoo’s admission charge for adults is $7, but if you’re a student, it’s only $5.
senior – a person who is more than 65 years old
* At this restaurant, seniors get a 20% discount before 6 p.m.
picture ID – a piece of identification with a photograph of the person, such as a driver’s license
* If you don’t have picture ID, the airline won’t let you fly.
stub – the small part of a ticket that one keeps, while the larger part is given to a person when one enters the building
* If you leave the park, keep your ticket stub with you, so that you can show it at the entrance when you want to return.
Comprehension Questions
1. What isn’t prohibited at the museum?
a) Self-guided tours.
b) Flash photography.
c) Food and drink.
2. What isn’t open to the public?
a) The exhibits in the east wing.
b) The sculpture and painting galleries.
c) The artifacts on the right.
Answers at bottom.
What Else Does It Mean?
flash
The word “flash,” in this podcast, means the quick, bright light that a camera produces to take a picture when it is dark: “When you use a flash to take a picture of someone wearing glasses, sometimes the reflected light makes it difficult to see the person’s face.” A “flash” can also be any other quick, bright light that comes and goes quickly: “Did you see that flash of lightning?” Sometimes a “flash” is a feeling that one gets very suddenly: “In a flash of anger, he hit the child.” On a news program, a “flash,” or “newsflash” is a small amount of information about something that’s happening at the moment: “CNN just had a newsflash about the hurricanes in Florida.” The phrase “in a flash” means very quickly: “I can get that information for you in a flash!”
wing
In this podcast, the word “wing” means one part of a large building that goes in a different direction than the rest of the building: “The university’s engineering department is building a new wing for chemical engineering.” On a bird or insect, a “wing” is an arm-like body part that helps the animal fly: “A hummingbird moves its wings very quickly.” On an airplane, a “wing” is one of the long arm-like parts on the sides that help it fly: “When I flew to Denver, my seat was next to the wing, so I couldn’t see the mountains.” As a verb, “to wing it” means to do something without planning first, or to be spontaneous: “We didn’t have time to reserve a hotel room, so we’re just going to wing it and hope that we can find a place to stay once we’re there.”
Culture Note
The Smithsonian Institution was “established” (created) in the early 1800s, when a British man named James Smithson left his “estate” (all the money and property that he owned) to the United States to create a Smithsonian Institution that would increase and spread knowledge among all people.
Today there are 19 Smithsonian Museums that are free and open to the public, meaning that anyone can go there and there are no admission charges. Some of the most famous Smithsonian Museums are the National Museum of Natural History, the National Museum of American History, the National Air and Space Museum, and many art galleries. But there are “lesser known” (less famous; less well-known) museums that you may not have heard of.
One is the “National Postal Museum,” which explains the history of the U.S. “Postal Service,” or the organization that delivers the mail. The museum also has a large “collection” (group of objects) of U.S. stamps.
Another Smithsonian Museum is the National Portrait Gallery. A “portrait” is a painting of a person, and this museum is full of portraits of famous people in American history.
The newest Smithsonian Museum is the National Museum of the American Indian, which has exhibits about “indigenous” (native) cultures of North and South America. Similarly, the Anacostia Community Museum has exhibits about the history and culture of “African American” communities, or black people who live in the U.S.
Finally, the National Zoological Park is also part of the Smithsonian Institute. It is a “zoo” (park with animals) that has more than 400 “species” (types) of animals that people can see. It also has many educational programs for visitors to learn more about the animals.
Comprehension Answers
1 - a
2 - a