= 1104
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,104 – Making a Discovery.
This is English as a Second Language Podcast episode 1,104. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com or become a member of ESL Podcast. Take a look at our ESL Podcast Special Courses on our website, and you can also check out our ESL Podcast Blog while you’re there.
On this episode, we’re going to listen to a dialogue between Pierre and Irene about finding something new – making a discovery. Let’s get started.
[start of dialogue]
Pierre: How does it feel to be on the cusp of a new discovery?
Irene: Let’s not jump the gun. We’ve made some major leaps forward, but I’m not sure I’d call what we’ve done so far revolutionary.
Pierre: Not yet, but you’re close to a breakthrough. That’s evident.
Irene: I think you might be overstating the case. If we do make a small breakthrough, it will only contribute to the current body of knowledge in the field, not turn the field on its head.
Pierre: I think you’re downplaying the possible impact of such a discovery. I think you’ll be recognized as a pioneer, a real trailblazer.
Irene: And your contribution?
Pierre: You know what they say: Behind every great woman is a great man!
[end of dialogue]
Pierre asks Irene, “How does it feel to be on the cusp of a new discovery?” “To be on the cusp” (cusp) of something means to be at the moment when something very interesting is going to happen, to be at the point in time where something important or exciting will happen. We often use this expression when we’re about to find out something new or discover something. “To discover” (discover) is to find out about something that you didn’t know about before. “Discovery” is the noun that comes from the verb “to discover.”
Pierre asks about a “new discovery,” although anything that is discovered is by definition “new,” at least to the person who discovers it. Irene says, however, “Let’s not jump the gun.” “To jump (jump) the gun (gun)” means to do something too soon – to do something before you are ready or before you are prepared, or perhaps simply before you’re supposed to.
When you have a race – when a group of people are running, such as at the Olympics – the traditional way of starting the race is to fire a gun, to make a loud noise with a gun and that begins the race. If you start running before the gun makes its sound, you have “jumped the gun.” You have gone before you should have gone. We use the expression more generally to mean to do something “prematurely” – before you should or too soon.
Irene says, “We’ve made some major leaps forward, but I’m not sure I’d call what we’ve done so far revolutionary.” We’re not sure exactly what Irene is talking about, but she says that in whatever they’re doing, they’ve “made some major,” or large, “leaps forward.” A “leap” (leap) is a long jump. Here it signifies or means a significant advance in something – to make a lot of progress.
“I’m not sure I’d call what we’ve done so far revolutionary,” Irene says. Something that is “revolutionary” is something that is very exciting, something that will change society in an important way. That’s one definition of “revolutionary.” “Revolutionary” could also refer of course to the overthrow, sometimes violent overthrow, of a government – the change of a government.
Pierre says, “Not yet,” meaning yes, we haven’t discovered anything revolutionary yet. “But,” Pierre continues, “you’re close to a breakthrough.” A “breakthrough” (breakthrough) – one word – is a sudden and significant discovery, something that advances your knowledge or your ability to do something significantly. Pierre thinks Irene is “close to a breakthrough.” He says, “That’s evident” (evident).”That’s evident” means that’s apparent. That’s easy to see. That’s obvious.
Irene, however, says, “I think you might be overstating the case.” “To overstate (overstate) the case (case)” means to exaggerate, to describe something as being bigger or more important than it really is. Irene says, “If we do make a small breakthrough, it will only contribute,” or add, “to the current body of knowledge in the field, not turn the field on its head.”
A “body of knowledge” is a certain amount of information or research about a certain area of study. You could talk about the body of knowledge in physics. That would include everything we know, basically, about physics or perhaps about one specific area of physics. “To turn something on its head” means to change something completely, to change something entirely. Irene is saying that whatever discovery is made by her, it’s not going to “turn the field,” whatever area of study she’s working in, “on its head.” It’s not going to change it completely.
Pierre disagrees. He says, “I think you’re downplaying the possible impact of such a discovery.” “To downplay” (downplay) means to do or say something that makes something not seem very important or significant – to treat something as being less important than it really is. It’s sort of the opposite of “overstating the case.” Pierre says that he thinks Irene is “downplaying the possible impact” (impact) of a discovery. The “impact” is the influence, the consequences.
He says, “I think you’ll be recognized as a pioneer, a real trailblazer.” A “pioneer” (pioneer) is a person who does something for the first time or goes somewhere that no one else has been to before. A “trailblazer” (trailblazer) – one word – means something similar. It’s a person who is the first to do something. In addition, a trailblazer is someone who other people follow, who other people imitate.
Irene then asks Pierre, “And your contribution?” A “contribution” is what you give to someone or something to support the effort, to support the goal. Irene is asking Pierre what his contribution to this effort will be considered. How will people think about his contribution to whatever it is that Irene is doing? Pierre says, “You know what they say: Behind every great woman is a great man!”
This is actually a joke based upon a common phrase, “Behind every great man is a great woman,” which means that whenever you read about or hear about a man doing something great, there is often a wife or a woman who is helping that man in some way or at least loving and supporting the man, typically the husband. Well, Pierre is switching this around. He’s changing the expression, “Behind every great woman is a great man,” and that’s what Pierre is saying he will be considered as, we would guess: Irene’s husband.
The word “behind” (behind) here means supporting or helping in a way that you can’t see or you don’t notice. So every great man, in the traditional saying, is accomplishing things, is doing things, with the help of a woman. Again, typically a wife. But of course, Pierre is Irene’s husband, and so he’s the great man behind the great woman.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Pierre: How does it feel to be on the cusp of a new discovery?
Irene: Let’s not jump the gun. We’ve made some major leaps forward, but I’m not sure I’d call what we’ve done so far revolutionary.
Pierre: Not yet, but you’re close to a breakthrough. That’s evident.
Irene: I think you might be overstating the case. If we do make a small breakthrough, it will only contribute to the current body of knowledge in the field, not turn the field on its head.
Pierre: I think you’re downplaying the possible impact of such a discovery. I think you’ll be recognized as a pioneer, a real trailblazer.
Irene: And your contribution?
Pierre: You know what they say: Behind every great woman is a great man!
[end of dialogue]
Her scripts are revolutionary in the world of English language teaching. I speak, of course, of the wonderful Dr. Lucy Tse, our scriptwriter.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
on the cusp of – at the point in time or progress where something important or exciting is about to happen; at the moment when something interesting happens
* Blake is on the cusp of being able to run a mile in less than four minutes.
discovery – the action of finding, learning, or understanding something new, especially before anyone else has done so
* The reporters made a shocking discovery about the politician’s criminal past.
to jump the gun – to do something prematurely; to do something too soon; to do something before it is fully ready or prepared for
* You’ve only been dating Heather for two months. Don’t you think you’re jumping the gun by asking her to marry you so soon?
leap – a long jump; a significant forward movement, especially when referring to progress in doing something
* Over the past few months, we’ve really seen a leap in Randall’s progress in learning to play the violin.
revolutionary – very exciting and with an ability to change and improve society in an important way
* Vaccines have been revolutionary in improving healthcare.
breakthrough – a sudden and significant discovery or forward movement that advances progress, seeming to skip many steps
* Finding the thief’s fingerprints in the train was a breakthrough for the police detectives investigating the crime.
evident – apparent; easy to be seen or perceived; obvious
* Johann’s refusal to make eye contact made it evident that he was lying.
to overstate the case – to phrase something too strongly or too broadly; to exaggerate; to describe something as being bigger or more important than it really is
* When Kelley said that they were broke, she was overstating the case. They actually still have several thousand dollars in savings.
body of knowledge – the collective amount of all information, research, and articles on a particular topic or in a particular academic field
* Native Americans are underrepresented in the body of knowledge about the occurrences of colorectal cancer.
to turn (something) on its head – to change something completely, entirely, or in an important, significant way
* Being diagnosed with cancer turned Carla’s plans on their head.
to downplay – to do or say things that minimize the importance, significance, or scope of something; to treat something as being less important than it really is
* Don’t downplay your role in earning this award. We never could have produced the movie without your involvement.
impact – influence; ability to change other people or things; the consequences associated with something
* What will be the impact of climate change on coral reefs?
pioneer – a person who does something for the first time, or goes where other people have not been before
* Michael DeBakey was a pioneer in heart surgery.
trailblazer – a person who makes a new trail or path for others to follow; a person who is the first to do something and whose experience teaches others how to do the same
* When Rachel Carson wrote Silent Spring, she became a trailblazer for the environmental movement.
contribution – what one gives to someone or something in support of or for the good of a goal; one’s input or effort toward achieving something
* Shakespeare will always be remembered for his contributions to English literature and theater.
behind every great woman is a great man – a humorous reversal of the more common phrase, “behind every great man is a great woman,” which means that a man’s accomplishments are made possible by the love and support of his wife
* Julia’s husband cares for their children, but more importantly, listens to her and supports her so that she has the time and energy to further her career. It’s truly a case of behind every great woman is a great man.
Comprehension Questions
1. What does Irene mean when she says, “I think you might be overstating the case”?
a) She doesn’t think Pierre understands her research.
b) She thinks Pierre is exaggerating the importance of her work.
c) She thinks Pierre is speaking too loudly.
2. According to Pierre, what is the main value of Irene’s work?
a) She is going to make a lot of money.
b) She is going to significantly advance knowledge in her field.
c) She is going to correct many misunderstandings.
Answers at bottom.
What Else Does It Mean?
leap
The word “leap,” in this podcast, means a long jump or a significant forward movement, especially when referring to progress in doing something: “Securing that account was a huge leap in our company’s growth.” Perhaps the most memorable use of the word “leap” was the words spoken by astronaut Neil Armstrong when he became the first person to step on the moon: “That's one small step for a man, a giant leap for mankind.” The phrase “by leaps and bounds” describes something that happens very quickly and suddenly: “Sales have been increasing by leaps and bounds since our commercial appeared on TV.” A “leap in the dark” is something one does without knowing the outcome or whether it will be successful: “The proposal might succeed or fail. We’re going to have to take a leap in the dark.” Finally, a “leap year” occurs once every four years, when February has 29 days.
pioneer
In this podcast, the word “pioneer” means a person who does something for the first time, or goes where other people have not been before: “The earliest pioneers in medicine were performing operations under difficult circumstances, without basic surgical tools or anesthesia.” The word can also refer to an organization or institution: “Our company is a pioneer in using plastics for computers.” A “pioneer” is also someone who settles (begins to live) in a new, undeveloped area where there are many challenges and/or dangers, especially in the western part of North American during the early and mid-1800s: “Early pioneers frequently fought with Native Americans.” Or, “What killed more of the early American pioneers: disease, injury, or starvation?”
Culture Note
Eureka
The word “eureka” is an “interjection” (a word used to express surprise or emotion) used to happily announce a discovery, realization, or invention. It is related to a Greek word that means, “I have found it,” and the use of the phrase is “attributed to” (said to be originated or started by) Archimedes, a “scholar” (person who studies to gain knowledge) in ancient Greece. When taking a bath, Archimedes became excited when he noticed that his body “displaced” (took the place of) water, causing the “water level” (height of the water) to “rise” (go up), which makes it possible to “accurately” (precisely; exactly) calculate the “volume” (how much space something takes up) of an object.
Now, people sometimes say “eureka!” when they make an exciting discovery or when something suddenly “makes sense” (has a clear meaning). “Eureka” is also the state “motto” (a word or phrase that represents the goals and values of an entity) of California, where it refers to the 1848 discovery of gold near Sutter’s Mill, which “launched” (started) the “Gold Rush” (the period of time when many people went to California to look for gold in an effort to become rich; see English Café 310). In the U.S., there are at least 28 cities named Eureka, the largest of which is Eureka, California. There is also an academic institution called Eureka College in Eureka, Illinois.
The “eureka effect” refers to an experience commonly known as an “aha! moment,” when someone suddenly realizes that he or she knows the answer to something, often when not “actively” (on purpose) thinking about it. For example, if you have been thinking about a problem all day, and then finally stop worrying about it and begin relaxing to try to fall asleep, the solution may suddenly “come to you” (appear in your mind).
Comprehension Answers
1 - b
2 - b