= 1107
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,107 – The Death of a Pet.
This is English as a Second Language Podcast episode 1,107. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at ESLPod.com. Download a Learning Guide for this episode right after you become a member of ESL Podcast. You can also take a look at our ESL Podcast Store with additional courses in Business and Daily English. All of our courses can be downloaded immediately. There’s nothing to wait for. In fact, you shouldn’t really wait for us to send anything to you because we don’t send our courses in the mail. You download them directly from the website.
This episode is a dialogue between a father and his daughter about a pet that has died.
[start of dialogue]
Dad: Honey, I have some bad news for you. Fluffy has gone to the other side.
Sarah: You mean she’s out of her cage again? I’ll go and try to find her.
Dad: No, you don’t understand. Fluffy passed away in the night.
Sarah: Oh, she died! That’s too bad, but she was getting up there in years.
Dad: Yes, but she didn’t die a natural death. She was run over by the neighbor’s car.
Sarah: You mean she was flattened? Cool!
Dad: Well, I wouldn’t put it that way, but I understand if you’re in shock. I guess people show grief in different ways . . .
Sarah: Fluffy went out with a bang. That’s the way she would have wanted to go.
Dad: I’d like to think of her as being in heaven and she’s gone to meet her maker.
Sarah: I don’t think there’s an afterlife for animals, Dad. It’s all just a part of the circle of life.
Dad: Okay. I thought we could have a funeral for her so we can pay our respects.
Sarah: Is that really necessary?
Dad: I’d thought you’d want one. She was your pet, after all.
Sarah: No, let’s just bury her in the backyard.
Dad: And who said that the youth of today is cynical?
[end of dialogue]
This episode is all about one’s “pet” (pet) dying. A pet is an animal that you have usually in your house or near your house. A pet is typically something like a dog or a cat that people like to have. It’s sort of a companion – a friend, if you will. I don’t know. I don’t have any pets. I don’t really like animals, but if you’ve been listening to ESL Podcast, you probably know that already. Let’s get into our dialogue, then.
We have a father talking to his daughter, Sarah. He says, “Honey, I have some bad news for you.” “Honey” (honey) is a word we use for a girl or a woman. It’s what we would call a “term of endearment.” It’s sort of a nice thing to say to someone. A man may call his wife “honey,” or girlfriend “honey.” It’s a term of affection used for a woman or a girl. Certainly it’s something that a father could use with his daughter, and that’s what we see here.
Dad says, “I have some bad news for you. Fluffy has gone to the other side.” “Fluffy” was either a dog or a cat, I’m not sure which. Let’s call it a cat. I think that’s probably a more likely match, or fit, for the name Fluffy. “Fluffy,” Dad says, “has gone to the other side.” “Gone to the other side” is just a nice way of saying that someone has died, that someone – or in this case, some animal – is no longer living.
Sarah, however, doesn’t really understand her father because “to go to the other side” could mean simply to go, say, from your property to the property next to you – from your house to somewhere else. So she says, “You mean she’s out of her cage again?” A “cage” (cage) is something that you would keep an animal in. So maybe this isn’t a cat; maybe this is a rabbit or something. Anyway, it doesn’t matter. Sarah says, “I’ll go and try to find her.”
Sarah thinks that the animal has escaped from its cage, from the place where she was keeping it. Her father says, “No, you don’t understand. Fluffy passed away in the night.” The phrasal verb “to pass away” also means “to die.” It’s much more common to hear someone describe someone dying as the person “passing away” than it is “going to the other side.” In fact, I don’t think you would hear the expression “to go to the other side” very often.
People often, however, do say that someone has “passed away.” It’s a nicer way of saying someone has died. There are lots of “euphemisms” – nice ways of describing death and the process of dying. In some Christian churches they use the expression “fallen asleep in the Lord,” which I kind of like – the idea of falling asleep. It sounds a bit more poetic.
Sarah says, “Oh, she died! That’s too bad, but she was getting up there in years.” The expression “to get up there in years” means to be old – to no longer be young or even middle-aged. Sarah doesn’t seem too upset ?– at least, not as upset as her father perhaps thought she would be. Dad says, “Yes, but she didn’t die a natural death.” A “natural (natural) death” is when you die of some disease or illness or failure of some bodily organ or part, such as your heart or your lungs.
If it’s not a natural death, then it’s either an accident or it’s murder. No, I don’t think Fluffy has been murdered, but that would be really interesting in terms of the story. You know what I’m saying? Then I could be like a detective – the person who tries to find out who murdered, in this case, Fluffy. But no, it wasn’t a murder. It was, however, an accident. Dad says, “She was run over by the neighbor’s car.” “To be run over” means to be hit and injured or, in this case, killed by a car that goes over, in this case, the animal.
We’re not sure if it was an accident, however. Remember, it was the neighbor who was driving the car. Maybe the neighbor was trying to kill Fluffy. It’s possible. But we continue. Sarah says, “You mean she was flattened? Cool!” “To flatten” (flatten) something is to make it flat, meaning to make it so that it has very little height. Usually we flatten something with a heavy weight or object.
But Sarah thinks it’s cool. Sarah thinks it’s kind of interesting, in a good way, that the pet was flattened by the neighbor’s car. Maybe Sarah shouldn’t be owning pets. Anyway, Dad says, “Well, I wouldn’t put it that way,” meaning I wouldn’t say that, “but I understand you’re in shock.” “To be in shock” (shock) is to be very surprised by something, usually something negative.
Dad continues, “I guess people show grief in different ways.” “Grief” (grief) are feelings of extreme sadness after someone has died. Sarah says, “Fluffy went out with a bang.” “To go out with a bang” (bang) is to die doing something exciting, unusual, surprising, and/or memorable in some way. I really don’t care about going out with a bang. I’d rather just not go out – that is, die. But we all have to, don’t we? Sarah says, “That’s the way she would have wanted to go,” meaning that’s the way Fluffy would have wanted to die – assuming animals could want something in the same way that we want something.
Dad says, “I’d like to think of her” – I’d like to imagine her – “as being in heaven and she’s gone to meet her maker.” “Heaven” (heaven) in many religions is a place where God lives, where you go after you die or where you may go after you die. According to the theologians in the rock group the Bangles, “Heaven Is A Place on Earth,” but I don’t think many people believe that. The expression “gone to meet your maker” (maker) means that you have died. It’s another way of saying someone has died and has gone on to meet God. God here being the maker of the world and of all things.
Sarah says, “I don’t think there’s an afterlife for animals, Dad.” An “afterlife” (afterlife) is a state that your soul is in after it dies. It’s the idea that you have a soul or spirit that continues living on, or it could simply refer to whatever happens to you after you die, whatever continued existence you have. Sarah says, “It’s all just part of the circle of life.” The phrase “circle of life” is sometimes used to talk about the natural processes of birth, life, and death.
Dad says, “Okay, I thought we could have a funeral for her so we can pay our respects.” A “funeral” (funeral) is a ceremony that you hold after someone dies, often intended to honor the person who has died – to give friends and family a chance to talk about the person, perhaps, or remember the person. “To pay your respects” (respects) – notice it’s plural – means to honor someone’s memory or to remember someone in a nice way by actually going to his or her funeral.
Sarah says, “Is that really necessary?” Dad says, “I thought you’d want one,” meaning I thought you would want a funeral for Fluffy. Dad says, “She was your pet, after all.” But Sarah says, “No, let’s just bury her in the backyard.” “To bury” (bury) is to put a dead body into a hole in the ground and cover it with dirt. Usually you put the body in some other container, some sort of box, which for a human body we would call a “coffin” (coffin).
Dad is a bit surprised by Sarah’s attitude. He says, “And who said that the youth of today” – that is, young people today – “is cynical” (cynical). “Cynical” in this case means not interested in commonly accepted standards and behaviors. It can also be used to describe someone who is self-interested, who is looking after his own interests before other people.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Dad: Honey, I have some bad news for you. Fluffy has gone to the other side.
Sarah: You mean she’s out of her cage again? I’ll go and try to find her.
Dad: No, you don’t understand. Fluffy passed away in the night.
Sarah: Oh, she died! That’s too bad, but she was getting up there in years.
Dad: Yes, but she didn’t die a natural death. She was run over by the neighbor’s car.
Sarah: You mean she was flattened? Cool!
Dad: Well, I wouldn’t put it that way, but I understand if you’re in shock. I guess people show grief in different ways . . .
Sarah: Fluffy went out with a bang. That’s the way she would have wanted to go.
Dad: I’d like to think of her as being in heaven and she’s gone to meet her maker.
Sarah: I don’t think there’s an afterlife for animals, Dad. It’s all just a part of the circle of life.
Dad: Okay. I thought we could have a funeral for her so we can pay our respects.
Sarah: Is that really necessary?
Dad: I’d thought you’d want one. She was your pet, after all.
Sarah: No, let’s just bury her in the backyard.
Dad: And who said that the youth of today is cynical?
[end of dialogue]
We’re thankful that our scriptwriter has not yet gone to meet her maker. I speak of the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to go to the other side – a gentler way of saying someone has died or is no longer be living
* We’ll all eventually go to the other side, so it’s important to make the most of the time we have here.
to pass away – to die; to no longer be living
* Morgan’s father passed away when he was just five years old.
to die – for one’s life to end; to no longer be living
* Her mother died of lung cancer and her father died of a heart attack.
to get up there in years – to be old; to no longer be young or middle-aged
* Mariah is getting up there in years, but she’s still surprisingly healthy and active.
natural death – dying of old age or an illness, not from an accident or injury
* The police said he died a natural death, but some of us still suspect that it was murdered.
to be run over – to be hit and injured or killed by a car or another heavy moving object
* How many people are run over by trains each year?
to flatten – to make something very flat (having little height) by applying a heavy weight or pressure over it
* They sat on their suitcases to try to flatten the clothes enough to close the zipper.
in shock – very surprised by something, especially something negative that has happened, and unable to fully grasp or understand it or react appropriately
* When doctors tell their patients that they have cancer, they are often in shock and unable to focus on anything else the doctor says.
grief – feelings of extreme sadness and loss after a loved one has died
* Baback was overwhelmed by grief when his daughter died.
to go out with a bang – to die or to stop doing something in an exciting, unusual, surprising, and memorable way
* The fireworks display went out with a bang, with over 30 fireworks going off at the same time to end the show.
heaven – in religion, a place where God, angels, and sprits live forever in peace and without problems; paradise
* Do you believe that we go to heaven after we die?
to meet (one’s) maker – to meet God or the creator of all life after one has died, especially to be held responsible for one’s actions during life
* When you meet your maker, will you be able to defend what you’ve done with your life?
afterlife – life after death; a spiritual, eternal (never ending) life
* Will we be reunited with our family in the afterlife?
circle of life – life cycle; the natural processes of birth, life, and death
* We all die eventually. It’s just part of the circle of life.
funeral – a ceremony held shortly after one’s death, intended to honor the deceased (the person who has died) and give friends and family members an opportunity to share their memories of that person and say goodbye
* Is everyone expected to wear black to the funeral?
to pay (one’s) respects – to say or to do something to show one’s admiration or friendly feelings for someone
* Of course nobody likes going to funerals, but it’s an important way to pay our respects.
to bury – to place a dead body in a hole in the ground and cover it with dirt
* Do you want to be buried or cremated after you die?
cynical – not interested in commonly accepted standards and behaviors, or showing contempt (strong dislike) for them; believing that people do things to benefit themselves and not for the good of others
* Jake is too cynical to believe that anyone might want to try to help him.
Comprehension Questions
1. Which of these phrases does not mean “to die”?
a) To go to the other side
b) To pass away
c) To get up there in years
2. What does Sarah mean when she says, “Fluffy went out with a bang”?
a) Fluffy made a loud noise when she died.
b) Fluffy was involved in a car accident.
c) Fluffy died in an exciting, unusual way.
Answers at bottom.
What Else Does It Mean?
to be run over
The phrase “to be run over,” in this podcast, means to be hit and injured or killed by a car or another heavy moving object: “When Virginia was run over by a car, several ribs were broken, but she survived.” The phrase “to run early/late” means to be ahead/behind schedule: “Mr. Johnson is running late. Please take a seat and I’ll let you know when he’s available.” Or, “Our workshop is running early, so we’ll have some extra time for questions and answers at the end.” The phrase “to run for cover” means to quickly go to a safer place that provides protection, especially from bullets or fighting: “When the bombing started, everyone ran for cover.” Finally, the phrase “to run high” means for people to have a lot of strong emotions: “Tensions were running high throughout the negotiations.”
heaven
In this podcast, the word “heaven” means paradise, or in many religions, a place where God, angels, and sprits live forever in peace and without problems: “Do you think great-grandpa is looking down on us from heaven?” The phrase “in heaven” describes something that is very enjoyable and pleasant: “I was in heaven that entire day at the healthspa.” The phrase “a match made in heaven” describes a marriage or a romantic relationship in which the two people are very happy and are perfectly suited for each other: “Paula thought that she and Karim were a match made in heaven.” The phrase “for heaven’s sake” is used to show exasperation or frustration: “For heaven’s sake, why are you doing it that way?” Finally, the phrase “thank heavens” is used to show that someone is very pleased and grateful for something: “Thank heavens you stopped me before I walked onto that unsafe bridge!”
Culture Note
Laws Against Animal Cruelty
Animal “cruelty” means treating an animal very badly, “inflicting” (causing) pain and suffering, or “neglecting” (not taking care of) an animal that depends on humans. In the United States, there are many “federal” (national) and state laws that are “intended” (meant) to protect animals and punish “offenders” (people who break the law).
The American Society for the Prevention of Cruelty to Animals (ASPCA) has an online database that allows people to search for laws against animal cruelty by state. In 2013, the Animal Legal Defense Fund released a “ranking” (listing from best to worst, highest to lowest, etc.) of states by their animal protection laws. The states with the greatest protection were Illinois, Maine, Michigan, Oregon, and California, while the states with the weakest protection were Kentucky, Iowa, South Dakota, New Mexico, and Wyoming.
The main federal law regarding animal cruelty is the Animal Welfare Act of 1966, which was “enacted” (made into law) by President Lyndon B. Johnson. It “governs” (deals with) how animals should be treated in “exhibition” (being shown to the public) and “research” (scientific experiments). The law requires exhibitioners and researchers to a have a “license” (official permission) to work with animals. However, many people argue that the law “does not go far enough” (is too limited), because it does not deal with birds, rats, mice, animals used for food, and “cold-blooded animals” (animals that cannot regulate their body temperature, such as fish and lizards).
Some people argue that animals should be treated like people, not animals, “in the eyes of the law” (from a legal perspective). But others argue that this would “take things too far” (make something too extreme), given that animals are regularly used for food, “labor” (work), and materials such as “wool” (the hair on a sheep or llama) and “leather” (the treated skin of an animal) in ways that humans are not.
Comprehension Answers
1 - c
2 - c