= 1109
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,109 – Reading Poor Handwriting.
This is English as a Second Language Podcast episode 1,109. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. On it, we have some Special Courses in Business and Daily English that I think you’ll like. You can buy and download these right away. We don’t sell books. We don’t sell CDs. We sell immediate and instant downloads. Check out our website for more information.
On this episode, we’re going to listen to a dialogue between Lily and Hassan about handwriting – you know, using your hand to write on a piece of paper. Let’s get started.
[start of dialogue]
Lily: Can you make out what this says?
Hassan: Geez, who wrote that?
Lily: My doctor. She wrote down some instructions for me, but I can’t read her handwriting.
Hassan: I have no idea what that chicken scratch says.
Lily: I think that’s a “T,” but maybe it’s an “F.”
Hassan: Face it. Those scribbles are illegible. Why don’t you take a photo of that and email it to her nurse? Maybe she can decipher it for you.
Lily: I feel like if I just keep at it, I’ll be able to work it out.
Hassan: Patients shouldn’t have to try and read a doctor’s sloppy writing. What if they misinterpret it and do the wrong thing as part of their treatment?
Lily: This note isn’t that bad. I think I might have the first two words figured out already.
Hassan: Then you’re better at reading bad penmanship than I am. Maybe you should have a try at these English essays. I have 60 of them to grade.
Lily: Wow, looking at these, I’d say you have 60 future doctors in the making!
[end of dialogue]
Lily asks Hassan, “Can you make out what this says?” The phrasal verb “to make out” (out) here means to be able to understand something that someone has said or that someone has written, to be able to read something. If, for example, you pick up something and you’re trying to read the serial number – the numbers that come on an object to identify it, especially an electronic object – usually the serial numbers are written with very small print. They’re not very large, and so they’re difficult “to make out.” They’re difficult to read.
Hassan says, “Geez, who wrote that?” “Geez” (geez) is a word used to express surprise, or amazement, or perhaps annoyance – when something bothers you. Hassan is asking Lily who wrote this note or message that she’s trying to read. Lily says, “My doctor.” This is a bit of a joke, of course. At least in the United States, doctors have the reputation of having very poor “handwriting” – that is, the writing that they make with a pen or a pencil with their hands. Lily says her doctor wrote down some instructions for her, but she can’t read her handwriting.
Hassan says, “I have no idea what that chicken scratch says.” The term “chicken scratch” (scratch) is an informal one referring to handwriting that is very difficult to read – that is very, we might say, “sloppy” (sloppy). If something is “sloppy,” it’s not neat and organized. It’s not done with care. If someone described your handwriting as “chicken scratch,” he or she is being somewhat insulting, saying that your handwriting is very sloppy, almost as if a chicken had written it. I don’t know why a chicken. That’s just the expression.
Lily is trying to read the note. She says, “I think that’s a ‘T,’ but maybe it’s an ‘F.’” Lily is pointing to different letters on the piece of paper, trying to guess what they are. Hassan says, “Face it. Those scribbles are illegible.” The expression “face (face) it (it)” is used to tell someone that he or she needs to recognize the truth of what one is saying. It’s usually used when someone is trying to deny something that is obviously true, or that perhaps the person knows is true but doesn’t want to admit.
Hassan says, “Those scribbles are illegible.” “Scribble” (scribble) as a verb refers to writing something down quickly. “Scribbles” as a noun would refer to writing that was done very quickly and not carefully. The term “illegible” (illegible) means impossible to read, usually because the handwriting is very bad. Hassan says, “Why don’t you take a photo of that and email it to her nurse?” Hassan is suggesting that Lily take a photograph and email that photograph to the nurse of her doctor. “Maybe she” – assuming now the nurse is a woman – “can decipher it for you.”
“To decipher” (decipher) means to be able to understand the meaning of something that has been written in another code or system or even language. “To decipher” something means to figure it out, to be able to understand it. Governments, for example, often communicate using special secret codes that no one else can understand. These are codes, of course, that the country’s enemies try to decipher, try to figure out.
Hassan is referring to the doctor’s writing, not some special secret code. He recommends getting the doctor’s nurse to decipher it. Lily says, “I feel like if I just keep at it, I’ll be able to work it out.” A couple of common expressions there. The first one is “to keep at it.” “To keep at it” or “to keep at” something means to continue to do it even though it is difficult or challenging. It’s the opposite of giving up. If you give up, you stop. You quit. If you continue working on it even though it’s difficult, we would say you are “keeping at it.”
Lily uses another very common expression: “to work something out.” “To work something out” is to find the answer to some question or solution to some problem that is very difficult, that is very challenging. “To figure something out” is “to work it out.” “To work it out” usually involves a very complicated problem. If, for example, you like to read detective fiction – novels about private investigators and police who investigate crimes – you might be someone who likes to work out the solution, who tries to figure out who committed the crime, who committed the murder.
There are lots of, of course, famous writers of detective fiction in English. People like Agatha Christie and Dorothy Sayers from the early to mid part of the twentieth century, and of course many, many others. I personally love watching detective shows. I’ve watched probably thousands of them. I love watching a good mystery and trying to work it out. I never do, of course. My wife works it out like halfway through the show, and I am always surprised at the end and she’s already worked it out a long time ago. She’s much smarter than I am, of course.
Anyway Hassan says, “Patients shouldn’t have to try and read a doctor’s sloppy writing.” We talked about “sloppy” earlier on as being not very carefully done. “What if they,” meaning the patients, “misinterpret and do the wrong things as part of their treatment?” “To misinterpret” something is to misunderstand something, to come to the wrong conclusion. If a patient misinterprets the doctor’s instructions, they could be doing the wrong thing in terms of their treatment. “Treatment” refers to medical care – things that you or your doctor does to make you feel better, to get better physically.
Lily says, “This note isn’t that bad. I think I might have the first two words figured out already.” “Figured out,” of course, means understood. Hassan says, “Then you’re better at reading bad penmanship than I am.” “Penmanship” (penmanship) is just another word for handwriting. You don’t hear the word that often anymore now that we live in a world of computers and texting. In fact, some parents complain that the schools no longer teach good penmanship anymore the way they did back when they were young. My school taught us good penmanship. The problem is I never really learned it. They tried to teach me, but I was never very good at it.
Hassan says, “Maybe you should have a try at these English essays.” It appears that Hassan is a teacher and he has to read some handwritten essays. An “essay” (essay) is a short written document, often done as part of a school assignment. The teacher will tell students to write several paragraphs in order to demonstrate their knowledge of a certain topic. This is often done on a test that is given to the class. Hassan says that he has 60 of these essays “to grade” – to give a score to as the teacher.
Lily says, “Wow, looking at these, I’d say you have 60 future doctors in the making!” Lilly is making a joke. She’s saying that all of Hassan’s students have bad handwriting, have poor handwriting, which must mean that someday they will become doctors. That’s why she says “60 future doctors in the making.” If something is “in the making,” it is in the process of being made or formed. It’s not finished yet – it’s not in its completed form yet – but it is in the process of being completed.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Lily: Can you make out what this says?
Hassan: Geez, who wrote that?
Lily: My doctor. She wrote down some instructions for me, but I can’t read her handwriting.
Hassan: I have no idea what that chicken scratch says.
Lily: I think that’s a “T,” but maybe it’s an “F.”
Hassan: Face it. Those scribbles are illegible. Why don’t you take a photo of that and email it to her nurse? Maybe she can decipher it for you.
Lily: I feel like if I just keep at it, I’ll be able to work it out.
Hassan: Patients shouldn’t have to try and read a doctor’s sloppy writing. What if they misinterpret it and do the wrong thing as part of their treatment?
Lily: This note isn’t that bad. I think I might have the first two words figured out already.
Hassan: Then you’re better at reading bad penmanship than I am. Maybe you should have a try at these English essays. I have 60 of them to grade.
Lily: Wow, looking at these, I’d say you have 60 future doctors in the making!
[end of dialogue]
Our scriptwriter’s handwriting is never sloppy. That’s because she’s always very careful. I speak, of course, of the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for being wonderful and listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to make out – to be able to understand what something or someone says; to be able to read something
* My vision isn’t very good. Can you make out that sign?
Geez – a word used to express surprise, amazement, or annoyance
* Geez, did you see how well that three-year-old boy can sing and dance?
handwriting – writing made with a pen or pencil, not words that are typed
* She has the handwriting of an 8-year-old.
chicken scratch – very messy, sloppy handwriting that is difficult to read
* Randall needs an administrative assistant who can understand and type up his chicken scratch.
face it – a phrase used to tell someone that he or she needs to recognize the truth of what one is saying
* Face it. We’re not as young as we used to be and we can’t plan eight-hour cycling trips anymore.
scribble – something that has been written down carelessly and quickly, especially a picture or a word
* Juniper was supposed to take notes during the meeting, but these scribbles provide almost no information about what was discussed.
illegible – impossible to read because the handwriting is very bad
* Monique wasn’t able to finish the report because her boss’s comments on her draft were illegible.
to decipher – to understand the meaning of something that has been written in code or another system that makes it very difficult to understand
* Scientists are trying to decipher DNA to find ways to prevent many bad or dangerous medical conditions.
to keep at it – to continue to do something that is challenging or difficult; to not give up
* We haven’t found the solution yet, but if we keep at it, we should make some progress.
to work it out – to figure something out; to find the answer or solution to something that is challenging or difficult
* How many times did you have to listen to that quote before you could work it out and translate it?
sloppy – messy and disordered; not neat or tidy; done with carelessness
* Those calculations are too sloppy to incorporate into the financial statements.
to misinterpret – to misunderstand; to understand something in the wrong way, arriving at an incorrect meaning
* Cultural differences can cause us to misinterpret each other’s actions.
treatment – medical care; the way that an illness or injury is dealt with
* The treatment includes taking this medicine, drinking plenty of water, and getting extra rest.
figured out – understood; deciphered; with the answer or solution found
* It took the students several hours to get the math questions figured out.
penmanship – handwriting; the art and practice of writing by hand with beautiful letters that can be read easily
* Schools offer fewer classes in penmanship now that students spend so much more time typing.
essay – a short written document, especially a school assignment of a few pages
* University applicants need to write a two-page essay describing their career goals and explaining why they want to attend the program.
in the making – in the process of being made; in the process of being formed
* This new drug is four years in the making, and it could be the best medication for high cholesterol.
Comprehension Questions
1. Which of these would be the easiest to read?
a) Illegible scribbles
b) Sloppy writing
c) Clear penmanship
2. What does Lily mean when she says, “you have 60 future doctors in the making”?
a) The students will be well prepared for medical school.
b) The students are already writing sloppily, as many doctors do.
c) The students need to see a doctor to get help for their handwriting.
Answers at bottom.
What Else Does It Mean?
face it
The phrase “face it,” in this podcast, is used to tell someone that he or she needs to recognize the truth of what one is saying: “Let’s face it. This relationship isn’t working and we should break up.” The phrase “to face up to (something)” means to admit that there is a problem and/or to take responsibility and blame for it: “It’s time to face up to your mistakes.” Or, “Do you think the Senator will ever face up to the way he lied to voters?” Finally, the phrase “to face the music” means to accept the punishment or criticism received for one’s actions: “Heather broke the law years ago and now it’s finally time for her to face the music.”
in the making
In this podcast, the phrase “in the making” means in the process of being made or formed: “This home remodeling project is two years in the making, but it still isn’t finished.” The phrase “to have the makings of (something)” means to have certain characteristics of something: “This project has the makings of a disaster.” The phrase “to be the making of (someone)” means to be the cause of someone’s success: “He’s going to the best school in the country, and this education will be the making of him.” Finally, the phrase “to be of (one’s) own making” describes a problem that was caused or created by oneself: “The problems of your child’s misbehavior are of your own making. They reflect how little time you’ve spent with her and how little attention you’ve given her.”
Culture Note
Handwriting Instruction in Schools
In the past, American schools taught very young children how to “print” (write separate letters) and then quickly began to teach them “cursive” (a form of writing in which letters are connected to each other, with many flowing loops and curls). Students practiced “tracing” (copying, with one sheet of paper over another, and the words to be written showing through to the blank top sheet) letters and words and then practiced writing their own text in cursive.
However, with the increasing “prevalence” (how often something is found) of computers, schools have begun to emphasize the importance of “touch typing” (being able to type on a keyboard quickly and accurately, using all ten fingers, but without looking at the keys). Some schools do not teach cursive at all, and those that do usually emphasize it for only a year or two in elementary school, with no expectation that students will continue to write in cursive in the “upper” (later; more advanced) grades.
Some people believe that cursive handwriting is “antiquated” (old fashioned; no longer relevant) and does not need to be taught in schools. But other people “counter” (provide an opposite argument) by stating that students must be taught to write in cursive so that they can read old documents. They also argue that computers will never entirely replace pen and paper, so students need to learn to write in cursive legibly and quickly.
Most adults have a “hybrid” (combination) writing style, where some letters are joined as they would be in cursive, but other letters are “printed” (written separately). People tend to “defend” (respond to criticism of) their hybrid writing style by saying that it is faster than “pure” (100%) cursive or printing.
Comprehension Answers
1 - c
2 - b