= 1140
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,140 – Dealing With a Language Barrier.
This is English as a Second Language Podcast episode 1,140. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there and become a member of ESL Podcast. When you do, you can download a Learning Guide for this episode that contains a complete transcript of everything we say in this lesson. This episode is called “Dealing With” (or handling, taking care of) “a Language Barrier” – when two people can’t understand each other. Let’s get started.
[start of dialogue]
Carol: Send another memo to the Gibberese office. I think we have our wires crossed again.
Art: Don’t you think it would be better to call the office and speak to someone there? You might be able to get to the bottom of the misunderstanding more quickly.
Carol: I don’t speak Gibberish and we don’t have anyone bilingual in the office to act as an interpreter.
Art: Which means there’s no one who could translate our correspondence into Gibberish to make things easier.
Carol: That’s right. And plus, leaving a paper trail is better.
Art: You mean in case we have to cover our asses.
Carol: I wouldn’t put it like that, but breakdowns in communication are inevitable and it’s always helpful to be able to trace their source.
Art: Right. Okay, I’ll draft a memo and pass it by you before I send it, okay?
Carol: Sounds good.
Art: What I don’t understand is why we don’t simply hire people for this office who are fluent in Gibberish.
Carol: Do you know anyone who speaks Gibberish?
Art: Plenty!
[end of dialogue]
This episode is entitled “Dealing With a Language Barrier.” “To deal (deal) with” something means to take care of something or to handle a situation that might be difficult. This dialogue is about dealing with a “language barrier” (barrier). A “barrier” is normally something that separates two people or two groups of people. A barrier might also separate two different substances that you don’t want to mix together. A “language barrier” usually refers to when two people speak different languages and can’t communicate with each other.
Carol begins by saying, “Send another memo to the Gibberese office. I think we have our wires crossed.” A “memo” (memo) is a short business document, usually just one or two pages, that has information about a specific topic. Usually a memo is sent to people in your organization or within your company. “Memo” is actually short for a longer word, “memorandum.”
Carol says, “Send another memo to the Gibberese office.” We’re guessing that the “Gibberese office” is another office, perhaps in a different country. Carol says, “I think we have our wires crossed again.” The expression “to have your wires (wires) crossed” means to have a misunderstanding – when two people or two groups of people don’t understand each other because one person didn’t communicate the message very clearly or the other person misinterpreted or misunderstood the message.
Art says, “Don’t you think it would be better to call the office and speak to someone there?” Art doesn’t think it’s a good idea just to send a memo, which is – well, in the old days – a piece of paper, but nowadays more typically a Word document or a PDF document, I suppose. Art says, “You might be able to get to the bottom of the misunderstanding more quickly.”
The expression “to get to the bottom (bottom) of” something is a very common one in English. It means to investigate and find the real reason for something or to understand the cause of something. Often we use this expression when we’re trying to understand the reason for a problem or the cause of some problem. When there is a disaster that the government is involved in, sometimes officials for the government will say, “We’re going to get to the bottom of this” – we’re going to really find out what caused this. Of course, they never do, but that’s what they say.
Art says that if Carol calls the Gibberese office that they might be able to get to the bottom of the misunderstanding more quickly. A “misunderstanding” as a noun means a confusion, something that wasn’t understood correctly. Carol says, “I don’t speak Gibberish and we don’t have anyone bilingual in the office to act as an interpreter.” “Gibberish” here is used as a real language, but it’s really a joke in the dialogue because the word “gibberish” (gibberish) means meaningless words – words that you can’t understand, that don’t have any meaning.
When people don’t have an answer for something or they want to confuse you, they might start using real words, but in such a way that the words don’t really convey any meaning – they don’t communicate any message. They are using these words just to confuse you. Carol says, “I don’t speak Gibberish,” which here is a real language, “and we don’t have anyone bilingual in the office.” “To be bilingual” (bilingual) means to be able to speak two languages.
There’s an old joke: What do you call someone who can speak three languages? The answer is “trilingual.” What do you call someone who can speak two languages? The answer is “bilingual.” What do you call someone who can speak only one language? The answer is “an American.” Well, the actual answer would be someone who is “monolingual” (monolingual). But back to our dialogue . . .
Carol says that she doesn’t have anyone in the office “to act as,” or to be, “an interpreter” (interpreter). An “interpreter” is someone who translates spoken language. “To translate” means to take the meaning of the words in one language, of course, and put them in another language. A “translator” (translator) is a person who does that translation in writing. An interpreter is someone who translates spoken language.
It’s a difference that is not always observed – that people speaking and writing in English don’t always follow – but technically, an interpreter is someone who translates spoken language. A translator is someone who translates written language. Art says, “Which means there is no one who could translate our correspondence into Gibberish to make things easier.” Here, Art uses the verb “to translate” to mean to take the words in one language in written form and put them in another language.
Carol says, “That’s right,” meaning that’s correct. “And plus,” she says, “leaving a paper trail is better.” A “paper trail” (trail) is when you have written documents that you can show someone to prove what happened or to demonstrate what happened. A paper trail is very useful if you think you may be, in the future, investigated or if you need to show what happened in a certain business transaction or business deal. A paper trail usually would include keeping paper documents or electronic documents – emails, for example – that show what happened during a certain situation.
For example, if someone hits your car and you need to contact your insurance company, you are going to want to have a paper trail of all the things the insurance company sends you, all the things the other driver sends you. You need to keep all of that in case there’s a problem in the future. Carol says, “A paper trail is better than just calling someone on the telephone.” Art says, “You mean in case we have to cover our asses?” “To cover (cover) your ass” means to protect yourself from blame, to protect yourself from future accusations that you did something wrong.
This expression is not one that you would want to use unless you knew the person fairly well. It’s an informal and vulgar expression – I wouldn’t normally use this expression, myself. I don’t like using bad words in English, but this is an expression that in fact you would probably hear in an office among people who knew each other well. A lot of people use an abbreviation instead of the actual expression which is “CYA,” which means “Cover Your A” – and then of course the rest of the word. It’s not an expression I would recommend you using. We include it here so you can understand what it actually means.
Continuing on, then, Carol says, “I wouldn’t put it like that,” meaning I wouldn’t express it like that, “but breakdowns in communication are inevitable and it’s always helpful to be able to trace their source.” A “breakdown (breakdown) in communication” is when two people or two groups of people misunderstand each other – when the message that one group is trying to communicate to the other is not understood correctly.
Something that is “inevitable” (inevitable) is something that you cannot avoid, something that will happen even if you don’t want it to happen or even if you try to prevent it from happening. Death is inevitable. You are all going to die, just like I am. It’s something you can’t avoid. There. Isn’t that a happy thought? Don’t you feel better now? You’re going to die.
Anyway, Carol says, “It’s always helpful to be able to trace (trace) their source.” “To trace” means to follow the path or development of something. In this case, really it means to identify the source, to find out where the breakdown in communication took place. That’s why Carol thinks it’s better to leave a paper trail. You can see when there is a miscommunication, where that happened. If you just talk to someone on the telephone, unless you are recording the conversation, you can’t figure out where the problem was, perhaps.
Art says, “Right. Okay, I’ll draft a memo and pass it by you before I send it, okay?” “To draft” (draft) something is to write the first version of something, especially something you plan on changing or revising in the future. Art is going to draft a memo and “pass it by” Carol. “To pass something by” someone means to give it to someone so that that person can look at it and perhaps approve it – say it’s okay – or revise it, change it so that it’s better.
Carol says, “Sounds good,” which is an informal way of saying yes, okay, that’s a good idea: “Sounds good.” Art says, “What I don’t understand is why we don’t simply hire people for this office who are fluent in Gibberish.” “To be fluent” (fluent) in a language means to be able to speak the language easily and smoothly like a native speaker, like someone who grew up speaking the language. Carol says, “Do you know anyone who speaks Gibberish?” Art responds, “Plenty” (plenty). “Plenty” means a lot or many – more than what we need.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Carol: Send another memo to the Gibberese office. I think we have our wires crossed again.
Art: Don’t you think it would be better to call the office and speak to someone there? You might be able to get to the bottom of the misunderstanding more quickly.
Carol: I don’t speak Gibberish and we don’t have anyone bilingual in the office to act as an interpreter.
Art: Which means there’s no one who could translate our correspondence into Gibberish to make things easier.
Carol: That’s right. And plus, leaving a paper trail is better.
Art: You mean in case we have to cover our asses.
Carol: I wouldn’t put it like that, but breakdowns in communication are inevitable and it’s always helpful to be able to trace their source.
Art: Right. Okay, I’ll draft a memo and pass it by you before I send it, okay?
Carol: Sounds good.
Art: What I don’t understand is why we don’t simply hire people for this office who are fluent in Gibberish.
Carol: Do you know anyone who speaks Gibberish?
Art: Plenty!
[end of dialogue]
None of our dialogues contain gibberish, because they are written by the finest scriptwriter on the Internet, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
memo – memorandum; a short business document, usually just one page, that begins by specifying to/from/date/subject and then has a few sentences or paragraphs
* Please write a memo to the employees explaining the new sick leave policy.
to have (one’s) wires crossed – for two or more people to have different understandings or interpretations of the same situation, causing confusion
* We must have our wires crossed, because I thought we were meeting at 6:00, but he thought it was 7:00.
to get to the bottom of (something) – to investigate and find the true cause, reason, or source of something
* The doctors are trying to get to the bottom of her frequent headaches.
misunderstanding – confusion; something that is understood incorrectly, or at least differently than the way another person understands it
* The man said he was supposed to have a first-class ticket. Apparently, there was some misunderstanding at the ticket counter.
jibberish – language without meaning; meaningless words that cannot be understood and do not convey any meaning
* When they first moved overseas, everything they heard sounded like jibberish, but eventually they began understanding some words and phrases.
bilingual – with the ability to speak two languages well
* We need to hire a bilingual receptionist who can answer the phones in English and Spanish, depending on who is calling.
interpreter – a person who translates spoken language; a person who provides oral translation
* The hospital has several interpreters who are trained to assist doctors when they meet with patients who do not speak English.
to translate – to express words in another language in writing; to transform words from one language to another in writing
* Could you please help me translate these legal documents into English?
paper trail – written documents that can be used to understand what happened and when, as well as who was involved
* Always shred your confidential information. Otherwise, you’re leaving behind a paper trail for criminals to follow.
to cover (one’s) ass – to protect oneself from blame; to protect oneself from potential harm or accusations of wrongdoing
* Jeremiah is trying to cover his ass by saying that he never wanted to hire Becca, but we all remember it differently.
breakdown in communication – errors in communication; instances where messages are not conveyed and/or understood correctly; miscommunication
* Cultural differences contributed to the breakdown in communication during the project’s implementation.
inevitable – unavoidable; happening under any circumstances
* Death and taxes are inevitable.
to trace – to follow the path or development of something, especially to identify its source
* Scientists are tracing the pollutants, trying to identify where they are entering the river.
to draft – to write the first version of something, especially for someone else to review and revise as needed
* It’s a lot easier to draft an essay if you’ve taken the time to write an outline first.
to pass (something) by (someone) – to give someone an opportunity to review, modify, and/or approve something before it is considered finished
* Remember to pass the budget by the other department heads for their input before you submit it to the vice president.
fluent – able to speak a language easily and smoothly, like a native speaker
* Charlotte is fluent in Russian and Hebrew, and is learning to speak Portuguese.
plenty – many; a lot; a sufficient number; more than one needs
* We still have plenty of extra tickets. Do you know anyone who’d like to go to the event?
Comprehension Questions
1. Why does Carol think they have their wires crossed?
a) Because the computer network is not working.
b) Because there seems to be a misunderstanding.
c) Because everyone is angry with each other.
2. What does Carol mean when she says, “breakdowns in communication are inevitable”?
a) Breakdowns in communication are frustrating.
b) Breakdowns in communication are expensive.
c) Breakdowns in communication are unavoidable.
Answers at bottom.
What Else Does It Mean?
to get to the bottom of
The phrase “to get to the bottom of,” in this podcast, means to investigate and find the true cause, reason, or source of something: “We must get to the bottom of these accounting errors and figure out how much money is actually in the account.” The phrase “the bottom of the heap” refers to the least important thing, or the people in the lowest position: “When airlines began allowing passengers to pay for extra leg room, other fliers began feeling that they were at the bottom of the heap.” Finally, the phrase “to hit rock bottom” means to reach the very worst point, or to be in the worst possible situation that could not get any worse: “After years of drug addition, Winston finally hit rock bottom and decided he needed to get help.”
paper trail
In this podcast, the phrase “paper trail” refers to written documents that can be used to understand what happened and when, as well as who was involved: “The detectives followed the paper trail of bank statements and phone records to determine where the thief had gone.” A “campaign trail” refers to all the places a political candidate goes while running for office to try to get people to vote for him or her: “The Senator visited 80 cities in 35 states in just a few weeks while on the campaign trail.” The phrase “trail of (something)” means a series or line of marks left by something that moved over the area: “The hurricane left a trail of destruction.” Or, “The little boy left a trail of crumbs as he ate the cookie.” Finally, the phrase “to be on the trail of (someone or something)” means to try to follow someone or something: “The hunters are on the trail of a fox.”
Culture Note
Bilingual Immersion School Programs
In the United States, many children learn only English in school, possibly with two to four years of Spanish, French, German or another language in high school to meet a “foreign language requirement.” However, some parents recognize the disadvantage of “monolingualism” (ability to speak only one language) by placing children in language “immersion” (completely surrounded by something) programs. In an “immersion program,” students spend part or all of the day speaking and learning in another language. Rather than taking a Spanish class, for example, some or all of their classes are taught in Spanish.
Some of the immersion programs are “public” (paid for by the government), and others are “private” (paid for by the individual). Parents are attracted to the programs for many reasons. Sometimes the children are “heritage speakers,” who speak some of the “target language” (the language being taught in the program) because earlier generations of their family immigrated from parts of the world where that language is spoken. Other families have adopted their children from other parts of the world, and want those children to learn the language of that country. “Still” (Additionally) other families simply want their children to be able to communicate and do business with a larger population, and they believe that being bilingual will “open doors” (present opportunities) for doing so.
The exact language “division” (splitting into parts) of a student’s day is different from school to school. Some of the programs offer a “50/50” immersion experience, where half of the day is spent in English and the other half is spent in the target language. Other programs start with a “90/10” model where the percentage of time spent in the target language gradually decreases until it reaches 50/50. In other programs, the immersion percentage decreases significantly when the students begin “middle school” (grade 6). At that point, the students may have only one or two courses per day in the target language.
Comprehension Answers
1 - b
2 - c