= 1141
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,141 – Proofreading a Document.
This is English as a Second Language Podcast episode 1,141. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and download a Learning Guide for this episode. But first you have to become a member of ESL Podcast, and why not? When you become a member, you get access to all of our current Learning Guides for all of our current episodes.
This episode is a dialogue about proofreading a document – going through something you write to make sure that there aren’t any mistakes in it. Well, let’s get started.
[start of dialogue]
Russell: Hey, LeeAnn, you were an English major, right?
LeeAnn: Yes.
Russell: Could you proofread this for me?
LeeAnn: I don’t know. Do you want me to proof it for content or for structure?
Russell: For everything.
LeeAnn: So you’re asking me to fact-check all of the facts and figures and to parse each line to find any spelling, grammar, or punctuation errors.
Russell: That’s right. I used the spell-check on it, but some typos may have slipped through. I wouldn’t be surprised if it were riddled with other errors, too.
LeeAnn: Right. What about the formatting?
Russell: Check that, too. You can edit out the errors as you go along.
LeeAnn: You want me to proofread and edit it?
Russell: Sure, if you don’t mind.
LeeAnn: You do realize that this is a 400-page document, right?
Russell: Is there a problem?
[end of dialogue]
Russell begins our dialogue by saying, “Hey LeeAnn, you were an English major, right?” An “English major” is someone who majored in, or specialized in, a certain topic in college. I was a Spanish and history major. Those were the areas that I studied in-depth when I went to college, when I was at the university. Usually we talk about “major” when we’re talking about someone’s undergraduate degree, someone’s bachelor’s degree. So, if someone says, “I was a psychology major,” he means he studied psychology in college. That was the area that he specialized in.
LeeAnn answers Russell’s question by saying, “Yes,” meaning yes, I was an English major. Russell says, “Could you proofread this for me?” “To proofread” (proofread) a document means to look at it to make sure there are no errors, or to find the errors so that someone else can fix them. LeeAnn says, “I don’t know. Do you want me to proof it for content or for structure?”
“Content” here refers to the ideas and the words used to present information. “Structure” (structure) refers to how the document is organized. “Content” usually refers to the message that you are trying to communicate, the ideas of your document. “Structure” refers to how the document is organized. Russell says, “For everything,” meaning for both content and structure. LeeAnn then says, “So, you are asking me to fact-check all of the facts and figures and to parse each line for any spelling, grammar, or punctuation errors.”
“To fact-check” means to make sure that everything that you say in a document is true, to research whether the things that you say are in fact correct. So, for example, if I’m talking about the history of the United States and I’m giving certain information about the presidents, someone who is fact-checking my article would have to go back and make sure that what I say about each president is correct – that I have their names correct, and the dates of birth correct, and so forth.
“Facts and figures” (figures) is an expression meaning the information that you present in a document, often including numbers. “Figures” is another word for numbers, such as statistics in a table or a graph. So, “facts and figures” means the specific details, including numbers and other statistical information, that might be in your document. LeeAnn mentions “parsing each line to find any spelling, grammar, or punctuation errors.”
The verb “to parse” (parse) here means to analyze something by taking a whole and breaking it down into its parts. Normally “to parse” is used to mean to analyze a sentence into its different syntactical functions: this is a verb, this is a noun, and so forth. But here, LeeAnn is using it in a more general way to mean to look at something and examine each of its parts. The parts here would be the spelling, grammar, and punctuation of this document.
“Spelling,” of course, refers to making sure that the letters you use are in the correct order and are the correct letters. English spelling can be very difficult for someone who doesn’t read a lot. The word “to,” for example, could be spelled (to), (too), or (two), depending on which meaning you are trying to communicate.
“Grammar” (grammar) is something you’re probably already familiar with – it’s the structure of language, the rules that are typically followed when using a language. “Punctuation” refers to the use of periods, commas, apostrophes, colons, and other marks that you see in the written form of a language that help you understand it better.
Russell says, “That’s right. I used the spell-check on it, but some typos may have slipped through.” “Spell-check” is a function that is found in many word processing programs, including Microsoft Word, that helps you identify words that were spelled incorrectly. A “typo” (typo) is a word that was misspelled or a word that has some mistake in it that was accidental. It wasn’t because the person writing it didn’t know the correct way of, say, spelling the word, but rather that he accidentally put down the wrong letters and therefore created a word that was misspelled.
“To slip (slip) through” means to not be noticed, especially something that is an error, a mistake. Sometimes there are errors that slip through our editors – mistakes that we don’t find, we don’t notice. We would use the verb “catch.” “We didn’t catch the mistakes. We didn’t catch the errors.” Russell says, “I wouldn’t be surprised if it were riddled with other errors, too.” If something is “riddled (riddled) with” something, it has a lot of that something that you don’t want. If something is “riddled with errors,” it is full of errors. It has lots of mistakes in it.
LeeAnn says, “Right. What about formatting?” “Formatting” (formatting) refers to the way that something is arranged on the page. If you are creating a document in a word processing program like Word, you have to select the font – the way that the letters look – the size of the letters, and so forth. This is all part of the formatting. Russell says, “Check that too,” meaning yes, look at the formatting when you proofread the paper.
He then says, “You can edit out the errors as you go along.” “To edit (edit) out” something means to identify them and remove them – in this case, to find the mistakes and correct them. LeeAnn then says, “You want me to proofread and edit it?” Russell says, “Sure, if you don’t mind.” “If you don’t mind” means if that’s okay with you.
LeeAnn says, “You do realize that this is a 400-page document, right?” The word “document” that I have been using throughout my explanation here means written materials that have information about something. A document is anything that contains information that is written either in electronic form or in paper form. Notice that LeeAnn says, “You do realize.” “Sometimes we add the verb “do” even though we could just say “you realize.” The “do” gives emphasis to the verb. It gives emphasis to the idea.
For example, if your friend says to you, “I’m going to ask that girl sitting at the next table for her telephone number,” and you know this girl already has a boyfriend, you could say, “You do know that she has a boyfriend, right?” You could’ve just said, “You know she has a boyfriend, right?” But the use of the verb “do” there is to emphasize – to put stress, if you will, on the meaning of the verb. LeeAnn then says, “You do realize that this is a 400-page document, right?
Russell then says, “Is there a problem?” “Is there a problem?” means “Is there something wrong with that?” Of course, Russell is asking LeeAnn to do a lot of work, and we’re not sure if Russell is actually going to pay LeeAnn anything to do that work. It doesn’t sound like it from the dialogue. If I were LeeAnn, I’d probably say no.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Russell: Hey, LeeAnn, you were an English major, right?
LeeAnn: Yes.
Russell: Could you proofread this for me?
LeeAnn: I don’t know. Do you want me to proof it for content or for structure?
Russell: For everything.
LeeAnn: So you’re asking me to fact-check all of the facts and figures and to parse each line to find any spelling, grammar, or punctuation errors.
Russell: That’s right. I used the spell-check on it, but some typos may have slipped through. I wouldn’t be surprised if it were riddled with other errors, too.
LeeAnn: Right. What about the formatting?
Russell: Check that, too. You can edit out the errors as you go along.
LeeAnn: You want me to proofread and edit it?
Russell: Sure, if you don’t mind.
LeeAnn: You do realize that this is a 400-page document, right?
Russell: Is there a problem?
[end of dialogue]
Our dialogues are not riddled with errors in English, we hope, because they’re written by the greatest scriptwriter on the Internet – our very own Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
major – a person who focused on a particular area of study in college
* Jenny is a political science major, who intends on going to law school when she graduates.
to proofread – to check a document for errors and mark those errors for someone to fix
* Could you please proofread this, paying close attention to punctuation?
content –the ideas and words used to present information in a written document
* The content is well organized, but we could improve the word choice to make it more persuasive.
structure – how sentences, paragraphs, and an entire document are organized and how they relate to each other
* The sentence structure is good, but I think the document structure requires a stronger introduction and conclusion.
to fact check – to review all statements and compare them against source material to ensure that they are correct
* Good newspaper editors spend a lot of time fact checking stories before publication.
facts and figures – information that is presented in written form, either as numbers or in tables or graphs
* Make sure your statements are supported by clear facts and figures that can help the readers understand your message.
to parse – to analyze something in parts, one part at a time; to disassemble something so that one can examine each part and determine how it fits with the other parts
* The software engineers are parsing the code, trying to figure out what’s causing the error messages.
spelling – the letters and the order in which they must be placed to create a word
* The spelling of the words is very important for words like “to,” “too,” and “two,” which sound the same but have different meanings.
grammar – the structure of a language and the rules that must be followed to maintain that structure
* Verb tenses and irregular verbs are some of the most challenging aspects of English grammar to learn.
punctuation – the use of periods, commas, apostrophes, colons, and other marks to clarify meaning in writing
* Punctuation can change the meaning of a sentence.
spell check – a tool found in Microsoft Word and other word processing programs to identify misspelled words and offer suggestions for correcting them
* If the spell check marks the company name as a misspelled word, just add the name to the dictionary and then that won’t happen again.
typo – a word that is typed incorrectly; a word that is misspelled
* How can the title of the book be misspelled? Didn’t anyone check for typos before it went to the printer?
to slip through – to not be noticed, especially to not be caught as an error, mistake, or program during a quality check or review
* At the factory, a few damaged units slipped through the quality control checks.
to be riddled with (something) – to have many of some unwanted thing; to be flawed or made impure by something
* These beans are riddled with rocks. It will take some time to separate them out.
formatting – layout; how something is arranged and displayed on the page
* The formatting guidelines call for one-inch margins with 12-point, Times New Roman font.
to edit out – to identify and remove errors to improve a document
* Please edit out any references to “consumers” and replace them with “customers.”
document – written materials that provide information about something
* His report is a 60-page document filled with charts and graphs.
Comprehension Questions
1. What does Russell mean when he refers to LeeAnn as an English major?
a) He thinks she is from England.
b) He thinks she is an expert in the English language.
c) He thinks she studied English in college.
2. Which type of error is the spell check most likely to catch?
a) Typos.
b) Grammar errors.
c) Formatting errors.
Answers at bottom.
What Else Does It Mean?
major
The word “major,” in this podcast, means a person who focused on a particular area of study in college: “He was an engineering major, but he now works as an economist.” The word “major” more often refers to the field of study: “He has an undergraduate degree with a major in philosophy.” In the military, a “major” is an officer rank: “Report to the major when you arrive on base.” The word “major” can also mean most important or most significant: “Her major objection to the program is simply the cost of implementation.” Finally, “the majors” refers to the major leagues, or professional leagues, in a particular sport: “She played golf in the majors for years before deciding to retire from competing in tournaments and instead coach other golf players.”
to be riddled with
In this podcast, the phrase “to be riddled with (something)” means to have many of some unwanted thing, or to be flawed or made impure by something: “At the crime scene, the windows were riddled with bullet holes.” The phrase “riddled with holes” means with many small holes: “Her old clothing was dirty and riddled with holes.” A “riddle” is a humorous question that requires a clever answer: “Have you heard this riddle? ‘What comes down, but never goes up?’ ‘Rain!’” A “riddle” is also a mystery, something that people cannot solve or explain: “The shape of DNA was a riddle for years.” Finally, “to speak in riddles” means to speak in a confusing way that other people cannot understand: “Why are you speaking in riddles? Just speak clearly!”
Culture Note
Style Guides
A “style guide” is a set of rules about how documents should be written, designed, and produced. They are created and followed to “ensure” (make sure something happens) “consistency” (happening the same way every time) and “uniformity” (with all items being the same, without variation) in an organization’s written materials in the belief that this improves communication.
Style guides cover many topics, including whether numbers should be “spelled out” (written with words) or written with “digits” (in numerals), whether “gray” or “grey” is the preferred spelling of the color, and whether commas should be placed before the “and” in a list. They also cover “line spacing” (how much vertical room there should be between lines of text), the font and size of headings and titles, the information placed in “headers” and “footers” (information that appears at the top and bottom of each page), and the size of “margins” (how much white space is at the top, bottom, and sides of pages).
Most publications have their own style guide, which authors are requested to follow and editors are expected to “enforce” (make sure that the rules are followed). Many universities and large corporations have their own styles guides. Smaller businesses generally follow one of the “established” (well known and with a long history) style guides, such as:
? “AP Style” (The Associated Press Stylebook)
? “The MLA Handbook” (Modern Language Association Handbook for Writers of Research Papers)
? “The APA Style Guide” (American Psychological Association)
? “The Chicago Manual of Style”
Comprehension Answers
1 - c
2 - a