= 0360
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 360: A Management Dispute.
This is English as a Second Language Podcast episode 360.  I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
To take full advantage – to get the most out of this podcast episode, go to our website eslpod.com and download a Learning Guide for this episode.  The Learning Guide is an 8 to 10 page PDF file that contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, and a complete transcript of this entire episode – every word we say.  That’s at eslpod.com.
This episode is called “A Management Dispute.”  A “dispute” is a disagreement.  We’re going to listen to a dialogue between Jeannie and Salih about a problem at their company – at their work regarding the “management,” or the people who are the bosses.  Let’s get started.
[start of dialogue]
Jeannie:  Have you heard about the new management dispute?
Salih:  No, what’s happening?
Jeannie:  Well, the CEO is having problems with the head of one of the subsidiaries.
Salih:  Which one?
Jeannie:  Lance Publishing.  Apparently, the head, Bill Riker, is saying that he and the CEO differ too much in their business philosophy and they can’t agree on
a future direction for the company.
Salih:  I really hope they can settle their dispute soon.  It doesn’t do anybody any good to have so much hostility in the office.
Jeannie:  I hope so, too.  This company can’t afford to have another high-level departure.  We’ve lost so many good people already this past year.
Salih:  We’ve had a lot of bad press, that’s for sure.  It doesn’t matter that our employment contracts have confidentiality agreements.  When somebody is disgruntled, they talk, and they talk loudly and to whomever will listen.
Jeannie:  You’ve got that right.  I just hope none of us gets caught in the crossfire.  I deal with people at Lance Publishing every week.
Salih:  I’m with you.  I’m keeping a low profile and hoping that the whole thing will blow over soon.  What the CEO and the head of Lance Publishing need is a good mediator who can find some way for two incompatible personalities to meet in the middle.
Jeannie:  What do you think the chances are of that happening?
Salih:  Quite frankly, knowing the people involved, I think it has a snowball’s chance in hell!
[end of dialogue]
Jeannie begins our conversation by saying to Salih, “Have you heard about the new management dispute,” the new disagreement among the leaders of our company.  Salih said, “No, what’s happening?”  Jeannie says, “Well, the CEO (the chief executive officer, one of the highest people in the company) is having problems with the head of one of the subsidiaries.”  The “head” would be the leader, the boss.  A “subsidiary” is a company that is owned by a larger
company.  So, one company buys another company, that smaller company is called the “subsidiary.”
Salih asks, “Which one,” meaning which subsidiary.  Jeannie says, “Lance Publishing.  Apparently, the head, Bill Riker, is saying that he and the CEO differ too much in their business philosophy.”  “To differ” means to disagree: “We differ about who will win the election this year” – we have different opinions.  “Business philosophy,” here, just means your idea about how a business should operate, how it should be managed, how it should be run.
Salih says, “I really hope they can settle their dispute soon.”  “To settle” means to solve, in this case, to resolve, to bring an end to a problem.  There are several meanings of that word, “settle.”  Take a look at our Learning Guide for some additional explanations.  Salih says, “It doesn’t do anybody any good to have so much hostility in the office.”  “Hostility” is feelings of anger, when you are unfriendly to another person.  There is an adjective “hostile” (hostile), it means you are angry, or you don’t like another person and you’re unfriendly to them.  Salih wants less hostility in the office.
Jeannie says, “I hope so, too.  This company can’t afford to have another high-level departure.”  “Departure” comes from the verb “to depart,” which means to leave.  When you go to an airport in the United States, you will see a sign that says “arrivals,” and another sign that says “departures.”  Departures are the planes that are leaving; arrivals are those that are coming to, or arriving to the airport.  What Jeannie is talking about here is that one of the bosses will leave; they will depart.  Jeannie doesn’t want another “high-level,” or important person departing from the company, she says, “We’ve lost so many good people already this year.”
Salih says, “We’ve had a lot of bad press, that’s for sure.”  “Press” refers to, in this case, publicity, what other people are saying or writing about you in the newspaper, in a magazine, on television, or on the radio.  That’s generally called the “press.”  So, “bad press” is bad publicity, bad stories, or negative news about your company.
Salih says, “It doesn’t matter that our employment contracts have confidentiality agreements.”  The “employment contracts” are the agreements that they sign when they become employees of the company.  A “confidentiality agreement” is a legal contract that is between an employer, the company, and an employee, the person working for the company, in which the employee agrees that he or she will not give any secret information that they learn while working at the company to someone else.  So they’re saying I won’t tell anyone about your secrets.  We have many secrets here at the Center for Educational Development; I can’t tell you because I signed a confidentiality agreement.  I’m just kidding, we have no secrets here – trust me!
Salih says, “When somebody is disgruntled, they talk, and they talk loudly and to whomever will listen.”  Salih is saying that although all of the employees sign a confidentiality agreement, when someone is “disgruntled,” meaning when someone is upset or unhappy, they will talk to other people even though they are not supposed to.  They’ll “talk loudly,” so other people can hear them, “and to whomever will listen,” to anyone who will listen to their story.
Jeannie says, “You’ve got that right,” which is a slightly informal way of saying you are correct.  “I just hope none of us gets caught in the crossfire.”  “To get caught in the crossfire” means to become involved in a situation where there are two or more people arguing or fighting about something that doesn’t really concern you.  You are not someone who is directly involved, but because you are somehow in between these two people, you are involved in their argument even though you don’t want to be.  That’s “to be caught,” or “to get caught in the crossfire.”  “I deal with people at Lance Publishing every week,” Jeannie says.  So she’s afraid that she will get caught in the crossfire.
Salih says, “I’m with you.”  Again, a slightly informal way of saying I agree with you.  “I’m with you.  I’m keeping a low profile and hoping that the whole thing will blow over soon.”  The expression “to keep a low profile” (profile) means to remain quiet and do your job without “drawing,” or attracting, attention to yourself.  In other words, you don’t want people to notice you.  You want “to keep a low profile,” don’t do anything that would make other people know that you are there or notice what you are doing.  Salih wants to keep a low profile because he hopes that the whole thing – this situation – “will blow over soon.”  “To blow over” is a two-word phrasal verb meaning to end quietly so that people can continue working as they were before, to pass, to no longer exist.  “To blow over” has a couple of different meanings; take a look at our Learning Guide for some additional explanations.
Salih says, “What the CEO and the head of Lance Publishing need is a good mediator.”  A “mediator” is a person whose job it is to end a fight or a disagreement between two people or two organizations.  Sometimes when two groups cannot agree to something, they will ask a third person – a mediator – to come in between them and help “negotiate,” or find a solution for their problem or disagreement.
Salih hopes that they can find “a good mediator who can find some way for two incompatible personalities to meet in the middle.”  If you are “incompatible,” you are not compatible.  “To be compatible” means that you can get along with someone, that you and that person have similar ways of thinking or similar personalities.  “To be incompatible” means that you can’t get along with each other.  Sometimes people will say they’re getting a divorce because they are
incompatible with their wife or husband.  That happens here in Los Angeles every day!
“To meet in the middle” means to compromise, to reach an agreement where each person gives up something that he or she wanted in order for you to come to an agreement on something.  For example, if I say, “I will sell you my car for $1,000,” it’s an old car, and you say, “I’ll give you $500.”  I say, “Okay.  Well, let’s meet in the middle, $750.”  We both had to do something different than our original position in order to come to an agreement.
Jeannie then asks what “the chances are of that happening,” how possible is that?  Salih says, “Quite frankly (meaning honestly), knowing the people involved (since I know who the two people are, and considering that fact), I think it has a snowball’s chance in hell!”  This is an old expression.  “Snowballs” are round balls made out of snow, which, of course, is cold.  “Hell” is a place, in the Christian religion at least, where you go if you are evil, where your soul will go if you are bad in this world.  After you die, you can either go to heaven, which is a wonderful place, or hell, which is a terrible place.  Traditionally, hell has been
represented as being a place where there is fire, where it’s very hot.  So, if someone says, “This has a snowball’s chance in hell,” they mean that it is very
unlikely.  It is very improbable because a snowball, which is cold, would not survive in a hot place like hell – or Phoenix, Arizona in the summertime, which is
very similar!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Jeannie:  Have you heard about the new management dispute?
Salih:  No, what’s happening?
Jeannie:  Well, the CEO is having problems with the head of one of the subsidiaries.
Salih:  Which one?
Jeannie:  Lance Publishing.  Apparently, the head, Bill Riker, is saying that he and the CEO differ too much in their business philosophy and they can’t agree on
a future direction for the company.
Salih:  I really hope they can settle their dispute soon.  It doesn’t do anybody any good to have so much hostility in the office.
Jeannie:  I hope so, too.  This company can’t afford to have another high-level departure.  We’ve lost so many good people already this past year.
Salih:  We’ve had a lot of bad press, that’s for sure.  It doesn’t matter that our employment contracts have confidentiality agreements.  When somebody is disgruntled, they talk, and they talk loudly and to whomever will listen.
Jeannie:  You’ve got that right.  I just hope none of us gets caught in the crossfire.  I deal with people at Lance Publishing every week.
Salih:  I’m with you.  I’m keeping a low profile and hoping the whole thing will blow over soon.  What the CEO and the head of Lance Publishing need is a good mediator who can find some way for two incompatible personalities to meet in the middle.
Jeannie:  What do you think the chances are of that happening?
Salih:  Quite frankly, knowing the people involved, I think it has a snowball’s chance in hell!
[end of dialogue]
The script for this episode was written by the never disgruntled, never hostile Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan.  Thanks for listening.  We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan.  This podcast is copyright 2008.
Glossary
management dispute – a disagreement among a company’s leaders about how the company should be run
The company is having a big management dispute over whether it should open offices in other countries.
subsidiary – a company that is owned by a larger company
Does that company have any subsidiaries in the Southern United States?
business philosophy – a broad idea about how a business should be run and how a company should be managed
Andy’s business philosophy is based on the idea that employees should be active participants in corporate decision-making.
to settle – to solve; to resolve; to bring an end to a problem; to reach agreement on something
The two drunk men tried to settle their argument with a fight.
hostility – feelings of anger, aggression, and unfriendliness
Ileana shows so much hostility toward her son-in-law that he never wants to come visit.
departure – the act of leaving a company, either because one was fired or because one no longer wants to work there
The vice-president’s departure left everyone feeling nervous about how the company was going to continue without him.
bad press – negative publicity; negative stories about a company or person in the media, such as newspapers, magazines, or television
The shipping company received a lot of bad press when oil leaked from its ship into the ocean.
confidentiality agreement – a legal contract, usually between an employer and an employee, in which an individual agrees not to share secret information
You have to sign a confidentiality agreement before you can begin working at a nuclear power plant.
disgruntled – upset and unhappy; displeased with something
The students are disgruntled because the professor didn’t give them any advance notice about the exam today.
to get caught in the crossfire – to become involved in a situation where two or more people are arguing or fighting about something that often doesn’t really concern oneself
Small children often get caught in the crossfire when their parents argue.
to keep a low profile – to remain quiet and do one’s job without drawing
attention to oneself; to not be the center of attention
Wally is always trying to get people’s attention, but his brother prefers to keep a low profile, staying quiet and not doing anything that other people would take an interest in.
to blow over – to pass; for a problem to end quietly so that people can move on as if it had never happened
The couple had a huge fight last weekend. Do you think they’ll break up, or will it blow over?
mediator – a person whose job is to end a fight or argument between two or more people or organizations and help them find a satisfactory solution
The two homeowners hired a mediator to help them decide who should pay for the damage caused when one neighbor’s tree fell during the storm.
incompatible – so different that they cannot function well together; impossible to work together; unable to exist in the same place and time
They decided to get a divorce, because their interests had become incompatible.
to meet in the middle – to compromise; to reach an agreement where each person gives up something that he or she originally wanted
Olaf wanted to buy a four-bedroom home, but his wife wanted only a twobedroom home. They met in the middle and bought a three-bedroom home.
a snowball’s chance in hell – an expression used to show that something is very unlikely; an expression used to show that something probably will not happen, just like a snowball could not exist in hell because the hot temperatures would melt it
* Houses are so expensive! There’s a snowball’s chance in hell that I’ll ever be able to buy a home.
Comprehension Questions
1. What would happen if Jeannie were to “get caught in the crossfire”?
a) She would be unable to work as normal because of the dispute.
b) She would need to change her business philosophy.
c) She would have more bad press and confidentiality agreements.
2. What will happen if the two managers “meet in the middle”?
a) They’ll have a meeting somewhere between the two locations.
b) They’ll agree on the company’s future direction and business philosophy.
c) They’ll keep a low profile until things blow over.
Answers at bottom.
What Else Does It Mean?
to settle
The verb “to settle,” in this podcast, means to solve or bring an end to a problem: “Have you ever settled an argument by playing cards?” The verb “to settle” also means for a group of people to begin living in an area where there aren’t any other people: “In what year did European Americans begin settling in California?” The phrase “to settle down” means to start living a calm, normal life, often getting married and buying a home: “I don’t think Jamie is ready to settle down and get married yet. She needs a few more years to enjoy being single.” The phrase “to settle down” can also mean to calm down and become quiet: “Children, please settle down so that we can listen to the story.”
to blow over
In this podcast, the phrase “to blow over” means for a problem to end quietly so that people can move on as if it had never happened: “I think their argument will blow over in a couple of days.” The phrase “to blow (something) up” means to make something explode: “The planes dropped bombs to blow up the military base.” The phrase “to blow up at (someone)” means to become very angry with someone very quickly: “Nancy blew up at her husband for coming home late, and then apologized later.” Finally, the phrase “to blow (something) off” means to decide not to do something that one was scheduled to do: “We were supposed to go to the conference last week, but we decided to blow it off and rest for a few days instead.”
Culture Note
Businesses are often “prone” (likely) to have “conflicts” (arguments and disagreements). Managers try to settle those conflicts “on their own” (without outside help), but if they are unable to do so, they often hire business mediators. These are professionals who are trained and experienced in settling conflicts.
Mediators listen to both parties’ “concerns” (worries) and try to help them find a “compromise” (a solution that both parties are comfortable with, even though it isn’t what either party wanted originally).
As in this podcast, many conflicts are caused by differences of opinion regarding the direction that a business should take. Mediators are “unbiased” (without an opinion) on these issues, so they are able to listen to each party’s “perspective” (point of view) without “judging” (deciding whether something is good or bad) them. This makes it easier for everyone to find a fair compromise.
Mediators are also used when there are “mergers and acquisitions” (when companies buy each other), which often result in conflict between the old staff and the new staff. “Family-owned businesses,” where a single family owns and operates a business, often use mediators. In these businesses, the conflicts that “arise” (appear) are based not only on different business philosophies, but also family relationships.
Mediators are also “called in” (asked to come to a place and participate in a situation) by “human resources” (a division that selects and hires employees and tries to keep them happy at work). For example, if there is a conflict between an employee and his or her “supervisor” (the person to whom an employee reports), and if the company cannot settle it internally, it may ask a professional business mediator for guidance.
Comprehension Answers
1 - a
2 - b