
==== ▸ brittle  [4001]   +
な/ˈbrɪtəl/   +

【ADJ】   An object or substance that is _brittle_ is hard but easily broken. 硬脆易碎的   +
⇒  Pine is brittle and breaks.  松木硬脆易折。   +

---


==== ▸ melody  [4002]   +
な/ˈmɛlədɪ/   +

【N-COUNT】   A _melody_ is a tune. 旋律   +
⇒  I whistle melodies from Beethoven and Vivaldi and the more popular classical composers.  我用口哨吹贝多芬、维瓦尔迪和更大众化一些的古典作曲家的曲子。   +

---


==== ▸ correspondent  [4003]   +
な/ˌkɒrɪˈspɒndənt/   +

【N-COUNT】   A _correspondent_ is a newspaper or television journalist, especially one who specializes in a particular type of news. (尤指对某一专题进行报道的) 记者   +
⇒  As our Diplomatic Correspondent Mark Brayne reports, the president was given a sympathetic hearing.  据我台外事记者马克·布雷恩报道，该总统获得了一个同情的申诉机会。   +

---


==== ▸ fellowship  [4004]   +
な/ˈfɛləʊˌʃɪp/   +

【N-COUNT】   A _fellowship_ is a group of people that join together for a common purpose or interest. 团体   +
⇒  ...the National Schizophrenia Fellowship.  …全国精神分裂协会。   +

【N-COUNT】   A _fellowship_ at a university is a post which involves research work. 研究员职位   +
⇒  He was offered a research fellowship at Yale.  他得到了一个耶鲁大学的研究员职位。   +

【N-UNCOUNT】  _Fellowship_ is a feeling of friendship that people have when they are talking or doing something together and sharing their experiences. 交情   +
⇒  ...a sense of community and fellowship.  …一种社群归属感和友谊感。   +

---


==== ▸ welfare  [4005]   +
な/ˈwɛlˌfɛə/   +

【N-UNCOUNT】   The _welfare_ of a person or group is their health, comfort, and happiness. 健康; 幸福; 福利   +
⇒  I do not think he is considering Emma's welfare.  我认为他没有考虑到艾玛的幸福。   +

【ADJ】  _Welfare_ services are provided to help with people's living conditions and financial problems. 福利的   +
⇒  Child welfare services are well established and comprehensive.  儿童福利机构发展成熟、体系完善。   +

【N-UNCOUNT】  _Welfare_ is money that is paid by the government to people who are unemployed, poor, or sick. 社会保障金   +
⇒  States such as Michigan are making deep cuts in welfare.  密西根等州正在大幅度削减社会保障金。   +

---


==== ▸ trash  [4006]   +
な/træʃ/   +

【N-UNCOUNT】  _Trash_ consists of unwanted things or waste material such as used paper, empty containers and bottles, and waste food. 垃圾; 废物   +
⇒  The yards are overgrown and cluttered with trash.  院子杂草丛生，堆满了垃圾。   +
⇒  Would you take out the trash?  你可以把垃圾带出去吗？   +

【N-UNCOUNT】   If you say that something such as a book, painting, or movie is _trash_, you mean that it is of very bad quality. 劣质的东西   +
⇒  Pop music doesn't have to be trash; it can be art.  流行音乐并不一定是劣质的东西，它可以是艺术。   +

【N-SING】  _The trash_ means the dustbin. 垃圾桶   +
⇒  I threw it in the trash.  我把它扔进了垃圾桶。   +

【V】   to attack or destroy (someone or something) wilfully or maliciously 蓄意捣毁(某物); 蓄意攻击(某人)   +

---


==== ▸ ambiguity  [4007]   +
な/ˌæmbɪˈɡjuːɪtɪ/   +

【N-VAR】   If you say that there is _ambiguity_ in something, you mean that it is unclear or confusing, or it can be understood in more than one way. 模棱两可   +
⇒  There is considerable ambiguity about what this part of the agreement actually means.  关于协议这一部分到底是什么意思存在着相当大的含混不清。   +

---


==== ▸ theory  [4008]   +
な/ˈθɪərɪ/   +

【N-VAR】   A _theory_ is a formal idea or set of ideas that is intended to explain something. 理论   +
⇒  Marx produced a new theory about historical change based upon conflict between competing groups.  马克思提出了一个新理论，认为历史变革是由于对立集团的冲突而产生的。   +

【N-COUNT】   If you have a _theory_ about something, you have your own opinion about it which you cannot prove but which you think is true. 观点   +
⇒  There was a theory that he wanted to marry her.  有种观点认为他想娶她。   +

【N-UNCOUNT】   The _theory_ of a practical subject or skill is the set of rules and principles that form the basis of it. 基础理论   +
⇒  He taught us music theory.  他教我们乐理。   +

【PHRASE】   You use _in theory_ to say that although something is supposed to be true or to happen in the way stated, it may not in fact be true or happen in that way. 从理论上说   +
⇒  Achieving these goals is relatively easy in theory, yet quite difficult in practice.  实现这些目标从理论上说比较容易，但在实践上却相当困难。   +

---


==== ▸ petroleum  [4009]   +
な/pəˈtrəʊlɪəm/   +

【N-UNCOUNT】  _Petroleum_ is oil that is found under the surface of the earth or under the sea bed. Petrol and kerosene are obtained from petroleum. 石油   +

---


==== ▸ lash  [4010]   +
な/læʃ/   +

【N-COUNT】   Your _lashes_ are the hairs that grow on the edge of your upper and lower eyelids. 睫毛   +
⇒  ...sombre grey eyes, with unusually long lashes.  …忧郁的灰眼睛，长着特长的睫毛。   +

【V-T】   If you _lash_ two or more things together, you tie one of them firmly to the other. 捆紧   +
⇒  Secure the anchor by lashing it to the rail.  把锚紧紧地捆在横木上。   +
⇒  The shelter is built by lashing poles together to form a small dome.  该掩蔽处是把杆子捆到一起形成一个小圆顶而搭建成。   +

【V-T/V-I】   If wind, rain, or water _lashes_ someone or something, it hits them violently. (风、雨、水等) 猛袭   +
⇒  The worst winter storms of the century lashed the east coast of North America.  本世纪最猛烈的暴风雪袭击了北美的东海岸。   +

【V-T/V-I】   If someone _lashes_ you or _lashes into_ you, they speak very angrily to you, criticizing you or saying you have done something wrong. 怒斥   +
⇒  She went quiet for a moment while she summoned up the words to lash him.  她沉默了一会儿，想了些话来怒斥他。   +

【N-COUNT】   A _lash_ is a blow with a whip, especially a blow on someone's back as a punishment. 鞭打   +
⇒  The villagers sentenced one man to five lashes for stealing a ham from his neighbour.  村民们判一个男人5下鞭刑，因为他偷了一个邻居的火腿。   +

---


==== ▸ average  [4011]   +
な/ˈævərɪdʒ, ˈævrɪdʒ/   +

【N-COUNT】   An _average_ is the result that you get when you add two or more numbers together and divide the total by the number of numbers you added together. 平均数   +
⇒  Take the average of those ratios and multiply by a hundred.  取那些比例的平均数再乘以100。   +

【ADJ】  _Average_ is also an adjective. 平均的   +
⇒  The average price of goods rose by just 2.2%.  商品的平均价格仅上涨了2.2%。   +

【N-SING】   You use _average_ to refer to a number or size that varies but is always approximately the same. 平均值   +
⇒  It takes an average of ten weeks for a house sale to be completed.  平均需要10周的时间才能完成一幢房子的销售。   +

【N-SING】   An amount or quality that is _the average_ is the normal amount or quality for a particular group of things or people. 一般水平   +
⇒  35% of staff time was being spent on repeating work, about the average for a service industry.  员工35%的时间花费在重复劳动上，大约是服务业的一般水平。   +

【ADJ】  _Average_ is also an adjective. 正常标准的   +
⇒  $2.20 for a beer is average.  一瓶啤酒$2.20是一般价位。   +

【ADJ】   An _average_ person or thing is typical or normal. 普通的   +
⇒  The average adult man burns 1,500 to 2,000 calories per day.  一个普通成年男子每天消耗1500到2000卡路里热量。   +

【ADJ】   Something that is _average_ is neither very good nor very bad, usually when you had hoped it would be better. 平平的   +
⇒  I was only average academically.  我的学业成绩只能算平平。   +

【V-T】   To _average_ a particular amount means to do, get, or produce that amount as an average over a period of time. 平均为   +
⇒  We averaged 42 miles per hour.  我们平均时速为42英里。   +

【PHRASE】   You say _on average_ or _on the average_ to indicate that a number is the average of several numbers. 按平均值   +
⇒  Shares rose, on average, by 38%.  股值平均上涨了38%。   +

---


==== ▸ bias  [4012]   +
な/ˈbaɪəs/   +

【N-VAR】  _Bias_ is a tendency to prefer one person or thing to another, and to favour that person or thing. 偏见   +
⇒  ...his desire to avoid the appearance of bias in favour of one candidate or another.  …他想避免表现出对这个或那个候选人有偏好。   +

【V-T】   To _bias_ someone means to influence them in favour of a particular choice. (影响某人) 使偏心; 使产生偏见   +
⇒  We mustn't allow it to bias our teaching.  我们不允许它使我们的教学产生偏见。   +

---


==== ▸ deny  [4013]   +
な/dɪˈnaɪ/   +

【V-T】   When you _deny_ something, you state that it is not true. 否认   +
⇒  She denied both accusations.  她否认对她的两项指控。   +
⇒  The government has denied that the authorities have uncovered a plot to assassinate the president.  政府否认当局已经发现一个暗杀总统的阴谋。   +

【V-T】   If you _deny_ someone something that they need or want, you refuse to let them have it. 拒绝给予   +
⇒  Two federal courts ruled that the military cannot deny prisoners access to lawyers.  两联邦法院裁定军方不能拒绝让囚犯聘请律师。   +

---


==== ▸ palatable  [4014]   +
な/ˈpælətəbəl/   +

【ADJ】   If you describe food or drink as _palatable_, you mean that it tastes pleasant. 美味的   +
⇒  ...flavourings and preservatives, designed to make the food look more palatable.  …用来使食物看起来更美味的调味品和防腐剂。   +

【ADJ】   If you describe something such as an idea or method as _palatable_, you mean that people are willing to accept it. 可接受的   +
⇒  ...a palatable way of firing employees.  …一种可接受的解雇雇员的方式。   +

---


==== ▸ command  [4015]   +
な/kəˈmɑːnd/   +

【V-T】   If someone in authority _commands_ you to do something, they tell you that you must do it. 命令   +
⇒  He commanded his troops to attack.  他命令他的部队进攻。   +
⇒  "Get in your car and follow me," she commanded.  “上车然后跟我来，”她命令道。   +

【N-VAR】  _Command_ is also a noun. 命令   +
⇒  The tanker failed to respond to a command to stop.  油轮未能对停止前进的指令做出反应。   +
⇒  I closed my eyes at his command.  我听从他的命令闭上了眼睛。   +

【V-T】   If you _command_ something such as respect or obedience, you obtain it because you are popular, famous, or important. 博得   +
⇒  ...an excellent physician who commanded the respect of all her colleagues.  …一位博得所有同事尊敬的杰出医生。   +

【V-T】   If an army or country _commands_ a place, they have total control over it. 完全控制   +
⇒  Yemen commands the strait at the southern end of the Red Sea.  也门完全控制着红海南端的海峡。   +

【N-UNCOUNT】  _Command_ is also a noun. 完全控制权   +
⇒  ...the struggle for command of the air.  …对制空权的争夺。   +

【V-T】   An officer who _commands_ part of an army, navy, or air force is responsible for controlling and organizing it. 指挥   +
⇒  ...the French general who commands the U.N. troops in the region.  …指挥着这一地区联合国部队的法国将军。   +

【N-UNCOUNT】  _Command_ is also a noun. 指挥   +
⇒  ...a small garrison under the command of Major James Craig.  …一小支在詹姆斯·克雷格少校指挥下的卫戍部队。   +

【N-COUNT-COLL】   In the armed forces, a _command_ is a group of officers who are responsible for organizing and controlling part of an army, navy, or air force. 指挥部   +
⇒  He had authorization from the military command to retaliate.  他得到了军事指挥部进行还击的授权。   +

【N-COUNT】   In computing, a _command_ is an instruction that you give to a computer. 指令   +
⇒  I entered the command into my navigational computer.  我把指令输入了我的导航计算机。   +

【N-UNCOUNT】   If someone has _command_ of a situation, they have control of it because they have, or seem to have, power or authority. 控制 (局面等)   +
⇒  Mr. Baker would take command of the campaign.  贝克先生将负责这次运动。   +

【N-UNCOUNT】   Your _command of_ something, such as a foreign language, is your knowledge of it and your ability to use this knowledge. 掌握   +
⇒  His command of English was excellent.  他的英语相当出色。   +

【PHRASE】   If you have a particular skill or particular resources _at_ your _command_, you have them and can use them fully. 掌控   +
⇒  The country should have the right to defend itself with all legal means at its command.  这个国家应该有权动用它所掌控的所有法律手段来捍卫自己。   +

---


==== ▸ scope  [4016]   +
な/skəʊp/   +

【N-UNCOUNT】   If there is _scope for_ a particular kind of behaviour or activity, people have the opportunity to behave in this way or do that activity. 机会   +
⇒  He believed in giving his staff scope for initiative.  他赞成给他的员工主动的机会。   +

【N-SING】   The _scope of_ an activity, topic, or piece of work is the whole area which it deals with or includes. 范围   +
⇒  Mr. Dobson promised to widen the organization's scope of activity.  多布森先生答应扩大该组织的活动范围。   +

---


==== ▸ slip  [4017]   +
な/slɪp/   +

【V-I】   If you _slip_, you accidentally slide and lose your balance. 滑; 滑倒   +
⇒  He had slipped on an icy pavement.  他在结冰的人行道上滑倒了。   +

【V-I】   If something _slips_, it slides out of place or out of your hand. 滑走; 滑落   +
⇒  His glasses had slipped.  他的眼镜滑落了。   +

【V-I】   If you _slip_ somewhere, you go there quickly and quietly. 溜走   +
⇒  Amy slipped downstairs and out of the house.  埃米悄悄地下楼，溜出了屋子。   +

【V-T】   If you _slip_ something somewhere, you put it there quickly in a way that does not attract attention. 把…悄悄地放在   +
⇒  I slipped a note under Louise's door.  我悄悄地把一张字条塞到了路易丝的门下。   +
⇒  He found a coin in his pocket and slipped it into her hand.  他在口袋里找到一枚硬币，把它悄悄塞进她的手里。   +

【V-T】   If you _slip_ something _to_ someone, you give it to them secretly. 偷偷地给   +
⇒  Robert had slipped her a note in school.  罗伯特上学时偷偷地塞给了她一张字条。   +

【V-I】   To _slip into_ a particular state or situation means to pass gradually into it, in a way that is hardly noticed. (不知不觉地) 陷入   +
⇒  It amazed him how easily one could slip into a routine.  一个人如此容易就能陷入俗套，这使他感到吃惊。   +

【V-T/V-I】   If something _slips to_ a lower level or standard, it falls to that level or standard. 使下降; 下降   +
⇒  Shares slipped to $1.17.  股票下跌至$1.17。   +
⇒  In June, producer prices slipped 0.1% from May.  六月份，生产商的价格从五月份下降了0.1%。   +

【N-SING】  _Slip_ is also a noun. 下降   +
⇒  ...a slip in consumer confidence.  …消费者信心的一次下降。   +

【V-T/V-I】   If you _slip into_ or _out of_ clothes or shoes, you put them on or take them off quickly and easily. 迅速轻松地穿上; 迅速轻松地脱下   +
⇒  She slipped out of the jacket and tossed it on the couch.  她快速脱下了那件上衣，把它丢在沙发上。   +

【V】   to detach (portions of stem, etc) from (a plant) for propagation (从植物)取接枝   +

【N-COUNT】   A _slip_ is a small or unimportant mistake. 差错; 疏漏   +
⇒  We must be well prepared, there must be no slips.  我们必须好好准备，一定不要有差错。   +

【N-COUNT】   A _slip of_ paper is a small piece of paper. 纸条   +
⇒  ...little slips of paper he had torn from a notebook.  …他从笔记本上撕下的几张小纸片。   +
⇒  I put her name on the slip.  我把她的名字写在那张纸条上。   +

【N-COUNT】   A _slip_ is a thin piece of clothing that a woman wears under her dress or skirt. 衬裙   +

【N】   clay mixed with water to a creamy consistency, used for decorating or patching a ceramic piece 粘土与水的混合物   +

【N】   a part of a plant that, when detached from the parent, will grow into a new plant; cutting; scion 接枝; 插枝   +

【PHRASE】   If you _let slip_ information, you accidentally tell it to someone, when you wanted to keep it secret. 无意中说出 (秘密)   +
⇒  I bet he let slip that I'd gone to America.  我确信他无意中说出了我已去了美国。   +

【PHRASE】   If something _slips_ your _mind_, you forget about it. 被遗忘   +
⇒  The reason for my visit had obviously slipped his mind.  我到访的原因显然被他忘了。   +

---


==== ▸ impose  [4018]   +
な/ɪmˈpəʊz/   +

【V-T】   If you _impose_ something _on_ people, you use your authority to force them to accept it. 强制实行   +
⇒  Fines are imposed on retailers who sell tobacco to minors.  向未成年人销售烟草制品的零售商要被强制罚款。   +
⇒  A third of companies reviewing pay since last August have imposed a pay freeze of up to a year.  自去年8月以来，在审检工资发放的公司中，有三分之一已经强行实施工资冻结长达1年。   +

【N-UNCOUNT】   强制实行   +
⇒  ...the imposition of sanctions against Pakistan.  …对巴基斯坦制裁的强制实行。   +

【V-T】   If you _impose_ your opinions or beliefs _on_ other people, you try and make people accept them as a rule or as a model to copy. 把 (观点、信仰等) 强加于   +
⇒  Parents should beware of imposing their own tastes on their children.  父母应该提防把自己的兴趣强加给孩子。   +

【V-T】   If something _imposes_ strain, pressure, or suffering _on_ someone, it causes them to experience it. 使承受 (令人不快之事物)   +
⇒  The filming imposed an additional strain on her.  影片拍摄使她承受了额外的压力。   +

【V-I】   If someone _imposes on_ you, they unreasonably expect you to do something for them which you do not want to do. 不合理地要求   +
⇒  I was afraid you'd feel we were imposing on you.  我担心你会觉得我们在不合理地要求你。   +

【N-COUNT】   不合理的要求   +
⇒  I know this is an imposition. But please hear me out.  我知道这是个不合理的要求，但请听我把话说完。   +

【V-T】   If someone _imposes themselves on_ you, they force you to accept their company although you may not want to. 使强迫接受   +
⇒  I didn't want to impose myself on my married friends.  我不想硬要我的已婚朋友们接受我。   +

---


==== ▸ calculus  [4019]   +
な/ˈkælkjʊləs/   +

【N-UNCOUNT】  _Calculus_ is a branch of advanced mathematics which deals with variable quantities. 微积分学   +

---


==== ▸ rival  [4020]   +
な/ˈraɪvəl/   +

【N-COUNT】   Your _rival_ is a person, business, or organization who you are competing or fighting against in the same area or for the same things. 对手   +
⇒  The world champion finished more than two seconds ahead of his nearest rival.  这位世界冠军领先离他最近的对手两秒多钟冲过终点。   +

【N-COUNT】   If you say that someone or something has _no rivals_ or is _without rival_, you mean that it is best of its type. 可匹敌者   +
⇒  The area is famous for its wonderfully fragrant wine which has no rivals in the Rhone.  这一地区以其极为醇香的葡萄酒而闻名，这种酒在罗纳河流域没有可匹敌者。   +

【V-T】   If you say that one thing _rivals_ another, you mean that they are both of the same standard or quality. 与…相匹敌   +
⇒  Cassette recorders cannot rival the sound quality of CDs.  盒式磁带录音机在音质上无法与CD相媲美。   +

---


==== ▸ Jupiter  [4021]   +
な/ˈdʒuːpɪtə/   +

【N】   (in Roman tradition) the king and ruler of the Olympian gods (罗马传说中的)朱庇特; 奥林匹亚的众神之主 (Greek counterpart Zeus)   +
 ▷ Jupiter   +
な/ˈdʒuːpɪtə/   +

【N】     +

【N】   the largest of the planets and the fifth from the sun. It has 16 satellites and is surrounded by a transient planar ring system consisting of dust particles. Mean distance from sun: 778 million km; period of revolution around sun: 11.86 years; period of axial rotation: 9.83 hours; diameter and mass: 11.2 and 317.9 times that of earth respectively 木星   +

---


==== ▸ corpus  [4022]   +
な/ˈkɔːpəs/   +

【N-COUNT】   A _corpus_ is a large collection of written or spoken texts that is used for language research. 语料库   +

---


==== ▸ outrageous  [4023]   +
な/aʊtˈreɪdʒəs/   +

【ADJ】   If you describe something as _outrageous_, you are emphasizing that it is unacceptable or very shocking. 不可接受的; 令人震惊的   +
⇒  By diplomatic standards, this was outrageous behaviour.  按外交标准，这是不可接受的行为。   +

【ADV】   不可接受地; 令人震惊地   +
⇒  ...outrageously expensive skin care items.  …贵得不可接受的护肤品。   +

---


==== ▸ analysis  [4024]   +
な/əˈnælɪsɪs/   +

【N-VAR】  _Analysis_ is the process of considering something carefully or using statistical methods in order to understand it or explain it. 分析   +
⇒  Sporting greatness defies analysis – but we know it when we see it.  运动的伟大无法进行分析–但是我们一看就知道。   +

【N-VAR】  _Analysis_ is the scientific process of examining something in order to find out what it consists of. 化验分析   +
⇒  They collect blood samples for analysis at a national laboratory.  他们收集血样以在一个国家实验室做化验分析。   +

【N-COUNT】   An _analysis_ is an explanation or description that results from considering something carefully. 分析报告   +
⇒  Coming up after the newscast, an analysis of the president's domestic policy.  在新闻广播之后是一个对总统国内政策的分析报告。   +

---


==== ▸ lighthearted  [4025]   +
 辞典中没找到  +
==== ▸ comply  [4026]   +
な/kəmˈplaɪ/   +

【V-I】   If someone or something _complies with_ an order or set of rules, they do what is required or expected. 遵从   +
⇒  The commander said that the army would comply with the ceasefire.  指挥官说过部队会遵从停火协议。   +
⇒  Some beaches had failed to comply with environmental regulations.  一些海滩没能遵守环保规定。   +

---


==== ▸ agile  [4027]   +
な/ˈædʒaɪl/   +

【ADJ】   Someone who is _agile_ can move quickly and easily. 敏捷的   +
⇒  At 20 years old he was not as strong, as fast, as agile as he is now.  在他20岁时，他没有现在这样强壮、迅速、敏捷。   +

【N-UNCOUNT】   敏捷   +
⇒  She blinked in surprise at his agility.  她对他的敏捷惊愕地眨了眨眼睛。   +

【ADJ】   If you have an _agile_ mind, you think quickly and intelligently. 机敏的   +
⇒  She was quick-witted and had an extraordinarily agile mind.  她很机智并且有一个特别敏锐的头脑。   +

【N-UNCOUNT】   机敏   +
⇒  His intellect and mental agility have never been in doubt.  他的才智和头脑的敏锐从未被受到怀疑。   +

---


==== ▸ giant  [4028]   +
な/ˈdʒaɪənt/   +

【ADJ】   Something that is described as _giant_ is much larger or more important than most others of its kind. 巨大的; 重大的   +
⇒  ...America's giant car maker, General Motors.  …美国的汽车制造巨头——通用汽车公司。   +
⇒  ...a giant oak table.  …一张巨大的栎木桌。   +

【N-COUNT】  _Giant_ is often used to refer to any large, successful business organization or country. 大企业; 大国   +
⇒  ...Japanese electronics giant, Sony.  …日本的电子业巨头——索尼公司。   +

【N-COUNT】   A _giant_ is an imaginary person who is very big and strong, especially one mentioned in old stories. (尤指古老故事中虚构的) 巨人   +
⇒  ...a Nordic saga of giants.  …一部关于巨人的北欧传奇。   +

---


==== ▸ rigid  [4029]   +
な/ˈrɪdʒɪd/   +

【ADJ】   Laws, rules, or systems that are _rigid_ cannot be changed or varied, and are therefore considered to be rather severe. (法律、规章或制度) 僵死的; 过于严格的   +
⇒  Several colleges in our study have rigid rules about student conduct.  我们调查中的几所学院对学生行为举止都有过于严格的规定。   +

【N-UNCOUNT】   (法律、规章或制度的) 僵死; 过于严格   +
⇒  ...the rigidity of government policy.  …政府政策的僵化。   +

【ADJ】   If you disapprove of someone because you think they are not willing to change their way of thinking or behaving, you can describe them as _rigid_. (人) 刻板的; 头脑僵化的   +
⇒  She was a fairly rigid person who had strong religious views.  她是个相当刻板、有着很强宗教观念的人。   +

【ADJ】   A _rigid_ substance or object is stiff and does not bend, stretch, or twist easily. 僵硬的   +
⇒  ...rigid plastic containers.  …坚硬的塑料容器。   +

【N-UNCOUNT】   硬度   +
⇒  ...the strength and rigidity of glass.  …玻璃的强度与硬度。   +

---


==== ▸ strike  [4030]   +
な/straɪk/   +

【N-COUNT】   When there is a _strike_, workers stop doing their work for a period of time, usually in order to try to get better pay or conditions for themselves. 罢工   +
⇒  Air traffic controllers have begun a three-day strike in a dispute over pay.  空中交通管制员在一场薪酬纠纷中开始了为时3天的罢工。   +
⇒  Staff at the hospital went on strike in protest at the incidents.  这个医院的员工举行罢工，抗议这些事件。   +

【N-COUNT】   A military _strike_ is a military attack, especially an air attack. 袭击   +
⇒  ...a punitive air strike.  …一次惩罚性空袭。   +

【N】   the act or an instance of knocking down all the pins with the first bowl of a single frame 第一球全中   +

【N】   the score thus made   +
 ▷ strike   +
な/straɪk/   +

【N】     +

【V-I】   When workers _strike_, they go on strike. 罢工   +
⇒  ...their recognition of the workers' right to strike.  …他们对工人罢工权利的承认。   +
⇒  They shouldn't be striking for more money.  他们不该为更多的钱而罢工。   +

【N-COUNT】   罢工者   +
⇒  The strikers want higher wages, which state governments say they can't afford.  这些罢工者要求得到更高的工资，州政府说他们无力支付。   +

【V-T】   If you _strike_ someone or something, you deliberately hit them. 打; 击   +
⇒  She took two quick steps forward and struck him across the mouth.  她向前快走两步，打了他一记耳光。   +
⇒  It is impossible to say who struck the fatal blow.  不可能确定是谁给了那致命的一击。   +

【V-T】   If something that is falling or moving _strikes_ something, it hits it. 碰撞; 击中   +
⇒  His head struck the bottom when he dived into the 6 ft end of the pool.  当他跳入水池6英尺深的那端时，头撞到池底。   +
⇒  One 16-inch shell struck the control tower.  一发16英寸的炮弹击中了那座指挥塔。   +

【V-T/V-I】   If you _strike_ one thing against another, or if one thing _strikes_ against another, the first thing hits the second thing. 碰撞   +
⇒  Wilde fell and struck his head on the stone floor.  怀尔德跌倒了，头撞在石头地板上。   +

【V-T/V-I】   If something such as an illness or disaster _strikes_, it suddenly happens. (疾病或灾难) 爆发   +
⇒  Fed officials continued to insist that the dollar would soon return to stability but disaster struck.  联邦政府的官员们仍坚持说美元会很快恢复平稳，但灾难却爆发了。   +
⇒  A moderate earthquake struck the northeastern United States early on Saturday.  美国东北部周六早晨遭遇了一次中等强度的地震。   +

【V-I】   To _strike_ means to attack someone or something quickly and violently. 攻击   +
⇒  He was the only cabinet member out of the country when the terrorists struck.  他在恐怖分子袭击时是惟一人在国外的内阁成员。   +

【V-T】   If an idea or thought _strikes_ you, it suddenly comes into your mind. 使突然想到   +
⇒  A thought struck her. Was she jealous of her mother, then?  她突然冒出一个念头。那她是在嫉妒自己的母亲吗?   +

【V-T】   If something _strikes_ you _as_ being a particular thing, it gives you the impression of being that thing. 给…印象   +
⇒  He struck me as a very serious but friendly person.  他在我眼里是个非常严肃但友好的人。   +

【V-T】   If you _are struck_ by something, you think it is very impressive, noticeable, or interesting. 把…迷住   +
⇒  She was struck by his simple, spellbinding eloquence.  她被他简洁、富有鼓动性的口才迷住了。   +

【V-RECIP】   If you _strike_ a deal or a bargain with someone, you come to an agreement with them. 达成 (交易或协议)   +
⇒  They struck a deal with their paper supplier, getting two years of newsprint on credit.  他们与其纸张供应商达成一个协议，可以赊购两年的新闻纸。   +
⇒  The two struck a deal in which Rendell took half of what a manager would.  这两个人达成一项协议，伦德尔拿一名经理将能得到的一半。   +

【V-T】   If you _strike_ a balance, you do something that is halfway between two extremes. 找到 (某种平衡)   +
⇒  At times like that you have to strike a balance between sleep and homework.  在那样的时候，你得在睡眠和家庭作业之间找到一种平衡。   +

【V-T】   If you _strike_ a pose or attitude, you put yourself in a particular position, for example when someone is taking your photograph. 摆出 (姿态)   +
⇒  She struck a pose, one hand on her hip and the other waving an imaginary cigarette.  她摆出一个姿势，一只手叉腰，另一只手挥动着一支假想的香烟。   +

【V-T】   If something _strikes_ fear _into_ people, it makes them very frightened or anxious. 引起 (恐惧)   +
⇒  If there is a single subject guaranteed to strike fear in the hearts of parents, it is drugs.  如果只有一个话题能保证在家长们的心中引起恐惧的话，那就是毒品。   +

【V-T/V-I】   When a clock _strikes_, its bells make a sound to indicate what the time is. (钟) 敲响   +
⇒  The clock struck nine.  钟敲了9下。   +

【V-T】   If you _strike_ words _from_ a document or an official record, you remove them. 删除   +
⇒  Strike that from the minutes.  从会议记录中把那个删除。   +

【PHRASAL VERB】  _Strike out_ means the same as . 删除   +
⇒  The censor struck out the next two lines.  审查员删除了下面那两行。   +

【V-T】   When you _strike_ a match, you make it produce a flame by moving it quickly against something rough. 擦 (火柴)   +
⇒  Robina struck a match and held it to the crumpled newspaper in the grate.  罗比纳擦了一根火柴，将它伸向壁炉中的那些皱报纸。   +

【V-T】   If someone _strikes_ oil or gold, they discover it in the ground as a result of mining or drilling. 发现 (石油或黄金)   +
⇒  Oil industry sources say that Marathon Oil Company has struck oil in Syria.  石油业消息人士称马拉松石油公司在叙利亚发现了石油。   +

---


==== ▸ patronize  [4031]   +
な/ˈpætrəˌnaɪz/   +

【V-T】   If someone _patronizes_ you, they speak or behave toward you in a way that seems friendly, but that shows that they think they are superior to you in some way. 屈尊对待   +
⇒  Don't you patronize me!.  你不要屈尊对待我。   +

【V-T】   Someone who _patronizes_ artists, writers, or musicians supports them and gives them money. 赞助   +
⇒  The Japanese imperial family patronizes the Japanese Art Association.  日本皇室资助日本艺术协会。   +

【V-T】   If someone _patronizes_ a place such as a bar, shop, or hotel, they are one of its customers. 光顾   +
⇒  The ladies of Berne liked to patronize the palace for tea and little cakes.  伯尔尼的女士们喜欢光顾这个地方喝茶吃点心。   +

---


==== ▸ bare  [4032]   +
な/bɛə/   +

【ADJ】   If a part of your body is _bare_, it is not covered by any clothing. 赤裸的   +
⇒  She was wearing only a thin robe over a flimsy nightgown, and her feet were bare.  她只在薄薄的睡衣外面穿了件薄袍子，还光着双脚。   +

【ADJ】   A _bare_ surface is not covered or decorated with anything. 无遮盖的; 无装饰的   +
⇒  They would have liked bare wooden floors throughout the house.  他们本想把整个房子都铺不加装饰的原木地板。   +

【ADJ】   If a tree or a branch is _bare_, it has no leaves on it. (树或树枝) 没有树叶的   +
⇒  ...an old, twisted tree, many of its limbs brittle and bare.  …一棵扭曲的老树，它的树枝很多是脆弱而光秃的。   +

【ADJ】   If a room, cupboard, or shelf is _bare_, it is empty. 空的   +
⇒  His fridge was bare apart from three very withered tomatoes.  他的冰箱里除了3个干瘪的番茄之外什么也没有。   +

【ADJ】   An area of ground that is _bare_ has no plants growing on it. (土地) 光秃的   +
⇒  That's probably the most bare, bleak, barren and inhospitable island I've ever seen.  那可能是我见过的最光秃、最荒凉、最贫瘠和最不适合居住的岛屿。   +

【ADJ】   If someone gives you the _bare_ facts or the _barest_ details of something, they tell you only the most basic and important things. 最简要的   +
⇒  Newspaper reporters were given nothing but the bare facts by the superintendent in charge of the investigation.  报社记者们只提供了负责该项调查的监管人所提供的一些简要事实。   +

【ADJ】   If you talk about the _bare_ minimum or the _bare_ essentials, you mean the very least that is necessary. 基本的   +
⇒  The army would try to hold the western desert with a bare minimum of forces.  军队将尽量用最少的兵力控制西部沙漠。   +

【ADJ】  _Bare_ is used in front of an amount to emphasize how small it is. 仅仅的   +
⇒  Sales are growing for premium wines, but at a bare 2 percent a year.  优质葡萄酒的销量在上涨，但每年仅涨2%。   +

【V-T】   If you _bare_ something, you uncover it and show it. 使露出   +
⇒  Walsh bared his teeth in a grin.  沃尔什一笑露出了牙齿。   +

【PHRASE】   If someone does something _with_ their _bare hands_, they do it without using any weapons or tools. 徒手   +
⇒  Police believe the killer punched her to death with his bare hands.  警方认为凶手是徒手击她至死的。   +

---


==== ▸ repress  [4033]   +
な/rɪˈprɛs/   +

【V-T】   If you _repress_ a feeling, you make a deliberate effort not to show or have this feeling. 抑制 (感情)   +
⇒  It is anger that is repressed that leads to violence and loss of control.  正是被抑制的愤怒导致暴力和失控。   +

【V-T】   If you _repress_ a smile, sigh, or moan, you try hard not to smile, sigh, or moan. 忍住 (笑、叹气或呻吟)   +
⇒  He repressed a smile.  他忍住没有笑。   +

【V-T】   If a section of society _is repressed_, their freedom is restricted by the people who have authority over them. 镇压; 压制   +
⇒  ...a UN resolution banning him from repressing his people.  …联合国的一项禁止他镇压人民的决议。   +

---


==== ▸ chart  [4034]   +
な/tʃɑːt/   +

【N-COUNT】   A _chart_ is a diagram, picture, or graph which is intended to make information easier to understand. 图表   +
⇒  Male unemployment was 14.2%, compared with 5.8% for women (see chart on next page).  男性失业率是14.2%，相比女性为5.8% (参见下页图表)。   +

【N-COUNT】   A _chart_ is a map of the sea or stars. 海图; 星图   +
⇒  ...charts of Greek waters.  …希腊水域图。   +

【V-T】   If you _chart_ an area of land, sea, or sky, or a feature in that area, you make a map of the area or show the feature in it. 绘制   +
⇒  Ptolemy charted more than 1,000 stars in 48 constellations.  托勒密绘制了48个星座中1000多颗星的星图。   +

【V-T】   If you _chart_ the development or progress of something, you observe it and record or show it. You can also say that a report or graph _charts_ the development or progress of something. 用图表记录   +
⇒  One doctor has charted a dramatic rise in local childhood asthma since the road was built.  一位医生用图表记录的方式，说明道路建成后当地儿童哮喘发病率急剧上升。   +

---


==== ▸ reunion  [4035]   +
な/riːˈjuːnjən/   +

【N-COUNT】   A _reunion_ is a party attended by members of the same family, school, or other group who have not seen each other for a long time. (家庭、学校及其他团体成员的) 重聚会   +
⇒  The association holds an annual reunion.  这个协会每年举行一次重聚会。   +

【N-VAR】   A _reunion_ is a meeting between people who have been separated for some time. 重逢   +
⇒  The children weren't allowed to see her for nearly a week. It was a very emotional reunion.  孩子们将近一周都没被允许见她。这是一次非常令人激动的重逢。   +

---


==== ▸ homing  [4036]   +
な/ˈhəʊmɪŋ/   +

【ADJ】   A weapon or piece of equipment that has a _homing_ system is able to guide itself to a target or to give out a signal that guides people to it. 自动导向的   +
⇒  All the cars are fitted with electronic homing devices.  所有这些汽车都安装了电子自动导向仪。   +

【ADJ】   An animal that has a _homing_ instinct has the ability to remember and return to a place where it has been in the past. (动物)有返回原地能力的   +
⇒  Then the pigeons flew into thick fog, and the famous homing instinct failed.  然后这些鸽子飞进浓雾中，著名的归巢本能失灵了。   +

---


==== ▸ prototype  [4037]   +
な/ˈprəʊtəˌtaɪp/   +

【N-COUNT】   A _prototype_ is a new type of machine or device that is not yet ready to be made in large numbers and sold. 样机   +
⇒  Chris Retzler has built a prototype of a machine called the wave rotor.  克里斯·雷兹勒做出了一台叫做波转子的样机。   +

---


==== ▸ interrogate  [4038]   +
な/ɪnˈtɛrəˌɡeɪt/   +

【V-T】   If someone, especially a police officer, _interrogates_ someone, they question them thoroughly for a long time in order to get some information from them. 审问   +
⇒  I interrogated everyone even slightly involved.  我审问了每个人，即便是稍有关联的人也在其中。   +

---


==== ▸ across  [4039]   +
な/əˈkrɒs/   +

【PREP】   If someone or something goes _across_ a place or a boundary, they go from one side of it to the other. 过   +
⇒  She walked across the floor and lay down on the bed.  她走过地板躺在了床上。   +
⇒  He watched Karl run across the street to Tommy.  他看着卡尔横穿那条街道向汤米跑去。   +

【ADV】  _Across_ is also an adverb. 从一边到另一边   +
⇒  Richard stood up and walked across to the window.  理查德站起来，走到了窗户那边。   +

【PREP】   If something is situated or stretched _across_ something else, it is situated or stretched from one side of it to the other. 跨越   +
⇒  ...the floating bridge across Lake Washington in Seattle.  …横跨西雅图华盛顿湖的浮桥。   +
⇒  He scrawled his name across the bill.  他在账单上草草地写了他的名字。   +

【ADV】  _Across_ is also an adverb. 跨越   +
⇒  Trim toenails straight across using nail clippers.  用指甲刀整块地剪脚指甲。   +

【PREP】   If something is lying _across_ an object or place, it is resting on it and partly covering it. 在…上   +
⇒  She found her clothes lying across the chair.  她发现她的衣服平放在椅子上。   +

【PREP】   Something that is _across_ something such as a street, river, or area is on the other side of it. 在…另一边   +
⇒  Anyone from the houses across the road could see him.  在路另一边的那些房子里的任何一个人都能看到他。   +

【ADV】  _Across_ is also an adverb. 在对面   +
⇒  They parked across from the Castro Theatre.  他们在卡斯特罗剧院对面停了车。   +

【PREP】   You use _across_ to say that a particular expression is shown on someone's face. (表情) 在 (某人脸) 上   +
⇒  An enormous grin spread across his face.  一个灿烂的笑容绽开在他的脸上。   +

【PREP】   If someone hits you _across_ the face or head, they hit you on that part. (击打) 在…上   +
⇒  Graham hit him across the face with the gun, then pushed him against the wall.  格林厄姆用枪打在他的脸上，然后把他推到墙上。   +

【PREP】   When something happens _across_ a place or organization, it happens equally everywhere within it. 在…各处   +
⇒  The film opens across the country on December 11.  这部电影于12月11日在全国各地上映。   +

【PREP】   When something happens _across_ a political, religious, or social barrier, it involves people in different groups. 在…里   +
⇒  ...parties competing across the political spectrum.  …在政治领域里竞争的党派。   +

【ADV】   If you look _across_ at a place, person, or thing, you look toward them. 向   +
⇒  He glanced across at his sleeping wife.  他瞥向睡着的妻子。   +
⇒  She rose from the chair and gazed across at him.  她从椅子上站起凝目朝他望去。   +

【ADV】  _Across_ is used in measurements to show the width of something. …宽   +
⇒  This hand-decorated plate measures 14 inches across.  这个手绘盘子有14英寸宽。   +

---


==== ▸ represent  [4040]   +
な/ˌrɛprɪˈzɛnt/   +

【V-T】   If someone such as a lawyer or a politician _represents_ a person, a group of people, or a place, they act on behalf of that person, group, or place. 代表; 代理   +
⇒  ...the politicians we elect to represent us.  …我们所选的代表我们的政治家。   +
⇒  ...Richard Bolling, a Democrat who represented Missouri in Congress.  …理查德•博林，一个在国会中代表密苏里州的民主党人。   +

【V-T】   If you _represent_ a person or group at an official event, you go there on their behalf. 代表 (出席)   +
⇒  The general secretary may represent the president at official ceremonies.  秘书长可以在官方仪式上代表主席。   +

【V-T】   If you _represent_ your country or city in a competition or sports event, you take part in it on behalf of the country or city where you live. 代表 (参赛)   +
⇒  My only aim is to represent the United States at the Olympics.  我惟一的目标就是代表美国参加奥运会。   +

【V-T PASSIVE】   If a group of people or things _is_ well _represented_ in a particular activity or in a particular place, a lot of them can be found there. 使有代表性   +
⇒  Women are already well represented in the area of TV drama.  女性在电视戏剧领域已经占有很大比例。   +

【V-T】   If a sign or symbol _represents_ something, it is accepted as meaning that thing. 代表; 表示; 象征   +
⇒  ...a black dot in the middle of the circle is supposed to represent the source of the radiation.  …圆圈中央的黑点应该表示射线的来源。   +

【V-T】   To _represent_ an idea or quality means to be a symbol or an expression of that idea or quality. 代表; 象征; 反映   +
⇒  New York represents everything that's great about America.  纽约象征着美国伟大的一切。   +

【V-T】   If you _represent_ a person or thing _as_ a particular thing, you describe them as being that thing. 描写; 描绘   +
⇒  The popular press tends to represent him as an environmental guru.  大众媒体倾向于把他描绘成环保领袖。   +

---


==== ▸ supplier  [4041]   +
な/səˈplaɪə/   +

【N-COUNT】   A _supplier_ is a person, company, or organization that sells or supplies something such as goods or equipment to customers. 供应商   +
⇒  ...one of the country's biggest food suppliers.  …该国最大的食品供应商之一。   +

---


==== ▸ slog  [4042]   +
な/slɒɡ/   +

【V-T/V-I】   If you _slog through_ something, you work hard and steadily through it. 苦干   +
⇒  They secure their degrees by slogging through an intensive 11-month course.  他们通过苦读11个月的强化课程而获得了学位。   +

【PHRASAL VERB】  _Slog away_ means the same as . 苦干   +
⇒  Edward slogged away, always learning.  爱德华埋头苦干，总是在学习。   +

【N-SING】   If you describe a task as a _slog_, you mean that it is tiring and requires a lot of effort. 苦干   +
⇒  There is little to show for the two years of hard slog.  这两年的埋头苦干没有什么可展示的。   +

---


==== ▸ dye  [4043]   +
な/daɪ/   +

【V-T】   If you _dye_ something such as hair or cloth, you change its colour by soaking it in a special liquid. 染色   +
⇒  The women prepared, spun, and dyed the wool.  妇女们将羊毛预备、纺线并染色。   +

【N-MASS】  _Dye_ is a substance made from plants or chemicals which is mixed into a liquid and used to change the colour of something such as cloth or hair. 染料   +
⇒  ...bottles of hair dye.  …一瓶瓶的染发剂。   +

---


==== ▸ architect  [4044]   +
な/ˈɑːkɪˌtɛkt/   +

【N-COUNT】   An _architect_ is a person who designs buildings. 建筑师   +

【N-COUNT】   The _architect of_ an idea, event, or institution is the person who invented it or made it happen. 设计师; 缔造者   +
⇒  James Madison was the principal architect of the constitution.  詹姆斯·麦迪逊是该宪法的主设计师。   +

---


==== ▸ counterfeit  [4045]   +
な/ˈkaʊntəfɪt/   +

【ADJ】  _Counterfeit_ money, goods, or documents are not genuine, but have been made to look exactly like genuine ones in order to deceive people. 伪造的   +
⇒  He admitted possessing and delivering counterfeit currency.  他承认持有和运送了假币。   +

【N-COUNT】  _Counterfeit_ is also a noun. 仿制品; 伪造品   +
⇒  Levi Strauss says counterfeits of the company's jeans are flooding Europe.  利瓦伊·斯特劳斯说该公司牛仔裤的仿冒品充斥着欧洲市场。   +

【V-T】   If someone _counterfeits_ something, they make a version of it that is not genuine but has been made to look genuine in order to deceive people. 仿冒; 伪造   +
⇒  ...the coins Davies is alleged to have counterfeited.  …这些据称是戴维斯伪造的硬币。   +

---


==== ▸ simmer  [4046]   +
な/ˈsɪmə/   +

【V-T/V-I】   When you _simmer_ food or when it _simmers_, you cook it by keeping it at boiling point or just below boiling point. 用文火炖; 煨   +
⇒  Make an infusion by boiling and simmering the rhubarb and camomile together.  煮炖大黄和黄春菊来熬成浓汁。   +

【N-SING】  _Simmer_ is also a noun. 炖; 煨   +
⇒  Combine the stock, whole onion and peppercorns in a pan and bring to a simmer.  把高汤料、整个洋葱和胡椒粒拌入平底锅内，然后用文火炖。   +

【V-I】   If a conflict or a quarrel _simmers_, it does not actually happen for a period of time, but eventually builds up to the point where it does. (冲突或争吵) 酝酿; 趋于激化   +
⇒  ...bitter divisions that have simmered for more than half a century.  …酝酿了半个多世纪的严重分歧。   +

---


==== ▸ approximate  [4047]   +
な【ADJ】   An _approximate_ number, time, or position is close to the correct number, time, or position, but is not exact. 大概的 (数字、时间或方位等)   +
⇒  The approximate cost varies from around $150 to $250.  大致的费用在$150至$250之间不等。   +

【ADV】   大概地   +
⇒  Approximately $150 million is to be spent on improvements.  大概1.5亿美元将花在改进上。   +

【ADJ】   An idea or description that is _approximate_ is not intended to be precise or accurate, but to give some indication of what something is like. 大概的 (观点或描述等)   +
⇒  They did not have even an approximate idea what the Germans really wanted.  他们对于德国人真正想要什么甚至没有一个大致概念。   +

【V-T】   If something _approximates_ something else, it is similar to it but is not exactly the same. 近似于   +
⇒  The mixture described below will approximate it, but is not exactly the same.  下面所描述的混合物会与之近似，但不完全一样。   +

---


==== ▸ raw  [4048]   +
な/rɔː/   +

【ADJ】  _Raw_ materials or substances are in their natural state before being processed or used in manufacturing. 未加工的   +
⇒  We import raw materials and energy and export mainly industrial products.  我们进口原材料和能源，主要出口工业产品。   +

【ADJ】  _Raw_ food is food that is eaten uncooked, that has not yet been cooked, or that has not been cooked enough. (食物) 生的   +
⇒  ...a popular dish made of raw fish.  …由生鱼做的一道很受欢迎的菜肴。   +

【ADJ】   If a part of your body is _raw_, it is red and painful, perhaps because the skin has come off or has been burned. (身体某部因破皮或烫着等) 红且疼的   +
⇒  ...the drag of the rope against the raw flesh of my shoulders.  …绳子勒磨在我肩上又红又疼的肉上。   +

【ADJ】  _Raw_ emotions are strong basic feelings or responses which are not weakened by other influences. 强烈直露的 (情感)   +
⇒  Her grief was still raw and he did not know how to help her.  她的悲伤仍然强烈直露，他不知道如何帮助她好。   +

【ADJ】   If you describe something as _raw_, you mean that it is simple, powerful, and real. (用以描述事物) 质朴的; 强大的; 真实的   +
⇒  ...the raw power of instinct.  …本能的强大力量。   +

【ADJ】  _Raw_ data is facts or information that has not yet been sorted, analysed, or prepared for use. (数据等) 未整理的; 原始的   +
⇒  Analyses were conducted on the raw data.  对原始数据进行了分析。   +

【ADJ】   If you describe someone in a new job as _raw_, or as a _raw_ recruit, you mean that they lack experience in that job. 无经验的   +
⇒  ...replacing experienced men with raw recruits.  …用没有经验的新成员代替有经验的人。   +

【ADJ】  _Raw_ weather feels unpleasantly cold. 阴冷的   +
⇒  ...a raw December morning.  …12月份一个阴冷的早晨。   +

【ADJ】  _Raw_ sewage is sewage that has not been treated to make it cleaner. 未处理的 (污水)   +
⇒  ...contamination of drinking water by raw sewage.  …饮用水被未处理的污水所污染。   +

【PHRASE】   If you say that you are getting _a raw deal_, you mean that you are being treated unfairly. 不公平的待遇   +
⇒  I think women have a raw deal.  我认为妇女受到了不公平的待遇。   +

---


==== ▸ salamander  [4049]   +
な/ˈsæləˌmændə/   +

【N-COUNT】   A _salamander_ is an animal that looks rather like a lizard, and that can live both on land and in water. 蝾螈   +

---


==== ▸ spill  [4050]   +
な/spɪl/   +

【V-T/V-I】   If a liquid _spills_ or if you _spill_ it, it accidentally flows over the edge of a container. 无意洒落; 意外溢出   +
⇒  Seventy thousand tons of oil spilled from the tanker.  7万吨油从油轮漏出。   +
⇒  He always spilled the drinks.  他总是不小心把饮料给洒了。   +

【N-COUNT】   A _spill_ is an amount of liquid that has spilled from a container. 洒落的液体   +
⇒  She wiped a spill of milkshake off the counter.  她擦掉柜台上洒落的奶昔。   +

【N】   a splinter of wood or strip of twisted paper with which pipes, fires, etc, are lit (点烟、点火用的)木头碎片或废纸   +

【V-T/V-I】   If the contents of a bag, box, or other container _spill_ or _are spilled_, they come out of the container onto a surface. 使散落; 散落   +
⇒  A number of bags had split and were spilling their contents.  许多包裂开了，里面的东西正在散落出来。   +

【V-I】   If people or things _spill_ out of a place, they come out of it in large numbers. 涌出   +
⇒  Tears began to spill out of the boy's eyes.  泪水开始从男孩的眼里涌出。   +

---


==== ▸ miserable  [4051]   +
な/ˈmɪzərəbəl/   +

【ADJ】   If you are _miserable_, you are very unhappy. 痛苦的   +
⇒  I took a series of badly paid secretarial jobs which made me really miserable.  我连着干了几份工资很低的秘书工作，这让我感到真的很痛苦。   +

【ADV】   痛苦地   +
⇒  He looked miserably down at his plate.  他痛苦地低头看着自己的盘子。   +

【ADJ】   If you describe a place or situation as _miserable_, you mean that it makes you feel unhappy or depressed. 令人忧伤的   +
⇒  There was nothing at all in this miserable place to distract him.  在这个令人忧伤的地方，根本没什么东西可以转移他的注意力。   +

【ADJ】   If you describe the weather as _miserable_, you mean that it makes you feel depressed, because it is raining or dull. 阴冷多雨的   +
⇒  On a grey, wet, miserable day our teams congregated in Port Townsend.  在灰暗、潮湿而又阴冷的一天，我们几队人聚集在了汤森港。   +

【ADJ】   If you describe someone as _miserable_, you mean that you do not like them because they are bad-tempered or unfriendly. 脾气不好的; 不友好的   +
⇒  He always was a miserable man. He never spoke to me nor anybody else, not even to pass the time of day.  他总是不友好。他从不和我说话，也不和别人说话，那怕是为了打发时光。   +

【ADJ】   You can describe a quantity or quality as _miserable_ when you think that it is much smaller or worse than it ought to be. 少得可怜的   +
⇒  Our speed over the ground was a miserable 2.2 knots.  我们在地面上的速度只有区区的2.2节。   +

【ADV】   少得可怜地   +
⇒  ...the miserably inadequate supply of books now provided for schools.  …现在提供给学校的书籍少得可怜。   +

【ADJ】   A _miserable_ failure is a very great one. 惨痛的   +
⇒  The film was a miserable commercial failure both in Italy and in the United States.  这部电影在意大利和美国票房收入都遭到了惨败。   +

【ADV】   悲惨地   +
⇒  Some manage it. Some fail miserably.  有人成功了。有些人败得很惨。   +

---


==== ▸ poster  [4052]   +
な/ˈpəʊstə/   +

【N-COUNT】   A _poster_ is a large notice or picture that you stick on a wall or board, often in order to advertise something. 海报; 招贴   +
⇒  I had seen the poster for the jazz festival in Monterey.  我已经见到了蒙特雷爵士音乐节的海报。   +

---


==== ▸ affluent  [4053]   +
な/ˈæflʊənt/   +

【ADJ】   If you are _affluent_, you have a lot of money. 富裕的   +
⇒  Cigarette smoking used to be more common among affluent people.  吸烟过去在富人中更为普遍。   +

【N-PLURAL】  _The affluent_ are people who are affluent. 富人   +
⇒  The diet of the affluent has not changed much over the decades.  富人的饮食数十年来没怎么变。   +

---


==== ▸ enrich  [4054]   +
な/ɪnˈrɪtʃ/   +

【V-T】   To _enrich_ something means to improve its quality, usually by adding something to it. 充实; 丰富   +
⇒  It is important to enrich the soil prior to planting.  栽种之前给土壤施肥很重要。   +

【V-T】   To _enrich_ someone means to increase the amount of money that they have. 使富裕   +
⇒  He will drain, rather than enrich, the country.  他将耗尽而不是增加国家的财富。   +

---


==== ▸ nostalgia  [4055]   +
な/nɒˈstældʒə/   +

【N-UNCOUNT】  _Nostalgia_ is an affectionate feeling you have for the past, especially for a particularly happy time. (尤指对幸福时光的) 怀旧   +
⇒  He might be influenced by nostalgia for the surroundings of his happy youth.  他也许被他对快乐青年时代的环境的怀念影响了。   +

---


==== ▸ apprise  [4056]   +
な/əˈpraɪz/   +

【V-T】   When you _are apprised of_ something, someone tells you about it. 告知; 通知   +
⇒  Have customers been fully apprised of the advantages?  客户有没有被充分告知各项好处呢？   +
⇒  We must apprise them of the dangers that may be involved.  我们必须把各种潜在危险告诉他们。   +

---


==== ▸ multiply  [4057]   +
な/ˈmʌltɪˌplaɪ/   +

【V-T/V-I】   When something _multiplies_ or when you _multiply_ it, it increases greatly in number or amount. 使大大增加; 大大增加   +
⇒  Such disputes multiplied in the eighteenth and nineteenth centuries.  此类争论在18世纪和19世纪大大增加。   +

【V-I】   When animals and insects _multiply_, they increase in number by giving birth to large numbers of young. 大量繁殖   +
⇒  These creatures can multiply quickly.  这些生物能迅速大量繁殖。   +

【V-T】   If you _multiply_ one number by another, you add the first number to itself as many times as is indicated by the second number. For example 2 multiplied by 3 is equal to 6. 乘   +
⇒  What do you get if you multiply six by nine?  6乘以9得多少？   +

---


==== ▸ costume  [4058]   +
な/ˈkɒstjuːm/   +

【N-VAR】   An actor's or performer's _costume_ is the set of clothes they wear while they are performing. 戏装   +
⇒  Even from a distance, the effect of his fox costume was stunning.  即使从远处看，他的狐装造型也非常漂亮。   +
⇒  The performers, in costume and makeup, were walking up and down backstage.  演员们穿着戏服化着妆，在后台走来走去。   +

【N-UNCOUNT】   The clothes worn by people at a particular time in history, or in a particular country, are referred to as a particular type of _costume_. (某一历史时期或某一国家人们穿的) 服装   +
⇒  ...men and women in eighteenth-century costume.  …身着18世纪服装的男男女女。   +

【ADJ】   A _costume_ drama is one which is set in the past and in which the actors wear the type of clothes that were worn in that period. 古装的   +
⇒  ...a lavish costume drama set in Ireland and the U.S. in the 1890s.  …以19世纪90年代的爱尔兰和美国为背景的一部大型古装戏。   +

---


==== ▸ therapy  [4059]   +
な/ˈθɛrəpɪ/   +

【N-UNCOUNT】  _Therapy_ is the process or talking to a trained counsellor about your emotional and mental problems and your relationships in order to understand and improve the way you feel and behave. 心理治疗   +
⇒  Children may need therapy to help them deal with grief and death.  孩子可能需要心理治疗来帮助他们应对悲伤和死亡。   +
⇒  Since I've been in therapy, I've grown to be a better husband and father.  自从我接受心理治疗后，我成了个更称职的丈夫和父亲。   +

【N-VAR】  _Therapy_ or a _therapy_ is a treatment for a particular illness or condition. (针对某种病情的) 治疗   +
⇒  ...hormonal therapies.  …激素疗法。   +

---


==== ▸ relevance  [4060]   +
な/ˈrɛləvəns/   +

【N-UNCOUNT】   Something's _relevance to_ a situation or person is its importance or significance in that situation or to that person. 相关性   +
⇒  Politicians' private lives have no relevance to their public roles.  政治家的私生活与他们的公众角色没有相关性。   +

---


==== ▸ pathology  [4061]   +
な/pəˈθɒlədʒɪ/   +

【N-UNCOUNT】  _Pathology_ is the study of the way diseases and illnesses develop. 病理学   +

---


==== ▸ revise  [4062]   +
な/rɪˈvaɪz/   +

【V-T】   If you _revise_ the way you think about something, you adjust your thoughts, usually in order to make them better or more suited to how things are. 修正 (对某事的想法)   +
⇒  With time he came to revise his opinion of the profession.  随着时间的推移，他开始修正自己对这一职业的看法。   +

【V-T】   If you _revise_ a price, amount, or estimate, you change it to make it more fair, realistic, or accurate. 调整 (使更合理、实际、准确)   +
⇒  They realized that some of their prices were higher than their competitors' and revised prices accordingly.  他们意识到他们的部分价格比竞争对手的高，就相应地调整了价格。   +

【V-T】   When you _revise_ an article, a book, a law, or a piece of music, you change it in order to improve it, make it more modern, or make it more suitable for a particular purpose. 修改; 修订 (使改进、更时尚、更适于某目的)   +
⇒  Three editors handled the work of revising the articles for publication.  3名编辑负责对要出版的文章进行修订的工作。   +

【V-I】   When you _revise for_ an examination, you read things again and make notes in order to be prepared for the examination. (为考试) 复习   +
⇒  Revising for exams gives you a chance to bring together all the individual parts of the course.  考前复习给你一个把课程各独立部分融会贯通的机会。   +
⇒  Review all the notes you need to cover for each course.  复习所有你需要涵盖的每门课的笔记。   +

---


==== ▸ promote  [4063]   +
な/prəˈməʊt/   +

【V-T】   If people _promote_ something, they help or encourage it to happen, increase, or spread. 促进   +
⇒  You don't have to sacrifice environmental protection to promote economic growth.  你们没有必要牺牲环保来促进经济增长。   +

【N-UNCOUNT】   促进   +
⇒  The government has pledged to give the promotion of democracy higher priority.  政府已承诺要给民主的促进以更高的优先级。   +

【V-T】   If a firm _promotes_ a product, it tries to increase the sales or popularity of that product. 促销   +
⇒  ...a tour to promote his second solo album.  …一场促销他第二张个人专辑的巡回演出。   +

【V-T】   If someone _is promoted_, they are given a more important job or rank in the organization that they work for. 晋升   +
⇒  I was promoted to editor and then editorial director.  我晋升为编辑，之后又晋升为编辑部主任。   +

---


==== ▸ halt  [4064]   +
な/hɔːlt/   +

【V-T/V-I】   When a person or a vehicle _halts_ or when something _halts_ them, they stop moving in the direction they were going and stand still. 使停住; 停住   +
⇒  They halted at a short distance from the house.  他们停在离房子不远处。   +

【V-T/V-I】   When something such as growth, development, or activity _halts_ or when you _halt_ it, it stops completely. 使完全停止; 完全停止   +
⇒  Striking workers halted production at the auto plant yesterday.  昨天，汽车厂的罢工工人完全停止了生产。   +

【V】   (esp of logic or verse) to falter or be defective (尤指逻辑或诗韵)有缺陷; 不流畅   +

【N】   an interruption or end to activity, movement, or progress (活动、运动或进展的)中止; 终止   +

【N】   lameness 跛; 瘸   +

【ADJ】   lame 跛的; 瘸的   +

【ADJ】   (_as collective noun;_ preceded by _the_) (用作集体名词，前面加)the   +
⇒  the halt     +

【PHRASE】   If someone _calls a halt to_ something such as an activity, they decide not to continue with it or to end it immediately. 决定停止   +
⇒  The Russian government had called a halt to the construction of a new project in the Rostov region.  俄罗斯政府已经决定停止在罗斯托夫地区的一个新工程的修建。   +

【PHRASE】   If someone or something comes _to a halt_, they stop moving. 停止移动   +
⇒  The lift creaked to a halt at the ground floor.  电梯嘎吱一声停在了底楼。   +

【PHRASE】   If something such as growth, development, or activity _comes_ or _grinds to a halt_ or _is brought to a halt_, it stops completely. 完全停止   +
⇒  Her political career came to a halt in December 1988.  她的政治生涯于1988年12月彻底结束了。   +

---


==== ▸ nurture  [4065]   +
な/ˈnɜːtʃə/   +

【V-T】   If you _nurture_ something such as a young child or a young plant, you care for it while it is growing and developing. 养育   +
⇒  Parents want to know the best way to nurture and raise their child to adulthood.  父母们想了解把他们的孩子养育成人的最好方法。   +

【V-T】   If you _nurture_ plans, ideas, or people, you encourage them or help them to develop. 培养   +
⇒  She had always nurtured great ambitions for her son.  她一直在培养她儿子的雄心大志。   +
⇒  ...parents whose political views were nurtured in the sixties.  …政治观点形成于60年代的父母们。   +

【N-UNCOUNT】  _Nurture_ is care and encouragement that is given to someone while they are growing and developing. 培育   +
⇒  The human organism learns partly by nature, partly by nurture.  人的学习能力部分是先天的，部分是后天培育的。   +

---


==== ▸ soybean  [4066]   +
な/ˈsɔɪˌbiːn/   +

【N-COUNT】  _Soybeans_ are the same as _soya beans_. 同soya beans   +

---


==== ▸ adjoin  [4067]   +
な/əˈdʒɔɪn/   +

【V-T】   If one room, place, or object _adjoins_ another, they are next to each other. 紧邻   +
⇒  The doctor's bedroom adjoined his wife's and the door between the rooms was always open.  这位医生的卧室紧邻他妻子的卧室，两间房之间的门总是开着的。   +

---


==== ▸ extremity  [4068]   +
な/ɪkˈstrɛmɪtɪ/   +

【N-COUNT】   The _extremity_ of something is its farthest end or edge. 尽头; 末端   +
⇒  ...a small port on the north-western extremity of the Iberian peninsula.  ...一个位于伊比利亚半岛最西北端的小港口。   +
⇒  ...the extremities of the aeroplane.  ...飞机的两端。   +

【N-PLURAL】   Your _extremities_ are the end parts of your body, especially your hands and feet. 身体末梢   +
⇒  He found that his extremities grew cold.  他发现他的手脚变冷了。   +

【N-UNCOUNT】   The _extremity of_ a situation or _of_ someone's behaviour is the degree to which it is severe, unusual, or unacceptable. 极端   +
⇒  In spite of the extremity of her seclusion she was sane.  尽管完全与世隔绝，她依然神智清醒。   +
⇒  In the past, the region had been protected by its forbidding geography and the extremities of its climate.  过去，这个地区受到令人生畏的地理条件和极端的天气状况的保护。   +

---


==== ▸ reinforce  [4069]   +
な/ˌriːɪnˈfɔːs/   +

【V-T】   If something _reinforces_ a feeling, situation, or process, it makes it stronger or more intense. 加强   +
⇒  I hope this will reinforce Indonesian determination to deal with this kind of threat.  我希望这会加强印度尼西亚对付这类威胁的决心。   +

【V-T】   If something _reinforces_ an idea or point of view, it provides more evidence or support for it. 巩固   +
⇒  The delegation hopes to reinforce the idea that human rights are not purely internal matters.  代表团希望巩固人权不完全是国家内政的观念。   +

【V-T】   To _reinforce_ an object means to make it stronger or harder. 加固   +
⇒  Eventually, they had to reinforce the walls with exterior beams.  最后，他们不得不用外梁来加固那些墙壁。   +

【V-T】   To _reinforce_ an army or a police force means to make it stronger by increasing its size or providing it with more weapons. To _reinforce_ a position or place means to make it stronger by sending more soldiers or weapons. 增援   +
⇒  Both sides have been reinforcing their positions after yesterday's fierce fighting.  在昨天的激战后，双方一直在增援各自的阵地。   +

---


==== ▸ secede  [4070]   +
な/sɪˈsiːd/   +

【V-I】   If a region or group _secedes from_ the country or larger group to which it belongs, it formally becomes a separate country or stops being a member of the larger group. (从国家或大集团中正式)脱离   +
⇒  Singapore seceded from the Federation of Malaysia and became an independent sovereign state.  新加坡脱离马来西亚联邦成为一个独立的主权国家。   +
⇒  Ukraine decided to secede.  乌克兰决定独立出来。   +

---


==== ▸ float  [4071]   +
な/fləʊt/   +

【V-T/V-I】   If something or someone _is floating_ in a liquid, they are in the liquid, on or just below the surface, and are being supported by it. You can also _float_ something on a liquid. 漂浮   +
⇒  They noticed fifty and twenty dollar bills floating in the water.  他们注意到水中漂浮着一些50和20美元的纸币。   +
⇒  It's below freezing and small icebergs are floating by.  气温在冰点以下，一座座小冰山正漂过。   +

【V-I】   Something that _floats_ lies on or just below the surface of a liquid when it is put in it and does not sink. (在水面或水中) 漂浮   +
⇒  They will also float if you drop them in the water.  如果你把它们丢进水里，它们也会浮起来。   +

【V-I】   Something that _floats_ in or through the air hangs in it or moves slowly and gently through it. (在空中) 飘浮   +
⇒  The white cloud of smoke floated away.  那团白色的烟雾飘走了。   +

【V-T】   If you _float_ a project, plan, or idea, you suggest it for others to think about. 提出   +
⇒  The French had floated the idea of placing the diplomatic work in the hands of the UN.  法国人提出了将外交工作交由联合国处理的意见。   +

【V-T】   If a company director _floats_ their company, they start to sell shares in it to the public. 使 (公司) 上市   +
⇒  He floated his firm on the stock market.  他让自己的公司上市了。   +

【V-T/V-I】   If a government _floats_ its country's currency or allows it to _float_, it allows the currency's value to change freely in relation to other currencies. 使 (货币) 自由浮动   +
⇒  On January 15th Brazil was forced to float its currency.  1月15日巴西被迫让其货币自由浮动。   +

【N-COUNT】   A _float_ is a light object that is used to help someone or something float. 救生圈   +
⇒  Floats will provide confidence in the water.  救生圈可以增强在水中的信心。   +

【N-COUNT】   A _float_ is a small object attached to a fishing line which floats on the water and moves when a fish has been caught. 浮子; 鱼漂   +

【N-COUNT】   A _float_ is a truck on which displays and people in special costumes are carried in a parade. 游行彩车   +
⇒  ...a procession of makeshift floats bearing loudspeakers and banners.  …临时代用的装有高音喇叭、挂有横幅的游行彩车队列。   +

---


==== ▸ dwindle  [4072]   +
な/ˈdwɪndəl/   +

【V-I】   If something _dwindles_, it becomes smaller, weaker, or less in number. 缩小; 减少   +
⇒  The factory's workforce has dwindled from over 4,000 to a few hundred.  该厂的工人总数已从4000多减少到了几百人。   +

---


==== ▸ legislate  [4073]   +
な/ˈlɛdʒɪsˌleɪt/   +

【V-T/V-I】   When a government or state _legislates_, it passes a new law. 通过 (法律); 立法   +
⇒  Most member countries have already legislated against excessive overtime.  大部分成员国已经立法禁止过度加班。   +
⇒  You cannot legislate to change attitudes.  你不能靠立法来让人们改变态度。   +

---


==== ▸ gorgeous  [4074]   +
な/ˈɡɔːdʒəs/   +

【ADJ】   If you say that something is _gorgeous_, you mean that it gives you a lot of pleasure or is very attractive. 十分宜人的; 很吸引人的   +
⇒  ...gorgeous mountain scenery.  …壮观的山间景色。   +
⇒  It's a gorgeous day.  今天天气真棒。   +

【ADJ】   If you describe someone as _gorgeous_, you mean that you find them very sexually attractive. (人) 很性感的   +
⇒  The cosmetics industry uses gorgeous women to sell its skincare products.  化妆品行业用很性感的女人来推销护肤品。   +

---


==== ▸ image  [4075]   +
な/ˈɪmɪdʒ/   +

【N-COUNT】   If you have an _image_ of something or someone, you have a picture or idea of them in your mind. (头脑里的) 形象; 概念   +
⇒  The image of art theft as a gentleman's crime is outdated.  艺术品盗窃是绅士犯罪这一观念已经过时了。   +

【N-COUNT】   The _image_ of a person, group, or organization is the way that they appear to other people. (个人、团体或组织的) 形象   +
⇒  ...the government's negative public image.  …政府负面的公众形象。   +

【N-COUNT】   An _image_ is a picture of someone or something. 画像   +
⇒  ...photographic images of young children.  …小孩子们的摄影图像。   +

【N-COUNT】   An _image_ is a poetic description of something. 生动的描绘   +
⇒  The natural images in the poem are meant to be suggestive of realities beyond themselves.  诗中自然景象的描写意在使人联想起那以外的现实。   +

【PHRASE】   If you _are the image of_ someone else, you look very much like them. 酷似某人   +
⇒  Marianne's son was the image of his father.  玛丽安娜的儿子酷似他的父亲。   +

---


==== ▸ loose  [4076]   +
な/luːs/   +

【ADJ】   Something that is _loose_ is not firmly held or fixed in place. 松的   +
⇒  If a tooth feels very loose, your dentist may recommend that it's taken out.  如果有颗牙齿非常松动，你的牙医可能会建议拔掉它。   +
⇒  Two wooden beams had come loose from the ceiling.  天花板上的两根木梁松动了。   +

【ADV】   松松地   +
⇒  Tim clasped his hands together and held them loosely in front of his belly.  蒂姆十指交叉搭在腹前。   +

【ADJ】   Something that is _loose_ is not attached to anything, or held or contained in anything. 零散的   +
⇒  Frank emptied a handful of loose change on the table.  弗兰克将一把零钱全部放在了桌子上。   +

【ADJ】   If people or animals break _loose_ or are set _loose_, they are no longer held, tied, or kept somewhere and can move around freely. 自由的   +
⇒  She broke loose from his embrace and crossed to the window.  她从他的拥抱中挣脱出来，穿过房间走到窗边。   +

【ADJ】   Clothes that are _loose_ are somewhat large and do not fit closely. 宽松的   +
⇒  A pistol wasn't that hard to hide under a loose shirt.  把一支手枪藏在宽松的衬衣里面并没那么难。   +

【ADV】   宽松地   +
⇒  His shirt hung loosely over his thin shoulders.  他的衬衣松松垮垮地挂在他瘦削的双肩上。   +

【ADJ】   If your hair is _loose_, it hangs freely around your shoulders and is not tied back. 披散的   +
⇒  She was still in her nightgown, with her hair hanging loose over her shoulders.  她仍穿着睡衣，头发披散在肩上。   +

【ADJ】   A _loose_ grouping, arrangement, or organization is flexible rather than strictly controlled or organized. 松散的 (分组、安排、组织)   +
⇒  Murray and Alison came to some sort of loose arrangement before he went home.  在他回家之前，默里和艾莉森做了些松散的安排。   +

【ADV】   松散地   +
⇒  The investigation had aimed at a loosely organized group of criminals.  该调查曾是针对一群组织松散的罪犯的。   +

【PHRASE】   If a person or an animal is _on the loose_, they are free because they have escaped from a person or place. 在逃; 行动自由   +
⇒  Up to a thousand prisoners may be on the loose inside the jail.  多达一千名的囚犯可能在监狱里行动自由。   +

---


==== ▸ literary  [4077]   +
な/ˈlɪtərərɪ/   +

【ADJ】  _Literary_ means concerned with or connected with the writing, study, or appreciation of literature. 文学的   +
⇒  Her literary criticism focuses on the way great literature suggests ideas.  她的文学批评集中于伟大文学作品表达思想的方法。   +
⇒  She's the literary editor of the "Sunday Review."  她是《周日评论》的文学编辑。   +

【ADJ】  _Literary_ words and expressions are often unusual in some way and are used to create a special effect in a piece of writing such as a poem, speech, or novel. 书面的   +
⇒  ...archaic, literary words from the Tang dynasty.  …唐代的古文书面用词。   +

---


==== ▸ myriad  [4078]   +
な/ˈmɪrɪəd/   +

【QUANT】  _A myriad_ or _myriads of_ people or things is a very large number or great variety of them. 大量; 各种各样   +
⇒  They face a myriad of problems bringing up children.  他们在抚养孩子上面临着各种问题。   +

【ADJ】  _Myriad_ means having a large number or great variety. 大量的; 各种各样的   +
⇒  The magazine has been celebrating pop in all its myriad forms.  该杂志一直在赞美各种形式的流行音乐。   +

---


==== ▸ restraint  [4079]   +
な/rɪˈstreɪnt/   +

【N-VAR】  _Restraints_ are rules or conditions that limit or restrict someone or something. 限制   +
⇒  The president is calling for spending restraints in some areas.  该总统要求在一些领域限制开支。   +

【N-UNCOUNT】  _Restraint_ is calm, controlled, and unemotional behaviour. 克制   +
⇒  They behaved with more restraint than I'd expected.  他们表现了比我预想还多的克制。   +

---


==== ▸ lava  [4080]   +
な/ˈlɑːvə/   +

【N-MASS】  _Lava_ is the very hot liquid rock that comes out of a volcano. 熔岩   +
⇒  Mexico's Mount Colima began spewing lava and ash last night.  墨西哥科利马山昨晚开始喷发熔岩和火山灰。   +

---


==== ▸ series  [4081]   +
な/ˈsɪəriːz/   +

【N-COUNT】   A _series of_ things or events is a number of them that come one after the other. 一连串; 一系列   +
⇒  ...a series of meetings with students and political leaders.  …与学生和政治领袖们的一连串会晤。   +

【N-COUNT】   A radio or television _series_ is a set of programs of a particular kind which have the same title. (广播或电视的) 系列节目   +
⇒  ...Captain Kirk's chair from the TV series "Star Trek."  …电视系列片《星际迷航》中柯克船长的椅子。   +

---


==== ▸ priority  [4082]   +
な/praɪˈɒrɪtɪ/   +

【N-COUNT】   If something is a _priority_, it is the most important thing you have to do or deal with, or must be done or dealt with before everything else you have to do. 优先处理的事   +
⇒  Being a parent is her first priority.  做母亲是她的头等大事。   +
⇒  The government's priority is to build more power plants.  政府的当务之急是建造更多的发电厂。   +

【PHRASE】   If you _give priority to_ something or someone, you treat them as more important than anything or anyone else. 优先考虑   +
⇒  Women are more likely to give priority to child care and education policies.  女性更可能给孩子的照料和教育方案以优先考虑。   +

【PHRASE】   If something _takes priority_ or _has priority over_ other things, it is regarded as being more important than them and is dealt with first. 有优先性   +
⇒  The fight against inflation took priority over measures to combat the deepening recession.  对抗通货膨胀的斗争比对抗日益加深的经济衰退措施更具优先性。   +

---


==== ▸ transact  [4083]   +
な/trænˈzækt/   +

【V-T】   If you _transact_ business, you enter into a deal with someone, for example, by buying or selling something. 交易   +
⇒  This would free them to transact business across state lines.  这会使他们自由地跨越州界进行商业交易。   +

---


==== ▸ stress  [4084]   +
な/strɛs/   +

【V-T】   If you _stress_ a point in a discussion, you put extra emphasis on it because you think it is important. 强调   +
⇒  The spokesman stressed that the measures did not amount to an overall ban.  发言人强调说，这些措施并不等于全面禁止。   +
⇒  China's leaders have stressed the need for increased co-operation between Third World countries.  中国领导人已经强调了增进第三世界国家之间合作的需要。   +

【N-VAR】  _Stress_ is also a noun. 重点   +
⇒  Japanese car makers are laying ever more stress on overseas sales.  日本的汽车制造商们把更多的重点放在海外销售上。   +

【N-VAR】   If you feel under _stress_, you feel worried and tense because of difficulties in your life. 精神压力   +
⇒  Katy could think clearly when not under stress.  凯泰在没有精神压力时能够清晰地思考。   +

【V-T】   If you _stress_ a word or part of a word when you say it, you put emphasis on it so that it sounds slightly louder. 重读   +
⇒  She stresses the syllables as though teaching a child.  她重读这些音节，像教小孩似的。   +

【N-VAR】  _Stress_ is also a noun. 重读   +
⇒  ...the misplaced stress on the first syllable of this last word.  …这个最末单词的第1个音节上的重读错误。   +

---


==== ▸ desolate  [4085]   +
な/ˈdɛsəlɪt/   +

【ADJ】   A _desolate_ place is empty of people and lacking in comfort. 荒凉的   +
⇒  ...a desolate landscape of flat green fields.  …一片荒凉平坦的绿地景观。   +

【ADJ】   If someone is _desolate_, they feel very sad, alone, and without hope. 感到凄凉的   +
⇒  He was desolate without her.  没有她，他感到很凄凉。   +

---


==== ▸ balm  [4086]   +
な/bɑːm/   +

【N-MASS】  _Balm_ is a sweet-smelling oil that is obtained from some tropical trees and used to make creams that heal wounds or reduce pain. (做疗伤或镇痛药膏的) 香树油   +
⇒  ...a jar of lip balm.  …一罐唇膏。   +

【N-UNCOUNT】   If you refer to something as _balm_, you mean that it makes you feel better. 慰藉物   +
⇒  The place is balm to the soul.  这个地方是对心灵的抚慰。   +

---


==== ▸ sauce  [4087]   +
な/sɔːs/   +

【N-MASS】   A _sauce_ is a thick liquid which is served with other food. 酱; 调味汁   +
⇒  ...pasta cooked in a sauce of garlic, tomatoes, and cheese.  …用大蒜、番茄和奶酪调味汁煮的意大利面。   +

---


==== ▸ controversy  [4088]   +
な/ˈkɒntrəˌvɜːsɪ/   +

【N-VAR】  _Controversy_ is a lot of discussion and argument about something, often involving strong feelings of anger or disapproval. 论战   +
⇒  The proposed cuts have caused considerable controversy.  削减的提议引起了巨大的争议。   +

---


==== ▸ external  [4089]   +
な/ɪkˈstɜːnəl/   +

【ADJ】  _External_ is used to indicate that something is on the outside of a surface or body, or that it exists, happens, or comes from outside. 外部的; 外来的; 外在的   +
⇒  ...a much reduced heat loss through external walls.  …透过外墙的大大减少的热量损失。   +

【ADV】   外部地; 外来地; 外在地   +
⇒  Vitamins can be applied externally to the skin.  维他命可以外用于皮肤上。   +

【ADJ】  _External_ means involving or intended for foreign countries. 涉外的; 对外的   +
⇒  ...the commissioner for external affairs.  …外事专员。   +
⇒  ...Jamaica's external debt.  …牙买加的外债。   +

【ADV】   涉外地; 对外地   +
⇒  ...protecting the value of the dollar both internally and externally.  …保护美元在国内外的价值。   +

【ADJ】  _External_ means happening or existing in the world in general and affecting you in some way. 外界的   +
⇒  Such events occur only when the external conditions are favourable.  此类事件只有当外界条件有利时才会发生。   +

---


==== ▸ database  [4090]   +
な/ˈdeɪtəˌbeɪs/   +

【N-COUNT】   A _database_ is a collection of data that is stored in a computer and that can easily be used and added to. 数据库   +
⇒  The state maintains a database of names of people allowed to vote.  该州有一个可以投票的人的姓名数据库。   +

---


==== ▸ sharpen  [4091]   +
な/ˈʃɑːpən/   +

【V-T/V-I】   If your senses, understanding, or skills _sharpen_ or _are sharpened_, you become better at noticing things, thinking, or doing something. 使敏锐; 增强   +
⇒  Her gaze sharpened, as if she had seen something unusual.  她眼睛一亮，好像看到了不寻常的东西。   +
⇒  He will need to sharpen his diplomatic skills in order to work with Congress.  他将需要增强外交技巧以与国会打交道。   +

【V-T】   If you _sharpen_ an object, you make its edge very thin or you make its end pointed. 使变锋利; 弄尖   +
⇒  He started to sharpen his knife.  他开始磨刀。   +

---


==== ▸ assimilation  [4092]   +
 辞典中没找到  +
==== ▸ dilate  [4093]   +
な/daɪˈleɪt/   +

【V-T/V-I】   When things such as blood vessels or the pupils of your eyes _dilate_ or when something _dilates_ them, they become wider or bigger. 使扩大; 扩大   +
⇒  At night, the pupils dilate to allow in more light.  晚上，瞳孔放大以便让更多的光线射入。   +

【ADJ】   扩大的   +
⇒  His eyes seemed slightly dilated.  他的双眼瞳孔似乎稍微扩大了些。   +

---


==== ▸ entity  [4094]   +
な/ˈɛntɪtɪ/   +

【N-COUNT】   An _entity_ is something that exists separately from other things and has a clear identity of its own. 实体   +
⇒  ...the earth as a living entity.  …作为一个生命实体的地球。   +

---


==== ▸ hatch  [4095]   +
な/hætʃ/   +

【V-T/V-I】   When a baby bird, insect, or other animal _hatches_, or when it _is hatched_, it comes out of its egg by breaking the shell. 使孵出; 孵出   +
⇒  The young disappeared soon after they were hatched.  幼崽孵出后不久就不见了。   +

【V-T/V-I】   When an egg _hatches_ or when a bird, insect, or other animal _hatches_ an egg, the egg breaks open and a baby comes out. 孵化   +
⇒  The eggs hatch after a week or ten days.  这些蛋1周或10天后孵化。   +

【V-T】   If you _hatch_ a plot or a scheme, you think of it and work it out. 策划   +
⇒  He has accused opposition parties of hatching a plot to assassinate the pope.  他曾指责各反对党阴谋策划暗杀教皇。   +

【V-T】   to mark (a figure, shade, etc) with fine parallel or crossed lines to indicate shading 在(图形、投影等上)画影线   +

【N-COUNT】   A _hatch_ is an opening in the deck of a ship, through which people or cargo can go. You can also refer to the door of this opening as a _hatch_. 舱口; 舱口盖   +
⇒  He stuck his head up through the hatch.  他把脑袋伸出舱口。   +

【N】   the act or process of hatching 孵化   +

【N】   hatchback的缩写   +

---


==== ▸ cohesive  [4096]   +
な/kəʊˈhiːsɪv/   +

【ADJ】   Something that is _cohesive_ consists of parts that fit together well and form a united whole. 有聚合力的   +
⇒  "Daring Adventures" from '86 is a far more cohesive and successful album.  1986年出的《勇敢的冒险》是一张极富凝聚力、极成功的唱片集。   +

---


==== ▸ moss  [4097]   +
な/mɒs/   +

【N-MASS】  _Moss_ is a very small, soft, green plant which grows on damp soil, or on wood or stone. 青苔   +
⇒  ...ground covered over with moss.  …长满青苔的地面。   +

---


==== ▸ boon  [4098]   +
な/buːn/   +

【N-COUNT】   You can describe something as a _boon_ when it makes life better or easier for someone. 福音   +
⇒  It is for this reason that television proves such a boon to so many people.  正是这个原因电视机成为这么多人的一大福音。   +

【ADJ】   close, special, or intimate (in the phrase _boon companion_) 亲密的; 特别的   +

---


==== ▸ rancher  [4099]   +
な/ˈrɑːntʃə/   +

【N-COUNT】   A _rancher_ is someone who owns or manages a large farm, especially one used for raising cattle, horses, or sheep. 农场主   +
⇒  ...a cattle rancher.  ...一位养牛场场主。   +

---


==== ▸ plague  [4100]   +
な/pleɪɡ/   +

【N-UNCOUNT】  _Plague_ or _the plague_ is a very infectious disease that usually results in death. The patient has a severe fever and swellings on his or her body. 瘟疫   +
⇒  ...a fresh outbreak of plague.  …瘟疫的新一轮爆发。   +

【N-COUNT】   A _plague of_ unpleasant things is a large number of them that arrive or happen at the same time. 泛滥   +
⇒  The city is under threat from a plague of rats.  这座城市面临着鼠患的威胁。   +

【V-T】   If you _are plagued by_ unpleasant things, they continually cause you a lot of trouble or suffering. 使困扰   +
⇒  She was plagued by weakness, fatigue, and dizziness.  她被虚弱、疲劳和眩晕折磨。   +

---


==== ▸ glorify  [4101]   +
な/ˈɡlɔːrɪˌfaɪ/   +

【V-T】   To _glorify_ something means to praise it or make it seem good or special, usually when it is not. 美化   +
⇒  This magazine in no way glorifies gangs.  本杂志决不美化各种犯罪团伙。   +

【N-UNCOUNT】   美化   +
⇒  ...the glorification of violence.  …对暴力的美化。   +

---


==== ▸ autonomy  [4102]   +
な/ɔːˈtɒnəmɪ/   +

【N-UNCOUNT】  _Autonomy_ is the control or government of a country, organization, or group by itself rather than by others. 自治   +
⇒  Activists stepped up their demands for local autonomy last month.  活动的积极分子上个月提高了其对地方自治的要求。   +

【N-UNCOUNT】  _Autonomy_ is the ability to make your own decisions about what to do rather than being influenced by someone else or told what to do. 独立自主   +
⇒  Each of the area managers enjoys considerable autonomy in the running of his own area.  每一位地区经理在各自主管的区域都享有相当大的自主权。   +

---


==== ▸ creep  [4103]   +
な/kriːp/   +

【V-I】   When people or animals _creep_ somewhere, they move quietly and slowly. 悄悄地缓慢行进   +
⇒  Back I go to the hotel and creep up to my room.  我回到旅馆，蹑手蹑脚地进了房间。   +

【V-I】   If something _creeps_ somewhere, it moves very slowly. 渐渐蔓延   +
⇒  Mist had crept in again from the sea.  大雾再次从海上渐渐蔓延过来。   +

【V-I】   If something _creeps_ in or _creeps_ back, it begins to occur or becomes part of something without people realizing or without them wanting it. 悄悄出现   +
⇒  Insecurity might creep in.  不安全感可能会悄然而生。   +
⇒  An increasing ratio of mistakes, perhaps induced by tiredness, crept into her game.  可能是因为疲劳，她在比赛中的错误率不知不觉地升高了。   +

【V-I】   If a rate or number _creeps up_ to a higher level, it gradually reaches that level. 攀升   +
⇒  The inflation rate has been creeping up to 9.5 per cent.  通货膨胀率已攀升至9.5％。   +

---


==== ▸ pinch  [4104]   +
な/pɪntʃ/   +

【V-T】   If you _pinch_ a part of someone's body, you take a piece of their skin between your thumb and first finger and give it a short squeeze. 掐; 拧   +
⇒  She pinched his arm as hard as she could.  她使出全力拧他的胳膊。   +

【N-COUNT】  _Pinch_ is also a noun. 掐; 拧   +
⇒  She gave him a little pinch.  她轻轻地拧了他一下。   +

【N-COUNT】   A _pinch of_ an ingredient such as salt is the amount of it that you can hold between your thumb and your first finger. 撮   +
⇒  Put all the ingredients, including a pinch of salt, into a food processor.  将所有的配料，连同一撮盐，放进食品加工机里。   +

【V-T】   To _pinch_ something, especially something of little value, means to steal it. 偷拿 (尤为不太值钱的东西)   +
⇒  Do you remember when I pinched your glasses?  你还记得我偷拿过你的眼镜吗？   +

【PHRASE】   If a person or company _is feeling the pinch_, they do not have as much money as they used to, and so they cannot buy the things they would like to buy. 感到手头拮据   +
⇒  Consumers are spending less and merchants are feeling the pinch.  消费者花钱少了，商家感到手头拮据。   +

---


==== ▸ involve  [4105]   +
な/ɪnˈvɒlv/   +

【V-T】   If a situation or activity _involves_ something, that thing is a necessary part or consequence of it. 需要   +
⇒  Running a kitchen involves lots of discipline and speed.  管理厨房需要讲究纪律和速度。   +

【V-T】   If a situation or activity _involves_ someone, they are taking part in it. 涉及   +
⇒  If there was a cover-up, it involved people at the very highest levels of government.  如果有掩盖真相的行为，它就牵扯到了处于政府最高层的那些人。   +

【V-T】   If you say that someone _involves_ themselves _in_ something, you mean that they take part in it, often in a way that is unnecessary or unwanted. 使卷入   +
⇒  I seem to have involved myself in something I don't understand.  我似乎已经将自己卷入了我不了解的事情当中。   +

【V-T】   If you _involve_ someone _in_ something, you get them to take part in it. 使参与   +
⇒  Nasser and I do everything together, he involves me in everything.  纳萨和我做什么事都在一起，他让我参与所有的事情。   +

【V-T】   If one thing _involves_ you _in_ another thing, especially something unpleasant or inconvenient, the first thing causes you to do or deal with the second. 使陷入   +
⇒  I don't want to do anything that will involve me in a long-term commitment.  我不想做任何会使自己做出长期承诺的事情。   +

---


==== ▸ mansion  [4106]   +
な/ˈmænʃən/   +

【N-COUNT】   A _mansion_ is a very large house. 大厦   +
⇒  ...an eighteenth-century mansion in New Hampshire.  …新罕布什尔州一座18世纪的大厦。   +

---


==== ▸ considerate  [4107]   +
な/kənˈsɪdərɪt/   +

【ADJ】   Someone who is _considerate_ pays attention to the needs, wishes, or feelings of other people. 体贴的   +
⇒  I think he's the most charming, most considerate man I've ever known.  我觉得他是我所认识的最有魅力、最体贴的男士。   +

---


==== ▸ confront  [4108]   +
な/kənˈfrʌnt/   +

【V-T】   If you _are confronted with_ a problem, task, or difficulty, you have to deal with it. 面临 (问题、任务、困难等)   +
⇒  She was confronted with severe money problems.  她面临严重的资金问题。   +

【V-T】   If you _confront_ a difficult situation or issue, you accept the fact that it exists and try to deal with it. 正视 (困难局面或问题)   +
⇒  We are learning how to confront death.  我们在学习如何正视死亡。   +

【V-T】   If you _are confronted_ by something that you find threatening or difficult to deal with, it is there in front of you. 面对 (有威胁或难处理的事物)   +
⇒  I was confronted with an array of knobs, levers, and switches.  我面对着一排旋钮、控制杆和开关。   +

【V-T】   If you _confront_ someone, you stand or sit in front of them, especially when you are going to fight, argue, or compete with them. 与 (某人) 对峙 (尤指准备打斗、争论或竞争)   +
⇒  She pushed her way through the mob and confronted him face to face.  她从那群暴民中挤出来，与他当面对峙。   +
⇒  They don't hesitate to open fire when confronted by police.  他们一旦遭遇警察就毫不犹豫地开火。   +

【V-T】   If you _confront_ someone _with_ something, you present facts or evidence to them in order to accuse them of something or force them to deal with a situation. (以某事物) 与 (某人) 对质   +
⇒  She had decided to confront Kathryn with the truth.  她已决定用事实与凯瑟琳对质。   +
⇒  I could not bring myself to confront him about it.  我不能就此事让自己与他对质。   +

---


==== ▸ molecular  [4109]   +
な/məʊˈlɛkjʊlə/   +

【ADJ】  _Molecular_ means relating to or involving molecules. 分子的   +
⇒  ...the molecular structure of fuel.  …燃料的分子结构。   +

---


==== ▸ concern  [4110]   +
な/kənˈsɜːn/   +

【N-UNCOUNT】  _Concern_ is worry about a situation. 担忧   +
⇒  The group has expressed concern about reports of political violence in Africa.  该集团已对有关非洲政治暴力的报道表示担忧。   +
⇒  The move follows growing public concern over the spread of the disease.  该行动是针对公众日益增长的对该疾病传播的担忧而采取的。   +

【V-T】   If something _concerns_ you, it worries you. 使担忧   +
⇒  The growing number of people seeking refuge in Thailand is beginning to concern Western aid agencies.  日益增多的到泰国寻求避难的人数开始让西方援助机构感到担忧。   +

【ADJ】   感到担忧的   +
⇒  Academics and employers are concerned that students are not sufficiently prepared for college courses.  学术界和用人单位都担心学生们对大学课程没有做好足够准备。   +

【V-T】   If you _concern yourself with_ something, you give it attention because you think that it is important. 关心   +
⇒  I didn't concern myself with politics.  我不关心政治。   +

【ADJ】   关心的   +
⇒  The agency is more concerned with making arty ads than understanding its clients' businesses.  这家代理商更关心制作附庸风雅的广告而不是理解其客户的生意。   +

【V-T】   If something such as a book or a piece of information _concerns_ a particular subject, it is about that subject. 有关于   +
⇒  The bulk of the book concerns Sandy's two middle-aged children.  这本书的主要部分讲的是桑迪的两个中年孩子。   +

【ADJ】   有关于…的   +
⇒  Randolph's work was exclusively concerned with the effects of pollution on health.  伦道夫的作品全部讲的是污染对健康的影响。   +

【V-T】   If a situation, event, or activity _concerns_ you, it affects or involves you. (情况、事件、活动等) 与…有关   +
⇒  It was just a little unfinished business from my past, and it doesn't concern you at all.  这只是我过去没有了结的一件小事，完全跟你没关。   +

【ADJ】   有关的   +
⇒  It's a very stressful situation for everyone concerned.  这对所有相关人员来说都是一个非常有压力的情况。   +

【N-COUNT】   A _concern_ is a fact or situation that worries you. 令人担忧的事   +
⇒  His concern was that people would know that he was responsible.  他担忧的是人们会知道他应该负责任。   +

【N-COUNT】   You can refer to a company or business as a _concern_, usually when you are describing what type of company or business it is. 公司; 生意   +
⇒  If not a large concern, the Potomac Nursery was at least a successful one.  虽不是一个大生意，波托马克幼儿园至少是一个成功的公司。   +

【N-VAR】  _Concern__for_ someone is a feeling that you want them to be happy, safe, and well. If you do something out of _concern for_ someone, you do it because you want them to be happy, safe, and well. 关心   +
⇒  Without her care and concern, he had no chance at all.  没有她的照顾和关心，他根本就没有机会。   +

【N-SING】   If a situation or problem is your _concern_, it is something that you have a duty or responsibility to be involved with. 负责任的事   +
⇒  The technical aspects were the concern of the Army.  技术方面是军方负责的事。   +

【PHRASE】   If a company is a _going concern_, it is actually doing business, rather than having stopped trading or not yet having started trading. 在运营的公司   +
⇒  The receivers will always prefer to sell a business as a going concern.  接管人总是更希望出售仍然在运营的公司。   +

---


==== ▸ sprout  [4111]   +
な/spraʊt/   +

【V-I】   When plants, vegetables, or seeds _sprout_, they produce new shoots or leaves. (植物、蔬菜、种子) 发芽   +
⇒  It only takes a few days for beans to sprout.  豆子只需几天就会发芽。   +

【V-I】   When leaves, shoots, or plants _sprout_ somewhere, they grow there. (叶子、芽、植株) 长出   +
⇒  Leaf-shoots were beginning to sprout on the hawthorn.  叶芽开始在山楂树上长出来。   +

【V-T/V-I】   If something such as hair _sprouts_ from a person or animal, or if they _sprout_ it, it grows on them. (人、动物) 长出 (毛发等); (毛发等) 长出来   +
⇒  She is very old now, with little, round, wire-rimmed glasses and whiskers sprouting from her chin.  她现在很老了，戴着小而圆的金属丝框眼镜，下巴长出了胡须。   +

【N-COUNT】  _Sprouts_ are vegetables that look like tiny cabbages. They are also called _brussels sprouts_. 抱子甘蓝    +

---


==== ▸ yeast  [4112]   +
な/jiːst/   +

【N-MASS】  _Yeast_ is a kind of fungus which is used to make bread rise, and in making alcoholic drinks such as beer. 酵母   +

---


==== ▸ wipe  [4113]   +
な/waɪp/   +

【V-T】   If you _wipe_ something, you rub its surface to remove dirt or liquid from it. 擦拭   +
⇒  I'll just wipe the table.  我只擦擦桌子。   +
⇒  When he had finished washing he began to wipe the basin clean.  他洗漱完后开始把水盆擦干净。   +

【N-COUNT】  _Wipe_ is also a noun. 擦拭   +
⇒  Tomorrow I'm going to give the toys a good wipe as some seem a bit greasy.  明天我会把那些玩具好好擦拭一番，因为有些看上去有点油腻了。   +

【V-T】   If you _wipe_ dirt or liquid from something, you remove it by using a cloth or your hand. (用布或手) 擦去   +
⇒  Gleb wiped the sweat from his face.  格莱布擦去了脸上的汗水。   +

【N-COUNT】   A _wipe_ is a small moist cloth for cleaning things and is designed to be used only once. 一次性湿巾   +
⇒  ...antiseptic wipes.  …一次性杀菌湿巾。   +

---


==== ▸ credit  [4114]   +
な/ˈkrɛdɪt/   +

【N-UNCOUNT】   If you are given _credit_, you are allowed to pay for goods or services several weeks or months after you have received them. 赊购   +
⇒  The group can't get credit to buy farming machinery.  该集团无法以赊购方式购买农业机械。   +

【N-UNCOUNT】   If you get _the credit for_ something good, people praise you because you are responsible for it, or are thought to be responsible for it. 赞扬   +
⇒  We don't mind who gets the credit so long as we don't get the blame.  只要我们不挨批评，谁受到表扬我们都不在乎。   +
⇒  It would be wrong for us to take all the credit.  我们把所有的功劳都揽到自己身上就不对了。   +

【V-T】   When a sum of money _is credited to_ an account, the bank adds that sum of money to the total in the account. 存入   +
⇒  She noticed that only $80,000 had been credited to her account.  她注意到只有$80000存入了她的账户。   +
⇒  Midland decided to change the way it credited payments to accounts.  米德兰公司决定改变将所付款项存入账户的方式。   +

【V-T】   If people _credit_ someone _with_ an achievement or if it _is credited to_ them, people say or believe that they were responsible for it. 归功于   +
⇒  The staff are crediting him with having saved Hythe's life.  海斯能得救全体人员都归功于他。   +
⇒  The 74-year-old mayor is credited with helping make Los Angeles the financial capital of the West Coast.  74岁的市长被归功为帮助洛杉矶成为西海岸金融中心的人。   +

【N-COUNT】   A _credit_ is a sum of money which is added to an account. 贷方款额   +
⇒  The statement of total debits and credits is known as a balance.  总的借贷报表称作借贷平衡表。   +

【N-COUNT】   A _credit_ is an amount of money that is given to someone. 补助   +
⇒  Senator Bill Bradley outlined his own tax cut, giving families $350 in tax credits per child.  参议员比尔·布拉德利简述了自己的减税计划，给家庭中每一个孩子$350税款补助。   +

【N-PLURAL】   The list of people who helped to make a film, a CD, or a television programme is called _the credits_. 摄制人员名单   +
⇒  It was fantastic seeing my name in the credits.  在摄制人员名单中看到我的名字真是太好了。   +

【N-COUNT】   A _credit_ is a successfully completed part of a higher education course, representing about one hour of instruction a week. At universities and colleges you need a certain number of credits to be awarded a degree. 学分   +
⇒  Through the AP programme students can earn college credits in high school.  通过大学预修课程计划，学生在中学就可以拿到大学的学分。   +

【N-SING】   If you say that someone is _a credit to_ someone or something, you mean that their qualities or achievements will make people have a good opinion of the person or thing mentioned. 为…增光的人   +
⇒  He is one of the greatest players of recent times and is a credit to his profession.  他是近年来最棒的选手之一，是为他的职业增光的人。   +

【PHRASE】   To _give_ someone _credit for_ a good quality means to believe that they have it. 相信某人有   +
⇒  Bratbakk had more ability than the media gave him credit for.  布拉特巴克有比媒体所宣传的还要强的能力。   +

【PHRASE】   If something is _to_ someone's _credit_, they deserve praise for it. 值得赞扬   +
⇒  She had managed to pull herself together and, to her credit, continued to look upon life as a positive experience.  她努力使自己振作起来，并且值得称赞的是，她一如既往地积极面对人生。   +

---


==== ▸ electrode  [4115]   +
な/ɪˈlɛktrəʊd/   +

【N-COUNT】   An _electrode_ is a small piece of metal or other substance that is used to take an electric current to or from a source of power, a piece of equipment, or a living body. 电极   +
⇒  Two electrodes that measure changes in the body's surface moisture are attached to the palms of your hands.  测量体表湿度变化的两个电极被连接到你的双掌上。   +

---


==== ▸ scrupulous  [4116]   +
な/ˈskruːpjʊləs/   +

【ADJ】   Someone who is _scrupulous_ takes great care to do what is fair, honest, or morally right. 讲良心的   +
⇒  You're being very scrupulous, but to what end?  你表现得很讲良心，但目的是什么呢？   +
⇒  I have been scrupulous about telling them the dangers.  我告诉他们这些危险是很讲良心的。   +

【ADJ】  _Scrupulous_ means thorough, exact, and careful about details. 谨小慎微的   +
⇒  Both readers commend Knutson for his scrupulous attention to detail.  两位读者都称赞克努森对细节谨小慎微的关注。   +

---


==== ▸ denounce  [4117]   +
な/dɪˈnaʊns/   +

【V-T】   If you _denounce_ a person or an action, you criticize them severely and publicly because you feel strongly that they are wrong or evil. 谴责   +
⇒  German leaders all took the opportunity to denounce the attacks and plead for tolerance.  德国领导人们都藉此机会谴责这些攻击，并且恳请宽容。   +

【V-T】   If you _denounce_ someone who has broken a rule or law, you report them to the authorities. 告发   +
⇒  They were at the mercy of informers who might at any moment denounce them.  他们完全受那些随时可能告发他们的告密者的支配。   +

---


==== ▸ blade  [4118]   +
な/bleɪd/   +

【N-COUNT】   The _blade_ of a knife, axe, or saw is the edge, which is used for cutting. 刃   +
⇒  Many of them will have sharp blades.  他们很多都会有锋利的刃。   +

【N-COUNT】   The _blades_ of a propeller are the long, flat parts that turn around. (螺旋桨的) 桨叶   +

【N-COUNT】   The _blade_ of an oar is the thin flat part that you put into the water. (船桨的) 桨叶   +

【N-COUNT】   A _blade_ of grass is a single piece of grass. 草叶   +
⇒  Brian began to tear blades of grass from between the bricks.  布赖恩开始从砖缝儿里拔草叶。   +

---


==== ▸ monogamy  [4119]   +
な/mɒˈnɒɡəmɪ/   +

【N-UNCOUNT】  _Monogamy_ is used to refer to the state or custom of having a sexual relationship with only one partner. 单一配偶制   +
⇒  People still opt for monogamy and marriage.  人们还是选择单一配偶制和婚姻。   +

【N-UNCOUNT】  _Monogamy_ is the state or custom of being married to only one person at a particular time. 一夫一妻制   +
⇒  In many non-Western societies, however, monogamy has never dominated.  然而，在很多非西方社会，一夫一妻制从未占主导地位。   +

---


==== ▸ pollinate  [4120]   +
な/ˈpɒlɪˌneɪt/   +

【V-T】   To _pollinate_ a plant or tree means to fertilize it with pollen. This is often done by insects. 给···传授花粉   +
⇒  Many of the indigenous insects are needed to pollinate the local plants.  需要很多种土生昆虫给当地植物授粉。   +

【N-UNCOUNT】  </div>   +
⇒  Without sufficient pollination, the growth of the corn is stunted.  没有充足的授粉，玉米的生长就会受阻。   +

---


==== ▸ semantic  [4121]   +
な/sɪˈmæntɪk/   +

【ADJ】  _Semantic_ is used to describe things that deal with the meanings of words and sentences. 语义的   +
⇒  He did not want to enter into a semantic debate.  他不想卷入一场关于语义的争论。   +

---


==== ▸ glimmer  [4122]   +
な/ˈɡlɪmə/   +

【V-I】   If something _glimmers_, it produces or reflects a faint, gentle, often unsteady light. 闪烁微光   +
⇒  The moon glimmered faintly through the mists.  月亮透过薄雾闪烁着微光。   +

【N-COUNT】   A _glimmer_ is a faint, gentle, often unsteady light. 微光   +
⇒  In the east there is the slightest glimmer of light.  东方有一丝闪烁的微光。   +

【N-COUNT】   A _glimmer of_ something is a faint sign of it. 一丝 (迹象)   +
⇒  Despite an occasional glimmer of hope, this campaign has not produced any results.  尽管偶尔有一线希望，这次宣传活动并没有产生任何结果。   +

---


==== ▸ rough  [4123]   +
な/rʌf/   +

【ADJ】   If a surface is _rough_, it is uneven and not smooth. 粗糙的   +
⇒  His hands were rough and callused, from years of karate practice.  他的双手由于多年的空手道练习，粗糙而布满老茧。   +

【N-UNCOUNT】   粗糙   +
⇒  She rested her cheek against the roughness of his jacket.  她把脸靠在了他粗糙的夹克上。   +

【ADJ】   You say that people or their actions are _rough_ when they use too much force and not enough care or gentleness. 粗暴的; 粗野的   +
⇒  American football's a rough game at the best of times.  在最好的情况下足球也是一项粗野的运动。   +

【ADV】   粗暴地; 粗野地   +
⇒  They roughly pushed her forward.  他们粗暴地向前推她。   +

【ADJ】   A _rough_ area, city, school, or other place is unpleasant and dangerous because there is a lot of violence or crime there. (治安) 乱的   +
⇒  It was quite a rough part of our town.  那是我们镇上相当乱的一个地方。   +

【ADJ】   If you say that someone has had a _rough_ time, you mean that they have had some difficult or unpleasant experiences. 艰难的   +
⇒  All women have a rough time in our society.  我们社会所有妇女都过着艰难的日子。   +

【ADJ】   A _rough_ calculation or guess is approximately correct, but not exact. 粗略的   +
⇒  We were only able to make a rough estimate of how much fuel would be required.  我们只能对所需燃料的量作一个粗略估计。   +

【ADV】   粗略地   +
⇒  Gambling and tourism pay roughly half the entire state budget.  博彩业和旅游业为整个国家预算提供大致一半的资金来源。   +

【ADJ】   If you give someone a _rough_ idea, description, or drawing of something, you indicate only the most important features, without much detail. 大致的   +
⇒  I've got a rough idea of what he looks like.  我对他的样子有了个大致的概念。   +

【ADV】   大致地   +
⇒  He knew roughly what was about to be said.  他大致知道该说些什么。   +

【ADJ】   You can say that something is _rough_ when it is not neat and well made. 粗糙的   +
⇒  The bench had a rough wooden table in front of it.  那长椅前有张粗糙的木桌。   +

【ADV】   粗糙地   +
⇒  Roughly chop the tomatoes and add them to the casserole.  把这些西红柿粗切一下，添到那个砂锅里。   +

【ADJ】   If the sea or the weather at sea is _rough_, the weather is windy or stormy and there are very big waves. 风浪大的   +
⇒  A fishing vessel and a cargo ship collided in rough seas.  一艘渔船与一艘货轮在风大浪急的海上相撞了。   +

【PHRASE】   If you have to _rough it_, you have to live without the possessions and comforts that you normally have. 将就   +
⇒  There is a campsite but, if you prefer not to rough it, the Lake Hotel is nearby.  有一个营地，不过如果你不想将就，湖滨酒店就在附近。   +

---


==== ▸ attentive  [4124]   +
な/əˈtɛntɪv/   +

【ADJ】   If you are _attentive_, you are paying close attention to what is being said or done. 注意的   +
⇒  He wishes the government would be more attentive to detail in their response.  他希望政府在回应时能更注意细节。   +

【ADV】   注意地   +
⇒  He questioned Chrissie, and listened attentively to what she told him.  他询问了克丽茜，专注地听了她的讲述。   +

【ADJ】   Someone who is _attentive_ is helpful and polite. 体贴的; 殷勤的   +
⇒  At society parties he is attentive to his wife.  在社交聚会上，他对妻子体贴殷勤。   +

---


==== ▸ advocate  [4125]   +
な【V-T】   If you _advocate_ a particular action or plan, you recommend it publicly. 提倡   +
⇒  Mr. Williams is a conservative who advocates fewer government controls on business.  威廉斯先生是一位提倡减少政府对商业的控制的保守人士。   +

【N-COUNT】   An _advocate of_ a particular action or plan is someone who recommends it publicly. 倡导者   +
⇒  He was a strong advocate of free market policies and a multi-party system.  他是自由市场政策以及多党制的坚定倡导者。   +

【N-COUNT】   An _advocate_ for a particular group is a person who works for the interests of that group. 为 (某团体) 谋利益者   +
⇒  ...advocates for the homeless.  …为无家可归者谋利益的人。   +

【N-COUNT】   An _advocate_ is a lawyer who speaks in favour of someone or defends them in a court of law. 辩护律师   +

---


==== ▸ obstacle  [4126]   +
な/ˈɒbstəkəl/   +

【N-COUNT】   An _obstacle_ is an object that makes it difficult for you to go where you want to go, because it is in your way. 障碍物   +
⇒  Most competition cars will only roll over if they hit an obstacle.  多数赛车在撞到障碍物时都会翻车。   +

【N-COUNT】   You can refer to anything that makes it difficult for you to do something as an _obstacle_. 障碍   +
⇒  Overcrowding remains a large obstacle to improving conditions.  过度拥挤仍然是改善条件的一大障碍。   +

---


==== ▸ mediate  [4127]   +
な/ˈmiːdɪˌeɪt/   +

【V-T/V-I】   If someone _mediates between_ two groups of people, or _mediates_ an agreement _between_ them, they try to settle an argument between them by talking to both groups and trying to find things that they can both agree to. 调解   +
⇒  My mom was the one who mediated between Zelda and her mom.  我妈妈是那个调解塞尔达和她妈妈的人。   +
⇒  United Nations officials have mediated a series of peace meetings between the two sides.  联合国官员们已经调解了双方的一系列和谈。   +

【N-UNCOUNT】   调解   +
⇒  The agreement provides for United Nations mediation between the two sides.  该协议为联合国对双方的调解奠定了基础。   +

---


==== ▸ facilitate  [4128]   +
な/fəˈsɪlɪˌteɪt/   +

【V-T】   To _facilitate_ an action or process, especially one that you would like to happen, means to make it easier or more likely to happen. 促进   +
⇒  The new airport will facilitate the development of tourism.  新机场将促进旅游业的发展。   +

---


==== ▸ liquefy  [4129]   +
な/ˈlɪkwɪˌfaɪ/   +
⇒  Heat the jam until it liquefies.  加热果酱直至其液化。   +
⇒  You can liquefy the carbon dioxide to separate it from the other constituents.  你可液化二氧化碳以使它与其他成分分离。   +
⇒  ...a truck carrying liquefied petroleum gas.  ...一辆装载着液化石油气的货车。   +

---


==== ▸ alternative  [4130]   +
な/ɔːlˈtɜːnətɪv/   +

【N-COUNT】   If one thing is an _alternative to_ another, the first can be found, used, or done instead of the second. 替代品   +
⇒  New ways to treat arthritis may provide an alternative to painkillers.  治疗关节炎的新方法可能会提供一种止痛药的替代品。   +

【ADJ】   An _alternative_ plan or offer is different from the one that you already have, and can be done or used instead. 另外的   +
⇒  There were alternative methods of travel available.  有另外的旅行方式可采用。   +

【ADJ】  _Alternative_ is used to describe something that is different from the usual things of its kind, or the usual ways of doing something, in modern Western society. For example, an _alternative_ lifestyle does not follow conventional ways of living and working. 另类的   +
⇒  ...unconventional parents who embraced the alternative lifestyle of the Sixties.  …信奉60年代另类生活方式的与众不同的家长们。   +

【ADJ】  _Alternative_ medicine uses traditional ways of curing people, such as medicines made from plants, massage, and acupuncture. 替代性的 (疗法)   +
⇒  ...alternative health care.  …替代性保健。   +

【ADJ】  _Alternative_ energy uses natural sources of energy such as the sun, wind, or water for power and fuel, rather than oil, coal, or nuclear power. 可再生的 (能源)   +

---


==== ▸ summon  [4131]   +
な/ˈsʌmən/   +

【V-T】   If you _summon_ someone, you order them to come to you. 召唤   +
⇒  Howe summoned a doctor and hurried over.  豪叫了一位医生，匆忙赶过去了。   +
⇒  Suddenly we were summoned to the interview room.  突然我们被召唤进了面试室。   +

【V-T】   If you _summon_ a quality, you make a great effort to have it. For example, if you _summon_ the courage or strength to do something, you make a great effort to be brave or strong, so that you will be able to do it. 努力拥有 (某特质); 鼓起 (勇气、力气)   +
⇒  It took her a full month to summon the courage to tell her mother.  她用了整整一个月的时间才鼓起勇气告诉了母亲。   +

【PHRASAL VERB】  _Summon up_ means the same as . 努力拥有; 鼓起 (同)(summon)   +
⇒  Painfully shy, he finally summoned up courage to ask her to a game.  尽管他非常腼腆，最终还是鼓起了勇气邀她去看一场比赛。   +

---


==== ▸ script  [4132]   +
な/skrɪpt/   +

【N-COUNT】   The _script_ of a play, movie, or television programme is the written version of it. 脚本   +
⇒  Jenny's writing a film script.  珍妮在写一个电影脚本。   +

【V-T】   The person who _scripts_ a movie or a radio or television play writes it. 为 (电影、广播、电视等) 写脚本   +
⇒  ...James Cameron, who scripted and directed both films.  …为这两部电影写脚本并执导的詹姆斯·卡梅伦。   +

【N-VAR】   You can refer to a particular system of writing as a particular _script_. 文字系统   +
⇒  ...a text in the Malay language but written in Arabic script.  …一段用阿拉伯文书写的马来语文本。   +

【N-VAR】  _Script_ is handwriting in which the letters are joined together. 连写体   +
⇒  When you're writing in script, there are four letters of the alphabet that you can't complete in one stroke.  当你用连写体书写时，字母表里有4个字母你不能一笔写完。   +

---


==== ▸ cohabitation  [4133]   +
 辞典中没找到  +
==== ▸ counter  [4134]   +
な/ˈkaʊntə/   +

【N-COUNT】   In a place such as a shop or café, a _counter_ is a long narrow table or flat surface at which customers are served. 柜台   +
⇒  ...those guys we see working behind the counter at our local video rental shop.  …我们所见在本地音像出租商店柜台后工作的那些家伙。   +

【N-COUNT】   A _counter_ is a mechanical or electronic device which keeps a count of something and displays the total. 计数器   +
⇒  The new answering machine has a call counter.  这种新型的电话答录机有一个通话计数器。   +

【N-COUNT】   A _counter_ is a small, flat, round object used in board games. 棋子   +
⇒  ...a versatile book which provides boards and counters for fifteen different games.  …一本为15种不同棋类游戏提供棋盘和棋子的多功能书。   +

【V-T/V-I】   If you do something to _counter_ a particular action or process, you do something which has an opposite effect to it or makes it less effective. 抵消; 抗衡   +
⇒  The leadership discussed a plan of economic measures to counter the effects of such a blockade.  领导层讨论了一项经济措施计划来抵消如此封锁的影响。   +
⇒  Sears countered by filing an antitrust lawsuit.  西尔斯通过提交反垄断诉讼进行了反击。   +

【N-SING】   Something that is _a counter to_ something else has an opposite effect to it or makes it less effective. 抵消物   +
⇒  ...NATO's traditional role as a counter to the military might of the Warsaw Pact.  …北大西洋公约组织作为华沙公约组织军事力量的遏制力量的传统角色。   +

【PHRASE】   If a medicine can be bought _over the counter_, you do not need a prescription to buy it. 不用开处方地   +
⇒  Are you taking any other medicines whether on prescription or bought over the counter?  你还要其他药吗，不管是处方药还是非处方药？   +
⇒  ...over-the-counter medicines.  …非处方药。   +

【PHRASE】  _Over-the-counter_ shares are bought and sold directly rather than on a stock exchange. 不通过交易所的   +
⇒  In national over-the-counter trading yesterday, Clarcor shares tumbled $6.125 to close at $35.625.  昨天在全国场外交易中，克拉克股票跌$6.125，以$35.625收盘。   +

---


==== ▸ humanity  [4135]   +
な/hjuːˈmænɪtɪ/   +

【N-UNCOUNT】   All the people in the world can be referred to as _humanity_. 人类   +
⇒  They face charges of committing crimes against humanity.  他们面临犯有反人类罪的指控。   +

【N-UNCOUNT】   A person's _humanity_ is their state of being a human being, rather than an animal or an object. 人性   +
⇒  He was under discussion and it made him feel deprived of his humanity.  他受到议论，这使他觉得自己被剥夺了人格。   +

【N-UNCOUNT】  _Humanity_ is the quality of being kind, thoughtful, and sympathetic toward others. 仁慈; 博爱   +
⇒  Her speech showed great maturity and humanity.  她的演讲表现出高度的成熟和博爱。   +

【N-PLURAL】  _The__humanities_ are the subjects such as history, philosophy, and literature which are concerned with human ideas and behaviour. (历史、哲学、文学等) 人文学科   +
⇒  The number of students majoring in the humanities has declined by about half.  主修人文学科的学生数量已经下降了近一半。   +

---


==== ▸ utilize  [4136]   +
な/ˈjuːtɪˌlaɪz/   +

【V-T】   If you _utilize_ something, you use it. 利用   +
⇒  Sound engineers utilize a range of techniques to enhance the quality of the recordings.  音响工程师利用一系列的技术来提高录音质量。   +

【N-UNCOUNT】   利用   +
⇒  ...the utilization of human resources.  …人力资源的利用。   +

---


==== ▸ modeling  [4137]   +
 辞典中没找到  +
==== ▸ eminent  [4138]   +
な/ˈɛmɪnənt/   +

【ADJ】   An _eminent_ person is well-known and respected, especially because they are good at their profession. 卓越的; 有名望的   +
⇒  ...an eminent scientist.  …一位卓越的科学家。   +

---


==== ▸ censor  [4139]   +
な/ˈsɛnsə/   +

【V-T】   If someone in authority _censors_ letters or the media, they officially examine them and cut out any information that is regarded as secret. 审查 (信件或媒体)   +
⇒  The military-backed government has heavily censored the news.  以军方为后盾的政府对新闻报道进行了严格审查。   +

【V-T】   If someone in authority _censors_ a book, play, or film, they officially examine it and cut out any parts that are considered to be immoral or inappropriate. 审查 (书刊、剧本、电影)   +
⇒  The Late Show censored the band's live version of "Bullet in the Head."  《深夜秀》节目组审查了该乐队现场演奏的曲目《脑里的子弹》。   +

【N-COUNT】   A _censor_ is a person who has been officially appointed to examine letters or the media and to cut out any parts that are regarded as secret. (信件、媒体的官方) 审查员   +
⇒  The report was cleared by the American military censors.  这篇报道被美国军方审查员删掉了。   +

【N-COUNT】   A _censor_ is a person who has been officially appointed to examine plays, movies, and books and to cut out any parts that are considered to be immoral. (书刊、剧本、电影的官方) 审查员   +
⇒  The film had to be cut before the board of censors accepted it.  该电影得先进行剪切，才能得到审查委员会的认可。   +

---


==== ▸ swear  [4140]   +
な/swɛə/   +

【V-I】   If someone _swears_, they use language that is considered to be vulgar or offensive, usually because they are angry. 咒骂   +
⇒  It's wrong to swear and shout.  骂人和喊叫是不对的。   +

【V-T】   If you _swear to_ do something, you promise in a serious way that you will do it. 郑重许诺   +
⇒  Alan swore that he would do everything in his power to help us.  艾伦郑重许诺他会尽其所能帮助我们。   +
⇒  We have sworn to fight cruelty wherever we find it.  我们已郑重许诺，无论在哪儿发现暴行我们都要与其斗争。   +

【V-T/V-I】   If you say that you _swear_ that something is true or that you can _swear_ to it, you are saying very firmly that it is true. 发誓   +
⇒  I swear I've told you all I know.  我发誓我已经把我所知道的都告诉你了。   +
⇒  I swear on all I hold dear that I had nothing to do with this.  我拿我所在乎的一切发誓我与这件事情无关。   +

【V-T】   If someone _is sworn to_ secrecy or _is sworn to_ silence, they promise another person that they will not reveal a secret. 使承诺 (保密)   +
⇒  She was bursting to announce the news but was sworn to secrecy.  她忍不住想要发布这条消息，但发过誓要保密。   +

---


==== ▸ proportion  [4141]   +
な/prəˈpɔːʃən/   +

【N-COUNT】   A _proportion of_ a group or an amount is a part of it. 部分   +
⇒  A large proportion of the dolphins in that area will eventually die.  那个地区的很大一部分海豚最终都会死去。   +

【N-COUNT】   The _proportion of_ one kind of person or thing in a group is the number of people or things of that kind compared to the total number of people or things in the group. (某部分在总体中所占的) 比例   +
⇒  The proportion of women in the profession had risen to 17.3%.  从事那个职业的女性比例已经增长到17.3%。   +

【N-COUNT】   The _proportion of_ one amount _to_ another is the relationship between the size of the two amounts. (一个量与另一个量的) 比值   +
⇒  Women's bodies tend to have a higher proportion of fat to water.  女性体内往往有更高的脂肪与水的比值。   +

【N-PLURAL】   If you refer to the _proportions_ of something, you are referring to its size, usually when this is extremely large. (某物的) 大小   +
⇒  In the tropics plants grow to huge proportions.  在热带，植物长得很高大。   +

【PHRASE】   If one thing increases or decreases _in proportion to_ another thing, it increases or decreases to the same degree as that thing. (与…) 成比例地   +
⇒  The pressure in the cylinders would go up in proportion to the boiler pressure.  汽缸内的压力会与锅炉的压力成比例上升。   +

【PHRASE】   If something is small or large _in proportion to_ something else, it is small or large when compared with that thing. (与…) 比   +
⇒  Children tend to have relatively larger heads than adults in proportion to the rest of their body.  与身体其余部位相比，孩子头部所占比例往往比成人大。   +

【PHRASE】   If you say that something is _out of all proportion to_ something else, you think that it is far greater or more serious than it should be. (与…) 完全不成比例   +
⇒  The punishment was out of all proportion to the crime.  惩罚和罪行完全不成比例。   +

---


==== ▸ barn  [4142]   +
な/bɑːn/   +

【N-COUNT】   A _barn_ is a building on a farm in which animals, animal food, or crops can be kept. 谷仓; 牲口房   +

【N-COUNT】   any large building, esp an unattractive one 大仓棚   +

【N-COUNT】   a unit of nuclear cross section equal to 10_–__28_ square metre 靶; 核反应截面单位 ( symbol: b)   +

---


==== ▸ muscle  [4143]   +
な/ˈmʌsəl/   +

【N-VAR】   A _muscle_ is a piece of tissue inside your body that connects two bones and which you use when you make a movement. 肌肉   +
⇒  Keeping your muscles strong and in tone helps you to avoid back problems.  保持强壮有力的肌肉有助于防范背疾。   +

【N-UNCOUNT】   If you say that someone has _muscle_, you mean that they have power and influence, which enables them to do difficult things. 影响力   +
⇒  Eisenhower used his muscle to persuade Congress to change the law.  艾森豪威尔施展了他的影响力来说服国会修改该法律。   +

【PHRASE】   If a group, organization, or country _flexes_ its _muscles_, it does something to impress or frighten people, in order to show them that it has power and is considering using it. 显示实力   +
⇒  The Fair Trade Commission has of late been flexing its muscles, cracking down on cases of corruption.  公平交易委员会最近一展雄威，对腐败案件进行了严惩。   +

【PHRASE】   If you say that someone did not _move a muscle_, you mean that they stayed absolutely still. 动一下   +
⇒  He stood without moving a muscle, unable to believe what his eyes saw so plainly.  他一动也不动地站着，不敢相信自己的眼睛。   +

---


==== ▸ rattle  [4144]   +
な/ˈrætəl/   +

【V-T/V-I】   When something _rattles_ or when you _rattle_ it, it makes short, sharp, knocking sounds because it is being shaken or it keeps hitting against something hard. 使发出嘎嘎声; 发出嘎嘎声   +
⇒  She slams the kitchen door so hard I hear dishes rattle.  她砰地一下使劲关上厨房门，我听到盘子都震得嘎嘎响。   +

【N-COUNT】  _Rattle_ is also a noun. 嘎嘎声   +
⇒  There was a rattle of rifle fire.  有步枪射击发出的嘎嘎声。   +

【N-COUNT】   A _rattle_ is a baby's toy with small, loose objects inside which make a noise when the baby shakes it. 拨浪鼓   +

【V-T】   If something or someone _rattles_ you, they make you nervous. 使紧张   +
⇒  Officials are not normally rattled by any reporter's question.  官员们一般不会因为任何记者的提问而紧张不安。   +

【ADJ】   紧张的   +
⇒  He swore in Spanish, an indication that he was rattled.  他用西班牙语宣誓，这表明他很紧张。   +

【V】   to fit (a vessel or its rigging) with ratlines 给(船或其桅索)扎梯绳   +

---


==== ▸ advanced  [4145]   +
な/ədˈvɑːnst/   +

【ADJ】   An _advanced_ system, method, or design is modern and has been developed from an earlier version of the same thing. 先进的 (系统、方法、设计等)   +
⇒  ...a superpower equipped with the most advanced military technology in the world.  …一个拥有世界上最先进的军事技术的超级大国。   +

【ADJ】   A country that is _advanced_ has reached a high level of industrial or technological development. (国家) 发达的   +
⇒  Agricultural productivity remained low by comparison with advanced countries like the United States.  与美国等发达国家相比，农业生产率仍很低。   +

【ADJ】   An _advanced_ student has already learned the basic facts of a subject and is doing more difficult work. An _advanced_ course of study is designed for such students. 高阶的 (学生、课程)   +
⇒  The course is suitable for beginners and advanced students.  该课程适合初学者和高阶学生。   +

【ADJ】   Something that is at an _advanced_ stage or level is at a late stage of development. 晚期的   +
⇒  Medicare is available to victims of advanced kidney disease.  晚期肾病患者可获得医疗保障。   +

---


==== ▸ flu  [4146]   +
な/fluː/   +

【N-UNCOUNT】  _Flu_ is an illness which is similar to a bad cold but more serious. It often makes you feel very weak and makes your muscles hurt. 流感   +
⇒  I got the flu.  我得了流感。   +

---


==== ▸ constituent  [4147]   +
な/kənˈstɪtjʊənt/   +

【N-COUNT】   A _constituent_ is someone who lives in a particular constituency, especially someone who is able to vote in an election. 选民   +
⇒  He told his constituents that he would continue to represent them to the best of his ability.  他告诉他的选民们他会继续竭尽所能代表他们。   +

【N-COUNT】   A _constituent of_ a mixture, substance, or system is one of the things from which it is formed. 成分   +
⇒  Caffeine is the active constituent of drinks such as tea and coffee.  咖啡因是茶和咖啡这类饮品的活性成分。   +

【ADJ】   The _constituent_ parts of something are the things from which it is formed. 构成的   +
⇒  ...a plan to split the company into its constituent parts and sell them separately.  …一项把公司拆分为各构成部分然后分别出售的计划。   +

---


==== ▸ Gothic  [4148]   +
な/ˈɡɒθɪk/   +

【ADJ】  _Gothic_ architecture and religious art was produced in the Middle Ages. Its features include tall pillars, high curved ceilings, and pointed arches. 哥特式的 (建筑物或宗教艺术)   +
⇒  ...a vast, lofty Gothic cathedral.  …一幢雄伟高耸的哥特式大教堂。   +
⇒  ...Gothic stained glass windows.  …哥特式彩色玻璃窗。   +

【ADJ】   In _Gothic_ stories, strange, mysterious adventures happen in dark and lonely places such as graveyards and old castles. (以神秘、怪诞为特征的) 哥特派文学的   +
⇒  This novel is not science fiction, nor is it Gothic horror.  这部小说既非科幻故事，也非哥特式恐怖故事。   +

【ADJ】  _Gothic_   +

---


==== ▸ zigzag  [4149]   +
な/ˈzɪɡˌzæɡ/   +

【N-COUNT】   A _zigzag_ is a line that has a series of angles in it like a continuous series of Ws. 之字线   +
⇒  They staggered in a zigzag across the road.  他们东倒西歪地踉踉跄跄穿过了公路。   +

【V-T/V-I】   If you _zigzag_, you move forward by going at an angle first to one side then to the other. 作之字形前移   +
⇒  I zigzagged down a labyrinth of alleys.  我在如迷宫般的小巷里拐来拐去。   +
⇒  He zigzagged his way across the field.  他东拐西拐穿过了田野。   +

---


==== ▸ adhesive  [4150]   +
な/ədˈhiːsɪv/   +

【N-MASS】   An _adhesive_ is a substance such as glue, which is used to make things stick firmly together. 黏合剂   +
⇒  Glue the mirror in with a strong adhesive.  用一种强力黏合剂把镜子粘进去。   +

【ADJ】   An _adhesive_ substance is able to stick firmly to something else. 带黏性的   +
⇒  ...adhesive tape.  …胶布。   +

---


==== ▸ delegate  [4151]   +
な【N-COUNT】   A _delegate_ is a person who is chosen to vote or make decisions on behalf of a group of other people, especially at a conference or a meeting. 代表   +
⇒  The Canadian delegate offered no reply.  那位加拿大代表没给答复。   +

【V-T/V-I】   If you _delegate_ duties, responsibilities, or power _to_ someone, you give them those duties, those responsibilities, or that power so that they can act on your behalf. 委托; 授权   +
⇒  He talks of travelling less, and delegating more authority to his deputies.  他说要减少旅行，还有要授予他的副手们更多的权力。   +

【N-UNCOUNT】   委托; 授权   +
⇒  A key factor in running a business is the delegation of responsibility.  经商的一个关键因素是责任委托。   +

【V-T】   If you _are delegated to_ do something, you are given the duty of acting on someone else's behalf by making decisions, voting, or doing some particular work. 委派   +
⇒  Officials have now been delegated to start work on a draft settlement.  官员们现已被委派开始准备一份拟定协议。   +

---


==== ▸ commission  [4152]   +
な/kəˈmɪʃən/   +

【V-T】   If you _commission_ something or _commission_ someone _to_ do something, you formally arrange for someone to do a piece of work for you. 委托   +
⇒  The Department of Agriculture commissioned a study into organic farming.  农业部委托了一项有机耕作的研究。   +
⇒  You can commission them to paint something especially for you.  你可以委托他们专门为你画点什么。   +

【N-VAR】  _Commission_ is also a noun. 委托   +
⇒  Our china can be bought off the shelf or by commission.  我们的瓷器可以现货购买或委托定做。   +

【N-COUNT】   A _commission_ is a piece of work that someone is asked to do and is paid for. 委托任务   +
⇒  Just a few days ago, I finished a commission.  就在几天之前我完成了一项委托任务。   +

【N-VAR】  _Commission_ is a sum of money paid to a salesperson for every sale that he or she makes. If a salesperson is paid _on commission_, the amount they receive depends on the amount they sell. 销售佣金   +
⇒  The salespeople work on commission only.  推销员只拿销售佣金。   +

【N-UNCOUNT】   If a bank or other company charges _commission_, they charge a fee for providing a service, for example for exchanging money or issuing an insurance policy. 服务费   +
⇒  Travel agents charge 1 per cent commission on tickets.  旅行社收1%的购票服务费。   +

【N-COUNT-COLL】   A _commission_ is a group of people who have been appointed to find out about something or to control something. 委员会   +
⇒  The government has set up a commission to look into those crimes.  政府已成立一个委员会调查那些罪行。   +

【N-COUNT】   If a member of the armed forces receives a _commission_, he or she becomes an officer. 任命   +
⇒  He accepted a commission as a naval officer.  他接受了海军军官的任命。   +

---


==== ▸ virtue  [4153]   +
な/ˈvɜːtjuː/   +

【N-UNCOUNT】  _Virtue_ is thinking and doing what is right and avoiding what is wrong. 正直的品性   +
⇒  Virtue is not confined to the Christian world.  正直的品性并不限于基督教世界。   +

【N-COUNT】   A _virtue_ is a good quality or way of behaving. 美德   +
⇒  His virtue is patience.  他的美德就是耐心。   +

【N-COUNT】   The _virtue_ of something is an advantage or benefit that it has, especially in comparison with something else. 优势; 益处   +
⇒  There was no virtue in returning to Calvi the way I had come.  按我来的路线返回卡尔维并不可取。   +

【PHRASE】   You use _by virtue of_ to explain why something happens or is true. 因为   +
⇒  The article stuck in my mind by virtue of one detail.  该文章因一细节而印入我脑海。   +

---


==== ▸ rehabilitate  [4154]   +
な/ˌriːəˈbɪlɪˌteɪt/   +

【V-T】   To _rehabilitate_ someone who has been ill or in prison means to help them to live a normal life again. To _rehabilitate_ someone who has a drug or alcohol problem means to help them stop using drugs or alcohol. 使康复; 使戒毒; 使戒酒   +
⇒  Considerable efforts have been made to rehabilitate patients who have suffered in this way.  为使受这种苦的病人康复已经付出了相当大的努力。   +

【N-UNCOUNT】   复原   +
⇒  A number of other techniques are now being used by psychologists in the rehabilitation of young offenders.  一些别的技术现正被心理学家们用于年轻罪犯的复原。   +

---


==== ▸ overnight  [4155]   +
な/ˌəʊvəˈnaɪt/   +

【ADV】   If something happens _overnight_, it happens throughout the night or at some point during the night. 通宵地; 在夜间   +
⇒  The decision was reached overnight.  这个决定是夜间做出的。   +

【ADJ】  _Overnight_ is also an adjective. 通宵的; 夜间的   +
⇒  Travel and overnight accommodation are included.  旅行及夜间住宿是包含在内的。   +

【ADV】   You can say that something happens _overnight_ when it happens very quickly and unexpectedly. 突然地   +
⇒  The rules are not going to change overnight.  这些规则是不会突然改变的。   +

【ADJ】  _Overnight_ is also an adjective. 突然的   +
⇒  In 1970 he became an overnight success in America.  1970年他在美国一夜之间成了成功人士。   +

【ADJ】  _Overnight_ bags or clothes are ones that you take when you go and stay somewhere for one or two nights. 外出住宿一两晚的 (包或衣服)   +
⇒  He realized he'd left his overnight bag at Mary's house.  他意识到他把自己的短途旅行包落在玛丽家里了。   +

---


==== ▸ patron  [4156]   +
な/ˈpeɪtrən/   +

【N-COUNT】   A _patron_ is a person who supports and gives money to artists, writers, or musicians. (艺术家、作家、音乐家等的) 资助人   +
⇒  Catherine the Great was a patron of the arts and sciences.  凯瑟琳大帝是艺术和科学的赞助人。   +

【N-COUNT】   The _patron_ of a charity, group, or campaign is an important person who allows his or her name to be used for publicity. (慈善机构、团体、运动等的) 名誉赞助人   +
⇒  He has now become one of the patrons of the association.  他如今已成为该协会的名誉赞助人之一。   +

【N-COUNT】   The _patrons_ of a place such as a bar or hotel are its customers. (酒吧、旅馆等的) 顾客   +
⇒  Few patrons of a high-priced hotel can be led to expect anything other than luxury service.  高价旅馆的顾客几乎没有人会被引导去期待奢侈服务以外的任何东西。   +

【N】   a man, who owns or manages a hotel, restaurant, or bar (旅店，餐馆、酒吧等的)老板   +

---


==== ▸ watercourse  [4157]   +
な/ˈwɔːtəˌkɔːs/   +

【N-COUNT】   A _watercourse_ is a stream or river, or the channel that it flows along. 水道   +

---


==== ▸ coexist  [4158]   +
な/ˌkəʊɪɡˈzɪst/   +

【V-RECIP】   If one thing _coexists with_ another, they exist together at the same time or in the same place. You can also say that two things _coexist_. 共存   +
⇒  Newspaper Web sites can coexist with the newspapers and still bring in healthy profit margins.  网络报纸可以与纸质报纸共存，仍能带来不错的利润。   +
⇒  The different cultures had coexisted peacefully for many years.  不同文化曾和平共存了很多年。   +

---


==== ▸ ingredient  [4159]   +
な/ɪnˈɡriːdɪənt/   +

【N-COUNT】  _Ingredients_ are the things that are used to make something, especially all the different foods you use when you are cooking a particular dish. (尤指烹调用的) 原料   +
⇒  Mix in the remaining ingredients.  掺入剩下的原料。   +

【N-COUNT】   An _ingredient_ of a situation is one of the essential parts of it. 要素   +
⇒  The meeting had all the ingredients of high political drama.  这次会议拥有了极富戏剧性的政治紧张场面的全部要素。   +

---


==== ▸ instill  [4160]   +
 辞典中没找到  +
==== ▸ symbol  [4161]   +
な/ˈsɪmbəl/   +

【N-COUNT】   Something that is a _symbol of_ a society or an aspect of life seems to represent it because it is very typical of it. 象征   +
⇒  To them, the monarchy is the special symbol of nationhood.  对他们而言，君主政体是国家的特殊象征。   +

【N-COUNT】   A _symbol of_ something such as an idea is a shape or design that is used to represent it. 象征物   +
⇒  Later in this same passage Yeats resumes his argument for the Rose as an Irish symbol.  后来在这同一篇文章里，叶芝再次提到把玫瑰作为爱尔兰象征的观点。   +

【N-COUNT】   A _symbol for_ an item in a calculation or scientific formula is a number, letter, or shape that represents that item. 符号   +
⇒  What's the chemical symbol for mercury?  水银的化学符号是什么？   +

---


==== ▸ prodigious  [4162]   +
な/prəˈdɪdʒəs/   +

【ADJ】   Something that is _prodigious_ is very large or impressive. 巨大的; 给人印象深刻的   +
⇒  This business generates cash in prodigious amounts.  这生意带来大量现金。   +

【ADV】   巨大地; 给人印象深刻地   +
⇒  She ate prodigiously.  她真能吃。   +

---


==== ▸ skull  [4163]   +
な/skʌl/   +

【N-COUNT】   Your _skull_ is the bony part of your head which encloses your brain. 颅骨; 头颅   +
⇒  Her husband was later treated for a fractured skull.  她丈夫后来因颅骨碎裂而接受治疗。   +

---


==== ▸ fraudulent  [4164]   +
な/ˈfrɔːdjʊlənt/   +

【ADJ】   A _fraudulent_ activity is deliberately deceitful, dishonest, or untrue. 欺骗性的   +
⇒  ...fraudulent claims about being a nurse.  …谎称自己是护士。   +

【ADV】   欺骗性地   +
⇒  All 5,000 of the homes were fraudulently obtained.  5000所房子全都是骗取的。   +

---


==== ▸ avoid  [4165]   +
な/əˈvɔɪd/   +

【V-T】   If you _avoid_ something unpleasant that might happen, you take action in order to prevent it from happening. 避免 (坏事的发生)   +
⇒  The pilots had to take emergency action to avoid a disaster.  飞行员们不得不采取紧急措施以避免灾难的发生。   +

【V-T】   If you _avoid_ doing something, you choose not to do it, or you put yourself in a situation where you do not have to do it. 避免   +
⇒  By borrowing from dozens of banks, he managed to avoid giving any of them an overall picture of what he was up to.  通过向几十家银行借钱，他得以避免让任何一家了解他要做事情的全貌。   +

【V-T】   If you _avoid_ a person or thing, you keep away from them. When talking to someone, if you _avoid_ the subject, you keep the conversation away from a particular topic. 避开   +
⇒  She eventually had to lock herself in the women's restroom to avoid him.  她最后不得不把自己锁在女厕所里避开他。   +

【V-T】   If a person or vehicle _avoids_ someone or something, they change the direction they are moving in, so that they do not hit them. (人或车) 避让   +
⇒  The driver had ample time to brake or swerve and avoid the woman.  该司机有足够的时间刹车或急转来避让那女子。   +

---


==== ▸ stumble  [4166]   +
な/ˈstʌmbəl/   +

【V-I】   If you _stumble_, you put your foot down awkwardly while you are walking or running and nearly fall over. 踉跄; 绊脚   +
⇒  He stumbled and almost fell.  他绊了一下，差点儿摔倒。   +

【N-COUNT】  _Stumble_ is also a noun. 踉跄; 绊脚   +
⇒  I make it into the darkness with only one stumble.  我只踉跄了一下就把它弄进了黑暗中。   +

---


==== ▸ ferment  [4167]   +
な【N-UNCOUNT】  _Ferment_ is excitement and trouble caused by change or uncertainty. 骚动   +
⇒  The whole country has been in a state of political ferment for some months.  整个国家几个月来一直处在政治骚动的状态中。   +

【V-T/V-I】   If a food, drink, or other natural substance _ferments_, or if it _is fermented_, a chemical change takes place in it so that alcohol is produced. This process forms part of the production of alcoholic drinks such as wine and beer. 使发酵; 发酵   +
⇒  The dried grapes are allowed to ferment until there is no sugar left and the wine is dry.  干葡萄要经过发酵，直到没有糖分存留，葡萄酒才不会有甜味。   +

【N-UNCOUNT】   发酵   +
⇒  Yeast is essential for the fermentation that produces alcohol.  酵母对酿酒的发酵是必要的。   +

---


==== ▸ hemp  [4168]   +
な/hɛmp/   +

【N-UNCOUNT】  _Hemp_ is a plant used for making rope or the drug marijuana. 大麻(植物)   +

---


==== ▸ franchise  [4169]   +
な/ˈfræntʃaɪz/   +

【N-COUNT】   A _franchise_ is an authority that is given by an organization to someone, allowing them to sell its goods or services or to take part in an activity which the organization controls. (公司授予某人的) 特许经营权   +
⇒  ...fast-food franchises.  …快餐特许经营权。   +
⇒  ...the franchise to build and operate the tunnel.  …建造、运营隧道的特许权。   +

【V-T】   If a company _franchises_ its business, it sells franchises to other companies, allowing them to sell its goods or services. 出售…的特许经营权   +
⇒  She has recently franchised her business.  她最近已出售了其公司的特许经营权。   +

【N-UNCOUNT】  _Franchise_ is the right to vote in an election. 选举权   +
⇒  ...the introduction of universal franchise.  …普选权的采用。   +

---


==== ▸ perceive  [4170]   +
な/pəˈsiːv/   +

【V-T】   If you _perceive_ something, you see, notice, or realize it, especially when it is not obvious. 感知到   +
⇒  Students must perceive for themselves the relationship between success and effort.  学生们必须自己去认识到成功与努力之间的关系。   +

【V-T】   If you _perceive_ someone or something _as_ doing or being a particular thing, it is your opinion that they do this thing or that they are that thing. 认为   +
⇒  Stress is widely perceived as contributing to coronary heart disease.  压力普遍被认为能造成冠心病。   +

---


==== ▸ diversion  [4171]   +
な/daɪˈvɜːʃən/   +

【N-COUNT】   A _diversion_ is an action or event that attracts your attention away from what you are doing or concentrating on. 令人分心的事物   +
⇒  ...armed robbers who escaped after throwing smoke bombs to create a diversion.  …在扔出烟雾弹造成注意力分散之后逃跑的武装抢劫犯们。   +

【N-COUNT】   A _diversion_ is a special route arranged for traffic to follow when the normal route cannot be used. 改道路线   +
⇒  A slight diversion in the road is causing major headaches for businesses along El Camino Real.  马路上的一小段绕行道让国王大道沿街的商家十分头疼。   +

【N-UNCOUNT】  _The diversion of_ something involves changing its course or destination. 转移; 转向   +
⇒  ...the illegal diversion of profits from secret arms sales.  …销售秘密武器所得收益的非法转移。   +

---


==== ▸ entourage  [4172]   +
な/ˈɒntʊˌrɑːʒ/   +

【N-COUNT】   A famous or important person's _entourage_ is the group of assistants, servants, or other people who travel with them. 随从   +
⇒  Rachel was quickly whisked away by her entourage.  雷切尔很快被她的随从带走了。   +

---


==== ▸ authorize  [4173]   +
な/ˈɔːθəˌraɪz/   +

【V-T】   If someone in a position of authority _authorizes_ something, they give their official permission for it to happen. 批准   +
⇒  It would certainly be within his power to authorize a police raid like that.  他肯定有权批准那种警方突袭行动。   +

【N-VAR】   批准   +
⇒  The United Nations will approve his request for authorization to use military force to deliver aid.  联合国将同意他的请求，批准他动用军队来运送救援物资。   +

---


==== ▸ geometric  [4174]   +
な/ˌdʒɪəˈmɛtrɪk/   +

【ADJ】  _Geometric_ or _geometrical_ patterns or shapes consist of regular shapes or lines. 几何图形的   +
⇒  Geometric designs were popular wall decorations in the 14th century.  几何图案是14世纪流行的墙面装饰。   +

【ADJ】  _Geometric_ or _geometrical_ means relating to or involving the principles of geometry. 几何学的   +
⇒  Euclid was trying to convey his idea of a geometrical point.  欧几里德正试图表达他的一个几何学观点。   +

---


==== ▸ revoke  [4175]   +
な/rɪˈvəʊk/   +

【V-T】   When people in authority _revoke_ something such as a licence, a law, or an agreement, they cancel it. 撤销; 废除   +
⇒  The government revoked her husband's licence to operate migrant labour crews.  政府撤销了她丈夫经营流动劳工团队的许可证。   +

---


==== ▸ profound  [4176]   +
な/prəˈfaʊnd/   +

【ADJ】   You use _profound_ to emphasize that something is very great or intense. 深刻的; 极大的   +
⇒  ...discoveries which had a profound effect on many areas of medicine.  …对医学的许多领域都有深刻影响的一些发现。   +
⇒  ...profound disagreement.  …极大的分歧。   +

【ADV】   深刻地; 极大地   +
⇒  This has profoundly affected my life.  这已极大地影响了我的生活。   +

【ADJ】   A _profound_ idea, work, or person shows great intellectual depth and understanding. 高深的   +
⇒  This is a book full of profound, original, and challenging insights.  这是一本充满高深、新颖且富有挑战性见解的书。   +

---


==== ▸ urgent  [4177]   +
な/ˈɜːdʒənt/   +

【ADJ】   If something is _urgent_, it needs to be dealt with as soon as possible. 紧急的; 迫切的   +
⇒  There is an urgent need for food and water.  有着对食品和水的迫切需要。   +

【N-UNCOUNT】   紧急性; 迫切性   +
⇒  The urgency of finding a cure attracted some of the best minds in medical science.  因迫切需要找到一种治疗方法，医学界的一些最优秀的人才前仆后继。   +

【ADJ】   If you speak in an _urgent_ way, you show that you are anxious for people to notice something or to do something. 急切的   +
⇒  His voice was low and urgent.  他的声音低沉而急切。   +

【N-UNCOUNT】   急切   +
⇒  She was surprised at the urgency in his voice.  她对他声音的急切感到吃惊。   +

---


==== ▸ thesis  [4178]   +
な/ˈθiːsɪs/   +

【N-COUNT】   A _thesis_ is an idea or theory that is expressed as a statement and is discussed in a logical way. 论点   +
⇒  This thesis does not stand up to close inspection.  这个论点经不起仔细推敲。   +

【N-COUNT】   A _thesis_ is a long piece of writing based on your own ideas and research that you do as part of a college degree, especially a higher degree such as a Ph.D. 学位论文   +

---


==== ▸ customs  [4179]   +
な/ˈkʌstəmz/   +

【N-PROPER】  _Customs_ is the official organization responsible for collecting taxes on goods coming into a country and preventing illegal goods from being brought in. 海关部门   +
⇒  What right does Customs have to search my car?  海关有什么权力搜查我的车？   +

【N-UNCOUNT】  _Customs_ is the place where people arriving from a foreign country have to declare goods that they bring with them. 海关   +
⇒  He walked through customs.  他步行通过了海关。   +

【ADJ】  _Customs_ duties are taxes that people pay for importing and exporting goods. 海关的   +
⇒  Personal property which is to be re-exported at the end of your visit is not subject to customs duties.  停留结束时要再次带出境的个人物品免收关税。   +

---


==== ▸ plow  [4180]   +
な/plaʊ/   +

---


==== ▸ yelp  [4181]   +
な/jɛlp/   +

【V-I】   If a person or dog _yelps_, they give a sudden short cry, often because of fear or pain. (因害怕或痛楚)尖叫; (狗)嚎叫   +
⇒  Her dog yelped and came to heel.  她的狗汪地叫了一声，紧跟了上来。   +

【N-COUNT】  _Yelp_ is also a noun. 尖叫; 嚎叫   +
⇒  I had to bite back a yelp of surprise.  我只好强忍着，没有惊叫出来。   +

---


==== ▸ hypothesis  [4182]   +
な/haɪˈpɒθɪsɪs/   +

【N-VAR】   A _hypothesis_ is an idea which is suggested as a possible explanation for a particular situation or condition, but which has not yet been proved to be correct. 假设   +
⇒  Work will now begin to test the hypothesis in rats.  在老鼠身上验证这一假设的工作现在要开始了。   +

---


==== ▸ shield  [4183]   +
な/ʃiːld/   +

【N-COUNT】   Something or someone which is a _shield_ against a particular danger or risk provides protection from it. 防护物; 保护人   +
⇒  He used his left hand as a shield against the reflecting sunlight.  他用左手遮挡反射过来的阳光。   +

【V-T】   If something or someone _shields_ you _from_ a danger or risk, they protect you from it. 保护   +
⇒  He shielded his head from the sun with an old sack.  他用一个旧袋子遮住头来防晒。   +

【V-T】   If you _shield_ your eyes, you put your hand above your eyes to protect them from direct sunlight. 遮挡   +
⇒  He squinted and shielded his eyes.  他眯着眼并遮住眼睛。   +

【N-COUNT】   A _shield_ is a large piece of metal or leather which soldiers used to carry to protect their bodies while they were fighting. 盾   +
⇒  He clanged his sword three times on his shield.  他用他的剑当当当地敲了3下盾。   +

【N-COUNT】   A _shield_ is a sports prize or badge that is shaped like a shield. 盾形奖章; 盾形徽章   +

---


==== ▸ rainbow  [4184]   +
な/ˈreɪnˌbəʊ/   +

【N-COUNT】   A _rainbow_ is an arch of different colours that you can sometimes see in the sky when it is raining. 彩虹   +
⇒  ...silk and satin in every shade of the rainbow.  …如彩虹般五颜六色的丝绸与锦缎。   +

---


==== ▸ submit  [4185]   +
な/səbˈmɪt/   +

【V-I】   If you _submit to_ something, you unwillingly allow something to be done to you, or you do what someone wants, for example because you are not powerful enough to resist. 屈从   +
⇒  In desperation, Mrs. Jones submitted to an operation on her right knee to relieve the pain.  绝望中，琼斯夫人不得已接受了一次她右膝的手术以减轻疼痛。   +

【V-T】   If you _submit_ a proposal, report, or request _to_ someone, you formally send it to them so that they can consider it or decide about it. 提交 (建议、报告或请求)   +
⇒  They submitted their reports to the chancellor yesterday.  他们昨天向财政大臣提交了他们的报告。   +

---


==== ▸ downside  [4186]   +
な/ˈdaʊnˌsaɪd/   +

【N-SING】   The _downside of_ a situation is the aspect of it which is less positive, pleasant, or useful than its other aspects. 不利的一面   +
⇒  The downside of this approach is a lack of clear leadership.  这种方式的不足之处是缺乏明确的指挥。   +

---


==== ▸ gilding  [4187]   +
な/ˈɡɪldɪŋ/   +

【N-UNCOUNT】  _Gilding_ is a layer of gold or gold paint that is put on something. 镀金层   +

---


==== ▸ puff  [4188]   +
な/pʌf/   +

【V-I】   If someone _puffs on_ or _at_ a cigarette, cigar, or pipe, they smoke it. 抽 (香烟、雪茄、烟斗等)   +
⇒  He lit a cigar and puffed on it twice.  他点上一支雪茄，抽了两口。   +

【N-COUNT】  _Puff_ is also a noun. 一口烟   +
⇒  I took a puff on the cigarette and started coughing.  我抽了一口烟就开始咳嗽起来。   +

【V-T/V-I】   If you _puff_ smoke or moisture from your mouth or if it _puffs_ from your mouth, you breathe it out. (从口中) 喷出   +
⇒  Richard lit another cigarette and puffed smoke toward the ceiling.  理查德点上另一支烟，将烟雾喷向天花板。   +

【PHRASAL VERB】  _Puff out_ means the same as . (从口中) 喷出   +
⇒  He drew heavily on his cigarette and puffed out a cloud of smoke.  他深深地吸了一口烟，喷出了一团烟雾。   +

【V-T】   If an engine, chimney, or stove _puffs_ smoke or steam, clouds of smoke or steam come out of it. (发动机、烟囱或炉子等) 喷   +
⇒  As I completed my 26th lap the Porsche puffed blue smoke.  我跑完第26圈时，保时捷车喷起了蓝色的烟雾。   +

【N-COUNT】   A _puff of_ something such as air or smoke is a small amount of it that is blown out from somewhere. 一股   +
⇒  Wind caught the sudden puff of dust and blew it inland.  风夹裹着那股突然扬起的尘土，把它吹向内陆。   +

【V-I】   If you _are puffing_, you are breathing loudly and quickly with your mouth open because you are out of breath after a lot of physical effort. 喘粗气   +
⇒  I know nothing about boxing, but I could see he was unfit, because he was puffing.  我对拳击一无所知，但我看得出他身体不行，因为他直喘粗气。   +

---


==== ▸ accord  [4189]   +
な/əˈkɔːd/   +

【N-COUNT】   An _accord_ between countries or groups of people is a formal agreement; for example, to end a war. 协议   +
⇒  UNITA was legalized as a political party under the 1991 peace accords.  根据1991年和平协议，安盟作为一个政党被合法化了。   +

【V-T】   If you _are accorded_ a particular kind of treatment, people act toward you or treat you in that way. 给予 (某种待遇)   +
⇒  His predecessor was accorded an equally tumultuous welcome.  他的前任受到了同样热烈的欢迎。   +
⇒  On his return home, the government accorded him the rank of Colonel.  在他回国时，该国政府授予他上校军衔。   +

【PHRASE】   If something happens _of its own accord_, it seems to happen by itself, without anyone making it happen. 自动地   +
⇒  In many cases the disease will clear up of its own accord.  在很多情况下这种疾病会自动地痊愈。   +

【PHRASE】   If you do something _of_ your _own accord_, you do it because you want to, without being asked or forced. 自愿地   +
⇒  He did not quit as France's prime minister of his own accord.  他不是自愿地辞去法国总理一职的。   +

---


==== ▸ outfit  [4190]   +
な/ˈaʊtˌfɪt/   +

【N-COUNT】   An _outfit_ is a set of clothes. 全套服装   +
⇒  She was wearing an outfit she'd bought the previous day.  她穿着前一天买的一套服装。   +

【N-COUNT】   You can refer to an organization as an _outfit_. 机构   +
⇒  He works for a private security outfit.  他在一家私人保安公司工作。   +

---


==== ▸ conscientious  [4191]   +
な/ˌkɒnʃɪˈɛnʃəs/   +

【ADJ】   Someone who is _conscientious_ is very careful to do their work properly. 认真的   +
⇒  We are generally very conscientious about our work.  我们一般对工作都是很认真的。   +

【ADV】   认真地   +
⇒  He studied conscientiously and enthusiastically.  他认真积极地学习。   +

---


==== ▸ tender  [4192]   +
な/ˈtɛndə/   +

【ADJ】   Someone or something that is _tender_ expresses gentle and caring feelings. 温柔的   +
⇒  Her voice was tender, full of pity.  她的声音很温柔，充满了怜悯。   +

【ADV】   温柔地   +
⇒  Mr. White tenderly embraced his wife.  怀特先生温柔地拥抱了妻子。   +

【ADJ】   If you say that someone does something at a _tender_ age, you mean that they do it when they are still young and have not had much experience. 幼小的   +
⇒  He took up the game at the tender age of seven.  他在7岁的小小年纪就开始从事这项运动。   +

【ADJ】   Meat or other food that is _tender_ is easy to cut or chew. (肉等食物) 嫩的; 易嚼的   +
⇒  Cook for a minimum of 2 hours, or until the meat is tender.  至少煮两个小时，或一直煮到肉软了为止。   +

【ADJ】   If part of your body is _tender_, it is sensitive and painful when it is touched. (身体部位) 敏感的; 易触痛的   +
⇒  My tummy felt very tender.  我的肚子一碰就痛。   +

【N-UNCOUNT】   触痛   +
⇒  There is still some tenderness in her ankle.  她的脚踝还有些触痛。   +
 ▷ tender   +
な/ˈtɛndə/   +

【N-UNCOUNT】     +

【N-VAR】   A _tender_ is a formal offer to supply goods or to do a particular job, and a statement of the price that you or your company will charge. If a contract is _put out to tender_, formal offers are invited. If a company _wins a tender_, their offer is accepted. 投标   +
⇒  Builders will then be sent the specifications and asked to submit a tender for the work.  然后建筑商们将会接到设计说明并被邀请参与此项工程的投标。   +

【N】   a small boat, such as a dinghy, towed or carried by a yacht or ship 小艇   +

【V-I】   If a company _tenders for_ something, it makes a formal offer to supply goods or do a job for a particular price. 投标   +
⇒  The staff are forbidden to tender for private-sector work.  员工们禁止投标私营部门的工程。   +

【V】   to give, present, or offer 提出; 提供   +
⇒  to tender one's resignation     +
⇒  tender a bid     +

---


==== ▸ quaint  [4193]   +
な/kweɪnt/   +

【ADJ】   Something that is _quaint_ is attractive because it is old-fashioned. 古雅的   +
⇒  ...a small, quaint town with narrow streets and traditional half-timbered houses.  …一座古朴的小镇，有着狭窄的街道和传统的半木制房屋。   +

---


==== ▸ chagrin  [4194]   +
な/ˈʃæɡrɪn/   +

【N-UNCOUNT】  _Chagrin_ is a feeling of disappointment, upset, or annoyance, perhaps because of your own failure. 失望; 懊恼   +
⇒  To the chagrin of their parents, neither Phil nor Pam went to church anymore.  令父母失望的是，菲尔和帕姆都再也不去教堂了。   +

---


==== ▸ projector  [4195]   +
な/prəˈdʒɛktə/   +

【N-COUNT】   A _projector_ is a machine that projects films or slides onto a screen or wall. 放映机; 投影仪   +
⇒  ...a slide projector.  …幻灯机。   +

---


==== ▸ initial  [4196]   +
な/ɪˈnɪʃəl/   +

【ADJ】   You use _initial_ to describe something that happens at the beginning of a process. 最初的   +
⇒  The initial reaction has been excellent.  最初的反应极好。   +

【N-COUNT】  _Initials_ are the capital letters that begin each word of a name. For example, if your full name is Michael Dennis Stocks, your initials are M.D.S. (姓名的) 大写首字母   +
⇒  ...a silver Porsche with her initials JB on the side.  …一辆银色保时捷汽车，侧面有她的姓名首字母JB。   +

【V-T】   If someone _initials_ an official document, they write their initials on it, to show that they have seen it or that they accept or agree with it. 签姓名的首字母于   +
⇒  Would you mind initialling this voucher?  请您在这张单子上签上姓名的首字母，好吗？   +

---


==== ▸ relieve  [4197]   +
な/rɪˈliːv/   +

【V-T】   If something _relieves_ an unpleasant feeling or situation, it makes it less unpleasant or causes it to disappear completely. 缓解; 减轻; 解除   +
⇒  Drugs can relieve much of the pain.  药物可以大大缓解疼痛。   +

【V-T】   If someone or something _relieves_ you _of_ an unpleasant feeling or difficult task, they take it from you. 使解脱; 使摆脱   +
⇒  A part-time bookkeeper will relieve you of the burden of chasing unpaid invoices.  一名兼职簿记员将使你摆脱追讨欠款的负担。   +

【V-T】   If you _relieve_ someone, you take their place and continue to do the job or duty that they have been doing. 接 (某人) 的班; 接替   +
⇒  At seven o'clock the night nurse came in to relieve her.  7点钟时值夜班的护士进来接了她的班。   +

【V-T】   If someone _is relieved of_ their duties or _is relieved of_ their post, they are told that they are no longer required to continue in their job. 使解除 (职务); 使免除 (职位)   +
⇒  The officer involved was relieved of his duties because he had violated strict guidelines.  该名军官因违反了严格的准则而被解除了职务。   +

---


==== ▸ silicon  [4198]   +
な/ˈsɪlɪkən/   +

【N-UNCOUNT】  _Silicon_ is an element that is found in sand and in minerals such as quartz and granite. Silicon is used to make parts of computers and other electronic equipment. 硅   +
⇒  The new chip will be made from a piece of silicon about the size of a postage stamp.  这种新的芯片将由大约邮票大小的一块硅片制成。   +

---


==== ▸ track  [4199]   +
な/træk/   +

【N-COUNT】   A _track_ is a rough, unpaved road or path. (崎岖不平的) 小路   +
⇒  We set off once more, over a rough mountain track.  我们又一次出发了，走在一条崎岖不平的山间小路上。   +

【N-COUNT】   A _track_ is a piece of ground, often oval-shaped, that is used for races involving running, cars, bicycles, horses, or dogs called greyhounds. 跑道   +
⇒  ...the athletics track.  …那条运动员跑道。   +

【N-COUNT】   Railway _tracks_ are the rails that a train travels along. 铁轨   +
⇒  A cow stood on the tracks.  一头奶牛站在铁轨上。   +

【N-COUNT】   A _track_ is one of the songs or pieces of music on a CD, record, or tape. (录制在CD、唱片或磁带上的) 一首歌曲; 一首乐曲   +
⇒  I only like two of the ten tracks on this CD.  我只喜欢这张CD上的10首歌曲中的2首。   +

【N-PLURAL】  _Tracks_ are marks left in the ground by the feet of animals or people. 足迹   +
⇒  The only evidence of pandas was their tracks in the snow.  有熊猫活动的惟一证据就是它们在雪中的足迹。   +

【V-T】   If you _track_ animals or people, you try to follow them by looking for the signs that they have left behind, for example, the marks left by their feet. 跟踪   +
⇒  He thought he had better track this wolf and see where it lived.  他认为他最好跟踪这只狼，并看看它在哪儿生活。   +

【V-T】   To _track_ someone or something means to follow their movements by means of a special device, such as a satellite or radar. (用卫星、雷达等特殊装置) 追踪   +
⇒  Our radar began tracking the jets.  我们的雷达开始追踪那些喷气式飞机。   +

【PHRASE】   If you _keep track of_ a situation or a person, you make sure that you have the newest and most accurate information about them all the time. 了解…的动向   +
⇒  With eleven thousand employees, it's very difficult to keep track of them all.  有11000名员工，很难了解他们所有人的动向。   +

【PHRASE】   If you _lose track of_ someone or something, you no longer know where they are or what is happening. 不了解…的进展   +
⇒  You become so deeply absorbed in an activity that you lose track of time.  你是那么专注于一项活动，以致忘了时间。   +

【PHRASE】   If someone or something is _on track_, they are acting or progressing in a way that is likely to result in success. 步入正轨   +

【PHRASE】   If you are _on the right track_, you are acting or progressing in a way that is likely to result in success. If you are _on the wrong track_, you are acting or progressing in a way that is likely to result in failure. 做得正确/不正确   +
⇒  Guests are returning in increasing numbers – a sure sign that we are on the right track.  回头客越来越多–一个我们做得对的确凿迹象。   +

【PHRASE】   If someone or something _stops_ you _in_ your _tracks_, or if you _stop dead in_ your _tracks_, you suddenly stop moving because you are very surprised, impressed, or frightened. (因吃惊、感动或惊恐) 突然停住脚步   +
⇒  This magnificent church cannot fail to stop you in your tracks.  这座宏伟的教堂一定会让你叹为观止。   +

【PHRASE】   If someone or something _stops_ a process or activity _in its tracks_, or if it _stops dead in its tracks_, they prevent the process or activity from continuing. 中断   +
⇒  Francis felt he would like to stop this conversation in its tracks.  弗朗西斯觉得他想中断这次谈话。   +

---


==== ▸ depredation  [4200]   +
な/ˌdɛprɪˈdeɪʃən/   +

【N-VAR】   The _depredations_ of a person, animal, or force are their harmful actions, which usually involve taking or damaging something. 掠夺; 破坏   +
⇒  Much of the region's environmental depredation is a result of poor planning.  这个地区的环境破坏大都是规划不周的结果。   +

---


==== ▸ naval  [4201]   +
な/ˈneɪvəl/   +

【ADJ】  _Naval_ means belonging to, relating to, or involving a country's navy. 海军的   +
⇒  He was the senior serving naval officer.  他曾是高级现役海军军官。   +

---


==== ▸ dogged  [4202]   +
な/ˈdɒɡɪd/   +

【ADJ】   If you describe someone's actions as _dogged_, you mean that they are determined to continue with something even if it becomes difficult or dangerous. 顽强的   +
⇒  They have, through sheer dogged determination, slowly gained respect for their efforts.  他们凭借顽强的毅力慢慢地为自己的努力赢得了尊重。   +

【ADV】   顽强地   +
⇒  She would fight doggedly for her rights as the children's mother.  她会顽强地为她作为孩子们母亲的权利而斗争。   +

---


==== ▸ terrorism  [4203]   +
な/ˈtɛrəˌrɪzəm/   +

【N-UNCOUNT】  _Terrorism_ is the use of violence, especially murder and bombing, in order to achieve political goals or to force a government to do something. 恐怖主义   +
⇒  ...the threat of global terrorism.  …全球恐怖主义的威胁。   +

---


==== ▸ spacecraft  [4204]   +
な/ˈspeɪsˌkrɑːft/   +

【N-COUNT】   A _spacecraft_ is a rocket or other vehicle that can travel in space. 航天器   +
⇒  ...the world's largest and most expensive unmanned spacecraft.  …世界上最大、最贵的无人航天器。   +

---


==== ▸ subsidy  [4205]   +
な/ˈsʌbsɪdɪ/   +

【N-COUNT】   A _subsidy_ is money that is paid by a government or other authority in order to help an industry or business, or to pay for a public service. 补贴金   +
⇒  European farmers are planning a massive demonstration against farm subsidy cuts.  欧洲的农场主们正在策划一场反对削减农场补贴的大游行。   +

---


==== ▸ tempt  [4206]   +
な/tɛmpt/   +

【V-T】   Something that _tempts_ you attracts you and makes you want it, even though it may be wrong or harmful. 引诱; 吸引   +
⇒  Cars like that may tempt drivers to speed.  那样的汽车可能会引诱司机超速行驶。   +
⇒  It is the fresh fruit that tempts me at this time of year.  只有新鲜的水果才会在每年的这个时候吸引我。   +

【V-T】   If you _tempt_ someone, you offer them something they want in order to encourage them to do what you want them to do. 诱使   +
⇒  ...a million dollar marketing campaign to tempt American tourists back to Britain.  …旨在诱使美国游客回到英国的、耗资一百万美元的营销活动。   +
⇒  Don't let credit tempt you to buy something you can't afford.  不要让赊购诱使你去购买你支付不起的东西。   +

---


==== ▸ drill  [4207]   +
な/drɪl/   +

【N-COUNT】   A _drill_ is a tool or machine that you use for making holes. 钻孔机   +
⇒  ...a dentist's drill.  …一把牙钻。   +

【N-COUNT】   A _drill_ is a routine exercise or activity, in which people practise what they should do in dangerous situations. 操练   +
⇒  ...a fire drill.  …一场消防演习。   +

【V-T/V-I】   When you _drill into_ something or _drill_ a hole in something, you make a hole in it using a drill. 钻 (孔); 打 (眼)   +
⇒  He drilled into the wall of Lili's bedroom.  他在丽莉卧室的墙上打孔。   +

【V-I】   When people _drill for_ oil or water, they search for it by drilling deep holes in the ground or in the bottom of the sea. 钻探 (石油或地下水源)   +
⇒  There have been proposals to drill for more oil.  有人提出了钻探更多石油的建议。   +

【N-VAR】   A _drill_ is repeated training for a group of people, especially soldiers, so that they can do something quickly and efficiently. 训练   +
⇒  The Marines carried out landing exercises in a drill that includes 18 ships and 90 aircraft.  海军陆战队在一场军事训练中进行了登陆练习，包括18艘军舰和90架飞机。   +

【V】   to teach by rigorous exercises or training (通过严格训练来)教学   +

【N】   a machine for planting seeds in rows or depositing fertilizer 条播机   +

【V】   to plant (seeds) by means of a drill 条播   +

【N】   a hard-wearing twill-weave cotton cloth, used for uniforms, etc 粗斜纹布   +

【N】   an Old World monkey, _Mandrillus leucophaeus,_ of W Africa, related to the mandrill but smaller and less brightly coloured (西非)鬼狒   +

---


==== ▸ sedimentary  [4208]   +
な/ˌsɛdɪˈmɛntərɪ/   +

【ADJ】  _Sedimentary_ rocks are formed from sediment left by water, ice, or wind. (岩石)沉积的   +

---


==== ▸ magnet  [4209]   +
な/ˈmæɡnɪt/   +

【N-COUNT】   If you say that something is a _magnet_ or is like a _magnet_, you mean that people are very attracted by it and want to go to it or look at it. 有吸引力的事物   +
⇒  Prospect Park, with its vast lake, is a magnet for all health freaks.  拥有大片湖区的展望公园是所有健身迷的向往之地。   +

【N-COUNT】   A _magnet_ is a piece of iron or other material which attracts iron toward it. 磁体   +
⇒  It's possible to hang a nail from a magnet and then use that nail to pick up another nail.  把一颗钉子挂在一个磁体上再用这颗钉子去吸起另一颗钉子是可能的。   +

---


==== ▸ evidence  [4210]   +
な/ˈɛvɪdəns/   +

【N-UNCOUNT】  _Evidence_ is anything that you see, experience, read, or are told that causes you to believe that something is true or has really happened. 证据; 依据   +
⇒  Ganley said he'd seen no evidence of widespread fraud.  甘利说他没有看见欺骗行为泛滥的证据。   +

【N-UNCOUNT】  _Evidence_ is the information that is used in a court of law to try to prove something. Evidence is obtained from documents, objects, or witnesses. (法律上的) 证据   +
⇒  The evidence against him was purely circumstantial.  不利于他的证据纯粹是间接证据。   +

【PHRASE】   If you _give evidence_ in a court of law or an official inquiry, you officially say what you know about people or events, or describe an occasion at which you were present. (在法庭上或官方调查中) 作证   +
⇒  The forensic scientists who carried out the original tests will be called to give evidence.  那些进行了原始化验的法医学家们将被叫去作证。   +

【PHRASE】   If someone or something _is in evidence_, they are present and can be clearly seen. 显然可见   +
⇒  Few soldiers were in evidence.  几乎看不见有士兵。   +

---


==== ▸ locomotive  [4211]   +
な/ˌləʊkəˈməʊtɪv/   +

【N-COUNT】   A _locomotive_ is a large vehicle that pulls a train. 火车头   +

---


==== ▸ packed  [4212]   +
な/pækt/   +

【ADJ】   A place that is _packed_ is very crowded. 拥挤的   +
⇒  The place is packed at lunchtime.  这个地方在午餐时间非常拥挤。   +
⇒  ...a packed meeting in Detroit.  …一个在底特律召开的座无虚席的会议。   +

【ADJ】   Something that is _packed with_ things contains a very large number of them. 充满的   +
⇒  The encyclopedia is packed with clear illustrations and over 250 recipes.  这本百科全书充满了清晰的插图，还有二百五十多个食谱。   +

---


==== ▸ hustle  [4213]   +
な/ˈhʌsəl/   +

【V-T】   If you _hustle_ someone, you try to make them go somewhere or do something quickly, for example by pulling or pushing them along. 猛拉; 猛推   +
⇒  The guards hustled Harry out of the car.  卫兵们把哈里从车子里拉了出来。   +

【V-I】   If you _hustle_, you go somewhere or do something as quickly as you can. 快速行进; 赶快做   +
⇒  You'll have to hustle if you're to get home for supper.  你想回家吃晚饭的话，得赶紧走了。   +

【V-I】   If someone _hustles_, they try hard to earn money or to gain an advantage from a situation. 奋力争取   +
⇒  I like it here. It forces you to hustle and you can earn money.  我喜欢在这里生活。这个想法迫使你拼命干活，这样可以挣到钱。   +
⇒  Hustling for social contacts isn't something that just happens. You have to make it happen.  社会关系不是说建立就建立起来的，你得想尽一切办法去争取。   +

【V-T】   If someone _hustles_ you, or if they _hustle_ something, they try hard to get something, often by using dishonest or illegal means. 诈取 (通常用不正当或非法的手段)   +
⇒  Two teenage boys asked us for money, saying they were forming a baseball team. Anna said they were hustling us.  两个小男孩向我们要钱，说他们要成立棒球队。安娜说他们在骗钱。   +
⇒  He hustled several daytime jobs and finished his education at night.  他骗得了几份白班工作，利用晚上完成了学业。   +

【N-UNCOUNT】  _Hustle_ is busy, noisy activity. 忙碌; 熙熙攘攘   +
⇒  ...the hustle and bustle of New York.  …纽约的熙攘喧闹。   +

---


==== ▸ landslide  [4214]   +
な/ˈlændˌslaɪd/   +

【N-COUNT】   A _landslide_ is a victory in an election in which a person or political party gets far more votes or seats than their opponents. (选举中) 压倒性优势的胜利   +
⇒  He won last month's presidential election by a landslide.  他以绝对优势赢得了上个月的总统选举。   +

【N-COUNT】   A _landslide_ is a large amount of earth and rocks falling down a cliff or the side of a mountain. 山崩   +
⇒  The storm caused landslides and flooding in Savona.  暴风雨引发了萨沃纳的山崩和水灾。   +

---


==== ▸ consolidate  [4215]   +
な/kənˈsɒlɪˌdeɪt/   +

【V-T】   If you _consolidate_ something that you have, for example power or success, you strengthen it so that it becomes more effective or secure. 巩固   +
⇒  The question is: will the junta consolidate its power by force?  问题是，这个军政府会通过武力来巩固它的政权吗？   +

【V-T】   To _consolidate_ a number of small groups or companies means to make them into one large organization. 合并   +
⇒  Judge Charles Schwartz is giving the state 60 days to disband and consolidate Louisiana's four higher education boards.  查尔斯·施瓦茨法官给该州60天解散且合并路易斯安那的4个高等教育委员会。   +

---


==== ▸ argue  [4216]   +
な/ˈɑːɡjuː/   +

【V-RECIP】   If one person _argues with_ another, they speak angrily to each other about something that they disagree about. You can also say that two people _argue_. 争吵   +
⇒  The committee is concerned about players' behaviour, especially arguing with referees.  该委员会担心运动员的表现，尤其担心他们与裁判争吵。   +

【V-RECIP】   If you _argue with_ someone _about_ something, you discuss it with them, with each of you giving your different opinions. 讨论   +
⇒  He was arguing with the king about the need to maintain the cavalry at full strength.  他在和国王讨论保留骑兵全部兵力的必要性。   +
⇒  They are arguing over foreign policy.  他们在讨论外交政策。   +

【V-I】   If you tell someone not to _argue with_ you, you want them to do or believe what you say without protest or disagreement. 争辩   +
⇒  Don't argue with me.  不要和我争辩。   +

【V-T】   If you _argue that_ something is true, you state it and give the reasons why you think it is true. 辩论   +
⇒  His lawyers are arguing that he is unfit to stand trial.  他的律师们在辩称他不适宜受审。   +

【V-I】   If you _argue for_ something, you say why you agree with it, in order to persuade people that it is right. If you _argue against_ something, you say why you disagree with it, in order to persuade people that it is wrong. 陈述理由   +
⇒  The report argues against tax increases.  该报告陈述理由反对增税。   +

---


==== ▸ qualify  [4217]   +
な/ˈkwɒlɪˌfaɪ/   +

【V-I】   If you _qualify_ in a competition, you are successful in one part of it and go on to the next stage. 通过预赛; 取得下一轮比赛资格   +
⇒  We qualified for the final by beating Stanford on Tuesday.  我们在星期二击败了斯坦福队，取得了决赛资格。   +

【N-COUNT】   通过预赛者   +
⇒  Kenya's Robert Kibe was the fastest qualifier for the 800 metres final.  肯尼亚的罗伯特·凯布是800米决赛入围者中速度最快的选手。   +

【V-T/V-I】   To _qualify as_ something or to _be qualified as_ something means to have all the features that are needed to be that thing. 使…符合 (某物的全部特征); 符合   +
⇒  13 percent of American households qualify as poor, says Mr. Mishel.  13％的美国家庭称得上是贫民，米歇尔先生说。   +

【V-T】   If you _qualify_ a statement, you make it less strong or less general by adding a detail or explanation to it. (通过增加细节、解释) 使语气缓和; 使…不太笼统   +
⇒  I would qualify that by putting it into context.  我会把它放入上下文中加以解释。   +
⇒  Boyd qualified his opinion, noting that the evidence could be interpreted in other ways.  博伊德补充说明了他的观点，指出证据可以用其他方式加以解释。   +

【V-T/V-I】   If you _qualify_ for something or if something _qualifies_ you for it, you have the right to do it or have it. (使) 有权做; (使) 有资格拥有   +
⇒  To qualify for maternity leave you must have worked for the same employer for two years.  你必须为同一雇主工作两年才有资格休产假。   +
⇒  The basic course does not qualify you to practise as a therapist.  这门基础课程并不能使你有资格当一名治疗师。   +

【V-I】   When someone _qualifies_, they receive the certificate, licence, diploma, or degree that they need to be able to work in a particular profession. 取得资格; 获得文凭   +
⇒  But when I'd qualified and started teaching it was a different story.  但是当我取得资格并开始从教时，情况就完全不同了。   +

---


==== ▸ implication  [4218]   +
な/ˌɪmplɪˈkeɪʃən/   +

【N-COUNT】  _The__implications__of_ something are the things that are likely to happen as a result. 可能的结果   +
⇒  The Attorney General was aware of the political implications of his decision to prosecute.  总检察长知道自己起诉的决定可能引起的政治后果。   +

【N-COUNT】  _The__implication_ of a statement, event, or situation is what it implies or suggests is the case. 含意   +
⇒  The implication was obvious: vote for us or it will be very embarrassing for you.  含意很明显：投票给我们，否则你会很难堪。   +

【PHRASE】   If you say that something is the case _by implication_, you mean that a statement, event, or situation implies that it is the case. 言下之意; 暗示地   +
⇒  Now his authority and, by implication, that of the whole management team are under threat as never before.  言下之意，现在他的权力以及整个管理团队的权威正面临空前的威胁。   +

---


==== ▸ temporary  [4219]   +
な/ˈtɛmpərərɪ/   +

【ADJ】   Something that is _temporary_ lasts for only a limited time. 暂时的   +
⇒  His job here is only temporary.  他在这儿的工作只是暂时的。   +
⇒  Most adolescent problems are temporary.  多数青春期的问题都是暂时的。   +

【ADV】   暂时地   +
⇒  The peace agreement has at least temporarily halted the civil war.  该和平协议至少已暂时中止了内战。   +

---


==== ▸ dictate  [4220]   +
な【V-T】   If you _dictate_ something, you say or read it aloud for someone else to write down. 口授; 使听写   +
⇒  Sheldon writes every day of the week, dictating his novels in the morning.  谢尔登每天都进行创作，在上午口述他的小说。   +

【V-T】   If someone _dictates to_ someone else, they tell them what they should do or can do. 指示; 命令   +
⇒  What right has one country to dictate the environmental standards of another?  一个国家有什么权利规定另一个国家的环境标准？   +
⇒  What gives them the right to dictate to us what we should eat?  是什么给他们权利来规定我们该吃什么？   +

【V-T】   If one thing _dictates_ another, the first thing causes or influences the second thing. 导致; 影响   +
⇒  The film's budget dictated a tough schedule.  该影片的预算决定了紧张的拍摄进度。   +
⇒  Of course, a number of factors will dictate how long an apple tree can survive.  当然，一棵苹果树能存活多久是由许多因素决定的。   +

【V-T】   You say that logic or common sense _dictates that_ a particular thing is the case when you believe strongly that it is the case and that logic or common sense will cause other people to agree. (逻辑或常识) 使人相信   +
⇒  Logic dictates that our ancestors could not have held a yearly festival until they figured what a year was.  依照逻辑推论，我们的祖先在弄清1年是什么意思之前，不可能举行过每年一度的节庆。   +

【N-COUNT】  _Dictates_ are principles or rules which you consider to be extremely important. 原则; 规定   +
⇒  We have followed the dictates of our consciences and have done our duty.  我们凭良心做事，尽了我们的职责。   +

---


==== ▸ absorb  [4221]   +
な/əbˈsɔːb, -ˈzɔːb/   +

【V-T】   If something _absorbs_ a liquid, gas, or other substance, it soaks it up or takes it in. 吸收 (液体、气体等)   +
⇒  Plants absorb carbon dioxide from the air and moisture from the soil.  植物从空气中吸收二氧化碳，从泥土中吸收水分。   +

【V-T】   If something _absorbs_ light, heat, or another form of energy, it takes it in. 吸取 (光、热等能量)   +
⇒  A household radiator absorbs energy in the form of electric current and releases it in the form of heat.  家用暖气以电流的形式吸收能量，然后以热量的形式将其释放出去。   +

【V-T】   If a group _is absorbed into_ a larger group, it becomes part of the larger group. 使并入   +
⇒  City schools were absorbed into the countywide school district.  市立学校被并入了郡学区。   +

【V-T】   If something _absorbs_ a force or shock, it reduces its effect. 使缓冲   +
⇒  ...footwear which does not absorb the impact of the foot striking the ground.  …不能缓冲脚踏在地面上所产生的冲击力的鞋子。   +

【V-T】   If a system or society _absorbs_ changes, effects, or costs, it is able to deal with them. 能应付   +
⇒  The banks would be forced to absorb large losses.  这些银行将被迫承担那些巨大的损失。   +

【V-T】   If something _absorbs_ something valuable such as money, space, or time, it uses up a great deal of it. 大量消耗   +
⇒  It absorbed vast amounts of capital that could have been used for investment.  它消耗掉了原本可以用作投资的大量资本。   +

【V-T】   If you _absorb_ information, you learn and understand it. 理解   +
⇒  Too often he only absorbs half the information in the manual.  通常，他对手册里的信息只是一知半解。   +

【V-T】   If something _absorbs_ you, it interests you a great deal and takes up all your attention and energy. 使专注   +
⇒  ...a second career which absorbed her more completely than her acting ever had.  …一个比其演艺事业更让她全身心投入的第二职业。   +

---


==== ▸ picky  [4222]   +
な/ˈpɪkɪ/   +

【ADJ】   Someone who is _picky_ is difficult to please and only likes a small range of things. 爱挑剔的; 过分讲究的   +
⇒  Some people are very picky about who they choose to share their lives with.  有些人对选择跟什么样的人共享生活非常挑剔。   +

---


==== ▸ curtsy  [4223]   +
な/ˈkɜːtsɪ/   +

【V-I】   If a woman or a girl _curtsies_, she lowers her body briefly, bending her knees and sometimes holding her skirt with both hands, as a way of showing respect for an important person. 行屈膝礼   +
⇒  We were taught how to curtsy to the Queen.  有人教我们如何向女王行屈膝礼。   +
⇒  Ingrid shook the Duchess's hand and curtsied.  英格丽德和公爵夫人握手并行了屈膝礼。   +

【N-COUNT】  _Curtsy_ is also a noun. 屈膝礼   +
⇒  She gave a curtsy.  她行了个屈膝礼。   +

---


==== ▸ fulfill  [4224]   +
 辞典中没找到  +
==== ▸ behave  [4225]   +
な/bɪˈheɪv/   +

【V-I】   The way that you _behave_ is the way that you do and say things, and the things that you do and say. 行为; 表现   +
⇒  I couldn't believe these people were behaving in this way.  我无法相信这些人竟这样行事。   +

【V-T/V-I】   If you _behave_ or _behave yourself_, you act in the way that people think is correct and proper. 使…规矩; 规矩地行事   +
⇒  You have to behave.  你得守规矩。   +

【V-I】   In science, the way that something _behaves_ is the things that it does. (科学领域) 运动表现   +
⇒  Under certain conditions, electrons can behave like waves rather than particles.  在某些条件下，电子能像波而不是粒子那样运动。   +

---


==== ▸ foliage  [4226]   +
な/ˈfəʊlɪɪdʒ/   +

【N-UNCOUNT】   The leaves of a plant are referred to as its _foliage_. 叶子   +
⇒  ...shrubs with grey or silver foliage.  …灰叶或银叶灌木丛。   +

---


==== ▸ philosophy  [4227]   +
な/fɪˈlɒsəfɪ/   +

【N-UNCOUNT】  _Philosophy_ is the study or creation of theories about basic things such as the nature of existence, knowledge, and thought, or about how people should live. 哲学   +
⇒  He studied philosophy and psychology at Yale.  他在耶鲁大学学习哲学和心理学。   +

【N-COUNT】   A _philosophy_ is a particular set of ideas that a philosopher has. 哲学思想   +
⇒  ...the philosophies of Socrates, Plato, and Aristotle.  …苏格拉底、柏拉图和亚里士多德的哲学思想。   +

【N-COUNT】   A _philosophy_ is a particular theory that someone has about how to live or how to deal with a particular situation. 人生哲学; 处事原则   +
⇒  The best philosophy is to change your food habits to a low-sugar diet.  最好的生活方式是将你的饮食习惯改成食用低糖食品。   +

---


==== ▸ perpetuate  [4228]   +
な/pəˈpɛtjʊˌeɪt/   +

【V-T】   If someone or something _perpetuates_ a situation, system, or belief, especially a bad one, they cause it to continue. 使继续 (尤指不好的情形、体系或信仰)   +
⇒  We must not perpetuate the religious divisions of the past.  我们绝不能使过去的宗教分裂继续下去。   +

---


==== ▸ augment  [4229]   +
な/ɔːɡˈmɛnt/   +

【V-T】   To _augment_ something means to make it larger, stronger, or more effective by adding something to it. 增加   +
⇒  While searching for a way to augment the family income, she began making dolls.  为求增加家庭收入，她开始做起了玩具娃娃。   +

---


==== ▸ nude  [4230]   +
な/njuːd/   +

【ADJ】   A _nude_ person is not wearing any clothes. 裸体的   +
⇒  The occasional nude bather comes here.  偶尔裸浴的那个人来到这里 。   +

【PHRASE】   If you do something _in the nude_, you are not wearing any clothes. If you paint or draw someone _in the nude_, they are not wearing any clothes. 裸体中   +
⇒  Sleeping in the nude, if it suits you, is not a bad idea.  如果适合你的话，光着身子睡觉并不是一个坏主意。   +

【N-COUNT】   A _nude_ is a picture or statue of a person who is not wearing any clothes. A _nude_ is also a person in a picture who is not wearing any clothes. 裸体画; 裸体雕像; 画像中裸体的人   +
⇒  He was one of Australia's most distinguished artists, renowned for his portraits, landscapes, and nudes.  他是澳大利亚最杰出的艺术家之一，以肖像画、风景画和裸体画而闻名。   +

---


==== ▸ layout  [4231]   +
な/ˈleɪaʊt/   +

【N-COUNT】   The _layout_ of a park, building, or piece of writing is the way in which the parts of it are arranged. (建筑或文章的) 布局   +
⇒  He tried to recall the layout of the farmhouse.  他想回忆那农舍的布局。   +

---


==== ▸ tactile  [4232]   +
な/ˈtæktaɪl/   +

【ADJ】   If you describe someone as _tactile_, you mean that they tend to touch other people a lot when talking to them. 说话时爱碰别人的   +
⇒  The children are very tactile with warm, loving natures.  小孩子说话的同时爱用上充满温暖和爱心的触摸。   +

【ADJ】   Something such as fabric which is _tactile_ is pleasant or interesting to touch. (织物)手感好的   +
⇒  Tweed is timeless, tactile and tough.  粗花呢从不过时，手感很好，结实耐磨。   +

【ADJ】  _Tactile_ experiences or sensations are received or felt by touch. (经验或感觉)触觉的   +
⇒  Babies who sleep with their parents receive much more tactile stimulation than babies who sleep in a crib.  和父母睡在一块儿的婴儿比单独睡在婴儿床上的婴儿得到更多的触觉刺激。   +

---


==== ▸ pause  [4233]   +
な/pɔːz/   +

【V-I】   If you _pause_ while you are doing something, you stop for a short period and then continue. 停顿   +
⇒  "It's rather embarrassing," he began, and paused.  “这很让人尴尬，” 他开始说道，又停顿了片刻。   +
⇒  He talked for two hours without pausing for breath.  他谈了两个小时，没有停下来喘口气。   +

【N-COUNT】   A _pause_ is a short period when you stop doing something before continuing. 停顿   +
⇒  After a pause Al said sharply: "I'm sorry if I've upset you."  停了一下之后艾尔突然说：“如果我让你不安了，我很抱歉。”   +

---


==== ▸ rare  [4234]   +
な/rɛə/   +

【ADJ】   Something that is _rare_ is not common and is therefore interesting or valuable. 稀有的   +
⇒  ...the black-necked crane, one of the rarest species in the world.  …黑颈鹤，世界上最珍稀的物种之一。   +

【ADJ】   An event or situation that is _rare_ does not occur very often. 罕见的   +
⇒  ...on those rare occasions when he did eat alone.  …在他独自吃饭的那些不常有的时候。   +

【ADJ】   You use _rare_ to emphasize an extremely good or remarkable quality. 极好的 (素质)   +
⇒  Ferris has a rare ability to record her observations on paper.  费里斯有将自己的观察结果以书面形式记录下来的杰出能力。   +

【ADJ】   Meat that is _rare_ is cooked very lightly so that the inside is still red. (肉类) 半熟的   +
⇒  Thick tuna steaks are eaten rare, like beef.  厚厚的金枪鱼片要半熟吃，就像牛肉一样。   +

---


==== ▸ scrape  [4235]   +
な/skreɪp/   +

【V-T】   If you _scrape_ something from a surface, you remove it, especially by pulling a sharp object over the surface. 刮掉   +
⇒  She went around the car scraping the frost off the windows.  她绕着车刮掉车窗上的霜。   +

【V-T/V-I】   If something _scrapes_ against something else, it rubs against it, making a noise or causing slight damage. 刮擦   +
⇒  The only sound is that of knives and forks scraping against china.  惟一的声音是刀叉刮擦瓷器的声音。   +
⇒  The car hurtled past us, scraping the wall and screeching to a halt.  那辆汽车从我们身旁疾驰而过，刮擦着墙嘎然停下。   +

【V-T】   If you _scrape_ a part of your body, you accidentally rub it against something hard and rough, and damage it slightly. 擦伤   +
⇒  She stumbled and fell, scraping her palms and knees.  她绊了一跤摔倒了，擦伤了双掌和双膝。   +

---


==== ▸ spin  [4236]   +
な/spɪn/   +

【V-T/V-I】   If something _spins_ or if you _spin_ it, it turns quickly around a central point. 转动   +
⇒  The latest disks, used for small portable computers, spin 3,600 times a minute.  用于小型手提电脑的最新磁盘每分钟转动3600次。   +
⇒  He spun the wheel sharply and made a U turn in the middle of the road.  他猛打方向盘，在路中间掉了个头。   +

【N-VAR】  _Spin_ is also a noun. 旋转   +
⇒  This driving mode allows you to move off in third gear to reduce wheel-spin in icy conditions.  这种驾驶方法可以让你用三档发动汽车以减少结冰情况下的车轮打滑。   +

【V-I】   If your head _is spinning_, you feel unsteady or confused, for example because you are drunk, ill, or excited. 眩晕   +
⇒  My head was spinning from the wine.  当时我因喝了酒而感到眩晕。   +

【N-SING】   If someone puts a certain _spin_ on an event or situation, they interpret it and try to present it in a particular way. (特意做的) 诠释与宣传   +
⇒  He interpreted the vote as support for the constitution and that is the spin his supporters are putting on the results today.  他把这次投票结果解释为对宪法的支持，这也是他的支持者们对今天的结果所做的诠释与宣传。   +

【N-UNCOUNT】   In politics, _spin_ is the way in which political parties try to present everything they do in a positive way to the public and the media. (政治) 粉饰   +
⇒  The public is sick of spin and tired of promises.  公众厌倦了粉饰和许诺。   +

【N-SING】   If you go for _a spin_ or take a car for _a spin_, you make a short trip in a car just to enjoy yourself. 兜风   +
⇒  Tom Wright celebrated his 99th birthday by going for a spin in his sporty Mazda.  汤姆•赖特开着他的运动型马自达车出去兜风以庆祝其99岁生日。   +

【V-T】   When people _spin_, they make thread by twisting together pieces of a fibre such as wool or cotton using a device or machine. 纺; 纺线   +
⇒  Michelle will also spin a customer's wool fleece to specification at a cost of $2.25 an ounce.  米歇尔也将以每盎司$2.25的价格按照顾客的要求为其纺羊毛呢。   +

【N-UNCOUNT】   In a game such as tennis or baseball, if you put _spin_ on a ball, you deliberately make it spin rapidly when you hit it or throw it. (击球或投球时故意使球做出的) 快速旋转   +
⇒  He threw it back again, putting a slight spin on the ball.  他把球略带旋转地又投掷了回去。   +

---


==== ▸ disturb  [4237]   +
な/dɪˈstɜːb/   +

【V-T】   If you _disturb_ someone, you interrupt what they are doing and upset them. 打扰   +
⇒  Did you sleep well? I didn't want to disturb you. You looked so peaceful.  你睡得好吗？我不想打扰你。你看起来如此平静。   +

【V-T】   If something _disturbs_ you, it makes you feel upset or worried. 使不安; 使烦恼   +
⇒  I dream about him, dreams so vivid that they disturb me for days.  我梦到他了，梦是那么栩栩如生以至于困扰了我好几天。   +

【V-T】   If something _is disturbed_, its position or shape is changed. 使紊乱   +
⇒  He'd placed his notes in the brown envelope. They hadn't been disturbed.  他已把票据放在那个棕色信封里了。票据没有被动过。   +

【V-T】   If something _disturbs_ a situation or atmosphere, it spoils it or causes trouble. 使混乱   +
⇒  What could possibly disturb such tranquillity?  有什么能破坏这种宁静？   +

---


==== ▸ drift  [4238]   +
な/drɪft/   +

【V-I】   When something _drifts_ somewhere, it is carried there by the movement of wind or water. 漂流   +
⇒  We proceeded to drift on up the river.  我们继续在河上漂流着。   +

【V-I】   If someone or something _drifts into_ a situation, they get into that situation in a way that is not planned or controlled. 脱离正途; 偏离   +
⇒  We need to offer young people drifting into crime an alternative set of values.  我们需要给误入犯罪歧途的年轻人提供另一套价值观。   +

【V-I】   If you say that someone _drifts_ around, you mean that they travel from place to place without a plan or settled way of life. 漂泊; 流浪   +
⇒  You've been drifting from job to job without any real commitment.  你频频换工作，全无恒心。   +

【V-I】   To _drift_ somewhere means to move there slowly or gradually. 缓慢地移动   +
⇒  As rural factories lay off workers, people drift toward the cities.  随着乡镇企业裁员，人们陆续移向城市。   +

【V-I】   If sounds _drift_ somewhere, they can be heard but they are not very loud. (声音) 隐约传出   +
⇒  Cool summer dance sounds are drifting from the stereo indoors.  屋内立体声音响飘出美妙的夏季舞曲。   +

【V-I】   If snow _drifts_, it builds up into piles as a result of the movement of the wind. 吹积   +
⇒  The snow, except where it drifted, was only calf-deep.  除了被风吹积起来的地方外，积雪只深及小腿。   +

【N-COUNT】   A _drift_ is a movement away from somewhere or something, or a movement toward somewhere or something different. 移向; 移动   +
⇒  ...the drift toward the cities.  …向城市的流动。   +

【N-COUNT】   A _drift_ is a mass of snow that has built up into a pile as a result of the movement of wind. (吹积成的) 雪堆   +
⇒  A nine-year-old boy was trapped in a snow drift.  一个9岁的男孩陷在雪堆里了。   +

【N-SING】  _The__drift of_ an argument or speech is the general point that is being made in it. (辩论、演说等的) 主旨   +
⇒  Grace was beginning to get his drift.  格雷斯开始抓住他的主旨了。   +

---


==== ▸ facet  [4239]   +
な/ˈfæsɪt/   +

【N-COUNT】   A _facet of_ something is a single part or aspect of it. 方面   +
⇒  The caste system shapes nearly every facet of Indian life.  种姓制度几乎决定了印度生活的各个方面。   +

【N-COUNT】   The _facets_ of a diamond or other precious stone are the flat surfaces that have been cut on its outside. (钻石等的) 刻面   +

---


==== ▸ transplant  [4240]   +
な【N-VAR】   A _transplant_ is a medical operation in which a part of a person's body is replaced because it is diseased. (器官) 移植   +
⇒  He was recovering from a heart transplant operation.  他正从心脏移植手术中康复。   +

【V-T】   If doctors _transplant_ an organ such as a heart or a kidney, they use it to replace a patient's diseased organ. 移植   +
⇒  The operation to transplant a kidney is now fairly routine.  移植肾脏的手术如今相当常见。   +

【V-T】   To _transplant_ a plant, person, or thing means to move them to a different place. 移种; 转移   +
⇒  I have to transplant the begonias.  我得移种那些秋海棠。   +

---


==== ▸ wax  [4241]   +
な/wæks/   +

【N-MASS】  _Wax_ is a solid, slightly shiny substance made of fat or oil that is used to make candles and polish. It melts when it is heated. 蜡   +
⇒  There were coloured candles which had spread pools of wax on the furniture.  彩色蜡烛在家具上留下了一摊摊的蜡油。   +

【V-T】   If you _wax_ a surface, you put a thin layer of wax onto it, especially in order to polish it. 给…上蜡   +
⇒  We'd have long talks while she helped me wax the floor.  她帮我给地板上蜡时，我们闲聊了很长时间。   +

【N-UNCOUNT】  _Wax_ is the sticky yellow substance found in your ears. 耳垢   +
⇒  Use a cotton bud to remove the wax from your ears.  用棉花棒挖掉你耳朵里的耳垢。   +

【V-T】   If you have a part of your body _waxed_, for example your legs, you have the hair removed from the area by having wax put on it and then pulled off quickly. (用蜡) 去毛   +
⇒  She has just had her legs waxed at the local beauty parlour.  她刚在当地的美容院用蜡去了腿毛。   +

【V】   to become larger, more powerful, etc 变更大; 变更强大   +

【N】   a fit of rage or temper 发怒; 生气   +
⇒  He's in a wax today.     +

---


==== ▸ porous  [4242]   +
な/ˈpɔːrəs/   +

【ADJ】   Something that is _porous_ has many small holes in it that water and air can pass through. 多孔的   +
⇒  The local limestone is so porous that all the rainwater immediately sinks below ground.  当地的石灰岩如此多孔以致所有的雨水很快渗到地下。   +

---


==== ▸ audience  [4243]   +
な/ˈɔːdɪəns/   +

【N-COUNT-COLL】   The _audience_ at a play, concert, film, or public meeting is the group of people watching or listening to it. 观众   +
⇒  The entire audience broke into loud applause.  全场观众爆发出响亮的掌声。   +

【N-COUNT-COLL】   The _audience_ for a television or radio programme consists of all the people who watch or listen to it. 观众; 听众   +
⇒  The concert will be broadcast to a worldwide television audience estimated at one billion.  这场音乐会将向全世界大约十亿电视观众转播。   +

【N-COUNT-COLL】   The _audience_ of a writer or artist is the people who read their books or look at their work. 读者; 欣赏者   +
⇒  Say's writings reached a wide audience during his lifetime.  塞伊的作品在他有生之年就拥有了广泛读者。   +

---


==== ▸ diverge  [4244]   +
な/daɪˈvɜːdʒ/   +

【V-RECIP】   If one thing _diverges from_ another similar thing, the first thing becomes different from the second or develops differently from it. You can also say that two things _diverge_. 相异   +
⇒  His interests increasingly diverged from those of his colleagues.  他和同事们的兴趣越来越不同。   +

【V-RECIP】   If one opinion or idea _diverges from_ another, they contradict each other or are different. You can also say that two opinions or ideas _diverge_. 有分歧   +
⇒  The view of the Estonian government does not diverge that far from Lipmaa's thinking.  爱沙尼亚政府的观点和李普马的想法并无太大分歧。   +

---


==== ▸ incubate  [4245]   +
な/ˈɪnkjʊˌbeɪt, ˈɪŋ/   +

【V-T/V-I】   When birds _incubate_ their eggs, or when they _incubate_, they keep the eggs warm until the baby birds come out. 孵 (卵); 孵化   +
⇒  The birds returned to their nests and continued to incubate the eggs.  那些鸟儿返巢继续孵卵。   +
⇒  They lay eggs that incubate through the winter.  它们产下卵，要孵化整个冬天。   +

【N-UNCOUNT】   孵卵; 孵化   +
⇒  Male albatrosses share in the incubation of eggs.  雄性信天翁参与孵卵。   +

---


==== ▸ daisy  [4246]   +
な/ˈdeɪzɪ/   +

【N-COUNT】   A _daisy_ is a small wildflower with a yellow centre and white petals. 雏菊   +

---


==== ▸ transport  [4247]   +
な【V-T】   To _transport_ people or goods somewhere is to take them from one place to another in a vehicle. 运送   +
⇒  They are banned from launching any flights except to transport people.  他们被禁止飞行任何航班，运送人除外。   +

【N-UNCOUNT】  _Transport_ refers to any vehicle that you can travel in or carry goods in. 交通工具   +

【N-UNCOUNT】  _Transport_ is a system for taking people or goods from one place to another, for example, using buses or trains. 交通运输系统   +

【N-UNCOUNT】  _Transport_ is the activity of taking goods or people from one place to another in a vehicle. 运输   +

---


==== ▸ indigenous  [4248]   +
な/ɪnˈdɪdʒɪnəs/   +

【ADJ】  _Indigenous_ people or things belong to the country in which they are found, rather than coming there or being brought there from another country. 本土的; 当地的   +
⇒  ...the country's indigenous population.  …该国的本土人口。   +

---


==== ▸ melt  [4249]   +
な/mɛlt/   +

【V-T/V-I】   When a solid substance _melts_ or when you _melt_ it, it changes to a liquid, usually because it has been heated. 使融化; 融化   +
⇒  The snow had melted, but the lake was still frozen solid.  雪已经融化了，但湖面仍然冻得结结实实。   +
⇒  Meanwhile, melt the white chocolate in a bowl suspended over simmering water.  同时，把碗架在快烧开的水上，融化碗里的白巧克力。   +

【V-I】   If something such as your feelings _melt_, they suddenly disappear and you no longer feel them. 消散   +
⇒  His anxiety about the outcome melted, only to return later.  他对结果的焦虑消失了，但过后又来了。   +

【PHRASAL VERB】  _Melt away_ means the same as . 同(melt)   +
⇒  When he heard these words, Scot felt his inner doubts melt away.  听到这些话，斯科特觉得内心的疑虑消失了。   +

【V-I】   If a person or thing _melts into_ something such as darkness or a crowd of people, they become difficult to see, for example because they are moving away from you or are the same colour as the background. 消失 (在黑暗、人群等中)   +
⇒  The youths dispersed and melted into the darkness.  年轻人们散开了，消失在夜色中。   +

---


==== ▸ bark  [4250]   +
な/bɑːk/   +

【V-I】   When a dog _barks_, it makes a short, loud noise, once or several times. (狗) 吠   +
⇒  Don't let the dogs bark.  别让狗叫。   +

【N-COUNT】  _Bark_ is also a noun. 吠声   +
⇒  The Doberman let out a string of roaring barks.  那条杜宾犬发出一连串的吼叫声。   +

【V-I】   If you _bark at_ someone, you shout at them aggressively in a loud, rough voice. 咆哮   +
⇒  I didn't mean to bark at you.  我不是有意吼你。   +

【N-UNCOUNT】  _Bark_ is the tough material that covers the outside of a tree. 树皮   +

【V】   to scrape or rub off skin, as in an injury 擦伤; 刮伤   +

---


==== ▸ bouquet  [4251]   +
な/bəʊˈkeɪ, buː-/   +

【N-COUNT】   A _bouquet_ is a bunch of flowers which is attractively arranged. 花束   +
⇒  The woman carried a bouquet of dried violets.  那个女子拿着一束干紫罗兰花。   +

【N-VAR】   The _bouquet_ of something, especially wine, is the pleasant smell that it has. 芳香   +
⇒  ...a Sicilian wine with a light red colour and a bouquet of cloves.  …一杯浅红色并带着丁香芬芳的西西里酒。   +

---


==== ▸ apply  [4252]   +
な/əˈplaɪ/   +

【V-T/V-I】   If you _apply for_ something such as a job or membership of an organization, you write a letter or fill out a form in order to ask formally for it. 申请   +
⇒  I am continuing to apply for jobs.  我在继续申请工作。   +
⇒  They may apply to join the organization.  他们可能申请加入该组织。   +

【V-T】   If you _apply yourself to_ something or _apply_ your mind _to_ something, you concentrate hard on doing it or on thinking about it. 将…投入   +
⇒  Scymanski has applied himself to this task with considerable energy.  赛曼斯基已经花了相当多的精力致力于这项任务。   +

【V-I】   If something such as a rule or a remark _applies to_ a person or in a situation, it is relevant to the person or the situation. (对…) 适用   +
⇒  The convention does not apply to us.  该协定对我们不适用。   +
⇒  The rule applies where a person owns stock in a corporation.  该规定对于在公司里拥有股份的人适用。   +

【V-T】   If you _apply_ something such as a rule, system, or skill, you use it in a situation or activity. 运用   +
⇒  The government appears to be applying the same principle.  政府似乎在运用同样的原则。   +

【V-T】   A name that _is applied to_ someone or something is used to refer to them. (在…上) 使用   +
⇒  ...a biological term that cannot be applied to a whole culture.  …一个不能用于整个培养物的生物学术语。   +

【V-T】   If you _apply_ something _to_ a surface, you put it on or rub it into the surface. 施用   +
⇒  The right thing would be to apply direct pressure to the wound.  正确的做法会是在伤口上施加直接压力。   +

---


==== ▸ wanna  [4253]   +
な/ˈwɒnə/   +
⇒  I wanna be married to you. Do you wanna be married to me?  我想和你结婚。你想和我结婚吗？   +

---


==== ▸ babble  [4254]   +
な/ˈbæbəl/   +

【V-I】   If someone _babbles_, they talk in a confused or excited way. 含糊不清地说; 兴奋地说   +
⇒  Momma babbled on and on about how he was ruining me.  妈妈喋喋不休地数说他在如何毁我。   +
⇒  They all babbled simultaneously.  他们全都异口同声地唧唧喳喳起来。   +

【N-SING】   You can refer to people's voices as a _babble of_ sound when they are excited and confused, preventing you from understanding what they are saying. 嘈杂的说话声   +
⇒  Kemp knocked loudly so as to be heard above the high babble of voices.  肯普大声地敲门，以压过唧唧喳喳的高声喧哗而让人听见。   +

---


==== ▸ rob  [4255]   +
な/rɒb/   +

【V-T】   If someone _is robbed_, they have money or property stolen from them. 盗窃; 抢劫   +
⇒  Mrs. Yacoub was robbed of her designer watch at her Westchester home.  雅各布夫人的名牌手表在她威斯特切斯特的家中被人盗走了。   +

【V-T】   If someone _is robbed of_ something that they deserve, have, or need, it is taken away from them. 抢走   +
⇒  When Miles Davis died jazz was robbed of its most distinctive voice.  当迈尔斯•戴维斯去世时，爵士乐里最具特色的声音也被夺走了。   +

---


==== ▸ glue  [4256]   +
な/ɡluː/   +

【N-MASS】  _Glue_ is a sticky substance used for joining things together, often for repairing broken things. 胶; 胶水   +
⇒  ...a tube of glue.  …一管胶水。   +

【V-T】   If you _glue_ one object to another, you stick them together using glue. 用胶粘   +
⇒  Glue the fabric around the window.  用胶把这布粘在窗户四周。   +
⇒  The material is cut and glued in place.  材料被剪开并粘到合适的位置。   +

【V-T PASSIVE】   If you say that someone _is glued to_ something, you mean that they are giving it all their attention. 使全神贯注   +
⇒  They are all glued to the Olympic Games.  他们都全神贯注于奥运会。   +

---


==== ▸ initiate  [4257]   +
な/ɪˈnɪʃɪˌeɪt/   +

【V-T】   If you _initiate_ something, you start it or cause it to happen. 使开始; 发起   +
⇒  They wanted to initiate a discussion on economics.  他们想发起一次关于经济学的讨论。   +

【V-T】   If you _initiate_ someone _into_ something, you introduce them to a particular skill or type of knowledge and teach them about it. 使初步了解; 传授   +
⇒  He initiated her into the study of other cultures.  他引导她进入对于其他文化的研究。   +

【V-T】   If someone _is initiated into_ something such as a religion, secret society, or social group, they become a member of it by taking part in special ceremonies. (常通过特殊仪式) 使加入   +
⇒  In many societies, young people are formally initiated into their adult roles.  在很多社会，年轻人要通过正式的仪式进入成年。   +

---


==== ▸ assassinate  [4258]   +
な/əˈsæsɪˌneɪt/   +

【V-T】   When someone important _is assassinated_, they are murdered as a political act. (因政治原因而) 刺杀   +
⇒  Would the U.S. be radically different today if Kennedy had not been assassinated?  如果肯尼迪没有被刺杀，今天的美国会大不相同吗？   +

【N-VAR】   刺杀   +
⇒  She would like an investigation into the assassination of her husband.  她想要对其丈夫的遇刺进行调查。   +
⇒  He lives in constant fear of assassination.  他一直生活在对刺杀的恐惧之中。   +

---


==== ▸ trace  [4259]   +
な/treɪs/   +

【V-T】   If you _trace_ the origin or development of something, you find out or describe how it started or developed. 追溯   +
⇒  The exhibition traces the history of graphic design in America from the 19th century to the present.  这个展览会追溯了从19世纪到现在美国平面设计的历史。   +

【PHRASAL VERB】  _Trace back_ means the same as . 追溯   +
⇒  ...Bronx residents who trace their families back to Dutch settlers.  …将自己的家族追溯到荷兰移民者们的布朗克斯居民。   +

【V-T】   If you _trace_ someone or something, you find them after looking for them. 找到   +
⇒  Police are anxious to trace two men seen leaving the house just before 8am.  警察急切想找到在接近早晨8点前被人看到离开那幢房子的两名男子。   +

【V-T】   If you _trace_ something such as a pattern or a shape, for example, with your finger or toe, you mark its outline on a surface. 勾画出 (轮廓)   +
⇒  I traced the course of the river on the map spread out on my briefcase.  我在自己公文包上铺展开的地图中勾画出了这条河的流向。   +

【V-T】   If you _trace_ a picture, you copy it by covering it with a piece of transparent paper and drawing over the lines underneath. (用透明纸盖在底样上) 描摹   +
⇒  She learned to draw by tracing pictures out of old storybooks.  她通过描摹旧故事书上的图画来学绘画。   +

【N-COUNT】   A _trace of_ something is a very small amount of it. 少许   +
⇒  Wash them in cold water to remove all traces of sand.  用冷水清洗它们以清除所有的沙子。   +

【PHRASE】   If you say that someone or something _disappears without a trace_, you mean that they stop existing or stop being successful very suddenly and completely. 消失得无影无踪   +
⇒  One day he left, disappeared without a trace.  有一天他离开了，消失得无影无踪。   +

---


==== ▸ predispose  [4260]   +
な/ˌpriːdɪˈspəʊz/   +

【V-T】   If something _predisposes_ you _to_ think or behave in a particular way, it makes it likely that you will think or behave in that way. 使…很可能 (以某方式思考或行事)   +
⇒  They take pains to hire people whose personalities predispose them to serve customers well.  他们煞费苦心雇用那些具备把顾客服务好的个性的人。   +

【ADJ】   有…倾向的   +
⇒  ...people who are predisposed to violent crime.  …有暴力犯罪倾向的人们。   +

【V-T】   If something _predisposes_ you _to_ a disease or illness, it makes it likely that you will suffer from that disease or illness. 使…很可能患 (某疾病)   +
⇒  ...a gene that predisposes people to alcoholism.  …使易于嗜酒的基因。   +

【ADJ】   易患…的   +
⇒  Some people are genetically predisposed to diabetes.  有些人先天性易患糖尿病。   +

---


==== ▸ planet  [4261]   +
な/ˈplænɪt/   +

【N-COUNT】   A _planet_ is a large, round object in space that moves around a star. The Earth is a planet. 行星   +
⇒  The picture shows six of the nine planets in the solar system.  这张图片展示太阳系9个行星中的6个行星。   +

---


==== ▸ cubism  [4262]   +
 辞典中没找到  +
==== ▸ execute  [4263]   +
な/ˈɛksɪˌkjuːt/   +

【V-T】   To _execute_ someone means to kill them as a punishment for a serious crime. 处死   +
⇒  He said nobody had been executed as a direct result of the events.  他说没有人作为这几起事件的直接后果被处死。   +
⇒  One group claimed to have executed the hostage.  一个组织声称他们已处死了那名人质。   +

【N-VAR】   处死   +
⇒  Execution by lethal injection is scheduled for July 30th.  注射死刑定于7月30日执行。   +

【V-T】   If you _execute_ a plan, you carry it out. 执行 (计划等)   +
⇒  We are going to execute our campaign plan to the letter.  我们将严格执行我们的竞选方案。   +

【N-UNCOUNT】   执行   +
⇒  U.S. forces are fully prepared for the execution of any action once the order is given by the president.  美国军队做好了充分准备，一旦总统下令就采取行动。   +

【V-T】   If you _execute_ a difficult action or movement, you successfully perform it. 完成 (高难动作)   +
⇒  The landing was skilfully executed.  着陆熟练地完成了。   +

---


==== ▸ calamitous  [4264]   +
な/kəˈlæmɪtəs/   +

【ADJ】   If you describe an event or situation as _calamitous_, you mean it is very unfortunate or serious. 灾难的   +
⇒  ...the calamitous state of the country.  ...该国家的悲惨境况。   +

---


