= 0804
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 804: Dealing with Time Changes in Scheduling.
This is English as a Second Language Podcast episode 804. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode. You can also take a look at some of our premium courses, our special courses in business and daily English on our website.
This episode is all about scheduling and changing times. Let’s get started.
[start of dialogue]
Danny: Don’t bother looking for next year’s meeting calendar. I’m still working on it.
Tessa: What’s taking so long?
Danny: This is my first time scheduling all of the major meetings for this company and I’m getting thrown off by all of the things I have to keep in mind. For instance, our bylaws say that we have to have a management meeting every 60 days. This is a leap year, so do I have to take that into account?
Tessa: That’s a tough one. I’m not sure.
Danny: And what about daylight saving time? I have to remember when clocks will be set ahead and back.
Tessa: That’s easy. My high school teacher taught us to remember it with a simple phrase: “fall back and spring ahead.”
Danny: Okay, but that doesn’t help me with dates. Apparently, daylight saving time changes on different dates in different countries. And I have to factor in time zones to set the time for each meeting, with meeting times that work for each international office that will be participating.
Tessa: You’re right, it’s a tall order, but you do know that someone has done this before? You don’t have to reinvent the wheel.
Danny: Yeah, Carl set the meeting calendar last year, but he left the company last month.
Tessa: Can’t you just take last year’s meeting calendar and fudge it?
Danny: Why do you think Carl is no longer with the company?
Tessa: Ah.
[end of dialogue]
Our dialogue begins Danny saying to Tessa, “Don’t bother looking for next year’s meeting calendar.” “Don’t bother” is a phrase we use to tell someone not to do something because it isn’t possible or they won’t be successful. “Don’t bother” means don’t look for next year’s meeting calendar. “Calendar” is, you probably know, a record of days and weeks and years that you use to perhaps schedule your life around, to plan, to know what date and day it is. Danny says he’s still working on next year’s meeting calendar, which we guess is a calendar telling you which days and times they will have meetings at their company.
Tessa says, “What’s taking so long?” Why is it taking you so long, you idiot? No! She didn’t say “you idiot,” she could have but she didn’t. So the idiot Danny says, “This is my first time scheduling all of the major meetings for this company and I’m getting thrown off by all of the things I have to keep in mind.” Danny says this is the first time he has scheduled – he has decided what days and times – all of the major or important meetings for the company. “And,” he says, “I’m getting thrown off by all of the things I have to keep in mind.” “To be thrown off” means to be confused, to be misled, when someone makes it or something makes it difficult or impossible for you to understand something. It can also be used sometimes when some unexpected or sudden change interrupts your plans so you can no longer do what you were going to do: “The thunderstorm (the rainstorm) canceled our flight (our airplane flight). It threw off our plans.” It made them impossible to complete; it changed them unexpectedly.
In the dialogue, Danny is thrown off; he’s not able to do what he thought he was able to do because all of the things he has to keep in mind – he has to remember. “To keep in mind” (mind) means to remember. Danny says, “For instance (for example), our bylaws say that we have to have a management meeting every 60 days.” Your “bylaws” (bylaws) are your official rules created by your organization. The bylaws are usually rules that the company uses to help it operate more smoothly, to make sure everything is done correctly. Well, these bylaws say they have to have a management meeting – a meeting of the managers – every 60 days. Danny says, “This is a leap year, so do I have to take that into account?” A “leap (leap) year” is a year, you probably know, that has 366 days; it happens once every four years when we have a February 29th, not just 28 days in February. Well, poor Danny is not sure what to do during a leap year. He says, “do I have to take that into account?” “To take (something) into account” means to include it or consider it in your decision or your opinion. You have to take into account that Danny is an idiot, and that helps you understand the dialogue a little better; you have to consider that in your opinion. Danny is wondering whether you have to take into account the fact that this year is a leap year.
Tessa says, “That’s a tough one.” Now, Tessa, it’s not a tough one, it’s obvious. February 29th is a day, you just count that into the 60 days. It’s not that difficult people! Huh! I’m sorry, I – I’m not in a very good mood today. I don’t know why, probably didn’t have enough coffee this morning. Did I tell you I’m drinking coffee now? Yeah, yeah. No, um – well I still drink, uh, tea, but, uh, I’ve started drinking coffee again. But when I don’t have my coffee then, you know, I’m not in a very good mood.
Anyway, back to our dialogue: Tessa says – wrongly – that this is a tough one, this is a difficult decision. She says she’s not sure. Danny says, “And what about daylight saving time?” “Daylight saving time” is a system used in many countries where you move your clock ahead one hour and then back one hour twice a year in order to give people, in part, more hours of light in the evening time. We talked about daylight saving time back on English Café number 78, many, many years ago. Danny says, “I have to remember when clocks will be set ahead and back.” “To set ahead” means to turn the clock forward one hour, so instead of being 10:00 now it’s 11:00. “To set the clock back” would mean to go from 11:00 to 10:00. It’s really not that complicated Danny! I should mention that the expression “to set back” has other meanings in English; take a look at our Learning Guide for some of those.
Tessa says, “That’s easy. My high school teacher taught us to remember it with a simple phrase: ‘fall back and spring ahead.’” This expression “fall back and spring ahead” is used in English to remind people when they are supposed to put their – or set their clocks ahead and when they’re supposed to set them back. In the fall – in the autumn, they put the clocks back; they fall back. “To fall back” means to go backwards, and so we use the two meanings of the word “fall.” “Fall” means the season of autumn: in North America roughly October, November, December. And it also means, when you say “fall back,” you mean to go back, to move backwards. So, “fall back” reminds you that in the fall you set your clock back an hour, and in the spring you spring ahead. “To spring ahead” means to jump forward. “Spring” also refers to the season of the year that comes between winter and summer. So “spring ahead” means to move your clock forward one hour during the springtime.
Danny says, “Okay, but that doesn’t help me with dates. Apparently, daylight saving time changes on different dates in different countries.” This is true; it’s different in the United States than it is in Europe. He says, “And I have to factor in time zones to set the time for each meeting.” “To factor in” means to include or to consider; it means the same as “to take (something) into account.” Danny has to factor in time zones. A “time zone” is a geographic area where people use the same time. Here in California, we’re in the Pacific time zone. So, it’s the same time in Los Angeles as it is in Oregon or in Washington or in British Columbia, Canada, or in Baja, California. New York City is in the Eastern time zone, where there is a three hour difference between the Pacific and the Eastern time zones. Well, Danny has to factor in time zones to set or to establish the time for each meeting because there are people in different parts of the world who participate.
Tessa says, “You’re right (you’re correct), it’s a tall order.” A “tall order” is something that’s very difficult or challenging that you have been asked to do. Tessa says, “but you do know that someone has done this before? You don’t have to reinvent the wheel.” This is an old expression: “to reinvent (reinvent) the wheel” means you don’t have to waste time doing something that someone has already done. “To invent” means to create, to come up with a new idea. Well the wheel was invented many, many years ago; you don’t have to come up with the idea of a wheel again. It means, again, you don’t need to waste your time; you can find out what someone else did before and do what they did.
Danny says, “Yeah, Carl set the meeting calendar last year, but he left the company last month.” Tessa says, “Can’t you just take last year’s meeting schedule and fudge it?” “To fudge (fudge) (something)” means to change something in a small way, presenting it as the real answer even though you’re really just guessing; you’re not really sure. You’re trying to fool someone into thinking that you know what the answer is, so you kind of take a guess but you know it’s not the exact answer, or you don’t think it’s the exact answer. Danny says, “Why do you think Carl is no longer with the company?” Tessa says, “Ah.” In other words, the joke here is that Carl, the person who used to do the calendar, didn’t do a very good job. He – he wasn’t accurate; he fudged his calendar dates. He didn’t calculate them very carefully, and that’s why he was fired. So, it would be a bad idea for Danny to do the same thing.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Danny: Don’t bother looking for next year’s meeting calendar. I’m still working on it.
Tessa: What’s taking so long?
Danny: This is my first time scheduling all of the major meetings for this company and I’m getting thrown off by all of the things I have to keep in mind. For instance, our bylaws say that we have to have a management meeting every 60 days. This is a leap year, so do I have to take that into account?
Tessa: That’s a tough one. I’m not sure.
Danny: And what about daylight saving time? I have to remember when clocks will be set ahead and back.
Tessa: That’s easy. My high school teacher taught us to remember it with a simple phrase: “fall back and spring ahead.”
Danny: Okay, but that doesn’t help me with dates. Apparently, daylight saving time changes on different dates in different countries. And I have to factor in time zones to set the time for each meeting, with meeting times that work for each international office that will be participating.
Tessa: You’re right, it’s a tall order, but you do know that someone has done this before? You don’t have to reinvent the wheel.
Danny: Yeah, Carl set the meeting calendar last year, but he left the company last month.
Tessa: Can’t you just take last year’s meeting calendar and fudge it?
Danny: Why do you think Carl is no longer with the company?
Tessa: Ah.
[end of dialogue]
Don’t bother looking for any other ESL podcast to listen to. You have the best with the scripts written by the best scriptwriter, Dr. Lucy Tse, right here at ESL Podcast.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
don’t bother – a phrase used to tell someone not to do something, because it will not be successful, it is not possible, or it will not be helpful
* Don’t bother asking Jenna for help with the calculations. She doesn’t know how to do them either.
calendar – a record of times, days, weeks, and years, used for showing what will happen and what one must do at certain times in the future
* I think I’m free for a meeting next Tuesday, but let me check my calendar.
to throw off – to confuse or mislead someone, making it difficult or impossible for him or her to do or understand something
* The flight cancellation threw off their vacation plans.
to keep in mind – to remember; to be aware of something, often while doing something else
* Keep in mind that most new restaurants fail within the first few years.
bylaws – official rules created by an organization that describes how it will function and be governed
* According to the bylaws, we should have at least eight people on the board of directors.
leap year – a year that has 366 days and comes once every four years; a year that includes February 29th
* Keith was born on February 29th, so he celebrates his birthday only during leap years and he likes to joke that he’s only seven years old, even though he’s really 28.
to take (something) into account – to include or consider something in one’s decision or opinion
* New cell phones seem really cheap, but once you take into account the monthly service fees, they can be quite expensive.
daylight saving time – a system of time that moves clocks ahead or back one hour twice a year to give people more hours of light in the evening
* Some people say that daylight saving time improves health, because it encourages people to spend more time outdoors after work.
to set ahead – to move one’s clock forward a certain amount of time, so that the time displayed on the clock becomes later
* I hate setting clocks ahead at night, because it means waking up an hour earlier the next morning.
to set back – to move one’s clock backward a certain amount of time, so that the time displayed on the clock becomes earlier
* Larion forgot to set back his watch, so he ended up arriving at the 3:00 meeting an hour early, when it was actually 2:00.
fall back and spring ahead – a phrase used to help people remember to set their clocks back one hour in the fall (autumn) and to set their clocks forward one hour in the spring, which is easier to remember because “to fall back” means to begin to walk more slowly behind a group of people, and “to spring ahead” means to jump or hurry and be in front of a group of people
* I know the phrase is “fall back and spring ahead,” but that doesn’t help me remember on which day I’m supposed to change the clocks.
to factor in – to include or consider something in one’s decision or opinion
* Oops, I forgot to factor in sales tax, so I don’t have enough cash to pay for this purchase.
time zone – a geographic area where people use the same time, or where all the clocks show the same time
* The continental United States covers four time zones, from Pacific Time in Washington to Eastern Time in Maine.
tall order – something difficult and challenging that one is expected to do or has been asked to do
* Heading up the effort to open a new office on the other side of the country is a tall order, but I’m sure you can do it.
to reinvent the wheel – to waste time doing something that another person has already done
* Why are you reinventing the wheel by typing up the U.S. Constitution? I’m sure you can find typed copies online.
to fudge – to fake one’s answer or result, altering an amount in some way, presenting one’s guess as a real answer, or telling a small lie
* What will you do if the auditors find out you’ve fudged your numbers?
Comprehension Questions
1. Why is Danny worried about the meeting calendar?
a) Because nobody wants to attend the meetings.
b) Because he’s struggling to find a time when everyone can attend.
c) Because the formatting is very confusing.
2. Why does Tessa tell Danny to not to reinvent the wheel?
a) Because she needs him to calm down and stop worrying.
b) Because she thinks he should tell his supervisor about the problems.
c) Because she doesn’t want him to spend time doing what someone else has already done.
Answers at bottom.
What Else Does It Mean?
to throw off
The phrase “to throw off,” in this podcast, means to confuse or mislead someone, making it difficult or impossible for him or her to do or understand something: “Drinking alcohol really throws off Clarke’s sense of direction.” The phrase “to throw (something) on” means to put clothing on carelessly, without worrying about one’s appearance: “This morning I threw on a pair of sweatpants and a t-shirt and went to the gym.” The phrase “to throw (something) out” means to put something in the garbage and get rid of it because it is no longer needed: “Why did you throw out my old comic book collection years ago? It could be worth a lot of money today.” Finally, the phrase “to throw (something) together” means to cook very quickly using whatever is available in the kitchen: “Hong threw together a pretty good dinner, just using leftovers.”
to set back
In this podcast, the phrase “to set back” means to move one’s clock backward a certain amount of time, so that the time displayed on the clock becomes earlier: “Did you remember to set back the clock on the microwave?” The phrase “to set (someone) back” means to cost someone a certain amount of money, usually a lot of money: “How much did that engagement ring set you back?” The phrase “to set aside” means to save something for a particular purpose, or to save it for later use: “Each month, they set aside $300 for their daughter’s college education.” Finally, the phrase “to set off” means to start a journey or begin a trip: “We’re setting off for the Grand Canyon after work on Friday.”
Culture Note
Standard Time and the Railroads
Through the mid-1800s, cities and towns in the United States used “local mean time,” which established a “uniform” (not changing; the same in all places) time for a specific “longitude” (one of the imaginary curved lines on the globe connecting the north and south poles). However, as “railroad” (train) travel became more popular, the “variations” (inconsistencies; changes) in local times led to confusion, missed trains, and “on occasion” (sometimes), accidents.
In October 1883, the leaders of the major railroad companies met and agreed to “adopt” (begin using) a system with five time zones across the continent. The states soon “followed suit” (did the same thing). At first, standardized time was “controversial” (difficult to reach agreement). Many cities and towns refused to adopt railway time, often having two clocks “on display” (seen by the public) in train stations: one with the local time and one with the railway time.
The “eventual” (happening at last or after a long wait) adoption of railway time made train travel easier and more “predictable” (able to know what will happen). The Travelers Official Railway Guide of the United States, Mexico and Canada published “extensive” (comprehensive; very long and detailed) list of railway schedules and “connections” (places where travelers can switch from one railroad train to another). The “timetables” (schedules of arrival and departure times) were useful only because the railroads had agreed to use standard time.
In 1918, the United States “enacted” (made into law) the “Standard Time Act,” also known as the “Calder Act.” This law officially adopted standard time in the United States.
Comprehension Answers
1 - b
2 - c