= 0832
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 832: Creating an Online Store
This is English as a Second Language Podcast number 832. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Our website is ESLPod.com. Go there to become a member, and get a Learning Guide for this episode.
This episode is a dialog about creating or opening a new store online, on the I Internet. Let’s get started!
[start of dialogue]
Kay: I’d say we’re well on our way to establishing our new online store.
Greg: I can’t wait for this to get off the ground. Orders will pour in and we’ll make money hand over fist.
Kay: Let’s not get ahead of ourselves. Let’s see where we are in our preparations.
Greg: All right. We’ve created a marketing plan that includes several ways to drive traffic to our website.
Kay: That’s great. We’ve also installed a shopping cart and a secure way to process orders.
Greg: We can use that system to track orders, right?
Kay: That’s right. All customer information will be captured and we’ll have a database of information we can mine later.
Greg: That’s great. We already have a place to house the inventory and a way to track it.
Kay: Right you are. Now all we need is one last thing.
Greg: We need to find a product to sell.
Kay: Yeah. Any ideas?
Greg: No, none. You?
Kay: Nope. But as soon as we do, we’ll be the next big thing in ecommerce.
Greg: Definitely!
[end of dialogue]
Kate starts by saying, “I’d say” – “I would say,” meaning here, “I think” – “we’re well on our way to establishing our new online store.” “We’re well on our way” means we are well on our way and that means that we are making good progress toward something. We’re getting closer to our goal, to finishing – in this case, this new project of establishing or starting an online store, a website basically on the Internet where you sell things. Greg says, “I can’t wait for this to get off the ground.” When someone says, “I can’t wait for something” they mean they’re very excited about it. Greg can’t wait for this online store to “get off the ground” (ground). “To get something off the ground” means to begin something – usually a project – to start something for the first time. Greg says, “orders” – people buying things – “orders will pour in and we’ll make money hand over fist.” The expression “to pour (pour) in” means to receive a lot of something, especially money, but it could be letters or emails. We could say, “The money is pouring in from our new product” – our new thing that we are selling on the Internet. Greg thinks money will pour in and that they will “make money hand over fist” (fist). The expression “to make money hand over fist” means to make a lot of money, to get very rich by doing something. Someone’s making money hand over fist.
Kay says, “Let’s not get ahead of ourselves.” The expression “to get ahead of yourself,” or “to get ahead of ourselves,” means to get so excited about something that we begin to think about all the wonderful things that will happen in the future and not focus on preparing for what’s happening right now. “To get ahead of yourself” would mean to start making plans, for example, about how you’re going to spend your money that you are going to get from your new online website – online store, rather – before you’ve actually started the business. That’s getting ahead of yourself. Or you see a beautiful woman and you start thinking about how you’re going to marry her and have children and you don’t even have her telephone number yet. Kay says, “Let’s not get ahead of ourselves. Let’s see where we are in our preparations.” “Let’s see where we are,” meaning let’s look at where we are currently – what we are doing now – for our preparations.
Greg says, “All right. We’ve created a marketing plan that includes several ways to drive traffic to our website.” A “marketing plan” is a plan about how you’re going to go out and find customers and get them to buy your product. “Driving traffic” means encouraging people to visit your website or to go to your store. On the Internet, it means to get people – we call them “visitors” – to come to your website and look at it and hopefully buy something from it. Kay says, “That’s great. We’ve also installed a shopping cart and a secure way to process orders.” “To install (install)” means to connect or to put something in somewhere. It could be something physical like, for example, I need a new water heater in my house so I ask a plumber – a person who deals with things like water heaters – to come in and install it in my house, to connect it, to put it in. We also use this verb in talking about computer programs, computer software, which are installed on a computer or on a computer that is running a website.
In this case, the software that is installed was a “shopping cart.” On a website, a “shopping cart” is a piece of software that allows you to look at things that are being sold and to buy them. It’s sort of a part of the website that you actually use to buy something. If you go to a real physical store like a grocery store, where you buy food, you also have a shopping cart. It’s that thing that you push around that you put the food into so you don’t have to carry it in your hands. On a website, however, a shopping cart is the part of the website used to buy things.
Kay says they have “installed a shopping cart and a secure way to process orders.” “Secure” (secure) means safe. And on the Internet, it means a place where your information, your name, your credit card, your address, will be safe – it won’t get stolen, someone won’t come and take it and use it somewhere else. Kay says they have a secure way “to process orders.” “To process (process) orders” means that you receive orders that people give you, that is, things that they want to buy – that’s what an order is. You say, “I want to buy this.” “To process” them means to take care of them, to figure out who’s going to get what and so forth. In an online store, sometimes you are buying things that the company will send you in the mail. Sometimes, you’re simply buying things that you download onto your computer.
Greg says, “We can use that system to track orders, right?” “To track (track) orders” means to make sure you know what’s going on with the order at all times – whether it was paid for, whether it was shipped – that is, whether it was sent to the person who bought. In some cases, whether the person received it – all of that would be part of “tracking an order.” “Processing the order” means getting it ready to send; “tracking the order” means knowing what part of the process you are in.
Kay says, “That’s right. All customer information will be captured and we’ll have a database of information we can mine later.” “To capture” (capture) here means to record, to save that information from the customer. “Capture” has a number of different meanings in English. Take a look at our Learning Guide for some of those. Kay says they also have a “database” (database). A “database” is a computer program that saves and organizes information for you. “To mine” (mine) here – when we’re talking about websites and databases – means to analyze a large amount of information, a large amount of data to find interesting patterns. So, you might want to know whether people from this country are buying more on a weekend than people from that country. You can look at your database – your set of information – and “mine” it. You could go in and try to find information by using other computer software.
Greg says, “That’s great. We already have a place to house the inventory and a way to track it.” “To house (house) something” means to store it, to keep it until you are ready to use it. So, if you’re selling books on your website, you would need a place to house the physical books. You need a place to keep them. The “inventory” (inventory) refers to all of the things that you are selling – usually physical things. So, your inventory would be all of the books that you have that you are selling on your website or all of the computers you have that you are selling on your website.
Kay says, “Right you are,” meaning that’s correct. “Now all we need is one last thing” – one final thing. Greg says, “We need to find a product to sell.” Of course, normally when you have a store you know what you’re going to sell but Greg and Kay have built a website but they don’t have anything to sell yet. Kay says, “Yeah, any ideas?” Greg says, “No, none. You?” meaning “Do you?” Kay says, “Nope” – an informal way of saying no. “But as soon as we do, we’ll be the next big thing in ecommerce.” “The next big thing” is the most recent thing to become popular that everyone is talking about. So, a few years ago it was Facebook and then it was Twitter and then it was – I don’t know, Pinterest. Whatever the next most popular thing is that’s “the next big thing.” “Ecommerce” (ecommerce) refers to selling things on the Internet – Internet selling and buying.
Now let’s listen to the dialog this time at a normal speed.
[start of dialogue]
Kay: I’d say we’re well on our way to establishing our new online store.
Greg: I can’t wait for this to get off the ground. Orders will pour in and we’ll make money hand over fist.
Kay: Let’s not get ahead of ourselves. Let’s see where we are in our preparations.
Greg: All right. We’ve created a marketing plan that includes several ways to drive traffic to our website.
Kay: That’s great. We’ve also installed a shopping cart and a secure way to process orders.
Greg: We can use that system to track orders, right?
Kay: That’s right. All customer information will be captured and we’ll have a database of information we can mine later.
Greg: That’s great. We already have a place to house the inventory and a way to track it.
Kay: Right you are. Now all we need is one last thing.
Greg: We need to find a product to sell.
Kay: Yeah. Any ideas?
Greg: No, none. You?
Kay: Nope. But as soon as we do, we’ll be the next big thing in ecommerce.
Greg: Definitely!
[end of dialogue]
If you’ve listened to several of our episodes, you are well on your way to improving your English, thanks to the wonderful scripts written by Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan, thank you for listening. Come back and listen to us again here on ESL Podcast.
ESL Podcast is produced by the Center for Educational Development in Los Angeles, California. This podcast is copyright 2005.
Glossary
well on (one’s) way – making good progress toward something
* Igor is getting really good grades and is well on his way to becoming the top student.
online store – a website where people can buy products
* Do you prefer to buy books from online stores, or physical bookstores?
to get off the ground – to launch; to begin something; for something to start for the first time
* We hope to get this project off the ground by the end of the summer.
to pour in – to receive a lot of something, especially money
* The director was very pleased when the critics’ praise started pouring in.
to make money hand over fist – to make a lot of money; for something to be very profitable
* If only we had invested in technology companies 20 years ago, we’d be making money hand over fist!
to get ahead of (oneself) – to get too excited about something so that one begins thinking about what will happen in the future before one has finished all the preparations
* Wendy got ahead of herself, buying paint and curtains before she had even bought the house.
marketing plan – a plan for how one will find buyers and interest them in buying one’s products and services
* Our marketing plan calls for a mix of newspaper ads, email campaigns, and radio announcements.
to drive traffic – to encourage and direct many people to go to a particular website or store
* Many companies are using social media sites to drive traffic to their online stores.
to install – to connect and configure a piece of hardware or software so that it works with one’s computer system
* How long did it take you to install the new scanner?
shopping cart – the part of a website where individuals can see a list of the products they have decided to buy and then “check out” (pay for the products)
* Once you have everything in your shopping cart, click “Check Out” and then enter your credit card information.
secure – safe; without risk of one’s personal or financial information being stolen
* Li keeps his online accounts secure by using a different password for each one.
to process orders – to receive, fulfill, and ship products that have been ordered and paid for by people
* It usually takes us just 2-3 days to process orders after we receive the payment.
to track orders – to observe and monitor the status of orders, including when orders were placed, when they were paid for, and when products were sent and received
* This computer program makes it easy to track orders. Just click here to see the most recent status.
to capture – to observe and record; to save data
* This website captures each visitor’s email address and country or origin.
database – a computer program that saves and organizes a large amount of information
* The university has a database that records personal and academic information for each student.
to mine – to analyze a large amount of data to find interesting or useful patterns or rules
* Grocery stores mine information about shoppers’ buying history to plan their future promotions.
to house – to store; to keep something until it is needed
* Where are you going to house all that camping gear during the winter months?
inventory – stock; all the products that are being stored until they are purchased and sent to the buyer
* Businesses try to minimize their inventory to save money, but if inventory is too low, they don’t have enough products to mail to customers.
the next big thing – the most recent thing to become very popular very quickly among many people; the latest fad or trend
* Do you remember when roller skating was the next big thing?
ecommerce – the practice of selling things on a website, not in a physical store
* Ecommerce makes it easier for customers to find the lowest price for the things they want to buy.
Comprehension Questions
1. What will their marketing plan do?
a) Identify ways for them to find new customers.
b) Help them sell more cars.
c) Reach out to new markets in other countries.
2. What will the database do?
a) It will describe all the products that are available for sale.
b) It will store information about customers and their purchases.
c) It will help them ship products inexpensively.
Answers at bottom.
What Else Does It Mean?
to pour in
The phrase “to pour in,” in this podcast, means to receive a lot of something, especially money: “As soon as the new downtown park was completed, people began pouring in.” The phrase “to pour out” means for something to come out very easily and quickly: “As soon as Becca sat down in front of the computer, the words began pouring out and she wrote the book in just a few weeks.” The verb “to pour” means to rain heavily: “It’s pouring outside, so take your rain jacket.” The phrase “when it rains, it pours” means that whenever a few good/bad things happen, many good/bad things happen: “After years of steady sales, we got hundreds of new clients in the past three months. When it rains, it pours.”
to capture
In this podcast, the verb “to capture” means to observe and record or save data: “Is there a way to capture customers’ address and phone number automatically?” The verb “to capture” also means to find and catch a person and hold him or her involuntarily: “He was captured and held as a prisoner for almost three years.” The verb “to capture” can also mean to express one’s feelings or emotions through words or art: “It’s difficult to capture these feelings in writing.” The phrase “to capture (someone’s) heart” means to make someone fall in love with oneself: “What did she do to capture your heart so quickly?” Finally, the phrase “to capture (one’s) imagination” means to make someone become very interested in something: “His writing captured her interest in space exploration.”
Culture Note
The CAN-SPAM Act of 2003
The CAN-SPAM Act of 2003 was the first law in the United States that “dealt with” (was related to) how businesses can send email. The full name of the “bill” (proposal for a new law) was Controlling the “Assault” (attack) of “Non-Solicited” (not requested) “Pornography” (images showing sex and designed to create interest in sex) and Marketing Act of 2003.
Unfortunately, the law has been “largely” (mostly) “ineffectual” (not successful, not able to get things done). Many people argue that the law was weak “to begin with” (from the beginning). For example, under the law, companies sending marketing messages via email do not have to get “permission” (agreement to do something) from the “recipients” (people who receive messages). The law also does not let people “sue” (take to court to demand money) people who send “spam” (unwanted email).
People also complain that the law has not been “enforced” (making people comply with the law). In 2004, less than 1% of spam messages were “in compliance with” (following the rules of) the law.
The law has had some successes. For example, it requires that all “mass” (sent to many people at the same time) email messages include an “opt-out mechanism” (a way to request that one’s email address be removed from a distribution list) and that those opt-out requests are “honored” (obeyed; followed) within ten days. The law also states that the “from” line should accurately “indicate” (show) who the message is from and the “subject line” must be “relevant” (related to the subject of the message).
Comprehension Answers
1 - a
2 - b