
= step 2 - Lesson 32
:toc: left
:sectnums:

---



Lesson 32 +

== part


Interviewer: Could you tell me how we should keep fit? +
Dr. Davis: Well really what we should do is to try to erm keep fit all round. Now what do I mean by that? I mean er such things as keeping up our strength and our suppleness and our stamina. Now er you may say why do we need all three of those things? Well, erm strength is useful really just so that we erm don't strain muscles or pull ligaments and tendons when we suddenly have to do something er a bit energetic like lift a heavy suitcase or er perhaps er shift a wardrobe or even get out of a chair or a bath. Erm. Suppleness is important er obviously so that you can can bend and and move freely and reach things, again without injuring yourself. And stamina is particularly important so that you can sort of keep going without ... without losing breath so you have you have endurance. One other great plus about developing stamina is that if you er maintain your stamina over a period of years, it actually has an effect of protecting the heart against heart disease. +
Interviewer: So out of those three, which is the most important? +
Dr. Davis: Well, it depends who you are and what you want to do. I mean, the ... the reason for keeping fit is to keep fit for your way of life, the life you choose. Now, you may say 'Well, if I choose to sort of flop about in an armchair all day watching telly, I don't need to keep very fit, do I?' Well, that's unfortunately not true because there are always times when you have to make a little bit of extra demand on your body. Erm by force of circumstance. You may have to suddenly lift something heavy or move something or may have to er run for a bus or whatever. In which case you could do yourself an injury and you may even actually erm harm something important, like your heart. So it is important to actually to try to keep your fitness a little bit ahead of the sort of erm way of life that you have. Just to give you ... to push yourself just that little bit harder and get yourself just that little bit fitter. +
Interviewer: So how do you do it? +
Dr. Davis: Well it doesn't have to be all grim and irksome. I mean, people have this view of fitness er freaks you know, who sort of are jogging grim-faced round the park you know, or who are er working weights, doing all sorts of horrible exercises you know. PT ... Very grim indeed. It doesn't have to be like that. To keep yourself fit, or get yourself fitter, which is really what it's about, you just have to do a little bit more each day, erm or even every other day for that matter. By a little bit more I mean erm for instance just er walking a bit more often, a bit further, perhaps getting off the bus a stop or two sooner. Erm perhaps er doing a bit of ... a bit of cycling instead of travelling by public transport. Using the stairs instead of going up in the lift. It's surprising the number of people that erm I see on the London tube who are actually standing on the escalators going down you know, just standing there slowly going down. And the same with lifts. People who take the lift down I mean, that's ridiculous. You should at least walk down, but preferably walk up, because by walking upstairs you actually perform really quite a useful aerobic exercise, that's an exercise that develops stamina, and that's having a beneficial effect on your whole body, toning you up and helping to protect against heart disease. +
Interviewer: So it isn't necessary to play squash three times a week or go swimming three times a week? +
Dr. Davis: It isn't necessary. Er actually swimming is a rather good way of keeping fit because it's particularly excellent for erm all three of the S-Factors if you like, the strength, the suppleness and the stamina. It helps to develop all three of those rather well, and er it's also a very pleasant and relaxing way to keep yourself in shape. Three times a week would be just about right actually, or even twice a week, or even once a week. Em. Squash though is not a good way to get fit. You have to actually get fit to play squash. Squash is a very demanding game. A very very er energetic game, and in fact you could do yourself a lot of damage by playing squash if you're not in good physical shape to start with. +
Interviewer: I have a lot of friends who play sport, and they always seem to have bad backs and pulled tendons, so what would you say to them? +
Dr. Davis: I'd say to them they're ... they're going about it the wrong way. Erm. They're forcing themselves into ... into sports, perhaps before they're ready, before they've got themselves in shape first. You have to get in shape to play these sports. Erm. And also for people who force themselves into these things generally. That's bad. Mustn't do that. Whenever you're exercising, or ... or just carrying out some physical activity, never push yourself beyond comfort. Anything that's uncomfortable, don't do it. Stop. Slow down. It's basically got to be fun. I mean, to keep yourself in shape you've got to carry on exercising week in week out, month in month out, year in year out, Now that sounds awful, but if you choose something which you enjoy doing, er, it's fun, then you will keep it up. You see you can't put fitness in the bank as it were. If you don't carry on exercising, all the benefits that you get from exercising will all disappear within about 6 to 8 weeks. All go and you'll be back where you stared so you have to keep it up, and to keep it up, it has to be something you enjoy, it has to be fun. So choose something which you get a lot of pleasure out of, and that way it won't seem irksome at all. +
Interviewer: What do you do to keep fit? +
Dr. Davis: Ah well, I'm glad you asked me that question. Actually, what I ... I live in London and I work in London, er so what I what I do to keep fit is to certainly do quite a lot of walking. I certainly walk upstairs er a lot, but also I do a fair amount of cycling, er and as I'm dashing round London I I use the bike. I find it the fastest way to get around town and it's er it's really good for keeping in shape. I'm a little worried about the traffic fumes, I have to admit, but actually er it makes me feel very good to cycle around there and I get there on time!
 +


采访者：您能告诉我我们应该如何保持健康吗？

戴维斯博士：嗯，我们真正应该做的是努力保持全面健康。我这是什么意思？我的意思是保持我们的力量、我们的柔软度和我们的耐力之类的事情。现在你可能会说为什么我们需要这三样东西？嗯，力量确实很有用，这样当我们突然需要做一些需要精力的事情时，比如举起一个沉重的手提箱，或者呃也许呃移动一个衣柜，甚至走出去时，我们就不会拉伤肌肉或拉伤韧带和肌腱。一把椅子或一个浴缸。嗯。柔软度显然很重要，这样您就可以自由弯曲、移动并够到东西，而且不会伤害自己。耐力尤其重要，这样你就可以继续前进而不会……​而不会失去呼吸，这样你就有耐力。增强耐力的另一大好处是，如果您在几年内保持耐力，它实际上具有保护心脏免受心脏病的作用。

记者：那么这三个中，哪个是最重要的呢？

戴维斯博士：嗯，这取决于你是谁以及你想做什么。我的意思是，......保持健康的原因是为了适应你的生活方式，你选择的生活。现在，你可能会说，“好吧，如果我选择整天坐在扶手椅上看电视，我不需要保持非常健康，不是吗？”不幸的是，事实并非如此，因为有时您必须对自己的身体提出一点额外的要求。嗯，迫于环境的力量。您可能必须突然举起重物或移动某物，或者可能必须跑去公交车或其他什么。在这种情况下，您可能会伤害自己，甚至可能伤害一些重要的东西，例如您的心脏。因此，重要的是要真正尝试让自己的健康状况比现有的生活方式提前一点。只是为了给你……​让自己更加努力一点，让自己变得更健康一点。

采访者：那你是怎么做到的呢？

戴维斯博士：嗯，这并不一定都是残酷和令人厌烦的。我的意思是，人们对健身怪胎有这样的看法，你知道，他们在公园里面色严峻地慢跑，或者你知道，他们正在举重，做各种可怕的运动。 PT……确实非常严峻。它不一定是那样的。为了让自己保持健康，或者让自己变得更健康，这才是真正的意义所在，你只需要每天多做一点，呃，甚至每隔一天就做一点。我所说的多一点，是指呃，比如，多走一点，走远一点，也许早一两站下车。呃，也许呃，骑一点自行车，而不是乘坐公共交通工具。使用楼梯而不是乘坐电梯。令人惊讶的是，我在伦敦地铁上看到有多少人实际上站在自动扶梯上，你知道，只是站在那里慢慢地下。电梯也是如此。我的意思是，那些乘电梯下来的人，这太荒谬了。你至少应该走下去，但最好是走上楼，因为走上楼实际上是一种非常有用的有氧运动，这是一种增强耐力的运动，对你的整个身体产生有益的影响，使你强身健体，帮助你预防心脏病。

采访者：所以一周打3次壁球、游泳3次是没有必要的吗？

戴维斯博士：没有必要。嗯，实际上游泳是一种很好的保持健康的方式，因为它对于呃所有三个 S 因素（如果你愿意的话）尤其出色，即力量、柔软度和耐力。它有助于很好地发展这三个方面，而且这也是一种非常愉快和放松的保持身材的方式。其实一周三次就差不多了，甚至一周两次，甚至一周一次。嗯。不过，壁球并不是健身的好方法。您必须真正保持健康才能打壁球。壁球是一项要求非常高的运动。这是一项非常非常精力充沛的运动，事实上，如果你一开始的身体状况不佳，打壁球可能会对你自己造成很大的伤害。

采访者：我有很多运动的朋友，他们总是感觉腰不好、筋拉伤，你想对他们说什么？

戴维斯博士：我会对他们说，他们……他们的处理方式是错误的。嗯。他们强迫自己进入……​运动，也许在他们准备好之前，在他们首先塑造自己的身材之前。您必须保持体形才能参加这些运动。嗯。对于一般强迫自己做这些事情的人来说也是如此。那很糟。绝对不能那样做。每当您锻炼或……​或只是进行一些身体活动时，切勿让自己感到舒适。任何不舒服的事情，都不要做。停止。减速。基本上一定很有趣。我的意思是，为了保持身材，你必须每周、每月、年复一年地坚持锻炼，这听起来很糟糕，但如果你选择你喜欢做的事情，呃，那就很有趣，那么你就会坚持下去。你看，你不能像以前那样把健身放在银行里。如果您不继续锻炼，您从锻炼中获得的所有好处将在大约 6 至 8 周内全部消失。一切都过去了，你会回到原来的地方，所以你必须坚持下去，而要坚持下去，它必须是你喜欢的事情，它必须是有趣的。因此，选择一些能让你从中获得很多乐趣的事情，这样就不会显得令人厌烦。

采访者：你会做什么来保持身材？

戴维斯博士：嗯，我很高兴你问我这个问题。事实上，我……​我住在伦敦，在伦敦工作，所以我为了保持健康所做的就是做大量的步行。我当然经常步行上楼，呃，但我也骑了很多自行车，呃，当我在伦敦奔跑时，我会骑自行车。我发现这是游览城镇最快的方式，而且它对于保持身材真的很有好处。我不得不承认，我有点担心交通烟雾，但实际上，呃，在那里骑自行车让我感觉非常好，而且我准时到达那里！


---

== part

In September bombs went off in Coeur d'Alene, Idaho. They were the work allegedly of a group of Neo-Nazis, three of whom now sit in an Idaho jail awaiting trial. While they wait, commentator Clay Morgan has been thinking about the bombings, the bombers and what it all means for his part of the country. +
 +
I lived in a promised land. We got trouble here right now. Some Neo-Nazis declared the north-west to be the homeland for the white races. In the past several weeks we've had four bombs blow up. The situation here is serious. I had a hope that they just go away. I was embarrassed by the news coverage. Every time I saw a story, I cringed and thought my God this will make four more of them move here. Then the bombs exploded in Coeur d'Alene. Let me describe these people to you. They are men mostly. They like to live in forts, and dress up like Hitler. They wear jackboots, brown shirts and military caps. They march around and act tough. What they are is evil. These are the cowardly little boys who never grow up. It is our misfortune that they came here. The north-west attracts these people with all the attributes of a promised land. A promised land you see is a place that's far away, isolated and sparsely populated by people who try to mind their own business. The north-west fits that bill. Ninety percent of some of our states are public lands, owned by everybody. That's everybody. This is a place to breath in. The pioneers came here on the Oregon trail. The Mormons came here to practice their religion. The Basques came here to escape poverty and persecution in Spain. Wyoming was the first state to give women the vote, the first to elect a woman governor. Idaho was the first to have a Jewish governor. Now we are attracting fascists like we were Paraguay. Bad things are happening in a good place. +
 +
We would like to have the sheriff go to them and say, "Pack up! Clear up! Get out of the state by sundown!" But we cannot. It is not against the law to believe in evil. The white supremacists protected by laws are meant to protect everybody. That's everybody. And we are to keep those laws. We can only watch these creeps and be ready when they make their move. The people who set off those bombs in Coeur d'Alene meant to rob the bank and ransack the armory. But when the bombs went off, the law came down so fast and hard the perpetrators lost their nerve. They got caught. There were several others who were not in jail yet. But we know about them. We can stand up to them. Those bombs did not scare Coeur d'Alene. So get ready for a good ending to a bad story. After all this embarrassment, Coeur d'Alene would be the town that stands up to evil and wins. And this Promised Land, maybe, would drop out the news and we can mind our own business again. +
 +
Writer Clay Morgan lives in McCall, Idaho. He comes to us by way of member station KBSU in Voizy, Idaho.


九月，爱达荷州科达伦发生炸弹爆炸。据称，这些作品是一群新纳粹分子的作品，其中三人目前关押在爱达荷州的一所监狱中等待审判。在他们等待的同时，评论员克莱·摩根一直在思考爆炸事件、轰炸机以及这一切对他所在的地区意味着什么。


我生活在一片应许之地。我们现在遇到麻烦了。一些新纳粹分子宣称西北部是白人的家园。在过去的几周里，我们已经发生了四枚炸弹爆炸事件。这里的情况很严重。我希望他们能走开。我对新闻报道感到尴尬。每次我看到一个故事，我都会感到畏缩，心想天哪，这会让另外四个人搬到这里。随后炸弹在科达伦爆炸。让我向你描述一下这些人。他们大多是男性。他们喜欢住在堡垒里，穿得像希特勒。他们穿着长筒靴、棕色衬衫和军帽。他们四处游行，表现得很强硬。他们的本质是邪恶的。这些都是永远长不大的懦弱的小男孩。他们来到这里是我们的不幸。西北地区以其应许之地的所有特征吸引着这些人。你所看到的应许之地是一个遥远、偏僻、人烟稀少的地方，人们只管自己的事。西北地区符合这一要求。我们一些州百分之九十的土地都是公共土地，归所有人所有。这就是所有人。这是一个可以呼吸的地方。拓荒者沿着俄勒冈小道来到这里。摩门教徒来到这里信奉他们的宗教。巴斯克人来到这里是为了逃避西班牙的贫困和迫害。怀俄明州是第一个给予女性投票权的州，也是第一个选举女性州长的州。爱达荷州是第一个有犹太裔州长的州。现在我们像巴拉圭一样吸引法西斯分子。好地方却发生了坏事。


我们想让治安官去对他们说：“收拾行李！清理干净！在日落之前离开这个州！”但我们不能。相信邪恶并不违法。受法律保护的白人至上主义者是为了保护所有人。这就是所有人。我们要遵守这些法律。我们只能看着这些小兵，并在他们采取行动时做好准备。在科达伦引爆炸弹的人意图抢劫银行并洗劫军械库。但当炸弹爆炸时，法律的严厉严厉让肇事者失去了勇气。他们被抓住了。还有其他几人尚未入狱。但我们了解他们。我们可以对抗他们。这些炸弹并没有吓到科达伦。所以，准备好迎接一个坏故事的好结局吧。在经历了所有这些尴尬之后，科达伦将成为对抗邪恶并取得胜利的城镇。也许，这个应许之地会放弃这个消息，我们就可以再管好自己的事了。


作家克莱·摩根住在爱达荷州麦考尔。他通过爱达荷州 Voizy 的 KBSU 会员站来到我们这里。

---

== What Your Sense of Time Tells about You (I) +

Imagine you are a high school principal. A teacher bursts breathless into your office. "There's a fist fight in the lunchroom," she gasps. The responsibility is yours to stop the fight. How do you meet it? +
 +
(1) Perhaps you, as a youngster, took part in fights and your present-day ties with students are warm and strong. You can stop the fight because your prestige is high among them. +
 +
(2) You have a plan prepared. Other schools have been disrupted so you have already planned a way to stop any fight. +
 +
(3) You are totally confident of your abilities in a crisis. You are ready to stride into the lunchroom and take charge without a single qualm. Stopping the fight will be easy. +
 +
(4) You fervently wish that you could delegate the job since you know that you're not a talented peacemaker. You wish you could return to the job of planning for the school's needs ten years hence. +
 +
One of these four reactions would be the first you'd feel, but only one — not two or three of them, say three psychologists. These psychologists — Dr. Harriet Mann, Dr. Humphrey Osmond and Miriam Siegler — have come up with a scheme for sorting people regardless of their education, age or situation. +
 +
The concept is based on the premise that all people have a basic way of seeing time. Each of us is predisposed to seeing all events from one time vantage point. Either it reminds you of the past (past-oriented), how the event fits in to today, yesterday and tomorrow (time line), what it is today (present), or how it will develop (future). +
 +
The three began working in 1968 when Dr. Mann and Mrs. Siegler were assistants to Dr. Osmond, director, at the Bureau of Research, New Jersey Neuro-Psychiatric Institute in Princeton. Dr. Osmond is currently devising ways to make empirical studies of the theory and Dr. Mann is in Cambridge, Massachusetts, writing a book on the Worlds of Time. Their take-off point was an interest in observations made by Swiss psychologist Carl Gustav Jung, who described in the 1920s the temperamental differences of four psychological types. Jung is known as the founder of analytic psychology. Since Jung's work in 1921, however, no one had conceived of a theoretical framework that would account for the four types. Without such a framework, there was no possibility of substantiating that people of different types experience the world very differently. Time and space are the touchstones in the system. Each person, after all, uses his time somehow and exists within and acts upon the space around him. Dr. Mann and company propose that certain traits are shared by persons falling in each of the four categories. +
 +
The first type, the past type, sees time as being circular. For him, the past crops up in the present and then returns to the past as a memory. He enjoys collecting souvenirs and keeping diaries. He tells stories about Great Aunt Hattie and always remembers your birthday. +
 +
Past types are pegged by this system as emotional people who see the world in a highly subjective way. For instance, School Principal I (past type) could identify with the fight and know how to handle it because of some past experience — whether it be similar fights as a child himself or ones previously dealt with as the school principal. In addition, past types usually follow strict moral codes and often are valued more for what they are than for what they do. This quality itself — because it lends authoritarian strength to one who possesses it — might cause the students to quit fighting. Past types often have been found to be skillful at assessing the exact emotional tenor of an event and are adept at influencing others' emotions, according to the Mann group. +
 +
Research reveals that many past-oriented people are flexible in early years when they do not have much of a personal past to draw upon. However, the dash of youth is often replaced by a need for stability and usually is rooted by age thirty-five or so. From this age onward, they are conservatives. +
 +
"They need to see things in the ways which were popular, fashionable and appropriate in their younger days," explains Dr. Mann. This applies, with exceptions of course, to personal taste in clothing fashions, music appreciation, and other social and environmental factors. In short, the past type often clings to the well-established way with nostalgic verve. Also, the past type finds it difficult to be punctual since the on-going feeling is more important than his next task. +
 +
The goal of these people is "to develop a language of the heart, rather than of the mind. To develop those techniques which make memories live, and to dignify any act of remembrance; those are the essential concerns of past-oriented types," explain the authors in the Journal of Analytical Psychology.


你的时间观念告诉你什么（一）
想象一下您是一名高中校长。一位老师气喘吁吁地冲进你的办公室。 “餐厅里有人打架，”她喘着气说。停止战斗是你的责任。你如何满足它？


(1) 也许你小时候参加过打架斗殴，现在你和学生的关系是温暖而牢固的。你可以停止战斗，因为你在他们中的威望很高。


(2) 你已准备好计划。其他学校已经被扰乱，所以你已经计划好了阻止任何打斗的方法。


(3)你对自己在危机中的能力充满信心。您已准备好大步走进餐厅并毫无疑虑地接管一切。停止战斗很容易。


(4) 你热切地希望能够将这项工作委派出去，因为你知道自己不是一个有才华的和事佬。您希望十年后能够重返规划学校需求的工作。


三位心理学家表示，你首先会感受到这四种反应中的一种，但只有一种，而不是两种或三种。这些心理学家——哈里特·曼博士、汉弗莱·奥斯蒙德博士和米里亚姆·西格勒——提出了一种对人们进行分类的方案，无论他们的教育程度、年龄或情况如何。


这个概念的前提是所有人都有一种看待时间的基本方式。我们每个人都倾向于从一个时间的有利位置来看待所有事件。它要么让你想起过去（面向过去），事件如何适应今天、昨天和明天（时间线），今天是什么（现在），或者它将如何发展（未来）。


三人于 1968 年开始工作，当时曼恩博士和西格勒夫人是普林斯顿新泽西神经精神病学研究所研究局主任奥斯蒙德博士的助手。奥斯蒙德博士目前正在想办法对该理论进行实证研究，曼恩博士正在马萨诸塞州剑桥市撰写一本关于时间世界的书。他们的出发点是对瑞士心理学家卡尔·古斯塔夫·荣格（Carl Gustav Jung）的观察感兴趣，荣格在 20 年代描述了四种心理类型的气质差异。荣格被称为分析心理学的创始人。然而，自 1921 年荣格的研究以来，没有人设想出一个能够解释这四种类型的理论框架。如果没有这样一个框架，就不可能证实不同类型的人对世界的体验有很大不同。时间和空间是系统的试金石。毕竟，每个人都以某种方式利用他的时间，存在于他周围的空间中并对其周围的空间采取行动。曼恩博士和他的同事提出，属于这四个类别的人都具有某些共同特征。


第一种类型，即过去类型，认为时间是循环的。对他来说，过去在当下突然出现，然后又作为记忆回到过去。他喜欢收集纪念品和写日记。他讲述关于海蒂姨婆的故事，并且永远记得你的生日。


过去的类型被这个系统视为情绪化的人，他们以高度主观的方式看待世界。例如，校长一（过去的类型）可以因为过去的一些经验而认同这场打架，并知道如何处理它——无论是他自己小时候遇到过的类似打架，还是以前作为校长处理过的打架。此外，过去的类型通常遵循严格的道德准则，并且往往更看重他们的本质，而不是他们的行为。这种品质本身——因为它赋予拥有这种品质的人独裁的力量——可能会导致学生们放弃战斗。曼恩小组表示，过去的类型通常被发现善于评估事件的确切情绪基调，并且善于影响他人的情绪。


研究表明，许多以过去为导向的人在早年没有太多个人过去可以借鉴的时候就很灵活。然而，青春的活力常常被对稳定的需求所取代，并且通常在三十五岁左右就扎根了。从这个时代开始，他们就是保守派。


“他们需要以年轻时流行、时尚和合适的方式看待事物，”曼博士解释道。当然，这也适用于个人对服装时尚的品味、音乐欣赏以及其他社会和环境因素。简而言之，过去的类型往往怀着怀旧的神韵，固守既定的道路。此外，过去型的人发现很难准时，因为正在进行的感觉比他的下一个任务更重要。


这些人的目标是“发展一种内心的语言，而不是头脑的语言。发展那些使记忆生动的技术，并尊重任何纪念行为；这些是面向过去的类型的基本关注点，” 《分析心理学杂志》的作者对此进行了解释。


---
