
= step 2 - Lesson 25
:toc:
:sectnums:

---



Lesson 25 +

== part


Mary: On holiday, one summer, we were camping, of course, (Yes, of course) er, and had been to Italy and, er, back into France (Yeah) and, at the border, we had an awful lot of trouble finding the passport and (Mm) the this and the that, (Mm) to move over from Italy to France, erm, so I was rather disappointed a, at the mess we'd made of it and, as we travelled on into France, I spent the rest of that day tidying up the car (Mhm) and I very carefully put into one folder the passports, the tickets, travellers' cheques and all our currency (Yeah) and it was all beautifully packed so that we wouldn't be caught in this position again of not being able to find (Mhm, Mhm) anything. Erm, we eventually decided to stop in a town where we knew there was a campsite and in the town we stopped at a garage, really to ask the way to the campsite, (Mm) but while we were there we thought, well, we'll get some petrol, erm, and, er, ask the question at the same time. (Yeah) Erm ... the man put the petrol in the car and, with all efficiency, I took out the folder (Yeah) with the money in it (Mhm) and paid for the petrol and then we went on our way. The campsite was about two or three miles away. Er, when we got to the campite, we went into the office and one of the things one usually carries as a camper is a little sort of card, erm, a camping ticket, if you like, and, er, I ... +
Tom: What's that for? +
Mary: Well, one gets reduced rates for being a (Oh, I see) member of a camping club, (Mm) or something like that. Erm, and I went to get it from the folder, properly packed folder, (Mm) and I could not find the folder! (Oh, God!) We had everything out of the car, all over the floor on the grass, erm, and each one of us was sure we, er, had seen it somewhere since the garage. And we finally had to say to these people, 'We are very sorry, we have no money, no card, no nothing' And ... +
Tom: How much money was involved? +
Mary: Well, all our holiday money, you know. Some hundreds of pounds, in travellers' cheques and some in currency, you see, a few pounds ... +
Tom: And passports? +
Mary: And passports, and tickets for the boat (God!) Erm, so we said we'd go to the police station. So back we went to the town. And we all went into the police station. Erm, and a very friendly policeman said, 'Well, I can do nothing about it. Your best bet is to see the British Consul, er, in the city.' Erm, well this was on a Saturday afternoon and it was five o'clock and he told us that we would be able to get into the, er, Consul on Monday morning when they opened, which didn't encourage us too much. (Quite!) Then it suddenly struck us that somebody must have taken this money, at the garage, (Ah, of course) so back we went the garage (Mhm) and we thought that as we stood talking to the man asking 'Where do you go to the campsite?', someone else had obviously stolen our folder. +
Tom: That was the last time you'd had it ...? +
Mary: Yes, indeed, (Mm) you see, erm, that was the last time that we could all agree (Mm) that we must have had it. (Mhm) So, er, John distracted the man's attention and I went into the man's office and went all through his papers on his desk (laughter) looking for it. It was a sort of green-coloured folder (Yeah) which one should have found easily (Yeah) and it wasn't there. And then we saw an old woman across the road, sitting on a window-ledge, and I was sure she was sitting on our folder because something green was sticking out underneath her. And we had to try and work out some way of moving er, to see. And eventually we persuaded her by asking her to give us directions and she stood up to speak to us. But it wasn't our folder at all she was just sitting on a little green mat (Oh) obviously to keep herself clean. Erm ... and we were feeling pretty desperate by now, (I bet you were. Yeah) so back we went to the campsite and we were going to beg, 'Please, may we stay tonight and worry (Mm) about it tomorrow?' (Mm) you see. And when we got back they said, 'There's been a phone call. Would you go to this address? Er, someone has found your folder.' So ... +
Tom: How would anybody who'd found your folder (have) phoned, the fact, the campsite? +
Mary: Right. Well, this is what we discovered. We were w, worried, because someone might have found it (Mm) and we might get our passports, but what about our money, you know. (Quite, yeah) So we went to the address, (Mhm) and it was a little cycle-repair shop, kept by two brothers. And they told us that they had seen us driving up the road to the campsite. We had swung round a corner (Mm) and the folder had flown off the top of the car! (Cor) We'd obviously left it (Yes) there, at the garage. And it had fallen at their feet. (Good heavens!) They saw the tent and camping stuff (Yeah) on top of the car. (Mm) They saw which way we were going. (Mm) They guessed we were going to the campsite, because it (Mm) was just a country lane (Mm) and they telephoned! Weren't we lucky? And (Gosh!) when we got there they said, er, 'Would we check that everything (Mm) was there.' (Mm) And certainly everything was there, (mm) nothing gone. And we were so pleased, we'd only got one piece of, erm, French currency — it was on large-value (Mm) note (Mm) — a number of pounds. (Mm) Erm, and we knew that we had to live till Monday, (Yeah) so we asked them if they would change this note for us. Erm, and the man sent a small boy to another shop to get change (Yes) and he came back with two equal value notes, (Oh yes) he'd split it in half (Mm) if you like. So we gave them half (Yeah) and we went back to the campsite and put up our tent and installed ourselves and then we went out and spent the other half on a celebration. Erm, and er, of course, we had no money all day Sunday (Yes) and had to spend the day eating bread and si ... +
Tom: But you felt rich, because you'd got everything back. +
Mary: Indeed, we were so relieved ... +
Tom: How terribly lucky, though! What a lucky story!

---

== part

Lesley: Oh Jackie, I've had such a terrible day. You just won't believe. +
Jackie: You look exhausted. What on earth have you been doing? +
Lesley: Oh, I've been such a fool! (Oh) You just wouldn't believe what I've done. +
Jackie: I would, I would. Come on ... (You won't) Where've you been? +
Lesley: I'm dying to tell someone. I've been down to London (Uh-huh) you see. (Uh-huh) OK, I thought I'd be very sensible, so I'd drive down to the Underground on ... on the outskirts of London, leave the car and go in by Tube. All right? (Er ... what you) Very sensible. (Yes) Yes? (OK) OK. So I drove down to London (Uh-huh) and I parked my car by the Tube station and I got the Tube into London. (Uh-huh) Fine! All right? (Well, sounds like it) so far, so good. (Yes) Right. Came back out of London ... (Uh-huh ... and you er ... forgot the car?) Got out of the Tube. No, no, I didn't forget the car. (Oh) I couldn't find the car, Jackie. (You're joking) It'd gone. (You're kidding) No, no, really, it'd gone. I walked out ... happily out of the Tube, you know, over to where it was (Mm) and I looked and it was a red Mini and mine's green, so (Oh on!) I thought 'Oh no'. So having panicked a bit, I rang the police, you see, and this lovely, new little policeman ... a young one (Yes, all shiny and bright) came out to help. That's it yes ... buttons shining ... (Yes) big, smile ... came down to help, so I said 'I've lost my car. It's been stolen' and I took him to see it and everything and ... +
Jackie: You mean where it wasn't. +
Lesley: And sure enough, it wasn't ... yes, well, right ... and it wasn't there. And then he coughed a bit and he went very quiet ... (Oh dear) and he took me back into the Tube station (Oh dear) and out the other side into the other car park ... and there was my car, Jackie (Oh Lesley) parked in the other Tube station car park, the other side of the station, because there are two exits, you see, so I walked out of an exit (Yes) not knowing there were two and it was in the other one. +
Jackie: Oh Lesley. And was he ever so cross? +
Lesley: He was livid, Jackie. (Really) He really ... he went on and on at me and I didn't know what to do. It was (Oh dear) just frightful. I just ... I went red and just shut up and said 'Sorry' all the time. +
Jackie: Jumped in your car and (Oh yes) and left. +
Lesley: Oh, it was awful. I'm never doing that again ever.

---

== part

Today we're going to look at some aspects of life — or perhaps it would be more correct to say 'death' in Ancient Egypt. +
 +
Egypt has always fascinated ordinary people as well as scholars engaged in the serious study of the past. To most of us it's a land of mystery and magic. In particular, the custom of preserving the bodies of important people, especially of kings and queens, has quite a hold on the popular imagination. How many thrillers and horror films are based on the idea of finding a mummy in the secret tomb of a lost king, who in the case of horror movies usually comes to life again! +
 +
In earlier times the subject exerted a more sinister fascination — so-called 'mummy dust' — the powdered remains of dead Egyptians — was thought to be an essential ingredient in many magical spells and medical remedies — a case of the cure being worse than the disease? +
 +
This of course led to a great demand for mummies both inside and outside Egypt, and even to an industry of making 'false mummies' to sell to unsuspecting foreigners. This continued well into the 19th century. Even when, at that time, tighter controls were exerted by the Egyptian authorities, many mummies were still sold on the Black Market, and even some of the mummies that were acquired for museums for scientific purposes were bought clandestinely. +
 +
These days, archaeologists and anthropologists have more moral scruples about the way they treat the dead — even those who have been dead for thousands of years. That's one reason why — even though new techniques of analysis can reveal fascinating information, there is some hesitation about carrying out 'autopsies' on too many mummies in an indiscriminate way. Besides the ethical question, there is the practical one that any analysis must involve at least some degree of destruction. +
 +
The studies that have been made in recent years have therefore for the most part been of mummies which were already in poor state of preservation, and the investigators have tried to do the minimum damage possible — taking only tiny samples of tissue for analysis, or using non-destructive means of study such as X-rays. +
 +
At the end of each study, it is now customary to restore the mummy to a state of 'decent burial'. In this way, the scientists involved have tried to satisfy both their curiosity and their consciences. +
 +
In a moment, I'm going to ask Dr Albert Simons, a noted expert on Egyptian archaeology, to give us an overview of some recent studies and what they have revealed ...

---

== Burglaries +

The figures for burglaries have risen alarmingly over the last few years and are now quite appalling. Let me quote you a few statistics about break-ins. +
 +
A house is burgled in Britain now about every two minutes, and over the past three years the number of burglaries reported to the police has risen by approximately 50,000 to well over 400,000 this year. The insurance companies report that last year alone household burglary losses rose by 27 per cent over the previous year to ￡138.2 million, and I believe one or two companies are refusing to provide burglary cover in what we might call high-risk areas. +
 +
There are, nevertheless, half a dozen measures which can be taken against burglaries, which I will briefly outline for you. It really only requires some basic common sense and a small outlay, combined with a little knowledge of the way a burglar thinks and operates. You have to put yourself in his position, really. Most burglars are opportunists looking for an easy break-in, so don't make things simple for them. Don't advertise the fact you're out or away, or be careless about security. Even if you're just popping out for a quarter of an hour, don't leave doors and windows open or unlocked. A burglary can take less than ten minutes. +
 +
This time element leads me to my second main point, that where a house is hard to get into and will take a long time to do so because you've fitted good locks and bolts on your exterior doors and windows or even burglar alarms, the chances are that the burglar will move on to somewhere easier. There are plenty of these, I can assure you. Milk bottles left on the doorstep, papers by the front door, garage doors wide open, curtains drawn in the daytime or un-drawn at night are all indications. For comparatively little you can buy a programmed time-switch that'll turn on and off a light at appropriate times. +
 +
Not all burglaries happen while you are out, of course. You should always be wary of callers at the door who say, for example, that they've come to read the gas meter; always check their credentials, and if in doubt don't let them in. It's also a good idea to keep a record of serial numbers on electrical equipment, radios, TVs and so on, or even to take photographs of valuable jewellery, antiques or pictures. +
 +
Any further tips I may not have mentioned can always be got from your local police station, where you should ask to speak to the Crime Prevention Officer. +
 +
In the final analysis I think I should say that when it comes to fitting security systems and the like you've really got to strike a balance between the cost of what you spend on installing the system and the value of the property you're trying to protect.


---
