
= step 2 - Lesson 28
:toc:
:sectnums:

---



Lesson 28 +

== part



Robert: Now, one of the biggest hurdles to cross in getting a good job is the interview. There's no getting away from it, because in nearly every case when you apply for a job you will be called for one, or sometimes even two, interviews. It's quite natural that you might also be dreading it; in fact, some people dread them so much they never turn up at all. What I want to try to do today is to take some of the sting out of the interview and get you over what I call 'job interview jitters' to show you how you can make a good impression and even use the interview to your own advantage. I mentioned two interviews earlier because some companies do a kind of screening interview first, where they try to find out what you're like and if you're suitable for the job before you go on to the main interview. This screening interview would probably be with someone from the personnel department, and I'd like now to show you on the video a couple of examples of these screening interviews, which I hope will help to illustrate how to go about it and how not to. In the first, Walter Edwards of the personnel department of a biscuit factory in Southampton is interviewing Anita Jones for a job as a secretary. +
Walter: Come in, I'm Walter Edwards and you're Miss ...? +
Anita: Anita Jones, er, but my friends call me Nita. +
Walter: How do you do, Miss Jones. Do please sit down. Now, your application tells me you were born in these parts. Did you grow up here? +
Anita: Er, um, yes. Well, no. I was born here in Southampton, but my dad, that is my father, works in a bank so we, um, moved up north when I was fairly small, which is where I went to school and, um, then we moved back down here, which is why I live round here now, you see. +
Walter: Quite. And I see you've just completed a one-year secretarial course. Is this your first job application? +
Anita: Yes, er, well, no. I mean, I've had several holiday jobs and part-time jobs but this is, or rather would be my first full-time job. I mean this is the first time I've been looking for one. +
Walter: Do you have any special reason for choosing this company? +
Anita: Oh, not really. I mean, er, yes, I was attracted by the money but that's not the only reason, of course. (Laughs.) +
Walter: I see. And could you tell me about your secretarial skills? +
Robert: Without going any further, I think we can all see that Anita is a very nervous applicant: hesitant and indecisive. It's quite clear that she is petrified by the whole idea of the interview, and her faltering and stammering delivery is even irritating for a Mr. Edwards who has, after all, only a few minutes to find out about Anita and to see if she's the right one for the job. Another important point to raise is appearance, which Anita obviously didn't take much care over. Dress is very important and you should never turn up in jeans and an old sweater if you're after a job in an office or a place of work where you will be meeting people, dealing with clients and that sort of thing. Clean, smart clothes are the order of the day, and try to avoid stage fright, like some nervous actor on the opening night of a new play. Job applicants often look upon the interviewer as some kind of ogre who enjoys making interviewees squirm in their seats, a kind of figure to be looked up to and revered. This negative attitude of mind will not help in any way and will only destroy your self-confidence and ensure failure. +
 +
 +
  Anita also mentioned money straight away, which was bad and made her come across as being mercenary. The one question she did volunteer a lot of information about was her upbringing and that was all highly irrelevant. Before we move on, there's something else I wanted to point out and that was the way Anita moved. As she came into the room she sidled nervously up to the desk and wasn't quite sure whether to shake hands, sit down or what to do and kept looking nervously around her. Throughout the interview she fidgeted about and kept twiddling the strap on her handbag, which she clutched tightly to herself. Furthermore, she sat on the edge of her seat with hunched shoulders and a tense look on her face, all of which indicates to the interviewer she is someone who can't handle pressure and responsibility and who appears indecisive and unsure. You have to remember that you've got about ten or fifteen minutes to show what you're made of, and no matter how good you are normally, it's in these vital minutes that you must project the right image. Now we'll take a look at another interview and see what conclusions can be drawn from that one. In this excerpt, Louise Simpson is being interviewed for a job with a book publishing firm by Audrey Maguire of personnel. +
Louise: I'm Louise Simpson. +
Audrey: Sit down, please, Miss Simpson. I'm Audrey Maguire. +
Louise: How do you do? +
Audrey: When you came in, did you happen to notice all the building work going on? +
Louise: Yes, I did. +
Audrey: Well, that's our new office extension and we're moving there within the month, so that's where you'd be working. +
Loiuise: Yes, I did read about it in the prospectus you sent me about the firm. I'm sure you're looking forward to the move. +
Audrey: Indeed, yes. Now I'd like to ask you one or two questions about your previous experience, if that's all right? +
Louise: Go right ahead. +
Audrey: Have you had any jobs before? +
Louise: Yes, I worked as a secretary in a lawyer's office as a summer job, primarily to earn some money to see me through college, but I also gained some useful work experience into the bargain. While I was there I did secretarial work and also took a turn on the reception desk, to help out, and it was very enjoyable meeting people in this way to vary the routine. +
Audrey: Did you like working in the lawyer's office? +
Louise: From the career point of view it was good to get to know how an office works, but I've always wanted to be in publishing really, which is why I applied for this job. +
Audrey: Now, can you tell me ... +
Robert: I think we've seen enough to make the distinction between Louise and Anita you saw in the previous slip. Louise gives a totally different image, an image of self-confidence without being too cocky, and she was conducting herself in a relaxed and friendly way. She talked to the interviewer in a normal manner, which was fluent and without the terrible 'ums' and 'ers' of Anita. She also gave the impression that she was there to exchange information with the interviewer rather than be interrogated. She wanted to know if the company was going to suit her as much as they wanted to know if she would suit them. Her clothes were sober and neat, without being too frumpy, and she was relaxed and casual without being too laid-back so that it would appear she didn't care. She had also taken the trouble to read the prospectus she'd been sent, which didn't hurt at all. The basic point about an interview is that it shouldn't be a question-and-answer routine, a boss and servant session, but a coming together of two personalities. It's the 'swan technique' which projects the best image in my view, serene on the surface but paddling like mad underneath. And now I'd like to come to the problem of ...
 +

---

== part

It is an election day and the Americans of all fifty states are going to the polls. Election observers have predicted a light to moderate turnout, of about forty percent. But some counties' election officials we talked this afternoon were more optimistic. +
 +
"I'm in Lamar, Colorado. It's raining. It's a very grey day. I think we are going to have a real good turnout if the weather doesn't getting worse." +
 +
"I'm the county auditor in the north-eastern portion of Aberdeen, South Dakota, Brown County, South Dakota. Our turnout in Brown County is absolutely fantastic at this point. The weather is cooperating, is absolutely gorgeous, in South Dakota, sun-shining, crisp beautiful day. Couldn't have ordered anything finer?" +
 +
"We are in Shelby, Montana, the county seat of Toole County. The weather is 59 degrees today, no snow anywhere in our area. It's beautiful. No windy. We expected a very good turnout today." +
 +
And it's a small exemplar there. Thirty-six states will elect governors today, in addition there are hundreds of local contests and battle issues to be decided. But the control in the United States senate remains the major item of national interest. A third of the senate, thirty-four seats, will be decided today. Republicans who have held their slim majority in the senate for the past six years are defending twenty-two of those seats. Democrats need a net gain of four seats to win control. According to the latest pre-election polls, the closest senate races were in these nine states, Washington, Idaho, North and South Dakota, North Carolina, Georgia, Alabama, California and Colorado. This would be the most closely watched tonight as county election officials turn their attention from watching the skies to counting the ballots.

---

== Listening and Understanding +

A student learning English often finds the following problems when he listens to talks or lectures. +
 +
Firstly, he doesn't always identify all the words correctly. I refer here to known words. i.e. words which the student would certainly recognize in print. Let's examine some of the reasons for this particular difficulty. In writing, there are clear spaces between each word; in speech, one word runs into the next. It's very difficult to decide, therefore, where one word finishes and the next one begins. +
 +
In writing, the words consist of letters of the alphabet. These letters have a fixed shape: they're easy to identify. In speech, however, vowel and consonant sounds are often very difficult to identify. Some of these sounds may not exist in the student's native language. Many of them, particularly the vowel sounds, are given different pronunciations by different English speakers. +
 +
Finally, some words in English, words like 'and' or 'there' or 'are' or 'will' are frequently pronounced with their weak or reduced form in speech. This is sometimes so short that non-native speakers, perhaps not accustomed to it, fail to recognize it at all. Many students, for example, don't recognize the normal pronunciation / 5TErE / for the words 'there are' which occur at the beginning of so many English sentences. Furthermore, they encounter a similar problem with unstressed syllables which are part of a longer word. For instance, think of the word 'cotton', which is spelt 'c-o-t-t-o-n'. I'll repeat that: 'c-o-t-t-o-n'. Each letter is the same size; no difference is made between the first syllable 'cot-' and the second syllable '-ton'. In speech, however, the first syllable is stressed, the second is unstressed. The work is not pronounced 'cot-ton' but 'COTn'. The same is true for the word 'carbon', spelt 'c-a-r-b-o-n'; it's not pronounced 'car-bon' but 'CAR bn'. +
 +
But I want now to come on to the second main problem; the difficulty of remembering what's been said. Again, the problem here is much less difficult in the written rather than the spoken form. Words on a page are permanently fixed in space. They don't disappear like words that are spoken. They remain in front of you. You can choose your own speed to read them whereas in listening you've got to follow the speed of the speaker. A difficult word, or sentence, on the printed page can be read again, whereas a word not clearly heard is rarely repeated. The listener, therefore, finds that he has to concentrate so hard on identifying the words correctly and on understanding them that he has little time left to remember. +
 +
In a foreign language his brain simply has too much to do. In his own language, of course, he's able not only to identify and understand the words automatically but also he can often even predict the words which are going to come. His brain, therefore, has much more time to remember. +
 +
Thirdly, I want to deal with a problem that worries most students in a lecture. The problem is this — they can't always follow the argument. This is, of course, partly due to the first two difficulties I've discussed. When you have difficulty in identifying or remembering words and sentences, you obviously won't be able to follow the argument. But even those students who can do these two things perfectly well have problems in following a quite straightforward argument. Why is this? I'll suggest three reasons here. Firstly, students don't always recognize the signals which tell the listener that certain points are important. Some of these signals will be quite different from those employed in writing. Secondly, some students try too hard to understand everything. When they come to a small but difficult point, they waste time trying to work it out, and so they may miss a more important point. Thirdly, students must concentrate very hard on taking notes and therefore may miss developments in the argument. But note-taking is a separate subject which will be dealt with in a later talk. +
 +
There are, however, other problems the student is faced with, which I'd like to mention briefly. +
 +
It's always a surprise to students to discover how much the pronunciation of English changes from one English-speaking country to another, and from region to region. Many lecturers from Britain have a B.B.C. type accent, the type of English associated mainly with the South of England and most commonly taught to non-native speakers. However, other lecturers will speak differently. To give an example / bQs /, / lQv /, / mQm / etc., as spoken in the south, are pronounced in Manchester and many other parts as / bRs /, / lRv / and / mRm /, Southern English / ^rB:s /, / fB:st /, / pB:W / are pronounced in Yorkshire and elsewhere as / ^rAs /, / fAst / and / pAW /. It's worth noticing that it's usually the vowels which have variants, though sometimes it may be the consonants. For instance, a Scotsman will roll his 'r's', whereas a Londoner won't. So a lecturer with a particularly strong regional accent will cause non-native speakers considerable difficulty. +
 +
Whether a student follows a lecture easily or not depends also on the style of English the lecturer uses. By 'style' I mean the type of English chosen to express an idea: at one extreme it may be very formal, at the other colloquial or even slang. Generally speaking, the more formal the style, the easier it is for the student to understand. For example, a lecturer who says, formally, 'This is undoubtedly the writer's central point' will be readily understood. On the other hand if he says, 'That's really what the writer's on about, many students will have difficulty in understanding. +
 +
Other factors, which I haven't the time to discuss in detail, may also be involved. These include the speed at which the lecture is delivered, the rather common use of irony, the peculiarly English sense of humour, references which presuppose a knowledge of British culture, etc. +
 +
All these factors combine to make it a formidable task for students to follow lectures comfortably. It's clearly helpful to be aware of the problems and to get as much practice as possible in listening to and trying to understand spoken English.


---
