
= step 2 - Lesson 26
:toc:
:sectnums:

---



Lesson 26 +

== part


Interest in sport in Britain is widespread, as is indicated by the huge crowds which attend such occasions as the Football Association Cup Final at Wembley Stadium, international rugby matches at Twickenham, Murrayfield or Cardiff Arms Park, the Wimbledon Lawn Tennis Championships and so on. Not only do millions watch these matches on television but there is also growing enthusiasm for active participation in sport and recreation in the country as a whole. People find they have more free time on their hands nowadays, so there is a duty on the part of government to make opportunities and facilities available. Apart from the professional side of it, there is increasing enthusiasm for amateur sport, which has led to a growth in interest in climbing, rambling, boating and other water-based sports, as well as keep fit, and movement and dance activities. +
 +
Probably the most popular spectator sport is Association Football, which dates back to the nineteenth century and is controlled by separate football associations in England, Wales, Scotland and Northern Ireland. There are well over 400 clubs affiliated to the English Football Association or FA and some 37,000 clubs to regional or district associations. The main clubs in England and Wales belong to the Football League, 92 in all, and the 38 Scottish clubs belong to the Scottish League. They play in four divisions in England and three in Scotland. During the football season, attendances total some 27 million. +
 +
Local authorities provide facilities to cater for a wide range of indoor and outdoor activities; these include such things as golf courses, swimming pools and leisure centres. Total expenditure in the country as a whole on sport and outdoor recreation came to well over ￡500 million last year. +
 +
Naturally, publicly maintained schools have to provide by law for the physical education of the pupils, and sometimes these facilities are also extended to the whole community for use out of school hours. +
 +
I'd like now to say a word or two about water-based sports. Activities on canals, rivers, lakes and reservoirs are becoming increasingly popular and for this we must thank the British Waterways Board, which as part of its work maintains 1760 km of cruising waterways for navigation, about 960 km of other waterways and some 90 reservoirs. +
 +
In addition to the facilities which are provided by local authorities, such as the sports centres and golf courses I mentioned earlier, we mustn't forget the local voluntary clubs such as rugby, cricket, tennis, golf and so on. Some clubs are even attached to local businesses and cater for the needs of a firm's employees, and in fact some companies are actively encouraging their staff to take advantage of the facilities provided. I've even heard of employees being given time off in the middle of the working day to do a little sport, a practice which is, I believe, already quite popular in the United States. +
 +
'A healthy mind in a healthy body', as the saying goes, so perhaps this is what is in the minds of these employers. This phrase of course applies very much to the young and, as I said before, all publicly maintained schools must by law provide for the physical education of their pupils. This covers gymnastics, team games, athletics, dancing and swimming. Every school, except those solely for infants, must have a playing field, or the use of one, and most secondary schools have their own gymnasium as well. Some have other amenities such as swimming pools, sports halls and halls designed for dance and movement. Sports and recreation facilities are likewise provided at universities, some of which have their own physical education departments, and there are also so-called 'centres of sporting excellence' at universities and other colleges enabling selected young athletes to develop their talents but which also provide for their educational needs.

---

== part

Chairperson: Good evening ladies and gentlemen. It's nice to see so many of you here. Well, I'd like to introduce our two guests this evening: Mr. Andrew Frobisher, who has spent many years in Malaysia in the 1950s and 60s and knows the country very well indeed. And, on my right, Dr. Harry Benson who's an agricultural economist. +
Benson: Good evening. +
Frobisher: Good evening. +
Chairperson: Well, erm ... the purpose of this evening is to find out more about that fascinating substance, rubber, and the effects that it has on that fascinating country, Malaysia. Erm erm ... I believe erm ... er Mr. Frobisher, erm ... that Malaysia is at the same time an extremely rich and rather poor country. Erm ... how is this possible? +
Frobisher: Yes, well, that's quite true, Monica. Malaysia's population is by now over 12 million, and er per head o ... on paper the citizens are richer than those of the UK. But ... +
Benson: But of course that wealth is not so evenly distributed. In fact in 1981, it was estimated that 37% of the population were below the poverty line ... +
Frobisher: Yeah, well ... whatever that means ... and anyway shouldn't it be, er, was below the poverty line. +
Benson: Yes, of course. Sorry, Andrew. +
Frobisher: Yes, well, erm ... as I was saying, er ... much of Malaysia's wealth is based on rubber. Now, I remember my planting days ... +
Benson: Yes, yes, yes yes you're quite right there Andrew. Rubber represents about 20% of the Gross National Product and 30% of export earnings. (Er yes I ...) This puts Malaysia in a very good position internationally since rubber is an example of what we might call a 'post-industrial industry'. +
Frobisher: Well, what do you what do you mean by that? I ... +
Chairperson: Er ... excuse me ... yes, what does that mean? +
Frobisher: What is a post-industrial erm ... society? +
Benson: Most manufacturing industries are based on fossil fuels, for example, coal and oil. Now, the problem is that these will not last forever. They are finite. Sooner or late they will run out! Now, rubber is a natural product. The energy source involved in its creation is sunlight. Now sunlight, we hope, will outlast coal and oil, and best of all, sunlight is free. So, it is much cheaper to produce natural rubber which as we all know comes from trees, than to use up all those fossil fuels, both as fuels and as raw materials, in making synthetic rubber in factories. Rubber is one of the world's strategic products, so you can see what a good position Malaysia is in, and it would help if she could produce more ... +
Chairperson: Er ... well, what stands in the way then? +
Frobisher: Ah. Well, well it's the way they go about cultivating it. You see, I remember in my day just after ... +
Benson: Yes, most people have this image of vast estates, centrally run, but that's just not the case, even if almost a quarter of the population is involved, one way and another, with the production of rubber ... +
Frobisher: Yeah well, that's if you count the families ... +
Nenson: Oh yes, yes, yes almost 3 million people are involved, but the picture is a very fragmented one. Do you realize that there are 2 million hectares of land under cultivation for rubber in Malaysia, but that 70% of this area is divided amongst small-holders — half a million of them — who between them produce 60% of the country's rubber? +
Frobisher: Well, there's nothing wrong with that i ... in terms of quality of life, though I remember (yes, quite right ...) just after the war there was ... +
Benson: Yes, quite right. But being a smallholder does present problems. For example, when it comes to replacing old trees — you'll know about this Andrew — and the average useful life of a rubber tree is about 30 years, (yes, yes,) this can cause financial problems for the small farmer. The problem is being tackled, however, by some very enlightened insurance schemes available to the small-holder which can give him help through the difficult years. After all, the new trees take some years to mature and start producing rubber. +
Frobisher: Yes, indeed they do. I ... I ... +
Benson: Look. I've got an overhead projection here, which I think will be useful to make the various problems and their solutions clearer to us all. +
Frobisher: Overhead projection. There wasn't anything wrong with the blackboard in my time, you know ... +
Benson: No, but this is clearer and neater and up-to-date. So, here you see a summary of the position of rubber in Malaysia's economy and here is the first problem, and the solution that has been found through these insurance schemes. +
Chairperson: Hm, yes, I see. That's really very clear. +
Benson: Now for the second and really major problem. +
Frobisher: And may I ask what that is? +
Benson: Boredom and fatigue. +
Frobisher: Boredom and fatigue? What? +
Chairperson: What do you mean by that? +
Benson: Well, as with so many societies, the young people are leaving the land for the cities, leaving no one behind to carry on their parents' business. The root cause seems to be simply, boredom. Rubber is just not that entertaining a product to be involved with. It is labour-intensive in the extreme. Each tree on a plantation has to be tapped, by hand, every other day. +
Chairperson: Tapped? +
Benson: Yes. +
Forbisher: Yes, well, we ... +
Benson: Yes. The trunk is cut and the latex that comes out is collected in a cup. This is collected on the next day. 400 trees per day is the average figure per worker, which means 800 trees under the care of each worker, ten hours a day. Now, as I said previously, the main problem is that of the boredom. The work is not only hard, it is also mind-blowingly tedious.

---

== part

Frobisher: So, ha ... have you got any suggestions to make things more interesting for them? +
Benson: Well, not so much me, but the Malaysians are doing some very good work in this field. One idea is to make the work on the plantations more varied, and profitable, by introducing other products which are compatible with continuing to grow rubber trees. +
Chairperson: Yes for example? +
Benson: Well, the most promising line seems to be to encourage small-holders to raise livestock which can live amongst the trees. +
Frobisher: Yes, yes, I, I hear they've started trying raising chickens and turkeys. +
Benson: Yes, yes, indeed. I have another OHP at this point. +
Frobisher: Erm ... OHP? +
Benson: Overhead projection ... +
Frobisher: Ah. +
Benson: Anyway, you can see here the different types of animals that have been tried. At first sight, chickens seemed ideal. After all, they did originate as jungle birds. However, hmm excuse me, so far the profits on chickens have proved disappointing. The turkey seemed an excellent choice, since it could live amongst the tress living very well off the seeds of the rubber trees, which lie scattered all over the forest floors and are put to no other use ... +
Frobisher: Yes, yes ... but, but the turkey, it's hardly an established part of the Malaysian diet! +
Benson: Exactly! So far the most successful candidate has been the sheep. +
Frobisher: Sheep? +
Benson: Now ... Sheep. Sheep will eat the weeds, which will save the cultivator money and work, and they are a source of meat which is acceptable both to Hindus and Muslims. +
Frobisher: Yes, well, that's most important in multicultural Malaysia. +
Benson: Yes, yes, and of course they can also be used for their milk, their wool and their skins. +
Frobisher: Yes, of course ... Mmm. +
Benson: And now, as you can see on my OHP ... +
Chairperson: Well, erm ... thank you both very very much to both our guests ... +
 +
Well, what lies ahead for Malaysia? Can her researchers and scientists continue to find ways of increasing the rubber yield? Can the labor-intensive and tedious life of the rubber plantation be made interesting and varied enough to capture the young people's interest and stop the migration to the cities? Well, I'm sure we've all enjoyed and learned a lot from huh what both our guests have had to say. Huh we look forward to the next meeting in the series 'Other lands, other problems' which will be on Monday next. That's at 8:15 and do please come on time. +
Frobisher: Hmm. Pushy bastard.

---

== part

Some of the Problems Facing Learners of English +
 +
Today I'd like to talk about some of the problems that students face when they follow a course of study through the medium of English — if English is not their mother tongue. The purpose is to show that we're aware of students' problems, and that by analysing them perhaps it'll be possible to suggest how some of them may be overcome. +
 +
The problems can be divided into three broad categories: psychological, cultural and linguistic. The first two categories mainly concern those who come to study in Britain. I'll comment only briefly on these first two and then spend most of the time looking at linguistic difficulties which apply to everyone wherever they are learning English. Some of the common psychological problems really involve fear of the unknown: for example, whether one's academic studies will be too difficult, whether one will fail the examinations, etc. All students share these apprehensions. It's probably best for a student not to look too far ahead but to concentrate day-by-day on increasing his knowledge and developing his ability. The overseas student in Britain may also suffer from separation from his family and possible homesickness; enjoyment of his activities in Britain and the passage of time are the only real help here. +
 +
Looking now at the cultural problems, we can see that some of them are of a very practical nature, e.g. arranging satisfactory accommodation: getting used to British money (or the lack of it!). British food and weather (neither is always bad!). Some of the cultural difficulties are less easy to define: they are bound up with the whole range of alien customs, habits and traditions — in other words, the British way of life. Such difficulties include: settling into a strange environment and a new academic routine; learning a new set of social habits, ranging from the times of meals to the meanings of gestures; expressing appropriate greetings; understanding a different kind of humour; and learning how to make friends. Being open-minded and adaptable is the best approach to some of the difficulties listed here. +
 +
The largest category is probably linguistic. Let's look at this in some detail. +
 +
Most students will have learnt English at school, but if they've already been to college or university in their own countries they'll have studied mostly in their own language except, perhaps, for reading some textbooks and journals in English. In other words, they'll have had little everyday opportunity to practise using English. +
 +
When foreign learners first have the opportunity to speak to an English-speaking person they may have a shock: they often have great difficulty in understanding! There are a number of reasons for this. I'll just mention three of them. +
 +
Firstly, it seems to students that English people speak very quickly. Secondly, they speak with a variety of accents. Thirdly, different styles of speech are used in different situations, e.g. everyday spoken English, which is colloquial and idiomatic, is different from the English used for academic purposes. For all of these reasons students will have difficulty, mainly because they lack practice in listening to English people speaking English. Don't forget, by the way, that if students have difficulty in understanding English-speaking people, these people may also have difficulty in understanding the students! +
 +
What can a student do then to overcome these difficulties? Well, obviously, he can benefit from attending English classes and if a language laboratory is available use it as much as possible. He should also listen to programmes in English on the radio and TV. Perhaps most important of all, he should take every available opportunity to meet and speak with native English-speaking people. He should be aware, however, that English people are, by temperament, often reserved and may be unwilling to start a conversation. Nevertheless, if he has the courage to take the initiative, however difficult it may seem to be, most English people will respond. He will need patience and perseverance! +
 +
In addition to these problems regarding listening and understanding, the student probably has difficulty in speaking English fluently. He has the ideas, he knows what to say (in his own language) but he doesn't know how to say it in English. The advice here will seem difficult to follow but it's necessary. Firstly, he must simplify his language so that he can express himself reasonably clearly: for example, short sentences will be better than long ones. Secondly, he must try to think in English, not translate from his mother tongue. This'll only begin to take place when his use of English becomes automatic: using a language laboratory and listening to as much English as possible will help. In general, he should practise speaking as much as possible. He should also notice the kind of English, and its structure, that educated people use, and try to imitate it.


---
