
= step 2 - Lesson 23
:toc:
:sectnums:

---



Lesson 23 +

== part

Interviewer: Hello. My name's Hudson. Dick Hudson. +
Applicant: I'm Pamela Gable. +
Interviewer: Well, take a seat, please. Miss Gable — it is Miss, isn't it? Thought so. Well, let me just check that I've got these particulars right. Your surname is Gable, spelt G-A-B-L-E, and your first names are Pamela Ann ... Fine. You live at 147 Collington Road, Croydon ... your telephone number is 246 8008 ... you were born on July 8th, 1965, and ... that's about it ... OK? Fine ... Let's see ... what are you working with at the moment? +
Applicant: I'm the personal assistant to the manager of a modelling agency. +
Interviewer: Oh, really? And what does that involve? +
Applicant: A bit of everything, really. I have to keep the accounts, write a few letters, answer the telephone, look after bookings and engagements and that sort of thing. +
Interviewer: You work with people a lot, do you? +
Applicant: Oh yes. I have to look after all the models who work for us, you know, keep them happy, lend an understanding ear to their heartaches, you know. +
Interviewer: Have you ever done anything to do with hotels or conferences — hotel management, for instance? +
Applicant: No, not really. I did work for a short time as a courier for a tour operator, taking foreigners on guided tours of London. Perhaps that's the sort of thing you mean? +
Interviewer: Yes, I think it is. Do you speak any languages? +
Applicant: Yes, I do. I speak French and Italian — you see, I spent several years abroad when I was younger. +
Interviewer: Oh, did you? That's very interesting. And what about any exams you've taken? +
Applicant: Well, I left school at 16. You know, there didn't seem to be any point in staying on somehow; I was sure I could learn much more by getting a job and a bit of experience and independence. +
Interviewer: So you have no formal qualifications at all? I see ... Well, I don't suppose it matters. +
Applicant: Um ... I was wondering if perhaps you could tell me a bit more about the job? You know, it said in the ad that you wanted a go ahead girl with car and imagination, but that's not very much to go on. +
Interviewer: No, it isn't. Well, we run conferences, and your job as conference coordinator would be, well, much the same as the one you have now, I suppose. Meeting people, transporting them from one place to another, making sure they're comfortable, a bit of telephoning, and so on. +
Applicant: It sounds like just the sort of thing I want to do. +
Interviewer: There is the question of salary, of course. +
Applicant: Well, my present salary is 8,000 pounds, so I couldn't accept any less than that. Especially if I have to use my car. +
Interviewer: Ah! We have something like 7,500 in mind, plus of course a generous allowance for the car. But look, if I were you, I'd take some time to think about this. Perhaps you'd care to have a quick look round the office here, see if you like the look of the people who work here. +
Applicant: What do you think I should do then ...?

---

== part


Ann: When did you discover that you had this talent for hypnosis, Dr. Parker? +
Dr. Parker: When I was a final year medical student, actually. I'd been reading a lot about it and decided to try it myself on a few friends, you know — using certain well-tried techniques. +
Ann: And you were successful. +
Dr. Parker: Well, yes. I was amazed at how quickly I was able to do it. +
Ann: Could you tell me more about these techniques? +
Dr. Parker: Certainly. My method has changed very little since I started. To begin with, I get the subject to lie comfortably on a sofa, which helps to relax the body. You see, in order to reach a person's mind, you have to make him forget his body as much as possible. Then I tell him to concentrate on my voice. Some experts claim that the sound of the voice is one of the most powerful tools in hypnosis. +
Ann: Do you have an assistant with you? +
Dr. Parker: Yes, but only as a secretary. He always sits well in the background, taking notes and looking after the recording equipment. Then I tell the subject not to think about what I'm saying but just to accept it. +
Ann: Don't you use a swinging watch or flashing lights? +
Dr. Parker: No. At first I used to rely on the ticking of a clock — some say that boring, repetitive sounds help — but now I simply get my patient to stare at some object in the room. At this point I suggest that he's feeling sleepy and that his body's becoming so relaxed that he can hardly feel it. +
Ann: Be careful, Dr. Parker, I'm beginning to feel very drowsy myself. +
Dr. Parker: Don't worry. I won't make you do anything silly, I promise. +
Ann: What you're saying, then, is that you want to control your patient's mind, and that to do this you have first to take care of the body. +
Dr. Parker: Yes. You see, the aim of the session is to make the patient remember in great detail an experience which has caused him a lot of pain and suffering, and by doing that to help him to face his problems. +
Ann: I've heard a person's memory is far more powerful under hypnosis. +
Dr. Parker: Indeed it is. Some of the things that patients are able to remember are just incredible. +
Ann: Would you mind giving me an example? +
Dr. Parker: Not at all. During a session, it's standard procedure to take a patient back in time slowly, pausing at certain times in his life and asking a few questions. +
Ann: To, sort of, set the scene before you go deeper. Is that what you mean? +
Dr. Parker: That's it exactly. Well, once, I took a thirty-five-year-old lady back to the age of eight — in fact, I told her it was her eighth birthday and I asked her what day it was. I later checked a calendar for that year and she was right — it was a Tuesday. She even told me who was at her party, their names, what they were wearing and about the presents she received. I mean, can you remember even your last birthday? +
Ann: I couldn't even tell you what day my birthday fell on this year. +
Dr. Parker: Precisely. And when I asked her to write down her address at that time, the handwriting was in a very immature style. I later compared it to a sample from some old school exercise books her mother had kept and it was identical. +
Ann: Dr. Parker, that's an amazing story. +
Dr. Parker: I've taken patients back to their first year and a few even further than that ... but that's another story, unless you've got plenty of time ...
 +

---

== part

These days it's hard enough to find a suitable job, let alone get as far as an interview. Dozens of people every day scour the Situations Vacant columns of the press, send off their curriculum vitae or application form, and wait hopefully to be summoned for an interview. Now this, apparently, is where a lot of people fall down, because of their inadequacy at completing their application forms, according to Judith Davidson, author of Getting a Job, a book which has recently come on the market. This book, as the title suggests, is crammed full of useful tips on how to set about finding yourself work in these difficult times. Our reporter, Christopher Shields, decided to look into this apparent inability of the British to sell themselves, and he spoke to Judith Davidson about it. +
Judith: Very often a job application or a curriculum vitae will contain basic grammatical or careless spelling mistakes, even from university graduates. Then those that do get as far as an interview become inarticulate or clumsy when they try to talk about themselves. It doesn't matter how highly qualified or brilliant you may be, if you come across as tongue-tied and gauche, your chances of getting a job are pretty small. +
Christopher: Judith Davidson lectures at a management training college for young men and women, most of whom have just graduated from university and gone there to take a crash course in management techniques. One of the hardest things is, not passing the course examinations successfully, but actually finding employment afterwards, so Judith now concentrates on helping trainees to set about doing just this. +
Judith: Some letters are dirty and untidily written, with finger marks all over them and ink blots or even coffee stains. Others arrive on lined or flowered or sometimes scented paper — none of which is likely to make a good impression on the average business-like boss. +
Christopher: This apparent inability of many people to make that initial impact with an employer by sending him an application which will stand out from the rest and persuade him you're the right one for the job prompted an enterprising young man, called Mark Ashworth, a recruitment consultant himself, to start writing job applications for other people for a fee, as a sideline. He told me he got the idea in America where it's already big business, and in the last few months alone he's written over 250 c.v.s. He feels that 80 per cent of job applications received by personnel managers are inadequate in some way. +
Mark: Many people simply can't cope with grammar and spelling and don't know what to put in, or leave out. Sometimes people condense their work experience so much that a future employer doesn't know enough about them. Then, on the other hand, some people go too far the other way. To give you an example, one c.v. I once received in my recruiting role was getting on for thirty pages long. +
Christopher: Mark has an initial interview with all his clients in which he tries to make them think about their motivation and why they've done certain things in the past. He can often exploit these experiences in the c.v. he writes for them, and show that they have been valuable preparation for the job now sought. He also believes that well-prepared job history and a good letter of application are absolutely essential. +
Mark: Among the most important aspects of applications are spelling, correct grammar, content and layout. A new boss will probably also be impressed with a good reference or a letter of commendation written by a former employer. The type of c.v. I aim to produce depends largely on the kind of job being applied for. They don't always have to be slick or highly sophisticated, but in certain cases this does help. +
Christopher: Judith Davidson thought very much along the same lines as Mark. In her opinion, one of the most important aspects of job applications was that they should be easy to read ... +
Judith: ... Many applicants send in letters and forms which are virtually unreadable. The essence of handwritten application is that they should be neat, legible and the spelling should be accurate. I stress handwritten because most employers want a sample of their future employee's writing. Many believe this gives some indication of the character of the person who wrote it. Some people forget vital things like putting their own address or the date. Others fail to do what's required of them by a job advertisement. +
Christopher: Judith believes that job seekers should always send an accompanying letter along with their application form stating clearly why their qualifications make them suitable for the vacancy. +
Judith: Personal details have no place in letters of application. I well remember hearing about one such letter which stated, quite bluntly, I need more money to pay for my flat. No boss would be impressed by such directness. +
Christopher: She added that the art of applying for jobs successfully was having to be learnt by more and more people these days, with the current unemployment situation. With as many as two or three hundred people applying for one vacancy, a boss would want to see only a small fraction of that number in person for an interview, so your application had to really outshine all the others to get you on the short list.

---

== part

==== 1. (Literature) +

We may note in passing that, although Dr Johnson's friend and biographer, Boswell, was a Scotsman, Johnson despised, or pretended to despise, Scotsmen in general. He once said that the best thing a Scotsman ever saw was the high road to England. In his famous dictionary, Johnson defined oats as 'a grain which in England is generally given to horses, but in Scotland supports the people'. He did not condemn all Scotsmen, however. Once he commented on a distinguished nobleman who had been born in Scotland but educated in England, saying that much could be made of a Scotsman — if he was caught young. +


==== 2. (Geography: American Indians) +

The first important point to note about the American Indians is that, in spite of their name, they are in no way related to the peoples of India. This confusion arose, as you probably know, because of a mistake on the part of Christopher Columbus. When he landed in America he thought that he had in fact discovered India. This mistake has been perpetrated, that is kept alive, ever since by the name he gave them. If they are related to any Asian group it is to the Mongols of Northern Asia. Many experts believe that the ancestors of the present American Indians emigrated from Northern Asia across the Bering Strait between 10,000 and 20,000 years ago. +


==== 3. (Science: methods of scientific discovery) +

A good illustration of how scientific discoveries may be made accidentally is the discovery of penicillin. Alexander Fleming was a bacteriologist who for fifteen years had tried to solve the problem of how to get rid of the disease — carrying germs or microbes in the human body without causing any dangerous side-effects. Fleming was an untidy worker and often had innumerable small dishes containing microbes all around his laboratory. One day, one of the dishes was contaminated with a mould, due to the window having been left open. Fleming noticed that the mould had killed off the microbes, and it was from similar moulds that the miracle drug penicillin was finally developed. Of course, only a brilliant scientist like Fleming would have been able to take advantage of this stroke of luck, but the fact remains that the solution to his problem was given to him, literally, on a plate. +


==== 4. (Psychology: memory) +

What I want to emphasize to you is this: that people remember things which make sense to them or which they can connect with something they already know. Students who try to memorize what they cannot understand are almost certainly wasting their time.


---
