= 0728
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 728: Describing One’s Skill Level.
This is English as a Second Language Podcast episode 728. Can you believe it?! I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Why? Well, we want you to become a member of ESL Podcast, my friend, and be able to download the Learning Guide for this episode, which will make your life much easier and happier.
This episode is a dialogue between Elaine and Tony, using vocabulary to describe how good you are at doing something. Let’s get started.
[start of dialogue]
Elaine: Welcome to your first day as an intern in our company office. Let me show you around. This is the main office area with a cubicle for each employee. Are you pretty good with computers?
Tony: Actually, my computer knowledge is pretty basic. The only thing I’m adept at is videogames. I’m not up to snuff on actually doing work on one.
Elaine: Okay, well you should be proficient by the end of your internship. Over there is where we keep the photocopier and fax machine. Have you used them before?
Tony: I’m an expert on the copier. I can use it with one hand tied behind my back. I’m particularly good at photocopying body parts.
Elaine: Uh, great.
Tony: But the fax…I’ve only used one once and I never quite mastered it.
Elaine: I’m sure you’ll get the hang of it pretty quickly. And this is the break room. You have your standard refrigerator and vending machines.
Tony: Hey, I’m really good with vending machines. That’s one machine I know inside and out.
Elaine: How could I have guessed that the one thing you really excel at is working the vending machine?
[end of dialogue]
Elaine says to Tony, “Welcome to your first day as an intern in our company office.” An “intern” (intern) is a person, usually a student, who works in an organization for a short period of time – a month, two months, maybe a year – to learn how to do something and to prepare for their future doing that kind of job. Lots of organizations have interns; they are young students, either still in college or just graduated from college, that perform different jobs. Sometimes they are paid, sometimes they are volunteer; you don’t get paid but you do get experience. I think I need an intern here at the Center for Educational Development. You know, someone to bring my coffee in the morning – or my tea, as the case may be. Well, Elaine is welcoming – is saying hello to Tony, who is an intern. She says, “Let me show you around.” Let me give you a tour; let me tell you where everything is. She then says, “This is the main office area with a cubicle for each employee.” A “cubicle” (cubicle) is a small work area within a larger office space. Typically, it has a desk, a computer, a telephone. There are walls around it, but the walls don’t go all the way up to the ceiling. That’s a cubicle.
Elaine then asks Tony, “Are you pretty good with computers?” Tony says, “Actually, my computer knowledge is pretty basic.” When we say our knowledge about something is “basic,” we mean that it isn’t very much; it’s the minimum that you need to know; you could be much, much better; it’s very low, very beginning level. “Basic” has a number of different meanings in English however; take a look at our Learning Guide for some more of those. Tony says, “The only thing I’m adept at is videogames.” “To be adept (adept) at (something)” means to be able to do something very well, to be very good at doing or using something. “He’s adept at certain programming languages,” Java and PHP – I don’t know – something you’re good at. Tony says he’s adept at videogames, but “I’m not up to snuff on actually doing work on one.” “To be up to snuff” (snuff) means to perform at a satisfactory level, to meet someone’s expectations, to be good enough to do something. I am up to snuff on recording podcasts; I’m able to do it. I can’t do a lot of other things, but I am up to snuff on the recording part anyway.
Elaine says, “Okay, well you should be proficient by the end of your internship.” Your “internship” is the time that you are an intern. “To be proficient” (proficient) means to be good at something, to be very good at it. You might be an expert or you might just have a lot of knowledge, but you are very good at what you do. We often talk about proficiency in languages, being able to speak them and understand them and so forth. Elaine says, “Over there is where we keep (where we have) the photocopier and the fax machine.” A “photocopier,” more commonly called a “copying machine” or just a “copier,” is a machine that produces an image on a piece of paper from what you give it. So it sort of takes the image and reproduces it onto a piece of paper; that’s a copying machine. A “fax machine” is a machine that uses phone lines to send images of paper to another machine – another fax or fax machine. Fax machines are becoming less and less common now, with the Internet and email.
Tony says, “I’m an expert on the copier.” “To be an expert” means to be someone who knows almost everything about something. You could be an expert on ancient Greek art or an expert on how to fix your car. Tony is an expert on copying machines. He says, “I can use it with one hand tied behind my back.” The expression “to have one hand tied behind your back” means you can do something very easily, without any difficulty. To tie your hand would be to take a piece of rope or string so that you couldn’t move your hand. If you tied it behind your back, you could only do something with one hand – with one arm. The idea is that you’re so good you don’t need both arms – both hands to do it. Tony, again, is making a little bit of a joke here. He says, “I’m particularly good at (I’m very good at) photocopying body parts.” A “body part” is a part of your body: your arm, your leg, your hand, and so forth. Sometimes in offices as a joke people will take pictures of their head or other parts of their body and give them to someone as a joke. So Tony is an intern who’s making a joke. Elaine is not really happy with this joke; she says, “Uh, great.” She doesn’t really mean “great,” she says it in a way that makes us understand that she doesn’t really think the joke is very funny.
Tony says, “But the fax…I’ve only used one once and I never quite mastered it.” “To master (something)” is to become very good at something; it’s to become an expert. Elaine says, “I’m sure you’ll get the hang of it pretty quickly.” “To get the hang (hang) of (something)” means to learn how to do something, to learn how to do something correctly. She says, “this is the break room.” A “break room” is a room in an office where you can go to eat, to relax. Many employees get a break – a 15 minute break every morning and every afternoon in addition to their, say, 30 minute lunch break, and this is where you can go in the building. It usually has chairs and tables, sometimes machines that sell things: candy and soda, coffee, etc. Elaine says, “You have your standard refrigerator (your normal refrigerator) and vending machines.” We just explained a “vending machine,” it’s a machine that you put money into and it gives you food or drink or other things.
Tony says, “Hey, I’m really good with vending machines.” I know how to use them very well; again, another joke. He says, “That’s one machine I know inside and out.” “To know (something) inside and out” means to know it very well, to have knowledge of all the different parts of something. Elaine says, “How could I have guessed that the one thing you really excel at is working the vending machine?” The first part of this question, “how could I have guessed,” means it should have been obvious. It’s a kind of a strange expression, but what she’s saying is it is obvious, knowing you – or knowing what I do about you, that in this case you really excel at working with the vending machine. “To excel” (excel), as a verb, means to do something very well, to become a master at doing something. We have the adjective “excellent,” which is related. Elaine says that Tony really excels at working the vending machine, meaning using the vending machine.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Elaine: Welcome to your first day as an intern in our company office. Let me show you around. This is the main office area with a cubicle for each employee. Are you pretty good with computers?
Tony: Actually, my computer knowledge is pretty basic. The only thing I’m adept at is videogames. I’m not up to snuff on actually doing work on one.
Elaine: Okay, well you should be proficient by the end of your internship. Over there is where we keep the photocopier and fax machine. Have you used them before?
Tony: I’m an expert on the copier. I can use it with one hand tied behind my back. I’m particularly good at photocopying body parts.
Elaine: Uh, great.
Tony: But the fax…I’ve only used one once and I never quite mastered it.
Elaine: I’m sure you’ll get the hang of it pretty quickly. And this is the break room. We have your standard refrigerator and vending machines.
Tony: Hey, I’m really good with vending machines. That’s one machine I know inside and out.
Elaine: How could I have guessed that the one thing you really excel at is working the vending machine?
[end of dialogue]
We want to thank our master scriptwriter, a true expert, Dr. Lucy Tse, for this script.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
intern – a person, usually who is still a student, who works in an organization for a short period of time to learn how to do something and prepare for a future career
* Last summer, Jezra was a finance intern on Wall Street and learned a lot about the stock market.
cubicle – a small work area within a larger office space, with a desk, computer, and telephone surrounded by four short walls that do not reach up to the ceiling
* I hate making phone calls from my cubicle, because my co-workers can hear everything I say.
basic – the minimum or standard type of something, without anything additional or impressive
* We were going to buy the basic model of this car, but then we started adding features like leather seats and a fancy stereo.
adept at – very good at doing or using something
* To improve our website, we need to hire someone who is adept at Java.
up to snuff – meeting the standards or expectations for something; at a satisfactory level
* Make sure your essay is up to snuff or the teacher will give you a failing grade.
proficient – very good at doing something; an expert; with an advanced level
* How many years did you have to work before you became proficient in making fancy wedding cakes?
photocopier – a machine that makes many copies of the text or images that appear on a piece of paper
* The photocopier was working fine yesterday, but now that I need to make copies of the agenda for today’s meeting, it won’t even turn on!
fax machine – a machine that uses phone lines to send the text or images on a piece of paper to another fax machine in a different location, where it is printed out onto a piece of paper
* I don’t have a fax machine in my home office. Can I scan the document and email it to you instead?
expert – someone who has a lot of knowledge on a topic; someone who knows almost everything about something
* Beth is an expert in ancient Greek and Roman art.
one hand tied behind (one’s) back – able to do something very easily, without any difficulty
* Daryl has been building homes for more than 20 years, and he can almost do it with one hand tied behind his back!
body part – one section of one’s body, such as an arm, leg, hand, or foot
* Tae-young chose to get a tattoo on his back, rather than a more visible body part.
to master – to become very good at doing something so that one doesn’t have any doubts about it
* It can take many years of practice to master the violin.
to get the hang of – to learn how to do something; to become familiar enough with something to use or do it correctly
* Cooper is a good skier, but it took him a while to get the hang of snowboarding.
break room – a room in an office building where workers go to eat and/or rest for short periods of time during the day
* I wish it were quieter in the break room so we could take a quick nap before going back to work.
vending machine – a large machine that people put coins into to receive small packages of food or drinks
* The sodas in this vending machine cost $1.25 each!
to know inside and out – to know something very well; to have knowledge about all parts or aspects of something
* Hinton grew up in New York City, so he knows the city inside and out.
to excel – to do something very well; to be a master at doing something
* Wei excelled in her graduate courses in marketing.
Comprehension Questions
1. Which of these machines accepts money?
a) A photocopier.
b) A fax machine.
c) A vending machine.
2. What is the first thing Tony shows Elaine on the tour?
a) The desks where each employee works.
b) The mailboxes where each employee receives documents.
c) The cots where employees can take naps on breaks.
Answers at bottom.
What Else Does It Mean?
basic
The word “basic,” in this podcast, means the minimum or standard type of something, without anything additional: “The basic cable package offers 20 channels, but you can pay extra to receive premium movie channels.” The “basics” refers to the most fundamental or important principles of something: “She learned the basics of music theory as a child, but she has forgotten a lot of it since then.” The word “basically” is used when one is summarizing something or putting something in simpler terms: “A lot of ingredients go into making a good soup, but basically, you need meat and/or vegetables that are fresh.” Finally, the phrase “basic training” refers to the period of time when people enter the military and receive intense instruction to prepare them for their work: “Basic training is really difficult, but if you can make it through the first few weeks, you’ll be fine.”
master
In this podcast, the verb “to master” means to become very good at doing something so that one doesn’t have any doubts about it: “If you want to master the art of watercolor painting, you’ll have to buy better paints and paintbrushes.” The verb “to master” can also mean to overcome something, or to succeed despite a challenge or difficulty: “Once Hal learned to master his impatience, he became a very successful leader.” As a noun, a “master” is a person who is in control of something or is an expert in something: “He is a master champion in golf.” A “master” can also refer to the original version of something: “Please don’t give away the master copy. Make copies of it instead.”
Culture Note
The Internship Experience
Students and “recent graduates” (people who recently earned a diploma or finished a course of study) can participate in internships to “obtain” (get) valuable job experience and “network” (meet; make connections) with people in their “chosen industry” (the field one wants to work in). Many internships are “unpaid” (the intern does not receive any money), and even the “paid” internships are usually not very well paying. Internships can also be “for credit” (giving the student academic credits that can be used to earn a degree, like a class) or “not for credit,” and interns usually have to write a report describing their experience in for-credit internships.
Internship experiences “vary widely” (are very different) depending on the industry and the organization. Some interns are disappointed when their work is primarily photocopying or getting coffee for the regular employees. But other interns become an “integral” (important; necessary) part of the organization. The best internships are generally opportunities to work on a specific project that benefits the organization, but that regular employees do not have enough time to complete on their own. Interns working on specific projects have “autonomy” (the ability to make one’s own decisions), but can also “turn to” (ask for help from) employees when they need guidance or additional information.
Many businesses offer internships as a way to “vet” (review the qualifications of) potential employees. If a supervisor is pleased with an intern, he or she may encourage the intern to return to the organization after graduation by making an “attractive” (desirable; with nice benefits) job offer. The intern’s familiarity with the organization and the “work culture” (how people interact within the organization), makes the transition into the new job easier, and the company knows how well qualified the new employee is, because it has already worked with him or her as an intern.
Comprehension Answers
1 - c
2 - a