= 0733
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 733: Voting in an Election.
This is English as a Second Language Podcast episode 733. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You can go there and download a Learning Guide for this episode. You can also get one of our Premium Business or Daily English courses on our ESL Podcast Store.
This episode is a dialogue between Khaled and Bernice. They’re talking about voting in an election and use a lot of vocabulary we might use to describe democratic elections. Let’s get started.
[start of dialogue]
Khaled: Are you going to the polling place or are you voting by absentee ballot again?
Bernice: I always vote with an absentee ballot so I can vote in the comfort of my own home and in my own time. In fact, I’ve already mailed in my ballot.
Khaled: Good for you. Which candidate did you vote for in the governor’s race?
Bernice: I didn’t vote for either of the bozos that are running. I voted for a write-in candidate.
Khaled: A write-in candidate? There isn’t a snowball’s chance in hell that a write-in candidate is going to win this election.
Bernice: That may be so, but I have to vote with my conscience, and I can’t bring myself to vote for either of those people. Have you voted?
Khaled: Not yet. I’m going to vote at the polls on Election Day. I want more time to think about whom to vote for and to read up on the ballot measures. There are a lot of them this time.
Bernice: Yeah, but the governor’s race is the only thing I care about. I can’t stand the thought of having either of those bozos as the next governor.
Khaled: Just out of curiosity, who did you write in as a candidate?
Bernice: You.
Khaled: Me?! You’re crazy. I don’t want to be governor.
Bernice: It was either you or me, and I’d rather not be a candidate and have to be in the company of those bozos.
[end of dialogue]
Our dialogue begins with Khaled saying to Bernice, “Are you going to the polling place or are you voting by absentee ballot again?” A “polling place” is a place usually in a school or a library – although here in California it could be in someone’s garage or living room, a place where you go to fill out a piece of paper or enter information in a computer to vote in an election. So, a polling place is a place where you go and vote. Where I’m from, in Minnesota, when I was growing up polling places were always in schools or the basement of churches or other buildings – community or public buildings. Here in California, for some reason, a lot of the polling places are in homes. I think part of the reason is for that safety reasons the schools don’t want all of these adults coming into the school, people they don’t know.
So Khaled is asking Bernice if she is going to go to her polling place or if she is going to “vote,” she’s going to indicate who she wants to be elected, by absentee ballot. “To be absent” (absent) means you are not there, it’s the opposite of “present.” “Absentee” refers to someone who isn’t there. It can be used as an adjective, as it is here, to describe something or someone who isn’t physically present. A “ballot” (ballot) is the piece of paper, traditionally, that you mark on that indicates who you want to win the election, and you give that ballot to someone and then they count the ballots. So, an “absentee ballot” is this piece of paper, but you aren’t actually there at the polling place; you mail the ballot in. So here in the United States, in many states you can vote by mail. I always vote by mail. They send me the ballot, I fill it out, I put a stamp on it, I mail it back. I don’t have to go anywhere on the day that the election is officially, which is what we would call “Election Day.” Pretty clever, huh?
Bernice says, “I always vote with an absentee ballot so I can vote in the comfort of my own home,” meaning I can be comfortable, I don’t have to go out anywhere. She also likes voting by absentee ballot so she can vote “in her own time,” meaning when she wants to do something, when something is convenient to her. Bernice says, “In fact, I’ve already mailed in my ballot.”
Khaled says, “Good for you. Which candidate did you vote for in the governor’s race?” A “candidate” is a person who wants to be elected to a position. The “governor” is the leader or head of the state. Our governor used to be Arnold Schwarzenegger, now it’s a man by the name of Jerry Brown here in California, as I am recording this in 2011. Khaled wants to know who Bernice voted for in the governor’s race. We use the word “race” (race) here to mean an election. It can also mean a competition between two people. “Race” has a number of other meanings also in English, and those can be found in our Learning Guide.
Bernice says, “I didn’t vote for either of the bozos that are running.” A “bozo” (bozo) is here meant to mean a clown, more generally an unintelligent person who is not doing his or her job very well, who does a very poor job at something. So, she’s describing the candidates as bozos. It’s kind of like saying they’re idiots. “I voted for a write-in candidate,” Bernice says. There are certain rules for being elected and being on the ballot in the United States. However sometimes, people don’t want to vote for anyone who is officially on the ballot, and so they will write someone’s name in. This is perfectly legal. In some states you have to register your name if you want to be a write-in candidate, even though your name is not printed on the ballot. Here in California, you can write in someone’s name, someone who is not officially on the ballot. These people almost never win, but some people like to do it as a protest to say, “I don’t like any of you people.” I have often written in candidates here for elections!
Khaled says, “A write-in candidate? There isn’t a snowball’s chance in hell that a write-in candidate is going to win this election.” The phrase “a snowball’s chance in hell” means absolutely no chance, no possibility, or simply impossible. It’s impossible for a write-in candidate to win this election, that’s what Khaled is saying. A “snowball” is cold; it’s made from basically frozen water, or water crystals. “Hell” in the Christian religion is where you go if you’re a bad person after you die, and traditionally it’s been thought of as a very hot place. So, if you put a snowball in a hot place, of course the snowball will melt; it will disappear; it will become water and no longer be a snowball. So, a snowball’s chance in hell means no chance, because, of course, it would not be able to survive.
Khaled says, “There isn’t a snowball’s chance in hell that a write-in candidate is going to win this election,” this race, this competition. Bernice says, “That may be so, but I have to vote with my conscience, and I can’t bring myself to vote for either of those people.” Your “conscience” is your sense of right and wrong; what is the right thing to do, the correct thing to do, the ethical thing to do, and what is the wrong thing to do. Bernice says, “I can’t bring myself to vote for either of those people.” This expression, “to not be able to bring yourself to do (something)” means that you can’t do it because you think it is wrong, you can’t even force yourself to do it because you think it is such a bad idea. We might say, “Oh, she looks so happy. I can’t bring myself to tell her any bad news today.” I just can’t do it.
Then Bernice asks Khaled, “Have you voted?” and he says, “Not yet. I’m going to vote at the polls on Election Day.” He’s going to go to the polling place and vote on the day of the election, Election Day. He says, “I want more time to think about whom to vote for and to read up on the ballot measures.” “To read up on (something)” means to learn about something by reading about it: reading information, reading books, websites, and so forth. A “ballot measure” is a proposal for a new law that the people vote on directly. Normally you vote for people, and those people – those representatives vote on the laws for your state or your city or your country. However, sometimes in American elections the people vote directly on a law. It might be a law to allow gambling or it might be a law to increase taxes. Just about any kind of law can be voted on directly by the people in some states; not all states have this system. Khaled says, “There are a lot of them this time,” a lot of ballot measures. Here in California, we always have many, many ballot measures; I think at least 5 or 10 every election. These are laws that we are being asked to vote on directly.
Bernice says, “Yeah, but the governor’s race is the only thing I care about.” She only cares about who wins the election for governor. She says, “I can’t stand the thought of having either of those bozos as the next governor.” Bernice says, “I can’t stand.” This means I cannot tolerate, I cannot find acceptable. “To be able to stand (something)” is to be able to tolerate it, often because it is difficult. We say, “I can’t stand it,” meaning I can no longer do this, I can no longer be in this situation. You might say, “I can’t stand the hot weather.” “I hate it” is another way of saying that.
Khaled says, “Just out of curiosity (just because I want to know), who did you write in as a candidate?” Remember, Bernice was going to write the name of someone in and not vote for the people whose names were on the ballot. Bernice says, “You.” Khaled says, “Me?! You’re crazy. I don’t want to be governor.” Bernice responds, “It was either you or me, and I’d rather not be a candidate and have to be in the company of those bozos.” “To be in the company of (someone)” means to spend time with someone, or to be in the same place as someone. Bernice really doesn’t like the candidates; she calls them “bozos” no less than three times!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Khaled: Are you going to the polling place or are you voting by absentee ballot again?
Bernice: I always vote with an absentee ballot so I can vote in the comfort of my own home and in my own time. In fact, I’ve already mailed in my ballot.
Khaled: Good for you. Which candidate did you vote for in the governor’s race?
Bernice: I didn’t vote for either of the bozos that are running. I voted for a write-in candidate.
Khaled: A write-in candidate? There isn’t a snowball’s chance in hell that a write-in candidate is going to win this election.
Bernice: That may be so, but I have to vote with my conscience, and I can’t bring myself to vote for either of those people. Have you voted?
Khaled: Not yet. I’m going to vote at the polls on Election Day. I want more time to think about whom to vote for and to read up on the ballot measures. There are a lot of them this time.
Bernice: Yeah, but the governor’s race is the only thing I care about. I can’t stand the thought of having either of those bozos as the next governor.
Khaled: Just out of curiosity, who did you write in as a candidate?
Bernice: You.
Khaled: Me?! You’re crazy. I don’t want to be governor.
Bernice: It was either you or me, and I’d rather not be a candidate and have to be in the company of those bozos.
[end of dialogue]
It’s always a pleasure to be in the company of our scriptwriter, the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
polling place – a building (often a school or library) where people can mark a piece of paper or touch a computer screen to vote in elections
* To vote, we’ll need to go the polling place, which is at the public library this year.
to vote – for many people to indicate who should have a government job or whether or not a particular law should be created
* This week, the Senate is going to vote on the new healthcare law.
absentee ballot – a way of voting by mail, so that the voters marks his or her choices on a piece of paper and then mails it to the government office where the votes are counted
* Americans living overseas have to vote by absentee ballot.
in my own time – when one wants to do something; when something is convenient and fits with one’s schedule
* - When do you think you’ll finish your novel?
* - Don’t worry. I’ll finish it in my own time.
candidate – a person who wants to be elected by voters for a particular government job
* How many people have expressed an interest in being a candidate for governor?
race – election; a competition between two or more people who want to be elected by voters for a particular government job
* So far, Melanie seems to be winning the race, but everything could change in the next few weeks before the election.
bozo – clown; an unintelligent, incompetent person who is not able to do his or her job well and who does not meet one’s expectations
* Is Janice really going to marry that bozo? She could do so much better.
write-in candidate – a name that is written down by a voter when he or she does not want to vote for the people who are listed for a particular government job
* Sometimes people put down “Mickey Mouse” or “Donald Duck” as a write-in candidate when they don’t think the elections are important.
a snowball’s chance in hell – something that is impossible or very unlikely and will not happen; something that cannot succeed
* We have a snowball’s chance in hell the client will want to do business with us again after what happened last week.
election – the process through which people vote for who should have a government job or whether or not a particular law should be created
* When will the next presidential election be?
conscience – an internal feeling of right or wrong, especially about whether one’s own actions are good or bad
* Shane is always very honest, because his conscience won’t let him tell lies.
to not be able to bring (oneself) – to not be able to force oneself to do something that one should or must do, usually because one thinks it is wrong
* She looks so happy. I can’t bring myself to tell her the bad news. Will you do it for me?
Election Day – the day when people vote on who should have a government job or whether or not a particular law should be created
* On Election Day, some employers let their workers take some time off work to go and vote.
to read up on – to learn about something by reading information about it, especially printed materials like brochures
* Ali bought a travel guide to read up on Chicago before his trip.
ballot measure – a proposal for a new law or regulation that asks people to vote yes or no in an election
* If this ballot measure passes, the minimum amount of prison time for theft will increase to five years.
to not be able to stand – to not be able to tolerate something; to think that something is unacceptable
* Larry can’t stand hot weather, so he moved to Alaska.
to be in the company of – to be in the presence of; to spend time with someone; to be in the same place as someone else
* If you don’t like to be in the company of drunken people, why do you go to bars?
Comprehension Questions
1. Why does Bernice always vote with an absentee ballot?
a) Because it’s convenient.
b) Because it’s less expensive.
c) Because it’s faster.
2. Why does Khaled think a write-in candidate isn’t a good idea?
a) Because the vote counters might not be able to read the name.
b) Because there’s no way the write-in candidate can win.
c) Because voting for a write-in candidate is disrespectful.
Answers at bottom.
What Else Does It Mean?
race
The word “race,” in this podcast, means an election, or a competition between two or more people who want to be elected by voters for a particular government job: “All of today’s news stories are about the presidential race.” A “race” is normally a competition to see who can move most quickly: “Hal runs every day, but he is a slow runner so he never competes in races.” Or, “Which horse do you think will win the race?” When talking about people, the word “race” refers to a person’s ethnicity, or skin, eye, and hair color: “How would you feel if your son or daughter married someone of a different race?” Finally, a “race” can refer to a situation where two or more people are competing to do something first: “When John F. Kennedy was President, the United States became involved in a space race with the USSR.”
to read up on
In this podcast, the phrase “to read up on” means to learn about something by reading information about it, especially printed materials like brochures: “Before you go to the job interview, try to read up on the company so that you can ask intelligent questions about the position.” The phrase “to read between the lines” means to understand someone’s feelings or opinions even when they are not stated directly: “I thought she sounded happy, but her mother said that by reading between the lines she could tell her daughter was actually very sad.” The phrase “read my lips” is used when one wants to emphasize that what one is saying is true and important: “Read my lips: I won’t raise taxes.”
Culture Note
Voter Eligibility
Voter “eligibility” (determinations of who has the right to vote) is determined through a combination of “federal” (national) and state laws. Here in California, individuals must meet “the following” (listed below) five “criteria” (factors that are important for making a decision or classification) to be eligible to vote:
The individual must be a citizen of the United States. It does not matter where the individual was born, as long as he or she is a citizen.
The individual must be a “resident” of the State of California. This means that the individual must be able to prove that he or she lives in California.
The individual must be at least 18 years old by Election Day.
The individual must not be in “prison” (jail; the place people are taken to as a punishment for having broken the law) or “on parole” (allowed to leave jail under close supervision, but still being punished for having broken the law) for a “felony” (a serious, dangerous crime).
The individual must not be “found by a court” (legally declared) to be “mentally incompetent” (unable to think clearly, usually because of a mental issue or illness).
Californians who meet those five criteria can fill out a voter registration “form” (a document with many empty lines requesting information). The form requests basic information, like the new voter’s name, address, and birth date. The individual can also choose to “indicate” (show) his or her “party affiliation” (whether one generally prefers the Democratic, Republican, or another political party).
After the state “processes” (handles; deals with) the form, the new voter receives a “voter registration card” in the mail. The card shows that the individual has registered and is eligible to vote in the State of California. Most of the other states have similar requirements and a similar process for registering to vote.
Comprehension Answers
1 - a
2 - b