= 0749
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 749: Getting Standard Medical Test Results.
This is English as a Second Language Podcast episode 749. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. How are you today? Oh, just fine; thank you for asking.
You should go to our website now at eslpod.com and become a member of ESL Podcast, and when you do you can download a Learning Guide for this episode. What’s a Learning Guide? Well, it’s our little secret weapon, our little magical pill that will help you improve your English faster than ever.
This episode is a dialogue between Judith and Steven about going to the doctor and getting some results from some tests that the doctor performs on you. Sounds like fun! Let’s get started.
[start of dialogue]
Judith: I had my annual physical two weeks ago and I just got a copy of the lab results, but I can’t figure out what they mean.
Steven: Let me take a look. The results of your blood tests are good. Your cholesterol is within the normal range, your glucose levels are fine, your hormone levels are good, and your red and white blood cell counts are normal, too.
Judith: That’s good news.
Steven: You did well on your EKG stress test and your bone density scan is fine.
Judith: Really? That’s great. What about the other results?
Steven: There appears to be no problems with your Pap smear or mammogram results, either.
Judith: I’m really glad to hear that. I hate going through those exams. I’m glad I don’t have to do them more often.
Steven: Just be glad you’re not a man.
Judith: Why’s that?
Steven: If you were a man, you’d have to have a PSA…and a DRE.
Judith: A what?
Steven: You don’t want to know.
[end of dialogue]
Judith has gone to the doctor, and she gets some test results back from the doctor. She said, “I had my annual physical two weeks ago and I just got a copy of the lab results, but I can’t figure out what they mean.” The word “annual” (annual) means once per year. A “physical” is short for a physical examination; it’s usually something you have a doctor do once a year to check to make sure that you are healthy, that there are no new medical problems. Instead of “physical exam” sometimes we just say “physical”: “I need to get a physical.” That’s what the “physical” is; it’s the examination. “Physical” has other meanings in English as well, and those can be found in the wonderful Learning Guide for this episode.
Judith says that she got a copy of the lab results. “Lab” (lab) is short for laboratory; it’s the place where things are tested by scientists. And, “lab results” are the results of tests that were sent to a laboratory in order to analyze them. Steven says, “Let me take a look.” “Let me take a look” means let me look at them; let me examine them. He says, “The results of your blood tests are good.” “Blood tests” are when they take blood – red blood – out of you and they test it for certain problems or certain things. Steven says that Judith’s cholesterol is within the normal range, her glucose levels are fine, her hormone levels are good, and her red and white blood cell counts are normal, also. “Cholesterol” is a fatty substance that when it goes into your bloodstream – into your arteries – it can be dangerous. It can prevent the blood from flowing through, at least that’s my understanding. I’m not a real doctor of course; I just have a Ph.D. But, I looked it up on the Internet; I think that’s right. A “range” (range) here means a number of numbers or levels. One is a minimum, one is a maximum, between which your score or the number of your test should fall. So, we might say that, for example, if you take an intelligent quotient test – an IQ test – the average result may be 100, but anything between, I don’t know, 90 and 110 might be considered the normal range, where most people would be. So, “range” has to do with a low number, a high number, and the numbers in between. The cholesterol levels of Judith are within the normal range, meaning that she’s like most people; her cholesterol isn’t too high, it isn’t too low, it’s just right.
“Glucose” (glucose) is a type of sugar that’s found in the blood, and is used by the blood as – or the body, rather, as a source of energy. So, in measuring your glucose level, the doctor is measuring the amount of that sugar, making sure it’s not too high or too low – or too sweet. No, just kidding, not that kind of sugar. “Hormones” are substances in your body that affect a lot of different things. They affect your sexual development, they can affect lots of different parts of the way your body functions. Men and women have different kinds or different levels of different hormones, and so you need to make sure you, uh, have the right level of the different hormones, and it sounds like Judith does. She also has good red and white blood cell counts. A “blood cell” is the smallest unit – the smallest part of what we call blood. A “count” is a number, how many of them are there. If you go on a tour with the group of people, and then you come back to the bus after the tour, the tour director – the leader – might do a head count, might count the number of people there to make sure that everyone’s head and body is present. Well, this is a blood cell count, finding out how many blood cells that Judith has, and it turns out that they are in normal range as well.
Judith says, “That’s good news.” Steven says, “You did well on the EKG stress test and your bone density scan is fine. An “EKG” is an electrocardiography test. “Stress” is normally when you are pushing your body to do perhaps more than it normally does; “stress” can also be anxiety, nervousness, worry. But here, it really refers to using an exercise machine to get your heart working so that the doctors can measure how well your heart is pumping – how well it’s working. This is called an “EKG stress test.” A “bone density scan” refers to a test where they use a machine that goes over your body. You can keep your clothes on; you don’t have to take them off – for now! Don’t take them off while listening to the podcast anyway please. As a general rule, we ask you to keep your clothes on while listening to the podcast. Anyway, this, uh, machine goes over your body and it’s looking to see whether your “bones,” the hard, white material under your skin – whether the bone has the correct amount of certain substances, whether they are becoming soft or not. If they are, then this can be an indication of problems.
So, Judith’s bone density scan was fine. Judith says, “That’s great. What about the other results?” Steven says, “There appears to be no problems with your Pap (pap) smear (smear) or mammogram.” Well, let’s start with Pap smear. I’ve never actually had a Pap smear; I don’t think I ever will. Why? Well, it is an examination that is only done on women, and it takes a sample from their…we’ll call it their internal reproductive organs – look that up if you don’t know what those are on a woman – and makes sure that there is no sign of cancer for that organ. “Pap” stands for…something. I don’t…I have the word in front of me here; I don’t how to pronounce it. I’ve never seen it before, I’m sorry. It doesn’t really matter; everyone calls it a Pap smear. A “mammogram” (mammogram) is also something I will probably never have. It is an x-ray of a woman’s breasts, those things that are on the top of a woman’s chest. It’s used to make sure the woman doesn’t have cancer in the breasts.
Steven says that her Pap smear and mammogram results were just fine, no problems. Judith says she’s glad to hear that. She says, “I hate going through those exams (or going to those exams). I’m glad I don’t have to do them more often.” Steven says, “Just be glad you’re not a man.” Judith asks, “Why’s that?” Steven says, “If you were a man, you’d have to do a PSA…and a DRE.” Judith says, “A what?” and Steven replies, “You don’t want to know,” meaning it’s better that I don’t tell you. Well, I will tell you, however. PSA and DRE are exams that are typically only done on men, just like Pap smears and mammograms are only done on women. “PSA” stands for prostate specific antigen, and only men have a prostate. It’s a test to make sure that the prostate is healthy and that there is no sign of cancer. It’s currently recommended, I believe, that men over the age of 50 have regular PSA examinations so that if there is a problem they can find it early – a problem with cancer. A “DRE” is a digital rectal exam. Let’s talk about that. “Digital” is your finger; “rectal” is, well, when you’re sitting on the toilet the things that come out of your body come through something called a “rectum” (rectum). So, “rectal” is an adjective that describes the rectum. So, you put those two things together, literally your finger and rectal, and you get the digital rectal exam, where the doctor places one of his digits – one of his fingers – in the rectal area. We’ll just leave it at that!
And now, we’ll listen to the dialogue at a normal speed.
[start of dialogue]
Judith: I had my annual physical two weeks ago and I just got a copy of the lab results, but I can’t figure out what they mean.
Steven: Let me take a look. The results of your blood tests are good. Your cholesterol is within the normal range, your glucose levels are fine, your hormone levels are good, and your red and white blood cell counts are normal, too.
Judith: That’s good news.
Steven: You did well on your EKG stress test and your bone density scan is fine.
Judith: Really? That’s great. What about the other results?
Steven: There appears to be no problems with your Pap smear or mammogram results, either.
Judith: I’m really glad to hear that. I hate going through those exams. I’m glad I don’t have to do them more often.
Steven: Just be glad you’re not a man.
Judith: Why’s that?
Steven: If you were a man, you’d have to have a PSA…and a DRE.
Judith: A what?
Steven: You don’t want to know.
[end of dialogue]
Our scriptwriter not only has red and white blood cells, she has red, white, and blue blood cells; it’s the all-American Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
annual – happening once each year; occurring at the same time each year; yearly
* Welcome to our 10th annual users conference!
physical – a medical exam, usually conducted once a year, to assess an individual’s health and monitor changes over time
* The school requires students to have a physical before they can participate on any sports teams.
lab results – a written report of what was found during a laboratory analysis, especially regarding what was found in a blood or urine (liquid waste) sample when it was analyzed in a medical laboratory
* Nancy’s lab results indicated that she has high levels of lead in her blood.
cholesterol – a fatty substance that is necessary for healthy cells and hormone production, but that is dangerous at very high levels and can lead to heart attacks
* Mary is trying to lower her cholesterol by eating less butter, cheese, and red meat.
range – a span of numbers or levels between some minimum and maximum amount
* Your test score fell in the average range, between 70 and 80 points.
glucose – a type of sugar found in the blood and used by the body as a source of energy
* If you don’t eat, your body won’t have enough glucose and you won’t have enough energy to do all the things you want to do.
hormone – one of many substances in the body that affects the functions of other cells and body parts
* When Betty turned 60, her doctor measured her hormone levels and prescribed estrogen pills.
blood cell – the smallest unit of material found in blood (the red liquid inside one’s body)
* People who suffer from Sickle-cell disease have blood cells with unusual shapes.
count – tally; the number of items that have been or can be counted
* This is a 30-count box, so you should have enough pills for the entire month if you take only one each day.
EKG stress test – a test in which a person is told to exercise while his or her electrocardiography (EKG) is used to see how the heart it working and whether it is healthy
* The doctor asked Jun to run on the treadmill as quickly as possible for a few minutes during the EKG stress test.
bone density – a measure of the amount of matter (substance) in a certain volume of bone, the pieces of hard, white material under one’s skin
* Women with low bone density are more likely to suffer from fractures and broken bones.
scan – a test that reads or produces an image of something
* Psychologists conducted brain scans of patients who were watching violent movies to see how their thought patterns were affected.
Pap smear – a Papanicolaou test; a medical exam where a doctor takes a sample from a woman’s internal reproductive organs to test for cancer
* My doctor recommends that most women have a Pap smear once each year.
mammogram – an x-ray of a woman’s breasts, used to test for cancer
* Most women don’t get mammograms until they’re 40 years old, but Karina started earlier because several of the women in her family have had breast cancer in their 30s.
PSA – prostate specific antigen; a test used to check the prostate (the part of a man’s body that makes liquid for carrying sperm) for cancer
* Harold’s PSA test showed high levels, so the doctor is recommending additional testing.
DRE – digital rectal exam; an exam in which the doctor puts his or her fingers into a man’s rectum (where solid waste leaves the body) to check for prostate cancer, or into a woman’s rectum to check for problems with reproductive organs
* Would you rather have a male or female doctor for your DRE?
Comprehension Questions
1. Why can’t Judith understand the lab results?
a) Because they’re written in very bad handwriting.
b) Because they use a lot of technical medical terms.
c) Because they contain conflicting information.
2. Which of these would provide information about a patient’s heart?
a) An EKG stress test.
b) A bone density scan.
c) A Pap smear.
Answers at bottom.
What Else Does It Mean?
physical
The word “physical,” in this podcast, means a medical exam, usually conducted once a year, to assess an individual’s health and monitor changes over time: “Tracy is looking forward to her next physical, so she can show her doctor how much weight she has lost.” The word “physical” can also be used to talk about things we can see and touch: “Teachers shouldn’t be expected to teach students until their physical needs are taken care of.” Or, “After years of working in an office, it was very challenging for Sam to work in a physical job in construction.” Finally, the phrase “a physical relationship” refers to a relationship where people are having sex: “They were best friends for years, but they never had a physical relationship.”
range
In this podcast, the word “range” means a span of numbers or levels between some minimum and maximum amount: “Today’s cars have a wide range of fuel efficiency, mostly depending on how big they are and what kind of engine they have.” Or, “Lynn thinks 72-75 is a comfortable temperature range, but people who visit her house always complain about being too hot.” When talking about music, “range” is the different notes a voice or instrument can make: “The singer was famous for having a range of more than four octaves.” Finally, in a kitchen, a “range” is a stovetop, or the device that produces heat to cook food in pots and pans: “Don’t forget to clean the range when you wash the dishes.”
Culture Note
Standard Physicals
Doctors check many things during an annual physical, depending on a patient’s “health history” (records of what kinds of medical problems a person has had in the past). But all “standard” (typical; common) physicals begin with a conversation where the doctor asks the patient how he or she feels and whether the patient is aware of any problems.
A standard physical for an adult includes “weighing” (determining how heavy something is) the patient. If the weight has increased or decreased “significantly” (in an important way), the doctor usually discusses “eating habits” (the type and quantity of food one normally eats) and exercise with the patient. The doctor will also determine whether the person is “underweight” (not weighing enough, considering one’s height), “overweight” (weighing too much), or “obese” (weighing far too much).
The doctor will also ask questions about the patient’s “behavior” (actions), including whether the patient smokes, “drinks” (drinks alcohol), takes drugs, exercises, or has “unsafe sex” (sex without protection from diseases).
The doctor usually looks into the patient’s ears, nose, and throat, looking for anything unusual. The doctor uses a “stethoscope” (a device that magnifies the sound of heart beating, with one end touching the patient’s chest and the other two ends in the doctor’s ears) to listen to the patient’s heart and “lungs” (the part of the body that takes oxygen from the air). The doctor also “takes the patient’s temperature” (uses a tool to see how hot a person’s body is) and uses a “blood pressure cuff” (a device that puts pressure around the upper arm) to measure the patient’s blood pressure.
Finally, the doctor may ask the patient to leave blood and “urine” (pee; liquid waste) “samples” (a small amount of something) for testing for infections, blood sugar levels, and other health “indicators” (things that show or reveal something).
Comprehension Answers
1 - b
2 - a