
= 2 - AP Government UNIT 2 REVIEW
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there and welcome back to Heimler's History. Now in this video I'm going to take you through everything you need to know about unit 2 of AP government and oh baby is this one a beast. So get them brain cows ready for milking because we have no small amount of information to cover. Let's get to it. +

So unit 2 is all about the three branches of government and how they interact with each other. We're gonna start by talking about the legislative branch 立法部门，then we'll move on to the executive branch 行政部门，and then we'll talk all about the judicial branch 司法部门. But we'll also talk about that kind of unofficial fourth branch of government, namely the bureaucracy 官僚机构. Hmm, you smell that? That smells like learning and it smells good. +

You should know that this video is part of my review packet which has exclusive video content, all the practice questions your little heart could desire, essential course questions and answers, and basically everything you need to do well in this course and on your exam in May. You know, if you're into that kind of thing. To get that, clicky finger out and have at it. +

Okay, let's begin with the legislative branch which is to say congress 国会，which is the law making branch of the government. Structurally congress is made up of two houses and the word for that is bicameral 两院制的. That means in order to pass a bill 法案，two camels are required to spit upon the legislation and that's how laws are made. That's not how laws are made, but now I'm wondering if I even want to live in a country where laws are not made that way. Anyway, congress is made up of two houses and the first is the House of Representatives 众议院. In this house, representatives are apportioned 分配 by the population of each state. More populous 人口稠密的 states have more representatives and vice versa 反之亦然. +

Now representatives in the house are more closely tied to the people whom they represent for two reasons. First, they only serve two-year terms 任期 and that means that they better listen to the people who elected them because in two years they have to go right on back and ask them for another term. Second, because a state is made up of in most cases many districts 选区，house members represent fewer people and thus are able to know their constituency 选区选民 better. Just for poops and giggles, you should probably know that there are 435 representatives that make up the house. +

The second house of congress is the Senate 参议院. There are 100 senators because each state gets two. If this history teacher has his math right, that means we have approximately 50 states. Now senators serve for six years and have a few more constitutional responsibilities than do members of the house, and I'll talk more about those in a minute. But because those senators represent an entire state, they are all things being equal going to be less connected to the intimate details of their constituency than house members. +

Taken together, both houses of congress are required to pass legislation 立法. They must agree on identical versions of the bills and then pass them on to the president for signing. Now you should know that in doing this work of legislation, coalitions 联盟 are formed in order to make the process more efficient. These coalitions are formed in both houses, but the durability 持久性 of the working relationships are affected by term length differences. Senate coalitions tend to be longer lasting and more durable while house coalitions can change more often, even though re-election rates tend to be high. +

Now let's talk about where congress gets its power and for that you need to know two terms: enumerated powers 列举权力 and implied powers 隐含权力. Enumerated powers are those powers explicitly 明确地 listed in Article 1 Section 8 of the constitution. The enumerated powers of congress include but are not limited to federal funding 联邦资金，foreign policy 外交政策 and military legislation 军事立法. Now under the heading of funding, congress has the power to raise revenue 增加收入 through taxation 征税，coin money 铸造货币 for a uniform currency 统一货币 throughout the nation, and pass a federal budget 联邦预算. Under the heading of foreign policy and military legislation, congress has perhaps the most important and far-reaching 影响深远的 foreign policy decision and that is to declare war 宣战. To that end, congress can raise armies 招募军队，pass draft laws 征兵法 and direct funding to the armed forces 武装部队. +

Okay, so those are some of the enumerated powers that congress holds, but they also have implied powers. This basically means that congress can pass any law that is required by the enumerated powers. And the justification 正当理由 for these powers comes at the end of Article 1 Section 8 and it's known as the necessary and proper clause 必要和适当条款，also known as the elastic clause 弹性条款. By this power, congress can pass a wide range of legislation addressing economic, environmental and social issues even if they're not explicitly mentioned in Article 1 Section 8. For example, Alexander Hamilton used the necessary and proper clause to argue for the establishment of a national bank 国家银行. Article 1 Section 8 says that congress can raise funds through taxation -- so you know that's an enumerated power -- but it says precisely nothing about congress having the authority to establish a bank. However, Hamilton argued that if the federal government is going to be raising money, it was necessary and proper to establish a bank. So his argument was that the need for a bank was implied by the power for raising taxes. +

Okay, now let's talk about the leadership structures in congress and we'll start with the house. The constitution only mentions one leader for the house and that's the speaker of the house 众议院议长，and basically all it says is that the house members will choose this leader. Now the speaker will always be a member of the majority party 多数党 -- not because that's what the constitution mandates 要求，but because this leader assumes his or her position by a vote and the majority party isn't going to vote for somebody in the minority party 少数党. Now the speaker has significant power from recognizing who can speak and who cannot, to assigning representatives to committees 委员会. +

Now under the speaker are the majority and the minority leaders 多数党和少数党领袖，and they basically direct debates and guide their party members in policy-making issues. Then you have the whips 党鞭，one each for the majority and minority parties, and whips are exactly what they sound like. Like if representatives are a bunch of livestock 牲畜，then the whips get in there and make sure that their party is moving in the same direction. If a party member steps out of line 越界，so whips render party discipline 党纪 and make sure members of the party walk in line with the party goals. +

Then over in the senate you have a somewhat different leadership structure. There are two senate leaders mentioned in the constitution and the first is the president of the senate 参议院议长，and that privilege 特权 falls to the vice president of the United States 美国副总统. Now the vice president is a non-voting member of the senate unless there's a tie 平局，and then the vice president can vote. The second senate leader mentioned in the constitution is the president pro tempore 临时议长，commonly known as the president pro tem. This is the most senior member of the majority party and has the authority to act as president of the senate when the vice president is not present, which in modern times is a lot. +

Okay, the next rung down on the leadership structure is the senate majority leader 参议院多数党领袖，which in practice much more powerful than the president and the president pro tem. This person sets the legislative agenda 立法议程 by determining which bills reach the floor for debate and which ones do not. And then finally you have the whips who function the way in the senate as they do in the house. +

Okay, so that's the basic leadership structure. Now let's talk about how these representatives get their legislative work done, and in both houses most of the work is done in committees 委员会. Now committees are not required by the constitution but they're more of a practical necessity 实际需要. Essentially there's small groups of representatives who can debate and draft precise legislation 精确的立法 that would otherwise be impossible in the large group setting. +

Now there are four kinds of committees you need to know about. First, standing committees 常设委员会 which are committees that endure for a long time. For example in the senate you have the standing committee on the budget and in the house you have the house judiciary committee 众议院司法委员会. Both of these are permanent committees because they do work that always needs to be done from congressional session 国会会议 to congressional session. It's standing committees where new legislation begins and most bills never make it past that stage. +

Second, you have joint committees 联合委员会 which are groups that have members from both the house and the senate. An example of this is the joint committee on the library of congress 国会图书馆联合委员会. Third, you have select committees 特别委员会 which are temporary 临时的 and created for a specific purpose -- like they're basically the opposite of standing committees. For example, a select committee was formed to investigate President Richard Nixon's Watergate scandal 水门事件，and when that was done the committee was dissolved 解散. +

And fourth, you have conference committees 协商委员会. Now to understand the purpose of these committees you have to realize that if a bill is going to become a law, the bill must be passed by both houses in identical form 相同形式. So if the house passes a bill to raise income tax by five percent and the senate has the same bill but added a provision 条款 to provide every American household with a five gallon tub of nacho cheese per month, well then they have to go into a conference committee and work out the difference. In that case I think it's obvious how to work it out -- get rid of the five percent and give us the cheese. +

Now one last note about committees: generally they serve the goals of the majority party since they hold a majority of seats on each committee, and the committee chair 委员会主席 is always from the majority party. Okay, now all the committees I just mentioned are found in both the house and the senate, but each house has different rules that they follow for getting their work done. +

House rules mandate 规定 limited debate 有限辩论，and that's not hard to understand why. Like compared to the senate, the house has a metric butt load of representatives and if everyone talked as long as they wanted to, they'd never get anything done. So the house limits its members to one hour for debate. Additionally, the house has the house rules committee 众议院规则委员会 which wields 行使 an awful lot of power. This committee is the one that decides which bills make it to the floor for debate, which means that if this committee doesn't allow the bill through, it effectively dies. +

The senate has a slightly different way of getting its work done. In the senate the rules for debate are much more relaxed 宽松的 because there are less members in the senate. Representatives can have unlimited time to debate bills, and one way that they can use that privilege to slow down a bill is by using the filibuster 阻挠议事. Basically this is an attempt to stall 拖延 or kill a bill by talking for a very long time. However, the cloture rule 终结辩论规则 is a way to get a filibustering senator to shut it. It requires a two-thirds vote 三分之二的票数，which is to say 60 senators, to shut down the filibuster and to bring the bill to a vote. Now getting 60 senators to agree on this is a very difficult thing and it doesn't happen that way often. +

Okay, so the senate also gets this work done through something called unanimous consent 一致同意 as a way of speeding legislation along. Before they get to work, the acting senate president asks all the senators if they will agree to limit debate, and of course this is a way of avoiding the possibility of a filibuster. And since it requires unanimous agreement, even one senator can object 反对 which is called a hold 搁置，and thus the bill under consideration can be stalled. +

Okay, now that we understand how each house of congress gets its work done, let's talk about the basic process of how a bill becomes a law. First, the bill has to be introduced and a member from either house can do that. Second, a bill is assigned to a committee and there it often undergoes some changes. Sometimes riders 附加条款 are added which are essentially non-relevant additions which will usually benefit a representative's own agenda, or alternatively it could be something added to help get the bill passed. Sometimes pork barrel spending 政治分肥支出 is added which are funds earmarked 指定用途的 for special projects in a representative's district. And probably the most well-known occasion of pork barrel spending became known as the bridge to nowhere 无实际用途的桥梁项目. Basically there was a bill introduced to provide body armor 防弹衣 for U.S. troops in Iraq, and an Alaska senator thought "you know nobody in their right mind is going to vote against body armor for U.S. troops, so why don't we go ahead and add 400 million dollars for Alaska in there to build a bridge." So you know, the process can be a little sleazy 不正当的. +

Anyway, after the bill is marked up 修订 and amended 修正，it comes back to the whole group where they vote on it. You know, in a perfect world representatives would just vote on the merits of a bill, but sometimes folks engage in log rolling 互投赞成票. This just means that representatives agree and say to each other "hey if you vote for my bill, I'll vote for yours." It's an elaborate system of congressional back scratching. But regardless, if the bill gets a thumbs up then it heads to the president's desk for signing. +

Now before we move on, as you probably mentioned that arguably the most important legislative work done by congress is passing a federal budget 联邦预算. Now most of the federal government's income is gathered from income taxes 所得税，although there are other taxes and tariffs 关税 that generate income as well. And when it comes time for passing a budget, congress has to allocate funds 分配资金 according to two categories. First is mandatory spending 强制性支出，which is spending that is you know mandatory. These are payments required by law, especially with respect to entitlement spending 福利支出. For example, congress passed the social security act 社会保障法案 and that means that they have to make those payments to retirees by law. Other big entitlement spending categories include medicare 医疗保险 and medicaid 医疗补助. And mandatory spending also includes interest payments on debt 债务利息，of which there is a metric butt load. +

Now after mandatory spending is accounted for, everything that's left over is called discretionary spending 可自由支配支出. And so committees debate how to use these funds, and the biggest recipient of discretionary spending by far is paying federal employees 联邦雇员. Now this is probably common sense but I'll say it anyway: as mandatory spending -- otherwise known as entitlement spending -- increases, discretionary spending must decrease. That is of course assuming that the federal government operates on a balanced budget 平衡预算. Wouldn't that be hilarious if they did that? No, there are always more opportunities to spend money than there is money available, so there are two ways to increase discretionary spending. First, congress can raise taxes and people generally don't like that. Second, congress can approve an increase in deficit spending 赤字支出. The deficit 赤字 basically just describes the gap between the budget and the funds available, and where does that money come from? They borrow it. +

Okay, now there is still more to talk about regarding how congress gets its work done. I've given you the mechanics of how they get their work done, but now let's consider some of the factors that might slow down or speed up how they get their work done. Factor number one is ideological divisions 意识形态分歧. Over the last 30 years, Republicans have become more conservative 保守的 and Democrats have become more liberal 自由的，which is a phenomenon called political polarization 政治极化. This makes negotiation 谈判 and compromise 妥协 -- which are essential for passing legislation -- very difficult and often leads to gridlock 僵局 regarding policy. So the quickest way for congress to get things done in this atmosphere is for one party to have a majority in both houses of congress, which means they can just push their legislation through without an occasion for the minority to interrupt it. If that's not the case, then generally anything that requires compromise gets stuck and slows the whole machinery down. +

That slowdown could be even worse when we have a divided government 分裂的政府，which is to say the president is from one party and both houses of congress are from another. For example in 2016, President Obama -- a Democrat -- had the occasion to appoint a new judge to the supreme court, and obviously he's going to choose a liberal judge. But the Republican-dominated senate argued that since it was an election year, they should wait to see who would win the presidency before they confirmed a new judge. You know, Obama was serving in the last months of his second term which made him a lame duck president 跛脚鸭总统，which basically means that he had very little power to do anything since he was on his way out of office. So the senate simply wouldn't hold a confirmation hearing 确认听证会. But the situation was very different in 2020. That also was an election year and Republican President Donald Trump had the occasion to appoint a new justice, and the Republican senate rushed the confirmation through without waiting on the outcome of the election. So here you have a very good example of how a divided government can slow things down and how a unified government 统一的政府 can speed things up. +

Alright, another factor that affects the efficiency of the work that congress does is the different conceptions of their representative role in determining how they vote. Some representatives follow the trustee model 受托人模式，which means they believe that they have been entrusted with the people's faith to vote according to the representative's best judgment 最佳判断. A good example of this is Republican Senator Mitt Romney's vote to remove Donald Trump from office. This was a move that the majority of his constituency did not support, but he voted according to his best judgment. Other representatives follow the delegate model 代表模式，which means that the representative believes that he or she must vote with the will of the people even if it goes against their own better judgment. You find this model more in the house since their two-year terms make them more accountable to the people. And then still other representatives adopt the politico model 政治人物模式，which is basically just a blend of the other two. For the politico, how they vote depends on the situation. Like if there is a strong public opinion on an issue, the politico will consider that when voting and may act like a delegate. If not, they will vote like a trustee. +

Okay, now there's one more issue that you need to know with respect to the efficiency of congressional work and that is redistricting 重新划分选区 and gerrymandering 不公正地划分选区. That sounds like two things, Heimlich. I know what I said, but they're related. Cool off. Anyway, the constitution says that every 10 years a census 人口普查 must be taken to find out how many people live in the United States and where they live. Then based on that information, the number of representatives for each state is apportioned to reflect the population, and then congressional districts are redrawn 重新绘制 to reflect those new seats. So you've got reapportionment 重新分配 which is the doling out of representative seats, and then you have redistricting which is the redrawing of boundaries that those folks represent. +

So this is a highly contentious 有争议的 issue and things can get even more heated when districts are not reapportioned properly, and to understand that we need to talk about two required supreme court cases. First is Baker vs Carr in 1962. So by 1962 Tennessee had not redrawn its districts for over 60 years. In that time the urban populations of Tennessee had exploded while the rural populations had grown much slower. That meant that rural citizens had much more voting power than urban citizens, or to say it another way, a minority of voters had a majority of the power precisely because districts had not been redrawn. So in this case the supreme court ruled that such a situation violated the equal protection clause 平等保护条款 of the 14th amendment, and out of this decision we got the one person one vote principle 一人一票原则. In other words, districts must be drawn in order to evenly distribute voting power. Additionally, this case settled the question about whether apportionment issues are justiciable 可由法院裁决的，which means whether or not the court can rule on such questions. In case you're not following, the answer is yes, the court can rule on apportionment issues because it is a constitutional issue not a political issue. +

The second case you need to know is Shaw versus Reno in 1993, which was similar to Baker versus Carr in that it dealt with the drawing of congressional districts, but in this case it considered the constitutionality 合宪性 of drawing those districts based on race alone. Now in order to understand the outcome of this case you need to understand the concept of gerrymandering. Basically this is a way of drawing districts and it's a little sleazy because districts can be drawn to favor one group over another. Usually gerrymandered districts are drawn in weird shapes which don't correspond at all to the natural features of the landscape, and they're drawn that way to ensure that a certain party has the authority in that district. And that is what's known as partisan gerrymandering 党派不公正划分选区. But Shaw versus Reno dealt with a different kind of gerrymandering known as racial gerrymandering 种族不公正划分选区，which means districts are drawn so that certain races constitute the majority in those districts. So in this case, two districts in North Carolina were drawn with strange shapes and created majority black districts which actually meant that these districts had a very good chance of electing black folks to office, thus upholding the provisions of the Voting Rights Act of 1965 for historically discriminated people. However, the court ruled that drawing this district solely based on race -- even if it helped historically discriminated people -- was a dangerous practice and thus unconstitutional. +

So the point of everything I just said at length is to show you how all of these factors taken together affect how well congress is able to do its job. Okay, that was a lot, but let's keep going and talk now about the executive branch. If you're weary 疲倦的 after all that talk about congress then go get yourself one of those energy drinks that have enough caffeine to kill a small horse. Let's continue. +

So let's begin talking about how a president can implement 实施 his or -- in the future perhaps her -- policy agenda 政策议程. Now every president comes into office with a set of policies that they want to see enacted 制定，but as you know by now, it is congress that has constitutional authority 宪法权力 to pass laws, not the president. So how does the president get that policy agenda enacted? Well, through formal powers 正式权力 and informal powers 非正式权力. +

The president's formal powers are laid out 阐述 in Article Two of the constitution. Now let's talk about a couple of them. First and maybe most important of the president's formal powers is the veto 否决权. As I mentioned before, if a bill is going to become a law then the president must sign it within 10 days of its arrival on the executive desk. If a particular law is not in line with 与… 一致 the president's policy agenda then the president can veto it, which means the bill will not become a law. At that point three things can happen. Number one, the bill dies, everyone wipes a single tear off their face and life goes on. Two, the bill is sent back to congress and they can add or subtract items from the bill to make it more palatable 受欢迎的 to the president, and if that happens that means that the bill would have to start over completely and go through the entire process again. And thus when a president even threatens a veto, it incentivizes 激励 congress to negotiate further before sending the bill to the presidential desk. Three, congress can override a presidential veto with a two-thirds vote 三分之二的票数，which is very difficult to do. +

Now that's the formal veto process, but the president can also exercise informal powers with the veto. An example of this is what I just mentioned -- like the president threatens to veto and so that sends a signal to congress that they have to work the bill into something that the president can sign. The president can also employ the pocket veto 搁置否决权. "It was right there in my pocket all along." Remember that the president has 10 days to sign the bill into law, but if a bill shows up that does not align with 与… 一致 the president's policy agenda and there are less than 10 days left in the congressional session, the president can do nothing with it, let the session expire 到期，and the bill is effectively vetoed. On the other hand, if there are more than 10 days left in the session and the president does not sign it, the bill then becomes a law. +

Now the president is also given formal powers with respect to foreign policy 外交政策. According to Article 2, the president is the commander-in-chief 总司令 of the United States armed forces 武装部队. Even so, remember that the president can't declare war 宣战 -- that power belongs to congress. But that can get a little murky 模糊的 because not every deployment of troops 军队部署 equals a declaration of war. For example, President Obama authorized navy seals 海豹突击队 to kill Osama bin Laden in 2011. Now with respect to foreign policy, the president can enter into executive agreements 行政协定 with other heads of state. This isn't a treaty 条约 since treaty ratification 条约批准 is a power belonging to the senate, but more like a contract 合同 between a president and another president or monarch 君主. For example, before the U.S. entered World War II, President Roosevelt made an executive agreement with Britain to provide U.S. destroyers 驱逐舰 in exchange for 99-year leases on certain UK naval bases 英国海军基地. +

Okay, now I've given you some of the formal powers of the presidency laid out in the constitution and have dabbled in 涉足 some of the more informal powers, but now let's talk directly about those informal powers. The first informal power of the president is bargaining 谈判 and persuasion 说服. We'll talk more about this in a moment, but essentially the president has the nation's attention in a way that no other politician does, so the president can use that attention to persuade the people according to the executive policy agenda. +

Another informal power is the executive order 行政命令，and this is a directive 指令 from the president that has the force of federal law 联邦法律的效力 but it's not actually a law. That's confusing, Heimler. Well then let me explain it up real nice to you. Mainly executive orders direct the actions of the federal bureaucracy 联邦官僚机构 and the military, which are both areas the president does have direct authority over. For example, by executive order the president can move money from one bureaucratic agency 官僚机构 to another in order to get done what the president wants to get done. For example, one of Donald Trump's central campaign promises was to build a wall on the U.S.-Mexico border, and when congress wouldn't approve that funding, Trump declared a national emergency 国家紧急状态 and by executive order moved money from several executive agencies so that the work could begin. +

Another informal power of the president is the signing statement 签署声明. So when signing a bill into law, the president can also issue a signing statement which informs the nation how the executive branch interprets that law and thus how the president intends to execute it, which of course could be different than the congressional version of the law. +

Okay, now still keeping with the president's policy agenda, it won't surprise you to know that this agenda can conflict with the agendas of other branches of government, especially with congress and even more specifically with the senate. So included in the president's power is the ability to make federal appointments 联邦任命，but those appointments have to be confirmed by the senate and that can lead to some tension 紧张关系. Let me just give you some examples. The president appoints a team of advisors 顾问 which is known as the cabinet 内阁. These folks make up the heads of all the different executive agencies 行政机构 -- on which more in a moment -- and typically the senate just lets these appointments cruise on through on the assumption that the president should be able to choose their own staff. However, there are some cabinet appointments that get downright scrappy 激烈的. For example, Donald Trump nominated Betsy DeVos as the education secretary 教育部长 because she made it clear that she would pursue the privatization of education 教育私有化. That made her a lot of enemies in the senate. Her confirmation hearing actually ended in a tie, and that brought Vice President Mike Pence -- in the president of the senate -- to break the tie in DeVos's favor. +

The president also appoints ambassadors 大使 to other countries, and usually the senate just confirms those folks without much drama. The white house staff 白宫工作人员 is likewise appointed by the president but requires no senate confirmation. At this point you're like "I thought you said there was tension here between these two branches. Like give us the drama." All right, you want the sauce? I'll give you the sauce. The sauce comes when there's an opening for a federal court nomination 联邦法院提名，more specifically the supreme court nomination 最高法院提名. This is where things get highly contentious 有争议的. Judges who are appointed to the supreme court hold that job for the rest of their lives, and that means that if a president appoints a judge who is favorable to the presidential policy agenda, the judge can rule in line with that agenda for many years to come after the president is no longer in office. Not surprisingly, conservative presidents appoint conservative judges and liberal presidents appoint liberal judges. And because of the long-term effects of this appointment, it creates no small amount of tension with the senators of the opposite party. +

Now you should know that over the course of U.S. history, the scope of presidential power 总统权力的范围 has expanded roughly three to four metric butt loads give or take. Reaching all the way back to unit one, this expansion of power in the executive branch is exactly what the anti-federalists 反联邦党人 were worried about. In fact they said that the presidency as it was laid out in the constitution was nothing less than the fetus of monarchy 君主制的雏形. But hark 听，I see upon yonder shore a required document. It's Federalist 70, and in this essay Hamilton argued that a single executive was necessary because one person is able to act swiftly and decisively 果断地 on matters that require firm leadership and tactical decision making 战术决策. Additionally, Hamilton argued that the executive branch can be checked with the power of the other two branches, so a presidential monarch would be an impossibility. And finally, if the president does turn out to be a corrupt turd, then it is much more easily detectable in a single individual than in multiple, and thus a single executive will have to be much more careful with their power since they will be much more closely watched. And ultimately, as you already know, that was the argument that won the day. +

But even so, as I mentioned, the power of the president has grown significantly over time. George Washington along with the first five presidents who followed him basically yielded to 屈服于 congress's agenda since congress was the voice of the people. Washington even stepped down after two terms to put the kibosh on 阻止 any fears of an overbearing executive 专横的行政部门. Remember in Washington's day there was no limit on the number of terms a president can serve. Now later that was added to the constitution in the 22nd amendment 第二十二修正案，but still, Washington set the two-term precedent 两届任期的先例. +

But then there was a significant shift in presidential power in the presidency of Andrew Jackson. He believed that the president was the representative of the people and not congress, and thus he expanded the power of the executive office to reflect that. The classic example here is the supreme court ruling that it was unconstitutional for the executive branch to force the Cherokee Indians off of their land in Georgia, and yet Jackson went ahead and did it anyway because that's what in his mind the people wanted. +

And then presidential powers expanded even further with Abraham Lincoln. He assumed way more power than any president before him, and he's generally forgiven for it because he had the civil war to fight. Most famously, he suspended the constitutional right of habeas corpus 人身保护令 which meant that he could order people to be arrested without granting them a trial. +

And then if there was ever a president who expanded executive power, it was our boy Franklin Roosevelt. The man used the veto 635 times. Look, in case you don't know, that's a lot. Like everybody broke out when Andrew Jackson used the veto 12 times in his tenure 任期 -- that was more than all the presidents before him combined. So FDR used the veto 635 times to which I say "dang." He was, to say the least, an energetic executive. He pushed his New Deal programs 新政计划 through congress in order to address the devastating effects of the Great Depression 大萧条 -- programs like social security 社会保障 and minimum wage laws 最低工资法 and public works programs 公共工程项目. Also, FDR served no less than four stinking terms as president. Now to be fair, he did die in the first year of his fourth term, but still, the man was elected four times. So we're talking about expansion of federal power, it really was FDR who gave us our old friend Big Daddy Government. +

Okay, now let's talk about presidential communication 总统沟通，and if there's one advantage that the president has that no other branch does, it's the eyes and ears of the nation 全国人民的关注，and good presidents use that attention to their advantage. The term for this presidential communication comes from Teddy Roosevelt who said that the presidency was a bully pulpit 天字第一号讲坛. Now the word bully doesn't mean then what it does now -- it just meant excellent. In other words, Roosevelt was enamored with 迷恋 the fact that he could speak directly to the people and that they would hopefully in turn put pressure on their representatives to legislate in line with Roosevelt's agenda. And one of the chief ways the president does this is through the annual state of the union address 国情咨文 to congress. +

Now the effectiveness of the presidential bully pulpit has changed as technology has advanced. For a long time presidents did give their state of the union addresses and those were filtered through newspaper editors. But with the advent of 随着… 的出现 radio, Franklin Roosevelt discovered that he could talk directly to the people without any intermediary 中间媒介，and he did so in his famous fireside chats 炉边谈话 where he explained in simple terms his policy proposals through the radio. John F. Kennedy was the first president to use the new medium of television to deliver live press conferences 现场新闻发布会，and that is when you saw the creation of a presidential communication office which worked to refine and to shape the president's talking points 谈话要点 so that the president's policy agenda would succeed in the hearts and minds of the people. And then with the advent of social media 社交媒体，the bully pulpit took on yet another form. This was a massive innovation in presidential communication because now the president had a way to speak to the people not only without an intermediary but as often as the president wanted to. Barack Obama appointed to social media as the key to winning his first campaign by creating a stream of communication directly to his supporters through social sites. To put it mildly, Donald Trump uh built on this innovation. He was deeply suspicious of traditional news media and used Twitter as his bully pulpit to comment dozens of times a day on legislation, his political enemies and foreign affairs. In fact, Trump so often used the Twitter platform that he earned the nickname "Tweeter in Chief." +

All right, with that let's move on to the judicial branch 司法部门. We're going to start with how the courts are structured 结构 and then talk about how it checks the other branches. So in terms of the structure of the federal court system 联邦法院系统，there are three levels. At the bottom there are the U.S. district courts 美国地方法院 and there are 94 of those spread across the nation. These courts have what's called original jurisdiction 初审管辖权，which means that they have the right to hear a case for the first time. On the next level you have the U.S. circuit court of appeals 美国上诉法院 and there are 12 of these. They have what's called appellate jurisdiction 上诉管辖权，which means that they hear appeals from the lower courts. And the big daddy federal court sitting on top of the heap is the supreme court 最高法院，which has both original and appellate jurisdiction depending on the kind of case being heard. +

The supreme court is the only one of these courts that is explicitly mentioned in the constitution, and that is in Article 3. All the other courts I mentioned are created by congress in the judiciary act of 1789. Now wouldn't you know it, there is a required document associated with the supreme court, namely Federalist 78. In this essay, Hamilton argued that the independence of the judicial branch 司法部门的独立性 acted as a protection for its power. Where does the court get such independence? Well, from the lifetime appointment of its judges 法官的终身任命. If the judges aren't answerable to the voters 对选民负责，that means that they can rule on cases without the pressure of trying to get reelected. Hamilton also argued that the court has the right of judicial review 司法审查权，which means it's the court's job to declare laws constitutional 合宪的 or unconstitutional 违宪的. It's through this power that the supreme court has the power to check the other branches of government. +

Now this power isn't explicitly mentioned in the constitution, and that's where the required case of Marbury versus Madison in 1803 comes in. Now I'm not going to go through all the details of this case, but what you really need to remember is that it was the court's ruling in this case that firmly cemented 巩固 the power of judicial review in the supreme court's purview 职权范围，and that had the effect of significantly increasing the power of the supreme court. In the constitution the supreme court was kind of like Steve Rogers trying to sign up for the army, but after Marbury the court is like Steve Rogers coming out of that pod with his muscles all jacked and twitching. +

Okay, now let's talk about how the court works as they're considering their cases. The role of precedence 先例 is of extreme importance. So when a decision is handed down 作出裁决，it creates a precedent which means that unless there are some very extreme circumstances, this decision will act as a binding template 有约束力的模板 for future decisions. You know, precedents are very hard to overturn 推翻 because of a principle to which the court holds, namely stare decisis 遵循先例原则 which when being translated means "let the decision stand." So if the court receives a case on a topic that has already been decided, it will often rule in the same way as the previous case. However, although it is rare, precedence can be overturned as it was for example in Brown versus the Board of Education -- on which more in unit 3. +

Now the supreme court by comparison is less bound to precedence than the lower courts, but even so, precedents still serve to guide present decisions in a very significant way. Now when it comes to upholding 维持 or overturning precedence, the court's activity falls under two headings: judicial activism 司法能动主义 or judicial restraint 司法克制主义. Judicial activism is the idea that the court acts to establish policy and considers more than just the constitutionality of a decision -- it also considers the decision's broader effects on society. Brown versus the Board of Education is an important example of that, and activism in the court can either be liberal or conservative. +

Okay, now on the other side of the spectrum is judicial restraint, and the idea here is that judges believe that they aren't appointed to make policy -- like the elected legislature 立法机关 exists for that. If judges act according to judicial restraint, they believe that a law should only be struck down 废除 if it violates the actual written word of the constitution. +

And then the ideology 意识形态 of the judges also plays a role in how the court makes his decisions as well. Presidents appoint judges that align with their own political sympathies 政治倾向，and this has a role in whether the court will remain bound to previous precedents or create a new one. For example, since the 70s, conservative presidents have appointed conservative judges to the court in hopes of overturning the precedent established in Roe v. Wade which made abortion legal in all 50 states. Now so far that effort has been unsuccessful, but it illustrates the point that ideology plays a role in the court's decisions. +

Now, probably not going to surprise you to hear that as the court has exercised its power of judicial review, it has often led certain groups of Americans to question the legitimacy 合法性 of the court's power. And this is especially true when controversial decisions are handed down. +

For example, in the landmark case 里程碑式案例 of Dred Scott v. Sandford in 1857, the court essentially ruled that slavery was permissible 可允许的 in all states. Now, if you know your U.S. history, you'll know that in 1857, the country was coming apart at the seams 即将分裂 over the slavery question. And so, when the court handed down this decision, no small amount of abolitionists 废奴主义者 and anti-slavery crusaders 反奴隶制斗士 called into question the legitimacy of the Supreme Court. Like, how in the world can these unelected judges overturn all the legislation that has kept the North free of slavery? +

When the court hands down a decision, it effectively becomes the law of the land. But there are some ways that the other branches can reduce the impact of those decisions. The president can appoint new judges as the opportunity arises. For example, I just mentioned Roe v. Wade a second ago. Evangelical Christians have been trying to get that overturned for a long time, and their chief way of doing it in the 2016 election was to elect Donald Trump. And when asked why they voted for a man whose ethics are so opposed to Christianity, their response was, "For the court nominations." +

Now, another way the president can mitigate 减轻 court decisions is by a lack of enforcement 不执行. For example, the court ruled that it was unconstitutional for the federal government to remove Cherokee Christians from their lands in Georgia, and Andrew Jackson went ahead and did it anyway. +

Then, Congress can also check the power of the judicial branch, and they do this through legislation 立法. For example, Congress invalidated 使无效 the Dred Scott decision by passing the 13th Amendment to the Constitution, which abolished slavery 废除奴隶制. Additionally, Congress passed the 11th Amendment, which limited the court's jurisdiction 管辖权，thus restricting the kinds of cases that can even be heard in the Supreme Court. +

And with that, it's time to turn the last corner in this video and talk about the federal bureaucracy 联邦官僚机构. +

Now, the bureaucracy is not a separate branch of government, although sometimes you'll hear people refer to it as the "fourth branch of government." Technically, the bureaucracy falls under the authority of 受… 管辖 the executive branch, and it's made up of millions of people who are employed to carry out the responsibilities of the federal government. +

So, why don't we begin by talking about the structure of the bureaucracy, and then we'll see how it gets its work done? +

In terms of structure, the highest level of authority in the bureaucracy falls to the cabinet secretaries 内阁部长. These are the leaders of the 15 executive departments 行政部门，like the Department of Energy 能源部，the Department of Homeland Security 国土安全部，or the biggest of all, the Department of Defense 国防部. And then, these departments are further subdivided into agencies 机构，which all work together to accomplish the goals of the department. +

For example, the Department of the Treasury 财政部 has all kinds of tax-collecting agencies within it, like the Internal Revenue Service 美国国税局，or the IRS. So, the way it works in this case is that Congress passes tax legislation 税收立法，and then it's up to these agencies to make sure that taxes are actually collected. +

Another part of the bureaucratic structure is commissions 委员会. These are regulatory groups 监管团体 who operate somewhat independently of the authority of the president but still fall under the executive authority. They're run by a board of individuals, and they're usually created for a specific purpose. For example, you have the FCC, or the Federal Communications Commission 美国联邦通信委员会，which regulates the content of media -- not by censoring free speech 审查言论自由，but by making sure that nothing inappropriate is displayed. +

And then, yet another part of the bureaucratic structure is government corporations 政府公司，which are kind of like a hybrid 混合体 between a business and a government agency. Basically, the government acquires businesses when they want to offer a public good 公共产品，but the free market is the best way to offer that service. A good example of this is PBS, which produces educational media. +

Now, when it comes to the actual work of the bureaucracy, here's what they do. +

First, they write and enforce regulations 法规. But it's important to remember the distinction here: The bureaucracy is not creating laws. Congress is responsible for that. The bureaucracy is only making a set of more refined rules 更细化的规则 that help facilitate the execution of the law 法律的执行. +

For example, the 16th Amendment 第十六修正案 establishes the income tax 所得税，but there's nothing about how those taxes are going to be collected. It was the IRS who determined that taxes are due by April 15th and how we are to pay them. So, this is what's known as delegated discretionary authority 委托自由裁量权. And by definition, it's the authority given to the bureaucracy by Congress that gives them the discretion 自由裁量权 on how to make the rules and carry out the laws. +

And another part of this authority is compliance monitoring 合规监测，which means that the bureaucratic agencies establish rules for certain industries and then have to do the work of making sure those industries are complying with those rules. Now, look, this can slow down policy implementation 政策实施，but the alternative is lax oversight 监管不力，which would essentially invalidate the regulations they exist to implement. +

The second thing that bureaucracy does is issue fines 罚款 when laws are violated. +

And third, heads of agencies will often testify before Congress -- either to be held accountable for their actions or just to give an update on the work of their agency. +

Now, these bureaucratic agencies often work very closely with other entities 实体，and I want to mention one relationship that you really need to know, and it's called an "iron triangle" 铁三角. The three points are bureaucratic agencies 官僚机构，congressional committees 国会委员会，and interest groups 利益集团. And these groups often work together and rely on one another to create policy. +

Bureaucrats offer expertise to congressional committees, with whom they are eager to cooperate, since it's Congress who approves funding for their departments. And the committee members want to pay attention to interest groups because they often have policy experts who can inform them of the implications of certain policies. And then, interest groups can provide funding for congressional races 国会竞选. +

And with all this mutual benefit 互利，the relationship between the three grows very strong. And that is why it's called an "iron triangle" -- not an "overcooked noodle triangle," because, you know, overcooked noodles are kind of weak and structurally can't hold much. You know, it'd be a bad metaphor for a strong relationship. +

Anyway, for your exam, you need to know the names and purposes of seven of these bureaucratic departments. I'm not going to tell you everything these departments are responsible for; I'm just going to give you a couple examples. +

First is the Department of Homeland Security, which protects the U.S. from terrorism 恐怖主义 and maintains and controls the nation's borders 边境. +

Second is the Department of Transportation 交通部，which manages all kinds of transportation, like highway and air travel. +

Third is the Department of Veterans Affairs 退伍军人事务部，which manages veterans' hospitals and the general welfare 总体福利 of America's veterans. +

Fourth is the Department of Education 教育部，which oversees 监督 states in their implementation of federal educational standards 联邦教育标准. +

Fifth is the Environmental Protection Agency 环境保护署，which works to protect the environment and human health through industrial regulation 工业监管. +

Sixth is the Federal Elections Commission 联邦选举委员会，which administers and enforces campaign finance laws 竞选财务法. +

And then seventh is the Securities and Exchange Commission 证券交易委员会，which regulates the stock market 监管股票市场 and prevents fraud 防止欺诈. +

Now, all the leadership in these entities are folks whom the president appoints. And if the bureaucracy doesn't act sufficiently in accordance with 与… 一致 the president's policy agenda, the president can fire them and appoint new leaders in cabinet and agency positions -- although the president cannot fire regulatory commission heads 监管委员会负责人. +

And often, not surprisingly, the president tries to staff those positions with folks sympathetic to the executive goals. Even so, commission heads serve fixed terms that overlap and outlast any given president. So, while the president does have a lot of influence over these entities, the president's influence isn't total. +

So, all of these departments and agencies and commissions I just listed, along with hundreds of others, are basically the law enforcement apparatus 执法机构 of the executive branch. But their power in this regard can still be checked by other branches of government. +

Because Congress is responsible for making sure that laws are upheld along the lines in which they were passed, they can hold committee hearings 委员会听证会 to ensure such execution is happening. Congress has many committees that correspond to the bureaucracy's agencies and will call directors of those agencies to testify and give reports of their progress. And sometimes, this is just a friendly check-in; other times, it can be tense. +

But Congress also has another way to check the bureaucracy, and that's because Congress is the entity who's holding all the hooch in its pockets. Through the power of the purse 财政权，Congress can decide how to allocate funds to different agencies. And agencies cannot spend their money until a committee or subcommittee authorizes them to do so. +

The president can also check the bureaucracy, and this is usually the first line of defense, since it falls under the president's authority. For example, President Clinton initiated a National Performance Review 国家绩效评估，in which the various agencies were required to scrutinize 审查 and, if necessary, change its mission and objectives. +

You didn't think the judicial branch was going to miss out on all this power-checking fun, did you? When citizens believe that bureaucratic decisions are unconstitutional, they can challenge them in court. And usually, unless the agencies are blatantly violating a law 公然违反法律，the court upholds the authority of the agency. +

And the legitimacy of the bureaucracy has been challenged over time, specifically regarding its independence 独立性. These agencies and commissions create rules and regulations that do have the force of law, but as you no doubt know by this point, they are not elected representatives and thus are not accountable to the people. And this has a way of chapping the American thighs. +

You also need to know that the way people have been chosen to work in the bureaucracy has changed over time. Back in the first hundred years or so of our history, people were given bureaucracy jobs based on the patronage system patronage system 庇护制，which means that these jobs were a way for the president to award those who supported his campaign 竞选活动. +

And that system was in place for a long time, but it kind of went sideways when President Garfield was assassinated. Basically, Garfield didn't give a bureaucratic job to a man who supported his campaign, so that man went ahead and shot the president. So, clearly, there needed to be some reform on that count. +

And there was. After the Garfield assassination, Congress passed the Pendleton Civil Service Act 彭德尔顿公务员法 in 1883, which created a merit system 功绩制 for bureaucratic appointments 官僚任命. So now, you had to pass a competitive examination 竞争性考试 in order to get one of those sweet bureaucratic jobs. +

And that reform continued into the 20th century in order to make the bureaucracy more professional, specialized, and neutral 中立的. For example, under Jimmy Carter's administration, we got the Civil Service Reform Act 公务员改革法，which upheld the merit system but made further reforms to help offer wider opportunities for women, more efficient control of human resource departments, etc. +

And that's it. Oh my goodness, that was a giant unit, but I hope it helped. And if you want more help getting an A in your class and a five on your exam in May, you can click right over here and grab the Ultimate Review Packet. +

If this video helped you, and you want me to keep making them, then you can let me know that by subscribing 订阅. +

Heimler out. +





'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史课程。在这个视频中，我会带你了解美国大学预修课程（AP）政府课程第二单元的所有内容，这部分内容可不少呢。所以，准备好汲取知识吧，我们可没有时间浪费，让我们开始吧。 +

第二单元的内容主要是关于政府的三个分支以及它们之间的相互作用。我们会先讨论立法分支，然后会讲到行政分支，接着我们会谈论司法分支。此外，我们还会讨论政府的 “非官方” 第四分支，也就是官僚机构。嗯，你闻到了吗？那是知识的味道，还挺不错的。 +

你应该知道，这个视频是我的复习资料包的一部分，其中包含独家视频内容、你想要的所有练习题、重要的课程问答，基本上包含了你在这门课程中取得好成绩以及在五月份的考试中取得高分所需要的一切。当然，前提是你对这些内容感兴趣。如果你想获取复习资料包，点击这里即可。 +

好的，让我们从立法分支开始讲起，立法分支也就是国会，它是政府的立法机构。从结构上看，国会由两院组成，这种结构被称为两院制。这意味着一项法案要获得通过，需要两院共同参与，这样法律才能得以制定。实际的立法过程可不是这样，但现在我在想，如果一个国家的法律不是这样制定的，那会是什么样呢？不管怎样，国会由两院组成，第一个是众议院（House of Representatives）。在众议院中，众议员的名额是根据每个州的人口来分配的。人口较多的州众议员人数较多，反之亦然。 +

众议院的众议员与他们所代表的民众联系更为紧密，原因有两点。第一，他们的任期只有两年，这意味着他们需要认真听取选民的意见，因为两年后他们需要再次寻求选民的支持以获得连任。第二，因为一个州通常由多个选区组成，众议员所代表的人数相对较少，所以他们能够更好地了解自己的选民。只是开个玩笑，你可能需要知道，众议院由435名众议员组成。 +

国会的第二个议院是参议院（Senate）。参议院有100名参议员，因为每个州有两名参议员。如果这位历史老师的数学没错的话，这意味着我们有大约50个州。参议员的任期为六年，他们比众议员承担着更多的宪法职责，我一会儿会详细讲到这些职责。但由于参议员代表的是整个州，所以与众议员相比，他们与选民的具体情况联系没那么紧密。 +

总的来说，一项立法需要国会两院共同通过。两院必须就法案的内容达成一致，然后将法案提交给总统签署。你应该知道，在立法过程中，为了提高效率，会形成一些联盟。国会两院都会形成这样的联盟，但由于任期长度的差异，这种工作关系的持久性也会受到影响。参议院的联盟往往更持久，而众议院的联盟变化会更频繁，尽管众议员的连任率往往很高。 +

现在，让我们谈谈国会的权力来源，为此你需要了解两个术语：列举权力（enumerated powers）和默示权力（implied powers）。列举权力是指在宪法第一条第八款中明确列出的权力。国会的列举权力包括但不限于联邦资金的管理、外交政策的制定以及军事立法。在资金管理方面，国会有权通过征税来筹集收入，铸造货币以统一全国货币，并通过联邦预算。在外交政策和军事立法方面，国会拥有一项非常重要且影响深远的权力，那就是宣战权。为了实现这一权力，国会可以招募军队、通过征兵法案并为武装部队提供资金。 +

好的，这些是国会拥有的一些列举权力，但国会也拥有默示权力。这基本上意味着国会可以通过任何基于列举权力所需要的法律。这些权力的合理性来自宪法第一条第八款的末尾，这一条款被称为 “必要且适当条款”（necessary and proper clause），也被称为 “弹性条款”（elastic clause）。凭借这一权力，国会可以通过一系列广泛的立法来解决经济、环境和社会问题，即使这些问题在宪法第一条第八款中没有明确提及。例如，亚历山大·汉密尔顿（Alexander Hamilton）利用 “必要且适当条款” 来支持建立国家银行。宪法第一条第八款规定国会可以通过征税来筹集资金——这是一项列举权力——但它并没有明确提到国会有权建立银行。然而，汉密尔顿认为，如果联邦政府要筹集资金，建立银行是必要且适当的。所以他的观点是，建立银行的必要性是由征税权力所暗示的。 +

好的，现在让我们谈谈国会的领导结构，我们从众议院开始。宪法只提到了众议院的一位领导人，那就是众议院议长（Speaker of the House），宪法基本上只是规定众议员将选出这位领导人。众议院议长通常是多数党的成员——这并不是宪法的强制规定，而是因为这位领导人是通过投票产生的，多数党不会投票给少数党的成员。众议院议长拥有很大的权力，比如决定谁可以发言，以及将众议员分配到各个委员会。 +

在众议院议长之下是多数党领袖和少数党领袖，他们主要负责指导辩论，并在制定政策的问题上引导本党成员。然后是党鞭，多数党和少数党都有党鞭。党鞭的作用就像他们的名字一样。就好比众议员们是一群牲畜，党鞭要确保本党成员朝着同一个方向行动。如果有政党成员违反规定，党鞭会维护党的纪律，确保党员们与党的目标保持一致。 +

在参议院，领导结构有些不同。宪法提到了参议院的两位领导人，第一个是参议院议长（President of the Senate），这个职位由美国副总统担任。副总统是参议院的非投票成员，除非出现平局，在这种情况下副总统可以投票。宪法提到的参议院的另一位领导人是临时议长（President pro tempore），通常被称为临时议长（President pro tem）。临时议长是多数党的资深成员，当副总统不在时，他有权担任参议院议长，而在现代，这种情况经常发生。 +

好的，领导结构的下一级是参议院多数党领袖，实际上，参议院多数党领袖比参议院议长和临时议长更有权力。参议院多数党领袖通过决定哪些法案可以在参议院进行辩论，哪些法案不能，来设定立法议程。最后是党鞭，参议院的党鞭和众议院的党鞭作用相同。 +

好的，这就是基本的领导结构。现在让我们谈谈这些众议员是如何完成立法工作的，在国会两院，大部分工作是在委员会中完成的。委员会并不是宪法所要求设立的，但它们是实际工作中的必要机构。基本上，委员会是由一小部分众议员组成的小组，他们可以在这样的小组中进行辩论并起草精确的立法，如果在整个大的议会中进行这些工作可能是无法实现的。 +

你需要了解四种类型的委员会。第一种是常设委员会（standing committees），这些委员会长期存在。例如，在参议院有预算常设委员会，在众议院有司法委员会（House Judiciary Committee）。这些都是永久性的委员会，因为它们的工作是每个国会会议都需要做的。新的立法通常从常设委员会开始，而且大多数法案在这个阶段就无法继续推进了。 +

第二种是联合委员会（joint committees），这些委员会由来自众议院和参议院的成员组成。例如，国会图书馆联合委员会（joint committee on the library of congress）。第三种是特别委员会（select committees），它们是临时设立的，为特定目的而成立——这与常设委员会正好相反。例如，曾成立过一个特别委员会来调查理查德·尼克松（Richard Nixon）总统的水门事件，当调查结束后，这个委员会就解散了。 +

第四种是协调委员会（conference committees）。为了理解这些委员会的目的，你必须明白，如果一项法案要成为法律，它必须以相同的形式在两院通过。所以，如果众议院通过了一项将所得税提高5% 的法案，而参议院通过的同一法案增加了一项条款，即每月为每个美国家庭提供一大桶玉米片奶酪，那么他们就需要进入协调委员会来解决这些差异。在这种情况下，如何解决差异很明显——去掉提高5% 所得税的条款，然后提供奶酪。 +

关于委员会还有最后一点需要注意：一般来说，委员会为多数党服务，因为多数党在每个委员会中占据多数席位，而且委员会主席总是来自多数党。好的，现在你已经了解了国会两院的委员会情况，但两院在完成工作时遵循的规则是不同的。 +

众议院的规则规定辩论时间有限，这不难理解为什么会这样。与参议院相比，众议院有大量的众议员，如果每个人都随心所欲地发言，那他们将一事无成。所以众议院将议员的辩论时间限制为一个小时。此外，众议院有一个规则委员会（House Rules Committee），这个委员会权力很大。这个委员会决定哪些法案可以进入众议院进行辩论，这意味着如果这个委员会不允许一项法案通过，那这项法案实际上就夭折了。 +

众议院还有一个独特的委员会，叫做全院委员会（committee of the whole），理论上这个委员会包括所有435名众议员，尽管只需要100名议员就可以召开这个委员会会议。基本上，召开全院委员会会议是一种程序性举措，它放宽了一些辩论规则，以便对法案的修正案进行更快速的审议和辩论。众议院还会使用一种叫做 “解扣请愿”（discharge petition）的方式。所以，如果一项法案被卡在委员会中，而众议院的其他议员希望将其提交众议院进行审议，他们可以通过多数投票将这项法案从委员会中提出，提交众议院进行审议和投票。 +

但参议院完成工作的方式略有不同。在参议院，辩论规则更加宽松，因为参议员人数较少。参议员可以无限制地对法案进行辩论，他们可以利用这一特权通过冗长辩论（filibuster）来拖延一项法案。基本上，冗长辩论是指通过长时间的发言来拖延或否决一项法案。然而，终止辩论规则（cloture rule）是一种让进行冗长辩论的参议员闭嘴的方式。终止辩论需要三分之二的参议员投票同意，也就是说需要60名参议员投票，才能终止冗长辩论并对法案进行投票。要让60名参议员达成一致意见是非常困难的，而且这种情况并不经常发生。 +

好的，参议院还会通过一种叫做 “一致同意”（unanimous consent）的方式来加快立法进程。在开始工作之前，代理参议院议长会询问所有参议员是否同意限制辩论，当然这是一种避免冗长辩论的方式。由于这需要全体一致同意，所以即使有一名参议员反对，也就是所谓的 “搁置”（hold），正在审议的法案就会被拖延。 +

好的，现在我们已经了解了国会两院是如何完成工作的，让我们谈谈一项法案成为法律的基本过程。首先，一项法案需要有人提出，两院的议员都可以提出法案。其次，法案会被分配到一个委员会，在委员会中法案通常会进行一些修改。有时候会增加一些附加条款（riders），这些附加条款基本上是不相关的内容，通常是为了满足某个众议员的议程，或者是为了帮助法案通过。有时候会增加一些政治分肥支出（pork barrel spending），这些资金是为众议员选区的特殊项目预留的。最著名的政治分肥支出事件是 “无实际意义的桥梁” 项目。基本上，有一项法案是为美国驻伊拉克部队提供防弹衣，而一位阿拉斯加州的参议员认为 “没有人会投票反对为美国部队提供防弹衣，所以我们不如在法案中增加4亿美元用于在阿拉斯加修建一座桥梁”。所以，这个过程可能有点不太光彩。 +

不管怎样，在法案经过修改后，它会被提交到整个议会进行投票。在一个理想的世界里，众议员们会根据法案的优劣进行投票，但有时候他们会进行 “互投赞成票”（log rolling）。这意味着众议员们会互相说 “如果你投票支持我的法案，我就投票支持你的法案”。这是一种精心设计的国会内部的 “互相帮助” 机制。但不管怎样，如果法案获得通过，它会被提交给总统签署。 +

在我们继续之前，你可能已经注意到，国会所做的最重要的立法工作之一是通过联邦预算。现在，联邦政府的大部分收入来自所得税，尽管还有其他税收和关税也能带来收入。当到了通过预算的时候，国会必须根据两类支出来分配资金。第一类是强制性支出（mandatory spending），也就是法律要求的支出。这些支出包括社会保障支出等法律规定的支出。其他主要的强制性支出类别包括医疗保险（Medicare）和医疗补助（Medicaid）。强制性支出还包括债务利息支出，而债务利息支出的数额非常巨大。 +

在考虑了强制性支出之后，剩下的支出被称为自由裁量支出（discretionary spending）。所以委员会会就如何使用这些资金进行辩论，而自由裁量支出的最大接受方是支付联邦雇员的薪酬。这可能是常识，但我还是要说：随着强制性支出——也就是福利支出——的增加，自由裁量支出必须减少。当然，这是在假设联邦政府实行平衡预算的情况下。如果联邦政府真的实行平衡预算，那可太有趣了，不是吗？但实际上，可支出的资金总是比实际可用的资金要多，所以有两种方法可以增加自由裁量支出。第一，国会可以提高税收，但人们通常不喜欢这样。第二，国会可以批准增加赤字支出。赤字基本上描述的是预算和可用资金之间的差距，那么这些资金从哪里来呢？答案是借款。 +

好的，关于国会是如何完成工作的，还有一些内容需要讨论。我已经告诉你国会完成工作的机制，但现在让我们考虑一些可能会影响国会工作速度的因素。第一个因素是意识形态分歧。在过去的30年里，共和党变得更加保守，民主党变得更加自由，这种现象被称为政治极化。这使得谈判和妥协变得非常困难，而谈判和妥协对于通过立法来说是至关重要的，所以这经常会导致政策方面的僵局。所以在这种情况下，国会完成工作的最快方式是一个政党在国会两院都占据多数席位，这意味着他们可以在少数党无法干扰的情况下推动立法通过。如果不是这种情况，那么通常需要妥协的事情就会被搁置，从而减缓整个立法进程。 +

当政府出现分裂时，这种减缓的情况可能会更严重，也就是说总统来自一个政党，而国会两院来自另一个政党。例如，在2016年，民主党总统巴拉克·奥巴马（Barack Obama）有机会任命一名最高法院法官，显然他会选择一名自由派法官。但共和党主导的参议院认为，由于这是选举年，他们应该等到总统选举结果出来后再确认新法官的任命。你知道，奥巴马在他第二个任期的最后几个月，这意味着他作为一个 “跛脚鸭” 总统，基本上没有什么权力，因为他即将卸任。所以参议院根本不会举行确认听证会。但在2020年情况就不同了。这也是选举年，共和党总统唐纳德·特朗普（Donald Trump）有机会任命一名新的大法官，而共和党参议院在没有等待选举结果的情况下，迅速通过了确认程序。所以这是一个很好的例子，说明分裂的政府会减缓立法进程，而统一的政府会加快立法进程。 +

好的，影响国会工作效率的另一个因素是，众议员在决定如何投票时对其代表角色的不同理解。一些众议员遵循 “受托人模式”（trustee model），这意味着他们认为自己被赋予了选民的信任，会根据自己的最佳判断进行投票。一个很好的例子是共和党参议员米特·罗姆尼（Mitt Romney）投票支持弹劾唐纳德·特朗普（Donald Trump）。这一投票行为大多数他的选民并不支持，但他是根据自己的最佳判断进行投票的。其他众议员遵循 “代表模式”（delegate model），这意味着这些众议员认为他们必须按照选民的意愿投票，即使这与他们自己的判断相悖。这种模式在众议院更为常见，因为众议员的两年任期使他们对选民更负有责任。还有一些众议员采用 “政治人物模式”（politico model），这种模式基本上是前两种模式的混合。对于采用 “政治人物模式” 的众议员来说，他们如何投票取决于具体情况。例如，如果公众对某个问题有强烈的意见，这些众议员在投票时会考虑到这一点，并且可能会像 “代表模式” 那样进行投票。如果不是这样，他们会像 “受托人模式” 那样进行投票。 +

好的，关于国会工作效率，还有一个问题你需要了解，那就是选区重划（redistricting）和不公正划分选区（gerrymandering）。听起来像是两件事，海姆勒。我知道我在说什么，但它们是相关的。冷静一下。不管怎样，宪法规定每10年必须进行一次人口普查，以了解美国的人口数量和居住地点。然后根据这些信息，每个州的众议员名额会进行分配，接着国会选区会重新划分以反映这些新的名额。所以这里有重新分配（reapportionment），也就是分配众议员席位，还有选区重划（redistricting），也就是重新划分众议员所代表的选区边界。 +

这是一个极具争议的问题，当选区没有得到恰当的重新划分时，情况可能会变得更加激烈，为了理解这一点，我们需要讨论两个最高法院的案例。第一个是1962年的 “贝克诉卡尔案”（Baker vs Carr）。到1962年，田纳西州已经有60多年没有重新划分选区了。在那段时间里，田纳西州的城市人口大幅增长，而农村人口增长则慢得多。这意味着农村选民的投票权比城市选民的投票权大得多，换句话说，少数选民拥有多数权力，而这正是因为选区没有重新划分。在这个案件中，最高法院裁定这种情况违反了宪法第十四修正案的平等保护条款，并且从这个裁决中产生了 “一人一票” 的原则。换句话说，选区的划分必须确保投票权的平等分配。此外，这个案件解决了一个问题，即选区分配问题是否可由法院裁决，也就是说法院是否可以对这类问题做出裁决。如果你不太明白，答案是肯定的，法院可以对选区分配问题做出裁决，因为这是一个宪法问题，而不是政治问题。 +

你需要了解的第二个案例是1993年的 “肖诉雷诺案”（Shaw versus Reno），这个案件与 “贝克诉卡尔案” 类似，因为它也涉及到国会选区的划分，但在这个案件中，法院考虑了仅基于种族划分选区的合宪性问题。为了理解这个案件的结果，你需要了解不公正划分选区（gerrymandering）的概念。基本上，不公正划分选区是一种划分选区的方式，这种方式有点不太光彩，因为选区的划分可以偏袒某一个群体。通常，被不公正划分的选区形状很奇怪，与当地的自然特征完全不符，这样划分选区是为了确保某个政党在该选区具有优势。这就是所谓的党派不公正划分选区（partisan gerrymandering）。但 “肖诉雷诺案” 处理的是另一种不公正划分选区的情况，即种族不公正划分选区（racial gerrymandering），这意味着选区的划分是为了让某些种族在这些选区中占多数。在这个案件中，北卡罗来纳州的两个选区被划分成奇怪的形状，形成了黑人占多数的选区，这实际上意味着这些选区有很大的机会选出黑人官员，这维护了 1965 年《选举权法案》中对历史上受歧视人群的规定。然而，法院裁定，仅基于种族划分选区 —— 即使这有助于历史上受歧视的人群 —— 是一种危险的做法，因此是违宪的。
所以，我长篇大论的重点是向你展示所有这些因素综合起来是如何影响国会履行职责的能力的。好的，讲了这么多，现在让我们继续谈谈行政分支。如果你在听了这么多关于国会的内容后感到疲惫，那就去喝一杯含有足够咖啡因的能量饮料吧。让我们继续。
所以，让我们开始讨论总统如何实施他 —— 或者在未来可能是她 —— 的政策议程。每个总统上任时都有一系列他们希望实施的政策，但你现在应该知道，宪法规定国会有权通过法律，而不是总统。那么总统如何使他的政策议程得以实施呢？嗯，总统可以通过正式权力和非正式权力来实现这一点。
总统的正式权力在宪法第二条中有所规定。现在让我们来谈谈其中的一些权力。首先，总统最重要的正式权力之一是否决权（veto）。正如我之前提到的，如果一项法案要成为法律，总统必须在法案送达总统办公室后的 10 天内签署它。如果一项特定的法律与总统的政策议程不一致，总统可以否决它，这意味着该法案不会成为法律。在这种情况下，会发生三件事。第一，法案被否决，每个人都擦去一滴眼泪，生活继续。第二，法案被送回国会，国会可以对法案进行增减，使其更能让总统接受，如果这样的话，法案必须重新走一遍整个立法程序。因此，当总统威胁要否决一项法案时，这会促使国会在将法案提交总统之前进行进一步的谈判。第三，国会可以以三分之二的票数推翻总统的否决，但这非常困难。
这是正式的否决程序，但总统也可以通过否决权行使非正式权力。一个例子就是我刚才提到的 —— 当总统威胁要否决一项法案时，这会向国会发出一个信号，即他们必须对法案进行修改，使其能被总统签署。总统还可以行使搁置否决权（pocket veto）。“法案一直在我的口袋里”。记住，总统有 10 天的时间签署法案使其成为法律，但如果一项法案与总统的政策议程不一致，并且国会会议只剩下不到 10 天的时间，总统可以对该法案不采取任何行动，让国会会议结束，这样法案就被有效地否决了。另一方面，如果国会会议还有超过 10 天的时间，而总统不签署法案，法案就会成为法律。
总统在外交政策方面也被赋予了正式权力。根据宪法第二条，总统是美国武装部队的总司令（commander-in-chief）。即便如此，要记住总统不能宣战 —— 宣战权属于国会。但这也有点模糊，因为不是每一次部队的部署都等同于宣战。例如，奥巴马总统在 2011 年授权海军海豹突击队击毙奥萨马・本・拉登（Osama bin Laden）。在外交政策方面，总统可以与其他国家的元首达成行政协议（executive agreements）。这不是条约，因为条约的批准权属于参议院，但行政协议更像是总统与其他总统或君主之间的合同。例如，在美国参加第二次世界大战之前，富兰克林・德拉诺・罗斯福（Franklin Roosevelt）总统与英国达成了一项行政协议，美国提供驱逐舰，作为交换，英国将一些海军基地租给美国 99 年。
好的，我已经向你介绍了宪法中规定的总统的一些正式权力，也提到了一些非正式权力，现在让我们直接谈谈这些非正式权力。总统的第一个非正式权力是谈判和说服（bargaining and persuasion）。我们一会儿会更详细地讨论这个问题，但基本上，总统能获得全国的关注，这是其他政治家所没有的，所以总统可以利用这种关注，根据行政政策议程说服民众。
总统的另一个非正式权力是行政命令（executive order），这是总统发布的一项指令，具有联邦法律的效力，但它实际上不是法律。这有点让人困惑，海姆勒。嗯，那让我给你好好解释一下。行政命令主要用于指导联邦官僚机构和军队的行动，而总统对这两个领域都有直接的权力。例如，总统可以通过行政命令将资金从一个官僚机构转移到另一个官僚机构，以实现总统想要完成的事情。例如，唐纳德・特朗普（Donald Trump）的一个核心竞选承诺是在美国和墨西哥边境修建隔离墙，当国会不批准这笔资金时，特朗普宣布进入国家紧急状态，并通过行政命令从几个行政机构转移资金，以便开始修建隔离墙。
总统的另一个非正式权力是签署声明（signing statement）。所以当总统签署一项法案使其成为法律时，总统也可以发布签署声明，告知全国行政分支对该法律的解释，以及总统打算如何执行该法律，而这当然可能与国会对该法律的理解不同。
好的，现在让我们继续讨论总统的政策议程，你应该不会感到惊讶，总统的政策议程可能与政府其他分支的议程发生冲突，特别是与国会的议程发生冲突，更具体地说，与参议院的议程发生冲突。所以总统的权力中包括任命联邦官员的权力，但这些任命必须得到参议院的确认，这可能会导致一些紧张关系。让我给你举一些例子。总统任命了一组顾问，也就是内阁（cabinet）。这些人是各个行政机构的负责人 —— 我们一会儿会详细介绍这些机构 —— 通常情况下，参议院会让这些任命顺利通过，因为他们认为总统应该能够选择自己的工作人员。然而，有些内阁任命会引起激烈的争议。例如，唐纳德・特朗普提名贝齐・德沃斯（Betsy DeVos）担任教育部长，因为她明确表示她将推行教育私有化。这使她在参议院树敌众多。她的确认听证会实际上以平局结束，副总统迈克・彭斯（Mike Pence）—— 他是参议院议长 —— 打破了平局，使德沃斯获得了任命。
总统还任命驻外大使，通常情况下，参议院会顺利确认这些任命，不会有太多争议。白宫工作人员同样由总统任命，但不需要参议院确认。在这一点上，你可能会想 “我还以为这两个分支之间会有紧张关系呢。给我们讲讲那些有争议的事情吧”。好吧，你想要听有争议的事情？那我就给你讲讲。当涉及到联邦法院的提名时，特别是最高法院的提名时，就会出现紧张关系。被任命到最高法院的法官会终身任职，这意味着如果总统任命了一位有利于总统政策议程的法官，这位法官在总统卸任后，在未来的很多年里都可以根据总统的政策议程进行裁决。毫不奇怪，保守派总统会任命保守派法官，自由派总统会任命自由派法官。由于这种任命的长期影响，这会与对立政党的参议员产生不少紧张关系。
现在你应该知道，在美国历史上，总统权力的范围大致扩大了三到四倍左右。回顾第一单元的内容，行政分支权力的扩大正是反联邦党人所担心的事情。事实上，他们认为宪法所规定的总统权力无异于君主制的雏形。但是听着，我看到那边有一份重要的文件。那就是《联邦党人文集》第 70 篇（Federalist 70），在这篇文章中，汉密尔顿认为，一个单一的行政机构是必要的，因为一个人能够在需要坚定领导和战术决策的事务上迅速而果断地采取行动。此外，汉密尔顿认为，行政分支的权力可以受到其他两个分支的制约，所以一个像君主一样的总统是不可能出现的。最后，如果你想知道总统是否会滥用权力，你应该知道，一个单一的行政机构的权力会受到更密切的监督，因为与多个行政机构相比，一个单一的行政机构更容易被发现滥用权力的行为。最终，正如你已经知道的，汉密尔顿的观点占了上风。
但即便如此，正如我提到的，随着时间的推移，总统的权力显著增加。乔治・华盛顿（George Washington）以及他之后的前五位总统基本上都听从国会的议程，因为国会是人民的代表。华盛顿甚至在两届任期后卸任，以消除人们对一个专横的行政机构的担忧。记住，在华盛顿那个时代，对总统的任期没有限制。后来，宪法第二十二条修正案（22nd Amendment）对总统任期进行了限制，但华盛顿开创了总统任期为两届的先例。
但是，在安德鲁・杰克逊（Andrew Jackson）担任总统期间，总统权力发生了重大转变。他认为总统是人民的代表，而不是国会，因此他扩大了行政办公室的权力以体现这一点。一个典型的例子是最高法院裁定，行政分支迫使切罗基印第安人（Cherokee Indians）离开他们在佐治亚州的土地是违宪的，但杰克逊还是这么做了，因为在他看来，这是人民想要的。
亚伯拉罕・林肯（Abraham Lincoln）总统进一步扩大了总统权力。他承担的权力比他之前的任何一位总统都要多，而且人们通常原谅了他，因为他要打内战。最著名的是，他暂停了人身保护令（habeas corpus）的宪法权利，这意味着他可以在不给予审判的情况下下令逮捕人们。
如果说有哪位总统扩大了行政权力，那就是我们所说的富兰克林・罗斯福（Franklin Roosevelt）总统。他使用否决权达 635 次。听着，如果你不知道的话，这可是很多次了。就像安德鲁・杰克逊在他的任期内使用了 12 次否决权 —— 这比他之前的所有总统使用否决权的次数加起来还要多。所以富兰克林・罗斯福使用否决权 635 次，我只能说 “哇”。至少可以说，他是一位精力充沛的行政长官。他推动国会通过了他的新政（New Deal）计划，以应对大萧条（Great Depression）的破坏性影响 —— 这些计划包括社会保障、最低工资法和公共工程项目。此外，富兰克林・罗斯福担任了不少于四届总统。公平地说，他在第四届任期的第一年去世了，但不管怎样，他被选举了四次。所以当我们谈论联邦权力的扩大时，实际上是富兰克林・罗斯福给我们带来了 “大政府”。
好的，现在让我们谈谈总统的沟通方式，总统有一个其他分支所没有的优势，那就是能获得全国人民的关注，优秀的总统会利用这种关注为自己谋利。总统沟通的术语来自西奥多・罗斯福（Teddy Roosevelt），他说总统职位是一个 “天字第一号讲坛”（bully pulpit）。这里的 “bully” 这个词的意思和现在不同 —— 它的意思是 “极好的”。换句话说，罗斯福很喜欢这样一个事实，即他可以直接向人民讲话，而且希望人民反过来向他们的代表施压，使代表们按照罗斯福的议程进行立法。总统这样做的主要方式之一是通过向国会发表年度国情咨文（state of the union address）。
随着技术的进步，总统 “天字第一号讲坛” 的效力也发生了变化。在很长一段时间里，总统发表国情咨文，而这些咨文会通过报纸编辑进行传播。但是随着广播的出现，富兰克林・罗斯福发现他可以直接向人民讲话，而不需要任何中间媒介，他通过广播发表了著名的 “炉边谈话”（fireside chats），用简单的语言解释他的政策提案。约翰・F・肯尼迪（John F. Kennedy）是第一位使用电视这种新媒体举行现场新闻发布会的总统，正是在这个时候，总统沟通办公室成立了，该办公室致力于完善和塑造总统的谈话要点，以便总统的政策议程能够赢得人民的支持。然后随着社交媒体的出现，“天字第一号讲坛” 又有了新的形式。这是总统沟通方面的一项重大创新，因为现在总统有了一种方式，可以在没有中间媒介的情况下，按照自己的意愿随时向人民讲话。巴拉克・奥巴马（Barack Obama）将社交媒体作为赢得他第一次竞选的关键，他通过社交网站直接与他的支持者进行沟通。毫不夸张地说，唐纳德・特朗普在这一创新的基础上更进一步。他对传统新闻媒体深感怀疑，并使用推特（Twitter）作为他的 “天字第一号讲坛”，每天多次就立法、他的政治敌人和外交事务发表评论。事实上，特朗普经常使用推特平台，他因此获得了 “推特总司令” 的绰号。
好的，现在让我们谈谈司法分支。我们将从法院的结构开始讲起，然后讨论它如何制衡其他分支。就联邦法院系统的结构而言，有三个层级。最底层是美国地方法院（U.S. district courts），全国共有 94 个地方法院。这些法院拥有 “初审管辖权”（original jurisdiction），这意味着它们有权首次审理案件。下一级是美国巡回上诉法院（U.S. circuit court of appeals），共有 12 个巡回上诉法院。它们拥有 “上诉管辖权”（appellate jurisdiction），这意味着它们审理来自下级法院的上诉案件。而位于联邦法院系统顶端的是最高法院（Supreme Court），最高法院根据案件的类型同时拥有初审管辖权和上诉管辖权。
最高法院是这些法院中唯一在宪法中明确提及的法院，宪法第三条对其进行了规定。我刚才提到的其他法院是根据 1789 年的《司法法》（Judiciary Act of 1789）由国会设立的。你可能不知道，与最高法院相关的还有一份重要的文件，那就是《联邦党人文集》第 78 篇（Federalist 78）。在这篇文章中，汉密尔顿认为，司法分支的独立性是对其权力的一种保护。法院的这种独立性从何而来呢？嗯，来自法官的终身任命。如果法官不对选民负责，这意味着他们可以在不受竞选连任压力的情况下对案件做出裁决。汉密尔顿还认为，法院拥有司法审查权（judicial review），这意味着法院的职责是判定法律是否符合宪法。正是通过这种权力，最高法院有权制衡政府的其他分支。
这种权力在宪法中并没有明确提及，这就是 1803 年 “马伯里诉麦迪逊案”（Marbury versus Madison）的重要性所在。我不会详细讲述这个案件的所有细节，但你真正需要记住的是，正是法院在这个案件中的裁决，巩固了最高法院的司法审查权，这极大地增加了最高法院的权力。在宪法中，最高法院有点像史蒂夫・罗杰斯（Steve Rogers，美国队长）试图报名参军时的情况，但在 “马伯里诉麦迪逊案” 之后，最高法院就像史蒂夫・罗杰斯从那个容器中出来一样，肌肉发达，充满力量。
好的，现在让我们谈谈法院在审理案件时的工作方式。先例（precedence）的作用极其重要。所以当一项裁决被下达时，它会创造一个先例，这意味着除非有非常特殊的情况，否则这项裁决将作为未来裁决的约束性模板。你知道，先例很难被推翻，因为法院遵循 “遵循先例”（stare decisis）的原则，这个原则的意思是 “让裁决保持不变”。所以如果法院收到一个与已经裁决的案件相关的案件，它通常会按照之前的案件进行裁决。然而，尽管这种情况很少见，但先例是可以被推翻的，例如在 “布朗诉教育委员会案”（Brown versus the board of education）中 —— 我们会在第三单元详细讨论这个案件。
与下级法院相比，最高法院对先例的遵循程度较低，但即便如此，先例仍然在很大程度上指导着当前的裁决。当涉及到维持或推翻先例时，法院的活动可以分为两种情况：司法能动主义（judicial activism）和司法克制主义（judicial restraint）。司法能动主义的观点是，法院不仅考虑裁决的合宪性，还会考虑裁决对社会的更广泛影响，以此来制定政策。“布朗诉教育委员会案” 就是一个重要的例子，法院的能动主义可以是自由派的，也可以是保守派的。
好的，在另一个极端是司法克制主义，其观点是法官认为他们不是被任命来制定政策的 —— 因为民选的立法机构才是负责制定政策的。如果法官遵循司法克制主义，他们认为只有当一项法律违反了宪法的实际文字规定时，才应该被推翻。
然后，法官的意识形态在法院做出裁决的过程中也起着作用。总统会任命与自己政治立场一致的法官，这会影响法院是继续遵循先前的先例，还是创造一个新的先例。例如，自 20 世纪 70 年代以来，保守派总统会任命保守派法官进入最高法院，希望推翻 “罗诉韦德案”（Roe v. Wade）所确立的先例，因为 “罗诉韦德案” 使堕胎在全美 50 个州合法化。到目前为止，这种努力还没有成功，但它说明了意识形态在法院裁决中所起的作用。
现在，听到法院行使司法审查权时，某些美国群体可能会质疑法院权力的合法性，这可能并不让你感到惊讶。特别是当法院做出有争议的裁决时，这种情况尤其会发生。
例如，在 1857 年具有里程碑意义的 “德雷德・斯科特诉桑福德案”（Dred Scott v. Sandford）中，法院基本上裁定奴隶制在所有州都是合法的。如果你了解美国历史，你就会知道，在 1857 年，这个国家因为奴隶制问题而四分五裂。所以，当法院做出这个裁决时，许多废奴主义者和反奴隶制的斗士都对最高法院的合法性提出了质疑。比如说，这些未经选举产生的法官怎么能推翻那些使北方没有奴隶制的立法呢？
当法院做出裁决时，它实际上就成为了国家的法律。但是其他分支也有一些方法可以减少这些裁决的影响。总统可以在有机会时任命新的法官。例如，我刚才提到的 “罗诉韦德案”。福音派基督徒长期以来一直试图推翻这个裁决，在2016年的选举中，他们这么做的主要方式就是选举唐纳德·特朗普。当被问及为什么投票给一个其道德观念与基督教相悖的人时，他们的回答是：“为了法院的提名。”

总统还可以通过不执行裁决来减轻法院裁决的影响。例如，法院裁定联邦政府将切罗基基督徒从他们在佐治亚州的土地上赶走是违宪的，但安德鲁·杰克逊还是这么做了。

此外，国会也可以通过立法来制衡司法分支。例如，国会通过了宪法第十三修正案，废除了奴隶制，从而使 “德雷德·斯科特案” 的裁决无效。国会还通过了第十一修正案，限制了法院的管辖权，从而限制了最高法院可以审理的案件类型。

有了这些内容，是时候进入这个视频的最后一部分，谈谈联邦官僚机构了。

现在，官僚机构不是政府的一个独立分支，尽管有时人们会把它称为 “政府的第四分支”。从技术上讲，官僚机构隶属于行政分支，它由数百万受雇来履行联邦政府职责的人组成。

那么，我们为什么不从讨论官僚机构的结构开始，然后看看它是如何开展工作的呢？

在结构方面，官僚机构的最高权力属于内阁部长（cabinet secretaries）。这些人是15个行政部门的负责人，比如能源部（Department of Energy）、国土安全部（Department of Homeland Security），或者最大的部门——国防部（Department of Defense）。然后，这些部门又进一步细分为各个机构，这些机构共同努力实现部门的目标。

例如，财政部（Department of the Treasury）内部有各种税收征管机构，比如美国国税局（Internal Revenue Service，IRS）。所以，这个过程是这样的：国会通过税收立法，然后这些机构负责确保税收的征收。

官僚机构结构的另一部分是委员会（commissions）。这些是监管团体，它们在一定程度上独立于总统的权力，但仍然隶属于行政权力。它们由一个委员会管理，通常是为了特定目的而设立的。例如，联邦通信委员会（Federal Communications Commission，FCC），它负责监管媒体内容——不是通过审查言论自由，而是确保没有不当内容被展示。

官僚机构结构的还有一部分是政府公司（government corporations），它们有点像企业和政府机构的混合体。基本上，当政府想要提供一种公共产品，但自由市场是提供这种服务的最佳方式时，政府就会收购企业。一个很好的例子是美国公共广播公司（PBS），它制作教育媒体。

现在，说到官僚机构的实际工作，它们是这样做的。

首先，它们制定并执行法规。但重要的是要记住这里的区别：官僚机构不负责制定法律。制定法律是国会的职责。官僚机构只是制定一套更细化的规则，以帮助执行法律。

例如，第十六修正案确立了所得税，但对于如何征收所得税并没有规定。是美国国税局决定了纳税截止日期是4月15日，以及我们应该如何纳税。所以，这就是所谓的 “委托自由裁量权”（delegated discretionary authority）。根据定义，这是国会赋予官僚机构的权力，使它们能够自行决定如何制定规则和执行法律。

这种权力的另一部分是合规监测（compliance monitoring），这意味着官僚机构为某些行业制定规则，然后要确保这些行业遵守这些规则。现在，这样做可能会减缓政策的实施，但另一种选择是监管不力，这基本上会使它们制定的法规失去效力。

官僚机构的第二项工作是在法律被违反时处以罚款。

第三，机构负责人经常要在国会作证——要么为他们的行为负责，要么汇报他们机构的工作进展。

现在，这些官僚机构经常与其他实体密切合作，我想提一种你真的需要了解的关系，那就是 “铁三角”（iron triangle）。“铁三角” 的三个点分别是官僚机构、国会委员会（congressional committees）和利益集团（interest groups）。这些团体经常合作，相互依赖以制定政策。

官僚们向国会委员会提供专业知识，他们渴望与国会委员会合作，因为国会决定他们部门的资金分配。而委员会成员需要关注利益集团，因为利益集团通常有政策专家，这些专家可以告知委员会某些政策的影响。然后，利益集团可以为国会竞选提供资金。

由于这种互利关系，这三者之间的关系变得非常牢固。这就是为什么它被称为 “铁三角”——而不是 “煮过头的面条三角”，因为，你知道，煮过头的面条很弱，在结构上支撑不了多少东西。你懂的，用它来比喻牢固的关系可不是个好比喻。

不管怎样，为了你的考试，你需要知道这些官僚部门中七个部门的名称和目的。我不会告诉你这些部门的所有职责；我只会给你举几个例子。

第一个是国土安全部（Department of Homeland Security），它负责保护美国免受恐怖主义威胁，并管理和控制国家的边境。

第二个是交通部（Department of Transportation），它管理各种交通事务，比如高速公路和航空旅行。

第三个是退伍军人事务部（Department of Veterans Affairs），它管理退伍军人医院，并负责美国退伍军人的总体福利。

第四个是教育部（Department of Education），它监督各州对联邦教育标准的实施。

第五个是环境保护署（Environmental Protection Agency），它通过工业监管来保护环境和人类健康。

第六个是联邦选举委员会（Federal Elections Commission），它管理和执行竞选资金法。

第七个是证券交易委员会（Securities and Exchange Commission），它监管股票市场并防止欺诈。

现在，这些实体的所有领导都是由总统任命的。如果官僚机构的行为与总统的政策议程不太一致，总统可以解雇他们，并任命新的内阁和机构领导——不过总统不能解雇监管委员会的负责人。

而且，毫不奇怪，总统会试图让那些支持行政目标的人担任这些职位。即便如此，委员会负责人的任期是固定的，并且会跨越多个总统任期。所以，虽然总统对这些实体有很大的影响力，但总统的影响力并不是绝对的。

所以，我刚才列出的所有这些部门、机构和委员会，以及其他数百个部门，基本上构成了行政分支的执法机构。但它们在这方面的权力仍然会受到政府其他分支的制衡。

因为国会负责确保法律按照其通过的方式得到执行，所以国会可以举行委员会听证会，以确保法律的执行情况。国会有许多与官僚机构的各个机构相对应的委员会，这些委员会会传唤这些机构的负责人作证，并汇报他们的工作进展。有时候，这只是一次友好的检查；而有时候，听证会会很紧张。

但国会还有另一种制衡官僚机构的方式，那就是国会掌控着资金。通过财政权力（power of the purse），国会可以决定如何向不同的机构分配资金。在委员会或小组委员会授权之前，机构不能使用资金。

总统也可以制衡官僚机构，而且这通常是第一道防线，因为官僚机构隶属于总统的权力范围。例如，比尔·克林顿总统发起了一项全国绩效评估（National Performance Review），要求各个机构进行审查，必要时改变其使命和目标。

你不会认为司法分支会错过这种权力制衡的乐趣吧？当公民认为官僚机构的决定违宪时，他们可以在法院对这些决定提出质疑。而且通常情况下，除非这些机构公然违反法律，否则法院会支持这些机构的权力。

随着时间的推移，官僚机构的合法性也受到了质疑，特别是关于它的独立性。这些机构和委员会制定的规则和法规具有法律效力，但你肯定知道，这些机构的成员不是民选代表，因此不对人民负责。这让美国民众感到不满。

你还需要知道，随着时间的推移，选择在官僚机构工作的人的方式也发生了变化。在美国历史的头一百年左右，人们通过 “政治分赃制”（patronage system）获得官僚机构的工作，这意味着这些工作是总统奖励那些支持他竞选的人的一种方式。

这种制度存在了很长时间，但当加菲尔德总统被暗杀后，这种制度就出问题了。基本上，加菲尔德没有给一个支持他竞选的人安排官僚机构的工作，所以那个人就开枪暗杀了总统。所以，显然在这方面需要进行改革。

改革确实进行了。加菲尔德总统被暗杀后，国会在1883年通过了《彭德尔顿公务员法》（Pendleton Civil Service Act），该法案创建了一个基于功绩的公务员任命制度。所以现在，要得到一份诱人的官僚机构工作，你必须通过竞争性考试。

这种改革在20世纪继续进行，以使官僚机构更加专业、专门化和中立。例如，在吉米·卡特总统的政府时期，通过了《公务员制度改革法》（Civil Service Reform Act），该法案维护了基于功绩的制度，但进行了进一步的改革，为女性提供了更广泛的机会，对人力资源部门进行了更有效的控制等等。

就是这些了。天哪，这个单元的内容可真多，但我希望这对你有帮助。如果你想在课堂上得A，在五月份的考试中得5分，你可以点击这里获取终极复习资料包。

如果这个视频对你有帮助，并且你希望我继续制作这样的视频，那就订阅吧。

海姆勒（Heimler）下线啦。


'''

== pure


hey there and welcome back to heimlich's history. now in this video i'm going to take you through everything you need to know about unit 2 of ap government and oh baby is this one a beast. so get them brain cows ready for milking because we have no time to waste. let's get to it.

so unit 2 is all about the three branches of government and how they interact with each other. we're gonna start by talking about the legislative branch, then we'll move on to the executive branch, and then we'll talk all about the judicial branch. but we'll also talk about that kind of unofficial fourth branch of government, namely the bureaucracy. hmm, you smell that? that smells like learning and it smells good.

you should know that this video is part of my review packet which has exclusive video content, all the practice questions your little heart could desire, essential course questions and answers, and basically everything you need to do well in this course and on your exam in may. you know, if you're into that kind of thing. to get that, clicky finger out and have at it.

okay, let's begin with the legislative branch which is to say congress, which is the law making branch of the government. structurally congress is made up of two houses and the word for that is bicameral. that means in order to pass a bill, two camels are required to spit upon the legislation and that's how laws are made. that's not how laws are made, but now i'm wondering if i even want to live in a country where laws are not made that way. anyway, congress is made up of two houses and the first is the house of representatives. in this house, representatives are apportioned by the population of each state. more populous states have more representatives and vice versa.

now representatives in the house are more closely tied to the people whom they represent for two reasons. first, they only serve two-year terms and that means that they better listen to the people who elected them because in two years they have to go right on back and ask them for another term. second, because a state is made up of in most cases many districts, house members represent fewer people and thus are able to know their constituency better. just for poops and giggles, you should probably know that there are 435 representatives that make up the house.

the second house of congress is the senate. there are 100 senators because each state gets two. if this history teacher has his math right, that means we have approximately 50 states. now senators serve for six years and have a few more constitutional responsibilities than do members of the house, and i'll talk more about those in a minute. but because those senators represent an entire state, they are all things being equal going to be less connected to the intimate details of their constituency than house members.

taken together, both houses of congress are required to pass legislation. they must agree on identical versions of the bills and then pass them on to the president for signing. now you should know that in doing this work of legislation, coalitions are formed in order to make the process more efficient. these coalitions are formed in both houses, but the durability of the working relationships are affected by term length differences. senate coalitions tend to be longer lasting and more durable while house coalitions can change more often, even though re-election rates tend to be high.

now let's talk about where congress gets its power and for that you need to know two terms: enumerated powers and implied powers. enumerated powers are those powers explicitly listed in article 1 section 8 of the constitution. the enumerated powers of congress include but are not limited to federal funding, foreign policy and military legislation. now under the heading of funding, congress has the power to raise revenue through taxation, coin money for a uniform currency throughout the nation, and pass a federal budget. under the heading of foreign policy and military legislation, congress has perhaps the most important and far-reaching foreign policy decision and that is to declare war. to that end, congress can raise armies, pass draft laws and direct funding to the armed forces.

okay, so those are some of the enumerated powers that congress holds, but they also have implied powers. this basically means that congress can pass any law that is required by the enumerated powers. and the justification for these powers comes at the end of article 1 section 8 and it's known as the necessary and proper clause, also known as the elastic clause. by this power, congress can pass a wide range of legislation addressing economic, environmental and social issues even if they're not explicitly mentioned in article 1 section 8. for example, alexander hamilton used the necessary and proper clause to argue for the establishment of a national bank. article 1 section 8 says that congress can raise funds through taxation -- so you know that's an enumerated power -- but it says precisely nothing about congress having the authority to establish a bank. however, hamilton argued that if the federal government is going to be raising money, it was necessary and proper to establish a bank. so his argument was that the need for a bank was implied by the power for raising taxes.

okay, now let's talk about the leadership structures in congress and we'll start with the house. the constitution only mentions one leader for the house and that's the speaker of the house, and basically all it says is that the house members will choose this leader. now the speaker will always be a member of the majority party -- not because that's what the constitution mandates, but because this leader assumes his or her position by a vote and the majority party isn't going to vote for somebody in the minority party. now the speaker has significant power from recognizing who can speak and who cannot, to assigning representatives to committees.

now under the speaker are the majority and the minority leaders, and they basically direct debates and guide their party members in policy-making issues. then you have the whips, one each for the majority and minority parties, and whips are exactly what they sound like. like if representatives are a bunch of livestock, then the whips get in there and make sure that their party is moving in the same direction. if a party member steps out of line, so whips render party discipline and make sure members of the party walk in line with the party goals.

then over in the senate you have a somewhat different leadership structure. there are two senate leaders mentioned in the constitution and the first is the president of the senate, and that privilege falls to the vice president of the united states. now the vice president is a non-voting member of the senate unless there's a tie, and then the vice president can vote. the second senate leader mentioned in the constitution is the president pro tempore, commonly known as the president pro tem. this is the most senior member of the majority party and has the authority to act as president of the senate when the vice president is not present, which in modern times is a lot.

okay, the next rung down on the leadership structure is the senate majority leader, which is in practice much more powerful than the president and the president pro tem. this person sets the legislative agenda by determining which bills reach the floor for debate and which ones do not. and then finally you have the whips who function the same way in the senate as they do in the house.

okay, so that's the basic leadership structure. now let's talk about how these representatives get their legislative work done, and in both houses most of the work is done in committees. now committees are not required by the constitution but they're more of a practical necessity. essentially there's small groups of representatives who can debate and draft precise legislation that would otherwise be impossible in the large group setting.

now there are four kinds of committees you need to know about. first, standing committees which are committees that endure for a long time. for example in the senate you have the standing committee on the budget and in the house you have the house judiciary committee. both of these are permanent committees because they do work that always needs to be done from congressional session to congressional session. it's standing committees where new legislation begins and most bills never make it past that stage.

second, you have joint committees which are groups that have members from both the house and the senate. an example of this is the joint committee on the library of congress. third, you have select committees which are temporary and created for a specific purpose -- like they're basically the opposite of standing committees. for example, a select committee was formed to investigate president richard nixon's watergate scandal, and when that was done the committee was dissolved.

and fourth, you have conference committees. now to understand the purpose of these committees you have to realize that if a bill is going to become a law, the bill must be passed by both houses in identical form. so if the house passes a bill to raise income tax by five percent and the senate has the same bill but added a provision to provide every american household with a five gallon tub of nacho cheese per month, well then they have to go into a conference committee and work out the difference. in that case i think it's obvious how to work it out -- get rid of the five percent and give us the cheese.

now one last note about committees: generally they serve the goals of the majority party since they hold a majority of seats on each committee, and the committee chair is always from the majority party. okay, now all the committees i just mentioned are found in both the house and the senate, but each house has different rules that they follow for getting their work done.

house rules mandate limited debate, and that's not hard to understand why. like compared to the senate, the house has a metric butt load of representatives and if everyone talked as long as they wanted to, they'd never get anything done. so the house limits its members to one hour for debate. additionally, the house has the house rules committee which wields an awful lot of power. this committee is the one that decides which bills make it to the floor for debate, which means that if this committee doesn't allow the bill through, it effectively dies.

the house also has a unique committee called the committee of the whole which theoretically includes all 435 representatives, although only a quorum of 100 is required to call this committee. basically calling the committee of the whole is just a procedural move that relaxes some of the rules for debate so that amendments for bills can be considered and debated more quickly. and the house also makes use of what's called a discharge petition. so if a bill gets stuck in a committee and the rest of the house wants to bring it out for consideration, they can muster a majority vote which will bring that bill out of the committee and into the house for consideration in voting.

but the senate has a slightly different way of getting its work done. in the senate the rules for debate are much more relaxed because there are less members in the senate. representatives can have unlimited time to debate bills, and one way that they can use that privilege to slow down a bill is by using the filibuster. basically this is an attempt to stall or kill a bill by talking for a very long time. however, the cloture rule is a way to get a filibustering senator to shut it. it requires a two-thirds vote, which is to say 60 senators, to shut down the filibuster and to bring the bill to a vote. now getting 60 senators to agree on this is a very difficult thing and it doesn't happen that often.

okay, so the senate also gets this work done through something called unanimous consent as a way of speeding legislation along. before they get to work, the acting senate president asks all the senators if they will agree to limit debate, and of course this is a way of avoiding the possibility of a filibuster. and since it requires unanimous agreement, even one senator can object which is called a hold, and thus the bill under consideration can be stalled.

okay, now that we understand how each house of congress gets its work done, let's talk about the basic process of how a bill becomes a law. first, the bill has to be introduced and a member from either house can do that. second, a bill is assigned to a committee and there it often undergoes some changes. sometimes riders are added which are essentially non-relevant additions which will usually benefit a representative's own agenda, or alternatively it could be something added to help get the bill passed. sometimes pork barrel spending is added which are funds earmarked for special projects in a representative's district. and probably the most well-known occasion of pork barrel spending became known as the bridge to nowhere. basically there was a bill introduced to provide body armor for u.s. troops in iraq, and an alaska senator thought "you know nobody in their right mind is going to vote against body armor for u.s. troops, so why don't we go ahead and add 400 million dollars for alaska in there to build a bridge." so you know, the process can be a little sleazy.

anyway, after the bill is marked up and amended, it comes back to the whole group where they vote on it. you know, in a perfect world representatives would just vote on the merits of a bill, but sometimes folks engage in log rolling. this just means that representatives agree and say to each other "hey if you vote for my bill, i'll vote for yours." it's an elaborate system of congressional back scratching. but regardless, if the bill gets a thumbs up then it heads to the president's desk for signing.

now before we move on, as you probably mentioned that arguably the most important legislative work done by congress is passing a federal budget. now most of the federal government's income is gathered from income taxes, although there are other taxes and tariffs that generate income as well. and when it comes time for passing a budget, congress has to allocate funds according to two categories. first is mandatory spending, which is spending that is you know mandatory. these are payments required by law, especially with respect to entitlement spending. for example, congress passed the social security act and that means that they have to make those payments to retirees by law. other big entitlement spending categories include medicare and medicaid. and mandatory spending also includes interest payments on debt, of which there is a metric butt load.

now after mandatory spending is accounted for, everything that's left over is called discretionary spending. and so committees debate how to use these funds, and the biggest recipient of discretionary spending by far is paying federal employees. now this is probably common sense but i'll say it anyway: as mandatory spending -- otherwise known as entitlement spending -- increases, discretionary spending must decrease. that is of course assuming that the federal government operates on a balanced budget. wouldn't that be hilarious if they did that? no, there are always more opportunities to spend money than there is money available, so there are two ways to increase discretionary spending. first, congress can raise taxes and people generally don't like that. second, congress can approve an increase in deficit spending. the deficit basically just describes the gap between the budget and the funds available, and where does that money come from? they borrow it.

okay, now there is still more to talk about regarding how congress gets its work done. i've given you the mechanics of how they get their work done, but now let's consider some of the factors that might slow down or speed up how they get their work done. factor number one is ideological divisions. over the last 30 years, republicans have become more conservative and democrats have become more liberal, which is a phenomenon called political polarization. this makes negotiation and compromise -- which are essential for passing legislation -- very difficult and often leads to gridlock regarding policy. so the quickest way for congress to get things done in this atmosphere is for one party to have a majority in both houses of congress, which means they can just push their legislation through without an occasion for the minority to interrupt it. if that's not the case, then generally anything that requires compromise gets stuck and slows the whole machinery down.

that slowdown could be even worse when we have a divided government, which is to say the president is from one party and both houses of congress are from another. for example in 2016, president obama -- a democrat -- had the occasion to appoint a new judge to the supreme court, and obviously he's going to choose a liberal judge. but the republican-dominated senate argued that since it was an election year, they should wait to see who would win the presidency before they confirmed a new judge. you know, obama was serving in the last months of his second term which made him a lame duck president, which basically means that he had very little power to do anything since he was on his way out of office. so the senate simply wouldn't hold a confirmation hearing. but the situation was very different in 2020. that also was an election year and republican president donald trump had the occasion to appoint a new justice, and the republican senate rushed the confirmation through without waiting on the outcome of the election. so here you have a very good example of how a divided government can slow things down and how a unified government can speed things up.

alright, another factor that affects the efficiency of the work that congress does is the different conceptions of their representative role in determining how they vote. some representatives follow the trustee model, which means they believe that they have been entrusted with the people's faith to vote according to the representative's best judgment. a good example of this is republican senator mitt romney's vote to remove donald trump from office. this was a move that the majority of his constituency did not support, but he voted according to his best judgment. other representatives follow the delegate model, which means that the representative believes that he or she must vote with the will of the people even if it goes against their own better judgment. you find this model more in the house since their two-year terms make them more accountable to the people. and then still other representatives adopt the politico model, which is basically just a blend of the other two. for the politico, how they vote depends on the situation. like if there is a strong public opinion on an issue, the politico will consider that when voting and may act like a delegate. if not, they will vote like a trustee.

okay, now there's one more issue that you need to know with respect to the efficiency of congressional work and that is redistricting and gerrymandering. that sounds like two things, heimlich. i know what i said, but they're related. cool off. anyway, the constitution says that every 10 years a census must be taken to find out how many people live in the united states and where they live. then based on that information, the number of representatives for each state is apportioned to reflect the population, and then congressional districts are redrawn to reflect those new seats. so you've got reapportionment which is the doling out of representative seats, and then you have redistricting which is the redrawing of boundaries that those folks represent.

so this is a highly contentious issue and things can get even more heated when districts are not reapportioned properly, and to understand that we need to talk about two required supreme court cases. first is baker vs carr in 1962. so by 1962 tennessee had not redrawn its districts for over 60 years. in that time the urban populations of tennessee had exploded while the rural populations had grown much slower. that meant that rural citizens had much more voting power than urban citizens, or to say it another way, a minority of voters had a majority of the power precisely because districts had not been redrawn. so in this case the supreme court ruled that such a situation violated the equal protection clause of the 14th amendment, and out of this decision we got the one person one vote principle. in other words, districts must be drawn in order to evenly distribute voting power. additionally, this case settled the question about whether apportionment issues are justiciable, which means whether or not the court can rule on such questions. in case you're not following, the answer is yes, the court can rule on apportionment issues because it is a constitutional issue not a political issue.

the second case you need to know is shaw versus reno in 1993, which was similar to baker versus carr in that it dealt with the drawing of congressional districts, but in this case it considered the constitutionality of drawing those districts based on race alone. now in order to understand the outcome of this case you need to understand the concept of gerrymandering. basically this is a way of drawing districts and it's a little sleazy because districts can be drawn to favor one group over another. usually gerrymandered districts are drawn in weird shapes which don't correspond at all to the natural features of the landscape, and they're drawn that way to ensure that a certain party has the advantage in that district. and that is what's known as partisan gerrymandering. but shaw versus reno dealt with a different kind of gerrymandering known as racial gerrymandering, which means districts are drawn so that certain races constitute the majority in those districts. so in this case, two districts in north carolina were drawn with strange shapes and created majority black districts which actually meant that these districts had a very good chance of electing black folks to office, thus upholding the provisions of the voting rights act of 1965 for historically discriminated people. however, the court ruled that drawing this district solely based on race -- even if it helped historically discriminated people -- was a dangerous practice and thus unconstitutional.

so the point of everything i just said at length is to show you how all of these factors taken together affect how well congress is able to do its job. okay, that was a lot, but let's keep going and talk now about the executive branch. if you're weary after all that talk about congress then go get yourself one of those energy drinks that have enough caffeine to kill a small horse. let's continue.

so let's begin talking about how a president can implement his or -- in the future perhaps her -- policy agenda. now every president comes into office with a set of policies that they want to see enacted, but as you know by now, it is congress that has constitutional authority to pass laws, not the president. so how does the president get that policy agenda enacted? well, through formal powers and informal powers.

the president's formal powers are laid out in article two of the constitution. now let's talk about a couple of them. first and maybe most important of the president's formal powers is the veto. as i mentioned before, if a bill is going to become a law then the president must sign it within 10 days of its arrival on the executive desk. if a particular law is not in line with the president's policy agenda then the president can veto it, which means the bill will not become a law. at that point three things can happen. number one, the bill dies, everyone wipes a single tear off their face and life goes on. two, the bill is sent back to congress and they can add or subtract items from the bill to make it more palatable to the president, and if that happens that means that the bill would have to start over completely and go through the entire process again. and thus when a president even threatens a veto, it incentivizes congress to negotiate further before sending the bill to the presidential desk. three, congress can override a presidential veto with a two-thirds vote, which is very difficult to do.

now that's the formal veto process, but the president can also exercise informal powers with the veto. an example of this is what i just mentioned -- like the president threatens to veto and so that sends a signal to congress that they have to work the bill into something that the president can sign. the president can also employ the pocket veto. "it was right there in my pocket all along." remember that the president has 10 days to sign the bill into law, but if a bill shows up that does not align with the president's policy agenda and there are less than 10 days left in the congressional session, the president can do nothing with it, let the session expire, and the bill is effectively vetoed. on the other hand, if there are more than 10 days left in the session and the president does not sign it, the bill then becomes a law.

now the president is also given formal powers with respect to foreign policy. according to article 2, the president is the commander-in-chief of the united states armed forces. even so, remember that the president can't declare war -- that power belongs to congress. but that can get a little murky because not every deployment of troops equals a declaration of war. for example, president obama authorized navy seals to kill osama bin laden in 2011. now with respect to foreign policy, the president can enter into executive agreements with other heads of state. this isn't a treaty since treaty ratification is a power belonging to the senate, but more like a contract between a president and another president or monarch. for example, before the u.s. entered world war ii, president roosevelt made an executive agreement with britain to provide u.s. destroyers in exchange for 99-year leases on certain uk naval bases.

okay, now i've given you some of the formal powers of the presidency laid out in the constitution and have dabbled in some of the more informal powers, but now let's talk directly about those informal powers. the first informal power of the president is bargaining and persuasion. we'll talk more about this in a moment, but essentially the president has the nation's attention in a way that no other politician does, so the president can use that attention to persuade the people according to the executive policy agenda.

another informal power is the executive order, and this is a directive from the president that has the force of federal law but it's not actually a law. that's confusing, heimler. well then let me explain it up real nice to you. mainly executive orders direct the actions of the federal bureaucracy and the military, which are both areas the president does have direct authority over. for example, by executive order the president can move money from one bureaucratic agency to another in order to get done what the president wants to get done. for example, one of donald trump's central campaign promises was to build a wall on the u.s.-mexico border, and when congress wouldn't approve that funding, trump declared a national emergency and by executive order moved money from several executive agencies so that the work could begin.

another informal power of the president is the signing statement. so when signing a bill into law, the president can also issue a signing statement which informs the nation how the executive branch interprets that law and thus how the president intends to execute it, which of course could be different than the congressional version of the law.

okay, now still keeping with the president's policy agenda, it won't surprise you to know that this agenda can conflict with the agendas of other branches of government, especially with congress and even more specifically with the senate. so included in the president's power is the ability to make federal appointments, but those appointments have to be confirmed by the senate and that can lead to some tension. let me just give you some examples. the president appoints a team of advisors which is known as the cabinet. these folks make up the heads of all the different executive agencies -- on which more in a moment -- and typically the senate just lets these appointments cruise on through on the assumption that the president should be able to choose their own staff. however, there are some cabinet appointments that get downright scrappy. for example, donald trump nominated betsy devos as the education secretary because she made it clear that she would pursue the privatization of education. that made her a lot of enemies in the senate. her confirmation hearing actually ended in a tie, and that brought vice president mike pence -- in the president of the senate -- to break the tie in devos's favor.

the president also appoints ambassadors to other countries, and usually the senate just confirms those folks without much drama. the white house staff is likewise appointed by the president but requires no senate confirmation. at this point you're like "i thought you said there was tension here between these two branches. like give us the drama." all right, you want the sauce? i'll give you the sauce. the sauce comes when there's an opening for a federal court nomination, more specifically the supreme court nomination. this is where things get highly contentious. judges who are appointed to the supreme court hold that job for the rest of their lives, and that means that if a president appoints a judge who is favorable to the presidential policy agenda, the judge can rule in line with that agenda for many years to come after the president is no longer in office. not surprisingly, conservative presidents appoint conservative judges and liberal presidents appoint liberal judges. and because of the long-term effects of this appointment, it creates no small amount of tension with the senators of the opposite party.

now you should know that over the course of us history, the scope of presidential power has expanded roughly three to four metric butt loads give or take. reaching all the way back to unit one, this expansion of power in the executive branch is exactly what the anti-federalists were worried about. in fact they said that the presidency as it was laid out in the constitution was nothing less than the fetus of monarchy. but hark, i see upon yonder shore a required document. it's federalist 70, and in this essay hamilton argues that a single executive was necessary because one person is able to act swiftly and decisively on matters that require firm leadership and tactical decision making. additionally, hamilton argued that the executive branch can be checked with the power of the other two branches, so a presidential monarch would be an impossibility. and finally, if the president does turn out to be a corrupt turd, then it is much more easily detectable in a single individual than in multiple, and thus a single executive will have to be much more careful with their power since they will be much more closely watched. and ultimately, as you already know, that was the argument that won the day.

but even so, as i mentioned, the power of the president has grown significantly over time. george washington along with the first five presidents who followed him basically yielded to congress's agenda since congress was the voice of the people. washington even stepped down after two terms to put the kibosh on any fears of an overbearing executive. remember in washington's day there was no limit on the number of terms a president can serve. now later that was added to the constitution in the 22nd amendment, but still, washington set the two-term precedent.

but then there was a significant shift in presidential power in the presidency of andrew jackson. he believed that the president was the representative of the people and not congress, and thus he expanded the power of the executive office to reflect that. the classic example here is the supreme court ruling that it was unconstitutional for the executive branch to force the cherokee indians off of their land in georgia, and yet jackson went ahead and did it anyway because that's what in his mind the people wanted.

and then presidential powers expanded even further with abraham lincoln. he assumed way more power than any president before him, and he's generally forgiven for it because he had the civil war to fight. most famously, he suspended the constitutional right of habeas corpus which meant that he could order people to be arrested without granting them a trial.

and then if there was ever a president who expanded executive power, it was our boy franklin roosevelt. the man used the veto 635 times. look, in case you don't know, that's a lot. like everybody broke out when andrew jackson used the veto 12 times in his tenure -- that was more than all the presidents before him combined. so fdr used the veto 635 times to which i say "dang." he was, to say the least, an energetic executive. he pushed his new deal programs through congress in order to address the devastating effects of the great depression -- programs like social security and minimum wage laws and public works programs. also, fdr served no less than four stinking terms as president. now to be fair, he did die in the first year of his fourth term, but still, the man was elected four times. so we're talking about expansion of federal power, it really was fdr who gave us our old friend big daddy government.

okay, now let's talk about presidential communication, and if there's one advantage that the president has that no other branch does, it's the eyes and ears of the nation, and good presidents use that attention to their advantage. the term for this presidential communication comes from teddy roosevelt who said that the presidency was a bully pulpit. now the word bully doesn't mean then what it does now -- it just meant excellent. in other words, roosevelt was enamored with the fact that he could speak directly to the people and that they would hopefully in turn put pressure on their representatives to legislate in line with roosevelt's agenda. and one of the chief ways the president does this is through the annual state of the union address to congress.

now the effectiveness of the presidential bully pulpit has changed as technology has advanced. for a long time presidents did give their state of the union addresses and those were filtered through newspaper editors. but with the advent of radio, franklin roosevelt discovered that he could talk directly to the people without any intermediary, and he did so in his famous fireside chats where he explained in simple terms his policy proposals through the radio. john f. kennedy was the first president to use the new medium of television to deliver live press conferences, and that is when you saw the creation of a presidential communication office which worked to refine and to shape the president's talking points so that the president's policy agenda would succeed in the hearts and minds of the people. and then with the advent of social media, the bully pulpit took on yet another form. this was a massive innovation in presidential communication because now the president had a way to speak to the people not only without an intermediary but as often as the president wanted to. barack obama appointed to social media as the key to winning his first campaign by creating a stream of communication directly to his supporters through social sites. to put it mildly, donald trump uh built on this innovation. he was deeply suspicious of traditional news media and used twitter as his bully pulpit to comment dozens of times a day on legislation, his political enemies and foreign affairs. in fact, trump so often used the twitter platform that he earned the nickname "tweeter in chief."

all right, with that let's move on to the judicial branch. we're going to start with how the courts are structured and then talk about how it checks the other branches. so in terms of the structure of the federal court system, there are three levels. at the bottom there are the u.s. district courts and there are 94 of those spread across the nation. these courts have what's called original jurisdiction, which means that they have the right to hear a case for the first time. on the next level you have the u.s. circuit court of appeals and there are 12 of these. they have what's called appellate jurisdiction, which means that they hear appeals from the lower courts. and the big daddy federal court sitting on top of the heap is the supreme court, which has both original and appellate jurisdiction depending on the kind of case being heard.

the supreme court is the only one of these courts that is explicitly mentioned in the constitution, and that is in article 3. all the other courts i mentioned are created by congress in the judiciary act of 1789. now wouldn't you know it, there is a required document associated with the supreme court, namely federalist 78. in this essay, hamilton argued that the independence of the judicial branch acted as a protection for its power. where does the court get such independence? well, from the lifetime appointment of its judges. if the judges aren't answerable to the voters, that means that they can rule on cases without the pressure of trying to get reelected. hamilton also argued that the court has the right of judicial review, which means it's the court's job to declare laws constitutional or unconstitutional. it's through this power that the supreme court has the power to check the other branches of government.

now this power isn't explicitly mentioned in the constitution, and that's where the required case of marbury versus madison in 1803 comes in. now i'm not going to go through all the details of this case, but what you really need to remember is that it was the court's ruling in this case that firmly cemented the power of judicial review in the supreme court's purview, and that had the effect of significantly increasing the power of the supreme court. in the constitution the supreme court was kind of like steve rogers trying to sign up for the army, but after marbury the court is like steve rogers coming out of that pod with his muscles all jacked and twitching.

okay, now let's talk about how the court works as they're considering their cases. the role of precedence is of extreme importance. so when a decision is handed down, it creates a precedent which means that unless there are some very extreme circumstances, this decision will act as a binding template for future decisions. you know, precedents are very hard to overturn because of a principle to which the court holds, namely stare decisis which when being translated means "let the decision stand." so if the court receives a case on a topic that has already been decided, it will often rule in the same way as the previous case. however, although it is rare, precedence can be overturned as it was for example in brown versus the board of education -- on which more in unit 3.

now the supreme court by comparison is less bound to precedence than the lower courts, but even so, precedents still serve to guide present decisions in a very significant way. now when it comes to upholding or overturning precedence, the court's activity falls under two headings: judicial activism or judicial restraint. judicial activism is the idea that the court acts to establish policy and considers more than just the constitutionality of a decision -- it also considers the decision's broader effects on society. brown versus the board of education is an important example of that, and activism in the court can either be liberal or conservative.

okay, now on the other side of the spectrum is judicial restraint, and the idea here is that judges believe that they aren't appointed to make policy -- like the elected legislature exists for that. if judges act according to judicial restraint, they believe that a law should only be struck down if it violates the actual written word of the constitution.

and then the ideology of the judges also plays a role in how the court makes his decisions as well. presidents appoint judges that align with their own political sympathies, and this has a role in whether the court will remain bound to previous precedents or create a new one. for example, since the 70s, conservative presidents have appointed conservative judges to the court in hopes of overturning the president established in roe v. wade which made abortion legal in all 50 states. now so far that effort has been unsuccessful, but it illustrates the point that ideology plays a role in the court's decisions.

Now, probably not going to surprise you to hear that as the court has exercised its power of judicial review, it has often led certain groups of Americans to question the legitimacy of the court's power. And this is especially true when controversial decisions are handed down.

For example, in the landmark case of Dred Scott v. Sandford in 1857, the court essentially ruled that slavery was permissible in all states. Now, if you know your U.S. history, you'll know that in 1857, the country was coming apart at the seams over the slavery question. And so, when the court handed down this decision, no small amount of abolitionists and anti-slavery crusaders called into question the legitimacy of the Supreme Court. Like, how in the world can these unelected judges overturn all the legislation that has kept the North free of slavery?

When the court hands down a decision, it effectively becomes the law of the land. But there are some ways that the other branches can reduce the impact of those decisions. The president can appoint new judges as the opportunity arises. For example, I just mentioned Roe v. Wade a second ago. Evangelical Christians have been trying to get that overturned for a long time, and their chief way of doing it in the 2016 election was to elect Donald Trump. And when asked why they voted for a man whose ethics are so opposed to Christianity, their response was, "For the court nominations."

Now, another way the president can mitigate court decisions is by a lack of enforcement. For example, the court ruled that it was unconstitutional for the federal government to remove Cherokee Christians from their lands in Georgia, and Andrew Jackson went ahead and did it anyway.

Then, Congress can also check the power of the judicial branch, and they do this through legislation. For example, Congress invalidated the Dred Scott decision by passing the 13th Amendment to the Constitution, which abolished slavery. Additionally, Congress passed the 11th Amendment, which limited the court's jurisdiction, thus restricting the kinds of cases that can even be heard in the Supreme Court.

And with that, it's time to turn the last corner in this video and talk about the federal bureaucracy.

Now, the bureaucracy is not a separate branch of government, although sometimes you'll hear people refer to it as the "fourth branch of government." Technically, the bureaucracy falls under the authority of the executive branch, and it's made up of millions of people who are employed to carry out the responsibilities of the federal government.

So, why don't we begin by talking about the structure of the bureaucracy, and then we'll see how it gets its work done?

In terms of structure, the highest level of authority in the bureaucracy falls to the cabinet secretaries. These are the leaders of the 15 executive departments, like the Department of Energy, the Department of Homeland Security, or the biggest of all, the Department of Defense. And then, these departments are further subdivided into agencies, which all work together to accomplish the goals of the department.

For example, the Department of the Treasury has all kinds of tax-collecting agencies within it, like the Internal Revenue Service, or the IRS. So, the way it works in this case is that Congress passes tax legislation, and then it's up to these agencies to make sure that taxes are actually collected.

Another part of the bureaucratic structure is commissions. These are regulatory groups who operate somewhat independently of the authority of the president but still fall under the executive authority. They're run by a board of individuals, and they're usually created for a specific purpose. For example, you have the FCC, or the Federal Communications Commission, which regulates the content of media -- not by censoring free speech, but by making sure that nothing inappropriate is displayed.

And then, yet another part of the bureaucratic structure is government corporations, which are kind of like a hybrid between a business and a government agency. Basically, the government acquires businesses when they want to offer a public good, but the free market is the best way to offer that service. A good example of this is PBS, which produces educational media.

Now, when it comes to the actual work of the bureaucracy, here's what they do.

First, they write and enforce regulations. But it's important to remember the distinction here: The bureaucracy is not creating laws. Congress is responsible for that. The bureaucracy is only making a set of more refined rules that help facilitate the execution of the law.

For example, the 16th Amendment establishes the income tax, but there's nothing about how those taxes are going to be collected. It was the IRS who determined that taxes are due by April 15th and how we are to pay them. So, this is what's known as delegated discretionary authority. And by definition, it's the authority given to the bureaucracy by Congress that gives them the discretion on how to make the rules and carry out the laws.

And another part of this authority is compliance monitoring, which means that the bureaucratic agencies establish rules for certain industries and then have to do the work of making sure those industries are complying with those rules. Now, look, this can slow down policy implementation, but the alternative is lax oversight, which would essentially invalidate the regulations they exist to implement.

The second thing that bureaucracy does is issue fines when laws are violated.

And third, heads of agencies will often testify before Congress -- either to be held accountable for their actions or just to give an update on the work of their agency.

Now, these bureaucratic agencies often work very closely with other entities, and I want to mention one relationship that you really need to know, and it's called an "iron triangle." The three points are bureaucratic agencies, congressional committees, and interest groups. And these groups often work together and rely on one another to create policy.

Bureaucrats offer expertise to congressional committees, with whom they are eager to cooperate, since it's Congress who approves funding for their departments. And the committee members want to pay attention to interest groups because they often have policy experts who can inform them of the implications of certain policies. And then, interest groups can provide funding for congressional races.

And with all this mutual benefit, the relationship between the three grows very strong. And that is why it's called an "iron triangle" -- not an "overcooked noodle triangle," because, you know, overcooked noodles are kind of weak and structurally can't hold much. You know, it'd be a bad metaphor for a strong relationship.

Anyway, for your exam, you need to know the names and purposes of seven of these bureaucratic departments. I'm not going to tell you everything these departments are responsible for; I'm just going to give you a couple examples.

First is the Department of Homeland Security, which protects the U.S. from terrorism and maintains and controls the nation's borders.

Second is the Department of Transportation, which manages all kinds of transportation, like highway and air travel.

Third is the Department of Veterans Affairs, which manages veterans' hospitals and the general welfare of America's veterans.

Fourth is the Department of Education, which oversees states in their implementation of federal educational standards.

Fifth is the Environmental Protection Agency, which works to protect the environment and human health through industrial regulation.

Sixth is the Federal Elections Commission, which administers and enforces campaign finance laws.

And then seventh is the Securities and Exchange Commission, which regulates the stock market and prevents fraud.

Now, all the leadership in these entities are folks whom the president appoints. And if the bureaucracy doesn't act sufficiently in accordance with the president's policy agenda, the president can fire them and appoint new leaders in cabinet and agency positions -- although the president cannot fire regulatory commission heads.

And often, not surprisingly, the president tries to staff those positions with folks sympathetic to the executive goals. Even so, commission heads serve fixed terms that overlap and outlast any given president. So, while the president does have a lot of influence over these entities, the president's influence isn't total.

So, all of these departments and agencies and commissions I just listed, along with hundreds of others, are basically the law enforcement apparatus of the executive branch. But their power in this regard can still be checked by other branches of government.

Because Congress is responsible for making sure that laws are upheld along the lines in which they were passed, they can hold committee hearings to ensure such execution is happening. Congress has many committees that correspond to the bureaucracy's agencies and will call directors of those agencies to testify and give reports of their progress. And sometimes, this is just a friendly check-in; other times, it can be tense.

But Congress also has another way to check the bureaucracy, and that's because Congress is the entity who's holding all the hooch in its pockets. Through the power of the purse, Congress can decide how to allocate funds to different agencies. And agencies cannot spend their money until a committee or subcommittee authorizes them to do so.

The president can also check the bureaucracy, and this is usually the first line of defense, since it falls under the president's authority. For example, President Clinton initiated a National Performance Review, in which the various agencies were required to scrutinize and, if necessary, change its mission and objectives.

You didn't think the judicial branch was going to miss out on all this power-checking fun, did you? When citizens believe that bureaucratic decisions are unconstitutional, they can challenge them in court. And usually, unless the agencies are blatantly violating a law, the court upholds the authority of the agency.

And the legitimacy of the bureaucracy has been challenged over time, specifically regarding its independence. These agencies and commissions create rules and regulations that do have the force of law, but as you no doubt know by this point, they are not elected representatives and thus are not accountable to the people. And this has a way of chapping the American thighs.

You also need to know that the way people have been chosen to work in the bureaucracy has changed over time. Back in the first hundred years or so of our history, people were given bureaucracy jobs based on the patronage system, which means that these jobs were a way for the president to award those who supported his campaign.

And that system was in place for a long time, but it kind of went sideways when President Garfield was assassinated. Basically, Garfield didn't give a bureaucratic job to a man who supported his campaign, so that man went ahead and shot the president. So, clearly, there needed to be some reform on that count.

And there was. After the Garfield assassination, Congress passed the Pendleton Civil Service Act in 1883, which created a merit system for bureaucratic appointments. So now, you had to pass a competitive examination in order to get one of those sweet bureaucratic jobs.

And that reform continued into the 20th century in order to make the bureaucracy more professional, specialized, and neutral. For example, under Jimmy Carter's administration, we got the Civil Service Reform Act, which upheld the merit system but made further reforms to help offer wider opportunities for women, more efficient control of human resource departments, etc.

And that's it. Oh my goodness, that was a giant unit, but I hope it helped. And if you want more help getting an A in your class and a five on your exam in May, you can click right over here and grab the Ultimate Review Packet.

If this video helped you, and you want me to keep making them, then you can let me know that by subscribing.

Heimler out.



'''

