
= 3 - Roe v. Wade
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Well hey there, and welcome back to Heimler's History. In this video, we're going to consider yet another one of your required 必修的 Supreme Court cases for the AP Government curriculum 教学大纲, namely Roe v. Wade in 1973. So if you're ready to get them brain cows milked（幽默表达：开动脑筋）, then let's get to it. +

So before we jump in, let me just say this is probably the most controversial 有争议的 case that you have to know for the AP Government curriculum, and as such I'm just outlining 概述 the facts of the case and how it was decided. People on both sides of this decision feel very deeply about its implications 含义，影响, so you know I'm not going to be cracking any jokes or making light of anything. We're just going to talk about the case itself. +

So as always, let's begin with the facts of the case 案件事实. In the 1930s, many states noticed a big problem, namely that many women were obtaining illegal 非法的 abortions, and because they were illegal they were not performed safely, and thus many women were falling severely ill or in some cases dying. And it was right about then that many states started liberalizing 放宽限制 their abortion laws to try to offer women the option for safe 安全的 abortions. +

Now a group of Catholic physicians were the first to seriously oppose 反对 this liberalization of abortion laws, and the reason that they did so was because according to the Catholic worldview 世界观 defined by natural law 自然法则, life began at conception 受孕，怀孕的开始, and thus to perform an abortion was no different than killing a human being outside the womb 子宫. Nevertheless, many states decided to grant further access to abortion because of the public health crisis caused by the high number of illegal abortions. +

Okay, now fast forward 快进 a few decades to the women's rights movement 女权运动 of the 60s and the 70s, and one of the key tenets 原则，信条 of this movement was the full-scale 全面 legalization of abortion. For women's rights advocates 倡导者, having control over their body was essential to their equality 平等 with men, and thus they argued that open access to abortion was necessary for that equality to be realized. By that point, Catholics still argued against abortion on demand, but they had now been joined by various other conservative 保守的 groups, especially Evangelical Christians 福音派基督徒 who were nervous about what abortion on demand would mean for what they understood as the declining 衰退的 morality 道德标准 of America. +

Okay, so it's against that backdrop 背景 that a Texas woman named Norma McCorvey (who because of the contentious 有争议的 nature of the case was identified only as Jane Roe) sought to get an abortion. Now the law in Texas only allowed for abortion in cases where the mother's life was in danger, and so she could not get the abortion that she wanted. And so finally this case wound up before the Supreme Court. +

Okay, so what was the constitutional principle 宪法原则 at stake? Well the answer is a little complicated. Now you'll no doubt know by this point that none of the amendments in the Bill of Rights 权利法案 says anything about a woman's right to an abortion, so what was the argument based on? Well ultimately it was based on a woman's right to privacy 隐私权. Now again, that's not explicitly 明确地 mentioned in the Bill of Rights, but the argument went like this: the court agreed that a right to privacy, while not explicitly mentioned, was for sure implicitly 含蓄地，暗示地 mentioned in the 1st, 4th, 5th, 9th and 14th amendments. And here's what they mean. +

For example, the Fourth Amendment 第四修正案 says that citizens have the right not to have their homes and personal effects searched without a warrant. That, the justices argued, implies 暗示 a right to privacy in one's personal space and belongings. The First Amendment 第一修正案 recognizes the right to choose any kind of religious belief you want and to keep that decision away from the prying eyes 窥探的目光 of the government. So that's the kind of thing they mean when they say that the right to privacy is implicit 内含的 in those amendments. But ultimately this case came down to the implicit right to privacy embedded in the Equal Protection Clause 平等保护条款 of the 14th Amendment 第十四修正案. +

Okay, so now let's see how the court decided this case. In a 7-2 decision 七比二的裁决, the Court ruled that the restrictive abortion laws in Texas violated Roe's constitutional right to privacy — namely to make decisions about her own body and obtaining an abortion. However, the justices acknowledged that there was a balance to strike between a woman's unmitigated 未加限制的 right to privacy and the state's potential interest in the child's life. Therefore, the decision offered different strictures 限制性规定 based on the trimester 孕期的三阶段 of pregnancy. +

In the first trimester, states could not legally restrict abortion. In the second trimester, states could make reasonable 合理的 restrictions as long as they were related to maternal 母体的 health. And in the third trimester, states may prohibit 禁止 abortions entirely except in cases where the mother's life was in danger. +

Okay, now why does this case matter? First of all, in the wake of 随着……之后 the Roe decision, a majority of states had to rewrite and liberalize their abortion laws, which granted women easier access to abortions across the nation. Second, this case matters because it became a clear crack 裂缝 in the foundation of American culture. After Roe, liberals 自由派 and conservatives 保守派 grew further apart and became unwilling to compromise 妥协 on many issues. In fact, overturning 推翻 Roe has been one of the key motivating energies 推动力 for conservatives winning the presidency since the decision was handed down. +

Remember, the president is the one who appoints 任命 justices to the Supreme Court, and Republicans have long sought to shift 转变 the court majority 多数派 to the conservative side in order to overturn Roe. And at the time of this recording, the Republicans have indeed done that, but whether they will overturn Roe remains to be seen. +

Okay, I hope that helped. If you want even more help, you can click right here and grab my review packet 复习资料包, which is going to help you get an A in your class and a five on your exam in May. I've got videos on all the other required Supreme Court cases right here, so click away if that's something that you're into. Subscribe if you want me to keep making these videos, and I shall surely oblige 乐意满足. I'm out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史课程。在这个视频中，我们要研究美国大学预修课程（AP）政府课程中另一个最高法院的必学案例，也就是1972年的 “罗伊诉韦德案”（Roe v. Wade）。所以，如果你准备好汲取知识，那么我们开始吧。 +

在我们深入这个案例之前，我得说，这可能是美国大学预修课程（AP）政府课程中你需要了解的最具争议的案例。所以我只是概述这个案件的事实以及它是如何裁决的。对于这个裁决，持不同立场的人都对其影响感受颇深，所以你知道我不会开任何玩笑，也不会轻视任何事情。我们只是要讨论这个案件本身。 +

和往常一样，我们先来看这个案件的事实。在20世纪30年代，许多州注意到一个大问题，即许多女性在进行非法堕胎，而且因为这些堕胎是非法的，所以并不安全，因此许多女性病得很重，在某些情况下甚至死亡。就在那时，许多州开始放宽堕胎法律，试图为女性提供安全堕胎的选择。 +

当时，一群天主教医生率先强烈反对堕胎法律的放宽，他们这样做的原因是，根据自然法定义的天主教世界观，生命从受孕开始，因此堕胎无异于杀害一个尚未出生的人。然而，许多州鉴于大量非法堕胎引发的公共卫生危机，决定进一步允许堕胎。 +

好的，现在快进到20世纪60年代和70年代的女权运动时期，这场运动的一个关键原则是全面将堕胎合法化。对于女权倡导者来说，对自己身体的控制权是实现与男性平等的关键，因此他们认为，为了实现平等，开放堕胎是必要的。在那个时候，天主教徒仍然反对按需堕胎，但现在其他各种保守团体也加入了他们的行列，特别是福音派基督徒，他们对按需堕胎可能对他们所认为的美国道德滑坡产生的影响感到担忧。 +

好的，在这样的背景下，一位名叫诺玛·麦科维（Norma McCorvey，由于案件的争议性，她以简·罗伊（Jane Roe）的身份出现）的德克萨斯州（Texas）女性寻求堕胎。当时德克萨斯州的法律只允许在母亲生命受到威胁的情况下堕胎，所以她无法得到她想要的堕胎机会。最终，这个案件被提交到最高法院。 +

好的，那么这个案件所涉及的宪法原则是什么呢？嗯，答案有点复杂。此时你无疑知道，《权利法案》（Bill of Rights）中的修正案都没有提及女性的堕胎权，那么这个案件的依据是什么呢？嗯，最终它基于女性的隐私权。同样，隐私权在《权利法案》中没有明确提及，但论点是这样的：法院认为，隐私权虽然没有明确提及，但在第一、第四、第五、第九和第十四修正案中确实有隐含体现。这是他们的意思。 +

例如，第四修正案规定，公民有权在没有搜查令的情况下，其住宅和个人财物不被搜查。法官们认为，这意味着在个人空间和财物方面的隐私权。第一修正案承认人们有权选择任何自己想要的宗教信仰，并使这一决定不受政府的窥探。所以当他们说隐私权隐含在这些修正案中时，就是这个意思。但最终这个案件归结为第十四修正案（14th Amendment）的平等保护条款中所隐含的隐私权。 +

好的，现在我们来看看法院是如何裁决这个案件的。最高法院以7比2的裁决判定，德克萨斯州的限制性堕胎法律侵犯了罗伊（Roe）的宪法隐私权——即对自己身体做出决定以及堕胎的权利。然而，法官们承认，在女性不受限制的隐私权和州对胎儿生命的潜在利益之间需要取得平衡。因此，该裁决根据怀孕的不同阶段提出了不同的限制条件。 +

在怀孕的头三个月，各州在法律上不能限制堕胎。在怀孕的第二个三个月，各州可以做出合理的限制，只要这些限制与孕妇的健康有关。在怀孕的第三个三个月，各州可以完全禁止堕胎，除非母亲的生命受到威胁。 +

好的，那么这个案件为什么重要呢？首先，在 “罗伊案” 的裁决之后，大多数州不得不重写并放宽他们的堕胎法律，这使得全国各地的女性更容易获得堕胎机会。其次，这个案件很重要，因为它成为美国文化基础上的一个明显裂痕。在 “罗伊案” 之后，自由派和保守派的分歧进一步加大，并且在许多问题上都不愿意妥协。事实上，自该裁决作出以来，推翻 “罗伊案” 一直是保守派赢得总统职位的关键动力之一。 +

记住，总统负责任命最高法院的大法官，长期以来，共和党人一直试图让最高法院的多数派转向保守派，以便推翻 “罗伊案”。在录制这个视频的时候，共和党人确实做到了这一点，但他们是否会推翻 “罗伊案” 还有待观察。 +

好的，我希望这对你有帮助。如果你想要更多帮助，你可以点击这里获取我的复习资料包，这将帮助你在课堂上得A，在五月份的考试中得5分。我这里还有关于所有其他最高法院必学案例的视频，所以如果你对此感兴趣，就点击观看吧。如果你希望我继续制作这些视频，我肯定会照做的。我下线了。 + 

'''

== pure

Well hey there, and welcome back to Heimler's History. In this video, we're going to consider yet another one of your required Supreme Court cases for the AP Government curriculum, namely Roe v. Wade in 1972. So if you're ready to get them brain cows milked, then let's get to it.

So before we jump in, let me just say this is probably the most controversial case that you have to know for the AP Government curriculum, and as such I'm just outlining the facts of the case and how it was decided. People on both sides of this decision feel very deeply about its implications, so you know I'm not going to be cracking any jokes or making light of anything. We're just going to talk about the case itself.

So as always, let's begin with the facts of the case. In the 1930s, many states noticed a big problem, namely that many women were obtaining illegal abortions, and because they were illegal they were not performed safely, and thus many women were falling severely ill or in some cases dying. And it was right about then that many states started liberalizing their abortion laws to try to offer women the option for safe abortions.

Now a group of Catholic physicians were the first to seriously oppose this liberalization of abortion laws, and the reason that they did so was because according to the Catholic worldview defined by natural law, life began at conception, and thus to perform an abortion was no different than killing a human being outside the womb. Nevertheless, many states decided to grant further access to abortion because of the public health crisis caused by the high number of illegal abortions.

Okay, now fast forward a few decades to the women's rights movement of the 60s and the 70s, and one of the key tenets of this movement was the full-scale legalization of abortion. For women's rights advocates, having control over their body was essential to their equality with men, and thus they argued that open access to abortion was necessary for that equality to be realized. By that point, Catholics still argued against abortion on demand, but they had now been joined by various other conservative groups, especially Evangelical Christians who were nervous about what abortion on demand would mean for what they understood as the declining morality of America.

Okay, so it's against that backdrop that a Texas woman named Norma McCorvey (who because of the contentious nature of the case was identified only as Jane Roe) sought to get an abortion. Now the law in Texas only allowed for abortion in cases where the mother's life was in danger, and so she could not get the abortion that she wanted. And so finally this case wound up before the Supreme Court.

Okay, so what was the constitutional principle at stake in this case? Well the answer is a little complicated. Now you'll no doubt know by this point that none of the amendments in the Bill of Rights says anything about a woman's right to an abortion, so what was the argument based on? Well ultimately it was based on a woman's right to privacy. Now again, that's not explicitly mentioned in the Bill of Rights, but the argument went like this: the court agreed that a right to privacy, while not explicitly mentioned, was for sure implicitly mentioned in the 1st, 4th, 5th, 9th and 14th amendments. And here's what they mean.

For example, the Fourth Amendment says that citizens have the right not to have their homes and personal effects searched without a warrant. That, the justices argued, implies a right to privacy in one's personal space and belongings. The First Amendment recognizes the right to choose any kind of religious belief you want and to keep that decision away from the prying eyes of the government. So that's the kind of thing they mean when they say that the right to privacy is implicit in those amendments. But ultimately this case came down to the implicit right to privacy embedded in the Equal Protection Clause of the 14th Amendment.

Okay, so now let's see how the court decided this case. In a 7-2 decision, the Court ruled that the restrictive abortion laws in Texas violated Roe's constitutional right to privacy -- namely to make decisions about her own body and obtaining an abortion. However, the justices acknowledged that there was a balance to strike between a woman's unmitigated right to privacy and the state's potential interest in the child's life. Therefore, the decision offered different strictures based on the trimester of pregnancy.

In the first trimester, states could not legally restrict abortion. In the second trimester, states could make reasonable restrictions as long as they were related to maternal health. And in the third trimester, states may prohibit abortions entirely except in cases where the mother's life was in danger.

Okay, now why does this case matter? First of all, in the wake of the Roe decision, a majority of states had to rewrite and liberalize their abortion laws, which granted women easier access to abortions across the nation. Second, this case matters because it became a clear crack in the foundation of American culture. After Roe, liberals and conservatives grew further apart and became unwilling to compromise on many issues. In fact, overturning Roe has been one of the key motivating energies for conservatives winning the presidency since the decision was handed down.

Remember, the president is the one who appoints justices to the Supreme Court, and Republicans have long sought to shift the court majority to the conservative side in order to overturn Roe. And at the time of this recording, the Republicans have indeed done that, but whether they will overturn Roe remains to be seen.

Okay, I hope that helped. If you want even more help, you can click right here and grab my review packet, which is going to help you get an A in your class and a five on your exam in May. I've got videos on all the other required Supreme Court cases right here, so click away if that's something that you're into. Subscribe if you want me to keep making these videos, and I shall surely oblige. I'm out.

'''

