
= 3.06 Individual FREEDOM vs. PUBLIC SAFETY - 2nd, 4th, 8th Amendments
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Well, hey there, and welcome back to Heimler History. Now, we've been going through Unit Three of the AP Government curriculum 课程, and in this video, we're going to talk about The Balancing Act 平衡行为 between individual Freedom 个人自由 versus public order 公共秩序. So, if you're ready to get those brain cows milked, then let's get to it. +

So, here's what we're trying to do in this video: explain how the Supreme Court 最高法院 has attempted to balance claims of individual Freedom with laws and enforcement procedures 执法程序 that promote public order and safety 公共秩序与安全. So, the idea here is the same as what I've said in nearly every other video in unit 3: none of our rights are absolute 绝对的, and when the Supreme Court takes up the task of interpreting the Amendments 修正案, they are always trying to figure out whether an individual's Freedom should be upheld 维护 or whether Public Safety and order is more important. +

So, in order to illustrate 说明 this tension 矛盾, we're going to look at this debate with respect to 关于 the Eighth Amendment 第八修正案, the Second Amendment 第二修正案, and the Fourth Amendment 第四修正案. So, let's begin with the Eighth Amendment, which says this: "Excessive bail 过高的保释金 shall not be required, nor excessive fines 过高的罚款 imposed 征收, nor cruel and unusual punishments 残忍和不寻常的惩罚 inflicted 施加." We're going to focus on that last clause 条款 about cruel and unusual punishments. In recent history, the debate over the Eighth amendment has been waged 进行 over whether the application of the death penalty 死刑的适用 is a violation of 违反 this amendment's protection against cruel and unusual punishment. Now, to be fair, the government putting a convicted criminal 已定罪的罪犯 to death is not on the surface 表面上 unconstitutional 违宪的. After all, the Fifth Amendment 第五修正案 states that no person shall be deprived of 被剥夺 life, liberty or property without due process of law 正当法律程序. So, according to this Clause 条款, someone could be deprived of their life if the due process of law was followed. But unfortunately, in the real world, it's not that clean. For example, in the non-required case of Furman V Georgia in 1972, the Supreme Court ruled that the death penalty was unconstitutional. Now, different justices 法官 gave different rationales 理由 for this decision, but one of the overriding themes 首要主题 was racial prejudice 种族偏见 in the application of the death penalty. For example, a study from 2019 found that roughly 50% of murder victims 谋杀受害者 are black, but 80% of new death penalty sentences 死刑判决 were imposed when the victims were white. And if you didn't follow that, let me explain it real simple for you: you are way more likely to get the death penalty if you kill a white guy than if you kill a black guy. And it was because of that disparity 差异 that the death penalty was deemed 被认为 cruel and unusual, not because of the methods of execution 处决方式, but because of the unequal application 不平等适用 of it. And because of similar findings in the 70s, that's why the Court ruled the death penalty unconstitutional in Furman V Georgia, which essentially 本质上 brought the death penalty to an end in the United States. However, the court decided differently four years later in another non-required case, Gregg V Georgia in 1976. After the Furman case, Georgia, along with many other states, rewrote 重写 their death penalty laws in an attempt to avoid the racial discrimination 种族歧视 which made the death penalty cruel and unusual. And in this case, the Court ruled that the death penalty in and of itself 本身 was not a violation of the Eighth amendment because for extreme crimes 严重罪行, an extreme penalty 严厉惩罚 was required, and thus may serve as a preventative 预防措施 for Citizens committing those extreme crimes. However, some have argued that there is no humane 人道的 way to execute 处决 another person. Like, not to be too graphic 过于直白, but there have been occasions when people have caught fire in the electric chair 电椅 or who have been in agony 痛苦 when lethal injection 注射死刑 drugs have been administered wrongly. Moreover 此外, here's where I blow your mind 让你震惊 and tell you that in four states, it's still legal to be executed by firing squad 行刑队枪决. What? Like, in 2010, a man was executed by firing squad in Utah. 2010! Like we're not talking about the old west here. +

Anyway, between these two cases, you can see the debate between individual freedom and social order 社会秩序. In the Furman case, the court upheld individual Freedom with respect to cruel and unusual punishment, but in the Gregg case, the court upheld social order when it said that the death penalty can be a deterrent 威慑 to Future crime 未来犯罪. And look, that debate continues today. Recent evidence has shown that at least a handful of 一些 people have been wrongly executed in the past, and attorneys 律师 have made use of DNA evidence 证据 to obtain the release of inmates 囚犯 who were on death row 死刑犯 who were found to be innocent despite their conviction 定罪. So, this is a very nuanced 微妙的 and hairy 复杂的 topic that will continue to be debated into the future. +

Okay, now let's consider that same debate with respect to the Second Amendment, which concerns, of course, the right to own guns 拥有枪支的权利. At various times and various places, laws have been passed which either open up 开放 people's right to own guns or seek to constrict 限制 those rights. And in general, this is an ongoing debate 持续的争论, but it gets very loud. Not surprisingly, every time there's a mass shooting 大规模枪击事件. For example, in 2012, the deadliest Mass school shooting occurred at Sandy Hook Elementary in Connecticut, and in that shooting, 20 children and six adults were killed. And as you can imagine, the public outcry 公众抗议 was Swift 迅速的 and severe 强烈的. The gunmen 枪手 had used several guns, some of them with high-capacity magazines 大容量弹匣. And within hours of the shooting, anti-gun interest groups 反枪支利益团体 were lobbying 游说 Congress for gun control legislation 枪支管制立法. Over the next few days, President Obama fired off 发出 several executive orders 行政命令 to try to restrict gun access 限制枪支获取, especially those with high-capacity magazines. And clearly, these things were being done in order to uphold Public Safety 维护公共安全 at the expense of 以…为代价 personal Liberty 个人自由 with respect to gun ownership. But on the other side, the National Rifle Association 全国步枪协会, while they denounce 谴责 such violence, blamed the incident on the gunman's obsession with 痴迷于 violent video games. Like, it wasn't the guns, it was the video game. And so the NRA began counter lobbying 反游说 to uphold individual liberty with respect to gun ownership. Now, the Supreme Court has generally ruled in favor of 支持 individual gun rights 个人持枪权, and I have a whole video on that in the landmark case 标志性案件 McDonald V Chicago. So, that's all I'll say about it here. +

Okay, now let's talk about this debate between individual freedom and Public Safety with respect to the Fourth Amendment 第四修正案. The fourth amendment protects citizens against unreasonable searches and seizures 不合理的搜查和扣押 of their property 财产. Warrants 搜查令 must be secured 获得 before entering a person's home, and those are only issued by courts when probable cause 合理理由 is well established. And that's pretty clear. Like, the police cannot enter your home and rifle through 翻找 your stuff without a court approving the action. But the most recent ongoing debate has to do with 与…有关 our rights to be secure in our digital lives 数字生活中的安全权利. So, after the terrorist attacks 恐怖袭击 on September 11th, 2001, and the resulting Patriot Act 爱国者法案, George W. Bush initiated 发起, by executive order, a program that allowed the federal government to interface with 与…交互 third-party cell phone carriers 第三方手机运营商 to search for leads on 寻找线索 suspected terrorists 恐怖主义嫌疑人. They did this by Mining 挖掘 and searching through Americans' metadata 元数据. Which, in case you don't know, is all the information about how a person communicates, minus 减去 the actual conversation. So, metadata tells us who you called, how long did you talk, how frequently did you call, Etc. And under the Patriot Act, this was deemed necessary to the upholding of Public Safety because we had just suffered this devastating 毁灭性的 terrorist attack. And while nobody wanted to suffer another terrorist attack, many groups fought back against this invasion of privacy 侵犯隐私, calling it a gross government overreach 政府过度干预 and a violation of 违反 the individual Freedom protected in the Fourth Amendment. +

Okay, that's what you need to know about unit 3 topic six in the AP Government curriculum. If you need help getting an A in your class and a five on your exam in May, then click right here and grab your review packet. And if this video helped you and you want me to keep making them, then you can let me know that by subscribing 订阅. I'm out. +

'''

== 中文释义

嘿，欢迎回到海姆勒历史课程。现在，我们一直在学习美国大学预修课程（AP）政府课程的第三单元，在这个视频中，我们要探讨个人自由与公共秩序之间的平衡行为。所以，如果你准备好汲取知识，那我们开始吧。 +

所以，在这个视频中我们要做的是：解释最高法院如何尝试在个人自由的主张与促进公共秩序和安全的法律及执法程序之间取得平衡。这里的观点和我在第三单元的几乎其他所有视频中所说的一样：我们的权利都不是绝对的，当最高法院承担起解释修正案的任务时，他们总是试图弄清楚是应该维护个人自由，还是公共安全和秩序更为重要。 +

所以，为了说明这种矛盾关系，我们要看看关于第八修正案、第二修正案和第四修正案的这场辩论。那么，我们先从第八修正案开始，它是这样说的：“不得要求过高的保释金，不得处以过高的罚款，不得施加残忍和不寻常的惩罚。” 我们要关注关于残忍和不寻常惩罚的最后这个条款。在近代历史上，关于第八修正案的辩论围绕着死刑的适用是否违反了该修正案对防止残忍和不寻常惩罚的保护。说句公道话，政府处决被定罪的罪犯表面上并不违宪。毕竟，第五修正案规定，未经正当法律程序，任何人不得被剥夺生命、自由或财产。所以，根据这个条款，如果遵循正当法律程序，某人可能会被剥夺生命。但不幸的是，在现实世界中，情况并非那么简单。例如，在1972年 “弗曼诉佐治亚州案”（Furman V Georgia）这个非必学案例中，最高法院裁定死刑是违宪的。不同的大法官对这个裁决给出了不同的理由，但一个首要的主题是在死刑的适用中存在种族偏见。例如，2019年的一项研究发现，大约50% 的谋杀受害者是黑人，但当受害者是白人时，80% 的新死刑判决被执行。如果你不理解这一点，让我简单解释一下：如果你杀了一个白人，你比杀了一个黑人更有可能被判处死刑。正是因为这种差异，死刑被认为是残忍和不寻常的，原因不是处决的方式，而是其不平等的适用。由于在70年代有类似的发现，这就是为什么最高法院在 “弗曼诉佐治亚州案” 中裁定死刑违宪，这实际上在美国终结了死刑。然而，四年后在另一个非必学案例 “格雷格诉佐治亚州案”（Gregg V Georgia）中，法院做出了不同的裁决。在 “弗曼案” 之后，佐治亚州和许多其他州重写了他们的死刑法律，试图避免使死刑变得残忍和不寻常的种族歧视。在这个案件中，法院裁定死刑本身并不违反第八修正案，因为对于极其严重的罪行，需要极其严厉的惩罚，因此这可以起到预防公民犯下这些极其严重罪行的作用。然而，有些人认为没有人道的方式来处决一个人。打个比方，说得不太形象些，曾有一些情况，有人在电椅上被处决时着火，或者在注射致死药物时处于痛苦之中。此外，我要告诉你一个惊人的事实，在四个州，被行刑队处决仍然是合法的。什么？比如在2010年，犹他州（Utah）一名男子被行刑队处决。2010年！我们说的可不是美国西部的旧时情况。 +

总之，在这两个案件中，你可以看到个人自由和社会秩序之间的辩论。在 “弗曼案” 中，法院在残忍和不寻常惩罚方面维护了个人自由，但在 “格雷格案” 中，法院认为死刑可以起到威慑未来犯罪的作用，从而维护了社会秩序。看，这场辩论在今天仍在继续。最近的证据表明，过去至少有一些人被错误地执行了死刑，律师们利用DNA证据让那些被判死刑但被发现是无辜的囚犯获释。所以，这是一个非常微妙且复杂的话题，在未来还会继续被讨论。 +

好的，现在让我们考虑关于第二修正案的同样的辩论，当然，它涉及到拥有枪支的权利。在不同的时间和不同的地方，通过了一些法律，这些法律要么开放了人们拥有枪支的权利，要么试图限制这些权利。总的来说，这是一场持续的辩论，但它的声音非常大。毫不奇怪，每次发生大规模枪击事件时都是如此。例如，2012年，康涅狄格州（Connecticut）桑迪胡克小学（Sandy Hook Elementary）发生了最致命的大规模校园枪击事件，在那次枪击事件中，20名儿童和6名成年人丧生。你可以想象，公众的抗议迅速而激烈。枪手使用了几把枪，其中一些枪配有大容量弹匣。枪击事件发生后的几个小时内，反枪支利益团体就游说国会制定枪支管制立法。在接下来的几天里，奥巴马总统发布了几项行政命令，试图限制枪支的获取，特别是那些配有大容量弹匣的枪支。很明显，这些措施是以牺牲个人在枪支拥有方面的自由为代价来维护公共安全的。但另一方面，全国步枪协会（National Rifle Association）虽然谴责这种暴力行为，但将这一事件归咎于枪手对暴力视频游戏的痴迷。也就是说，问题不在于枪支，而在于视频游戏。所以全国步枪协会开始进行反游说，以维护个人在枪支拥有方面的自由。现在，最高法院总体上做出了支持个人持枪权的裁决，我在具有里程碑意义的 “麦克唐纳诉芝加哥案”（McDonald V Chicago）中有一整个关于这个案件的视频。所以关于这个我就说这么多。 +

好的，现在让我们谈谈关于第四修正案的个人自由与公共安全之间的这场辩论。第四修正案保护公民免受对其财产的不合理搜查和扣押。在进入一个人的家之前必须获得搜查令，并且只有在确定存在合理理由的情况下，法院才会签发搜查令。这一点非常明确。比如，没有法院批准的行动，警察不能进入你的家并翻找你的东西。但最近持续的辩论与我们在数字生活中的安全权利有关。所以，在2001年9月11日的恐怖袭击以及随之而来的《爱国者法案》（Patriot Act）之后，乔治·W·布什（George W. Bush）通过行政命令启动了一个项目，允许联邦政府与第三方手机运营商对接，以寻找可疑恐怖分子的线索。他们通过挖掘和搜索美国人的元数据来做到这一点。以防你不知道，元数据是关于一个人如何通信的所有信息，但不包括实际的对话内容。所以，元数据会告诉我们你给谁打电话、通话时长、通话频率等等。根据《爱国者法案》，这被认为对维护公共安全是必要的，因为我们刚刚遭受了这场毁灭性的恐怖袭击。虽然没有人希望再遭受一次恐怖袭击，但许多团体反对这种对隐私的侵犯，称这是政府的严重越权行为，违反了第四修正案所保护的个人自由。 +

好的，这就是你需要了解的美国大学预修课程（AP）政府课程第三单元第六主题的内容。如果你想在课堂上得A，在五月份的考试中得5分，那就点击这里获取复习资料包。如果这个视频对你有帮助，并且你希望我继续制作这类视频，那就通过订阅告诉我。我下线了。 + 

'''

== pure

Well, hey there, and welcome back to Heimler History. Now, we've been going through Unit Three of the AP Government curriculum, and in this video, we're going to talk about The Balancing Act between individual Freedom versus public order. So, if you're ready to get those brain cows milked, then let's get to it. 

So, here's what we're trying to do in this video: explain how the Supreme Court has attempted to balance claims of individual Freedom with laws and enforcement procedures that promote public order and safety. So, the idea here is the same as what I've said in nearly every other video in unit 3: none of our rights are absolute, and when the Supreme Court takes up the task of interpreting the Amendments, they are always trying to figure out whether an individual's Freedom should be upheld or whether Public Safety and order is more important. 

So, in order to illustrate this tension, we're going to look at this debate with respect to the Eighth Amendment, the Second Amendment, and the Fourth Amendment. So, let's begin with the Eighth Amendment, which says this: "Excessive bail shall not be required, nor excessive fines imposed, nor cruel and unusual punishments inflicted." We're going to focus on that last clause about cruel and unusual punishments. In recent history, the debate over the Eighth amendment has been waged over whether the application of the death penalty is a violation of this amendment's protection against cruel and unusual punishment. Now, to be fair, the government putting a convicted criminal to death is not on the surface unconstitutional. After all, the Fifth Amendment states that no person shall be deprived of life, liberty or property without due process of law. So, according to this Clause, someone could be deprived of their life if the due process of law was followed. But unfortunately, in the real world, it's not that clean. For example, in the non-required case of Furman V Georgia in 1972, the Supreme Court ruled that the death penalty was unconstitutional. Now, different justices gave different rationales for this decision, but one of the overriding themes was racial prejudice in the application of the death penalty. For example, a study from 2019 found that roughly 50% of murder victims are black, but 80% of new death penalty sentences were imposed when the victims were white. And if you didn't follow that, let me explain it real simple for you: you are way more likely to get the death penalty if you kill a white guy than if you kill a black guy. And it was because of that disparity that the death penalty was deemed cruel and unusual, not because of the methods of execution, but because of the unequal application of it. And because of similar findings in the 70s, that's why the Court ruled the death penalty unconstitutional in Furman V Georgia, which essentially brought the death penalty to an end in the United States. However, the court decided differently four years later in another non-required case, Gregg V Georgia in 1976. After the Furman case, Georgia, along with many other states, rewrote their death penalty laws in an attempt to avoid the racial discrimination which made the death penalty cruel and unusual. And in this case, the Court ruled that the death penalty in and of itself was not a violation of the Eighth amendment because for extreme crimes, an extreme penalty was required, and thus may serve as a preventative for Citizens committing those extreme crimes. However, some have argued that there is no humane way to execute another person. Like, not to be too graphic, but there have been occasions when people have caught fire in the electric chair or who have been in agony when lethal injection drugs have been administered wrongly. Moreover, here's where I blow your mind and tell you that in four states, it's still legal to be executed by firing squad. What? Like, in 2010, a man was executed by firing squad in Utah. 2010! Like we're not talking about the old west here. 

Anyway, between these two cases, you can see the debate between individual freedom and social order. In the Furman case, the court upheld individual Freedom with respect to cruel and unusual punishment, but in the Gregg case, the court upheld social order when it said that the death penalty can be a deterrent to Future crime. And look, that debate continues today. Recent evidence has shown that at least a handful of people have been wrongly executed in the past, and attorneys have made use of DNA evidence to obtain the release of inmates who were on death row who were found to be innocent despite their conviction. So, this is a very nuanced and hairy topic that will continue to be debated into the future. 

Okay, now let's consider that same debate with respect to the Second Amendment, which concerns, of course, the right to own guns. At various times and various places, laws have been passed which either open up people's right to own guns or seek to constrict those rights. And in general, this is an ongoing debate, but it gets very loud. Not surprisingly, every time there's a mass shooting. For example, in 2012, the deadliest Mass school shooting occurred at Sandy Hook Elementary in Connecticut, and in that shooting, 20 children and six adults were killed. And as you can imagine, the public outcry was Swift and severe. The gunmen had used several guns, some of them with high-capacity magazines. And within hours of the shooting, anti-gun interest groups were lobbying Congress for gun control legislation. Over the next few days, President Obama fired off several executive orders to try to restrict gun access, especially those with high-capacity magazines. And clearly, these things were being done in order to uphold Public Safety at the expense of personal Liberty with respect to gun ownership. But on the other side, the National Rifle Association, while they denounce such violence, blamed the incident on the gunman's obsession with violent video games. Like, it wasn't the guns, it was the video game. And so the NRA began counter lobbying to uphold individual liberty with respect to gun ownership. Now, the Supreme Court has generally ruled in favor of individual gun rights, and I have a whole video on that in the landmark case McDonald V Chicago. So, that's all I'll say about it here. 

Okay, now let's talk about this debate between individual freedom and Public Safety with respect to the Fourth Amendment. The fourth amendment protects citizens against unreasonable searches and seizures of their property. Warrants must be secured before entering a person's home, and those are only issued by courts when probable cause is well established. And that's pretty clear. Like, the police cannot enter your home and rifle through your stuff without a court approving the action. But the most recent ongoing debate has to do with our rights to be secure in our digital lives. So, after the terrorist attacks on September 11th, 2001, and the resulting Patriot Act, George W. Bush initiated, by executive order, a program that allowed the federal government to interface with third-party cell phone carriers to search for leads on suspected terrorists. They did this by Mining and searching through Americans' metadata. Which, in case you don't know, is all the information about how a person communicates, minus the actual conversation. So, metadata tells us who you called, how long did you talk, how frequently did you call, Etc. And under the Patriot Act, this was deemed necessary to the upholding of Public Safety because we had just suffered this devastating terrorist attack. And while nobody wanted to suffer another terrorist attack, many groups fought back against this invasion of privacy, calling it a gross government overreach and a violation of the individual Freedom protected in the Fourth Amendment. 

Okay, that's what you need to know about unit 3 topic six in the AP Government curriculum. If you need help getting an A in your class and a five on your exam in May, then click right here and grab your review packet. And if this video helped you and you want me to keep making them, then you can let me know that by subscribing. I'm out. 

'''

