
= 4.05 Measuring PUBLIC OPINION
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History. Now we've been going through 单独学习；钻研 Unit 4 of the AP Government curriculum 课程设置；课程, and in this video that means it's time to talk about how we measure public opinion 舆论；公众意见. So if you're ready to get them brain cows milked with a low sampling 抽样；取样 error 误差；错误, then let's get to it. +

So this video is simple, and here's what we're trying to do: describe 描述；描绘 the elements 要素；组成部分 of a scientific poll 民意测验；民调. Okay, now so far in this unit we've been talking about how people come to hold certain political beliefs 政治信仰；政治观点, and all sorts of people -- especially politicians 政治家；政客 -- are interested in knowing those beliefs. So how can they do that? Well, the main way we measure public opinion is through 通过；借助 scientific polls, which is to say we ask people what they believe and hopefully they tell us. +

The information that pollsters 民意调查人员 get from these polls has a big impact 影响；作用 on elections 选举 and policy 政策；方针 debates 辩论；争论. If a poll is created with scientific rigor 严密性；严格性, then they are the best tools 工具 we have for measuring public opinion. The process includes 包括；包含 writing questions that are as free from bias 偏见；偏向 as possible, and then presenting them to a small randomized 随机的 group of people, and then generalizing those results to the larger population 人口；群体. +

So first let's have a look at the different ways pollsters measure public opinion, and then we'll have a look at how they know those results are accurate 精确的；准确的. So there are four different kinds of polls that you need to know. First is an opinion poll, which is exactly what it sounds like. Pollsters use an opinion poll to get a feel for 感知；了解 the public's opinion on a certain topic or discerning 识别；分辨 people's feelings on certain candidates 候选人 or policies. So when a candidate starts making speeches and promising certain things, it's not because the candidate is just pulling those policies out of thin air 凭空；无依据地. No, they have paid attention to the opinion polls and are now making promises based on what the people actually want. +

Second is a benchmark poll. This is a poll taken at the beginning 起始阶段；初期 of a candidate's run 竞选活动. This gives the campaign a benchmark 基准；参考点 against which they can compare future polls to see how the candidate is faring 进展；表现. Benchmark polls often focus on a candidate's messaging 信息传递. When they figure out 弄明白；理解 which messages are resonating 引起共鸣 with voters, they'll spend more time on those messages and throw the others away. +

Third is a tracking poll. These are polls that are conducted over time, usually with the same group of people, and that gives information on how the group feels about an issue 问题；议题. This helps a candidate shape 制定；设计 his or her campaign promises, especially when the election is near. +

And fourth, you have entrance and exit polls. And these are polls conducted at voting 投票 sites 地点 and ask people how they voted. If they ask them before a person goes in to vote, that's called an entrance poll. If they ask after they have voted, that's an exit poll. These kinds of polls are among the most desirable 值得拥有的；理想的 because they're measuring actual voters, not just people who may say they're gonna vote and then don't for whatever reason. "Well, it's election day but my toe here ain't gonna shave itself." +

Okay, so those are the different kinds of polls you need to know, and their purpose 目的；意图 is to measure public opinion. Now the real question is this: how do we know that these measurements are legitimate 合法的；正当的？Well, the short answer is that good polls are created with scientific rigor. So how do they do that? +

Well, the first thing you need to know is how researchers 研究人员 choose the people they're going to ask, and for that let's talk about sampling techniques 技巧；方法. Pollsters always measure public opinion by means of 借助；通过 a sample. I mean, think about it: if you're a pollster and you want to measure public opinion, then the best way would be to ask every American of voting age what they think about an issue. But then you'd be surveying 调查 like 256 million people, and just in case you'd like those results in fewer than 400 years, you're gonna need to measure the opinion of a sample of those people. +

Now in order to be scientifically rigorous 严谨的；缜密的, a sample first needs to be representative 有代表性的, which is to say the sample needs to have the same characteristics 特征；特点 as the larger population that it's measuring. So if you want to know what millennials 千禧一代 think about the legalization 合法化 of marijuana 大麻, then you need to ask a small sample of millennials and not senior citizens 老年人. Now the sample also needs to be random, which means that everyone in a given population has an equal chance of being included. +

Now once a pollster has gathered a representative, random sample, then he or she makes sure that the makeup 组成；构成 of the sample matches the larger population and then makes adjustments if need be 必要时. So the percentages 百分比 of the samples should match the percentages of the population when it comes to demographic 人口统计的 categories 类别；种类 like male/female, race 种族, ethnicity 民族；族群, socioeconomic status 社会经济地位, etc. And once all those balances 平衡 have been achieved, then the pollster can measure their opinion on an issue and then generalize those responses 回应；反应 to the larger population that the sample represents. +

Now in a perfect world, the sample would match the general population's opinions exactly. But if you've been alive for more than five minutes, you already know that we do not in fact live in a perfect world. So that means there's always the possibility 可能性 of sampling error, which means that there is always a chance that the sample will not exactly represent the general population. However, in general, if a poll has a plus or minus three sampling error, that's considered 被认为；被视为 a good and representative poll. +

So getting a good sample is one way the pollsters know that the results are legitimate. Another way they strive 努力；力求 for accuracy 准确性 is by asking neutral 中立的；不偏不倚的 questions. And this just means that the questions are neither confusing 令人困惑的 nor leading 引导性的. Scientific pollsters take great care in making sure that their questions measure what they really want to know, because the way questions are worded 措辞 can have a big effect on results. For example, if you wanted to measure public opinion on COVID vaccines 疫苗, here are two ways to ask the question: "Should the government violate 侵犯；违背 people's personal liberty 自由 by requiring vaccination 接种疫苗 against COVID-19?" or "Should a COVID-19 vaccination be required?" Depending on how you word that question, the results will... uh... vary 变化；不同. +

Now the last thing we need to talk about is survey methodology 方法论；方法体系 and the different ways pollsters can measure public opinion. And for our purposes, you just need to know two. First is the mass survey 大规模调查, and really most of what I've said in this video applies to the mass survey technique. This is when pollsters put together a questionnaire 问卷；调查表 that can be given to as many people as possible. And since they're going big with a survey like this, mass surveys can really only measure quantitative data 定量数据. So if a group wants to know how many people favor 支持；赞成 a change in immigration 移民 laws, that's what a mass survey is for. +

On the other end of the spectrum 范围；系列 is the focus group 焦点小组, which is when pollsters measure the opinion of a small group of people. This method is better for collecting qualitative data 定性数据, which provides more in-depth 深入的 data about how people feel and think. The benefit 优点；好处 of a focus group is that respondents 被调查者 can flap their mouth hole (俚语，意为“说话”) at length 长时间地；充分地 about their opinions, rather than just being confined 限制 to a couple of options on a survey question. Now maybe it's obvious, but focus groups aren't considered scientific polling because their opinions can't really be statistically 统计地 generalized to the larger population. However, focus groups can help a candidate refine 改进；完善 his or her message. +

Okay, thanks for watching. Click right here and grab a review packet 学习资料包, which is going to help you get an A in your class and a five on your exam in May. And if this video helped you and you want me to keep making them, then by all means 一定；尽管 subscribe 订阅 and I shall oblige 乐意效劳. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史课程。我们一直在学习美国大学预修课程（AP）政府课程的第四单元，在这个视频中，意味着是时候讨论我们如何衡量公众舆论了。所以，如果你准备好以低抽样误差来汲取知识，那我们开始吧。 +

这个视频很简单，我们要做的是：描述科学民意调查的要素。好的，到目前为止，在这个单元中，我们一直在讨论人们是如何形成特定政治信仰的，而各种各样的人——尤其是政治家——都有兴趣了解这些信仰。那么他们要怎么做呢？嗯，我们衡量公众舆论的主要方式是通过科学民意调查，也就是说我们询问人们的信仰，并且希望他们能告诉我们。 +

民意调查者从这些调查中获得的信息对选举和政策辩论有很大影响。如果一个民意调查是以科学严谨的方式进行的，那么它们就是我们衡量公众舆论的最佳工具。这个过程包括撰写尽可能没有偏见的问题，然后将这些问题呈现给一个随机抽取的小群体，然后将这些结果推广到更大的人群中。 +

所以首先让我们看看民意调查者衡量公众舆论的不同方式，然后我们再看看他们如何知道这些结果是准确的。有四种不同类型的民意调查是你需要了解的。第一种是意见调查，它听起来是什么样就是什么样。民意调查者使用意见调查来了解公众对某个特定话题的看法，或者洞察人们对某些候选人或政策的感受。所以当一个候选人开始发表演讲并承诺某些事情时，并不是因为候选人凭空想出这些政策。不，他们关注了民意调查，并根据人们真正想要的东西做出承诺。 +

第二种是基准调查。这是在候选人竞选开始时进行的调查。这为竞选活动提供了一个基准，他们可以将未来的调查与之比较，看看候选人的表现如何。基准调查通常关注候选人的宣传信息。当他们弄清楚哪些信息能引起选民的共鸣时，他们会在这些信息上花费更多时间，而放弃其他信息。 +

第三种是跟踪调查。这些是随着时间进行的调查，通常针对同一组人，这能提供关于这个群体对某个问题的看法的信息。这有助于候选人制定竞选承诺，尤其是在选举临近的时候。 +

第四种是投票站调查（入口调查和出口调查）。这些是在投票站点进行的调查，询问人们的投票情况。如果在人们进去投票之前询问他们，这被称为入口调查。如果在他们投票之后询问，这就是出口调查。这类调查是最理想的调查之一，因为它们衡量的是实际投票的人，而不仅仅是那些可能说自己会投票但出于某种原因没有投票的人。“嗯，今天是选举日，但我的脚趾可不会自己刮毛（意思是有些人找借口不投票）。” +

好的，这些就是你需要了解的不同类型的民意调查，它们的目的是衡量公众舆论。现在真正的问题是：我们如何知道这些衡量结果是合理的呢？嗯，简短的回答是，好的民意调查是以科学严谨的方式进行的。那么他们是怎么做的呢？ +

嗯，你首先需要知道的是研究人员如何选择他们要询问的人，为此我们要谈谈抽样技术。民意调查者总是通过样本测量公众舆论。我的意思是，想想看：如果你是一个民意调查者，并且你想衡量公众舆论，那么最好的方法就是询问每个达到投票年龄的美国人对某个问题的看法。但那样的话，你就要调查大约2.56亿人，而且如果你想在少于400年的时间内得到结果，你就需要测量这些人的一个样本的意见。 +

为了做到科学严谨，一个样本首先需要具有代表性，也就是说样本需要具有与它所测量的更大人群相同的特征。所以如果你想知道千禧一代对大麻合法化的看法，那么你需要询问一小部分千禧一代，而不是老年人。样本还需要是随机的，这意味着给定人群中的每个人都有平等的机会被纳入样本。 +

一旦民意调查者收集了一个有代表性的随机样本，然后他或她要确保样本的构成与更大的人群相匹配，如果需要的话进行调整。所以在性别、种族、民族、社会经济地位等人口统计类别方面，样本的百分比应该与人群的百分比相匹配。一旦实现了所有这些平衡，民意调查者就可以测量样本对某个问题的意见，然后将这些回答推广到样本所代表的更大人群中。 +

在一个完美的世界里，样本会与总体人群的意见完全匹配。但如果你已经生活了五分钟以上，你就已经知道我们实际上并不生活在一个完美的世界里。这意味着总是存在抽样误差的可能性，也就是说样本总是有可能不能完全代表总体人群。然而，一般来说，如果一个民意调查的抽样误差在正负3%以内，那它就被认为是一个好的、有代表性的民意调查。 +

所以获得一个好的样本是民意调查者知道结果合理的一种方式。他们努力确保准确性的另一种方式是提出中立的问题。这意味着问题既不应该令人困惑，也不应该有引导性。科学的民意调查者非常小心地确保他们的问题能测量到他们真正想知道的东西，因为问题的措辞对结果有很大影响。例如，如果你想测量公众对新冠疫苗的看法，有两种提问方式：“政府是否应该通过要求接种新冠疫苗来侵犯人们的个人自由？” 或者 “是否应该要求接种新冠疫苗？” 根据你对问题的措辞，结果会……呃……有所不同。 +

最后我们需要讨论的是调查方法以及民意调查者测量公众舆论的不同方式。就我们的目的而言，你只需要知道两种。第一种是大规模调查，实际上我在这个视频中所说的大部分内容都适用于大规模调查技术。这是指民意调查者整理出一份问卷，并尽可能多地分发给人们。由于他们进行的是大规模调查，大规模调查实际上只能测量定量数据。所以如果一个团体想知道有多少人支持移民法的改变，这就是大规模调查的用途。 +

另一种是焦点小组调查，这是指民意调查者测量一小群人的意见。这种方法更适合收集定性数据，它能提供关于人们感受和想法的更深入的数据。焦点小组调查的好处是，受访者可以详细阐述他们的意见，而不仅仅局限于调查问题中的几个选项。也许很明显，但焦点小组调查不被认为是科学的民意调查，因为他们的意见实际上不能从统计学上推广到更大的人群。然而，焦点小组调查可以帮助候选人完善他或她的宣传信息。 +

好的，感谢观看。点击这里获取复习资料包，它将帮助你在课堂上得A，在五月份的考试中得5分。如果这个视频对你有帮助，并且你希望我继续制作这样的视频，那么一定要订阅，我会照做的。海姆勒（Heimler）下线。 + 

'''

== pure

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 4 of the AP Government curriculum, and in this video that means it's time to talk about how we measure public opinion. So if you're ready to get them brain cows milked with a low sampling error, then let's get to it.

So this video is simple, and here's what we're trying to do: describe the elements of a scientific poll. Okay, now so far in this unit we've been talking about how people come to hold certain political beliefs, and all sorts of people -- especially politicians -- are interested in knowing those beliefs. So how can they do that? Well, the main way we measure public opinion is through scientific polls, which is to say we ask people what they believe and hopefully they tell us.

The information that pollsters get from these polls have a big impact on elections and policy debates. If a poll is created with scientific rigor, then they are the best tools we have for measuring public opinion. The process includes writing questions that are as free from bias as possible, and then presenting them to a small randomized group of people, and then generalizing those results to the larger population.

So first let's have a look at the different ways pollsters measure public opinion, and then we'll have a look at how they know those results are accurate. So there are four different kinds of polls that you need to know. First is an opinion poll, which is exactly what it sounds like. Pollsters use an opinion poll to get a feel for the public's opinion on a certain topic or discerning people's feelings on certain candidates or policies. So when a candidate starts making speeches and promising certain things, it's not because the candidate is just pulling those policies out of thin air. No, they have paid attention to the opinion polls and are now making promises based on what the people actually want.

Second is a benchmark poll. This is a poll taken at the beginning of a candidate's run. This gives the campaign a benchmark against which they can compare future polls to see how the candidate is faring. Benchmark polls often focus on a candidate's messaging. When they figure out which messages are resonating with voters, they'll spend more time on those messages and throw the others away.

Third is a tracking poll. These are polls that are conducted over time, usually with the same group of people, and that gives information on how the group feels about an issue. This helps a candidate shape his or her campaign promises, especially when the election is near.

And fourth, you have entrance and exit polls. And these are polls conducted at voting sites and ask people how they voted. If they ask them before a person goes in to vote, that's called an entrance poll. If they ask after they have voted, that's an exit poll. These kinds of polls are among the most desirable because they're measuring actual voters, not just people who may say they're gonna vote and then don't for whatever reason. "Well, it's election day but my toe here ain't gonna shave itself."

Okay, so those are the different kinds of polls you need to know, and their purpose is to measure public opinion. Now the real question is this: how do we know that these measurements are legitimate? Well, the short answer is that good polls are created with scientific rigor. So how do they do that?

Well, the first thing you need to know is how researchers choose the people they're going to ask, and for that let's talk about sampling techniques. Pollsters always measure public opinion by means of a sample. I mean, think about it: if you're a pollster and you want to measure public opinion, then the best way would be to ask every American of voting age what they think about an issue. But then you'd be surveying like 256 million people, and just in case you'd like those results in fewer than 400 years, you're gonna need to measure the opinion of a sample of those people.

Now in order to be scientifically rigorous, a sample first needs to be representative, which is to say the sample needs to have the same characteristics as the larger population that it's measuring. So if you want to know what millennials think about the legalization of marijuana, then you need to ask a small sample of millennials and not senior citizens. Now the sample also needs to be random, which means that everyone in a given population has an equal chance of being included.

Now once a pollster has gathered a representative, random sample, then he or she makes sure that the makeup of the sample matches the larger population and then makes adjustments if need be. So the percentages of the samples should match the percentages of the population when it comes to demographic categories like male/female, race, ethnicity, socioeconomic status, etc. And once all those balances have been achieved, then the pollster can measure their opinion on an issue and then generalize those responses to the larger population that the sample represents.

Now in a perfect world, the sample would match the general population's opinions exactly. But if you've been alive for more than five minutes, you already know that we do not in fact live in a perfect world. So that means there's always the possibility of sampling error, which means that there is always a chance that the sample will not exactly represent the general population. However, in general, if a poll has a plus or minus three sampling error, that's considered a good and representative poll.

So getting a good sample is one way the pollsters know that the results are legitimate. Another way they strive for accuracy is by asking neutral questions. And this just means that the questions are neither confusing nor leading. Scientific pollsters take great care in making sure that their questions measure what they really want to know, because the way questions are worded can have a big effect on results. For example, if you wanted to measure public opinion on COVID vaccines, here are two ways to ask the question: "Should the government violate people's personal liberty by requiring vaccination against COVID-19?" or "Should a COVID-19 vaccination be required?" Depending on how you word that question, the results will... uh... vary.

Now the last thing we need to talk about is survey methodology and the different ways pollsters can measure public opinion. And for our purposes, you just need to know two. First is the mass survey, and really most of what I've said in this video applies to the mass survey technique. This is when pollsters put together a questionnaire that can be given to as many people as possible. And since they're going big with a survey like this, mass surveys can really only measure quantitative data. So if a group wants to know how many people favor a change in immigration laws, that's what a mass survey is for.

On the other end of the spectrum is the focus group, which is when pollsters measure the opinion of a small group of people. This method is better for collecting qualitative data, which provides more in-depth data about how people feel and think. The benefit of a focus group is that respondents can flap their mouth hole at length about their opinions, rather than just being confined to a couple of options on a survey question. Now maybe it's obvious, but focus groups aren't considered scientific polling because their opinions can't really be statistically generalized to the larger population. However, focus groups can help a candidate refine his or her message.

Okay, thanks for watching. Click right here and grab a review packet, which is going to help you get an A in your class and a five on your exam in May. And if this video helped you and you want me to keep making them, then by all means subscribe and I shall oblige. Heimler out.

'''

