
= fd 03 - Brutus no.1
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimlich's History, and further welcome to another video in our foundational documents 基础文献 series for AP Government. In this video, we're going to be considering Brutus Number One 《布鲁图斯第一篇》. So if you're ready to get them brain cows milked participatory 参与式 style, well then let's get to it. +

So in the last video, I talked about Federalist 10 《联邦党人文集》第10篇, and the AP overlords （这里指课程主导者）are concerned that you understand the debate between that document and Brutus 1. Now by way of reminder, the Federalist Papers 《联邦党人文集》argued for the ratification 批准 of the Constitution 宪法, while the Anti-Federalist papers 反联邦党人文集 -- of which Brutus Number One is the first -- argued against ratification of the Constitution. And both sets of essays were published in New York newspapers to try to persuade the public one way or the other. +

Now while Federalist 10 argued for the merits 优点 of a republican-style government 共和制政府 for a large nation like the United States, Brutus is going to take an anti-constitutional dump all over that argument 对该论点进行全面抨击. And let's see how he does it. And by the way, there is a debate who actually wrote Brutus 1, so I'm just gonna call him Brutus. And if it helps you remember what this document is all about, just remember that Brutus was one of the guys who assassinated Julius Caesar 刺杀尤利乌斯·凯撒, who happened to lead a very powerful centralized government 强大的中央集权政府. Okay, so let's get into the document. +

The main question Brutus is attempting to answer is this: "The first question that presents itself on the subject is whether a confederated government 邦联制政府 be the best for the United States or not." Now a confederated government -- in case you don't know -- is the kind of government that the United States had under the Articles of Confederation 《邦联条例》. The states had all the power and the central government had very little. In fact, you might say that there were 13 governments in the early United States -- one for each state -- that were loosely tied together 松散地联系在一起 by a weak central authority 软弱的中央权力机构. +

Okay, so continuing: "Or in other words, whether the 13 United States should be reduced to one great republic, governed by one legislature 立法机构 and under the direction of one executive 行政机构 and judicial 司法机构, or whether they should continue 13 confederated republics under the direction and control of a supreme federal head for certain defined national purposes only." Okay, so the question is this: which is better for this new freedom-loving nation -- a confederacy of state governments 州政府组成的邦联 or a powerful central government 强大的中央政府? And Brutus argued in no uncertain terms 毫不含糊地 that a confederacy is better than the republic that the Constitution would establish. +

There are several arguments Brutus makes in support of this claim, chief among them is that oh-so-odious 极其讨厌的 necessary and proper clause 必要且适当条款 in Article 1 Section 8 of the Constitution, which says that Congress can make any law which shall be necessary and proper to the execution of its enumerated powers 列举的权力. And causing a further stench 令人厌恶的事物 in Brutus's nostrils is the supremacy clause 至上条款 in Article 6, which says that federal laws have greater authority 更高权威 than state laws. +

So what's the problem with that? Well, Brutus, help me out: "It appears from these articles that there is no need of any intervention of the state governments between the Congress and the people to execute any one power vested in the general government 授予联邦政府的权力, and that the constitution and laws of every state are nullified 废除 and declared void 无效 so far as they shall be inconsistent with this constitution." And so what happens in that case? "All power that is reserved for the individual states must very soon be annihilated 消灭, except so far as they are barely necessary for the organization of the general government." +

So Brutus's main concern 主要担忧 is that by creating a central authority who can -- by the necessary and proper clause -- pass any law imaginable 想象得到的法律, and by which the supremacy clause can crush any state law under its big hairy feet 彻底压制州法律, that state governments will just shrivel up and die 萎缩消亡. But this is not just theoretical for Brutus. He gives several examples of how this death of state power could happen, but we'll only look at the most pressing example -- the collection of taxes 征税. +

"In the business therefore of laying and collecting taxes, the idea of confederation 邦联制 is totally lost, and that of one entire republic 单一共和国 is embraced. It is proper here to remark that the authority to lay and collect taxes is the most important of any power that can be granted. It connects with almost all other powers. Everyone who has thought on this subject must be convinced that but small sums of money can be collected in any country by direct taxes 直接税. Hence, when the federal government begins to exercise the right of taxation in all its parts, the legislatures of the several states will find it impossible to raise monies to support their own governments. Without money, they cannot be supported, and they must dwindle away 逐渐缩小, and as before observed, their powers will be absorbed in that of the general government." +

In other words, any government that exists can only collect a small amount of taxes -- otherwise the citizens will grow weary of that taxation 对征税感到厌烦 and throw the government off. So if the federal government is going to collect taxes, and there's only a small amount that people will tolerate 容忍, how will the states also collect taxes? And if states cannot collect taxes, they'll shrivel up and die, and now you've got one big powerful government left in their way. +

Now Brutus goes on to make the same argument about the federal courts 联邦法院. If the federal courts trump 凌驾于…之上 state courts, then state courts will soon be rendered obsolete and unnecessary 变得过时且不必要. And then the final part of the argument is about the size of the nation and how by its sheer girth 巨大规模, a republican form of government 共和政体 is not well suited to be installed 不适合实行. And Brutus pulls out the big guns 拿出有力论据 for this argument, quoting the Baron de Montesquieu 孟德斯鸠男爵 who said in his treatise The Spirit of the Laws 《论法的精神》: "It is natural to a republic to have only a small territory 疆域, otherwise it cannot long subsist 存续." +

Wait, why can't a republican government work in a big territory with a lot of people? Well, Brutus will answer that question with a question: "Is it practicable 可行的 for a country so large and so numerous as they will soon become to elect a representation that will speak to their sentiments 反映他们的想法 without their becoming so numerous as to be incapable of transacting public business 处理公共事务? It certainly is not." Okay, he answered it with a question and an answer, but whatever. His point is with a nation as large as the United States -- both in territory and in people -- how could elected representatives possibly keep their fingers on the pulse of 了解 everyone whom they represent? +

And Brutus's answer is simple: it's not possible. And the problem in that situation is as follows: "Confidence which the people have in their rulers in a free republic arises from their knowing them, from their being responsible to them for their conduct 行为负责, and from the power they have of displacing them when they misbehave 行为不当. But in a republic of the extent of this continent, the people in general will be acquainted with very few of their rulers. The people at large would know very little of their proceedings 施政情况, and it would be extremely difficult to change them." +

Okay, that's what you need to know about Brutus 1. If you need help getting an A in your class and a five on your exam in May, then click right over here and grab a review packet. For more of the videos on the foundational documents, you can have a look right here. And if you want me to keep making these videos, then let me know by subscribing 订阅. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史频道，也欢迎来到美国大学预修课程（AP）政府课程基础文献系列的另一个视频。在这个视频中，我们将探讨《布鲁图斯》第一篇（Brutus Number One）。所以，如果你准备好以 “参与” 的方式激发自己的思维，那么我们就开始吧。 +

所以在上一个视频中，我谈到了《联邦党人文集》第十篇（Federalist 10），而且AP课程的主导者希望你理解这篇文献与《布鲁图斯》第一篇之间的争论。现在提醒一下，《联邦党人文集》主张批准宪法，而反联邦党人的文章（《布鲁图斯》第一篇是其中的第一篇）则反对批准宪法。这两组文章都发表在纽约的报纸上，试图从不同方面说服公众。 +

现在，《联邦党人文集》第十篇主张像美国这样的大国实行共和制政府的优点，而《布鲁图斯》则对这一论点进行了批判。我们来看看他是怎么做的。顺便说一下，关于到底是谁写了《布鲁图斯》第一篇存在争议，所以我就称作者为布鲁图斯（Brutus）。如果这能帮助你记住这篇文献的主旨，那就记住布鲁图斯是刺杀尤利乌斯·凯撒（Julius Caesar）的人之一，而凯撒曾领导着一个非常强大的中央政府。好的，那我们来深入探讨这篇文献。 +

布鲁图斯试图回答的主要问题是：“在这个问题上首先出现的是，一个邦联制政府对美国来说是不是最好的？” 现在，邦联制政府（如果你不知道的话）是美国在《邦联条例》（Articles of Confederation）下实行的那种政府形式。各州拥有所有权力，而中央政府权力很小。事实上，你可以说在早期美国有13个政府（每个州一个），它们由一个薄弱的中央权力机构松散地联系在一起。 +

好的，继续：“换句话说，13个美国是应该变成一个由一个立法机构治理、在一个行政和司法机构领导下的大共和国，还是应该继续成为13个邦联共和国，只在一个最高联邦首脑的指导和控制下，为某些特定的国家目标而存在呢？” 好的，问题是：对于这个热爱自由的新国家来说，是州政府组成的邦联更好，还是一个强大的中央政府更好呢？布鲁图斯毫不含糊地认为邦联比宪法所建立的共和国更好。 +

布鲁图斯提出了几个论点来支持这一主张，其中最主要的是宪法第一条第八款中那个非常讨厌的 “必要且适当” 条款，该条款规定国会可以制定任何对于执行其列举权力来说必要且适当的法律。让布鲁图斯更加反感的是宪法第六条中的 “最高权力” 条款，该条款规定联邦法律比州法律更具权威性。 +

那么这有什么问题呢？嗯，布鲁图斯来帮我说明：“从这些条款可以看出，在国会和人民之间不需要州政府的干预来执行赋予联邦政府的任何一项权力，而且每个州的宪法和法律，只要与这部宪法不一致，就会被废除并宣布无效。” 那么在那种情况下会发生什么呢？“除了那些对于组织联邦政府来说绝对必要的权力之外，所有留给各个州的权力很快就会被消灭。” +

所以布鲁图斯主要担心的是，通过 “必要且适当” 条款，一个中央权力机构可以通过任何想象得到的法律，并且通过 “最高权力” 条款可以践踏任何州法律，这样州政府就会萎缩消亡。但对布鲁图斯来说，这不仅仅是理论上的担忧。他举了几个州权力可能消亡的例子，但我们只看最紧迫的例子 —— 税收的征收。 +

“因此，在征税和收税这件事上，邦联的概念完全被抛弃，而一个完整共和国的概念被接受。在这里有必要指出，征税和收税的权力是被授予的所有权力中最重要的权力。任何思考过这个问题的人都必须相信，在任何国家，直接税只能征收很少的钱。因此，当联邦政府开始全面行使征税权时，各个州的立法机构会发现无法筹集资金来维持自己的政府。没有钱，它们就无法维持下去，它们必然会逐渐消亡，正如前面所观察到的，它们的权力将被联邦政府吸收。” +

换句话说，任何存在的政府只能征收少量的税 —— 否则公民就会对税收感到厌倦并推翻政府。所以如果联邦政府要征税，而人们只能容忍少量的税收，那么各州又如何征税呢？如果各州无法征税，它们就会萎缩消亡，然后就只剩下一个强大的政府了。 +

现在布鲁图斯接着就联邦法院提出了同样的论点。如果联邦法院凌驾于州法院之上，那么州法院很快就会变得过时且不必要。争论的最后一部分是关于国家的规模，以及从国家的规模来看，共和制政府不太适合建立。布鲁图斯在这个论点上拿出了有力的论据，他引用了孟德斯鸠男爵（Baron de Montesquieu）在他的《论法的精神》（The Spirit of the Laws）一书中的话：“对于一个共和国来说，拥有小块领土是很自然的，否则它无法长久存续。” +

等等，为什么共和制政府在一个领土广大、人口众多的国家行不通呢？嗯，布鲁图斯用一个问题来回答这个问题：“对于一个像美国这样领土广大、人口众多的国家来说，选举出一个能表达民众情感的代表机构，同时又不会因为代表人数过多而无法处理公共事务，这可行吗？当然不可行。” 好吧，他用一个问题和一个答案来回答了这个问题，但不管怎样。他的观点是，对于像美国这样领土和人口规模的国家来说，当选代表怎么可能了解他们所代表的每一个人的想法呢？ +

布鲁图斯的答案很简单：这是不可能的。在那种情况下的问题如下：“在一个自由的共和国里，人民对统治者的信任源于他们了解统治者，源于统治者对自己的行为向人民负责，以及源于人民在统治者行为不当时有权罢免他们。但在一个像这片大陆这么大的共和国里，普通民众几乎不了解他们的统治者。广大人民对统治者的行为了解甚少，而且要更换他们也极其困难。” +

好的，这就是你需要了解的关于《布鲁图斯》第一篇的内容。如果你想在课堂上取得A的成绩，并在五月份的考试中获得5分，那么点击这里获取复习资料包。如果你想观看更多关于基础文献的视频，可以在这里查看。如果你希望我继续制作这样的视频，那就通过订阅告诉我。海姆勒，退出。 + 

'''

== pure

Hey there, and welcome back to Heimlich's History, and further welcome to another video in our foundational documents series for AP Government. In this video, we're going to be considering Brutus Number One. So if you're ready to get them brain cows milked participatory style, well then let's get to it.

So in the last video, I talked about Federalist 10, and the AP overlords are concerned that you understand the debate between that document and Brutus 1. Now by way of reminder, the Federalist Papers argued for the ratification of the Constitution, while the Anti-Federalist papers -- of which Brutus Number One is the first -- argued against ratification of the Constitution. And both sets of essays were published in New York newspapers to try to persuade the public one way or the other.

Now while Federalist 10 argued for the merits of a republican-style government for a large nation like the United States, Brutus is going to take an anti-constitutional dump all over that argument. And let's see how he does it. And by the way, there is a debate who actually wrote Brutus 1, so I'm just gonna call him Brutus. And if it helps you remember what this document is all about, just remember that Brutus was one of the guys who assassinated Julius Caesar, who happened to lead a very powerful centralized government. Okay, so let's get into the document.

The main question Brutus is attempting to answer is this: "The first question that presents itself on the subject is whether a confederated government be the best for the United States or not." Now a confederated government -- in case you don't know -- is the kind of government that the United States had under the Articles of Confederation. The states had all the power and the central government had very little. In fact, you might say that there were 13 governments in the early United States -- one for each state -- that were loosely tied together by a weak central authority.

Okay, so continuing: "Or in other words, whether the 13 United States should be reduced to one great republic, governed by one legislature and under the direction of one executive and judicial, or whether they should continue 13 confederated republics under the direction and control of a supreme federal head for certain defined national purposes only." Okay, so the question is this: which is better for this new freedom-loving nation -- a confederacy of state governments or a powerful central government? And Brutus argued in no uncertain terms that a confederacy is better than the republic that the Constitution would establish.

There are several arguments Brutus makes in support of this claim, chief among them is that oh-so-odious necessary and proper clause in Article 1 Section 8 of the Constitution, which says that Congress can make any law which shall be necessary and proper to the execution of its enumerated powers. And causing a further stench in Brutus's nostrils is the supremacy clause in Article 6, which says that federal laws have greater authority than state laws.

So what's the problem with that? Well, Brutus, help me out: "It appears from these articles that there is no need of any intervention of the state governments between the Congress and the people to execute any one power vested in the general government, and that the constitution and laws of every state are nullified and declared void so far as they shall be inconsistent with this constitution." And so what happens in that case? "All power that is reserved for the individual states must very soon be annihilated, except so far as they are barely necessary for the organization of the general government."

So Brutus's main concern is that by creating a central authority who can -- by the necessary and proper clause -- pass any law imaginable, and by which the supremacy clause can crush any state law under its big hairy feet, that state governments will just shrivel up and die. But this is not just theoretical for Brutus. He gives several examples of how this death of state power could happen, but we'll only look at the most pressing example -- the collection of taxes.

"In the business therefore of laying and collecting taxes, the idea of confederation is totally lost, and that of one entire republic is embraced. It is proper here to remark that the authority to lay and collect taxes is the most important of any power that can be granted. It connects with almost all other powers. Everyone who has thought on this subject must be convinced that but small sums of money can be collected in any country by direct taxes. Hence, when the federal government begins to exercise the right of taxation in all its parts, the legislatures of the several states will find it impossible to raise monies to support their own governments. Without money, they cannot be supported, and they must dwindle away, and as before observed, their powers will be absorbed in that of the general government."

In other words, any government that exists can only collect a small amount of taxes -- otherwise the citizens will grow weary of that taxation and throw the government off. So if the federal government is going to collect taxes, and there's only a small amount that people will tolerate, how will the states also collect taxes? And if states cannot collect taxes, they'll shrivel up and die, and now you've got one big powerful government left in their way.

Now Brutus goes on to make the same argument about the federal courts. If the federal courts trump state courts, then state courts will soon be rendered obsolete and unnecessary. And then the final part of the argument is about the size of the nation and how by its sheer girth, a republican form of government is not well suited to be installed. And Brutus pulls out the big guns for this argument, quoting the Baron de Montesquieu who said in his treatise The Spirit of the Laws: "It is natural to a republic to have only a small territory, otherwise it cannot long subsist."

Wait, why can't a republican government work in a big territory with a lot of people? Well, Brutus will answer that question with a question: "Is it practicable for a country so large and so numerous as they will soon become to elect a representation that will speak to their sentiments without their becoming so numerous as to be incapable of transacting public business? It certainly is not." Okay, he answered it with a question and an answer, but whatever. His point is with a nation as large as the United States -- both in territory and in people -- how could elected representatives possibly keep their fingers on the pulse of everyone whom they represent?

And Brutus's answer is simple: it's not possible. And the problem in that situation is as follows: "Confidence which the people have in their rulers in a free republic arises from their knowing them, from their being responsible to them for their conduct, and from the power they have of displacing them when they misbehave. But in a republic of the extent of this continent, the people in general will be acquainted with very few of their rulers. The people at large would know very little of their proceedings, and it would be extremely difficult to change them."

Okay, that's what you need to know about Brutus 1. If you need help getting an A in your class and a five on your exam in May, then click right over here and grab a review packet. For more of the videos on the foundational documents, you can have a look right here. And if you want me to keep making these videos, then let me know by subscribing. Heimler out.

'''

