
= eco 19.11 (08-09)
:toc:

---


== 19.11.08 The migrants who made China an industrial giant `谓` face a grim retirement

Those who built the new China are still suffering for it

让中国成为工业巨头的农民工, 面临着严峻的退休生活

Nov 30th 2019

EVEN IN A China (filled with the shiny(a.)(`=bright and reflect light`) and the new), the southern city of Guangzhou *stands out*(`=very noticeable 突出;显眼`).

[A generation ago] it was a smoggy(a.)(`=is badly affected by smog`), sweltering(a.)(`=非常热，让你感到不舒服`) sprawl(n.)(`=一大片被建筑物覆盖的地区，以一种丑陋的方式从城市一直蔓延到乡村`) of factories and workshops 车间；工场；作坊, a bit embarrassed by its history as a semi-colony of Western powers, who knew it as Canton 广州.

Now Guangzhou *aspires(`=有强烈的愿望去实现或成为某事; 渴望（成就）；有志（成为）`) to be* a hub(`=某一特定地点或活动的中心和最重要的部分;活动中心`) of global commerce(`=贸易，特别是国与国之间的贸易;商品和服务的买卖`).

It boasts(`=自夸;有（值得自豪的东西）`) the 600-metre tall Canton Tower, an opera house designed by Zaha Hadid and high-speed trains that can reach Beijing, 2,300km to the north, in just eight hours.

Yet Guangzhou’s rise(n.) *had* human costs.

The province of Guangdong, of which it is the capital, is a hotbed(n.)(`=（坏事、暴力等的）温床`) of worker unrest(n.一种政治形势, 人民愤怒并很可能产生抗议或斗争; 动荡,动乱), with 129 strikes(`=侵袭;罢工`) and protests(`=（公开）强烈反对；抗议`) *logged*(`=把信息记录在正式的记录中`) this year *by* China Labour Bulletin(`=对某事重要的官方声明;公告；简报`) (CLB 中国劳工通讯), a Hong Kong-based(`=基地（或总部）在`) monitor(`=（尤指派往国外的）监督员，核查员/者/机构`) of workers’ rights 劳工权益.

`主` A growing number *involve* workers (reaching retirement age), who `谓` discover that -- because they *fall through*(`=to not be completed, or not happen 落空；失败；成为泡影`) gaps in the welfare safety-net, or because employers(`=雇主`)  *skimped(`=试图在某事物上花费比实际需要更少的时间、金钱等; 节省，吝惜`) on* pension(`=养老金；退休金；抚恤金`) contributions(`=（给雇主或政府用作医疗保险、养老金等津贴的）定期缴款`) -- `宾从` a meagre(a.)(`=数量少，质量差`) future *awaits*(v.)(`=to wait for sb/sth`).

越来越多的人(包括达到退休年龄的工人)，他们发现 -- 因为他们在福利保障网络上的缺口，或者因为雇主在养老金上的克扣 -- 一个渺茫的未来在等待着他们。

====
- sprawl => 可能最终来自 PIE*sper,播洒，散播，展开，词源同 spark,spread.引申词义蔓延，杂乱的扩张。 拼写受 crawl 影响。
- unrest => un- +‎ rest
- bulletin => bull, 教皇文件，官方文件，见bill, 议案，bull, 教皇训谕。
- unrest : n.  a political situation in which people are angry and likely to protest or fight 动荡；动乱；骚动
* *There is growing unrest* in the south of the country. 这个国家的南方日益动荡不安。

- *fall through* : to not be completed, or not happen 落空；失败；成为泡影
* *Our plans fell through* because of lack of money. 我们的计划由于缺钱而落空了。
====


`主` China’s migrant workers, who [for 30 years] *have left* inland villages and townships 镇区 *for* coastal(a.)沿海的；靠近海岸的`) boomtowns 新兴城镇 , `谓` are growing old.

Their average age is now over 40.

Nearly a quarter are over 50.

`主` More than a tenth of all strikes, sit-ins(n.)静坐抗议；静坐示威  and protests (*recorded by* CLB in 2018 and 2019) `谓` involved *rows(n.)个人、组织等之间对某事的严重分歧 over* pensions and social insurance.

CLB在2018年和2019年记录的所有罢工、静坐和抗议中，超过十分之一涉及养老金和社会保险问题。

`主` The latest national survey 民意调查;总体研究；全面评述 on living conditions of the urban 城镇的 and rural 乡村的；农村的 elderly(a.)老人；上了年纪的人, published in 2018 on the orders of the Communist Party’s Central Committee, `谓` *describes* startling(a.)非常不寻常和令人惊讶的;让人震惊的 inequalities 不平等; 不公平.

`主` About 100m retired(a.)已退休的；已退职的 Chinese *covered by* the unified 统一的;使成一体的 basic urban pension system, *to which* most full-time 全职的(地) urban workers *contribute*, `谓` received [average monthly] benefits of 2,600 yuan ($369) in 2016.

But about 150m retirees 退休人员 had to *make do with* 勉强对付,凑合着应对 a state pension scheme *open to* both urban and rural residents.

They received [on average] 117 yuan ($17) a month, a pittance(`=微薄的工资；极少的报酬`) even in a poor region.

====
- *row(n.) (about/over sth)* : a serious disagreement between people, organizations, etc. about sth 严重分歧；纠纷
* *A row* has broken out *over education*. 在教育问题上出现了严重分歧。
- national survey on The living conditions of The urban and rural elderly 《全国城乡老年人生活状况调查报告》

- *make do (with sth)* : to manage with sth that is not really good enough 凑合；将就
* We were in a hurry *so we had to make do with a quick snack*. 我们很匆忙，只好将就着来了点小吃。

- pittance => 来自古法语pitance,可怜，同情，施舍，词源同pity.-ance,名词后缀。引申词义微薄的工资。
====


There are 288m migrant *workers* in China, of whom 173m *work far from* their home towns.

In theory, they *should enjoy* the same social protections *as* urban Chinese (*with* permanent residence permits(n.)给予某人做某事的权利的官方文件，尤指在有限时间内; 许可证，特许证（尤指限期的）) who live in big cities like Guangzhou. They do not.

====
- permanent residence permit 永久居留许可证
====

从理论上讲，他们应该享受与在广州等大城市拥有永久居住证的中国城市居民同等的社会保障。但他们没有。

Today’s 40- and 50-something （表示不确切的描述或数量）大致，左右 Chinese migrants are a “lost generation”, argues Mark Frazier of the New School in New York.

They fall(v.)突然倒下,跌倒; 被打败；沦陷; 阵亡；被击毙; 进入（某状态）；开始变成（某事物） *between* the oldest, pioneering 先驱性的；探索性的 migrant workers (who were expected to *head back to* 返回 the countryside 乡村；农村 in retirement(n.
)退休；退休年龄 *to eke out a living* 设法用很少的钱生活; 竭力维持生计；勉强度日 from tiny plots (专用的)小块土地 of land), *and* today’s 20-something workers, who *are less inclined*(a.)有…倾向；很可能; 想（做某事） to seek distant factory jobs /and *are more likely* to be covered by social-security 社会保障制度 protections from a patchwork 由许多不同的部件组成的东西; 拼凑之物;拼缝物 of new labour laws and insurance schemes.

Few *see* the current system *as* sustainable(a.)这种情况可以持续很长一段时间的;可持续的, amid 在…中间, 或在…期间，尤指引起兴奋或恐惧的 gloomy(a.)对未来的成功和幸福不抱太大希望; 前景黯淡的；悲观的 statistics about falling(a.)(总数、价值、强度或实力等)下降的 birth rates and the shaky(a.)颤抖的(身体发抖，感觉虚弱，因为你生病了)；颤巍巍的;不稳固的；摇晃的 finances of the main urban pension fund: the Chinese Academy of Social Sciences *predicts* it will *go bust* 破产;打破；摔碎 by 2035.

Plans are afoot(a.)(`=being planned; happening 在计划中；进行中`) to increase China’s retirement age, which is normally 60 for men, 55 for women in white-collar jobs /and 50 for female blue-collar workers, though the rules *vary [by region]*.

几乎没有人认为目前的体系是可持续的，因为悲观的统计数据显示，出生率在下降，而主要城市养老基金的财务状况也不稳定:中国社会科学院(Chinese Academy of Social Sciences)预测，到2035年，这个体系将会破产。中国正在酝酿提高退休年龄的计划。中国的退休年龄通常为男性60岁，白领女性55岁，蓝领女性50岁。尽管规则因地区而异。

====
- something : ( informal ) used to show that a description or an amount, etc. is not exact （表示不确切的描述或数量）大致，左右
* a new comedy aimed at *thirty-somethings (= people* between thirty and forty years old) 一部以三十几岁的人为主要观众的新喜剧
* She called *at something after ten o'clock*. 她十点多钟来过电话。
* She found herself *something of a (= to some degree a) celebrity*. 她发现自己差不多成名人了。

- eke => 来自PIE*aug, 增加，词源同augment.
- *eke sth out* : to make a small supply of sth such as food or money last longer by using only small amounts of it （靠节省用量）使…的供应持久；节约使用 +
* She managed *to eke out her student loan* till the end of the year. 她想方设法节约用钱使学生贷款维持到了年底。 +
- *eke a living, etc*. : to manage to live with very little money 竭力维持生计；勉强度日

- shaky => 来自 shake,摇动，摇晃，-y,形容词后缀。
* *Her voice sounded shaky*(a.)(`=shaking and feeling weak because you are ill/sick, emotional or old 颤抖的；颤巍巍的`) on the phone. 电话里她的声音听着发颤。
* That ladder *looks a little shaky*(a.)(`=not firm or safe; not certain 不稳固的；不牢靠的；摇晃的；不确切的`). 这梯子看来不大牢靠。
* Her memories of the accident *are a little shaky*. 那次事故她记不太清楚了。
* *Business is looking shaky*(a.)(`=not seeming very successful; likely to fail 不大出色的；成问题的；可能失败的`) at the moment. 从目前看，业务举步维艰。

- bust
* The lights *are busted*(v.)(`=The lights are busted. 灯泡被砸碎了。`). 灯泡被砸碎了。
* Come out, or *I'll bust the door down*! 出来，不然我就砸门了！

====

None of those plans will help a group of older workers (who spoke to Chaguan 茶馆栏目 recently in Guangdong).

The seven women and one man showed hands *too* damaged by factory work *to* pour tea without shaking.

They *shared* stories of parental(a.)与父母或父母有关的,父母的 guilt *after failing to return home* for two or three years at a time 一次, leaving children *to be brought up* 养育成人,带大 by grandparents.

Even during the spring festival, an occasion (某事发生的) 时候; 场合 for family reunions, there was valuable(a.)值钱的、贵重的 overtime(n.)加班;加班费;加班的时间 to be earned, said a 50-year-old woman from Hubei province.

Besides, returning to the village *would have involved* long train journeys (尤指长途)旅行，行程 /and *buying* clothes, shoes and other gifts *for* many relatives.

“We spent 20 spring festivals here,” she said wistfully(ad.) 伤心地想着你想要拥有的东西，尤其是那些过去的你再也无法拥有的东西; 伤感的；（对已不可能发生之事）徒然神往的.

Unfortunately, before she reached retirement age in September, she learned that she could not draw her full pension in Guangdong because she began to make social-insurance payments 付款；支付 after she was 40.

If she had local residency （在他国的）居住权，居留许可 she could make back-payments towards the 15 years of contributions （给雇主或政府用作医疗保险、养老金等津贴的）定期缴款 needed.

As a migrant, her only option *was* to return to Hubei, where her pension might come to 600 yuan ($85) a month. She *compared* 表明…与…相似；将…比作; 作比较,以得出异同 her fate *to* an old, bitter 使你感到非常不快乐;由巨大的不幸引起的; 味苦的 saying: “Unharness(v.)给(马)卸下挽具 the donkey from the grindstone (圆形的)磨石；砂轮, then butcher(v.)把动物杀了，然后切碎当肉吃;屠宰；宰杀 it.”

====
- butcher => 屠夫；肉贩. 来自buck, 雄鹿, 公羊。插入字母t. 卖羊肉的人。
====

Another woman had worked at a handbag factory owned by Simone, a South Korean firm, for nearly 20 years. She alleged （未提出证据）断言，指称，声称 that her employer had failed to make the correct payments into a state housing-savings fund 住房储蓄基金 that serves as a second pension *for many* 对于许多人来说.

After she complained, she said the firm had denied her overtime and warned other workers to avoid 回避；避开；躲避 her.

Simone denies these allegations （无证据的）说法，指控. It says it takes employee benefits seriously and “strictly follows” and even *exceeds* 比法律或命令等允许你做的更多; 超越（法律、命令等）的限制 China’s labour-law requirements.

====
- exceed : V-T If you exceed a limit or rule, *you go beyond it*, even though you are not supposed to or it is against the law. 超越 (限制、规定) +
-> *She was exceeding the speed limit* (= driving faster than is allowed) . 当时她超速驾驶。 +
-> The officers *had exceeded their authority*. 这些官员超越了他们的权限。
====

A people’s republic, for the benefit of bosses

The eight workers had varied(a.)各种各样的；形形色色的；不相同的 problems, but all *described* a system in which social stability is the authorities’ guiding 提供建议和帮助的;对人有很大影响的 obsession 使人痴迷的人（或物）.

这八名工人有各种各样的问题，但他们都描述了一个以社会稳定为官方导向的体制。

That preoccupation 不断思考某事的状态;你经常想或想了很长时间的事情; 专注 can offer(v.) workers *slivers(n.)从较大的一块上切下或折断的小的或薄的一块;（切下或碎裂的）小块，薄片 of power* if they *make just enough trouble*, perhaps by *staging(v.)组织和参加需要仔细计划的行动，尤指作为公众抗议;组织；筹划 a respectful 表示敬意的；尊敬的 sit-in* （建筑物内的）静坐罢工，静坐示威 at a government office /or party-controlled *trade union* 工会 (China *bans* independent ones).

====
- preoccupation :  ~ (with sth) : a state of thinking about sth continuously; sth that you think about frequently or for a long time 盘算；思虑；长久思考的事情 +
-> She found *his preoccupation with money* irritating. 她对他一心只想着钱感到很厌烦。

- sliver : n. a small or thin piece of sth that is cut or broken off from a larger piece （切下或碎裂的）小块，薄片 +
=> 来自辅音丛 sl-,砍，劈，分开，比较 slab,slip,slat,slit,slot.引申词义小块，薄片。 +
-> *slivers of glass* 玻璃碎片
-> *A sliver of light* showed under the door. 门底下现出一丝亮光。

====

If enough workers *complain*, companies will often “budge(v.)改变你对某事的看法;使某人改变主意 and pay”, one of the workers said.

When they *go further* and *organise*, for instance through social-media groups, repression 使用武力来控制一群人,并限制他们的自由的行为;压制；镇压 *follows*.

In March, during meetings of the national legislature 有权力制定和修改法律的一群人; 立法机关 in Beijing, some workers in Guangdong *used* social media to discuss *submitting(v.)把文件、建议等交给权威人士以便他们研究或考虑;提交，呈递（文件、建议等） a petition 由许多人签名的书面文件，要求某人做某事或改变某事;请愿书 to* the central government.

The term “petition” *triggered* 使某事突然发生;引起；触发 an algorithm 算法；计算程序.

Police *dragged* （使劲而吃力地）拖，拉，拽，扯 workers *from* dormitory(n.)集体宿舍；学生宿舍 beds /and *humiliated*(v.)羞辱；使丧失尊严 them *with* strip(v.)脱光衣服；脱掉大部分衣服；扒光…的衣服 searches, Chaguan was told.

Chaguan被告知，警察把工人从宿舍的床上拖下来，并用脱衣搜查来羞辱他们.

Other workers *were reportedly evicted* （尤指依法从房屋或土地上）驱逐，赶出，逐出 after landlords *were told* they were “problematic(a.)产生问题的;难以处理或理解的;充满问题的;不一定能成功的” by officials.

====
- humiliate => 来自humus,土，尘土，词源同humus,-ate,使。即使像尘土一样卑微的，引申词义羞辱。

- *strip sth (off) +
strip (down to sth) +
strip sb (to sth)* : to take off all or most of your clothes or another person's clothes 脱光衣服；脱掉大部分衣服；扒光…的衣服 +
-> She *stripped down to her underwear*. 她把衣服脱得只剩下了内衣。(*这里的to是"直到...为止"*)
-> He stood there *stripped to the waist* (= he had no clothes on the upper part of his body) . 他脱光了上衣站在那里。

- evict => e-, 向外。-vict,胜利，词源同victory,convince. 即胜利赶走，驱逐。

- problematic : ADJ Something that is problematic involves problems and difficulties. 有问题的 +
-> Some places *are more problematic(a.) than others* for women travelling alone. 对独自旅行的妇女来说，有些地方比其他地方更容易出问题。

====

`主` Many of the hardships(n.)由于你没有足够的钱、食物、衣服等而造成的困难和不愉快的情况;艰难；困苦；拮据 (*described [around that table]* in Guangdong) `谓` *would cost* only small sums to resolve.

Alas （表示悲伤或遗憾）哎呀，唉, it *would also involve* those who *wield(v.)拥有并使用权力、权威等; 拥有，行使，支配（权力等）;挥，操，使用（武器、工具等）  power* *deferring to*  遵从；听从；顺从 the rights of individual workers.

Instead, those workers must *navigate 航行；航海；横渡 a ruthless system* in which they must *plead* and *bargain for* （与某人就某事）讨价还价，商讨条件 what they have earned.

A remarkable 不寻常的或令人惊讶的，引起人们注意的; 非凡的 generation of migrants *built* the new China. They are still *paying the costs*, in broken hands, backs and hearts.

他们仍然在付出代价，在受伤的手中，背部和心上。

====
- wield => 来自 PIE*wal,强健，支配，统治，词源同 value,valiant.
-> She *wields(v.)(`=to have and use power, authority, etc. 拥有，运用，行使，支配（权力等）`) enormous power* within the party. 她操纵着党内大权。 +
-> He *was wielding(`=to hold sth, ready to use it as a weapon or tool 挥，操，使用（武器、工具等）`) a large knife*. 他挥舞着一把大刀。
====


---



== 19.11.08 The migrants who made China an industrial giant face a grim retirement 纯净版

Those who built the new China are still suffering for it



Nov 30th 2019

EVEN IN A China *filled with* the shiny and the new, the southern city of Guangzhou *stands out*. A generation ago it was *a smoggy, sweltering sprawl* of factories and workshops, a bit embarrassed by its history *as* a semi-colony of Western powers, who knew it as Canton. Now Guangzhou *aspires to be* a hub of global commerce. It *boasts* the 600-metre tall Canton Tower, an opera house designed by Zaha Hadid /and high-speed trains that can reach Beijing, 2,300km to the north, in just eight hours. Yet Guangzhou’s rise *had* human costs. The province of Guangdong, of which it is the capital, is a hotbed of worker unrest, with 129 strikes and protests *logged* this year by China Labour Bulletin (CLB), a Hong Kong-based monitor of workers’ rights. A growing number *involve* workers reaching retirement age, who discover that -- because they *fall through* gaps in the welfare safety-net, or because employers *skimped on* pension contributions -- a meagre future *awaits*.

China’s migrant workers, who for 30 years *have left* inland villages and townships *for* coastal boomtowns, are growing old. Their average age is now over 40. Nearly a quarter are over 50. More than a tenth of all strikes, sit-ins and protests recorded by CLB in 2018 and 2019 *involved* rows over pensions and social insurance. The latest national survey on living conditions of the urban and rural elderly, published in 2018 on the orders of the Communist Party’s Central Committee, *describes* startling inequalities. About 100m retired Chinese covered by the unified basic urban pension system, *to which* most full-time urban workers *contribute*, *received* average monthly benefits of 2,600 yuan ($369) in 2016. But about 150m retirees had to *make do with* a state pension scheme *open to* both urban and rural residents. They received [on average] 117 yuan ($17) a month, a pittance even in a poor region.

There are 288m migrant *workers* in China, of whom 173m *work far from* their home towns. In theory, they should enjoy the same social protections as urban Chinese with permanent residence permits who live in big cities like Guangzhou. They do not. Today’s 40- and 50-something Chinese migrants are a “lost generation”, argues Mark Frazier of the New School in New York. They *fall between* the oldest, pioneering migrant workers (who were expected *to head back to* the countryside in retirement *to eke out a living* from tiny plots of land), *and* today’s 20-something workers, who *are less inclined* to seek distant factory jobs /and *are more likely* to be covered by social-security protections from a patchwork of new labour laws and insurance schemes. Few *see* the current system *as* sustainable, *amid* gloomy statistics about *falling(a.) birth rates* and *the shaky finances* of *the main urban pension fund*: the Chinese Academy of Social Sciences *predicts* it will *go bust* by 2035. Plans are afoot(a.) to increase China’s retirement age, which is normally 60 for men, 55 for women in white-collar jobs /and 50 for female blue-collar workers, though the rules *vary* by region.

None of those plans will help a group of older workers who spoke to Chaguan recently in Guangdong. The seven women and one man showed hands *too* damaged by factory work *to* pour tea without shaking. They *shared* stories of *parental guilt* after failing to return home for two or three years at a time, leaving children *to be brought up by* grandparents. Even during the spring festival, an occasion for family reunions, there was *valuable overtime* to be earned, said a 50-year-old woman from Hubei province. Besides, returning to the village *would have involved* long train journeys /and *buying* clothes, shoes and other gifts *for* many relatives. “We spent 20 spring festivals here,” she said wistfully. Unfortunately, before she reached retirement age in September, she learned that she could not draw her full pension in Guangdong because she began to make social-insurance payments after she was 40. If she had local residency she could make back-payments towards the 15 years of contributions needed. As a migrant, her only option was to return to Hubei, where her pension might come to 600 yuan ($85) a month. She *compared* her fate *to* an old, bitter saying: “*Unharness* the donkey from the grindstone, then *butcher* it.”

Another woman *had worked at* a handbag factory owned by Simone, a South Korean firm, for nearly 20 years. She alleged that her employer had failed to make the correct payments into a state housing-savings fund that serves as a second pension for many. After she complained, she said the firm had denied her overtime and warned other workers to avoid her. Simone denies these allegations. It says it takes employee benefits seriously and “strictly follows” and even *exceeds* China’s labour-law requirements.

A people’s republic, for the benefit of bosses

The eight workers had varied(a.) problems, but all *described* a system in which social stability is the authorities’ guiding obsession. That preoccupation *can offer* workers *slivers of power* if they *make just enough trouble*, perhaps by *staging a respectful sit-in* at a government office or party-controlled *trade union* (China *bans* independent ones). If enough workers complain, companies will often “*budge* and *pay*”, one of the workers said. When they *go further* and *organise*, for instance through social-media groups, repression *follows*. In March, during meetings of the national legislature in Beijing, some workers in Guangdong *used* social media to discuss *submitting a petition to* the central government. The term “petition” *triggered* an algorithm. Police *dragged* workers *from* dormitory beds and *humiliated* them *with* strip(v.) searches, Chaguan was told. Other workers *were reportedly evicted* after landlords *were told* they were “problematic(a.)” by officials.

Many of the hardships *described around that table* in Guangdong *would cost* only small sums to resolve. Alas, it *would also involve* those who *wield power* *deferring to* the rights of individual workers. Instead, those workers *must navigate* a ruthless system in which they must *plead* and *bargain for* what they have earned. A remarkable generation of migrants *built* the new China. They are still *paying the costs*, in broken hands, backs and hearts.


---



== 19.11.09 Who shot the sheriff (美国)负责维持一个县或镇的法律和秩序的民选官员;治安官;（苏格兰）法官?

It’s the end of the World Trade Organisation [as we know it]

正如我们所知，这是世界贸易组织的末日

And America feels fine

Nov 28th 2019 | WASHINGTON, DC

“WINTER IS COMING,” *warned* a Norwegian representative(n.)被选出来代表某人(或团体)来发言或投票的人;代表; 代理人 on November 22nd, at a meeting of the World Trade Organisation (WTO). 

`主` The multilateral(a.)三个或三个以上的团体、国家等参加的;多边的；多国的 trading system that the WTO *has overseen* 监视某人[某事物]并确保某项工作或活动正确完成 since 1995 `系` *is about to freeze up* 冻结. 

====
- multilateral => -multi-多(重)的 + -later-边,侧 + -al形容词词尾
====

[On December 10th] `主` two of the judges *on its appellate(a.)上诉的; 与上诉有关的 body* 一起工作或一起行动的一群人，通常是为了某个官方目的，或以其他方式联系在一起;团体；社团；群体, which *hears appeals*(n.)向法院或权威人士请求更改判决或决定的正式请求;上诉；申诉 in trade disputes(n.)两个人、团体或国家之间的争论或分歧;讨论一个存在分歧的话题;争论;纠纷 /and *authorises*(v.)准许某人做某事;批准；授权 sanctions 制裁; 限制与某一特定国家进行贸易、接触等的官方命令，以迫使该国做某事，如遵守国际法 *against* rule-breakers, `谓` will retire 退职；退休-- and an American block(n.) on new appointments *means* they will not be replaced. 

====
- dispute =>  dis-分离 + -put-考虑 + -e动词词尾 → 各人想法不一样,各抒己见, 即不同的思考，引申词义争论。
====

With just one judge (remaining), it will no longer *be able to hear new cases*.

The WTO *underpins* 支撑着或构成着某个论点、主张等的基础; 构成（…的基础等）; 支撑,加固 96% of global trade. 

====
- underpin : v. to support or form the basis of an argument, a claim, etc. 加强，巩固，构成（…的基础等） +
=> under-,在下面，pin,别针，固定。引申词义固定根基，加强。 +
 -> The report *is underpinned by* extensive research. 这份报告以广泛的研究为基础。
====

By one recent estimate （对数量、成本等的）估计；估价, membership of the WTO or _General Agreement on Tariffs  (政府对进口货物征收的) 关税 and Trade_ (GATT 关税与贸易总协定), its predecessor 前任,前身, *has boosted 使某事物增加，变得更好或更成功;使增长；使兴旺 trade* (among members) *by* 171%. 

根据最近的一项估计，世贸组织,或其前身关税与贸易总协定(GATT)的成员国身份, 使成员国之间的贸易增长了171%。

When iPhones move from China to America, or bottles of Scotch whisky from the European Union to India, *it is* the WTO’s rules *that* *keep*(v.) tariff and non-tariff barriers *low* /and *give* companies the certainty(`=the state of being certain 确定性`)  they need to plan and invest.

正是世贸组织的规则, 将关税和非关税壁垒, 保持在较低水平，并给予企业"在进行计划和投资时"所需的确定性。

The system *is supposed (按规定、习惯、安排)应当; 应该 (表示按计划或期望);本应该 to be* self-reinforcing 自我加强. 

Mostly, countries *follow* the WTO’s rules. But if one *feels* another *has transgressed*(v.)超越道德或法律所能接受的限度; 越轨, then [*instead of* starting a one-on-one 一对一的 trade spat(n.)小争吵；口角] it can *file 提起（诉讼）；提出（申请）；送交（备案） a formal dispute* 人们或群体之间的争论或分歧;争端 .
====
- transgress => trans-横过,越过 + -gress-步,级; 词源同 grade,aggressive.引申词义违背，违犯等。
====

If the WTO’s ruling *displeases* 使恼怒；使生气；使不悦 either party （契约或争论的）当事人，一方, it *can appeal*.

The appellate 上诉的; 与上诉有关的 body’s judgments(n.)由法官或法庭做出的决定,判决 *pack a punch*(重拳击打；用力的捶打) 对某人产生巨大影响；十分有效力.

====
- *pack a (powerful, real, etc.) punch* :  +
(1) ( of a boxer 拳击手 ) to be capable of hitting sb very hard 能重拳出击；能重击 +
(2) to have a powerful effect on sb 产生巨大影响；十分有效力 +
-> The advertising campaign *packs quite a punch*. 这次广告造势产生了相当大的影响。
====

If the loser *fails to bring* its trade rules *into* compliance 服从；顺从；遵从, the winner *can impose* tariffs *up to* the amount 数量；数额 the judges *think* the rule-breaking *cost* it.

*It is* that punishment *that* deters(v.)使某人决定不做某事或不继续做某事，尤指通过使他们明白, 他们的行动会给他们带来麻烦和不愉快的结果;威慑；使不敢;阻止了 rule breaking [in the first place].
====
- *deter(v.) sb (from sth/from doing sth)* to make sb decide not to do sth or continue doing sth, especially by making them understand the difficulties and unpleasant results of their actions 制止；阻止；威慑；使不敢 +
=> de-, 向下，强调。-ter, 恐惧，词源同terrible,terrorist. 即使恐惧，威慑，震慑。 +
-> The high price of the service *could deter* people *from* seeking advice. 这么高的服务费可能使咨询者望而却步。
====


如果输家未能遵守其贸易规则，胜利者可以征收关税到最大限额 -- 该限额是法官所认可的, 认为违反规则的一方所应该付出的。正是这种惩罚, 从一开始就阻止了违反规则。


*It* is no surprise *that* President Donald Trump *has axed* 斧;精简（机构等）；大量削减（经费等） these foreign arbiters 仲裁人,裁决人, given 考虑到；鉴于 his general distaste 不喜欢；反感；厌恶 for internationally agreed rules.

====
- arbiter =>  ar（=ad，去）+bit（去某地）+er（的人）→受法官委托，去某地判案的人→仲裁者 +
arbiter和arbitrator都可以表示“受争议双方委托，居中仲裁的人”，但arbiter比较书面，arbitrator比较通俗，并且arbitrator的自由裁量权更大，甚至可以是arbitrary（武断的）。
====

如果输家未能遵守其贸易规则，胜利者可以征收关税到最大限额 -- 该限额是法官所认可的, 认为违反规则的一方所应该付出的。正是这种惩罚, 从一开始就阻止了违反规则。


On November 12th he *declared* 公开宣布 himself “very tentative”(a.)踌躇的；犹豫不定的 on the WTO.

But the problems *run far deeper than* dislike of multilateral institutions 有特定目的的大型重要组织机构，如大学或银行.

They *stem from* a breakdown 关系、讨论或制度的破裂;失败 in trust over the way (international law should work), and the more general failure of the WTO’s negotiating 谈判 arm 分部；职能部门.

[*Had* the Americans *felt that* they *could negotiate away* their grievances 你认为不公平的事情，或对此的抱怨;抗议;委屈;不满],  `主` resentment  愤恨；怨恨 *towards* the appellate body `谓` *might not have built up*.

But [with so many members *reluctant to liberalise* 使某事物(如法律、政治或宗教制度)不那么严格,使自由化；放宽对…的限制, including smaller countries *fearful of* opening up to China], that *has been* impossible.

====
- tentative => tent-,接触，触摸，-ative,形容词后缀。即接触性的，引申词义暂定的，不确定的。
- negotiate => 一个人在谈判过程中，比如商人在谈判一笔大的生意时，心理状态往往有几分紧张不安，表示“谈判”的negotiate 一词本身就带有此一含义。其拉丁语词源negotium由 *neg‘not’* 和otium‘ease’组成，字面含义就是not at ease（紧张，不安）。
- grievance => griev(-grav-)重;压迫 + -ance名词词尾. 不平的事；委屈；抱怨；牢骚
- resentment => re-回,向后;相反,反对 + -sent-感觉 + -ment → 愤恨；怨恨. 来自 resent,气愤，愤恨
====

但问题远不止是因为特朗普不喜欢多边机构。还源于"对国际法该如何运作的方式"的信任, 已经破裂，以及世贸组织谈判机构的更普遍的失败。 +
如果美国人觉得他们可以通过谈判来解决他们的不满，那么他们对上诉机构的怨恨可能就不会形成。


America has had some wins at the WTO: against the European Union for subsidies to Airbus, an aircraft-maker; and against China for its domestic subsidies; theft of intellectual property; controls on the export of rare earths, which are used to make mobile phones; and even its tariffs on American chicken feet. But it has also been dragged before the appellate body repeatedly, in particular by countries objecting to its heavy-handed use of “trade remedies”: tariffs supposed to defend its producers from unfair imports. Time after time, it has lost. In such cases, it has generally sought to become compliant with the rules rather than buy the complainant off.

Though previous administrations had grumbled, and occasionally intervened in judges’ appointments, the Trump administration went further. Its officials complained that disputes often dragged on much longer than the supposed maximum of 90 days, and—more seriously—that the appellate body made rulings that went beyond what WTO members had signed up to. They made it clear that unless such concerns were dealt with, no new judges would be confirmed.

Judicial overreach is in the eye of the beholder. Losers will always feel hard done by, and America has been quick to celebrate the WTO’s rulings when it wins. But plenty of others think that the appellate body had overstepped its remit. A recent survey of individuals engaged with the WTO, including national representatives, found that 58% agreed with that verdict.

Getting so many countries to sign up to the WTO was a remarkable achievement. One way negotiators managed this was by leaving the rules vague, and papering over their differences with ambiguous language. Take “zeroing”, for example: using dubious mathematics to calculate defensive tariffs on unfairly traded imports. The Americans claim that the rules do not say they cannot do it. But others counter that the rules do not say they can. It is such long-running differences that have set the scene for the latest showdown.

Offer me solutions

The American trade lawyers happy to kill the appellate body see a fundamental difference between their attitude to international law, and that of Europeans. Their position is that only clear contractual terms can be enforced, and they see Europeans as more comfortable with resolving ambiguities by going beyond what is written. Essentially, they regard the appellate body as too European. Moreover, in its eagerness to rule where terms are unclear, and in the American government’s willingness to change its laws in response, they feel an affront to America’s sovereignty.

Under the GATT, which lacked a proper enforcement system, ambiguities were hashed out in smoke-filled rooms. But the WTO was supposed to make naked power politics over trade obsolete. Had it worked as intended, there would have been a balance between settling disputes and writing new rules. Policy is best made with a vibrant judiciary interpreting the law, and a functioning legislative arm to fix any mistakes. Whenever the appellate body made decisions that annoyed members, they could have resolved their differences at the negotiating table. Perhaps America could have got others to agree to higher tariffs on imported steel, or been granted some flexibility in its defensive duties.

But the WTO’s negotiating arm has been broken for years. With the current count of members at 164, it has become more inclusive, but is unable to get much agreed. Each member has a veto over any further multilateral trade liberalisation. And without new negotiations, resentment towards the appellate body has built up.



If you think this has a happy ending...

Had the multilateral system been more effective at dealing with the rise of China, perhaps the single biggest issue of its times, then calls to save it might be louder in Washington. Although various American administrations pursued and won several cases, the process was slow and occasionally frustrating. America can justly claim that, when it tried to hold China to account for its breaches of trade rules, it got little support. America has been responsible for more than half of all complaints against China. And other WTO members’ complaints were generally copycat, filed in America’s wake.

Now that the Trump administration has bypassed the WTO and taken the fight straight to China, there is nothing remaining that it particularly wants from the WTO. And so the chances that it will relent and allow nominations to the appellate body by December 10th are slim to none. In response to proposals from other members to change the body’s rules, an American representative said that they were not persuaded that the rules would be stuck to.

On November 26th the Trump administration suggested slashing the pay of members of the appellate body. In October Chuck Grassley and Ron Wyden, the top Republican and Democrat politicians on the Senate Finance Committee, published an editorial saying that while they saw the value of an appellate body, it “needs to operate as the members agreed”.



Of the WTO’s 163 other members, 117 have signed a joint letter calling upon America to end the impasse. Although America has been the heaviest user of the dispute-settlement system, others will miss it too (see chart). Some have already begun preparing, for example by agreeing at the start of any disputes to forgo the right to appeal. The EU, Canada and Norway have agreed on an interim arbitration mechanism that will use retired members of the appellate body as judges. And the EU is considering beefing up its own enforcement mechanism to fill the hole left by the appellate body, though it would probably cleave more closely to the outcomes of first-stage rulings in WTO disputes.

But some members are likely to shun such alternatives—especially those that expect to be sued a lot. And it is unclear how robust they will be if disputes turn nasty. Some WTO members may try to choose their dispute-settlement mechanism case by case. An organisation as ambitious as the WTO, for all its faults, will be easier to break than replace.

All this means that global trade is about to become a lot less predictable and a lot more contentious. Without the appellate body to act as honest broker, disputes between the biggest members may escalate. Under the GATT America acted as global trade sheriff, launching investigations at will and bullying disputatious countries into submission. It is not impossible that it will resume this role. On November 27th the Trump administration announced that it had nearly finished an investigation into a French tax on digital services, which America reckons discriminates against its tech giants. That could lead to tariffs.

You’ll miss it when it’s gone

In the 1980s American unilateralism was no fun for countries on the receiving end. But at least back then Uncle Sam could point to the lack of any other power even theoretically capable of doing the job. Now the absence of independent referees is America’s own doing. And of all Mr Trump’s trade policies, it may prove the hardest to reverse and have the longest-lasting effects.



美国在世贸组织取得了一些胜利:反对欧盟对飞机制造商空客的补贴;反对中国的国内补贴;盗窃知识产权;控制用于制造移动电话的稀土的出口;甚至对美国鸡爪征收关税。但它也多次被上诉机构提起诉讼，尤其是那些反对其滥用“贸易救济措施”的国家:关税本应保护其生产商免受不公平进口的影响。一次又一次，它失败了。在这种情况下，它通常会寻求遵守规则，而不是收买投诉人。


尽管前几届政府都抱怨过，偶尔还会干预法官的任命，但特朗普政府做得更多。WTO官员抱怨称，争端通常拖得比预期的最长90天要长得多，更严重的是，上诉机构做出的裁决超出了WTO成员国签署的规定。他们明确表示，除非解决这些问题，否则不会任命新法官。
司法上的越权在旁观者的眼中。输家总是会觉得受到了不公平的对待，而美国在获胜后很快就会庆祝WTO的裁决。但是很多人认为上诉机构已经超出了它的职权范围。最近对包括国家代表在内的WTO工作人员的调查发现，58%的人同意这一裁决。
让这么多国家加入世贸组织是一个了不起的成就。谈判者解决这个问题的方法之一是让规则含糊不清，并用含糊不清的语言掩盖他们之间的分歧。以“归零”为例:使用可疑的数学计算不公平贸易进口产品的防御关税。美国人声称，规则并没有说他们不能这么做。但另一些人反驳说，规则并没有说他们可以。正是这种长期存在的分歧为最后的摊牌埋下了伏笔。
给我解决方案
美国贸易律师乐于扼杀这个上诉机构，他们看到了自己对国际法的态度与欧洲人的态度之间的根本区别。他们的立场是，只有明确的合同条款才能得到执行，他们认为，欧洲人更愿意通过超越文字来解决含糊不清的问题。本质上，他们认为上诉机构过于欧洲化。此外，他们渴望在条款不明确的地方进行统治，而美国政府也愿意修改法律作为回应，他们觉得这是对美国主权的侮辱。
在关贸总协定下，由于缺乏适当的执行制度，含糊不清的问题只能在烟雾缭绕的房间里解决。但世贸组织本应让赤裸裸的贸易强权政治过时。如果它像预期的那样运作，那么在解决争端和制定新规则之间就会取得平衡。制定政策时，最好有一个活跃的司法机构来解释法律，并有一个有效的立法机构来纠正任何错误。无论何时，上诉机构做出的决定惹恼了成员，他们本可以在谈判桌上解决分歧。或许美国可以让其他国家同意对进口钢铁征收更高的关税，或者在其防御关税上给予一些灵活性。
但世贸组织的谈判机制多年来一直处于瘫痪状态。目前的成员人数为164人，这一数字已变得更加包容，但仍无法达成多少共识。每个成员国都有权否决任何进一步的多边贸易自由化。而且，如果没有新的谈判，对上诉机构的怨恨就会增加。
如果你认为这是一个幸福的结局…
如果多边体系能够更有效地应对中国的崛起(这或许是当今最大的一个问题)，那么在华盛顿，拯救中国的呼声可能会更高。尽管不同的美国政府追求并赢得了一些案件，但过程缓慢，有时令人沮丧。美国有理由声称，当它试图让中国为其违反贸易规则承担责任时，得到的支持很少。在所有针对中国的投诉中，美国占了一半以上。其他世贸组织成员的申诉基本上都是模仿美国的做法。
既然特朗普政府绕过世贸组织，直接与中国对抗，那么它特别想从世贸组织得到的东西已经没有了。因此，在12月10日之前，它放宽限制，允许上诉机构提名的机会几乎为零。在回应其他成员国提出的改变该机构规则的建议时，一名美国代表表示，他们不相信这些规则会被遵守。
11月26日，特朗普政府建议削减上诉机构成员的薪酬。去年10月，参议院财政委员会(Senate Finance Committee)的共和党和民主党两党最高领导人查克•格拉斯利(Chuck Grassley)和罗恩•怀登(Ron Wyden)发表了一篇社论，称尽管他们看到了上诉机构的价值，但它“需要按照成员们的共识来运作”。



世贸组织的163个其他成员中，有117个已经签署了一份联合信，呼吁美国结束僵局。尽管美国是争端解决机制最大的使用者，其他国家也会想念它(见图表)。一些国家已经开始准备，例如在争端开始时同意放弃上诉的权利。欧盟、加拿大和挪威已就一项临时仲裁机制达成一致，该机制将让上诉机构的退休成员担任法官。欧盟正在考虑加强自己的执法机制，以填补上诉机构留下的空白，尽管它可能会更密切地关注WTO争端第一阶段裁决的结果。
但是一些成员可能会回避这样的替代方案，尤其是那些可能会被起诉的。而且，如果争端恶化，这些替代方案将会有多强大还不清楚。一些世贸组织成员可能会根据具体情况选择争端解决机制。像世界贸易组织这样雄心勃勃的组织，尽管有种种缺点，但打破它比取代它更容易。
所有这些都意味着全球贸易将变得更加难以预测，争议也会更多。没有上诉机构作为诚实的中间人，最大成员之间的争端可能会升级。在关贸总协定下，美国扮演着全球贸易警长的角色，随意展开调查，威逼有争议的国家屈服。它恢复这一作用并非不可能。11月27日，特朗普政府宣布，它几乎完成了一项关于法国对数字服务征税的调查。这可能会导致关税。
当它消失的时候，你会怀念它的
在20世纪80年代，美国的单边主义对接受国来说毫无乐趣可言。但至少在当时，山姆大叔可以指出，即使在理论上也没有任何其他力量能够胜任这一工作。现在，缺乏独立的裁判是美国自己的事情。在特朗普所有的贸易政策中，它可能是最难逆转的，而且会产生持续时间最长的影响。



---



== 19.11.09 Who shot the sheriff? 纯净版

It’s the end of the World Trade Organisation as we know it

And America feels fine



Nov 28th 2019 | WASHINGTON, DC

“WINTER IS COMING,” warned a Norwegian representative on November 22nd, at a meeting of the World Trade Organisation (WTO). The multilateral trading system that the WTO has overseen since 1995 is about to freeze up. On December 10th two of the judges on its appellate body, which hears appeals in trade disputes and authorises sanctions against rule-breakers, will retire—and an American block on new appointments means they will not be replaced. With just one judge remaining, it will no longer be able to hear new cases.

The WTO underpins 96% of global trade. By one recent estimate, membership of the WTO or General Agreement on Tariffs and Trade (GATT), its predecessor, has boosted trade among members by 171%. When iPhones move from China to America, or bottles of Scotch whisky from the European Union to India, it is the WTO’s rules that keep tariff and non-tariff barriers low and give companies the certainty they need to plan and invest.

The system is supposed to be self-reinforcing. Mostly, countries follow the WTO’s rules. But if one feels another has transgressed, then instead of starting a one-on-one trade spat it can file a formal dispute. If the WTO’s ruling displeases either party, it can appeal. The appellate body’s judgments pack a punch. If the loser fails to bring its trade rules into compliance, the winner can impose tariffs up to the amount the judges think the rule-breaking cost it. It is that punishment that deters rule breaking in the first place.

It is no surprise that President Donald Trump has axed these foreign arbiters, given his general distaste for internationally agreed rules. On November 12th he declared himself “very tentative” on the WTO. But the problems run far deeper than dislike of multilateral institutions. They stem from a breakdown in trust over the way international law should work, and the more general failure of the WTO’s negotiating arm. Had the Americans felt that they could negotiate away their grievances, resentment towards the appellate body might not have built up. But with so many members reluctant to liberalise, including smaller countries fearful of opening up to China, that has been impossible.

America has had some wins at the WTO: against the European Union for subsidies to Airbus, an aircraft-maker; and against China for its domestic subsidies; theft of intellectual property; controls on the export of rare earths, which are used to make mobile phones; and even its tariffs on American chicken feet. But it has also been dragged before the appellate body repeatedly, in particular by countries objecting to its heavy-handed use of “trade remedies”: tariffs supposed to defend its producers from unfair imports. Time after time, it has lost. In such cases, it has generally sought to become compliant with the rules rather than buy the complainant off.

Though previous administrations had grumbled, and occasionally intervened in judges’ appointments, the Trump administration went further. Its officials complained that disputes often dragged on much longer than the supposed maximum of 90 days, and—more seriously—that the appellate body made rulings that went beyond what WTO members had signed up to. They made it clear that unless such concerns were dealt with, no new judges would be confirmed.

Judicial overreach is in the eye of the beholder. Losers will always feel hard done by, and America has been quick to celebrate the WTO’s rulings when it wins. But plenty of others think that the appellate body had overstepped its remit. A recent survey of individuals engaged with the WTO, including national representatives, found that 58% agreed with that verdict.

Getting so many countries to sign up to the WTO was a remarkable achievement. One way negotiators managed this was by leaving the rules vague, and papering over their differences with ambiguous language. Take “zeroing”, for example: using dubious mathematics to calculate defensive tariffs on unfairly traded imports. The Americans claim that the rules do not say they cannot do it. But others counter that the rules do not say they can. It is such long-running differences that have set the scene for the latest showdown.

Offer me solutions

The American trade lawyers happy to kill the appellate body see a fundamental difference between their attitude to international law, and that of Europeans. Their position is that only clear contractual terms can be enforced, and they see Europeans as more comfortable with resolving ambiguities by going beyond what is written. Essentially, they regard the appellate body as too European. Moreover, in its eagerness to rule where terms are unclear, and in the American government’s willingness to change its laws in response, they feel an affront to America’s sovereignty.

Under the GATT, which lacked a proper enforcement system, ambiguities were hashed out in smoke-filled rooms. But the WTO was supposed to make naked power politics over trade obsolete. Had it worked as intended, there would have been a balance between settling disputes and writing new rules. Policy is best made with a vibrant judiciary interpreting the law, and a functioning legislative arm to fix any mistakes. Whenever the appellate body made decisions that annoyed members, they could have resolved their differences at the negotiating table. Perhaps America could have got others to agree to higher tariffs on imported steel, or been granted some flexibility in its defensive duties.

But the WTO’s negotiating arm has been broken for years. With the current count of members at 164, it has become more inclusive, but is unable to get much agreed. Each member has a veto over any further multilateral trade liberalisation. And without new negotiations, resentment towards the appellate body has built up.



If you think this has a happy ending...

Had the multilateral system been more effective at dealing with the rise of China, perhaps the single biggest issue of its times, then calls to save it might be louder in Washington. Although various American administrations pursued and won several cases, the process was slow and occasionally frustrating. America can justly claim that, when it tried to hold China to account for its breaches of trade rules, it got little support. America has been responsible for more than half of all complaints against China. And other WTO members’ complaints were generally copycat, filed in America’s wake.

Now that the Trump administration has bypassed the WTO and taken the fight straight to China, there is nothing remaining that it particularly wants from the WTO. And so the chances that it will relent and allow nominations to the appellate body by December 10th are slim to none. In response to proposals from other members to change the body’s rules, an American representative said that they were not persuaded that the rules would be stuck to.

On November 26th the Trump administration suggested slashing the pay of members of the appellate body. In October Chuck Grassley and Ron Wyden, the top Republican and Democrat politicians on the Senate Finance Committee, published an editorial saying that while they saw the value of an appellate body, it “needs to operate as the members agreed”.



Of the WTO’s 163 other members, 117 have signed a joint letter calling upon America to end the impasse. Although America has been the heaviest user of the dispute-settlement system, others will miss it too (see chart). Some have already begun preparing, for example by agreeing at the start of any disputes to forgo the right to appeal. The EU, Canada and Norway have agreed on an interim arbitration mechanism that will use retired members of the appellate body as judges. And the EU is considering beefing up its own enforcement mechanism to fill the hole left by the appellate body, though it would probably cleave more closely to the outcomes of first-stage rulings in WTO disputes.

But some members are likely to shun such alternatives—especially those that expect to be sued a lot. And it is unclear how robust they will be if disputes turn nasty. Some WTO members may try to choose their dispute-settlement mechanism case by case. An organisation as ambitious as the WTO, for all its faults, will be easier to break than replace.

All this means that global trade is about to become a lot less predictable and a lot more contentious. Without the appellate body to act as honest broker, disputes between the biggest members may escalate. Under the GATT America acted as global trade sheriff, launching investigations at will and bullying disputatious countries into submission. It is not impossible that it will resume this role. On November 27th the Trump administration announced that it had nearly finished an investigation into a French tax on digital services, which America reckons discriminates against its tech giants. That could lead to tariffs.

You’ll miss it when it’s gone

In the 1980s American unilateralism was no fun for countries on the receiving end. But at least back then Uncle Sam could point to the lack of any other power even theoretically capable of doing the job. Now the absence of independent referees is America’s own doing. And of all Mr Trump’s trade policies, it may prove the hardest to reverse and have the longest-lasting effects.

---







