
= my Values
:toc: left
:toclevels: 3
:sectnums:

---

== 荣耀

展现出独有的个人价值，家族以我为荣。

---

== 价值观大树

=== 创建我自己的价值观, 方法论架构大树

各科都有自己的理论框架模型，就像一棵棵不同长相的大树. *你不可能记住世上所有的树*（各种学科的各种理论框架），而且未来还会永远有新树出来. *但你一定能记住你自己, 从零创造出来的这一棵树 (自己的框架)！ 即, 你能以你的“一”，来统其他的“万“.*

把别的树上的叶子, 组装到自己的大树上: 一定要把别人的理论, 翻译成你自己的话. 即经过你自己的理解"翻译", 变成你思考后的东西. 再把所学到的理论, 思维模型，模块化, 变形组装到你自己的大树上。作为叶子.  千万不要原封不动直接搬别人的框架(或别人的思维导图)! 你自己想出来的组织方式，才最符合你自己的实战需要的。

---

==== 记树叶是舍本逐末, 你要弄懂的是树枝,树干(底层逻辑)

一棵树上的叶子万万千（各种规律现象发现），我们去单独直接记忆所有的叶子是错误的. 我们要理解弄懂的, 是更少的树干，树枝(即"本源出发点"). 正是树干, 推导出了树枝, 树枝又推导出了树叶. 即, 知其"所以然"，就能知其"然".
真正重要的, 不是已经是最后一步的"果", 而是推导出"果"的前面的"因".

- 三国的故事(只是因果的"果")本身根本不重要, 重要的是导致这些事件发生的"因"的部分 -- 即其背后的人物的思考, 性格, 当时所处的环境分析. 事实上, 等事情发生了, 战争发生了, 已经是整个因果链上最后的一环了.
- 我不是在看历史故事，我并不关心历史的具体细节，我是借助他们的遭遇，来得到我自己的人生启示。比如，看蒋介石的历史，不是为了向他人去说这些无用的陈年旧事. 我看的目的，是从他的教训中，得到对现在的我有用的处事经验。
- 我在看老毛的思想及行径时, 重点不是在判断他的对错上, 而是能从中看出(总结出), 他的"政治斗争手段"套路!
你学的不是那几首歌, 而是发声技巧.

*你学习并使用各种思维模型, 来分析解决工作, 商业等问题, 也并不只是为了该问题本身, 而是为了借助它们来训练你的大脑思维方式!*

*把案例研究当哑铃, 你的目的不是哑铃, 而是锻炼你肌肉(大脑思维认知, 及建立你自己"方法论大树"的食材)*

---

===  对任何"事物"的判断, 都要问4个问题

(1). 它存在的意义和价值是什么? 即, 它是为了解决什么问题, 而存在? 为什么它必须要存在? 其他事物能替代它吗 ?

(2). 它宣称能针对解决的问题, 这些问题重要吗? 价值度如何?

(3). 它是如何做到的? 方法是什么? 背后的原理是什么? 底层逻辑是什么? 心理学依据是什么? 每个方法的ROI如何? 成功率如何? 优点和缺点分别是什么? 使用场景的前提要求是什么?

(4). 对同一个问题, 经常不同高人间的观点, 也会彼此不同 (这在政治学领域很常见). 那么你就要特别注意他们彼此间的批判, 观点逻辑如何. 对对方理论的漏洞, 挖掘深度如何? 犀利度如何, 一针见血吗? 令你拍案叫绝吗? 并以此来补足你的思考漏洞, 和理论框架.

把你这4个问题类别, 建立起一个问题框架树 (清单填空题),  将你的答案, 一一填充进你的这个"框架树"填空题中. 这个问题对你的价值, 就基本榨干了.

---

=== 世上没有绝对的唯一定义, 定义是人赋予的

概念是个框. 对任何一个概念, 世上没有绝对的唯一定义, 定义内容是人赋予的, 每个人都有自己的定义.

.标题
====
例如：
假设, 你的营销目标是: 提升你的公司品牌在粉丝中的公信力。那么你首先就要弄清楚, 你所想得到的这个"公信力", 到底是指什么? 包含哪些东西? *即, 你要对它下一个明确的自己的定义 (而不是照搬别人的的定义. 因为别人的定义中打包的内核, 是别人想以的东西, 不一定是符合你所想要的)*.

所以, 你要先搞清楚你自己的需要:

- 在你自己的价值观中(而不是别人的价值观), 什么叫"公信力"？
- 你自己希望展现出的"公信力", 是什么样子的？

"公信力"是个打包后的概念, 那么包里面, 有哪些东西呢? 即, 你需要对其进行拆包, 拆解.  比如, 可以拆解为：

[options="autowidth"  cols="1a,1a"]
|===
|Header 1 |指标有 : ...

|内容本身造成的影响力.
|Column 2, row 1

|粉丝的反应程度
|- 粉丝中是业内著名的高公信力账号的, 有多少?
- 最有公信力的微博账号，账号的无提示提及率

|在圈层上的影响力. 指标有
|- 账号与多少业内高公信力账号彼此关注, 并且经常互动.
- 账号参与了多少社会热点话题的讨论，输出了观点，并被认可.
- 有多少社会热点话题, 是由你公司率先引发的.
|===
====

又如, 如何找到你自己的正确的 KPI? 你要用你自己的指标(而非别人的), 你自己的营销目标的数据, 来进行解构分析.

---

=== 不要用实习生的认知, 取代你的认知

要对市场和产品的深入了解, 你要亲自去和市场上吃过猪肉的人多聊天, 看看别人在干什么. 而不要只派两个实习生做个调查报告，得出一个结论。这本质上是用实习生的认知取代了决策者的认知。

---

== 我观史的4步逻辑分析法

1. 造成现状的原因 (向前推, 溯源)
2. 当前现状, 带来的后果和问题
3. 如何解决当前这个现状?
4. 当前采取的措施, 又导致了什么新的后果和问题(即"未来的现状")? 这一步就与第1步形成了循环.

---


