

= 0007 How to reveal a country’s sense, over the years, of its own well-being
:toc: left
:toclevels: 3
:sectnums:

'''


== How to reveal a country’s sense, over the years, of its own well-being

如何揭示一个国家多年来对自身福祉的感受


Overall, then, Dr Sgroi and Dr Proto found that *happiness does vary (v.)（根据情况）变化，变更，改变  with GDP*. But 主 the effect of health and *life expectancy*, which does not *have the episodic (a.)偶尔发生的；不定期的 quality* 质量；品质 of booms （贸易和经济活动的）激增，繁荣 , busts (n.)打破；摔碎,突袭,经济萧条时期  and** armed conflict**, 系 is larger, even 主 when the tendency of wealth to improve health 谓 *is taken into account*.

主 A one-year increase in longevity 长寿；长命；持久, for example, 谓 *has the same effect* on national happiness *as* 如同，像……一样 a 4.3% increase in GDP.

And, *as* the grand historical sweep 巡行；搜索；扫荡 *suggests*, 强调句 it is warfare 战争 that causes (v.) the biggest drops in happiness. [On average] it takes a 30% increase in GDP *to raise happiness by the amount* 后定 that a year of war causes (v.) it to fall.

*The upshot 最后结果；结局 appears to be that*, while 虽然；尽管 despite the fact that…​ 虽然；尽管 主 increasing national income 系 is important to happiness, *it is not as important as* ensuring the population is healthy *and* avoiding conflict.


====
.episodic :
ADJ Something that is episodic *occurs at irregular and infrequent intervals*. 偶然发生的; 不定期的

-  ...*episodic attacks* of fever. ...不定期的发烧。


总体而言，斯格罗伊和普罗图发现, 幸福感确实会随GDP的变化而改变。健康和预期寿命的影响, 不像繁荣、萧条和武装冲突那样断断续续，但它们的影响更大，即使把财富改善健康的趋势考虑在内。例如，寿命延长一年，对国民幸福感的影响, 与GDP增长4.3％的影响相同。而且，正如对漫长历史的探究所显示的那样，战争导致幸福感下降最多。平均而言，一年的战争所导致的幸福感降幅, 需要GDP增长30%才能拉平。结果似乎是，虽然增加国民收入对提升幸福感很重要，但确保人口健康和避免冲突的作用更大。
====


'''



== <pure> How to reveal a country’s sense, over the years, of its own well-being

Overall, then, Dr Sgroi and Dr Proto found that /{happiness does vary with GDP}. But  the effect of health and life expectancy, which does not have the episodic quality of booms, busts and armed conflict, is larger, even when  the tendency of wealth to improve health /is taken into account.  A one-year increase in longevity, for example,  has [underline]#the same# effect on national happiness /[underline]#as# a 4.3% increase in GDP. And, as the grand historical sweep suggests, it is warfare /that causes the biggest drops in happiness. [On average] /it takes a 30% increase in GDP to raise happiness /by the amount /(that a year of war causes it to fall). The upshot appears to be that, while increasing national income /is important to happiness, it is not as important as /ensuring the population is healthy /and avoiding conflict.


'''
