= 1364
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 59.
This is English as a Second Language Podcast’s English Café episode 59. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we’re going to talk about the police in the United States and how they are organized. We are also going to talk about one of the most popular television shows of the last 15 years or so in the U.S., The Simpsons. And, as always, we’ll answer some of your questions. Let’s get started.
Our first topic today is the police in the U.S. “Police” (police) is a general term for people who work for the government in the area of what we call “law enforcement.” “To enforce” (enforce) means to make someone do something – to force someone to do something. So, when we say “law enforcement,” we are referring to people who get other people to follow the law – the legal rules and restrictions of the state or of the country.
The U.S. has lots of different police “structures,” we could call them – lots of different types of police. In some countries, the police are all part of one big organization. But in the United States, because we have a tradition of each state having some independence from the other states, there are several different levels of police officers. There are federal police, although we don’t normally call them police – we would instead say “federal law enforcement.” “Federal” is “national,” in this instance.
Federal law enforcement includes organizations like the Federal Bureau of Investigation, or “FBI.” The FBI is famous in the movies, if you watch American movies. These are the government police officers, sometimes called the “G-men.” The letter “G” in “G-men” refers to government – the letter “G” in “government.” So, these are the government police officers, the federal government police officers, and they are in charge of certain types of crimes that occur on a national level.
There are many other types of law enforcement officers at the national level. There are the people who guard the border, called the “Border Patrol.” The border is the line that divides the U.S. from other countries, such as Canada and Mexico.
The people who enforce drug laws make up a special police force called the “Drug Enforcement Agency.” These are all groups that can arrest people, and that’s really what a police officer is: someone who can arrest you and put you in jail. “To arrest” (arrest) means to put someone in jail, to say that they have done something wrong.
I’ve been using the term “officer” (officer). That’s just a word we use to describe a man or a woman who works, usually, for a police organization. Each state also has its own police force. A “police force” (force) is a noun which means a group of police officers, a group of law enforcement people. Many states have their own police forces. These often include “state troopers” (troopers). A state trooper is a police officer who works for the state police force.
We also have county police officers in the United States. Every state is divided into smaller areas, smaller regions, which we call “counties” in most places. Some states call these areas “parishes” or “boroughs,” but in most states they are called “counties.” Each county has its own police force, and if there are cities inside the county, often each individual city will have its own police force.
So, you could have a state police officer, a county police officer, and a city police officer, and each of those different levels is responsible for different areas and different things. There even more police forces in certain areas. In California, for example, the airport has its own police force. The public universities have their own police forces. Even the transportation system here in Los Angeles has its own police force.
Now, if you watch American television and movies, you will often see certain terms used in describing the police. The most common, informal term is “cops” (cops). A cop is a police officer. It’s an informal term. There’s actually a popular television show about police officers, called Cops. Another term that you will hear is “squad car.” A “squad (squad) car (car)” – two words – is the car that the regular police officers in a city or in a county drive. These are sometimes called “black-and-whites,” because the usual color for these cars is black and white. So, a squad car is a car that the police use.
Each police force in a city, like Los Angeles or New York City, is broken down into, or divided into, what are called “precincts” (precincts). A precinct is just a smaller part of the city, in which you have one police station or building that’s responsible for that area.
One other thing that you will often hear in American movies and TV shows is something called the “Miranda warning.” “Miranda” (Miranda) was the name of a court case, and this warning is what police officers have to say to people whom they arrest before they arrest them, to tell them what their legal rights are.
The standard or common Miranda warning is, “You have the right to remain silent,” meaning you have a right not to talk. “You have the right to remain silent. Anything you say can and will be used against you in a court of law.” So, anything that you say to the police officer – like “I’m guilty” or “I did it” – can be used in your trial. Your “trial” (trial) is when you go before the judge in court.
The Miranda warning typically continues, “You have the right to speak to an attorney.” An attorney is a lawyer. So, you have the right to speak to an attorney and “to have an attorney present during any questioning.” This means that if you are being arrested and the police are asking you questions, you can say, “I want a lawyer,” and they cannot ask you any more questions until they get you a lawyer.
The warning finishes by saying, “If you cannot afford a lawyer” – if you don’t have money for a lawyer – “one will be provided for you at government expense.” In other words, if you are poor and you do not have money for your own lawyer, the government will give you a lawyer for free. Those are called “public defenders,” and they are lawyers who try to help people who are arrested and who don’t have money for their own lawyer.
So, that’s the Miranda warning, and you’ll hear it in lots of different shows and movies. “You have the right to remain silent” is how it begins, and that’s the most famous line from the Miranda warning.
Our second topic has nothing to do with the police – it is one of the most popular television programs of the last 15 years or so in the United States, called The Simpsons. The Simpsons is an animated series. “Animated” (animated) is the same as a cartoon. So, The Simpsons is a cartoon, but it’s a cartoon that both children and adults like to watch. Some of the jokes are very simple ones that children can understand, and others are more complicated jokes that adults will enjoy.
The Simpsons is what we call a “satire.” A “satire” (satire) is when you use jokes – humor – to criticize something or to show the problems with something. Satire is often political. Political satire is when you use jokes or humor to criticize a politician or the government. But satire can also be what we would call “social satire.” Social satire would be criticizing the way people live or the way people act. The Simpsons is a satire about sort of a typical American family, what some people might describe as “Middle America.” “Middle” here means typical or average.
The Simpsons are a family who live in a made-up, or fictional, town called “Springfield.” Springfield is actually a very popular town name in the United States. At least 30 different states have a city or town named Springfield. Springfield, Illinois, is perhaps the most well-known, and that is the capital of the state of Illinois. The Springfield in The Simpsons, however, is not a real place, but it’s considered a typical American town, and the whole show is about the life of this family living in Springfield.
The Simpsons are a traditional family. There’s a mother and a father and three children. The father’s name is “Homer” (Homer), which is also the name of the famous Greek poet who we think wrote the great poems of ancient Greece, “The Iliad” and “The Odyssey.” But this Homer is not as smart as the ancient Greek Homer. Homer is not very smart. He’s a nice guy, but he’s not very intelligent.
Homer works at a nuclear power plant. A “plant” is, in this case, a building that makes power – “generates” power, we would say – by using nuclear energy, and so there are lots of jokes about his job. His wife is a typical housewife: she works at home and doesn’t have a job outside the home. Then there is the most famous character, Bart. Bart is a ten-year-old boy who gets into lots of different types of trouble. If you have a chance to see The Simpsons, it’s a very funny show.
There are several phrases and expressions from the show that have become popular in regular conversation. The most famous one is an expression that Homer, the father of the family, uses. Whenever he makes a mistake or does something stupid, he’ll hit himself on his head with his hand and say, “D’oh!” We spell this either (d’oh) or just (doh). And that is a famous expression now in English – “D’oh!”
There are a couple of other expressions from this program that are popular. One which is kind of old now, but was popular in the ‘90s, is an expression that Bart uses: “Don’t have a cow.” “Don’t have a cow, man!” The expression “Don’t have a cow” is an old one, and it means don’t get upset, don’t get excited, don’t get angry. Usually you say that to somebody who is getting angry or getting excited about something more than they should. It’s an informal expression; you would not want to say that to your boss. “Don’t have a cow, man!” That may get you a new job.
Now let’s answer a few of the questions you have sent to us.
Our first question today comes from Atsushi (Atsushi) in Japan. Atsushi wants to know the meaning of the expression, “It’s going down.” What does “It’s going down” mean?
Normally, that’s an expression that you would use when describing or talking about something that is illegal, something that is against the law – like buying illegal drugs, for example. When that event is happening or is about to happen, someone could say, “It’s going down,” or “It’s going to go down” (in the future). In this way, “going down” means “happening,” but usually in reference to something that is illegal, something that is against the law – a crime.
The other expression Atsushi has a question about is a word – kind of an odd word, but one that you will see now and then: “QWERTY.” “QWERTY” (QWERTY) is not exactly a common word, but it’s one that we use to talk about a type of keyboard. The letters and numbers that you use to type on your computer are called the “keyboard.”
“QUERTY” describes a kind of keyboard in English that is a complete keyboard. In contrast, many small cell phones don’t have a complete keyboard; they have only a certain number of buttons, or keys, and each key has two or three letters, so you have to press them until you get the right letter. But a QWERTY keyboard is a complete keyboard.
It’s called a QWERTY keyboard because, on the keyboard in English, the first six letters on the top row are (QWERTY). So, it’s a word that describes the complete keyboard that you will find, for example, on most computers and on many types of cell phones.
Our next question comes from Alexandre (Alexandre) in France. His question is about the expression, “can’t help but.” For example, if someone says, “I can’t help but laugh when I watch The Simpsons,” “I can’t help but laugh” means it is impossible for me not to laugh – I have to do it. I cannot stop myself from doing it.
We usually use this expression when we don’t want to do something or shouldn’t do something, but we do it anyway because it is impossible for us to stop – it is impossible for us to resist. Perhaps you see somebody fall on the street, and later you say, “I couldn’t help but laugh when he fell.” That would be one use of that particular expression.
Our final question comes from Jihai (Jihai) in Japan. Jihai wants to know the meaning of two expressions, “stolen glance” and “witchcraft.” Let’s start with the expression, “stolen glance.” A “stolen (stolen) glance (glance)” – two words – is when you look at something very quickly. “Stolen” comes from the verb “to steal,” which means to take something that doesn’t belong to you. To steal something from someone is to take it from them.
A “stolen glance” means to look quickly at something that you are probably not supposed to look at, or don’t have permission to look at. It’s very similar to the verb “to peek” (peek). “To peek” also means to look at something quickly, and “stolen glance” is a similar expression.
The last term is “witchcraft.” “Witchcraft” (witchcraft) – all one word – has to do with magic. A witch is a woman who performs magic. (If you remember the Harry Potter movies, there are witches in the movies.) Witchcraft is just another word for the kind of magic that a witch would do.
Well, we hope that we have done some magic for you today. If you have a question about an expression, you can email us at eslpod@eslpod.com, and we’ll try to answer it.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you again next time right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2006 by the Center for Educational Development.
Glossary
to arrest – to take someone who may have committed a crime to prison, usually done by the police
* After running for three years, the bank robber was found and arrested by the Belgium police.
police force – an organized group of police officers, usually belonging to a city or a state
* The city of Los Angeles is offering high salaries to recruit people to join their police force.
officer – an official person working for an organization or for the government; a policeman or policewoman
* Excuse me, officer. This boy is lost and needs help to find his parents.
state trooper – a police officer working for one of the US states
* I heard that just outside of the city, there are a lot of state troopers trying to catch people speeding along this freeway.
squad car – police car used for driving around the area that the officers are watching and trying to keep safe
* The neighbors saw a squad car pull up outside the house where a loud party had been going on for four hours.
precinct – a police station located in a neighborhood
* The police officer advised me to go to my local precinct to file a report about my stolen car.
animated – a way to film drawings to make them look like they are moving; a movie or TV show that is made with drawings instead of real people
* Some animated movies are now making more money than movies with famous movie stars!
satire – using humor or jokes to make fun of other people’s beliefs or actions, sometimes done to cause or to prevent change
* This comedian is famous for his political satire about the president and his policies.
D’oh! – an exclamation made famous by Homer Simpson, a character on an American animated TV show called The Simpsons to express surprise or disappointment
* D’oh! I know I’m on a diet but do you have to take away my cookies, pizza, and potato chips?
Don’t have a cow! – don’t overreact; don’t have such a big reaction to a small thing
* Dr. McQuillan got upset when I borrowed his toothbrush to clean the floor, but I told him, “Don’t have a cow!”
it’s going down – it is happening now; it is proceeding, often used for illegal activities
* Did you hear about the car race? It’s going down right now in the center of town!
qwerty – the standard arrangement of an English-language keyboard with the letters q, w, e, r, t, and y as the first keys on the left side on the top row
* Until they come out with a cell phone with a qwerty keyboard that’s easier to use, I don’t plan to get a new phone.
can’t help but – have no choice except to do something; cannot control oneself to do anything differently than this
* I know that June is 18-years-old, but I can’t help but worry that she’ll get into trouble traveling to Australia by herself.
stolen glance – a quick look at someone or something taken so that others will not see it
* He didn’t want anyone to know that he was in love with Kerri, so during the ceremony, he only took a few stolen glances in her direction.
witchcraft – magic
* This book is about a period in American history when people suspected of using witchcraft were put in prison or killed.
What Insiders Know
Seinfeld: “Yada, yada, yada” and “Get out!”
One of the most popular TV shows in recent years was called Seinfeld. This show was on U.S. television from 1989 to 1998, and it is still shown in most American cities in “reruns,” when a show is shown again after it’s first broadcast. This show was a “sitcom,” or situation comedy that was 30 minutes long and was shown every week. The main character in the show, Jerry Seinfeld, was a “standup comedian,” or a person whose job it is to tell jokes in front of an audience, and the show was about him and his friends. The show was so popular that many of the sayings or “catchphrases” from the show has become part of the language that people use in everyday American life.
The phrase “Yada, yada, yada” was used on the show when the speaker wanted to “skip” or pass over something they didn’t want to talk about because it is too obvious or they don’t want to say aloud, sometimes for something that was embarrassing. It means the same as “and so forth” and “blah, blah, blah.” For example, you may use it when telling your friend about something that happened to you: “I was walking out of the store when the clerk stopped me and accused me of stealing. There were a lot of people around and they were all looking at me. The clerk took me into his office and yada, yada, yada. I didn’t leave the store for an hour!”
Another phrase used on the show Seinfeld that people still use today is, “Get out!” Normally, we use this phrase to tell someone to leave a place. However, it was used on the show to express surprise when someone heard some good news. One of the characters on the show, Elaine, would give the person telling her the good news a playful but powerful “shove” or push, and then yell, “Get out!” So, if someone tells you that you’ve won a trip around the world, you might say to them, “Get out!” You don’t want them to leave. You’re just expressing your surprise.