= 1376
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast's English Café, number 71.
This is English as a Second Language Podcast's English Café number 71. I'm your host Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com to download the Learning Guide for this episode. We also have some new things on our website including our ESL Podcast Store, where you can download previous Learning Guides from our older podcasts as well as some new courses that we think you'll enjoy.
Our topics today on the Café are going to be “How to Ruin Your Computer” - I will tell you a little bit about my experience with this. We're also going to talk about how much things cost - what do very common things that everyone uses cost here in Los Angeles - how much money would you pay for them. That's always interesting to know, and as always, we'll answer a few questions. Let's get started!
A couple of weeks ago, I was working on my computer. I have a little laptop, “laptop,” which is a computer that's usually small and thin, between 12 and, maybe, 17 inches in terms of the size of the screen.
Well, I was working hard, as I always do, and like many Americans I like to have something to drink at my desk. Someone said that they notice that Americans are always drinking something, even when they are out in public they have a bottle of water or cup of coffee from Starbucks or some soda. And that's, I think, true, especially in the office people like to have coffee or tea or soda. I like, in this case, to drink water.
Well, you can guess what happened. The water accidentally spilled onto the top of my laptop computer. That's why I call this first part of our Café “How to Ruin Your Computer.” To ruin, “ruin,” means to hurt something or harm something - to make it so that it is no longer good or that you can no longer use it.
This verb, to ruin, is actually very, what we would call, versatile, “versatile.” When we say something or someone is versatile we mean they can do something - many different things, or they can use something in many different ways. Well, the verb to ruin is a very versatile verb. You can ruin your computer, which is what I did because I spilled water on it. To spill, “spill,” means that you put some liquid on something, usually by mistake - by accident.
I spilled some water and it ruined the computer. I was saying that this verb, to ruin, is versatile; you can also ruin your clothes, if you spill something on your clothes. Or, we can use this verb when we are talking about a movie. Something in the movie happens that you don't like and it ruins the movie for you, meaning you can no longer enjoy it because they did something that you really didn't like in the movie. You can also ruin a meal. If you are talking to someone, and you're having a nice meal at a restaurant and suddenly two other people come in and they are talking very loudly and yelling on their cell phones in the middle of the restaurant - something which I really hate! Well, that could ruin your meal - it could make it no longer enjoyable.
I ruined my laptop, and I brought it into the repair shop. I should confess - I should tell you a secret, which is that after I spilled the water I turned the computer off and I dried it off. I took some towels - some cloths - to get the water off of the laptop, and I waited for about ten minutes. Then, I thought I would restart the computer to see if it was still working. This is a big mistake! If you ever spill something on your laptop, do not turn it on again right away, like I did. You should wait probably a whole day - 24 hours - before trying to turn it on.
Unfortunately, I didn't know that when I turned on my computer, and what happened was the water was still in the computer and it essentially - basically - fried the main part of my computer. The expression to fry a computer part means that it burned. This word fried, as an adjective, means something has been burned with fire or some other heat. This is an expression we use about computers, you say, “Well, the motherboard” - or the logic board, which is the main part of the computer - “is fried,” meaning it's - it - it doesn't work anymore.
I took the laptop into a repair shop to get it fixed. To take something in means to bring it somewhere to get fixed. You may say, “I need to take my car in to get some new oil” - to get my oil changed. Well, you can take in your computer, and that's what I did. Unfortunately, they told me that the computer could not be saved, and they could salvage, however, the hard drive.
To salvage, “salvage,” means that you are able to rescue or get something that was in danger out of danger. Usually, we use this when we are talking about, for example, a large ship that has an accident and some things fall into the water that were on the ship. You may try to go into the ocean and salvage that which came off of the ship. So, you save it - you rescue it - you bring it back and you are able to use it again.
I'm able to salvage my hard drive, and that's a good thing because I did not back up my hard drive recently. That's another good lesson. To back up, “back up,” (two words) means to put the information on your hard drive somewhere else so you have two copies.
So, that's how you ruin your computer. I don't recommend it, however! Now, the good news is that I will be able to by myself a new computer, so that's the good news. My wife doesn't really think that's good news, but I do!
I thought it would be interesting to talk today about how much things cost in Los Angeles, in the United States. The price of different things, of course, is very different depending on the country you live in. In the United States, it also depends on the part of the country where you live. In some parts of the country, for example, gas is more expensive. In other parts of the country, things like milk and cheese are more expensive. It depends on where you live because different products come from different parts of the country and the world, and so sometimes the price is different.
Well, let's start with the price of gas. Currently, in January of - or February - of 2007, gas here in Los Angeles, where I live, costs about two dollars and 55 cents a gallon ($2.55). You could also just say two 55 - that means, in this case, two dollars and 55 cents.
Now, in some parts of the United States the gas is much cheaper. In many places you can get gas for two dollars and 15 cents right now ($2.15). However, California has higher taxes than other states. Each state can put a different sales tax on things that are sold in the state. California has a very high sales tax, especially for gasoline, so we pay much more than most places. The only state where they probably pay more for gas than California is Hawaii, and that is because it's an island and the transportation costs for getting the oil there are very high.
Houses in Los Angeles are also very expensive compared to other parts of the United States. This is true in New York and Chicago, Boston, Washington D.C., Los Angeles, San Francisco - any big city usually has higher prices for the homes than smaller cities. California has very high home prices; here in Los Angeles, the average home is probably about 400 thousand dollars ($400,000). Now, if you live in Europe, you can multiply that by .75 or so - 75 percent of that; that would give you the price in euros. In Japan, you would multiply that by, I think, 121 to get the number of yen - that would be - and those of you in other countries can probably know roughly what the conversion is into your currency. So, 400 thousand dollars ($400,000) is the average price. That means there are many houses that are more expensive, and there are houses that are less expensive.
In other parts of the United States such as St. Paul, Minnesota, where I'm from originally, the average house is much cheaper, maybe 200 thousand dollars ($200,000). So, it depends on the place where you live.
A new computer - a new laptop computer - a new MacBook computer, made by Apple Incorporated (Apple Inc.) costs around 11 hundred dollars ($1,100) for the cheapest version - we'd say the cheapest model, “model.” Of course, I know how much that costs since I have to get a new computer!
Daily newspapers in the United States are fairly inexpensive. In some countries there are now in big cities like London and Paris and other places, they have newspapers that are free that you can find in the subway or metro stations. This is not as common in the United States; I think there may be a free newspaper in New York. But, in cities like Los Angeles, the local newspaper is between 25 and 50 cents (25￠ and 50￠). That's for a local newspaper - a newspaper that is published and distributed mainly in that one city.
There are national newspapers - like the Wall Street Journal and the New York Times - that cost more, usually about a dollar ($1.00) a day if you buy them at the newsstand. A newsstand is a place where you buy newspapers.
The price of food in the United States, again, depends on where you live and depends on what you like to eat. If you were to go to an average restaurant - not McDonald's, not a fast food, but not the best restaurant in the city, somewhere in between - you would probably pay about ten to 15 dollars ($10.00 to $15.00) for an entrée - that's your main meal - your main course we would say. There are, of course, additional costs for the tax, and you have to leave, in most restaurants, a tip for the waiter or waitress that helped you. The average tip is ten to 15 percent (10% to 15%), sometimes 20 percent (20%) in a good restaurant.
Cable television or satellite television is also very popular. A month of cable or satellite TV in the US right now is about 60 to 80 dollars ($60.00 to $80.00) a month, so it can be quite expensive. Some people don't have cable TV; they just have the local channels.
Phone service in the US is also, again, dependent upon where you live. There are different phone companies in different parts of the country. I think our local phone service is about 30 or 40 dollars ($30.00 or $40.00) a month. If you have a cell phone or a mobile phone, you'll probably pay around 40 to 80 dollars ($40.00 to $80.00) a month, depending on how much service you have.
Finally, rent in the US if you're going to rent a house or rent an apartment. This is also very different in different parts of the country. In Los Angeles, to rent a one bedroom, one bathroom apartment would probably cost you about eight hundred dollars ($800.00) on average a month. That is usually not including your telephone, your heat, your electricity, gas, et cetera.
In other parts of the country, again to give the example of Minnesota, you would probably pay only half of that, maybe 400 or 450 dollars ($400.00 or $450.00) a month. So, it's much cheaper to live in other parts of the country.
Now let's answer a few questions.
Our first question comes from Kambiz, “Kambiz,” from the country of Iran. Kambiz wants to know the difference between the words secret, “secret,” private, “private,” and confidential, “confidential.”
All of these words are used to describe something that is not known to other people, or it is not meant to be known - you don't want other people to know about it. It's information that you don't want other people to have.
We use these words in a little different way. Secret is usually for something that is not supposed to be known to other people - that shouldn't be, we would say, public. When we say something shouldn't be public or is not public, we mean that it is not known by most people - only some people know it, and it is something that you try to keep from other people. So, secret is a general term.
Confidential is usually used for official situations, such as the government. “The government has confidential information” - that means that only the government or people in the government know about it. For example, if you are talking about spies, “spies,” spies are people who try to get information, usually about another country. Confidential information is information that an organization, such as a government but also a company, tries to keep secret - tries to protect from other people.
Private can also means something belonging to or only used by a particular person. So, private can mean the same as secret, but it also can mean something that only a certain group of people or only certain people use. For example, “Our company has a private box of seats at the sports stadium that only people who work for the company can use.” So, there is an area in the sports stadium, where people watch teams playing sports like soccer or baseball or basketball, and there's an area - we usually call them a box because it's almost like a separate room near the top of the stadium - where they have seats that only people who are members of that company can use. And the companies pay a lot of money for these special - private, if you will - seats. Private here doesn't mean secret, it just means that only a certain group of people can use them.
So, to review, children could have secrets, information from your company could be confidential, and your letters could be private if you don't want other people to read them. Secret is also a word you would use for your password - don't tell anyone your password for your bank account; it should be a secret.
Our next question comes from Oswaldo, “Oswaldo,” in Puerto Rico - in Puerto Rico we would say in English. Oswaldo wants to know the difference between the word cliché, spelled “cliché,” with an accent mark over the “e” - a little line over the “e” - and touché, “touché,” with an accent over the “e”.
A cliché is a phrase or an expression or opinion that is used too much - that is overused - and using it shows or demonstrates that you don't have very original thinking or an original thought. So, if someone says to you, “I saw this movie, and the good guys in the movie were wearing white and the bad guys were wearing black,” you could say this movie is full of clichés because in all of the movies, the good guys wear white and the bad guys wear black. It's a cliché - it's been done too much - it's been used too much.
Touché is something you say to someone else who has said something very smart or clever, usually something that makes you look bad - that makes you look, perhaps, not as good as the other person. For example, you're complaining to your friend that the people you meet are often rude - not nice. Especially if you bump into someone - you hit someone accidentally - and the person doesn't say they're sorry, which is what you would normally say if you are on a train, for example, and you hit someone accidentally - by mistake - you would say, “Sorry.”
Your friend tells you that you are sometimes rude, and you say, “Touché,” meaning you're right. You pointed out something to me that was very smart - very clever - that I didn't think of that makes me not as good, or not appearing as good.
Both of these words come from French originally. In English, as I said before, when we write them there's an accent mark over the “e” at the end of the word.
That's all we have time for. If you have a question you can email us, our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on the English Café.
English as a Second Language Podcast's English Café is written and produced by Dr. Jeff McQuillan. This podcast is copyright 2007, by the Center for Educational Development.
Glossary
laptop – a small portable (able to move from place to place) computer
* When I needed a new computer, I bought a laptop instead of a desktop so that I can take it with me when I travel.
to ruin – to destroy; to damage something so that it cannot be repaired
* I walked outside in the rain in my new jacket and now it’s ruined!
versatile – able to be used for different things and in different ways; able to change easily
* This new table we bought is really versatile. We can use as a dining table or as a desk.
to spill – to cause liquid to flow or fall out of a container by accident
* She forgot to put the cap back on the bottle, and when her roommate took it out of the refrigerator later, soda spilled everywhere
fried – destroyed by burning (with fire or high heat), usually used for electronic things
* Nicholas was hoping that his cell phone could be fixed, but the clerk at the store said that it was fried.
to take (something) in (for repair) – to bring something to a store or center to be fixed
* When do you have time this week to take the TV in to get fixed?
to salvage – to rescue; to prevent something from being lost completely or destroyed
* Sinead and Paul went on a long vacation together in hopes of salvaging their troubled marriage.
to back up – to save a copy of files from a computer in case there is a problem with the original files
* I know I should back up my hard drive everyday, but I keep forgetting!
model – one version of a product; one type of product among others
* This DVD player comes in three models. All three cost about the same, but they have slightly different features.
spy – a person who secretly gets information on someone or something, and gives that information to someone else, usually a government or a business
* Have you seen that movie about the two spies? One of them works for the US government and other one is a spy for Britain.
secret – something that should not be told to other people; information that should not be known by other people
* My granddaughter asked me, “If I tell you where I hid my doll, can you keep it a secret from my brother?”
private – something that should not be told to other people; something that belongs to and is used only by a particular person or group of people
* When I was little, I used to keep a diary where I wrote down all of my private thoughts.
confidential – something that should not be told or shown to other people; usually for official use for things such as information, records, or reports
* The management sent out an important memo to all of the managers marked “confidential.”
cliché – a phrase or an opinion that is used too often and shows a lack of original thought or thinking
* Curt tries to impress everyone when he talks, but he uses so many clichés, it’s hard to take him seriously.
touché – said as an acknowledgement (recognition) when someone else has said something smart or clever at your expense (while making you look bad)
* A: You complain that schools don’t teaching students how to write, but
look at all these mistakes in your report!
B: Touché! I guess I’m no better than the kids today.
What Insiders Know
Computer-Related Versions of Old Sayings:
Give a man a fish and you feed him for a day. Teach him to use the Net and he won't bother you for weeks.
You can't teach a new mouse old clicks.
Computers have changed our lives in many ways. It has even changed some old and well-known English “sayings,” or short phrases or sentences that have in them good advice or wisdom. These “takeoffs” (new versions) are often very funny.
The original version of the first saying is: “Give a man a fish and you feed him for a day. Teach him to fish and you feed him for a lifetime.” “To fish” means to catch fish from the lake or ocean, usually using a fishing “pole” (stick) or a “net” (something made from rope to catch fish). This saying, then, means that if you give other people something, they will benefit only today or right now. But if you teach people to do something on their own, they can take care of themselves and won’t need you or someone else to help them.
The takeoff on this phrase is: “Give a man a fish and you feed him for a day. Teach him to use the Net and he won’t bother you for weeks.” The “Net” means the “Internet” and is a “pun” for the other meaning of “net,” which is something made of rope to catch fish. A “pun” is a joke that uses two meanings of the same word. So, the meaning of this saying is that if you teach someone how to use the Internet, they can keep busy by themselves without troubling you for a long time. We all know how much time we “waste” (to use carelessly) “surfing” (moving from one website to another) on the “Net!”
Another famous saying is: “You can’t teach an old dog new tricks.” This means that it’s difficult to teach a new way to do something to a person who is used to doing it the “old” way. A takeoff on this saying is: “You can’t teach a new mouse old clicks.” A “mouse” is the part of your computer that you put in your hand or that you control with your finger that allows you to move around to different places on your computer screen. A “click” is when you press down with a mouse. This saying, then, means that you can’t do things the old way with a new device or method.