= 0322
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 322: Picking up a Rental Car.
This is English as a Second Language Podcast episode 322. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at eslpod.com and download a Learning Guide for this episode. There you can find all of the vocabulary, definitions, additional sample sentences, cultural notes, and a complete transcript of this episode.
This episode is called “Picking up a Rental Car.” When you are traveling and you need a car, you can rent one. You “pick it up” means you get it. In this case, we’re going to hear a conversation between Ralph and someone who works for the rental car company, and we’ll hear all the common expressions and phrases you use when you are picking up a car. Let’s get started.
[start of dialogue]
Ralph: I have a reservation for a car.
Clerk: What is the last name on the reservation?
Ralph: It’s Furcal.
Clerk: Just one moment. I have a reservation for Ralph Furcal, picking up today and returning on the 19th.
Ralph: Yes, that’s right. I reserved an economy car.
Clerk: We do have an economy car reserved for you, but for $3.00 more per day, you can upgrade to a mid-sized car. And, for only $5.00 more per day, you can upgrade to a convertible. Would you like to take advantage of either of these offers?
Ralph: No, thanks. I’ll stick to the economy car.
Clerk: That’s fine. If you’ll just sign here and initial here, here, and here, please. Would you like to purchase insurance for the car?
Ralph: No, thanks.
Clerk: Okay, then just sign here to decline the insurance. Be sure to return the car with a full gas tank or you’ll be charged $3.00 per gallon. Remember also that you are not allowed additional drivers unless they are over the age of 25.
Ralph: Okay, I’ll do that.
Clerk: Here is your contract. Your car is in parking space number W34. Just show your paperwork to the employee at the gate as you exit the parking lot. Do you need a local map?
Ralph: Yes, I’d like one. Thanks.
Clerk: Here you are. Have a good stay in our city.
Ralph: Thanks. I appreciate it.
[end of dialogue]
Ralph begins the dialogue by saying, “I have a reservation for a car.” A “reservation” is an arrangement to have or do something at a future date in time. Usually it’s something that you are either going to do such as go to dinner, you can have a dinner reservation, or, in this case, something that you are going to get – a reservation for a car. They put your name down and they are going to keep, or hold, a car for you.
The clerk says, “What is the last name on the reservation?” Ralph says, “It’s Furcal.” The clerk says, “Just one moment. I have a reservation for Ralph Furcal, picking up today and returning on the 19th.” “Returning” here means the date you are going to bring the car back. Ralph says, “Yes, that’s right. I reserved an economy car.” An “economy” car is sometimes called a “compact” (compact) car. It’s a small car, usually not very expensive; it’s cheaper to rent an economy car. It’s also cheaper because small cars use less gasoline.
The clerk tells Ralph, “We do have an economy car reserved for you, but for $3.00 more per day, you can upgrade to a mid-sized car.” What’s happening here is that the clerk is trying to get Ralph to get a bigger car and pay more money. This is very common in American rental car companies, what we would call “rental car agencies.” You go to pick up your car, you order a small car, and they try to get you to rent a larger car so they can get more money. In this case, the clerk says “you can upgrade,” or choose a higher class of something – choose a better type of something. That’s to “upgrade.” “You can upgrade to a mid-sized car.” A “mid-sized,” or average-sized car is one that is not too small, not too big. Something in the middle – “mid-sized.”
The clerk continues, “And, for only $5.00 more per day, you can upgrade to a convertible.” A “convertible” car is one where the top of the car – the roof – can be folded down or removed, so you have the sun and the wind right on you. These are very popular in warm places like Southern California, where people have convertibles. Not me, other people. Convertible cars are usually more expensive.
The clerk says, “Would you like to take advantage of either of these offers?” “Would you like to take advantage of...” means would you like to get the benefit from one of these offers. An “offer,” here, is a promotion – a special deal, something that the company offers to do or sell you for a cheaper price, usually for a limited time. Sometimes you’ll hear commercials that say, “limited time offer,” meaning you have to buy it before a certain date, or otherwise you will not get the discount.
Ralph says what I always say, “No, thanks. I’ll stick to the economy car.” To “stick to” something is a very common phrasal verb meaning to remain with something, not to change your plans, to continue to do what you had originally planned to do. So, you plan on going to a movie, and your wife or husband says, “Oh, let’s go shopping instead,” and you say, “No, I want to stick to our plan, we’re going to a movie.” So, Ralph is going to stick to the economy car, he’s going to continue with his plan to rent the smaller, cheaper car.
The clerk says, “That’s fine (okay). If you’ll just sign here and then initial here, here, and here, please.” Two things about this expression: first, notice the clerk says, “If you’ll (if you will) just sign here.” It’s sort of a polite way of saying please sign here. In a rental car agreement – a contract – you have to sign several places. Sometimes you don’t need to give your whole signature, and they’ll ask you to initial. To “initial” means to put your first letter of your first name and the first letter of your middle and last name next to something that you are agreeing to.
The clerk says then, “Would you like to purchase insurance for the car?” “Insurance” is when you pay a small amount to an insurance company, in case you have an accident the insurance company will pay for the damage. In the United States, it’s very important to have insurance; in fact, you are required to have insurance. If you are coming from another country, you will have to buy insurance from the rental car agency. This is usually somewhat expensive, sometimes as expensive as the car itself – the rental price of the car itself. If you live in the United States and you have insurance on your own car, usually you do not have to buy the insurance. There are some credit card companies, also, that will insure your car if you have a problem, if you use their credit card.
Ralph here has insurance, and so he says, “No, thanks.” The clerk says, “Okay, then just sign here to decline the insurance.” To “decline” to do something means to decide not to do something, to say no to something. “She declined my invitation to go to dinner” – she told me no. Happens all the time – well, used to happen all the time before I became happily married!
The clerk says, “Be sure to return the car with a full gas tank (or a full tank of gas) or you’ll be charged $3.00 per gallon.” Most rental car companies in the U.S. will give you the car full of gas, and then you can bring it back, but when you bring it back you must put gas in it so that it has a full tank of gas. If you don’t, they will charge you extra money to put the gas in. So, right before you go to the rental car agency, near the airport for example, you have to stop and “gas up,” or put gas into your car – into your car’s gas tank, the place that holds the gas in the car.
The clerk says, “Remember also that you are not allowed additional drivers unless they are over the age of 25.” An “additional driver” is someone who is going to drive the car besides you – in addition to you. Also in most U.S. states, most U.S. rental car agencies say you have to be 25 years old to rent a car, so high school student, for example, cannot rent a car.
Ralph says, “Okay, I’ll do that.” The clerk then says, “Here is your contract (here is your agreement). Your car is in parking space number W34. Just show your paperwork to the employee at the gate as you exit the parking lot.” In most airports, for example, the rental car companies – or in many airports, the rental car companies are right at the airport, so you go into a garage and you find your car. You then drive your car to the exit, and at the exit there will be a guard who will ask to see your paperwork. Your “paperwork” is your documents; these are the papers that show you have rented and paid for the car.
Finally, the clerk says, “Do you need a local map?” “Local” here means of the area where you are, not far away. A “local newspaper” is a newspaper for that area: the Los Angeles Times is our local newspaper. Ralph says, “Yes, I’d like one. Thanks.” The clerk says, “Here you are (when you give something to someone, you often say “here you are” or “here you go”). Have a good stay in our city.” Ralph thanks the clerk and says, “I appreciate it.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Ralph: I have a reservation for a car.
Clerk: What is the last name on the reservation?
Ralph: It’s Furcal.
Clerk: Just one moment. I have a reservation for Ralph Furcal, picking up today and returning on the 19th.
Ralph: Yes, that’s right. I reserved an economy car.
Clerk: We do have an economy car reserved for you, but for $3.00 more per day, you can upgrade to a mid-sized car. And, for only $5.00 more per day, you can upgrade to a convertible. Would you like to take advantage of either of these offers?
Ralph: No, thanks. I’ll stick to the economy car.
Clerk: That’s fine. If you’ll just sign here and initial here, here, and here, please. Would you like to purchase insurance for the car?
Ralph: No, thanks.
Clerk: Okay, then just sign here to decline the insurance. Be sure to return the car with a full gas tank or you’ll be charged $3.00 per gallon. Remember also that you are not allowed additional drivers unless they are over the age of 25.
Ralph: Okay, I’ll do that.
Clerk: Here is your contract. Your car is in parking space number W34. Just show your paperwork to the employee at the gate as you exit the parking lot. Do you need a local map?
Ralph: Yes, I’d like one. Thanks.
Clerk: Here you are. Have a good stay in our city.
Ralph: Thanks. I appreciate it.
[end of dialogue]
The script for this podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
reservation – an arrangement to have or do something at a future date and time; an arrangement so that something is held for one’s own use at a future date or time
* Have you made a reservation at a hotel for next Tuesday night?
economy car – compact car; a small, inexpensive car that doesn’t use very much gas
* I prefer to buy an economy car because it’s small and inexpensive.
to upgrade – to choose a higher class of something; to choose a better type of something
* The airline offered to upgrade our seats from coach class to first class.
mid-sized car – an average-sized car, not too small and not too big
* When the Wu family had its third child, they decided to buy a mid-sized car because their old car wasn’t big enough anymore.
convertible – a car where the roof can be folded down or removed so that the passengers can feel the wind and sun
* Having a convertible isn’t very practical if you live in a state where it rains a lot.
offer – promotion; special deal; something that a company offers to do or sell inexpensively or for free for a limited period of time
* This airline has an offer where you can fly to Puerto Rico for only $225 between now and the end of the month.
to stick to (something) – to remain with something; to not change one’s plans; to continue to do what one had originally planned
* Are you going to swtich to the deluxe service or stick to the basic service you’ve always had?
to initial – to write the first letters of one’s first, middle, and last name, usually on a legal agreement, to show that one agrees with something
* Please initial each page of this agreement, and then sign your name on the last page.
insurance – an arrangement where one pays money to a company each month, and if something bad happens, that company will pay one a lot of money to cover the costs, such as for fire, floods, theft, health problems, or death
* Some people with young children buy life insurance, so that if they die, their family will have enough money to live.
to decline – to decide not to do or accept something; to say ‘no’ to something; to refuse something
* I decided to declined the company’s offer for early retirement.
gas tank – the part of a car that is filled with gasoline
* It costs more than $45 to fill this car’s gas tank!
additional driver – a person who will drive a rented car and whose name is not on the rental agreement
* Many car rental companies charge extra for additional drivers.
contract – a legal agreement; a legal document that shows what two or more people or businesses are agreeing to
* I had to sign a two-year contract with the phone company to get my cell phone at a discounted price.
paperwork – documents; all the forms and other papers that are needed to do something or apply for something
* Have you finished the paperwork for your university applications?
local – nearby; connected with the surrounding area; not far away
* The McQuillan Times is the best local newspaper in the country!
Comprehension Questions
1. What does Ralph decide not to get?
a) An economy car.
b) Insurance coverage.
c) Additional drivers.
2. What does Ralph need to do after signing the contract?
a) Show his papers to the parking lot attendant.
b) Get a map of the local area.
c) Park the car in space W34.
Answers at bottom.
What Else Does It Mean?
to stick to
The phrase “to stick to (something),” in this podcast, means to not change one’s plans, or to continue to do what one had originally planned: “We thought we might be able to finish the project early, but we have decided to stick to our original schedule.” The phrase “to stick with (something)” means to continue to do something, even though it is difficult: “He didn’t enjoy playing the violin and wanted to stop taking lessons, but his parents convinced him to stick with it.” The phrase “to stick (someone) with (something)” means to do something so that another person has to do something unpleasant, without one’s help: “My boss left early and stuck me with finishing the work.” The verb “to stick” means to adhere, or for two things to be attached to each other, usually with glue or tape: “May I stick this poster on the wall?”
initial
In this podcast, the verb “to initial” means to write the first letters of one’s first, middle, and last name, usually to show that one agrees with something: “The bank employee initialed the check before giving the customer his money.” One’s “initials” are the first letters of one’s first, middle, and last name when they are written together: “Wally Hou wrote his initials, W.H., on all his books so that he could find them if they got lost.” The word “initial” also means first, or earliest: “His initial reaction was anger, but then he calmed down.” The adverb, “initially,” means at first, or in the beginning: “Initially, this company had just one office, but now it has offices in almost every state.”
Culture Note
People who rent cars in the United States have many “options,” or choices. They can rent the car “onsite” (where the rental car company has an office) or “offsite” (away from a rental car office, so that the company brings the car to another location). Onsite car rentals are “cheaper” (less expensive), but offsite car rentals are more “convenient” (easy and simple, because one doesn’t have to do anything special), because the company brings the car to wherever it is needed. Onsite care rentals are usually cheapest at airports, where rental car companies offer the greatest “selection” (the number and variety of cars that are available).
When “shopping around” (looking for the lowest price) for a rental car, be aware that the companies don’t provide the “full” (total or entire) cost of renting the car. There are usually many “fees” (additional costs) and “taxes” (a percentage of the price that must be paid to the government) that are not included in the “quoted price” (the amount that a company says something will cost before the purchase). When making a reservation, ask what the rental fee would be with taxes and fees to get a more accurate total.
Rental car companies always offer car insurance, which is a good idea in case the driver gets into an accident. However, be aware that many credit cards “automatically” (happening without one having to do anything special) provide insurance for cars rented with their cards.
It is important to return the rental car “on time” (not late), because if it is returned late, the rental car company might charge the customer for an extra day. Ask if the rental car company has a “grace period,” a short period of time when you can return the car late, but still pay no extra charges. Also, the car needs to be returned with a full gas tank. If not, the company may charge the customer an “exorbitant” (extremely expensive) amount of money to fill the tank.
Comprehension Answers
1 - b
2 - a