= 0343
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 343: Being Alike and Different.
This is English as a Second Language Podcast episode three-four-three (343). I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California, the home of Hollywood; the home of Angelina Jolie and Brad Pitt, and George Clooney – and Lucy Tse!
If you’d like to visit our website, you can go to eslpod.com. While you’re there, you can take a look at our ESL Podcast Store, which has some additional business and personal English courses you may be interested in.
This episode is called “Being Alike and Different.” It’s a dialogue between Fabian and Clarissa; their dialogue is about different personalities. It’s going to give you a lot of good vocabulary to talk about someone’s personality. Let’s get started.
[start of dialogue]
Fabian: Oh, your babies are adorable. They’re like two peas in a pod.
Clarissa: They may look like mirror images of each other, but they’re nothing alike. They each have their distinct personalities. Randy likes to sleep during the day and Dominic likes to sleep at night.
Fabian: That’s like my babies at home. They’re polar opposites. They don’t like eating the same foods and they have clashing personalities.
Clarissa: Oh, really? Does that cause problems?
Fabian: Yes, sometimes it does. One is playful all the time and the other one is always pensive. They get on each other’s nerves more often than not. I can’t believe they have the same parents.
Clarissa: You’re telling me! I sometimes wonder how two babies born at the same time can be so different.
[barking sound] Oh, my precious little babies are hungry. We’d better get home so they can eat.
Fabian: I’d better get home to mine. They’ll be crawling up the walls if I don’t get back soon with their treats!
[end of dialogue]
Fabian begins by saying, “Oh, your babies are adorable.” “Adorable” means very pretty, very cute, very attractive. We often use that adjective when you are talking about babies – young children, or perhaps small animals. You may say to someone, “Oh, your 800 pound gorilla is so adorable!” Fabian says the babies are “like two peas in a pod.” The expression “two peas (peas) in a pod (pod)” means they’re almost identical, they’re very similar, they’re like twins. “Two peas in a pod,” used to describe two people who are very alike, very similar. A “pea” is a small, green vegetable that you eat. Peas grow in what are called “peapods,” which are small, you can think of them as little packs – little containers, where the pea itself grows.
Clarissa says my babies “may look like mirror images of each other, but they’re nothing alike.” When we say something is a “mirror image,” we mean it’s identical; very similar in appearance, just like twins. Me and the actor Johnny Depp, for example, are mirror images – really!
Clarissa says her babies are “nothing alike,” meaning they’re not at all the same – they’re not at all alike, they’re completely different. You could say, “My brother and I are nothing alike, he’s completely different than I am.” Clarissa says each of her babies has “their distinct personalities.” Something that is “distinct” is easy to distinguish, easy to tell the difference.
“Randy (one of her babies), likes to sleep during the day and Dominic (her other baby) likes to sleep at night.” Fabian says, “That’s like my babies at home. They’re polar opposites.” When we say something is “opposite,” we mean it’s completely different; it’s not alike. The word “polar” opposites means they’re extreme opposites; they have no similarities, they’re very different – they’re “polar” opposites.
Fabian’s babies “don’t like eating the same foods and they have clashing personalities.” When we say something “clashes,” we mean that it is very different from something else – it causes problems with that other thing. So, “clashing personalities” would be very different personalities – the opposite of someone else’s personality.
Clarissa says, “Oh, really? Does that cause problems?” Fabian says, “Yes, sometimes it does (cause problems). One (child) is playful all the time and the other one is always pensive.” “To be playful” means that you always want to play, you always want to have to fun. “To be pensive” means to be thoughtful, to be thinking about something all the time. Often, people are pensive when they’re sad or worried, but not necessarily. “To be pensive” means to be thinking about something.
Fabian says his babies “get on each other’s nerves more often than not.” There are a couple of expressions there: the first is “to get on each other’s nerves” (nerves). “To get on each other’s,” or “to get on someone’s nerves,” means to bother or annoy them, to do something that makes the other person angry. Usually we have this expression when two people are together for a long time, and they keep bothering each other. Every hour, every day, there seems to be some problem between them – they’re “getting on each other’s nerves.” Well, the babies “get on each other’s nerves more often than not.” The expression “more often than not” means frequently, often, most of the time. “More often than not, I wake up at 7:00 in the morning” – usually, unless I don’t, but usually I do!
Fabian says, “ I can’t believe (the babies) have the same parents.” Maybe they don’t, Fabian! Clarissa says, “You’re telling me!” That expression, “you’re telling me,” is a phrase we use to show that what another person has said is correct, or that you understand what another person is talking about because you agree with them, or you have had a similar experience. For example, someone says, “Oh, I had to pay $1,500 for rent this month, it’s so expensive,” and you say, “You’re telling me! I have to pay $2,000 in rent.” Clarissa says, “You’re telling me,” meaning she agrees or understands what Fabian says. “I sometimes wonder how two babies born at the same time (“twins,” we would call them) can be so different.” Then you hear a barking sound, the kind of sound that a dog would make, and we realize that Fabian and Clarissa are not talking about human babies; they’re talking about little animals.
We usually use the word “baby” to refer to a human, but sometimes people use that in talking about an animal. A baby dog is called a “puppy.” Clarissa then says, “Oh, my precious little babies are hungry.” “Precious” is a word that means very special, very valuable – either because of a money or emotional reasons. When you love something very much, you say it’s “precious.” Sometimes you can even use that word about your husband or wife; you can say, “Oh, my precious – my precious darling.” I say that every day to my wife!
Clarissa says, “We’d better get home so they can eat,” meaning we now have to leave – we ought to, we should get home, or go home, so the dogs can eat. Fabian says, “I’d better get home to mine (to my, in this case, dogs). They’ll be crawling up the walls if I don’t get back soon with their treats!” “To crawl up the walls” is an expression which means you have too much energy – you’re very nervous, anxious, maybe worried or stressed. You could also be very annoyed by some situation. “The noise outside had me crawling up the wall” – I was very upset. In this case, the dogs are excited, which is why they are “crawling up the walls.” The verb “to crawl” (crawl) usually means to get down on your hands and knees and move forward. Little babies first crawl, and then they learn to walk.
In this case, the dogs are going to be crawling up the wall if Fabian doesn’t get back with their treats. A “treat” (treat), in the dialogue, means something that is very tasty, something that tastes good, usually something you give to a child or to a pet – a dog or a cat – in between their main meals. So, they eat breakfast at 8 and they get a treat at 10, usually something sweet but not always. “Treat” has a couple of different meanings; take a look at our Learning Guide for some additional explanations. We also talk about Americans and their pets, and what some Americans do with their pets that you may not believe. Take a look at our culture note in the Learning Guide for a discussion of that.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Fabian: Oh, your babies are adorable. They’re like two peas in a pod.
Clarissa: They may look like mirror images of each other, but they’re nothing alike. They each have their distinct personalities. Randy likes to sleep during the day and Dominic likes to sleep at night.
Fabian: That’s like my babies at home. They’re polar opposites. They don’t like eating the same foods and they have clashing personalities.
Clarissa: Oh, really? Does that cause problems?
Fabian: Yes, sometimes it does. One is playful all the time and the other one is always pensive. They get on each other’s nerves more often than not. I can’t believe they have the same parents.
Clarissa: You’re telling me! I sometimes wonder how two babies born at the same time can be so different.
[barking sound] Oh, my precious little babies are hungry. We’d better get home so they can eat.
Fabian: I’d better get home to mine. They’ll be crawling up the walls if I don’t get back soon with their treats!
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse – who never gets on my nerves!
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
adorable – very cute, pretty, and attractive, especially when referring to young children or animals
* The baby looked adorable in her pink dress.
two peas in a pod – almost identical; very similar; like twins
* Her sons are like two peas in a pod, except that Kensuke has brown eyes and Jun has green eyes.
mirror images – identical; very similar in appearance; like twins
* The twins are mirror images of each other.
nothing alike – not at all the same; not at all alike; very different; completely different
* Their food preferences are nothing alike. She likes salty, crunchy foods, and he likes sweet, soft foods.
distinct – different; easy to distinguish; easy to see the differences between two or more things
* Howard has a distinct way of walking, so I can tell that it’s him even when it’s too dark to see his face.
polar opposites – extreme opposites; not at all alike; completely different
* Those two friends have personalities that are polar opposites: Shane is always happy and Bertha is always depressed.
clashing – being very different and the opposite of something or someone else; not being a good match with something or someone else
* They have clashing views on national politics since he is a Democrat and she is a Republican.
playful – always having fun; always wanting to play and have fun; not serious
* Everyone likes to work with Frank because he brings a playful attitude to the office.
pensive – thoughtful; thinking about something all the time, especially when one is sad or worried
* Maggie became very pensive after her husband died.
to get on (someone’s) nerves – to bother or annoy someone; to do something that makes another person feel frustrated or angry
* My brother gets on my nerves every time he comes into my room without knocking!
more often than not – frequently; often; most of the time
* More often than not he sleeps until 11:00 on Saturdays.
You’re telling me – a phrase used to show that what another person has said is obvious, or that one understands what another person is talking about because it is related to one’s own experience
* When Julie started complaining about how expensive rent was, I said, “You’re telling me! I pay almost $1,300 per month for a one-bedroom apartment!”
precious – dear; very special and valuable, either because of money or for emotional reasons; something or someone that one likes or loves very much
* This is the precious vase that I bought when I was in Phoenix last summer.
to crawl up the walls – to have too much energy; to be very nervous, anxious, bored, worried, stressed, or annoyed
* Shannon was crawling up the walls, waiting to find out whether she had been accepted into medical school.
treat – something that is tasty and is eaten between meals, especially for children and pets
* Our cat loves to eat crunch and salty treats.
Comprehension Questions
1. Which phrase could be used to describe identical twins?
a) Two peas in a pod.
b) Nothing alike.
c) Polar opposites.
2. What does “crawling up the walls” mean?
a) Sleeping quietly and peacefully.
b) Eating everything in the house.
c) Having too much nervous energy.
Answers at bottom.
What Else Does It Mean?
to get on (someone’s) nerves
The phrase “to get on (someone’s) nerves,” in this podcast, means to do something that makes another person feel frustrated or angry: “Doesn’t your husband get on your nerves when he leaves his dirty socks on the floor?” The phrase “to have nerves of steel” means to stay calm in very stressful, difficult, and/or dangerous situations: “She’s a great surgeon because she has nerves of steel and can concentrate no matter what goes wrong during an operation.” The phrase “to be a bundle of nerves” means to be extremely nervous: “Jackie was a bundle of nerves before her important presentation.” Finally, the phrase “to hit a nerve” or “to touch a nerve” means to talk about something that is a sensitive topic for another person and makes him or her upset: “You really touched a nerve when you mentioned Iris’s weight!”
treat
In this podcast, the word “treat” means something that is tasty and is eaten between meals: “Once a month, they go out for ice cream as a special treat for the kids.” As a verb, “to treat” means to relate to someone or behave toward someone in a certain way: “He treats his girlfriend very kindly, always listening to her and supporting her ideas.” The phrase “to treat (someone) like dirt” means to behave very badly toward someone: “She treated her boyfriend like dirt, always asking him to buy her things while she never gave him anything.” Finally, the phrase “to treat (someone) to (something)” means to buy something for another person, especially in a restaurant, or to entertain someone: “I’d like to treat you to dinner tomorrow night to thank you for all your help this past week.”
Culture Note
Many Americans have “pets” (animals that live in their homes and are treated as friends). Often they treat their pets as family members or even as children, giving them all the love, attention, and things that other people might give to their human family members. Americans “pamper” (make someone feel as comfortable as possible) their pets in many ways, and spend a lot of money doing so.
Americans often pamper their pets by taking them to “salons” (businesses that improve one’s appearance) that wash, dry, and cut their pets’ “fur” (the hair that grows on an animal), “clip” (cut) their toenails, and even put “bows” (long, thin, colored pieces of fabric tied in a pretty way) in their fur. Some pet owners also buy clothing for their pets, such as special jackets or sweaters to keep their dogs warm. “Wealthy” (with lots of money) owners sometimes buy “collars” (pieces of leather put around a pet’s neck) that have diamonds or other expensive jewels in them.
Some pet owners buy “fancy” (very nice and expensive) toys for their pets to play with. Other owners pay for “doggie school classes” where their dogs are taught “to do tricks” such as to sit, roll over, and “shake” (hold one “paw” (foot) in the air for a human to hold and move up and down, as if shaking hands).
Many Americans also buy expensive, “gourmet” (very good tasting) food for their pets, even though it might cost as much as (or more than!) regular food for humans. Some of these pets eat their food out of very expensive “food and water bowls” (dishes that are placed on the ground to feed animals) and then go to sleep on soft beds of their own.
Comprehension Answers
1 - a
2 - c