= 0347
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 347: Writing a Postcard.
This is English as a Second Language Podcast episode 347. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the beautiful City of Los Angeles, California – the home of Hollywood; the home of Dr. Lucy Tse!
On this episode, we’re going to listen to someone writing a postcard to a friend, and receiving a postcard. We’ll discuss some typical vocabulary you might use when you are sending someone a postcard. Let’s get started.
[start of story]
I was on vacation in Yosemite and I decided to send a postcard to my friend, Elaine, who was on her own vacation in Europe.
Dear Elaine,
I arrived safely two days ago and I’m having the time of my life. I met some nice people here and we’ve been keeping each other company. The weather has been ideal and we’re off on another hike tomorrow. This is the life.
Wish you were here. I hope you’re having as good a time as I am.
See you soon!
Vivian
On the day I sent my postcard to Elaine, I got one from her. She wrote:
Dear Vivian,
I’ve had a nightmare of a trip. Our flight was delayed and we missed our connection to Oslo. I’ve been here three days and it has poured the entire time. There’s nothing to do but sit in the hotel. What a dump! It looks nothing like the pictures and it’s not at all what I expected. I even got food poisoning the first day I was here!
I hope your trip wasn’t a washout like mine. I can’t wait to get home!
Elaine
[end of story]
Our story begins with Vivian saying, “I was on vacation in Yosemite” – Yosemite is a large National Park here in California, very famous in the United States. “I was on vacation in Yosemite (when) I decided to send a postcard to my friend, Elaine, who was on her own vacation in Europe.” A “postcard” is something that you mail at the Post Office. It’s a small, rectangular piece of thick paper, usually with a photograph on one side and room on the backside to write a short message and the address of the person you are sending it to. Normally with a postcard, you don’t put it in an envelope.
So Vivian is sending a postcard from her vacation to Elaine, and she writes on the back of the card, “Dear Elaine (comma), I arrived safely two days ago.” “To arrive safely” means that you take a plane, a bus, a train, a ship, or a car to get to another place, and you don’t have any problems getting there. “I arrived safely,” it’s a common expression people use when describing the part of their trip related to their arrival. “I arrived safely two days ago and I’m having the time of my life.” The expression “to have the time of your life” means to greatly enjoy something that you have done, something that is very fun, or enjoyable, or memorable. “I’m having the time of my life” – it’s a wonderful time.
“I met some nice people here and we’ve been keeping each other company.” “To keep someone company” means to spend time with another person so that that person doesn’t feel alone – doesn’t feel lonely. “The weather has been ideal (perfect – “ideal” is perfect) and we’re off on another hike tomorrow.” “To be off” means that we are ready to start to do something or to go somewhere. So, “we’re off (we will be leaving) on another hike (another walk through the mountains or through a certain outdoor area) tomorrow. This is the life,” she says. That is a common expression, “this is the life,” to describe a situation where someone is very happy, very relaxed, believes this is one of the best experiences of your life. You win the lottery and you go on a cruise and you say, “This is the life!” – this is a happy situation for me. Unless, the cruise is in Antarctica, and it hits some ice and the ships sinks – hmm, that’s not so happy! But that’s not happening to Vivian, because she’s in Yosemite where there are no oceans.
“Wish you were here,” she says. This is a common expression you will say to someone on a postcard, specifically when you are on vacation. “Wish you were here,” notice we don’t even say “I wish you were here,” it’s just, typically, “wish you were here.” It’s to tell someone that you are having a good experience traveling, and that you think it would be nice if that person could also have that same experience – could share that experience with you. There was also a song in the 1970s by the British rock band, Pink Floyd, called Wish You Were Here.
Vivian continues, “I hope you’re having as good a time as I am.” She then ends her postcard by saying, “See you soon!” (exclamation point) and then puts her name at the bottom, “Vivian.”
“On the day I sent my postcard to Elaine,” she says, “I got one from her. She wrote: Dear Vivian, (comma) I’ve had a nightmare of a trip.” A “nightmare,” you may know, is a bad dream. The expression “a nightmare of...” is used when you have a very bad experience, where everything has gone wrong – it’s been a disaster. “I had a nightmare of a dinner with my boss last night” – it was terrible. “I had a nightmare of a trip” – it was a bad trip.
Well, poor Elaine had a nightmare of a trip. She says, “Our flight (our airplane flight) was delayed and we missed our connection to Oslo.” Your “connection,” when you are flying, is another plane that you have to get on in order to get to the place where you want to go, what we would call your “final destination.” If I want to fly to Paris, I may take a plane to New York, and then in New York “make a connection,” that is, get on a different plane that flies to Paris. Well here, poor Elaine missed her connection to Oslo; the plane got in too late and the other plane left without her. She says, “I’ve been here (we’re not sure where she is) three days and it has poured the entire time.” “To pour” means, in this case, to rain very heavily – to rain a lot. Both “connection” and “to pour” have different definitions in English as well; take a look at the Learning Guide for some additional explanations.
Elaine says, “There’s nothing to do but sit in the hotel.” The use of “but” here means “except.” “Save for” would be another way of saying that: “There’s nothing to do here save for sitting in the hotel.” If you use “save for,” the verb is in an “ing” form. But in this case, she’s saying there’s nothing to do here but sit in the hotel – except sit in the hotel.
“What a dump!” she says. This is an expression you use when you go to a hotel that’s old, it’s dirty, it’s in bad condition, you say, “What a dump!” The word “dump” (dump) describes the place where you take your trash – where you take your garbage. If you live in a city, the city may come by and take the garbage and they put it in a “dump,” in a place with trash and garbage. So to say someplace “is a dump” means it’s a very bad place.
The hotel “looks nothing like the pictures and it’s not at all what I expected.” When you say something is “not at all what you expected,” you mean it’s the opposite of what you thought it would be; it’s not what anyone would think of or expect. She says, “I even got food poisoning the first day I was here!” “Food poisoning” is when you eat something bad that either causes you to go to the bathroom a lot or to “vomit,” when the food comes out of your stomach and out through your mouth. Not a good thing!
Elaine ends her postcard by saying, “I hope your trip wasn’t a washout like mine.” If you say something is a “washout” (one word), you mean it’s a disaster – it’s a waste of time, it wasn’t worth doing.
Finally she says, “I can’t wait to get home!” When you say, “I can’t wait to do something,” you mean you are very eager to do something; you want to do something as soon as possible. Well, poor Elaine can’t wait to get home, and I understand why!
Now let’s listen to the story, this time at a normal speed.
[start of story]
I was on vacation in Yosemite and I decided to send a postcard to my friend, Elaine, who was on her own vacation in Europe.
Dear Elaine,
I arrived safely two days ago and I’m having the time of my life. I met some nice people here and we’ve been keeping each other company. The weather has been ideal and we’re off on another hike tomorrow. This is the life.
Wish you were here. I hope you’re having as good a time as I am.
See you soon!
Vivian
On the day I sent my postcard to Elaine, I got one from her. She wrote:
Dear Vivian,
I’ve had a nightmare of a trip. Our flight was delayed and we missed our connection to Oslo. I’ve been here three days and it has poured the entire time. There’s nothing to do but sit in the hotel. What a dump! It looks nothing like the pictures and it’s not at all what I expected. I even got food poisoning the first day I was here!
I hope your trip wasn’t a washout like mine. I can’t wait to get home!
Elaine
[end of story]
The script for this episode was written by our ideal scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
postcard – a small, thick, rectangular piece of paper with a photograph of a place on one side and room to write a short message and address on the other side so that it can be sent through the mail without using an envelope
* Whenever Lynn travels, she sends postcards to all of her nieces and nephews.
to arrive safely – to take a plane, bus, train, ship, or car to another place and get there without any problems
* Please call us as soon as your plane lands to let us know that you arrived safely!
to have the time of (one’s) life – to greatly enjoy something that one has done, so that it is one of the most fun, enjoyable, and memorable experiences that one has had in one’s life
* I had the time of my life in Oahu, swimming all day and eating great seafood.
to keep (someone) company – to spend time with another person so that he or she does not feel lonely
* The doctors told her to stay in bed for six weeks, so her friends are coming over to keep her company during the long days.
ideal – perfect; exactly what one had wanted and hoped for; couldn’t be better
* Her ideal job is one where she would be paid to travel around the world.
to be off – to be ready to start to do something or go somewhere
* On Friday at 7:00 they’re off to Florida for their one-week vacation in the Everglades.
this is the life – a phrase used to show that one is very happy, content, and relaxed doing what one is doing and believes that this experience is one of life’s best experiences
* The women spent all day at the spa, getting manicures, pedicures, facials, and massages. They kept smiling and saying, “This is the life!”
wish you were here – a phrase used when one is having a good travel experience and wants to tell another person that it would be nice to share the experience with him or her
* We’re having so much fun! Today we went to the Seattle Space Needle and Pike’s Place Market. Wish you were here!
a nightmare of – a disaster; an experience where everything is going wrong
* Right after Tracy graduated from college, she lived in a nightmare of an apartment, full of rats and bugs.
connection – connecting flight; the flight that one takes when one has flown from one airport to another, but still hasn’t gotten to where one wants to go
* To fly from Eugene, Oregon to Denver, Colorado, she had to catch a connection in Portland, Oregon.
to pour – to rain very heavily; to rain a lot
* It’s pouring outside! Let’s wait until it stops to take the dog for a walk.
but – except; save for; unless; only
* I wouldn’t want to live in the desert, where there’s nothing to see but sand.
what a dump – a phrase used to show that a place is very old, dirty, and in bad condition
* What a dump! I can’t believe you’ve lived in this building for almost five years. It’s time for you to find a newer – and nicer – apartment.
not at all what (one) expected – the opposite of what one thought something would be; not what one expected
* Serving in the military is not at all what he expected and he wants to quit so that he can come home.
food poisoning – the state of having diarrhea and/or vomiting because one has eaten food that had bacteria and wasn’t cooked well
* Everyone who was at the picnic got sick that evening, so they decided it must have been food poisoning from the chicken they ate.
washout – a disaster; a waste of time; something that wasn’t worth doing
* That movie was a washout! I can’t believe I wasted two hours watching it.
to not be able to wait to (do something) – to be very eager to do something; to want to do something as soon as possible
* Wendy can’t wait to own her own home.
Comprehension Questions
1. What is Vivian doing with the people she has met?
a) They’re starting a new company.
b) They’re spending time together.
c) They’re sharing company information.
2. Why is Elaine sitting in the hotel?
a) Because it’s a beautiful building.
b) Because it’s where she’ll find a connection.
c) Because it’s raining outside.
Answers at bottom.
What Else Does It Mean?
connection
The word “connection,” in this podcast, means a connecting flight, or the flight that one takes when one has flown from one airport to another, but still hasn’t arrived to where one wants to go: “There weren’t any direct flights from Houston to Milwaukee, so they had to get a connection in Omaha.” A “connection” can also be a contact or a professional relationship with someone, especially with someone who can help one professionally: “Do you have any good connections in the energy industry?” The phrase “to make a connection with (someone)” means to feel like one understands another person and could be friends with that person: “Sidmar really felt like he made a connection with the vice-president during his interview.” Finally, a “connection” can be a link or association between two things: “What’s the connection between inflation and unemployment?”
to pour
In this podcast, the verb “to pour” means to rain very heavily: “It was pouring all day, so the children had to play indoors.” The verb “to pour” also means to hold a large container at an angle so that the liquid inside it comes out and goes into a smaller container or glass: “Olivia poured the lemonade into three glasses for her guests.” The phrase “to pour out (one’s) soul or heart” means to express one’s emotions freely, without hiding anything: “He pours out his heart in his poetry.” Finally, the verb “to pour” can mean to swarm or move in a large group very quickly: “The students poured out of the high school’s doors as soon as the bell rang.”
Culture Note
Americans generally send each other cards and postcards on birthdays and holidays and at other times when they want another person to know that they are thinking about him or her. However, with the “advent” (introduction and development) of the Internet, many Americans are starting to send “e-cards” (electronic cards) and “e-postcards” (electronic postcards) instead of “traditional” (old-style) cards and postcards.
An e-card or an e-postcard has a picture and a short message, just like regular cards and postcards do, but they are sent “via” (through) email. They give the sender space to write a “brief” (short, with few words) message. Many e-cards and e-postcards have “fancy” (special) graphics, “animation” (moving pictures), and music.
Many people like to send e-cards and e-postcards because they are “cheap” (very inexpensive) or free, and because they arrive “instantaneously” (without any delay). To send a card or postcard, people have to “plan ahead of time” (think about something in anticipation) in order to buy the card, write the message, buy a stamp, and mail it. An e-card or e-postcard can be sent in just seconds on the day of the birthday or holiday.
Many younger Americans like receiving e-cards and e-postcards because they think they are “cool” (modern and interesting). But many older Americans dislike receiving e-cards and e-postcards. They think that the people who send them are less “thoughtful” (considerate, thinking about other people) because the e-cards are free and can be sent so quickly and easily. Other people think that e-cards and e-postcards are “annoying” (irritating and bothersome) because they don’t like to receive extra emails.
Comprehension Answers
1 - b
2 - c