
= 0005 Getting Dressed & Ready for Work
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 5: Getting Dress and Ready for Work

This is English as a Second Language Podcast episode number five. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.

In this episode, I’ll talk about getting dressed and ready for work.

Let’s get started!

[Start of story]

I go back into my bedroom and open up closet door. I have about 30 dress shirts, 10 pairs of pants, a half-dozen ties, and some sweaters, suit jackets, and t-shirts. I pull out a clean pair of socks and underwear, and then decide which shirt I’m going to wear today. I’m terrible at color coordinating, so I usually bring my wife in at this point to help match my shirt and pants. I put on my belt with the silver buckle and polish my shoes. I put my cell phone and car keys in my front pocket, and my wallet in the back one.

I put on my glasses and check myself in the mirror to make sure I look okay, and then go into the home office to get my bag. I used to carry a more traditional briefcase, but now I just use my computer bag to hold my laptop and my papers. Now it’s back into the kitchen to grab my Thermos on the way out the door. I lock the door and then hurry to my car in the garage. I’m usually running late and today is no exception!

[End of story]

Part four is called “Getting Dressed and Ready for Work.” We began by me going into the bedroom and opening up my closet door. “To open up” means here to open the door. A “closet” (closet) is a place, usually in your bedroom, where you put clothes—you store your clothing. You can also have a closet in other parts of your house, and it's usually a place where you keep things—you store things.

Well, I “open up my closet door” and I look at my dress shirts. My “dress (dress) shirts” – two words. are the nice shirts, the shirts that I can wear to work. The opposite of a dress shirt would be a “casual shirt” (casual). A dress shirt is a nice shirt; something that usually has a collar on it. A “collar” (collar) is the top of the shirt, what goes around the neck.

Well, I look at my dress shirts and I look, also, at my “pants” (pants). Pants are what you put on your legs. You can have different kinds of pants. Jeans is a type of pants. We might say dress pants for nice pants that you would wear to work. I also have “ties”. A “tie” (tie) is a long, thin thing that goes around your neck that men usually wear—often wear to work, and it comes in different colors, and that's your tie.

A “sweater” (sweater) is something that keeps you warm. It's like a shirt that's very thick. You usually put a sweater over your shirt so that you can be warm. “Suit jackets” (suit jackets) – two words – are jackets that you wear that are for a formal occasion. So, if you are going to work, especially if you were going to an interview, you would wear a suit jacket. The word “suit” (suit) refers to a formal set of clothing for, in this case, a man. For a man it would be pants and a, probably, white shirt and a suit jacket that goes over your shirt. Usually, you would also have a tie that you wear. That's a suit. Well, a suit jacket is part of a suit.

A “t-shirt,” spelled (t-shirt)is a plain shirt that you usually wear underneath a dress shirt. So first, you put on a t-shirt—a white t-shirt—then you would put on your shirt, and then you would put on you jacket. T-shirts can also be used by themselves as your main shirt. It is usually an informal occasion that you would just wear a t-shirt. You probably wouldn't wear a t-shirt to your office, for example, though some people do. And, many people have t-shirts that have things on them—that say things on them. T-shirts usually do not have a collar like a dress shirt does.

“I pull out a pair of socks and underwear.” “Socks” (socks) are the things you put on your feet before you put your shoe on. Socks can be dark, or they can be light or white socks. Normally you don't wear white socks with a formal suit; you would wear black or dark blue socks.

“Underwear” is the piece of clothing that you put on and it covers up all of the—how should we say—things that you want to cover so that you can keep your pants and shirt clean. Underwear is something that goes over your back of your body, your butt or your rear, as well as the front of the body, whatever you have there. Underwear can come for men in two basics styles usually. There can be boxer underwear, or “boxer” shorts (boxer) and that's a kind of short—or rather, a kind of underwear that it is loose on the bottom. So, it's almost like a pair of shorts. The opposite of that would be “briefs” (briefs). Briefs would be underwear that is not loose at the bottom; it's tight at the bottom of the underwear. Usually it's a little smaller as well.

I “then decide which shirt I'm going to wear today. “I'm terrible,” I say, “at color coordinating.” “Color coordinating” means you wear things that have similar or matching colors. So, if you wore a pink shirt you would probably not wear green pants because they don't do together, we would say; they don't look very good with each other. Color coordinating is finding the right colors that you wear on your—with your shirt, and your pants, and your tie, and your jacket, and your socks, and your shoes. All of those have to be color coordinated. The verb “to coordinate,” (coordinate) means to put two things together so that they work well together, in this case.

Well, since I'm so terrible—I'm so bad—at color coordinating I usually bring in my wife, that is I go and ask my wife to come into the room. So, I “bring my wife in”—to the room— “at this point to help me,” meaning at this time, when I've already picked out some things, then I bring my wife to help me “match my shirt and pants.” I want them color coordinate.

“I put on my belt with the silver buckle and polish my shoes.” A “belt” (belt) is what you use to keep your pants from falling down. A buckle is the piece of, usually, metal in the front that connects the belt so it forms a circle around your body. I have a silver buckle that I put on with my belt.

I also “polish my shoes.” “To polish” (polish) means to clean and to make “shiny” (shiny). When we say something is shiny, we mean that it's bright—it reflects light. So, when you polish your shoes, you want them to be clean but you also want them to look like they are bright—they are reflecting light. I polish my shoes and my head, so it's very shiny!

“I put my cell phone,” my cellular or mobile phone, “and car keys in my front pocket.” You have front pockets and you have back pockets in a pair of pants. So, I put my keys and cell phone in the front pocket “and my wallet in the back” pocket. My “wallet” (wallet) is where I put my money and my credit cards and my driver's license; all of those things go in my wallet.

“I put on my glasses,” because I cannot see without my glasses very well, and I “check myself in the mirror.” “To check yourself” means to look at yourself, usually in a mirror, and you can see how you look. I usually look pretty ugly. I check myself in the mirror, and then I go into my “home office,” or my office in my house and get my bag. I used to carry a more traditional briefcase.” A “briefcase” (briefcase) – all one word – is not something that you put your underwear in—your briefs. A briefcase means the thing that you carry papers in when you are going from your home to your office. Usually a briefcase is square and it usually has hard sides on it, many times it has a lock on the top; that's a briefcase. A lot of people nowadays do not use a briefcase; they use a computer bag—a bag that they can put their computer and other information in, including their papers.

Well, I put my things into my computer bag, then I go “back into the kitchen to grab my Thermos,” to get or take my Thermos with my coffee in it “on the way out the door.” The expression, “on the way out,” means that you are about to leave or you are leaving your house, in this case. Somebody may call you on the phone and you are getting ready to go to dinner, you could say, “I can't talk right now, I'm on my way out the door,” means I'm just getting ready to leave.

Well, before I leave—before I'm going out the door—I “grab my Thermos. I lock the door,” to my house, “and then I hurry to my car in the garage.” The “garage” (garage) is the place where you keep your car.

“I'm usually running late and today is no exception!” When you are running late, you are behind your schedule; you're behind time that you want to be somewhere. “To run late” means the same as to be late or to be tardy (tardy). Usually that word, “tardy,” is only used in school. We say a student is tardy, we mean that they are late for school or late for class. To be running late means that you are not on the schedule that you want to be on—that you did not leave at the time you wanted to leave.

I say “I'm running late and today is no exception!” That expression, “is no exception” (exception) means that today is the same as every other day—it is not different. An exception is when something is different. Well, today is no different, that means today is no exception—it is not different.

Now let's listen to the story, this time at a normal speed.

[Start of story]

I go back into my bedroom and open up my closet door. I have about 30 dress shirts, 10 pairs of pants, a half-dozen ties, and some sweaters, suit jackets, and t-shirts. I pull out a clean pair of socks and underwear, then decide which shirt I’m going to wear today. I’m terrible at color coordinating, so I usually bring my wife in at this point to help match my shirt and pants. I put on my belt with the silver buckle and polish my shoes. I put my cell phone and car keys in my front pocket, and my wallet in the back one.
I put on my glasses and check myself in the mirror to make sure I look okay, and then go into the home office to get my bag. I used to carry a more traditional briefcase, but now I just use my computer bag to hold my laptop and my papers. Now it’s back into the kitchen to grab my Thermos on the way out the door. I lock the door and then hurry to my car in the garage. I’m usually running late and today is no exception!

[End of story]

Her scripts are always great, and this one is no exception. I speak of our wonderful scriptwriter, Dr. Lucy Tse.

From Los Angeles, California, I’m Jeff McQuillan, thank you for listening. Come back and listen to us again right here on ESL Podcast.

Glossary
closet – a very small room or a piece of furniture for storing clothes and shoes

* Kevin needs to stop buying so many clothes. He can’t even close his closet doors!

dress shirt – a man’s shirt worn for office work, with a collar, buttons, and long sleeves

* Do you think it’s okay for a man to wear a pink dress shirt to work?

pants – clothing worn over the legs

* Jennifer couldn’t decide whether she wanted to wear pants or a skirt, so she chose a dress instead.

tie – a long, narrow piece of fabric worn around a man’s neck

* He doesn’t like wearing ties because he says they make it hard for him to breathe.

sweater – a heavy, knitted shirt made of cotton or wool yarn (material that looks like a thick string)

* It’s very cold outside, so you and your sister should put on your sweaters if you want to play at the park.

suit jacket – a piece of formal clothing worn over a shirt, with long sleeves and buttons on the front, usually worn in formal business settings

* The sleeves of his suit jacket are too short. He needs to buy a new one for his interview.

t-shirt – a comfortable, casual, short-sleeved cotton shirt with no collar, often with a design or picture on the front

* You don’t have to dress up to come to my party. I plan to just wear a t-shirt and jeans.

socks – clothing worn on one’s feet

* In the winter, I wear socks and shoes, but in the summer, I prefer to wear sandals without socks.

underwear – clothing worn next to the skin and under other clothing

* We have to do laundry today because I don’t have any clean underwear!

to color coordinate – to identify things that look good together because they have the same or colors that look good together

* Her bedroom walls, floors, pictures, and toys are all color coordinated. I have never seen so much green in one room!

buckle – a piece of metal used to connect two ends of a belt, shoe, or bag

* American cowboys often wore large belt buckles with images of their daily life.

to polish – to rub something to make it shine

* Before going to the wedding, I need to polish my black shoes so they’ll look nice with my suit.

wallet – a piece of leather or heavy fabric with many pockets that is used to store money and credit cards

* He needed to clean out his wallet because it was too full of business cards and receipts to fit in his pocket.

to check (oneself) – to look at oneself, searching for something that looks wrong or is out of place

* I wish I had checked myself in the mirror before the big meeting because I had food between my teeth.

briefcase – a flat bag with a handle to carry documents, usually used by office workers to carry papers between their home and the office

* She forgot her briefcase at home and had to ask her husband to bring it to her at the office so she’d have her notes for the presentation.

garage – a room in a house for parking cars

* They have so many things in their garage that they almost don’t have room to park their car!

to run late – to be delayed; to be behind schedule; to be in a hurry because one needs to be somewhere very soon

* I didn’t have time to say goodbye to everyone at the lunch meeting because I was running late for my flight back to New York.

today is no exception – today is the same; today is not different

* I usually receive a lot of emails and today is no exception. This morning I had 238 messages in my inbox!

Culture Note
Reducing Access to Sugary Beverages Among Young People

“Sugar-sweetened beverages” (drinks made sweeter with sugar) are the largest source of added sugars in the “diet” (what people eat and drink each day) of U.S. “youth” (children and teenagers). Drinking these beverages increases the “intake” (putting into the body) of “calories” (units of energy for the body), which “contributes to” (adds to) “obesity” (being very fat or overweight) among youth across the country.

In the United States, childhood obesity has more than “tripled” (multiplied by three; x 3) in the past 30 years. In recent “decades” (periods of 10 years), drinking of sugar-sweetened beverages among children and teenagers has also increased. A national 2010 “survey” (questionnaire; piece of research) showed that although water, milk, and 100% fruit juice were the beverages most commonly “consumed” (drunken) during the seven days before the survey, daily drinking of regular soda, sports drinks, and other sugar-sweetened drinks were also very common.

Parents should help children and teenagers to make healthy beverage choices by making available or only buying certain drinks at the store. By doing this, parents can encourage their children to drink water and low-fat or fat-free milk, and/or limited amounts of 100% fruit juices.

Since young people spend a “significant portion” (large part) of each “weekday” (Monday through Friday) in school, making sure that healthy beverage choices are available—and that less “nutritious” (good for the body) ones are not—is “critical” (very important). “Implementing” (establishing) school “policies” (rules) that “restrict” (limit) access to sugar-sweetened beverages is an especially important for reducing childhood obesity and improving students' nutritional health.

'''