-
- 听力推荐 : VOA慢速英语
- 阅读推荐: 美国原版大学教材 : 经济学, 数学, 心理学, 社会心理学, 政治学, 社科等
-
-
- [[像高手一样学语法 - 牛童]]
- [[English 学习方法论]]
-
-
-
- [[常用的说法, 句式, 套子]]
- ---
- [[eng grammar]]
-
-
-
-
- ---
- VOA 慢速英语
	- https://learningenglish.voanews.com/z/955?withmediaplayer=1
	- [[001 Scientists Raise(v.) Questions about Future Vaccine Strategy]]
	- [[002 First Woman Is Reported Cured of HIV]]
	- [[003 Omicron Increases Worries about ‘Long COVID’]]
	- [[004 US Researchers Announce Another Pig to Human Transplant]]
	- [[005 Experts: More Variants after Omicron Likely]]
	- [[006 Study Finds New Evidence Linking Virus to Multiple Sclerosis]]
	- [[007 How Will the Pandemic End?]]
	- [[008 Testing Best Way to Know Difference Between Cold, Flu or COVID]]
	- [[009 Final Thoughts from a Garden Expert]]
	- [[010 Study Cannot Confirm Many Lab Results for Cancer Experiments]]
	- [[011 Study Suggests Link Between Long Sleep Times, Cognitive Loss]]
	-
-
-
- ---
- [[lesson to this 01]]
- [[lesson to this 02]]
- [[lesson to this 03]]
- ---
- 考研英语一. 阅读真题
- [[M.D 2008]]
-