= 0582
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 582: A Parent-Teacher Conference.
This is English as a Second Language Podcast number 582. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at eslpod.com. Download a Learning Guide for this episode that contains more information to help you improve your English even faster.
This episode is called “A Parent-Teacher Conference.” It’s a dialogue between Ms. Vasquez and Mr. Polo. One is a teacher, one is a parent; they’re talking about the parent’s son and are going to be using a lot of vocabulary that you would hear if a parent were talking to a teacher about how his or her daughter or son was doing in school. Let’s get started.
[start of dialogue]
Ms. Vasquez: Hello, Mr. Polo. I’m Ms. Vasquez. Please have a seat.
Mr. Polo: Thank you.
Ms. Vasquez: In this parent-teacher conference, I want to go beyond Marco’s report cards and his standardized test scores to talk about his general performance in the classroom.
Mr. Polo: That’s great. I want to know how he’s doing.
Ms. Vasquez: Marco is a good student. He’s attentive in class, a hard worker, and hands in his homework on time. Here’s his portfolio, if you want to take a look at his classroom work.
Mr. Polo: This is great. Are there any areas he needs to work on?
Ms. Vasquez: Marco is a good student, but he does sometimes misbehave. He often has disagreements with other students and loses his temper. I think he needs to work on his social skills.
Mr. Polo: Well, I don’t think that’s the most important thing, do you? His academics are the most important and he seems to be doing well in his subjects.
Ms. Vasquez: It’s true that academics are important, but learning to work cooperatively with other people is important, too, if he wants to get ahead in life, don’t you think?
Mr. Polo: I’ll have a talk with him. I’m sure you’ll see an improvement.
Ms. Vasquez: I appreciate you taking this seriously. Again, Marco is a good student and it’s a pleasure to have him in my class.
Mr. Polo: I’m glad to hear that. Good-bye.
Ms. Vasquez: Have a good afternoon.
[end of dialogue]
Ms. Vasquez begins our dialogue; she’s the teacher. She says, “Hello, Mr. Polo. I’m Ms. Vasquez. Please have a seat.” Typically, teachers would probably call parents “Mr.” or “Mrs. (Something),” not their first name unless they knew each other already. Similarly, the parent would probably call the teacher “Mr. (Something)” or “Mrs. (Something)” or “Ms. (Something).” Mr. Polo says, “Thank you.” Ms. Vasquez asks him to “have a seat,” to sit down. She says, “In this parent-teacher conference, I want to go beyond Marco’s report cards and his standardized test scores and talk about his general performance in the classroom.” A “parent-teacher conference” usually is something that schools will do (I’m talking about kindergarten through 12th grade – through high school) about two or three times a year; some schools do it four times a year. This is one night when the teachers come to school, and the parents go and can talk to their student’s teacher. The idea is that the parent can get a better idea about how their son or daughter is doing by talking directly to the teacher. When I was teaching high school and junior high school we would have these parent-teacher conferences. I absolutely hated them because, of course, all the parents think that their sons and daughters are perfect, and that if they’re not learning something it’s because you aren’t doing a good job teaching rather than the kid playing video games five hours every night. But, we’ll get back to the dialogue.
Ms. Vasquez says, “I want to go beyond Marco’s report cards and his standardized test scores.” “To go beyond (something)” is a phrasal verb meaning to discuss or deal with something in addition to what is expected, to go further into something than expected. Normally, a teacher talks about a student’s report cards for example. A “report card” is a piece of paper – in the old days – where you show how the student is doing every “term,” every part of the school year. Sometimes two times a year, usually four times a year, you give these report cards to the student. The student takes them home and shows the parents, that will tell the parent how the student is doing in the different classes that the son or daughter is taking. Hopefully, the child doesn’t change the report card somewhere between school and home! Nowadays, I suppose, it’s all done through the Internet or Twitter – I…I don’t know. “Standardized test scores” are the scores – the marks, if you will – that a student receives on a test, a national test typically, that all students at his or her grade level take. So these are tests that usually private companies develop, and they give them to thousands or tens of thousands students – perhaps millions of students – and it allows you to compare how much this student knows compared to the average student. Standardized test scores; these are very important especially now in American education.
Well, Ms. Vasquez wants to go beyond the report cards and the standardized test scores to talk about Marco’s general performance in the classroom. Mr. Polo says, “That’s great. I want to know how he’s doing.” Oh, really? Ms. Vasquez says, “Marco is a good student.” Probably lying! She says, “He’s attentive in class, a hard worker, and hands in his homework on time.” “To be attentive” means that you listen to what someone is saying, you pay attention to them. A “hard worker” is someone who tries very hard to do what is expected or required of them. “To hand in” is a two-word phrasal verb meaning to give usually a piece of paper or a document or a form to someone in authority, often for it to be evaluated. So we talk about how students turn in their homework. They give the piece of paper to their teacher. The teacher then looks at it, grades it (sees if it is correct or not), and then gives it back to the student. So, Ms. Vasquez is saying that Marco is attentive in class, a hard worker, and hands in his “homework,” the assignments he does outside of school – at home, or the library, or wherever. “Homework” is one word.
Ms. Vasquez says, “Here’s his portfolio, if you want to look at his classroom work.” Portfolios have been become popular in American schools in the last 20 years. What happens is the student hands in different assignments – different things that he or she is required to do, and the teacher keeps all of these together in one place to be able to show them to the parent to be able to evaluate the student at the end of the term – the end of the semester, the three or four months of school. That’s a portfolio. “Portfolio” has other meanings in English that are not found in this Learning Guide.
Mr. Polo, looking at this portfolio, says, “This is great. Are there any areas he needs to work on?” “To work on” is a two-word phrasal verb meaning to try to improve something, to become better at something. “To work” has a number of different phrasal verbs connected to it; take a look at the Learning Guide, where you will find those meanings.
Ms. Vasquez says, “Marco is a good student, but he does sometimes misbehave.” “To misbehave” means to act inappropriately, to not do what you are told or expected to do. It’s a word we use especially with children, whether they’re at home or at school. So Ms. Vasquez now is starting to tell the truth. She says Marco “often has disagreements with other students and loses his temper.” “To lose your temper” (temper) means become very, very angry with someone; maybe you start hitting them or fighting with them even. But, Ms. Vasquez doesn’t want to say that, she puts it very politely – very nicely, says that he loses his temper. “I think he needs to work on his social skills.” “Social skills” refers to the ability to be able to have conversations with other people, to be positive, to make friends; those would be good social skills to have.
Mr. Polo says, “Well, I don’t think that’s the most important thing, do you?” It’s not the most important thing for his son. Of course, Mr. Polo doesn’t have to be the teacher and have this misbehaving student in his classroom. Mr. Polo says that Marco’s academics are the most important – the most important thing – and he seems to be doing well in his subjects. “Academics” refers to traditional areas in school – traditional classes: reading, writing, math, history, science, podcasting. Mr. Polo says that Marco seems to be doing well in his “subjects,” in the classes that he is taking. “Subject” has a couple of different meanings however, and those are in the Learning Guide.
Ms. Vasquez says, “It’s true that academics are important, but learning to work cooperatively with other people is important, too, if he wants to get ahead in life, don’t you think?” “Cooperatively” means that you are able to do things with other people without getting angry. You’re able to do them in such a way as that it is a positive experience and result. American schools, again in the last 25-30 years, have used cooperative learning groups to get children – students – to learn how to work together; it’s a very popular approach. Ms. Vasquez says that Marco needs to work cooperatively with other people if he wants to get ahead in life. The phrasal verb “to get ahead” means to be successful, especially more successful than other people.
Mr. Polo says, “I’ll have a talk with him (meaning I will talk to him about this in a serious way). I’m sure you’ll see an improvement.” An “improvement” is things getting better. Ms. Vasquez says, “I appreciate you taking this seriously. Again, Marco is a good student and it’s a pleasure to have him in class.” “It’s a pleasure” means it’s nice to have him in class. She’s lying, of course! Mr. Polo says, “I’m glad to hear that. Good-bye.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Ms. Vasquez: Hello, Mr. Polo. I’m Ms. Vasquez. Please have a seat.
Mr. Polo: Thank you.
Ms. Vasquez: In this parent-teacher conference, I want to go beyond Marco’s report cards and his standardized test scores to talk about his general performance in the classroom.
Mr. Polo: That’s great. I want to know how he’s doing.
Ms. Vasquez: Marco is a good student. He’s attentive in class, a hard worker, and hands in his homework on time. Here’s his portfolio, if you want to take a look at his classroom work.
Mr. Polo: This is great. Are there any areas he needs to work on?
Ms. Vasquez: Marco is a good student, but he does sometimes misbehave. He often has disagreements with other students and loses his temper. I think he needs to work on his social skills.
Mr. Polo: Well, I don’t think that’s the most important thing, do you? His academics are the most important and he seems to be doing well in his subjects.
Ms. Vasquez: It’s true that academics are important, but learning to work cooperatively with other people is important, too, if he wants to get ahead in life, don’t you think?
Mr. Polo: I’ll have a talk with him. I’m sure you’ll see an improvement.
Ms. Vasquez: I appreciate you taking this seriously. Again, Marco is a good student and it’s a pleasure to have him in my class.
Mr. Polo: I’m glad to hear that. Good-bye.
Ms. Vasquez: Have a good afternoon.
[end of dialogue]
The scriptwriter for this episode is definitely a hard worker, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
parent-teacher conference – a special meeting between a student’s parents and teacher when they discuss how well (or poorly) the student is doing in school
* At the parent-teacher conference, they found out that their daughter hadn’t been doing her homework for the past two weeks.
to go beyond (something) – to discuss or deal with something else in addition to what is expected; to go further into something
* At this company, we go beyond our customer’s expectations and try to give them the best service possible.
report card – a piece of paper given to each student every quarter or every term showing his or her grades in all classes
* Miyuki’s report card had three As, two Bs, and one C.
standardized test scores – the number of points received on tests that are given to all students at the same grade level, used to compare their performance
* Do universities consider students’ standardized test scores from tests taken in elementary school?
attentive – paying attention; listening to and caring about what another person says
* Daniel wishes his wife were more attentive. He feels like she doesn’t even hear what he’s saying most of the time.
hard worker – a person who tries very hard to do what is expected or required; a person who is dedicated and committed to doing his or her work well
* Pauline isn’t our brightest employee, but she is a very hard worker and always does her job well.
to hand in – to submit; to turn in; to give a document or form to someone with authority, usually so that it can be graded or evaluated
* Don’t forget to hand in your essays by the end of the day.
homework – assignments that should be completed at home after school and given to the teacher by a certain time and date
* Even the kindergarten teacher gives her students homework, asking them to practice writing letters and numbers.
portfolio – a collection of the work that one has done during a particular period of time, especially for artists, models, and students
* This artist’s portfolio contains some beautiful watercolor paintings.
to work on – to try to improve something; to try to become better at something or do something better
* Janice is going to France this summer to work on her French.
to misbehave – to behave inappropriately; to do things that are against the rules; to act in unexpected and unacceptable ways
* The teacher becomes very frustrated when his students misbehave by talking and playing games during class.
to lose (one’s) temper – to become very angry and lose control of one’s actions and words
* When the employee came in late for the fifth day in a row, his boss lost her temper and shouted, “You’re fired!”
social skills – the ability to interact with other people in positive ways and make friends
* People who work in teams need to have strong social skills so that they can maintain good relationships with their co-workers.
academics – related to education at a school, especially to education in traditional areas like writing, reading, math, history, and science
* When James’ academics began to suffer, his parents told him to stop playing so many sports so that he would have more time to study
subject – one area of knowledge studied in school, such as English, math, history, science, a foreign language, music, and more
* Biology used to be my favorite subject in school, but now I prefer chemistry.
cooperatively – collaboratively; doing things together with other people, offering to help them get something done
* If those two companies could find a way to work together cooperatively, they’d both be more profitable.
to get ahead – to be successful, especially to be more successful than other people
* Ash is studying several computer programming languages to get ahead in his job.
improvement – something that has become better
* We’ve seen a great improvement in our sales figures over the past year, with revenue increasing by more than 250 percent.
Comprehension Questions
1. According to Ms. Vasquez, what does Marco need to work on?
a) His listening skills.
b) His study skills.
c) His interpersonal skills.
2. What does Mr. Polo agree to do?
a) He’ll punish Marco.
b) He’ll put Marco in extra classes.
c) He’ll talk to his son about working with others.
Answers at bottom.
What Else Does It Mean?
to work on
The phrase “to work on,” in this podcast, means to try to improve something, or to try to become better at something: “My coach said I should work on increasing the strength in my upper arms.” The phrase “to work out” means to do exercise: “Last night I worked out in the gym for more than two hours, so today I’m really sore.” The phrase “to work (something) out” can mean to reach an agreement with another person or to find a solution: “Let’s talk about what’s happening and see if we can work out a solution.” The phrase “to work under (someone)” means to work for someone, or to have someone as one’s supervisor: “It must be so hard to work under someone as demanding as your boss is! How do you do it?”
subject
In this podcast, the word “subject” means one area of knowledge studied in school, such as English, math, history, science, a foreign language, or music: “All students have to take the same core subjects like English and math, but then they can decide which other classes they want to take each quarter.” The word “subject” also means something that is being discussed or covered: “This controversial law has been the subject of much discussion.” The phrase “to change the subject” means to change topics or to begin talking about something else: “This is so boring! Let’s change the subject.” The phrase “a touchy subject” is something that one doesn’t want to talk about because it is very personal or directly affects oneself: “Her weight is a very touchy subject.”
Culture Note
A parent-teacher conference is a great opportunity for parents to have a “one-on-one” (personal; individual) discussion with their child’s teacher when he or she is focused only on that student’s performance, instead of on all the children in the classroom. Parents can “get more out of” (benefit more from) a parent-teacher conference by “making a list” (writing things down) of all the things they want to ask the teacher about before the meeting begins. They can also ask their child if he or she wants them to discuss anything “in particular” (specifically) with the teacher.
Teachers say that some parents become very “defensive” (defending oneself; not able to accept criticism or negative comments) when they hear what the teacher has to say. It is important to remember that the teacher “has the student’s best interests at heart” (wants to do what is best for the student). If parents can listen “with an open mind” (willing to hear what is being said, without making judgments) and allow the teacher to give for his or her opinion, then parents can get a more complete and “accurate” (close to the truth) picture of how their child is doing in school.
Teachers suggest that parents “jot down” (write down quickly or informally) notes about what was discussed, so that they don’t forget anything later. Instead of waiting, it is better if parents can talk with their child and tell him or her what was discussed in the meeting. If the teacher identified things that need to be worked on, the parents and child can create a plan for improvement and “follow up” (have another meeting or discussion) with the teacher in a few weeks or months.
Comprehension Answers
1 - c
2 - c