= 0591
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 591: Handling a Traffic Stop.
This is English as a Second Language Podcast episode 591. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Consider becoming a member of ESL Podcast to help support us, or you can make a donation by going to our website. This episode is called “Handling (or taking care of) a Traffic Stop,” when the police stop you in your car because you’ve done something wrong. Let’s get started.
[start of story]
I was having a great day until I saw the police car behind me with its loud siren and lights flashing. I pulled off the road and waited for the officer to approach my car.
Officer: May I see your driver’s license, proof of insurance, and car registration, please?
Lindsay: Let me get them out of my glove compartment. Here they are. What did I do wrong, officer?
Officer: Didn’t you see that stop sign back there?
Lindsay: Stop sign? What stop sign? I didn’t see any stop sign.
Officer: Sit tight and I’ll be right back.
…
I guess he was running my driver’s license and license plate numbers to make sure there are no outstanding warrants for me or for my car. He came back after a few minutes.
…
Officer: You ran a stop sign back there and I’m going to have to give you a citation.
Lindsay: Is that really necessary, officer? I’m really sorry I ran the stop sign and I’ll be more careful next time.
Officer: I suppose I could let you off with a warning, just this once.
Lindsay: Oh, thank you so much!
Officer: Drive more carefully in the future.
Lindsay: I will. I definitely will.
…
Phew! That was close. Good thing I tossed the incriminating evidence out the window before I pulled off the road!
[end of story]
Our story begins with Lindsay saying, “I was having a great day until I saw the police car behind me with its loud siren and lights flashing.” A “siren” (siren) is that part of the police car or ambulance or fire truck that makes a very loud noise so that other drivers will move their cars out of the way so they can go faster. A siren would typically go in the U.S. something like “woo-woo-woo-woo-woo.” That’s terrible, I know! I’ll give you a better siren [sound of a siren]. Phew, I thought they were going to stop me! Back to our story: Poor Lindsay heard the loud siren, and then she saw the lights flashing on the police car. “To flash” here means for a light to go on and off, on and off, on and off. “Flash” has many meanings, however, in English, and those can be found in that good old Learning Guide.
So Lindsay saw the police car, and obviously the police car wanted her to stop. She pulled off the road and waited for the officer to approach her car. This is, in fact, what you are supposed to do. If you are driving in the U.S. and let’s say you’re going too fast or you didn’t stop at the stop sign and there is a police officer who “pulls you over,” meaning who makes you take your car and park it on the side of the road, you should wait in your car, don’t get out of your car to go talk to the police officer. They don’t like that!
Lindsay pulled off the road – she drove her car to the side and stopped. The officer came up to her window and said, as they probably will typically, “May I see your driver’s license, proof of insurance, and car registration, please?” These are three things that everyone is required to have in most states: a driver’s license, you have to have permission to drive in the U.S., or an international license; proof of insurance, you have to prove that the automobile has car insurance. Now if you rent an automobile, typically that proof will be found in the small box in the front right of the car called the “glove compartment.” Your car registration is information that verifies your car was officially registered and you paid the tax for it with the state government where you are. So, driver’s license; proof of insurance, which is usually a little card from the insurance company with your name and the insurance policy – the agreement you have with the insurance company, that number; and your car registration, which is also a small little card.
Lindsay says, “Let me get them out of my glove compartment.” We just explained what that was. Why is called a glove compartment? Well, presumably that’s where people used to put their gloves when they used gloves to drive. But I don’t think anyone uses them for gloves anymore, unless you live in a very cold part of the country – which happily I don’t! So Lindsay says, “Here they are.” This is an expression we would use if you are going to give a set of something to another person – “here they are.” If it’s just one thing, you would say, “here it is,” but she has three things so she says, “Here they are.” Then she asks, “What did I do wrong, officer?”
The officer said, “Didn’t you see that stop sign back there?” A “stop sign” in the U.S. is a red, eight-sided, or octagonal, sign that says “stop,” and it means you have to stop your car completely before going forward. Well, unfortunately Lindsay didn’t see the stop sign; she says, “Stop sign? What stop sign? I didn’t see any stop sign.” The officer says, “Sit tight and I’ll be right back.” If someone tells you to “sit tight” (tight) they mean wait, usually sitting down somewhere, for a period of time and don’t go anywhere. “Sit tight” means to wait and not leave. Well, the officer is telling Lindsay to sit tight, to stay in her car, and not leave. Again, this is very typical.
What the police officer will do now is explained by Lindsay. She says, “I guess he was running my driver’s license and license plate numbers to make sure there are no outstanding warrants for me or for my car.” “To run” here means to check; he’s probably going to his computer in his car, or perhaps some other means of communicating with the headquarters (the main office of the police) so he can check to see that the driver’s license is valid – it’s a good driver’s license. He’s also checking the license plate numbers. Those are the large letters and numbers on a rectangular piece of metal either in the front of the car, in the back the car, or both in the front and the back. They are used to identify the car in the state’s registration system. So, they want to make sure the car is not stolen, so they make sure it hasn’t been reported stolen by running the license plate numbers. She says that the police want to make sure there are no outstanding warrants. A “warrant” is usually a document that allows the police to arrest someone but it hasn’t yet been used, probably because the person cannot be found. “Outstanding” here means something that hasn’t been done yet. In this case, an “outstanding warrant” would be something that the police have not yet used because they couldn’t find the person. The police catch lots of people who are doing something wrong with their car who have outstanding warrants, meaning they are criminals; they’ve done something wrong somewhere else.
The officer comes back and says, “You ran a stop sign back there and I’m going to have to give you a citation.” “To run a stop sign (or a stop light)” means not to stop your car when you are legally required to do so. So if the light is red and you just keep driving through the intersection – through the place where the two streets cross, you could get a citation. Another word for a citation is a ticket. “Citation” is the more legal name. It’s a piece of paper from the police saying that you have broken the law and you have to pay a certain amount of money, what we would call a “fine,” or you have to go to the judge – to the court.
Lindsay says, “Is that really necessary, officer? I’m really sorry I ran the stop sign and I’ll be more careful next time.” The police can not give you a ticket. I have never heard it happening, but it’s possible, at least it never happens here in Los Angeles. The officer says, “I suppose (I guess) I could let you off with a warning, just this once.” “To let (someone) off” is a phrasal verb meaning to forgive someone, to not give someone the punishment they deserve. A “warning” is a written or a spoken statement that says that what you did was wrong and you should not do it again. That’s really all a warning is. The officer says that he could let her off with a warning, meaning he could not give her a ticket and just tell her to be more careful next time. He says he’ll do it “just this once,” meaning this time only; this is an exception to the rule, we don’t normally do this – unless the woman is very attractive, right? And the police officer is typically a man. I’m not saying that happens frequently.
The officer says, “Drive more carefully in the future.” Lindsay says, “I will. I definitely will.” “Phew!” she says. “Phew” is a way of saying I’m relieved, I’m happy; something bad was going to happen to me but it didn’t. She says, “That was close (meaning I almost got a ticket). Good thing I tossed the incriminating evidence out the window before I pulled off the road!” “To toss” (toss) means to throw something, especially to throw something away, to get rid of it. “Evidence” is proof of something. “Incriminating evidence” is proof that you were doing something illegal. What Lindsay is saying is that she had something illegal in her car. Maybe it was a beer bottle that was open, which is illegal in most states if you are driving. Or maybe she had something else that she threw out the window and the police officer didn’t see it, and so she didn’t get in trouble for that probably more serious crime.
I’ve been pulled over for speeding once; it was about three or four years ago. And what happened was I went to a restaurant and I remembered that I had left the stove in the kitchen on – the fire was burning on the top of the stove. So I drove very fast back home from the restaurant where I was, and of course I was driving too fast, and the police officers saw me and pulled me over. I, of course, explained the reason but he didn’t care; he still gave me the ticket – the fine, which was something around 250 dollars, something like that. It was a lot of money. Sometimes it doesn’t matter if you have a good reason for driving fast, you’re still going to get a citation!
Now let’s listen to the dialogue, this time at a normal speed.
[start of story]
I was having a great day until I saw the police car behind me with its loud siren and lights flashing. I pulled off the road and waited for the officer to approach my car.
Officer: May I see your driver’s license, proof of insurance, and car registration, please?
Lindsay: Let me get them out of my glove compartment. Here they are. What did I do wrong, officer?
Officer: Didn’t you see that stop sign back there?
Lindsay: Stop sign? What stop sign? I didn’t see any stop sign.
Officer: Sit tight and I’ll be right back.
…
I guess he was running my driver’s license and license plate numbers to make sure there are no outstanding warrants for me or for my car. He came back after a few minutes.
…
Officer: You ran a stop sign back there and I’m going to have to give you a citation.
Lindsay: Is that really necessary, officer? I’m really sorry I ran the stop sign and I’ll be more careful next time.
Officer: I suppose I could let you off with a warning, just this once.
Lindsay: Oh, thank you so much!
Officer: Drive more carefully in the future.
Lindsay: I will. I definitely will.
…
Phew! That was close. Good thing I tossed the incriminating evidence out the window before I pulled off the road!
[end of story]
The scriptwriter for this episode would never run a stop sign. That’s because it’s Dr. Lucy Tse!
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
siren – the part of a police car, ambulance, or fire truck that makes a very loud noise to let drivers know that they should move aside and allow it to go through
* When I hear a siren, I know I should slow down or stop my car until the police car has passed me.
to flash – for a light to turn on and off, on and off
* Do you think the Christmas tree lights would look better if they were always on, or if they were flashing?
to pull off the road – to drive one’s car to the side of the road and stop, usually because one is having mechanical problems or at a police officer’s request
* When we saw smoke coming out of the car, we pulled off the road and opened the hood of the car.
driver’s license – a small, flat, rectangular piece of paper or plastic that shows one has permission to drive a vehicle
* In most states, you can get your driver’s license when you are 16 years old.
proof of insurance – a document showing that one has purchased automobile insurance as required by law
* Our proof of insurance expires at the end of the month, but the insurance company will send us a new one as soon as we make another payment.
car registration – a document showing that one has registered one’s car with the state’s department of motor vehicles
* How much do we have to pay for car registration each time we buy a new car?
glove compartment – the box that opens in the front of the car, next to the passenger’s knees, where one can keep important documents, maps, and more
* Lauren keeps paper towels in the glove compartment, just in case something spills in the car.
stop sign – a red, octagonal (eight-sided), metal sign placed on the right-hand side of the road at intersections, letting drivers know they should stop their car
* If two cars stop at a stop sign at the same time, the car on the right goes first.
to sit tight – to wait somewhere, usually seated, for a period of time without moving or going anywhere else
* Students, I have to make some extra copies of the test. Please sit tight and wait quietly until I come back.
license plate number – the large letters and numbers on a rectangular piece of metal at the front and back of a car, used to identify a car in the state’s registration system
* Justine bought a customized license plate number: “1DERFUL,” meaning “wonderful.”
outstanding warrant – a document that allows police to arrest someone, but that hasn’t yet been used, probably because the person has not been found by the police
* There’s an outstanding warrant for Eve’s arrest. Apparently, she has more than 50 unpaid parking tickets!
to run (a stoplight or stop sign) – to not stop one’s car when one is legally required to do so
* Yoshio wasn’t paying attention and ran a stoplight, almost hitting a car that was coming the other way.
citation – a ticket; a piece of paper from the police, showing that one has broken the law and should pay a fine (money) and/or go to court
* Elizabeth got a citation for driving without wearing her seatbelt.
to let (someone) off – to forgive someone, not giving him or her the punishment that he or she should have received
* When Karen came home really late last weekend, her parents let her off, but if it happens again they’re going to take away her car.
warning – a written or verbal statement that something bad or dangerous may happen, intended to prevent that thing from happening in the future
* At the beach, you can see many signs with warnings about dangerously high waves.
to toss – to throw something, especially to throw something away
* Marlys tossed the peanut shells as she walked and ate, leaving a trail of shells behind her.
incriminating evidence – proof that one has done something wrong or illegal
* The lawyer held up a bloody knife as incriminating evidence against the murderer.
Comprehension Questions
1. Which of these would you be able to hear?
a) A loud siren.
b) Lights flashing.
c) A stop sign.
2. What does the officer mean when he says, “I’m going to have to give you a citation”?
a) He’s going to take away Lindsay’s driver’s license.
b) He’s going to give her a ticket.
c) He’s going to write down her license plate numbers.
Answers at bottom.
What Else Does It Mean?
to flash
The verb “to flash,” in this podcast, means for a light to turn on and off, on and off: “The dance club is filled with many brightly colored, flashing lights.” The verb “to flash” also means for a bright light to shine for a short period of time: “Did you see the lightening flash in the sky a minute ago?” When a thought or idea “flashes,” it comes into one’s mind very suddenly and unexpectedly: “Childhood memories often flash through her mind, surprising her with their clarity.” “To flash (something)” means to show something to someone very quickly: “Charles flashed his bus pass at the driver as he boarded the bus.” Finally, the phrase “to flash forward” means for a movie or book to show quickly what will happen in the future: “The movie was confusing because it had too many flash forwards.”
to run
In this podcast, the phrase “to run (a stoplight or stop sign)” means to not stop one’s car when one is legally required to do so: “That driver ran a stop sign and almost hit the pedestrian who was crossing the road!” In politics, the verb “to run” means to try to be elected for a particular job: “Have you ever considered running for mayor?” The phrase “to run a bath” means to fill a bathtub with water: “Ingrid likes to relax by running a hot bath.” The phrase “to run (one’s) course” means for something to continue as expected until it has ended, usually without interference: “David hates taking medicine. He prefers to let a cold run its course.” Finally, the phrase “to run for cover” means to run to a safe place, especially if one is being shot at: “When the city was bombed, everyone ran for cover.” Or, “It started to rain and we ran for cover.”
Culture Note
The easiest way to “avoid” (not let something happen) getting a “traffic” (related to driving) ticket for “speeding” (going faster than the allowed “speed limit” (maximum speed)) is to not speed. However, many drivers want to drive faster than the speed limit, and there are certain things they can do to make a traffic ticket less likely.
First, drivers can try to stay within 5-10 “mph” (miles per hour) of other cars on the same road. Even if all the cars are speeding, the “cops” (police officers) probably won’t “issue” (give out) speeding tickets until they find a car that is moving much more quickly than the other cars. It’s also a good idea to stay “in the midst of” (surrounded by) those other cars, not “leading” (being in front of) the “pack” (group of cars), since a police officer might be more likely to pull over the first car in a group of speeding cars.
Fast drivers can also reduce the “chance” (likelihood; probability) of receiving a speeding ticket by driving in the middle or right-hand lanes, and not the left-hand lane, which is for the fastest cars. Certain types of cars are also more likely to get tickets. For example, bright red or yellow “sports cars” (small cars designed to go very fast) are more likely to get tickets than “ordinary” (normal; regular) family cars, since they “attract” (get) the police officers’ attention.
Some drivers buy a “radar detector,” or a special piece of electronic equipment placed inside a car that can “alert” (send a message to) the driver when a police car is nearby and is using radar to detect drivers’ speed. Radar detectors aren’t legal in all states, but where they are legal, drivers often speed and then slow down when their radar detector alerts them of the police’s “presence” (being in an area).
Comprehension Answers
1 - a
2 - b