= 0598
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 598: Suggesting a Nightcap.
This is English as a Second Language Podcast episode 598. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to become a member of ESL Podcast and get all of our Learning Guides that will help you improve your English even faster.
This episode is called “Suggesting a Nightcap.” A “nightcap” is an alcoholic drink, such as beer, that you would drink right before you go to bed. Let’s get started.
[start of dialogue]
Brittany: [slurring her speech] I had a really nice time.
Tri: I’m glad to hear it. It was nice of Marie to set us up.
Brittany: Yeah, she told me that you would be my soul mate, and she was right! You’re dreamy…
Tri: Uh…well, thanks. It was really nice meeting you, but I’d better be going.
Brittany: What? Why are you leaving so soon? Don’t you want to come in for a nightcap? Let’s have a drink, or two, or three. I’ll make it worth your while…
Tri: I think we’ve both had enough to drink tonight, don’t you? I’ll just take a rain check.
Brittany: Don’t go yet. The night is young. Don’t you want to see my apartment?
Tri: Sure I do, but let’s make it another time. I really do have to go.
Brittany: Spoilsport!
…
Brittany seemed nice when I first met her, but that impression didn’t last long. It only took 15 minutes for me to realize that she and I had nothing in common, and then, I couldn’t get out of there fast enough. You might think I’m crazy because she really was drop-dead gorgeous, but I had no intention of taking advantage of a drunk woman!
[end of dialogue]
The dialogue begins with Brittany slurring her speech. She’s saying something to Tri, but we can’t understand it very well because she is slurring her speech. “To slur” (slur) means to speak very slowly but not clearly. You don’t stop in between your words. It’s often something that happens if you are drunk – if you have had too much alcohol, or perhaps are taking some sort of medicine that may have that same effect.
Brittany, we believe, has been drinking a little too much alcohol; she says to Tri, “I had a really nice time.” Tri says, “I’m glad to hear it.” It appears that Tri and Brittany were on a date. He says, “It was nice of Marie to set us up.” “To set (someone) up” here means to make arrangements – to make a plan for two people to meet. Usually this involves a man and a woman who are perhaps going to be romantically interested in each other. So you have a friend, who has another friend who is single – who is not married, and you want to date that person, or that person may say, “You know, I know someone who would be really good for you,” and they set you up. They arrange for you to come together and go on a date.
Brittany says, “Yeah, she (Marie) told me that you would be my soul mate, and she was right! You’re dreamy.” A “soul (soul) mate (mate)” is a person that you have many things in common with, you feel very comfortable with this person, perhaps you are in love with this person. Usually it’s something you would say to someone who you are very much in love with, someone that you would want to marry; that might be your soul mate. Tri and Brittany, however, are on their first date. They’ve only known each other for a few hours. But because Brittany has been drinking she thinks that Tri is somehow her soul mate, even though she doesn’t know him very well. She says that Tri is dreamy. “Dreamy” often refers to a very attractive man, a very desirable man, someone who a woman would be very interested in. Usually, it’s when somebody isn’t thinking very clearly, but it’s possible that Brittany really believes Tri is dreamy.
Tri says, “Uh…well, thanks.” He’s not quite sure what to say back to Brittany since it’s only their first date. He says, “It was really nice meeting you, but I’d better be going,” meaning I need to leave now. Brittany says, “What? Why are you leaving so soon? Don’t you want to come in for a nightcap?” A “nightcap” (one word) is alcohol that you drink before going to bed; it would be like one last drink for the night. Remember, Brittany has been drinking. She’s inviting Tri to come to her apartment and have this drink. She says, “Let’s have a drink, or two, or three. I’ll make it worth your while.” “To make (something) worth (someone’s) while (while)” means to give someone something if they do something for you. So if someone says, “If you go and get me some milk at the store, I’ll make it worth your while.” I’ll give you 10 dollars or 20 dollars.
Brittany is saying that she will make it worth his while – Tri’s while – by coming in for a nightcap, remembering Brittany has been drinking. Tri says, “I think we’ve both had enough to drink tonight, don’t you?” Tri recognizes that Brittany has drunk too much alcohol; he’s trying to get away from the situation. He says, “I’ll just take a rain check.” A “rain (rain) check” (two words) is the ability to do something at a later time – at a later date, instead of right now when it is being offered to you. Usually this term is used in a store, where you go in to buy something that the store has on sale but the store doesn’t have any more, it’s sold out. Sometimes – I’m not sure how often this happens anymore, but it used to be that the store would give you a rain check. It would give you a piece of paper that you could bring back for example a week later or two weeks later and, when the store has more of that product you could still get the sale’s price. In this case, what Tri is saying is that he doesn’t want to have a nightcap with Brittany, maybe later – maybe at some other time. That’s why he says, “I’ll just take a rain check.”
Brittany says, “Don’t go yet. The night is young.” This is a common expression; “the night is young” means that it is still early, there are still plenty of things we can do before we have to go to bed. “The night is young” means there is a lot of time for us to still enjoy ourselves. Brittany says, “Don’t you want to see my apartment?” Tri says, “Sure I do, but let’s make it another time.” When someone says they “want to make (something) another time” they mean they want to do it later. It’s similar to “taking a rain check.” You want to do something at a later time, but you’re not going to set a particular or a specific day right now, just in the future.
Once again, Tri is trying to leave here. He says, “I really do have to go.” Brittany then says, “Spoilsport!” “Spoilsport” (spoilsport – one word) is someone who spoils another person’s fun. That is, someone who ruins or wrecks or somehow prevents another person from having fun. Someone who isn’t interested in doing fun things, especially someone who wants to do everything properly, that doesn’t want to break any of the rules, that’s what a spoilsport is. We have another expression, a “party pooper” (pooper). This is basically the same idea, someone who doesn’t want to go along with the rest of the group who wants to have fun.
Tri says, “Brittany seemed nice when I first met her, but that impression didn’t last long.” “Impression” is, here, the way that you think about someone, your opinion of someone. It has other meanings, this word “impression,” and those can be found in our Learning Guide. Tri continues by saying, “It only took 15 minutes for me to realize that she and I had nothing in common,” meaning they got together on their date, but after 15 minutes Tri knew that he wasn’t really going to like this woman. He didn’t have anything in common, they didn’t share any interests. Tri says, “then, I couldn’t get out of there fast enough.” “To not be able to get out of (somewhere) fast enough” means that you want to leave a place right away, very badly we might say. You want to go immediately. He says, “You might think I’m crazy because she really was drop-dead gorgeous.” “Drop-dead gorgeous” is someone, usually a woman, who is very beautiful, very sexually attractive. “Gorgeous” means beautiful. “Drop-dead” means that she’s so beautiful if you see her you would die. I don’t know why, but that’s the expression. Tri says, however, that he had no intention (he didn’t have any plan; he didn’t want to) of taking advantage of a drunk woman. “To take advantage of (someone)” is to do something to someone in a situation where they may not be able to help themselves, to treat someone unfairly. We might even say “to abuse a situation,” to take the situation and use it for your advantage, hurting someone else. That’s taken advantage of someone. Tri doesn’t want to take advantage of Brittany. She has been drinking, and so he decides that he will not have another drink with her or go to her apartment, but he will go home. Which is probably a good idea!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Brittany: [slurring her speech] I had a really nice time.
Tri: I’m glad to hear it. It was nice of Marie to set us up.
Brittany: Yeah, she told me that you would be my soul mate, and she was right! You’re dreamy…
Tri: Uh…well, thanks. It was really nice meeting you, but I’d better be going.
Brittany: What? Why are you leaving so soon? Don’t you want to come in for a nightcap? Let’s have a drink, or two, or three. I’ll make it worth your while…
Tri: I think we’ve both had enough to drink tonight, don’t you? I’ll just take a rain check.
Brittany: Don’t go yet. The night is young. Don’t you want to see my apartment?
Tri: Sure I do, but let’s make it another time. I really do have to go.
Brittany: Spoilsport!
…
Brittany seemed nice when I first met her, but that impression didn’t last long. It only took 15 minutes for me to realize that she and I had nothing in common, and then, I couldn’t get out of there fast enough. You might think I’m crazy because she really was drop-dead gorgeous, but I had no intention of taking advantage of a drunk woman!
[end of dialogue]
We hope we’ve made it worth your while to listen to this episode. Thanks to Dr. Lucy Tse for writing it.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
to slur – to speak slowly and unclearly, without pausing between one’s words, often because one is drunk or has taken too much medicine
* Whenever Randy takes sleeping pills, his speech becomes slurred for a while before he falls asleep.
to set (someone) up – to make arrangements for two people to meet, usually because one thinks they will like each other and be able to start a romantic relationship together
* I don’t know why Hugh set me up with Jackson. We have nothing in common.
soul mate – a person whom one has many things in common with, feels very comfortable with, is in love with, and is meant to be with in a romantic relationship for the rest of one’s life; one’s true love
* The day I met you, I knew I’d finally found my soul mate.
dreamy – very pleasant, desirable, or attractive, often used if the speaker isn’t thinking very clearly or is very idealistic
* Isn’t this dress dreamy? I have to have it!
nightcap – a drink with alcohol consumed right before going to bed
* If you can’t fall asleep without a nightcap, you may need to see your doctor.
to make (something) worth (one’s) while – to give someone something if he or she does something for oneself; to compensate a person for something that he or she is going to do for oneself
* She waved money in front of my face, saying that if I helped her study for the exam, she’d make it worth my while.
rain check – the ability to do something at a later date instead of right now, when it is being offered
* I’d love to see your new paintings, but right now I’m running late for a meeting. Can I take a rain check?
the night is young – a phrase meaning that it is still early in the evening and there is plenty of time to do things before people need to go home to sleep
* Why are you going home so early? The night is young! Let’s go out and have some fun!
to make (something) another time – to do something later; to do something on an unspecified day in the future, not now
* Callie had planned to go shopping with Ollie earlier today, but she said she had a headache and asked to make it another time.
spoilsport – a party pooper; someone who spoils another person’s fun; someone who isn’t interested in doing fun things with another person or group of people, often because he or she wants to follow the rules and do everything properly
* Earle is a spoilsport who never drinks, smokes, listens to loud music, dances, swears, or eats junk food.
impression – the way that one feels or thinks about someone or something; the opinion one has of someone or something
* Becca made a great impression when we interviewed her for the job, but her performance since then hasn’t been very good.
to not be able to get out of (somewhere) fast enough – to want to leave a place very badly and not spend any time there at all
* Our realtor took us to see a horrible, ugly, old house. We couldn’t get out of there fast enough!
drop-dead gorgeous – very beautiful, used to describe a woman
* Cherice is drop-dead gorgeous. I wonder why she didn’t try to become a model.
intention – plan; what one wants and plans to do
* Pierre’s intention was to study all night, but he ended up falling asleep at his desk around 11:00.
to take advantage of (someone or something) – to get what one wants or needs by treating someone unfairly or abusing a situation
* Why have you let Pinella live in your apartment for free for the past six months? I think she’s taking advantage of you.
Comprehension Questions
1. Why doesn’t Tri accept Brittany’s offer for a nightcap?
a) Because he doesn’t drink alcohol.
b) Because he doesn’t think she’s attractive.
c) Because he thinks she is too drunk.
2. What does Brittany mean when she says, “The night is young”?
a) It’s still early.
b) There is a full moon.
c) Tomorrow is her birthday.
Answers at bottom.
What Else Does It Mean?
to slur
The verb “to slur,” in this podcast, means to speak slowly and unclearly, without pausing between one’s words, often because one is drunk or has taken too much medicine: “Bartenders aren’t supposed to serve more alcohol to customers whose speech is slurred.” In music, “to slur” means to play notes together very smoothly, without breaks between them: “This part of the song would sound better if you slurred the notes of the melody.” As a noun, a “slur” is a negative comment against someone or something, often used to make other people dislike or hate that person or thing: “Terry made a horrible slur about poor people.” Finally, a “racist slur” is an unkind and unfair comment about someone’s race or skin color: “Irving was shocked when his parents made a racial slur about his best friend.”
impression
In this podcast, the word “impression” means the way that one feels or thinks about someone or something, or the opinion one has of someone or something: “I’ve never seen Lake Superior, but I have the impression that it’s a very beautiful place to visit.” The phrase “first impression” refers to the way one is perceived at one’s first meeting: “Our first impression of you was that you were really quiet and shy, but now we know that you just weren’t feeling well that day.” The phrase “to be under the impression” means to believe something that wasn’t actually true: “I’m sorry I called you Mrs. Thompson, but I was under the impression that you were married.” Finally, an “impression” is the mark made when something hard is pushed into something soft: “The folds in the pillowcase left an impression on her cheek.”
Culture Note
In this episode, a “nightcap” is an alcoholic drink drunken right before going to bed, usually to help one fall asleep. However, a “nightcap” is also a warm hat that used to be worn when people went to bed. Nightcaps were very common during the “Middle Ages” (the period of European history between the 5th and 15th centuries), but are rarely used “these days” (in modern times).
Nightcaps were used to keep people’s head warm at night, but they also “served another purpose” (had another reason for existing): they helped prevent the “spread” (expansion; growth; movement into new areas) of “lice” (small insects that live in people’s and animals’ hair and bite the skin, causing it to itch). In the Middle Ages, many people had little or no hair, instead choosing to wear “wigs” (artificial hair). These wigs often had a lot of lice. So, when people wore nightcaps to bed instead of wigs, they were able to keep the lice away from their skin and stay warmer during cold nights.
Women’s nightcaps were normally just a long piece of “fabric” (cloth) that they “wrapped” (put around something else several times; rolled) around their head. Men’s nightcaps were hats that had a very long, pointed part on top. The long part was wrapped around the neck for extra warmth.
Nightcaps are “out of fashion” (uncommon and not popular) now, but some people do still wear a hat to bed for warmth, especially if they are “bald” (without hair on one’s head) and are in a cold place, such as when sleeping “outdoors” (outside). However, they are unlikely to call these hats “nightcaps.”
Comprehension Answers
1 - c
2 - a