= 1108
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,108 – Foreign Currency Exchange Rates.
This is English as a Second Language Podcast episode 1,108. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast, or take a look at some of our ESL Podcast Courses which you can buy and download the very same day – nothing to wait for.
On this episode, we have a dialogue between Sydney and Isaac about exchanging money when you travel. Let’s get started.
[start of dialogue]
Sydney: Where should we go on our honeymoon? I thought Rome would be nice.
Isaac: Let me check. No, that wouldn’t be a good idea.
Sydney: Okay, how about Tokyo? I’ve always wanted to visit Japan.
Isaac: No, I’m afraid not.
Sydney: How are you making these determinations?
Isaac: I’m checking to see if the U.S. dollar has a favorable exchange rate with those currencies. We want our dollars to go as far as they can.
Sydney: You mean you want to pick our honeymoon destination according to the currency market.
Isaac: I’m just saying that we should take advantage of falling currencies or ones that have already depreciated significantly. A strong dollar means we can get more bang for the buck.
Sydney: So you’re saying that you want us to make plans at the whim of the Federal Reserve and central banks.
Isaac: Well, I wouldn’t go that far. I’m only saying that it would make financial sense.
Sydney: That doesn’t seem like a very romantic way of picking a honeymoon destination.
Isaac: Romance is overrated. Wouldn’t you rather be solvent than sentimental?
Sydney: I’d rather be solvent and sentimental.
[end of dialogue]
Sydney asks Isaac, “Where should we go on our honeymoon?” Your “honeymoon” (honeymoon) is the vacation you take after you get married. Usually, but not always, it’s immediately after the wedding. Sometimes people take their honeymoon later. The honeymoon is supposed to be, of course, a wonderful time for the married couple, and often the last wonderful time they have. I’m just kidding, of course. Marriage has happiness beyond the honeymoon. It often lasts another month or two.
Sydney suggests they go to Rome – Rome, Italy, of course. Isaac says, “Let me check” – let me investigate. “No,” he says, “that wouldn’t be a good idea.” Now, we’re not sure what Isaac is checking when he says, “Let me check.” We’re not sure what he’s investigating in order to say yes or no. Sydney then gives him another suggestion. She says, “Okay, how about Tokyo?” – Tokyo, Japan, of course. “I’ve always wanted to visit Japan,” she says. Isaac says, “No, I’m afraid not.” “I’m afraid not” is just another way of saying no. It’s a little more polite.
Sydney then says, “How are you making these determinations?” which is, of course, a very good question. A “determination” is a decision or an assessment – how you decide one way or another. Isaac says, “I’m checking to see if the U.S. dollar has a favorable exchange rate with those currencies.” So, Isaac is making this determination based upon the exchange rate. The “exchange rate” is basically the amount of money that you get when you, in effect, buy another country’s money, another country’s currency.
“Currency” (currency) refers to the system the money that is used in a particular country. In the United States, we use dollars. But if I’m going to go to Europe, I would in many countries need to exchange my dollars for euros. I would need, basically, to buy euros. A “favorable exchange rate” is when you can get a lot of money in the other country for the money in your country. So, a favorable exchange rate between say the U.S. dollar and the euro would mean that I could get a lot of euros for my dollar. And as we record this in 2015, that is true.
Isaac, then, is making his decision about where he and Sydney should go on their honeymoon by looking at the exchange rates. He says, “We want our dollars to go as far as they can,” meaning we want to get as much for our money as possible. Sydney is not very happy when she learns this. She says, “You mean you want to pick our honeymoon destination according to the currency market.”
Sydney is saying that Isaac wants to “pick” (pick), or select, the honeymoon location based on the currency market – the price of different currencies. A “market” is usually a word we use to describe the system or the mechanism for people to buy and sell things. So, the “currency market” would be buying and selling of currencies, of different kinds of money. Isaac says, “I’m just saying that we should take advantage of falling currencies or ones that have depreciated significantly.”
For a currency to “fall” means that it has become less expensive or less valuable. “Falling” here refers to decreasing – becoming smaller or lower. We could talk about the stock market falling. That would mean that the price of stocks was going down. Isaac thinks that they should select their honeymoon location based on the state of the currency in that country. He also mentions “depreciated currencies.” The verb “to depreciate” (depreciate) means to lessen in value or worth, to be worth less money – at least that’s what Isaac means here.
He says, “A strong dollar means we can get more bang for the buck.” A “strong dollar” would be a dollar that keeps its value, that is expensive relative to other currencies. The phrase “bang (bang) for the buck (buck)” refers to getting a lot for your money. “Buck” refers to money here, American money. We refer to one dollar as a “buck.” “To get a lot of bang for your buck” means to get a lot for your money, to get a very good value. Sydney says, “So, you’re saying that you want us to make plans at the whim of the Federal Reserve and central banks.”
The expression “at the whim (whim) of” means based on some rather unpredictable idea of another person or organization. We have a related expression, “on a whim,” which means to do something without thinking about it closely or carefully. So to be “at the whim of” someone means that your future – things that are important to you – depend on someone else’s decision, someone else who may not make a decision very rationally or might make a decision arbitrarily – without any good reason for it.
Sydney is saying that their plans depend on the decisions of the Federal Reserve and the central banks. The “Federal Reserve” is the national bank of the United States. A “central bank” of a country – or in the case of the European Union, of the E.U. – is the bank that helps determine and regulate the monetary system for that country or that area or region. The central bank typically decides how much money it’s going to print. Here in the U.S. that would mean how many dollars will be available in the economy.
Isaac disagrees with Sidney’s description of his approach to planning their honeymoon. He says. “Well, I wouldn’t go that far,” meaning that’s partially true, but not as much as you are saying. He says, “I’m only saying that it would make financial sense” – it would make economic sense for the two of them. Sydney, however, says, “That doesn’t seem like a very romantic way to pick a honeymoon destination.” Something that is “romantic” (romantic) is something related to feelings of love toward another person – an expression of that love.
Then Isaac says something very stupid, very foolish. He says, “Romance is overrated.” To say something is “overrated” (overrated) means that people think it’s more important than it really is, more significant than it actually is. You would never want to say that to your girlfriend, wife, or in this case, fiancé – the woman who is going to marry you. Isaac says, “Wouldn’t you rather be solvent than sentimental?”
“To be solvent” (solvent) means that you have enough money to pay for your expenses. You have enough money to live on. You have enough money to pay your bills. “Sentimental” (sentimental) refers to a person who is strongly influenced by feelings and perhaps is basing their decisions more on feelings than on reason, than on intellect. Isaac says, “Wouldn’t you rather be solvent than sentimental?”
He’s saying that there is this choice: either you can be solvent – either you can spend money wisely – or you can be sentimental; you can be guided by your feelings. Sydney doesn’t think you have to choose between these two options. She says, “I’d rather be solvent and sentimental,” which I think is true, of course. You can pay your bills and still follow your heart. Now that’s romantic.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Sydney: Where should we go on our honeymoon? I thought Rome would be nice.
Isaac: Let me check. No, that wouldn’t be a good idea.
Sydney: Okay, how about Tokyo? I’ve always wanted to visit Japan.
Isaac: No, I’m afraid not.
Sydney: How are you making these determinations?
Isaac: I’m checking to see if the U.S. dollar has a favorable exchange rate with those currencies. We want our dollars to go as far as they can.
Sydney: You mean you want to pick our honeymoon destination according to the currency market.
Isaac: I’m just saying that we should take advantage of falling currencies or ones that have already depreciated significantly. A strong dollar means we can get more bang for the buck.
Sydney: So you’re saying that you want us to make plans at the whim of the Federal Reserve and central banks.
Isaac: Well, I wouldn’t go that far. I’m only saying that it would make financial sense.
Sydney: That doesn’t seem like a very romantic way of picking a honeymoon destination.
Isaac: Romance is overrated. Wouldn’t you rather be solvent than sentimental?
Sydney: I’d rather be solvent and sentimental.
[end of dialogue]
There’s nothing overrated about our wonderful scripts written by our wonderful
scriptwriter. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
honeymoon – a vacation taken by a wife and husband immediately or very soon after their wedding, intended to develop their romantic relationship and celebrate their love for each other
* The day after the wedding, they’ll fly to the Bahamas for a one-week honeymoon.
determination – a decision; an assessment; an evaluation
* The determination of the U.S. government’s Internal Revenue Service is final, so there is no way to appeal its decisions.
favorable exchange rate – an indication that one’s own currency can buy a lot of the currency of another country at a lower prices than usual, making it cheaper for one to buy goods and services in that country
* The favorable exchange rate allowed them to dine in fine restaurants and go to the theater often while on a trip back to their home country.
currency – the system of money used in a particular country, such as dollars, pesos, francs, or yens
* How many countries use the euro as their currency?
currency market – the business exchange and the transactions of buying and selling one currency to exchange it for another currency with the aim of making money
* They’re saving their money in several different currencies to protect themselves from fluctuations in the currency market.
falling – decreasing; becoming smaller or lower
* The shareholders aren’t pleased with the company’s falling sales.
to depreciate – to lessen in value or worth; to be worth less money; for something’s value to decrease
* New cars depreciate quickly as soon as you drive them off the car sales lot.
strong – with a steady value or a value that decreases only very slowly, not dramatically decreasing over time
* The neighborhoods around the best schools usually have strong home prices.
bang for the buck – receiving a very good return on one’s expense or investment; getting a lot in exchange for spending one’s money
* We get more bang for the buck by buying a 20-pound bag of rice rather than 20 one-pound bags.
at the whim of – based on the arbitrary, odd, or unpredictable idea of another person or organization
* She flew to Philadelphia at the whim of her boyfriend, even though they had been dating for only a few weeks.
Federal Reserve – the central bank of the United States, which regulates the monetary system and has significant influence over finance and economics
* What factors does the Federal Reserve consider when setting interest rates?
central bank – a national bank of a country, responsible for printing money, implementing monetary policies, and providing banking services for the government
* If the central bank produces too much money, the country will experience inflation.
financial – related to money; related to the management of a large amount of money, especially for a company or government
* As a financial analyst, Cedric will be responsible for analyzing investment opportunities.
romantic – related to feelings of love toward another person and the expression of that love
* What’s so romantic about roses and a candlelight dinner?
overrated – said or believed to be bigger, better, more important, and more significant than something actually is
* That restaurant was really overrated. The food wasn’t nearly as good as everyone said.
solvent – able to cover one’s expenses and pay one’s debts; with cash or other assets that exceed (are greater than) one’s liabilities (bills)
* Sales are growing, but our company won’t be solvent for another year or two.
sentimental – a person who is strongly influenced by feelings and values those feelings over being practical
* Wynona is very sentimental, so she easily cries when she watches movies or listens to sad songs.
Comprehension Questions
1. What does Isaac mean when he says, “We can get more bang for the buck.”
a) They’ll be able to go hunting.
b) They’ll be able to buy fireworks.
c) They’ll be able to get more for their money.
2. Which of these would be a romantic way of picking a honeymoon destination?
a) Considering which one has the most beautiful sunsets.
b) Considering which one has the most stable political conditions.
c) Considering which one has the best prices for travel packages.
Answers at bottom.
What Else Does It Mean?
falling
The word “falling,” in this podcast, means decreasing, or becoming smaller or lower: “The availability of news and other content on the Internet has led to falling sales of newspapers and magazines.” The phrase “to have a falling-out with (someone)” means to have a bad or major argument with someone: “He had a falling out with his father three years ago, and they haven’t spoken since then.” The phrase “to fall flat on (one’s) face” means to not achieve the expected or desired result in an embarrassing way: “The comic fell flat on his face. Nobody laughed at any of his jokes.” Finally, the phrase “to be falling to pieces/bits” means to be falling apart and to be in very bad condition: “That old house is falling to pieces.”
strong
In this podcast, the word “strong” means with a steady value or a value that decreases only very slowly, not dramatically decreasing over time: “When oil prices are strong, gasoline is more expensive.” The phrase “to be in a strong position” means to have some advantage in a negotiation and be likely to win: “The buyers knew that the sellers were desperate to move, so they were in a strong position when they made an offer on the house.” A person’s “strong point” is his or her greatest strength: “Tina doesn’t have much experience as the other job applicants, but her good communication skills are a strong point.” Finally, the phrase “to be going strong” means to continue to be successful even after someone or something is old and has been doing something for a long time: “The company just turn 135 years old, and it’s still going strong.”
Culture Note
The FDIC
The “Federal Deposit Insurance Corporation” (“FDIC”) is a U.S. government “corporation” (business) that “insures” (provides financial protection for) individuals’ “deposits” (the amount of money that one has put into an account) in bank accounts. Banks that are members of the FDIC can say that their customers’ accounts are insured for up to $250,000. “In other words” (to explain things in another way), an individual can “rest assured” (not worry), knowing that he or she will always have access to his or her deposits of up to $250,000—even if the bank “goes under” (goes out of business and closes)—because the FDIC will “repay” (pay back) any lost money.
Banks that are members of the FDIC have signs with the following words:
Deposits are “backed” (insured) by the full “faith and credit” (a phrase describing a government’s full commitment to doing something) of the United States Government.
In addition to insuring deposits, the FDIC also works closely with its member banks. The FDIC “examines” (inspects) banks to make sure they are following all the rules and managing money in “prudent” (responsible, conservative, and safe) ways while considering “consumer protection” (efforts to give customers reassurance, power, and safety when interacting with large businesses).
The FDIC was created by the Banking Act of 1933. It operates on funds or money received from member banks and from the “proceeds” (money received) from its investments, but it does not receive any money from the U.S. government. “To date” (so far), it has always “met its obligations” (been able to “cover” (pay for) deposits) when banks have “failed” (gone out of business).
Comprehension Answers
1 - c
2 - a