= 1116
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,116 – Reading and Processing Emails.
This is English as a Second Language Podcast episode 1,116. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com, or become a member of ESL Podcast. If you do, you can download the Learning Guide for this episode. What is the Learning Guide? It’s an eight- to ten-page PDF file that you can download that includes a complete transcript of everything I say, as well as a glossary with the words and definitions and sample sentences of key vocabulary, as well as culture notes and a whole lot more. Go to our website for more information.
On this episode, we’re going to talk about reading and processing emails. Let’s get started.
[start of story]
Every day I feel more and more overwhelmed by email. Once I turn on my computer and look at my inbox, I get sucked into reading and responding to emails.
I have a personal email account and an email account for work. With my work email, I try to take an organized approach. I scan each email, looking at the sender and subject line, and delete the ones I don’t need or want. With the remaining ones, I archive some, file others for future reading, and write replies to the rest. I’ve set up templates for the routine emails, but spend a lot of time drafting personalized responses to the rest. That takes up a large part of my workday.
When reading my personal email, I take my time. Yes, I get the usual junk that slips through the spam filters and get newsletters I keep meaning to unsubscribe from, but people who have my personal email address are mainly friends and family.
When I’m done and I look at the clock, I’m often surprised at how much time I’ve spent processing email. That’s time I could have been spending working on my Celine Dion impression.
“Near, far, wherever you are
I believe that the heart does go on. . . .”
[end of story]
I begin my story by saying, “Every day I feel more and more overwhelmed by email.” “To be overwhelmed” (overwhelmed) is to not be able to deal with something or to make decisions about something because the situation is very challenging, very difficult, very demanding. When you are “overwhelmed” with something, you have too much of it. You have too much pressure, too much stress, perhaps, because of the situation. If you get a lot of email, we might say that you are “overwhelmed with email.” The email is too much for you, too much to handle.
I then say, “Once I turn on my computer and look at my inbox, I get sucked into reading and responding to emails.” Your “inbox” is the main folder in an email account, the place where all your new emails show up on your computer or on your mobile device, such as a phone or a tablet. That’s your “inbox.”
The word “inbox” (inbox) was originally used – and still is, or could be – to describe a physical box that you have in an office, say, where people put things for you to look at or do. When you’re done with things or you want to send them to someone else within an office, you put them in your “outbox.” Well, we’ve taken those terms from the business world and “imported” them, we might say, into our modern vocabulary about technology.
I say that once I “turn on,” or start up, “my computer and look at my inbox, I get sucked into reading and responding to emails.” The expression “to get sucked (sucked) into” something means to be forced to do something or to be persuaded to do something even though you don’t really want to do it. It might actually be something that you enjoy, but you don’t have time to do.
If you are at work and you like to watch cat videos on YouTube, you might watch one of them and get sucked into watching 10 of them. It’s almost like you are addicted to that particular activity, so you keep doing it even though you know you shouldn’t be doing that. You can also get sucked into a “negative situation,” a situation that you don’t want to be a part of. That’s really what I mean in saying that “I get sucked into reading and responding to emails.” “Email,” of course, is short for “electronic mail,” and you probably know what that is if you’re listening to this podcast.
I should explain, in the title of this episode, I say “reading and processing emails.” The verb “to process” means here to take care of. For some reason that’s a word that we use in English when we’re talking about looking at your email and deciding what you want to do with the emails. You might delete it – you might get rid of it – you might answer it, or you might put it aside or do what a lot of people do, simply leave it in your inbox for several days until you finally decide to delete it.
Some people have hundreds of inbox emails that they say they’re going to get back to but never do. “To process your emails,” then, means to look at them and to make a decision about what you’re going to do about them. I continue, “I have a personal email account and an email account for work. With my work email, I try to take an organized approach.” An “approach” is the way that you do something, how you handle something.
I continue, “I scan each email, looking at the sender and subject lines.” “To scan” (scan) here means to read something very quickly, looking for some specific information. It might be a word, it might be a name – something that you are looking for that will help you, in this case, decide perhaps what to do with the email. In my case, I scan each email, looking at the “sender” (sender). The sender is the person who, of course, sent me the email. The other word we would use, for the person receiving the email, is “recipient.” If you’re looking at your own inbox, you are the recipient of all of the emails. So you’re looking at the “senders” – people who sent you emails.
I also look at the “subject line.” The subject line is what we call that brief description of the topic of the email. Some emails don’t have a subject line. They’re just blank, so you have to open it to see what exactly is inside of it. Then I say that I delete the emails I don’t want or need. “To delete” (delete) means to permanently remove, to get rid of something. Usually when you delete an email, it goes into your trash. The word “trash” outside of the context of email refers to garbage, junk, things that you don’t want anymore.
In an email program, however, “trash” means the place where your deleted emails go. Sometimes email programs allow you to put messages in the trash and then later empty the trash – get rid of all those messages permanently. I then say, “With the remaining ones” – that is, with the remaining emails, the ones I didn’t delete – “I archive some, file others for future reading, and write replies to the rest.”
“To archive” (archive) an email means to place it in a general archive folder. Now, to understand this concept, we really have to define the next term here, which is “to file” an email. “To file” (file) here means to put a message in a particular folder for some specific purpose. Most email programs allow you to create special places where you can store or keep old emails, where you can place them after you take them out of your inbox. You don’t want to delete these emails. You want to keep them for later, but you want to separate them into different groups.
You may have a folder for emails from your family. You may have a folder for emails from your wife. You may have a folder for emails from your girlfriend, who is not your wife. I’m hoping you don’t have both of those folders, but you could. That would keep them separate. That’s what we mean by the verb “to file” in the context of an email. It’s to put an email message in a particular folder.
Most email programs have a, I guess we could call “general folder,” where you can put stuff even if you’re not putting it in a particular folder, and that would be – I guess we could call it an “archive folder.” So the verb “to archive” means to move your message out of your inbox into this more general folder that is created by the email program itself. So, I can archive emails, I can file emails, or I can write “replies” to emails – I can “answer” the emails, we would say.
“I’ve set up templates for the routine emails,” I continue, “but spend a lot of time drafting personalized responses for the rest.” “To set up” is a two-word phrasal or verb meaning to establish, to create something. I’ve created or set up “templates” (templates). A “template” is an electronic document that has writing in it, text in it, that you can use to send to different people.
Usually businesses have templates for when someone writes them an email about a specific question. If a lot of people ask that question, the company will just send them the template for that question that has the answer in it. So, you don’t have to write a new email every time. We use templates here at ESL Podcast to respond to some of your messages. “Routine (routine) emails” are emails that are common, normal, everyday – emails that aren’t unusual or different in any way.
I also say that I “spend a lot of time,” meaning I take a lot of time, “drafting personalized responses.” “To draft” (draft) means to write something, usually with the idea that you will go back later and edit it and make it better. “To draft” something means to write something that you’re going to work on in the future. You’re going to save it and then work on it later – make it better and then send it. I say that “drafting personal emails takes up a large part of my workday.” That’s just another way of saying it takes up a lot of time during the time that I’m working.
“When reading my personal email, I take my time.” The expression “to take your time” means to go slowly, not to rush, not to hurry. “Yes,” I say, “I get the usual junk that slips through the spam filters and get emails I keep meaning to unsubscribe from.” “Junk (junk) email” is email that is sent to you that you don’t want. We sometimes call that type of email “spam” (spam).
A “spam filter” (filter) is a function in your email program or your email service that stops those unwanted emails from getting into your inbox. Usually they go into a special folder called a “spam folder.” Sometimes there are emails that you actually want, that the spam filter puts in the spam folder. Sometimes you need, therefore, to check your spam folder to make sure it’s not putting things you want into the spam folder instead of your inbox. But usually, nowadays, the email programs are pretty good about identifying which emails are spam and which are ones that you would want.
I also talk about “unsubscribing” to newsletters. “To unsubscribe” (unsubscribe) is to remove your name and email address from a company’s or organization’s email list. The opposite of “unsubscribe” is “subscribe,” which is to sign up, or to give your information to an organization or company, allowing that organization or company to send you emails about its activities. “To unsubscribe” is the opposite. It means to get off of those lists, essentially.
I finish by saying that “when I’m done” – when I’m finished – “and I look at the clock, I’m often surprised at how much time I’ve spent processing email. That’s time I could have been spending working on my Celine Dion impression.” An “impression” is an imitation – when someone tries to sound like another person, usually a famous person. I then sing a few lines from a famous song by Celine Dion in what is almost certainly the worst impression of Ms. Dion in the world.
Now let’s listen to the story, this time at a normal speed.
[start of story]
Every day I feel more and more overwhelmed by email. Once I turn on my computer and look at my inbox, I get sucked into reading and responding to emails.
I have a personal email account and an email account for work. With my work email, I try to take an organized approach. I scan each email, looking at the sender and subject line, and delete the ones I don’t need or want. With the remaining ones, I archive some, file others for future reading, and write replies to the rest. I’ve set up templates for the routine emails, but spend a lot of time drafting personalized responses to the rest. That takes up a large part of my workday.
When reading my personal email, I take my time. Yes, I get the usual junk that slips through the spam filters and get newsletters I keep meaning to unsubscribe from, but people who have my personal email address are mainly friends and family.
When I’m done and I look at the clock, I’m often surprised at how much time I’ve spent processing email. That’s time I could have been spending working on my Celine Dion impression.
“Near, far, wherever you are
I believe that the heart does go on. . . .”
[end of story]
There’s nothing routine about the dialogues and stories written by our wonderful scriptwriter, Dr. Lucy Tse. So, thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
overwhelmed – not able to deal with something or make decisions about it, especially because something is very large, challenging, or demanding
* Mike feels overwhelmed with his job and caring for his two young children.
inbox – the main folder in an email account, where new messages appear until they are moved or deleted
* I sent the message a moment ago. It should be in your inbox now.
to get sucked into – to be compelled, persuaded, or forced to do something without really wanting or intending to do it
* How did you get sucked into volunteering to be the club president?
email – electronic mail; digital, typed notes that are exchanged between addresses with an @ (“at”) symbol
* If you would like to cancel your membership, please send us an email with your account number.
approach – the way in which one does something; how one considers, handles, tackles, or deals with something
* Her detail-oriented approach has been an asset to the accounting firm.
to scan – to read something very quickly, focusing on only the most important words, and not reading every word, especially when searching for specific information
* They scanned the financial statements, looking for the firm’s sales revenue.
sender – the person who sent a message; the person who wrote an email
* Jennie won’t open an email unless she recognizes the sender, because she’s afraid of someone sending her a virus.
subject line – a brief description of the topic and contents of an email, displayed next to the name of the sender, the name of the recipient, and the date
* A subject line should be as descriptive as possible. Never just write “hi” in the subject line of a professional email.
to delete – to permanently remove; to move something to the trash so that it will no longer be present
* I accidentally deleted your message. Could you please send it again?
to archive – to move a message out of the inbox so that it can be found in the future if needed, but without placing it in any particular folder
* If you’ve already replied to a message, please archive it so that nobody else thinks it’s waiting for a reply.
to file – to place a message in a folder with related messages so that one can find it in the future, if needed
* I file all itineraries, flight tickets, and hotel reservations in the “Travel” folder.
template – an electronic document with all the basic formatting and text, so that one can send it to many different people with little or no modification
* The customer service representatives use templates to quickly reply to the most common inquiries.
routine – normal, common, everyday, not unusual
* The university campus tour guides get tired of answering routine questions from prospective students.
to draft – to write something, especially with the expectation that it will be edited and revised to create a final version
* The speechwriter drafts all of the President’s speeches, but she always makes changes to it before giving it.
spam filter – a set of rules or a program that identifies unwanted messages and prevents them from being delivered to the inbox
* The spam filter does a good job of blocking emails from people who aren’t on my contact lists.
to unsubscribe – to remove one’s name and contact information from a newsletter distribution list because one no longer wants to receive messages from that sender
* I have no interest in your company’s products or services. Please unsubscribe me from your mailing list.
to process – to handle or deal with something; to determine what one’s action should be and then perform it, especially when those determinations and actions must be repeated many times
* The accounting office processes hundreds of invoices every month.
Comprehension Questions
1. What is a spam filter supposed to do?
a) Prevent unwanted emails from appearing in the inbox
b) Automatically reply with an out-of-office message
c) Tag (label) emails from preferred senders as being important
2. What does he do when he scans each email?
a) He prints it out and files it
b) He decides whether he should reply to it
c) He reads it very quickly
Answers at bottom.
What Else Does It Mean?
to scan
The verb “to scan,” in this podcast, means to read something very quickly, focusing on only the most important words, and not reading every word, especially when searching for specific information: “Please scan these reports to find the contact information.” When talking about computer hardware, “to scan” means to create a digital image of a printed piece of paper: “Please sign the contract, scan it, and return it by email as a PDF.” Finally, when a machine “scans” something, it examines it by using technology to form a picture of what is inside: “The MRI machine can scan the brain to look for abnormalities.” Or, “What are the airport security officials looking for when they scan our carry-on items and suitcases?”
to process
In this podcast, the verb “to process” means to handle or deal with something, or to determine what one’s action should be and then perform it: “The healthcare website has to process thousands of transactions each hour.” The verb “to process” also means to manufacture or to create something: “The factory processes meat, milk, and wool to sell at local markets.” Less formally, “to process” means to take the time to understand and accept something that has happened: “It’s going to take us a while to process the tragedy and really understand what happened.” Finally, “due process” refers to the correct legal procedures and rules that should be followed: “The court is following due process to ensure that everyone is treated fairly.”
Culture Note
E-cards
Americans often send “greeting cards” (printed, folded cards with an image on the front and a kind or humorous message printed on the inside) to each other on “special occasions” (holidays and other dates that deserve recognition or celebration), but in recent years “e-cards” or “electronic cards” have become popular. E-cards have many of the same “elements” (parts) of greeting cards, but they can be sent via email and opened on a computer screen. The “recipient” (the person who receives something) can view the image and read text online.
“Nowadays” (in modern times), e-cards are more “sophisticated” (fancy; complex), often with moving images or video and music, as well as opportunities for the recipient to interact with the e-card, perhaps with a simple video game, or even just clicking to open a “present” (gift) and view a message that appears to come from a box or envelope. Sometimes recipients can modify the images on the e-card, for example by inserting their own photograph into the design. And some e-cards are “integrated” (combined) with “gift cards” (a card representing money that can be spent at a particular store).
Most e-cards can be created and sent for free, although some require the sender to be a paying member of a particular website. Some nonprofit organizations have created e-cards that spread important messages, such as the need to “spay and neuter” (sterilize; make it so that an animal cannot reproduce) pets, or the importance of “donating organs” (agreeing to give parts of one’s bodies to sick people who need them after one’s death).
Comprehension Answers
1 - a
2 - c