= 1136
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,136 – Missing a Deadline.
This is English as a Second Language Podcast episode 1,136. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast. When you do, you can download a Learning Guide for this episode. You can also take a look at our ESL Podcast Store, with additional courses in Business and Daily English. And why not like us on Facebook? Go to facebook.com/eslpod.
This episode is a dialogue between Oliver and Alena about missing a deadline. Let’s get started.
[start of dialogue]
Oliver: I’ve just had to tell a client that I’m running behind and I won’t make the deadline.
Alena: How did she take it?
Oliver: Not so well, at first. I knew she wouldn’t be happy, so I’ve been in a dilemma for days: Should I tell her now that I’m going to miss the deadline, or wait until the deadline had passed.
Alena: For what it’s worth, I think you did the right thing. It gives her advance notice in case it affects other parts of her project.
Oliver: That’s what I thought, too. I also offered to make up for any inconvenience the delay would cause.
Alena: Did she take you up on it?
Oliver: No, she said that giving me a three-day extension wouldn’t set her back, but if it dragged on for longer than that, it would put her in an awkward spot, and she would let me know.
Alena: I’m glad you came to an understanding. So you’ll have it done by the new deadline, right?
Oliver: Yes, even if I have to do without sleep, food, or bathroom breaks for the next week.
Alena: That’s very dedicated of you, though potentially messy.
[end of dialogue]
Oliver begins our dialogue by saying, “I’ve just had to tell a client that I’m running behind and I won’t make the deadline.” A “client” (client) is a person you work for, usually a person for whom you do some sort of service. It’s sometimes used the same way we use the word “customer,” although “customer” usually means that the person is buying something from you, some physical object – a book, or a car, or a computer.
Oliver tells his client that he’s “running behind.” The phrasal verb “to run behind” (behind) means to be late, to have something take longer than planned so that you will probably not finish it when you are supposed to finish it. “I’m running behind” means I’m late. “To make the deadline” (deadline) means to complete something when you are supposed to complete it, to complete it on time. A “deadline” is a time or a day by which you have to finish something. Here in the United States, everyone has to pay their taxes by the 15th of April. The personal tax deadline is April 15th.
Alena says, “How did she,” meaning Oliver’s client, “take it?” The expression here “to take it” means to accept something, to react to some news, some information – usually bad information, although not always. Someone may say, “Well my boss fired his secretary.” He fired the person who was working for him. You might ask, “Well, how did he take it?” How did he react? “What was his emotional state?” you might say. Alena asks how Oliver’s client took the information or the notification that he wasn’t going to make his deadline.
Oliver says, “Not so well, at first,” meaning right after he told her. “I knew she wouldn’t be happy,” he continues, “so I’ve been in a dilemma for days.” A “dilemma” (dilemma) is a situation where you don’t know what to do. It’s a difficult or confusing situation that makes it hard or tough for you to make a decision. Often, we use this when we have two different possible solutions and we can’t decide which solution is better.
Oliver then tells us what the two possible solutions to his dilemma were. He says, “Should I tell her now that I’m going to miss the deadline, or wait until the deadline has passed.” “To miss (miss) the deadline” means to not make the deadline. It’s the opposite of “making the deadline.” “To miss the deadline” means that you don’t complete what you are supposed to complete on time.
Oliver’s dilemma was deciding if he should tell his client that he wasn’t going to make the deadline – that he was going to in fact miss the deadline – or just wait until the deadline had passed, meaning after the deadline. Alena answers, “For what it’s worth, I think you did the right thing.” The expression “For what it’s worth” (worth) is used when we’re giving someone information that we hope will be helpful but often it isn’t, or perhaps you’re just unsure if it will be helpful or not. Alena says that she thinks Oliver did the right thing.
She says, “It gives her advance notice in case it affects other parts of her project.” “Notice” (notice) is information you give someone about some situation. “Advance notice” would be information before the event occurs. If you are going to leave at five o’clock this afternoon, you may say to your boss, “I want to give you advance notice that I’m leaving at five o’clock today instead of my normal time at six o’clock.” If you wait until five o’clock to tell your boss, you are not giving advance notice, and your boss might not be very happy with you.
Oliver says, “That’s what I thought, too.” In other words, yes – it was good to give her advance notice. “I also offered to make up for any inconvenience the delay would cause.” “To make up for” something is a very useful phrasal verb in English. It means to do something that corrects a problem or a mistake that you have made. It may also be used as a way of apologizing for a mistake that you made.
Let’s say you were supposed to take your wife out to dinner tonight, and you can’t because you have to work late at the office. You may call your wife and say, “I’m sorry, I can’t go to dinner tonight, but I will make up for it by taking you to a movie tomorrow night.” I’m not sure if your wife will agree that taking her to a movie makes up for going out to dinner, but that could be a way to use that expression. Oliver says he offered to make up for the “inconvenience the delay (delay) would cause.” A “delay” is when something happens later than it should, later than it was scheduled to happen.
Alena says, “Did she take you up on it?” “To take someone up on” something is another very useful phrase. It means to accept another person’s offer to do something. If someone says, “If you need a ride to the airport tomorrow, just let me know,” you could call the person later and say, “I’d like to take you up on your offer to take me to the airport.” In other words, you’re agreeing to let that person help you. Alena asks if Oliver’s client took him up on his offer to make up for the inconvenience. Oliver says, “No, she said that giving me a three-day extension wouldn’t set her back.”
An “extension” (extension) here means additional time to complete a task. If you are late on a project you are supposed to be completing, you might go to your boss and say, “I need an extension” – I need more time. Oliver’s client tells him that giving him a three-day extension would not “set her back.” “To set (set) someone back” means to create a delay for someone else, to make someone else be behind schedule. You could also say, “This problem set us back” or “set me back.” It caused me to no longer be able to meet the deadlines I was hoping to meet.
Oliver’s client told him, however, that if this delay “dragged on” for longer than three days, “it would put her in an awkward spot.” “To drag (drag) on” is a phrasal verb meaning to last for a longer time than anticipated – to go at a very slow pace, a very slow speed. If the delay dragged on for longer than three days, Oliver’s client said it would put her in an “awkward (awkward) spot (spot).” A “spot” here means a situation. An “awkward spot” would be a difficult or uncomfortable situation.
Alena says, “I’m glad you came to an understanding.” This is a very common phrase in business, “to come to an understanding.” “To come to an understanding” means to reach an agreement, to agree on something. “My brothers and sisters came to an understanding about what we should do with my parents’ house.” We came to an understanding. We came to an agreement.
Alena continues, “So you’ll have it done by the new deadline, right?” Oliver says, “Yes, even if I have to do without sleep, food, or bathroom breaks for the next week. “To do without” something is not to do something, especially when normally you would consider it a necessary thing to do. “To do without sleep” means that you are not going to go to sleep. You’re going to, in this case, continue working. Sleep is normally considered necessary, so to do without it is considered a sacrifice, a difficult thing to do.
Doing without food would also be very difficult if you did it for a week. Oliver obviously doesn’t really mean he’s going to do without food for a week. Alena says, “That’s very dedicated of you,” and “potentially messy.” “Dedicated” (dedicated) means committed or devoted, wanting to do a particular thing. “I’m very dedicated to working out in the afternoon, to exercising every afternoon, which I do on a treadmill.” I’m dedicated to that. I am committed to it.
Alena says that Oliver is dedicated. He’s dedicated to completing this task for his client, though his idea of doing without bathroom breaks is “potentially,” or possibly, “messy.” “Messy” (messy) is unorganized or dirty. Of course, bathroom breaks would mean going to the bathroom, and you certainly do not want to do without that.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Oliver: I’ve just had to tell a client that I’m running behind and I won’t make the deadline.
Alena: How did she take it?
Oliver: Not so well, at first. I knew she wouldn’t be happy, so I’ve been in a dilemma for days: Should I tell her now that I’m going to miss the deadline, or wait until the deadline had passed.
Alena: For what it’s worth, I think you did the right thing. It gives her advance notice in case it affects other parts of her project.
Oliver: That’s what I thought, too. I also offered to make up for any inconvenience the delay would cause.
Alena: Did she take you up on it?
Oliver: No, she said that giving me a three-day extension wouldn’t set her back, but if it dragged on for longer than that, it would put her in an awkward spot, and she would let me know.
Alena: I’m glad you came to an understanding. So you’ll have it done by the new deadline, right?
Oliver: Yes, even if I have to do without sleep, food, or bathroom breaks for the next week.
Alena: That’s very dedicated of you, though potentially messy.
[end of dialogue]
Our scriptwriter never misses a deadline. She’s too organized for that. I speak, of course, of the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to run behind – to be behind schedule; to be late; to have something take longer than planned, so that one will probably not finish it on time
* It took me a few minutes to find my car keys this morning. Could you please call the office and let them know that I’m running behind?
to make the deadline – to meet the deadline; to complete and submit or deliver something on time
* Did you make the deadline for filing your taxes this year?
to take it – to accept something, usually information or news; to react to something in a particular way, especially with strong emotions
* When Jake crashed his parents’ car, they took it surprisingly well and said they were just relieved that he was okay.
dilemma – a situation where one does not know what to do; a difficult or confusing situation in which it is difficult to make a decision
* Not knowing which job offer to accept is a dilemma, but it’s a good situation to be in!
to miss the deadline – to not meet the deadline; to not complete, submit, or deliver something on time, instead requiring additional time
* If students miss the deadline for turning in the essay, will you let them turn it in later?
for what it’s worth – a phrase used when presenting information that one hopes will be helpful, but probably isn’t, or that does not truly solve another person’s problem
* I’m sorry your boss didn’t accept your proposal, but for what it’s worth, I think you have a great idea.
advance notice – notification about something ahead of time, not at the last minute; information about an event before it occurs
* If you need to change your appointment, please call the doctor’s office with at least 24 hours of advance notice.
to make up for (something) – to do something that corrects or apologizes for something that one has done wrong
* We’re so sorry we forgot to thank you as one of the volunteers. What can we do to make up for our mistake?
delay – when something happens later than scheduled
* This flight delay is going to make it difficult to catch our next flight.
to take (one) up on (something) – to accept another person’s offer to have or do something
* Heather is studying at beauty school and has offered to cut her friends’ hair for free, but so far nobody has taken her up on it.
extension – additional time or space; more time given to complete a task
* The bank agreed to give us a 30-day extension for paying our mortgage.
to set (someone) back – to put someone behind schedule; to create a delay and a problem for another person
* The electrician completed the work really slowly, which set us back for the larger remodeling project.
to drag on – to last for a very long time, especially at a slow pace, seeming to be unending
* If this ballet drags on much longer, everyone in the audience will be asleep!
awkward spot – a difficult, challenging, and uncomfortable situation
* If the reporters find out that the Senator was lying, she’ll be in an awkward spot.
to come to an understanding – to reach an agreement; to agree on something
* The siblings finally came to an understanding about how to handle their parents’ estate.
to do without – to not have or do something, especially something that is normally considered a necessity
* Humans can do without water for only a few days.
dedicated – committed; devoted; wanting and intending to do a particular thing
* Justin is a dedicated student who always turns in his homework on time.
messy – unorganized, disordered, and dirty; not clean or tidy
* The girls’ room is so messy that she have a hard time finding clothes to wear in the morning.
Comprehension Questions
1. Which of these could cause a delay?
a) Missing the deadline
b) Coming to an understanding
c) Doing without sleep, food, or bathroom breaks
2. What does Oliver mean when he says, “I’ve been in a dilemma for days”?
a) He has been very stressed out.
b) He has been very worried.
c) He has been unsure of what to do.
Answers at bottom.
What Else Does It Mean?
to make up for
The phrase “to make up for,” in this podcast, means to do something that corrects or apologizes for something that one has done wrong: “Exercising for four hours on one day can’t make up for weeks of sitting on the couch and eating junk food.” The phrase “to make up for lost time” means to do something quickly because one wasn’t working on it before, or because one is behind schedule: “Most people are working long days, trying to make up for lost time from when the office was closed for repairs.” Finally, the phrase “to make up” means to reconcile, or to end a disagreement and have a good relationship again: “Last week they weren’t speaking to each other, but fortunately, they’ve made up and they are friends again.”
to do without
In this podcast, the phrase “to do without” means to not have or do something, especially something that is normally considered a necessity: “If Pierre can’t find a new job soon, he’ll have to do without restaurants meals, new clothing, and other luxuries.” The phrase “to have to do with (something)” means for something to be related to something else: “What does a class in ancient Greek history have to do with your major in civil engineering?” Finally, the phrase “without so much as a (something)” is used to emphasize that something did not happen or was not present: “Without so much as a ‘thank you,’ he took the money and left.” Or, “He acted like he didn’t know her and walked past without so much as a smile or nod.”
Culture Note
Common Clauses in Freelance Contracts
Many “freelancers” (independent contractors; people who work independently, without a formal employer/employee relationship) begin working without a “contract” (a written legal agreement), but as they build their business, they often need to develop contracts to make their work go as “smoothly” (without problems) as possible.
Freelance contracts almost always “specify” (describe in detail) the “payment schedule,” describing what will be paid, when, and how. Often the payment schedule specifies “milestone payments,” or payments that are made only when a particular “deliverable” (something the freelancer gives to the client) is completed “satisfactorily” (to an acceptable level, with the client being pleased with it).
Another common “clause” (a part of a contract) is a “kill fee,” which allows the freelancer to be paid for work completed “to date” (so far) if the project is canceled. Without a kill fee, a client could decide to “terminate” (end) a project without “compensating” (paying) the freelancer for the time that he or she has already worked on the project.
When freelancers work for a larger company, they might include a clause specifying a “single point of contact,” which means that the freelancer will need to communicate with only one person in the company. This is important, because communicating with a large team can be “confusing” (unclear) and “time-consuming” (requiring a lot of time).
Finally, many clauses are related to “copyright,” or the idea of who owns the work produced by the freelancer. Sometimes the freelancer “retains” (keeps) the copyright and can “reuse” (use again) the material while working with other clients, but in other cases the copyright “passes to” (is transferred to) the client.
Comprehension Answers
1 - a
2 - c