= 1137
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,137 – Using Battery Power.
This is English as a Second Language podcast episode 1,137. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com. Why? Well, I thought you’d never ask. So you can become a member of ESL Podcast and download the Learning Guide for this episode. You can also like us on Facebook at facebook.com/eslpod. And why not follow us on Twitter – at @eslpod, of course.
This episode is a dialogue between Luisa and Allesandro about using battery power for your electronic devices. Let’s get started.
[start of dialogue]
Luisa: The battery on my computer is almost out of juice.
Allesandro: Did you bring a spare?
Luisa: It’s a rechargeable battery, so instead of replacing it, I need to plug it in, but there are no outlets in here.
Allesandro: I don’t see one either.
Luisa: Forget it. I’ll just finish watching the movie on my phone. Oh no, my phone battery is running low, too. It’s a high-capacity battery and is supposed to discharge slowly, giving me a full day of power. I don’t know what’s wrong with it.
Allesandro: Do you want to borrow my radio? At least you can listen to music for a while.
Luisa: A radio? You mean an old-fashioned radio?
Allesandro: Yeah, it uses disposable batteries and I brought plenty.
Luisa: No, thanks. I don’t think a radio will do me any good. Maybe there’s an emergency generator around here. I just need enough electricity to finish watching my movie.
Allesandro: I don’t think that will do you any good, and plus, the emergency generator is supposed to be used for emergencies and only in the event of a power failure.
Luisa: Exactly! What can be more of an emergency than not knowing how a movie ends?
[end of dialogue]
Luisa kicks things off – that is, starts things – in our dialogue by saying, “The battery on my computer is almost out of juice.” Your “battery” is what stores energy that you use for an electronic device. Your cell phone, your tablet, most laptop computers have batteries in them so you can use them without plugging in directly to the electrical outlet in the wall. “To be out of juice” (juice) means that your battery no longer has any power, any energy.
The word “juice” is also used, of course, for a liquid that you drink, made from usually some sort of fruit. Think of orange juice or apple juice or pineapple juice (although pineapple juice isn’t very popular). This juice, however, has nothing to do with something you drink. It has to do with the power, energy remaining in your battery. (Please don’t email me and tell me that power and energy are not the same thing. I understand that, but in conversational English we use those two words interchangeably often, one for the other.)
Allesandro says, “Did you bring a spare?” A “spare” (spare) is an additional item or an additional thing that you can use as a replacement for something else if it stops working. So, here the word “spare” really means “spare battery,” an extra battery. We also, in our cars, carry a “spare tire,” which some people often refer to simply as “the spare.” “The spare” is the extra tire or wheel you have in your car in case you have a problem with one of your tires. We call it a “spare tire” for your car even though the tire goes around the wheel. We probably should call it a “spare wheel.” But we don’t. We usually just say a “spare tire.”
Anyway, we’re not talking about cars here, Jeff. Get back to the story.
Allesandro asks Luisa if she brought a spare – that is, spare battery. Luisa says, “It’s a rechargeable battery, so instead of replacing it, I need to plug it in, but there are no outlets here.” There are basically two kinds of batteries. There are batteries that you use once and then you throw away, and there are batteries that you can recharge. “To charge” (charge) something means to add power to it, in a sense. So, “rechargeable” (rechargeable) is a battery that you can use more than once. You can add power or energy to it again so that you can use it again.
Luisa says that she has a rechargeable battery, so instead of replacing it – that is, instead of throwing it out and putting a new battery in – she needs to plug the battery in. “To plug something in” means to connect it to a source of electricity so that it will work. If you have a television, usually you have to plug it in. You have to connect the television to some form of, or source of, electricity.
Luisa is saying that she wants to plug her battery in so she can recharge it. “But,” she says, “there are no outlets here.” An “outlet” (outlet) is a small set of holes in the wall into which you plug something in. We may also call it a “power outlet” or an “electrical outlet.” One of the problems of traveling to another country is that sometimes their outlets are different than the outlets you have in your own country. So, you have to buy what’s called an “adapter.” Luisa says she cannot find any outlets wherever she is there in this dialogue.
Allesandro says, “I don’t see one either.” Luisa then says, “Forget it. I’ll just finish watching the movie on my phone.” So apparently Luisa was watching a movie on her computer, and now she’s going to watch it on her phone. Then she says, “Oh no, my phone battery is running low, too.” “To run (run) low (low)” means to have very little of something left – “to be running out of” something, we may also say. “I’m running low on coffee” means I don’t have very much coffee left. “I’m running low on battery power” means my battery is almost out of juice.
Luisa says, “The battery is a high-capacity battery and is supposed to discharge slowly, giving me a full day of power.” “Capacity” (capacity) refers to how much something can contain, or how big or sometimes how powerful something is. A “high-capacity battery” would be a battery that, one presumes, you could use for a long time. Luisa says, “The battery is supposed to discharge slowly.” “To discharge” (discharge) is the opposite of “to charge.” So, if “to charge” is to add electrical power to a battery, “to discharge” would be to take that away. When you use a battery, you are slowly discharging it.
Luisa thought that her high-capacity battery would give her a full day of power, a full day of use, of energy. “I don’t know what’s wrong with it,” she says. Allesandro then asks, “Do you want to borrow my radio?” A “radio” (radio), for those too young to remember, is a device that receives what are called “radio frequency waves” and uses them to produce sound. Allesandro says, “At least you can listen to music for a while.” Luisa says, “A radio? You mean an old-fashioned radio?” “Old-fashioned” here means something that no one uses anymore.
Allesandro says, “Yeah,” meaning yes. “It uses disposable batteries and I brought plenty.” “Disposable” (disposable) is the opposite of “rechargeable.” A “disposable battery” is one of those batteries that you use once and then you throw it away. A paper napkin is disposable. Once you use it, you can’t wash it. You just have to throw it away. Allesandro says he brought “plenty” (plenty). Here, he means plenty of batteries. “Plenty” is a lot of something. “We have plenty of food,” meaning we have enough food for everyone.
Luisa says, “No, thanks. I don’t think a radio will do me any good,” meaning it won’t help me. “Maybe there’s an emergency generator around here.” An “emergency generator” (generator) is a machine that produces energy when the regular supply of electricity that you get to your house or your office building doesn’t work. In some parts of the world, emergency generators are very common because the electrical system perhaps is not very reliable.
Some people have emergency generators in case there is, well, an emergency – a situation that may cause the electricity to no longer work. Here in Southern California, it’s probably a good idea to have an emergency generator in case we have an earthquake, where the earth begins to move and bad things can happen. Do I have an emergency generator? Of course not, because I do not plan ahead very well, kind of like Luisa.
Luisa says, “Maybe there’s an emergency generator around here. I just need enough electricity to finish watching my movie.” The word “electricity” here is used to mean something similar to “power” and “energy.” Allesandro says, “I don’t think that will do you any good,” meaning I don’t think that will help you.
“And plus,” Allesandro says, meaning in addition, “the emergency generator is supposed to be used for emergencies and only in the event of a power failure.” A “power failure” (failure) is when, as I mentioned earlier, you don’t have any electrical power coming to your house or your building. A “failure” is when something stops working the way it should. Allesandro says that an emergency generator is supposed to be used “only in the event of a power failure.” “In the event (event) of” something means if something happens or in case something happens.
Luisa says, “Exactly,” meaning that’s exactly what I mean. “What can be more of an emergency than not knowing how a movie ends?” Luisa thinks that not knowing how the movie ends is an emergency, and therefore she needs an emergency generator. I suppose if you have young children and you are entertaining them by having them watch a movie on a tablet such as an iPad and your battery dies, it might be considered an emergency because your young children may be very upset they don’t know how the movie ends.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Luisa: The battery on my computer is almost out of juice.
Allesandro: Did you bring a spare?
Luisa: It’s a rechargeable battery, so instead of replacing it, I need to plug it in, but there are no outlets in here.
Allesandro: I don’t see one either.
Luisa: Forget it. I’ll just finish watching the movie on my phone. Oh no, my phone battery is running low, too. It’s a high-capacity battery and is supposed to discharge slowly, giving me a full day of power. I don’t know what’s wrong with it.
Allesandro: Do you want to borrow my radio? At least you can listen to music for a while.
Luisa: A radio? You mean an old-fashioned radio?
Allesandro: Yeah, it uses disposable batteries and I brought plenty.
Luisa: No, thanks. I don’t think a radio will do me any good. Maybe there’s an emergency generator around here. I just need enough electricity to finish watching my movie.
Allesandro: I don’t think that will do you any good, and plus, the emergency generator is supposed to be used for emergencies and only in the event of a power failure.
Luisa: Exactly! What can be more of an emergency than not knowing how a movie ends?
[end of dialogue]
Our scriptwriter has plenty of good ideas about vocabulary and expressions that you should know in English. That’s because she’s wonderful – the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m the not-very-wonderful Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
battery – a device that stores energy, used to provide electricity and to power other devices
* Please buy some AA batteries for the flashlight, and four AAA batteries for this toy.
out of juice – without any remaining energy
* Is it important to let a phone run entirely out of juice before plugging it in again?
spare – an additional item that can be used as a replacement if or when the first one stops working
* Do you keep a spare tire in your car?
rechargeable – able to be charged repeatedly; able to accept and store a new charge after the previous charge has been used
* Rechargeable batteries are better for the environment, because they can last for years before they have to be thrown away or recycled.
to plug (something) in – to connect something to a source of electricity, usually a power outlet in a wall
* We thought the TV washing working, but it turns out that it simply wasn’t plugged in.
outlet – the small holes in the wall into which one puts the metal parts at the end of a power cord in order to connect a device to the source of electricity
* The outlets overseas are a different shape than the outlets here, so you’ll need an adapter for your electronics.
to run low – to be running out of something; to have little of something left
* We’re running low on bread and milk. Can you please pick some up at the store on your way home from work?
capacity – a measure of how much something can contain or produce, or how big or powerful something is
* With four teenage boys in the house, we need a higher-capacity refrigerator, or else we’ll have to go grocery shopping every day.
to discharge – to release the electrical charge; for the amount of stored charge to decrease as it is used
* The digital camera has been slowly discharging all day, but we should still be able to take a few more pictures if we don’t use the flash.
power – electricity; energy used to make a machine work
* The storm caused a problem with the power lines and we’ve been without power for two days.
radio – a device that receives electromagnetic radio frequency waves and uses them to produce sound, normally music or news
* I heard an interesting news story on the radio while I was driving to work this morning.
disposable – able to be thrown away; intended to be thrown away, especially after a single use
* Instead of offering disposable plates and cups at the picnic, we’re using plastic ones that we can wash later.
plenty – a lot of something; a sufficient amount, especially enough to share
* We have plenty of extra blankets in case you get cold at night.
emergency generator – a machine that produces energy when the regular supply of electricity is interrupted
* The hospital has some emergency generators that can keep the lights and other equipment running during a natural disaster.
electricity – energy the powers most devices, created by the movement of electrons
* How much electricity does your electric car use for a 30-minute drive?
to do (one) any good – to be useful or helpful to someone; to be beneficial
* Going back to school won’t do you any good if nobody is hiring when you graduate.
in the event of – if; in case something happens
* In the event of a fire, please break the glass cover and pull the alarm to notify the fire department.
power failure – a temporary loss of electricity; a period of time when electricity is not delivered to homes and businesses in a particular area
* During the windstorm, thousands of people experienced a power failure.
Comprehension Questions
1. Which of these needs to be charged?
a) An outlet
b) A battery
c) A power failure
2. What is a high-capacity battery?
a) A very expensive battery
b) A very small, compact battery
c) A battery that lasts for a long time
Answers at bottom.
What Else Does It Mean?
spare
The word “spare,” in this podcast, means an additional item that can be used as a replacement if or when the first one stops working: “Let’s give a spare key to a neighbor, just in case we get locked out of our apartment someday.” The phrase “spare time” means free time, referring to what one does when not working: “In his spare time, Clarke enjoys kayaking and snowboarding.” The phrase “spare change” refers to small coins that one does not really need: “On the way home, four homeless people asked for my spare change.” Finally, a “spare room” is a guest room, or a bedroom used for visitors: “This room is my home office, but we also use it as a spare room when we have houseguests.”
power
In this podcast, the word “power” means electricity, or energy used to make a machine work: “We wouldn’t have such high power bills if we didn’t run the air conditioner all day.” The word “power” also refers to control and one’s ability to make decisions or influence other people or events: “Does the governor have the power to let prisoners out of jail before they’ve completed their sentence?” The phrase “purchasing power” refers to people’s ability to make purchases and buy goods: “A rapid rise in inflation can decrease citizens’ purchasing power even if their average income remains constant.” Finally, when talking about math, raising something to the power of “n” means multiplying a number by itself n times: “The number 4 raised to the power of 3 equals 64.
Culture Note
Battery Disposal
For batteries to “convert” (transform; change) chemical energy into electrical energy it relies on many “heavy metals” (mercury, lead, nickel, etc.) and other chemicals that are “hazardous” (dangerous; not safe) for people and the environment. “Single-use” (used only one time) batteries must be “disposed of” (thrown away; gotten rid of) safely, because if they end up in a “landfill” (a garbage dump; a large area where garbage is left by big trucks), they might “leak” (allow a liquid to escape) hazardous materials into the “surrounding” (nearby; next to something) water and “soil” (dirt; earth).
Devices are supposed to be designed to make it easy to remove batteries so that they can be “recycled” (used to make new products). Most “waste disposal” (trash) companies that offer “curbside service” (pickup from in front of a home) allow consumers to leave a small container with used batteries, which are then collected to be recycled. And many businesses, schools, and libraries have “drop-off sites” (places where people can leave things) for used batteries. Most “retailers” (stores) that sell electronics also collect used batteries from customers “at no charge” (for free; without requesting a payment).
However, while some batteries are considered “hazardous waste,” others are not. Batteries that are “classified” (labeled; grouped) as non-hazardous waste can simply be thrown away. But in most cases, it is better to take them to a recycling center.
Comprehension Answers
1 - b
2 - c