= 1138
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,138 – Dating Nice Guys and Bad Boys.
This is English as a Second Language Podcast episode 1,138. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development, oh yeah, in beautiful Los Angeles, California.
Go to ESLPod.com and become a member of ESL Podcast. When you do, you can download the eight- to ten-page Learning Guide we provide for all of our current episodes. It gives you a complete transcript of everything we say, plus a complete glossary with all of the key terms, definitions, sample sentences, and more.
This episode is a dialogue between Jack and Alison about dating nice guys and bad boys. Let’s get started.
[start of dialogue]
Jack: I’ve had it. I’m going to start treating women like dirt. I’d get more dates.
Alison: What brought this on?
Jack: I got dumped again by a woman who thinks I’m too nice – too nice! She says she wants to be with someone who’s more assertive and unpredictable. She didn’t say it in so many words, but that means she thinks I’m a wimp and I’m boring.
Alison: My guess is she wants a bad boy. A lot of women go through that phase. We want excitement and drama, the thrill of the chase.
Jack: You mean they choose to be with selfish, irresponsible jerks because it’s exciting?
Alison: I hate to say it, but it’s true. But I’m telling you, this phase doesn’t last in most women. When we want to settle down, that’s when we look for the nice guys.
Jack: You mean I have to wait until then to get a nice girlfriend?
Alison: No, I simply mean that until then, nice guys finish last.
Jack: Well, I’m not willing to wait.
Alison: Where are you going?
Jack: I’m going to work on my swagger and my sneer.
[end of dialogue]
Jack says to Alison, “I’ve had it.” When someone says, “I’ve had it,” he means he no longer wants to continue in this situation. He is frustrated or tired of something and will no longer continue doing what he has been doing. Jack says, “I’ve had it. I’m going to start treating women like dirt. I’d get more dates.” “To treat women like dirt” (dirt) means to treat them very poorly and rudely, with very little respect. It’s an odd thing to say. How would treating women badly get you more women interested in you? Jack will explain in a minute.
Alison asks him, “What brought this on?” The question “What brought this on?” is used when you are surprised by what another person has said or done, and you want to understand what caused him or her to do what he or she did. “What brought this on?” is usually used when someone does something or says something that surprises us, something for which we don’t understand the reason.
Jack says, “I got dumped again by a woman who thinks I’m too nice.” “To get dumped” (dumped) is to be told by your boyfriend or girlfriend that the relationship you have is now over. “To get dumped” means the other person says, “You know what, I don’t want to go out with you anymore. I don’t want to be in a romantic relationship with you anymore.” Jack says he got dumped again by a woman who thinks he’s too nice. The woman, according to Jack, says that she “wants to be with someone who’s more assertive and unpredictable.”
“Assertive” (assertive) is used to describe someone who has a lot of confidence – someone who isn’t shy, someone who does what he wants and gets what he wants. “Unpredictable” is the opposite of “predictable” (predictable). “To be predictable” means to do things that someone expects you to do. “To be unpredictable” means to do things that other people don’t think you will do, or don’t expect you to do. Jack says this woman who just dumped him wants to be with someone who’s more assertive and unpredictable.
Well, actually, we find out the woman didn’t actually say that. Jack says, “She didn’t say it in so many words.” The expression “in so many words” is used to mean “in those exact words,” “in that exact way.” So, if you tell your boss, “Well, John isn’t coming in today. He says that he went out drinking last night and now he feels sick,” your boss may ask you, “What? Is that what he said?” And you say, “Well, not in so many words,” meaning he didn’t actually say that, but that’s what you think he meant. You’re not a very nice friend to John, are you, if you say that to your boss? But back to our story.
Jack says that this now ex-girlfriend of his didn’t say exactly that she wants someone who’s more assertive and unpredictable, “but that means she thinks I’m a wimp and I’m boring.” Jack is saying that the fact that this woman said that he was “too nice” means that she thinks Jack is a wimp and that he is boring. A “wimp” (wimp) is a person who is scared, who is not strong, who perhaps is a coward. Jack is saying that the woman is telling him that he is a wimp.
Alison says, “My guess is that she,” this now ex-girlfriend of Jack, “wants a bad boy. A lot of women go through that phase.” A “bad (bad) boy” is a young man, typically (or boy, teenager) who does things that are against the rules, who perhaps even breaks laws, because that makes him seem brave, daring, cool, popular, and attractive to at least some girls.
“To be a bad boy” means to be the young man who does things that are dangerous, and there are, of course, many girls who are attracted to that sort of boy or man. I should say a little bit about the expression “bad boy.” It may refer not to someone who is a teenager or a boy, but to someone who is in fact over 18 years old, someone who we would normally call a “man.” The term “bad boy” does not mean the same as the term “bad guy.” I’ll explain that in a few minutes. Let’s go back to the dialogue, though.
Alison says that this now ex-girlfriend of Jack wants a bad boy. She says, “A lot of women go through that phase” (phase). A “phase” is what we would also describe as a “stage” in the development of a person, or it could be the stage in the development of a project. It’s a period of time, in other words, when certain things happen. What Alison is saying is that some girls and women go through a phase, or a period in their life, when they want not a nice guy, but a bad boy – someone who is a little, perhaps, dangerous.
Alison explains, “We want excitement and drama, the thrill of the chase.” The expression “the thrill (thrill) of the chase (chase)” means the excitement of trying to get something that is challenging or difficult. Alison is describing what almost certainly is a very common feature in many cultures, of girls and women being attracted to men who seem very strong and sometimes even a little dangerous.
Jack says, “You mean they choose to be with selfish, irresponsible jerks because it’s exciting?” Jack is describing these bad boys not as being exciting, but rather as being “selfish, irresponsible jerks.” “To be selfish” (selfish) means to only think about your needs and your desires ?– not to care about anyone else, including in this case, your girlfriend.
“To be a jerk” (jerk) means to be a person who behaves badly, who is annoying to other people. The term “jerk” is an insult. You definitely don’t want to call anyone a “jerk,” unless perhaps you want to start a fight. “Irresponsible” (irresponsible) is the opposite of, of course, “responsible.” Someone who is “irresponsible” is someone who is not reliable, someone who doesn’t do what he’s supposed to do. Jack is describing these young men that women seem to be attracted to as being “selfish, irresponsible jerks.”
Alison says, “Well, yes, actually.” Women are attracted to these guys, these men, even though they are selfish and irresponsible, because it is exciting. Alison says, “But I’m telling you, this phase doesn’t last in most women.” In other words, most women get out of this phase at some point and no longer want to date bad boys.
She says, “When we want to settle down, that’s when we look for the nice guys.” “To settle (settle) down” is a two-word phrasal verb meaning to have a more predictable, steady life. Traditionally that means getting married, buying a home, and having children, starting a family. That’s usually what we mean by this phrasal verb “to settle down.” If you are asked by your father or mother, “When are you going to settle down?” you are being asked when are you going to get married, buy a house, have children, and so forth.
Alison says that when women want to settle down, then they stop dating bad boys and look for the nice guys. A “nice guy” is a young man who is nice, responsible, treats other people with respect. The term “nice guys” is opposite to the term “bad boys.” Now, it’s a little confusing, because we don’t say “bad guys” to mean the opposite of “nice guys.” A “bad guy” is someone who is truly evil, someone who is perhaps a criminal, someone who wants to hurt us. Similarly, a “good boy” is not the opposite of a bad boy. A “good boy” is someone who obeys the rules, who always does what he is told.
So, there are two sets of opposites here. One is “bad boy/nice guy.” The other is “good guys/bad guys.” A “bad guy” is, for example in a movie, the person who tries to kill other people or to hurt someone. The opposite of a “bad guy” is a “good guy.” The “good guy” is the hero, the person who does things right, the person who is the honest, trustworthy person. We often use “good guy” and “bad guy” when we’re talking about movies. So Alison says to Jack that when women are ready to settle down, they look for the nice guys, not the bad boys.
Jack says, “You mean I have to wait until then to get a nice girlfriend?” Alison says, “No, I simply mean that until then, nice guys finish last.” This expression “nice guys finish last” means really that good, responsible men normally don’t have success in romantic relationships, especially when they are young. Now, this changes, as Alison says, when women decide they want to have a family. That depends on the culture and the people involved, of course.
Is there an age at which American women stop looking for bad boys and start wanting to settle down? I don’t know. People are getting married much later, much older than they used to. I would say maybe when I was growing up, around the ages of, say, 22 through 25, women stopped looking for bad boys and started looking for nice guys – at least, that’s the way it worked for me. Anyway, Jack says, “Well, I’m not willing to wait.” Alison says, “Where are you going?”
Jack says, “I’m going to work on my swagger and my sneer.” “Swagger” (swagger) describes here a very confident powerful way that a man walks. If you have a certain swagger, you walk in a certain way that makes you look powerful and strong. A “sneer” (sneer) is a mean smile, usually on only one side of your mouth. You might sneer at someone you think is not as good as you if you want to show contempt of that person, if you want to indicate that you don’t think that person is at perhaps the same level as you are. It’s not a very nice thing, to sneer.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Jack: I’ve had it. I’m going to start treating women like dirt. I’d get more dates.
Alison: What brought this on?
Jack: I got dumped again by a woman who thinks I’m too nice – too nice! She says she wants to be with someone who’s more assertive and unpredictable. She didn’t say it in so many words, but that means she thinks I’m a wimp and I’m boring.
Alison: My guess is she wants a bad boy. A lot of women go through that phase. We want excitement and drama, the thrill of the chase.
Jack: You mean they choose to be with selfish, irresponsible jerks because it’s exciting?
Alison: I hate to say it, but it’s true. But I’m telling you, this phase doesn’t last in most women. When we want to settle down, that’s when we look for the nice guys.
Jack: You mean I have to wait until then to get a nice girlfriend?
Alison: No, I simply mean that until then, nice guys finish last.
Jack: Well, I’m not willing to wait.
Alison: Where are you going?
Jack: I’m going to work on my swagger and my sneer.
[end of dialogue]
There’s nothing unpredictable about our scriptwriter. She always writes wonderful scripts. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to treating (someone) like dirt – to treat someone very poorly and rudely, with little or no respect
* If you treat people like dirt, you won’t have any friends.
What brought this on? – a question asked when one is surprised by what another person has said or done and wants to understand what has caused it or what the motivations were for it
* Wow, a home-cooked meal, candlelight, and roses? What brought this on?
to get dumped – to be told by one’s romantic partner that the relationship is ending
* The last time Jose got dumped, it took him nearly a year to recover and be ready to date again.
assertive – displaying confidence and being comfortable stating what one wants or needs, without being shy or subtle
* To be successful in the workplace, learn to be assertive without being rude or too demanding.
unpredictable – doing unexpected things; doing things that other people do not expect or anticipate; spontaneous
* It’s unusual for a romantic comedy to be unpredictable. Most of them follow the same storyline.
in so many words – in those exact words; as described; in that exact way
* A: Has she said she loves you?
B: Not in so many words, but I know she feels that way.
wimp – coward; a person who is scared and does not do brave things; a person who is not strong
* Jackson is such a wimp! He’ll never ask his boss for a raise.
bad boy – a young man who does things that are against the rules or that break laws, especially to be considered brave, daring, cool, popular, and attractive to girls
* A lot of teenage girls are attracted to bad boys whom their parents don’t approve of.
phase – one stage in the development of a person or project; one of many steps
* In the early phases, nobody thought this project would succeed.
the thrill of the chase – the excitement of trying to get something that is challenging or difficult
* Are you really in love with Karina, or are you just interested in the thrill of the chase?
selfish – thinking only about one’s own needs and desires, and not caring about those of other people
* Chantelle is so selfish. She dragged her whole family to the mall because she wanted to go shopping, even when she knew that everyone else wanted to spend the day outside.
irresponsible – not fulfilling one’s responsibilities or duties; not reliable or responsible
* Mason is too irresponsible to watch his younger siblings while his parents are away.
jerk – a rude term for a disliked person who behaves badly and is annoying or offensive
* Sammy is such a jerk. Did you hear those horrible things he was saying about his co-workers when they weren’t around?
to settle down – to become established in a more predictable, steady life, especially to get married, buy a home, and start a family
* Nick dated a lot of women throughout his 20s, but now he’s ready to settle down and start a family.
nice guy – a young man who is kind, nice, and responsible, and treats other people well
* Kai is a nice guy. He would never do anything to hurt another person.
nice guys finish last – a phrase meaning that good, responsible men rarely have success in romantic relationships, while mean, irresponsible men often do
* They say that nice guys finish last, and that might be true for younger people, but once they’re older, they end up happily married.
swagger – an overly confident, powerful way for a man to walk, with large steps
* They want to find an actor with a clear swagger for the role of the cowboy.
sneer – a mean smile, especially on only one side of the mouth
* Her sneer made it clear that she didn’t like the presentation.
Comprehension Questions
1. What does Jack mean when he says, “I got dumped again by a woman”?
a) A woman yelled at him.
b) His girlfriend ended their relationship.
c) A female co-worker was promoted instead of him.
2. What does Jack mean when he says, “I’m going to work on my swagger and my sneer”?
a) He’s going to get a better-paying job.
b) He’s going to start acting like a bad boy.
c) He’s going to learn about the thrill of the chase.
Answers at bottom.
What Else Does It Mean?
in so many words
The phrase “in so many words,” in this podcast, means in those exact words or in that exact way: “They didn’t offer me the job in so many words, but the interview went really well so I think I’ll receive an offer soon.” The phrase “in (someone’s) words” means as another person said something, and is used to quote another person: “In Allen Saunders’ words, ‘Life is what happens while you are busy making other plans.’” The phrase “to have/exchange words with (someone)” means to argue: “We overheard them having words, but it sounds like they’ve made up now.” Finally, the phrase “words fail (one)” means that one cannot think what to say because one is too surprised or angry: “When he behaved so rudely, words failed me and I could only shake my head and walk away.”
jerk
In this podcast, the word “jerk” is a rude term for a disliked person who behaves badly and is annoying or offensive: “The truck drivers in this city are jerks, always cutting in front of other cars and trucks on the freeway.” A jerk is also a very rapid movement: “He signaled to his friends with a jerk of his head.” Or, “The jerk of her hand on the key helped to open the lock.” The phrase “knee-jerk reaction” describes how someone responds to something almost automatically, without thinking about it first: “Francesca’s knee-jerk reaction was to become angry about the mistake, but she took a deep breath and asked for an explanation instead.” Finally, the phrase “to jerk (someone) around” means to create problems or a difficult situation for another person: “Sometimes it seems like the agency’s policies are designed to jerk customers around.”
Culture Note
The Ben Franklin Effect
The Ben Franklin effect is a “psychological” (relating to the mind and how it affects behavior) “phenomenon” (something that is observed, but the reasons for it may not be understood) named after Benjamin Franklin, one of the “Founding Fathers” (leaders in the creation of the United States). He “observed” (noticed) that people are more likely to “do a favor” (do something nice for another person) for another person if they have previously done a favor for that person, even more than if that second person does a favor for them in return. In other words, if Person A does a favor for Person B, Person A will be more likely to do another favor for Person B than he/she would be if Person B had done a favor for Person A.
The “reverse” (opposite) is also true. If Person A “harms” (hurts) Person B, Person A is more likely to harm Person B again than Person B is to “retaliate” (doing something bad in return) against Person A.
Here is how Benjamin Franklin described the effect:
Having heard that he had in his library a certain very “scarce” (rare) and “curious” (interesting) book, I wrote a note to him, expressing my desire of “perusing” (reading) that book, and requesting he would do me the “favour” (British spelling of “favor”) of lending it to me for a few days. He sent it immediately, and I return'd it in about a week with another note, expressing strongly my sense of the favour. When we next met in the “House” (legislative body; law-making group), he spoke to me (which he had never done before), and with great “civility” (kindness and politeness); and he ever after “manifested” (showed) a readiness to serve me on all occasions, so that we became great friends, and our friendship continued to his death.
Comprehension Answers
1 - b
2 - b