= 1143
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,143 – Repairing an Appliance.
This is English as a Second Language Podcast episode 1,143. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. You can also download our free magazine app. Go to eslpod.com/apple or eslpod.com/android to download it to your phone or tablet.
On this episode, we’re going to hear a dialogue between Alonso and Virginia about fixing or repairing an appliance – a machine in your house that does some work for you, such as a dishwasher or a clothes dryer. Let’s get started.
[start of dialogue]
Virginia: Hand me that screwdriver, will you?
Alonso: Don’t tell me you’re trying to fix that dryer yourself. We need to call in an authorized repairman or repairwoman.
Virginia: Do you have any idea what they’ll charge?
Alonso: All right, then I’ll call a handyman and see if he knows anything about fixing dryers.
Virginia: If he doesn’t, he might make matters worse. I think it’s just a matter of clearing a clog or replacing a worn component.
Alonso: Yes, but which one? We should just upgrade to a newer model.
Virginia: This dryer does not need to be replaced. It’s not that old.
Alonso: But it’s been on the fritz on and off for a year.
Virginia: I don’t want to throw out a perfectly good appliance just because of a minor problem.
Alonso: Well, this “minor problem” is the reason I had to walk to work in damp clothes this morning.
Virginia: That wasn’t so bad, was it?
Alonso: In the middle of winter?! You try walking with icicles in the most uncomfortable places!
[end of dialogue]
This episode is called “Repairing an Appliance.” An “appliance” (appliance) is any machine, powered usually by electricity, that performs tasks in the home, such as a dishwasher, a washing machine, a toaster, a coffee maker – all of these could be called “appliances.” Our dialogue begins with Virginia asking Alonso, “Hand me that screwdriver, will you?” “To hand” someone something means to give it to the person, to put it in the person’s hand.
Virginia asks for a “screwdriver,” which is a special tool used for putting in and taking out small metal pieces called “screws” (screws). A “screw” is used usually to connect two pieces of material, such as two pieces of wood in a chair. Alonso says, “Don’t tell me you’re trying to fix that dryer yourself.” “To fix” (fix) means the same as to repair. When something is broken, when something isn’t working properly, you may try to repair it, to fix it. Virginia is trying to fix a “dryer” (dryer) which is an appliance you use to dry wet clothing.
Alonso says, “We need to call in an authorized repairman or repairwoman.” “To call in” is a phrasal verb meaning to get someone to come to your house or your business, usually to fix something or to help you with something. An “authorized (authorized) person” is someone who has official permission to do something. For example, if you own an Apple computer, you can take it to a person or a store to get it fixed. The person might be “authorized by Apple,” meaning Apple has said, “Yes, this person knows how to fix our computers.”
Some companies have authorized repair places – or repair “shops,” we might call them – that you can use to bring your broken appliance or broken machine and get it fixed. Alonso thinks they should call an authorized repairman. A “repairman” is a person who fixes something. Now, more recently we have started to use “repairman” to refer only to a male human being who fixes things. That’s why Alonso says a “repairman or a repairwoman.” I suppose we might also say a “repairperson,” meaning you’re not sure if it’s a man or a woman.
Virginia says, “Do you have any idea what they’ll charge?” “To charge” (charge) here means to request an amount of money in order to do something. If you go to get your car fixed, the mechanic – the person who fixes your car – will charge you something for doing it. He will say, “You have to pay me a thousand dollars.” That’s what he is charging you.
Virginia asks Alonso, “Do you have any idea what they’ll,” meaning the repair people, “charge?” This particular question, “Do you have any idea,” is usually used when you are angry or perhaps surprised that another person thinks something that you think is clearly wrong, or doesn’t have the information that the person should have. If your wife says, “I think we should drive from New York City to Los Angeles for our vacation,” you might say, “Do you have any idea how long it will take to drive from New York to Los Angeles?” You’re surprised that your wife is suggesting this.
Anyway, Alonso says, “All right, then I’ll call a handyman and see if he knows anything about fixing dryers.” A “handyman” (handyman) is a person whose job it is to fix things, usually someone who isn’t an expert or doesn’t have formal training in doing the kinds of things that he does. But sometimes a handyman will, in fact, have some education. Usually handymen don’t have licenses or official permissions to do things, but they know how to do them.
Many people, instead of going out and, say, getting an electrician to fix a problem in their home with the electricity, will hire a handyman – someone who doesn’t have the same education and training but may know how to fix smaller problems that you have in your house. Virginia says, “If he doesn’t,” meaning if he doesn’t know anything about fixing dryers, “he might make matters worse.” The phrase “to make matters (matters) worse” means to make a bad situation even worse, to make a problem bigger than it is right now.
Virginia says, “I think it’s just a matter of,” meaning it only requires, “clearing a clog or replacing a worn component.” A “clog” (clog) is when you have something blocking the flow of water through a pipe. If your kitchen sink is “clogged,” the water won’t go down into the pipes. The pipe is clogged. There’s something blocking it, and sometimes you need to do something to get that clog removed. You may need to pour some sort of chemical into the pipe. I don’t know, I’m not a plumber. I’m not a person who fixes things like clogged pipes.
Virginia thinks the problem with this dryer is a clog, which is kind of unusual since dryers don’t normally have clogs. They don’t usually use water, although I suppose you could have a clog in a pipe connected to a dryer that goes to the outside. You know, sometimes clothes dryers have a pipe that goes to the roof or goes to the outside wall. There might be a clog in that, I suppose.
Virginia also thinks the problem might be a “worn (worn) component (component).” A worn component would be a piece of something that has been used so much that it’s no longer doing what it’s supposed to be doing. You can think of your tires on your car being worn. They have been used so much that they no longer are able to do what they are supposed to do. You have to get them replaced. Alonso says, “Yes, but which one?” meaning which part, which component is worn.
He then says, “We should just upgrade to a newer model.” “To upgrade” (upgrade) means to buy a newer version of something. So if you own, say, an iPhone 4, you might want to upgrade to an iPhone 5 or an iPhone 6. You might want to buy the newer “model” (model). The model is the version of a product. The iPhone 4, 5, and 6 are three different models of the iPhone.
Virginia says, “This dryer does not need to be replaced.” “To replace” something means to bring something in to do what the machine is doing now – basically, to get a different machine. She says, “It’s not that old,” meaning it’s not very old. Alonso says, “But it’s been on the fritz on and off for a year.” “To be on the fritz” (fritz) means not to be working reliably, not to be working correctly. It’s an informal expression, “to be on the fritz.” You don’t hear it as much anymore, but you can still use it.
If something is happening “on and off,” it isn’t happening all the time. If you describe your relationship with a girlfriend as being “on and off,” that means that sometimes she is your girlfriend and sometimes you break up and are not going out together, and then perhaps later she becomes your girlfriend again. It’s “on and off.” Why? I don’t know. She’s not my girlfriend.
Virginia says, “I don’t want to throw out” – that is, I don’t want to get rid of – “a perfectly good appliance just because of a minor,” or not very important, “problem.” “Perfectly good” means there’s nothing wrong with it. It’s good enough. It works. Alonso says, “Well, this minor problem is the reason I had to walk to work in damp clothes this morning.” “Damp” (damp) means slightly wet or a little moist. Alonso is saying that he had to walk to work in “damp clothes” because the clothes dryer wasn’t working.
Virginia asks, however, “That wasn’t so bad, was it?” meaning that isn’t really that bad. What are you complaining about? Alonso says, however, “In the middle of winter?! You try walking with icicles in the most uncomfortable places!” We learn that Alonso had to walk to work in damp clothes in the middle of winter, and of course if it’s in the middle of winter and you have water, sometimes icicles form. An “icicle” (icicle) is a long pointed piece of ice, usually formed when water is dripping from a high surface such as a roof or the branch of a tree.
Now of course, in the case of Alonso, he probably didn’t actually have icicles on his clothing. He’s just telling Virginia that he doesn’t want to walk to work in damp clothing in the wintertime when it’s cold out, and I can understand that.
Now let’s listen to the dialogue at a normal speed.
[start of dialogue]
Virginia: Hand me that screwdriver, will you?
Alonso: Don’t tell me you’re trying to fix that dryer yourself. We need to call in an authorized repairman or repairwoman.
Virginia: Do you have any idea what they’ll charge?
Alonso: All right, then I’ll call a handyman and see if he knows anything about fixing dryers.
Virginia: If he doesn’t, he might make matters worse. I think it’s just a matter of clearing a clog or replacing a worn component.
Alonso: Yes, but which one? We should just upgrade to a newer model.
Virginia: This dryer does not need to be replaced. It’s not that old.
Alonso: But it’s been on the fritz on and off for a year.
Virginia: I don’t want to throw out a perfectly good appliance just because of a minor problem.
Alonso: Well, this “minor problem” is the reason I had to walk to work in damp clothes this morning.
Virginia: That wasn’t so bad, was it?
Alonso: In the middle of winter?! You try walking with icicles in the most uncomfortable places!
[end of dialogue]
Our scriptwriter is like an authorized repairwoman for your English. I speak, of course, of the wonderful Dr. Lucy Tse, who can fix any language problem you might have.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to me again (well, listen to us again, really) right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to fix – to repair; to take something that is broken and make changes to it so that it works again
* Zayda thinks she can fix almost anything with a little bit of duct tape.
authorized – with official permission to have or do something
* You can’t go in there! The door has a sign that says, “Authorized personnel only.”
repairman – a man whose job is to fix things, especially a particular brand of appliances or electronic devices
* In the past year, how many times has our office had to call a repairman to fix the copier?
to charge – to request an amount of money in exchange for one’s goods or services; to set the price for something that another person is paying for
* How much do you charge for three hours of housecleaning?
handyman – a man whose job is to build or fix things, especially with a little bit of knowledge about many different things, such as plumbing, carpentry, electrical work, and more
* We need to call a handyman to fix that window and unplug the sink.
to make matters worse – to make a bad situation even worse; to make a problem bigger than it already was
* He was already in trouble for driving his father’s car without permission, but then to make matters worse, he accidentally broke his mother’s favorite lamp.
clog – something that blocks the flow of water through a pipe, typically a large amount of toilet paper, food, or hair
* Don’t put large amounts of food down the kitchen sink. It might create a clog.
worn – used; no longer new; showing the effects of age and repeated use
* These tires look worn. Don’t you think we should buy some new ones soon?
component – a part or piece of something, especially referring to an electronic device
* The keyboard, mouse, and speakers are all important components of a modern computer.
to upgrade – to buy and use the newest version of something, replacing the older version that one was previously using
* Should we upgrade our antivirus program for better virus protection?
model – one version of a product that is available in several different types
* The original camera could only take photos, but this new model takes video, too.
to replace – to begin using something else in place of what one was previously using
* They replaced their electric stove with a new gas stove.
on the fritz – broken down; not performing reliably; starting to fall apart or has stopped working
* This computer is on the fritz. It keeps shutting down unexpectedly for no reason.
on and off – alternating between two stages or statuses for a period of time; sometimes happening or working and sometimes not
* They’ve been dating on and off for the past eight years, but it still isn’t a serious relationship.
perfectly good – satisfactory; good enough; functional
* Those leftovers were perfectly good. Why did you throw them away?
appliance – a machine powered with electricity that performs tasks, usually in the home, such as a dishwasher, washing machine, blender, toaster, or coffeemaker
* They keep just two appliances on their kitchen counter: a food processor and a toaster. Everything else is kept in the cupboard.
damp – slightly wet; a little moist
* Please wipe the table with this damp washcloth.
icicle – a long, pointed spear of ice, usually formed by water dripping from a branch, roof, or some other object suspended in very cold air
* The ski lodge is so beautiful when it’s covered in icicles and surrounded by snow.
Comprehension Questions
1. Which of these needs to be replaced?
a) A clog
b) A worn component
c) A perfectly good appliance
2. What does Alonso mean when he says that the dryer has been on the fritz?
a) It has been under warranty.
b) It has not been working properly.
c) It has been causing electrical fires.
Answers at bottom.
What Else Does It Mean?
charge
The verb “to charge,” in this podcast, means to request an amount of money in exchange for one’s goods or services, or to set the price for something that another person is buying: “Can you believe they wanted to charge $4 for a bottle of water? That’s outrageous!” The verb “to charge” also means to fill a battery with electrical power so that it can operate a device: “How often do you have to charge your smart phone?” When talking about the law, “to charge” means to state that someone has broken the law: “He was charged with assault and murder.” Finally, the phrase “to charge at (someone or something)” means to quickly move toward someone or something in order to attack it: “The mountain lion charged at the chicken coop, but it wasn’t able to break in.”
damp
In this podcast, the word “damp” means slightly wet: “Sometimes a cool, damp washcloth placed on the forehead can help to get rid of a headache.” The word “damp” can also refer to very humid or moist air, especially air that is unpleasant: “Do people living in damp, swampy environments get respiratory infections more often than people living in drier areas?” A “damper” is a small metal door that controls how much air reaches the fire in a fireplace or stove: “Open the damper so we can get a brighter flame.” A “damper” is also a padded hammer that stops a piano string from making noise: “Open the top of the grand piano so the kids can see the dampers move up and down.” Finally, the phrase “to put a damper on (something)” means to make something less pleasant or enjoyable: “Don’t let the rain put a damper on our plans.”
Culture Note
Home Appliance Warranties
Home appliances are expensive, so many people want to have a “warranty” (an agreement for a company to repair or replace something if it breaks within a certain period of time) to protect themselves “in case of” (if something happens) unexpected “breakdowns” (instances where something stops working). Most appliances come with a standard manufacturer’s warranty, often for one year. But some consumers “opt” (choose) to purchase an “extended warranty.” This means that they pay extra money to have the warranty extended by some period of time, usually 2-5 years, depending on the appliance. In many cases, the investment “makes sense” (is logical; is a good idea), because people are often buying appliances immediately after buying a new home, in which case they have little cash to pay for repairs or new appliances.
A “protection plan” or a “home warranty plan” applies to a group of appliances, rather than an individual unit. The purchaser pays an “annual” (yearly) fee, and in exchange, a company “commits” (promises) to repairing and/or replacing any of the “covered” (included in the agreement) appliances if they break during the “term” (length of time) of the plan, typically one year. Often these plans are purchased by people who are selling their home, and the buyer receives protection for the appliances left behind by the sellers. This is important, because the buyers don’t really know how “reliable” (dependable; trustworthy) the appliances are.
Finally, a “service contract” is similar to a protection plan, but it focuses more on repairs than on replacement. If something breaks, the company agrees to come to the home or business and “service” (fix or repair) the appliance at no additional charge beyond what the “policyholder” (the person who benefits from the plan) has already paid.
Comprehension Answers
1 - b
2 - b