= 1145
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,145 – Using Herbs and Spices in Cooking.
This is English as a Second Language Podcast episode 1,145. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Yeah, I know. I know. It’s weird.
Go to our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. You can also take a look at our ESL Podcast Store, with additional courses in Business and Daily English.
This episode is a dialogue about cooking. Hmm, makes me hungry. Let’s get started.
[start of dialogue]
Gisela: That smells wonderful!
Danny: This is my family’s recipe. The secret is in the combination of seasonings we use.
Gisela: I can see that. You must have 30 different dried and fresh herbs and spices on this counter.
Danny: To get a bold flavor, we use a lot of aromatic seeds, barks, and roots.
Gisela: How much do you put in of each one?
Danny: Precise measurements aren’t really necessary. I put in a pinch of this and a dash of that. I add them to taste.
Gisela: So getting the recipe wouldn’t do me any good, huh?
Danny: I’m afraid not. I learned how to make this in my mother’s kitchen.
Gisela: Would you teach me if I volunteered to be your apprentice, doing all of your prep work?
Danny: That depends.
Gisela: On what?
Danny: On how quick you are with this potato peeler.
[end of dialogue]
Gisela says to Danny, “That smells wonderful! Danny replies, “This is my family’s recipe.” A “recipe” (recipe) is a set of written instructions about how to make a particular kind of food. Danny says, “The secret” – that is, the secret to the success of this recipe – “is in the combination of seasonings we use.” “Seasonings” (seasonings) refers to things you put in food to give them a certain flavor.
There are lots of different things that could be considered “seasonings.” Gisela tells us a little bit about those. She says, “I can see that. You must have 30 different dried and fresh herbs and spices on this counter.” The most common kinds of seasonings are, in fact, “herbs and spices.” That’s why the title of this episode is “Using Herbs and Spices in Cooking.”
“Herbs” (herbs) – notice that in American English, the “H” is silent; you don’t pronounce it – are leaves or other green parts of a plant that are used for seasoning food, to give food a certain flavor. You can also use herbs, or at least some people do, to make tea or even to make a kind of medicine, something to help you if you are sick. There are two different kinds of herbs. There are “dried herbs” and “fresh herbs.” Something that is “dried” is something that has been, we would say “dehydrated,” meaning all the water has been removed from it.
“Fresh herbs,” then, would be plants or parts of plants that still have some water in them, that still look and feel like they did when they were in the ground growing. Dried herbs are herbs that don’t have any water in them and that you can put in a jar, in a container and use many weeks or months later. Herbs always come from the leafy or green parts of a plant. Some examples of herbs include oregano, thyme, basil, parsley, and rosemary. Those are all common herbs used in cooking.
Another kind of seasoning for food is what is called a “spice” (spice). “Spices” also come from plants, but they come from the non-green and non-leafy part of the plant. In other words, any other part of the plant that isn’t the leaf or the green part and is used for seasoning is called a “spice.” Examples of spices include cloves, cardamom, cinnamon, ginger, and pepper. Those are all common spices. Spices are usually used after they are dried. That’s the most common way of using spices in cooking.
Gisela notes that Danny has “30 different dried and fresh herbs and spices on this counter.” A “counter” (counter) in a kitchen is a flat surface, a flat place where you can put your bowls and your ingredients for your food. Danny says, “To get a bold flavor, we use lots of aromatic seeds, barks, and roots.” “Bold” (bold) means strong or forceful. If we have a “bold flavor” (flavor), we have a taste that is very strong, a flavor that is very strong.
Danny says they use a lot of “aromatic (aromatic) seeds (seeds), barks (barks), and roots (roots).” “Aromatic” refers to something that has a very strong scent, a very strong but nice smell. The “seed” of a plant is the small part that carries the necessary information in order to have a new plant come to life, a new plant to grow. That’s how plants typically reproduce themselves. Humans reproduce themselves in a slightly different way. I will not explain that to you here.
The term “bark” is usually associated with a tree – the outermost layer of a tree. Something like a hard skin that goes around a tree. That’s “bark.” “Roots” are the parts of the plants that are underneath the ground, typically. “Roots,” “barks,” and “seeds” are all ways of getting spices – places in a plant, if you will, where spices come from. Gisela says, “How much do you put in each one?” How much of these seasonings, I’m guessing. Danny says, “Precise measurements aren’t really necessary.”
Something that is “precise” (precise) is something that is exact – one tablespoon, one teaspoon, one ounce. Those are precise measures of something. Danny says, however, that precise measurements aren’t necessary. He says, “I put a pinch of this and a dash of that.” A “pinch” (pinch) of something means a small amount of something. You’ll sometimes see that in a recipe. It’ll say “a pinch of salt.” That means just a little bit of salt. Similarly, you will see the word “dash” (dash) of some ingredient. “Dash” here also means a small amount.
Usually, it refers to a small amount of something that is in a container, what we would call a “shaker” (shaker). If you have salt and pepper in your kitchen, they are probably in what we would call, in English, “shakers” – small containers that have holes on the top of them. A “dash of salt” would be to take the salt shaker and maybe move it once over the food. A “pinch of salt” would be to take some salt in your fingers and put it into the food. Often, it can mean the same amount of salt. It’s just a different way of describing the manner or way in which you put the seasoning into the food.
Danny says, “I add them,” meaning the seasonings, “to taste.” “To add something to taste” means to put it in and then to taste the food to see how it tastes and to determine whether you need more of that ingredient. Gisela says, “So getting the recipe wouldn’t do me any good, huh?” Danny says, “I’m afraid not. Gisela is asking if she can get a copy of the recipe and then cook the food herself. Danny says no, really, you can’t because he does so much to taste. You would have to know what the taste is in order to make this recipe correctly. He says he learned how to make it “in his mother’s kitchen.”
Gisela says, “Would you teach me if I volunteered to be your apprentice, doing all of your prep work?” An “apprentice” (apprentice) is someone usually who is studying some sort of career, some sort of technical career or trade – learning how to do it by watching someone else. There are many different kinds of jobs were you learn most of what you need to know by being an apprentice. Plumbing, carpentry, and in some ways being a chef are all things that are learned best by being an apprentice, by working with an expert – someone who already knows what he’s doing.
That’s what Gisela wants to do. She wants to “volunteer” – that is, not be paid – to be Danny’s apprentice. She’ll do all of his “prep (prep) work.” “Prep” stands for “preparation. “Prep work” in a kitchen is doing all the things that you have to do to get the ingredients ready. It may involve chopping up or slicing vegetables, getting meat or other kinds of protein prepared. These are things you do before you put them all together in order to make the dish that you are making, the food that you are making.
Danny answers Gisela’s question by saying, “That depends.” Gisela says, “On what?” meaning what does it depend on? Danny says, “On how quick you are with this potato peeler.” Danny says he will give Gisela a job if she’s good at using a potato peeler. A “potato peeler” (peeler) is a small tool, almost like a knife, that is used to remove the skin from a potato. A “potato” is a kind of plant that is usually white inside and is cooked in water or using some sort of heat in order to make the inside of the plant soft in order to eat it.
Potatoes can be eaten with or without the covering that goes around the potato. We call that covering the “skin” (skin), just like you have skin on your body. “Peeling potatoes,” means taking the skin off of the potato. It is often considered a very dull and uninteresting job. When I was growing up, I would often peel potatoes for my mother. I come from an Irish-American family. Potatoes are a popular dish with Irish Americans because they were popular (and still are) in Ireland, so it’s no surprise they continue to be popular with Irish families living in the United States.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Gisela: That smells wonderful!
Danny: This is my family’s recipe. The secret is in the combination of seasonings we use.
Gisela: I can see that. You must have 30 different dried and fresh herbs and spices on this counter.
Danny: To get a bold flavor, we use a lot of aromatic seeds, barks, and roots.
Gisela: How much do you put in of each one?
Danny: Precise measurements aren’t really necessary. I put in a pinch of this and a dash of that. I add them to taste.
Gisela: So getting the recipe wouldn’t do me any good, huh?
Danny: I’m afraid not. I learned how to make this in my mother’s kitchen.
Gisela: Would you teach me if I volunteered to be your apprentice, doing all of your prep work?
Danny: That depends.
Gisela: On what?
Danny: On how quick you are with this potato peeler.
[end of dialogue]
We consider our dialogues to have bold flavors and wonderful seasoning. That’s because they’re written by the master cook of the English language, our very own Dr. Lucy Tse.
From Los Angeles California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
recipe – written instructions for making a particular type of food, including the items needed and steps required for cooking
* Could I get a copy of your recipe for blueberry muffins? They’re delicious!
seasoning – flavor; items that give flavor to food
* When the doctor told Martin to reduce his use of salt, he taught himself to use different seasonings in his food.
dried – dehydrated; with all the water removed from something
* These dried mango strips are delicious, but very chewy.
herb – the leaf or other green part of a plant, used for seasoning food or for making medicine or tea
* Sage, oregano, and rosemary are common herbs in Italian cuisine.
spice – a part of a plant, but not a leaf, used for seasoning food
* Warm apple cider seasoned with cinnamon, cloves, cardamom, and other spices is a delicious treat on a fall afternoon.
bold – strong, forceful, and direct
* Jesse doesn’t like coffee with a bold flavor, so he often mixes it with flavored cream.
flavor – the way that something tastes
* Avril likes candy that has grape flavor, but her brother prefers lemon.
aromatic – with a strong scent; having a strong and pleasant smell
* These aromatic candles are supposed to help me relax, but instead they make me sneeze.
seed – the small part of a plant that carries all the genetic information to make a new plant; the part of a plant that can be placed under soil to create a new plant
* Strawberries are the only fruit that have their seeds on the outside, not inside the fruit.
bark – the outermost layer of a tree, like a hard skin; the brown layer on the outside of a tree
* They carved their initials in the bark of the tree.
root – the part of a plant that grows underground, holding it in place and bringing water and nutrients into the plant
* They made stew with a lot of root vegetables, like carrots, onions, parsnips, turnips, and potatoes.
precise – exact; with a known amount of something
* We need to have precise measurements of the window before we buy new window blinds.
pinch – a small amount of something, equal to the amount that one can hold between one’s thumb and index or middle finger
* Season the salmon with a pinch of salt and pepper.
dash – a small amount of something, equal to the amount that comes out of a shaker when one turns it upside down and shakes it one time
* This oatmeal would be delicious with a dash of cinnamon and nutmeg.
to taste – according to how one wants something to taste; based on one’s preferences for the flavor; adding more or less of something until one likes the way the food tastes
* As you sauté the onions and peppers, add cilantro and cumin to taste.
apprentice – someone who is studying a technical career and learning how to do it by working closely with someone who is already working in that field, similar to an internship
* Gregorio worked as an apprentice to a very experienced and successful electrician.
prep work – the washing, peeling, cutting, stirring, and measuring that must be done before foods can be cooked
* After coming home from the grocery store, Heather tries to do most of her prep work for the week. She boils eggs, cuts up fruits and vegetables, and puts everything in small containers.
potato peeler – a small tool with a handle and a sharp blade, used to remove the skin from potatoes and other vegetables and fruits
* It’s easier and safer to remove the peel from a carrot with a potato peeler than with a knife.
Comprehension Questions
1. Which of these grows underground?
a) Potato Peelers.
b) Barks.
c) Roots.
2. What does Danny mean when he says, “I add them to taste”?
a) He adds more or less until he likes the way the food tastes.
b) He tastes each seasoning before he adds it to the food.
c) He uses different combinations of seasonings each time.
Answers at bottom.
What Else Does It Mean?
seed
The word “seed,” in this podcast, means the small part of a plant that can be placed under soil to create a new plant: “Have you planted seeds in your vegetable garden yet?” The phrase “seeds of (something)” describes the beginning of a new situation that is growing quickly: “Education plants the seeds of success in young children.” The phrase “to go to seed” means for a plant to start producing flowers and seeds: “Pick that cilantro soon, before it goes to seed.” That same phrase can also mean that something is getting old and falling apart: “The old homes in this neighborhood with no one living in them are going to seed.” Finally, the phrase “top seed” describes the best player in a tournament or competition: “Clarke is the top seed in the tennis tournament and is expected to win again this year.”
dash
In this podcast, the word “dash” means a small amount of something, equal to the amount that comes out of a shaker when one turns it upside down and shakes it one time: “You’ll need more than a dash of baking soda if you want those biscuits to rise.” The word “dash” can also refer to a very fast run: “The race ended with a dash to the finish line.” The phrase “to make a dash” means to run somewhere very quickly: “It started raining, so they made a dash for that office buliding.” Finally, when talking about punctuation, a “dash” is a wide hyphen (—), used to indicate a break in thought: “Come home soon—the kids are waiting for you.”
Culture Note
Kitchen Staff
“Professional kitchens” (usually kitchens in a very nice restaurant or hotel, where people have studied the “culinary arts” (the art of cooking)) and “commercial kitchens” (large kitchens that prepare food that is sold to other restaurants and stores) are “staffed with” (have working there) many people.
The “chef,” sometimes known as the “executive chef,” “top chef,” or “head chef” is the leader of the kitchen brigade staff. The executive chef is responsible for everything that the kitchen does, making sure that the right foods are prepared at the right time.
The “next in command” (the person immediately below the leader) is the “sous-chef,” whose job is to make sure that the “order” (the food items a person has asked for) of each “patron” (diner; a person who is eating at the restaurant) is correct and of good quality. The sous-chef is “largely” (mostly) “concerned with” (worried about and dealing with) timing, making sure that all the orders for a particular table are ready at the same time.
“Line cooks” are assigned to individual “stations” (areas were a certain type of food preparation is performed). The line cooks can include a “sauté chef” who works on dishes with sauces, the “roast cook” who cooks meat over flames, the “fish cook,” the “fry cook” who cooks everything that must be cooked in hot oil, the “vegetable cook,” and the “pastry chef” who makes desserts.
Other positions include a “swing cook,” who helps at other stations as needed, and the dish washers, whose job is to wash all the dishes. They wash the pots and pans as the cooks finish using them, and if the kitchen serves a restaurant, they also wash the dishes when “diners” (the people who eat at the restaurant) are finished with them.
Comprehension Answers
1 - c
2 - a