=  English pod 061-080
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''




== 061. Elementary ‐ The Weekend ‐ Swim faster! (C0061)

A: This is such a beautiful day! Great for
sailing!

B: It sure is! The water looks so nice! Anchor
the boat for a little while. I’m going to take a
dip.

A: Why are you doggy-paddling? I taught
you how to swim! Do your breast stroke!

B: I get too tired! I’ll just backstroke, it’s
easier!

A: Try kicking your legs more. That’s good.
Don’t go out too far!

B: It’s Jump in!

A: Kathy! Get back here! I see a shark!

B: Ahhhh!!!! Help me! Help! Bring the boat
closer! The shark is coming straight towards
me!

A: It’s right under you! Kathy!!!!!

'''


== 062. Elementary ‐ The Office ‐ Job Interview II (C0062)

A: Thanks for coming in today, did you have
any trouble finding us? Please take a seat.

B: Thank you.

A: So, let’s get started; tell me a bit about
your educational background.

B: Sure! Well, I graduated with honors from
Chesterton University with a major in
Business Administration, with a specialization
in Information Management, and I minored
in psychology. I chose this course of study
for two reasons: I wanted to gain some
practical, marketable skills, which the
information management track provided, and
I also feel that interpersonal skills are
essential for professional success, hence the
minor in psychology.

A: Interesting. And, your postgraduate
studies?

B: Well, I am really passionate about
consumer behavior, so I pursued a master’s
18
Englishpod Dialogues
in that area. I also strive to keep my
professional skills current, so I continuously
attend seminars and conferences related
management and customer service.

A: Very good. Now, tell me a little bit about
your work experience. I see here that you
previously worked at Oracle.

B: Yeah, I worked as their customer support
manager, which brought me a breadth of
experience in both client care, and process
management. I supervised and coordinated
the customer support team as well as
implemented new strategies to achieve
better customer satisfaction.

A: Interesting...

B: Yes, in this position I was able to make
some pretty significant contributions to the
overall success of the company. With the
different initiatives that we implemented, we
lowered our churn rate to about five percent,
which had a direct impact on revenue.

'''


== 063. Elementary ‐ The Office ‐ Receptionist (C0063)

A: Good afternoon. May I help you?

B: Yes, I’m here to see Joanna Stevens. I
have an appointment at four.

A: Certainly, may I take your name? I’ll let
her know you’ve arrived.

B: Sure, it’s Josh O’Neil.

A: Ms. Stevens will be with you momentarily.
Can I offer you something to drink?

B: Yes, a coffee would be nice, thank you.

A: Here you are. Ms. Stevens is ready for
you now. I’ll show you to her office, right this
way.

A: Just watch your step here...

'''


== 064. Elementary ‐ Daily Life ‐ I’m Sorry I Love You VI (C0064)

A: This is ridiculous! I can’t believe you’ve
been sleeping with someone else! How could
you do this! You know what? I’m out of here!

B: Wait! Doctor how is this possible? I
haven’t cheated on my boyfriend!

C: I have something to confess... I’m sorry
Veronica, I lied.

B: Wait... what? What do do you mean?

C: I lied. You aren’t even pregnant; there’s
no bun in the oven. I was just so
overwhelmed with jealousy that I couldn’t
help myself. Veronica I love you!

B: What are you talking about!!! Who are
you?

C: It’s me! Daniel, don’t you remember me?
From high school. I sat behind you every day
in class! I used to go to every football game
and watch you in the cheerleading squad!

B: You are insane! We never even spoke!
Why did you lie like that to my boyfriend?

C: Because Veronica... It’s not fair! I love
you; I have since the first day we met!
Everything was going fine until that jerk
came into the picture and ruined everything!
I went to med school and became a doctor
for you! You always said how you wanted to
marry a doctor! You will be mine now... one
way or another...

A: I heard everything, you lying bastard! Get
your hands off her!

'''


== 065. Elementary ‐ The Office ‐ Job Interview III (C0065)

A: Very good. Now, I have a couple of final
questions.

B: I hope they’re not too hard!

A: Well, why should we hire you?

B: I think that I would be a perfect fit in this
company. I have a unique combination of
strong technical acumen, and outstanding
soft skills; you know, I excel at building
strong, long-term customer relationships. For
example, when I headed the customer
support department in my previous company,
our team solved about seventy percent of
our customers’ problems. I decided that we
needed better information and technical
preparation on our products, so after I
implemented a series of training sessions in
coordination with our technical department,
we were able to solve ninety percent of our
customers’ issues. Given the opportunity, I
could bring this kind of success to this
19
Englishpod Dialogues
company.

A: Impressive! So, what would you consider
to be your greatest weakness?

B: To be honest, I struggle with organization
and time management. Punctuality has never
been a strength of mine. I find it hard to
organize my time efficiently. I have actually
addressed this weakness recently, by
attending a workshop on efficient time
management. It helped me a lot, by
providing me with great insights on how to
get organized and use my time efficiently, so
I think I’m getting better now.

A: Great... Well, let me tell you that I am
very pleased with this interview. We are
short-listing our candidates this week, and
next week we will inform our short listed
candidates of the day and time for a second
interview with our CEO.

B: Great, thanks a lot! I hope to hear from
you! Good bye.

'''


== 066. Elementary ‐ The Office ‐ Calling The Office (C0066)

A: Ello-hay, Aniel-day eaking-spay, ow-hay
ay-may I elp-hay ou-yay

B: Ay-hay, Aniel-day, Ulie-jay ere-hay

A: Ay-hay, Ulie-jay, ow-hay are ou-yay?

B: Actually, Im eeling-fay ite-quay ill otdaytay.

A: Im orry-say oo-tay ear-hay, at-they. utway
is ong-wray?

B: I ink-thay Im oming-cay own-day ith-way
uhthey oo-flay. I ave-hay a eadache-hay, a
ore-say oat-thray and Im eeling-fay ighlyslay
everishfay.

A: I ee-say. O-say oure-yay alling-cay in icksay?

B: Es-yay, I uz-way oping-hay oo-tay ake-tay
uh-they ay-day off oo-tay eecover-ray.

A: Ok, en-they. Ay-tray and et-gay ome-say
est-ray.

'''


== 067. Elementary ‐ The Weekend ‐ Soccer (C0067)

A: Welcome back, soccer fans. My name is
Rick Fields and, as always, I am joined by
my commentating wingman, Bob Copeland.

B: And we’re on the brink of soccer history
today, as Ecuador and Brazil are tied one-one
as we begin the second half of the 2022
World Cup!

A: The ref calls the players for the kick off,
and here we go! Ecuador quickly passes the
ball to the midfield, but, ohhh, it’s out of
bounds.

B: That will be a throw in for Brazil. Adriano
has the ball and makes a long pass to
Robinho, and the ref has called him offside.

A: No question about it. He was offside by a
mile! We have a goal kick for Ecuador. Edison
Mendez heads it to Valenica, he shoots!
Deflected by the defender and we have a
corner kick.

B: Delgado takes the corner. We have a foul!
Oh no, Dida, the goalkeeper, has fouled the
Ecuadorian player! He gets a yellow card and
that will be a penalty kick!

A: This is the perfect opportunity for Ecuador
to get ahead in this match and become World
Champions! He gets ready for the kick. He
shoots! and he...

'''


== 068. Elementary‐TheOffice‐Ground breaking Research (C068)

A: We’ve been over this a thousand times.
The data is irrefutable! Look, we’ve done
extensive research, built studies, and read
the literature, and there is conclusive
evidence to support my theory!

B: Horowitz, I beg to differ. Even in your
most recent study, the investigative
approach was flawed! You know as well as I
do that the collection of data was not
systematic, and there is a large margin of
error. To draw a definitive conclusion based
on that data would be misleading

A: That is preposterous!

B: You are trying to single-handedly solve
one of the world’s greatest mysteries, and
yet you are oblivious to the fact that you are
wrong!

A: I am not wrong! The chicken came first!

B: No! The egg came first!

'''


== 069. Elementary ‐ Daily Life ‐ How Would You Like Your Eggs? (C0069)

A: Wow, you’re up early today! What’s for
breakfast?

B: Well, I felt like baking, so I made some
muffins.

A: Smells good! I’ll make some coffee. Do
you want me to make you some eggs?

B: Sure, Ill take mine, sunny side up.

A: Eww, I don’t know how you can eat your
eggs like that! Ever since I was small, I’ve
had eggs and soldiers.

B: You know, my dad had scrambled eggs
eggs every morning for twenty years. It
drove my mom crazy!

A: You know what really drives me crazy?
When I ask for soft boiled eggs, and they
overcook them, so they come out hard
boiled! How can you dip your toast into a
hard boiled egg?

B: You’re so picky sometimes.

A: Here you go, honey, fried eggs.

B: Dammit! I asked for sunny side up! How
many times do I have to tell you.

'''


== 070. Elementary‐AdvancedMedia‐Buying Underwear (F0070)

A: This sucks; I hate buying lingerie. Okay,
just find something and get out of here.
Alright, these are fine. Oh, no, don’t come
over here, don’t come over here.

B: You look a little lost, can I help you?

A: Um, I’m just having a look around. It’s my
girlfriend’s birthday tomorrow. Im trying to
find her something.

B: Well, you can’t give her granny panties.
Have you thought about getting her some
sleepwear? We’ve got these lovely, silky
nighties. Or, how about a nice panty-and
and-bra set. Look, here’s a nice satin pushup
bra, and you can choose a few different
styles of undies to go with it.

A: Sure that’s fine.

A: This is so awkward...what ones do I pick?
What size is she?

B: Well, do you want a thong, some bikini
briefs, maybe this nice pair of lacy boy
shorts?

A: Just pick something and get the hell out
of here.

A: Um, I’ll go with these two.

A: This is mortifying; I just want to get this
over with. She better thank me for this...
Here you are, sir. I’m sure she’ll enjoy them.

B: Finally!

A: I’m sorry, sir. I’m going to have to take a
look inside your bag.

'''


== 071.   Elementary ‐ The Weekend ‐ Happy Hour (C0071)

A: Hey man, what do you have on tap?

B: Heineken and Budweiser. We have a twofor-
one happy hour special.

A: Cool, gimme a pint of Heineken and half a
pint of Bud.

B: Okay...A pint of Heineken and and half a
pint of bud for table six! And what about
some appetizers?

A: Sure! Let’s have some nachos and
mozzarella sticks.

B: Okay. That’ll be 80 bucks.

A: Wait... What!

'''


== 072. Elementary ‐ Intermediate ‐ You Are Fired! (C0072)

A: Hi Isabel! You wanted to see me?

B: Yes Anthony, come on in. Have a seat.

A: Is everything okay? You seem a bit
preoccupied.

B: Well, Anthony, this is not going to be an
easy conversation. The company has made
some decisions which will have a direct
impact on your employment.

A: Okay...

B: I don’t want to beat around the bush so
I’m just gonna come out with it. We are
going to have to let you go.

A: What? Why? I mean... just like that? I’m
fired?

B: I’m sorry but, to be honest, you are a
21
Englishpod Dialogues
terrible employee!

A: What! I resent that!

B: Anthony, you were caught making
international calls from the office phone, you
called in sick in eight times this month and
you smell like alcohol!

'''


== 073. Elementary ‐ Daily Life ‐ Which Finger? (C0073)

A: ...The rings please. May this ring be
blessed so he who gives it and she who
wears it may abide in peace, and continue in
love until life’s end.

B: With this ring I thee wed. Wear it as a
symbol of our love and commitment

A: Honey, that’s my pinkie. The ring goes on
the ring finger!

B: This one?

A: That’s my index finger!

B: Oh, right. This one, right?

A: Umm... that’s the thumb, Nick.

B: Okay, Okay, I got it! This is the ring
finger!

A: That’s my middle finger, Nick. This is my
ring finger!

'''


== 074. Elementary ‐ Daily Life ‐ What Am I Thinking! (C0074)

A: Miss, your salad.

B: Mmm, looks good! I’m positively
famished.

A: And for you, sir...

C: Thank you.

A: Enjoy.
B,C:Thank you.

C: I can’t believe she’s on a date with me!
I’m so lucky! I must be the luckiest guy in
the world! I want to scream at the top of my
lungs, ” I’m the luckiest dude in the world! ”
Oh, shut up! Don’t be such a dumb ass.
She’s so hot. Wait, I can’t say that. That’s
sexist. She’s so hot, She’s making me sexist.
Oh my god! I’m such a tool. Okay, get it
together. Uhh, she’s eating salad. Oh right, I
have a salad. Oh, crap! Which fork do I use?
Dammit! She’s going to think I’m a moron.
What the hell are all these forks for? Which
one did she use? Okay, chill... be cool, be
cool. Just take a fork... eat your salad...

B: Um... I...

C: Yrmf? Mmmm. Sorry, you were saying?

B: You’re eating my salad.

C: Oh, yes... it’s delicious...

'''


== 075. Elementary ‐ Daily Life ‐ Going To The Dentist (C0075)

A: Hey, Gary, great to see you again. Please
have a seat. So tell me, what seems to be
the problem?

B: Thanks, doc. I’ve got a really bad
toothache! I can’t eat anything, and look, my
face is all swollen. I think it might be my
wisdom tooth.

A: Well, let’s have a look. Open wide. Hmm...
this doesn’t look good. Well, it looks like you
have a cavity and your crown is loose. We’ll
need to put in a filling before it gets any
worse, and the crown probably needs to be
refitted. I’m going to order some x-rays.

B: Is it gonna hurt?

A: No, not at all! Just lay back and relax.

A: Ok, spit.

'''


== 076. Elementary ‐ Daily Life ‐ Learning Simple Math (C0076)

A: Alright, children, let’s review. Tommy! Pay
attention!

B: Sorry Miss Kadlec.

A: Okay, Crystal, now tell me, what’s four
plus eleven?

C: Um...fifteen!

B: Miss Kadlec always asks Crystal; she’s
such a teacher’s pet.

A: Okay...and what about fifty six minus
sixty?

C: Um... negative four!

A: Very good... twelve times twelve?

B: Very good. Suck up.

C: One hundred and forty four!

A: Zero divided by one?

C: Zero!

A: How did you know that? Okay, smarty
22
Englishpod Dialogues
pants, the square root of two!

B: Bet you’re not going to get that one,
know-it-all.

C: Um...one point four one four two one
three five...

'''


== 077. Elementary ‐ The Weekend ‐ F1 Racing (C0077)

A: Welcome back racing fans! My name is
Rick Fields and, as always, I am joined by
my partner in crime, Bob Copeland.

B: We’re in the last stretch of this very
exciting race, and Kimi Rikknen is leading the
pack with only four laps to go! They are
heading to turn three and Lewis Hamilton
tries to pass Rikknen! It’s a close one and,
oh no! Hamilton hits the wall!

A: He came in too fast, jammed on the
breaks and spun out. We have a yellow flag
and the pace car is making its way onto the
track.

B: The cleanup crew is towing the heavily
damaged car and the green flag drops!
Rikknen is still in the lead with only two laps
to go!

A: Smoke is coming out of his car! He seems
to be having engine trouble! He makes his
way into the pit, and Fernando Alonso takes
the lead!

B: How unlucky for Rikknen, and this race is
over ladies and gentlemen, Alonso takes the
checkered flag!

'''


== 078. Elementary ‐ The Weekend ‐ International Workers Day (C0078)

A: Alright everyone settle down. Let’s get
started. As you know, an important aspect of
becoming a good citizen is understanding the
genesis of our legal system. It is not enough
to simply memorize our laws, it is necessary
that we comprehend why and how they were
formed. This brings me to our topic for today.
Does anyone know what we celebrate on May
first?

B: Cinco de mayo?

A: No, that’s May fifth in Spanish, James, no
wonder you are failing my Spanish class. No,
May first is International Workers’ Day.

B: Do we get a day off from school then?

A: No! It is not considered to be a national
holiday here in the US, but in other countries
it is.

B: Aww, man!

A: In the nineteenth century, working
conditions were appalling, with workers being
forced to work ten, twelve, and fourteen
hours a day. Support for the eight-hour work
day movement was growing rapidly, despite
the indifference and hostility of many union
leaders, and by April 1886, 250,000 workers
were involved in the May Day movement.
Previous legislative attempts to improve
working conditions had failed, so labor
organizers took drastic measures. They
passed a resolution stating that eight hours
would constitute a legal day’s work. And, on
May First 1886, the resolution took effect.

B: Cool! Is that why we only work eight
hours now?

A: Yes! But the happy ending came at a high
price. On May third, 1886, police fired into a
crowd of strikers at the McCormick Reaper
Works Factory, killing four and wounding
many. A mass meeting was called for the
next day to protest the brutality.

B: And then what happened?

A: Well, as we say, the rest is history...

'''


== 079. Elementary‐The Weekend‐ Funky Galaxy Battles (C0079)

A: They are breaking through! Set your
blasters to full power!

B: Excellent job. Search the ship, she’s gotta
be in here somewhere... bring her to me!

C: Lord Hater, we have a survivor here...

B: Where is she? Don’t make me destroy
you, tell me where she is!

D: Not so fast! She will no longer be your
prisoner! It’s time you and I settled this once
and for all!

B: You are unwise to think you can defeat
me. You know nothing of the power of the
obscure side!
23
Englishpod Dialogues

D: We will stop you...

C: Lord Hater! We have an unidentified
spacecraft taking off from the rear dock!
They somehow managed to escape our
tractor beam!

B: After them!

C: They are accelerating towards the speed
of light We lost them, sir...

'''


== 080. Elementary ‐ Daily Life ‐ I’m Sorry I Love You VII (C0080)

A: Thank god you showed up when you did!
He’s insane! Do you think we should call the
police?

B: Don’t worry about it, I’ll call my friend and
have him take care of it. I can’t believe he
was stalking you all these years. What a nut
job!

A: I know! Well... he said I’m not pregnant.
I’m sorry if I got you all worked up over
nothing. I want you to know that I didn’t do
it on purpose...

B: Don’t apologize! From the moment I met
you, not a day has gone by when I haven’t
thought of you. And now that I’m with you
again, I’m... I’m just scared, Veronica. The
closer I get to you, the worse it gets. The
thought of not being with you, I mean, I just
can’t handle it! We were made for each
other, Veronica. You are my everything, my
soul mate. What can I do?

A: Just hold me... I’ll always be here for you,
no matter what. And together, we can tackle
whatever life throws at us. I believe in us,
Veronica.

B: I’m so happy to hear that! I knew we
belong together. I love you so much.

'''