
=  English pod 141-160
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''




== Elementary ‐ Daily Life ‐ What If? Part 2 (C0141)

A: This is the good life! We have it good
don’t you think?

B: Yeah of course! Although, don’t you ever
wonder what ”could have been”?

A: What do you mean?

B: Well, sometimes I think of how things
could have turned out if I had done things a
little differently.

A: For example?

B: Like for example, if I hadn’t studied
architecture, I would have become an artist
like I wanted to.

A: I see. Yeah now that I think of it, I
wouldn’t have gotten married if I hadn’t
moved to this town and met Sally.

B: You see! Everything happens for a reason!
We wouldn’t even have met if I hadn’t been
in that car accident ten years ago!

A: Well, I have no regrets!

B: I’ll drink to that!

'''


== Elementary ‐ The Weekend ‐ What Do I Wear? (C0142)

A: Honey come on! We are going to be late!
Honestly, you take longer getting ready than
I do!

B: I was drying my hair and ironing my shirt!
Can you come here for a sec? I need your
help.

A: What is it? Why are all these clothes on
the bed?

B: I don’t know what to wear! Ok, give me
your opinion. Do you like the way this looks?
The striped short sleeved shirt with this
checkered sweater and my lucky sandals. I
like the cut and hemline of these shorts so I
think I’ll wear these as well.

A: Are you joking? What am I going to do
with you? We are going to a dinner party not
the beach! Wear the shirt with the silk tie I
bought you and these corduroy pants. It’s
chilly outside so you can wear this coat.

B: Thanks honey! You have such great
fashion sense. Now, what am I going to do
with my hair?

'''


== Elementary ‐ Daily Life ‐ The Butcher (C0143)
Butcher: Hi. What can I get for you?
Gina: Id like a half a pound of ground beef,
please.
Butcher: Good choice! Our ground beef is
extra lean, if you know what I mean.
Gina: Could I also have half a dozen pork
chops and two pounds of boneless chicken
breasts?
Butcher: No, no no no chicken breasts at
the moment, but we have some nice chicken
thighs.
Gina: No, that won’t do. I’ll take this smoked
ham you have here.
Butcher: Okay, is there anything else?
Gina: Do you have any other cold cuts? Is
this salami and bologna you have here?
Butcher: Yes! It’s very fine meat! Made it
myself...
Gina: Sounds good. Okay, that’s it.
Butcher: Wait! We have T-bone, rib eye, and
sirloin steaks. They are very fresh! Just came
from the slaughter house...
Gina: Mmm... No that’s okay, really. I think
that’s all for today.
Butcher: Okay. That will be thirty-four
dollars and fifty cents.

'''


== Elementary ‐ Global View ‐ Capital Punishment (C0144)
ProfeTsshoar:t’s all for today’s class. We
will continue our lecture on crime and
punishment tomorrow.

A: Do you think we should be tougher on
crime?

B: Well, it depends on what you mean.

A: For example, we could bring back the
death penalty for murder, give longer prison
sentences for lesser offences and lock up
45
Englishpod Dialogues
juvenile offenders.

B: Those really sound like Draconian
measures. Firstly, what do you do about
miscarriages of justice if you’ve already put
innocent people to death?

A: You’d only use capital punishment if you
were absolutely sure that you’d convicted the
right person.

B: But, there’ve been many cases of
wrongful conviction where people have been
imprisoned for many years. The authorities
were sure at the time, but later it was shown
that the evidence was unreliable. In some
cases, it’d been fabricated by the police.

A: Well, no system of justice can be perfect,
but surely there’s a good case for longer
prison sentences to deter serious crime.

B: I doubt whether they could act as an
effective deterrent while the detection rate is
so low. The best way to prevent crime is to
convince people who commit it that they’re
going to be caught. It doesn’t make sense to
divert all your resources into the prison
system.

A: But if you detect more crimes, you’ll still
need prisons. In my reckoning, if we could
lock up more juvenile criminals, they’d learn
that they couldn’t get away with it. Soft
sentences will merely encourage them to do
it again.

B: Yes, but remember that prisons are often
schools for criminals. To remove crime from
society, you really have to tackle its causes.

A: Well, if I were president, I would impose
tougher laws and punishment. I would have
a peaceful society based on fear of
punishment, not consciousness of doing the
right thing.

B: You sound like a dictator!

A: Well if it works, why not?

'''


== Elementary ‐ Daily Life ‐ Chicken Pox (C0145)

A: What’s wrong with you? Why are you
scratching so much?

B: I feel itchy! I can’t stand it anymore! I
think I may be coming down with something.
I feel lightheaded and weak.

A: Let me have a look. Whoa! Get away from
me!

B: What’s wrong?

A: I think you have chicken pox! You are
contagious! Get away! Don’t breathe on me!

B: Maybe it’s just a rash or an allergy! We
can’t be sure until I see a doctor.

A: Well in the meantime you are a biohazard!
I didn’t get it when I was a kid and I’ve
heard that you can even die if you get it as
an adult!

B: Are you serious? You always blow things
out of proportion. In any case, I think I’ll go
take an oatmeal bath.

A: Ewww!

'''


== Elementary ‐ Global View ‐ Animal Rights (C0146)

A: You should have seen the T.V. show that
was on last night, the topic it covered was
really interesting; animal rights.

B: Do you really believe in that? If they are
going to focus on something, they should do
it on civil rights.

A: Yes, but we cant deny that animals are
vulnerable, defenseless, and are completely
at the mercy of human beings.

B: I understand your point, but we continue
to have transgressions against human rights.
If so much attention weren’t devoted to the
topic of animals, we would then concentrate
more on saving a human being instead of
protecting a koala.

A: You can’t compare apples and oranges; I
believe that both topics are important and
that we can’t ignore them, the mistreatment
of animals can cause a great environmental
imbalance. I believe that governments
should prohibit activities like poaching.

B: Well, you are right on that point. This is
the reason that I don’t buy leather and I try
to buy synthetic products.

B: At least youre doing your part. My
contribution is to have a pet in the house
that I treat like a member of the family.

A: As long as you dont treat it better than
46
Englishpod Dialogues
your wife, its fine.

'''


== Elementary ‐ Daily Life ‐ The Argument (C0147)

A: Wow, that terrible movie is finally over.
Next time I’m picking the film, because I
don’t want to end up seeing a chick flick.

B: Well you should have picked, in the end
you always complain about everything.

A: Not everything, just this film. Even the
title is ridiculous; and it’s so long, those are
the two and a half most wasted hours of my
life, so much so that I’m thinking about
asking them to give me my money back.

B: I’m thinking of taking you back home. I
thought we could have a nice evening, but
you’re always so negative.

A: I’m only complaining about a movie that I
could have rented or bought and then thrown
in the garbage.

B: You see, that’s what I’m talking about, I
can’t stand your sarcastic jokes anymore

A: Next time, go with your gay friend who is
more in touch with his feelings.

B: Well he’s more of a man than you are; at
least he appreciates love stories.

A: Love? More like one-night-stands.

B: Don’t criticize Mario or else I’ll start on
those fat, drunk friends of yours; they’re no
saints.

A: My friends? Fat? What about those whales
you call friends?

B: You’re unbearable; you can walk home,
I’m leaving.

'''


== Elementary ‐ Daily Life ‐ Paranoid (C0148)

A: Dan, Dan dude. You have to come over to
my house right now!

B: Is everything Ok?

A: Just get over here!

A: Come in! Quickly!

B: So, since when is your house a bank?

A: What do you mean?

B: I mean, what’s up with the and locks and
iron bars on your windows.

A: Security Dan, security! You can never be
too safe you know! A lot of sickos out there.
Just the other day they caught that peeping
tom red handed! Had a high power telescope
and binoculars by his window.

B: Whats the matter with you? Why are you
acting all paranoid?

A: Paranoid? I’m not paranoid! I’m cautious!
You see Dan, we have to be on guard at all
time! People just invade your privacy as if
they knew you! Telemarketers, solicitors,
even your bank! They have way too much
information! I like to keep everything on a
need to know basis

B: OK, well, what did you want to see me
about?

A: You are being watched! Be careful Dan!
Be careful!

'''


== Elementary ‐ Daily Life ‐ Moving (C0149)

A: Ok, that’s fine. Bye.

B: What happened?

A: That’s it, my lease is up. I have to move.

B: What? Why? Can’t you renew it?

A: The owner apparently is selling this place
to make way for the construction of a
parking lot

B: Well, I can help you pack. We should start
looking for a new place for you ASAP.

A: I think I might move in with my parents
for a couple of months until I can find
something. You know how hard it is to find a
decent place around here. I’m gonna have to
put most of my stuff in storage for a while.

B: Well, let me know if there’s anything I can
do to help out.

A: Actually, would you mind looking after my
pet tarantula and snake for a couple of
weeks?

B: hehe.. sure

'''


== Elementary ‐ The Weekend ‐ Bug Spray (C0150)

A: The mosquitos are biting me!

B: Me too, I can’t stop scratching. They are
everywhere! Sneaky little jerks.
47
Englishpod Dialogues

A: Do you have any bug spray?

B: No, I forgot to buy some.

A: Then we’ll have to put up with it.

B: We can cover ourselves with beer! That
way if they bite us, they’ll get drunk and fall
asleep

A: That’s without a doubt, the best idea
youve had! Lets do it!

B: Run! They are thirsty for more!

'''


== Elementary ‐ Advanced ‐ Darwin’s Theory Of Evolution (E0151)

A: It’s been a long time since I last saw you.
Where have you been?

B: The exams and plans I have to turn in in
are driving me crazy, I don’t even have time
to sleep.

A: It’s the same for me. I’m up to my neck in
work, but at least finals are coming soon and
we’ll have a vacation. Where are you going
now?

B: I’m going to Anthropology class and now
with the year anniversary of Darwin, it’s the
only thing we study. Frankly, I’m sick and
tired and tired of hearing about this guy.

A: What? Why? How can you not like
Darwin? I mean the man changed the entire
perception of how things came to and his
theory is backed by pretty solid evidence!

B: I don’t like him. His theory of human
evolution and natural selection is full of
holes. It lacks the solid evidence of which
you speak of.

A: That statement puts you at odds with half
of the academy. Not to mention your
professors! Furthermore, the explanation
proposed by Darwin about the origin of
species and the mechanism of natural
selection constitutes a grand step toward a
coherent understanding of the world and
evolutionist ideas.

B: I’m not minimizing his grand
contributions, it’s just that his theory
reminds of the conundrum of the chicken and
the egg.

A: What are you talking about?

B: The question is, which was first? The
chicken or the egg? I feel the same regarding
his theory. How does the first cell of life
come to be?

A: Interesting. I think that question is better
suited for my philosophy class. In the
meantime, how about we settle this... with a
due!

'''


== Elementary ‐ The Office ‐ Cut It Out (C0152)
Ed: Hey, Mary, can you cut that out?
Mary: Cut what out I’m not doing anything.
Ed: The tapping of your pen on your desk.
It’s driving me crazy.
Mary: Fine! By the way would you mind not
slurping your coffee every time you have a
cup!
Ed: I don’t slurp my coffee. And plus, how
can you hear it when you’re shouting into
your phone all the time?
Mary: You ’ve got to be kidding me! You’re
complaining about me talking on the phone
when you go out for a cigarette break ten
times a day to shoot the breeze?
Ed: Look, we have a lot of accumulated
anger from working in these conditions, and
it’s probably okay to let off steam once in a
while But, it’s probably not a good idea to
keep it up I’m willing to forgive and forget
and if you are.
Mary: Fine. Let’s call a truce. I’ll try to more
considerate and to keep the noise down
Ed: Yeah, I’ll try to do the same. So, I was
wondering you wanna go out to dinner Friday
night?

'''


== Elementary ‐ Daily Life ‐ Homesick (C0153)
Sarah: Tom! How are you? We missed you at
the party last night. Are you ok?
Tom: I don’t know. I didn’t really feel like
going out. I guess I’m feeling a little
homesick.
Sarah: Come on We’ve been through this
already! Look, I know the adjustment was
hard when you first got here, but we agreed
48
Englishpod Dialogues
that you were gonna try and deal with it.
Tom: I was. It’s just that the holidays are
coming up and I won’t be able to home
because I can’t afford the airfare. I’m just
longing for some of the comforts of home,
like my mom’s cooking and being around my
family.
Sarah: Yeah, it can get pretty lonely over
the holidays. When I first got here, I’d get
depressed and nostalgic for anything that
reminded me of home. I almost let it get to
me, but then I started going out, keeping
myself busy and before I knew it, I was used
to to it.
Tom: I see what you mean, but I ’m still
bummed out.
Sarah: Ok how does this sound: let’s get
you suited up and hit the dance club tonight.
I hear that an awesome DJ is playing and
there will be a lot of pretty single girls there!
Tom: You know, I could really go for that.
You don’t mind being my wingman for
tonight?
Sarah: Not at all! It be fun! It will be like a
boys night out... well kinda...
Tom: Great! I must warn you though,
whatever happens, don’t let me go on a
drinking binge. Trust me, it’s not a pretty
picture!

'''


== Elementary ‐ The Weekend ‐ Rock Band (C0154)

A: I’m forming a music band.

B: Do you already know how to play an
instrument?

A: Uh... Yeah! I’ve told you a thousand times
that I’m learning to play the drums. Now that
I know how to play well, I would like to form
a rock band.

B: Aside from yourself, who are the other
members of the band?

A: We have a guy who plays guitar, and
another who plays bass. Although we still
haven’t found anyone to be our singer. You
told me that you had some musical talent,
right?

B: Yes, I’m a singer.

A: Perfect. So you can audition this weekend
here at my house.

B: Great! Wait here? You don’t have enough
room for the amplifiers, microphones or even
your drums! By the way where do you keep
them or practice?

A: Dude? What are you talking about? It’s
right here! All we need is my Nintendo Wii
and we are set!

'''


== Elementary ‐ The Weekend ‐ Bachelor Party (C0155)

A: Hi honey! You’ll never guess what! My
friends Julie and Alex are getting married!

B: Wow that’s great news! They’re a great
couple!

A: I know! Anyways I just talked to Alex’s
best man and he is organizing the bachelor
party It’s gonna be gonna be so much fun!
All the groomsmen are thinking up all the
wacky and crazythings we are going to do
that night.

B: You aren’t going to a strip club are you? I
don’t want you getting a lap dance from
some stripper with the excuse that it’s your
friends party.

A: Aw come on! It’s just some innocent fun!
You know how these things are! We are
gonna play drinking games, get him some
gag gifts and just have a good time. Nothing
too over the top .

B: Well, I don’t know.

A: Come on! If one of your friends was
getting married I wouldn’t mind you going to
her bachelorette party!

B: Good,because my friend Wendy is getting
married and I’m organizing her party!

A: What!

'''


== Elementary ‐ The Weekend ‐ Scary Story (C0156)

A: Oh no! The lights went out! Honey can
you light a candle?

B: Sure. What do we do now?

A: Well, we can just talk, you know, like we
used to. Hmm... I know! I'll tell you a scary
49
Englishpod Dialogues
story! It happened to me and my dad when I
was a teenager... (fade out - fade in new
scene) I was living with my father at the
time, when he received a phone call.

B: Hmm... I know! I’ll tell you a scary story!
It happened to me and my dad when I was a
teenager...I was living with my father at the
time, when he received a phone call. I was
living with my father at the time, when he
received a phone call.
FatheHr:ello? Yes this is him. I see, I’m
sorry to hear that. Ok no problem. I’ll be
there shortly. Pack some clothes Tony, my
great aunt is very ill and no one in the family
wants to take care of her. We are going to
stay at her house for a few days.
Kid: Aunt? What aunt? I never knew you had
a great aunt!
FatheWr:ell, the family doesn’t talk about
her or get near her, for that matter.
Kid: Why is that?
FatheCr:ome on, we have to go.

B: So we arrived at this old house on the
outskirts of our town. There was almost no
one around and the house had an eerie look
to it. Once inside the house, we walked to
her room and I was surprised to find my
dad’s great aunt in a wheelchair, yelling at
someone, but we were alone in the room.
FatheHr:i, aunt Ursula! This is my son Tony.
UrsulWa:hy have you come? Why are you
here? Don’t you know it isn’t safe? My time is
near, he is coming for me.
Kid: Who is coming for you?
UrsulTah: e prince of darkness! The lord of
the underworld, the tempter, the old serpent.
FatheCr:ome on, aunt Ursula let’s lay you
down. You need to get some rest. Tony, help
me lay her down.

B: That night, we slept in one of the 12
rooms of that big old mansion. The trees
outside seemed to come alive and their
shadows formed ghoulish shapes on my bed.
All of a sudden, we heard screaming.
UrsulAah: hh! Get off me beast! I won’t let
you take me! Ahhh!
Kid: Dad! Dad! Something is attacking aunt
Ursula! UrsulUa:rsula: Take your claws off
me! Go back to the underworld you demon! I
shall be judged before you can take me!
FatheTrh: e door is jammed! Stand back!
Aunt Ursula! Where are you?
Kid: Over here!

B: And as we approached her, she was lying
on the floor, with her hands and feet open
like the Vitruvian Man, breathing heavily with
bloody marks and scratches on her arms,
legs and face. Remember how I mentioned
that she was in a wheel chair? My aunt had
been paralyzed from the neck down for just
over a year. After this incident, strange
things would happen in the house and my
aunt would yell and scream, according to her,
warding off the evil that had come to get her.
As the days passed, she became very weak
and eventually was unable to talk. My dad
had to work during the day, so I was left to
care for her. When she lost her voice and laid
on her death bed, I would hear her breathe,
in and out.

B: Until finally one day, she breathed in...
and never exhaled. That night, I felt relieved
that it was finally over, but it wasn’t.

B: I was so terrified of what I was hearing,
that I didn’t sleep all night. The following
morning, I went to the bathroom, expecting
to find a mess and everything torn up, but I
found everything exactly as it was before.
The movers came that same day and as we
were cleaning out her drawers and personal
items, we found strange notebooks with
names and amounts of money written next
to them. We found pictures with people’s
faces sewn with black or red string. And you
want to know what the strangest thing was?
There was a small doll, filled with dead ants,
with a strand of hair tied around it’s waist,
and on the doll’s face, there was a picture of
me with the numbers: ”311009”. You know
what date it is today? October 31st, 2009....

'''


== Elementary ‐ The Weekend ‐ Trick Or Treat (C0157)

A: Trick - or -treat

B: Tom, aren’t you a littletoo old to be trick-
50
Englishpod Dialogues
or - treating?

A: What are you talking about? Where is
your Halloween spirit?
Didn’t you ever dress up in a costume and go
around the neighborhood trick-or treating
with your friends?

B: Of course I did, but when I was ten! Trick
–or treating is for kids, plus, I ’m sure people
will think you’re a kidnapper or something,
running around with kids NCP at night.

A: Whatever, I’m going next door, I heard
Mrs. Robinson is giving out big bags of
M&Ms!

'''


== Elementary ‐ Global View ‐ All Saints Day (C0158)

C: The Day of the Dead has arrived All Soul’s
Dayand All Saint’s Day!

A: Your neighbor is crazy. Why is he
screaming that?

B: Because today is the first of November
the Day of the Dead

A: Oh, that’s right.

B: This is a very special day among many
cultures around the world especially in Latin
America

A: Seriously? I thought it was just like any
other day, except for the fact that people
visit the cemetery and remember their loved
ones.

B: Well, that’s just part of it People across
the world celebrate in different ways. In
Mexcio for example it’s Common to see
people building private altars honoring the
deceasedusing sugar skulls, preparing the
favorite foods and beverages of the departed
and visiting graves with these as gifts. In the
Philippines , the tombs are cleaned or
repainted, candles are lit and flowers are
offered Entire families camp out in
cemeteries .and sometimes spend a night or
two near their relatives’ tombs!

A: Whoa! That’s scary! I don’t know if I could
do that!

B: Why? We should fear the living, not the
dead .

'''


== Elementary ‐ Daily Life ‐ Getting Flowers (C0159)

A: Hello sir, how may I help you?

B: I would like to buy some flowers, please.
Something really nice.

A: I see, may I ask whatthe occasion is?

B: It’s not really an occasion, it’s more like
I’m sorry.

A: Very well. This arrangement here is very
popular among regretful husb ands and
boyfriends. It has a dozenlong stem red
roses with a couple of sunflowers and a
single orchid that stands out. It includes a
small teddy bear to achievethe effect of
immediate forgiveness.

B: I think I’m gonna need more than just a
dozen red roses and a bear. What else do
you recommend?

A: Mmm, well this is our ” I’m sorry I
cheated on you” package. Two dozen red
roses lined with tulips, carnati ons and lilies.
The fragrance and beauty of this flower
arrangement is sure to make her forgive you.

B: I don’t think that’s gonna cut it. I need
something bigger and better!

A: I’m sorry sir but, what exactly did you do?

B: Well, I may have accidentally insinuated
that she is getting chubbier .

A: Get out of my store you jerk!

'''


== Elementary ‐ Global View ‐ Health Insurance (C0160)

A: Hey honey, how was your day?

B: It was alright. I ran into Bill and we got to
talking for a while. He’s in a bit of a jam.

A: Why? What happened?

B: Well, his son had an accident and Bill
doesn’t have health insurance. This really got
me thinking, and I wondered if we shouldn’t
look into a couple of different HMO’s.

A: Yeah, you’re right. We aren’t getting any
younger and our kids are getting older.

B: Exactly! I searched on the web and found
a couple of HMO’s with low co pays and good
coverage. The deductibles are low, too.

A: Sounds good, although, do you think we
51
Englishpod Dialogues
can qualify for insurance? Those insurance
companies are real pirates when it comes to
money.

B: Well, we don’t have any pre-existing
illnesses or conditions, so we should be fine.

A: I wish our company or country provided
us with healthcare.

B: Not in a million years!

'''
