
=  English pod 161-180
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''





== Elementary ‐ Daily Life ‐ Computer Games (C0161)

A: Mark, Where have you been? I’ve been
calling you all morning.

B: I’ve been playing computer games.

A: What? So you blew me off yesterday and
today over a stupid video game? What game
is so important that you have no time for me
anymore? What are you playing?

B: It’s called Counter Strike It’s a first person
shooter game. It’s awesome. It’s a multi
player game where you can go online and
compete against players from all over the
world.

A: You’ve been wasting your time on this? I
can’t believe it! It doesn’t even look fun or
challenging!

B: My laptop is on my bed. If you think it’s
so easy then get onlineand try to beat me.

A: Fine!

B: Damm it! How are you killing me with a
single shot? It’s not fair! I don’t want to play
anymore! Let’s go get something to eat.

A: Can you bring me something? I am totally
hooked on this game!

'''


== Elementary ‐ Global View ‐ Veteran’s Day(C0162)

A: Do you have any plans for Veteran’s Day

B: You mean Armistice Day

A: Well, as you know, on November 11th
allies signed a peace treaty with the
Germans, also known as the Armistice Treaty
This marked the end of WWI and many
countries around the world commemorate
this date under names such as day. In Poland
it’s their independence day! There’s a lot
going on around the world on this day.

B: Wow, I didn’t know! Probably because I
flunked history in school.

'''


== Elementary ‐ Global View ‐ Social Security (C0163)

A: Well that was an interesting documentary!

B: For sure! I didn’t really understand some
of the technical jargon they used in the film
when they talked about social security in the
US.

A: Like what?

B: Well, they mentioned how people put
away money in something called a 401K?

A: Yeah, I know it sounds weird, but a 401k
is a type of retirement plan that allows
employees to save and invest for their own
retirement Through a you can authorize your
employer to deduct a certain amount of
money from your paycheck and invest it in
the plan Everyone tries to contribute as
much as possible so that when you retire,
you can rest peacefully on your nest egg.

B: That’s interesting and logical I guess. In
my country, we also have to contribute to a
government run retirement fund, but most
people don’t really trust it so they just invest
in properties or things like that.

A: That seems a bit unstable don’t you
think?

B: Yeah, but corrupt governments inthe past
have created distrust among banks and
financial institutions, so now people prefer to
have money hidden in a jar or a piggy bank.

A: I’ve been thinking of doing that lately! I
don’t want some banker to run off with my
money!

'''


== Elementary ‐ Daily Life ‐ Apology Letter (C0164)

A: Dear Mary, I come here today, in this way,
because I need to apologize to you. I failed
you. Although I did not lie to you in words, I
lied to you with faces that did not belong to
me. I never meant to ruin the friendship that
meant the world to me. You mean the world
52
Englishpod Dialogues
to me and now I come to you asking for
forgiveness. If in your heart you find you
can’t, then I will understand and learn from
this experience.

A: You came into my life at a time when I
needed you the most. We talked about so
many things that I started to realize my
heart and my soul could actually
feel something other than hurt. You placed
comfort where there was fear, confidence
where there was doubt, a shoulder where
tears could fall and completeness where
there was emptiness. I wanted to hold onto
to this so badly that I did whatever it took
for you to notice. What I didn’t realize was
that I could lose my entire being, all of who I
was and all that I had placed in you.

A: I wanted to be the one who would be
there when you needed to talk. I wanted to
be the comfort for your soul when the world
was too much to handle. I wanted to be
strong for you when everything else seemed
impossible. I wanted to love you in only the
way you deserved to be loved, never
realizing that I was destroying myself and
you. Somehow I needed you to be a part of
my life. The only problem was that I was
willing to jeopardize everything to get that
done.

A: All the things that I told you about how I
felt and how you make me feel were true.
Nothing else mattered to me except hearing
the laughter in your voice when you were
happy. You made my days easy to get
through and my nights peaceful; you helped
me look forward to another day. Even though
distance separated us, just being was
enough.

A: I’m sorry for hurting you and if I had to
do all over again I would have been 100%
with you. Forgive me please,

'''


== Elementary ‐ Daily Life ‐ Asking For A Loan (C0165)

B: Hello Sir may I help you?

A: Yes. I would like some information for
requesting a loan.

B: Very well, here are the general terms of
our loan policies. We pride ourselves in
having the lowest interest rate in the country
for personal loans.

A: I see. So let me get this straight. If I
borrow let’s say, ten thousand dollars, how
much will I have to pay each month?

B: It depends on how long you take to pay it
back. If we lend you ten thousand dollars at
an annual interest rate of ten percent for
forty eight months, you would have to pay
each month a portion of the loan which is
called the principal and another small portion
of the annual interest rate. This of course is
considering that you don’t default on a
payment!

A: It sounds good but, there is just one
problem. I have a terrible credit score.

B: That is a very serious problem you see,
the bank must assess your personal
information, past loans, assets and any other
relevant information such as your credit
score in order to approve your loan.

A: You know what? I don’t really need the
money. Thanks anyways!

'''


== Elementary ‐ Daily Life ‐ Dr. Botox (C0166)

A: What are you doing?

B: Look at me. I look so old! I look as if I
were thirty.

A: Come on! Stop being so vain. You look
great! You are beautiful!

B: Yes, I am, but I think it’s time for some
plastic surgery I’m tired of these wrinkles
and sagging skin. See?

A: I don’t see any wrinkles or sagging skin!
You are stop beings ridiculous. Besides, I
think that people who get Botox, have
facelifts, or tummy tucks look weird. It
doesn’t look natural.

B: Whatever, I think I’m gonna get
liposuction and a nose job and some breast
implants as well.

A: I think you need to get brain surgery. I
honestly don’t think you need cosmetic
surgery. You look amazing.
53
Englishpod Dialogues

B: I thought you were my friend and would
support me on this! I just want to feel better
about myself and feel more attractive.

A: You don’t need plastic surgery to do that.
You are fine the way you are and you have
guys drooling all over you! Plus, plastic
surgery hurts!

B: Really?

A: Yeah! When I got my nose job I was black
and blue for a week!

'''


== Elementary ‐ Daily Life ‐ Learning How To Drive (C0167)

A: Ok! I’m ready for my driving lesson!
Should I start the car?

B: Hold on there Fittipaldi, first let’s go over
things one more time. Now before you even
think of starting the car, make sure your seat
is at a comfortable position and you can grip
the steering wheel firmly. Next check your
rear view mirrors to make sure you can see
properly.

A: We have been through this a million
times! Let’s get going already! I’m ready!

B: Fine start the car. now gently step on the
clutch and shift to 1st gear. Good, now
accelerate gently and let go of the clutch as
u do it. There we gogood!

A: I’m doing it! I’m driving! This is awesome!
Le’ts turn some music on!

B: Keep your eyes on the road! No music!
We are coming up to a red light, step on the
brakes. What are you doing? I said the
brakes! Look out for those people! Get off
the sidewalk!

A: Get out of my way! This is just like
playing video games!

B: It’s the police! Pull over!

A: They’ll never take me alive!

'''

== Elementary  (C0168)



'''

== Elementary ‐ The Weekend ‐ Roller Coaster (C0169)

A: I’m so excited! We are finally here! Six
Flags Magic Mountain! This is the best
amusement park in the world!

B: Alright settle down now, you’re gonna
give yourself a heart attack.

C: I can’t believe they charged us dollars
each. It seems like a rip off don’t you think?
It’s not like I’m gonna get on these rides.

A: Whoa. . . Viper! That’s the world’s highest
and fastest roller coaster! You go at more
than miles per hour! I wanna go on that one!
Can I mom please? Can I ?

B: Chris I’m not sure you should get on that
it seems a bit too much for you and we just
had breakfast minutes ago. I don’t think it’s
a good idea.

A: Aww come on mom! I can handle it. I
promise I won’t ask for anything else!
Besides, it’s not like I’m gonna throw upor
anything. . .

C: Let him go Carol, he’ll be fine.

A: Alright! Yeah! This is amazing! See how
high up we’re going? Whoa. . . mmmf mmfff
barf.

'''


== Elementary ‐ Daily Life ‐ Wedding Doubts (C0170)

A: Man, I’m freaking out! You gotta help me!

B: Whoa whoa take it easy, relax. Geez,
you’re sweating like a pig! What’s going on?

A: I can’t go through with this! I just can’t!
I’m not ready for marriage! What was I
thinking? I’m only thirty five years old! I’ve
got my entire life ahead of me, adventures
waiting! I can’t settle down yet!

B: What are you talking about? It wasn’t
more than a month ago that you were
rambling on about how you are tired of living
the life of a bachelor and how you envy your
friends that have a family!

A: I know I know!

B: Let’s think this through. First of all, you
cannot leave Amy at the altar. Not only will
she be humiliated and kill you, but she is the
woman that you love andthe woman of your
dreams! Why would you want to end that or
jeopardize it like this? Second of all, you are
just getting cold feet. You know deep down
inside that you want to marry her, so cut the
crap and do it!

B: You’re right. I’m being crazy! Ok, I’m
54
Englishpod Dialogues
ready, lets do this!

A: Great! Phew! That was a close one ! You
had me going there for a minute I thought I
was gonna have to slap some sense into you

'''


== Elementary ‐ The Weekend ‐ Buying a Camera (C0171)

A: Hello, ma’am, can I help you find
something?

B: Yes, actually I’m looking to buy a camera.

A: We’ve got a wide selection do you know if
you’d like a point-and-shoot, or something a
little fancier? Are you shopping for yourself
or for someone else?

B: Actually I’m buying a camera for my
husband.

A: Ah, well then I’d recommend a nice entrylevel
digital SLR.

B: Yeah? Can I take a look at the SLRs you
carry?

A: Sure thing, follow me. This here is the.

B: The Canon Eos. Yeah it’s ok, but I’m
looking for something that performs better in
low light, has a better display panel, and
longer battery life.

A: Oh, ah, um the Nikon D60 is a nice
option.

B: Yeah, but what kit lens does this camera
come with? I don’t want some bulky
telephoto lens.

A: Oh, well this one has the, uh.

B: Looks to me like an 18-55mm lens. pretty
standard, that will do. Not like my husband
will be stalking celebrities or anything!

A: So, ahem, can I interest you in any acc...

B: Accessories? Do you carry polarizing
filters?

A: Polarizing filter um we should! I’m sorry,
ma’am. looks like we’re sold out.

B: No you’re not! There are some right here!

A: Oh, well, would you look at that! Po-la-rizing
filters.

B: Thanks for your help, Ralph!

A: No problem, ma’am.

'''


== Elementary ‐ Daily Life ‐ Dry Cleaners (C0172)

A: Thank god you are open! I have an
emergency!

B: Hello Mr. Henderson what can I do for
you?

A: I need this dress and this suit dry cleaned
ASAP!

B: OK, I can have it ready by the end ofthe
week.

A: No you don’t understand, I need this
tomorrow morning! I accidentally spilled beer
all over my wife’s dress and we have a
wedding to attend tomorrow! She’s gonna kill
me!

B: Ok, I can have it ready tomorrow
afternoon, but this suit is also very stained. I
can’t guarantee we can remove it completely.

A: Fine! Can you also iron and starch this
shirt?

B: Certainly.

A: Great! This is our secret! If you see my
wife, say nothing to her about this!

'''


== Elementary ‐ The Office ‐ Preparing a Budget (C0173)

A: Welcome Mr and Mrs Carnwell, please
take a seat.

B: Thank you.

A: So I understand that your family spending
has sky rocketed and you want to start
budgeting.

C: Yes that’s correct. Frankly speaking our
household income is relatively high and we
have never had any money problems, but I
think this is the main reason as to why our
spending has gone out of control.

B: We have two kids and with allowances,
paying their credit cards, ours and not to
mention our mortgage and car payments.
With the recent economic downturn, my
husband’s business has suffered and now we
need some advice as to how we can prepare
a family budget.

A: I see. Well you have come to the right
place. First what we need to do, is determine
your cash flow. Knowing how much money is
coming in will help us allocate spending to
different categories such as mortgage,
55
Englishpod Dialogues
education, groceries, etc.

B: Yes that makes sense.

A: Secondly, I need you to bring all of your
receipts for the last two to three months.
That way, we can determine what your
average expenditures are and see which
category you are spending money on the
most. Usually, your fixed costs are higher
and we can’t do much about that, but we can
usually trim your variable costs such as
entertainment or clothing.

C: Great! We will do that then! Now how
about we treat you to a nice dinner?

A: That’s another thing. If you really want to
stop spending so much money, throw away
at least half of your credit cards!

'''


== Elementary ‐ The Weekend ‐ Getting a manicure (C0174)

A: Honey I’ll be right back!

B: Where are you going?

A: I told you already! I’m going to get my
nails done.

B: Again? You just went last week! You
spend more time atthe nail salon than you do
here at home! Honestly, why do you need a
manicure every week?

A: Well, first of all, I like to pamper myself,
and my nails look great. You should come
with me!

B: Why? I don’t want to have nail polish or
anything like that!

A: They don’t only paint my nails! The
manicurist will remove my cuticles, file my
nails, and apply at least nails coats of nail
polish!

B: Yeah, sounds like something I should
definitely do.

'''


== Elementary‐ Global View ‐ New Years Resolution (C0175)

A: Did you read this? It says that the number
one new years resolution make is to spend
more time with friends and family.

B: Why would that be funny?

A: Well, think about it. We are a society that
is always on the go, not because we have to,
but because we want to.

B: Why?

A: We work hard and spend less time at
home because we are trying to provide for
our family with goods and services that are
usually unnecessary.

B: I don’t agree, but anyways, I think you
should start thinking of a new year’s
resolution yourself.

A: What’s the point? We always make a new
year’s resolution and by February we will
have forgotten about it. It’s pointless.

B: Well then maybe you should resolve to
sticking to your goals and objectives.

A: What about you? Your gym bag is
gathering dust and you still have brand new
running shoes that are yet to be jogged in.

B: Well, I would go if you kept your promise
of going to the gym with me everyday!

A: Yeah yeah whatever.

'''


== Elementary ‐ Daily Life ‐ Heating (C0176)

A: It’s freezing in here! Can I turn up the
heat?

B: Don’t touch that thermostat! You don’t
pay the bills around here!

A: Dad! Are you serious? What’s the point of
having central heating if we can’t use it!
Look, I can see my breath!

B: Put on a sweater! I’m not gonna let you
run up my heating bill just because it’s a bit
chilly.

A: Dad! I’m gonna catch a cold!

B: When I was your age, my parents didn’t
have central heating like you do! We had a
furnace in the center of the living room and
that was it. We used it to cook, heat the
house and even dry our clothes! We never
caught a cold. You should be grateful!

'''

== The Weekend ‐ Decorating a Christmas Tree (C0177)
HUSBAND: I’m home! Everyone come here!
I bought a Christmas tree! Look at this
56
Englishpod Dialogues
beautiful pine tree!
WIFE: Wow, it’s huge! Are you sure it will fit
inthe living room?
KID: Awesome! I’ll go getthe Christmas
lights!
HUSBAND: Of course it will. help me put it
in the living room.
KID: I found the lights!
WIFE: I got the Christmas ornaments! We
could also place these stockings next to the
chimney.
HUSBAND: Great idea! While we decorate
the tree, we can listen to some good old
Christmas songs!

'''


== Elementary‐Daily Life‐ Finding the perfect present (C0178)

A: Bill. Bill! You gotta help me!

B: What’s wrong? Slow down or you are
gonna give yourself a heart attack.

A: Tomorrow is Christmas and I haven’t
bought my mom anything! I’m such a bad
son!

B: Take it easy! Let’s go to the mall, window
shop a little and see if there is anything she
might like.

A: That’s just it! I don’t know what to get
her! Last year I got her a ring that was two
sizes too big and a pair of shoes five sizes
too small! I suck at getting presents for
people.

B: That’s where you’re making a big mistake!
You can’t just guess peoples’ likes or sizes!
Especially with clothes or jewelry. On top of
that, I think that you should get your mom
something that shows how much you love
her. At the same time you should show her
that you took the time and effort to look for
something that she would really like!

A: Yeah you’re right. When it comes down to
it, I can be pretty tacky.

B: Yeah tell me about it. I know! Your mom
is trying to learn Spanish right? Why don’t
you get her a gift certificate for this great
website I saw called SpanishPod.

A: Now that’s a great idea!

'''


== Elementary ‐Intermediate ‐ Silent Night(C0179)

A: Silent night, holy night

A: All is calm, all is bright

A: Round yon Virgin Mother and Child

A: Holy Infant so tender and mild

A: Sleep in heavenly peace

A: Sleep in heavenly peace

A: Silent night, holy night

A: Shepherds quake at the sight

A: Glories stream from heaven afar

A: Heavenly hosts sing Alleluia!

A: Christ, the Saviour is born

A: Christ, the Saviour is born

A: Silent night, holy night

A: Son of God, love’s pure light

A: Radiant beams from Thy holy face

A: With the dawn of redeeming grace

A: Jesus, Lord, at Thy birth

A: Jesus, Lord, at Thy birth

'''


== Elementary ‐ Jingle Bells (B0180)

A: Dashing through the snow

A: In a one horse open sleigh

A: O’er the fields we go

A: Laughing all the way

A: Bells on bob tails ring

A: Making spirits bright

A: What fun it is to laugh and sing

A: A sleighing song tonight

A: Oh, jingle bells, jingle bells

A: Jingle all the way

A: Oh, what fun it is to ride

A: In a one horse open sleigh

A: jingle bells, jingle bells

A: Jingle all the way

A: Oh, what fun it is to ride

A: In a one horse open sleigh

A: Dad, dad, dad! Wake up! It’s Christmas!

B: Timmy. It’s too early for this. Look, it’s six
in the morning! Go back to bed!

A: No way! Santa already came and left all
our presents! Can we go open them? Please!
Please!

C: Of course we can honey. Bill, come on, get
dressed.
57
Englishpod Dialogues

B: Fine! Not like Santa brought me any gifts!

C: Bill! Honestly, you can be such a grouch
sometimes.

A: Look at all these presents under the
Christmas tree! Awesome!

B: Alright Timmy, knock yourself out. We
should get ready and head to the market to
buy everything for the Christmas dinner
tonight.

C: Yeah you’re right. It’s the first time we are
hosting Christmas dinner at our house so
everything has to be perfect.

B: I got the list right here. Ham, turkey,
mashed potatoes, ingredients for the gravy
and of course, yams!

C: My dad offered to bring the eggnog so we
should be set!

'''


