
= english pod 301-320
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''



== The Weekend ‐ Vampires (C0301)

A: You want to go tothe movies tonight?

B: Sure! What’s playing?

A: The new Twilight movie!

B: Twilight? As inthe vampire movies? No
way I am watching that. I don’t understand
why everyone isso excited about these films
about vampires. It doesn’t make sense.

A: Of course it does. It’s like a modern tale
of Romeo and Juliet. You have a couple that
101
Englishpod Dialogues
is in love but can’t be together because they
are so different. Add in the fact that
immortality and super human strengthis
really sexy and there you have it! Plus the
cast is hip, young people that make the
movie even more enticing.

B: I don’t buy into that. I think it’s just a fad.
Pretty soon this will pass and everyone will
be into werewolves or zombies!




'''

== Global View ‐ Phobias (C0302)

A: Are you excited about your trip next
month?

B: Yes and no. I can’t wait to go to Europe,
but at the same time I am terrified.

A: Why?

B: Well, I have aerophobia. I have a chronic
fear of flying.

A: Oh really? I have an uncle who is also
terrified of flying. It’s not that bad though, I
mean, it is pretty scary to be in this big
machine flying through the air at seven
hundred miles per hour. I actually have
arachnophobia.

B: You’re scared of spiders? I actually have
two more phobias. Acrophobia and
glossophobia.

A: I guess that explains why you are afraid
of flying, but public speaking is not that bad.

B: Are you kidding? When I get on stage, my
palms start to sweat, I get really nervous
and I can hardly speak.

A: Well, I must confess I am a bit
claustrophobic. I hate being in an elevator
for more than 5 seconds.

B: We are such weirdos right?




'''

== Daily Life ‐ Mexican Food (C0303)

A: Hello sir, welcome to Pistolera restaurant.
May I take your order?

B: Yes, I would like the chicken cheese
enchiladas with a side of guacamole.

A: I’m sorry sir, but we ran out of chicken.
May I suggest our delicious beef burritos or
cheese quesadillas? Both include a side of
guacamole and jalapenos.

B: Sure I’ll have the burrito.. Do you have
nachos?

A: Of course sir. Our nachos come with
melted cheese and chili.

B: Sounds good.

A: Would you like anything to drink?

B: Sure, I’ll have a Corona.




'''

== Daily Life ‐ Neat Freak (C0304)

A: Ugg, this bathroom is a pigsty!

B: Helen, why do you keep flushing the
toilet? What’s wrong?

A: I just can’t stand it. It’s really gross in
here! There’s a stain on the toilet seat, and
the floor was wet and slippery. So I cleaned
it!

B: You did what? Helen, I know it’s gross,
but I’ve seen many public washrooms that
are much worse. Why are you cleaning the
counter top? are you out of your mind?

A: I can’t help myself; it’s just so disgusting
in here!

B: Helen, this is not like your own bathroom.
Just leave it to the cleaners,okay?

A: Hang on. I’m just gonna quickly wipe the
sink and sweep the floor.

B: You’re such a neat freak! I’m outta here!




'''

== The Weekend ‐ Bowling (C0305)

A: Alright, so the first thing that you need to
know about bowling is that you should never
cross that line where the lane begins.

B: Why not?

A: Because they polish and oil it to make the
ball slide down. If you step there you will slip
and fall.

A: OK, so I got my bowling shoes, my ball,
our names on the scorecard, so now, how
the heck do I play this?

A: You throw the ball down the lane and try
to knock down all the pins. If you do, that is
called a strike. If you don’t knock them all
down on the first try, then you get a chance
to get the spare. After ten frames, we add up
the points and see who has the most. Three
hundred is a perfect score, but very hard to
102
Englishpod Dialogues
get.

B: Got it! OK, I’m gonna give it a go. Oh no!
My ball went in the gutter!

A: I told you, its harder than you think. Now
let a pro show you how it’s done.




'''

== The Weekend ‐ Pick Up Lines (C0306)

A: Let’s got out tomorrow night. We can go
to a bar and try to find you a girlfriend.

B: I don’t think that’s a good idea. I am just
not good with approaching someone and
starting up a conversation.

A: Maybe you just need a few pick up
lines,you know, break the ice.

B: Pick up lines don’t work!

A: Come on! You can just walk up to a girl
and say: “If you were a booger I’d pick you
first.”

B: What? Come on! That’s just lame! No girl
would fall for that!

A: Fine, then you can say: “So there you
are! I’ve been looking all over for YOU, the
woman of my dreams!”

B: That’s a good one! I think that’s pretty
funny.

A: Yeah, so you make her laugh, you make a
fool of yourself a little bit and then you buy
her a drink.

B: Ok, how does this sound: “I was so
enchanted by your beauty that I ran into that
wall over there. So I am going to need your
name and number for insurance purposes.”

A: Nice! Let’s go!




'''

== The Office ‐ Small Talk Series ‐ Showing Interest (C0307)
Tina: Hey Michelle, this is my friend James.
He’s visiting Shanghai from New York.
Michelle: Oh, hi James. Nice to meet you.
So, uh. you visiting for business or pleasure?
James: Well, actually a little of both. I’m
meeting some business contacts but I’m also
taking some Mandarin classes too.
Michelle: That’s cool! How’s it going?
James: Well, I’m finding the classes pretty
tough actually, but I’m having a great time in
Shanghai. It’s really an amazing city.
Michelle: It sure is. Are you staying for
long?
James: Only two weeks unfortunately. I wish
I could stay longer but.
Michelle: Well listen, if you need someone
to show youthe sights then just call me. I’m
having a little get together at my new
apartment next week so if you want to drop
bythen.
James: That sounds great. I’d love to! Let
me take down your number Michelle.




'''

== Daily Life ‐ Boxers and Briefs (C0308)

A: Lily, I found a pair of men’s boxers in the
laundry machine this morning!

B: What?! That’s weird. Are they your
boyfriend’s?

A: Nah, Kevin only wears briefs. Plus, this
pair is extra small!

B: What do they look like?

A: They’re light blue with thin pink stripes...
Oh, and there’s a Snoopy on it which is
hilarious, hahah...

B: Those are my undies!




'''

== Global View ‐ Indian Food (C0309)

A: So where is this mystery restaurant that
we are going to?

B: It’s an Indian restaurant! I know you have
never had Indian food, so I thought you
might want to try.

A: That sounds great! I am craving some
type of beef dish.

B: Well, Indian cuisine actually doesn’t serve
beef. You see, cows are a sacred animal, a
very important element inthe Hindu religion,
so beef is not eaten.

A: I see, so what are we having? Chicken?

B: There are many amazing dishes to choose
from. We can havesome chicken tikka
masalawhich is an amazing curry. It’s a bit
spicy, but I think you can handle it.

A: Sounds good! I have always heard that
103
Englishpod Dialogues
Indian spices give a rich flavor to food.

B: Yeah. Also, we can have some Naan bread
which is baked in a tandoori oven. Since you
don’t use any utensils to eat, you can use
this bread to scoop upthe curry or rice.

A: What about veggies?

B: They have a good variety of vegetable
based dishes like palak paneer, vegetable
samosas or Daal.

A: It all sounds exquisite! I can’t wait!




'''

== The Office ‐ Small Talk 2 (C0310)

James: So Michelle, let me introduce you to
Maria. She’s my colleague from Brazil. Maria,
this is Michelle.
Maria: Hi Michelle. So what do you do here
in Shanghai? I mean, what work do you do?
Michelle: I work in advertising right now.
How about you?
Maria: I’m actually inthe wine business.
Michelle: That sounds really great. I love
wine myself! Is this your first time to
Shanghai Maria?
Maria: No actually, I often visit. I usually
come to China for business at least once a
year. Also, I love the restaurants in
Shanghai, so that’s a good reason to come.
Michelle: Me too. Actually, there’s a great
Brazilian restaurant I recommend. I mean,
the food is delicious butthe service isn’t so
good. I often like to get together with friends
and have a great barbecue there.
James: We should go together some time.
Michelle: Wonderful idea! I’d love that!




'''

== The Office ‐ Sorry I’m Late (C0311)
Maggie Gao: Okay everyone, shall we
begin?
Bill: Sorry Maggie, but we are missing a few
people. Can we hang on a sec?
Maggie Gao: Well, I did say eleven o’clock
sharp, and it’s now five past so. . . .
James: Hi everyone, I’m so sorry I’m late.
It’s raining cats and dogs outside and I had
to wait ages for a taxi.
Maggie Gao: Okay James, take a seat
quickly please. Right, the subject ofthe
meeting is.
Sally: Hi guys. Please excuse me ,I was held
up in traffic.
Maggie Gao: Right, as I was saying the
subject ofthe m. . .
Bruno: Hi Maggie. I’m terribly sorry. The
traffic is murder out there.
Maggie Gao: Sit down Bruno! Okay now, as
you are aware, the topic for this meeting is
‘The importance of being punctual’. Who
would like to start?




'''

== The Weekend ‐ Ordering Drinks (C0312)

A: What Can I get you?

B: I’ll have a Cosmo please.

C: Dude! You can’t order a Cosmo! That’s a
ladies drink, you’re embarrasing me!

B: What are you talking about? It’s a good
drink!

C: It’s too soft! Order something with a little
more kick to it!

B: Fine! I’ll have a sex on the beach.

C: You have to be kidding me!

B: Come on! It’s delicious! Especially when
served in a pineapple or coconut.

C: Forget it, I’m ordering for you. I’ll have a
Scotch on the rocks and my friend here will
have a Manhattan. Put it on my tab. Here
now this is a real drink!

B: That’s strong! This is going to get me
wasted!

C: That’s the idea!




'''

== The Office ‐ Small talk 3 (C0313)
Grace: Hey Michelle! Is that you?
Michelle: Wow, Grace! Long time no see!
Where have you been?
Grace: Oh yeah. Well you see I got a
promotion, so I moved tothe new Pudong
office last September.
Michelle: You did? Congratulations!
Grace: Thanks a lot. So how are things with
you Michelle?
Michelle: Well, same old same oldyou know.
Nothing much has changed here.
104
Englishpod Dialogues
Grace: Are you still seeing Chris?
Michelle: No, actually we split up last
month.
Grace: Oh dear. I’m sorry to hear that.
Michelle: But I met a really cute guy last
night at a networking party so, . . . .....well,
let’s just wait and see......
Grace: Good for you Michelle!




'''

== Daily Life ‐ Making A Collect Call (C0314)

A: This isthe operator, how may I help you?

B: Yes, I would like to make a collect call.

A: Ok sir, please dial the number. Now please
state your name.

B: Tommy.

A: Please wait a moment. Hello, you have a
collect call from Tommy. Would you like to
accept the charges?

C: Yes of course.

A: Dad?

C: Yeah Tommy, what happened are you ok?

A: Yeah dad everything is ok. I’m calling you
because I want to know if it’s ok for me to go
to my friend’s house today after school.

C: Yeah sure no problem. You scared me to
death! I’ve told you to make a collect call in
case of an emergency only! Why didn’t you
call me from your mobile phone?

B: I ran out of credit and I also didn’t have
twenty five cents N forthe payphone. Sorry
dad.




'''

== The Office ‐ Sending A Quote Via Email (C0315)
Tracy: Melanie, can you help me with
something? We need to finalize the account
with the Mexican Embassy and, I need some
advice on phrasing this letter correctly in
English.
Melanie: Sure Tracy, let me just get my
laptop. all set. Tracy: Okay, so. . . . . . .
toWhom It May Concern, I am writing.
Melanie: Um, Tracy? I think that’s a little too
formal. I know you want to be polite but
you’ve already made contact with them, so in
English you can be more relaxed inthe
opening. . . .
Tracy: Okay, more relaxed. Got it. . . . Hey
Sally, what’s up? It’s Tracy here, just.
Melanie: Okay Tracy, now it’s too relaxed!
You’ve still got to show some respect. How
about starting with “Dear Ms. Cooper, I’m
writing to confirm. . . ?
Tracy: Great, okay. “Dear Miss Cooper, I’m
writing to confirm the final quotation forthe
full page back cover color advertisement you
requested forthe spring issue of Voila
magazine.
Melanie: That’s great. . . .
Tracy: “ The final costing, including advert
design and production, comes to forty-five
thousand six hundred RMB. We want
payment ten working days before publication
or we will cancel the ad. Thanks for. . . ”
Melanie: Woo, okay back up a second Tracy.
That’s too direct. Can I suggest you say, ”
please note thatfinal payment is due two
working weeks before publication? You don’t
want to offend her.
Tracy: Oops okay. You are right. Then I can
just end with “All the best, Tracy”
Melanie: Hmmmm, maybe, but I’d play it
safeand just finish with “Yours Sincerely”.
That’s more professional.
Tracy: Oh, Melanie you are a life saver,
thank you!




'''

== Daily Life ‐ Small Talk Series 4 ‐ Discussing Recent Workevents (C0316)
Jeremy: Hi Michelle. Do you need to usethe
photocopier?
Michelle: Oh hi Jeremy. No please, go
ahead. So how are you Jeremy? I was talking
to Linda about you only last week.
Jeremy: Oh I’m fine thanks. I’m super busy
with work actually. Did you hear about the
Lawson contract?
Michelle: No, tell me more.
Jeremy: Well, I was discussing the contract
with Bill and he said that they metthe head
105
Englishpod Dialogues
of Lawsons last week.
Michelle: And.
Jeremy: And hopefully they are going to
confirm the deal on Wednesday, fingers
crossed
Michelle: That’s great news Jeremy.
Congratulations! Anyway, I must get back,
but give my regards to your wife Monica.
Jeremy: I will Michelle. Speak to you soon.




'''

== The Office ‐ First Paycheck (C0317)
Emily: Hey, Susan. Have you got a sec? I
have some questions about my paycheck.
Susan: You bet, Emily. Pull up a chair.
Emily: Well, this is my first paycheck here
inthe States and there are a few things I
don’t understand. First off, what is this FICA,
and SUI Y tax, and why are there deductions
both for Medicare and for my health
insurance plan?
Susan: OK, let’s start from the top of your
pay stub. This number here represents your
gross pay.
Emily: Yes, that’s easy enough to
understand.
Susan: Then here we have a series of
deductions. First off are the federal ones.
FICA stands for Federal Insurance
Contribution Act, or something like that. It’s
your federal income tax. And then there’s
Social Security and Medicare, which are both
federal programs to help you out after you
retire or if you were unable to work.
Emily: All right, I see. So the Medicare isn’t
actually a health insurance I can use now.
Susan: That’s right. Below the federal
deductions are the state deductions. There’s
the state income tax, and then this SUI
SDItax you were asking about is paying into
an unemployment and disability fund that
our state has set up, but you can see it’s a
pretty small quantity that they take.
Emily: Yeah, I don’t mind giving them a
dollar fifty for that. So there are two
separate income taxes – one at a state level
and one at a federal level?
Susan: That’s right. Not all states have an
income tax. Some use higher property taxes
or sales taxes instead.
Emily: I see. All right, well I think everything
else I can figure out on my own. The
deductions for health insurance and my
401(K) are pretty self-explanatory. Thanks
for your help, Susan.
Susan: No problem! All those deductions do
add up, and nobody’s net pay is as high as
they’d like. I can understand why you’d want
some explanation.
Emily: Yeah, I guess it’s the same in the UK,
I just never paid much attention. See you
later!




'''

== Global View ‐ Allergies (C0318)
Jim: Argh...I feel terrible, I keep sneezing
and my eyes are all watery, what’s wrong
with me?
Tom: Wow, you’re not dying are you, it looks
like you have a cold, you should take some
medicine.
Jim: I don’t think it’s a cold, I feel fine if I
move a few feet away from my desk.
Tom: Maybe we should put you into
quarantine ha ha, jokes aside, I think you
might have an allergy.
Jim: An allergy? I never thought about that,
I don’t think I’m allergic to pollen though and
I’m desensitized to bee stings after being
stung so many times, Hmm.. .
Jim: Ow! Why did you chuck that peanut at
me? Tom: Just checking if you’re allergic to
peanuts, I guess not.
Jim: Not funny! I could have gone into
Anaphylactic Shock.
Tom: Okay my bad, how about dust? This
office is full of it.
Jim: Yes the whole is office is dusty yet I
only feel affected near our desks!
Cat: Meow meow meow
Jim: You brought your cat into the office?!
Tom: Yes, it’s Mr Snuffle’s birthday today, I
didn’t want him to be alone on his special
day!
Jim: ACHOO! Argh put it away ACHOO!
Tom: I guess we found the problem, your
106
Englishpod Dialogues
allergic to cats!




'''

== Daily Life ‐ Small Talk 5 ‐ Brief Talk With A Stranger (C0319)

Older gentle- man: Oh dear Miss, you are
soaked! Wow, it’s really raining heavily
outside.
Michelle: Yes, it sure is. I had to run here
from work! I need to rush as I’m on my
lunch break.
Older gentle- man: ell please, why don’t
you go ahead of
me in line? I’m in no hurry.
Michelle: Oh, that’s so nice of you! Thank
you very much.
Older gentle- man: My pleasure Miss.
Actually, could you recommend what to eat
here? I’ve never been here before.
Michelle: Sure. Well, the avocado sandwich
is delicious, and it’s the healthiest thing on
the menu. Personally, I think the beef salad
is the tastiest choice. I usually get that. Also,
the milkshakes are the best milkshakes in
town!
Older gentle- man: Well, thanks for the
suggestions. Michelle: Oh, don’t mention it.




'''

== Global View ‐ Taking The GMAT (C0320)

Ash: I can’t seem to progress up the career
ladder no matter how hard I try and I have
been here for 2 years already!
Mindy: Well, have you thought of getting an
MBA? I heard it does wonders in getting you
to the top.
Ash: An MBA hey. . . well my degree wasn’t
in business, the business schools won’t be
interested in me.
Mindy: Nonsense! The business schools
measure your ability through a test called
GMAT.
Ash: GMAT? What does that stand for and
what will the test contain?
Mindy: Graduate Management Admission
Test, it contains three parts; Analytical
Writing Assessment, the Quantitative section,
and the Verbal section. Not only does the
test mark you on the number of questions
answered but also on the difficulty.
Ash: Okay this sounds a little tough, how am
I supposed to practice for this?
Mindy: Up to you, you could have a one on
one session with a tutor or group sessions,
you can also use free or private computer
software. Going to church might help as well!
Ash: No matter what I do I’m going to ace
this test and go on to become a corporate fat
cat!
Mindy: Umm.. . That’s the spirit!




'''
