
= english pod 361-365
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''





== Daily Life - Fast Food (C0361)

A: I’m hungry, let’s order up something to
eat.

B: Ok, maybe we can order a soup and a
salad from the restaurant down the street.

A: I was thinking of getting a hamburger,
fries and a chocolate sundae.

B: You eat too much junk food. That sort of
stuff clogs up your arteries and is very high
in cholesterol.

A: Well I never seem to gain weight so I
don’t mind.

B: It’s not only about getting fat or not, it’s
about being healthy. You could really have
some health problems later on.

A: How about pizza or maybe some fried
chicken!
Better yet, let’s order some hot dogs!

B: You are a lost cause.


'''

== Daily Life - What Mood Are You In? (C0362)

A: Are you ok? You seem a bit anxious.

B: Yeah I’m OK, I have been having a lot of
mood swings lately. I think it has to do with
the pills my doctor prescribed that are
causing chaos on my hormones.

A: So you mean you feel ecstatic one minute
and then blue the next?

B: Yeah, it’s weird. For example just this
morning
I was feeling detached and lonely, even
though there was really no reason to feel
that way.

A: Well, maybe your mood will swing
positively and you will feel confident, brave
and hopeful!

B: I hope you are right.


'''

== Daily Life - Living With Your Parents (C0363)

A: Why did your girlfriend break up with you?

B: I don’t know, she said she was tired of me
not manning up and being more
independent, which I think is all a bunch of
crap.

A: Well, you still live with your parents, so
she does have a point.

B: What do you mean? Lots of people live
with their parents, especially when rent is so
expensive and the slump in the economy.

A: Yeah, but you are almost forty! Plus, you
make good money so there is really no
excuse. It’s simply because you are a
momma’s boy.

B: Whatever dude, I have everything I need,
why would I move out! Have a great roof
over my head, my mom does my laundry
and cooks for me, what else could a guy ask
for!

A: Let’s agree to disagree.


'''

== Daily Life - Hiring Help (C0364)

A: Can you help me write a newspaper ad?

B: Sure, what are you looking to buy or sell?

A: Actually, I want to hire someone to help
me around the house.

B: Oh, you want to get a maid?

A: Well, I think it’s better if you call her a
cleaning lady or domestic help.

B: Ok, so what do you want her to do?

A: Well, let’s see. I want her to come in three
times a week for a couple of hours to clean
the kitchen, bathroom and maybe do some
cooking.

B: Got it. And how much do you offer per
month?

A: I would pay her hourly, I don’t know what
the going rate is though.

B: I know for sure it’s more than minimum
wage but maybe you should just negotiate
119
Englishpod Dialogues
with the person that answers the ad.

A: Great! Thanks for your help!


'''

== Daily Life - Household Chores (C0365)

A: Kevin, what is this mess? It looks like a
pigsty in here! Clean this up!

B: Ok dad, I will do it in a minute, let me just
finish this level of this game.

A: No, I said now! Plus, you are grounded,
you’re not allowed to play video games. I
want you to make your bed, do the laundry
and then come downstairs and sweep the
floors.

B: That’s so unfair!

A: You have to pull your weight around here
young man. My house, my rules.

B: But I already mopped the floors, dusted
the furniture and vacuumed the rugs!

A: That’s great, but you still have work to do,
so get to it.


'''