= 0865
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 865: Believing in Predictions.
This is English as a Second Language Podcast episode 865. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there today and become a member of ESL Podcast. It will help support this podcast and improve your English, because you will be able to download a Learning Guide as a member.
This episode is a dialog between Armond and Patricia about believing in people who say they can predict the future. Let’s get started.
[start of dialog]
Armond: I hope that this new year will bring me better luck.
Patricia: You can find that out easily enough. My astrologer says...
Armond: Hold on. You consult an astrologer? You really believe in that nonsense?
Patricia: It’s not nonsense and, yes, I believe in it. I like getting predictions about the future and knowing what is in the stars for me.
Armond: Astrologers are charlatans and what they tell their customers is phony. They make it all up and tell people what they want to hear.
Patricia: I don’t know how you can say that. The horoscope for my sign each day gives me warnings and helps me avoid mistakes. And when I have big decisions to make, I go for a reading. The guidance I get is invaluable.
Armond: You’re too smart to be taken in by con artists who style themselves as mystics. It’s all smoke and mirrors.
Patricia: You’re wrong. I’ll give you an example. My horoscope today said that an unpleasant person will try to shake my beliefs. It said I should just walk away.
Armond: Hey, where are you going?
[end of dialog]
Armond begins our dialog by saying “I hope that this new year will bring me better luck.” He hopes that good things will happen to him this year. Patricia says, “You can find that out easily enough,” meaning it’s very simple. It’s very easy to get that answer. “You can find that out easily enough,” she says. “My astrologer says…” An “astrologer” (astrologer) is a person who studies the movements of the planets and the stars in the belief that somehow that will help him understand people and be able to predict events in the future.
Astrology has been around for thousands of years. People have always believed somehow that what is up in the sky somehow controls what happens here on earth and apparently, there are still people today who believe such a thing. Armond says, “Hold on. You consult an astrologer?” “To consult” (consult) here means to get someone’s advice about something, to seek someone’s guidance, to get their suggestions. In this case, it means to talk to an astrologer and ask that person what the future will bring you – what will happen in your future.
Armond says, “You really believe in that nonsense?” “Nonsense” is something that isn’t logical. It is not rational. You shouldn’t take it seriously. It makes no sense. Patricia says, “It’s not nonsense and yes, I believe in it. I like getting predictions about the future.” A “prediction” is a guess about what will happen in the future. Tomorrow it will rain. I predict that it will rain tomorrow. That’s what I think will happen.
Patricia likes getting predictions about the future which – in a way, you don’t really need to say about the “future” because a prediction is always about something that will happen in the future. But she says she likes getting predictions about the future and “knowing what is in the starts for me.” “In the stars” here means what is meant to happen in the future. Once again, the idea is somehow that the stars and the planets are controlling our lives.
Armond says, “Astrologers are charlatans and what they tell their customers is phony.” A “charlatan” (charlatan) is someone who pretends to be very intelligent, who says they know a lot about something but is actually not. A charlatan is someone who lies in order to make you think that they know something. There are lots of charlatans on the Internet, for example, about almost every topic.
Armond says that astrologers are charlatans and what they tell their customers – the people who pay them money – is “phony” (phony). “Phony” is fake, not real, false, not true. “They make it all up.” “To make something all up” is to invent it, to say something as if it were true when you really don’t have any idea whether it is true or not. The astrologers make it all up and tell people what they want to hear. Patricia says, “I don’t know how you can say that,” meaning I don’t understand why you are talking that way or saying those things.
“The horoscope for my sign each day gives me warnings and helps me avoid mistakes.” A “horoscope” (horoscope) is a prediction or a description of what will happen to someone on a particular day and what they should do about it. Horoscopes are based on or are determined, according to astrologers, by when your birthday is and what the position of the stars and the planets are. It’s a type of astrology. A lot of people like to read their horoscope for their particular sign. Your “sign” refers to the 12 parts of what is called the “zodiac” (zodiac). Supposedly, this is an area where the stars and the planets travel and they’re associated with a name and a symbol.
The calendar is divided up into 12 signs. Most people know their astrological sign even if they don’t believe in it. I was born in September and so I’m – late September – and so I’m a Libra. And then if you were born in a different month, you would be something else, one of the other 12 signs of the zodiac. This again is part of this whole belief that somehow the stars and the planets control us. Some people read their horoscopes just for fun. Most horoscopes are written so generally that they could probably be applied or it would probably be true for almost anyone.
Patricia says, “When I have big decisions to make, I go for a reading.” A “reading” here means you go to this person, this astrologer, in this case, who will then predict what your future will be. Maybe they’ll look at your hands, your palms. Maybe they’ll look at some special cards. Maybe they’ll look at something else that’s supposed to help them predict what your future will be. Patricia says when she has a big decision to make, she goes for a reading. She goes to her astrologer. “The guidance I get” – the suggestions that she receives – “is invaluable,” meaning it’s worth a lot. It’s extremely valuable. It’s impossible to say how much because it is so valuable to you, so worthwhile to you.
Armond says, “You’re too smart” – you’re too intelligent – “to be taken in by con artists who style themselves as mystics.” Couple of different expressions there – “to be taken in” means to be tricked or to be fooled by someone, for someone to lie to you and for you to believe it. That’s to be taken in. A “con artist” is a person who does something to trick you out of your money, to fool you into giving him your money. “Con” is short for “confidence,” basically, trust that you have in that person, that that person is able to get you to give them. That’s what a con artist does.
Armond says that Patricia is too smart to be taken in by con artists who style themselves as mystics. “To style (style) yourself as something” means to present yourself in a certain way, to pretend that you are something that you really aren’t. In this case, the con artists are styling themselves as mystics. A “mystic” (mystic) is a person who is very spiritual, who seems to have a close relationship with God and is somehow closer to the truth than other people. Armond says, “It’s all smoke and mirrors.” The phrase “smoke (smoke) and mirrors (mirrors)” is used to describe a situation where what appears to be happening is not actually happening. The idea is that you are being fooled. You are being tricked. You are being lied to. A person is doing something to make you believe something that isn’t true. “It’s all smoke and mirrors,” Armond says.
Patricia says, “You’re wrong. I’ll give you an example. My horoscope today says that an unpleasant person” – someone who’s not very nice – “will try to shake my beliefs” – to shake my confidence in my beliefs. “To shake (shake) someone’s confidence in their beliefs,” or “to shake someone’s beliefs,” we might say, means to make another person doubt what they previously had believed, to make them less certain about something. Patricia says that her horoscope told her that she should “walk away,” meaning she should leave when she finds or meets this unpleasant person. Of course, what does she do? She turns around and leaves. Armond says, “Hey, where are you going?” – indicating to us that Patricia is walking away from Armond because that’s what her horoscope told her to do.
Now let’s listen to the dialog this time at a normal speed.
[start of dialog]
Armond: I hope that this new year will bring me better luck.
Patricia: You can find that out easily enough. My astrologer says...
Armond: Hold on. You consult an astrologer? You really believe in that nonsense?
Patricia: It’s not nonsense and, yes, I believe in it. I like getting predictions about the future and knowing what is in the stars for me.
Armond: Astrologers are charlatans and what they tell their customers is phony. They make it all up and tell people what they want to hear.
Patricia: I don’t know how you can say that. The horoscope for my sign each day gives me warnings and helps me avoid mistakes. And when I have big decisions to make, I go for a reading. The guidance I get is invaluable.
Armond: You’re too smart to be taken in by con artists who style themselves as mystics. It’s all smoke and mirrors.
Patricia: You’re wrong. I’ll give you an example. My horoscope today said that an unpleasant person will try to shake my beliefs. It said I should just walk away.
Armond: Hey, where are you going?
[end of dialog]
Her scripts are invaluable to us here at ESL Podcast. I speak of our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again, right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
astrologer – a person who studies the movements of the planets and stars to understand people and/or predict the future and provide advice
* Heather’s astrologer explained that 2014 would be a difficult year for her professionally, given the location of Mars and Saturn.
to consult – to speak with someone to ask for and receive advice or guidance
* Let’s consult with the engineering team before we continue working on these designs.
nonsense – something that does not make any sense; something that is illogical or irrational; something that is silly and cannot be taken seriously
* Many self-help books are nonsense, but some have good advice.
prediction – a statement about what will happen in the future, or what one believes will happen in the future, when it is impossible to know for sure
* A lot of people made predictions about who would win the presidential election, but many of them were wrong.
in the stars – fated; related to one’s destiny; something that is meant to happen in the future and cannot be changed by one’s actions or decisions
* When Justin met Charlene, he knew that she would become his wife. To him, it felt like it was written in the stars.
charlatan – someone who pretends to be very intelligent or skillful and claims to be able to do something, but actually is not and cannot
* That doctor is a charlatan! His diagnosis was completely wrong and I doubt he even went to medical school!
phony – fake; not real or true; false
* Did Lyle really propose to his girlfriend with a phony diamond ring?
to make (something) all up – to say something as if it is true, when one really does not have any proof and has thought of it oneself, without any supporting facts
* Do you think people have really seen aliens, or are they just making it all up?
horoscope – a written description of one’s personality, what will happen to someone on a particular day, and how one should react, based on one’s birthday and the position of the stars and planets
* According to my horoscope, today is a good day to make major decisions.
sign – zodiac; one of 12 parts of the area where the stars and planets travel, each associated with a name and a symbol, and with certain characteristics
* Richard was born on June 15, so his sign is Gemini.
reading – the act of having one person predict another person’s future based on looking at that person’s palm (the inside of one’s hand), tea leaves, “tarot cards” (playing cards used to predict the future), and more
* When Miriam was having trouble deciding whether she wanted to move to a new city, she decided to have a reading.
invaluable – extremely valuable; impossible to put a price on something because it is worth so much
* A good letter of recommendation from a former professor is invaluable when you’re applying to law school.
to be taken in – to be tricked or fooled; for someone to somehow lie to another person, usually in order to make money
* Hundreds of people were taken in by the email fraud that provided their credit card information to thieves.
con artist – a person who tricks other people to get money from them
* Edgar dated a woman who disappeared one day with his most valuable possessions and later he found out that she was a con artist.
to style (oneself) – to present oneself a certain way; to pretend that one is something one is not
* Kristoff styles himself as an experienced businessman, but the truth is that he has very little professional experience.
mystic – a person who is very spiritual and seems to have a close relationship with God or supernatural powers and is closer to the truth than most other people
* Dio is a mystic, and many people ask him for guidance on spiritual matters.
smoke and mirrors – a phrase used to describe a situation where what appears to happen is not what actually happens, and one has been deceived, tricked, or lied to, much like what happens when a magician performs
* Our competitors used a lot of smoke and mirrors to convince Acme Company to work with them, but Acme will soon realize that they made the wrong decision.
to shake – to make another person doubt or question his or her beliefs; to make a person less certain about something
* When your father died, did it shake your religious beliefs, or strengthen them?
Comprehension Questions
1. Why doesn’t Armond like astrologers?
a) Because he doesn’t believe anything they say.
b) Because he thinks they charge too much.
c) Because they gave him incorrect information in the past.
2. What does Armond mean when he says, “It’s all smoke and mirrors”?
a) The astrologers smoke too much.
b) The astrologers use tricks to fool people.
c) The astrologers are dangerous.
Answers at bottom.
What Else Does It Mean?
in the stars
The phrase “in the stars,” in this podcast, means fated or related to one’s destiny, referring to something that is meant to happen in the future and cannot be changed by one’s actions or decisions: “Francesca always knew that she would become a psychologist; it was written in the stars.” The phrase “under the stars” means outdoors: “Even though it was cold, they went camping under the stars.” The phrase “to see stars” means to see strange flashes of light, usually after one has been hit in the head: “Are you still seeing stars? Maybe we should take you to the doctor’s office.” Finally, the phrase “to have stars in (one’s) eyes” means to think that something is better, more interesting, more beautiful than it really is: “When they bought their first house, they had stars in their eyes and they didn’t really see all the problems.”
to shake
In this podcast, the verb “to shake” means to make another person doubt or question his or her beliefs, or to make a person less certain about something: “When Gregorio’s cancer failed to respond to the medications, it shook Gregorio’s belief in his doctors’ advice.” The phrase “to shake (one’s) head” means to move one’s head from side to side, as if saying “no” or showing sadness: “When I asked Gerald if he had passed the exam, he just shook his head sadly.” Finally, the phrase “to shake (one’s) fist” means to show that one is very angry at another person by moving one’s closed hand in the air: “When the seller realized that the boys were stealing, she shook her fist and threatened to call the police.”
Culture Note
Fortune-Telling Tools
“Fortune-tellers” (people who predict the future) use many tools to predict the future. The simplest reading is probably “palm reading,” where they look at the lines on one’s “palm” (the flat, inside part of one’s hand) to predict the future. The length of different lines has different meanings. For example, the “palm reader” might talk about the client having a short “love line” or a long “life line.”
Other fortune-tellers use “tarot cards” to predict the future. They usually lay the cards “face-down” (with the image facing the table, so that it cannot be seen) in front of the client, and the client turns them over one at a time, following the fortune-teller’s instructions. The fortune-teller “interprets” (understands the meaning in a particular way) each card. There are cards for Death, The Fool, the Lovers, Strength, and many other “concepts” (ideas).
Some fortune-tellers use a “crystal ball” to “divine” (predict) the future. A crystal ball is a “transparent” (clear) or “translucent” (allowing light through) “globe” (a round shape, like a ball) that sits on a small stand. A fortune-teller tells clients that he or she can look into the crystal ball, see images, and interpret them for the client, providing information about the future or helping the client make an important decision.
Finally, some fortune-tellers use “numerology” to predict the future. Numerology is the study of numbers, their special meanings, and their special relationships with each other. “Numerologists” may interpret special meanings on certain dates and times, such as 11:11 on November 11, 2011. Or they may find importance in the “serial numbers” (unique numbers) on “currency” (paper money).
There are many other fortune-telling tools, but the ones described above are some of the most familiar ones in the United States.
Comprehension Answers
1 - a
2 - b