= 0868
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 868: Mergers and Acquisitions
This is English as a Second Language Podcast episode 868. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there, become a member of ESL Podcast, and download the very useful Learning Guide to this episode.
This episode is a dialog between Marisol and Lamar about one company buying another company. Let’s get started.
[start of dialog]
Marisol: What do you think of the big announcement this morning?
Lamar: That our company is going to merge with McQ Corp.? From what I’ve heard through the grapevine, this isn’t a merger but a hostile takeover.
Marisol: But the CEO said this morning that our company and McQ Corp. are equals in this merger, and the integration of the two companies will be seamless.
Lamar: Don’t you believe it! McQ Corp. has a history of taking over companies with high valuations and a lot of assets and selling it off in pieces. This is no friendly acquisition.
Marisol: But what about all of that talk about our two companies consolidating into a strong business entity and creating great synergy? Didn’t you buy any of that?
Lamar: Not one word. When McQ Corp. is through with us, we’ll be lucky to still have the shirts on our backs!
[end of dialog]
Marisol begins by saying to Lamar, “What do you think of the big” – or important – “announcement this morning?” An “announcement” is when you are given some piece of news, usually from someone in authority, like your boss or the president of the United States. Lamar says, “That our company is going to merge with McQ Corp?” He’s making sure he understands what Marisol is asking him. He says, “Oh, basically, you mean the big announcement that our company is going to merge (merge) with McQ Corp.” “To merge” means to combine two companies and form one, new company. The idea with a merger is that it’s sort of equal – 50-50. You take your company, I take my company, and together, we merge them. We make them one company.
Lamar says, “From what I’ve heard through the grapevine, this isn’t a merger but a hostile takeover.” A “hostile (hostile) takeover (takeover)” is when one company buys another company, but the other company that they’re buying doesn’t want to be bought. But because, typically, it’s a public company and they have what are called “shareholders” – people who own part of the company – often the people who run the company don’t have the final say. They don’t have a majority of the people who vote in the meeting, to decide whether this company should be taken over or not. So, a “hostile takeover” is when the leaders of the company don’t want another company to buy them, but because the other company is able to convince the stockholders – the people who own small parts of the company and who get to vote on questions such as this – they are able to do it anyway.
Lamar says that he heard this information “through the grapevine (grapevine),” one word. The expression “to hear something through the grapevine” means to hear a rumor, to hear someone say something that you think is true but you don’t have any proof. You don’t have any evidence that it is true and in fact; it might not be true. So, you hear from one person, and that person tells another person, and then so on and so forth. That’s “hearing something through the grapevine.” You’re not hearing it directly from the president or from the boss. You’re hearing it through other people who, the idea is, have some connection with the person who made this decision, in this case.
There was a popular song in the late 1960’s called “I Heard it Through the Grapevine.” It was actually made popular by Gladys Knight and the Pips – a female band – and the great Marvin Gaye. Marvin Gaye’s version is the one that people usually associate now with this song. It’s a song about a man who hears that his lover, his girlfriend, is going to leave him, and he doesn’t hear it from the girlfriend. He hears it “through the grapevine.” He hears it from somebody else who heard it from somebody else. And of course, like a lot of songs, he’s wanting that person to come back.
I heard it through the grapevine
Not much longer would you be mine
“Not much longer would you be mine” – meaning you would not be with me for very much longer. That’s what he heard through the grapevine.
This is a little less musical of an example. We’re talking about a hostile takeover after all. Marisol says, “But the CEO” – the Chief Executive Officer, the top person in the company – “said this morning that our company and McQ Corp. are equals in this merger.” “To be equals (equals)” means that you are the same. You have the same rights, the same responsibilities, the same amount of power in some agreement or some connection with another person or another organization. To say “two people are equals” means to say that you consider them both the same. You don’t treat one or act towards one differently than you would the other.
Marisol says that the two companies are supposed to be equals in this merger and the integration of the two companies will be seamless. “Integration” (integration) is a combination or a combing of two different things. They’re mixed together so that all of the different parts work together, that everything seems to move forward normally. “Integration” is taking two different things and combining them, often two different organizations or two different plans. “Seamless” here means very smooth, without any problems, especially when we’re talking about two organizations that are joining together to do something or in this case, merging completely.
A “seam” (seam) is what you would have in a piece of clothing – for example, if you’re wearing a shirt, there may be a seam between the main part of the shirt that’s on your shoulder or on your chest and the arm of the shirt. Those two pieces of cloth, of fabric, of material, are connected by a “seam.” A “seam” is what you see – the line you see that is evidence that they are connected. “Seamless” would be you don’t have any signs that they were two separate pieces of material. Similarly here, if we say, “The integration of the two companies will be seamless,” we mean you won’t even realize that they were two separate companies before.
Lamar says, “Don’t you believe it,” which is just another way of saying “You’re wrong. What you just said is wrong. You should not think that it’s true.” Lamar says, “McQ Corp. has a history of” – meaning they have a reputation in the past for – “taking over” – or buying companies – “with high valuations and a lot of assets.” “Valuations” are estimations or assessments of how much something is worth. It’s a term we use in the business world, when we are talking about trying to determine usually how much a company is worth.
“Assets” (assets) refer to the things in a company that are worth money. That could be technology. That could be intellectual property - that is, things that belong to the company that no one else can use because they created it. It could be software. It could be lots of sorts of things. It could be physical things like buildings and cars. Anything you can buy and sell that’s valuable – it could be considered an asset. Your home might be considered an asset if you own it. Lamar says that “McQ Corp. has a history of taking over companies with high valuations and a lot of assets and selling them off in pieces.” “To sell them off” means really the same as to sell, just a little more emphatic. “To sell them off” means they’re almost – like they’re trying to get rid of them. “In pieces” means in many different parts, not all as one thing but selling this part to one person and this part to another person.
Lamar says, “This is no friendly acquisition.” “Acquisition” means purchase, to buy something. When we talk about a company, an acquisition would be one company buying the other and the company taking over that other company and doing whatever it wants with it, basically. With a merger, we might think of the two companies coming together to form one company. With an acquisition, we think of one company basically coming in and taking over the other company and making it part of their, now larger company.
Marisol says, “What about all of that talk about our two companies consolidating into a strong business entity and creating great synergy?” “To consolidate” (consolidate) means to put two things together, to combine them. It’s basically the same as to merge them. A “business entity” is the same as a company, a corporation. “Synergy” (synergy) is when two things combine in such a way that they’re even stronger or more powerful after you combine them. Marisol says, “Didn’t you buy any of that?” Here, the verb “to buy” means to believe. “Didn’t you believe that?” It’s often used when someone is trying to persuade you, to convince you something is true that you’re perhaps having difficulty doing. Lamar says, “Not one word.” He didn’t buy one word of it. He didn’t believe anything the company told him.
“When McQ Corp. is through with us” – when they’re done, when they’ve purchased the company – “we’ll be lucky” – we’ll be fortunate – “to still have the shirts on our backs.” The shirt on your back is a phrase used to talk about when you lose everything you have. “I didn’t even have the shirt on my back” – that would mean “I lost everything, even my clothing. I was naked. I lost everything.” So, the bank came and took away my car. They took away my house and left me only with the shirt on my back. That’s the only thing I have left – or, “…didn’t even leave me with the shirt on my back” – didn’t even leave me with my clothes. That’s just an example. The bank didn’t actually do that. But banks, do, in fact, take over people’s assets when they have loans that the people don’t pay. Here, the evil McQ Corp. will take over this company and, probably, not even leave Lamar with a shirt on his back.
Now let’s listen to the dialog this time, at a normal speed.
[start of dialog]
Marisol: What do you think of the big announcement this morning?
Lamar: That our company is going to merge with McQ Corp.? From what I’ve heard through the grapevine, this isn’t a merger but a hostile takeover.
Marisol: But the CEO said this morning that our company and McQ Corp. are equals in this merger, and the integration of the two companies will be seamless.
Lamar: Don’t you believe it! McQ Corp. has a history of taking over companies with high valuations and a lot of assets and selling it off in pieces. This is no friendly acquisition.
Marisol: But what about all of that talk about our two companies consolidating into a strong business entity and creating great synergy? Didn’t you buy any of that?
Lamar: Not one word. When McQ Corp. is through with us, we’ll be lucky to still have the shirts on our backs!
[end of dialog]
Our greatest asset here at ESL Podcast is our wonderful scriptwriter and her talent for writing wonderful scripts. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan, thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
to merge – to combine two companies to form a new company
* How many people will lose their jobs when the companies merge?
to hear through the grapevine – to hear a rumor; to hear someone say that something is true or happening, but not have any proof and know that it may not actually be true
* I heard through the grapevine that Joel and Noemi broke up. Is that true?
hostile takeover – an event where one company buys another without the approval of that company’s executives or board of directors
* Nobody realized that Acme Corporation was buying shares in order to pursue a hostile takeover of the company.
equals – people or organizations that have the same rights and responsibilities, with the same amount of importance or significance
* In a perfect world, husbands and wives would be equals, but in reality, one person is usually the decision-maker.
integration – the way two things are put together or mixed together to create something new where all the parts or pieces work together
* The racial integration of schools in the southern United States was an important social issue in the 1960s.
seamless – very smooth, without any problems, especially referring to where two things join each other
* Please practice the introduction so that it is seamless with the rest of your speech.
don’t you believe it – a phrase used to contradict what another person has said, meaning that one disagrees with the other person and thinks he or she is incorrect
* A: Mom said she’s going to host a simple Thanksgiving meal this year.
B: Don’t you believe it! She says that every year, but then she makes it too fancy and ends up spending days in the kitchen.
valuation – an assessment of the value of something; a determination of how much money something is worth
* How much do square footage and the number of bedrooms affect the valuation of a new home?
asset – something that is valuable and can be sold to receive cash
* For most American families, their home is their greatest asset.
in pieces – with many parts; not all at once or altogether; one at a time
* It’s interesting to watch sculptors who work in pieces, finishing one detailed part of a sculpture before moving onto the next part.
acquisition – purchase; the process of buying something so that one is the owner and has it
* Pedro spent most of his life involved in the acquisition of expensive things, but as he became older, he realized that family and friends are more important.
to consolidate – to put two or more things together so that they form one strong unit; to unite or combine
* These consolidated financial statements show the profitability of all our offices, not just our headquarters.
business entity – a company, corporation, or firm; an organization that tries to make money by selling products or services
* Have you structured your business entity as a partnership or a sole proprietorship?
synergy – cooperation and coordination between two or more people or organizations that produces stronger, better, or more influential results than either of the people or organizations could have achieved alone
* The best teams have strong synergy that produces a lot of exciting, creative ideas.
to buy – to believe something; to be persuaded; to be convinced of something
* Did you buy Linda’s story about how she lost her cell phone?
the shirt on (one’s) back – a phrase used to talk about losing almost everything one has
* Dave sold the shirt on his back to try to keep his restaurant open, but it just wasn’t profitable and he had to close it.
Comprehension Questions
1. What does Lamar mean when he says that he “heard through the grapevine”?
a) He is being paid for secret information.
b) He heard the news while drinking wine.
c) He heard a rumor, but has not been able to verify it.
2. Why does Lamar say, “We’ll be lucky to still have the shirts on our backs”?
a) Because the new company will ask employees to wear a different uniform.
b) Because they’re going to have to work very hard.
c) Because the other company is going to destroy McQ Corp.
Answers at bottom.
What Else Does It Mean?
equal
The word “equals,” in this podcast, refers to people or organizations that have the same rights and responsibilities, with the same amount of importance or significance: “Should all teachers be treated as equals, or should teachers with more experience receive extra benefits?” The phrase “to be the equal of (someone or something)” means to be as good as someone or something else: “This new car is the equal of any car I’ve ever owned before.” The phrase “to be without equal” or “to have no equal” means to be the best: “Francisco believes the novel is without equal and he recommends it to all his friends. Finally, the phrase “all things being equal” means that all other factors are the same, or everything is working normally: “All things being equal, they should have enough money to buy their first home in 2016.”
to buy
In this podcast, the verb “to buy” means to believe something or to be persuaded: “Did you buy what the politicians were saying about the new healthcare law?” The phrase “to buy time” means to find a way to give oneself more time to make a decision, postponing it for later: “The reporters have been asking questions about this for weeks already and we can’t buy you any more time. You need to give them an answer.” The phrase “to buy up (something)” means to buy as much of something as one can: “The day after Thanksgiving, shoppers bought up almost everything in the store.” Finally, the phrase “to buy (somebody) out” means to buy all of the stock or shares that a person owns, so that he or she no longer has any power or influence: “How much did Jason pay to buy out the other partners?”
Culture Note
Types of Mergers
The business world has “seen” (experienced; witnessed) many types of mergers. A “horizontal merger” “occurs” (happens) between two companies that are working in the same “field” (area; sector; industry). For example, a company that sells medical equipment in the northeast might purchase a company that sells similar medical equipment in the southwest. This allows the company to “expand” (increase; spread out) its “geographic reach” (the physical area covered by a company) and increase its “market share” (what percentage of sales are held by a particular company).
In contrast, a “vertical merger” occurs when a company “purchases” (buys) a company that produces products or offers services that are normally used by the purchasing company. For example, an auto manufacturer might purchase the company that supplies its tires. Companies participate in these types of mergers because they “anticipate” (believe will happen) that this will decrease costs. In this example, the auto manufacturer will now have access to tires “at cost” (paying only the cost of making the tires), without paying for the “overhead” (additional expenses, such as executive salaries) that was included in the price of the tires when the tire manufacturer was a separate company.
A third type of merger, called a “conglomerate merger,” occurs when the buying company and the company being “acquired” (bought) are “unrelated” (not connected to each other). For example, a company that makes computer games might buy a company that provides financial advice. Conglomerate mergers are usually “intended” (planned) to “diversify” (make less risky by having many different, unrelated parts or by being in many different fields) large corporations’ investments.
Comprehension Answers
1 - c
2 - c