= 0874
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 874: Poor Road Conditions.
This is English as a Second Language Podcast episode 874. I'm your host Dr. Jeff McQuillan coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there to download a Learning Guide for this episode that will give you a complete transcript of everything we say.
This episode is a dialogue between Alice and Sam about going out onto the street, onto the roads in a city or a town, and having problems with the road conditions. Let’s get started.
[start of dialog]
Alice: I’m really glad I let you talk me into going for a bike ride. It’s been years since I’ve been on a bicycle.
Sam: This is the only way to travel. You get to really see the scenery and enjoy the fresh air.
Alice: Hey, watch out! You almost dropped into that huge pothole. This asphalt is cracked and the road is all bumpy.
Sam: Thanks for the warning. Yeah, this asphalt really needs to be repaired. I’d ride on the gravel path instead, but it’s full of ruts. Oh, slow down! There’s a big dip ahead.
Alice: Whoa! I didn’t see that coming. I almost lost control on that slippery section of road. Sorry, I nearly swerved into you. Are you okay?
Sam: Yeah, I’m fine. When I suggested this route, I was sure it would be an easy ride since it’s paved all the way. I didn’t bargain for these lousy road conditions.
Alice: We’ll just have to keep our eyes open and be thankful for these crash helmets!
Sam: You won’t blame me if you go flying, will you?
Alice: Not if you break my fall.
[end of dialog]
Alice begins by saying to Sam, “I'm really glad” – I'm really happy – “I let you talk me into going for a bike ride.” “To talk someone into something” means to convince them, to persuade them, to get them to agree with your opinion of something. Alice and Sam are on a bike ride. “Bike” (bike) is short for bicycle. Alice says “It's been years since I've been on a bicycle.” “It's been years since I have been on a bicycle.” A “bicycle,” of course, has two wheels and a seat and what we call a “handlebar” that helps you steer or move the bicycle in the correct direction.
Sam says “This is the only way to travel.” This is not to be taken literally. Sam doesn't mean this is the only possible way in the world to travel. That expression, “This is the only way,” is used to indicate this is the best way. This is the way that is better than any other way or method of traveling.
Sam says “You get to really see the scenery and enjoy the fresh air.” “Scenery” (scenery) is what you can see, usually outside of a building, often referring to trees, lakes, things that are nice to look at, things that are beautiful.
Alice says “Hey! Watch out! You almost dropped into that huge pothole.” A “pothole” (pothole) is a hole in a street or a road, or a freeway, usually created by a lot of traffic, often caused by the change in temperature that sometimes makes the surface of the street loose and then you get a hole in the street. We call those holes in the street “potholes.” Alice says Sam almost went into one of the big potholes in the street.
She says, “This asphalt is cracked and the road is all bumpy.” “Asphalt” (asphalt) is a very common surface that we used to cover our streets and our roads, usually made by mixing small rocks with a very hot, oily substance. It's usually black or a very deep kind of blue when you look at it. That's “asphalt.” Asphalt is used on most of the streets here in Los Angeles. It's a cheap and effective way to cover the roads to make them smooth, but it's not perfect. Asphalt can sometimes crack. When we talk about “cracked asphalt,” we mean there are little lines in the asphalt going through the surface where the asphalt appears to be separating. A “crack” is anytime you have some surface that appears to be separating, causing a line to go through it – what looks like a line. For example, if you have a glass and you hit the glass against the wall, the glass might break, or it might just crack. It might start to fall apart even though it’s still in one piece.
The asphalt is cracked, according to Alice, and the road is all bumpy. “Bumpy” (bumpy) means that it is uneven. Some areas are higher than others. So as you drive down it, it's like you're going up and down. Your car moves up and down because the road isn't even. It isn't flat. Sam says “Thanks for the warning. Yeah, this asphalt really needs to be repaired” – it needs to be fixed. “I’d ride on the gravel path instead, but it's full of ruts.” A “gravel (gravel) path” is an area for bikes, or for people who are walking, that is not covered with asphalt. Instead, it's covered with small, little rocks. Sam says he can't go on the gravel path because it's full of ruts. A “rut” (rut) is basically the hole in the ground that is made by wheels, many different wheels, going over the same spot. If you have a lot of bicycles or a lot of other wheels going over soft ground, and going over it in the same place over and over again, eventually you will create a rut, which is a long line, a hole, really, in the ground that is caused by these wheels going over and over it.
Sam says, “Slow down. There's a big dip ahead.” A “dip” (dip) is sort of like a hole. It's an area that's lower than the surrounding area around it. Alice says, “Whoa! I didn't see that coming.” I didn't anticipate that. “I almost lost control on that slippery section of the road.”
“To lose control” means you no longer have power to change the direction that you are moving, or to change what is happening. Some people may drink too much alcohol and lose control of themselves. They don't have a way of controlling themselves because they drank too many beers – so don't drink too many beers, especially if you're bicycling! Alice probably wasn't drinking…we don't know. It's possible Alice was drinking before we started this dialog, but she doesn't appear to be drinking. The problem appears to be the road itself.
She says she lost control on that slippery section of road. Something that is “slippery” (slippery) is often covered with water or ice, and is difficult to drive on because things keeps sliding off of it, or sliding around on it. Something that is slippery is something that could be very dangerous because as you walk over it or drive over it, you could suddenly move and then have a problem, possibly even an accident. If you walk on a street that is slippery, you could fall, for example.
Alice is on a slippery section of the road. She says, “Sorry. I nearly swerved into you.” “To swerve” (swerve) means to suddenly change direction in an unexpected way, often to avoid hitting something else. So, you have two cars traveling down the street and one of the cars sees a little cat that comes out onto the road. Well, some cars would continue driving, but most cars would swerve to miss the cat. They would move the car over to the left or to the right suddenly in order not to hit the cat.
Sam says, “I'm fine.” Alice didn't hit him. He says, “When I suggested this route” – this path, this way of getting from one place to another – “I was sure it would be an easy ride since it's paved all the way.” “To be paved” (paved) means to put asphalt, cement, or something else on top of the ground, on top of the dirt, in order to make it easier to ride on. Sam says, “I didn't bargain for these lousy road conditions.” The expression “to bargain for” means here to plan for, to expect something to be in a certain way. Sam says he did not plan for, or bargain for these lousy, or bad road conditions. The “condition of something” is the situation that it is in. It is the state that it is in.
In this case, Sam is referring to bad road conditions – roads and streets that are not very easy to drive on. Alice says, “We’ll just have to keep our eyes open” – we’ll have to be alert – “and be thankful for these crash helmets.” A “helmet” (helmet) is a protective hat that goes over your head on the top and on the sides to protect it. A “crash helmet” is something that someone riding a bicycle or a motorcycle might have on their head to protect it in case they fell off of the bicycle or the motorcycle and hit the ground. The crash helmet would protect their head.
Sam then says to Alice, “You won't blame me if you go flying, will you?” “To go flying,” in this case, would mean to hit something while you're riding the bike and to be thrown from the bike. You would fly in the air off the bike and onto the ground. Sam says “You won't blame me” – you won't think I'm guilty if that happens to you – will you, Alice? Alice says, “Not if you break my fall.” “To break (break) someone's fall” means to prevent them from getting hurt, by either catching them or by doing something that would prevent them from hurting themselves by falling on the ground or some hard object. That's Alice's little joke, of course. If Sam broke her fall, he would get hurt as well, especially if Alice is a big woman…which I don't know if she is or not.
Now let’s listen to the dialog this time, at a normal speed.
[start of dialog]
Alice: I’m really glad I let you talk me into going for a bike ride. It’s been years since I’ve been on a bicycle.
Sam: This is the only way to travel. You get to really see the scenery and enjoy the fresh air.
Alice: Hey, watch out! You almost dropped into that huge pothole. This asphalt is cracked and the road is all bumpy.
Sam: Thanks for the warning. Yeah, this asphalt really needs to be repaired. I’d ride on the gravel path instead, but it’s full of ruts. Oh, slow down! There’s a big dip ahead.
Alice: Whoa! I didn’t see that coming. I almost lost control on that slippery section of road. Sorry, I nearly swerved into you. Are you okay?
Sam: Yeah, I’m fine. When I suggested this route, I was sure it would be an easy ride since it’s paved all the way. I didn’t bargain for these lousy road conditions.
Alice: We’ll just have to keep our eyes open and be thankful for these crash helmets!
Sam: You won’t blame me if you go flying, will you?
Alice: Not if you break my fall.
[end of dialog]
She never loses control when she's writing her wonderful scripts. I speak, of course, of our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California. I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
GLOSSARY
bicycle – a device with two wheels, a seat, and a handlebar, that moves forward when the rider balances and pushes the pedals (pieces under the feet) in a circle
* If everyone rode bicycles to work, we would have less traffic and less air pollution.
scenery – views; what one sees in one’s surroundings, especially when talking about a beautiful natural area
* The hike is difficult, but the scenery from the top of the mountain makes it all worthwhile.
pothole – a hole in the paved road, usually caused by a lot of traffic and very cold temperatures
* The city doesn’t have enough money to fix all the potholes, so local residents are filling them with gravel and small rocks.
asphalt – a hard, black surface covering roads, usually made by mixing small rocks with hot, sticky, oily substances
* On a hot summer day, the asphalt heats up so much that you could cook an egg on it!
cracked – with small lines running through the surface of something where pieces are separating, usually because something is breaking
* When Maggie goes grocery shopping, she always checks to make sure that none of the eggs are cracked before she buys them.
bumpy – uneven; with many areas that are higher than the rest of the surface, making for an uncomfortable ride
* When we drove grandpa home after his surgery, we tried to avoid all the bumpy roads so that he wouldn’t be in pain.
gravel – many small rocks, often used to cover a road that is not paved, or for decoration in a yard
* The gravel roads in this area can get very dusty if it hasn’t rained for a while, so people tend to drive slowly and not follow other cars too closely.
path – route; a way to go between two points, especially one that is not paved and is only for people who are walking or riding bicycles
* Can we follow this path to the lake?
rut – a long line made in a soft road, caused by many heavy vehicles traveling over the same spot
* This path is hard to walk on because there are a lot of ruts from car tires.
dip – an area that is lower than the surrounding area, often because the surface was built poorly and is sinking
* There’s a big dip in the road near their home, and sometimes it becomes a small pond after it has rained a lot.
to lose control – to no longer have power or influence over what happens or how something or someone behaves
* A lot of drivers lose control of their car when driving on icy streets.
slippery – referring to something that is difficult to hold onto, possibly because it is covered in oil, water, or ice
* Be careful walking on that wet floor. It’s slippery!
to swerve – to turn quickly and unexpectedly, usually to avoid hitting something
* Did you see how that driver swerved to avoid hitting the dog in the road?
paved – with a hard, flat surface designed to make travel easier for cars, bicycles, and other wheeled vehicles
* Areas with paved roads have a lot less dust in summertime.
to bargain for – to plan for; to expect something to be a certain way
* When we bought this house, we didn’t bargain for the city to decide to put a subway line along our street!
road conditions – a report of the weather and temperature and how they affect driving, and/or an assessment of the quality of the road
* A lot of accidents occur under poor road conditions, especially at dawn and dusk with heavy rain.
crash helmet – a protective hat that covers the top and sides of one’s head, with a connecting strap underneath the chin, designed to protect one’s head and brain from falls, especially when riding a motorcycle or bicycle
* If Jun hadn’t been wearing a crash helmet, he probably would have died.
to go flying – to move very quickly through the air, especially when one is in an accident
* It isn’t safe to keep heavy objects inside your car, because they might go flying and hit someone if you have to stop quickly.
to break (one’s) fall – to cushion and protect someone from falling; to interrupt one’s fall so that one does not fall as hard and does not get hurt as badly
* The cat fell out of a third-story window, but fortunately, the canopy over the door on the first floor broke its fall and it survived.
Comprehension Questions
1. Which word would describe a road that has a lot of potholes?
a) Cracked.
b) Bumpy.
c) Slippery.
2. What does Sam mean when he says, “I didn’t bargain for these lousy road conditions.”
a) He’s upset that his tax money isn’t being used to fix the roads.
b) He doesn’t think the roads are as bad as Alice does.
c) He didn’t expect the roads to be in poor condition.
Answers at bottom.
What Else Does It Mean?
cracked
The word “cracked,” in this podcast, means with small lines running through the surface of something where pieces are separating, usually because something is breaking: “This old vase is a little bit cracked, but it’s still beautiful.” If a voice “cracks,” it sounds different than usual, usually because one is sick or has used one’s voice too much, or because a young boy is going through puberty: “Carl is only 11 years old, but his voice has already started to crack.” Finally, the phrase “to crack up” means to laugh very loudly, almost uncontrollably: “Adam told a really funny joke that made us all crack up.”
to go flying
In this podcast, the phrase “to go flying” means to move very quickly through the air, especially when one is in an accident: “People who go on this ride have to take off their hats, jewelry, and glasses, or else those things might go flying.” The phrase “with flying colors” means with a lot of glory, having done something very well: “Craig studied really hard for the exam and passed with flying colors.” The phrase “to get off to a flying start” means for something to begin well or strongly, more successfully and more quickly than one might have expected: “The new campaign is off to a flying start, with high name recognition for the candidate in several key states.”
Culture Note
Non-Motorized Paths
In America’s “car-centric culture” (a lifestyle that focuses and depends on cars for transportation), many people “associate” (think about in connection with) transportation with streets and highways, but there are also many other types of “thoroughfares,” or “routes” or paths that connect one place to another.
One of the simplest thoroughfares would be an unpaved “trail,” which is just ground that has been “compacted” (pushed down) by the feet of many people or animals so that, over time, plants stop growing there and the route is “visible” (can be seen). People who explore nature and go hiking are often following trails. Sometimes these trails are called “footpaths.” “Developed” trails are trails that are being maintained, with people cutting back “shrubs” (small bushes) and maybe putting “gravel” (small rocks) or “bark dust” (small pieces of wood) on the trail. If the trails are specifically designed for “snowshoeing” (the sport of walking on top of snow with special shoes) or “cross-country skiing” (skiing across flat areas, not down a mountain), they are sometimes called “snowshoe trails” or “skiing trails.”
A “cycleway” is a paved route that is designed for use by bicycles, but also used by “pedestrians” (people who are walking). “Motorized” (with an engine) vehicles are not allowed on the cycleways, which often “run parallel to” (are alongside; go in the same direction as) major streets or rivers. When a cycleway is very wide and next to a river, it is sometimes called an “esplanade.”
A path that is created for horses and riders is called a “bridle path,” because a “bridle” is the leather pieces placed on a horse’s head so that the rider can control the horse’s speed and direction. Usually pedestrians and sometimes bicycles are welcome to use bridle paths, too.
Comprehension Answers
1 - b
2 - c