= 0890
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 890, Enjoying Nature. This is English as a Second Language Podcast episode 890. I'm your host Dr. Jeff McQuillan coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there and become a member of ESL podcast and download a Learning Guide.
This episode is a dialogue between Charles and Rachel about going out and enjoying the world outside of your home, outside of any building, enjoying nature. Let’s get started.
[start of dialog]
Charles: This is what I call the great outdoors. Look at that stunning view!
Rachel: This is truly jaw-dropping. We’re in the middle of one of the most pristine areas of the world where wildlife lives in its natural habitat.
Charles: It’s almost like living in the middle of the wilderness, isn’t it? I bet those ponds and forests have amazing biodiversity.
Rachel: It is beautiful, and it’s great to be away from all of the pollution of the city. I’ve never seen foliage like this. This is truly a majestic landscape.
Charles: You really can’t appreciate the outdoors until you come to a place like this.
Rachel: You’re right. I feel like I’m at one with nature here.
Charles: Should we leave the hotel and go for a walk?
Rachel: A walk? Why? We have the best view of nature right here. We don’t want to spoil the effect by getting too close.
[end of dialog]
Charles begins our dialogue by saying to Rachel, “This is what I call the great outdoors.” The phrase “the great outdoors” refers to the beauty of the natural world – mountains, and rivers, and flowers – and everything that's natural out in the world that you can go see – the ocean, trees, forests – all of these things are part of what you could call “the great outdoors,” meaning the wonderful world of nature. Charles says, “Look at that stunning view.” “Stunning” (stunning) means very impressive, very beautiful. A “view” refers to the things you can see when you look in a certain direction. Some people who live near the ocean have a view of the ocean. They can look out of their window and see the ocean. Charles is talking about a stunning, or amazingly beautiful view.
Rachel agrees. She says, “This is truly jaw-dropping.” The term “jaw-dropping,” used as an adjective here, means very surprising, very shocking but in a good way – something that is really good, really beautiful. Your “jaw” (jaw) is the lower part of your face. It's what you move up and down when you talk, and when you eat your food. That whole thing is called your jaw. “To drop” means to go down quickly. “Jaw-dropping” would be when your jaw drops down and your mouth is open. That's the expression that we have on our face when we see something very surprising or very amazing. That's why we have this term “jaw-dropping” to describe something that is amazing. Rachel says, “We’re in the middle of one of the most pristine areas of the world.” “Pristine” (pristine) means perfect, just like new – something that hasn't been touched, something that hasn't been altered or changed in any way.
Rachel says they’re in one of the most pristine areas of the world where wildlife lives in its natural habitat. “Wildlife” (wildlife) – one word – refers normally to the animals that live in nature, not your dog or your cat in your house, but bears and moose and, I don't know, wolves, that live out away from any human area, away from any area where the humans live. That would be wildlife. “Wildlife” is any animal that doesn't live inside of a house or inside of a cage. Rachel says this is an area where wildlife lives in its natural habitat. The “natural habitat” (habitat) is the area where a certain kind of animal normally lives or a certain kind of plant normally grows. This again would be, typically, an area where there aren't any humans or very few humans, and so the animals and the plants live and die as they would normally do, without any humans interfering, or any humans getting involved.
Charles says, “It's almost like living in the middle of the wilderness, isn't it?” “Wilderness” (wilderness) is a large area of land that doesn't have a lot of humans in it. It doesn't have a lot of buildings or a lot of roads. That would be “wilderness.” Large parts of the state of Alaska here in the United States could be described as wilderness. They’re areas where no humans have ever even gone or at least that we know of. Charles says, “This is like living in the middle of the wilderness.” He says, “I bet those ponds and forests have amazing biodiversity.” A “pond” (pond) is a small lake. “Forests” are areas where there are a lot of trees. “Biodiversity” refers to the variety, the different kinds of life in a certain area. It might be different kinds of plants. It might be different kinds of animals. Typically it's both of those things. That's what “biodiversity” refers to. “To be diverse” means to be different, to have a lot of different types. “Biodiversity,” then refers to a lot of different types of life.
Rachel says, “It is beautiful and it's great to be away from all of the pollution of the city.” “Pollution” (pollution) refers to something that is dirty, something that is harmful perhaps even something that is poisonous. When we talk about pollution here in Los Angeles, we're usually referring to air pollution, where you look in a distance towards downtown and you see this sort of brown air. That would be pollution. We have a lot of it here in Los Angeles. It's the part of the city that isn't so beautiful. Rachel then says, “I've never seen foliage like this.” “Foliage” (foliage) are the leaves of trees and other plants. That's foliage. “This is truly a majestic landscape.” “Majestic” (majestic) refers to something that is very beautiful, very lovely, very impressive. “Landscape” is the same as scenery. It's the things that you can see in a distance, usually when there aren't a lot of buildings or houses that are blocking your view. You can see out onto the land. That would be the “landscape.” Charles says, “You can't really appreciate” – you can't really understand and enjoy – “the outdoors until you come to a place like this.” Rachel says, “You're right. I feel like I'm at one with nature.” “To be at one with something” means that you feel connected to it. You feel united with that thing or that idea or that group of people, even. In this case, Rachel feels at one with nature – with the natural environment, the natural world. Charles says, “Should we leave the hotel and go for a walk?” That, of course, is the funny part of the dialog. We imagine, in the first part of the dialogue that they're out somewhere by a lake, or in the mountains, or in a forest but instead they're still in their hotel. Charles says, “Should we leave the hotel and go for a walk?” Rachel says, “A walk? Why? We have the best view of nature right here. We don't want to spoil the effect by getting too close.” “To spoil (spoil) the effect (effect)” means to change or to ruin some perception or illusion that you have, to change the way you are thinking about something in such a way that it would be worse, that it would be not as good. That would be “to spoil the effect.”
Rachel says, “We don't want to spoil the effect” – the effect of this beautiful nature – “by getting too close” – by actually leaving their hotel and going out into the nature that they are looking at through their window. That’s kind of my view of enjoying nature. I like to enjoy nature from my hotel room, from my car maybe. An airplane would also be a place I could enjoy nature from. I’m not so much interested in going out into the actual nature itself. Now let’s listen to the dialog, this time at a normal speed
[start of dialog]
Charles: This is what I call the great outdoors. Look at that stunning view!
Rachel: This is truly jaw-dropping. We’re in the middle of one of the most pristine areas of the world where wildlife lives in its natural habitat.
Charles: It’s almost like living in the middle of the wilderness, isn’t it? I bet those ponds and forests have amazing biodiversity.
Rachel: It is beautiful, and it’s great to be away from all of the pollution of the city. I’ve never seen foliage like this. This is truly a majestic landscape.
Charles: You really can’t appreciate the outdoors until you come to a place like this.
Rachel: You’re right. I feel like I’m at one with nature here.
Charles: Should we leave the hotel and go for a walk?
Rachel: A walk? Why? We have the best view of nature right here. We don’t want to spoil the effect by getting too close.
[end of dialog]
She's at one with the English language. Her scripts are majestic. They’re stunning. I speak of course, of our very own, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
the great outdoors – a phrase used to describe the beauty and wonder of the natural world, including opportunities to explore and have adventures
* Hinton loves hiking, skiing, and rafting in the great outdoors.
stunning – very impressive and beautiful; breathtaking
* The art museum has a stunning exhibit of modern art.
view – scenery; the things that can be seen in the distance with a wide, open perspective
* Their seaside home has large windows with a beautiful view of the ocean.
jaw-dropping – surprising or shocking, especially in a good way
* The CEO made the jaw-dropping announcement that we were all going to receive 15% raises. It was unbelievable!
pristine – in perfect, like-new condition; untouched and unaltered; clean
* If that old painting were in pristine condition, it would be worth thousands of dollars.
wildlife – animals that live in nature; not animals that live in homes or on farms
* Bears, moose, and caribou are some of the larger types of wildlife that we see here in the national park.
natural habitat – the outdoor area where a plant or animal normally lives, without influence from humans and not in a park or zoo
* The planned building poses a major threat to the owls’ natural habitat.
wilderness – a large area of land that is mostly untouched and unaffected by humans, without roads or buildings
* When people go hiking in a wilderness area, it is very important that they take all of their trash and waste with them when they leave.
pond – a body of still (not moving) water, bigger than a puddle but smaller than a lake
* Do any fish live in this pond?
forest – a large area covered with many trees and other plants
* At night, you can hear owls in the forest.
biodiversity – the variety of life in an area; a measure of the number of plant and animal species in an area, as well as how many of each species live in the area
* Modern agricultural fields have very low biodiversity, because they normally have only a single plant like corn growing over a large area.
pollution – contamination; something that is harmful, poisonous, or dirty in a natural area
* What causes more air pollution: cars or factories?
foliage – the leaves of trees and other plants
* Each year, tourists go to Vermont to see the fall foliage as it changes from green to red, orange, and yellow.
majestic – with great beauty and dignity; lovely, impressive, and grand; related to royalty (kings and queens)
* The castle feels majestic, with tall ceilings, velvet fabrics, and stained glass windows.
landscape – scenery; the things that can be seen in the distance with a wide, open perspective
* Do you prefer to paint landscapes or portraits?
at one with – feeling united with or connected to something; feeling peaceful and in harmony
* Through meditation, Arnand is trying to become one with the universe.
nature – the natural environment; the parts of the world that are not controlled or changed by humans
* Sometimes people think we have dominated nature, but storms and earthquakes prove just how powerful nature is.
to spoil the effect – to ruin or destroy the illusion, perception, or the way one thinks about something
* Charlene put on a beautiful dress, had her hair styled, and wore expensive makeup, but her cheap jewelry spoiled the effect.
Comprehension Questions
1. Where would you expect to see the most foliage?
a) In a pond.
b) In a forest.
c) In a majestic landscape.
2. What does Rachel mean when she says that she feels like she is “at one with nature”?
a) She feels like she is all alone, without anyone else around her.
b) She feels very lonely and unimportant.
c) She feels connected to the natural environment.
Answers at bottom.
What Else Does It Mean?
stunning
The word “stunning,” in this podcast, means very impressive and beautiful or breathtaking: “Their new home is stunning. It must have cost a million dollars!” The word “stunning” also means shocking and important: “When Jared heard the stunning news, he couldn’t even speak.” A “stun gun” is a weapon that produces a strong electrical current that can hurt or kill people or animals, making them unable to move: “Is it legal for police officers to use stun guns?” As a verb, “to stun” can mean to use a stun gun to make a person or animal unable to move: “The slaughterhouse stuns cattle before it kills them.” Or, “In some parts of the world, people use special tools to stun fish in the ocean so that they can catch them more easily.”
landscape
In this podcast, the word “landscape” means scenery, or the things that can be seen in the distance with a wide, open perspective: “Before the fire, this was a beautiful green landscape with many trees, but now we can see only dead trees for miles in every direction.” The phrase “the political landscape” describes the current political situation or environment: “In this political landscape, it is common for election campaigns to have many negative ads about the other candidate.” Finally, when talking about documents, “landscape” describes a document with a layout that is printed on horizontal paper, while “portrait” describes a document with a layout that is printed on vertical paper: “The table and graphs were too wide to display with a portrait layout, so she changed the layout to landscape.”
Culture Note
The Most Beautiful Natural Places in the United States
The United States is a large country with “abundant” (many; a lot of) natural resources and many “protected areas,” such as state and national parks. One of the most beautiful and stunning natural areas is the Grand Canyon in Arizona. A “canyon” is a deep area “carved” (cut) through high rocks by a river over many thousands of years, and the Grand Canyon is one of the largest. The river flows through beautiful “reddish” (red-colored) rocks. Nearby, Bryce Canyon National Park has stunning rock features in “shades” (variations of color) of red, brown, and orange.
Another one of the most beautiful natural areas is the Redwood Forest in northern California. The “Redwoods” are very large, very tall trees with reddish “bark” (the outer covering of a tree’s trunk). The trees are very old and majestic. People who prefer open mountains might think the most beautiful natural areas are found in the “snow-capped” (with snow on top) Rocky Mountains. And the National Parks found at Yosemite, with its rocky “cliffs” (steep sides of a mountain) and trees, and Yellowstone, with its “geysers” (water that sprays out of the earth), would have to be included on any list of the most beautiful natural areas.
A lot of the most beautiful natural places are associated with water. For example, some people might say that the “tropical” (with warm, wet weather) beaches of Hawaii are the most beautiful natural places in the United States. The Florida “Everglades” are also quite beautiful, with many plants and animals that are adapted to live in “wetlands” (areas that are always covered by some water), such as “mangroves” (trees that grow in areas with a lot of salt water) and “crocodiles” (long animal with large jaws and a long tail).
Comprehension Answers
1 - b
2 - c