= 0899
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 899 – Purchasing and Using an E-Ticket.
This is English as a Second Language Podcast episode 899. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Become a member of ESL Podcast by going to our website.
This episode is a story about using an electronic ticket to travel. Let’s get started.
[start of story]
I thought I would save time by purchasing my airline ticket online and checking in at the airport with my e-ticket. I went onto the McQ Air website and selected my flights. The screen then prompted me to pay with a credit card. After I typed in my payment information, I got a confirmation receipt with my ticket number and my itinerary. I printed out a copy of my e-ticket and I was ready to go – easy!
But when I got to the airport, it was a different story. I went up to a self-serve kiosk and swiped my credit card to bring up my account. The computer said that it couldn’t find my account. I flagged down an employee and she didn’t have any better luck, suggesting I stand in line at the check-in counter.
I got in the long line and 45 minutes later, the employee helped me check in and gave me my boarding pass. When I asked her what the problem was, she said she didn’t know and it was probably just a glitch in their computer system.
Well, the best laid plans of mice and men often go awry, especially if technology is involved!
[end of story]
Our story begins by me saying, “I thought I would save time by purchasing my airline ticket online.” “To save time” means to do something more quickly so that it won't take as much time. I decided I would save time by purchasing – buying – my airline ticket online – on the Internet – and checking in at the airport with my e-ticket. “To check in” is a two-word phrasal verb, meaning usually to present yourself at an event or at a location to register for something. When we use it in terms of airline travel, we mean to go to the airport and to tell the airline, “Yes, I'm here. I want to get on the airplane.” You have to check in before you're allowed to go onto an airplane.
I said I was going to check in at the airport with my e-ticket. “E-ticket” stands for electronic ticket. It's a ticket that most airlines in the United States now use. It's not a paper ticket that they send you like they used to many years ago. I still remember those days. Instead, they just send you an e-mail or they take you to a website. Now, you can print out your e-mail but that's not exactly the same as a paper ticket. An e-ticket is something that's done electronically and most tickets nowadays are e-tickets. I say that, “I went on to the McQ Air website.” “To go on to a website” means to visit a website, to go to that URL, that address on your web browser on your computer or your phone. I went onto the McQ Air website and selected, or picked, chose, my flights.
A “screen” is anything on an electronic device that is used to display something, to look at something. A “screen” could also be something that's on a wall that you show a movie on. In talking about computers though, the screen is a thing you're looking at. It could be a separate monitor from your main part of your computer, or it could be, for example, on a smart phone such as an iPhone. It could be the part of the phone that you look at that, that the information is displayed on. In our story, “screen” really means the same as the page that was on the screen.
“The screen prompted me to pay with a credit card.” “To prompt (prompt) someone” means to tell them they should do a certain action, to give them an indication that they should do something, to request that they do something. So, the website is prompting me – is asking me, if you will – to pay with a credit card. After I typed in my payment information -- my name, my credit card number, and so forth – I got a confirmation receipt with my ticket number and my itinerary.
A “confirmation receipt” is an electronic, in this case, document that shows that you have paid for something. You can print it out and show someone and say, “Look, I paid for this. I have a confirmation receipt.” A “receipt” in general, is any piece of paper or e-mail that indicates that you have purchased something. “Confirmation” is used here because we’re talking about making an airline reservation and when you make a reservation, when you say, “Yes, I want to fly on this day at this time,” the airline says back to you, “Yes. Okay. You can do that.” They give you a confirmation of your reservation.
I say that, “I got a confirmation receipt with my ticket number and my itinerary.” Your “ticket number” is a number that is on your ticket that is used to identify that ticket and that ticket only. Every ticket has its own ticket number. “Itinerary” (itinerary) means your travel plans. An “itinerary” is a list of all the important, in this case, airline flights that you are going to take. Your complete itinerary might include the airline flights you're going to take, the hotels you’re going to stay at, the tours that you may take – all that could be part of your itinerary.
Sometimes people use the word “itinerary” to mean their travel schedule, everything they will be doing when they are traveling. Next, I say, “I printed out a copy of my e-ticket and I was ready to go.” “To print out” means to make a paper copy of your electronic ticket. This, of course, is kind of funny because the idea is that you would be saving paper, not using paper, by having an electronic ticket, but the truth is most of us know that computers don't always work the way they should. And so we print out a copy so we have proof that we did what we said we did, in this case, that we purchased a ticket.
I say that, “When I got to the airport, it was a different story,” meaning things did not go the way I planned them to go. I say, “I went up to a self service kiosk and swiped my credit card to bring up my account.” Lots of vocabulary in that sentence, let's take a look. “I went up to” means I walked up to. I walked in the direction of and then stopped in front of something. You could go up to a person, or you could go up to, in this case, an object. The object that the person is going up to, is walking up to, is a self-serve kiosk. “Self-serve” means there isn't anyone there to help you. You are doing everything yourself. You are serving or helping yourself.
A “kiosk” (kiosk), in American English, usually refers to a computer where people can go and get information, or buy things, without anyone helping them. In other countries, in other languages, “kiosk” means a little, something a little different, but when we talk about a “self-serve kiosk,” we’re talking about a computer or a machine that you can go and do things on. This kiosk asked me to swipe my credit card.
“To swipe” (swipe) means to move something very quickly, especially a credit card or any other sort of bankcard through a machine that reads the electronic information on the card. When you go to a store, there'll often be a little machine and you use that machine to put your credit card information into the electronic system of the store. You do that by moving the credit card very quickly through the machine. The verb we use specifically for that action is “swipe.”
So, I swiped my credit card to bring up my account. “To bring up” is a two-word phrasal verb that has a couple of different meanings. Here, it means to retrieve or get information from a computer and have it be displayed on the computer screen. “To bring up” can also mean to raise a child, to be a parent and/or a friend who helps a child grow up, but here it means simply to get information from the computer so you can see it. The computer, however, said that it couldn't find my account. “My account” here would be my information. “I then flagged down an employee.” “To flag (flag) down” is a two-word phrasal verb meaning, usually, to wave your hand in the air in order to get someone's attention, to get them to come over and help you. We can flag down an employee at an airport and ask them to help us.
That's what I'm doing in the story. You could also flag down someone else who you want to help you in some public space. You may flag down a police officer if you have a problem and you need his help or her help. I flagged down an employee but she didn't have any better luck, meaning she wasn't able to find the information either. “So, she suggested that I stand in line at the check-in counter.” “To stand in line” means to go and to wait for someone to help you. The “check-in counter” is the place, usually a very large desk at an airport where employees will help you check in. It's different than the self-service kiosk where you're supposed to check-in yourself. The check-in counter is the place where they have real live human beings that will help you.
“I got in the long line and 45 minutes later, the employee helped me check in and gave me my boarding pass.” A “boarding pass” is a – usually a small piece of paper that you're given that you have to give to the airline employee in order to get on the actual plane. So, you hold it. You keep it with you. It also proves that you are going to go on an airplane and is your only way, typically, to get past the airport security. Now, in most American airports, you can't go up into where the people are getting on airplanes unless you have a boarding pass, unless you are actually traveling. In the old days, you could just go up to any airport and go through the security and sit and wait for someone to leave or for someone to arrive. Nowadays, you can't do that. You have to have a boarding pass to get past security. I asked the person what the problem was – why the computer couldn't find my information and I was told it was just a glitch in their computer system.
A “glitch” (glitch) is a technical problem, usually a small problem related to the way the computer is working. It's not working correctly. It's an error. I end by saying that, “The best laid plans of mice and men often go awry.” This is an old expression that means even when we plan things very carefully, sometimes things happen and our plan does not work out. Our plan is not successful. “The best laid plans” would be the plans that are prepared the best. Even if we prepare good plans, they often go awry. “To go awry” (awry) means to go wrong. There is a famous book in English called Of Mice and Men. You can learn about that in our Learning Guide.
Now let’s listen to the story, this time at a normal speed.
[start of story]
I thought I would save time by purchasing my airline ticket online and checking in at the airport with my e-ticket. I went onto the McQ Air website and selected my flights. The screen then prompted me to pay with a credit card. After I typed in my payment information, I got a confirmation receipt with my ticket number and my itinerary. I printed out a copy of my e-ticket and I was ready to go – easy!
But when I got to the airport, it was a different story. I went up to a self-serve kiosk and swiped my credit card to bring up my account. The computer said that it couldn’t find my account. I flagged down an employee and she didn’t have any better luck, suggesting I stand in line at the check-in counter.
I got in the long line and 45 minutes later, the employee helped me check in and gave me my boarding pass. When I asked her what the problem was, she said she didn’t know and it was probably just a glitch in their computer system.
Well, the best laid plans of mice and men often go awry, especially if technology is involved!
[end of story]
You can go on to our website and print out the wonderful scripts by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again, right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
to check in – to officially present oneself at an event or location; to sign in and register for something
* When you arrive for your interview, please check in at the front desk and then take a seat in the waiting area.
e-ticket – an electronic ticket; a ticket that is available on a website or by email, but not physically mailed to the buyer
* Can I get on the train just by showing this e-ticket on my smart phone, or do I need to bring a printed copy?
to go onto [a website] – to visit a website; to go to a URL
* Tessor goes onto this bank’s website at least once a week to check his account for any fraudulent transactions.
screen – the part of a computer, television, or other electronic device that displays information in lights
* The screen on this phone is almost impossible to read in the sunlight.
to prompt (someone) – to cue someone to do something; to give a signal or make a request indicating that a person needs to do something
* Walking by a flower shop prompted Nolan to buy flowers for his girlfriend.
confirmation receipt – an electronic or digital document that provides proof that a payment has been made, a request has been received, a transaction has been processed, or some other action has been taken
* Please print out this confirmation receipt for your records.
ticket number – a unique number found on a ticket, used to identify the purchase and the person to whom it belongs
* Please type in your ticket number and your last name, and our computer should be able to retrieve your payment history.
itinerary – a travel plan; a list of all the important flights, train trips, bus rides, hotels, and other items used to coordinate travel on a trip
* The executive assistant is responsible for coordinating the CEO’s itineraries.
to print out – to have a computer produce a printed version (on paper) of an electronic document or image
* We have thousands of digital photographs on the computer, but we rarely print them out.
to go up to – to approach; to move closer to someone or something
* The elderly, the disabled, and pregnant women are allowed to go up to the front of the line.
self-serve kiosk – a computer where people can complete their transaction without needing assistance from an employee and without interacting with a person
* Utility customers can pay their bills by mail, in person, or at a self-serve kiosk.
to swipe – to move something very quickly, especially to slide a credit or debit card into the side of a plastic machine that “reads” the information and then completes a transaction
* Pedro tried to swipe his debit card at the grocery store, but it didn’t work, so the grocery clerk had to enter his card number by hand.
to bring up – to retrieve information and have it be displayed on a computer screen
* Let me bring up the current version of the report so we can edit it together.
to flag down – to wave one’s hand or arm in the air to get someone’s attention and have that person come closer and provide assistance
* Please flag down the waiter and ask him to bring some more napkins.
check-in counter – a large desk at an airport where many employees help passengers get their boarding passes or tickets and check their luggage
* The woman at the check-in counter said that our bags were too heavy, so we had to pay an extra fee.
boarding pass – a printed document that allows a passenger to get on an airplane
* Li thought she had lost her boarding pass, but found it before her flight.
glitch – a technical problem, especially a computer error
* We’re sorry, but there was a glitch when you tried to pay your bill online. We have fixed the problem, so please try again.
the best laid plans of mice and men often go awry – a phase based on a Robert Burns’ poem “To a Mouse,” meaning that no matter how much we plan for things, what actually happens is unpredictable and beyond our control
* They wanted to have an outdoor wedding, but then a hurricane passed through. The best laid plans of mice and men often go awry.
Comprehension Questions
1. Which document would he need to present immediately before getting on the airplane?
a) His e-ticket.
b) His confirmation receipt.
c) His boarding pass.
2. What did he do when he “flagged down an employee”?
a) He yelled at the employee.
b) He asked to speak to the manager.
c) He got the employee’s attention.
Answers at bottom.
What Else Does It Mean?
to prompt
The verb “to prompt,” in this podcast, means to cue someone to do something, or to give a signal or make a request indicating that a person needs to do something: “Howard uses a special alarm on his computer to prompt him to stand up and go for a short walk every hour.” The verb “to prompt” also means to make someone want to do something: “What prompted you to study architecture?” In acting, “to prompt” means to remind an actor of what he or she is supposed to say next: “Don’t worry, if you forget your line. The director will prompt you.” As an adjective, “prompt” means quickly, soon, or at the right time: “Thank you for your prompt reply.” Or, “Please arrive promptly as we will not wait for anyone who arrives late.”
to flag down
In this podcast, the phrase “to flag down” means to wave one’s hand or arm in the air to get someone’s attention and have that person come closer and provide assistance: “The policeman flagged down passing cars and asked to see the drivers’ license.” The verb “to flag” means to make a mark or put a piece of paper next to important parts of a document: “We’ve flagged a few typos in the report.” Finally, the phrase “to wave the white flag” means to surrender or to show that one no longer wants to fight: “When the enemy began to wave the white flag, all our soldiers began cheering.” Finally, the phrase “like a red flag to a bull” describes doing something to make another person angry: “When we see Jeremiah tonight, please don’t talk about what happened. That would be like a red flag to a bull.”
Culture Note
Of Mice and Men
Of Mice and Men is a 1937 novel by John Steinbeck. It is about two “migrant workers” (people who move from place to place while looking for work, especially doing farm work) who are looking for jobs in California during the “Great Depression” (very difficult economic times before World War II). The title of the novel was “taken” (adapted; borrowed) from a poem called “To a Mouse” by Robert Burns.
The novel is about two men, George and Lennie. Lennie is very big and strong, but he has some “mental problems” (slow or incomplete intellectual and/or emotional development). They are very good friends, and George often protects Lennie. Lennie often gets into trouble, because he does not understand what he is doing or how his actions are “perceived” (observed and interpreted) by others.
The men dream of owning a “ranch” (a large farm that raises many large animals like cows and horses), but they face many “obstacles” (things that make it difficult for one to achieve goals). In the end, Lennie becomes the “pair’s” (the two men’s) greatest obstacle to fulfilling their dream, but you’ll have to read the novel to understand why – no “spoilers” (something that tells a person how a book or movie ends and ruins the story) here!
The novel is often “required reading” (something that all students must read) in American high schools, but it has also been a “target of censorship” (something that people do not want to have be made available, usually because they believe it is wrong) it has some offensive and “racist” (treating people unfairly based on the color of their skin) language.
Comprehension Answers
1 - c
2 - c