= 0900
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 900: Simplifying Information.
This is English as a Second Language Podcast episode 900. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful, Los Angeles, California.
Our website is ESLPod.com. That's been our website for 900 episodes. If you go there, you can become a member of ESL Podcast and get a Learning Guide for most of those 900 episodes.
On this episode we’re going to listen to a dialog between Tara and Stan about explaining information to people in a simple way. Let's get started.
[start of dialog]
Tara: How is your presentation coming along?
Stan: It’s okay, but I’m having trouble simplifying some of the key concepts without dumbing them down too much.
Tara: I think your instincts are right. You’ll be presenting to non-specialists, so it’s important to keep your presentation clear and simple.
Stan: That’s my problem. How do I capture the essence of all of this information without making it too simplistic?
Tara: My rule of thumb is to think about which concepts really jump out at me when I think about the topic and identify any patterns in the information. Then, I build my presentations around those things.
Stan: That’s a good idea.
Tara: I would also find a non-specialist and do a run-through and get his or her feedback. That’s the best way to know if you’ve nailed it.
Stan: That’s another good idea. What do I owe you for all of this good advice?
Tara: There’s a new restaurant across the street I’ve been meaning to try for lunch...
Stan: Say no more. Lunch is on me.
Tara: Really? Let’s go right now before you change your mind!
[end of dialog]
Tara begins by saying to Stan, “How is your presentation coming along?” The expression “to come along” means to make progress. It's a phrasal verb meaning to advance toward some goal, to be in the process of completing something. Tara wants to know how Stan's presentation is coming along. A “presentation” would be when you give information to someone, usually in some sort of formal setting, some formal situation. Stan says, “It's okay, but I'm having trouble simplifying some of the key concepts without dumbing them down too much.”
“To simplify” (simplify) means to make something less complex, to make something easier to understand. A “concept” is an idea. A “key (key) concept” is your main idea, or your most important ideas. Stan is trying to simplify, or make easier to understand, some key concepts without “dumbing them down.” The expression “to dumb (dumb) something down (down)” means to make something too simple, too basic, so that you are changing the meaning of something in an important way as you simplify it. “To dumb something down” is to lose some important information as you try to make it easier to understand.
This expression was often used in criticizing American education in the 1980’s and 90’s. You will still hear it in other contexts, when people talk about making things too simple in such a way that you are distorting the reality that is being described. You are not describing accurately because you are trying to make it too simple.
Tara says, “I think your instincts are right.” “Instincts” (instincts) are the reactions that you have or that an animal has that they are typically born with. We think of this more when it comes to animals than we do for humans. When we talk about instincts for humans, we don't necessarily mean it's something you are born with. It could just mean something that everyone seems to have, because this is the way that human beings are brought up in a culture or society. We may talk about a mother's love for her child as being a “maternal instinct” – the idea that a woman who is a mother will naturally want to take care of her own child. Tara says that she thinks Stan's instincts are correct, not about taking care of children, but about trying to simplify the key concepts.
She says, “You'll be presenting” – you will be giving this information – “to non- specialists.” A “specialist” (specialist) is someone who specializes in something, someone who's an expert in something. A “non-specialist” would be a person who is not an expert. If you work at a large company, for example, you probably have an IT department – an information technology department. Sometimes people from IT departments will be talking to normal human beings, regular people, and they won't understand that the person they're talking to is not a specialist. So, they may use information or they may use descriptions that are difficult to understand. A “non-specialist” is someone who's not an expert.
Tara says, “It's important to keep your presentations clear and simple because these are non-specialists.” Stan says, “That's my problem. How do I capture the essence of all of this information without making it too simplistic?” The “essence” (essence) here means the most important part or the most important parts. “To capture” (capture) here means to clearly explain, to make sure that you're including all of the important parts. That's the meaning of “to capture the essence of something.” Stan wants to capture the essence without it being too “simplistic.”
Something that is “simplistic” is too simple. It's related to the previous expression, “dumbing them down” or “dumbing something down.” You don't want to dumb it down so that it's simplistic. “Simplistic” would be a description that is not accurate because you are leaving important things out in order to try to make it easier for people to understand. When it's simplistic, people are understanding the wrong thing because you're not giving them all the information they need.
Tara tries to help him by saying that, “My rule of thumb is to think about which concepts really jump out at me when I think about the topic and identify any patterns in the information.” A “rule of from thumb (thumb)” means a general guideline, something that isn't an official rule. It isn't written down, but it's something you use to help you think about a certain situation. For example, in the kitchen, my rule of thumb is to put the oven at 350 degrees Fahrenheit if I'm not sure how hot the oven should be. That's my rule of thumb. That's what I use when I'm not sure about something. So, a rule of thumb is a general rule that you apply in different situations. Tara says her rule of thumb in preparing presentations is to think about which concepts really jump out at her. The expression “to jump out at someone” means to be the thing that gets that person’s attention the most, to capture or catch someone's interest or attention. Something that “jumps out at you” is something that you notice immediately. It's something that you see is important right away.
Tara tries to find ideas that jump out at her and help her identify any patterns in the information. A “pattern” (pattern) is a repeating design or sequence, something that you see over and over again. A, A, B, B, B, A, A, B, B, B, A, A, B, B, B – that's a pattern, okay? Two A’s followed by three B’s.
Stan says, “That's a good idea.” He is going to take Tara’s suggestion of building his presentation around the things that jump out at him. “To build a presentation” would mean to construct or to make the presentation. Tara says, “I would also find a non-specialist and do a run-through to get his or her feedback.” A “run-through” is when you practice something in order to prepare for some other event. You are going to go through it as a way of practicing it. It's not the actual presentation. It's something you would do to prepare yourself. Tara suggests finding someone who is a “non-specialist” and doing a “run-through” to get his or her feedback or opinion. Tara says, “That's the best way to know if you’ve nailed it.” “To nail (nail) something” is an informal expression meaning to do it exactly the way you should've done it, to do something very well.
Stan says, “That's another good idea. What do I owe you for all of this good advice?” “What do I owe you?” means “What do I have to give you as payment?” Tara says, “There is a new restaurant across the street I've been meaning to try for lunch.” Tara is suggesting that Stan take her to lunch to thank her at a new restaurant that she wants to try near where they work.
Stan says, “Say no more.” This is an expression that means I understand what you are saying completely. You don't need to tell me anything else. “Say no more. Lunch is on me.” When someone says, “Lunch is on me,” they mean they're going to pay for it. They’re inviting you to lunch. Tara says, “Really? Let's go now before you change your mind.” “To change your mind” means to change your opinion, to come to a different decision. Terra wants to go immediately before Stan changes his mind, changes his opinion about taking her to lunch.
Now let’s listen to the dialog this time, at a normal speed.
[start of dialog]
Tara: How is your presentation coming along?
Stan: It’s okay, but I’m having trouble simplifying some of the key concepts without dumbing them down too much.
Tara: I think your instincts are right. You’ll be presenting to non-specialists, so it’s important to keep your presentation clear and simple.
Stan: That’s my problem. How do I capture the essence of all of this information without making it too simplistic?
Tara: My rule of thumb is to think about which concepts really jump out at me when I think about the topic and identify any patterns in the information. Then, I build my presentations around those things.
Stan: That’s a good idea.
Tara: I would also find a non-specialist and do a run-through and get his or her feedback. That’s the best way to know if you’ve nailed it.
Stan: That’s another good idea. What do I owe you for all of this good advice?
Tara: There’s a new restaurant across the street I’ve been meaning to try for lunch...
Stan: Say no more. Lunch is on me.
Tara: Really? Let’s go right now before you change your mind!
[end of dialog]
She simplifies without ever making it simplistic. I speak, of course, of our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
to come along – to make progress or advance toward some goal or completion
* How are your vacation plans coming along?
to simplify – to make something simpler, less complex, and easier to understand
* The agency could improve customer satisfaction by simplifying the application process.
key concept – a main idea; one of the most important ideas or facts that a person is trying to communicate through speech or writing
* The five-paragraph essay starts with an introduction, then presents three key concepts, and then ends with a conclusion.
to dumb (something) down – to make something too simple or basic, usually by removing the most important or interesting information
* It must have been hard for a genius like Albert Einstein to dumb his ideas down and explain them so that other people could understand them.
instinct – a behavior or reaction that a person or animal is born with, something that does not need to be taught or learned
* Babies are born with an instinct to suck.
non-specialist – an ordinary person with a normal amount of knowledge, not an expert or something with a lot of knowledge about a technical topic
* Many researchers struggle to describe their work clearly for non-specialists when they apply for funding.
to capture the essence – to clearly explain the most important parts of something so that someone who is not familiar with it can understand the main idea without knowing all the details
* This photograph really captures the essence of life on the streets in New Orleans.
simplistic – very simple, especially overly simple, without any details or complex information, usually used to describe something in a negative way
* The novel’s characters are too simplistic. They don’t seem to have any deep emotions or thoughts.
rule of thumb – a general guideline, but not something that is written down or official
* In the kitchen, Yukato’s rule of thumb is to bake everything at 350 degrees.
to jump out at – to catch someone’s interest and attention; to be the thing that gets the most attention
* I don’t want any typos to jump out at my teacher when he reads my essay.
pattern – a repeating design or sequence, like AABBBAABBB
* The children had to identify the pattern in a series of colored beads and then extend it.
run-through – a trial presentation, used to receive feedback and improve one’s style and content before making the full presentation in front of a real audience
* Before making a big presentation, James likes to record himself in a run-through and then watch himself on the screen.
to nail – to do something very well; to meet one’s goal
* Wow, we nailed that presentation! The clients are definitely going to select our proposal.
to be on (someone) – to be paid for by someone as a special treat
* The coffee’s on me. It’s the least I can do to thank you for meeting with me.
to change (one’s) mind – to change one’s opinion; to make a different decision
* Harold was going to spend the weekend at the coast, but then he changed his mind and decided to stay at home instead.
Comprehension Questions
1. Why is Stan struggling with his presentation?
a) Because he doesn’t understand the key concepts.
b) Because he doesn’t think the audience will understand it.
c) Because he gets very nervous when speaking in public.
2. What is Stan going to do to thank Tara?
a) He’s going to get her a reservation at the new restaurant.
b) He’s going to pay for her lunch.
c) He’s going to give her a nice thank-you note.
Answers at bottom.
What Else Does It Mean?
to jump out at
The phrase “to jump out at,” in this podcast, means to catch someone’s interest and attention: “The problem might not jump out at you right away, but I’m sure you’ll find it if you study the materials.” The phrase “to jump the gun” means to do something too early or too soon, without developing a careful plan: “Don’t you think you’re jumping the gun by marrying someone whom you’ve known for only a few weeks?” The phrase “to jump for joy” means to be very pleased, happy, and excited: “When Sheila received the job offer, she was jumping for joy.” Finally, the phrase “to jump down (someone’s) throat” means to shout or speak very angrily, almost attacking another person: “Stay away from Barbara today. She’s having a bad day and is jumping down everyone’s throat.”
to nail
In this podcast, the verb “to nail” means to do something very well or to meet one’s goal: “Wow, you really nailed that performance. Good job!” The verb “to nail” can also mean to arrest someone for a crime, or to prove that someone is guilty: “Laden was nailed for robbery, even though he still says he’s innocent.” The phrase “to nail (somebody) to the wall” means to punish someone very harshly: “The judge really nailed him to the wall, putting him in prison for 20 years.” Finally, the phrase “to nail (someone) down” means to define the terms of an agreement or the price of something: “We need to nail this down in writing before we start performing the work.”
Culture Note
Diploma Mills
A “diploma mill” or a “degree mill” is an organization that gives students “bogus” (not real; worthless) degrees in exchange for a “fee” (money paid for a particular service). Most of these institutions are found online. Unlike traditional schools, which require that students complete certain coursework and demonstrate their knowledge of a particular topic in order to earn a degree, diploma mills have very simple courses and few or no tests.
Diploma mills “lack” (do not have) “accreditation” (official recognition that an educational organization meets certain standards), and the students who pay to receive a degree there may or may not be aware of that.
“Critics” (people who are opposed to something and do not approve of it) argue that these programs used a “dumbed-down” (made for people who are not intelligent; very simple) “curricula” (plans for and materials used in teaching in school). They “point out” (draw attention to) the fact that the programs offer little or no interaction between students and professors. Students may be required to purchase textbooks, but they can pass the test with little or no studying. Some diploma mills simply award degrees without even the “pretense” (an attempt to make something appear true) of asking students to study or take an exam.
Individuals often seek degrees from diploma mills to “advance their career” (get a better job). However, when the quality of the degree “comes to light” (becomes known by others), it often results in legal trouble, especially for people working in politics or public positions. The diploma mills are “rarely” (not very often) “held accountable” (made responsible for their actions), so students must research schools carefully before trying to buy or earn a degree.
Comprehension Answers
1 - b
2 - b