= 1869
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 564.
This is English as a Second Language Podcast’s English Café episode 564. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and take a look at our ESL Podcast Special Courses. If you’re on Facebook, you can like us on Facebook. Go to facebook.com/eslpod.
On this Café, we’re going to talk about the American author Mary Roberts Rinehart. We’re also going to talk about a famous love song from the twentieth century, “I’ll Be Seeing You,” and as always, we’ll answer a few of your questions. Let’s get started.
Mary Roberts was born on August 12th, 1876, in the state of Pennsylvania. Pennsylvania is located in the eastern part of the United States, one of the original thirteen U.S. states. Mary Roberts began her career, her working life, as a nurse when she was 20 years old. In 1896, that same year, however, she married a doctor by the name of Stanley Rinehart and changed her name to Mary Roberts Rinehart. She kept what we would call her “maiden name,” or her last name before she got married. A “maiden” (maiden) is a non-married woman.
Mary Roberts Rinehart and her husband Stanley had three sons and one daughter. In 1903, the stock market had what we call a “crash” in the United States. The “stock (stock) market” is a place where you buy and sell, well, of course, “stock.” “Stock” is partial ownership of a company. When you “buy stock” in a company or when you “buy a company’s stock,” you are buying a certain percentage of that company. You own a small percentage of that company. A “stock market,” then, is a place where you buy and sell partial ownership of companies.
If we say a stock market “crashes,” we mean that the value of the stocks goes down quickly, goes down suddenly. All of a sudden, stocks that were worth a lot of money are not worth very much money. This means that the value of the companies themselves, of course, go down rapidly. From time to time – “periodically,” we would say – stock markets crash, and the U.S. stock market crashed in 1903.
This was very bad news for the Rineharts because they lost a lot of the money that they had because they had owned a lot of stocks. This meant that they needed to find other ways of making money. So, Mary Roberts Rinehart decided she would make money by writing stories and selling them. Writing came easily to Reinhart. She wrote 45 stories in 1903 alone, meaning in the period of just 12 months, she wrote 45 stories. Many of these stories appeared in a popular magazine at that time by the name of Munsey’s Magazine.
In 1908, about five years later, Mary published her first novel, called The Circular Staircase. This was a mystery novel about a woman named Rachael Innes who sees and hears strange noises and things at a summer home – a place where she lives during the summertime. A “mystery” describes a story usually about a crime that has been committed, often a murder. In the story, we find out who committed the crime, and throughout it, we are trying to figure out who the murderer is.
The Circular Staircase, then, was a mystery novel, and it was successful – that is, Reinhart managed to sell many copies of her book. The next year, she wrote another mystery novel, this one called The Man in the Lower Ten. It tells the story of a lawyer who wakes up from a nap – from a short period of sleeping – on a train, to find that all of his papers have been stolen. Ooh, what happened? Well, to find out you have to read the mystery.
This second book was also very popular and it helped solidify Rinehart as a popular mystery writer in the United States. “To solidify” (solidify) means to make stronger. So when we say the second book “solidified” her reputation as a great or popular mystery writer, we mean that it helped make certain, it provided even stronger evidence that she was in fact a good writer, or at least a writer that people wanted to buy.
Rinehart began writing and publishing about one new mystery novel every year beginning after the success of her second novel. In 1911, she created a character for her novels by the name of Letitia Carberry, or “Tish” for short. Tish was a middle-aged, unmarried woman who did things that women during this period tended not to do. “Middle-aged” describes someone who is neither old nor young. I guess we could say “middle-aged” is probably someone nowadays between the ages of, say, 45 and 65.
Tish and her friends in these novels did things that other women did not commonly do. They flew in airplanes. They drove race cars. They hunted bears. They hunted animals. They were exciting things that they did – shocking things, really, for women to do in the early part of the twentieth century. The fact that the people in her novels, the women in her novels, did these things that were unusual for women to do during this period made the novels all that more popular.
In addition to the five books that Rinehart wrote about this character Tish, she continued to write short stories that were published in magazines such as the Saturday Evening Post. In fact, Tish continued to appear in stories in the magazine, and it helped Rinehart continue her popularity as a writer. Beginning in 1914, Rinehart started to write romances in addition to the mysteries that she was writing. A “romance” (romance) is a book or a movie about love, about two people falling in love.
Rinehart, then, was writing both mysteries and romances in addition to the short stories that she would write. These were the main forms of “fiction,” or made-up stories, that she was making money off of. Rinehart’s romance stories were popular, although many of the people didn’t think that they were as good as her mystery stories that she had become famous for.
Although it’s not always true that novelists write about their own lives, it was somewhat the case with Mary Roberts Rinehart that the novels reflected some of her own problems and issues. In most of the novels, the married couples are unhappy, but the mothers and the children in the stories have good relationships. In real life, Rinehart’s husband was not very happy that his wife was much more successful than he was, and so in many ways her own marriage was not a particularly happy one. But as in the case of Rinehart’s novels, she did have a good relationship with her own children.
In addition to her mystery, romance, and other fiction writing, Mary Roberts Rinehart also wrote plays. A “play” (play) is a story that is acted out upon a stage, in a theater, with actors and actresses. The first play that Rinehart wrote was called Seven Days, and it was performed in New York City in 1909, soon after she became popular as a novelist. Her second play was called The Bat, and that was actually based on her first novel, The Circular Staircase. It was first performed in 1920, also in New York City.
Mary Roberts Rinehart wrote for the rest of her life basically, until 1958. During the nearly 55 years that she wrote, she published more than 50 books, eight plays, and hundreds of short stories. By the time she died, she had sold over 10 million copies of her books, many of which remained popular long after her death.
If you are a lover of mystery stories in English, you may have heard of Mary Roberts Rinehart. Her books are no longer popular the way they were in the early part of the twentieth century, but they are still considered by lovers of mysteries to be wonderful books, wonderful stories, wonderful novels.
Now let’s turn to our second topic, which is a famous song also from the middle of the twentieth century, a song by the name of “I’ll Be Seeing You.” This song was written in 1938 for a Broadway musical called Right This Way. A “musical” (musical) is a performance similar to a play, except the actors, in addition to talking, also sing and dance during the performance.
This particular musical told the story of a man and a woman who meet in Paris and fall in love. How romantic. But then the man, from the United States, has to go home. This causes him to leave the woman with whom he has fallen in love behind in Paris. After he leaves, the woman – played in the original musical by the actress Tamara Drasin – sits at a cafe and she sings about her love. She sings,
I’ll be seeing you
In all the old familiar places
A place that is “familiar” (familiar) is a place you know. She’s saying, then, that she will see her love in all of the places that the two of them know. We think, of course, that she means that as she goes to the places that the two of them know, she will be reminded of her love even though he isn’t there.
I’ll be seeing you
In all the old familiar places
That this heart of mine embraces
All day through
The “places” are places that her heart “embraces” (embraces). “To embrace” means to hold something. You embrace the one you love. You may embrace your husband or wife or child. The heart “embraces” the places that are familiar to the woman singing the song. These are places that are close to her heart, are close to her – the parks, the trees, the time of day, even, will remind her of the person she loves.
I’ll be seeing you
In all the old familiar places
That this heart of mine embraces
All day through
She misses her love, of course. While the song was first performed in 1938, the musical for which it was written was not very popular and did not become a success. However, a few years later, in 1943, one of the most popular singers in the United States at that time, Mr. Bing Crosby, decided to record the song himself.
Remember, in 1943 the United States was involved in World War II, and millions of men were fighting in other countries, away from the women they loved. This song, then, was popular not only with the soldiers and sailors, but also with the girlfriends and wives who were back here in the United States. In fact, in 1944 it was the most popular song in the United States.
Interestingly, another famous popular singer in the U.S., Frank Sinatra, had recorded “I’ll Be Seeing You” a few years later in 1940 with one of the most popular bands of that time, the Tommy Dorsey Band. Even though they recorded the song, the song had never been released. It had never been made available for people to buy and listen to. Sinatra decided to release the song in 1944.
It was already a popular song, and this became for him one of his signature songs. A “signature song” is a song that the singer, an artist is famous for singing. It’s one of the most popular songs of that particular singer. Sinatra, even though it had already been made famous by Crosby, made the song his own, in a way, by releasing his own version. But it wasn’t just Crosby and Sinatra who decided this was a good song to record and sell. A third popular singer, Billie Holiday, a famous female jazz singer, recorded yet another version of the song and this one became popular as well.
So, you had three famous singers recording the same song and releasing that song within the period of two years, but because everyone loved the song so much, all three of the versions were popular. The Billie Holiday version became popular again more recently, back in 2004, when it was used for a movie called The Notebook, a love story based on the novel by Nicholas Sparks. Over the years, still other singers have recorded this song, including Dean Martin, the Carpenters, Willie Nelson, and the Scottish singer Rod Stewart.
The song has become a “classic,” you could say, about lost love or about people who are separated from their lovers. The two people who wrote the song really believed in the song. They knew that someday it would become popular. Sadly, one of those writers died in 1942, before the song had become well known, but he believed that someday people would sing the song about the painful experience of being separated from the one you love, and he was right.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Ivan (Ivan) in Russia. Ivan wants to know about the meaning of three terms or words that he heard in a recent popular movie called The Martian with Matt Damon. One of the words that he heard was “dispense” (dispense). “To dispense” means to supply others with something or to provide something from someone. We often use this verb “to dispense” when we are talking about a pharmacist or a druggist who is giving medicine to a person who needs it. We talk about the pharmacist “dispensing medication” or “dispensing drugs” to a person.
Another word Ivan had a question about was “wedgie” (wedgie). Well, the term “wedgie” is something that you will hear children use, perhaps. A “wedgie” is produced by pulling someone’s underwear up from the top of the underwear towards the top of the person’s body so that the underwear becomes . . . well, let’s just say fixed very firmly in your behind – in your butt, or in between the two parts of your butt. That is called a “wedgie.” The verb would be “to give someone a wedgie.” It’s a thing that I suppose teenagers do to be funny with each other.
A third term Ivan didn’t understand was “on principle” (principle). To do something “on principle” is to do something because you believe it’s true or because you believe in a certain idea. The sentence that Ivan heard in the movie is, “And if I ever met a botanist like me, he’d dispense a wedgie on principle.” A “botanist” is a scientist who studies plants.
I have no idea what that sentence means, Ivan. I can only guess, but my guess would probably be wrong. “To dispense a wedgie” is somewhat of an unusual way of saying “to give someone a wedgie.” The word “dispense” makes it seem as though it were a prescription, something the doctor would order you to receive. I don’t understand the rest of the sentence to be quite honest with you. I’m sure if I watched the movie The Martian it would make more sense to me, but sadly, I haven’t seen it yet.
Our next question comes from Victor (Victor) in Ukraine. Victor wants to know the meaning of three phrases: “to get on with something,” “to get along with someone,” and “in a nutshell.”
“To get on with something” means to make progress in doing something, to continue to do something after stopping for a short time. If, for example, you are working on a report at your office and someone interrupts you – someone stops you from working to talk to you for five minutes or 10 minutes – you might say to that person, “Well, I have to get on with my report,” meaning I have to go back and continue working on it so I can make progress on it.
“To get along with someone” means to have a friendly relationship with the person, to not have any problems with the person. You could say, “I get along with everyone at work.” That means I’m friendly with everyone and everyone is friendly with me. We don’t have any serious personal problems. We can talk and communicate with each other and be very friendly about it.
Now interestingly enough, you can also use the phrasal verb “to get on with” with a person as well. You can say, “How do you get on with Mary?” You could say, “Oh, I get on with her very well.” That means that you get along with her very well.
Finally, the expression “in a nutshell” (nutshell) means very briefly or in summary. A “nut” is, of course, very small. So the shell of a nut is very small. If you put something in a nutshell, you would be putting something in a very small place. So, the expression “in a nutshell” is used to mean very briefly or in summary.
For example, someone may be asking you for a favor, and this person may be talking for several minutes. You may interrupt the person and say, “So, in a nutshell what you want is to use my office today.” You’re giving a summary. You’re giving a very brief statement of a longer problem or a longer question. If someone asks you a question – “What happened at the party last night?” – you could say, “Well, I could tell you a long story, but in a nutshell, everyone had a good time.” That’s what happened. You’re giving a brief summary of the events.
Our final question comes from Jonnie (Jonnie) from the planet of Neptune. Jonnie wants to know the meaning of a prefix in English. He wants to know the meaning as well as how we pronounce it in American English. The prefix is (semi). It can be pronounced either “sem-ee” or “sem-eye.” The last vowel there can be pronounced either as an “i” or an “e.” There is no difference in meaning in how the prefix is pronounced.
Let’s define it and then talk a little bit more about its uses. One of the definitions of the prefix “semi” is “partially,” or not completely. It could also be used to mean “almost.” you could say, “I’m semi-awake.” That means I’m not completely awake. I’m still partly sleeping. Or you could say, “My homework is semi-finished.” It’s not completely finished. It’s partially completed. It’s partially finished. It’s almost finished.
The prefix is used before a couple of words to have a slightly different meaning, or a special meaning. One of those words is “circle.” A “semicircle” is not just part of a circle. It’s exactly one half of a circle – 50 percent, if you will, of a circle. If the teacher tells her students “to stand in a semicircle,” she means that they should form a half circle.
Another word we use this prefix in front of in a special way is “trailer.” A “semitrailer” is actually a truck that pulls a long trailer, a long vehicle, behind it. These are also referred to as “18-wheelers” because typically there are 18 wheels on the vehicle and the trailer. A “semitrailer” is also called sometimes simply a “semi.” In that case, “semi” is a shortened form of the word and for whatever reason is always pronounced with a long “i” sound instead of a long “e” sound.
So, when you are referring to a semitrailer, we always say “sem-eye,” not “sem-ee.” But if “sem-eye” or “sem-ee” is a prefix, then it could be pronounced either as an “i” or an “e.” So I hope that’s not too confusing for you, Jonnie. But up on Neptune they probably don’t have any semis, so you don’t really have to worry about it, do you?
If you have a question that you’re worried about, email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
stock market – the part of the financial market where portions of companies are bought and sold
* The stock market is affected by many factors, such as oil prices and government policies.
to crash – to fall suddenly and by a large amount, losing much of its value; to fall suddenly and violently
* The value of gold crashed overnight, reaching the lowest prices in the past 20 years.
mystery – a movie, play, or book that describes a crime that is difficult to solve, usually a murder
* In the mystery novel Murder on the Orient Express, a man is killed on a train and the murderer or murderers are trapped on that train.
to solidify – to make something stronger; to reinforce something
* Being offered her dream job solidified Mary’s opinion that moving to a new city was the right decision.
middle-aged – a person who is between early adulthood and old age, usually age 45 to 65
* After his long illness, Daniel looked middle-aged, not 33 years old.
romance – a movie, play, or book about a love story
* The romance novel told the story of a rich woman and a poor man falling in love.
fiction – a short story or novel that describes imaginary people or events
* Some fiction is so realistic that it’s difficult to believe that the characters and story aren’t based on real people and events.
play – a story that is acted out on a stage by actors and actresses
* During the play, one of the actors started coughing and couldn’t say his lines.
musical – a performance where actors on stage sing and dance, as well as speak lines of dialogue
* The final song in the musical was a happy and upbeat one, involving all of the actors and actresses dancing and singing on stage.
to embrace – to hold someone or something closely in one’s arms
* When Jacque got off the airplane, his father embraced him.
signature song – a song that a singer or band is best known for performing
* The band played the singer’s signature song as she walked onto the stage.
to dispense – to supply to others; to give to many people
* Her mother dispenses cooking advice to Julia whether Julia wants it or not.
wedgie – the act of pulling the back of someone's underwear quickly in an upward motion as a joke or prank
* The boys thought it would be funny to give the new student a wedgie in the locker room.
on principle – in order to show one's acceptance and support of a particular belief
* Ros is an animal lover and doesn’t eat meat on principle.
to get on with (something) – to make progress in doing something; to proceed despite hesitation; to continue after a temporary pause
* Stop talking about it and get on with it. This deck isn’t going to build itself!
to get along with – to have or establish a friendly relationship with someone; to have smooth relations with another person
* Did you get along with all five of your brothers when you were growing up or were there a lot of fights?
in a nutshell – very briefly; in summary
* In a nutshell, our vacation was a disaster from beginning to end.
semi – partial; partially; not completely; almost; a short heavy truck that has a long trailer attached to the back
* After being hit by a car, Mina was semi-conscious and wasn’t able to give a description of the car or the driver.
What Insiders Know
Howcatchems
In a traditional detective story, a “crime is committed” (someone does something that breaks the law) and then the “detective” (a police officer or other professional who investigates crimes) has to “figure out” (research and determine through hard work) who did it and how. Sometimes this is called a “whodunit” (“who has done it”), because the detective and the reader are trying to figure out who committed the crime.
In an “inverted detective story,” this is “reversed” (backward; the opposite). An inverted detective story begins with a detailed description of the crime, including who committed the crime and how. Then, the rest of the book “follows” (covers, presents, and talks about) how the detective “caught” (apprehended) the “criminal” (the person who committed the crime). These inverted detective stories are known as “howcatchems” because the reader wants to find out how the detective caught the criminal.
The best-known howcatchems are from the American TV show Columbo, which was “aired” (shown on television) from 1971 to 2003. Each episode “features” (is primarily about) a man named Columbo, a police detective, as he figures out who committed a crime. Almost all of the episodes begin with the viewers seeing the crime “unfold” (happen; occur). Viewers get to “observe” (see) the criminal’s “reaction” (response) to Columbo’s presence as he “gets closer to the truth” (begins to realize what actually happened). Columbo normally has a friendly relationship with the criminal until the end of the show, and the viewers rarely get “insight into” (a true understanding of) Columbo’s thoughts until the end of each episode.