= 1890
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 585.
This is English as a Second Language Podcast’s English Café episode 585. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast Store with additional courses in business, daily, and cultural English. You can also like us on Facebook. Go to facebook.com/eslpod.
On this Café, we’re going to talk about the American writer Truman Capote. And as always, we’ll answer a few of your questions. Let’s get started.
Truman Capote was born Truman Persons in September of 1924 in New Orleans, Louisiana. His parents divorced when he was a child, and later he changed his last name to that of his stepfather, which was Capote. “To divorce” (divorce) means to legally end a marriage. Your “stepfather” (stepfather) is a man married to your mother but who isn’t what we would describe as your “biological father.” He wasn’t there when your life began, shall we say. Of course, if your biological father remarries, we would call that woman your “stepmother.”
Your stepmother or stepfather’s children would be “stepchildren.” If your stepfather or stepmother had biological children, then you would refer to them as your “stepbrothers” and “stepsisters.” Not everyone who divorces and remarries someone who already has children legally adopts those children, legally makes those children his stepchildren or her stepchildren, though it is quite common if children are still young when the divorce takes place. In any case, Truman Capote changed his name to Capote, from his biological father’s last name, Persons.
After the parents divorced, Capote was sent originally to live with some aunts and uncles in the state of Alabama, which like Louisiana is located in the southern part of the United States. Louisiana is in the southern-central part of the U.S. Alabama is east of Louisiana. It goes Louisiana, then Mississippi, then Alabama, and then Georgia, as you move east from Louisiana.
Capote lived with his relatives but he did not have a happy childhood. He felt unloved by his parents because they had sent him to live with his aunts and uncles. He didn’t have many friends, and many of the other children who lived in the small town where he lived teased him. “To tease” (tease) means to make fun of someone, usually in a way that is funny or is supposed to be funny but sometimes is considered mean. He had one good friend growing up. Her name was Harper Lee. You might recognize that name, Harper Lee, because she, like Capote, also grew up to be a writer.
She wrote one of the most famous American novels of the mid twentieth century, To Kill a Mockingbird, and it is said that one of the main characters in that story is based on Truman Capote. “To base (base) something on” means to use a person or an event as a starting point for a new idea – to take the essential elements of a person’s character or events and use those as a way of creating something fictional, something made up. Harper Lee and Truman Capote met when they were only five years old and continued as friends throughout their entire life.
In 1932, Capote moved to New York City to live with his mother and stepfather. His mother was not kind to Capote and she also teased him for being shy and not behaving or doing what other children did. Truman’s stepfather was nicer to him, however, and in 1935 officially adopted Capote. “To adopt” a child means to make that child legally part of your family.
Capote didn’t like school (who did?) and didn’t do very well in his classes. This did not mean, however, that he wasn’t intelligent. In fact, some say he taught himself to read and write, but he was not interested in going to college after he graduated, or finished, high school. Instead, he got a job working at one of the most famous magazines in the United States, The New Yorker.
He also began trying to get his own stories published, or to appear in a magazine or newspaper. Many of Capote’s early stories were based on his own experiences as a child, and they included people who often felt unloved and alone, as he felt. Finally, in 1945, Capote was successful in getting a short story published. It was called
“Miriam.” It was about an old woman who meets a very strange young girl one day and whose life is never the same after that. The story won a famous award called the O’Henry Award in 1946. The O’Henry Award is given to the best short stories.
Capote continued writing and continued getting his stories published. In 1948, he published his first book, which was called Other Voices, Other Rooms. In 1951, he published a second book, called The Grass Harp, which was later made into a play. In 1958, Capote published one of his two most famous works. It was called Breakfast at Tiffany’s, and it told the story of a young woman named Holly Golightly who gets involved with many different men but who is optimistic even though the reader knows that she doesn’t seem to have much reason to be optimistic.
“Optimistic” (optimistic) is thinking that things in the future will go well – having a positive view or outlook, we might say, on life. The opposite of someone who is “optimistic” is “pessimistic” (pessimistic). If you’re pessimistic, you think things are going to be bad in the future. The character in Capote’s novel was optimistic. The title Breakfast at Tiffany’s refers to a very expensive jewelry store that has its main store in New York City. It’s called, of course, Tiffany’s. You might be familiar with Tiffany jewelry. It’s considered expensive and is very well known.
In the story, Holly says that nothing bad can ever happen at a Tiffany store. So she goes to visit the store whenever she’s feeling sad. The book was successful, but even more successful was the movie that was based on the book. In 1961, the movie – starring, of course, Audrey Hepburn – became an American classic. It’s still a movie that people watch today. When I say it became a “classic” (classic), I mean it became something that people thought was of the highest quality, that would last for many years.
After publishing the book Breakfast at Tiffany’s, Capote became more and more interested not in writing novels, but in journalism. “Journalism” (journalism) is the profession of writing news stories, traditionally for newspapers or magazines, although nowadays we have journalists who are on television, the radio, and of course the internet. Someone who works in the field or area of journalism is called a “journalist” or a “reporter” (reporter).
Capote, as he got interested in journalism, decided to write a book that was not fictional or made-up, but what we would describe as “nonfiction.” “Nonfiction” is something that talks about real or actual events and people. The name of Capote’s nonfiction book – his first one, that is – was called In Cold Blood. The expression “in cold blood” refers to killing someone not out of anger or because you are fearful the person might hurt you, but simply because you want that person dead.
So “to kill someone in cold blood” means that your blood wasn’t hot because you were angry – metaphorically, of course – but rather you had planned it. It was something you did rationally, if you will. The book was about a real murder, about two men who kill an entire family in the state of Kansas. Kansas is in the middle of the United States, in the very center of the U.S. The book actually began as a long article in The New Yorker magazine. The New Yorker magazine is famous still for publishing long, detailed nonfiction stories.
Capote got so involved in the story, however, that he ended up making it an entire book. Capote and his friend Harper Lee actually went to Kansas many times to visit the two men in prison – while they were on trial and while they were waiting to be executed. “To be on trial” (trial) means that you have been arrested and accused of a crime. The government says you broke the law, and you are now in the process of a court case, where the judge and a group of people known as the “jury” will decide if you are guilty or innocent.
The two men were found guilty of murdering this family, and they were later sentenced to death. They were told that they would be killed by the government because of their crime. The verb we would use here is “execute” (execute). “To execute” a person means to kill that person because he has been found guilty of a crime. The verb “to execute,” however, has other non-lethal, non-deadly meanings. “To execute a plan” means simply to carry it out. But “to execute a person” means to kill that person, usually because the person has been found guilty of a crime.
These two men were found guilty and executed. But before they died, Capote and Harper Lee had interviewed them, though Capote was the one who was doing the writing. Harper Lee herself helped edit the book before it was published. When the book was published, Capote became incredibly famous. The book itself was very, very successful and was one of the first nonfiction books about a crime that made a lot of money. It was the first of many books that described crimes and that became popular bestsellers.
Other authors started to write about famous crimes, and “publishers,” the people who make books, began getting interested in real crime or true crime stories because if they were told well, told almost like a novel, people bought them and they were popular. Capote was incredibly popular not only as a writer but also as what we might describe as a “socialite.” A “socialite” (socialite) is someone who is well-known in society, who spends time with rich and powerful people.
A lot of famous people you see in magazines and on television could be described as socialites. They spend their time with rich and powerful people. People loved having Capote at their parties because he was funny and he told interesting stories. Many people later said, however, that the story that Capote told in In Cold Blood had many errors in it. That in fact Capote had invented or made up some of the details of the book. Capote denied this, said everything he wrote was true.
In any case, Capote was a popular man in the mid and late 1960s. He loved to gossip and know everything about people’s personal lives. “To gossip” (gossip) means to talk about people’s private information, even though it may not be true. Capote later used some of the gossip he learned from famous people in another book, called Answered Prayers. When parts of that book were published in 1975, not surprisingly, many of Capote’s friends were quite angry that he had used this private information to write his book.
The publication of In Cold Blood, although it made Truman Capote a household name – that is, everyone in America knew who he was – had a very negative effect on Capote’s own life. He became addicted to certain medication, certain drugs. “To be addicted” (addicted) means that you are dependent on, or that you require, a certain substance or perhaps a certain activity, and if you don’t have it, many bad things happen to you. You can’t survive without it. He became an alcoholic. He became addicted to alcohol and started drinking too much.
When he was asked to stop taking the medicine, he was unable to, and had difficulties in his personal relationships as well. Capote died in August of 1984 after having many health problems related to these addictions. He is still a well-known name, however. There was a well-known movie made about the life of Truman Capote a few years ago called simply Capote. It starred one of the great actors of our generation, Philip Seymour Hoffman. Sadly, Hoffman himself died of a drug overdose a few years later.
On that happy note, let’s answer some of your questions.
Our first question comes from Alex (Alex) in Ukraine. Alex wants to know the meaning of three expressions or phrases: “to be understaffed,” “to be stretched thin,” and “to be on the brink of something.” “To be understaffed” (understaffed) means that you don’t have enough people in your job, or on a certain project, to do what needs to be done. The word “staff” refers to people who work for a company. If you go to a restaurant, the “staff” includes the waiters and waitresses, the cooks, the people who clean the tables, and so forth. All of those are “members,” we would say, “of the staff,” or are part of the staff.
Notice that the word is singular. We don’t say “staffs” unless we’re talking about different groups of people. A single group of people working for a company is referred to simply as the company’s “staff.” “To be understaffed,” then, means not to have enough people to do what needs to be done in a work situation.
“To be stretched (stretched) thin (thin)” means to have too many things to do at the same time and not, therefore, enough time to do everything well or to do everything that needs to be done. If you say, “Well, I’m really stretched thin right now,” you mean you have a lot of different projects, usually at work, that don’t allow you to do everything you should be doing or to do anything else besides what you’re already doing.
You could describe a company, perhaps, or a group within the company as being “stretched thin,” meaning they’re doing too many things at the same time. If a company is “understaffed,” the people who are there will probably be “stretched thin.” So there is a relationship between the two expressions, or could be. A company that doesn’t have enough people working for it would have to give more and more work to the people who are there, and they wouldn’t have enough time to do everything that needs to be done, so they would be “stretched thin.”
The final expression is “to be on the brink (brink) of” something. “To be on the brink of” something means that you are close to some event. It’s often a bad thing that you are close to. We might describe someone being, for example, “on the brink of bankruptcy.” “Bankruptcy” is when you don’t have enough money to pay all of your bills. You could describe two countries as being “on the brink of war.” They’re very close to starting a war with each other. They’re not there yet, but they’re very close.
You might be “on the brink of disaster.” “Disaster” (disaster) is a very bad situation, when something really bad happens. If your company is understaffed, and everyone working there is stretched thin, the company might be on the brink of bankruptcy or a disaster because it is unable to do what it’s supposed to do.
Our next question comes from Silvie (Silvie) in France. The question has to do with expressions you use when someone thanks you for something. We’ve talked about this on other Café’s, I’m sure. This question is about three expressions used in that situation of responding to someone who thanks you for something. One of them is “Don’t mention it.” The second one is “You’re welcome.” And the third one is “My pleasure.” How do we use these three expressions?
The most common and probably the most formal one, the one that you can always use, is “You’re welcome.” If someone thanks you for something, you can simply say, “You’re” – or “you are” – “welcome” (welcome). That’s the one that you can use in almost every circumstance.
“My pleasure” (pleasure) is also somewhat formal and is usually used in a situation where someone works in a business or is doing something for you in a business relationship. If you go to a store, for example, and the person who works for the store helps you and you say, “Thank you,” the person might say, “You’re welcome,” but probably would say something more like, “My pleasure.”
“My pleasure” means literally “It was something that gave me pleasure” – something I enjoyed doing. “My pleasure” is a good thing to say in a business situation like this because you are in fact helping the person who is paying you money. So in some ways, the person doesn’t really need to thank you, and so saying “My pleasure” is a way of saying you don’t have to say that because this is something good for me – which, of course, for a business it is.
Your waiter or waitress in a restaurant might say that when you say, “Thank you.” They may say, “Oh, my pleasure.” It is often said, then, in those business settings or in a situation where you are the customer or a client thanking someone who is giving you help or service.
The third expression is the most informal of the three, “Don’t mention it.” “Don’t mention it” would not typically be used in the same situations as “My pleasure.” “My pleasure” is used in situations where that person works for a company and I’m a customer or client. “Don’t mention it” could be used with friends, family members, or even strangers whom you help in some small way.
If someone asks you to give him a ride to the store, and you do that in your car and he thanks you, you could say, “Don’t mention it.” Another common expression that I would probably use in that case would be “No problem” or “It was no problem.” I probably would not use it with my boss or in a work situation unless the person thanking me was at the same level as I was.
You know sometimes people thank you to be polite, to be nice, even though they don’t have a good reason to thank you, even though it’s a situation where you’re doing what you’re supposed to do or what you are being paid to do. I would not use it in those cases. I would use it in cases where I actually am helping someone because I’m being a nice person and that person is thanking me for helping him.
This is a good question because the exact cases or situations when you would use each of these expressions is a little bit different, and it’s one of the things that you get mostly just by doing a lot of reading and listening to English conversations.
Our final question is from Christophe (Christophe), also from France. The question has to do with the expression “I think he’s the bee’s knees.” Well, this is an interesting expression, “the bee’s (bee’s) knees (knees).” This is an interesting expression and I have to say not one that you hear very often anymore, though you might read it in a book, an older book.
A “bee” is, of course, a little insect that flies around and can hurt you by “stinging” you, we would say. Bees are often yellow and black in color. Your “knees” are where the top part of your leg is connected to the bottom part of your leg, where your leg bends. Your arms have a similar joint called the “elbows” (elbows).
Now, the expression “bee’s knees” has nothing to do with your actual knees or with insects. It’s a very old expression that became popular in the United States back in the 1920s. It means the very best of something, the absolute greatest of a certain thing. There are different theories about where the expression comes from, but the meaning is clear enough. It means the height of excellence – something that is really, really good. If you say, “I think he’s the bee’s knees,” you mean he’s the best. He’s the greatest at something, or simply a really great person.
Well, I think you are the bee’s knees for listening to us. If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
stepfather – a man married to one’s mother, but who is not one’s biological or birth father
* Jeremy’s father died when he was only two years old, so the only father he has really known is his stepfather.
to tease – to make fun of someone in a playful or mean way
* It hurt Nicola’s feelings when the other children teased her and called her a giraffe because she is very tall.
to be base on – to use something as the starting point for a new idea or creation
* The architect’s design for the new music center is based on 17th century Japanese architecture.
to adopt – to legally make a child part of one’s family and raise him or her as one’s own
* The couple decided to adopt a child after unsuccessfully trying to have a child of their own.
optimistic – feeling positive and hopeful about the future; feeling confident that good things will happen
* Despite many setbacks, Karen is optimistic that she’ll earn her college degree.
classic – something thought to be of the highest quality and the best of its kind
* Students read classic novels in school so they can become familiar with famous authors and important works.
journalism – the activity or job of writing news stories for newspapers, magazines, the Internet, and other outlets
* Mona works in journalism, reporting the news from war zones.
nonfiction – writing that is based on facts, real events, and real people
* Joanna likes to read nonfiction, mainly books about economics and marketing.
to execute – to carry out a death sentence on someone who has been found guilty of committing a crime; to kill someone
* The soldiers found guilty of war crimes were executed at dawn.
socialite – a person who is well known by fashionable people and who spends time with the rich and powerful
* Some of the most well known socialites came from very rich families and spend their time at parties and traveling around the world.
to gossip – to talk and exchange private information about other people that may or may not be true
* When he started to repeat a story he’d heard about a boy at school, his mother told him he shouldn’t gossip.
addicted – physically and mentally dependent on a particular substance and unable to stop taking it without having negative effects
* After having surgery on her leg, she was given pain medication and quickly became addicted to it.
to be understaffed – to not having enough workers in a business or organization; to have too few people doing the required work
* The restaurant is understaffed so diners are waiting a long time to get served.
to be stretched thin – for a person or group to be doing too many things at the same time
* With so many people on vacation in August, our staff is stretched thin.
to be on the brink of – to be close to the occurrence of something, usually something very bad; to be nearly at or close to
* Trust Bank is on the brink of collapse so Lina is rushing there to withdraw her money.
don’t mention it – a polite response to thanks; a polite expression used to indicate that an apology or an expression of thanks is not necessary
* A: Thanks for giving me a ride.
B: Don’t mention it.
you’re welcome – a polite response to thanks
* A: Thank you for your donation.
B: You’re welcome.
my pleasure – a polite and somewhat formal reply to thanks
* A: Thanks for taking me out to dinner.
B: It was my pleasure.
What Insiders Know
The O. Henry Award
Almost every year since 1918, the O. Henry Award has been “bestowed” (given with a lot of honor) to American authors who have written “exceptional” (excellent; very good) short stories. These stories are also featured in a “collection” (group of writings published together) called The PEN/O. Henry Prize Stories.
The stories must have originally been written in English and they must have been published in a U.S. or Canadian newspaper, journal, or magazine. An editor selects 20 stories for consideration, and they are given to three “jurors” who decide, without viewing the author information, which of the stories are exceptional. The jurors also write “commentary” (a description of one’s opinion about something) about the stories they have selected.
The PEN/O. Henry Prize Stories contain the winning short stories, the jurors’ commentaries, descriptions from the writers about what “inspired” (made them think of something) to write the stores, an introduction from the editor, and a “resource list” (information that other people can use to learn more about a topic) of magazines that published the short stories.
The O. Henry awards are named in recognition of the “pen name” (the name that an author uses for publishing, but not his or her real name) of William Sydney Porter (1862-1910), who published more than 250 short stories in the early 1900s. His most famous short stories include The Gift of the Magi and The Last Leaf.
Some authors have been recognized with the O. Henry Award “multiple” (several; many) times. For example, author Joyce Carol Oates has appeared on the list 29 times, followed by Alice Adams, John Updike, and William Faulkner. More than 200 of the short stories were originally printed in The New Yorker magazine, and more than 100 have been published in Harper’s Magazine and The Atlantic Monthly.