= 1868
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 563.
This is English as a Second Language Podcast’s English Café episode 563. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our web site at ESLPod.com. Why? Because you can become a member of ESL Podcast and you can take a look at our ESL Podcast Store that has additional courses in Business and Daily English.
On this Café, we’re going to talk about perhaps one of the biggest sporting scandals in American history – one of the great things that many people were shocked by in the sporting world. I’m referring to the Black Sox Scandal of 1919. We’re also going to talk about another classic American television show, The Flintstones. And as always, we’ll answer a few of your questions, of course. Let’s get started.
In 1923, fans of American baseball became aware of, or found out about, one of the biggest scandals in the history of the great American pastime, which is another term for baseball. A “scandal” (scandal) is an action or an event that is legally, morally, or ethically wrong that makes the general public very angry – that makes the average person angry.
“Scandal” has another slightly different definition, which is the action of any person that would cause another person to perhaps do something immoral or unethical. That’s an older definition of “scandal.” Nowadays we use the word to refer to any shocking thing that is done that causes a lot of people to pay attention to it, especially in the newspaper or on television.
But individuals who are not famous can also cause a scandal – or to use an older expression, “give scandal” – by doing things in their own lives that are immoral or unethical that other people find out about and that may influence their future decisions, especially if they decide to do things that are similarly immoral or illegal or unethical – in effect, to cause other people to do immoral things by your own actions.
The baseball scandal was about eight players on a professional baseball team in Chicago called the “White Sox.” Before 1900, this team, the White Sox, was called the “White Stockings” (stockings). “Stockings,” nowadays, we call simply “socks” – things that you put over your feet in order to put on a pair of shoes, or before putting on a pair of shoes. You don’t have to wear socks to wear shoes, of course. The word “stockings” is another word for socks.
In American baseball, there are actually two teams that use the word “socks,” but they spell it (sox), which is just a different, unusual way of spelling “socks,” normally spelled (socks). There is the Chicago White Sox and the Boston Red Sox. But that’s not important to our story. The Chicago White Sox were involved in this scandal that included eight players.
The eight players were accused of “throwing” the 1919 World Series game. Now, there’s a couple of things for you to understand to know what that sentence means. The first is the term “World Series.” The “World Series” in baseball is the championship set of games played at the end of the baseball season, or the time of year when baseball is played, which is in the spring, summer, and fall. The World Series is a competition, a contest between the two best teams in baseball that year. It’s sort of like the finals of the World Cup, to put it in football – or I should say, “soccer” – terms.
The 1919 World Series was a game, a set of games, between the Chicago White Sox and the Cincinnati Reds. The Cincinnati Reds was another professional baseball team. So, these eight players on the Chicago White Sox were accused of throwing the World Series. “To accuse” (accuse) someone, or a group of people, means to say that this person or these people committed a crime or did something wrong.
The key expression here, however, is “to throw (throw) a game.” “To throw a game” means to lose a game on purpose – to try not to win a game, but rather to lose the game. Now normally when you are playing a game or you are in a competition, you’re supposed to try to win. Instead, these players tried to lose. Why did they try to lose? Well, one reason athletes may throw a game is because they’re being paid – they will make more money losing the game than winning it. Someone may be paying them, especially someone involved in gambling.
“Gambling” (gambling) is when you try to win money by betting or giving money to someone in the hopes that a certain thing will happen. People often “bet” (bet) in card games like poker. That’s a kind of gambling. You are hoping to win more money if a certain thing happens. This is exactly what the eight players on the Chicago White Sox were accused of. They were accused of throwing the World Series because they were being paid.
The most famous player on this White Sox team was a man by the name of Shoeless Joe Jackson. Many people thought Shoeless Joe Jackson was the best baseball player of his generation, of his time. Maybe even the best baseball player who ever played baseball. After the World Series game, one of the reporters, one of the people working for a newspaper, reported that these men had thrown the game. He believed that the White Sox were just too good of a team to have lost the World Series. People ignored this reporter, however.
But in 1920, the following year, it was in fact revealed, or it became known, that gamblers had become very involved in the game of baseball. A “gambler” is a person who gambles, who tries to bet in order to win money. These gamblers were betting money that certain baseball teams would win certain games. In this case, the gamblers bet that the White Sox, who were considered a great team that year, would lose the World Series in 1919.
In order to make sure that they won their bets, the story went that the gamblers gave the players money to lose the game. This apparently is what happened in the 1919 World Series. Many of the players admitted yes, they in fact had been paid money to lose the game, including Shoeless Joe Jackson.
The owner of the White Sox, a man by the name of Charles Comiskey, decided to suspend the players involved in this scandal. “To suspend” (suspend) means to no longer allow a person to do his job for a short period of time, usually until an investigation can be completed, or perhaps simply as a punishment for doing something wrong.
The men were actually arrested for their crime and they went on trial. They had to go in front of a judge. Interestingly, the men were found innocent of throwing the games even though they had already admitted that they had done so. This is because some of the evidence, some of the proof that they had admitted doing wrong was stolen by someone before the trial and so the court, the judge, didn’t actually have that evidence in front of them.
Even though the men were found innocent, they were banned from the sport of baseball after their legal trial. “To ban” (ban) someone is to no longer allow a person to participate in a certain activity – in this case, from the game of baseball. Well, from the professional game of baseball. The men could still play baseball. They just could not play in the professional baseball league or organization.
This was a great scandal because many people thought that this pure American game, this much-loved American game, had become dirtied. It had become made impure somehow by this horrible scandal of men actually cheating, of throwing the game – not only a game, but the most important set of games in professional baseball: the World Series.
Historians looking back at this scandal treat it or consider it a little differently than it was treated during the 1920s when it took place. Many people point out or state that these baseball players were not paid very much money at the time. Shoeless Joe Jackson, for example, the best player in the world of baseball during this period, was only paid about $6,000 a year, which would be about $83,000 in today’s money. $83,000 seems like a lot of money to us perhaps, but baseball players nowadays make at least a half a million dollars and often several million dollars a year.
Other historians point out that the owner of the White Sox, Charles Comiskey, wasn’t a very nice person and he would often not give the men, the baseball players, their salary each year even though he was supposed to. A “salary” (salary) is the money you get for doing your job. This meant that while Shoeless Joe Jackson, for example, was supposed to get $6,000 a year, sometimes he didn’t, because the owner decided he didn’t want to pay him because he was unhappy for some reason.
Nevertheless, historians don’t say that it was okay that these players cheated – that they acted dishonestly – but it does at least help us understand why the men may have done what they did. People still talk about the great baseball scandal, the White Sox scandal of 1919, as being perhaps one of the worst things that happened to baseball.
Others point to more recent scandals, especially the use of drugs in professional sports – not just baseball, of course, but in many sports including the Olympics, where athletes take drugs to make them stronger. This has become a scandal, and perhaps even greater scandal for baseball as it has for other sports in recent years.
Our second topic on this Café is one of my favorite shows growing up as a young child, The Flintstones. The Flintstoneswas a popular cartoon, or animated television program, that was on from 1960 until 1966. “Animated” (animated) refers to a way of putting together a series of images or drawings to make it appear as though there were motion and movement. Another word for “animated” is simply “cartoon.”
The Flintstones were a popular cartoon in the early 1960s that continued to be shown in the ’70s and ’80s when I was growing up. What does the word “Flintstone” mean? Well, “flint” (flint) is a type of very hard stone that we believe was used in early human history for making tools and later for building. The Flintstones was a cartoon about a family that lived supposedly thousands of years ago in what we sometimes call the “Stone Age” – that period of human history between roughly 6,000 and 1,000 B.C. – before the birth of Christ.
I say “B.C.,” but historians nowadays often use the letters “B.C.E.” there instead of “Before Christ” in “B.C.” The “C” stands for “common” and the “E” stands for “era,” which is a long period of time. So, “B.C.E.” is “before the common era.” What’s the difference between “B.C.E.” and “B. C.?” Nothing really, except the letter “c” now means something else, but it’s the exact same idea.
In any case, The Flintstones was a funny cartoon about this family that supposedly lived back in the Stone Age. It was created by two of the most well-known producers of cartoons in the 1960s, William Hannah and Joseph Barbera. What was different about The Flintstones is that not only was it a cartoon, but it was a cartoon that was shown in what we call “prime time.”
“Prime time” is the period every evening when television audiences – the people who are watching television – are expected to be the largest. So between, roughly seven o’clock in the evening to 10 o’clock at night – or if you’re on the east and west coasts of the United States, between eight o’clock and 11 o’clock, Monday through Friday. This was a period of time when there weren’t cartoons on television. There were other sort of more serious, adult dramas and comedies on T.V.
But Hannah and Barbera managed to create a program, a cartoon program, that was shown in prime time, not just for children. As I mentioned, the show was about a family who lived in the Stone Age. In many ways it was typical of this kind of comedy. The husband, whose name was Fred, was not a very intelligent man. The wife, whose name was Wilma, was in fact smart.
This seems to be a common pattern in comedies, especially in the U.S., when you have a family involved. The husband isn’t very smart and the wife is. If you’ve ever seen The Simpsons, you see the exact same kind of pattern. The husband isn’t very intelligent but the wife is. That’s true in life, generally – I guess that’s why it’s also shown on television – at least in my family.
In any case, The Flintstones had a daughter whose name was Pebbles, and they had good friends, Barney and Betty Rubble whose son was called Bamm-Bamm. The term “pebbles” and “rubble” are both jokes in a way. A “pebble” is a small piece of rock, and “rubble” is a pile or a group of broken stones. The two families lived in a city called Bedrock.
The idea behind the show, the premise of the show, was that people who lived in the Stone Age acted just like us today. Of course, in order for it to be a comedy, it would have to have some relation to modern life, and so they made the people in the show have the same sort of problems and even the same kinds of technology we had today. They had cars, but they didn’t have motors or engines or run on gasoline. The cars were powered by your legs.
There were other kinds of jokes like this that made reference to or included examples of what we might call “prehistoric life.” “Prehistoric” refers to the time in human history before writing had been invented or before writing was used by a certain group of people. The two main characters in The Flintstones are best friends, Fred and Barney. They spend a lot of time together and they work together. Of course, in order to be a funny show, they also got into trouble together. A lot of people enjoyed watching The Flintstones – not just children, but adults as well.
Perhaps the most famous part of the show was something that Fred Flintstone would say, especially when he began the show. He would say the phrase “Yabba dabba doo.” “Yabba dabba doo” doesn’t mean anything in English. It was just a nonsense thing that Fred Flintstone would say because he was happy – “Yabba dabba doo.” I don’t know if a lot of people would recognize that anymore. You would have to be someone a little older, like me, who grew up watching the show as a child to recognize it, I think.
Because The Flintstones was a successful television series in prime time, they started making other animated or cartoon shows that were shown at night. This included The Jetsons, which I also grew up watching. The Jetsons was about a family that lived in the future, so the opposite of The Flintstones. Wait Till Your Father Gets Home was another animated show that I remember watching, growing up, in prime time.
Perhaps the most famous prime time comedy animated show is The Simpsons, which began in 1989 and continues even to this day – at least, as I record this episode in 2016. The Simpsons really owes its success – can thank for its success, in a way – to The Flintstones because The Flintstones was the very first animated show that was created for adults and children and shown in prime time.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Iryna (Iryna) in Ukraine. The question has to do with a few terms related to how we refer to places in the United States, some of them somewhat technical. The terms are “census designated place,” “community,” and “unincorporated community.”
Let’s start with the word “census” (census). A “census” is an official counting of people who live in a certain place or a certain area. In the United States, we have an official U.S. government census every 10 years. Every 10 years, the government counts everyone who is in the United States, getting their name, where they live, and so forth. The census is used for a lot of things, but primarily to determine how our government representatives are broken up or allocated among the people living in this country.
So, a “census-designated place” would be a place that the U.S. government uses in order to count people. The word “designated” here just means “officially chosen,” or somewhere specific that the U.S. government has decided to be part of this counting process. A “census designated place” would be anywhere that is not necessarily in a city or a town – in fact, somewhere that is not in an official city or town – but is still considered to have the qualities of a city and town.
It’s kind of a strange concept. For example, Stanford University is not a city, it’s not a town, but it might be considered a “census designated place.” It has some of the characteristics or qualities of a place and so the government considers it like a town. You might think of it that way. It has its own identity and so it is counted as if it were its own community.
That leads us to the next word, which is “community.” The word “community” is used to refer to a group of people who live in the same area. It could be in the same city or town. It could also refer to people in the same area within a larger city. Here in Los Angeles, we have many different communities. We have the community of Venice. We have the community of Playa Vista. We have the community of Hollywood. All of those are areas within the larger city.
The word “community” can be applied to these smaller areas within a larger city, or confusingly, to the whole city or area. We could talk about “the Los Angeles community.” So, it’s a word that can be used in many different ways in terms of how large an area or how or large of a group of people we’re talking about.
“Community” can also be used for groups of people who don’t live in the same area but who have something in common. We could talk about the “podcast community” – people who make podcasts or produce podcasts are all part of that community. So, “community” can be something referring to a group of people with common interests as well as to a group of people who live next to each other or in the same place.
Finally, we have the term “unincorporated community.” This is a legal term. “Unincorporated” (unincorporated) is the opposite of “incorporated.” Well, what does “incorporated” mean? “Incorporated” means it’s legally recognized by the government as being, in this case, a community that shares the same laws and other administrative functions.
Los Angeles is an “incorporated” city. The government, the state of California, recognizes Los Angeles as an official city. However, California is a big place – it’s a big state – and not every area in California is part of a city or a town. Those parts that are not officially part of a larger city or town are called “unincorporated.” They’re not legally part of a city or town. Those areas are governed by the laws of the county in which they reside or in which they are found.
A “county” (county) is a division of the state that is larger, typically, than a city or a town. So within Los Angeles county, there are dozens of different cities. The largest city is Los Angeles. The city of Los Angeles is in the county of Los Angeles. So, states typically have divisions that are called “counties,” and within those counties there are smaller divisions called “cities” and “towns.”
Every area in a state is part of one county or another, but not every area in a county is part of a city or town. Those that are not are “unincorporated communities.” Strangely, here in Los Angeles County there are many unincorporated areas – areas that are right next to cities and towns, but for a variety of reasons are not part of those cities and towns. I mention “counties” – I should also point out that there is one state in which the counties are called something else, and that would be the state of Louisiana, where the counties are called “parishes.” That’s due to the French influence in the state of Louisiana, which was once part of French territory, as was indeed the middle part of the United States. But only in Louisiana do you still see that strong French influence, culturally and even legally.
Our next question comes from Paolo (Paolo) in Italy. Paolo wants to know the meaning of two expressions. First, “they mean well.” What does it mean when someone says, “Oh, well, they mean well.” “They mean (mean) well” means that these people have good intentions. They’re trying to do the right thing. They may not be doing the right thing. They may be making mistakes, but they want to do what is right. They have good intentions. They’re not trying to be evil. They’re trying to do something good.
That’s the meaning of “they mean well.” You may say about your neighbors, who are always telling you how to paint your house, “They mean well.” You don’t like them doing it. It might even make you angry. But they’re not trying to be evil or mean. They’re trying to be nice to you, even if they’re being a little annoying, even if they are bothering you.
The second question Paolo has refers to the phrase “to bend (bend) the rules.” “To bend the rules” means to do something that is not normally allowed by a set of rules or regulations. It often refers to someone who breaks the rules – who decides to not do what he or she is supposed to do, but is allowed because perhaps there is some good reason for doing what the person is doing.
If you are taking a test that is supposed to be completed within 30 minutes and the teacher says, “I’m going to give you an extra five minutes. I’m going to bend the rules,” this would be a case of “bending the rules.” The teacher decides not to follow the rules in this case, just this once, for a good reason.
Finally, Gustavo (Gustavo) in Brazil wants to know the meaning of the term “pit crew.” “Crew” (crew) refers to a group of people who work together doing similar kind of work. The word “pit” (pit) here refers to an area on the side of a racetrack – where cars go round and round in a race trying to drive as fast as they can.
As the cars are going around and around this area we call a “racetrack,” which is essentially a road that’s a circle, that goes in a circle, the cars sometimes have to stop and get gas or be repaired. That area where the cars stop alongside the racetrack is called the “pit.” The “pit crew” refers to the group of people who work on the car as it stops temporarily in order to get service for some reason. I don’t know if we ever use that expression in anything other than referring to the world of car racing.
If you have a question or comment, it doesn’t have to be about car racing. You can ask about anything, really. Just email us at eeslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen again next time right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
scandal – an action or event that is morally or legally wrong that makes the general public very angry
* The president of the company caused a scandal when it was revealed that he had been stealing money for years.
to accuse – to say that someone committed a crime, broke a rule, or did something wrong
* James accused Sheila of stealing the shirt from the store, but Sarah showed him the sales receipt, proving that she had bought it.
to throw a game – to lose a game on purpose; to allow the other player or team to win
* To keep her friend happy, Ambika sometimes throws their game of chess.
gambler – a person who plays games of chance to try to win money
* The gamblers sat down at the poker table, each hoping to win the $1 million prize.
to suspend – to stop someone from doing a job or action for a short period of time, usually as punishment for wrongdoing or until an investigation can be completed to find out if he or she had done something wrong
* After starting a fight in the hallway, the student was suspended from school for three days.
to ban – to officially prohibit someone from doing something; to not allow someone to do something
* Smoking is banned in all restaurants, bars, and stores in this state.
salary – an amount of money one is paid each year for doing one’s job
* Annette negotiated a salary that would cover her yearly expenses and also give her some extra to put away in a savings account.
to cheat – to act dishonestly or unfairly to win a game or gain an advantage
* Damian cheated on his exam by copying the answers from the student sitting next to him.
animated – a method of arranging and putting together a series of images or drawings to make it appear as though there is motion and movement
* I grew up watching animated movies produced by Walt Disney Studios featuring Snow White, Cinderella, and Sleeping Beauty.
prime time – the time period each day when television audiences are expected to be the largest, usually between 8 p.m. and 11 p.m., Monday through Friday
* A show that airs during prime time must be suitable for all ages and not have too much sex or violence.
premise – the basic idea that other ideas are based on or are created from
* The premise of most superhero movies is the triumph of good over evil.
prehistoric – the time period before written records
* In prehistoric times, humans lived out in the open or in caves and hunted for their food.
census-designated place – an area with people identified by the U.S. Census Bureau for statistical (related to information in the form of numbers) purposes
* All of the census-designated places in this state are far from the major cities.
community – a group of people who live in the same area, such as a city, town, or neighborhood; a group of people who have the same interests, religion, race, or other common characteristics
* Each year, we have a community party to meet new neighbors.
unincorporated community – an area that is not governed by its own local government but rather as part of a larger division, such as a borough or county
* Sales taxes are paid when you make purchases in town, but not when you do so in unincorporated communities nearby.
to mean well – to have the intention and making an effort to be nice, polite, or helpful, but failing
* Georgio meant well when he offered to play the piano at our wedding, but he doesn’t play very well.
to bend the rules – to do something or to allow someone to do something which is not usually allowed
* Our teacher bends the rules sometimes, allowing us to turn in our assignments late if we have a good excuse.
pit crew – the group of mechanics who fix a race car in between laps (each circle traveled) during a race
* The pit crew checked the tires on the racecar as the driver completed each lap.
What Insiders Know
Bobby Socks and Bobby Soxers
A “bobby sock” is a small, usually white sock that was very popular among young girls in the 1940s and 1950s. They are made of “cotton” (a natural plant fiber used to make many items of clothing) with a “thick” (not thin) upper part that is folded down to create a “cuff” (a folded part of clothing) at or above the “ankle” (the part of the body between the foot and the leg).
Most bobby socks are “plain” (without decoration), but some have “lace” (an open, decorative fabric made by looping or twisting the thread) and others are made from fabrics with different colors or “patterns” (repeating designs). Bobby socks are “designed to be seen” (they are supposed to be seen, not hidden underneath pants). In the past, girls often wore them with “loafers” (casual shoes with flat soles (shoe bottoms)) and shorter skirts.
In the 1940s and 1950s, teenage girls wore “poodle skirts” (wide, flowing skirts) with bobby socks. At school dances, the students had to “remove” (take off) their shoes to “avoid” (not do something) “damaging” (causing harm to) the wooden floors, so these dances where they danced in socks came to be known as “sock hops.” Today, bobby socks are not as common, but schools that require “uniforms” (the same clothing for all students) sometimes require female students to wear bobby socks.
Bobby socks became so “synonymous with” (closely associated with; thought of at the same time as) teenage girls that the term “bobby soxer” began to refer to young, “immature” (not yet fully developed, especially not emotionally or intellectually developed) teenage girls who were “major fans” (people who really like someone or something) of “pop music” (popular music).