



IT TOOK 125 years for *America’s Declaration 公告；宣告；宣言 of Independence* to reach a wide Chinese audience, and when it did, some *lofty 崇高的；高尚的 phrases* got lost.

主 The earliest known(a.)知名的；已知的 Chinese translation 翻译;译本 of the declaration, published in 1901 by young nationalists burning(v.) 有强烈的情感；渴望 to overthrow the Qing empire, 系 is an impatient, combative text.

The document’s name, noted(v.) the scholar who rediscovered it, Frank Li of the Chinese *Academy of Social Sciences*, became the “American War Proclamation 宣言；公告；声明 of Independence”.

The rights it deemed(=to have a particular opinion about sth 认为；视为；相信) inalienable(=that cannot be taken away from you 不可剥夺（或分割）的) -- “life, liberty and the pursuit of happiness” -- turned into something bleaker(a.)(=exposed, empty, or with no pleasant features 无遮掩的；荒凉的；索然无味的;/ not encouraging or giving any reason to have hope 不乐观的；无望的；暗淡的): “life, liberty and all interests”.


.标题
====
.lofty
(a.) very high and impressive 巍峨的；高耸的; / showing a belief that you are worth more than other people 傲慢的；高傲的; /deserving praise because of its high moral quality 崇高的；高尚的

.burn
(v.) (with sth) :to feel a very strong emotion or desire 有强烈的情感；渴望; / to make sb very angry 激怒；使大怒

.proclamation
[ CU] an official statement about sth important that is made to the public; the act of making an official statement 宣言；公告；声明 +
->



- bleak => 词源同bleach, 漂白，指苍白的，暗淡的。 +
-> bleak(a.)(=(of a place 地方) exposed, empty, or with no pleasant features 无遮掩的；荒凉的；索然无味的) concrete housing 索然乏味的混凝土住宅群 +
-> a bleak(=(of a situation 状况) not encouraging or giving any reason to have hope 不乐观的；无望的；暗淡的) outlook/prospect 暗淡的前景╱前途 +
-> a bleak(a.)(=(of the weather 天气) cold and unpleasant 阴冷的) winter's day 一个阴冷的冬日

《美国独立宣言》花了125年的时间才接触到广大的中国观众，当它到达时，一些崇高的短语就丢失了。该宣言最早的中文译本, 由渴望推翻清帝国的年轻民族主义者, 于1901年出版，是一篇不耐烦、好斗的文本。 重新发现该文件的学者，中国社会科学院的弗兰克·李（Frank Li）指出，该文件的名称成为“美国独立战争宣言”。它认为不可剥夺的权利——“生命、自由和追求幸福”——变成了更黯淡的东西：“生命、自由和一切利益”。 (happiness 被改成了 all interests)
====
