= 0762
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 762: Eating a Family Dinner.
This is English as a Second Language Podcast episode 762. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Welcome to our podcast.
Go to our website at eslpod.com to download a Learning Guide for this episode – and improve your English faster than a speeding bullet!
This episode is a dialogue about having dinner with a large number of people. Let’s get started.
[start of dialogue]
My roommate, Jim, invited me over to his house for a family meal. I’m an only child, so I’m not used to a big family dinner. I felt like a fish out of water.
…
Jim’s mother: Sit down, everybody. Dinner’s ready.
Phil: Thank you for having me over, Mrs. Moreno.
Jim’s mother: Don’t mention it. Just sit down and eat. Jim, pass the potatoes, and Dana, don’t hog the peas. Hand them both to Phil.
Phil: Thank you, Mrs. Moreno, but I’ve already taken a helping of each dish.
Jim’s mother: Then you need to have seconds. You’re too skinny. Eat up!
Phil: This food is really good, but I don’t think I have the appetite for more. My plate is already overloaded.
Jim’s mother: All right, no more potatoes or peas, but you need more ham. Laura, serve Phil some more ham, and Jason, round up some more rolls.
Phil: No, no, please. I really couldn’t eat more than what’s already on my plate.
Jim’s mother: Don’t be ridiculous. I know you’re saving room for dessert. There’s an apple pie, a strawberry shortcake, a cheesecake, and some ice cream.
…
I now know why Jim only comes home for meals every once in a while. Eating like this more than once a week would give anybody a coronary!
[end of dialogue]
Our story begins with Phil saying that his roommate, the person that he lives with, Jim, invited him over – invited him to his house for a family meal, a meal – a dinner with the other members of, in this case, Jim’s family. Phil says that he was, or is, an only child, meaning that his parents only had one child, him, so he is not used to – he’s not familiar with a big family dinner. He said, “I felt like a fish out of water.” The expression “a fish out of water” is used to describe someone who is very uncomfortable or in a situation that they are not used to being in, they are in a very different kind of environment than the one they are used to. I grew up in a big family, so a big family meal would not make me uncomfortable. But if I go to a house that has a very small family I might feel like a fish out of water. Fish, of course, normally are in water, and if they go out of water, well, sometimes they die. In fact, I think pretty often the fish will die out of water!
Well, Phil doesn’t die, but he does have an interesting experience. He goes to Jim’s house, and Jim’s mother says, “Sit down, everybody. Dinner’s ready.” We are ready to eat. Phil says, “Thank you for having me over, Mrs. Moreno.” “To have (someone) over” means to have someone come to your house for a short time to visit and usually to eat. Phil says, “Thank you for having me over, Mrs. Moreno.” And Mrs. Moreno, who is, of course, Jim’s mother, says, “Don’t mention it.” We use this phrase “don’t mention it” to mean sort of you’re welcome. We’re saying that you don’t have to thank me, it was nothing, it’s no big deal – don’t mention it.
She says, “Just sit down and eat. Jim, pass the potatoes, and Dana, don’t hog the peas.” “To pass (something),” as a verb, in this case means to take the dish that has the food and give it to the person usually next to you so he or she can get food for themselves. Although in some families, one person, often the mother, will put the food on the plate for everyone, it’s more common that you have all of the plates of food – all of the dishes on a large table and people pick them up and they give them to the person next to them – they pass them to the person next to them.
Jim’s mother is telling him to pass the potatoes, and Dana, who we guess is her daughter, “Don’t hog (hog) the peas.” “To hog” as a verb means to use all of something without having anyone else use it. Or, to take up all the time with something and not let anyone else have time with it. Your parents might tell you not to hog the TV. Or as parents, you may tell your children, “You’re hogging the TV. I want to watch something now.” You’re spending too much time with that and you’re not letting me do it. Dana is hogging the peas, meaning she’s not passing them to other people. I think that’s what Jim’s mother means. She also says, “Hand them both to Phil.” “To hand (something) to (someone)” means to give them that thing. In this case, to give the potatoes and the peas to Phil, who is, of course, the guest that they have invited over.
Phil says, “Thank you, Mrs. Moreno, but I’ve already taken a helping of each dish.” A “helping,” as a noun, is a serving; it’s the amount of food that you take and put on your plate to eat. That’s a helping (helping). You could have a large helping, you could have a small helping, depending on how much food you want to eat. Phil has already taken a helping of the potatoes and the peas, of each dish. A “dish” is, in this case, a type of food that has been prepared. You could have potatoes and vegetables and meat, each of those would be a dish. The word “dish,” as a noun, can also mean the plate that you are using to eat off of, or more commonly the container that the food is kept in. So you put all of the potatoes into a large bowl, we could say into a large dish. “Dish” has a couple of somewhat confusing meanings here.
Jim’s mother says, “Then you need to have seconds.” “Seconds” (seconds) is a second helping, or additional food. You’ve already had some potatoes and your mother says, “You need to have seconds,” you need to have even more potatoes, a second helping of potatoes. Jim’s mother thinks Phil needs to have seconds because he’s too skinny, he’s too thin. Kind of like me! Jim’s mother says, “Eat up!” This expression – informal – “eat up” means go ahead and start eating, eat everything that we are giving you. It’s a phrase that is used to encourage people to eat more or to start eating.
Phil says, “This food is really good, but I don’t think I have the appetite for more.” “Appetite” (appetite) is your desire to eat food, or how much food you want to eat right now. If you say, “I have a big appetite,” that means you are very hungry, you want to eat a lot of food. If you don’t have much of an appetite, that means you’re not very hungry at all. Phil says that he doesn’t think he has the appetite for more food; he can’t eat any more. He says, “My plate is already overloaded.” “To be overloaded” means to have too much of something, usually more than what the container can hold, or the plate can hold. To be overloaded with food means to have too much food, more than you can eat.
Jim’s mother says, “All right, no more potatoes or peas, but you need more ham.” “Ham,” of course, is a type of meat from a pig. “Laura, serve Phil some more ham.” “To serve (someone)” in this case means to put food on their plate. “I will serve you,” I will put the food that you need on your plate. We talk about waiters and waitresses in restaurants as servers; they are the people who are serving you – who are giving you the food, or at least bring it from the kitchen to your table. Jim’s mother tells Laura to serve Phil some more ham, and Jason is told to round up more rolls. “To round up,” as a phrasal verb, means to find something and bring it back. Go out to the kitchen or go to the store and round up some more milk or round up some more bread. You go and get more of that and you bring it back. Jason is supposed to round up some more rolls. “Rolls” are small pieces of bread that you eat with your meal.
Phil says, “No, no, please. I really couldn’t eat more than what’s already on my plate.” Phil says he can’t eat any more. Jim’s mother says, “Don’t be ridiculous.” She’s saying don’t be silly, that’s not right. “I know you’re saving room for dessert.” “To save room for,” when we’re talking about eating, means not to eat too much because you want to also be able to eat something else that comes later, in this case dessert – the sweet. Jim’s mother says that Phil is saving room for dessert. She says, “There’s an apple pie, a strawberry shortcake, which is strawberries on top of a small, little cake; a cheesecake, cake made out of cheese, of course; and some ice cream.
After the meal, Phil says, “I know now why Jim only comes home for meals every once in a while.” “Every once in a while” means occasionally, not very often, not frequently. “Eating like this more than once a week would give anybody a coronary!” “Coronary” (coronary) here means a heart attack. It’s an informal term referring to when your heart stops beating. If you eat a lot of unhealthy food that may give you high cholesterol, which could eventually lead to you having a coronary or a heart attack, and that’s what Phil is suggesting here. Notice that Phil doesn’t thank Jim’s mother for all the work that she has done making the meal. Instead, he’s worried about a heart attack. Well, too bad Phil! Next time make your own meal!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
My roommate, Jim, invited me over to his house for a family meal. I’m an only child, so I’m not used to a big family dinner. I felt like a fish out of water.
…
Jim’s mother: Sit down, everybody. Dinner’s ready.
Phil: Thanks for having me over, Mrs. Moreno.
Jim’s mother: Don’t mention it. Just sit down and eat. Jim, pass the potatoes, and Dana, don’t hog the peas. Hand them both to Phil.
Phil: Thank you, Mrs. Moreno, but I’ve already taken a helping of each dish.
Jim’s mother: Then you need to have seconds. You’re too skinny. Eat up!
Phil: The food is really good, but I don’t think I have the appetite for more. My plate is already overloaded.
Jim’s mother: All right, no more potatoes or peas, but you need more ham. Laura, serve Phil some more ham, and Jason, round up some more rolls.
Phil: No, no, please. I really couldn’t eat more than what’s already on my plate.
Jim’s mother: Don’t be ridiculous. I know you’re saving room for dessert. There’s an apple pie, a strawberry shortcake, a cheesecake, and some ice cream.
…
I now know why Jim only comes home for meals every once in a while. Eating like this more than once a week would give anybody a coronary!
[end of dialogue]
Our scriptwriter serves us a wonderful dialogue each and every ESL Podcast. Thank you Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
fish out of water – a phrase used to describe someone who is very uncomfortable because he or she is in an unfamiliar situation or environment
* For the first few weeks in her new job, Bethany felt like a fish out of water, but now she’s more comfortable with the office environment.
to have (someone) over – to invite someone into one’s home for a short period of time, especially for a meal
* Alicia had us over for dinner and drinks last week.
don’t mention it – a phrase used to respond to another person’s gratitude or apology, used to show that it isn’t necessary and that one’s actions aren’t important
* - I’m so sorry I broke your vase!
* - Don’t mention it. I never liked that one very much anyway.
to pass – to pick up a serving dish on the table and give it to another person so that he or she can put more food on his or her plate
* Could you please pass the pepper? I can’t reach it from here.
to hog – to have or use all of something, without letting anyone else have or use it
* Maxine’s brother used to complain about how she hogged the bathroom each morning.
to hand – to give something to someone
* Hand me the keys. It’s my turn to drive.
helping – a serving; one portion; the amount of food taken from a serving dish and put on one’s plate
* Broccoli is Glen’s favorite vegetable, so he always takes an extra-large helping.
dish – a type of food that has been prepared and is being served
* Of all the dishes served for Thanksgiving, cranberry sauce is Uncle Ron’s favorite.
seconds – a second helping of food; additional food put on one’s plate after one has finished the food that was put on the plate originally
* Caroline loves to cook, especially when people ask for seconds, because then she knows they like the food she has made.
to eat up – to eat all of something or to eat a lot of something, often used to encourage someone to eat more
* We don’t have any room for leftovers in the refrigerator, so eat up!
appetite – one’s desire to eat; how much food one wants to eat at the moment
* When teenage boys are growing, they have a tremendous appetite.
overloaded – with too much of something; with more of something than an object was designed to hold or contain
* Sammy’s backpack was overloaded with books and he could hardly carry it.
to serve – to put food on a person’s plate; to provide some service to another person
* They served hamburgers and hot dogs at the barbeque.
to round up – to find something and bring it
* Do you think you can round up some more folders for these presentation materials?
to save room for – to not eat as much as one wants, so that one will be able to eat another type of food that will be served very soon; to avoid becoming so full that one won’t be able to eat something else
* I’m glad you like the pasta, but save room for the peach pie!
every once in a while – occasionally; not frequently; not very often
* Lorenzo loves to go to clubs with his friends, but every once in a while, he enjoys a quiet evening at home.
coronary – a heart attack; an informal term referring to the medical condition when one’s heart stops beating, usually due to a very unhealthy diet and a lack of exercise
* If Earl keeps eating red meat every day, he’s going to have a coronary!
Comprehension Questions
1. Why did Phil feel like a fish out of water?
a) Because he doesn’t like to eat seafood.
b) Because he wasn’t accustomed to large family dinners.
c) Because he is a vegetarian.
2. Why didn’t Phil want to eat more?
a) Because he was already full.
b) Because the food was very unhealthy.
c) Because he was too nervous.
Answers at bottom.
What Else Does It Mean?
seconds
The word “seconds,” in this podcast, means a second helping of food, or additional food put on one’s plate after one has finished the food that was put on the plate originally: “That soup was delicious! May I have seconds?” The phrase “to have second thoughts” means to have doubts about what one has done or about what one is planning to do: “Everyone says it’s normal to have second thoughts before your wedding.” The phrase “on second thought” shows that one has changed one’s mind: “I’d like a loaf of bread, please. On second thought, I’ll take two.” Finally, the phrase “to not give (something) a second thought” means to not worry about something: “Chase apologized for arriving so late, but Zaheer just laughed and said, ‘Don’t give it a second thought.’”
to round up
In this podcast, the phrase “to round up” means to find something and bring it: “We need to round up some more speakers for the conference.” Or, “Where can we round up some more volunteers for the work party?” When talking about numbers, the phrase “to round up/down” means to increase/decrease a number to a certain number of decimal points: “Please round down to the nearest 10. For example, 738 should become 730.” The phrase “to round (something) out” means to make something more complete, comprehensive, and/or balanced: “Evelyn is rounding out her college classes with a few courses in literature and fine arts.” Or, “The pianist rounded out his repertoire with a few sonatas.”
Culture Note
Customs at Family Meals
Traditionally, American families ate their meals together. However, in recent years, “hectic” (busy) schedules have led to fewer opportunities to share meals, and many families report eating together as a family only on “special occasions” (holidays; times when something is being celebrated). These family meals “tend to be” (are usually) more formal than “ordinary” (regular, common) and the “diners” (the people who are eating) are expected to follow certain customs and traditions.
The food is placed in “serving bowls” at the center of the table. Diners are expected to serve themselves from the closest serving bowl and then pass it to the next person. Nobody should begin eating until everyone has been served.
In a Christian family, the “head of the family” (leader, traditionally the father) usually “says grace” (prays aloud) while everyone “bows their head” (looks downward) with eyes closed. The prayer usually thanks God for the food and for the opportunity to spend time together. When the prayer ends, everyone says “Amen.”
If there is a large “roast” (a large piece of meat that has been cooked slowly for a long period of time), turkey, or ham, the head of the family uses a special “carving knife” to “carve” (cut into slices) the meat and put a piece on each person’s plate.
The diners are expected to “engage” (participate) in “small talk” (friendly, unimportant conversation). Cell phones, television sets, and other “distractions” (things that take away one’s attention) should be turned off so that the diners can interact with each other, though that may not be a common expectation with some families today.
Comprehension Answers
1 - b
2 - a