= 0771
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 771: Commuting by Train.
This is English as a Second Language Podcast episode 771. I’m your host, Dr. Jeff McQuillan, coming to you from beautiful Los Angeles, California.
Our website – you know what it is – eslpod.com. Become a member, if you’re not already, and support this podcast. You can download a Learning Guide when you do. Are you on Facebook? You can like us at facebook.com/eslpod. You can follow us on Twitter @eslpod.
This episode is a dialogue between Lisa and Omar talking about traveling on a train. Let’s get started.
[start of dialogue]
Lisa: Can you tell me if this is the right platform for the train to Arlington?
Omar: Yes, it is. Is this your first time taking the train?
Lisa: Is it that obvious?
Omar: No, you just look a little lost.
Lisa: I’m starting a new job and I have to commute to work for the first time.
Omar: Oh, I see. Did you buy a ticket at the ticket machine?
Lisa: Yes, I did, when I entered the station. I hope I bought the right one.
Omar: Let me see. Yes, that’s the right one. The good news is that I haven’t heard any announcements about the train being delayed, like it has been a couple of times this week, so it should be on time.
Lisa: I’m relieved to hear that. I can’t afford to be late to work on my first day. Will I need to show this ticket to get on the train?
Omar: Not when you get on. After the train is under way, the conductor will walk down the aisle to collect it.
Lisa: Oh, I see, thanks. That sounds simple.
Omar: It is simple if you can actually find a seat. It can be pretty crowded on these commuter trains. Sometimes it’s standing room only.
Lisa: Let’s hope for the best.
Omar: Stick with me. I’ll elbow a few people out of the way to get you a seat.
Lisa: [laughs] Thanks, I think.
[end of dialogue]
Lisa begins by asking Omar, “Can you tell me if this is the right platform for the train to Arlington?” A “platform” (platform) is a large, flat area where people stand waiting for a train or a subway train. A train, you probably know, has several small sections called “cars,” but they’re not cars like you drive down the street. They are cars that are connected to each other and all move in one direction down something called a “track” (track).
Well, Lisa wants to know if this is the right platform, the right place to get the train to Arlington. Omar says, “Yes, it is. Is this your first time taking the train?” Lisa says, “Is it that obvious?” Something that is “obvious” is something that is easily seen; you have no difficulty understanding it. What she’s saying here is do I really seem like that much of a beginner, obviously it is the first time she has taken the train. Omar says, “No, you just look a little lost,” a little confused, like you don’t know where to go.
Lisa says, “I’m starting a new job and I have to commute to work for the first time.” “To commute” (commute) means to travel usually from your home to where you work and back again. Some people commute by car, some people commute by subway; some people commute, if it’s a very long distance, by train. Lisa is commuting by train.
Omar says, “Oh, I see. Did you buy a ticket at the ticket machine?” The “ticket machine” is the machine that gives you usually a little piece of paper called a “ticket” that allows you to be on the train. Lisa says, “Yes, I did, when I entered the station.” The “station” is the area where the trains all come and stop, and that’s where you get on and off the train, at the train station. You can also have a bus station. Lisa says, “I hope I bought the right one,” meaning I hope I purchased the correct ticket.
Omar says, “Let me see. Yes, that’s the right one. The good news is that I haven’t heard any announcements about the train being delayed. An “announcement” is information, in this case that would be said over the large speakers in the train station on the platform. If a train is going to be late they sometimes tell everyone – they announce it, and the noun is an “announcement.” “To be delayed” means that it isn’t going to arrive or leave when it’s supposed to; it’s late. Sometimes trains are delayed; they don’t arrive or leave when they are supposed to. Omar says that the train has been delayed a couple of times this week, but because there were no announcements it should be on time. When we say something is “on time” we mean it should leave at the correct or scheduled time, or arrive at the correct or scheduled time.
Lisa says, “I’m relieved to hear that (I’m happy to hear that). I can’t afford to be late to work on my first day.” “I can’t afford” means that it’s not possible for me, otherwise it will be very bad for me. “Will I need to show this ticket to get on the train?” Omar says, “Not when you get on. After the train is under way, the conductor will walk down the aisle to collect it.” “After the train is under way” means after the train has already started to move – has left the station. Then, the “conductor,” the person who works for the train company whose job it is to collect the tickets, he will walk – or she – will walk down the aisle. The “aisle” is the narrow area between the seats for walking, where you can move up and down the train. The conductor will then “collect” the tickets, he will take them from you. Sometimes he will put mark on them and then give them back to you, depending on the train.
Lisa says, “Oh, I see, thanks. That sounds simple.” Omar says, “It is simple if you can actually find a seat. It can be pretty (or very) crowded on these commuter trains,” these trains that take people back and forth from work. “To be crowded” means you don’t have a lot of room to move. Omar says, “Sometimes it’s standing room only.” “Standing room only” means that all of the seats are filled. There’s no place to sit down, you have to stand. This, of course, is very common in a subway system in a large city, but sometimes it can happen on trains as well.
Lisa says, “Let’s hope for the best,” meaning let’s be optimistic; let’s hope that we get a seat, in this case. Omar says, “Stick with me.” “To stick with (someone)” means to stay very close to that person or to listen to everything they say, especially when you are traveling somewhere or going somewhere. Omar says, jokingly we think, “I’ll elbow a few people out of the way to get you a seat.” “To elbow” (elbow), as a verb, means to push someone out of the way with your elbow. Your “elbow” is the point in your arm that connects the forearm, that has your hand on the end of it, and I guess we’d call the upper part of your arm; that’s the “elbow. But as a verb “to elbow” would mean to use that part of your body to push people away. Omar is saying he’s going to elbow a few people out of the way so that Lisa can have a seat. We suspect here that Omar maybe is interested in Lisa, trying to be friendly with her. Lisa laughs and says, “Thanks, I think.” When someone says “I think” at the end, that means they’re not really sure; they’re not sure if they should thank this person for what they just said.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Lisa: Can you tell me if this is the right platform for the train to Arlington?
Omar: Yes, it is. Is this your first time taking the train?
Lisa: Is it that obvious?
Omar: No, you just look a little lost.
Lisa: I’m starting a new job and I have to commute to work for the first time.
Omar: Oh, I see. Did you buy a ticket at the ticket machine?
Lisa: Yes, I did, when I entered the station. I hope I bought the right one.
Omar: Let me see. Yes, that’s the right one. The good news is that I haven’t heard any announcements about the train being delayed, like it has been a couple of times this week, so it should be on time.
Lisa: I’m relieved to hear that. I can’t afford to be late to work on my first day. Will I need to show this ticket to get on the train?
Omar: Not when you get on. After the train is under way, the conductor will walk down the aisle to collect it.
Lisa: Oh, I see, thanks. That sounds simple.
Omar: It is simple if you can actually find a seat. It can be pretty crowded on these commuter trains. Sometimes it’s standing room only.
Lisa: Let’s hope for the best.
Omar: Stick with me. I’ll elbow a few people out of the way to get you a seat.
Lisa: [laughs] Thanks, I think.
[end of dialogue]
I think it’s obvious we have the best scriptwriter on the Internet; that’s because we have the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
platform – a large, flat area where people stand while waiting for a train or subway
* When standing on the platform, always stand behind the yellow line for safety, because you don’t want to get hit by the cars as they come into the station.
train – a type of vehicle where many cars are attached together and pulled by one or more engines
* This is the red line train to the Portland airport.
obvious – apparent; easily seen and understood; not difficult to identify or understand
* When Jenna accidentally walked into the men’s restroom, it was obvious she wasn’t familiar with the building.
to commute – to use some type of transportation between one’s home and workplace
* Eddie commutes more than an hour each day, so he’s thinking of moving closer to his office.
ticket machine – a machine that accepts money and produces tickets, especially tickets used for transportation
* The ticket machine accepts only coins and one-dollar bills.
station – a large, covered area where trains, buses, or metros stop to drop off and pick up passengers
* I’ll meet you at the bus station in front of the library.
announcement – information that is said loudly to a large group of people; notification
* When children are separated from their parents inside the store, employees can use the loudspeaker to make an announcement and help the family members find each other.
delayed – arriving later than planned, later than usual, or later than expected
* Their first flight was delayed, so they missed their connecting flight and had to spend the night in Houston.
on time – happening at the correct time; happening when something was planned to occur; happening as planned or scheduled
* What percentage of the students submit their assignments on time?
under way – happening now; in motion; in the process of doing something
* Once tax season is under way, accountants are very busy.
conductor – a person whose job is to take tickets from passengers on a train, bus, or subway, and answer any questions or deal with problems
* The conductor can make people pay a fine for eating on the metro.
aisle – the narrow area for walking between rows of seats
* The flight attendant pushed the beverage cart down the aisle.
to collect – to gather; to take objects from many different locations and bring them to one or more central locations
* Janice likes to collect seashells while walking on the beach.
crowded – without very much room to move; with many people in a small space
* Grocery stores are very crowded around 5:30 p.m., when most people get off work.
standing room only – with all the seats filled, so that additional people have to stand
* The new play is so popular that the theater has standing room only.
to stick with (someone) – to be next to someone and follow that person or do as he or she recommends, usually for protection, guidance, and care
* As long as everyone sticks with the leader, we’ll be fine.
to elbow – to push someone away with one’s elbow (where one’s arm bends between the wrist and shoulder), usually to make more space
* During the big sale, shoppers had to elbow each other out of the way to find the things they wanted to buy.
Comprehension Questions
1. Why does Omar think the train will come on time?
a) Because it is always very punctual.
b) Because he hasn’t heard about any cancellations.
c) Because he can see it coming down the tracks.
2. What does Omar offer to do for Lisa?
a) He offers to make other people move so that she can sit down.
b) He offers to ride the train all the way to her office so she doesn’t get lost.
c) He offers to pay for her train ticket.
Answers at bottom.
What Else Does It Mean?
platform
The word “platform,” in this podcast, means a large, flat area where people stand while waiting for a train or subway: “Is this platform for the northbound trains or the southbound trains?” A “platform” is also a type of computer software or system: “Our new platform works with Microsoft Windows.” In politics, a “platform” refers to one’s main ideas and promises: “He campaigned on a platform of reducing the unemployment rate and improving public schools.” Finally, when talking about shoes, “platforms” or “platform shoes” are tall shoes that have a thick layer of wood under the sole (bottom part of the shoe): “Those platforms add at least six inches to her height, but they make it really hard for her to walk.”
under way
In this podcast, the phrase “under way” means happening, in motion, or in the process of doing something: “Once the conference is under way, we can’t make any more changes to the schedule.” The phrase “to give way” means to be replaced with something else: “Her sadness gave way to a deep depression.” The phrase “to make (one’s) way” means to make progress in a certain direction or toward a certain goal, especially when it is difficult or takes a lot of time: “He’s making his way through some difficult personal circumstances.” The phrase “to make (one’s) way home” can also mean to return home without receiving help from another person: “Everyone was surprised when the little boy made his way home after having been lost in the woods for two days.”
Culture Note
Commuter Rail Systems in the United States
There are many commuter “rail” (with trains or train-like vehicles that travel on metal tracks attached to the ground) systems in the United States. The “commuter rail systems” travel between major cities, or at least between large cities and their “suburbs” (areas where people live, surrounding a city). As you might expect, they are more common in large “metropolitan areas” (developed areas in and around a city) and the larger cities “tend to have” (usually or generally have) the greatest “ridership” (number of passengers).
The Long Island Rail Road was opened in 1836. Today, it has 124 stations and serves an average of 341,200 riders on a typical “weekday” (a day other than Saturday or Sunday), primarily in New York City. New York is also served by the Metro-North Railroad, which is the nation’s third-biggest commuter rail system, with average weekday ridership of 289,900. It opened in 1983, has 120 stations, and covers 384 miles.
The Metra in Chicago, Illinois is the second-biggest commuter rail system in the United States, with average weekday ridership of 311,500. The Metra has been in operation since 1984 and today has 240 stations and covers 495 miles. A second commuter rail system that serves Chicago, the NICTD South Shore Line, is the nation’s 12th-largest system with average weekday ridership of 13,000.
Philadelphia, Pennsylvania is also a major transportation “hub” (the most important part of a system; something that many things are connected to). The New Jersey Transit Rail connects New York and Philadelphia and, with average weekday ridership of 285,063, it is the fourth-largest commuter rail system in the United States. The SEPTA Regional Rail also serves Philadelphia and is the nation’s sixth-largest commuter rail system, with average weekday ridership of 114,500.
Comprehension Answers
1 - b
2 - a