= 0777
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 777: Supplies for Outdoor Recreation.
This is English as a Second Language Podcast episode 777 – or backwards, 777. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there and check out our ESL Podcast Blog, where we twice a week provide some additional English help. You can also look at our ESL Podcast Store, and get some of our premium courses in English.
This episode is a dialogue between Jim and Fumiko about spending time outside having fun. Let’s get started.
[start of dialogue]
Jim: I shouldn’t have let my brother pack my supplies for this trip. I was running late and he offered to do it.
Fumiko: What’s the problem?
Jim: He doesn’t know the first thing about hiking or camping. Look at this! My backpack is filled with bottles of water!
Fumiko: What’s wrong with that?
Jim: He should have just packed me a water filter, instead of all these heavy bottles to lug around. And he forgot some of the most important supplies, like bug spray and a flashlight.
Fumiko: You’re welcome to borrow any of our supplies. Here’s some bug spray. Do you need matches?
Jim: Yeah, I do. My brother packed matches, but not in a waterproof bag. One of the bottles of water leaked and got them all wet. At least my tent and cook stove were spared.
Fumiko: Maybe your brother is telling you something.
Jim: What?
Fumiko: Maybe he wants to be included in your camping trips. Then, he’ll learn what to do and what to bring.
Jim: You might have something there.
[end of dialogue]
Jim begins by saying, “I shouldn’t have (I should not have) let (or allowed) my brother pack my supplies for this trip.” “Supplies” are things that you need for some particular purpose. It’s a very general term; it can be used when talking about making something: we need certain materials – certain things. In this case, it’s about going on a trip, where you need to bring certain things. Jim says, “I was running late (meaning I was behind schedule) and he offered to do it.” So his brother – Jim’s brother – packed Jim’s supplies. He put them all in a bag or in some suitcase for Jim to take with him.
Fumiko says, “What’s the problem?” Jim says, “He (my brother) doesn’t know the first thing about hiking or camping.” When we say someone “doesn’t know the first thing about something” we mean they don’t know anything; they have no knowledge at all about this topic – this subject. In this case, it’s about hiking and camping. “Hiking” (hiking) is when you go out and walk in a forest or on a mountain or by a lake, some area outside of perhaps the city or in a park inside a city. “To hike” is the verb; “hiking” is the noun. “Camping” is when you go and you sleep away from your house outside – outdoors, not in a hotel. That’s where I’ll be! But you can be camping; that’s fine. I’m not a camper, I’m not really someone who likes to sleep outside, but some people do and so that’s why we have this strange thing called “camping.”
So Jim then says, “Look at this! My backpack is filled with bottles of water!” Your “backpack” is a large bag that you wear on your back, and you put things in there that you will need for your camping trip or your hiking. In the United States, it’s very common in colleges and universities for students to carry their books in backpacks. This is different than what happens in other countries. In other countries, only little children wear backpacks, but in the United States it’s very common for college students to wear backpacks with all of their books and everything. So, Jim has a backpack, not for books but to go camping.
Fumiko says, “What’s wrong with (filling your backpack with bottles of water)?” Jim says, “He should have just packed me a water filter, instead of all these heavy bottles to lug around.” A “water filter” is a small device that you put inside a water bottle that cleans the water so you can drink it, so you can use the water that is outside – out in the park, or wherever you are – and the water filter will clean it. That way, if you want clean water, you don’t have to bring all of the bottles of water with you; you don’t have to lug the bottles around. “To lug” (lug) is to carry something that is very heavy, very difficult to move. “Lug around” just means to move from one place to another
Jim said his brother also forgot some of the most important supplies, like bug spray and a flashlight. “Bug (bug) spray (spray)” is a liquid you put on your skin to prevent or stop little mosquitoes and bugs from biting you. A “flashlight” (flashlight – one word) is a small, portable light; usually it has batteries. Here in the U.S., a common kind of flashlight is a long tube, usually 6 to 12 inches, and there’s a light at the end of it, but it could be of a different shape, certainly. So, Jim’s brother didn’t put a flashlight into his backpack for this trip.
Fumiko says, “You’re welcome to borrow any of our supplies.” “You’re welcome” is usually what you say when someone says “thank you” to you. But in the expression “you’re welcome to (do something),” “you’re welcome to use my matches,” that means that I don’t mind, I would be happy to share my matches with you; you can use them if you want. “Matches” are usually small, little sticks of wood or paper that have a special chemical on them that when you move the match against another surface it creates a flame – it causes a fire. Of course, if you don’t have matches, then you just go eat in a restaurant, and you don’t have to worry about lighting a fire!
Well, Fumiko says that Jim is welcome to borrow any of their supplies, she says, “Here’s some bug spray,” then asks him if he needs matches. Jim says, “Yeah (or yes), I do.” He says his brother packed matches, but not in a waterproof bag. Something that is “waterproof” (one word) does not allow water inside of that container or that thing. So, if a bag is waterproof, you could put it in the water or you could have rain fall on it and what is inside of the bag would not get wet. It prevents the water for going inside. Jim says, “One of the bottles of water (that were in his backpack) leaked.” In other words, the water came out of the bottle by accident, and that got all of the matches wet. “At least my tent and cook stove were spared,” he says. Your “tent” is a small thing that you use to sleep in; it is usually made of a thin material and you use poles or sticks to put it up. It’s like a little house that you build, where you can put yourself into and your supplies into when you are outside – when you are camping. A “cook stove” is a small thing you use to cook on when you are outside; you can cook food on one of these little stoves. The stove usually is powered by or has gas to produce the fire for the heat. Jim says that his tent and cook stove were spared. “To be spared” (spared) means they were not hurt or harmed or affected by, in this case, the water. “Spare” has a number of meanings in English; take a look at our Learning Guide for some of those.
Fumiko says, “Maybe your brother is telling you something.” She means maybe his brother is trying to communicate some message to him by the way that he packed his supplies. Jim says, “What?” Fumiko says, “Maybe (your brother) wants to be included in your camping trips. Then, he’ll learn what to do and what to bring.” Jim says, “You might have something there.” The expression “you might have something there” is used to show that you believe what the other person said is correct, or at least is partially correct. Maybe you don’t agree with everything, but most of what they say, or part of what they say is correct, is something you agree with.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Jim: I shouldn’t have let my brother pack my supplies for this trip. I was running late and he offered to do it.
Fumiko: What’s the problem?
Jim: He doesn’t know the first thing about hiking or camping. Look at this! My backpack is filled with bottles of water!
Fumiko: What’s wrong with that?
Jim: He should have just packed me a water filter, instead of all these heavy bottles to lug around. And he forgot some of the most important supplies, like bug spray and a flashlight.
Fumiko: You’re welcome to borrow any of our supplies. Here’s some bug spray. Do you need matches?
Jim: Yeah, I do. My brother packed matches, but not in a waterproof bag. One of the bottles of water leaked and got them all wet. At least my tent and cook stove were spared.
Fumiko: Maybe your brother is telling you something.
Jim: What?
Fumiko: Maybe he wants to be included in your camping trips. Then, he’ll learn what to do and what to bring.
Jim: You might have something there.
[end of dialogue]
Our scriptwriter might not know the first thing about camping, but she does know a lot about writing good scripts. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
supplies – something that is needed for a particular purpose
* Each fall, Maria buys folders, notebooks, pens, pencils, and other school supplies for her children.
to not know the first thing – a phrase used to emphasize that someone is completely ignorant about or unaware of something, or that someone does not have any knowledge of something
* Why did Christian decide to fix the toilet himself? He doesn’t know the first thing about plumbing or home repair
hiking – an outdoor recreational activity of walking through natural areas, often to reach the top of a mountain or a lake
* The library has some books that describe local hiking trails with the best views.
camping – a recreational activity of spending at least two days outdoors far away from a city, usually sleeping in a tent and sleeping bag
* Kevin hates bugs and dirt, so he probably wouldn’t enjoy camping.
backpack – a large bag worn over one’s shoulders and on one’s back, used to carry things while walking
* Ruby likes to carry her things in a backpack, because it leaves her hands free to do other things while she’s walking.
water filter – a small device that sits inside or screws onto the top of a water bottle, used to clean water so that it can be drunken safely
* Are you sure this water filter will make the water safe to drink?
to lug – to carry or drag something that is very heavy and difficult to move
* Why are you lugging all those books home each night? Can’t you keep them in the office?
bug spray – a liquid put on one’s body to keep away insects
* This bug spray really keeps the mosquitoes away, but be careful not to get any in your eyes.
flashlight – a small light that can be carried in one’s hand, usually powered by batteries
* It’s a good idea to have flashlights and extra batteries in the house, just in case we lose power.
match – a small piece of paper or a wooden stick that has a special red tip that can be rubbed against another surface to create a flame for lighting a fire, stove, candle, or cigarette
* Masaki remembered to buy candles for her husband’s birthday cake, but she forgot to get matches.
waterproof – a substance or material that does not allow water to pass through and protects whatever is inside from getting wet
* Aden bought a pair of waterproof boots, but they didn’t work well, so his socks got wet when he walked through the rain.
tent – a small shelter made of fabric held up by special poles, used for protection from the weather while sleeping outdoors
* We went camping last weekend, but it rained so much that we had to spend most of Saturday inside the tent.
cook stove – a small stove that folds up and can be used to cook outdoors, usually powered by propane (a type of gas burned for energy)
* Rosa surprised everyone by cooking a gourmet meal of chicken, mushrooms, and rice on a tiny cook stove.
spared – not harmed or affected by something when everything or everyone else is harmed or affected
* No one in this small town was spared from the housing crisis.
might have something there – a phrase used to show that one believes someone might be at least partially correct
* A: Having a better education system is the key to reducing crime and poverty.
* B: Yes, you might have something there.
Comprehension Questions
1. Why is Jim upset that his brother packed bottles of water?
a) Because Jim prefers to drink juice.
b) Because the bottles are too heavy.
c) Because Jim’s brother didn’t include ice.
2. What happened to Jim’s tent and cook stove?
a) They got wet.
b) They got crushed.
c) Nothing. They’re fine.
Answers at bottom.
What Else Does It Mean?
bug
“Bug spray,” in this podcast, refers to a liquid put on one’s body to keep away insects: “This bug spray smells terrible, but at least we won’t get any bug bites.” A “bug” is any type of insect: “Tom is fascinated by bugs like spiders and ants, but he hates bees.” A “bug” can also refer to the bacteria or virus that causes a cold, flu, or other illness: “Everyone at the office has the same bug, so a lot of people are staying home this week.” When talking about software, a “bug” is an error in the computer program: “The software developers are trying to fix all the bugs by the end of the month.” Finally, as a verb, “to bug (someone)” means to annoy or irritate someone: “Mom, Sofia is bugging me. Make her stop!”
spared
In this podcast, the word “spared” means not harmed or affected by something when everything or everyone else is harmed or affected: “The tornado destroyed most of the town, but for some reason, four homes on Tenth Street were spared.” The word “spare” normally refers to something extra or additional that is saved until it is needed: “Do you know how to put a spare tire on your car in case you get a flat tire?” Or, “If you get to the house before I do, you can find a spare key underneath the mailbox.” The phrase “spare time” refers to free time, or a period of time when one does not have to be working or doing other things: “In his spare time, Huang enjoys reading and playing volleyball.”
Culture Note
Outdoor Recreation Activities
Americans enjoy many types of outdoor recreation activities in addition to the hiking and camping described in today’s episode. “Backpacking” refers to long hikes where one sleeps outdoors, but has to carry a tent, sleeping bag, and other items in a large backpack. “Trekking” refers to very long-distance backpacking trips, especially up mountains.
“Rock climbing” refers to using one’s hands, feet, “ropes” (long, thick, strings), and other special equipment to climb up mostly flat, “vertical” (straight up and down) surfaces on the side of a mountain. When people do this over icy surfaces in the winter, they use “ice picks” (sharp metal objects used to hold onto the icy surface) and the activity is called “ice climbing.”
In the winter, many people enjoy “skiing” (traveling over the snow by putting two long, flat pieces on one’s feet), either “downhill skiing” (very fast skiing from the top of the mountain downward) or “cross-country skiing” (slower skiing, sliding over more flat areas). Many younger people prefer “snowboarding” (like skiing, but with a single, wider board). “Less adventurous types” (people who do not want to take many risks) prefer “snowshoeing,” where they put special round, wooden, or metal frames under their boots so that they can walk on top of the snow.
A lot of people like water-based recreational activities, too. These can include fishing or boating. Some people enjoy “rowing” (moving sticks in the water to make a boat go forward), “canoes” (long, narrow boats for just a few people, designed like Native American boats), or “kayaks” (very small, narrow boats for just one person). Other people like the “thrill” (excitement) of “white water rafting” (riding in a large “inflatable” (air-filled) boat over fast-moving water in a river).
Comprehension Answers
1 - b
2 - c