= 0786
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 786: Going to a Bar.
This is English as a Second Language Podcast episode 786. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode that will help you improve your English even faster.
This episode is a dialogue about going to a “bar,” a place where you go and have an alcoholic drink. Let’s get started.
[start of dialogue]
I’d been complaining to a coworker, Amy, about having to move to the burbs for my job. She said that there were plenty of things to do outside of the city and invited me to a bar she likes.
…
Amy: Hey, there you are.
Mykhailo: Hey, so this is the famous McQ’s you’ve been talking about.
Amy: This is it. What would you like to drink? There are several beers on tap and pretty good well drinks.
Mykhailo: I think I’ll get a couple of shots.
Amy: On a Wednesday night? You guys do party hard in the city.
Mykhailo: I’ve had a really rough week and I welcome any excuse to let my hair down. That said, I won’t be getting stinking drunk on a school night. You were right. This place is nice. It even has a dance floor.
Amy: On the weekends, there’s a live band or a DJ, although there’s also a cover charge on Fridays and Saturdays.
Mykhailo: So you do know how to party in the burbs.
Amy: Didn’t I tell you?
Mykhailo: But for me to get a thorough impression of the burbs, I’ll have to come here to check it out this weekend. What are you doing Saturday night?
Amy: Actually, I plan on coming here.
Mykhailo: Want some company?
[end of dialogue]
Our story begins with Mykhailo saying, “I’ve been complaining to a coworker.” “To complain” means to talk about something negative, to say how unhappy you are about something that is happening. Mykhailo’s been complaining to a “coworker,” someone he works with named Amy, “about having to move to the burbs for my job.” “Burbs” (burbs) is an informal word for suburb. “Suburbs” are areas around the main city, outside of the downtown area, usually outside of a major city. In Los Angeles, the suburbs would be all of the cities around the City of Los Angeles, around the biggest city.
Mykhailo says Amy “said there were plenty of things to do outside of the city and invited me to a bar she likes.” A “bar,” which would be called a “pub” in England, or a “tavern,” is a place that serves mostly alcoholic beverages: beer, wine, whiskey, rum, and so forth. I like rum personally, if I have an alcoholic drink, which is very, very rarely now. But I really like the taste of rum – Bacardi Rum – especially the rum from Mexico for some reason. The Mexican Bacardi is very good, as good as I think the Puerto Rican rum. Now, if you’re from Puerto Rico you’ll probably email and complain that I said that, but there you go. Anyway, I’m not drinking; I’m recording a podcast so let’s continue.
Amy says, “Hey, there you are.” We would say that expression “there you are” for someone who you were looking for or perhaps you were waiting for and they finally came. Mykhailo says, “Hey, so this is the famous McQ’s you’ve been talking about.” The name of the bar is called McQ’s, no relation to me. Amy says, “This is it. What would you like to drink? They have several beers on tap and pretty good well drinks.” “On tap” means available usually from a faucet. If a beer is on tap, it’s in a big barrel – a big container, and it comes right out of that container into the glass – into the mug where you pour the beer and drink the beer out of. The opposite would be beer in a bottle, but beer on tap is beer that the bar has in a big container. A “well (well) drink” is any alcoholic drink made from some other kind of alcohol, like whiskey or rum. Usually it’s mixed with something else, either some sort of soda pop, or some juice, or some water, or something similar.
Mykhailo says, “I think I’ll get a couple of shots.” Well, there are a number of different things you can order at a bar. A well drink, or just a drink, would be what some people might call a “cocktail,” that would be, for example, rum and Coke, which we call a Cuba Libre, or a Tom Collins, or a whiskey seven – whiskey with 7-Up. Those are all well drinks. A “shot” is when you just have alcohol in a small, little container called a “shot glass,” and it’s a very small amount of alcohol. You could have a whiskey shot, or a shot of whiskey, which would be just one little container full of alcohol, usually served in a very small glass – in a shot glass.
So, Mykhailo says, “I think I’ll get a couple of shots.” Amy says, “On a Wednesday night? You guys do party hard in the city.” She’s surprised because getting a couple of shots is a lot of alcohol, and it’s in the middle of the week, so she’s surprised that Mykhailo wants to drink so much. That’s why she says, “You guys (you people who live in the city) party hard.” “To party” means to have a good time, to celebrate, to drink and dance. “To party hard” would be to enjoy yourself, usually by drinking a lot of alcohol, an extreme amount of alcohol, alcohol that would get you drunk quickly and for a long time.
Mykhailo says, “I’ve had a really rough (or difficult) week and I welcome any excuse to let my hair down.” “To welcome any excuse to let your hair down” would be to use any opportunity or reason to relax and have fun. Not quite sure about his use of the term “let my hair down.” That’s something a woman might say more likely than a man, but maybe Mykhailo has, uh, long hair; I don’t know. He says, “That said, I won’t be getting stinking drunk on a school night.” “That said” means nevertheless. Even though he is looking for an excuse to party – to let his hair down – he won’t be getting stinking drunk. “To be drunk” is to be intoxicated, to have too much alcohol. “To be stinking drunk” is an informal expression meaning to be really drunk, to be incredibly drunk, to be very drunk. A “school night” is kind of a joke here. When you are in school, of course any time you have to go to school the next day you can’t go out and party at night. Your parents will often say you have to study and be to bed by 10:00 on a school night. So, Monday, Tuesday, Wednesday, and Thursday – well, Sunday, Monday, Tuesday, Wednesday, Thursday are all school nights because the next day you have school, Monday through Friday. However, people sometimes use it just to mean a work night, a day that – or a night that will be followed by a day that you have to go to work. That’s what Mykhailo is talk about.
He says, “You were right. This place is nice. It even has a dance floor.” A “dance floor” is an area where you can dance to music, of course. Amy says, “On the weekends, there’s a live band or a DJ.” A “live band” is a musical group that performs; there are actually people up there singing and playing guitars and other musical instruments. A “DJ” stands for a disc jockey; it’s a person whose job it is to – well, it used to be to play records, to play discs, now they play compact discs or I guess MP3s, I’m not sure. But that’s a DJ, a person who is in charge of selecting the music. Amy says, “there’s also a cover charge on Fridays and Saturdays.” A “cover charge” means you have to pay money just to get into the bar or the club and, of course, you also have to pay for your drinks. A cover charge is, I don’t know, it used to be like 5, 10, 15 dollars. Now it’s probably more than that, I haven’t been to a bar with a cover charge since Ronald Reagan was president!
Mykhailo says, “So you do know how to party in the burbs.” Amy says, “Didn’t I tell you?” Mykhailo’s saying you guys also know how to have a good time. Mykhailo says, “But for me to get a thorough impression of the burbs, I’ll have to come here to check it out this weekend.” A “thorough impression” means a complete idea. An “impression” can mean the way that you understand something, the opinion you have about something. “Impression” can have a few other meanings as well; take a look at our Learning Guide for those.
So, Mykhailo is saying that in order to really understand whether this bar is a good place he’ll have to come back on the weekend. He says to Amy, “What are you doing Saturday night?” Now of course, Mykhailo and Amy are friends, but now it sounds like Mykhailo wants to see Amy again at this bar, so perhaps he has other ideas. Amy says, “Actually, I planned on coming here.” I was already going to come to this bar again on the weekend. Mykhailo says, “Want some company?” “Company” is other people who spend time with you. And of course, we think Mykhailo possibly is interested romantically in Amy. We’ll have to see later on. When? Probably never!
Now let’s listen to the dialogue at a normal speed.
[start of dialogue]
I’d been complaining to a coworker, Amy, about having to move to the burbs for my job. She said that there were plenty of things to do outside of the city and invited me to a bar she likes.
…
Amy: Hey, there you are.
Mykhailo: Hey, so this is the famous McQ’s you’ve been talking about.
Amy: This is it. What would you like to drink? They have several beers on tap and pretty good well drinks.
Mykhailo: I think I’ll get a couple of shots.
Amy: On a Wednesday night? You guys do party hard in the city.
Mykhailo: I’ve had a really rough week and I welcome any excuse to let my hair down. That said, I won’t be getting stinking drunk on a school night. You were right. This place is nice. It even has a dance floor.
Amy: On the weekends, there’s a live band or a DJ, although there’s also a cover charge on Fridays and Saturdays.
Mykhailo: So you do know how to party in the burbs.
Amy: Didn’t I tell you?
Mykhailo: But for me to get a thorough impression of the burbs, I’ll have to come here to check it out this weekend. What are you doing Saturday night?
Amy: Actually, I plan on coming here.
Mykhailo: Want some company?
[end of dialogue]
If you’ve listened to Dr. Lucy Tse’s scripts, you should have a good impression of what she does, I hope.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
burbs – suburbs; the area surrounding a city where there are many homes
* William lives in the burbs, so he has to drive more than an hour each morning to get to his office downtown.
bar – tavern; pub; a restaurant that mostly serves alcoholic drinks and some types of food
* Ingrid looks very young, so she always has to show her ID to get into a bar.
on tap – available from a faucet, usually when talking about a large barrel of beer that drinks can be served from
* We have a few local beers on tap, but most of our beers are sold in bottles.
well drink – an alcoholic beverage made from one of more types of liquor, mixed with juices, carbonated water, and/or other liquors
* My favorite well drinks have vodka and fruit juice in them.
shot – a small amount of a very strong liquor, served in a very small glass
* Drey celebrated by buying a shot of tequila for each of his friends.
to party hard – to enjoy oneself in an extreme way, having a lot of fun and usually drinking a lot of alcohol or using drugs
* Heather partied hard as a college student, but then she realized it wasn’t good for her, so she stopped.
to welcome any excuse to let (one’s) hair down – to be eager to have an opportunity or reason to relax and have fun, especially when one has been very stressed out, controlled, or limited in some way
* After testifying in court all day, I’d welcome any excuse to let my hair down! Let’s go!
that said – nevertheless; even though that is true
* I wish I had more money. That said, I’ll never steal.
stinking drunk – intoxicated; inebriated; acting and speaking strangely because one has drunken too much alcohol and cannot control one’s body or mind
* The teacher was fired for coming to school stinking drunk.
school night – an evening when one has to go to school or work the next morning; Sunday, Monday, Tuesday, Wednesday, or Thursday evening
* This has been fun, but it’s a school night, so I need to go home now.
dance floor – the part of a bar, restaurant, hotel lobby, or other building where there is room for people to dance to music, often with a lot of lights
* Everyone watched as the bride and groom stepped onto the dance floor.
live band – a musical performance, not recorded music
* Do you want to go hear the live band that’s performing at the theater next weekend?
DJ – disc jockey; a person whose job is to choose which recorded songs will be played for an audience, and in which order
* Matt is a DJ who specializes in weddings, so he has a huge collection of love songs.
cover charge – money that must be paid to enter a building, especially a popular bar or dance hall
* If I spend that much on the cover charge, I won’t have any money left to buy a drink once we get in!
thorough – complete; exhaustive; leaving nothing unknown or untouched
* Earning a certificate shows that you have a thorough understanding of computer programming languages.
impression – perception; the way one understands and interprets something, positive or negative
* Katie wore her best suit to the interview because she wanted to make a good impression.
company – another person or other people; people whom one spends time with so that one is not alone
* If you want some company, I could come over tonight.
Comprehension Questions
1. Where does Mykhailo need to move for his job?
a) To a very cold part of the country.
b) To a farming town.
c) To the residential area surrounding a big city.
2. What does Mykhailo want to do at the bar?
a) He wants to relax and have fun.
b) He wants to get his hair cut.
c) He wants to take off his hat.
Answers at bottom.
What Else Does It Mean?
shot
The word “shot,” in this podcast, means a small amount of a very strong liquor, served in a very small glass: “How many shots of bourbon have you had?” A “shot” is also one photograph: “Look at this great shot of the sun setting over the ocean.” Sometimes a “shot” is one attempt to do something: “His first shot at baking a pie was a disaster, but now he’s pretty good at it.” The phrase “to give (something) (one’s) best shot” means to try very hard to do something well, especially when it is difficult: “This job is so hard, but I’m going to give it my best shot.” Finally, the phrase “to be a long shot” is used when one doesn’t believe something will succeed: “Jenna knows that winning the beauty pageant will be a long shot, but she’s going to try anyway.”
impression
In this podcast, the word “impression” means perception, or the way one understands and interprets something, positive or negative: “When the speaker couldn’t get her PowerPoint presentation to work, it made a bad impression on the audience.” A “first impression” is the reaction one has to someone when meeting for the first time: “My first impression was that Khalid was rude, but then I realized he was just in a hurry.” When talking about artwork, an “impression” is a drawing of what something might look like: “This illustration is an artist’s impression of the train station that will be built here in the future.” Finally, the phrase “to be under the impression” means to have believed something that one later finds out was not true: “This is so embarrassing! I was under the impression that this was going to be a costume party.”
Culture Note
Types of Bars and Pubs
Americans enjoy going to many types of “drinking establishments” or “bars.” A “dive bar” is the least “sophisticated” (elegant; refined) type of bar. A dive bar is very informal and serves simple drinks, and “blue collar workers” (people who have little education and work with their hands) might go there after work to drink a few beers.
“At the opposite end of the spectrum” (as something that is very different), a “cocktail lounge” is an “upscale” (very fancy, nice, and expensive) bar where people “dress up” (wear nice clothing) and order expensive liquors or wine. Cocktail lounges are found in restaurants, hotels, and large airports. Businesspeople might go to a cocktail lounge to impress clients, or romantic couples might go there as part of a date.
A “wine bar” is a special kind of bar that serves only wine. “Patrons” (customers) might “sample” (try a small amount of) many different wines and then choose to buy their favorite wine “by the bottle” or “by the glass.” Wine bars often have small plates of fruit, cheese, and nuts available for sale, too.
A “brew pub” usually has a “full bar” (all types of alcohol), but specializes in “craft beers” (beers made in small quantities by small, local companies) that are “brewed” (made) “on site” (in the facility). Patrons can drink the beer in the pub, or they can buy a bottle to take home. Brew pubs often have a full menu of food offerings, too.
Other bars have a particular “theme” (main idea). For example, a “music bar” features live performances, and a “biker bar” “caters to” (specializes in serving) “bikers” (people who ride motorcycles).
Comprehension Answers
1 - c
2 - a