= 0796
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 796: Setting Up Conference Calls and Videoconferences.
This is English as a Second Language Podcast episode 796. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Become a member of ESL Podcast today, and download a Learning Guide for this episode that will help you improve your English even faster.
This episode is a dialogue about setting up or getting ready for a conference call and videoconferences. Let’s get started.
[start of dialogue]
Ewan: Who’s running the videoconference next week?
Petra: I am. Desmond put me in charge of it last week.
Ewan: Oh, somebody’s moving up in the world. It’s nice that he’s giving you more responsibility.
Petra: Yeah, but I’m not sure I’m ready.
Ewan: I’ve set up conference calls and videoconferences before. Maybe you can tell me what you’ve already done and I can see if you’ve missed anything.
Petra: That would be great. Okay, I’ve scheduled the meeting for 3:00…
Ewan: Stop right there. If the videoconference is at 3:00 here, it’s already 6:00 on the East Coast. That’s too late to start the meeting, don’t you think?
Petra: Oh, I didn’t factor in time zones! But I still have time to reschedule, I think, so it’s not a total catastrophe.
Ewan: Good. Be sure to initiate the call or the connection at least 10 minutes before the time of the meeting, and make sure you know how to reconnect someone if they get disconnected during the meeting.
Petra: I still need to figure that out.
Ewan: Are you facilitating the meeting, too?
Petra: I don’t know. I guess so.
Ewan: In that case, make sure you identify each person by greeting them by name.
Petra: I was hoping to lurk in the background in case something went wrong. I’d be ready to troubleshoot.
Ewan: If Desmond put you in charge of setting up the meeting, he’ll want you to take a more active part.
[Petra breathing heavily]
Ewan: What are you doing?
Petra: Hyperventilating. I don’t think I’m ready for this.
[end of dialogue]
Our dialogue begins with Ewan saying to Petra, “Who’s running the videoconference next week?” “Who’s running” meaning who’s organizing, who is the person who is managing the videoconference. A “videoconference” (one word) is a meeting where people in different locations, different cities perhaps different countries, talk to each other by using either a telephone line or an Internet line that allows you to see the person like you’re talking to them on a television set. It’s a video of all of the members who are part of this meeting – this conference. Petra says, “I am (I’m running the videoconference). Desmond put me in charge of it last week.” “To put (someone) in charge of (something)” means to say that they are going to organize it, they are going to run it.
Ewan says, “Oh, somebody’s moving up in the world.” “To move up in the world” is an expression meaning to be doing well or to be doing better professionally: to be getting more money, more responsibility, a better job. That’s to move up in the world. Ewan is sort of making a joke here. Ewan says, “It’s nice that he’s giving you more responsibility.” Petra says, “Yeah, but I’m not sure I’m ready.” She’s not sure she’s ready for this new responsibility. Don’t worry Petra, you’re ready! I know you. Well, I don’t know you because you don’t exist. But if you did, you’d be ready.
Ewan says, “I’ve set up conference calls and videoconferences before.” “Conference calls” are meetings where, like a videoconference, you have people in different places, perhaps in the country or even in the world, but typically they don’t involve any video. It’s just the telephone, or nowadays it might be on the Internet using a service like Skype. So Ewan says that he has set up conference calls and videoconferences before, and we all know what an idiot Ewan is, so if Ewan can do it certainly Petra can do it. That’s my opinion. Ewan says, “Maybe you can tell me what you’ve already done and I can see if you missed anything,” if there’s something you didn’t think of.
Petra said, “That would be great.” “Okay,” she says, “I’ve scheduled the meeting for 3:00.” Ewan says, “Stop right there,” meaning don’t say anything else. Usually we use this expression in a conversation when a person has said something that’s either wrong or perhaps not what you should be saying or should have done. So for example, I could say, “Well, I’m going to Europe. The first thing I’m going to do is buy myself a little boat so that I can get to Europe,” and someone would say, “Oh, stop right there. There’s no way you can take a little boat to Europe. It will take you a very long time.” That’s just an example.
Petra says she wants to schedule the meeting, or has scheduled the meeting for 3:00. Ewan says, “Stop right there. If the videoconference is at 3:00 here (meaning if it’s at 3:00 where we are, let’s say Los Angeles), it’s already 6:00 on the East Coast,” meaning there’s a time difference between Los Angeles and the East Coast of the United States where New York and Washington and Boston and Atlanta and other big cities are – Philadelphia, and so forth. Well, she scheduled the meeting at three, but it will already be 6:00 in New York and, of course, people may have already gone home.
Ewans say, “That’s too late to start the meeting, don’t you think?” Petra says, “Oh, I didn’t factor in time zones!” “To factor (factor) in” means to consider something in your decision. If you’re going to take a small boat from New York to France, you have to factor in all of the time it’s going to take you to take your boat from one side of the Atlantic to the other. So that’s to factor in, to consider. “Time zones” are one of the 24 geographic areas in the world that we divide up into different hours, so that when it is 3:00 in the afternoon here in Los Angeles it’s 4:00 in Las Vegas, it’s 5:00 in Chicago, and it’s 6:00 in New York. Three o’clock in the afternoon would be, I think, midnight in Rome – in central Europe. I think that’s right. Anyway, Petra says that she scheduled this meeting at three, and of course that won’t work. She says, “I didn’t factor in time zones. But I still have time to reschedule (to pick a new time), so it’s not a total catastrophe,” she says. A “catastrophe” is a disaster, something that is very serious, very negative. Normally we use this word in talking about an earthquake or a hurricane. Those would be, well, this would be disasters; if they caused a lot of damage they could be catastrophes. Or, if you lose a million dollars, that would be, for most people, a catastrophe.
Ewan says, “Good,” meaning good that you can reschedule it. He says, “Be sure to initiate (or begin) the call (the telephone call) or the connection at least 10 minutes before the time of the meeting.” The “connection” would be the connection, in this case, between two or more people; it could be on the Internet, it could be on a telephone line. Ewan says, “make sure you know how to reconnect someone if they get disconnected during the meeting.” So, “to get disconnected” means that, for example, you’re talking to someone and then suddenly your phone line stops working, or your Internet connection isn’t working and you get disconnected; you are no longer talking or communicating with that person. So if that happens, you have to get “reconnected,” connected again.
Petra says, “I still need to figure that out,” meaning I still need to understand how to do that. Ewan says, “Are you facilitating the meeting, too?” “To facilitate” (facilitate) means, really, to run the meeting, to be the person who is in charge of getting people to accomplish what they’re supposed to accomplish. Petra says, “I don’t know. I guess so.” She’s not sure if she’s running or facilitating the meeting. Ewan says, “In that case (in that instance), make sure you identify each person by greeting them by name.” “To greet (greet) (someone)” means to say hello to someone. “By name” means you use their name: “Hello Jeff, hello Petra, hello Newman.”
Petra says, “I was hoping to lurk in the background in case something went wrong.” “To lurk” (lurk) means that you are present, you are there, but you’re sort of hidden. Other people aren’t listening to you or observing you; you’re not participating. Petra says she wants to lurk in the background. The “background” here means in the environment, but not where everyone can see her. “To be in the background” means that no one is really paying attention. You’re there, you may even be influencing things, but no one sees you, no one talks to you, no one thinks about you. Petra says, “I’d be ready to troubleshoot.” “To troubleshoot” (one word) means to figure out what the problem is and how to solve it. So Petra wants to be part of the conference – the videoconference, but she doesn’t want be actively participating, we could say. She wants to lurk in the background and if there’s a problem she will troubleshoot it; she will figure out what the problem is and what the solution should be.
Ewan says, “If Desmond put you in charge of setting up the meeting, he’ll want you to take a more active part.” “To take a more active part” means to be an actual participant, to be talking and to be asking questions and so forth.
Petra then begins to breathe heavily; she starts breathing so that you can hear her breathe. Ewan says, “What are you doing?” Petra says, “Hyperventilating. I don’t think I’m ready for this.” “To hyperventilate” means to breathe very quickly and deeply, usually because you are very nervous or you’re frightened about something. Someone who starts to hyperventilate is breathing very fast and it could be dangerous; if they’re very nervous or very excited that might happen. So Petra isn’t really ready to facilitate, much less to set up the conference call or videoconference. Maybe she’s not as smart as I thought she was!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Ewan: Who’s running the videoconference next week?
Petra: I am. Desmond put me in charge of it last week.
Ewan: Oh, somebody’s moving up in the world. It’s nice that he’s giving you more responsibility.
Petra: Yeah, but I’m not sure I’m ready.
Ewan: I’ve set up conference calls and videoconferences before. Maybe you can tell me what you’ve already done and I can see if you’ve missed anything.
Petra: That would be great. Okay, I’ve scheduled the meeting for 3:00…
Ewan: Stop right there. If the videoconference is at 3:00 here, it’s already 6:00 on the East Coast. That’s too late to start the meeting, don’t you think?
Petra: Oh, I didn’t factor in time zones! But I still have time to reschedule, I think, so it’s not a total catastrophe.
Ewan: Good. Be sure to initiate the call or the connection at least 10 minutes before the time of the meeting, and make sure you know how to reconnect someone if they get disconnected during the meeting.
Petra: I still need to figure that out.
Ewan: Are you facilitating the meeting, too?
Petra: I don’t know. I guess so.
Ewan: In that case, make sure you identify each person by greeting them by name.
Petra: I was hoping to lurk in the background in case something went wrong. I’d be ready to troubleshoot.
Ewan: If Desmond put you in charge of setting up the meeting, he’ll want you to take a more active part.
[Petra breathing heavily]
Ewan: What are you doing?
Petra: Hyperventilating. I don’t think I’m ready for this.
[end of dialogue]
Our scriptwriter, Dr. Lucy Tse, works in the background. You don’t see her, but she’s there, certainly taking an active part by writing these wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
videoconference – a meeting where the participants are in different locations and can see each other on a video screen and hear each other through a speaker
* The company could save a lot of money if people would start meeting via videoconferences instead of traveling to other offices.
to move up in the world – to do well professionally and receive jobs with greater pay and more responsibility, and to receive more recognition and fame for one’s work or contributions
* Damian grew up in a poor neighborhood, but he realized that doing well in school would be the key to moving up in the world.
conference call – a meeting where the participants are in different locations but can hear each other’s voices through a telephone call with more than two participants
* Adam dislikes conference calls because it’s hard for him to identify who is speaking.
to factor in – to consider something in one’s decision
* Normally it takes 20 minutes to drive to the office, but if you factor in the morning traffic, it could take up to 45 minutes.
time zone – one of 24 large geographic areas where a single time is used
* The Center for Educational Development is in the Pacific Time Zone, which is three hours behind New York City.
catastrophe – a major disaster; an event with very serious, negative consequences, usually involving damage, suffering, or even death
* The hurricane was a catastrophe for local farmers.
to initiate – to begin or start something; to cause something to start to happen
* Who initiated the argument?
connection – a link or association between two points, especially when referring to electricity, phones, or Internet
* The connection on my cell phone isn’t very good when we drive through the mountains.
to disconnect – to lose the connection between two people or points, especially when referring to electricity, telephone, or Internet
* Which number can I reach you at in case we get disconnected?
to facilitate – to guide a discussion or meeting, keeping everyone on topic and making sure everyone has an opportunity to participate
* The hardest part of facilitating that meeting was making sure that the loudest speaker didn’t dominate the discussion.
to greet – to say hello to someone; to recognize someone’s presence and make him or her feel welcome by saying something
* Is Justin mad at me? He didn’t greet me when I came into the room.
by name – using someone’s name
* It took hours to announce all of the university graduates by name as each one received his or her diploma.
to lurk – to be present in a hidden way while listening or observing, but not participate
* A small number of people participate on my blog, while a lot of other people lurk there, reading comments without adding to the discussion.
background – backdrop; rear; the general environment around a place, but not exactly where the action is; the part of something that nobody really pays attention to
* The speaker was distracted by all the movement in the background.
to troubleshoot – to identify problems and solve them
* Please try to use the software manual to troubleshoot before you call to request technical support.
to take a more active part – to become an active participant in something; to assume a more involved role in something
* Doctors want their patients to take a more active part in their healthcare by exercising and eating well.
to hyperventilate – to breathe very quickly and deeply, often because one is frightened or panicked
* When Sheila thought she saw a ghost, she began hyperventilating.
Comprehension Questions
1. What does Ewan mean when he says that Petra is “moving up in the world”?
a) She’s beginning to work with their international colleagues.
b) She’s beginning to learn how to use new technology.
c) She’s beginning to take on more responsibilities at work.
2. According to Ewan, what does Desmond want Petra to do?
a) He wants her to lead the meeting.
b) He wants her to find a new videoconferencing company.
c) He wants her to take notes during the meeting.
Answers at bottom.
What Else Does It Mean?
to factor in
The phrase “to factor in,” in this podcast, means to consider something in one’s decision: “Make sure you factor in the cost of living before accepting a job in another part of the country.” When talking about mathematics, the verb “to factor” means to divide a number into the smaller numbers that can be multiplied to produce that number: “If you factor 12, you get 2 x 2 x 3.” As a noun, a “factor” refers to the cause of something: “The high unemployment rate is a factor in the rising crime rate.” The phrase “a key factor” or “a decisive factor” refers to something that is very important: “The many local regulations were a key factor in their decision to open an office overseas.”
connection
In this podcast, the word “connection” means a link or association between two points, especially when referring to electricity, phones, or Internet: “We’ll need a better Internet connection to watch streaming videos online.” The word “connection” also refers to networking and one’s relationship with another person, especially for professional or business purposes: “Do you have any connections in the software development industry?” The phrase “to have/feel a connection” can refer to one’s interest in having a romantic relationship with a particular person: “The date was fun, but I just didn’t feel a connection with Tom.” Finally, when talking about transportation, a “connection” can refer to an arrangement to move from one bus, train, or plane to another bus, train or plane: “The plane left Seattle two hours late, so we missed our connection in Dallas.”
Culture Note
Advantages and Disadvantages of Videoconferencing
“Videophone calls” are designed to help individuals communicate over the phone with a video “link” (connection) so that they can see each other “in real time” (as something is happening, not recorded and then viewed later). “Videoconferencing” is designed to connect larger groups of individuals at multiple locations in a similar way. “Advances” (progress) in communication technologies have improved the video “resolution” (how detailed an image is) and “reliability” (ability to maintain a connection), so today videoconferencing is popular in business, education, medicine, and more.
Videoconferencing offers many advantages. First, it reduces expenses because people do not have to travel for meetings. Videoconferences provide many of the “benefits” (advantages) of a “face-to-face” (in-person; in the same room) meeting without the “hefty” (significant; expensive) “price tag” (cost).
Of course, videoconferencing isn’t “quite” (exactly) the same as a face-to-face meeting. One problem is the “perceived” (seeming; apparent) “lack” (not having something) of eye contact. In a face-to-face conversation, people look into each other’s eyes. In a videoconference, people are looking at the screen and not into the camera, so the viewer “has the impression” (believes) that the other participants are not making eye contact and are not listening. Some people are also “overly conscious” (worried) about their appearance on camera, and that can affect their level of comfort and their performance. Finally, there may be short delays in “transmission” (sending signals) that can make it seem as if the other participants are “hesitating” (waiting) before responding to someone’s comments. This can make the conversation feel “unnatural” (uncomfortable) and “stilted” (stiff).
Comprehension Answers
1 - c
2 - a