= 0799
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 799: Dealing With the Heat.
This is English as a Second Language Podcast episode 799. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in – you guessed it – Los Angeles, California.
Our website is eslpod.com. Go there, become a member of ESL Podcast; help support this podcast. Keep us going!
This episode is about dealing with or handling the heat, when it gets very hot outside. Let’s get started.
[start of dialogue]
Jolene: I’m sweating like a pig. When is this heat wave going to end?
Eric: I’ve no idea, but I’m not moving a muscle until it does. Hand me that pitcher of iced tea, would you?
Jolene: Get it yourself. I’m not moving until it drops below 80 degrees.
Eric: It’s not the temperature. It’s the humidity. It’s not even the dog days of summer yet and it’s scorching outside.
Jolene: It’s scorching inside, too. Why can’t that fan move any faster? Remind me why we moved into an apartment with no air conditioner?
Eric: We couldn’t afford an apartment with an air conditioner. We were lucky to get this place.
Jolene: I don’t feel so lucky right now. My legs are stuck to this chair and I’ve sweated through my clothes.
Eric: We could buy a portable air conditioner.
Jolene: We can?
Eric: Yeah, but you’d have to get up.
Jolene: Ugh, let’s do it tomorrow.
[end of dialogue]
This episode is entitled – has the title of – “Dealing With the Heat.” “To deal (deal) with (something)” is a phrasal verb meaning to manage or to handle, to react to something in a certain way. This is dealing with the heat, when the temperature gets very high.
Jolene – who is not high, but is apparently hot – says, “I’m sweating like a pig.” “To sweat” (sweat) means you have liquid leaving your body, because your body is so hot so there is what feels like water on your skin. Many people sweat a lot when it gets hot. I have a friend who sweats a lot, even like when it’s 75 degrees; I mean it’s kind of strange. But anyway, “to sweat” means to have this water on your body – this liquid that comes out of your body when it gets very hot. “Sweat” also has other meanings in English; take a look at our Learning Guide for those. Jolene says, “When is this heat wave going to end?” A “heat wave” (wave – two words) is a period of time, usually a couple of days, maybe a week, when the temperature seems very hot, when it’s hotter than usual. In the summertime we often have heat waves here in Los Angeles, where it gets very hot for maybe a week or so. Doesn’t happen all that often, but it does happen.
Eric says, “I’ve no idea (I have no idea when this heat wave is going to end he means), but I’m not moving a muscle until it does.” “To not move a muscle” means not to move, not to get up, not to move your body, because it’s so hot – that’s the idea. Eric says, “Hand me (or give me) that pitcher of iced tea, would you?” A “pitcher” is a large glass or plastic container that we use to put liquid in. “Pitcher” (pitcher) is something we would use for beer or tea or some other sort of usually cold liquid.
Eric says he wants some iced tea, some tea that has ice in it. Jolene, however, is not interested in helping Eric; she says, “Get it yourself. I’m not moving until it (the temperature) drops below 80 degrees.” “To drop” means to go lower. “Drop” has a couple of other meanings in English as well; take a look at our Learning Guide for those. Here it means for the temperature to go down; in this case, to go below 80 degrees. A “degree” here means a unit of measurement of temperature. In the United States, we use the Fahrenheit scale; in most other countries the Celsius scale is used.
Eric says, “It’s not the temperature. It’s the humidity.” He’s saying the reason it’s so uncomfortable outside or uncomfortable where they are is because of the humidity, not because of the temperature. “Humidity” is how much moisture – how much liquid is in the air – how much water is in the air. “Temperature” refers to how hot or cold it is. So, you could have a very high temperature but not very much humidity. It could be very dry out; there’s not very much water in the air. Places like Phoenix, Arizona, or anywhere in a desert, has very high temperatures but also very dry weather, so it’s what we would call a “dry heat,” there’s not a lot humidity. Some places have both heat and humidity, states like Florida for example, in the southeast part of the United States, and there when it gets hot it gets very uncomfortable because there’s also a lot of water in the air. This is actually sort of an old expression: “It’s not the heat, it’s the humidity.” Eric says, “It’s not the temperature. It’s the humidity,” but there’s a more common way of saying that. “It’s not the heat, it’s the humidity,” meaning the real problem is not that it’s hot out, but that there’s so much water in the air.
Eric says, “It’s not even the dog days of summer yet and it’s scorching outside.” “The dog days of summer” is an expression used to describe the hottest days of the year in the summertime. Usually in the United States, that’s sometime in July or August. The phrase is sort of associated with the time where it’s so hot that you can’t really do anything else, so it might not be a very exciting time of year because it’s so hot. The dog days of summer would be days where it’s so hot you can’t really have a lot of fun.
Eric says, “it’s scorching outside.” When we say something is “scorching” (scorching) we mean it’s extremely hot. Jolene says, “It’s scorching inside, too (meaning inside of the house). Why can’t that fan move any faster?” A “fan” (fan) here means a small machine that moves air around; it blows air in a little circle that is supposed to help make you cooler. Jolene says, “Remind me why we moved into an apartment with no air conditioner?” An “air conditioner” is a machine that produces cold air during times when it’s hot outside. Jolene says, “Remind me.” Literally, this means help me remember something, but in the way that she’s using it she’s really sort of complaining. She’s wondering why we did something that perhaps wasn’t very intelligent, wasn’t a very good idea. “Remind me why we moved into an apartment with no air conditioning. The “remind me” means I think we made a mistake; she’s saying that we made a mistake.
Eric answers her; he says, “We couldn’t afford an apartment with an air conditioner.” “To afford” means to have enough money. Eric says that he and Jolene could not afford an apartment with an air conditioner. “We were lucky to get this place,” he says. Jolene says, “I don’t feel so lucky right now. My legs are stuck to this chair and I’ve sweated through my clothes.” “To be stuck” (stuck) means to be attached to something else, often so that you can’t move it or not move it very easily. Because Jolene is sweating so much she’s stuck to her chair; she can’t move because the water is sticking to her skin and to the chair. Jolene says that she’s sweated through her clothes. “To sweat through” means that you’ve been sweating so much your clothes are now wet. Your shirt and your pants are wet because of your sweat. “Wet from sweat,” we might say.
Eric says, “We could buy a portable air conditioner.” Something that is “portable” (portable) is something you can move easily from one place to another. Eric says that they could buy a portable air conditioner. Air conditioners usually are either in a window or they’re part of the building or the house where you live; they’re part of the way that the house or apartment is built, you don’t have to buy a separate machine. But it is possible to buy a separate portable air conditioner you can just move from one room to another.
Jolene says, “We can?” Eric says, “Yeah, but we’d have to get up,” meaning we’d have to leave our seats and actually go somewhere. Jolene says, “Ugh, let’s do it tomorrow.” She’s so tired, she’s so hot, she doesn’t want to get up and get the portable air conditioner today.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Jolene: I’m sweating like a pig. When is this heat wave going to end?
Eric: I’ve no idea, but I’m not moving a muscle until it does. Hand me that pitcher of iced tea, would you?
Jolene: Get it yourself. I’m not moving until it drops below 80 degrees.
Eric: It’s not the temperature. It’s the humidity. It’s not even the dog days of summer yet and it’s scorching outside.
Jolene: It’s scorching inside, too. Why can’t that fan move any faster? Remind me why we moved into an apartment with no air conditioner?
Eric: We couldn’t afford an apartment with an air conditioner. We were lucky to get this place.
Jolene: I don’t feel so lucky right now. My legs are stuck to this chair and I’ve sweated through my clothes.
Eric: We could buy a portable air conditioner.
Jolene: We can?
Eric: Yeah, but you’d have to get up.
Jolene: Ugh, let’s do it tomorrow.
[end of dialogue]
Many of you listen to this podcast on a portable device, something you can carry around – move around with you. So, you can carry around the wonderful scripts by Dr. Lucy Tse that you hear on these episodes.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2012 by the Center for Educational Development.
Glossary
to sweat – to have liquid leaving one’s body through the surface of one’s skin, usually because one is very hot, has done a lot of physical activity, or is nervous
* After exercising, it’s a good idea to drink water to replace the liquid you lost through sweating.
heat wave – a period of time (usually a few days) with temperatures that are higher than usual
* Normally we have warm summers, but last July we had a heat wave where temperatures were over 100 degrees every day for a week.
to not move a muscle – to not move at all; to be perfectly still
* A butterfly just landed on your shoulder! Don’t move a muscle or you might scare it away.
pitcher – a glass or plastic container with a large handle and a spout (the part of a container used for pouring liquids), used to hold beverages
* If everyone is going to drink lemonade, it would be cheaper for us to buy a pitcher at the restaurant.
to drop – to fall below a certain number or value; to decrease
* The network is going to cancel the TV show if its ratings continue to drop.
degree – a unit of measurement for temperature, usually in Celsius (°C) or Fahrenheit (°F)
* Lynn usually heats her home to 72 degrees, but she lowered it to 68 degrees to try to save some money.
temperature – a measure of how hot or cold something is
* The freezing temperatures have killed all the plants we put in the garden last weekend.
humidity – a measure of the amount of moisture (liquid) in the air
* Washington, D.C. feels hotter than it actually is because there’s so much humidity in the air.
dog days of summer – the hottest days of the year
* Ingrid doesn’t like hot weather, so she always travels to the mountains during the dog days of summer.
scorching – very hot; extremely hot
* How can you wear a long-sleeved black shirt in this scorching weather?
fan – a small machine that has long blades (flat pieces) that move around in a circle very quickly to blow air in one direction, usually used to cool down a room
* Please turn on the bathroom fan when you take a shower.
to remind – to help someone remember something; to tell someone something that he or she has forgotten
* Please remind me to return the library books by Thursday.
air conditioner – a machine that produces cold air so that a home or building has a more comfortable temperature
* The air conditioner makes my office so cold that I have to wear a jacket inside!
stuck – attached to something else, not able to move freely
* The window is stuck. Can you help me open it?
to sweat through – for one’s clothing to be wet from the liquid coming off of one’s body, usually because one is very hot or has done a lot of physical activity
* Whenever Neva speaks in public, she gets nervous and sweats through her blouse, so she always wears a suit jacket.
portable – able to be moved around; not permanently attached to something
* They used a portable CD player to keep their kids entertained during the long flight.
Comprehension Questions
1. According to Eric, why are they so uncomfortable?
a) Because there’s a lot of moisture in the air.
b) Because there isn’t any wind.
c) Because they’re wearing the wrong clothes.
2. Why doesn’t Jolene want to get an air conditioner today?
a) Because she’s doesn’t want to go to the store when it’s so hot.
b) Because she doesn’t think they have enough money.
c) Because she doesn’t think she’ll be able to carry it home.
Answers at bottom.
What Else Does It Mean?
to sweat
The verb “to sweat,” in this podcast, means to have liquid leaving one’s body through the surface of one’s skin, usually because one is very hot, has done a lot of physical activity, or is nervous: “Sorry I’m sweating so much, but I just got back from a run.” The verb “to sweat” can also mean to be nervous or anxious: “Don’t sweat it! You’re going to do well on the exam.” The phrase “no sweat” means “no problem” and is used as an informal response when someone expresses gratitude: “I tried to thank James for his help, but he just said, ‘No sweat.’” Finally, the verb “to sweat” can mean for liquid to condense or appear on the outside of a cold glass: “That glass of lemonade might sweat, so please don’t put it directly on the wood table.”
to drop
In this podcast, the verb “to drop” means to fall below a certain number or value, or to decrease: “They’re waiting for home prices to drop a little more before they buy their first house.” The phrase “to drop by” means to visit someone without an appointment: “The neighbor dropped by to give us some cookies.” The phrase “to drop out” means for someone to stop attending school before graduation: “What percentage of U.S. high school students drop out?” The phrase “to drop names” means to try to seem important or powerful by mentioning famous or well-respected people in conversation: “April was dropping names at the party. Do you think she knows all those celebrities, or was she just trying to impress us?”
Culture Note
Historic Heat Waves
The United States has experienced many heat waves, many of which were “deadly” (killed many people). One of the most “severe” (extreme) weather “phenomena” (something that happens and is observed) was in 1936, when much of North America experienced a “historic” (important in history) heat wave in the summer and then a “cold wave” (a period of very cold temperatures) in the winter. More than 5,000 people died and many “crops” (plants grown in fields for food or other use) were “destroyed” (ruined).
Another heat wave “struck” (affected people) in 1954. Eleven states “witnessed” (saw; experienced) temperatures higher than 100 °F for 22 days “in a row” (without interruption), and East Saint Louis in Illinois “recorded” (measured and wrote down) a temperature of 117 °F, which is the highest temperature ever recorded there.
About 10,000 people died during a heat wave and “drought” (a period of time without rainfall) in 1980 that affected the central and eastern parts of the United States. The area around Dallas and Fort Worth, Texas recorded temperatures above 100 °F for 42 “consecutive” (in a row; without interruption) days.
More recently, the heat wave in 2006 killed more than 200 people and Los Angeles County recorded its highest temperature ever: 119 °F.
March 2012 also brought a heat wave, breaking “temperature records” (the most extreme temperatures) in 1,054 locations across the United States. The temperatures were not the highest temperatures ever recorded, but they were extremely high for that time of the year.
Comprehension Answers
1 - a
2 - a