= 0710
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 710: Doubting One’s Language Use.
This is English as a Second Language Podcast episode 710. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Support this podcast by becoming an ESL Podcast member. In addition to feeling good about yourself for supporting this podcast, you can also download a Learning Guide for each of our current episodes that will help you improve your English faster than ever.
This episode is about doubting one’s language use, especially when you’re speaking another language, which, of course, most of you are. Let’s get started.
[start of dialogue]
Flora: Can you help me? I’m working on this email to Emil and I’m having trouble coming up with the right words in French.
Andy: My French isn’t much better than yours, but I’ll give it a shot.
Flora: Okay, read this sentence for me. What I want to know is if that is a suitable way to say that I’m sick, but that I’m not seriously ill.
Andy: Word choice can be tricky, but I think that’s the appropriate word, with the right meaning and the right connotations.
Flora: Okay, now read this sentence. It doesn’t sound right to me. Is this the right usage of the word “faire”? I really doubt it.
Andy: That’s because you’re using the wrong form of the verb, I think. Now if only I can think of the correct form. My French is really, really rusty.
Flora: Now that you’ve pointed out the problem, I can look it up later. What about this paragraph? The last sentence sounds awkward to me.
Andy: It sounds okay to me, but then again, I’m not a native speaker.
Flora: Ugh, this is so frustrating! It’s such a production every time I write him an email.
Andy: Maybe Emil will learn English and your troubles will be over.
Flora: Yes and maybe monkeys will fly out of my butt!
[end of dialogue]
Our dialogue begins with Flora saying to Andy, “Can you help me? I’m working on this email to Emil and I’m having trouble coming up with the right words in French.” “To come up with (something)” is a phrasal verb meaning to think of something, to have an idea for something or an idea about something: “I have to come up with a title for this episode.” I have to invent one; I have to think of one; I have to create one. Flora is having difficulty coming up with or thinking of the right or correct words in French for an email she’s writing in French.
Andy says, “My French isn’t much better than yours,” meaning my knowledge of French, or my French fluency or proficiency isn’t much better than yours. He says, “I’ll give it a shot.” “To give (something) a shot” (shot) means you’ll try something even when you don’t think you will be successful, usually because it’s very difficult. “I’m not very good at fixing cars, but I’ll give it a shot.” I’ll try; I don’t expect I will be successful. Andy is going to give it a shot, going to give helping Flora in her French email a shot.
Flora says, “Okay, read this sentence for me. What I want to know is if that is a suitable way to say that I’m sick, but that I’m not seriously ill.” A “suitable” (suitable) way is an appropriate way, an acceptable way, something that is okay to do in a particular situation. Flora wants to know if she’s using the right word to say that she’s sick, but not seriously sick.
Andy says, “Word choice can be tricky.” “Word choice” is picking the right word to say exactly what you want to say. “Tricky” (tricky) here means difficult or challenging, something that is easy to make a mistake at. So, it can be difficult to pick the right word. Andy says, “Word choice can be tricky, but I think that’s the appropriate word, with the right meaning and the right connotations.” “Appropriate” here means the same as suitable; it’s something that is acceptable; it is right for this situation. Andy thinks she has the right word; it has the right “meaning” – the right definition, if you will, and the right connotations. A “connotation” (connotation) is an additional meaning to a word or a phrase; it is the ideas that you think of when you hear that word and phrase even if it isn’t the actual definition that you would find in a dictionary. We have something called the “denotation,” that’s the definition that you will see in a dictionary. The “connotation” are all the other meanings that are associated with that word or things that you think of when you hear that word. For example, the word “stubborn” means the same as “strong-willed.” It’s someone who doesn’t change their mind, someone who will do what they want to do even if other people disagree with them. However, the connotations of stubborn are negative. If you say someone is stubborn, that’s a criticism. If you say someone is strong-willed, that is a compliment usually; it means that they are a strong person, a good thing. So the connotations are different, even though the denotations are similar.
Andy thinks this word that Flora chose is the right word. I’m not sure what word it is. Je ne sais pas, as we say in French. That means, I think, I don’t know. I’m not sure, I don’t know! Anyway, Flora then says, “Okay, now read this sentence. It doesn’t sound right to me.” When we say something doesn’t “sound right” we mean that it might be grammatically correct but it isn’t the exact meaning you want or it isn’t what people would normally say in this situation. Flora says, “Is this the right usage of the word ‘faire’? I really doubt it.” “Usage” (usage) is the way that a word or phrase is used. The correct grammatical way that you use a word as well as the correct meaning, that’s usage. Flora is asking about how the verb “faire” in French is used. Flora says that she doubts that she is using it correctly. “To doubt” means that you are not sure about something.
Andy says, “That’s because you’re using the wrong form of the verb, I think.” “Form” here refers to the correct conjugation of the verb; is it for “I” or “you” or “they,” that sort of thing. “Form” has many meanings in English, of course. Some of those can be found in our Learning Guide for this episode. Andy says, “Now if only I can think of the correct form.” He means he doesn’t know what it is, but he’s trying to think of it right now: “If only I can think of the correct form.” He says, “My French is really, really rusty (rusty).” “Rusty” is a way of saying that it isn’t as strong as it used to be; I haven’t practiced it; I haven’t used it. You can say this about anything; you could say, “Oh, I used to be a very good tennis player, but now I’m little rusty.” “Rust” (rust) is what happens when you have metal changing because of water and air and other things that change the outside of the metal; often it becomes a reddish color. But in the sentence, “rusty,” as an adjective, is used to mean something that you used to do well but don’t do very well anymore.
Flora says, “Now that you’ve pointed out the problem (now that you’ve told me what’s wrong), I can look it up later.” “To look (something) up” is a two-word phrasal verb meaning to search for it. We used to search for it in books, dictionaries, grammar books. Nowadays, people search for it on the Internet, they Google it. That’s how we look things up nowadays, how we research, how we investigate something to find an answer. Flora says, “What about this paragraph? The last sentence sounds awkward to me.” The verb “to sound” here is normally for something to make a noise, like “the bell sounds” or “the alarm sounds.” But here, it means seems: “The last sentence seems to me to be awkward.” It appears to me; that’s the way I’m reading it; that’s my interpretation; it seems to me the last sentence sounds awkward. “Awkward” (awkward) means that it isn’t quite right. It’s often used to describe something that’s difficult to do, or someone who is in a tough position or an uncomfortable position. Here, when we say it sounds awkward, we mean it doesn’t sound correct.
Andy says, “It sounds okay to me, but then again, I’m not a native speaker.” “Then again” means on the other hand: “However, I’m not a native speaker.” A “native speaker” is someone who grew up, usually from the time they were a small baby, hearing and speaking the language.
Flora says, “Ugh, this is so frustrating! It’s such a production every time I write him an email.” “Production” here means something that requires a lot of work. Andy says, “Maybe Emil will learn English and your troubles will be over.” When we say someone’s troubles will be over, we mean that sometime in the future, we’re not sure when, they will no longer have this problem. Flora says, “Yes and maybe monkeys will fly out of my butt!” Well, your “butt,” you probably know, (butt) is what you sit on. This is a very informal phrase that comes from a movie in the 1990s called Wayne’s World in English. It was a movie with Mike Myers. Anyway, in the movie they’re talking about something that seems very impossible, something that would be almost impossible to happen. For example, you might say, “Well, maybe you will become President of the United States,” which doesn’t seem very likely, and you can reply, “Well, yeah. Maybe monkeys will fly out of my butt!” Of course, monkeys don’t fly, and they certainly don’t fly out of your butt! It’s a funny phrase. The old phrase was “when pigs fly.” “When pigs fly” is meant to indicate an impossible condition. Pigs, of course, don’t fly, and so it will never happen. So, it’s another way of saying that will never happen. Do not use this with your boss!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Flora: Can you help me? I’m working on this email to Emil and I’m having trouble coming up with the right words in French.
Andy: My French isn’t much better than yours, but I’ll give it a shot.
Flora: Okay, read this sentence for me. What I want to know is if that is a suitable way to say that I’m sick, but that I’m not seriously ill.
Andy: Word choice can be tricky, but I think that’s the appropriate word, with the right meaning and the right connotations.
Flora: Okay, now read this sentence. It doesn’t sound right to me. Is this the right usage of the word “faire”? I really doubt it.
Andy: That’s because you’re using the wrong form of the verb, I think. Now if only I can think of the correct form. My French is really, really rusty.
Flora: Now that you’ve pointed out the problem, I can look it up later. What about this paragraph? The last sentence sounds awkward to me.
Andy: It sounds okay to me, but then again, I’m not a native speaker.
Flora: Ugh, this is so frustrating! It’s such a production every time I write him an email.
Andy: Maybe Emil will learn English and your troubles will be over.
Flora: Yes and maybe monkeys will fly out of my butt!
[end of dialogue]
Our scriptwriter comes up with wonderful scripts each and every week for you here on ESL Podcast. That’s the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
to come up with – to think of; to have an idea about or for something
* How did you come up with such a creative marketing campaign?
to give it a shot – to try to do something, especially when one doesn’t think one will be successful, usually because it is too difficult
* I’m not very good at fixing cars, but I’ll give it a shot.
suitable – appropriate; acceptable; okay to use, have, or do in a particular situation
* Shorts and a t-shirt aren’t suitable for a wedding.
word choice – the selection of a particular word when there are several other that have similar meanings
* Su asked the teacher to talk about selecting the correct word choice for this sentence among the words “angry,” “furious,” “mad,” and “upset.”
tricky – difficult; challenging, with a high probability of making a mistake
* Some of the math questions on that test were really tricky.
appropriate – suitable; acceptable; okay to use, have, or do in a particular situation
* Racist and sexist jokes are never appropriate in the workplace.
connotation – the additional meanings related to the core or main meaning of a word; the ideas that a particular word makes someone think of
* The words “stubborn” and “strong-willed” have the same meaning, but “stubborn” has a more negative connotation.
to sound right – for a phrase to seem to be accurate or grammatically correct based only on how one reacts when hearing it, without understanding the underlying rules
* It just doesn’t sound right, but I can’t explain why and I don’t know how to fix it.
usage – the way a word or phrase is used grammatically
* Kim wrote her report on how the usage of slang changes over time.
to doubt – to be unsure whether something is true or correct; to believe that something is possibly false or incorrect, but not know with certainty
* This résumé seems too good to be true. I doubt the candidate really has an Olympic gold medal, a Nobel Peace Prize, and a Purple Heart.
form – one of many possible conjugations and tenses of a verb
* Which form of the verb is correct here: “I will have eaten” or “I would have eaten”?
rusty – unpracticed; describing a skill that is not as strong as it once was, because one has not used it in a long time
* Paulo hasn’t taken a math class since high school, so his algebra skills are really rusty.
to look (something) up – to search for a word or concept in a reference book like a dictionary, thesaurus, or encyclopedia to learn more about it
* As a pharmacist, Busaraporn often looks medicines up in special books to learn more about them.
awkward – uncomfortable; difficult to do, use, or observe; inconvenient; problematic
* Most teenagers are awkward while their bodies are changing during puberty.
native speaker – a person who is raised in an environment where a particular language is used and therefore learns to speak it perfectly
* Make sure a native speaker reviews the translation before you publish it.
production – something that requires a lot of work and/or the involvement of many people because it is complex
* Once you have kids, packing for a weekend trip becomes a production. There are so many things you have to bring!
(one’s) troubles will be over – a phrase used to talk about some unspecified time in the future when the problems one is currently facing will no longer exist
* Stephen doesn’t have enough money for food right now, but he dreams that once he finishes school and gets a job, all of his troubles will be over.
monkeys will fly out of my butt – a very informal phrase used to show one does not believe something will happen
* - Within 20 years, we will achieve world peace.
* - Sure, and monkeys will fly out of my butt!
Comprehension Questions
1. What does Andy mean when he says, “I’ll give it a shot”?
a) He’s agreeing to send Flora’s email.
b) He’s going to delete Flora’s email for her.
c) He will try to help Flora improve the email.
2. Why does Andy describe his French as “rusty”?
a) Because he hasn’t used his French in a long time.
b) Because he never studied French with a native speaker.
c) Because he only knows colloquial French with a lot of slang.
Answers at bottom.
What Else Does It Mean?
to give (something) a shot
The phrase “to give (something) a shot,” in this podcast, means to try to do something, especially when one doesn’t think one will be successful, usually because it is too difficult: “This recipe seems really hard, but we’ll give it a shot.” The phrase “to give (something) one’s best shot” means to work as hard as one can to do something difficult: “I doubt we can clean the house in just four hours, but let’s give it our best shot.” The phrase “a long shot” refers to something that is unlikely to succeed: “Yolanda is going to apply for the job, even though she knows it’s a long shot.” Finally, the phrase “a shot in the dark” refers to a guess made without any actual knowledge about the topic: “If you don’t know the answer to a question on the test, at least take a shot in the dark.”
form
In this podcast, the word “form” means one of many possible conjugations and tenses of a verb: “Why do so many verbs have irregular forms?” A “form” is often a piece of paper that requests information, usually as part of an application: “Just fill out this form and pay $40, and then we’ll give you your new driver’s license.” The phrase “to take form” means to begin to have a certain shape and begin to be established: “When the construction crew started working across from our home, it was interesting to watch the building take form over time.” Finally, the phrase “true to form” refers to someone who is doing what one expects of him or her, often a negative thing: “True to form, Gretl refused to share her cookies with anyone else. She has always been very selfish.”
Culture Note
Idioms Related to Monkeys
Modern American English has many idioms and sayings that seem to refer to monkeys. Today’s dialogue used “monkeys will fly out of my butt,” but there are other monkey-related phrases that are even more common.
For example, Americans sometimes talk about “monkeying around,” which means to behave foolishly, doing things that are unimportant, “pointless” (without a purpose), and silly. Sometimes parents tell their children, “Stop monkeying around before someone gets hurt!” People can also refer to children as “monkeys,” especially if they are very active and curious: “What are you doing, little monkey?”
The phrase “monkey business” refers to actions or behaviors that are wrong, not honest, and hidden. One could say, “Why are so many politicians involved in monkey business?” Or, “The reporter is trying to investigate some of the monkey business that happens on Wall Street.”
The phrase “monkey see, monkey do,” is used to talk about how children end up doing what they observe, not what they are told to do: “If you really want your children to eat healthy foods, you need to stop eating so much “junk food” (food with little or no nutritional value). Monkey see, monkey do.”
The phrase “more fun than a “barrel” (a large, wooden container used to store wine and other liquids) of monkeys” describes something that is very enjoyable: “Going to Disneyland was more fun than a barrel of monkeys!”
Finally, the phrase “a monkey on (one’s) back” refers to a serious problem that makes one’s life more difficult. For example, the “IRS” (Internal Revenue Service; tax-collection agency) could be a monkey on your back during an “audit” (an examination of financial papers).
Comprehension Answers
1 - c
2 - a