= 0725
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 725: Childhood Illnesses and Diseases.
This is English as a Second Language Podcast episode 725. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there today and become a member of ESL Podcast. The world will be a happier place if you do!
This episode is on the always-happy topic of childhood illnesses and diseases. We’re going to talk about the names of some common illnesses and diseases that, unfortunately, children sometimes get. Let’s get started.
[start of dialogue]
Rebecca: You look exhausted! Another tough day at the daycare center?
Puneet: Yeah, it was. This is a record year for the kids getting sick. The chicken pox is going around. Last year, it was the measles. The year before that, it was the mumps. This year, it’s the chicken pox.
Rebecca: You sent the kids home, right?
Puneet: Yeah, but today, a couple of the kids looked like they have pink eye, and I had to call their parents to let them know.
Rebecca: What happened to simple nosebleeds and earaches?
Puneet: Oh, we have kids with those, too, but it’s the contagious diseases that really take its toll. I’m not sure, but I think one of the little kids has strep throat, and a couple of the really little kids have croup. I wish there were a way to immunize all of them from every illness and disease out there.
Rebecca: Are you sure you’re working in a daycare center?
Puneet: Yeah, why?
Rebecca: Because it just sounds like you’re working at the Center for Disease Control. Tomorrow, I suggest wearing a gas mask to work.
[end of dialogue]
Rebecca begins by saying to Puneet, “You look exhausted (meaning you look very tired)! Another tough day at the daycare center (another difficult day at the daycare center)?” “Daycare centers” are places where you can take young children, and they will take care of them for you during the day – pretty logical. Daycare is usually something provided for children who are not yet old enough to go to school, so anyone from being a baby to, say, five or six years old, although some programs also have after school care, where you can take a child after they finish school. However for the most part, daycare is for men and women who work during the day and need someone to watch their young children.
Puneet says, “Yes, it was (it was a tough day). This is a record year for the kids getting sick.” A “record year” is a year where you have the highest level or highest amount of something, a year with more of something than any other year. So if you said, “This is a record year for rainfall,” for the amount of rain that has fallen from the sky in this area, that means that no other year has had as much rain as this year. “Record” has a couple of different meanings in English; you can find those in our wonderful Learning Guide.
Puneet says the kids are getting sick this year more than any other year, so it’s a record year. “The chicken pox is going around.” “Chicken pox” (pox) is an infection that is easily shared among children, and sometimes among adults. It is a disease that can give you a fever – a high temperature, it causes you to be tired, and more importantly, it produces small, little red spots or marks on your skin that are “itchy,” meaning you want to take your fingers and move them back and forth over them, what we would call “scratch” them. That’s chicken pox; it’s a very common disease – illness among children. I had chicken pox. I think you can get chicken pox typically just once, and I certainly remember having it when I was a young child. When we say something is “going around,” we mean that many different people seem to be getting this illness or this sickness. We could talk about the flu is going around – influenza; many people are getting sick from it. In this case, “The chicken pox is going around. Last year, it was the measles,” meaning last year the disease that was popular, that was going around among the children was measles. “Measles” (measles), which I believe the more technical name would be rubeola; it’s a disease that also causes fever – high temperature, as well as coughing, red eyes, and like chicken pox, many red spots on the skin. I’m not sure if I had measles when I was young; I don’t think so. I don’t remember; it was so many years ago.
So, Puneet says that last year the popular disease was measles, “The year before that, it was the mumps” (mumps). The “mumps” is another disease that causes pain in your what we call “salivary glands.” It’s the part of the body that produces liquid inside of your mouth. So you often have pain near your ears, and it’s technically an “inflammation.” That is, it causes it to grow – to swell. Although I’m not a real doctor, so if I’m not describing these perfectly, and you’re a doctor, please don’t email and say, “Jeff, no, actually it’s…” – well, you get the idea, right? It’s not fun, the mumps. Did I have the mumps? I don’t remember; you’ll have to ask my mother!
Puneet says, “This year, it’s the chicken pox.” Rebecca says, “You sent the kids home, right?” meaning the children could not stay at the daycare if they were sick, because then other kids would get sick. Puneet said, “Yeah (meaning yes, I did send them home), but today, a couple of kids (two or three) looked like they have pink eye, and I had to call their parents to let them know.” “Pink eye” is another disease – another illness that can be caught from one person to another, what we would say a “contagious” disease. Its technical name is conjunctivitis, and it is an infection on the white part of your eye; your eye actually becomes pink, and it can be quite painful as well.
Rebecca says, “What happened to the simple nosebleeds and earaches?” A “nosebleed” is when blood comes out of your nose and you can’t stop it quickly; usually it just lasts for a few minutes. If you hit your nose you might get a nosebleed. “Earaches” are when you have pain in your ears. Nosebleeds and earaches are not serious illnesses; they’re not serious medical problems. They are something that children often get, and that’s why Rebecca is saying, “What happened to simple nosebleeds and earaches?” She’s really saying it used to be kids would only get simple problems, and now it seems the problems are getting worse. That’s sort of the idea of her question.
Puneet says, “Oh, we have kids with those, too, but it’s the contagious diseases that really take its toll (or that really take their toll).” “Contagious” means, as I mentioned earlier, that it is easy for the disease to go from one person to another. A “disease” is just another name for an illness or a sickness. When we say something is “taking its toll,” we mean that it is having a negative impact on something; it is having a bad effect on something. Puneet says, “I’m not sure, but I think one of the little kids has strep throat.” “Strep (strep) throat” is when you have an infection in your throat that makes it very painful. I had strep throat more than once when I was a child, I’m pretty sure. In any case, I was a very sickly child. You see, I…I was always sick it seems. No, not really, just my memory I think. You remember the bad things more than the good things sometimes, right?
Anyway, Puneet says, “a couple of the really little kids have croup” (croup). “Croup” is a more serious illness that makes it difficult for young children to breathe and makes them cough a lot. Puneet says, “I wish there were a way to immunize all of them from every illness and disease out there.” “To immunize” (immunize) means to protect someone from getting a disease by either giving them a shot of a drug or having them swallow something that helps their body fight against those diseases if they are exposed to them – if they come in contact with them. Immunizations are very important for childhood health. Unfortunately, for a variety of reasons, there are still many parents who do not immunize their children. That’s dangerous to their children; it’s dangerous to other children, but we won’t talk about that here.
Rebecca says, “Are you sure you’re working in a daycare center?” Puneet says, “Yeah, why?” Rebecca says, “Because it just sounds like you’re working for the Center for Disease Control.” The Center for Disease Control is a U.S. government organization or agency whose job it is to investigate diseases and educate people how to prevent them. It’s located in Atlanta, Georgia, and most people know it simply by the initials, the CDC. Rebecca says, “Tomorrow, I suggest wearing a gas mask to work.” A “gas mask” (mask) is something that you wear over your mouth and nose, sometimes your eyes, to allow you to breathe even though you have been exposed to dangerous chemicals in the air. In World War I, when both sides in the war in Europe used gas to try to kill or hurt the other side, many of the soldiers would have gas masks to protect themselves so they could breathe without getting sick from the poisonous gas. Of course, Rebecca is making something of a joke here, saying that the place – the daycare center where Puneet works is so dangerous maybe he should wear a gas mask to work tomorrow.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Rebecca: You look exhausted! Another tough day at the daycare center?
Puneet: Yeah, it was. This is a record year for the kids getting sick. The chicken pox is going around. Last year, it was the measles. The year before that, it was the mumps. This year, it’s the chicken pox.
Rebecca: You sent the kids home, right?
Puneet: Yeah, but today, a couple of the kids looked like they have pink eye, and I had to call their parents to let them know.
Rebecca: What happened to simple nosebleeds and earaches?
Puneet: Oh, we have kids with those, too, but it’s the contagious diseases that really take its toll. I’m not sure, but I think one of the little kids has strep throat, and a couple of the really little kids have croup. I wish there were a way to immunize all of them from every illness and disease out there.
Rebecca: Are you sure you’re working in a daycare center?
Puneet: Yeah, why?
Rebecca: Because it just sounds like you’re working at the Center for Disease Control. Tomorrow, I suggest wearing a gas mask to work.
[end of dialogue]
It’s been a record year for wonderful scripts here at ESL Podcast. That’s thanks to the wonderful work by our own Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
daycare center – a facility or business that takes care of young children while their parents are working somewhere else
* Most daycare centers ask parents to leave an extra set of clothing, just in case the child gets very dirty during the day.
record year – the year with the highest level or amount of something; a year with more of something than ever before
* The years 2009 and 2011 are record years for heat waves in many states.
chicken pox – varicella; an infection that is shared easily among children and also among some adults, causing fever, tiredness, and many small, itchy red marks on the skin
* Chicken pox is very uncomfortable, but it isn’t life-threatening for most children.
to go around – for many people to suffer from a disease in a certain area during a certain period of time, because the disease is easily passed from one person to another
* The flu has been going around at work lately.
measles – rubeola; a viral disease that causes a fever, coughing, runny nose, red eyes, and many red spots on the skin
* The boy was covered in red spots, but he wasn’t scratching them, so the doctors thought he might have the measles.
mumps – a viral disease that causes painful “swelling” (growth; increase in size) in the “salivary glands” (parts of the body that produce liquid inside the mouth) near the ears
* When she had the mumps, the sides of her neck swelled so much that she couldn’t really move her head.
pink eye – conjunctivitis; a bacterial or viral infection that causes the white part of the eye to become pink or red, often with clear, yellow or green liquid coming out of the eye
* You can avoid pink eye by always washing your hands before touching your eye area.
nosebleed – when blood comes out of a person’s nose, sometimes for no apparent reason, usually for only a few minutes
* When Randall was hit in the face with a baseball, it caused a nosebleed.
earache – pain inside one’s ear caused by an infection
* Do swimmers get earaches more often than non-swimmers?
contagious – a disease that is easily passed from one person to another, perhaps by coughing or sneezing, or by kissing or sharing food or drink
* The nurse told the students that washing their hands with soap and water after using the bathroom and before eating is a very good way to protect themselves from contagious diseases.
disease – illness; sickness, especially caused by a bacteria or virus
* Did you read about yellow fever and other common diseases before you decided to travel to that part of the world?
to take its toll – to have a negative impact on someone or something; for the bad effect of something to be noticed
* Years of smoking and sunbathing have taken its toll on Helena’s skin.
strep throat – a painful bacterial infection that makes one’s throat feel scratchy
* Strep throat is much more painful than a regular sore throat.
croup – an illness that makes it very hard for young children to breathe and makes them cough a lot
* When Kenny has croup, his coughing sounded a lot like a dog barking.
to immunize – to protect someone from getting a disease by giving them a shot or having them swallow a liquid that contains a small amount of the virus or bacteria and makes the body fight against it
* All children must be immunized against polio before they can enter kindergarten.
Center for Disease Control – a U.S. government agency that protects public health by educating people about health and diseases and by promoting programs to prevent and fight against diseases
* What is the Center for Disease Control doing about the growing number of Americans who are overweight or obese?
gas mask – a device worn over one’s mouth and nose, and sometimes eyes, to allow one to breathe without being exposed to dangerous chemicals in the air
* Yes, changing a dirty diaper can be a smelly job, but I don’t think you really need a gas mask.
Comprehension Questions
1. Which of these ailments are not contagious?
a) Mumps.
b) Pink eye.
c) Nosebleeds.
2. Which of these conditions causes coughing?
a) Chicken pox.
b) Earaches.
c) Croup.
Answers at bottom.
What Else Does It Mean?
record
The phrase “record year,” in this podcast, means the year with the highest level or amount of something: “Last year was a record year for accidents in our company, and it’s our job to find out why.” The phrase “in record time” means very quickly: “Blake finished his work in record time and went home early to watch the game on TV.” The phrase “for the record” is used to give emphasis to what one is saying so that other people will pay attention and remember later: “For the record, I think this is a very bad idea.” Finally, the phrase “off the record” is used when one is going to say something that should not be repeated, especially in the media: “Off the record, Janice is a strong supporter of the proposed law, but she would never admit it in public.”
mask
In this podcast, a “gas mask” is a device worn over one’s mouth and nose, and sometimes eyes, to allow one to breathe without being exposed to dangerous chemicals in the air: “All the soldiers have gas masks, just in case the enemy tries to poison them.” A “mask” can also be other objects that are worn over the face to hide it or to participate in a special ceremony: “The thief wore a mask, so nobody could describe what he looked like.” Or, “Are you going to wear a mask with your Halloween costume?” A “face mask” or a “facial mask” is a thick cream put on one’s face and allowed to dry before being washed off in order to improve one’s skin: “This face mask is supposed to treat acne.”
Culture Note
Immunizations Required by Schools
Most schools won’t allow children to “attend” (go to classes) unless their “shots” (immunizations) are “up to date” (having everything that is required). The United States does not have a “federal” (national) law on immunizations, but each state does require certain vaccinations for students in “public” (operated by the government; not private) schools. Parents have to “present” (show) vaccination “records” (written documents) signed by the children’s “pediatrician” (a doctor who specializes in treating children) before their children can attend classes.
The Center for Disease Control has an online “database” (collection of electronic information) that shows the “school entry requirements” (what must be done before one is allowed to attend school) for each state. Although the laws “vary” (are different) by state, most children in public schools must be immunized against mumps, measles, rubella, diphtheria, “pertussis” (whooping cough), “tetanus” (a deadly disease caused when a bacteria enters the body through a bad cut), and “polio” (a disease that causes “paralysis” (inability to move one’s body)). The rules often “extend to” (cover; affect) private schools and daycare centers, too.
In recent years, many parents have begun to “question” (to have doubts about) the safety of immunizations. Some people believe that certain immunizations cause “autism” (a developmental condition that affects a child’s ability to communicate and interact with other people). They try to “modify” (change) the “standard” (normal; regular) “immunization schedule” (the plan showing at what age each immunization should be given) because they think it will be safer. However, this has resulted in a “resurgence” (increase in strength or number after a period of time when something was weak or few) in some diseases that were “once” (in the past) almost nonexistent in the United States.
Comprehension Answers
1 - c
2 - c