= 0744
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 744: Dealing With a Mistake.
This is English as a Second Language Podcast episode 744. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at eslpod.com and become a member of ESL Podcast. Get a Learning Guide for each of our current episodes. You can also take a look at our ESL Podcast Store, and why not friend us on Facebook, or like us, or something. Facebook.com/eslpod.
This episode is a dialogue between Jenny and her boss about making mistakes. Let’s get started.
[start of dialogue]
Boss: What is going on here?!
Jenny: There was a miscommunication.
Boss: A miscommunication?! There are 16 copiers in this office. Who ordered 16 copiers?
Jenny: No one did. Clearly wires got crossed somewhere. I’ll try to get to the bottom of this, but the copiers will be removed before lunch.
Boss: I can’t even walk to my office with all of these machines in here. How am I supposed to get any work done?
Jenny: I’m looking for the purchase order right now to see if the mistake was on our end or on their end.
Boss: Let me know as soon as you figure it out. I want to know who’s responsible for this.
Jenny: Right, I’ll let you know. No doubt it was just a clerical error. No harm, no foul.
Boss: No harm, no foul?! This screw up has cost me half a day’s productivity. I think that’s plenty of harm done.
Jenny: You’re right, sir. I stand corrected. I’m sure it was just an honest mistake.
Boss: Stop making excuses for the person responsible for this debacle. Jenny, why are you making excuses for the person responsible?
Jenny: You look thirsty. I’ll go get you some coffee right now!
[end of dialogue]
The title of this episode is “Dealing With a Mistake.” “To deal with” means to handle, to take care of, and Jenny and her boss need to deal with a mistake
The boss asks Jenny, somewhat angrily, “What is going on here?!” What is happening here? Jenny says, “There was a miscommunication.” A “miscommunication” is a nice way, a polite way of saying that somehow two people didn’t understand each other. One person thought there was one meaning, the other person thought it meant something else, and so the two of them did not properly communicate.
The boss says, again somewhat angrily, “A miscommunication?! There are 16 copiers in this office. Who ordered 16 copiers?” A “copier” is also called a “photocopier,” many people call it a “Xerox machine.” Xerox is a company that makes photocopiers, or at least they used to. In any case, there’s a problem here. The boss says there are now 16 of these copiers in the office. Jenny says, “No one did. Clearly wires got crossed somewhere.” To say that your “wires got crossed” is an old expression meaning there was some sort of mistake, but it was due to some misunderstanding – some miscommunication, and no one is really at fault. That’s the idea; no one is really to blame. This probably comes from the old days when telephone lines would get connected accidentally to each other perhaps, I don’t know, and you would hear someone else’s communication. Well here, the wires got crossed and they did not communicate properly.
Jenny says, “I’ll try to get to the bottom of this, but the copiers will be removed before lunch.” She’s going to get rid of or remove the copying machines before lunchtime. She’s also going to get to the bottom of this. That expression, “to get to the bottom of (something),” means to research and investigate something to find the real reason, the real explanation. When you find out about a problem and it seems complicated, and you don’t know the reason for the problem you might use this expression. “I’m going to get to the bottom of this issue, why my car wasn’t finished on time.” I’m going to talk to the mechanic, I’m going to talk to the mechanic’s boss, and so forth. I’m going to research – investigate – till I find an answer.
The boss says, “I can’t even walk to my office with all of these machines in here. How am I supposed to get any work done?” You see, Jenny is trying to make her boss happy, but the boss keeps talking about the problem. If he stopped talking, maybe he would get some work done! Right Jenny? Am I right, huh? Exactly.
Anyway, Jenny says, “I’m looking for the purchase order right now to see if the mistake was on our end or on their end.” A “purchase order” is a document used in businesses that are buying something from another business, and they say, well, here’s our order, here’s what we want, and a purchase order is considered official approval. It’s almost like a contract that says we will pay you this amount of money if you give us these things. The person who sells to a company is called a “vendor.” Usually, the purchase order has a number on it, and that’s how they keep track of it, that’s how they know which order it was. Jenny says that she’s going to look at the purchase order for the copiers to see if the mistake was on our end. “On our end” means if it was our responsibility, if it was something that the company did, instead of “on their end,” which would be the seller or the vendor; it was their mistake.
The boss says, “Let me know as soon as you figure it out (that is, as soon as you understand and solve this problem). I want to know who’s responsible for this.” “Who’s responsible” means who is the person who was in charge, and therefore if something goes wrong has to take the blame. That is, has to accept the responsibility: “Yes, it was my fault.” For example in a marriage, it’s always the husband who is responsible for any problems or any mistakes. And if you understand that, gentlemen, your life will be much easier!
Well, Jenny is trying to understand who’s responsible for this error. She says, “Right, I’ll let you know. No doubt it was just a clerical error.” “Clerical” refers to doing paperwork, adding numbers, typing; these are all considered clerical tasks. A “clerical error” means it’s an unimportant error caused by someone who wasn’t paying attention. They didn’t mean to make a mistake, it was just like a small accident. That’s why Jenny says, “No harm, no foul.” This expression is used when we recognize that something bad has happened, but it isn’t very serious. For example you’re driving, and you stop at a stop sign, and a car behind you bumps you – hits you very lightly. You get out, you see that he did hit you, but there doesn’t appear to be any problem with your car; there’s no damage. You might say, “Well, okay. No harm, no foul.” Yes, you hit me, but there isn’t any serious damage and therefore it’s no big deal.
The boss doesn’t like this attitude by Jenny. He says, “No harm, no foul?! This screw up has cost me half a day’s productivity.” A “screw up” is a noun; it can also be a verb, “to screw up.” As a noun, it means a bad mistake. As a verb, it means to make a bad mistake, something that has consequences; that is, something that does cause some damage – some problems. The problem here, the boss says, is that it has cost him a half a day’s productivity. “Productivity” is the amount of work that you can complete in a certain period of time, and it’s used generally here to mean getting a lot of things done. By the way, I should mention the word “screw” has a number of different meanings in English, not all of which are covered in our Learning Guide for this episode. The boss says, “I think that’s plenty of harm done,” meaning yes, there was harm because of this mistake.
Jenny says, “You’re right, sir.” Notice she calls him “sir.” He’s angry; she’s trying to show respect to him. She says, “I stand corrected.” This is a common expression. “I stand corrected” means that you recognize that what you said was wrong and that the other person is right. So that husband says to the wife, “Honey, my dear. I think we need to go to my brother’s house tonight,” and the wife says, “Oh, no. I told you I’m not going. Remember?” and the husband, who of course doesn’t remember, says, “Oh, yes. I remember. I stand corrected.” You see how that works? Okay, good. Well, that’s how it works with Jenny and her boss. She says, “I’m sure it was just an honest mistake.” An “honest mistake” is an error that was made by accident. It wasn’t someone trying to cause problems, it was just one of those things that happened by accident.
The boss says, “Stop making excuses for the person responsible for this debacle.” “To make excuses” means to give a reason or an explanation for why something happened, usually because you want to avoid the other person getting angry or you don’t want to be punished yourself. “To make excuses” is to say, “Well, okay. Yes, I made a mistake, but the reason was because my friend told me something that wasn’t true, and then I talked to my other friend, and she said…” and so forth. You’re trying to give reasons why you made your mistake to make you seem less guilty. Well, that’s what the boss does not want Jenny to do. She is making excuses, he says, for this debacle. “Debacle” (debacle) is a huge failure, a serious problem caused by some big mistake. Then the boss says, “Jenny, why are you making excuses for the person responsible?” Jenny says, trying to change the subject – trying to get the boss to think about something else says, “You look thirsty. I’ll go get you some coffee right now!” This is something that an employee might do for their boss to try to make the boss happy. Of course, we suspect that Jenny made the mistake, and that’s why she’s trying to, we would use the expression, “play it down,” that is, not make a big deal of it, say that it is no big deal, it wasn’t important, and so forth.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Boss: What is going on here?!
Jenny: There was a miscommunication.
Boss: A miscommunication?! There are 16 copiers in this office. Who ordered 16 copiers?
Jenny: No one did. Clearly wires got crossed somewhere. I’ll try to get to the bottom of this, but the copiers will be removed before lunch.
Boss: I can’t even walk to my office with all of these machines in here. How am I supposed to get any work done?
Jenny: I’m looking for the purchase order right now to see if the mistake was on our end or on their end.
Boss: Let me know as soon as you figure it out. I want to know who’s responsible for this.
Jenny: Right, I’ll let you know. No doubt it was just a clerical error. No harm, no foul.
Boss: No harm, no foul?! This screw up has cost me half a day’s productivity. I think that’s plenty of harm done.
Jenny: You’re right, sir. I stand corrected. I’m sure it was just an honest mistake.
Boss: Stop making excuses for the person responsible for this debacle. Jenny, why are you making excuses for the person responsible?
Jenny: You look thirsty. I’ll go get you some coffee right now!
[end of dialogue]
The person responsible for the scripts for this episode is the one and only Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
miscommunication – something that was said or written to mean one thing, but understood to mean something else; an instance of unsuccessful communication
* Craig thought we were meeting at 7:00, but nobody else showed up until 9:00. He was upset, but it was just a simple miscommunication.
copier – a copy machine; a machine that makes copies, reproducing an image on another piece of paper
* Chantrelle is using the copier to make copies of the homework assignment for all her students.
wires got crossed – a mistake that happened due to a misunderstanding or miscommunication
* Phyong asked for a small cup of soup, but somehow the wires got crossed and her waiter brought her a small cup of coffee.
to get to the bottom of – to research or investigate something to find the true explanation or reason why something happened
* The police officer swore he wouldn’t rest until he got to the bottom of the mysterious murder.
purchase order – an official document that a company gives to a vendor (seller) stating the number, specifications, and price of the items it wants to buy
* We can’t buy the new computer until our manager approves and signs the purchase order.
on (one’s) end – one’s responsibility or fault, used to emphasize that it is not the other person’s responsibility or fault; describing what one party is doing versus what another party is doing
* We’re working really hard on our end to meet the terms of the contract, but it seems like the client doesn’t really care.
to figure (something) out – to work hard to understand something; to analyze what happened and/or determine why it happened
* How many hours did it take you to figure out what was wrong with Supin’s computer?
responsible – having responsibility for something; in charge of something and needing to accept the consequences of one’s actions or decisions
* The office kitchen is so dirty! Who’s responsible for cleaning it?
clerical error – an unimportant, careless error caused by an office worker, especially by filling out a form or typing something incorrectly
* Clerical errors in legal contracts can cost the firm thousands of dollars, so please proofread everything carefully.
no harm, no foul – a phrase used to recognize that something bad happened, but indicate that it was not very important because nobody was hurt by it and there were no serious consequences
* Yes, Randall forgot about the meeting, but no harm, no foul. They can just reschedule it for next week.
screw up – a bad mistake with significant consequences; a problem caused by someone’s mistake
* When Shane forgot his girlfriend’s birthday, it was a major screw up and she didn’t talk to him for a week.
productivity – the amount of work that one can complete during a certain period of time, especially when compared to the amount of work other people can do
* Do you think computers have increased people’s productivity?
to stand corrected – to recognize that what another person is saying is correct; to admit that one had been wrong, but now agrees with the other person
* The newspaper originally published the article with a few mistakes, but now the journalist stands corrected.
honest mistake – an error that was made by accident or oversight, not intentionally or on purpose
* I’m so sorry I took your suitcase at the airport, but it was an honest mistake. It looked exactly like mine!
to make excuses – to offer a reason or explanation for why something happened, usually because one wants to avoid punishment or avoid making another person angry
* Wynona gets really angry when her employees make excuses. She respects them a lot more if they just admit they made a mistake and then find a way to fix it.
debacle – a major failure; a serious problem
* The computer conference was a debacle and I’m sure nobody will register to go again next year.
Comprehension Questions
1. What does Jenny mean when she says, “I’ll try to get to the bottom of this”?
a) She’ll try to move the copiers out of the way.
b) She’ll make an angry call to the copier supplier.
c) She’ll try to determine how and why this happened.
2. Why is the boss so angry?
a) Because the company cannot afford to buy 16 copiers.
b) Because he won’t be able to work in his office that morning.
c) Because the same mistake has happened before.
Answers at bottom.
What Else Does It Mean?
on (someone’s) end
The phrase “on (one’s) end,” in this podcast, means one’s responsibility or fault, used to emphasize that it is not the other person’s responsibility or fault, or to describe what one person is doing compared to what another person is doing: “We’ll do everything possible on our end to fix the problem.” The phrase “in the end” is used to describe the final result of something: “It took years to renovate the home, but in the end, they were really pleased with it.” The phrase “to go to the ends of the earth” means to do everything possible: “Reno would go to the ends of the earth to make his daughter happy.” Finally, the phrase “to make ends meet” means to have just enough money to buy what one needs, but no more: “With just one salary, they’re able to make ends meet, but they aren’t able to save.”
to screw up
In this podcast, the phrase “to screw up” means to make a bad mistake with significant consequences: “Opening a new office was a bad decision. We screwed up and the company won’t make any money this year.” The phrase “to screw up (one’s) eyes” means to move the muscles in one’s face so that one’s eyes are mostly closed: “Carolay screwed up her eyes in disgust.” The phrase “to screw (someone) up” means to create emotional problems for another person: “Sheila’s parents divorced when she was just seven years old, and it really screwed her up.” The phrase “screw (someone)” is a very rude phrase shouted in anger when one is very upset: “You threw away my baseball card collection? Screw you!” Finally, the phrase “to screw (someone) out of something” means to cheat someone out of a certain amount of money: “The store screwed us out of $100.”
Culture Note
How Companies Place Orders
Large companies can “place” (make) orders and pay for their purchases in many ways. One of the most common is a “purchase order,” which was described in today’s episode. A purchase order must be signed and approved by a manager before it can be “fulfilled” (the vendor or seller provides the desired items). This allows the manager to control how much of his or her “budget” (the amount of money that can be spent for a particular purpose) is spent.
Some companies have an “open account,” which is like a credit account that the “vendor” (seller) provides to the company. The company’s purchases are “deducted” (subtracted) from the “balance” (amount of money remaining) in the credit account, and “periodically” (at regular intervals of time), the vendor bills the company, requesting payment for the total amount “due” (owed).
Other companies “are billed” (receive bills) by vendors for individual purchases. Each time the company purchases something, the vendor sends an “invoice” (a document stating what was purchased, when, and how much it cost). The company usually has 30 days to pay the invoice, after which it may “incur” (have to pay something extra added to the bill) “late fees” (money that must be paid when the regular bill is not paid on time) and/or “interest” (a percentage increase in the amount due).
The company keeps track of the money it owes as “accounts payable,” where each account represents one vendor. A computerized system allows the company to “pull up” (retrieve and display data) the current balance due on each account and see when those amounts must be paid.
Comprehension Answers
1 - c
2 - b