

= 继承之战 S03 - 07
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''



== 释义



'''

== pure



♪If you search for tenderness ♪

♪It isn't hard to find♪

♪You can have the love You need to live♪

♪But if you look for truthfulness♪

♪You might just as well be blind♪

♪It always seems to be so hard to give♪

♪Honesty is such a lonely word♪

♪Everyone is so untrue♪



Yeah, I think we're good. That's good.

-Yeah? -Yeah.

-Yeah? -Yeah. I mean, yeah.

Pretty good, man.

That means it's funny, right?

I think good.

And then you're gonna do the...

-Your whole, like, thing? -Yeah...

I mean fuckk it, right? Just fucking go nut-nut.

Pure excess, full bore, yeah?

Yeah.

-What? No? -No...Yeah, I think.

No, it's like I've gone anti-fragile.

I can accommodate anything.

If I start second guessing, it collapses.

Right. I think that is right.

This is the full fucking thing. It's gonna be epic.

This is the full fucking thing.

We're good, right? All makes sense?

Oh, yeah, this is great work, Rome.

Well, obviously, the main thing is

the organizational cultural thing.

I think, you know, everyone agrees that GoJo makes sense.

No one needs persuading of that.

Ah, well, kind of regret staying up all night

with my assholes then.

No. It's just about, you know us here who get it

oiling the wheels and making sure there's no friction.

Well, of course. I mean, I would say

we could handle the human stuff without too much issue.

That needn't concern us

that actually comes naturally to some of us.

Which is why I focused

on integration benefits and deal detail.

Great. Yeah. I'm just saying, big picture.

Well, big picture is made from small details so...

Guys, guys, honestly,

it's just nerves. You've done really great work.

Let's go and help your dad make the deal.

Yeah. All right.

-Nice rally cry, Braveheart. -I try.

And you're going tonight? -Ken Fest?

-Yeah.  I wouldn't think so.

If Matsson does, maybe for follow-up?

It's gonna be pretty horrific.

Your brother in a...port-a-potty rolling down a hill.

I might have to go just to see how bad it is.

Brothers.

Oh, fuck you. It's pure rubbernecking.

Okay? What's this?

Maybe Matsson's here early?

Or she's gonna give birth to Dad's baby

while we chant a Satanic mass?

It's like he's having a midlife crisis, aged 80.

It's fine. No, it's not, Rome.

He's fucking an assistant who's 50 years younger than him.

It's not a crisis. That's normal.

It's the opposite of a crisis.

We should all be so fucking lucky.

-Hi-ya. -That's so funny.

-Okay. Champagne? -Yeah.

Did you do it already?

Did you land GoJo already without us, Dad?

We're not celebrating.

Long road ahead.

Lovely long open road. Wind in our hair.

Wind in your hair?

We've had a vibration.

I've been speaking to a contact

with connections at DOJ.  Laurie?

Well, we have a number of friends.

And, the word is, on the down-low that

they've seen everything now

they've reviewed,

and they're happy with how we're engaging

and they're coming to the view that Kendall over-promised.

And perhaps some men were terribly naughty back in the day

but nothing systemic, nothing sanctioned.

It's going to be a number.

Just a number? Nothing custodial.

For anyone. No prison?

Nope, we don't think so.

-Here's to us! -To us!

And to justice!

-To justice. Yeah. -To justice.

I'll remember.

Well, congratulations, Dad. You've done it again.

It's great.

Let's just hope you don't do it again, right?

No. Lessons learned.

And here's to Tom!

Long road ahead. No premature celebrations.

Absolutely. Amen to that!

Top me up, why don't ya?

Take me home, country roads!

I'm just gonna run to the little boy's room.

Okay. Enough. No more mooning.

No more backslapping.

Hello.

Hello?

Hey, scooch over for a little bit, buddy.

Thank you, Greg.

Yes!

Yes! Yes! Yes! Yes!

Yeah, fuck yeah!

What? What?

What is going on? Are you okay?

Apologies, Greg, I may have gotten a little carried away.

But I just popped around to say

that no one is going to jail.

Gerri spoke to the DOJ

and the Waystar Two...-are free.

-Okay. Is it real?

It was good news.

What are we looking at in terms of...

What are the responses looking like?

I think about 80% of your A list is "yeses"

and 15% are "maybes."

Okay. Well, "maybes" are "nos," let's not live in a dream world.

But who's in?

Off the top of my head, it's great.

Dion, Barry, JP, David...  -Nice.

-...Anna, Tom Tory, Jeff, Elon, Lukas,

Jennifer and Emma, "yeses."  Chloe is still a "maybe."

And... and the sibs?

Yeah.

Okay. No. Whatever. Fine.

This is fucking cool, Comfry. Hey, hey, listen

you have a good time, too, yeah? Like everyone.

Servers, fucking, the imagineers, the DJ crew, you know

this is highly egalitarian like

do your job, but fucking get your drink on,

get your buzz on.

There's no boundaries if you're cool.

Mission Control out! Shit is about to pop off.

Party!

It's my birthday! fuck You!

Hey.

There might be a problem with GoJo.

Okay. Where's Matsson?

He's sent Sherpas. He's not coming.

Okay.

It's off.  Tell these kids to fuck off. Meeting cancelled.

Okay. Well, what's the downside, Dad?

You know, meet these guys, could read petulant not to?

-If he wants to send a nobody...

-Well, his CFO-and a whole team of people...

-He's going to this fucking party isn't he?

Where is he? Getting his nails done,

asshole whitened?

I think we might have to court him

a little is the thing. Nah..Nah..

It's bad fucking juju to start like this.

Can we not at least...

-talk to the nobodies and... -No! -No. We have other options.

-Do we though? This could be

our last chance to avoid the legacy media graveyard.

Frank's reached out to Nan about Pierce.

What? Seriously? We're going after Pierce again?

It's exciting.

Okay. That's it. Everyone back to work.

The deal makes sense. It's a great deal

but he won't make the deal because he's an arrogant prick.

Fine. Matsson's an asshole. fucking of course he is.

But do we burn our only parachute because of that?

It's just smart business, Shiv.

I don't wanna pay over the odds. And eventually,

the market will make him make the deal.

Unless someone makes a better offer first.

Yeah, Dad, this is it. We have a scale issue.

Our streaming platform is for shit.

And... we have nothing that looks like growth.

This gets us consequentially into streaming

it gets us into sports betting, it gets us into social media.

We have a little window.

Miss this and we end up being a pilot fish

nibbling leftovers from Bezos's fucking teeth.

Kerry? What was it, that thing you said about Matsson?

Thinks he's a genius.

He's made one good piece of tech. fuck him.

We appreciate your input, Kerry, but "fuck him"

is not good tactics.  -It is good tactics.

Dad, please, if you don't wanna talk to Matsson,

fine but let me.

-Or let me. Or we can both do it.

He's gonna be at the party, right?

You're going?

Can't hurt.

Fine. But don't go in too strong.

This is a black box and I don't want to overpay.

Yeah. Got it. I'm on it.

Yeah, I'll reorganize my diary. I got it.

Since you're going

you might as well give him this in person.

Oh, yeah. Okay.

What do you think? Do you think he'll like it?

No, I just... I feel amazing, you know?

My senses are heightened. The air smells sweeter.

And, you know, it's like I can see the poetry

and all little mundane things.

It's...

I'm gonna get so fucked up.

Okay. Is that okay?

-Yeah, you don't need my permission. -Okay.

Like, how fucked up?

-Hi there. -Hi there.

Tom Wambsgans!

Not going to prison!

Hi. We're asking everyone

to hand in their coats and phones.

Kendall would like his present to be everyone being present.

-Yeah. fuck off. I'm not doing that.

-Yeah, you're gonna have to tase us.

And your coat?

I will remain coated. Thank you as is my right.

So come on. What? What happened?

Ranch stuff.

What, a horse didn't want you to fuck it? What?

-He had a fall. -Don't say "had a fall"

that sounds like I'm 89. No!

Maxim and I actually got some polling results

we shared a Cognac

and then I slipped doing a little Irish jig.

Oh, okay. Ranch stuff.

Got it. A real cowboy.

Oh, my God. This feels disgustingly Kendall.

So where's Tabs? She busy? Yeah.

Again? Or did you kill her?

It's going great, I'll have you know.

It's just a bit boring is all. That's all I'm saying.

Okay. The relationship was fine sexually

and you're loving the intimacy and all?

Yes.  I love the intimacy.

I love people really getting to know me.

Yeah.

Like you're the fucking catch of the day.

You're more fucked up than I am.

Congratulations!

You've just been born into the world of Kendall Roy!

Okay. Immersive theater.

I mean, I could have consulted, but whatever.

Oh, Jesus.

So if we've just been born then...

Okay. So I'm inserting myself

into my mom's vagina now?

-Wow. -Is that what's happening?

Cold and inhospitable, seems to check out.

I am repeatedly entering my own mother.

Is that... That's not right.

This is my mom's cooch, so you know.

And you're implying that it's massive so you might wanna

tighten my mother's vagina.

Hey, Tom Wambsgans, free man, how's it going?

Gregory Hirsch, not going to prison.

Pleased to meet you!

Look at you all gussied up, you slick little fuck.

-Well, thank you. -It looks nice.

Yes. I'm feeling good.

Yeah. Say have you seen, Comfry?

Ken's PR with the hair always kind of

in a messy... Gregory John Hirsch,

you got a crush?

-Oh, my God. -What?

She seems like a nice person.

Well, I mean, she's way out of your league, man.

I mean, it's like a haunted scarecrow asking out Jackie Onassis.

-It's a suicide mission.

Really. -Oh, yeah. -Sure... Tom.

-No...This is not a razz.

Greg, she's a goddess and you're a...

you're a nine-foot Cro-Magnon man.

I mean, you shouldn't even be really thinking about her.

You're gonna put her in a tough spot.

Look, I'm not unaware of the discrepancy

in terms of our physical circumstances. It's a chasm.

Well, I have an initial approach which is...

"You're like a fascinating book

I'd like to crack open."

Okay. Well, how'd... How'd you get Shiv?

She's out of your league.

Oh! Testy, Greg! -Well?

-Well, Greg, I'll tell you. I got a dick the size of a Red Sequoia

and I fuck like a bullet train. Okay? Satisfied?

Prove it.  What?

Okay, so where's Matsson?

He's probably standing in a corner somewhere

monitoring his biometrics from his watch.

Should we just say hi to Ken really fast?

-Just to get out of the way? -Yeah.

-Oh, hey, hey, Berry.

-Hi. -Where's Ken?

-VIP.

Okay.

Today is pretty fucking iconic.

Yeah.

Wait a second.

Who... let you guys in?

This is friends only. Shouldn't it be empty then?

Beat me by one second.

Happy birthday, old man.

Just to say, I'm only here because

I heard this was going to be a five-dimensional catastrophe

and I want to watch you crash and burn.

-Come here. -Oh. Yeah, all right. Hugsy.

Man, it's like you fueled.

Are you sure you're only 40? You look like shit.

What? No card? I'm disappointed

because you normally write me such lovely letters.

Oh, yeah. No, I couldn't find one that said

both "Happy Birthday" and "Get Well Soon".

Well, I'm glad you came.

It says a lot. Yeah, it was a ten-minute drive.

Uh...

Okay. Well, give me a hug before you start weeping.

It's good to see you.

-Hi, Kenny. -Holy shit.

Holy shit. Gang's all here?

-Yeah. -Happy birthday. Thank you. Hey, man, what...

what's this? What happened?

Well, a little overexcited about a political breakthrough, so...

-Okay. -Yeah.

But what... what's with the coat? You're not staying or...

It's a coat. I like it.

So, what do you think?

It's cool. Can I ask you

did you ask for Mommy's permission

for the use of her squatch?

What? From a copyright perspective?

Well, it's just, you know, call me old-fashioned

but I think you should ask before you construct

a giant replica of someone's vagina. No?

Roman, relax. Yes, you can take it home with you.

Okay. So. Go on, tell us. Who's here?

Who isn't? -Your dad.

-Your mom. -Your wife and kids.

-Any real friends.

I mean business folks, yeah. Stewy?

I mean, honestly, we could do with building some bridges.

So, yeah, Lawrence Yee? Lukas Matsson?

Yeah. They're all here. Somewhere.

Hey, I got something to show you. -This way.

-Great. -Hey, Will.

Hey, Nate. -Yeah.

Nate, I'm gonna show these guys around.

Hey, I actually got something from Dad,

and myself, I suppose.

-What is it?

-Oh, it's...it's your baby teeth and an iTunes gift card.

It's nice. No, it's a... it's a nice thing.

We hope you'll like it.

Okay. Let me show you some shit. Okay.

So I consulted with Gladwell and Harari

and Lovelock and Popcorn and this in here

it's pretty technical

but this is the best we could come up with

on the likely directions of society

so a little dry, but...

...accurate, I would say. Accurate. -President.

Not a bad way to go.

Also, we got people in here picturing me jerking off

so who's the real winner?

Oh, man.

What if, McCartney tweets this?

This is not... I mean, jokes are all very well and...

Come on, man, I'm breaking through.

Ken, I'm not sure that you're aware but Conn is

pulling very close to 1% so...-1%?

Congrats. -Really?

That's four million people

and it's enough to sway the race.

And I am interested to see who comes crawling first

Merkel, begging for me to save democracy

or Soros serenading me from the trees.

You did, however, actually shit your bag.

Yeah, you know why? Because I took you two fucking assholes

on a camping trip because Dad couldn't be bothered.

That's why!  -Okay...

-And I ate some bad fucking fish. -Okay...

Hey.  -This is bullshit!

Excuse me, hey, can we... can we take down

the crap sack Connor piece, please?

Conn?

It's coming down. It's a joke, okay?

-Come on, man. Loosen up. -I'm good.

-Okay. -Loose the coat. Yeah.

Okay.

All right, I gotta circulate. We can check in later.

-Yeah... That would be great. -You know, I'd like that.

It's a great night. I'm happy you're here.

fucking best birthday ever.

Okay. Later.

Hey...

Hey. Oh, I think there's a line at the treehouse

actually, can you fix, please? Thank you.

-What's up? -Hey. I'm glad I ran into you.

Yeah, me too.

Right, because I might have to brief the press against you.

Oh. The... the whole press?

Yeah. Just Kendall's really going balls-to-the-wall

and, you know, you're on the other team.

But I'm gonna try to keep it targeted rather than terminal.

Thank you kindly, ma'am.

That's very kind of you.

How can I possibly repay you?

-Hey, Comf. -You are a very fair maiden for...

for such activities, for such a kind...

a very evenhanded maiden.

You good?

Yeah.

Yeah. So...Dad sent me something for my birthday.

Okay?

It's a little Trojan mind fuck.

He's trying to slip a maggot in the candy apple.

He's offering to buy me out of my share in the company.

Okay. Wow. Like what is that?

In terms of a number?

Two bill. But, it's a mind game. He's just...

he's worried I'm not gonna let him keep on living rent free up here.

-And? -And fuck him.

Right? Maybe I refuse to engage.

Mind game that, motherfucker.

Yeah. That's great. But...

maybe you do take it.

Maybe, I don't know. Yeah, maybe...

maybe I buy you

a diamond the size of the Ritz-Carlton

and a few illustrious newspapers.

The Globe and Mail, the LA Times

I print a front page of

my dad eating dog dick every day for a year.

And we're living in Marrakesh and I'm fucking you

and smoking hash and learning how to turn a lathe?

All good.

But do we know where Lukas Matsson is right now?

Shiv and Roman have been asking staff for Matsson's location

and inquiring discreetly about a private meeting space.

Is that okay?

Okay.

Okay. Can the party team

get eyes on Matsson and ask him to meet me in the treehouse?

Sure.

Can you find Lukas Matsson and tell...

Hey, I have a location.

-Oh, great. Let's go! -Yeah.

-But don't fuck this, yeah? -Oh, come on.

-Easy. No. -Please, where are we going?

Upstairs.

What the fuck?  -Yeah. I don't know.

I think a 40-year-old man who rebuilds

his childhood treehouse should immediately

go on the sex offender registry.

Hey.

Are you letting me in or what's the deal?

-Do you have a rainbow band? -Yes, I'm... I'm...

I'm a walking rainbow band.

There he is.  -Oh, hey.

-Hey.  Okay.

-This guy's not letting us in.

-You done downstairs? Yeah. We are done.

Hey, Ken may we please step inside your mental disorder?

-Good one. -Thanks.

-Okay. -Sorry. -So?

What? -That's not possible.

Okay. Why?

Yeah, well, because the thing is

the treehouse is cool and you're not cool.

Oh, wow, yes. The coolest grown-man's treehouse

I've seen in quite a while.

Okay. Okay.

No, seriously, guys, just come over...

come over here for a second. -Okay. -Let's go over here.

Just one second.

Sorry, but, like, so joking aside...

Great jokes.

There is actually a real issue here

and I need to be discreet

because there's a lot of celebrities around

and if you guys were in the treehouse it kinda...

kinda wouldn't feel like the treehouse, you know?

You're a Nazi lover.

And you're a Nazi lover.

And I'm a defender of liberal democracy.

-Okay. -And this here

is made from George Washington's cherry tree, so...

The fuck?

Are you actually not gonna let us in?

Or are you just gonna bullshit us a little bit

before you let us in?  -To see Matsson?

That's why you're here. You're trying to push a deal here.

-So? -Who fucking gives a shit?

Like what's the difference? I just wanna talk to him.

High-quality personal conduct.

Really top rank.

What's the difference? I wanna talk to him. So what?

Yeah. And you know what happens if we do talk to him

either we strike out and nothing.

Or we succeed, Waystar benefits and your net worth goes up

-by several hundred million dollars. -You're welcome.

-Right. -Yeah.

But I have to weigh that against the consideration

that "no losers are allowed."

Okay. I'm going in. It's fine. This is stupid.

-This is dumb. -Hey, hey,

look at him! -Hey... -Oh, my God.

Did you see that? I just got moved. -All right.

Oh, my God, bro! no...no...

-What? What is this?  -Bro, bro. Calm down.

Are you actually gonna... What...stop me?

You're getting worked up ...about a treehouse?  -Yeah.

-You know how ridiculous that is?

-Hey, come on in. Wristband him.

Yeah, wristband this guy. What's his name?

What is his name? Who is he? -No idea.

-Good. So good. -See these two?

-Don't let these two in, okay?

-Yeah. -This is my treehouse.

You shouldn't be anywhere near here!

-What is happening?

-Hey, thanks for the offer, Rome.

Really cool. Great head-fuck from you and Dad, thanks.

Unbelievable. Unbelievable.

What's he talking about? What offer?

Oh, God. That's nothing.

What is it? It's... No, it's a

it's a little move to ease him out of the holding company.

You and Dad?

Well, he can only sell to family, right

and, yeah, I think Dad put my name on there.

It's housekeeping.  Oh, I think?

It's a name on a piece of paper, Shiv.

-It's nothing. -Okay.

So can I be the name on the piece of paper?

I can't even do anything with it, it's musical chairs.

I'm sorry. Just, historically,

who owns the fucking company has been of some interest?

Dad and I handled it.

What, you wanna figure out the financing?

-"Dad and I handled it"? -So... Yeah.

Wow. Oh, that's cute. Yeah, I love that. It's great.

it's just fucking great. fuck you. fuck this.

There he is.

Lukas Matsson.

The Odin of coding.

My man, my myth, my fucking monolith.

-What's up, bro? -How are you?

You having a good time?

Do I look like I'm having a good time?

-No, you do not. -I am not.

Still haven't figured out the socials, huh?

Dude, you should get your Algo Guy to fix your code.

Listen, heads up,

my siblings, they're looking for you now.

Well, maybe I need to find an even more exclusive area then

-like a crawl space or something.

-Yeah. Maybe.

They're like emissaries from the Grand Old Duke of Old.

Dad wants to buy you so he sent his winged dildos to schmooze.

I shouldn't say anything.

Even the look on my face is commercially sensitive.

But it makes no sense, correct?

Amtrak buys Tesla.

I mean, if anything, you should buy him.

You think?

Well, I really appreciate your impartial read.

-Yeah. -Rava wants to say hi.

Sure.

-Not right now. When I'm ready.

-Okay.

Listen, you should stay up here, okay?

So you don't get networked to fuck.

You need anything? What can I get you?

Privacy, pussy, pasta.

Done. Reece can help you out. Like pussy, coke, wristwatches,

fucking garganelli he's like a one-man dark web.

Yo, Reece, Reece, customer for your candy store, man.

He's not a good guy. Enjoy.

Yeah, thanks.

Hey. they said you were looking for me?

-Hey. Yeah. Happy birthday. -Thank you.

I...I just wanted to say hi before, you know,

everyone's too high.

Right.

We... we, might go soon, so...

Well, you can't go. No, no. I'm doing

a whole thing.

And we got the Tiny Wu Tang Clan.

These kids we found that do Wu Tang covers.

It's better than it sounds. Trust me.

Okay. What? Are you not enjoying it?

Yeah. No, it's a lot of people. It's huge.

Wow. Savage. What you gonna do for yours?

Just Sarah and Orla and some... some pasta alfredo?

Three glasses of Chablis if you're feeling naughty

and lights out by 11?

That actually sounds really nice to me.

-Right.

-But, listen Gary, you know Gary.

-Yeah. I know Gary. -Okay.

Nice little poseable action figure.

Does he have any genitals? -Oh, yes, yes.

He does. -Yes.

Gary has an early start, so...

Okay. Gary's gotta be fresh for the big meet.

Okay. Thank you. Happy birthday.

Did you get the kids' present?

They've... they've made something for you.

-What? No. -Yeah. -They made me something? -Yeah.

No, I didn't... that didn't get to me. What... when?

When you arrived? -Who did you give it to?

-We... yeah. We... I don't know.

We left it with one of the people.

They said they would give it to you, but...

-Fine. Okay. No, I'll find it. -Yeah.

I'm gonna find it because it'll be logged.

What did it... what did it look like?

Like a present.

-It had... -Like a present... It had rabbit wrapping paper.

All right. Got it.

Fine.

Thanks for coming.  Yeah.

You know, I might be getting out from the firm, finally.

So we'll... we should... we'll talk more.

It's great, actually, because maybe, you know they'll stop

sending their goons to the park

to talk to the nanny about

how often you lose your temper with the kids.

Sorry. Obviously, that's not cool.

I'll handle it. -I'm sorry.

-I'm sorry, I didn't mean...

-on your birthday.

-You wanna burst my...-burst my birthday bubble?

-I didn't.  -Well, good job.

-Okay. Okay. Rabbits, rabbit paper.

-Rabbits. -Got it.

Give my love to Kevin.

Gary.

Why didn't that get to me? Can we trace that gift, please?

-Priority one. -Yes. Absolutely.

Hey, cool shoes, man. Orthopedics?

Are they playing from the approved playlist in the main room?

Because my... my thing was all bangers all the time.

Yeah? All bangers all the time.

-I think so. -Yeah?

They're stopping. Let's read the playlist.

Listen, this is nothing. It's nothing

but can we get Connor to lose his coat?

-Sure. -Yeah, it's nothing.

He's souring the vibe.

And he's making everyone feel cold. -It's not cold, is it?

-No. It's at a good level.

Exactly. So let's encourage him to remove his coat if he wants,

loosen this thing up.

Look, it just...

it just feels like an asshole's birthday party.

And my thing from the very first meeting

was that it shouldn't feel like an asshole's birthday party.

Yeah.

-Hey, Ken. -Hey, Greg! The snitch bitch.

You're... yeah. Well... I've had too much.

Can I have one moment with you?

I'm about to do my set, so...

Oh, yeah. Yeah, let's ride.

Yeah, I was wondering about something because,

I was just about to ask Comfry out

and then she said this slightly worrying thing about

how she might have to do, like, a press brief.

You were gonna ask Comfry out? Comfry, my employee Comfry?

Yeah. But is that right?

I mean...are you... Do you have to spin against me?

Because I feel like things are kind of slowing down

in that regard, right?

No. And she's out of your league, bro.

Well, yeah, I... I don't see it that way.

What if I wanna ask her out?

Inappropriate. But no.

It's best you don't, okay?

Too complicated. She works for me.

Clean lines. Church and State, okay?

Okay. I mean, it doesn't...I don't think it really matters

because... -things are... -Well, I said no, Greg.

-Sorry. -I said no.

Jesus, dude.  Duh?

You're like the world's biggest fucking parasite.

You're a human tapeworm.

Maybe stop feeding on your own fucking family

and try sucking some blood elsewhere. Yeah?

What?

I'm kidding.  Okay.

Or am I? I have...

Are you kidding? I...

I'm not kidding. Am I or am I?

What's up?

fucking asshole, man.

Look at their faces. So fucking dour.

It's a festivity,

people are supposed to be festive.

It's fucking bullshit.

Roman and Dad necking in the catbird seat.

Did you know anything about this buyout thing?

Why is no one happy? What... what is this?

Babe, you're harshing your own mellow, just calm down.

I mean, that is... some substantial rigging.

What do you think that cost? I don't know, baby.

Hi, Connor. I'd like to offer you a

complimentary cashmere sweater.

We're handing them out to prestige guests.

I have my coat. I'm fine.

Well, the coat check was supposed to take that,

but I'd be happy to.

Respectfully, I don't trust those things.

I lost a Norwegian Wool in a fusion restaurant in Vancouver.

Kendall would really appreciate it

if you took the sweater.  -What?

-Hey, my partner is cold

and he'd like to keep his fucking coat on, okay?

And he's running to be the next President

of the United States of America

so maybe you should show him some fucking respect, okay?

She would not fuck off.

Yeah, she did.

Hi, I had to kill a man for it,

but step aside, hombre, let me in.

I'm sorry, sir. I really can't. He said you're not coming in

-Yeah. He was joking. That's my brother, okay?

You can Google it. ..  Sir,

Wow, are you touching me?

This man is groping the guests.

You do not have my permission.

You do not have my permission to touch me.

Hey. There you are, fucking hiding from me.

Like a human VPN.

-How you doing? -I'm all right.

I'm just... you know you can fill in the blanks.

No, I hear you. It's fucking life, right?

It's fucking exhausting.

I just wanna find a good pussy and get out, you know.

Mission, side mission. I hear you, man.

I fucking love pussy.   -You see my mom's?

-Yeah.

You seen my mom's?

-Yeah. -It's not... it's not great.

No, sure. I mean, not touching that one.

Question.

My old man got a little bit grumpy this morning

but you weren't trying to humiliate him, right?

I mean, everyone says, I mean, fucking everyone says

last big legacy content library

last fucking super app streaming platform.

We fit, obviously, right?

-People say we fit. -Yeah.

Well, I guess I do have one question though.

Yeah, hit me up.

When will your father die?

When will... when will my father die?

Yeah.

Like, I don't wanna be rude,

but what kind of shape is he in?

We're talking less than a year or it's more like five years?

'Cause if it's five, that's...

it's a long time.

It would be better sooner, wouldn't it? -Right?

-No... I know, like  we're laughing here,

but, you know, that is my dad, so, you know...

-Right. Yeah. -...go easy there, chief!

No, I... I can tell that it's a bit weird for you.

That's okay.

It's just I don't like the idea of a man

hanging over me.  Oh, fuck yeah.

No, I can understand. Who the fuck wants that? Yeah.

The guru guy who's fucking... fucking bullshit, you know?

Okay.  'Cause

it's not my world, media.

-Yeah. -So...

his death would clear space.

With due respect.  Yeah. No...

I know.  I mean, like, we're all obviously

hugely looking forward to my father dying

but there's another shape to this.

How about you never ever have to speak to him?

I mean, you work out of Austin,

London, Stockholm, Geneva, whatever.

Totally separate corporate identities

and, StarGo, we burn, obviously.

-Yes. Yes. Please. -Oh, yeah.

Like burn the codes

and fucking acid bath those servers!  fucking we can do that.

We can do that together. Let's do it.

Absolutely. I mean, GoJo full bore.

I mean, our library, our firepower

our relationships for content.

And like good shit, you know what I mean?

Like not fucking gay moms and wheelchair kids bullshit

like, popular, actual good shit

and on the occasion that you need to send up

a fucking smoke signal from Geneva

then that goes through me.

You won't ever, ever have to deal with him

or see him, or talk to him, or hear... Nothing.

And you know that StarGo truly, truly is a piece of shit, right?

It's a piece of shit. I know.

I like to open it just to see how long it takes

for the landing page to load.

It is a piece of shit. Hey, why don't we...

Why don't we just, like, take a big old piss on our app?

I'm going to open up the app on my phone

and we can stream some piss on our little streaming platform.

-How's that sound? -fuck yeah.

Nineteen, twenty,

twenty-one, twenty-two. Yeah...

So I can't piss near other men

due to we don't know what reason, but please,

go ahead.  -Don't mind if I do.

-Yeah. Enjoy.

So I know GoJo is your baby

and we do not wanna interfere with that at all.

You're the genius.  Damn right I am.

Yup. So bearing that in mind

would you consider meeting with my dad?

Yeah.

And you'd be interested in selling to us maybe?

Yeah, well, if all this is true, then... yeah.

How's Monday? Monday is great.

And if I were to shake your hand right now

could I go tell my dad that I basically just bought GoJo for him?

No.

But you can tell him I'm in the conversation.

fucking A, I'll take it.  Okay. Take this.

Will do.

Are we amazing?

I think I might be the best businessman in America.

Hey, check this out. Still fucking loading.

-You piece of shit. -Shit.

fuck you.

Okay. If you wanna put on the harness

you can tuxedo up and step up onto the footrest

and then we'll strap you in.

You'll have 30 seconds and the rig will fly you up

and into position

you'll have a 3-2-1

and you'll see the green light, okay?

That's the countdown to the intro.

You ready? You ready to crucify Billy Joel?

Yeah.

I'm just kidding. You're gonna be great.

Remember the thing he said about the rig spiraling

so just, like, keep still, yeah? That sounded serious.

Okay. Harness, then mic.

Ready to rock? You wanna get changed?

Yeah, you know what?

I don't think I'm gonna do this.

-You don't wanna do it?

-No, it's...it's bullshit. No.

Because you did say if you don't lean right in

it could come across dumb.

And your speech kind of tees it up with a kind of ironic

"This is the culmination of my life's journey.

To be crucified to save you morons and..."

I'm not doing it. It's...

it's like 15 layers overdetermined master's degree fucking hokum.

Let's just... let's just pull it. I mean, what... What is it?

It's dressed in a tuxedo nailed to a cross,

singing Honesty by Billy Joel?

It doesn't make any fucking sense.

What about the Tiny Wu Tang?

fuck.

I don't know. I don't... you know what? I don't think so.

No? Okay.

Tell 'em they've got it all ahead of them. Yeah.

That's a fucking relief.

Oh, hey.

Hey, Comf.  -How's it going? -Hey. Good.

-Yeah? -Yeah, it's good.

Ken had me try to call Springsteen to rescue the vibe

and then that got countermanded and now I'm working on

a jetpack for him to leave through the retractable ceiling

that takes 48 hours to move, so...

Okay. Yeah.

Yeah, I mean a lot of the ideas are jokes but some aren't.

Very weird. Yes, indeed.

-What?

-No, me... no, nothing.

Yeah... it's stupid but earlier,

before I heard

you were gonna orchestrate a smear campaign against me

I was actually gonna ask you

if you wanted to grab a drink sometime.

Oh, okay.

Yeah, but then...Kendall,

you know, Kendall, he said...

He said what?

He just said maybe not. Clean lines. Church and State.

Wrong time, wrong place. But

maybe

when you're not working for him anymore

and trying to destroy my reputation and,

and such... You know, I've spent a week researching

where to get lunchboxes from the '80s

to serve canapés from?

Like the one he used to take to school

and then he decided that he didn't want lunchboxes

and so now I have all these He-Man lunchboxes in my apartment

and I have to resell them on eBay

and his office wants receipts.

So if you wanna ask me out, then ask me out.

Do you wanna go out sometime? Yes.

Great.

Wow. She's... she's really dancing there.

Very emancipated.

Do you know what she's taken?

I don't think she's taken anything.

Just getting the demons out, I guess.

Hey, you found the gift from my kids?

I don't believe so.

No? Well, okay. That's not good.

Will you give us a moment, please?

They made me something, apparently so I gotta find it.

Hey, Ken, it'll turn up.

Well, it won't turn up if we don't look for it.

-Well, I know that. -Sorry.

I'm sorry. I'm just saying.

Where the fuck is it?

Hey, Ken, take a break.

You want my gift?

Yeah. Yes, I would. Yes, I would love that.

-It's a watch. -Okay. Wow. Yeah. Thanks.

-I'm, like... -Thanks, Nay. ...really bad at presents

-It... I like it, all right. -Just... just give it back.

-No, I like it. -No, it's fine.

Thanks, Nay. Is it...

can I see?

Is it...inscribed or... -No, it's just a stupid watch, okay?

I'll get you something else.

Do you want a blow job?

No, it's just...

I don't wanna be a dick but I have a watch

you know, I have my watch.

-It's a shitty gift, okay?

I'm bad. -No, Nay, listen.

Yeah, I'm just trying to get inside your head and figure out

why you would give me this gift.

Yeah, it's fine.

-It's fine. -Ken?

Hey, Ken, come on.

Ken, come on, seriously, okay? Look...

I'm gonna look for that gift. Hey, stop.

Ken, Jesus. Hey, calm... Stop... stop.

Just chill.

I'm sorry.

It's okay.

This is so pathetic.

I wish I was...

What?

I wish I was home.

Let's go home.

Are you okay?

Yes, I'm okay, Greg. Why do you keep asking if I'm okay?

Well, just... I haven't seen you smile in, like, six hours.

You don't have to smile to be happy, Greg.

I'm enjoying very much thinking about myself

and my own various skills and abilities.

-Shall we try the compliment tunnel?

-Sure. It could be nice.

Why are you so happy?

-Me? -Yeah.

Well, actually, because I...

I have met the most wonderful girl in the world.

You're just fantastic.

Yes, I am. Amazing. Amazing.

I mean, it's possible she's only going out with me

due to, you know, rancor or pique.

-You're so full of grace.

-What's that?  I think he said you're full of grace.

That's a weird thing to say.  You being sarcastic?

He being sarcastic?  -No, I think it's...

-He said fucking full of grace. Full of fucking what? What?

What did you say?  Wait. Tom, easy.

He's just... you're doing the job, right?

And he's had a little cocaine tonight, so I think he's...

Dude, don't say that.

I'm a public figure who could one day run for high office

or lead a Fortune 500. Don't say that.

All right. He's a lovely guy.

You're doing great work.

You're so merry.

Well, yeah, it's just...

I don't know. I'm excited about my date. I like her.

-What can I say? It's exciting. -You're the best.

-Thank you. -fuck off.

You seem much happier than me, Greg.

I feel happy. I guess... it's not a finite pie

-we can both be happy. -Sure.

But it's supposed to be me that's happy and it's you.

How did that happen?

I took the wrong drugs in the wrong order

and I can't get happy.

Well, can't you just be happy you're free?

No, 'cause you've ruined it.

-How have I ruined it? -I don't know. You just have.

-Hey, there she is.

-Hey. What are you up to?  What's going on?

I heard you were speaking.  -Did you get to Matsson?

-Are you okay?

On-lookers reported you having some kind of breakdown.

People were anxious that you maybe swallowed your tongue.

Yeah, I was dancing.

I heard it looked like a cry for help.

The Dance of the Sugar Plum Failure.

fuck you. You spoke to him? -Yup.

-And? Do you mind if I don't say?

Okay... Okay, come on.

All right. Don't worry about it, Shivvy. I'll handle it.

You can go cut a rug.

Rome, seriously, come on. I am being serious.

I will talk to Dad and see if he wants to loop you in.

He often does like to loop you in.

Rome, just... just fucking tell me.

This is important and I might need to finesse.

-Oh, you need to finesse? -Yeah.

Thank you. That's kind.

How would you finesse something that's done?

What? By ruining it?

-No, by making sure you don't... -The thing is

that Lukas and I have, like, a thing

and I don't see how you fit in.

You know what? If you wanna show off to somebody

maybe do it to someone who gives a shit.

You're having a very bad day. I know that.

What, with hearing

that you have to continue to share your apartment with the old meat wardrobe

but, you know,

try to keep your wig on, yeah?

I'm the one in a functioning relationship. Sure you are.

I saw you, you know.  I saw you sipping Dad's champagne

looking like you were sucking a lemon.

I don't drink on work days

-You don't drink on work days. -because I have self-control.

Okay. That's what that is.

Okay. I thought

maybe you were thinking about all the dick

you were gonna ride when he was inside?  Oh, my fucking God.

You know what?

No one likes talking about me fucking guys as much as you do.

Do you know that?

Why is that?  Is that because you're the COO who can't fuck?

Did you think Tom was going to jail?

-Did you? Did you? Did you?  -No, I'm happy he's not going... -to jail.

-Oh, I'm sure you are. You look really happy.

Did you think he was though? Maybe?

He... there was a chance he was going to jail?

Maybe Dad was gonna go to jail?

fuck. Maybe I was gonna go to jail.

And because Kendall's...

that it was all about you.

You thought it was ladies' night

and they were playing your song.  But guess what,

you're wrong.

All the men got together in man club

and we decided, sweetheart, everything's fine, so just...

-We got it. -You know he is......using you

as a messenger boy.  But, as usual,

you're too fucking dumb to see it.

It's difficult. I get it. It's very difficult for you

to have to do the dance for Dad because you just suck at dancing.

You're a piece of shit, you know that?

It turns out he loves it when I do the Daddy dance

but I guess that's because he loves me.

He loves fucking me, and he just doesn't wanna fuck you anymore.

What are you even talking about? You're so gross.

Well, Daddy doesn't love his little carrot top

even when she does her little Daddy dance.

Dad-daddy, dad-daddy dance.  -I fucking hate you, you know?

-Oh, shit. Look at this. It's birthday boy.

Hey, happy birthday, man.  -Enough, yeah?

-Oh, okay. Yeah. Sorry. Good night.

Neither of you should be in here.

Oh, my God, you're right. Someone call the cops!

Intruders have breached the Masturbatorium!

You're both full of shit.

And you came here to fuck me behind my back.

And you're ghouls and you're disgusting.

Sorry. Whoops. Can we get them out?

-Oh, get them out? -Can we get them out, please.

It's a little late for that,

buddy.  I already spoke to Matsson

who hates you, by the way, and laughs at you constantly.

-Just stop.

-Oh, what?  Go easy on birthday boy?

Did you come here to see me at all?

You didn't, did you, Shiv?

Well, look, we haven't been getting along that great lately

so what do you think? Surprised?

GoJo was my idea.

-You stole my idea. -"You stole my idea."

What are you, fucking six?

Dude, you lost. No big deal.

No need to cry about it. You lost.

You like the spying, Shiv? On my daughter,

on your niece? You like that?

Okay. Lay off the drugs, Ken. Not a fucking big deal.

Who gives a shit? -We are spying?

-Yes, of... oh, come on. Of course we are.

It's a fucking party game.   He's in Dad's shit,

so we're up in his   everybody's in his shit.

Don't act like you're fucking clean. Okay. That is disgusting.

It's disgusting? What, you're siding with him now? Traitor?

I'm just saying there's a line, bro.

fucking Sophie and Iverson?

They're kids.

There's a fucking line now? No line for him,

no line for you.  But there's a line for me?

You're a bunch of stuck up cunts

who can't fucking bear to see me win.

-That's it. That's all this is.

You're not a real person.

You know that? You're not a real person.

You're not real.

Come on. Why don't you hit me maybe?

-Come on. -Come on, shitty Jesus.

You know you want to, just fucking hit me. Do it.

"I'm not a real person." fuck you.

All right. I'm sorry.

Have a good birthday, okay, fuckface?

-Hey, what is this? -Oh, shit! Oh, fuck,

are you okay?   -Happy birthday.

-Everybody just take it easy, okay?

Take your coat off.

-Take your fucking coat off. -That's enough.

Take your fucking coat off!

He's such a fucking hater.

You're an asshole.

It's funny. It's funny.

You're gonna laugh at it later.

You're gonna wake up in the middle of the night

and be like, "That was funny."

To the birthday boy.

Hey, you wanna go someplace else?

Like out out now?

No thanks, honey.

I might be up for a while.

Hey, Dad. I nailed him.

I am the only child you'll ever need.

You can kill the others. Love you.

Hey, you can piss off. I'm gonna walk home.

Hey.

I think the party's over, yeah?

Yeah. Just the party.

Let it fizzle.  Come.

