= 1601
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 296.
This is ESL Podcast’s English Café episode 296. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. On it, you can visit our ESL Podcast Store, which has some additional courses in business and daily English. Don’t forget to download also the Learning Guide for this episode. You can get a Learning Guide by becoming a member of ESL Podcast on our website.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking, and then we go back and explain what they said. Today we’re going to talk about texting while driving. And, as always, we’ll answer a few of your questions. Let’s get started.
Our topic on this English Café is texting (texting), specifically texting while driving. “To text,” as a verb, means to use your mobile phone or cell phone to send short, written messages to other people. Normally texting is, of course, a convenient way to communicate with people you know. But some people unfortunately text while they’re driving, which, you would think, most of us would see as an obvious danger, but people do it anyway because, well, some people are stupid. What more can we say?
We’re going to listen to some people talking about the problems associated with texting while driving, if those were not obvious to you already. First we’ll listen to the story of a woman whose daughter was killed while texting and driving. We’ll listen first, and then go back and explain what she said. Let’s listen:
[recording]
The eyewitness report says that for no apparent reason, she lost control of her car, crossed the center median, clipped a bridge, and then flipped across two more lanes of traffic. No parent wants to receive that phone call.
[end of recording]
The woman is being interviewed on the telephone, so it’s a little difficult to hear her. She starts by saying that there was an eyewitness report. An “eyewitness” is someone who sees something happen, or someone has information about something because they have seen it, not because they heard it from another person or read it in the newspaper. Eyewitnesses are not always, of course, reliable. Some people think they see something that, in fact, didn’t happen. But, this was an “eyewitness report,” that is, someone who had told her after the fact, later on.
The woman is describing an eyewitness report of an accident in which her daughter died. According to the eyewitness report, the daughter lost control of her car for no apparent reason. “To lose control of (something)” means to no longer have power or influence over what happens. If you are driving on a road that is icy – that is slippery, you could lose control of the car; you would not be able to direct the car to where you want it to go. In that case, the reason why you lost control is obvious – the road was slippery or icy. In this accident, however, the driver lost control for no apparent reason. Something that is “apparent” (apparent) is something we can see and understand. The phrase “for no apparent reason” is quite common, it’s used to describe things that happen when we don’t know why they happened or what caused them.
The driver apparently lost control of the car and crossed the center median. On a highway or freeway, there’s often a median that separates the two directions of traffic. The “median” is the area that separates these two lanes of traffic. As I say, most freeways have medians that separate the fast-moving traffic on those roads. Sometimes, medians are just grassy areas – areas with grass; sometimes they are made of cement, and are more like walls. For a car “to cross the center median” means that it went into the other side of the freeway, with cars traveling in the opposite direction. Obviously, that would be dangerous and, in fact unhappily, this woman’s daughter was killed because of it.
So the car crossed the center median and then clipped a bridge. To “clip” (clip) in this case means to hit the edge of something at an angle. To say the car “clipped the bridge” means that it didn’t go right into it, it wasn’t “perpendicular” we might say, it hit the bridge at an angle, somewhere between 0 and 90 degrees let’s say, and then flipped across two more lanes of traffic. “To flip” (flip) means in this case to turn over. What was on the bottom is now the top, and the top is now the bottom. We talk about “flipping a coin,” taking a coin and putting it on your finger – your first finger, using your thumb to make the coin flip over. The top becomes the bottom, then the bottom becomes the top, and so forth. It could flip one time, it could flip many times. This car flipped two times, which means it rolled over twice.
The description of the accident ends with the statement “No parent wants to receive that phone call,” meaning the phone call from the police telling her that her daughter had died.
Let’s listen to this quote one more time.
[recording]
The eyewitness report says that for no apparent reason, she lost control of her car, crossed the center median, clipped a bridge, and then flipped across two more lanes of traffic. No parent wants to receive that phone call.
[end of recording]
We’ll now listen to someone explain the three reasons why texting while driving is dangerous. This is someone from the National Organization for Youth Safety. “Youth” here refers to young people; “safety” is keeping them from being hurt or injured. Her name is Sandy. Let’s listen to her describe why texting while driving is a bad idea.
[recording]
The problem with texting behind the wheel is that it includes all three distractions. It is a visual distraction, because many of them still glance down at their phone either to read the text or to grab their phone to see who sent them a text so that they can respond. You also have the manual distraction, which takes their hands off of the wheel so that they can text, as well as the cognitive distraction where they’re taking their mind off of what they’re doing, either reading the text or responding to a friend.
[end of recording]
Sandy says that the problem with texting behind the wheel – “behind the wheel” means while you are driving – is that it includes all three distractions. A “distraction” is something that takes your attention away from something else. For example, you might be listening to this English Café, but then telephone rings or your husband or wife says something to you, and that would distract you from listening to me; it would be a distraction. Of course, what you should do is answer the phone and say, “Excuse me, I’m doing something very important right now. Please call me later.” Or say to your husband or wife, “Excuse me honey, I need to listen to Jeff and the English Café.” Now, this might have other consequences – other results in your relationship, so you need to consider that, too!
Sandy is talking about distractions while driving. She starts by talking about a visual distraction. “Visual” (visual) relates to seeing or the things that we can see. Texting is a visual distraction because we need to use our eyes in order to look at our phone. She says people need to glance down at their phone. “To glance” (glance) means to look at something very quickly. You may glance at a clock or a watch or your cell phone to see what time it is, and then you move your eyes back to what you were looking at before. People glance down at their phone to read their text messages or they grab their phone – they pick up their phone so they can send a text in response.
She says, Sandy does, that texting is also a manual distraction. “Manual” refers to things we do with our hands; comes from the Latin word for hand. For example, a car can have manual steering, meaning that you have to move the wheels of the car back and forth without any help, without any additional technology. Many cars now have what is called “power steering,” where the technology helps you turn the wheel; it’s easier. My first couple of cars had manual steering, and it is much easier with power steering. Of course, the cars are a little more expensive, and, in my case, the cars are a little newer nowadays. We’re talking about my first driving experience, which was, oh, almost 30 years ago. In fact, I think we had horses…yeah. My first car was a horse, so we’re talking a long time ago people!
Anyway, I got distracted. Let’s get back to our Café here. So, cell phones are a manual distraction; they cause us to have to take our hands off the steering wheel, which is the round wheel we use to put the car in the direction we want it to go, turn left or right. She says the manual distraction is that we have to take our hands off the wheel so we can pick up our phone and text.
Finally, she talks about a cognitive distraction. Something that is “cognitive” (cognitive) relates to thinking, or what you are thinking about. Texting is a cognitive distraction, because you have to think about what you are saying. The problem when you do this while driving is that it takes your mind off of what you’re doing. This phrase, “to take your mind off of (something),” means the same as to distract, to change the focus of your attention or concentration. When I’m hungry, I could be sitting at my desk, and if I smell food, that will take my mind off of my work. I will be distracted; I will start thinking about the food instead of my work. When people are texting while driving, that takes their mind off of driving, because they are either reading the text message or even responding to the text message on their phone.
Let’s listen again as Sandra talks about these three distractions.
[recording]
The problem with texting behind the wheel is that it includes all three distractions. It is a visual distraction, because many of them still glance down at their phone either to read the text or to grab their phone to see who sent them a text so that they can respond. You also have the manual distraction, which takes their hands off of the wheel so that they can text, as well as the cognitive distraction where they’re taking their mind off of what they’re doing, either reading the text or responding to a friend.
[end of recording]
I know this has been a happy topic for everyone. I have to say that there is something good about texting. Not texting while driving, that’s dangerous and stupid. But one thing I have noticed is that now when I am walking out in a public place – at the mall, walking down the street, at an airport, at a school or university – I notice that many people now are not talking on their cell phones, they’re texting. So instead of talking out loud and sharing their conversation with you, which you don’t want to hear anyway, now you just see them walking and looking at their phones. Which can also cause problems for them; they could hit the wall, for example, if they’re not paying attention. But I think it’s good for what we might call the “noise pollution problem,” where you have people talking on their cell phones everywhere. You used to, now fewer people are doing that and I think that’s a wonderful thing.
Now let’s answer some of your questions.
Our first question comes from Mairia Cristina (Mairia Cristina). I’m not sure if that’s supposed to be “Maria” and I wrote it down wrong, or if that’s her name. I haven’t seen that spelling before. In any case, she’s from Italy, and she has a question about three words: “ground,” “soil,” and “land.”
“Ground” (ground), as a noun, is the top level of earth, what you walk on. That’s the “ground.” Wherever you walk on our planet, the very top level or layer is called the “ground.” “To go underground” means to dig a hole, put something below the top level. In London, “the underground” is what they call their subway system or metro system; it’s also called “the tube.” “Ground,” then, is the top level of earth.
“Ground” can also refer to an area of land that belongs to a particular business or a large house or a park. Usually we use this word in the plural, we’ll talk about “the grounds.” “The garden on the grounds of the old school are beautiful.” “On the grounds,” on the area of land where there are no buildings. Or, we talk about the “school grounds.” Here it means something a little different; the “school grounds” would be any part of the school and its property, where the school is located.
“Soil” (soil) is the brown or black earth that is good for growing things and is typically found in the top level of the earth. When I say “the earth,” I’m referring to the substance that makes up our planet. Our planet is also called “Earth,” with a capital “E” in English, but here I’m using “earth” with a small “e” as a noun to mean something similar to these words we’re discussing: “ground,” “soil,” and “land.”
“Soil” can also be used as a verb, and it means to make something dirty. “The little baby soiled his new shirt.” Little babies, of course, sometimes do what we say in English, “spit up.” The contents of their stomach comes out and onto their shirt. And then, mom and dad have to give the young one a clean shirt. Well, that’s “to soil” something, to make something dirty, usually clothing.
Finally, “land” (land) can mean the same as “ground,” the top level of earth. “Land” can also be a more general term for a country or a nation. They sometimes call the United States “the land of opportunity,” meaning the country where you have opportunities. I’m not sure if that’s always true, but that’s the saying – that’s the expression. You could also use “land” to talk about an area that’s smaller than a country. The State of Illinois is sometimes called “the Land of Lincoln,” because that’s where Abraham Lincoln lived. Someday it may be called “the Land of Obama,” since President Obama represented the State of Illinois in the U.S. Senate.
Both the words “soil” and “land” are used when we’re talking about growing plants. “Soil” refers to the actual brown stuff or black stuff that you put seeds into, that you grow the plants in. “Land” is a more general term referring to the area where you have your plants, plants such as corn, or tomatoes, or what have you, whatever it is that you are planting, which is also a verb: “to plant.” That’s “soil” and “land.” “Ground” refers more to the surface of the Earth, the part of the Earth where you can walk or sit – or drive your car while texting! That would be more appropriate for the word “ground.”
Yoshio (Yoshio) from Japan wants to know the meaning of a very common phrase in English: “as such.” “As such” can mean a lot of different things. I’m going to give you an example sentence, and then explain how it is used in that sentence. Let’s start with this sentence: “That is an excellent question Yoshio. As such, it deserves a good answer.” “As such” here means in that capacity, because it is an excellent question. Or, in that role, in that particular occupation. For example: “My friend is the manager of a store. As such, he should be paid a manager’s salary.” He should make the money that a manager should make.
Here’s another use of “as such”: “I don’t mind the work as such, but my boss is an awful person.” Not my boss, just an example! Boss, if you’re listening to this, I’m not talking about you. Well here, the expression or the phrase “as such” means in itself, or if we leave out all the other possible considerations. So when I say, “I don’t mind the work as such,” I mean the work itself is okay, it’s these other things that I don’t like.
A third use of “as such” could be as in the sentence: “I just climbed a mountain today (I went up to the top of a mountain), and as such, I am too tired to wash the dishes,” the dishes I used to eat on; I’m too tired. Here, “as such” is used as sort of a general transition phrase, that asks the reader or listener to think back on the ideas that they just mentioned – you as the speaker, I should say, just mentioned. For example, another example: “The patient in the hospital (the sick person) is able to function normally in daily life. As such, she is not mentally ill.” Because they can function or act normally, therefore they’re not ill. “As such” here then kind of works like “therefore,” it takes you from one idea to the next as a logical progression or a conclusion.
Finally, Hamid (Hamid) in Iran wants to know the difference between “pupil” (pupil) and “people” (people). Well, the first question is how we pronounce these two words: “pupil” and “people.” “Pupil,” “people.”
A “pupil” is a student, someone who is learning something. It’s not used that often anymore in modern conversational, at least in American English. Instead of “pupil” you will hear much more commonly “student.” But it’s still used in some places in some schools.
“People” refers to more than one person: “There are thousands of people here.” “People” could also refer to a group of people – of persons – from the same culture or background. In the second case, it can be used with an “s” at the end; you can make it plural even though “people” already seems plural. You could say, “There are many peoples in Africa.” Or, “The peoples of Latin America.” You’re referring to various groups of people who have similar culture or background.
“People” is often used informally in English to talk to a small group or a small crowd of people. Young people, people who are younger than I, sometimes use it this way when they are talking to two or more people – two or more friends. I think one of the reasons they do so is to be funny. It’s a word that teachers often use in schools, especially among high school students. You can’t call them “boys and girls,” even though they really are. They’re too old for that, and so some teachers will say, “All right people, listen to me. Listen up.” Stop talking; stop texting on your cell phones. So that’s another informal use of “people,” to talk a group – a small group of people.
We’d love to hear your question or comment. You can email us at eslpod@eslpod.com.
From Los Angeles, California, I am Jeff McQuillan. Thank you for listening. Come back and listen to us again on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
eyewitness report – information from someone who has seen something happen (not something he or she has only heard about)
* I’ll tell you what I know, but I can’t offer an eyewitness report because I wasn’t actually there when it happened.
to lose control – to no longer have power or influence over what happens, especially while driving
* When Tracie braked quickly to avoid hitting the dog, she lost control of the car and ran into a tree.
apparent – obvious; something that can be seen and understood
* These studies make it very apparent that there is a link between foods with a lot of fat and heart disease.
median – the grassy or cement area that separates two lanes of traffic traveling in opposite directions
* The city planners put a beautiful, grassy median with many trees in the middle of the boulevard.
to clip – to hit the edge of something, often at an angle
* While learning how to parallel park, Shawn accidentally clipped a Mercedes.
to flip – to roll or turn over
* Everyone clapped when the acrobat flipped in the air.
distraction – something that takes one’s attention away from something else
* How can you study with so many distractions? When I study, I have to turn off the TV and the music so that I can study in silence.
visual – related to seeing; related to the things that one sees
* The report would be easier to understand if it included some visual aids, like charts and graphs.
to glance – to look at something very quickly; to look at something very briefly
* Federico normally doesn’t have time to read the newspaper in the morning, but he always glances at the headlines.
manual – done by or with one’s hands
* This job includes a lot of manual date entry, so we need to hire a fast typist.
cognitive – related to thinking or what one thinks about; related to what occurs in one’s mind
* Babies and toddlers have many medical appointments, so that pediatricians can review their cognitive and physical development.
to take (one’s) mind off – to distract; to change the focus of one’s attention or concentration
* Egbert has been really stressed out lately, so we’re taking him to the beach this weekend to try to take his mind off work.
ground – the top level of earth beneath (one’s) feet
* It’s difficult to walk barefoot here because the ground is covered with small, sharp rocks.
soil – the brown earth that is good for growing things and makes up the top part of the earth
* Do we have the right kind of soil for growing vegetables?
land – the top level of earth; area of ground
* They bought a home with three acres of land.
as such – in that role; in that capacity; in itself; a phrase used as a transition phrase that asks someone to think back to the ideas that came before
* Dan is the new treasurer. As such, he’ll keep track of the money we receive and spend.
pupil – a student
* How many pupils are in your classroom?
people – more than one person; a group of people who belong to the same culture
* Hey people, please quiet down and listen! This is important.
What Insiders Know
Common Texting Terms
Most cell phones and other “mobile devices” (small, hand-held electronic devices that connect the to Internet and/or a phone network) have very small “keyboards” (a set of buttons with letters, numbers, and punctuation marks, used for typing), so it can be difficult to type long messages. That is why people use so many “abbreviations” (a short form of a word or phrase) and “symbols” (an image used to mean something else) when texting.
For example, people who text often use a single letter to represent an entire word. “R” means “are,” “U” means “you,” “Y” means “why,” and “B” means “be,” so phrases like this become common:
RUOK? Are you okay?
YRUthere? Why are you there?
Common phrases are “transmitted” (sent) by using only the first letter of each word. For example:
LOL Laughing out loud (used to show something is funny) or lots of laughs
ROTLF Rolling on the floor laughing (used to show something is very funny)
OTL Out to lunch
BRB Be right back
Sometimes these two ideas are used together to create phrases like these:
CYT See you tomorrow
CUL8R See you later
GR8 Great
HRU How are you?
YGTBKM “You’ve got to be kidding me” (used when one is very surprised by or does not believe what another person has said)
Some of these messages look like a foreign language at first, but with a little practice, they become easy to “interpret” (understand) and create.