= 1576
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 271.
This is ESL Podcast’s English Café episode 271. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. On it, you can visit our ESL Podcast Store, which has some additional courses in business and daily English. You can also download the Learning Guide for this episode on our website.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech – a normal speed. We’re going to listen to them and explain what they are talking about. Today we’re going to be talking about Latinos or Hispanics, those that come from primarily Spanish speaking countries or whose parents or grandparents came from those countries and are now living here in the U.S., we’re going to talk about Latinos going to college. As always, we’ll answer a few of your questions as well. Let’s get started.
Our topic on this Café’s Ask an American segment is efforts to help young Latinos or Hispanics get a college education here in the U.S. Compared with other racial and ethnic groups, only a small percentage of Latinos go to college and get a college degree.
We’re going to listen to some people talking about what the organization here in the U.S. called the Hispanic College Fund does in order to help young Latinos go to college, and support them once they are in college. You may ask, well, why is it that Latinos don’t go to college as much as other racial and ethnic groups, or at least compared to whites and Asian Americans in the U.S. The answer is complicated. It is in part due to economic reasons – to poverty, in part due to educational issues.
One thing that can help these students is for them to see other Latinos who have been successful in college. We’re going to listen first to Karen Guzman; she’s an 18-year-old “freshman,” or first-year student in college at the University of Maryland. Maryland is on the eastern coast of the United States, next to Washington D.C., our capital. She’s going to talk about her experience when she attended a “symposium” (symposium), which is a special conference – a special meeting, in this case, one organized by the Hispanic College Fund.
We’ll just listen to her first. Try to understand as much as you can, and then we’ll go back and explain what she said. Let’s listen:
[recording]
I remember that that was the first time I saw so many young Latinos like me say, “I’m here in college and, you know, you can do it, too,” because before then I didn’t have that, I guess, role model to look up to. Everyone I knew was either dropping out or their plans weren’t to go to college, [going into] the military, or something like that.”
[end of recording]
Karen says that attending the symposium was the first time she saw so many young Latinos like herself. Many of them were already college students, and that showed her that she could go to college, too.
She says that before attending the symposium, she didn’t have a role model to look up to. A “role (role) model” (model) is a person whom you admire, who you try to be like. Sometimes a role model can be a famous person. Sometimes it can be a member of our family, our parents for example. It may be a brother; it may be a friend. Well, what Karen found was that the other young Latinos who were there – who were in college became role models for her, people that she looked up to. “To look up to (someone)” means to admire someone, to think that he or she is very good, to want to be like that other person. That’s to look up to.
Karen explains that before attending this meeting, or symposium with other students, she didn’t have a role model, meaning she didn’t know a Latino college student whom she could try to be like. The college students she knew were in fact dropping out of school. To “drop out” is a two-word phrasal verb meaning to stop going to school, to stop studying before you finish. We have, unfortunately, a lot of student who drop out of high school before they finish high school. This is because in many states when you turn 16 – when you become 16 years old you can drop out of school; you are no longer required to go to school. We have a lot of young students, in particular young Latinos, who drop out of high school. That is a problem, especially when everyone around you is dropping out, you don’t have that role model for continuing on with your education.
She says, “Everyone I knew was either dropping out or their plans were not to go to college.” She says that other people she knew wanted, for example, to join the military or to do something else. To join the military would be to join the army or the navy, one of the what we call armed forces in the United States, to work for the government.
Let’s listen to Karen one more time.
[recording]
I remember that that was the first time I saw so many young Latinos like me say, “I’m here in college and, you know, you can do it, too,” because before then I didn’t have that, I guess, role model to look up to. Everyone I knew was either dropping out or their plans weren’t to go to college, [going into] the military, or something like that.”
[end of recording]
Next we’re going to hear from – that is, we’re going to listen to a man named George Cushman. Cushman works with the Hispanic College Fund, and he’s going to talk about why it’s important to encourage Latinos to get college degrees. Let’s listen.
[recording]
In America, there’s many people like me in their 50s and 60s. They’re highly educated. They’re the engineers, the doctors, the lawyers, the health care professionals, the teachers. They’re all hitting the exit doors ‘cause it’s time to retire soon. The largest, fastest-growing student population to follow in our footsteps is Hispanic, but they’re getting degrees at a third of the rate. You can feel the vacuum forming. If we don’t fix that, it’s going to hurt the economy. It’s going to hurt the security of our country.
[end of recording]
He begins by saying that in America there’s many people (he means there are many people) like me in their 50s and 60s. They are highly educated. To be highly educated means, of course, you have a lot of education. They are the engineers, the doctors, the lawyers, the healthcare professionals, the teachers. He says that these people are hitting the exit doors because it’s time to retire soon. “To hit the exit door (or doors)” means to leave typically. “Exit” is the word we use for the doors where you leave a building; it can also be a verb, “to exit,” you exited the room – you left the room. But this expression, “to hit the exit doors,” is not to be taken literally – that is, he doesn’t mean that people are actually getting up and going through a door. He means that people are leaving their jobs – leaving their positions. The reason is that it is time for them to retire, especially when they get into their mid-60s that’s a common thing.
George says that these professionals – the lawyers, the doctors, the engineers – are hitting the exit doors because it’s time for them to “retire,” they’re going to stop working. George says that a lot of today’s professionals are getting ready to retire and they need to be replaced. He says, “The largest, fastest-growing student population to follow in our footsteps is Hispanic.” The fastest growing would be the group that is getting bigger the fastest, the one that is becoming larger and larger. “To follow in (someone’s) footsteps” means to come after someone else, to do what that person was doing. So when here in the U.S. the president leaves office, another person follows in his footsteps; he or she takes over the office of the presidency. To follow in someone’s footsteps means, we could also say, to “succeed” that person, to do what they do after they are finished doing it.
George says that Latinos are the fastest-growing student population to follow in the footsteps of today’s professionals, but unfortunately they’re earning fewer college degrees than other student populations. He says, “they’re getting degrees at a third of the rate.” So whereas other groups, whites and Asian Americans in particular, are getting college educations, the Latino population is not getting as many. In fact, they’re getting only about one third as many. He says, “you can feel the vacuum forming.” A “vacuum” is, in this case, a container – a thing that has no air in it, the air has been taken out of it. In old radios, we used to have things called vacuum tubes. These were electronic parts. There’s no air inside of the tube – inside of the little piece of glass. The idea of a vacuum means that there is nothing there, and so when George says there’s a vacuum forming he means that there aren’t students graduating from college to follow in the footsteps of today’s professionals, at least not among Latino or Hispanic students. This means that we have a lot of jobs that will be available, but there will be no one there qualified and educated enough to work in those jobs from the Latino community. He says finally that if we don’t fix the vacuum – that is, if we don’t prevent the vacuum from forming – it’s going to hurt the economy. He says it’s going to hurt the security of this country also, the “security” being the safety of the country.
Let’s listen to George one more time.
[recording]
In America, there’s many people like me in their 50s and 60s. They’re highly educated. They’re the engineers, the doctors, the lawyers, the health care professionals, the teachers. They’re all hitting the exit doors ‘cause it’s time to retire soon. The largest, fastest-growing student population to follow in our footsteps is Hispanic, but they’re getting degrees at a third of the rate. You can feel the vacuum forming. If we don’t fix that, it’s going to hurt the economy. It’s going to hurt the security of our country.
[end of recording]
The Hispanic College Fund is one of the organizations that helps Latino students get to college and stay in college. We’re going to hear now from Anne Guarnera, she’s going to talk about how this organization helps Latino college students. Let’s listen:
[recording]
Once our students have gone through that, they then have year-round programming through the Hispanic Youth Institute. So that helps us support them as they move along and get closer to actually going to college. Once they’re in college, we have a scholarship program that supports students financially as well as emotionally and just helps them with the process of integrating into their schools.
[end of recording]
She begins by saying, “Once our students have gone through that, then they have year-round programming through the Hispanic Youth Institute.” She begins by saying “once,” but doesn’t mean one time; she means, in this case, after – after our students have “gone through,” meaning participated in the initial phases – the initial stages of the program, then they have “year-round,” meaning throughout the entire year, January through December, year-round programming through the Hispanic Youth Institute. “Programming” here just means activities, things that they do through this other organization called the Hispanic Youth Institute.
She continues by saying, “So that helps us to support them as they move along and get closer to actually going to college.” So even before they are in college, after they go through this symposium, then they participate in these other programs while they are still in high school. This programming helps them move along – move forward and get closer to actually going to college. “Once they’re in college,” again, after they’re in college, she says, “we have a scholarship program that supports students financially as well as emotionally.” A “scholarship” is usually money that you are given to help you go to school. Unlike a loan, a scholarship is a gift. If you get a loan, you have to pay that money back. Scholarships are often given to students with very good grades or students are who are very good in, say, sports or some other activity.
Anne says that the organization’s scholarship program supports students financially, or with money, but also emotionally, with their feelings – with the reactions, the psychological issues that they may confront – they may have in college. The program, then, helps them with the process of integrating into their schools. To “integrate” means to become part of something, to become just like all of the other members of that organization.
Let’s listen to Anne one more time:
[recording]
Once our students have gone through that, they then have year-round programming through the Hispanic Youth Institute. So that helps us support them as they move along and get closer to actually going to college. Once they’re in college, we have a scholarship program that supports students financially as well as emotionally and just helps them with the process of integrating into their schools.
[end of recording]
Finally one more short quote from Karen, the woman who is the college freshman at the University of Maryland that we heard from earlier. She’s going to talk about her experiences at this Hispanic Youth Institute. Let’s listen:
[recording]
It was amazing. We got to go to different companies, talk to different people in different fields and get mentors. And we keep in touch. My mentor still tells me, “Apply to this program,” “Do this,” “How are you doing in your classes?” You know, and they tell me that, and then, I know that someone cares for me, someone who’s not just like “Here I am,” but then they never keep the communication. They’re there constantly.
[end of recording]
Karen speaks very quickly, like a lot of teenagers I guess. Let’s go back and figure out what she said. She starts by saying, “It was amazing (it was great). We got to go (we were able to go) to different companies, talk to different people in different fields (different areas) and get mentors.” A “mentor” (mentor) is a person who helps a student or a young professional develop personally and professionally; they give them advice, they help them. They give them guidance; they say “do this,” maybe “don’t do that.” They can answer questions from the student or the young employee or professional.
Karen says that her mentor and she still keep in touch. “To keep in touch” means to maintain communication, to continue communicating with someone. Sometimes we’ll say to someone, “Keep in touch,” meaning email, call, write visit me; let’s keep communicating with each other. Karen says that her mentor still gives her advice: she tells her which program she should apply to. She says, “Do this,” meaning here’s something you should do. She asks how things are going in her classes – how she’s doing in her classes. Is she successful? Is she having problems? Then Karen says, “You know, and they tell me that, and then, I know that someone cares for me.” Noticed the use of “you know.” It’s common, as you probably know, in English as sort of a filler word, when you’re thinking of something else to say. Karen says that she knows someone cares for her, “someone who is not just like ‘Here I am,’ but then they never keep the communication.” This is a somewhat difficult phrase here, or part of the sentence: “Someone who is not just like ‘Here I am’.” The word “just” is used for emphasis. So she’s saying that this is someone who is not like “Here I am,” that is, someone who says I am here for you but then never continues the communication – does not keep in touch. Instead, she says, the mentors are there “constantly,” continually, all the time, without stopping.
Let’s listen to this quote one more time.
[recording]
It was amazing. We got to go to different companies, talk to different people in different fields and get mentors. And we keep in touch. My mentor still tells me, “Apply to this program,” “Do this,” “How are you doing in your classes?” You know, and they tell me that, and then, I know that someone cares for me, someone who’s not just like “Here I am,” but then they never keep the communication. They’re there constantly.
[end of recording]
That’s the end of our Ask an American segment. Now let’s answer a few of your questions.
Our first question comes from Luciana (Luciana) in Brazil. The question is about the expression, or phrase really, “per se.” “Per (per) se (se)” means a couple of different things. It can mean essentially, by its very nature; we might say “in and of itself.” Let me give a few examples: “The company isn’t against giving employees more money per se, but we’re not sure it will happen this year.” In some ways, it’s sort of an emphasis expression here: the company isn’t opposed or isn’t against more money in of itself. It’s not against that idea, but they’re not sure they can do it this year. So in general, we might say, they’re not against it. We could also say, “I’m not against people putting dresses on their pets to make them look more like people per se, but I do think it’s very strange and silly.” So, I’m not against the idea, but I think it’s a little strange. So, once again, the idea here is essentially or in general.
Another use of “per se,” which you may know is actually a Latin phrase, is not quite, not exactly. For example: “We do not need to cancel our trip per se, but we might want to change it now that it is raining outside.” “Per se” here means not exactly. We don’t have to cancel our trip, that’s not exactly what I mean; what I mean is we might want to change it. Or you could say, “It’s not the cake that bothered my stomach (that made my stomach feel bad, that made me ill) per se, it was eating the cake at two o’clock in the morning.” So the problem was not the cake exactly, it was the time I ate the cake.
“Per se” is a phrase that you will see most often in written English; it’s not used in spoken English very much, except in perhaps very formal circumstances.
Our second question comes from Hesamodin (Hesamodin) in an unknown country. We’ll call it Country B. The question is what does “it pays to be” mean? “It pays (pays) to be” means that there is something good if you are doing this thing, you are likely to have a positive result by doing it. For example: “It pays to get to work early.” “It pays” meaning there are benefits to getting to work early: there are fewer people there, you can show your boss that you are hard working by arriving before he or she arrives. “It pays to plan your trip carefully so that you don’t have any problems with gas, food, and lodging (the places where you’re going to stay – the hotels).” It pays to do that, meaning it will give you a lot of good things – a lot of benefits. We often use this when giving advice to someone: “It pays to buy a good car so you don’t have extra repair expenses later.” You don’t have to fix it every month. You’re giving someone advice.
Sometimes we use it to what we might call gloat (gloat). “To gloat” means to tell other people what a good job you did. “To brag” (brag) means the same thing, to tell other people how smart you are. If someone asks, “How did do get your job? It’s a good job,” you may say, “Well, it pays to work hard and to have a good education.” You are saying that you were very smart to do these things. Generally, people don’t like it when you are gloating, so you probably avoid that use of this expression “it pays to.”
Notice that the verb after “to” is in the infinitive form: “it pays to write,” not “it pays to writing.” Or, “it pays to go,” not “it pays to going.” Also remember that although the verb here is “pay,” it isn’t talking about money necessarily, it might be, but usually just benefits – good things that you get from doing that action.
If you have a comment or a question, you can email us. Our email address is eslpod@eslpod.com. It pays to look on our website first before you email us; we may have already answered your question.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
role model – a person whom one admires and tries to be like
* Do you think professional athletes have an obligation to be role models for children?
to look up to (someone) – to admire someone, thinking that he or she is very good and wanting to be like him or her
* Mulin always looked up to her father, because he was very kind and generous.
to drop out – to stop going to school and stop studying before one has earned a degree
* Studies show that people who drop out of high school earn much less money than people who have their high school diploma.
to hit the exit doors – to leave; to begin to leave
* After the big earthquake, many people hit the exit doors, quitting their jobs and moving away from the city.
to retire – for an older person to stop working
* Most Americans hope to retire when they are 65 years old.
to follow in (one’s) footsteps – to come after someone else, doing what he or she was doing
* Everyone expects James to follow in his grandfather’s footsteps and become a famous author, but he’d much rather become a pilot.
vacuum – a container where all the air has been taken out; a lack of something; a situation without enough of something
* Their home felt like a vacuum after their children grew up and moved away.
scholarship – a financial award; an amount of money that is given to a student to help him or her pay for college and does not have to be paid back, normally given to students who have very good grades or are very good in sports or art.
* Our organization awards 10 scholarships to medical students each year.
to integrate – to become part of something; to make something become part of something else
* Over time, our teachers are integrating the new teaching methods into their curriculum.
mentor – a person who voluntarily helps a student or a young professional develop and grow personally and professionally, providing advice and guidance, especially on how to do well in school or how to succeed in a particular career
* Yorick’s mentor helped him decide which university to attend.
to keep in touch – to maintain communication, or to continue communicating with someone over a long period of time
* Have you kept in touch with any of your friends from high school?
constantly – all the time, without stopping
* We’re constantly trying to improve our customer service.
per se – in and of itself; essentially; intrinsically; by its nature; not quite; not exactly
* There’s nothing wrong with wearing white socks and black shoes per se, but most fashion experts would advise against it.
it pays to (be) – there is a benefit to (being); one is likely to have a positive result by doing/being
* It pays to take the time to do things right the first time. Otherwise, you just waste time redoing things.
What Insiders Know
The Military Campus Recruiting Controversy
“Branches” (parts) of the U.S. “military” (the people and organizations that work to defend the country) often “recruit” students on college campuses, trying to “generate” (create; produce) interest in military “service” (a period of time spent working in the military). Since Americans are not required to serve in the military, recruitment efforts are “critically important” (very important) for military branches. College campuses are a good place for those recruitment efforts, because the military can “reach out to” (connect and interact with) highly-educated young people.
However, some people dislike military campus recruiting. They think it is “inappropriate” (not right) for the military to recruit at an institution that provides “higher education” (education beyond a high school degree). Many organizations have “staged” (organized) protests against military recruitment offices on campuses, but the “controversy” (disagreement) seems most “heated” (with strong feelings) at Berkeley, near the University of California at Berkeley.
The Marine Recruiting Center opened in downtown Berkeley in January 2007. Protests began in September of that year and “haven’t stopped since” (are still continuing). A group called “Code Pink,” an anti-war group, organized the original protest, arguing that military recruiting centers shouldn’t be allowed to open near schools. People “chained themselves to the entrance” (tied themselves to the front door with long, interlocking pieces of metal) so that other people couldn’t go in, and they made a lot of noise that “disrupted” (interrupted or changed normal activities) nearby businesses.
Some people support the protest, but other people think the protest is disrespectful and shows a lack of support for the “troops” (people serving in the military).