= 1605
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 300.
This is English as a Second Language Podcast’s English Café episode 300. Wow, 300! It seems like it was only yesterday when we began. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the still beautiful city of Los Angeles, California.
Visit our website at eslpod.com to download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English.
On this 300th English Café, we’re going to continue our series on American Presidents, talking about the 26th President of the United States, Theodore Roosevelt. We’ll also talk about something called the Folk Tales of Uncle Remus, a series of controversial stories about the American South. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a continuation of our series on American Presidents. This Café will focus on the 26th President of the United States, Theodore Roosevelt, who was president from 1901 to 1909. You may be more familiar with his nickname Teddy; Teddy is a form of the name Theodore, just like Bobby is a form of the name Robert.
Teddy Roosevelt was born in New York City in 1858. He was a sickly child. “Sickly” (sickly) is a child or a person who is very often sick, who has many different illnesses or diseases. It’s not quite as common a term now as it used to be. Roosevelt had spent a lot of time resting in bed, but he was very interested in the study of animals, what we would call “zoology.” He did not go to a formal school; he was what we would now call “home schooled.” He did, however, go on to study at Harvard College, where he began writing an important book on the history of the U.S. Navy during one of America’s early wars, the War of 1812. After Harvard, he entered Columbia Law School, another one of the best universities in the United States, but he dropped out or left law school in order to run for election as a New York State Assemblyman in 1881. The Assembly is the same as the Legislature; it’s a group of elected representatives. In New York if you are elected you are called an Assemblyman or an Assemblywoman. Roosevelt won election in 1881, when he was only 26 years old.
However, Roosevelt became disillusioned by politics. “To become disillusioned” means that you become disappointed by something; you had a certain idea about what it was going to be about – certain expectations, and then when you actually got to that place or had that experience you’re disappointed; it’s not what you thought it was going to be. Roosevelt was disillusioned by politics and decided instead to move to the north central part of the United States, to the state of North Dakota, which is just west of Minnesota, and start a ranch. A “ranch” is a large area of land usually used for horses, cows, that sort of thing.
In 1886, Roosevelt lost a lot of money on his ranch. By the way, some people say “Roosevelt, some people say “Roosevelt”; “Roosevelt” is probably the more popular pronunciation. Anyway, Teddy lost a lot of money on his ranch and he moved back to New York. He tried to become mayor of New York City, but he did not win the election. Then he “campaigned” or helped Benjamin Harrison become president; he went out and tried to get Benjamin Harrison elected President of the United States. Harrison was elected, and Roosevelt was awarded or given a government job. Somewhat ironically, Roosevelt, while he was given this government job, tried to stop what was then called the “spoils system,” which was the practice of thanking voters by giving them government jobs, rather than giving the jobs to the people who were really qualified, who could do the jobs the best. “Spoils” is a general term for what happens when one country defeats another country and they take the best artwork or the money – the riches from one country and they bring it back to their own country. Those are called the “spoils of war.” Well, the “spoils system” was rewarding voters for voting for certain politicians by giving them things like jobs.
In 1895, Roosevelt became president of the Board of New York City Police Commissioners, a government organization responsible for running the police departments. When he was there, he fought against “corruption,” against the practice of criminals paying police officers to do things or not do things.
Finally, President McKinley appointed Roosevelt as Assistant Secretary of the Navy, and while he was doing that – this was in the 1890s – he helped prepare the U.S. Navy for the Spanish-American War, which you may remember began in 1898, at the very end of the 19th century. This was a war with Spain. As soon as war was “declared,” as soon as the country officially said it was at war, Roosevelt “resigned” from the Navy, he quit his Navy job. Instead, he asked for volunteers – soldiers – to form a group of fighters who became known as the Rough Riders. The word “rough” (rough) is the opposite of smooth, but it can also refer to people who perhaps are not very elegant, not very educated. They might be very good at what they do, but they are, what we may say, a little unrefined. They’re rough; they need some more polishing, just like a stone might be rough or polished. Roosevelt was the leader of the Rough Riders in the Spanish-American War; they participated in the war for the United States. They became very well-known for certain battles in the war. In fact, the most famous battle that Teddy Roosevelt and his Rough Riders were part of was the Battle of San Juan Hill in Cuba. Much of the fighting took place in Cuba for the Spanish-American War. Cuba was at that time a possession of Spain. After the war it became an independent country, one that was friendly to the United States up until the mid-20th century, 1959, when Fidel Castro became head of Cuba. But anyway, we’re talking about Teddy Roosevelt.
Roosevelt was elected Governor of New York in 1898, the same year as the war, and once again he fought against corruption, against government officials taking money for favors. He then became Vice-President of the United States in 1901, so he was elected vice-president along with the president, William McKinley, in the election of 1900. However in 1901 President McKinley was killed – he was assassinated, and as happens when the president is killed “in office,” while serving as president, the vice-president becomes president, and that’s what happened with Roosevelt. He became president in 1901. He tried to continue the policies – the ideas of McKinley. In 1904, he ran for election as president and won on his own.
During Roosevelt’s presidency he fought hard against trusts (trusts). “Trusts” were very large corporations or companies that often didn’t have a lot of competition. He was famous for signing laws to protect people, things like the Meat Inspection Act and the Pure Food and Drug Act, which tried to protect people against companies that were selling bad products, food, and drugs. Roosevelt was probably most famous for being a “conservationist,” someone who wants to protect the natural environment against humans, basically. He actually set aside or declared a lot of land in the United States for national parks, including the most famous national park in California, Yosemite.
Teddy Roosevelt was also active in “foreign policy,” dealing with other countries. He helped establish the United States’ “role” or position in using international power to help other countries. Of course, that doesn’t always happen in U.S. history or most other countries’ history. Roosevelt was given the Nobel Peace Prize for helping negotiate an end to the Russo-Japanese War – the Russian and Japanese war. He was also a leader in the construction of what we call the Panama Canal. A “canal” is a long strip – a large, long hole really – that you dig in order to connect two bodies of water, two lakes for example. For the Panama Canal, it connects two oceans, the Atlantic and Pacific, going through the middle of the country of Panama in Central America.
Roosevelt could have run for another “term,” another four-year period as president in 1908, but he decided not to. Instead, he decided to travel to Africa to go on an African “safari,” an adventure where, at least in the old days, you used to hunt and kill animals. Roosevelt went on an African safari, where he caught and killed many animals, which were later given to the Smithsonian museums, the United States’ national set of museums in Washington, D.C. Photographs of Roosevelt on his safari certainly helped give Americans the image of this rough, tough man, an “outdoorsman,” somebody who likes to go outside a lot, someone who spends a lot of time outside, or “outdoors,” we say. People viewed Roosevelt as a very strong fighter, as a hunter, and that’s still the popular image of Teddy Roosevelt today.
In 1908, because Roosevelt did not try to become president again, another man, William Taft, became president. Taft, however, was often at odds with Roosevelt. When we say someone was “at odds (odds) with” someone else, we mean that they didn’t agree on many things. So in 1911, Roosevelt decided he was going to run for president again. However, the political party that supported Roosevelt, the Republican Party, were already supporting other people, and so Roosevelt decided to do the very difficult thing in American politics, to create a third party, not Democrat, not Republican, but a third party. His party was known as the Bull Moose Party. They promised to protect people against large corporations and corrupt politicians. However, Roosevelt lost the election to Woodrow Wilson, a man in some ways the opposite of Roosevelt, a man who was considered an academic. He was, for a while, President of Princeton University, a very different sort of politician. Though Roosevelt was more successful than most, in fact, more successful than any other third-party politician in American history, he came in second to Woodrow Wilson, who won the election in 1912.
During that election, someone tried to kill Roosevelt, and Roosevelt was shot. Although he didn’t die, he was affected by that assassination attempt. In 1913, Roosevelt went on a scientific expedition, this time to South America, but again he suffered an injury and his health was getting worse. When he returned home in 1914, he continued to be ill. He died in 1919, and was considered one of the better presidents in American history. In fact, less than 10 years later he was selected as one the four greatest American presidents, along with George Washington, Thomas Jefferson, and Abraham Lincoln. Today, historians still consider Roosevelt to be a good president.
A couple of interesting side notes: First of all, Roosevelt did not like being called Teddy, even though that was his nickname and that’s what most Americans know him by. Of course, the last name Roosevelt should remind you of another American president, Franklin Delano Roosevelt, president during a large part of the 1930s through World War II. The two Roosevelts were related, but not closely, they were what we call fifth cousins. So, they weren’t close relatives but they were related. America has had much closer relationships in its presidents: John Quincy Adams was the son of John Adams, George W. Bush was the son of George Herbert Walker Bush, and William Henry Harrison was the grandfather of Benjamin Harrison, who, you remember, gave Roosevelt a job for supporting his campaign for president.
Now let’s turn briefly to our second topic on this Café, the Folk Tales of Uncle Remus. A “folk (folk) tale (tale)” is a story that is told by many people, especially stories that have been told for many, many years. Folk tales are often associated with what we would call “rural” areas, that is, places outside of the cities and towns.
In 1881, a man by the name of Joel Chandler Harris, who lived in Georgia, decided to publish a book of folk tales that he called Uncle Remus. Now, there was no such person as Uncle Remus; Remus was a fictional character. However, Harris says that many of the stories he heard, he heard from African Americans who lived in the Americans South; Georgia is in what we call the Deep South of the U.S.
In the book, Uncle Remus is a man who shares these folk tales with the children who are listening to him. The stories are written in what is called “dialect,” which is the way that a certain group of people speak; in this case, the dialect of slaves in the Deep South.
Some people see the stories as being very racist, since they were written by a white author. Other people, however, are impressed by how well Harris was able to record these folk tales that were popular among African Americans at that time.
Probably the most famous folk tale that most Americans will know from this collection of stories is called “Br’er Rabbit (or Brother Rabbit) and “Br’er Fox (or Brother Fox)” (the “Br’er” is short for brother). Br’er Fox, in the story, takes some clothes and some “tar,” which is a very sticky, dark substance we now use on our roads where the automobiles go, and he puts this tar in the clothes so that this tar looks like a person. When the other character in the story, Br’er Rabbit, sees it he tries to be friendly, but the little baby made of tar, the Tar Baby, doesn’t respond and Br’er Rabbit becomes angry. He “punches” or hits the Tar Baby, but his fist, which is your hand when it is all together like you’re going to hit someone, his fist gets stuck in the tar. That story and references to a “tar baby” are sometimes used to talk about how some problems get worse the more we try to fight against them.
The Folk Tales of Uncle Remus have been repeated many times and made into movies. Walt Disney made a movie called Song of the South in 1946 that combined actors and animation (or cartoons) to tell some of these stories. So if you want to learn more about Br’er Rabbit, you can watch that movie.
An interesting connection between our two topics today, although we didn’t know this before we started: Many of the stories of Br’er Rabbit that are included in the Folk Tales of Uncle Remus were originally written down by a man called Robert Roosevelt, who was – that’s right – a relative of Teddy Roosevelt; he was Teddy Roosevelt’s uncle. And, Teddy Roosevelt talks about, in his own story – his autobiography, about hearing the tales of Br’er Rabbit from his aunt and uncle.
Now let’s answer some of your questions
Chenming (Chenming) in Australia wants to know the meaning of the words “drug,” “pill,” and “tablet.” These three words are very similar.
“Drug” is a general term meaning medicine, anything that you put into your body to make you healthy when you are sick. A drug can also be something that changes your behavior, that you don’t take to make yourself better but you take to change the way you feel or behave. In that way, alcohol or marijuana could be called drugs.
A “pill” is usually a very small amount of a drug or a small amount of medicine. Usually it’s round, often like a ball. You put it in your mouth and typically you either swallow it whole or you use your teeth to chew it – to break it up so you can swallow it.
A “tablet” could also be a ball-shaped amount of medicine, although when I think of tablet I think of the shape as being more flat on both sides, so it’s more like a coin, a small, round thing. But it is also it way of calling what we refer to as a “dose” or a single amount of a drug that you take to get better. A tablet can also be a large, flat piece of stone or rock that you use to write things on. And nowadays, we have electronic tablets, things like the iPad – which some people also think is a drug!
Although “pill” and “tablet” are similar, “pill” is much more common in American English. In other countries – English-speaking countries, the word “tablet” is more common, but Americans understand both.
Fei (Fei) in China wants to know how we pronounce certain fractions. A “fraction” is a number that is less than one, usually it’s represented with one number and then a line, what we would call a “slash,” and then another number on the bottom or to the right of the first number.
Well, “1/2” is pronounced “one half.” “1/3” or “one over three,” we would say, is one third; “1/4” is one fourth, “1/5” is one fifth, “1/10” is one tenth , “1/253” is one 253rd, and so forth.
You will often see in cooking recipes, instructions about making food, these fractions such as 1/2. Native speakers would probably just say “half” or “one half.” However they never say “one second,” even though two is, as an ordinal number, second – first, second, third, right? But we don’t say “one second,” we say “one half,” we never say “one second.” “One second” would refer to an amount of time; there are 60 seconds in one minute for example. And, you can say things like “a half a second” or “one half of a second,” that would be a single unit of time, one second divided by two. You can say “a half hour” or “a half a day,” depending on what you want to talk about.
Americans often sometimes use “half” in front of an adjective when they are trying to make something sound bigger than it is, and so they are exaggerating. I could say, “I’m half starved.” “To be starved” means to be so hungry that you’re about to die. So, you’re not actually starved, so instead you say “I’m half starved.” Or you could say, as I do, “My neighbor is half crazy,” I mean – actually, my neighbor is crazy, not half crazy, but that would be an example!
Finally, Luis Alberto (Luis Alberto) in the country of Chile wants to know the difference between “engagement” and “commitment” when we’re talking about business.
In general, an “engagement” is a promise to do something at a certain time. “I have an engagement to meet my boss at five o’clock this afternoon.” It’s the same, really, as a meeting with my boss. An engagement could also be a period of work. “My friend has an engagement to play piano at his friend’s wedding.”
Finally, “engagement” in a non-business sense is an agreement to get married. We say “the couple is engaged,” there is an engagement, there is an agreement to get married.
“Commitment” is a promise to do something, especially if it involves money. “The company made a commitment to buy all of its paper from the Smith Paper Company.” It doesn’t always have to involve money, however. You could just say to someone, “I’m sorry I can’t help you, I have too many commitments,” meaning I have too many things that I have promised other people to do.
A “commitment,” more generally outside of the business world, can mean a feeling of responsibility toward someone or something. “Our company has a commitment to quality,” we are promising ourselves that we will do some things that will give you quality; we have this responsibility.
Finally, just to make things confusing, “commitment” can also mean a meeting, just like “engagement” can mean a meeting. Someone says, “Can you meet me at four o’clock,” you might say, “No, I have a commitment at 3:30.” Or, you could say, “I have an engagement to meet my colleague at four o’clock, I can’t meet you.”
We at ESL Podcast have a commitment to help you improve your English. If you have a question email us at eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again in a couple of years on our 400th episode of the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
sickly – often ill; in poor health
* Randall is strong and healthy now, but he was a sickly child.
disillusioned – feeling disappointed by something because one had certain expectations for it or ideas about how something should be, but the reality didn’t meet those expectations
* When the boy saw that the magic was only a trick, he felt disillusioned.
spoils system – the practice of thanking voters by giving them government jobs, rather than giving those jobs to the people who are really qualified for them
* Under the spoils system, the wealthy and well connected get the best jobs, instead of those who deserve them.
to declare – to officially announce; to announce the official beginning of something
* The president declared May as Asian Pacific American Heritage month.
rough – not smooth; not socially well-mannered or elegant
* His manners are a little rough, but that’s only because he grew up without parents.
trust – an older term used for a very large corporation that has successfully limited or eliminated competition
* The new anti-trust laws ensure that no one company completely dominates any one market.
canal – a long area of land dug out to connect two bodies of water
* We need to find the canal that will allow our boat to reach the Atlantic Ocean.
at odds with – disagreeing with someone; having different opinions as someone else
* The uniform Sally is required to wear to work is at odds with her religious beliefs.
folk tale – a story told by many people, especially in a rural area or long ago
* My grandfather told me a folk tale about talking frogs and dancing bears.
fictional – invented by someone, usually to tell a story; not real
* This story is about a fictional war between the U.S. and Belgium.
dialect – a particular form of a language spoken by a group of people from a specific region or social group
* Mike speaks a southern dialect that is difficult for New Yorkers to understand.
tar – a dark, thick liquid made of wood or coal that is often used for the top surfaces of roads
* We didn’t see the signs and drove on the new road before it was ready to be used, getting tar all over the outside of the car.
drug – medicine; something people use to cure, avoid, or reduce the bad effects of an illness; a chemical that changes the way people feel or behave
* Doctor, how long will I need to take this drug before I start to feel better?
pill – a small single unit or amount of medicine which people take by swallowing or chewing
* The pills my husband takes are so big that he has to take a very large drink of water to try to swallow just one.
tablet – a small single unit or amount of medicine, usually in the shape of a ball that is flat on top and bottom, which people usually take by swallowing or chewing
* The tablet was too big for little Jake to swallow, so his mother crushed it and mixed it into his food.
half (?) – one of two equal parts; (about) fifty percent
* Salia gave half of the apple to her brother and ate the other half herself.
engagement – a promise to do something, especially at a certain place and time; an agreement to get married
* Matt and Lisa’s engagement only lasted two weeks before they broke up.
commitment – a promise to do something, especially if it involves an exchange of money; a feeling of responsibility toward a person, idea, or activity
* For over 20 years, Kristina has had a commitment to help the poor find affordable housing.
What Insiders Know
The Origin of Teddy Bears
Few children today grow up without playing with or owning a “teddy bear,” a soft toy in the shape of a “bear,” a large white, brown, or black animal. “Teddy bears” are actually named after President Theodore Roosevelt. His “nickname,” or informal name among friends and family, was Teddy.
The name came from something that occurred in November of 1902. The governor of Mississippi, Andrew H. Longino, had invited President Roosevelt on a bear-hunting trip in his state. Several hunters joined the Governor and the President, and after a few hours, most of them had already shot and killed an animal. President Roosevelt’s “attendants” (people who work for him and who accompanied him) captured a bear and tied it to a tree, suggesting to the President that he should shoot it. That way, he would have killed an animal, too.
President Roosevelt refused to shoot the bear. He said that it was “unsportsmanlike” (not fair in the playing of sports) the way that his attendants had “cornered” (prevented escape) and “clubbed” (used heavy pieces of wood to hit someone or something to hurt it) the bear. It was clear that the bear was badly hurt and in pain, and he ordered someone else to shoot it “to put it out of its misery” (to end its suffering).
The “incident” (event) was the subject of a “political cartoon” (drawing about political issues, making a specific point) in The Washing Post newspaper in 1902. Morris Michtom, an immigrant candy store owner, saw the cartoon and created a stuffed toy bear called “Teddy’s bear.” He sent the bear to President Roosevelt and received the President’s permission to use his name. Michtom and his wife started making the bears at night and selling them in his candy store. However, the new Teddy’s bear sold so well that Michtom decided to start a new company just to make and sell these stuffed bears.