= 1571
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 266.
This is English as a Second Language Podcast’s English Café episode 266. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. On it, you can visit our ESL Podcast Store, which has some additional premium courses in business and daily English that you will enjoy, I think – no, no, you definitely will enjoy them! You will also be able to download the Learning Guide for this episode. The Learning Guide contains lots of additional information, including a complete transcript of this episode to help you improve your English even faster – and get up earlier in the morning!
On this Café, we’re going to have another one of our Ask an American segments, where we listen to another native speaker talk at a normal rate of speech – a normal speed. Today, we’re going to listen people talk about the need for minority doctors in the United States, or doctors who are something other than white. As always, we’ll answer a few of your questions as well. Let’s get started.
Our topic on this Café’s Ask an American segment is the need for minority doctors. The word “minority” (minority) is the opposite of majority. A majority is more than 50 percent; a minority means, therefore, less than 50 percent. There’s a third word to describe a situation where you have three or more groups to describe the biggest of those groups even if it is not a majority; that word is “plurality” (plurality). When you have a plurality, your group is biggest but it’s not a majority. When talking about people here in the United States you most often hear minority to refer to “race,” the factor that is indicated most often by skin color. In the United States, most people – the majority of the people are white. The minorities are anyone of a different race, such as African American, Hispanic American, or Asian American. Now there are some people who don’t like putting Hispanic American or Latino American into that group because you can have different races that are Latino or Hispanic. Both words, by the way, mean the same thing in the United States. Some people refer, instead, to racial and ethnic groups. Ethnic groups are related more to the country or countries where people are from rather than to things like skin color. In any case, it’s generally understood that the major minority groups, if you will, in the U.S. are black or African American, Latino or Hispanic, and Asian American.
Unfortunately, the healthcare – the medical care that minorities receive in the U.S. on average isn’t as good as the healthcare that many white people receive. Many experts believe this is partly because there are not very many minority doctors in the U.S. Another obvious reason is poverty; people who are poorer get worse healthcare – worse medical attention, and that is particularly true among Latino and African American populations. Some people think that if there were more minority doctors – more black, Latino, and Asian American doctors, or if there were more white or Caucasian doctors who were trained to provide medical care for minorities, who were trained in the different customs, the different cultural practices perhaps of different minority communities that healthcare for minorities would get better – would improve.
We’re going to listen today to a doctor, Dr. Louis Sullivan, who used to be the secretary or the leader of the federal department that takes care of healthcare and medicine, the U.S. Department of Health and Human Services. He’s first going to talk about some research – some scientific studies about African American and Latino or Hispanic American physicians. “Physicians” are doctors. Let’s listen to Dr. Sullivan.
[recording]
There are studies that have shown that African American physicians or Hispanic American physicians are three to five times more likely to establish their practices in African American or Hispanic American communities.
[end of recording]
Dr. Sullivan begins by talking about certain studies. Normally “to study” means to try to learn something by taking classes or reading books on a particular topic. Here, the word “studies” refers to research or scientific studies, which are the efforts of experts – scientists – to learn detailed information about a particular topic. For example, both Lucy and I have done and read a lot of studies about language acquisition and things related to language as part of our own practice and training.
The studies Dr. Sullivan is referring to show or indicate that African American or black physicians or Latino physicians are three to five times more likely to establish their practices in African American or Hispanic American communities. What does that mean? Well, let’s begin with the verb “to establish.” To establish usually means to start or create something officially. We talk about organizations that were established, when they were first created. The Center for Educational Development was established in the year 2000. Here, we’re talking about physicians, doctors establishing their practices; that is, starting up their medical service to people. Usually when we talk about setting up your practice or establishing your practice, we’re talking about the office that you start – you open to help people with their medical problems, so “practice” really refers to the place where the doctor works. When a doctor establishes a practice, then, he may open an office or a clinic to start seeing patients – seeing people who are sick or need help.
Dr. Sullivan says that research studies show that minority physicians are three to five times more likely to establish their practices in African American or Hispanic American communities. “Communities” here means places where a particular group or groups of people live. So, if you are black or Latino, you will probably start your medical practice – you will probably open a medical office in areas where there are other blacks or Latinos living. This, of course, helps improve the medical care by providing more opportunities – more access to healthcare in those communities. Let’s listen to Dr. Sullivan one more time:
[recording]
There are studies that have shown that African American physicians or Hispanic American physicians are three to five times more likely to establish their practices in African American or Hispanic American communities.
[end of recording]
We continue listening to Dr. Sullivan. This time he’s going to talk about what is important in healthcare and why having minority doctors is important in improving the healthcare of those who are in minority communities. This is a very long quote. Listen, try to understand what you can, and then we’ll come back and explain it.
[recording]
What happens with the health outcome depends upon good communication, the trust and credibility between the health professional and the individual seeking care, and an understanding of the patient’s culture, value system, so that one can develop, hopefully, a strong relationship or interaction between the health professional and the individual. Otherwise, what we see resulting are lack of compliance, people not returning for appointments, not filling prescriptions, not doing a number of things that they should be doing and they must do as part of doing their part of the health exchange.
[end of recording]
Dr. Sullivan begins by saying, “What happens with the health outcome depends upon good communication. An “outcome” (outcome) is a result, what is accomplished, what is achieved. A health outcome refers to what happens after the doctor sees, or “treats” we would say, a patient. Is the patient healthier? Is there an improvement? That would be a good health outcome.
He’s saying that health outcomes depend upon first good communication, the ability for the doctor and the patient to talk to each other. He also says it depends on trust and credibility between the health professional and the individual seeking care. “Credibility” is whether you can be believed, whether something is believable. So, trust and credibility refer to whether the patient trusts the doctor, believes the doctor knows what he or she is talking about. The “health professional” could be a doctor, it also could be a nurse or someone else working in a hospital or clinic. The individual seeks care. “To seek” is to ask for or to look for. So, this is talking about the patient, the person who comes to see the doctor.
In addition to trust and credibility the doctor also needs to understand the patients culture and value system. The value system would be the things that they think are important, the things that they think are rights and wrong. Dr. Sullivan believes that if you have these things, good communication, trust and credibility, understanding a patient’s culture and value system, then you can develop a strong relationship or interaction between the health professional and the individual. You can develop, hopefully, Dr. Sullivan says, meaning we hope, a strong connection – a strong relationship between the doctor and the patient. “Otherwise,” he says, meaning if this doesn’t happen, “what we see resulting are lack of compliance, people not returning for appointments.” We’ll stop right there. “What we see resulting” means what happens as a result, what is the consequence of this situation. What happens when you don’t have doctors who have good communication, trust, credibility, and so forth is you see a lack of compliance. “A lack of” something means you don’t have something. “Compliance” refers to following the rules or the laws; in this case, doing what the doctor tells you to do. When patients don’t trust their doctors, there is a lack of compliance. The doctor may say, for example, to come back next week for another appointment, but people don’t come back; people are not returning for their appointments. Sometimes they’re not filling their prescriptions. A “prescription” is normally a piece of paper where the doctor writes down the name of the drug, and then signs or puts his or her signature. The patient takes that piece of paper to a pharmacy or a drugstore and gets the drugs. Well, some patients are not filling their prescriptions; they’re not actually going out and getting the drugs that the doctor told them to take.
They’re also not doing, according to Dr. Sullivan, a number of things – several things that they should be doing, and they must do as part of doing their part of the health exchange. So, there are other things that patients don’t do in these situations. They are not doing what they are supposed to do – what they should be doing as part of doing their part of the health exchange. What does that mean? Well, you hear the word “part” (part) twice here. “As part of (something)” means as one element, as one factor, as one piece of something. “To do your part” means to do what you are supposed to do, to do what you are expected to do. Dr. Sullivan says that people are not doing their part of the health exchange. An “exchange” is what happens when one person gives something and another person gives something else, or when one person does one thing for another person and that person does something in return. In healthcare, what the doctor is saying is that we can’t expect doctors to do everything. We have to do the things that we’re supposed to do; the doctors will do their part by making sure that they have an appointment for you, writing prescriptions, and so forth.
Let’s listen one more time to Dr. Sullivan.
[recording]
What happens with the health outcome depends upon good communication, the trust and credibility between the health professional and the individual seeking care, and an understanding of the patient’s culture, value system, so that one can develop, hopefully, a strong relationship or interaction between the health professional and the individual. Otherwise, what we see resulting are lack of compliance, people not returning for appointments, not filling prescriptions, not doing a number of things that they should be doing and they must do as part of doing their part of the health exchange.
[end of recording]
We’ll listen to one more quote from Dr. Sullivan, as he talks about expectations for minority doctors in the United States.
[recording]
If we’re successful, it will be decades before our health professionals, our health professions, really, truly mirror the makeup of our general population. So yes, we want all physicians – white, African American, Latino, what have you – to be culturally competent.
[end of recording]
He says, “If we are successful, it will be decades before our health professionals, our health professions, really, truly mirror the makeup of our general population.” A “decade” is 10 years, so “decades” (plural) would be 20-30-40 years from now. It will take that long, Dr. Sullivan says, before our health professionals, doctors and nurses, really, truly mirror the makeup of our general population. “Truly” means actually; the word is related to truth or honesty, and here it’s used for emphasis, like the word “really.” If you really, truly want to improve your English you should listen and read English every day. He’s saying that the health professionals will not mirror the makeup of our general population for decades. “To mirror” here means to reflect, to be the same as. The “makeup” (makeup – one word) of a population is the different elements – the different parts: ethnically, racially, in terms of men and women. All of these are categories to describe the makeup of a population – all different elements. So we need, Dr. Sullivan says, to change the health profession so that we have physicians of all different races and ethnicities – “white, African American, Latino, what have you,” he says, “to be culturally competent.” “What have you” means and all the others. “Culturally competent” means that you are good at understanding another culture; you understand different cultures, cultures that are different from your own.
Let’s listen one more time.
[recording]
If we’re successful, it will be decades before our health professionals, our health professions, really, truly mirror the makeup of our general population. So yes, we want all physicians – white, African American, Latino, what have you – to be culturally competent.
[end of recording]
Now let’s answer a few of your questions.
Our first question comes from Yaroslav (Yaroslav) in Ukraine. Yaroslav wants to know to the meaning of the phrases “if I were” and “I wish I were.” Why do we say “were” here in the past tense? Well, this is a rare case of what in other languages is called the past subjunctive. We use the past subjunctive, or the subjunctive form in general, when we want to express a wish, a hope, or a possibility: something that is not true now, but if certain things happen will be or can be true in the future.
For example: If my mother were here – and she’s not here, but if she were here she would tell me to drink less tea. That is what would happen if she were here. But she’s not here, and so that is not happening. The “would” is the conditional part of the sentence.
This use of the past subjunctive, the “were” in the previous statements, is not as common now as it used to be. In fact, many people now use simply “was” – “if I was going there I would do that.” It’s not the grammar book way of doing it – it’s not what the grammar books would say is correct, but it is very common now in conversations and even in written English in some places.
Benjamin (Benjamin) in Chile wants to know how we use the words “near” (near) and “close” (close). “Near” and “close” have similar meanings, and sometimes they can be used interchangeably. That is, you could use either one and they both would be correct. That isn’t always true, however. Let’s start with the interchangeable uses.
If you’re talking about a very short distance from one thing to another either physically, such as from my chair to my desk, or in time, such as Christmas to New Year’s, then you can use either “near” or “close.” You could say, “My house is near my school,” “My chair is close to the table,” “The Christmas holiday is close to the end of the year.” Notice, however, when we use them in this way we have to put the preposition “to” (to) after the word “close,” so it’s “close to” something.
You can also use both words adding the letters “by” at the end, so you get “nearby,” which is one word, and “close by,” which is two words, but it means the same thing. What you’re saying is that whatever you are talking about is close to where you are now or where you have been talking about. For example, I’m talking about the store that is close to my house; I would say, or could say, “Well, the store is over there, and there’s a pizza place nearby,” or “there’s a taco shop close by.” That means that near the store, close to the store there is a pizza place or a taco shop – a pizza restaurant.
There are some differences, however, in using these two words. When you use the word “near” as an adjective it means almost, in the sense of you are almost at that condition. For example: “He is near death.” He’s not dead, but he’s very close to being dead; he’s almost dead. “Near” can also be used, especially in the form “nearest,” to mean directly related, usually related in terms of being a member of the family: “Who is your nearest living relative?” What member of your family is nearest to you in terms of relationship? If you are an only child and your parents die, your nearest relative might be an uncle or an aunt or a cousin.
“Close” as an adjective can mean limited in space, not a lot of room. “We are living in close quarters.” That means there isn’t a lot of room where we are. “Close” can also mean very friendly. For example: “My wife and our neighbor are close,” meaning they’re close friends, they know each other very well. Or I could say, “All of my brothers and sisters are close.” We all are friendly, we know each other – of course! – but we are very good friends with each other. “I used to be close to my friend Jack, but we have not talked to each other in many years.” We are no longer close.
Finally, Sanghye (Sanghye), from an unknown country – we’ll call it Country X, says he wants to know the meaning of the expression “to hold (something) against (someone).” “To hold “something) against (someone)” usually means to be mad at somebody because of something that they did a long time ago but you continue to be angry. You continue to, perhaps, treat that person differently: you don’t talk to them or you say bad things about them because of something that happened a long time about. “I know you said you don’t like men who are bald (who have no hair), but I hope you won’t hold that against me.” In this last example, it’s not that I did something wrong a long time ago. Instead, it’s that you have said something a long time ago, perhaps last week, and I am not meeting that condition. You said you don’t like people who are bald, and I’m bald, so I hope you won’t hold that against me. I don’t meet those conditions that you want, but I still hope that we can be friends.
If you’re a friend of ESL Podcast, you can email us your question or comment. We don’t have time to answer all of your questions, and remember many of the questions that are emailed to us are already on our website. They’ve already been answered in many cases, so make sure that you search the website before emailing us your question. But again, if you have questions and we haven’t answered them, you can email us at eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
study – a research study; the efforts of experts to learn detailed information about a particular topic
* Have there been any studies on the long-term effects of cell phone usage?
to establish – to officially start or create something, especially an organization or business
* This university was established in 1842.
practice – where a doctor or lawyer works; the business of a doctor or lawyer
* Their legal practice specializes in immigration law.
outcome – result; what is achieved
* We’re hoping for a positive outcome by the end of the project’s first year.
credibility – the quality of being believed and having one’s opinion trusted
* The conservative politician lost a lot of credibility when he admitted that he had lied about his military service.
health professional – a doctor or medical care provider; someone who works in the medical field
* Surgeons are some of the highest-paid health professionals.
to result – to happen as a consequence of something else
* Having a better website doesn’t always result in more website traffic.
compliance – following the laws; following the rules
* Is it more effective to reward people for compliance, or punish them for non-compliance?
prescription – a piece of paper where a doctor writes down the name of a medicine that a patient should take so that the patient can buy that medicine in a pharmacy
* When Cooper had an ear infection, his doctor gave him a prescription for antibiotics.
exchange – the practice of one person giving something and another person who giving something else in return; when one person does something and another person does something else in return
* I propose an exchange: You mow my lawn each week for one year and I’ll paint your house for free.
truly – really; a word used for emphasis to show that something is true or honest
* Do you really, truly want to buy such an expensive car?
makeup – what something is made up of; the characteristics of a group of people or object
* We were surprised by the makeup of the new class of engineering students. Less than 10% are women.
culturally competent – having a very good understanding of another culture so that one can work with people from that culture without insulting or offending them, doing things that are appropriate in that culture to make people comfortable and have a good relationship with them.
* Anyone who is culturally competent in the United States knows the importance of making eye contact when speaking with an American.
near – a very short distance apart, either in space or time; almost; close but not quite on target
* He wants to find an apartment near the office, so that he can walk to work.
close – a very short distance apart, either in space or time; limited in space; known only to a few people; very friendly
* Have you and your sister always been close?
to hold (something) against (someone) – to think badly of someone or something because of something that this person/group has done or some existing condition related to this person/group; to continue to feel anger toward someone
* I know I treated you badly in the past, but please don’t hold it against me. I have changed!
What Insiders Know
ER
Many people are fascinated by “medical dramas” (TV shows about doctors), and ER is one of the most popular medical drama in the United States. “ER” “stands for” (is an abbreviation for) “emergency room,” or the part of a hospital that people go to when they have a very serious, life-threatening condition and need to see a doctor right away, without making an appointment.
The TV show is about a group of doctors, nurses, and “administrators” (management; people whose job is to make a business or organization run efficiently) who work in the emergency room at a hospital in Chicago, Illinois. In each show, there are many different patients and medical challenges, but the real “drama” (interest and excitement in the relationships between people) comes from the relationships among the doctors, nurses, and administrators. The show lets viewers see what happens in the emergency room, as well as “glimpses” (small, rapid views) of what happens in the characters’ personal life.
The show tries to be medically “accurate” (correct; precise). Real doctors review the “scripts” (written version of the show) before they are filmed to make sure that the patients’ medical conditions and treatments are “depicted” (shown) realistically.
The show “ran” (was shown on TV) from 1994 to 2009, making it the “longest running” (seen on TV for the largest number of years) medical drama on American television. ER won 23 Emmy awards and was “nominated” (listed as a potential winner) for many others. In 1996, it won the award for Outstanding Drama Series. Although the show’s producers aren’t making any new episodes, viewers can still see “reruns” (repeats of earlier shows) on TV.