= 1428
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 123.
This is the English Café episode 123. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com to download a Learning Guide for this episode. You can also take a look at our ESL Podcast Store, which has some business and personal English courses to help you improve your English even faster.
On this Café, we’re going to talk about Charles Schultz, one of the most famous American cartoonists of the 20th century. He is the person behind the Peanuts cartoons, which have become very popular in many countries. We’ll talk about him and his life. We’ll also talk about becoming a police officer in the United States; what are the procedures, what are the things that you have to do to become a “cop,” as we sometimes call them. As always, we’ll answer a few of your questions. Let’s get started.
When I was growing up, one of the most popular comic strips was something called Peanuts. A “comic strip” is a funny drawing that appears in the newspaper. Usually there are three or four drawings that tell a small story, and the most popular comic strip in the United States was Peanuts by Charles Schultz. It had characters such as a dog named Snoopy and a boy named Charlie Brown.
The person who created and drew the comic strip Peanuts was called Charles Schultz. Schultz began the Peanuts comic strip back in October of 1950, and it continued to “run,” that is, it continue to be published until February of the year 2000, so nearly 50 years. During that 50 years more than 17,000 comic strips were published. When the comic strip was “at its peak,” that is, when it was most popular, it ran in over 2,600 newspapers and had more than 350 million people in 75 countries who read it. Perhaps you have read a version of the Peanuts comic strip in your own language.
Charles Schultz was an interesting man. He was born in Minneapolis, Minnesota, but he was raised in St. Paul, Minnesota. That’s where he grew up – that’s where he spent his early childhood and teenage years. St. Paul is famous, of course, for producing famous and talented people! He was an only child; his parents had no other children. He grew up in St. Paul; he actually went to high school at a place where my father went to high school. He was two years younger than my father, I believe. The tradition in American high schools is at the end of the year they publish a book called a “yearbook” that contains all the pictures of all of the students, and my father has a yearbook where he has the signature of Charles Schultz, who, of course, was not famous when he was in high school when my father knew him.
Schultz became a “cartoonist,” that is, someone who draws cartoons or comic strips. He first worked for the local newspaper in St. Paul, Minnesota. He eventually got what we would call a “syndicated” comic strip. Something that is “syndicated” is something that is distributed to different newspapers; it is also a term we can use for a television program that is shown on different stations throughout the country.
Schultz’s mother died in 1943 – very young. Schultz was a very good student in school. In fact he was so good that he was put in a higher grade at a younger age, and this may have caused some problems because he was always the youngest person in his class. Some people think that the character of Charlie Brown – Charles Schultz’s most famous character – is in part a reflection of his own difficult childhood, where he was very shy and withdrawn. To be “withdrawn” means you don’t talk to many people – you are very quiet, and that was the personality of Charles Schultz as well.
The person Charlie Brown was an actual cartoonist, one of the friends of Charles Schultz. The real Charlie Brown actually wrote a book, oh, about 20-25 years ago before he died, about his own life – his own difficult life. I had a friend of mine in the Twin Cities – in Minneapolis/St. Paul – who actually helped publish the book, and gave me a copy of it. Very few people know that there was a real Charlie Brown that was the, in part, inspiration for the character Charlie Brown.
Well, Schultz became very famous once his comic strip began to syndicate in other newspapers. Although there was a real Charlie Brown, some of the characteristics of the comic strip were a reflection of Schultz’s own life. His father was a barber. A “barber” (barber) is a person who cuts your hair, usually a term we use for a man who cuts another man’s hair. If it’s a woman, we sometimes called them a “hairdresser,” or a “hair stylist.” “Barber” is a little older term. The place where a barber works is called a “barber shop.”
In October of 2007 a biography of Charles Schultz was published. The family of Charles Schultz criticized the author, saying that the biography was not an accurate reflection of who the real Charles Schultz was. But other people say that it was, in fact, an accurate “portrait” we might say, an accurate picture, an accurate description of his own somewhat lonely life. If you’ve ever watched a Charlie Brown television program or read the Peanuts comic strip, you know that Charlie Brown has a very difficult childhood. He goes through some painful experiences. He also has what we might call an “inferiority complex.” “To feel inferior” means you think you are not as good as other people around you – you are not as smart or not as strong as other people who are around you, and this is sometimes called an “inferiority complex,” meaning that’s the way you think.
Charlie Brown, Patty, Violet – Patty, of course, was Peppermint Patty – and Snoopy were some of the famous members of this comic strip. There was also Lucy and her brother Linus. Lucy was always teasing Charlie Brown. “To tease” (tease) here means to make fun of – to make jokes about. So, we all felt sorry for Charlie Brown, and perhaps some of us identified with him as well – felt like we were like him.
If you haven’t had a chance to read the Peanuts comic strip in English, you might want to try. Comic strips are actually very good ways of getting exposure to informal English. The picture helps you figure out, sometimes, what the joke is, and it might be interesting, especially if you’ve read the Peanuts comic strip in your own language.
Our next topic is how to become a police officer in United States. In the U.S., the basic requirement for a police officer is someone who has a high school education, what we would say a “high school diploma,” that’s the certificate you get when you finish high school. Many police officers also study in college; they often study in what are called “criminal justice” programs. A “criminal” is someone who commits a crime, that is, who breaks the law. “Justice” is following the law – is doing the right thing. Criminal justice programs, then, study human behavior, psychology, legal issues, other things that might help a police officer, sometimes called a “law enforcement officer.” “To enforce” (enforce) means to make sure that someone is following the rules – to make sure that someone is doing what they’re supposed to be doing.
There are many different police forces in the United States. A “police force” is a group of police officers who are all under the same organization. Most individual cities – such as Los Angeles, Santa Monica, Beverly Hills – have their own police force, their own officers who take care of the area of the city. Most states also have police officers; these are often called the “State Patrol.” In California, we have, also, county police officers. A “county” is bigger usually than a city; it’s a way of dividing up the state into different regions or sections. So, you will also have county police officers; you will have, sometimes, state police officers. In California these are called the “California Highway Patrol”; they’re responsible for the freeways and the highways. In many states each public university has its own police force, so you can see there are many different kinds of police forces. On the federal level there are law enforcement officers, we don’t often call them police officers. We have things like the Federal Bureau of Investigation – the FBI. That’s the closest we have in the United States to a national police officer – a national law enforcement officer. Most police officers are local, however, from a city or a county, or perhaps the state.
To become a police officer you have to be strong. You have to be able to pass physical tests, tests of things like your strength; also your vision, make sure you can see well; your hearing, make sure that you can hear properly; and agility. “Agility” (agility) is your ability to move quickly – to be able to react quickly to a situation. Police officers also have to take a drug test and a lie detector test, the drug test to make sure that they are not using illegal drugs. A “lie detector test” is when they ask the person questions, and they use a special machine – a lie detector machine – to determine if you are lying or not based upon your reactions, especially the reactions that you can’t control, on your skin for example. Police officers also have to pass a background check. A “background check” means that they look at your past record to make sure that you haven’t committed any crimes.
After you’ve done all this, then you have to take a written exam, what’s called a “civil service exam.” A “civil service exam” is a test that the government gives its employees to make sure that they know what they’re supposed to know. There’s a specific civil service exam for police officers. After they pass the test – if they pass the test – then they go to a special school called a “police academy.” “Academy” is just another word for school here. They then have to be interviewed and write an essay, take a test, be interviewed by different police officers. Finally, after they finish their schooling at the academy, they are given an “appointment,” that is, they are given a job in the police force where they were training.
Police officers have other names that they are called; sometimes informally we call them “cops” (cops). In fact, there’s a famous TV show in the United States called Cops, where they follow police officers around and videotape what they do.
Police officers have good reputations in some cities, and bad reputations in other cities. Many people, I don’t think, understand the entire job of a police officer. Most of what a police officer does is not necessarily exciting, like you see on TV. They have to do a lot of very what we would call “routine” work, that is, common, ordinary work – responding to phone calls, people who are having problems, going to try to clam people down, perhaps, who are angry. Here in Los Angeles, we have a large homeless population – people who don’t have homes, who live on the streets. Police officers have to help these people; they have to deal with them. When we say you have to “deal with” someone, we mean you have to communicate with them, get along with them.
So that’s how to become a police officer in the U.S.; it requires many different steps. Most police officers are good and honest, I think. Of course, there are always problems in any profession, including law enforcement. It is always important to have a good system when you are giving someone a gun and the authority to arrest someone, it’s important that we have people who know what they’re doing.
Now let’s answer a few of your questions.
Our first question comes from Roberto (Roberto) in Italy. Roberto wants to know how we use the words “I” and “me.” For example, do you say “you and I,” or do you say “you and me” – when do you use each form?
Well, “you and I” are subject pronouns, so when they are the subject of a sentence, that is what you use. For example: “You and I will make great business partners,” or “You and I should go see a movie together this weekend.” “You and me” are object pronouns, and so when they are the object of the sentence, we use “you and me.” Notice, of course, that “you” is the same, but “I” becomes “me” as an object. For example: “She is going to take a picture of you and me.” “Me” is the object of the preposition “of” in this sentence, as is, of course, “you.” Or, “She’s telling you and me to shut up” – to be quiet. There again, “you and me” are the object of that sentence, of the verb “tell.”
Sometimes, however, we use the word “me” informally – incorrectly, if you want to think of it that way; it’s simply the way that people talk in normal conversation. For example, if someone says, “I want to go,” and another person, you, also want to go, you would say, “Me, too,” even though there it’s the subject. Technically, it should be “I, as well,” or “I, too,” but that sounds too formal – too strange. So, in certain circumstances, like “me, too,” we use “me” instead of “I” in informal English, in any case.
Sometimes it’s easy to figure out if you simply drop the “you” and just use the first person pronoun, “I” or “me.” For example, you have the sentence “He’ll blame you and me,” or “He’ll blame you and I.” Which is correct? Well, get rid of the “you,” and just say “He’ll blame me” – “He’ll blame I.” Well of course, the answer is “me.” Usually you’ll be able to hear the correct answer.
Sometimes you’ll hear native speakers trying to speak very correctly, and actually make a mistake. For example: “Who are these flowers for?” Someone who thinks that they’re speaking good English might say, “Oh, those are for you and I,” but in fact, “those are for you and me.” Sometimes trying to be too correct can lead you to problems.
Megumi (Megumi) in Japan wants to know about an expression that appears in the movie Die Hard, with Bruce Willis. At the very end of the movie the main character – Bruce Willis’s character – says “Yippee-ki-yay.” Actually, he says, “Yippee-ki-yay, mother...” and then a word that I can’t use on the podcast!
Well, what does “yippee-ki-yay” mean? It’s actually an expression from old cowboy movies – movies about the American West in the 19th century. Some people think that “yippee-ki-yay” originated from a cowboy’s call to the cows – the cattle – that he was trying to move, so he would call to the cows “yippee-ki-yay,” I’m not sure why. Some people say it actually comes from the word “yippee” (yippee), which was first used in 1920. Again, we’re not really sure why that particular word was used. So, “yippee-ki-yay” is a cry, it’s something that cowboys used to shout, usually to get the attention of the animals.
In this case though, in the movie Die Hard, the Bruce Willis character is using this expression because he’s acting alone to fight against bad guys, just like the hero in many of the old cowboy movies – there were five bad men and just one good man, and the good man fought against the bad men. So, he’s saying I am just like those heroes in the western movie – “Yippee-ki-yay!”
Francesco (Francesco), from I’m not sure where, wants to know the meaning of the expression “to call dibs” (dibs), or “to call first dibs.”
This is an expression very popular among children, especially children in a big family like the one I grew up in. “Dibs” is actually an informal word meaning a claim or a right to something. “To call dibs,” or “to call first dibs,” says that you have a claim to something – you own something, or you possess something, or you get to go first in something. For example, there’s only one piece of chocolate cake in the refrigerator, and you say to your brother, “I have dibs,” or “I call dibs on the last piece of cake, so don’t eat it.” In other words, you’re saying I have a right to eat that cake, that’s mine.
This is usually used when you are talking about something that no one has a natural right to. It’s something, perhaps, that is common or that doesn’t belong to anyone in particular, and you want it for yourself so you “call dibs” on it. Mostly, it’s an expression that children use.
If you have an expression you’d like us to try to explain, email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational Development.
Glossary
comic strip – a series of drawings that tell a funny story, printed every day or every week in a newspaper or magazine
* There was a funny comic strip about working in an office in today’s newspaper. Did you see it?
to syndicate – to sell what one writes or draws to many newspapers; to sell one’s articles or comic strip to many newspapers
* Dear Abby is an advice column that is syndicated to newspapers nationwide.
high school yearbook – a book with many color photographs that is produced at the end of the academic year and shows what happened at a high school during that year, so that people can remember their high school experiences after they have graduated
* Maxwell appears in his high school yearbook three times: on the soccer field, at the senior dance, and in chemistry lab.
withdrawn – shy; timid; not interested in talking or spending time with other people; solitary; isolated
* Carina is very withdrawn, always preferring to be alone with her books and music instead of spending time with friends.
at its peak – at its maximum; at the highest point or amount of something
* The price of oil is now at its peak; it has never been higher than it is right now.
barber – a man who cuts other men’s hair
* Quinton told the barber to be careful not to cut his hair too short.
hairdresser – a person (man or woman) who cuts and styles other people’s hair
* I need to make an appointment with a hairdresser because my hair is getting too long.
inferiority complex – the feeling that one is not as good, beautiful, powerful, intelligent, or important as other people
* Janey has such an inferiority complex! Just because she didn’t go to college, she thinks that everyone else is smarter than she is.
criminal justice – the system that a country uses to punish people who break the law and protect the rest of society from those people
* Courts and prisons are part of the U.S. criminal justice system.
agility – ability to move easily and quickly; flexibility
* The 95-year-old man ran across the street with surprising agility. No one thought he could move that quickly!
law enforcement officer – police officer; a person whose job is to make sure that other people follow the laws
* The woman identified herself as a law enforcement officer and told us to leave the area.
police force – the group of people who make sure that other people follow the laws; the members of one group of police officers, usually of a city or state
* Timmy joined the police force when he was 19 years old because he wanted to make his city a safer place to live.
civil service examination – a test taken by people who want to work in government administration; a test that the government uses to select employees for administration, but not for the military
* If you want to work at the embassy, you will probably need to take the civil service examination.
yippee-ki-yay – a meaningless phrase that is shouted to express enthusiasm, especially by cowboys
* We’re going to Austin, Texas for summer vacation. Yippee-ki-yay!
to call dibs – to have the right to use, do, or have something first, before anyone else.
* I call dibs on the front seat!
What Insiders Know
Classic Comic Strips
Peanuts is probably the most well known “classic” (very popular and well known) comic strip in the United States, but many others have been published a long time and are popular, too.
Calvin and Hobbes was a comic strip about a little boy named Calvin and his “stuffed animal” (a soft doll made to look like an animal, as a toy for children), a tiger named Hobbes. Everyone else sees the stuffed animal, but Calvin sees a live tiger who can talk. Calvin and Hobbes have many “adventures” (exciting experiences) together that make people think about their own childhood when they had a lot of “imagination” (the ability to see and believe things that are not really happening). Calvin and Hobbes is no longer being drawn, but it is “reprinted” (old drawings are printed multiple times) in many newspapers.
Another popular comic strip is Doonesbury, which is usually about what is happening in U.S. politics. For example, many of the Doonesbury strips are about the war in Iraq, and they often “feature” (show) U.S. presidents.
The Far Side is not really a comic strip, because it has only one “panel” (all the drawings appear in only one square, rather than a series of drawings). It has “surreal” (dreamlike and strange) humor that often focuses on strange events in life, talking animals, and logical problems. The panels appear not only in newspapers, but also on “coffee mugs” (large ceramic cups used for drinking coffee), calendars, and posters, especially in offices.
Finally, Cathy is another popular comic strip about a young single woman and the “struggles” (difficult things) that she faces in life. The comic strip is often about the humor in shopping, taking care of a house, working, and romance. The comic strip often “deals with” (covers a certain topic) society’s expectations of women.