= 1424
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 119.
This is English as a Second Language Podcast’s English Café episode one-one-nine (119). I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at eslpod.com. You can download a Learning Guide. You can also take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog, where several times a week we provide even more help in helping you increase your language proficiency.
On this Café, we’re going to talk about one of the most famous legendary heroes from American history, someone who is not a real person but represents some interesting ideas about American history. This person’s name is John Henry. We’re also going to talk about the City of Anchorage, Alaska. Alaska is our most northern state; we’ll talk about its largest city in this largest state of the United States. And as always, we’ll answer a few of your questions. Let’s get started.
Our first topic today is John Henry. John Henry is an African American (or black) folk hero. When we say someone is a “folk (folk) hero,” we mean that they are a made-up or imaginary person who has had some story told about them. It’s often the case that these stories – these folk stories have as their basis – as their cause some deeper social problem or important cultural issue.
John Henry was supposed to be the strongest man alive, according to the story. During the 19th century – during the 1800s – there was a story of this John Henry, who worked on the railroads. During the 19th century in the United States, as in other countries, there were many railroads being built. In the U.S., there were railroads connecting the east part of the United States – the East Coast with the newly growing West Coast, and John Henry worked on one of these railroads. He was what was called a “steel driver.” A “steel driver” is somebody who uses a hammer in order to put in what are called “spikes” (spikes). A “spike” is like a big nail that holds the railroad track together. The “track” is the thing that the train rides on; it’s what you put down on the ground – the “railroad track.”
So, John Henry was a steel driver; he used a hammer to put in rail spikes. But one day, the company that owned the railroad decided to use a “mechanical hammer,” a hammer that was powered, or that was fueled, by steam. Of course, modern technology was improving in the 19th century, and there were many more of these machines that were doing the job that men and women used to do.
Well, John Henry decided to challenge the inventor of this steam-powered hammer to a contest, and so the contest was to see who could drive in the most spikes – who could be most efficient: the man, John Henry, or the machine. At the end of the story, John Henry wins the contest. He beats the machine, however right after he dies, probably because of the hard work it took to participate in this contest against a machine.
So, what is the story here? Well, many people see John Henry as a symbol of the working class. The term “working class” refers to people who do manual labor, that is, they use their hands in order to finish their job. Most of us, in modern economies, sit at a desk with a computer. But doing manual labor would be actually going out, using your muscles, and accomplishing your work that way.
So, John Henry is a symbol of the working class, specifically the African American working class of the 19th century, and he’s also a symbol of this conflict between the new technology and the traditional working class. New technology brings many advantages economically, but it can also displace workers. “To displace” (displace) means that you replace one thing with another thing, usually involuntarily. That is, the person didn’t want to leave, but they were forced to leave because something else came in to replace them. So these “displaced workers,” we might call them, had as their hero, in some ways, John Henry. But of course, since John Henry dies at the end of the story, it’s hard to say exactly that he is the winner. In fact, eventually the workers were replaced by machines.
John Henry is similar to other folk heroes in American “mythology,” you could call it. Paul Bunyan, for example, is a very similar kind of mythical folk hero. Paul Bunyan’s strength – his talent – was chopping down trees. “To chop down a tree” is to take an “axe,” something that is a tool that has a sharp metal edge, and you hit the axe against the tree removing the wood, and eventually the tree will fall down. But eventually, the companies that made money cutting down the trees invented a mechanical saw. A “saw” (saw) is another way of cutting down a tree; it is a long, sharp tool that you move back and forth against the wood. This mechanical saw was like the steam-powered hammer in the John Henry story, a representation of the new technology.
So, all of these big men – all of these folk heroes represent different groups in different parts of the country during the 19th century, and now these stories are taught in schools. Children learn about John Henry and Paul Bunyan; they learn about this nice story, but underneath the story – at the base of the story is this struggle – this conflict, this fight between the working class and new technology, and what happens when new technology displaces workers.
Our second topic is the City of Anchorage, Alaska. Alaska, you may know, is the northernmost state in the United States. It is next to Canada, in between Canada and Russia. The land that we now call Alaska was once part of Russia, but in 1867 Russia sold Alaska to the United States for about seven million dollars.
The person who was responsible in the U.S. government for this sale, the Secretary of State, was named William Seward, and because many people thought that this was a silly or stupid thing to do, because at the time Alaska was just mostly ice and mountains, they called it “Seward’s Folly.” A “folly” (folly) is an older word meaning a stupid thing to do, not very intelligent action.
Alaska became part of the United States in 1867, and in 1888, about 20 years later, gold was discovered in Alaska, and suddenly people became interested in going to Alaska. In 1912, Alaska became a U.S. territory.
Anchorage was one of the first cities that was built in Alaska after it became a territory. President Woodrow Wilson decided to build a railroad in Alaska – we were just talking about John Henry and the railroad. Wilson wanted to build a railroad that would connect different parts of Alaska, and so he helped found and plan this city – or at least the U.S. government did – of Anchorage.
Anchorage is currently the largest city in Alaska, but it’s not very big. Only about 280,000 people live in Alaska – compare that to Los Angeles, which has about three million people – but half of the population of Alaska lives in or near Anchorage. So, if you go to Alaska you will definitely go to Anchorage. Even if you are going to the interior of Alaska, away from the coast – away from the Pacific coast of Alaska, you will still probably go through Anchorage.
The biggest change in Anchorage and in Alaska after it became a state in 1959, our 49th state, was the discovery of oil in 1968. Oil in Alaska increased the population of the state, especially after 1974 when it was decided to build something called the “Trans-Alaska Pipeline System,” and this “pipeline,” this long series of tubes would take oil from where it was discovered down to different parts of Alaska to transport it to ships and so forth.
Well, there was a huge what we would call “economic boon” (boon) in Alaska in the mid-1970s. A “boon” is when the economy suddenly increases very quickly, or a particular industry – a particular kind of work increases quickly, becomes more popular – a lot of people are making money on it. You could talk about the Internet boon of the late 1990s, or the dot com boon. Well, this was a oil boon, and I remember, as a child in the 1970s, hearing about all of the jobs in Alaska, that you could get a really good job working on this pipeline – sort of like working on the railroads – if you moved to Alaska, and many people did move to Alaska in order to work on this pipeline. Today, there is a similar oil boon taking place in the Province of Alberta, Canada; it’s a very similar thing.
Well, if you go to Alaska, what will you see? Most people visit Alaska not because of buildings or museums, but because of what we would call “nature.” The one area that you’ll want to see if you go to Anchorage is Prince William Sound. I should say I have never been to Alaska myself, but would like to go someday, so if you go, stop in Los Angeles and take me with you!
A “sound,” of course, means a noise, but when we talk about geography a “sound” is an area of water, usually that has a very deep bay (bay). The “bay” is an area right next to land, where the water meets the land, for example in the Atlantic or the Pacific Ocean. Here in Los Angeles, we have the Santa Monica Bay. It’s the area of water next to the land, usually there’s like a semi-circle in the land, where it goes in. So, the land goes in, and the water is there; this is also sometimes called an “inlet.” A “sound” is when you have one of these inlets – one of these deep bays. In Washington, there is something called the Puget Sound, and in Alaska there is the Prince William Sound, and in this sound – in this area, you can see lots of animals. You can see beautiful scenery of glaciers; “scenery” just means nice things to look at, “glaciers” are large areas of ice that you would find in a place like Alaska. So, if you go to Anchorage, be sure to go to the Prince William Sound, and enjoy the nature – the scenery – of our 49th state.
Now let’s answer a few of your questions.
Our first question comes from Bianca (Bianca) and Wolf (Wolf); both of them are from the State of Bavaria in Germany. Bianca and Wolf want to know the meaning for a couple of expressions that they heard. The first one is “you might as well,” the second one is “to hit the ground running.”
“You might as well” is when you are going to do something, but you’re not sure it will be successful. Or perhaps, you don’t feel like doing it, you don’t think it will work, or even there’s no reason to do it. For example: “I tried to teach her by phone and email, so I might as well try sending her a letter.” You see, I’ve failed in the past; I don’t think that sending her a letter will really help, but I say, “I might as well.” It’s almost like saying I have nothing to lose, there’s no reason not to, but it probably won’t work. You could also say, “I’ve planned on driving through Los Angeles on my way to San Francisco. But, I might as well stop and see some sights.” Again, here it’s a little different; it’s not a matter of success, it’s a matter of “well, I have the opportunity, it won’t cost me anything extra.” So, it can be used in those different ways. “You might as well tell me where your sister lives, because I’m going to find her anyway.” In that example, what you’re saying is it doesn’t make any sense for you not to tell me; it’s inevitable that I will find out the information myself.
The expression “to hit the ground running” means to start something new with a lot of energy, to get a fast start on something. “I started my new job today. It was so busy, I had to hit the ground running and had no time to get any training.” Or, “She decided to study to become a doctor last year. She hit the ground running by applying and getting accepted to three different medical schools.” “She hit the ground running” – she started strong and was successful.
Our next question comes, next door in France, from Laurent (Laurent). The question has to do with the name of our show, the English Café. It’s a French word, “café,” so why don’t we say “English Coffee?”
Well, in English we often take words and change the meaning, or provide a slightly different meaning. In the U.S., we talk about a café referring to a place where people go and buy coffee, tea, and other drinks. It’s also place to go and relax. It’s not that different from the cafés in Paris, where people go and talk and relax. Starbucks Coffee, for example, is an international company that has many of these cafés around the world.
We don’t use the word “coffee shop.” “Coffee shop” would mean something a little different in American English. A “coffee shop” is a place that has a place for you to sit and eat. Usually the shop has a number of “booths,” which are long plastic seats on either side of a table. There’s also, in a coffee shop, usually what we call a “counter,” and this is a place for people to eat, where you are facing the cook or the people who work there. It’s a long, narrow place where you can sit and eat. Coffee shops are places where you can eat cheap food, not expensive.
So, we don’t say “English Coffee,” or “English Coffee Shop,” we say “English Café.” And, another reason is because Americans think the French language is more sophisticated, and so using “café” makes it sound a little more sophisticated. If you’ve listened, you know we’re not, but we like to sound that way! The idea is that you can listen and relax, just like you might in a café, talking to friends or drinking coffee.
Finally, Mirzega (Mirzega) from the Russian Federation wants to know the meaning of two expressions: “what goes around comes around” and “breaking news.”
“What goes around comes around” means what you do to other people will be done to you in the future. So, if you act towards someone else very badly or treat someone very badly, someday people will treat you badly, too. In general, something that is “going around,” is something that is spreading, something that is moving. “To come around” means to return, so the way you treat other people is the way that you may end up being treated. Especially we use this expression if you are talking about treating someone badly. There’s another expression, “do unto others as you would have them do unto you.” That’s an older expression, with that word “unto,” it just means “to” – “do to others as you would want them to do to you” – treat them the same, in other words.
“Breaking news” is the most recent news, something that is happening right now. This is often a term you’ll see on the television or listening to the radio when there is an important event: an emergency, a crisis, or some important news has just been discovered. They’ll say, “This is breaking news: actor Brad Pitt and Angelina Jolie are getting a divorce.” Call me, Angelina!
If you have a question or comment, email us at eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational Development.
Glossary
folk hero – a famous person, real or imaginary, who is admired and respected for what he or she has done and who is referenced in many popular, traditional songs and stories
* Johnny Appleseed is an American folk hero who introduced the apple to the U.S. Midwest.
spike – a large, heavy, pointed piece of metal that is used to hold metal and wooden pieces together when building a road for a train
* He spent the summer driving railroad spikes and now he has very strong arm and back muscles.
railroad track – a road for a train; the long pieces of metal that a train’s wheels move on top of
* My mother taught me to look both ways for trains before crossing the railroad tracks.
hammer – a tool with a wooden handle and a large metal piece on top with a flat end, used for hitting nails, spikes, and other objects
* Sandra was trying to hang a picture on the wall, but when she swung the hammer she missed the nail and hit her finger instead.
working class – a group of people who do not have very much money or social power and work in difficult, physical jobs
* People who work in factories and mines are considered to be part of the working class.
to displace – to replace; to take the place of something or someone else; to make something or someone else move so that one can have its spot
* Many poor families in Washington, D.C. are being displaced by rich families as housing becomes more expensive.
to chop down – to cut something, especially a tree, so that it falls to the ground
* The neighbors are going to chop down all their trees because they want more sunlight to come in through their windows.
axe – a tool with a wooden handle and a large metal piece on top that has one sharp edge, used to cut pieces of wood into smaller pieces
* Mr. Punkay wants to borrow our axe to cut some firewood.
folly – something silly and/or stupid that is done without thinking about it very much ahead of time
* It would be a folly to sell your car for just $2,000. It’s worth at least $5,500.
boon – something that makes one’s life easier; something that is very helpful and useful
* The development of the Internet was a boon to the computer industry.
sound – a narrow body of water that connects two larger bodies of water; a strait
* Have you ever visited Vineyard Sound in Massachusetts?
coffee shop – a small restaurant that serves coffee, snacks, and possibly small meals, often with comfortable furniture
* I heard that this city has more coffee shops than any other city in the United States.
(one) might as well (do something) – an informal phrase used to mean that one should do something because it isn’t difficult or expensive, it can’t hurt, and it might help
* I might as well apply for the job, even though I don’t think I’ll get it. The worst that can happen is that they’ll say “no.”
to hit the ground running – to start a new activity by working very hard and quickly, without first starting slowly and then gradually increasing one’s speed
* The new employee hit the ground running, staying at the office until 8:30 p.m. every day during her first week on the job.
what goes around comes around – a phrase meaning that one gets what one gives: if one does something bad/good, then one receives something bad/good
* Khuu always gives money to poor people on the street because he believes that what goes around comes around, and he hopes that if he doesn’t have money someday in the future, other people will help him.
breaking news – the most recent news; news that is happening at the moment
* During the forest fires, everyone listened to the radio to hear the breaking news about which roads were open and which neighborhoods were in danger.
What Insiders Know
Songs about John Henry
John Henry was a folk hero who was very good at hammering railroad spikes, and when machines began to do the work instead of people, he had a “contest” (a competition to see who is better at doing something) against the machine. He won, but died immediately after the contest.
Many songs have been written about John Henry. Here are some of the “lyrics” (the words sung in a song) to one popular song called John Henry, Steel Driving Man:
John Henry was a railroad man,
He worked from six 'till five,
"Raise them up bullies and let them drop down,
I'll beat you to the bottom or die."
John Henry said to his captain:
"You are nothing but a common man,
Before that steam drill shall “beat me down” (do something better than me)
I'll die with my hammer in my hand."
John Henry's captain came to him
With fifty dollars in his hand,
He laid his hand on his shoulder and said:
"This belongs to a steel driving man."
John Henry was hammering on the right side,
The big steam “drill” (a machine for making holes) on the left,
Before that steam drill could beat him down,
He hammered his fool self to death.
John Henry was lying on his death bed,
He turned over on his side,
And these were the last words John Henry said,
"Bring me a cool drink of water before I die."