= 1409
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 104.
This is ESL Podcast’s English Café episode 104. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. You can also visit our ESL Podcast Store, which has some business and personal English courses you may be interested in.
In this Café we’re going to talk about the city of Nashville and something called the “Grand Ole Opry.” We’re also going to talk about fundraisers at American schools, what they are and why some people don’t like them. And as always, we’ll answer a few of your questions. Let’s get started.
Today we’re going to talk about the city of Nashville. Nashville is in the state of Tennessee, which is in the eastern part of the United States, sort of in the center of the country. Nashville is the capital of the state of Tennessee. It is not the biggest city in Tennessee however; that would be the city of Memphis.
Nashville is a medium-sized city, about 600,000 people or so. It is famous in the U.S. for being the home of country music. “Country music” is a traditional kind of American music. Many people associate country music with the western part of the United States. Country music is very popular in the southern states, states such as Tennessee, as well as in some western states, but there are country music fans all over the United States. For more information on country music, go back and listen to English Café number 39 from June of 2006, we talk about country music there.
Nashville is the home to the Country Music Hall of Fame. A “Hall (hall) of Fame” is usually a place where the best people of some field or area are recognized. There is a Rock and Roll Hall of Fame in Cleveland, Ohio. There are Halls of Fame for most professional sports, so if you like baseball, you can go to Cooperstown, New York, for the Baseball Hall of Fame.
People are selected to become members of the Hall of Fame if they are very good at what they do. The word we would use would be “inducted.” To be “inducted” (inducted) means to be made a member of, usually a member of an organization, or in this case, the Hall of Fame.
Another famous thing that most Americans know about Nashville is something called the “Grand Ole Opry.” “The Grand Ole (ole) Opry (opry)” is a weekly country music radio program. This program began back in 1925, so it is very old, from the very early days of radio. And each week on the Grand Ole Opry they have a country music program that you can listen to. The singers come and sing live and it is broadcast on the radio.
I should explain that the word “ole” (ole) is a word that means “old.” It’s an old word that means “old,” you will sometimes find it in Old English – English from the 17th or 18th centuries. The word “opry” is a dialectical pronunciation for “opera” (opera). When I say it’s a dialectical or a dialect pronunciation, I mean that it is a pronunciation in a certain region, in this case, in the southern region of the United States. However, most people don’t say “opry” when they mean “opera.” “Opry” now is associated almost exclusively with this radio program, the Grand Ole Opry.
The Grand Ole Opry has had most of the famous country singers perform at its show, or in its show. Back in 1954, a young teenager by the name of Elvis Presley performed at the Grand Ole Opry. Unfortunately, the manager of the Opry didn’t like Elvis Presley’s singing; he told Elvis that he should go back to Memphis and drive a truck. In other words, stop his singing career. Of course, he was wrong about that! But Elvis never went back to the Grand Ole Opry after that.
Finally, some people, when they hear about Nashville, may think about a movie that was made back in the 1975 by a famous American film director, Robert Altman, who died recently. The movie was called Nashville, and it was about, in part – or partly – the music business in Nashville. So, if you want to become famous and be a well-known country singer, don’t come to Hollywood, don’t go to New York, go to Nashville!
Our second topic today has to do with something related to schools in the United States; they’re called “fund-raisers.” A “fund-raiser” (fund-raiser) comes from two words, to “fund” something means to give money to something. The noun “funds” is often used in business to refer to an amount of money. “I have no funds in my checking account” – I have no money in my checking account. I have a little money, but not a lot! Notice also that as a noun “funds” is always plural, with an “s” at the end when it means money. The verb is to “fund.” To “raise money,” or to “raise funds,” means to get money usually for some organization, often a school or another charitable group – a group that is not a business but that is designed to help other people, so you have a “fund-raiser.”
In American schools fund-raisers are very popular, both in private schools and in public schools. This sometimes surprises people about the American education system. When they come here, they find out the children and parents are asked to participate in fund-raisers.
There are a number of popular kinds of fund-raisers that you will see in American schools; I’m talking mostly here about grade schools and high schools. One of them is a raffle. A “raffle” (raffle) is when you sell tickets to win something. So you have a car, and you sell tickets for $1 each. You pick one of the tickets to win the prize, in this case, the car. So, raffle tickets are very popular kinds of fund-raisers. What will happen is the children will be given some tickets and told to go and sell the tickets, and, of course, bring the money back to the school.
Many parents have complained about these fund-raisers; we might say they have “grown weary” of the fund-raisers. To “grow weary” (weary) means to grow tired, to become tired. Many parents think these fund-raisers are too much work. Many public school parents – schools that are supported by the government – think that the government should pay for things, that the students and parents should not have to go out and get money for the school.
Usually fund-raisers are for organizations in the school. So for example, if the school has a marching band – a musical group that performs at football games and other events of the school – they may have a fund-raiser, they may have a raffle. Sometimes schools will have car washes, where the students come together and they will wash your car, and the school gets the money from that fund-raiser.
Another popular fund-raiser is to sell candy. This, of course, is not a very good way of demonstrating healthy eating to children. Candy fund-raisers were very popular when I was in school. Perhaps the most famous type of fund-raiser involving food are Girl Scout cookies. The Girl Scout organization – which is an organization for young girls to give them the opportunity to work with each other on different experiences – the Girl Scout organization every year has a Girl Scout cookie sale where the girls go around and they will knock on the door of different houses and sell the cookies.
Here, where I live, at least once a week we have someone coming to our door of our house, knocking on the door trying to sell candy or cookies for their school or other community organization. When I was in high school, every year we had a candy sale, and we had to sell two or three boxes of candy bars. So as students, we would go out after school and knock on doors and ask people to buy the candy to support our school.
Many parents are trying to do away with these fund-raisers. When I say “to do away with something,” I mean they are trying to eliminate. Another way we may say that is “to get rid (rid) of,” it means to eliminate, to no longer have something. They consider the fund-raisers to be too, we may say, burdensome. “Burdensome” (burdensome) comes from the word “burden,” which means a difficulty, a problem – usually something that makes your life more difficult, makes your life more stressful. A “burden” is a heavy responsibility; we might use the word “load” (load). “It’s a heavy load” – it’s a heavy responsibility. So, “burdensome” means something that causes problems, makes your life difficult.
Still, my guess is most schools will continue to have these fund-raisers, and consider them necessary in order to have additional activities for the children at school. Of course, what many parents do is they simply, instead of having their child go out and sell raffle tickets or sell candy to other people, they simply write a check to the school and buy it all themselves. My parents never did that for me; I had to go out and sell my candy.
In our school we had competitions, so that the classroom that sold the most candy would get a certain prize, and it was a very, very big event. Every October – September, October in our school we had this annual candy sale. I think that’s why I probably don’t eat chocolate candy too much anymore. I ate too much when I was in high school. Instead of selling the chocolate, I used to eat it; that’s probably why my school did not make very much money!
Now let’s answer a few of your questions.
Our first question comes from Oleg (Oleg) in Russia. Oleg wants to know the meaning of the phrase “hold on to your hat” (hat).
A “hat” is something you put on your head, on the top of your head to cover it. To “hold on” means to put your hands on something so that something doesn’t move, or you don’t move. To “hold on to your hat,” then, would mean putting your hand on your hat so that it doesn’t, for example, fly away if there is a strong wind – it won’t blow away.
The expression, however, “hold on to your hat,” means get ready for something really surprising. Sometimes it’s a good thing; sometimes it’s a bad thing. “Hold on to your hat” is a way of getting someone’s attention and preparing them for something that is going to be very surprising. For example, if someone says, “Hold on to your hat, because you’re going to love this,” what they’re saying is “get ready because you’re going to love what I’m going to tell you or show you.” Another example would be: “I just recorded a new song for my upcoming CD, “Jeff McQuillan Live.” Hold on to your hat, I’m going to play for you!” It would be very surprising, trust me!
Our next question comes from Poland, from Tomek (Tomek). Tomek has a question about the expression “they put me inside on a one to five.” It is a line from a rock song; I believe a Billy Idol song.
To “put someone inside” means to put someone in prison, to put someone in jail. The expression “one to five” means that the prisoner – the person in jail, the criminal – has to be there from one to five years, depending usually on many things, including how well they act in prison – how well they behave in prison. For example, when I went to prison – oh, no – no, that wasn’t me! Well, the idea is that if someone says they’re going to “put me inside,” they mean they’re going to put me inside the prison.
Finally, Robert (Robert) in Indonesia wants to know the meaning of the expression “a blow-by-blow account.”
An “account,” in this case, means a description of something. The expression “blow-by-blow” would mean a very detailed description, describing everything that happened in order that it happened – or in the order that it happened. It’s actually one of the many sports idioms in American English. It comes from boxing, where two people stand in front of each other and try to hit each other. A “blow” is a hit, when one of the boxers punches – takes his hand and hits the other person, that’s to “punch.” When one of the boxers punches the other person, that’s sometimes called a “blow.” So a “blow-by-blow description,” or a “blow-by-blow account,” means a very detailed account – a very detailed description of something.
If you have a question or comment about something in English you don’t understand, you can email us. Our email address is eslpod@eslpod.com. We can’t answer everyone’s questions, but we’ll do our best to answer many of them on our English Café.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2007, by the Center for Educational Development.
Glossary
Hall of Fame – a museum or a list of names honoring the people who have done something very well
* The Pro Football Hall of Fame is in Canton, Ohio and has information about America’s best professional football players.
to be inducted into (a group or organization) – to be accepted into a group; to participate in a ceremony when receiving a new job or position
* The top 10% of the students were inducted into the school’s honor society.
dialect – a form of the language, usually used in a particular area, with differences that include pronunciation, vocabulary, and other things
* In the United States, the dialect spoken by some New Yorkers is very different from the dialect spoken by people in Georgia.
fund-raiser (or fundraiser) – an event that is held to earn money for a project or organization; an event that people pay money to participate in, knowing that the money will be used by a specific group
* The Parent-Teacher Association is selling cookies as a fund-raiser to buy more sports equipment for the school.
funds – money that will be used for a specific purpose; money that can be spent
* The library doesn’t have enough funds to buy new books this year.
raffle – a drawing; a way to earn money for a project or organization, where people buy small pieces of paper with numbers on them, so that the pieces of paper are put in a large container and, if one’s number is chosen, one wins a prize
* Felina bought a $2 ticket in the raffle and won a new TV!
to grow weary – to become tired; to be bored or to have little patience for something
* After 16 hours in the bus, Vicky grew weary of traveling.
to do away with – to destroy or remove something; to stop doing something; to eliminate something
* Yana decided to do way with her long hair and now her hair is shorter than her husband’s.
to get rid of (something) – to do something so that one no longer has or owns something
* Frank gained 20 pounds over the Christmas holiday and now he needs to find a way to get rid of the extra weight.
burdensome – making something more difficult; causing worry or hard work
* Paying high taxes is burdensome for small businesses that are just starting out.
to hold on to (one’s) hat – to get ready for something that will be very exciting, unpredictable, or surprising
* No one knows what’s going to happen today, so hold on to your hat and be ready for anything!
to be put inside – to be placed in a box or another container; informal (slang) – to be put in prison or jail
* If she gets caught driving drunk again, she’ll be put inside for at least a month.
blow-by-blow account – a very detailed telling; something that is told to another person with a lot of detail
* We almost fell asleep when Sheryl started giving us a boring, blow-by-blow account of how she decided which toothbrush to buy.
to punch – to hit someone or something with one’s fist (closed hand) very hard
* The little boy punched his friend in the stomach for no reason.
What Insiders Know
Hee Haw
In the 1980s, Hee Haw was a television “variety show” (a show that has many “acts” (types of performances) with a lot of music and comedy). “Hee haw” is the sound that a “donkey” (a small, strong animal similar to a horse) makes. Hee Haw had a lot of “country music” (American music popular in especially in the West and South) and Southern humor.
Like other variety shows, Hee Haw “consisted of” (was made up of) many “segments” (parts). One segment was Pickin’ and Grinnin’, where “picking” means moving strings to make music on a guitar, and “grinning” means smiling. In this segment, two men had a “duet” (music played by two people), playing a banjo and guitar while singing and telling jokes. Another segment was Sample Sales where a “used car salesman” (a man who tries to sell used cars, usually that aren’t very good) tried to sell a “clunker” (a car that doesn’t work well).
In The Gossip Girls, women sang while washing clothes. “To gossip” means to say bad things about other people when they aren’t there. In this segment, the women would sing a song with a different “verse” (4-6 lines of words in a song) each time, but always end in the same way:
No, you'll never hear one of us repeating gossip,
So you'd better be sure and listen close the first time!"
In Archie’s Barber Shop, men would share funny stories and jokes in a “barber shop” (where men get their hair cut). In The Fence, an actor would stand in front of a “fence” (a wooden wall that separates two outdoor areas) and tell a short joke. When he or she is finished, part of the fence would move and hit the person’s “rear end” (the part of one’s body below one’s back and above one’s legs).