= 1450
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 145.
This is English as a Second Language Podcast’s English Café number 145. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. While you’re there, you can download this episode’s Learning Guide, an 8 to 10 page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog, where several times a week we provide even more help in helping you improve your English.
On this Café, we’re going to talk about Advanced Placement courses and tests, what they are and who takes them in the United States. Then we’ll turn to the topic of children’s toys, talking specifically about Legos, Legoland, and my favorite, Hot Wheels. As always, we’ll answer a few of your questions as well. Let’s get started.
Our first topic on today’s Café is something called “Advanced Placement” courses and tests. “Placement” refers to how or where you put something or someone. Normally, you take a test, and based on the results of that test, you are placed at a certain level, for example in a language classroom. Advanced Placement is a specific program that lets students in the U.S. and Canada take college-level courses while they are still in high school. Now, I say college-level, they are still usually taught by high school teachers, but they cover some of the same information that you might get in a college class on that topic. In other words, the classes place students in courses that are more difficult, more advanced than the courses in the typical high school. We say these courses are more advanced – they’re more difficult.
Many schools, perhaps even most high schools, offer Advanced Placement, which we usually call simply “AP” classes. These AP courses are, as I said, usually more challenging, or difficult, than regular high school courses. There are more than 30 AP “subject areas,” that is, topics that students can study and then be tested on. Most high schools, however, only offer a very small number of AP classes. English, history, biology, calculus, and, perhaps, Spanish are the most common AP courses in American high schools. Some of the less common subject areas include art history and Latin. I say most high schools offer these courses, but not all. My high school did not have any AP courses, so it depends on the school that you attend.
High school students who take these AP courses have to study for an exam that takes place at the end of the year. We might say they have to “gear up for” an exam. To “gear up for” something is a phrasal verb, which means to get ready for something. We sometimes will gear up for the holidays – Christmas, Chanukah, or New Years – by buying gifts for our family and friends. AP students gear up for the AP exam by studying a lot. Now, you don’t have to take an AP course to take the AP exam, but it is helpful to have that entire year to prepare for the exam under a teacher’s supervision, or guidance.
AP exams are usually given in the spring of each year. Students have to pay a fee to take the exam. A “fee” is the amount of money you pay to do something. When I was younger and single, I had a gym membership. I would go to the gym every week – not to exercise, just to meet girls! I had to pay a fee every month. The fee for the AP exam is currently about 80 dollars, but it is possible, if you don’t have a lot of money – if you are what we may call a “low-income” student – to get “financial aid,” meaning that they don’t have to pay as much. “Aid” is another word for assistance. So, “financial aid” is help.
The AP exam, itself, is created by The Educational Testing Service, which is a private organization – a company – that creates and grades the TOEFL test, the Test of Spoken English, many different standardized tests, the SAT test, and the AP exams.
More than one million American and Canadian students took the AP exams back in 2006, and many of them took more than one AP exam. Now, you may be asking, well, why should students study and take this exam – this test? The reason is that in many places they can get college credit if they do well on the exams. At a university, students earn “credit” each time they complete a course successfully. Some courses may be three credits; some may be four credits; some may be five credits. Students need a certain number of credits to graduate from college. If a high school student does well on the AP exam, he or she can get college credit for that subject area. For example, if a student does very well on the AP biology exam, he or she can get college credit for biology. This helps the student save money, because the 80-dollar AP exam fee is much less expensive than paying for the complete biology course at the university. So, what it allows students to do is to get credit for classes, but they don’t have to take the class again when they get to the university. Students who takes a lot of AP exams and earn a lot of college credit can actually graduate earlier from a university, because he or she will have the required number of credits more quickly than other students.
AP exams are graded on a numerical scale – a system of numbers – from one to five, with five being the highest possible score. Usually students can get college credit from most universities if they get a four or five on the AP exam. Sometimes universities give credits for a score of three, too; it depends on the university. If a student gets a lower score, then they don’t get any credit and will probably need to take that class again in college in order to get college credit.
Many people have criticized AP exams because they tend to focus students on just studying for the test, rather than learning more about the subject. As you probably know, doing well on an exam doesn’t necessarily mean that you have a very deep or rich knowledge of a topic; you can study things just to pass the exam. Many people are now criticizing these AP courses because they don’t necessarily give students the same level of education as a regular college-level course, because they are so focused on, or worried about, passing the exam itself.
Now let’s turn from AP courses to children’s toys, specifically Legos and Hot Wheels. Most American children know about these two kinds of toys. Legos are colorful plastic toys that are used to build things. They are made by a Danish company – a company from the country of Denmark – but they have a very popular following; many people in the United States like this toy. Really, this began 50 or 60 years ago. The small plastic pieces – the Legos – are “interlocking,” meaning they can be put together so that they hold onto each other. The pieces are easy to put together and take apart again, but they are also strong enough, when you do put them together, to be able to build small things. Legos are sort of like bricks or stone in a building or a house. You can build a house from bricks, one brick on top of the other, and you can create a house. With Legos, you take these little pieces of plastic and you can make something from them.
Legos are, and have been, very popular in Europe and the United States for many years. In fact, the company that makes Legos makes about 20 billion pieces each year! A typical, or normal, Lego is a rectangular piece of plastic that has some small raised circles on top of it that fit into the bottom of another Lego piece. Over time, Legos have become “fancier,” or more detailed – more interesting. Basic Lego pieces are rectangular blocks, but now there are also Lego pieces that are made to look like people, trees, wheels, and other things.
There are many Lego kits for building special things – special items. A “kit” (kit) is a group of pieces that are sold together for a special purpose. For example, there are Lego kits to build ships, cars, castles, and other things. Some of these Lego kits even have motors to make the different parts move.
Legos were designed for children, but there are many adults who enjoy building things with Legos. Some people use Legos to build very large, or relatively large structures, or buildings, and there are even theme parks based around Legos. A “theme park” is a large area with many rides that are based on a single idea. Perhaps the most famous theme park is Disneyland – Disney World, Euro Disney, and so forth. The Lego theme parks are known as Legoland. There are several Legolands in Europe, and there is one here in California, in Southern California. Legoland visitors can go on different rides that are built around these large Lego structures, like dinosaurs, animals, buildings, even an entire city! Visitors can also relax and watch professionals, people who get paid to build Lego structures.
There are clubs for adults who like to build things with Legos, also. They often meet to build one of these structures. There are online clubs, where you can go to websites to share pictures of your Lego project. Some of them are very large and very “impressive,” meaning that you would feel surprised in a good way. January 28, 2008 was the 50th anniversary of the first Lego. The company celebrated the anniversary with a building contest, and people participated from all over the world. You can also see photos of what they built on many websites.
Another popular toy, one that I used to play with when I was a kid, is Hot Wheels. I never had Legos growing up – I don’t remember them, anyway – but we did have Hot Wheels. Hot Wheels are miniature, or very small, cars and trucks made from plastic and/or metal. Sometimes they’re plastic plus metal. Hot Wheels are designed to look just like the real cars and trucks that they “replicate,” or copy. The wheels move, so that the cars can be raced against each other. Hot Wheels makes not only cars, but also tracks for those cars. A “track” is a path for a car to follow, usually in a circle or an oval shape. Often children play by putting their cars on Hot Wheels tracks and seeing which one is fastest. When we were growing up, my brothers and I, we used to build Hot Wheels racecourses in our basement, back in Minnesota, and we would take many different tracks, and it would be very long and complicated. We’d spend hours building these tracks and then racing the little cars on them. I grew up in a very competitive family; we always had competitions and games where we would play each other to win.
More than 40 million children have played with Hot Wheels, many of these children end up collecting them. To “collect” means to buy and keep many different kinds of things. Some people collect coins, stamps; here in the United States, some people collect “baseball cards,” cards with pictures of baseball players on them. Many children, and even some adults, collect Hot Wheels cars. Some of the older models, or types of cars, are now very valuable and can be sold for a lot of money. Collectors often participate in Hot Wheels “conventions,” or big meetings where they get together and they look at their cars, and they buy new cars, and so forth.
Both Legos and Hot Wheels are more popular among boys than girls, I think, at least when I was growing up. But children of both sexes – of both genders – play with them at times. Almost all Americans are familiar with these toys and you can probably find them in any child’s “toy box,” or place where children keep their toys when they aren’t playing with them. I don’t have any collections of Legos or Hot Wheels, but there are adults who we would say “get into” that, meaning they get interested in it.
Now let’s answer some of the questions that you’ve sent us.
Our first question comes from Tiago (Tiago) in Brazil. Tiago wants to know the difference between the words “might” and “maybe,” and when we use each of these.
Both “might” and “maybe” are used to express the possibility of something happening. This could be in the past, this could be in the present, or this could be in the future. You can say, “Maybe I made a mistake by asking that girl to dance because she didn’t really like me.” Maybe I made a mistake – past. “Maybe I am making a mistake right now by working instead of relaxing.” “Maybe I’ll go to the store this afternoon” – that would be a future use.
You can use “might” in the present and the future. You can say, “I might be drinking too much water today.” That would be the present. Or, you could say, “He might be going to the store tomorrow.” That would be a future idea. So, “maybe” can be used in the past, present, or the future. “Might” can be used in the present or the future, and they both mean the same thing.
You can also say “might” in the past, but it’s a special case involving “have.” For example: “He might have gotten lost.” You could also say, “Maybe he got lost.” So, “might have” is a possible way of using “might” in the past tense, but it’s always going to be plus what we would call the “past participle.” “He might have flown on an airplane yesterday” – I don’t know, but he “might have” done that.
You can also use the word “may” to express possibility in ways that are very similar to “might” and “maybe”: “Mr. Sanchez may have gotten lost on his way home from the store.” “She may be buying a new dress right now.” “Joseph may show up to the party tomorrow.” All of these mean the same as “might” or “maybe.”
Our second question comes from Zhenhua (Zhenhua) in China. The question has to do with the expression – two expressions, really – “judgment call” and “no-brainer.”
A “judgment call” is a decision about something that doesn’t have a clear answer. The word “call,” here, means decision, so a “judgment call” is a somewhat difficult decision that is often based on your own opinion or belief or background. It’s when you have a situation where there isn’t one clear, logical choice: “The manager made a bad judgment call by firing the employee without talking to his supervisor.”
A “no-brainer” is an easy decision, something that is very easy to decide: “One plus one is a no-brainer for a college student.” A college student should know how to add one plus one – so should a second-grader! “Knowing that your wife would be mad at you for forgetting her birthday is a no-brainer.” In other words, anyone knows the answer; anyone knows that your wife would be mad at you if you forgot her birthday. “Taking the job with the best pay and the best work conditions is a no-brainer.” It’s obvious; it’s logical. You don’t even have to think about it. You don’t have to use your brain, that’s why the expression is “no-brainer.”
If you have a question, even a no-brainer, you can email us. Our email address is eslpod@eslpod.com. We can’t answer everyone’s question, but we’ll do the best we can to answer as many as we can here on the Café.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational
Development.
Glossary
placement – how and where you put something or someone, often according to type of level of skill
* The music students each played one song for the director and hoped for a placement in the advanced class.
college-level – something that has a similar difficulty level as things taught or done in colleges or universities
* Janie was able to do college-level math while she was in elementary school!
subject area – topics that are studied in school, such as math, science, history, and music
* The new teacher our school hired can teach courses in three different subject areas.
to gear up for (something) – to prepare for something or to get ready for something
* The fans are gearing up for the big football game this weekend by buying team T-shirts to wear to the game.
financial aid – money received from the government or another source to help students pay for school fees
* Without financial aid, Steven will have to stop going to school next year.
college credit – points toward graduation a student receives at a college or university each time they successfully complete a course
* Three of my students got college credit by completing a special summer study program.
interlocking – pieces that can be put together so that they hold onto each other and do not come apart; pieces made to fit together so that they can be combined
* These floor mats are interlocking so that they won’t come apart when people walk on them.
kit – a group of things that are packaged or sold together for a special purpose
* I want to build my own boat. Do you think I can buy a kit?
theme park – a large area with many rides that are based around a single idea
* On our vacation to Florida, we spent three days at the theme park and had a lot of fun!
replicate – copy; something made to look like the original
* I bought this Rolex watch on the street for 10 dollars. Do you think it’s real or a replicate?
track – a path for a person or a car to follow, usually in a circle or oval shape
* All four cars drove onto the track right before the race began.
to collect – to buy and keep many different kinds of something
* Katrina began collecting paintings by her favorite artist and now has eight of them.
maybe – perhaps; might; possibility of something happening
* Maybe it will rain today and I’ll have to walk home in the rain.
might – perhaps; maybe; possibility of something happening
* Dan said that he might be late to our party because he has a lot to finish before he can leave work.
judgment call – a decision that does not have a clear answer; a personal opinion based on one’s own beliefs, knowledge, and wisdom
* I don’t know if we should expand our company this year or not. It’s a judgment call.
no-brainer – an easy decision; something easy to do; common sense
* It’s a no-brainer to tell your wife “no” when she asks you, “Do I look fat in this dress?”
What Insiders Know
The Advance Placement Subject Exams
Many students in American schools take Advanced Placement examinations each May. The exams have multiple-choice questions, which are questions with several possible answers and the students select the correct one. The exams also ask free-response questions. The “free-response” questions require that students write an “essay” (narrative; explanation) or solve a problem. The test for Studio Art, which includes painting, drawing, and sculpture, requires that students submit a “portfolio,” which is an organized collection of their work. The free-response answers and portfolios are judged by university and advance placement teachers, who are trained to “evaluate” (judge) them.
Here are the subjects with Advance Placement Subject Exams:
Art History
Biology
Calculus AB
Calculus BC
Chemistry
Chinese Language and Culture
Computer Science A
Computer Science AB
Macroeconomics
Microeconomics
English Language
English Literature
Environmental Science
European History
French Language
French Literature
German Language
Comp Government & Politics
U.S. Government & Politics
Human Geography
Italian Language and Culture
Japanese Language and Culture
Latin Literature
Latin: Vergil
Music Theory
Physics B
Physics C
Psychology
Spanish Language
Spanish Literature
Statistics
Studio Art
U.S. History
World History