= 1429
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast's English Café number 124.
This is ESL Podcast's English Café episode one-two-four (124). I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the beautiful City of Los Angeles, California.
Remember to visit our website at eslpod.com. You'll find our ESL Podcast Store, which contains several premium courses on business and personal English I think you'll be interested in. You can also take a look at our ESL Podcast Blog, where we help you learn English throughout the week with some additional information, cultural and otherwise.
On this Café, we're going to talk about the great City of New Orleans, Louisiana, sometimes pronounced “New Orleans” or “New Orleans.” We're going to talk about this city and its importance in the United States. We're also going to talk about the 9-1-1 system – the emergency system in the United States, what it is, and how it got started. And, as always, we'll answer a few of your questions. Let's get started.
Our first topic is the City of New Orleans, in the State of Louisiana. Louisiana is located in the southern central part of the United States; it is on the Gulf of Mexico of the Atlantic Ocean. Louisiana is where the great river that divides United States, the Mississippi River, ends. It ends in the City of New Orleans. New Orleans is a “port” city, that is, it's a city where ships – boats – come, that is on the ocean. It is the largest city in the State of Louisiana.
New Orleans is an interesting city for several reasons. First, Louisiana is an area that was originally “settled,” that is, originally lived in after the Europeans came to what is now the United States, by the French, and Louisiana has still some influences of French language and culture. New Orleans, in particular, has been very influenced by French language and French customs. The City of New Orleans was named after the Duke of Orleans, although that's not how it would be said in French.
It is one of the oldest cities in the United States; it was “founded,” that is, it was started in 1718. It was, at the time, part of the French territories in the United States. During the middle of the 18th century, about 50 years later, the French colony was actually given to the Spanish. The Spanish controlled New Orleans for 40 years. Eventually, the French got the territory of Louisiana back. Napoleon sold it to the United States in 1803, to then President Thomas Jefferson, in what was called “The Louisiana Purchase,” where a huge part of what is now the United States was bought from the French, from Napoleon.
By the middle of the 19th century, by the 1840s and 50s, New Orleans was one of the richest cities in the United States. It was, as I said, a port city, so there was a lot of trade – a lot of commerce – business that was taking place in New Orleans. New Orleans is also famous for what is called “The Battle of New Orleans,” which took place during the war that the United States had with Great Britain, what we call here in the U.S. “The War of 1812.”
It's interesting to look at who lives in Louisiana, and who lives in New Orleans. The people of Louisiana are sometimes called “Cajun” (Cajun). “Cajun” comes from the word “Acadia.” “Acadia” was a region in what we now know as Canada, where there were a lot of French people living. However, after another war in the mid-18th century, what we call in the U.S. “The French and Indian War,” the British defeated the French, and the French had to leave Canada. Many of those people left this area of Canada called Acadia and they came to French Louisiana, and they began to live there and have their families there. There's still a very strong influence in Louisiana of Cajun culture – of this French influenced culture.
The population of New Orleans is “predominantly,” that is, mostly African American, or black. Almost two-thirds of the population is African American. About 28 percent are white, or Caucasian American. There are smaller percentages of Asian Americans and Hispanic, or Latino, Americans.
New Orleans, as you probably know, was hit by, or had suffered the effects of a great hurricane back in 2005, Hurricane Katrina. The population of New Orleans, before the hurricane, was about 1.4 million in the larger area, what we would call “Greater New Orleans,” meaning New Orleans and the suburbs around it. Many of these people left – most of these people left during that hurricane. There were more than 1,500 people, however, who died in the hurricane. Katrina was a huge disaster for the city; 80 percent of the city was “flooded,” that is, it had water where water should not have been.
Many of the residents of New Orleans returned, about 70 percent. The population now is about 1.2 million, but that's still a loss of over 200,000 people who never went back to New Orleans after the terrible hurricane there. New Orleans is recovering; it is trying to rebound. “To rebound” (rebound) means to recover – to get better after a very difficult situation.
There are still many interesting things to see and visit in New Orleans. I've been to New Orleans twice for academic conferences, and had a chance to the visit the city before Hurricane Katrina. The most famous part of New Orleans is the French influenced parts of the city; the main tourist area is called the “French Quarter.” When we say a “quarter” here, we mean an area or a section of the city, and there's a section in the main part of the city called the French Quarter, which still has the original French and Spanish architecture of the 18th century in it. The French Quarter is famous for many hotels and bars, dance clubs. The most famous street in the French Quarter is called “Bourbon Street.” Bourbon Street was named for the French royal family, and it is also a type of alcohol – a type of liquor, and if you walk down Bourbon Street you will see lots of bars – and lots of people who have drunk too much alcohol, shall we say!
New Orleans also has some beautiful mansions. A “mansion” (mansion) is a large house – a very beautiful house where someone rich lives. My house is not a mansion – my neighbor's house is a mansion, not mine!
If you go to New Orleans, you also want to visit the church – the Catholic Church, Saint Louis Cathedral. There's also a very famous area where you can listen to jazz. “Jazz” is a very famous kind of American music, and many people say that jazz really began with the African American community in New Orleans. You can go to Preservation Hall to listen to jazz music.
New Orleans is famous for two events; one is its Jazz Festival, where many famous jazz musicians go and play each year. It's also famous for something called “Mardi Gras.” “Mardi Gras,” which is the French term that in English would be “Fat Tuesday,” Mardi Gras is the last day of what is called the carnival season. You may be familiar with the carnivals in Brazil, in Rio de Janeiro, which are very famous. Well, in the U.S., the most famous place for these carnivals is in New Orleans. Carnival is a period of celebration before the season of Lent in the Catholic Church. “Lent” is a time of preparation for the great celebration in the Christian religion, which is Easter. Before this, there is a celebration called Carnival, and Mardi Gras is the last day of that celebration, on Tuesday before what is called “Ash Wednesday,” the beginning of the Lenten season.
Many people go to New Orleans during this time; it is a time when there are lots of celebrations, lots of parties, there are parades, people drink way too much alcohol. I have never been to New Orleans during Mardi Gras, but some people enjoy that atmosphere, and it is certainly one of the most famous things that people think of when they think of New Orleans in the United States.
Finally, New Orleans is famous for its food. Cajun food is the local food of the Cajun people who came to New Orleans and Louisiana. This is a food that has traditionally a lot of seafood. If you go to New Orleans, on Bourbon Street you'll see a lot of restaurants that have “crawfish,” which are like tiny lobsters and live in the wetlands of southern Louisiana. Cajun food is often considered “spicy,” that is, if you eat it, it will produce a hot or burning sensation on your tongue, so you have to be careful.
So I hope you will someday have a chance, if you visit the United States, to go to New Orleans. It's still one of the most interesting cities in the U.S., for its music, for its food, for its people, for the things you can see there.
Our second topic today is the emergency telephone system in the United States. If you ever come to the United States and you have an emergency – a medical emergency, you are suddenly sick, or an emergency involving crime, where someone is chasing you, perhaps, or someone is trying to do something bad to you, you would pick up the telephone and you would dial three numbers: 9-1-1. 9-1-1 is the emergency number in almost every place in the United States; every city, state, has a 9-1-1 system.
The 9-1-1 system was created back in the late 1960s. Back then, we had just one telephone company; it was called AT&T. When I was growing up, it was called “Ma Bell.” “Bell Telephone” was another word that was used to describe this company. They created the 9-1-1 emergency system; 9-1-1 is the number you dial, and when you dial it, you are given to what is called an “emergency dispatch center.” A “dispatch center” is a place where you have operators who take your telephone call, ask you what the problem is, and then send either a police officer or, if it's a medical problem, a paramedic. A “paramedic” is someone who is trained in medicine, not a doctor, but who will take you from your house to a hospital. 9-1-1 operators dispatch police and paramedics. “Dispatch,” as a verb, means to send someone to some place.
9-1-1 is only for emergencies; if you're lost or want to know what time it is, you should not call 9-1-1. In fact, if you do, you could actually be charged with a crime. Calling 9-1-1 for any reason other than an emergency is against the law.
9-1-1 is a very useful system. Many people complain, however, that in big cities, such as New York or Los Angeles, the police are very slow to respond; you call 9-1-1 and nothing happens – no one answers the phone. That's not the normal situation however; usually you will get someone who answers the phone to help you. If you are calling from a building or a house, the 9-1-1 operator knows exactly where you are; your address, that is, will appear on their computer screen. If you call from a cell phone they won't know where you are, although the U.S. telephone companies are going to have a system soon where the police will be able to identify you based upon your cell phone call. That isn't quite ready yet.
Although the numbers you dial – you press on your phone, “to dial” is to press numbers on your telephone – is 9-1-1, we never say 9-11. For obvious reasons, 9-11 refers to September 11th now, and events of September 11th, 2001. Before 9-11, the system was always known as 9-1-1; part of the reason is that if you said 9-11, some people, in an emergency, would look for the number 11 on their telephone. That's, at least, the story, and so the police decided that they would advertise it as 9-1-1 so people knew that there's no 11 on your telephone pad. But now we call it 9-1-1, 9-11 refers only to the events of September 11th. It's just a coincidence that they are the same numbers.
Now let's answer a few of your questions.
Our first question comes from Brian (Brian), from a mystery country – I don't know where Brian is from. Brian wants to know the difference between the expressions “you don't need to know it” versus “you need not know it.”
“You don't need to know it” and “you need not know it” mean the same thing. However, “you need not know it” is very old-fashioned – very formal or official. Most people would not say that, or even write that anymore; they would say, simply, “you don't need to know it” – it's not necessary for you to know this thing. But, it is possible to say “you need not know it.”
This expression of “need not (something)” is used in a few cases a little more commonly, for example, “You need not worry yourself about this problem.” That means you don't need to worry about this problem.
Our next question comes from Priscilla (Priscilla) in Hong Kong. Priscilla wants to know the difference between “incident” (incident) and “accident” (accident).
An “incident” is an event – an occurrence, something that happens. It could be a good thing; it could be a bad thing. For example: “Do you remember the incident last year, when the president of our company said everyone was going to get a raise?” – going to get more money. Or, “There was an incident last week, where someone fell on the floor and got hurt.” “Incident” can be positive or negative – good or bad. I would say it's often used, however, for a negative event – something bad that's happened. “There was an incident yesterday” usually means there was some problem – something happened that is not good. But you can use it either for a good or a bad situation.
“Accident” is when you have a bad thing happen – a bad incident – that happens suddenly and unexpectedly. Usually, an accident causes some damage – some injury. For example: “I didn't want to tell Laurie about the surprise birthday party for her. I mentioned it to her, but it was an accident” – I didn't mean to – I didn't want to, but I made a mistake and I told her. Or, “There was a car accident on the street this morning” – some car was damaged this morning.
Finally, J.C., who is also from a mystery country – perhaps the same place that Brian is from – wants to know why we sometimes use the expression “his or her” together as a possessive pronoun. For example: “The customer can put his or her shoes next to the door.”
“His or her” is used because you don't know if the customer is a man or a woman. If you knew it was a woman, you could say, “The customer can put her shoes next to the door,” and you wouldn't need to say “his.” But, when you're not sure, in a lot of modern English writing, people say “his or her.” Now, if you know if it is a man or a woman – a boy or a girl – you can use “his” or “her” separately.
Now, if you look at older writing, or sometimes even modern English writing, sometimes people will say “his” to mean both “his and her.” “The student should finish his degree” – we don't know if the student is a man or a woman, but the automatic answer – what we would call the default answer – in traditional English writing has been to use the possessive pronoun for the man, and that is “his.” However, there many people, especially in the last 30 years, who don't like this practice. They want women to be included, if you will, and so that is where the idea of a “his or her” developed.
Sometimes, however, it can sound a little strange and doesn't work very well. In those cases, you will sometimes hear people use the third person plural possessive pronoun “their.” For example: “A student can study for their first degree after finishing high school.” I could have said “A student can study for his or her first degree after finishing high school.” If I knew the student was a man, I could say “A student can study for his first degree after finishing high school,” or, if you are writing in a more traditional manner, you might just say “his” even if you don't know.
We sometimes, on ESL Podcast, use “their,” sometimes we use “his or her.” You will see different variations of this depending on who is writing the sentence. Some people say that “their” is grammatically incorrect. However grammar changes with the way language changes in its usage, so I think it's difficult to say it's incorrect. It’s become something that you will see in both formal and informal English. Some people like to solve the problem by changing the subject into a plural subject. So instead of saying “A student can study for their first degree,” you would say “Students can study for their first degree.” There, the possessive pronoun and the subject pronoun match. Not every situation can be solved in this way however, so there will always be some disagreement, I suspect.
There's no disagreement about us wanting to answer your questions here on the English Café. Email us at eslpod@eslpod.com. We can't answer everyone's questions, but we'll do our best to answer as many as we can.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening, as always. We'll see you next time on the English Café.
ESL Podcast's English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational Development.
Glossary
port – a city next to the ocean where many ships and boats are used to transport products
* A lot of ships from Japan deliver goods to the Port of Seattle in Washington.
to settle – to begin to live in an area where people didn’t live previously; to begin to live in an area where there are no other people
* Many people decided to settle in this city when oil was found there.
to found – to establish; to start an organization or society
* Willamette University was founded in 1842.
to rebound – to be able to recover from a bad situation; to be able to do something well again even though it just went very poorly
* Do you think that the orange growers in Florida will be able to rebound after last year’s hurricanes destroyed their orchards?
Cajun – related to the people who live in Louisiana and have French ancestry, or related to their language or food
* He speaks Cajun with his family, but mainly English at work.
predominately – mostly; primarily; mainly
* The Spanish-speaking immigrants in this area are predominantly Cuban.
quarter – a section of a city; a neighborhood; a part of an area
* Walking through the historic quarter of Boston is fascinating.
to flood – to become covered in water, usually because of a storm or a broken dam
* When the street began to flood, all the homeowners began to pack up their valuable belongings.
mansion – a very large, well-built house
* There are many beautiful mansions in Washington, DC, and many of them are now used as embassies.
Mardi Gras – the last day of Carnival, when people wear colorful costumes, make music, and eat and drink a lot, especially in New Orleans
* During Mardi Gras, men throw plastic bead necklaces at women.
Lent – the period of 40 days when Christians, especially Catholics, fast (do not eat certain foods) and pray before Easter
* During Lent, most Catholics do not eat meat on Fridays.
crawfish – a small animal that looks like a lobster and lives in rivers, lakes, and wetlands, and can be eaten, especially in Louisiana and surrounding states
* They had a delicious meal of crawfish boiled with potatoes, onions, garlic, and lemon.
spicy – having a strong, hot taste, even if the temperature is not hot, due to the spices and/or herbs that were used for flavoring
* Kiran loves spicy Indian and Thai food.
paramedic – a person who is not a doctor or nurse, but who helps people who are sick or injured, usually in an emergency; a person who provides medical care in an ambulance
* The paramedics carried the woman into the ambulance and began giving her treatment.
incident – something that happens, usually when it is unpleasant, dangerous, unusual, or violent
* The police were sent to the scene of the incident.
accident – something that is unplanned; something that happens unexpectedly, especially when it results in injury or death
* The car accident occurred when the driver lost control of her car and it crashed into a tree.
What Insiders Know
Hurricane Katrina
In 2005, “Hurricane” (a large storm with very strong winds that forms over the ocean and then moves over land) Katrina had very “devastating” (very damaging) effects on New Orleans, Louisiana and nearby areas. Hurricane Katrina and the “subsequent” (something that happened afterward) flooding caused $8.12 billion of damage and at least 1,836 people “lost their lives” (died).
Because New Orleans is built next to the ocean and parts of the city are below sea level, it has “levees” (low walls to keep water away from a city) for flood protection. As Hurricane Katrina “approached” (came nearer), people began to fear that the water would go over the top of the levees, so “evacuations” (orders to leave a place for safety reasons) began.
When the storm “hit” (came onto land), it was much stronger than anyone had “anticipated” (expected). It broke the levees and the city immediately flooded. Many of the people who had not been evacuated waited for “rescue” (being saved by other people) on roofs.
The government tried to create “refuges” (safe places) for the people who were left in New Orleans. Approximately 26,000 people were put in the Louisiana Superdome, a sports stadium. Unfortunately, very poor planning meant that there was not enough food and water, and the “sanitation facilities” (water and bathrooms) were “insufficient” (not enough) for that many people. The refuges quickly became very unhealthy places.
Many people have blamed the U.S. government for its “inadequate” (not good enough) response to the “disaster” (a very large, serious problem). They say that the government should have “maintained” (to take care of something, especially as it gets older) the levees more carefully, and that it should have started the evacuations sooner.