= 0174
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome back to EnglishPod.
My name is Marco.
And my name is Catherine and today we have an elementary level lesson for you guys out there.
That's right.
Today we are going to talk about an interesting topic, especially for women.
We are going to the nail salon.
Okay, so we're going to get our fingernails painted.
Alright, so let's take a look at vocabulary preview to find out what nail salon means.
Vocabulary preview.
Alright, so if you go to a nail salon, it's a specific place where they paint your nails, right?
Exactly, so it's a shop or a store where you can have your nails painted.
So they have special people to help you.
If you want to go get your hair cut, you would go to the hair salon.
Exactly, so we have hair salon and nail salon.
In this case at the nail salon they can't cut your hair.
Okay, very good.
So why don't we listen to our dialogue for the first time.
Honey, I'll be right back.
Where are you going?
I told you already, I'm going to get my nails done.
Again?
You just went last week.
You spend more time at the nail salon than you do here at home.
Honestly, why do you need a manicure every week?
Well, first of all, I like to pamper myself and my nails look great.
You should come with me.
Why?
I don't want to have nail polish or anything like that.
They don't only paint my nails.
The manicurist will remove my cuticles, file my nails and apply at least four coats of nail polish.
Yeah, sounds like something I should definitely do.
Alright, we're back so now we found some very interesting things to do and specific words related to nails so why don't we look at those now on Language Takeaway.
Language Takeaway.
Alright, so this first word is an important word for every woman to know and I know a lot of men who get this too.
It's called a manicure.
Alright, manicure.
And what exactly is a manicure?
Well, a manicure is a service that you get at a nail salon and that means that the people at the nail salon will cut your nails and shape your nails.
That means if you want them to be pointy or boxy and then you get them painted and dried.
Okay, so they basically take care of your nails, of your fingernails, a manicure.
Exactly and so the important thing to remember here that a manicure is for your hands.
Right, so you can also get your toenails or your feet taken care of, right?
Exactly, so that's different, that's a pedicure because peda means foot.
So pedicure is for your feet and a manicure is for your hands.
Alright, very good and well we talked about painting your nails and that paint has a specific name, right?
Exactly, so you wouldn't use wall paint on your fingers, would you?
Right, right.
So you have to use a special paint and this is called nail polish.
Nail polish, okay.
So a polish is something that makes a surface or a thing shiny.
Okay, so nail polish is a paint that makes your nails very shiny.
Alright, very good and well moving on we talked about a manicure and there's a specific word for the person that provides this service that takes care of your nails.
Okay, so the job at a nail salon is manicurist, that's the person who paints your nails, okay?
Alright.
And so you could say I have a favorite manicurist, her name is Sally.
Okay, very good and well manicurists they perform a manicure and well apart from painting your nails they also push your cuticles or remove your cuticles like in the dialogue.
What are the cuticles?
Okay, cuticle is a very hard word.
This word describes the skin around your fingernail, okay?
So you have skin all over your body but on your fingernail you have special kind of skin and so a manicurist will sometimes push or cut the dead skin, that's the cuticle, from your finger.
Okay, very good.
So if you look at your fingernails now you will see a little thin layer of skin on your fingernail, that's the cuticle and well apart from removing your cuticles and painting your nails they will also file your nails and this is a verb, to file.
To file, okay so this is a word that's kind of like cut or trim but a file is a more delicate process so it means that we kind of shave off very very very little at a time and so to file your nails means to make them shaped differently or to smooth them, they're not cutting, clip clip clip, it's not that, it's a little bit less than that.
And now there's also a noun for this, a nail file and most women will usually have it, it's a long piece of cardboard that has a paper that's kind of like sand on it, kind of like sandpaper.
It doesn't feel good when you rub it with your hand.
With your hand but if you use it on your nails it will little by little just take away little parts of your nail.
Yeah, you usually see it, the many secretaries you know in TV shows they're always filing their nails.
Exactly, making them perfect.
Okay, so those are the words we have for language takeaway why don't we take a look at our dialogue again and we'll be back in a little bit.
You just went last week, you spend more time at the nail salon than you do here at home.
Honestly, why do you need a manicure every week?
Well, first of all I like to pamper myself and my nails look great, you should come with me.
Why?
I don't want to have nail polish or anything like that.
They don't only paint my nails, the manicurist will remove my cuticles, file my nails and apply at least four coats of nail polish.
Yeah, sounds like something I should definitely do.
Alright, we're back so now why don't we start with some phrases, some very good phrases that we found in this dialogue in Fluency Builder.
This first phrase is really important when we talk about nails because it's the way that we describe going to the nail salon.
So I can say, I'm going to get my nails done today.
Okay, so to get your nails done, that means that you're going to get your nails cut, filed, painted, etc.
I'm going to get a manicure but that's very, I don't know, serious.
So you could say, I'm going to get my nails done, it's more spoken language.
Okay, so I'm going to get my nails done or you got your nails done.
Very good.
And well, the woman was talking about why she likes to go get a manicure and she said that she likes to pamper herself.
Okay, this is very common especially when women are trying to talk about why they spend money on hair and nails and clothes.
They say, I like to pamper myself.
To pamper means to treat very, very well.
Okay, so if you go get a manicure, it's kind of like pampering yourself or maybe going to a spa.
Exactly, or getting a massage and so we could say also, don't pamper the dog, that's very naughty.
So a synonym would be to spoil.
To spoil oneself, to pamper.
Indulge, okay.
So, and well, she was talking about how they perform a manicure and she talked about four coats of nail polish.
So a coat, we know that it's kind of like a jacket, right?
But in this case?
In this case it means a layer.
So you paint your nails one time, okay, maybe you have color, maybe it doesn't look right, okay, it's very thin.
So you say, okay, I'm going to paint two coats and then you paint one more time and the color gets darker.
You paint one more time and the color gets very dark and very thick.
And so these are called coats, that means layers of nail polish and it's a special where we use when we're talking about painting our nails.
Right, so it's not only for nails but if you're painting your house, maybe you need two or three coats of paint.
Exactly, if we have a red wall and we want to paint it white, we definitely need two, three, maybe four coats of paint, otherwise we'll still see the red.
Uh-huh, okay, very good.
Very interesting phrases, let's take a look at this dialogue for the very last time and we'll be back shortly.
Honey I'll be right back.
Where are you going?
I told you already, I'm going to get my nails done.
Again?
You just went last week, you spend more time at the nail salon than you do here at home.
Honestly, why do you need a manicure every week?
Well, first of all, I like to pamper myself and my nails look great.
You should come with me.
Why?
I don't want to have nail polish or anything like that.
They don't only paint my nails, the manicurist will remove my cuticles, file my nails and apply at least four coats of nail polish.
Yeah, sounds like something I should definitely do.
Alright we're back, so Catherine are you a big fan of manicures?
Do you get it done often?
I didn't used to, but I really enjoy them now.
I think it's a nice way to relax on the weekends, so every couple of weeks I go to the nail salon and I have my nails, I get my nails done.
Alright, and I think one of the words that we didn't talk about here, but it's very, I don't know, for men it's kind of a strange smell is nail polish remover.
The acetone, right?
It's a very strong chemical.
It is really disgusting.
Nail polish remover, you know the word to remove means to take away.
And so when the nail polish, we want to change the color, we have to use this.
It's like water, but it smells really bad.
So my boyfriend always gets angry when I use the nail polish remover because the whole house starts to stink.
It's a very strong smell and you get kind of dizzy.
Yeah, it goes into your head.
Alright well if you guys have any questions, any doubts or any suggestions about this lesson or any other lesson, please come to our website EnglishPod.com and we'll see you guys there.
Bye everyone. +
