= 0197
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello, everyone, and welcome back to EnglishPod.
My name is Marco.
My name is Katherine, and today we've got a great, informative lesson for you.
That's right.
We are going to talk about an emergency situation.
So what do you do when you have an emergency?
You dial 911.
Exactly.
All right, well, maybe not in your country, but today we're talking about emergencies in America and jobs, so people who can help you in an emergency.
So before we get into those words and phrases, let's take a listen to today's dialogue.
All right, class, now that we're all dressed up, let's see what professions you chose.
I see a fireman, a police officer, a medic, and a lifeguard.
Can anyone tell me what these people have in common?
They save people from bad things?
That's right.
Now, class, if something bad happened and you had to get help, do you know what phone number you would call?
911.
Yes!
You would pick up the phone and dial 911.
What are some emergency situations in which you would need to dial 911?
If my grandpa had a heart attack.
If there was an accident.
If a robber broke into the house.
If the fire alarm went off.
I wouldn't call 911 if the fire alarm went off in my house.
The only time that ever happens is when we're having spaghetti for supper and my mom burns the garlic bread as usual.
All right, we're back.
So now we have a couple of different jobs for people that are working specifically in emergency situations.
So let's take a look at those now in Language Takeaway.
Language Takeaway.
All right, so we have a teacher in today's dialogue who's talking to her students about jobs.
So probably these students are very young and she says another word that means jobs.
What's the word she uses?
Professions.
That's the plural.
So profession is a job.
Let's say, for example, a lawyer is a profession.
Or a doctor.
A doctor, a lawyer.
So what's your profession is another way to ask what's your job.
All right, so they're talking about professions and some of the kids dressed up as different people.
The first one was a fireman.
A fireman.
So you know the first word fire.
A fireman is a person who puts out a fire.
That means he uses water to stop a fire.
Very good.
So a fireman puts out fires.
Now apart from a fireman, we also have a police officer.
A police officer.
So an officer is someone who works in an official capacity, so in a job.
So we could say he is a police officer or a policeman or a policewoman.
So three ways to say this.
So officer is for both genders, right?
A man or a woman could be a police officer.
That's right.
So you're going to hear this very often because policeman doesn't explain a woman police officer.
So we use police officer to be general.
Okay.
So we have a fireman, a police officer, a medic.
Now what is this medic?
A medic is a kind of doctor.
Someone who will look at your health or help you if you've hurt yourself.
Who usually works on the road like driving to an accident or driving to a fire with police officers.
So these people help police officers and firemen when there's an emergency.
Okay.
So a medic is not really a doctor.
He's more of a specific person that can help you if you have maybe some cuts or bruises or will help you out.
Right.
So this person will stop your bleeding or will help take you to the hospital and they'll make sure that you're healthy when you get to the hospital.
But they are not really like a doctor where you work in a hospital or a doctor's office.
Okay.
And our last profession is a lifeguard.
Well think about these two words.
We have life and we have guard.
Guard is like protect.
So a person that protects your life.
Hmm.
Interesting.
Well this is someone who usually works at the beach or at a pool.
They have a special chair and usually they have a cross on their bathing suit or on their towel and this means that they're going to help protect people who are at the beach.
So if someone can't swim, the lifeguard will run or swim to get them and save them.
Okay.
Very good.
So you have a lifeguard.
Now this is for men and women as well, right?
A lifeguard.
Exactly.
Okay.
So interesting professions.
Why don't we listen to our dialogue again and we'll be back shortly.
All right class.
Now that we're all dressed up, let's see what professions you chose.
I see a fireman, a police officer, a medic and a lifeguard.
Can anyone tell me what these people have in common?
They save people from bad things?
That's right.
Now class, if something bad happened and you had to get help, do you know what phone number you would call?
911.
Yes.
You would pick up the phone and dial 911.
What are some emergency situations in which you would need to dial 911?
If my grandpa had a heart attack.
If there was an accident.
If a robber broke into the house.
If the fire alarm went off.
I wouldn't call 911 if the fire alarm went off in my house.
The only time that ever happens is when we're having spaghetti for supper and my mom burns the garlic bread as usual.
All right, we're back.
So now let's start with Fluency Builder.
Fluency Builder.
Our first item in Fluency Builder we've already talked about.
The number in America to call when you have an emergency is 911.
So we usually say, hey, dial 911.
Okay, so that's a verb there, to dial.
Exactly.
To dial means to select the numbers for a phone call.
To telephone someone.
To telephone someone.
To dial.
So you can dial 911 or dial my office number.
Or I tried to dial your home number but no one answered.
Okay.
Now you can call 911 for many different situations or emergency.
One of the kids said, well, if my grandpa had a heart attack.
Okay, so this is an example of an emergency.
A heart attack is a medical problem.
It's when your heart cannot receive oxygen.
Okay, so your heart stops beating sometimes.
That's right.
Sorry.
It's when your heart does not receive enough blood or oxygen.
So it's when your heart stops beating.
Okay, very good.
So that's a heart attack.
Now another possible emergency situation is if the fire alarm goes off.
This often happens in office buildings and schools.
So you hear a dee dee dee or some kind of strange noise.
Well that's because there's maybe a fire or some smoke in your building.
And so usually when this sound goes off, it automatically calls the police and the fire department.
Now there's an interesting phrasal verb that is used along with this word fire alarm.
We say the fire alarm goes off or the fire alarm went off.
So that means it started to sound, to emit a sound.
So the verb here, as you said, it's a phrasal verb is to go off, to go off.
We could say my alarm went off or every morning at seven o'clock, my alarm goes off.
Okay, that means your alarm begins to make a sound.
A very annoying sound.
Right.
You know, it's the worst sound ever.
But a lot of things can go off.
We could talk about a bell or an alarm or fireworks.
Fireworks go off.
Okay.
And well, the last emergency that we were talking about is if a robber broke into the house.
So if a robber breaks in.
To break into.
This means to enter, to go inside without permission or without a key.
Illegally.
Illegally.
You have to break something, but usually you break a window or a door.
But this means that someone comes into your house looking to steal something.
So usually you have to use force.
For example, if I forget my keys inside my car and I have to break into my own car, that means maybe I have to force the door open or maybe break the window.
Yeah, it's not, not fun.
I think it usually ends up being very expensive.
Yes, it does.
All right, so those are all the phrases we have for today.
Why don't we listen to our dialogue for the very last time?
Yes!
You would pick up the phone and dial 911.
What are some emergency situations in which you would need to dial 911?
If my grandpa had a heart attack.
If there was an accident.
If a robber broke into the house.
If the fire alarm went off.
I wouldn't call 911 if the fire alarm went off in my house.
The only time that ever happens is when we're having spaghetti for supper and my mom burns the garlic bread as usual.
So, Marco, when you were a kid and your teacher said, what jobs are there?
What professions are there?
What profession would you like?
What did you answer?
I always wanted to be a pilot.
Oh, pilots.
You wanted to fly airplanes.
Yeah, I wanted to be a jet pilot.
Actually, I collected books about it.
I read up about it.
So even till now, I probably still remember like the capacity of certain jets or what types of weapons they have.
I was really, really into it.
Wow.
I never knew this about you.
Yeah.
What about you?
Oh, I could never decide as a kid.
I remember we had to draw pictures of what I will look like in 20 years and everyone had these pictures.
I will be a doctor.
I'll be a veterinarian.
I'll be the president.
I never knew what to draw.
So, you know, I think I copied my friend.
She wanted to be a lawyer.
I thought, OK, that sounds OK.
Yeah, I think it's hard.
And usually what you want to be as a kid, you don't do it when you're older.
I couldn't do it because of my vision.
I didn't have 20-20 vision to actually join the Air Force.
Well, and a lot of kids don't know how many jobs there are out there.
You know the big ones.
Doctor, lawyer, fireman, policeman, astronaut.
So I guess the question for you is what's your profession?
Tell us about it, especially if it's one of the less famous professions out there.
There's a lot that I don't know about those.
Our website is EnglishPod.com.
We hope to see you there.
And until next time.
Bye.
Bye. +
