= 0198
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome back to EnglishPod.
My name is Marco.
My name is Catherine and today we are covering a very important health issue.
That's right.
We are...
that's right.
In case of an emergency, maybe somebody stops breathing, so we need to apply CPR.
Now what is this procedure?
Well, let's take a look at it in vocabulary preview.
Vocabulary preview.
CPR in English is an acronym that means C, P, and R all stand for different words.
The big phrase here is cardiopulmonary resuscitation.
So you don't have to remember that.
Well, it's pretty hard.
What if you break it down?
So what is cardio?
Cardio means it has to do with your heart.
And then pulmonary?
Pulmonary means lungs.
It has to do with your lungs.
And what about resuscitation?
That means to bring back.
So to resuscitate is to bring back to life.
That's right.
Okay.
So this is a very popular procedure.
You probably see it in movies when somebody almost drowned the lifeguard performed CPR.
Oh no!
The love of my life has just drowned!
And then someone comes and they push their chest and they say, one, two, three.
They count.
And then the person spits out water and everything and they're like...
I always love to.
Alright, so that's CPR.
Why don't we listen to this dialogue, see what's going on, and we'll be back shortly.
Hello everyone and welcome to our CPR for beginners course.
First of all, does anyone know what CPR stands for?
Cardiopulmonary resuscitation.
That's right.
We apply CPR in the case of cardiac arrest or pulmonary arrest.
What does that mean?
Well, basically, if your heart stops pumping blood or your lungs stop pumping air, then we need to get them going again.
That's when we have to apply this procedure.
Let's begin.
I need a volunteer.
Me!
Me!
Alright, come here and lay flat on your back.
Let's suppose this young woman has stopped breathing.
We must lift the person's chin so that we clear a pathway for air to get into the lungs.
Then we place our mouth over the other person's mouth and blow air two or three times, like this.
Wait, what are you doing?
I'm a married woman.
You can't just try to kiss me like that.
Ma'am, I'm not trying to kiss you.
I'm trying to demonstrate how to apply CPR in the case of an emergency.
Well, okay.
No French kissing.
As I was saying, we blow air through the mouth in this manner.
Once this is done, we must try to get the heart going again.
To do this, we place our hands over the person's chest and press down firmly two or three times.
Wait, what are you doing?
You can't just kiss me, then go for second base.
All right, we're back.
So a couple of pretty difficult words and phrases there, but don't worry.
We'll explain them now in Language Takeaway.
Language Takeaway.
The first phrase we've got today is cardiac arrest.
All right, so cardiac arrest.
Now, cardiac, I think that has to do with the heart again, right?
Exactly, your heart.
And what about arrest?
Well, arrest means two things.
Maybe you've heard of this meaning to arrest somebody, the police arrested someone.
Well, this means to stop.
So we're not talking about the police here.
We're talking about the heart stopping.
So cardiac arrest means when your heart stops.
Okay, and another word that's right next to it, pulmonary arrest.
So I'm guessing, again, pulmonary has to do with lungs and arrest stops.
So your lungs stop pumping air.
Exactly.
So cardiac and pulmonary arrest, these are two times when your heart or your lungs, they stop doing what they are supposed to do.
All right, and interestingly enough, the heart pumps blood, the lungs pump air, and that's our next word.
What is this word to pump?
To pump means to fill something with, okay?
So for example, the heart pumps blood to the rest of your body.
That means it's always making sure your body has blood going into it.
And the same thing with your lungs.
Your lungs help oxygen and air get to the rest of your body.
So they pump it, they fill up with air.
Okay, and we can do the same in other things.
For example, you pump air into your tire.
That's right.
If you have a flat tire, you're riding your bicycle and your bicycle won't move, oh no, you have to pump it with air.
That means fill it up with air.
Okay, or maybe even pump water, right, like in your house.
Or pump your car up with gas.
Okay.
All right, very good.
So now the man is going to explain how to perform this procedure, CPR, and he asks for a volunteer.
Okay, a volunteer.
This is a word that can be both a noun, so a thing, and it can be an action, a verb.
Okay, so who is or what is a volunteer?
A volunteer is someone who offers to do something for free.
For free, without you asking them to do it.
Right, so are there any volunteers in the room?
Right, and somebody says, me, me, me.
Me, me, me, I do.
Okay.
You can also volunteer to help people who need help.
So for example, in Haiti there's an earthquake, and there are many people who offered to volunteer to help patients.
So that means they said, I will work for free to help these people.
A volunteer.
A volunteer, or to volunteer.
Very good.
So now we have our volunteer, and the man is explaining what to do.
Oh, this is a good one.
So a path is like a road.
It's where something can go, can move.
To clear a pathway means to make some room.
Okay.
To make a clear path.
So that means, think about it, if you can't breathe, someone has to find a way to make room, to make a hole for you to breathe.
So that means to move whatever is blocking you to clear some kind of space.
Okay.
So that's a pathway, a clear space.
And now, well, he's demonstrating how to perform CPR.
So what is this verb, to demonstrate?
To demonstrate is very important.
We use this in most kinds of teaching.
So to demonstrate is to show, or to give an example.
Okay.
So for example, here in EnglishPod, we are demonstrating how to use these words in sentences.
Exactly.
So a simple example is a good way to demonstrate the word or the phrase.
Very good.
All right.
Why don't we listen to this dialogue again, and we'll be back in a bit.
Hello everyone, and welcome to our CPR for beginners course.
First of all, does anyone know what CPR stands for?
Cardiopulmonary Resuscitation.
That's right.
We apply CPR in the case of cardiac arrest or pulmonary arrest.
What does that mean?
Well, basically, if your heart stops pumping blood or your lungs stop pumping air, then we need to get them going again.
That's when we have to apply this procedure.
Let's begin.
I need a volunteer.
Me, me.
All right.
Come here and lay flat on your back.
Let's suppose this young woman has stopped breathing.
We must lift the person's chin so that we clear a pathway for air to get into the lungs.
Then we place our mouth over the other person's mouth and blow air two or three times like this.
Wait, what are you doing?
I'm a married woman.
You can't just try to kiss me like that.
Ma'am, I'm not trying to kiss you.
I'm trying to demonstrate how to apply CPR in the case of an emergency.
Well, okay.
No French kissing.
As I was saying, we blow air through the mouth in this manner.
Once this is done, we must try to get the heart going again.
To do this, we place our hands over the person's chest and press down firmly two or three times.
Wait, what are you doing?
You can't just kiss me then go for second base.
All right, we're back.
So now let's go with Fluency Builder.
Fluency Builder.
Well, the first phrase in Fluency Builder we hear in the beginning of today's dialogue, the teacher says, well, basically, if your heart stops pumping blood, then we need to get it going again.
Okay.
So that's a whole phrase there, to get something going, to get it going.
What do you mean by this?
This means to start it up again.
Okay.
We could say, I used to teach an English class for my colleagues, but we stopped having it.
I'd like to get it going again.
Okay, so you'd like to start it up again.
Exactly.
Usually, you're talking about turning something on or getting something started.
For example, maybe your car won't start, so if you push it, you can get it going.
Right, to get it going or to turn the keys to get it going.
Okay.
Right.
So to get something going.
Now, moving on, we have two key phrases here that are a little bit spicy, right?
Yeah, they're very romantic, although this is a CPR class, so it shouldn't be very romantic.
All right.
Well, this phrase that we have coming up is French kiss, to French kiss someone or a French kiss.
So the volunteer says, okay, I'm happy to help you, but no French kissing.
Okay, so what is French kissing?
No one wants to answer.
All right.
What is it?
It is when you kiss someone, but your tongue goes into that other person's mouth.
Ew.
All right, so there's a normal kiss.
You can kiss your friends on the cheek, but a French kiss means that you use your tongue.
Okay, so I wonder why they call it a French kiss.
Maybe Americans just were too shy.
They blamed it on the French.
Maybe the French listeners out there can tell us.
All right, so now moving on, and she says, okay, no French kissing.
Now the man is going to perform CPR, and obviously he has to firmly press down on her chest to get her heart pumping blood, right?
Right, this is a part of CPR.
So first of all, you try to give the person air so they can breathe, and then you have to push their chest to start their heart.
And this woman, the volunteer says, hey, what are you doing?
You can't just kiss me first and then go for second base.
All right, so what is second base?
Okay, this is a sports metaphor.
With baseball, right?
Baseball.
Because baseball has four bases, first, second, third base, and home plate.
Exactly.
Or home base.
So in romance, when we're talking about dating, we have a way to say first, second, third, and fourth base.
First base is kissing.
That's kissing, right?
So second base, what would be second base?
Well, in this example, it means touching.
Touching, certain parts of the body, right?
Romantic touching.
All right, so second base, and then obviously we have third and fourth, but we're not going to get into that now.
You can look it up on Google, third base and fourth base.
We trust that you can find it.
But first and second base are very common.
It's okay to talk about.
It's not a bad word.
So you'll probably see it in movies, young kids talking about first base or going to second base with someone.
So it's kind of saying this in a different way, as a metaphor, as you said.
It's more polite than talking about.
It's subtle.
All right, so that's all the words and phrases we have on Fluency Builder.
Let's listen to this great dialogue one last time.
Hello everyone, and welcome to our CPR for beginners course.
First of all, does anyone know what CPR stands for?
Cardiopulmonary Resuscitation.
That's right.
We apply CPR in the case of cardiac arrest or pulmonary arrest.
What does that mean?
Well, basically, if your heart stops pumping blood or your lungs stop pumping air, then we need to get them going again.
That's when we have to apply this procedure.
Let's begin.
I need a volunteer.
Me, me.
All right, come here and lay flat on your back.
Let's suppose this young woman has stopped breathing.
We must lift the person's chin so that we clear a pathway for air to get into the lungs.
Then we place our mouth over the other person's mouth and blow air two or three times like this.
Wait, what are you doing?
You can't just try to kiss me like that.
Ma'am, I'm not trying to kiss you.
I'm trying to demonstrate how to apply CPR in the case of an emergency.
Well, okay.
No French kissing.
As I was saying, we blow air through the mouth in this manner.
Once this is done, we must try to get the heart going again.
To do this, we place our hands over the person's chest and press down firmly two or three times.
Wait, what are you doing?
You can't just kiss me then go for second base.
All right, we're back.
So a CPR class, this is actually a very popular thing to take up.
You never know when you need to perform it, right?
That's true.
And I think it's a really smart class to take.
You can usually take them for free at a community center or a fire department.
The Red Cross.
The Red Cross.
I have a Red Cross certification.
Oh really?
So you know how to perform this?
Yep.
Wow.
It's actually, as I said, I think it would be very useful.
And I've never taken a course like this up, but I know how to perform the procedure.
So I'm not certified though, so I'm not a certified CPR person.
But it's interesting.
Let us know if in your country maybe you can take CPR classes or maybe you are a CPR certified technician.
Or maybe you are trained in other ways.
So we're curious about those as well.
Let us know if you have any questions about today's lesson.
Our website is EnglishPod.com.
All right, we'll see you guys there.
Bye everyone. +
