
=
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

文案的工作性质, 两个核心指标：曝光、销转率。这就需要先"洞察人性". *为什么这个公司这样写他的文案？背后相关的是他的营销逻辑、营销打法、营销策略相关的。* +




*当你服务的甲方越多时，对比起来的大家的稿件、营销打法的区别程度就越大，各类套路看多了，能思考并且抽出来模型的时候*，你个人成长的速度就越快。

去外面兼职文案, 真的是我觉得是个人成长速度最快的方式，没有之一，不要听自己老板在那里瞎比比.

记住，时间花在哪里是看得见的。你把时间用在哪里，你的成长就在哪里。看三个月剧不会成为编剧，但用脑子有策略的去写三个月稿件，



技术分析: +
第一, **标题有哪些打动你的地方?**  +
第二，*如何开头的*,  +
第三，*如何引出产品*,  +
第四，*如何激发你的欲望，让你想要购买*  +
第五，*如何让你产生信任*  +
第六，*价格部分如何处理*  +
第七，*如何让你迅速下单*  +
第八，整篇文案**段与段的连接，如何让你不断的往下阅读**  +
第九，*整篇文案的逻辑思路是怎么样的*  +
第十，**有什么是你觉得不好或者好的地方，**摘抄你觉得好的部分，如果你写你会怎么写这篇推文?

①在写稿子前问下自己，我写这篇文章是不是别人喜欢看的，需要看的. +
②在写完稿子后再回过头看下稿子，这篇稿子里面有没有把一个小点说透，有没有给到读者一些新的内容，稿子的丰富度自己能不能感觉出来，就可以了。

假装学习、书面化学习是人最大的偷懒表现。你说的话他听，你交代的作业他做，但是课程结束后，他不思考，不练习这项技能.

你能看见自认为好的文案，是许多不好的文案堆积起来的，不信你就在你住的方圆三公里转转，你能找到多少经典（自认为）的文案？敲定一个文案，要看领导需要什么，客户需要什么。一句话，好的文案并不一定是一个人的事儿，*它是集体的创作。*

文案到底是这样的一种工作呢？就目前来看，现今我对文案的理解是：写字+微信运营+微博运营+策划+后勤工+推广+客服经理（AE）+市场跟踪调查≈文案。
要说明的是，*这些我做过，有的做得好，有的做得坏，如果你能在这些岗位全部做到优秀，或许不是文案，而是创意总监.*







