= 1822
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 517.
This is English as a Second Language Podcast’s English Café episode 517. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles California.
Visit our website at ESLPod.com. Become a member of ESL Podcast. When you do, you can download the Learning Guide for this episode. The Learning Guide contains a complete transcript of everything we say, plus it has all of the vocabulary definitions, additional sample sentences with our keywords, cultural notes, and a whole lot more. If you’re on Facebook, why don’t you go and like us on facebook.com/eslpod.
On this Café, we’re going to talk about the 1998 movie Die Hard, with Bruce Willis. We’re also going to talk about a famous American poet, a woman with a very interesting story, by the name of Emma Lazarus. And as always, we’ll answer a few of your questions. Let’s get started.
The movie Die Hard tells the story of a tough, strong New York City police officer by the name of John McClane. John McClane, who is played by the actor Bruce Willis in the movie, uses his skills as a policeman and his intelligence to outwit a criminal, a group of criminals, and to save innocent people. “To outwit” (outwit) someone means to defeat someone in a contest or competition by being more intelligent, by being smarter than the other person.
The movie begins with John McClane on an airplane. He is flying from New York to Los Angeles to visit his wife, Holly, and their children for Christmas in December. He and his wife are “separated,” meaning they no longer live together but they’re not legally divorced. McClane hopes his wife will give their marriage another try after this visit. “To give something another try” (try) means to attempt to do something for a second time to see if it will work better or will be successful.
McClane arrives at the airport, and when he does, there is someone waiting for him, a professional limousine driver. A “limousine” (limousine) is a large, very comfortable car that usually has a professional driver, sort of like a taxicab. However, a limousine is more expensive and much nicer. This limousine driver takes McClane to the office building where his wife works here in Los Angeles.
McClane gets out of the car and goes into the office building, and the driver goes down into the basement below the office building and sits in the car, waiting for McClane to finish his visit so he can drive him to his next destination – to where he is going after that. So McClane enters into the building and his wife Holly is there. Holly takes him to her office so that he can freshen up.
“To freshen (freshen) up” is a two-word phrasal verb that means to wash your face and hands, perhaps even to change your clothing, after a long period of travel or of some other activity. I tend to think we use this phrasal verb “to freshen up” more with women than with men, but I guess we could say that John McClane went into Holly’s office, his wife’s office, to freshen up after this long plane ride from New York.
Holly leaves her husband in her office and goes back to the Christmas party that her company is having. McClane says he will join her when he is finished freshening up. After Holly goes back to the party, however, a group of men arrive at the building. They enter with guns and kill the security guard – the man whose job is to keep people safe. One of the men stays at the desk and pretends to be the security guard.
The rest of them go upstairs to the office party and they take the entire group of people working hostage. A “hostage” (hostage) is a person who is held against his wishes, a person who is held as a prisoner until some sort of condition is met. When someone is taken as a hostage, often the person who is taking them as a hostage will demand money. “I want a million dollars, and when I get a million dollars, I will give you your husband back” (or your child back). That is a hostage.
Sometimes hostages are taken for political reasons. A political group might take someone hostage and demand certain changes in a government, for example. Well, Holly and her fellow employees are taken hostage. McClane, however, is still in Holly’s office. He doesn’t know what’s going on, but he hears the noises and realizes that the building is being attacked. So, he escapes. He leaves Holly’s office and goes to an area of the building that is still under construction, meaning it’s still being built. It’s not yet finished.
He pulls the fire alarm to try to call the police. A “fire alarm” is a loud siren or noise that goes off in a building, usually when a fire has started. If you pull the fire alarm, you turn it on and so a noise is made, and in most cases the fire department and/or police are automatically called. Usually it’s the fire department, of course. The police are told that there’s a fire, and they call the building to see if a fire truck needs to be sent to help put the fire out.
When the police call, however, the man pretending to be a security guard, one of the criminals, answers the phone and says, “No, no there’s nothing wrong in the building.” He tells the police not to come to the building. At this point our hero, John McClane, realizes he will have to do something else to get the police to come to the building in order to save these hostages.
The leader of the evil men is a German named Hans Gruber. It’s interesting, as the movies and politics of the world change, the evil people in American movies change nationalities as well. For many years it was a German person, then it could be perhaps a Russian – maybe now, I don’t know, a Chinese. It depends on the political atmosphere of the period in which the movie is made. This movie was made in the late 1990s.
Anyway, Hans Gruber knows that there is someone else in the building, someone who is not in the group of the hostages that he has. So, he sends his man to go and find this person. We also learn that Hans Gruber is really just a criminal. He is in the building to steal $640 million worth of a kind of investment called a “bond.” These “bond certificates,” or pieces of paper, are inside the building in something called a “safe.”
A “safe” (safe) is a strong, secure box or room where you keep valuable things, things that you don’t want someone to steal. Most banks, for example, have a safe where you can perhaps put valuable objects that you own into a little box, what we call a “safe deposit box.” Well, this isn’t a bank. This is a business that has a safe inside of the building.
The owner of this building is a man by the name of Joe Takagi. Gruber wants Takagi to give him the, what we would call, “combination,” or numbers that would let him go into the safe – of course, so Gruber can steal everything inside. Takagi refuses, and so Gruber kills Takagi. The building, by the way, is called the Takagi Building.
Meanwhile, while this is going on, the men that Gruber sent to find John McClane are searching every floor, every level, in order to find them. McClane, however, is waiting for them. He knows that they are going to come looking for him, and so he kills these men, or at least most of them. So what does Gruber do? He sends even more men to look for our hero, John McClane. McClane is eventually able to contact the police by using one of the radios that he gets from one of the men he has killed.
He talks to a police officer by the name of Sergeant Al Powell. Powell arrives and looks at the building from the outside and it seems that there is nothing wrong. So, he’s about to leave when McClane, realizing he has to do something else to get the police’s attention, throws the body of one of the men he has killed onto Powell’s police car. Well, of course, immediately Powell understands that something serious is happening and he calls for more support, more police officers.
The movie continues and Gruber and his men continue to try to find McClane and try to steal the money and objects that are inside of the safe. Will they be successful? Will they kill John McClane or will they be killed? Well, I’m not going to tell you the ending of the movie, but my guess is many of you have seen it. If you haven’t, it’s an exciting movie to watch and you should try to find it somewhere, I think. I think you’ll enjoy it.
Now John McClane, I mentioned earlier, was played by a famous actor, Bruce Willis. And the bad guy, Hans Gruber, is played by another famous actor – not a German but a Brit, someone from Great Britain, an actor by the name of Alan Rickman, who was also in the Harry Potter movies. There’s a famous and funny part of the movie where Gruber asks McClane who he is, and McClane refuses to give his name or tell him why he is in the building. So, Gruber calls McClane “Mr. Cowboy.”
A “cowboy” (cowboy) is a man who rides horses. Cowboys featured famously in many movies during the twentieth century, in what are called “Westerns” – movies about the western part of the United States during the nineteenth century. In these Westerns, cowboys are always tough. Cowboys are always, or typically, the heroes. One of the things that cowboys would say in these movies is an expression that just means “I’m excited” or “Let’s go.” The expression was “Yippee-ki-yay.”
Well, because Hans Gruber calls McLane “cowboy,” McClane, during one important scene or part of the movie, says to Gruber, “Yippee-ki-yay” and then calls Gruber a very vulgar name. The name has the word “mother” in it, as well as another word that begins with “F” that I won’t repeat here on the podcast, but if you know something about English, you probably have heard what we call the “F-word.” He uses this word obviously in an insulting way when he talks to Gruber.
A lot of people wonder what “Yippee-ki-yay” means. It’s just an expression that doesn’t have any meaning, at least in English, other than to say that you are excited or to say, “Let’s go.” No one uses it anymore in daily conversational English unless they’re making a joke related to the Die Hard movie. It’s only an expression you would hear in an old western movie.
Die Hard was immediately popular, not only in the United States but all around the world. In fact, it was so popular, they made a couple more Die Hard movies. Die Hard II was released in 1990. Die Hard with a Vengeance was released in 1995. In 2005, Live Free or Die Hard was released. In 2013, there was A Good Day To Die Hard, and there is apparently one more movie (not yet released at the time I am recording this episode) in the summer of 2015 called Die Hardest.
Even though all the other movies have not been as popular as the original, people still love and know this character John McClane, played by the actor Bruce Willis.
From movies, we turn to poetry. The poet Emma Lazarus was born in New York in July of 1949. She was a Sephardic Jew. “Sephardic” (Sephardic) means that she was descended from the Jewish people who lived in Spain and Portugal in the late sixteenth century. When I say she was “descended from,” I mean she was a relative of – her family, many, many years ago, centuries ago, was from this particular group.
She was raised in New York, and she had the opportunity when she was there during this time, in the middle of the nineteenth century, to study different languages and the literature of different languages. As a result, she grew up a very well-educated woman. This was somewhat unusual for women during this period of history.
Lazarus began writing early in her life and published her first book in 1867, when she was only 18 years old. The book was called Poems and Translations and was very well received by newspapers and others who were educated. “To be well received” means it got a positive response from people, from those who read it.
In fact, the famous American author Ralph Waldo Emerson liked Lazarus’ poems and writing so much that he began telling other people about her work. As a way of thanking Emerson for his support, Lazarus dedicated her next book, Admetus and Other Poems, published in 1871, to Ralph Waldo Emerson. When I say she “dedicated” the book to him, I mean that she said that this particular book was done in his honor.
You can dedicate your book to a certain important person in your life, or to someone you think had an influence on you or was perhaps someone who had an influence on the topic you are writing about. When I published my first book, I dedicated it to my parents. That’s a common dedication for books. Sometimes even movies and TV shows, when you watch them at the end, will show a person to whom that movie or show was dedicated.
Over the next 10 years, Lazarus published three more books and had many of her poems published in magazines. Beginning in 1881, Emma Lazarus started to focus on the difficulties, the problems, of the Jewish people in Europe and in the United States. At this time, during the late nineteenth century, many Jews were immigrating to the United States from Eastern Europe and Russia because of the persecution they experienced there.
“Persecution” comes from the verb “to persecute” (persecute). “To persecute” someone means to treat someone very badly because of perhaps his or her race or political beliefs or religion. Unfortunately, some of the Jewish people who escaped persecution from Eastern Europe and Russia came to the United States and were not made to feel very welcome here, either.
Lazarus decided to write more about the persecution of Jews in Eastern Europe to try to make Americans understand the difficult situation these new immigrants had faced, had lived through. She also began working with Jewish immigrants arriving to the United States to try to help them adjust, to build new lives here.
Lazarus was proud to be an American, so it is no surprise that when a group of people asked her to help raise money, to help get more money, to build what we would call the “base” for the Statue of Liberty, she agreed. The Statue of Liberty, you may know, was a gift from the people of France to the United States. It is the famous structure in New York City, with Lady Liberty holding up a torch, a lamp.
In order to put the Statue of Liberty up in New York, they needed something to put it on – the “base” (base) is what the statue rests on. It’s the thing you put the statue on. They needed a base, and in order to build the base, they needed money. France had paid for the building of the statue, but the people of New York had to build the base upon which to put it.
Lazarus decided to write a poem to make some money to help pay for this base, and the poem was called “The New Colossus.” A “colossus” (colossus) is a statue of a person that is much larger than a real person. People liked Lazarus’ poem so much that they decided to put it on the base of the Statue of Liberty after Lazarus died.
The poem that Lazarus wrote is still one of the most famous poems known to at least some Americans. Schoolchildren often learn the poem, or at least they used to. The poem contains the famous lines:
Give me your tired, your poor,
Your huddled masses yearning to breathe free,
The wretched refuse of your teeming shore.
The poem is about welcoming people who have been persecuted in their home countries into the United States. The first line of the poem is “Give me your tired, your poor.” That’s easy enough to understand. The second line is little more difficult. It says “Your huddled masses yearning to breathe free.” “To huddle” (huddle) means to stand very close together, stand close to other people. A “mass” (mass) is a large group of something – in this case, a large group of people.
Now, why would people huddle next to each other? Why would they stand close to each other? Well, perhaps because they’re scared, or maybe they’re just cold. New York gets awfully cold in the wintertime. However, I think it’s the first meaning there – that people perhaps are being persecuted and they’re scared, and so they huddle together for safety. These masses huddling together were, according to Lazarus, “yearning to breathe free.” “To yearn” (yearn) means to desire something strongly, to really want something. These people want to “breathe free.” They want to be free.
The final line of this section of the poem says, “The wretched refuse of your teeming shore.” The word “wretched” (wretched) means very unhappy or very unlucky. “Refuse” (refuse) basically means trash, something that you throw away. So the wretched refuse would be, I guess, the people from other countries who are unlucky and whose countries no longer want them or no longer seem to want them.
The word “teeming” (teeming) is not a common word in English. It means to be full of something. A “shore” (shore) is a piece of land next to the sea, next to a lake, or another large body or area of water. So, we have “the wretched refuse of your teeming shore.” You can imagine these people who are huddled next to each other in a large group, standing on the shore of another country, wanting to go to a different country. Sadly, a situation that we continue to see even in the twenty-first century.
You can see how Lazarus, in writing these words, was in part expressing her thoughts, her opinions about welcoming the persecuted Jews from Europe who were then arriving to the United States. Because of what the Statue of Liberty represents to people coming to this country, the words of the poem are also very appropriate or suitable for other groups as well, and certainly appropriate for being placed on the base of the Statue of Liberty.
Lazarus actually spent a couple of years in the 1880s travelling through Europe and learning more of the history of the Jews there. By the time she returned to New York, she was very sick, and she died in 1887. Emma Lazarus continues to be a well-known poet because of this poem, “The New Colossus.” In many ways, that is perhaps the best way to remember her – as someone who cared deeply about the United States, who was proud to be an American, and who wanted to welcome those who were persecuted in other countries to this country.
Now let’s answer a few of your questions.
Our first question comes from Iris (Iris) in China. The question has to do with three expressions, or terms: “in front of,” “ahead of,” and “before.” All three of these have a similar meaning. Let’s start with “in front (front) of” something. “To be in front of” means to be in a position just ahead of something else. So, if I am standing in a line, in a queue, waiting for service at the bank, I have someone in front of me and I have someone behind me. The person in front of me will get service right before I get service.
“Ahead of” (ahead of) means the same as “in front of,” and can usually be used in the same situations where you would use “in front of.” It can be used to describe someone’s physical position. However, it can also be used to mean the same thing as the third term in this question, “before.” “Ahead of” can mean prior in time, or before something happens.
So, you can talk about someone finishing his test “ahead of the other students.” He wasn’t physically in front of the other students, but he finished his test “before,” in terms of time, the other students. The word “before” can actually mean either something related to time or to physical location. Although usually we use it to mean something related to time.
“Before,” when used to talk about “in front of” and location, often appears with the verb “to stand.” In somewhat more formal English, you can say, “I stand before you.” It’s a somewhat poetic way of saying, “I’m standing in front of you,” although the more normal meaning is “I am here talking to you.” For example, if you were in a courtroom before a judge. You are standing before the judge. “I stand before you, saying that I am innocent.” It’s a little more formal or perhaps a little bit more poetic way of expressing that idea.
Our next question comes from a Amauris (Amauris) in Cuba. Amauris wants to know the meanings of three different phrases or expressions: “as if,” “as though,” and “as for.” The truth is we could spend an hour talking about these three expressions, but let me just give you the brief definitions and uses of each.
“As if” means “as would be the situation if,” or “as would be the case if.” For example, “My brother acted as if he were innocent.” He isn’t actually innocent, but he’s pretending to be innocent. The use of the expression “as if” asks you to imagine a hypothetical situation – something that isn’t true, or at least isn’t true right now.
“As though” (though) means the same as “as if.” In most situations, you can use “as though” and “as if” interchangeably – one for the other. You might have noticed in my example for “as if” that I used the past tense, and not even a form of the past tense that you might associate with the example, which was with a third person singular pronoun. The use of “as if” and “as though” is one of the few cases where something called the “subjunctive mood” is used in English and changes the form of the verb.
However, in recent years, the use of the “subjunctive” in this case in English has become less and less popular. Nowadays you will hear people say and write things such as, “As if he was innocent,” instead of “As if he were innocent.” You will also hear the present tense used with “as if” and “as though.” “He acts as if he owns this room,” instead of, “He acts as if he owned this room.”
“As for” has a completely different meaning than “as if” and “as though.” “As for” (for) simply means “concerning” or “with regard to.” It's a little more formal than saying “regarding” or “concerning.”
For example: “As for Sally, she decided to leave her job last year.” “As for” there means “in talking about” or “referring to” Sally. You're telling the listener the topic of what your sentence is about. We probably would use this expression “as for” when we are talking about a number of different people or a number of different groups, and you want to make sure that the person listening to you understands the person to whom you are referring, or about whom you are speaking.
You can even use it for yourself. You could say, “As for me, I don't want to go to the movie.” You might say that if just previously you had been talking about other people wanting to go to a movie, or your friends wanting to go to a movie. You're trying to say, “Well, in my case. . .” “As for me, I don't want to go to the movie.” Notice that because “for” is a preposition, that the pronoun that comes after it is the object pronoun, “me.” You don't say, “As for I.” You say, “As for me.” You don't say “As for he.” You say “As for him.” It's the object of the preposition.
Finally, Imil (Imil) in Colombia wants to know the meaning of the expression “to take stock.” “To take stock” (stock) means usually to think about a situation or an event carefully so that you can make a decision about what to do – to examine your own life or a certain situation in your life in order to make a decision or to form an opinion about something.
Another meaning of “to take stock” is to make a list or to check a list of things that you own, especially if you have a store that sells things. If you have a store that sells shoes, every so often you would want to take stock of the shoes in your store. You’d want to go through and count the shoes to make sure that they’re all there or that perhaps someone hasn’t stolen some of them.
But in normal conversation, we use this expression “to take stock of” something in a more general way, meaning to think about something carefully or examine something carefully. “I need to take stock of my life.” I need to figure out why I’m here on this earth and what I’m supposed to be doing.
If you can answer that question, you can email me. My email address is eslpod@eslpod.com. Oh, if you have other questions about English, you can email me also.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational
Development.
Glossary
to be separated – for a married couple to stop living together, but to remain legally married
* After being separated for a year, Tomas and Luciana decided to get a divorce.
to give (something) another try – to attempt to do something again in hopes of a better outcome; to make a second try after failing the first time
* Anoop was having trouble logging into the website, but decided to give it another try before contacting tech support.
to freshen up – to wash one’s face and hands and perhaps change clothes in order to feel clean, usually after traveling or working
* After a long day at the office, Elin went to her room to freshen up for her date.
hostage – a person who held as prisoner until a certain wish or condition is met
* The bank robber said he would release his hostages once the police gave him an airplane that would take him out of the country.
safe – a strong and secure box or room where valuable items are kept for protection
* As soon as she got to her hotel room, Sophie put her passport and jewelry in the hotel room safe.
cowboy – a man who rides a horse and gathers and moves cattle (cows) on a ranch (large farm for keeping and raising animals)
* John Wayne and Clint Eastwood were famous for playing cowboys in movies.
to be descend from – to be a direct relative of or be directly related to someone who lived in the past
* Marianne was shocked to learn that she was descended from royalty.
to be well received – to get a positive response from an audience, other people, or general society
* The film was well received by audiences and was nominated for three awards.
to dedicate – to say that a piece of work, such as a book or film, was done in someone’s honor (while thinking of them), as a way of showing respect
* Christina dedicated her book to her father who had always encouraged her and told her that he knew she would be successful.
to persecute – to treat someone very badly because of his or her race, or political or religious beliefs
* There are many instances in history where homosexuals were persecuted and severely punished.
to huddle – for people to stand very close together, usually for warmth or comfort
* The family huddled together to stay warm while waiting in the cold winter air for their train.
to yearn – to want something very much; to wish for someone or something that has been lost or that one has been separated from
* After living overseas for nearly 20 years, Marco found himself yearning to return to his home country to spend the rest of his days.
in front of – in a position just ahead; in a position at the front section of something
* Put those flowerpots next to, not in front of, the front door of the house.
ahead of – in front of; before
* How many people are ahead of us in line?
before – in front of, usually a group; occurring ahead of another event
* George made the important announcement before the entire committee.
as if – as would be the case if; as would be the situation if
* Leona walked into the room as if she were the queen of England.
as though – as would be the case if; as if
* If we’re going to attend this party uninvited, we have to act as though we belong here.
as for – with regard to; concerning
* I’m glad we made a decision. As for these other issues, let’s discuss them next week.
to take stock – to compile a list of items a store has available for sale; to think carefully about a situation or event and form an opinion about it, so that one can decide what to do; to examine a situation carefully
* After the fire, we took stock of the damage and decided not to rebuild.
What Insiders Know
Century City and Fox Plaza
Located on the western side of Los Angeles, Century City is a 176–acre “commercial” (related to business) and “residential” (related to homes) “district” (an area of a country or city) that has almost 6,000 residents. The land on which Century City is located originally belonged to a cowboy and actor named Tom Mix. Mix used the land as a “ranch” (a large farm where cattle (cows) or other animals are kept and raised). Later in 1956, it became a “backlot” (an outdoor area in a film studio where large outdoor sets or false buildings are built and outside scenes are filmed) for the film company 20th Century Fox. In 1957, because of a series of expensive “flops,” movies that completely failed, 20th Century Fox decided to sell the land to a “developer” (person who builds new buildings to rent or sell, with the intention of making money).
The new owners wanted Century City to feel like a small city within Los Angeles, and in 1963, the first building, Gateway Building, was completed. Within a few years, several other buildings had also been constructed, including the Century Plaza Hotel and Century City Medical Plaza.
Today, Century City is home to Fox Plaza, a 35-“story” (floor), 492-foot “skyscraper” (very tall building with many floors) built in 1987. The building serves as 20th Century Fox’s official “headquarters” (main office). The former U.S. President Ronald Reagan had once rented the “penthouse” (apartment on the top floor of a building) on the 34th floor of the building several years after he was no longer president.
Fox Plaza has also been featured in a few films released by 20th Century Fox. In Die Hard, Fox Plaza was used as a “fictional” (imaginary; not true) building called Nakatomi Plaza. At the time of filming, Fox Plaza was still “under construction” (being built; not completed). In fact, in one of the scenes, Bruce Willis’ character explores an unfinished floor, which was an actual unfinished floor of the Fox building at the time.