= 1820
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 515.
This is English as a Second Language Podcast’s English Café episode 515. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download this episode’s Learning Guide, an eight- to ten-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store with additional courses in English, as well as our ESL Podcast Blog. You can also follow us on Twitter at @eslpod, or like us on Facebook at facebook.com/eslpod.
On this Café, we’re going to talk about what are referred to as “historically black” colleges and universities in the United States. We’re also going to talk about a famous American actress of the early twentieth century, Mary Pickford. And as always, we’ll answer a few of your questions. Let’s get started.
A historically black college or university is a college or university that was created to pay special attention to or focus on educating African-American or black students in the U.S. We call these colleges and universities “historically black” because that’s how they started. It doesn’t mean that they’re just for African Americans, certainly not nowadays. These colleges and universities have students from all sorts of backgrounds, but historically – that is, in terms of the individual histories of these universities – they were primarily for African-American students.
Why are there black colleges or universities? Well, because once again, if you go back and look at the history of the United States, especially in the nineteenth and first half of the twentieth centuries, African Americans were not allowed to go to white colleges and universities, or those colleges in universities that had white students, especially in the southern part of the United States. There were many African Americans who were not educated or allowed to be educated. That situation ended in 1865, at the end of the American Civil War.
Even before that time, however, at least two colleges were started in the northern states for African-American students – one in Pennsylvania and one in Ohio. The Pennsylvania college was started by a white farmer by the name of George Cheyney. He started something called the “Institute for Colored Youth” in Philadelphia. The word “colored” (colored) is an old-fashioned term to describe African Americans. However, we do not use that term anymore, and you should definitely not use it when referring to black Americans or African Americans.
Cheyney founded this college. When we say someone “founded” something, we mean he established or created this institution or organization. The purpose of Cheyney’s institute was to train teachers – teachers who would work in high schools and elementary schools. This was in fact the purpose for a lot of colleges and universities that were started in the early part of our history. Many of the colleges and universities that you see today began as teacher training institutes, often with just two years of instruction.
The school that Cheyney started still exists today. It is now named after him. It’s called Cheyney University, and it does more than just educate teachers. It’s part of the University of Pennsylvania system – a collection of colleges in the state of Pennsylvania. Pennsylvania is located in the eastern part of the United States, and is one of the original thirteen states.
A little later on, in 1856, another historically black college was founded, this time in the state of Ohio, which is just west of the state of Pennsylvania. The college was started in a small town that was then known as Tarawa Springs, but it is now known as Wilberforce. If you know something about British history, about English history, you might recognize the name “Wilberforce.” William Wilberforce was one of the most important abolitionists in the history of Great Britain. An “abolitionist” (abolitionist) is a person who tried to end the practice of slavery.
So, this college was named after the famous English abolitionist William Wilberforce and was called Wilberforce University. It was created primarily to help African Americans who had escaped from the southern states, where slavery was still legal, into the northern states. We don’t have time to talk about it today, but the system that was used for helping slaves escape from the southern states to the northern states during this period was called the “Underground Railroad.”
After the practice of slavery was made illegal in 1865 in all states of the United States, people who were slaves – blacks who were slaves – became free. The U.S. government then decided that it would create its own programs to help slaves build new lives and especially get an education. There was a special department set up in the southern states called the Freedmen’s Bureau. The word “freedmen” (freedmen) refers to people who were once slaves who were now free. A “bureau” (bureau) is just another name for an office or a department.
One of the many things that the Freedman’s Bureau did to help African Americans was to create some colleges for them. They started a college in Atlanta, Georgia, called Atlanta University, although it is now called Clark Atlanta University. In 1865, the Bureau also started Howard University – located in our nation’s capital, Washington, D.C. – in 1867, and in that same year Morehouse College, in again Atlanta, Georgia.
Some of these schools had only male or only female students, but most of them were what we call “co-educational,” meaning both men and women could attend classes there. In addition to the government giving money to start these colleges, there were individuals who also gave money. One very well-known rich individual who gave money to these colleges was John D. Rockefeller, a very rich American who gave money to lots of different organizations in the nineteenth century.
There were basically two types of historically black colleges. The first is what we would call a “vocational school.” A vocational school is a school that teaches students how to do a specific type of job, such as become a plumber or, nowadays, repair cars. Vocational schools are still popular in the United States. We still have them in many different places, including here in Los Angeles. Some of these historically black colleges, then, were vocational schools that taught African Americans how to work in agriculture and in factory jobs.
The second type of historically black college – colleges such as Howard University and Morehouse College – were considered what I guess we would call “intellectual schools.” “Intellectual” refers to the traditional things you would associate with the university – the study of philosophy and science and literature and so forth. The purpose of these universities and colleges was to give students the traditional liberal arts education. The term “liberal (liberal) arts” refers to the study of literature, philosophy – what we now call the “humanities.”
In modern American universities, “liberal arts” refers just to those topics. It usually doesn’t describe things such as science, math, and engineering, although traditionally in the liberal arts, these subjects were also included. But in modern American universities, the college of liberal arts at a university, for example, would not be the place where you would take science and math classes. You would take those in a different part of the university. But at this time, the liberal arts really did encompass, or include, many different kinds of knowledge.
I’ve been calling these colleges “historically black” colleges or universities, but this term actually wasn’t used until the twentieth century, until 1965, when the U.S. government passed a law called the “Higher Education Act.” The word “act” (act) just means law. “Higher education” refers to colleges and universities. So, the Higher Education Act is a law that created government programs and government regulations and rules for colleges and universities. The law was considered by many to be part of the larger civil rights movement of the 1960s – an effort to get better treatment for African Americans and other minorities in the United States.
While you will find African-American college students at almost every college and university in the United States nowadays, these historically black colleges and universities continue to be very influential. Many of the leaders of the African-American community have studied at one of these colleges. Currently, there are over 100 historically black colleges and universities in the United States. I repeat that you don’t have to be African American to go to these colleges, and if you go to them you will find that they have a mix of students, even though the biggest group of students will probably still be blacks.
Some of the most famous African Americans have attended these colleges and universities, including the author Toni Morrison, the singer Roberta Flack, the nuclear physicist Roderic Pettigrew, the movie director Spike Lee, and most famously of all, the Nobel Peace Prize winner the Reverend Martin Luther King Jr. In terms of geography – where these colleges and universities are located – most of them are in the American South, in the states that had slavery until the end of the Civil War, and where the majority of African Americans were living after the end of the Civil War.
Let’s turn now to a famous American actress, writer, and businesswoman, Mary Pickford.
Mary Pickford’s real name was Gladys Mary Smith, and she was born in April of 1893 – not here in the United States, but in that little country just north of us called Canada. You may have heard of it. She changed her name to Mary Pickford, however, early on in 1906, when she was just, what, 13 years old, which is kind of unusual, but you’ll understand why when you learn that her parents were actors – and interestingly enough, she became an actor. It’s not unusual for actors and actresses to change their name when they start performing.
Pickford’s parents were actors, but her father died when she was very young. She began performing herself when she was only five years old, in the shows that her mother performed in. She went on tour when she was just eight years old and was performing in plays in New York City by the time she was 18. When I say she “went on tour,” I mean she went traveling from city to city, performing in this particular show.
Pickford began acting in movies in 1909 when she was 16 years old. At this time, the movie industry was just starting in the United States. If you were an actor or an actress, you were a theater actor or actress – you performed in theatres, in plays. Pickford got her start – she began – as an actress in the theater, but by the time she was 20 years old, she was only doing movies.
She worked for one of the most famous movie directors of this period, a man by the name of D. W. Griffiths. Griffiths had a company, what we would call a “production company,” called Biograph Studios. A “production company” is a company that organizes different kinds of entertainment, including dancing or theater or, in this case, movies.
Pickford quickly became a very popular movie actress, one of the first popular movie actresses in American history. She was a very beautiful woman and she was very talented. She was known in particular for having very beautiful blonde hair. She had very curly hair. “Curly” (curly) describes hair that is not straight, that grows in circles. I had very curly hair when I was growing up. It’s true. If you look at me now, you won’t believe it since I don’t have any hair at all, but when I was younger, I had curly hair.
Pickford became so popular that some Americans started calling her “America’s Sweetheart.” A “sweetheart” (sweetheart) is a very lovable or pleasing person, someone that many people like. The term “sweetheart” is usually used to refer to your boyfriend or girlfriend, your husband or wife. It’s what we call a “term of endearment,” the sort of thing you say to someone to show that person that you love him or her.
So Mary Pickford was America’s Sweetheart, and because she was so popular, she got paid a lot of money. In 1917, she was paid $350,000 for every movie she made. Now in today’s dollars, that would be somewhere over four million dollars, which is just a little bit more than I get paid for doing this podcast. So that’s pretty good, right?
Pickford was not only a talented actress. She was also a very good businesswoman. She, the director D.W. Griffiths, and the actor Charlie Chaplin, along with the actor Douglas Fairbanks, founded their own movie company, called “United Artists Corporation.” This was a production company that became the most successful and important production company for movies in the United States during the early twentieth century. In fact, it is still around as a movie company.
The decade of the 1920s was definitely the best period in Mary Pickford’s career, though it wasn’t without difficulties. She divorced her first husband and married the actor Douglas Fairbanks. The two became the most popular couple in Hollywood. They were sort of the Brad Pitt and Angelina Jolie of the 1920s, I guess we could consider them (though much better actors than both).
People around the world who watched movies became interested in their lives just as people, for whatever reason, are interested in the lives of Hollywood actors and actresses today. The two were known as the “King and Queen of Hollywood” because they were so successful. During this time, because they had so much money, they built a huge house just outside of Los Angeles that they called “Pickfair” – a combination of their two names, of course, “Pickford” and “Fairbanks.”
Ah, but the success would not last. Technology was changing the movies, and by the late 1920s, there was now what were called “talkies,” or “talking pictures” – movies that had sound when the actors spoke. This is in contrast to the way movies were made up until this time, where they were silent. A “silent movie,” or a “silent film,” is one in which you can’t hear the actors speak, although there may be music that goes along with the movie.
The first talking movies were released in 1927, and some actors and actresses were not able to make the transition, we might say – weren’t able to make this change from silent movies to talking movies. Pickford was not able to make this change. She did make a talking movie called Coquette in 1929, and she even won an Academy Award or an Oscar for her performance. But after acting in 194 movies, she retired from acting in 1933. But she didn’t retire completely from the movie industry. She continued to work at United Artists Production company as the vice president of the company and wrote and produced movies as well.
If you know anything about marriages here in Hollywood, here in Los Angeles, you know that they often don’t last very long, especially between famous people. This, sadly, was also the case for Pickford and Fairbanks. They divorced in 1935, and Fairbanks quickly remarried a woman with whom apparently he had been having a relationship even before he divorced. Pickford also remarried, this time to a man by the name of Charles Buddy Rogers. This third marriage of Pickford’s was much more successful than her first two. She got married in 1937 and remained married until her death in 1979.
The end of Pickford’s life was not a happy one – again, not unusual for Hollywood actors. After her career as an actress and her marriage to Fairbanks ended, she began drinking a lot of alcohol. She and her third husband adopted some children, but she didn’t get along with those children very well. “To adopt” (adopt) means to legally make another person’s child your own.
In 1979, shortly before her death, Mary Pickford was given a special Academy Award, a special Oscar called a “Lifetime Achievement Award.” Pickford, however, was not well enough, not healthy enough, to accept the award in person. She was unable to go to the ceremony, to the event. She died in 1979, very close to where I live, in the city of Santa Monica, California. If you go back and watch any of the old silent movies from the first part of the twentieth century, you will almost certainly see Mary Pickford. She was, as I say, one of the most well-known and famous actresses of her generation.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Joshua (Joshua) living in Canada, but originally from China. Joshua wants to know the difference between “to infer,” or “to deduce,” and “to derive.” Let’s start with “to infer” (infer).
“To infer” is to come to some conclusion or to form an opinion based on a certain set of facts. The opposite of “inferring” is “implying.” “To imply” (imply) means to suggest a certain conclusion in the way that you present evidence or facts. So, if I’m talking to you, I can imply that it would be nice if you bought me a Christmas present. You listening to me could “infer” that I wanted a Christmas present. So, the “inferring” part is something you do from what you are reading or hearing; the “implying” is what a person does in terms of trying to get other people to reach a certain conclusion.
“To deduce” (deduce) means to use logic or reason to come to some sort of conclusion based on certain principles. I don’t want to go into the technical differences between “deduction” and “induction” when it comes to logic. More generally, the verb “to deduce” is used to talk about someone who looks at certain principles and facts, and comes to a conclusion. It’s often used in conversational English to mean the same as “I figured out” or “I came to this conclusion based on facts or evidence that I examined.”
“To derive” (derive) means to take something from something else, to base or get some concept from another concept. When you “derive” something, you create something new, but it’s based on or comes from someone else’s creation or idea. So, for example, you could say that Plato “derived” his system of ethics from Socrates’ teaching. The two things are not identical, but one comes from the other.
We also use this verb “to derive,” in linguistics when we’re talking about where a word comes from. The word “mortal” (mortal) in English refers to death. “Mortal” is derived from a Latin word “mors” (mors), meaning death. When you “derive” something from something else, you’re creating something new based on something that already existed. “To deduce” and “to infer” are intellectual actions or activities that relate to coming to a conclusion. “To derive” is about creating something that didn’t exist before from something that did exist before.
Our second question comes from “Muhammed” (Muhammed) in Iraq. The question has to do with two phrasal verbs, “to clean out” and “to free up.”
“To clean out” means to thoroughly and completely remove everything that is inside some space. For example, if I clean out my desk, I’m going to remove everything that is in my desk right now – the pens, the papers, the notes, the computers, everything is going to be removed. I’m cleaning out my desk. If you work for a company and you’re fired, your boss might ask you “to clean out your desk” – remove everything that is yours from that particular space.
You could clean out a room. You could remove all the furniture – the chairs, the tables, and so forth – from a room. In some ways, “to clean out” means something different than simply “to clean.” “To clean” means to remove dirt or some substance that is on an object. “To clean out” means to remove things from a certain space. Often when you have a two-word phrasal verb, the preposition just is used for emphasis, but here it really does change the meaning.
“To free up” means to either remove something or stop doing something so there is either time or space for something else. You might, for example, need to meet with one of your coworkers at work, and you have a very busy schedule. You say to the coworker, “Let me free up some time so we can talk about this project.” You cancel another appointment or you decide not to do things you were going to do in order to “free up time” for your coworker.
You could also “free up” space on your desk. You could remove something so that there would be space now for more papers or books. Most commonly, however, people use this phrasal verb nowadays to refer to time and to one’s schedule. “To free up time on your schedule” (“to make room for,” we might also say).
Finally, a question from Geturu (Geturu) in the Democratic Republic of Congo. The question has to do with two different terms – “civil disturbance” and “civil unrest.”
“Civil” (civil) has a couple of different meanings in English. Here it refers to people who live in a certain place, to the population. It is sometimes used to distinguish between those who are in the military and those who are not. We talk about the “civil population” versus members of the military of a country.
A “disturbance” (disturbance) is some sort of violent or noisy behavior in public, where other people can see you and hear you. A “civil disturbance” would be when a group of people living in a country or a certain area show that they are unhappy, that they are upset. Often it is related to a protest against the government – in some places, directly against the military of a country. That’s a “civil disturbance” – any time where people are breaking the law using violence and so forth in order to protest or show their anger.
“Civil unrest” (unrest) is usually used in the same way as we use “civil disturbance” – to describe a group of people who are using violence in order to protest against something. I suppose it’s possible to use “civil unrest” in situations where there is no actual violence by people.
The two terms can be used to mean the same thing in most cases, I think. “Civil unrest” might describe a longer-term situation in a country. To say, “There is civil unrest in country X” usually would mean that it’s not just happening today. It has been happening for a long time. A “civil disturbance” might describe a more limited set of circumstances, where you have something happening on a certain day or over a limited number of days. That might be one way that we would use these two terms differently.
If you’re reading in the newspaper that a certain country has a lot of “civil disturbances” or “civil unrest,” you might want to pick a different country for your vacation next year – just an idea.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to me again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational
Development.
Glossary
to found – to create or establish an institution or organization
* The United Nations was founded on October 24, 1945 after World War II with the purpose of encouraging cooperation between countries.
Underground Railroad – a system of secret routes, with hiding places used to help slaves in southern states escape to freedom in northern states and Canada
* Historians believe that over 100,000 slaves escaped the south and slavery using the Underground Railroad between 1800 and 1865.
bureau – an office or department that has a specific job or goal, usually in the government
* Mikki works for the bureau that is in charge of providing funding for special education programs in elementary, middle, and high schools.
coeducational – a situation in which men and women are educated together
* Sabine felt more comfortable in classes with only other women so decided to attend an all-women’s college instead of a coeducational college.
vocational – a school or program that teaches students specific job-related skills
* Our college has vocation programs in bookkeeping, forestry, and welding.
intellectual – involving the ability to understand and think through abstract ideas, or ideas that cannot be seen or touched
* After dinner, the two women found themselves in an intellectual discussion about whether government programs to support poor people are helpful.
Liberal Arts – fields of study such as literature, science, math, and philosophy that are not specifically professional or technical subjects, intended to give students are broad or general knowledge of many subjects
* In many liberal arts colleges, students must take courses in a number of different fields before deciding on a focus for their more advanced studies.
higher education – education after high school, especially college or university
* Many people agree that getting a higher education is necessary today to qualify for the best jobs.
to go on tour – for a group of performers to travel to different cities or countries to perform a show
* When the band released their newest album, they went on tour and visited over 40 countries to perform shows for their fans.
production company – a company that creates different types of entertainment, such as dance, theater, or film
* The production company hired the director and found funding for the film.
sweetheart – a very lovable or pleasing person, liked by many people
* When the little girl gave her grandmother a big hug, her grandmother smiled and said, “You are such a sweetheart!”
to adopt – to legally make another person’s child one’s own, raising that child as part of one’s family
* Many American celebrities have adopted children from other countries such as Vietnam, Mali, and China.
to infer – to form an opinion based on evidence; to reach a conclusion based on facts
* What can be inferred based on the rise in violent crimes in this area?
to deduce – to use logic or reason to form a conclusion or opinion about something; to decide something after thinking about the facts
* Careful examination of the data allowed us to deduce the cause of death.
to derive – to take or get something from something else; to base a new concept on a previous one
* These beautiful dyes are derived from plants and flowers found in the desert.
to clean out – to thoroughly and complete clean the inside of something
* We need to clean out the car if we hope to fit these three suitcases in the trunk.
to free up – to do something to create more space or room for something else; to do some work or task in order for someone to be available for something else
* If you deleted these videos from your computer, you’ll free up more room for music.
civil disturbance – for a group of people to protest and to show anger, sometimes by breaking the law and/or with acts of violence; to riot
* The police chief expected acts of civil disturbance at the conclusion of the trial.
civil unrest – for a group of people to protest and to show anger, sometimes by breaking the law and/or with acts of violence; to riot
* Many people believed that the elections were rigged, resulting civil unrest across the country.
What Insiders Know
United States v. Virginia
United States v. Virginia was an important legal case that determined whether schools could “exclude” (not include; not allow) girls or women as students. The case was fought between the U.S. Department of Justice and the Virginia Military Institute (VMI). The U.S government took the military college to court because it wanted to challenge the college’s male-only “admission policy” (rules on who is allowed to become a student). The U.S. Department of Justice filed a “discrimination” (unfair treatment of certain categories of people or things, especially because of race, age, or gender) “lawsuit” (court case) against VMI in 1990. During this time, the State of Virginia proposed a “parallel program” (a program that is the same or equal to another) for women called the Virginia Women’s Institute for Leadership (VWIL) located at Mary Baldwin College.
In 1996, the U.S. Supreme Court, the highest and most important court in the country, “struck down” (made illegal) VMI’s male-only admission policy, voting 7 to 1. One of the judges “presiding” (hearing evidence and making legal decisions) over the case, “Justice” (judge) Ruth Ginsburg, wrote for “majority” (more than 50%) of the Supreme Court judges, stating that VMI did not convince the court that their “exclusion” (leaving out; not allowing of) women was “justified” (supported by good reasons).
After the decision, the VMI tried to become a private college so that it would not need to follow the “federal” (national) rules set by this court decision. However, the U.S. Department of Defense said that it would remove its program to help pay for students to study at the college if it become a private college. In 1997, VMI’s “board” (group of people who make high-level decisions) voted 8-7 to admit women to the college. VMI was the last all-male public military university in the United States.