
= 003 - Florence and the Renaissance
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义


Hi, I'm John Green, and this is Crash Course European History. So, as you'll recall from our previous episode, a declining 下降的 European population due to disease and war in the 14th century meant that labor 劳动力 had become much more valuable, which shifted 改变 long-held beliefs about how society should be organized.

Amid 在…中间 all this upheaval 动荡；剧变, and to some extent 某种程度上 because of it, the Florentine 佛罗伦萨的 author Francesco Petrarca, aka Petrarch, was unleashing 宣泄 his critique 批评 of 14th century life. "Living," he lamented 哀叹, "I despise 鄙视 what melancholy 忧郁的 fate has brought us wretches 可怜人 in these evil years." Oh, Petrarch, are you sure you weren't writing about now? It's almost like people always feel like they live in the worst possible time.

At any rate 无论如何, not happy with the state of things in Europe, he turned to Plato, Cicero, and other ancient writers, whom he thought of as residents 居民 of the Old Age. In fact, Petrarch gave the era 时代 in which he lived its name — calling them the "middle ages" just as his writing and research helped usher in 开创 a New Age that we now call the Renaissance 文艺复兴.

[Intro]

According to Renaissance author Leonardo Bruni in the early fifteenth century, "Francesco Petrarch was the first with a talent sufficient 足够的 to recognize and call back to light the ancient elegance 优雅 of the lost and extinguished 熄灭的 style." The Renaissance, meaning revival 复兴 or renewal 重生, harkened back to 回想起 what was seen as the bright light of classical antiquity 古典时期, which had then been obscured 掩盖 in the dark and ignorant 无知的 Middle Ages.

But in some ways, the Middle Ages existed simultaneously 同时地 with the Renaissance. Like, just as scholars 学者 were reviving 复兴 translations of Plato and integrating 融合 knowledge from the Islamic 伊斯兰的 world, the bubonic plague 腺鼠疫 went on killing people; and in Petrarch's hometown, ordinary people like the Ciompi were vigorously 强烈地 protesting 抗议 living conditions. Which brings us to an old question here at Crash Course: Was the Renaissance really a thing? Was it in fact just a continuation 延续 of the medieval world? Or was it the dramatic 巨大的 change that Renaissance thinkers believed it to be?

The writers and thinkers of the Renaissance scoured 搜索 monasteries 修道院 for ancient works, initially 最初 written or at least influenced by Roman writers. It was from this manuscript-hunting 手稿搜寻 — especially for works by Cicero, and Tacitus, and Quintilian — that Renaissance scholars began to focus on so-called humanism 人文主义. That is to say, they became more interested in worldly 世俗的 and human concerns.

And because the Renaissance really was a revival, this new thought was based on learning about old or ancient ways, especially in the study of the "humanities 人文学科." The three liberal arts 文科 of grammar 语法, rhetoric 修辞, and logic 逻辑 led to the so-called sciences of theology 神学, philosophy 哲学, laws, and medicine.

The study of the humanities as developed by the ancients focused not on the heavens 天堂 or saints 圣徒 but on human speech or rhetoric, human logic, and the correct use of language. And by language, of course, they mostly meant Latin — being able to write in Latin and even perform Latin orations 演说 was seen as key to a fully educated life, as every high school Latin teacher will be happy to tell you.

Competence 能力 in these fields was seen as crucial 至关重要的 to developing the self and a prerequisite 先决条件 for joining Florentine or Venetian 威尼斯的 elites 精英. Like, Venetian youth Lauro Quirini, for example, studied the humanities at the University of Padua and then was sent to work in a Venetian enterprise 企业 on Crete, fully prepared for his new job as a commodities trader 商品贸易商, although he also worked as a translator 翻译 and a writer. You might say he was a real Renaissance Man. I'm sorry.

The Italian city-states 城邦 were the heartland 中心地带 of the early Renaissance. In these prosperous 繁荣的 cities, artists, composers 作曲家, writers, and scholars thrived 兴盛 along with the commerce 商业 that paid for everything. Urban 城市的 merchants 商人 and manufacturers 制造商 built a brisk 活跃的 business that brought in products and ideas from around Afroeurasia. And some families achieved immense 巨大的 wealth, which allowed them to support the world of Renaissance thinkers and artists in a system called patronage 赞助.

I would like a phenomenally 惊人地 wealthy patron 赞助人 like Lorenzo Medici. If any of you are out there, I am available. And I would like all your ducats 杜卡特（旧时欧洲金币）. You can visit patreon.com/crashcourse. But at any rate, banking institutions 机构 also sprang up 涌现, and bankers funded 资助 civic 市政的 events and the construction 建设 of lavish 奢华的 cathedrals 大教堂.

Bankers also backed 支持 or personally paid for the building of masterworks 杰作 in the classical style — that is, in the style of the restrained 克制的, stately 庄重的 design of the pre-Christian Roman Empire. Did the Globe open? Is there a neoclassical 新古典主义的 piggy bank 储蓄罐 in the center of the world? There is!

You know all those white statues 雕像 of the Renaissance that take their whiteness from the white statues of the ancient Greeks and Romans? Yeah, they were not white! They were painted. Like, here are some of our best guesses of what actual classical statues looked like, and as you can see, not very much like neoclassical white piggy banks.

Nonetheless 尽管如此, the idea of unpainted marble 大理石, or porcelain 瓷器, or whatever has proven so powerful that even though we now know that ancient statues were painted, we still don't paint our neoclassical ones.

Bankers also financed 资助 artists needing funds to complete their works, including Botticelli and Michelangelo. And city governments themselves were also important patrons of the Renaissance, while individual leaders often spent as much as six percent of their personal income 收入 on the arts.

Why? Well, largely for the same reason rich people fund art and buildings today — for status 地位, for recognition 认可, and maybe even for the love of beauty. But also, funding public art and cathedrals and the like served to legitimize 使合法化 the wealth of these families. The Church could not very well condemn 谴责 merchant 商人的 wealth if it was used to build churches, nor could the governments that came to depend on it. We see this again and again throughout history — wealth supports institutions 机构 that in turn legitimize that wealth.

Regardless 无论如何, in these artworks, you can see the paradoxes 矛盾 of the Renaissance — paganism 异教 is combined with Christianity, as it often had been throughout Christian history. Profit-oriented 追求利润的 bankers financed the Church, which was run by priests 牧师 who'd taken a vow of poverty 贫穷誓言, and founded by a figure who in the gospels 福音书 overturns 推翻 the tables of moneylenders 放债人 in the temple.

Also, in these city-states, access to a more humanistic 人文主义的 educational approach helped boost 促进 economic growth and fueled 推动 the creation of much art and architecture 建筑 that is still really influential 有影响力的.

Now, many city-states participated in this humanist 人文主义的 revival, but its headquarters 总部 was undoubtedly 无疑地 Florence. Let's go to the Thought Bubble.

Artists of the time were following ancient styles and taking them further.
Visual artists, like Sandro Botticelli and Michelangelo,
focused on human dignity 尊严 and realistic 写实的 details.
Botticelli's portraits 肖像 of Florentine citizens display 展现 the distinct 独特的 features 特征 of his subjects 描绘对象,
while his depictions 描绘 of religious individuals show, for example, a plump 丰满的 infant 婴儿 Jesus realistically reaching for his mother's garments 衣物.
Botticelli's portrait of the long-dead Dante similarly displayed his long, thin, and pointed 尖的 nose
rather than some idealized 理想化的, formulaic 程式化的 hero.
And Michelangelo's "David" presents truly human characteristics 特征
even as it sought to copy ancient sculptural 雕塑的 styles.
Across the spectrum 范围 of Renaissance art, anatomical 解剖学的 accuracy 精确性 flourished 盛行,
which you can see in Michelangelo's sculptures 雕塑作品
and also in the work of fellow Florentine Leonardo da Vinci —
both artists, incidentally 顺便提一句, were able to render 描绘 the human form in part because they both dissected 解剖 cadavers 尸体.
And nature, as a setting 背景 for humans and thus humanism, was also glorified 赞美 in Renaissance art,
as you can see in the *Birth of Venus*. Botticelli's painting focuses on the mythical 神话的 goddess 女神 from the classical world
but at the same time she's about to be clothed in the flowers found in the natural world of the countryside.
In short, the artists of the Renaissance focused on situating 安置 a realistically depicted human body
in both its natural environment and its civic 城市的 setting.
Thanks, Thought Bubble. But amid this prosperity 繁荣 and cultural revival, Florentine history was marked by a succession 一连串 of economic and natural shocks 冲击, class divisions 分裂, corporate 企业的 rivalries 竞争, party struggles, conflicts 冲突 with the church, and especially political crises 危机.

And those arose from threats 威胁 of external 外部的 invasion 入侵 as well as internal 内部的 tyranny 暴政 and discontent 不满 among the lower classes. Like Venice, Florence took great pride in being a Republic 共和国, although it was a bit different from contemporary 当代的 republics and exceedingly 极其地 unstable 不稳定的.

Like, there weren't really elections; instead, names of members of Florence's guilds 行会 would basically be drawn out of a large leather bag, and if your name was drawn, you got to serve on the Signoria 执政团, which ran the city. And if you weren't psyched 对…热衷 about the job, no worries — new Signorias were chosen every two months, which might make it seem like lots of people were able to participate in civic life, but:

In order to be a member of a guild, you needed to be debt-free 无债务的 and male and well-connected 人脉广的,
and in truth the lotteries 抽签 were often rigged 操纵, with wealthy families tending to win places on the Signoria.
Also, there were frequent 频繁的 coups 政变 and countercoups 反政变, and the Republic would often cease to be republican and at times become downright 完全地 monarchical 君主制的. It was all quite *Games of Thrones*y — one might even say that it was a bit Machiavellian 马基雅维利式的（为达目的不择手段的）.

And no wonder — the political theorist 政治理论家 Niccolo Machiavelli did live in Florence. We'll discuss him more next week, but for now, it's important to know that he saw — and suffered through — much of this turmoil 动荡, including the rise and fall and rise again of the Medici family.

The Medicis were tremendously 极其地 powerful in Florence, although contrary to 与…相反 what you might read they weren't the only important family in the Renaissance. But they did make huge sums in banking and investing, and were important patrons to artists — in fact Michelangelo carved 雕刻 one of their tombs 陵墓.

Cosimo Medici and his grandson Lorenzo dominated 主导 the second half of the fifteenth century in Florence, while successive 连续的 members of the family perpetuated 延续 its power and patronage by serving as popes 教皇 in the next centuries.

Machiavelli argued that the Florentine Renaissance's Golden Age ended with the death of Lorenzo de Medici in 1492 and the invasion 入侵 of the "barbarians 野蛮人." Of course, "Barbarians" mostly means "Not Us" throughout history — in fact the word itself comes from a feeling that the language of Barbarians sounded like bar bar bar bar bar. Anyway, these particular Barbarians were French, so I guess it sounded like Bar. I wasn't very good at High School French.

And so we return at last to the old question: Were there really broad shifts away from the religiofication 宗教化 of all aspects of European life toward the human and the secular 世俗的 in the Renaissance? Like, Michelangelo sculpted 雕刻 David, but he also painted the ceiling of the Sistine Chapel 西斯廷教堂.

Perspective 视角 matters when you ask these questions — something important and new was happening in 14th century Florence (and Venice and Milan and so on) among merchants and intellectuals 知识分子. But the lives of average people, especially peasants 农民, were not much transformed 改变 by this humanist thinking — at least not in the short run.

But in other ways, ordinary people did also have a Renaissance — ancient authors were translated into Italian and French, which allowed those without access to Latin to read Cicero and the like. But of course most Italian peasants couldn't read anything.

Historians also debate whether women experienced a Renaissance. Women were among the patrons of the arts: Isabella d'Este sponsored 赞助 musical events and loved Petrarch's poems so much that she had music composed for them. She also sponsored painters, maintaining contacts with Leonardo da Vinci.

But, Isabella d'Este and her similarly accomplished 有成就的 sister Beatrice are often seen as the exception 例外. In general men, according to fifteenth century writer Laura Cereta, discounted 轻视 women's intellectual 智力的 worth 价值.

Deliberately 刻意地 following Petrarch's path as he had followed Cicero's, Cereta wrote a famous letter to one misogynist 厌恶女性者 that read in part: "I cannot tolerate your having attacked my entire sex... With just cause I am moved to demonstrate how great a reputation for learning and virtue 美德 women have won by their inborn 天生的 excellence 优秀, manifested 展现 in every age as knowledge..."

Also, the rise of Roman legal thinking meant the rise of the Pater Familias 家父（古罗马家庭中的男性家长）. The idea that the father is the center of every family, and also the center of power.

All of which is to say that the Renaissance saw tremendously important developments in the intellectual 知识的 and cultural life of Italian city-states, developments that would soon be exported to other communities.

But we have to be able to shift perspectives — to the Medicis, the Renaissance was a thing. To many peasants, it was not. We remember the Renaissance today partly because it's helpful for historians to periodize 划分时期 history to frame their analyses 分析, and partly because so much Renaissance thinking shapes our thinking.

And I think it's worth remembering how the ideas of the Renaissance continue to resonate 产生共鸣 for us today. Consider, for example, the feeling that the current age is so full of corruption 腐败 and destruction 毁灭 that we must return to the purity 纯洁 of some bygone 往昔的 era of greatness. That Renaissance thinking seems very relevant 相关的, indeed. Thanks for watching. I'll see you next time.

Sources
Hunt, Lynn et al. *The Making of the West: Peoples and Cultures*, 6th ed. Boston: Bedford St. Martins, 2019.
Donald R. Kelley, *Renaissance Humanism*. Boston: Twayne, 1991.

'''

== 中文释义


大家好，我是约翰·格林，这里是《速成欧洲史》。正如我们在上一集提到的，14世纪由于疾病和战争, 导致的欧洲人口减少，使得劳动力变得更为珍贵，*这也动摇了长期以来关于"社会应如何组织"的固有观念。*

在这场动荡中，且在一定程度上正因如此，**佛罗伦萨作家**弗朗切斯科·彼得拉克（又称**彼特拉克）开始对14世纪的生活提出批判。**“活着，”他哀叹道，“我鄙视这悲惨的命运，在这些灾难年间将我们这些可怜人带入如此境地。”哦，彼特拉克，你确定你不是在写现在吗？仿佛人们总觉得自己生活在最糟糕的时代。

**无论如何，他对欧洲的现状不满，**于是转向柏拉图、西塞罗和其他古代作家，他将这些人视为“古代”的代表。事实上，彼特拉克为自己所处的时代命名——他称其为“中世纪”，而他的写作与研究, 则助力开启了一个我们如今称为“文艺复兴”的新时代。

[片头]

15世纪初，文艺复兴时期作家莱昂纳多·布鲁尼曾说：“弗朗切斯科·彼特拉克是首位有足够才识去Recognize, 并重新点亮已然消逝与熄灭之文风的古典雅致的人。”*“文艺复兴”意为“复兴”或“重生”，它回望被视为"古典时代明亮光芒"的古希腊罗马文明，而这光芒在黑暗蒙昧的中世纪曾被遮蔽。*

**但在某些方面，中世纪与文艺复兴是并存的。**例如，当学者们重新翻译柏拉图著作, 并吸收伊斯兰世界的知识时，腺鼠疫仍在夺取人命；在彼特拉克的家乡，像“梳毛工”这样的普通人, 正激烈抗议生存条件。*这就引出了《速成课程》里的一个老问题：文艺复兴是否真的是一个独立的“时代”？它是否只是中世纪的延续？还是如文艺复兴思想家所认为的，是一场剧烈的变革？*

文艺复兴时期的作家和思想家们, 在修道院中搜寻古代作品——这些作品最初由罗马作家撰写，或至少受其影响。正是从这种手稿搜集中——尤其是对西塞罗、塔西佗和昆体良作品的搜寻——*##文艺复兴学者开始关注所谓的“人文主义”。也就是说，他们对世俗和人类事务产生了更多兴趣。##*

由于文艺复兴确实是一场“复兴”，**这种新思想, 建立在对古代方式的学习之上，**尤其体现在对“人文学科”的研究中。*#语法、修辞和逻辑这三门文科，衍生出神学、哲学、法学和医学等所谓的“科学”。#*

**古人所倡导的##人文学科研究，关注的不是天堂或圣徒，而是人类的言语（修辞）、人类的逻辑，以及语言的正确使用。##**当然，这里的“语言”主要指拉丁语——能够用拉丁语写作，甚至进行拉丁语演讲，被视为受过全面教育的关键，正如每一位高中拉丁语老师都会乐于强调的那样。

在这些领域的能力，被视为"自我发展"的关键，也是跻身佛罗伦萨或威尼斯"精英阶层"的先决条件。例如，威尼斯青年劳罗·奎里尼, 在帕多瓦大学学习人文学科，随后被派往威尼斯在克里特岛的企业工作，为成为商品贸易商做好了充分准备，尽管他也从事翻译和写作。你或许会说他是真正的“文艺复兴人”。抱歉，我忍不住这么说。

**意大利城邦是早期文艺复兴的中心地带。**在这些繁荣的城市里，艺术家、作曲家、作家和学者蓬勃发展，**支撑这一切的商业也蒸蒸日上。**城市商人和制造商开展着活跃的贸易，从亚非欧大陆各地引入商品和思想。*一些家族积累了巨额财富，得以通过“赞助”体系, 支持文艺复兴时期的思想家和艺术家。*

我也想要一个像洛伦佐·美第奇那样极其富有的赞助者。如果你们中有人愿意，我随时待命，而且我想要你所有的金币。你可以访问patreon.com/crashcourse。但无论如何，银行机构也如雨后春笋般涌现，银行家们资助市政活动和宏伟教堂的建造。

银行家们还支持或亲自出资,  建造古典风格的杰作——即前基督教罗马帝国那种克制、庄严的设计风格。环球剧院开张了吗？世界中心有一个新古典主义的储蓄罐吗？还真有！

你知道所有**那些白色的文艺复兴雕像**吗？它们的“白”源于古希腊罗马的白色雕像？其实，**它们原本并不是白色的！它们曾被彩绘过。**例如，这是我们对真实古典雕像模样的一些最佳推测，如你所见，它们和新古典主义的白色储蓄罐不太一样。

尽管如此，未上漆的大理石、瓷器或其他材质的理念已深入人心，以至于即使我们现在知道古代雕像曾被彩绘，我们仍不为新古典主义雕像上色。

银行家们还资助需要资金完成作品的艺术家，包括波提切利和米开朗基罗。**城市政府本身也是文艺复兴的重要赞助者，**而个别领导人经常花费个人收入的6%, 用于艺术。

*为什么？很大程度上与如今富人资助艺术和建筑的原因相同——为了地位、认可*，甚至可能是对美的热爱。但此外，**#资助公共艺术、教堂等, 也有助于让这些家族的财富合法化。如果商人的财富被用于建造教堂，教会就很难谴责商人的财富；依赖这些财富的政府, 也无法谴责他们。#**我们在历史中反复看到这一点——*#财富支持机构(政治献金)，而机构反过来使财富合法化(权钱交易)。#*

无论如何，在这些艺术作品中，你可以看到文艺复兴的**矛盾之处**——异教元素与基督教相结合，这在基督教历史上屡见不鲜。*追逐利润的银行家, 资助教会，而教会由发过清贫誓言的牧师管理. 而其创立者, 在福音书中曾掀翻圣殿里放贷者的桌子。*

此外，在这些城邦中，接触更**人文主义的教育方式, 有助于推动经济增长，**并促进了许多至今仍具影响力的艺术和建筑的创作。

**许多城邦都参与了这场人文主义复兴，但毫无疑问，其中心是佛罗伦萨。**让我们进入“思想泡泡”环节。

当时的艺术家们在追随古代风格的同时，也将其推向新高度。
像桑德罗·波提切利, 和米开朗基罗这样的视觉艺术家，
关注人类的尊严和现实细节。 +
波提切利为佛罗伦萨市民绘制的肖像, 展现了人物的独特特征，
而他对宗教人物的描绘——例如，一个丰满的婴儿耶稣, 真实地伸手去抓母亲的衣服。
*波提切利为已故的但丁绘制的肖像, 同样展现了他瘦长尖挺的鼻子，
而非某种理想化、公式化的英雄形象。* +
米开朗基罗的《大卫》在试图模仿古代雕塑风格的同时，
也展现了真实的人类特征。
*在整个文艺复兴艺术领域，解剖学准确性蓬勃发展，*
这在米开朗基罗的雕塑中可见一斑，
也体现在佛罗伦萨同乡, 列奥纳多·达·芬奇的作品中——
顺便说一句，这两位艺术家都曾解剖过尸体，这是他们能够描绘人体的部分原因。

自然，作为人类（及人文主义）的背景，也在文艺复兴艺术中得到赞美，
如《维纳斯的诞生》所示。波提切利的这幅画, 聚焦于古典世界的神话女神，
但同时，她即将被乡村自然世界中的花朵所覆盖。

*简而言之，文艺复兴时期的艺术家们, 致力于将真实描绘的人体, 置于自然环境和城市背景中。*

感谢“思想泡泡”。*但在这种繁荣和文化复兴的表象下，佛罗伦萨的历史, 充满了接连不断的经济与自然冲击、阶级分化、企业竞争、党派斗争、与教会的冲突，尤其是政治危机。*

这些危机源于外部入侵的威胁，也源于内部的暴政和下层民众的不满。*#与威尼斯一样，佛罗伦萨以身为“共和国”而自豪，尽管它与"当代共和国"略有不同，且极其不稳定。#*

**比如，#这里没有真正的选举#；**相反，**佛罗伦萨行会成员的名字, 会从一个大皮袋中随机抽出，**如果你的名字被抽中，你就可以在执政团（Signoria）任职，管理城市。**如果你不想干，也没关系——新的执政团每两个月选举一次，这可能让人们觉得很多人都能参与公民生活，**但是：

- *要成为行会成员，你需要无债务、男性, 且人脉广泛*，
- 事实上，*抽签往往被操纵，富裕家庭往往能在"执政团"中获得席位。*
- 此外，**政变和反政变频繁发生，共和国常常不再“共和”，有时甚至变得完全像君主制。**这一切很像《权力的游戏》——*甚至可以说有点“马基雅维利主义”。*

**这并不奇怪——政治理论家尼科洛·马基雅维利, 确实生活在佛罗伦萨。**我们下周会进一步讨论他，但现在重要的是要知道，**他见证了——并经历了——许多动荡，**包括美第奇家族的兴衰起伏。

美第奇家族在佛罗伦萨权势极大，尽管与你可能读到的不同，他们并非文艺复兴时期唯一重要的家族。但他们确实通过银行业和投资, 积累了巨额财富，并且是艺术家的重要赞助者——事实上，米开朗基罗曾为他们的一座陵墓雕刻。

科西莫·美第奇和他的孙子洛伦佐, 在15世纪下半叶主导了佛罗伦萨，而家族的后续成员, 在接下来的几个世纪中, 通过担任教皇, 延续了家族的权力和赞助。

**马基雅维利认为，佛罗伦萨文艺复兴的黄金时代, 随着洛伦佐·德·美第奇于1492年的去世, 和“野蛮人”的入侵而终结。**当然，“野蛮人”在历史上大多意味着“非我们族类”——事实上，这个词本身源于一种感觉，即野蛮人的语言听起来像“巴巴巴巴巴”。无论如何，**这里的“野蛮人”指的是法国人，**所以我猜听起来像“Bar”（法语发音）。我高中法语学得不太好。

**#于是我们又回到了那个老问题：在文艺复兴时期，欧洲生活是否真的从所有方面的“宗教化”, 向关注人性和世俗发生了广泛转变？#**例如，米开朗基罗雕刻了《大卫》，但他也绘制了西斯廷教堂的穹顶画。

*#当你提出这些问题时，视角很重要——14世纪的佛罗伦萨（以及威尼斯、米兰等地）的商人和知识分子中, 确实发生了重要的新变化。但普通人，尤其是农民的生活，并未因这种"人文主义思想"而发生太大改变——至少在短期内如此。#*

但在其他方面，普通人也确实经历了“文艺复兴”——古代作家的作品被翻译成意大利语和法语，使那些不懂拉丁语的人, 也能阅读西塞罗等人的著作。但当然，大多数意大利农民仍目不识丁。

**历史学家也在争论, 女性是否经历了文艺复兴。**女性中有艺术赞助者：伊莎贝拉·德·埃斯特赞助音乐活动，她如此喜爱彼特拉克的诗歌，甚至为其谱曲。她还赞助画家，与列奥纳多·达·芬奇保持联系。

但伊莎贝拉·德·埃斯特, 和她同样有成就的妹妹贝亚特丽斯, 常被视为例外。**总体而言，**根据15世纪作家劳拉·切莱塔的说法，*男性低估了女性的智力价值。*

切莱塔刻意追随彼特拉克（正如彼特拉克追随西塞罗）的脚步，给一位厌恶女性的人写了一封著名的信，其中部分内容为：“我无法容忍你攻击我整个性别……我有正当理由要证明，女性凭借其天生的卓越——在每个时代通过知识展现的卓越——赢得了多么崇高的学识与美德的声誉……”

此外，*罗马法律思想的兴起, 意味着“家父长制”的兴起。即父亲是每个家庭的中心，也是权力的中心。*

*这一切都表明，#文艺复兴时期, 意大利城邦的知识和文化生活, 发生了极其重要的发展，这些发展(犹如工业革命一样)很快将传播到其他地区#。*

但我们必须转换视角——对美第奇家族而言，文艺复兴是真实存在的“时代”；对许多农民而言，它并非如此。我们如今铭记文艺复兴，部分原因是历史学家需要对历史进行分期以构建分析框架，部分原因是文艺复兴的许多思想塑造了我们的思维。

我认为值得记住的是，文艺复兴的思想至今仍在我们心中回响。例如，认为当前时代充满腐败与毁灭，我们必须回归某个逝去的伟大时代的纯粹。这种文艺复兴式的思维，确实与我们息息相关。感谢观看，下次见。

参考资料
Hunt, Lynn et al. 《西方的形成：人民与文化》，第6版。波士顿：贝德福德·圣马丁出版社，2019年。
Donald R. Kelley, 《文艺复兴人文主义》。波士顿：Twayne出版社，1991年。


'''

== pure

Hi, I'm John Green, and this is Crash Course European History. So, as you'll recall from our previous episode, a declining European population due to disease and war in the 14th century meant that labor had become much more valuable, which shifted long-held beliefs about how society should be organized.

Amid all this upheaval, and to some extent because of it, the Florentine author Francesco Petrarca, aka Petrarch, was unleashing his critique of 14th century life. "Living," he lamented, "I despise what melancholy fate has brought us wretches in these evil years." Oh, Petrarch, are you sure you weren't writing about now? It's almost like people always feel like they live in the worst possible time.

At any rate, not happy with the state of things in Europe, he turned to Plato, Cicero, and other ancient writers, whom he thought of as residents of the Old Age. In fact, Petrarch gave the era in which he lived its name -- calling them the "middle ages" just as his writing and research helped usher in a New Age that we now call the Renaissance.

[Intro]

According to Renaissance author Leonardo Bruni in the early fifteenth century, "Francesco Petrarch was the first with a talent sufficient to recognize and call back to light the ancient elegance of the lost and extinguished style." The Renaissance, meaning revival or renewal, harkened back to what was seen as the bright light of classical antiquity, which had then been obscured in the dark and ignorant Middle Ages.

But in some ways, the Middle Ages existed simultaneously with the Renaissance. Like, just as scholars were reviving translations of Plato and integrating knowledge from the Islamic world, the bubonic plague went on killing people; and in Petrarch's hometown, ordinary people like the Ciompi were vigorously protesting living conditions. Which brings us to an old question here at Crash Course: Was the Renaissance really a thing? Was it in fact just a continuation of the medieval world? Or was it the dramatic change that Renaissance thinkers believed it to be?

The writers and thinkers of the Renaissance scoured monasteries for ancient works, initially written or at least influenced by Roman writers. It was from this manuscript-hunting -- especially for works by Cicero, and Tacitus, and Quintilian -- that Renaissance scholars began to focus on so-called humanism. That is to say, they became more interested in worldly and human concerns.

And because the Renaissance really was a revival, this new thought was based on learning about old or ancient ways, especially in the study of the "humanities." The three liberal arts of grammar, rhetoric, and logic led to the so-called sciences of theology, philosophy, laws, and medicine.

The study of the humanities as developed by the ancients focused not on the heavens or saints but on human speech or rhetoric, human logic, and the correct use of language. And by language, of course, they mostly meant Latin -- being able to write in Latin and even perform Latin orations was seen as key to a fully educated life, as every high school Latin teacher will be happy to tell you.

Competence in these fields was seen as crucial to developing the self and a prerequisite for joining Florentine or Venetian elites. Like, Venetian youth Lauro Quirini, for example, studied the humanities at the University of Padua and then was sent to work in a Venetian enterprise on Crete, fully prepared for his new job as a commodities trader, although he also worked as a translator and a writer. You might say he was a real Renaissance Man. I'm sorry.

The Italian city-states were the heartland of the early Renaissance. In these prosperous cities, artists, composers, writers, and scholars thrived along with the commerce that paid for everything. Urban merchants and manufacturers built a brisk business that brought in products and ideas from around Afroeurasia. And some families achieved immense wealth, which allowed them to support the world of Renaissance thinkers and artists in a system called patronage.

I would like a phenomenally wealthy patron like Lorenzo Medici. If any of you are out there, I am available. And I would like all your ducats. You can visit patreon.com/crashcourse. But at any rate, banking institutions also sprang up, and bankers funded civic events and the construction of lavish cathedrals.

Bankers also backed or personally paid for the building of masterworks in the classical style -- that is, in the style of the restrained, stately design of the pre-Christian Roman Empire. Did the Globe open? Is there a neoclassical piggy bank in the center of the world? There is!

You know all those white statues of the Renaissance that take their whiteness from the white statues of the ancient Greeks and Romans? Yeah, they were not white! They were painted. Like, here are some of our best guesses of what actual classical statues looked like, and as you can see, not very much like neoclassical white piggy banks.

Nonetheless, the idea of unpainted marble, or porcelain, or whatever has proven so powerful that even though we now know that ancient statues were painted, we still don't paint our neoclassical ones.

Bankers also financed artists needing funds to complete their works, including Botticelli and Michelangelo. And city governments themselves were also important patrons of the Renaissance, while individual leaders often spent as much as six percent of their personal income on the arts.

Why? Well, largely for the same reason rich people fund art and buildings today -- for status, for recognition, and maybe even for the love of beauty. But also, funding public art and cathedrals and the like served to legitimize the wealth of these families. The Church could not very well condemn merchant wealth if it was used to build churches, nor could the governments that came to depend on it. We see this again and again throughout history -- wealth supports institutions that in turn legitimize that wealth.

Regardless, in these artworks, you can see the paradoxes of the Renaissance -- paganism is combined with Christianity, as it often had been throughout Christian history. Profit-oriented bankers financed the Church, which was run by priests who'd taken a vow of poverty, and founded by a figure who in the gospels overturns the tables of moneylenders in the temple.

Also, in these city-states, access to a more humanistic educational approach helped boost economic growth and fueled the creation of much art and architecture that is still really influential.

Now, many city-states participated in this humanist revival, but its headquarters was undoubtedly Florence. Let's go to the Thought Bubble.

Artists of the time were following ancient styles and taking them further.
Visual artists, like Sandro Botticelli and Michelangelo,
focused on human dignity and realistic details.
Botticelli's portraits of Florentine citizens display the distinct features of his subjects,
while his depictions of religious individuals show, for example, a plump infant Jesus realistically reaching for his mother's garments.
Botticelli's portrait of the long-dead Dante similarly displayed his long, thin, and pointed nose
rather than some idealized, formulaic hero.
And Michelangelo's "David" presents truly human characteristics
even as it sought to copy ancient sculptural styles.
Across the spectrum of Renaissance art, anatomical accuracy flourished,
which you can see in Michelangelo's sculptures
and also in the work of fellow Florentine Leonardo da Vinci --
both artists, incidentally, were able to render the human form in part because they both dissected cadavers.
And nature, as a setting for humans and thus humanism, was also glorified in Renaissance art,
as you can see in the Birth of Venus. Botticelli's painting focuses on the mythical goddess from the classical world
but at the same time she's about to be clothed in the flowers found in the natural world of the countryside.
In short, the artists of the Renaissance focused on situating a realistically depicted human body
in both its natural environment and its civic setting.
Thanks, Thought Bubble. But amid this prosperity and cultural revival, Florentine history was marked by a succession of economic and natural shocks, class divisions, corporate rivalries, party struggles, conflicts with the church, and especially political crises.

And those arose from threats of external invasion as well as internal tyranny and discontent among the lower classes. Like Venice, Florence took great pride in being a Republic, although it was a bit different from contemporary republics and exceedingly unstable.

Like, there weren't really elections; instead, names of members of Florence's guilds would basically be drawn out of a large leather bag, and if your name was drawn, you got to serve on the Signoria, which ran the city. And if you weren't psyched about the job, no worries -- new Signorias were chosen every two months, which might make it seem like lots of people were able to participate in civic life, but:

In order to be a member of a guild, you needed to be debt-free and male and well-connected,
and in truth the lotteries were often rigged, with wealthy families tending to win places on the Signoria.
Also, there were frequent coups and countercoups, and the Republic would often cease to be republican and at times become downright monarchical. It was all quite Games of Thronesy -- one might even say that it was a bit Machiavellian.

And no wonder -- the political theorist Niccolo Machiavelli did live in Florence. We'll discuss him more next week, but for now, it's important to know that he saw -- and suffered through -- much of this turmoil, including the rise and fall and rise again of the Medici family.

The Medicis were tremendously powerful in Florence, although contrary to what you might read they weren't the only important family in the Renaissance. But they did make huge sums in banking and investing, and were important patrons to artists -- in fact Michelangelo carved one of their tombs.

Cosimo Medici and his grandson Lorenzo dominated the second half of the fifteenth century in Florence, while successive members of the family perpetuated its power and patronage by serving as popes in the next centuries.

Machiavelli argued that the Florentine Renaissance's Golden Age ended with the death of Lorenzo de Medici in 1492 and the invasion of the "barbarians." Of course, "Barbarians" mostly means "Not Us" throughout history -- in fact the word itself comes from a feeling that the language of Barbarians sounded like bar bar bar bar bar. Anyway, these particular Barbarians were French, so I guess it sounded like Bar. I wasn't very good at High School French.

And so we return at last to the old question: Were there really broad shifts away from the religiofication of all aspects of European life toward the human and the secular in the Renaissance? Like, Michelangelo sculpted David, but he also painted the ceiling of the Sistine Chapel.

Perspective matters when you ask these questions -- something important and new was happening in 14th century Florence (and Venice and Milan and so on) among merchants and intellectuals. But the lives of average people, especially peasants, were not much transformed by this humanist thinking -- at least not in the short run.

But in other ways, ordinary people did also have a Renaissance -- ancient authors were translated into Italian and French, which allowed those without access to Latin to read Cicero and the like. But of course most Italian peasants couldn't read anything.

Historians also debate whether women experienced a Renaissance. Women were among the patrons of the arts: Isabella d'Este sponsored musical events and loved Petrarch's poems so much that she had music composed for them. She also sponsored painters, maintaining contacts with Leonardo da Vinci.

But, Isabella d'Este and her similarly accomplished sister Beatrice are often seen as the exception. In general men, according to fifteenth century writer Laura Cereta, discounted women's intellectual worth.

Deliberately following Petrarch's path as he had followed Cicero's, Cereta wrote a famous letter to one misogynist that read in part: "I cannot tolerate your having attacked my entire sex... With just cause I am moved to demonstrate how great a reputation for learning and virtue women have won by their inborn excellence, manifested in every age as knowledge..."

Also, the rise of Roman legal thinking meant the rise of the Pater Familias. The idea that the father is the center of every family, and also the center of power.

All of which is to say that the Renaissance saw tremendously important developments in the intellectual and cultural life of Italian city-states, developments that would soon be exported to other communities.

But we have to be able to shift perspectives -- to the Medicis, the Renaissance was a thing. To many peasants, it was not. We remember the Renaissance today partly because it's helpful for historians to periodize history to frame their analyses, and partly because so much Renaissance thinking shapes our thinking.

And I think it's worth remembering how the ideas of the Renaissance continue to resonate for us today. Consider, for example, the feeling that the current age is so full of corruption and destruction that we must return to the purity of some bygone era of greatness. That Renaissance thinking seems very relevant, indeed. Thanks for watching. I'll see you next time.

Sources
Hunt, Lynn et al. The Making of the West: Peoples and Cultures, 6th ed. Boston: Bedford St. Martins, 2019.
Donald R. Kelley, Renaissance Humanism. Boston: Twayne, 1991.

'''