
= 004 - The Northern Renaissance
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义


Hi, I'm John Green, and this is Crash Course European History. So when we left off last time, the Renaissance 文艺复兴 was a very big deal — provided you were a member of the elite 精英 in approximately this part of the world. Today, we're gonna follow the spread of the Renaissance to France, England, Spain, the Low Countries, and the 72 bajillion mini-states of Central Europe. Also, suddenly there are a lot more books to read.

The Renaissance was shaped and promoted by the discovery in the mid-15th century of movable-type 活字的 printing. The credit 功劳 mostly goes to the German goldsmith 金匠 and tinkerer  tinkerer n.  tinkerer n. 爱 tinkerer n. 爱鼓捣的人 Johannes Gutenberg, whose printing press 印刷机 from the 1440s produced the famous Gutenberg Bible and fuelled 推动 the spread of printed books. Now, printing techniques, including movable type, had been used in China for many centuries, but printing could be quicker in Europe because the Latin alphabet 字母表 only contained 26 characters. Also, innovations 创新 made the letters easier to eject  eject v.  eject v. 弹出 and reset 重置 to form new words that eventually became pamphlets 小册子 and newsletters 时事通讯 and then entire books.

In fact, there are books in the center of the world today. It's my favorite center of the world yet. I love books. It's really hard to exaggerate 夸大 just how big a deal printing was. Like, before our friend Gutenberg, most books in Europe were copied from other books by hand. This was time-consuming 耗时的 and expensive, and it introduced errors 错误. And it also meant that books were not part of most people's lives. Like, if you were among the around 80% of people in England and France who worked in agriculture 农业 at the time, it's not just that you didn't need to learn to read to do your job — there was generally nothing you could read.

But printing changed all of that incredibly quickly. The first printing press arrived in Venice in 1469. By 1500, there were 417 printing presses in the city. In the first 50 years after printing came to Europe, over 20 million volumes 册 of books were printed. This included the great works from the classical 古典的 world that the Renaissance was rediscovering, but also many legal works. And as jurists 法学家 worked to decipher 破译 the meaning of every Latin word of the corpus 文集 of Roman law, the Western legal tradition 传统 was born. More copies of the Bible were available to read and argue about, and new stories and poems could be shared more widely.

Think of it this way: Whether you were interested in science or literature 文学 or law or mathematics, printing meant that more people had the opportunity to encounter 接触 far more voices across time and space. And as Renaissance ideas spread north — in part by printing — it followed that writers and scholars would see the ideas of humanism 人文主义 through the lens 视角 of local concerns. Also, of course, northern European thinkers downplayed 淡化 the movement's Italian origins.

One of the great rules of history is that whenever Italy has an idea, northern Europe will be like, "Yeah, no, we totally already had that idea like eight times. Our version is so much different and better. Wait till you see how we do the Black Death / ballet / fascism / automatic weapons / pizza / defensive-minded football."

Anyway, Pieter Bruegel's *Dutch Proverbs* is one example of how different Northern Renaissance art was from its Italian counterparts 对应物. Bruegel is still interested in the ideas of humanism — in this painting, it's secular 世俗的, focused on people, set in the natural world. But you can see that Bruegel's painting of scruffy 邋遢的 rural 乡村的 villagers 村民 acting out ridiculous 荒谬的 common wisdom has none of the lyricism 抒情性 or elegance 优雅 of, say, Botticelli's *Birth of Venus*.

Then again, in many respects 方面, the Northern Renaissance wasn't so unique. The touchstone 试金石 was still the classical world and its art and writing. Florentines had made much of the Roman legal tradition that empowered 授权 the *paterfamilias* 家父, or male head of the family, and this was very much embraced 接受 in the north as well. The idea was that all social and political order stemmed from 源于 the exercise 行使 of the father's authority 权威 over the family unit. From the father's secure position, the well-being 福祉 of the family flowed, and more than that, the well-being of the larger state depended on the good order of all the families it encompassed 包含 — just as the successes of Rome had rested on familial 家庭的 underpinnings 基础.

And if humanism was going to open the door to rethinking current values, some sort of anchor 锚 was needed to prevent chaos 混乱. And people to the north and south agreed that this security was gonna rest in the classical tradition of the father's legal dominance 主导.

In both north and south, humanism also went radical 激进的. Some humanists began regularly teaching — not just discussing — its principles 原则 and its main subject matter, rhetoric 修辞, which may not seem like a big deal to you, but it meant that, at least in parts of the radical fringe 边缘 of the Renaissance world, ancient Latin and Greek were being taught — not just the medieval 中世纪的 versions of those languages, which would eventually contribute to a rethinking of what certain texts actually said, perhaps most notably the Bible.

Also, girls sometimes joined their brothers in being tutored 辅导 — a radical idea indeed, although one that could also trace itself back to the old light. In justifying 证明合理 the education of girls, scholars cited 引用 ancient women who'd received tutoring, including Sappho, Aphasia, and Cornelia, the daughter of the Roman general Scipio.

And as humanism grew, so did the number of universities. European universities had long taught a system of theology 神学 and philosophy 哲学 known as scholasticism 经院哲学 that focused on early church teaching and Aristotelian 亚里士多德的 logic 逻辑. But now they began to embrace humanism, spending less time studying religious texts and more time investigating 研究 the human condition and thinking about how to organize human societies, including how to establish 建立 and enforce 执行 laws.

And amid these developments, Desiderius Erasmus of Rotterdam — also known as the Prince of the Humanists — became the commanding 权威性的 figure in the Northern Renaissance. Let's go to the Thought Bubble.

Erasmus contributed to taking humanism along its twisted path from ideas of the study of humans and the act of life into politics. He went to study at the University of Paris and began publishing his opinions on public affairs, including the responsibilities 责任 of a ruler. A prince, he declared in *The Education of a Christian Prince*, needed to study the classics and the deeds 事迹 of worthy 值得尊敬的 ancient leaders. And in these examples, he would discover the means 方法 by which great leaders achieved the public good and kept the peace even in troubled times.

He also emphasized 强调 the importance of reading the Bible and the leading Christian authors. It was for this that he came to be known as advocating for 倡导 a middle road between the pagan 异教的 ancients and the more recent Christian thinkers. But he was at times also very critical of the Catholic Church.

Erasmus was also a central figure in the rising Republic of Letters — a growing international community 社区 of humanists in Europe. In his lifetime, he corresponded with 与…通信 some 500 people around Europe, including everyone from Sir Thomas More to Martin Luther to Pope Leo X. Aside from his work on biblical 圣经的 translations, he also edited, translated, and published ancient pagan texts like Cicero's and the works of many pivotal 关键的 religious authors, especially St. Jerome.

He was astonishingly 惊人地 prolific 多产的, hiring editors, proofreaders 校对员, and even ghostwriters 代笔人 to help him produce mountains of humanistic texts. And he fashioned himself as the quintessential 典型的 figure of the Northern Renaissance before dying suddenly of dysentery 痢疾 at the age of 69 — because, you know, it was the 16th century.

Thanks, Thought Bubble.

So before he died, Erasmus saw the rise of the Protestant Reformation 新教改革, and he disagreed with much of Martin Luther's teachings and remained loyal to 忠于 the Catholic Church. But Erasmus's emphasis on inner spirituality 精神性 over ritual 仪式 did, in some ways, presage 预示 Protestantism. Some felt that Erasmus had laid the egg and Luther had hatched it, but Erasmus dismissed 否认 that, saying Luther hatched a different bird entirely. Also, for the record, neither Erasmus nor Martin Luther could lay eggs because they were mammals 哺乳动物.

But now we're venturing into 涉足 biology 生物学 and getting a bit ahead of ourselves with the Reformation. Before we started debating how many angels can fit on the head of a pin, we should acknowledge the other great Renaissance thinker who shaped what we now call political science: Niccolò Machiavelli, who was like the Erasmus living in the Upside Down.

Machiavelli had been a faithful 忠实的 supporter of Florence's republican 共和的 traditions. After the death of Lorenzo de' Medici in 1492, Machiavelli served the Republic in several positions. But after Spanish, papal 教皇的, and other forces defeated the Republic in 1512, Machiavelli was imprisoned 监禁 and tortured 折磨. He was hung by his wrists until his shoulders were dislocated 脱臼. He was eventually released after three weeks in prison and then set out to write his masterwork 杰作, *The Prince*, which was only published in 1532, five years after his death.

*The Prince* was very different from the work of other humanists, especially from the political ideas of Christian humanism found in Erasmus's essays and letters. Machiavelli imagined a grounding 基础 in the classics for an aspiring 有抱负的 leader of his day, but he believed the attitudes necessary for leaders were vastly 极大地 different from what the ancients had counseled 建议.

His most quoted advice focused on whether a ruler should aim to be loved or feared: "One should wish to be both, but because it is difficult to unite them in one person, it is much safer to be feared than loved." Machiavelli took a so-called realist 现实主义的 view of politics. He focused on how a prince could retain 维持 power and maintain order, and he was much more interested in what was effective 有效的 than what was, like, noble 高尚的.

And unlike many humanists' focus on maintaining peace, Machiavelli believed that war was necessary. In fact, he wrote a book about it called *The Art of War*. He argued that rulers needed to prepare for war by studying great military leaders of the past, and he believed that effective military leadership was vital 至关重要的 to effective political leadership because those who win wars get to gain peace on their terms.

But there were also idealists 理想主义者 among Renaissance humanists, like the Englishman Thomas More, who was one of Erasmus's 5-billion friends — and a close one, in fact. More wrote the classic book *Utopia* 乌托邦, which imagines a society without private property, where reason 理性 and cooperation 合作 have replaced struggles for glory 荣耀 and power.

It's an odd book. More was a devout 虔诚的 Catholic, and in fact would eventually be executed 处决 for opposing King Henry VIII's turn toward Protestantism. And yet, this seemingly enlightened 开明的 utopia is very much not Catholic. Like, the Utopians have married priests, for instance, and also they can get divorced 离婚. But regardless, More believed that humanistic analysis 分析 could lead to widespread peace and prosperity 繁荣 — which, by the way, I would argue, turned out to be sort of correct, even though (a) it would take a while for humanism's benefits to be felt, and (b) More did not really get to enjoy them on account of 由于 being separated from his head in 1535.

A century before More's *Utopia*, another book that imagined an ideal city-state, *The Book of the City of Ladies*, was written by Christine de Pizan. De Pizan was born in Venice but moved to France as a kid when her dad got a job as the French king's astrologer 占星家 — as you do. She married and had three kids, but then her husband died of the plague, and thereafter 此后 she earned her living writing.

In *The Book of the City of Ladies*, de Pizan gathered up all the great and good women of history and placed them in a city where the Virgin Mary is queen. The book argues that women can be virtuous 品德高尚的 leaders and rational 理性的 beings and that leadership by virtuous women could beget 产生 virtuous communities — a stark 明显的 contrast 对比 to Machiavelli's worldview.

So at this point, it's common to ask students to think about the relative merits 优点 of idealism and realism. Is a prince or princess — or, for that matter, a student at a high school — better off being loved or feared? Is it more important for a community to be fair or stable 稳定的? Should leaders prioritize 优先考虑 virtue 美德 or effectiveness? These are big, interesting questions, and I think they're worth considering.

But I would also ask you to look at the lens through which you're approaching those questions. Machiavelli's life was marked by 以…为特征 endless wars and shifting alliances 联盟. He saw many short-lived governments fail to achieve stability. Christine de Pizan saw the intense 强烈的 oppression 压迫 of women and the dismissal 轻视 of their talents and intellect 智力. Erasmus didn't exactly have an easy life — he was born out of wedlock 非婚生的, and both his parents died of plague when he was a teenager — but he saw a very different world in northern Europe than Machiavelli saw in Italy or than Christine de Pizan saw.

Where do you sit in the world, and how might that shape what kind of community you wish to see?

Thanks for watching. I'll see you next week.

Thanks so much for watching Crash Course European History, which is filmed here in Indianapolis and produced with the help of all of these nice people. Our animation team is Thought Cafe, and Crash Course would not exist without the generous support of our patrons on Patreon.

Patreon is a voluntary 自愿的 subscription 订阅 service where you can support the content you love through a monthly donation 捐赠 and help keep Crash Course free for everyone forever. Thanks again for watching, and as they say in my hometown, don't forget to be awesome.

You.


'''

== 中文释义



大家好，我是约翰·格林，这里是《速成欧洲史》。我们上次讲到，文艺复兴是件大事——前提是你属于欧洲这片区域的精英阶层。今天，我们将跟随文艺复兴的传播足迹，看看它如何影响法国、英国、西班牙、低地国家，以及中欧不计其数的迷你城邦。此外，突然之间，可供阅读的书籍变得多了起来。

**文艺复兴的形成与推动, 得益于15世纪中叶活字印刷术的发明。这一成就主要归功于德国金匠兼发明家约翰内斯·古腾堡。**他在15世纪40年代发明的印刷机, 印制了著名的《古腾堡圣经》，并推动了印刷书籍的传播。**诚然，包括活字印刷在内的印刷技术在中国已使用多个世纪，但在欧洲，印刷效率更高，因为拉丁字母只有26个字符。**此外，一系列创新让字母更易于拆卸和重新排列以组成新词，这些技术最终催生了小册子、时事通讯，乃至完整的书籍。

事实上，如今世界的中心就有书籍。这是我至今最爱的“世界中心”。我热爱书籍。印刷术的重要性怎么强调都不为过。*##在##我们的朋友##古腾堡出现之前，##欧洲的大多数书籍都是手工抄写的。这一过程既耗时又昂贵，还容易出错。这也意味着##书籍并非大多数人生活的一部分。##例如，#当时英法约80%的人口从事农业，他们不仅工作中无需学习阅读——通常也无任何可读之物。#*

**但印刷术以惊人的速度改变了这一切。**1469年，第一台印刷机抵达威尼斯。到1500年，这座城市已有417台印刷机。**印刷术传入欧洲的头50年里，超过2000万册书籍被印刷出来。其中既包括文艺复兴时期重新发掘的古典著作，也有许多法律文献。当法学家们致力于解读罗马法全书中每个拉丁语词汇的含义时，西方法律传统应运而生。更多人得以阅读《圣经》并展开讨论，**新的故事和诗歌也得以更广泛地传播。

这样想吧：无论你对科学、文学、法律还是数学感兴趣，印刷术都意味着更多人有机会跨越时空, 接触到更多不同的思想。随着文艺复兴思想向北传播——部分借助印刷术的力量——作家和学者开始从本土视角, 审视人文主义思想。当然，北欧思想家也有意淡化这一运动的意大利起源。

**历史的一大规律是：每当意大利出现一种思想，北欧总会如此回应：“呵，不，这想法我们早八百年就有了。我们的版本更独特、更优越。**等着瞧我们如何演绎黑死病/芭蕾/法西斯主义/自动武器/披萨/防守型足球吧。”

无论如何，彼得·勃鲁盖尔的《荷兰谚语》便是北欧文艺复兴艺术, 与意大利同行截然不同的例证之一。勃鲁盖尔仍关注人文主义理念——在这幅画中，画面是世俗的，聚焦于人物，以自然世界为背景。但你会发现，勃鲁盖尔描绘的邋遢乡村村民演绎荒谬俗语的画面，完全没有波提切利《维纳斯的诞生》的抒情性或典雅感。

不过，在许多方面，北欧文艺复兴也并非完全独树一帜。其核心依旧是古典世界及其艺术与文学。**佛罗伦萨人极为推崇赋予“家父”（家庭男性户主）权力的罗马法律传统，这一传统在北欧也备受推崇。其核心理念是：所有社会和政治秩序, 均源于父亲对家庭单位的权威。**从父亲的稳固地位中，家庭得以繁荣，而更广泛的国家的福祉, 则依赖于其包含的所有家庭的良好秩序——*正如罗马的成功建立在家庭根基之上。*

如果人文主义旨在为"重新思考当下价值观"打开大门，就需要某种“锚点”来防止混乱。南北欧的人们一致认为，这种稳定性, 将基于父亲法律主导地位的古典传统。

在南北欧，人文主义还走向了“激进”。一些人文主义者开始系统教授——而不仅是讨论——其核心原则和主要研究对象“修辞学”。这对你来说可能不算什么，但这意味着，*至少在文艺复兴世界的某些激进边缘地区，人们开始教授古代拉丁语和希腊语——而非中世纪版本的这些语言，这最终将促使人们重新审视某些文本的真实含义(相当于去中介了. 相当于唐僧取景, 直接去源头翻译. 又比如, 翻译的德国书, 是从德语到英语到汉语. 我们就直接去看德语.)，其中最显著的或许是《圣经》。*

此外，女孩有时会和兄弟一起接受家庭教师的教导——这确实是个激进的想法，尽管其根源也可追溯至古代。在为女孩教育辩护时，学者们援引了曾接受过教导的古代女性，包括萨福、阿菲西亚，以及罗马将军"西庇阿"之女"科妮莉亚"。

*随着人文主义的发展，大学数量也随之增加。#欧洲的大学长期教授一种名为“经院哲学”的神学和哲学体系，其核心是早期教会教义和亚里士多德逻辑。但如今，它们开始拥抱人文主义，减少对宗教文本的研究，更多关注人类处境，思考如何组织人类社会，包括如何制定和执行法律。#*

在这些发展中，鹿特丹的"德西德里乌斯·伊拉斯谟"——又称“人文主义王子”——成为北欧文艺复兴的领军人物。让我们进入“思想泡泡”环节。

**#伊拉斯谟推动人文主义, 从“研究人类与生命”的理念, 向政治领域延伸。#**他曾在巴黎大学学习，并开始发表对公共事务的见解，包括对统治者职责的看法。他在《基督教王子的教育》中宣称，君主需要研究古典著作, 和古代杰出领袖的事迹。从这些范例中，君主将发现伟大领袖实现公共福祉、甚至在动荡时期维持和平的方法。

他还强调阅读《圣经》和主流基督教作家作品的重要性。正因如此，他被誉为在异教古代与近代基督教思想家之间倡导“中间道路”。但他有时也对天主教会提出尖锐批评。

伊拉斯谟也是新兴“文字共和国”（欧洲日益壮大的国际人文主义者社群）的核心人物。在他的一生中，曾与欧洲各地约500人通信，包括托马斯·莫尔爵士、马丁·路德、教皇利奥十世等各界人士。除了致力于《圣经》翻译，他还编辑、翻译并出版了西塞罗等古代异教文本，以及许多关键宗教作家的作品，尤其是圣杰罗姆的著作。

他的创作量惊人，曾雇佣编辑、校对员, 甚至代笔作家, 来协助自己产出大量人文主义文本。在69岁突然死于痢疾之前，他一直将自己塑造为北欧文艺复兴的典型代表——要知道，那可是16世纪。

感谢“思想泡泡”。

在去世前，伊拉斯谟目睹了"新教改革"的兴起。他不同意马丁·路德的许多教义，始终忠于天主教会。但**伊拉斯谟强调内"在精神性高于宗教仪式"的理念，在某种程度上, 确实为"新教改革"埋下了伏笔。**有人认为“伊拉斯谟下了蛋，路德孵出了小鸡”，但伊拉斯谟对此不以为然，称路德孵出的完全是另一种“鸟”。此外，郑重声明：伊拉斯谟和马丁·路德都不能下蛋，因为他们是哺乳动物。

但我们现在涉足生物学领域，且对宗教改革的讨论有点超前了。在开始争论“多少天使能站在针尖上”之前，我们应该认识另一位塑造了我们如今所称“政治学”的文艺复兴思想家：尼科洛·马基雅维利，他就像生活在“颠倒世界”的伊拉斯谟。

马基雅维利曾是佛罗伦萨"共和传统"的忠实支持者。1492年洛伦佐·德·美第奇去世后，马基雅维利在共和国担任过多个职位。但1512年，在西班牙、教皇及其他势力击败共和国后，**马基雅维利**遭到监禁和酷刑。他被吊起来，手腕被拉至脱臼。入狱三周后，他最终获释，随后开始撰写代表作《君主论》，该书直到他去世五年后的1532年才出版。

《君主论》与其他人文主义者的作品大相径庭，尤其不同于伊拉斯谟散文和书信中, 体现的基督教人文主义政治理念。马基雅维利设想，当代有抱负的领导者应具备古典文化根基，但他认为，领导者所需的态度, 与古人的教导截然不同。

*他最常被引用的建议, #围绕“统治者应被爱戴, 还是被畏惧”展开：#“人皆希望两者兼得，但因二者难以兼具，故##'被畏惧'比'被爱戴'更安全。##”马基雅维利采取了所谓的“现实政治”视角。#他关注君主如何维系权力、维持秩序，更在意“有效”而非“高尚”。#*

与许多人文主义者关注维持和平不同，**#马基雅维利认为战争是必要的。#**事实上，他曾写过一本关于战争的书，名为《战争的艺术》。他主张，统治者需通过研究历史上伟大的军事领袖, 来为战争做准备，且**认为有效的军事领导力, 对有效的政治领导力至关重要，#因为赢得战争的人, 才能按自己的条件缔造和平。#**

但文艺复兴时期的人文主义者中, 也有理想主义者，如英国人托马斯·莫尔，他是伊拉斯谟众多密友之一。莫尔写下经典著作《乌托邦》，书中设想了一个没有私有财产的社会，理性与合作, 取代了对荣耀和权力的争夺。

这是一本奇特的书。莫尔是虔诚的天主教徒，最终因反对亨利八世转向"新教"而被处决。然而，这个看似开明的乌托邦, 却绝非天主教式的。例如，乌托邦人允许牧师结婚，也允许离婚。但无论如何，莫尔相信, 人文主义分析, 能带来普遍的和平与繁荣——我认为，这一观点某种程度上是正确的，尽管（一）人文主义的益处, 需假以时日才能显现，（二）莫尔因1535年身首异处, 而未能真正享受这些益处。

在莫尔的《乌托邦》问世前一个世纪，另一部设想理想城邦的著作《城市淑女》, 由"克里斯蒂娜·德·皮桑"撰写。皮桑生于威尼斯，幼时随担任法国国王占星师的父亲, 移居法国——是的，**占星师是当时的一种职业。**她成婚后育有三个孩子，但丈夫死于瘟疫，此后她以写作谋生。

在《城市淑女》中，皮桑汇集历史上所有杰出女性，将她们置于以圣母玛利亚为女王的城市中。该书主张，女性可以成为有德行的领导者, 和理性的存在，由有德女性领导的社群, 将孕育有德的社会——这与马基雅维利的世界观形成鲜明对比。

至此，*我们常让学生思考"理想主义"与"现实主义"的相对价值。对君主（或高中生）而言，"被爱戴"还是"被畏惧"更好？对社群而言，"公平(民主)"还是"稳定(专制独裁)"更重要？领导者应优先考虑"美德(名声,面子)"还是"效率(现实,里子)"？这些都是重大而有趣的问题，值得我们思考。*

但我也想请你审视自己思考这些问题的“视角”。马基雅维利的一生充满无尽的战争和动荡的联盟，他目睹许多短命政府未能实现稳定。克里斯蒂娜·德·皮桑则见证了女性遭受的深重压迫，以及她们的才华和智慧被忽视。伊拉斯谟的人生也并非一帆风顺——他是非婚生子，十几岁时父母均死于瘟疫——但他在北欧所见的世界，与马基雅维利在意大利、皮桑在法国所见的截然不同。

*你身处怎样的世界，又会如何塑造你期望看到的社会？*

感谢观看，下周见。

感谢观看《速成欧洲史》，本节目在印第安纳波利斯拍摄，并在以上所有善良人士的帮助下制作完成。我们的动画团队是Thought Cafe。没有Patreon上赞助者的慷慨支持，就没有《速成课程》。

Patreon是一项自愿订阅服务，您可以通过每月捐款支持自己喜爱的内容，并帮助《速成课程》永远免费面向所有人。再次感谢观看，正如我家乡的人们所说：“别忘了做个出色的人。”

说的就是你。


'''

== pure



Hi, I'm John Green, and this is Crash Course European History. So when we left off last time, the Renaissance was a very big deal -- provided you were a member of the elite in approximately this part of the world. Today, we're gonna follow the spread of the Renaissance to France, England, Spain, the Low Countries, and the 72 bajillion mini-states of Central Europe. Also, suddenly there are a lot more books to read.

The Renaissance was shaped and promoted by the discovery in the mid-15th century of movable-type printing. The credit mostly goes to the German goldsmith and tinkerer Johannes Gutenberg, whose printing press from the 1440s produced the famous Gutenberg Bible and fuelled the spread of printed books. Now, printing techniques, including movable type, had been used in China for many centuries, but printing could be quicker in Europe because the Latin alphabet only contained 26 characters. Also, innovations made the letters easier to eject and reset to form new words that eventually became pamphlets and newsletters and then entire books.

In fact, there are books in the center of the world today. It's my favorite center of the world yet. I love books. It's really hard to exaggerate just how big a deal printing was. Like, before our friend Gutenberg, most books in Europe were copied from other books by hand. This was time-consuming and expensive, and it introduced errors. And it also meant that books were not part of most people's lives. Like, if you were among the around 80% of people in England and France who worked in agriculture at the time, it's not just that you didn't need to learn to read to do your job -- there was generally nothing you could read.

But printing changed all of that incredibly quickly. The first printing press arrived in Venice in 1469. By 1500, there were 417 printing presses in the city. In the first 50 years after printing came to Europe, over 20 million volumes of books were printed. This included the great works from the classical world that the Renaissance was rediscovering, but also many legal works. And as jurists worked to decipher the meaning of every Latin word of the corpus of Roman law, the Western legal tradition was born. More copies of the Bible were available to read and argue about, and new stories and poems could be shared more widely.

Think of it this way: Whether you were interested in science or literature or law or mathematics, printing meant that more people had the opportunity to encounter far more voices across time and space. And as Renaissance ideas spread north -- in part by printing -- it followed that writers and scholars would see the ideas of humanism through the lens of local concerns. Also, of course, northern European thinkers downplayed the movement's Italian origins.

One of the great rules of history is that whenever Italy has an idea, northern Europe will be like, "Yeah, no, we totally already had that idea like eight times. Our version is so much different and better. Wait till you see how we do the Black Death / ballet / fascism / automatic weapons / pizza / defensive-minded football."

Anyway, Pieter Bruegel's *Dutch Proverbs* is one example of how different Northern Renaissance art was from its Italian counterparts. Bruegel is still interested in the ideas of humanism -- in this painting, it's secular, focused on people, set in the natural world. But you can see that Bruegel's painting of scruffy rural villagers acting out ridiculous common wisdom has none of the lyricism or elegance of, say, Botticelli's *Birth of Venus*.

Then again, in many respects, the Northern Renaissance wasn't so unique. The touchstone was still the classical world and its art and writing. Florentines had made much of the Roman legal tradition that empowered the *paterfamilias*, or male head of the family, and this was very much embraced in the north as well. The idea was that all social and political order stemmed from the exercise of the father's authority over the family unit. From the father's secure position, the well-being of the family flowed, and more than that, the well-being of the larger state depended on the good order of all the families it encompassed -- just as the successes of Rome had rested on familial underpinnings.

And if humanism was going to open the door to rethinking current values, some sort of anchor was needed to prevent chaos. And people to the north and south agreed that this security was gonna rest in the classical tradition of the father's legal dominance.

In both north and south, humanism also went radical. Some humanists began regularly teaching -- not just discussing -- its principles and its main subject matter, rhetoric, which may not seem like a big deal to you, but it meant that, at least in parts of the radical fringe of the Renaissance world, ancient Latin and Greek were being taught -- not just the medieval versions of those languages, which would eventually contribute to a rethinking of what certain texts actually said, perhaps most notably the Bible.

Also, girls sometimes joined their brothers in being tutored -- a radical idea indeed, although one that could also trace itself back to the old light. In justifying the education of girls, scholars cited ancient women who'd received tutoring, including Sappho, Aphasia, and Cornelia, the daughter of the Roman general Scipio.

And as humanism grew, so did the number of universities. European universities had long taught a system of theology and philosophy known as scholasticism that focused on early church teaching and Aristotelian logic. But now they began to embrace humanism, spending less time studying religious texts and more time investigating the human condition and thinking about how to organize human societies, including how to establish and enforce laws.

And amid these developments, Desiderius Erasmus of Rotterdam -- also known as the Prince of the Humanists -- became the commanding figure in the Northern Renaissance. Let's go to the Thought Bubble.

Erasmus contributed to taking humanism along its twisted path from ideas of the study of humans and the act of life into politics. He went to study at the University of Paris and began publishing his opinions on public affairs, including the responsibilities of a ruler. A prince, he declared in *The Education of a Christian Prince*, needed to study the classics and the deeds of worthy ancient leaders. And in these examples, he would discover the means by which great leaders achieved the public good and kept the peace even in troubled times.

He also emphasized the importance of reading the Bible and the leading Christian authors. It was for this that he came to be known as advocating for a middle road between the pagan ancients and the more recent Christian thinkers. But he was at times also very critical of the Catholic Church.

Erasmus was also a central figure in the rising Republic of Letters -- a growing international community of humanists in Europe. In his lifetime, he corresponded with some 500 people around Europe, including everyone from Sir Thomas More to Martin Luther to Pope Leo X. Aside from his work on biblical translations, he also edited, translated, and published ancient pagan texts like Cicero's and the works of many pivotal religious authors, especially St. Jerome.

He was astonishingly prolific, hiring editors, proofreaders, and even ghostwriters to help him produce mountains of humanistic texts. And he fashioned himself as the quintessential figure of the Northern Renaissance before dying suddenly of dysentery at the age of 69 -- because, you know, it was the 16th century.

Thanks, Thought Bubble.

So before he died, Erasmus saw the rise of the Protestant Reformation, and he disagreed with much of Martin Luther's teachings and remained loyal to the Catholic Church. But Erasmus's emphasis on inner spirituality over ritual did, in some ways, presage Protestantism. Some felt that Erasmus had laid the egg and Luther had hatched it, but Erasmus dismissed that, saying Luther hatched a different bird entirely. Also, for the record, neither Erasmus nor Martin Luther could lay eggs because they were mammals.

But now we're venturing into biology and getting a bit ahead of ourselves with the Reformation. Before we started debating how many angels can fit on the head of a pin, we should acknowledge the other great Renaissance thinker who shaped what we now call political science: Niccolò Machiavelli, who was like the Erasmus living in the Upside Down.

Machiavelli had been a faithful supporter of Florence's republican traditions. After the death of Lorenzo de' Medici in 1492, Machiavelli served the Republic in several positions. But after Spanish, papal, and other forces defeated the Republic in 1512, Machiavelli was imprisoned and tortured. He was hung by his wrists until his shoulders were dislocated. He was eventually released after three weeks in prison and then set out to write his masterwork, *The Prince*, which was only published in 1532, five years after his death.

*The Prince* was very different from the work of other humanists, especially from the political ideas of Christian humanism found in Erasmus's essays and letters. Machiavelli imagined a grounding in the classics for an aspiring leader of his day, but he believed the attitudes necessary for leaders were vastly different from what the ancients had counseled.

His most quoted advice focused on whether a ruler should aim to be loved or feared: "One should wish to be both, but because it is difficult to unite them in one person, it is much safer to be feared than loved." Machiavelli took a so-called realist view of politics. He focused on how a prince could retain power and maintain order, and he was much more interested in what was effective than what was, like, noble.

And unlike many humanists' focus on maintaining peace, Machiavelli believed that war was necessary. In fact, he wrote a book about it called *The Art of War*. He argued that rulers needed to prepare for war by studying great military leaders of the past, and he believed that effective military leadership was vital to effective political leadership because those who win wars get to gain peace on their terms.

But there were also idealists among Renaissance humanists, like the Englishman Thomas More, who was one of Erasmus's 5-billion friends -- and a close one, in fact. More wrote the classic book *Utopia*, which imagines a society without private property, where reason and cooperation have replaced struggles for glory and power.

It's an odd book. More was a devout Catholic, and in fact would eventually be executed for opposing King Henry VIII's turn toward Protestantism. And yet, this seemingly enlightened utopia is very much not Catholic. Like, the Utopians have married priests, for instance, and also they can get divorced. But regardless, More believed that humanistic analysis could lead to widespread peace and prosperity -- which, by the way, I would argue, turned out to be sort of correct, even though (a) it would take a while for humanism's benefits to be felt, and (b) More did not really get to enjoy them on account of being separated from his head in 1535.

A century before More's *Utopia*, another book that imagined an ideal city-state, *The Book of the City of Ladies*, was written by Christine de Pizan. De Pizan was born in Venice but moved to France as a kid when her dad got a job as the French king's astrologer -- as you do. She married and had three kids, but then her husband died of the plague, and thereafter she earned her living writing.

In *The Book of the City of Ladies*, de Pizan gathered up all the great and good women of history and placed them in a city where the Virgin Mary is queen. The book argues that women can be virtuous leaders and rational beings and that leadership by virtuous women could beget virtuous communities -- a stark contrast to Machiavelli's worldview.

So at this point, it's common to ask students to think about the relative merits of idealism and realism. Is a prince or princess -- or, for that matter, a student at a high school -- better off being loved or feared? Is it more important for a community to be fair or stable? Should leaders prioritize virtue or effectiveness? These are big, interesting questions, and I think they're worth considering.

But I would also ask you to look at the lens through which you're approaching those questions. Machiavelli's life was marked by endless wars and shifting alliances. He saw many short-lived governments fail to achieve stability. Christine de Pizan saw the intense oppression of women and the dismissal of their talents and intellect. Erasmus didn't exactly have an easy life -- he was born out of wedlock, and both his parents died of plague when he was a teenager -- but he saw a very different world in northern Europe than Machiavelli saw in Italy or than Christine de Pizan saw.

Where do you sit in the world, and how might that shape what kind of community you wish to see?

Thanks for watching. I'll see you next week.

Thanks so much for watching Crash Course European History, which is filmed here in Indianapolis and produced with the help of all of these nice people. Our animation team is Thought Cafe, and Crash Course would not exist without the generous support of our patrons on Patreon.

Patreon is a voluntary subscription service where you can support the content you love through a monthly donation and help keep Crash Course free for everyone forever. Thanks again for watching, and as they say in my hometown, don't forget to be awesome.

You.

'''