
= 005 - The Age of Exploration
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义


Hi, I’m John Green, and this is Crash Course European History.
So, remember back in May of 1453 when the Ottomans 奥斯曼人（土耳其帝国居民） smashed 粉碎 the thick walls of Constantinople, captured the city, and beheaded 斩首 the Byzantine emperor? You probably don’t remember May of 1453, come to think of it, but you remember learning about it. It was a bit of a footnote 脚注 in our first episode, but you never know when the footnotes are going to be very important, but that one really did change the world.

With the Ottomans now also controlling much of southeastern Europe, they established a navy, which they used in the Black, Adriatic, and other seas in the region. Ottoman domination 统治 meant that European kingdoms and empires needed to find different paths to Afroeurasian trading routes — which ultimately 最终地 helped spark 引发 the voyages 航行 of explorers from the Iberian peninsula 伊比利亚半岛.

So we’ve talked already in this series about the importance of shifting perspective when looking at history, and today we’re going to ask you to shift perspective several times, but let’s begin with the perspective of the Portuguese.

In the fifteenth century, Portugal was poor, and it became more so as the Ottomans contested 争夺 their access to overland 陆上的 trade. But luckily for Portugal, the fourth son of their king was Prince Henry, who came to be called The Navigator 航海家 because he funded 资助 and encouraged exploration, the study of navigation 航海术, and the development of new tools to aid in navigation.

The Portuguese began to increase their travels along the Mediterranean’s southern shore. And by the mid-15th century, they were venturing 冒险前往 southward along the Atlantic coast of Africa, where they expected to find vast 巨大的 wealth. In those days, Africa was rich in food, salt, gold, and slaves 奴隶.

Mansa Musa, the Malian king who made a spectacular 壮观的 hajj 朝觐 to Mecca in 1324-1325, was legendary 传奇的 and very inspiring to the Portuguese. He had an entourage 随行人员 of 60,000 people including 12,000 slaves and huge quantities of gold. He seemed like the model of what the Portuguese hoped to become by traveling to Africa: that is, rich beyond imagining.

In this pursuit 追求 of food, slaves, and gold, the Portuguese gradually made their way down the African coast, locating island clusters 群 like the Canaries. And they kidnapped 绑架 local people to sell into European slave markets and began dotting 遍布 the coast with stone fortresses 堡垒 that doubled as trading stations. And there, many European men partnered with African women and started families.

These women were often themselves traders and would be crucial 至关重要的 for all European nations; because they were the main force behind local markets and regional trade networks, and they provided essential 必不可少的 connections to trade. Again, most of the Portuguese explorers were poor, and many of these female traders were wealthy and successful. From their perspective, Portuguese traders offered them access to new markets and access to new goods.

I know we’re all very accustomed to 习惯于 thinking of Europe as rich and Africa as poor, but that frame 框架 is both relatively new and way too essentializing — the truth as always resists 抗拒 simplicity.

So in 1488, Bartolomeu Dias rounded the Cape of Good Hope 好望角, or, as it was called at the time, the Cape of Storms. And then the Portuguese ventured further afield 更远地 into the Indian Ocean.

When we talk about explorers and exploring, we often conjure up 想象出 images of intrepid 勇敢的 groups wearing hats trekking 长途跋涉 through empty lands in search of hidden treasures, but that was certainly not the reality when, for instance, Vasco De Gama reached India in 1498 and found a highly developed Indian Ocean commerce 贸易 with trading posts run by sophisticated 精明的 Muslim merchants.

Da Gama’s instincts 本能 were to menace 威胁 and fight them, and he did. And when the Portuguese reached Southeast Asia and China, they found a cornucopia 丰富的宝藏 of goods that Europeans came to crave 渴望 and about whose production they hadn’t the slightest knowledge: colorful, washable cottons, and finely crafted porcelain 瓷器, also tea.

Where would we be without tea? Well, I’d be fine, actually. I’d just drink coffee. What’s that? Oh, Stan informs me that coffee also isn’t from Europe.

By the seventeenth century, the Portuguese were importing millions of pieces of porcelain into Europe along with lots of delicious spices 香料. And spices were not only important for flavouring 调味, but also for food preservation 保存. Which I suppose is a kind of flavouring if you like your food not-mouldy 发霉的 tasting.

The Portuguese “empire” was, at first anyway, a trading empire, with small and agile 灵活的 ships known as caravels 卡拉维尔船（15世纪西班牙、葡萄牙的轻快帆船）patrolling 巡逻 ports and collecting large fees. The wealth would be extracted 提取 from controlling shipping and trading routes, as the Ottomans were doing in the eastern Mediterranean.

In contrast, the Spanish empire, which began in 1492 with the exploratory 探险的 voyages of Genoese ship captain Christopher Columbus, was based on colonies 殖民地 — that is, rather than controlling trade routes, the empire would control the land itself and the people who lived there, and extract wealth from them to enrich the empire.

Columbus was a student of geography and maps, and he’d lobbied 游说 the Portuguese king to back his voyages. But when that didn’t go to plan, he headed for Spain to petition 恳请 its devoutly 虔诚地 Catholic rulers, Queen Isabella of Castile and King Ferdinand of Aragon.

These two monarchs 君主 were finishing up the drive to expel 驱逐 Muslims from Spain and to force Spanish Jews to convert to Christianity. But religious persecution 迫害 wasn’t cheap. The motto 座右铭 of the Iberian pathfinders — God, gold, and glory — perfectly described their ambitions 抱负. Although perhaps not in that order.

Hopping the islands along the African coast and using the trade winds, Columbus’s ships made it to the Caribbean islands, and his crews, which tellingly 意味深长地 included both clergy 神职人员 and bankers, found signs of gold but not great quantities of it. However, they did find people to enslave 奴役, and because no one knew the size or shape of the Americas, there was the perpetual 持续的 hope that gold or other riches might lie just on the other side of this river, or that mountain.

So I want to stop here to shift perspective: From the perspective of European explorers, these lands were new, and potentially 潜在地 very lucrative 获利多的, and the colonization 殖民化 model that Spain adopted, and that Portugal began using in Brazil, and that the rest of Europe’s empires would eventually use, was built on the idea that colonies existed for the benefit and enrichment of the colonizers — and secondarily 次要地 to convert human souls to Christianity.

Much of the wealth that was generated by these empires was done so by claiming human beings as a form of property — both through the slave trade and through forcing colonized people to work. And the systems that were built to support the colonies — from roads and bridges to churches — were built to extract wealth and convert people to Christianity.

So from the perspective of indigenous 土著的 people living in colonized communities, colonization meant impoverishment 贫困 in many forms — the loss of land for use, the loss of life itself at an unprecedented 空前的 scale, the loss of long-held religious beliefs, and the loss of all sorts of community assets 资产.

But from the colonizers’ perspective, it meant the possibility of getting rich, and so waves of ambitious 有野心的 sailors followed Columbus, searching both North and South America for extractable 可开采的 wealth.

Another breakthrough 突破 occurred in 1519-22, when Ferdinand Magellan’s Spanish ships circumnavigated 环航 the globe. Magellan had alienated 使疏远 members of the Portuguese court and, like Columbus, he found no backing for his proposed trip there. Also like Columbus, he went to Spain to fund his voyage.

If you were going to be somewhere between 1519 and 1522, on one of Magellan’s ships was not necessarily the best place. The conditions and Magellan’s no-nonsense 严肃的 discipline 纪律 caused mutinies 兵变 and other problems, which Magellan also handled harshly, executing 处决 or marooning 流放 mutineering captains in the fleet.

But after finding the straits 海峡 at the tip of South America, the fleet set out across the Pacific, eventually returning to Spain despite Magellan’s death at the hands of local leaders in the Philippines in 1521. Of the 237 original voyagers and five ships, only eighteen men and one ship returned to Spain in 1522.

But the voyage arranged and headed by Magellan was a revelation 揭示；重大发现; it opened the world up to global transportation, exchange, settlement, and yes, global slavery, warfare, pandemics 流行病, and conquest 征服.

The Spanish could now stock 储备 their new world settlements with Chinese and Indian luxuries by crossing the Pacific and fill their coffers 金库 from profits in New World goods by crossing the Atlantic.

In 1519, Spanish invader 侵略者 Hernan Cortés came in contact with indigenous people in present-day Mexico, landing on its Mayan eastern coast with several hundred soldiers and making his way inland, starting battles and forging 建立 alliances 联盟.

He eventually reached the center of the Aztec empire at Tenochtitlan. The Spaniards were astonished 震惊的 at the wealth of this civilization, and Cortes bowed before its king, Montezuma II, who led a vast empire that stretched to present-day Honduras and Nicaragua.

The capital had tens of thousands of inhabitants, perhaps hundreds of thousands. Markets overflowed with luscious 甘美的 produce and crafts, and the city had a sophistication  sophistication n.  sophistication n. 复杂精妙 that, like the wealth itself, was foreign to Europeans, even if the Aztec practice of human sacrifice was also foreign.

A similar awe 敬畏 filled Francisco Pizarro when he saw the superb 极好的 textiles 纺织品 and silver and gold objects crafted by the Incas, who’d also created thousands of miles of roads and efficient institutions 机构 to hold their vast empire together along the west coast of present-day South America.

Both Pizarro and Cortes relied on help from rival 敌对的 indigenous communities to help them take control from the Incas and Aztecs. The conquerors 征服者 also married the princesses and other noble women they had raped as a ritual 仪式 of domination 统治. And marriage gave them access to insider information, local networks, and the wealth that such women possessed — including wealth in enslaved peoples.

So, Iberians 伊比利亚人 were incentivized 激励 to set sail by their poverty and by their Catholic faith, but they were disadvantaged 使处于不利地位 by a comparative 相对的 lack of manufacturing skills when it came to trade. What they did have, at least at first, was sailing prowess 高超技艺 and weaponry 武器 on their side.

Iberian caravels were nimble 灵活的, and they could be loaded with cannons 大炮. The Portuguese borrowed the use of triangular sails from the Arabs, often combining them with square-rigged 横帆的 ones to make better use of the winds.

And Iberians also employed 运用 a range of navigational 导航的 instruments 工具 — technology generally taken from other cultures — in determining latitude 纬度, while their on-board cartographers 制图师 created portolan charts 波特兰海图 — literally, charts related to ports — indicating coastal dangers, good harbors, and other details important to seafarers 航海者.

Astrolabes 星盘, quadrants 象限仪, compasses 指南针, and other instruments gave good indications of location and direction, but you know what you really needed? A clock. That’s right, there’s a clock in the center of the world. This six-dollar clock is an astonishing piece of technology. Stan would like me to point out that it was actually eight dollars.

Thank you for your support on Patreon.com/crashcourse. It wasn’t until the eighteenth-century development of the chronometer 精密计时器 that sailors could chart longitudinal 经度的 location, and even now, GPS relies on an extremely precise 精确的 knowledge of the time.

In short, when it comes to history and also everything else, it’s not just a question of where you are, it’s a question of when you are.

Early European explorers almost always had to enlist 征募 local people to advise them how to navigate the seas, especially the Indian Ocean, and local, non-European traders served as intermediaries 中介 for the artisans 工匠 in porcelain, cotton, and other crafted products.

Through them, Europeans slowly learned about trading procedures, sources of goods, and the means of judging quality, as initially 最初地 the Iberians were not well acquainted with 熟悉 the goods available in these trading ports.

And there were other go-betweens 中间人, like translators, connecting Europeans and local people. One example is Malinche (or Doña Maria, as the Spanish called her). She facilitated 促进 the passage of Hernan Cortes and his small army across Mexico and into the capital of the Aztec empire, gathering allies for him and warning him of impending 即将发生的 danger along the way.

Because of the hostility 敌意 among different groups, go-betweens who knew about the animosities 仇恨 and warfare among them could help mobilize 动员 support for the Europeans, so that one local group would lead the charge against another. That happened in the conquest of both Central America in the 1520s and the Inca Empire in the 1530s.

In Europe meanwhile, all of this voyaging and conquering produced chaos 混乱 between the Iberian kingdoms — what land would be Spain’s, and what land would be Portugal’s?

A treaty 条约 sponsored by the Church eventually settled disputes 争端 between Spain and Portugal over territory that each was claiming. I mean, who do you call about property disputes, if not the pope?

The Treaty of Tordesillas 托尔德西里亚斯条约, which was signed in 1494, provided a permanent line of demarcation 分界线 370 leagues west of the Cape Verde islands off the Atlantic coast of Africa. In 1529, another treaty set bounds 界限 for each country in the Indian Ocean and Pacific regions.

But treaties of course did not prevent the death at the hands of European weaponry and diseases that contact entailed 牵涉. In the Western Hemisphere, the local inhabitants’ lack of resistance 抵抗力 to European diseases was probably a more important factor in conquest than weaponry was.

In the long run, violence, enslavement 奴役, and European diseases like smallpox 天花 and measles 麻疹 led to the death of perhaps as much as ninety percent of the indigenous American population. Diseases spread and killed so quickly that entire communities ceased to exist almost at once, and with them their traditions, stories, and values.

Meanwhile, colonization proved extremely lucrative for Spain and Portugal, which within a century went from being poor kingdoms to astonishingly 惊人地 rich ones, especially after 1545, when the Spanish uncovered a huge deposit 矿床 of silver in Potosi, in present-day Bolivia, and began conscripting 征召 indigenous people to do the most dangerous work in the mines.

Migration 移民 to both regions swelled 膨胀, and ships now criss-crossed 纵横交错 both the Atlantic and the Pacific. And this huge influx 涌入 of wealth to Spain and Portugal would reshape power in Europe and also life everywhere else, as everything from microbes 微生物 to ideas suddenly had a truly global reach.

Thanks for watching. I’ll see you next time.

'''

== 中文释义


大家好，我是约翰·格林，这里是《速成欧洲史》。
还记得**1453年5月奥斯曼人攻破君士坦丁堡**的厚墙，占领城市, 并处决拜占庭皇帝的事吗？仔细想想，你可能不记得1453年5月，但一定记得学过这段历史。这在我们的第一集里只是个脚注，但谁也不知道脚注何时会变得至关重要——而**这个事件确实改变了世界。**

**随着奥斯曼人控制了东南欧大部分地区，他们**建立了海军，*在黑海、亚得里亚海及该地区其他海域活动。奥斯曼对那些地理的统治, 意味着欧洲王国和帝国需要寻找通往"亚非欧贸易路线"的新途径——这最终推动了"伊比利亚半岛"探险家的航行。*

我们在本系列中, 已经讨论过**"看待历史时, 转换视角"的重要性，今天我们会多次要求你转换视角，**但首先从葡萄牙人的视角开始。

15世纪的葡萄牙很穷，而奥斯曼人对其陆上贸易通道的争夺, 使其(葡萄牙)处境更加艰难。但对葡萄牙来说幸运的是，国王的第四个儿子亨利王子（因其资助和鼓励探险、航海研究, 及新航海工具的开发, 而被称为“航海家”）改变了这一切。

**葡萄牙人**开始增加沿地中海南岸的航行。到**15世纪中叶，他们沿非洲大西洋海岸, 向南探险，期望在那里找到巨大的财富。当时的非洲盛产粮食、盐、黄金和奴隶。**

1324-1325年壮观地前往麦加朝圣的马里国王曼萨·穆萨，是葡萄牙人的传奇榜样。他的随行队伍有6万人，包括1.2万名奴隶和大量黄金。他看起来就是葡萄牙人希望通过非洲航行成为的模样：富可敌国。

**在对粮食、奴隶和黄金的追逐中，葡萄牙人逐渐沿非洲海岸南下，发现了加那利群岛等岛群。他们绑架当地人, 卖到欧洲奴隶市场，并开始在海岸建造兼具贸易站功能的石头堡垒。#在那里，许多欧洲男子与非洲妇女结合, 组建家庭。#**

**这些女性通常本身就是商人，**对所有欧洲国家都至关重要；因为她们是当地市场和区域贸易网络的主力，提供了关键的贸易连接。**此外，#大多数葡萄牙探险家都很贫穷，而许多女性商人富有且成功。#**从她们的角度看，葡萄牙商人让她们接触到新市场和商品。

*#我们都习惯认为欧洲富裕而非洲贫穷，但这种框架既相对片面又过于绝对化——真相总是复杂的。#*

*1488年，巴尔托洛梅乌·迪亚士绕过好望角（当时称为“风暴角”）。随后，葡萄牙人进一步冒险进入印度洋。*

当我们谈论探险家与探险时，脑海中常浮现勇敢的队伍戴着帽子, 穿越空旷土地, 寻找隐藏宝藏的画面，但现实并非如此。例如，1498年瓦斯科·*达伽马抵达印度时，发现了高度发达的印度洋贸易，那里有精明的穆斯林商人经营的贸易站。*

达伽马的本能反应是威胁和战斗，他确实这么做了。*当葡萄牙人到达东南亚和中国时，他们发现了欧洲人渴望却对其生产一无所知的丰富商品：色彩鲜艳、耐洗的棉布、工艺精湛的瓷器，还有茶叶。*

如果没有茶，我们会怎样？其实，我还好，我可以喝咖啡。什么？斯坦告诉我**咖啡也不是欧洲原产的。**

到17世纪，葡萄牙人向欧洲进口了数百万件瓷器, 和大量美味香料。*香料不仅用于调味，还用于食品保存。如果你喜欢食物没有霉味，这也算一种调味吧。*

**葡萄牙“帝国”最初是贸易帝国，**由被称为“卡拉维尔”的小型敏捷船只巡逻港口, 并收取高额费用。*财富通过"控制航运和贸易路线"获取，就像奥斯曼人在地中海东部所做的那样。*

**相比之下，#西班牙帝国始于1492年#**热那亚船长克里斯托弗·*#哥伦布的探险航行，其基础是"殖民地"——即不是"控制贸易路线"，而是"控制土地本身, 及居住在那里的人"，并从他们身上榨取财富来充实帝国。#*

哥伦布是地理学和地图学的研究者，他曾游说葡萄牙国王支持他的航行。但计划失败后，他前往西班牙，向虔诚的天主教统治者卡斯蒂利亚女王伊莎贝拉, 和阿拉贡国王斐迪南请愿。

这两位君主正完成将穆斯林逐出西班牙, 并迫使西班牙犹太人皈依基督教的行动。但宗教迫害代价高昂。伊比利亚开拓者的座右铭“上帝、黄金、荣耀”完美描述了他们的野心——尽管顺序可能不同。

借助沿非洲海岸的岛屿和信风，**哥伦布的船队抵达加勒比群岛，**他的船员（其中明显包括神职人员和银行家）**发现了黄金的迹象，但数量不多。**然而，*他们确实找到了可以奴役的人，而且由于没人知道美洲的大小和形状*，人们一直希望黄金或其他财富, 可能就在这条河或那座山的另一边。

我想在此转换视角：从欧洲探险家的角度看，这些土地是全新的，潜在利润巨大，*西班牙采用的"殖民模式"（葡萄牙开始在巴西使用，欧洲其他帝国最终也效仿）建立在“殖民地存在是为了殖民者的利益和致富”的理念之上，其次是让人们皈依基督教。*

这些帝国创造的财富很大一部分, 来自将人视为财产——通过奴隶贸易, 和强迫殖民地人民劳动。为支持殖民地而建的系统（从道路、桥梁到教堂）, 都是为了榨取财富, 和使人皈依基督教。

因此，*从生活在殖民社区的"原住民"角度看，殖民意味着各种形式的贫困：失去可用土地、前所未有的生命损失、长期宗教信仰的丧失，以及各种社区资产的流失。*

**但从殖民者的角度看，这意味着致富的可能，**因此大批雄心勃勃的水手, 追随哥伦布，在北美和南美寻找可开采的财富。

**另一个突破, 发生在1519-1522年，费迪南德·麦哲伦的西班牙船队, 完成了环球航行。**麦哲伦曾与葡萄牙宫廷成员不和，*和哥伦布一样，他在葡萄牙找不到对其航行计划的支持。也和哥伦布一样，他去西班牙为航行寻求资金。*

如果你生活在1519-1522年，乘坐麦哲伦的船, 未必是最好的选择。*船上的条件, 和麦哲伦的铁腕纪律, 引发了叛乱和其他问题，他也严厉处置了这些问题，处决或流放了船队中叛乱的船长。*

但在发现南美洲尖端的海峡后，船队穿越大西洋，最终返回西班牙，尽管麦哲伦于1521年在菲律宾死于当地领导人之手。最初的237名航海者和5艘船中，1522年只有18人和1艘船返回西班牙。

但麦哲伦策划和领导的航行, 是一次启示；它开启了全球运输、交流、定居，当然还有全球奴隶制、战争、流行病和征服。

西班牙人现在可以通过横渡太平洋, 为其新大陆定居点储备中国和印度的奢侈品，并通过横渡大西洋, 从新大陆商品中获利充实国库。

1519年，西班牙侵略者埃尔南·科尔特斯, 在今墨西哥与原住民接触，他率领数百名士兵在玛雅东海岸登陆，向内陆进发，发动战斗并建立联盟。

他最终抵达"阿兹特克帝国"的中心"特诺奇蒂特兰"。西班牙人对这个文明的财富感到震惊，科尔特斯向其国王蒙特苏马二世鞠躬，后者领导着一个延伸至今洪都拉斯和尼加拉瓜的庞大帝国。

这座首都有数十万甚至数百名居民。市场上摆满了丰富的农产品和手工艺品，城市的 sophistication（就像财富本身一样）对欧洲人来说是陌生的，尽管阿兹特克的"人祭"习俗, 对他们来说也很陌生。

弗朗西斯科·皮萨罗看到印加人制作的精美纺织品和金银器物时, 也充满敬畏，印加人还在今南美洲西海岸, 修建了数千英里的道路和有效的机构, 来维系其庞大的帝国。

**##皮萨罗和科尔特斯,  都依靠敌对的原住民社区, 帮助他们从印加人和阿兹特克人手中夺取控制权。##征服者还将他们强奸的公主和其他贵族妇女, **作为统治仪式的一部分, *娶为妻子。#婚姻使他们获得了内部信息、当地网络, 以及这些女性拥有的财富#——包括奴隶财富。*

因此，伊比利亚人因贫穷和天主教信仰, 而被激励启航，但在贸易方面，他们因相对缺乏制造技能而处于不利地位。至少一开始，他们拥有的是航海能力和武器。

伊比利亚的卡拉维尔船, 灵活轻便，可以装载大炮。*葡萄牙人从阿拉伯人那里借鉴了"三角帆"的使用，经常将其与"横帆"结合, 以更好地利用风力。*

伊比利亚人还使用一系列导航仪器（通常是从其他文化借鉴的技术）来确定纬度，而船上的制图师绘制了"波特兰海图"（字面意思是与港口相关的海图），标明沿海危险、优良港口, 和其他对海员重要的细节。

**星盘、象限仪、指南针, 和其他仪器, 能很好地指示位置和方向，但你知道真正需要什么吗？时钟。**没错，世界中心有一个时钟。这个六美元的时钟是一项惊人的技术。斯坦想让我指出它实际上花了八美元。

感谢你在Patreon.com/crashcourse上的支持。*#直到18世纪发明"精密计时器"后，水手们才能绘制"经度"位置，即使现在，GPS也依赖于对时间的极精确了解。#*

简而言之，关于历史和其他一切，不仅是“你在哪里”的问题，也是“你在何时”的问题。

**早期欧洲探险家几乎总是需要招募当地人, 来指导他们如何在海上航行，**尤其是在印度洋，当地的"非欧洲商人"充当了瓷器、棉花和其他手工艺品工匠的中介。

**通过他们，欧洲人慢慢了解了贸易程序、商品来源和质量判断方法，**因为最初伊比利亚人对这些贸易港口的商品并不熟悉。

**还有其他中间人，比如翻译，**连接着欧洲人和当地人。马林切（或西班牙人所称的多娜·玛丽亚）就是一个例子。她帮助埃尔南·科尔特斯和他的小军队, 穿越墨西哥进入阿兹特克帝国的首都，为他聚集盟友，并沿途警告他即将到来的危险。

**#由于不同群体之间的敌意，"了解他们之间仇恨和战争"的中间人, 可以帮助动员对欧洲人的支持，使一个当地群体, 带头对抗另一个群体。#**这种情况在16世纪20年代对中美洲的征服, 和16世纪30年代对印加帝国的征服中, 都发生过。

与此同时，*#在欧洲，所有这些航行和征服, 在伊比利亚半岛王国之间引发了混乱——哪些土地是西班牙的，哪些是葡萄牙的？#*

**教会发起的一项条约, 最终解决了西班牙和葡萄牙对各自声称领土的争端。**我的意思是，如果不是教皇，你会找谁解决财产纠纷？

1494年签署的《托尔德西里亚斯条约》, 在非洲大西洋海岸佛得角群岛以西370里格处, 划定了永久分界线。1529年，另一项条约为两国在印度洋和太平洋地区划定了边界。

但条约当然无法阻止欧洲武器, 和接触带来的疾病导致的死亡。在西半球，当地人对欧洲疾病缺乏抵抗力，这可能是征服中比武器更重要的因素。

**从长远来看，暴力、奴役和天花、麻疹等欧洲疾病, 可能导致美洲原住民人口减少了90%。**疾病传播和致死速度如此之快，整个社区几乎瞬间消失，*随之消失的还有他们的传统、故事和价值观。*

与此同时，**#殖民对西班牙和葡萄牙来说极为有利可图，这两个国家在一个世纪内, 从贫穷王国变成了极其富有的国家，#**尤其是1545年西班牙在今"玻利维亚"的"波托西"发现巨大银矿后，开始征召原住民在矿中从事最危险的工作。

向这两个地区的移民激增，船只现在横渡大西洋和太平洋。西班牙和葡萄牙的财富大量涌入, 将重塑欧洲的权力，也重塑其他各地的生活，因为从微生物(疾病病毒)到思想(殖民思想,新教思想,重商主义)的一切, 突然都有了真正的全球影响力。

感谢观看，下周见。


'''

== pure

Hi, I’m John Green, and this is Crash Course European History.
So, remember back in May of 1453 when the Ottomans smashed the thick walls of Constantinople, captured the city, and beheaded the Byzantine emperor? You probably don’t remember May of 1453, come to think of it, but you remember learning about it. It was a bit of a footnote in our first episode, but you never know when the footnotes are going to be very important, but that one really did change the world.

With the Ottomans now also controlling much of southeastern Europe, they established a navy, which they used in the Black, Adriatic, and other seas in the region. Ottoman domination meant that European kingdoms and empires needed to find different paths to Afroeurasian trading routes -- which ultimately helped spark the voyages of explorers from the Iberian peninsula.

So we’ve talked already in this series about the importance of shifting perspective when looking at history, and today we’re going to ask you to shift perspective several times, but let’s begin with the perspective of the Portuguese.

In the fifteenth century, Portugal was poor, and it became more so as the Ottomans contested their access to overland trade. But luckily for Portugal, the fourth son of their king was Prince Henry, who came to be called The Navigator because he funded and encouraged exploration, the study of navigation, and the development of new tools to aid in navigation.

The Portuguese began to increase their travels along the Mediterranean’s southern shore. And by the mid-15th century, they were venturing southward along the Atlantic coast of Africa, where they expected to find vast wealth. In those days, Africa was rich in food, salt, gold, and slaves.

Mansa Musa, the Malian king who made a spectacular hajj to Mecca in 1324-1325, was legendary and very inspiring to the Portuguese. He had an entourage of 60,000 people including 12,000 slaves and huge quantities of gold. He seemed like the model of what the Portuguese hoped to become by traveling to Africa: that is, rich beyond imagining.

In this pursuit of food, slaves, and gold, the Portuguese gradually made their way down the African coast, locating island clusters like the Canaries. And they kidnapped local people to sell into European slave markets and began dotting the coast with stone fortresses that doubled as trading stations. And there, many European men partnered with African women and started families.

These women were often themselves traders and would be crucial for all European nations; because they were the main force behind local markets and regional trade networks, and they provided essential connections to trade. Again, most of the Portuguese explorers were poor, and many of these female traders were wealthy and successful. From their perspective, Portuguese traders offered them access to new markets and access to new goods.

I know we’re all very accustomed to thinking of Europe as rich and Africa as poor, but that frame is both relatively new and way too essentializing -- the truth as always resists simplicity.

So in 1488, Bartolomeu Dias rounded the Cape of Good Hope, or, as it was called at the time, the Cape of Storms. And then the Portuguese ventured further afield into the Indian Ocean.

When we talk about explorers and exploring, we often conjure up images of intrepid groups wearing hats trekking through empty lands in search of hidden treasures, but that was certainly not the reality when, for instance, Vasco De Gama reached India in 1498 and found a highly developed Indian Ocean commerce with trading posts run by sophisticated Muslim merchants.

Da Gama’s instincts were to menace and fight them, and he did. And when the Portuguese reached Southeast Asia and China, they found a cornucopia of goods that Europeans came to crave and about whose production they hadn’t the slightest knowledge: colorful, washable cottons, and finely crafted porcelain, also tea.

Where would we be without tea? Well, I’d be fine, actually. I’d just drink coffee. What’s that? Oh, Stan informs me that coffee also isn’t from Europe.

By the seventeenth century, the Portuguese were importing millions of pieces of porcelain into Europe along with lots of delicious spices. And spices were not only important for flavouring, but also for food preservation. Which I suppose is a kind of flavouring if you like your food not-mouldy tasting.

The Portuguese “empire” was, at first anyway, a trading empire, with small and agile ships known as caravels patrolling ports and collecting large fees. The wealth would be extracted from controlling shipping and trading routes, as the Ottomans were doing in the eastern Mediterranean.

In contrast, the Spanish empire, which began in 1492 with the exploratory voyages of Genoese ship captain Christopher Columbus, was based on colonies -- that is, rather than controlling trade routes, the empire would control the land itself and the people who lived there, and extract wealth from them to enrich the empire.

Columbus was a student of geography and maps, and he’d lobbied the Portuguese king to back his voyages. But when that didn’t go to plan, he headed for Spain to petition its devoutly Catholic rulers, Queen Isabella of Castile and King Ferdinand of Aragon.

These two monarchs were finishing up the drive to expel Muslims from Spain and to force Spanish Jews to convert to Christianity. But religious persecution wasn’t cheap. The motto of the Iberian pathfinders — God, gold, and glory — perfectly described their ambitions. Although perhaps not in that order.

Hopping the islands along the African coast and using the trade winds, Columbus’s ships made it to the Caribbean islands, and his crews, which tellingly included both clergy and bankers, found signs of gold but not great quantities of it. However, they did find people to enslave, and because no one knew the size or shape of the Americas, there was the perpetual hope that gold or other riches might lie just on the other side of this river, or that mountain.

So I want to stop here to shift perspective: From the perspective of European explorers, these lands were new, and potentially very lucrative, and the colonization model that Spain adopted, and that Portugal began using in Brazil, and that the rest of Europe’s empires would eventually use, was built on the idea that colonies existed for the benefit and enrichment of the colonizers -- and secondarily to convert human souls to Christianity.

Much of the wealth that was generated by these empires was done so by claiming human beings as a form of property -- both through the slave trade and through forcing colonized people to work. And the systems that were built to support the colonies -- from roads and bridges to churches -- were built to extract wealth and convert people to Christianity.

So from the perspective of indigenous people living in colonized communities, colonization meant impoverishment in many forms -- the loss of land for use, the loss of life itself at an unprecedented scale, the loss of long-held religious beliefs, and the loss of all sorts of community assets.

But from the colonizers’ perspective, it meant the possibility of getting rich, and so waves of ambitious sailors followed Columbus, searching both North and South America for extractable wealth.

Another breakthrough occurred in 1519-22, when Ferdinand Magellan’s Spanish ships circumnavigated the globe. Magellan had alienated members of the Portuguese court and, like Columbus, he found no backing for his proposed trip there. Also like Columbus, he went to Spain to fund his voyage.

If you were going to be somewhere between 1519 and 1522, on one of Magellan’s ships was not necessarily the best place. The conditions and Magellan’s no-nonsense discipline caused mutinies and other problems, which Magellan also handled harshly, executing or marooning mutineering captains in the fleet.

But after finding the straits at the tip of South America, the fleet set out across the Pacific, eventually returning to Spain despite Magellan’s death at the hands of local leaders in the Philippines in 1521. Of the 237 original voyagers and five ships, only eighteen men and one ship returned to Spain in 1522.

But the voyage arranged and headed by Magellan was a revelation; it opened the world up to global transportation, exchange, settlement, and yes, global slavery, warfare, pandemics, and conquest.

The Spanish could now stock their new world settlements with Chinese and Indian luxuries by crossing the Pacific and fill their coffers from profits in New World goods by crossing the Atlantic.

In 1519, Spanish invader Hernan Cortés came in contact with indigenous people in present-day Mexico, landing on its Mayan eastern coast with several hundred soldiers and making his way inland, starting battles and forging alliances.

He eventually reached the center of the Aztec empire at Tenochtitlan. The Spaniards were astonished at the wealth of this civilization, and Cortes bowed before its king, Montezuma II, who led a vast empire that stretched to present-day Honduras and Nicaragua.

The capital had tens of thousands of inhabitants, perhaps hundreds of thousands. Markets overflowed with luscious produce and crafts, and the city had a sophistication that, like the wealth itself, was foreign to Europeans, even if the Aztec practice of human sacrifice was also foreign.

A similar awe filled Francisco Pizarro when he saw the superb textiles and silver and gold objects crafted by the Incas, who’d also created thousands of miles of roads and efficient institutions to hold their vast empire together along the west coast of present-day South America.

Both Pizarro and Cortes relied on help from rival indigenous communities to help them take control from the Incas and Aztecs. The conquerors also married the princesses and other noble women they had raped as a ritual of domination. And marriage gave them access to insider information, local networks, and the wealth that such women possessed — including wealth in enslaved peoples.

So, Iberians were incentivized to set sail by their poverty and by their Catholic faith, but they were disadvantaged by a comparative lack of manufacturing skills when it came to trade. What they did have, at least at first, was sailing prowess and weaponry on their side.

Iberian caravels were nimble, and they could be loaded with cannons. The Portuguese borrowed the use of triangular sails from the Arabs, often combining them with square-rigged ones to make better use of the winds.

And Iberians also employed a range of navigational instruments — technology generally taken from other cultures — in determining latitude, while their on-board cartographers created portolan charts -- literally, charts related to ports -- indicating coastal dangers, good harbors, and other details important to seafarers.

Astrolabes, quadrants, compasses, and other instruments gave good indications of location and direction, but you know what you really needed? A clock. That’s right, there’s a clock in the center of the world. This six-dollar clock is an astonishing piece of technology. Stan would like me to point out that it was actually eight dollars.

Thank you for your support on Patreon.com/crashcourse. It wasn’t until the eighteenth-century development of the chronometer that sailors could chart longitudinal location, and even now, GPS relies on an extremely precise knowledge of the time.

In short, when it comes to history and also everything else, it’s not just a question of where you are, it’s a question of when you are.

Early European explorers almost always had to enlist local people to advise them how to navigate the seas, especially the Indian Ocean, and local, non-European traders served as intermediaries for the artisans in porcelain, cotton, and other crafted products.

Through them, Europeans slowly learned about trading procedures, sources of goods, and the means of judging quality, as initially the Iberians were not well acquainted with the goods available in these trading ports.

And there were other go-betweens, like translators, connecting Europeans and local people. One example is Malinche (or Doña Maria, as the Spanish called her). She facilitated the passage of Hernan Cortes and his small army across Mexico and into the capital of the Aztec empire, gathering allies for him and warning him of impending danger along the way.

Because of the hostility among different groups, go-betweens who knew about the animosities and warfare among them could help mobilize support for the Europeans, so that one local group would lead the charge against another. That happened in the conquest of both Central America in the 1520s and the Inca Empire in the 1530s.

In Europe meanwhile, all of this voyaging and conquering produced chaos between the Iberian kingdoms -- what land would be Spain’s, and what land would be Portugal’s?

A treaty sponsored by the Church eventually settled disputes between Spain and Portugal over territory that each was claiming. I mean, who do you call about property disputes, if not the pope?

The Treaty of Tordesillas, which was signed in 1494, provided a permanent line of demarcation 370 leagues west of the Cape Verde islands off the Atlantic coast of Africa. In 1529, another treaty set bounds for each country in the Indian Ocean and Pacific regions.

But treaties of course did not prevent the death at the hands of European weaponry and diseases that contact entailed. In the Western Hemisphere, the local inhabitants’ lack of resistance to European diseases was probably a more important factor in conquest than weaponry was.

In the long run, violence, enslavement, and European diseases like smallpox and measles led to the death of perhaps as much as ninety percent of the indigenous American population. Diseases spread and killed so quickly that entire communities ceased to exist almost -- at once, and with them their traditions, stories, and values.

Meanwhile, colonization proved extremely lucrative for Spain and Portugal, which within a century went from being poor kingdoms to astonishingly rich ones, especially after 1545, when the Spanish uncovered a huge deposit of silver in Potosi, in present-day Bolivia, and began conscripting indigenous people to do the most dangerous work in the mines.

Migration to both regions swelled, and ships now criss-crossed both the Atlantic and the Pacific. And this huge influx of wealth to Spain and Portugal would reshape power in Europe and also life everywhere else, as everything from microbes to ideas suddenly had a truly global reach.

Thanks for watching. I’ll see you next time.

'''