
= 006 - Expansion and Consequences
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义


Hi, I’m John Green, and this is Crash Course European History.
So today we’re going to continue looking at European expansion 扩张 and its impact 影响 on the world’s humans. Like, imagine learning that there are people in places you did not know existed, that they eat foods you’ve never seen, that their world contains plant and animal species 物种 entirely different from your world.

What people thought was one world turned out to be two, and the collision 碰撞 of those worlds wrought 造成 devastation 毁灭 and opportunity on a truly mind-boggling 令人难以置信的 scale. And today, we’re going to ask you to look at the consequences 后果 of European expansion, and consider how those consequences change depending on where you find yourself.

Destruction from Iberian expansion was truly extraordinary 非凡的 across the sixteenth century. As Hernan Cortes commented: “We could not walk without treading on 踩在…上 the bodies and heads of dead Indians.”[i]

Besides the slaughter 屠杀 of empire-building directly inflicted 施加 by the invaders 侵略者 and their local allies, the ongoing progress of smallpox 天花, and measles 麻疹, and other diseases that Europeans brought to the Americas completely overwhelmed 压垮 the healthcare systems of native Americans. Many millions died. Within a century, the population of native Americans had fallen perhaps by as much as 90%.

Throughout the Spanish Empire in the Americas, the colonizers 殖民者 made use of existing political structures that were already in place for collecting taxes and otherwise maintaining order. Even as the Spanish king appointed 任命 elite 精英的 men from Spain as viceroys 总督 enforcing 执行 civil and military rule over what had been the Incan Empire, for instance, the Incan systems of roads and communication networks facilitated 促进 Spanish domination 统治.

It’s also important to remember that because the Spanish had never before experienced almost three-thousand-mile-long imperial 帝国的 operation, like the one the Incans had, the Spanish had very little understanding of how to maintain its functions or to provide for its upkeep 维护.

Much as the Spanish empire initially 最初地 depended on brute force 蛮力, sustaining 维持 it required practical interactions with conquered people and in many cases their cooperation 合作.

The rewards 回报 of empire for the Spanish were truly astonishing 惊人的. Thanks to the seizure 夺取 of art and religious objects made with precious metals 贵金属, the discovery of mines, and the know-how 技能 of native Americans and others in running those mines, by the mid-sixteenth century silver and gold were pouring into Spain. And what had been a very poor kingdom became a very, very rich one.

It’s now believed that pre-Columbian peoples knew how to use liquid mercury 汞 to process silver and gold -- a method that’s still used today. It was also used by the Spanish. And by the end of the century, the Portuguese had discovered precious metals in Brazil, too.

The Portuguese cut down trees in Brazilian forests to trade in Brazilwood. And sugar production flourished 繁荣 across the Caribbean beginning in Jamaica in 1515 and eventually spreading across tropical 热带的 and forested regions of the New World, where the vast tracts 大片土地 of trees could be felled 砍伐 to feed the fires needed for sugar refining 精炼.

To launch and sustain 维持 all these enterprises 企业 -- mining, metallurgy 冶金学, sugar refining, lumbering 伐木业 -- Iberians initially used the forced labor and know-how of local peoples, as I mentioned earlier. The Spanish government awarded 授予 its soldiers and adventurers encomienda 委托监护制 (a system of forced labor in Spanish colonies), that is the labor of local people on a large plot of land.

But there were critics 批评者 of this system among Europeans, perhaps most notably Bartolomé Las Casas, a Catholic missionary 传教士 who had helped in the savage 野蛮的 conquest of Cuba and who had received an encomienda for his participation. But then the preaching 布道 of a Dominican friar 修士 made him see conquest in a different light, and he began a campaign 运动 on behalf of local people.

Las Casas, while underscoring 强调 the benefits of conversion 皈依 to Christianity, lambasted 严厉批评 his fellow conquerors for their murder, brutality 残忍, and pillage 掠夺. He wrote of native Americans, “To subject them first by warlike means is a form and procedure contrary to 与…相反 the law … and gentleness of Jesus Christ.”

Las Casas wrote much more and lobbied 游说 the Spanish court (some would say he harassed 骚扰 it), beginning in some historians’ minds the drive for what are considered today human rights.

Las Casas’ story is a reminder that the cause of human rights always needs people who have them in order to press it forward. But ultimately 最终地 the people who are responsible for expansions in human rights are the people who are denied 被剥夺 them and insist upon their humanity anyway.

So to shift perspectives for a moment, some Europeans were advocating for 倡导 human rights, but many, many people without those rights were advocating for them. And as for indigenous 土著的 people in the New World, to present one story of their response to colonization would be inaccurate 不准确的 -- at times, communities and individuals resisted 抵抗; at times, some cooperated.

But it’s hard to overstate 高估 how destabilizing 破坏性的 it was to these communities to lose, in many cases, 90% of their population.

One of the huge changes, though, was the arrival of Christianity and the demand that the colonized become Christians. Christianity changed the Americas, but the Americas also changed Christianity.

In the face of the demand of the Church that conquered people become Catholic, they might, for instance, blend 融合 their own beliefs with Catholic ones. In 1531, the Aztec Cuauhtlatoatzin, whose baptismal 洗礼的 name was Juan Diego, had five visions 幻象 of the Virgin Mary on a sacred 神圣的 Aztec spot of the corn goddess, near Mexico City.

Mary’s miracles left an imprint 印记 of her form on Juan Diego’s cape. And on the cape, Mary appeared to be an Aztec woman wearing a robe with Aztec designs and symbols. This version of Mary, known as Our Lady of Guadalupe, was brown-skinned and was often called “the dark virgin.”

Many shrines 圣地 to Our Lady of Guadalupe were built, and her story was written down both in Spanish and in the Aztec language, Nahuatl. Our Lady of Guadalupe replaced some of the local goddesses that were suppressed 压制 by the Christians. Women in particular took up devotion 虔诚 to her as a symbol of motherhood. And today, Our Lady of Guadalupe’s basilica 大教堂 in Mexico City is said to be the most visited shrine in the world.

It wasn’t too long before other European powers, eyeing 觊觎 these profits, sought to literally capture Spanish wealth. Like English privateer 私掠船船长 Francis Drake began his career of attacking Spanish shipping in the 1560s and often seized 夺取 huge fortunes for the queen and investors in his voyages.

While circumnavigating 环航 the globe, he captured stores of Spanish gold and silver from ships along the west coast of South America. In some cases, a single seizure might yield 产生 the equivalent 等同物 of an entire year’s income for the royal treasury 国库.

You heard that right -- taking down one Spanish ship could equal all the tax collection in England for a year -- which gives you a sense of just how much wealth was being extracted 提取 from colonies. No wonder Elizabeth knighted 授予爵位 Drake in 1581 after he returned from his historic circumnavigation -- which was only the second circumnavigation of the globe in European history at the time.

And Drake made it home. Magellan -- Stan, am I allowed to make a joke about Magellan dying? Has enough time passed? Stan says “yes.” Right.

So the French, Dutch, and other treasure-hungry people joined the English in Atlantic piracy 海盗行为, which increased the wealth of many European kingdoms and individuals, of course. But those same European states also began imitating 模仿 the Portuguese and Spanish in global exploration, trade, and eventually settlement 殖民.

In 1497, Italian sailor John Cabot, which was not his Italian name by the way. I’ve always found it very funny that the two most famous Italian sailors in history are named John Cabot and Christopher Columbus.

At any rate, John Cabot, commissioned 委托 by Henry VII of England, landed somewhere north of Maine, probably on the Canadian coast, and then returned to London to great acclaim 赞誉.

The English established the East India Company in 1600 to focus on their exploration efforts, and the Dutch founded a similar United East India Company in 1602, which brought together several trading companies from various Dutch states. And other governments chartered 特许成立 similar corporations 公司.

These companies performed a variety of functions, from gathering investors and building ships to raising armies and taking over new territory and enslaving 奴役 people to work conquered land. Lest 以免 you think that corporations are newly evil.

Which brings us to the slave trade. Initially, Portuguese sailors sought to catch Africans they happened to spot along the coast and then sell them as slaves in Europe. But by the end of the sixteenth century, the capture of Africans for sale to Europeans became routine 常规的 and then eventually a massive 大规模的 business for both African slave traders and Europeans after 1650.

And this was also partly due to disease and the devastation 破坏 of colonization. The Spanish had trouble with sugar production in the Caribbean after the native Taino people had been wiped out 消灭 by disease; the British then took over and began importing African slaves to work in sugar plantations 种植园.

By the eighteenth century, British slavers 奴隶贩子 had taken the lead in the Atlantic trade. Partly due to petitions 请愿书 like those from Las Casas, Spanish rulings that Native Americans could not be enslaved led the Spanish landowners and mine operators to import Africans and Asians to stay within the law, which did not yet say that people could not be enslaved.

Some Asian slaves, once brought to the Spanish Empire, were able to pass as local people and claim their freedom on that basis. But almost everyone who was enslaved died in slavery. Life expectancy 预期寿命 was very low; all manner of mistreatment 虐待 was common; and legal protections were almost nonexistent 不存在的.

It’s very important to consider those perspectives too. And also to consider why, traditionally, those perspectives have been ignored.

We’ve talked about how the establishment of transoceanic 跨洋的 travel meant that diseases, and people, and finished goods were traveling across oceans, but so were plants and animal species. This whole process is sometimes known as the Columbian exchange 哥伦布大交换.

This movement of goods and people and species across the Atlantic was tremendously 极大地 important to history -- before it, New World foods like pumpkins and tomatoes, maize 玉米, potatoes did not even exist in Afroeurasia.

Did the globe open up? What’s in the center of the world? It’s a pumpkin. You want to know why there were no jack-o’-lanterns in 13th-century Europe? There were no pumpkins. There was no popcorn because there was no corn. #sponsored. I wish. I love this stuff.

You know the famous bananas of South America? No, you don’t. Bananas are from Africa. They didn’t exist in the Americas until the Columbian exchange.

So much of what feels natural and even defining 决定性的 about our cultures and histories is in fact really, really new. Nigerian cassava 木薯. Irish potatoes. Vanilla ice cream in Europe. Tomatoes in Italy. None of this was conceivable 可想象的 before the Columbian exchange.

Europeans also learned a lot from the Americas about food preservation 保存. Like the Incas dried some potatoes, for instance, which made them lighter and easier to transport, and then would later reconstitute 重新构成 them so they could be eaten, a strategy 策略 which fortified 增强 messengers along the Inca’s extensive 广泛的 network of roads.

Similar processes came to be used in Europe and would eventually be used to fortify astronauts, who often eat reconstituted dehydrated 脱水的 food. And over time, potatoes and maize (known here as corn) increased overall calories available to Europeans because they could be dried and stored in huge quantities. And that decreased starvation 饥饿 and increased populations.

Meanwhile, as we’ve discussed, the travel of microbes 微生物 to the Americas devastated 摧毁 communities there, and a range of Afroeurasian animals -- horses, sheep, and pigs, to name a few -- arrived in the New World for the first time.

In some ways, these new animals were useful, of course, but they also did extensive 广泛的 damage, stripping away vegetation 植被 necessary for soil conservation 保护 and trampling 践踏 farmland. And deforestation 森林砍伐 began with the clearing of forests for sugar cane production, as we discussed earlier, a process that accelerated 加速 in Central and South Americas through the twentieth century.

In Europe, sugar was initially such a precious luxury 奢侈品 that a sprinkle 撒 of it was all that even the wealthy could afford. Queen Isabella of Castile and Spain gave a small box of sugar to her daughter as a Christmas present to be treasured 珍视.

Chocolate began as a ceremonial 仪式的 drink for the powerful, as it was among the Aztecs. But as European communities became wealthier, more people transitioned 转变 from subsistence 生存 living to being able to afford goods from distant places.

Treats 美食 of sugar, chocolate, tea, coffee, and tobacco 烟草 transformed attitudes, while the hot water that was needed for making tea and coffee and hot cocoa is thought to have extended the lifespans in Europe by killing water-borne germs 病菌.

And slowly the English and some of Spain and Portugal’s other competitors established their own colonies -- the English had the unsuccessful colony of Roanoke in the 1580s, and then Jamestown in 1607, and the Massachusetts Bay Colony in 1620.

Some of these settlers 移民 came in families, but many came as single men and occasionally single women. And in the developing propaganda 宣传 war among these rivals, English latecomers to the Atlantic world promoted an idea that came to be called the “Black Legend 黑色传奇.”

It maintained that, unlike the tolerant 宽容的 and kind English Protestants, the Spanish were bigoted 偏执的 Catholics, brutal 残忍的 and destructive of local people. That would be what psychologists call “projection 投射.”

Today we know that English settlers slaughtered 屠杀 local peoples with abandon 肆意地 -- even people on whom their own survival depended, because many adventurers had no knowledge of farming. Moreover 此外, most English settlers were as bigoted as other Europeans in those days.

But the “Black Legend” was a really powerful idea in history for a long time -- in fact, when I was a kid growing up in Florida, I was told that it was unfortunate Florida had been a Spanish colony, because the English were much kinder rulers.

So by the end of the seventeenth century, the rush 热潮 for trade and empire was in full swing 全面展开. Plantations based on New World tobacco 烟草 had been set up in North America and sugar mills 磨坊 in the Caribbean and South America.

Mining and many other lucrative 获利的 enterprises, as well as the promise of exploitable 可开发的 land, kept the Atlantic and Pacific Oceans crowded with voyagers 航海者. All the while, most native people ruled by colonizers saw the vast majority of their labor’s value exported 输出.

It was the beginning of the true globalization we experience today, complete with all of its contradictions 矛盾 and complexities 复杂性. We live in a world today of tremendous abundance 丰富, where a pinch 少量 of sugar is not generally seen as a great Christmas present.

Starvation and child mortality 死亡率 are more rare than they have ever been. But we also live in a world with profound 深刻的 inequality 不平等 and injustice 不公, where the powerful have legal and social protections that the weak do not.

It’s important to remember that in all those senses, we are the products of history -- but of course we are also producing history.

Thanks for watching. I’ll see you next time.

[i] Bernal Dias, quoted in Jackson J. Spielvogel, Western Civilization, 7th ed. (Belmont, CA: Thomson Wadsworth, 2009) 419.
[ii] Bartolomé Las Casas, “Thirty Very Juridical Propositions” (1552) quoted in Bonnie G. Smith, ed., Modern Empires: A Reader (New York: Oxford University Press, 2018) 64-67.

'''

== 中文释义


大家好，我是约翰·格林，这里是《速成欧洲史》。
今天我们将继续探讨欧洲扩张, 及其对全球人类的影响。试想一下，当你得知在未知的地方存在着不同的人群，他们食用你从未见过的食物，他们的世界里有与你完全不同的动植物物种，会作何感想？

原本被认为是“一个世界”的认知，最终变成了“两个世界”，而这两个世界的碰撞带来了规模惊人的毁灭与机遇。今天，我们希望你审视欧洲扩张的后果，并思考这些后果如何因视角不同而迥异。

*16世纪，伊比利亚扩张带来的破坏, 堪称惨烈。正如埃尔南·科尔特斯所言：“我们每走一步，都要踩在印第安人的尸体和头颅上。”*[i]

除了侵略者及其本地盟友, 在建立帝国过程中直接实施的屠杀，天花、麻疹等欧洲人带入美洲的疾病, 持续肆虐，彻底击垮了美洲原住民的医疗体系。数百万人死亡。*一个世纪内，美洲原住民人口可能减少了多达90%。*

在西班牙美洲帝国境内，殖民者利用当地现有的征税和维持秩序的政治结构。例如，尽管西班牙国王任命西班牙精英担任总督，对曾经的印加帝国实施军政统治，但印加的道路, 和通讯网络系统, 便利了西班牙的统治。

值得注意的是，*#西班牙此前从未管理过像印加帝国这样跨度近三千英里的帝国，因此他们对如何维持其运作, 或提供支持, 几乎一无所知。#*

*尽管西班牙帝国最初依赖暴力，但维持统治需要与"被征服人民"进行实际互动，在很多情况下, 甚至需要他们的合作。* (如同中国历史上, 北方少数民族统治中原, 就必须获得中原汉人的帮助)

**西班牙从帝国中获得的回报惊人。**由于掠夺了用贵金属制成的艺术品和宗教器物，**发现了矿山，**以及利用美洲原住民和其他人经营矿山的专业知识，*到16世纪中叶，金银大量涌入西班牙。这个曾经贫穷的王国变得极为富有。*

现在人们认为，前哥伦布时期的美洲人, 已懂得使用液态汞提炼金银——这种方法沿用至今，也被西班牙人采用。到16世纪末，葡萄牙人在巴西也发现了贵金属。

葡萄牙人砍伐巴西森林中的树木，用于贸易巴西红木。1515年始于牙买加的制糖业, 在加勒比地区蓬勃发展，并最终蔓延到新大陆的热带和森林地区，那里的大片树木可被砍伐, 用于提供制糖所需的燃料。

为启动和维持采矿、冶金、制糖、伐木等所有这些产业，伊比利亚人最初利用当地人的强迫劳动和专业知识。*#西班牙政府向其士兵和冒险家授予“委托监护权”（encomienda），即在大片土地上征用当地人劳动。#*

**但欧洲人中也有对这一制度的批评者，最著名的当属巴托洛梅·德·拉斯·卡萨斯。**这位天主教传教士, 曾参与对古巴的野蛮征服，并因功获得一份“委托监护权”。但一位多明我会修士的布道, 让他对征服有了新的认识，他开始为当地人奔走疾呼。

拉斯·卡萨斯在强"调皈依基督教"益处的同时，痛斥同行征服者的屠杀、暴行和掠夺。他写道，对美洲原住民“先用战争手段征服，这违背了耶稣基督律法的形式与温和……”

*拉斯·卡萨斯撰写了大量著作，并向西班牙宫廷游说（有人说他是在骚扰宫廷），在一些历史学家看来，他开启了后来被称为“人权运动”的先河。*

拉斯·卡萨斯的故事提醒我们，**人权事业, 总是需要"拥有权利的人"来推动。**但归根结底，推动人权扩展的, 是那些"被剥夺权利, 却仍坚持自身人性"的人。

暂时转换视角：一些欧洲人在倡导人权，但更多没有人权的人, 也在为自身权利呐喊。至于新大陆的原住民，单一地描述他们对殖民的反应, 是不准确的——有时，社区和个人会抵抗欧洲殖民者；有时，一些人会选择与欧洲殖民者合作。

但这些社区失去90%人口的破坏性, 无论如何强调都不为过。

其中一个重大变化, 是基督教的传入, 及要求殖民者皈依基督教。*基督教改变了美洲，但美洲也改变了基督教。*

面对"教会要求被征服者成为天主教徒"的压力，**他们可能会将自己的信仰, 与天主教信仰融合。**1531年，阿兹特克人"夸乌特拉图阿津"（洗礼名胡安·迭戈）在墨西哥城附近, 阿兹特克玉米女神的圣地, 五次见到圣母玛利亚显灵。

圣母的奇迹, 在胡安·迭戈的斗篷上留下了她的形象。*在斗篷上，圣母看起来像一位身着带有阿兹特克图案和符号长袍的阿兹特克女性。这个版本的圣母, 被称为"瓜达卢佩圣母"，她肤色棕褐，常被称为“深色圣母”。*

许多瓜达卢佩圣母的 shrine 得以建造，她的故事, 被用西班牙语和阿兹特克语（纳瓦特尔语）记录下来。瓜达卢佩圣母取代了一些被基督徒压制的当地女神。女性尤其将对她的崇拜, 视为母性的象征。如今，墨西哥城的瓜达卢佩圣母大教堂, 据说是世界上参观人数最多的圣地。

**#不久之后，其他觊觎这些财富的欧洲列强, 开始试图直接掠夺西班牙的财富。#**例如，**英国私掠船船长弗朗西斯·德雷克, 在16世纪60年代开始了袭击西班牙船只的职业生涯，**并经常为女王和航行投资者,  攫取巨额财富。

在环球航行中，**他从南美西海岸的船只上, 掠夺了大量西班牙金银。**有时，一次掠夺的财富, 就相当于英国王室一年的收入。**你没听错——击沉一艘西班牙船的收益, 可能等于英国全年的税收总和，这让你明白从殖民地榨取的财富有多少。**难怪伊丽莎白在德雷克完成历史性环球航行（当时欧洲历史上第二次环球航行）返回后，于1581年授予他爵士头衔。

德雷克活着回来了。麦哲伦——斯坦，我能开个关于麦哲伦去世的玩笑吗？时间够久了吗？斯坦说“可以”。好的。

*#因此，法国人、荷兰人和其他渴望财富的人, 加入了英国人的大西洋海盗行列，这当然增加了许多欧洲王国和个人的财富。但这些欧洲国家也开始效仿葡萄牙和西班牙，进行全球探险、贸易，并最终建立殖民地。#*

1497年，意大利水手约翰·卡博特（顺便说一句，这不是他的意大利名字。我一直觉得历史上两位最著名的意大利水手, 分别叫约翰·卡博特, 和克里斯托弗·哥伦布, 很有趣）受英国亨利七世委托，在缅因州北部某处登陆（可能是加拿大海岸），并载誉返回伦敦。

*##英国于1600年成立"东印度公司"，专注于探险；##荷兰于1602年成立类似的"联合东印度公司"，将荷兰各州的几家贸易公司合并。其他国家的政府, 也特许成立了类似的公司。*

*##这些公司履行多种职能，从聚集投资者、建造船只, 到招募军队、占领新领土、奴役人口在征服土地上劳作。##* 别以为企业的“邪恶”是现代才有的。

**这就引出了奴隶贸易。**最初，葡萄牙水手试图捕捉在海岸偶然发现的非洲人，然后作为奴隶卖到欧洲。但到16世纪末，"捕捉非洲人卖给欧洲人"已成为常规操作，1650年后，这对非洲奴隶贩子和欧洲人来说, 最终变成了大规模产业。

*这也部分归因于疾病和殖民破坏。#西班牙在加勒比地区的泰诺人, 因疾病灭绝后，难以维持制糖业；英国人随后接管，开始进口非洲奴隶, 在甘蔗种植园劳作。#*

到18世纪，英国奴隶贩子, 在大西洋贸易中占据主导地位。部分由于拉斯·卡萨斯等人的请愿，*#西班牙裁定"美洲原住民不得被奴役"，这导致西班牙地主和矿主为遵守法律（当时法律尚未禁止奴役人口）, 而进口非洲和亚洲奴隶。#*

一些亚洲奴隶被带入西班牙帝国后，能够冒充当地人, 并以此为由争取自由。但**几乎所有被奴役的人, 都在奴役中死去。预期寿命极低，各种虐待普遍存在，法律保护几乎不存在。**

考虑这些视角也非常重要，同时也要思考, 为什么这些视角传统上被忽视。

我们曾讨论过，*跨洋航行的建立, 意味着疾病、人口、制成品跨洋流动，植物和动物物种也如此。这一整个过程有时被称为“哥伦布大交换”。*

跨大西洋的商品、人口和物种流动, 对历史极为重要——在此之前，南瓜、西红柿、玉米、土豆等新大陆食物, 在亚非欧大陆甚至不存在。

地球打开了吗？世界中心有什么？是一颗南瓜。*你知道为什么13世纪的欧洲没有南瓜灯吗？因为那时没有南瓜。也没有爆米花，因为没有玉米。*#赞助（可惜不是真的）。我喜欢这些知识。

你知道南美洲著名的香蕉吗？不，你不知道。*香蕉来自非洲，哥伦布大交换前美洲没有香蕉。*

许多我们认为是文化和历史中自然甚至决定性的元素，实际上非常非常“新”。*尼日利亚的木薯、爱尔兰的土豆、欧洲的香草冰淇淋、意大利的西红柿，这些在哥伦布大交换前都无法想象。*

欧洲人也从美洲学到了许多食物保存方法。例如，印加人将土豆晒干，使其更轻便易运输，之后再泡发食用，这种方法, 为印加广阔道路网络上的信使, 提供了能量。

类似的方法后来在欧洲被采用，并最终用于为宇航员提供能量——宇航员常食用泡发的脱水食品。随着时间推移，*土豆和玉米（此处称为“玉米”）增加了欧洲的整体热量供应，因为它们可以晒干并大量储存。这减少了饥饿，促进了人口增长。*

与此同时，如我们所述，微生物传入美洲, 摧毁了当地社区，而一系列"亚非欧"动物（如马、羊、猪等）, 首次抵达新大陆。

当然，这些新动物在某些方面有用，但也造成了广泛破坏，它们啃食土壤保持所需的植被，践踏农田。正如我们之前讨论的，为种植甘蔗而砍伐森林的行为, 引发了森林砍伐，这一过程在中南美洲一直持续到20世纪。

在欧洲，糖最初是如此珍贵的奢侈品，即使是富人也只能负担得起一小撮。西班牙的伊莎贝拉女王, 曾将一小盒糖作为圣诞礼物送给女儿，视若珍宝。

巧克力最初像在阿兹特克一样，是权贵的仪式性饮品。但随着欧洲社会变得更加富裕，更多人从勉强糊口, 转向能够负担远方商品。

糖、巧克力、茶、咖啡和烟草等消费品, 改变了人们的生活态度，而泡茶、咖啡和热可可所需的热水, 被认为通过杀死水中的病菌, 延长了欧洲人的寿命。

*慢慢地，英国和西班牙、葡萄牙的其他竞争对手, 建立了自己的殖民地* ——英国在16世纪80年代有过失败的"罗阿诺克"殖民地，然后是1607年的詹姆斯敦, 和1620年的马萨诸塞湾殖民地。

这些定居者中有些是举家迁徙，但许多是单身男子，偶尔也有单身女性。在这些竞争对手展开的宣传战中，大西洋世界的**英国, 后来者推广了一种被称为“黑色传奇”的理念。**

*该理念声称，与宽容善良的英国新教徒不同，西班牙人是偏执的天主教徒，对当地人残忍且具破坏性。这在心理学上被称为“投射”。*

*如今我们知道，英国定居者肆意屠杀当地人——甚至包括那些他们赖以生存的人，因为许多冒险家不懂农耕。此外，大多数英国定居者, 和那个时代的其他欧洲人一样偏执。*

但“黑色传奇”在历史上长期占据强势地位——事实上，*我在佛罗里达长大时，曾被告知"佛罗里达曾是西班牙殖民地"是不幸的，因为英国统治者更仁慈。*

因此，*到17世纪末，对贸易和帝国的狂热达到高潮。基于新大陆烟草的种植园在北美建立，制糖厂在加勒比和南美兴起。*

**采矿和许多其他有利可图的产业，以及可开发土地的诱惑，使大西洋和太平洋上挤满了航海者。**与此同时，被殖民者统治的大多数原住民, 目睹自己劳动的大部分价值被输出。

**#这是我们今天所经历的"真正全球化"的开端，#**充满了矛盾与复杂性。我们生活在一个物质极大丰富的世界，一小撮糖通常不再被视为珍贵的圣诞礼物。

饥饿和儿童死亡率, 比以往任何时候都更罕见。但**#我们也生活在一个存在深刻不平等和不公正的世界，强者拥有弱者所没有的法律和社会保护。#**

重要的是要记住，从所有这些意义上讲，*我们是历史的产物——但当然，我们也在创造历史。*

感谢观看，下周见。

[i] Bernal Dias，引用自Jackson J. Spielvogel所著《西方文明》第7版（贝尔蒙特，加利福尼亚州：汤姆森·沃兹沃斯出版社，2009年）第419页。 +
[ii] Bartolomé Las Casas，《三十项极具法律性的主张》（1552年），引用自Bonnie G. Smith编辑的《现代帝国：读本》（纽约：牛津大学出版社，2018年）第64-67页。

'''

== pure

Hi, I’m John Green, and this is Crash Course European History.
So today we’re going to continue looking at European expansion and its impact on the world’s humans. Like, imagine learning that there are people in places you did not know existed, that they eat foods you’ve never seen, that their world contains plant and animal species entirely different from your world.

What people thought was one world turned out to be two, and the collision of those worlds wrought devastation and opportunity on a truly mind-boggling scale. And today, we’re going to ask you to look at the consequences of European expansion, and consider how those consequences change depending on where you find yourself.

Destruction from Iberian expansion was truly extraordinary across the sixteenth century. As Hernan Cortes commented: “We could not walk without treading on the bodies and heads of dead Indians.”[i]

Besides the slaughter of empire-building directly inflicted by the invaders and their local allies, the ongoing progress of smallpox, and measles, and other diseases that Europeans brought to the Americas completely overwhelmed the healthcare systems of native Americans. Many millions died. Within a century, the population of native Americans had fallen perhaps by as much as 90%.

Throughout the Spanish Empire in the Americas, the colonizers made use of existing political structures that were already in place for collecting taxes and otherwise maintaining order. Even as the Spanish king appointed elite men from Spain as viceroys enforcing civil and military rule over what had been the Incan Empire, for instance, the Incan systems of roads and communication networks facilitated Spanish domination.

It’s also important to remember that because the Spanish had never before experienced almost three-thousand-mile-long imperial operation, like the one the Incans had, the Spanish had very little understanding of how to maintain its functions or to provide for its upkeep.

Much as the Spanish empire initially depended on brute force, sustaining it required practical interactions with conquered people and in many cases their cooperation.

The rewards of empire for the Spanish were truly astonishing. Thanks to the seizure of art and religious objects made with precious metals, the discovery of mines, and the know-how of native Americans and others in running those mines, by the mid-sixteenth century silver and gold were pouring into Spain. And what had been a very poor kingdom became a very, very rich one.

It’s now believed that pre-Columbian peoples knew how to use liquid mercury to process silver and gold -- a method that’s still used today. It was also used by the Spanish. And by the end of the century, the Portuguese had discovered precious metals in Brazil, too.

The Portuguese cut down trees in Brazilian forests to trade in Brazilwood. And sugar production flourished across the Caribbean beginning in Jamaica in 1515 and eventually spreading across tropical and forested regions of the New World, where the vast tracts of trees could be felled to feed the fires needed for sugar refining.

To launch and sustain all these enterprises -- mining, metallurgy, sugar refining, lumbering -- Iberians initially used the forced labor and know-how of local peoples, as I mentioned earlier. The Spanish government awarded its soldiers and adventurers encomienda, that is the labor of local people on a large plot of land.

But there were critics of this system among Europeans, perhaps most notably Bartolomé Las Casas, a Catholic missionary who had helped in the savage conquest of Cuba and who had received an encomienda for his participation. But then the preaching of a Dominican friar made him see conquest in a different light, and he began a campaign on behalf of local people.

Las Casas, while underscoring the benefits of conversion to Christianity, lambasted his fellow conquerors for their murder, brutality, and pillage. He wrote of native Americans, “To subject them first by warlike means is a form and procedure contrary to the law … and gentleness of Jesus Christ.”

Las Casas wrote much more and lobbied the Spanish court (some would say he harassed it), beginning in some historians’ minds the drive for what are considered today human rights.

Las Casas’ story is a reminder that the cause of human rights always needs people who have them in order to press it forward. But ultimately the people who are responsible for expansions in human rights are the people who are denied them and insist upon their humanity anyway.

So to shift perspectives for a moment, some Europeans were advocating for human rights, but many, many people without those rights were advocating for them. And as for indigenous people in the New World, to present one story of their response to colonization would be inaccurate -- at times, communities and individuals resisted; at times, some cooperated.

But it’s hard to overstate how destabilizing it was to these communities to lose, in many cases, 90% of their population.

One of the huge changes, though, was the arrival of Christianity and the demand that the colonized become Christians. Christianity changed the Americas, but the Americas also changed Christianity.

In the face of the demand of the Church that conquered people become Catholic, they might, for instance, blend their own beliefs with Catholic ones. In 1531, the Aztec Cuauhtlatoatzin, whose baptismal name was Juan Diego, had five visions of the Virgin Mary on a sacred Aztec spot of the corn goddess, near Mexico City.

Mary’s miracles left an imprint of her form on Juan Diego’s cape. And on the cape, Mary appeared to be an Aztec woman wearing a robe with Aztec designs and symbols. This version of Mary, known as Our Lady of Guadalupe, was brown-skinned and was often called “the dark virgin.”

Many shrines to Our Lady of Guadalupe were built, and her story was written down both in Spanish and in the Aztec language, Nahuatl. Our Lady of Guadalupe replaced some of the local goddesses that were suppressed by the Christians. Women in particular took up devotion to her as a symbol of motherhood. And today, Our Lady of Guadalupe’s basilica in Mexico City is said to be the most visited shrine in the world.

It wasn’t too long before other European powers, eyeing these profits, sought to literally capture Spanish wealth. Like English privateer Francis Drake began his career of attacking Spanish shipping in the 1560s and often seized huge fortunes for the queen and investors in his voyages.

While circumnavigating the globe, he captured stores of Spanish gold and silver from ships along the west coast of South America. In some cases, a single seizure might yield the equivalent of an entire year’s income for the royal treasury.

You heard that right -- taking down one Spanish ship could equal all the tax collection in England for a year -- which gives you a sense of just how much wealth was being extracted from colonies. No wonder Elizabeth knighted Drake in 1581 after he returned from his historic circumnavigation -- which was only the second circumnavigation of the globe in European history at the time.

And Drake made it home. Magellan -- Stan, am I allowed to make a joke about Magellan dying? Has enough time passed? Stan says “yes.” Right.

So the French, Dutch, and other treasure-hungry people joined the English in Atlantic piracy, which increased the wealth of many European kingdoms and individuals, of course. But those same European states also began imitating the Portuguese and Spanish in global exploration, trade, and eventually settlement.

In 1497, Italian sailor John Cabot, which was not his Italian name by the way. I’ve always found it very funny that the two most famous Italian sailors in history are named John Cabot and Christopher Columbus.

At any rate, John Cabot, commissioned by Henry VII of England, landed somewhere north of Maine, probably on the Canadian coast, and then returned to London to great acclaim.

The English established the East India Company in 1600 to focus on their exploration efforts, and the Dutch founded a similar United East India Company in 1602, which brought together several trading companies from various Dutch states. And other governments chartered similar corporations.

These companies performed a variety of functions, from gathering investors and building ships to raising armies and taking over new territory and enslaving people to work conquered land. Lest you think that corporations are newly evil.

Which brings us to the slave trade. Initially, Portuguese sailors sought to catch Africans they happened to spot along the coast and then sell them as slaves in Europe. But by the end of the sixteenth century, the capture of Africans for sale to Europeans became routine and then eventually a massive business for both African slave traders and Europeans after 1650.

And this was also partly due to disease and the devastation of colonization. The Spanish had trouble with sugar production in the Caribbean after the native Taino people had been wiped out by disease; the British then took over and began importing African slaves to work in sugar plantations.

By the eighteenth century, British slavers had taken the lead in the Atlantic trade. Partly due to petitions like those from Las Casas, Spanish rulings that Native Americans could not be enslaved led the Spanish landowners and mine operators to import Africans and Asians to stay within the law, which did not yet say that people could not be enslaved.

Some Asian slaves, once brought to the Spanish Empire, were able to pass as local people and claim their freedom on that basis. But almost everyone who was enslaved died in slavery. Life expectancy was very low; all manner of mistreatment was common; and legal protections were almost nonexistent.

It’s very important to consider those perspectives too. And also to consider why, traditionally, those perspectives have been ignored.

We’ve talked about how the establishment of transoceanic travel meant that diseases, and people, and finished goods were traveling across oceans, but so were plants and animal species. This whole process is sometimes known as the Columbian exchange.

This movement of goods and people and species across the Atlantic was tremendously important to history -- before it, New World foods like pumpkins and tomatoes, maize, potatoes did not even exist in Afroeurasia.

Did the globe open up? What’s in the center of the world? It’s a pumpkin. You want to know why there were no jack-o’-lanterns in 13th-century Europe? There were no pumpkins. There was no popcorn because there was no corn. #sponsored. I wish. I love this stuff.

You know the famous bananas of South America? No, you don’t. Bananas are from Africa. They didn’t exist in the Americas until the Columbian exchange.

So much of what feels natural and even defining about our cultures and histories is in fact really, really new. Nigerian cassava. Irish potatoes. Vanilla ice cream in Europe. Tomatoes in Italy. None of this was conceivable before the Columbian exchange.

Europeans also learned a lot from the Americas about food preservation. Like the Incas dried some potatoes, for instance, which made them lighter and easier to transport, and then would later reconstitute them so they could be eaten, a strategy which fortified messengers along the Inca’s extensive network of roads.

Similar processes came to be used in Europe and would eventually be used to fortify astronauts, who often eat reconstituted dehydrated food. And over time, potatoes and maize (known here as corn) increased overall calories available to Europeans because they could be dried and stored in huge quantities. And that decreased starvation and increased populations.

Meanwhile, as we’ve discussed, the travel of microbes to the Americas devastated communities there, and a range of Afroeurasian animals -- horses, sheep, and pigs, to name a few -- arrived in the New World for the first time.

In some ways, these new animals were useful, of course, but they also did extensive damage, stripping away vegetation necessary for soil conservation and trampling farmland. And deforestation began with the clearing of forests for sugar cane production, as we discussed earlier, a process that accelerated in Central and South Americas through the twentieth century.

In Europe, sugar was initially such a precious luxury that a sprinkle of it was all that even the wealthy could afford. Queen Isabella of Castile and Spain gave a small box of sugar to her daughter as a Christmas present to be treasured.

Chocolate began as a ceremonial drink for the powerful, as it was among the Aztecs. But as European communities became wealthier, more people transitioned from subsistence living to being able to afford goods from distant places.

Treats of sugar, chocolate, tea, coffee, and tobacco transformed attitudes, while the hot water that was needed for making tea and coffee and hot cocoa is thought to have extended the lifespans in Europe by killing water-borne germs.

And slowly the English and some of Spain and Portugal’s other competitors established their own colonies -- the English had the unsuccessful colony of Roanoke in the 1580s, and then Jamestown in 1607, and the Massachusetts Bay Colony in 1620.

Some of these settlers came in families, but many came as single men and occasionally single women. And in the developing propaganda war among these rivals, English latecomers to the Atlantic world promoted an idea that came to be called the “Black Legend.”

It maintained that, unlike the tolerant and kind English Protestants, the Spanish were bigoted Catholics, brutal and destructive of local people. That would be what psychologists call “projection.”

Today we know that English settlers slaughtered local peoples with abandon -- even people on whom their own survival depended, because many adventurers had no knowledge of farming. Moreover, most English settlers were as bigoted as other Europeans in those days.

But the “Black Legend” was a really powerful idea in history for a long time -- in fact, when I was a kid growing up in Florida, I was told that it was unfortunate Florida had been a Spanish colony, because the English were much kinder rulers.

So by the end of the seventeenth century, the rush for trade and empire was in full swing. Plantations based on New World tobacco had been set up in North America and sugar mills in the Caribbean and South America.

Mining and many other lucrative enterprises, as well as the promise of exploitable land, kept the Atlantic and Pacific Oceans crowded with voyagers. All the while, most native people ruled by colonizers saw the vast majority of their labor’s value exported.

It was the beginning of the true globalization we experience today, complete with all of its contradictions and complexities. We live in a world today of tremendous abundance, where a pinch of sugar is not generally seen as a great Christmas present.

Starvation and child mortality are more rare than they have ever been. But we also live in a world with profound inequality and injustice, where the powerful have legal and social protections that the weak do not.

It’s important to remember that in all those senses, we are the products of history -- but of course we are also producing history.

Thanks for watching. I’ll see you next time.

[i] Bernal Dias, quoted in Jackson J. Spielvogel, Western Civilization, 7th ed. (Belmont, CA: Thomson Wadsworth, 2009) 419.
[ii] Bartolomé Las Casas, “Thirty Very Juridical Propositions” (1552) quoted in Bonnie G. Smith, ed., Modern Empires: A Reader (New York: Oxford University Press, 2018) 64-67.

'''