
= 009 - Commerce, Agriculture, and Slavery
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义


Hi, I'm John Green, and this is Crash Course European History.
So, last time, we were focusing on queens and kings and rivalries 竞争；对抗. Today we're gonna take a break from struggles over religion and political disputes 争论 that made for so much violence and look instead at some basics of everyday life — the foods people ate centuries ago, the kinds of things people bought and sold, and changes in the kinds of lives people could hope to live.

I know developments in agriculture 农业 and commerce 商业 may seem like sidelines 副业；补充 to the main political show — I mean, there's a reason it's called *Game of Thrones* and not like, *Game of Slightly Improved Seed Quality* — but I'd argue that history is about how people lived, and what we might learn from their lives.

And if you think about our lives today, our leaders are important. Our forms of government are important. But as Miroslav Volf said, "Politics touches everything, but politics isn't everything." On a day-to-day basis, our lives are also shaped by the kinds of goods and services available to us, and our professional and personal opportunities. Whether you go to school, whether you get enough to eat, the kinds of freedom you do and do not enjoy... those are the big questions we're exploring today.

The citizens of many European nations today have long life expectancies, and a top standard of living. Europe also comprises 组成 the largest developed economic marketplace and a major region of trade. But in 1500, that was hardly the case.

In the early fourteenth century a major famine 饥荒 erupted 爆发, with further famines across the centuries. We've talked about the Black Death. Trade was local and regulated by guilds 行会 — that is, by organizations of individual artisans 工匠 and traders that determined the number and type of goods that could be produced and marketed.

In the late middle ages Europe was a subsistence economy 自给自足经济, with little if any agricultural surplus 剩余. If princes could satisfy their appetite for food and drink on a regular and reliable basis, they were virtually alone in experiencing a consistently happy and full stomach.

In 1500, Europe was not exceptional in life expectancy or in many other measures of well-being. But in the early modern period, roughly between 1500 and 1750 the situation gradually improved. And I know that seems impossible, given all the religious strife 冲突, and wars, and massacres 大屠杀 we've discussed in this series so far.

But during this period, population actually rose; In Britain, for instance, the population almost doubled between 1700 and 1800. Historians attribute 把…归因于 this rise to developments in agriculture, sometimes called an agricultural revolution that unfolded 展开 alongside all that warfare.

And there was also a growth in commerce, often called a commercial revolution, and of course, the Columbian exchange, which made new nutritious 有营养的 foods — from potatoes to corn — available to Europeans.

But the agricultural revolution was also driven by innovation 创新 that dramatically boosted agricultural yields 产量 in Europe between 1500 and 1800.

Let's go to the Thought Bubble.

For starters, it was discovered that planting certain crops, like turnip 芜菁 and clover 三叶草, could replenish 补充 soil, which was one example of crop rotation 轮作 — farmers would plant one crop in a field one year, and then another the next year, rotating 2 or at times three crops to add nutrients 营养物 to the soil.

And the great thing about crop rotation is that it decreased the amount of farmland that needed to remain fallow 休耕的 each year — that is, unplanted.

Secondly, with the Dutch pioneering 开创 some advances, land reclamation 土地开垦 occurred across Europe. This entailed 牵涉 converting marshes 沼泽 and other previously unusable land into farmland.

And Third, common lands were enclosed 圈占. Enclosure 圈地运动 occurred when wealthier farmers bought up or simply took common land (land that had been open to community use). Private farms were able to innovate faster than communities, which required consensus 共识 in group decision-making.

And fourth, there were new inventions such as the seed drill 条播机 and a plow 犁 that could be drawn by two instead of six or eight farm animals. The new plow cut down on expenses and the seed drill made planting more accurate with less wasted seed.

Both of these new tools, by the way, copied Chinese inventions.

But while enclosure and more mechanized 机械化的 farming practices did mean more overall food, and therefore more overall wealth, not everyone benefited, because a decrease in common land meant that fewer people had direct access to land for their own use.

Thanks, Thought Bubble.

So one example of all these innovations can be seen in the life of Elizabeth, Countess of Sutherland, who inherited 继承 some 800,000 acres in Scotland. Stan, hold on a second. Is that a trout 鳟鱼 in her hair? Is it a feather? Was there some kind of hair fish trend at the time?

Let's move on from lighthearted hair fish jokes and talk about people being wrested 抢夺 from their land. So, Elizabeth removed hundreds of tenants 佃户 from her estate 庄园, then created unified acreage 土地 for farming and raising sheep with the help of day laborers 日工.

These landless workers were cheaper, and also unlike the tenant farmers who had lived on the land previously, day laborers did not have longstanding claims to inhabit 居住 and work the land, called "tenancy 租赁权".

The Countess was known for chasing villagers away from their land with her own hands, and also for innovations that increased productivity 生产力 even as Sutherland's former tenants became homeless.

So more overall food, but on land controlled by fewer people. So obviously, this Agricultural Revolution entailed massive social dislocation 混乱 that included the rise of poverty, migration 迁移 of disenfranchised 被剥夺权利的 farmworkers to cities and also to other continents, and even as overall agricultural production rose, some among the poor starved.

And this period of European history is still widely debated in part because ideas of private property and inequality 不平等 of wealth remain resonant 引起共鸣的 today, but whether this modernization helped or hurt humanity again depends on your perspective.

To some, it was fatal. To many, it meant trauma 创伤 and impoverishment 贫困 as people were removed from lands their families had farmed for generations. But these changes also helped fuel greater overall food production, population growth, larger cities, and more space for all kinds of specialized labor 专门劳动, from shoemaking to theater.

I mean, it's no coincidence that Shakespeare and Marlowe were writing as English agricultural production started to increase.

Another ingredient 因素 in the rising population and overall output of food was the inflow 流入 of novel 新奇的 plants from the Americas and other parts of the world. Potatoes and maize 玉米, for example, were grown on the marginal land 边缘土地 that was previously seen as unfit for agriculture.

Farmers started experimenting with all the new crops, but especially with maize and potatoes that could produce super-abundant... did the world just open? Is there a potato in the center?

There's a lot of candidates for most important plant of the last 500 years, but I'm gonna say it's the potato. They contain lots of carbohydrates 碳水化合物, and whatever micronutrients 微量营养素 are. You can turn them into both French fries and tater tots, the world's two most important foods.

But most importantly, you don't need great soil to have great potatoes. Just ask Idaho!

In addition to the transfer of crops, knowledge about agriculture was transferred from Africa and the Americas to Europe. Women in both the Americas and Africa had made their regions food-rich, as European traders and invaders testified 证实, and their knowledge of crops and irrigation 灌溉 techniques allowed, for instance, rice to be grown in much larger quantities in European colonies.

Much of what Europeans learned about agriculture from Africans came from enslaved 被奴役的 women agriculturalists. Slavery has existed for millennia 千年, but slaves have experienced very different lives depending on culture, and religion, and occupation, and gender.

Before 1650, the Atlantic slave ships took an annual total of 7,500 Africans to the Western Hemisphere — and that number was comparable to other slave routes, such as the one in South Asia or the Ottoman Empire. The vast majority went to Mexico and South America.

European ships transported other slaves from the Indian Ocean across the Pacific, many of them to Mexico. But, beginning in the late seventeenth century, there was a massive upsurge 高涨 in African slavery that sought to replace the labor of the native American populations that had been utterly devastated 摧毁 by disease and warfare.

In particular, slave labor was used to fill the world's increasing demand for commodities 商品 and consumer goods. Europeans came to depend on sugar, and tobacco, and coffee, and tea — all of which was produced primarily via forced labor.

And racism 种族主义 developed alongside the growth of the African slave trade. At first, Europeans were in awe of African wealth in the fifteenth and sixteenth centuries, as it motivated their first contacts.

They craved 渴望 African gold and found African men and women stately — "intelligent and rich," as one Portuguese trader wrote. However, greed for profit took over and as the indigenous 本土的 Amerindian population declined, the desire for slaves grew, and to justify 为…辩解 slavery, European descriptions of Africans became contemptuous 轻蔑的 and dehumanizing 非人性化的.

As dehumanization 非人化 progressed, Europeans treated Africans as morally and intellectually inferior 低等的, and used those incorrect constructions to justify their horrendous 可怕的 treatment of Africans, packing them into slave ships and subjecting them to the lethal 致命的 middle passage across the Atlantic.

African kings and independent African traders fed the rising demand for slaves. In those days of state consolidation 巩固 African rulers sought funds for weaponry 武器, which Europeans provided in exchange for slaves.

More advanced weaponry then allowed leaders to capture additional people to sell to European slavers for yet more weapons. European slavers mostly operated along the West African coast, while Arabs took slaves from East Africa to sell to India or into the Middle Eastern markets.

The Saharan slave trade went northward, transporting many women slaves to serve as domestics 佣人 and as sex workers. But the European slave was by far the largest, and the dehumanizing racism that has endured to this day.

In the eighteenth century, one million slaves worked in the sugar industry and diamond and gold mines of Brazil. These industries were tremendously lucrative 利润丰厚的, and in that sense, slavery both produced and was a product of growing European wealth.

The conditions of slavery were truly dire 悲惨的: Torture, beatings, overwork, and malnutrition 营养不良 were routine. And because the system itself did not treat them as humans, enslaved people had very little recourse 求助的方法, and there was always the knowledge that you could be separated from your children, from your family, at any time, because you were treated legally and practically as property.

The slave trade itself was part of a web of interactions that is still being understood. Historians used to talk of the triangle trade 三角贸易: shippers took small iron goods from Britain to Africa, trading them for slaves; and then shippers dropped off the slaves who survived the passage in Brazil or the Caribbean, and then filled their holds with local sugar or molasses 糖蜜 to take back to England.

But while there was a triangle, there were also many other shapes. West African rulers and consumers wanted cowrie shells 贝壳 and Indian textiles 纺织品 as payment for slaves. These products took a much more circuitous 迂回的 route than a simple triangle.

Cowrie shells, for example, were picked up from merchants along the Pacific Ocean or South Asian coasts, then "cured" and processed in Sri Lanka, then shipped again. With slaves coming to the New World across the Pacific and commodities to pay for them flowing in multiple directions, the slave trade into the Americas was part of a global, not just triangular, market.

In fact, multidirectional 多向的 trade in many goods increased in diversity and quantity. In the seventeenth century literally millions of pieces of porcelain 瓷器 went in Portuguese ships to Dutch and other European ports.

And to get funds to buy that porcelain, European shippers did a lot of local coastline shipping, stopping at ports around the Indian Ocean or at Chinese depots 仓库 in the Philippines. European consumers snapped up 抢购 goods and merchants grew wealthy.

The increase in consumption 消费 was truly unprecedented 前所未有的: For example, in 1660 the East India Company imported 23 pounds of tea to Britain; in 1750 it imported five million pounds.

Besides slavery and colonization 殖民化, innovation was also an important facilitator 促进因素 of economic growth. And I don't just mean innovation in terms of actual things, I also mean innovation in terms of ideas... like corporations 公司!

The East India companies such as those founded in Britain, the Netherlands, and France focused each kingdom's international trade and raised funds for investment. Joint stock companies 股份公司 arose to finance merchant ships.

The development of double entry bookkeeping 复式记账法 gave merchants and bankers a better idea of inflows 流入 and expenditures 支出. However, there wouldn't be laws limiting liability 责任 of such companies until much later. So, a ship lost at sea could still mean the investors' loss of homes and possessions.

Whereas now, when investors do things that lose money, we just give them their money back.

And talking of bankers brings us to the Fuggers, or Fuggers. The Fugger family of bankers, who once loaned money to monarchs such as Charles V and Philip II of Spain, who then spent everything on defeating Protestants, the monarchy's bankruptcy 破产 made the bankers penniless too.

This whirl 混乱 of commerce disrupted 扰乱 society by producing new values and creating new groups of wealthy, influential people. Almost everywhere in Europe, people who weren't aristocrats 贵族 became rich from global expansion of trade.

Many of the aristocrats also became richer, of course, but the wealth of new groups of people upset long-held notions about the importance of family lineage 血统. And capitalism 资本主义 — that is, the private ownership of enterprises 企业 — changed everyday values and turned activities toward making profit above all else.

Capitalism created a new class of wealthy traders and merchants, who competed for political influence with those from hereditary 世袭的 status groups such as the nobility.

We'll hear more, of course, about the twists and turns of capitalism across the centuries. But by the beginning of the eighteenth century capitalism was in a lively stage of development, thanks to the abundance 丰富 provided by the agricultural and commercial revolutions and also by the Atlantic slave trade, which wrenched 抢夺 some eleven to twelve million Africans from their homes and families.

Thanks for watching. I'll see you next time.

'''

== 中文释义


大家好，我是约翰·格林，这里是《速成欧洲史》。
上次我们聚焦于君主之间的竞争。今天我们将暂别引发诸多暴力的宗教与政治纷争，转而关注日常生活的基本面——几个世纪前人们的饮食、买卖的物品，以及人们对生活的期望所发生的变化。

我知道农业和商业的发展, 可能看似是政治主线的旁枝末节——毕竟《权力的游戏》叫这个名字，而不是《种子质量微提升游戏》——但我认为历史关乎人们如何生活，以及我们能从他们的生活中汲取什么。

想想我们今天的生活，领导者很重要，政府形式很重要。但正如米罗斯拉夫·沃尔夫所言：“*政治触及一切，但政治并非一切。*”在日常生活中，我们的生活也由可获得的商品和服务、职业与个人机会所塑造。你是否能上学、是否能吃饱、享受何种自由……这些是我们今天要探讨的核心问题。

如今许多欧洲国家的公民, 享有较长的预期寿命和最高标准的生活。欧洲还构成了最大的发达经济市场和主要贸易区域。但在1500年，情况并非如此。

14世纪初爆发了一场严重的饥荒，此后数个世纪饥荒不断。我们曾谈及黑死病。*#当时贸易以本地为主，由"行会"（guilds）监管——即由个体工匠和商人组成的组织，决定可生产和销售的商品数量及类型。#*

**中世纪晚期的欧洲, 是自给自足的经济，农业剩余极少（如果有的话）。**如果说有谁能定期、可靠地满足自己的吃喝需求，那几乎只有王公贵族能始终拥有幸福而饱腹的胃。

1500年，欧洲在预期寿命, 或其他福祉指标上, 并无特别之处。**但在近代早期（大致在1500年至1750年间），情况逐渐改善。**我知道，鉴于我们在本系列中讨论过的所有宗教冲突、战争和屠杀，这似乎不可能。

**但在此期间，人口实际增长了；**例如，英国人口在1700年至1800年间几乎翻了一番。历史学家将这一增长归因于农业发展，有时称之为与战争同步展开的“农业革命”。

**此外，商业也有所发展（常被称为“商业革命”），当然还有“哥伦布大交换”（Columbian exchange），**它为欧洲人带来了新的营养丰富的食物——从土豆到玉米。

但农业革命也由创新驱动，这些创新在1500年至1800年间, 极大地提高了欧洲的农业产量。

让我们进入“思想泡泡”环节。

首先，*人们发现种植某些作物（如芜菁和三叶草）可以补充土壤肥力，这是轮作（crop rotation）的一个例子——农民每年在一块田里种植一种作物，次年换种另一种，通过轮作两种或三种作物, 为土壤补充养分。*

*轮作的好处在于, 减少了每年需要休耕（fallow）的农田数量——即不种植作物的土地。*

其次，*在荷兰人的率先推动下，欧洲各地开展了土地开垦（land reclamation）。这包括将沼泽和其他此前无法利用的土地, 转化为农田。*

第三，*#公有土地被圈占（enclosure）。当较富裕的农民购买或直接占据公有土地（即社区共用土地）时，圈地就发生了。私人农场比需要集体决策达成共识的社区, 更能快速创新。(即发展私有化, 不吃大锅饭.)#*

第四，*出现了新发明，如条播机*（seed drill）和只需两头而非六到八头牲畜牵引的犁。*新犁降低了成本，条播机使播种更精准，减少了种子浪费。*

顺便说一句，这两种新工具都借鉴了中国发明。

但尽管圈地和更机械化的耕作方式, 意味着整体粮食增加、财富总量提升，*并非所有人都从中受益，因为公有土地减少, 意味着更少人能直接使用土地。*

感谢“思想泡泡”。

这些创新的一个例证, 可见于萨瑟兰伯爵夫人伊丽莎白（Elizabeth, Countess of Sutherland）的生活，她继承了苏格兰约80万英亩土地。斯坦，等一下，她头发里是条鳟鱼吗？还是羽毛？当时有“头发插鱼”的潮流吗？

让我们放下关于“头发插鱼”的轻松玩笑，谈谈人们被剥夺土地的问题。伊丽莎白从自己的庄园驱逐了数百名佃户，然后在日工的帮助下, 将土地整合为统一的农田和牧场。

这些无地工人成本更低，而且与此前居住在土地上的佃农不同，日工没有长期居住和耕种土地的权利（称为“租佃权”）。

伯爵夫人以"亲自驱赶村民离开土地"而闻名，她在提高生产力的同时，也让萨瑟兰的前佃户无家可归。

**因此，整体粮食增多了，但土地由更少的人控制。##显然，这场农业革命伴随着大规模的社会动荡，包括贫困加剧、被剥夺权利的农场工人向城市和其他大陆迁移，##甚至在农业总产量上升的同时，部分穷人仍在挨饿。**

*这段欧洲历史仍存在广泛争议，部分原因在于"私有财产"和"财富不平等"的观念, 在今天依然具有现实意义，但这种现代化对人类是助益还是伤害，仍取决于你的视角。*

对某些人来说，这是致命的；对许多人而言，当他们被从家族耕种了数代的土地上赶走时，这意味着创伤和贫困。*但这些变化也推动了整体粮食产量增加、人口增长、城市扩大，并为从制鞋到戏剧等各种专业劳动腾出了更多空间。(即第一产业农业, 向第二,第三产业的工业, 服务业发展.)*

莎士比亚和马洛在英国农业产量开始增加时进行创作，这并非巧合。

人口增长和粮食总产量提升的另一个因素, 是来自美洲和世界其他地区的新植物的流入。例如，*土豆和玉米, 被种植在以前被视为不适合农业的边缘土地上。*

农民开始尝试所有新作物，尤其是产量极高的玉米和土豆——世界刚刚“打开”了吗？中心有个土豆？

**过去500年最重要的植物有很多候选，但我会说是土豆。它们富含碳水化合物, 和各种微量营养素。**你可以把它们做成薯条和薯饼，这两种世界上最重要的食物。

*但最重要的是，##种植土豆不需要肥沃的土壤。##问问爱达荷州就知道了！*

除了作物的传播，农业知识也从非洲和美洲传到欧洲。正如欧洲商人和侵略者所证实的，美洲和非洲的女性曾让当地粮食丰富，她们的作物和灌溉技术知识, 使水稻能在欧洲殖民地大规模种植。

*欧洲人从非洲人那里学到的许多农业知识, 来自被奴役的女性农业劳动者。奴隶制已存在数千年，但根据文化、宗教、职业和性别不同，奴隶的生活境遇差异极大。*

*1650年前，大西洋奴隶船每年将7500名非洲人运往西半球——这一数字与其他奴隶路线（如南亚或奥斯曼帝国的路线）相当。绝大多数奴隶被运往墨西哥和南美洲。*

欧洲船只还将其他奴隶, 从印度洋跨太平洋运往墨西哥，其中许多是女性。*但从17世纪末开始，非洲奴隶贸易大规模激增，试图替代因疾病和战争而惨遭摧毁的美洲原住民劳动力。*

特别是，奴隶劳动被用来满足世界对商品和消费品日益增长的需求。*欧洲人开始依赖糖、烟草、咖啡和茶——所有这些主要通过强迫劳动生产。*

*种族主义, 随着非洲奴隶贸易的发展而滋生。起初，15至16世纪的欧洲人对非洲的财富充满敬畏，这促使他们首次接触非洲。*

*他们渴望非洲的黄金，认为非洲男女庄重威严*——正如一位葡萄牙商人所写：“聪明而富有”。然而，对利润的贪婪占据了上风，随着美洲原住民人口减少，对奴隶的需求增长，*#为了给奴隶制辩护，欧洲人对非洲人的描述变得轻蔑且非人性化。#*

*随着非人性化的加剧，#欧洲人将非洲人视为道德和智力上的劣等者，并利用这些错误的认知, 为他们对待非洲人的可怕行为辩护#*——将他们塞进奴隶船，使其遭受跨大西洋“中间航程”的致命折磨。

*非洲国王和独立的非洲商人, 满足了欧洲人对奴隶不断增长的需求。在国家巩固时期，#非洲统治者寻求资金来购买武器，欧洲人则以获得奴隶作为交换,来提供给对方武器。#*

*更先进的武器, 随后使非洲领导者能够捕获更多人口, 卖给欧洲奴隶贩子，以换取更多武器。欧洲奴隶贩子主要在"西非海岸"活动，而阿拉伯人则从东非捕获奴隶, 卖给印度或中东市场。*

撒哈拉奴隶贸易向北运输，许多女性奴隶被用作"佣人"或"性工作者"。**但欧洲主导的奴隶贸易规模最大，**其非人性化的种族主义一直延续至今。

18世纪，100万奴隶在巴西的制糖业、钻石和金矿中劳作。这些产业利润极高，从这个意义上说，奴隶制既产生了欧洲日益增长的财富，也是其产物。

奴隶的生存条件极其恶劣：酷刑、殴打、过度劳作,和营养不良是常态。*##由于该奴隶体系本身不将他们视为人，被奴役者几乎无处申诉，##而且他们始终清楚, 自己可能随时与子女、家人分离，因为从法律和实际层面看，他们被视为财产。*

奴隶贸易本身是一个仍在被解读的互动网络的一部分。历史学家曾谈及“三角贸易”（triangle trade）：船主从英国将小铁器运往非洲，交换奴隶；然后将在途中幸存的奴隶, 送到巴西或加勒比地区; 再将船舱装满当地的糖或糖蜜,运回英国。

**但除了三角贸易，还有许多其他贸易路线。**西非统治者和消费者, 希望用贝壳和印度纺织品作为购买奴隶的 payment。这些产品的运输路线, 比简单的三角贸易迂回得多。

例如，贝壳从太平洋或南亚海岸的商人处收集，然后在斯里兰卡“加工”处理，再运输。随着奴隶跨太平洋被运往新大陆，支付它们的商品向多个方向流动，美洲的奴隶贸易成为全球市场（而非仅仅三角贸易）的一部分。

事实上，许多商品的多向贸易, 在多样性和数量上都有所增加。17世纪，数百万件瓷器通过葡萄牙船只, 运往荷兰和其他欧洲港口。

为了筹集资金购买瓷器，欧洲船主进行了大量的本地沿海运输，停靠在印度洋港口或中国在菲律宾的商埠。欧洲消费者抢购商品，商人则变得富有。

消费的增长堪称空前：例如，1660年东印度公司（East India Company）向英国进口了23磅茶叶；1750年，这一数字达到500万磅。

*除了奴隶制和殖民化，创新也是经济增长的重要推动因素。我不仅指实际物品的创新，还指思想的创新……比如“公司”！*

*英国、荷兰和法国等国成立的东印度公司（East India companies）, 聚焦于各国的国际贸易，并为投资筹集资金。#股份公司（Joint stock companies）应运而生，为商船提供资金。#*

**复式簿记（double entry bookkeeping）的发展, 让商人和银行家更清楚收入和支出情况。然而，#限制此类公司责任的法律, 直到很久以后才出现。#**因此，一艘船在海上沉没, 仍可能意味着投资者失去家园和财产。

而如今，当投资者做了亏损的事，我们只是把钱还给他们。

说到银行家，就不得不提富格尔家族（Fuggers）。*富格尔家族的银行家, 曾向查理五世和西班牙菲利普二世等君主贷款，而后者将所有资金用于击败新教徒，君主的破产, 也让银行家变得一文不名。*

这种商业漩涡, 通过产生新价值观, 和创造有影响力的富裕新群体, 扰乱了社会。在欧洲几乎所有地方，*非贵族阶层的人通过全球贸易, 扩张致富(经商致富, 资本主义崛起)。*

当然，许多贵族也变得更富有，但**##新富群体的财富, 动摇了长期以来关于家族血统重要性的观念 (商人不次于做官了)。##资本主义（capitalism）——即企业私有制——改变了日常价值观，使活动转向将盈利置于首位。**

*资本主义创造了一个富有的商人和贸易者新阶层，他们与贵族等世袭地位群体, 竞争政治影响力 (钱能带来权力, 和政治影响力)。*

当然，我们将在未来更多地探讨几个世纪以来资本主义的曲折发展。但**到18世纪初，**得益于农业和商业革命, 以及大西洋奴隶贸易带来的丰富资源，*资本主义进入了活跃的发展阶段*——尽管这场贸易使1100万至1200万非洲人被迫与家园和家人分离。

感谢观看，下期再见。

'''

== pure

Hi, I'm John Green, and this is Crash Course European History.
So, last time, we were focusing on queens and kings and rivalries. Today we're gonna take a break from struggles over religion and political disputes that made for so much violence and look instead at some basics of everyday life -- the foods people ate centuries ago, the kinds of things people bought and sold, and changes in the kinds of lives people could hope to live.

I know developments in agriculture and commerce may seem like sidelines to the main political show -- I mean, there's a reason it's called Game of Thrones and not like, Game of Slightly Improved Seed Quality -- but I'd argue that history is about how people lived, and what we might learn from their lives.

And if you think about our lives today, our leaders are important. Our forms of government are important. But as Miroslav Volf said, "Politics touches everything, but politics isn't everything." On a day-to-day basis, our lives are also shaped by the kinds of goods and services available to us, and our professional and personal opportunities. Whether you go to school, whether you get enough to eat, the kinds of freedom you do and do not enjoy... those are the big questions we're exploring today.

The citizens of many European nations today have long life expectancies, and a top standard of living. Europe also comprises the largest developed economic market place and a major region of trade. But in 1500, that was hardly the case.

In the early fourteenth century a major famine erupted, with further famines across the centuries. We've talked about the Black Death. Trade was local and regulated by guilds -- that is, by organizations of individual artisans and traders that determined the number and type of goods that could be produced and marketed.

In the late middle ages Europe was a subsistence economy, with little if any agricultural surplus. If princes could satisfy their appetite for food and drink on a regular and reliable basis, they were virtually alone in experiencing a consistently happy and full stomach.

In 1500, Europe was not exceptional in life expectancy or in many other measures of well-being. But in the early modern period, roughly between 1500 and 1750 the situation gradually improved. And I know that seems impossible, given all the religious strife, and wars, and massacres we've discussed in this series so far.

But during this period, population actually rose; In Britain, for instance, the population almost doubled between 1700 and 1800. Historians attribute this rise to developments in agriculture, sometimes called an agricultural revolution that unfolded alongside all that warfare.

And there was also a growth in commerce, often called a commercial revolution, and of course, the Columbian exchange, which made new nutritious foods -- from potatoes to corn -- available to Europeans.

But the agricultural revolution was also driven by innovation that dramatically boosted agricultural yields in Europe between 1500 and 1800.

Let's go to the Thought Bubble.

For starters, it was discovered that planting certain crops, like turnip and clover, could replenish soil, which was one example of crop rotation -- farmers would plant one crop in a field one year, and then another the next year, rotating 2 or at times three crops to add nutrients to the soil.

And the great thing about crop rotation is that it decreased the amount of farmland that needed to remain fallow each year -- that is, unplanted.

Secondly, with the Dutch pioneering some advances, land reclamation occurred across Europe. This entailed converting marshes and other previously unusable land into farmland.

And Third, common lands were enclosed. Enclosure occurred when wealthier farmers bought up or simply took common land (land that had been open to community use). Private farms were able to innovate faster than communities, which required consensus in group decision-making.

And fourth, there were new inventions such as the seed drill and a plow that could be drawn by two instead of six or eight farm animals. The new plow cut down on expenses and the seed drill made planting more accurate with less wasted seed.

Both of these new tools, by the way, copied Chinese inventions.

But while enclosure and more mechanized farming practices did mean more overall food, and therefore more overall wealth, not everyone benefited, because a decrease in common land meant that fewer people had direct access to land for their own use.

Thanks, Thought Bubble.

So one example of all these innovations can be seen in the life of Elizabeth, Countess of Sutherland, who inherited some 800,000 acres in Scotland. Stan, hold on a second. Is that a trout in her hair? Is it a feather? Was there some kind of hair fish trend at the time?

Let's move on from lighthearted hair fish jokes and talk about people being wrested from their land. So, Elizabeth removed hundreds of tenants from her estate, then created unified acreage for farming and raising sheep with the help of day laborers.

These landless workers were cheaper, and also unlike the tenant farmers who had lived on the land previously, day laborers did not have longstanding claims to inhabit and work the land, called "tenancy."

The Countess was known for chasing villagers away from their land with her own hands, and also for innovations that increased productivity even as Sutherland's former tenants became homeless.

So more overall food, but on land controlled by fewer people. So obviously, this Agricultural Revolution entailed massive social dislocation that included the rise of poverty, migration of disenfranchised farmworkers to cities and also to other continents, and even as overall agricultural production rose, some among the poor starved.

And this period of European history is still widely debated in part because ideas of private property and inequality of wealth remain resonant today, but whether this modernization helped or hurt humanity again depends on your perspective.

To some, it was fatal. To many, it meant trauma and impoverishment as people were removed from lands their families had farmed for generations. But these changes also helped fuel greater overall food production, population growth, larger cities, and more space for all kinds of specialized labor, from shoemaking to theater.

I mean, it's no coincidence that Shakespeare and Marlowe were writing as English agricultural production started to increase.

Another ingredient in the rising population and overall output of food was the inflow of novel plants from the Americas and other parts of the world. Potatoes and maize, for example, were grown on the marginal land that was previously seen as unfit for agriculture.

Farmers started experimenting with all the new crops, but especially with maize and potatoes that could produce super-abundant... did the world just open? Is there a potato in the center?

There's a lot of candidates for most important plant of the last 500 years, but I'm gonna say it's the potato. They contain lots of carbohydrates, and whatever micronutrients are. You can turn them into both French fries and tater tots, the world's two most important foods.

But most importantly, you don't need great soil to have great potatoes. Just ask Idaho!

In addition to the transfer of crops, knowledge about agriculture was transferred from Africa and the Americas to Europe. Women in both the Americas and Africa had made their regions food-rich, as European traders and invaders testified, and their knowledge of crops and irrigation techniques allowed, for instance, rice to be grown in much larger quantities in European colonies.

Much of what Europeans learned about agriculture from Africans came from enslaved women agriculturalists. Slavery has existed for millennia, but slaves have experienced very different lives depending on culture, and religion, and occupation, and gender.

Before 1650, the Atlantic slave ships took an annual total of 7,500 Africans to the Western Hemisphere -- and that number was comparable to other slave routes, such as the one in South Asia or the Ottoman Empire. The vast majority went to Mexico and South America.

European ships transported other slaves from the Indian Ocean across the Pacific, many of them to Mexico. But, beginning in the late seventeenth century, there was a massive upsurge in African slavery that sought to replace the labor of the native American populations that had been utterly devastated by disease and warfare.

In particular, slave labor was used to fill the world's increasing demand for commodities and consumer goods. Europeans came to depend on sugar, and tobacco, and coffee, and tea -- all of which was produced primarily via forced labor.

And racism developed alongside the growth of the African slave trade. At first, Europeans were in awe of African wealth in the fifteenth and sixteenth centuries, as it motivated their first contacts.

They craved African gold and found African men and women stately -- "intelligent and rich," as one Portuguese trader wrote. However, greed for profit took over and as the indigenous Amerindian population declined, the desire for slaves grew, and to justify slavery, European descriptions of Africans became contemptuous and dehumanizing.

As dehumanization progressed, Europeans treated Africans as morally and intellectually inferior, and used those incorrect constructions to justify their horrendous treatment of Africans, packing them into slave ships and subjecting them to the lethal middle passage across the Atlantic.

African kings and independent African traders fed the rising demand for slaves. In those days of state consolidation African rulers sought funds for weaponry, which Europeans provided in exchange for slaves.

More advanced weaponry then allowed leaders to capture additional people to sell to European slavers for yet more weapons. European slavers mostly operated along the West African coast, while Arabs took slaves from East Africa to sell to India or into the Middle Eastern markets.

The Saharan slave trade went northward, transporting many women slaves to serve as domestics and as sex workers. But the European slave was by far the largest, and the dehumanizing racism that has endured to this day.

In the eighteenth century, one million slaves worked in the sugar industry and diamond and gold mines of Brazil. These industries were tremendously lucrative, and in that sense, slavery both produced and was a product of growing European wealth.

The conditions of slavery were truly dire: Torture, beatings, overwork, and malnutrition were routine. And because the system itself did not treat them as humans, enslaved people had very little recourse, and there was always the knowledge that you could be separated from your children, from your family, at any time, because you were treated legally and practically as property.

The slave trade itself was part of a web of interactions that is still being understood. Historians used to talk of the triangle trade: shippers took small iron goods from Britain to Africa, trading them for slaves; and then shippers dropped off the slaves who survived the passage in Brazil or the Caribbean, and then filled their holds with local sugar or molasses to take back to England.

But while there was a triangle, there were also many other shapes. West African rulers and consumers wanted cowrie shells and Indian textiles as payment for slaves. These products took a much more circuitous route than a simple triangle.

Cowrie shells, for example, were picked up from merchants along the Pacific Ocean or South Asian coasts, then "cured" and processed in Sri Lanka, then shipped again. With slaves coming to the New World across the Pacific and commodities to pay for them flowing in multiple directions, the slave trade into the Americas was part of a global, not just triangular, market.

In fact, multidirectional trade in many goods increased in diversity and quantity. In the seventeenth century literally millions of pieces of porcelain went in Portuguese ships to Dutch and other European ports.

And to get funds to buy that porcelain, European shippers did a lot of local coastline shipping, stopping at ports around the Indian Ocean or at Chinese depots in the Philippines. European consumers snapped up goods and merchants grew wealthy.

The increase in consumption was truly unprecedented: For example, in 1660 the East India Company imported 23 pounds of tea to Britain; in 1750 it imported five million pounds.

Besides slavery and colonization, innovation was also an important facilitator of economic growth. And I don't just mean innovation in terms of actual things, I also mean innovation in terms of ideas... like corporations!

The East India companies such as those founded in Britain, the Netherlands, and France focused each kingdom's international trade and raised funds for investment. Joint stock companies arose to finance merchant ships.

The development of double entry bookkeeping gave merchants and bankers a better idea of inflows and expenditures. However, there wouldn't be laws limiting liability of such companies until much later. So, a ship lost at sea could still mean the investors' loss of homes and possessions.

Whereas now, when investors do things that lose money, we just give them their money back.

And talking of bankers brings us to the Fuggers, or Fuggers. The Fugger family of bankers, who once loaned money to monarchs such as Charles V and Philip II of Spain, who then spent everything on defeating Protestants, the monarchy's bankruptcy made the bankers penniless too.

This whirl of commerce disrupted society by producing new values and creating new groups of wealthy, influential people. Almost everywhere in Europe, people who weren't aristocrats became rich from global expansion of trade.

Many of the aristocrats also became richer, of course, but the wealth of new groups of people upset long-held notions about the importance of family lineage. And capitalism -- that is, the private ownership of enterprises -- changed everyday values and turned activities toward making profit above all else.

Capitalism created a new class of wealthy traders and merchants, who competed for political influence with those from hereditary status groups such as the nobility.

We'll hear more, of course, about the twists and turns of capitalism across the centuries. But by the beginning of the eighteenth century capitalism was in a lively stage of development, thanks to the abundance provided by the agricultural and commercial revolutions and also by the Atlantic slave trade, which wrenched some eleven to twelve million Africans from their homes and families.

Thanks for watching. I'll see you next time.


'''