
= 012 - The 17th Century Crisis
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hi, I'm John Green.
This is Crash Course European History, and today we're going to look at what is sometimes called the "seventeenth century crisis" 十七世纪危机.

Now I know what you're thinking: This whole history business is just one crisis after another.

And yes, dear viewer, it's true.
Humankind careens 猛冲；歪歪斜斜地行驶 from disaster to disaster, but still we press on, like boats against the current, and sometimes we even learn from previous disasters.

And since the Seventeenth Century Crisis involves climate change and catastrophic 灾难性的 war, we should maybe pay attention to this one.

Let's begin with the Little Ice Age 小冰河期.
The Little Ice Age began in 1300, but it really escalated 加剧 beginning in 1570, and then the climate continued to cool for over one hundred years after that.
It was a global phenomenon 现象.
In some places, the temperature may have shifted two degrees Celsius or 3.6 degrees Fahrenheit, but the average was about half a degree Celsius.
That may not sound dramatic, but it was.
Intense rainfall, lack of sunshine, and lower temperatures decreased harvests or ruined them entirely.
Europeans suffered hypothermia 体温过低；低温症; the birthrate dropped; and famines 饥荒 became more common -- as did cannibalism 食人行为.
In New England, the end of the 17th century was the worst part of the Little Ice Age.
1797 was especially brutal 残酷的; Settler Samuel Sewell noted in his diary: "To Horses, Swine, Nett-Cattell, Sheep, and Deer, Ninety and Seven prov'd a Mortal yeer."
Now, unlike contemporary 当代的；同时代的 climate change, the Little Ice Age was not caused primarily by human behavior -- it may have been caused by volcanic activity or orbital cycles 轨道周期 or cyclical lows in solar radiation 太阳辐射.
We like to think of the Earth's climate as entirely stable, but it never has been.
That said, contemporary climate change IS caused by humans -- and even the most ambitious goals to limit it would result in an average global temperature change of 1.5 degrees celsius, far higher than the average shifts seen during the catastrophic Little Ice Age.

And something else was also happening in the 17th century that felt as mysterious and strange as lower temperatures: Higher prices, sometimes called a "price revolution" 价格革命, that increased prices for food and other goods.
This was caused partly by the growing population we discussed in our last episode, and partly by inflation 通货膨胀 -- more precious metals were entering Europe, especially due to mining in the Americas, which decreased the value of coinage 铸币；货币制度.
But this was really baffling 令人困惑的 for people -- I mean, imagine that you're living in Spain in the 17th century, watching precious metals pour into your country via the New World, and despite all this new wealth, you're finding it harder to pay for bread, and clothing, and almost everything else.
Inflation, like climate, is extremely complex, and also a hugely important historical force.

And so as prices soared 猛涨 and harvests declined, it really did feel like the 17th century might just be the end.
As one pamphleteer 小册子作者 from Spain wrote in 1643: "Every nation is turned upside down, leading some great minds to suspect that we are approaching the end of the world."

And then there was the 30 Years War 三十年战争, which unlike the 100 Years War, actually did last for 30 years.
The war, which took place from 1618 to 1648, was tremendously destructive in Central Europe -- millions of people were killed, including many from starvation brought on by the war.
Many different states within the quickly fracturing 分裂的 Holy Roman Empire were involved, as were France and Sweden and Denmark and England.
The war started in 1618 over, you guessed it, religion.
It began when Ferdinand II, the devotedly Catholic new Hapsburg king of Bohemia, sent representatives to inform powerful Protestants that Prague and the rest of Bohemia would be Catholic territory from now on.
Unsurprisingly, the Protestant lords in Prague weren't terribly happy with this news.
In fact, they were so unhappy that they threw Ferdinand's representatives out -- literally, out the window, in the so-called Defenestration of Prague 布拉格掷出窗外事件.
Did the center of the world just open?
Is there a window in there?
Now, this is a famous moment in European history, in part because it's called the Defenestration of Prague, which is just irresistible, but in part because it was the SECOND defenestration of Prague.
The first one occurred in 1419 and resulted in the deaths of seven people; the second one, the one we're concerned with now, resulted in the deaths of no people, because all four of the defenestrated landed in a pile of manure  manure 粪肥.
Ferdinand's people, of course, called this a divine miracle 神的奇迹, while the Protestants were like, "they landed in poop!"
Ah, god I love history.
Soon after the defenestration, Ferdinand II was elected Holy Roman Emperor, which led the Protestant Czechs to reject him as king of Bohemia, and choose the protestant Frederick V of the Palitanate to replace him, and then war truly erupted.
The Czechs would be initially defeated by Hapsburg forces in the Battle of White Mountain in 1620, and the Hapsburg family would in fact rule the area until 1918.
But that didn't settle the war -- nor, in fact, did Ferdinand's next victories.

Let's go to the Thought Bubble.

So on the one hand you have the imperial forces 帝国军队,
led by the Catholic Hapsburg Ferdinand II,
and on the other hand you have protestant Frederick V
and his allies among the protestant aristocrats 贵族 of central Europe.
The Hapsburgs went on to crush Frederick's allies.
In the 1620s, Ferdinand took the Palatinate from the defeated Frederick
and awarded 授予 it to his Catholic ally, Maximilian of Bavaria.
Ferdinand then awarded other lands to Catholic allies
that had belonged to defeated protestant princes,
and he decreed 颁布；命令 that in conquered territories those who had bought Catholic lands, like monasteries, had to return them.
Furthermore, all citizens needed to return to the Catholic Church or else leave their homes.
The Little Ice Age, inflation, and war had crashed the economies,
making it difficult for people to dispose of 处理；处置 their property before they moved.
And we see this again -- and again and again -- in refugee crises 难民危机 throughout history.
So it seemed the Catholics Hapsburgs were going to win,
but then the Protestant king of Denmark, Christian IV, a hugely wealthy ruler,
decided to enter the war to block imperial expansion,
protect Protestants,
and preserve the traditional rights of the many hundreds of independent kingdoms, and duchies 公国, and cities in the Holy Roman Empire.
And that meant that the war, instead of being over, was just getting started.
Thanks, Thought Bubble.

So, Emperor Ferdinand hired the wealthy Albrecht von Wallenstein to confront the Danish menace 威胁 and to continue conquering the Protestant princes in the empire, thus restoring more property to the Catholic Church.
Wallenstein was Czech -- and he'd been born a Protestant, but he'd converted to Catholicism as a teenager and then married a widow who died a few years after their marriage, leaving him a lot of property.
But that was just the beginning of Wallenstein gaining property via death and/or marriage.
Wallenstein did his conquering with such gusto 热情；兴致 and success that Ferdinand constantly rewarded him with more estates 庄园；地产.
And when Wallenstein married again, he gained even more wealth and prestige 威望；声望.
He started out as hired help, but eventually grew to be powerful in his own right 凭借自身能力.
It's a real Holy Roman Empire Dream story.
You know, you start out in the war-making mailroom, and then eventually work your way up to being the CEO of war.
He raised armies of tens of thousands of fighters who laid waste 损毁；破坏 Protestant lands and slaughtered 屠杀 hundreds of thousands of people.
He also had army officers go house-to-house, collecting regular contributions or "taxes" to support the ever growing military forces.
And as he built his army, he justified raising taxes.
Wallenstein expanded the battlefield, in the 30 years war, by seeking out any nearby Protestants whose lands could be captured and returned to the Catholic side, thereby bringing new entrants into the war.
The Netherlands came to the Palatinate's rescue; Spain, Italian states, and France also got involved, as did Sweden, a military powerhouse 军事强国 at the time.
Unlike today, when the Swedes are primarily a Flat Packed Home Goods powerhouse.
Then in 1626, Danish King Christian IV, a Protestant, lost half his army in the battle of Lutter.
Ferdinand II's confidence soared, and with it his counter-reformation zeal 反宗教改革热情; in 1629 he issued the Edict of Restitution 归还敕令 -- a sweeping confiscation 没收 of formerly Catholic lands and a harsh directive 指令 for non-Catholics to emigrate 移民.
And Ferdinand was merciless 无情的；残忍的.
When his armies would defeat the rebels, Ferdinand had those taken prisoner disemboweled 取出内脏 after their right hands were hacked off 砍掉.
His German prince allies counseled moderation 建议节制, but Ferdinand preferred the advice of his Jesuit priest to push the Counter-Reformation ever further.
Ferdinand, his confessor 告解神父 announced, could "lose all his kingdoms and provinces and whatever he has in this world, provided he save his soul." So there would be no compromise.
Then in 1631, Swedish king Gustavus Adolphus defeated the imperial army at the Battle of Breitenfeld, the first major Protestant victory of the war, which was by then thirteen years old.
Though Gustavus Adolphus was killed in battle the next year, that Catholic defeat heartened Protestant forces, who kept the war going.
Meanwhile, the war stopped being about JUST religion.
For instance, Louis XIII of France had allied himself with the Swedish king, even though Louis was Catholic and the Swedes were Protestant, because Louis didn't want the Holy Roman Empire to become too powerful.
Over time, the daily realities of the war became even more brutal, as armies simply wandered across central Europe killing and scrounging for food 搜寻食物.
Young and old peasants and townspeople were stabbed or captured and tortured to death as waves of soldiers went from house to house.
The first waves took obvious treasure, and then each successive wave settled on smaller objects like copper and other base metal coins 贱金属硬币 or tiny silver trinkets 小银饰品.
Those were the minor offenses.
Roasting people alive, torturing people's genitals 生殖器 until victims died, and raping girls to death now became standard behavior in the war.
Meanwhile, civilians were also dying of hunger, and cold, and disease.
The little ice age was taking its toll 造成损失 along with the armies, who fought in the name of the Catholic, or Lutheran, or Calvinist cause or just merely to survive.
Desperate refugee families were forced to leave their homes to start over dozens of times.
Just one example of the horror: in Protestant Magdeberg, city officials faced an imperial army and its mercenaries 雇佣兵 at the city limits in the fall of 1630.
And over the course of seven months devastation 破坏；毁灭 unfolded.
Residents harassed 骚扰 the Catholic invaders, hurling rocks and other objects on them from the city's ramparts 城墙.
And once the imperial armies breached the walls, they started to torch the city 放火烧城.
Magdeberg's citizens struggled to escape both the armies and the fire.
Of 25,000 citizens, only 5,000 were left at the end of the battle for the city -- which was in the end destroyed by fire.
In 1634, Holy Roman Emperor Ferdinand II had his own general Wallenstein assassinated 暗杀, because it appeared that Wallenstein was plotting to make peace with Sweden and perhaps planning a coup 政变, although why anyone would want to be the Holy Roman Emperor at that point is an absolute mystery to me.
But the war continued.
The 1640s brought more horrendous 可怕的；令人震惊的 weather, and disorder reigned as social and political systems completely fell apart.
There was often little in the way of a functioning government; economies completely collapsed; and all manner of social norms 社会规范 broke down.
There were, for instance, many reports of cannibalism.
And public spaces became additionally dangerous when wolves and other wild animals arrived in villages and private farms.
Finally, in 1648, the Peace of Westphalia 威斯特伐利亚和约 finally brought the war to an end.
Even hard-headed theologians 顽固的神学家 by that time allowed concessions 让步 to the other religion in order to obtain peace.
And the fact that French Catholics uniting with Swedish and other Protestants led to the conclusion that this maybe meant the end of religious war -- at least in Europe, at least for now.
The war tapered off 逐渐减弱 because of political and economic considerations, but also because the level of devastation just became too horrifying.
Combatants 参战方 met at a peace conference where Emperor Ferdinand III made concessions of land and cash reluctantly 不情愿地, forced by exhaustion and the continuing miseries inflicted by the little ice age.
All of this marked a turn to more "practical" concerns in government policy rather than just like, going to war to promote your religion.
Rates of mortality 死亡率 were very high in the seventeenth century globally because of the pervasiveness 普遍性 of the little ice age and because of devastating warfare.
And we need to remember the immense human costs of the thirty Years war: some 20 percent of the central European population died, while in areas of intense and continuous fighting, it was closer to 50 percent.
If I can return to a shockingly positive picture, amidst all of that, the creation of our modern view of science and its benefits was taking place in many of the same regions, which reminds us that history is not one human story, but all human stories.
Some good news is coming next week.
Thanks for watching.
I'll see you then.

'''

== 中文释义


大家好，我是约翰·格林。 +
这里是《速成欧洲史》，今天我们将探讨有时被称为“17世纪危机”的历史事件。 +

我知道你在想什么：**整个历史**简直**就是一场接一场的危机。** +
没错，亲爱的观众，确实如此。 +
人类在灾难间跌跌撞撞前行，却仍像逆水行舟般奋进，有时甚至能从过往灾难中吸取教训。 +
鉴于**17世纪危机涉及气候变化与灾难性战争，**我们或许该好好关注一下。 +

让我们从“小冰期”（Little Ice Age）说起。 +
*小冰期始于1300年，但从1570年起显著加剧，此后一个多世纪里气候持续变冷。 这是全球性现象。* +
*在某些地区，气温可能下降了2摄氏度（3.6华氏度），但平均降幅约为0.5摄氏度。* +
这听起来或许不惊人，但实际影响巨大。 +
*暴雨、光照不足, 与低温, 导致农作物减产甚至绝收。* +
欧洲人遭受体温过低之苦，出生率下降，饥荒愈发普遍——食人现象也随之增多。 +
*在新英格兰，17世纪末是小冰期最严酷的时期。* +
1797年尤为惨烈：定居者塞缪尔·休厄尔（Samuel Sewell）在日记中写道：“对马、猪、牛、羊和鹿而言，1797年是致命的一年。” +

与当代气候变化不同，小冰期主要并非由人类行为引发——其成因可能是火山活动、轨道周期, 或太阳辐射的周期性低谷。 +
*我们总以为地球气候完全稳定，但事实并非如此。* +
不过，当代气候变化, 确由人类导致——即便最雄心勃勃的减排目标，也只能将全球平均气温升幅控制在1.5摄氏度，这远高于灾难性小冰期的平均温差。 +

**17世纪**还发生了与"气温下降"同样神秘诡异的现象：*物价上涨（有时被称为“价格革命”），食品与其他商品价格攀升。* +
**部分原因是**我们在上一集讨论过的**人口增长，部分则源于通货膨胀——尤其是美洲矿产开采促使更多贵金属流入欧洲，导致货币贬值。** +
这让当时的人们困惑不已——试想，你生活在17世纪的西班牙，眼看新大陆的贵金属源源不断涌入国家，却发现连面包、衣物和几乎所有物品都越来越难以负担。 +
通货膨胀如同气候变化，极其复杂，却也是极具影响力的历史力量。 +

*因此，当物价飞涨、收成锐减，17世纪的确给人以“末日将至”之感。* +
正如一位西班牙小册子作者在1643年所写：“各国陷入混乱，让一些有识之士怀疑我们正走向世界末日。” +

*接下来是“三十年战争”（30 Years War）*，与“百年战争”不同，它确实持续了30年。 +
这场1618至1648年的战争, 对中欧造成了巨大破坏——数百万人丧生，其中许多人死于战争引发的饥荒。 +
迅速分裂的神圣罗马帝国境内诸多邦国, 卷入战争，法国、瑞典、丹麦和英国也参与其中。 +
**战争的起因，**你猜对了，*是宗教。* +

1618年，虔诚的天主教徒、哈布斯堡王朝新任波西米亚国王斐迪南二世（Ferdinand II）, 派代表告知强大的"新教"贵族：布拉格及波西米亚其他地区, 从今往后将成为天主教领地。 +
不出所料，布拉格的新教贵族, 对此深感不满。 +
事实上，他们愤怒到将斐迪南的代表扔出窗外——这就是著名的“布拉格抛窗事件”（Defenestration of Prague）。 +

世界中心又“打开”了吗？里面有扇窗户？ +
这是欧洲历史上的著名事件，部分因为它被称为“布拉格抛窗事件”，光这名字就令人印象深刻，部分则因为这已是第二次“布拉格抛窗”。 +
第一次发生在1419年，导致7人死亡；我们现在关注的第二次则无人死亡，因为被抛下的4人全都落在了一堆粪肥上。 +
斐迪南的支持者当然将此称为“神圣奇迹”，而新教徒则表示：“他们掉进了粪堆里！” +
啊，我太爱历史了。 +

抛窗事件后不久，斐迪南二世当选神圣罗马帝国皇帝，这导致"新教"的捷克人, 拒绝承认他的波西米亚国王身份，转而选择普法尔茨（Palatinate）的"新教"领主腓特烈五世（Frederick V）取而代之，战争由此全面爆发。 +
捷克人起初在1620年的白山战役（Battle of White Mountain）中, 被哈布斯堡军队击败，而哈布斯堡家族确实统治该地区直至1918年。 +
但这并未终结战争——事实上，斐迪南随后的胜利, 也未能终结战争。 +

让我们进入“思想泡泡”环节。 +
一方面是"天主教"哈布斯堡王朝斐迪南二世领导的帝国军队，另一方面是"新教"的腓特烈五世, 及其中欧"新教"贵族盟友。 +
哈布斯堡王朝继而击溃了腓特烈的盟友。 +
17世纪20年代，斐迪南从战败的腓特烈手中, 夺取普法尔茨，将其赐予天主教盟友巴伐利亚的马克西米利安（Maximilian of Bavaria）。 +
斐迪南随后将其他原属战败新教诸侯的土地赐予天主教盟友，并颁布法令：在被征服领土上，购买过天主教土地（如修道院）的人必须归还土地。 +
此外，所有公民必须回归天主教会，否则需背井离乡。 +
小冰期、通货膨胀与战争已让经济崩溃，人们在迁徙前, 难以处置财产。 +
我们在历史上的难民危机中, 一次又一次看到这种困境。 +

**眼看天主教哈布斯堡王朝即将胜利，新教的丹麦国王**克里斯蒂安四世（Christian IV）——一位极其富有的统治者——*决定参战，以阻止帝国扩张、保护新教徒，并维护神圣罗马帝国数百个独立王国、公国和城市的传统权利。* +
这意味着战争远未结束，一切才刚刚开始。 +

感谢“思想泡泡”。 +

于是，斐迪南皇帝雇佣富有的阿尔布雷希特·冯·华伦斯坦（Albrecht von Wallenstein）, 应对丹麦威胁，并继续征服帝国境内的新教诸侯，从而为天主教会夺回更多财产。 +
华伦斯坦是捷克人，出生时为新教徒，但十几岁时皈依天主教，后与一位寡妇结婚，妻子在婚后几年去世，留给他大量财产。 +
但这只是华伦斯坦通过死亡或婚姻积累财产的开始。 +
华伦斯坦在征服行动中, 充满热忱, 且战绩显赫，斐迪南不断赏赐给他更多庄园。 +
当他再次结婚时，又获得了更多财富与声望。 +
他从“雇佣军”起步，最终凭借自身实力成为权臣。 +
这简直是“神圣罗马帝国的梦想故事”——从战争“收发室”起步，最终晋升为“战争CEO”。 +

他招募了数万人的军队，蹂躏"新教"土地，屠杀数十万人。 +
*他还让军官挨家挨户征收“常规贡赋”或“税款”，以维持不断扩张的军队。* +
在组建军队的过程中，他为征税找到了“合理理由”。 +
华伦斯坦在三十年战争中扩大了战场范围，搜寻附近任何可征服的新教土地, 并划归天主教一方，从而让更多势力卷入战争。 +
荷兰赶来支援普法尔茨；西班牙、意大利各邦和法国也加入战局；当时的军事强国瑞典亦参战——与如今主要作为“平装家居用品强国”的瑞典不同。 +

1626年，新教的丹麦国王克里斯蒂安四世, 在卢特战役（battle of Lutter）中损失了半数军队。 +
斐迪南二世信心大增，反宗教改革的热情也随之高涨；1629年，*他颁布《归还敕令》（Edict of Restitution）——全面没收前天主教土地，并严厉指示非天主教徒移民。* +
斐迪南毫不留情。 +
当军队击败叛军时，他下令将俘虏砍去右手后开膛破肚。 +
他的德意志诸侯盟友建议宽大为怀，但斐迪南更愿意听从耶稣会牧师的建议，将反宗教改革推向更远。 +
斐迪南的忏悔神父宣称，皇帝“可以失去所有王国、行省和世间一切，只要能拯救灵魂”。因此，绝不妥协。 +

1631年，瑞典国王古斯塔夫·阿道夫（Gustavus Adolphus）, 在布赖滕费尔德战役（Battle of Breitenfeld）中击败帝国军队，这是战争爆发十三年来, 新教的首次重大胜利。 +
尽管古斯塔夫·阿道夫次年在战斗中阵亡，但天主教的失败鼓舞了新教势力，战争得以持续。 +
*与此同时，战争不再仅仅围绕宗教。* +
例如，法国国王路易十三（Louis XIII）与瑞典国王结盟——尽管路易是天主教徒而瑞典人是新教徒——因为路易不希望神圣罗马帝国过于强大。 +

*随着时间推移，战争的日常现实愈发残酷，军队在中欧四处游荡，杀戮并搜寻食物。* +
*无论老幼，农民和城镇居民都可能被刺伤、俘虏或折磨致死，一波又一波士兵挨家挨户洗劫。* +
*第一波士兵掠走显眼的财宝，随后每一波士兵则盯上更小的物品，如铜币、其他贱金属硬币或 tiny 银饰。* +
这些尚属“轻微暴行”。 +
*将人活活烤死、折磨生殖器直至受害者死亡、奸杀女孩等行为，如今成为战争中的“常规操作”。* +
与此同时，平民也因饥饿、寒冷和疾病死去。 +
小冰期与打着天主教、路德宗或加尔文宗旗号（或仅仅为了生存）的军队共同肆虐。 +
绝望的难民家庭被迫离家, 重建生活数十次。 +

举一个恐怖的例子：1630年秋，新教城市马格德堡（Magdeberg）的官员, 在城界处面对帝国军队及其雇佣军。 +
七个月间， devastation 接踵而至。 +
居民从城墙上, 向天主教入侵者投掷石块和其他物品，骚扰敌军。 +
*一旦帝国军队攻破城墙，便开始纵火焚烧城市。* +
马格德堡市民挣扎着逃离军队与大火。 +
2.5万市民中，战役结束时仅存5000人——城市最终被大火摧毁。 +

1634年，神圣罗马帝国皇帝斐迪南二世, 派人暗杀了自己的将军华伦斯坦，因为有迹象表明, 华伦斯坦正密谋与瑞典议和，甚至可能策划政变。不过在当时，究竟为何有人想成为神圣罗马帝国皇帝，我完全无法理解。 +
但战争仍在继续。 +
17世纪40年代，天气愈发恶劣，随着社会和政治体系彻底崩塌，混乱统治着一切。
政府几乎瘫痪，经济完全崩溃，各种社会规范土崩瓦解。
例如，当时有许多食人现象的报道。
当狼群和其他野生动物涌入村庄和私人农场时，公共空间变得更加危险。 +

*最终，1648年的《威斯特伐利亚和约》（Peace of Westphalia）终于结束了战争。* +
*即便顽固的神学家, 此时也允许对其他宗教做出让步，以换取和平。* +
法国天主教徒与瑞典等新教徒联合，这一事实暗示着**宗教战争可能就此终结——至少在欧洲，至少暂时如此。** +
*战争逐渐平息，既出于政治和经济考量，也因为破坏程度已令人无法承受。*
交战各方召开和平会议，斐迪南三世皇帝因疲惫与小冰期持续带来的苦难，勉强在土地和金钱上做出让步。
*这一切标志着政府政策转向更“实际”的考量，而不再仅仅为了推广宗教而发动战争。* +

*由于小冰期的普遍性和毁灭性战争的影响，17世纪全球死亡率极高。* +
我们需要铭记**三十年战争的巨大人道代价：中欧约20%的人口死亡，而在战斗激烈且持续的地区，死亡率接近50%。** +

即便在这样的黑暗中，仍有一丝惊人的积极迹象：现代科学观及其益处正在许多相同地区孕育。这提醒我们，历史不是单一的人类故事，而是所有人类故事的总和。 +
下周将带来一些好消息。 感谢观看，下期见。

'''

== pure

Hi, I'm John Green.
This is Crash Course European History, and today we're going to look at what is sometimes called the "seventeenth century crisis."

Now I know what you're thinking: This whole history business is just one crisis after another.

And yes, dear viewer, it's true.

Humankind careens from disaster to disaster, but still we press on, like boats against the current, and sometimes we even learn from previous disasters.

And since the Seventeenth Century Crisis involves climate change and catastrophic war, we should maybe pay attention to this one.

Let's begin with the Little Ice Age.

The Little Ice Age began in 1300, but it really escalated beginning in 1570, and then the climate continued to cool for over one hundred years after that.

It was a global phenomenon.

In some places, the temperature may have shifted two degrees Celsius or 3.6 degrees Fahrenheit, but the average was about half a degree Celsius.

That may not sound dramatic, but it was.

Intense rainfall, lack of sunshine, and lower temperatures decreased harvests or ruined them entirely.

Europeans suffered hypothermia; the birthrate dropped; and famines became more common -- as did cannibalism.

In New England, the end of the 17th century was the worst part of the Little Ice Age.

1797 was especially brutal: Settler Samuel Sewell noted in his diary: "To Horses, Swine, Nett-Cattell, Sheep, and Deer, Ninety and Seven prov'd a Mortal yeer."

Now, unlike contemporary climate change, the Little Ice Age was not caused primarily by human behavior -- it may have been caused by volcanic activity or orbital cycles or cyclical lows in solar radiation.

We like to think of the Earth's climate as entirely stable, but it never has been.

That said, contemporary climate change IS caused by humans -- and even the most ambitious goals to limit it would result in an average global temperature change of 1.5 degrees celsius, far higher than the average shifts seen during the catastrophic Little Ice Age.

And something else was also happening in the 17th century that felt as mysterious and strange as lower temperatures: Higher prices, sometimes called a "price revolution," that increased prices for food and other goods.

This was caused partly by the growing population we discussed in our last episode, and partly by inflation -- more precious metals were entering Europe, especially due to mining in the Americas, which decreased the value of coinage.

But this was really baffling for people -- I mean, imagine that you're living in Spain in the 17th century, watching precious metals pour into your country via the New World, and despite all this new wealth, you're finding it harder to pay for bread, and clothing, and almost everything else.

Inflation, like climate, is extremely complex, and also a hugely important historical force.

And so as prices soared and harvests declined, it really did feel like the 17th century might just be the end.

As one pamphleteer from Spain wrote in 1643: "Every nation is turned upside down, leading some great minds to suspect that we are approaching the end of the world."

And then there was the 30 Years War, which unlike the 100 Years War, actually did last for 30 years.

The war, which took place from 1618 to 1648, was tremendously destructive in Central Europe -- millions of people were killed, including many from starvation brought on by the war.

Many different states within the quickly fracturing Holy Roman Empire were involved, as were France and Sweden and Denmark and England.

The war started in 1618 over, you guessed it, religion.

It began when Ferdinand II, the devotedly Catholic new Hapsburg king of Bohemia, sent representatives to inform powerful Protestants that Prague and the rest of Bohemia would be Catholic territory from now on.

Unsurprisingly, the Protestant lords in Prague weren't terribly happy with this news.

In fact, they were so unhappy that they threw Ferdinand's representatives out -- literally, out the window, in the so-called Defenestration of Prague.

Did the center of the world just open?

Is there a window in there?

Now, this is a famous moment in European history, in part because it's called the Defenestration of Prague, which is just irresistible, but in part because it was the SECOND defenestration of Prague.

The first one occurred in 1419 and resulted in the deaths of seven people; the second one, the one we're concerned with now, resulted in the deaths of no people, because all four of the defenestrated landed in a pile of manure.

Ferdinand's people, of course, called this a divine miracle, while the Protestants were like, "they landed in poop!"

Ah, god I love history.

Soon after the defenestration, Ferdinand II was elected Holy Roman Emperor, which led the Protestant Czechs to reject him as king of Bohemia, and choose the protestant Frederick V of the Palitanate to replace him, and then war truly erupted.

The Czechs would be initially defeated by Hapsburg forces in the Battle of White Mountain in 1620, and the Hapsburg family would in fact rule the area until 1918.

But that didn't settle the war -- nor, in fact, did Ferdinand's next victories.

Let's go to the Thought Bubble.

So on the one hand you have the imperial forces,
led by the Catholic Hapsburg Ferdinand II,
and on the other hand you have protestant Frederick V
and his allies among the protestant aristocrats of central Europe.
The Hapsburgs went on to crush Frederick's allies.
In the 1620s, Ferdinand took the Palatinate from the defeated Frederick
and awarded it to his Catholic ally, Maximilian of Bavaria.
Ferdinand then awarded other lands to Catholic allies
that had belonged to defeated protestant princes,
and he decreed that in conquered territories those who had bought Catholic lands, like monasteries, had to return them.
Furthermore, all citizens needed to return to the Catholic Church or else leave their homes.
The Little Ice Age, inflation, and war had crashed the economies,
making it difficult for people to dispose of their property before they moved.
And we see this again -- and again and again -- in refugee crises throughout history.
So it seemed the Catholics Hapsburgs were going to win,
but then the Protestant king of Denmark, Christian IV, a hugely wealthy ruler,
decided to enter the war to block imperial expansion,
protect Protestants,
and preserve the traditional rights of the many hundreds of independent kingdoms, and duchies, and cities in the Holy Roman Empire.
And that meant that the war, instead of being over, was just getting started.
Thanks, Thought Bubble.

So, Emperor Ferdinand hired the wealthy Albrecht von Wallenstein to confront the Danish menace and to continue conquering the Protestant princes in the empire, thus restoring more property to the Catholic Church.

Wallenstein was Czech -- and he'd been born a Protestant, but he'd converted to Catholicism as a teenager and then married a widow who died a few years after their marriage, leaving him a lot of property.

But that was just the beginning of Wallenstein gaining property via death and/or marriage.

Wallenstein did his conquering with such gusto and success that Ferdinand constantly rewarded him with more estates.

And when Wallenstein married again, he gained even more wealth and prestige.

He started out as hired help, but eventually grew to be powerful in his own right.

It's a real Holy Roman Empire Dream story.

You know, you start out in the war-making mailroom, and then eventually work your way up to being the CEO of war.

He raised armies of tens of thousands of fighters who laid waste Protestant lands and slaughtered hundreds of thousands of people.

He also had army officers go house-to-house, collecting regular contributions or "taxes" to support the ever growing military forces.

And as he built his army, he justified raising taxes.

Wallenstein expanded the battlefield, in the 30 years war, by seeking out any nearby Protestants whose lands could be captured and returned to the Catholic side, thereby bringing new entrants into the war.

The Netherlands came to the Palatinate's rescue; Spain, Italian states, and France also got involved, as did Sweden, a military powerhouse at the time.

Unlike today, when the Swedes are primarily a Flat Packed Home Goods powerhouse.

Then in 1626, Danish King Christian IV, a Protestant, lost half his army in the battle of Lutter.

Ferdinand II's confidence soared, and with it his counter-reformation zeal; in 1629 he issued the Edict of Restitution -- a sweeping confiscation of formerly Catholic lands and a harsh directive for non-Catholics to emigrate.

And Ferdinand was merciless.

When his armies would defeat the rebels, Ferdinand had those taken prisoner disemboweled after their right hands were hacked off.

His German prince allies counseled moderation, but Ferdinand preferred the advice of his Jesuit priest to push the Counter-Reformation ever further.

Ferdinand, his confessor announced, could "lose all his kingdoms and provinces and whatever he has in this world, provided he save his soul." So there would be no compromise.

Then in 1631, Swedish king Gustavus Adolphus defeated the imperial army at the Battle of Breitenfeld, the first major Protestant victory of the war, which was by then thirteen years old.

Though Gustavus Adolphus was killed in battle the next year, that Catholic defeat heartened Protestant forces, who kept the war going.

Meanwhile, the war stopped being about JUST religion.

For instance, Louis XIII of France had allied himself with the Swedish king, even though Louis was Catholic and the Swedes were Protestant, because Louis didn't want the Holy Roman Empire to become too powerful.

Over time, the daily realities of the war became even more brutal, as armies simply wandered across central Europe killing and scrounging for food.

Young and old peasants and townspeople were stabbed or captured and tortured to death as waves of soldiers went from house to house.

The first waves took obvious treasure, and then each successive wave settled on smaller objects like copper and other base metal coins or tiny silver trinkets.

Those were the minor offenses.

Roasting people alive, torturing people's genitals until victims died, and raping girls to death now became standard behavior in the war.

Meanwhile, civilians were also dying of hunger, and cold, and disease.

The little ice age was taking its toll along with the armies, who fought in the name of the Catholic, or Lutheran, or Calvinist cause or just merely to survive.

Desperate refugee families were forced to leave their homes to start over dozens of times.

Just one example of the horror: in Protestant Magdeberg, city officials faced an imperial army and its mercenaries at the city limits in the fall of 1630.

And over the course of seven months devastation unfolded.

Residents harassed the Catholic invaders, hurling rocks and other objects on them from the city's ramparts.

And once the imperial armies breached the walls, they started to torch the city.

Magdeberg's citizens struggled to escape both the armies and the fire.

Of 25,000 citizens, only 5,000 were left at the end of the battle for the city -- which was in the end destroyed by fire.

In 1634, Holy Roman Emperor Ferdinand II had his own general Wallenstein assassinated, because it appeared that Wallenstein was plotting to make peace with Sweden and perhaps planning a coup, although why anyone would want to be the Holy Roman Emperor at that point is an absolute mystery to me.

But the war continued.

The 1640s brought more horrendous weather, and disorder reigned as social and political systems completely fell apart.

There was often little in the way of a functioning government; economies completely collapsed; and all manner of social norms broke down.

There were, for instance, many reports of cannibalism.

And public spaces became additionally dangerous when wolves and other wild animals arrived in villages and private farms.

Finally, in 1648, the Peace of Westphalia finally brought the war to an end.

Even hard-headed theologians by that time allowed concessions to the other religion in order to obtain peace.

And the fact that French Catholics uniting with Swedish and other Protestants led to the conclusion that this maybe meant the end of religious war -- at least in Europe, at least for now.

The war tapered off because of political and economic considerations, but also because the level of devastation just became too horrifying.

Combatants met at a peace conference where Emperor Ferdinand III made concessions of land and cash reluctantly, forced by exhaustion and the continuing miseries inflicted by the little ice age.

All of this marked a turn to more "practical" concerns in government policy rather than just like, going to war to promote your religion.

Rates of mortality were very high in the seventeenth century globally because of the pervasiveness of the little ice age and because of devastating warfare.

And we need to remember the immense human costs of the thirty Years war: some 20 percent of the central European population died, while in areas of intense and continuous fighting, it was closer to 50 percent.

If I can return to a shockingly positive picture, amidst all of that, the creation of our modern view of science and its benefits was taking place in many of the same regions, which reminds us that history is not one human story, but all human stories.

Some good news is coming next week.

Thanks for watching.

I'll see you then.

'''