
= 014 - Absolute Monarchy
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hi, I'm John Green, and this is Crash Course European History.


So today we're moving into the second half of the 17th century.

The 30 Years War has ended with the Treaty of Westphalia 威斯特伐利亚和约, and the Scientific Revolution is producing amazing new universal laws 普遍规律, but life is still pretty terrible for the vast majority of people.

For Kings though, things were changing with the advent 出现；到来 of absolutism 专制主义, in which the king is said to have a divine right 神权 to the throne 王位.

And the divinest divine right monarch 君主 of them all, Louis XIV, led Western Europe's most powerful Kingdom for more than 70 years.

So this is a portrait of Louis XIV -- the French Sun King 太阳王, painted when he was 63.

Louis XIV looks regal 威严的；帝王般的 in his massive black wig 假发 and swaths of ermine 貂皮, embellished 装饰 with fleurs-de-lis 鸢尾花；百合花, the symbol of the former French royal house 法国王室.

His high heels show off his shapely legs in white hose 长筒袜, demonstrating the king's perfection.

Men's legs garbed in tightly fitted stockings 紧身长袜 were a key indication of desirability 魅力 at the time, and while he may not appear super masculine 有男子气概的 to us, Louis XIV was the model of powerful kingship 王权 and indeed absolute power 绝对权力.

Louis was four years old when he started his reign 统治 in 1643, while Europe was attempting to pull itself out of the 30 Years War.

Earlier, under Louis's father, Louis XIII, rebellions 叛乱 abounded 大量存在 in the hundreds across the kingdom because of increasingly heavy taxation 税收 to pay for the war and the famine conditions 饥荒状况 due to the relentless 无情的 little ice age.

It seemed almost unthinkable to ordinary people that the king would betray his subjects 臣民 with rising taxes in a time of famine.

So instead, they usually blamed tax collectors 税务官 and local officials, not the king.

After Louis XIII died, his four-year-old son was a smidge 少量；些许 small for France ruling, so the job was taken over by his regent 摄政王, his mother, Anne of Austria, with help from her sidekick 助手 and rumored lover 传闻中的情人, the Italian-born Cardinal Mazarin.

The first years of Anne's Regency 摄政期 were the last years of the 30 Years War, and she increased French military deployments 军事部署 even amid all these protests, with the simple and eventually successful goal of defeating the Spanish and Austrian Habsburgs to gain more territory 领土.

Alongside increasing the desperation 绝望 of ordinary people, this constant warfare stretched aristocratic resources 贵族资源 because Nobles raised and paid for their own armies in wartime.

Louis's mother had to move him several times to keep him safe amid protests from peasants and nobility alike, some of whom even went to the point of plotting coups d'état 政变, which is, after all, a French phrase.

The Pieds-Nus -- or barefooted ones 赤脚者, the Croquants -- or crunchers or crispies 饥民, and even judges of Paris were among the people resisting.

One judge listed the sacrifices of ordinary people, such as selling all their furniture and sleeping on straw 稻草 in order to pay rising taxes.

He said, to maintain the luxury of Paris, millions of innocent souls are obliged to live on black bread 黑面包 and oats 燕麦.

Did the center of the world just open?

Is there a pumpernickel bagel 粗黑麦百吉饼 in there?

It's the closest we could get to black bread.

Now, this is a properly great bagel.

Hmm.
I'm gonna eat that whole thing once this is done.

But black bread in 17th century France... not good.

For one thing, it was often cut with sawdust 锯末, which, you know, isn't ideal for bread making and also isn't ideal for nutrition 营养.

In fact, our contemporary bread is so good that it's hard for us to imagine just how difficult the circumstances were in the 17th century.

Like, just how desperate you have to be to add sawdust to your dough 面团.

So we're gonna jump back in time for a bit.

Earlier in the 17th century, a group of judges managed to undermine 削弱 the monarchy 君主制, if only temporarily 暂时地.

You'll recall that France ended their religious civil war with Henry, Paris's well-worth amassed the fourth ruling.

Henry was Louis XIV's grandfather, and to pay for ongoing wars, Henry raised a new tax called the Paulette 官职税 that was paid by government officials, including judges, over a nine-year period.

And if you paid the Paulette, you could keep your job for life or even sell your job to a successor 继任者, and this created a powerful class of bureaucrats 官僚 who were basically immune from state oversight 免受国家监督.

But Henry couldn't afford to get rid of the Paulette because he needed the cash to wage wars 发动战争.

The officials who bought their positions came to be known as the nobles of the robe 穿袍贵族, as opposed to the old-school nobles 传统贵族, who were called the nobles of the sword 佩剑贵族 because they'd gotten their status via military service to the king.

Flash forward 快进 a few decades.

Anne of Austria and Cardinal Mazarin are trying to throw these nobles of the robe out of office 免职, which the new nobles are, of course, not keen on 不感兴趣, leading them to threaten to arrest them.

I mean, after all, they'd paid a lot of money for those robes.

All of this pushed the people of Paris to their most menacing protests 威胁性的抗议 until the monarchy backed down 让步 and released the judges that they had imprisoned 监禁.

And this triumph over the monarchy made the nobility of the robe a force to be reckoned with 不可忽视的力量 and also indicated that maybe the absolute power of the monarchy wasn't actually that absolute.

Alongside these protesters, another contender for influence 有影响力的竞争者 arose.

A new Catholic movement, Jansenism 詹森主义, called for a complete purging of the self 自我净化 and a fervent spirituality 狂热的灵性 to replace the insufficient and even deluded practices of the church.

Like, for instance, being a cardinal who is probably hooking up with 和…有不正当关系 the king's mom.

The Jansenists believed only intense and full religious commitment could pull France from its dire straits 困境, and they menaced established authority 威胁既有的权威.

But the most threatening uprising 起义 was the Fronde 投石党运动, a series of opposition movements 反对运动 between 1648 and 1653, in which the old nobility and the courts were like, "You can't just raise our taxes willy-nilly 随心所欲地 without asking permission," and Anne of Austria was like, "Of course we can.

It's a kingdom, and we are, well, if not exactly the king, at least the king's regent and her sidekick."

Let's go to the Thought Bubble.

Louis XIV was officially crowned king 加冕为王 in 1654 when he was 15, and as he grew older, his urgent task became organizing the administration of his kingdom 王国管理, raising funds 筹集资金, and uniting his subjects in loyalty to him 使臣民效忠于他.

Part of his brilliance 高明之处 was to divert the nobility 转移贵族注意力 and, in fact, a good part of France with a spectacular court life 壮观的宫廷生活, rather how a parent might divert a relentless unhappy child with, say, an iPad.

But Louie's court was even more diverting 有趣的 than, I don't know, what kids like?

TikTok?
In the 1660s, the king began the task of removing his government from the tumult 骚乱 of Paris by converting a hunting lodge 狩猎小屋 at Versailles 凡尔赛 outside of Paris into the most spectacular European palace complex 宫殿建筑群 of its day.

It housed some 15,000 people when the court moved there in the 1680s, and further thousands in the many adjacent buildings 相邻建筑 for servants and smaller chateaus 城堡 built for Louis's mistresses 情妇.

The nobility was kept busy attending to 伺候 the king and queen, as well as serving the monarchs' legitimate 合法的 and many illegitimate children 私生子.

They also outdid themselves in maneuvering for status 争权夺势.

One of the highest honors being to hand the king his nightshirt 睡衣 in the evening or to oversee his use of the commode 便桶.

The king also sponsored 赞助 and sometimes starred in 主演 spectacular operas and concerts and plays to add to the feeling of his greatness and power.

While the nobility enhanced the scene by behaving as if the king were, in fact, more than humanly powerful.

It was almost like the king was a bright sun whose presence warmed all those it graced, and indeed, that's why Louis XIV came to be known as the Sun King.

Thanks, Thought Bubble!

In the days of absolutism, monarchs across Europe embraced the idea that they had the divine right to their absolute rule 绝对统治.

The Bishop Jacques-Bénigne Bossuet preached 布道 in the royal chapel 皇家礼拜堂 of Versailles that, quote, "It is God who establishes kings...

He vested royalty 赋予王权 in the House of David, and ordered him to cause Solomon, his son, to reign in his place...

Princes thus act as ministers of God."

He continued, "This is why we have seen that the royal throne is not the throne of a man, but the throne of God himself."

To his mind, "God has placed in princes something divine."

And in fact, Bossuet maintained, "Princes are gods."

The king's divinity 神性 allowed for his regime 政权 to be free from arbitrariness 专断 or the tyranny of anarchy 无政府状态的暴政 because whatever he did was necessarily correct.

Louis XIV probably never said the line most famously attributed to him 归属于他, "L'état, c'est moi," or "The state is me," but it has endured 持续存在 for a reason.

He really was the state's power and authority 权力和权威, and he felt that even if he never said it.

But Divine Right theory 君权神授理论 also meant religious conformity 宗教统一.

Louis XIV viewed the presence of Protestants in his realm 王国 as disorderly 混乱的 and sinful 有罪的, causing him to revoke 废除 the Edict of Nantes 南特敕令 in 1685.

Thousands of Protestants then fled France, taking their skills and successful businesses to the Netherlands, the German states, North America, South Africa, and other places.

And for all the surface grandeur 华丽；壮观 of Louis's regime, it worked mostly because of accomplished bureaucrats 有能力的官僚, including the intendants 总督 -- or intendants, if I'm pretending to be able to pronounce French -- whose jobs were regularized 规范化 to oversee tax collections 税收 and the administrations of the various regions of the kingdom.

The most prominent 杰出的 and important of all Louis's officials was Jean-Baptiste Colbert, who oversaw finances 财政 and public works 公共工程, among other things.

Despite being of middle-class birth 中产阶级出身, Colbert drove the kingdom's economy, including its merchants 商人, shipbuilders 造船者, and artisans 工匠.

Colbert also oversaw French expansion into North America, sending out settlers 殖民者 and officials.

Traders combed the continent 搜寻大陆 for the desperately needed furs 毛皮 that were in high demand during the intense cold of the Little Ice Age.

Colbert is most famous for his support of mercantilism 重商主义, a policy that saw economic development and trade as akin to 类似于 war.

Mercantilist thinkers believed that there was only so much wealth in the world -- a finite and fixed amount 有限且固定的数量.

And in such a zero-sum world 零和世界, the only way for one kingdom to win would be for other kingdoms to lose.

We now know this isn't true, but mercantilism was an important driver of policy and foreign relations 外交关系 at the time.

There were many applications of this theory: refusing entry of another kingdom's ships, for instance, or enacting high tariffs 征收高关税 on competitors' goods.

We can see one example of this in cotton textiles 棉纺织品, which were wildly popular, but Europeans had no idea how to produce such lively and washable fabrics 可水洗的织物, so they were outlawed 禁止 in France.

Smuggling 走私, however, thrived 盛行, with women and men alike wearing cotton and even high officials bringing them in illegally.

In this and other areas of life, people did disobey absolutist rules 专制统治的规定.

Still, Louis had a lot of power, including the power to wage war 发动战争.

He waged four major ones: first, the War of Devolution 遗产战争, in which France gained territory in the north; second, the Dutch War 法荷战争, which gained additional land to the north and along the eastern border; third, the War of the League of Augsburg 奥格斯堡同盟战争, in which he lost much of the land won in the Dutch War; and fourth, the War of the Spanish Succession 西班牙王位继承战争, again with significant losses, including in Canada this time to Britain, who you might not have expected to be mixed up in 卷入 the Spanish War of Succession, but everyone wanted in on warring in 17th century Europe.

Clearly, like the ideal reality TV contestant 真人秀参赛者, Louis was not there to make friends.

But we can see through this exchange of lands through endless war how a zero-sum, "I can only win if you lose" worldview 世界观 ends up exhausting resources 耗尽资源 rather than expanding them.

By the end of his reign, the idea of absolutist rule 专制统治 was being thrown into question 受到质疑.

An English critic called absolutist France a "state full of boils and wounds and putrid sores 溃烂的伤口".

Exiled Huguenots 流亡的胡格诺派 called the French under Louis "slaves," his rule directed only "to satisfy both his ambition 野心 and his vengeance 报复".

Again, satisfying one's ambition and one's vengeance makes you a great reality TV contestant, but maybe not necessarily the perfect king.

So absolutism can be seen as a form of tyrannical rule 专制统治, demanding religious, economic, and social conformity 一致；遵从 based on a political theory of monarchical divinity 君主神性的政治理论.

It cost huge amounts in taxation 税收 and loss of life in wars to create this system of civility to royal power 对王权的尊崇制度, and it was pretty disempowering 剥夺权力的 to the French public.

But then again, the rise of a political system of power-sharing in England called constitutionalism 立宪主义 wasn't really less violent, although it did enshrine 把…奉为神圣 certain ideas about human rights 人权.

Thanks for watching.

I'll see you next time.


Thanks for watching Crash Course European History, which is made by all these nice people and filmed here in the Jaden Smith Studio in Indianapolis.

Our animators 动画师 are Thought Cafe.

We have lots more Crash Course available.

You want to learn about astronomy 天文学?

Computer science 计算机科学?

We've got you covered!

Thanks again for watching, and don't forget to be awesome!


'''

== 中文释义

大家好，我是约翰·格林，这里是《速成欧洲史》。
今天我们将进入17世纪的后半叶。

三十年战争随着《威斯特伐利亚和约》的签订而结束，科学革命也产生了令人惊叹的新的普适定律，但对于绝大多数人来说，生活依然相当糟糕。 +
然而，对于国王们来说，**随着专制主义的出现，**情况正在发生变化，*在专制主义中，国王被认为拥有神授的王位继承权。*
而在所有拥有神授君权的君主中，最具神权色彩的当属路易十四（Louis XIV），他统治着西欧最强大的王国长达70多年。

这是一幅路易十四的肖像画，他是法国的太阳王，这幅画绘制于他63岁时。
路易十四戴着巨大的黑色假发，身着大片的貂皮服饰，上面装饰着鸢尾花图案，鸢尾花是前法国王室的象征，他看起来威严庄重。
他的高跟鞋搭配白色长袜，展现出他匀称的双腿，彰显着国王的完美。
**在当时，男士穿着紧身长袜包裹的双腿, 是具有吸引力的关键标志。**虽然在我们看来，他可能不太具有阳刚之气，但路易十四却是强大王权，乃至绝对权力的典范。

1643年，路易十四4岁时开始了他的统治，那时欧洲正试图从三十年战争的创伤中恢复过来。
早些时候，在路易十四的父亲路易十三（Louis XIII）统治时期，由于为战争支付的赋税日益沉重，再加上小冰期肆虐导致饥荒，王国内爆发了数百起叛乱。
对于普通人来说，在饥荒时期国王通过提高税收来背叛他的臣民，这几乎是不可想象的。
所以，他们通常会责怪税务官和地方官员，而不是国王。

路易十三去世后，他4岁的儿子对于统治法国来说还太小了点，所以这项工作由他的摄政者，也就是他的母亲奥地利的安妮（Anne of Austria）接管，她的助手兼传闻中的情人，出生于意大利的马扎然枢机主教（Cardinal Mazarin）也在一旁协助。 +
安妮摄政的最初几年, 正值三十年战争的最后阶段，尽管面临着各种抗议，她还是增加了法国的军事部署，目的很简单，而且最终成功了，那就是打败西班牙和奥地利的哈布斯堡王朝，以获得更多的领土。

除了让普通人的生活更加绝望之外，*这场持续的战争也耗尽了贵族们的资源，因为贵族们在战时需要招募并供养自己的军队。* +
在农民和贵族的抗议声中，路易的母亲不得不几次转移他以确保他的安全，其中一些人甚至密谋发动政变，毕竟，“政变”（coup d'état）是一个法语词汇。 +
“赤脚党”（Pieds-Nus），也就是“赤脚者”，“Croquants”，可以译为“碎碎党”或“脆皮党”，甚至巴黎的法官们也在反抗者之列。
一位法官列举了普通人做出的牺牲，比如为了支付不断上涨的税收，他们卖掉了所有的家具，只能睡在稻草上。
他说，为了维持巴黎的奢华，数百万无辜的灵魂不得不以黑面包和燕麦为生。

世界的中心是不是又打开了？
里面有黑麦贝果吗？
这是我们能找到的最接近黑面包的东西了。
现在，这是一个非常棒的贝果。
嗯。
等录完这个我要把它全吃掉。

但是17世纪法国的黑面包……可不好。
一方面，**黑面包里常常掺杂着锯末，**你知道的，这对于制作面包来说不太理想，而且对营养也不好。
事实上，我们现在的面包如此美味，以至于我们很难想象17世纪的情况有多么艰难。
比如，得绝望到什么程度才会往面团里加锯末啊。

所以我们要稍微回到过去一段时间。
*在17世纪早期，一群法官成功地削弱了君主制的权力，尽管只是暂时的。*
你可能还记得，法国在亨利四世（Henry IV）的统治下, 结束了宗教内战。
亨利四世是路易十四的祖父，*为了支付持续的战争费用，亨利四世开征了一种名为“ Paulette ”的新税，由包括法官在内的政府官员, 在九年时间内缴纳。*
*如果你缴纳了“Paulette”税，你就可以终身保有你的职位，甚至可以把你的职位卖给继任者，这就产生了一个强大的官僚阶层，他们基本上不受国家的监督。*

但是亨利四世无法废除“Paulette”税，因为他需要这笔钱来发动战争。
*那些买官的官员, 后来被称为“穿袍贵族”（nobles of the robe），与传统的“佩剑贵族”（nobles of the sword）相对，佩剑贵族是因为为国王服兵役, 而获得贵族身份的。*

快进到几十年后。
*奥地利的安妮和马扎然枢机主教, 试图将这些"穿袍贵族"免职，而这些新贵族当然不愿意，甚至威胁要逮捕他们。*
我的意思是，毕竟他们为那些职位花了很多钱。 +
所有这些都把巴黎人民推向了最激烈的抗议，直到君主制做出让步，释放了他们关押的法官。
*这次对君主制的胜利, 让"穿袍贵族"成为了一股不可忽视的力量，也表明君主的"绝对权力"实际上可能并没有那么绝对。*

除了这些抗议者之外，另一个有影响力的竞争者出现了。
一个新的天主教运动，詹森主义（Jansenism），呼吁彻底净化自我，并以一种狂热的精神信仰, 来取代教会那些不充分甚至是误导性的做法。
比如说，成为一个可能和国王母亲有暧昧关系的枢机主教。 +
詹森主义者认为，只有强烈而完全的宗教信仰, 才能把法国从困境中拯救出来，他们对既定的权威构成了威胁。

但最具威胁性的起义, 是投石党运动（Fronde），这是1648年至1653年间的一系列反对运动，**在这场运动中，旧贵族和法院表示：“你们不能未经允许, 就随意提高我们的税收。”**而奥地利的安妮则回应道：“我们当然可以。这是一个王国，而且我们，嗯，就算不是国王本人，至少也是国王的摄政者和她的助手。”

让我们进入“思想泡泡”环节。
1654年，路易十四15岁时正式加冕为国王，随着他逐渐长大，他紧迫的任务变成了管理他的王国，筹集资金，并让他的臣民忠诚于他。
他的高明之处在于，**用奢华壮观的宫廷生活, 转移了贵族们的注意力，**实际上也转移了法国相当一部分人的注意力，就像父母可能会用，比如说，一个iPad来转移一个一直不开心的孩子的注意力一样。
但是路易的宫廷生活可比，我不知道，现在孩子们喜欢的东西，比如抖音（TikTok），更有吸引力。

在17世纪60年代，国王开始将他的政府, 从巴黎的动荡中转移出来，他把巴黎郊外凡尔赛（Versailles）的一个狩猎小屋改造成了当时欧洲最壮观的宫殿建筑群。
17世纪80年代，*当宫廷迁至凡尔赛时，这里能容纳约1.5万人，另外还有数千人住在许多相邻的建筑里，这些建筑是为仆人们, 以及为路易的情妇们建造的小城堡。*

贵族们忙于侍奉国王和王后，以及照顾君主们的合法子女和众多私生子。
他们也在为提升自己的地位而绞尽脑汁。
其中最高的荣誉之一就是在晚上给国王递睡衣，或者监督国王使用便桶。

国王还赞助，有时甚至亲自参与壮观的歌剧、音乐会和戏剧表演，以彰显他的伟大和权力。
而贵族们则表现得好像国王实际上拥有超越凡人的力量，从而为这一景象增添了色彩。
*国王就像一颗明亮的太阳，他的存在温暖着所有受他恩泽的人，事实上，这就是为什么路易十四被称为太阳王。*

感谢“思想泡泡”！

*#在专制主义时代，欧洲的君主们都接受了这样一种观念，即他们拥有神授的权力, 来进行绝对统治 (君权神授)。#*

雅克-贝尼涅·博絮埃主教（Bishop Jacques-Bénigne Bossuet）在凡尔赛的皇家礼拜堂布道时说：“是上帝确立了国王的地位……他将王权赋予大卫家族，并命令他让自己的儿子所罗门接替他的王位……因此，王子们是上帝的使者。”
他继续说道：“这就是为什么我们看到，国王的宝座不是凡人的宝座，而是上帝自己的宝座。”
在他看来，“上帝在王子们身上赋予了某种神圣的东西。”
事实上，博絮埃坚持认为，“王子们就是神。”

国王的神性, 使得他的政权可以免受专制或无政府状态的暴政，因为无论他做什么都必然是正确的。

*路易十四可能从未说过那句最常被认为是他说的话：“L'état, c'est moi”，也就是“朕即国家”，但这句话能流传下来是有原因的。*
他确实代表着国家的权力和权威，即使他从未说过这句话，他也有这样的感觉。

但"神授君权"理论, 也意味着宗教上的一致(独尊天主教, 罢黜新教)。
**路易十四认为, 他的王国中存在"新教徒"是混乱和有罪的，这导致他在1685年废除了《南特敕令》（Edict of Nantes）。随后，成千上万的新教徒逃离法国，**他们带着自己的技能和成功的生意前往荷兰、德意志各邦、北美、南非和其他地方。

尽管路易政权表面上华丽壮观，但它的运作在很大程度上得益于有能力的官僚，包括总督（intendants，如果我假装会说法语的话），他们的职责被规范化，负责监督税收和王国各个地区的行政管理。

在路易十四的所有官员中，最杰出和最重要的是让-巴蒂斯特·柯尔贝尔（Jean-Baptiste Colbert），他负责监管财政和公共工程等事务。
尽管柯尔贝尔出身中产阶级，但他推动了王国的经济发展，包括商人、造船工人和工匠。
柯尔贝尔还监督了法国在北美的扩张，派出了定居者和官员。 +
*商人们在北美大陆上搜寻在小冰期的严寒中急需的毛皮，这些毛皮当时需求量很大。*

*柯尔贝尔最为人所知的是他对"重商主义"（mercantilism）的支持，#重商主义是一种将经济发展和贸易, 视为类似于战争的政策。
重商主义思想家认为，世界上的财富是有限的——数量是固定的。
在这样一个零和世界里，一个王国获胜的唯一途径, 就是让其他王国失败 (即零和博弈)。#*
我们现在知道这是不正确的 (外贸能使各国都获益)，但"重商主义"在当时是政策和外交关系的重要驱动力。

*这种理论有很多应用：例如，拒绝其他王国的船只进入，或者对竞争对手的商品征收高额关税。*
我们可以在棉纺织品上看到这样一个例子，棉纺织品非常受欢迎，但欧洲人不知道如何生产如此鲜艳且耐洗的织物，所以在法国，棉纺织品被禁止生产和销售 (*让外国从法国人身上赚不到钱, 相当于法国对外国进行了高关税*)。
然而，走私活动却十分猖獗，男女都穿着棉布衣服，甚至高级官员也会非法带入。
在生活的这个方面以及其他方面，人们确实会违抗专制统治的规定。

尽管如此，路易十四仍然拥有很大的权力，包括发动战争的权力。
他发动了四次主要战争：第一次是遗产战争（War of Devolution），法国在北方获得了领土；第二次是法荷战争（Dutch War），法国在北方和东部边境获得了更多土地；第三次是奥格斯堡联盟战争（War of the League of Augsburg），在这场战争中，他失去了在法荷战争中获得的大部分土地；第四次是西班牙王位继承战争（War of the Spanish Succession），这次又遭受了重大损失，包括这次在加拿大的领土输给了英国，你可能没想到英国会卷入西班牙王位继承战争，但在17世纪的欧洲，每个人都想参与战争。

很明显，*#就像理想的"真人秀"参赛者一样，路易十四不是来交朋友的。#*
但通过这场无休止的战争中的领土交换，我们可以看到，一种零和的、“只有你输, 我才能赢”的世界观最终会耗尽资源，而不是扩大资源。

在他统治结束时，专制统治的理念受到了质疑。
一位英国评论家称, 专制统治下的法国是“一个充满疖子、伤口和腐疮的国家”。
*流亡的胡格诺派（Huguenots）称, 路易统治下的法国人是“奴隶”，他的统治只是“为了满足他的野心和复仇欲望”。*

同样，满足自己的野心和复仇欲望, 能让你成为一个优秀的真人秀参赛者，但不一定能成为一个完美的国王。
所以，*专制主义可以被看作是一种暴政，它基于"君主神权"的政治理论，要求在宗教、经济和社会方面保持一致(专职独裁)。* +
为了建立**这种对王权的尊崇体系，**在税收和战争中的生命损失方面付出了巨大的代价，而且**这极大地削弱了法国民众的权力。**

但话说回来，*英国出现的一种名为"立宪主义"（constitutionalism）的"权力分享"政治制度，虽然确实确立了某些"人权观念"，但它的兴起也并非不那么暴力。*

感谢观看。
下次再见。

感谢观看《速成欧洲史》，本片由这些优秀的人士制作，并在印第安纳波利斯的贾登·史密斯工作室（Jaden Smith Studio）拍摄。
我们的动画制作团队是Thought Cafe。
我们还有很多其他的《速成课程》。
你想学习天文学吗？
还是计算机科学？
我们都能满足你！
再次感谢观看，别忘了保持优秀！

'''

== pure

Hi, I'm John Green, and this is Crash Course European History.

So today we're moving into the second half of the 17th century.

The 30 Years War has ended with the Treaty of Westphalia, and the Scientific Revolution is producing amazing new universal laws, but life is still pretty terrible for the vast majority of people.

For Kings though, things were changing with the advent of absolutism, in which the king is said to have a divine right to the throne.

And the divinest divine right monarch of them all, Louis XIV, led Western Europe's most powerful Kingdom for more than 70 years.

So this is a portrait of Louis XIV -- the French Sun King, painted when he was 63.

Louis XIV looks regal in his massive black wig and swaths of ermine, embellished with fleurs-de-lis, the symbol of the former French royal house.

His high heels show off his shapely legs in white hose, demonstrating the king's perfection.

Men's legs garbed in tightly fitted stockings were a key indication of desirability at the time, and while he may not appear super masculine to us, Louis XIV was the model of powerful kingship and indeed absolute power.

Louis was four years old when he started his reign in 1643, while Europe was attempting to pull itself out of the 30 Years War.

Earlier, under Louis's father, Louis XIII, rebellions abounded in the hundreds across the kingdom because of increasingly heavy taxation to pay for the war and the famine conditions due to the relentless little ice age.

It seemed almost unthinkable to ordinary people that the king would betray his subjects with rising taxes in a time of famine.

So instead, they usually blamed tax collectors and local officials, not the king.

After Louis XIII died, his four-year-old son was a smidge small for France ruling, so the job was taken over by his regent, his mother, Anne of Austria, with help from her sidekick and rumored lover, the Italian-born Cardinal Mazarin.

The first years of Anne's Regency were the last years of the 30 Years War, and she increased French military deployments even amid all these protests, with the simple and eventually successful goal of defeating the Spanish and Austrian Habsburgs to gain more territory.

Alongside increasing the desperation of ordinary people, this constant warfare stretched aristocratic resources because Nobles raised and paid for their own armies in wartime.

Louis's mother had to move him several times to keep him safe amid protests from peasants and nobility alike, some of whom even went to the point of plotting coups d'état, which is, after all, a French phrase.

The Pieds-Nus -- or barefooted ones, the Croquants -- or crunchers or crispies, and even judges of Paris were among the people resisting.

One judge listed the sacrifices of ordinary people, such as selling all their furniture and sleeping on straw in order to pay rising taxes.

He said, to maintain the luxury of Paris, millions of innocent souls are obliged to live on black bread and oats.

Did the center of the world just open?

Is there a pumpernickel bagel in there?

It's the closest we could get to black bread.

Now, this is a properly great bagel.

Hmm.

I'm gonna eat that whole thing once this is done.

But black bread in 17th century France... not good.

For one thing, it was often cut with sawdust, which, you know, isn't ideal for bread making and also isn't ideal for nutrition.

In fact, our contemporary bread is so good that it's hard for us to imagine just how difficult the circumstances were in the 17th century.

Like, just how desperate you have to be to add sawdust to your dough.

So we're gonna jump back in time for a bit.

Earlier in the 17th century, a group of judges managed to undermine the monarchy, if only temporarily.

You'll recall that France ended their religious civil war with Henry, Paris's well-worth amassed the fourth ruling.

Henry was Louis XIV's grandfather, and to pay for ongoing wars, Henry raised a new tax called the Paulette that was paid by government officials, including judges, over a nine-year period.

And if you paid the Paulette, you could keep your job for life or even sell your job to a successor, and this created a powerful class of bureaucrats who were basically immune from state oversight.

But Henry couldn't afford to get rid of the Paulette because he needed the cash to wage wars.

The officials who bought their positions came to be known as the nobles of the robe, as opposed to the old-school nobles, who were called the nobles of the sword because they'd gotten their status via military service to the king.

Flash forward a few decades.

Anne of Austria and Cardinal Mazarin are trying to throw these nobles of the robe out of office, which the new nobles are, of course, not keen on, leading them to threaten to arrest them.

I mean, after all, they'd paid a lot of money for those robes.

All of this pushed the people of Paris to their most menacing protests until the monarchy backed down and released the judges that they had imprisoned.

And this triumph over the monarchy made the nobility of the robe a force to be reckoned with and also indicated that maybe the absolute power of the monarchy wasn't actually that absolute.

Alongside these protesters, another contender for influence arose.

A new Catholic movement, Jansenism, called for a complete purging of the self and a fervent spirituality to replace the insufficient and even deluded practices of the church.

Like, for instance, being a cardinal who is probably hooking up with the king's mom.

The Jansenists believed only intense and full religious commitment could pull France from its dire straits, and they menaced established authority.

But the most threatening uprising was the Fronde, a series of opposition movements between 1648 and 1653, in which the old nobility and the courts were like, "You can't just raise our taxes willy-nilly without asking permission," and Anne of Austria was like, "Of course we can.

It's a kingdom, and we are, well, if not exactly the king, at least the king's regent and her sidekick."

Let's go to the Thought Bubble.

Louis XIV was officially crowned king in 1654 when he was 15, and as he grew older, his urgent task became organizing the administration of his kingdom, raising funds, and uniting his subjects in loyalty to him.

Part of his brilliance was to divert the nobility and, in fact, a good part of France with a spectacular court life, rather how a parent might divert a relentless unhappy child with, say, an iPad.

But Louie's court was even more diverting than, I don't know, what kids like?

TikTok?

In the 1660s, the king began the task of removing his government from the tumult of Paris by converting a hunting lodge at Versailles outside of Paris into the most spectacular European palace complex of its day.

It housed some 15,000 people when the court moved there in the 1680s, and further thousands in the many adjacent buildings for servants and smaller chateaus built for Louis's mistresses.

The nobility was kept busy attending to the king and queen, as well as serving the monarchs' legitimate and many illegitimate children.

They also outdid themselves in maneuvering for status.

One of the highest honors being to hand the king his nightshirt in the evening or to oversee his use of the commode.

The king also sponsored and sometimes starred in spectacular operas and concerts and plays to add to the feeling of his greatness and power.

While the nobility enhanced the scene by behaving as if the king were, in fact, more than humanly powerful.

It was almost like the king was a bright sun whose presence warmed all those it graced, and indeed, that's why Louis XIV came to be known as the Sun King.

Thanks, Thought Bubble!

In the days of absolutism, monarchs across Europe embraced the idea that they had the divine right to their absolute rule.

The Bishop Jacques-Bénigne Bossuet preached in the royal chapel of Versailles that, quote, "It is God who establishes kings...

He vested royalty in the House of David, and ordered him to cause Solomon, his son, to reign in his place...

Princes thus act as ministers of God."

He continued, "This is why we have seen that the royal throne is not the throne of a man, but the throne of God himself."

To his mind, "God has placed in princes something divine."

And in fact, Bossuet maintained, "Princes are gods."

The king's divinity allowed for his regime to be free from arbitrariness or the tyranny of anarchy because whatever he did was necessarily correct.

Louis XIV probably never said the line most famously attributed to him, "L'état, c'est moi," or "The state is me," but it has endured for a reason.

He really was the state's power and authority, and he felt that even if he never said it.

But Divine Right theory also meant religious conformity.

Louis XIV viewed the presence of Protestants in his realm as disorderly and sinful, causing him to revoke the Edict of Nantes in 1685.

Thousands of Protestants then fled France, taking their skills and successful businesses to the Netherlands, the German states, North America, South Africa, and other places.

And for all the surface grandeur of Louis's regime, it worked mostly because of accomplished bureaucrats, including the intendants -- or intendants, if I'm pretending to be able to pronounce French -- whose jobs were regularized to oversee tax collections and the administrations of the various regions of the kingdom.

The most prominent and important of all Louis's officials was Jean-Baptiste Colbert, who oversaw finances and public works, among other things.

Despite being of middle-class birth, Colbert drove the kingdom's economy, including its merchants, shipbuilders, and artisans.

Colbert also oversaw French expansion into North America, sending out settlers and officials.

Traders combed the continent for the desperately needed furs that were in high demand during the intense cold of the Little Ice Age.

Colbert is most famous for his support of mercantilism, a policy that saw economic development and trade as akin to war.

Mercantilist thinkers believed that there was only so much wealth in the world -- a finite and fixed amount.

And in such a zero-sum world, the only way for one kingdom to win would be for other kingdoms to lose.

We now know this isn't true, but mercantilism was an important driver of policy and foreign relations at the time.

There were many applications of this theory: refusing entry of another kingdom's ships, for instance, or enacting high tariffs on competitors' goods.

We can see one example of this in cotton textiles, which were wildly popular, but Europeans had no idea how to produce such lively and washable fabrics, so they were outlawed in France.

Smuggling, however, thrived, with women and men alike wearing cotton and even high officials bringing them in illegally.

In this and other areas of life, people did disobey absolutist rules.

Still, Louis had a lot of power, including the power to wage war.

He waged four major ones: first, the War of Devolution, in which France gained territory in the north; second, the Dutch War, which gained additional land to the north and along the eastern border; third, the War of the League of Augsburg, in which he lost much of the land won in the Dutch War; and fourth, the War of the Spanish Succession, again with significant losses, including in Canada this time to Britain, who you might not have expected to be mixed up in the Spanish War of Succession, but everyone wanted in on warring in 17th century Europe.

Clearly, like the ideal reality TV contestant, Louis was not there to make friends.

But we can see through this exchange of lands through endless war how a zero-sum, "I can only win if you lose" worldview ends up exhausting resources rather than expanding them.

By the end of his reign, the idea of absolutist rule was being thrown into question.

An English critic called absolutist France a "state full of boils and wounds and putrid sores."

Exiled Huguenots called the French under Louis "slaves," his rule directed only "to satisfy both his ambition and his vengeance."

Again, satisfying one's ambition and one's vengeance makes you a great reality TV contestant, but maybe not necessarily the perfect king.

So absolutism can be seen as a form of tyrannical rule, demanding religious, economic, and social conformity based on a political theory of monarchical divinity.

It cost huge amounts in taxation and loss of life in wars to create this system of civility to royal power, and it was pretty disempowering to the French public.

But then again, the rise of a political system of power-sharing in England called constitutionalism wasn't really less violent, although it did enshrine certain ideas about human rights.

Thanks for watching.

I'll see you next time.

Thanks for watching Crash Course European History, which is made by all these nice people and filmed here in the Jaden Smith Studio in Indianapolis.

Our animators are Thought Cafe.

We have lots more Crash Course available.

You want to learn about astronomy?

Computer science?

We've got you covered!

Thanks again for watching, and don't forget to be awesome!

'''