= 024 - The Congress of Vienna
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义


Hi, I'm John Green, and this is Crash Course European History.

So how did Europe restore 恢复 order after the social and political upheaval 动荡；剧变 of the French Revolution and the Napoleonic regime 政权?

Well, European leaders got together and set up a committee -- or a "Congress" 代表大会 -- that met in Vienna 维也纳 to set things straight 整顿局面.

It's a great town, Vienna.

Great sausages 香肠.

I went there once.

Lots of skeletons 骷髅 under the city.

Freaked me out 使我吓坏了 pretty bad.

What are we talking about?

Right, the Congress of Vienna 维也纳会议.

So, when Europe looked around at the previous century with its endless wars, the reign of reason 理性时代 seemed disastrous 灾难性的, and so Europe turned to its past, and a conservatism 保守主义 that embraced 拥护 monarchies 君主制 and romanticism 浪漫主义.

They believed that Enlightenment 启蒙运动 ideas, like the support of individual rights 个人权利, had caused too much turmoil 混乱 and misery 苦难, and so they wanted to go back to simpler times -- when kings were kings, peasants 农民 were landless 无地的, and obedience 服从 mattered more than thinking.


[Intro]

So, even as Napoleon was on his way back to the continent in 1815 to retake 重新夺回 his empire, the Congress of Vienna had been meeting to restore stability 稳定.

Its members included representatives from Russia, the Habsburg Empire 哈布斯堡帝国, Prussia 普鲁士, Britain, and France, which though defeated was central to discussions of how to return to the old order 旧秩序.

The first step was to bring back the French royal family, starting with the executed 被处决的 king's brother, Louis XVIII 路易十八, who was known as "the desired" because presumably 大概；可能 that was the only way to get him to take the job that killed his brother.

Like you're desired.

We want you!

We're not gonna guillotine 用断头台处决 you.

The second step was to balance out 平衡 great power interests 大国利益.

This meant ensuring that France was no longer a menace 威胁 and that no state felt aggrieved 愤愤不平的 enough to start another war.

A major player at the Congress was, oddly enough 奇怪的是, a once-leading minister of Napoleon: Charles Maurice de Talleyrand-Périgord 夏尔·莫里斯·德塔列朗 - 佩里戈尔.

Ga, that was great.

In the bajillion years since I graduated high school, my high school French teacher has died, and that is very sad.

But at the same time, I'm glad she is not here to hear me speak French.

So, during Napoleon's reign 统治, Talleyrand had been a relentless 不知疲倦的 womanizer 花花公子 and also a relentless seeker of bribes 贿赂.

Like a lot of people who succeed in politics, he was mostly a moth 飞蛾 that flew toward the lights of power and influence.

With Napoleon's defeats, Talleyrand switched sides 改变立场 to support Louis XVIII, and was just the kind of well-connected 人脉广的 wheeler-dealer 精明的商人 the Congress needed.

The Congress's initial ideas for a settlement 和解 with France involved basically leaving France and its restored monarch 君主 alone to enjoy a good number of the revolutionary conquests 革命成果.

But those moderate 温和的 terms 条件 became harsh 苛刻的 when Napoleon returned to France in the spring of 1815 to much acclaim 欢呼 from many of his French followers, including especially veterans 退伍军人 of his army.

After Napoleon and his forces were defeated at Waterloo 滑铁卢 in June of 1815, the Allies 同盟国 imposed an indemnity 赔款, meaning France would be responsible for some of the losses they caused.

And the Allies decided that they would occupy 占领 France until that indemnity was paid.

The presiding spirit 主导精神 over the Congress and its negotiations 谈判 was the Austrian minister Prince Klemens von Metternich 克莱门斯·冯·梅特涅亲王.

Through his arch-conservative 极端保守的 eyes, there was a lot to worry about.

One concern was the resurgence 复苏 of revolution, a possibility he worked to prevent through the use of secret police 秘密警察, spies 间谍, and censorship 审查制度.

But for him, stopping revolution also entailed 意味着 closing down 关闭 student fraternities 学生社团 as breeding grounds 滋生地 for liberal ideas 自由主义思想.

Basically, attempts to restore rights, freedom, or achieve any part of the liberal program 自由主义计划 of the revolutionaries were seen as criminal 犯罪的.

Metternich was also concerned about Russia, which was now the strongest continental power 大陆强国, and he wanted to prevent its further expansionism 扩张主义.

He felt a strong monarchy in France would help make France powerful enough to check 遏制 the power of Russia, thereby bring Europe into sociopolitical balance 社会政治平衡.

Did the center of the world just open?

Is there Jenga 叠叠乐 in there?

So, you're gonna hear this phrase balance of powers 权力平衡 a lot in the next 200 years.

The idea is that if we can just distribute 分配 power among communities, the way that we distribute the load of Jenga pieces...even if something goes wrong, the thing doesn't fall.

It's worked great for 200 years.

What's that?

Oh gosh, Stan says that there's a World War I coming.

The Congress also divvied up 瓜分 available territories 领土 and resources.

Britain received some of France's territory in the Indian Ocean and the Caribbean 加勒比海, for instance, while Prussia was allocated 分配 part of Saxony 萨克森 and Austria was given Italian and other territory.

There was also the leftover 剩余的 question of Poland; so, remnants 残余部分 of the Duchy of Warsaw state 华沙公国 fell to Russian control, with the remaining pieces going to Prussia and Austria.

Basically, the Congress of Vienna settlement had something for everyone.

Except for the Poles 波兰人.

We're beginning the "This was good news for everyone except for the Poles" period of European history, which ends -- when did it end, Stan? in 1991.

In terms of international politics 国际政治, the Congress's major achievements were twofold 双重的.

First, the Congress aimed for a "balance of power," which would guide European international developments for decades to come, and eventually provide a model for 20th century geopolitics 地缘政治 as well.

We see this emphasis on "balance" in the tradeoffs 权衡 and parceling out 分配 of benefits, but also in the general attitudes of great power leaders.

So in addition to working toward the balance of powers, the Congress established a "congress" system for arriving at agreements 达成协议 and enforcing 执行 them.

And this would become very important.

For one thing, it helped change the way we understand how people come into power 掌权.

Like, the Congress did not imagine kingship 君主制 as deriving from 源自 divine power 神权 but instead from the decision making of the combined "great powers."

And the group acted with one voice 一致行动, arriving at common policies 共同政策, which was key to their strength.

This system is often called the "Concert of Europe" 欧洲协调, and in some ways it did presage 预示 the contemporary European Union 当代欧盟.

Besides establishing the conditions for peacetime 和平时期, thinkers across Europe were devising 构思 political theory 政治理论 for this post-revolutionary age 后革命时代.

Leading politicians embraced Edmund Burke's theory of conservatism 保守主义理论, for instance, which emphasized tradition 传统 and the wisdom enshrined in 铭记于 institutions from the past.

Monarchy, according to conservatives 保守派, was the primary institution 主要制度 because it had endured 持续 for centuries so it provided age-old 古老的 political stability 政治稳定.

The aristocracy 贵族 also claimed an acquired superiority 获得的优越性 simply because of the long-lived leadership of its families.

In other words, the middle-classes 中产阶级, who promoted hard work and money-making skills, were no longer really models of capability 能力典范.

Instead, readers flocked to 涌向 Sir Walter Scott's tales of knights 骑士 from the past as testimonial 证明 to aristocratic bravery 贵族的勇敢 -- especially when they were defeating the citizen-led armies of Napoleon.

The chivalrous Middle Ages 侠义的中世纪 were reborn as a golden age...despite all that black death 黑死病, famine 饥荒, and schism 分裂 in the church.

It is truly astonishing 令人惊讶的 what humans can, with time, nostalgicize 使变得怀旧.

Religion 宗教 emerged as another part of the old regime 旧政权 that needed to be restored.

In tandem with 与…同时 the other terms of the political settlement 政治解决方案, Russia, Prussia, and Austria agreed among themselves to a Holy Alliance 神圣同盟.

This alliance 联盟 would promote religious values 宗教价值观 and support diverse Christian religions 基督教教派 of the three kingdoms, and also emphasize the importance of good old fashioned Christian obedience to the church, no matter which church it is, just please be obedient to it.

At the same time, religious activism 宗教行动主义 renewed focus on philanthropy 慈善事业.

Aristocratic Catholics 天主教贵族 in France, for example, called themselves "socialists" 社会主义者 because they were concerned that the strong emphasis on individualism 个人主义 had resulted in the deterioration 恶化 of community and society.

Now, they were unrelated to the Marxist "socialists" 马克思主义社会主义者 who would later preach about revolution 鼓吹革命.

These French "socialists" raised money to aid the poor in their towns and city centers.

In Protestant countries 新教国家, religion made a comeback 卷土重来 as part of a second Great Awakening 第二次大觉醒.

Like the First, it emphasized religious feeling 宗教情感 instead of strict theological learning 严格的神学学习.

In Britain, Methodist churches 卫理公会教堂 sprang up 涌现, shunning 避开 the fancy ceremonials 华丽的仪式 and religious hierarchies 宗教等级制度 of Anglicanism 英国国教.

Instead of bowing to 向…鞠躬 archbishops 大主教 and British aristocrats 英国贵族, they worshipped among their own kind in a spirit of democracy 民主精神.

Another result of conservatism 保守主义 was a new rationale 理论依据 for allegiance to 忠诚于 a kingdom or state.

Conservatives didn't promote constitutions 宪法 and the rule of law 法治, like the French and U.S. revolutionaries did with their Enlightenment-inspired governing structures 受启蒙运动启发的治理结构.

Instead, they saw nations as stemming from 源于 historical evolution 历史演变 of noble families 贵族家庭, a common language 共同语言, and common heritage 共同遗产.

They collected folk tales 民间故事 and artifacts 文物 from the past, considered to be central to a kingdom's heritage.

The way things had always been done was the way they should be done in the present and future.

These ideas brought about clashes 冲突 within nations between the agrarian interests 农业利益 of the landed aristocracy 土地贵族 and the budding wealth 新兴财富 of urban industrialists 城市工业家 and financiers 金融家.

Industrialists often wanted progressive change 进步性变革, such as infrastructure 基础设施 that would support their businesses, while landed aristocrats wanted to ensure that traditional hierarchies 传统等级制度 would not be disturbed, on account of 因为 how they benefited from them.


Let's go to the Thought Bubble.

There was another new idea dominating the post-revolutionary era:
the culture of Romanticism 浪漫主义文化, which replaced the culture of Enlightenment 启蒙运动文化.

Romanticism held that the world of feeling 情感世界 was far superior to 远优于 the regime of reason 理性统治;
that nature 自然 was superior to manufacturing 制造业;
and that the past was better than the present.

Mary Shelley 玛丽·雪莱 was the daughter of Mary Wollstonecraft 玛丽·沃斯通克拉夫特.

And you'll recall, in A Vindication of the Rights of Woman 《女权辩护》, Wollstonecraft emphasized the need for knowledge and reason in people's lives.

But her daughter's novel Frankenstein 《弗兰肯斯坦》 took the opposite stance 立场, in some ways.

It's a story, in part about what can be wrought 造成 by reason run amok 失控的理性.

Although the monster had many abilities, it lacked human love and warmth 爱与温暖,
so it ended up killing those who had loved and been kind to him.

For Shelley, the lack of feeling -- not the lack of reason -- lay at the heart of social problems 社会问题的核心.

And unchecked reason 不受约束的理性, like that of Dr. Frankenstein, created monstrosities 怪物.

Meanwhile Russian poet Alexander Pushkin 亚历山大·普希金 wrote the novel Eugene Onegin 《叶甫盖尼·奥涅金》 in the kind of romantic, flowery verse 华丽的诗句
that stands in stark contrast to 与…形成鲜明对比 the cold and rational exposition 冷静理性的阐述 of Enlightenment novelists like Voltaire 伏尔泰.

Eugene Onegin tells the story of a tragically ill-timed romance 悲剧性的不合时宜的爱情 between Onegin and Tatyana
as the two attempt to navigate paths 探索道路 between strong emotion 强烈情感 and the traditions of Russian courtship 俄罗斯求爱传统.

It's remembered today in part because it explores the paradoxes 悖论 of romantic thinking without dismissing any perspective 不否定任何观点.

Indeed, Pushkin himself followed at least one of the conventions 惯例 of traditional male honor 传统男性荣誉 in his own life:
He died in a duel 决斗 with his wife's purported lover 据称的情人.


Thanks Thought Bubble.

Not only did Romantic poets write about nature, they also invoked 唤起 foreign lands 异国 and exoticism 异国情调 -- an exoticism that was earlier expressed in material goods like textiles 纺织品, porcelain 瓷器, umbrellas 雨伞, and coffee.

Painters depicted 描绘 nude women 裸女 in harems 后宫 (even though none had ever entered a harem much less seen a nude woman in one).

And Samuel Coleridge 塞缪尔·柯勒律治 wrote in "Kubla Khan" 《忽必烈汗》 of an opium dream 鸦片引发的梦 in which he is mystically transported to 神秘地被传送到 another time and place.

Percy Bysshe Shelley 珀西·比希·雪莱, husband of Mary Shelley, wrote of distant Asia 遥远的亚洲.

Still others, escaping harsh reality 逃避残酷现实, composed odes 颂歌 to poppies 罂粟, from which opium is derived 提取.

Sir Walter Scott, like other novelists, wrote about the Middle Ages, but he too reached romantic intensity 浪漫的强烈程度 in part because of his opium addiction 鸦片成瘾.

The highs and lows of existence 生存的起起落落, raging storms 狂风暴雨, extreme suffering 极度痛苦, foreboding moods 不祥的情绪, all characterized the desire to turn Enlightenment rationality 启蒙运动的理性 upside down 颠倒 with intense emotion 强烈情感 -- or even to personally escape from that hyper-reasoned reality 过度理性的现实.

Musicians also conveyed 传达 romantic highs and lows.

They did this by juxtaposing 并列 thundering choruses 雷鸣般的合唱 with more tender passages 更柔和的段落.

Composer Ludwig von Beethoven 路德维希·凡·贝多芬, the extremely intense fellow behind me, excelled at 擅长 creating these types of musical contrasts 音乐对比.

The crisp and disciplined compositions 简洁严谨的作品 of Enlightenment musicians were gone.

Individualism 个人主义, which had not really entered the eighteenth century Enlightenment world until Rousseau 卢梭 wrote of his individual emotions 个人情感, also figured in 出现在 post-revolutionary thought 后革命思想.

Romantic individualism 浪漫主义个人主义 emphasized poetic or other forms of genius 天赋.

Like, during the Enlightenment and revolutionary years, individual rights and liberties 个人权利和自由 for everyone dominated debates 主导辩论.

But in the post-revolutionary era, both history and fiction began to look at -- and in a way worship -- the individual Great Man 伟人.

These great individuals -- who tended to be cleaned up military stars 被美化的军事明星 -- were seen to be the central drivers of historical change 历史变革的核心驱动力 and the individuals at the center of every great tale 伟大故事的核心人物, whether fiction or not.

And this still shapes our way of looking at history and other stories -- while almost all inventions, for instance, are the result of broad and complex networks of collaborators 合作者, we still tend to put individuals at the center of those stories, whether it's Edison and his light bulb 爱迪生和他的电灯泡 or Napoleon and his army.

But try as they might, leaders at the Congress of Vienna and a cultural emphasis on conservatism could not quash 镇压 the revolutionary spirit 革命精神, especially the spirit embodied by 体现的 the idea that people were citizens of a community, rather than subjects of a king.

And amid all these political changes, a different revolution was shaking the economic status quo 经济现状 so dramatically that old ways of thinking about peasants and land and aristocrats would soon prove untenable 站不住脚的.

The nature of work and life were profoundly reshaped 深刻重塑 by the Industrial Revolution 工业革命.

In France in 1780, somewhere around 60% of people worked in agriculture 农业.

200 years later, in 1980, only 8% did.

The Industrial Revolution will change how we spend our days, how we relate to one another and to the world, what we value, and in some ways, who we are.

That's next time.

I'll see you then.

'''


== 中文翻译

大家好，我是约翰·格林，这里是《速成欧洲史》。 +

那么，在经历了法国大革命（French Revolution）和拿破仑政权（Napoleonic regime）带来的社会与政治动荡之后，欧洲是如何恢复秩序的呢？ +

嗯，欧洲各国领导人聚在一起，成立了一个委员会——或者说是“会议”——在维也纳（Vienna）召开会议来整顿局面。 +

维也纳是个很棒的城市。 +
那里的香肠很美味。 +
我去过一次。 +
城市地下有很多骷髅。 +
可把我吓坏了。 +
我们刚才在说什么来着？ +
对，维也纳会议（Congress of Vienna）。 +

所以，当欧洲回顾过去的一个世纪，看到那些无休止的战争时，理性时代似乎带来了灾难，于是欧洲开始回望过去，转向一种拥护君主制（monarchies）和浪漫主义（romanticism）的保守主义（conservatism）。 +
他们认为，启蒙运动（Enlightenment）的思想，比如对个人权利的支持，已经引发了太多的动荡和苦难，所以他们想要回到更简单的时代——那时国王就是国王，农民没有土地，服从比思考更重要。 +

[开场介绍] +

所以，就在1815年拿破仑（Napoleon）返回欧洲大陆，试图夺回他的帝国之际，维也纳会议已经在召开，旨在恢复稳定。 +
会议成员包括来自俄罗斯（Russia）、哈布斯堡帝国（Habsburg Empire）、普鲁士（Prussia）、英国（Britain）和法国（France）的代表，尽管法国战败了，但在讨论如何恢复旧秩序的问题上，它是核心参与者。 +
第一步是迎回法国王室成员，从被处决的国王的弟弟路易十八（Louis XVIII）开始，他被称为“被渴望的人”，大概是因为只有这样说，才能让他接受这份曾经害死他哥哥的工作。 +
就像“我们渴望你。 +
我们需要你！ +
我们不会把你送上断头台的。” +

第二步是平衡大国利益。 +
这意味着要确保法国不再构成威胁，并且没有哪个国家会感到受委屈到要发动另一场战争。 +
在这次会议上，一个重要人物很奇怪，他曾是拿破仑的一位主要大臣：夏尔·莫里斯·德·塔列朗-佩里戈尔（Charles Maurice de Talleyrand-Périgord）。 +
嗐，太棒了。 +
自从我高中毕业这么多年来，我的高中法语老师已经去世了，这真的很让人难过。 +
但与此同时，我也很高兴她不在这里听到我说法语。 +

所以，在拿破仑统治时期，塔列朗是个无情的好色之徒，同时也是个不停地索贿的人。 +
就像很多在政治上取得成功的人一样，他就像一只飞蛾，总是朝着权力和影响力的光芒飞去。 +
随着拿破仑的失败，塔列朗转而支持路易十八，而且他正是维也纳会议所需要的那种人脉广泛、善于投机钻营的人。 +
会议最初关于与法国达成和解的想法基本上是让法国及其恢复统治的君主独自享有大量革命时期征服的成果。 +
但当1815年春天拿破仑回到法国，受到他的许多法国追随者，尤其是他军队中的退伍军人的热烈欢迎时，那些温和的条件就变得苛刻起来。 +
1815年6月拿破仑及其军队在滑铁卢（Waterloo）战败后，同盟国要求法国支付赔款，这意味着法国要为他们所造成的一些损失负责。 +
而且同盟国决定，在赔款付清之前，他们将占领法国。 +

主持维也纳会议及其谈判的灵魂人物是奥地利大臣克莱门斯·冯·梅特涅亲王（Prince Klemens von Metternich）。 +
在他极端保守的眼光看来，有很多令人担忧的事情。 +
其中一个担忧是革命的再次兴起，他通过使用秘密警察、间谍和审查制度来努力阻止这种可能性。 +
但对他来说，阻止革命还意味着要关闭学生联谊会，因为他认为这些联谊会是自由主义思想的滋生地。 +
基本上，任何试图恢复权利、自由，或者实现革命者自由主义纲领的任何一部分的尝试，都被视为犯罪行为。 +
梅特涅也很担心俄罗斯，因为俄罗斯现在是欧洲大陆最强大的国家，他想阻止俄罗斯进一步的扩张主义。 +
他认为，法国强大的君主制将有助于使法国强大到足以制衡俄罗斯的力量，从而使欧洲实现社会政治平衡。 +

世界的中心刚刚打开了吗？ +
里面有叠叠乐（Jenga）吗？ +

所以，在接下来的200年里，你会经常听到“权力平衡”（balance of powers）这个词。 +
这个概念是说，如果我们能像分配叠叠乐积木的重量那样，在各个群体之间分配权力……即使出了什么问题，整个体系也不会崩溃。 +
这在200年里一直运作得很好。 +
什么？ +
哦，天哪，斯坦说第一次世界大战（World War I）要来了。 +

维也纳会议还对现有的领土和资源进行了瓜分。 +
例如，英国获得了法国在印度洋（Indian Ocean）和加勒比地区（Caribbean）的一些领土，而普鲁士被分配到了萨克森（Saxony）的一部分，奥地利则得到了意大利（Italian）和其他一些领土。 +
还有波兰（Poland）的遗留问题；所以，华沙公国（Duchy of Warsaw）的残余部分落入了俄罗斯的控制之下，剩下的部分则归普鲁士和奥地利所有。 +
基本上，维也纳会议的解决方案对每个人都有好处。 +
除了波兰人。 +
我们开始进入欧洲历史上“除了波兰人，这对每个人都是好消息”的时期，这个时期结束于——它是什么时候结束的，斯坦？——1991年。 +

在国际政治方面，维也纳会议的主要成就有两个方面。 +
首先，会议旨在实现“权力平衡”，这将在未来几十年里指导欧洲的国际发展，最终也为20世纪的地缘政治提供了一个模式。 +
我们不仅在利益的权衡和分配中看到了对“平衡”的强调，在大国领导人的总体态度中也能看到这一点。 +
所以，除了致力于实现权力平衡之外，会议还建立了一个“会议”体系，用于达成协议并执行这些协议。 +
这将变得非常重要。 +
一方面，它有助于改变我们对人们如何掌权的理解。 +
比如，会议并不认为王权来自神授，而是来自各个“大国”共同的决策。 +
而且这个团体行动一致，达成共同的政策，这是他们力量的关键。 +
这个体系通常被称为“欧洲协调”（Concert of Europe），在某些方面，它确实预示了当代的欧盟（European Union）。 +

除了为和平时期奠定基础之外，欧洲各地的思想家们还在为这个后革命时代设计政治理论。 +
例如，主要的政治家们接受了埃德蒙·伯克（Edmund Burke）的保守主义理论，该理论强调传统以及过去的制度中所蕴含的智慧。 +
根据保守派的观点，君主制是首要的制度，因为它已经延续了几个世纪，所以它提供了古老的政治稳定性。 +
贵族阶层也声称，仅仅因为其家族长期的领导地位，他们就拥有一种后天获得的优越性。 +
换句话说，那些提倡努力工作和赚钱技能的中产阶级，不再是真正的能力典范。 +
相反，读者们纷纷涌向沃尔特·司各特爵士（Sir Walter Scott）关于过去骑士的故事，以此作为贵族勇敢精神的证明——尤其是当他们打败拿破仑的公民军队的时候。 +
充满侠义精神的中世纪（Middle Ages）被重新塑造为一个黄金时代……尽管当时有黑死病（black death）、饥荒和教会分裂（schism in the church）。 +
随着时间的推移，人类竟然能对这些事情产生怀旧情绪，这真的很令人惊讶。 +

宗教成为了旧政权中另一个需要恢复的部分。 +
与政治解决方案的其他条款相呼应，俄罗斯、普鲁士和奥地利相互之间达成了神圣同盟（Holy Alliance）。 +
这个同盟将促进宗教价值观，支持三个王国的不同基督教（Christian）教派，同时也强调传统的基督教徒对教会的服从的重要性，不管是哪个教会，只要服从就好。 +
与此同时，宗教活动重新将重点放在慈善事业上。 +
例如，法国的贵族天主教徒（Catholics）称自己为“社会主义者”（socialists），因为他们担心对个人主义的强烈强调导致了社区和社会的恶化。 +
现在，他们与后来宣扬革命的马克思主义（Marxist）“社会主义者”没有关系。 +
这些法国“社会主义者”筹集资金来帮助他们城镇和市中心的穷人。 +

在新教（Protestant）国家，宗教作为第二次大觉醒（Second Great Awakening）的一部分重新兴起。 +
和第一次大觉醒一样，它强调宗教情感，而不是严格的神学学习。 +
在英国，卫理公会教堂（Methodist churches）纷纷涌现，摒弃了英国国教（Anglicanism）华丽的仪式和宗教等级制度。 +
他们不再向大主教和英国贵族鞠躬，而是以民主的精神在自己的群体中进行崇拜。 +

保守主义的另一个结果是，人们对效忠一个王国或国家有了新的理由。 +
保守派不像法国和美国（U.S.）革命者那样，在他们受启蒙运动启发的治理结构中提倡宪法（constitutions）和法治（rule of law）。 +
相反，他们认为国家源于贵族家族的历史演变、共同的语言和共同的遗产。 +
他们收集过去的民间故事和文物，认为这些是一个王国遗产的核心。 +
过去一直以来的做事方式，就是现在和未来应该遵循的方式。 +
这些想法在各国国内引发了拥有土地的贵族的农业利益与新兴的城市工业家和金融家的财富之间的冲突。 +
工业家们常常希望进行渐进式的变革，比如建设能支持他们业务的基础设施，而拥有土地的贵族则希望确保传统的等级制度不会受到干扰，因为他们从这些制度中受益。 +

让我们进入“思想泡泡”环节。 +

还有另一个新思想主导了后革命时代： +
浪漫主义（Romanticism）文化，它取代了启蒙运动（Enlightenment）文化。 +
浪漫主义认为，情感世界远比理性时代优越； +
自然优于制造业； +
过去比现在更好。 +

玛丽·雪莱（Mary Shelley）是玛丽·沃斯通克拉夫特（Mary Wollstonecraft）的女儿。 +
你可能还记得，在《女权辩护》（A Vindication of the Rights of Woman）中，沃斯通克拉夫特强调了人们生活中对知识和理性的需求。 +
但她女儿的小说《科学怪人》（Frankenstein）在某些方面却持相反的立场。 +
这是一个部分讲述当理性失控时会造成什么后果的故事。 +
虽然那个怪物有很多能力，但它缺乏人类的爱和温暖， +
所以它最终杀死了那些爱他、对他好的人。 +
对雪莱来说，社会问题的核心在于缺乏情感——而不是缺乏理性。 +
而且不受约束的理性，就像弗兰肯斯坦博士（Dr. Frankenstein）那样，会创造出怪物。 +

与此同时，俄罗斯诗人亚历山大·普希金（Alexander Pushkin）用浪漫、华丽的诗句创作了小说《叶甫盖尼·奥涅金》（Eugene Onegin）， +
这与伏尔泰（Voltaire）等启蒙运动小说家冷静、理性的阐述形成了鲜明的对比。 +
《叶甫盖尼·奥涅金》讲述了奥涅金（Onegin）和塔季扬娜（Tatyana）之间一段悲剧性的、时机不当的浪漫爱情故事， +
他们两人试图在强烈的情感和俄罗斯求爱的传统之间找到出路。 +
这部小说在今天被人们记住，部分原因是它在不忽视任何观点的情况下，探讨了浪漫主义思维的矛盾之处。 +
事实上，普希金本人在自己的生活中至少遵循了传统男性荣誉的一个惯例： +
他在与他妻子所谓的情人的决斗中丧生。 +

感谢“思想泡泡”！ +

浪漫主义诗人不仅描写自然，他们还会提及异国他乡和异国情调——这种异国情调早些时候体现在纺织品、瓷器、雨伞和咖啡等商品上。 +
画家们描绘了后宫（harems）中的裸体女性（尽管他们中没有人真正进入过后宫，更不用说在后宫里看到过裸体女性了）。 +
塞缪尔·泰勒·柯勒律治（Samuel Coleridge）在《忽必烈汗》（“Kubla Khan”）中描写了一个鸦片引发的梦境，在梦中他神秘地被传送到了另一个时间和地点。 +
玛丽·雪莱的丈夫珀西·比希·雪莱（Percy Bysshe Shelley）写过关于遥远的亚洲（Asia）的作品。 +
还有一些人，为了逃避残酷的现实，创作了关于罂粟（poppies）的颂歌，而鸦片就是从罂粟中提取的。 +
沃尔特·司各特爵士和其他小说家一样，写过关于中世纪的作品，但他的作品也达到了浪漫主义的强烈程度，部分原因是他吸食鸦片成瘾。 +
生活中的起起落落、狂风暴雨、极度的痛苦、不祥的情绪，所有这些都体现了人们渴望用强烈的情感颠覆启蒙运动的理性——甚至是个人想要逃离那个过度理性的现实。 +

音乐家们也传达出了浪漫主义的高潮和低谷。 +
他们通过将雷鸣般的合唱与更温柔的乐段并置来做到这一点。 +
作曲家路德维希·凡·贝多芬（Ludwig von Beethoven），就是我身后这位极其热情的人，擅长创造这类音乐对比。 +
启蒙运动时期音乐家们简洁、严谨的作品风格已经一去不复返了。 +

个人主义（Individualism），在卢梭（Rousseau）开始描写他个人的情感之前，并没有真正进入18世纪的启蒙运动世界，它也在后革命时代的思想中占有一席之地。 +
浪漫主义的个人主义强调诗意或其他形式的天赋。 +
比如，在启蒙运动和革命时期，关于每个人的个人权利和自由的讨论占据主导地位。 +
但在后革命时代，历史和小说都开始关注——在某种程度上甚至是崇拜——那些伟大的个人。 +
这些伟大的个人——往往是经过美化的军事明星——被视为历史变革的核心驱动力，以及每一个伟大故事（无论是虚构的还是真实的）的核心人物。 +
这仍然影响着我们看待历史和其他故事的方式——例如，尽管几乎所有的发明都是广泛而复杂的合作网络的结果，但我们仍然倾向于将个人置于这些故事的中心，无论是爱迪生（Edison）和他的电灯泡，还是拿破仑和他的军队。 +

但是，尽管维也纳会议的领导人尽了最大的努力，以及文化上对保守主义的强调，他们还是无法压制革命精神，尤其是那种人们是一个共同体的公民，而不是国王的臣民的思想所体现的革命精神。 +

在所有这些政治变革中，另一场不同的革命正极大地动摇着经济现状，以至于关于农民、土地和贵族的旧有观念很快就会被证明站不住脚。 +
工业革命（Industrial Revolution）深刻地重塑了工作和生活的本质。 +
1780年在法国，大约60%的人从事农业工作。 +
200年后，也就是1980年，只有8%的人从事农业工作。 +
工业革命将改变我们度过每一天的方式，改变我们彼此之间以及与世界的关系，改变我们所重视的东西，在某些方面，甚至改变我们是谁。 +
这将是我们下次要讲的内容。 +

到时候见。  +

'''


== pure

Hi, I'm John Green, and this is Crash Course European History.

So how did Europe restore order after the social and political upheaval of the French Revolution and the Napoleonic regime?

Well, European leaders got together and set up a committee -- or a "Congress" -- that met in Vienna to set things straight.

It's a great town, Vienna.

Great sausages.

I went there once.

Lots of skeletons under the city.

Freaked me out pretty bad.

What are we talking about?

Right, the Congress of Vienna.

So, when Europe looked around at the previous century with its endless wars, the reign of reason seemed disastrous, and so Europe turned to its past, and a conservatism that embraced monarchies and romanticism.

They believed that Enlightenment ideas, like the support of individual rights, had caused too much turmoil and misery, and so they wanted to go back to simpler times -- when kings were kings, peasants were landless, and obedience mattered more than thinking.

[Intro]

So, even as Napoleon was on his way back to the continent in 1815 to retake his empire, the Congress of Vienna had been meeting to restore stability.

Its members included representatives from Russia, the Habsburg Empire, Prussia, Britain, and France, which though defeated was central to discussions of how to return to the old order.

The first step was to bring back the French royal family, starting with the executed king's brother, Louis XVIII, who was known as "the desired" because presumably that was the only way to get him to take the job that killed his brother.

Like you're desired.

We want you!

We're not gonna guillotine you.

The second step was to balance out great power interests.

This meant ensuring that France was no longer a menace and that no state felt aggrieved enough to start another war.

A major player at the Congress was, oddly enough, a once-leading minister of Napoleon: Charles Maurice de Talleyrand-Périgord.

Ga, that was great.

In the bajillion years since I graduated high school, my high school French teacher has died, and that is very sad.

But at the same time, I'm glad she is not here to hear me speak French.

So, during Napoleon's reign, Talleyrand had been a relentless womanizer and also a relentless seeker of bribes.

Like a lot of people who succeed in politics, he was mostly a moth that flew toward the lights of power and influence.

With Napoleon's defeats, Talleyrand switched sides to support Louis XVIII, and was just the kind of well-connected wheeler-dealer the Congress needed.

The Congress's initial ideas for a settlement with France involved basically leaving France and its restored monarch alone to enjoy a good number of the revolutionary conquests.

But those moderate terms became harsh when Napoleon returned to France in the spring of 1815 to much acclaim from many of his French followers, including especially veterans of his army.

After Napoleon and his forces were defeated at Waterloo in June of 1815, the Allies imposed an indemnity, meaning France would be responsible for some of the losses they caused.

And the Allies decided that they would occupy France until that indemnity was paid.

The presiding spirit over the Congress and its negotiations was the Austrian minister Prince Klemens von Metternich.

Through his arch-conservative eyes, there was a lot to worry about.

One concern was the resurgence of revolution, a possibility he worked to prevent through the use of secret police, spies, and censorship.

But for him, stopping revolution also entailed closing down student fraternities as breeding grounds for liberal ideas.

Basically, attempts to restore rights, freedom, or achieve any part of the liberal program of the revolutionaries were seen as criminal.

Metternich was also concerned about Russia, which was now the strongest continental power, and he wanted to prevent its further expansionism.

He felt a strong monarchy in France would help make France powerful enough to check the power of Russia, thereby bring Europe into sociopolitical balance.

Did the center of the world just open?

Is there Jenga in there?

So, you're gonna hear this phrase balance of powers a lot in the next 200 years.

The idea is that if we can just distribute power among communities, the way that we distribute the load of Jenga pieces...even if something goes wrong, the thing doesn't fall.

It's worked great for 200 years.

What's that?

Oh gosh, Stan says that there's a World War I coming.

The Congress also divvied up available territories and resources.

Britain received some of France's territory in the Indian Ocean and the Caribbean, for instance, while Prussia was allocated part of Saxony and Austria was given Italian and other territory.

There was also the leftover question of Poland; so, remnants of the Duchy of Warsaw state fell to Russian control, with the remaining pieces going to Prussia and Austria.

Basically, the Congress of Vienna settlement had something for everyone.

Except for the Poles.

We're beginning the "This was good news for everyone except for the Poles" period of European history, which ends -- when did it end, Stan? in 1991.

In terms of international politics, the Congress's major achievements were twofold.

First, the Congress aimed for a "balance of power," which would guide European international developments for decades to come, and eventually provide a model for 20th century geopolitics as well.

We see this emphasis on "balance" in the tradeoffs and parceling out of benefits, but also in the general attitudes of great power leaders.

So in addition to working toward the balance of powers, the Congress established a "congress" system for arriving at agreements and enforcing them.

And this would become very important.

For one thing, it helped change the way we understand how people come into power.

Like, the Congress did not imagine kingship as deriving from divine power but instead from the decision making of the combined "great powers."

And the group acted with one voice, arriving at common policies, which was key to their strength.

This system is often called the "Concert of Europe," and in some ways it did presage the contemporary European Union.

Besides establishing the conditions for peacetime, thinkers across Europe were devising political theory for this post-revolutionary age.

Leading politicians embraced Edmund Burke's theory of conservatism, for instance, which emphasized tradition and the wisdom enshrined in institutions from the past.

Monarchy, according to conservatives, was the primary institution because it had endured for centuries so it provided age-old political stability.

The aristocracy also claimed an acquired superiority simply because of the long-lived leadership of its families.

In other words, the middle-classes, who promoted hard work and money-making skills, were no longer really models of capability.

Instead, readers flocked to Sir Walter Scott's tales of knights from the past as testimonial to aristocratic bravery -- especially when they were defeating the citizen-led armies of Napoleon.

The chivalrous Middle Ages were reborn as a golden age...despite all that black death, famine, and schism in the church.

It is truly astonishing what humans can, with time, nostalgicize.

Religion emerged as another part of the old regime that needed to be restored.

In tandem with the other terms of the political settlement, Russia, Prussia, and Austria agreed among themselves to a Holy Alliance.

This alliance would promote religious values and support diverse Christian religions of the three kingdoms, and also emphasize the importance of good old fashioned Christian obedience to the church, no matter which church it is, just please be obedient to it.

At the same time, religious activism renewed focus on philanthropy.

Aristocratic Catholics in France, for example, called themselves "socialists" because they were concerned that the strong emphasis on individualism had resulted in the deterioration of community and society.

Now, they were unrelated to the Marxist "socialists" who would later preach about revolution.

These French "socialists" raised money to aid the poor in their towns and city centers.

In Protestant countries, religion made a comeback as part of a second Great Awakening.

Like the First, it emphasized religious feeling instead of strict theological learning.

In Britain, Methodist churches sprang up, shunning the fancy ceremonials and religious hierarchies of Anglicanism.

Instead of bowing to archbishops and British aristocrats, they worshipped among their own kind in a spirit of democracy.

Another result of conservatism was a new rationale for allegiance to a kingdom or state.

Conservatives didn't promote constitutions and the rule of law, like the French and U.S. revolutionaries did with their Enlightenment-inspired governing structures.

Instead, they saw nations as stemming from historical evolution of noble families, a common language, and common heritage.

They collected folk tales and artifacts from the past, considered to be central to a kingdom's heritage.

The way things had always been done was the way they should be done in the present and future.

These ideas brought about clashes within nations between the agrarian interests of the landed aristocracy and the budding wealth of urban industrialists and financiers.

Industrialists often wanted progressive change, such as infrastructure that would support their businesses, while landed aristocrats wanted to ensure that traditional hierarchies would not be disturbed, on account of how they benefited from them.

Let's go to the Thought Bubble.

There was another new idea dominating the post-revolutionary era:
the culture of Romanticism, which replaced the culture of Enlightenment.
Romanticism held that the world of feeling was far superior to the regime of reason;
that nature was superior to manufacturing;
and that the past was better than the present.
Mary Shelley was the daughter of Mary Wollstonecraft.
And you'll recall, in A Vindication of the Rights of Woman, Wollstonecraft emphasized the need for knowledge and reason in people's lives.
But her daughter's novel Frankenstein took the opposite stance, in some ways.
It's a story, in part about what can be wrought by reason run amok.
Although the monster had many abilities, it lacked human love and warmth,
so it ended up killing those who had loved and been kind to him.
For Shelley, the lack of feeling -- not the lack of reason -- lay at the heart of social problems.
And unchecked reason, like that of Dr. Frankenstein, created monstrosities.
Meanwhile Russian poet Alexander Pushkin wrote the novel Eugene Onegin in the kind of romantic, flowery verse
that stands in stark contrast to the cold and rational exposition of Enlightenment novelists like Voltaire.
Eugene Onegin tells the story of a tragically ill-timed romance between Onegin and Tatyana
as the two attempt to navigate paths between strong emotion and the traditions of Russian courtship.
It's remembered today in part because it explores the paradoxes of romantic thinking without dismissing any perspective.
Indeed, Pushkin himself followed at least one of the conventions of traditional male honor in his own life:
He died in a duel with his wife's purported lover.
Thanks Thought Bubble.

Not only did Romantic poets write about nature, they also invoked foreign lands and exoticism -- an exoticism that was earlier expressed in material goods like textiles, porcelain, umbrellas, and coffee.

Painters depicted nude women in harems (even though none had ever entered a harem much less seen a nude woman in one).

And Samuel Coleridge wrote in "Kubla Khan" of an opium dream in which he is mystically transported to another time and place.

Percy Bysshe Shelley, husband of Mary Shelley, wrote of distant Asia.

Still others, escaping harsh reality, composed odes to poppies, from which opium is derived.

Sir Walter Scott, like other novelists, wrote about the Middle Ages, but he too reached romantic intensity in part because of his opium addiction.

The highs and lows of existence, raging storms, extreme suffering, foreboding moods, all characterized the desire to turn Enlightenment rationality upside down with intense emotion -- or even to personally escape from that hyper-reasoned reality.

Musicians also conveyed romantic highs and lows.

They did this by juxtaposing thundering choruses with more tender passages.

Composer Ludwig von Beethoven, the extremely intense fellow behind me, excelled at creating these types of musical contrasts.

The crisp and disciplined compositions of Enlightenment musicians were gone.

Individualism, which had not really entered the eighteenth century Enlightenment world until Rousseau wrote of his individual emotions, also figured in post-revolutionary thought.

Romantic individualism emphasized poetic or other forms of genius.

Like, during the Enlightenment and revolutionary years, individual rights and liberties for everyone dominated debates.

But in the post-revolutionary era, both history and fiction began to look at -- and in a way worship -- the individual Great Man.

These great individuals -- who tended to be cleaned up military stars -- were seen to be the central drivers of historical change and the individuals at the center of every great tale, whether fiction or not.

And this still shapes our way of looking at history and other stories -- while almost all inventions, for instance, are the result of broad and complex networks of collaborators, we still tend to put individuals at the center of those stories, whether it's Edison and his light bulb or Napoleon and his army.

But try as they might, leaders at the Congress of Vienna and a cultural emphasis on conservatism could not quash the revolutionary spirit, especially the spirit embodied by the idea that people were citizens of a community, rather than subjects of a king.

And amid all these political changes, a different revolution was shaking the economic status quo so dramatically that old ways of thinking about peasants and land and aristocrats would soon prove untenable.

The nature of work and life were profoundly reshaped by the Industrial Revolution.

In France in 1780, somewhere around 60% of people worked in agriculture.

200 years later, in 1980, only 8% did.

The Industrial Revolution will change how we spend our days, how we relate to one another and to the world, what we value, and in some ways, who we are.

That's next time.

I'll see you then.

'''
