= 029 - Expansion and Resistance
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义

Hi, I'm John Green, and this is Crash Course European History. +

So we've made it to the nineteenth century, and as European societies are trying to build cohesive 有凝聚力的 political structures 政治结构 known as nations, many are also expanding or initiating 发起 overseas empires 海外帝国. +

And so while more European nations were grounded in 基于 the rule of law 法治 and constitutional guarantees 宪法保障, including property rights 财产权, life was very different in the empires governed by those nations, where there were few if any rights. +

While many nation-builders 国家建设者 and citizens supported rights and the rule of law as a bedrock 基石 of their nations, expansion 扩张 entailed 意味着 taking away 剥夺 the rights of others. +

And understanding how this contradiction 矛盾 functioned, and who it benefited, is key to understanding not just 19th century colonialism 殖民主义, but also the contradictions we still live with today. +

[Intro] +

So, when we last looked at expansion, the British were moving forcefully 强有力地 into India, in part to compensate for 补偿 losing monopoly rights 垄断权 over trade with North America, while the Spanish and French were losing their grip 失去控制 in the Western Hemisphere 西半球. +

But by the mid-19th century, Asia, Africa, and the Pacific islands 太平洋岛屿 were now the focus of imperial activity 帝国活动, much of it to gain trading advantages 贸易优势 and acquire 获得 more raw materials 原材料 like palm oil 棕榈油 for industry 工业. +

And much firmer political control 政治控制 of territories 领土 was established, as in India, North Africa, and Australia. +

In the nineteenth century, the Chinese continued to attract European trade because of their excellent products, especially tea and silk. +

The English were leaders in industrialization 工业化, but they mostly made low quality products that pretty much nobody wanted, including the Chinese. +

But the British needed something to sell in exchange for 交换 tea and silk, and they ended up focusing on drug smuggling 毒品走私. +

When the Chinese government began to crack down on 打击 the opium smugglers 鸦片走私者 -- many of whose descendants 后代 are today some of the most respected and wealthy families in Britain -- the smugglers convinced the British government to initiate 发动 the Opium Wars 鸦片战争 of 1839-1842 and 1856-1860. +

British success in these wars forced China to open new ports to trade. +

And while China had banned opium in 1799, the British used the idea of "freedom of trade" 自由贸易 to keep opium sales going and increasingly imposed 强加 their political and economic will 意志 on Chinese rulers. +

Regions in Southeast Asia and the Pacific were also targets 目标 for forced trade 强迫贸易 and takeovers of land 土地侵占. +

The French set up rubber 橡胶 and other plantations 种植园 in Indochina 印度支那, the British took vast quantities of 大量 lumber 木材 from Burma 缅甸, and the Dutch set up a variety of plantations in Indonesia 印度尼西亚, no longer confining 限制 their interests simply to trading posts 贸易站. +

Pacific islands also became way-stations 中途站 for ships to resupply 补给物资 and obtain other raw materials. +

The French, British, and Belgians 比利时人 headed for 前往 the interior of Africa 非洲内陆, now that they had quinine 奎宁 with which to treat malaria infections 疟疾感染. +

While the Portuguese 葡萄牙人 maintained a toehold 立足点 on a part of Southwestern Africa, the French took over 接管 much of West and North Africa and the British took areas in the south and east. +

Belgian King Leopold assaulted 侵占 the Congo 刚果 for its rubber (and yes, we are using that verb intentionally), while Otto von Bismarck, generally not a fan of 不喜欢 expansion outside of Europe, allowed German businessmen and adventurers 冒险家 to head for regions in Asia and southeastern and southwestern Africa. +

He also allowed them to launch ventures 发起冒险活动 in the Middle East, especially the Ottoman Empire 奥斯曼帝国. +

But the largest and most continuous enterprise 企业；事业 was the one the British built in India and Central Asia. +

They sought manufactured goods 制成品 and raw materials, but they were also motivated by 出于…动机 simple plunder 掠夺. +

The British invested little in ruling India, instead using different princes' well-trained soldiers for conquering new areas and policing 维持治安. +

Governance 治理 of the colony 殖民地 involved some 4,000 British officials and tens of thousands of local civil service workers 当地公务员 who did the main work. +

And as in the past, European invaders 侵略者 relied on 依靠 local people to serve as informants 线人, and guides 向导, and go-betweens 中间人 and negotiators 谈判者. +

They were some of the human "tools of empire 帝国工具". +

And while "explorers" 探险家 and colonial generals 殖民将领 were portrayed 描绘 in European newspapers and magazines as standard bearers 旗手 of heroic masculinity 英雄气概, they required vast entourages 随行人员 of local people to survive. +

This was especially true in Africa where from village to village go-betweens and guides had to lead and negotiate the supposedly "lone" 独自的 adventurer's food, and safe passage 安全通行, and health care needs. +

It is well-documented 有充分记录的 that many of these romanticized heroes 被浪漫化的英雄 became addicted to 对…上瘾 drugs and alcohol because of the stresses 压力 but also because of the boredom 无聊 of the slow movement of hundreds of animals and carriers of supplies and weapons. +

Let's go to the Thought Bubble. +

1. Other tools of empire were industrial, like steamships 蒸汽船 built to navigate rivers 内河航行 +
2. and weaponry 武器 that local people lacked (at least initially 最初). +
3. Europeans often sold inferior 劣质的 or outdated 过时的 weapons to the people they wanted to conquer 征服, +
4. who were quick to duplicate 复制 the better models that fell into their hands. +
5. Railroads 铁路 also became tools of empire in that they were set up not to benefit local people +
6. but to strip them of 剥夺 their goods and get those goods to ports 港口 as quickly as possible. +
7. Infrastructure 基础设施 was built to disadvantage 使处于不利地位 not advantage colonized peoples 被殖民人民. +
8. A final and crucial 至关重要的 tool of empire was the aforementioned 前面提到的 quinine, +
9. which was made from the bark 树皮 of the cinchona tree 金鸡纳树 found primarily in South America. +
10. Jesuit priests 耶稣会牧师 were introduced to the drug by indigenous people 原住民 in South America, +
11. but initially the bark had to be procured 获得 and ground up 研磨, +
12. which made quinine difficult to produce in large quantities 大量生产. +
13. But after the 1820s, French scientists devised 设计 procedures 方法 to extract 提取 quinine from the bark, +
14. and then in the 1850s, the Dutch finally obtained the closely guarded 严密保护的 cinchona seeds 金鸡纳树种子, +
15. which South Americans were embargoing 禁运, +
16. and the Dutch set up successful plantations in Indonesia. +
17. The medicalization 医学应用 and plantation production 种植园生产 of cinchona meant that quinine was widely available to Europeans, +
18. which in turn 反过来 allowed for the invasion of Africa's interior 内陆, where malaria was common. +

Thanks Thought Bubble. +

Oh my gosh, the center of the world just opened! Our two main bits are right next to each other! So this is a train. I'm not sure if its a real train, it might just be a model train, I'm not a scientist. +

All I know is that railroads were incredibly important in the 19th century, and remain so. +

And if you look at where nations built railroads inside their nations, and where they built railroads inside their colonies 殖民地, you'll immediately understand the difference between living in a nation and living in a colony. +

In Britain, for instance 例如, the railroads primarily connect cities to each other, so people and goods can be connected and distributed 分配. +

But if you look at where Britain built railroads in, for instance Sierra Leone 塞拉利昂 in the early 20th century, you'll see that those railroads are designed almost entirely to get goods from the interior of the country to a port. +

And that brings us to resource extraction 资源开采. +

The discovery of diamond 钻石 and gold mines 金矿 in South Africa from the 1860s into the 1880s provided another impetus 动力 to colonization 殖民 and contests over territory 领土争夺. +

To get Africans to leave their homes and work in the mines, the British demanded that taxation 税收 be paid in currency 货币 instead of in produce 农产品 or other goods. +

So to acquire funds 获得资金, Africans had to leave their farms for the mines, where work was treacherous 危险的 and often fatal 致命的. +

South African lands were also simply stolen to drive people into the mines. +

Was there resistance 抵抗 to the violence 暴力, theft 盗窃, and exploitation 剥削 of imperialism 帝国主义? +

Yes. +

Colonized people 被殖民人民 rebelled 反抗 in a variety of ways. +

In 1857, local people in India including Indian soldiers 印度士兵 and even the widow 寡妇 of a local ruler, Rani Lakshmi Bai, Queen of Jhansi 章西女王, launched a rebellion 起义 against expanding British rule 英国统治扩张 and its seizure of property 财产没收. +

Her wealth had been stolen, and she had been removed from power 被剥夺权力. +

"We all know," read a circular letter 通告信 that year, "that if [the English] stay in Hindustan [India] they will kill everyone and spoil our faith... In this scenario we ask you what you are doing to defend your faith and our lives... And this has been published in order to save the religion and faith and the lives of all you Hindus and Muslims." +

As they crushed the rebellion 镇压起义, the British justified 为…辩解 the ensuing slaughter 随后的屠杀 as needed to punish the supposed rapes 所谓的强奸 that vicious 凶残的 Indians had inflicted on 施加于 "white" women. +

But later investigations 调查 proved that no such rapes had occurred. +

The English additionally 另外 branded 污蔑 the Rani a prostitute 妓女. +

She died in battle during the uprising 起义, one of more than 5,000 Indians killed on June 17, 1857. +

Resistance to empire took many forms. +

In the Belgian Congo 比属刚果, for instance, where local people were horrifically abused 遭受可怕虐待 by the colonial authorities 殖民当局, officials realized that the fertility level 生育率 was dropping. +

Across the colonized world drop in births like this, seen by historians as a form of intentional "strike" 罢工, and they've been happening for a long time. +

For example, in the Caribbean 加勒比地区, women used the peacock flower 孔雀花 to abort fetuses 堕胎; enslaved women 女奴 elsewhere used rue 芸香, willow 柳树, ergot 麦角, and other plants so that additional children would not be born into slavery 奴隶制. +

Such was the horror of colonial oppression 殖民压迫 that many people did not want a new generation to be born into the world. +

That said 尽管如此, some local people living under colonial conditions 殖民统治条件下 prospered 繁荣 not just as soldiers and civil servants 公务员 but as business and professional people 商业和专业人士. +

They were labor contractors 包工头, and merchants 商人, and large property owners 大业主. +

The Tagores of Bengal 孟加拉的泰戈尔家族 owned agricultural estates 农业庄园 but as the English advanced, they invested their growing funds in establishing silk and other mills 工厂 while also serving as high level agents 高级代理人 for British companies in India. +

Rabindranath Tagore 罗宾德拉纳特·泰戈尔 of that family won the Nobel Prize for Literature 诺贝尔文学奖 in 1913 -- the first non-European to do so. +

Empire builders 帝国建造者 justified their conquests 征服 by describing themselves as fully entitled to 完全有权 take the wealth, land, and know-how 专门知识 of distant peoples 遥远地区的人民 and even to enslave 奴役 them. +

Initially 最初 they argued that local people, whom they often called "savages" 野蛮人 needed to be turned into Christians for their salvation 救赎. +

In this explanation, imperialism became a holy endeavor 神圣事业, as it had been for the Spanish and Portuguese more than three centuries earlier. +

But after the mid-nineteenth century publication 出版 of Charles Darwin's Origin of Species 物种起源 and The Descent of Man 人类的由来, empire was viewed as imperative 必要的 in order to save civilization 文明 from violent brutes 野蛮暴力之人. +

Now, I know what you're thinking. "I've studied European history a bit, and its pretty violent." +

We agree, obviously, but people tell themselves stories in order to justify the oppression 压迫 of others. +

And indeed, to justify wherever they find themselves in life. +

In this telling 说法, humans had evolved from 从…进化而来 lower forms of existence 生存形式, and Darwin argued that human development reached a pinnacle 顶峰 in white men. +

So according to him, all people of other races 种族 were less-evolved 进化程度较低的 and less accomplished 成就较低的. +

Social Darwinists 社会达尔文主义者 -- people who took Darwin's scientific studies 科学研究 and made them the basis of 以…为基础 expansionist 扩张主义的 and domestic politics 国内政治 -- believed that white people needed to be engaged in conquest 征服 to preserve 维持 their superior lives 优越生活. +

So the justification for, say, stealing palm oil or diamonds from colonized regions 殖民地 was that it helped keep white people superior, and those were the people who really mattered. +

I know that it's tempting 有吸引力的, especially for people who benefitted from colonialism 从殖民主义中获益的人 to say that this is all in the past, but the wealth extracted from 从…提取 colonized regions had a lasting effect on 对…有持久影响 both the colonizer 殖民者 and the colonized 被殖民者. +

And ideas about race 种族观念 that were constructed 构建 to justify colonialism are still deeply ingrained in 深深植根于 lived human experience 人类生活体验 around the world. +

Imperialists 帝国主义者 eventually tried to calm what came to be called the "Scramble for Africa" 瓜分非洲 with the Berlin Conference 柏林会议 of 1884-85, which ruled that European nations with outposts 前哨站 on African coasts 非洲海岸 could claim 宣称拥有 the corresponding interior region 相应的内陆地区. +

There were also conditions, for example, against selling firearms 火器 to Africans. +

But the main result of all of this was to intensify 加剧 imperial competition 帝国竞争. +

The British and French almost came to blows 发生冲突 at Fashoda 法绍达 in Sudan 苏丹 in 1898; the Germans threatened French holdings 领地 in North Africa early in the twentieth century. +

And eventually these growing international tensions 国际紧张局势 within Europe would lead to World War 世界大战, which we'll hear more about that in a few more weeks. +

But for now, I want to ask you to shift perspectives 转换视角 and consider the experience of those who were most negatively affected in this imperialism. +

How that imperialism is still shaping life today. +

Thanks for watching, I'll see you next time. +

'''


== 中文翻译

大家好，我是约翰·格林，这里是《速成欧洲史》。 +

我们已经讲到了19世纪，当欧洲社会试图构建被称为 “国家” 的有凝聚力的政治结构时，许多国家也在扩张或建立海外帝国。 +

因此，虽然更多的欧洲国家以法治和宪法保障（包括财产权）为基础，但在这些国家统治的帝国里，情况却大不相同，在那里几乎没有什么权利可言。 +

许多国家的建设者和公民支持将权利和法治作为国家的基石，然而扩张却意味着剥夺他人的权利。 +

理解这种矛盾是如何产生的，以及它使谁受益，不仅是理解19世纪殖民主义的关键，也是理解我们如今仍然面临的矛盾的关键。 +

[开场介绍] +

我们上次讲到扩张时，英国人正强力进入印度（India），部分原因是为了弥补失去与北美（North America）贸易的垄断权的损失，而西班牙人（Spanish）和法国人（French）则在西半球（Western Hemisphere）逐渐失去了控制。 +

但到了19世纪中期，亚洲（Asia）、非洲（Africa）和太平洋岛屿（Pacific islands）成为了帝国活动的焦点，其中很大一部分活动是为了获得贸易优势，并获取更多的工业原材料，比如棕榈油（palm oil）。 +

像在印度、北非（North Africa）和澳大利亚（Australia），对领土建立了更为稳固的政治控制。 +

在19世纪，中国人（Chinese）因其优质产品，尤其是茶叶（tea）和丝绸（silk），继续吸引着欧洲的贸易。 +

英国人（English）在工业化方面处于领先地位，但他们生产的大多是质量低劣的产品，几乎没人想要，包括中国人也不想要。 +

但英国人需要一些东西来换取茶叶和丝绸，最终他们专注于毒品走私。 +

当中国政府开始打击鸦片（opium）走私者时——这些走私者的许多后代如今是英国一些最受尊敬和富有的家族——走私者说服英国政府发动了1839年至1842年以及1856年至1860年的鸦片战争（Opium Wars）。 +

英国在这些战争中的胜利迫使中国开放了新的通商口岸。 +

虽然中国在1799年就禁止了鸦片，但英国人利用 “自由贸易”（freedom of trade）的理念继续进行鸦片销售，并越来越多地将他们的政治和经济意志强加给中国统治者。 +

东南亚（Southeast Asia）和太平洋地区也成为了强制贸易和夺取土地的目标。 +

法国人在印度支那（Indochina）建立了橡胶（rubber）和其他种植园，英国人从缅甸（Burma）获取了大量木材，荷兰人（Dutch）在印度尼西亚（Indonesia）建立了各种种植园，不再仅仅局限于贸易据点。 +

太平洋岛屿也成为了船只补给和获取其他原材料的中转站。 +

现在法国人、英国人和比利时人（Belgians）有了奎宁（quinine）来治疗疟疾（malaria）感染，他们开始向非洲内陆进发。 +

葡萄牙人（Portuguese）在非洲西南部的一部分地区维持着据点，法国人占领了西非和北非的大部分地区，而英国人则占领了南部和东部的一些地区。 +

比利时国王利奥波德（Belgian King Leopold）为了获取橡胶而对刚果（Congo）进行了侵略（没错，我们故意用了 “侵略” 这个词），而奥托·冯·俾斯麦（Otto von Bismarck），总体上并不支持在欧洲以外进行扩张，却允许德国（German）商人和冒险家前往亚洲以及非洲东南部和西南部地区。 +

他还允许他们在中东（Middle East）开展业务，尤其是在奥斯曼帝国（Ottoman Empire）。 +

但规模最大且持续时间最长的事业是英国人在印度和中亚（Central Asia）建立的帝国。 +

他们寻求制成品和原材料，但同时也受到单纯掠夺的驱使。 +

英国人在统治印度方面投入很少，而是利用不同王公训练有素的士兵来征服新地区并维持治安。 +

对这个殖民地的治理涉及大约4000名英国官员和数万名当地的公务员，这些公务员承担了主要工作。 +

和过去一样，欧洲侵略者依靠当地人充当告密者、向导、中间人和谈判者。 +

他们是一些人类 “帝国工具”。 +

虽然 “探险家” 和殖民将领在欧洲的报纸和杂志上被描绘成英勇阳刚的典范，但他们需要大量的当地人随行才能生存下去。 +

在非洲尤其如此，从一个村庄到另一个村庄，中间人和向导必须带领并为这些所谓 “独自” 的冒险家安排食物、安全通行和医疗需求。 +

有充分的记录表明，许多这些被浪漫化的英雄因为压力，也因为数百头动物以及物资和武器搬运者缓慢行进带来的无聊，而染上了毒瘾和酒瘾。 +

让我们进入“思想泡泡”环节。 +

1. 其他的帝国工具是工业化产物，比如为在河流中航行而建造的轮船（steamships）。 +
2. 以及当地人所缺乏的武器装备（至少最初是这样）。 +
3. 欧洲人常常把劣质或过时的武器卖给他们想要征服的人， +
4. 而这些人很快就会仿制落到他们手中的更好的武器型号。 +
5. 铁路（Railroads）也成为了帝国的工具，因为它们的建设不是为了让当地人受益， +
6. 而是为了掠夺他们的货物，并尽快将这些货物运到港口。 +
7. 基础设施的建设是为了让被殖民的人民处于不利地位，而不是为他们带来好处。 +
8. 帝国的最后一个关键工具是前面提到的奎宁， +
9. 它是从主要在南美洲（South America）发现的金鸡纳树（cinchona tree）的树皮中提取的。 +
10. 耶稣会（Jesuit）牧师是由南美洲的原住民介绍认识这种药物的， +
11. 但最初，树皮必须采集并研磨， +
12. 这使得奎宁很难大量生产。 +
13. 但在19世纪20年代之后，法国科学家设计出了从树皮中提取奎宁的方法， +
14. 然后在19世纪50年代，荷兰人终于获得了被严密保护的金鸡纳树种子， +
15. 而南美洲人当时正在对这些种子实行禁运， +
16. 荷兰人在印度尼西亚建立了成功的种植园。 +
17. 金鸡纳树的医学利用和种植园生产意味着奎宁对欧洲人来说广泛可得， +
18. 这反过来又使得他们能够入侵疟疾常见的非洲内陆。 +

感谢“思想泡泡”！ +

哦，我的天哪，世界的中心刚刚打开了！我们的两个主要部分紧挨着！所以这是一列火车。我不确定它是不是一辆真正的火车，它可能只是一个火车模型，我不是科学家。 +

我只知道铁路在19世纪极其重要，并且至今依然重要。 +

如果你看看各国在自己国内修建铁路的地方，以及他们在殖民地修建铁路的地方，你会立刻明白生活在一个国家和生活在一个殖民地之间的区别。 +

例如在英国，铁路主要是连接各个城市，这样人和货物就可以相互联系和流通。 +

但是，如果你看看英国在比如20世纪初在塞拉利昂（Sierra Leone）修建铁路的地方，你会发现那些铁路几乎完全是为了把货物从该国的内陆运到港口而设计的。 +

这就引出了我们要讲的资源开采。 +

从19世纪60年代到19世纪80年代，在南非（South Africa）发现的钻石矿（diamond mines）和金矿（gold mines）为殖民和领土争夺提供了另一个推动力。 +

为了让非洲人离开家园去矿山工作，英国人要求用货币纳税，而不是用农产品或其他货物。 +

所以为了获得资金，非洲人不得不离开他们的农场去矿山，在那里工作充满危险，而且常常会致命。 +

南非的土地也被直接掠夺，以迫使人们进入矿山工作。 +

对于帝国主义的暴力、掠夺和剥削，有反抗吗？ +

有的。 +

被殖民的人民以各种方式进行了反抗。 +

1857年，印度的当地人，包括印度士兵（Indian soldiers），甚至当地一位统治者的遗孀，章西女王（Rani Lakshmi Bai, Queen of Jhansi），发动了一场反抗英国统治扩张及其对财产的掠夺的起义。 +

她的财富被掠夺，她也失去了权力。 +

那年的一份通告信中写道：“我们都知道，如果[英国人]留在印度斯坦[印度]，他们会杀光所有人，破坏我们的信仰……在这种情况下，我们问你们，你们在为捍卫你们的信仰和我们的生命做些什么……发布这份通告是为了拯救你们所有印度教徒和穆斯林的宗教、信仰和生命。” +

在镇压起义时，英国人将随后的屠杀辩解为是惩罚所谓凶残的印度人对 “白人” 女性实施的强奸行为所必需的。 +

但后来的调查证明，并没有发生这样的强奸事件。 +

此外，英国人还污蔑章西女王是妓女。 +

她在起义中战死，是1857年6月17日丧生的5000多名印度人之一。 +

对帝国的反抗有多种形式。 +

例如在比利时统治的刚果，当地人民遭到殖民当局的残酷虐待，官员们意识到当地的生育率正在下降。 +

在整个被殖民的世界，像这样的出生率下降，被历史学家视为一种有意的 “罢工” 形式，而且这种情况已经持续了很长时间。 +

例如，在加勒比地区（Caribbean），女性用孔雀花（peacock flower）来堕胎；其他地方被奴役的女性则使用芸香（rue）、柳树（willow）、麦角（ergot）和其他植物，这样就不会有更多的孩子出生在奴隶制下。 +

殖民压迫是如此可怕，以至于许多人不希望新一代出生在这样的世界里。 +

话虽如此，一些生活在殖民环境下的当地人不仅作为士兵和公务员，而且作为商人和专业人士获得了成功。 +

他们是劳工承包商、商人和大业主。 +

孟加拉（Bengal）的泰戈尔（Tagores）家族拥有农业庄园，但随着英国人的推进，他们用不断增加的资金投资建立了丝绸和其他工厂，同时还担任英国公司在印度的高级代理商。 +

这个家族的罗宾德拉纳特·泰戈尔（Rabindranath Tagore）在1913年获得了诺贝尔文学奖（Nobel Prize for Literature）——他是第一个获此殊荣的非欧洲人。 +

帝国的建立者们为他们的征服行为辩护，声称他们完全有权利夺取遥远地区人民的财富、土地和专门技能，甚至有权奴役他们。 +

最初，他们辩称当地人，他们常常称这些人为 “野蛮人”，需要皈依基督教（Christians）才能得到救赎。 +

在这种解释下，帝国主义变成了一项神圣的事业，就像三个多世纪前对西班牙人和葡萄牙人那样。 +

但在19世纪中期查尔斯·达尔文（Charles Darwin）的《物种起源》（Origin of Species）和《人类的由来》（The Descent of Man）出版之后，人们认为为了使文明免受野蛮人的侵害，建立帝国是势在必行的。 +

现在，我知道你在想什么。“我学过一点欧洲历史，它相当暴力。” +

显然，我们对此表示认同，但人们会给自己找理由，来为压迫他人的行为辩护。 +

而且事实上，是为他们在生活中所处的任何位置找理由。 +

在这种说法中，人类是从较低级的存在形式进化而来的，达尔文认为人类的发展在白人男性身上达到了顶峰。 +

所以根据他的观点，所有其他种族的人进化程度较低，成就也较少。 +

社会达尔文主义者（Social Darwinists）——那些将达尔文的科学研究作为扩张主义和国内政治基础的人——认为白人需要进行征服，以维护他们优越的生活。 +

所以，比如说，从殖民地地区掠夺棕榈油或钻石的理由是，这有助于保持白人的优越性，而白人是真正重要的群体。 +

我知道，尤其是对于那些从殖民主义中受益的人来说，很容易说这一切都已经成为过去了，但从殖民地地区掠夺的财富对殖民者和被殖民者都产生了持久的影响。 +

为殖民主义辩护而构建的种族观念，至今仍然深深植根于世界各地人们的生活体验之中。 +

帝国主义者最终试图通过1884年至1885年的柏林会议（Berlin Conference）来平息所谓的 “非洲争夺战”（“Scramble for Africa”），该会议规定，在非洲海岸拥有前哨站的欧洲国家可以宣称对相应的内陆地区拥有主权。 +

会议也有一些条件，例如，禁止向非洲人出售枪支（firearms）。 +

但这一切的主要结果却是加剧了帝国主义之间的竞争。 +

1898年，英国人和法国人在苏丹（Sudan）的法绍达（Fashoda）差点发生冲突；20世纪初，德国人威胁到了法国在北非的领地。 +

最终，欧洲内部这些不断加剧的国际紧张局势将导致世界大战（World War），再过几周我们会听到更多关于这方面的内容。 +

但现在，我希望你转换一下视角，考虑一下那些在这种帝国主义中受到最负面影响的人们的经历。 +

以及这种帝国主义是如何仍然在塑造着今天的生活的。 +

感谢观看，我们下次再见。 +

'''


== pure

Hi, I'm John Green, and this is Crash Course European History.

So we've made it to the nineteenth century, and as European societies are trying to build cohesive political structures known as nations, many are also expanding or initiating overseas empires.

And so while more European nations were grounded in the rule of law and constitutional guarantees, including property rights, life was very different in the empires governed by those nations, where there were few if any rights.

While many nation-builders and citizens supported rights and the rule of law as a bedrock of their nations, expansion entailed taking away the rights of others.

And understanding how this contradiction functioned, and who it benefited, is key to understanding not just 19th century colonialism, but also the contradictions we still live with today.

[Intro]

So, when we last looked at expansion, the British were moving forcefully into India, in part to compensate for losing monopoly rights over trade with North America, while the Spanish and French were losing their grip in the Western Hemisphere.

But by the mid-19th century, Asia, Africa, and the Pacific islands were now the focus of imperial activity, much of it to gain trading advantages and acquire more raw materials like palm oil for industry.

And much firmer political control of territories was established, as in India, North Africa, and Australia.

In the nineteenth century, the Chinese continued to attract European trade because of their excellent products, especially tea and silk.

The English were leaders in industrialization, but they mostly made low quality products that pretty much nobody wanted, including the Chinese.

But the British needed something to sell in exchange for tea and silk, and they ended up focusing on drug smuggling.

When the Chinese government began to crack down on the opium smugglers -- many of whose descendants are today some of the most respected and wealthy families in Britain -- the smugglers convinced the British government to initiate the Opium Wars of 1839-1842 and 1856-1860.

British success in these wars forced China to open new ports to trade.

And while China had banned opium in 1799, the British used the idea of "freedom of trade" to keep opium sales going and increasingly imposed their political and economic will on Chinese rulers.

Regions in Southeast Asia and the Pacific were also targets for forced trade and takeovers of land.

The French set up rubber and other plantations in Indochina, the British took vast quantities of lumber from Burma, and the Dutch set up a variety of plantations in Indonesia, no longer confining their interests simply to trading posts.

Pacific islands also became way-stations for ships to resupply and obtain other raw materials.

The French, British, and Belgians headed for the interior of Africa, now that they had quinine with which to treat malaria infections.

While the Portuguese maintained a toehold on a part of Southwestern Africa, the French took over much of West and North Africa and the British took areas in the south and east.

Belgian King Leopold assaulted the Congo for its rubber (and yes, we are using that verb intentionally), while Otto von Bismarck, generally not a fan of expansion outside of Europe, allowed German businessmen and adventurers to head for regions in Asia and southeastern and southwestern Africa.

He also allowed them to launch ventures in the Middle East, especially the Ottoman Empire.

But the largest and most continuous enterprise was the one the British built in India and Central Asia.

They sought manufactured goods and raw materials, but they were also motivated by simple plunder.

The British invested little in ruling India, instead using different princes' well-trained soldiers for conquering new areas and policing.

Governance of the colony involved some 4,000 British officials and tens of thousands of local civil service workers who did the main work.

And as in the past, European invaders relied on local people to serve as informants, and guides, and go-betweens and negotiators.

They were some of the human "tools of empire."

And while "explorers" and colonial generals were portrayed in European newspapers and magazines as standard bearers of heroic masculinity, they required vast entourages of local people to survive.

This was especially true in Africa where from village to village go-betweens and guides had to lead and negotiate the supposedly "lone" adventurer's food, and safe passage, and health care needs.

It is well-documented that many of these romanticized heroes became addicted to drugs and alcohol because of the stresses but also because of the boredom of the slow movement of hundreds of animals and carriers of supplies and weapons.

Let's go to the Thought Bubble.

1. Other tools of empire were industrial, like steamships built to navigate rivers
2. and weaponry that local people lacked (at least initially).
3. Europeans often sold inferior or outdated weapons to the people they wanted to conquer,
4. who were quick to duplicate the better models that fell into their hands.
5. Railroads also became tools of empire in that they were set up not to benefit local people
6. but to strip them of their goods and get those goods to ports as quickly as possible.
7. Infrastructure was built to disadvantage not advantage colonized peoples.
8. A final and crucial tool of empire was the aforementioned quinine,
9. which was made from the bark of the cinchona tree found primarily in South America.
10. Jesuit priests were introduced to the drug by indigenous people in South America,
11. but initially the bark had to be procured and ground up,
12. which made quinine difficult to produce in large quantities.
13. But after the 1820s, French scientists devised procedures to extract quinine from the bark,
14. and then in the 1850s, the Dutch finally obtained the closely guarded cinchona seeds,
15. which South Americans were embargoing,
16. and the Dutch set up successful plantations in Indonesia.
17. The medicalization and plantation production of cinchona meant that quinine was widely available to Europeans,
18. which in turn allowed for the invasion of Africa's interior, where malaria was common.

Thanks Thought Bubble.

Oh my gosh, the center of the world just opened! Our two main bits are right next to each other! So this is a train. I'm not sure if its a real train, it might just be a model train, I'm not a scientist.

All I know is that railroads were incredibly important in the 19th century, and remain so.

And if you look at where nations built railroads inside their nations, and where they built railroads inside their colonies, you'll immediately understand the difference between living in a nation and living in a colony.

In Britain, for instance, the railroads primarily connect cities to each other, so people and goods can be connected and distributed.

But if you look at where Britain built railroads in, for instance Sierra Leone in the early 20th century, you'll see that those railroads are designed almost entirely to get goods from the interior of the country to a port.

And that brings us to resource extraction.

The discovery of diamond and gold mines in South Africa from the 1860s into the 1880s provided another impetus to colonization and contests over territory.

To get Africans to leave their homes and work in the mines, the British demanded that taxation be paid in currency instead of in produce or other goods.

So to acquire funds, Africans had to leave their farms for the mines, where work was treacherous and often fatal.

South African lands were also simply stolen to drive people into the mines.

Was there resistance to the violence, theft, and exploitation of imperialism?

Yes.

Colonized people rebelled in a variety of ways.

In 1857, local people in India including Indian soldiers and even the widow of a local ruler, Rani Lakshmi Bai, Queen of Jhansi, launched a rebellion against expanding British rule and its seizure of property.

Her wealth had been stolen, and she had been removed from power.

"We all know," read a circular letter that year, "that if [the English] stay in Hindustan [India] they will kill everyone and spoil our faith... In this scenario we ask you what you are doing to defend your faith and our lives... And this has been published in order to save the religion and faith and the lives of all you Hindus and Muslims."

As they crushed the rebellion, the British justified the ensuing slaughter as needed to punish the supposed rapes that vicious Indians had inflicted on "white" women.

But later investigations proved that no such rapes had occurred.

The English additionally branded the Rani a prostitute.

She died in battle during the uprising, one of more than 5,000 Indians killed on June 17, 1857.

Resistance to empire took many forms.

In the Belgian Congo, for instance, where local people were horrifically abused by the colonial authorities, officials realized that the fertility level was dropping.

Across the colonized world drop in births like this, seen by historians as a form of intentional "strike," and they've been happening for a long time.

For example, in the Caribbean, women used the peacock flower to abort fetuses; enslaved women elsewhere used rue, willow, ergot, and other plants so that additional children would not be born into slavery.

Such was the horror of colonial oppression that many people did not want a new generation to be born into the world.

That said, some local people living under colonial conditions prospered not just as soldiers and civil servants but as business and professional people.

They were labor contractors, and merchants, and large property owners.

The Tagores of Bengal owned agricultural estates but as the English advanced, they invested their growing funds in establishing silk and other mills while also serving as high level agents for British companies in India.

Rabindranath Tagore of that family won the Nobel Prize for Literature in 1913 -- the first non-European to do so.

Empire builders justified their conquests by describing themselves as fully entitled to take the wealth, land, and know-how of distant peoples and even to enslave them.

Initially they argued that local people, whom they often called "savages" needed to be turned into Christians for their salvation.

In this explanation, imperialism became a holy endeavor, as it had been for the Spanish and Portuguese more than three centuries earlier.

But after the mid-nineteenth century publication of Charles Darwin's Origin of Species and The Descent of Man, empire was viewed as imperative in order to save civilization from violent brutes.

Now, I know what you're thinking. "I've studied European history a bit, and its pretty violent."

We agree, obviously, but people tell themselves stories in order to justify the oppression of others.

And indeed, to justify wherever they find themselves in life.

In this telling, humans had evolved from lower forms of existence, and Darwin argued that human development reached a pinnacle in white men.

So according to him, all people of other races were less-evolved and less accomplished.

Social Darwinists -- people who took Darwin's scientific studies and made them the basis of expansionist and domestic politics -- believed that white people needed to be engaged in conquest to preserve their superior lives.

So the justification for, say, stealing palm oil or diamonds from colonized regions was that it helped keep white people superior, and those were the people who really mattered.

I know that it's tempting, especially for people who benefitted from colonialism to say that this is all in the past, but the wealth extracted from colonized regions had a lasting effect on both the colonizer and the colonized.

And ideas about race that were constructed to justify colonialism are still deeply ingrained in lived human experience around the world.

Imperialists eventually tried to calm what came to be called the "Scramble for Africa" with the Berlin Conference of 1884-85, which ruled that European nations with outposts on African coasts could claim the corresponding interior region.

There were also conditions, for example, against selling firearms to Africans.

But the main result of all of this was to intensify imperial competition.

The British and French almost came to blows at Fashoda in Sudan in 1898; the Germans threatened French holdings in North Africa early in the twentieth century.

And eventually these growing international tensions within Europe would lead to World War, which we'll hear more about that in a few more weeks.

But for now, I want to ask you to shift perspectives and consider the experience of those who were most negatively affected in this imperialism.

How that imperialism is still shaping life today.

Thanks for watching, I'll see you next time.

'''
