= 1529
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 224.
This is English as a Second Language Podcast’s English Café episode 224. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. While you’re there take a look at the ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog, where several times a week we provide even more help in helping you increase your language proficiency.
On this Café, we’re going to talk about hip hop culture in the United States. Then we’re going to talk about the New York Stock Exchange, or NYSE. And as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion of hip hop culture. Hip (hip) hop (hop) is a cultural phenomenon, we could call it a cultural movement; it’s the way certain people behave and reflects the things they like in a certain time. That’s what a movement is. Hip hop culture “originated,” or started in the late 1970s in New York City among Latinos (Hispanics), and African Americans, along with Afro Caribbean groups, those from the islands in the Caribbean – or Caribbean, either pronunciation is correct. Hip hop culture is still very popular among certain groups of young Americans today.
The hip hop cultural movement is said to have, by people who study such things, four identifying features – four things that are related to this particular culture or “subculture,” which is a culture that is part of the larger American culture. These features include DJing, rapping, graffiti writing, and breakdancing. Let’s look at each one of these separately and try to define them.
The first characteristic we’ll talk about is DJing (DJing). Outside of hip hop culture, a DJ (written with just the capital letters D and J) is a disc jockey, or a person whose job it is to host a radio program, deciding which music is played when, and saying something in between the songs. In hip hop, a DJ is someone who uses two “turntables,” or pieces of equipment that are like record players, to combine two different songs in a new and unusual way, making an entirely new piece of music. That’s one the common things that a hip hop DJ would do.
A second characteristic of hip hop culture is rapping (rapping), which is also sometimes called MCing (MCing). Now, in other contexts, MC stands for master of ceremonies, that’s the person who hosts a special event or an awards ceremony. They’re the ones in front of the room with a microphone, welcoming people, giving information, and introducing other people who are going to speak. In hip hop culture, MCing has a different meaning; MC means to say rhyming words in a rhythmic way, sometimes while music is playing, but other times without any music at all. These are essentially rhyming poems. Most people refer to this type of music or art as rapping, but others in hip hop culture refer to this as MCing; it’s the same thing. You may have heard about rap songs and rap artists in your own language. I will not do any rapping on this episode, I’m sorry!
A third characteristic of hip hop culture is graffiti writing. “Graffiti” (graffiti) is an Italian word originally; in English, we use it to describe the type of drawing or painting that you sometimes see in big cities on the walls of buildings, next to major streets, perhaps in a city like New York on the train or subway cars. The people who put the graffiti on there do not have permission; it’s not supposed to be there, but they do it anyway. Most graffiti is made by using an “aerosol” paint can, paint that can be sprayed out of a can like you might use with hairspray. Good graffiti artists use many different colors and write text in a special style, which they call “wildstyle,” that is almost impossible for people to read unless they’re very familiar with hip hop graffiti. In fact, usually it doesn’t look like English at all, and many times the letters don’t look like English letters. Of course, people outside of hip hop culture generally do not like to see graffiti; certainly business owners don’t want graffiti on their walls. Some people consider some graffiti to be art, and there are even some graffiti artists that have become well known for their graffiti.
The last characteristic of hip hop culture is breakdancing. Breakdancing, which hip hop followers call breaking or perhaps b-boying or b-girling is sort of hard to describe on the podcast. You probably have seen it however. It was very common in the 1980s, when people did breakdancing on basketball courts and on sidewalks. In breakdancing, the dancers move their bodies in unusual ways, often supporting all of their weight on just one hand or moving their body into different positions very quickly. Breakdancing was, and I guess is, still mostly done by young men, but there are some young women who also breakdance. In hip hop culture, there are breakdancing battles, or competitions. Normally a battle is an important fight, but in breakdancing, a battle means people are competing to see who is the best break-dancer. They don’t actually fight each other, or if they do, it’s not part of the competition.
There are other characteristics of hip hop culture, but the four I’ve just described seem to be the most important, the ones that people would recognize. Of course, hip hop has changed, and people have given it new meanings. There is also the issue of hip hop “fashion,” the type of clothing that people wear, that’s usually easy to recognize. The men tend to wear very baggy (baggy) – or baggy, if you don’t like my Midwestern accent – clothing. That is, their pants tend to be very big for them. Something that is “baggy” is something that is too big for you. And in hip hop culture men often wear pants that are too big for them, shirts that are too big for them. It’s also common for them to have their pants – their jeans or whatever they’re wearing – to be very low on their body; they almost seem to be falling off. There are also other parts of hip hop fashion: baseball caps or hats are sometimes worn, but they’re usually worn backwards. That is, the front part of the hat faces the back, not like you would see on a baseball team. There’s also, very commonly, a lot of big, heavy, metal jewelry; the slang term for this is “bling” (bling).
Some people view hip hop culture as a way for young people to “rebel,” or fight against difficult, perhaps even oppressive social conditions. Something that is “oppressive” (oppressive) is controlling or very difficult and doesn’t allow you to do what you want. An oppressive social condition might be that, for example, many “minority,” or non-white groups have a greater rate of “poverty,” lack of money, and fewer opportunities for education and good jobs. Some people think that hip hop culture is one way that men and women, boys and girls – many of them – in that situation can somehow fight against it, or somehow show their disapproval of those situations.
Some researchers think that early hip hop culture actually helped reduce gang violence. “Gangs” (gangs) are groups of young people who spend a lot of time on the streets; they often are fighting each other. Here in Los Angeles, there are many criminal gangs that are involved in drugs, prostitution, other forms of violence, killing people, doing things that are certainly not legal. Of course, that’s not the only thing that gangs do, but that is one of the things, at least in a big city like L.A., that happens. Gangs can be very dangerous and deadly. But some people say that early hip hop gave young people something else to do with their time, so they would not be part of gangs. They could express themselves through their own art and music. However, in recent years, hip hop has become more connected with violence, drugs, and guns, especially in the rap “lyrics,” or the words sung in songs while rapping. That wasn’t necessarily true when hip hop began more than 30 years ago.
Now let’s turn to a completely different topic: the New York Stock Exchange. A “stock exchange,” sometimes called a “stock market,” is a place where people buy and sell stocks and shares – seems logical. A “stock” or a “share” (they’re the same thing) is partial ownership of a company. So for example if you’re a company, and you need money – you need money to expand your business, you can sell part ownership in your company by selling something called a stock or a share. When people buy them, they then become owners of a very small part of the company. People buy stock because they hope that over time the company will be successful and the value of their investment – of their stock will increase. They can then make money by selling the stock to someone else at a higher price than what they paid for it.
As you can guess from the name, the New York Stock Exchange is not in Los Angeles, it’s in New York City. The New York Stock Exchange is actually the world’s largest stock exchange. In October of 2008, the value of all the companies listed or included in the stock exchange was about 10.3 trillion dollars.
The center of the New York Stock Exchange is what is called the “trading floor.” “To trade stocks” means to buy and sell them. The floor is a large open area where many “traders,” people who buy and sell stock for their clients, make agreements with each other. There are technically 1,366 seats on the trading floor – you can actually go and see them – meaning that are about 1,366 people who are allowed to buy and sell stocks on the trading floor. Many financial professionals want to be able to buy and sell stocks directly on the New York Stock Exchange. They don’t want to hire one of the people who already has a seat, they want their own seat, so the seats are very expensive. In fact in 2005, a seat sold for 3.25 million dollars – it’s a very expensive chair!
In the past, the trading floor used to be a very noisy and “chaotic,” a very disorganized place, with mostly men shouting at each other to buy and sell stock. Today, however, most trades are electronic, and there are large computer screens on the trading floor for traders to look at as they work.
In order to determine how well the stock exchange overall is doing, there’s something called the NYSE Composite Index. This is a measurement that lets people know how well the overall market is doing. Its base value, or the amount that it is calculated from, is 5,000 points, equal to the amount that the New York Stock Exchange stocks were worth at the end of 2002. So the 5,000 points is, in some ways, arbitrary; it’s just a way of trying to measure whether things are getting better or worse. If you listen to people talk about the stock market in the United States, you’ll probably hear them say that the market is up or the market is down a certain number of points, in which case they’re talking about, often, this New York Stock Exchange Composite Index. There are other indexes also: the Dow Jones Industrial Average, for example, is the name of another index that lets you know how stocks in general are doing.
The New York Stock Exchange is normally open for trading during the week from 9:30 in the morning until 4:30 in the afternoon Eastern Time (that is, New York time). However, when there is a large “drop,” or decrease in the value of stocks, the stock market can be closed temporarily. If stocks drop 10 or 20 percent, the New York Stock Exchange closes for a short period of time. If the overall index drops 30 percent, it closes for the rest of the day. The reason for this is that they want to give traders time to calm down and think. Sometimes people get too involved and psychologically don’t always make the best decisions. If everything is dropping in price, people begin to sell, which of course causes the price to go lower even more. They’re trying to prevent, by closing the market, a “panic,” which is an uncontrollable fear; a very terrible fear is a panic.
The New York Stock Exchange also closes when there are other national events. For example, it has closed for the funerals of former U.S. presidents; it has also observed “moments of silence,” a few minutes when trading stops and nobody says anything, for perhaps a death, an explosion (when the space shuttles exploded, there was a moment of silence), for American soldiers at war, and others. Perhaps most famously, the New York Stock Exchange closed for four days after the attacks on the World Trade Center on September 11, 2001.
Now let’s answer some of the questions that you have.
Our first question comes from Gleb (Gleb) in Russia. Gleb wants to know the difference between “effectiveness” and “efficiency.”
“Effectiveness” is the degree or amount to which someone or something is able to produce a particular result. Something that is effective is something that does what it’s supposed to do; it’s able to do what you expect it to do. When we say something is “effective,” we mean that it works; it does what you want it to do. “Effectiveness” is a noun, with that same idea. You could say, “His flowers are beautiful because of the effectiveness of the plant food he uses.”
“Efficiency” is the degree or amount to which someone or something works well without wasting time or effort. “Effectiveness” has to do with producing the expected or desired result; “efficiency” has to do with doing something without wasting time, money, and effort. You can be very effective – you can do something well, but not very efficient. You could take a long time to do it, or spend a lot of money; you may be effective, but you’re not being efficient. If you go outside and build a big fire – huge fire, which is two or three feet tall, you can take that fire and use it to cook a hot dog. It would be effective for that, but it would not be very efficient because you don’t need a big, huge fire to cook a hot dog outside, and you would be wasting a lot of energy and money.
Ibis (Ibis) in the State of Rhode Island, here in the United States, which is, by the way, the smallest state by area in the U.S.; it’s located on the East Coast near Connecticut and Massachusetts. Ibis has a question about the word “jilted” (jilted).
Well, this is something of an old-fashioned word; you don’t hear it that much anymore, but you might read it. “Jilted” is used to describe when a boyfriend or girlfriend has been abandoned, usually very suddenly and sometimes cruelly – not very nice. “Poor Kendra was jilted only two weeks before her wedding.” She was planning on getting married in two weeks, and her boyfriend left her; he even said that she was not someone he would want to marry. So that was a little cruel – a little mean. The actor Ben Affleck jilted the actress and singer Jennifer Lopez right before they were going to get married. He left her suddenly, and not in a very good way. As you can guess, “jilted’ is the past tense of the verb “to jilt” (jilt).
If one is the person who is ending the relationship – if you are the person who is telling your boyfriend or girlfriend “sorry, see you later,” then we don’t normally use the word “jilt.” “Jilt” implies there’s some wrongdoing – something that you did wrong. You would probably not say, “I jilted my girlfriend,” what you’re really saying is you did something wrong. Now if you’re honest, maybe you would.
“Jilted” is also used when we’re talking about a fairly serious relationship, people who are about to get married for example. “Jilted” is more often used when a wedding is called off because the other person suddenly decides to cancel it. That’s what happened to Jennifer Lopez by Ben Affleck. You got a feeling I don’t like Ben Affleck? Well, I just think it wasn’t a very nice thing to do. He can be a good actor; not a great actor, but, eh, he’s a good actor.
Tom in Germany wants to know the difference between “hence” and “thus” (thus). Both “hence” and “thus” can mean the same thing; they can both mean because of something. For example: “My gas tank is empty, hence my car won’t move (my car won’t run).” You could also say, “My gas tank is empty, thus the car won’t run.” Or you could say, “I don’t have any tickets to the Dodger baseball game, hence I will not be taking my wife,” or “thus I will not be taking my wife.”
Both of these words are less common than another word we would probably use in many situations where we used to say “hence” and “thus,” and that is simply the word “so.” “It’s raining today, so I am not going to go jogging.” You could say “hence I will not go jogging” or “thus I will not go jogging,” but that is rather old-fashioned; most people don’t use those words in that sense anymore. You’ll see them in written English more often than in spoken, or oral, English.
There is one more use of the word “hence,” and that can mean coming from this place or coming from this thing. “This dog is very dangerous, hence his name: Killer.” You’re saying that “Killer” comes from the fact that he is very dangerous. An additional, also rather old-fashioned use of “hence” would be to talk about a certain time in the future. “Two years hence, I hope to have a new job.” That means two years from now – two years into the future, I hope to have a new job. You’ll sometimes hear that.
There’s a related term “henceforth” (one word), which is very formal and means from this point onward. “Because you have done well in school, henceforth you shall be called ‘the smart one.’” It’s something you might read in an old novel more than anything else.
We’ve used up all of our time, thus we will not be answering any more questions today. But if you have a question you would like us to answer in the future, you can email us at eslpod@eslpod.com, and we’ll try to answer it on a future Café.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Please come back and listen to us on the next episode of the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010
Glossary
hip hop – a cultural movement (a way that a certain group of people behave and the things they like) that began in the late 1970s in New York City among Latinos and African Americans, that affected music, dancing, art
* Danny listens to mainly hip hop music on his MP3 player.
DJ – disc jockey; a person whose job is to host a radio program or musical event, deciding which music is played when, and saying something between songs
* The DJ at our wedding played some strange songs that nobody wanted to dance to.
to rap – to say rhyming words in a rhythmic way, sometimes while music is playing
* The students got very creative and presented their project ideas in a rap to the rest of the class.
graffiti – the type of drawing and painting that is seen in cities on the walls of buildings, next to major streets, or on train cars
* It’s such a shame that the new bank building down the street is already covered in graffiti.
breakdancing / breaking – a type of dance where dancers move their bodies in unusual ways, often supporting all of their weight on just one hand and moving their body into different positions very quickly
* The show we saw in Las Vegas included dancers performing spectacular breakdancing moves.
oppressive – being under another’s control; being prevented by others from doing what one wants to do
* Our elementary school had very strict rules and most of the students found it very oppressive.
stock exchange – a place where people buy and sell company stocks and shares; the business of buying and selling stocks and shares
* Working at the stock exchange was an exciting, but stressful job.
stock – partial ownership of a company; owning a small piece of a company
* Ellen lost a lot of money in stocks and is now putting her money in the bank.
trading floor – a large open area where people who buy and sell stock for their clients make agreements with each other
* Making the wrong hand movements on the trading floor can get a stock trader into a lot of trouble.
NYSE Composite Index – a measurement that lets people know how well (or how poorly) the stock market is doing
* Get me information on how well this company’s stock has done over the past 10 years according to the NYSE Composite Index.
base value – how much something is worth at the beginning before changes occur; the amount that another number is calculated from
* I wish we could pay the base value for this stock instead of its current value.
panic – uncontrollable fear; sudden extreme fear
* Don’t panic! The car has run out of gas, but we’re on a busy road and someone will come along soon to help us.
effectiveness – the degree or amount to which someone or something is able to produce a result or a product
* We won’t know the effectiveness of the new machines until we begin production in January.
efficiency – the degree or amount to which someone or something works well without wasting time or effort; the ability to use the least amount of time, effort, and materials to produce something
* The company is bringing in an expert to help us increase our efficiency.
jilted – a situation where one member of a romantic couple ends the relationship; ending a romantic relationship, usually suddenly and perhaps unkindly
* Petra found out she had been jilted when Danny took another girl to the dance.
hence – because of a reason or idea already expressed; therefore; for this reason
* The city had a lot of rain this year, hence the many repairs needed on the roads.
thus – because of a reason or idea already expressed; as a result
* Jemima threw the final punch and thus won the boxing match.
What Insiders Know
The Movie Wall Street
In the United States, the 1980s were known as a “decade” (10-year period) of “excess,” with people making and spending too much money, and always wanting more, better, and bigger things. One movie that “epitomized” (was a perfect example) of this excess was Wall Street.
The movie “starred” (had as the lead actor) Michael Douglas who played a wealthy and “unscrupulous” (without moral principles; dishonest) businessman. He is admired by a young “stockbroker” (someone whose job is to buy and sell stocks) who is very “ambitious” (wanting very much to be successful). This young stockbroker does some dishonest things to get the attention of the businessman, and the businessman takes the young stockbroker “under his wing” (giving him the benefit of his help and encouragement). Overtime, the young stockbroker becomes more and more “corrupt” (acting dishonestly), and begins to live by the businessman’s “creed” (guiding belief) that “greed” (selfish desire for money and power) is good.
“Ultimately” (in the end), this film was a criticism of the culture of the 1980s when everyone was trying to “make a quick buck” (make money quickly, often without regard for honesty and fairness to others). Several examples of this corrupt culture included “high profile” (receiving a lot of attention) cases of stockbrokers who broke the law by participating in “insider trading,” which is when people buy and sell stocks because of secret information they learn about companies that no one is supposed to know.
The film got a lot of attention when it was released. The star, Michael Douglas, received an “Academy Award” (the most respected film award in the U.S.) for his role, and it is still referred to when talking about the excesses of Wall Street today.