= 1509
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 204.
This is English as a Second Language Podcast’s English Café episode 204. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog.
On this Café, we’re going to talk about fraternities and sororities, which are organizations that many college students join when they go to a university. We’ll also talk about foster care and the adoption system in the United States, looking at what happens to American children when their parents die or are unable to take care of them. And as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion of fraternities and sororities, which I think is although not unique to the United States (in many countries students have organizations; in Europe, I believe these are sometimes called corporations), it does have some attributes – some characteristics that are found mostly in the United States alone. Fraternities and sororities are organizations that some college students join when they begin to study at a university. The word fraternity is used here to talk about a group of men who have a close relationship or friendship with each other and who work together in some way. The word fraternity can be used in a broader context to talk about other kinds of organizations. But in this Café, and we talk about American universities, we're referring specifically to this organization of men students – male students who are going to the same college or university. Basically, the fraternity is a club for male students. A sorority is an organization or club for female students.
Most fraternities and sororities have names that use Greek letters. For example, you may hear students talking about Phi Delta Theta (???), Sigma Chi (??), and Phi Mu (??). These are combinations of letters in the Greek alphabet, and the fraternities and sororities – these clubs at the university typically use the letters from the Greek alphabet to name their club. That is why sometimes this is called the Greek system, because they use the Greek alphabet.
When students come to a university, they can be asked by friends or others they meet whether they want to participate in a process called rush, which is the period of time when students can learn about different fraternities and sororities on campus, or at the university. What happens is in the fall of the year, when new students come to the university or college, they may be invited to participate in rush, and in many universities there’s a week early on in the fall called rush week. Students can then go and visit with these different groups, talk to people, and decide if they want to join one of these fraternities for men and sororities for women. During rush, students are invited to visit different fraternities and sororities. The fraternities and sororities also get a chance to meet these people and decide if they want them to be part of their club.
If a student decides that he or she is interested in joining a particular fraternity or sorority, the next step is to pledge. “To pledge” (pledge) a fraternity or sorority means to apply to join, although it isn’t like other application processes that you might be familiar with. There aren’t forms to fill out or essays to write. Instead, when students pledge, they have to do things, often strange and sometimes embarrassing things, to show how much they really want to join the fraternity or sorority. Once pledging is finished, there is an initiation ceremony, a special event where the people who want to join this group, called the pledges, become full members of that sorority or fraternity.
Students who belong to fraternities or sororities refer to each other as brothers and sisters; fraternity comes from “frater,” sorority comes from “soror,” brother and sister in Latin. It gives them a home away from home, usually because they can develop friendships within the sorority or the fraternity. Some people ask why do they join fraternities and sororities, and one reason is because if they’re new to the university and they may not know a lot of people, they see this as an opportunity to make new friends, to join this particular club. It’s never clear to me, however, since I was never a member of a fraternity I don’t have any personal experience in this, why or how people decide to join one group versus another. I suppose it just has to do with the people in those groups and whether you like the people in those groups. We’re talking here about a minority of students; that is, most students do not join fraternities and sororities. In some universities, they’re very popular; in other universities, there are very few of them, sometimes none of them.
Many of those who join these fraternities and sororities live in a house that is owned by the club or the organization called a fraternity house or a sorority house. It’s a special building where they can live, at least for the first couple of years while they are studying at the university. It’s normally not required that you live at the fraternity or sorority house to be a member, but it is very popular for people to do so. For fraternities, these are sometimes called frat houses (frat). “Frat” is an informal expression meaning fraternity. Although I heard from one person, who was a member of a fraternity at a university where I was teaching, that they didn’t like that term “frat.” But it’s very common on campus for people to talk about frat houses. They’ll also talk about people who are members of fraternities as “frat boys” or “sorority girls,” not necessarily in a complimentary way. Sometimes the reputation of fraternities and sororities on campus, among the students and the faculty and the teachers, is that is a place where people go to party – to drink. It’s a social organization, but it also has some negative aspects to it. However, before talking about those negative aspects, we’ll talk about some of the positive ones.
Many fraternities and sororities are organizations that have an academic or a professional focus. For example, they may be students who are all in engineering or in a particular area of study. They might also be students who are members of a particular group. On some campuses, there are some fraternities and sororities that are mostly African American students. Or here in the State of California, where there are a lot of Asian American students at the university, it may be an Asian American sorority or fraternity.
Most fraternities or sororities are what we would call service organizations, at least that’s one of the things they are. That means they try to help other people in the community. Many fraternities and sororities organize fundraisers, which are special events when they try to get money (funds) in order to donate that money – to give that money to children’s groups or to hospitals or other groups in that city or community that need help. So, there’s a positive aspect to these organizations; they try to get money for other groups.
However, as I said, there also has been some negative things that have been said about fraternities and sororities. Some fraternities and sororities have been accused of hazing (hazing). “Hazing” is when a group abuses or tries to hurt people or a group of people. Remember I said that when students pledge a fraternity or sorority – when they try to join this group, they have special parties and meetings where the pledges have to do certain things, often embarrassing things. This is not necessarily hazing, but if it becomes dangerous, if they are asked, for example, to drink too much alcohol, to do drugs, to hurt other people or to hurt themselves, that could be considered hazing. Now, most fraternities and sororities ban hazing, meaning they don’t allow it, but I still happens at many – well, I don’t know many – at some fraternities and sororities. Fraternities and sororities are university-registered groups; the university recognizes them as student groups. If, however, they are accused of hazing, they can be removed from the university, or the university could investigate to find out whether any hazing took place. Again hazing is the process of trying to hurt or somehow damage the pledges that are trying to join your fraternity or sorority.
There are other criticisms of fraternities and sororities. Some people say the groups are very exclusionary. “Exclusionary” comes from the verb “to exclude,” which means to not allow something, to not allow a certain person or kind person from joining your group. The most obvious way that fraternities and sororities could be exclusionary is by the cost of joining the organization. These organizations aren’t free; you have to pay several hundred dollars, sometimes more, just to be a member. That’s why some people who criticize fraternities and sororities say they’re just groups where you pay to have friends, but that’s probably an unfair criticism for most fraternities and sororities, though it was a common one when I was at the University of Minnesota.
Fraternities and sororities do sometimes, however, specifically focus on a particular group, as I mentioned before; it might be for social reasons, it might be for academic reasons. Fraternities and sororities are, however, almost always undergraduate organizations, meaning students who are studying in their first four years for their bachelor’s degrees. It’s not something you would find at the graduate level.
Fraternities and sororities, then, have a mixed reputation in the United States. There are some people, especially those who are or were members of the organization, that defend the groups – say that they are good things. Again, it’s a minority of people who actually become members of fraternities and sororities. There are other people who have criticized the groups for the reasons we’ve mentioned, but basically these are clubs just to allow students to do a lot of drinking and partying. There was a famous movie in the 1970s called Animal House, staring John Belushi, about a fraternity. This is a film that depicts (or describes) a fraternity where the only reason that people become members really is to have fun and to drink, so that’s not a very positive portrayal – a positive depiction of what happens in fraternities and sororities. Again I was never a member; it never really interested me, and none of the members of my family were in fraternities or sororities. But they are a very common part of American college life; you can’t go to an American university – a large university and not be aware of or see these Greek organizations, as they’re called, on campus.
Our second topic today is quite different, we’re going to talk about what happens to children in the United States when their parents die or they are no longer able to take care of them. Sometimes what happens when parents are judged to be “unfit,” that is, not having the capacity to take care of the children – the government makes that decision sometimes in extreme cases, when the parents, for example, are on drugs or alcohol and are not taking care of their children. Ideally, in the perfect world, we want children to grow up with their parents, but this isn’t always possible. Sometimes when that happens, when there’s a reason why the parents cannot take care of the children, they live with “relatives,” other family members. Sometimes, however, there is no one for the child to stay with, or none of the family members want to take the child in. The phrase “to take (someone) in” means to let someone live in your house, to take them and allow them to be part, in effect, of your household – of your family, perhaps. You, however, could also take in a dog or a cat, but here we’re talking about taking in a child, which, of course, is a lot of responsibility and a lot of work. When nobody wants to take the child in, the government has to find a home for that child.
The United States does not have a system anymore of orphanages. An “orphan” (orphan) is a child who has lost their parents, perhaps they have both died, and they have nowhere to go. In the old days there used to be special houses – special buildings where children would all live together in one area, what is called an “orphanage,” and these are still common in many countries. Here in the U.S., however, there aren’t large orphanages anymore. Most of the children who don’t have parents to live with, who are orphans or who are taken away from their parents for a variety of reasons, don’t live in orphanages, they live with individual families. We call these “foster” families.
Foster care is the system that gives children a home with a family, often a temporary home. Many children end up in foster care if their parents, as I said before, had problems with drugs or alcohol and it’s not safe for the child to live with the parents. People who take in the children are known as foster parents. They agree to have the child live with them, at least temporarily. They don’t, however, adopt the child; that is, they don’t make the child legally part of their family; the child is just sort of living there and being taken care of by the foster parents.
People have to receive special training and education to become foster parents in most states – most counties (a county is a smaller part of the state). Once a foster child starts to live in their home, the foster parents then receive money from the government to help take care of the child, to pay for the child’s food, clothing, education, and so forth. A foster child might be with foster parents for a few days, a few weeks, or perhaps even a few years.
During that time, the government tries to find a permanent home for these children. In other words, they try to get the child adopted. “To adopt” means to make a child a permanent part of your family. Many people who cannot have children, perhaps because of medical problems, choose to adopt children. Other people adopt children because they feel sorry for them, they want those children to have permanent home, and so they adopt them and love them. It’s also possible for the foster parents to adopt the child. They may grow to like the child and decide they want the child to be part of their family permanently. Sometimes another family will adopt the foster child.
Although the governments try to get foster children adopted as soon as possible, sometimes it isn’t possible. Sometimes children will grow up their whole lives, until they are 18 years old, being part of a foster family. It’s particularly difficult for older children – 5, 6, 7, 10, certainly teenagers – 14, 15, 16 years old, it’s difficult to get them adopted, and often they will be with foster families until they become of legal age – until they become adults at 18. Unfortunately, in many places their government assistance ends immediately and they have to leave the house right away. Here in Los Angeles, for example, almost half of the foster children who become 18 eventually end up either in jail or living on the street. It’s a very said, unfortunate situation. The government doesn’t provide them any support, and of course they don’t have a family who will help them once they become adults.
Another unfortunate thing that happens with these children is they basically get stuck in the foster care system. “To get stuck in (something)” means that you are not able to move out of it, or to get away from it. When a child gets stuck in the foster care system, he or she might be moved to different houses several times before they turn 18, because nobody wants to have them as a permanent part of their family. Often children in the foster care system have been hurt or abused by their own parents and so they need a lot of psychological help, so it makes it very difficult for these children growing up.
There are, however, many happy cases of children who are adopted and who become successful out of the foster care system. But unfortunately, there are many who do not. So, it is another area where our country needs to improve its services, I think, for these children.
Now let’s answer a few of your questions.
Our first question comes from Roberto (Roberto) in Spain. Roberto wants to know the difference between a “scholarship” and a “grant.” Both scholarships and grants are things that you receive, usually to study at a university or a college; it’s money that is given to you.
A scholarship is usually a gift of money to a student because of their academic record – because they are smart, they’re good students, or because they are, perhaps, members of a certain group where the organization gives money to people who are members or children of members. A grant is also money that is given to a student to study. It usually, when we talk about universities, is something that is given because the student has what is called “financial need,” meaning they don’t have enough money, so the government or another organization gives them a grant. Both scholarships and grants are gifts; that is, the student does not have to give the money back later (that would be a loan).
The word grant has a more general meaning outside of the university, or within the university but not referring to students. A grant can be any money that an organization gives a person or a group to do some special project. So, university professors can get grants to conduct (or carry out) their research. An organization that helps homeless people, or perhaps foster children, could receive a grant, money from the government or from another private organization to help them do some special project. But when we talk about the university, scholarships and grants refer to money given to students.
Our next question comes from Uwe (Uwe) in Germany. The question is about the expression “to be a commie” (commie). Commie is a negative term to describe a member of the Communist Party. Someone who has views similar to the Communist Party could also be called a commie. The word was used especially in the 20th century – the early and mid parts of the 20th century as an attack on those who held views similar to the Communist Party. Sometimes, however, it was used on people who were not communists or communist sympathizers, which in American politics was certainly a very dangerous thing to be, but rather people who simply had liberal ideas.
Although communism is still around in the world obviously, the word is not used very much anymore in modern American English. You’ll see it in movies, you might see it nowadays more as a joke; when someone is calling somebody a commie it could be because they’re trying to insult that person or paint that person as someone who is somehow extreme. But again, it’s not a term we use much anymore; it was much more popular, say, in the 1950s and 60s, especially when the then Soviet Union and the United States were considered enemies during what is commonly called the Cold War.
Well, we don’t have any wars here, other than the war to help you improve your English – if that can be considered a war. You can email us at eslpod@eslpod.com. If you have any questions, we’ll be happy to help you fight this battle.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse, copyright 2009 by the Center for Educational Development.
Glossary
fraternity – an organization or club at a university for male students
* Dean joined a fraternity when he started college and stayed friends with several of his fraternity brothers after he graduated.
sorority – an organization or club at a university for female students
* We don’t want to join that sorority because the members aren’t very friendly.
rush – the period of time when students can learn about different fraternities and sororities on a university campus and decide which ones, if any, they might want to join
* During rush, we visited six sororities and talked to their members.
to pledge – to formally apply to join a fraternity or sorority
* Let’s pledge the same sorority so that we can become sorority sisters.
initiation ceremony – a special event where applicants become full members of a club, organization, or group
* During the initiation ceremony, each member lit a candle and read from the official club handbook.
service organization – an organization that tries to help other people in the community.
* In high school, she joined a service organization that passed out blankets to the homeless.
hazing – when an organization requires its applicants to do strange, embarrassing, or dangerous things to show how much they really want to join the organization
* Although the school denies any hazing, graduates tell us that it is still going on today.
exclusionary – not allowing certain types of people to join; keeping out of certain groups of people
* The country club eliminated its exclusionary rules against women over 20 years ago.
to take (someone) in – to let someone begin living in one’s home
* I lost my job and I don’t have any money. I hope my sister will take me in for a few months until I can find work.
foster care – the system that gives children a temporary home with a family until a permanent home can be found for them
* After their parents died, Cathy and Eddie were put into foster care.
to adopt – to make a child a permanent part of one’s family; to make a child a legal part of one’s family
* How old were you when your parents adopted you?
to get stuck in – to not be able to move; to not be able to get away from something
* I’m afraid to get stuck in a low-paying job with no possibilities for promotion.
scholarship – money given to students to help pay for the cost of attending a private school or university
* Without a scholarship, Shawn would never have had enough money to enroll at the university.
grant – money given to a person, organization, or company, usually by a charity (group that exists to give help to others), the government, or a wealthy person to do something useful for society, such as scientific research or helping the poor
* Our community group received a grant to turn the empty lot in the neighborhood into a park.
commie – a negative and insulting term for a member of the Communist Party; an insulting term for someone who is seen to have views similar to communists or to the Communist Party
* Why do you call him a commie just because he thinks we need more equality in our society?
What Insiders Know
Orphans in Literature: Jane Eyre, Oliver Twist, & Anne of Green Gables
When we look at “literature” (books; written works), we “come across” (encounter; see) many books with orphans as main characters. In “classic” (judged over a period of time to be of very high quality) literature, two of the most well known orphans are Jane Eyre and Oliver Twist.
Jane Eyre, written by Jane Austen, is about a girl whose parents died and whose aunt puts her in an orphanage for girls. When she becomes an adult, she finds a job as a “governess” in the home of a rich man. Wealthy people hired “governesses” in the old days to take care of their children and act as the children’s teacher. There is a secret in this big house, and Jane eventually finds out what this terrible secret is.
Oliver Twist was written by Charles Dickens and is about a boy whose mother gives birth to him and then dies. He runs away from the “cruel” (unkind; causing pain and suffering) people taking care of him and goes to London, where he works with many other boys for a group of street criminals. There is a secret about Oliver’s birth and eventually he finds out about his real family.
Jane Eyre and Oliver Twist were written before the twentieth (20th) century, that is, before the 1900s. More recently, Anne of Green Gables has become very popular with children, teenagers, and adults alike. Anne of Green Gables, and the other books about the character Anne by Lucy Maud Montgomery, is about an orphan who is adopted by an older woman and her brother. At first, her new “guardians” (people who have legal rights and responsibilities for a child) are unsure about Anne. They had originally hoped to adopt a boy to help work on their farm. However, Anne’s “sunny” (happy) personality “wins them over” (cause them to like her) and they come to love Anne very much.