= 1514
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 209.
This is English as a Second Language Podcast’s English Café episode 209. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes. It contains all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes – oh, yeah, a complete transcript of everything we say on this episode. Pretty cool! If you want to support us, consider becoming an ESL Podcast member or making a donation on our website.
On this Café, we’re going to talk about what is sometimes called the Golden Age of Hollywood and something called the studio system, which is the way that movies used to be made here in beautiful Los Angeles. Then we’ll talk about a controversy from American history back in the 1970s over school busing. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion about the Golden Age of Hollywood. Normally the word “golden” (golden) refers to a bright, yellow- or what we call gold-colored metal. For example, if you buy a nice ring or a watch, it could be made of gold. There’s also something called white gold, but here we’re talking about yellow gold. In this context, however, “golden” refers to the best period of time. Someone may talk about “the golden years,” referring to the time after you retire from your job and are free to enjoy your life because you don’t have to work anymore. The expression “Golden Age” is often used to describe a period when things were at the very best, especially artistic things, so we might talk about the Golden Age of Spanish Theater or the Golden Age of Japanese Cinema (Japanese movies). Here, we’re talking about the Golden Age of American Movies – the Golden Age of Hollywood. The Golden Age of Hollywood is the best period of time – what some people think was the best period of time here in Hollywood for American cinema – American movie-making.
The Golden Age of Hollywood is said to have begun in the late 1920s and ended in the late 1950s. Some people, of course, say that there is no one Golden Age, that there are still good movies being made, but when someone says the “Golden Age of Hollywood,” they’re referring to this period between the 20s and the 50s.
It began when the “silent area” of movie-making ended, the period of time when there was only “silent movies,” movies that didn’t have talking, because the technology at the time didn’t allow filmmakers (people making movies) to record what the actors and actresses were saying, so you had silent movies, people like Charlie Chaplin and Buster Keaton. Once movies could include sound, more people started to watch the movies and movie-making became more “profitable,” meaning that the companies that made the movies, what we call the “studios,” started to make more and more money.
Some of the greatest Hollywood movies were made during this Golden Age. These include one of my favorite movies, Citizen Kane, which many people say is one of the greatest films “of all time,” or one of the best films ever. Some would even say it is the best film ever made, I’m not sure if that’s true. Other films created during this time include The Wizard of Oz, Gone with the Wind, Only Angels Have Wings, Casablanca; one of my favorite movies, It’s a Wonderful Life, with Jimmy Stewart; King Kong, and there are others. If you haven’t seen any of these films, what’s wrong with you? You should definitely go out and see some. These are “classic” films, films that are well known, admired, considered some the best films and most important films. You can also learn a lot about American culture by watching some these films – or at least learn what American culture used to be like before Arnold Schwarzenegger became an actor!
The Golden Age of Hollywood is also remembered for its use of something called the studio system. I mentioned “studios” were the companies that made movies. A “studio” is also a room or a building where creative things are done. An artist, for example, might paint or draw in his artist studio. ESL Podcast is made in a recording studio – not a very good one, though! Films are made by movie studios, so those are the companies that make the movies. And that’s, when we talk about the studio system, what we are talking about is the companies that make these movies.
Under something called the studio system, movie studios had thousands of people on salary. The phrase “to have (someone) on salary” means you pay someone a certain amount of money every year. Most people, if they have a full-time job, are on salary; they don’t get paid by the hour. Although normally you work only 40 hours a week, they get paid for being an employee even if they have to work extra hours – more than 40 hours a week. That’s called being on a salary. This also means that companies continue to pay these people even if they’re not working. If there is no work to be done, and they’re on a salary, they’re still being paid. Today, movie studios here in Los Angeles and in other cities that make movies – New York, Vancouver, Toronto, London, Bollywood, and so on and so forth – most of these movie studios use “contractors,” people who are hired and paid only for a short period of time, and when the project is over, that’s it, they don’t get paid anymore. But under the studio system in the Golden Age of Hollywood, actors were typically kept on salary and received a certain amount of money every year. That is, they did not get paid by the movie; if they were in 4 movies versus 10 movies they would get paid the same thing.
Also, studios used to have the same group of people – the same group of actors working on all of their films, or at least most of them. So directors and actors would be “affiliated,” or connected to a certain studio – a certain movie-making company. This means if you worked for MGM, a famous studio in this time period, and somebody else worked for a different studio, say RCA, you wouldn’t see them in movies made by the other company. You would only see actors and directors working within the studio that they were getting paid from, you didn’t work for different studios. Today, it’s very different. Today, actors and directors can work for any studio they want, but back in the Golden Age you worked for the one studio that paid your salary.
Also, during this time under the studio system, movie studios owned and controlled movie theaters throughout the United States. In other words, not only did they make the movies but they also owned the movie theaters that you went to see the movies in. Today, these movie theaters are owned by separate companies that aren’t involved in making movies. But during the Golden Age of Hollywood, things were very different and the movie studios would control the movie theaters, forcing them, for example, to buy an entire year’s worth of films whether they were good or not. Theaters weren’t allowed to show films that were from other studios; they also weren’t even allowed to see the films before they decided whether they wanted to buy them or not. So, the movie studios either owned or controlled the movie theaters.
However, in 1948, the U.S. Supreme Court, or the most important legal body in the United States, said that the way in which movie studios controlled the movie theaters and the distribution of movies was unfair and illegal. This basically ended the studio system, and it ended the Golden Age of Hollywood; by controlling and owning these movie theaters, the studios were able to make a lot more money. So, this Golden Age ended, although, as I say, there were still, and still are, many wonderful movies that are still made under the current system. But the studio system was one in which the movie studios were able to control things much more, and were able to produce, also, some important movies.
Now let’s jump to our next topic – let’s changed to our next topic, which is the busing controversy of the 1970s. A “controversy” is something people don’t agree on. For example, nowadays there is a controversy over global warming, because some people think it’s happening and it’s being caused by humans, other people think it’s a natural process and that we don’t have to worry about it, so you have these different sides of the issue. It’s a controversy. Today we’re going to talk about a controversy related to “busing,” putting school children on buses and taking them from the area – the neighborhood where they live to a school on the other side of town for the purposes of desegregation, which we’ll explain in a moment.
In 1954 there was a famous Supreme Court case called Brown vs. the Board of Education – technically, Brown vs. the Topeka Board of Education. Topeka is a small town in Kansas, which is in the very center part of the United States. In this famous court case, Brown vs. the Board of Education, the Supreme Court desegregated public schools. “To segregate” means to separate people into different groups. It was quite common for schools to be segregated in many places in the U.S., where black students went to one school and white students went to another. “To desegregate” is to take those two groups and put them together, in fact, to make sure that there are both black students and white students and Asian American students and Latino students all together, mixed up in the same schools. So, Brown vs. the Board of Education made it illegal for schools to segregate their students by race. We talk a little bit about this important case in English Café number 166.
Although Brown vs. the Board of Education made school segregation illegal, in reality schools were still segregated, because white people and black people (the two main groups that we usually talk about when referring to segregation in the U.S., least at this period) tended to live in different neighborhoods. The students who lived in the white neighborhoods went to schools in the white neighborhoods, and the black neighborhoods had their own schools with mostly or only black students. In fact, some school districts were drawing their district lines (that is, the boundaries between schools on maps) so that they followed the racial segregation of the neighborhoods themselves. In other words, the area that the school covered – and it’s important to understand that in the United States normally, at least traditionally, you go to the school closest to where you live, and each school has its own little district (its own boundaries; it’s own borders), and if you live outside of that boundary (that border), then you can’t go to school there. So, what they would do is they would draw these boundaries – these lines so that they would separate the black and the white neighborhoods. You would end up with schools that were “predominantly,” or mostly of one race.
Finally in 1971, almost 20 years later, the Supreme Court again had a case in which it decided that it was legal to use busing to end this school segregation. In other words, school districts were told that they had to use buses to take students from the black neighborhoods into the white neighborhood schools and vice a versa in order to desegregate the schools. So, you had all these kids in buses going to different schools on the other side of town in order to have this desegregation.
Although parents and students didn’t have to pay for these buses (the schools provided them for free), it was, for many families, inconvenient. When we say something is “inconvenient,” we mean that you don’t enjoy doing it because it takes more time or it’s more difficult. Desegregation busing was inconvenient for many families, because some students were sent to schools that were many miles from their home, even though there was a school, perhaps, just a mile or less from their house. Parents didn’t like being forced to send their children to these other neighborhoods, but forced busing happened anyway in many cities in the U.S. I remember myself, when I was in school in the 1970s, in elementary school and high school, reading about cities that were involved in this forced busing program.
Unfortunately, the programs did not work as well as the Supreme Court had hoped, or at least they didn’t work in the way that they thought they would work. In fact, forced busing was extremely unpopular among parents in the 1970s. One “poll,” or survey, found that only about 4 percent of whites and 9 percent of blacks thought that forced busing was a good idea, so people really didn’t like the idea. In 1978, one study tried to find out why both black and white parents disliked busing, and they found that it wasn’t primarily due to racism – that is, discrimination against those of a different color, although that was probably part of the reason for some people. Instead, families were worried that this forced busing – forced desegregation would hurt their own neighborhood schools, the schools nearest to where they lived, and create more problems with discipline. Discipline is, of course, a big issue in schools. Normally when we talk about “discipline,” we mean behaving properly – not fighting, not yelling, not doing the things that you should not do in school. In Boston, Massachusetts, for example, 60 percent of the parents thought there were more discipline problems after the forced busing than before the busing began.
Boston, Massachusetts is an interesting case of the problems with this forced busing program. When I was growing up in the 1970s, I would always see television reports and read in the newspaper about problems in Boston about this issue. The rules in Boston said that if more than half of a school’s students were white, forced busing would be used. At one mostly white school, they decided, for example, to send all the students who were in the junior class (all of the third-year students in high school) to another school that was mostly black. Only 13 of the 550 students went to the new school on the first day. The forced busing program caused many parents to “protest,” to fight against the changes. It also caused racial problems in the schools. White and black students would sometimes use different doors to go into the school. Unfortunately, sometimes things became violent. There were whites attacking blacks, and blacks attacking whites. It became so bad that one school actually had to close for an entire month.
Unfortunately, despite all of these problems, forced busing did not really work. When it was ended in Boston in 1988, there were only 57,000 students left in the Boston school district, compared to 100,000 students before it began, and only 15 percent of those 57,000 students were white, meaning that most of the white students had left the Boston public school district. What happened is what we sometimes called “white flight.” “Flight” is to fly, to go to a different place, usually in an airplane. But “flight” can also be used to describe running away from something, and white flight was a case where white families would move to the suburbs – move to a different part of the city to avoid being in the Boston public school system. This didn’t happen just in Boston, however; it happened in many cities in the United States with similar programs.
Unfortunately, this left only the poorer students in many of these school districts, largely minority: black, Latino, Hispanic, African American, Asian American. So, there was really no integration or desegregation. In fact, the schools in some places became even more segregated – more separated, because the white students simply moved to a different city, a different town, or started to go to private schools.
Most school districts no longer have a forced busing program, but busing is still very common. That is, now that parents have gotten used to the schools having these buses available, many parents voluntarily ask that their students study in a different school in a different part of town because they believe it’s a better school. So there is still a lot of busing, but it is mostly voluntary, not forced.
Now let’s answer some of the questions that you have sent to us.
Our first question comes From Daniel (Daniel) in Brazil. Daniel wants to know the differences in meaning of “as well,” “also,” and “too” (too). All three of these can mean the same thing in some circumstances. For example, all of them can mean “in addition,” or “along with”; we might say “likewise.”
Let me give you some examples, it will be clearer: “I heard you’re a painter. Are you a writer, as well?” This means do you both paint and write – do you do both things? You could also say, “I heard you’re a painter. Are you a writer, too?” “I heard you’re a painter. Are you a writer, also?” All of those are possible, and they all mean the same thing. I would say that “as well” is a little more formal; you might hear it in business situations more than informal conversation.
Although the meaning is the same, usually, for these three phrases, their placement in the sentence – where you actually put it in the sentence is different sometimes. “Too” and “as well” are not normally put at the beginning of a sentence. You can say, “Carl wants to go, too,” but you cannot say, “Too, Carl wants to go,” that’s not possible.
“Also,” however, can sometimes be used at the beginning of a sentence to introduce a new phrase. For example: “I want the steak and the salad. Also, could you add some potatoes?” There, “also” can go at the beginning of the sentence because you’re introducing a new idea. But “too” and “as well” are not normally used this way. “Too” and “as well” are placed in the middle or the end of the sentence. “Also” can go at the beginning, middle, or end of the sentence in most cases.
The word “too” (too) can also mean an excessive amount of, when you have more than what is required or necessary. For example: “The music here is too loud.” It is louder than it needs to be or should be.
Leandro (Leandro), also from Brazil, wants to know the meaning of the expression “to take into account.”
“To take (something) into account,” or “to take into account (something),” means to consider, to think about something before making a decision or an action. “You should take into account the rain when deciding what time you will leave this morning.” You should consider it, because it’s going to have an effect – it’s going to have an influence on how long it takes you to drive somewhere. Or you could say, “Taking into account how much this car costs, maybe it’s better to buy a different car.” Considering the cost – keeping those costs in mind and taking them into consideration in our decision. That’s what “taking into account” means.
You will usually hear this expression in a formal presentation or in writing. It can be used in informal conversation, but it’s not that common. It’s often used in the sense of “I gave that serious consideration; I did think about that.”
Finally, Ibis (or Ibis – Ibis), currently living in the state of Rhode Island on the eastern coast of the United States, wants to know why some people say “why, yes” when you ask them a question. Why don’t they just say “yes”? If I say, “Are you going to the art museum?” you would normally say, “Yes, I am.” But it is possible to say, “Why, yes. I am.” “Why,” here, is used as a way of emphasizing the word. It’s also used to show some surprise at the question or surprise at the person who’s asking the question. If Miss America comes up to me wants to know if I want to dance with her, I might say, “Why, yes!” I would be a little surprised!
This use of “why, yes” is a little old fashioned; it’s not as common anymore, but you will still hear it. You will also sometimes hear people use the word “why” as a way of expressing surprise, especially at the beginning of a sentence after someone has asked a question. If someone says, for example: “Have you been stealing money from our company?” you might say, “Why, I don’t know what you mean!” You’re not asking a question with “why,” you’re expressing surprise. Again, this is sort of an old fashioned use; you might read it in a novel or see it in a movie. It’s also something that was more common among higher-classed, richer speakers of the language; it sounds very formal.
If you have a question or comment, you can email us as well. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2009 by the Center for Educational Development.
Glossary
cinema – the business and process of making movies; a movie theater
* I’m reading a book about the history of Indian cinema.
silent movie – a movie without talking; a movie without speech
* Actors in silent movies were very good at using their bodies to communicate emotions.
of all time – ever; from the beginning of time to the present
* I don’t think that song belongs on a list of the best songs of all time.
classic – a very well-known, admired, and important movie, book, or something else that has become part of a culture
* Do you think our English teacher will allow us to read something other than the classics this year?
studio – a room or building where creative things, such as painting, music-making, and film-making, are done
* Why don’t you come over to my studio and we’ll record some music together?
to have (someone) on salary – to pay someone a certain amount of money each year; to employ someone
* For two years, Francine worked part-time for our company, but this year, she’ll be on salary.
controversy – something that people do not agree on; something that causes disagreement
* The basketball player caused a major controversy when he criticized the coach and the other players on his team.
desegregated – making it illegal to have certain schools or facilities only for white students and other schools or facilities for non-white students
* White students and black students still sat apart in the cafeteria after the school became desegregated.
predominantly – mostly; mainly
* Jessie was very happy to see that the students in the art class were predominately female.
inconvenient – causing problems or difficulties; something that one doesn’t enjoy doing because it makes one’s life more difficult
* Would it be inconvenient for you if I picked up my daughter at 3:00 instead of 2:00?
white flight – a phrase used to describe the situation of when white families move out of a neighborhood, leaving only non-white families in the area; the moving out of white residents in cities to the suburbs to get away from immigrants or non-white people moving into the area
* In the 1970s, this neighborhood experienced white flight and is now a completely different place.
suburbs – the area outside of a city with more homes and fewer businesses
* Jean’s family moved to the suburbs after they had their first child.
as well – also; along with; in addition
* I invited Paco and Lin to the party, and Monica and Steve, as well.
to take into account – to consider; to think about something before making a decision or acting
* Did Sam take into account whether he has enough money to live on when he decided to quit his job and become a painter full-time?
why – an interjection (word used to express emotion) meant to show mild surprise, hesitation, or indecision
* - Would you like to go to the movies with us this weekend?
* - Why, yes, I’d love to!
What Insiders Know
The Golden Raspberry Awards (The Razzies)
Most people have heard of the Academy Awards, which are given out to the best films each year and is considered the most “prestigious” (respected) award a movie can receive in the United States. In 1980, a new set of awards was introduced called The Golden Raspberry Awards. These awards “honored” (gave respect) to a completely different type of film: The worst movies of the year. A “raspberry” is a type of red fruit that grows on trees, but the name of the award is referring to “blowing a raspberry,” which is when a person sticks out his or her tongue between the lips and blows, making a noise that sounds like “flatulence” (gas coming out of one’s body). Blowing a raspberry is a way to show that one doesn’t like something or that one feels that something is silly or ridiculous.
“Nominations” (proposing someone or something for an award) for The Golden Raspberry Awards, frequently called the “Razzies,” are announced one day before the Academy Award nominations are announced, and the awards are presented one day before the Academy Awards are given out. In addition to the categories of awards that one would expect – such as Worst Actor, Worst Picture (film), and Worst Director – Razzies are also given out for the “Worst Screen Couple” to two people who are romantically involved in a film. Another Razzie given out each year is the Worst Prequel, Remake, Rip-off or Sequel. A “prequel” is a movie that occurs in time before another film that has already been made, giving the background or early story of the same characters. A “sequel” is a movie that occurs in time after another film that has already been made, telling the story of what happened after the first film ended. A “remake” is a modern version of an older film. A “rip-off” is an “inferior” (lower quality) version of something, taking important parts of the original without “giving it credit” (saying where it came from).
The Razzies are given out “tongue in cheek” (as a joke) and are not taken seriously. Most people do not go to the award ceremony to receive the award, though one or two celebrities have done so to show their sense of humor.