= 1519
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 214.
This is English as a Second Language Podcast’s English Café episode 214. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog.
On this Café, we’re going to talk about something known as psychological pricing, the reason why many businesses decide to sell a product, for example, for 99￠ instead of $1.00. We’re also going to talk about daytime soap operas, which are a special type of television program normally seen in the middle of the day or early in the afternoon. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a discussion about psychological pricing. When you walk into a store in the United States and in other countries, you may notice that prices often aren’t whole numbers. A whole number is a number that isn’t followed by a decimal point, or a period. In the U.S., a decimal point is represented by a period; in other countries, it’s represented by a comma. So, a whole number would be 2, 7, 4,389 – those are all whole numbers. However, if the number has a decimal point, if it is, for example, 1.2 or 3.587, those are not whole numbers, because there’s a decimal point followed by some numbers. In American stores, then, you normally don’t see whole-number prices, like $1.00 or $2.00. Instead, you’re more likely to see something sold for 99￠ or $1.95.
In 1997, a little more than 10 years ago, a magazine called Marketing Bulletin did a study and discovered that 60% of advertised prices in the U.S. ended with the number 9, 30% ended with the number 5, and only 7% ended with a 0. In other words, you will typically find in stores something that has a price of, for example, $4.95 or $13.99, but not $5.00 and $14.00.
Stores don’t price their goods that way because they like to “make change,” to give people back two pennies or a nickel when they buy something. In fact, making change is difficult, or more work for businesses, because the people who are working for the store that are taking your money – the “cashiers,” we call them – are more likely to make mistakes. However, businesses price their goods this way, they put 99￠ or 95￠ on them, because of something known as “psychological” pricing.
Psychological pricing is based on the idea that prices have a psychological impact or influence. They make people think in a certain way. Obviously, if people stop to think about it, they know that something that costs $1.99 is basically $2.00. But for some reason, when we go into stores, we tend to round down; that is, think about the number that is lower than the next whole number. So, if something costs $1.99, “to round down” means to say, “Oh, so that’s like $1.00,” instead of “rounding up,” which would make us say, “Oh, that’s $2.00.” It’s a very strange thing that we tend to do. We should round up, go to the next higher number, but that isn’t what happens most of the time. People tend to round down, they think about the one rather than rounding up to the two. So, when I see something that costs $1.99, I should think to myself that it really costs $2.00, but studies show that buyers like me are more likely to think that it really costs something closer to $1.00. So as a result, if the price is $1.99 more people are likely to buy it than if you said it was $2.00.
Another “aspect,” or part of psychological pricing is that, as buyers, we tend to think the stores are offering us their lowest possible price when we see something that ends in 95￠ or 99￠. If something costs $3.95, some people think it looks as though the store really could not go any lower, they’re offering their lowest price. And that makes us want to buy it, because it seems to be a good deal – it seems to be a good buy to us.
Does psychological pricing really work? Well, it seems to. The Center for Research in Marketing at the University of Chicago, located in Chicago Illinois, studied the price of “margarine,” which is a food similar to butter, but it is made from oil instead of milk. The normal price for margarine was 89￠. When the price was reduced – when it was lowered to 71￠, sales increased by 65%, meaning more people bought it. But when the price was reduced from 89￠ to 69￠, just 2￠ less, the sales increased by 222%! The store made 2￠ less on each container – each product of margarine in the second experiment than in the first experiment, but they sold a lot more margarine. So, the 69 or 65 – that 9 or 5 really makes a difference.
Stores began using psychological pricing back in the 19th century and early 20th century, and since then it has become very “commonplace,” something that you’ll see almost everywhere. There is even a chain store in the United States called the 99￠ Store. A “chain” is a group of stores with the same name, usually owned by the same person, but in different locations. These particular stores are called the 99￠ Only Stores, they’re actually more than 271 of these stores in California, Nevada, Arizona, and Texas. Do they make more money than the store that calls itself The Dollar Tree, where everything sells for $1.00? I don’t really know, but according to what we’ve learned, it’s possible or even likely that the 99￠ stores should make more money because they have the price of 99￠ instead of the whole number of $1.00.
There is one place where you will see whole numbers as prices, you won’t see the 99 or 95￠ at the end of the price, and that is at some restaurants. Especially some newer restaurants or restaurant that are more modern try to appeal to people who have a little more money perhaps, they will often put their prices as whole numbers. So, salad is not 6.95, it’s $7. I’m not sure why that particular area of restaurant uses that, and again, it’s not all restaurants, it’s not even most restaurants. But there are some restaurants that, at least in the last few years, have been putting whole number prices on their food.
Now let’s talk about a completely different subject: soap operas. Soap operas are sometimes just called “soaps,” and they are a special type of television program. Soaps are dramatic shows usually about the lives of a large group of people and their relationships with each other.
The shows usually are one hour long, at least in the United States, and are “broadcast,” or are shown on TV every day, Monday through Friday, five days a week. Soap operas are usually shown during the day, so most of the viewers are people who are at home during the day, either people who are unemployed or people who stay home with their children instead of working. Traditionally, the audience for soap operas was women, although now there are many men at home during the day who watch soap operas. Some people say that soap operas can be “addictive,” meaning that it’s hard to not watch them once you start watching them – once you get interested in the story. Viewers become invested in the lives of the characters, meaning they start to care about these people and so they want to know what happens next, just like any good story.
The first soap opera was made in the 1930s as a series of 15-minute episodes for the radio. So, the first soap operas were radio programs. The reason the show became known as a soap opera was because it was created by a soap company, at least the first one was, by the name of Proctor & Gamble, a company that sells many products for the home, including soaps. They’re still around today. They were called operas, I guess, because operas tend to be very dramatic stories. I’m not exactly sure why, but that’s the word that was given, a soap opera, back in the 1930s. These were these 15-minute dramas that usually went on every day or every week, and that would be about the lives of a certain group of people.
In the 1950s, the soap operas began to be broadcast on television, and some of them became very popular. In fact, some of them are still being broadcast today! The longest-running soap opera – the soap opera that has been broadcast for the longest period of time, was called Guiding Light. “To guide” means to lead someone on a journey or on a trip – a path. Guiding Light started in 1952. The story actually first began on radio back in 1937, so this soap opera continued for many, many years. In fact this year, 2009, is the last year; they’ve decided to stop the Guiding Light as a soap opera, but it was, up until this year, the longest-running soap opera.
Soap operas in the United States can go for years and years; this is different than soap operas in other countries. For example, soap operas from Latin America, which are sometimes shown in Spanish here on American television, usually last a much shorter period of time. There’s a story, it begins, and it ends maybe in 10 weeks or 15 weeks. But American soap operas go forever and ever, as long as someone still watches them.
Guiding Light, like most soap operas, has some very bizarre plot twists. Something that is “bizarre” is very strange, very unusual, maybe even shocking. The “plot” is the storyline; it’s the story of the show. A plot “twist” is when there’s an unexpected change in the story. Something suddenly changes that you didn’t expect; that’s called a plot twist (twist). Well, soap operas have bizarre plot twists. The reason is that the story has to continue; it’s difficult to write a story that lasts 60 years, especially if the show is on five days a week.
The Guiding Light, for example, had a plot twist where one of the characters made a clone of herself from her own eggs. A “clone” (clone) is the exact copy genetically of a plant, an animal, or theoretically, a human being, although that has not been done. A clone looks just like the original. You may remember a few years ago in Scotland scientists cloned a sheep named Dolly, that was back, I think, in the 1990s. Well, in Guiding Light, the character made a clone of herself – which, of course, currently isn’t possible – and gave the clone a special chemical so that she would grow up more quickly. However, the clone was the “evil” clone – a bad clone, and tried to take the place of the original character. This is a good example of a bizarre plot twist, really almost a science fiction twist in the plot.
The second-longest-running soap opera (and now the longest-running soap opera since the Guiding Light is no more) is As the World Turns. That’s the name of the soap opera: As the World Turns. “To turn” means to move around; the Earth, of course, moves around once every 24 hours. As the World Turns began in 1956; it is still being broadcast. There are more than 13,000 episodes! It tends to be a little more realistic than the other soap operas, meaning that they are not going to have any clones; they tend to be things that would actually happen in real life. But there are still a lot of bizarre plot twists in this soap opera: people come back from the dead, which of course, is not normally possible. That is, people think they’re dead, and suddenly they become alive again. It’s very typical on these soap operas when they want to get rid of a character – when they no longer want a certain actor or character to be in the show, they’ll typically kill them in the story. Sometimes children grow up more quickly on the soap opera than they do in real life; people are not really very interested in watching the relationships with children, they want to see adults.
The third-longest-running soap opera in U.S. history, you could say, is called General Hospital. General Hospital began the year I was born, in 1963. Some people think it’s the greatest soap opera of all time, the greatest soap opera ever. I’m not sure what the qualifications are for that!
The characters in soap operas are very often people who have strange medical conditions, strange diseases, weird accidents. It’s very common in a soap opera for one of the characters to fall into a coma (coma). A “coma” is a long period of time when you’re unconscious, when you’re unaware of what is happening, when you can’t move, you can’t speak; you’re still alive, however. Another very common plot twist in soap operas is when the character finds out that his mother isn’t really his mother or his father isn’t really his father, maybe because the child was adopted or there was some terrible thing that happened in the family. Another common plot twist in soap operas is when somebody gets hit on the head and they have what’s called “amnesia,” they can’t remember what happened in their past life.
I personally have never watched soap operas, although some members of my family certainly did. I remember when I was in college there was a popular soap opera called All My Children. I think it’s still on the air, and my older brother and his then girlfriend, now wife, used to watch this show at noon every day. And eventually my father, who was then retired, started watching the show also, and he watched the show for many years. I just never really got that interested in the soap operas, but they are very popular, and people watch them for years and years.
Now let’s answer some of your questions.
Our first question comes from Atsuo (Atsuo) in Japan. Atsuo wants to know the meanings of the words “target,” “objective,” and “purpose,” and what the differences are. All three of these words can have similar meanings; let’s start with the word “target.”
“Target” can mean a goal that you’re trying to achieve. For example: “My target this year is to lose 10 pounds.” That’s my goal, that’s the thing that I want to accomplish. That can be your “target,” with the word used as a noun. “Target” can also be used as an adjective, meaning something that is describing your goal. So you could say, “My target weight is 145 pounds.” That means that’s the weight I want to achieve, that’s the weight that I want to be, that’s my goal weight.
A “target” can also be a particular point, especially if you are shooting at something, with a gun for example: “He hit his target.” He hit what he was trying to hit with his gun – well, with the bullet from the gun. A “target” can also be someone who is being criticized, or someone who is being made fun of: “He was the target of the newspaper’s criticism.” He was the person the newspaper was criticizing. So, all those are definitions of “target.”
“Objective” usually just means a goal; it doesn’t have as many meanings as the word “target,” but it can mean the same thing as a target. It’s the goal you are trying to achieve. So here, you could use the two words interchangeably, meaning one for the other. “My goal is to lose 10 pounds.” “My target is to lose 10 pounds.” “My objective is to lose 10 pounds.” Sometimes people distinguish between “goal” and “objective.” A “goal” is more general; an “objective” is more specific, but that’s not always the case.
Finally, a “purpose” can be a goal; it also can be the reason you’re doing something or the function of something, what something does. So you can say, “We are starting a group for the purpose of painting our building.” We are putting a group of people together with the purpose of painting the outside of our building. That’s the reason. It’s not exactly the goal however; it’s not your objective, it’s the reason for doing something. You may also say, “What is the purpose of this machine?” What is the function? What does it do? That’s another meaning of “purpose.” So “purpose” means something slightly different; it can mean a goal, but it more likely means the reason you do something.
Our next question comes from Ahmad (Ahmad) in Israel. Ahmad wants to know about pronouncing the letter “b” in a word. When is it pronounced and when is it not pronounced? This is a good question. There are some words, for example “plumber” (spelled plumber), where the “b” is not pronounced. A “plumber” is someone who fixes your toilet, someone who deals with water and pipes. My grandfather was a plumber and my uncles were all plumbers. So, a plumber is spelled with a “b” – the word is spelled with a “b,” but the “b” is not pronounced. Other words, such as “slumber” (spelled slumber) do pronounced the “b.” “Slumber” is something like sleep, to sleep peacefully.
Well, why are these two words pronounced differently? Why is the “b” pronounced in one and not the other? The reason is somewhat complicated. The word “plumber” comes from the word “plumb” (plumb). “To plumb” means to make straight or judge how deep something is, such as with a long pipe. A plumber is a person who plumbs. Because the “b” is not pronounced in what we call the “root word,” the original word, it’s not pronounced in any of the forms of that word. So when you say “plumber,” adding an “er” to the word, is still doesn’t have the “b” pronounced. “Slumber” is the root word – “slumber” is the root; there is no word “to slum.” Well, there is, but that’s a different meaning. There is no (slumb). “Slumber” is the original word, and so the “b” is pronounced.
There are other words in English that end in “b,” where the “b” is not pronounced. The word “numb” (numb) means without feeling. “The word “crumb” (crumb) means a very small piece of something, usually a small piece of bread. So, there are other words in English like this.
Usually, it’s not a good idea to try to think about rules here; it’s just a matter of hearing the word and learning it by hearing it rather than trying to analyze the reasons.
Finally, Roman (Roman) from Ukraine wants to know the meaning of an expression he heard: “there, there.” Somebody says, for example, to perhaps a little girl who is crying, the mother may say, “There, there. Don’t worry.”
“There, there” is an expression we use to give our sympathy or our comfort to someone. A little boy may be crying because he lost his dog, and the father may say, “There, there son. Don’t worry.” He’s trying to comfort him; he’s trying to make him feel better.
“There,” as an individual word, however, has many different meaning in English. The most common meaning means at that place, or at that point in time: “The teacher told the students to put their books there,” a specific place. But “there, there” means something completely different; it means expressing sympathy or comfort. I would say nowadays “there, there” is a old-fashioned; you won’t hear it or read it all that much anymore, but there are cases where you will.
If you have a question or a comment, you can email us. Our email address is eslpod@eslpod.com. Consider supporting this podcast by becoming a member or sending a donation, go to our website at eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening again. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2009 by the Center for Educational Development.
Glossary
whole number – a number that isn't followed by a decimal point; a number that is not a fraction
* Danny and I got different solutions to the math problem. My answer was a whole number and Danny’s was a fraction.
to make change – to give someone money back when he or she has paid for something with more money than the item costs
* The bus driver cannot make change, so we’ll need exactly $1.25 to get the bus.
to round up/down – to think about a number with a decimal point as the next higher/lower whole number; to think of a number ending in 1-9 as the nearest number ending in 0, either of higher or lower value
* With my weight, I like to round down from 154 pounds to 150 pounds, and with my age, I like to round up from 18 to 20.
chain – a group of stores with the same name, owned by the same person, but in many different locations
* When we travel, we look for the same chain restaurant because we know we’ll be able to find food that all five children like to eat.
soap opera – a very dramatic show about the lives of a large group of people and their relationships with each other, where the story continues from one episode to the next
* Shenice missed seeing her soap opera today at lunchtime, and she’s dying to know what happened to her favorite characters.
longest-running – broadcasted for the longest period of time; continuing as a show for the longest period of time
* One of the longest-running television shows is The Simpsons.
bizarre – very strange, unusual, and shocking
* Nicholas received a bizarre letter in the mail, telling him about a sister he didn’t know he had!
plot twist – an unexpected change in a storyline; a unexpected and sudden change in a story
* The writers tried to keep the show interesting with a plot twist where the main characters go back in time and live their lives again, making different decisions.
clone – an exact copy of a plant, animal, or human, with the same genetic information
* In this movie, a man meets his evil clone, and they fight to see who will survive.
to come back from the dead – to be alive after everyone thought one was dead
* Everyone thought that Sharif had died in the plane crash, but after 20 years, he came back from the dead.
of all time – ever; from the beginning of time to the present
* Who do you think is the best singer of all time?
coma – a long period of time when one is unconscious, unaware of what is happening, and cannot move or speak
* Bing’s wife had been in a coma for two weeks when she woke up, and eventually made a full recovery.
target – a goal to be achieved; a point or a particular object to be shot at
* Do you think we will reach our sales target for this month?
objective – a goal to be achieved
* Our objective is to raise enough money to build a new playground in our neighborhood.
purpose – a goal; a reason for something’s existence; its function
* The purpose for these bars along the mountain road is to prevent people from falling over the edge.
slumber – sleep; a peaceful sleep
* We put the cats in the other room so that they won’t disturb our guests’ slumber.
plumber – a person who works on parts that bring water into a house or building, such as water pipes, sinks, toilets, and bathtubs
* The plumber came and fixed the toilet so that it now flushes properly.
there, there – an expression meant to express sympathy or comfort; an expression used to calm a person who is upset, usually a child
* Simone ran to her mother when she had a bad dream and her mother said, “There, there, you’re fine now. It was only a dream.”
What Insiders Know
Primetime Teen Soaps
In this podcast, we talked about daytime soap operas or “soaps.” The soap opera “format” (type of show or recording) is not restricted to daytime television, however. Several of the most popular soaps have been “primetime” (in the evening hours, between 7:00 and 10:00 or 8:00 and 11:00) shows, and many of these have “featured” (made as the most important part) “teenagers” or “teens” (people age 13 to 19).
One of the most popular teen soaps was Beverly Hills 90210, “on the air” (broadcasted) between 1990 and 2000. The show was “set” (located) in Beverly Hills, one of the most “affluent” (wealthy; rich) cities in the United States. The number “90210” is one of the main “zip codes,” or postal codes, of that California neighborhood. The show was about a family that moved from the Midwestern state of Minnesota to Beverly Hills, and their “adjustment” to life in a very different environment.
Using a similar “premise” (basic idea), the show The O.C. “debuted” (was first shown) in 2003 and “went off the air” (shown for the last time) in 2007. “O.C.” stands for “Orange County,” an area just south of Los Angeles with many affluent neighborhoods. In this show, a teen from a poor neighborhood moves to the O.C. and faces a lot of challenges adjusting to life surrounded by money and “privilege” (having special opportunities and things because of wealth).
In recent years, another teen soap has become very popular, a show called Gossip Girl. This show is based on a series of books of the same name and debuted in 2007. This series is about the lives of wealthy teenagers at an “elite” (considered one of the best, with few people allowed to join) private high school in New York City.