= 1534
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 229.
This is English as a Second Language Podcast’s English Café episode 229. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, as well as our ESL Podcast Blog.
On this Café, we’re going to continue our series on American cities, focusing on the city of Milwaukee, Wisconsin. We’re also going to talk about neighborhood watches and citizen’s arrests, which are ways people can protect their neighborhood against crime. And, as always, we’ll answer a few of your questions. Let’s get started.
We begin with a continuation of our series on American cities. Today, we’re going to talk about Milwaukee, Wisconsin, which is the biggest city in the state of Wisconsin, with about a million people in it. Wisconsin is located in the Midwest – in the middle of the country, in the north. Wisconsin is just east of Minnesota, just west of Michigan, and just north of Illinois. On the northern border of Wisconsin, there’s Michigan as well as Lakes Superior, one of the five Great Lakes that are in the central northeastern part of the U.S. So, Wisconsin is very familiar to me since it is a state right next to my state, only about an hour or less driving from where I used to live in St. Paul. Milwaukee is located in the eastern part of the state, on Lake Michigan.
People aren’t sure what the word “Milwaukee” means, it seems to be related to words in several Native American languages where it means something like good, beautiful, and pleasant land. It also may have something to do with a meeting place by the water; remember I said Milwaukee is located on Lake Michigan. Many Native American “tribes,” or groups of people lived in this area, as they did in many areas of the United States, before the European settlers came in the early 1800s.
Many of the early Europeans who came to this part the United States were German. They began coming in the 1840s, and for many years the city had more German speakers than English speakers. In fact, Milwaukee was famous for its German heritage. They had more German-language newspapers in the middle of the 19th century than English-language newspapers. The area still has strong ties, or connections, with German culture and history. In addition to the German population in Milwaukee there are also many Poles, that is, people from the country of Poland, as well as other immigrants from Western, Central, and Eastern Europe. In general, you’ll find a lot of German immigrant populations in the Midwest during the 19th century – you would have found, I should say. In addition, the Irish also came to this part of the country.
Because of the city’s strong German heritage, its strong connections with German culture, Milwaukee is famous for beer making, because Germany is famous for its beers. Milwaukee has many small “breweries” (breweries), or places where beer is made; it also has many “taverns,” or bars. Milwaukee used to be home – used to be the headquarters for four of the world’s largest breweries: Blatz, Miller, Pabst, and Schiltz. Notice these are all German-sounding names. Today, only the Miller Brewing Company still remains in the city, and it is still an important employer. In fact I remember when I was growing up there was a show – a television show called Laverne and Shirley, and it was about two women who worked in Milwaukee in a beer factory – in a brewery, where they put the beer into the bottles. When you mention Milwaukee to an American, they will almost always think of beer, in fact the city’s baseball team – the professional baseball team is called the Milwaukee Brewers, where a “brewer” is a person whose job it is to make beer – to brew beer. It’s also become popular for people to brew their own beer at home; I have a couple of good friends that do that.
Milwaukee stands on the shores of Lake Michigan. The phrase “on the shores of” a lake means next to the lake. The “shore” (shore) of the lake is the place where the lake meets the ground, the ground that is not under the water, that is. You can walk along the shore of a lake, just as you can walk along the seashore, which would be where the ocean meets the land. Milwaukee is located on the shores of Lake Michigan. There are also three large rivers and several small rivers in and around Milwaukee, so the city has many bridges that let cars and “pedestrians,” or people who are walking, pass over the water. Milwaukee’s “proximity,” or closeness to the lakes and rivers helped the city grow quickly, because people were able to transport goods and products over the “waterways,” or routes over the water. Railroads were also built to connect Milwaukee to other parts of the country.
Milwaukee is home to many universities and colleges, in fact the city has one of the highest per-capita student populations in the United States. The phrase “per-capita” (capita) literally means per-person; we use it to talk about how common something is in a given population. If you had 1,000 students living in a city with 10,000 people, that would have a higher per-capita population of students than a city with 1,000 students and a million people. So the percentage, if you will, of the total number of people who live there is what we are talking about when we mention per-capita. Milwaukee is home to the University of Wisconsin at Milwaukee; it’s also home to Marquette University, where one of my nephews went to college I believe.
If you go to Milwaukee, especially during the spring, summer, or fall, you’ll see many people enjoying time on Lake Michigan sailing or windsurfing, or kitesurfing. “Windsurfing” is a sport where you stand on a small floating piece kind of like a surfboard and there’s another “sail,” or a large piece of fabric that catches the wind and pushes you over the water. “Kitesurfing,” is similar, except the sail is not attached – is not connected directly to the boat, but is instead attached with a long rope or string and flies up in the air, and you use the wind to pull the surfboard that you’re standing on over the water.
Tourists also come to Milwaukee for its many museums, gardens, parks, and sports. Many people come to see the cultural festivals. In fact Milwaukee is known as the “City of Festivals,” probably because it has many different ethnic groups, groups from different parts of the world, each of whom has their own cultural festival. Two important festivals in Milwaukee are Summerfest, which is a summer music festival, and Oktoberfest, which is a celebration of German heritage and culture – and of course beer – each fall.
You may have seen photos of the new art museum, the Milwaukee Art Museum. It has a very “unique” design, a design that you won’t see anywhere else. The building has a large structure that is shaped like a bird’s wing. This is a new section of the museum, what we would call a new “pavilion,” which opened in 2001. It was designed by Santiago Calatrava, a Spanish-born “architect” or building designer. At nighttime and during bad weather, the wing actually moves and folds over the rest of the building, to protect it. So if you go to Milwaukee, you definitely want to see the art museum.
Milwaukee used to have the reputation – it used to be known in the United States as being a “violent” city, a city where many people were attacked, hurt, or even killed. Milwaukee used to be the tenth-most-dangerous city in the United States. In recent years, however, the police have done a lot to protect resident; Milwaukee is not nearly as dangerous as it used to be. So don’t fear about visiting Milwaukee, I think you’ll enjoy your time there.
I’ve driven through Milwaukee; I don’t think I’ve ever stopped and got out of the car. I remember my relatives who live in Wisconsin used to have family reunions, and some of them came from Milwaukee. But as I say, I don’t really know the city that well even though it’s only six or seven hours from where I grew up in Minnesota.
Our next topic is related to crime, we were just talking about Milwaukee being a violent city in the old days. Our next topic is neighborhood watches. A “neighborhood watch” is a group of people who live in the same “neighborhood,” the same area, and want to work together to prevent crime. Neighborhood watches began, in terms of organized units – organized groups, back in the 1970s I believe. I remember growing up and hearing about these neighborhood watches. Neighborhood watches are meant to help prevent crime. “Crime,” is anything that is against the law, like stealing, or murder, or other things. Some neighborhood watches are organized by the people who live near each other, “neighbors.” Other neighborhood watches are organized by neighborhood groups or associations.
The people in neighborhood watches are not really trained to fight crime, they’re not police officers. Instead, they are trained to look for suspicious activities. Something that is “suspicious” (suspicious) looks strange and makes you think that there is something bad happening, or something bad might happen. For example, if you look out your window and you see a “stranger,” someone you’ve never seen before in your neighborhood, and this stranger is trying to get into your neighbor’s house, you might be suspicious. You might think the stranger shouldn’t be there and shouldn’t be going into the home. You don’t have any proof – you don’t have any actual evidence. It might be that the stranger is a friend of the person who lives next to you, but that’s what suspicious activity is, something that we think might be wrong.
When people in a neighborhood watch see suspicious activities, they are not supposed to try to “intervene,” that is to become involved, to try to stop it themselves, that’s not what neighborhood watches do. Instead, they’re supposed to call the police. Continuing our example, this means you shouldn’t go to your neighbor’s house and ask the stranger who he or she is. That might be very dangerous for you if it is, in fact, a criminal. Instead, you should call the police, describe what is happening, so they can investigate – they can intervene.
Even though neighbors aren’t supposed to intervene in crimes, they do sometimes get involved in something called a “citizen’s arrest.” “To arrest” (arrest) someone means to have someone held by the police because he or she has done something wrong. The police arrest people who they think are criminals. However, sometimes people who aren’t police officers can make a kind of arrest if they see something wrong – someone doing something wrong, they can hold that person and this would be called a “citizen’s arrest.” A “citizen” is someone who is a legal member of a particular community. Citizen’s arrests allow you to hold someone until the police arrive – until the police get there.
Citizen’s arrests are allowed in every state except North Carolina, but you can only arrest someone, as a citizen, when you see them committing a felony. A “felony” (felony) is a very serious crime, like murder for example. In most cases, citizen’s arrests are not allowed for minor crimes. For example if you see someone stealing something, or perhaps driving their car too quickly, normally you can’t stop that person and make a citizen’s arrest. Of course, citizen’s arrests can be very dangerous to the citizen who is making them. If the person is bigger, or stronger than you, or has a gun you probably don’t want to try to make a citizen’s arrest!
Neighborhood watches are usually formed or created when one individual goes around and talks to his or her neighbors and forms the organization. The neighbors might meet together once a month or once every few months. They try to get to know each other. This is important because if they know their neighbors then they know who isn’t their neighbor, who might be a stranger who could possibly be a criminal. Neighbors also tell each other when they’re out of town – when they are traveling, perhaps for business or on a vacation. That way your neighbors can watch your house to make sure that no one is going in there.
Neighborhood watches often buy signs that they hang, or put up in their neighborhood. If you go to an American city, you might be driving through a neighborhood – through an area with a lot of homes, and you might see neighborhood watch signs. Usually they’re orange signs. A typical message on these signs would be something like:
NEIGHBORHOOD WATCH PROGRAM IN FORCE.
When we say something is “in force,” we mean that it’s active, it’s working. So:
NEIGHBORHOOD WATCH PROGRAM IN FORCE.
We report all suspicious persons and activities to our law enforcement agency.
The law enforcement agency typically is the police.
These are all voluntary organizations; of course, you don’t have to become a member of a neighborhood watch group. But many neighbors feel safer knowing that their other neighbors are looking out for them – are trying to make sure that nothing bad happens in the neighborhood. The neighborhood watch signs are supposed to deter criminals. “To deter” (deter) means to make someone decide not to do something wrong. Of course, this doesn’t always work, but at least people are trying to protect themselves, which is always a good thing. I don’t have, or am not a member of a neighborhood watch organization where I live. I’m not sure why we don’t have one, but we don’t. So, I guess I need to be more careful!
Now let’s answer a few of your questions.
Our first question comes from Aki (Aki) in Japan. Aki wants to know the difference between “look” and “look like.”
“Look,” in this case, can mean to appear a certain way. For example: “He looks upset.” “My friend looks tired.” He appears tired; he seems tired. “Look” can also mean the same as the verb “to see.” “Look over there,” meaning turn your head and your eyes so that you can see something over there. But in this case, we’re using “look” to mean appear. The way someone looks is the ways someone appears – someone seems to you.
“Look like” means that you resemble someone or something. For example: “Leticia looks like her mother.” They resemble each other; they have similar looks. A child will usually resemble his or her parents in some way. However – and here’s the confusing part – “look like” can also be used in the same way as we use the word “look.” It can also just mean that someone appears a certain way.
Even though they can have similar meanings, there are different rules for “look” versus “look like” in an actual sentence. If you say “look,” you have to follow that verb with an adjective. For example: “He looks tired.” “Tired” is the adjective. “She looks angry.” “Angry” is the adjective. You could also add an adverb to describe the adjective: “She looks very proud.” “Very” is an adverb. Or, “He looks too young.” “Too” is an adverb. You can also use “look” with nationalities; you could say “My friend looks Chinese.” “My brother looks German.” Those are also possibilities because Chinese and German, in this case, are being used as adjectives.
The expression “look like” is a little different – used a little differently. If we are using “look like” to mean resemble, the way, for example, a son looks like his father, then the expression is followed by a noun, not an adjective: “He looks like his father.” “His father” is a noun, not an adjective, in that sentence. When you are using “looks like” to mean the same as “look,” in previous example, then you are actually going to have to create a second “clause,” or a second part of your sentence: “You look like you have some good news.” “She looks like she doesn’t feel well.” Notice that after the word “like” you have a separate clause, basically another sentence. “She doesn’t feel well.” “She looks like she doesn’t feel well.” That is the difference between “looks like” and “look.” For “look” you would just add an adjective: “She looks sick.” If you’re going to use “looks like,” you have to add basically another sentence: “She looks like she is ill,” or “she is sick.”
Just like the word “look,” you can also use “looks like” for nationalities: “My father looks like an Irishman.” “My father looks Irish.” Both of these mean the same thing. In the first case, “looks like” is followed by a noun; in the second case “look,” or “looks” is followed by an adjective.
Our second question comes from Hendra (Hendra) from an unknown country. Hendra wants to know the meaning of the phrase “not by the hair of my chinny-chin-chin.”
“Not by the hair of my chinny-chin-chin” is taken from a folk tale, an old story that is often told to children. It means absolutely not. There was a popular children’s story back in the 19th century in England, but it may in fact be older than that. In the story there are three pigs that have three different houses, and the wolf tries to enter each house. Each time the wolf wants to enter the house, the pig says “no.” But he doesn’t just say “no,” he uses this expression: “Not by the hair of my chinny-chin-chin.” Your “chin” is the part of your face that is below your mouth, between your mouth and your neck.
We actually have a course called Simple English Stories, where one of the stories is this story where this line comes from, “not by the hair of my chinny-chin-chin,” so you can take look at that in our ESL Podcast Store.
Finally, Kevin (Kevin) from China wants to know how we use the word “pretty” (pretty) with an adjective. For example, what does it mean when we say “it’s pretty good”?
“Pretty” means something like mostly; fairly; generally. “She’s pretty good.” It doesn’t mean she’s very good; very good would be better than pretty good. You could have someone who’s good; someone who’s pretty good, that means they’re a little better; and someone who’s very good, that means they are even better than pretty good. However, sometimes people use “pretty good” to mean the same as “very good,” so it depends on how the person is using that particular expression. But generally, when you say something is “pretty good” or “pretty bad” or “pretty loud” “pretty quiet,” you mean that they are generally, fairly, mostly quiet or loud or whatever the adjective is.
“Pretty” can also be used as an adjective by itself. You could say, “That’s a pretty dress,” meaning that’s a beautiful dress. So, “pretty” can mean beautiful as well, but that would be a different use of the word.
If you’d like to know different uses of words, you can email us. Our email address is eslpod@eslpod.com. We can’t answer all of your questions, but we’ll do our best here on the Café.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
brewery – places where beer is made; a factory that makes beer to sell
* Everyone who works at the brewery received cases of beer as holiday gifts.
on the shores of – next to a body of water; on the land next to a lake, river, ocean, or sea
* The ship was lost at sea until the sailors saw the lights on the shores of the nearest town.
waterway – a route people take to travel through water; a path that boats and ships follow when traveling through large areas of water
* So many boats travel through this waterway each year that fishing is no longer possible.
per-capita – for each person; for each individual, used to talk about how common or frequent something is
* This state has more universities per-capita than any other state.
violent – using physical force to try to hurt, damage, or kill someone or something
* Liam is a gentle person, but when he drinks alcohol, he often becomes violent.
crime – an action that is against the law; doing something that is not allowed by law
* Crime has become a major problem as more and more people move into this small neighborhood, which doesn’t have enough housing or jobs.
suspicious – something that looks strange and makes you think that something bad might be happening, even if you don’t have any proof
* Ellen became suspicious of her neighbor when she heard strange sounds coming from her apartment late at night.
to intervene – to become involved; to come between two or more people or two sides in order to try to influence the result
* I wanted the employees to complete this project on their own, but it’s not going well and I think I may need to intervene to give them some help.
citizen’s arrest – for a normal person (not a police officer) to not allow someone who has done something against the law to leave a place until the police arrives
* Six customers who saw the crime put the thief under citizen’s arrest until the police could get there.
felony – a very serious crime, such as murder; a serious crime that results in serious punishment, such as going to jail or even death
* If you are convicted of this felony, you may go to jail for five to fifteen years.
sign – a piece of metal, wood, or plastic hung where people can see it, usually with words or pictures, often used for advertising or for displaying the name of a company or store
* I’ve driven up and down this street three times, but I haven’t seen a sign for the shoe repair store.
to deter – to make someone change his/her mind and decide not to commit a crime
* Since Mina and Dave have a lot of computers and other electronic equipment in their house, they got a dog to deter burglars.
to look – to appear to be a certain way; to have the appearance of being a certain way
* Jeannine looked so tired after spending the entire day with her young nieces and nephews.
to look like – to resemble someone or something; to appear to like someone or something
* Kiro looked like a bear when he stopped shaving and grew a long beard.
not by the hair of my chinny-chin-chin – a line from a folktale The Three Little Pigs meaning “absolutely not”
* The children asked their mother if they could have more cake, and their mother said, “Not by the hair of my chinny-chin-chin!”
pretty – generally; moderately; fairly
* This is not the hottest day in October, but it’s still pretty hot for a fall day.
What Insiders Know
Laverne and Shirley
When Americans think of Milwaukee, they think of beer. Some Americans may also think of a classic television show from the 1970s and 1980s called Laverne and Shirley “set” (taking place) in Milwaukee. This show was a “sit-com” (half-hour comedy show) about two roommates named Laverne and Shirley who work at a Milwaukee brewery. It was a “spin-off” from another, even more popular TV show from the 1970s and 1980s called Happy Days. Laverne and Shirley were first introduced on Happy Days as friends of one of the main characters named Fonzie.
Although the show “aired” (was shown) between 1976 and 1983, it was set around 1959. Laverne and Shirley were best friends and worked as “bottlecappers,” putting tops on bottles of beer produced at the Shotz Brewery. They lived in a “basement” (below ground) apartment, where the feet of people passing could be seen going past their front window. They had two neighbors upstairs, Lenny and Squiggy, and they communicated with them by shouting up the “dumbwaiter shaft,” the small elevator inside of apartments used in the old days to bring food and other things from one floor of a building to another.
The theme song to Laverne and Shirley is “memorable” (difficult to forget) and many Americans still remember it. At the beginning of each episode, Laverne and Shirley “skip” (moving forward, stepping from one foot to the other with a hop) down the street, while saying these words to an old Yiddish-American “hopscotch chant” (a short poem said during a sidewalk game): “One, two, three, four, five, six, seven, eight! Schlemiel! Schlimazel! Hasenpfeffer Incorporated!” “Schlemiel” is a Yiddish word that is used to describe someone who is clumsy and doesn’t do things well, and “Hasenpfeffer” is a “stew” (thick soup) made with rabbit. Neither of these words is commonly used in the U.S. and many Americans may not even know the meanings of them, but they would “surely” (certainly) recognize this very familiar start to this classic TV show.