= 1536
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 231.
This is English as a Second Language Podcast’s English Café number 231. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there, right now, to download the Learning Guide for this episode, or if you’re not a member yet, to become a member and support this podcast.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal speed – a normal rate of speech. We’ll listen to them and then explain what they’re talking about. Today our topic is using social media. We’ve talked about Facebook and Twitter in past Cafés. On this one, we’re going to talk about how people use social media, use what is called online networking, to get a job. As always, we’ll also answer a few of your questions. Let’s get started.
Our topic on this Café’s Ask an American segment is how people are using social media, or online networking, when they look for a job, things like Facebook, MySpace, and Twitter. Today we’re going to listen to part of an interview with a man who works here in Los Angeles at an executive search agency. This is a company that other companies use to find good people for them to apply for jobs. He’s what we call a “recruiter” (recruiter). A recruiter is someone who “recruits,” which means to go out and look for people for a particular job or purpose. The man’s name is Kurt Weyerhauser. We’re going to listen to him first talk about why social media is important in searching for a job.
The audio quality on this recording is not the best; it may be little harder for you to understand. I think he is being interviewed on the phone. I took this from a Voice of America story, so I apologize if the quality is not quite as good as it should be. Let’s listen:
[start of recording]
We’ve only scratched the surface. There’s no telling where things are gonna be going in the next 5 to 10 years. In many ways, social media is like the wild, wild west and it’s still, you know, uncertain as to how it’s gonna evolve. But, there’s some very interesting things that…that I think give people tremendous benefits to date, and I will tell you, most of it is absolutely free.
[end of recording]
Kurt is a fast talker, probably not originally from Los Angeles. He sounds like he may be from the east coast of the U.S. In any case, he begins by saying that we’ve only scratched the surface. To “scratch” (scratch) means to rub something quickly against something sharp. For example, if your skin itches, if you have this feeling on your skin that you need to touch your skin to get rid of it, you might scratch it with your fingernails. Your fingernails are sharp, at the end of your fingers. You can then move them back and forth against your skin. That would be scratching. Or for example, if you move a heavy table across the floor, you might scratch the floor if you don’t lift it up. The phrase “to scratch the surface” means that you’re only scratching, you’re only exploring, you’re only talking about the very top part of something. The surface is the top part of an object. For example, if you have a ball there’s air inside of the ball, and on the outside there is the surface of the ball. Well, if you’re scratching the surface, you’re not getting at all of what you could be talking about or understanding. It means, generally, that we are just beginning to understand something, that we don’t have all the potential benefits or information from this particular thing.
We’ve only scratched the surface of social media. Kurt says, “There’s no telling,” meaning there’s no one who knows, no one can say exactly, “There’s no telling where things are gonna be going in the next 5 to 10 years.” Notice Kurt says “are gonna.” “Gonna” is an informal, short way of saying “going to.” So he says, “There’s no telling where things are going to be going (or are going to go) in the next 5 to 10 years.”
He says, “In many ways, social media is like the wild, wild west.” The expression “the wild, wild west” refers to a period in American history – in U.S. history when European Americans lived mostly in the eastern part of the United States, although people were beginning to move westward, towards California, towards the west coast of what is now the United States, so that land in between where there were lots of people in the East and the Pacific Ocean was often called the wild, wild west. “Wild,” here, means out of control; there are no rules, no laws, things are perhaps a little dangerous. If you’ve watched old American movies about cowboys and Indians for example, those are stories that all took place in the wild, wild west. Basically, most of the 19th century was like that. There was a lot of violence, there were a lot of guns; people could do almost anything to make money or to get land. When people describe something as the wild, wild west today, they mean that things are unpredictable, nobody really knows what will happen. The phrase is also used to describe something that is very interesting because so many different things can happen and no one person is in control. So he says social media is like the wild, wild west. He says, “It’s still (it continues to be), you know, uncertain (meaning we don’t know) how social media is going to evolve.” “Evolve,” here, means change over time. So because social media is so new, we don’t know how it’s going to change in the 5 to 10 years.
However, he then says, “But, there are some very interesting things that give people tremendous benefits to date.” The word “tremendous” (tremendous) means huge, very large, very important, or very significant. We might talk about having a tremendous amount of work to do – we have a lot of work to do. Or, we may have tremendous feelings of love for our children – a lot of love. According to Kurt, then, social media offers tremendous benefits (good things) to people who are searching for a job, and most of these benefits, he says, are absolutely (meaning completely) free. Let’s listen again:
[start of recording]
We’ve only scratched the surface. There’s no telling where things are gonna be going in the next 5 to 10 years. In many ways, social media is like the wild, wild west and it’s still, you know, uncertain as to how it’s gonna evolve. But, there’s some very interesting things that…that I think give people tremendous benefits to date, and I will tell you, most of it is absolutely free.
[end of recording]
Next, we’ll listen to Kurt’s advice on how people can use Internet networking sites in their job search. As before, we’ll listen first and then I’ll explain what he said. Let’s listen:
[start of recording]
What I was talking about, in terms of it takes time to really get…uh…some…some real benefit from, is using social media in a very different way, and that is in a way to enhance your credibility and your visibility. And that can be done now also, in many cases, absolutely free. And that, I…I think the most powerful thing people can do is exhibit thought leadership about what they know…uh…the job that they perform, the…the function, the industry they’re in, developments that they see coming. You know, speaking about things that they really know.
[end of recording]
Kurt begins by saying, “What I was talking about, in terms of it takes time to really get some real benefit from, is using social media in a very different way.” He’s referring back to an earlier part of the conversation when he says “What I was talking about.” The phrase “in terms of” means same as regarding or referring to. For example: “In terms of the weather, it’s really rainy outside.” “What I was talking about, in terms of it takes time to really get some real benefit from, is using social media in a very different way.” “Social media,” as we mentioned earlier, is online content or text that is created by many different people, such as a blog, Twitter, Facebook, MySpace, and so on, it allows people to express themselves, to respond to each other. In terms of looking for a job, the site LinkedIn is very popular as far social networking sites go.
Kurt then gives the reason why you want to use social networking site, or how to use it best. He says that you should use it in a way to enhance your credibility and your visibility. “To enhance” (enhance) means to improve, to make something better or bigger. Kurt suggests using social media to enhance your credibility. Your “credibility” means your believability, the ability for people to believe in you or in what you do. People who are credible for a particular job have enough experience, qualifications, and knowledge so that other people trust them and believe in what they to say. If a politician is giving a speech and he starts talking about things that you know are not true – which is almost every politician and every political speech – that person loses credibility. They don’t have the believability; people won’t believe them. He also says social media can enhance, or improve, your visibility. “Visibility” comes from the word “visible” (visible), which means you can be seen, or able to be seen, easily seen.
He continues, “And that can be done now also (that is, you can enhance your credibility and visibility now), in many cases, absolutely (or completely) free.” He continues, “I think the most powerful thing people can do is exhibit (or show; demonstrate) thought leadership about what they know.” The term “thought leadership” is one of those business terms that people invent to make simple ideas seem complicated. I think what he means here is that you should show that you are one of the best thinkers, you know a lot about your topic. So, “leadership” refers to being a leader, being the person that everyone else follows. “Thought,” of course, relates to your ideas. Someone with thought leadership has a lot of new and interesting ideas that other people are interested in. They might publish articles in magazines, or other things that people would read. Well, according to Kurt, people can use social media to show that they have this thought leadership related to the job that they do, or their position in their particular – their specific industry. “Industry” refers to everyone who does a similar kind of business. The pharmaceutical industry consists of drug companies, all the different companies that make legal drugs. To review, then, Kurt says, “I think the most powerful thing people can do is exhibit thought leadership about what they know, the job they perform, their function (what they do), the industry they’re in, developments that they see coming. You know,” he says, “speaking about things that they really know.” Let’s listen to Kurt one more time:
[start of recording]
What I was talking about, in terms of it takes time to really get…uh…some…some real benefit from, is using social media in a very different way, and that is in a way to enhance your credibility and your visibility. And that can be done now also, in many cases, absolutely free. And that, I…I think the most powerful thing people can do is exhibit thought leadership about what they know…uh…the job that they perform, the…the function, the industry they’re in, developments that they see coming. You know, speaking about things that they really know.
[end of recording]
In another part of the interview, Kurt says that it’s important for people to act professionally when they write things on social media sites. But he doesn’t mean pretending to be someone you’re not, trying to seem as though you are someone or a kind of person that you are not. Let’s listen as he explains what he means by this.
[start of recording]
Look, you and three buddies going to a football game are going to behave very differently…uh…than you and your family attending a funeral, but you are yourself in both cases. It’s the…it’s the environment – the situation that dictates how you behave. And the only thing I’m suggesting is when you go online, you have to define who you should be, because you do not want to have things come back that could damage you…uh…or hurt you, or require you to explain yourself five years from now. And…and that, I…I think, is a really important point, that social media is defined as much by its permanency, as it is by its immediacy.
[end of recording]
Kurt begins by giving an example, telling a little story. He says, “Look, you and three buddies going to a football game (an American football game) are going to behave very differently than you and your family attending a funeral. He’s saying imagine that you and three buddies are going to a football game. A “buddy” (buddy) is an informal word for a good friend, usually a male friend – a boy or a man. Of course, Kurt is a man, and he uses sports analogies the way some men like to do. He says imagine you’re going to this game and how you would behave – how you would act. You would act very differently than if you and your family were attending, or going to, a funeral. A “funeral” a ceremony that happens after someone dies. But even though you behave differently in these two situations, you’re still being yourself in each situation. He says, “you are yourself in both cases.” “Cases,” here, means situations.
He says, “It’s the environment – the situation that dictates how you behave.” “To dictate” (dictate) means to say how something must or should be. The word “dictator” refers to a leader of a country who has all of the important power and authority. He or she tells people what to do and doesn’t listen to anyone else. In the same way, a situation dictates, forces, compels us to do things in a certain way. Kurt says it’s the environment – the situation that determines how you behave – how you act.
He continues, “And the only thing I’m suggesting is when you go online, you have to define who you should be.” You have to figure out who you are, what kind of image you want to present to people. He says, “you do not want to have things come back that could damage you, or hurt you, or require you to explain yourself five years from now.” The expression “to come back” means to return to you. So, if you say something stupid on your blog, and then five years from now someone searches the web and finds this stupid comment, you may have to explain yourself. That comment may hurt you – may damage you. I have been on the Internet pretty actively for the last five years, so I’m sure I’ve said many stupid things and they’ll probably hurt me years from now. Fortunately, I’m not looking for another job!
Kurt concludes by saying, “And that, I think, is a really important point, that social media is defined as much by its permanency, as it is by its immediacy.” Kurt is saying that this really important thing about online networking, the idea that you may be hurt buy something stupid you say now, is true because social media – online activity – is both immediate and permanent. “Immediacy” is something that happens right away, something that you can see as soon as you finish doing it or as you are doing it. Something that is “permanent” is something that will remain for many years, that will still be there many years from now. “Permanency,” then, is the noun of this idea of things being permanent, being there forever. “Immediacy” is the noun for the idea of things being immediately available – immediately visible. People get excited by social media because they can do things immediately and see results. Unfortunately, if what you are doing is not very smart, it will be there years from now. On Twitter, for example, the question the website asks you is “What are you doing now?” Well, maybe it’s better that you don’t tell people what you’re doing now if what you’re doing will get you in trouble later!
Here’s Kurt one more time:
[start of recording]
Look, you and three buddies going to a football game are going to behave very differently…uh…than you and your family attending a funeral, but you are yourself in both cases. It’s the…it’s the environment – the situation that dictates how you behave. And the only thing I’m suggesting is when you go online, you have to define who you should be, because you do not want to have things come back that could damage you…uh…or hurt you, or require you to explain yourself five years from now. And…and that, I…I think, is a really important point, that social media is defined as much by its permanency, as it is by its immediacy.
[end of recording]
Now let’s answer a few of your questions.
We have time for a couple of quick questions. The first one is from Jurgen (Jurgen) – I’m probably pronouncing that incorrectly – from Germany. He wants to know the meaning of a phrase he heard, “Go ahead, and make my day.” Usually it’s simply “Go head, make my day.” This is a famous movie quote, something said by the actor Clint Eastwood in 1983 in a movie called Sudden Impact. Clint Eastwood, in that movie and other movies, played a tough policeman called Dirty Harry, “dirty” in the sense that he would do things that weren’t necessarily legal to do. “Dirty” can mean someone who is a criminal.
Well, Dirty Harry was supposed to be very brave, and in one scene of the movie a criminal points a gun at a young woman. Harry pulls out his gun and points it at the criminal and says, “Go ahead, make my day.” What he’s saying is you don’t scare me, my day will be better if you gave me an excuse to shoot you. So, “go ahead” means do what you are planning on doing; “make my day” means make my day happy.
We use this expression now as a joke usually; to make someone’s day means to make their day happy, make their day great. But when someone says that, they are usually joking; they’re saying if you do that I will punish you, or that thing will make me happy. If a teacher says to a student, “I’m going to call your parents because of your bad behavior,” the student might say, “Go ahead, make my day.” The student is saying that he doesn’t care, he’d be happy if you called his parents.
Carlos (Carlos) in Nicaragua wants to know how we use the expression, or the phrase, “years old” and “year old.” For example, he heard the sentences “A 64-year-old man,” as well as “The man is 64 years old.” One has an “s,” the other doesn’t.
“Years old” is a way of expressing age, by counting the number of years you have been alive: “I am 46 years old.” It’s usually used with the verb “to be (years old).” “This television program is 20 years old.” If you want to describe a particular thing you can use “year old” before the thing that you are describing, basically using it as an adjective: “We have a 14-year-old refrigerator.” “The refrigerator is 14 years old.” So when it comes before the noun, used as an adjective, we say “year old.” We also put a hyphen in between the number and the word “year,” the word “year” and the word “old,” so it’s actually “14-year-old,” that’s how you would spell it.
If you have a question for our now 4?-year-old podcast, email us at eslpod@eslpod.com.
From Los Angeles, California, I am Jeff McQuillan. I do thank you for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2010 by the Center for Educational Development.
Glossary
to scratch the surface – to just begin to understand something, or to understand only a very small part of something
* Scientists have just begun to scratch the surface in their understanding of the outer areas of space.
there’s no telling – nobody knows; no one can say
* There’s no telling how long it will take to find a new job.
wild, wild west – the western United States before many European Americans were living there, when there were few rules or laws and things were a little bit out of control, now used to describe a situation or period that is very interesting because many different things can happen and no one is really in control
* During the dot-com boom, it was like the wild, wild west, with people opening online businesses very quickly, with hardly any limits on how much they could sell them for.
tremendous – huge or very large and important or significant
* Aisha has been offered a tremendous opportunity to study art at a prestigious university in Italy.
social media – online content or text that is created by many people, where each person has an opportunity to edit (change) or add to what other people have already written, and where people are encouraged to interact with each other
* Are you concerned about sharing too much private, personal information on social media sites?
to enhance – to improve; to make something bigger or better
* Have you considered enhancing your qualifications by getting a certificate for a software program?
credibility – believability; how much others trust and believe what someone says
* The politician lost a lot of credibility when the newspaper reported that he had lied during the election campaign.
thought leadership – the practice of being a leading thinker in one’s field or one’s area of expertise, with many new and interesting ideas that other professionals in that field are interested in hearing about
* Alan Greenspan received a lot of recognition for his thought leadership in macroeconomics.
buddy – a good friend, almost always male
* Each Saturday, Mark invites his buddies over to eat pizza and watch the football game on TV.
to dictate – to say with a lot of authority on how something must or should be
* Teenagers hate it when their parents dictate what they can and cannot do.
to come back – to return from a distance or after a period of time
* When will you come back from your vacation in Maui?
permanency – the way that things are permanent or last forever, and cannot be lost or forgotten
* Great authors and artists create works of art that have permanency long after they die.
immediacy – things that are created immediately in the moment, with no thought for the past or the future
* The team has a strong sense of immediacy on this project and everyone wants to get the work done as quickly as possible.
Go ahead, make my day – a famous movie quote meaning, “Whatever you’re about to do next (to try to hurt me), I don’t fear it; I’ll enjoy it,” usually used sarcastically, and often as a threat
* - Sir, I’m going to give you a ticket for speeding.
* - Go ahead, make my day.
years old – a way of expressing age by counting the number of years someone or something has been alive
* His great-grandfather is 98 years old and still very healthy.
year old – when following a number, a noun meaning a person or thing of a certain age; an adjective describing a person or thing of a certain age
* They have a five-year-old, a two-year-old, and a two-month-old.
What Insiders Know
Ways to Fix a Poor Online Reputation
In today’s English Café, Kurt provided a lot of information and advice about why it’s important to be professional when using social media, but he didn’t provide information about what to do if you already have a bad “reputation” (the way that one is known or perceived by other people) on the Internet. Not only individuals, but also companies can have a bad “Google reputation” (the information that appears when one searches for a specific name in the Google search engine).
The best way to “mitigate” (make less damaging) a bad Google reputation is to create a good Google reputation. Individuals and companies can do this by creating their own website if they don’t already have one. They can also start a “blog” (text that is added to a website every day or a few times each week on a particular topic). Websites and blogs let people control what kind of information is shared. They don’t have that same control over the content on other people’s websites and blogs.
Individuals and companies can also improve their Google reputation by creating social networking “profiles” (accounts; basic information about the user) on sites like Facebook, MySpace, and Twitter. Then they can invite people into their “social network” (the group of people who are connected as friends or contacts through social networking sites) and try to spread their “messages” (the information people want to share) through those networks.
None of these things can erase the information that’s already on the Internet and is creating a bad Google reputation. However, as the amount of positive information increases, anyone who searches for your name on Google becomes more likely to find the good information instead of the bad information.