
= 301 西欧文艺复兴 (14-16世纪)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''




== 历史框架

The Renaissance, which means “rebirth” in French. It began in the city-states of northern Italy that had grown wealthy through trade, especially trade with the Ottomans. Beginning in the 1300s, scholars there turned to the works of Western antiquity—the writings of the ancient Greeks and Romans—for wisdom and a model of how to live.

文艺复兴在法语中意为“重生”，它始于意大利北部的城邦，这些城邦通过贸易，特别是与奥斯曼帝国的贸易而变得 富裕。从 1300 年代开始，那里的学者转向西方古代著作——古希腊人和古罗马人的著作——寻求智慧 和生活方式的典范

Petrarch has been called the father of humanism. Humanism was a movement born in Italy in the fourteenth century that focused on the study of human beings, human nature, and human achievements, as opposed to the study of God. Humanists stressed the beauty and dignity of humanity instead of focusing on its sinful, “fallen” nature.

彼特拉克被称为人文主义之父。人文主义是十四世纪诞生于意大利的一场运动，其重点是对人类、人 性和人类成就的研究，而不是对上帝的研究。人文主义者强调人性的美丽和尊严，而不是关注其罪恶 的“堕落”本质。


During the Renaissance, the depiction of scenes from Greek and Roman mythology became common in European art.

文艺复兴时期，对希腊和罗马神话场景的描绘在欧洲艺术中变得很常见。





















