= 0501
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 501: Buying Glasses.
This is English as a Second Language Podcast episode 501. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode, an 8- to 10-page guide that contains all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of this episode.
This episode is called “Buying Glasses.” We’re going to listen to a dialogue between Alice and Pierre talking about someone who needs to buy some eyeglasses. Let’s get started.
[start of dialogue]
Alice: Ooh, look at these! Don’t I look great? I’ve always wanted sunglasses like these.
Pierre: You’re supposed to be here helping me pick out frames for my new bifocals.
Alice: I don’t know why you won’t get progressives. That’s what everybody is getting these days.
Pierre: I’ve always had bifocals and that’s what I’m going to get.
Alice: Are you going to get metal, plastic, or rimless frames?
Pierre: I’m not sure. The optician said that with my prescription, I could get any kind.
Alice: Okay, try these. How do they feel?
Pierre: I like the way the hinges move, but they’re too small for my head. Hey, these are nice. I think I’ll go with these.
Alice: There’s no accounting for taste! Okay, but what about the lenses? There are so many options. You can get ones that reduce glare, ones that darken automatically, ones with anti-scratch coating…
Pierre: I want to keep it nice and simple. I don’t want any of those options.
Alice: How about these for a backup pair? They’re designer frames.
Pierre: Give me those. I should have known better than to let you tag along. What was I thinking?!
[end of dialogue]
Alice says to Pierre, “Ooh, look at these! Don’t I look great? I’ve always wanted sunglasses like these.” “Don’t I look great?” of course, means I look great in these, don’t I, asking for the other person to agree. Alice says that she’s always wanted sunglasses like these. “Sunglasses” are glasses we use to protect our eyes from very bright sunshine.
Pierre says, “You’re supposed to be here helping me pick out frames for my new bifocals.” Pierre is saying that Alice is supposed to be helping him pick out frames. “Frames” are the metal or plastic part of your glasses that hold in what we call the “lenses,” the things that you see through, made of glass or plastic. The frames can be metal or plastic, and they go behind your ear so that they stay up – so that they stay in place.
Pierre needs to get bifocals. “Bifocals” are glasses that have two sections with a small line separating them. The largest section is for seeing distance; that is, seeing things that are far away. And, bifocals typically have reading glasses, or a reading section in the glasses. That’s a smaller section of the lens which you use to read. So, you can have one pair of glasses to do two different things. “Bi,” of course, means two. I have bifocals, so I can see far, when I’m driving for example, and I also can see close up when I’m reading.
Alice says to Pierre, “I don’t know why you won’t get progressives.” “Progressives” is a special kind of glasses that have two or three sections. There is a section on the top that helps you see far away, a section in the middle of the lens that helps you see a medium distance – not too far, not too close, and then there’s a section that helps you see things close, for example when you’re reading. The difference is that progressives don’t have a little line that separates the different parts of the lens, whereas a bifocal would. “Progressive” has a couple of different meanings in English; take a look at our Learning Guide for some additional explanations.
Alice says, “everybody is getting progressives these days (nowadays).” Pierre says, “I’ve always had bifocals and that’s what I’m going to get.” Alice asks him, “Are you going to get metal, plastic, or rimless frames?” “Metal” is something that is hard; a material made of iron, steel, aluminum, those would all be metals. Silver, gold, and nickel are also metals. “Plastic” is a strong material that is made by taking petroleum (oil) and making it into a hard object. “Rimless glasses” are glasses that don’t have any edges. The lens – remember the lens is the part of the glasses that you see out of – that you look out of – they are attached to the frames, but there is not any plastic or metal around the actual glass or plastic lenses, so it looks like you just have these two lenses sitting in front of your eyes. The “rim” (rim) of the glasses are the parts that go around the lens – the edge of the lenses. “Rimless” would be without a rim, and that’s what rimless glasses are.
Well, Pierre says, “I’m not sure. The optician said that with my prescription, I could get any kind (I could get frames that are metal, plastic, or rimless).” The “optician” is the person who makes the glasses, puts the glasses together, and helps people put on the glasses. Usually if you are going to have your eyes checked, you go to a doctor called an “optometrist,” but if you are just buying glasses, then you would go to an optician. The optician is not a doctor; it is a person who knows about how glasses are made and helps you select a pair and put them on your face. When you have your eyes examined by the optometrist and they determine you need glasses, you are given something called a “prescription,” which is a piece of paper where the doctor writes down what kind of glasses you need. We use that same word if a doctor is giving you some sort of drug; they would write down the name of the medicine. That’s your “prescription,” it’s the piece of paper that has that information, usually with the doctor’s signature, that you then bring in order to get your glasses or your drugs.
Alice says, “Okay, try these. How do they feel?” Pierre says, “I like the way the hinges move, but they’re too small for my head.” A “hinge” (hinge) is a small piece of metal that connects two larger pieces of wood, plastic, or metal. If you have a door in your house, there are at least two hinges. The door opens and closes, but there’s a metal plate that connects the door to the wall, and that allows you to open the door. So the hinge opens and closes; it’s flexible. Your glasses have hinges – if you have glasses – that connect the lens part of the glasses – the lens part of the frame with the pieces of the frame that go on either side of your head and behind your ears. So, Pierre likes the hinges on the pair of glasses that Alice showed him, but he says they’re too small for his head. Obviously, he has a very big head! “Hinge” has a couple of meanings in English; take a look at our Learning Guide for some additional explanations.
Pierre says, “Hey, these are nice. I’ll go with these,” meaning I’ll select these. Alice says, “There’s no accounting for taste!” The expression “there’s no accounting for taste” is used to show that you don’t like another person’s choice of style or fashion. To say “there’s no accounting for” means there’s no way to explain. So, everyone has different tastes – a different sense of style and fashion.
Alice doesn’t like Pierre’s taste; she obviously doesn’t like the pair of glasses that Pierre is trying on. Alice says, “Okay, but what about the lenses?” the clear, plastic, or glass pieces that you see through. You also call that clear piece of plastic or glass in a camera a lens. Alice says, “There are so many options. You can get lenses that reduce glare, ones that darken automatically, ones with anti-scratch coating.” “Glare” (glare) is a bright light that is reflected off of a piece of glass or plastic. If you have glasses that reduce glare – they make it less, that means you won’t have that problem with the bright like reflecting off the glass or the plastic. It’s also possible to get lenses that darken automatically, so instead of having a pair of glasses that you use inside the house and another pair of sunglasses that you use outside, you can get lenses that will automatically darken when you go outside into the light. I had these for a few years when I was in high school, but they were rather inconvenient because it takes a while for the lenses to darken and to brighten up – to un-darken, so they weren’t very convenient in my opinion. Lenses can also have anti-scratch coating. A “scratch” is when you make a mark on a piece of glass or plastic that you don’t want; you can also scratch, for example the back of a watch or the front of a watch. “Coating” is something that goes over something else, usually to protect it. So, “anti-scratch coating” is a special chemical they put over the glass – over the lenses that prevents it from getting scratched.
Pierre says however, “I want to keep it nice and simple,” meaning very simple. “I don’t want any of those options.” Alice says, “How about these for a backup pair? They’re designer frames.” Something that “backs up” something else is something that you use in case the first thing doesn’t work or the first thing doesn’t operate properly. If you have a computer, you should also have another external disk drive or some sort of online service that backs up your files. Notice it can be used as a verb as well: “to backup.” I back up my files every day on an external hard drive. “Backup pair” refers to a pair of glasses that you use in case your first ones break or you have a problem with them.
Alice is looking at a pair of designer frames. “Designer” means that they are made by a company; they’re usually of a certain style or shape and they’re usually more expensive. So if you buy a dress made and designed by Versace, for example, or you buy something made by Prada, these are designer products; they are things that have a very special and unique sort of design to them.
Pierre says, “Give me those. I should have known better than to let you tag along. What was I thinking?!” “To tag” (tag) – some would pronounce it “tag,” but in my Minnesota accent it’s “tag” – “to tag along” means to go with someone somewhere they’re going even though you are not invited initially or the person is going even if you don’t go with them. So, if your older brother is going to the movies you may say, “Can I tag along?” meaning can I go with you, you didn’t invite me but I’d like to go. In this case, Alice tags along with Pierre to buy some glasses. Pierre is wishing that he never invited her to come with him.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Alice: Ooh, look at these! Don’t I look great? I’ve always wanted sunglasses like these.
Pierre: You’re supposed to be here helping me pick out frames for my new bifocals.
Alice: I don’t know why you won’t get progressives. That’s what everybody is getting these days.
Pierre: I’ve always had bifocals and that’s what I’m going to get.
Alice: Are you going to get metal, plastic, or rimless frames?
Pierre: I’m not sure. The optician said that with my prescription, I could get any kind.
Alice: Okay, try these. How do they feel?
Pierre: I like the way the hinges move, but they’re too small for my head. Hey, these are nice. I think I’ll go with these.
Alice: There’s no accounting for taste! Okay, but what about the lenses? There’s so many options. You can get ones that reduce glare, ones that darken automatically, ones with anti-scratch coating…
Pierre: I want to keep it nice and simple. I don’t want any of those options.
Alice: How about these for a backup pair? They’re designer frames.
Pierre: Give me those. I should have known better than to let you tag along. What was I thinking?!
[end of dialogue]
We don’t have a backup scriptwriter; we have only the wonderful Dr. Lucy Tse, who wrote this script.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
sunglasses – glasses that are worn to protect one’s eyes from bright sunshine and other strong lights
* Do you know where my sunglasses are? It’s really bright outside and I can’t see anything.
frames – the metal or plastic part that wraps around one’s ears and over one’s nose, used to hold clear glass or plastic in front of one’s eyes to correct one’s vision
* Luca liked the purple frames, but she didn’t get them because she didn’t think they looked very professional.
bifocals – glasses where the clear glass or plastic part has two sections with a small line in between, where the top section helps one see things that are far away and the bottom section helps one see things that are close
* If I didn’t have bifocals, I’d have to put on a different pair of glasses every time I wanted to read something, and then another pair every time I wanted to look at something further away.
progressives – glasses that have two or three sections, where the top section helps one see things that are far away, the middle section helps one see things at medium distance, and the bottom section helps one see things that are close, but there is no line in between the sections
* Meghan wants to get progressives, because she thinks bifocals are only for old people.
metal – a hard, usually heavy material like iron, steel, silver, gold, aluminum, nickel, or copper
* Which kind of metal do you want for your wedding ring? Gold or platinum?
plastic – a strong material, either hard or soft, made through a chemical process using petroleum
* She doesn’t want to buy any plastic toys for her children, because she prefers wooden and cloth toys.
rimless – without rims; without edges; glasses that have very little plastic or metal, so they are not very noticeable
* Chuck hopes his new rimless glasses make it look like he isn’t wearing glasses at all.
optician – a person whose job is to make glasses and help people see
* First, make an appointment with an optometrist to figure out what’s wrong with your vision, and then ask an optician to help you find the right pair of glasses.
prescription – a piece of paper where a doctor writes down what kind of medicine, or glasses or contact lenses a person needs
* Vanessa’s doctor gave her a prescription for antibiotics.
hinge – the small piece of metal that connects two larger pieces of wood, plastic, or metal, letting them move toward and away from each other, such as for a door or lid to close
* When the screw fell out of the hinge on his glasses, he temporarily fixed them with tape.
there’s no accounting for taste – a phrase used to show that one does not approve of another person’s choice in style or fashion, meaning that there is no way to explain why people like certain things while other people dislike them
* Our neighbors decided to paint their home bright orange and green. We think it’s really ugly, but they love it. There’s no accounting for taste.
lens – one of the clear glass or plastic pieces used in glasses or in a camera to change the way in which one’s eyes focus on something
* Melvin got a headache when he tried to look though his nephew’s lenses, because they were too strong for his vision.
glare – the bright light that is reflected off of a piece of glass or plastic
* They have a lot of framed photographs on their living room walls, but the glare when the sun is shining makes it almost impossible to see them.
to darken – to become darker; to begin to have a darker color; to have less light
* The painter darkened the red color by adding a little more black paint.
anti-scratch coating – a thin, invisible layer that goes on top of a piece of glass or plastic to protect it from getting small lines if something sharp moves against it
* I wish this watch had an anti-scratch coating. There are so many scratches and lines on it that it’s hard to see what time it is.
backup pair – an extra pair of glasses that one can use if one’s regular glasses are broken or lost
* Don’t forget to pack your backup pair of glasses, because I don’t want to spend our vacation time looking for a new pair of glasses if your old pair breaks!
designer -– with a well-known, expensive brand name
* These designer jeans cost almost 10 times as much as the other jeans in the store.
to tag along – to follow someone somewhere; to go somewhere with another person when one isn’t really needed there
* Jacques’s little brother wants to tag along everywhere he goes.
Comprehension Questions
1. Where might you find hinges?
a) On the frames.
b) On the prescription.
c) On the lenses.
2. Which lenses could take the place of sunglasses?
a) Lenses that reduce glare.
b) Lenses that darken automatically.
c) Lenses that have anti-scratch coating.
Answers at bottom.
What Else Does It Mean?
progressives
The word “progressives,” in this podcast, is used to describe glasses that have two or three sections, where the top section helps one see things that are far away, the middle section helps one see things at medium distance, and the bottom section helps one see things that are close, but there is no line in between the sections: “Are progressives more expensive than bifocals?” The word “progressive” is also used to describe something that is changing or growing over time: “The progressive increase in the size of the population will continue to strain the country’s health care system.” “Progressive taxes” are taxes where people with more money pay a higher percentage than people with less money do: “The United States has a progressive tax system, with rich people paying more than poor people.” A person or thing that is “progressive” supports new ideas and changes that will make things better: “Will you send your children to a regular school, or one of the new progressive schools?”
hinge
In this podcast, the word “hinge” means the small piece of metal that connects two larger pieces of wood, plastic, or metal, letting them move toward and away from each other, such as for a door or lid to close: “Please put some oil on the hinge so the door to the baby’s room isn’t so noisy.” A “hinged lid” is a lid that can be opened and closed, but not separated from the box or container, because it is attached on one side: “Their mailbox has a hinged lid.” The phrase “to hinge on (something)” means to depend on something: “Our ability to buy that home hinges on whether we can get a good loan.” Or, “The health of millions of people hinges on whether we can find a cure for AIDS.”
Culture Note
It is “pretty common” (not unusual) to see people wearing glasses and sunglasses, but there are some other types of “eyewear” (something that is worn over the eyes) that might “make you take a second look” (look at something again, more closely, because it is unusual or surprising).
Swimmers wear “goggles,” which are like small glasses, except that there is plastic around each lens that reaches to the swimmer’s face. Goggles “prevent” (don’t allow) water from touching the swimmer’s eyes, so that he or she can see things while underwater.
Many people who work in “construction” (making new buildings), “carpentry” (making things out of wood), and other fields where dangerous machines are used often wear “safety glasses,” which are large glasses that protect not only the front of the eye, but also the top, bottom, and sides. If a small piece of wood or some chemical comes toward the eye, it is stopped by the safety glasses before it can cause damage.
“3-D glasses,” or “three-dimensional glasses” are often made out of heavy paper, with one plastic blue lens and one plastic red lens. These glasses are used to watch 3-D television or movies. The images are filmed in a special way, so that when one is wearing 3-D glasses, it looks as if the images are coming out of the screen toward oneself.
Finally, an “eye patch” is a small piece of black fabric that is attached to a black string. The string is tied around one’s head so that the fabric hangs over one eye. People might use eye patches when they have a medical problem that doesn’t let them use one eye, or when they have only one eye.
Comprehension Answers
1 - a
2 - b