= 0512
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 512: Changing the Subject in Conversation.
This is English as a Second Language Podcast episode 512. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide, an 8- to 10-page guide we provide for all of our current episodes that will help you improve your English even faster. Or you can also make a donation if you’d like to support this podcast by going to our website.
This episode is a dialogue between Laura and Gaius talking about common expressions and phrases we use to change the subject (the topic) of our conversations. A very useful episode, I think you will find. Let’s get started.
[start of dialogue]
Laura: I think that’s all we need to talk about regarding last month’s report. Let’s turn to this month’s report, shall we? I didn’t get a copy of it. Could someone hand me one?
Gaius: By the way, I have just one last comment before we shift our focus to this month’s report. It seems to me that we need more information on how the Duluth office is doing. Could we ask for more info to be included in next month’s report?
Laura: I’m sure we can. Incidentally, Dee is quitting and Kara will be taking her place. This is off the record, of course. Okay, now back to this month’s report…
Gaius: Speaking of personnel changes, did you know that Lee is being promoted to V.P. next month?
Laura: I hadn’t heard that, but I’m not surprised. She’s been in line for that job for years. Okay, we need to get back to this month’s report…
Gaius: Something just occurred to me. If Lee is being promoted, what will happen to the Baseship project?
Laura: I think it’s being put on the back burner for now. All right, could someone hand me a copy of this month’s report?
Gaius: I don’t mean to change the subject but…
Laura: I think that’s precisely what you’re trying to do. What’s the matter with this month’s report?
Gaius: It’s not quite finished. It’ll be on your desk this afternoon.
Laura: Is that what this tap dance has been about? All right, we’ll talk about it at tomorrow’s meeting. Next time, just give it to me straight, okay?
[end of dialogue]
Our dialogue begins with Laura saying that she thinks that’s all they need to talk about regarding last month’s report. We’re obviously here in a business meeting, and Laura is the boss. She’s telling Gaius that they don’t need to talk about the report on what was done last month. Instead, she wants to talk about this month’s report, so she says, “Let’s turn to this month’s report, shall we?” “To turn to (something)” is one of the many expressions we’ll discuss in this dialogue used to change the subject of a conversation. It means let’s begin talking about something else, let’s begin to focus on something different. It’s somewhat of a formal expression that might be used by someone who is running a meeting, who is leading a group in a discussion. Laura says, “Let’s turn to this month’s report, shall we?” “Shall we” is a formal phrase inviting someone to join you in doing what you are doing. “Shall we dance?” means do you want to dance with me. No? Okay. Then you go to the next girl, you see. That was always my strategy!
Laura says that she didn’t get a copy of this month’s report, and asks if someone could hand her one. “To hand (someone) (something)” means to give something to someone. It’s a polite way of saying “please could you give me this thing,” or “pass me this thing.” “Could you hand me that pen, please?” means could you give me that pen, take it and put it into my hand. “Hand” has several different meanings in English; take a look at our Learning Guide for some additional explanations.
Gaius says, “By the way, I have just one last comment before we shift our focus to this month’s report.” “By the way” is a phrase used to say that you want to continue talking about something but add a slightly different topic, so it’s not a completely new subject. If you say, “Let’s turn to the Baseship project,” well, you’re saying I want to talk about something completely new, usually. But if you say “by the way,” you mean that you have something additional to say about the topic you’re talking about now, but slightly different than what you were just talking about. So, Gaius says, “By the way, I have just one last comment before we shift our focus to this month’s report.” “To shift (shift) your focus” means to begin discussing a new or different topic; it’s similar to “to turn to.” Gaius says, “It seems to me that we need more information on how the Duluth office is doing.” Duluth is a city in northern Minnesota. Gaius says, “Could we ask for more info (meaning information) to be included in next month’s report?”
Laura says, “I’m sure we can. Incidentally, Dee is quitting and Kara will be taking her place.” “Incidentally” (or, if it’s pronounced more carefully, “incidentally”) means that you want to add some additional information about the topic that you were just discussing – usually that’s what it means. Laura says that Dee is quitting and Kara will be taking her place. Perhaps Dee and Kara both work in the Duluth office, so this is an additional piece of information related to the topic they were just discussing. Then she says, “This is off the record, of course.” “Off the record” means unofficially. It’s a phrase that you use to tell people that the information you are giving them is secret. It’s usually used by government officials or other people who are being interviewed, for example, by a newspaper reporter, and they don’t want something “on the record,” meaning they don’t want something to be recorded – something to be written down. That’s what “the record” is here; it’s an account of something; it’s a story or details about something. So, “off the record” would mean I don’t want you to write this down or I don’t want you to tell anyone else I’m telling you.
Laura says, “Okay, now back to this month’s report…” Gaius, however, says, “Speaking of personnel changes, did you know that Lee is being promoted to V.P. next month?” “Speaking of” is a phrase used to show that you want to add more information that is related to the topic just mentioned. Once again, it’s another way of changing the topic of the conversation, but what you’re really doing here is linking – connecting the information you’re about to say with information that was just discussed. So for example if I’m talking about going to New York City on a vacation and my friend has a relative, someone who is part of his family that lives in New York, after I tell him my story, he may say to me, “Speaking of New York, I have an uncle who lives there, you know.” So he’s connecting his topic to my topic. Gaius says, “Speaking of personnel changes (personnel refers to the people who work for a company), did you know that Lee is being promoted to V.P. next month?” “To be promoted” means to get a better job, a job with more responsibility, a job that is higher up in the company.
Laura then says, “I hadn’t heard that, but I’m not surprised. She (meaning Lee) has been in line for that job for years. “To be in line for” means that you are the next person who will get something, you will be the next person to receive something, or you are ready for something to happen. Many people think California is in line for another major earthquake. We’re in line for – we’re waiting for it to happen, it will happen. We’re next, in other words.
Laura says, “Okay, we need to get back to this month’s report…” But Gaius doesn’t want to talk about this month’s report, He says, “Something just occurred to me (meaning I just thought of something). If Lee is being promoted, what will happen to the Baseship project (the name of a project they’re working on in their company)?” Laura says, “I think it’s being put on the back burner for now.” “To put (something) on the back burner” means to delay something or to stop focusing on something temporarily because it isn’t that important – it isn’t that urgent. Laura is saying that that project will probably be delayed. Then she says, “All right, could someone hand me a copy of this month’s report?” Remember, she asked for someone to give her a copy of the report at the beginning of the conversation.
Gaius says, “I don’t mean to change the subject but…” “To change the subject” means to changed topics, to stop discussing one thing and begin discussing something else. Laura interrupts him and says, “I think that’s precisely what you’re doing,” meaning you’re trying to change the subject so that we don’t talk about this month’s report. “Precisely,” here, means exactly – that’s exactly what you’re doing. “What’s the matter with this month’s report?” she finally asks. “What’s the matter with” means what’s wrong with. It’s something people use when something isn’t working correctly or isn’t behaving normally. You could say it about a person: “What’s wrong with your brother?” – he seems angry, why? Or, it could be something you use to talk about a machine: “What’s wrong with my computer? It stopped working.” Oh, I poured water on it; well, okay, that’s why it stopped working!
Gaius says, “It’s not quite finished (meaning this month’s report isn’t finished, he didn’t complete it). It will be on your desk this afternoon,” meaning I will give it to you this afternoon. Laura then says, “Is that what this tap dance has been all about?” “Tap dance” normally is a kind of dance where someone has special pieces of metal on their shoes – on the bottom of their shoes that make noise. But the expression here means that someone is trying to avoid talking about or avoid doing something by talking about something else. “I tap danced around the subject” – I didn’t want to talk about it so I talked about other things. It’s a negative expression in the sense that the person isn’t being direct, they aren’t going right to the truth. They’re trying to distract you by talking about other things, perhaps. Laura says, “Next time, just give it to me straight.” This is the opposite of giving someone a tap dance. “To give it to (someone) straight” means to tell the full truth, very directly, right away.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Laura: I think that’s all we need to talk about regarding last month’s report. Let’s turn to this month’s report, shall we? I didn’t get a copy of it. Could someone hand me one?
Gaius: By the way, I have just one last comment before we shift our focus to this month’s report. It seems to me that we need more information on how the Duluth office is doing. Could we ask for more info to be included in next month’s report?
Laura: I’m sure we can. Incidentally, Dee is quitting and Kara will be taking her place. This is off the record, of course. Okay, now back to this month’s report…
Gaius: Speaking of personnel changes, did you know that Lee is being promoted to V.P. next month?
Laura: I hadn’t heard that, but I’m not surprised. She’s been in line for that job for years. Okay, we need to get back to this month’s report…
Gaius: Something just occurred to me. If Lee is being promoted, what will happen to the Baseship project?
Laura: I think it’s being put on the back burner for now. All right, could someone hand me a copy of this month’s report?
Gaius: I don’t mean to change the subject but…
Laura: I think that’s precisely what you’re trying to do. What’s the matter with this month’s report?
Gaius: It’s not quite finished. It’ll be on your desk this afternoon.
Laura: Is that what this tap dance has been about? All right, we’ll talk about it at tomorrow’s meeting. Next time, just give it to me straight, okay?
[end of dialogue]
There’s nothing the matter with this episode’s script, because it was written by Dr. Lucy Tse.
Incidentally, if you want to help support us here at ESL Podcast, why don’t you become a member? Go to our website at eslpod.com and look at our Learning Guide membership options.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
to turn to (something) – to begin talking about something else; to begin to focus on something else; to change the subject of conversation to another topic
* After they discussed the weather and what they had done over the weekend, they turned to the projects they needed to do in the next week.
shall we – a formal phrase inviting someone to join oneself in doing something
* I love dancing to this type of music. Shall we?
to hand (someone) (something) – to give something to someone
* Could you please hand me that pencil? Thanks.
by the way – a phrase used when someone wants to say something that is only slightly related to the current discussion and isn’t the main focus
* The class was discussing recent developments in energy efficiency, when one student said, “By the way, did anyone read the articles in today’s newspaper about the tax credits for buying electric cars?”
to shift (one’s) focus – to begin discussing a different topic; to change the subject
* First, I’m going to pay my bills, and then I’m going to shift focus to cooking dinner for tonight.
incidentally – a word used when one wants to add information to what one has just said
* Thriftway is having a great sale on pork, chicken, and turkey. Incidentally, chicken is also on sale at Roth’s Market.
off the record – unofficially; a phrase used to let other people know that information is secret and shouldn’t be shared with others, or at least not while using the speaker’s name
* The politician agreed to have an interview with the reporter, but only if everything he said would be off the record.
speaking of (something) – a phrase used to show that one wants to add information that is somehow related to a particular topic that was just mentioned
* Maggie was talking about the way she disliked the color of her office, when Ahmed said, “Speaking of offices, we’ve decided to look for a new office building.”
to promote – to give someone a job with more responsibilities and better pay in the same organization, usually because he or she has been doing very good work
* Melissa was very happy to be promoted from Regional Sales Manager to National Sales Manager.
in line for – ready for something to happen; waiting to be next; waiting to receive something
* Many geologists think California is next in line for a major earthquake.
to occur to (someone) – to enter into someone’s mind; to become an idea that someone has
* It never occurred to me that you would be insulted by what I said. I’m sorry.
to put (something) on the back burner – to delay something or stop focusing on something temporarily because it is not very important or urgent
* Heather put her career on the back burner so that she could stay at home with her kids for a few years.
to change the subject – to change topics; to stop discussing one thing and begin discussing something else
* Whenever people start talking about work, Isaac tries to change the subject and talk about music or art instead.
precisely – exactly; with great accuracy
* He gets to work at precisely 7:58 each morning.
What’s the matter with (something)? – what’s wrong with something?; a phrase used to ask why something isn’t working correctly or behaving normally
* What’s the matter with your bicycle? Why is it making so much noise?
tap dance – an effort to avoid doing or talking about something, usually by doing or talking about something else, trying to change the focus of another person’s attention
* Isabella tried to do a tap dance around her parent’s questions about her new boyfriend, but they insisted that she answer them.
to give it to (one) straight – to tell someone the full truth very directly, without delaying it or hiding anything
* What are you trying to say? Just give it to me straight. Are you breaking up with me?
Comprehension Questions
1. What does Laura mean when she says, “this is off the record”?
a) Dee has worked in her position longer than anyone else.
b) The information about Dee and Kara is secret.
c) Dee and Kara work in a recording studio.
2. What does Laura mean when she says the Baseship project is “on the back burner”?
a) The project is behind schedule.
b) The project is related to cooking.
c) The project isn’t a high priority.
Answers at bottom.
What Else Does It Mean?
to hand (one)
The phrase “to hand (someone) (something),” in this podcast, means to give something to someone: “Could you please hand me that book?” The phrase “to hand (something) back to (someone)” means to return something to someone: “Please hand the pen back to the clerk when you’re finished using it.” The phrase “to hand (something) down” means to give something to someone after one has used it, or possibly after one has died: “She hands down all her clothes to her younger sister.” Or, “That vase has been handed down through the family for generations.” The phrase “to have to hand it to (someone)” means to give someone credit, or to admit that someone did something very well or is very good at something: “You have to hand it to Maxine. She’s a great tax accountant.”
off the record
In this podcast, the phrase “off the record” means unofficially and is used to let other people know that information is secret and shouldn’t be shared with others, or at least not while using the speaker’s name: “That was supposed to be off the record. Why did you publish it?” The phrase “to be on the record as saying” is used when one wants what one says to be written down and remembered, especially as part of a meeting where people do not agree on something: “I know that all of you want to vote for the proposal, but I want to be on the record as saying that I disagree.” Finally, the phrase “in record time” means very quickly, or faster than anyone else has ever done something before: “He finished his dinner in record time and then ran outside to play.”
Culture Note
Businesses have to create many different types of “reports” (written or oral descriptions of progress) to the government, “shareholders” (people who own stocks or small parts of a business), owners, and “creditors” (people and organizations who have loaned money and expect to be paid back).
Tax “filings” (information officially sent to an organization) are a common way of reporting to the government. Businesses have to “fill out” (write information on) tax “forms” (pieces of paper with empty lines to write down specific information) about how much money they have received and spent. The forms are used to calculate how much the business should pay to the government in taxes.
Shareholders and owners also want to have information about how a business is doing, usually more frequently than the government. Businesses regularly send their “financial statements” (pages showing how much money a business has in different “accounts” (money set aside for a particular purpose), usually “quarterly” (four times a year; every three months). Once a year, businesses usually give their shareholders and owners an “annual report” that includes the financial statements, as well as a written summary of what the business has done in the past year and what it is planning for the future.
Creditors are most interested in what a business is doing with its “loan” (the money the creditor has given) and whether the business will be able to “pay it back” (return the money with “interest” (extra money)). As long as the business is making payments, the creditors might not be interested in additional information. However, if the business has trouble repaying its loan, the creditor will probably begin asking for more detailed reports and explanations.
Comprehension Answers
1 - b
2 - c