= 0514
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 514: Describing Old and New Clothes.
This is English as a Second Language Podcast episode 514. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode. The Learning Guide contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension questions, and a complete transcript of everything we say on this episode. You can also find out about becoming a member and supporting us here at ESL Podcast, or you can also make a donation on our website.
This episode is a dialogue between Ellen and Hiro. It’s going to be using vocabulary that you would use to describe clothing, both old clothing and new clothing. Let’s get started.
[start of dialogue]
Ellen: What are you wearing to the party?
Hiro: Your guess is as good as mine.
Ellen: Let’s look through your closet and I’ll help you pick something out.
Hiro: Okay, but I have to warn you. I have a pretty limited wardrobe.
Ellen: Let’s see, these black pants are nice, but they’re frayed on the bottom. How about these jeans?
Hiro: You don’t think they’re too faded? There’s also a rip in the back.
Ellen: No, I guess those jeans won’t work. I like this shirt, though.
Hiro: Did you see the stain on the front? The zipper is also stuck, I think.
Ellen: How about shoes? Do you have any shoes that are presentable?
Hiro: Well, I always wear these, but they’re scuffed on the top and the sole is pretty worn.
Ellen: Okay, desperate times call for desperate measures. Come on!
Hiro: Where are we going?
Ellen: We’re going to a magical place with brand spanking new clothes and where everything is flawless.
Hiro: Where’s that?
Ellen: The mall!
[end of dialogue]
Our dialogue begins with Ellen asking Hiro, “What are you wearing to the party (what clothes are you going to wear to the party)?” Hiro says, “Your guess is as good as mine.” This phrase, “your guess is as good as mine,” means I don’t know, meaning that you don’t know any more than the person who is asking you the question.
Ellen says, “Let’s look through your closet (let’s look in your closet) and I’ll help you pick something out.” The “closet” is a small opening in the wall, usually covered by a door where you could store or keep your clothing. “To pick something out,” or “to pick out something” is a two-word phrasal verb meaning to select something from many different options. Usually it’s a physical thing; you go to a store and you pick out a dress to wear. I do this at least once a month! That’s to pick out something or to pick something out – either way.
Hiro says, “Okay, but I have to warn you. I have a pretty limited wardrobe.” “I have a pretty limited wardrobe” means I have a very limited (not very big) wardrobe. “Wardrobe” here means all the clothing that you own, a collection of all of your shirts and pants and ties and dresses and underwear and socks – all of that is part of your wardrobe.
Ellen says, “Let’s see, these black pants are nice, but they’re frayed on the bottom.” When something is “frayed” (frayed) we mean it is worn out; it is falling apart. When we talk about clothing, frayed clothing usually means that the clothing is beginning to come apart; you can see the individual threads – the individual pieces of the clothing, especially at the edge of the clothing, at the end of a sleeve on a shirt or on the bottom of your pants.
Ellen says, “How about these jeans?” meaning what do you think of these jeans. Hiro says, “You don’t think they’re too faded?” When we say something – a piece of clothing is “faded” (faded) we mean that the color isn’t as bright as it used to be. This happens when you buy blue jeans. When you buy them and you put them on the first time the blue may be very blue – very dark. But later, as you wash them over and over again, they may become lighter – they may become faded, we would say.
Hiro says, “There’s also a rip (rip) in the back (of the jeans).” A “rip” is the same as a tear; it’s a small hole when two things are separated from each other – or something, rather, is separated into two pieces we say that it has a rip. That’s especially used when talking about clothing. If you’re a man with big muscles, like me, and you put on a shirt that’s too small – that’s too tight and then you try to move your arms up and down, you might rip the shirt. The shirt might get a rip in it (notice it can be a verb or a noun), a tear – it will come apart. I have this problem!
Ellen says, “No, I guess those jeans won’t work. I like this shirt, though (I like this shirt, however).” Hiro says, “Did you see the stain (stain) on the front?” A “stain” is where there is a color on the fabric that shouldn’t be there. For example, if you are drinking coffee and you have a white shirt on, and some of the coffee drops fall onto your shirt, you spill it, then you will have a coffee stain – a brown stain on your white shirt. Another word for this is a “discoloration.”
Hiro says, “The zipper is also stuck, I think.” The “zipper” is the long strip of metal, usually, that you use to keep something together, but also allows you to open something up. So on a pair of jeans, for example, there is a zipper in the front at the very top that goes down about, maybe – I don’t know, one or two inches, and that allows you to take the pants off and put them on easily. It also allows men to use the bathroom, with their pants, more easily – in ways we shall not describe here! Hiro complains that the zipper is stuck. When something is “stuck,” we mean that it isn’t able to move. It should move, it’s supposed to move, but something is wrong with it and it doesn’t move. You could even get your hand stuck, for example, in a hole. You put your hand into a small hole and then you can’t get it out – your hand is stuck. Well here, the zipper is stuck, meaning that it won’t move up and down the way it should.
Ellen says, “How about shoes (meaning what shoes are you going to wear)? Do you have any shoes that are presentable?” The term “presentable” here means they are good enough for other people to see; they are acceptable or appropriate for whatever occasion that you are going to or being a part of. Hiro says, “Well, I always wear these, but they’re scuffed on the top and the sole is pretty worn.” “Scuffed” means that there are marks, usually on, for example, a pair of shoes or perhaps a wooden floor. Scuffs are usually caused by two things rubbing together hard. It causes a discoloration of the shoe; that is, there’s a mark on the shoe – maybe not a discoloration, although the scuff is usually a different color. “Scuff” can be a verb or a noun. Hiro says his shoes are scuffed, which is very common when you wear your shoes a lot. “The sole is pretty worn,” he says. The “sole” (sole) is the bottom of your shoe, in this case. You can also refer to the bottom of your feet as your sole: “the soles of my feet.” “Sole” is also a type of fish – which usually tastes better than your feet, at least my feet! He complains, Hiro does, that his sole is pretty (again, very) worn (worn). “Worn” damaged, old, used; in this case, too thin. You could see, perhaps, a hole in the bottom of the shoe. That would be a sole that was worn. “Worn,” like the word “stain” we discussed earlier, has a couple of different meanings in English that are explained – you guessed it – in the Learning Guide.
Ellen says, “Okay, desperate times call for desperate measures.” “To be desperate” means that you don’t have any other options and you must do something that you might not otherwise do. “Measures,” here, means things that you do, tasks, methods; things that you try to do to, in this case, fix a situation. So this common expression, “desperate times call for desperate measures,” means that when you have a very difficult situation sometimes you have to do some things that you would not normally do. The verb here, “to call for,” means to require.
So Ellen says, “Come on!” to Hiro, meaning follow me. Hiro says, “Where are we going?” Ellen says, “We’re going to a magical place with brand spanking new clothes and where everything is flawless.” Couple of terms here: a “magical place” would be a place with special powers, where impossible things can happen. “Brand,” in the sense of “brand new,” means complete new, entirely new. “Brand spanking new” is just a way of emphasizing it even more – it’s very new; it’s completely new. You could say, “this is brand new,” that would be the common way of describing something that you just bought that no one else has used. “Brand spanking new” is a little informal; it’s just giving more emphasis to this idea that it’s new.
Ellen says this place they’re going is a place where everything is flawless. A “flaw” (flaw) is a problem, a mistake, an error. “Flawless” (with a l-e-s-s at the end) means that it’s perfect, there are no flaws – no problems. Hiro says, “Where’s that?” Ellen says, “The mall!” meaning the shopping mall. So, Ellen is going to take Hiro to buy some new clothing.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Ellen: What are you wearing to the party?
Hiro: Your guess is as good as mine.
Ellen: Let’s look through your closet and I’ll help you pick something out.
Hiro: Okay, but I have to warn you. I have a pretty limited wardrobe.
Ellen: Let’s see, these black pants are nice, but they’re frayed on the bottom. How about these jeans?
Hiro: You don’t think they’re too faded? There’s also a rip in the back.
Ellen: No, I guess those jeans won’t work. I like this shirt, though.
Hiro: Did you see the stain on the front? The zipper is also stuck, I think.
Ellen: How about shoes? Do you have any shoes that are presentable?
Hiro: Well, I always wear these, but they’re scuffed on the top and the sole is pretty worn.
Ellen: Okay, desperate times call for desperate measures. Come on!
Hiro: Where are we going?
Ellen: We’re going to a magical place with brand spanking new clothes and where everything is flawless.
Hiro: Where’s that?
Ellen: The mall!
[end of dialogue]
The magical script for this episode was, I think you’ll agree, flawless. It was written by Dr. Lucy Tse.
From Los Angeles, California, I am Jeff McQuillan. I thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
Your guess is as good as mine – a phrase that means “I don’t know,” showing that the other person has the same amount of information about what will happen as oneself
* - What’s going to happen next?
* - I don’t know. Your guess is as good as mine.
closet – an opening in a wall, usually covered with doors so that it can be closed, that is used to hold clothing, shoes, hats, and accessories
* His wife’s clothes fill the closet, so he has nowhere to put his own clothes.
to pick (something) out – to choose or select something from many choices
* Wally is at the store, picking out a birthday present for his daughter.
wardrobe – all the clothes that one has; the collection of all of one’s clothing
* After Jaycee’s college graduation, she had to buy a new wardrobe because she needed more professional clothes for work.
frayed – worn out and falling apart, with individual threads separating from the fabric
* Many teenagers buy jeans that are already frayed at the bottom because they like the way they look.
faded – with a color that is paler (not as bright) than it used to be, usually because something has been washed and dried many times, or because it has spent too much time in the sun
* The couch used to be a beautiful dark red color, but now it’s faded because it has been in front of a sunny window for too many years.
rip – a tear; where a piece of fabric has opened up into two parts or pieces
* This skirt has a rip at the bottom. Can you please sew it for me?
stain – a discoloration; where a piece of fabric is dirty or has a spot with a different color, but that spot cannot be removed by washing
* When he spilled the red wine, it left a horrible stain on his suit jacket.
zipper – a long strip with many small pieces of metal or plastic that slide together to hold two pieces of fabric together, such as the top of one’s pants or the front of one’s jacket
* I can’t get this zipper open. How am I going to change my pants?
stuck – not able to move, often because something is not working correctly
* His hand got stuck in the little hole, and he can’t get it out.
presentable – acceptable and appropriate for being seen by other people; ready to be seen
* I need to change my clothes before your parents come over. I’m not presentable in these dirty jeans and this old T-shirt
scuffed – with marks from being rubbed against something with a lot of pressure
* The hardwood floors are scuffed where people have walked on them with their shoes.
sole – the bottom of one’s foot or shoe
* The soles of her feet were sore after having walked all day.
worn – used, damaged, old, and too thin
* The tires on your car are really worn! You need to replace them as soon as possible.
desperate times call for desperate measures – a phrase meaning that in a difficult situation, one needs to do something that one normally wouldn’t do
* In a slow economy, many companies ask their employees to agree to a lower salary. Desperate times call for desperate measures.
magical – with special powers to do exciting things that would normally be impossible
* King Midas had a magical ability to turn everything he touched into gold.
brand spanking new – completely or entirely new, without being old in any way
* We were really surprised to come home and see a brand spanking new car in the driveway!
flawless – without any problems or damage; in perfect condition
* Misty spent hours getting ready for the dance, making sure her hair and make-up were flawless.
Comprehension Questions
1. What’s wrong with Hiro’s shirt?
a) It’s torn.
b) It’s dirty.
c) It’s too old.
2. What does Ellen mean when she asks whether Hiro has any presentable shoes?
a) Whether the shoes were given to him as a present.
b) Whether the shoes can be given to someone else as a present.
c) Whether the shoes are appropriate for the party.
Answers at bottom.
What Else Does It Mean?
rip
The word “rip,” in this podcast, means a tear, or where a piece of fabric has opened up into two parts or pieces: “There was a rip at the bottom of the pants, so she cut off the legs and made them into a pair of shorts.” The phrase “to let (it/something) rip” means to make a car or a machine go as fast as it can: “Let’s see how fast this car can go. Let it rip!” A “rip-off” is something that was too expensive and a waste of one’s money: “What a rip-off! That movie was terrible. I wish we hadn’t bought tickets to see it.” Finally, as an acronym, “RIP” means “rest in peace,” and is often written on tombstones (pieces of stone above a grave, where a body is buried): “Here lies Anna (1842-1895). RIP.”
worn
In this podcast, the word “worn” means used, damaged, old, and too thin: “Almost all your clothes look worn. It’s time to go shopping for some new outfits!” Or, “This old rug is worn in the middle where everyone has been walking on it for years and years.” “Worn” is also the past participle of the verb “to wear”: “The museum has many of the clothes that were worn by Princess Diana and other famous people.” Something that is “time-worn” is old and has been used a lot: “This old building is time-worn, but beautiful.” The phrase “well-worn” has the same meaning: “Even though the seats on this train are well-worn, they are surprisingly comfortable.” Finally, the phrase “worn out” means very tired: “Jorge is always worn out by the end of the week.”
Culture Note
New York City is the “fashion capital” (a place where fashion is very important, popular, and influential) of the United States. New York Fashion Week is a “semiannual” (happening two times each year) event that “attracts” (brings in) important people in the fashion industry, such as “designers” (people who create ideas for new clothes) and “models” (beautiful people who wear clothes for other people to see), as well as “clothing buyers” (people who decide which clothes stores will buy and sell), “journalists” (news reporters), and “celebrities” (famous actors, singers, and musicians).
New York Fashion Week “is held in” (happens at) Bryant Park in New York City. There are many large “tents” (large pieces of cloth held up with long poles to create rooms outdoors) that have “runways” (long, narrow paths that models walk along) with “seating” (places for the audience to sit), sound, and lighting. New York Fashion Week is an “invitation-only event,” meaning that people can come only if they have been asked to come. The fashion designers create the “guest list” (the names of people who will be asked to come).
Most national newspapers report on New York Fashion Week, because the styles shown there “influence” (have an effect on) clothing trends. Few Americans can “afford” (have enough money to pay for) the expensive clothing made by “top” (leading; most important; best) designers for Fashion Week, but similar styles appear in lower-priced “department stores” (large stores that sell clothing and other items) soon after they appear on the runways.
Comprehension Answers
1 - b
2 - c