= 0524
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 524: Talking About Failure.
This is English as a Second Language Podcast episode 524. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. If you enjoy this podcast and would like to support us, consider becoming a member of ESL Podcast or making a donation by going to our website. Members receive our 8- to 10-page Learning Guide for each and every current episode of this podcast that will help you improve your English even faster.
This episode is called “Talking About Failure.” It’s a dialogue between Akiko and Gerry using vocabulary that we would employ – that we would use when talking about things that go wrong – things that fail. Let’s get started.
[start of dialogue]
Akiko: How did your presentation go over this morning at the meeting?
Gerry: It was a complete flop!
Akiko: I don’t believe it. You spent weeks working on that presentation.
Gerry: It wasn’t the presentation that bombed. It was my big idea. Leona called it a retread of what I presented last year, and she was not in the least impressed.
Akiko: Ouch, that’s pretty harsh. What did the others say?
Gerry: Overall, the response was dismal. Everyone else was trying to be tactful, but it boiled down to the fact that they thought it was pathetic.
Akiko: I’m sure that’s not true. And if they didn’t jump up and down about the idea right away, they’re bound to come around after you give them more details.
Gerry: I don’t know…
Akiko: Come on, aren’t you the same guy who told me that you didn’t know the meaning of the word “quit”?
Gerry: That was before this morning’s presentation.
Akiko: Are you giving up on your great idea?
Gerry: No, I guess not, but it’ll take some reworking…
Akiko: Good, then you won’t give up?
Gerry: I guess not. What the heck? I’m only risking more humiliation and failure, right?
Akiko: That’s the spirit!
[end of dialogue]
Akiko begins by asking Gerry, “How did your presentation go over this morning at the meeting?” The phrasal verb “to go over” here means how did people like it, how was it received – did people think it was good or bad? Something that “goes over well” is something that is good. Something that “goes over poorly,” obviously, is something that is bad. So, we use this expression “to go over” when we’re talking about a presentation, perhaps a performance; it might also be used in asking someone about something that they told somebody that might have been difficult for them to accept: “I told my boss I was leaving in two weeks. That didn’t go over very well.” He didn’t like it; he didn’t receive the news very well.
Gerry says his presentation was a complete flop (flop). “Flop” is a slightly informal way of saying “failure,” something that didn’t work as you planned, something that didn’t work correctly. Again, usually used to describe a performance of some sort or a presentation. We might say, “The movie was a flop,” we mean the movie was a failure, nobody liked it, it wasn’t popular, it didn’t make any money.
Akiko says, “I don’t believe it. You spent weeks working on that presentation.” Akiko doesn’t think it was a flop. Gerry, however, insists, “It wasn’t the presentation that bombed.” “To bomb” in this context means to fail, when some event or project doesn’t work as well as you had hoped. Once again, we can use the example of a movie: “The movie bombed.” It means it wasn’t very successful. A television show, a performance, a comedy routine (somebody telling jokes) – those are all things that can bomb. Both the word “bomb” and “flop” have different meanings in English; take a look at the Learning Guide for some additional explanations of those two terms.
Gerry says that the presentation didn’t bomb, it was his big idea. In other words, it wasn’t the way he presented it, it was what he was saying – the content, the idea behind his presentation. “Leona called it a retread of what I presented last year.” A “retread,” here, means something that is repeated from a previous project or a previous idea; it’s usually an insulting term – a negative term saying that it wasn’t original. Gerry says that Leona was not in the least impressed. “Not in the least” means not at all, not even a little bit: “Are you enjoying your new job?” and you say, “Not in the least. It’s horrible, and I want to quit.” That’s usually what I say when I start a new job!
Akiko says, “Ouch, that’s pretty harsh.” When someone says “ouch” in a situation like this they mean oh, that must hurt. “Ouch” is a word we use to express pain. Somebody punches you or you hit your arm on the door, you might say “Ouch!” It’s when something hurts. Well, this comment of Leona’s certainly hurt Gerry. Akiko says, “Ouch, that’s pretty harsh.” “Harsh,” in this case, means very negative, perhaps rude, something that is very direct. If you go up to a man and say, “Excuse me, you’re really ugly,” well, that’s pretty harsh!
Gerry says that the response, overall, from the other people at the presentation was dismal. “Dismal” (dismal) means not good, very bad, depressing, negative. You might describe the weather as dismal, or you might describe a book as dismal. Gerry says that everyone else was trying to be tactful. “To be tactful” (tactful) means to be very polite, to tell someone something with a lot of respect, but usually it’s bad news. You’re criticizing someone; you’re saying something bad about them, but you’re trying to be nice about it – you’re trying to say it in a nice way. That’s being tactful. Gerry says that it boiled down to the fact that they thought his idea was pathetic. “To boil down to (something)” means to be the same as something else, to give a summary of something, to get down to the very necessary – the important details of something. You may have lots of different reasons for buying a new car, but you probably have one or two reasons that are most important. So if you take away all the other ideas – all the other things you could consider, these are the things that are the most important. So, that’s what it means to boil down to: “I like the color of the car, I like the seats, but it boils down to the price; that’s the most important thing.” It’s the most essential element.
Gerry said that it boiled down to the fact that they thought his idea was pathetic (pathetic). Something that is “pathetic” make you feel sad because it is such a sad, useless thing. It’s something that deserves your sympathy. Something that is pathetic is so bad that you feel sorry for the person who’s doing it or who’s experiencing it. That was how bad Gerry’s idea was, I guess. We’re not told what his idea was.
Akiko says, “I’m sure that’s not true. And if they didn’t jump up and down about the idea right away, they’re bound to come around after you give them more details.” When you say somebody “jumps up and down about (something),” you mean they’re very excited about something. “To be bound to” means to be certain to happen, something that is very likely going to happen. What Akiko is saying here is that even though the other people at Gerry’s presentation weren’t excited about it, they didn’t jump up and down right away, they’re bound to come around after you give them more details. They’re very likely to come around. “To come around,” here, means to finally agree with someone even if you had a different opinion originally: My wife asked me to wear a green shirt because she thinks it looks good on me; I’ll don’t like the idea, but finally I come around to it. I decide okay, I’ll wear the green shirt. I’ll wear anything my wife tells me to wear, that’s the way it works! So here, Akiko is saying that the people are going to eventually like this idea once they get more details – more specific information about it.
Gerry says, “I don’t know,” he’s doubtful. Akiko tries to cheer him up – tries to make him happy by saying, “Come on, aren’t you the same guy (the same man) who told me that you didn’t know the meaning of the word ‘quit’?” The expression “he didn’t know the meaning of the word…” and then you put in the word, is a common one to say that a person is the opposite of whatever that word is. So if Gerry doesn’t know the meaning of the word “quit,” that means he’s never going to quit; he’s going to continue on, the opposite of quitting.
Gerry says that that was before this morning’s presentation, meaning that’s what he said before he made the presentation but he no longer thinks that. Akiko says, “Are you giving up on your great idea?” “To give up” means to abandon, to say okay, I’m not going to do that anymore. Gerry says, “No, I guess not, but it’ll take some reworking.” “To rework (something)” means to improve it, to revise it because it’s not good enough yet. Akiko says, “Good, then you won’t give up?” and Gerry says, “I guess not. What the heck?” The expression “what the heck” is a phrase used to show that you plan on doing something even though it might not be successful: I’m not a very good bowler – I don’t know how to bowl, but what the heck, I’m going to play a game with my friend because it’s fun, even though I’m going to do a bad job at it – what the heck.
So, Gerry says, “What the heck? I’m only risking more humiliation and failure, right?” “Humiliation” is when you are very embarrassed by something or someone. So, Gerry is saying well, I’m probably not going to succeed – I’m probably going to fail, but I’m going to try anyway. Of course, it’s not a good thing to think about being humiliated, so Gerry is kind of joking here. Akiko says, “That’s the spirit!” “That’s the spirit” is normally an expression we use to encourage someone else, to make them have the right attitude. But here, and often now, it’s used sarcastically; that is, Akiko’s making a joke. Gerry doesn’t seem to be very enthusiastic about his plan; he thinks it’s going to cause him to fail, and Akiko is making fun of his negative view, saying, “Oh, that’s the spirit,” when, of course, she means the opposite. That’s not the spirit – that’s not the attitude that he should have.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Akiko: How did your presentation go over this morning at the meeting?
Gerry: It was a complete flop!
Akiko: I don’t believe it. You spent weeks working on that presentation.
Gerry: It wasn’t the presentation that bombed. It was my big idea. Leona called it a retread of what I presented last year, and she was not in the least impressed.
Akiko: Ouch, that’s pretty harsh. What did the others say?
Gerry: Overall, the response was dismal. Everyone else was trying to be tactful, but it boiled down to the fact that they thought it was pathetic.
Akiko: I’m sure that’s not true. And if they didn’t jump up and down about the idea right away, they’re bound to come around after you give them more details.
Gerry: I don’t know…
Akiko: Come on, aren’t you the same guy who told me that you didn’t know the meaning of the word “quit”?
Gerry: That was before this morning’s presentation.
Akiko: Are you giving up on your great idea?
Gerry: No, I guess not, but it’ll take some reworking…
Akiko: Good, then you won’t give up?
Gerry: I guess not. What the heck? I’m only risking more humiliation and failure, right?
Akiko: That’s the spirit!
[end of dialogue]
The dialogue for this episode was not in the least a flop. That’s because it was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
to go over – to happen and be perceived by other people as being good or bad
* His liberal speech didn’t go over very well with the conservative audience.
flop – a failure; something that doesn’t work as planned; something that doesn’t work correctly
* The party was a total flop. Hundreds of people were invited, but only three people came!
to bomb – to fail; for an event or project to be very unpopular and disliked; to not be successful in any way
* Jacques had planned to ask Helene to marry him, but he was so nervous that he bombed and she couldn’t even understand what he was saying.
retread – something that has already been done once before and is now being repeated
* I registered to go to the conference again this year, but I hope it isn’t just a retread of everything they talked about last year.
not in the least – not at all; not even a little bit
* - Are you enjoying your new job?
* - Not in the least. It’s horrible and I want to quit.
harsh – very direct and negative and perhaps rude
* Try not to be so harsh! Instead of saying, “That orange dress is ugly,” try saying, “I think you’d look even better in a pink or yellow dress.”
dismal – depressing and negative; not good or optimistic
* In this economic recession, sales have been dismal and the company might have to close some of its offices.
tactful – very polite and with a lot of respect, especially when sharing bad news or criticism
* Is there a tactful way to tell Jeremy that his breath smells bad?
to boil down to (something) – to be the same as something else, once all the extra, unnecessary details are taken away
* Some universities have better academic programs than others, but her decision of where to study will boil down to the cost of tuition.
pathetic – deserving sympathy and making one feel sad because something is so sad, useless, and without hope
* Gina thinks it’s pathetic to see old men trying to date girls who are in their early 20s.
to jump up and down – to be very excited about something, possibly jumping up and down because one has too much excitement and energy
* The children began jumping up and down when their father said they could get a dog.
to be bound to – to be certain to happen; to have to happen; to be very likely
* You’re bound to make a lot of money if you become a heart surgeon.
to come around – to finally agree with someone after one has had a different opinion for a long period of time; to be persuaded to change one’s opinion to agree with another person
* Medina has been asking her parents to let her pierce her ears for years, and they’re finally coming around.
to not know the meaning of the word “quit” – to be a person who never quits or gives up; to be a person who always does what he or she has planned to do, no matter how difficult it may be; to be very persistent
* Jolene doesn’t know the meaning of the word “quit”! Even though she has received hundreds of rejection letters, she keeps applying for more jobs.
to rework – to revise and improve something, usually because it still isn’t good enough
* She finished the first draft of her essay last night, but she still needs to rework it before giving it to the teacher.
what the heck – a phrase used to show that one plans to do something, even though it probably will not be successful
* I know I’m on a diet and shouldn’t eat this ice cream, but what the heck? I can always start a new diet tomorrow.
humiliation – strong feelings of embarrassment caused when other people laugh or say bad things about what one has done
* Vicente hated the humiliation of being laughed at by all the other students in his class.
Comprehension Questions
1. Why was Gerry’s presentation a flop?
a) Because he forgot what he had planned to say.
b) Because few people came to hear his presentation.
c) Because nobody liked the idea he presented.
2. What does Gerry mean when he says “it’ll take some reworking”?
a) He’ll have to find a new job.
b) He’ll have to give the same presentation again.
c) He’ll have to improve his idea.
Answers at bottom.
What Else Does It Mean?
flop
The word “flop,” in this podcast, means a failure, or something that doesn’t work as planned: “Their new business was a flop, making only one sale in the first four months.” The verb “to flop” means to be a failure: “Nobody expected the movie to flop like it did.” The verb “to flop” also means to lie down or sit down on something heavily, usually because one is very tired: “As soon as he comes home, he flops onto the couch and watches TV.” When fish are out of the water, they “flop” when their bodies jump up and fall back down: “The fish were flopping in the bucket after they were caught.” Finally, an animal that has “floppy ears” has ears that hang down: “Look at that goat with floppy ears! It’s so cute!”
to bomb
In this podcast, the verb “to bomb” means to fail, or for something to not be successful in any way: “The play bombed at the theater last night. Most of the audience members left before it was over.” The verb “to bomb” also means to drop explosive weapons onto a building or a piece of land, often in a war: “Do you think the enemy will bomb the government buildings?” Or, “Did the military bomb the hospital on purpose, or was that a mistake?” The informal phrase “to be the bomb” means to be very good at something, or to be the best: “That new dance club is the bomb! Everybody loves going there.” Or, “This new book is the bomb! You have to read it as soon as you can.”
Culture Note
In the late 1990s, people invested a lot of money in “dot.com companies” (companies working online, named for the way we pronounce URLs ending in “.com”). Suddenly, companies became much more attractive if it used “e-“ as a “prefix” (something that comes before a word) or “.com” as a “suffix (something that comes after a word) to its name.
That period became known as the “dot.com bubble,” because people invested much more than the companies were actually worth, and eventually everything “fell apart” (stopped working). The “stock market” (the part of the economy where people buy and sell small pieces of ownership in companies) “crashed” (decreased very quickly), and many people “suffered” (experience financial loss, pain, and other negative consequences) in the dot.com “bust” (failure).
In the dot.com bust, many companies “went out of business,” meaning they could not continue operating as a business because they had lost too much money. For example, eToys.com had a “share price” (the amount of money that one piece of ownership in a company can be sold for) of $80 in May 1999, but that number had “fallen” (decreased) to $1 in February 2001, when the company “declared bankruptcy” (made an official statement that it could not pay all the money it owed).
“In all” (overall), the dot.com crash caused technology companies to lose $5 trillion in “market value” (the total amount that all shares could be sold for) between March 2000 and October 2002. Businesses and individuals who had invested in technology companies and dot.coms lost a lot of money.
Comprehension Answers
1 - c
2 - c