= 0540
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 540: Promoting a New Product.
This is English as a Second Language Podcast episode 540. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Go there to support this free audio podcast by becoming an ESL Podcast Learning Guide member. With a Learning Guide membership you can download an 8- to 10-page guide for each of our current episodes, that gives you the complete transcript, vocabulary, definitions, sample sentences, cultural notes, comprehension checks, and more. You can also support this podcast by making a donation on our website.
This episode is called “Promoting a New Product.” It’s a dialogue between Zoila and Leo using vocabulary that would be associated, or related to promoting or trying to sell a new business product. Let’s get started.
[start of dialogue]
Zoila: I haven’t seen you around lately. What have you been up to?
Leo: My business partners and I have been putting the final touches on our new line of energy drinks.
Zoila: Really? I didn’t even know that you were in the beverage business.
Leo: Yeah, we’ve branched out into a few other areas. We’re going to start promoting the new drinks very soon. We’re working with an advertising agency and we’ll start with sponsoring a couple of sporting events.
Zoila: Wow, when am I going to start seeing ads on TV?
Leo: I don’t think we’re going to go that route just yet.
Zoila: Are you taking the new products to trade shows?
Leo: No, no trade shows for us. We’re working on product placement in some music videos and maybe a TV show or two.
Zoila: That’s great. What about tie-ins with other products or with a movie? I see those everywhere.
Leo: We’re considering it. We’re working on a couple of endorsement deals right now. Once we have some celebrities on board, we’ll do even more.
Zoila: It would be great if you could get Jeff McQuillan to endorse your products. Everybody knows he’s the greatest baseball player who ever lived. With him plugging your energy drinks, sales will go through the roof.
Leo: Yeah, but I think we’d be shooting too high. We might have to settle for someone a little less famous – like David Beckham or Lance Armstrong.
[end of dialogue]
Our dialogue begins with Zoila saying, “I haven’t seen you around lately. What have you been up to?” meaning what have you been doing. Leo says, “My business partners and I have been putting the final touches on our new line of energy drinks.” Leo has a business, and the people who own the business with him are called his “business partners.” They’ve been putting the final touches on something. “To put the final touches on (something)” means to do the last, usually minor things that you need to finish a project, to complete the final steps of something. You could say, “I’m writing a report for my boss. I’m almost done with it, I just need to put a title on it and put it in a nice folder,” that would be putting the final touches on it. Leo and his partners are putting the final touches on their new line of energy drinks. Here, “line” refers to a group of related products that are sold by one company. Coca-Cola Company has a line of soft drinks – of soda pops, or simply “soda.” Coke, Diet Coke, etc., those are all part of a group of related products, or a line. “Line,” however, has several different meanings in English; take a look at our Learning Guide for some additional explanations.
Well, Leo and his business partners are putting the final touches on the new line of energy drinks they have. “Energy drinks” are drinks that give you more energy, often have a lot of caffeine in them. College students sometimes use energy drinks when they need to study for an exam late at night, especially when they should have been studying in the past and they wait until the last minute.
Zoila says, “Really? I didn’t even know that you were in the beverage business.” A “beverage” is a drink. Coffee is a beverage; alcohol is a beverage; tea is a beverage. At a restaurant, usually, the word that you use for the things that you are going to drink, or want to drink, is beverage. The waiter may ask you, “Would you like a beverage?” Would you like something to drink?
Leo says, “Yeah, we’ve branched out into a few other areas.” His company has branched out. “To branch out” is a phrasal verb meaning to expand into different areas or fields, to grow into some sort of new operation – new kind of business. The word “branch” comes from the part of the tree; we call the parts of the tree that go out from the main section of the tree “branches.” That main section is called the “trunk.” Well, Leo is branching out into new areas. He says his company is going to start promoting the new drinks very soon. “To promote a product” means to tell other people about it; by telling them how good it is, trying to get other people interested so that they will want to buy the product. We can use “promote” in a business sense for a new product or service. We also use the word “promote” in a business sense to mean when someone gets a better job. When they go from being vice president to president, we say they’ve been promoted.
Leo says that he and his business partners are working with an advertising agency and that they will start with sponsoring a couple of sports events. An “advertising agency” is a company that specializes in helping other companies get people interested in buying their product; they may put a commercial on the television, or put an announcement in the newspaper. That’s what an advertising agency does. Traditionally, the largest advertising agencies always had an office in New York City on one particular street called Madison Avenue, and sometimes people will use the words or term Madison Avenue to refer to advertising companies or people involved in publicity and promotion.
Leo says that they’re going to sponsor a couple of sporting events. “To sponsor” means to provide money for an event or a program and you, in return, get the opportunity to advertise your product or service to the people who are going to that event or program. Many times a sporting event – a game will be sponsored by a particular company, so everyone who goes the game knows that this game was, in part, paid for by that company. It’s a way of advertising, and also a way of showing that you are interested in helping the community perhaps.
Zoila says, “Wow, when am I going to start seeing ads on TV?” “Ad” is short for advertisement; we also would call those, on television, “commercials,” it’s the same thing. A “commercial” would only be on the TV or the radio; an “ad” could be on TV, radio, or in a magazine or newspaper. Leo says, “I don’t think we’re going to go that route just yet.” “To go that route” means to do that particular thing, to take a specific direction with your actions. So you could say, “I was thinking about going and getting my master’s degree, but I decided not to go that route.” I decided not to do that or those series of things. Here, Leo is saying that they are not going to be putting commercials, or ads, on the television.
Zoila then asks, “Are you taking the new products to trade shows?” A “trade show” is a large event, usually held in a big auditorium or hotel, where companies that have similar products get together, typically once a year, to show their new products and their new services. The word “trade” here simply refers to the business – the particular business. So you could have a trade show for dentists, where all the companies that make products for dentists would get together so that other companies, or dentists themselves, could go and look and see what there was to buy. Leo says, “No, no trade shows for us,” meaning we’re not going to any trade shows. “We’re working on product placement in some music videos and maybe a TV show or two.” “Product placement” is when a company tries to get its product as part of a movie, TV show, or other types of entertainment. So you could be watching a TV show, and somebody’s drinking a can of Coca-Cola. Well, Coca-Cola probably paid the makers of that TV program to put their product in that TV program. This happens a lot in American television and in American movies. That’s called product placement.
Zoila says, “That’s great. What about tie-ins with other products or with a movie? I see those everywhere.” A “tie-in” is a connection between two or more things, especially when you are trying to sell something related to a movie or a TV show. So, you could have a famous movie such as Star Wars, and one of the tie-ins could be little dolls – a little doll of Chewbacca for example. That would be a tie-in to the movie; it is related to the movie. Leo says, “We’re considering (tie-ins). We’re working on a couple of endorsement deals right now. Once we have some celebrities on board, we’ll do even more.” An “endorsement” is when a famous person says that they like this product or service, and they use that person’s name and his picture or part of a video to promote that product. Usually these are famous sports stars, such as the golfer Tiger Woods, or entertainment stars that endorse, or say they like this product, and that, of course, gets other people interested in the product. At least that’s the idea. Leo says once they have some “celebrities,” famous people, on board, we’ll do even more. “On board” here means agreeing to participate in something.
Zoila says, “It would be great if you could get Jeff McQuillan to endorse your products. Everybody knows he’s the greatest baseball player who ever lived. With him plugging your energy drinks, sales will go through the roof.” Zoila is suggesting that a very famous baseball player, whose name is the same as mine, could endorse this product – these energy drinks. She says, “ With him plugging your energy drinks, sales will go through the roof.” “To plug” means to promote, to endorse, to say that you use this product and you like it. When we say “sales will go through the roof,” we mean that they will go to a very high amount, and usually go up very quickly. So if Jeff McQuillan was plugging the product, they would sell a lot of the product very quickly.
Leo says, “Yeah, but I think we’d be shooting too high. We might have to settle for someone a little less famous – like David Beckham or Lance Armstrong.” “To shoot too high” means to try to do something that is too difficult or something that is too out of reach – too advanced, perhaps. So, they’re saying here that Jeff McQuillan probably would not want to endorse or plug anything, he’s too famous, so they will have to settle for someone less famous. “To settle for” means to accept something that isn’t your first choice; you really wanted to have this, but you’ll settle for something a little less, something that was your third or fourth choice for example. “Settle” has a couple of different meanings; take a look at the Learning Guide for some additional explanations.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Zoila: I haven’t seen you around lately. What have you been up to?
Leo: My business partners and I have been putting the final touches on our new line of energy drinks.
Zoila: Really? I didn’t even know that you were in the beverage business.
Leo: Yeah, we’ve branched out into a few other areas. We’re going to start promoting the new drinks very soon. We’re working with an advertising agency and we’ll start with sponsoring a couple of sporting events.
Zoila: Wow, when am I going to start seeing your ads on TV?
Leo: I don’t think we’re going to go that route just yet.
Zoila: Are you taking the new products to trade shows?
Leo: No, no trade shows for us. We’re working on product placement in some music videos and maybe a TV show or two.
Zoila: That’s great. What about tie-ins with other products or with a movie? I see those everywhere.
Leo: We’re considering it. We’re working on a couple of endorsement deals right now. Once we have some celebrities on board, we’ll do even more.
Zoila: It would be great if you could get Jeff McQuillan to endorse your products. Everybody knows he’s the greatest baseball player who ever lived. With him plugging your energy drinks, sales will go through the roof.
Leo: Yeah, but I think we’d be shooting too high. We might have to settle for someone a little less famous – like David Beckham or Lance Armstrong.
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse. Don’t settle for less!
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
to put the final touches on (something) – to do the last, minor things needed to finish a project; to complete the last steps
* We’re just putting the final touches on the report, and we’ll have it finished in less than an hour.
line – a group of related products that are sold by one company
* This company is famous for its line of inexpensive women’s jewelry.
to branch out – to expand into different areas or fields; to grow
* The soccer club used to be only for adults, but now it’s branching out into children’s programs.
to promote – to say good things about a product or service to try to generate interest and make other people want to have or to buy it
* Many companies are starting to promote their products on Twitter.
advertising agency – a company that specializes in helping companies get people interested in buying those companies’ products and services
* They’re looking for an advertising agency that specializes in cars and trucks.
to sponsor – to provide money for an event or program and receive opportunities to advertise one’s company or products at that event or in that program
* Companies that sponsor the high school football team get to put their advertisements on the stadium walls.
ad – advertisement; a short video or printed image and text that provides information about a product or service and where one can buy it
* I saw a TV ad for pizza, and it made me really hungry!
to go that route – to do a particular thing; to take a specific direction with one’s actions
* We talked about getting married, but we decided we’re not ready to go that route quite yet. Maybe we will in a year or two.
trade show – a large event attended by representatives of many companies in one industry, where they display their products and services and try to find new customers
* This weekend, there’s a dentists’ trade show at the fairgrounds, where companies will be showing their dental tools, chairs, medications, and more.
product placement – the practice of having a particular company’s product photographed or filmed in a movie, TV show, or news story so that viewers or readers will see it and subconsciously (without being aware of something) want to have or buy it
* How much does a company have to pay for product placement in a major Hollywood movie?
tie-in – a connection between two or more things, especially to market or promote a product by relating it to a movie or TV show
* Their sales more than doubled once they started using a tie-in to a popular TV show.
endorsement – a statement, usually from a famous person, about how good a product or service is and how much it has helped him or her; testimonial
* Are you more likely to buy a beauty product if it has an endorsement from a well-known actress?
deal – an official agreement to do something; a contract
* The company made a deal with Kirsten: it would pay her 10% of the sales price for the first 2,500 units she sold, and 15% of the sales price for each unit beyond that.
on board – in agreement; agreeing to and participating in something
* Kaza plans to travel for one year between high school and college, but he still needs to get his parents on board with that idea.
to plug – to promote; to endorse; to say that one thinks a certain product is very good or beneficial and encourage other people to use or buy it
* Do you think it’s acceptable for teachers to plug products in their classroom?
through the roof – with a high amount of something; going up very quickly
* After he broke his leg and wasn’t able to exercise anymore, his weight went through the roof.
to shoot too high – to try to do something that is too difficult or too advanced
* The program was designed to help 50,000 poor families, but the leaders were shooting too high. They were actually able to help only 30,000 families.
to settle for – to accept something other than one’s first choice; to be satisfied with one option, even though it isn’t the best one
* The Hardwicks wanted to buy a large home on the coast, but they settled for a small two-bedroom home instead.
Comprehension Questions
1. What is the advertising agency going to help the company do?
a) Organize sporting events.
b) Have its drinks sold at sporting events.
c) Advertise at sporting events.
2. According to Leo, which of these people is the most famous athlete?
a) Jeff McQuillan.
b) David Beckam.
c) Lance Armstrong.
Answers at bottom.
What Else Does It Mean?
line
The word “line,” in this podcast, means a group of related products that are sold by one company: “The company is launching a new line of running shoes.” The phrase “to drop (someone) a line” means to send a short note, usually as a short letter, email, or text message: “I just wanted to drop you a line and say ‘hi.’” The phrase “don’t give me that line” is rude and is used to tell someone that you don’t believe what he or she has said, especially if he or she has given an excuse: “Mindy said she saw you at the party, so don’t give me that line about staying home because you didn’t feel well.” The phrase “to be on the line” means to be at risk of being lost or damaged: “If this presentation doesn’t go well, our jobs are on the line.”
to settle for
In this podcast, the phrase “to settle for” means to accept something other than one’s first choice and to be satisfied with that option, even though it isn’t the best one: “Ricky is asking for $65,000, but he’ll settle for $50,000 if the company offers enough vacation time.” The phrase “to settle down” means to live a calmer, more stable life, especially after one is married: “Paolo had a lot of fun in his 20s, but now he wants to settle down, find a wife, and start a family.” The phrase “to settle in” means to feel comfortable in a new situation: “It took Theo a few weeks to settle in at his new job.” Finally, the phrase “to settle up” means to pay the money that one owes: “During our vacation, we put all the expenses on Brock’s credit card. We’ll settle up once we’re back home.”
Culture Note
“These days” (in modern times), it’s hard to find a website that isn’t covered in advertising. Companies that traditionally advertised through television, radio, magazines, and newspapers are now “turning to” (beginning to consider or use) online advertising, placing their ads on websites.
Pop-up ads are one popular – “albeit” (but; although) “annoying” (unpleasant and frustrating) – type of online advertising. When you visit a webpage and another “window” (one box on a computer screen) opens over it, you’re seeing a “pop-up ad” because it “pops up” (appears unexpectedly) when you are trying to see something else. Most “Internet browsers” (software programs used to see webpages) have “pop-up blockers” (tools that don’t allow pop-up ads to be seen), but they don’t always work very well.
Many websites have “banner ads,” which are rectangular ads on the website, usually at the top or side of the page. In the past, these were only “text ads” (only words, without images), but now they have multiple images, graphics, and “Flash animation” (a way for the images to change in a sequence). Some banner ads have sound, too. Occasionally banner ads “fill the screen” (cover the entire computer screen) when you first visit a website, and then “shrink” (become smaller) to a “standard” (normal; regular) banner size after a few seconds.
As Internet connection speeds increase, more and more companies are using “video ads” to promote their products and services. In a video ad, a short video plays, sometimes as a “loop” (starting over when it reaches the end) and usually with sound. Videos ads are “eye-catching” (getting someone’s attention) and are more difficult to ignore than other “static” (non-moving) types of ads.
Comprehension Answers
1 - c
2 - a