= 0546
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 546: Having an Open House.
This is English as a Second Language Podcast episode 546. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this audio episode. The Learning Guide contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension questions, and a complete transcript of everything we say on this episode. So if you’re having difficulty understanding something, or want to look at the vocabulary and get new sample sentences or new definitions, go to the website and download the Learning Guide.
This episode is called “Having an Open House.” It’s a dialogue between Kyoko and Ernie; they’re going to be using some vocabulary that is common when we talk about open houses, when you sell your house. We’ll find out more about that in a minute. Let’s get started.
[start of dialogue]
Kyoko: We’re not supposed to be here. I think we should leave and let our real estate agent hold the open house without us looking over her shoulder.
Ernie: We’re not looking over her shoulder. I just want to sit in this car to see how many people go in and out.
Kyoko: You know, there’ll be a lot of lookie-loos. And plus, there’ll be a sign-in sheet, so we’ll be able to see afterwards how many people stopped in.
Ernie: Hey, someone’s coming in now.
Kyoko: That’s the stager. She’s making some last-minute changes.
Ernie: She really doesn’t need to do anything else. We did everything our agent told us to do. We made cosmetic repairs, painted, and de-cluttered. What more could they ask for?
Kyoko: She’s just doing some minor landscaping, putting some plants along the front path and around the front door. Let’s get out of here before people start showing up. I don’t want to seem like I’m spying on my own house.
Ernie: What does it matter? Hand me the fact sheet for our house. I want to read it through again to make sure the agent didn’t miss anything. Okay, the square footage on the house and the lot are correct, she noted that our addition is permitted, and she mentioned the upgrades – good. Where are you going?
Kyoko: I’m not going to sit in this car for the next four hours. Let’s go to visit our neighbors’ open houses.
Ernie: Good idea. We’ll see what our competition is and maybe we can steal some of their open house ideas!
[end of dialogue]
Kyoko begins this dialogue by saying to Ernie, “We’re not supposed to be here.” What she’s saying is that this is a place where they are not permitted or that they should not be in. “We’re not supposed to be here. I think we should leave and let our real estate agent hold the open house without us looking over her shoulder.” A “real estate agent” refers to a person, the agent, who sells houses and buildings – real estate. So a real estate agent is someone who sells and buys homes, buildings, and sometimes just the land.
An “open house” is an event where people can come into a home that is for sale, walk through it, look at it, learn about it, ask questions of the real estate agent, the person who’s selling the home for the owners; in the United States this is a very common custom. To sell your house you have, usually on a Sunday afternoon from one in the afternoon to perhaps four or two to five, you have people come to your house, you advertise your house for sale, people come and walk around it and look at it and can ask the agent questions. Typically, however, the owners of the house are not at the open house. The real estate agent is responsible for showing the house. Some people like to have open houses because it gets more people interested in their house, and perhaps someone will buy it from looking at it. Some people don’t like open houses because many times the people who go and look at the house are not really interested in buying it; they just want to see what the house looks like. So if you come to the United States in you’re in a large city, you can buy the Sunday newspaper, take a look at the open house listings, and simply go and take a look at some houses, pretending perhaps that you’re interested. Many people go and look at other people’s houses if they’re going to be selling theirs to see how good the house is for the price. It sometimes helps you figure out what price you want to put on your house. Most real estate agents know that many of the people who come to the house are not really that interested in buying it; they just want to see. Sometimes even the neighbors come and look at a house that is being sold in their neighborhood.
Kyoko says that she thinks that she and Ernie should leave. She says that they should let their real estate agent hold the open house – “to hold an open house” means to have an open house – “without us looking over her shoulder.” “To look over (someone’s) shoulder” is an expression that means to watch another person’s work very closely, to pay careful attention to what another person is doing, especially when that person doesn’t want you watching them. So you’re doing something at your desk in your office and your boss comes over and looks at what you are doing and watches you work, you might say to him, “Why are you looking over my shoulder?” He may, or she, may not actually be looking over your shoulder, that is looking down at your desk with their head above your shoulder. It’s the expression that we use to mean to watch someone else working when they don’t really want you watching them working.
Ernie says, “We’re not looking over her shoulder. I just want to sit in this car to see how many people go in and out.” So they’re not in the house; they’re sitting in their car outside of the house. Kyoko says, “You know, there’ll be a lot of lookie-loos.” A “lookie-loo” is an informal expression for someone who likes to see what is happening, especially someone who doesn’t really need to see it. So in this case, lookie-loos would be people, as I mentioned earlier, who go to the open house and don’t want to buy the house, they just want to see the house. Kyoko says, “And plus (meaning in addition), there’ll be a sign-in sheet, so we will be able to see afterwards how many people stopped in.” A “sign-in sheet” is a piece of paper where everyone who is participating or attending a certain event puts his or her name, sometimes the address and the phone number. In open houses, real estate agents asks everyone who comes into the house to sign the sign-in sheet, mainly to get their name and telephone number and call them later to see if they’re interested in selling their house or interested in buying the house. It is also proof to the owners of the house that people came and looked at the house. The term “sign-in sheet” can be used for any event, anything that you want people, when they first come to, to put down their name, sometimes their signature. So Kyoko is telling Ernie that they don’t need to sit there and watch everyone going into the house, they can just look at the sign-in sheet later.
Ernie says, “Hey, someone’s coming in now.” Someone is going into their house. Kyoko says, “That’s the stager. She’s making some last-minute changes.” A “stager” (stager) is a person whose job it is to make the home look nice. Sometimes when people move and they haven’t sold their house, the house will be empty when people come to look at it. Real estate agents have found that people are more likely to buy a house if they can imagine themselves in the house, and that means putting things in the house – the empty house – that will help you imagine what the house will look like. So you put a bed in, you put a television in, you put pictures on the wall. None of these belong to the owner; they’re just there to help the people looking at the house to get a better picture, if you will, of what the house looks like when there is furniture inside. “To make last-minute changes” means to change something right before the event starts, in the last hour or maybe last day.
Ernie says, “She really doesn’t need to do anything else (that is, the stager). We did everything our agent told us to do. We made cosmetic repairs, painted, and de-cluttered.” “To repair (something)” is to fix it. A “cosmetic repair” improves the appearance of something, in this case the appearance of the house. You don’t actually make it a better house, or a stronger or a safer house; you may paint the walls, for example. That’s a cosmetic change. You may fix something that is broken so that it looks better; that would be a cosmetic repair. “To clutter” (clutter) means to put too many things in a space, on your desk or in a room, so that it looks crowded. “To de-clutter,” then, means to take away things so that the space is more open, that you can see the desk, you can see the room better.
Kyoko says the stager is doing some minor landscaping. “Landscaping” is when you do something with the plants, the trees, the grass outside of a home to make it more beautiful. She says that the stager is putting some plants along the front path, where people walk into the house. “Let’s get out of here before people start showing up,” she says. “To show up” is a two-word phrasal verb meaning to arrive, to appear, to come to a particular event or place: “What time did your brother show up last night?” You were waiting for him, he was late, he didn’t show up until 8:00. Kyoko says, “I don’t want to seem like I’m spying on my own house.” “To spy on (something)” means to look at it in secret, to get information.
Ernie says, “What does it matter (what difference does it make)? Hand me the fact sheet for our house.” “Hand me” means give me – put in my hand – the fact sheet. A “fact sheet” is a piece of paper with detailed information about something; it could be about anything. For a house, the fact sheet would have the price, how big the house is, and so forth. Ernie says, “I want to read it through (meaning I want to read it completely) again to make sure the agent didn’t miss anything. Okay, the square footage on the house and the lot are correct.” The “square footage” is the number of square feet in a particular area; it’s a way of measuring the size of a house. The “lot” (lot) is the land that the house sits on, or the building sits on. “Lot” has a couple of other meanings; take a look at the Learning Guide for some additional definitions.
Then Ernie says that the real estate agent noted, or put on the paper, that our addition is permitted, and she mentioned the upgrades. An “addition” to a house is a new part of the house that was built after the original house. The word “addition” has some additional definitions; once again, the Learning Guide will help you. When we say that a part of the house or a building is “permitted,” we mean that it has all the necessary permissions and government documents. If you decide you want to add a new room to your house, you need to get permission from the city, and the city comes and looks at it to make sure that what you built is safe. This is part of getting something permitted. Many people, at least here in Los Angeles, because it’s so expensive to get a government permit – a government approval – will add things to their house without getting approval from the government. Of course, if the government finds out, they’ll have to pay for the permit; but usually the government is too busy trying to do other things, like spend our money! Ernie said that the real estate agent mentioned the upgrades. An “upgrade” is an improvement to something. For a home, usually it’s making the home better, perhaps by putting in a nicer kitchen, putting in a nicer refrigerator. These would be upgrades. Changing the carpet, that would be also a minor upgrade; more cosmetic than anything else, but still, it makes the house nicer.
Well, Kyoko says that she doesn’t want to sit in the car for the next four hours during the open house. She says, “Let’s go to visit our neighbors’ open houses.” Ernie says, “Good idea. We’ll see what our competition is and maybe we can steal some of their open house ideas!” So, Ernie and Kyoko are going to look at other open houses, just like I mentioned earlier people often do, to see if they can get some ideas about selling their house.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Kyoko: We’re not supposed to be here. I think we should leave and let our real estate agent hold the open house without us looking over her shoulder.
Ernie: We’re not looking over her shoulder. I just want to sit in this car to see how many people go in and out.
Kyoko: You know, there’ll be a lot of lookie-loos. And plus, there’ll be a sign-in sheet, so we’ll be able to see afterwards how many people stopped in.
Ernie: Hey, someone’s coming in now.
Kyoko: That’s the stager. She’s making some last-minute changes.
Ernie: She really doesn’t need to do anything else. We did everything our agent told us to do. We made cosmetic repairs, painted, and de-cluttered. What more could they ask for?
Kyoko: She’s just doing some minor landscaping, putting some plants along the front path and around the front door. Let’s get out of here before people start showing up. I don’t want to seem like I’m spying on my own house.
Ernie: What does it matter? Hand me the fact sheet for our house. I want to read it through again to make sure the agent didn’t miss anything. Okay, the square footage on the house and the lot are correct, she noted that our addition is permitted, and she mentioned the upgrades – good. Where are you going?
Kyoko: I’m not going to sit in this car for the next four hours. Let’s go to visit our neighbors’ open houses.
Ernie: Good idea. We’ll see what our competition is and maybe we can steal some of their open house ideas!
[end of dialogue]
There’s no need for the boss to look over the shoulder of the writer of this script. It’s by Dr. Lucy Tse, so you know it’s going to be good!
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
real estate agent – a person whose job is to help other people buy and sell homes, buildings, and land
* We gave our real estate agent a list of the three most important things we’re looking for in a new home: a short distance to work, three large bedrooms, and a big backyard for the kids to play in.
open house – an event where people can come into a home that is for sale to walk through it, learn about it, and decide whether they would like to buy it
* They’ve had an open house every Sunday for the past month, but they haven’t found a buyer yet.
to look over (one’s) shoulder – to closely watch another person’s work; to pay careful attention to what another person is doing, especially when that person doesn’t want to be watched
* Please stop looking over my shoulder! I work much better when I’m left alone.
lookie-loo – a person who wants to see what is happening, especially when he or she doesn’t really need to see it
* Whenever there’s an accident, traffic slows down because of all the lookie-loos who slow down to get a better view as they drive by.
sign-in sheet – a piece of paper where every attendee or participant writes his or her name and/or contact information, so that there is a record of who was there
* Please put your name, email address, and telephone number on the sign-in sheet when you come into the conference room.
stager – a person whose job is to make a home look its best so that it can be sold more easily
* The stager took down all their family photographs and hung landscape paintings instead.
cosmetic repair – something that improves the appearance of a house or building without actually making it stronger or safer
* They spent all their money on cosmetic repairs, fixing the cabinets and painting the walls, but they really need to fix the roof and the fireplace.
to de-clutter – to reduce the number of things that are visible in a room; to put things away; to clear the surfaces of tables and counters
* This house would look so much better if you de-cluttered it, hiding all the toys, dishes, magazines, pictures, and other small things.
landscaping – the combination of plants, flowers, trees, grass, and rocks used to make a garden or yard beautiful
* Which city parks have the best landscaping?
to show up – to appear; to arrive; to come to a particular event or place
* What time did your parents show up at the house?
fact sheet – a piece of paper with detailed information about something
* According to this fact sheet, the museum was built in 1924 and has about 4,000 visitors each day.
square footage – the number of square feet in a particular area; the size of a building or a piece of land
* I hope our next house has less square footage because I’m tired of cleaning so much space!
lot – the land that a building sits on; the land owned by a homeowner or building owner
* They’ve decided to buy an empty lot and then build their own home on it.
addition – a section of a home or other building that has been added to the original structure
* They’re saving money for an addition because they want two more bedrooms and an extra bathroom for their growing family.
permitted – with all the necessary permits, permission, and documentation; having followed all the laws, rules, and regulations
* My construction crew only works on permitted projects.
upgrade – an improvement in a home, usually replacing an old appliance with a newer appliance, or installing a very nice and expensive countertop or light fixtures
* Francine paid extra for all the upgrades, including a marble bathtub and granite countertops.
Comprehension Questions
1. Why are they having an open house?
a) To welcome friends and family into their new home.
b) To try to find buyers for their home.
c) To see how many people fit inside the house.
2. According to Ernie, what information is included on the fact sheet?
a) The size of the house.
b) The number of bedrooms.
c) The shape of the floors.
Answers at bottom.
What Else Does It Mean?
lot
The word “lot,” in this podcast, means the land that a building sits on and is owned by a homeowner: “Their home is on a beautiful lot right next to the river.” A “lot” can also be any area of land used for a specific purpose: “Do you remember where we parked in the parking lot?” A “lot” is also a large number of people or things: “This store has a lot of nice sweaters.” The phrase “(one’s) lot in life” is used to describe one’s situation, especially when one is dissatisfied with it and wishes it could be better: “She’s unhappy with her lot in life as a salesperson, because she always dreamed of being a dentist.” Finally, a “lot” is a group of things that are sold together, especially at an auction: “Which lots are you bidding on?”
addition
In this podcast, the word “addition” means a section of a home or other building that has been added to the original structure: “It used to be a really small home, but over the years, each owner has made a new addition, and now it’s quite large.” An “addition” is something that is added to something else to make it better: “These DVDs will be a great addition to our movie collection.” In mathematics, “addition” is the process of finding the sum: “Let’s practice with some addition problems. What’s 6,482 + 461?” The phrase “in addition to” is used to provide extra information about something: “In addition to learning how to swim, Rafaella learned how to play baseball in the school’s summer program.”
Culture Note
A real estate agent has many responsibilities, although they “vary” (are different) “slightly” (a little bit), depending on whether the agent is a “buyer’s agent” (a real estate agent helping someone buy a home) or a “seller’s agent” (a real estate agent helping someone sell a home).
The buyer’s agent “is supposed to” (should) interview clients to find out what they’re looking for in a new home and then study the “property listings” (information about homes that are for sale) to find a good “match” (something that meets the client’s needs). The buyer’s agent then “sets up” (schedules) appointments when the clients can view the home, and drives the buyer(s) to the homes.
The seller’s agent is supposed to help the homeowner understand the “market value” (the amount that something can be sold for) of his or her home and provide suggestions on how to “stage” the home, making it look its best. The seller’s agent organizes open houses, inviting other real estate agents to view the home, and “markets” (promotes) the home to “prospective” (potential, possible) buyers.
Real estate agents are also responsible for helping buyers write “offers” (written statements indicating how much one is willing to pay for a home) and helping sellers understand and respond to the offers. Agents assist their clients throughout the “negotiation process,” or the period of time when buyers and sellers try to reach an agreement. Agents also “draft” (write; put in writing) real estate contracts and “accompany” (be with; go with) their clients when the “paperwork” (necessary documents) is signed.
Of course, real estate agents have many other job responsibilities, but the ones described above are the “main” (primary; most important) ones.
Comprehension Answers
1 - b
2 - a