= 0504
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 504: Training Inexperienced Employees.
This is English as a Second Language Podcast number 504. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode, an 8- to 10-page guide that will help you improve your English even faster.
This episode is called “Training Inexperienced Employees.” It’s a dialogue between Kazuko and Martin using a lot of vocabulary that relates to experience or “inexperience” (someone without experience) at work. Let’s get started.
[start of dialogue]
Kazuko: I really appreciate you helping with the training of the newbies. I couldn’t have done it without you.
Martin: Don’t mention it. I remember when I was still wet behind the ears and the veterans in the company gave me the benefit of their time and expertise. They propped me up until I could stand on my own two feet.
Kazuko: I can’t imagine you as a novice. Everybody here thinks of you as the cornerstone of the institution.
Martin: Well, that may be, but you should have seen me in the early years. I was na?ve and reckless. I may be more adept at my job now, but I felt inept for years.
Kazuko: I saw you talking with some of the new recruits. What advice did you give them?
Martin: I gave them the same advice that an old hand gave me when I first started: Take every piece of advice you get with a grain of salt!
[end of dialogue]
Kazuko begins by telling Martin that she really appreciates him helping with the training of the newbies. A “newbie” (newbie) is an informal term used to describe someone who’s a beginner, someone who’s a novice, someone who is new at something. Kazuko says, “I couldn’t have done it without you.” Martin says, “Don’t mention it,” meaning not at all, not a problem. “I remember when I was still wet behind the ears and the veterans in the company gave me the benefit of their time and expertise.” The expression “to be wet behind the ears” means to be inexperienced, to be doing something for the first time, not to know exactly what you’re doing. I’m not sure where the expression comes from, but it’s a common enough one. When you say someone is “wet behind the ears,” you mean they don’t know what they’re doing, they’re new at something, they’re inexperienced. A “veteran,” here, means someone who has a lot of experience, someone who has done something for a long time. A veteran teacher is someone who has been a teacher for long time. The word “veteran” can also describe someone who was once part of a country’s army or military forces, but here it just means someone with a lot of experience.
The veterans in the company gave Martin “the benefit of” (the advantages of) their time and “expertise,” meaning their knowledge about something – their deep knowledge, their considerable understanding about something. He says, “They propped me up until I could stand on my own two feet.” “To prop up (something)” or “to prop (something or someone) up” is a phrasal verb meaning to support someone or something, to help someone do something – to accomplish something. So, in this case, because Martin didn’t have very much experience, he needed help; he needed other people to help him do what he needed to do, and they propped him up until he could stand on his own two feet. “To stand on your own two feet” means to be independent, to do something without help from other people.
Kazuko says, “I can’t imagine you as a novice.” A “novice” (novice) is a newbie, someone who is doing something for the first time, or someone who doesn’t have very much experience. If you were beginning to learn the piano, for example, you could say, “I’m a novice (I’m not very good, I’m a beginner).” Well, Kazuko says she can’t imagine Martin as a novice, “Everybody here thinks of you as the cornerstone of the institution.” The “cornerstone” is, in this case, someone or something that is necessary for the success of a project or a company; something that is absolutely vital, important, something you could not do without. The word “cornerstone” comes from architecture. It’s the actual piece of stone that you would put in the corner of a building, where the two walls would meet. More generally, “cornerstone” is the part of the building that is often dedicated at the beginning of the construction of an important building. When used normally in conversation, it means the foundation, the thing that is very necessary or important.
Martin says, “Well, that may be (I may be thought of as the cornerstone of this institution), but you should have seen me in my early years. I was na?ve and reckless.” “Na?ve” (na?ve) means that you don’t have a lot of experience in life, so you have to trust other people. Na?ve is usually considered a bad thing; it’s when you trust other people too much and you believe things that you shouldn’t believe. For example, if your new girlfriend tells you that she’s going to have dinner with her ex-boyfriend because they’re just friends, you might not want to be so na?ve as to think that perhaps there isn’t something else going on there. That would be an example of being na?ve, perhaps. The same would be especially so if it happened with your boyfriend. If your new boyfriend says they’re going to have dinner with their ex-girlfriend, you should probably maybe go with! “To be reckless” means to things that are risky, without thinking about the danger involved. We have an expression “reckless driving,” that’s when people drive their cars without any concern about how dangerous driving can be, and, for example, they may hit another car or hurt people. That is reckless driving, driving in a way that could cause an accident or does cause an accident.
Martin says, “I may be more adept at my job now, but I felt inept for years.” We have two words here that end in “ept”: “adept” (adept) and “inept” (inept). “To be adept” means to be able to do something easily, quickly, and well. “My mother is adept at cooking (she can cook very well).” That’s just an example, however! “Inept” means incapable, unable to do something, without the ability to do something well. “I am inept at playing the violin (I’m not very good at it).” Notice that both with “adept” and with “inept” we use the preposition “at”: “I am adept at making cakes.” The verb is in the “ing” after the “at.” “I am inept at driving” – “ing” form.
Kazuko says, “I saw you talking with some of the new recruits. What advice did you give them?” A “recruit” is someone who has recently joined an organization. We usually talk about “recruits” as new employees, often people that we try to go and find and hire. The army, the navy, the military forces also have recruits; these are people that they want to get to join the army and then join the military service.
Kazuko asks what advice Martin gave the new recruits. Martin says, “I gave them the same advice as an old hand gave me when I first started.” The expression “an old hand” means a person who has a lot of experience doing something, someone who knows how to do something very well. “Hand” has several different meanings in English; take a look at our Learning Guide for some additional explanations. Martin says, “I gave them the same advice that an old hand gave me when I first started: Take every piece of advice you get with a grain of salt!” “To take (something) with a grain of salt” is an old expression that means not to believe everything that you are told, to decide which things you are going to believe. Of course, Martin is giving this as a piece of advice, that the recruits take advice from people like him with a grain of salt. Of course, if we take his advice about taking advice with a grain of salt, well, you see the problem – we’re not sure what to believe!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Kazuko: I really appreciate you helping with the training of the newbies. I couldn’t have done it without you.
Martin: Don’t mention it. I remember when I was still wet behind the ears and the veterans in the company gave me the benefit of their time and expertise. They propped me up until I could stand on my own two feet.
Kazuko: I can’t imagine you as a novice. Everybody here thinks of you as the cornerstone of the institution.
Martin: Well, that may be, but you should have seen me in the early years. I was na?ve and reckless. I may be more adept at my job now, but I felt inept for years.
Kazuko: I saw you talking with some of the new recruits. What advice did you give them?
Martin: I gave them the same advice that an old hand gave me when I first started: Take every piece of advice you get with a grain of salt!
[end of dialogue]
The script for this episode was written by someone who’s very adept at writing, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
newbie – informal term for novice; someone who is doing something for the first time; someone who is new and inexperienced in a particular position or task
* I always try to avoid the newbies at the grocery store, because it takes them a long time to complete a transaction when they’re still learning to use the cash register.
wet behind the ears – inexperienced; doing something for the first time
* Are you trying to hire someone who has a lot of experience, or someone who’s still wet behind the ears?
veteran – someone who has a lot of experience doing something
* Don’t worry, Marcus can help us. He’s a veteran at solving these kinds of problems.
expertise – having deep knowledge about something; having special and deep understanding about a specific thing or area of study
* Which professor has the most expertise in quantum physics?
to prop (someone or something) up – to support someone or something; to help someone or do something, or to help something happen
* His parents’ love props him up in difficult times.
to stand on (one’s) own two feet – to be independent; to do something on one’s own, without help from other people
* Rachel is very proud that she has a job and can pay for her living expenses. She’s finally standing on her own two feet.
novice – newbie; someone who is doing something for the first time; someone who is new and inexperienced in a particular position or task
* Many novice tennis players make the same mistake, trying to hit the ball too hard.
cornerstone – someone or something that is necessary for the success of a project or organization
* Good customer service is the cornerstone of our business’s success.
na?ve – without very much experience in life, so that one trusts other people or believes what other people say too easily
* I can’t believe you were so na?ve that you believed that email and wrote a check to that person. You’ll never see your money again!
reckless – doing things that are risky, without thinking about the bad or dangerous things that might happen as a result
* The students watched an instructional film in school and learned that driving while drunk is reckless. They might hurt or kill other people, or themselves.
adept – able to do something quickly, easily, and well
* Ophelia is adept at baking desserts, but she isn’t very good at cooking meals.
inept – incapable; unable to do something; without the ability to do something well
* Dean is so inept at driving that few of his friends will ride in a car with him.
recruit – a person who has recently joined an organization or workplace
* We plan to hire 20 new recruits this fall.
old hand – a person who has a lot of experience doing something and knows how to do it very well
* He’s an old hand at fishing.
to take (something) with a grain of salt – to not believe everything that one is told; to decide which parts of something to believe; to know that something isn’t completely true
* Jackie has good intentions, but take what he says with a grain of salt, because sometimes he doesn’t really know what he’s talking about.
Comprehension Questions
1. Which of these people would be wet behind the ears?
a) A newbie.
b) A veteran.
c) An old hand.
2. Which of these people would have the most expertise?
a) Someone who is adept.
b) Someone who is a new recruit.
c) Someone who is inept.
Answers at bottom.
What Else Does It Mean?
to prop (someone) up
The phrase “to prop (someone or something) up,” in this podcast, means to support or help someone or something: “Sales of our product have been propped up by the strong economy.” The verb “to prop” normally means to lean something next to something else for support: “Why don’t you prop your bike against the tree, instead of dropping it on the ground?” The phrase “to prop up the economy” means for the government to do things to improve economic growth: “The government is spending a lot of money on infrastructure projects to prop up the economy.” In the theater, a “prop” is a small object used or held by actors: “This scene requires three props: a tall glass, a boot, and a letter.”
old hand
In this podcast, the phrase “old hand” means a person who has a lot of experience doing something and knows how to do it very well: “After 30 years of working at the grocery store, he’s an old hand at helping customers find what they’re looking for.” The phrase “to be (someone’s) right-hand man” means to be very helpful to that person: “In Star Trek, Mr. Spock is Captain Kirk’s right-hand man.” The phrase “To have (someone) in the palm of (one’s) hand” means to control what another person does: “He’s so in love with you that you have him in the palm of your hand and he’ll do anything you ask him to do.” Finally, the phrase “to give (someone) a hand” means to help someone do something: “Could you please give me a hand with these heavy boxes?”
Culture Note
Most American schools and university have a “tenure system” where teachers who have taught at a particular school or university for a long time have more “tenure” than teachers who are new to that school or university. If the school or university needs to “lay off” (fire) staff, possibly due to “budget cuts” (having less money than expected) then it will lay off teachers with little or no tenure. People with more tenure know that their jobs are safe.
Some people argue that having a tenure system is very important, especially at a university, because it protects professors who might be involved in unpopular research. If they have tenure, they cannot be fired simply for “conducting” (doing; performing) researching that makes people angry or uncomfortable.
Many other people believe that tenure systems are unfair, because they don’t consider whether or not someone is a good teacher. Sometimes people who have been teaching for many years have “antiquated” (old; no longer relevant) teaching “techniques” (ways of doing something) and “outdated” (not current) knowledge about their “subject area” (the topics that are taught), or they might be “burnt out” (no longer interested and enthusiastic) about teaching. In contrast, new teachers might be better educated and more interesting for the students. However, under a tenure system, the new teachers will be fired before the old teachers lose their jobs.
Even if teachers are “incompetent” (unable to do their jobs well), sometimes it can be very difficult to fire them in a school or university with a strong tenure system. On the other hand, schools use tenure to improve schools, first as a reward for teachers who have passed through a “probationary” (temporary trial) period, and then for those who remain at a school for long periods of time, thereby reducing “turnover” (people leaving a job only after a short time).
Comprehension Answers
1 - a
2 - a