= 0506
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 506: Being Generous and Stingy.
This is English as a Second Language Podcast episode 506. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode, an 8- to 10-page guide that we provide for all of our current episodes that gives you some additional help in improving your English.
This episode is called “Being Generous and Stingy.” It’s a dialogue between Britney and Salvador using a lot of vocabulary describing how people use their money. Let’s get started.
[start of dialogue]
Britney: I was thinking of hitting up Jane for a little loan. You know her better than I do. What are the chances she’ll spot me a couple hundred dollars until next month?
Salvador: I think that’s a pipe dream. I wouldn’t exactly call her a cheapskate, but she’s not known for her generosity.
Britney: What about Francke? He’s rolling in it. He could easily part with a couple hundred bucks without giving it a second thought.
Salvador: You’ve got your work cut out for you if you think you can borrow money from Francke. He’s always been a penny-pincher and he always will be.
Britney: Okay, then help me think. Who do we know who isn’t stingy? Who do we know who is big-hearted and charitable?
Salvador: What the heck. Here’s $150 to tide you over until your next payday.
Britney: Wow, thanks! You know, another $100 would really come in handy.
Salvador: I really think you should quit while you’re ahead.
[end of dialogue]
Our dialogue begins with Britney saying, “I was thinking of hitting up Jane for a little loan.” The verb “to hit up (someone)” or “to hit (someone) up” is a two-word phrasal verb meaning to ask someone for money. It’s an informal expression to ask someone to give you something for free. “I need to hit up my brother for 20 dollars” means I need to ask my brother for 20 dollars – I’m sure he’ll say no! “To hit” plus a preposition, in this case “to hit up,” is a common construction in English. Take a look at our Learning Guide for this episode to get some additional phrasal verbs using the verb “hit.”
Britney says, “You know her better than I do. What are the chances she’ll spot me a couple hundred dollars until next month?” “To spot (someone)” is another informal expression meaning to make a loan to someone, to give money to someone expecting that person will pay you back – will give you the money back eventually. I may say to my sister, “Spot me 10 dollars,” meaning loan 10 dollars to me. Or I could say, “My sister spotted me 10 dollars.” She wouldn’t, of course, any more than my brother would – they know me too well!
Britney wants Jane to spot her a couple hundred (or a couple of hundred) dollars. Salvador says, “that’s a pipe dream.” A “pipe dream” is something that you would like to happen; it’s a dream but it’s impossible, or it is very unlikely: “I would like to win the Nobel Peace Prize.” I would like to, but it is very unlikely; that’s a pipe dream. Salvador, describing Jane, says, “I wouldn’t exactly call her a cheapskate, but she’s not known for her generosity.” A “cheapskate” (cheapskate – one word) is a person who doesn’t like to spend very much money, who spends as little money as possible. It’s an informal expression. It’s an insult to call someone a “cheapskate.” Another expression we use is a “penny-pincher,” a “penny” being one cent (1￠) in American money – in American currency. Salvador says Jane’s not known for her generosity. “Generosity” is your willingness to give money to other people, or to give your time to other people to help other people. “Generosity” is the noun; the adjective is “generous.” “To be generous” means to be giving, to give things to other people.
Britney then asks, “What about Francke? He’s rolling in it.” The expression “to be rolling in it” is informal; it means to have a lot of money, to be very rich. I am not rolling in it – trust me! “He could easily part with a couple hundred dollars without giving it a second thought.” “To part with” is a two-word verb meaning to give something away or to sell something, to be separated from something that you own, especially if you really want to keep it. If you lose your job and you don’t have any money, you may have to part with your car – you may have to sell your car. You don’t want to, but you need to. So, “to part with (something)” is to give something or sell something that you would prefer not to. Britney says that Francke could part with (could give away) a couple of hundred dollars without giving it a second thought. The expression “without giving it a second thought” means without worrying about it, without spending any time thinking about it. He wouldn’t have to think about it twice is the idea; it would be an easy decision for him.
Salvador says, “You’ve got your work cut out for you if you think you can borrow money from Francke.” “To have your work cut out for you” means that you have a lot of work to do; that you have a very difficult situation here, and you are going to have to work very hard to get what you want. If I decided I wanted to be governor of California, I would have my work cut out for me. I don’t want to be governor, fortunately! Salvador says to Britney, “Francke has always been a penny-pincher and he always will be.” A “penny-pincher,” remember, is the same as a cheapskate, someone who doesn’t give away money, who spends as little money as possible.
Britney says, “Okay, then help me think. Who do we know who isn’t stingy?” “Stingy” (stingy) is the opposite of generous; it’s like cheapskate. It’s an insulting thing to say about someone, that they’re stingy. They don’t like to share things, especially their money. Britney says, “Who do we know who is big-hearted and charitable?” “To be big-hearted” means to be generous, always wanting to help other people. “To be charitable” is similar; it means to be generous, to share your time, your goods (what you own), your money with people that need that time or money. That is to be charitable.
Salvador says, “What the heck.” “What the heck” is an expression meaning that you will go ahead and do something even though you don’t really want to or probably shouldn’t, but because another person wants you to do something you do it. In this case, Salvador is going to give Britney the money that she is looking for, that’s why he says, “What the heck.” “What the heck” can also be used as a way of expressing surprise, or anger, or even disappointment. “What the heck are you doing?” a mother may say to her son who is making a mess – who’s making the house dirty: “What the heck are you doing?” “Heck,” here, could be seen as taking the place of a stronger word, a swear word (a curse word) like “hell” (hell). But here, in Salvador’s case, he says, “ What the heck” to mean okay, I’m going to do something to help you. He says, “Here’s $150 to tide you over until your next payday.” “To tide (someone) over” means to help someone for a short period of time, often by giving them money. Let’s say I need 50 dollars right now; I will be paid by my job next week, so I ask someone for 50 dollars to tide me over – not my brother or sister, however!
Salvador says he’s going to help Britney until her next payday. “Payday” is the day that you are paid for your work from your job; sometimes once a week, sometimes every two weeks, sometimes people get paid once a month. Britney says, “Wow, thanks! You know, another $100 would really come in handy.” Britney is asking now for another hundred dollars from Salvador, she says it would really come in handy (handy). “To come in handy” means to be useful, to be helpful.
Salvador says, “I really think you should quit while you’re ahead.” The expression “to quit while you’re ahead” means to stop doing something at the point you become successful, not to try to continue to get more of something. In this case, Salvador is already lending Britney 150 dollars, she should stop asking for more; she should quit while she’s ahead. She’s already gained something, which is what it means to be ahead in this case, so she should stop there, not ask for more money.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Britney: I was thinking of hitting up Jane for a little loan. You know her better than I do. What are the chances she’ll spot me a couple hundred dollars until next month?
Salvador: I think that’s a pipe dream. I wouldn’t exactly call her a cheapskate, but she’s not known for her generosity.
Britney: What about Francke? He’s rolling in it. He could easily part with a couple hundred bucks without giving it a second thought.
Salvador: You’ve got your work cut out for you if you think you can borrow money from Francke. He’s always been a penny-pincher and he always will be.
Britney: Okay, then help me think. Who do we know who isn’t stingy? Who do we know who is big-hearted and charitable?
Salvador: What the heck. Here’s $150 to tide you over until your next payday.
Britney: Wow, thanks! You know, another $100 would really come in handy.
Salvador: I really think you should quit while you’re ahead.
[end of dialogue]
The script for this episode was written by someone who’s always generous with her time and talent, Dr. Lucy Tse.
If you’d like to be generous to ESL Podcast, you can help support us by sending a donation or by becoming a Learning Guide member. Go to our website, eslpod.com, for more information.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
to hit (someone) up – to ask someone for money; to ask someone to give you something for free
* Billy hit up all the neighbors, asking them to donate money for his baseball team.
to spot (someone) – to make a loan to someone; to give money to someone for a short period of time, expecting that person to pay one back
* Can you spot me $20? I’ll pay you back next week.
pipe dream – something that one would like to have happen, but is impossible or extremely unlikely
* He wants to be a millionaire by the time he’s 30, but it’s just a pipe dream.
cheapskate – a penny-pincher; a person who spends as little money as possible, preferring to save everything; a person who won’t give money away to help other people
* Mariah is such a cheapskate! She won’t buy new clothes for her children even when their clothes have holes in them!
generosity – one’s willingness to give money, time, and other things to help other people
* The children showed a lot of generosity when they collected money to help pay for their classmate’s medical bills.
to be rolling in it – to have a lot of money; to be very rich
* They’ve been rolling in it ever since they won the lottery.
to part with – to give something away or sell something; to be separated from something that one owns, especially when one would rather keep it
* I’d have to be pretty desperate for money before I’d consider parting with my guitar.
without giving it a second thought – without worrying about something; without spending time thinking about something
* Phil writes thousand-dollar checks without giving it a second thought.
to have [got] (one’s) work cut out for you – with a lot of work to do; having a lot of things that one needs to do, with a difficult project or task
* You’ve got your work cut out for you, trying to raise three children as a single parent.
penny-pincher – a cheapskate; a person who spends as little money as possible, preferring to save everything; a person who won’t give money away to help other people
* Jin is a penny-pincher who uses coupons, hangs wet clothes outside to dry, and never buys anything new.
stingy – not generous; not liking to share things, especially money; not liking to spend money
* It seems like people become stingier when the economy is bad.
big-hearted – generous; always wanting to help other people
* Krzystof is very big-hearted, often opening his home to people who need a place to stay, even if he doesn’t know them very well.
charitable – generous; sharing money, goods, and time with people and organizations that need it
* The Richardsons are very charitable, always donating 10% of the money they make to local organizations.
what the heck – an expression meaning that one will do something, even though one doesn’t really want to or probably shouldn’t, because another person wants one to do it
* I’m supposed to be on a diet, but what the heck. Sure, I’ll help you eat your birthday cake.
to tide (one) over – to help a person, usually for a short period of time, until something else happens
* Gretchen needs an afternoon snack to tide her over until dinner.
payday – the day when one is paid for one’s work, usually once a week or once every two weeks
* Her payday is the 15th of every month.
to come in handy – to be useful or helpful
* Knowing a few words in another language comes in handy when you’re traveling.
to quit while (one) is ahead – to stop doing something while one is successful, not trying to continue to get more of something or to do something better
* Jothio made a lot of money while playing cards, so she decided to quit while she was ahead and not risk losing it all.
Comprehension Questions
1. Which of these people is the most generous?
a) Someone who is a cheapskate.
b) Someone who is a penny-pincher.
c) Someone who is big-hearted.
2. What does Salvador mean when he tells Britney to quit while she’s ahead?
a) She should quit her job and find something that pays better.
b) She should quit asking him for more money.
c) She should quit talking so much.
Answers at bottom.
What Else Does It Mean?
to hit up
The phrase “to hit (someone) up,” in this podcast, means to ask someone for money: “It’s very unprofessional to hit your co-workers up for money.” The phrase “to hit on (someone)” means to say something that lets a person know that one is interested in him or her sexually or romantically: “Sheila hates going to bars where men hit on her.” The phrase “to hit it off” means for two people to instantly like each other when they meet: “You and Jaime have a lot of things in common. I think you’re going to hit it off when you meet each other at the party.” Finally, the phrase “to hit the spot” means to be satisfying, or to do what one intended something to do: “Craig was really thirsty and that glass of orange juice really hit the spot.”
to part with
In this podcast, the phrase “to part with” means to give something away or sell something, or to be separated from something one owns: “Yoshi won’t part with his car for less than $8,000.” The phrase “to be parted from (someone)” means to be separated or away from someone: “She hates traveling for business, because it means being parted from her husband and children.” The verb “to part” means for two things to move away from each other, leaving space between them: “His lips parted as if he were going to say something, but then he changed his mind and stayed silent.” The phrase “to part (one’s) hair” means to comb part of one’s hair in one direction and the other part in another direction, leaving a line of skin showing between the two sections: “Have you always parted your hair on the right?”
Culture Note
One of the most famous stingy “characters” (a person in a book, show, or movie) in English “literature” (books, stories, and poems) is Ebenezer Scrooge from the “novel” (a fictional book) called A Christmas Carol, which was written by Charles Dickens in 1843. In fact, his name has “become synonymous with” (means the same as) stinginess, and you might hear people refer to another person as a scrooge, meaning that he or she doesn’t share things or help people.
In the story, Scrooge is a “wealthy” (rich) man who treats his employee very badly, not paying him enough money to “support his family” (pay for food, housing, clothing, and other things that one’s family needs). He refuses to share his money with other people, often saying “bah humbug” (an expression showing dislike or disgust) when he sees other people being generous or kind.
One of the most generous and big-hearted characters in English literature is Pollyanna, from a novel with the same name, written by Eleanor H. Porter in 1913. This story is about a young “orphan” (a child whose parents have died) who goes to live with her aunt. Although she didn’t have money to share with other people, she shares a lot of kindness with the community, giving things to people who need them and helping people find things to be “glad” (happy) about in their own lives. Today you sometimes hear Americans referring to someone as a “Pollyanna,” meaning that he or she is always happy and “optimistic” (thinking something good will happen).
Both novels have become well-known movies and a part of American culture, with most Americans having seen the characters on screen, even if they haven’t read the books.
Comprehension Answers
1 - c
2 - b