= 0516
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 516: Naming and Appointing Officials.
This is English as a Second Language Podcast number 516. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
We have a website at eslpod.com. Go there to download a Learning Guide for this episode. If you’re not a Learning Guide member, consider joining and supporting this podcast. The Learning Guide is an additional help to improve your English even faster.
This episode is a dialogue between Goran and Anne. It is about when you have official appointments in a company or in a government. When someone takes a new job – takes a new position, we have some particular vocabulary we use that will be discussed in dialogue. Let’s get started.
[start of dialogue]
Goran: Who do you think will be appointed to succeed Ramon on the board?
Anne: I don’t know whom they’ll pick to fill the position, but I know who the candidates are. The higher ups have been quietly vetting three people to make sure they don’t have any skeletons in their closets.
Goran: Really? Who are they?
Anne: I’m not at liberty to say, but I think at least two of the candidates are people outside of the inner circle.
Goran: You mean we might actually get a new board member who’s not buddy-buddy with the higher ups?
Anne: All I can say is that two outsiders are under consideration.
Goran: Wow, that’s huge. Can you at least tell me if the remaining candidate is the interim board member? Everybody thinks he has the inside track.
Anne: I can’t tell you that. The selection is being kept under wraps until next Thursday. I’ve already let slip too much.
Goran: Don’t worry. My lips are sealed.
Anne: They’d better be. You know what they say about loose lips.
Goran: Yeah, and I’m not sinking this ship.
[end of dialogue]
Our dialogue begins with Goran asking Anne, “Who do you think will be appointed to succeed Ramon on the board?” “To be appointed” means to be name or chosen, usually for some leadership position. “To succeed” can mean to be successful, but here it means to follow, the person who takes over a job or a position from another person. We often use this in talking about, for example, the president; we have certain rules in our laws about what happens if the president were to die, there is what is called “presidential succession.” It comes from this verb “to succeed” when it means to take the place of.
So, Goran is asking Anne who she thinks will be appointed (named) to succeed Ramon on the board, probably the board of directors of a company. Anne says, “I don’t know whom they’ll pick to fill the position, but I know who the candidates are.” “To fill a position,” or “to fill a job,” means to find someone to take that job, to put someone in that job. “We need to fill the position of secretary,” we need to find someone to work in that position, and when we fill it, that means we found a person. Anne says, “I know who the candidates are.” The “candidates,” here, mean the people who are being considered for a particular position. We use that word also in government. You have different presidential candidates, but you can also have candidates for a position. When I worked at the university, every year usually we would have a hiring committee, a group of people who would decide how to fill the open teaching positions we had, and we would have different candidates that we would interview.
Anne says, “The higher ups have been quietly vetting three people.” The “higher ups” refers to someone who works in management, a decision-maker, a leader. The expression is sort of informal, but you will hear it in business context sometimes. “Vetting” means to talk to different people, look at their information, and decide who is really the perfect person for this job, who has the qualifications for this job, and who is not qualified. “To vet” is the verb (vet). Once again, we use this sometimes in government. When the president appoints important members of his government, there is someone who does the vetting – someone who looks into the background, usually to make sure that there isn’t anything bad in their past that would cause a problem.
So, Anne says, “The higher ups have been quietly vetting three people to make sure they don’t have any skeletons in their closets.” This is what I was just talking about. The expression “skeletons in their closets” refers to secrets about their past that might be damaging or embarrassing, things that would make them unqualified to take the job or position. So for example, if you go and rob a bank and spend five years in prison and then you apply for a job, if they investigate your past – your background, they will find a skeleton in your closet, meaning they will find something that is negative about your background. The word “skeleton” refers to a human being’s bones without anything else on them, or not considering anything else. If you had a skeleton in your closet, you probably killed someone and then hid them in your closet, which I don’t recommend – you should bury them somewhere else!
Goran says, “Who are they?” Anne says, “I’m not at liberty to say.” When you say “I’m not at liberty to say,” you’re saying I can’t tell you, I’m not able to tell you, I’m not free to tell you. It’s a somewhat formal expression. Anne continues, “but I think at least two of the candidates are people outside of the inner circle.” The expression “inner circle” refers to a small group of people who work together or who have the same information about something. What Anne is saying here is that two of the people they are considering for the position aren’t people who are currently working at the company or currently at a leadership position in the company, among those who are in the inner circle – the group of leaders, most probably.
Goran says, “You mean we might actually get a new board member who’s not buddy-buddy with the higher ups?” “To be buddy-buddy” (buddy) means to be a close, personal friend of someone, to have a very close relationship with someone. It’s sometimes used in a negative way to say “Oh, well. He’s buddy-buddy with the boss, so the boss likes him a lot.” That would mean he’s very friendly with the boss, but not in a way that I really like, or perhaps I’m a little jealous of him. Goran obviously thinks that somebody who is buddy-buddy with the higher ups is not the best person for the job.
Anne says, “All I can say is that two outsiders are under consideration,” meaning they’re being considered, they’re being discussed, they’re a possibility. Goran says, “Wow, that’s huge.” “That’s huge” is an informal expression meaning that it is very important, or it could be very important. It’s an expression that has become more popular in the last, probably, 10 or 15 years. “Wow, that’s huge.” Goran says, “Can you at least tell me if the remaining candidate is the interim board member?” If you are “interim” (interim), you are temporarily in a position; you are in a position, but you are not necessarily going to stay there. So, if your president of your company resigns, they may appoint an interim president until they have a chance to find the perfect person. So, they will put someone there who they know won’t be there for very long, or at least has to apply for the job formally and be interviewed and vetted just like any other candidate.
Here, Goran is referring to an interim board member. “Everybody thinks he has the inside track.” “To have the inside track” is to have an advantage in getting a job, usually because you know somebody in the company. If I was interviewing at the university and I was friends with one of the professors there, I might have an inside track, meaning I have an advantage over all the other candidates because I have this relationship already with one of the professors.
Anne says, “I can’t tell you that. The selection is being kept under wraps until next Thursday.” “To keep (something) under wraps” (wraps) means to keep it secret, not to tell other people about it. Anne says, “I’ve already let slip too much.” “To let (something) slip” (slip), or “to let slip (something),” would mean to accidentally share a secret, to tell someone something that you didn’t mean to tell them, something that is secret that you weren’t supposed to tell them. The word “slip” has a couple of different meanings in English, as does the word “fill” that we talked about earlier. For both of those, take a look at our Learning Guide for some additional explanations.
Goran says, “Don’t worry. My lips are sealed.” Your “lips” are the opening to your mouth; on the front of your face you have an upper lip and a lower lip. “To seal (something)” means to close it, so when someone says, “my lips are sealed,” they mean I will not open my mouth, I will not tell anyone.
Anne says, “They’d better be,” meaning you better not tell anyone. “You know what they say about loose lips.” The expression “loose lips” refers to people who talk too much, who tell people secrets. There’s an old expression: “Loose lips sink ships.” “To sink” means to, in this case, take a ship or a boat and make it go down into the water, which, of course, is not want you want your boat or ship to do. I believe the expression comes from World War I. When you said “loose lips sink ships” back then, the idea was that you shouldn’t tell anyone, if you are working in the military for example, what the plans are or anything about military secrets, because there could be other people who are your enemies (spies) listening, and that could hurt people who are on those ships. Of course, that would happen in a war. The enemy would find out where your ship is because you were telling secrets, and that could give them the opportunity to sink the ship.
So, Anne says, “You know what they say (you know the expression) about loose lips.” Goran says, “Yeah, and I’m not sinking this ship,” I’m not going to damage anything or hurt anything by telling anyone anything that I know.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Goran: Who do you think will be appointed to succeed Ramon on the board?
Anne: I don’t know whom they’ll pick to fill the position, but I know who the candidates are. The higher ups have been quietly vetting three people to make sure they don’t have any skeletons in their closets.
Goran: Really? Who are they?
Anne: I’m not at liberty to say, but I think at least two of the candidates are people outside of the inner circle.
Goran: You mean we might actually get a new board member who’s not buddy-buddy with the higher ups?
Anne: All I can say is that two outsiders are under consideration.
Goran: Wow, that’s huge. Can you at least tell me if the remaining candidate is the interim board member? Everybody thinks he has the inside track.
Anne: I can’t tell you that. The selection is being kept under wraps until next Thursday. I’ve already let slip too much.
Goran: Don’t worry. My lips are sealed.
Anne: They’d better be. You know what they say about loose lips.
Goran: Yeah, and I’m not sinking this ship.
[end of dialogue]
I’m pretty sure our scriptwriter doesn’t have any skeletons in her closet, that’s because it’s Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
appointed – named or chosen for a particular position by someone with a higher position and/or political power
* U.S. Supreme Court judges are appointed by the President, not elected by voters.
to succeed – to follow; to work in a particular position after someone else has done it
* Raymond has been the chairman for more than 15 years, and nobody knows who will succeed him when he finally retires.
to fill – to be in a particular position; to occupy a position or job; to have a particular position
* They’re looking for someone to fill this sales position for two weeks, but they can’t find anyone suitable.
candidate – a person who is being considered for a particular position; someone who may be hired or chosen for a particular job
* They received 75 applications for the job, but chose to interview only three candidates.
higher-up – someone who works in management; a decision-maker with a lot of power in an organization
* The CEO and the other higher-ups are having a meeting at 3:00 today to discuss the company’s new strategy.
to vet – to review someone or something in detail, especially to make sure that a person really has the qualifications for a particular position and no harmful secrets
* The Human Resources Manager vets each candidate, calling their past employers and reviewing their applications carefully.
skeleton in (one’s) closet – a secret about something that one has done in the past and does not want other people to know about
* Elba has a lot of skeletons in her closet, because she did a lot of unwise things when she was younger.
at liberty – free to do something; able to do something; with permission to do something
* I’m not at liberty to speak with reporters, but you can contact our Communications Director.
inner circle – a small group of people who have the same information and are working together for some purpose
* He’s worked in that company for more than 20 years, but he still isn’t part of the inner circle.
buddy-buddy – with a close, personal, friendly, and familiar relationship
* When did you become so buddy-buddy with the boss?
under consideration – being considered; a possibility
* We want to buy a house, and so far, we’ve found three that are under consideration.
that’s huge – an informal phrase meaning that something is very important or has a lot of potential to be influential
* Did you hear that James asked Karina out on a date? That’s huge! He hasn’t dated anyone since his last girlfriend broke up with him nearly three years ago.
interim – temporary; being used or serving in a particular position for a short period of time, only until something or someone permanent can be found
* Would you be willing to serve as the interim .vice-president until we can hire someone for the job?
inside track – an advantage for getting a job, usually because one has a personal relationship with the people who will make a hiring decision
* I applied for the job, but everyone knows the boss’s daughter has the inside track.
under wraps – secret; not being shared with other people; confidential
* The committee members have already made their decision, but they’re keeping it under wraps until next week.
to let (something) slip – to accidentally share a secret; to say something that one shouldn’t have said because the information shouldn’t be shared
* I accidentally let it slip that we were planning a surprise birthday party for Aunt Melina.
(one’s) lips are sealed – a phrase meaning that one will not repeat what one has heard and that the other person should feel safe and confident about having shared a secret with oneself
* At the end of our conversation, Beverly promised her lips were sealed, but then she went and told everyone my secret. I’m so mad at her!
loose lips sink ships – a phrase meaning that talking too much and sharing secret information might have bad consequences, hurting people, organizations, or projects
* During World War I, sailors sometimes shared too much information with people about where their ships were going and what they were doing, and that information was used to bomb those boats. Soon sailors began warning each other to be quiet by saying, “loose lips sink ships.”
Comprehension Questions
1. Who would be an outsider?
a) Someone who’s a higher-up.
b) Someone who’s outside of the inner circle.
c) Someone who’s buddy-buddy with management.
2. What are the higher-ups doing while they vet candidates to make sure they don’t have any skeletons in their closets?
a) They’re looking through their homes to see what they can find.
b) They’re giving them a test about human bodies.
c) They’re learning as much as they can about the candidates’ past.
Answers at bottom.
What Else Does It Mean?
to fill
The verb “to fill,” in this podcast, means to be in a particular position or to have a particular position: “Jemina was hired to fill a position in accounting, but she quickly transitioned to finance.” The phrase “to fill (someone) in on (something)” means to tell someone about something so that he or she has all the information that everyone else does: “Can you please fill me in on what I missed at today’s meeting?” The phrase “to fill in for (someone)” means to work in someone’s position for a short period of time while he or she isn’t there: “Who’s going to fill in for Becca while she’s on vacation next month?” Finally, the phrase “to fill up on (something)” means to eat so much of something that one isn’t able to eat anything else: “The kids filled up on cookies and weren’t able to eat their dinner.”
to let slip
In this podcast, the phrase “to let slip” means to accidentally share a secret, or to say something that one shouldn’t have said because the information shouldn’t be shared: “How could you let it slip that he’s thinking of quitting his job? That was supposed to be a secret!” A “pink slip” is a small piece of paper letting one know that one has been fired from one’s job: “The company is giving out hundreds of pink slips and closing the factory.” A “slip of the tongue” happens when one uses the wrong word and says something else by accident: “I meant to say, ‘she’s fun,’ but I accidentally said, ‘she’s fat.’ It was just a slip of the tongue!” Finally, a “slip” is a narrow piece of paper: “Where did you put the order slip for table #3?”
Culture Note
American businesses, government “agencies” (departments), and organizations often want to make “major” (important) “announcements” (official information that is shared with others) to “the public” (all people). They usually want the “media” (newspapers, radio, television, and magazines) to help them, so they use “press releases” and “press conferences” to share the information with the media.
With a “press release,” a business, agency, or organization writes a short article about its announcement, often including “quotes” (things said by people in the organization) and “images” (photographs or drawings), as well as “press contact information” (information about whom reporters should call if they want more information). Companies often put their press releases on their website. Press releases are also “distributed” (sent) to “media bureaus” (offices where reporters research and write stories). If the reporters are interested in the story, they might publish the press release in the newspaper or use it as the “basis” (source of information) for the “televised” (on television) news. More often, the reporters will use the press release as basic information, but then call the press contact or do other research to write their own story about the announcement.
For very important announcements, businesses and agencies prefer to “hold” (organize an event) a “press conference.” Reporters are invited to come to the event at a particular place and time. A “spokesperson” (a person who officially speaks for an organization) reads the announcement and “members of the press” (reporters) are allowed to ask questions and “tape” (make a video and/or audio recording) the answers.
Comprehension Answers
1 - b
2 - c