= 0527
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 527: Describing Men’s Bodies.
This is English as a Second Language Podcast episode 527. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode that contains all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of this episode.
This episode is called “Describing Men’s Bodies.” It’s a dialogue between Justin and Katrina talking about the way that men and women look at their bodies. Let’s get started.
[start of dialogue]
Justin: What are you ogling at?
Katrina: I’m watching those guys working across the street.
Justin: Those construction workers?
Katrina: Yeah, those prime examples of manhood. There’s not a flabby gut in the bunch.
Justin: I’m pretty sure they wouldn’t appreciate you watching them as though they were pieces of meat. Hasn’t anyone ever told you not to objectify the opposite sex?
Katrina: What? I’m not objectifying anybody. I’m just admiring their six-packs and guns. Look at those long, lean bodies.
Justin: Stop it! It’s demeaning, and on behalf of all men out there, I’m really offended. It’s disgusting.
Katrina: Is it disgusting to have a picture of Megan Fox on the wall in your office?
Justin: That’s different!
Katrina: How?
Justin: It’s her personality I admire.
Katrina: You could’ve fooled me.
[end of dialogue]
Justin begins by saying to Katrina, “What are you ogling at?” “To ogle (ogle) (someone),” or “to ogle at (someone)” means to look at someone in a way that shows that you are interested in them, possibly even sexually interested in them. It’s usually something that someone doesn’t want you to do. Often it’s done with someone you don’t know, but it could be someone you know as well. You don’t want your college professor ogling at his female students, for example.
Katrina says, “I’m watching those guys working across the street.” So, Katrina is looking at some men, presumably attractive men, who are working across the street from where she is. Justin says, “Those construction workers?” A “construction worker” is a person whose job it is to help build new buildings or roads or bridges, someone who works outdoors, someone who does physical labor – physical work, building or constructing something. “To construct” means to build, so we have “construction workers.”
Katrina says, “Yeah, those prime examples of manhood.” Something that is “prime” is something that is the best. So, a “prime example” would be a perfect or very good example of something. During the 1980s, I was a prime example of what my father used to call a “professional student.” That’s sort of a joking term; someone who’s a professional student is someone who stays in school, usually college, for a very long time. I was in school for almost eight years finishing my bachelor’s degree, which is normally finished in four. I’m not too smart, you see! So, I became a professional student. It’s a long story; I’ll tell you some other time.
Getting back to our dialogue, Katrina says those men – those construction workers are “prime examples of manhood.” “Manhood” is the characteristics of a man, usually someone who is strong, someone who’s responsible. “Manhood” can refer also to the physical attractiveness, perhaps, of a man. Katrina seems more interested in the physical features, or physical aspects of these men. She says, “There’s not a flabby (flabby) gut (gut) in the bunch.” “To be flabby” means to have too much fat. If your arms are flabby, they have a lot of fat on them, and if you move them quickly you may see the fat move. That’s to be flabby. A “gut” is another word for your stomach, the middle part of your body in front of your body – or rather, in the front part of your body. Your stomach, what we would sometimes call your “tummy,” this is the gut, this is the middle part of your body. The word “gut” has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations. To say someone has a “flabby gut” means that perhaps they’ve been drinking too much beer, they’ve been eating too many doughnuts or McDonalds hamburgers, and they have a lot of fat in front in their stomach area. A “bunch” means a group of people or a group of things. So, Katrina says, “There’s not a flabby gut in the bunch.” She means that none of the men have a flabby gut, meaning they’re in good physical condition.
Justin says, “I’m pretty sure that they wouldn’t appreciate you watching them as though they were pieces of meat.” Justin is saying that these men, if they knew that Katrina was looking at them just for their physical aspect – just for their physical appearance, would not appreciate it; they would not want that to happen. That’s what Justin says! “Pieces of meat” is an expression here to mean only for the physical aspect – only for the physical beauty of someone. It’s a negative way of describing this. We don’t want to look at people as though they were pieces of meat; they’re human beings with personalities, and minds, and so forth. But, Justin is saying that that’s the way Katrina is looking at these men. Justin says, “Hasn’t anyone ever told you not to objectify the opposite sex?” “To objectify” (objectify) means to treat a person – a human being as though they were an object; as though they were just a physical thing, and not referring or not being concerned about their personality – who they were inside, and so forth.
Now, there’s a little bit of a switch – a little bit of a reversal happening here; things are a little backwards than they would normally be. Normally, we think about men objectifying women, looking at women just for their physical beauty. Here, we have Katrina looking at the men and objectifying them, making them as though they were just physical objects. The “opposite sex” would be whatever you’re not, so if you’re a man, the opposite sex would be a woman; if you’re a woman, the opposite sex would be a man.
So, Justin says, “Hasn’t anyone ever told you not to objectify the opposite sex?” – not to do that. Katrina says, “What? I’m not objectifying anybody. I’m just admiring their six-packs and guns. Look at those long, lean bodies.” Katrina uses a couple of different informal expressions in describing a man’s body: The first one is a “six-pack.” A “six-pack” normally refers to a way of buying beer, where you buy six cans of beer and they’re held together by a plastic strap. This is called a “six-pack.” But here, the word – or expression “six-pack” refers to the abdominal muscles of a man who is very healthy, very athletic, very strong. “Abdominal” refers, once again, to the stomach – the stomach area, and if you have a very strong man who exercises his abdominal muscles you can see the six muscles under the skin, which is considered to be very healthy, very athletic looking. So, a man’s six-pack would be his abdominal muscles that were in good shape – good condition. Even though we normally use the word “six-pack” to refer to beer, if you drink a lot of six-packs you probably won’t have a six-pack. That is, if you drink a lot of beer, you won’t have those abdominal muscles showing. “Guns,” here, means the biceps, which are the large muscles in your upper arm. They’re between your elbow and your shoulder, and if you take your arm and you put it at a 90-degree angle – at a right angle – and you stress your muscles, you will see your biceps. And of course, for a man to have big biceps is to be considered, usually, more attractive. Arnold Schwarzenegger, our government, has big biceps – although I’m not sure he’s attractive! “Lean” means with very little fat. Someone who doesn’t have a lot of fat on their body is lean. We also talk about pieces of meat, such as beef, being lean, not having a lot of fat on them. So, Katrina says that she’s admiring the men’s six-packs and guns. “Guns” has a couple of different meanings however; take a look at the Learning Guide for some additional explanations. “Guns” is also a pretty informal expression; it would probably be used more as a joke than anything else.
Katrina says, “Look at those long, lean bodies.” Justin says, “Stop it! It’s demeaning, and on behalf of all men out there, I’m really offended. It’s disgusting.” Something that is “demeaning” is something that is embarrassing or shameful, something that is showing less respect to the other person than they should. To be “demeaning” to someone means not to treat them with respect. Justin says it’s demeaning to look at men that way, “and on behalf of all men out there, I’m really offended.” “On behalf of” means speaking for a larger group of people, representing, in this case, all men. That’s what Justin is trying to do here. He says, “I’m really offended,” meaning he’s insulted; he’s angered by something that someone has said or done. Of course, most men would not be offended if a woman looked at him and thought that he was attractive, but again, there’s a little bit of a reversal going on here. Justin says, “It’s disgusting.” Something that’s “disgusting” is something that is unattractive, unpleasant, makes you feel uncomfortable or dirty, something that is gross. All of these would be ways of describing “disgusting.” It’s a very negative way of describing something. If you go to a restaurant and you say, “Oh, the soup was disgusting,” that means it was absolutely terrible, it was horrible; the worst you’ve ever had, perhaps.
Katrina says, “Is it disgusting to have a picture of Megan Fox on the wall in your office?” She’s talking to Justin, who has a picture of a famous actress, someone who’s very – considered by some men, not me – sexually attractive, a woman by the name of Megan Fox. Well, Justin has a picture of this woman on the wall in his office. Katrina is saying that, well, Justin does exactly what he says Katrina should not do.
Justin says, “That’s different!” Katrina says, “How (how is it different)?” Justin says, “It’s her personality I admire.” “Personality” is one’s character, the way one treats other people, the way one talks to other people, the way you think about things; all of these are part of your personality. Of course, Justin here is really making a joke, because he doesn’t have a picture of her if he admires her personality, he has a picture of her because he thinks that she’s attractive.
Katrina says, “You could’ve fooled me.” “The expression “you could’ve fooled me” is a sarcastic phrase used when you don’t really believe what someone else says. Someone says, “I really love going to the dentist,” when you know that person hates going to the dentist, you could say, “Oh well, you could’ve fooled me. It looks like you had a horrible time at the dentist last year.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Justin: What are you ogling at?
Katrina: I’m watching those guys working across the street.
Justin: Those construction workers?
Katrina: Yeah, those prime examples of manhood. There’s not a flabby gut in the bunch.
Justin: I’m pretty sure they wouldn’t appreciate you watching them as though they were pieces of meat. Hasn’t anyone ever told you not to objectify the opposite sex?
Katrina: What? I’m not objectifying anybody. I’m just admiring their six-packs and guns. Look at those long, lean bodies.
Justin: Stop it! It’s demeaning, and on behalf of all men out there, I’m really offended. It’s disgusting.
Katrina: Is it disgusting to have a picture of Megan Fox on the wall in your office?
Justin: That’s different!
Katrina: How?
Justin: It’s her personality I admire.
Katrina: You could’ve fooled me.
[end of dialogue]
On behalf of every one at ESL Podcast, I want to thank the scriptwriter for today’s script, a prime example of a wonderful writer, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
to ogle (someone) – to look at someone in an unwanted way that shows one is sexually interested in that person
* Have you ever noticed how Professor DuPuois always ogles his female students?
construction worker – a person whose job is to help build new buildings, roads, or bridges
* How many construction workers have been assigned to the bridge project?
prime example – a perfect example of something; precisely what one is trying to describe
* Bill is a prime example of how you can succeed even without a college degree, as long as you’re willing to work hard.
manhood – manliness; all the characteristics of a man, such as strength and responsibility
* Kai taught his sons that real manhood means loving your wife and children and being loyal to them.
flabby – with extra fat, so that one’s skin is larger than it needs to be and moves when one walks
* I have lost a lot of weight, but I still have flabby arms.
gut – tummy or stomach; the area of skin in front of one’s stomach and around one’s belly button, especially when talking about someone who is overweight
* My wife says that if I continue drinking beer and eating chips while watching TV, I’m going to have a huge gut.
bunch – a group of people or things
* They picked a bunch of flowers at the park.
to objectify – to value a person as a physical object, not paying attention to that’s person’s personality, intelligence, or feelings
* The newspaper editorial said that magazines like Maxim and Playboy objectify women.
opposite sex – men if one is a woman, or women if one is a man; the other gender
* Would you ever consider having a roommate of the opposite sex?
six-pack – the abdominal muscles of a man who is very healthy and athletic, where one can clearly see six muscles under the skin in front of the stomach
* He does hundreds of sit-ups each day, trying to get a six-pack.
guns – biceps; the large muscles on one’s upper arm, between one’s elbow and shoulder
* He has an impressive set of guns! I wonder how many hours he lifts weights each day?
lean – with very little fat
* Johann’s coach is helping him become leaner and faster.
demeaning – embarrassing and shameful, because someone is showing one less respect than he or she should
* Many people think that picking up garbage is a demeaning job, but somebody has to do it.
on behalf of – speaking for a larger group of people; representing another person or group
* On behalf of everyone who worked on this project, I’d like to thank you for this award.
offended – insulted and angered by something that someone has said or done
* Wallace was offended when his boss criticized his writing style.
disgusting – gross; icky; unattractive and unpleasant, making one feel uncomfortable or dirty
* Picking your nose in a public place is disgusting!
personality – character; the way one interacts with other people
* He has a very outgoing personality, so it’s easy for him to make friends.
you could’ve fooled me – a sarcastic phrase used when one doesn’t believe what a person has said
* - I like vacuuming.
* - Really? You could have fooled me.
Comprehension Questions
1. What does Katrina mean when she says she’s “admiring their six-packs”?
a) She’s looking at which sodas they’re drinking.
b) She’s looking at a group of six men.
c) She’s looking at their stomach muscles.
2. Why does Justin want Katrina to stop?
a) Because he doesn’t want her to view men as objects.
b) Because he wants Katrina to look only at him.
c) Because the men might see her watching them.
Answers at bottom.
What Else Does It Mean?
gut
The word “gut,” in this podcast, means one’s stomach, especially when talking about someone who is overweight: “Your gut is hanging over the waistband of your pants! It’s time to lose weight or buy some larger clothes.” The phrase “blood and guts” is used to describe what comes out of a person’s body in a bad injury: “There was too much blood and guts in that movie!” The phrase “to take guts” means for something to be difficult and need courage: “It takes guts to talk that way to an army sergeant!” The phrase “to have the guts (to do something)” means to be brave or courageous enough to do something frightening or difficult: “Would you ever have the guts to go bungee jumping?”
guns
In this podcast, the word “guns” is an informal word for biceps, or the large muscles on one’s upper arm, between one’s elbow and shoulder: “Hey, you’ve got big guns. Come help me move these heavy boxes.” The phrase “to put a gun to (someone’s) head” means to force someone to do something: “Marliss didn’t want to work on the project, but her boss put a gun to her head.” The phrase “big gun” is used to describe an important decision-maker or a person with a lot of power: “That seems like a good idea, but we’ll have to present it to the big guns before we can act on it.” Finally, the phrase “hired gun” is used to talk about a person who is paid to kill another person: “The mafia uses a lot of hired guns to murder its enemies.”
Culture Note
While some women compete in “beauty pageants” (competitions where the most beautiful woman wins), some men compete in “bodybuilding contests,” where they try to create the largest, most beautiful muscles. Bodybuilding is different from weight training, because bodybuilding focuses on how muscles look, while weight training focuses on building strength. Body builders not only lift “weights” (large, heavy pieces of metal) to become stronger, but also work hard to decrease the amount of fat in their body and use oils and “tans” (coloring the skin with sunlight or ultraviolet light) to make their muscles more “defined” (clearer and easier to see, with sharper lines).
The Mr. America contest is an “annual” (once a year) bodybuilding competition that began in 1940 and is now “considered to be” (thought to be) one of the world’s “premiere” (best and most important) bodybuilding contests. The competitors have to participate in a weight lifting contest to “prove” (show that something is true) their strength. Then, in the main part of the competition, they “pose” for the audience and “judges” (the people who decide who wins), holding their bodies in specific positions and “flexing their muscles” (making muscles bigger by moving them in certain ways).
The winner is named Mr. America and “declared” (said to be) the man with the finest “physique” (body; physical appearance) in the United States. There are also competitions for specific body parts, like arms, legs, and “abdominals” or “abs” (the muscles over one’s stomach).
There is also a Ms. America “title” (the name given to the winner of a competition) for female bodybuilders, but that competition isn’t as popular as the Mr. American bodybuilding contest.
Comprehension Answers
1 - c
2 - a