= 0547
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 547: Shopping for a Hat.
This is English as a Second Language Podcast episode 547. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
If you enjoy listening to these audio files, consider becoming a member of ESL Podcast to support this effort. You can go to our website at eslpod.com. Not only will you be helping us continue to provide these free audio files, but you’ll also improve your English even faster with our Learning Guides.
This episode is called “Shopping for a Hat.” Christine and Eric are trying to buy a hat, and we’ll, of course, be introduced to lots of vocabulary related to hats. Let’s get started.
[start of dialogue]
Christine: What do you think of this one?
Eric: We’re here to buy hats to protect us from the sun while we’re on vacation. Do you think a beret will do that?
Christine: No, but it looks great on me, don’t you think? Isn’t it great to be getting away to the beach in the middle of winter! I already picked out a straw hat with a wide, floppy brim, so I’m all set for the trip.
Eric: In that case, help me pick one out. How about this baseball cap?
Christine: Well, the brim gives your face plenty of shade, but it leaves the back of your head exposed. How about this helmet?
Eric: Very funny. Do you want me to suffocate in this thing? Okay, hand me that cowboy hat.
Christine: That looks cute on you, but it’s huge and it’s going to get squished in the luggage. Hey, try these two hats on!
Eric: Stop messing around. I don’t need a top hat, and that one looks like a bonnet!
Christine: Okay, okay, how about this straw hat? Like mine, it’s soft enough to travel in a suitcase.
Eric: Hey, this one isn’t bad. How do I look?
Christine: Just like the tourist that you are, but that makes two of us.
Eric: I couldn’t care less. I don’t care if I look cool on vacation as long as I am cool!
[end of dialogue]
Christine says to Eric, “What do you think of this one?” She’s showing Eric a “hat,” something you put on your head. Eric says, “We’re here to buy hats to protect us from the sun while we’re on vacation.” “To protect (something)” means to keep it safe or to keep it out of danger. Eric wants to protect his face and his neck so that the sun doesn’t hit it and give him “sunburn,” when the sun makes your skin red and dry. Eric says, “Do you think a beret will do that?” A “beret” is a small, round hat, with a tight piece next to the head. It’s traditionally something associated with the French, and it would almost certainly be too small to protect against much of the sun. You don’t see berets very often in the U.S., although at certain times they were popular. There was a song by the rock singer Prince that was called “Raspberry Beret.” [Jeff sings] She wore a raspberry beret...See, it’s about a girl he likes that is wearing a beret that is the color of a raspberry, which is a small red fruit.
Anyway, Christine tells Eric that no, the beret will not protect against the sun. She says, “it looks great on me, don’t you think (the beret)? Isn’t it great to be getting away to the beach in the middle of the winter!” “To get away” means usually to go on a vacation, to go to another part of the country or the world. Christine says, “I already picked out a straw hat with a wide, floppy brim, so I’m all set for the trip.” A “straw hat” is a hat made from dried pieces of hay or grass that have been put together; we would say they’ve been “woven” together. This hat has a wide, floppy brim. The “brim” (brim) is the part of the hat that extends, or sticks out, beyond the head to protect your face. It can also go around and protect the back of your neck. So the brim is the part of the hat is not directly on your head; it extends out in front, sometimes on the sides and in the back. A “floppy brim” is one that is flexible; it moves easily. “Floppy,” as an adjective, means something that usually hangs down a little bit, is flexible. You can think of the ears of a dog. Some dogs have floppy ears; they hang down and they’re flexible.
Christine says she’s all set for the trip, meaning she’s ready for the trip. Eric says, “In that case, help me pick one out (help me select one). How about this baseball cap?” He means what do you think of: “How about this baseball cap?” A “cap” is just another word for a hat that is very small, that fits, we would say, closely around the head. But there’s a part in front that sticks out – there’s a brim that sticks out in front. We call these baseball caps because they’re the kind of caps, or hats, that baseball players wear. If you ever have seen an American baseball game, you know what these hats look like. They’re very popular for people not playing baseball as well. I have a couple of baseball caps that I use to keep the sun away from my face – to protect my face from the sun.
Christine says, “Well, the brim gives your face plenty of shade, but it leaves the back of your head exposed.” “Shade” is an area of darkness that is created when the sun or some bright light is blocked, so that you can’t see the light. For example, if you are in a park, and there’s a tree, and the sun is coming up in the sky, you can stand by the tree so that the tree is blocking the sun. You would be in the shade; the tree is shading you, it’s giving you protection from the sun. The word “shade,” along with the word “brim,” has other meanings; take a look at our Learning Guide for some additional explanations. Christine says the baseball cap gives Eric shade in the front, but not in the back. She says, “the back of your is head exposed.” “To be exposed” can mean that other people can see you or see something. Here, it really means not protected. In other words, the back of the head will not be protected from the sun. Christine suggests to Eric, “How about this helmet?” meaning what do think about this helmet, here’s something else you can wear. A “helmet” (helmet) is a very large, heavy, strong hat. It’s typically used by people who are riding motorcycles; they often wear helmets. Soldiers in an army will often have a helmet to protect their head. That’s a helmet.
Of course, Christine isn’t serious, because you would not wear a helmet just to protect your head from the sun. So Eric says, “Very funny,” which is an expression that we use sometimes to mean that’s not very funny, I don’t think you’re very funny. So Eric says, “Very funny. Do you want me to suffocate in this thing?” “To suffocate” means to not be able to breathe, usually because something is covering your mouth. Eric says, “Okay, hand me that cowboy hat.” A “cowboy hat” is a large hat that has a soft top and a very large brim – a large, circular area that goes around the entire head. Traditionally, it was a hat worn by men in the American West when they rode horses. So if you ever have seen a movie, which we would call a “Western,” about 19th century in the western part of the U.S., you have seen, no doubt, a cowboy hat. Cowboy hats are still worn by men in some parts of this country, not so much here in Southern California.
Eric wants the cowboy hat, and Christine says that it looks cute on him, meaning it looks nice on him; it looks good when he’s wearing it. “But,” she says, “it’s huge (it’s very big) and it’s going to get squished in the luggage.” “To get squished” (squished) means to put a lot of pressure on something, and you, without wanting to, will make it smaller and it will lose its shape. There’s a similar verb, “to squash,” which doesn’t help you very much. You can think of a soft hat, like a baseball cap or a cowboy hat, that has a big book on top of it. Well, the book will press against the hat and make it flat; it will squish it.
Christine then gives Eric two more hats to try on, meaning to put on to see if he likes them. Eric says, “Stop messing around,” meaning stop joking, stop fooling around. She has given him two hats that he is obviously not going to wear as a joke. One of them is a top hat. A “top hat” is a very tall hat, usually black or gray, that is sometimes, not very often, worn by men for a formal occasion. Abraham Lincoln, our 16th president, is often pictured in a top hat. It’s an old-fashioned kind of hat that you don’t see very much anymore. Christine also gave Eric a bonnet (bonnet). A “bonnet” is a hat worn by women, where you put a certain piece of fabric over the head, and then there’s a string down below that that you tie underneath your chin. Once again, it’s an old-fashioned hat for the most part, not that common anymore.
Christine says, “Okay, okay, how about this straw hat? Like mine, it’s soft enough to travel in a suitcase.” Eric says, “Hey, this one isn’t bad (meaning it’s pretty good). How do I look?” Christine says, “Just like the tourist that you are,” meaning you look like a “tourist,” someone who obviously is visiting a place. “But,” she says, “that makes two of us.” The phrase “that makes two of us” is used to show that the same thing is true for you, often when you agree with what someone says or what applies to their situation applies to your situation. Someone could say to you, “I’m worried about losing my job in this economy,” and the other person says, “That makes two of us.” They mean they are also worried about losing their job.
Eric says, “I couldn’t care less (meaning it doesn’t bother me that I look like a tourist). I don’t care if I look cool on my vacation as long as I am cool!” Here, “cool” has two different meanings. In the first case, “if I look cool” means if I look attractive, interesting, something that other people would like. “Cool,” as an adjective, used to describe things that are popular, at least it was a few years ago. “Cool” can also mean a comfortable temperature, a temperature that is not too hot. So, Eric is using both meanings here. He says as long as I am cool, meaning I’m not hot, I don’t care if I don’t look cool, meaning if I don’t look attractive, if people don’t think what I’m wearing is attractive.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Christine: What do you think of this one?
Eric: We’re here to buy hats to protect us from the sun while we’re on vacation. Do you think a beret will do that?
Christine: No, but it looks great on me, don’t you think? Isn’t it great to be getting away to the beach in the middle of winter! I already picked out a straw hat with a wide, floppy brim, so I’m all set for the trip.
Eric: In that case, help me pick one out. How about this baseball cap?
Christine: Well, the brim gives your face plenty of shade, but it leaves the back of your head exposed. How about this helmet?
Eric: Very funny. Do you want me to suffocate in this thing? Okay, hand me that cowboy hat.
Christine: That looks cute on you, but it’s huge and it’s going to get squished in the luggage. Hey, try these two hats on!
Eric: Stop messing around. I don’t need a top hat, and that one looks like a bonnet!
Christine: Okay, okay, how about this straw hat? Like mine, it’s soft enough to travel in a suitcase.
Eric: Hey, this one isn’t bad. How do I look?
Christine: Just like the tourist that you are, but that makes two of us.
Eric: I couldn’t care less. I don’t care if I look cool on vacation as long as I am cool!
[end of dialogue]
The scriptwriter for this episode was the always cool Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
to protect – to keep something safe; to keep something out of danger or away from harm; to make sure something isn’t hurt, injured, or killed
* Chantasit protects his important documents by putting them in his safe.
beret – a small, round hat with a tight piece next to the head and some extra fabric on top, traditionally used by the French
* The artist in the play wore berets while she painted.
straw hat – a hat made from dried pieces of hay or grass that have been woven together
* Yoshio is taking a class to learn how to make straw hats.
floppy – something that hangs down, is flexible, and moves easily; not stiff
* What a cute dog! Look at those long, floppy ears.
brim – the part of a hat that sticks out beyond the head to protect one’s face, neck, and hair from sunshine and/or rain
* This hat’s brim is too narrow, so the sun comes right into my eyes.
baseball cap – a small hat that fits closely around the head, but has a part in front that sticks outward, protecting one’s face from the sun, often used by baseball players, and often with a logo and/or writing on the front
* Why do so many teenage boys wear baseball caps backwards?
shade – an area of darkness created when sunlight or another bright light is blocked by something else
* There isn’t any shade in their backyard, so they’re going to plant some tall trees.
exposed – seen; vulnerable; not protected
* Maxim is wearing so many jackets, scarves, mittens, and hats that only his nose and eyes are exposed.
helmet – a very large, heavy, strong hat that is worn to protect one’s head, often used by soldiers or motorcycle riders
* What kind of helmets do soldiers wear to fight in the hot desert?
to suffocate – to not be able to breathe, usually because something is covering one’s mouth and nose
* It’s so hot here I feel like I’m suffocating! Let’s go out and get some fresh air.
cowboy hat – a large hat with a soft top and a large circular area that sticks out from the head on all sides, traditionally worn by men in the American West when they rode horses and worked on ranches
* Blake loves watching Western movies, so for the costume party, he’s going to wear a cowboy hat and cowboy boots.
to squish – to squash; to put a lot of pressure on something, or to squeeze something between two things, making it lose its shape and become smaller
* There’s a big bug on the wall. Squish it!
top hat – a very tall hat, usually black or grey, sometimes worn by men for very formal events
* They had an unusual wedding: she wore a very long, old-fashioned dress and he wore a dark suit with a top hat.
bonnet – a type of hat that used to be worn by women, made of a loose fabric and tied under the chin
* Laura sewed a bonnet to match her dress.
that makes two of us – a phrase used to show that the same is true for oneself; a phrase used to show that one agrees with what another person has said, and that it applies to one’s own situation
* - I’m worried I’m going to lose my job.
* - That makes two of us.
cool – popular, attractive, and interesting; admired and liked by other people
* Were you one of the “cool kids” in high school?
cool – a comfortable temperature that is refreshing and isn’t too warm or too cold
* They keep their house nice and cool during the summer.
Comprehension Questions
1. Which of these hats is the biggest?
a) A beret.
b) A baseball cap.
c) A cowboy hat.
2. Which of these hats is worn only by women?
a) A straw hat.
b) A helmet.
c) A bonnet.
Answers at bottom.
What Else Does It Mean?
brim
The word “brim,” in this podcast, means the part of a hat that sticks out beyond the head to protect one’s face, neck, and hair from sunshine and/or rain: “Please take off your hat for the photo because the brim is covering your eyes.” A “brim” is also the top edge of a glass or a container: “She filled the glass to the brim with milk, so there was no way to move it without spilling it.” Or, “The box is filled to the brim with crayons and small toys.” The phrase “to brim with tears” means to have one’s eyes fill with tears and to begin to cry: “Her eyes brimmed with tears when she heard the bad news.” Finally, the phrase “to brim over with (something)” means to have a lot of some feeling or emotion: “They were brimming over with happiness when they finally saw each other again.”
shade
In this podcast, the word “shade” means an area of darkness created when sunlight or another bright light is blocked by something else: “This plant won’t grow in the shade. It needs direct sunlight.” A “lampshade” is the round, stiff piece of fabric that is placed around the top part of a lamp to cover the light bulb: “They bought lampshades to match their couch.” “Shades” can also be blinds, or a type of window covering: “Please close the window shades before you go to bed tonight.” A “shade” is also a specific type of a certain color: “Which shade of green do you like best?” Finally, the word “shades” is an informal term meaning sunglasses: “Hey, nice shades! You look like a movie star.”
Culture Note
In the United States, some types of “headgear” (hats; things worn on one’s head) are “associated with” (connected to) specific jobs and activities. For example, in the “food service industry” (the part of the economy related to making and serving prepared, cooked food), “chefs” (professional cooks) normally wear a “chef’s hat,” which is a large, white hat with a wide band around the head and with loose fabric on top. People who serve food, especially if they have long hair, often wear “hair nets,” which have elastic to wrap around the head and cover the hair with a type of loose fabric made from many “threads” (strings) that are woven together. The hair can still be seen through the hairnet, but it cannot fall off the person’s head and into the food that is being served.
People who work in the “construction industry” (the part of the economy related to building things) or who work with “heavy equipment” (large, dangerous machines) usually wear “hardhats,” which are large, heavy, and very strong hats that “attach” (have two pieces that connect to each other) under the “chin” (the bony part of one’s face below one’s mouth and above one’s neck) and protect the head from heavy objects that might fall from above.
At a high school or college graduation ceremony, people wear “mortar boards,” which are hats with a flat, square piece that sits on top of the head. A “tassel” (a group of many long threads tied together) hangs down from the center. Mortar boards come in different colors, depending on the colors of the school and the type of degree that the graduate is earning.
Comprehension Answers
1 - c
2 - c