= 0901
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcomed English as a Second Language Podcast number 901 – Participating in a Clinical Trial.
This is English as a Second Language Podcast episode 901. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there, download the Learning Guide, and become a member of ESL podcast.
This episode is a dialogue between Lucinda and Elan about clinical trials. Let’s get started.
[start of dialog]
Lucinda: You look tired. Are you all right?
Elan: I’m fine. It’s this clinical trial I’m enrolled in. I’m suffering from some side effects.
Lucinda: Are they serious?
Elan: No, they’re not too bad. I was told to expect some adverse reactions in the first weeks of the pilot study. I guess that’s why only a small group of volunteers is taking part right now. It’s so they can judge the drug’s effectiveness before the pharmaceutical company does a large-scale trial.
Lucinda: At least you know you’re not in the group getting a placebo.
Elan: Who knows? I hope not. If I successfully get through this first phase, I’ll get a full dose of the drug in phase two.
Lucinda: Then you may once and for all be rid of Podcaster’s Disease.
Elan: I really hope so. No one should go through life sounding like a podcaster.
[end of dialog]
Lucinda begins the dialog by saying, “You look tired. Are you all right?” – are you okay? Elan says, “I'm fine. It's this clinical trial I’m enrolled in.” A “clinical trial” is a careful testing of some new drug or some new procedure. They get people who are willing to be tested with this new drug or this new treatment, and see what happens. In the United States, in order for a drug to be approved for use by the general public, by the average person, the drug company has to have these clinical trials to test what the drug does. Elan is enrolled in a clinical trial. “To be enrolled in something” means to be signed up for something, to be registered for something. We often use this verb “to enroll” when talking about school. “I'm going to enroll at the university.” I'm going to sign up or register to be part of the university.
Elan says, “I'm suffering from some side effects.” “To suffer from something” means to feel pain or some other negative effect of some disease, or in this case, drug. A “side effect” is something that happens to your body – a negative thing that happens to your body – when you take a drug, or undergo some kind of medical treatment. A side effect would be something that is bad, but is not the same thing as what the disease or illness is. For example, you might take a drug to help you with your allergies, to help you so that you don't sneeze so much.
One of the side effects of the drug you take could be drowsiness, making you sleepy. That could happen as a side effect. It's not the main reason. In fact, it's not the reason at all. You're taking the drug but it has that side effect on you. It has that other thing that happens. That is not desirable.
Lucinda says, “Are they serious?” – are the side effects serious? Elan says, “No, they're not too bad. I was told to expect some adverse reactions in the first weeks of the pilot study.” An “adverse (adverse) reaction” is a negative result, a negative effect – once again, a term that we usually associate with medical treatment. An adverse reaction would be, when you take a drug and something negative happens. It's like a side effect. Usually, I think it's a little more serious than that. An adverse reaction might cause your doctor to stop giving you the drug.
Elan said he was told to expect some adverse reactions in the first weeks of the pilot study. The “study” is just the trial, the period where they are studying this drug. A “pilot study” is a study that is a small experiment, a small test before the main, larger study. A “pilot study” would involve fewer people, perhaps for a shorter amount of time in order to see whether the drug was going to work at all and then if you got some positive results from a pilot study, then you would do a larger study, the main study.
Elan says, “I guess that's why only a small group of volunteers are taking part right now.” A “volunteer” (volunteer)” is someone who agrees to do something either for free or without being required to do it. You could ask for volunteers for something at your work, even though the person is being paid for it. We could consider them a volunteer because they don't have to say yes.
Volunteers always have the option of not doing something. In many contexts, however, volunteer means not getting paid for something. You do it just because you want to help. That would be one reason. This is a volunteer for a pilot study. It's not clear to me that they are doing it for free. However, they could've just volunteered in the sense of agreeing to do it without being required to do it. This small group of volunteers is taking part right now. “To take part” means to participate, to have a role in something. I'm taking part in the activity this afternoon. I'm going to be part of it. I'm going to participate in it. These volunteers are taking part in the study.
Elan says, “It's so they can judge the drug’s effectiveness before the pharmaceutical company does a large-scale trial.” The drug is the medicine. “Effectiveness” would refer to whether it does what it says it is supposed to do – whether it works. “Pharmaceutical” refers to a company related to making drugs and medicine. “Large-scale” means a lot of people, a lot of people involved in the study trial. “Trial,” remember, means the same as study. So, Elan says that there are only a few volunteers taking part so that the drug company, the pharmaceutical company, can decide whether the drug is going to work or not, before they have a large-scale trial.
Lucinda says, “At least you know you're not in a group getting a placebo.” A “placebo” (placebo) is something you are given in a clinical trial that looks like a drug, or it looks like medicine, but it's not really. It's nothing that would help you or hurt you. The reason that they use placebos in clinical trials is to test to make sure that people are not getting better for psychological reasons, rather than for physical reasons. So, the placebo is given to a group of people who aren’t told, of course, that it's not the real drug.
Elan says, “Who knows?” meaning “Who knows whether I'm getting a placebo or not?” “I hope not. If I successfully get through this first phase I'll get a full dose of the drug in phase two.” “Phase” (phase) here – it just means stage or step or a period, one part of something. A drug trial, a drug study, could have a number of different phases. The first phase is the pilot study. The second phase could be a large-scale trial. The third phase could be another large-scale trial and so forth. So, phase is just a general term for a period or stage or step.
A “dose of a drug” is an amount of medicine that you usually take at one time. If you have a headache, the doctor might tell you to take two aspirin. That would be your dose – two aspirin. There’s an old joke, the doctor will tell you, “Take two aspirin and call me in the morning. If you come in and complain about something.” The idea is the doctor doesn't really want to help you and is just trying to get rid of you.
Lucinda says to Elan, “Then you may once and for all be rid of Podcaster’s disease.” “Once and for all” means finally, conclusively, without any remaining amount that is not done. “Once and for all” is the end of something. Lucinda says that Elan may once and for all be rid of Podcaster’s disease. “To be rid of something” means to no longer have something, especially something that you don't really want or like or that is unpleasant. I am finally rid of my neighbor’s dog. The dog is no longer at my neighbor's house. I am rid of the dog.
Podcaster’s disease is when a person can't stop talking and they always talk like they are producing a podcast. That is what Elan has. Elan says, “No one should go through life” – no one should live – “sounding like a podcaster.” Personally, Elan, I think it's the best thing that could happen to you. You should be so lucky as to have Podcaster’s disease.
Now let’s listen to the dialog this time at a normal speed.
[start of dialog]
Lucinda: You look tired. Are you all right?
Elan: I’m fine. It’s this clinical trial I’m enrolled in. I’m suffering from some side effects.
Lucinda: Are they serious?
Elan: No, they’re not too bad. I was told to expect some adverse reactions in the first weeks of the pilot study. I guess that’s why only a small group of volunteers is taking part right now. It’s so they can judge the drug’s effectiveness before the pharmaceutical company does a large-scale trial.
Lucinda: At least you know you’re not in the group getting a placebo.
Elan: Who knows? I hope not. If I successfully get through this first phase, I’ll get a full dose of the drug in phase two.
Lucinda: Then you may once and for all be rid of Podcaster’s Disease.
Elan: I really hope so. No one should go through life sounding like a podcaster.
[end of dialog]
There are no side effects to listening to our wonderful scripts written by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
clinical trial – a carefully controlled test of a new drug, closely watching and recording people’s reactions to its use
* I would never consider participating in a clinical trial. What if they find out the experimental drug causes more harm than good?
to enroll – to officially sign up and register as a participant of a program or as a member of an organization
* How many students enroll in the university each fall?
to suffer from – to feel the pain or other negative effects of something, especially a disease or injury
* Heather has suffered from terrible headaches ever since the car crash.
side effect – an unintended, negative consequence of taking a particular medicine
* The most common side effects of this pain medication are nausea and dizziness.
adverse reaction – an unintended, harmful effect of taking a medicine or getting treatment
* The operation should have been simple, but Gregorio had an adverse reaction to the anesthetic used during the surgery.
pilot study – a small experiment, test, or study conducted before the main experiment or test, usually to prove that something can succeed
* The school district is running a pilot study in one school to determine whether the new language program can help students learn a new language.
volunteer – someone who wants to participate in a project and/or performs work without receiving payment
* Volunteers help to feed and clean the cats and dogs in the animal shelter, so that employees can focus more on administrative duties.
to take part – to participate; to have a role in something
* Why did you decide to take part in the protests?
drug – a medicine; a medication
* Are you taking any prescription drugs?
effectiveness – a measure of how well something works
* Even after several months, we’re not sure of the effectiveness of giving employees more breaks to produce better workers.
pharmaceutical – related to the creation and production of medicines and drugs, especially working with chemicals instead of plants
* Pharmaceutical labs have to meet very high standards for safety and cleanliness to produce medicines that are safe.
large-scale – involving many people, locations, resources, or areas; not a small or limited project
* Global warming will result in many large-scale climate changes.
placebo – a tablet or liquid that is given to a patient as if it were a medicine, but which actually has no effect on one’s physical health, because the doctor or researcher expects it to have psychological consequences
* Doctor King sometimes wishes that she could prescribe a placebo for patients who come into her office demanding a prescription for a new drug that she knows won’t really help them.
phase – period; stage; step; one of many parts or levels in a process
* In this first stage, the builders are leveling the ground and pouring the foundation. In the second stage they’ll build the walls and roof. And in the third stage they’ll work installing windows and doors.
dose – dosage; the amount of medicine that one is supposed to take at a certain time
* If this doesn’t make your headache go away, you can increase the dose to 100 milligrams.
once and for all – conclusively; firmly and finally; without anything remaining undone or undecided
* What can we do to answer this client’s questions once and for all, so that she doesn’t continue to call?
to be rid of – to no longer have something, especially something that is unpleasant
* Now that we’re rid of our houseguests, we can wake up as late as we want and walk around in our pajamas all day.
Comprehension Questions
1. What could be done to increase the strength of a medicine?
a) Increase the side effects.
b) Increase the placebo.
c) Increase the dose.
2. What kind of company will conduct the large-scale trial?
a) A government agency.
b) A company that makes medicines.
c) A retail store that sells drugs.
Answers at bottom.
What Else Does It Mean?
to take part
The phrase “to take part,” in this podcast, means to participate or to have a role in something: “How many people are going to take part in the conference next month?” The phrase “to play a part” means to have a role in something: “What factors played a part in your decision to attend Acme University?” The phrase “to want no part of (something)” means to not want to be involved in something in any way: “You can do whatever you want, but I want no part in those dishonest deals.” The phrase “to dress the part” means to wear appropriate clothing, especially for a particular job or event: “If you want to get a promotion at work, you have to dress the part.” Finally, the phrases “in these parts” and “around these parts” means in this area: “We don’t see many wild animals in these parts.”
phase
In this podcast, the word “phase” means one of many parts, stages, or levels in a process: “What phase of the software development life cycle are you in?” Or, “It’s often unpleasant to spend time with two-year-olds, but they’re just passing through a phase.” The phrase “to phase (something) in” means to begin using something gradually: “We’ll phase in the budget cuts slowly to minimize their impact.” The phrase “to phase (something) out” has the opposite meaning – to stop using something gradually: “The company is phasing out the buying of cars for employees to use. Next year, only senior employees will be allowed to use them, and then the year after that, only managers will still be allowed."
Culture Note
Institutional Review Boards
An “institutional review board” (IRB) is a “committee” (a group of people working together for a particular purpose, usually by having many meetings) that “approves” (says something is okay) and “monitors” (observes) research that involves people. Scientists present their research projects to an IRB, whose members then ask whatever questions are necessary before deciding whether the research is approved and the scientist can “proceed” (continue; move forward). The IRB may “modify” (change) the scientist’s proposed research to make it safer.
IRBs analyze the researchers’ goals and determine whether the “potential” (possible; referring to what might happen) “benefits” (has advantages or good affects) “outweigh” (are greater than, are more important than) the potential “risks” (bad things that might happen). The IRB members focus not only on the potential physical and mental results for the trial participants, but also on “ethical issues” (questions of what is good or bad, right or wrong).
The IRBs are “instructed” (told) to “safeguard” (protect) the rights of the “trial subjects” (the people being studied in an experiment). They are supposed to pay special attention to highly “vulnerable” (easily hurt) populations, like children and pregnant women. The IRB also considers the amount of any “compensation” (money paid for a service) provided to the trial participants.
Once a research project has been approved, the IRB must review it at least once per year. If the IRB members determine that the situation has changed and the risks now outweigh the benefits, they can tell the scientists to modify or “terminate” (stop) the trials.
Comprehension Answers
1 - c
2 - b