= 0925
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 925 – Going Through Customs.
This is English as a Second Language Podcast episode 925. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there and become a member of ESL Podcast.
This episode is about someone who is going through customs. When you go into another country, the government officials of that country often want to look to see what you are bringing into the country. Let’s get started.
[start of dialogue]
Customs Officer: Your passports, please. What is your final destination?
?zkan: Los Angeles.
Customs Officer: How long is your stay?
?zkan: We’ll be there for a week.
Customs Officer: What is the purpose of your trip?
?zkan: I’m going there on business, and my family is accompanying me on vacation.
Customs Officer: Who are you traveling with?
?zkan: This is my wife, Ayse, and these are my children, Mustafa and ?mer.
Customs Officer: Are you bringing in any restricted items? Any plants, fruits and vegetables, meats, or animals?
?zkan: No.
Customs Officer: Do you have anything to declare?
?zkan: We bought some duty-free items in the airport. Here’s the receipt.
Customs Officer: That’s fine. Step over to the exam station for baggage inspection.
...
We opened our bags for inspection, and luckily, the inspector found nothing to confiscate and we got off scot-free. I’m really glad they didn’t find that cat we’re smuggling in as a gift for my favorite podcaster!
[end of dialogue]
The topic of this episode is “going through customs” (customs). “Customs” refers to the office, or the people who work for the office, of the government that check the things that you are bringing into a country. So, when you go from one country to another and you have a suitcase – you have luggage with clothing and other things in it – the customs official wants to make sure that you’re not bringing anything into the country you’re not supposed to. Most countries have two people or two offices that handle new arrivals to the country, either at an airport or somewhere else. That would be “immigration and customs.” “Immigration” checks to make sure that you have the legal right to come into the country, and “customs” checks to make sure you’re not bringing anything that you shouldn’t bring into the country.
Our dialogue begins, then, with a customs officer. “Officer” here just means employee – person who works for the customs office. The customs officer says, “Your passports, please.” Your “passport” is the official government document from your government that allows you to travel to other countries. In the U.S. you typically have to show your passport to an immigration official and then later to a customs official, because it’s your official identification.
Customs officers will often ask you what your final destination is. So, if you fly to Boston, but you are only going to arrive in Boston and stay there for a few hours, and then you’re going to drive down to New York City, you would say your final destination is New York City. That’s where you are going to go. That’s the place you’re really going to go. You’re just here in Boston to rent a car and drive down to New York City. That’s what the customs officer is asking ?zkan.
?zkan says, “Los Angeles.” That’s his final destination. The customs officer says, “How long is your stay?” Your “stay” is the period of time when you’re going to be in a certain place. “How long are you going to remain in Los Angeles?” ?zkan says, “We’ll be there for a week.” The customs officer says, “What is the purpose of your trip?” Why are you coming? Usually they want to know if you’re there for business or if you’re there for pleasure – that is, just for fun. ?zkan says, “I’m going there on business.” So, his reason, his purpose, is for something related to his job.
He says, “My family is accompanying me on vacation.” To “accompany” someone is to go with someone else. The other person needs to go somewhere, and you decide to go with them, perhaps “to keep them company,” we might say. That is, to be their friend, to have someone for them to talk to. That would be an example of accompanying someone.
In this case, the family is accompanying ?zkan on vacation. “On vacation” means they’re there for pleasure. They’re there just to have fun, to relax. The customs officer says, “Who are you travelling with?” ?zkan answers, “This is my wife, Ayse, and these are my children, Mustafa and Omer.” The customs officer says, “Are you bringing in any restricted items?” An “item” (item) is just a thing – something. A “restricted item” is something that you are not supposed to bring into that country or that, if you bring it into that country, you need special permission, or you might even have to pay money, like a tax, to bring it into the country. That would be a “restricted item.”
The customs officer then lists, or gives examples of, restricted items – plants, fruits and vegetables, meats, or animals. In some countries, they don’t allow you to bring in plants, for example, because they’re afraid that they may be plants that have diseases, or have bugs, or have things that might hurt the plants in that country. ?zkan says, “No.” No, I don’t have any of these restricted items.
The customs officer says then, “Do you have anything to declare?” “To declare” (declare) means to make an official statement. In this case, it means to tell the customs officer that you have something that you want to bring in the country but that you will probably have to pay tax on or that you think the customs officer might want to know that you’re bringing it in.
So, for example, if you’re bringing in a lot of cigarettes, or if you’re bringing in alcohol, you might have to declare that at customs. You might have to say, “Yes, I am bringing in a bottle of alcohol,” and tell that to the customs officer. You might have to pay some sort of tax, however, if you do that. But, you do not want to go through customs and not declare things you’re supposed to, because then, if they search you and they find those things in your luggage, in your suitcase, you could get into more trouble. They, in fact, could not allow you to come into the country, possibly.
?zkan says, “We bought some duty-free items in the airport. Here’s the receipt.” In many places, you can buy things without having to pay taxes on them, especially if you are about to leave the country and you’re not going to remain in that country. If you are from another country, you can sometimes buy things at the airport, or even there on the airplane, that you don’t have to pay the local taxes on. That’s what ?zkan is talking about. He says, “We bought some duty-free items.” “Duty” (duty) is the tax. It’s another word for a tax you pay to bring something into a country. “Duty-free” means that it is not taxable. You don’t have to pay tax on it.
The customs officer says, “That’s fine. Step over to the exam station for baggage inspection.” “To step over” means to move over to one side, to go to a particular place in a particular direction, usually to the side of where you are right now. The customs officer wants the family to step over to the “exam station.” “Exam” is short for “examination.” The word “station” is sometimes used to describe one particular place within a larger place where something is done. In this case, it is a place at the airport, usually a big table where they take your luggage or your baggage and they open it up and they inspect it – that is, they look inside of it to see what you are bringing into the country.
When you come into the United States, you don’t always have to go through baggage inspection. Sometimes it’s just random. They just pick people who they think may be bringing something – or just because they need to show that they’re working – and they inspect the luggage. They look inside of your luggage to make sure that you are not bringing in anything that you should not.
After the customs officer speaks to ?zkan, he says, “We opened our bags for inspection and luckily,” – fortunately – “the inspector found nothing to confiscate and we got off scot-free.” The “inspector” is the person who works for the customs office who looks, who inspects the baggage. “He found nothing to confiscate.” “To confiscate” (confiscate) means to take something from you because you are, in this case, bringing it in illegally. “To confiscate” means to take away something from another person. In this case, the inspector did not confiscate anything.
And so, ?zkan says, “We got off scot-free.” “To get off scot- (scot) free” means not to be punished for something you did wrong. We only use this expression if you’ve done something wrong but you are not punished for it. You have no negative consequences for it. That is “to get off scot-free.” That’s what ?zkan says.
He says, “We got off scot-free. I’m really glad they didn’t find that cat we’re smuggling in as a gift for my favorite podcaster.” “To smuggle (smuggle) in something” or “to smuggle something in” is a phrasal verb meaning to bring something in that you are not allowed to – to hide something so that the customs inspector doesn’t see it, because it’s illegal and you don’t want to get caught, or you don’t want to pay the duty, to pay the tax you would have to. This is not, by the way, a very good idea. But ?zkan wants to give his favorite podcaster – I don’t know who that is – a cat. I assume it’s not me.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Customs Officer: Your passports, please. What is your final destination?
?zkan: Los Angeles.
Customs Officer: How long is your stay?
?zkan: We’ll be there for a week.
Customs Officer: What is the purpose of your trip?
?zkan: I’m going there on business, and my family is accompanying me on vacation.
Customs Officer: Who are you traveling with?
?zkan: This is my wife, Ayse, and these are my children, Mustafa and ?mer.
Customs Officer: Are you bringing in any restricted items? Any plants, fruits and vegetables, meats, or animals?
?zkan: No.
Customs Officer: Do you have anything to declare?
?zkan: We bought some duty-free items in the airport. Here’s the receipt.
Customs Officer: That’s fine. Step over to the exam station for baggage inspection.
...
We opened our bags for inspection, and luckily, the inspector found nothing to confiscate and we got off scot-free. I’m really glad they didn’t find that cat we’re smuggling in as a gift for my favorite podcaster!
[end of dialogue]
She never seems to go on vacation. She’s always working hard. I speak of our wonderful scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
passport – an official government document that allows one to travel internationally, with pages for stamps each time one enters or exits a country
* Do Americans need to have a passport to travel to Canada?
final destination – the place where one is going, not the one or more stops on one’s journey
* Our final destination is Madison, Wisconsin, but first we have to change planes in Houston, Texas.
stay – the period of time when one is in a particular place, especially during a vacation or a business trip
* How long was your stay in the resort?
on business – traveling for work, not for pleasure
* Rick is traveling on business, but he will reply to your email once he’s back in the office later this week.
to accompany (someone) – to go with someone; to provide companionship to someone; to do something with another person
* In some countries, women are not allowed to be in public unless they are accompanied by a male relative.
on vacation – traveling for pleasure, relaxation, and enjoyment, not for work
* We both gained a lot of weight while on vacation, because we ate in restaurants every day.
restricted items – things that are not allowed, or that have limitations or rules
* Knives, scissors, aerosol cans, and fireworks are all restricted items on airplanes.
to declare – to make an official statement, especially to let a customs official know that one is carrying something of interest while traveling
* Why do we have to declare how much money we’re bringing into the country?
duty-free – without taxes being included in the price of things one buys
* A lot of people on the flight purchased duty-free alcohol and cigarettes.
to step over – to move to the side; to go in a particular direction
* Please step over here, sir, and let me show you some of our best luxury watches.
exam station – a large table or a small area where people can thoroughly examine something, especially a place where people review the items inside suitcases in an airport
* Tomio works in an exam station at the airport, and he has some interesting stories about the crazy things some people pack when they travel internationally.
baggage inspection – the process of opening a suitcase and reviewing all the items inside it to determine whether people are carrying things that are not allowed
* Dogs that can smell illegal drugs are an important part of baggage inspections at the airport.
to confiscate – to use one’s authority to take something from a person against that person’s wishes
* If you take knitting needles on an airplane, the flight attendant might confiscate them so you can’t use them as a weapon.
to get off scot-free – to not receive any punishment for one’s bad behavior; to break the rules without any negative consequences
* If that criminal gets off scot-free, it’s a clear sign that our justice system isn’t working.
to smuggle (something) in – to bring something that is not allowed under the laws or rules, especially when crossing international borders
* Sometimes people smuggle in drugs by swallowing small plastic bags filled with cocaine.
Comprehension Questions
1. What did ?zkan and his family buy at the airport?
a) Items on which they did not have to pay taxes.
b) Items that cannot be sold to children, like cigarettes and alcohol.
c) Items that will allow them to relax and forget their duties and responsibilities.
2. What does ?zkan mean when he says that the family “got off scot-free”?
a) They weren’t allowed into the country.
b) They weren’t punished for breaking the rules.
c) They didn’t have to go back to Scotland.
Answers at bottom.
What Else Does It Mean?
stay
The word “stay,” in this podcast, means the period of time when one is in a particular place, especially during a vacation or a business trip: “Did you enjoy your stay in the Virgin Islands?” When talking about clothing, a “collar stay” is a small, flat piece of plastic with a pointed end that is inserted into the collar of a man’s dress shirt to keep the tip (end) stiff and pointed: “Remember to take out the collar stays before you put your shirt in the washing machine.” “Staying power” is the ability to persevere and continue to do something until it is finished: “Finishing a 50-mile race requires a lot of staying power.” Finally, a “stay-at-home mom/dad” is a parent who does not work outside of the home, instead spending almost all his/her time with the children: “Denise wants to quit her job and become a stay-at-home mom.”
to declare
In this podcast, the verb “to declare” means to make an official statement, especially to let a customs official know that one is carrying something of interest while traveling: “All travelers are required to declare any fruits, vegetables, nuts, or seeds.” Or, “After the hurricane, the governor declared a state of emergency.” The phrase “to declare income” means to state how much money one has received, especially on tax forms: “Please declare all your income, including your tips, scholarships, lottery winnings, and gambling winnings.” The phrase “to declare war” means to officially announce the beginning of a war with another country, competitor, or something harmful: “Many nonprofit organizations have declared war on poverty and hunger.”
Culture Note
How to Clear Customs
“Frequent travelers” (people who travel often) have “figured out” (identified) many ways to “clear customs” (get through customs without problems) quickly. They understand that the “role” (job; responsibilities) of a “customs official” is to make sure travelers are not bringing anything “illegal” (against the law) or “harmful” (dangerous) into the country. So before traveling, they find out which items are “prohibited” (not allowed) and make sure that those items are not in their “baggage” (luggage; suitcases).
Experienced travelers know if their items “are subject to” (fall under the rules of) “duties” (taxes). If they must pay duties, they pack those items “separately” (independently; not with other items) and have their “method of payment” (the way someone pays, such as cash or a credit card) “on hand” (ready and available).
Frequent travelers are also prepared to respond to customs officials’ questions directly and “succinctly” (in as few words as possible). They “anticipate” (think about ahead of time) questions about the “nature” (type) of their travel, their citizenship, and the length of their stay in the country.
Finally, frequent travelers are “aware of” (knowledgeable about and familiar with) their “rights” (how one should be treated) and “responsibilities” (what one must do). They understand that they must cooperate with customs officials, “readily” (willingly and quickly, without delaying) opening their bags if they are selected for baggage inspection. But they also know that if they do not like the way they are being “treated” (dealt with) by a customs official, they can “complain” (say something negative) about it to that individual’s “supervisor” (boss).
Comprehension Answers
1 - a
2 - b