= 0942
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 942 – Daily Chores on a Farm.
This is English as a Second Language Podcast episode 942. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Become a member of ESL Podcast by going to our website.
This dialogue is between Cesar and Karol about working on a farm, a place where they have animals and other exciting things. Let’s get started.
[start of dialogue]
Cesar: Rise and shine! It’s time to get to work.
Karol: What?! It’s four o’clock in the morning. The sun isn’t even up yet.
Cesar: You live on a farm now. We have a lot of chores to do before sunup and we need to start doing them now.
Karol: I’ll milk the cows later. Let me sleep to a decent hour.
Cesar: All right, you can milk the cows a little later, but we have to feed and water the animals now. We also have to clean out the stalls and groom the animals before we start repairs on the fences.
Karol: Why can’t we do those things when the sun is up and we can see what we’re doing?
Cesar: Because we’ll need daylight hours to tend to the crops. We’re done with planting, but we’ll need to do the watering and weeding. Just be glad that the harvest is three months away.
Karol: I don’t think I’m cut out to be a farmhand.
Cesar: You should have thought of that before agreeing to spend the summer at your uncle’s farm. Now move!
Karol: But I thought I’d spend the days learning how to ride horses.
Cesar: City girls!
[end of dialogue]
Our dialogue begins with Cesar saying to Karol, “Rise and shine!” This expression, “Rise (rise) and shine (shine),” is used when you want to wake someone up, someone who is sleeping. This is especially used when you want to seem very happy, when you want to seem what we would call “cheerful.” “Rise and shine everyone!” You are telling everyone to wake up.
Sometimes it's used sarcastically or jokingly when you are telling someone that they have been sleeping too long. You might say this to your children, for example, on Saturday morning if they are sleeping too late. You might say, “Rise and shine everyone.” Typically, it's used when you have somewhere to go or something to do and you need everyone to wake up in order to do it. The verb “to rise” means to get up, to get out of your bed. “Shine” here, I guess, could mean happy. If you're telling someone to shine, you want them to do well. You want them to be smiling, perhaps.
Cesar is telling Karol to rise and shine because it's time to get to work. Karol says, “What?! It's four o'clock in the morning.” It's four a.m. “The sun isn't even up yet.” When we say “the sun is up,” we mean the sun is in the sky. It is no longer nighttime. Cesar says, “You live on a farm now.” A “farm” is a place where you grow plants for food. You can also have animals that are also used to produce food. Sometimes the animals are the food. Chickens, for example, produce eggs which you can eat and then you can eat the chicken. Cesar and Karol are on a farm.
Cesar says, “We have a lot of chores to do before sunup and we need to start doing them now.” “Chores” (chores) are tasks that you have to perform, especially related to cleaning or taking care of something such as your house or, in this case, animals. Farm chores would probably be related to doing things that are required to keep the farm operating. In general, the word “chore” is used for a task that is not very pleasant, that you don't really want to do. Cesar says that he and Karol have to do these chores before “sunup” (sunup). “Sunup” is sunrise – the time when the sun appears in the sky and the day begins.
Karol says, “I’ll milk the cows later.” “To milk (milk) a cow (cow)” is to take your hands or to use a machine to take milk from a cow. A “cow” is an animal that produces milk. We also get beef from a cow. We call the meat of the cow “beef” – steaks, hamburgers, that sort of thing. That meat is called “beef,” and it comes from a cow. “Milk” is also a noun referring to the liquid that comes out of a cow. You can also have other kinds of milk from other animals, such as goat’s milk. Karol says she'll milk the cows later. “Let me sleep to a decent hour,” she says. A “decent (decent) hour” here means a time that isn't too early or too late, a time that is considered normal for doing certain kinds of tasks.
Cesar says, “All right, you can milk the cows a little later, but we have to feed and water the animals now.” “To feed (feed) and water the animals” means to take care of the animals by giving them food to eat and fresh water to drink. Cesar says, “We also have to clean out the stalls and groom the animals before we start repairs on the fences.” “To clean out” is a two-word phrasal verb that means basically the same as to clean. The word “out” is just used for emphasis. It could mean to completely remove everything from a place. “I'm going to clean out my desk” means I'm going to remove everything from my desk. That's what you do if you lose your job. You have to clean out your desk. Here, we’re talking about making something cleaner – getting rid of the dirt and whatever else is there.
Cesar and Karol need to clean out the “stalls” (stalls). A “stall” is a small section, a small area, in a barn that is separated from other areas by a wall and is used usually to keep an animal in, such as a horse. A “barn” is a large building where you keep animals and farm equipment. The verb “to groom” (groom) means to clean an animal, often including brushing its fur, its hair. It may also mean to do other things to the animal in order to keep it clean and healthy.
The verb “to groom” can also be used with humans. You can talk about “grooming” yourself. That might include cutting your hair, shaving, making sure you look handsome or pretty. I try to groom myself so that I don't look too ugly. I look ugly even after I groom myself, but not as ugly as I would if I didn't groom myself. The word “groom,” interestingly enough, is also used for a man who is about to get married. The woman is called a “bride” (bride) and the man is called the groom. I'm not sure if there's a connection there between husbands and animals, quite possibly.
Cesar says they need to groom the animals “before we start repairs on the fences.” A “fence” (fence) is a short wall that goes around a certain area, a certain piece of property, that is usually made from wood or metal. A fence is designed either to keep something in, such as your animals so they don't escape, or to keep something out, such as your neighbors. That's a fence. There's an old expression, “Good fences make good neighbors,” meaning be careful what kind of fence you put up to separate you from your neighbor. You want to make sure that you don't make them angry by putting up your fence. I made my former neighbor angry by putting up a fence, but that's another story.
Karol says, “Why can't we do those things when the sun is up and we can see what we're doing?” Cesar says, “Because we’ll need daylight hours to tend to the crops.” Karol wants to wait until the sun is up, but Cesar says no, we have to save that time, those “daylight hours to tend to” – or take care of – “the crops.” The term “daylight hours” refers to the time of the day when the sun is out, when the sun is in the sky. “Crops” (crops) refers to plants that you grow in order to eat or sometimes to make clothing or, for some of you, to smoke.
Cesar says, “We’re done with the planting, but we’ll need it to do the watering and weeding. Just be glad the harvest is three months away.” “Planting” refers to putting seeds in the ground so that you can grow new plants. You can also plant a plant. The word “plant” can be used as a noun, to refer to the things that grow out of the ground. It's also used here as a verb meaning to put things into the ground so that they grow.
Cesar says they need to do the watering and weeding. “To weed” (weed) means to get rid of the unwanted plants, the plants that you don't want from your garden nor from your farm. Cesar says, “Just be glad,” meaning you should be happy, “that the harvest is three months away.” The “harvest” (harvest) is the process of taking all the plants out of where they are growing – out of the “fields,” we would say – and bringing them in so you can sell them or eat them or do whatever you’re going to do with them.
Karol says, “I don't think I'm cut out to be a farmhand.” The expression “to be cut out to be” something means to be qualified or prepared to do something. Perhaps you don't have the interest or you don't have the right attitude or, simply, you don't have the skills to do something. I am not cut out to be a professional baseball player. I would like to be, but I am not cut out to be. I don't have the preparation or the skills. But I can watch baseball on television, so that's almost as good as being a real player.
Karol says she's not cut out to be a “farmhand” (farmhand), one word. A “farmhand” is a person who works on a farm, especially one who does physical work – “physical labor” we would call it. Cesar says, “You should have thought of that before agreeing to spend the summer at your uncle's farm.” Karol, we now learn, is “spending the summer” – staying for the months of June, July, and August – at her uncle's farm. Karol says, “But I thought I'd spend the days learning how to ride horses.” Karol thought that going to a farm was going to mean riding horses and doing fun things, not getting up early and milking the cows.
Cesar ends our dialogue by saying, “City girls!” A “city girl” or a “city boy” is an insulting phrase to describe someone who lives in the city and doesn't know anything about farming. People who live on farms would use this term about people who live in cities and don't know how to do anything that needs to be done on a farm. I am, for example, definitely a city boy.
Now let's listen to the dialogue, this time at a normal speed.
[start of dialogue]
Cesar: Rise and shine! It’s time to get to work.
Karol: What?! It’s four o’clock in the morning. The sun isn’t even up yet.
Cesar: You live on a farm now. We have a lot of chores to do before sunup and we need to start doing them now.
Karol: I’ll milk the cows later. Let me sleep to a decent hour.
Cesar: All right, you can milk the cows a little later, but we have to feed and water the animals now. We also have to clean out the stalls and groom the animals before we start repairs on the fences.
Karol: Why can’t we do those things when the sun is up and we can see what we’re doing?
Cesar: Because we’ll need daylight hours to tend to the crops. We’re done with planting, but we’ll need to do the watering and weeding. Just be glad that the harvest is three months away.
Karol: I don’t think I’m cut out to be a farmhand.
Cesar: You should have thought of that before agreeing to spend the summer at your uncle’s farm. Now move!
Karol: But I thought I’d spend the days learning how to ride horses.
Cesar: City girls!
[end of dialogue]
Thanks to our city girl scriptwriter, Dr. Lucy Tse, for milking the English cow in order to feed us another wonderful dialogue.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
rise and shine – a phrase used when waking someone up, especially when one wants to be very cheerful and happy
* Rise and shine! Breakfast is ready!
farm – a place where plants used for food or making clothing are grown and animals are raised for eating or producing other products
* They own a sheep farm in Minnesota.
chore – a task that must be performed, especially related to cleaning or the care of animals
* They expect their children to do many household chores, like setting the table, washing the dishes, checking the mail, and feeding the dog.
sunup – sunrise; the time when the sun appears and the day begins
* Sunup will continue to get earlier each day until June 21, when the days start to get shorter again.
to milk a cow – to use one’s hands or a machine to take milk from a cow
* You can’t really appreciate a bowl of ice cream unless you’ve milked a cow at least once.
decent hour – a time that is not too early or late; a time that is considered appropriate or normal for performing a certain activity
* I can’t believe our neighbor is playing the tuba at 7:00 a.m. on a Saturday! Can’t he wait until a decent hour to start practicing?
to feed and water the animals – to care for animals by giving them food and fresh water
* Paolo feeds and waters most of the animals on their farm, but his wife is responsible for feeding the chickens and ducks.
stall – a small section in a barn that is separated from other areas by walls, used for one large animal, usually a horse
* Sheila’s horse is in the third stall on the left.
to groom – to clean an animal and brush its fur (hair), and possibly to cut its claws (nails) and brush its teeth
* When you groom a horse, it’s important to brush all parts of the body, but avoid walking behind the animal, because it might kick you.
fence – a short wall around a property, usually made from wood or metal, designed to keep animals inside (or out of) an area
* Anita and Howard had to install an eight-foot fence to keep the deer out of their vegetable garden.
daylight hours – the period of time during a 24-hour day when there is sunshine; daytime
* Before people had electric lights, they had to finish all their homework and reading during the daylight hours, or else read by candlelight.
crop – a plant that is grown for food or making clothing
* Corn and soybeans are two very common crops in many parts of the United States.
planting – the process of placing seeds or small plants in the ground and covering them with soil so that a plant can grow
* Broccoli, lettuce, and spinach are all good for fall planting, once the weather cools down a little bit.
to weed – to remove unwanted plants from an area to make the ground more attractive and/or to give other plants more room to grow
* When weeding, it’s important to pull out the roots of a plant so that it doesn’t grow back right away.
harvest – the process of taking the part(s) of a plant that one wants to eat or use, collecting it for eating or processing
* Most of the strawberries were eaten by slugs, so we had a very poor harvest this past year.
to be cut out to be – to be qualified or prepared to do something, especially when referring to someone’s inner qualities rather than skills that can be learned
* If you faint when you see blood, you probably aren’t cut out to be a nurse.
farmhand – a person who works on a farm, doing physical work
* It’s hard to find farmhands who are willing to work an eight-hour day in the hot sun without complaining.
city girl – an insulting phrase used to describe a girl or woman who is not familiar with farm life and is not accustomed to doing physical work or being around plants and animals
* We were shocked to realize that many of the campers were city girls who didn’t even know that carrots grew underground.
Comprehension Questions
1. According to Cesar, what do they need to do before they can start repairing the fences?
a) They need to give the animals their medicine.
b) They need to wash and brush the animals.
c) They need to walk the animals for exercise.
2. Which activity immediately results in having food to eat?
a) Planting.
b) Weeding.
c) Harvesting.
Answers at bottom.
What Else Does It Mean?
stall
The word “stall,” in this podcast, means a small section in a barn that is separated from other areas by walls, used for one large animal: “It seems cruel to keep such a large horse in such a small stall where it hardly has room to walk around.” When talking about public bathrooms, a “stall” is the small area surrounded by partial walls that provide privacy around one of several toilets: “Why doesn’t this stall have a hook where I can hang my purse?” A “stall” is also one booth or an area for one seller in a large outdoor market: “The fruit and vegetable stalls are at the northern end of the Saturday market, while artists and musicians are at the southern end.” Finally, when used as a verb, “to stall” means to delay: “Why are you stalling? Just announce the award winners!”
to weed
In this podcast, the verb “to weed” means to remove unwanted plants from an area to make the ground more attractive and/or to give other plants more room to grow: “If you don’t want to get scratches on your hands while weeding blackberries, wear gloves!” The phrase “to weed (something or somebody) out” means to get rid of someone or something that is not as good as the others: “How can we weed out the liars?” Or, “The human resources department will weed out the weakest job applicants.” As a noun, “weed” is a slang (informal) term for marijuana: “Have you ever smoked weed?” Finally, the phrase “to grow like weeds” means to grow very quickly: “Goodness, your teenagers are growing like weeds!”
Culture Note
Common Agricultural Products in the USA
The United States is a “net exporter” (a country that exports (sends out to other countries) more than it imports (receives from other countries)) of food. Most “agricultural” (related to growing plants for food and making clothing) activities is done in the “Great Plains,” a large area of flat land with good “soil” (dirt used for growing plants) in the “central” (middle) part of the country. The Great Plains states (primarily Kansas, Nebraska, Iowa, Minnesota, North and South Dakota, and Wisconsin) are often referred to as “the breadbasket of the United States” because they are the source of so many agricultural products.
Corn is “by far” (significantly more than anything else) the “top” (greatest; most) agricultural product in the United States “by weight” (in terms of weight; as measured by weight), followed by soybeans and wheat. A lot of that corn is grown in the State of Iowa, which is often referred to as “corn country.” People can drive for many, many miles and see nothing but corn “fields” (areas where a particular crop is grown).
The State of Texas is often referred to as “cattle” (cows) country, because there are many “ranches” where cows are raised for “beef” (meat from a cow) and for “dairy” (food made from milk). And the State of Idaho is often “associated with” (thought about in connection with) potatoes, which grow very well there.
“Cotton” (a plant that has a white fiber used for clothing) and “tobacco” (a plant with leaves used in cigarettes) grow best in the southeastern part of the United States. The States of Florida and California are often associated with “citrus fruits” (fruits like oranges, grapefruits, lemons, and limes), and California is also known for its avocadoes.
Comprehension Answers
1 - b
2 - c