= 0943
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 943 – Making a Will.
This is English as a Second Language Podcast episode 943. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there. Become a member of ESL Podcast. Download the Learning Guide for this episode.
This episode is a story about making a will – a plan for what happens to your property when you are no longer on this earth. Let's get started.
[start of story]
Last week, I got a wake-up call. One of my oldest friends from high school died suddenly in an accident, leaving no will. With no estate planning at all, his assets went into probate and his dependents were left in limbo.
My friend was a young man, the same age as me. At our age, who thinks about estate planning? Well, he should have, and I’m starting right now to put my affairs in order.
I’ve already decided who will be my beneficiaries and how much of an inheritance each family member will get. One big decision I’m still thinking about is who should be my executor. I want to make sure my bequests are carried out and my assets are properly disposed of, so this person has to be trustworthy.
After I make those decisions, I’ll write a holographic will. It’s the simplest way of drawing up a will and adding codicils without an attorney, and since I’m still of sound mind, there shouldn’t be any problems. I’ll ask my neighbors to be witnesses.
Before I start drawing up my will, though, I still have one other important decision to make. Who should get custody of my eight cats?
[end of story]
This episode is about the happy topic of death – what happens not to you when you die, but to everything that you own. We’re talking in this story about making a will. A “will” (will) is a legal document saying what should happen to your money and the other things that you own after you die. If you want to give your car, when you die, to your friend, you have to put that in your will. It's a written, typically, statement that says what you want to have happen to your property, to the things you own, after you die.
Our story begins when I say, “Last week, I got a wake-up call.” “To wake up” means to stop sleeping, to be conscious again. A “wake-up call” is when someone calls you, for example, at a hotel to wake you up in the morning. Hotels used to do that – some hotels still do – back before they put alarm clocks in all of the rooms, which is pretty common nowadays in most hotels. You could ask the hotel to call you on the telephone and wake you up at a certain hour. As I said, there are many hotels that still do that.
The expression “to get a wake-up call,” however, is a little different. It means to experience something surprising, something shocking, or to see someone else experience something, often negative, that makes you think again about your own life and what you are doing with your life. “To get a wake-up call” is always used to indicate that you are seeing something or realizing something that you didn't realize before, and now your view of the world is a little different.
I said, “I got a wake-up call. One of my oldest friends from high school died suddenly in an accident, leaving no will.” This did not actually happen. It's just a story, but it could happen. Someone dies in an accident and doesn't leave a will, doesn't leave a legal statement saying where they want their property to go. “With no estate planning at all, his assets went into probate and his dependents were left in limbo.”
The word “estate” (estate) can mean a couple of different things. Here, it refers to all the money and things that you own when you die. That's your estate. “Estate planning” is deciding before you die what is going to happen to your things and, more importantly, how to make things easy for the people who you will give your things to. “Estate planning” could include things like making sure that the government doesn't take all of what you have in order to pay taxes, because in most places, in many places in the U.S., you have to pay taxes to the government, especially if you have a lot of money when you die.
“Assets” (assets) refers to something you own, something that has value. It could be money. It could be jewelry. It could be a house. All of those are assets. The word “probate” (probate) refers to the legal process where the government – the courts – decide how your assets are going to be given out. The technical word we would use here is “distributed.” “How will your assets be distributed?” If you die and you don't leave a will, then the government determines who gets your money based on certain laws and rules that have been set up for that situation.
A “dependent” is a person who is financially depending on or financially connected to another person, usually someone who doesn't have their own job or doesn't have another source of income, or at least not very much income. “To be left in limbo” (limbo) means to be in an uncertain condition, uncertain situation. You're not quite sure what the final decision is going to be about what you're going to get, in this case. “To be left in limbo” means to not know what is going to happen to you. This is typically used when someone has to make a decision about something, but he or she hasn't made that decision yet.
In the story, I say that my friend did not have any estate planning, so “his assets went into probate and his dependents were left in limbo.” The government is going to decide who gets his money, and the people who were depending on him – the people who were perhaps receiving money from him when he died – now are in a situation where they don't know what they're going to get. “My friend was a young man,” I say, “the same age as me.” Well, I'm not that young, but young enough. “At our age,” I say, “who thinks about estate planning?” People who are young don't think about dying and what will happen to them when they die, so they don't think about things like wills and estate planning.
“Well,” I continue, “he should have” – meaning he should have thought of that – “and I'm starting right now to put my affairs in order.” The expression “to put your affairs (affairs) in order” means to prepare for your death by making sure all of your documents are in place for the people who have to come after you and take care of your assets. To make sure that you have a will would be another part of putting your affairs in order. It's an expression we use when someone is getting ready to die, in a way, or at least getting prepared in case they do die.
I then say, “I've already decided who will be my beneficiaries and how much of an inheritance each family member will get.” A “beneficiary” is a person who receives some benefit, often a person who receives money or other things after someone else dies. “Beneficiaries” could also get money from, for example, an insurance policy. “Inheritance” refers to the money or the things that a person will actually get. We use the verb “to leave someone.” “I'm going to leave you my car.” That means that when I die, your inheritance – the thing that you will get from me – is my car. Or my bike. I'm not sure if I want to give you my car, but definitely my bicycle.
I continue, “One big decision I'm still thinking about is who should be my executor.” The “executor” (executor) is the person who is responsible for taking care of your affairs, your financial affairs, after you die. “I want to make sure my bequests are carried out,” I say. A “bequest” (bequest) is another word for the money or property that is given to a person or to an organization – to a beneficiary – after you die. It's similar to the idea of an inheritance. The word “inheritance” usually refers to a family member, someone you are related to. If that person gets something, you could call that an inheritance. If it's another person, a friend, or an organization, we would talk about a “bequest.”
I want to make sure that my bequest is carried out – that the money actually goes to the people I want my money to go to. I also talk about my assets being “properly disposed of,” meaning the person who is my executor does with the money what I want him to do with the money. “After I make those decisions, I’ll write a holographic will.” A “holographic (holographic) will” is a will that is written by hand. That's all the word “holographic” means here. Written by hand, not typed on a typewriter – if you still own a typewriter – or on a keyboard or computer and then printed out on a printer. Those types of wills are not holographic wills. A holographic will is written by hand, the old way.
I say that a holographic will is the “simplest way of drawing up a will and adding codicils without an attorney.” “To draw up” something, or “to draw something up,” means to prepare and write out a document, especially a formal document. “We’re going to draw up a contract” – we’re going to prepare an agreement to buy a new house. “To draw up the will” would mean to prepare the will: to write it down, to get it ready so that it can be used. A “codicil” (codicil) is like an amendment to your will. It's something that you add to your will after you have written it. Maybe you've changed your mind about giving your car to your nephew. You can write a codicil giving your car to someone else, or your bike.
Then I say, “Since I'm still of sound mind, there shouldn't be any problems.” The expression “sound mind” is often used in legal situations. It means the person is rational, is able to think clearly. Basically, that the person isn't crazy. In order to write and sign a will, you have to be of sound mind. If you're not, then the government may not carry out the terms of your will – what you say you want done in your will after you die.
I then say, “I'll ask my neighbors to be witnesses.” A “witness” in this case is a person who sees you sign the will yourself. A witness is saying, “Yes, this person actually signed the will, and I was there to see it.” Witnesses are required for certain kinds of special contracts or documents, including a will.
I end by saying, “Before I start drawing up my will, though, I still have one other important decision to make. Who should get custody of my eight cats?” “Custody” (custody) refers to the responsibility that a person has to take care of someone such as a young child or an animal. When a husband and wife divorce, someone gets custody of the children. Perhaps the mother gets custody of the children, meaning she will be the one who is primarily responsible for the child and has the legal authority to make decisions for the child.
We don't talk about custody for someone who is an adult and who is of sound mind. If you have some sort of mental difficulties, then it's possible that someone would have custody of you. They would have the legal authority and right to make decisions for you. We don't normally talk about getting custody of an animal, and certainly not a cat. That last sentence is a good indication that this story is completely made-up.
Now let’s listen to the story, this time at a normal speed.
[start of story]
Last week, I got a wake-up call. One of my oldest friends from high school died suddenly in an accident, leaving no will. With no estate planning at all, his assets went into probate and his dependents were left in limbo.
My friend was a young man, the same age as me. At our age, who thinks about estate planning? Well, he should have, and I’m starting right now to put my affairs in order.
I’ve already decided who will be my beneficiaries and how much of an inheritance each family member will get. One big decision I’m still thinking about is who should be my executor. I want to make sure my bequests are carried out and my assets are properly disposed of, so this person has to be trustworthy.
After I make those decisions, I’ll write a holographic will. It’s the simplest way of drawing up a will and adding codicils without an attorney, and since I’m still of sound mind, there shouldn’t be any problems. I’ll ask my neighbors to be witnesses.
Before I start drawing up my will, though, I still have one other important decision to make. Who should get custody of my eight cats?
[end of story]
Our greatest asset here at ESL Podcast is, of course, our script writer – the wonderful Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
to get a wake-up call – to experience something shocking, or to see someone else it experience it, so that one questions what is most important in life and realizes that one must make changes
* When Barney suffered a heart attack, it was a wake-up call for all of us to improve our diet and exercise more.
will – a legal document stating what should happen with one’s money and what one owns after one dies
* According to the will, each child will receive more than two million dollars.
estate planning – the process of planning for what will happen to one’s money and property after one dies, as well as the process of creating plans to make sure that one’s family members will be taken care of after one dies
* It’s important to update your estate planning records after major life events, like a marriage or the birth of a child.
asset – something that one owns and that has value, especially money and property
* The Kastens have a lot of assets, like expensive artwork and fancy cars.
probate – the legal process that determines whether a will is valid and determines how assets are distributed if there is no will
* Harold’s house never entered probate, because his wife was a co-owner, so it passed to her automatically.
dependent – a person who is financially depended on another person, usually a child or a non-working spouse
* What are the tax advantages of claiming an adult child as a dependent on my tax forms?
in limbo – in flux; uncertain, unclear, and undecided; still changing or still being discussed and decided upon
* It looks like the hurricane is going to hit the island on Thursday, so now our vacation plans are in limbo.
to put (one’s) affairs in order – to prepare for one’s own death by organizing papers, closing accounts, and telling others where important information can be found
* Li put her affairs in order by giving her sister access to her most important documents.
beneficiary – a person who receives some benefit, usually money, especially through an insurance policy
* If a beneficiary is not designated when the policy holder dies, the funds in the account will automatically be given to the spouse, followed by the children.
inheritance – money or other assets given to a person when someone dies, especially a relative
* Di worked hard all her life to leave a good inheritance for her three children.
executor – a person who is responsible for making sure that a will is followed correctly
* Karina wants to have an executor who isn’t a family member, because she thinks that will prevent arguments and bad feelings.
bequest – money or property that is given to a person or organization in accordance with a will after someone dies
* His bequests included a generous donation to the local hospital.
holographic will – a will that is written by hand (not typed) and signed by the individual, without the witness signatures that are part of more formal wills
* When the man realized he was dying, he quickly wrote “all to my wife” on the wall over his bed, and it became his holographic will.
to draw up – to draft; to write something; to create a written document, especially informally
* How long did it take the team to draw up a new contract?
codicil – a written statement that adds to, changes, or revokes (nullifies) a will
* As soon as the divorce papers were signed, Kazuyuki asked his lawyer to work on the codicils.
of sound mind – logical, rational, and able to think clearly; without a mental illness; not crazy
* It would be illegal and unethical for a minister to marry two people unless he believed they were both of sound mind.
witness – a person who signs a document to officially indicate that he or she saw it be signed by the person it directly affects
* Could you please sign your name here as my witness for this health insurance paperwork?
Comprehension Questions
1. Who receives an inheritance?
a) Dependents.
b) Beneficiaries.
c) Executors.
2. What does he mean by saying, “I’m still of sound mind”?
a) He’s still young and should live for many more years.
b) He is smart enough to write his own will without an attorney.
c) He can think logically, clearly, and rationally.
Answers at bottom.
What Else Does It Mean?
will
The word “will,” in this podcast, means a legal document stating what should happen to one’s money and possessions after one dies: “Luna wrote her will immediately after the birth of her daughter.” A “will” is also one’s determination to do something: “If you have the will, you will find a way to succeed.” The phrase “where there’s a will there’s a way” means that if one really wants to do or have something, it is possible: “Losing 200 pounds will be a major challenge, but where there’s a will there’s a way.” Finally, the phrase “at will” means however and whenever one wants: “You can’t just leave the office at will. You need to tell your boss where you’re going and when you’ll be back.”
of sound mind
In this podcast, the phrase “of sound mind” means logical, rational, and able to think clearly, without a mental illness: “How could anyone of sound mind leave millions of dollars to a pet rabbit?” A “sound sleeper” is someone who sleeps well and is not easily woken up: “Justin is a such a sound sleeper that he didn’t even wake up when the fire alarm sounded.” The phrase “sound asleep” means in a deep sleep and not easily disturbed: “The baby is sound asleep, but you can hold him once he wakes up.” Finally, a “sound bite” is a short excerpt (part) of a recorded statement or speech that is shown repeatedly in the news: “Ollie is a popular politician who is very good at coming up with interesting sound bites, but he isn’t really a very good policy-maker.”
Culture Note
Types of Wills
In the United States, there are many different types of wills. Most people “opt for” (choose to have) a “simple will,” which is also known as a “statutory will.” People can “adapt” (modify; change) a “template” (a document that can be customized to meet one’s needs) by filling in the “blanks” (empty lines) to make sure that their will meets the state’s legal requirements. These types of wills work best for people with an “uncomplicated” (simple) “estate” (everything one owns at the time of death).
Wealthier individuals sometimes opt for a “pour-over will,” which “pours” (transfers) assets into a “trust” (a special type of account with named beneficiaries), and then those assets can be distributed “in accordance with” (according to) the terms of the trust.
A “conditional will,” also known as a “contingent will,” is “contingent” (dependent) on certain events happening. For example, a beneficiary might be required to have reached a certain age, or a beneficiary might be required to not have had a divorce. If those “conditions” (requirements) are not met, the other terms of the will are not followed.
A “living will” is a completely different type of document. It does not deal with the distribution of assets, but “rather” (instead) indicates what type of medical treatment an individual wants to have. For example, an older person with many health problems might create a living will stating that he or she does not want to “be resuscitated” (brought to life or kept alive after one has stopped breathing).
Comprehension Answers
1 - b
2 - c