= 0947
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 947 – Seeing a Circus Performance.
This is English as a Second Language Podcast episode 947. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
This episode, like all of our episodes, has a Learning Guide. Go to ESLPod.com and download the one for this episode.
This episode is a dialogue about going to see a circus performance, a place where you can see animals and people doing all sorts of interesting tricks. Let’s get started.
[start of dialogue]
Paula: Ta-da! We’re here. This is your big surprise.
Roman: We’re going to the circus?
Paula: You got it in one! It’s going to be great. There’ll be clowns and acrobats, trapeze artists and lion tamers.
Roman: I haven’t been to the circus since I was a kid.
Paula: That’s the point. I thought this would be a nostalgic experience for both of us, and let us feel like kids again.
Roman: I’m not sure . . .
Paula: Come on! We’ll miss the first act. I think there’ll be jugglers, magicians, and tightrope walkers, too.
Roman: Great.
Paula: Listen! I can hear the ringmaster from here. Let’s go!
Roman: When you said that you had a surprise for me that would make me feel young again, this wasn’t exactly what I envisioned.
Paula: I know. It’s even better, right?
Roman: If you say so.
[end of dialogue]
Paula begins our dialogue by saying, “Ta-da! We’re here.” That expression, “Ta-da!” (ta da) – two words – is used when you are excited and proud to show another person something. You are introducing something to another person – something you're excited about or something, perhaps, you are presenting them as a gift. Paula says, “We’re here. This is your big surprise.” So, Paula’s surprise – her gift, if you will – is the place where she has taken Roman.
Roman says, “We’re going to the circus?” A “circus” (circus) is a type of live entertainment where you go and watch people – we would call them “performers” – and trained animals do certain tricks, often things that are dangerous or things that seem unusual. A circus may have lions that do certain tricks. A circus may have someone who is walking on a wire that is suspended way up high – what we call, in fact, a “high wire” or a “tightrope.” All of these things could be found at a circus, in addition to many other kinds of entertaining performances.
Circuses are popular with children, and many of the things that you will see at a circus are designed to entertain children. Circuses, at least here in the United States, typically travel from one city or one town to another, and they’ll stay for maybe three or four days, maybe a week or two. When I was growing up, in the 1970s, back in St. Paul, Minnesota, we would have a circus that would come to town that would arrive to the city at least once a year and would stay for a couple of weeks. You could go and watch the show, watch the circus performances, in a large auditorium.
Roman asks Paula, “We’re going to the circus?” Paula says, “You got it in one.” The expression “to get it in one” (one) means to guess something correctly the first time – not to need another guess, to get it right on the first attempt. Paula says, “It's going to be great. There'll be clowns and acrobats, trapeze artists and lion tamers.” Paula lists some of the things you see, typically, at a circus. We've already mentioned a few of these.
One thing you will always see at a circus is a “clown” (clown). A “clown” is a person who dresses in a large outfit, a large uniform that's usually very colorful, that has a lot of bright colors. “Clowns” often have big red noses on their face and big shoes that they wear. Clowns also often have a big wig – fake hair, basically – that they wear. That's also very colorful. Clowns are very popular among small children. They are used to entertain small children.
An “acrobat” (acrobat) has nothing to do with your computer or reading PDF files. An “acrobat” is a person who uses their body in an unusual way, similar to a gymnast, but often does things in the air. They do a lot of things that involve jumping or going up high into the air. A “trapeze (trapeze) artist” is a performer who entertains people by flying through the air, usually jumping from one bar or one rope to another. “Trapeze artists” do things that may be very dangerous because they could fall, although usually in a circus there will be something called a “net” (net) that is put below them to catch them so they don't hit the floor if they fall.
A “lion (lion) tamer (tamer)” is a person who trains animals – in this case, a lion – to do certain tricks. The word “tamer” comes from the verb “to tame” (tame), which means to take a wild animal and basically calm it down, make it so that it will not kill anyone or hurt anyone, especially when you're talking about a lion. A lion, of course, is a large cat and, like all cats, can be very dangerous. I recommend staying away from lions and other cats.
Roman says, “I haven't been to the circus since I was a kid.” A “kid” (kid) is a young child. This, of course, is not unusual. People go to circuses usually when they are young, when they are young children – unless, of course, you're the parent taking a child to the circus. Roman is a little surprised, I guess, that Paula is taking him to a circus. Paula says, however, “That's the point.” She’s saying, “Exactly. That's why I'm bringing you here.”
“I thought this would be a nostalgic experience for both of us, and let us feel like kids again.” The word “nostalgic” (nostalgic) means being filled with strong emotions, strong feelings, especially when thinking about something in the past, when reflecting on your memories. When we say something is “nostalgic,” there’s also a sense that we want to go back in time. We want to return to that time when a certain thing was popular or when we experienced a certain positive thing.
Paula wants this trip to the circus to be a nostalgic one and let her and Roman “feel like kids again” – to feel as though they were young children. That’s something I honestly never really want to do, is to feel like a young child again. I know I had a happy childhood. I'm not saying there was anything bad about when I was growing up, but there were a lot of things that weren’t very fun about being a child. So, honestly, I’ve never much had a feeling about wanting to be a kid again. I'd like to be 20 years old again. That's different.
Roman is also expressing some doubts. He says, “I'm not sure,” meaning “I'm not sure I want to go to the circus.” Paula, however, insists. She says, “Come on!” meaning let's go. “We’ll miss the first act.” An “act” (act) here refers to a part of a performance, a section of a performance. The first act would be the first part of some performance. It could be a play. It could be, as in this example, a circus. She says, “We’ll miss the first act” – if we don't go now, we will miss the first act. That's why she's trying to hurry Roman up.
Then Paula lists some other things you will see at a circus. She says, “I think there'll be jugglers, magicians, and tightrope walkers, too.” A “juggler” (juggler) is a person who can keep several objects in the air at the same time by throwing them up and catching them and throwing them up again. A “magician” (magician) is a person who uses what we would call “illusions” to make you think something is going on even though it really isn't. That’s sort of what a politician does, I think.
A “tightrope walker” is a person who walks on a high wire, or a rope that is very high up in the air. We mentioned this previously. “Tightrope” (tightrope) is what you call that wire, that rope that the person walks on. Roman says, “Great.” But he says “great” not to indicate that he's happy, but to indicate that he's not very excited about it. He uses the word “great,” but he’s making a joke. He doesn't think it's great. Paula says, “Listen, I can hear the ringmaster from here. Let's go!” The “ringmaster” (ringmaster) is basically the leader of the circus, the person who talks to the audience and who directs the performers to do what they're supposed to do, or at least when they're supposed to do it.
Obviously, Paula is more excited about this than Roman. Roman says, “When you said you had a surprise for me that would make me feel young again, this wasn't exactly what I envisioned.” It's not what I was thinking about. Paula says, “I know. It's even better, right?” Roman says, “If you say so.” Paula is saying that going to the circus is the best thing that she could have given Roman to make him feel young, but Roman doesn't agree.
He ends by saying, “If you say so.” “If you say so” is a phrase we use when you do not believe or agree with what another person is saying, but you're willing to pretend it's true because you don't want to argue about it. You don't want to fight about it.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Paula: Ta-da! We’re here. This is your big surprise.
Roman: We’re going to the circus?
Paula: You got it in one! It’s going to be great. There’ll be clowns and acrobats, trapeze artists and lion tamers.
Roman: I haven’t been to the circus since I was a kid.
Paula: That’s the point. I thought this would be a nostalgic experience for both of us, and let us feel like kids again.
Roman: I’m not sure . . .
Paula: Come on! We’ll miss the first act. I think there’ll be jugglers, magicians, and tightrope walkers, too.
Roman: Great.
Paula: Listen! I can hear the ringmaster from here. Let’s go!
Roman: When you said that you had a surprise for me that would make me feel young again, this wasn’t exactly what I envisioned.
Paula: I know. It’s even better, right?
Roman: If you say so.
[end of dialogue]
The ringmaster of the ESLPod circus is our very own scriptwriter, Dr. Lucy Tse. She's not a clown, but she is a magician when it comes to words.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
ta da – a phrase used when one is excited and proud to show another person something
* Ta da! What do you think of my new sweater? I made it myself!
circus – a type of entertainment with many trained animals and performers who travel from one place to another and perform inside large tents
* The most interesting part of the circus was seeing an elephant balance on top of a large red ball.
to get it in one – to guess the correct answer the first time, without needing to try again and again
* We didn’t think anyone would be able to guess how many beans were in the jar, but the first person got it in one!
clown – a person who dresses is large, colorful clothing, very large shoes, a round red nose, and a colorful wig (fake hair) and does funny things to make other people laugh
* Shane volunteers as a clown at the local hospital to try to make the sick children laugh and forget about their problems.
acrobat – a person who uses his or her body in surprising ways to entertain other people, similar to a gymnast, but often doing things in the air
* Wow! Did you see how that acrobat was walking upstairs on his hands?
trapeze artist – a person who entertains audiences by flying through the air from hanging bars and ropes, often catching the arms or legs of other people
* Kimi could never be a trapeze artist, because she’s afraid of heights.
lion tamer – a person who trains animals to be calm around humans and perform certain tricks
* Daphne has worked as a lion tamer for years, but she has never been scratched or bitten, because she is very careful around the animals.
nostalgic – filled with strong feelings, especially when remembering the past and wishing one could return to some earlier time
* Attending weddings always makes Timothea nostalgic for her own wedding.
act – one part of a larger show or theatrical performance, usually with a beginning and end
* The opening act has to grab the audience’s attention, or they might not stay for the rest of the performance.
juggler – a person who keeps several objects in the air, throwing them up one or more at a time, often while performing tricks to entertain other people
* Ollie is studying to be a juggler. He’s really good with balls and fruit, but he hasn’t yet figured out how to juggle larger objects
magician – a person who uses illusions to make it look like he or she is doing things that are impossible and require supernatural forces; a person who performs magic
* How could that magician have known what card I had in my hand? That’s impossible!
tightrope walker – a person who walks on a small rope high in the air without falling
* Did you hear about the tightrope walker who walked over Niagara Falls?
ringmaster – the leader of a circus; the person whose job is to speak to the audience and describe what is happening and who is performing in a circus
* The ringmaster began the show by saying, “Ladies and gentlemen, boys and girls, welcome to the greatest show on earth!”
if you say so – a phrase used when one does not really believe or agree with what another person is saying, but is willing to pretend that one does and not argue about it
* A: Being outdoors too much is bad for your health.
B: If you say so.
Comprehension Questions
1. Which of these circus performers spends time in the air?
a) Clowns
b) Trapeze artists
c) Lion tamers
2. Why did Paula want to create a nostalgic experience?
a) Because she wanted them to feel what it was like to be a child again.
b) Because she wanted them to relax after a long week at work.
c) Because she wanted them to remember sad times in the past.
Answers at bottom.
What Else Does It Mean?
clown
The word “clown,” in this podcast, means a person who dresses is large, colorful clothing, very large shoes, a round red nose, and a colorful wig (fake hair) and does funny things to make other people laugh: “The company hired a clown to entertain people in between presentations.” A “class clown” is a student who does silly things to make other people laugh, but often as a distraction for the teacher and the other students: “Your son is getting good grades, but he is a class clown and he needs to learn to control his behavior.” Finally, to call someone a “clown” is a sign of disrespect, meaning that one thinks that person is annoying and not very intelligent: “Why are we doing business with these unreliable clowns?”
act
In this podcast, the word “act” means one part of a larger show or theatrical performance: “How many acts are in the play?” The phrase “an act of God” describes a natural event that is not caused by humans: “Does this insurance policy provide coverage for acts of God, like hurricanes and earthquakes?” The phrase “a juggling act” or “a balancing act” describes a situation in which one is trying to do many things at the same time: “Being a parent, a business owner, a musician, and a homeowner is a juggling act.” Finally, the phrase “a tough act to follow” describes someone who does something very well, better than most other people: “Heather was a great CEO, and when she leaves the company it’s going to be a tough act to follow.”
Culture Note
The Evil Clown
Normally a clown is a “humorous” (funny) entertainer who tries to make people smile and laugh. But there is also a cultural image of the “evil” (very bad, connected with Satan or the devil) clown. In movies, the evil clown is usually shown with the same bright colors, “make-up” (painting on one’s face), and large nose as regular clowns seen in movies, but they might have darker, black lines on the face and possibly blood.
“Horror” (a type of book that tries to scare people) writer Stephen King wrote a novel in 1986 called It. In that story, a “mysterious” (not known) creature appears to young children as a clown, but then “terrorizes” (deeply scares) them by “exploiting” (taking advantage of) their greatest “fears” (the things people are afraid of), and in many cases “murdering” (killing) them.
The Batman series has a very well-known clown, the Joker, who does bad things. And the “animated” (drawn in pictures) TV “series” (a group of related shows The Simpsons has an evil clown called Sideshow Bob who is always engaged in “plots” (plans) to do evil things.
Some psychologists believe that children are naturally scared of clowns, because they are reacting to a familiar body shape that has a face that has been painted to be unrecognizable. Other researchers note that the “appearance” (the way something looks or seems) of clowns is similar to that of “demons” (evil creatures, especially in hell), which are traditionally shown with “pale” (very light-colored) faces and a very large, red mouth.
Comprehension Answers
1 -b
2 - a