= 1634
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 329.
This is English as a Second Language Podcast’s English Café episode 329. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. How are you today? Me? Pretty good, thanks for asking.
Visit our website at eslpod.com. You know what to do: become a member, download our Learning Guide, and improve your English as fast as you can.
On this Café, we’re going to continue our series on American presidents, focusing on the 39th President of the United States, Jimmy Carter. We’re also going to talk about the legend of the lost ship of the desert. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a continuation of our series on American presidents. Today we are going to talk about the 39th President of the United States, Jimmy Carter. Jimmy Carter was born in the State of Georgia, in the southeastern part of the United States, back in 1924. He studied at the U.S. Naval Academy; that’s the college where the officers for the U.S. Navy, the part of our military that has ships and boats, go to school. Carter was in the U.S. Navy until 1953, when his father died. Carter’s family needed his help running, or operating, the family farming business after his father had passed away – that is, had died. So Carter left the Navy and returned home to become a farmer.
Carter did very well in the farming business and soon became a wealthy – a rich peanut farmer. A “peanut” (peanut), you may know, is a small, light brown nut. There are two peanuts in each peanut shell. The “shell” (shell) is what we call the outer part of the peanut. We eat peanuts in many different foods, but what is very popular here in the United States is peanut butter, as well as peanut oil. The very famous sandwich that you will find for many children is called a “peanut butter and jelly sandwich,” or a “PBJ.” Many children grow up eating these sandwiches; I did not. I don’t really like the taste of peanut butter. But more importantly, the older members of my family – my older brothers were all allergic to peanuts. If they ate peanuts they would get sick, so my mother never had peanut butter in the house, and I grew up without peanut butter and have never had a peanut butter and jelly sandwich. So I’m very much unusual for that reason, and many other reasons, here in the United States. Farmers in Georgia and other parts of the southern U.S. grow a lot of peanuts, so Carter was not unusual in his business.
While still working as a farmer, Carter became involved on the boards of many local organizations. A “board” (board) is a short way of saying a board of directors. This is the small group of people who lead an organization or a business, who make the important decisions for it, especially a large organization or a large business. Small businesses usually don’t have boards of directors, or if they do, there are only one or two people on them. The boards that Carter was involved in were for schools, libraries, and other government organizations. Then Carter became more interested in politics, and in 1961 he became a state senator and then the governor, or leader, of the State of Georgia.
In the mid-1970s Jimmy Carter decided to run for president. That means he decided to try to get elected to the presidency. However, he had very little national name recognition. “Name recognition” means people know who you are. For example, our former governor, Arnold Schwarzenegger has worldwide name recognition. When you say his name, many people will say, “Oh, yes. I know who that is.” They may not know lot about him, but they have heard of his name. Well, Jimmy Carter did not have name recognition in the United States, not outside of the State of Georgia, so he had to work much harder, and he did. Eventually he became the Democratic Party’s “nominee,” the person they were going to put on the election ballot for president. The “ballot” is the piece of paper you mark when you vote for someone. Nowadays, it’s all done electronically; there aren’t too many paper ballots, though they still exist. In any case, Carter was the Democratic candidate and he won; he beat then-President Ford in the 1976 elections. This was an important election; it was the first election after the resignation of Richard Nixon – President Richard Nixon; we talked about him in café number 280.
Carter became president at a very difficult time in the United States – in the world. There was the beginning signs of a stagflation economically. “Stagflation” is a combination of two words. “Stagnate” (stagnate) is when something is not growing, especially the economy. If things aren’t getting better, if more people are not getting jobs, we might say the economy has stagnated; it’s not getting any better. It’s not necessarily getting any worse, but it’s not improving. “Inflation” is when the price of things go up. “Stagflation,” then, is a combination of those two words, “stagnate” and “inflation,” meaning that not only is the economy not growing but there’s also inflation, the price of things are going up. That was something that people were very unhappy about, and unfortunately, President Carter did not do a very good job of getting the country out of this stagflation. However, we can’t blame him entirely because when he became president there was already this stagflation going on.
More problematic – more difficult for Carter was the foreign policy situation – the international situation. In Carter’s presidency, he had to deal with the Iranian hostage crisis – or Iranian hostage crisis. In 1979, a large group of Americans at the American Embassy in Tehran were taken hostage. “To be taken hostage” means that you are held somewhere by a group of people, or by someone, and you are not able to leave that place. Sometimes hostages are taken for money; the people will take someone hostage and they say, “We won’t give this person back until you give us a million dollars” or “ten million dollars.” Sometimes hostages are taken in order to have some power in a situation; it may be because they want to have more attention – this group. It may be because they want the other government, or the government to release prisoners – to let certain prisoners go.
In the Iranian hostage crisis there were 52 Americans. They were held hostage for more than one year, in fact, for 444 days. They were only allowed to return home to the United States after President Carter ended his presidency, when President Ronald Reagan became president in January of 1981. However, because Carter was unable to free the hostages during that year’s time, many people saw his government – his administration as being inept. “To be inept” (inept) means to be unable to do your job or to do your job well.
However, the Carter administration did have some successes in international relations. The Camp David Accords was an important part of that record of success. An “accord” (accord) is an agreement; it’s sort of like a treaty. It’s an official agreement between two countries. The Camp David Accords were signed by the leaders of Egypt and Israel after negotiating – after talking to each other for almost two weeks in a place called Camp David, which is in the State of Maryland. It’s a place where the president goes sometimes to relax; it’s sort of like a big park. But Camp David was a place where they met and came to this agreement. The Camp David Accords were an important part of the Middle East peace process during the 70s and 80s.
As president, Carter also created some new departments in the U.S. government. He created the Department of Energy and the Department of Education. Education used to be under something called Health, Education, and Welfare – HEW. Then they took Education and made it its own department, and the Health and Welfare part became the Department of Health and Human Services. Carter was also an important figure in supporting the Panama Canal treaties. These were the agreements that the U.S. government had with Panama that returned control of the Panama Canal back to the Country of Panama. The Carter Administration was also responsible for deciding that the United States would not participate in the 1980 Summer Olympics. They refused to participate; we would say they “boycotted” the Olympics because of the Soviet Union’s invasion of Afghanistan. The U.S. did not go to the 1980 Summer Olympics, and the Carter Administration had basically made that decision.
Carter had successes in his administration, but he also many failures, especially with the economy and with the Iranian hostage situation. He tried to become president again in 1980, but he was beaten – he was defeated by Ronald Reagan, who won a very large majority in that year.
Carter was not a very popular president. When he left office – when his term as president ended, only 34 percent of the people thought he was doing a good job. Many people believed he was inept, especially in economic and foreign policy. He was admired after leaving office. In fact, more people liked him after he left then when he was president. It’s probably too early to make a final decision in terms of history about how good a president or bad a president Carter was. However, the general opinion is that he was not a very good president – not the worst president.
As this podcast is being recorded in the year 2012, Jimmy Carter is still alive. In fact, Carter remained very active after leaving the White House, the place where the president lives. In 1982, he created something called The Carter Center in Georgia that tried to improve human rights throughout the world. He and his wife were also very active in an organization called Habitat for Humanity. “Habitat” (habitat) is another word for a place where you live – a house. Carter started an organization – or was very active in an organization that helped build houses for poor people. This was a very popular program; we’ll talk a little bit more about it on a future Café. I have a good friend of mine who was very active in this organization here in Los Angeles.
Carter also continued to work in international relations as a diplomat. A “diplomat” (diplomat) is someone who represents their country in another country. He’s been involved in diplomacy in North Korea, Israel, Syria, Egypt, and Tunisia, just to name a few of the countries.
In the year 2002, Carter received the Nobel Peace Prize for his work. He is one of only four U.S. Presidents to receive that prize; the others are Theodore Roosevelt, Woodrow Wilson, and Barack Obama. Of those four, he is the only one to receive it after he left the office of presidency.
As we record this, Carter is now 87 years old. He continues to write books and give speeches. He is still controversial, especially for some of his views about the Middle East. But he is, as I say, still active, and will be remembered I think both for his unfortunately not very successful presidency but also for the good work he has done since he left.
Now let’s turn to our next topic, which is a legend. A “legend” (legend) is a story, usually told about people who lived many years ago who were very brave. Legends sometimes are made up – sometimes they’re invented, sometimes they’re true. I’m going to talk about a legend from California, a traditional story that people tell.
Here in California, we have something called the Colorado Desert. A “desert” is a large, hot, dry area with a lot of sand and very little rain. We have a legend here in California, a traditional story, that one or more ships are buried in the sand of the deserts in California. A “ship” is a very large boat used to carry people and things over the ocean. Now you say, “Well, Jeff, how is this possible? How can there be the ships in the middle of a desert?” Well, the legend explains why that is.
You see, during the 19th century, in the 1860s, some people began reporting – began saying that they could see part of a ship coming out of the sand in one of these desert areas. Now, these stories were printed – were reported in the Los Angeles newspaper, the Los Angeles Daily News, which still exists. But whenever people went out to find the ship they were unable to do so. The legend has it – that is, the legend says that the ship went back into the desert – went back underground into the sand.
Some people think that this ship is a Spanish galleon. A “galleon” (galleon) is a type of ship that was used by the Spaniards many years ago. Of course, it was the Spanish that first came from Europe to the State of California – what is now the State of California. Some people think that this ship is full of treasure. “Treasure” is a general term for things that are worth a lot of money, like gold coins or jewelry. We often talk about a treasure hunt, where you hide things, and it’s for young children; they go around and try to find these things. A lot of people believe that this ship is full of treasure and that if you find it you will become rich and famous.
Is this story a legend? Is it a true story? Some people actually think the ship is still there, but they think it’s hard to find because it’s on land used by the military for bombing, so you can’t get there. The legend continues to fascinate some people even today; some websites have stories about this legend. I’m pretty sure it’s just a legend – that is, it’s just a story, like the Loch Ness Monster in Scotland and many other things that people say they saw, but, of course, can’t ever actually be proven.
Now let’s answer some of the questions that you have sent us.
Guillermo (Guillermo) in Spain has a question about what we might call informal business English. When you’re talking to someone on the telephone or you’re exchanging emails in English with someone you’re doing business with, you might want them to give you some information – some recent information about what is happening. Let’s say you order a product. You buy something and it hasn’t yet arrived, or they’re still making it, you might want to get some more information during that process – during that time. Guillermo wants to know how you should ask for that information so that it doesn’t seem too formal, but it doesn’t seem too informal. That’s why I say this is sort of a informal business English question.
One phrase that you might want to use, but you should not probably in email, is the expression “tell me something.” “Tell me something” is an expression you can use when you are talking to someone face to face – when they are there in the same room as you, or you are perhaps talking to them over Skype or some sort of Internet telephone service. “Tell me something” means give me a certain piece of information; it’s always followed by another question. “Tell me something. Have you ever gone to dinner at Sakura, the Japanese restaurant?” “Tell me something. Have you ever been to Rome? Have you ever visited the Coliseum?” Notice that I always ask a question after the expression “tell me something.” It’s an informal expression. Technically it’s a command; you are telling the person to tell you something. It’s not something you would use on email.
Email is a new form of communication in many ways. People use it now like they used to use the telephone, and so there are still new ways of communicating that are being established. Email is a place where people often want to be very brief; they want to be as short as possible in their message. However, in a business situation you also want to be polite; you don’t want to sound too aggressive. That doesn’t mean you can never use a command form – that is, the form of the verb in English we would call the imperative, where you are, in some ways, telling someone to do something. You can do that, but first you have to begin your email in a way that’s more polite; you probably want to be a little more informal, not start by saying “give me this information.”
Some polite ways of asking for information would be “keep me updated,” “let me know,” or, “where are we?” Let me start with the first one: “keep me updated.” “To update (someone)” is to give them information about a situation that is going on over a certain period of time. It keeps changing, or it might keep changing, and so you want new information about what the current situation is – what the status is right now. “Keep me updated, please.” You would always want to say “please” so it doesn’t sound too aggressive – too harsh.
“Let me know” is another expression. “Let me know if there is any change in my order. If there is a problem, please let me know.”
Another expression, a little bit more informal, would be “so, where are we?” This can also be followed with the preposition “with.” “Where are we with that order I placed last week? Is it still going to arrive next week?” So, “where are we” is another way of doing that.
You could also say, “Please send me a status (status) update.” “Status” is the current situation, so send me an update about what is going on right now.
Another informal way of asking for information is “How are things going?” Once again, you can follow this with the preposition “with.” “How are things going with my order?” By asking a question instead of telling them – giving them a command, it’s a little more informal, a little more polite.
Finally, you could also say, “Is everything on schedule?” “Is everything on schedule for the order I placed last week?” “Is everything on schedule for that meeting we are having next week? Are you going to be able to be there? (And so forth.) If not, please give me an update about where we are.” That would be a combination of some of those expressions. I hope that helps Guillermo.
Next question is from Wislei (Wislei) in Brazil. Wislei wants to know the meaning of the expression “to start off for.” “To start off for” means that you are leaving one place and traveling to another place. “We started off for San Francisco at seven o’clock in the morning.” We left Los Angeles, and started driving north to San Francisco.
A couple of other expressions we would use in describing travel would be, simply, “to go to.” “I’m going to go to San Francisco.” You could also say “to head (head) for.” “I’m headed for work right now, I can’t talk. I have to get going.” Where are you going? I’m going to work. “What time did you start off for work?” “I started off at seven o’clock.” “To start off for” puts the emphasis on the time or the action of leaving one place and going toward another. “To go to” is more general. “To head for” is similar to “to start off for,” it emphasizes the direction in which you are traveling.
Finally, Francisco (like the city San Francisco) Luis (Luis), from Brazil also, wants to know how we use the terms “likely” (likely) and “probable” (probable). Both “likely” and “probable” can mean the same thing, usually do almost in all cases. It means to have a good chance of being true or of coming true in the future. We’re not certain, but it seems very possible – it seems, well, very likely, very probable. It will almost certainly happen.
Most of these words can be used in the same situations. “Probable” is a little more formal; you might see that more at the university or in an academic paper. There is one difference – major difference between these two words. You can use “likely” in sentences that have the following form: (someone) is likely to do (something). “I am likely to go to the store at two o’clock.” You can’t say, “I am probable to go to the store at two o’clock.” You could use “probable,” but you would have to make it a more impersonal expression: “it is.” “It is probable that I will go to the store at two o’clock.” That means the same thing as “it is likely I will go to the store” or “I am likely to go to the store.” So, in informal conversations “likely” is a little more common; in more formal conversations you are more likely to hear “probable.”
If you have a question, we are likely to answer it, although we get many questions and we can’t answer everyone’s questions. But, you can email us at eslpod@eslpod.com, and we’ll do our best to answer them.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2012 by the Center for Educational Development.
Glossary
peanut – a small, light brown nut, with two nuts in each shell
* Bob likes to eat peanuts with a lot of salt on them.
board – the small group of people who lead an organization or business and make important decisions for it
* Large companies sometimes name important people to their boards so that they can use their influence to help the company.
name recognition – having one’s name known to many people; being famous
* After acting in small roles in two movies, Sandra now has some name recognition and is being offered more acting jobs.
stagflation – a period when there is high inflation and high unemployment and little economic growth
* During a period of stagflation, prices for everyday items go up, but salaries remain the same.
to be taken hostage – to be held somewhere by a group of people, so that one is unable to move or leave, usually until money is paid or some demand is met
* The prison guards were taken hostage by the political prisoners, who demanded to be set free.
inept – without the skill or ability to do one’s job well; having or showing no skill or ability
* If students are failing in school, it is not because of inept teachers, but because there is no money for books and learning materials.
accord – an agreement, especially an official one between two countries
* The United States and Canada reached an accord to make traveling between the two counties even easier.
diplomat – a person who represents another country overseas, often representing his or her own country in negotiations
* At the White House dinner, it is important not to seat diplomats of unfriendly countries next to each other.
legend – a story that is told by many people, usually about very brave people doing magical things that may or may not have actually happened
* There is a legend that this mountain was built by just one giant man very long ago.
desert – a large, hot, dry area of land with a lot of sand and very little rain
* If we were left in the desert without any water, how many days do you think we could survive?
ship – a very large boat used to carry people and things across the ocean or another large body of water
* The ship was seriously damaged during the big rainstorm.
treasure – things that are worth a lot of money, such as gold coins or jewels
* The children believed Grandpa’s story that there is a hidden treasure in the backyard and are digging holes trying to find it!
to start off for – to leave a place with the intention of going to another
* We arrived in Dallas last night, and we’ll start off for Austin after lunch today.
likely – having a good chance of being true or coming true in the future; not certain but with a good chance of something happening
* It’s likely to rain on our trip, so be sure to bring an umbrella and a raincoat.
probable – having a good chance of being true or coming true in the future; not certain but with a good chance of something happening
* It is probable that the U.S. dollar will continue to drop in value over the next year.
What Insiders Know
Dune Buggies
If you live in or near a desert, you may be familiar with “dune buggies,” which are vehicles that look like cars, but with very large and wide wheels. These wheels and the overall dune buggy design allow them to be driven over sand “dunes” (hills of sand or other material, usually formed by wind) and on beaches.
Many dune buggies are built by “altering” (making changes to) a car. The car most often used to create a dune buggy is the Volkswagen Beetle. The popular nickname for the Beetle is “Bug” (insect), and that’s how the dune buggy got its name.
Many people use the Volkswagen Beetle as the “starting point” (beginning; foundation) in building their dune buggy because the car’s engine is in the back of the car, rather than the front. This allows the buggy to have more weight in the rear and “traction” (ability to stay on the road). This is important when traveling over a “shifting” (moving) surface such as sand, rather than a firm surface such as a “paved” (ground covered with a hard material, such as stone or bricks, to allow people or vehicles to travel over it easily) road.
People ride dune buggies mainly for fun, but they can also be used for other, more serious purposes. The U.S. “military” (parts of the government concerned with defense and fighting wars), for example, have dune buggies built for what it calls “Light Strike Vehicles,” to be used in places where desert “patrol” (watching over an area by police or soldiers) or fighting are necessary.