= 1609
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 304.
This is English as a Second Language Podcast’s English Café number 304. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide and support this podcast.
On this Café, we’re going to continue our series on American Presidents, focusing on William (better known as Bill) Clinton. We’re also going to talk about something called Voodoo, as it relates to the State of Louisiana. And, as always, we’ll answer a few of your questions. Let’s get started.
This Café begins with a continuation of our series on American Presidents. Today we are going to talk about the 42nd President of the United States, Bill Clinton. Clinton was born in Arkansas, which is in the central part of the United States, in 1946 and was named William Jefferson Blythe III, but his father died a few months before he was born, and he later “assumed” or took the last name of the man his mother married – his mother married again – that is, he took the name of Clinton.
Clinton was a good student; he enjoyed music, singing, and especially playing the saxophone. When he was just 16 years old, he realized he wanted to work in public service; that is, to work in the government to help people. He ended up going to Georgetown University in Washington, D.C., where he earned his bachelor’s degree in foreign service. Yes, there is a degree in foreign service; Georgetown is famous for its program in this area. He then earned what is called a Rhodes Scholarship to study philosophy, politics, and economics at University College in Oxford, at Oxford University in England. The Rhodes scholarship is the most prestigious scholarship in the United States for a college student; that is, it is the one that is considered perhaps the most difficult but also the one that will always be mentioned when your name is mentioned in the future. Someone who receives a Rhodes Scholarship is called a Rhodes Scholar, and they have included many famous men and women throughout the years.
In any case, Clinton, after he finished his time at Oxford, studied law at one of the best law schools in the country, Yale University. It was there that he met his future wife, Hillary Clinton. As a law student, he worked on several political campaigns helping other people get elected.
After he graduated, he began teaching law at the University of Arkansas. In 1976, he was elected as the Attorney General of Arkansas, who is sort of the most important government lawyer, the person that works for the government and defends the government in the legal system. He, two years later in 1978, was elected Governor of Arkansas. A “governor,” you may know, is the political leader of a state; every state has a governor. Our governor, when this podcast was being recorded, is a man by the name of Jerry Brown, who was actually governor back in the 1970s when Bill Clinton was governor; he became governor again – it’s a long story. Clinton was just 32 years old when he was elected, making him the youngest governor in the United States. He served as governor from 1979 to 1981 and then he lost the next election, but he ran again the next time and served as governor from 1983 to 1992. As governor, he worked hard to improve the economy and educational system in Arkansas.
In 1992, Clinton, who was and is a Democrat, won the U.S. Presidential elections, beating George H. W. Bush and a wealthy businessman named Ross Perot. He won 43 percent of the votes nationally. The Democrats did very well in the elections, and they had control of the legislative part of our government, what we call the Congress. As president, Clinton focused on “fiscal responsibility,” the idea that government should not spend more money than it has received. He supported the North American Free Trade Agreement, more commonly called in the U.S. by its initials: NAFTA. This was an agreement between the United States, Mexico, and Canada that helped increase the business – the imports and the exports among those three countries. He also increased the amount of time people had to wait before buying a gun; he reduced taxes for low-income families and he raised taxes for the wealthiest or richest Americans.
He and his wife also famously tried to reform or change the health care system in the United States, the system of hospitals and doctors that takes care of or should take care of your health. His idea was to give everyone health care coverage, but this failed. In fact, it was a rather dramatic failure. As a result, the opposite or opposing party, the Republicans, took control of Congress after this failure. This reduced or certainly limited President Clinton’s ability to do the sort of things he wanted to do. It was necessary for him to move to what we might call the political center, meaning he had to support laws that were not too liberal, not too conservative, somewhere in the middle.
Clinton was re-elected in 1996. However, his second term, his second four-year period as President, was marred by what became known as the Lewinsky scandal. “To be marred” (marred) means to become less beautiful or attractive. The Lewinsky scandal was related to an affair that Clinton had with a 22-year-old woman, an intern named Monica Lewinsky. An “affair” is a sexual relationship between two people when at least one of those people is married to someone else. President Clinton, of course, was married to Hillary Clinton at the time. Monica Lewinsky, the 22-year-old intern was not. An “intern,” I should mention, is someone who works for a company or for the government; usually they don’t get paid very much, sometimes they don’t get paid anything. They’re usually young college students or those recently graduated from college who are looking to get experience, and Monica Lewinsky was one of those interns.
At first, when the news first came out – was first published that Clinton had this affair, Clinton denied it, saying it never happened, but recorded conversations later made it clear that something did happen. There followed a long investigation, of course, and if you were alive in the late 1990s you certainly will remember it if you followed American news at all.
The House of Representatives actually voted to impeach President Clinton. “To impeach” (impeach) means to accuse an elected government official of a crime and try to punish that person by taking away his or her job. The House of Representatives has only impeached one other president, that was Andrew Johnson back after the U.S. Civil War in the 19th century, in the 1800s. Clinton was impeached, meaning he was accused of being guilty of a crime, mostly of lying about what happened with Monica Lewinsky. The affair was not a crime, but lying about it was. Many people believed that Clinton have lied under oath. “To lie under oath” means to not tell the truth when you are in an official government court when you promise to tell the truth. Before you are a witness or before you give evidence in the American legal system you have to promise to tell “the truth, the whole truth, and nothing but the truth,” as the expression we use goes. However, the House of Representatives in our government system accuses, but it’s the United States Senate that decides whether the government official is guilty or not, and the Senate acquitted Bill Clinton, said he was not guilty, in February of 1999.
Clinton’s presidency was also marred by another controversy called the Whitewater controversy. Many people asked questions about the Clintons’ financial transactions in the 1970s and 1980s, how they spent their money. In the end, Bill and Hillary Clinton were never charged with any crime, there were just people who said they did something wrong.
On Clinton’s last day as President, he did what many presidents do their final days; he issued some pardons. The President of the United States has the authority – the ability to give criminals, people who have broken the laws, pardons. A “pardon” (pardon) is when the U.S. President says that you can leave prison, or you will no longer be officially considered a criminal, even though they were guilty. Pardons can also be issued by the governor of a state for certain crimes. The president has the ability to pardon criminals. However, many of Clinton’s pardons were quite controversial. Of the 141 pardons, some people said that many of them went to people who didn’t deserve it or people who had tried to influence the Clintons, financially or otherwise. But again, there was nothing criminal about what Clinton did, at least not formally, and like a lot of political controversies many of the people who tried to argue that there were some problems were themselves motivated or had political reasons for making these accusations. It’s true with every president, every big political figure.
Despite the Lewinsky scandal and the controversies surrounding Whitewater and the pardons, President Clinton remained and continues to be very popular in the United States. In fact, his popularity reached its highest point, 73 percent, shortly after he was impeached; that is, 73 percent of the people said they approved of the President and what he was doing. These polls – these research studies asked people’s opinions; they showed that people didn’t think Clinton could be trusted – you couldn’t trust him, but he had done a good job as President. Clinton was and is especially popular among African Americans, because he did a lot to try to improve race relations during his presidency.
Since leaving the presidency in 2001, Clinton has remained active in public life. He worked with President George W. Bush, became involved in many disaster recovery efforts, especially after Hurricane Katrina and the Asian tsunami. His foundation – his organization that he started – raises money to fight against HIV and AIDS and tries to find solutions to improve public health, reduce poverty, and reduce international conflict or fighting. Clinton is still very popular, perhaps the most popular Democrat still in the United States.
Now let’s turn to our next topic, which is Louisiana Voodoo, also called New Orleans Voodoo. “Voodoo” (voodoo – one word) is a set of beliefs and actions involving magic that are part of a religion. Voodoo is common in the Country of Haiti, but it is, or least was common in and around New Orleans in the State of Louisiana. Louisiana is located in the south central part of the United States; it’s where the Mississippi River goes into the Gulf of Mexico.
Voodoo has a lot of original African influences. This means that some of the beliefs and practices can be traced back to parts of Africa where the slaves were brought from in the 19th – 18th and 19th centuries. The phrase “to trace (trace) (something) back” means to look back in time and determine when and where something was created. For example, I can trace my interest in applied linguistics to my days as a Spanish student, back in the late 1980s. That’s where it started. African influences on Louisiana Voodoo also include the use of charms. A “charm” is a small, supposedly magical object that is used to provide protection or perhaps even to hurt someone else.
Louisiana Voodoo has also taken on some Catholic influences. Voodoo spirits, or magical sources of energy without bodies, are sometimes named after Catholic saints, or holy people. Voodoo even uses some Catholic prayers, the cross, and the practice of baptism. However, it is not part of the Catholic religion, and in fact, the Catholic religion would very much disapprove of much of what Voodoo does and stands for.
Women known as Voodoo queens lead many of these Voodoo meetings and dances, at least they did traditionally. They also created charms to help people or to hurt people. The most famous Voodoo queen was a woman by the name on Marie Laveau, who was known to have – or thought to have special powers, back in the 19th century, in the 1830s. Even today, some people go to her tomb, the place where she is buried, where her body was put, to ask for “favors,” to ask her to do something for them.
In 1932 there was a movie called White Zombie about Voodoo, but it gave many people the wrong idea about Voodoo; it led them to believe things about Voodoo that weren’t entirely or completely true. The movie emphasized the practice of putting pins into dolls. A “pin” (pin) is a small, long, sharp piece of metal that you use normally in sewing, when you are trying to put two pieces of what we call fabric together, like your clothing. The movie showed Voodoo followers putting pins into little dolls, which look like human beings. And when they did that, the person whom the doll represented then got certain pains where they had put the pin. Voodoo followers apparently do put pins into dolls, but usually it’s to help them rather than to hurt them.
The film certainly increased people’s interest in Voodoo in the 1930s, and many tourists went to New Orleans to learn more about it. There are still Voodoo practitioners, people who are believers in the Voodoo religion, but a lot of what you will see now in New Orleans is very commercial; it exists for the tourists. People charge tourists money to perform these Voodoo services, even if they don’t really believe in it. But there is also a real practice of Voodoo in parts of New Orleans, parts that are not normally visited by tourists.
There are also many superstitions in the Voodoo belief system, we could call it – the Voodoo religion. “Superstitions” are beliefs that certain actions can have certain consequences. For example, if you break a mirror you will have seven years of bad luck.
Now let’s answer a few of your questions.
Our first question comes from Cynthia (Cynthia) in Singapore. Cynthia wants to know the meanings of the words “articulation,” “enunciation,” and “pronunciation.” Let’s start with “articulation.”
“Articulation” can mean the act of speaking words or the sounds that make up words. The verb “to articulate” is usually used to mean to say something clearly, especially if someone is having difficulty hearing you. “Articulate” can also mean, more generally, to take your ideas and put them into words, or your thoughts and put them into words, especially when you may think it’s difficult to do so.
“Enunciation” (enunciation) is similar to the first meaning of “articulation,” it’s pronouncing words or the sounds within words very carefully. Someone may say “enunciate” as a criticism, meaning you need to open your mouth and say the words more clearly. This is a common problem with native speakers, they’re speaking very fast and sometimes not all of the sounds of the words come out. “To enunciate” would be to more clearly say each of those words or sounds within the words.
“Pronunciation” is a way of speaking the words out loud, especially a way that is considered correct according to a native speaker for example. “Pronunciation” would be used, for example, in the case of someone’s name: “What is the proper or correct pronunciation of your name?” As you know in English, the pronunciation of names in particular, or especially, can be very different from the way that they seem to look by the way they are spelled.
“Enunciation” and “articulation,” especially that first meaning of “articulation,” can often be used in the same circumstances. “Articulation” is more about individual sounds, of a letter for example. “Enunciation” is a little more common, a little more general, telling people to speak more clearly in general; “articulation” might be related to some specific sound.
“Pronunciation” is related to talking about how a certain word is supposed to be said out loud. When you “mispronounce” a word, you are saying it in a way that is considered wrong or incorrect.
Our next question comes from Ebrahim (Ebrahim). My apologies if I mispronounced that. Our questioner comes from Iran. The question has do with the meanings of the words “to start” and “to commence.” Well, both “to start” and “commence” mean the same thing; they both mean to begin something. Usually, we use the word “start,” that’s the most common word. “Commence” is only used in very formal circumstances or special situations; it usually sounds too formal in normal conversation. So, “start” would work better, both formally and informally.
There’s a common expression that you might hear Americans say: “Don’t start.” This is used when someone begins to talk about a topic or do something and you aren’t very happy about it; you don’t want to hear about it or you don’t want them to act that way. You may say, “Oh, don’t start,” don’t continue talking about that topic or that subject, it makes me mad or angry.
Finally, Diogo (Diogo) in Brazil wants know the difference between the phrase “I believe you” and “I believe in you.”
“I believe you” means I think what you are saying to me is correct or is true. “I believe in you” means I trust you; I have faith in you as a person; I think that you are good person and that you will do good things.
People say “I believe you” a lot in English. It’s a simple way of telling someone that you think the words that they are saying are true. “I believe in you” doesn’t normally get used much in real life; you might hear it in a movie or on a television show. It’s usually said to someone who is perhaps having difficulties believing in themselves or believing in their ability to do something. You might say it to someone who has a lot of doubts about whether they can do something or not. You might say, “I believe in you,” meaning I think that you can do it; I think you can be successful.
There are two other major uses of the expression “believe in.” One is typically used to talk about a religious belief: “I believe in God,” meaning I believe that God exists. “To believe in” can also mean to think that it is important to do something: “I believe in getting up early in the morning.” That’s something that I consider important. Not really; I…I don’t get up that early, but it’s an example. Or, you could say that the parents believe in hard work for their children. They think that’s important that their children work hard. Or it could be negative: “They don’t believe in watching television every night.” That’s not something they think is important.
We at ESL Podcast believe in helping our listeners, so if you have a question or comment please email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
governor – the political leader of a state; the highest-level political job in state government
* The Governor of Idaho is visiting other states to promote tourism to her state.
fiscal responsibility – the idea that a person, business, or government should not spend more money than it has received
* Until she shows more fiscal responsibility, Hamid is taking away his daughter’s credit card.
to mar – to become less beautiful or attractive; to spoil; to cause something to appear less perfect
* The smooth surface of this table is marred by a cigarette burn.
affair – a sexual relationship between two people when at least one of those people is married to someone else
* Why do so many powerful men have affairs with their secretaries and assistants?
to impeach – to accuse an elected government official of a crime and to try to punish that person by taking away his or her job
* Our group wants to impeach the mayor for not following through on his promise to fix the town’s bridge, and instead, spending money irresponsibly elsewhere.
to lie under oath – to not tell the truth when one has sworn or promised to tell the truth, usually in court or in front of an official government committee
* A judge can put you in jail for lying under oath in his or her court.
pardon – the act where the U.S. President allows criminals to go free without being (fully or completely) punished, even though the court found them guilty
* The political prisoner received a pardon when it became clear that he was put in prison unfairly.
Voodoo – a set of beliefs and actions involving magic that are part of a religion
* I don’t think losing your hair has anything to do with your wife using Voodoo on you.
to trace (something) back to – to be able to look back in time and determine when and where something was created
* Our son’s athletic ability can be traced back to his grandmother, who was an Olympic swimmer.
charm – a small, magical object that can be used to provide protection or to hurt other people in some way
* Cherise carries a penny in her pocket as a good luck charm.
favor – something that one asks other people to do for one to help oneself; something one does for another person to help him or her
* Can you do me a favor? Can you feed my cat for two days while I’m away?
superstition – a belief in the power of the supernatural or things beyond scientific understanding, and that acting in some way will bring a desired result
* Many sports players have superstitions about things they need to have or to do in order to perform at their best on the field or on a court.
articulation – the act of speaking words or the sounds that make up words; the act of putting a thought into words, especially when it is difficult to do so
* The articulation of some sounds is difficult for very young children.
enunciation – the act of speaking words or the sounds that make up words in a very clear way
* When you speak to a large crowd of people while using a microphone, it is important to have clear enunciation to be understood.
pronunciation – the way that a word is said aloud; the making of the sounds associated with a word
* The word “sauce” has different pronunciations in different parts of the country.
to start – to begin
* We’re all here. Let’s start the party!
to commence – to begin, often used in formal situations
* Before we commence today’s meeting, let me introduce our special guests.
I believe you – I think what you are saying is true; I believe you are being truthful
* I believe you when you tell me that your dog ate your homework.
I believe in you – I have confidence in you as a person; I think you can reach your goal
* Because you study so hard, I know you’ll get into the university you want to attend. I believe in you!
What Insiders Know
Krispy Kreme Doughnuts*
While Bill Clinton was serving as the President of the United States, the “press” (news organizations) often mentioned his love of unhealthy foods, such as fried chicken. The president “reportedly” (was said to) liked “doughnuts,” a small fried sweet cake, often “dipped” (put into and then pulled out of) sugar. Bill Clinton’s favorite doughnuts were said to be from a company called Krispy Kreme.
The name of the company is “a play on” (a clever version of) the words “crispy,” meaning that the surface is slightly hard or crunchy, usually from “deep frying” (cooking by placing something entirely in very hot oil), and “cream,” a rich sweet mixture made with eggs.
Although doughnuts sound like a food eaten as dessert, most Americans eat doughnuts for breakfast. Doughnuts come in many shapes and sizes, and many have cream “filling” (food placed inside other food).
Krispy Kreme was “founded” (started) in 1937 in North Carolina, a state in the southeastern part of the U.S. The company became very popular in the 1990s, especially in the southern part of the U.S., where Bill Clinton is from. Since then, the “chain” (store with many locations) has “branched out” (spread to cover a larger space) across the country. For several years in the late 1990s, Krispy Kreme doughnuts became a “sensation” (very popular with a lot of people) and they became the doughnut “of choice” (the most preferred). Now, you can find Krispy Kreme locations across the U.S. and in many countries “abroad” (outside of the U.S.).
* “Doughnut” can also be spelled “donut.”