= 1616
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 311.
This is English as a Second Language Podcast’s English Café episode 311. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. On it, you can visit our ESL Podcast Store, which has some additional premium courses in business and daily English. You can also download the Learning Guide for this episode, and every current episode. The Learning Guide contains lots of additional information, including a complete transcript of this episode.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech – a normal speed. We’re going to listen to them and explain what they are talking about.
Today we’re going to talk about teen athletes and some problems that they have, specifically we’ll be talking about concussions. And as always, we’ll answer a few of your questions. Let’s get started.
Today we’re talking about teen or teenaged athletes. “Athletes” are people who play some sport. We’re going to talk about some the problems that teen athletes have, especially when it relates to concussions. A “concussion” (concussion) is when you get hit on the head, typically, and you lose consciousness; that is, for a second you don’t know where you are, you sort of fall asleep. When you wake up, you’re often confused, you don’t know where you are; there are other symptoms – other signs of a concussion. A concussion is an injury to the brain, and it can be very serious. American athletes – athletes in any country can suffer from a concussion if they are hit on the head. We typically associate concussions with the sport of American football, where people are hitting each other all the time. However, it can happen in any sport.
Today we’re going to listen first to a young man by the name of Dane Harlowe; he’s a 17-year-old high school athlete. He’s going to talk about what happened when he was wrestling. “Wrestling” is a sport where two people, usually two men, grab each other and try to throw each other down, try to keep the other person down on the ground. It, of course, comes from the Greeks, at least that’s who we often associate it with in western culture.
Now let’s listen to Dane. He talks like a typical American high school student, not very clearly sometimes. We’ll listen to him, and then we’ll explain what he said.
[recording]
I kind of backed up a little bit and I told the ref I needed a time out. And so, the trainer came over and checked me and she just wanted to see if I was having any symptoms of concussion.
[end of recording]
Young Dane says that while he was in a wrestling match – that’s what a game, a competition between two wrestlers is called, a “match” – he backed up a little bit. “To back up” means to move your body backwards. He says, “I kind of backed up.” “Kind of” here usually would mean sort of, in a way. But my guess is, like a lot of people speaking informally, Dane is just using this as a filler – as a few words that you say when you are thinking of what else to say, or it could just be the way that he talks. “I kind of backed up a little bit (a small amount) and I told the ref I needed a time out.” A “ref” (ref) is short for “referee” (referee). A “referee” is the person whose job is to watch a game and make sure people are following the rules. In basketball, a referee or a ref looks to see whether players are pushing each other for example. In wrestling, a ref determines when one wrestler has held down another wrestler for a long enough time to win the match. A ref is also looking for illegal moves, things that you’re not supposed to do.
Dane asked or told the ref that he needed a time out. A “time out” is a pause in the game. It’s a phrase that is sometimes used in schools by teachers when students are misbehaving, when they’re yelling and screaming or doing something wrong – which is most of the time! The teacher will then sometimes say to one student, “Johnny, you’re going to get a time out,” which usually means that you take the child and you put them somewhere else – maybe in the corner, in a smaller room, maybe a closet. Well, maybe not a closet! But, you take the child away from the other children; they are getting a time out. Parents sometimes use this. My parents never gave us time outs; they would just yell at us, or send us to our rooms – I guess that’s a sort of time out. You have time outs in lots of different sports. Football has a time out; baseball has a time out. You can ask for a break, a pause in the game for whatever reason. There are limits to how many time outs you can ask the ref for, especially in American football. But the general concept is one that you will find in many different sports.
Well, Dane wasn’t feeling well, so he asked the ref for a time out. Then he says, “And so (and then), the trainer came over and checked me.” A “trainer” is someone kind of like a coach, who works with athletes to make sure that they stay healthy. Trainers often have some medical knowledge; they’re not doctors usually, but they can tell whether someone is hurt or not. A trainer came over to check Dane, to look at his physical condition to see if there was anything wrong with him. “To come over” means, in this case, to walk from one place to another. The trainer checked Dane; she just wanted to see if he was having any symptoms of concussion. A “symptom” (symptom) is a sign, an indication. “Concussion,” as we mentioned earlier, is an injury to the brain that happens when you are hit in the head. Usually someone feels a little sick, maybe a little dizzy, and often will lose consciousness – will not know what is happening or will go to sleep, if you will, for a short period of time. Let’s listen to Dane one more time.
[recording]
I kind of backed up a little bit and I told the ref I needed a time out. And so, the trainer came over and checked me and she just wanted to see if I was having any symptoms of concussion.
[end of recording]
Next we are going to listen to Dane’s father, Dennis Harlowe. He’s going to describe what he saw that day, the day that Dane was injured.
Let’s listen:
[recording]
Dane just laid there face down on the mat with his arms by his side and the kid’s working him and I’m looking and wondering “Why is this continuing? Obviously something is wrong,” and when Coach Sholders said, “There’s obviously something wrong, stop the match,” the ref blew the whistle and stopped it and that was actually – it turned out to be the end of the match.
[end of recording]
Mr. Harlowe begins by saying that Dane, his son, was lying face down on the mat. “To lie face down” means to be on the ground, with your face on the ground – your whole body is on the ground. He was lying face down on a mat (mat). A “mat” is a soft, padded type of flooring that you use for wrestling matches or gymnastics. It’s, for example, when you watch the gymnastic events at the Olympics, when the athletes jump up and down they’re jumping up and down on a mat. It’s like a thick cushion on the floor. In wrestling they use a mat for the sport, that’s where the wrestlers wrestle on.
So, Dane is lying down on the floor, with his face down on the floor. Dennis, the father, says that his son was lying face down with his arms by his side and the kid’s working him. The kid is the other wrestler – the other young man who was in the wrestling match. “To be working him” here means, in this context, to be hitting him, or to be holding him down – that’s really what wrestlers do, they don’t hit or aren’t supposed to hit each other, but they are trying to hold each other, and that’s what’s happening here.
Dennis is confused. He says, “I’m looking and wondering (I’m thinking, I’m asking myself) ‘Why is this continuing (why is the match continuing)? Obviously something is wrong,” and when Coach Sholders (the name of the coach is Sholders – his last name) said, ‘There’s obviously something wrong, stop the match.’” “To stop the match” means to end the match, to end the game. “The ref (the referee) blew the whistle and stopped it.” A “whistle” (whistle) is a small plastic or metal thing – device that makes a loud, high-pitched noise. You will hear a whistle in many different kinds of sports, usually to stop the game or to indicate that there’s some problem. Whistles are also sometimes used by police officers to get people’s attention, although I’m not sure how many police officers have whistles nowadays, but they used to do that.
So, the ref blew – “blew” is the past tense of the verb “to blow,” which means to put air into the whistle from your mouth so that it makes a sound. “The ref blew the whistle and stopped it (meaning stopped the match) and it was actually – it turned out to be the end of the match.” “It turned out to be” is a phrase we use when you realize something only later. “I saw a man and I yelled to him, not knowing who he was. It turns out that it was my brother.” I didn’t recognize him; I didn’t realize it at first, but then later I did. That’s when we use this expression, “it turned out to be.”
Let’s listen once more to Dane’s father:
[recording]
Dane just laid there face down on the mat with his arms by his side and the kid’s working him and I’m looking and wondering “Why is this continuing? Obviously something is wrong,” and when Coach Sholders said, “There’s obviously something wrong, stop the match,” the ref blew the whistle and stopped it and that was actually – it turned out to be the end of the match.
[end of recording]
Finally, we hear from the trainer, Alison Lane, the woman who went to Dane to try to see if there was anything wrong with him.
Let’s listen:
[recording]
An athlete that sustains a concussion will have any number of symptoms: confusion or fogginess, inability to think straight, a headache, nausea, dizziness, feeling off balance.
[end of recording]
Alison says that an athlete that sustains, or has, or gets a concussion will have any number of symptoms, meaning they will have one or more of these symptoms – these signs, these indications. She then gives an example of some of the symptoms. She says that an athlete with a concussion might experience confusion or fogginess. “Fogginess” is when you’re not quite certain where you are; it’s very similar to confusion. The word “fog” (fog) describes a weather condition where there are a lot of clouds close the ground, making it difficult to see. We often get fog here in the west side of Los Angeles near the ocean, and that’s true near many oceans. There’s another expression, “to be in a fog,” which means to be somehow confused or not completely aware of what is going on around you.
Another symptom is inability to think straight. “To think straight” means to think clearly, logically, reasonably. Sometimes if you get excited you’re not able to think straight. When a man sees a beautiful woman he is not often thinking straight; he’s not thinking clearly and logically. This can be very dangerous, as dangerous as a concussion I think!
A “headache” is another symptom of a concussion, where your head hurts. “Nausea” (nausea) is a feeling that you are going to be sick, that you are going to vomit or throw up. That is, the contents – what’s inside your stomach comes up and out through your mouth. Not a pleasant feeling! Nausea isn’t the same as vomiting; it’s feeling like you are going to vomit.
“Dizziness” is another symptom, where you have a feeling that you’re going to fall down or that the world around you is spinning. If you have dizziness, or if you’re feeling dizzy – it’s the same thing – you may feel off balance. “To feel off balance” is to feel like you’re going to fall down. Those are some of the symptoms of a concussion: confusion, inability to think straight, a headache, nausea, dizziness. This is how I feel every morning when I come to work, maybe I have a concussion!
Let’s listen to Alison one more time.
[recording]
An athlete that sustains a concussion will have any number of symptoms: confusion or fogginess, inability to think straight, a headache, nausea, dizziness, feeling off balance.
[end of recording]
Concussions can be very serious. That is, they can cause some serious damage, especially if you have more than one over a period of time. So, a lot of high schools are trying to prevent concussions, and also have more people at these games – more trainers who know what to do and how to determine whether someone has a concussion.
Now let’s answer some of your questions.
Our first question comes from Rainer (Rainer) in Germany. Rainer wants to know the difference between the words “customer” and “client.” “Customer” (customer) and “client” (client) can both be used to refer to someone who buys something from someone else. It could be a physical thing; it could be a service. In American English, “customer” is a little more common when we talk about people buying some thing – some object. “Client” is a little more common when talking about buying some sort of service. For example, you have an accountant, you have a lawyer; you are their client because they provide you with a service, not a thing. If you go to a store and buy some groceries, you’re a customer of the store. We wouldn’t call you a “client” of the store, because “client” is used more frequently for services.
Sometimes people talk about “client” when they’re referring to a larger business. You might, for example, be a bus company, and you go and have your buses fixed, we would say that you are a client of the mechanic who fixes your buses. But if you go in with your individual car they would probably call you a customer, even though it’s a service.
So you can see, there isn’t an exact rule you can follow here. Generally speaking, a “client” is either a large business that buys something from your company or you, as an individual, who is purchasing – who’s buying some sort of service. “Client” sounds a little more formal, a little more polite in some circumstances. But they both mean basically the same thing; you’re buying something from someone else.
That (That) in Cambodia wants to know the difference between the words “overwhelming” and “exciting.”
“Overwhelming” (overwhelming) means very strong, very powerful. It could be a good kind of powerful, it could be a bad kind of powerful. “The winds from the rainstorm were overwhelming. They knocked me down to the ground.” Or, “The smell of her perfume was overwhelming. It was so strong I thought I was going to be sick.” Or you could say, “The support that my friends gave me when I was sick was overwhelming.” It was very strong, it was very powerful.
“Exciting” (exciting) is a feeling of pleasure, a strong feeling, very positive. When we say something is “exciting” we mean it’s interesting, it gets us interested, we feel a lot of pleasure, we are thrilled. We may say, for example, “He leads an exciting life.” He’s always doing fun, interesting things. Or, “This book has an exciting ending.” Something surprising happens, it’s very exciting, it’s very fun, it’s enjoyable.
Finally, Tetsuya (Tetsuya) in Japan wants to know the proper or correct preposition we put after the word “discussion.” Do you say, “it’s a discussion on,” “it’s a discussion about,” “it’s a discussion of,” which is correct?
First, a “discussion” is when two people or more than two people have a conversation; they talk to each other about something, usually it’s a serious conversation. When we’re talking about that kind of serious conversation normally we use the preposition “on” or “about.” “We had a discussion about our plans for a new website.” “The professor had a discussion on race relations in the United States.” Either one can be used, “about” or “on.”
When you use “discussion” to mean a formal speech, as it can be used, or a formal piece of writing about a certain topic, then we would use the word “of.” This is a much less common usage, however. “The governor’s speech,” or “The president’s speech included a discussion of race in American society.” Or, “The professor’s article included a discussion of the changes in civil rights over the last 50 years.” So, it’s a formal piece of writing or a formal speech when “discussion” refers to that sort of presentation of information, not a conversation between two people, then “of” is more common. In the case of a formal speech or a piece of writing, the word “discussion” is really the same as a thoughtful presentation of ideas given by one person who knows a lot about the topic.
One more note, “discussion about” is more common in informal situations, talking about your family or your friends. “Discussion on” would more likely be used in a formal discussion at the university, at your business, and so forth. Both of them refer to conversations between two people or more than two people, but we tend to use “about” more for personal things and “on,” which sounds a little more formal, for business, school, that sort of thing.
If you have an overwhelming need to get one of your questions answered, email us at eslpod@eslpod.com. We cannot promise our answer will be exciting, but we’ll try to give you the correct answer – which isn’t always very exciting!
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2011 by the Center for Educational Development.
Glossary
ref – referee; a person whose job is to watch a game and make sure people are following the rules
* Our coach was really angry about the ref’s decision.
time out – a pause in a game when the coach can speak with the players, advising them on better strategies for winning the game
* If the players look tired, it might be a good idea to call a time out and let them drink water while you give them a motivational speech.
trainer – a person who works with athletes to help them become healthy or stay healthy and perform very well
* Her trainer uses a video camera to record her running style and then analyzes it to help her run faster.
concussion – an injury to the brain caused by being hit on the head or neck
* Melissa didn’t wear a helmet and got a concussion when she fell off her bicycle.
face down – with one’s face, chest, and stomach touching the floor
* How can you sleep face down? Doesn’t that make it hard to breathe?
to work (someone) – to hit another person or otherwise use one’s strength against another person
* The teacher quickly stopped the boys from working their classmate.
match – one game or one competition between two athletes or teams, especially in wrestling, tennis, and soccer
* Who won the final match in the championship?
whistle – a small plastic or metal device that makes a loud, high-pitched noise when held between one’s lips so that one can blow air through it
* Sabrina always carries a whistle when she walks home late at night.
fogginess – the feeling one has when one cannot think clearly, almost as if there are many clouds in one’s head, making it difficult to think
* This medicine may cause feelings of fogginess, so please don’t drive while taking it.
to think straight – to be able to think clearly, logically, and reasonably
* When you’re in love, it’s hard to think straight.
nausea – the feeling that one is going to vomit or throw up, involuntarily pushing substances out of one’s stomach and up through one’s mouth.
* Whenever Sergey travels in the backseat of a car, he experiences nausea.
dizziness – the feeling that the world is spinning around, moving in circles very quickly
* Ninet is afraid of heights and she experiences dizziness whenever she’s in a tall office building.
off balance – feeling as if one is going to fall down
* Do you think you can walk across the river on that log without getting off balance?
customer – a person who buys something, often from a store or restaurant
* Some stores offer discounts to first-time customers.
client – a person who buys something, often keeping a long-term relationship with the seller; a person who uses a professional service
* As a graphic designer, Alan has designed logos for clients all over the world.
overwhelming – very strong or very effective; so powerful as to be impossible to fight
* The candidate has overwhelming support among young Latino men.
exciting – creating a feeling of a thrill or pleasure
* It must be so exciting to travel all over the world!
discussion – a serious conversation between two or more people; a formal speech or piece of writing about a certain topic
* Let’s sit down and try to have a reasonable, logical discussion about our disagreements.
What Insiders Know
Friday Night Lights
Friday Night Lights: A Town, a Team, and a Dream is the story of a high school football team in Texas as it prepares to compete in the state “championship” (an important competition to determine which team is best). The book, written by H.G. Bissinger, was published in 1990. In 2004, it was made into a movie and, in 2006, it became a television “series” (a group of related shows, usually one per week), both of which were titled simply Friday Night Lights.
The story focuses on the football team and its coach, but it is really about how the entire community is affected by the sport and the team. The coach has to make sure the team wins “at all costs” (no matter what else happens), or else he will lose his job and his family will be “unwelcome” (without being wanted) in the town.
The book, movie, and TV series explore the lives of the individual players, showing the struggles they have both “on and off the field” (when they are playing football and when they aren’t). The story also “touches on” (addresses, discusses) “contemporary” (modern) societal issues like “racism” (the belief that all members of a certain race have the same characteristics), school funding, unemployment, drugs, and “abortion” (ending a pregnancy).
Entertainment Weekly, a popular entertainment magazine in the U.S., “ranked” (put in numerical order) the movie as number 37 on its list of Best High School Movies. The TV series was never very popular, but people admired the show for its “portrayal” (way of showing something) of “Middle America” (normal, middle-class families in rural parts of the United States) and it did receive several awards, but it stopped “airing” (being shown on TV) in February 2011.