= 1647
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 342.
This is English as a Second Language Podcast’s English Café episode 342. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Download this episode’s Learning Guide by going to our website and becoming a member of ESL Podcast.
On this Café, we’re going to talk about a famous American movie called Apocalypse Now. We’re also going to talk about what parents do in the United States to get their children into private schools. And, as always, we’ll answer a few of your questions. Let’s get started.
We begin this Café by talking about one of the most famous American movies of the later part of the 20th century, Apocalypse Now. The “apocalypse” (apocalypse) is the end of the world. The idea is that when the world ends, everything will be destroyed – the Earth will be destroyed. Many Christians think of the apocalypse in religious terms as the time when God, in the person of Jesus Christ, will return to earth. Other people think of the apocalypse as a time when perhaps humans will destroy the natural environment, maybe with a nuclear war that will damage the Earth.
The movie Apocalypse Now was directed and produced by Francis Ford Coppola, who also directed a famous set of movies, The Godfather series. Apocalypse Now was made in 1979. I remember it very well; I was a sophomore in high school. It is a movie that is set in the Vietnam War. There were several movies during the 1970s, especially the late 1970s, about the Vietnam War and how difficult and terrible it was for not just the people in that area but also for the American soldiers. Apocalypse Now is “set in” the Vietnam War, meaning that’s when it takes place.
The main character is a U.S. Army officer by the name of Captain Benjamin Willard. He’s played by a young actor named Martin Sheen. Martin Sheen became a very well-known actor in the 70s, 80s, and 90s; he still is. His son is also an actor; in fact, I think he has a couple of sons who are actors. Martin Sheen was also in a famous TV series more recently, called The West Wing.
Well, in the movie, Captain Willard, played by Martin Sheen, is told to kill a renegade officer. A “renegade” (renegade) is someone who leaves an army or leaves a political group and becomes a member of the other side, or simply stops following the orders of the leaders of his group. The renegade officer – an “officer” is one of the leaders in the military, in the army – the renegade officer’s name is Walter Kurtz, and he’s played in the movie by another famous American actor, Marlon Brando. Kurtz, in the movie, has left the army; people think that he has gone crazy, that he’s insane. He’s begun “to command” or to lead a group of native peoples in the Country of Cambodia, giving them orders on how to live and how to fight. He’s sort of acting almost like a god, who has power and control over these people.
Trying to kill Walter Kurtz is dangerous mission for Benjamin Willard. A “mission” is a purpose or what a person or an organization is trying to do. In the military, a mission is usually one part of a larger plan, one objective in a war. In Apocalypse Now, Willard’s mission is to kill Kurtz, and the entire movie is about that mission and all of the strange and terrible things that happen to Willard and his men as they go and try to find this Walter Kurtz.
The movie uses some themes taken from a famous novel called Heart of Darkness, by Joseph Conrad. If you are familiar with the novel, you may recognize the name Kurtz. The movie is famous for, in part, its use of other cultural references. During one part of the movie we hear Wagner’s “Ride of the Valkyries” as the American helicopters are bombing a certain area. The movie also has quotes from T.S. Eliot’s poetry, especially by Walter Kurtz. And of course, there is the amazing acting of Martin Sheen and Marlon Brando, as well as several other very good actors in the movie.
There are a couple of famous lines from the movie, famous quotes that people like to say. One of them comes from one of the soldiers on the mission with Willard. He says, “I love the smell of napalm in the morning.” “Napalm” (napalm) is a chemical substance that is mixed with petroleum – gasoline – in order to start fires. And napalm, in the movie, is used in order to attack a certain area by Willard’s troops. Napalm is, of course, a very dangerous chemical, and only a soldier who is perhaps a little crazy would say that he loved the smell of napalm. It’s sort of like saying you love the smell of death. But the soldier is probably trying to show how brave he is in terms of facing these dangers.
As I mentioned, the movie is also famous for the music, especially Wagner’s music. The music is, in the movie, meant to symbolize a certain triumph; we might call it “triumphant music.” A “triumph” (triumph) is a victory. But of course, it’s hard to see what happens in the film, and in many parts of the war, as anything victorious.
There’s another famous line that Kurtz says. He says, “The horror…the horror…” “Horror” (horror) is something that is frightening, something that is shocking, or surprising. We talk about horror movies, that are supposed to scare you. In Apocalypse Now, it isn’t clear exactly the horror that Kurtz is talking about. It could be the horror of war; it could be the horror that Kurtz has caused by being a renegade and leader of this group of people.
The movie, like a lot of war movies, is about the horrors of war as well, in general. And certainly, if you watch this movie you will see some very violent and difficult things to watch. But that’s part of the point of the movie; the reason of the movie is to show people how horrible war can be.
There were a lot of movies made about the Vietnam War when I was in high school and in college, the late 70s-1980s. Most of them were anti-war films, showing the terrible things about war. This was very different from the movies that were made immediately after World War II, where war was a terrible thing, but there was some goodness in the cause of the Americans fighting in the war. A lot of Vietnam War movies were very critical of the United States; there were a couple of these movies you may have heard of. Another one, which was very good, was called The Deer Hunter.
I won’t tell you the ending of the movie. I don’t like to do that because I’d like to encourage you to try to see the movie, or read, if we’re talking about a book, the book. This is not a book; this is a movie. It’s considered one of the best movies of the 20th century. It won two Academy Award – two Oscars: one for cinematography, the filming of the movie, the other for sound. It also received several other awards, and is considered by the American Film Institute to be one of the top 100 movies of the 20th century.
We turn now to our next topic, which is what parents do in order to get their children into private schools; and we’re talking here about K-12 schools. “K” stands for kindergarten, and “12” is the 12th grade. There are, well, 13 grades; there’s kindergarten plus 12 grades: 1st, 2nd, 3rd, 4th, and so forth. Twelfth grade is the last grade of high school in an American school system.
Anyone in the United States can go to public school, if you live in the United States. But some parents, for a variety of reasons, want to send their children to a private school, a school that is not run by the government. Sometimes it’s for religious reasons. Many times it’s for educational reasons; they think their child can get a better education in a private school versus in one of the government schools.
Private schools are expensive, as you might expect, it depends on where you live. But in large cities, such as New York, Washington, D.C., Chicago, San Francisco, Boston, Los Angeles – any big city really, there are many private schools. Some of them are religious schools. The Catholic Church in the United States has many thousands of schools that it operates. But many schools, especially the more expensive ones, are not religious schools. They’re private schools that may have started as religious schools, but now are mainly schools that try to give students the best education possible, and that’s why parents send their children there.
Many well-educated parents want their children to do well. That’s true for most parents in most places. Parents are often ambitious when it comes to their children’s success. When we say “ambitious” we mean they want them to succeed, they want them to do great things with their life.
Private schools, in order to get into one, usually require that you fill out an application. The application can be very complex and very long, and it is often almost as much work as filling out an application to go to college, at least for some of the better private schools. If the child is transferring from another school, a public school or another private school, the school will want to see how the child performed, so they’ll want to see his or her transcript. A “transcript” (transcript) is a record of all of the grades that you get in your classes.
Sometimes, the application requires an interview, where the parents and the child have to come in and talk to someone and be interviewed by them, just like a job interview. If they’re very young children – three- or four-year-olds – they might be put in a room and be observed by some of the members of the school staff – some of the teachers – to see if the child is someone that, I guess, will be successful at that school. I don’t know what they look for. I suppose any child who has a gun, for example, probably won’t make it into the school – probably!
Parents often have to provide references for themselves and for their children. A “reference” is someone who can talk about your qualifications and talk about, in this case, how smart the child is or how good the child is. Normally, we have references when you apply for a job, people that you say can tell what your good and bad qualities are to someone else. In this case, they are references about how good a student the young boy or girl is.
For “prestigious” schools – that is, schools that are very well respected, perhaps even famous – the application process can be very difficult. Many of the schools will only accept a certain percentage of the people who apply. They only have so much room, and of course there are more people trying to get into the school than there are places for students.
Many parents spend thousands of dollars preparing their children to get into the very best schools. It’s a little bit crazy. In fact some parents, especially in cities like New York and Los Angeles where you have a lot of rich people, spend a lot of money even on young children to get them prepared to get into a very good school. Their thinking is that if they go to a good grade school, they’ll get into a good high school, and if they go to a good high school, they have a better chance of getting into a good college, and so forth. Many parents give their children a lot of additional educational experiences. They’ll send them to ballet class or have them take extra math tutoring. During the summertimes they’ll send them to colleges and universities that have special programs for grade school and high school students. It’s really an entire what we might call “industry,” an entire business surrounding preparing children to get into these private schools, and then, of course, preparing them to get into the university – to college.
Many private schools have their own exams, examinations that students have to take, and they have to get a good score in order to get into, say, a high school – a private high school.
The better the school – the more prestigious the school, the more expensive it is to go there. Some schools can cost now 15-20,000 dollars for one year of schooling. In fact, I think many schools now are even more expensive. That’s not true for all private schools. I’m talking about the very best ones, the most prestigious; we might say the most “exclusive,” the ones where celebrities and people with a lot of money send their children. There are many other private schools that are smaller and much more affordable – cost a lot less money. Though, of course, the cheapest school is always going to be the public school – the government school, where you don’t have to pay any money to study there, at least there’s no tuition.
Now let’s answer some of the questions that you have sent to us.
Our first question comes from Keisaku (Keisaku) in Japan. The question has to do with the phrase “relating to” and “related to.” What do these mean, and how do we use them? Well, both “relating to” and “related to” can mean having some connection with another thing, some relationship, having to do with something else. “The president gave a speech related to the economy.” Or I could say, “The president gave a speech (a talk) relating to the economy.” They mean the same thing there.
“To be related to” can also mean to be part of someone’s family, either because you’re the blood relative – a son, a daughter, a cousin – or you’re related to someone by marriage. So, I am related to my wife’s sister not by blood, we don’t have any common parents or grandparents, but I am related to her by marriage because she is my sister-in-law, she is my wife’s sister. So that’s one meaning of “to be related to.” We wouldn’t say, “I am relating to,” we would say, “I am related to,” with the “ed” at the end.
If you say “relating to” it can also mean to react to someone or to something. “Kids who have problems in school sometimes have difficulty relating to others.” Getting along with is the idea: being able to talk to them, being able to be friends with them, and so forth.
Our second question is from Tatsuro (Tatsuro), also from Japan. Tatsuro wants to know the meaning of an expression that he read in a story, the story of Peter Pan. The expression was “Down with the king.” The phrase “down with (someone)” is used to mean we want to get rid of this person; we want to do away with them, we might say; we want that person to be gone. So if I say, “Down with the king,” I’m against the king; I want to get rid of the king. I could say, “Down with taxes,” or, “Down with Apple computers,” meaning I don’t like those things; I don’t want those things. Normally, however, it’s used when we’re talking about the leader. It’s an old expression; you probably wouldn’t hear anyone say that anymore. In the United States, you would never hear that expression because we don’t have a king, of course. You could say, “Down with the president.”
There are other expressions that use “down with” that mean very different things. “To be down with” is a slang, more modern expression of the last, I don’t know, 20-30 years, to mean you agree with someone. It’s probably already a little old fashioned. When you say, “I’m down with that,” you mean yes, I will do that, I’m interested in doing that. I think that has already become old fashioned, like a lot slang, it changes quickly. I don’t think a lot of people say that anymore. Could be wrong.
Our final question comes from Lyuba (Lyuba) – I apologize for mispronouncing the name – from the beautiful Country of Russia. The question has to do with the word “qualify” (qualify). What does “qualify” mean?
There are a couple of different meanings. The first one means that you are a member of a certain group, you have the characteristics of a certain group. “My son is having problems reading, and he qualifies for additional help in school.” Because of his characteristics he is able to get extra help; he qualifies for that help. I don’t have a son, but if I did I could use that example.
“To qualify” also means to be good enough to perform some sort of job – some sort of profession. We might say, “I am a qualified teacher.” That often means not only can I do it, but I have some sort of official license or some certificate that says I am able to do that. Or, you can just use it as an adjective to describe someone who is good at what they do. “He’s a qualified plumber.” He is able to do that job.
“Qualified,” finally, can also mean to make something a little less serious, a little less critical. “I want to qualify my comment.” Maybe you’ve made a negative statement; you’ve said something critical about someone else. And then, you try to say something nice, or you try to maybe change the meaning of what you said. “I’d like to qualify that remark.” So if I say something like, “I hate cats,” and then later I see that you’re upset. I say, “Well, let me qualify that. I don’t hate all cats. I just hate live cats.” That’s a qualification, you see, I’m making it a little less critical.
If you have a question or comment related to something you read, perhaps, or something you heard in English, email us. Our email address is eslpod@eslpod.com. Unfortunately, we don’t have time to answer everyone’s questions, but we’ll do our best.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse, copyright 2012 by the Center for Educational Development.
Glossary
apocalypse – the end of the world, when many or all people die and there is a lot of damage; complete destruction of the world
* If our two countries started a nuclear war, it may lead to an apocalypse.
to be set in – for a film or story to take place in a particular time or place
* This novel about several influential American authors is set in Paris in the 1930s.
renegade – a person who leaves and betrays an organization, military group, or political group
* Jeb believed that what his country was doing was wrong and became a renegade to try to stop its military operations.
to command – to lead a group; to be the leader of a group
* Laurel has a very strong personality and was born to command a large organization.
mission – a purpose; what a person or organization is trying to do
* Our group’s mission is to get more people registered to vote in state and national elections.
horror – something very frightening, shocking, and surprising
* Don’t read to the children any more horror stories! They’re having nightmares at night.
napalm – a substance that is mixed with petroleum or other fuels to light fires, used especially in weapons such as bombs
* Many soldiers suffered from health problems related to napalm when they returned from battle.
triumphant – having won a battle or contest; being the winner of a battle or contest
* After losing three years in a row, Rose was finally triumphant in the horse race.
ambitious – wanting to achieve something special that most people cannot or will not achieve
* Karim has always been ambitious, first earning a law degree and now going to medical school.
transcript – an academic record showing a student’s performance from a school he or she previously attended
* This transcript shows which courses she took in college and the grades she earned in each one.
prestigious – very well respected; respected and admired
* Bernard never cared about earning prestigious awards. He only wanted to write music that expressed his creativity.
reference – a person who can provide information about one’s qualifications, personal characteristics, and other things, usually needed for school or job applications
* Two of Sue’s former professors served as her references when she applied for a government scholarship.
relating to – having to do with; being connected to
* Karla handles all of the office matters relating to contracts with new clients.
related to – having to do with; being connected to; connected within a family or through marriage; reacting to someone or something
* Neeta’s memory problems are related to her accident.
down with – get rid of; do away with
* Down with greedy banks! We need banks with lower fees and better services.
to qualify – to have the traits of a certain group and to count as a part of that group because of it; to get very good at something, usually in order to perform a certain job; to make less harsh or severe
* If your parents don’t make very much money, you might qualify for a school loan or scholarship.
What Insiders Know
Heart of Darkness by Joseph Conrad
In today’s episode of the English Cafe, we talked about the movie Apocalypse Now. The film was based, “in part” (some but not all), on a “novella” (short novel; short book) by an author named Joseph Conrad.
Joseph Conrad was born in Ukraine in 1857, and his real name was Józef Teodor Konrad Korzeniowski. His father was a writer, who was “exiled” (not allowed to stay in his native country) for political reasons.
Conrad later moved to England and changed his name. He was of Polish “descent” (heritage) and only became fluent in English in his 20s. Before “settling in” (begin living in) England, he led a very interesting and adventurous life as a “seaman” (man who works and sails on ships).
Conrad’s novella Heart of Darkness was published in 1903. The novella is “narrated by” (told from the point of view of) a man named Charles Marlow. He is an Englishman hired by a trading company to be the captain of a ship in Africa. His job is to “transport” (move) “ivory” (the tusks of elephants and other animals) down a river, but he is also given the job of bringing back another ivory trader named Kurtz, who used to sail for the company, but who never came back. The novella is about several types of darkness, including the darkness of a person’s heart and the “evil” (immorality; very bad things) that is there.
Today, Heart of Darkness is considered a “classic” (old and well respected). It is often on lists of the most important books in the Western world and Joseph Conrad is considered one of the greatest English-language writers.