
= 000. Introduction  介绍
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 释义

Hong Kong was arguably the most important place in China for more than 150 years, however, precisely because it was not politically part of China. Sun Yat-sen, the man who led the revolution that toppled the last Chinese dynasty in 1911, was educated in colonial Hong Kong. The father of modern Chinese law, Wu Tingfang, was raised and educated in Hong Kong, where he was better known as Ng Choy. From its early colonial days, Hong Kong served as a haven for Chinese refugees: during the Taiping Rebellion (1851–1864), after the republican revolution of 1911 and throughout the turbulent 1920s, after the outbreak of the Sino-Japanese War in 1937, and after the Communist revolution of 1949.

Hong Kong has been China’s most critical link to the rest of the world.   Until recent decades, about 90 percent of all Chinese emigrants went through Hong Kong.

After the Communist revolution of 1949, capitalist Hong Kong played an important and ironic role in building China’s Socialist economy: as a window to the outside world, as a center for remittances from overseas Chinese that provided valuable foreign exchange, and as a base for importing goods that China could not produce. Hong Kong was of particular use to the Chinese during the Korean War, as scarce goods such as gas, kerosene, and penicillin were smuggled in during the American and United Nations embargoes.


Until the early 1970s, governors were selected from the British colonial service and had served in other colonies before coming to Hong Kong. Alexander Grantham, governor from 1947 to 1957, had worked for the Hong Kong government in the 1920s and 1930s and had served in Bermuda, Jamaica, Nigeria, Fiji, and the South Pacific before returning to Hong Kong. In the 1950s and 1960s, Hong Kong received a group of colonial “retreads,” second-generation colonial servants transferred from the recently independent British colonies and dependencies in Africa, South Asia, and the Middle East. From top to bottom, Hong Kong’s government was a colonial one. For example, as late as the 1960s, the Hong Kong police force was organized along traditional colonial lines. Most of its senior officers were expatriate veterans from Africa, Malaya, and Palestine, while junior officers were generally Chinese.

Although many Americans, especially during and after World War II, viewed the idea of empire with distaste, they became less critical during the Cold War, when colonialism appeared preferable to the spread of Communism. Hong Kong thus became of great use to the United States as a listening post on China, a base for anti-Communist propaganda, and a popular destination for rest and recreation for American servicemen during the Korean War and the Vietnam War.

Despite a relatively high degree of personal freedom, for example, until the late 1980s and early 1990s Hong Kong had no political representation or political parties.

'''



== pure

Hong Kong was arguably the most important place in China for more than 150 years, however, precisely because it was not politically part of China. Sun Yat-sen, the man who led the revolution that toppled the last Chinese dynasty in 1911, was educated in colonial Hong Kong. The father of modern Chinese law, Wu Tingfang, was raised and educated in Hong Kong, where he was better known as Ng Choy. From its early colonial days, Hong Kong served as a haven for Chinese refugees: during the Taiping Rebellion (1851–1864), after the republican revolution of 1911 and throughout the turbulent 1920s, after the outbreak of the Sino-Japanese War in 1937, and after the Communist revolution of 1949.

Hong Kong has been China’s most critical link to the rest of the world.   Until recent decades, about 90 percent of all Chinese emigrants went through Hong Kong.

After the Communist revolution of 1949, capitalist Hong Kong played an important and ironic role in building China’s Socialist economy: as a window to the outside world, as a center for remittances from overseas Chinese that provided valuable foreign exchange, and as a base for importing goods that China could not produce. Hong Kong was of particular use to the Chinese during the Korean War, as scarce goods such as gas, kerosene, and penicillin were smuggled in during the American and United Nations embargoes.


Until the early 1970s, governors were selected from the British colonial service and had served in other colonies before coming to Hong Kong. Alexander Grantham, governor from 1947 to 1957, had worked for the Hong Kong government in the 1920s and 1930s and had served in Bermuda, Jamaica, Nigeria, Fiji, and the South Pacific before returning to Hong Kong. In the 1950s and 1960s, Hong Kong received a group of colonial “retreads,” second-generation colonial servants transferred from the recently independent British colonies and dependencies in Africa, South Asia, and the Middle East. From top to bottom, Hong Kong’s government was a colonial one. For example, as late as the 1960s, the Hong Kong police force was organized along traditional colonial lines. Most of its senior officers were expatriate veterans from Africa, Malaya, and Palestine, while junior officers were generally Chinese.

Although many Americans, especially during and after World War II, viewed the idea of empire with distaste, they became less critical during the Cold War, when colonialism appeared preferable to the spread of Communism. Hong Kong thus became of great use to the United States as a listening post on China, a base for anti-Communist propaganda, and a popular destination for rest and recreation for American servicemen during the Korean War and the Vietnam War.

Despite a relatively high degree of personal freedom, for example, until the late 1980s and early 1990s Hong Kong had no political representation or political parties.

'''




















