
= 2-04 香港与内地的政治互动
:toc: left
:toc-title: 目录
:toclevels: 4
:sectnums:
:stylesheet: ../../myAdocCss.css
:pdf-font-family: Microsoft YaHei UI


'''

== 中法战争时

在1850年代末至1860年代初, 法國以保護天主教傳教士和修道院為由, 出兵越南. 越南向清廷求助. 导致1880年代初, 中法在中越邊境爆發零星戰鬥. 这也引起了香港华人对法国的民族情绪, 并由于某些事件, 香港华人的矛头扩大至殖民地政府, 进行罢工.   +

但清廷并不想华人闹大. 因为: +
- 清廷和法国打仗的军费, 是来自香港銀存的貸款. +
- 所需的武器彈藥, 也是從這個殖民地進口. +
- 他們更不想刺激英國人, 以免英法兩國聯手. +

'''

== 香港與辛亥革命

==== 香港爲革命黨人提供的有利條件

和其他殖民地的政府一樣, 香港政府無心插柳助長了華人民族主義的成長:

- 雖然為免鼓勵排滿或革命情緒 (這樣會激發中國政府對香港的回收態度), 港府不在本地學校教授中國近代史. 但是, *殖民地教育的課程內容, 包括"議會政體"等課題, 因而能鼓勵學生思考政治, 塑造了他們的政治意識.*
- 此外, 在中央書院這類學校中, 學生能接觸到不同國籍和背景的師生, 學校圖書館藏有來自世界各地的書刊, 能擴大學生們的政治素養眼界.

雖然港府致力不讓香港成為巔覆基地, 但這個殖民地還是成為中國革命黨人 招兵買馬和受訓的根據地.

- [貿易自由]: 香港是自由港, 可以輕易取得來自日本和西方的軍火
- [新聞自由]: 由於香港有較大的新聞自由, 革命報章都在香港出版, 並發行到海外華人社會. 它們不單在此地與保守派報章論戰, 反駁它們提出在中國實行"漸進改革"的主張, 還可以公開鼓吹革命.
- [盟友圈]: 這個殖民地還有大量支持革命黨人的本地組織.

- [避難地] 香港也充當了華人改革家和革命黨人的庇護所: +
-> 孫中山在1895年起義失敗後, 就避禍於此. +
-> 1898年夏天推行的"百日維新"失敗後, 維新派領袖康有為, 在英國政府協助下流亡香港.

香港政府支持中國的政治變革, 但它要小心地來走鋼絲. 英國政府命令殖民地政府不要讓香港變成顛覆基地, 但港府也不能完全鎮壓革命活動, 以免華人子民離心. 香港政府也沒有試圖取締"興中會"這些革命組織.

- 但在1896年3月, 廣州當局要求把一名孫中山追隨者引渡到中國, 港督羅便臣拒絕. 但他向孫中山提出, 限制他五年內不得進入香港.
- 同樣, 1899年10月維新派康有為回到香港, 清政府以他陰謀顛覆清廷為由, 要求將他驅逐. 英國外交部認為, 容許康有為留在香港, 可能會授人以柄, 其他國家會以此指摘英國助長中國的叛亂. 外交部最後決定, 以新加坡較安全為由, 婉轉地建議康有為前往新加坡.

'''

==== 香港对中国革命的热情, 是有限的

*不過, 我們不能過於高估香港對中國民族主義壯大, 所發揮的作用.  因為香港人對於中國所發生事件的關注, 充其量只是「半溫不熱」. 革命刊物存在的時間全都不長.*

雖然革命記載把香港描繪為"革命的孕育地", 但事實上: +
- 《中國日報》那些報章的影響力很小. +
- “興中會”在1895 年和1900年起義失敗後, 就鋭氣頓失. +
- "同盟會"香港分會的活動, 並非如這些記述所說的那樣廣泛和有效果. +
- 1919年的辛亥革命, 香港也沒有參與策動. +

'''

==== 孫中山与香港

孫中山在香港受教育.  孫中山在1923年在香港大學演講, 就說過他的革命思想發源地「即為香港」. 他說, 香港的秩序整齊而安穩, 與中國的混亂腐敗成強烈對比, 「我恆默念……何以如此不同?外人能於七八十年間在一荒島上成此偉績, 中國以四千年之文明乃無一地如香港者, 其故安在?」

他在檀香山唸書時, 在當地創辦了"興中會"(1894年11月24日). 1905年又在東京創立了"同盟會". +

孫中山及其革命黨人, 能在香港籌劃一連串秘密活動. 如1895年第一次廣州起義, 就是在香港策劃的.

'''

==== 辛亥革命

在1911年10月10日 (*1911年就是农历辛亥年，清宣统三年. 宣统是清朝末代皇帝溥仪的年号，前后共三年*), 駐紮武昌的一支清廷新軍部隊起義, 奪取了城內一個軍械庫. 其後, 兩個鄰近城市中的革命黨人聞風而動, 相繼發難, 武昌宣佈獨立. 這觸發各地紛紛響應, 兩星期內有十省宣佈獨立, 及後其他各省也陸續脱離清政府.  +
1912年1月1日, 起義軍成立中華民國, 定都南京, 並推舉孫中山為臨時大總統. 革命後, 香港也成為前清遺老避難之地.

革命黨人為了令外國列強保持中立, 不鼓勵排外情緒, 但許多在港華人認為, 既然已驅除滿人, 接下來應該輪到英國人. 香港各處爆發暴亂. 被警察拘捕的人太多, 以致監獄當局在一些囚犯刑滿前就釋放他們.  +
這場民眾動亂為時很短暫, 原因在於: +
1.它的發動主要局限在香港低下階層. +
2.新成立的廣州政府, 表明不予支持. +
3.香港華人精英雖然支持革命, 但不想它損害香港的經濟和政治穩定. +

不過, 辛亥革命後, 香港政府對中國和香港的革命活動感到憂慮. 港督梅含理在1913年制定《教育條例》(Education Bill ), 要求所有私立學校向政府登記, 目的是要防止這些學校變成反英宣傳基地.

北洋軍領袖袁世凱, 在1912年3月取代孫中山成為總統. 雖然袁世凱致力維持秩序和統一, 並推動中國現代化, 但他對於保住自己的權力同樣不遺餘力. 1913年他刺殺國民黨領袖, 鎮壓孫中山領導五省反袁的二次革命. 翌年袁世凱解散各省議會. 他聽信美國政治學家之言, 認為中國還沒有條件實行民主後, 在1915年復辟稱帝. *袁世凱於1916年去世, 但在他死前, 中國的權力已開始流到軍閥和軍事領袖之手. 中國遂陷入政治上四分五裂的局面, 直至1920年代末.*

'''

==== 辛亥革命对香港的影响

到了 1913年, 許多香港華人對於孫中山已熱情不再.

辛亥革命為香港帶來太多煩擾：

- 每天都有大量難民從中國湧入, 到了1914年, 香港人口達到五十萬.
- 這場革命也根本改變了香港與中國的政治關係. 因為北京政府只是名義上統治中國, 香港政府須與廣州此起彼落的歷屆政府直接打交道, 其中幾個廣州政府, 還試圖破壞香港的政治和經濟穩定.
- 因為英國外交部繼續承認在北京掌權者為中國合法政府, 這常引致外交部和香港政府之間的摩擦.

*由於中國缺乏强而有力的中央政府, 有些香港商人為保護在大陸的生意, 就試圖影響中國政情.*

許多本地華人 （尤其是富有居民）是依賴於香港的殖民地環境, 賺取財富, 香港的穩定, 與中國的動盪, 形成強烈對比, 令他們對香港產生愈來愈強的認同感. 一位在二次大戰前夕訪港的西方政治學者觀察到：「中國多年以來一直動盪不安, 是造就一種"視香港為家"的華人階級的因素之一. 」



'''

== 1920年代

中國國內竭力爭取政治統一, 隨之而來的是, 要求廢除不平等條約、治外法權, 和外國租界的呼聲也愈來愈高. 這種激盪的民情, 雖然沒有在香港引起任何重大的反殖民運動, 但卻令1920年代成為香港歷史上政治最動盪的歲月.

'''

== 國共內戰時期

在整個國共內戰期間, 香港事實上是共產黨活動的重要基地.  中共利用這個殖民地的安全環境, 培訓幹部, 並「有組織和持續地」從本地學校和工廠, 招募黨員.

'''

