


= 3-02  (cn) hong kong history 移民
:toc: left
:toc-title: 目录
:toclevels: 4
:sectnums:
:stylesheet: ../../myAdocCss.css
:pdf-font-family: Microsoft YaHei UI


'''


== (移民) 移入香港

=== 最早移民来源

- 在香港開埠初期, 前來此地的華人, 大都來自低下階層, 如勞工, 工匠 , 受排擠的蜑(疍dàn)家人(一种以船为家的独特渔民社群,到处漂泊,又被称为“水上的吉卜赛人”), 娼妓, 無業遊民和私梟.  +
這些人甘於違反廣州當局"嚴禁與外國人合作"的命令, 顯示當時中國的惡劣境況, 以及英國殖民統治所提供的機會.

- 早期歐籍人, 也包括一小撮無業貧民、流浪漢, 和被放逐之人 ——通常一是被解僱的水手, 逃兵, 或罪犯.

在1850年代中期, 女性只佔香港人口的1/4 至 1/3.


从事的职业:
[.small]
[options="autowidth" cols="1a,1a"]
|===
|男 |女

|勞工階層的歐籍人, 主要包括:

- 警察、政府督察、 +
- 士兵、海軍和商船水手、 +
- 監工和領班、 +
- 機械技工、工匠 +
|- 娼妓
- 有些歐籍女人以僕人或保姆為業, 很少數則自己開店, 售賣洋裝和女帽.
|===

他們來香港工作, 主要是因為這裏的工資比英國高.



在香港開埠初期, 歐籍人面對許多問題. 其中很重要的是他們的死亡率很高, 要是因為”瘧疾”等熱帶病所致.

*英國人比起其他社群, 更為執著於社會地位.  社會學家認為, #香港的英國人之所以如此執迷於社會地位, 主要是因為大多數香港的英國人, 其實是來自英國中產階級(而非上层人), 儘管他們不願承認, 並假裝並非如此.#* +
與英國人相比, 葡萄牙人較多與華人通婚, 還會說粵語.

*香港跟印度那些英國殖民地不同, 此地沒有真正的貴族.* 香港的英國官員和商人, 在社會地位上頗為平等.

'''

=== (19世纪50-60年代) 太平天国动乱时期 -> 难民移入

香港一直是内地逃难百姓的庇护所. 如太平天国时期(1851-1864), 辛亥革命后(1911)和整个动荡的1920年代, 抗日战争爆发后(1937), 中共建立政权后(1949). (#*逃避戰亂, 動亂, 與饑荒*#)

[.small]
[options="autowidth" cols="1a,1a"]
|===
|難民:
|#*太平天国起事时, 许多中国商人为逃避太平军, 而来到有大片西方租界而受保护的上海, 及香港*# (1850年代初).  +
这些新移民, 不乏殷商富户, 带同家人, 资金, 营商手段和商业联系到来, 这也帮助香港摆脱了经济萧条的困境.

|外商:
|香港经济的成长, 也同时吸引了新的外国投资. 美国和葡萄牙公司, 都从澳门和广州迁来 (1850年代末至1860年代初).
|===

'''

=== 1880年代末至1890年代 -> 欧洲人移入

一批新的移民遷到這個殖民地, 他們是來自澳洲、加拿大和美國的華僑.

他們移居香港是因為:  +
1.英國自治領, 實施限制性的"移民法",  +
2.美國在1882年制定”排華法案”.

'''

=== 辛亥革命後

#*辛亥革命後中國局勢混亂, 令富有華人企業家大量湧入香港.*# +
來自廣東的華人每年蜂擁而至的情況, 一直維持到1941年日本侵略香港.

'''

=== 日本侵華時期

日本在1937年7月全面侵華. 在1938年10月, 蔣介石撤退至重慶. 同月, 日軍登陸距離香港東北只有三十英里的大亞灣, 兩周內攻陷廣州. #*香港成為逃避日本侵略的難民庇護所*#（單單在1938年就有約50萬人）. 許多中國報社也遷到香港.

- 香港也是輸入中國抗戰所需軍火的主要來源.  +
- 而本地組織, 如香港華商總會籌賑會、中國婦女兵災籌賑會、香港中國婦女會, 都協助籌款支持抗戰.

'''

=== 1949年前後

- 到1940年代末, 中國大陸的企業家**#為逃避內戰和共產黨統治, 來到香港.#**
- 1946年到1950年代中期, 約有100萬人從中國來到香港——平均每天近三百人. 雖然殖民地政府在1950年5月限制來自中國的移民數量. 但到了該年年底, 湧入的移民把香港人口推高至將近200萬.
- 1951年2月, 中國政府開始限制人民移往廣東, 減低南遷香港的人數,
- 到了1955年, 香港人口已約有250萬.

'''

=== 香港在冷戰中的作用

杜魯門總統在1949年冬天至1950年, 陸續關閉美國在華大使館和領事館後, 領事和匯報工作就遷到香港.

之前, 儘管美國過去對香港曾很感興趣, 但到了第二次世界大戰時, 美國已不再重視香港. 美國出口到香港的貨品微不足道, 這個地區似乎也沒有什麼軍事價值(並非戰略要地, 如海峽口).

然而, 中共奪取大陸和1950年韓戰爆發, 迫使美國重新估量香港的戰略價值: +

- 香港是蒐集情報, 策劃對華秘密行動的理想地點.  +
- 此外, 由於冷戰升級, 美國覺得可以利用現有和從前的殖民地, 來協助圍堵共產主義. +
- 香港是美國海軍的熱門渡假休整地點, 其後在越戰期間也是.  +
過去歐美旅客到香港旅行, 是為一睹邊界彼方的共產中國, 還有保存在”新界”的傳統中國社會.

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|香港難民的生活狀況:
|英籍教育家、社會運動家兼前立法局議員, 杜葉錫恩( Elsie Elliot)在1951年來港.  當時是傳教士的她, 與木屋區居民住在一起. 這些難民家庭:

- 女人:  +
許多這些家庭中的婦女是繡花工, 即使她們「從早到晚」工作, 「掙的錢也不夠養活一個人」. 他們的小屋裏只能點盞小油燈, 天黑以後根本幹不了活. 所以他們只好坐在門口, 眼睛湊近細細的絲線, 竭力捕捉最後的亮光. 」有些女人「四十歲就幾近失明」.

- 男人:  +
男人還得到別處找活幹.

- 小孩:  +
要想全家有口飯吃, 孩子也得去掙錢. 「於營養不良, 加之居住環境濕熱難耐, 大多數孩子, 包括最小的娃娃在內, 都患有大塊的疥瘡, 和皮膚感染.」

|香港政府沒有更盡力照顧大陸來港難民的原因是:
|- 它認為一旦中國局勢穩定, 這些人就會返回中國.  +
- 許多殖民地官員擔心, 提供太多社會福利, 會吸引更多大陸難民來港.
- 安德葛說：「沒有人逼亞裔人(尤其是中國人)來港. 他們來了以後無論境況如何都得(自願)接受. 」
|===


'''

=== 60年代 -> 文革难民移入

香港人口自1960年以來, 由約400萬躍升至近500萬. 這些新增人口, 大部分是在釀成巨災的##**中國"大躍進"（1958年至1961年）, 和其後的"三年饑荒"時期來港.**##  +

- 據估計單單在1962年就有約15萬名難民湧入.
- 1962年5月, 約6-10萬內地人, 在中國邊防守軍協助下, 非法越過邊界（雖然一個月內約6萬人被捕和遣返）. 香港警察和英軍其後在英方界線後, 築建起鐵絲網圍欄.

本地身份認同, 其實早在十九世紀末已經出現, 那時候許多在港的富有華人, 開始視自己為此地的永久居民, 並且是一群特殊的華人, 不同於他們在中國大陸的同胞.  +

不過, 人口中其他階層的人, 則要待到1960和1970年代, 才開始對香港產生更加强烈的認同感. +
大部分1950 年後在香港出生的人, 對中國沒有什麼經驗, 父母又是避禍南來的, 所以他們不大認同中華人民共和國, 特別是其共產黨政府. *香港人把香港的政治穩定和經濟自由, 對照於內地的壓迫和混亂, 尤其是在大躍進和文化大革命時期.*

'''

=== 1975年 -> 越南難民移入

1975年**越南共產黨得勝統一全國後, 約七萬名越南船民為避難, 逃到香港.**

但他們的出現也挑起恨意和敵意, 特別是本地的社會服務和房屋設施原已不足. +
港府為遏止更多難民來港 , 在1982年7月實施禁閉營政策, 把大量越南難民, 關閉在由"懲教署"管理的禁閉營內. 政府並竭力安排其他收容國收留這些難民, 又勸他們自願返回越南. 但禁閉營一直存在至1992年.

'''


=== 80年代

港督麥理浩在1980年10月宣佈, 政府將取消「抵壘」政策.  +

#*Touch Base Policy 抵垒政策* : 是1974年11月-1980年10月间, 香港政府针对来自中国非法入境者的难民政策, *即由中国偷渡到香港市区（界限街以南）即得到香港居民的身份。*# *抵垒（Touch Base）本是棒球用语，*意指跑垒员只要能及时抵达并触碰垒包，便不会出局。*

*港府自1950年以來, 一直容許那些已經與家人團聚, 或覓得有酬工作的非法入境者, 留在香港. 但##現在"抵垒政策"取消後, 被捕獲的非法入境者, 則會被遣返.##*  麥理浩指, 這些非法入境者, 令房屋、醫療 、 教育和社會福利資源, 捉襟見肘. 而且這些人犯罪數目之多, 「與他們的人數完全不成比例」.

'''

== (移民) 移出香港 -> 海外华工

直至最近几十年为止, 移民海外的中国人中, 约90%都取道香港.

=== 香港开埠后的早年
<南京条约>开放了其他口岸, 令广州生意承压, 竞争加剧. 到了1840年代末和1850年代初, 广州丧失了茶叶和生丝贸易方面的优势, 导致了大量人口失业. 几乎在同一时间, 英, 法, 和美国部分地区废除了奴隶制, 令美国, 加拿大, 澳洲, 新西兰, 及西印度和东印度群岛, 对廉价苦工的需求大增. 第一批华工出海. +
對於華工出洋, 雖然清廷法律禁止, 但中國官方無力也不曾阻止. 因为華工出洋也有助緩解中國沿海地區的人口壓力。

*華工出洋貿易, 这个产业链所涉及的各個環節, 均有利可圖.* 其背後有一個龐大的網絡: 農村的招工館 , 香港和其他口岸的契約商和中間人, 苦力掮客, 華工船上的翻譯和照料者, 大型招工代理商。 +
香港經營的"向舊金山運送華工"業務的兩家最大經紀行，都是由本地華商擁有。

'''

=== Commonwealth Immigrants Act 1962  (1962年 /英联邦移民法)

*#在1962年以前, 任何生於英聯邦的人, 都可以到英國定居#,* 因此"新界"居民開始向英國連鎖式移民.

但是1962年开始的這部移民法(具體見後面專題), 就有了限制.

image:/img/svg006.svg[,100%]

'''

=== 1981《英國國籍法》 -> 香港人不再有居英权

1979年3月, 麥理浩訪問鄧小平后, 沒有人知道中國政府究竟是什麼時候決定要收回香港. 但**1981年通過的《英國國籍法》, 把逾250萬名原本有資格領取英國護照的香港華人身份, 將爲「英國屬土公民」, 並剝奪他們的英國居留權.** 這顯示英國政府那时已了解到香港的英治歲月將在1997年終結 (而不希望有大量香港人移民英國). 雖然"行政,立法"兩局的"非官守議員", 想派代表團到倫敦, 遊說英國國會不要通過這法案, 但麥理浩叫他們取消行程(這些 "非官守議員"原本有可能成功, 因為這法案, 只以三票之差通過).

'''

=== 80年代: 中英谈判期间 -> 港人移出

1986年12月5日, 港督尤德, 在英國駐北京大使館發心臟病辭世,是第一個死於任內的香港總督. 尤德猝逝令香港人的恐懼和不安更形加劇. 雖然在中英談判期間, 這位港督不獲准正式代表香港, 但他仍在談判中為港人爭取權益. +

面對這種不明朗的情況, 有些香港人的反應是更熱中於本地政治, 但其他人則用腳投票. *在中英談判之前, 和期間, 不斷有香港人移民海外* （主要目的地是澳洲、英國、加拿大和美國）. 但《聯合聲明》簽署後, 移民無論數目和意慾, 都大為增加, 香港出現「日益洶湧的移民潮」.  +
從1980至1986年, 每年約有二萬名港人移居海外. 但根據政府數字, 在 1987和1989年, 移居海外的港人分別升急三萬人和四萬. 這些數字不容小覷, 因為它們只代表那些找到收容國接納他們的人, 而沒有反映那些渴望和曾嘗試移民的人的數目.

儘管港督"衛奕信" 否認香港出現人才外流, 但這些移民大多是受過良好教育, 能操雙語, 並擁有英國護照的中產專業人士. *#1981年的《英國國籍法》剝奪了他們的英國居留權,# 所以在1997年香港主權交還中國之前, 他們就轉而尋找其他庇護所.*

[.my1]
.案例
====
在1981年法案生效之前（1948–1982期间），香港居民普遍拥有的国籍是： *CUKC — Citizen of the United Kingdom and Colonies （英国及殖民地公民）*

在1981年法案之前，CUKC 的概念还比较模糊 ——
普通人心理上仍以为“是英国公民”；
而英国政府在立法上也没有完全“划清界线”。

*#但1981年的法案（1983年1月1日生效）彻底拆解了“英国及殖民地公民”这个统一身份。
所有CUKC都必须被重新分类为下列三种之一：#*

1. British Citizen <- 与英国本土有“紧密联系”的人（在英国出生或定居）, 有居英权.
2. British Dependent Territories Citizen (*#BDTC#*) <- 与英国属地（如香港、直布罗陀）有联系的人. 无居英权.
3. British Overseas Citizen *(BOC) <- 授予"出生于前英国殖民地, 但未在独立后获得该国国籍的人"。 即曾经为殖民地居民，但(由于该殖民地后来独立了, 导致其中有些人)已无属地国籍了. 这类人也无居英权.*

#*于是：绝大多数香港人*#—— 尽管仍是“英国属地的公民”，但##**在1983年起自动变成 BDTC（英国属地公民），并明确地被排除在**##拥有英国本土##**"居英权"之外。**##

image:/img/svg008.svg[,100%]

这种“剥夺”是怎样体现在法律文字里的？

1981年法案第11条规定：

`主`A person /*who* _immediately before_ 紧接在……之前 commencement 开始，开端 *was* _a citizen of the United Kingdom and Colonies_ `谓`*shall* 将要，将会 on commencement *become*— +
在开始生效前 身为英国及殖民地公民的人，在开始生效时将变为...... +

- (a) a _British citizen_ /if he has _the right of abode_ in the United Kingdom; +
- (b) a _British Dependent Territories citizen_ /if he *has a connection with* a British dependent territory; +
- (c) otherwise, _a British Overseas citizen_. +

翻译重点：

- 如果你在1982年12月31日那天拥有英国居英权 → 成为 British Citizen。
- 如果你与英国属地（如香港）有联系 → 成为 BDTC。
- 否则（两者都不是） → 成为 BOC。 +

结果： +
几百万香港居民, 虽然依旧是英国属地公民（BDTC），
但不再与英国本土, 有任何法律上的入境或定居权联系。
这等于英国在国籍法上切断了香港与英国之间的“公民纽带”。


自 1983年1月1日 起：
香港人自动成为 British Dependent Territories Citizen (BDTC – Hong Kong)，
但 ⚠️ 没有英国居英权（Right of Abode）。

这意味着： +
- 虽然仍持“British Passport”， +
- 但入境英国需签证， +
- 在英国不能自由工作、居住或领取福利。 +

因此，想移民英国，就必须通过“特别渠道”或“工作/投资等签证类别”。
====

'''

=== 89年天安门事件后 -> 港人移出

1989 年春天北京發生的事件, 令許多香港人對中國政府的信心蕩然無存. 1989年4月15日, 因阻止1986年學生示威不力而遭撤職的前中共總書記胡耀邦去世, 北京大學生組織了一連串爭取民主的示威. 到了 5月4日「四五運動」七十周年的日子, 示威引起全世界關注.學生在5月13日佔據天安門廣場舉行絕食, 抗議政府貪腐, 並要求民主改革. 總理李鵬在5月20日頒佈戒嚴令.

对此,  +

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|-> 港人加快自己的"民主化"步伐
|*北京的示威也令許多人相信, 香港須要加快步伐推進自己的民主化.* 在5月24日, *行政立法兩局的官守議員一致同意, 香港立法機關50%的成員, 在1995年由"直接選舉"產生, 到2003年則全部由"直選"產生.*

|-> 港人移民, 移出
|6月4日, 天安門事件發生. 天安門事件令許多香港人對中國政府信心蕩然, 也對香港前途完全盡失信心. 请反映於股票市場下挫百25%, 房地產價值下跌, 申請移民人數大增.

以下**兩種主要策略,** 是許多人的反應：*用腳投票, 和用選票投票.*

香港人移民海外屬於一種長期趨勢, 而非純粹因天安門事件引發的反應, 不過, 移民數目由1989年4萬人, 激增至1990年的6.5萬人, 1992年更攀升至6.6萬人的巔峰.

**從1984年, 到主權移交前夕, 香港總人口中約有"一成人"離開, **他們主要移民到澳洲、加拿大和美國, 也有前往英國, 新西蘭和新加坡等地（*新加坡政府在天安門事件後宣佈, 在往後五至八年,  它容許二萬五千個香港家庭移居該國, 第二天就有超過一萬人湧到新加坡領事館*）.

從1960年代到1980年代, 英國頒佈各種移民法, 減慢了移民遷入英國的速度.


|-> 英国为港人施行《人權法案》保护
|港同盟主席李柱銘比喻, 把香港人交給中國, 等於把猶太人交給希特勒的納粹德國. +
*行政局議員鄧蓮如問, 英國人怎麼能心安理得「把英國子民, 交藉一個毫不猶疑地用坦克和軍隊對付本國人民的政權」.* +
首相戴卓爾夫人表示, 對於殺戮感到「極度反感和憤怒」, 承諾會放寬英國移民法律, 以協助減輕香港人的憂慮.

**#英國人確實採取了幾項措施#, **去安撫國際社會和恢復香港信心：*#鼓勵香港市民留港的國籍計劃, 加快進行"代議政制", 以及《人權法案》在1997年後維持有效.#* +
如果香港人突然大舉出走, 對英國, 對中國, 對香港本身的後果都可能不堪設想.

|-> 英国为一部分港人, 给予英国移民资格
|**行政立法兩局**因此推出「香港是我家」運動, *要求英國政府給予325萬香港英籍居民, 可到英國定居的"英國本土公民身份",* 並協助其餘港人在別的地方尋找家園. 目的是替香港人留個退路. *戴卓爾政府斷然拒絕,* 因爲考慮到當時英國失業率節節上升. +

*英國政府勉為其難地答應港督衛奕信提出的要求, 向5.5萬名擔任要職的合資格港人及其直系親屬, 發出居英權, 總共涉及22.5萬名香港居民.* +
1989年12月頒佈的《英國國籍（香港）法案》, 向5.5萬名這類人士及其家屬, 提供英國本土國籍（當中2/3來自私人企業, 1/3來自政府部門. *這個向港人發出英國公民權的名額, 是"外交部"與"內政部"妥協折衷的結果, 前者希望人數盡量多, 後者則希望盡量少*）.

**中國政府**指摘英國違反《聯合聲明》和《基本法》, *堅稱它在1997年後不會承認這些人是英國子民.* 結果, 申請這個"居英權"方案的人數, 比英國政府和港府所預期的少. 也因為**中國説, 持有這種新護照的人, 在中國境內不會享有"領事保護".**

|太空人/ 降落傘兒童
|儘管不少移居海外的人, 在取得外國國籍後就回流, 但這些數目龐大的移民, 創造了兩種新形的家庭結構一 太空人家庭, 和降落傘兒童.

- 太空人:  指太太不在身邊的男人, 這些人移民後把妻兒留在海外, 自己則穿梭香港和移居地工作或做生意.
- 降落傘兒童: 是父母回流香港, 自己卻被父母為安全計, 留在海外的兒童.

更加重要的是經濟因素：這些家庭很快發現, 他們在新定居地的收入, 比不上他們在香港所賺的多.
|===

'''


=== 97前 -> 港人移出

英國政府在1996 年, 給予七千名在港的南亞裔人（大部分是印度人）移居英國的權利.

*1996年3月, 香港人民入境事務處外大排長龍,* 因為許多人抓緊這最後機會, 為自己在九七後的前途打算, *#申請歸化為"英國屬土公民". 雖然"英國屬土公民"國籍到1997年6月30日後就失效, 但歸化後, 就有資格領取"BN(O) 英國國民（海外）護照".# 這種護照的持有人, 雖然沒有英國居留權, 但可以免簽證到多個國家旅行.(但後來, #國安法頒佈後, BN(0)護照就有居英權了!#)*  +
在1990年, *超過300萬香港人持有這種護照.* 香港政府在1993年宣佈, *1996年3月31日後不再接受"歸化申請".*

那些申請”英國屬土公民”國籍的眾多港人, 其歸化申請如獲接納, 須宣誓效忠伊利沙伯女皇.

[.my1]
.案例
====
(BBC新聞): +

*根據香港政府估算，#1987年至1996年間，約有50萬人移居外地，佔當時人口的8%。#*

- 英國1990年代曾推出俗稱「居英權計劃」的"英國國籍甄選計劃"，讓五萬名合資格港人及家屬, 透過計劃登記成為英國公民。

- ##**2020年《香港國安法》實施後，出現新一輪移民潮，至今約有30萬人移居海外。**##據英國內政部的數據，截至2025年3月，共批出約17.9萬宗申BN(O)簽證申請，有約16.3萬人已抵埠。 +
*《香港國安法》之後，西方國家推出「救生艇計劃」予港人申請. 而##在九七前那一波的移民潮裡，不少香港人都是以"投資移民、技術移民"的方式移居海外。##* +
而目前最多港人透過 BN(O)簽證移民.

- 那些在1997年前移民到其他國家，隨後「回流」香港工作; 近年再從香港出走，「回流」到當初移民目的地國家的現象，又被稱為是「二次（雙向）回流」。 +
除了社會政治環境的因素外，也有一些人是選擇回到外國退休。「香港不是退休的好環境」.
====

'''

=== 97後

主權移交後兩年, 社會學家黃紹倫, 對於港人看待香港迴歸的態度, 整理出4种類型:  +
親中 — 中立 — 想移民而不得 — 能夠且已經移民

- 「忠誠派」(親中派)生於中國, 在人生後期才來到香港, 通常**出身低下階層**.
- 「本地人」屬於較年輕一輩, 與中國大陸的家族聯繫不多. 他們在政治上持中立態度.
- 「猶豫觀望派」*大多屬工人階級*, 寧願受英國統治而不想被中國控制, 他們**想移民但找不到國家收留.**
- 「四海為家者」通常出生於南來的**中上層家庭**, 這些家庭在1949年後因政治問題逃離中國, 南來香港. 這些人希望接受英國統治, 反對香港交還中國. 他們為了九七的後路籌謀多年, 已在西方建立家族聯繫.



'''

