

= 4-01 港中时代
:toc: left
:toc-title: 目录
:toclevels: 4
:sectnums:
:stylesheet: ../../myAdocCss.css
:pdf-font-family: Microsoft YaHei UI


'''

== (97後) 港中時代



=== ★ (97後) 中共对香港自主权力的侵入, 和香港民主權力的倒退. 及##香港人對普選的要求##

事實上, 一國兩制模式, 最初是針對台灣設計的, 香港”一國兩制”的失敗,  會激發更多台灣人要求獨立. (今日香港, 明日臺灣)

大部分香港人有一個揮之不去的憂慮, 那就是中國政府在九七後, 會試圖干預香港事務.  +
中國政府答應香港享有「高度自治」. 但是許多香港人認為中國政府經常干預特區政治事務. **一個主要憂慮是香港的法律和政治自主權. **

- 2007年6月, **吳邦國宣稱, 香港不享有任何「剩餘權力」, 其「高度自治權」是由中央政府授予,而非香港的新憲法地位所固有的. (意思就是是我恩賜給你的, 不是你拼實力爭得來的. 我想拿就能拿走. 自治權不是你們的”天賦權利”).**

*97後的香港特區政府, 和之前的殖民地政府一樣, 試圖以推動經濟增長和發展, 令市民不去注意香港的政治(民主)停滯.*


'''


== (港中) 特首

雖然行政長官的推選過程並不民主, 但在設計上是, 還是讓全體香港社會得以參與了下. 候選人在推選過程中, 會與所有主要政黨和利益團體會面. *北京想表達的意思其實是: 在殖民地時代, 所有港督都是由倫敦委派, 從沒有徵詢香港人意見; 而董建華獲委任前,  至少還是稍為徵詢過香港人的意見.*


=== 第1屆特首: 董建華

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|#*香港回归后的性质, 从"外殖民", 变成了"内殖民"*#
|董建華想同時令香港人和中方利益集團滿意, 方法之一是保留兩名彭定康的"行政局"議員. 但**他沒有委任任何民主黨成員加入"行政會議",** 而受抨擊. *因此, 新的”行政會議”被指 跟殖民地時代的”行政局”, 沒有分別.* +
事實上, 某些觀察家認為, *香港沒有”非殖化”, 而是被”再殖民”,* 只是宗主國由倫敦轉為北京.

[.my1]
.案例
====
关于”行政會議”, Wikipedia的介绍: +
*Executive Council (ExCo) 行政会议, 就是97前的"行政局". 是政府内阁及"顾问机构".*  +

97前: +

- 流程: 港英总督在决定重要决策, 或向"立法局"提交法案前, 均先由"香港总督"会同"行政局"通过.
- 无实权: 在1991年"立法局"部分议席改为"直选"前，立法局议员, 大多数是均由香港总督"委任"或"间接选举"产生的，而且**不少"立法局议员"均兼任"行政局议员"，因此"立法局"实际只是“橡皮图章”.**

97后: +
《香港基本法》规定，##*行政长官作出任何重要决策前，均须征询"行政会议"的意见*，##即“行政长官会同行政会议”。 +
"行政会议"实行"保密制"及"集体负责制"。*
====


|港人对董建华的评价
|董建華是香港開埠150多年來, 首名管治此地的華人.
許多批評者視他為北京的傀儡, 但有些中國領導人反而擔心他在政治上是否可靠（他的家族與台灣有長久的聯繫）.

許多香港人認爲, 港督彭定康比董建華能幹. *董建華更為注重於扶植和奉承大財團, 而不是實踐自己的諾言, 來满足長者對於醫療, 照料, 和房屋的需求,* 以及去為市民大眾提供更好的房屋.

在1999年7月1日, 一群長者組成代表團, 向董建華請願, 要求他兑現在1996年競選時所許的承諾, 改善長者服務.

|特区官员
|- 2001年1月, 民望極高的政務司司長陳方安生, 突然宣佈將在5月辭職, 比她任期屆滿提早一年離任. 因爲陳方安生在民主改革步伐, 和捍衛香港新聞自由的問題上, 與董建華意見不一, 她早已明言, 如果政府施政有違她的原則, 就會請辭 (集體責任制).
- 2003年7月1日, 香港民衆爆發大遊行, 抗議由保安局局長葉劉淑儀主力推動的"國家安全條例". 後, 她在7月16日請辭.
- 財政司司長梁錦松, 一直因爲無法降低香港的高失業率, 和恢復消費者對經濟的信心, 而受到批評.  他在葉劉淑儀請辭後幾個小時也接着下台.
- 2004年7月, “立法會”發表調查2003年沙士事件的報吿書, 指政府沒有及時遏止沙士散播, 兩名高級衛生官員隨即請辭.

|董建华的提早辞职
|董建華在2005年3月提早下台, 辭職, 被廣泛視為他無法取信於中國政府的證明. 因爲董建華失去了他在北京的主要靠山——前國家主席江澤民.
|===

'''

=== 第2屆特首: 曾蔭權

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|
|接替董建华的, 是前政務司司長曾蔭權, 是董建華內閣中民望最高的官員.  +
曾蔭權必須小心翼翼平衡各方：既不令商界支持者背棄他, 又要向中國輸誠, 還要令一般平民滿意.

曾蔭權在2005年11月宣佈, 委任153名公眾人士, 包括民主黨主席李永達在內的民主派立法會議員, 加入"策略發展委員會"（策發會）, "咨發會"是香港特區政府的諮詢組織, 其工作包括負責研究如何擴大香港的民主改革. (该机构在2017年7月1日起被裁撤.)

|反对"扩大民主改革"
|這些富商巨賈, 和中國領導人一樣, 反對擴大香港的民主改革.

- 中共: 中國領導人擔心香港實行民主, 會 1.刺激大陸百姓提出同樣要求. 2.要求政府增加民生福利支出.
- 香港商界大亨 : 擔心"民主化"會導致加税.

平民百姓「對於政府和商界精英合謀決定香港的未來, 完全無視民眾意見, 已經忍無可忍」. (*贵族和政府合谋, 玩了平民*)
|===







