= 0458
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 458: Going to the Playground.
This is English as a Second Language Podcast episode 458. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode, which will give you all of the vocabulary, definitions, new sample sentences with the new words that we talk about, additional definitions, cultural notes, comprehension questions, and a complete transcript of this episode.
This episode is a story called “Going to the Playground.” It’s going to introduce some common vocabulary you might use if you are on a playground, a place where kids play. Let’s get started.
[start of story]
My wife was out of town on business and our nanny was sick, so I took the day off from work to take care of our two kids: Livia, who is two, and Augustus, who is three and a half. I thought that going to the playground would be a good thing to do, but it turned out to be an accident waiting to happen.
When we got to the playground, the kids jumped out of the car. Livia got onto the merry-go-round, pushing it as hard as she could. The trouble was, there were a couple of toddlers playing on it and they fell backwards, getting the wind knocked out of them.
Augustus, on the other hand, ran straight for the swing set and almost got decapitated! Then he went over to the see-saw and almost got smashed when he tried to run under it! He ran out of my grasp and onto the jungle gym. He started hanging off the monkey bars. I caught him just in time as he fell!
When I turned around, I saw that Livia had got onto the slide and slid head first into the sandbox! Good thing she wasn’t hurt.
By this time, I realized my mistake. Far from a safe place to play, for two lively kids and one father, the playground was a deathtrap!
[end of story]
Our story begins with the poor father in this story – not me, by the way – taking his son and daughter to a playground. A “playground” is an area where children play that usually has large pieces of equipment. You often find these in a public park or next to a school.
He says that “My wife was out of town on business (she was traveling in another city) and our nanny was sick.” A “nanny” (nanny) is a woman whose job is to take care of someone else’s children, usually when the parent is gone working. The nanny often lives in the home of the family, although sometimes they just come over early in the morning when the mother and father are getting ready to leave for work.
In the story, the poor father took the day off from work (to not go to work) and took care of their two children, Livia and Augustus. He says that he thought that going to the playground would be a good thing to do, but it turned out (it resulted that) it was an accident waiting to happen. The expression “an accident waiting to happen” means that something is dangerous. It’s a situation where something bad will probably happen if you wait long enough, with enough time – so in general, a dangerous situation.
“When we got to the playground,” he says, “the kids jumped out of the car,” meaning they opened the doors quickly and got out of the car. Livia got onto the merry-go-round. A “merry-go-round” is a large, round piece of equipment for children to play on. It is flat and spins around in a circle. Usually there are places for the children to stand or sit on the merry-go-round. Merry-go-rounds can sometimes be sophisticated, with horses – not real horses, of course – horses that go up and down as the circle goes around and around. A merry-go-round is interesting for very young children, maybe three, four, five years old.
Well, in this case Livia got onto the merry-go-round and pushed it as hard as she could – got it to move around in a circle. Unfortunately, there were already a couple of “toddlers” (a couple of young children, usually one to two years old) that were sitting on the merry-go-round. Because Livia pushed the merry-go-round to make it spin – to make it go around in a circle, this caused the other two children to fall off of the merry-go-round (they probably weren’t expecting it to suddenly move), and this caused them to get the wind knocked out of them. To “get the wind knocked out of you” is an expression that means to fall down usually on your chest or your stomach, or having someone hit you so that you find it difficult to breathe for a short period of time. Your “wind,” in this case, is the air going in and out of your lungs (that part of the body where the air goes when you breathe in).
“Augustus, on the other hand,” he says, “ran straight for the swing set.” To “run straight for” means to go directly to the swing set. A “swing set” is a large piece of equipment you would find on a playground, or even in someone’s back yard behind their house – someone who had young children. It usually has two or three of little seats, rectangular pieces of wood or plastic that kids can sit on, and these seats are connected to a pole that is above them so that they can swing – they can go back and forth in the air. We used to have one of these in my house – in the back yard in the house where I grew up. They were very popular, and still are. Swing sets, however, can be a little dangerous because if you swing too high it’s possible for you to fall off.
Augustus apparently was swinging a little bit too much and almost got decapitated. “Decapitated” means without your head, literally when someone cuts your head off from the rest of your body – separates your head from the rest of your body. During the French Revolution there was something called, in English, the guillotine, which was a large blade like a large knife that cut people’s heads off who were enemies of the government. This is a way of decapitating someone. I don’t recommend it, personally!
Getting back to Augustus, he then went over to the see-saw. A “see-saw” (see-saw) is a long piece of wood – a rectangular piece of wood, or sometimes metal, that has seats on both ends, and in the middle there is something that holds up the wood or the piece of metal. When one child goes up the other child goes down, and they go back and forth going up and down. In the center is something that is holding up this piece of wood; technically, it is what we would call a “fulcrum” (fulcrum). Once again, the see-saw would be a popular toy – a popular piece of equipment for a young child. Unfortunately, the young son of the narrator of our story, Augustus, almost got smashed when he tried to run under the see-saw. One is guessing that there was somebody already on the see-saw who was coming down, and Augustus was running underneath the see-saw. When we say he almost got “smashed,” we mean that he almost got hurt – he almost got hit. To “smash” usually means to apply force from the top down, something very heavy. You could take a hammer, for example, and smash a plate. I don’t know why you would do this, maybe you’re angry! Sometimes it’s useful to hit something when you’re angry, as long as you don’t hit another person.
In this case, poor Augustus almost got smashed – almost got hit when he tried to run under a see-saw. “Augustus ran out of my grasp,” the poor father says, “and onto the jungle gym.” To be “out of your grasp” (grasp) means to be away from your hands – to be too far for you to hold or to touch. We can also use this in a more metaphorical sense, you can say that becoming president of the company is out of my grasp – it’s too far away from me, I can’t reach it, I can’t obtain it. The word “grasp” has a couple of different meanings in English; take a look at our Learning Guide for some additional explanations.
Augustus runs out of his father’s grasp and onto a jungle gym. A “jungle gym” is a large, tall piece of equipment that has many different metal bars separated by open spaces so that children can climb on them. It’s another large piece of equipment that you would find in a park on a playground. Part of the jungle gym has what we would call “monkey bars.” “Monkey bars” are sort of like a ladder that is horizontal instead of vertical. Normally, if you want to climb up to the top of your house or to a top of a building you might use a ladder, which has pieces of metal every couple of feet or every foot that are basically steps that you can climb up to go straight up. Monkey bars consist of a ladder that is horizontal instead of vertical, and you grab onto each metal bar and you try to move forward. If you’ve seen a movie about the army – the armed forces training, this is a very common way of training soldiers when you have these monkey bars, essentially. We don’t call them monkey bars in the army, I would guess, but that’s what they’re called on a playground. It’s basically a horizontal ladder that you have high above the ground, and you grab one bar and move forward with your arms.
In this case, Augustus got up to the monkey bars and almost fell off of them, hitting the ground. He did fall off, but his father was there to catch him. When the father turns around he sees that Livia has gone onto the slide. A “slide” on a playground is a long, flat, narrow piece of metal that is placed at an angle so that children can go down it. So you have a ladder that goes to the top of the slide, and the children get on the slide and they go all the way down to the bottom. In fact, we would use the verb “to slide” – “They slide down to the bottom of the slide” (used as a noun). “Slide” has a couple of different meanings in English, however, so take a look at the Learning Guide to understand this word a little better.
Unfortunately, Livia is going down the slide head first. When we say someone goes down “head first” we mean that their head is moving in front of their feet, especially if you are sliding down something. It is dangerous if you are going down with your head as the first thing that would hit the ground; you want your feet to be the first thing that hits the ground. So, the opposite of head first would be feet first. Livia slides into a sandbox. A “sandbox” is a large, open, rectangular box that is filled with sand, very small pieces of earth that you usually find on a beach. Very young children often like to play in these sandboxes. Fortunately for Livia, because the slide went into a sandbox, the sand was able to protect her from hurting herself too much.
The father says at the end of the story, “By this time, I realized my mistake.” He thought the playground was a safe place to play, which is why he says, “Far from a safe place to play (meaning that’s not true, it’s not a safe place to play), it’s not a safe place for two lively kids and one father.” “Lively” means very active, with lots of energy. Instead, he says, “the playground was a deathtrap!” A “deathtrap” is a very dangerous thing or dangerous place where you can get killed very easily.
Now let’s listen to the story, this time at a normal speed.
[start of story]
My wife was out of town on business and our nanny was sick, so I took the day off from work to take care of our two kids: Livia, who is two, and Augustus, who is three and a half. I thought that going to the playground would be a good thing to do, but it turned out to be an accident waiting to happen.
When we got to the playground, the kids jumped out of the car. Livia got onto the merry-go-round, pushing it as hard as she could. The trouble was, there were a couple of toddlers playing on it and they fell backwards, getting the wind knocked out of them.
Augustus, on the other hand, ran straight for the swing set and almost got decapitated! Then he went over to the see-saw and almost got smashed when he tried to run under it! He ran out of my grasp and onto the jungle gym. He started hanging off the monkey bars. I caught him just in time as he fell!
When I turned around, I saw that Livia had got onto the slide and slid head first into the sandbox! Good thing she wasn’t hurt.
By this time, I realized my mistake. Far from a safe place to play, for two lively kids and one father, the playground was a deathtrap!
[end of story]
The script for this episode was written by the lively Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2009, by the Center for Educational Development.
Glossary
nanny – a woman whose job is to take care of another person’s children, usually full-time while the parent is working and often living in the family’s home
* Toshiyo and Mariah both work as engineers, so they have a nanny who takes care of their three children.
playground – an area where children can play on large pieces of equipment, usually at a park or next to a school
* They often play with their friends at the playground after school.
an accident waiting to happen – something that is dangerous; a situation where something bad is likely to happen eventually if enough time passes
* Letting people smoke cigarettes near a gas station is just an accident waiting to happen.
merry-go-round – a large, round piece of equipment for children to play on that spins in a circle around the center and has room for children to stand or sit on it
* Melinda got dizzy on the merry-go-round and she felt sick.
toddler – a young child who is one to two years old and is learning how to walk, but cannot do it very well yet
* Taking care of toddlers is a lot of work because you have to follow them around and make sure they don’t get into trouble.
to get the wind knocked out of (one) – to fall down, usually on one’s stomach or chest, so that air is pushed out of one’s lungs and one has difficulty breathing for a few seconds
* She got the wind knocked out of her when she fell off the table.
swing set – a large piece of equipment where small, rectangular pieces of wood or plastic hang from ropes or chains so that children can sit on them and move back and forth through the air
* The little boy asked his father to push him higher and higher on the swing set.
decapitated – without one’s head; with one’s head separated or cut off from one’s body
* How many people were decapitated while Catherine the Great ruled Russia?
see-saw – a long, rectangular piece of wood or metal with seats on both ends that is held up in the middle so that one child sits on each end and they use their legs against the ground to push each other up into the air
* A see-saw doesn’t work well unless both children weigh about the same.
smashed – pressed from above by something very heavy so that something or someone becomes smaller and damaged or injured
* His hand was smashed in a machine at work and he has already had three surgeries on it.
out of (one’s) grasp – away from one’s hands or arms so that someone or something is no longer being held
* The expensive vase fell out of her grasp and broke when it hit the floor.
jungle gym – a large, tall piece of equipment with many metal bars separated by open spaces that children can climb onto, through, and over
* When the boy reached the top of the jungle gym, he got scared and didn’t know how to come back down, so his brother had to help him.
monkey bars – a piece of equipment that looks like a ladder lying horizontally with tall pieces of metal holding it up at each end, so that children can use their hands to hang from the pieces of metal and move from one end to the other without having their feet touch the ground
* Jake is already too tall for the monkey bars, so he has to bend his knees when he hangs from them, or else his feet hit the ground.
slide – a long, narrow, flat piece of metal or plastic that is placed at an angle so that children can climb stairs to get to the top, sit down, and move quickly down until their feet are on the ground again
* Little kids like to go down the slide, but bigger kids often try to climb up it.
head first – with one’s head going somewhere first, followed by the rest of one’s body and one’s feet
* The 10-month-old girl tried to get off the couch head first. She needs to learn to turn around and come down on her legs instead.
sandbox – a large, open box that is filled with sand (very small pieces of earth usually found on the beach) for children to play with
* Pippy likes to build castles in the sandbox with her friends.
lively – very active; with a lot of energy
* The wedding reception was very lively as the guests laughed and danced.
deathtrap – something that is very dangerous; a place where one might die because there are many dangers
* He drives an old car with bad brakes and poor steering. It’s a deathtrap!
Comprehension Questions
1. What happened to the toddlers who were playing on the merry-go-round?
a) They started running faster and faster.
b) They ran out of breath from playing so hard.
c) They weren’t able to breathe for a moment.
2. Which of these pieces of playground equipment can move?
a) A see-saw.
b) A jungle gym.
c) Monkey bars.
Answers at bottom.
What Else Does It Mean?
out of (one’s) grasp
The phrase “out of (one’s) grasp,” in this podcast, is used for something that is away from one’s hands or arms so that someone or something is no longer being held: “The clerk ripped the money out of my grasp as he hurried to make the sale.” The phrase “to have a good grasp of (something)” means to understand something well or thoroughly: “She has a good grasp of music theory.” When one has a good “grasp of (something),” one understands it very well or can do it very well: “I wish I had a better grasp of basic math.” The phrase “beyond (someone’s) grasp” is used to talk about something that one is not able to do, have, or use because it is too difficult or expensive: “Driving a Porsche is out of our grasp because those cars are too expensive.”
slide
In this podcast, the word “slide” means a long, narrow, flat piece of metal or plastic that is placed at an angle so that children can climb stairs to go to the top, sit down, and move quickly down until their feet are on the ground again: “Let’s go to the park and watch the children play on the slide.” A “slide” is also a small, rectangular, thin piece of plastic that has a photograph or another image on it and a bright light shines through it to show the photograph or image on a wall or screen: “They have many slides with family photos from the 1970s.” Finally, a “slide” is a decrease in something: “Why have we been seeing a slide in sales in recent months?”
Culture Note
Most playgrounds in the United States have “posted” (hung for people to see) rules, such as the hours when the park is open and whether or not dogs can be “off leash” (without anything tied around their necks for the owners to control them). There are also usually signs telling people that they shouldn’t drink alcohol or use drugs in the park. In addition, there are also many unofficial rules that children and their parents follow at the playground, although they are not written down.
For example, children are told to “take turns.” This means that if many children want to use one piece of playground equipment, they should do it one at a time. It wouldn’t be fair for one child to use something 20 times while the other children wait, so each child uses something once and doesn’t get to use it again until everyone else has been able to use it.
Children are also taught to “watch out for” (be careful around) younger children. At most playgrounds, there are children of many different ages, and sometimes it can be dangerous for toddlers who are just learning how to walk to play near older children who run quickly and might accidentally hurt them.
Another important rule at playgrounds and in other places, too, is to not talk to “strangers,” or people whom one doesn’t know. In cities, people are worried that strangers will “approach” (come near) their children and maybe try to hurt or “kidnap” (take a child away) them, so they teach their children not to talk to strangers or to “accept” (take) gifts or candy from strangers.
Comprehension Answers
1 - c
2 - a