= 1377
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast's English Café number 72.
This is English as a Second Language Podcast's English Café episode 72. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we're going to talk about some recent articles in the news, one of them about “The Nobel Effect,” and other one about bicycle riding. We're also going to, as always, answer some of your questions. Let's get started!
Did you know that we have a website? Well, we do! Go to eslpod.com and take a look at the Learning Guide for this episode. While you're there, you can also check out our new ESL Podcast Store with some interesting premium courses.
Our first topic today is based on an article that I read in one of the major newsweeklies. There are three main news magazines in the United States; Time is the name of one, US News and World Report is another. This article comes from the third one, called Newsweek, “Newsweek.”
The article is called “The Nobel Effect.” The Nobel, “Nobel,” Prize, you probably know, is a set of prizes given out every year, mostly to scientists and researchers. There's also the Nobel Peace Prize, which is given to a person or an organization that helps promote world peace.
The article talks about a recent study by some researchers in England, at the University of Warwick, that found that people who win a Nobel Prize will often live longer than other people. The quote from the article says that The Nobel Prize winners “stick around about two years longer than colleagues who don't” win a prize. The expression to stick, “stick,” around, or to stick around longer, means to stay or to remain longer. In this case, they live longer.
Normally we use this expression, to stick around, when we are talking about someone in a particular place. You might say, “I'm going to stick around and wait for my brother to call me” - I'm going to wait here - I'm going to stay here. Here they mean they stick around in life - they live longer.
There was a similar study of this phenomenon - this idea - done a few years ago, about people who win Oscar movie awards. The Oscars are the most famous movie awards in the United States for actors and actresses and movies. People who win an Oscar live longer than people who don't win an Oscar - people, of course who are nominated - the other people who lost.
Now, scientists have been trying to figure out why this is. One of the ideas - one of the guesses they have - is that according to the article, simply having the bragging rights of having won a Nobel Prize allows them to live longer - gives them some advantage in living longer.
The expression bragging, “bragging,” rights, “rights,” comes from the verb to brag, “brag.” To brag means to say something good about yourself - to say that you have done something well - you have won a prize, or you have done something that other people will be proud of you for. Usually, to brag is considered a bad thing - at least in American culture - to say that you are the best. Of course, this doesn't stop people from bragging, many Americans do! The expression bragging rights means that you have the right to brag - you deserve to brag. You really have done whatever you are bragging about and, therefore, you have that particular right.
The idea is that people who win these prizes have a certain effect caused by the winning of the prize that helps them, perhaps, psychologically. One researcher says that they may live longer because they are “buffeted against subsequent adversities.” That's an interesting expression. To be buffeted, “buffeted,” against something means to be protected from - you won't be affected by a certain thing. They're “buffeted” - or protected - “against subsequent adversities.” Subsequent, “subsequent,” means something that comes after. Adversity, “adversity,” (the plural is adversities) are bad things that happen to you. So, “buffeted against subsequent adversities” means that the Nobel Prize winners are protected against bad things that happen later on in life because psychologically they feel very good about themselves, and that has an effect on their health.
Another scientist quoted in the article says that he thinks they live longer because once “you've reached the pinnacle, you behave more carefully.” The pinnacle, “pinnacle,” is the highest point that you can reach - the very top. It could be a place, like the top of a mountain. We often use this expression in talking about someone's career - their success in life. “They've reached the pinnacle of their success” - the highest point of their success.
So, what this researcher is saying is that once you've reached the highest point, and everyone knows you and you're famous, you behave more carefully. You may not do things that would damage or hurt your health. You won't go out and get drunk and drink too much alcohol every night because people say, “Hey! This guy won a Nobel Prize, look a terrible he's acting!” So, that's another possibility.
I think in either case, the conclusion that we want to draw from this article, for me personally is that if I am going to live longer and continue making ESL Podcasts, I need to win a Nobel Prize. Probably the Nobel Peace Prize, I think. So, if anyone there in Sweden, where they give these prizes out every year, is listening, I would really appreciate winning a Nobel Prize this year!
Our second topic is also from the news media; this one comes from the New York Times Magazine. On Sunday, the New York Times, which is the largest and most important newspaper in the United States, has a magazine section, like many newspapers have on Sundays.
There was an interesting article a few weeks ago about bicycle helmets. Now, I don't normally ride a bicycle, so I don't normally wear a bicycle helmet. A helmet, “helmet,” is what you put on your head to protect your head in case you fall. Now, most people think that if you wear a helmet to protect your head when you are bicycling, you will be safer. If you are out on the street and there are cars around you, if you have a helmet on you'll feel and be safer. However, one researcher - again in England, this time at the University of Bath - said that this isn't, in fact, necessarily true.
He did a study where he rode his bicycle and he wore a helmet. Sometimes he wore a helmet; some days he didn't wear a helmet. What he found out is that on the days that he wore a helmet, the cars would come closer to him. The cars and trucks on the road - on the street - would come closer to his bike. If he didn't wear a helmet, they would go around him - they would come close to him.
The idea is that the helmet changed the way the drivers reacted. So, if the driver of the car saw someone with a helmet, they would say, “Oh, well, they must be a very good bicyclist” - a safe bicyclist. So, they didn't worry as much about hitting the bicyclist, and they actually drove closer to them, which, of course, is more dangerous for the bicyclist.
This was an interesting observation. He published his study in a scientific journal. Some people complained that people who would read the article with stop wearing their helmets, when in fact, what the researcher suggested is that governments educate drivers - they tell drivers - that just because someone has a helmet on doesn't mean that they are necessarily going to be safer.
Interestingly, during his study, this researcher was actually hit twice on his bicycle by cars. We would say he was struck by a car. To be struck, “struck,” by something means to be hit by something, usually a car or a truck.
The conclusion of this article - some people think - is that wearing a bicycle helmet puts you at risk of being hurt. Notice that expression, to be put at risk, “risk.” That means to be put in danger - to be in a dangerous situation. Well, I'm not sure if that's the right conclusion; you can decide for yourself what it means if you ride a bicycle.
Now let's answer a few of your questions.
Our first question today comes from Durian, “Durian,” originally from Vietnam, now living in California. Durian wants to know the difference between the expression “to talk someone out of something” and “to have it out with someone.”
To talk someone out of something means to convince someone not to do something - to persuade them against doing something - to get them to change their mind. That's another expression; to change someone's mind means to get them to do something or think in a different way. Usually, you try to talk someone out of something that you think will be bad for them or that will hurt them. For example, if your friend likes listening to ESL Podcast and decides to get a tattoo of ESL Podcast on his arm, that's something you probably want to try to talk him out of - talk him out of getting the ESL Podcast tattoo. Probably not a good idea!
To have it out with someone means that you talk to someone, usually you have an argument, and then you solve a problem or you come to some sort of agreement. You find a solution to some problem that you have. First, you have this discussion - this argument - and then you have a solution. For example, your boss gives you more work and more work all of the time - every week you're getting more work, too much - but she doesn't pay you any more - you don't get any more money for doing the extra work. So, you become very unhappy and you decide to have it out with your boss. You tell her that you want more money if you are going to work more hours. Of course, you can have it out, but the solution may not be the one you want. You should be prepared to hear the words “You're fired,” that would not be a good solution!
Harouna, “Harouna,” from the country of Senegal, in Africa, wants to know the difference between the expression “I'll wait for you” and “I'll be waiting for you.”
Sometimes these two expressions mean the same thing. There are some cases, however, where you can only use one or the other. If you are talking about something that is going to happen very soon - in the immediate future, within the next hour, maybe two hours, for example, you and your wife are shopping at the store - at the mall - the shopping mall - and she wants to go into a clothing store - a women's clothing store - you might say, “I'll wait for you outside,” meaning that's what I'm going to do in the very immediate future - for the next ten minutes I'll wait for you here. You wouldn't say, “I'll be waiting for you,” you would probably say, “I'll wait for you” for something that will happen very soon.
If your wife tells you that she's going to fly to New York to buy some new clothing, you could also say, “I'll wait for you at home.” This is further in the future, but you could still use that expression - “I'll wait for you.”
If you say, “I'll be waiting for you,” usually you are trying to emphasize the fact that you are actually waiting. The emphasis is on the verb waiting, or to wait. You would also probably say, “I'll be waiting for you” if it is even further in the future. You may say in the same situation, where your wife says, “I'm going to go to New York to buy some new clothing,” you say, “Well, when you come back” - when you return - “I'll be waiting for you.” So, when this happens in the future, then I will be waiting for you even further in the future. So, it has a more future - farther in the - further, rather, in the future, that's sometimes how we use that expression, “I'll be waiting for you.”
So again, “I'll wait for you” is something you would say in the immediate future; “I'll be waiting for you” is often further in the future. But, you'll sometimes hear people use them to mean just about the same thing.
Our final question comes from Oleg, “Oleg,” in Russia, in Moscow. Oleg wants to know the meaning or how you use the word mixture, if it is singular or if it is plural. Do you say, “the mixture is,” or “the mixture are?”
Well, let's start by defining this word mixture, “mixture.” A mixture is something you get when you combine two different things. For example, if you are baking a cake, you would combine some flour with some eggs, maybe some butter, and you would combine those together. You would mix those together and you would create - or produce - a mixture. That's what you get when you combine the things.
Mixture is a singular noun. Even though a mixture has different things in it, we consider the noun mixture to be singular. So, you would say, “The mixture is given to the child,” if it was some sort of medicine, for example.
You can also, instead of saying mixture, just say mix. “The mix for the cake is ready.” So, mix can be a verb, but mix can also be a noun meaning the same thing as mixture. You might also say, “The class” - or the group - “has a good mix of students,” meaning there are different types of students - different kinds of students together.
It is possible, however, to have a sentence such as this: “The parts of the mixture are added to the solution.” The verb is plural, but the reason it is plural is because the subject of the sentence it is the word parts, and parts is a plural noun - parts of the mixture, but mixture is not the subject of the sentence.
So again, mixture is always singular and takes a singular verb.
If you have a question that you would like us to try to answer on the Café, send us an email. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on the English Café.
ESL Podcast's English Café is written and produced by Dr. Jeff McQuillan. This podcast is copyright 2007, by the Center for Educational Development.
Glossary
Nobel Prize – prizes given each year to people who have done outstanding work in science, literature, economics, or promoting world peace
* This university is famous for having six Nobel Prize winners on its faculty.
to stick around – to stay in one place; to remain in the place where you are
* I know that you said he would be back in about a half hour, but I’m not sure I want to stick around that long.
bragging rights – the right to boast (tell others with pride) about your accomplishment because you feel you have earned it
* After beating the best team in the league, their team won bragging rights for an entire year.
to be buffeted against – to have defense against; to be protected from
* The families living near the sea filled put boards over their windows and doors to buffet themselves against the strong winds of the coming storm.
adversity – misfortune; bad luck; hardship; trouble
* Even though Martin grew up in poverty, he overcame adversity to become one of the most respected men in this city.
subsequent – the next; following; future
* The first time Denise met her music teacher, she thought he was unfriendly. But on subsequent visits, she changed her mind and now likes him a lot.
pinnacle – the highest point; the most successful
* When I reach the pinnacle of my career, I hope I’ll also be happy.
helmet – a hard hat worn to protect the head of soldiers, motorcycle and bike riders, construction workers, and other people doing dangerous things
* Wearing the safety helmet on the construction site saved his life when the heavy brick fell on top of him.
to be put at risk – to be placed in a dangerous situation
* The government report says that poor nutrition in childhood puts people at risk for serious health problems later in life.
to be struck by – to be hit by
* During the storm, the school was struck by lightening and most of the computers in that classroom were damaged.
to talk someone out of (something) – to convince someone not to do something; to get someone to change their mind
* Don’t try to talk him out of getting married. If he says he’s ready, then he’s ready.
to have it out with (someone) – to end or conclude something decisively (finally); to reach a final agreement; to confront someone about some issue or problem in order to find a solution or to make a decision
* I’m tired of the coach telling me that she’ll let me play soon. She never puts me in and I plan to have it out with her before the next game.
I’ll wait for you – I will stay here while you go somewhere or do something
* If you want to go to the movie, I’ll bring a book to read and wait for you in the park.
I’ll be waiting for you – I will be here after something else happens
* When the movie ends, I’ll be waiting for you in the parking lot to take you home.
mixture – something that is made after adding different things together
* The sauce on the chicken tastes weird. I think it’s a mixture of fruit, nuts, and eggs.
What Insiders Know
Darwin Award
The Darwin Award is an “honor” (award or prize) that is given as a joke to people who have done stupid things to hurt themselves badly or to kill themselves. It is given out each year. It was started by different people on the Internet, and there is no official organization that gives out this award. One of the most well known lists, however, can be found at www.darwinawards.com.
This award is named after Charles Darwin (1809–1882) who is best known for his “theory” (general principles to explain something) about “evolution,” or how people have changed over its long history on earth. One idea that came out of Darwin’s theory is often called “survival of the fittest,” which is the idea that the strongest and smartest people survive, and the weakest and dumbest don’t. As a result, the weakest people do not pass on their “genes” (the characteristics that a person passes onto his or her children) to future generations.
This award is a “tongue-in-cheek” (not serious) prize for the people each year who has done the stupidest thing to kill themselves or to hurt themselves so that they can no longer have children. For example, in 1996, the winners included a man who wanted to prove how brave and strong he was by cutting off his head! In 2000, one of the winners shot himself with his own gun while teaching his wife about gun safety. In 2005, two men who had been drinking alcohol made a bet while standing on an “overpass” (road or bridge over a freeway). They wanted to know who was strongest. They decided that the winner would be the person who could “dangle” (hang by one’s arms) over the freeway the longest. The winner was too tired to climb back up and was killed when he fell.
No one is certain why most of the winners have been men.