= 1357
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 52.
This is English as a Second Language Podcast’s English Café number 52. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com.
On today's Café, we’re going to talk about wills and estates – things related to your money after you are no longer here on earth. And, as always, we’ll answer a few of your questions. Let's get started.
Our topic today is one that not many people like to think about, and that is: what happens when you die, or more importantly – what happens, after you die, to your money? What happens to the things you own – your money, your house, your car, your laptop computer, your favorite pen . . . all of the things that you own, what happens to them? In most countries, there are laws that say what will happen to that property, the things that you own.
There have been several cases in the United States recently, or in the last ten years or so, where very rich people died and it wasn't exactly clear what was going to happen to their money. For example, here in Los Angeles, there was a famous producer – someone who made television shows – by the name of Aaron Spelling. Mr. Spelling's daughter is named Tori. She was on a television show that was very popular many years ago called Beverly Hills 90210, about a group of high school students at a high school in the very rich city here in Southern California called Beverly Hills.
Well, what happened was that Tori Spelling's father died a very wealthy man – a very rich man. He had maybe 500 million dollars. Now, he had a legal document that said what he wanted done with that money. We call that legal document a “will.” A “will” is something you make that tells people what you want to happen to your money and your property after you die. Now, the very rich Mr. Spelling did not, in his will, leave very much to Tori Spelling, his daughter.
“To leave” here means to give, but to give only after you die. It's only a verb we would use in a will, in a legal document about what happens to your property after you're dead. “I leave my iPad to my friend Jimmy.” That means after I die, my iPad will go to my friend Jimmy. Of course, I hope I don't die soon, and the iPad probably won't be worth very much money in a few years, but if I die right away and it is, then Jimmy will be happy. That's the verb “to leave” your property to someone.
When you write a will, it isn't always going to be followed. Tori Spelling didn't like the fact that her father didn't leave her any money, and so she tried to change the situation to make sure that the will would not be followed. I want to talk a little bit about what happens in the United States in these situations. I'm not a lawyer, of course. I did a little research, and I think what I'm about to tell you is mostly accurate, but of course, you should always talk to a real attorney – a real lawyer – if you are here in the United States, anyway, and want to write a will.
If you do write a will here in the United States before you die, when you do die, the people in your family or your friends will take that will – that legal document, that piece of paper – to a judge, to what we call a “probate court.” “Probate (probate) court” is the place where decisions about what happens to your property legally are decided. Now, typically when you die, you have to pay taxes, especially if you're very wealthy. If you have a lot of money, you have to pay some of that money back to the government in the form of taxes.
Of course, you don't have to pay it because you’re dead, but the people you are leaving the money to have to pay your taxes. After you die, all of your property is given a single name that describes everything you owned, and that name is “estate” (estate). Your “estate” is your property after you’re dead. You could say, “Mr. Spelling's estate was worth 500 million dollars,” meaning if you took all of his money and his cars and his houses, they would have a value of 500 million dollars.
The tax that you pay on the money when you die is called an “estate tax.” If you die without a will – if you don't write something down before you die (and many people do not) – your family still has to go to probate court. They still have to go there and find out what has to be done with your property. Now, in most states, there are very specific laws about what happens if someone dies without a will. In most states, if you are married to someone, your wife or your husband will get your money if you don't leave a will.
Sometimes, people write a will so that certain members of their family will not get any money. The verb we would use here would be “to disinherit” someone. “To inherit” (inherit) means that you get money from someone who died. You get money from that person's estate. “To disinherit” means that the will says you're not going to get any money. So, if you have a son or a daughter, and you don't like the way they live their lives, you may decide to disinherit them. You may decide to say in your will, “I leave no money to my son and daughter.” In part, that's what Mr. Spelling did with Tori Spelling.
If someone who dies is left money, we call that person an “heir” (heir). An “heir” is the person or persons who get money from an estate – the persons to whom you leave money in your will. The verb we would use when someone is not included in a will who should be or would normally be, such as the case of Tori Spelling and her father, is “to cut out of” the will. If we say some person was “cut out of a will,” we mean that the will said that person would not get any money or would not get any property, even though you might expect them to.
Now, as I said before, most states have laws that say what happens to your property if you do not have a will. I mentioned that your husband or your wife would get your property after you died, if they're still alive. If not, the property would go to your children, and if you don't have children, then it would go to the next closest relatives. It might be your brothers and sisters. It might be your cousins. It could be your nieces and nephews. It could even be someone older than you. It could be an aunt or an uncle.
Regardless of who is the closest person, the government – the court – has to decide who gets what, and the court is the one who will make the final decision if you don't have a will. That's why lawyers tell you to make a will – so that nothing happens after you die that you would not want to happen. Of course, lawyers also tell you to write a will because they charge you money to write the will for you.
Some people won’t like what's in the will, and they will contest the will. The verb “to contest” (contest) means that, in this case, you go to the probate court that's handling the estate of the person whose will you are interested in, and you say, “No, this is wrong.” You might say, for example, that the will “is not valid.” “To be valid” (valid) means that it is correct, that it has followed the laws of that particular state.
When you write a will, you can't just take a piece of paper and say, “I leave all of my money to my neighbor John or my wife Susie.” You have to follow certain procedures. Typically, a will has to have witnesses. A “witness” (witness) is a person who says, “Yes, this person is the real person whose name is on the bottom of the will.” You're saying, “Yes, I read this and this person actually wrote it and signed it.” That's a witness, and most wills require that you have a witness or two, depending on the state you are in.
In the United States, every state has its own regulations about wills, but the laws are pretty similar. Sometimes there is a case where there is more than one will. You might write a will, and then a year later you might write another will. Or you might write a will by typing it out on a computer and printing it out, and then you might take a piece of paper and a pencil and write down some things on a piece of paper that you want to be your will. So, all of these questions have to be brought before the probate judge who has to decide which is the valid will and whether the will, or any of the wills, is valid.
Once, there was a very famous businessman here in the United States by the name of Howard Hughes. Howard Hughes was famous in the airplane industry and was a very, very rich man. Well, Howard Hughes died without a valid will. He had millions – probably billions – of dollars, but he never left a valid will. And so his property was distributed according to the laws in that state about where the money should go.
Now, having a will, when talking about writing a will, is not always a happy topic. Most of us don't think that we will ever die. There a lot of older rock stars, I think, who believe that even though they’re 70 years old they should act like they were 25. Those people probably think they'll never die – but of course, all of us will die.
It's always a good idea to prepare for things, if for no reason other than you want life to be easier for your husband or wife or your family. You don't want to cause them a lot of legal problems, and if you die without a will, it's always more difficult for your family to take care of the financial matters related to your estate. If you don't want to talk to a lawyer or spend money on a lawyer in order to write a will, then my suggestion would be just never die.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Marcel (Marcel) in Germany. Marcel wants to know the meaning of the expression “no big.” “No big” is a shorter form of another informal expression, “No big deal.” When someone says something is “no big deal,” they mean it's not very important. You sometimes will hear people say, “It's no big deal.” They may shorten it to “It's no big.” “It's no big,” or “It's no biggie” (biggie). Other ways of saying this same idea, once again very informally, would be, “It's no big whoop” (whoop). That means the same thing – “It's no big deal.”
Lisa (Lisa) in Taiwan wants to know the meaning of the expression “primordial soup.” “Soup” (soup) is normally a liquid that you eat at lunch or dinner. It often has vegetables or meat in it that you eat with the liquid. “Primordial” (primordial) comes from the Latin, originally – something that was “prime” was something that was first. So, “primordial” means something that was at the very beginning, at the very earliest time.
The term “primordial soup” is one used sometimes in biology to refer to when the Earth was just starting, or I should say, when life on earth was just starting. There are some scientists who talk about the basic elements of life, the basic components of life, and how these components came together many millions and millions of years ago. That's the theory that some biologists have. So, they describe the substances that were available many millions of years ago that, according to their theories, caused life to begin as “primordial soup.”
Our third question comes from Giacomo (Giacomo). I'm guessing Giacomo is from Italy, but he could be from some other country. Giacomo wants to know the difference in the use of the words “trouble,” “problem,” “issue,” and “situation.” Let’s start with the most general of these four words, “problem.” When you say there is a problem, you mean that there is something wrong and you need to fix it. You need to change it. You need to find a solution. We would use the expression “solve the problem.” “To solve a problem” is to find a solution or to fix the problem.
So, if you don't have any money to take your girlfriend to a nice dinner, well, that's a problem. The solution, of course, is to take her to McDonald's for a hamburger. Of course, you may not have the girlfriend much longer if you do that, but that also solves the problem – you see, you don't have to take anyone to dinner if you don't have a girlfriend.
“Trouble” is when someone has done something wrong or someone has a problem. So, “trouble” and “problem” are related. However, “trouble” is typically used either as a noun in the plural – “I have troubles,” meaning I have lots of problems – or we use the expression “I'm in trouble.” “To be in trouble” means to have a lot of problems. It might be because you did something wrong.
Often, when we say, “That boy is in trouble,” we mean that boy did something wrong and he will be punished – something bad will happen to him because he did something wrong. He's in trouble. This is something kids say about each other, especially in a family. A brother might say, “Oh, you're in trouble,” meaning mom or dad is going to get angry with you because you did something wrong.
“Issue” (issue) is a general term that doesn't necessarily mean something’s bad. It doesn't necessarily mean something’s good. “Issue” simply describes a certain kind of situation, a certain kind of event. It's not a negative or a positive description. “Trouble” and “problem” are definitely always negative. “Issue” could be positive or negative. “Issue” just means you're talking about a certain idea or certain examples of something. You might say, “The issue is, how do we get more money for our school?” The issue is the topic. It's the idea that you're talking about.
You could have many things that are called issues, and sometimes issues are problems, as I mentioned earlier, and sometimes issues are just things that you have to talk about. This is especially popular when talking about politics. People talk about the issue of the economy or the issue of defense spending. These are all topics that people disagree about and therefore there is a lot of discussion about.
Another word that has become more popular in the last 15, 20 years or so is “situation.” It used to be that “situation” was a neutral – neither positive nor negative – word describing a series of actions or events. Now, more recently, people use the word to describe a problem, to describe some trouble. “We have a situation here.” That means we have a problem here. We have something bad that is happening. Notice that it's almost always in the singular: “We have a situation.”
So to review, “problem,” “trouble,” and “situation” are all bad things, negative things. “Issue” is neutral. It could be positive or negative.
Our next question comes from Camille (Camille) back over in Taiwan. Camille wants to know the meaning of the expression “It will come” – or “It will arrive” – “in no time.” “In no time” means very quickly. “Your brother will be here in no time.” That means he will be here within a minute or two – very quickly, not a long time. “In no time” means quickly.
Our next question is from German (German) from Uruguay in South America. German wants to know the difference between the words “answer,” “response,” and “reply.” All three of these words are nouns, although some of them can also act as verbs. “Answer” is used when someone asks you a question and they want to get information from you. You “give them an answer” or, using it as a verb, you “answer” them.
“Response” and “reply” are usually when someone has said something to you, but not necessarily a question, and you say something back to them. You “reply,” as a verb, or you “respond.” “Respond” is the verb form of “response,” which is a noun. So, I say something to you and you say something back to me. You “respond” to me, or you “reply” to me.
We could also say you “give me a reply” or you “give me a response” just like you “give me an answer.” “Answer” is used mostly for questions – what you say back to someone who is asking you a question. “Response” and “reply” are more general. They can be used for a question, but they can also be used for a comment – when someone says something to you that is not a question, but you want to give your idea or you want to continue the conversation.
“Response” is a little more formal in terms of its use. When we talk about a “response,” we’re usually talking about some sort of legal or business situation. “Reply” is now used a lot in email. “I replied to his message.” That means I sent an email back to him responding to, perhaps answering, whatever questions he had or comments that he made.
Our next question comes from Miyu (Miyu), originally from Japan but now living here in the United States. Miyu wants to know about the use of the word “though” (though), especially at the end of a sentence. For example, when someone says, “I really like this pair of shoes. They're expensive, though.” The “though” here means the same as “however,” and usually what we are saying is that the last thing you said somehow contradicts or disagrees with the first thing you said.
So, the first sentence is, “I really like this pair of shoes.” That's a positive thing. But you’re also saying a negative thing: “They're expensive.” They cost a lot of money. So I say, “They're expensive, though.” You're saying that the second thing disagrees somewhat with the first thing, or it is providing a negative where first you started with a positive.
You could go in the other direction. You could start with saying something negative such as, “Boy this is a really ugly shirt. It looks good on you, though.” You’re saying the person who's wearing the shirt doesn't look ugly. The shirt is good for that person even though you just said it was an ugly shirt. So, you're saying something positive after saying something negative, although I'm not sure if the person will be very happy.
Our last question today comes from way up in Norway. Lisa (Lisa) wants to know the meanings of the words “device,” “gadget,” “gizmo,” and “contraption.” A “device” (device) is a general term to describe any sort of machine. A radio, for example, is a device used to listen to audio programs. A “gadget” (gadget) is a small device – a small machine, often electronic or computer-related – that does something interesting or something new.
We may describe a new mobile phone, a new cell phone, as a “gadget,” especially when it can do something that other phones can't do. After a while, after a few years, it may no longer be used with that object. The word “gadget” usually describes that something is new, something is technologically advanced and interesting. “Gizmo” (gizmo) is very similar to “gadget.” It's not as common as gadget, but it really means the same thing. Sometimes using the word “gizmo” might have a slightly negative connotation. You may be sort of criticizing the device by calling it a gizmo.
“Contraption” (contraption) is a word for a machine, but usually a machine that is very complicated or that isn't made very well. Like when we say “gizmo,” to call something a “contraption” is usually a criticism. You're usually saying that it's not very well built or that it's too complicated.
None of your questions are too complicated for us. If you have some, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2006 by the Center for Educational Development.
Glossary
will – a legal document with instructions on what to do with someone’s money and property after they die
* When I made a will, I decided to leave some money to my close friends as well as to my family.
estate – all of the money and property owned by one person who has died
* No one knew that her estate was worth over $2 million until after her death.
to inherit – to receive money or property when someone else dies
* My aunt told me that when she dies, my brother and I will inherit her house.
heir – the person who will legally own a property after someone else dies
* The family lawyer asked all of the heirs to meet at his office for the reading of the will.
to cut (someone) out of a will – to not allow someone to get your money or property after you die
* It was a surprise to everyone that his grandmother cut him and his entire family out of the will.
to contest a will – to dispute a legal document with instructions on what to do with someone’s money and property after they die
* Edward was surprised to hear that his sisters were contesting the will because they thought it was a fake.
no big (deal/whoop)! – it’s not important
* Even though Lena was very disappointed when Manny canceled their date, she told him that it was no big deal.
trouble – difficulty; a bad situation
* We broke the neighbor’s window and now, we’re in big trouble.
problem – a bad situation that needs to be solved or fixed
* What was that loud noise in the kitchen? Is there a problem?
issue – an important topic
* There are three new issues we need to discuss at today’s meeting.
situation – a problem
* Can you come into the office right away? We have situation here with a group of very unhappy employees.
response – a reaction to something; an answer to something
* What type of response do you expect when you suddenly tell your parents that you have a new wife?
reply – saying something in response to what someone else has said
* If you want a reply, you have to ask me that question seriously.
answer – something that is said or written to respond to a question
* The answer to that math problem is in the back of the textbook.
gadget – a small machine or tool
* With this new gadget, I can open my car door and start the engine without a key.
contraption – a machine that looks strange or that is too complicated, often badly made or unsafe
* I don’t plan to ride in that contraption. It just doesn’t look safe.
What Insiders Know
“In this world nothing is certain but death and taxes.” – Benjamin Franklin
Benjamin Franklin is one of the most important people in American history. He was one of the “Founding Fathers,” or one of the men who signed the original documents to form the United States and who were leaders in making the U.S. independent of Britain. He was an important “diplomat,” who represented the U.S. in other countries, and shaped how people saw the U.S. through his political activities and writings.
Benjamin Franklin was born in Boston, Massachusetts in 1706, and he became a newspaper editor and a “printer,” or someone whose job is to print books and papers. He wrote and published many books and articles, and is well known for the interesting and clever things he said and wrote. This quote, “In this world nothing is certain but death and taxes,” like many of his other quotes, is still well known and used today. The meaning of this quote is that people can never be sure about anything in life except that they will die and that they will have to pay taxes. He is, of course, making a joke and a statement that the government makes everyone pay taxes, no matter who they are. Many people have developed their own versions of the quote. For example: “There is nothing certain in life but uncertainty.” And, “In this world nothing is certain but change.”
Benjamin Franklin is also well known as a scientist and “inventor,” or someone who creates new things. He made many discoveries, but he is probably most well-known for his theories about “electricity,” a form of energy.