= 1401
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast's English Café number 96.
This is the English Café episode 96. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. You can also take a look at the ESL Podcast Store, where we offer some additional specialized courses.
In this Café, we're going to talk about how people become medical doctors in the United States. Every country is a little different; we'll talk about how you do it here in the U.S. We'll also talk a little bit about the differences in income based on how much education you have here in the U.S. And, as always, we'll answer a few of your questions. Let's get started.
Our first topic is about doctors and how to become a doctor. We've talked a little bit about how you become – how you get to be a certain kind of occupation or have a certain kind of occupation in our previous Cafés. Today, we're going to talk about how you become a doctor in the United States – what do you have to do.
First, I should “distinguish,” or tell you the difference, between a medical doctor, someone we would call an “M.D.” for medical doctor, and a doctor of philosophy, what we would call a “Ph.D.” A doctor of philosophy isn't necessarily a philosopher, like Plato and Aristotle were philosophers. A doctor of philosophy, a Ph.D., is someone who gets a graduate degree, but not in medicine; an M.D. is a medical doctor, someone who can help you with your health. I am not a medical doctor; I am a Ph.D., so I can't really help you at all. Some people would call me a fake doctor! A real doctor – a medical doctor – is someone who can help you with your health.
In the U.S., in order to get either a Ph.D. or an M.D. you need to finish your Bachelor's degree, usually taking four or five years to finish what we would call your “undergraduate” degree, or Bachelor's degree. After that, you have to go to school for four more years – to medical school.
There are about 140-150 medical schools in the United States. To get into a medical school is highly competitive. When we say something is “competitive,” we mean it is very difficult; there are lots of people who want to get into medical school. Some schools, like the Harvard Medical School, are extremely competitive – highly competitive. Other schools are less competitive, but generally, medical schools have a very competitive acceptance. Getting a medical degree is very demanding. We say something is “demanding” when it is very difficult – it requires a lot of work.
So, getting into a medical school is difficult, and then getting your medical degree is also difficult. If you want to go a medical school in the U.S., you need to “submit,” or send, your transcripts. “Transcripts” are a list of your grades; they include all of the classes that you took as an undergraduate. You also have to take a test called the “Medical College Admissions Test,” or the MCAT. This is sort of like the SAT, the “Scholastic Achievement Test.” It's a difficult test that tests your knowledge of math and reading comprehension and other things. You also need to get “letters of recommendation.” These are letters from usually your professors from your Bachelor's degree, saying that you are a good student. Many schools also require that you go and interview with someone from the school – someone from the “admissions committee,” the group of people who decide who gets into the medical school and who doesn't.
Your first two years of your four years of medical school are mostly classroom experiences or in a laboratory. You're learning basic scientific medical ideas about “anatomy,” the parts of the body, other types of scientific study. You also learn, during these first few years, to take a “medical history.” This is when you ask patients – ask the people you are trying to help, what their problems are, what the symptoms are. A “symptom” is an indication of a problem. You also learn to diagnose illnesses. “To diagnose” (diagnose) means to determine – to figure out what the problem is. The doctor diagnoses you with a certain problem: “I was diagnosed with influenza” – with the flu.
You do all of this under the supervision of, or with the help of, more experienced doctors and physicians in hospitals and clinics. A “clinic” is like a small hospital that doesn't have a complete hospital set-up. It's a medical office where you can go to get examined.
Medical school also requires you to go through what are called “rotations.” “Rotations” comes from the verb “to rotate.” “To rotate” means to change from one thing to another thing to another thing. Rotations require medical students to go to different departments in the hospital: to pediatrics, which is for young children; to psychiatry; to surgery; to gynecology, which is medical treatment specifically for women; and so forth. So, you work in all the different departments for a certain amount of time so you get experience in different types of medical treatment.
Now, once you finish your four years of medical school, in most states – in fact, in all states and U.S. territories – you have to take an exam. The exam gives you a “license” – gives you permission – to practice medicine. Notice we use the verb “practice”: “I'm practicing medicine.” You could also say, “I'm practicing law.” Normally, “practice” is when you are just trying to do something, but when we talk about medicine and law, “practice” means to actually be a doctor or to be a lawyer. So, you can practice medicine after you past an exam.
You also have to graduate from what is called an “accredited” medical school. “Accredited” means that there is an organization that says, “Yes, this medical school is good. This is a acceptable quality medical school.”
If you are doctor from another country, and you want to get a license to be a physician in a U.S. state, you have to, usually, take the same exam, and sometimes you have to work in a hospital for a year or two in something called a “residency.” A “residency” is something that even U.S. doctors – most U.S. doctors do. It's like additional training after your four years of medical school in one special area, in what we would call a “specialty,” where you are being paid, but you are working on one special area of medicine. That's called a “residency.” Residencies can last one, two, or more years.
So, to review: you go to four years of medical school, you take an examination, then you usually spend one or more years as a resident specializing in one area. If you come from another country, you can usually take the exam and then work in a residency for a year or two, and then get your license.
Most states accept doctors from other states, so you don't need to get a new license when you move from California to Oklahoma or to New York, but not all states. Sometimes states require some additional things from you, even though you were a doctor in a different state.
How much does all of this cost? Well, it's very expensive to go to medical school in the U.S. For one year of medical school at a private – that is, a non-government medical school – you will probably pay around $35-34,000. That's every year, so for four years, you're going to be paying more than $120,000. That's just for your tuition – that is, that's just for your classes. “Tuition” refers to the money you pay the university to take classes there. You also have to eat, however, and have a place to live, what we would call your “housing,” or living expenses. This 30 to $35,000 does not include your housing and living expenses.
It is a little cheaper to go to a government medical school – a lot cheaper, usually about half that cost. But, you must be a resident of that state, meaning you have to be a citizen who is living in that state, or someone who has residency status. This use of “residency” should not be confused with the “residency” we talked about earlier, which was referring to a specialization that you do in a hospital after medical school. Here, we mean someone is living in a state for a certain amount of time. For example, I am a resident California – I live in California. If I move to Texas and I want to go to school in Texas, I may have to wait a year or two years in order to get the discount for residents. So, you have to have a certain amount of time in a state; each state is different when it comes to how long you have to be there. And, if you're from another country, you may never get the residency discount at the public universities. Discounts for residents are usually just for public universities, not for private universities.
So, if you want to become a doctor in the United States, you need a lot of money and a lot of time. Of course, most doctors don't have $130,000 to pay for their school, so they take out loans. They get loans from a bank, and then when they start working, they pay the loans back.
I thought I'd talk a little bit – since we are talking about education – a little bit about how much Americans make depending on their level of education. There was a recent article in the New York Times Magazine; this is a publication of the New York Times newspaper. This was a story about how much people who have a Bachelor's degree make in the U.S. on average, how much people with a Master's degree make, how much people with a Ph.D. make, how much people with a professional degree such as a lawyer or a doctor makes.
The average salary – the average income each year for someone who has a Bachelor's degree is about $40,000. That's the average salary – the average income, how much money you make each year. If you don't have a Bachelor's degree, if you just have a high school diploma and you never went to college, the average salary is about $21,000 a year, so almost half of what you would make if you went to college. So, going to college doubles your salary on average.
If you go to college but don't graduate, you go for one year or two years and then you stop, that does not give you very much advantage over those who just have a high school education. A person who has some college makes about $23,000 on average; so, just a little bit more then a high school graduate.
Now, if you get a Master's degree, which usually requires one or two more years after your Bachelor's degree, your average salary is about $51,000, so about $11,000 more than people who just have a four-year Bachelor's degree. If you get a Ph.D., your average salary will be about $70,000, or about $30,000 more than those who have a Bachelor's degree. Getting a Ph.D. requires usually going to four to six years of school after your Bachelor's degree.
People who have a medical degree, however, make even more money. The average doctor makes between $130,000 a year up to maybe a half a million, or a million dollars a year if they are a very specialized doctor. Most doctors make between 130 and $300,000 a year. So, if you are willing to go to school for a long time, you can definitely make more money, if that's what you want to do!
Now let's answer a few of your questions.
Our first question comes from Sam (Sam) in Taiwan. Sam wants to know the difference among a couple of different constructions in English: “from” and “to,” “during” and “to,” and “between” and “to.” For example, “I will be available from 6:00 to 10:00 tonight.” His question has to do with the differences among these three constructions – these three uses.
Let's give a few examples to make this a little clearer: “I will be available in my office from 6:00 to 9:00 tonight.” If you are talking about a specific time, from this hour to that hour, then we would usually use the expression “from,” such as “I will be available from 9:00 this morning to 4:00 this afternoon.” You could also say, “until 4:00 this afternoon.” So, “I will be free...” or “I will be available...” or “The museum will be open from six to nine,” or “six until nine.”
You can also use “between,” although you will probably hear the word “and” instead of “to.” For example, “The museum is open between 6:00 and 9:00,” or “I will be available between 4:00 and 7:00 this afternoon.”
The word “during” is usually used when talking about a specific event or period of time: “during the day,” or “during the week.” You could say, “During World War II, many people suffered and died.” “During” is an event or a long period of time or a specific period of time. But, you don't normally say “during” when you are using specific hours, such as six to nine. So, you could say, “This library has books between 1700 and 2007”; you could say, “This library has books from 1700 to 2007.” You can say, “This store was closed during the week before Christmas,” or you could say, “This store was closed from December 17th to December 26th.” Notice that if you have a specific time or date you would use “from-to” or “between-and.” If it's talking about the general time, or a week, a day, we would use “during.”
Luc (Luc) from Belgium, over in Europe, wants to know the difference between “fire” (fire) and “arson” (arson). “Fire” is any kind of burning, when you have light, usually smoke, something that is very hot, and you see the fire; we would say you see the “flames” (flames).
“Arson” is a kind of fire. “Arson” is when someone deliberately – intentionally, on purpose – starts a fire to destroy a building or, perhaps, to destroy a park. Usually “arson” is a bad thing, in fact, it's considered a crime whenever you try to burn something down. Many of the – or some of the fires that you may see in the news here in California are often caused by teenagers or other kids who start the fire; this would be “arson.”
“Fire” is any kind of burning of a material or substance; “arson” is a crime, where you start a fire on purpose. We would say the fire is “set” (set) by someone: “Who set the fire?”
Our final question comes from I-H-O-R, I'm not sure how to pronounce that, I'm sorry – from the Ukraine. The question has to do with the expression “town hall meeting.” For example, “The governor will hold a town hall meeting to talk about the environment.”
A “town hall” is a place where people meet; usually it's a government building. A “hall” is sometimes used to refer to a building. So, the “town hall” would be a building that belongs to the town or city, so, a government building, usually.
A “town hall meeting,” however, is usually a meeting with some government official – the mayor, the governor, the president even – where they get together in a room with people, who then can ask questions. So, it's a little more informal kind of meeting.
In the U.S., when we have our presidential elections, there's usually a series of town hall meetings, where the candidates – the people who want to become president – will go, and voters – people who are interested – will come and ask questions of him or her. Sometimes, if there's a controversial issue – a problem in a city or a town – the mayor or one of the town officials – the city officials – will have a town hall meeting.
The word “town hall” is a little old, a little old-fashioned even, but the expression “town hall meeting” it is still used to mean a meeting between a government official and normal citizens to talk about some issue and to allow the citizens to ask questions.
If you have a question, you do not need to go to a town hall meeting, you can just email us at eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on the English Café.
ESL Podcast's English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2007, by the Center for Educational Development.
Glossary
competitive – describes a situation where people, businesses, or organizations try to be better than the others; describes a situation where everyone tries to be the best at something
* Getting into the best universities is very competitive, so we need to study hard and earn good grades.
demanding – challenging; needing a lot of work, concentration, effort, focus, and energy
* Being a financial investor is a demanding career, but it is interesting and it pays very well.
to submit – to send or give something to someone; to give someone something that he or she has asked for
* Did you submit your application before the 5:00 deadline?
transcript – a written record of one’s education; a written document that shows what classes one took, what grades one got, and what degree one earned
* I see on your transcript that you took five chemistry classes. Is that correct?
to diagnose – to identify what an illness, injury, or problem is; to say what is wrong with someone’s health
* The doctors diagnosed her stomach pain as a minor problem that can be treated with medication.
to be under the supervision of (someone) – to work while someone is closely watching and evaluating what one does; to work under someone’s guidance; to be guided in one’s work by someone
* Before you can become a professional counselor, you have to have worked for thousands of hours under the supervision of another counselor.
rotations – periods of time that medical students spend in different parts of a hospital while they are training
* Sandra’s favorite rotations were emergency medicine and surgery.
to practice – to do the work of a professional, such as a doctor, dentist, or lawyer
* Dr. Greller has been practicing in the New Jersey community for more than ten years.
residency – a period of time when a medical student receives special, advanced training at a hospital
* Will is completing his residency at Sacred Heart Hospital, and even though he is often very tired, he is learning a lot.
accredited – an academic institution that is certified by another organization; a college or university whose educational system has been approved by a national organization
* If you don’t go to an accredited university, most people won’t accept your degree as valid.
clinic – a private hospital or group of doctors’ offices where people can go for a specific type of medical care
* Does this city have any good clinics to treat drug abuse and alcoholism?
from…to… – words used to show the times that something starts and ends
* The meeting will be next Wednesday from 10:45 a.m. to 12:15 p.m.
between…and… – words used to show a range of time during which something happens
* Someone hit my car between 11:00 p.m. and 7:30 a.m., but I don’t know exactly when, because I was asleep.
during – in a period of time; through a period of time
* I was living in Russia during the presidential elections.
arson – the crime of setting something on fire; lighting a fire to burn something you do not have legal permission to burn
* Arson is a common cause of forest fires in the Southwestern United States.
town hall meeting – a community meeting; a time and place where community members meet to discuss and vote on things that are important in their community
* At last night’s town hall meeting, people talked about the need to build a new park so that children can play together.
What Insiders Know
Classic TV Doctors
Doctors are a popular “theme” (main idea) in many TV programs. Here are a few of the most famous American TV doctors, “past and present” (from the past and also currently on TV).
Quincy, M.E. was a popular TV show in the late 1970s and early 1980s. The main “character” (person) was Dr. Quincy, who was a “medical examiner,” or a person who helps determine how and why people died. When there was a “suspicious death,” or a death where Quincy thought that maybe the person was killed by another person, then Quincy became like a “detective” (a person who tries to find out who is the killer).
A different type of doctor was shown in Dr. Quinn, Medicine Woman. This program ran in the mid-1990s, and was about a female doctor in the “Old West,” or the Western United States, in the mid-1800s. Because almost all doctors were men at that time, it is interesting to see how the community reacts to Dr. Quinn and her ideas.
Another classic TV show about a doctor was Doogie Howser, M.D., which “aired” (was shown on television), in the early 1990s. It was about a teenage “prodigy,” or extremely intelligent or talented person, who became a doctor when he was only 10 years old. The episodes were about how Doogie “struggled” (had a hard time) being a professional doctor and an American teenager at the same time.
Finally, Marcus Welby, M.D. was a popular TV show during the early 1970s. Dr. Welby was a “family practitioner” (a doctor who specializes in family medicine). He had “unorthodox” (new and unusual) ideas about how to take care of his patients. His younger co-worker had more traditional ideas about medical care, and so the show was about how the two men worked together.