= 1389
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast's English Café number 84.
This is the English Café episode 84. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. You'll be able to look at the vocabulary, read the definitions, have additional cultural information, get the complete transcript for this episode, and win a million dollars – well, everything except the million dollars!
Our topics today are homelessness in the United States; what happens when people don't have a place to live. We're also going to talk about something called a “prenup” and a “postnup” for people who are going to get, or who have gotten married. And finally, we'll answer a few of your questions. Let's get started!
Our first topic today is a difficult one, called “homelessness.” To be “homeless” (homeless) means that you do not have a permanent home – a place where you can go. You may be living on the street, sleeping in a park. You may be sleeping in your car. You may be staying at what we would call a “shelter” (shelter). Homeless shelters are temporary residences – short-term places for people who don't have a home to live.
Many people who come to the United States are surprised to see so many people on the street who are homeless – who don't have a place to live. There was recently a movie about this topic called Pursuit of Happyness that was made with Will Smith, a famous Hollywood actor as the star, about a man and his son who are homeless – who don't have a place to live – and all of the things they have to do in order to survive.
There are many reasons why there are so many homeless people in the United States. One study found there are about 750,000 people in the US who do not have a permanent place to live, who sleep in their car or sleep in a park or some other place.
There are lots of reasons why that is, one of them is that people don't have money. In Hawaii, for example, there is a problem now that the price of the houses have gone up so high that some who people live there don't have money to pay for or rent an apartment, and so they have to sleep on the beach or in a tent or somewhere else.
Sometimes the problem has to do with people not having a job; sometimes the problem is that people have what we would call “substance abuse" problems. “Substance” (substance) basically means drugs or alcohol. “To abuse” (abuse) something means not to use it correctly. So, “substance abuse” is when someone has a problem, usually they are an alcoholic or they are a drug addict. They're someone who uses drugs or alcohol, and this causes them to have problems.
Another problem, and a very big problem, are people who have some sort of “mental illness.” “Mental” (mental) refers to how you think; how you behave, in some way. “Mental illness” is when you have some psychological problem.
Unfortunately, one of the problems in the United States in the last thirty years is that many of the government programs – the government institutions – to help the mentally ill have been closed. Part of this was a change in the way the medical community decided to look at mental illness. The doctors and the government decided that there were too many people in the government programs for people who were mentally ill, and so they let many of these people out into the world.
Unfortunately, some of those people still needed help and many of them ended up being homeless, and that is certainly a percentage of the people who you will see here in Los Angeles or in New York. Not every one, however. Many people are there because they are poor, and the government doesn't have a lot of programs to help these people.
There are many organizations, however, that do try to help people who don't have a home. Many church organizations, many community organizations have homeless shelters; they also try to provide training for people so they can get a job and have money to get into an apartment. But it's a very difficult problem – a very sad problem that we have, and one that, I hope, we can change in the future here in the US.
Our second topic today is very different; this is something called a “prenup” and a “postnup.” A marriage “prenup” and a marriage “postnup,” what is this all about?
Well, this is something that, in some ways, is very American. It is an agreement between two people who are going to get married, we would call that a “prenup” agreement; or, two people who are married already, we would call that a “postnup.” Now, the word “prenup” (prenup) comes from the word “prenuptial.” “Nuptial” (nuptial) is an adjective describing marriage and weddings. Someone may say, “When are your nuptials,” meaning when are you getting married – when will you become a married couple.
A “prenup,” or prenuptial agreement, is an agreement that two people make – a legal agreement – about what will happen, usually to their money, if they get a divorce – a legal divorce – in the future. A “divorce” (divorce) is when you end your marriage.
This is sort of a strange idea because you are saying that you love this person, but maybe in the future you will divorce them, so you want to protect your money. So, you're saying, “I love you, but in case I stop loving you, don't take my money.” Not a very romantic thing, I think!
Now, what are prenups about? Well, usually they're about, as I said, money. They can also be about what we would call “division of property,” meaning how are you going to divide the property you own – your house, your cars, all of the other things that you own, your money – how are you going to divide those things between you and your husband or wife.
Sometimes the prenup has something in the contract about “spousal support.” “Spousal” (spousal) comes from the word “spouse” (spouse). A “spouse” is a person that you are married to. You have a husband and a wife; they are spouses. “Spousal support” means whether one person – the husband or the wife – will give money to the other person for a certain number of years, or one big amount of money, if they get a divorce.
Spousal support is often something that the legal system – the court – decides, especially if there are children. If there are children in the marriage, and they get divorced, we have what's called “child support,” where you have to legally give money to the person who is taking care of the child, usually the wife but not always.
Most people in the US know about prenups, however prenups are not things that are very common among average people. Prenups are only common among people who have a lot of money, or famous people – movie stars who get married many times. Prenups are not something that most people have; I don't have a prenup; I don't know anyone who has a prenup. So, they're not as common as you might think if you read about them in the newspaper. Usually it's for someone who has a lot of money or who is very famous and has a lot of money. If their marriage is on the rocks, we would say, then they're happy they have a prenup. When we say, “your marriage is on the rocks” (rocks), we mean that you have problems with your marriage.
There was an article recently in one of the national newspapers about a new kind of agreement called a “postnup.” A prenup is before you are married; a postnup is an agreement that you have with your spouse – your husband or your wife – after you get married.
These are new kind of agreements. Usually they are about how you are going to divide your property, how you are going to take care of your children, and so forth. So, they're about all the same topics that a prenup would be about, but you do it after you are married. Again, these are very rare; they're a new thing that is happening among some couples who are married.
Of course, the way to solve the problem of dividing your money and so forth is to stay married, a radical idea, especially here in Los Angeles!
Now let's answer a few questions.
Our first question comes from Marina (Marina) in Spain. Marina wants to know the meaning of the expression that she heard or read, “Smith's the name, oil's the game.”
This is actually an example of a type of expression. “X is the name, Y is the game.” “X” is whatever your name is, and “Y” is whatever you are good at, or whatever your business is. So, in this expression, “Smith's the name,” or Smith is the name – the person's name is Smith, their last name – “oil's the game,” or oil is the game, means that oil – petroleum – is this person's business. “X” is the name of the person, and “Y” is whatever business or industry they are in. I might say, “McQuillan's the name, podcasting's the game,” my name is McQuillan, and I am in the business or industry of podcasting.
It's an old expression that you may see in books; it's not something that's common in daily conversation.
Chiyoko (Chiyoko) in Japan wants to know the difference between the words “to weep” (weep) and “to cry” (cry).
Both of these verbs mean to have water come out of your eye and go down your face. That water we call “tears” (tears), the singular is “tear.” We have an expression “to shed (shed) a tear,” or “to shed tears.” “To shed” means to give off – to have, in this case, come out of your eye.
So, to cry, to weep, to shed tears, all of these mean the same thing – you have water coming out your eyes, usually because you are sad, though you could be very, very happy.
Cry is something you can do for many reasons. Maybe you hurt yourself, you are sad; those are reasons you might cry. The verb “cry” can also mean to shout or to scream, often when you have something very bad happen to you – you are in great pain or sadness.
“To weep” is usually used to decide someone who is very sad, who is crying a lot. It's normally used in writing or in literature; in books you may see the word “he was weeping” instead of “he was crying.” Weeping is stronger, it's even – even greater than just crying – someone who is crying a lot usually because something terrible has happened to them. Their wife has asked for a postnup, and they begin to weep because they see their marriage is over.
“Cry,” as I say, is a little more common. If a child hurts himself, we might say, “he cried.” There's an old expression, “Real men don't cry.” “Real men don't cry,” meaning if you're a real man, you will not ever cry. This, of course, is true, unless your soccer team loses the World Cup, then you will cry!
“To weep” is more formal, but you could use it in conversation if, for example, you were describing a family at a funeral, where someone has died. You might say, “The family wept.” “Wept” (wept) is the past tense of “weep.” “The family wept.”
Our final question comes from Amauri (Amauri) in Brazil. Amauri does not have a question about crying or weeping; he has a question about smiling. He recently saw an advertisement for McDonald's, the restaurant that sells terrible hamburgers, and McDonald's had an advertisement that says, “I want to see you smile.” Amauri wants to know the meaning of “smile” here, since it seems to be, to him, grammatically incorrect.
When someone says, “I want to see you smile,” that is grammatically okay – that is grammatically correct; it means I want to see a smile on your face – I want to see you smiling.
We use this phrase when we want something to happen to someone else, or we want someone else to do something. For example, you can say, “I want to see you working,” means I want to see you at your desk working instead of listening to podcasts. “I want to see you work,” you could also say.
“I want to see you happy,” for example, if your son or daughter comes home one day and says, “Mom, Dad, I do not want to be a doctor. I want to be a rock star, a great singer like Jeff McQuillan on ESL Podcast.”
And you say, “Well son, I just want to see you happy,” meaning I don't care if you don't become a doctor, but I want you to be happy – “I just want to see you happy.”
We just want to see you happy! If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. I want to see you listening next time to the English Café!
ESL Podcast's English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2007 by the Center for Educational Development.
Glossary
homeless – not having a home to live in; living on the streets or in a car
* Many families become homeless when one of the parents loses his or her job and the family can’t pay rent.
shelter – a building where homeless people and families can live temporarily so that they aren’t sleeping on the streets
* Homeless shelters are usually full on very cold and snowy nights.
substance abuse – the use of alcohol or other addictive drugs (narcotics) so that it makes someone sick
* There are many special clinics that can help people with substance abuse problems.
mental illness – psychological illness; the state of being sick or unwell mentally or psychologically
* Many people with mental illness are homeless because they can’t get a regular job and make enough money to have a place to live.
prenup / postnup – prenuptial / postnuptial agreement; a legal contract signed before (prenup) or after (postnup) two people get married that says how their money and the things they own will be divided if they later get divorced
* Very rich people often sign a prenup or postnup because they want to protect their money if they get divorced later.
nuptials – a wedding or marriage
* The wedding invitation says that the nuptials will take place at the neighborhood church in two months.
divorce – the legal end of a marriage; the process of ending a marriage because the husband and wife no longer wish to be married to each other
* Did you know that the Graffs got a divorce last year?
division of property – the way in which property (the things that a married couple own) are divided between a husband and wife during a divorce, so that he gets certain things and she gets certain things
* In their division of property, the wife got the large house and the husband got the small beach house and the car.
spousal support – payments made to an ex-wife or ex-husband after a divorce
* Miles receives spousal support of $750 each month from his ex-wife.
on the rocks – a relationship that is not doing well and will probably fail soon
* Their marriage has been on the rocks for years, so nobody was surprised when they decided to get a divorce.
tears – the water that comes out of one’s eyes and falls down one’s cheeks when one is crying
* Can you please give her a tissue to wipe away her tears?
to weep – to cry (have water come out of one’s eyes) a lot because one is very sad
* Everyone was weeping at Uncle Geoffrey’s funeral.
to cry – to have water come out of one’s eyes because one is sad, injured, or very emotional
* Did you cry when you broke your arm?
to shed tears – to cry very gently
* Melinda often sheds tears when she sees a dead dog lying in the road.
to want to see someone (do something) – to want someone else to do or feel something; to want something for another person
* Please let me help you pay for college. I want to see you get a good education and be successful.
What Insiders Know
Sitcoms about Marriage:
Married with Children, Everybody Loves Raymond, & The Cosby Show
In the United States, there are many “sitcoms” on television. The word “sitcom” is short for “situation comedy,” which is a 30-minute funny show that has the same characters in each “episode” (weekly show). Many sitcoms are about marriage, and some of these are very popular. The most popular sitcoms can have many “seasons” and last for years, so viewers watch the characters grow older over time.
One popular sitcom is Married with Children. The “protagonist” (main character) is a shoe salesman named Al. He lives with his wife, son, and daughter and none of them like each other very much. Al doesn’t like his wife Peg, and the members of the family are often doing things to “irritate” (bother) Al. The show has many funny “lines” (the things that the characters say to each other) and it was very popular in the late 1987 and 1997.
Another popular sitcom is Everybody Loves Raymond. The protagonist is a sports writer named Ray. He lives with his wife and young children, but his parents live across the street and his brother often visits. Ray likes having his parents nearby, but his wife doesn’t. Ray is generally happier than Al from Married with Children, but he still has very frustrating experiences with his family and in his marriage. Everybody Loves Raymond was on the air from 1996 to 2005.
The Cosby Show was a funny family sitcom created by comedian Bill Cosby. The father in the family (Bill Cosby) was a doctor and his wife was a lawyer. When this show first came “on the air” (began to be shown on TV) in 1984, it was one of the first TV shows that showed a “wealthy” (rich) African American family. Many people thought that this was a “breakthrough” (a major development or improvement) in how African Americans were “portrayed” (shown) on television. The show ran for eight years and went “off the air” (ended) in 1992.