= 0110
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 110: Hotel Reservations.
You’re listening to English as a Second Language Podcast number 110. I’m your host, Dr. Jeff McQuillan, from the Center for Educational Development in beautiful Los Angeles, California.
Today’s podcast is called “Hotel Reservations.” Let’s travel!
[start of dialogue]
I just finished a huge project at work and I needed some down time. I decided to take a short vacation. I liked the idea of a long weekend out of town. My friend Sara offered to let me crash at her place in San Francisco, but I decided to stay at a hotel instead. Sara has a couple of roommates and I thought it might be too crowded.
I called the toll-free reservation number for a major hotel chain. The reservation agent was very helpful, after I got through the long phone tree.
Agent: Dutton Hotels. How may I help you today?
Jeff: I wanted to check rates and availability for your San Francisco location.
Agent: Certainly, I can help you with that. Will that be the downtown or waterfront location?
Jeff: The waterfront location.
Agent: What date do you plan to check in?
Jeff: I’d like to check in on October 12th and check out the 15th.
Agent: Okay, let me see what we have. For how many?
Jeff: One. And, if possible, I’m looking for a non-smoking room.
Agent: Sure, we have a non-smoking queen with an ocean view for 189 dollars or a standard room with a courtyard view for 139 dollars a night.
Jeff: I’d like to book the standard room.
Agent: Okay, your last name?
Jeff: Rama.
Agent: And your first name?
Jeff: Jeff.
Agent: Okay, I have you booked in a standard, non-smoking queen, checking in on October 12th and departing the 15th. What major credit card would you like to use to guarantee the reservation?
Jeff: A Visa.
Agent: The number and expiration?
Jeff: It’s 7388-2424-3535-1818, and the expiration is 05/08.
Agent: Your confirmation number PD672. Is there anything else I can help you with?
Jeff: No, that’s all. Thanks.
Agent: Have a nice day, and thanks for calling Dutton Hotels.
[end of dialogue]
In this podcast, we are making reservations for a hotel. I started by saying that I had just finished a huge, or large, project and I needed some down time. “Down time” (two words) means time to relax. After you’ve worked hard or had a very stressful experience, we say “I need some down time,” time that I don’t have to work. So, I made a call because my friend Sara in San Francisco said I could crash at her place, but I decided to go to a hotel instead. “To crash” (crash) here means to stay at someone else’s house or apartment, usually for a short period of time. The verb “to crash” also can mean, of course, what would happen when you hit something, like two cars have an accident and they crash. But this is a completely different meaning of the verb “to crash,” it’s an informal use of the verb.
I called the toll-free reservation number of a major hotel chain. “Toll-free” (toll-free), or simply as two words, “toll free,” means that you are not charged for it, it’s a free call. And in the United States numbers that begin with 800 and 866 and 877 and 888, all of those area codes, if you will, those are all toll-free numbers. You don’t have to pay to call them, the company pays the…for the call. A “hotel chain” (chain) just refers to a hotel that is part of a larger company where there are many hotels. A chain of any company is a company that has lots of different locations. McDonald’s is a good example of a restaurant chain. Hotel chains in the United States would be things like Hilton and the Radisson and the Marriott. These are all hotel chains, there’re many different locations for the hotels.
In calling up the reservation number, I got through a long phone tree. A “phone tree” (two words) is when you call and you get an automatic voice message that asks you to “press one” if you want one place – one department, “press two” if you want this, “press three” if you want that, and they want you to press that number on the telephone. Now, it’s become common, in big companies in the United States they have what’s called “voice recognition,” so you don’t even have to press a number, you just say the number and they recognize it – the computer recognizes it – speech recognition. In any case, a phone tree is often a pain in the neck, meaning an inconvenience, because you don’t get to talk to anyone who is a real human being. But I eventually, in calling the hotel, got a “reservation agent,” and that is someone who takes the reservations for the company on the telephone.
I asked…the first thing I asked is “I wanted to check rates and availability.” “Rates,” of course, are how much the hotel costs – how much the rooms – what the price of the rooms are. “Availability” means do you have rooms available – free, open – for the dates I want to go. So it’s common when you first call a reservation agent to say, “Yes, I want to check rates and availability.” The reason you would say that is you may not necessarily want to make a reservation. If you want to make a reservation, and you know you’re going to make a reservation, you say, “Hi, I’d like to…I’m calling to make a reservation.” But if you say, “I’m calling to check rates and availability,” well, you’re just getting the information; you may decide to make a reservation, you may not.
The reservation agent asks me if I want the downtown or waterfront location. Well, “downtown,” you know, is the central part of the city, usually where many businesses are located. “Waterfront” (all one word – waterfront) is the area that’s right next to a lake or an ocean. So, a waterfront hotel would usually have a view of the ocean. I said I wanted the waterfront location, and the agent asked me when I planned to check in. Of course, to “check in” (two words) means to arrive at the hotel. The opposite would be to “check out,” which is to leave the hotel.
The agent said that they had available a non-smoking queen with an ocean view for 189 or a standard room with a courtyard view for 139 a night. A “queen,” of course, is a size of the bed. There are double beds, which fit two people very…but not very much room; queen bed is bigger. A king bed is the biggest kind of bed, and the queen bed is the second biggest. A “ocean view” would, of course be a room with a view, or you can see the ocean from your room. “Non-smoking,” in most American hotels there are rooms that are designated, or are labeled non-smoking; you can’t smoke in the room. The “courtyard view” (courtyard – all one word), a courtyard view would be a room that looks onto other rooms in the hotel, into the center of the hotel. A “courtyard” is when you have a building that has a space in the middle of the building, and parts of the building go around a central area that we call the courtyard.
I decide to book the standard room. “To book” (book) here means same as to reserve or to make a reservation. The “standard room” would be the normal, usually the cheapest room in the hotel – a standard room. If you want more expensive room you can get a suite (suite), those are usually bigger rooms.
The reservation agent asks me my name and I tell her. Then she says, “What major credit card would you like to use to guarantee the reservation?” A “major credit card” (three words), “major” here…well, you know what a credit card is. A major credit card” would be from a…from a big company, and the two biggest are, of course, Visa and MasterCard. In other countries there are, for example in Japan there is the JCB card, there’s also the American Express card, and there are a few others as well. These are major credit cards. To “guarantee the reservation” means that I have to put money…they take my credit card number in case I don’t cancel and I don’t show up to the hotel, they’re going to charge me anyway. So, it’s a way for the hotel to protect itself so it doesn’t lose money.
I then give the women my Visa credit card number. Of course, that isn’t actually my Visa credit card that you heard in the dialogue. In fact, that wasn’t even a Visa credit card number, it was just a made up number. I give the credit card number, usually in groups of four numbers, there are 16 numbers on a credit card, and I give the expiration date as “05/08,” meaning May 2008; “05” for the month, “08” for the year.
The agent gives me a “confirmation number,” and that’s a number that the hotel computer gives her so that I can…they can find my reservation if I have a problem.
Now let’s listen to the dialogue, this time at a native rate of speech.
[start of dialogue]
I just finished a huge project at work and I needed some down time. I decided to take a short vacation. I liked the idea of a long weekend out of town. My friend Sara offered to let me crash at her place in San Francisco, but I decided to stay at a hotel instead. Sara has a couple of roommates and I thought it might be too crowded.
I called the toll-free reservation number of a major hotel chain. The reservation agent was very helpful, after I got through the long phone tree.
Agent: Dutton Hotels. How may I help you today?
Jeff: I wanted to check rates and availability for your San Francisco location.
Agent: Certainly, I can help you with that. Will that be the downtown or waterfront location?
Jeff: The waterfront location.
Agent: What date do you plan to check in?
Jeff: I’d like to check in on October 12th and check out the 15th.
Agent: Okay, let me see what we have. For how many?
Jeff: One. And, if possible, I’m looking for a non-smoking room.
Agent: Sure, we have a non-smoking queen with an ocean view for 189 dollars or a standard room with a courtyard view for 139 dollars a night.
Jeff: I’d like to book the standard room.
Agent: Okay, your last name?
Jeff: Rama.
Agent: And your first name?
Jeff: Jeff.
Agent: Okay, I have you booked in a standard, non-smoking queen, checking in on October 12th and departing the 15th. What major credit card would you like to use to guarantee the reservation?
Jeff: A Visa.
Agent: The number and expiration?
Jeff: It’s 7388-2424-3535-1818, and the expiration is 05/08.
Agent: Your confirmation number PD672. Is there anything else I can help you with?
Jeff: No, that’s all. Thanks.
Agent: Have a nice day, and thanks for calling Dutton Hotels.
[end of dialogue]
The script for today’s podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. We’ll see you next time on ESL Podcast.
ESL Podcast is a production of the Center for Educational Development in Los Angeles, California. This podcast is copyright 2005. No part of this podcast may be sold or redistributed without the express written permission of the Center for Educational Development.
Glossary
down time – a period of time with little or no stress when one can relax, especially after a period of time when one has been very busy, worried, or stressed out
*All the college students are looking forward to having some down time after final exam week.
to crash – to stay at a friend’s house for a short period of time, especially when it is very informal and one might be sleeping on a couch instead of a bed
* Ward drank too much at the party to drive home safely that night, so he crashed at Robbie’s house.
toll-free – a telephone number that one can dial without being charged anything, usually beginning with 1-800, 1-877, or 1-866; a number for a free telephone call
* Does our company have a toll-free number for out-of-state customers to call?
hotel chain – a large group of hotels that have the same name and similar rooms and services, found throughout a region or country
* Whenever Marlys travels, she always tries to stay in the same hotel chain, because she really likes their free breakfast options.
agent – a customer service representative; a person whose job is to give information to customers, especially over the telephone
* Ask the agent if you can get a refund for last month’s charges.
phone tree – a computerized telephone system that guides one to the right person or department by asking a series of questions that the caller can either speak or type the answers to
* Our new phone tree tries to find out whether the caller has a question about sales or technical support, and then which device the caller needs assistance with.
rates and availability – the amount that a hotel room costs each night and when it is available (empty) for use
* The hotel’s website lists current rates and availability, but sometimes you can find out about special offers if you call the hotel directly.
downtown – in the center of a large city, especially where there are many tall office buildings
*The traffic is horrible downtown, so try to take the subway if you can.
waterfront – near the water’s edge; facing the water, usually a river or lake
* Marzyck has a waterfront office, and he enjoys watching the ducks fly around the lake while he works at his computer.
to check in – to begin one’s stay at a hotel, speaking with an employee to get a room assignment and room keys
* When we check in, don’t forget to ask for a room on the first floor, away from the elevators.
to check out – to end one’s stay at a hotel, speaking with an employee to make the payment and return one’s room keys
* Remember to check out by 11:30 a.m., or else you will be charged for one additional night.
non-smoking – a place where people are not allowed to smoke and where it does not smell like cigarette smoke
* Many cities are starting to pass laws that make all of their restaurants non-smoking.
queen – a large bed for two people; the most common size of bed for married couples; the second largest bed size
* Even though we have a queen bed, my wife is always kicking me at night, so we’ve decided to get a bigger, king-sized bed.
ocean view – with windows that face the ocean, allowing people to look out and see the water
* They asked for a room with an ocean view so that they could watch the sunrise without getting out of bed in the morning.
standard room – a basic, normal, ordinary room without anything special or fancy
* To save money while traveling, she always stays in a standard room.
courtyard – an open space surrounded by buildings or different parts of a single building, usually with many plants and benches where people can rest
* Whenever the weather is nice, Troy tries to eat lunch in the courtyard of his office building.
to guarantee – to provide some promise or assurance, especially that one will pay the amount of money that is owed, or fix something if it is broken
* Can you guarantee that my order will arrive by next Thursday?
confirmation number – a series of numbers and/or letters associated with a transaction that can be repeated to a customer service representative later to find information about that transaction
* Charlene always asks for a confirmation number whenever she buys anything online, so that if the package doesn’t arrive, she can call to complain.
Culture Note
Hotel Discounts
When “booking” (reserving; making arrangements for) a hotel room, it’s always “worthwhile” (worth the effort) to ask about any special “discounts” (reductions in price) that might be available. Many hotels offer discounted rates for certain groups of customers.
For example, sometimes “government employees” (people who work for the federal, state, or local government) can get a discount. People who “serve” (work) in the “military” (the people and organizations that protect the country, such as the Army, Navy, Air Force, and Marines) may also be “eligible for” (qualified to get) a discount, as well as members of their “immediate” (closely related) family. “Senior citizens” (people older than 65 years old) are also eligible for discounts at many hotels. Less commonly, students might be able to get discounts, too, although this is more common at “hostels” (very inexpensive hotels, usually with shared bathrooms).
Sometimes organizational “affiliations” (connections with an organization; membership) can make an individual eligible for special rates. “Presenting” (showing) an “AAA” (American Automobile Association) membership card can often “secure” (get) a lower rate.
Many hotel chains have membership programs for their most “frequent” (doing something often) customers. These customers might earn points each time they stay at the hotel, and when they “accumulate” (add up; collect) a certain number of points, they might be eligible for discounts or special services.
Finally, hotel guests can sometimes get discounted rates for booking their hotel room online and/or paying for the room online instead of doing it “in person” (while interacting face-to-face with another person) or over the phone.