= 0123
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 123: Pop and Jazz Music.
Hello and welcome to episode 123 of English as a Second Language Podcast. I am your host, Dr. Jeff McQuillan, from the Center for Educational Development in beautiful Los Angeles, California.
This podcast is going to be about popular music or pop music, as well as jazz. Let’s listen!
[start of dialogue]
Abby: Hey, what are you listening to?
Bill: Right now I'm listening to the Foo Fighters' latest album. There are some really good tracks on this CD, including their new single.
Abby: Let me see your iPod for a minute. It looks like you've got a ton of good stuff loaded up. I like Gwen Stefani, too, and what's this? Shakira? I had no idea you were a fan of hers.
Bill: I think she's a really talented singer and songwriter. And, well, she's hot, too.
Abby: Yeah, I bet. Let's see. You've got some great jazz and blues standards here, too. Charlie Parker, Duke Ellington, and Billie Holiday. This one is a live recording, and these are compilations. You've got their greatest hits and some bootleg stuff, too. I never knew you were such a jazz buff.
Bill: Yeah, I like all kinds of music. Now, where are you going with my iPod?
Abby: I thought I'd just borrow it for a little while.
Bill: Yeah, right. Hand it over. I've got to download my favorite podcast.
[end of dialogue]
Well, today’s podcast is about listening to different types of music and the vocabulary that we use to talk about that. The dialogue begins with Abby saying, “Hey, what are you listening to?” Notice that this is an informal conversation and the use of “Hey” (hey) is very common, particularly among the younger people. “Hey, what are you listening to?” And Bill says, “Well, right now I’m listening to the Foo Fighter’s latest album.” “The Foo Fighters” are a popular music group in the United States or used to be anyway. “The latest album” (album) – an “album” is – can also be called a “record” (record). Now, we often call it a “CD” – a compact disc – those are all – mean the same thing now. An
“album” used to be something that was big and black and made out of a material called “vinyl.” But now, it’s all digital and we still, however, use the term “album.” So, when a group releases – and that’s the verb we use – when they first put out an album, when they first sell an album, we say they “release” an album. We still use that term.
“There are some good tracks on this CD,” Bill says, “including their new single.” A “track” on a CD or on an album – (track) – is a song. So, a song can be called a “track.” A “single” (single) is a song that a popular group writes in order to have it played on the radio in order that it will be popular. And usually, songs or rather albums or CD’s have a number of singles that the musician – that the band hopes will become popular and so, they’ll make a video. a music video, for it. And they will send it to the radio stations.
Well, Abby says, “Let me see your iPod for a minute.” That expression “let me see” is very common to mean give it to me so I can look at it. “Let me see” means that you have to actually give the thing to the person. They don’t mean just hold it. Usually it means to give something to someone. So, “let me see your pen” means give me your pen so I can look at it or whatever I’m doing. Well, Abby says, “Let me see your iPod for a moment” – for a minute rather. She says, “It looks like you’ve got a ton of good stuff loaded up.” A “ton” (ton) is just an informal expression – informal use here – means a lot. If you have a lot of something, you can say, “You have a ton” (ton). “Ton” (ton) is also a way of measuring weight in English. And a “ton” is the same as 2,000 pounds, depending on the kind of ton. There are actually different kinds of tons. But normally we talk about a ton as 2,000 pounds. But here it just means a lot – a large number.
So, you have a ton of good stuff or good things loaded up. “To load up” (load) up your iPod, or your mp3 player, means to put things on it. So if you go to your iPod and you load up some podcasts, so you can listen to them on your drive to work, for example. Well, Abby likes Gwen Stefani who is a female rock singer – rather Bill likes Gwen Stefani because it’s Bill’s iPod. And he also likes Shakira. Shakira is a Colombian singer who is very popular in the United States. She records in Spanish and in English. Well, Abby says, “I had no idea you were a fan of Shakira.” “I had no idea” means I didn’t know. I had absolutely no idea. I didn’t know that you were a “fan.” A “fan,” of course, (fan) – someone who likes a particular group here. Bill says, “I think she’s a really talented singer and songwriter.” A “songwriter” is all one word – (songwriter) – is, of course who writes songs and that’s the noun – a “songwriter.” Then Bill says, “And well, she’s hot too.” This is an informal – kind of a slang expression. When you say a woman is hot or a man is hot, you mean they’re very beautiful. And usually, you also mean that they are very sexually attracted – that they are very good looking, very pretty, very beautiful. To say something is “hot” now has become a common slang term to say, “Oh that’s hot” – means that’s really great, that’s wonderful. Mostly a rich American girl, woman, by the name of Paris Hilton, has made that expression very popular, but the expression “She’s hot” or “He’s hot” is actually – goes back several years.
Well, Abby says, after Bill tells her that Shakira is hot, Abby says, “Yeah, I bet.” “I bet” (bet) means I’m sure that’s true. Here it means I’m sure that’s true. It actually, when someone says, “Yeah. I bet” – means that yes, I agree. I’m sure that’s true. But there’s also this idea that they don’t really like the idea that it is true or there’s some negative meaning, some negative idea that they are trying to convey. “To convey” (convey) means to tell you. Sometimes, we use that expression “I bet” when you don’t believe someone. Someone says, “I hear it is going to rain tomorrow.”
and you say, “Yeah, I bet.” – means you don’t believe it’s going to rain tomorrow. So, it can be very confusing. Usually, however, it means that you agree it’s true even though you don’t particularly like the fact that it is true.
Well, Abby says to Bill, “You’ve got some great jazz and blues standards here. “Jazz,” (jazz) of course, is a style of music that began in the 20’s and 30’s that was originally very popular among African American or black musicians. “Blues” (blues) is even older and is also – comes from the African American people who were living in the early 20th century. Of course, there are still jazz and blues players. “Blues” tends to be a little more – usually a little sadder type of music. Jazz – there’s lots of different kinds of jazz with all different sorts of instruments – musical instruments. A “standard” – when we are talking about a song. A “standard” (standards) – a “standard” is the same as a classic. It’s a song that was very popular many years ago. And that it was – the fact that it was very popular means that people still listen to it. So, a jazz standard or a blues standard would be a song from the past that’s still very popular today.
Bill’s iPod has Charlie Parker and Duke Ellington, those are two jazz artists, and Billy Holiday, who was a blues artist. When we say an “artist” (artist) – just like an artist who paints a picture, you can also be a “recording artist,” meaning you make – you’re a singer or a musician who makes albums. Abby also says that Bill has some “Greatest Hits” and some “bootleg stuff” too. “Greatest Hits” – two words – are the most popular songs of a group and often the group after several years, will put out an album. “To put out” means the same as to release an album, to start selling an album. They’ll put out an album of “Greatest Hits” – their best, most popular songs. “Bootleg” (bootleg) – all one word – is an illegal recording, usually at a concert where someone records the band and then sells it even though they do not have permission – they’re not supposed to. Abby also says that she didn’t know Bill was such a “jazz buff.” To be a “jazz buff” (buff) means the same as a jazz fan – someone who likes jazz music.
Well, Abby says that she wants to borrow Bill’s iPod and Bill says, “Yeah, right.” “Yeah (yeah) right” – when someone says, “Yeah, right” they mean no you can’t or I don’t believe that. “It’s going to rain tomorrow.” “Yeah, right” means no, it’s not going to rain tomorrow. You don’t think it’s going to rain tomorrow. Instead Bill says, “Hand it over.” “Hand (hand) it over” means give it back to me. “Hand it over” – it’s kind of a – there’s some negative connotation. Negative idea behind hand it over. You’re demanding, you’re almost forcing the person to give it back to you- to give something to you. Someone who is going to steal your wallet might say, “Hand it over” because you don’t have a choice. Bill says, “Hand it over.”
Now let’s listen to the dialogue this time at a native rate of speech.
[start of dialogue]
Abby: Hey, what are you listening to?
Bill: Right now I'm listening to the Foo Fighters' latest album. There are some really good tracks on this CD, including their new single.
Abby: Let me see your iPod for a minute. It looks like you've got a ton of good stuff loaded up. I like Gwen Stefani, too, and what's this? Shakira? I had no idea you were a fan of hers.
Bill: I think she's a really talented singer and songwriter. And, well, she's hot, too.
Abby: Yeah, I bet. Let's see. You've got some great jazz and blues standards here, too. Charlie Parker, Duke Ellington, and Billie Holiday. This one is a live recording, and these are compilations. You've got their greatest hits and some bootleg stuff, too. I never knew you were such a jazz buff.
Bill: Yeah, I like all kinds of music. Now, where are you going with my iPod?
Abby: I thought I'd just borrow it for a little while.
Bill: Yeah, right. Hand it over. I've got to download my favorite podcast.
[end of dialogue]
Of course, his favorite podcast is ESL Podcast. Remember to visit our website for more information about our other podcasts or if you want to send us an email. Our website is www.eslpod.com.
From Los Angeles, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
ESL Podcast is a production of the Center for Educational Development in Los Angeles, California. This podcast is copyright 2005. No part of this podcast may be sold or redistributed without the expressed written permission of the Center for Educational Development.
Glossary
album – a collection or group of songs sold together under one title or name; songs sold together as a set on a musical recording
* "Bringing Down the Horse" was the name of the second album created by The Wallflowers, and it had eleven different songs on it.
track – one song on an album; one song from a group of songs sold together under the same name or on the same musical recording
* Emerson’s favorite song was the second track, but he liked all the songs on the disc.
single – a recording of one song, usually played on the radio
* Laticia heard a new single from her favorite singer on the radio.
ton – a large amount; many
* Julius has a ton of work to do so he cannot relax or enjoy himself yet.
to be loaded up – for music to be put onto a device or other machine that plays music
* Ronda loaded up her computer with songs from her favorite bands and singers.
songwriter – someone who writes the words and/or music for a song
* Charles dreamed of becoming a famous songwriter who wrote lyrics and music for the most popular singers.
hot – attractive; very good looking
* Corey thought Naomi was a hot, and got nervous talking to her.
I bet. – I am sure you must be right.; a statement meaning that one believes or trusts what someone else has said must be true
* When Brooke told Gus that she was upset at her sister for lying to her, Gus replied, “I bet.”
jazz – a type of music created in the southern part of the United States beginning the 1910s and 1920s, with fast tunes and a complicated range or pattern of musical notes
* Noreen liked listening to jazz because she liked the upbeat tunes.
blues standard – a popular or well known song from the type of music known as blues, which is like jazz in style but focuses on sad or serious topics
* "Hound Dog" is a blues standard sung by many musicians, including Etta James, Albert King, Elvis Presley, and Jimi Hendrix.
live recording – a song that was recorded during a show or program where the song was played for an audience; a song or group of songs that were not changed or fixed very much after the songs were recorded
* The live recording was taken from a concert that the band played in London.
compilation – a group or collection of songs that come from different sources, like different singers or different albums
* The compilation album included songs sung by Tony Sheridan and The Beatles.
greatest hits – a collection of a musician's or musical group's most popular songs; a collection of the most popular songs from different musicians or musical groups
* After being in the music business for 10 years, the singer released his first greatest hits album, featuring his most famous songs.
bootleg – obtained against the rules or without having paid money; songs that were not sold by the musician or the music company, but were obtained from places that are not allowed to give or sell the music by law
* Brad got in trouble when his parents found out that he had downloaded bootleg songs onto the family's computer.
buff – someone who has a strong interest or love of a subject; someone who knows a large amount of information about a topic
* Layla was a history buff and knew many facts about political leaders from the 1800s and early 1900s.
Hand it over. – Give that to me.; a statement one makes to demand that someone else give one an item that he or she currently holds in his or her hands
* When Eduardo saw that Berta was holding the book he had been looking for, he told her, "Hand it over."
Culture Note
Old Music in New Packages
There have been many reports in the past 10 years that the music industry is losing money because people aren’t buying CDs anymore. Instead, people are downloading music, and many do it through “file-sharing” (moving files from computer to computer through the Internet), so that the music companies and the “artists” (singers; musicians) don’t get paid.
One way that the music industry is trying to “make up for” (compensate for; correct; fix) this lost income is by repackaging people’s favorite artists, putting together songs and adding material in a new way. They are counting on “diehard fans” (people who love something very, very much) to want everything, or at least something special, that is released for their favorite artist. Many of these new packages are “anniversary editions,” perhaps 10, 25, or 50 years after the album/CD was first released or since the birth or death of an artist. What do these “reissues” (re-releases) include?
Some very old recordings that came out in “vinyl” (flat, round disks played on a record player) are “re-mastered,” using today’s technology to improve the “audio” (sound) quality. Other reissues have “extras,” such as never-before-heard versions of songs, “commentary” (spoken comments) by the artist or people involved in making the music, and “remixes,” which are new versions of songs created electronically, often by changing the “tempo” (speed) or by putting them in a different order or adding parts to the songs. Some reissues even include DVDs of “live” (in front of an audience) performances or interviews.
These reissues and repackaged music can sell for a lot of money. But for diehard fans, it is a small price to pay to own something “new” from their favorite artists.