= 0131
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 131: Sharing an Apartment.
You’re listening to English as a Second Language Podcast episode 131. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this podcast, we’re going to learn about what it means to share your apartment with someone else. Let’s get started!
[start of story]
I've shared a two-bedroom, two- bath apartment with my roommate for two years. He was moving to Austin and I posted a "roommate wanted" ad in the local newspaper. I got a few calls, a couple from some very weird people. Finally, I got a call from Andrew. He seemed normal on the phone and we agreed he would stop by today to see the apartment.
When he got there, I showed him around. The apartment has a pretty large living room with a large couch and TV. It doesn't have a dining room, but it does have an eat-in kitchen. My room is the master bedroom with a connecting bathroom. My roommate's room was the guest room with the bathroom in the hall.
I told Andrew that he could use any of the furniture that my roommate was leaving behind. He was taking his bed and dresser, but he planned to leave his desk in the bedroom. I also told him that he could use any of the appliances? the refrigerator, microwave, and coffee maker.
Andrew said he liked the place and we agreed on the rent and to split the utilities. It was settled. He would move in next month. What a relief I didn't have to talk to any more weird people!
[end of story]
We’re talking in this podcast about sharing an apartment. “To share an apartment” means that two people live in the same apartment. In this story, the person is sharing a two-bedroom, two-bath apartment. And we use the term “bath” as short for bathroom. So, there’s two bedrooms and two bathrooms in a two-bedroom, two-bath apartment. He’s sharing the apartment with a “roommate.” And a “roommate” – all one word – (roommate) – a “roommate” is, of course, someone that is in the same room – although usually we use that if someone is just in the same apartment with you. We call that a “roommate.” You might also hear the term “housemate” which is also one word (housemate). Again, this would be someone who lives with you in the same house. We usually talk about roommates and housemates for people who are paying rent, that is, for someone who’s paying money to be there.
Well, the roommate of the person in our story is moving to Austin. And Austin is a city in the state of Texas. It’s actually the capital of Texas. And the person in the story decided to “post a roommate wanted ad” in the local newspaper. “To post an ad” (post) means the same as to place an ad or to put an ad in the paper. And the ad or advertisement was for a roommate. So, “roommate wanted.” When you are posting an ad or putting an ad and you want something or someone, that’s a very common way of doing it. So you could say, “Refrigerator wanted,” meaning you are looking for a refrigerator. Well, the same is true here, “roommate wanted.” If you’re looking for someone to work for you, you would say, it is a “help wanted.” So, the “help wanted” section of the newspaper is where the ads are for jobs.
Well, the person in the story got a few calls, a couple from some very “weird” people. “Weird” (weird) means strange, unusual. Los Angeles is full of weird people and if you ever come to Los Angeles, you will find that out. And, of course, I am one of those weird people, I think. Well, back to the story. Finally, the person gets a call from someone named “Andrew” and he “seemed normal on the phone,” meaning he wasn’t weird. He was normal. “On the phone” means when he talked to him on the phone. We use that expression “on the phone” also when somebody asks if you are talking on the telephone. You say, “I’m sorry, I’m on the phone.” I’m talking on the telephone. Any case, these two agreed that Andrew would stop by to see the apartment. “To stop by” – two words – (stop) (by) – means to go and visit and stay for a short time somewhere, usually at someone’s house or apartment.
Well, when Andrew got to the apartment, the man in the story showed him around. “To show someone around” means to take him to see all of the different parts, in this case, of the apartment. If someone says, “I’m going to show you around Los Angeles, they mean they are going to take you to different parts of Los Angeles to visit and to see. But “to show someone around in an apartment” means just to show them the different rooms of the apartment.
Now, the apartment was “pretty large.” And, of course, we use that word “pretty” (pretty) – “pretty” means very large here. “Pretty,” of course, also means beautiful. My wife is pretty, for example. But here it just means very. So, this apartment has a pretty large living room. And a “living room” (living) is the main part, usually, where people sit and talk. Usually, also, in an American house, there would be a television in the living room. Well, the living room has a large couch and a “couch” (couch) is the same as a “sofa.” It’s a place usually, where two or three or maybe even four people can sit and, of course, the TV. The apartment doesn’t have a “dining room.” And a “dining (dining) room” is where you dine. “To dine” (dine) means to eat. Not to be confused with the verb “to die” – “To dine” with an “n” and “to die.” Although, if you eat some really bad food, I guess you could dine and then die.
The apartment has an “eat-in kitchen.” “Eat-in” is hyphenated (eat-in), and that just means that it is big – big enough so that you could put a table in there and eat in the kitchen. The rooms in the apartment include the “master bedroom.” Now, the bedroom, of course, is where you sleep. The “master bedroom” is the biggest bedroom. And usually, in an American house or an apartment, the master bedroom has its own private bathroom for just the people. So to get to the bathroom, you have to use the master bedroom. It has its own separate bathroom. This story we hear it called the – a “connecting bathroom.” And a “connecting bathroom” just means the bathroom that is part of the master bedroom. It’s connected to the master bedroom. The roommate’s room was the guestroom. And the “guestroom” (guestroom) – the “guestroom” is, of course, where you have a, normally, a guest. It just means, in this case, the smaller of the two bedrooms. The guestroom has a bathroom in the hall. And the “hall” (hall) is the – usually a narrow – not a wide, but a narrow space where you walk and you have the doors to the other rooms in the hall. It’s also called the “hallway” (hallway) – all one word – and both of these are – another word I guess, would be a passage. It’s a place – it allows you to go from one part of the house to another part of the house. And usually, the bedrooms in a house are often, you get to them by going through the hallway.
Well, in this story, the person who is renting the apartment, who is looking for a roommate says that his new roommate can use any of the furniture that his old roommate was leaving behind and “to leave behind” just means to leave here. Usually, we use that verb “to leave behind” when we are talking about an object or a thing that you are leaving in a place. You can leave a thing behind or you could leave a person behind, meaning you go somewhere else and they stay where they are.
Well, his old roommate is taking his bed and his dresser. And a “dresser” (dresser) is a place where you keep your clothes. It usually has three or four drawers and a “drawer” (drawer) is like a little box. And you have two or three drawers – these little boxes that you put into a dresser – a larger piece that holds the individual drawers. Sometimes, this is actually called a “chest of drawers.” A “chest (chest) of drawers” – that means the same as a “dresser.” It’s a place where you keep things in drawers, in these little boxes that move in and out. Well, he plans on taking these two pieces of furniture and of course, “furniture” is just a general word we use for things that you use in your house that are big, like a table, chair, couch, a dresser – those are all types of furniture.
He can also use any of the appliances in the house. And an appliance (appliance) are the refrigerator where you keep food cold and the microwave, where you can heat up food quickly. A “coffee maker” is a little machine that you use to make coffee. I don’t drink coffee very much anymore. I usually drink tea, but we don’t call a thing to make tea, a “tea maker.” I don’t know if there is anything like that like a coffee maker.
Anyway, Andrew said that he “liked the place,” meaning he liked the apartment that he was looking at. And the two men agreed on the rent. And, of course, the rent (rent) is what you pay for an apartment or a house you may be renting. They decided to split the utilities. “Utilities” (utilities) are the gas, the electricity, the water. The telephone, sometimes, is called a “utility” – usually though it’s just the gas and the water and the electricity. And when you rent an apartment or a house or you buy a house or something like that, you have to pay separately for your water – that’s one government office. You also have to pay for your electricity and in the United States, electricity is all private companies. So, you pay a company for your electricity. Your gas, if you have gas, and in some parts of the country, they do not have natural gas – that you can go to a house. But in the older cities, cities like Los Angeles, we have gas and gas lines or pipes that come to the house, and that’s also a private company that you have to pay. So, each of those are separate and you have to pay them to the individual government office or private company. Well, to split the utilities – “to split” (split) means to divide – here divide in half. So, they’ll each pay half of the utilities. Andrew decided that he would move in next month. And “to move in” is a verb that we use – two-word verb – “move” (move) “in” (in) – when you are moving to a new apartment, or perhaps, even to a new office. We say we’re going to “move in” – basically the same as to move and that is what Andrew is going to do.
Now let’s listen to the story this time at a native rate of speech.
[start of story]
I've shared a two-bedroom, two- bath apartment with my roommate for two years. He was moving to Austin and I posted a "roommate wanted" ad in the local newspaper. I got a few calls, a couple from some very weird people. Finally, I got a call from Andrew. He seemed normal on the phone and we agreed he would stop by today to see the apartment.
When he got there, I showed him around. The apartment has a pretty large living room with a large couch and TV. It doesn't have a dining room, but it does have an eat-in kitchen. My room is the master bedroom with a connecting bathroom. My roommate's room was the guest room with the bathroom in the hall.
I told Andrew that he could use any of the furniture that my roommate was leaving behind. He was taking his bed and dresser, but he planned to leave his desk in the bedroom. I also told him that he could use any of the appliances? the refrigerator, microwave, and coffee maker.
Andrew said he liked the place and we agreed on the rent and to split the utilities. It was settled. He would move in next month. What a relief I didn't have to talk to any more weird people!
[end of story]
Our podcast script today was written by Dr. Lucy Tse and we thank her, as always, for her help in this podcast. Remember to visit our website at www.eslpod.com for the script for today’s podcast and for information on our other ESL related podcasts.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
roommate – someone who is not a relative but who lives in the same room, apartment, or house as one
* Even though they lived in the same home, Jeanette did not see her roommate much because they lived on different sides of the house.
to stop by – to visit a place briefly; to go to a place for a short period of time while on the way to another
* Edmund stopped by the store on his way home from work.
to show (someone) around – to show someone a space that he or she has never seen before; to guide someone around a place or location
* Marguerita's brother was visiting her university for the first time, so Marguerita showed him around.
living room – the main room in an apartment or house, usually with a sofa and other comfortable chairs for relaxing; the room in a house or apartment where people meet and relax together
* The family played a game in the living room every evening.
dining room – the room in an apartment or house where people eat their meals
* The dining room had a large table that fit 12 peoples for meals.
eat-in – a room, usually a kitchen, large enough for a table and chairs where people can eat an informal meal
* The family of four could eat at the small table in the eat-in kitchen, rather than the formal dining room.
master – master bedroom; the main bedroom, usually larger than any other bedroom in a home
* The parents slept in a master bedroom and their children slept in three smaller bedrooms.
connecting – attached; a room that is directly next to another room that one can get to directly, with no other rooms or paths in between
* Warner’s bedroom had a connecting bathroom, so he didn’t need to go out into the hallway to get to it.
guest room – an extra bedroom for visitors
* The Smith family had an extra room in their house, so they turned it into a guest room for visiting relatives and friends.
hall – a path someone walks down to reach a room or a set of rooms
* The hall connected the kitchen with a bathroom and a bedroom.
dresser – a piece of furniture that people store clothes in; a large wood box or cabinet that is divided into drawers, where people place clothing
* Teresa had a large dresser that held all of her shirts, jeans, and socks.
appliance – a machine or tool that uses electricity to do a task or job, usually in the home
* When the electricity did not work in the house, no one could use any of the appliances to finish any of their chores.
refrigerator – a metal box or cabinet using electricity where one stores food and drinks to keep them cold and fresh
* Perry put the milk inside the refrigerator to keep it cold.
microwave – a small machine with a door that heats and cooks food very quickly using electricity
* Silva cooked the rice in the microwave instead of on the stove.
coffee maker – a small machine one uses to make coffee (a hot brown drink made from ground beans and water)
* Marcus bought a coffee maker because he liked to drink coffee every morning.
rent – money one pays to live in an apartment or house that one does not own
* Carolyn wanted to move into the apartment, but she could not afford to pay the rent each month.
to split – to divide into equal parts; to pay equal parts of a bill or fee
* Terrell and Brittney split the cost of the restaurant meal.
utilities – services that one must pay for to have in one’s home, such as water, electricity, and gas
* Timothy did not pay for his utilities this month, so the electricity and water were turned off.
Culture Note
A House and a Home
The terms “house” and “home” are often used to mean the same thing: the place where you live. In many situations, these two words can be used “interchangeably” (one for the other).
However, these two terms can also have slightly different meanings. You would only use “house” to refer to a “stand-alone” (not attached to something else) building where you live. An “apartment” (a room or set of rooms in a building you rent), “condominium”/”condo” (like an apartment, but you can own your own unit), “townhouse” (like a house, but shares a wall with the house next to it, usually with a smaller yard than a house or no yard) are not usually called “houses.” On the other hand, you can use “home” to refer to any space where you live and sleep, including a house, apartment, condo, townhouse, and more. A good way to think about it is that “home” is the more general term and “house” is one type of “home.”
Keep in mind, however, that when people hear the word “home,” they often think of something else, something more than just a building or a room. We often “associate” (connect) “home” with a feeling of belonging and with a place where we feel comfortable. That’s why there are expressions like these: “Home is where the heart is,” meaning anywhere can be a home as long as the people you love and care about are there; “home sweet home,” which is something people say when they return to their home and are very glad to be there; and “a place to call home,” which is a place where a person feels he or she belongs. There is even an old song called “A House is Not a Home,” meaning that a building or room cannot make you feel like you belong there, or that your house is not necessarily where you can find the people you love.