= 0133
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 133: Going to a Wedding.
You’re listening to English as a Second Language Podcast episode 133. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development, here in beautiful Los Angeles, California.
On this podcast, we’re going to go to a wedding. Let’s go!
[start of story]
I got an invitation in the mail last month that really surprised me. My friend Ulrich was getting married! We went to college together and he always said that he’d never get married. I guess he found his dream girl in the end.
The church wedding was going to be at 3 p.m. and the reception would start at 7 p.m. at the reception hall.
I arrived at the church shortly before 3 p.m. and one of the ushers asked me if I was a friend of the bride or the groom. I told him that I was a friend of the groom and he sat me on the left side of the church. I saw Ulrich standing near the front of the church with the best man, and a few minutes later, the pianist started playing the wedding march. The flower girl and ring bearer walked down the aisle, followed by the bridesmaid. Then, the bride appeared wearing a beautiful wedding dress, walking with her father who was giving her away. The bride and groom exchanged vows and they were married. It was a simple and traditional ceremony.
At the reception, there was a lot of champagne. The best man made a toast that really embarrassed Ulrich, but it was all in good fun. I got a chance to talk to Ulrich and he seemed really happy. In fact, he was trying to set me up with the bridesmaid. I guess it's true. All married people want to get all of their friends married. We'll see about that!
[end of story]
Today we go to a wedding. Our story begins by the person saying he got an “invitation” in the mail last month. An “invitation” is, of course, when someone asks you to go to a party or a wedding or some special event. You send an invitation. And his friend, Ulrich, was getting married. Now, the two of them knew each other from college. They went to college together, or university together, and he said he would never get married – Ulrich said that. But, in the story, the narrator, the person telling the story, says, “I guess he found his dream girl in the end.” A “dream girl” – two words – (dream) “girl” – is the most perfect woman for you, the woman that you want to marry. She looks the way you want her to look and she acts the way you want her to act – that would be your dream girl. He says he found his dream girl in the end. And that expression “in the end” means after some time, after some time looking, in this case, he found his dream girl.
The church wedding was going to be at 3 PM. And in the United States, as in many countries, you can be married in a church, or you can be married – what we call a “civil ceremony.” “Civil” is (civil) and a “civil ceremony” means that you are married by someone from the government and that you are registered officially as “married.” Now, in the United States, if you are married in a church, by a minister or a priest, or a rabbi or whoever is the leader – if you are married in a church, you do not need to get married by the government. You do not need a separate ceremony to have your marriage recognized. The ministers and priests are authorized, you could say, are able to perform a ceremony and it doesn’t need – you don’t need to do an extra one. So, most people who do a “church ceremony” don’t do a civil ceremony and those who do a “civil ceremony” probably won’t do a church ceremony either.
Well, this is a church wedding, meaning it was going to be in a church and the reception – well, the wedding started at 3 P.M. The reception was going to start at 7 P.M and the “reception” (reception) – that is the party – that’s the party that you have after the wedding ceremony where there’s dancing and eating and perhaps drinking – that’s a reception and that’s a special word we use for a party after a wedding. You can also have a reception after another event and that, sometimes – word, is used sometimes also. The reception was going to be at the reception hall. And a “hall” (hall) here means a big building with a large – usually a large space where you can put many tables and have a – maybe a place for people to dance and food and there are many of these reception halls that you can rent for one night and some of them are run by church organizations, some of them are run by community – private community organizations. And there are even some governments, some city governments and county governments – the city government in the United States, would be, for example, the city of Los Angeles, but all of the states in the United States are broken up into larger units – you call them and these are called “counties.” So, the county and city government sometimes has its own places that you can rent for a reception.
In the story, the person arrived at the church shortly before three, and one of the ushers asked him if he was a friend of the bride or the groom. An “usher” (usher) – an “usher” is, at a wedding, or in a church in general, church or synagogue, I should say – it’s a person who helps you to your seat so things are a little more organized, a little more orderly. So, when you come to the back of the church, there’ll be an usher that will help you find a seat in the church. And in weddings, it’s traditional to ask the person coming, “Are you a friend of the bride?” And the “bride” (bride) – that’s the girl, the woman being married – or the “groom” (groom) – and the groom is the man. It depends which side of the church you sit on, if you’re a friend of the bride or a friend of the groom. If you’re the friend of both, you have to sit outside the church. No, no, no I’m kidding – joke. They’ll put you on whichever side you want to sit on. That’s how it’s done traditionally. “Usher,” by the way, the word “usher” is also a name of a famous singer in the United States.
Any case, going on with the story here, the person in our story said he was a friend of the groom and he sat on the left side because that’s where the friends of the groom and the family of the groom sit. He saw his friend Ulrich standing at the front of the church with the best man. And so, as it is probably in other countries, the tradition in the United States is that the man – the person getting married, the groom, usually with another man – a friend of his – and that friend and sometimes there’s more than one, but that friend is called the “best man” – the “best (best) man” – and he is responsible for - legally, he’s responsible for witnessing the marriage. “To be a witness” (witness) here means that you sign your name on the government form saying that yes, this person was married and I was there. “To witness” in general means to observe or to see something – usually, something official. Although, it can also be, if you see a crime or an accident, you are a witness to the accident, a witness to the crime. Well, there’s no crime here. They’re just getting married and the best man is a witness. Although, it might be an accident, the wedding, so, maybe you can use a witness for that as well.
The flower girl and the ring bearer are the first two people to walk up the aisle. The “aisle” (aisle) is the center of the church. Now, again, traditionally, the flower girl is a young girl – usually 5, 6, 7, maybe 10, or 12 years old at most and they are responsible for bringing up flowers for the bride. The “ring bearer” – and that’s two words – (ring) “ring bearer” which is spelled (bearer) – a “ring,” of course, is what you put on your hand and the bride and the groom both have rings. “Wedding rings,” we would call them. Well, the ring bearer brings those rings up to the best man or to the people standing in front, and that again is usually, traditionally a small, young boy – again four, five, six, maybe 10 or 12 years old. Often it’s a cousin or a younger sister or younger brother, depending on the family.
Well, the “flower girl” and “ring bearer” walked down the aisle, and notice, the verb there “to walk down the aisle” – that’s for some reason, we say that with that particular word “aisle.” So, you walk down, or you could “run down the aisle,” if you were late I guess. And after the ring bearer and the flower girl, there are the bridesmaids. And the “bridesmaid” is all one word (bridesmaid). A “maid” – traditionally in English – a “maid” is (maid) – is an unmarried woman, but in a wedding, we use the term “bridesmaid” for any girl or woman that is a friend of the bride and is going to be with her, standing with her when she gets married.
I mentioned before that we have the best man and for the woman, we have a “maid of honor.” The “maid of honor” (honor) is her best friend, the person that she has as her witness. And she is one of the bridesmaids. Well, the bride appears, in our story, wearing a beautiful wedding dress, traditionally white dress in American weddings, and she’s walking down the aisle with her father who was “giving her away.” Again, the tradition is if a woman is getting married, her father, although sometimes her father and her mother, but traditionally her father, walks with her and gives her away. Now, it’s kind of a strange expression. When we talk about the verb “to give away” - two words – “give away” usually means you’re giving something like you’re giving away your pen to someone. You’re giving them your pen. But here, we use this very special case in a wedding. “To give away the bride” means you’re the person that – the father usually that sort of gives his daughter to the husband, to the man. It’s very old, very old tradition and some couples do that and some couples don’t do that anymore.
The bride and groom then, are ready to get married, finally. And they exchange “vows.” “To exchange (exchange) vows” – two words – (vows) – “exchange vows” means that they say that they will love the other person and they promise to be – we’d say, promise to be faithful. “To be faithful” means that you will only be in love with that person and will only be with that person, romantically anyway, and this is called a “vow.” And a “vow” is like a promise that you are making. And the traditional promise, you’ll see in movies and some very traditional weddings, the priest or the minister or the rabbi will say, “John, do you take this woman, Maria, to be your lawfully wedded wife?” “Lawfully” means legally and “wedded wife” is kind of – just wife would be good enough but the expression is a “wedded wife.” And the man says, “I do.” And of course, the woman is asked the same question. I forgot her name – Maria – “Maria, do you take this man to be your lawfully wedded husband?” And she says, “I do.” And then they kiss and it’s all happy, at least for the first couple of days.
At the reception, there is a lot of champagne. “Champagne,” of course, is that special alcoholic beverage – technically comes from an area in France. But now, people use that word for things that don’t come from France – special kind of wine.
The best man makes a toast. A “toast” (toast), you may know, is when you raise your glass. When you lift your glass up and say something funny or nice, in this case, embarrassing about the groom or the bride and groom. But even though this toast embarrassed Ulrich, the groom, “it was all in good fun.” “It was all in good fun,” meaning he didn’t mean it in a bad way, it was just for a joke.
Well, at the end of the story, the man talks to his friend, Ulrich, and he says that Ulrich was trying to set him up with the bridesmaid. “To set someone up” is when you have a friend, for example, and you know another friend – woman – let’s say and you think that those two would be a good couple. So, you say to your friend who’s a man, “I want to introduce you to my friend” – my female friend, my woman friend – and the idea is that he is setting them up. He is helping them get together, to be romantically involved. Well, the man in the story says that all married people, want to have all of their friends married too. And the story ends with the expression “We’ll see about that.” “We’ll” (we’ll) – as in we will – “We’ll” or “We will see about that” – that expression means that the person doesn’t agree or doesn’t want to do whatever is being talked about and plans on not doing it, or in this case, he plans on not getting married. “We’ll see about that” means I don’t think so. And that is a common expression when you want to tell someone that you don’t – you aren’t going to do what they want you to do, in this case.
Now let’s listen to the story again, quickly at a native rate of speech.
[start of story]
I got an invitation in the mail last month that really surprised me. My friend Ulrich was getting married! We went to college together and he always said that he’d never get married. I guess he found his dream girl in the end.
The church wedding was going to be at 3 p.m. and the reception would start at 7 p.m. at the reception hall.
I arrived at the church shortly before 3 p.m. and one of the ushers asked me if I was a friend of the bride or the groom. I told him that I was a friend of the groom and he sat me on the left side of the church. I saw Ulrich standing near the front of the church with the best man, and a few minutes later, the pianist started playing the wedding march. The flower girl and ring bearer walked down the aisle, followed by the bridesmaid. Then, the bride appeared wearing a beautiful wedding dress, walking with her father who was giving her away. The bride and groom exchanged vows and they were married. It was a simple and traditional ceremony.
At the reception, there was a lot of champagne. The best man made a toast that really embarrassed Ulrich, but it was all in good fun. I got a chance to talk to Ulrich and he seemed really happy. In fact, he was trying to set me up with the bridesmaid. I guess it's true. All married people want to get all of their friends married. We'll see about that!
[end of story]
That’s going to do it for today’s podcast.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
invitation – a written or spoken message to ask someone to come to an event
* Patrick got an invitation asking him to go to his aunt's birthday party.
dream girl – a girl with one’s ideal personality and characteristics
* Michael told Denise that he loved her because she was his dream girl.
church wedding – the act of getting married inside of a church, temple, or other religious location
* Diana was very religious and wanted to have a church wedding once she found a man to marry.
reception – a party that occurs after a wedding (the ceremony to get married) to celebrate or honor the married couple; a party that happens after an event that celebrates the event
* After the award ceremony, the high school held a reception to honor the students who received awards.
usher – someone who leads guests to the correct seats
* There were two ushers at the wedding, and they led 200 guests to their seats.
bride – a woman getting married at a wedding ceremony
* All the guests at the wedding thought that the bride looked very beautiful.
groom – a man getting married at a wedding ceremony
* The groom was happy about getting married, but he also felt nervous.
best man – a man who stands next to the groom (the man getting married) and helps the groom during the wedding, usually a close relative or friend
* The best man helped the groom get dressed before the wedding.
flower girl – a young girl who covers the path to the altar with flower petals before the bride walks down the path
* The flower girl threw pink rose petals as she walked to the altar.
ring bearer – a young boy who holds the wedding rings for the two people getting married, which they place on each other’s fingers during the ceremony
* The ring bearer carried the rings to the bride and groom on a shiny white pillow.
aisle – the path to the altar; a path that the woman getting married walks down to reach the place where she will stand during the wedding ceremony
* The groom stood near the altar and watched his bride walk down the aisle.
bridesmaid – a woman who stands by the bride (the woman getting married) and helps the bride during the wedding, usually a close relative or friend
* One of the bridesmaids held the bride’s flowers during the wedding.
to give the bride away – for a male relative, usually the father, to walk the bride down the aisle to the altar during the wedding ceremony
* The man who gave the bride away to the groom was the bride’s father, and he trusted the groom with his daughter’s future.
to exchange vows – during the wedding ceremony, for the two people getting married to promise to love and stay loyal to each other
* Rosalind and Reginald exchanged vows, promising to stay with each other through good times and bad times.
champagne – an alcoholic drink with a light color and many bubbles (pockets of air), usually used for parties and special events
* Marina drank champagne at the New Year’s Eve party.
toast – a speech or spoken statement honoring a person or event, usually said while holding a drink, with guests all drinking together after the statement; a speech to honor a bride and groom at a wedding
* Eduardo made a serious toast at his brother’s wedding.
all in good fun – meant as a joke; meant to cause laughter
* Sheldon teased Erika about her new hair style, but it was all in good fun.
to set someone up – to introduce someone to someone else with the hopes that the two people can form a romantic relationship
* Katherine’s brother tried to set her up with his best friend, since his best friend was a nice guy who was not currently in a relationship.
Culture Note
The Cost of Wedding Cakes
The costs of having a wedding in the United States can be very high. While some people prefer a simple “wedding ceremony” (official event to get married) and “reception” (party or celebration after a wedding or other ceremony), some “couples” (two people who are together romantically) “go all out” (do the maximum; do something without limits).
The reception itself can be very “costly” (expensive). The price of “renting” (paying money to use a place for a short time) a place to hold the reception and “catering” (professional service to provide food for guests) can really “run up the tab” (add up to a high price).
One of the major expenses is the wedding cake, which can be very “elaborate” (fancy; complicated, with many parts). According to a 2007 Reader’s Digest article, real wedding cakes in the U.S. cost an average of $550.
But now, there’s one way to cut costs: a fake wedding cake! To save money, some Americans are buying a “replica” (copy) made of “foam,” the white materia used to pack the inside of packages to prevent the contents from breaking. In these fake cakes, there is a secret compartment or section for the first “slice” (piece) of cake that is “cut” and eaten by the bride and groom. The tradition is for the bride and groom to feed each other the cake, often with their hands, and it can get very messy. Once that part of the wedding reception is over, the fake cake is taken into the kitchen and the guests are served slices of a much less expensive cake.