= 0141
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 141: A Brainstorming Session.
This is English as a Second Language Podcast number 141. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Today’s podcast is about people who are trying to come up with new ideas at a brainstorming session. Let’s get started!
[start of story]
Judy: I've called this meeting so we can brainstorm some fundraising ideas. As you know, we're in danger of closing. Any thoughts?
Stan: I thought that Juan was working on getting donors.
Judy: He is, but we can't count on that coming through.
Dominique: How much do we need to raise? What's a ballpark figure?
Judy: We need at least $50,000 for next year.
Dominique: That's a lot of money, but I think we'll come up with something. How about a benefit performance?
Stan: That sounds promising. Who can we get to perform?
Judy: It would be great to get someone like Barry Manilow.
Dominique: I think we're shooting too high. I was thinking more like a local band or comedy group.
Stan: I've got it. My brother works for The Improv. He knows a lot of comedians from this area. Maybe we can get a few of them to perform.
Dominique: That would be great.
Judy: I like how this is shaping up. We're out of time, but let's meet again on Friday to hammer out the details. Thanks everybody.
[end of story]
The title of this podcast is “A Brainstorming Session.” “To brainstorm” (brainstorm) – as a verb – means that you and someone else, perhaps a group of people, get together and you try to think of ideas to solve a problem – that is to brainstorm. And a “session” is simply the same here as a meeting. Well, there are three people in today’s podcast having a brainstorming session. Judy begins by saying, “I’ve called this meeting so we can brainstorm some fundraising ideas.” The verb “to call” means, of course, you can call someone on your telephone, but we also use the verb “to call” with the idea of a meeting. “I’m going to call this meeting,” means I’m going to organize this meeting. Well, the meeting is to “brainstorm some fundraising ideas.” Once again, that verb “to fundraise” (fundraise) – all one word – “to fundraise” means to try to make money, usually for an organization. A volunteer organization, for example, would try to do fundraising. And the noun for that is “fundraiser.” Someone might say, “We’re having a fundraiser for my church.” So, you are trying to make money. The verb would be “to raise money” for your organization.
Judy says that their organization is “in danger of closing.” “In danger of,” means that it hasn’t happened yet, but it could happen and it’s always a negative thing that could happen. So, for example, you tell your boss that he is an idiot, that he’s stupid. Well, you are now in danger of losing your job. So, that’s the meaning of “in danger of.” It’s when something bad may happen. There’s a possibility, it could happen.
Well, in this dialog, their organization is in danger of closing. And notice also that we use the “ing” form of the verb. So, not “in danger of close,” but “in danger of closing,” or shutting down. Stan recommends that – or comments rather – that he thought Juan was working on getting donors. A “donor” (donor) is, as you probably know, someone who gives money. The verb is “to donate” (donate). And Judy says that yes, he is. Juan is working on getting donors. I should probably explain “He is working on” and the “ing” form, “getting.” “I am working on finishing my paper” – that means I am trying to, I am in the act of finishing my paper. Well, Judy says that they can’t “count on that coming through.” “To count on” (count) – two words – means to depend upon, to rely upon, to think that it is going to happen. People sometimes say, “Don’t count on it,” meaning don’t rely on that, it may not happen.
“To come through” here as a verb – “to come through” (through) – means that – we use that expression, that verb “to come through,” talking about someone who is going to help you, usually, out of a difficult situation and they haven’t yet helped you, but you hope that they will do what they promised to do. And so, we’d say, “Well, I hope he comes through with that money,” meaning he says he was going to find the money so let’s hope he, in fact, does. And it’s usually used when you’re trying to help someone out of a difficult situation. Dominique says, “What’s a ballpark figure?” for how much money they need. “What’s a ballpark figure?” “Ballpark” (ballpark) – all one word – a “ballpark” is a place where you play baseball, for example, or football – it’s a big stadium. But the expression “Ballpark figure” – and “figure” (figure) – just means here, number. We use that expression “A ballpark figure” to mean an estimate, an approximate number. Someone says, “Well, I’m not really exactly sure how much,” and you say, “Well, give me a ballpark figure” – that means an estimate, a guess. It may not necessarily be true, but it’s a guess, a good guess – that’s a ballpark figure.
Judy says they need $50,000. Dominique says, “That’s a lot of money,” and she suggests a “benefit performance.” A “benefit (benefit) performance” – a “performance” is usually a show or, for example, you could have a symphony orchestra or a band or a play – all of these could be performances. It’s when they actually sing or dance or whatever it is. Well, a benefit performance is a special performance where people pay money to see the entertainment – the performance. And that money goes to the organization to help the organization. Stan says, “This sounds promising.” That expression “It sounds promising” means it sounds like it’s a good idea. It sounds like something that will actually work. You can also say, “It looks promising.” For example, “I went on an interview for a new job because I told my boss he was stupid and fired me.” And the person – my friend says, “Well, how does it look?” And I say, “Well, it looks promising,” meaning I think I may get the job if I can keep my mouth shut.
Dominique says, “We’re shooting too high,” because Judy recommends getting Barry Manilow as a singer. Barry Manilow is an American singer from the 1970’s and 80’s. I guess he is still alive and Barry Manilow is – he must be in his 90’s, I think. Anyway, he is a famous American pop singer. And Dominique says, “I think we’re shooting too high.” “To shoot (shoot) too high” means, or we also say “to aim (aim) too high” – means that you are trying to do more than is possible – trying to get a big famous singer – that’s not going to be possible. It’s shooting too high. It’s too difficult. Stan recommends that they try another solution. He says, “I’ve got it,” meaning I have an idea. I have the solution. His brother works for “The Improv.” An “Improv” (improv) is short for “improvisation” and it’s a place where you have comedians, where people get up and tell jokes. And there’s actually a place here in Los Angeles called “The Improv” and it’s a place where you can go see famous comedians. Well, Stan says he knows a lot of comedians and a “comedian” (comedian) is someone who tells jokes – better than me.
Judy says, “I like how this is shaping up.” “To shape up” (shape) up (up) – two words – “to shape up” means you like how things are developing. You like how things are turning out – are progressing – are coming along – all of those are the same. “To shape up” – “things are shaping up.” Now, there’s another use of that verb “to shape up” and it’s sometimes used to mean to improve yourself. If your mother says, “You need to shape up” means you need to behave better. You need to act better. You need to improve yourself.
Judy says that they’re “out of time,” meaning they have no more time for their meeting but they agreed to meet on Friday to “hammer out the details.” “To hammer (hammer) out (out)” – two words. Well, a “hammer” is what you use to put a nail – a little piece of metal in wood, for example. You hammer it. It’s long and it has a little – usually made of some sort of metal and it’s hard and it’s made for hitting. Well, “to hammer out,” however, means to figure out, to go over all of the smaller details. You can use this verb, for example, when you’re talking about an agreement or a negotiation. “We’re going to hammer out the details” means we’re going to figure them out. We have the big general idea, now we’re going to talk about the – each individual item and all of its details.
Now let’s listen to the dialogue this time at a native rate of speech.
[start of story]
Judy: I've called this meeting so we can brainstorm some fundraising ideas. As you know, we're in danger of closing. Any thoughts?
Stan: I thought that Juan was working on getting donors.
Judy: He is, but we can't count on that coming through.
Dominique: How much do we need to raise? What's a ballpark figure?
Judy: We need at least $50,000 for next year.
Dominique: That's a lot of money, but I think we'll come up with something. How about a benefit performance?
Stan: That sounds promising. Who can we get to perform?
Judy: It would be great to get somebody like Barry Manilow.
Dominique: I think we're shooting too high. I was thinking more like a local band or comedy group.
Stan: I've got it. My brother works for The Improv. He knows a lot of comedians from this area. Maybe we can get a few of them to perform.
Dominique: That would be great.
Judy: I like how this is shaping up. We're out of time, but let's meet again on Friday to hammer out the details. Thanks everybody.
[end of story]
Thank you for listening to today’s podcast. It was written as always, by Dr. Lucy Tse. We also want to thank Dr. Marlene Rodriguez who helped us with reading the dialog today. Thank you, Marlene!
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2006.
Glossary
fundraising – making money to support a cause or organization; formally asking other individuals to give money for a cause or group
* The school needed to buy new books, so the teachers held a fundraising event to raise money.
in danger of – dealing with a risk; with the possibility of a negative result
* Carlotta would not take her medicine and was in danger of making her illness worse.
to count on – to rely on; to depend on
* Enrique was a very honest person and his friends could always cont on him to tell the truth.
to come through – to solve a problem; to help in a situation that seems worrying or hopeless
* The bank came through on the loan, so the family was able to purchase a house.
ball-park figure – an estimated amount of money
* The car salesperson gave Sally a ball-park figure of $25,000 to buy the car, but the car actually cost $26,500 with all of the taxes and fees.
benefit performance – an entertainment show, such as a concert, comedy show, or dance performance, organized to raise money for a cause or group
* The famous band played at the benefit performance to raised money for medical research.
to sound promising – to seem like a good idea; to seem like a plan that will work
* Gill’s idea about spending less money by eating fewer snacks sounds promising.
to shoot too high – to set goals that are too difficult to achieve; to have unrealistic expectations
* Belle and John were shooting too high when they planned on taking an expensive trip to Europe with only $500 to spend.
I've got it. – a statement made when someone has an idea that he or she believes will solve a problem or answer a question
* Rachel solved a difficult mathematic problem, and she said aloud, “I’ve got it!”
comedian – an individual who tells jokes to an audience
* The first comedian was very funny, but the audience had trouble understanding the second comedian’s jokes.
to shape up – to form; to develop
* Peter studies more than he used to and is shaping up to be a good student.
to hammer out the details – to determine the details of a complicated project; to plan specific details not already talked about or decided
* Jacques decided to open a bakery but still needs to hammer out the details.
Culture Note
Factors that Help and Hinder Creativity
Why are some people more “creative” (able to think of new and original ideas) than others? Psychologists have “sought” (looked for) an answer to this question for many years, with some interesting “hypotheses” (guesses; theories). Dean Keith Simonton at the University of California, Davis, is well known “in the world of” (field of; area of) psychology as the “leading” (one of the top or best) researchers in this area. Simonton has identified several “factors” (influences; items) that may influence creativity. Here are some of those, “categorized” (classified) by whether they help or “hinder” (hurt) creativity:
Help: Being born last in the family. Younger members of the family will get to see different kinds of “role models” (people whose actions and ideas you may want to imitate) and are “exposed to” (experience) family conflicts and how they are resolved. These experiences can “fuel” (increase) original thinking.
Hurt: Being born first in the family. First-born children are more likely to think in “conventional ways” (traditional or commonly accepted ways).
Help: Taking time off. Taking a break from your work allows your ideas to “incubate” (develop slowly without interruptions) and gives original ideas a chance to grow.
Hurt: Resistance to change. People who don’t want to change are almost “by definition” (by that very fact) people who cannot be very creative, since being creative means doing something original and that hasn’t been done before. Interestingly enough, Simonton found that those who too easily give up on an idea are also less creative. Sometimes we need to continue with an idea even though some of our ideas fail.
Help: Freedom to take risks. It’s hard to be creative if your boss won’t ever let you do anything different. Being able to work on a “variety of” (mixture of; different) things can help you think in different ways, and “thereby” (because of that fact) be more creative.
Hurt: Pressure to play it safe. To play it safe means to never take any risks, to always do things that have no possible danger involved. Again, almost by definition, this is something that will make you a less creative person, since creativity means sometimes doing things that might fail or even hurt your chances in the future.