= 1472
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 167.
This is ESL Podcast’s English Café episode 167. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. On it, you can visit our ESL Podcast Store, which has some additional courses in daily and business English that you will enjoy. You can also download the Learning Guide for this episode, and every current episode. The Learning Guide contains lots of additional information, including a complete transcript of this episode, vocabulary words, definitions, sample sentences, cultural notes, and a comprehension quiz on what you’re listening to now.
On this Café, we’re going to have another one of our Ask an American segments, where we listen to other native speakers talking at a normal rate of speech – at a normal speed. We’re going to listen to them and explain what they are saying. Today we’re going to talk about a topic that is controversial in the United States: underage drinking, or young people who drink before they are 21 years old, which is the legal age for drinking alcohol in the United States. As always, we’ll answer a few of your questions as well. Let’s get started.
Our topic on this Café’s Ask an American segment is underage drinking. “Underage” drinking happens when young people drink before they have reached the legal drinking age. As I mentioned, in the United States, the legal drinking age is 21. In other words, it’s against the law to drink alcohol before you are 21 years old. But many young people do it anyway.
In the past, different states had different drinking ages. Many states had a legal drinking age of 18 years old. When I was in high school and in college, in my state (the state of Minnesota) the drinking age was 19. The drinking age in the state next to Minnesota, Wisconsin, was 18. So, states used to, in the past, have different drinking ages. This, of course, would cause people to drive to the states where the drinking age was lower. So, because it was 19 when I turned 19, that’s when I could start drinking. But a few years later, in 1984, the U.S. federal (or national) government passed (or approved) the National Minimum Drinking Age “Act,” or law. This act (or law) made it illegal for anyone less than 21 years old to buy or “possess,” that is, to have alcohol in public.
Now normally, the way our Constitution is set up (our government is set up in the U.S.) the states have a right to determine a great many things, including things like the drinking age. So how is it possible for the U.S. government (the federal government and the president) to “put into place” (to approve) a law for drinking in all the individual 50 states? Well, the answer is something called the Federal Aid Highway Act. Now, the Federal Aid Highway Act gives states money to build highways. So, what the government said is “Well, we can’t force you to change your drinking age, but we are not going to give you all of your money for the freeways and highways unless you change your law to make the legal drinking age in your state 21.” Well, if states wanted to get all of the money, they would have to change their own laws. So, this was an effective way for the federal government to force states to do things that, constitutionally, the federal government does not have the power to do. But, it does have the power over its own money, and this is how it forced states to change their drinking laws. The government has done this in other cases as well, when they want the states to do something that they think is right and the individual state may think is wrong.
Teenage drinking is “controversial,” something that people don’t agree on. The U.S. system of laws that have legal ages for doing something are very inconsistence; we have different laws for different activities. For example, Americans, in most states, can drive when they are 16 years old. But, they cannot vote or serve in the army until they are 18 years old. And they can drink alcohol and “gamble,” or play games to try to win money when they are 21 years old. So, the laws are different for different things. Many people think these laws are not fair. Specifically, they think it is wrong that an 18-year-old can vote and serve in the army to fight for his or her country, but is not allowed to buy a beer.
Other people say that “prohibiting” young people from drinking, or not allowing them to drink alcohol, makes them more likely to want to drink, and to drink dangerous amounts when they have an opportunity to drink alcohol illegally. Drinking a lot of alcohol all at once (at one time) is known as “binge” (binge) drinking. According to a study by the National Institute on Alcohol Abuse and Alcoholism, between 1991 and 2003, the rates of binge drinking increased among 12- to 20-year-olds (that is, those who are too young to drink legally) from 15.2 to almost 19 percent . So, one out of every five teenagers is binge drinking – is not only drinking illegally but drinking a large amount of alcohol at one time when they do drink.
We’re going to listen now to some students – some college students talking about underage drinking. We’ll listen first. Try to understand as much as you can, and then we’ll go back and explain what they said. You’re going to hear four students talking, and each quote is rather short. Let’s listen:
[recording]
Female student: “If 18-year-olds can have access to alcohol, that doesn’t mean that 14-year-olds can’t access it either.”
Male student: “You need some consistency with the driving age and the smoking age.”
Female student 2: “If the drinking age were lower, people might be more comfortable with it. If it wasn’t such a rebellious thing, maybe people would, you know, not think of it as being cool.”
Female student 3: “I personally don’t drink, so I really don’t have a problem with it being 21.”
[end of recording]
We heard three women and one man give their opinion about underage drinking; let’s go back and take a closer look at what they said. The first student says, “If 18-year-olds can have access to alcohol, that doesn’t mean that 14-year-olds can’t access it either.” “Access” (access) means being able to get or have something. So an 18-year-old isn’t supposed to have access to alcohol, because 18-year-olds aren’t allowed to go to a store and buy it legally. What the woman is saying here is that if they can get an older person to buy it, then they can have access to alcohol. This is a common argument for not lowering the drinking age below 21. The idea that if you lower it to 18, then the 18-year-olds will buy it for 14-year-olds or younger students, and the likelihood that these very young students (14-15-year-olds) would know a 21-year-old is less than if they would know an 18-year-old.
The second student says that you need some consistency with the driving age and the smoking age. “Consistency” means doing things the same way each time, without changing it. So he means that the legal age for drinking, driving, and smoking should all be the same, they shouldn’t be different – they should be consistent.
The third student says that if teenage drinking were allowed, if the drinking age were lower, people might be more comfortable with it. She says, “If it wasn’t such a rebellious thing, maybe people would not think of it as being cool.” To “rebel” (rebel) means not to obey the rules, or not to listen, for example, to one’s parents or one’s teachers. Many teenagers are called “rebellious” (using the adjective now) because they do things that their parents don’t want them to do. One way that teenagers can be rebellious is to drink when they are younger than the drinking age – the legal drinking age. So, what she’s saying is that because the drinking age is now 21, drinking when you’re a teenager is a way of rebelling – of being rebellious, of being cool. If the drinking age were lower, it would no longer be rebellious to drink because it would be legal and therefore teenagers wouldn’t do as much of it. That’s her thinking.
The last student says that she doesn’t drink, so she doesn’t have a problem with, or doesn’t she disagree with, the current legal drinking age of 21.
Now let’s listen to the four students again:
[recording]
Female student: “If 18-year-olds can have access to alcohol, that doesn’t mean that 14-year-olds can’t access it either.”
Male student: “You need some consistency with the driving age and the smoking age.”
Female student 2: “If the drinking age were lower, people might be more comfortable with it. If it wasn’t such a rebellious thing, maybe people would, you know, not think of it as being cool.”
Female student 3: “I personally don’t drink, so I really don’t have a problem with it being 21.”
[end of recording]
Underage drinking is a serious problem at many universities, where most or many students are less than 21 years old. Let’s listen to Jonathan Gibraltar, the president of a university in Maryland, which is on the east coast of the United States, next to Washington, D.C. He’s going to talk about why underage drinking is a bad thing, and he is against changing the drinking age to 18.
[recording]
“Every year, of the millions of kids who go away to college, 1,700 die due to binge drinking and the behaviors associated with binge drinking. And then if you add to that the numbers who die in automobile accidents, DUIs, DWIs, sexual assault, physical assault, date rape, the numbers of incidents go up into the hundreds of thousands a year. So, I don’t ever want to call a parent and tell them that their son or daughter died the night before because they were binge drinking.”
[end of recording]
That was a long quote; let’s go back and talk about what he said. He starts by saying that every year, of the millions of kids who go away to (or who attend) college, 1,700 die due to binge drinking. He’s saying that there are 1,700 students every year who die from binge drinking and the behaviors associated with binge drinking. He says that there are many students who die from things that are related to binge drinking, and then he gives us some examples of that. They could die from automobile accidents; if a person is drinking and driving, they cause more accidents and can kill themselves and others. He mentions DUIs and DWIs. “DUI” means driving under the influence – driving under the influence of alcohol or some other drug. To “drive under the influence” means that you are driving drunk, you have been drinking and then you start driving. “DWI” is similar, “DWI” means driving while “intoxicated,” meaning that you are driving when there is so much alcohol in your body that you cannot drive effectively.
He also says that binge drinking is related to sexual assault and physical assault. An “assault” (assault) is a physical attack on another person. So, “sexual assault” would be a sexual attack on another person, usually a man against a woman. He also mentions something called “date rape.” Rape happens when a man forces a woman to have sex with him, usually by using violence. Date rape happens when the man is usually someone the woman knows, often a friend or someone that she is dating. This person then forces the girl or women to have sex with him, even though they’re not strangers – they know each other. Jonathan Gibraltar, this president of the university in Maryland, says that date rape is associated with binge drinking, and that there are hundreds of thousands of these types of problems on college campuses every year. As the president of a university, he doesn’t want to have to call the parents of a student to tell those parents that the student died because he or she was binge drinking. So, he’s saying that binge drinking causes all of these serious problems, and that he doesn’t want those problems to continue.
Let’s listen again:
[recording]
“Every year, of the millions of kids who go away to college, 1,700 die due to binge drinking and the behaviors associated with binge drinking. And then if you add to that the numbers who die in automobile accidents, DUIs, DWIs, sexual assault, physical assault, date rape, the numbers of incidents go up into the hundreds of thousands a year. So, I don’t ever want to call a parent and tell them that their son or daughter died the night before because they were binge drinking.”
[end of recording]
Not all college presidents agree with this analysis. David Oxtoby, who’s the president of a college here in Southern California, believes that changing the legal drinking age to 18 years old would actually help to “curb,” or reduce, binge drinking. Let’s listen to what he has to say:
[recording]
“I think if we were able to show responsible drinking, and model responsible drinking, and educate students about it, that would be very beneficial for everyone.”
[end of recording]
He says that he thinks people should model responsible drinking, or drinking alcohol in a way that isn’t dangerous. To “model” something means to set an example, to show someone how to do something. If you have a young child, you may want to model good table “manners,” good polite ways of eating and acting, because your son or daughter will watch you and learn from your example. That’s modeling a behavior – modeling the way you should act. David Oxtoby says that modeling responsible drinking and educating students about that topic would be very “beneficial,” or good for everyone. Let’s listen to him again:
[recording]
“I think if we were able to show responsible drinking, and model responsible drinking, and educate students about it, that would be very beneficial for everyone.”
[end of recording]
Finally, we’ll listen to a “legislator,” that is, someone who is a government representative in the State of Maryland, who is against lowering the drinking age, who agrees with the first college president, Mr. Gibraltar about the dangers of lowering the drinking age to 18. Once again, he’s going to talk about all of the problems that could be caused or made worse if we lower the drinking age. Let’s listen:
[recording]
“If you want more death, if you want more injury, if you want more disease, if you want more sexually transmitted diseases, unintended pregnancies, more crime, and more addiction-related problems in our communities go ahead, lower it to 18, because that’s what we are going to get.”
[end of recording]
He says that changing the drinking age to 18 will cause more death, “injury,” or people getting hurt, and “disease,” or sickness or illness. He says that there will be more “sexually transmitted diseases,” or diseases that are passed from one person to another person when they are having sex. He also talks about “unintended,” or unwanted, pregnancies. If something is unintended, it is unplanned. It’s something that happened even though you weren’t trying to make it happen. Getting pregnant, for some people, is one of those things. He also says that there will be more “crime,” or people breaking the law, and more addiction-related problems. An “addiction” is the physical need to do or to have something, even if it is bad for you. Some people are addicted to cigarettes; they have an addiction to cigarettes, they can’t stop smoking them.
The legislator says that if we want to have all these problems, then we should go ahead and “lower,” or reduce, the drinking age to 18. The phrase “go ahead” is used to invite someone to do something. For example, if you ask me how to improve your listening comprehension in English, I might say, “Go ahead and listen to all of the ESL Podcast episodes.” Go ahead and do it. I invite you to do it.
Let’s listen to the legislator one more time:
[recording]
“If you want more death, if you want more injury, if you want more disease, if you want more sexually transmitted diseases, unintended pregnancies, more crime, and more addiction-related problems in our communities go ahead, lower it to 18, because that’s what we are going to get.”
[end of recording]
As you can hear, people have very strong opinions – very different opinions on this topic in the United States.
Now let’s answer a few of your questions.
Our first question comes from Antje (Antje), originally from Germany, now in California. The question has to do with the meaning of the word “fluke” (fluke).
A “fluke” is something that happens, usually something good, that happens by chance. It’s almost like a mistake; you didn’t mean it to happen, but it happens because you have very good luck. For example: “My friend doesn’t know how to play poker, but he went to Las Vegas and won $10,000 playing one game of poker.” It was a fluke – it was very good luck. He wasn’t a good poker player, he didn’t have knowledge or experience; it was just a lucky event.
Fernando (Fernando) in Mexico wants to know the meaning of an expression he heard: “ain’t quite right.”
“Quite” (quite) means exactly, or perhaps completely. It can also mean to a certain extent or to a certain degree. For example: “He was quite interested in the job.” That means he was very interested in the job. If someone says something is “quite right,” they mean it is completely correct, it is absolutely right.
“Ain’t” (spelled ain’t) is an informal contraction – an informal form of saying “am not,” “are not,” “is not,” and in some dialects of English (some varieties of English) “do not,” “does not,” and “did not.” So, “ain’t” is one of these words that is very informal; it’s not considered good English; it’s not considered educated English, but you will sometimes hear people say it. For example: “We ain’t letting that team win” – we are not letting them win, we will not allow them to win. Or someone may say “Your car ain’t no Mercedes Benz.” They mean your car is not a Mercedes Benz. The car, in other words, is not very nice.
So, “ain’t quite right” could also be expressed as isn’t completely right, or is not completely the way that it should be.
Well, we ain’t finished yet. Our last question is from Ariel (Ariel) in Taiwan. Ariel wants to know the meaning of the expressions “domino effect” and “chain reaction.” These two terms really mean the same thing; it describes how one thing causes another thing to happen, which automatically causes a third thing to happen, and then a fourth thing to happen.
The expression “domino effect” refers to the game of dominoes, which is a popular game in some countries. They’re small, rectangular pieces that are used for playing a game called dominoes. You line the dominoes up in row, one next to the other. When you knock one down, that knocks the one next to it down, which knocks the one next to it down, and so forth. So, a “domino effect” is you do one thing, and then all these other things will automatically happen.
The term “domino effect” became popular in the 1960s and 70s in American politics when the United States was fighting in Vietnam. The theory was that if one country was allowed to become communist, all of the other countries would become communist in that area. There would be a domino effect – one country would cause another country, would cause another country to become communist, and so forth.
A “chain reaction” is the similar idea. Technically, a chain reaction is a chemical reaction, but a chain reaction can also refer to something the same as the domino effect. For example, if there are 100 cars on the freeway (on the highway) and one car gets into an accident, then the car after that hits the car in front of it, and that causes the car behind him to hit his car, and so forth. You have a chain reaction; one thing causes all of these other problems.
If you have a question or comment for us, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m ain’t Lucy Tse, I’m Jeff McQuillan. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational Development.
Glossary
access – the ability to get or have something; being able to enter a place
* Does that coffee shop have Internet access for customers who bring their computers?
consistency – the practice of doing things the same way each time, without changing anything
* Teachers in our school show consistency in how they grade their students’ essays.
rebellious – not doing the things that one is told to do; not doing the things that one is supposed to do
* Maggie is very rebellious and always does the opposite of whatever her father tells her to do.
binge drinking – drinking dangerous amounts of alcohol very quickly; drinking a lot of alcohol in a short amount of time
* Some university students go binge drinking almost every weekend.
DUI / DWI – driving under the influence / driving while intoxicated; a ticket for driving while one has had so much alcohol to drink that one’s body does not function normally, so that one is driving dangerously
* I’ve had too much to drink. Can you give me a ride home so that I don’t get a DUI?
assault – a physical attack to hurt another person
* We never walk on that street at night because we often read about assaults that happen there.
date rape – when a woman is forced to have sex with a man whom she knows, often a friend or someone she is dating
* Some women don’t want to report date rape to the police, because they think that nobody will believe that they didn’t want to have sex with the man.
to model (something) – to set an example; to show someone how to do something
* Samantha is going to model the correct way to help a person who is choking.
sexually transmitted disease – a sickness or illness that is passed from one person to another when they have sex
* AIDS is a very dangerous sexually transmitted disease.
unintended – not planned; something that happened even though nobody was trying to make it happen
* The higher cost of food was an unintended consequence of using corn to create ethanol for cars.
addiction – a physical need to do or have something, even if it hurts a person
* Do you think it’s possible to have an addiction to chocolate?
go ahead – a phrase used to invite someone to do something
* If you don’t believe me, go ahead and call the project leader to find out for yourself.
to lower (something) – to reduce something; to decrease the amount of something
* The doctor wants him to take some medicine that will lower his blood pressure.
to chalk (something) up to – to give credit to; to explain
* Craig’s business is failing, but he chalks it up to the bad economy, not his management skills.
fluke – a mistake; an unexpected and unusual thing to happen
* The first time Jenna went bowling, she scored a perfect game, but she said it was a fluke.
quite – exactly, completely; to a degree, to some extent; extremely so
* You don’t quite have the experience we’re looking for, but thank you for applying for the job anyway.
ain’t – an informal contraction of am not, are not, is not and, in some dialects, do not, does not, did not
* I ain’t someone who’s happy working in front of a computer all day. I need to be outside!
domino effect – the phenomenon where one thing happens and causes another thing to happen, which causes another things to happen, which causes another thing to happen, etc.
* When one store closes, it has a domino effect, because the people who used to work there no longer have enough money to buy things in other stores, so those stores have to close, too, and then those employees don’t have enough money to buy things.
chain reaction – the phenomenon where something happens or changes and causes many other things to happen or change, since they are all connected in some way
* Mariah was always very unhealthy, but when she started to walk for an hour each day, it started a chain reaction. She had more energy to exercise more, and doing that made her want to eat better, which gave her even more energy and made her want to exercise even more.
What Insiders Know
The “Just Say ‘No’“ Campaign
In the 1980s, “recreational drug use” (the use of illegal drugs for fun and entertainment) became increasingly popular. Americans and the U.S. government were worried about drug addiction, and wanted to find ways to “encourage” (get someone to do something) young people to not start taking drugs. “First lady” (the wife of the U.S. president) Nancy Reagan thought that this was an important “cause” (something that people need to work together to change), and she became a leader for it.
Nancy Reagan “spearheaded” (led) a popular television advertising “campaign” (a series of advertisements that have a similar style and send a single message) called “Just Say ‘No’.” The campaign messages mostly “aired” (were shown on TV or heard on the radio) in the 1980s and early 1990s. People, and especially children, were encouraged to say ‘no’ to alcohol and other drugs, or to not use illegal drugs. The “slogan” (a phrase repeated many times to share and spread a message) of “Just Say ‘No’” was part of the United States’ “War on Drugs,” (a long effort to decrease drug use and not let illegal drugs be sold in the United States).
Over time, the “Just Say ‘No’” slogan began to be used for other things, like encouraging children to say ‘no’ to violence and “premarital sex” (having sex before one is married). Some people think that the slogan began to lose its “effectiveness” (ability to do something well) as the message was “diluted” (became less precise and specific). Other “critics” (people who say negative things about something) thought that the “Just Say ‘No’” campaign “reduced” (made something less important) the problem of drug addiction to a “cliché” (a phrase that is repeated by many people but doesn’t have very much meaning or importance).