= 1459
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 154.
This is English as a Second Language Podcast’s English Café episode 154. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8 to 10 page guide we provide for all of our current episodes that gives you some additional help in improving your English. While you’re there take a look at our ESL Podcast Store, which has some additional courses in English, as well as our ESL Podcast Blog.
On this Café, we’re going to continue our series on famous Americans, focusing on a writer named Amy Tan. We’re also going to talk about a U.S. law called the Americans with Disabilities Act and how it affects buildings and life in the United States. A very important law that most people are aware of here in the U.S. And as always, we’ll answer a few of your questions. Let’s get started.
In this Café we begin with a continuation of our series on famous Americans. Today we are going to talk about a famous writer named Amy Tan. Tan is an American of Chinese “descent,” meaning her relatives – parents, grandparents, or great-grandparents – are from a Chinese-speaking country. We use this word, “descent” (descent), to refer to where we came from. The United States is mostly a country of immigrants, and so everyone has a different place where they came from. I am of Irish descent, because my great-great-great-grandparents were from Ireland. Tan is of Chinese descent because both of her parents were from China. Tan is an American, however, because she was born in the United States. She was born in Oakland, California, which would make her a Chinese American. She was born in 1952.
Amy’s father – Amy Tan’s father and one of her brothers died when she was very young. She lived with her mother and her other brother, but they moved around a lot and she lived in many different places, including the Netherlands and Switzerland in Europe. Amy and her mother fought a lot. “Fought” is the simple past tense for the verb “to fight.” Normally “to fight” means to be angry with another person, even hitting the other person. But when I say that Amy and her mother fought a lot, I don’t mean they physically hit each other. I mean they disagreed with each other and had a lot of arguments. You could say, “My wife and I had a fight last night; we fought over what we were going to watch on television.” I wanted to watch the baseball game; she wanted to watch the hockey game. She likes hockey! Many teenagers fight with their parents – if you have teenagers, you know this – but I think Tan and her mother fought more than most people do.
When Amy got a little older, her mother wanted her to become a doctor, but Amy decided to study English literature instead. This made her mother so angry that the two gave each other the silent treatment for more than six months! This expression “to give someone the silent treatment” means that you don’t talk to someone. You don’t talk to them as a way of punishing them, usually because you are angry at them: “I came home late last night, and my wife gave me the silent treatment.”
When Amy finished college at San José State University, which is located in Northern California very close to Oakland where Amy was born, she started a business in writing, but then her mother got very sick. Amy made her mother a “promise,” something that we say we will do. She made a promise that if her mother got better, she and her mother would travel to China together so that Amy could learn about her mother’s life.
Well, Amy’s mother did get better and the two women did go to China in 1987. This trip was a life-changing event for Amy. When we say something is a “life-changing event,” we mean it changes your life in a very big or important way. Marriage is a life-changing event. Death is also very life-changing! For some people, a life-changing event may be if they get the cancer, or they decide to move to a different city. So for Amy, this trip back with her mother to China was a life-changing event because she learned a lot about her mother’s life and she used that information in her writing. The trip helped her understand different “aspects,” or parts of her relationship with her mother. Of course, the relationship between a woman and her mother – the daughter and mother – is always very important and can be very difficult.
Amy has written several books, which have made her famous in the United States. Most of them are about the relationships between mothers and their daughters, and about the expectations that Chinese women, or Chinese American women put on their daughters. An “expectation” is something that you think and want to happen. My expectation is that you will enjoy this podcast and learn some new vocabulary. In Amy Tan’s books, many of the Chinese and Chinese American women put expectations on their daughters. These expectations might be to become a doctor or a lawyer, to get married, or perhaps to make a lot of money. Of course, there are many different kinds of expectations that all mothers put on their sons and daughters.
Amy is best known for her book, The Joy Luck Club, which was published in 1989, two years after she went to China. The book is about four women who come to America – to San Francisco – again, San Francisco is near where Amy grew up in Oakland. They come to San Francisco from China, and they play a very popular Chinese game called Mahjong and talk about their lives, mostly about their daughters. The book contains stories of these women’s lives and their relationships with their daughters. It was a very popular book when it was published, especially with female readers, and it was made into a movie in 1993. If you’re interested in knowing more about Amy Tan and her work, you might start by watching that movie, The Joy Luck Club.
Amy Tan has won a lot of awards for her books, including The Joy Luck Club. She’s written other books such as The Kitchen God’s Wife and The Bonesetter’s Daughter. She is, perhaps, the best known Chinese American author in the U.S., and certainly one that many schools have their students read now, because it is such a good portrait – that is, a good picture, a good description of Chinese American families, at least Amy Tan’s view of Chinese American families.
And now for something completely different, we’re going to talk about a very important law that has affected life in the United States in many ways, it’s called the Americans with Disabilities Act. An “act” (act) is just another word for a law. “Americans with Disabilities” is the name of this law – the name of this act. A “disability” is something that makes it difficult or perhaps impossible for a person to use part of his or her body or mind. Someone who cannot move his legs, for example, has a disability, or someone who cannot see or hear. Many people have disabilities, and the Americans with Disabilities Act was created to help them.
The law was enacted in 1990. To “enact” something means to make something into a law. So the Americans with Disabilities Act, which many people just call the ADA, became a law in 1990. What does this law do and why is it important? Well first, it “prohibits,” or doesn’t allow discrimination against people with disabilities. “Discrimination” happens when someone treats a group of people in a certain way that is considered unfair. So for example, if companies won’t give jobs to people over 45 years old or 50 years old, then that is considered age discrimination. There’s also race discrimination, sex discrimination, religious discrimination, and others. The ADA was enacted to help stop discrimination against people with disabilities.
Specifically, the ADA doesn’t allow, or let companies discriminate against people with disabilities when they are hiring new employees. Obviously the person has to be able to do the job. In other words, if you are looking for a bus driver and the person is blind, well of course, that would not be discrimination because you need someone who can see. But, if you are hiring someone to work as a typist or someone to work in another job that doesn’t require sight, then you would have to look at and not discriminate against someone who could not see – someone who is blind (blind). If a blind person can do something, or a deaf (deaf) person can do something, then you must not discriminate against that person when you are hiring. Someone who is “deaf” is someone who cannot hear. This is, then, one of the most important parts of the ADA, it said companies could no longer discriminate, legally, in their businesses against those with disabilities.
But the act goes beyond that, meaning it does even more than that – it goes beyond it. It also requires businesses to provide accessibility. “Accessibility” comes from the word “access” (access), which means to be able to go in somewhere or to be able to enter somewhere. “Accessibility” means giving people with disabilities a way to use your business – to use the building where you have your business without too much difficulty. For example, a person in a wheelchair can’t use the stairs, so the ADA requires businesses, when possible, to provide a way for that person to get from one floor of a building to another. A “wheelchair” is a chair with wheels that is used by people who cannot walk. The building might have to have, for example, an “elevator,” which is a large box with doors that you walk into, push a button, and it brings you up to the different floors – the different levels of a building. If there are stairs that you must go up to get into a building, the building may have to provide a “ramp” (ramp), which is a large flat area that goes up at an angle. So someone in a wheelchair could go up and down the ramp to get into the building.
Now, there are some exceptions to these rules. An “exception” is something that you do not have to do; it’s when someone doesn’t have to follow a certain rule. If the building is very old and it’s considered historically important and providing accessibility, such as an elevator or ramps, would change the building too much, then that building is not required to have changes made to it. Also, if the business is very small and doesn’t have a lot of money, and providing accessibility would be considered very expensive, then it is given an exception to the rule and doesn’t have to necessarily provide accessibility. So, there are reasonable compromises that are made, with the understanding that not every building in America could change in order to provide accessibility. But certainly, all buildings with large companies, government buildings, and any new buildings that are built have to meet these accessibility requirements.
Many hotels and even apartments have to provide accessibility. This includes putting bars, or long pieces of metal for people to hold onto in the bathrooms. It also means having wider doors, so that a wheelchair could get in and out of a bathroom. If you go to almost any public bathroom in the United States – a hotel, a public building – you will see that one of the toilets has, usually, a lot more space and a much bigger door to allow us someone with a wheelchair to get in and out of there.
Finally, the ADA makes “telecommunications” companies, or companies that work with telephones and other types of communication, provide services for “deaf” people, people who cannot hear. Telecommunication companies have to provide something called “TDD services.” TDD stands for Telecommunications Device for the Deaf. This is how it works: a deaf person wants to make a phone call, so that person has a small keyboard, just like the keyboard on your computer that you type on. They have a small keyboard and they call a special number to speak with an operator, or an employee of the telecommunications company – the phone company. The deaf person can type a message and the operator on the other end can read the message. The deaf person types a message to the operator, and then gives your phone number to the operator. The operator calls your number, and then the operator reads what your friend is typing, and types back what you say to him or her.
Without the ADA, many people with disabilities would have to stay at home, because they couldn’t go to stores, or banks, restaurants, or hotels. So the act has definitely made a difference in American life in the last 18 years, and is considered a positive step in ending discrimination against people with disabilities.
Now let’s answer few your questions.
Our first question comes from Ivo (Ivo); I’m not sure where he is or she is from. The question has to do with something that they saw in a movie, a very popular movie called The Usual Suspects. The person says in the movie, “He takes convincing.” What does this mean, to take convincing?
To say a person “takes convincing,” or, “took (past tense) convincing,” means that the person did not immediately believe or accept what he or she was being told. In other words, the person needed to have some evidence to be persuaded or convinced. You can also say, “to take persuading,” or, “to take getting used to,” or, “to require getting used to” – to require thinking. All of these are the same kind of construction, where the second verb is in the “ing” form. So, to take or require convincing means that the person needs more evidence – needs more to believe what you are saying to them.
Julio (Julio) in Mexico wants to know the meaning of the word, or expression, “full-fledged” (fledged).
When we say something or someone is “full-fledged,” we mean they are complete – they are completely developed or they are fully trained. Originally, this expression was used to talk about birds. They would call a young bird – a small bird that was still learning to fly – a “fledgling,” and “fledge” described a bird that was now able to fly – a bird that has developed, or “matured,” we might say, whose wings have grown. Now it means more generally to be complete, to be completely developed. For example, you could say, “I don’t want a small party for my graduation from high school. I want a full-fledged celebration,” meaning a large, complete celebration. Or, someone may say at work, “I need more than just a few ideas from you. I need a full-fledged plan” – a complete, developed plan.
Finally, Wislei (Wislei) in Brazil wants know the meaning of a couple of slang expressions. The expression is “I’m there, dude.”
Well, there are actually two expressions here. The first is “I’m there.” “I’m there” is an informal way of saying that you plan to go to a certain place or go to a certain event. It’s a short way of saying “I am going to be there.” For example, your friend asks you, “Are you going to the rock concert next week?” and you say, “Oh, yeah, I’m there. I definitely want to go.” Or they might say, “I’m totally there.” “Totally” is a word – a slang expression used by many young people to mean absolutely: “I am absolutely going to go. No doubt. I’m totally there.”
“Dude” (dude) is a slang term usually for a man, a boy, a guy. For example: “Dude, let’s go to the beach,” meaning “hey man” – “hey friend,” in this case, “let’s go to the beach.” Or you could say, “That dude was six feet, five inches.” That man – that person was six feet, five inches.
“Dude” is often used with other descriptive words. For example: “He was a cool dude,” meaning he was someone who was popular, well liked. He was a cool guy – a cool dude. You will also hear the expression, especially here in California, a “surfer dude.” A “surfer” (surfer) is someone who surfs, someone who goes on the ocean with a small board and tries to ride the waves of the ocean – a surfer dude. My neighbor who just moved out in the house next door is a surfer dude; he goes surfing almost every day.
I’m a podcast dude, and if you have any podcast questions you can email us. Our email address is eslpod@eslpod.com. We don’t have time for all your questions, but we’ll try to answer as many as we can.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and
Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational
Development.
Glossary
descent – background of a person in terms of family and cultural or ethnic background
* It’s not uncommon to find Americans with mixed descent from many different cultural and ethnic backgrounds.
to fight – to have disagreements; to argue; to use words or physical actions to hurt the other person and/or to win an argument or contest
* The two men had a fight over who would ask Sherri out on a date first.
to give (someone) the silent treatment – to not talk to someone else as a way to punish them and show that one is very angry
* We always know when Mom is angry. She gives us the silent treatment.
promise – something that we say we will do; a commitment to do something
* Gianetta’s boss made her a promise that if she worked late this week, she could leave work early next week.
life-changing event – something that changes someone’s life in a very big or important way
* For many people, having a baby is a life-changing event.
expectation – something that one thinks will happen and wants to happen
* All of the guests arrived with the expectation that the host would make an important announcement that evening.
act – a law; a law made by the government
* The people in the city were happy about the government’s new act, which would help homeless people find places to live.
disability – a physical or mental condition that makes it difficult or impossible for a person to use a part of his or her body or mind
* Do you consider your poor eyesight a disability?
to enact – to make something a law; to pass a law or regulation
* The lawmakers enacted a new law that required everyone to listen to ESL Podcast every day.
discrimination – treating a group of people a certain way that is unfair; behaving to people in a group negatively because they belong to that group
* Even though some people believe the United States is a fair country, discrimination still exists and causes difficulties for many Americans.
accessibility – giving people with disabilities a way to use buildings and services
* Before we decide on where to hold our yearly meeting, let’s make sure that the building has accessibility for everyone.
wheelchair – a chair on wheels that is used by people who cannot walk
* This parking space is reserved for people with wheelchairs.
elevator – a large box with doors that one walks into and pushes a button to go to another floor in a building
* Don’t you hate it when you get into an elevator and someone pushes all of the buttons so you have to stop on every floor?
ramp – a large flat surface placed at an angle, probably over the steps, so that wheelchairs can roll up it
* I can’t carry this large suitcase up the stairs. Is there a ramp?
exception to the rule – something that allows people not to have to follow a rule; something that does not follow the normal or standard pattern
* All the children eat lunch at school. Linda is the exception. She lives next to the school and walks home ever day for lunch.
bars – long pieces of metal attached to the ground or to a wall, often for people to hold so that they walk, sit, or stand better
* My grandmother has a bar on the wall of her bathroom that she holds onto so that she doesn’t fall when getting in or out of the bathtub.
to take convincing – a phrase used to mean that the person did not immediately believe or accept what he or she was told and he or she needed to have some evidence or more information to be persuaded or convinced
* It took convincing to get Jeremiah to agree to drive us to San Diego this weekend, especially since he doesn’t like to drive long distances.
full-fledged – totally developed; complete; fully trained
* Daniella worked as an assistant in a hair salon for a year before she became a full-fledged hair stylist.
dude – informal term for a man; a guy
* Hey, dude. Why don’t we get some beer and watch the game at your house?
What Insiders Know
Disabled Facilities and Parking
In the U.S., businesses are required to make sure that their “premises” (building; location) are accessible for people with disabilities. This usually means that a separate area is “set aside” (only allowing certain people to use) in part of the building. For example, “changing rooms” or “fitting rooms” where customers in stores put on the store’s clothes to see if they are the right size must have a place that is accessible for people in wheelchairs or other disabilities. This is also true for bathrooms, or “restrooms.” You will either see a special separate bathroom set aside that is wheelchair accessible, or a “stall” (individual small room with a toilet) that is “designated” (marked) for wheelchair users.
To make sure that everyone knows that there is a “facility” or place for the use of people with disabilities, business owners put up a sign that looks like sign number 1:
2.
Businesses are also required by law to set aside parking spaces near the “entrance” (place where people enter a building) for use by people with disabilities. You will see signs like sign number 2 at many business and public places. Only people who apply to the government and receive a special “license plate” (metal plate with numbers and letters that identify your car) or a “permit” (sticker or sign that people place in their car window to show that they have special permission to do something) can park there. Anyone else who parks there will get a ticket and will have to pay a “fine” (money paid as punishment for doing something against the law).