= 1456
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 151.
This is English as a Second Language Podcast’s English Café episode 151. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8 to 10 page guide we provide for all of our current episodes that gives you some additional help in improving your English. You can also take a look at our ESL Podcast Store, with additional courses in English, as well as our ESL Podcast Blog, where several times a week we comment on interesting things in the news and other topics related to improving your English.
On this Café, we’re going to talk about a famous mystery in the United States. The man that we are going to be talking about is D.B. Cooper. We’ll talk about why there is a mystery about this man. We’ll also discuss something from American history, the Underground Railroad, which was a system that helped slaves escape their owners in the 19th century. As always, we’ll also answer a few of your questions. Let’s get started.
On November 24, 1971, there was an airplane hijacking. To “hijack” (hijack) means to take control of something, usually an airplane, through violence or through threats – telling someone you will hurt them if they don’t do what they are told. Airplanes are often hijacked by people who want money; sometimes they are hijacked for political reasons. In 1971, the airplane hijacking that took place on November 24th was for money, not for politics, but it was very unusual. The hijacking is what we would call an “unsolved mystery,” something that happened but no one can explain how or why. Let me explain the story to you, and I remember this story from the 1970s. I was a young child, 9 or 10 years old, but I liked to read the newspapers and I remember reading a story about this.
The hijacking happened on an airplane flight from Portland, Oregon to Seattle, Washington. Portland and Seattle are cities in the northwest part of the U.S. Oregon is the state above California – north of California; Washington is a state north of Oregon. The distance is not very much between the two cities, however; probably in an airplane, no more than a half hour or 45 minutes.
There was a man on this airplane who called himself D.B. Cooper; D.B. were his initials. He also called himself Dan Cooper. He gave a note, when he got on the plane, to one of the flight attendants. The “flight attendants” are the employee who ride on the airplane, helping you find your seat, bringing you food and drink. The note that D.B. Cooper gave to this flight attendant said that he had a “bomb,” something that could explode and kill everyone. Usually bombs are dropped out of airplanes onto cities during a war. In this case, though, the man said he had a bomb that he would use to make the airplane explode, and of course, kill everyone on it. When the flight attendant heard that he had a bomb, she took his threat seriously. To “take someone’s threat seriously” means she believed him, she paid attention to what he was saying.
D.B. Cooper then asked for 200,000 dollars and four parachutes. A “parachute” is a very large piece of fabric – of a material – that is attached to your body with ropes. A person puts on a parachute and then jumps out of an airplane. When this person is falling – not me – the parachute fills with air and slows down the fall so you can land on the ground. That’s called a “parachute.” Jumping out of a plane doesn’t sound like very much fun to me, but everybody has a different idea of fun!
Well, the airplane pilots on this hijacked flight used their radios to get the money and parachutes ready for D.B. Cooper. When the plane landed in Seattle, those things were waiting for him. D.B. Cooper released, or let go, 36 passengers. The people who are on the plane are called “passengers.” He let them go in exchange for the money and the parachutes, so he got something for giving up what we would call the “hostages,” someone who is taken against their will is called a “hostage.” “In exchange for,” then, means that we use one thing to get something else, in this case the money and the parachutes were used in exchange for the passengers. D.B. Cooper, however, said that the pilot, the person who flies the plane, and two other people had to stay on the airplane.
Well, once D.B. Cooper got the money and parachutes, he told the pilot to fly the plane towards the State of Nevada. Nevada is just east of California, south of Oregon and of Washington. Nevada is where Las Vegas is; Nevada is famous mostly because it allows gambling.
The plane, then, left Seattle and started to fly toward Nevada, but long before it got there, D.B. Cooper jumped out of the plane. He used one of the parachutes for himself. You may wonder why he wanted four parachutes? Well, he was thinking! He used the other three parachutes for the money.
The plane was flying through a “storm,” through very bad weather with very strong winds. After D.B. Cooper jumped from the plane, the police started to search for him on the ground, in particular, the FBI – the Federal Bureau of Investigation, which is the part of the U.S. national government that helps solve crimes. They search for him for 18 days in the area, and couldn’t find him. Many people believe that D.B. Cooper died when he jumped out of the plane, but it’s a mystery because the body and the money are still missing. They were never found in the places where we believe he would have landed – where the parachute would have come down to the ground.
Now, many years later in 1980, a little boy found 5,800 dollars in frayed bills in the State of Washington. The word “frayed” (frayed) means that the ends are falling apart, so it was old money. Well, the 5,800 dollars in frayed bills was part of the money that was given to D.B. Cooper, part of the 200,000 dollars. However, the rest of the money has never been found, or at least it has never been found by the police. It’s possible someone else found it and decided to keep it. If you are walking through the forest, in the trees, and you see 200,000 dollars there, you might decide to keep it! The money that they gave D.B. Cooper was all “marked,” meaning they put a special mark on the money so that if he spent it the police could find out where he was spending it. But, the money was never spent, so the FBI thought he must have died.
Well, in March of 2008, just a few months before we are publishing this podcast, a man in Washington State found an old parachute in his “field,” the place where he has plants that he grows for food. Many people believe that the parachute might have been D.B. Cooper’s, so the FBI investigated. On April 1, just a few weeks later, the FBI said no, it was not D.B. Cooper’s parachute, but many people remain “unconvinced,” they’re not sure if that was true or not.
So, this is one of the great mysteries in crime in the U.S. in the last 30-40 years, the disappearance of D.B. Cooper. So, if you ever find a man teaching English who calls himself D.B. Cooper, be sure to email us!
Now let’s turn from this unsolved mystery to the Underground Railroad, which in some ways was also a mystery when it was going on. The Underground Railroad was an escape route for slaves. A “slave” is a person who is forced to work without being paid, usually living in very poor conditions. In the U.S., back in the 1800s, there were many black slaves that were brought from Africa to the United States to work in the fields. In the first half of the 1800s, most of these slaves were in the southern part of the U.S., but many of the blacks who had originally been slaves were free, living in the northern U.S. states. Of course, this difference between the northern and southern states was one of the reasons that the U.S. had a civil war, back in the middle of the 19th century.
Of course, many of the slaves of the South wanted to escape, or get away from their owners – their masters – by going north, even going as far as Canada. The people who owned the slaves didn’t want them to escape, of course, so they tried to escape secretly. The slaves needed to escape secretly, and the route – the path – that they took was called the Underground Railroad. Of course, it wasn’t actually a railroad under the ground. “Underground,” here, is a term meaning not official, something that isn’t public. It was called a railroad because it was, like a railroad, of leading them from the South to the North.
The Underground Railroad was a group of people who were sympathetic toward the slaves. To be “sympathetic” means that you feel something – you feel for someone even if they are in a different situation; usually, you feel badly for them. You feel sympathy toward them. The people who were sympathetic toward the slaves and participated in the Underground Railroad would hide the slaves in their homes and help them get to another house on the path – on the Underground Railroad as they moved northward. This was similar to some people who helped, for example, save Jews during World War II in Germany, France, and other countries by hiding them in their houses.
Of course, in the southern states, these slaves were considered property and so you would in effect be stealing someone’s property if you had these slaves in your home. But these men and women – these families – believed that slavery was wrong and that this was the right thing to do, to help them escape to the North where they could be free. Slavery was not permitted, at least by the 1860s in the northern states, so this is why they went north.
The Underground Railroad was most active between 1810 and 1850. Nobody knows exactly how many slaves actually escaped through this system. It could be 6,000, it could be 100,000; we don’t really know, it depending on which documents you read – which historians have looked at it. But no matter how many slaves actually escaped, the Underground Railroad was important historically because it was a threat to the southern slave owners; it made the slaves feel as though they had a chance. These changes were important in changing the United States so that slavery would later become illegal in the U.S., after the Civil War.
The most famous leader and organizer of the Underground Railroad was a woman that many Americans know the name of, Harriet Tubman. Tubman was a black woman herself; she had been a slave, but then she escaped. Once she was free, she helped her family escape and then many other slaves, too. Some people think she may have rescued 300 slaves during her lifetime! While doing this, she returned to the southern states 19 times, something that was very dangerous for her because she could have been caught and made a slave again. Harriet Tubman was a very “brave” woman, meaning she was courageous – she wasn’t afraid of things. The Underground Railroad might not have been successful without Harriet Tubman’s bravery and leadership.
So that’s the Underground Railroad, an important part of American history.
And now, let’s answer a few of your questions.
Our first question is from Natsuki (Natsuki) in Japan. Natsuki wants to know the difference between the words “extend” (extend) and “expand” (expand).
To “extend” means to stretch out to a full length, to lengthen something or to make something longer. The word “extend” can be used to describe time. “Extend” can also be used when we are talking about taking your arm or your leg and making it straight – you’re making it longer, in a way. “Extend” can also be used as a way of talking about giving appreciation, welcome, or thanks to someone. Someone may “extend his congratulations,” meaning he’s giving you his congratulations. When it means to make longer, “extend” can be used in situations such as you are on a date with a beautiful woman and you want to extend the amount of time you are spending with her, so you start telling stories, for example. “Extend” can also be used, for example, if you are in a meeting, and someone says, “Can we extend the meeting by 30 minutes? I want to listen to my boring co-workers even longer!” That would be a use of “extend.”
To “expand” means that something grows in size. It’s used to describe things that are stretched out, are extended but in more than one direction, if it’s something physical. For example, it can mean to grow bigger when we are talking about a group of people: “The number of people in the organization expanded by 1,000” – there are a thousand new people in the organization; it got bigger. If you are woman, and you get pregnant with a child, your belly – your middle part of your body – will expand so the baby has room to grow. If you blow air into a balloon, a thin piece of plastic, the balloon expands – it gets bigger and bigger, just like a woman’s belly when she’s pregnant!
So, “extend” is used with time expressions or with something that gets longer. “Expand” is used to mean either to grow or to get larger; the size increases, not just gets long, but gets bigger in other ways as well.
Bill (Bill) from China wants to know the meaning of the expression “God forbid,” such as “God forbid you should do your homework tonight.”
“God forbid” was once said as a sort of prayer or wish that something bad that you are describing would not happen – may God forbid that something bad would happen to you. So you’re praying, you’re asking God, who, of course, in many religious traditions is this all-powerful being, this person or this force that controls the world.
We use this expression to say that we hope something doesn’t happen or something is not true. It’s similar to “I certainly hope not.” You could say, “God forbid that I fail my test,” meaning “I hope I do not fail my test.” Sometimes “God forbid” is used sarcastically, as a joke; in fact, it is often used this way. So for example, your son or daughter complains that they have too much homework and that they don’t have time to watch their television programs, and you say, “Well, God forbid that you should miss any of your television programs!” You’re being sarcastic. You’re not actually saying that you hope they don’t miss their programs; you’re saying that that’s not important. It’s sarcasm; it’s making a joke of something with the opposite meaning.
Ricardo (Ricardo) in Brazil wants to know the meaning of the expression a “brown-bag lunch.” This is a good question because you’ll hear this expression especially in many workplaces – in many companies.
A “brown-bag” is usually what we use when we are taking food from home that we want to eat at work, or we are taking food from home that a student would eat at school. When I was going to school, the schools I went to, anyway, didn’t have food. They didn’t serve food, so all of the students had to bring a brown bag – why it’s brown I don’t know – and that was used to carry their food.
A “brown-bag lunch” is usually a meeting – an informal meeting to discuss something over lunch. So for example, when I was a student at the university sometimes there would be professors from other universities that would be visiting that day, and so we would have a brown-bag lunch discussion. Everyone would bring own food; it would be between noon and one o’clock, when Americans eat lunch, and we would sit around and talk. It could also be something that happened at a workplace. Of course, being students, we didn’t work!
“Brown-bag it” also means to save money. Sometimes people will say, “Well, I’m going to brown-bag it,” using it as a verb. There, it would mean to save money. But the most common use is a “brown-bag lunch.” Someone may ask you, for example, “Do you want to go to a restaurant for lunch with me?” at work, and you say, “No, I’m going to brown-bag it today,” meaning I’m going to eat my lunch, because I brought it from home, I’m going to eat it here at work.
If you have a question, comment or suggestion, you can email us. Our email address is eslpod@eslpod.com. We can’t answer all of your questions, but we’ll do our best.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2008, by the Center for Educational Development.
Glossary
to hijack – to take control of something, usually an airplane, using violence or strong, threatening language
* The airplane was hijacked by a bank robber who was trying to run from the police.
threat – telling people that one will hurt them or do something else bad to them if they do not do what one tells them to do
* Carl threatened that he would take away his children’s toys if they didn’t clean up the mess they made.
unsolved mystery – something that happened but no one can explain how or why
* There is a popular TV show that features unsolved mysteries, in hopes of getting new information from someone watching the show.
flight attendant – an airline employee who rides on the airplane, helping people find their seats and bringing them food and drinks
* Is there a flight attendant here who can help me fit my suitcase in the overhead compartment?
bomb – a weapon that explodes and damages buildings and hurts people
* Three booms exploded in the streets and injured more than 50 people.
parachute – a very large piece of fabric that is attached to one's body with ropes so that one can jump from a high place or an airplane and stay alive
* Do airplanes still carry parachutes in case there is an emergency?
in exchange for – to give up something to get something else; to give something to someone else to get something in return
* I like ice cream and you like cake. I’ll give you my cake in exchange for your cake.
frayed – with worn ends; with ends that are falling apart
* I wanted to wear these pants to my interview until I saw they were frayed on the bottom.
unconvinced – not sure that something is true; not decided yet whether something is real
* Paula told her boyfriend Dave that she was out with her girlfriends last night, but he was unconvinced.
slave – a person who is forced to work for another person without being paid for that work and often living in poor conditions
* The politician said that there were people working as slaves in his country and it was his aim to put an end to it.
to escape – to get away from; to leave a place that one is put into that did not allow one to come and go as one wants
* The pigs on this farm are kept in this locked area, but the pigs escaped last night and now we can’t find them.
to be sympathetic toward – to feel what someone else feels even though one is in a different situation; to understand someone else’s situation or feelings even though one is not in that situation
* The teacher was sympathetic toward his students who were taking four exams in two days, and canceled the test in his own class.
to extend – to stretch out something to its full length; to make something last a longer period of time
* Let’s extend our one-day meeting to two days so we’ll have enough time to talk about all of these important issues.
to expand – to spread out; to unfold; to grow in size, usually in many directions
* For our business to expand, we need to hire more people.
God forbid – a phrase that means that one hopes something will not happen or that something is not the case
* Gerald lost a lot of money gambling. God forbid he keeps gambling and loses everything he has!
brown-bag lunch – to gather to eat together, usually for a meeting or to discuss a topic, where each person brings his or her own lunch to eat while they talk
* The manager is having a brown-bag lunch for anyone who wants advice on how to advance in the company.
What Insiders Know
Terminology Used on the Underground Railroad
The Underground Railroad was an important part of American history and one of the factors in helping to end slavery in the United States. As we mentioned in the podcast, the Underground Railroad was not really under the earth or ground and it was not a real railroad. However, to help keep this system of freeing slaves a secret, the people who were part of it used special terms or words so that others would not know what they were talking about. Many of these terms related to the railroad.
For example, the people who guided the slaves from one place to another, and from one house to another, were called “conductors.” A conductor on a railroad is the person who is “in charge of” (have responsibility and power over) the train. The people whose houses the slaves stayed and hid in were called “stationmasters.” A “stationmaster” on a railroad is, as you can probably guess, the person in charge of the train station.
If you were a slave and you were going to try and escape with the help of the Underground Railroad, you would receive a “ticket,” which is the information on when and where you will start your journey. You, as a slave, would be called a “passenger” (person who pays to travel on trains, buses, and other transportation) or “cargo” (goods that travel from one place to another). If there was a problem with the “route” or path that you took, then the “tracks” would need to be fixed. The “tracks” are the metal rails or lines that the trains travel on.
Using these special terms to describe the parts and activities of the Underground Railroad helped to keep it a secret, and allowed thousands of slaves to travel from the South to the North.