
= 0001 Introducing Yourself
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== Welcome to Daily English 1 – Introducing Yourself.

This is Daily English number 1. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.

This episode is a story about me, introducing vocabulary you need to talk about yourself. Let’s get started.

[start of story]

Let me tell you a little about myself.

I was born and raised in Minnesota and I’m a native of the city of Saint Paul. I grew up there with my parents and my eight brothers and two sisters. I’m the eleventh child, so you could say I’m the baby of the family, but I swear I wasn’t spoiled.

That’s right, I’m part of a big family, probably the biggest family in the neighborhood, perhaps the biggest family in the state!

I had a happy childhood, for the most part. My father and mother didn’t have a lot of money, but because they both worked hard, we never felt deprived.

I wasn’t much interested in sports, like my brothers were. I enjoyed reading and listening to music while growing up. I went to grade school near my house, and then to high school about two miles away from our home.

After graduating from high school, I went on to the University of Minnesota for my bachelor’s degree. It took me a while to learn the ropes at the university, but I finally graduated about six years later. Better late than never, as my father used to say.

I then went to Mexico for a couple of years to teach English and to study Spanish. When I returned, I decided to become a teacher, so I went back to school to get my master’s degree. After teaching high school for a few years, I was offered a job in California, so I moved to Los Angeles in 1991. After working here for a few years, I went back to school (again!) to get my Ph.D. I was starting to become a professional student.

Well, I completed my Ph.D. in four years and then taught at the university for several years. Now I work at a small research organization here in Los Angeles. I am happily married, and I still enjoy reading and listening to music, and of course, creating ESLPod.com lessons.

[end of story]

Our story begins by me saying, “Let me tell you a little about myself.” I’m going to give you some information about me. I start by saying, “I was born and raised in Minnesota.” “To be born” (born) means, of course, to come out of your mother, to be separated from your mother’s body. “To be raised” (raised) means to be cared for as a child until you are an adult. We might also use the phrasal verb “to be brought (brought) up.” You may, for example, be “born” in one city and “raised” in another, if your parents moved soon after you were born.

In the story I say, “I was born and raised in Minnesota.” Minnesota is a state in the north-central part of the U.S. on the border of Canada. I continue by saying that I am a “native” (native) of the city of St. Paul. A “native” is a person born in a specific place. I am a native of St. Paul because that’s the city where I was born. I could also say, “I’m a native of Minnesota,” because I was born in the state of Minnesota. I could say, “I’m a native of the United States,” because I was born in the United States. So, depending on what place you want to use, you can say you are a “native” of that particular place.

Well, I was a native of St. Paul. I grew up there with my parents and my eight brothers and two sisters. I say then, “I am the eleventh child, so you could say” – that is, you could call me – “the baby of the family.” The “baby” (baby) here means the youngest person in the family, or the youngest child of your parents. We call that person “the baby of the family.” The word “baby” usually refers to a child from the time he is born until maybe two or three years old, but if someone says, “he’s the baby of the family” or “she’s the baby of the family,” he means that person is the youngest of the family. We would say the youngest “sibling” (sibling). Your “siblings” are your brothers and sisters.

Now, in many families, the baby of the family is “spoiled.” “To be spoiled” (spoiled) is to get whatever you want and often to not behave very well, especially if you’re a child. If parents spoil their children, the children get whatever they want, and because of that, they often don’t behave or act like they should. They don’t act politely. Well, I was not spoiled even though I was the youngest, or baby of the family.

“That’s right,” I say, “I’m part of a big family, probably the biggest family in the neighborhood.” A “neighborhood” is an area inside of the city where you live. Most cities have several neighborhoods or areas. I say that “I had a happy childhood.” Your “childhood” (childhood) refers to the period during which you were growing up, from the time you were a baby until you became an adult or perhaps a teenager – 13, 14, and so forth. That’s your “childhood.” Some people have a happy childhood. Some people have a sad childhood.

I say that my childhood was happy “for the most part.” That expression “for the most part” means mainly or in most cases – or in this case, perhaps the majority of the time. Sometimes, of course, my childhood was not happy, but usually it was. I explain that my mother and father “did not have a lot of money” – they were not rich – “but they both worked hard,” meaning they worked a lot. Because they worked a lot, they had enough money to give us what we needed as children. Therefore, or because of that, we never, I say, “felt deprived” (deprived). “To feel deprived” means to not have everything you need to be happy, not have the things that you want to have in order to have a good life.

I say that “I wasn’t much interested in sports.” I didn’t like playing sports, but my brothers did. I instead “enjoyed reading and listening to music while growing up.” I say that “I went to grade school near my house.” “Grade (grade) school” is also called, in the U.S., “elementary school.” It’s the first five to eight years of a child’s education, depending on the school. Sometimes these are also called, in certain areas, “grammar school,” although that isn’t a term as commonly used now as it was, say, 50 years ago. We usually refer to grade schools as elementary schools, nowadays.

I then went on to high school, which in the U.S. is normally grades 9 through 12, though it might be grades 10 through 12 depending on the school system. My high school was grades 9 through 12. “After graduating” – that is, after completing high school – “I went on to the University of Minnesota for my bachelor’s degree.” “To go on to” means to move to the next level – in this case, the next level of my education, which was college or the university. I went to the University of Minnesota for my “bachelor’s (bachelor’s) degree (degree).” A “degree” is a certificate or recognition of study at a certain school. A “bachelor’s degree” is given after typically four years of study at a college or university.

I say that, “It took me a while” – that is, a long time – “to learn the ropes (ropes) at the university.” The expression “to learn the ropes” is an idiom meaning to learn how things are done in a certain group or organization, or to learn how to do a certain kind of job. In this case, I was learning how things worked at the university. I say that “I finally graduated,” or completed my studies, “about six years later.” That is, instead of taking the normal four years at university, I took six years because, well, I’m just not very smart.

I then say, “Better late than never.” The expression “Better late than never” means it is better to do something, even if you don’t do it quickly, as long as you are able to complete it or finish it. So, my father used to say, “Better late than never” about my university studies because it took me so long to finish, but I did in fact finish. Well, at least my bachelor’s degree. “I then went to Mexico for a couple of years to teach English and to study Spanish.”

“When I returned, I decided to become a teacher, so I went back to school” – that is, I returned to the university – “to get my master’s degree.” A “master’s (master’s) degree” is a one, sometimes two-year degree that is given for studying about a certain topic after you complete your bachelor’s, or typically four-year, degree. A “bachelor’s degree” is sometimes called an “undergraduate degree,” and a “master’s degree” is a graduate degree.

There are actually two graduate degrees that are common. One is a “master’s degree,” done immediately after or at least at some point after finishing your bachelor’s degree. There’s also a “doctoral” or “doctorate degree.” That takes longer. There are many different kinds of graduate degrees, however, but “master’s” and “doctorate,” which we also call a “Ph.D.,” are the most common graduate degrees.

“After teaching high school,” I say, “I was offered a job in California,” which is true, “and I moved here in 1991. After working here for a few years, I went back to school again to get my Ph.D.” A “Ph.D.,” as I mentioned, is a graduate degree. It usually takes somewhere between four and seven years to complete. After you get your Ph.D., you can be called “Doctor.” “I started becoming a professional student,” I say.

I then finish by saying that “I completed my Ph.D. in four years and then taught at the university for several years.” I taught at a couple of different colleges after I got my Ph.D. “Now I work at a small research organization.” “Research” (research) is used to describe efforts to learn more about something, either in a scientific or other disciplined way. I work at a research organization here in Los Angeles.

I say, “I am happily married.” “To be married” (married) means to have a husband or a wife. “I am happily married, and I still enjoy reading and listening to music, as well as, of course, making these ESLPod.com lessons.”

Now let’s listen to the story again, this time at a normal speed.

[start of story]

Let me tell you a little about myself.

I was born and raised in Minnesota and I’m a native of the city of Saint Paul. I grew up there with my parents and my eight brothers and two sisters. I’m the eleventh child so you could say I’m the baby of the family, but I swear I wasn’t spoiled.

That’s right, I’m part of a big family, probably the biggest family in the neighborhood, perhaps the biggest family in the state!

I had a happy childhood, for the most part. My father and mother didn’t have a lot of money, but because they both worked hard, we never felt deprived.

I wasn’t much interested in sports, like my brothers were. I enjoyed reading and listening to music while growing up. I went to grade school near my house, and then to high school about two miles away from our home.

After graduating from high school, I went on to the University of Minnesota for my bachelor’s degree. It took me a while to learn the ropes at the university, but I finally graduated about six years later. Better late than never, as my father used to say.

I then went to Mexico for a couple of years to teach English and to study Spanish. When I returned, I decided to become a teacher, so I went back to school to get my master’s degree. After teaching high school for a few years, I was offered a job in California, so I moved to Los Angeles in 1991. After working here for a few years, I went back to school (again!) to get my Ph.D. I was starting to become a professional student.

Well, I completed my Ph.D. in four years and then taught at the university for several years. Now I work at a small research organization here in Los Angeles. I am happily married, and I still enjoy reading and listening to music, and of course, creating ESLPod.com lessons.

[end of story]

From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESLPod.com.

English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2017 by the Center for Educational Development.

Glossary
to be born – to exist as a result of birth; to have come from a mother’s or parent’s body

* Jeb and Chris are brothers and were born about two years apart.

to be raised – to be brought up as a child; to be cared for as a child until one is an adult

* Omar was raised in the countryside and enjoys horseback riding and outdoor sports.

native – a person born in a specific place; a person from a particular place

* Many people who live in Los Angeles are not natives to the city, having moved there from somewhere else.

baby of the family – the youngest sibling; the youngest child of a set of parents

* Ricky is the baby of the family and complains about being told what to do by all of his sisters.

spoiled – a child who gets whatever he or she wants and doesn’t follow rules, behaving badly as a result

* Jiyoung’s granddaughter is really spoiled and doesn’t listen when other people tell her no.

childhood – the years during which a person is a child; the state of being a child

* What are your happiest childhood memories?


for the most part – mainly; in most cases

* Beatrice arrives to work on time for the most part. The only time she is ever late is when her children are sick.

deprived – not having what one needs to be content; not being allowed to have or to use something

* If I don’t follow my parents’ rules, I’m deprived of my videogames for a few days as punishment.

grade school – elementary school; a school for the first five to seven years of a child’s education

* Did you learn to read well in grade school?


to go on to – to proceed to; to move forward to; to move to the next level

* When you’re finished with page one of the exam, turn the page and go on to page two.

bachelor’s degree – an undergraduate degree, typically earned after four years of study at a college or university

* Clara has a bachelor’s degree in computer science, but she’s working in finance.

to learn the ropes – to learn how things are done in a particular organization; to learn how to do a particular job or activity

* It’s expected that new employees will make a few mistakes until they learn the ropes.

to graduate – to complete a course of study or a course of training

* Sophie plans to graduate from college this spring and hopes to find a job in her field.

better late than never – a saying meaning that it is better to do something late than to not complete it at all

* A: Here are the chairs I promised to bring for the party.

B: You’re two hours late, but better late than never.

master’s degree – a graduate degree that is given to a student by a college or university after completing one or two years of study after a bachelor's degree

* If you want to be a pharmacist, you’ll need a master’s degree to work in most pharmacies.

Ph.D. – a graduate degree that is given to a student by a college or university after several years of additional study following a master's degree

* Kwame hopes to become an English professor at the local college after he gets his Ph.D.

research – efforts to learn more about something, often in a systematic and scientific way

* Will breast cancer research lead to a cure in the next 50 years?

happily married – feeling content and happy in one’s marriage

* Pat and Mary are still happily married after being together for over 50 years.

Culture Note
Improving Bicycle Safety

Riding a “bicycle” (a vehicle with two wheels ridden with one’s feet while steering with a bar called “handlebars”) is part of many people’s childhoods. The National Highway Traffic Safety Administration (NHTSA) is a “federal” (national) government “agency” (section of the government) within the Department of Transportation. Its “mission” (goal) is to, "Save lives, ‘prevent’ (keep from happening) injuries, reduce vehicle-related ‘crashes’ (when two vehicles hit each other unexpected and violently)."

The NHTSA has advice for bicycle riders to try to “reduce” (make smaller or less) accidents. Their advice includes:

Wear a bicycle “helmet” (hard hat with a strap under the chin) that is “fitted” (sized) properly to protect your “brain” (organ in your head that allows you to think and control your body).
“Adjust” (make changes to) your bicycle to fit your body. There should be 1 to 2 inches between you and the top “bar” (long hard piece) if using a “road bike” (bicycle intended to be used on streets) and 3 to 4 inches if you are using a “mountain bicycle” (bicycle used for rough paths). The seat should be “level” (having the same height) front to back. The seat height should be adjusted to allow a “slight” (small; little) “bend” (curve) at the knee when the leg is “fully extended” (at full length). The “handlebar” (piece of a bicycle or motorcycle a rider holds) height should be at the same level with the seat.
Make sure you’re able to see well and others are able to see you. Always wear bright colors when riding day or night. Also wear something that “reflects light” (throws back light), such as reflective “tape” (material that I sticky on one side) or markings, or “flashing” (going on and off repeatedly) lights. Remember, just because you can see a driver doesn’t mean the driver can see you.


'''