= 0305
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome to EnglishPod.
My name is Marco.
My name is Catherine and today we're going to be talking about a very fun game.
That's right.
Today we're going bowling, a very popular sport amongst many people.
And so we're going to take a look at how you play this sport and all the vocab related to this great game.
Alright, so let's take a listen to our dialogue and we'll be right back.
Alright, so the first thing you need to know about bowling is that you should never cross that line where the lane begins.
Why not?
Because they polish and oil it to make the ball slide down.
If you step there you'll slip and fall.
Okay, so I got my bowling shoes, my ball, our name's on the scorecard, so now how the heck do I play this?
You throw the ball down the lane and try to knock down all the pins.
If you do, that is called a strike.
If you don't knock them all down on the first try, then you get a chance to get the spare.
After 10 frames we add up the points and see who has the most.
300 is a perfect score, but very hard to get.
Got it.
Okay, I'm going to give it a go.
Oh no, my ball went in the gutter.
I told you, it's harder than you think.
Now let a pro show you how it's done.
Alright, we're back, so now let's take a look at some of that vocab on Language Takeaway.
Language Takeaway.
So the first word we have today in Language Takeaway is lane.
That's right, a bowling lane.
So a lane, that is where you actually play this game.
That's right, a lane is also a word for like a road, a small narrow road.
So in bowling this is the flat surface, the floor that's long that you roll the ball down.
That's right, okay so that's your lane.
So as you said, you roll the ball down the lane and you try to knock down the pins that are at the end of the lane.
That's right, so pins are, they're a little bit heavy, they're usually white and they have, they're wide at the bottom and narrow at the top.
They almost look like wine bottles.
Exactly.
And the goal of the game is to knock these down to make them fall on the ground.
That's right, okay so that's why you are using, that's why you are throwing the ball down the lane to knock down these pins.
Now, if you knock all of them down on your first try, that's called a strike.
A strike, that's right.
So that means all ten pins fall down on your first try.
But sometimes you don't get a strike, you maybe knock down eight pins and then later on your second try, because every person gets two tries, on your second try you knock down the last two pins.
Now what's that called Marco?
So if you knock all of them down on your second try, that's called a spare.
Okay, strike, usually you write it with an X, that's on the scorecard, and a spare, which is two tries to get all ten pins, that's a slash.
That's right.
And if you don't get all of the pins in two tries, you still get points.
So if you knock down eight pins you get eight.
Or if you knock down four pins you get four.
That's right.
And you put your score on your scorecard, and now each player usually gets ten frames, or ten different opportunities to knock down all the pins.
Alright, so usually these are boxes on the scorecard, and you can play ten frame bowling, or also five frame, but it's important to remember that each frame gives you the opportunity to bowl two times.
Right.
Alright, so you get those two tries.
So really it's twenty total tries to knock down these pins.
That's right.
And now if you did really well, and on every opportunity of each frame you got a strike, that means that you would get a perfect score.
That's right, a perfect score.
That means that you made no mistakes, you knocked down all the pins on the first try.
And now obviously down the lane, it's not as easy as it looks, because to the sides of your bowling lane you have this kind of a path that's to the bottom, so if your ball goes in there you can't get it out.
That's right.
So remember like I said earlier, a lane is also the name of a place where we can walk or drive, it's like a road.
Well we have gutters which are on the sides of these roads, and also in bowling, gutters.
They're lower, and normally on the streets they're for water, but in bowling they're the places on the right or the left side where your ball will fall.
And if your ball falls into the gutter, or it rolls into the gutter, you will hit no pins.
Right.
I think that's the main thing, if your ball goes in the gutter, you don't hit any pins at all, it just goes straight down and you don't hit anything.
That's right, so it's really sad when you bowl badly and you get a gutter ball we call it.
That's right.
Alright, so let's take a look at all this vocab again, let's listen to our dialogue.
And we'll be back in a bit with Fluency Builder.
You throw the ball down the lane and try to knock down all the pins.
If you do, that is called a strike.
If you don't knock them all down on the first try, then you get a chance to get the spare.
After 10 frames, we add up the points and see who has the most.
300 is a perfect score, but very hard to get.
Got it.
Okay, I'm going to give it a go.
Oh no, my ball went in the gutter.
I told you, it's harder than you think.
Now let a pro show you how it's done.
Alright, so we've picked out three different phrases for you, let's take a look at those now in Fluency Builder.
Fluency Builder.
Alright, so the first phrase that we have today is something that you're going to hear a lot, although I want to remind everyone this is very informal.
So, we heard someone say in the dialogue, so now how the heck do I play this?
Okay, so how the heck do I turn this computer on?
Okay, so how do I turn this computer on means I don't know, please help me.
But how the heck means I really don't know, I really need your help.
That's right, I really don't understand what's going on, I need someone's help.
Like how the heck did this happen means I absolutely did not expect this to happen, I'm very surprised.
That's right, it's actually a not very polite phrase to use, but at the same time it's not terribly impolite.
It's in the middle.
But it's very informal.
Alright, so now the person understands how to bowl, how the game works and he says, okay, got it, I'm going, I'm gonna give it a go.
Okay, I'm gonna means I'm going to, and this is very informal.
Gonna is a way to say going to, I will.
But the phrase here is give it a go.
What does that mean, Marco?
Give it a go.
So if you're gonna give it a go, it means that you're going to try.
Okay, so I'm gonna try.
So we can say this, now that we know how to play the game, let's give it a go.
Let's try to play.
Because we've been talking about it, but we haven't been doing it.
So to give it a go means to try to do something.
Exactly, and that's basically it.
If maybe you're watching a game on the street and you want to try maybe a card game, you say, okay, I want to give it a go.
I want to give it a go.
Alright, and what about our last phrase?
Now the very last phrase is the last phrase of our dialogue.
The character says, now let a pro show you how it's done.
Alright, so how it's done, this let me show you how it's done, because this person is saying, I'm a pro, let me show you how it's done, is a very interesting way of saying something in English.
What is the real meaning of this phrase?
He's basically saying, now let me show you how to do it.
Okay, the correct way.
Right.
So basically he's saying, you didn't do it very well, you didn't bowl very well, you're new.
Let me show you how professional people bowl.
Right.
Let me give you an example.
Exactly.
Maybe you and your friend are making a cake and you don't really know what you're doing, so your friend says, move over, let me show you how it's done.
That means the proper way to do it, the correct way.
So Marco, you're not doing it right, let me show you how it's done.
Exactly.
A very useful phrase and actually it can seem a little bit confusing because you're using the verb there done.
So it may seem a little bit weird, do, done, but don't worry about it, just take it as a phrase, let me show you how to do it, let me show you how it's done.
That's right.
So that's all we've got for Fluency Builder today, let's take another listen to our dialogue and we'll be back in a second.
Alright, so the first thing you need to know about bowling is that you should never cross that line where the lane begins.
Why not?
Because they polish and oil it to make the ball slide down.
If you step there you'll slip and fall.
Okay, so I got my bowling shoes, my ball, our name's on the scorecard, so now how the heck do I play this?
You throw the ball down the lane and try to knock down all the pins.
If you do, that is called a strike.
If you don't knock them all down on the first try, then you get a chance to get the spare.
After 10 frames we add up the points and see who has the most.
300 is a perfect score, but very hard to get.
Got it.
Okay, I'm gonna give it a go.
Oh no, my ball went in the gutter.
I told you, it's harder than you think.
Now let a pro show you how it's done.
Alright, we're back, so bowling is actually a very, kind of like a past time in the United States.
You get together with friends and you just go bowling.
That's right, I do believe it's also considered a sport, so many people play professionally or semi-professionally, but for me it's always been a very social game, something you do with a group of friends, you go out, it's really fun.
Yeah, especially because when you go bowling many people can play, right?
Obviously at the same time, but you take turns and so while you're waiting people are talking and eating, so it is a very social activity.
That's right, so maybe a group of people will rent a lane, remember we were talking earlier about a lane being that one kind of strip of wood where you roll the ball.
Well, a group of friends can rent a lane or two lanes and the four or the eight of you can play together, each person playing one frame at a time.
That's right, and now actually the other thing about it is it's very funny to see people trying to bowl or maybe with the heavy ball or maybe they pass the line that we said they shouldn't pass and they slip and fall, so I guess that's what also makes it a little bit fun to play.
Yes, it can be a little bit embarrassing if you're not, I'm not very good, so I'm a very embarrassing bowler, but it's also really fun because if you go and you just have a nice time, it's a very social game.
Well, it is and actually we are really curious to know if you've ever been bowling, I know many people who've never been bowling and they find it very, very fun, so why don't you come to our website, EnglishPod.com and leave your questions and comments there as well.
Yeah, we hope to see you there, until next time guys.
Bye. +
