= 0308
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome to EnglishPod.
My name is Marco.
Hi guys, my name is Catherine and today we're talking about something that is a little bit private.
That's right, but very necessary to learn in English because it's very, very useful.
That's right.
So we're talking about clothing, more specifically underwear.
So the clothes you wear under your clothes.
That's right.
Okay, so let's just jump into the dialogue.
Let's see what happens today and we'll be back in a bit.
Lili, I found a pair of men's boxers in the laundry machine this morning.
What?
That's weird.
Are they your boyfriends?
Nah, Kevin only wears briefs.
Plus this pair is extra small.
What do they look like?
They're light blue with thin pink stripes.
Oh, and there's a Snoopy on it, which is hilarious.
Those are my undies.
Alright, so a lot of great vocab there.
Let's take a look at that now on Language Takeaway.
Language Takeaway So the first thing we have here in Language Takeaway is actually very interesting, Marco, because we don't say one underwear or one boxers.
We say a pair of, just like pants, a pair of pants or a pair of underwear.
A pair of pants, a pair of shorts, socks.
The same thing goes for underwear.
So I really don't know why, because it's one piece.
So are pants, but basically you have two holes, two places for your legs.
So anything with your legs, your socks, your shoes, your pants, your underwear, we say a pair because you've got the both sides, left and right.
Okay, alright, so you've got a pair of men's boxers.
Now, before we describe the underwear part, let's take a look at this other machine, a laundry machine.
Okay, so you know what a machine is.
It's usually something that uses electricity to help us with a task or a job.
But a laundry machine is special because it helps us clean our laundry.
What kind of things are laundry?
So anything that's your clothes.
So basically it's also called a washing machine, right?
So laundry machine or washing machine, same thing.
It uses water and soap to wash your clothes.
That's right.
Okay, so now let's get into the type of underwear here, specifically for men.
Usually we have boxers, boxer shorts.
That's right.
So shorts means that they're not long, they're short.
But boxers or boxer shorts, as you say, are usually pretty loose.
They're not very tight.
And they're longer than the other kinds of underwear we have.
Okay, so boxers are a type of underwear that men wear under their clothes.
And as you say, they're pretty much shorts.
But they're called boxers or you can call them boxer shorts.
Now, I guess the classic or the common form of men's underwear are called briefs.
Briefs.
Now these are smaller than boxers and they're tighter.
And they are usually made out of some kind of material that stretches.
You can pull them a little bit.
And this is again a smaller kind of underwear.
That's right.
So boxers are more like shorts.
Briefs are kind of...
And briefs are not really shorts.
They're more like a, I guess, kind of like a swimming suit.
They look like a bathing suit bottom for men.
Okay.
Now, that's it, right?
Okay.
Andes.
Okay.
So both these things we could actually describe as undies.
That's right.
So undies is a common spoken language way of saying underwear.
Okay.
So it's very casual.
And it's usually something that we say with our family or friends.
Especially moms like to say this with their kids.
All right, honey.
I'm gonna buy you some new undies this week.
And of course, as a child, you feel very embarrassed.
Undies is a way to say underwear.
All right.
Okay.
So that's all the vocab that we have for you on Language Takeaway.
Why don't we listen to our dialogue again?
And we'll be back in a bit with Fluency Builder.
Lily, I found a pair of men's boxers in the laundry machine this morning.
What?
That's weird.
Are they your boyfriend's?
Nah, Kevin only wears briefs.
Plus, this pair is extra small.
What do they look like?
They're light blue with thin pink stripes.
Oh, and there's a Snoopy on it, which is hilarious.
Those are my undies.
All right, we're back.
So now let's take a look at some descriptive words in Fluency Builder.
Fluency Builder.
All right.
So as you said, Marco, we have a lot of great phrases today and some words for describing underwear.
And you can describe other things with these words as well.
The first one we have is a phrase extra small.
Okay.
So when you buy underwear the size is, you sometimes get small, extra small, large, medium, but it's just a way of describing how big it is.
Right.
So you know the S, the M, and the L are small, medium, and large.
But if you see the XS, that's extra small.
It means it's very small.
All right.
We also have XL, which is extra large.
That's right.
Okay.
So now that we've described the size, now we're going to describe a little bit of how they look like, the colors, and maybe any characteristics.
So the first thing that we see is the color is light blue.
Okay.
So we've got blue, which is normal blue.
We have light blue, which is maybe the color of the sky on a beautiful summer day.
There's also, we didn't hear it in today's dialogue, but there's another color.
It's dark blue, which is almost more like purple or black.
That's right.
So this is the way of describing a color.
Now it can be for any color except white.
You don't really say light white or dark white.
Yeah, you don't.
So you could say light green, dark green, light orange, dark orange.
Okay.
And now some characteristics.
They had some thin pink stripes.
So we have the word here thin.
So not fat, thin.
Pink, we have the color, but what are stripes?
Okay.
Stripes are a very common design for clothes and you often see stripes.
They're like lines.
And so that means that you have different lines that are pink.
You often see stripes on flags.
So for example, the American flag has red and white stripes.
Okay.
Very good.
So as you said, they're lines and yeah, usually in clothing you can find maybe shirts.
They have vertical stripes or sometimes even horizontal stripes.
Yes.
But these undies are quite unique.
They're very special because they have pink stripes.
That's right.
Okay.
So that's all the language we have for you.
Why don't we listen to our dialogue one last time and we'll be back in a little bit.
Lily, I found a pair of men's boxers in the laundry machine this morning.
What?
That's weird.
Are they your boyfriend's?
Nah, Kevin only wears briefs.
Plus this pair is extra small.
What do they look like?
They're light blue with thin pink stripes.
Oh, and there's a Snoopy on it, which is hilarious.
Those are my undies.
All right.
So in this case, we're talking about men's boxer shorts because there was a confusion about the boyfriend, but women also wear boxer shorts.
It's very popular now among women.
Yeah, it is.
It's usually something that women wear over their underwear.
Women don't really wear boxer shorts as underwear.
Women's underwear is smaller.
It's like men's briefs.
They're small.
So if a girl wears boxers, and it's usually for maybe if they're just around the house and you don't want to wear pants and you don't want to wear shorts, you can just wear a pair of comfortable boxer shorts.
Exactly.
Like they wear pajamas.
And actually, I think a lot of girls also use boxer shorts as pajamas, right?
That's right.
They're comfortable and they're light and they're usually made from cotton, which is a nice material to sleep in.
Now, when we're talking about briefs, there is also another way that I've heard that they're called sometimes a more maybe funny way of calling them that some people say they're called tighty whities.
That's right.
This is usually something we say to joke because in America, at least many men like to wear young men like to wear boxers.
So they call briefs tighty whities.
Because usually their briefs are just white.
They're plain.
They don't have any design or any other color.
Now they're plain and they're white usually or gray and they're tight, not like boxers.
So the casual name, this is not something you want to say to your English teacher.
The casual name or the funny name is tighty whities.
Tighty whities.
And actually, this is a very interesting because with newer generations, I think men are wearing boxers instead of briefs before.
I think the only option was briefs.
Exactly.
But now boxers have grown more and more popular.
And I think when you're a little kid, your mom always buys you little briefs and everything.
But then when you're a teenager, I think you just switch over to boxers.
It's not as cool anymore to wear briefs.
Yeah, I think it's the whole fact of how kids sometimes dress with saggy or baggy pants.
And so they like to show their boxers.
That's right.
Underneath for some reason.
I don't really understand it.
But if you do let us know our website is EnglishPod.com.
We're going to have all the vocabulary and stuff on the website.
So check it out.
All right.
We'll see you guys there.
Bye.
Bye. +
