= 0337
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome to EnglishPod.
My name is Marco.
My name is Catherine and a very Merry Christmas to everyone.
That's right, Merry Christmas.
We are at that time again where we are celebrating Christmas, we're having dinner with family and friends, we're giving presents, and of course, there are some other traditions that come into play, like for example Santa Claus.
Santa Claus.
So, we've got a very special advanced level lesson for you today.
We've got a poem.
It's a very traditional poem that is read or listened to on the holiday.
And we're going to talk a little bit about some of the interesting words and phrases that are used in this.
But first off, let's just listen to the poem itself.
Twas the night before Christmas when all through the house Not a creature was stirring, not even a mouse The stockings were hung by the chimney with care In hopes that St.
Nicholas soon would be there The children were nestled all snug in their beds While visions of sugar plums danced in their heads And Mama in her kerchief and I in my cap Had just settled down for a long winter's nap When out on the lawn there arose such a clatter I sprang from the bed to see what was the matter Away to the window I flew like a flash Tore open the shutters and threw open the sash The moon on the breast of the new fallen snow Gave the lustre of midday to objects below When what to my wondering eyes should appear But a miniature sleigh and eight tiny reindeer With a little old driver so lively and quick I knew in a moment it must be St.
Nick More rapid than eagles his coursers they came And he whistled and shouted and called them by name Now dasher, now dancer, now prancer and vixen On comet, on cupid, on donder and blitzen To the top of the porch, to the top of the wall Now dash away, dash away, dash away all As dry leaves that before the wild hurricanes fly When they meet with an obstacle mount to the sky So up to the housetop the coursers they flew With the sleighs full of toys and St.
Nicholas too And then in a twinkling I heard on the roof The prancing and pawing of each little hoof As I drew in my head and was turning around Down the chimney St.
Nicholas came with a bound He was dressed on fur from his head to his toe And his clothes were all tarnished with ashes and soot A bundle of toys he had flung on his back And he looked like a peddler just opening his pack His eyes, how they twinkled, his dimples, how merry His cheeks were like roses, his nose like a cherry His droll little mouth was drawn up in a bow And the beard of his chin was as white as the snow The stump of a pipe he held tight in his teeth And the smoke it encircled his head like a wreath He had a broad face in the little round belly That shook when he laughed like a bowl full of jelly He was chubby and plump, a right old jolly elf And I laughed when I saw him, in spite of myself A wink of his eye and a twist of his head Soon gave me to know I had nothing to dread He spoke not a word but went straight to work And filled all the stockings then turned with a jerk And laying his finger aside of his nose And giving a nod up the chimney he rose He sprang to his sleigh, to his team gave a whistle And away they all flew like the down of a thistle But I heard him exclaim, ere as he drove out of sight Happy Christmas to all, and to all a good night!
The story of the poem is that Santa Claus is coming to visit someone's house And there's a person in the story who is watching Santa Claus arrive And he's seeing Santa Claus take the reindeer up onto the roof Come down the chimney and lay the presents out for the children Filling the stockings as well So it's basically a nice poetic description of Santa Claus And also it goes in to describe in a very nice way the way Santa Claus looks like It's very descriptive We have descriptions of what Santa Claus looks like What he's wearing, his smile, how he's a little bit fat We also have descriptions of the animals These special animals that we hear about so often that are called reindeer Alright, so we've divided up the poem into by line So then it's going to be easier for you to go to the line that we're talking about Let's start with the first line With this first word that's actually very interesting Twas the night before Christmas when all through the house So what does this first word mean?
Twas is an abbreviation, so it's a shortened version of it was Okay, so do you actually use this now if you're writing?
No, this is not something I would use now in writing And it's not something I would say It's actually more of an archaic form, something that you might hear in poetry or historical writing Okay, so it was the night before Christmas, right?
So we're talking about December 24th The night of December 24th, that's right Alright, so the first two lines talk about how it was the night before Christmas And in the house there was nothing stirring, not even a mouse So not even the smallest little animal So it's very quiet in the house is what's happening So now we jump to line number seven where the poet describes And mama in her kerchief and I in my cap So we know that the person talking is the dad Because he's talking about himself and mama, mother, they're in bed together And mama in her kerchief and I in my cap So I'm wearing a night cap, a cover on my head, it's like a hat And mama has a kerchief What's a kerchief?
A kerchief is another abbreviation, it's short for handkerchief And a handkerchief is a piece of fabric or cloth That sometimes we use for our noses when we have to blow our nose But also you can use a kerchief in your hair to cover your hair Okay, so if you can imagine it, this must take place, I don't know, maybe 50, 60 years ago And dads used to wear hats to bed and women also handkerchiefs on their heads Or longer, maybe 200 years ago when people wore these long night hats, night caps The pajamas and everything Alright, now let's jump over to line 18 and 19 When he's talking about the reindeer and the sleigh arriving And he says, I knew in a moment it must be Saint Nick This is another way of calling Santa Claus, right?
Saint Nicholas is his name, but you also call him Claus or Santa Claus Okay, and then he said, more rapid than eagles, his coursers they came So the word order is a bit strange here, this is common in poetry We could also say, his coursers came more rapidly than eagles They were very, very fast But what are these coursers?
We're talking about the animals pulling Santa Claus And what are those animals again?
They're called reindeer Reindeer, so the reindeer are very, very fast Okay, that's right, because he's making the comparison about how fast eagles are compared to them And we hear their names, right?
Exactly, he goes on to say, now dasher, now dancer, now prancer And all of their names, vixen, comet, cupid, donder, and blitzen All eight reindeer, each animal has its own name That's right, so all eight reindeer Actually, we're missing one though that's very common nowadays The reindeer that goes in the front, illuminating the sky Rudolph the red-nosed reindeer You might know the song, Rudolph the red-nosed reindeer That's right, that's right So there are actually nine reindeer nowadays But I guess this story was before the Rudolph story came out Alright, so those are, this is interesting because those are the names of all the reindeer Now, I'm not sure in which order they are, I don't know who's in the back, who's in the front Yeah, I don't know either, but it's important to know that they're very fast And they come down and then they go up They have to take Saint Nicholas to the roof of the house, on top of the house That's right, so now he arrives to the top of the house Line 32, we see down the chimney, Saint Nicholas came with a bound He came quickly down the chimney, boom And at the end, he's all dressed in fur From his head to his foot, so top to bottom, he has fur on That's right, and I think he's got fur because he lives in the North Pole, right?
That's right, and it's very cold where Santa Claus lives So he has to wear these clothes that are very warm Okay, and obviously since he is going up and down chimneys in line 34, we see And his clothes were tarnished with ashes and soot So to tarnish, or tarnish means dirty Something is tarnished if it's dirty, so his clothes, his fur clothes were dirty with ashes and soot This means that, you know, in your fireplace when the fire is gone, there's some grey and black stuff And that's what's on Santa Claus' clothes Okay, very good So, and then we go on to line 35, a bundle of toys he had flung on his back And he looked like a peddler just opening his pack Alright, a peddler, now this is not just something we talk about on Christmas You know, we have peddlers all year round What are peddlers, what do they do?
Basically they go around selling things So maybe you see them in a small market or sometimes in different places And maybe, I don't know, on the streets you see them selling little things like toys or combs or books, something like this Oranges, you see fruit peddlers, people who sell fruit Or you could see those watch peddlers, you know, they say, would you like a Rolex watch?
That's a watch peddler So that's what they do, right, they just, they're informal salesmen They don't have a store, they work on the street So this is why Santa looks like a peddler He isn't in a store, he has a bag, and he says, look in my bag Right, exactly, now from line 37 we go on to describe the way Santa Claus looks like So, he says, his eyes, how they twinkled, his dimples, how merry Dimples are those small circles on your cheeks So some people when they smile they have these small holes or circles, those are dimples, they're very cute That's right, so not everyone has them, right, some people when they smile you can see those dimples Alright, so, and his cheeks were like roses, his nose like a cherry, so we're saying that they're red They're red, they're pink Okay, now in line 39 he says, his droll little mouth was drawn up like a bow Now, droll is a word that some people still use, it's pretty common in places like England We don't use it as much in America, we say funny instead, but something that is droll, d-r-o-l-l, droll is funny Okay, so his mouth, his face is funny looking Okay, his face is funny looking, alright And going on to line 45 we're describing how he was chubby and plump So we're basically saying he was a little bit fat Yes Okay, a right jolly old elf, so what is an elf?
An elf is, actually normally we talk about elves, so one elf, two elves As people, little people who help Santa, they're mythical creatures who live in the North Pole and who make presents So an elf is a small creature who makes presents Okay Or maybe lives in the woods, there are many different stories with elves Elves, right, right, okay And in line 46 we say, and I laughed when I saw him in spite of myself, what does he mean by in spite of myself?
Now this is really important and this is something we say in English all the time, in spite of myself So I laughed in spite of myself, so I didn't want to laugh I wanted to be serious, but I did laugh, so in spite of myself I didn't want to laugh, I laughed anyway So you say in spite of myself when you did the thing you did not want to do Okay, and finishing off we are going towards the last three lines where we say, and away they all flew like the down of a thistle What is a thistle?
They're talking about the part of a flower that's a thistle Oh, okay, so they all flew away quickly, rapidly like the little flower Well you know when a flower is sending its seeds out, it's down, it's white So maybe if you blow on a flower with the white seeds, they blow away That's what it looks like, it looks like the seeds of a flower being blown away, very easy Okay, line 55 says, but I heard him exclaim, ere he drove out of sight So this is an older way of saying, as he drove out of sight, so as he's flying away, I can't see him anymore, almost I can't see him anymore He exclaimed something, so ere means while this is happening Now this is another one of those maybe old English words that we don't use anymore, right?
You wouldn't really use ere Ere I was walking to school, I saw the milkman, no, we don't say this anymore, but you will find it in poetry and you might also find it in stories Okay, and line 56 he ends, and this is very the famous way that this poem ends by saying, happy Christmas to all, and to all a good night Happy Christmas to all, and to all a good night, yeah, and the first line of the poem are the most famous, everyone knows these Okay, very good, so a beautiful poem, why don't we listen to it one more time Twas the night before Christmas when all through the house, not a creature was stirring, not even a mouse The stockings were hung by the chimney with care, in hopes that St.
Nicholas soon would be there The children were nestled all snug in their beds, while visions of sugarplums danced in their heads And Mama in her kerchief, and I in my cap, had just settled down for a long winter's nap When out on the lawn there arose such a clatter, I sprang from the bed to see what was the matter Away to the window I flew like a flash, tore open the shutters and threw open the sash The moon on the breast of the new fallen snow gave the lustre of midday to objects below When what to my wondering eyes should appear but a miniature sleigh and eight tiny reindeer With a little old driver, so lively and quick, I knew in a moment it must be St.
Nick More rapid than eagles his coursers they came, and he whistled and shouted and called them by name Now dasher, now dancer, now prancer and vixen, on comet, on cupid, on donder and blitzen To the top of the porch, to the top of the wall, now dash away, dash away, dash away all As dry leaves that before the wild hurricanes fly, when they meet with an obstacle, mount to the sky So up to the housetop the coursers they flew with the sleighs full of toys, and St.
Nicholas too And then, in a twinkling, I heard on the roof the prancing and pawing of each little hoof As I drew in my head and was turning around, down the chimney St.
Nicholas came with a bound He was dressed all in fur from his head to his toe and his clothes were all tarnished with ashes and soot A bundle of toys he had flung on his back and he looked like a peddler just opening his pack His eyes, how they twinkled, his dimples, how merry, his cheeks were like roses, his nose like a cherry His droll little mouth was drawn up in a bow and the beard of his chin was as white as the snow The stump of a pipe he held tight in his teeth and the smoke had encircled his head like a wreath He had a broad face and a little round belly that shook when he laughed like a bowl full of jelly He was chubby and plump, a right old jolly elf, and I laughed when I saw him, in spite of myself A wink of his eye and a twist of his head soon gave me to know I had nothing to dread He spoke not a word but went straight to work and filled all the stockings then turned with a jerk And laying his finger aside of his nose and giving a nod, up the chimney he rose He sprang to his sleigh, to his team gave a whistle, and away they all flew like the down of a thistle But I heard him exclaim, ere as he drove out of sight, Happy Christmas to all, and to all a good night!
Alright, so this is one of the very famous poems you can listen to.
Usually people listen to it or read about it during Christmas, right?
That's right.
It's a classic.
It's something that you think about people listening to in front of the fireplace and they're drinking their eggnog and talking about how wonderful family is.
So yeah, it's a classic.
It's something that we often talk about and read and listen to.
Alright, so it's very interesting because it's part of the American tradition of Christmas.
I think maybe also in other parts of the world the poem might be translated or also might be popular.
But Santa Claus and all these things are traditions that are observed in some countries and it's very interesting to understand them.
Absolutely, and I'm very curious to know about your Christmas traditions.
What do you do in your home country on Christmas Eve or on Christmas Day?
Do you know any poems like this or do you listen to this poem in translation?
Let us know.
Our website is EnglishPod.com.
Alright guys, we'll see you there and have a Merry Christmas.
Merry Christmas.
Bye. +
