
= step 2 - Lesson 05
:toc:


---


Lesson 5 +

== 1

Herbert Wilson and his wife went to the Isle of Wight for their summer holiday. But they were by no means pleased with their hotel. As soon as they returned home, Herbert decided to write to the Manager of Happytours. +
Herbert: Can you spare a moment, dear? I want you to listen to this letter. +
Margaret: Go ahead, then. +
Herbert: Dear Sir, my wife and I arrived home last night after a holiday arranged by your firm, in Jersey. We stayed at the hotel described in your brochure as a comfortable, medium sized hotel, with a magnificent view of the sea, offering courteous, old fashioned service and excellent food, served in a relaxed friendly atmosphere. +
Margaret: Yes, that's what the brochure said. +
Herbert: In fact the hotel is situated at least half a mile from the sea. Our room overlooked a car park ... +
Margaret: Through the gates of which motor vehicles were constantly arriving or departing. +
Herbert: Yes, that's good. The food was strictly beef burgers and chips or fish and chips. Wine was available, but at exorbitant prices, and as for the courteous, old fashioned service, the majority of the staff were foreign and virtually incapable of speaking or understanding the English language. +
Margaret: Yes, that's quite true. +
Herbert: In addition to this, we were most unhappy with the arrangements for our journey home. We were instructed to catch the 11:00 am ferry ... +
Margaret: Wasn't it 12:00? +
Herbert: No, 11:00 ... but this was apparently delayed and we did not get away till 6 o'clock in the evening. Now that our holiday is over, it seems fairly pointless writing this letter, but I should like you to know that we were most disappointed with the hotel and travel arrangements and shall certainly not be booking any future holidays through Happytours. Yours faithfully, Herbert Wilson. +
Margaret: Yes dear, that's a very good letter.

---

== 2

Miss Bush is talking to a travel agent in London. +
Travel Agent: Good morning. Can I help you? +
Miss Bush: Hello. Er, my name's Miss Bush and I'm intending to go to a conference in Sydney for three weeks. +
Travel Agent: I see. Er, do you want the excursion fare or the full return fare. +
Miss Bush: Now, can I get a stopover on an excursion fare? +
Travel Agent: Yes, you're allowed only one stopover on the excursion fare. +
Miss Bush: Oh, only one. +
Travel Agent: Yes. But of course, if you pay the full return fare then you can have unlimited stopovers. +
Miss Bush: Oh that's much better. Yes. You see, the thing is that I've got two weeks' holiday after the conference and I've never been out that way before at all to Australia or the Far East, and I, I wanted to go, you know, shopping or seeing Hong Kong or India or somewhere round there. +
Travel Agent: Yes. Uhum. +
Miss Bush: Um, where exactly can I go? +
Travel Agent: Well, lots of places. There's Singapore or um, Teheran, Kuwait, Athens, you've really got quite a lot of choice you know. +
Miss Bush: Mm. Well, it sounds marvellous. Um, how much would that cost? How much is the full fare? +
Travel Agent: The full fare? Well, that's really quite a lot. It's ￡1204. +
Miss Bush: (laughs) Yes, a thousand two hundred and four. Well, it's once in a lifetime, you know, I've never been. +
Travel Agent: Mm. +
Miss Bush: The thing is, actually that, um, I'm absolutely terrified of flying. I've never done it before. +
Travel Agent: Oh dear. Uhum +
Miss Bush: And er, um, I'm hoping that I can persuade my two friends, who are also going to the conference, to stop over with me on the way back. +
Travel Agent: Yes, that would be a good idea, yes. +
Miss Bush: Mm, yes. By the way, one of them's in Cairo at the moment. Would it be possible for me to stop over there on my way to Sydney? +
Travel Agent: Yes of course. There are plenty of flights to Cairo and, and then plenty more onwards from Cairo to Sydney. And then you can stay, there, in Cairo, for as long as you like. +
Miss Bush: Oh that's great? Now, the thing is, I think I'd better go and persuade Mr. Adams that, you know, he'd like to stop with me in Cairo ... +
Travel Agent: I see. +
Miss Bush: ... go and discuss it with him and then come back to you in a day or two, if that's all right. +
Travel Agent: Yes. Certainly. Of course, madam. +
Miss Bush: Oh, thank you very much. OK. Goodbye. +
Travel Agent: Thank you. Goodbye.

---

== 3

Gillian felt slightly uneasy as the porter unlocked the gates and waved her through. St Alfred's Hospital was not an ordinary mental institution. It was the most exclusive institution of its type in the country. You had to be not only mentally ill, but also extremely wealthy to be accepted as a patient. She parked her car outside the main entrance of the imposing eighteenth century building. She paused on the steps to look at the superb ornamental gardens and surrounding parkland. An old man in a white panama hat was watering the flowerbed beside the steps. He smiled at her. +
Old man: Good afternoon, miss. A lovely day, isn't it? +
Gillian: Yes, it certainly is. +
Old man: Are you a new patient? +
Gillian: Oh, I'm not a patient. I'm just here to do some research. +
Old man: Will you be staying long? +
Gillian: I really don't know. I wonder if you could direct me to Dr. Carmichael's office? +
Old man: Certainly, miss. Just go through the main door, turn left, walk down to the end of the corridor, and it's the last door on the right. +
Gillian: Thank you very much indeed. +
 +
 Dr. Carmichael was waiting for her. He had been looking forward to meeting his new research assistant. He himself had always been interested in the special problems of long stay patients. Dr. Carmichael was very proud of his hospital and she was impressed by the relaxed and informal atmosphere. She spent the mornings interviewing patients, and the afternoons writing up the results of her research in the gardens. Some of the patients were withdrawn and depressed, some seemed almost normal. Only one or two had to be kept locked up. She found it hard to believe that all of them had been thought too dangerous to live in normal society. She often saw the old man in the panama hat. He spent most of his time working in the gardens, but he always stopped to speak to her. She found out that his name was Maurice Featherstone. He was a gentle and mild-mannered old fellow, with clear, blue, honest eyes, white hair and a pinkish complexion. He always looked pleased with life. She became particularly curious about him, but Dr. Carmichael had never asked her to interview him, and she wondered why. One night, at dinner, she asked about Mr. Featherstone. +
Dr. Carmichael: Ah, yes, Maurice. Nice old chap. He's been here longer than anybody. +
Gillian: What's wrong with him? +
Dr. Carmichael: Nothing. His family put him here thirty-five years ago. They never come to visit him, but the bills are always paid on time. +
Gillian: But what had he done? +
Dr. Carmichael: I'll show you his file. It seems that he burnt down his school when he was seventeen. His family tried to keep the incident quiet. Over the next few years there were a number of mysterious fires in his neighbourhood, but the family did nothing until he tried to set fire to the family mansion. He was in here the next day. Maurice never protested. +
Gillian: And that was thirty-five years ago! +
Dr. Carmichael: I'm afraid so. If I'd had my way, I'd have let him out years ago. +
Gillian: But he can't still be dangerous! +
Dr. Carmichael: No. He's had plenty of opportunities. We even let him smoke. If he'd wanted to start a fire, he could have done it at any time. +
 +
 Gillian was shocked by the story. She became determined to do something about it. She wrote letters to Maurice's family, but never received a reply. He had never been officially certified as insane, and legally, he could leave at any time. Dr. Carmichael was easily persuaded to let her talk to Maurice. +
Gillian: Maurice, have you ever thought about leaving this place? +
Maurice: No, miss. I'm very happy here. This is my home. And anyway, I've got nowhere to go. +
Gillian: But wouldn't you like to go into the village sometimes ... to walk around, to buy your own tobacco? +
Maurice: I've never thought about it, miss. I suppose it would be nice. But I wouldn't want to stay away for long. I've spent twenty years working on this garden. I know every flower and tree. What would happen to them if I weren't here? +
 +
 Gillian realized that it would be unkind to make him leave the hospital. However, she found out that the next Saturday was his birthday. She arranged with the staff to give him a party. They wanted it to be a surprise and Dr. Carmichael agreed to let him go out for the afternoon. There was a flower show in the village. Maurice left at two o'clock. He seemed quite excited. They expected him to return about four o'clock. The cook had made a birthday cake and the staff had decorated the lounge. +
 +
Gillian was standing in the window when she saw him. He was early. He was walking up the drive towards the house, whistling cheerfully. Behind him, above the trees, several thick black columns of smoke were beginning to rise slowly into the clear blue sky.

---

== 4

1. The student, puzzled about a particular point, decides to ask a question. As so often happens when under pressure, he tends to concentrate most of his attention on the subject matter and he pays practically no attention to the language. Consequently, (pause) he fails to employ the correct question form. +

2. However, even though the student does employ an appropriate question form, (pause) difficulties may still arise. +

3. The basic difficulty may, in fact, be one of several different types. It may lie in the student's limited aural perception, in other words, (pause) the student may not have clearly heard what was said. +

4. Learners of English have, for example, said to me such things as "See me here tomorrow" or "Explain this". Fortunately, as I deal with non-native speakers and as I understand their language problems, I interpret this as inadequacy in the language rather than rudeness. Other teachers, however, (pause) may feel angry at receiving such orders. +

5. Today I'm going to consider, very briefly, a problem concerned with the competition for land use, that i... that is (pause) whether crops should be used to produce food or to ... should be used to produce fuel. +

6. A particularly interesting possibility for many developing countries has been the conversion of plant material to alcohol. Th... this is interesting because in many developing countries there is a large agricultural sector, and at the same time (pause) a small industrial sector.

---

== 5 The School Holidays Are Too Long +

Today the children of this country have at last returned to work. After two months' holiday pupils have started a new term. How many adults get such long holidays? Two to four weeks in the summer and public holidays — that's all the working man gets. As for the average woman, she's lucky to get a holiday at all. Children don't need such long holidays. In term-time they start work later and finish earlier than anyone else. +
 +
In the holidays most of them get bored, and some get into trouble. What a waste! If their overworked parents were given more free time instead, everyone would be happier. +
 +
This isn't just a national problem either — it's worldwide. Dates may be different from country to country, but the pattern's the same. Why should children do half as much work and get twice as much holiday as their parents?


---
