
= step 2 - Lesson 36
:toc:
:sectnums:

---



Lesson 36 +

== part


Just before I give a few details about the — er — fun aspect of computers that is, for use at home and for entertainment — I'd like to mention a couple of facts about the outlook for ISDN — that's the integrated services digital network — and it foresees a world-wide telecommunications network which could transmit telex and voice signals and, indeed, full-colour video images and high-speed computer data. Now, can you just imagine having a meeting with your colleagues around the world without even leaving your office? Well, that's what world-wide video teleconferencing can do, and it's on the cards that internal toll-free telephones may be available and also faster computer transmission with a digital network. And how are all these marvellous things achieved? Well, there are satellite relays, and digital packet switching, and laser devices which transmit over fibre-optic cables. But more about that another time. +
 +
And after that slight diversion I'll get back to a totally different aspect of modern technology — home computers, or PCs — that stands for personal computers. First, a bit of background. Some people attribute this growth industry to the recession which led to redundancies and a shorter working week, and this in turn led to more leisure time. So what are people doing with this extra free time that's on their hands? They're indulging in home entertainment, that's what! Hundreds of companies have sprung up to fill this gap, and the sports, DIY and home entertainment industries are achieving phenomenal success. In 1983 in the US, there were four million PCs, and game-playing was the principal use, with educational use a close second; and in third place was the financial function for things like budgeting, balancing cheque books, accounting and forecasting and so on. +
 +
To illustrate this with a few concrete figures, from the States again, in 1983, 52 per cent of the software was for entertainment programs, whereas only 16 percent was educational. Possibly this could be explained by the short life span of computer games, and having teenagers in the home was a decisive factor in the purchase of a personal computer, as households with children in this age-range were 50 per cent more likely to buy them. As far as the interest versus disapproval statistics go, in the 18-19 age-group, 25 per cent expressed interest in PCs and 18 per cent disapproval; and at the other end of the scale, the over-60s showed only 3 per cent interest and a resounding 87 per cent disapproval! +
 +
And this trend towards PCs is likely to continue as users become more knowledgeable and want more expensive machines with all kinds of new things. And there's a wide range in sizes, too, as the portable market expands, and now you can buy a featherweight lap-size model that's less than 2 kg, or something larger at around 12 kg but still portable. Just to digress slightly, I'd like to point out that microtechnology has hit other aspects of the home and leisure industry as well. With more time on our hands it seems we're spending more time keeping fit, and fitness has become a real growth industry, and it seems prone to gadgetry as well! There are all sorts of new things on the market these days. Take, for example, the watches that monitor your pulse rate as you jog or do aerobics, or exercise bicycles with sensors in the handgrips to check your pulse rate and then display it on a screen. And for those of you who remember that famous toy of the early 80s — Rubik's cube, the one with six sides, each composed of nine rotating faces, with 43 quintillion combinations — well, anyway, in a lab in the US they're working on a Cubot — that's a self-contained robot using microprocessors and mechanics — to solve it. But I'm getting off the track again, so back to our home computers with a final warning. +
 +
The technical innovations of the last couple of decades have led to a host of new words in our vocabulary, and one of these is hacker — that's H-A-C-K-E-R — and it simply means an enthusiast who breaks into computers. And, not so long ago in the States, teenagers who were hackers used their home computers to break into supposedly secure government and business computers, for example in banks, labs and research centres. They just tried out different passwords until they found the right one. And as one seventeen-year-old said, 'It was like child's play.' And all that's needed is a home computer and a modem — that's M-O-D-E-M — which is a device that allows computers to transmit data over the phone lines — and, of course, a basic knowledge of how to operate a computer! And this has led to tangled legal and ethical problems — but we won't go into that here. But, as you can see, home computers are indeed a handy thing to have around, not only for entertainment but also for educational value. And no doubt in future ...
 +

---

== part


Dade County, Florida, which includes the city of Miami, is a dangerous place to be these days, that according to a Miami Herald poll released this week. The survey reports that forty-two percent of people interviewed or their family members have been victims of burglary, robbery or assault in the past five years. Almost one half say they need guns to feel safe in Dade County, although most people won't say whether they do own weapons. The Herald conducted the survey in the wake of a widely publicized booby trap killing, in which a store owner killed a would-be burglar. And now the poll suggests a lot more people want to take law into their own hands. Herald reporter Andre Vicluchee has been covering the story. +
 +
"The one part I think that that was a little surprising was the number of people who feel that it is okay to shoot, to kill an intruder that comes into your house. We found sixty-three percent feel that they should have the right to kill an intruder in their house." +
 +
"Whether or not the person is armed or not only if ..." +
 +
"Whether they know or not if the person is armed. It surprised us; we figured there would be something of a hard-line attitude out there. But this was probably above what we expected." +
 +
"Well, it seems, though, that people are perceiving at least in Dade County that crimes are really in bad situation that they are willing to do something about it with violence." +
 +
"Yes. I went back and questioned more at length another fifteen or twenty responded from the poll. And they all seem to feel that, if they find themselves in a situation in which they have to take some action, even if it means killing somebody, they'll do it." +
 +
"I'll take it that Miami Herald poll and perhaps that a lot of people's feelings about crimes stem in part from this case of the booby trap victim, a store owner booby trapped his variety store raider in a black neighborhood. Tell us about that case." +
 +
"The man's name is Prentice Raschid. He is a black business man who has a small store in a black high-crime area of town. He has been burglarized, I think, seven or eight times over the past few weeks, had asked for help from the police and had not gotton any answer to his satisfaction. So he went ahead and set up an electrical booby trap in the store. About a week and a half ago one morning, they found a young man dead in the booby trap who had been electrocuted while trying to carry out some stuff from the store." +
 +
"In what has the public reaction been then?" +
 +
"The public reaction has been an overwhelming support for Mr Raschid. He has been charged with man slaughter, and with setting up an illegal man trap. But our poll found that seventy-nine percent of the population here feel he should not be prosecuted." +
 +
"Has this case, this booby trap case, led to inspire any other similar instances of citizen store-owners fighting back against burglars?" +
 +
"I don't know if it directly inspired them, but it may have been a coincidence. But in the following week there were another five incidents in which citizens, if you will, turn the tables on assailants. In fact these all six incidents left four people dead, four alleged criminals dead and two others wounded in the hospital." +
 +
"Is there anything about Dade County that is making it a particularly blood thirsty place at the moment, as crime's really on the increase in Dade County . . ." +
 +
"I believe the situation is, we have a city here that has grown a lot in the last few years." +
 +
"In what way? What's been the source of the growth?" +
 +
"Immigration for the most part, and lot of people coming in from Cuba, Cuban refugees, a lot of Haitian refugees, and from all over Latin America. What is interesting about the Raschid case in this context is that, as Mr Raschid has pointed out himself, that although he is a black business man operating in a black area, his support has come from all groups, Hispanic, white and black." +
 +
"Andre, do you carry around a gun when you are doing your reporting?" +
 +
"I don't. But I know some reporters that do." +
 +
Andre Vigluche is a reporter for the Miami Herald.

---

== Technology and the Future (III) +

Now I would like to discuss environment, which is very much a function of transportation and communication. But it is also a function of population. As everybody knows, we are now in a population explosion — but probably around the turn of the century this particular explosion will be controlled and the world population may be shrinking again. +
 +
Nevertheless, even with a six billion population there may be more room than is generally imagined today. By the twenty-first century, agriculture will be on the way out. It's a ridiculous process: a whole acre is needed to feed one person, because growing plants are extremely inefficient devices for trapping sunlight. If we could develop a biological system working at a mere five per cent efficiency — today's solar cells can double that — it would require twenty square feet, not one acre, to feed one person. +
 +
Food production is the last major industry to yield to technology. Only now are we doing something about it, probably too little and too late. +
 +
One promising field of research is the production of proteins from petroleum by microbiological conversion, which sounds most unappetizing — but we do use microbes to make wine. This process gives high-quality proteins, some of them better balanced for human consumption than natural vegetable proteins. It would take only three per cent of today's petroleum output to provide the total protein needs of the entire human race. +
 +
With the exception of luxury items — and the Russians, I've heard, have already started to export synthetic caviare — most foods will be factory-made in the next century. This will free vast areas of agricultural land for other purposes — living, parks, recreation, hunting — above all, for wilderness. +
 +
As a source of raw materials, the sea seems inexhaustible. Any element you care to mention is there, in solution or lying on the seabed. We will also be forced to use it for more and more of our water supply, through desalination techniques. +
 +
I'm sorry to leave the sea so hastily, but space is a lot bigger and I must spend more time on that. +
 +
Our current ideas of space and its potentialities are badly distorted by the primitive nature of our techniques. To prove this, here is a statistic that will surprise you. +
 +
The amount of energy needed to lift a man to the Moon is about 1,000 kilowatt-hours and that costs only ten to twenty dollars! The difference of nine zeros between this and the Apollo budget is a measure of our present incompetence. Ultimately, there's no reason why space travel should be, in terms of future incomes, much more expensive than jet flight today. +
 +
Space communities will be established first on the Moon, then on Mars, and later on other worlds. But much closer to the Earth, orbital space stations of many kinds will be in wide use by the year 2000. In May 1967, I was in Dallas to attend the first conference on the commercial uses of space — including tourism. Barron Hilton gave a talk on the Hilton Orbiter Hotel, which he hopes to see in his lifetime. Space tourism is going to be a major industry in the twenty-first century. +
 +
Another tremendously important use of space stations will be for medical research. One paper given at Dallas discussed the engineering problem of a hospital in orbit. +
 +
Which brings a poignant memory to mind. The last letter I ever received from that great scientist professor J B S Haldane was written when he was dying of cancer and in considerable pain from his operations. In it, he said what a boon the weightless environment of a space hospital would be to patients like himself not to mention burn victims, sufferers from heart complaints, and those afflicted with muscle diseases. I am convinced that research in space will open up unguessed regions of medical knowledge and give us a vast range of new therapies. So I get pretty mad when I hear ignorant but well-intentioned people ask, 'Why not spend the space budget on something useful — like cancer research?' When we do find a cancer cure, part of the basic knowledge will have come from space. And ultimately we will find even more important secrets there: perhaps, some day, a cure for death itself ...

---

== Scarborough Fair +

Are you going to Scarborough Fair +
Parsley, sage, rosemary and thyme +
Remember me to one who lives there +
She once was a true love of mine +

Tell her to make me a cambric shirt +
Tell her to make me a cambric shirt +
(On the side of a hill in the deep forest green) +
Parsley, sage, rosemary and thyme +
(Tracing of sparrow on the snow-crested brown) +
Without no seams nor needle work +
(Blankets and bedclothes the child of the mountain) +
Then she'll be a true love of mine +
(Sleeps unaware of the clarion call) +
Tell her to find me an acre of land +
Tell her to find me an acre of land +
(On the side of a hill a sprinkling of leaves) +
Parsley, sage, rosemary and thyme +
(Washes the grave with silvery tears) +
Between the salt water and the sea strands +
(A soldier cleans and polishes a gun) +
Then she'll be a true love of mine +
Tell her to reap it with a sickle of leather +
Tell her to reap it with a sickle of leather +
(War bellows blazing in scarlet battalions) +
Parsley, sage, rosemary and thyme +
(Generals order their soldiers to kill) +
And gather it all in a bunch of heather +
(and to fight for a cause they've long ago forgotten) +
Then she'll be a true love of mine +

(Repeat)


---
