
= step 2 - Lesson 16
:toc:


---




Lesson 16 +

== 1

BBC interviewer: It's probably true to say that women have been affected more than men by recent changes in the way we actually live. Over a hundred years ago people began to question whether men were really so much wiser, stronger, altogether more sensible and simply better than women as the laws of the country made out. In the end women got the vote, and very recently — in 1975 — the Sex Discrimination Act was passed. +
 +
 But it's doubtful whether legislation has changed the way we women actually think. A lot is heard about the dilemma of women's two roles. How can a woman be a wife and mother and have a full-time job as well? +
 +
In this new series we are going to try to find out what people are really thinking and feeling about this problem, and how it affects their personal lives. In the studio with me today is Mrs. Marina Spiden, who recently experienced the problem of having too much to do at home. With Mrs. Spiden are her husband Brian, her mother Mrs. Vera Cresswell and Mr. Tom Penman, their local newsagent. Mrs. Spiden ... tell us what happened will you? +
Mrs. Spiden: Well ... you just said it ... the problem of having too much to do at home. I do an afternoon job so I have to get the housework and shopping ... er ... done in the morning. And one morning you see ... er ... I just couldn't stand it no more. The ... the baby was bawling her head off. Jimmy — that's my little boy ... he's two — had thrown the radio out of the window ... +
Interviewer: Really! +
Mrs. Spiden: Yes really ... The dog ... you know ... had made a ... a mess on the carpet. And there was Brian — my husband — there he was snoring a way on the settee. Didn't lift a finger he didn't ... not a finger to help me. +
Mr. Spiden: Now now love ... Don't get all her up about it again ... I mean that's your side of the story ... +
Interviewer: Of course Mr. Spiden ... We'd like to hear your side later. So ... what did you do about it? +
Mrs. Spiden: Well ... What do you do when you've got something you're fed up with or ... or ... you don't want like ... You put them up for sale don't you? And that's exactly what I did do. Put the whole damn lot of 'em up for sale. +
Interviewer: The family you mean. +
Mrs. Spiden: Yes ... the family ... including the dog. +
Mr. Penman: She came into my shop that very day and 'Tom', she says, 'I've just about had enough of it. I'm sick of slaving for a husband what sleeps all day. So here you are,' she says. And she gives me an advert on a card to put up in the window of the paper shop. +
Interviewer: What did it say? +
Mr. Penman: I've got it here. +
Interviewer: Read it for us will you? +
Mr. Penman: 'For Sale — One house-trained dog, one reasonably trained boy of two years, one baby girl of two weeks and one man that needs training. Any offers considered. Apply within.' +
Interviewer: And were there any offers? +
Mrs Cresswell: It was me what wrote that advert. You see ... I live with Marina and Brian ... +
Mr Spiden: She and her dog ... +
Mr. Penman: Oh yes. Caused quite a stir it did. I should say I had inquiries from ... from about a couple of dozen housewives in all. +
Interviewer: And what offers did they make? +
Mr. Penman: Well one woman offered 25p. She said that's all a man was worth. +
Interviewer: What about you Mr. Spiden? What was your reaction to the advertisement? +
Mr. Spiden: Well ... you can imagine ... My wife told me about it but I thought she was joking. Little did I realize ... I was bloody furious when I saw it there. It wasn't till next morning. We live upstairs of the paper shop and when I come down to go on my milk round ... +
Interviewer: Yes of course ... you're a milkman ... +
Mrs. Spiden: That's right. I often have a dekko at the adverts Tom puts up. And when I saw that one sort of ... staring me in the face ... I nearly blew me top. +
Interviewer: What did you do? +
Mrs. Cresswell: I'll tell you what he did. He came and blamed me for everything. +
Mr. Spiden: Well it was you ... wannit ... that egged her on. It was you that wrote the advert. +
Mr. Penman: It was a big joke really. Just that Brian took it all the wrong way. Know what he did? When he come off his milk round he barges into the shop and he says, 'Take that bloody advert out and put one in for me. Ask some kind taxi-driver or someone to come and take my mother-in-law back to Birmingham.' +
Mr. Spiden: But it's all blown over now ... innit. It's done us a world of good in a way. We're the best of friends again. Even the dog started to ...

---

== 2

Interviewer: I'm going to talk to you now about the suffragette movement. Were you yourself ever a suffragette? +
Mrs. Bruce: No, I did not approve of suffragettes. I did not want to have the vote. I felt the man of the house should be in charge of that section. And the woman, of course, to look after the home and the children. I think that voting was unnecessary, at that time. But I'm not going to say now, that perhaps it has had its advantages. +
Interviewer: How common was your attitude at the time that the suffragettes were being militant? +
Mrs. Bruce: Oh, I was very much against them. I'd be highly insulted if anybody called me a suffragette. I remember walking with my governess down Downing Street just past Number 10 and they chained themselves to the railings. Of course, I had a good laugh but I thought it wasn't going to be me. +
Interviewer: Were they a popular movement in their day? +
Mrs. Bruce: Well, with a certain number of course. And they tried very hard and eventually they got the vote, er through their efforts, so I suppose their efforts were good in quite a lot of ways. Er, I think women in Parliament — there aren't many, but those that've been there have done a lot of good. +
Interviewer: So you think in the long term ... +
Mrs. Bruce: In the long term, no harm was done. As long as their demonstrations were peaceful. +
Interviewer: Do you think it would matter very much if women didn't, hadn't achieved the vote, if they hadn't got the vote at all and still didn't have it? +
Mrs. Bruce: I don't think it would've made a great deal of difference, no, but there are certain things they've done — those that've been Members of Parliament — that have been very useful in helping women in their jobs, in other vocations. I think it's good that it happened. But I wish it happened a little bit more peacefully, perhaps. +
Interviewer: What sort of things can you remember, what other sorts of demonstrations do you remember? +
Mrs. Bruce: Marching, they were marching. But of course those were much more peaceful days, nobody interfered with their marches. There were a few boos here and there and a lot of clapping. Yes. +
Interviewer: Did you, did you actually know any suffragettes yourself? +
Mrs. Bruce: Well, my friends, my close friends, were not suffragettes but I had one or two friends, not very close friends, that were. And we used to have great arguments and I used to say I didn't want the vote, I don't want to vote. +
Interviewer: How did they react to that? +
Mrs. Bruce: They didn't like that. They said I ought to join the movement but I said, no I don't want to vote. +
Interviewer: But, and yet you've done so many exciting things. You've done so many things that in your day, were probably the exclusive preserve of the man +
Mrs. Bruce: Well, yes. But voting didn't make any difference because that's a political thing, voting, I never, I don't care about women entering into politics particularly. Ah, no harm's been done with the few that have entered the House of Commons but, in fact, some have done a great deal of good. But that's quite different to beating men at their own job. Now that's nothing to do with votes. Now, for instance, I always got a great thrill on the race track at Brooklands, if I could beat, well, Sir Henry Seagrave, for instance, in a race, I never did beat him but I did beat Frazer Nash, a famous racing driver in a race, and I was thrilled to death. I thought that was super. +
Interviewer: So you don't mind actually joining men in their world of work and sport but you're happy to leave politics to them. +
Mrs. Bruce: No. I would rather really leave politics to them.

---

== 3

Jan: Changes are very gradual. They're too slow. I mean if you sit under a tree long enough the apple'll fall off and you can eat it but sometimes you've got to stand up and do something. You've got to ... Um, I think the law is there to protect people. Because women were being discriminated against, it was necessary for the law to stop that, um, at least to some extent. But you can't change the way people think. +
Duncan: People's discrimination is based on the fact ... a lot of it, that they don't think women are capable of making decisions or have any intelligence at all. I mean a lot of people believe that ... and if that ... provided ... once that's proved wrong, that removes the valid grounds for the discrimination and you know you ... the belief is then unjustified. You've got to stamp it out. I mean, it's as simple as that. +
Keith: But just in the same way that if I want to become a managing director, I have to look at the company in which I work and prove certain elements of my behaviour or ... or my skills to these people, so must women. +
Jan: Yes, but if they're not given the chance, then how can they? I mean it's very sad that the law has to be there at all. I mean that you have to say to somebody who's employing someone you must give ... you must interview men and women ... it, it seems a great shame ... you have to tell people to do that. It's also a great shame that you have to tell people not to go around murdering other people. I mean, the law's there because people do stupid things. +
Duncan: As I say, the law is ... is not that you have to sort of ... I mean you basically all you have to do is give women the right to apply and the right to be considered in the same way as everybody else and if the law was effective as it should be, there'd be nothing wrong with that. I mean, what's wrong with giving women the chance to apply for a job and giving them the right to be considered on equal terms with men. +
Keith: Women could always ... women could always apply. +
Duncan: That's not true, though. I mean there are employers who just would not consider them. +
David: A woman would not apply if the job was ... if the job advertisement was couched in such terms. +
Keith: I mean ... the leading example ... +
Duncan: I mean the whole point about the ... an advertisement asking for a draughtsman being against the terms of the act, is that it gives the imp ... it's implied that only men will be considered and that's why that would be a legal advertisement if you put at the bottom, um, applications from men and women will be considered ... the same with postmen and all the other jobs. +
David: Interesting point. How important is the language, Jan, do you think? +
Jan: I ... it's symbolic. Um, I personally don't find it particularly important. Er, if you have a meeting and you call the man or the woman who chairs the meeting the chairman, it just doesn't matter I don't think at all.

---

== 4

1. When a teacher or lecturer recommends a student to read a book it's usually for a particular purpose. The book may contain useful information about the topic being studied or it may be invaluable for the ideas or views that it puts forward, and so on. In many cases, the teacher doesn't suggest that the whole book should be read. In fact, he may just refer to a few pages which have a direct bearing on the matter being discussed. +
2. On Many occasions, however, the student does not come to the library to borrow a book, or even to consult a book from the shelves. He may well come to the library because it provides a suitable working environment, which is free of charge, spacious, well-lit and adequately heated. +
3. Learners of English usually find that writing is the most difficult skill they have to master. The majority of native speakers of English have to make an effort to write accurately and effectively even on those subjects which they know very well. The non-native learner, then, is trying to do something that the average native speaker often finds difficult himself. +
4. Students, however, often work out a sentence in their own language and then try to translate it in this way. The result is that very often the reader simply cannot understand what the student has written. The individual words, or odd phrases, may make sense but the sentence as a whole makes nonsense. The student should, therefore, always try to employ sentence patterns he knows are correct English. +
5. Many students seem to think that simplicity is suspect. It is, on the contrary, a quality which is much admired in English. Most readers understand that a difficult subject can only be written up 'simply' if the writer understands it very well. A student should, therefore, organize all his points very carefully before he starts to write. +
6. Non-native speakers of English, like their native counterparts, usually find that the opportunity to participate in group discussions is one of the most valuable aspects in their whole academic programme. But in order to obtain full value from this type of activity the student must be proficient in asking questions. If he isn't, then any attempt to resolve his difficulties may lead to further confusion, if not considerable embarrassment.


---
