
= step 2 - Lesson 34
:toc:
:sectnums:

---



Lesson 34 +

== part


Like most of us, I was pretty skeptical about palmistry, and I still am to some extent, but I have found one or two interesting things which I'd like to mention. There are, in fact, three kinds of hand interpretation which have to be considered. Most people tend to think immediately of chiromancy when they hear about palmistry — the study of the lines on the hand. This suffers from a bad press, really, because of the gypsy fortune-teller associations it has, but I will explain more fully about that later. The second type of hand interpretation is called chirognomy. This is concerned with the shape of the hand, the thickness and form of the palm, length of fingers and thumb, flexibility and so on. Then dermatoglyphics is the name given to the study of the ridges and furrows which make a pattern on our hands. It is this, incidentally, which is the basis for police identification of fingerprints and so on. +
 +
I want to speak briefly today about the first two of these, which is where the bulk of my research was done, and I'll start by saying something about chirognomy. The hand is divided into four areas which I will briefly describe by using this diagram here on the screen. There is, by the way, a connection with astrology. The signs of the Zodiac are, for instance, divided into four distinct groups of three, linked to the four elements, as are modern hand shapes. Now, looking at the diagram, this area here, which includes the little finger, ring finger, half the middle finger and the area below all three, is the inner active area, and this area, area A, relates to close relationships, your love life and your relationship to your partner. Now the second area, B, is called the outer active area around the base of the index finger and the other half of the middle finger, and that relates to our social attitudes, what we might call our relationships to the outside world. Area C is the inner passive area, which lies below the inner active area, and relates to the subconscious part of the mind, and then last of all is the part relating to our energy and our creative potential, area D, which is the outer passive area ... right here, and the area all around the base of the thumb. +
 +
Now I can already hear you asking yourselves why should there be any connection between us — our character, that is — and our hands. Well, the only possible explanation I can give is that there is a large part of the brain concerned with the hand, and there are more nerve endings in the hand than elsewhere in the body, proportional to size, so it just may be — and I stress may be — that the traffic is two-way; that not only does the brain gain information from the hand, but also passes it back again. So, in this way the hand reflects the way the brain operates. +
 +
Now I'd like to say a word about the fingers, and this is where the connection with astrology can also be seen, in the names given to the individual fingers. These are taken from the names of the old Roman gods, just like the planets' names. The index finger is the finger of Jupiter, and in this can be seen the worldly tendencies of a person — ambition, life energy, prospects for success. The finger of Saturn is the name given to the middle finger, which reveals the presence of saturnine qualities, as the name would suggest — brooding, melancholy, that type of thing. The third finger or ring finger is the one with which we move towards inner concerns, and this is the finger of Apollo or the Sun. And finally, the little finger or finger of Mercury reveals a lot about human relationships. Palmists look, too, at the shape of the fingers and their flexibility and general position in relation to the hand. +
 +
Look now, if you will, at my second diagram where I've illustrated five types of fingers and I'll try to explain the characteristics people with these types of fingers are supposed to have. Now, the square shape illustrated here, where the nails and finger ends are squared off, this type reflects a cautious, thoughtful kind of person. Secondly, the spatulate type of finger, which you can see here, shaped like a spoon, narrow before the tip and then getting wider and flatter, these are the fingers of energetic and active people. Then the pointed type of finger with the tapering end; this belongs to the sensitive and artistic kind of person. Finger number three with the smooth joints indicates a quick-thinking and impulsive kind of character, and then finally the rather crooked type of finger with the knotty joints means a deep-thinking, dignified and methodical nature. +
 +
Now I've got another diagram to show you about chirognomy, and that concerns the little bumps we all have on the palm of our hand, which are said to reveal a whole lot about ourselves. Look first, if you will, at the mount of Venus, which is situated at the base of the thumb. This, you may remember, is the area of the hand relating to energy and creativity. Notice, too, the signs used to indicate these bumps: Venus, for example, as in astrology, is shown by the female sign of a circle and a cross underneath it. In the hand where this mount is very flat and under-developed it implies a person with a detached and self-contained nature. Where it is large it implies a person with lots of vitality, and where normal-sized it implies a person who is healthy, warm-hearted and sincere, with plenty of compassion. Moving across to the other side of the hand opposite the mount of Venus but, like it, just above the wrist, is the mount of the Moon. A normal-sized mount of this kind will supposedly be indicative of a sensitive, romantic and imaginative type. If flat, the contrary is indicated, that is, an unimaginative, possibly unstable and even bigoted character. Where it is large, then we can interpret that as being a person who is over-imaginative and introspective. Directly above the mount of the Moon is the upper mount of Mars. It would seem that it's best to have a normal-sized one of these, because if this is the case you are meant to be morally courageous. If it's flat, then you're cowardly, and if it's large you're bad-tempered and cruel. We'll contrast this with the lower mount of Mars on the far side of the hand, above the mount of Venus I spoke about first of all. With this mount, if it's normal size you're meant to be physically brave and not a panicky sort of person; you're violent and argumentative if it's large. and cowardly if it's flat. The other four mounts are at the base of the fingers, the mount of Jupiter lies below the index finger, and next to that the mount of Saturn. Below the ring finger, here, is the mount of Apollo, and then next to that is the mount of Mercury. In the first of these four, the mount of Jupiter, if your mount is flat then that means you are a selfish, lazy individual, and if it's normal that is supposed to indicate enthusiasm, self-confidence and friendliness, whereas if large it would indicate an overbearing and very ambitious nature. The next one right beside it, Saturn, if normal would mean a serious and studious type of personality, and if flat would seem to indicate dullness, and if large a gloomy, reclusive and withdrawn nature, none of which is very promising. The mount of Apollo, when normal, corresponds to a lucky, sunny and pleasant nature, but if flat would indicate a lack of purpose and a philistine nature. Where this mount is large, an extravagant, hedonistic and pleasure-seeking nature would seem to be implied. Finally I'll come to the mount of Mercury, and where this is of normal size it would seem to indicate a lively, persuasive and hard-working character; where flat a gullible and humourless one, and where large a person with a good sense of humour. I'd like now to ...
 +

---

== part

In the Philippines today, Cardinal Haimi Sung, the influential Archbishop of Manila, endorsed President Corazon Aquino's efforts to negotiate with Communist insurgence of the New People's Army. Leaders of the Philippine military, however, and members of her own cabinet have criticized Aquino's attempts at negotiation. The NPA rebels had proposed a one-hundred-day cease-fire to begin in December. +
 +
A group of civilian negotiators and military advisers will meet tomorrow with rebel leaders to discuss the possible truce. Garis Porter, an assistant professor at the American University's School of International Service, says the rebel proposal is a response to President Aquino's earlier offer for a thirty-day cease-fire. +
 +
"I think they're proposing a hundred-day cease-fire primarily because they want to regain initiative, because they do have to have the appearance of being open to a cease-fire, in fact, being at least as open to cease-fire as the government is. The real question, of course, is what terms the cease-fire will be implemented on. And there is where you are going to find a lot of worms which neither side, I think, is really quite clear on exactly what they're yet ready to settle for." +
 +
"They suggested five talking points. And some of those talking points I would think could meet with some pretty stiff opposition from the Philippine military." +
 +
"Well, there's no question that the military is going to oppose, at least a couple of them very strongly." +
 +
"Such as which one?" +
 +
"The first one, the most important one, I think for both sides at this point is the disposition of the Philippine military, the New Armed Forces of the Philippines, NAFP, during a cease-fire. The Communists have, from the beginning, made it clear that they would insist on the pull back of NAFP units from areas which they claim to control. And the military, on the other hand, has also made equally clear that they reject any terms which would not allow them to claim clear control of all of the countryside. +
 +
"Is President Corazon Aquino being naive, as some of her military officials suggest, and thinking that she can negotiate some kind of cease-fire agreement with the Communists that will not ultimately work to their advantage?" +
 +
"I don't think 'naive' is the term to describe Aquino's policy towards the insurgency. There are two points here. One is that she understands that the intentions of the Communist side are at best unclear in terms of the cease-fire. She understands they have their own interests and cease-fire will fit into those interests in a way that may or may not be an interest to the government. The other point, however, I think this is more important to her and perhaps objectively more important in looking at the situation. She understands that the military on her side is simply not capable of controlling the NPA through military means. And by threatening to unleash the military she may actually be making a threat which does not have much credibility. But I think she would almost do anything possible to put off having to go to primarily military strategy for dealing with the insurgency. So in a sense she is playing for time." +
 +
"If they manage to agree on a cease-fire, then what happens after that? What happens when the hundred days is up?" +
 +
"Nobody wants to be the first one to break the cease-fire once it's put into effect. So I think the agreement to a hundred-day cease-fire is, ... has much longer term and much broader implication, if in fact they could come to that agreement, which at this point I think it is still very much up in the air." +
 +
"If it fails, if it fails, does that mean an escalation in the military complex?" +
 +
"Well, I think the pressures on Aquino for letting the military go back its preferred strategy, attempting to go on the offensive, to carry out major military operations, particularly in Central Luzon and in the Southern Tagalog, that is south of Manila, is very strong. And that she will probably make concession to the military which will allow it to resume the offenses to, at least, try that out." +
 +
Garis Porter is assistant professor at the American University's School of International Service in Washington, D.C.

---

== Technology and the Future (I) +

The title of my talk is 'Technology and the Future', and it's only fair to start with a couple of warnings. I have never been interested in the near future — only the more distant one. So if you take my predictions too seriously, you'll go broke; but if your children don't take them seriously enough, they'll go broke. I'll deal first with transportation and communication, because they are inextricably linked together and do more than anything else to shape society. For near-earth applications, both communication and transportation may now be approaching their practical limits and may reach them by the turn of the century. +
 +
For terrestrial transportation, I don't see any real need for much advance beyond the currently planned supersonic transports, operating at almost two thousand miles per hour. +
 +
True, one could build pure rocket vehicles to go from pole to pole in about one hour, but I don't think the public will enjoy fifteen minutes of high acceleration and fifteen minutes of high deceleration, separated by half an hour of complete weightlessness. +
 +
Rather more practical, and of much more immediate importance, will be ground-effect vehicles, or hovercraft. I think we'll have them in the thousand-ton and ten-thousand ton class by the end of the century. +
 +
The political effect of such vehicles may be enormous, as they can go over land and sea and can cross most reasonable obstacles as if they aren't there. You could have the great 'ports' of the world at the centre of the continents, if you wanted to. +
 +
That private hovercraft will ever be popular, I rather doubt. They are noisy and have poor efficiency and poor control. (You can't put on the brakes in a hurry if you're riding on a bubble of air.) However, they are splendid for opening up terrain where conventional vehicles cannot travel — such as shallow rivers, swamps, ice fields, coral reefs at low tide, and similar types of fascinating and now inaccessible wilderness. +
 +
I hope to see the automatic car before I die. Personally, I refuse to drive a car — I won't have anything to do with any kind of transport in which I can't read. I can see a time when it's illegal for a human being to drive a car on a main highway. +
 +
More seriously, we'll certainly have to get rid of the petrol engine, and everybody is now waking up to the urgent necessity of this. Apart from the facts of air pollution, we have much more important uses for petroleum than burning it. +
 +
To make non-petrol cars and other vehicles practical, we need some new power source. Fuel cells are already here, but they are only a marginal improvement. I don't know how we're going to do it, but we want something at least a hundred times lighter and more compact than present batteries.


---
