
= step 2 - Lesson 06
:toc:


---


Lesson 6 +

== 1

Reporter: And now, Mrs. Skinner, can you tell us your story? What happened at your farm when the earthquake passed? +
Mrs. Skinner: Oh, it was terrible. I'll never forget it to my dying day. I hope I never see anything like that again. It was terrible. Well, we always get up, Jack and me, at about quarter to five. He has to milk the cows early, you see, and while he's doing that I make his breakfast. I was in the kitchen when it came. Suddenly the whole house was moving. The coffee pot flew through the window, and I was on my back on the kitchen floor. The noise was terrible. Well, I knew what I had to do. You have to get outside, you know, it's safer there. So I ran through the house and opened the front door. Then I stopped — I couldn't believe it — everything was different, everything had changed, nothing was in the right place any more. You know outside our house there is a path to the gate — there was I should say — well, the path wasn't there any more. In front of the front door was our rose garden, not the path! And next to the rose garden were the eucalyptus trees, and behind them the raspberry patch — just as before, but they had all moved, moved about five metres to the left, to the south that is. On each side of the garden path we had a line of beautiful old cypress trees. Well these had now moved right down to the end of the house, to the left again that is. And the path had completely disappeared. +
Reporter: But that's incredible, Mrs. Skinner. Do you mean that everything in front of your house had moved — what? — five metres to the left, I mean to the south? The raspberry patch, the eucalyptus trees, the rose-garden, the two lines of cypress trees — all had moved? +
Mrs. Skinner: Yes, everything had moved into the place of the other! +
Reporter: But your front path had completely disappeared? +
Mrs. Skinner: Yes, that's right. Oh it was terrible, terrible. +
Reporter: And your husband Jack? Was he all right? +
Mrs. Skinner: Yes — but the cowshed had moved too — it had moved several metres. Jack was all right — I could see him running round after the cows — all the cows had escaped you see. They were running all over the place — it was impossible to catch them. +
Reporter: So Jack, your husband, was all right. +
Mrs. Skinner: Well he was a bit shocked like me, but he was all right. Oh, I forgot to tell you about the granary — that had moved south too. Its normal place was behind the house and now it was near the cowshed. Can you believe it? +
Reporter: Incredible, Mrs. Skinner. And the house itself — what about your house? +
Mrs. Skinner: Well then we saw what had happened. Everything had moved one way — that is, to the south — except the house. The house — can you believe it? — had moved the other way — the house had moved north. So the house went one way and everything else — the garden, the trees, the granary — went the other way. +
Reporter: Incredible, Mrs. Skinner, absolutely incredible.

---

== 2

A funny thing happened to me last Friday. I'd gone to London to do some shopping. I wanted to get some Christmas presents, and I needed to find some books for my course at college (you see, I'm a student). I caught an early train to London, so by early afternoon I'd bought everything that I wanted. Anyway, I'm not very fond of London, all the noise and traffic, and I'd made some arrangements for that evening. So, I took a taxi to Waterloo station. I can't really afford taxis, but I wanted to get the 3:30 train. Unfortunately the taxi got stuck in a traffic jam, and by the time I got to Waterloo, the train had just gone. I had to wait an hour for the next one. I bought an evening newspaper, the 'Standard', and wandered over to the station buffet. At that time of day it's nearly empty, so I bought a coffee and a packet of biscuits ... chocolate biscuits. I am very fond of chocolate biscuits. There were plenty of empty tables and I found one near the window. I sat down and began doing the crossword. I always enjoy doing crossword puzzles. +
 +
After a couple of minutes a man sat down opposite me. There was nothing special about him, except that he was very tall. In fact he looked like a typical city businessman ... you know, dark suit and briefcase. I didn't say anything and I carried on with my crossword. Suddenly he reached across the table, opened my packet of biscuits, took one, dipped it into his coffee and popped it into his mouth. I couldn't believe my eyes! I was too shocked to say anything. Anyway, I didn't want to make a fuss, so I decided to ignore it. I always avoid trouble if I can. I just took a biscuit myself and went back to my crossword. +
 +
When the man took a second biscuit, I didn't look up and I didn't make a sound. I pretended to be very interested in the puzzle. After a couple of minutes, I casually put out my hand, took the last biscuit and glanced at the man. He was staring at me furiously. I nervously put the biscuit in my mouth, and decided to leave. I was ready to get up and go when the man suddenly pushed back his chair, stood up and hurried out of the buffet. I felt very relieved and decided to wait two or three minutes before going myself. I finished my coffee, folded my newspaper and stood up. And there, on the table, where my newspaper had been, was my packet of biscuits.

---

== 3

Inspector: Morning, Sergeant. What have you got for me today? +
Sergeant: We've got that tape from Gentleman Jim, sir. It was sent to us yesterday. They want to know if it's all right to send it to his wife. +
Inspector: And is it? +
Sergeant: I don't know sir. I'm sure there's a message hidden in the tape, but I don't know what it is. It's been examined by half the police force in London, and nothing was found. But there is something very peculiar about that tape. +
Inspector: Well, what is it? +
Sergeant: Well, sir, he talks about happy memories and things. And really, Inspector, I don't think Gentleman Jim really feels like that about anything. I don't think he means any of it. I'm sure there is something else on the tape, and it's hidden in what he says. But I can't find it. +
Inspector: The tape is all right, is it? It wasn't tampered with when Gentleman Jim recorded the message? +
Sergeant: The tape was carefully examined by three different experts, and they didn't find anything. Whatever it is, it's in the words. +
Inspector: Well, I think I'd better listen to this tape, and see if I can find this mystery message. +
Sergeant: Right you are sir, it's waiting for you. +
Jim: Hello my dear wife. I want you to listen very carefully to this recording. Play it over and over again, and enjoy all the beautiful things I want to remind you about. Don't worry about me, just think about the beautiful things, and I'm sure you will be very happy, and you will find something very comforting in my words. Are you ready? I want to remind you of some really happy memories. Do you remember the day when we first met? You were very beautiful. There was a lot of sunshine that day, do you remember? There aren't many girls who are very beautiful, are there? But you were lovely. And our children. They're very beautiful. Two lovely girls, and a handsome boy, although they're all in prison now. I remember when our son was small, he had lovely blue eyes, and very beautiful gold curly hair. Do you remember the toys he used to play with? I remember his teddy bear, and also some very beautiful bricks, which he used to play with on the bedroom floor. Those were happy days. Do you remember, dear wife, the first dance we went to? You wore a blue dress and you looked very beautiful in the moonlight, and we danced until the morning, and then I took you home on my motorbike. Your mother was waiting for us, and she looked very beautiful. The next day I asked you to marry me. I don't think your mother was very pleased. She wanted us to buy the house next to her, do you remember? But we wanted a bigger house, with a very beautiful garden and we found one. I like our house very much. I remember coming home one day in the winter, and looking at our house. It looked very beautiful under the white snow, and I knew that you were waiting in the kitchen with a cup of hot soup, and my dear friend Ginger. Poor Ginger. He has been in prison too. He says that you are very beautiful. The important thing in prison is to have happy memories. And I've got wonderful memories. Do you remember Ginger's cat? It was a very beautiful big black cat. Ginger liked it very much. He bought it fish to eat, and a very beautiful red ribbon, which he tied around its neck. I always liked Ginger's cat. I'm sorry I did not want to see you when you came. I wanted to send you this message instead. When I come home, I will buy you some expensive perfume, or a very beautiful rose. Play this recording many times, and think carefully about my words. Think about what came after all these beautiful things, and walk into the country, sit down beside the river, under a very beautiful tree, and think about me. Your loving Gentleman Jim. +
Inspector: Is that all? +
Sergeant: Yes, that's all. +
Inspector: You're quite right. There is something very peculiar about that message. Look, I've written some questions for you. +
Inspector: Well, I think Gentleman Jim has hidden a message in the tape. +
Sergeant: Yes sir, so do I. He keeps telling his wife to play the message over and over again. +
Inspector: He tells her that she'll find something comforting. What do you think he means by that? +
Sergeant: Well sir, perhaps there is money hidden somewhere, and this message tells his wife where to look? +
Inspector: I wish he'd tell us where to look. Then perhaps we'd find the message. +
Sergeant: I think he has told us, Inspector. +
Inspector: What do you mean? +
Sergeant: Well, did you notice that he keeps saying the same words over again? +
Inspector: Yes, of course. He says everything is very beautiful. +
Sergeant: Mm, that's right. And he tells his wife to think about these beautiful things. That must be a clue. +
Inspector: Well, what does he say? His wife is beautiful, the girls are beautiful, his son is beautiful, the bricks were beautiful ... +
Sergeant: That's a very funny thing to say. +
Inspector: Yes, it is. But wife, girls, son, bricks. It doesn't make any sense. 'Very beautiful bricks,' he said. It's nonsense! +
Sergeant: Just a minute. Do you remember what Gentleman Jim said at the end of the recording? +
Inspector: What was that? +
Sergeant: He said, 'Think about what came after all these beautiful things.' I think that's the answer, Inspector. Play it again, and every time he says 'very beautiful' write down the next word. I think we'll find Gentleman Jim's message. +
Inspector: Right Sergeant. That's very clever of you. Well done!

---

== 4

1. When it has been decided what's to be read — a chapter of a book, for example — then it's helpful to get an overview of the contents before starting to read. This can be done by reading the introduction, usually the opening paragraph, and the conclusion, usually the final paragraph. In addition, (pause) a glance at the headings of sections or subsections will show the order in which the items are introduced. +
2. Finally, the students should ask themselves a specific question connected with the main part of their reading. They should then endeavour to answer it by making appropriate notes as they read. This will help them to focus on the reading as well as (pause) providing a summary which can be reread later. +
3. When the student is writing a dissertation or doing a piece of research then he will need to consult a specialized bibliography. This is a book which lists all the published materials on a particular subject, and in some cases gives a brief summary of each item. Very recent research, however, (pause) may not appear in a bibliography. +
4. There's the type of error which leads to misunderstanding or, even worse, to a total breakdown in communication. The causes of such misunderstandings and breakdowns are numerous, and I'll therefore be able to (pause) do no more than try to cover the most important ones here. +
5. Very often those students who come from a language background which is Indo-European, misuse English words which have a similar form to those in their native language. Spanish speakers, for example, expect the English word "actually" to mean the same as the Spanish word "actualmente". Unfortunately, (pause) it doesn't. +
6. Finally, we come to the third type of error. This is the least damaging of the three, though (pause) it's still important.


---

== 5 Sign Language +

Deaf people, people who can't hear, are still able to communicate quite well with a special language. It's called sign language. The speaker of sign language uses hand gestures in order to communicate. Basic sign language has been used for a long, long time, but sign language wasn't really developed until about 250 years ago. In the middle of the 1700s a Frenchman named Epee developed sign language. Epee was able to speak and hear, but he worked during most of his life as a teacher of deaf people in France. Epee developed a large number of vocabulary words for sign language. Epee taught these words to his deaf students. Epee's system used mostly picture image signs. We call them picture image signs because the signs create a picture. For example, the sign for sleep is to put both hands together, and then to place the hands flat against the right side of your face, and then to lower your head slightly to the right. This action was meant to show the position of sleep. So we call it a picture image sign.

---

== Try to Remember +

Try to Remember the kind of September +
When life was slow and also mellow +
Try to Remember the kind of September +
When grass was green and grain was yellow +
Try to Remember the kind of September +
When you were a tender and callow fellow +
Try to Remember and if you remember +
Then follow +
Follow ... +

Try to remember when life was so tender +
That no one wept except the willow +
Try to remember the kind of September +
When love was an ember about to billow +
Try to remember, and if you remember +
Then follow +
Follow ... +

Deep in December It's nice to remember +
Although you know the snow will follow +
Deep in December It's nice to remember +
The fell of september that makes us mellow +
Deep in December Our hearts should remember +
And follow +
Follow ... +


---
