
= step 2 - Lesson 10
:toc:


---



Lesson 10

== 1.

Here's the news at 11:30. +
 +
Thousands of people have marched through the centre of Corby in Northamptonshire to protest against plans to close the steel works, the town's major employer. The marchers demonstrated outside the local British Steel Corporation's headquarters where union leaders are talking about closure plans with the management. +
 +
Hospital waiting lists in the south west of England have gone up by a quarter in the last five years. While the number of doctors, nurses and other staff have increased, the demand on the service has grown even faster. +
 +
The EEC is to give another ￡31 million to Britain's poorer areas. The aid from the regional development fund includes ￡13.5 million for Northern Ireland and ￡10 million for industrial improvement and road works in the north of England. +
 +
In a report on rabies controls, Kent County Council has said that 17 dogs, 5 cats, 2 rabbits and 2 hamsters have been landed illegally at Channel ports in the first nine months of this year. This was seven more than in the same period last year. +
 +
A derailed coal train at Thirsk in North Yorkshire has disrupted rail services between Newcastle and the south of England.

---

== 2.

It's time for the news at 3:30 here on Radio I. +
 +
A girl aged 16 armed with a shotgun held up a class of children at a secondary school in Surrey this morning. Police said that soon after school began at Blair Hill Secondary School, Newton, the girl, armed with a double-barrelled shotgun belonging to her brother, went into one of the classrooms and threatened a teacher and about thirty pupils. A shot was fired into the ceiling as she was being overpowered by police officers. +
 +
Surgeons at Cambridge have successfully transplanted a pancreas — the organ that produces insulin — in two patients suffering from diabetes. One patient, a 23-year-old electronics worker also had a liver transplant. The other patient, a 55-year-old housewife, had a kidney transplanted at the same time. Both patients are doing well. +
 +
A stately home owner who allowed a pop concert to be staged in his grounds was fined yesterday for letting a rock band play overtime. The Honourable Frederick Sidgwick Johnson admitted allowing the rock group Led Zepplin to play on after midnight during a concert at his home near Stevenage two months ago. Stevenage magistrates fined him ￡125 with ￡25 costs. +
 +
Three people have so far been killed in the storms sweeping across the north of England and southern Scotland. A woman was killed in Carlisle when a chimney on a house collapsed and two men were killed when their car crashed into a fallen tree on a country road near Melrose. More high winds and rain are forecast for tonight.

---

== 3.

Professor Richard Hill is talking about British newspapers. +
 +
It seems to me that many British newspapers aren't really newspapers at all. They contain news, it is true, but much of this news only appears in print because it is guaranteed to shock, surprise or cause a chuckle. +
 +
What should we expect to find in a real newspaper? Interesting political articles? Accurate reports of what has been happening in distant corners of the world? The latest news from the stock exchange? Full coverage of great sporting events? In-depth interviews with leading personalities? +
 +
It is a sad fact that in Britain the real newspapers, the ones that report the facts, sell in thousands, while the popular papers that set out to shock or amuse have a circulation of several million. One's inescapable conclusion is that the vast majority of British readers do not really want a proper newspaper at all. They just want a few pages of entertainment. +
 +
I buy the same newspaper every day. In this paper political matters, both British and foreign, are covered in full. The editorial column may support government policy on one issue and oppose it on another. There is a full page of book reviews and another devoted to the latest happenings in the theatre, the cinema and the world of art. Stock exchange prices are quoted daily. So are the exchange rates of the world's major currencies. The sports correspondents are among the best in the country, while the standard of the readers' letters is absolutely first-class. If an intelligent person were to find a copy of this paper 50 years from now, he or she would still find it entertaining, interesting and instructive. +
 +
So my favourite newspaper is obviously very different from those popular papers that have a circulation of several million. But that does not mean that it is 'better' or that they are 'worse'. We are not comparing like with like. A publisher printing a newspaper with a circulation of several million is running a highly successful commercial operation. The people who buy his product are obviously satisfied customers and in a free society everybody should have the right to buy whatever kind of newspaper he pleases.

---

== 4.

Dave: Dr. Jones, how exactly would you define eccentricity? +
Dr. Jones: Well, we all have our own particular habits which others find irritating or amusing, but an eccentric is someone who behaves in a totally different manner from those in the society in which he lives. +
Dave: When you talk about eccentricity, are you referring mainly to matters of appearance? +
Dr. Jones: Not specifically, no. There are many other ways in which eccentricity is displayed. For instance, some individuals like to leave their mark on this earth with bizarre buildings. Others have the craziest desires which influence their whole way of life. +
Dave: Can you give me an example? +
Dr. Jones: Certainly. One that immediately springs to mind was a Victorian surgeon by the name of Buckland. Being a great animal lover he used to share his house openly with the strangest creatures, including snakes, bears, rats, monkeys and eagles. +
Dave: That must've been quite dangerous at times. +
Dr. Jones: It was, particularly for visitors who weren't used to having 'pets' — for want of a better word — in the house. They used to get bitten and even attacked. And the good doctor was so interested in animals that he couldn't resist the temptation to sample them as food. So guests who came to dinner had to be prepared for a most unusual menu, mice on toast, roast giraffe. Once he even tried to make soup from elephant's trunk. Strangely, though, his visitors seemed to go back for more. +
Dave: They must've had very strong stomachs, that's all I can say. Dr. Jones, what particular kind of eccentric are you most interested in from a psychologist's point of view? +
Dr. Jones: I think they're all fascinating, of course, but on the whole I'd say it's the hermit that I find the most intriguing, the type who cuts himself off from the world. +
Dave: Does one of these stand out in your mind at all? +
Dr. Jones: Yes, I suppose this century has produced one of the most famous ones: the American billionaire, Howard Hughes. +
Dave: But he wasn't a recluse all his life, was he? +
Dr. Jones: That's correct. In fact, he was just the opposite in his younger days. He was a rich young man who loved the Hollywood society of his day. But he began to disappear for long periods when he grew tired of high living. Finally, nobody was allowed to touch his food and he would wrap his hand in a tissue before picking anything up. He didn't even allow a barber to go near him too often and his hair and beard grew down to his waist. +
Dave: Did he live completely alone? +
Dr. Jones: No, that was the strangest thing. He always stayed in luxury hotels with a group of servants to take care of him. He used to spend his days locked up in a penthouse suite watching adventure films over and over again and often eating nothing but ice cream and chocolate bars. +
Dave: It sounds a very sad story. +
Dr. Jones: It does. But, as you said earlier, life wouldn't be the same without characters like him, would it?

---

== 5.

1. In the United States we are using more and more oil every day, and the future supply is very limited. +
2. It is estimated that at the current rate of use, oil may not be a major source of energy after only 25 more years. +
3. We have a lot of coal under the ground, but there are many problems with mining it, transporting it, and developing a way to burn it without polluting the air. +
4. Production of new nuclear power plants has slowed down because of public concern over the safety of nuclear energy. +
5. The government once thought that we would be getting 20 percent of our electricity from nuclear energy by the 1970's, but nuclear energy still produced only about 12 percent of our power as of 1979. +
6. There is no need to purchase fuel to operate a solar heating system because sunshine is free to everyone. +
7. Because solar systems depend on sunshine, they can't always provide 100% of your heat. +
8. Solar heating can be used in most areas of the United States, but it is most practical in areas where there is a lot of winter sunshine, where heat is necessary, and where fuel is expensive. +
9. A hot-liquid system operates in basically the same way except the hot-liquid system contains water instead of air; and the storage unit is a large hot water tank instead of a container of hot rocks. +
10. Then energy from the sun may provide the answer to our need for a new, cheap, clean source of energy.

---

== 6. Voice Analysis +

If we want to measure voice features very accurately, we can use a voice analyser. A voice analyser can show four characteristics of a speaker's voice. No two speakers' voices are alike. To get a voice sample, you have to speak into the voice analyser. The voice analyser is connected to a computer. From just a few sentences of normal speech, the computer can show four types of information about your voice. It will show nasalization, loudness, frequency and length of articulation. The first element, nasalization, refers to how much air normally goes through your nose when you talk. The second feature of voice difference is loudness. Loudness is measured in decibels. The number of decibels in speaking is determined by the force of air that comes from the lungs. The third feature of voice variation is frequency. By frequency we mean the highness or lowness of sounds. The frequency of sound waves is measured in cycles per second. Each sound of a language will produce a different frequency. The final point of voice analysis concerns the length of articulation for each sound. This time length is measured in small fractions of a second. From all four of these voice features — length of articulation, frequency, loudness and nasalization — the voice analyser can give an exact picture of a person's voice.



---
