
= step 2 - Lesson 29
:toc:
:sectnums:

---



Lesson 29 +

== part



Linda: Oh, yes, I remember. We were conducting a survey into the, the needs of disabled people in the borough (Yes) in which I work in London. And we got a request from an old man to go along and, and see him in connection with this survey. Well, some of the people that I'd seen on the survey before were really quite poor and lived in very bad housing conditions. (Yes) They were also ... tended to be elderly and to really have some quite bad disabilities, so I was quite prepared for, for anything I thought that I might meet. Anyway, I went along to, to this house and it was not at all what I'd expected. It was a, a large house and really had an air of fa, faded gentility about it. It was in a part of the borough which had (Really?) once been quite fashionable. Er, I knocked at the door and the old man, Mr. Sinclair, came to, to let me in and showed me into a back room, which he lived in. The rest of the house, I think, must have been shut up and he was just living in one or two rooms. (How extraordinary!) Anyway, we started the interview which I had to, to conduct with him and he was very, very willing to talk but he never stopped grumbling. He grumbled about ... young people, about the rising cost of living, about the government, about how the area had gone down, and so on and so forth. He didn't seem to have a good word to say for anybody at all. (S ... ) +
Janet: Got a real chip on his shoulder? +
Linda: Well, he was. He was a really grumpy old man and not very likeable with it. But he was ... rather frail and in his eighties and ... I just accepted that perhaps, you know, he'd had a hard life in, in some way an, and hadn't really resolved it. Anyway, I left the, er, the house and went back to the office, wrote up the interview and didn't think any more about it. And then about a week later, I got a phone call from him saying that he thought he'd left out some important things about himself (Really?) that I should know, and would I go and see him again. So I explained that it was a survey that we were doing and that it wasn't really very usual to go back and see somebody a second time, but if he felt it was really important then, of course, I would go. (Yeah) So I went along and exactly the same thing happened as had happened before. He showed me into the back room and he started grumbling again and this went on for about half an hour and I began to wonder why on earth he'd asked me to go back a second time. +
Janet: He didn't tell you anything new about himself? +
Linda: Well, he ... after about half an hour he started. He said, 'I, I expect you wonder why I've asked you to come back,' (Quite) and I said, 'Well, as a matter of fact, yes I do.' So he said, 'Well, I think I should tell you a bit about myself and perhaps explain why I, I seem to have a chip on my shoulder,' which took me aback, back a bit, you know. Anyway, apparently, he had come from a, a family which was ... really quite well-to-do but not spectacularly rich and his father had a, a small grocery business and had supported his mother and, and his two sisters. Well, his mother and father both died quite early on in his life and he took over the business (Yes) and it fell to him, of course, to support his two sisters. (Yes) Well, gradually the, the business began to, to flourish. He opened up new lines in the shops, he bought in some foreign foods and he (He ... ) acquired new premises. +
Janet: He really built the whole thing up. +
Linda: Well yes. He didn't become a multimillionaire or anything like that, but he was certainly very comfortably off. Anyway, he ... one of his sisters got married and the other sister emigrated to Australia but he himself never, never married. +
Janet: He just stayed on in the house by himself? +
Linda: He stayed on in, in this house which had been the family house for a number of years. +
Janet: Completely alone? +
Linda: Completely alone, yes. And he ... really cut himself off from his friends, or friends of the family, because he was giving all day, every day, to the growth of his business. So he kept going for a number of years but eventually, of course, he began to, to grow older and with age came arthritis (Oh dear) and ... gradually the, the condition worsened and he became more and more in pain, more and more frail but he still battled on, I think, for a number of years (Yes) but eventually he was forced to give up. And it left him completely alone. He was still, of course, well off, (Yes) but that wasn't in itself enough, and while he was telling me this he was, he was so upset because he'd remembered when telling me the excitement and the thrill he'd felt (Yes) when he was completing these transactions, of what it m, meant to be both powerful, respected and really somebody of note (Yes) in the area, whereas now he was old, (H...) frail, in pain. +
Janet: He'd lost everything. +
Linda: Yes, he had. His, his neighbours were very good to him, but it wasn't that that he wanted. (No) And I felt so ... helpless because it wasn't that he needed more money, it wasn't that he really needed visitors — he didn't particularly want visitor. (No) What he wanted was to be, to be young again and to be in a position of, of building something up and seeing the results (Yes) from it. +
Janet: Oh, what a sad story!
 +

---

== part

Los Angeles police yesterday added a new name to the list of victims of what they believe is a new serial killer. Like the first four victims Joseph Griffin was a homeless man shot on the head while sleeping alone. NPR's Salas Wason reports from Los Angeles. +
 +

Early this month the police department sent notices to every homeless shelter about the transient killer. Staff member Marcotte Tears reads from the Xerox post near the check-in window at the Union Rescue Mission down town. +
 +
 "Four men have been shot in the head in the last three weeks. The men were all transients and sleeping alone at the time of the killings. Please tell everyone in this chapel and those along the streets to come indoors at night to any of the missions or shelters. When they are full please tell the men to group together, not to be alone at night, but huddle for safety. The lives of the men may depend upon their following these instructions." +
 +

Since that notice was distributed, police have searched their records and added five more victims to the list. Except for the victim added yesterday they are not transients, but they were all shot while out on the streets in the early morning hours. Commander William Booth, a spokesman for the police department, won't confirm it, but reportedly all the men were shot with a small caliber gun. So far Booth said the task force working on the case doesn't have many clues and only a little bit of information about the murderer. +
 +

"Frankly not nearly enough. We have a brief description: a male black, who is tall, slim, a hundred fifty to a hundred and seventy pounds, twenty-five to thirty years old. With a medium to large Afro haircut." +


The first victim was shot on September 4th, the most recent October 7th. The crime took place in several Los Angeles neighborhoods. All five homeless men killed were sleeping outside downtown. Not in the skid road area, but nearby. Although the city's transients have been urged to sleep in shelters, there are thousands more men than beds are available. And not all the homeless choose to stay in the shelters. Still most of the men at the Union Rescue Mission know about the transient killer and admit to some concern. +
 +

Los Angeles police are still looking for another serial murderer. This outside slayer is suspected of killing seventeen women, mostly prostitutes during the past three years. I'm Salas Wason in Los Angeles.


---

== How to Present a Seminar Paper +


In this talk, I am going to give some advice on how to present a seminar paper. +

At one time, most university teaching took the form of giving formal lectures. Nowadays, many university teachers try to involve their students more actively in the learning process. One of the ways in which this is done is by conducting seminars. In a seminar, what usually happens is this. One student is chosen to give his ideas on a certain topic. These ideas are then discussed by the other students (the participants) in the seminar. +

What I'd like to discuss with you today is the techniques of presenting a paper at a seminar. As you know, there are two main stages involved in this. One is the preparation stage which involves researching and writing up a topic. The other stage is the presentation stage when you actually present the paper to your audience. It is this second stage that I am concerned with now. Let us therefore imagine that you have been asked to lead off a seminar discussion and that you have done all the necessary preparation. In other words you have done your research and you have written it up. How are you going to present it? +


There are two ways in which this can be done. +

The first method is to circulate copies of the paper in advance to all the participants. This gives them time to read it before the seminar, so that they can come already prepared with their own ideas about what you have written. The second method is where there is no time for previous circulation, or there is some other reason why the paper cannot be circulated. In that case, of course, the paper will have to read aloud to the group, who will probably make their own notes on it while they are listening. +

In this talk, I am going to concentrate on the first method, where the paper is circulated in advance, as this is the most efficient way of conducting a seminar; but most of what I am going to say also applies to the second method; and indeed may be useful to remember any time you have to speak in public. +
 +

You will probably be expected to introduce your paper even if it has been circulated beforehand. There are two good reasons for this. One is that the participants may have read the paper but forgotten some of the main points. The second reason is that some of the participants may not in fact have had time to read your paper, although they may have glanced through it quickly. They will therefore not be in a position to comment on it, unless they get some idea of what it is all about. +

When you are introducing your paper, what you must not do is simply read the whole paper aloud. This is because: +
 +

Firstly, if the paper is a fairly long one, there may not be enough time for discussion. From your point of view, the discussion is the most important thing. It is very helpful for you if other people criticize your work: in that way you can improve it. +
 +

Secondly, a lot of information can be understood when one is reading. It is not so easy to pick up detailed information when one is listening. In other words, there may be lack of comprehension or understanding. +
 +

Thirdly, it can be very boring listening to something being read aloud. Anyway some of your audience may have read your paper carefully and will not thank you for having to go through all of it again. +
 +

Therefore, what you must do is follow the following nine points: +


 1. Decide on a time limit for your talk. Tell your audience what it is. Stick to your time limit. This is very important. +


 2. Write out your spoken presentation in the way that you intend to say it. This means that you must do some of the work of writing the paper again, in a sense. You may think that this is a waste of time, but it isn't. If a speaker tries to make a summary of his paper while he is standing in front of his audience, the results are usually disastrous. +


 3. Concentrate only on the main points. Ignore details. Hammer home the essence of your argument. If necessary, find ways of making your basic points so that your audience will be clear about what they are.

 4. Try to make your spoken presentation lively and interesting. This doesn't necessarily mean telling jokes and anecdotes. But if you can think of interesting or amusing examples to illustrate your argument, use them. +

 5. If you are not used to speaking in public, write out everything you have to say, including examples, etc. Rehearse what you are going to say until you are word perfect. +
 +

 6. When you know exactly what you are going to say, reduce it to outline notes. Rehearse your talk again, this time from the outline notes. Make sure you can find your way easily from the outline notes to the full notes, in case you forget something. +

 7. At the seminar, speak from the outline notes. But bring both sets of notes and your original paper to the meeting. Knowing that you have a full set of notes available will be good for your self-confidence. +

 8. Look at your audience while your are speaking. The technique to use is this. First read the appropriate parts of your notes silently (if you are using outline notes, this won't take you long). Then look up at your audience and say what you have to say. Never speak while you are still reading. While you are looking at your audience, try to judge what they are thinking. Are they following you? You will never make contact with your audience if your eyes are fixed on the paper in front of you. +

 9. Make a strong ending. One good way of doing this is to repeat your main points briefly and invite questions or comments. +

Perhaps I can sum up by saying this. Remember that listening is very different from reading. Something that is going to be listened to has therefore got to be prepared in a different way from something that is intended to be read.


---
