
= 2-18 移民, 难民
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


== 19-20世纪前几十年 的移民动向

Over the course of the nineteenth century and the first decades of the twentieth century, approximately sixty million Europeans sought better economic opportunities on other continents. Most came from relatively nonindustrialized or agricultural regions, such as southern Italy and Sicily.


Other common landing places for European immigrants were Australia, New Zealand, and South Africa.


'''

==  去往美国

=== 19世纪上半叶

Approximately twenty-eight million Europeans and Canadians immigrated to the United States during this time, the majority between 1890 and 1914. Most were peasant farmers from southern and eastern Europe.

Many also continued to arrive from Germany and Ireland, the countries that had been responsible for the greatest influx of immigrants in the first half of the nineteenth century. Along with those fleeing poverty came victims of religious persecution, especially Jewish people of the Russian empire. Political dissidents and craftspeople displaced by industrialization made up the rest.



Most people have heard of Ellis Island, the immigration station in the New York City harbor that welcomed millions of European immigrants to the United States. Less well known was Angel Island in San Francisco Bay that served as the station through which most Asian immigrants were processed while they awaited permission to enter the United States or were returned to their home countries. Today, it is a national historic landmark.


'''

===  排华法案 (1882)

Asian immigrants found themselves more unwelcome than European immigrants were. In 1882, the United States passed the Chinese Exclusion Act, which prevented all Chinese laborers from immigrating to the country.  +
The Johnson-Reed Act banned all immigration from Asia, with the exception of people coming from U.S. territories in the Pacific.


'''

=== 执行移民法, 限制人数 ( 约翰逊-里德法令, 1924)

By the end of the nineteenth century, many native-born Protestants of northern European ancestry in the United States began to call for changes in immigration laws.

These calls were met in 1924 with the passage of the Johnson-Reed Act, which set a quota on the total number of immigrants allowed to enter the United States from outside the Western Hemisphere. In addition, the act limited the number of immigrants of each nationality to 2 percent of the number already living in the United States in 1890. Thus, a person might be turned away if the permitted number of immigrants of that particular nationality had already been admitted, even if the total limit had not been reached.

Before 1890, most immigrants had come from northern and western Europe and relatively few from southern or eastern Europe. Thus, the 2 percent quota allowed far more English, Irish, and German people to enter than Italian, Polish, or Russian Jewish people.

Immigration from Asia, with the exception of the U.S. territory of the Philippines, was banned.






'''

==  去往加大拿

Canada was the destination of approximately 5.1 million people between the 1850s and the 1920s.


'''

===  对中国移民征税, 以限制中国移民人数 (1885)

Although Canada did not ban Asian immigration, in 1885 it placed a tax of $50 on all Chinese people entering the country to work. Students, scientists, merchants, and government officials were exempt, but in subsequent years, the tax was raised.


'''

== 去往澳洲

=== 移民限制法令 (1901)

The White Australia Policy culminated in the passage of the Immigration Restriction Act in 1901, excluding anyone who could not pass a dictation test administered in a European language.


'''

==  去往拉美

After the United States, it was Argentina, Brazil, Chile, and Uruguay that received the largest numbers. Some 4.5 million emigrants went to Argentina, where at one point they made up 30 percent of the population. Latin America attracted many Italians and Germans as well as Spanish and Portuguese settlers.


In Latin America, the situation was much different. Argentina and Uruguay, for instance, had never had large populations because they lacked their neighbors’ mineral wealth and climates conducive to the growing of sugar and coffee. The arrival of European immigrants there was thus a welcome boost. Brazil and Venezuela deliberately sought out European immigrants to make their predominantly African, Native American, and biracial population more White.



'''

==  二战结束时的移民情况

There remained the huge task of repatriating all those displaced by the war. Millions of people had been shuttled around Europe by the Germans as they drew forced labor to Germany and dispatched Jewish people and others to concentration/death camps.

The Soviets demanded the return of all their citizens. The Allies agreed to the controversial “Operation Keelhaul,” whereby people who had cooperated with the Germans against the Soviets, including Cossacks, Ukrainians, and Russians, were forcibly repatriated to the Soviet Union with the probability of a harsh and possibly fatal reception.

Millions of others were also forcibly moved back to their “home” nations at the end of the war, such as Germans living in areas now belonging to Poland who were forced to leave for Germany. The hope was that this would help avoid ethnic tensions that might lead to another conflict.

At the same time, 250,000 Jewish survivors of the Holocaust languished in camps for displaced persons because their home countries refused to take them back. About eighty thousand were eventually able to relocate to the United States, and more than 100,000 settled in the British Mandate of Palestine.





'''

== 冷战后移民美国的情况

Millions of immigrants from Mexico and other parts of Latin America have made their way into the United States over the last few decades. They serve an important role in the U.S. economy, often doing work domestic workers are unwilling to do. Many entered the country illegally and live and work in the shadows to avoid deportation. This makes them vulnerable to abuse.


'''

==  难民逃亡西方发达国家, 引发问题

Instability in Iraq and Syria led to a flood of refugees making their way across the Mediterranean to Europe in 2015.

Many others sought to escape failing states and poverty in numerous parts of the Middle East, Africa, and Asia. These refugees and economic migrants felt they would find a better and safer life in the developed countries of the West, particularly Germany, Sweden, Britain, France, and the United States.



Upon arrival, these groups met various responses. Others said they were fleeing circumstances outside the host country’s responsibility and would bring too many cultural and religious changes. For example, many Europeans feared that refugees from Islamic countries would reject the values of the largely secular European nations in which they settled. Many others believe that Muslims embrace political extremism or support acts of terrorism.



Responding to the developing migrant crisis, German chancellor Angela Merkel declared, “We can do this!” and promised Germany would welcome 800,000 refugees in 2015.

Others throughout Europe felt it was short-sighted. They noted that since Germany was in the European Union, bringing refugees there effectively amounted to bringing them into any other country in the EU.


'''