
= 3-03 古罗马 & 东罗马帝国
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


== 古罗马

=== 经济

Despite these attempts at collecting taxes, by the third century CE the empire had entered a period of financial crisis. Constant wars meant a never-ending need to sustain large armies. As less new land was acquired, troop payments came more often from the central treasury than from newly conquered territory.


'''

===  古罗马的建立

According to Roman tradition, the city was founded in 753 BCE by the twin brothers Romulus and Remus, sons of Mars, the god of war.


The Roman city-state free itself from Etruscan domination and establish an independent republic around 500 BCE.


The early Romans did not plan on building an immense empire. They were surrounded by hostile city-states and tribes, and in the process of defeating them they made new enemies even as they expanded their network of allies. Thus they were constantly sending armies farther afield to crush these threats until Rome emerged in the second century BCE as the most powerful state in all the lands bordering the Mediterranean Sea.


'''

===  打败迦太基 (布匿战争)

After conquering most of the Italian peninsula, Rome came to challenge the other major power in the region, Carthage. A series of wars ensued, called the Punic Wars, in which Rome and Carthage vied for dominance.


'''

====  第一次布匿战争

the First Punic War (264–241 BCE) ended with Rome annexing Sicily.


'''

==== 第二次布匿战争

Carthage desired revenge. In the Second Punic War (218–201 BCE), As the Carthaginian general Hannibal’s army was rampaging through Italy, Rome sent an army across the Mediterranean to Africa to attack Carthage, which summoned Hannibal back to defend his homeland.


Hannibal’s Invasion of Rome. This map shows the route Hannibal followed from Hispania over the Alps to attack Italy before finally returning to defend Carthage in the Second Punic War.



Carthage sued for peace and was stripped of all its overseas territory. Rome thus acquired Carthage’s lands in Hispania.


'''

====  消灭马其顿王国

During the war, King Philip V of Macedon made an alliance with Carthage. After Rome’s victory against Carthage, Rome declared war against this new enemy. Philip suffered a defeat and lacked the resources to continue. Consequently, he agreed to become an ally of Rome. Rome also liberated all regions in Greece formerly under Macedonian control.

Rome discovered in the second century BCE that there was no end to the threats from hostile powers. Perseus, the son of Philip V, renounced the alliance with Rome. Roman armies invaded Macedon, which soon afterward became a Roman province.



'''

====  第三次布匿战争 (前149年－前146年)

Roman armies also destroyed the city of Carthage in the Third Punic War.


'''

===  the First Triumvirate 前三头执政同盟 (Julius Caesar 凯撒)

Three men in particular eventually assumed enormous dominance. One was Pompey Magnus. Another politician and military commander of this era was Crassus. The third influential figure was Julius Caesar.


The optimates in the Senate distrusted all these men and cooperated to block their influence in Roman politics. In response, in 60 BCE the three decided to join forces to advance their interests through a political alliance known to history as the First Triumvirate (“rule by three men”). But they were all very ambitious and each greatly distrusted the others.


'''

====  Julius Caesar 凯撒

After serving as consul in 60 BCE, Julius Caesar took command of the Roman army in Gaul (modern France). Over the next ten years, his armies conquered all Gaul and launched attacks against German tribes across the Rhine, and on the island of Britain across the English Channel.


'''

====  Crassus 克拉苏

The Roman people were awed by Caesar’s military success, and Pompey and Crassus grew jealous of his popularity. In 54 BCE, Crassus invaded the Parthian Kingdom in central Asia, hoping for similar military and political triumphs. The invasion was a disaster, however, and Crassus was captured by the Parthians and executed.


'''

====  Pompey Magnus 庞培

After Crassus’s death, Pompey decided to break with Caesar and support his old enemies the optimates. In 49 BCE, the optimates and Pompey controlled the Senate and demanded that Caesar disband his army in Gaul and return to Rome to stand trial on various charges. Instead, Caesar convinced his client army to march on Rome. In January of that year he famously led his troops across the Rubicon River, the traditional boundary between Italy and Gaul. Since Caesar knew this move would trigger war, as it was illegal to bring a private army into Rome proper, the phrase “crossing the Rubicon” continues to mean "passing the point of no return."

In 48 BCE, Caesar defeated Pompey.



'''

====  凯撒成为终身独裁者

To prosecute the war against Pompey, Caesar had himself appointed dictator in 48 BCE. Despite the tradition that dictatorship was to be temporary, Caesar’s position was indefinite. In 46 BCE, he was appointed dictator for a term of ten years, and in 44 BCE his dictatorship was made permanent, or for life.


These appointments and other efforts to accumulate power unnerved many Romans, who had a deep and abiding distrust of autocratic rulers. Caesar had hoped to win over his former enemies by inviting them to serve again in the Senate and appointing them to positions in his government. However, these former optimates viewed him as a tyrant, and in 44 BCE two of them, Brutus and Cassius, led a conspiracy that resulted in his assassination.



The Roman Empire through 44 BCE. Some of the areas marked in purple, like Gaul and Syria, were added to the Roman Empire by the victories of Julius Caesar and Pompey, respectively.



'''

===  the Second Triumvirate 后三头同盟  (Octavian 屋大维)

Octavian was only eighteen when Caesar was killed, but as Caesar’s adopted son and heir he enjoyed the loyalty and political support of Caesar’s military veterans. Together these three shared the power of dictator in Rome in a political arrangement known as the Second Triumvirate. Unlike the First Triumvirate, which was effectively a conspiracy, the Second Triumvirate was formally recognized by the Senate.


After crushing the remnants of the optimates, the three men divided the Roman Empire between them. Soon they quarreled, however, and civil war erupted once again.


To avoid the fate of his adopted father, he successfully maintained a façade that the Roman Republic was alive and well. Octavian, traditionally referred to as Augustus after 27 BCE, had assumed enormous power. Despite his claim that he had restored the Republic, he had in fact inaugurated the Empire.


Augustus was keenly aware that the peace and prosperity he had created was largely built upon his image and power, and he feared what might happen when he died. As a result, the last few decades of his life were spent arranging for a political successor. This was a complicated matter since there was neither an official position of emperor nor a republican tradition of hereditary rule.

Augustus had no son of his own, and his attempts to groom others to take control were repeatedly frustrated when his proposed successors died before him. Before his own death in 14 CE, Augustus arranged for his stepson Tiberius to receive from the Senate the power of a proconsul and a tribune. While not his first choice, Tiberius was an accomplished military leader with senatorial support.







Problems with imperial inheritance remained. There were always risks that a hereditary ruler might prove incompetent.


'''

=== 动荡和变革的三世纪

The third century was a period of upheaval and change for the Roman government, often referred to as the Crisis of the Third Century. From 235 to 284, a span of only forty-nine years, the empire was ruled by upward of twenty-six different claimants to the imperial throne. New emperors were often declared and supported by Roman soldiers. As a result, civil wars—as well as wars on the eastern frontier—were nearly constant.


'''

===  日耳曼人入侵, 罗马帝国西部沦陷, 罗马帝国重心向东移动 (Constantinople 君士坦丁堡)

Germanic Kingdoms.

The increasing influx of Germanic peoples into the western empire brought about a fracturing of Roman power as a series of independent kingdoms took control of the Italian peninsula.



Many of the migrations of Germanic peoples during this period were a result of the influx of the Huns. These migrations eventually pushed Germanic groups and others into Roman territory, with the Huns led by their ruler, Attila.

Although the Huns reached as far as Gaul, their empire ultimately collapsed following Attila’s death in 454.



'''

===  法兰克人

Roman troops were likewise pushed out of Britain for the final time by the invasion of Germanic peoples who included the Angles and the Saxons. Coming from modernday southern Denmark and northern Germany, they occupied southern Britain in the late fifth century. Originally two distinct groups, they are more commonly known as Anglo-Saxons, a name applied to them in the eighth century to distinguish them from similarly named Germanic groups on the European continent.


'''

===  盎格鲁人和撒克逊人

Roman troops were likewise pushed out of Britain for the final time by the invasion of Germanic peoples who included the Angles and the Saxons. Coming from modernday southern Denmark and northern Germany, they occupied southern Britain in the late fifth century. Originally two distinct groups, they are more commonly known as Anglo-Saxons, a name applied to them in the eighth century to distinguish them from similarly named Germanic groups on the European continent.



The eastern half of the Roman Empire did not collapse until the fifteenth century. Traditionally, though, the end of the empire is fixed at 476, when a German general named Odoacer deposed the emperor Romulus Augustulus and established himself not as a Roman emperor but as King of Italy. Even that date may be arbitrary, but by the late fifth century, traditional Roman authority had ceased to be the basis of political power in much of western Europe.


Historians of Rome have debated what the fall of Rome actually means. As soon as time or accident had removed the artificial supports, the stupendous fabric yielded to the pressure of its own weight. Instead of inquiring why the Roman empire was destroyed, we should rather be surprised that it had subsisted so long.


'''

==  东罗马帝国 (395-1453年)

=== 古代晚期

The Roman Empire Moves East.



Constantine had effectively ushered in a new era of Christian governance. The Roman Empire’s eastward shift epitomized the major cultural changes occurring during this period. Because of these shifts, Late Antiquity has been characterized as a transitional period between the ancient and medieval worlds that occurred from roughly 150 to 750 CE. People from this period thought of themselves as being different from what was seen in the ancient world.


The period of Late Antiquity witnessed the height of two great competing empires. The Roman Empire morphed into the Byzantine Empire. Meanwhile, in the East, the Sasanian Empire emerged and vied with the Byzantines for supremacy.


'''

===  7-8世纪 (史料严重缺乏)

This period is known as the “Byzantine Dark Age” because of the severe lack of historical writing that survived in the seventh and eighth centuries.


'''

===  被 (突厥)奥斯曼土耳其帝国 灭亡 (1453 年)

The fall of Constantinople was lamented in Europe as signaling that no significant force remained to counter the Muslim advance westward. For many historians, it also marks the end of the European Middle Ages.


'''