
= 6-03 改变人类生活质量的重要发明
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


Water power had earlier replaced animal power, and steam engines fueled by burning coal had driven the machinery of the late eighteenth and early nineteenth centuries.


'''

==  内燃机 (1860)

The automobile’s arrival depended on another crucial invention—the internal combustion engine. Internal combustion engines powered automobiles as well as machinery in small workshops, offering an alternative where steam engines, which were large, could not easily fit.



'''

== 巴氏灭菌 (1860年代)

Pasteur’s discoveries also led to the pasteurization of milk beginning in the 1860s, making it safer to drink by heating it to destroy pathogens.


'''

== 奎宁 (能防止疟疾) (1870年代)

Malaria was also a significant problem in Britain’s colony of India. It was exacerbated by schemes to dig irrigation canals and clear land for railroads, creating more areas for water to collect in breeding grounds for the mosquitoes that carried the disease.

Quinine, which comes from the bark of the cinchona tree, had been used to treat malaria for years, and in the 1840s the British discovered that taking it before exposure could prevent people from ever contracting the disease. Cinchona trees grew only in the Andes, however, and there were not enough to meet the European demand. Attempts to plant cinchona trees elsewhere often failed, but by the 1870s the Dutch were successfully growing them in their colony of Indonesia and producing additional quinine.



'''

== 电灯 (1879)

Electricity ran machines in factories and lit streets, workplaces, and homes following the invention of the incandescent light bulb, by Joseph Swan in Britain in 1878 and Thomas Edison in the United States in 1879.


'''
