
= Lesson 35
:toc:


---


== Section 1

==== A. Tastes in Common. +

Woman A: I can't stand places like Majorca or the Costa Brava. +
Man: No, nor can I. +
Woman A: You know, where you have to share the beach with thousands of other people
and everyone speaks English. +
Woman B: Oh, I don't mind that. +
Man: Oh, I do. I never go to places like that. I like to get right away from all the tourists, go
somewhere that's really quiet and peaceful, like an island or something. +
Woman A: Yes, so do I—where no one speaks English. +
Woman B: What's wrong with people speaking English? I like meeting people when I'm on
holiday. I like places with a good night life, and plenty of men around, and ... well, you
know, where you can have a good time ... +

---

==== B. Monologue. +

I remember sailing on a pond that used to be by my grandfather's sawmill—we had a
boat, and we used to go sailing on this. Also, we used to do a lot of climbing trees. We
used to climb these trees for apples, which we then ate and made ourselves very sick. +
And my mother would come along and complain very strongly, but I don't think that
stopped us at all. And of course in those days I had a bike, too, and I remember I used to
push it up this very long hill near our house and then I'd get on and ride down as fast as I
could go. My mother used to complain about that, too. +

---

== Section 2

==== A. Recipe. +

Doris: Hello. What's all this then, Harry? +
Harry: What's all what? I'm making a cake. +
Doris: Yes. We can see what you're up to. Obviously you're making a cake. What else
would you be doing with a cake tin and a rolling pin on the table and the place absolutely
covered in flour. Yes, we can see what you're doing. But why are you doing it? +
Man: Yes, it's rather unlike you, Harry. +
Harry: Well, I just decided I'd try and make one for a change instead of buying one. +
Anyway this is going to be a rather special sort of cake. You can't buy them like this. And
while you're here, Doris, do you mind beating up half a dozen eggs in that blue bowl over
there? You'll find a fork and egg whisk, whichever you prefer, in the drawer on the left. +
Doris: OK. I don't mind. But what's so special about this cake? +
Harry: It's a surprise cake. +
Man: A surprise cake? +
Harry: Yes. Doris, don't forget to add five tablespoons of sugar. +
Doris: No, dear. But tell us about this surprise cake. +
Harry: Well, it was an idea I had while I was lying in bed last night. +
Man: Do you usually think of food in bed? +
Harry: I wasn't thinking of food. I decided to have a party for some old friends of mine, but I
want to give them a surprise. +
Man: What kind of surprise? +
Harry: Can you add a half of a pint of cream to that, Doris? That's right, drip it in slowly and
then beat it up again until it becomes all sticky. That's the way. +
Doris: I have made a cake before, you know. Now, come on, what's the surprise? +
Harry: Well, it's quite simple, really. You see I serve the cake with candles on it. Then I
switch out the lights and I slip out of the room. But before this I tell them that they must
count to twenty before trying to blow out the candles and they'll get a surprise. +
Man: And then? (Explosion effect) +

---

==== B. Waiting. +

—Listen! I'm terribly sorry I'm late. +
—Oh, that's all right. It doesn't really matter, does it? I haven't got anything better to do,
have I? +
—Just let me explain, will you? +
—I've only been waiting for over an hour, that's all. +
—Yes, I know, and I would have got ... +
—After all, my time isn't really that important, is it? +
—Please don't be like that. Just let me explain. I ... I tried to get here in time but just after I
left home, the car broke down. +
—The car broke down? +
—Yes, and ... well ... luckily ... there was a garage near me. And ... and it took them a
while to repair it. +
—Why didn't you at least phone? +
—I would have! But I didn't know the number of the restaurant. +
—You could have looked it up in the telephone book! +
—Yes, but ... you'll never believe this ... I couldn't remember the name of the restaurant. I
knew where it was, but forgot the name. +
—I see. Well, at least it was lucky you found a garage to repair your car. +
—Yes. It was something I couldn't do myself. It didn't take too long, but that's why I'm late,
you see. +
—Hu huh. Which garage, by the way? +
—Pardon? +
—Which garage did you take it to? +
—Uh ... the one near my flat. You know. Lewis Brothers. +
—Yes, I know that garage. It's the only one near your flat. +
—Hmm. Well now, let's have something to eat. Uh, what about some ... +
—I know the garage very well! +
—Yes. Let's see now. Yes, I think I'll have some ... +
—A pity it's Sunday. +
—Pardon? +
—A pity it's Sunday. That garage is closed on Sunday! +

---

==== C. Hiking. +

Donald: Isn't it a relief to see people and lights, Walter? Now, let me see. Where are we
exactly? According to my map, this must be Chagford. +
Walter: You're right, Don. That sign says Chagford Town Hall. But there's a more
interesting notice on the other side of the square. Do you see what it says? 'Open for +
Devon Cream Teas'. +

\* * * +

Donald: Oh, yes, so it does. Hold on a moment. I must get a newspaper. There's a
newsagent next door. +
Walter: What do you want a newspaper for? +
Donald: To find out what's been happening, of course. +
Walter: I don't need a newspaper to find out what's been happening. We must have been
walking for at least six hours. My feet have been hurting for about four hours and I've been
starving since we shared that tin of cold beans. +
Donald: You don't mean you're hungry again? I see what you mean. That tea shop does
look interesting. We could plan to morrow's walk while we were having tea, couldn't we? +

\* * * +

Walter and Donald have just finished their Devon Cream Tea, but they don't seem to want
to leave. +
Waitress: I really don't know what to do, Mrs. Adams. The two gentlemen at table four
have had complete Devon cream teas, with additional sandwiches and cakes, and
another order of scones. They don't seem to want to leave and it's a quarter past five and I
should be going off ... +
Mrs. Adams: Never mind, Mary. You go. Poor lads. They must have been walking all day
by the
look of them. They must have been starving. +
Walter: I feel a hundred per cent better. How about you, Donald? +
Donald: I must admit that a Devon cream tea is better than a tin of cold beans. In fact, it's
better than almost anything I can think of ... except a good newspaper. Do you ever buy a
newspaper? +
Walter: Not often. But I watch television a lot. +
Donald: Television! It only scratches the surface. +
Walter: I don't know what you mean by that. Television coverage is very dramatic. +
Donald: Dramatic, yes. You learn what happened but never why it happened. +
Walter: Rubbish. The television pictures show you what happened and then the people
concerned are interviewed and they tell you why it happened. +
Donald: They say what they saw, but they aren't in a position to fill in the background. +
Walter: Yes, they are. They were there. +
Donald: That doesn't mean they're in a position to fill in the background. Anyway, the
television pictures don't show you the whole truth. They only show you the bits that
happened while the cameraman was filming. Very often he missed the most important
bits. +
Mrs. Adams: Excuse me. I'm afraid it's almost half past five and we must close. Could I
just give you your bill? +
Donald: Yes, of course. See to it, will you, Walter. I must get a newspaper before the
newsagent closes. +
Walter: ... Er ... Don ... +
Donald: Yes? +
Walter: Could you get me a paper, too? +
Donald: What do you want a paper for? +
Walter: To find out what's on television. +

---

==== D. Giving Directions. +

Alan: Yes, well ... good ... that sounds great ... thanks a lot ... haven't been to a party for
ages. I'll drop round then. Er ... tell me how I get there. +
Caller: I just told you, Alan. +
Alan: You didn't. You just reminded me it was somewhere near Willesden Green. +
Caller: I told you exactly how to get here. +
Alan: Then I wasn't listening. Tell me again and I'll write it down. +
Caller: All right. Take a 46 bus. +
Alan: A what? +
Caller: A 46. +
Alan: It can't be a 46. +
Caller: It is, it is. +
Alan: Look, the 46 goes in the opposite direction. It goes towards the Elephant and Castle. +
Caller: No, it doesn't. +
Alan: It does. +
Caller: Listen, it may go towards the Elephant and Castle on its way back but before that
it's headed in the opposite direction because I happen to catch it every day on my way
home from work. +
Alan: All right, but I've seen the 46 going the opposite way, I'm sure. I didn't want to end up
at the wrong end of town, that's all. +
Caller: In any case, what you may have seen is the 46B. That goes from here down to the +
Elephant on its return journey. +
Alan: But I seem to remember coming to your house one time on the 28. Am I right? I used
to catch it at Marble Arch. +
Caller: Yes. It's discontinued. It used to run from Tooting straight through to here. It's a
pity. +
Alan: OK, so I catch the 46. Now where do I get off? +
Caller: Get off at Boots the chemist's on the corner, two stops after the railway bridge. +
Turn right and walk on until you come to the second set of traffic lights then turn right into +
Hartington Road. +
Alan: Hang on ... let me write that down. So I get off at Boots the chemist's after the
railway bridge. +
Caller: Two stops after you've gone under the railway bridge. +
Alan: All right. Then what? +
Caller: Then turn right and turn right again at the second set of traffic lights. +
Alan: Right at the second set of lights. +
Caller: Then first right into Hartington Road and I'm number one, second floor. +
Alan: OK, I've got all that. Where do you think is the nearest place for me to catch the 45? +
Caller: 46. The 45 would take you up to Wembley and you wouldn't get here till the middle
of next week. +
Alan: All right the 46. Where do I catch it? +
Caller: I should think Piccadilly Circus or Green Park would be the nearest to you. +
Alan: Oh well, they're both within walking distance. Have you any idea how often they
run? +
Caller: What? +
Alan: The 46, do you know how often it runs? +
Caller: I've no idea. I should think every ten or fifteen minutes. I never have to wait long. +
Alan: Good. I should be there in about an hour. Thanks for the invitation. Cheers. +
Caller: Cheers. See you later. +

---

== Section 3

==== A. Burglary. +

Fred: Are you sure this is the right house? +
Harry: Course I'm sure. I used to live next door, didn't I? It's easy and safe. She's not been
out for twenty years. Frightened to go out in case someone pinches her money. +
Fred: That's just what we're going to do, isn't it? Except she's in. What if she hears us? +
Harry: She won't. Deaf as a post. Probably half blind, too. Living in the dark all those years. +
Come on, get in this window. Stand on my back and give me a hand up. Right, now come
on. Let's have a look around. +

\* * * +

Wendy: Ah, good evening, you've come at last. +
Fred: Blimey! +
Harry: Oh. ... er ... good evening. Yeah ... er ... sorry to be late. +
Wendy: Late! Oh, you are naughty. Keeping me waiting here twenty years. And then
trying to surprise me by coming in the window. And you've brought a friend, I see. Good
evening. I hope you didn't damage your clothes coming in the window like that. Harry's
such a silly boy. Still up to his tricks. Do take a chair. And you Harry, sit down and we can
all have a nice cup of tea. You'd like that, wouldn't you? +
Fred: Oh ... er ... yeah, er ... thanks very much. Er ... thank you. +
Wendy: Lovely. Now, won't be a minute. Harry, entertain your friend, ha, ha, ha, ha, ha,
ha. +
Fred: A right mess this is. Quick, back out of the window. +
Harry: No. Calm down. Can't you see? It's even easier. She thinks I'm her old boyfriend. +
Must've been waiting for him for twenty years. All I have to do is ask her for the money and
she'll give it to me. She's off her head. +
Fred: Do you think so? Reckon it'll be as easy as that? +
Harry: Course it will. Now shut up. She's coming back. +
Fred: She didn't even notice our masks. +
Harry: Oh, shut up. +
Wendy: Here we are. A nice cup of tea and a bun. Now, Harry, you haven't introduced
your friend. +
Harry: Oh, no. Sorry. Er ... this is Fred. Yeah ... 'Fred'. Fred, this is ... +
Wendy: Hello, Fred. So pleased to meet you. I'm Wendy. Wendy Hartfelt. +
Fred: Oh, very pleased, I'm sure. +
Harry: Wendy, I wanted to talk to you about money. +
Wendy: Ah yes, Harry. I wondered. I wasn't going to mention it quite so soon, but that ten
thousand pounds I lent you must have acquired quite a lot of interest by now, and times
are rather hard. Now, drink your tea like a good boy and we'll discuss how you can pay it
back. Twenty years is a long time to wait, after all. Harry? Harry, what are you doing? +
Come back in here at once. Oh dear. He is a naughty boy. But I know he'll come back. +
Always did. But I'm afraid his tea will be cold. Ah ... +

---

==== B. The Empty Chair. +

A friend of mine, Rob Jenkins, almost had a nervous breakdown last year. I told him
to go to the doctor. +
Doctor: Hello, Mr. Jenkins. What can I do for you? +
Mr. Jenkins: Well, doctor ... I'm very tense and nervous. I haven't been able to sleep for
several days. +
Doctor: Hmm ... have you been working hard? +
Mr. Jenkins: Oh, yes. I've been very busy. I've been working twelve hours a day. +
Doctor: Have you been taking any pills? +
Mr. Jenkins: No, but I've been smoking too much, and I've been drinking a lot of coffee. +
Doctor: Well, you should take a holiday. You should go somewhere quiet and peaceful,
like Cornwall. Why don't you go there? +

\* * * +

Rob decided to go to Cornwall the next weekend. Penquay was a very small fishing
village on the north coast of Cornwall. There were no trains or buses to Penquay, so he
had to drive. It was a long journey, and Rob arrived late on Friday evening. The landlady
of the guest house, Mrs. Doone, answered the door and showed him to his room. Rob
was very tired and went straight to bed. He slept well and didn't wake up until nine o'clock
the next morning. +
Rob went downstairs for breakfast. Because there were no other guests, Mrs. Doone
invited him to have breakfast with her and her daughter, Catherine. Catherine was already
sitting in the dining room. She was about thirteen years old, with long, black hair and clear,
grey eyes. Mrs. Doone went to the kitchen to prepare breakfast. Rob and Catherine
looked at each other nervously for a few seconds. +
Mr. Jenkins: There are four places at the table. Is there another guest? +
Catherine: Oh, no ... we never talk about the empty place. +
Mr. Jenkins: The empty place? What do you mean? +
Catherine: Well, that used to be my father's place. +
Mr. Jenkins: 'Used to be?' I don't understand. +
Catherine: My father was a fisherman. Three years ago he went out in his boat, and he
never returned. +
Mr. Jenkins: What happened to him? +
Catherine: Nobody knows. They searched everywhere, but they found nothing. My mother
always keeps that place for him, and she makes his breakfast every morning. She thinks
he'll come back. That's a photograph of him ... over there, on the wall. My mother's been
waiting for him for three years. +

\* * * +

Rob said nothing, but he looked very worried. At that moment Mrs. Doone returned. +
She poured four cups of tea, and put one cup in the empty place. Rob looked more
worried and he stared at the empty chair. Suddenly, he heard footsteps outside the door
and a tall man, with a black beard, walked into the room. Rob looked terrified. It was the
man in the photograph! He jumped up and ran out of the room. +
Man: Who was that? What's the matter? +
Mrs. Doone: I don't know. I don't understand. He's a guest from London. He arrived last
night while you were asleep. +
Man: Catherine! Do you know anything about this? +
Catherine: No, I don't, father. But he's here because he's very nervous. He says he's
hiding here because a tall man with a black beard is trying to kill him. +
Man: Catherine, have you been telling stories again? +
Catherine: Stories, father? Me? (laughing)

---

