
= Lesson 1
:toc:

---

==== Section 1

Dialogue 1:

—Hello, I want a cab. +
—OK. What address is it? +
—1120 East 32nd Street. +
—Right. The cab will be there in a few minutes.


- cab : a taxi 出租汽车；计程车；的士

---

Dialogue 2:

—What's your job? +
—I'm an accountant. +
—Oh! Do you enjoy it? +
—No. I don't really like it. It's boring.

---

Dialogue 3:

—Where do you come from? +
—Indonesia. +
—Oh! Which part? +
—Jakarta. +
—Really?

- Jakarta印尼首都

---

Dialogue 4:

—Can you speak German? +
—Yes, I can. I speak it very well. +
—Where did you learn it? +
—I lived in Germany when I was a child. +
—What else can you speak? +
—Well, I know a little Italian.

---

Dialogue 5:

—I think a businessman should be good-looking. +
—No, I don't agree.

- good-looking : ( especially of people 尤指人 ) physically attractive 漂亮的；好看的

---

Dialogue 6:

—Would you like a drink? +
—No, thank you. I don't drink. +
—Are you sure? +
—Yes. I'm quite sure. Thank you very much. +
—What about a soft drink then? +
—Oh, alright. Lemonade would be fine.

- Lemonade柠檬味汽水;/ 柠檬饮料

---

Dialogue 7:

—Thank you very much for the meal. +
—Not at all. I'm glad you could come. +
—You must come and have a meal with me some time. +
—Yes. That would be nice.

---

Dialogue 8:

—Have you heard about the Prime Minister? +
—No. +
—She's gone to China! +
—Really!

- Prime Minister :  ( abbr. PM ) the main minister and leader of the government in some countries 首相；总理

---

Dialogue 9:

—How do you spell interesting? +
—I-N-T-E-R-E-S-T-I-N-G. +
—Thank you very much.

---

Dialogue 10:

—Would you mind passing(v.) the salt, please? +
—Certainly.

- salt盐；食盐

请把盐递给我好吗?

---

==== Section 2

A. Discussion.

Tim talked to Harry about the lecture. +
Harry: What did you think of the lecture? +
Tim: I thought it was very interesting. +
Harry: Did you really? +
Tim: Yes, didn't you? +
Harry: Certainly not. I thought he talked a lot of rubbish. +
Tim: So you think you know more than he does. +
Harry: Well, take coal for instance. +
Tim: What about it? +
Harry: Coal won't become important again. +
Tim: Why not? +
Harry: It's too dirty. They won't be able to find people to work down coal mines in the future. +
Tim: They'll invent new kinds of machinery. +
Harry: Nonsense. The only sort of power they'll use in the future is atomic power.

- lecture （通常指大学里的）讲座，讲课，演讲
- coal煤
- invent (v.) 发明；创造
- machinery （统称）机器；（尤指）大型机器 / ~ (of sth)~ (for doing sth) : 组织；机构；系统；体制
- Nonsense (n.) 谬论；胡扯；胡言乱语; /毫无意义的话；没有意义的文章
- atomic power原子能

将来他们将找不到人在煤矿下工作。

---

B.
Interview.

A reporter from a local newspaper is interviewing some students on the subject of students and money.

Reporter: Excuse me. Are you a student? +
Student 1: Yes, I am. +
Reporter: Forgive my asking you, but do you have to take a part-time job in the holidays? +
Student 1: Not really. My parents are fairly well off so I get an allowance from my father. +
Reporter: You're lucky, aren't you? +
Student 1: I suppose so. +

Reporter: What about you? Are your parents wealthy? +
Student 2: No, certainly not. +
Reporter: Do you work during the holidays? +
Student 2: Well, last Christmas I did two weeks as temporary postman, then in the summer I spent four weeks fruit picking, and I do a bit of baby-sitting, so I manage. +
Reporter: Thank you.

- Forgive my asking you 恕我冒昧
- part-time 部分时间的；兼职的
- Not really 不完全是, 不尽然
- well off : adj. 有钱的，富的；境遇好的
- allowance 津贴；补贴；补助
- fruit picking 摘水果; 摘果子
- baby-sitting 当临时保姆（baby-sit的现在分词 ）

- manage (v.) ~ (with/without sb/sth) 能解决（问题）；应付（困难局面等） / ~ (on sth) 凑合着活下去；支撑 +
-> I don't know how she manages on her own with four kids. 我真不知道她一个人是怎么养活她那四个孩子的。 +
-> He has to manage on less than ￡100 a week. 他就靠每周不到100英镑来维持生活。


---

==== Section 3

Dictation.

Dictation 1:

My name is Robert. I am eighteen years old and I am French. I am not married. Sylvia is small and fair. She is seventeen and she is a student.

---

Dictation 2:

The tall boy with fair hair is eighteen years old and he comes from Sweden. He works in a record shop. The small boy with dark hair is seventeen. He is Spanish, but he does not live in Spain. He lives in France. He works in a hotel.

- record shop 唱片行, 音像店


---
