


= Sex.And.The.City s02-17
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../+ 美国高中历史教材 American History ： From Pre-Columbian to the New Millennium/myAdocCss.css

'''


This is a story about a lovely couple, Rob and Elaine, +
who rented a house, one especially hot and sticky summer +
in the Hamptons. +
Elaine invited her best single friends, +
Cindy and Janet. +
While Rob invited his single friends, +
Ira and Matthew, +
to share the good times and exorbitant rent. +
Until one day, +
this lovely couple had a terrible fight +
when Elaine went out for a run and twisted her ankle, +
and came back early to find Rob canoodling with Janet. +
And Cindy got tired of Matthew's idiotic jokes +
and incessant market chatter. +
And Ira tried to be there for Elaine +
and confessed his true feelings for her, +
which she tried to laugh off as a joke. +
By August, it got to the point where everything was so awkward +
that nobody wanted to come back. +
And that's when Janet called her friend Charlotte. +
It's a really cute three-bedroom cottage. +
And they're giving us a fantastic deal +
for the month of August. +
Yeah, of course, it's a good deal. +
It's haunted with cheating boyfriends +
and sexual rejection. +
We can always burn sage. +
Hey, sharing a house with your girlfriends +
is fine in your 20's, +
but I feel like in your 30's, +
isn't it a tiny bit pathetic, +
like being the oldest kid at summer camp? +
She has a point. +
My 25-year-old assistant, Nina Grabowski, +
has a summer share in Bridgehampton with 18 other girls. +
They have to sleep in shifts. +
What do they do when they meet someone? +
Oh, they fuck in shifts too. +
Hold it, hold it. +
I can't believe you guys +
would pass up a chance +
to get out of this sweltering heat. +
And besides, the city's completely dead during August. +
That's because everyone's in the Hamptons. +
Or stuck in traffic trying to get there. +
But this could be the last summer +
that we can actually all get together +
and do something like this. +
I mean, next year, who knows? +
One of us could be married, or have kids. +
And then we'll always regret that last summer +
that we didn't spend together in the Hamptons. +
Charlotte's sweet hopefulness +
touched something in all of us. +
Okay, I'm in. +
Me, too. +
Fine, but I get the late shift. +
Oh, my God! +
Samantha always felt +
like she was in her 20's +
until the sight +
of an actual twenty-something +
brought her back down to earth. +
Oh, you have to try it. +
No, I'm getting you on the VIP list. +
You have to try it for one night. +
My best friend Jerry owns it. +
He also owns the one in South Beach. +
Yes! The same one. +
I need you to proof and confirm the guest list +
for the Hetrick Martin benefit +
and get me Richard Johnson, ASAP. +
No, he is not a fag. +
No, because I happen to have three friends +
he's personally fucked. +
You are nasty. You are. +
Listen, I am sending you a car, to and fro, +
and if you hate it, I'm gonna let you blow me. +
I am! +
I am serious. Off, now. +
Alec, I've gotta go. +
I'll keep you posted, okay? +
Bye, honey. +
I, um... I have personal relationships of my own, you know. +
Not with my clients you don't. +
And I have my own career to worry about. +
Your career is being my assistant. +
You're so deluded. +
I mean, you wouldn't even know what's hot if it wasn't for me. +
Nina, unfortunately, you don't seem to grasp +
the vast difference between us. +
Oh, yes, I do. +
You stood in line at Studio 54. +
I stood in line at Studio 54, +
the movie! +
I gave that bitch her first job out of college. +
She didn't know a fucking thing! +
These girls in their 20's, +
they're so spoiled and ungrateful. +
They think they're it. +
Yeah, don't they realize we're still it? +
No, because the world validates their delusion. +
And, she took a copy of my Rolodex. +
-Do you think I can sue? -Um... +
Excuse me, do you remember us in our 20's? +
Dimly. +
Have a little compassion, ladies. +
The only thing worse than being single +
and in your 30's in this city +
is being single and in your 20's. +
Hey! Where have you been? +
I was worried you were going to miss the Jitney! +
The Hamptons Jitney is just like the bus to summer camp, +
only instead of singing songs, +
everyone ignores each other +
and talks on their cell phones. +
Everyone, this is Greg. +
This is Samantha, Carrie, and Miranda. +
-Hi! Hi. +
Greg has been going +
to the Hamptons every summer +
for 20 years. +
Since I was six. +
-You do the math. -Oh, I have. +
Thank you. +
Oh! +
Ah, ah, ah, easy sister. No need to push, huh? +
Four bumper-to-bumper hours later, +
we arrived at our new digs. +
They said this place was shabby chic, +
I'm thinking it's much more shitty chic. +
These towels are mildewed. +
Actually, this whole house smells like mildew. +
That's not mildew. It's beachy. +
Would you all stop being so cynical? +
We're lucky to be here. +
Ah! Cynicism. +
Now, there's one advantage we have over girls in their 20's. +
I was cynical in high school. +
-Who's that? -Hmm. +
It's Greg, that cute guy I met on the Jitney. +
I told him to drop by. +
And if he asks, he thinks I'm 27. +
Evidently, while we had taken the midtown tunnel, +
Charlotte had taken the time tunnel. +
-Hi! -Hey. +
Come on in. +
You guys remember Greg. +
Hi, Greg. +
Hey. Uh, so, listen, uh, me and my housemates +
are having a big bonfire tonight out at the beach, +
and I just wanted to tell you that you're all invited. +
Excellent! +
Here you go, ladies. +
It's got so much foam you could ski on the head! +
Sorry, it's been a while since I've pumped a keg. +
I love young men, but, come on, I mean... +
the guys here, they don't even have chest hair yet! +
Well, that's good news for their backs. +
Sorry! +
Okay, this is really fun. +
How long do we have to stay? +
Oh, God! +
All right, I'm gonna go tell Charlotte we're leaving. +
That's another thing about twenty-something girls. +
They're very considerate. +
You can always count on one of them +
to hold your hair back when you vomit. +
Excuse me! +
Oh, my God, Carrie Bradshaw! +
-Yeah? -Laurel Harris. +
May I just tell you that I worship you? +
I read your column every week, it's like my religion. +
Oh, thank you. +
I work as an assistant in a publishing house, +
but I'm really a writer. +
Oh, great. +
Well, we'll see. +
Maybe I could send you something to read sometime? +
-Sure. -You have no idea what that would mean to me. +
To-- to have someone like you +
as my mentor. +
Oh, well, mentor. +
So, could I call you up sometime in the city? +
It would-- if I could just spend some time with you, +
that-- that would be so cool. +
Uh, of course, +
uh, I'll-- I'll be looking at a very busy summer. +
I-- I can help, I'll run errands. I'll do your wash. +
No, no, no menial labor necessary. +
I'll just, um, I'll give you my phone number. +
Oh, my God, this is so cool. +
Oh, thank you. +
Oh, I'll take that. +
Thank you. +
The next day, Miranda woke up early +
to enjoy the cool morning breeze +
and a much needed moment of solitude. +
All right, somebody puked on the deck. +
Oh, sorry. Stacy and Holly did too many Jell-O shots. +
What are you, 25 now? +
Good morning. +
No, 27! +
Whatever. +
That week, back in the city, I wondered. +
What was the allure of the 20's? +
On one hand, there's great skin tone, +
the thrill of fresh experience, +
and the sense of a consequence-free life +
full of seemingly endless possibilities. +
While on the other, +
there are horrible apartments, +
sexually inexperienced men, +
and embarrassing errors in fashion judgment. +
Should we fear these freshly minted, +
single women as a threat to our very survival? +
Or pity them as clueless half-wits +
about to get their dreams dashed +
and illusions shattered? +
Twenty-something girls... +
Friend... or foe? +
And that evening, in my first act as a mentor, +
I took my young acolyte to a book party. +
Ceviche? +
Oh, my God. +
I can't believe I'm out with Carrie Bradshaw, +
this is too cool. +
Oh, stop, I can feel my head swelling. +
If it gets any bigger, I'm gonna have to say goodbye to my hats. +
-I have a question. -Yeah? +
Do you think that 25 is too young +
to write a personal memoir? +
Well, as long as it doesn't deal with incest, +
Prozac, or partying, no. +
Well, it does deal with sex. +
Or rather, not having sex. +
It's about how girls my age +
are saving themselves for marriage. +
Saving what for marriage? +
Our virginity. +
Are you seriously telling me +
that you've never had sex with a man? +
That is correct. +
Okay, uh, now, what do you consider sex? +
Are you implying I'm some kind of Lewinsky? +
No! No-- -I'm not! +
I'm talking no blow jobs, no hand jobs. +
All right, I get it, no jobs of any kind. +
You know what? +
I think I need to get a drink. +
I'll get it. Cosmopolitan, right? +
-Yes. -I remember. +
From your column. +
A 25-year-old virgin was getting me a Cosmopolitan. +
The generation gap had never seemed so wide. +
-Hi. -Hi. +
Have you actually read the book? +
-Uh, no. Have you? -Nope, not yet. +
Do you know anything about the author? +
Yeah, his family has a history of diabetes +
and he has a steel splint in his left femur. +
I'm his doctor, Bradley Meego. +
Oh! Carrie Bradshaw. +
Jeez, my doctor won't even make house calls +
let alone attend a book party. +
Yeah, I've never been to one before. +
I thought it might be interesting. +
Now it's just exceeded all my expectations. +
Yeah, I know, generally, it's just cheese and crackers. +
You never see an actual shrimp. +
No, I meant you. +
Oh. +
You know, I'd ask you out for a drink after, +
but I'm driving straight from here to the Hamptons. +
Oh, I'm-- I'm actually going out to the Hamptons tomorrow. +
Well, great. Um, can I call you there? +
All right, well, you know what? +
I'll be with my friends Saturday at Townline Beach. +
A big yellow umbrella. +
You can come by and say hello if you'd like. +
Is this just a ploy to see me in my bathing suit? +
Yeah. +
-Here's your Cosmo, miss. -Thank you. +
-Hi. -Uh... +
Dr. Bradley Meego, this is Laurel. +
-Hi. -Hey. +
Um, so, what if it rains? +
Do we pick another date, or... +
Doctor, you are persistent. +
All right, in case of emergency only. +
Yep, now I'm gonna have to buy the book. +
Nice meeting you. +
-You, too. Bye. +
Drive safe. +
Oh, my God, he is such a fox. +
Did-- did you just meet him when I was at the bar? +
-Mm-hmm. -Lady, you've got it going on! +
That Saturday turned out to be hot and sunny. +
While we sat under our umbrella, +
twenty-something girls sizzled on the sand +
like rotisserie chickens. +
Excuse me, when did tanning come back in style? +
Hand me the 45! +
Forty-five? Didn't know it went up that high. +
You can sit in a microwave and not burn. +
It's Charlotte's, but I don't think she's gonna be using it. +
It's not good for her 27-year-old image. +
She actually put on oil. +
Just let her have her fun now. +
Come Labor Day, she's gonna look like a 27-year-old handbag. +
I'd risk a few precancerous freckles +
for a summer romance. +
And right then, +
my summer romance made his appearance, +
right on schedule. +
The yellow umbrellas seem to be very popular this year. +
Hey! +
Samantha, Miranda, this is Dr. Bradley Meego. +
-Hello! Hi. +
Hello, ladies. +
So what kind of a doctor are you, doctor? +
Uh, internal medicine. +
General, all-purpose kind of thing. +
Fabulous! So you can prescribe medication? +
What did you have in mind? +
Feel free to ignore her. +
-I'm sure that's impossible. +
Listen, I'm gonna go take a quick dip. +
Now, you promise not to ditch me, now. +
-I promise. -Okay. +
Is that the guy from the book party? +
Yeah. +
I've got to start reading. +
He's cute, I'm just not really sure I'm interested. +
Good-looking, polite, +
house in the Hamptons. +
It's good on paper. +
-Well, you know the rule. -Huh? +
-Good on paper, bad in bed. +
A "good on paper guy" is a guy with great credentials, +
who you always end up leaving for some hot guy +
who rides a motorcycle +
and doesn't have a checking account. +
-I got ya. +
Oh, my God! +
Ah! The water feels so awesome. +
You guys should really go in. +
You better put on some sunscreen, +
Georgette Hamilton. +
Oh, that's okay, I never burn. +
Well, I do. +
In fact, I think I've had enough for today. +
I'm gonna go grocery shopping. +
You guys want anything? +
Oh, we should get some rum. +
We can make Long Island Iced Teas. +
Oh, yes. I love Long Island Iced Teas. +
Excellent! +
So I took a leap of faith and made reservations +
at one of those impossible to get into restaurants for tonight. +
Oh, wow, I'd love to, +
I just, I can't abandon my friends. +
Well, actually, that wasn't an invitation. +
It was just restaurant chit-chat. +
Oh, oh. +
-I'm kidding. -Oh. +
How about after dinner? +
I got a great little house. +
A cute little porch we can sit on. +
Oh, I don't know. +
Okay, then, how about if I just call your +
in case of emergency number this weekend. +
The emergency being I think I'm gonna miss you. +
Yes, you can definitely do that. +
Good. +
Romantic, polite, +
and his very own house south of the highway. +
My "good on paper" guy was jumping right off the page. +
Later that afternoon, +
we came back from the beach +
rested, rejuvenated, +
feeling almost 29 again. +
Even Miranda was in good spirits. +
Hey, guys, I just got back from the market. +
Yeah? +
Fresh corn and seafood for dinner. +
-Yummy! +
Except, Carrie, your groupie can't stay. +
I only got enough for the four of us. +
She's here? +
Yeah, she was asking too many inane questions. +
I sent her up to your room. +
Oh, thanks. +
-Sorry. -So, I have got to go shower, +
-I'm all itchy in my bathing suit from the sand. -Uh-huh. Uh-huh. +
-And then I'm gonna help ya. -Okay. +
Take your time. +
Samantha, that came for you. +
Oh... +
Oh, my God! +
What's wrong? +
It's for the Hampton's hoedown tomorrow night. +
And the event is being run by Nina G. Public Relations. Nina G.! +
Overnight, Samantha's ex-assistant, Nina Grabowski, +
had reinvented herself as Nina G. +
I was up for that job. +
And now she's using my Rolodex +
to put together the guest list. +
While Samantha was getting fucked royally +
by her protégé, +
mine was giving me the royal treatment. +
It's not that I don't wanna have sex with men, +
I just feel like these previous generations of women +
have devalued sex to the point where it's not even special anymore. +
One summer, when I was 15, +
I read everything Jackie Collins ever wrote. +
And I thought to myself, "Who cares?" +
I mean, is this supposed to be shocking, +
wagging one's pussy at every good-looking stud +
who walks by? +
Please. +
And, what is it you like about my column? +
I have a, a tiny tick on my stomach, +
and I can't get it off. +
Ew. Does it hurt? +
No, but it itches. +
Oh, my God, that is not a tick. +
Well, well, what is it? +
Well, there go our shitty sheets. +
Oh, my God, it's so disgusting. +
Where's she going? +
To the drugstore. +
Charlotte really is in her 20's. +
She's got crabs. +
Oh, my God! +
That night, I called Dr. Meego. +
I figured it was an emergency. +
I just, I have this thing about crabs. +
I had them once in college, +
and the experience scarred me for life. +
So, I really, I don't think I can go back to that house +
until the mattresses are sanitized +
and the sheets and towels are burned. +
No, I'm-- I'm flattered you thought of me. +
I'd be happy to prescribe your friend +
some industrial strength pubicide. +
No, that's all right, +
I think she can take care of herself. +
-Here, cheers. -Cheers. +
You might have to spend the night here, you know. +
I might have to, but only to sleep. +
You know, women are always saying that, +
and then, as soon as the lights go out, +
boom, they're going right for my pajamas. +
All righty, I promise, no funny stuff. +
That night, we slept together +
but we didn't sleep together. +
It was really nice. +
And I believe it was the first instance +
of a case of crabs moving a relationship forward. +
Every year, one of the local Hamptons billionaires +
got down and dirty and threw a big hoedown +
full of cowboys and caviar. +
It was the event of the season. +
We joined Samantha to lend our moral support. +
I can't believe it. +
There are people here who don't even come to my parties +
and they came to Nina's. +
Look at her over there. +
Beef jerky carpaccio? +
I am just so depressed right now. +
Excuse me. +
Hey, where are you going? +
To congratulate Nina. +
I may need her to hire me someday. +
While Samantha set out to negotiate +
twenty-something détente , +
Charlotte prepared to launch a full-out war. +
Excuse me. +
Right. No way. +
Hey! +
Do you know that you gave me crabs? +
What? +
You heard me. +
What makes you think it was me? +
Oh, that is so tacky. +
Yeah, well, so is lying about your age. +
You know, I saw your driver's license +
when you bought the beer last night. +
I didn't lie. +
You made an assumption, +
I didn't contradict it. +
Whatever. +
You know, I may have given you crabs, +
but you deceived me. +
That is so much worse. +
Grow up. +
You are a wait person. That does not mean that you wait, +
it means that you go! +
Nina! +
Oh, my God, you actually came. +
I just stopped by to wish you good luck. +
It's a fabulous party. +
That is very cool of you. +
Nina, I told you, +
I didn't want Martha seated near the hayride. +
-She's allergic. -Oh. +
Could you please try to keep the young people +
out until after 11:00? +
Oh. Yeah. +
I just wanna tell you, +
we're all out of country fried goat cheese, +
somebody got stuck with a cactus needle, +
and there are people outside with invitations +
who are not on the fucking list. +
Jesus fucking Christ. +
You are totally coked out. +
You are totally jealous. +
What is that? Oh, my God! What is that? +
What is that sound? Oh, my God. What? +
What is happening? +
That is not supposed to happen until midnight. +
I know! +
This is your problem. +
Get them to stop! +
I can't, they're on a fucking barge! +
Oh, my God. Samantha, could you help me? +
I-- I need to get everybody outside. +
I'm just, I'm totally fucked right now. +
Okay, people, fiesta fireworks, outside! +
Let's go. Let's go! +
-Oh, Nina! -Yeah? +
This is Greg. +
I think the two of you would really hit it off. +
-Hi. -Hi. +
I began to realize then +
that the biggest threat twenty-something girls posed +
was to themselves. +
Hey, Carrie, I've been looking all over for you. +
Hey. Look, I got one just like yours. +
Oh, wow, that's great. +
You want me to get you a Cosmopolitan? +
No, no, that's okay, I'm actually, I'm gonna go find my date. +
But I'll see you later, okay? +
That guy from the bookstore? +
-Oh, my God, he was so cute! -Oh. +
Annoying, yes, dangerous, no. +
They were simply our youthful doppelgangers +
who needed our compassion more than anything. +
And then everything I so firmly believed +
was promptly blown to pieces. +
Yeah, yeah. I know. +
Listen. +
-Yeah? -Yeah. +
Is it you? +
Hey, what are you, what are you doing here? +
What am I doing here? +
What are you doing here? +
I just got back this week from Paris. +
Oh, Carrie, this is Natasha. +
Hi, it's a pleasure to meet you. +
I've heard so much about you. +
Oh, really? +
Natasha's parents have a house here in East Hampton. +
We just came up for the weekend. +
Excuse me. It was nice to meet you, Carrie. +
I'm sorry, I'm just... a little stunned here. +
And confused. +
Who is she? +
Well, I, you know, I meant to call you. +
She's a girl... +
She's this girl that I met in Paris. +
She works for Ralph Lauren in Europe. +
So you're just in from Paris for the weekend? +
No. +
The Paris deal fell through. +
I, uh, I planned on calling you. +
I certainly didn't want to run into you like this. +
Well, you can't plan everything. +
Life can be pretty random. +
I'm here on a, on a date, too, somewhere. +
It's Dr. Bradley Meego. +
He's good on paper, you know, probably like Natasha. +
Good-looking, sweet, blah, blah blah. +
So how old is she, anyway? +
I don't know, 26, 27. +
Something like that. +
Well, I'll see you in the Hamptons +
or back in the city. +
I-- I promise to call when I get back into town. +
Carrie? +
Are you okay? +
No, I just ran into Big. +
He's back from Paris. +
He has a new girlfriend. +
She's 26. +
-Where is he? I didn't see-- -Oh, God. +
And then I realized. +
Twenty-something girls are just fabulous, +
until you see one +
with the man who broke your heart. +
欲望城市 +
（性爱专家凯莉布雷萧） +
，二十岁女孩VS三十岁女人 +
这是关于一对爱侣 罗伯与伊莲的故事 +
在一个特别炎热的夏季 他们在汉普顿租了一栋别墅 +
伊莲邀请她最好的单身朋友 辛蒂和珍娜 +
而罗伯也邀了单身友人 艾拉和马修 +
一起共度美好时光 以及分摊过高的房租 +
直到有一天 这对爱侣起了激烈的争执 +
伊莲因慢跑时不慎扭伤脚踝 提早返家 +
发现罗伯和珍娜一起泛舟 +
辛蒂厌烦马修的白痴笑话 以及没完没了的市场经 +
艾拉则对伊莲示爱 +
她却试图一笑置之 +
到了八月，情况变得很尴尬 +
没人想再回到那个地方 +
珍娜便在此时打给夏绿蒂… +
那是栋小巧的三房别墅 正适合八月去度假 +
-那屋里充斥求欢被拒的阴影 -我们可以烧鼠尾草 +
二十多岁时和女性友人 分租房子还说得过去 +
但到了三十几岁仍如此 不会有点可悲吗？ +
她说得有理，我25岁的助理 +
夏天在布里治汉普顿 和18个女孩一起分租房子 +
-她们得轮班睡觉 -要是有艳遇怎么办？ +
-连做爱也要排班 -慢着 +
我不敢相信 你们要放弃避暑的大好机会 +
再说，八月时 整个纽约就像死城 +
因为人人都去了汉普顿 +
或者正塞在去那里的途中 +
这或许是最后一个 我们能自在出游的夏天 +
明年，谁知道呢？ 我们其中一人可能已结婚生子 +
我们会终生遗憾最后一个夏天 +
未能一起在汉普顿共度 +
夏绿蒂充满希望的甜蜜语气 打动了我们 +
-好吧，我加入 -我也是 +
好吧… +
但我要排晚班 +
莎曼珊永远觉得 自己还是二十几岁 +
直到她看见 真正二十几岁的女人 +
你得尝试一次 +
屋主是我最好的朋友杰瑞 他在南滩也有一栋房子 +
确认宾客名单 然后尽快帮我联络理查强森 +
他不是同性恋 我三个朋友跟他上过床 +
你真下流 +
我已经把邀请卡寄给你了 如果你不喜欢，尽管找我算帐 +
我是说真的，马上去办 +
艾力克，我得挂了 有最新消息我再通知你 +
我有自己私人的人际关系 +
-不准勾搭我的客户 -我也要烦脑我的前途 +
你的前途就是担任我的助理 +
要不是我 你哪懂什么东西才热门 +
妮娜，你似乎不明白 我们之间有着天壤之别 +
我当然明白 你站在夜总会门口排队 +
而我站在电影院门口排队 +
那臭丫头大学毕业第一份工作 是我给她的 +
二十几岁的女孩真是不知好歹 她们以为自己多了不起 +
-她们不懂我们仍是主流吗？ -这世界支持她们的错觉 +
她还拿走我通讯录的副本 我能告她吗？ +
-记得我们二十几岁那时吗？ -没什么印象 +
唯一比三十几岁单身还惨的事 +
就是二十几岁时孤零零一个人 +
你们差点赶不上巴士 +
它就像开往夏令营的游览车 +
只不过谁也不理谁 自顾自地讲电话 +
各位，这是葛瑞格 她们是莎曼珊、凯莉和米兰达 +
二十年来 葛瑞格每年夏天都去汉普顿 +
-从我六岁起 -你来算年龄吧 +
-我算过了 -谢谢 +
别急，小姐，没必要推挤 +
在车阵中缓慢前进四小时后 我们抵达了新住处 +
他们说这房子有点简陋 我认为是糟透了 +
这些毛巾发霉了 整个房子都有霉味 +
那不是发霉，是砂砾 +
你们别再冷嘲热讽了好吗？ 我们能来这里就很幸运了 +
愤世嫉俗，这是我们胜过 二十几岁女孩的优势 +
-我高中时就很会挖苦人 -是谁来了？ +
是葛瑞格 我在巴士上认识的那个帅哥 +
我叫他过来坐一下 如果他问起，就说我27岁 +
当我们穿越城中隧道来到此地 +
夏绿蒂已穿越了时光隧道 +
快进来 你们还记得葛瑞格吧？ +
你好，葛瑞格 +
我和我室友今晚要在沙滩 办一个盛大的营火派对 +
-你们都被邀请了 -太棒了 +
各位，拿去吧 +
泡沫好多 简直可以在上面滑雪了 +
我已经很久没用唧筒了 +
我爱年轻小伙子 但这里的男人连胸毛都没有 +
这对他们的背部是好消息 +
抱歉 +
真是有趣极了 我们还要待多久？ +
天啊 +
我去跟夏绿蒂说我们要走了 +
二十几岁的女孩非常体贴 +
当你呕吐时 她们会帮你把头发撩起来 +
不好意思 +
我的天，你是凯莉布雷萧？ +
我叫萝拉哈里斯 我一定要告诉你我有多崇拜你 +
-我每个礼拜都读你的专栏 -谢谢 +
我在一家出版社当助理 但我其实是个作家 +
也许改天我能把我的文章 寄给你看看吗？ +
当然可以 +
你不知道能有像你这样的人 +
做我的良师意义多么重大 +
-良师… -回城里我能打电话给你吗？ +
我能跟你见面吗？ +
当然，不过这个夏天我会很忙 +
我可以帮你跑腿、洗衣服 +
不需要干仆人的活儿 我把电话号码给你 +
-我的天，真是太酷了 -谢谢 +
隔天，米兰达一早起床 享受清晨的微风 +
以及更为必要的独处时光 +
-有人在门口呕吐 -抱歉 +
史黛西和荷莉喝太多酒了 +
你以为你现在几岁，25吗？ +
早安 +
-不，27岁 -随便 +
回到城里 我纳闷二十多岁的魅力是什么 +
气色很好 对新奇的体验感到兴奋 +
不计后果 充满无限可能的人生 +
同时住很糟糕的公寓 交往没有性经验的男友 +
以及穿没有品味的衣服 +
我们是否该担心 这些年轻的单身女子 +
对我们的生存造成威胁？ +
或者同情她们 幻想即将破灭却一无所知？ +
二十多岁的女孩 是朋友…还是敌人？ +
那晚，身为良师的第一件事 +
我带着我年轻的门徒 参加一个新书派对 +
我的天 +
我真不敢相信 我和凯莉布雷萧一起出现 +
够了，若我的头继续变大 我就必须和我的帽子道别 +
我有个问题，25岁写回忆录 会不会太年轻？ +
只要里面没提到乱伦 百忧解或狂欢就不会 +
它探讨性 或者应该说是没做爱 +
它是关于我这年纪的女孩 为了婚姻保有处女之身 +
-为了婚姻保有什么？ -贞操 +
你的意思是 你从没和男人上过床？ +
没错 +
你认为性是什么？ +
你在暗示我跟莒恩丝基一样？ +
不，我是指口交、手淫都不算 +
我懂了，任何费力的事都不算 +
你知道吗？ 我想我需要喝杯饮料 +
我去拿，四海为家，对吗？ 我记得…你专栏中写过 +
一个25岁的处女 正帮我去拿四海为家 +
世代鸿沟从未显得如此深远 +
-嗨 -嗨 +
-你读过这本书了吗？ -还没 +
你呢？你对作者有何认识？ +
他的家族有糖尿病遗传 而他左股骨上了夹板 +
-我是他的医生，布莱德米哥 -我是凯莉布雷萧 +
我的医生平常连电话都不打 更别说是来参加新书派对 +
我想这可能会很有趣 现在已经超出我的期望了 +
通常，连只真正的虾子也没有 +
不，我是指你 +
等会我很想约你一起喝东西 但我要开车去汉普顿 +
事实上，我明天也要去汉普顿 +
太好了，我可以打电话给你吗 +
星期六我跟我朋友 会去唐莱海滩 +
寻找很大的黄色遮阳伞 你可以来打个招呼 +
这是为了看我穿泳衣的计谋吗 +
这是你的酒，小姐 +
他是布莱德米哥医生 她是萝拉 +
万一下雨怎么办？ 要另外定约会吗？ +
医生，你还真是不屈不挠 +
好吧，除非有急事才打 +
现在我得买下这本书了 很高兴认识你，你也是 +
小心开车 +
他真迷人，你是在我去吧台时 认识他的吗？ +
小姐，真有你的 +
那个星期六炎热又晴朗 +
当我们坐在遮阳伞下时 +
二十多岁的女孩 像烤肉般发出嘶嘶声 +
请问古铜色皮肤 何时又开始流行了？ +
-把防晒系数45的拿给我 -我不知道有出到这么高系数 +
你可以待在微波炉中而不灼伤 +
这是夏绿蒂的 但我不认为她会用 +
这不符合她27岁的形象 +
她竟然还抹了油 +
到时候，她看起来 便会像个27岁的手提包 +
我愿意为了夏日恋情 甘冒长癌症雀斑之险 +
就在此时 我夏日恋情的男主角 +
准时出现了 +
黄色遮阳伞今年似乎非常流行 +
嗨 +
莎曼珊、米兰达 这位是布莱德米哥医生 +
你是哪一科的医生，大夫？ +
什么都看，可以说是万事通 +
太棒了，那么你能开药方？ +
-你有什么意见？ -别理她 +
我要去冲个澡 你保证不丢下我？ +
我保证 +
他是你在新书派对上认识的？ +
我得开始阅读了 +
他很可爱 我只是不太确定有没有兴趣 +
人长得帅、又有礼貌 在汉普顿有房子 +
擅长理论 +
你知道那定律 擅长理论的人床上功夫很差劲 +
擅长理论的男人 拥有出色的背景资历 +
最后你却永远会为了一个 骑摩托车的浪子离他而去 +
海水真是棒呆了 你们应该下去玩一玩 +
你最好擦一点防晒油 +
-没关系，我从来不会晒伤 -我会 +
我要去买点东西 你们想要什么吗？ +
兰姆酒，我们可以做长岛冰茶 +
好，我爱死长岛冰茶了 +
太棒了 +
我在一家很热门的餐厅订位了 +
我很想去 但我不能就这样丢下我的朋友 +
其实这并不是邀请 我只是随口提起 +
开玩笑的 +
那晚餐之后呢？ 我们可以在阳台上坐坐 +
我不知道 +
好吧，这个周末 我打你的紧急电话如何？ +
紧急状况是 我猜我会开始想你 +
好，你当然可以这么做 +
浪漫、殷勤 加上他在公路南方拥有的房子 +
这个擅长理论的男人 正从纸上一跃而出 +
我们从海滩返回别墅时 感觉仿佛又是29岁般年轻 +
连米兰达心情都很好 +
我刚从市场回来 晚餐有新鲜的玉米和海产 +
你的崇拜者不能留下来，凯莉 我只准备了四人份 +
她在这里？ +
她问太多问题了 我让她去你房间 +
-谢了 -对不起 +
我得把身上的沙冲干净 然后就去帮你 +
慢慢来 莎曼珊，那封信是你的 +
-我的天 -怎么了？ +
明晚是汉普顿的土风舞晚会 +
由妮娜G公关公司举办 +
一夜之间，莎曼珊的前助理 便将自己重新塑造成为妮娜G +
她用我的通讯录制作宾客名单 +
当莎曼珊被她的手下 狠狠摆了一道 +
我的门徒正给我女王般的待遇 +
不是我不想跟男人上床 +
但以前的女人贬低了性的价值 +
因此它甚至不再特别了 +
我15岁时 我读每本杰姬柯林斯的作品 +
当时我在想 “这应该是惊人的吗？” +
“对每个经过的性感男人 搔首弄姿？” +
你到底喜欢我专栏哪一点？ +
我肚子上有个虱子，我弄不掉 +
-会痛吗？ -不，但会痒 +
-我的天，那不是虱子 -那是什么？ +
-都是可恶的床单害的 -好恶心 +
-她要去哪里？ -去药房 +
夏绿蒂真的回到二十几岁了 她身上有阴虱 +
当晚，我打给米哥医生 我想这算是紧急情况 +
我大学时长过一次阴虱 害我一辈子留下疤痕 +
我得等床单和毛巾都烧掉 才能回去 +
我很高兴你想到了我 +
我很乐意为你朋友 开一点杀菌药 +
我想她能照顾自己 +
干杯 +
你可能得在这里过夜 +
-可能，不过只是睡觉而已 -女人总是这么说 +
灯一关掉 她们就来脱我的睡衣 +
我保证没有滑稽的玩意儿 +
我们同床，但并未上床 那感觉好极了 +
这是第一件 阴虱让感情有所进展的案例 +
每年，本地的有钱人 +
都会办一个挤满牛仔 和鱼子酱的盛大土风舞会 +
这是社交季的大事 +
我们陪莎曼珊出席 给予她精神支持 +
有人不参加我办的派对 却参加妮娜办的 +
你看看她 +
来点生腌牛肉干？ +
我现在真的非常沮丧，失陪 +
-你要去哪里 -去恭喜妮娜 +
有一天我可能得靠她 赏我一口饭吃 +
当莎曼珊出发去向 二十多岁的女孩低头 +
夏绿蒂则准备发动战争 +
不好意思 +
你知道你把阴虱传染给我吗？ +
-什么？ -你听到了 +
-你凭什么认为是我？ -那真是太低级了 +
你谎报年龄还不是一样 昨晚我看到你的驾照了 +
我没有说谎 是你这么假设，我没反驳而已 +
也许阴虱是我传染给你的 但你欺骗我 +
-这严重多了 -成熟点吧 +
你是个接待员 没做好份内事就滚吧 +
我的天，你真的来了 +
我只是来祝福你好运 +
-这是个很棒的派对 -你真好 +
我不希望玛莎乘干草卡车 她会过敏 +
你能让年轻人一直到11点 都待在外头吗？ +
羊酪已经没了 还有人被仙人掌刺到 +
外面有不在 宾客名单上的人要进来 +
-你办事能力真差 -你太小心眼了 +
那是什么？我的天啊 那是什么？ +
那应该等到午夜才放的 +
-我知道 -这是你的问题 +
-叫他们停下来 -不行，他们在该死的游艇上 +
莎曼珊，你能帮我吗？ 我需要让大家到外面去 +
我现在把一切都搞砸了 +
各位，外面在放烟火 我们往外移动吧 +
妮娜，这是葛瑞格 我想你们两个将会一见如故 +
我发现二十多岁的女孩 +
所造成的最大威胁 是对她们自己 +
我到处找你 你看，我有条跟你一样的项练 +
-那很好 -你要来杯四海为家吗？ +
我要去找我的男伴了，待会见 +
那个在书店认识的男人？ 他好帅 +
她们的确烦人，却不危险 只不过是我们年轻时的翻版 +
需要我们的同情甚过一切 +
接着我所坚信的一切马上瓦解 +
-是你吗？ -你怎么会在这里？ +
我怎么会在这里？ 那你又怎么会在这里？ +
我刚从巴黎回来 +
凯莉，这是娜塔莎 +
很高兴认识你 我听说许多有关你的事 +
是吗？ +
娜塔莎的父母在这里有栋别墅 我们只是周末来度假 +
抱歉失陪，幸会，凯莉 +
对不起，我只是…有点震惊 +
还有困惑，她是谁？ +
我本来想打给你 +
她是… 她是我在巴黎认识的女孩 +
她在欧洲替劳夫罗伦工作 +
所以你只是 从巴黎回来度周末？ +
不是 +
巴黎的计划已经告吹 +
我…我有打算跟你联络 +
我真的不想 在这种情况下遇见你 +
世事难料 我的男伴也在这里…某个地方 +
他是布莱德米哥医生 +
他擅长理论，或许跟 娜塔莎一样，好看、温柔… +
她到底几岁？ +
我不知道，26、27 +
大概吧 +
我们在汉普顿或回纽约时再见 +
我保证回城里一定打电话给你 +
凯莉，你还好吧？ +
不好，我刚碰到大人物了 +
他从巴黎回来 交了新的女朋友 +
她26岁 +
他在哪里？我没看见他 +
我这才明白 二十多岁的女孩确实很迷人 +
直到你看到她身边 有个曾令你心碎的男人 +
