

= succession - s1-01
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''

Where am I?
[.my2]
﻿我在哪儿

Where the fuck am I?
[.my2]
这是什么鬼地方

Jesus.
[.my2]
老天

Logan?
[.my2]
洛根

Logan?
[.my2]
洛根

Logan, where are you?
[.my2]
洛根 你在哪儿

- Logan! - Oh, fuck.
[.my2]
-洛根  -我操

Where am I?
[.my2]
我在哪儿

It's OK.
[.my2]
没事的

We're in the new place.
[.my2]
我们在一个新地方

- I'm sorry. - It's OK.
[.my2]
-对不起  -没事

What's that, man?
[.my2]
你说啥 老兄

- We're here, Mr. Roy. - This is it.
[.my2]
-我们到了 罗伊先生  -就是今天

This is the day we make it happen 实现它, Fikret.
[.my2]
今天就是我们创造历史的日子 费克雷

You're the man, Mr. Roy.
[.my2]
您是天选之人 罗伊先生

You're the man.
[.my2]
祝您成功

We good?
[.my2]
可以了吗

Jesus Christ.
[.my2]
我的天

Hey, hey, hey, buddy.
[.my2]
伙计们

Good to see you.
[.my2]
真高兴见到你

So, are we ready to fuck or what?
[.my2]
咱们准备好大干一场了吗

Yeah... OK.
[.my2]
好... 好吧

Look, I-I'm really sorry,
[.my2]
我说 真的很遗憾

but it looks like there's an issue.
[.my2]
似乎出了点问题

Come on, I came all the way up here, dude.
[.my2]
拜托 我这么大老远都来了 哥们

Yeah, I'm sorry...
[.my2]
很遗憾...

Uh, dude.
[.my2]
哥们

OK.
[.my2]
好吧

Listen, you know I love what you do, right?
[.my2]
听着 你知道我喜欢你做的事 对吧

I'd love to keep you and your team in place, Lawrence.
[.my2]
我很想让你和你的团队继续做下去 劳伦斯

I think Vaulter is the shiz.
[.my2]
沃尔特烂得像屎

We're the shiz?
[.my2]
我们很烂吗

Yeah.
[.my2]
对

What's it gonna take?
[.my2]
还有什么条件

You want me to send a vintage Jaguar over to your house today?
[.my2]
就算要我今天往你家运一台古董捷豹

I'll do it.
[.my2]
我也会照做

Um, s-sure. Look, um...
[.my2]
我明白 但是...

I just think bottom line,
[.my2]
就底价而言

I can deliver a lot more value for our shareholders.
[.my2]
我要为自家股东们创造更大的价值

I hope we haven't inconvenienced you.
[.my2]
希望这不会对你造成困扰

I see you. I see this.
[.my2]
我算明白了

We appreciate your interest in our little outfit,
[.my2]
谢谢贵司对我们小团队的认可

but I think that's it.
[.my2]
但到此为止吧

Come on. That's it?
[.my2]
别这样 到此为止吗

That's not it. What the fuck happened?
[.my2]
不能这样结束 搞毛线呢

Yo, hang on.
[.my2]
等一下

Hold up, hold up.
[.my2]
慢着 慢着

- You get the message? - What?
[.my2]
-你收到消息了吗  -什么

I'm not letting you Neanderthals in to rape my company.
[.my2]
我不会让你们这些穴居人们掠夺我的公司

Ever.
[.my2]
永远不会

I'm sorry?
[.my2]
什么

You're a bunch of bloated dinosaurs
[.my2]
你们就是群傲慢的恐龙

who didn't even notice the monkeys swinging by till yesterday.
[.my2]
快饿死了才发现猴子就在眼皮底下跑

Well, fuck you, daddy's boy.
[.my2]
总之 去你妈的 小屁孩

Hey, come on. Don't blow this up.
[.my2]
别这样 这事儿不能吹

I got a track record from founding
[.my2]
我手里有一份销售记录

one of the most exciting new media brands in the world.
[.my2]
来自世界上最新潮的媒体品牌之一

And what do you got?
[.my2]
你有什么

Track marks from shooting junk?
[.my2]
射击废物留下的痕迹吗

Thanks for coming down. It was great to meet you.
[.my2]
谢谢你来 很高兴见到你

Sorry this isn't going to work out.
[.my2]
但这事儿谈不成的

No, it's gonna work out.
[.my2]
不 可以的

No, it isn't.
[.my2]
不 真的不行

Take care, dude.
[.my2]
保重 哥们

Fuck. What the fuck, Frank?
[.my2]
操 这他妈怎么回事 弗兰克

- I...  - How can we salvage this?
[.my2]
-我...  -我们该怎么补救

You still want to pursue this?
[.my2]
你还想谈这单吗

Yeah, of course I wanna pursue.
[.my2]
废话 我当然想继续谈

I wanna announce.
[.my2]
还要开发布会

This is part of the whole thing.
[.my2]
这是计划的一部分

This is the secret sauce.
[.my2]
是秘密武器

Do we need to sweeten the offer?
[.my2]
我们要给个更诱人的出价吗

You wanna bump the offer another point?
[.my2]
你想把出价再提高一个点吗

Do you wanna call your dad?
[.my2]
要给你爸打电话吗

Do I wanna call my dad?
[.my2]
要给我爸打电话吗

No, I don't wanna call my dad.
[.my2]
不 我不想给我爸打电话

Do you wanna call your dad?
[.my2]
你要给你爸打一个吗

- No. - No?
[.my2]
-不  -不用吗

Do you wanna call your dad?
[.my2]
你要打吗

Does anybody wanna call their dad?
[.my2]
还有人要给老爸打电话的吗

OK, nobody wants to talk to their fucking dad.
[.my2]
行 没人想他妈跟自己老爸讲话

So, we've started, so let's buy this fucking company.
[.my2]
那么 既然开始了 就把那破公司买下来

I'm pushing the bid to 120. OK?
[.my2]
把报价提到1.2亿 行吗

OK.
[.my2]
可以

How's it going?
[.my2]
进行得如何

Yeah, I'm right in the middle, Dad.
[.my2]
挺好的 还在努力 爸

Did you close?
[.my2]
成功了吗

Yeah, it's OK.
[.my2]
还算顺利

We're not quite closed.
[.my2]
但离成功还差一点

I'm going to 120.
[.my2]
我打算提到1.2亿

So, that's good.
[.my2]
所以 还行

and are we still good for the announcement?
[.my2]
咱们还能办发布会吧

Uh-huh.
[.my2]
可以

Great, 'cause obviously I'm soft floating
[.my2]
那就好 因为显然我这边

to, you know like, Frank and Rava,
[.my2]
还要软处理弗兰克和拉瓦

and there's gossip getting soft floated.
[.my2]
而且有人在传播谣言

By who?
[.my2]
谁

Uh, by the ether.
[.my2]
就 网民吧

I don't know.
[.my2]
我也不知道

Hey, hey, happy birthday, you old geezer.
[.my2]
对了 生日快乐 怪老头

Look, it's exciting.
[.my2]
你看 这事儿激动人心

This is gonna be great for you, Dad.
[.my2]
会对你有好处的 老爹

Mm-hmm. I'm excited.
[.my2]
我很激动

Waystar Royco is a family.
[.my2]
韦斯达·罗伊科是个大家庭

A family that spans four continents,
[.my2]
这个家庭横跨四大洲

50 countries, three divisions:
[.my2]
五十个国家 拥有三个部门:

Entertainment, News and Resorts.
[.my2]
娱乐部 新闻部和度假区部

Working together
[.my2]
协同合作

to provide a net that can hold the world,
[.my2]
共同编织成一张网络包罗世界

or catapult it forward
[.my2]
推动世界向前

to the next adventure!
[.my2]
致下一段征程

Joining Waystar Royco, you're joining
[.my2]
加入韦斯达·罗伊科

one of the most dynamic news and entertainment companies
[.my2]
就是加入世界上最具活力的

in the world.
[.my2]
新闻娱乐公司之一

Feel it!
[.my2]
用心感受

OK, how's everyone feeling?
[.my2]
好的 大家觉得怎么样

- Great! - Great!
[.my2]
-好极了  -很棒

Excellent!
[.my2]
很好

Hey. You in the room?
[.my2]
你在听吗

OK. Well, let's go out and give these kids
[.my2]
好 那这就出去给孩子们留下

the best day of their lives, huh?
[.my2]
最美好难忘的回忆吧

Feel it!
[.my2]
用心感受

- Feel it! - Feel it!
[.my2]
-用心感受  -用心感受

Hi!
[.my2]
你好

Hi, Doderick!
[.my2]
你好 道德里克

Hi!
[.my2]
你好啊

Good morning!
[.my2]
早上好

It's Doderick!
[.my2]
是道德里克

Whoo! It's me, Doderick!
[.my2]
是我呢 我就是道德里克

Hey, happy birthday!
[.my2]
生日快乐

Don't pull on my tail!
[.my2]
别拽我的尾巴

Don't hit Doderick!
[.my2]
别打道德里克

Hey!
[.my2]
喂

Quit it!
[.my2]
住手

Wait, OK. Please get off.
[.my2]
等一下 行吗 请下去

Can you fuck off?
[.my2]
能滚下去吗

Can you just get the fuck off?
[.my2]
给我滚下去

Ew!
[.my2]
呕

He's puking out of his eyes!
[.my2]
他的眼睛在呕吐

Protein spill.
[.my2]
蛋白质泄露而已

OK, this way, this way. Come on.
[.my2]
过来 过来 往这边来

Greg?
[.my2]
格雷格

Hi, Mom.
[.my2]
妈妈

How... Are you OK? How's it going?
[.my2]
你... 还好吗 工作怎么样了

Mom, sorry, but I sort of screwed up.
[.my2]
妈 对不起 我好像闯祸了

Well, not me, actually, but this kid.
[.my2]
其实不是我 而是那小孩

Greg.
[.my2]
格雷格

So, this kid smoked a joint in my car.
[.my2]
有个小孩在我车里抽了一根大麻

A kid.
[.my2]
小孩

Like this hitchhiker kid that I
[.my2]
就今早我接上的那个

picked up this morning, like earlier this morning.
[.my2]
搭便车的小孩 早些时候那会儿

'Cause it was raining and I didn't want...
[.my2]
因为那时在下雨 我不想...

I didn't want him to get sexually assaulted?
[.my2]
不想他被坏人性骚扰之类的

Greg.
[.my2]
格雷格

Before I could even say anything...
[.my2]
我还没说啥呢...

What the fuck?
[.my2]
你搞毛呢

Aggressively takes out...
[.my2]
他上车就点了一根...

Have you ever seen, like, so, a doobie?
[.my2]
就是你知不知道 那种 大麻烟

And the car smelled like skunk weed.
[.my2]
车里都是焦臭的大麻味儿

And then I guess I smelled like it.
[.my2]
我身上也是那味

And then they were just like,
[.my2]
他们就说

"Get all your stuff and go. "
[.my2]
"收拾东西滚蛋"

Greg.
[.my2]
格雷格

Did you even think for one second
[.my2]
你有没有想过告诉他们

to tell them who you are?
[.my2]
你是谁

No, I thought...
[.my2]
没有 我觉得...

I didn't wanna be an asshole
[.my2]
我不想当个混蛋

or get into it all.
[.my2]
也不想掺和进去

- OK. - I don't know.
[.my2]
-好吧  -我也不知道

Here's what you're gonna do.
[.my2]
你接下来这样做

You're gonna get a plane ticket to New York.
[.my2]
买张去纽约的机票

It's your Uncle...
[.my2]
是你伯伯...

Your Great-Uncle Logan's birthday,
[.my2]
大伯父洛根要过生日

and they're having a big party.
[.my2]
要办一个大型生日宴会

I'll call Marcia and tell her you're coming.
[.my2]
我会打给玛西娅说你要去

It's his birthday?
[.my2]
他要过生日吗

You're gonna go to the party.
[.my2]
你去参加派对

You're gonna get him a nice gift.
[.my2]
再送一份体面的礼物

And you're gonna look nice.
[.my2]
还要看着英俊潇洒

In a grown-up shirt and a grown-up blazer.
[.my2]
穿上成年人的衬衫和西装

A blazer?
[.my2]
西装

I'll let you know.
[.my2]
我告诉你怎么做

They're not gonna budge unless it gets to be a stupid number.
[.my2]
不给出一个大数目他们是不会让步的

What's a stupid number?
[.my2]
多大算大

What's stupid? A "badillion"? I don't know.
[.my2]
多大 数兆亿吗 谁知道

Because 120 is stupid. Am I wrong?
[.my2]
因为1.2亿够大了 不是吗

120 is a stupid number.
[.my2]
1.2亿是个大数目

But it's not really a money thing right now.
[.my2]
这已经不是钱的事情了

Mr. Roy, someone's here to see you.
[.my2]
罗伊先生 有人找您

- OK. Who's this? - Hi, Kendall Roy?
[.my2]
-好 谁找我  -打扰 是肯德尔·罗伊吗

Yeah, hi.
[.my2]
是我 你好

I was sent by Roman to burn some sage.
[.my2]
罗曼派我来烧点鼠尾草

Excuse me?
[.my2]
你说什么

It's auspicious.
[.my2]
求个好彩头

I'm a business alchemist.
[.my2]
我是个商业炼金师

It's a gift, from your brother.
[.my2]
这是你弟送你的礼物

Will it set off the smoke alarms?
[.my2]
会触发烟雾报警器吗

Not usually.
[.my2]
通常不会

Not usually?
[.my2]
啥叫通常

Hey, hey, motherfuckers!
[.my2]
嘿 混蛋们

- Roman. - My guy?
[.my2]
-罗曼  -我的人吗

Are you saging?
[.my2]
开始烧了吗

Well, we're concerned about the alarms.
[.my2]
我们担心这会触发警报

Ooh, right, yeah, the bad juju.
[.my2]
说得是啊 巫术

Now, I can use essential oils.
[.my2]
我可以用精油代替

Oh, I think just fuck off, thanks.
[.my2]
你可以滚蛋了 谢谢

How ya doing?
[.my2]
你最近咋样

Good. Good. Just finessing.
[.my2]
不错 我们正在商议对策

Mm. Finessing. Nice.
[.my2]
商议对策 很好

Bye.
[.my2]
再见

He's good.
[.my2]
他很不错

You OK, man?
[.my2]
你没事吧

OK? Yes, I'm OK. Obviously.
[.my2]
我吗 好啊 好得不行了

Why would you even ask that?
[.my2]
这还用问吗

I don't know. Just, you know.
[.my2]
不知道 问问而已

Here? Man, I'm so over it. I was a bad fit.
[.my2]
回来吗 早就翻篇了 我不适合这里

I was never a corporate cock-suck anyway.
[.my2]
我从来不是拍企业主马屁的料

Besides, I never made it this high in the fucking building!
[.my2]
更何况 我在这栋楼里从来没有爬到这么高

They stuck me in LA with Old Father Time right here.
[.my2]
他们把我丢在洛杉矶混日子

We were the pool boys, right, Frank?
[.my2]
咱们以前是泳池兄弟 对吗 弗兰克

Fuckin' banana cabana?
[.my2]
记得香蕉小屋吗

Good times.
[.my2]
都是美好时光

So, what's the bid?
[.my2]
目前竞价是多少

- What's the bid? - Mm-hmm.
[.my2]
-你问竞价吗  -对

Well...
[.my2]
这个...

What? That's commercially sensitive?
[.my2]
怎么 这还算商业机密了

I'm still on the board, man.
[.my2]
我可还在董事会呢 兄弟

Going 125.
[.my2]
要到1.25亿了

One-twenty-five?
[.my2]
1.25亿吗

- What? - Fuck!
[.my2]
-怎么了  -我去

What? High or low?
[.my2]
怎么 高了还是低了

- You're laughing. What? - No.
[.my2]
-你笑什么  -没什么

- For Vaulter, right? - Yeah.
[.my2]
-为了买沃尔特 对吗  -是啊

Bit of content and a brand name?
[.my2]
那个没啥内涵的商标吗

Bit of content and a brand name kinda's the whole game.
[.my2]
没啥内涵的商标就是精髓

- Isn't it? - Mm-hmm.
[.my2]
-不是吗  -好吧

What are you laughing at?
[.my2]
你到底在笑什么？

I don't know what I'm talking about.
[.my2]
我不知道我在说什么

You're gonna be captain of the ship soon enough.
[.my2]
反正你马上要当这艘船的船长了

- So I don't... - Shh.
[.my2]
-我不...  -嘘

Oh, shit.
[.my2]
糟糕

Sorry. Fuck you, man.
[.my2]
抱歉 去你妈的

Every intern on the street knows that you're stepping up.
[.my2]
街上的所有实习生都知道你要上位了

Seriously, congrats.
[.my2]
恭喜你 真心的

I'm just so pleased to be out of here.
[.my2]
能离开这里我实在太高兴了

This place was essentially a cage to me.
[.my2]
这里对我简直就像个牢笼

I should take off. Fuck it.
[.my2]
我该走了 管他妈的

Hey, congrats, man.
[.my2]
恭喜你 兄弟

Thanks for coming by.
[.my2]
谢谢你过来

Look at all this fuckin' bullshit!
[.my2]
瞧这胡诌八扯的地方

Mm, yes, mm, very serious, mm.
[.my2]
我很严肃的哦

Love you, brother.
[.my2]
爱你哦 老哥

Good.
[.my2]
很好

Right.
[.my2]
好

Just keep everything straight, OK?
[.my2]
把它们都摆正 明白吗

Good.
[.my2]
很好

By the way, we need another setting.
[.my2]
对了 还要加一套新餐具

Another family member is coming.
[.my2]
还有一位家庭成员要来

- Marcy. - What?
[.my2]
-玛西  -怎么了

I'm heading out, as ordered.
[.my2]
我要出去 定好了的

Great. Till 1:00...
[.my2]
好的 一点前回来...

Fine. But in here, yeah?
[.my2]
好吧 但惊喜就在这里 好吗

I don't want a fuckin' heart attack from the surprise.
[.my2]
我他妈可不想被吓出心脏病

And I don't want anyone in my face when I come out of the elevator.
[.my2]
我出电梯时 不想看到任何人朝我欢呼

Right. Distance.
[.my2]
保持好距离

Have them here. And, uh...
[.my2]
把他们安排在这 还有...

- What? - Not too loud.
[.my2]
-怎么了  -小点声

Do you want me to email you the exact details of the surprise?
[.my2]
你希望我把惊喜的精准细节发给你吗

Yeah?
[.my2]
想吗

- I'll see you later. - Yeah.
[.my2]
-待会儿见  -好

Right. Get your coat.
[.my2]
还有 穿好外套

Yeah, yeah.
[.my2]
知道了

Richard, get him his coat.
[.my2]
理查德 把外套递给他

Of course.
[.my2]
好的

- Just double-check. - OK.
[.my2]
-再仔细检查一遍  -好的

When were you gonna look at that speech?
[.my2]
你打算多久去审演讲稿

I'll be back by Sunday night so I'll look at his speech with him then, OK?
[.my2]
我周日晚上回来 到时候和他一起审 行吗

OK, but his office wants the poll numbers by the preekend.
[.my2]
但他那边要在前周末拿到民调数据

The "preekend"? What the fuck's a "preekend"?
[.my2]
"前周末" 这他妈是啥玩意儿

Preekend is Friday.
[.my2]
前周末就是周五

If he wants them by Friday, can he not say Friday?
[.my2]
那他不能直接说是周五吗

Thursday lunch through Friday afternoon is the preekend.
[.my2]
前周末是周四午后到周五中午

Oh, fine. Get Rennie to look at the numbers.
[.my2]
好吧 让蕾妮搞好数据

Shiv.
[.my2]
小西

This is a fuckin' disaster.
[.my2]
真他妈是场灾难

I got to strategize my gift.
[.my2]
我得好好挑礼物

What can I get him he'll love?
[.my2]
他会喜欢什么礼物呢

I don't know. My dad doesn't really like things.
[.my2]
不清楚 我爸没什么喜好的

He doesn't like things?
[.my2]
他没什么喜好吗

No, not really.
[.my2]
确实是这样

It needs to say that "I respect you,
[.my2]
这份礼物要表达出

but I'm not awed by you.
[.my2]
"我尊重你 但我并不怕你

And that I... I like you,
[.my2]
我还... 欣赏你

but I need you to like me before I can love you."
[.my2]
但我要你在我爱你之前 欣赏我"

So what says that?
[.my2]
所以选啥礼物好

Just, look, everything that you get him
[.my2]
听着 你买任何东西给他

will mean an equal amount of nothing,
[.my2]
都相当于没买

so make sure it looks like 10 to 15 grand's worth and you're good.
[.my2]
只要看上去价值一万到一万五就可以了

Will you come in here and help me?
[.my2]
你能进来帮帮我吗

Yes.
[.my2]
好

Please help me.
[.my2]
求你帮帮我

Yes. Get him a watch.
[.my2]
当然了 给他买块表吧

If we go stupid on the stock,
[.my2]
要是我们连股票也送

what does a really sexy package look like? Hmm?
[.my2]
这份诱人的福利礼包看着如何

He's probably illiquid, right?
[.my2]
他也许没有流动资金了 对吗

So, what, we throw in another ten million?
[.my2]
那我们要再投一千万吗

Might need to throw in a blow job, too.
[.my2]
没准还要再来一次跪舔

I'll throw in a blow job.
[.my2]
我来跪舔

I'll throw in a blow job.
[.my2]
我来跪舔

I'll throw in a reach-around.
[.my2]
还要让他高潮

Hell, I'll even cup his balls.
[.my2]
见鬼 我还要捏他的蛋

Dad.
[.my2]
爸

I thought you'd be in St. Barts by now.
[.my2]
你这会儿该到圣巴特岛[加勒比度假岛]了啊

- How's it goin'? - Good.
[.my2]
-一切顺利吗  -还不错

Uh, yeah. Fine. Good.
[.my2]
是的 挺好的

Uh, why are you...
[.my2]
你怎么...

Are we OK?
[.my2]
我们没事吧

Yeah, it's just some paperwork.
[.my2]
当然 就是些文件而已

What, ahead of the announcement?
[.my2]
怎么 发布会前还有吗

Putting Marcy on the trust. It's... bullshit.
[.my2]
我要把玛西纳为信托人... 破事一桩

I, uh, I just felt like checkin' in.
[.my2]
然后就想顺路过来瞧瞧

Oh. Yeah, fine.
[.my2]
是吗 好啊

- So this is just the trust? - Yeah.
[.my2]
-只是改信托人吗  -对

Doesn't affect me stepping up?
[.my2]
不会阻碍我升职吧

No, no, no, no, no. I think I told you about it.
[.my2]
不 不 不会的 我好像跟你谈过了

Is that...
[.my2]
这是...

Sorry, Dad, I'm kind of in the middle of...
[.my2]
抱歉 父亲 我这边正忙...

Do you need... Do I need to lawyer all this?
[.my2]
你需要... 需要我走法律形式吗

It's housekeeping.
[.my2]
一些家务而已

Fine. Yeah. Yeah. Marcy's fine by me.
[.my2]
好吧 我对玛西没意见

I mean, the others might not feel the same, but...
[.my2]
我是说 那几个家伙可能不这么想 但...

I'll deal with that.
[.my2]
我会处理的

So, I'll see you in...
[.my2]
那我们...

Yeah, look, Dad, on lunch.
[.my2]
对了 爸 午饭这事

I really want to be with you, but the deal...
[.my2]
我很想陪你的 但是生意...

- Son. - You know.
[.my2]
-儿子  -你知道的

It's your call.
[.my2]
你自己决定吧

Just priorities.
[.my2]
分清主次

There'll be plenty more.
[.my2]
这种事以后只会更多

Uh-oh. Wheat.
[.my2]
麦穗的故事 记得吗

Bye, Frank.
[.my2]
再见 弗兰克

All right, amigo.
[.my2]
再见 老朋友

I have five farms, and underneath all my farms
[.my2]
我有五个农场 而这些农场下面

runs a big, giant aquifer that's like an underground lake.
[.my2]
有个非常大的蓄水池 像地下湖那种

- That's so cool! - I have pumping rights.
[.my2]
-真酷啊  -我有抽水权

That means I get to take the water.
[.my2]
就是说我能拥有那些水

- That's so cool! - And it's very important
[.my2]
-太酷了  -还相当重要呢

because someday water's gonna be more precious than gold
[.my2]
因为有一天 水会比黄金还珍贵

and people are gonna kill each other to try to get that water.
[.my2]
人们会互相残杀 只为得到水

Oh, hey, hey, Con, don't, don't.
[.my2]
悠着点 康纳 别这样

- Don't listen to him. - Right, right, sorry.
[.my2]
-别听他的  -我知道 抱歉

But I'm gonna have the water.
[.my2]
但我会拿到水的

And I'll share with you.
[.my2]
然后就分享给你

- Hi. - Hi.
[.my2]
-你好  -你好

- How are you? - Good.
[.my2]
-你怎么样  -不错啊

- How are you? - Good. You look great.
[.my2]
-你呢  -很好 你看起来棒呆了

- What a beautiful color. - Thanks. Same.
[.my2]
-颜色真漂亮  -谢谢 你的也很美

- Thank you. - Love that.
[.my2]
-谢谢  -我很喜欢

Thanks.
[.my2]
谢谢

- Hi, Tom. - Hey, Marcia, how are you?
[.my2]
-汤姆  -玛西娅 最近好吗

- Nice to see you. - Nice to see you.
[.my2]
-真高兴见到你  -我也很高兴见到你

- How are you? - Very good.
[.my2]
-你怎么样  -非常好

Hey, Global Tom. How you shaking?
[.my2]
环球汤姆 你还好吗

You still fucking shit up for us?
[.my2]
还在为我们搞事吗

Still cleaning up your mess, pal.
[.my2]
还在收拾你的烂摊子 伙计

Yeah, right.
[.my2]
是啊

- Hey, sis. - Hi.
[.my2]
-你好啊 老妹  -好啊

Politics still boring the living shit out of you?
[.my2]
政治还让你无聊到死吗

Yeah, you know, I'm burying the bodies, counting the cash.
[.my2]
当然 就埋埋尸体 数数钞票罢了

Look at you. You like, you know, an actual human person.
[.my2]
瞧瞧你 还挺像个活人的

Well, thanks, buddy.
[.my2]
谢了 老哥

- Hi.  - Oh, what is that?
[.my2]
-好  -这什么味儿

Date Rape by Calvin Klein?
[.my2]
CK的"约会强奸"吗

Yeah, you wish.
[.my2]
你想得美

"You wish"?
[.my2]
"你想得美"

- Mr. Roy!  - Mr. Roy, please!
[.my2]
-罗伊先生  -请您看这 罗伊先生

Mr. Roy. Over here. One shot, please.
[.my2]
罗伊先生 看这里 就照一张

Say, guys, can we back off?
[.my2]
伙计们 能不能退后

- How 'bout a smile? - Guys, back off. Private event.
[.my2]
-笑一个怎么样  -伙计们 退后 这是私人活动

Logan, Logan, you going today? Is that right? Is that right?
[.my2]
洛根 洛根 今天您要出席 对吗 是吗

- Back off, please. - Fuck off.
[.my2]
-请退后  -滚边儿去

- Handle that, will ya?  - Just one shot!
[.my2]
-搞定他们 行不  -照一张就好

Mr. Roy.
[.my2]
罗伊先生

Hi. Hello. Hello there.
[.my2]
你好 你好啊

Can I help you, sir?
[.my2]
需要帮助吗 先生

Yeah, I'm actually... I'm actually here to see you.
[.my2]
是的 我... 其实我是来找你的

Get your hands back!
[.my2]
把手放背后

Who are you?
[.my2]
你是谁

- What are you doing? - Greg! I'm Greg!
[.my2]
-你要做什么  -格雷格 我叫格雷格

I'm Marianne's Greg. Your nephew?
[.my2]
我是玛丽安家的格雷格 我妈是你外甥女

- You know this guy?  - My Mom called Marcia
[.my2]
-你认识这人吗  -我妈给玛西娅打了电话

and I talked to that guy and he said that I could go up.
[.my2]
我和那人说了 他说我可以上去

- We're good? - Right.
[.my2]
-没事了吗  -对

I didn't know you were coming.
[.my2]
我不知道你要来

- Yeah, you did. - Sorry about that, guy.
[.my2]
-你知道吧  -刚才抱歉了 伙计

- I think you did. - You all right?
[.my2]
-我觉得你应该知道  -你还好吧

- Sorry about that. - I hope it's OK.
[.my2]
-不好意思了  -希望没事

I wanted to say happy birth...
[.my2]
我想跟你说生日快...

Happy birthday and many happy returns.
[.my2]
祝你生日快乐 长命百岁

Oh, thank you.
[.my2]
谢谢

I suppose you better come up.
[.my2]
跟我一起上楼吧

He's a very good bodyguard.
[.my2]
他是个尽职尽责的保镖

Folks, he's back!
[.my2]
各位 他回来了

He's back. Find a place. Hide for the surprise. Come on.
[.my2]
他要到了 藏起来给他个惊喜 快

Oh, we're not surprising him, are we?
[.my2]
我们真要给他个惊喜吗

- Yeah.  - Oh, he's gonna love this.
[.my2]
-没错  -他肯定"爱死了"

Think last time I surprised him,
[.my2]
上次我给他一个惊喜

he took a swing at me.
[.my2]
他回我一记重拳

You might know this, but I got a little bit of help,
[.my2]
你可能已经知道了 我得到过您的帮助

and I got onto the international management training program?
[.my2]
我参加了管培生的国际项目

The theme park tour?
[.my2]
在主题公园实习

And I was very into it?
[.my2]
我也算很投入

And... I got sick.
[.my2]
可是... 那天我病了

Out of Doderick's eyeholes.
[.my2]
吐了布偶狗一眼睛

Surprise!
[.my2]
生日惊喜

Great. Excellent. Wonderful.
[.my2]
好 很棒 太妙了

Go ahead. Go ahead.
[.my2]
出去 出去

Hi. Hi.
[.my2]
你们好

OK. OK. Give me room. Give me room.
[.my2]
行了 行了 腾个地方 腾个地方

Thank you. Thank you. What a surprise.
[.my2]
谢谢 谢谢 真是惊喜啊

- Marcia. - What?
[.my2]
-玛西娅  -怎么

What did I say? I said nobody by the elevator.
[.my2]
我怎么嘱咐你的 我说了不要等在电梯口

And what do I find? Everybody's by the elevator.
[.my2]
结果呢 每个人都等在电梯口

- It's a surprise. - Oh, a surprise.
[.my2]
-是个惊喜啊  -真"惊喜"

Give me that.
[.my2]
给我吧

In the office, please.
[.my2]
请送到办公室去

Connor, Primo! How are you?
[.my2]
康纳 老大 你好吗

Good. Excellent, Pa. Here you go.
[.my2]
不错 很棒 老爸 送给你

Roman! Romulus!
[.my2]
罗曼 罗慕路斯

Look at you! You look fantastic!
[.my2]
瞧瞧你 看起来棒极了

Yeah, of course.
[.my2]
那是自然

Happy birthday.
[.my2]
生日快乐

Siobhan. Sweetheart.
[.my2]
西沃恩 亲爱的

Happy birthday.
[.my2]
生日快乐

Where's Tom?
[.my2]
汤姆呢

He's here. He's just there.
[.my2]
他在这 就在这

Oh, well, never mind.
[.my2]
好吧 当我没问

Everybody, this is... Craig, by the way.
[.my2]
各位 顺带一提 这位是... 克雷格

Cousin Craig.
[.my2]
克雷格表弟

"Craig"? It's Greg. N-No?
[.my2]
"克雷格" 是格雷格吧 不是吗

Yeah. Greg.
[.my2]
是 是格雷格

People sometimes, like, mistakenly call me Craig, too,
[.my2]
人们有时会叫错 叫成克雷格

so I'll answer to both.
[.my2]
所以叫哪个我都应

Here. This is just a token of my very
[.my2]
这是我的一点心意

real and enduring admiration, in the hope...
[.my2]
想表达我对您的真挚崇敬...

Kendall?
[.my2]
肯德尔

You came?
[.my2]
你来了

Yeah, of course.
[.my2]
是的 当然

Happy birthday, Dad.
[.my2]
生日快乐 爸

- Hey, Marcy.- Hi.
[.my2]
-你好 玛西  -你好

- How are you?- Big day.
[.my2]
-你好吗  -大喜的日子

Congratulations... you bastard.
[.my2]
恭喜了... 你这混球

- Congratulations. Good luck.- Thanks.
[.my2]
-祝贺你 祝你好运  -谢了

Hey. Hey, Kendall.
[.my2]
你好 肯德尔

- How's it goin'?  - So! What's the news?
[.my2]
-过得如何  -有什么新消息吗

Yeah, good, good. We're at the one-yard line.
[.my2]
一切顺利 只差临门一脚

I'm just gonna... This is important.
[.my2]
我得接一下... 这很重要

Uh, sorry, guys, I'll be right back.
[.my2]
抱歉了 各位 我很快回来

Excuse me. Hello.
[.my2]
抱歉 你好

I hear you went down? Did you go down?
[.my2]
我听说你遇到麻烦了 真的吗

Oh, yeah, I did.
[.my2]
是啊 没错

Not so good.
[.my2]
很糟糕

It's a shitshow.
[.my2]
一团糟

Just gotta get somewhere quiet.
[.my2]
我找个安静的地方

Yeah, I got news.
[.my2]
我有新消息

Hey, talk to me.
[.my2]
快说

Yeah, PPG Bank have got their nose in,
[.my2]
PPG银行闻风而动

might be rustling up another bid.
[.my2]
可能有别家参与竞标

Word's out. We gotta move. What do you wanna do?
[.my2]
已经传开了 咱们得行动了 你想怎么办

I'm gonna call you back in five.
[.my2]
五分钟后打给你

- I'm not losing this deal.  - All right.
[.my2]
-这笔交易我志在必得  -好吧

We call PPG, we offer to cut them in on the financing
[.my2]
联系PPG 我们可以在融资上给他们让利

if they make the other bid fuck off.
[.my2]
只要他们把另一家干掉

Great idea, Ken, great idea.
[.my2]
好主意 肯 好主意

Boom. Kendall takes over. Boom. Acquisition.
[.my2]
砰 肯德尔掌权 砰 搞定收购

That's how it's done.
[.my2]
干净利落

Hey, you know, I wanted to talk to you about Tom.
[.my2]
我想跟你谈谈汤姆的事

He thinks he might be ready for the parks,
[.my2]
他差不多准备好接手主题公园了

- you know, globally and...  - Look, Dad,
[.my2]
-全球业务啥的...  -老爸

we should get this somewhere ambient.
[.my2]
我们该聊点轻松愉快的话题

- You want to?  - Connor. How are you?
[.my2]
-意下如何  -康纳 你好吗

- How's the ranch?  - Oh, perfect.
[.my2]
-牧场怎么样  -完美

The light pollution is practically zero,
[.my2]
那里基本不存在光污染

so, you know, that's nice.
[.my2]
所以 你懂的 很棒

- Hey.  - Oh, wonderful.
[.my2]
-给你  -真好

What is it?
[.my2]
这是什么

- Well...  - Oh, yes, yes.
[.my2]
-这是... -对 就是这个

It's a... It's a goo.
[.my2]
这是一个... 粘团

It's a fucking goo?
[.my2]
就他妈是个粘团

It's perfect.
[.my2]
很完美

It's sourdough starter.
[.my2]
这是酸酵头

Amazing.
[.my2]
棒呆

I thought that you might like to make something.
[.my2]
我觉得你可能想做点儿面包啥的

Ah, great.
[.my2]
很棒

Yeah, OK, you shouldn't have opened it. OK?
[.my2]
那啥 你不该打开 好吗

Never mind, forget it.
[.my2]
算了吧 罢了

It was an idea. I thought you might like it.
[.my2]
我就是突发奇想 以为你会喜欢

I do. I do.
[.my2]
喜欢 我喜欢

I just don't know what the fuck it is.
[.my2]
我只是不知道这是啥几把玩意儿

It's sourdough starter
[.my2]
是酸酵头

to make bread without yeast... The old way.
[.my2]
不用酵母做面包... 是古法

Oh. Oh, OK.
[.my2]
原来如此 好吧

Old bread. Thank you.
[.my2]
古法面包 谢谢你

- It's very kind. Thank you very much - You bet.
[.my2]
-这很棒 非常感谢  -客气

Be nice.
[.my2]
和气点

How's it lookin'?
[.my2]
事情怎么样了

Looking good.
[.my2]
一切向好

I'll keep you posted.
[.my2]
我会随时向你汇报

I just checked with Frank, and the holidays mean
[.my2]
我刚问了弗兰克 年底的节假日期间

the board might be kinda hard to get together,
[.my2]
董事会成员可能到不齐

so if it's cool I've scheduled a call at 4:00?
[.my2]
所以如果你方便 我定了四点开董事会

Then we can issue the release?
[.my2]
到时我们可以宣布

You did?
[.my2]
你定了吗

Yeah. Is that OK?
[.my2]
是的 行吗

You go on.
[.my2]
你忙

I'm not going.
[.my2]
我不去

- Hey. Give Daddy a hug.  - Hi, Daddy.
[.my2]
-来跟爸爸抱抱  -午安 爸爸

Sorry we're late.
[.my2]
抱歉 我们迟到了

No, no, you're not even. Don't worry.
[.my2]
不 没有 完全没有 别担心

Twenty's the margin of error.
[.my2]
二十分钟内都不算晚

Hey, sorry I haven't Skyped with you guys in a couple days.
[.my2]
抱歉我这几天都没跟你们视频

I've been super busy. You feel good?
[.my2]
我太忙了 你们还好吗

- I'm good.  - OK.
[.my2]
-还不错  -很好

You see Isla up there? Your friend Isla?
[.my2]
看到那边的艾拉了吗 你们的朋友艾拉

You guys wanna go see her, maybe make a
[.my2]
你们要不要去跟她玩

drawing for Grandpa for his birthday?
[.my2]
给爷爷画张像当生日礼物

Sorry, one second.
[.my2]
抱歉 稍等

It's OK.
[.my2]
没关系

I got your message. That's fine.
[.my2]
我收到你的信息了 没关系

Oh, yeah. Yeah.
[.my2]
对 没错

It's just as this all goes through,
[.my2]
这个档口事情太多

next two weekends will be kinda crazy.
[.my2]
接下来两周会忙疯的

But then once it's done, it would be great if...
[.my2]
但只要尘埃落定 要是能...

Yeah, no, it's fine. Bank the weekends, spend them later.
[.my2]
不 没事的 好饭不怕晚

OK. I can come up to you.
[.my2]
好的 我可以去找你

Maybe if you want, we could grab dinner for the hand-over?
[.my2]
如果你愿意 我们交接孩子的时候一起吃个饭

Ugh. What, like two weekends? Um...
[.my2]
呃 孩子要在我这两周吗...

No? Are you... Is that not...
[.my2]
不行吗 难道你... 你不会是...

Are you seeing someone?
[.my2]
你在交往别的人吗

Yeah.
[.my2]
是的

I am.
[.my2]
没错

And I'm just hoping this one doesn't leave coke smeared all over the kids' iPads.
[.my2]
我只希望这次没人把可卡因洒在孩子们的平板电脑上

All right, that's fair.
[.my2]
好吧 要求很合理

- Oh, God.  - It was three years ago, but...
[.my2]
-天呐  -那是三年前的事了 但...

Kendall, I'm fucking with you.
[.my2]
肯德尔 我逗你玩呢

It's OK, it's OK. You're good.
[.my2]
没事 没事的 没问题

This is a big day. Coronation day.
[.my2]
这是你大喜的日子 加冕日

- Yeah.  - Hey, you deserve this.
[.my2]
-对  -这是你应得的

Seriously. After everything.
[.my2]
我说真的 你经历了这么多

Guys, lunch in ten.
[.my2]
各位 十分钟后开饭

Listen, just two minutes before lunch in the sitting room.
[.my2]
听我说 趁着还没开饭 到起居室来 我有事要说

Kids. Can you give me two minutes.
[.my2]
孩子们 能给我两分钟吗

Got a speech.
[.my2]
有个演讲

- So, Uncle Logan, can I... - Not now.
[.my2]
-洛根伯伯 我能...  -待会儿再说

Sorry, sir. Sir, sir, just, I need your attention, please.
[.my2]
不好意思 先生 先生 我需要您听我说

About the... what I was talking about earlier,
[.my2]
关于... 我之前所说的

the management training program?
[.my2]
管理培训计划

I need to get back in.
[.my2]
我需要回去继续参加培训

- You're out? - Yes.
[.my2]
-你退出了吗  -是的

There was an issue, and I talked to my mom
[.my2]
出了点小问题 我跟我母亲说了

who talked to my grandfather and said that I can come to you
[.my2]
她与我祖父提了一下 然后让我来找您

and... and iron it out.
[.my2]
就能... 解决这个问题

I'll do anything for my brother.
[.my2]
我愿意为兄弟两肋插刀

Oh, that's... that's nice.
[.my2]
那... 那太好了

And I'm gonna work 100%...
[.my2]
我会拼尽全力...

All he needs to do is just ask.
[.my2]
他只用求我就好

My grandfather?
[.my2]
我的祖父吗

I mean, you two don't talk so much.
[.my2]
我是说 您二位交集甚少

Right?
[.my2]
对吧

Anything.
[.my2]
两肋插刀

Just get him to ask me.
[.my2]
只要他来求我

Fuck!
[.my2]
操

- Dad. - Yes.
[.my2]
-爸  -什么事

Yeah, what's the deal?
[.my2]
你要说什么事

So...
[.my2]
所以...

On the family trust, which will decide the situation
[.my2]
假如我不幸去世 家族信托

in the event of my unlikely demise,
[.my2]
将掌控家族大局

I'm going to add Marcy to myself and you four.
[.my2]
我要让玛西取代我 和你们四个一道

Whoa. OK.
[.my2]
是吗

And my seat also to go to her on my death.
[.my2]
在我死后 我的位置要留给她

What? Wait, that gives her double voting weight.
[.my2]
什么 等下 这就给了她双份投票权了

Uh-huh. So I've got some paperwork...
[.my2]
没错 我这里有几份文件...

Whoa, whoa, whoa. What?
[.my2]
等等 啥

So Marcia will have two votes when you...
[.my2]
在你那啥之后玛西娅有两票...

- "If" he...  - Well, no, Rome, it's not an if.
[.my2]
-"假如"他...  -小罗 才不是假如

Well, excuse me if I don't want him to...
[.my2]
抱歉啊 要是我不想让他...

Well, it's not really what we want in this case, Rome.
[.my2]
小罗 这不是他的真正意图

Kendall's already signed, but if I can get you all to...
[.my2]
肯德尔已经签字了 但如果我能让你们全员...

Two votes? I don't think I was aware of that when I...
[.my2]
两票 我觉得我当时应该是没注意到...

Read the small print, asshole.
[.my2]
混球 那你倒是读附属细则啊

I mean, this looks...
[.my2]
这看起来...

I'm gonna have to talk to my lawyers, just for all the implications.
[.my2]
我要跟我的律师谈谈 弄清各项内涵

Of course.
[.my2]
请便

Just to get the full picture.
[.my2]
看清全局

Sure, take a beat.
[.my2]
当然 三思而后行

But look, I love the bread... goo...
[.my2]
但听着 我喜欢那面包... 还是粘团...

But this is the present I really want.
[.my2]
但这才正是我最想要的礼物

By 4:00, good?
[.my2]
四点前决定 行吗

Oh, also, I already mentioned to Kendall,
[.my2]
还有 我已经和肯德尔提过了

despite the chatter and all things considered,
[.my2]
除唠唠叨叨之外 其他的事都考虑到了

I'm going to give it a couple of years.
[.my2]
我会再坚持几年

As in?
[.my2]
做什么

I'll stay in situ.
[.my2]
我会继续主持大局

As chairman, CEO, head of the firm.
[.my2]
仍然担任主席 总裁 公司的一把手

Dad, wh... you... you what?
[.my2]
爸 你... 说啥

I just said, son,
[.my2]
我才说完 我的儿

or were you not listening, as usual?
[.my2]
还是说你一如既往地没听我说话

But I'm... You're not... What?
[.my2]
但我才是... 你不是... 什么

It's no big deal. I'm staying on.
[.my2]
没啥大不了的 我要继续主持大局

- We can discuss the details. - You didn't tell me.
[.my2]
-细节好商量  -你没跟我说过

We can announce you're in pole position,
[.my2]
咱们能对外公布你仍留在决策圈

pending events, a move up or whatever.
[.my2]
未定事项啊 升职什么的

- "Pending events"? - OK, come on, let's eat.
[.my2]
-"未定事项"  -行 不说了 吃饭吧

Dad, wait.
[.my2]
爸 等一下

Oh, fuck!
[.my2]
我操

I don't know what you're fucking laughing about!
[.my2]
我不知道你他妈有什么好笑的

I'm not even laughing. What?!
[.my2]
我根本没笑 搞毛呢

Fuck. What the fuck.
[.my2]
操 操他妈的

I mean, he can't just... Right?
[.my2]
他不能就... 对吧

He's gonna blow the firm's credibility.
[.my2]
公司的声誉都得被他玩坏

Did he look OK to you?
[.my2]
你们觉得他还撑得下去吗

Oh, come on! Ken, this is typical. It's Dad.
[.my2]
得了 肯 这是爸典型的作风

I'm out, OK?
[.my2]
我不干了 总成吧

I'm not playing.
[.my2]
不玩了

Whatever you three decide, goes.
[.my2]
不管你仨如何决定 悉听尊便

- Goodbye. - Connor.
[.my2]
-拜拜了您哪  -康纳

On the trust, I refuse to play.
[.my2]
我拒绝在信托上玩玩闹闹

I don't want to engage. I'm water, I flow.
[.my2]
我不想趟这浑水 我是清水 我流走还不行么

This doesn't stand, right?
[.my2]
这根本站不住脚的 对吧

I...
[.my2]
我...

Oh, fucking shrug? You're fucking shrugging me?
[.my2]
还他娘的耸肩 耸你妹的肩啊

Are you texting? Dude, what are you...
[.my2]
你发短信呢是吧 哥们 你干什...

Hey, hey!
[.my2]
说你呢

- Are you telling? - Are you fucking serious?
[.my2]
-你当长舌妇呢  -你他娘的那么认真干什么

- What, are you 14? Private. - Hey, this stays in here.
[.my2]
-啥 你14岁小毛孩吗  -这件事绝不能外传

- OK? This is a lockdown. - We all need advice, man.
[.my2]
-懂吗 这件事禁止外传  -我们都需要心理咨询 伙计

Advice? What? You're gonna give a double vote
[.my2]
咨询 啥玩意儿 你要把两票

to a power-hungry maniac
[.my2]
交给一个权利控制狂吗

who will do fuck-knows-what with it
[.my2]
这人他妈指不定能弄出什么幺蛾子

because she's got our dad's dick in some Super Max pussy grip
[.my2]
就因为她用她的大逼紧紧夹住了爸的屌

and she's juicing him before he croaks?
[.my2]
在他胡言乱语前给他灌了什么浆

Guys? Lunch is coming up.
[.my2]
大家伙 饭好了

Sorry, I don't mean to be strict.
[.my2]
抱歉 我不想这么严格的

Can you give us a minute, please? Thank you.
[.my2]
让我们单独待会儿 好吗 谢谢

Hey. So... you fucked me.
[.my2]
所以说... 你阴了我一道

I changed my mind, Kendall.
[.my2]
我改主意了 肯德尔

When? When, exactly.
[.my2]
多久 多久改的

'Cause it feels like you fucked me.
[.my2]
因为我觉得你就是阴了我

It's me. It's mainly me.
[.my2]
主要还是在我

But you... Three years ago,
[.my2]
但你... 三年前

you were still in the nuthouse.
[.my2]
你还在精神病院

Rehab, Dad. It's called rehab.
[.my2]
疗养 爸 那叫疗养

And I'm in recovery.
[.my2]
而且我已经痊愈了

It's all good.
[.my2]
都不是事

I'm just concerned you might be soft, as yet.
[.my2]
但我担心你会变软骨头

S-Soft? Are you kidding?
[.my2]
软骨头 你开玩笑吧

I did a fucking year in Shanghai.
[.my2]
我他妈在上海待了一年

I hear you let the guy from the website trash-talk you
[.my2]
我听说你任由网站公司那男的灭你士气

and you just let him come.
[.my2]
你还毫无还击之力

It's not a website.
[.my2]
那不是网站

And I was being professional.
[.my2]
我也只是想专业点

I hear it played weak. Conflict averse.
[.my2]
我听说谈判很失败 逆向冲突

I wasn't about to get into a fucking big dick competition.
[.my2]
我又不是卷进了什么"比谁屌大"的竞争

OK?
[.my2]
好吗

I hear you bent for him.
[.my2]
听说你向他低头了

Wha... I what?
[.my2]
什... 我什么

I hear you bent for him and he fucked you.
[.my2]
听说你低头求他 却反被搞了

Well, no, actually.
[.my2]
其实并没有

I know that you've read a lot of books
[.my2]
我知道你读了很多

about business management and this and that,
[.my2]
关于商务管理的这样那样的书

but you know what?
[.my2]
但你猜怎么着

What?
[.my2]
怎么着

Sometimes it is a big dick competition.
[.my2]
有时候这就是一场比谁屌大的竞争

OK. OK. So that's it?
[.my2]
行 所以就这样了吗

So I should have shouted at some guy, but I didn't.
[.my2]
所以我本该冲他们大喊 但我没有

So you've ripped up 18 months of corporate strategy?
[.my2]
于是你就撕毁了18个月的合作战略吗

And you never lawyered the trust change.
[.my2]
你也别想染指信托改动

I trusted my father. That's a black mark?
[.my2]
我相信我父亲 这也能成了污点

It's an accumulation.
[.my2]
日积月累吧

You left the room. The deal.
[.my2]
你离开了房间 谈生意的那间

To come to my Dad's fucking birthday party
[.my2]
来给我爸过他妈的生日

'cause we don't know how many more there'll be!
[.my2]
因为天知道你还能过几个生日

Sorry.
[.my2]
对不起

So come on.
[.my2]
告诉我吧

When will you be ready?
[.my2]
你要多久能准备好

To step down?
[.my2]
下任

I don't know.
[.my2]
我不知道

Five?
[.my2]
五年吧

Five years?
[.my2]
五年

Ten?
[.my2]
十年吧

Ten! Dad? Seriously!
[.my2]
十年 爸 开玩笑吧

It's my fuckin' company.
[.my2]
这他妈是老子的公司

Yeah, it is your fucking company, and you know what?
[.my2]
没错 这他娘的是你的公司 但你猜怎么着

You're running it into the fucking ground.
[.my2]
你快要把它带到阴沟里了

You spend all your time on costs...
[.my2]
你一辈子都耗在了砸钱上...

Where's the vision? You're off the beat.
[.my2]
你的远见呢 你已经落后了

Where's the growth? All our graphs go down. All of them.
[.my2]
增益呢 数据全面下降 无一幸免

Is that why you're paying a billion dollars for a gay little website?
[.my2]
所以你要把十亿砸进一个破袖珍网站吗

It is not a fucking website!
[.my2]
都他娘的说了不是网站

It's a portfolio of online brands and digital video content
[.my2]
这是一个在线品牌及数字视频的组合产品

and it's part of an upstream investment strategy
[.my2]
如果你让我放手一搏 这也是能挽救

to save us, if you'll just let me.
[.my2]
我们公司的上游投资策略

Do you want to hit me, is that it?
[.my2]
你想打我 是吧

Huh?
[.my2]
对吧

Go on.
[.my2]
来呀

Go on.
[.my2]
来呀

Give it your best shot.
[.my2]
你使出吃奶的劲儿来

Dad, come on. What are you doing?
[.my2]
爸 别这样 你在干嘛

Are you gonna fuckin' cry?
[.my2]
你他娘的要哭不成

Kendall, are you fuckin' crying?
[.my2]
肯德尔 你他妈在哭鼻子吗

You know, this has been floated already?
[.my2]
你知道局势已经漂浮不定了吗

There's fucking paps outside. I'm getting asked for quotes.
[.my2]
外面什么样的说法都有 总有人来找我证实

Fuck them.
[.my2]
操他们的

Yeah, 'course, "fuck 'em."
[.my2]
是 当然 "操他们的"

Great, great media strategy, Dad.
[.my2]
牛 牛逼的媒体策略 爸

Great business strategy.
[.my2]
牛逼的商务策略

- The world is changing... - Oh, yeah, yeah, yeah, yeah.
[.my2]
-时移事易...  -对对对

Yeah, everything changes.
[.my2]
万事万物都在变化

The studio was gonna tank when I bought it,
[.my2]
我买工作室那会 它就快破产了

everyone was gonna stay home with video tapes.
[.my2]
人人都想待在家里看录像

But guess what? No! They wanna go out.
[.my2]
但你猜怎么样 并不是 大家都想出门找乐子

No one was gonna watch Network,
[.my2]
没人看什么电视网

except you give it zing and they do.
[.my2]
除非你来点刺激的 他们就乐意看了

You make your own reality.
[.my2]
创造你自己的现实吧

And once you've done it, apparently,
[.my2]
而一旦你成功了 显然

everybody's of the opinion it was all so fucking obvious.
[.my2]
每个人的观点都他娘的这么显而易见

Lunch!
[.my2]
开饭

Come on. Find your places. Sit.
[.my2]
快来 找好位置 坐下

Please give me my seating plan.
[.my2]
请把座位图递给我一下

This is confusing. Sorry.
[.my2]
我有点弄混了 不好意思

She was drunk and sitting in Gore Vidal's lap.
[.my2]
她喝多了 坐到了戈尔·维达尔的腿上

She's very funny.
[.my2]
她很风趣

- Your mom's very funny. - Who's Gore Vidal?

[.my2]
你妈妈特别风趣  -戈尔·维达尔是谁

She's the one, you know, with the hair, and she usually wears the clothes?
[.my2]
她就是那个 你知道 长发披肩 老是穿着那种衣服的那个

- Yeah. - Yeah.
[.my2]
-是的  -是的

Yeah, no, I remember your daughter.
[.my2]
是啊 不 我记得你女儿

Marcy. This was delicious. Thank you.
[.my2]
玛西 很好吃 谢谢你

Thank you.
[.my2]
谢谢

The whole day. Really thoughtful.
[.my2]
今天的安排都很用心

It's been great.
[.my2]
都很棒

Thank you very much.
[.my2]
十分感谢

You're a suck-up.
[.my2]
你个马屁精

I'm happy to have you.
[.my2]
很开心能邀请你

"You are so swell, Double Vote Power Mom!"
[.my2]
"你太棒了 能投两票的妈妈"

You know what? Fuck you.
[.my2]
你他妈给我滚

If you'll excuse me...
[.my2]
打扰下 我说两句...

Logan Roy.
[.my2]
洛根·罗伊

Born in Dundee, Scotland, 80 years ago today,
[.my2]
八十年前的今天 他生于苏格兰的丹地

raised in Quebec by an uncle with a print shop and a few advertising billboards
[.my2]
叔婶在魁北克把他抚养长大 叔叔有家印刷厂和几个广告牌

and an aunt with a herd of cattle.
[.my2]
婶婶养着一群牛

Logan himself has made a decent way for himself these past 60 years.
[.my2]
洛根在过去的六十年中给自己拼出了一条路

Fifth largest media conglomerate in the world.
[.my2]
建立起世界第五大传媒帝国

A pal to prime ministers, a truth teller to presidents.
[.my2]
他是首相的哥们儿 和总统们无话不谈

He's tough, he's wily,
[.my2]
他坚韧 他老谋深算

but he's always true to his word.
[.my2]
但他总是信守诺言

I arrived to give him legal advice 30 years ago,
[.my2]
我三十年前开始做他的法律顾问

and I never got out the door.
[.my2]
至今也没离开

And since that day, I'm proud to call him a friend.
[.my2]
时至今日 我很骄傲与他为友

So, let's raise a toast.
[.my2]
那么 举杯吧

Logan Roy.
[.my2]
敬洛根·罗伊

Logan Roy.
[.my2]
敬洛根·罗伊

Thank you.
[.my2]
谢谢

So, I think it's time to play the game.
[.my2]
我们也该玩那个游戏了

We're playing the game?
[.my2]
要玩那个游戏吗

Well, yes.
[.my2]
没错 是的

It's my birthday, so yes, we're playing the game.
[.my2]
今天是我的生日 当然要玩

Do we have to play the game?
[.my2]
我们必须玩那个游戏吗

What's the game?
[.my2]
那个游戏是什么

What's the game?
[.my2]
到底是什么

Nice day! You OK, Greg?
[.my2]
天不错 你还好吗 格雷格

Sure. I'm not... Is there room in there?
[.my2]
还好 我不... 车里还有地方吗

Hop in.
[.my2]
上车

I'm sorry if it's a crush.
[.my2]
有点挤 抱歉

It's fine.
[.my2]
没关系

I was just talking to my grandpa.
[.my2]
我跟我祖父通了话

And he said happy birthday.
[.my2]
他跟你说生日快乐

Did he?
[.my2]
他说了吗

Well, no, not technically,
[.my2]
好吧 理论上 他没说

but he's aware it's your birthday.
[.my2]
但他知道你过生日

But it occurred to me, talking to him,
[.my2]
但跟他通话后 我突然想到

that him having his seat on the holding company still,
[.my2]
他仍在控股公司有席位

from historically,
[.my2]
这是历史遗留问题

now, that must be suboptimal, in some ways.
[.my2]
某种程度上讲 他不是最佳人选

But if I could... if he was willing to give his seat
[.my2]
但如果我可以... 如果他愿意把这个位置

to someone a bit more perspicacious,
[.my2]
让更精明的人来接替

someone who could learn the ropes, running a theme park, say.
[.my2]
让更熟悉门道的人来运营这些主题公园

Running the parks?
[.my2]
运营这些游乐场

Just a little guy. Learning, you know?
[.my2]
交给年轻人 不断学习

I mean, could that be...?
[.my2]
那个人选...

You scratch my back, I...
[.my2]
你要是帮我 我...

I'm not gonna say I could scratch yours.
[.my2]
虽说我并不能回报你什么

It's be too considerable of a space.
[.my2]
因为这个范围太大了

But is there an angle there, perhaps?
[.my2]
但... 也许你能考虑下

So... what're you thinking, son?
[.my2]
儿子 你什么想法

On the thing?
[.my2]
对于这件事

She's very smart.
[.my2]
她很聪明

She'd make good picks. Family first.
[.my2]
她是很好的人选 家人优先

I'm sure. I'm sure.
[.my2]
我懂 我懂的

But what's your cut?
[.my2]
那你为什么不高兴

Um... No.
[.my2]
我没

No. God no, Dad. No, it's your firm.
[.my2]
没有 我天 爸我没不高兴 这是你的公司

Like, it's not what's in it for me.
[.my2]
这跟我没什么关系

But you know, like, what is in it for me?
[.my2]
不过 到底能不能有点关系

I'd love to get you back in.
[.my2]
我倒是想让你回公司

Sure. No, sure.
[.my2]
行 也行

It's just it was tough last time.
[.my2]
可上回不怎么样

It was very tough with Frank over me in LA.
[.my2]
弗兰克在洛杉矶管我太严了

Frank's very important to the firm.
[.my2]
弗兰克对公司很重要

Oh, no, sure. No, of course, I understand that.
[.my2]
可不是 很重要 当然 我理解

It's just I had a lot of ideas at the studio.
[.my2]
只不过 我在制片上有很多点子

As you know, I'm quite an innovative thinker,
[.my2]
你也知道 我是大创新思想家

and I was met with a lot of resistance.
[.my2]
可我遇到了很多阻力

Is this still the film thing?
[.my2]
这还是因为节目吗

No... Oh, what, Robot Olympics?
[.my2]
不是... 你说机械奥运会吗

No, Dad, it's not about one fantastic idea.
[.my2]
不 爸 不只是这一个好点子

It was a culture. There were many of them.
[.my2]
这是种文化 当时有很多这种点子

What would be your dream outfit?
[.my2]
你想怎样呢

I wanna run the damn show. I do.
[.my2]
我想做那节目的制片 非常想

And until it opens up, Chief Operating Officer.
[.my2]
运行起来以后 我要做首席运营官

But I guess... I guess that's Frank, huh?
[.my2]
但我猜... 位置应该是弗兰克的 对吧

You OK?
[.my2]
你还好吗

Sure. You?
[.my2]
不错 你呢

The boys are here!
[.my2]
人都到了

Just right this way.
[.my2]
您这边走

That was my first helicopter ride.
[.my2]
这是我第一次坐直升机

It was so crazy.
[.my2]
太疯狂了

It goes so much faster than I thought.
[.my2]
比我想象的快多了

Hey, it's good to see you.
[.my2]
见到你很高兴

OK, let's get a glove.
[.my2]
好了 大家把手套戴好

Let's have a second.
[.my2]
再给我倒点

What time is it?
[.my2]
几点了

- Toss it over here! - Come on back, come on back.
[.my2]
-往这扔  -回来 回来

Now that things are getting shaken up, would you come inside?
[.my2]
目前局势有些动荡 你要回公司吗

Dad, I'm not just playing with the politics.
[.my2]
爸 我不是随便搞搞政治

Oh, no, of course. Politics.
[.my2]
对 当然 政治

Not to be crude about it, but politics is what comes out the asshole.
[.my2]
我不想说的太直白 但政治就是拉出来的屎

Wouldn't you rather be up front, feeding the horse?
[.my2]
明明回来有体面的工作 干嘛要去玩屎

Well, Joyce, she's got that Air Force One look.
[.my2]
乔伊丝表现地像我已经入主白宫了

So... to come back, I'd want the top job.
[.my2]
所以... 真要我回来帮忙 我必须万人之上

And if that was difficult?
[.my2]
但要是很难怎么办

Overseeing everything outside the US, parks and all.
[.my2]
你要掌管所有海外的部分 游乐场等全部

What, like... Tom's boss?
[.my2]
什么... 你是说 做汤姆的老板

Yeah. Stepping stones.
[.my2]
没错 垫脚石

What's the rescue pup looking for?
[.my2]
那来求救的小崽子到底要什么

He screwed up. Needs help.
[.my2]
他搞砸了工作 需要帮助

He might fit in eventually to the parks.
[.my2]
他将来可能适合游乐场的管理

Do you think Tom can handle the competition?
[.my2]
你觉得汤姆能处理好这种竞争吗

Mr. Roy. All set.
[.my2]
罗伊先生 准备就绪

There you go.
[.my2]
这就对了

Hey.
[.my2]
那啥

So, just wanted to give this to you
[.my2]
我想把这个亲手交给您

in person just to say, you know, happy birthday.
[.my2]
当面跟您说声 生日快乐

Hold that, will you?
[.my2]
帮我拿下

It's just a Patek Philippe. So...
[.my2]
是块百达翡丽表...

Yeah, it says "Patek Philippe."
[.my2]
我知道 写着呢 "百达翡丽"

Yeah. I know.
[.my2]
是 我知道

It's incredibly accurate.
[.my2]
这表极其准

Every time you look at it,
[.my2]
每次你看向它

it tells you exactly how rich you are.
[.my2]
都能准确展示你的富有

That's very funny.
[.my2]
这话挺逗的

Did you rehearse that?
[.my2]
刚这段你彩排过吗

No. Well, no. Yes. But...
[.my2]
没 我没有 好吧 有 但是...

OK. Yeah.
[.my2]
好 还行

Here.
[.my2]
给

OK, let's play ball.
[.my2]
好了 开始玩球了

So, what are you thinking?
[.my2]
好了 你们怎么想

We say no, all of us, on the trust. Full block.
[.my2]
我想我们集体反对改信托人 一致对外

Stability. Stick to the plan.
[.my2]
要稳定 得按原计划来

I take over and we just...
[.my2]
我上位 之后我们只要...

You two, under me, co-presidents.
[.my2]
你俩 在我之下 做两位总裁

- Under you? - Uh-huh.
[.my2]
-在你之下  -没错

But, you know, three. The power of three?
[.my2]
但是 你懂的 我们三人并肩作战

Interesting.
[.my2]
有趣

- Can we think about it? - Of course.
[.my2]
-我们能想下吗  -当然

I thought about it. Fuck you.
[.my2]
我想完了 滚你丫的

Go, Rava!
[.my2]
上啊 拉瓦

Psych your mind!
[.my2]
看穿你了

Go!
[.my2]
上啊

That's a strike.
[.my2]
好球

- Got her looking! - That's good pitching.
[.my2]
-骗到她了  -球扔得不错

- Change sides! - Hey, man.
[.my2]
-换边  -老兄

It was balletic, though,
[.my2]
跟跳芭蕾一样

kinda came around..
[.my2]
感觉出来了...

I hear you're the new kid. Yeah?
[.my2]
听说你是新成员 对吗

Oh, well, I mean, I'm just kinda starting...
[.my2]
对 我才刚开始...

- I hear you're coming in. - Yeah.
[.my2]
-我听说你也要加入了  -对

Yeah, eyes on the prize.
[.my2]
没错 你紧盯目标

Well, I have got my eye on you.
[.my2]
可我要紧盯你

You need any help,
[.my2]
如果你需要任何帮助

seriously, any help, any advice, just, you know,
[.my2]
我说真的 任何帮助 或需要建议

don't fuckin' bother, OK?
[.my2]
都他妈咽肚子里 好吗

I'm only razzing you, cuz.
[.my2]
我逗你的 表弟

You're dreaming, really.
[.my2]
你还迷糊呢

I'm razzing you.
[.my2]
我就是逗你玩

- OK. - That was a joke.
[.my2]
-好吧  -就是个玩笑

No, really.
[.my2]
不 我说真的

You know, the thing, I may look really fun,
[.my2]
你知道吗 我可能看上去挺逗的

- you know? - Yeah.
[.my2]
-知道吗  -知道

But the thing about me
[.my2]
但你要知道

is that I'm a terrible, terrible prick.
[.my2]
我就是个彻头彻尾的混蛋

I got you again. I just got you again.
[.my2]
你又上当了 我又骗到你了

Fuck me, man, your face.
[.my2]
太逗了老兄 看你表情

Pals. Yes?
[.my2]
我们是哥们

Yeah.
[.my2]
好吧

Would you kiss me?
[.my2]
你能亲我吗

- What? Kiss you? - Would you?
[.my2]
-什么 亲你  -你能吗

If I asked you to?
[.my2]
我要是让你亲呢

- Would I kiss you? - If I told you to? Huh?
[.my2]
-我会亲你吗  -如果我命令你亲 你亲吗

- I don't...  - Come on.
[.my2]
-我不...  -得了

I'm joking. I'm joking.
[.my2]
我开玩笑的 开个玩笑

- All right, Siobhan. - Bring it!
[.my2]
-好了 西沃恩 -开打吧

Batter swing!
[.my2]
挥棒

Just like that!
[.my2]
就是这样

Hold up. Hang on, hang on. Sorry.
[.my2]
等下 等一会 等等 抱歉

- Apologies. - Boo! Boo.
[.my2]
-抱歉  -嘘 嘘

Honey, boo him.
[.my2]
亲爱的 嘘他

- Yeah. OK. Sorry. I gotta run. - Boo!
[.my2]
-不好意思 我得走了  -你真没劲

It's the crunch.
[.my2]
要摊牌了

Frank, will you be link man here?
[.my2]
弗兰克 你来主持一下

Dad?
[.my2]
爸

Of course.
[.my2]
去吧

Come here, sweetie.
[.my2]
来这儿 宝贝

Well, if Kendall's going, we need one more to make it fair!
[.my2]
如果他要走 公平起见 我们队还需要一个人

Keep it up, slugger.
[.my2]
坚持住 击球手

The kid. Hey! Hello!
[.my2]
那边的小孩 看这里

Hello! Kid. Yeah. Yes.
[.my2]
对 就是你

You. You. You wanna play?
[.my2]
你想加入吗

Dad, can he play?
[.my2]
孩他爸 他能上场吗

Yes. Sure.
[.my2]
当然 去吧

Thank you, Dad.
[.my2]
谢了 孩他爸

Yeah, hey, what's up?
[.my2]
是我 怎么样

I just got some background
[.my2]
我听说你正准备一篇报道

for the story I heard you had cookin'.
[.my2]
我入手了一些背景资料

That's right. Yeah, I know Kendall Roy.
[.my2]
对 我认识肯德尔·罗伊

And he's saying Logan's lost it.
[.my2]
他说洛根已经没救了

Yeah, that's right.
[.my2]
就是这样

Some board members and senior management,
[.my2]
某些董事成员和高层管理人员

they want him out.
[.my2]
想让他走人

That's what I'm hearing from people close to the family.
[.my2]
我听和家族走得很近的人说的

Those disloyal fucks.
[.my2]
那群墙头草

Just... Just say source close to the family.
[.my2]
就是... 和家族走得近的线人

- That's high. - Too high.
[.my2]
-高了  -太高了

You're gonna be fine. Relax, don't worry about it.
[.my2]
你搞得定的 放轻松 别紧张

- Can you hit a ball? - Yeah.
[.my2]
-你能打中球吗  -能

Great, because I will give you
[.my2]
很好 因为如果你

one million dollars if you hit a home run.
[.my2]
打出了全垒打 我就给你一百万美金

- I'm dead serious, OK? - For real?
[.my2]
-我没开玩笑 好吗  -真的吗

Yes, for real. A million dollars.
[.my2]
千真万确 一百万美金

Honey, where's the... your bag?
[.my2]
亲爱的 你的... 包呢

Hey, I'll do it for a million. Give me that.
[.my2]
我也想挣一百万 把球棒给我

Just kidding. You're good.
[.my2]
开玩笑的 你加油

All right.
[.my2]
好了

I don't know why you're smiling. I am dead serious.
[.my2]
我不懂你笑什么 我可是非常严肃的

I will give you one million dollars, cash,
[.my2]
我会给你一百万现金

for a home fucking run.
[.my2]
如果你他妈能打出全垒打

Rome, don't be an asshole.
[.my2]
小罗 别犯贱

I'm not being an asshole. I want him incentivized.
[.my2]
我没犯贱 我要给他点物质刺激

This is fun.
[.my2]
多有趣

It's a game. Jeez, stop being so serious.
[.my2]
这只是个游戏 天 你别这么认真

Huh?
[.my2]
看到了吗

Witnesses.
[.my2]
证人们

Good luck. I believe in you.
[.my2]
祝你好运 我相信你能行

All right, let's do this!
[.my2]
好了 来吧

One million dollars.
[.my2]
一百万美金

OK, come on.
[.my2]
来吧

- That's it. - Run, kid!
[.my2]
-打中了  -孩子 快跑

- That's a hit. - That's a damn hit.
[.my2]
-打中了  -飞得真远

Come on, Shiv! I'm here, Shiv!
[.my2]
快 小西 我在这

- Come on! - Tom!
[.my2]
-快  -汤姆

Come on! Come on, run faster!
[.my2]
快 快 再跑快点

- No! No! - Bad luck, kid.
[.my2]
-不  -孩子 运气不好

Oh, no! You were so damn close!
[.my2]
你就差那么一点点

That was so close!
[.my2]
就那么一点点

Oh, my goodness!
[.my2]
天啊

Oh, that is so sad! Oh, I'm sorry.
[.my2]
真可怜 但不好意思

I can't give it to you. That would have counted, by the way.
[.my2]
钱不能给你了 顺便说句 钱差点就是你的了

That was almost a home run, if you went all the way around.
[.my2]
如果你刚跑完了 就真的是全垒打了

But it was a really good effort.
[.my2]
不过你真的努力了

Really. Quite tremendous.
[.my2]
真的 很精彩

So take this back to your life.
[.my2]
拿着这个 回到你的生活

It's a quarter million. Enjoy.
[.my2]
这是一百万的四分之一 好好享受

Son... magnificent effort.
[.my2]
孩子... 打得很棒

- Thank you. - Magnificent.
[.my2]
-谢谢  -很棒

- Come here. - It's OK.
[.my2]
-来这里  -没关系的

Hey, Lawrence.
[.my2]
劳伦斯

Sorry the other offer fell through.
[.my2]
真可惜那个提案失败了

I don't know what happened.
[.my2]
我不知道发生了什么

But we fattened the goose nice now, right?
[.my2]
不过待宰的羊已经养肥了 是吧

The number is 140.
[.my2]
我给你1.4亿

Cash, with a stock alternative.
[.my2]
现金 股票也可以

You're on our board.
[.my2]
你加入我们

Take the stock, you'll own a nice piece of us.
[.my2]
股票到手 你会分到一份不错的羹

Well, that is an appealing package.
[.my2]
好吧 这提议很诱人

It is, yeah. It's appealing.
[.my2]
你说得没错 是很诱人

You better play nice, though. Because I'm the whole company.
[.my2]
但你最好想清楚 因为我代表整个公司

Yeah, I think you're gonna stick around
[.my2]
当然 我觉得你不会走的

because I'm gonna stuff your mouth with so much money
[.my2]
因为我会在你嘴里塞满了钱

you're gonna shit gold figurines.
[.my2]
你拉屎都拉的小金人

Non-disclosure agreement. Non-voting shares. Non-compete.
[.my2]
保密协议 无表决权股票 竞业禁止

I'm going to lock you in a golden cage, fuck you with a silver dildo,
[.my2]
你会被我关进金笼子 屁眼里插满银阴茎

and pay you so much you sing whatever song I want.
[.my2]
收着我的钱 唱我想听的歌

- Easy. You still need me to recommend this. - No, I don't.
[.my2]
-别急 你还需要我的推荐  -不 我不需要

This is a deal so fucking good you have to take it,
[.my2]
因为我的提案太他妈好了 你不得不接受

or we'll see you in court.
[.my2]
否则我们法庭见

Dude.
[.my2]
哥们

How you doing, sir? How's everything?
[.my2]
你还好吗 先生 事情还顺利吗

I'm Colin. I work for Mr. Logan Roy and the Roy family.
[.my2]
我叫科林 我为洛根·罗伊先生和他的家族工作

We'd like to keep this quiet today, if you'll agree to that.
[.my2]
我们希望您能对今天的事保密

We'd like to have you sign a non-disclosure agreement.
[.my2]
我们希望和您签订一份保密协议

- You wanted five? - Oh, Frank. Yeah.
[.my2]
-你想再干五年吗  -对 弗兰克

I've been thinking
[.my2]
我一直在想

if now isn't a time for a new role for you.
[.my2]
现在 是不是该给你分配新职位

OK. As in what sort?
[.my2]
好吧 什么职位

Light duties.
[.my2]
轻松点的

Light duties.
[.my2]
轻松的

Are you kidding me? Logan. Me?
[.my2]
你耍我吗 洛根 开我

There should be a press release on your phone.
[.my2]
你手机应该收到了一封任命信

Proof it.
[.my2]
看看吧

You might want to give it a bit of color, it's quite dry.
[.my2]
你可能想再润色下 写得挺直白的

That's it? To me. That's it? After 30...
[.my2]
就这样吗 这样对我 都过了30...

Jesus Christ. Here?
[.my2]
老天 就在这林子里

You are what you do, Logan. You know that?
[.my2]
你是你的所为 洛根 你知道吗

In the end, you're just what you do.
[.my2]
最终 你只不过是你的所为

Don't worry, you'll get your nut.
[.my2]
别担心 你会拿到补贴

Connor!
[.my2]
康纳

Shiv! Roman!
[.my2]
小西 罗曼

The other helicopter.
[.my2]
坐那架直升机

Colin, see to it.
[.my2]
科林 交给你了

Well, officially the deadline has passed.
[.my2]
截止日期已经正式过了

So... what do you say, kids?
[.my2]
所以... 你们怎么想

What's the Frank situation?
[.my2]
弗兰克什么情况

Frank's out of the picture.
[.my2]
弗兰克与我们无关了

Yeah?
[.my2]
怎么

Frank's dead. Tom's stepping up,
[.my2]
他出局了 由汤姆接替

and Shiv's thinking about a new role.
[.my2]
小西也在考虑一个新职位

So, are we good?
[.my2]
所以 都满意了吗

Um... Shiv?
[.my2]
小西觉得呢

Rome?
[.my2]
小罗

Con?
[.my2]
康纳

I'm with these two. What they say goes.
[.my2]
我听他俩的 他们说了算

Our position is this doesn't quite work for us.
[.my2]
我们认为这对我们没什么用

At present.
[.my2]
就目前来说

You what?
[.my2]
你说啥

It's not sufficiently attractive as a proposition.
[.my2]
作为一个提议来说 还不够吸引人

Are you fuckin' joking?
[.my2]
你们他妈扯淡呢

We get that. We do.
[.my2]
我们懂的 真的

And we would love to help. I would love to help.
[.my2]
而且我们也很乐意帮忙 尤其我

Then help.
[.my2]
那帮啊

But why would I when I'm giving away power?
[.my2]
但我们连权力都失去了 为什么还要帮你

Why would I do that?
[.my2]
有什么理由这么做

- So... so Kelly, uh... - Who's Kelly?
[.my2]
-那...让凯莉  -凯莉是谁

Kelly will set up some figures.
[.my2]
让凯莉准备一些数据

- He should see that, uh... - Dad?
[.my2]
-他应该看到...  -爸

- Dad? - Yeah, he...
[.my2]
-爸  -对 他...

Dad, it's just a first position. Dad?
[.my2]
爸 这只是初始意愿 爸

Get a grasp of what... what...
[.my2]
能领会... 那个...

- Dad! Dad! - Dad!
[.my2]
-爸 爸  -爸

Dad!
[.my2]
爸

- Dad! Dad! - Dad! Dad!
[.my2]
-爸 爸  -爸

Just, yeah. A hospital. Take us to a hospital.
[.my2]
去医院 把我们送到医院

OK, yeah, now!
[.my2]
马上

Has he fainted?
[.my2]
他昏过去了吗

- He fainted? He's hot. - He's really hot. I don't know.
[.my2]
-他昏过去了 他身上好烫  -真的很烫 怎么回事

- Kendall? - Yeah.
[.my2]
-肯德尔  -怎么了

Have you heard the news?
[.my2]
你听说那消息了吗

What?
[.my2]
什么

Deal.
[.my2]
成交

It's all very exciting. I can't wait to...
[.my2]
太让人兴奋了 我很期待...

- We got a deal? - Yeah.
[.my2]
-我们成交了吗  -是的

- Serious? - Yes?
[.my2]
-说真的  -真的

Oh, dude.
[.my2]
哥们

Listen, I think...
[.my2]
听着 我觉得...

I think you've made a really great decision
[.my2]
你做了非常明智的决定

and I hope there's no hard feelings over all the shit-talking.
[.my2]
我希望你不要介意我刚说的那些话

Oh, no, no, it's cool.
[.my2]
不会 没关系

It's cool.
[.my2]
没事的

So, the news I was talking about
[.my2]
我刚说的消息是

is that your dad just had a brain hemorrhage.
[.my2]
你父亲刚突发脑溢血

What?
[.my2]
什么

Yeah. I'm so sorry.
[.my2]
是的 我很抱歉

- Are you... - But...
[.my2]
-你...  -但...

you just invited me into the chicken coop.
[.my2]
你就在刚才引狼入室

And without Daddy around to protect you,
[.my2]
没有你老爸来保护你

I'm gonna eat you all.
[.my2]
我会把你们所有人吃干抹净

One by fucking one.
[.my2]
一个接着一个

Hello?
[.my2]
喂

Kendall. Thank God.
[.my2]
肯德尔 你终于接了

We've been trying to reach you. Um...
[.my2]
我们一直在联系你...

Dad is in the hospital.
[.my2]
爸进医院了

He's...
[.my2]
他...

We were in the helicopter, and we got here really fast,
[.my2]
我们刚在直升机里 很快到了医院

but they think...
[.my2]
但他们认为...

We don't know. They think he's had a brain hemorrhage.
[.my2]
还不确定 但医生认为他突发了脑溢血

If you could get here really soon,
[.my2]
如果你能现在赶过来

that'd be good.
[.my2]
那就太好了

I'm sorry.
[.my2]
对不起

Most first-time homebuyers would love to live in Newport Beach.
[.my2]
多数首次购房买家选择新港海滩

But average home price in Newport Beach is over $1 million.
[.my2]
但新港海滩的均价超过一百万美金

So, most of the homes...
[.my2]
所以 大多数房产...

There is a degree of stock market volatility
[.my2]
出现了一定幅度的股票波动

As Waystar Royco's chairman is reported to be in critical condition
[.my2]
据说韦斯达·罗伊科的总裁已病危

following a major medical incident...
[.my2]
接下来报道一起重大医疗事故...
