
= 继承之战 S01 - 08
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''



== 释义



'''

== pure



It's a pretty great view, huh?

I mean, out there. Not me.

Where are we at, Bob?

Excuse me, I... I'm actually not even here.

- You're at 5.3? - Correct.

And I think we can live with that.

Yeah?

Yeah.

It's a fair price.

Well, I don't know about that.

You'll have 70 local TV stations.

Buy in Sandy, you're King Kong of local.

The kid knows. The kid's smart.

Are we good?

Give us five minutes.

We'll set you up with a room.

Good, right? Is it whiskey time?

Shut the fuck up.

- Uh, it's a good price. - What the fuck's going on?

He's selling me things I want at a fair price?

So what's next? Fellatio?

I think he just wants out, fast.

If he does, we fuck him.

I think we did just fuck him.

He's smiling.

It's no good if he's smiling.

Well, objectively,

I mean, if we get what we want

and he gets what he wants...

You screw them out.

You chisel them out.

You fuckin' hurt them.

And then you watch them squeal.

I like hurting human beings as much as the next guy,

but, Dad, this is really fucking good.

Walk him to the elevator and tell him 4.9.

Oh, Dad, no, that's... it's insulting.

Walk him to the elevator and tell him 4.9.

Gerri, you do it.

You, fuck off.

If you can't do it, fuck off!

All right.

Just text on your phone, ya bendy fuck.

Really just warms the walls.

- Greg.  - Hey.

Ow! Dude.

Hold on, hold on, hold on.

Are you OK?

What? Oh, that? That was nothing.

Sometimes you gotta play possum, ya know?

Let him punch it out till he gets tired,

and then you go in for the kill.

Right, nice. Listen, hold on.

- Yeah.  - How's Kendall doin'?

He's blowing you off too?

Last time I saw him he was smoking crank with some mole men,

but that was like a month ago.

- He's hustlin'.  - Yeah, right. VCing?

I may be seeing him this weekend. If he shows.

- Oh, yeah?  - Aw, fuck.

Dude, I don't suppose you know a coke dealer in Prague, do you?

Ah, probably. Yeah. Why?

Tom Wams' bachelor party.

"And if he doesn't show..." I don't have time for this.

Hey, let me tell you something, dude. Fuck Prague.

My girlfriend and her fuckin' freak dogs

run these... You ever heard of these parties, Rhomboid?

Bullshit.

I'm tellin' ya. I'm fuckin' cool.

You don't understand.

Why, because you have a nipple ring

and simply will not stop going on about it?

It's better than telling everyone you're down with Dre

because he sends you cereal bars at Christmas.

Fuck you. I have a reputation.

I can't take my crew to watch some art pricks

dance around in fucking bowler hats and twizzle their mustaches

out of time to the beats.

Are you done? You know who else will be there?

Sandy Furness.

Fuck off.

I'm tellin' you.

Bleahh. He goes to that kind of thing?

I know, right? But he is sitting

on the other half of your dad's dream deal.

Packet of 50 more local stations.

Come to the party, get him to sell,

and trust me when I say this,

you will become the number one son.

Sandy... goes? Jesus.

Yeah. Get me those names and I'll get you on that list.

And one more thing, bring Kendall, OK?

I need to patch things up with him.

Oh, fuck yeah.

- What do you think?  - Yeah.

Hey, bro, can you turn up the bass in the back?

Louder.

- You feelin' good?  - What?

- You're good?  - Yeah, I'm great.

I'm psyched.

- Nice and loose, yeah, Frank?  - Yeah.

Try not to drag yourself in there

like the world's oldest man.

I'll try.

Frank. Kendall.

- This is Dust.  - Hey, man.

Hey. Great to connect.

Love the name, by the way. Very... funky.

Sorry, please excuse Captain fuckin' Be-Bop here.

Hey, how's it goin'?

Cool earrings. Very Bauhaus.

Big fan of what you guys do.

Fuckin' sweet chili sauce.

Thanks. Uh, likewise.

Angela, you want to spin us through the pitch deck?

- Sure. So...  - That's OK.

I don't need to hear the pitch.

I've been through the deck, and I get it.

Basically, you buy a

painting from some art student in a basement,

jack up the price, sell it to some Morgan Stanley sex pest,

and you, me, and the student all get rich. Right?

We're interested in increasing the reach of young artists.

And the democratization of art.

No, absolutely. I get it.

You're providing a platform to marginalized talent,

the next generation of artists.

I'm just telling you how

it works from the outside, to the sharks.

Maybe we can talk about funding cycles.

Sure. We've worked out a plan

for the first year after the launch...

I'm sorry. Can I just say something?

so, I... I... I...

I got these sneakers...

on the way down here because, uh,

I thought... I don't know what I thought,

I thought you'd all be dressed like fuckin' Bjork,

and I wanted to, uh, make an impression.

Um, so, I'm a jackass, um,

the truth is, I don't know anything about art.

What I do know is how to monetize your concept

and achieve the scale it deserves.

Don't sell your soul to some monolith.

We're boutique, we're light on our feet,

we're not the Gang of Four, we're the fuckin' Rebel Alliance.

I'm a good guy, who knows the bad guys,

I've got reach, and I will fight for you every fuckin' day.

I'm the asshole who can be your Warhol.

And, uh... yeah, I just thought of that,

so apparently I do know a little bit about art.

So... what?

Talk to me. What do I need to do?

Do I need to take off my dopey sneakers?

- No. - I will. Seriously,

I'll throw them out the fuckin' window right now.

- They're not bad. - I'm taking 'em off.

- Here. Ilhan, have 'em. - I'll trade you.

OK?

Can we talk now?

Oh, shit.

Sor... Um, so,

what do you think... Miss?

Uh, betw... You know...

Sorry, I... I'm...

I'm somewhat between the devil and the deep blue sea here,

because my boss downstairs is waiting,

and my boss upstairs is him, you know,

so I've been here three and a half hours.

What do you think? What do you...

Do you want...

Yes, sir.

I'll send him in.

Thank you.

At long last.

It's the wheel, it's... doin' its thing.

Oh, yeah. It's buffering.

You could try knocking it down to low... low quality?

Hmm. Go ahead.

Yeah, just...

It's a... heckuva good head of hair on ya there.

I think it's the maternal side that it's carried on, so...

So I hear you and the boys

are heading out for Tom's bachelor party.

Yes. That's correct.

Roman's arranging, Prague has been mentioned.

I will tell you this much.

I believe Logan Roy is a pernicious influence on our culture.

He is, to be frank,

- Man, what... a jack...jackhole. - a cancer to American values.

I don't take these words lightly...

Yeah, well, he just lost my vote.

Uh, listen to me.

Um... do me a favor.

Can you make sure that Kendall doesn't come back in a box?

- OK. - Yeah, I...

I don't want him showing up dead

at the bottom of some French fag's pool.

Oh, no, absolutely. None of us do.

Keep an eye on him for me.

Is this something you can do for me?

I hear he's been, uh,

wetting his beak.

Yes, sir.

Um, in which case,

would now be a convenient time

to talk with you about, like, a lateral shift

in terms of my position at the company?

Because I'd like to move on from Parks

and into, for example, Digital?

I don't want to mention any names, because I...

But the culture there,

it borders on the personally abusive at times.

Tom?

Oh, Tom.

I didn't know he had it in him.

He can be pretty able in that department.

But what I'm doing, sir, is I'm flagging to you

that I'm thirsty for the next chapter.

Well, you take care of this for me, and perhaps we'll talk.

OK? Done? Are we done?

Muchly appreciated.

"Muchly"?

Time's up.

Time's up for the big media operations that poison...

- Have you seen this? - ATN spot.

I guess we do, right?

You're gonna stand there?

In my air space?

I'm re-reading it.

- For context. - You're CCed.

...the power that one man wields.

We can't let these monopolistic practices go unchecked

simply because we're too afraid

of the power that one man wields.

Waystar Royco is a cancer at the heart of America.

I can't believe I'm getting paid to call my dad names.

It's so cathartic.

Logan Roy is out of control...

You really think he should do ATN?

Yeah. Sure. Into the lion's den.

He'll attack them,

righteous, Old Testament, anti-capitalist Gil,

and they'll attack us, "There's a Red in the bed,"

they get the viewers and we get the base fired up.

No one's mind's getting changed,

then once we're through the primaries,

- we pivot to center. - Except Gil won't pivot.

- I say no! - I'll get him to pivot.

I say no more!

- Hello? - Hey, Shiv, it's me!

- Tom, sweetheart. - So listen,

something's afoot,

because we've arrived at the drop-off point

for my bachelor party.

Seems there's been a change of plan,

and I'm pretty sure I'm being pranked.

What's happening, Roman?

Hold your tingling wiener.

All will be clear soon.

I don't think you understand how disruptive it is

to be changing the itinerary at this late stage.

I don't know what's gonna happen,

but I've got a feeling it's liable to get a little disgusting.

I don't think you're supposed to be telling me this.

I know, I just

wanted to flag it, and, you know,

calm the qualms, because I, for one, would never...

Tom, it's one night,

we're both adults,

just enjoy yourself, OK?

Shiv, honey badger.

God, I want to dock myself inside you

so much right now.

Yeah. OK. I love you too, Tom.

Ok.

Now he deigns to join us.

- You're late. - Yeah, sorry.

I've been a little busy revolutionizing tech financing.

On coke.

Hope not. What up?

So, who wants to fuck a hobo?

No? All right,

then let's party. Down there.

What... No...

We're going to a party in the tunnel?

OK. No, relax, we're not going

to a party in a tunnel.

This is just a ruse.

What is this, some pop-up shit?

Am I gonna need my central Europe coat?

Romey, I'm wearing flight socks and my TSA slippers.

I know what you're doing right now, OK?

I'm being lured into a tunnel

and then next thing, I'm gonna wake up in Belgium

with no frickin' eyebrows!

You probably want to dump your luggage in the car.

Shit.

fellas.

Sorry, it's actually a really tight guest list.

Roman.

- Yeah. - It's Matt and Jonas.

If the Fly Guys aren't on the... They flew in!

- Roman. - Relax, OK?

We're gonna figure it out. We're gonna first-wave it,

we'll call you once we're inside, all right?

You know what? Go get some coffees on me.

Thanks, we're good. I can buy coffee.

All right, let's go!

God!

I...

I can't just leave the Fly Guys.

That's the Fly Guy code.

OK, just leave your phones on,

- and I'll call ya. - All right.

- Five minutes! - It's on.

Man!

Roman. What the fuck have you got planned for me, man?

No, seriously,

what have you got planned?

Tom, Prague fell through,

and I was fuckin' busy,

and I didn't have time to plan

the hot air balloon to Monaco.

OK. Hot air balloon?

- Yeah. - That would have been nice.

Dude! Oh, my God, that's a dead rat.

You guys, this is a disaster on the footwear front.

Can I change?

It's a dead rat. Who gives a shit?

Yeah, fine, thank you, just keep goin'.

- We'll be here. - All right, see you over there.

Are you gonna be OK around all the booze

and the coke and shit?

'Cause I can just make sure no one does it around you.

- I'll be fine. - Yeah?

- Thanks, bro. - Yeah. Of course.

Wait up!

Jesus fuckin' Christ, it's a dead rat. Relax.

I hear you're doin' apps.

Yeah.

I'm incubating.

I'm rebalancing away from crypto into eco.

Sounds... futuristico.

Yeah, it's good.

It's better than being carried around in Dad's pockets

like fuckin' Stuart Little.

They're nice pockets.

Spacious.

How is he?

He's... I mean, you know.

Actually, he's... he's got me overseeing

the satellite launch out of Tanegashima.

Spaceship?

Yeah. Plus I'm heading up the local deal.

Bob Galpin is selling

and, I knocked it out of the park,

which is nice.

Good for you, bro.

Yeah. Guess I finally broke out of the cage.

Can't keep a good dog down, right, Ken?

Abandon all hope ye who enter.

- Is this real? - Is this a real corridor?

Are we goin' to an airfield?

Greg, did I tell you that Willa

- moved out to Austerlitz? - Oh?

Yeah, she loves how quiet it is.

She didn't think she would, but she does.

So I for one won't be engaging in any debauchery.

Roman Roy and guests?

That is correct.

- Welcome to Rhomboid. - Thank you.

Boys, we're pouching our phones.

Wait! Is this it?

Is this actually where I'm going to have my bachelor party?

Why is it so wet? I think there's a big leak somewhere.

I've been living on central European time

for 48 hours to ease the transition.

I'm gonna be ready for breakfast soon.

I don't know if this is the kind of party with a lot of food.

Roman, I'm sorry, is this where I'm having my bachelor party?

Roman, how are you, man?

Ken. Long time.

Are we good?

You're my third-oldest friend.

You fucked me like a tied goat.

- We're great. - No, yeah,

you're goin' the right way. Keep goin' straight.

- Kendall, I was gonna say. - Yeah?

If you need anything tonight,

bottle of water, soft drink,

whatever, I'm gonna be your mule.

Actually, you know what? I need something a little off-menu.

See if you can find me some ketamine.

I don't know what that is.

Is Sandy here? When do we sit?

Yeah, yeah, all things in time.

Right here.

Sorry.

Well. Now I'm sure it's gonna be great. Thanks, Roman.

What did you expect? Why'd you even ask me, Tom?

Thought you'd rise to the occasion.

Well, clearly I haven't risen to the occasion.

Gents, have a great fuckin' night.

Dmitri, how are you?

Kendall. I'll find you, all right?

OK. This is it.

Yeah? Cool, right?

Is it cool, or is it, like, total fucking bullshit?

Well, what is it? What is it?

It's a physical fun palace.

It's basically, if you're into it, and she's into it,

it's all good.

Look at this fucking guy with the bird mask

like Eyes Wide Shut.

Oh, wow. Eyes w...

Wait, is this... is this gonna be an orgy?

-No. - This is not gonna be an orgy?

Greg, it's not 1997. It's not this, it's not that.

Don't be so binary, Mr. Betamax.

Is it gonna be like a little bit of an orgy?

It's basically a collective of hot people...

and Connor... at a party.

And a monkey dressed as an astronaut, apparently.

It's whatever you want it to be.

It's a fucking sand pit for emergent behavior.

OK, OK, holy shit. So... OK. OK.

So, does that mean we're able to... fuck here?

Yeah. Hey, Ken, what do you think of the pussycat? On it?

No, not me. Business is my fucking.

Great. I'll find you a Bloomberg terminal to stick your dick in.

Well, I'm out. In a relationship. Girlfriend!

I gotta say, Roman, this is looking promising.

This is looking really promising!

See? Have a little faith.

There's areas, though, right?

Neutral areas in terms of not being, you know,

compulsory to do sex stuff?

No, Greg. If you refuse, they cut your dick off.

What did I just say? It's very consensual.

Angela.

Angela?

Angela. Angela.

Yo. Dust.

- Oh. Fuck. - Hey. What's up?

Yeah, hey, what's happening?

Here we are in a fuckin' warehouse

- in Sunset Park or whatever. - Yeah.

I feel like this is synchronicity.

Yeah? Like the universe is telling us something.

Yeah. We really appreciated you coming to see us.

Yeah, yeah, totally,

I'm super-excited.

Yeah. Totally. Me too.

OK, well, fuck, yeah. Excellent. All right.

All right. Good to see you.

Yeah.

You know, I was thinking,

maybe one wine, one water,

as like an informal rule for the group?

Also, uh, they have risotto balls.

Like, they're soakers. Super-soakers.

- Ketamine. - Greg! Greg!

Got you one. Come on, man, it's goin' off tonight!

We should talk to some girls.

A little tip. Ask 'em where they were on 9/11.

If they don't know, they could be under 21.

Well, Shiv gave me a hall pass.

'Cause we're adults. Apparently.

I'm gonna blow my load like multiple times.

Wow. So... And Shiv has that same arrangement?

She's an adult too, so...

What? No, no.

Well, yeah, sure.

I mean, I don't know, Greg. It's not a competition.

No, no, no. That's cool.

I'm sure you guys have it all figured out.

- Romey, what is this? - Molly. Happy pills.

- Oh, cool. - But I wouldn't...

No, no, no, no. Prague time.

It's two in the morning for me. I need a little pick-me-up.

- Don't. - Dude. I know my way around.

1986, me, a Fleetwood Mac LP,

and a bag of weed touched the face of God.

Huh? The first of the evening, the first of many.

- Do not do any more of these. - Got it. I'm one and done.

Got a lot of shit cookin',

like, artificial sun solar cells thing...

Yeah. Listen, man, about the vote,

and your dad and us,

I love you, man, but you know I had to follow the money.

You know that, right?

I get it.

All right. Hey, why don't we talk in private for a second?

- Can we do that? - We can talk right here.

All right.

So listen, I have a question for you.

How would you like to be all the way out?

Half a bill for your share of Waystar.

- Is this for real? - Yeah, man.

I'm feelin' fuckin' generous, that's all.

And I've plumped the pillows and added a little premium.

- Consisting of what? - Straight liquid.

- Bullshit. - Don't you worry about it.

I can raise it.

Why would you want to be even more in?

The place is a fuckin' antique shop.

Ken, just take the money and get out. Please.

I mean...

it's not uninteresting.

Fantastic. Great. So listen,

there's a part two to this.

Why don't we talk this over with Sandy?

Sandy... Furness?

Come with me.

Come.

Bottom's up.

- One, two, three! - Ketamine.

- You good? - Line 'em up, please.

These bathrobes are nice.

See these?

What's your table linen philosophy?

Uh, my philosophy is I literally don't give a fuck.

So what's that, Nietzsche?

These are what's on our registry.

You should go for these.

Right, you want us to have matching cutlery?

Why not?

It'll be sort of horrible, and cute.

So when we both get divorced and split all our stuff,

we can hook up and have the same set.

The full set.

Yeah.

You know this is just fun, right?

- I know, it's just... - It's nothing.

I mean, it's not anything. There's no God,

there's no... anything,

there's just people in rooms

trying to be happy.

- Right? - Right.

Oh, and I suggested to Gil

that he cool off on the anti-Waystar agenda on ATN tonight.

- Excuse me? - Yeah.

I talked to him at the thing.

Oh. OK.

Well, I did spend quite some time

on how it'd be very vivid to attack Waystar

- on a Waystar network, but... - Very vivid?

It's played out. Makes it look like we have an agenda.

Uh, we do.

Stopping overly mighty media owners

setting the agenda for our democracy.

DOJ, FCC, Batman,

to stop your dad eating the news.

OK, but even if we're going for that,

isn't that in some big speech that no one reads?

Can't he just connect to America tonight and forget the base?

Shiv, I appreciate you might have split loyalties on this.

Fuck you. I'm just trying to make him win.

I don't think he can do both at once.

I don't think Gil can do the base and the rest.

Well, if he can't ride two horses at once,

he shouldn't be working at the circus.

- Sandy comes to these? - Oh, yeah. He loves sex.

Dude, the thing that he pees through,

he puts into other people.

It's fucking vile. And a lot.

Hey, Sandy.

Oh. Gents, excuse me.

- Kendall. You look well. - Thank you.

You look, uh, out of place.

I do like to see the youngsters frolic.

So, you wanna talk?

Uh, did Stewy fill you in?

Why do I feel like I'm about to find out

you're not my real mommy and daddy after all?

Look, the truth is,

he wants your piece of pie,

but... and please don't fucking blow a fuse here, OK?

The reality is, he's already in on Waystar.

- As in? - As in Sandy's me,

and I'm Sandy.

We're like a single entity.

Like a creature from mythology.

You know, head of a horse, dick of a swan.

Stewy... seriously?

I have a shell company attached to his private equity fund.

I'm a parasite on a parasite.

You should have disclosed that to me when I brought you in.

You are one hundred percent

correct about that. I should have done that.

You were in a tough position

without having to consider whether your dad

would want me involved.

He very much would not.

So apparently, my girlfriend's having a panic attack.

I'm gonna let you two just catch up now. Cool?

Stewy tells me you're getting into tech.

Yeah, I have a fund.

We're niche, but we're engaged.

Just closed a deal tonight, actually.

And I found these four Stanford grads

who are doing this thing, it's pretty cool,

they have this cluster of hydrogen lamps...

Wait. What's going on?

Dude, are you pitching? You just pitch?

Where'd you spring from, Heidi?

Don't stop. I want to hear the pitch. I might invest.

We were just talking.

To him? The enemy?

The adults are talking. How about you go play in the other room?

Hey, Sandy, could I maybe get a moment with you in private?

I'd like to talk to you about how attached you're feeling

to your 50 failing local TV stations.

Sure. I'm sure we could find a time.

Roman, could you maybe back off for, like, 20 minutes?

- No. - Yeah. Get us a drink?

I would love another old-fashioned.

He would love another old-fashioned, cliché that he is.

No, that's not gonna happen.

I know that you and my dad

have been deeply and madly in hate with each other,

and you have been for many years,

but I want you to know that I'm my own thing,

and I am fully authorized...

I am fully authorized

to negotiate on behalf of Logan.

Yeah, he's doing satellites like it's 1985.

Dad's got him holding the plastic steering wheel in the back

and telling him he's driving.

You have to excuse my brother.

He's adjusting to his medication right now.

How about you fuck off back to your little gang-bang?

- See how he talks to me? - You're embarrassing yourself.

- You're family. - He used to lock me in a cage.

- What the fuck? - No, that's a true story.

What, you're pretending that you don't remember the dog pound?

- Are you tripping? - Yeah, it was a "Game."

I had to go climb in this big dog cage in the kitchen

and wait for someone to come collect me.

Oh, yeah? Well, I-I don't know.

Might be three minutes, might be the whole afternoon.

Four years old. I was eating dog food out of a cold tin bowl.

I know, right? They should

make a fuckin' movie of this shit, right?

Excuse me.

I'll be back.

- What the fuck are you doing? - What?

- What was that bullshit? - I can say what I want.

Yeah, but you... That was insane. You're acting insane.

So you just want me to pretend that none of that happened?

What happened?

None of it happened. Dog pound didn't happen.

I never made you eat dog food.

There was a bowl that was filled with chow,

and I couldn't leave the cage until I finished it.

It was a game, you enjoyed it.

A-Ask Connor. Ask Shiv.

I enjoyed being in a cage with a leash around my neck?

So now there's a leash? You're full of shit.

Me? I'm full of shit?

- Have fun. - Get the fuck outta here.

Asshole! Nwahh!

- So I got this gelding, right? - Chestnut brown.

You wouldn't believe the size of this guy's cranium.

Big ol' noggin!

Hey! Con, can I ask you something?

Do you remember anything

about a dog pound when we were growing up?

Sure, I remember that game you used to play.

So he used to lock me in a fucking cage.

Sure, the big cage, yeah, in your mother's place.

The laundry room in Cheltenham.

Thank you! He's trying to gaslight me.

No, you liked it!

You asked to be put in that cage.

- What? - Yeah.

It was really weird, but I think you enjoyed it.

OK, so I asked to eat dog food?

It was chocolate cake. I think.

- Bullshit. - I don't know.

No. Kendall locked me in a cage, I went weird,

I started wetting the bed,

and that's why Dad sent me away to St. Andrews.

No, Rome, Dad sent you to military school

because you asked to go.

- Oh, you're full of shit! - That's how I remember it!

So listen, my ranch

is completely safe from biological or chemical attack.

- These are your friends, right? - Yeah.

You'd all be welcome, anytime, pre- or post-apocalypse.

Tom!

- Tom. - Hey.

Have you seen Kendall?

No.

I feel like we should maybe keep an eye out for him.

Aw, damn it.

Tom, sweetheart, I'm at ATN with Gil.

What's the least amount of syllables you can say this in?

Well, I just want to be clear in terms of you and me.

Is this a quid pro quo arrangement?

I don't know what you're talking about.

It's just, you know, if I...

if I, for instance,

if I touch a boob,

do you grab a dick?

I don't know if that's a...

Just to get a rough chart of comparison

from Fahrenheit to Celsius,

or, you know, an eye for an eye?

Or an orifice for an orifice?

I'm just trying to get a sense of the parameters here.

Uh, Tom, I can't negotiate right now.

But we know, right? We just know.

Sure.

We know.

So you want to run the tree on how personal stuff plays?

Issues, issues, issues.

I can handle the soft soap, Shiv.

Hey, Kendall. Just spoke to Shiv.

Official permission for having of the fun.

Amazing. So happy for you.

Hey, man, can I get this, uh...

- Hey, Ken. - Hey, Frank. Listen.

I've had an approach.

It's kind of a very interesting approach,

and I wanted to get your brain on it.

I heard from the girls. The Dust thing. With the art?

Yeah, I know. I saw them. It's locked down.

They wanted you to know they loved you in the room. But...

I just spoke to the girl. We're good.

Ken, they're already setting this up elsewhere.

But like I said,

they loved you in the room.

What are you talking about?

I think there's other money and they liked it better.

Then we match it.

I tried that already, but...

Seriously, they loved you in the room.

Will you stop telling me they loved me in the fucking room?!

Frank! I heard you the first time.

OK. OK, let me talk to her.

I can fix this.

Hey. Hey. Can we talk for a second?

Can we do this another time?

I just got off the phone to Frank.

What happened? He told me.

I'm sorry, it's nothing personal.

I shouldn't be telling you this,

but I'm about to land a chunk of seed capital

the size of fuckin' Idaho,

so, I mean, whatever it is you need,

I can make it happen. OK?

- Yeah, OK. - OK?

So are we good?

You know, it's just not about that.

Then, like, help me out here,

'cause there's something I'm not seeing.

- It's the name. - Which? You mean "Dust"?

Roy. Kendall Roy.

It'd be like I was marrying Hitler,

and then I'd get to be, what, Mrs. Hitler?

OK, uh, that's not really fair,

Look, that's... that's not me.

I'm not a Roy.

OK? Not really.

I'm sorry. It's cool, we just don't want to be Hitler Incorp...

Can you stop saying Hitler? Please? You don't know what I am.

Consensus is you're a coked-up prick who can't shit straight.

You think you're different?

OK, Angela. You know what,

I'm gonna be frank with you...

Look, I didn't want to do this here.

And I may be being more forthright 'cause of the coke.

I tend to get more forthright on coke.

All right? I'm sorry.

Hey, fuck off!

Hey, man, can I get in on this?

I'm joined in the studio by Senator Gil Eavis. Firstly, Senator,

welcome. We really appreciate it.

Happy to be here, Sharon.

I want to just jump straight in, if we may.

Your wife very tragically took her own life 18 months ago.

The warmest of ATN welcomes.

I think everybody knows about that,

and it's something I live with every day.

But it's not relevant to the issues.

- I want to explore... - The impression you've given

is that it did inform your decision to run.

A lot of things inform a big decision like this.

But what I want to talk about tonight...

But it hasn't been long,

and I guess that what some people may ask is,

what could possibly have caused such a tragedy?

And are you ready so suddenly

to turn around and run for the highest office?

Doesn't he have a line for this?

It's usually... normally OK.

I'm focused on what I think this country needs to do

- to move to... - So you have thought about it,

your mental and emotional state?

I think about my feelings, like most humans...

Oh, no, no. No sarcasm.

It must be incredibly difficult for you

as a person who has had to deal with rumors

swirling about the state of his mental health.

Why don't we stop playing this game of pretend sympathy

where you're just trying to get your viewers to ask,

"What sort of guy has a wife who kills herself?"

- That is... - You wanna make this personal?

Let's talk about Logan Roy, shall we?

The paymaster who set you up in this hack job against me today...

Oh, Senator, come on.

If you want to know about a person,

look at his relationships with his family.

His only daughter

- has come to work for me. - Oh, fuck off.

- Shiv. - I'm not the fucking angle.

So you don't want to take any more questions?

Certainly not from you. Thank you.

Unfortunately, that seems to be

all the time we're going to have with Senator Eavis.

Hey! Kenny!

Whoa. That's a chunk of chang you got there, buddy.

It sure is, Greg.

Maybe... just ease... ease into that, right?

I mean, not all at once?

Can I help you with something, man?

What the fuck's going on? You've been up my ass all night.

No, I just... I'm just keepin' an eye out for you.

I mean, drugs... You don't know where...

Is this Rava? Did she put you up to this?

No.

Then what's your fuckin' deal, man?

Your dad is, I think, a little worried about you is all.

My dad asked you to fuckin' spy on me?

No, not spy, watch...

Family-style watching you.

I'm about to do these four lines of cocaine,

to top up the four I just did,

and then my heart's gonna explode.

So if you want to stop me,

be my guest.

I don't do white drugs.

My dad's gonna be super-disappointed

if his son ODs.

- I know. - So...

What the fuck?

He's counting on you to look after me.

OK, OK, OK! Stop. Stop.

OK. Give it to me.

- Go on. - I'm goin'.

Greg!

Go for it, Greg!

Suck on those big white dicks, you fuckin' pervert.

Greg, you greedy piece of shit.

Oh, my God!

Greg, you total coke whore.

Should I puke?

Not unless you can puke up your entire bloodstream.

- Oh, my God, man. - That is strong drugs.

- I know. I hope you don't die. - Oh, my God!

If you do, your heart is gonna be pumping so hard

it'll probably bring you back to life.

- Where did he go? - Buckle up, fucklehead!

Hi.

- Hello, Pinky. - Hello.

- I'm glad you kept the date. - Well, family.

- How was the play? - Oh, you know,

people pretending to be people.

How are the wedding arrangements?

Very exciting.

Yeah, well, I'm excited. My daughter.

So you saw the interview.

They told me.

You came after the man's wife.

They said.

You're OK with that?

Tell him not to speak about my family,

not on my network...

not on any network, ever again.

Or I'll end him.

Yeah, silence the man who says you're stifling dissent.

I'm a bad father? How dare he.

He's a bad fuckin' husband. He killed his wife.

Oh, come on. Dad.

What if the acquisitions you're making

are actually bad for the country?

He's using you. Can't you see it?

Don't let any of the bullshit overshadow your wedding.

The wedding?

The fucking wedding? I don't give a shit.

Siobhan, come on. Stop screwing around.

I want to talk about you properly.

Come in. I'm tired of this.

You have potential.

I've always thought you were the smartest.

So that's why you tried Kendall and Roman first?

You know what? I am the smartest.

Which is why I can see through you

and this transparent little offer to buy me off.

I've always tried to do right by you, Siobhan.

And maybe...

maybe I shouldn't have.

Maybe I should just let them come for you.

Like who?

Like... I don't know.

But I hear things.

Are you threatening me?

Absolutely not.

If this is the way things are gonna go, then fuck off, Dad.

Then... I'm truly sorry.

So, in terms of Shiv,

where I've landed is

I'm maybe just gonna ask for a handy.

- Think that's OK? - Don't pre-rationalize.

You get off, you eat the shame for dessert.

- Wait. Her? That one? - Yeah. We were talking

for, like, 20 minutes about financial derivatives,

and she just asked me.

My God! Holy shit!

Dad would go fuckin' nuts for her. You should do it.

- Yeah? - Yeah! Fuck yeah!

I'd be all over that.

I'd, like... I'd fuckin'...

Fuck.

OK, well...

I need something. Do you have a Smint?

- What? - Do you have a Smint?

No! Just grab your baloney-pipe and jizz.

- OK. OK. - Yeah. OK.

Champagne?

- Bye. - Bye.

You gotta get into P.R.

That's where the real fuckin' money...

Do you think now would be

a good time to sit down with the old fart?

Dude, did you see that guy jerking off near the hors d'oeuvres?

Dude, that's a fuckin' health hazard.

No. When do you think I can talk to him?

I'd really love to hear something to take home.

Ro-Ro, can you just be fucking cool, man?

Maybe get a slider.

Ask if you can stick your finger up someone's ass, all right, buddy?

- Jeez. - Hey! Fuck you!

I'm not your little pet that you get to kick around.

Oh, I'm sorry. Excuse me, space suit.

Bro.

You think that I can't make your life difficult,

but word in the right ear,

and I could be your migraine, motherfucker.

I came here to talk to the old man on your word,

so make it happen.

- OK. - Yeah?

- All right. - Cool.

I tried to hide... but it finds you.

Wherever you hide, the party finds you.

Sir, this is your final warning.

Absolutely.

Got it.

Wait. What's happening?

Your friend here

keeps telling people he's in love with them,

and it's making people uncomfortable.

My bad. Mixed messages.

It's just we share such strong feelings about gut bacteria

I think I got the wrong end of the stick.

Watch him.

Maybe I should go apologize.

Give her a hug.

My God, dude!

That was insane!

- Oh, yeah? - Yeah. Me and this girl,

we go into this side room and we start making out,

and then I'm touching her

and then she goes down on me,

and then I splooge in her mouth, and...

I know! I know!

And get this. She kisses me

and puts it back in my mouth, and I swallow.

Which, the cum?

I know. So hot!

You swallowed your own load?

Yeah. I heard of it, but I don't...

I didn't know it actually happened.

I haven't heard about it before.

I have. It's a thing. There's a word for it.

I can't remember what it is right now.

So fuckin' hot.

When are we allowed to go home?

We have cars at 5:00.

Greg, I'm having the time of my life.

This is nightmarish.

You ready for your bachelorette party?

They were out of marine uniforms,

so I've come dressed as a political consultant.

Sss...

Relax.

This isn't real.

It's becoming real, which might be a problem for us.

Uh... can I stay?

But with you, as a human dog

just at the foot of the bed?

I love you, Kenny.

- I love you too, man. - I'm tryin' to find this girl,

but I think she's trying to hide from me.

Listen, is there another room for humping?

'Cause I also lost Roman.

- Fuck Roman. - Well, you know,

he was askin' about the dog pound,

and he got kind of riled up.

Is he still talking about that?

Yeah.

- It's pathetic. - Yeah.

He enjoyed it, right?

Oh, yeah!

I mean, you did too.

You know, just messin' around.

Yeah, just messin' around.

Dad's theory was you got two fighting dogs,

you send the weak one away,

you punish the weak one.

Then everyone knows the hierarchy,

then everyone's happy.

So away he went.

I gotta keep lookin'. OK.

Hi! Hey, may I ask you,

where were you on 9/11?

You know what, I... Never mind.

Listen, Sandy.

I appreciate your offer. I'm not getting out.

OK. Well, if you think you

have to tell your father and get back in with him,

- then I... - Keep your money.

Keep your money, bring me in.

We do this properly.

We'll go fuck my dad together.

Takeover.

Leveraged buyout. Hostile.

That's a dual stock situation.

That's not gonna be straightforward.

Price in the toilet, shareholders are pissed...

you and me could force him to the table.

What about the rest of your family?

Fuck the rest of my family.

- Easy to say. - No one has a clue but me.

I know what to do. I see it all.

We take it apart.

Fuck local TV, newspapers, parks...

we bulldoze the whole fuckin' shantytown.

We just keep the juiciest morsels,

turn the thing from a pod of rotting whales

into one bastard great white.

What's your end?

CEO. I'm the only one who knows the architecture.

OK? The emotional corporate architecture.

Well, I could like it. Stewy might not like it.

Fuck Stewy.

Stewy will follow the money like a dog in a cartoon.

And you sure you got the stomach?

Yeah.

I'm good.

Tom.

...sorry to wake you.

Hey. Is everything OK?

No.

He couldn't catch his breath.

Listen, we've been advised, and we are really sorry,

but I don't think it's a

good idea for him to come to the wedding.

Oh, yeah. That sounds sensible.

Shiv.

He really is sorry.

Yeah, me too.

OK, bye.

You OK?

Yeah. I'm great. That's two less wedding dinners

for the caterers to have to organize.

I don't know, Nate.

I don't fuckin' know.

And I would be your point man on this,

so you would not have to deal direct with my dad.

So if we can find a price...

- But there's potential? - It could happen.

Well, fuck, I'm excited.

This is great. This is pure upside.

- Thank you. - Awesome, dude.

Let's jerk him around for a bit,

then throw him back.

This fuckin' family.

Ooh, hey! Come on.

How's it goin'?

What?

What, are you psyching me out?

I'm fuckin' terrified.

Asshole!

Shit.

If the car doesn't come soon,

I'm just gonna swim home, I think.

Greg tells me you swallowed your own load.

Yeah, It was... Yeah. It was pretty wild.

It's cool, though, 'cause it's like I didn't cheat

'cause all the sperm stayed in my own body.

Like a closed loop system. So...

It'd be really nice to see Shiv.

Willa! Hi, I just want to say I love you.

I love you so much.

What's happening? Where's the car?

Arriving in five.

Congratulations, Tom.

I hear you swallowed your own load.

Yeah, I did.

It's been a really wonderful night.

I would love a chicken pot pie.

Thank you.

OK, honey, bye.

Hey, Shiv!

I'm home!

Still got both my eyebrows!

- Oh, hi! - Hey.

Hey, you're back... already.

God, I missed you, honey. God, I missed you.

- I missed you. - How was it?

- Which... Oh, the party? - Yeah.

It was a blast.

- Yeah? - Yeah.

So... what happened?

You know, just...

like, this and that.

Usual. Normal stuff.

Specifically what, Tom?

Wait, what? No. Shiv, you...

I thought you said...

Oh, honey, I'm shitting you.

Oh, my God, OK.

Oh, it's good to have you back.

Yeah, Frank.

Those girls from the art thing,

I want you to put the word around they're junkies,

they're sluts, they're shooting seed capital

straight into their arms.

Let's sink them.

Gentlemen. Shall we?

My man.

