
= 继承之战 S01 -04 释义
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''

== 释义

OK, that's right,
[.my2]
对，就是这样，

along the edge 沿着边缘.
[.my2]
沿着边。

Good. That's good.
[.my2]
好。很好。

Don't patronize  (v.)表现出高人一等的姿态，以高人一等的态度对待;赞助；资 me 以高人一等的态度对待我.
[.my2]
别用那种居高临下的态度对我。

Walking's not good. It's fuckin' normal 他妈的正常.
[.my2]
能走路不算好。这他妈是正常水平。

I'm not. That is good, Mr. Roy.
[.my2]
我没有。这确实很好，罗伊先生。

I need to sit down.
[.my2]
我需要坐下。

-Chair 椅子. -Logan,

[.my2]
-椅子。 -洛根，


if you're not well enough for the charity dinner 慈善晚宴,
[.my2]
如果你身体不适，无法参加慈善晚宴，

I maybe go /with this handsome young man.
[.my2]
我或许可以和这位英俊的年轻人一起去。

OK. Now,
[.my2]
好的。现在，

this is a little trickier (难办的；难对付的) 更棘手.
[.my2]
这个有点难度。

This is the proprioception [生理]本体感觉.
[.my2]
这是本体感觉测试。

That's _side to side_ 左右移动.
[.my2]
那是左右移动。

Turn it off 关掉. It's like being inside a fuckin' commercial (n.a.)电视广告，电台广告;广告;商业的.
[.my2]
关掉它。感觉像在他妈的广告片里。

There you go.
[.my2]
这就对了。

You turn it off yourself.
[.my2]
你自己把它关掉了。

Come on.
[.my2]
来吧。

Where the fuck's she goin'?
[.my2]
她他妈要去哪儿？

Thank you.
[.my2]
谢谢。

Rava, hey, did you decide yet about tomorrow night?
[.my2]
拉瓦，嘿，明晚的事你决定了吗？

It's kind of a big night 重要夜晚 for me.
[.my2]
那对我来说是个重要的夜晚。

I'm making Dad's RECNY ball （大型正式的）舞会 speech 演讲.
[.my2]
我要代爸爸在RECNY晚宴上演讲。

I just kind of assumed 以为 /your "Hopefully" was a "Yes."
[.my2]
我还以为, 你说的“希望可以”就是“同意”呢。

Are you serious 你是认真的吗?
[.my2]
你是认真的吗？

...GDP numbers that showed the US economy
[.my2]
…显示美国经济

maintained a brisk (a.)快的；敏捷的；忙碌的 pace 活跃的速度 of growth
[.my2]
保持了2.8%年增长率的活跃增速

at a 2.8% annual rate.
[.my2]


-How was L.A.? -Great.

[.my2]
-洛杉矶怎么样？ -很棒。


They're all fuckin' nuts 疯子, but great.
[.my2]
他们都他妈是疯子，但很棒。

Can you get onto 联系 Lance about my speech?
[.my2]
你能联系一下兰斯关于我演讲的事吗？

And can we get one of the late night guys 深夜脱口秀的人 to,
[.my2]
还有，我们能找个深夜脱口秀的写手，

-you know, cook me up a bit 帮我准备点素材? -A bit?

[.my2]
-你知道，帮我准备点素材吗？ -一点？


Yeah, a bit. You know, a selection of jokes and riffs 即兴重复段?
[.my2]
对，一点。你知道，就是选一些笑话和即兴段子？

You're gonna do a joke 讲笑话?
[.my2]
你要讲笑话？

What does that mean? I was fuckin' king of the Lampoon 讽刺刊物.
[.my2]
你什么意思？我当年可是他妈的《哈佛妙文》的王者。

Kicked their distribution 发行 into shape 步入正轨.
[.my2]
把他们的发行搞得井井有条。

-I cleared your morning because... -Who's that in my dad's...?

[.my2]
-我把你上午的时间空出来是因为… -谁在我爸爸的…？


because your dad wants to see you.
[.my2]
因为你爸爸想见你。

Guessing you didn't know that.
[.my2]
猜你还不知道吧。

No, I didn't know. But, uh...
[.my2]
不，我不知道。但是，呃…

it's great news. Right?
[.my2]
这是好消息。对吧？

-Did you know? -No, but it's great.

[.my2]
-你知道吗？ -不知道，但很好。


Sure. Oh, sure.
[.my2]
当然。哦，当然。

Shouldn't he have told you?
[.my2]
他不是应该告诉你吗？

OK, uh, listen, I'll just, um...
[.my2]
好吧，呃，听着，我这就，嗯…

get myself straight 整理一下
[.my2]
整理一下自己，

and go and see the old... fuckin' goat 老家伙.
[.my2]
然后去见那个老…他妈家伙。

Ok.
[.my2]
好的。

You look good.
[.my2]
你看起来不错。

Uh, well, yeah. Well, thank you.
[.my2]
呃，嗯，是的。嗯，谢谢。

Whoops 哎哟. Uh, Grace, um...
[.my2]
哎哟。呃，格蕾丝，嗯…

OK, see, this is why your staying here doesn't work 行不通.
[.my2]
看吧，这就是为什么你住在这里行不通。

There are five bathrooms in this place, and you're here.
[.my2]
这地方有五个卫生间，而你偏偏在这儿。

Why are you here? Like, right now I have to fart 放屁, and I'm not.
[.my2]
你为什么在这儿？比如，现在我想放屁，但我不能放。

-I'm physically not farting because you're here. -OK.

[.my2]
-因为你在这儿，我生理上没法放屁。 -好吧。


I'm just feeling a little oppressed 感到压抑 is all, OK?
[.my2]
我只是觉得有点压抑，好吗？

Thank you.
[.my2]
谢谢。

Do you want me to speak to Connor and confirm table arrangements 确认座位安排?
[.my2]
需要我和康纳确认一下座位安排吗？

-Uh-huh. -We're hosting basically the same as last year,

[.my2]
-嗯。 -我们基本上和去年招待的客人一样，


plus Joyce and Daniel. Is that OK?
[.my2]
加上乔伊斯和丹尼尔。可以吗？

I didn't go last year, Shiv.
[.my2]
我去年没去，希芙。

Yes, you did.
[.my2]
不，你去了。

Remember we had that racist Belgian GS guy?
[.my2]
记得那个有种族歧视的比利时高盛家伙吗？

And his wife who wanted to kill herself?
[.my2]
还有他那想自杀的妻子？

Siobhan, I think I would remember
[.my2]
西沃恩，我觉得我应该会记得

our first Roy Endowment Creative New York ball together.
[.my2]
我们第一次一起参加罗伊创意纽约捐赠晚宴。

I was trapped in Honk Kong, scoping out 考察 theme parks.
[.my2]
我当时被困在香港，考察主题公园呢。

-Really? -Yeah. Honey,

[.my2]
-真的吗？ -是的。亲爱的，


growing up I used to look at the pictures of the RECNY
[.my2]
小时候我常常看妈妈《名利场》杂志里

in Mom's "Vanity Fairs."
[.my2]
RECNY晚宴的照片。

And now, a little boy from St. Paul's going,
[.my2]
而现在，一个从圣保罗来的小男孩要去参加了，

with the most beautiful gal 姑娘 in the world.
[.my2]
和世界上最美丽的姑娘一起。

-Oh, what the fuck? -What?

[.my2]
-哦，搞什么鬼？ -怎么？


It's quite a haunting 萦绕心头的 image, isn't it?
[.my2]
这画面挺让人难忘的，不是吗？

The eye almost seems to follow you around the room.
[.my2]
那双眼睛几乎像是在房间里跟着你转。

What is this?
[.my2]
这是什么？

You know, your client, the future senator? Apparently,
[.my2]
知道吗，你的客户，那位未来参议员？显然，

this is her husband's asshole 肛门.
[.my2]
这是她丈夫的肛门。

What? Fuck off 滚开. Can you prove that?
[.my2]
什么？滚蛋。你能证明吗？

He posted it himself with the caption 标题: "Check out my asshole."
[.my2]
他自己发的，标题是“看看我的屁眼”。

It was on a site called Filthy Rich.
[.my2]
在一个叫“肮脏的富人”的网站上。

-Has everybody got it? -Just us, I believe, right now.

[.my2]
-大家都收到了吗？ -目前我相信只有我们。


Leaked to ATN. My buddy thought I'd be intrigued 感兴趣.
[.my2]
泄露给ATN了。我哥们觉得我会感兴趣。

All right, well, bring it on 放马过来.
[.my2]
好吧，那就放马过来吧。

Ooh, feisty 暴躁的.
[.my2]
哦，火气不小。

What, they're not gonna run it 刊登?
[.my2]
怎么，他们不打算刊登吗？

It's dirty, it's weird,
[.my2]
这很下流，很怪异，

and it's evidence of precisely the kind
[.my2]
而且这恰恰证明了那种

of disgusting liberal metro butt-love 屁股之爱
[.my2]
恶心的自由派都市人的屁股之爱，

that makes our viewership angry enough to buy pharmaceuticals 药品.
[.my2]
这会让我们的观众气得去买药（看我们的节目消气）。

-Oh, OK, fuck you very much. -OK, well,

[.my2]
-哦，好吧，去你妈的。 -好吧，嗯，


hate to be the bearer of bad news 坏消息的传递者.
[.my2]
真不想当这个报丧的。

What do we call it, "An intimate part 私密部位 of his body"?
[.my2]
我们怎么称呼它，“他身体的私密部位”？

No! That sounds like his dick 阴茎.
[.my2]
不行！那听起来像是指他的阴茎。

Or just his "Anus" 肛门?
[.my2]
或者就直接用“肛门”？

"Anus"? At breakfast?
[.my2]
“肛门”？在早餐时间（谈论）？

That's a fucking juice-dropper 让人倒胃口的事.
[.my2]
那他妈太倒胃口了。

"A very private part of his body."
[.my2]
“他身体的一个非常私密的部位。”

It's boring. And she needs to get more sleep.
[.my2]
太无聊了。而且她需要多睡会儿。

-Karen. -Yeah?

[.my2]
-凯伦。 -嗯？


-You sleepin' OK? -I thought so.

[.my2]
-你睡得好吗？ -我觉得还行。


Yeah? Are you sleeping on your face?
[.my2]
是吗？你是趴着睡的吗？

-Boom! Ouch. -I'm just kidding 开玩笑.

[.my2]
-砰！哎哟。 -我开玩笑的。


-You look great. -How about me, darling?

[.my2]
-你看起来气色很好。 -那我呢，亲爱的？


How do I look?
[.my2]
我看起来怎么样？

FIE, Mark. Fuckable in an emergency 紧急情况下可以上.
[.my2]
一般，马克。紧急情况下可以上。


[.my1]
.案例

"FIE" 是一个非常古老、几乎不再使用的感叹词，表示厌恶或轻蔑，类似于“呸！”或“哼！”。这里说话人故意使用这个古词来嘲讽和贬低。
"Fuckable in an emergency" 是极其粗俗和物化的表达，意思是“在紧急情况下（找不到更好的人时）可以考虑发生关系”，带有强烈的侮辱和戏谑意味。
例句：
-He uttered "Fie!" upon seeing the mess. (他看到混乱时哼了一声。)

-That remark was beyond the pale, fie on you! (那句话太过分了，呸！)

-She joked that he was only fuckable in a power outage. (她开玩笑说只有在停电时才会考虑和他上床。)

Now, if we don't call out 揭穿 this frigid little phony 虚伪的人,
[.my2]
现在，如果我们不揭穿这个冷漠的小骗子，

who will?
[.my2]
那谁来揭穿？

Yeah. Good.
[.my2]
是的。好。

Hey, Dad.
[.my2]
嘿，爸爸。

I didn't know you were coming in.
[.my2]
我不知道你要来公司。

Did--Did Gerri?
[.my2]
是…是格里（通知你）吗？

Do I need permission 许可?
[.my2]
我需要许可吗？

Hey, come on. Screw you 去你的.
[.my2]
嘿，得了吧。去你的。

Just making sure you're not selling
[.my2]
只是确保你没有再背着我

any more of the company from under me 背着我.
[.my2]
卖掉公司的更多股份。

Oh, you want to get into that 谈这个?
[.my2]
哦，你想谈这个？

You know, you put a hole 弄出窟窿 in us
[.my2]
知道吗，你背了一屁股债，

by taking on a shitload of debt 大量债务.
[.my2]
给我们搞出了个大窟窿。

But look, this is, uh...
[.my2]
但是你看，这个，呃…

it's great to see you.
[.my2]
见到你很好。

Are you sure you're OK?
[.my2]
你确定你没事吗？

Maybe you should get a briefing 简报 and get some rest, yeah?
[.my2]
也许你应该听个简报然后休息一下，嗯？

Yeah, OK.
[.my2]
是的，好吧。

Joseph!
[.my2]
约瑟夫！

Bring the wheelchair 轮椅! I need to take a leak 小便!
[.my2]
拿轮椅来！我要去撒尿！

Hey. So, uh, Dad's back.
[.my2]
嘿。所以，呃，爸爸回来了。

Back where? Back in the chair 回到主席位?
[.my2]
回哪儿？回到主席位了？

Seems kind of fast, right?
[.my2]
似乎有点快，对吧？

But, you know, it's good, obviously.
[.my2]
但是，你知道，这显然是好事。

You'd love it if his brain fell out the back of his head.
[.my2]
你巴不得他的脑子从后脑勺掉出来吧。

Jesus. I'm just scared in case 以防...
[.my2]
天啊。我只是害怕万一…

You're scared in case he tries to push you out 排挤你
[.my2]
你是害怕他试图排挤你，

and your plans for, you know, Uber for news and Facebook for cats
[.my2]
以及你的那些计划，你知道，新闻界的优步，猫中脸书，

and open plan office 开放式办公室.
[.my2]
还有开放式办公室。

You want a dance platform jerkin' off idea gloop into...
[.my2]
你想把那些在跳舞平台上打飞机的想法灌进…

think boxes.
[.my2]
思维盒子裡。

I gotta go.
[.my2]
我得走了。

-Roman. Good morning. -Frank.

[.my2]
-罗曼。早上好。 -弗兰克。


No, correction 更正, it is not a good morning from my POV 从我角度看
[.my2]
不，更正一下，从我的角度看这不是一个美好的早晨，

because you're here and I fuckin' hate you.
[.my2]
因为你在这儿而我他妈恨你。

Oh, come on, kid 小子.
[.my2]
哦，得了吧，小子。

What the fuck is goin' on?
[.my2]
他妈的发生什么事了？

Your dad asked me to come back.
[.my2]
你爸爸请我回来的。

Oh, the fuckin'--the weasel 黄鼠狼 prevails 得逞.
[.my2]
哦，他妈的一一这黄鼠狼得逞了。

That'd be a good name for your autobiography 自传,
[.my2]
那会是你自传的好名字，

if they did books by jerks 混蛋.
[.my2]
如果他们会给混蛋出书的话。

God, you're pathetic 可悲的.
[.my2]
天啊，你真可悲。


-He apologized 道歉. -Sure, man. Yeah.

[.my2]
-他道歉了。 -当然，老兄。是的。


He didn't apologize when he hit our au pair 互惠生 with his car.
[.my2]
他开车撞到我们家互惠生的时候可没道歉。


He wants me to show you the ropes 传授诀窍.
[.my2]
他想让我带你熟悉业务。


"It was her fault for being too short," He said.
[.my2]
“都怪她个子太矮，”他说。


Ok.
[.my2]
好吧。


-Nothing else? -What do you mean?

[.my2]
-没别的了？ -你什么意思？


I mean, in terms of what went up there 被上传的内容.
[.my2]
我的意思是，关于被上传的内容。


Because first it's a finger, then it's a fist.
[.my2]
因为一开始是手指，然后是拳头。


then it's a dildo 假阳具 shaped like Richard Nixon.
[.my2]
接着是个理查德·尼克松形状的假阳具。


Ohh. Fuck this 去他的!
[.my2]
哦。去他的！


A man wouldn't be getting this 受到这种对待.
[.my2]
男人就不会受到这种对待。


Let's say that.
[.my2]
我们这么说吧。


Yeah, agreed. Hundred percent.
[.my2]
是的，同意。百分之百。


But for us, now,
[.my2]
但对我们来说，现在，


this isn't gonna go away 消失,
[.my2]
这事不会轻易过去，


so we need to be clear, we need to know the details.
[.my2]
所以我们需要搞清楚，我们需要知道细节。


I think you need to talk to your husband again.
[.my2]
我觉得你需要再和你丈夫谈谈。


It's not going away because ATN won't let it go away.
[.my2]
这事过不去是因为ATN不肯让它过去。


So I think you should talk to your father.
[.my2]
所以我觉得你应该去和你父亲谈。


I just hope the seating plan 座位安排 holds 保持不变.
[.my2]
我只希望座位安排能保持不变。


If it does...
[.my2]
如果真能这样…


look out 小心, Middle East,
[.my2]
中东地区可得小心了，


'cause I can fix anything 我能解决任何问题.
[.my2]
因为我能搞定任何事。


I just want you to know
[.my2]
我只想让你们知道


you're the best damn bunch of people 一帮人
[.my2]
你们是我有幸为之效力的


I ever had the honor to work for.
[.my2]
最棒的一帮人。


Thank you very much.
[.my2]
非常感谢。


Here he comes.
[.my2]
他来了。


Bill. The best boss that ever lived.
[.my2]
比尔。有史以来最好的老板。


It's like Mandela fucked Santa and gave birth to Bill.
[.my2]
就好像曼德拉上了圣诞老人然后生出了比尔。


[.my1]
.案例

这是一个极其粗俗且夸张的比喻，将比尔（Bill）形容为两位备受爱戴的伟人（曼德拉和圣诞老人）的结合体，意在表达极度的赞美和奉承，但方式非常不得体且充满讽刺意味。
例句：
-He described his new teacher as if Einstein had a baby with Mother Teresa. (他描述他的新老师就像爱因斯坦和特蕾莎修女生了个孩子。)

-This dish is so good, it's like a Michelin chef made love to a farmer's market. (这道菜太好吃了，就像米其林厨师和农夫市集相爱了。)

Thank you, everybody.
[.my2]
谢谢大家。


Did you hear about Logan?
[.my2]
你听说洛根的事了吗？


They say he came in 来公司了.
[.my2]
他们说他也来公司了。


Uh, uh-huh. Yeah, I knew.
[.my2]
呃，嗯哼。是的，我知道。


But I couldn't say 不能说.
[.my2]
但我不能说。


Thank you.
[.my2]
谢谢。


Thank you so much.
[.my2]
非常感谢。


Come on, you genial 和蔼的 old fucker 老家伙.
[.my2]
来吧，你这和蔼的老家伙。


Get in here already, before it's time for me to retire 退休.
[.my2]
快进来吧，趁我还没到退休的时候。


-Hey, Bill! -Sorry about all that.

[.my2]
-嘿，比尔！ -刚才那些，抱歉了。


No problem, Bill! I just hope one day
[.my2]
没问题，比尔！我只希望有一天


I can eventually inspire similar affection 激发同样的喜爱.
[.my2]
我也能最终激发起大家同样的喜爱。


Uh, this is,
[.my2]
呃，这是，


this is Greg,
[.my2]
这是格雷格，


new kid I took under my wing 庇护 when I started.
[.my2]
我刚开始时关照的新人。


I'm actually a part of the fam...
[.my2]
我其实是家族的一...


Doesn't need to hear your life story 人生故事, Greg.
[.my2]
没人想听你的人生故事，格雷格。


-So, uh, thanks for everything. -No.

[.my2]
-所以，呃，感谢你做的一切。 -不客气。


But listen, before I do the final photo,
[.my2]
但听着，在我拍最后一张合影前，


there's a... thing I need to mention.
[.my2]
有件…事我需要提一下。


-Cool. -You know, just us?

[.my2]
-好的。 -你知道，就我们几个？


Oh. Yeah. Yeah.
[.my2]
哦。是的。是的。


-Great to meet you. -Yeah. Thanks for understanding.

[.my2]
-很高兴认识你。 -是的。谢谢理解。


-Thank you, Bill. -You're welcome.

[.my2]
-谢谢你，比尔。 -不客气。


OK. So, uh...
[.my2]
好的。那么，呃…


I've turned off the Wi-Fi, and...
[.my2]
我已经关掉了Wi-Fi，而且…


this is, uh... this is air-gapped 物理隔离的,
[.my2]
这个，呃…这是物理隔离的，


so I'm gonna create a Word document for you,
[.my2]
所以我要为你创建一个Word文档，


and then I'm gonna print it, because I don't want
[.my2]
然后我会把它打印出来，因为我不想


anything with my handwriting 笔迹 on it.
[.my2]
留下任何我的笔迹。


I think someone has been watching
[.my2]
我觉得有人退休后


a few too many spy movies 间谍电影 since they retired, eh, Bill?
[.my2]
间谍电影看多了点，嗯，比尔？


Yeah, maybe.
[.my2]
是啊，可能吧。


Ah. Here.
[.my2]
啊。给。


This, uh, this is the number
[.my2]
这个，呃，这是一组


of a set of storage files in the depository 档案库,
[.my2]
档案库里存储文件的编号，


and the subject is, well,
[.my2]
主题嘛，嗯，


something that... it's not a big deal 没什么大不了的,
[.my2]
是件…没什么大不了的事，


but it needs to be handled 处理,
[.my2]
但需要处理一下，


and, uh... you're in the family.
[.my2]
而且，呃…你是家族成员。


So... this is the name of the legal office
[.my2]
所以…这是那家


that is the intermediary 中间人,
[.my2]
作为中间人的法律事务所的名字，


and this is the person outside the firm
[.my2]
这是公司外部


that we've been using as a firewall 防火墙
[.my2]
我们一直用作防火墙的人，


to deal with the blowback 后果 from the NDAs 保密协议.
[.my2]
用来处理保密协议带来的后果。


It's not a big deal, Tom.
[.my2]
不是什么大事，汤姆。


Right, but what is it, Bill?
[.my2]
对，但到底是什么事，比尔？


Well...
[.my2]
嗯…


You...you have two viable options 可行的选择.
[.my2]
你…你有两个可行的选择。


I can tell you everything, and that's fine.
[.my2]
我可以告诉你一切，这没问题。


Or I can not tell you, and... you wouldn't know,
[.my2]
或者我可以不告诉你，然后…你就不会知道，


and then you can steer clear of 避开 the whole death pit 死亡陷阱.
[.my2]
这样你就能避开整个死亡陷阱。


And that would be fine, too.
[.my2]
那样也没问题。


So, I mean,
[.my2]
所以，我的意思是，


the nice news is, either way, both ways, everything is fine.
[.my2]
好消息是，无论哪种方式，一切都没事。


Just keep the nuclear rods 核燃料棒 cool, nothing's gonna blow 爆炸.
[.my2]
只要让核燃料棒保持冷却，就不会爆炸。


OK, so...there's the death pit,
[.my2]
好吧，所以…有个死亡陷阱，


and at the bottom of the death pit there's nuclear rods?
[.my2]
死亡陷阱底下还有核燃料棒？


Well...
[.my2]
这个…


You want to give me the good news now, Bill?
[.my2]
你现在是想告诉我好消息吗，比尔？


Excuse me.
[.my2]
打扰一下。


-Photographer's ready. -Terrific 太棒了!

[.my2]
-摄影师准备好了。 -太好了！


Thanks, Kelly.
[.my2]
谢谢，凯莉。


And...
[.my2]
然后…


print 打印.
[.my2]
打印。


OK, you need to tell Dad to back the fuck off 滚远点.
[.my2]
好吧，你得告诉爸爸让他滚远点。


Hey, shouldn't you be at 1 OAK or something by now?
[.my2]
嘿，你这会儿不是该在1 OAK之类的夜店了吗？


You know he rehired 重新雇用 Frank to babysit 看管 me?
[.my2]
你知道他又雇了弗兰克来看管我吗？


I don't need a babysitter.
[.my2]
我不需要保姆。


OK? Especially one I don't get to fuck.
[.my2]
懂吗？尤其是我还上不了的那个。


-Seriously? -Yes.

[.my2]
-认真的？ -是的。


-Frank is back? -Yeah. I mean, you're CEO.

[.my2]
-弗兰克回来了？ -是啊。我的意思是，你是CEO。


Can he even do that?
[.my2]
他能这么做吗？


I don't...
[.my2]
我不…


It's... It's a question.
[.my2]
这…这是个问题。


OK, well, have a talk with him,
[.my2]
好吧，嗯，跟他谈谈，


tell him to butt out 别插手,
[.my2]
告诉他别插手，


because we are running the show 掌权 now.
[.my2]
因为现在是我们掌权。


Tell him he needs to go back to bed
[.my2]
告诉他他需要回去睡觉，


and eat some soup, get some rest.
[.my2]
喝点汤，休息休息。


Look, relax 放松, OK?
[.my2]
听着，放松点，好吗？


The, uh, you know,
[.my2]
那个，呃，你知道，


the dinosaur 恐龙 is having one last roar 咆哮 at the meteor 流星
[.my2]
这只恐龙不过是在流星撞上来之前最后吼一声，


before it wipes him out 消灭他. But look,
[.my2]
但你看，


...you're doing a great job.
[.my2]
…你做得很好。


Thank you. Thanks, man.
[.my2]
谢谢。谢谢你，老兄。


It's actually good to hear. It's a big job.
[.my2]
听到这个真好。这是个重任。


I know it, bro 兄弟. Tell me about it.
[.my2]
我知道，兄弟。可不是嘛。


Do you want some help? I can help you,
[.my2]
需要帮忙吗？我可以帮你，


we can tag-team it 接力完成 on Dad's speech at Sad Sack Wasp Trap.
[.my2]
我们可以接力完成爸爸在“穷酸白人佬聚会”上的演讲。


[.my1]
.案例

"Sad Sack Wasp Trap" 是一个带有侮辱性的虚构活动名称。
"Sad Sack" 指可怜虫、窝囊废。
"Wasp" 指白人盎格鲁-撒克逊新教徒，常指美国主流社会精英。
"Trap" 指陷阱。
整个短语可能意在讽刺该活动聚集了一群无趣、刻板的精英人士。
例句：
-He mocked the charity gala as a gathering of boring old farts. (他嘲笑那个慈善晚宴是无聊老家伙的聚会。)

-She called the country club a "stuffy rich people's prison." (她称那个乡村俱乐部是“沉闷的有钱人监狱”。)

Um, I guess, yeah,
[.my2]
呃，我想，是的，


I mean, it is a CEO thing,
[.my2]
我的意思是，这毕竟是CEO的事，


so, I mean, like I have a whole thing prepared
[.my2]
所以，我是说，比如我准备了整套东西


-with jokes, and so... -You're doing jokes 讲笑话?

[.my2]
-带笑话的，所以… -你要讲笑话？


Why does everyone keep saying that? I'm funny.
[.my2]
为什么大家都这么说？我很搞笑。


Yup. I'm sure you're gonna kill it 大获成功.
[.my2]
是的。我相信你肯定会讲得很棒。


-Who you taking? -Uh, no one. Rava's busy.

[.my2]
-你带谁去？ -呃，没人。拉瓦没空。


-Doesn't want to? Got it. -So maybe I'll roll solo 单独行动.

[.my2]
-是不想去吧？明白了。 -所以也许我自己去。


How's that gonna look?
[.my2]
那看起来像什么样子？


CEO can't even get an ugly sister 丑姐姐 to go to the ball?
[.my2]
CEO连个丑姐姐都请不动去舞会？


-You know who I'd like to take? -Hmm?

[.my2]
-你知道我想带谁去吗？ -嗯？


Anna Newman. That blonde chick 金发妞 from ATN?
[.my2]
安娜·纽曼。ATN那个金发妞？


The bl... Oh, shit, yeah! I'd fuck that in a minute 立刻.
[.my2]
那个金…哦，靠，对！我立马就想上她。


-Take her. -It's not cool 不合适. I'm her boss.

[.my2]
-带她去啊。 -这不合适。我是她老板。


Oh, come on, what a pathetic beta-cuck 可悲的弱男.
[.my2]
哦，得了吧，真是个可悲的弱男。


[.my1]
.案例

"beta-cuck" 是网络侮辱性用语，结合了 "beta"（指社会等级中地位较低的男性）和 "cuck"（是 "cuckold"（戴绿帽者）的缩写，带有强烈的贬低和蔑视意味，用来攻击男性缺乏男子气概、软弱可欺。
例句：
-He called anyone who disagreed with him a "snowflake beta." (他称任何不同意他的人是“玻璃心弱鸡”。)

-The online trolls resorted to name-calling like "cuck" to provoke a reaction. (网络喷子用“绿帽龟”之类的辱骂来挑衅。)

"Uh, excuse me, uh, would it be cool,
[.my2]
“呃，不好意思，呃，这样行吗，


'cause I have something very secret in my pants.
[.my2]
因为我裤子里有点秘密。


Would it be OK to show, please? Or is that a trigger warning 触发警告?"
[.my2]
可以给您看看吗？还是这需要触发警告？”


Jesus, Roman, you're a walking fuckin' lawsuit 行走的诉讼案.
[.my2]
天啊，罗曼，你他妈就是个行走的诉讼案。


Uh, no, I'm honest, I'm just like,
[.my2]
呃，不，我很诚实，我就直接说，


"Hey, I like your face. I wanna fuck your face.
[.my2]
“嘿，我喜欢你的脸。我想干你的脸。


Can I cum on your face?"
[.my2]
能射你脸上吗？”


Which is why my face is drowning in pussy 被女人包围 and you're not even fucking your wife.
[.my2]
所以我的脸被女人包围，而你连你老婆都上不了。


Too far 过分了. Eeh! Sorry, it just...
[.my2]
太过分了。哎！抱歉，只是…


them's the facts 事实如此.
[.my2]
事实就是这样。


... No, thank you!
[.my2]
…不，谢谢你！


Please leave me alone 别打扰我, please! Thank you!
[.my2]
请别打扰我，拜托！谢谢你！


I... I got it.
[.my2]
我…我自己来。


Morning.
[.my2]
早上好。


OK. Give me a hand 帮个忙. Yeah.
[.my2]
好的。帮我一下。嗯。


Uh, personal first,
[.my2]
呃，先看个人相关的，

then the corporate 公司的.
[.my2]
然后是公司相关的。


Corporate.
[.my2]
公司。


Um, OK.
[.my2]
嗯，好的。


Well, personal, nothing much.
[.my2]
嗯，个人方面，没什么大事。


Pre-ball piece 舞会前的报道,
[.my2]
舞会前的报道，

profiles of endowment recipients 捐赠接受者简介,
[.my2]
捐赠接受者的简介，

that's all great,
[.my2]
这些都很好，

and just a little piece on your health,
[.my2]
还有一小段关于你健康状况的，

but I don't think you need to hear that.
[.my2]
但我觉得你不需要听那个。


Say it 说出来.
[.my2]
说。


Um, "Kendall Roy will give the traditional address 传统致辞
[.my2]
嗯，“肯德尔·罗伊将在今晚的RECNY慈善舞会上发表传统致辞，

at the RECNY charity ball tonight,
[.my2]
这标志着即使在中风康复后，

in a sign that even after recovery from his stroke,
[.my2]
洛根·罗伊也打算逐步退出公共事务。”

Logan Roy is intending to wind down 逐步结束 from public duties."
[.my2]


Where did he get that? Who gave him that?
[.my2]
他从哪儿得来的消息？谁给他的？

-I... I don't know. -Well, here's an idea 有个主意: find out 查清楚.

[.my2]
-我…我不知道。 -嗯，给你个主意：去查清楚。


Or find some other prick 讨厌的人 to pay ya a million a fuckin' year.
[.my2]
或者找个别的混蛋去付你他妈一年一百万。


Ok.
[.my2]
好的。


I just gotta tell you, handling the ball 处理舞会事宜,
[.my2]
我得告诉你，处理舞会事宜，

it's just not a big deal 没什么大不了的 for me,
[.my2]
对我来说根本不算什么，

which is the thing that's so nice.
[.my2]
这正是美妙之处。

-It is not a big deal. -"Winding down."

[.my2]
-这不算什么。 -“逐步退出。”


Winding fucking down. I'm winding up 准备大干一场.
[.my2]
退他妈出。我正要大干一场。


It's just funny, being in charge 负责.
[.my2]
当家作主的感觉真有意思。

I remember years ago
[.my2]
我记得多年前

I'd be at the table between you and Mom
[.my2]
我坐在你和妈妈中间，

and we'd look down, and there'd be the mayor,
[.my2]
我们往下看，能看到市长，

and all the names of old New York,
[.my2]
所有纽约老牌名流，

and you'd whisper in my ear, you'd say,
[.my2]
你会在我耳边低语，说，

"That Astor used to be that, and he ran this
[.my2]
“那个阿斯特以前是干那个的，他管着这个，

till he SNAFUed 搞砸了 that,
[.my2]
直到他把那事搞砸了，

and he's porking 与...性交 her, and she's a slut 荡妇."
[.my2]
他正在上她，而她是个荡妇。”

And it was just... A very lovely time.
[.my2]
那真是…一段非常美好的时光。


Yeah.
[.my2]
是啊。


Your mom loved all that.
[.my2]
你妈妈很喜欢那些。


... Fuckin' Wasp Trap.
[.my2]
…他妈的白人佬聚会。


What would you think about
[.my2]
你觉得

me taking over a little on the foundation 基金会?
[.my2]
我稍微接管一下基金会怎么样？


Could we pivot it away from 转向 sick kids and contemporary dance 当代舞蹈
[.my2]
我们能把它从病童和当代舞蹈转向

and toward tax reform 税制改革?
[.my2]
税制改革吗？

-Huh? -To be frank 坦白说, everyone's dancing anyway,

[.my2]
-嗯？ -坦白说，反正大家都会跳舞，


and there are a lot of charities
[.my2]
而且有很多慈善机构

that cater to 迎合 sad sacks 可怜虫... God knows I love 'em,
[.my2]
是迎合可怜虫的…天知道我喜欢他们，

but hey, what about lending a hand 帮忙 to stimulate free enterprise 自由企业?
[.my2]
但是嘿，帮帮忙刺激一下自由企业怎么样？


Yeah, well, let's... let's see how tonight goes, huh?
[.my2]
是啊，嗯，咱们…咱们看看今晚情况如何，嗯？


Yeah.
[.my2]
好吧。


I don't have time for this shit 没时间耗在这破事上.
[.my2]
我没时间耗在这破事上。


-Hey. -Hi.

[.my2]
-嘿。 -嗨。


Uh, so... look,
[.my2]
呃，所以…听着，

I want you to call off your dogs 停止攻击.
[.my2]
我要你停止攻击。


Mm-hmm.
[.my2]
嗯。


Because this obsession with 对...着迷 Joyce,
[.my2]
因为对乔伊斯的这种穷追不舍，

it's... it's out of line 过分.
[.my2]
这…这太过分了。


It's sitting very high on your half hour 你节目的重要位置.
[.my2]
在你半小时的节目里占了很重要的位置。


Uh-huh.
[.my2]
嗯哼。


And it's vindictive 报复性的.
[.my2]
而且是报复性的。


And actually, it's bad for democracy 民主.
[.my2]
实际上，这对民主不利。


Are you going to respond 回应?
[.my2]
你要回应吗？


Well, I think it's important to remember
[.my2]
嗯，我觉得重要的是要记住

that I'm not the one taking pictures of my asshole here.
[.my2]
我可不是那个给自己屁眼拍照的人。


Yeah.
[.my2]
是啊。


Are you running this because you think my dad likes this shit?
[.my2]
你报道这个是因为你觉得我爸爸喜欢这种破事吗？


Oh, he wouldn't put that kind of pressure on his people.
[.my2]
哦，他不会给他的人施加那种压力。


Ok.
[.my2]
好吧。


Look, if I could get some
[.my2]
听着，如果我能搞到一些

nasty little tidbits 丑闻 on some other folk,
[.my2]
关于其他一些人的丑闻，

could you ramp this down 降低热度?
[.my2]
你能把这事压下去吗？


We're not the only ones running it, Shiv.
[.my2]
不是只有我们在报道，希芙。


It's a hugely popular story.
[.my2]
这是个超级热门的故事。


Yeah, but you're leading it 主导报道, Eva.
[.my2]
是啊，但你是主导者，伊娃。


You had a ten-minute "Sexpert" Segment 专家环节
[.my2]
你在一个新闻频道上

on "How to keep your man happy in bed,"
[.my2]
搞了个十分钟的“性专家”环节，讲“如何让你的男人在床上开心”，

on a news channel.
[.my2]


OK, you've said your piece 发表了意见, so...
[.my2]
好吧，你的意见说完了，所以…

and I've listened.
[.my2]
我也听了。


-Great. -Great.

[.my2]
-很好。 -很好。


Actually, no. You know what?
[.my2]
实际上，不。你知道吗？


I'm saying as her strategist 战略师, this level of attack
[.my2]
我作为她的战略师要说，这种程度的攻击

begins to reflect on your professional judgement 专业判断.
[.my2]
开始影响你的专业判断了。


And you need to think about the future, because this...
[.my2]
你需要考虑未来，因为这…

this is the old world 旧世界,
[.my2]
这是旧世界，

and someday, in this world, things will change.
[.my2]
总有一天，在这个世界里，事情会改变的。


You know I wouldn't let any other strategist in the building,
[.my2]
你知道我不会让任何其他战略师进这栋楼，

let alone this floor.
[.my2]
更不用说这一层了。


Well, I am very grateful 感激.
[.my2]
嗯，我非常感激。


So when we're talking professional judgement,
[.my2]
所以当我们谈论专业判断时，

good to bear in mind 记住 that you're only here
[.my2]
最好记住你之所以能在这里

because your name matches the one carved on the building.
[.my2]
只是因为你的姓和刻在这栋楼上的那个一样。


OK, last thing.
[.my2]
好的，最后一件事。


For the press and comms 公关,
[.my2]
对新闻和公关部门来说，

it's clear, right, that I'm CEO.
[.my2]
很清楚，对吧，我是CEO。


We hope one day my dad will be back, we don't know when.
[.my2]
我们希望我爸爸有一天能回来，但我们不知道是什么时候。


Thank you. Thanks, guys.
[.my2]
谢谢。谢谢各位。


Hey, Kendall. Stewy's here.
[.my2]
嘿，肯德尔。斯图威来了。


I just put him in the South Tank
[.my2]
我把他安排在南方会议室了，

in case you want to keep it on the DL 低调处理.
[.my2]
以防你想低调处理。


Hey, Kendall. Can I grab five 占用五分钟?
[.my2]
嘿，肯德尔。能占用你五分钟吗？


Uh-huh.
[.my2]
嗯。


Um, there's something, uh,
[.my2]
嗯，有件事，呃，

something that you don't know about,
[.my2]
一件你不知道的事，

and maybe it's probably
[.my2]
而且可能

something that you don't want to know about.
[.my2]
是一件你不想知道的事。


And, uh...
[.my2]
而且，呃…


You know what my dad always said?
[.my2]
你知道我爸爸常说什么吗？


He'd say he loved all his employees,
[.my2]
他会说他爱他所有的员工，

but he particularly loved the guys
[.my2]
但他尤其喜欢那些

who ate the shit for him 替他背黑锅 and he never even knew it.
[.my2]
替他背了黑锅而他甚至从不知道的人。


Got it 明白了.
[.my2]
明白了。


Got it. Excuse me while I get myself a knife and a fork
[.my2]
明白了。失陪一下，我去拿副刀叉

and some Hollandaise 荷兰酱.
[.my2]
和一些荷兰酱。


-Hey! -Hey, bro 兄弟.

[.my2]
-嘿！ -嘿，兄弟。


How's it goin'?
[.my2]
怎么样？


-Good. What's up? -So your dad's in?

[.my2]
-挺好。什么事？ -所以你爸爸来公司了？


Yup, he made it in.
[.my2]
是的，他来了。


Which we were all, uh, delighted about 对此很高兴.
[.my2]
我们所有人都，呃，对此感到高兴。


-You were delighted about? -Sure.

[.my2]
-你们很高兴？ -当然。


Sure. What's the story 怎么回事?
[.my2]
当然。怎么回事？


No, he's great, you know,
[.my2]
不，他很好，你知道，

he likes to remind us he's still alive.
[.my2]
他喜欢提醒我们他还活着。


It's great to get his take 听取他的意见, but he needs a lot of rest.
[.my2]
听取他的意见很好，但他需要大量休息。


-Dad. Hey. Just talkin' about you. -Sir Roy. Logan.

[.my2]
-爸爸。嘿。正说起你呢。 -罗伊爵士。洛根。


It's just great to see you. How have you been?
[.my2]
见到你太好了。你最近怎么样？


So, you're the little schmuck 卑鄙的人 who owns such a big chunk of 一大块 me.
[.my2]
所以，你就是那个占了我一大块股份的小混蛋。


Dad, it's Stewy. You guys have met like a million times.
[.my2]
爸爸，这是斯图威。你们见过无数次了。


Excuse me barging in 闯进来,
[.my2]
抱歉闯进来，

it's just Gerri told me I have a meeting with Opalite later...
[.my2]
只是格里告诉我稍后要和Opalite开会…

just to say, "I like it. Buy it."
[.my2]
就想说，“我喜欢。买下来。”


-OK, Ken? -OK, good thought 想法不错.

[.my2]
-行吗，肯？ -好的，想法不错。


Uh, I'll come find you and we can discuss.
[.my2]
呃，我会来找你，我们可以讨论一下。


Sure, but if I don't see you, I want it.
[.my2]
当然，但如果我没见到你，我就要买。


OK, uh...
[.my2]
好的，呃…


Well, it's not necessarily the best option in the sector 行业,
[.my2]
嗯，它不一定是这个行业的最佳选择，

so, uh, so, yeah, but we can, uh...
[.my2]
所以，呃，所以，是的，但我们可以，呃…


I want us into data mining 数据挖掘. Buy it.
[.my2]
我要我们进入数据挖掘领域。买下来。


It's a really flooded sector 竞争激烈的行业, OK?
[.my2]
这是个竞争非常激烈的行业，懂吗？


Lotta hustlers 投机者, lots of bullshit 胡说八道.
[.my2]
很多投机者，很多狗屁东西。


You know, it's a gold rush 淘金热.
[.my2]
你知道，这就像淘金热。


Oh, yeah.
[.my2]
哦，是啊。


And who wants gold?
[.my2]
谁想要黄金？


Make them an offer they get excited about.
[.my2]
给他们一个让他们兴奋的报价。


Make them an offer they want to tell their wives about at night.
[.my2]
给他们一个他们晚上想告诉妻子的报价。


Nice outdated sexism 过时的性别歧视, Dad,
[.my2]
不错的过时性别歧视言论，爸爸，

but I'm sure you're all over the data mining.
[.my2]
但我相信你对数据挖掘了如指掌。


I'm sorry?
[.my2]
你说什么？


You OK? Dad?
[.my2]
你没事吧？爸爸？


Hey, should I get... someone?
[.my2]
嘿，需要我叫…人来吗？


Maybe you should go home. Yeah?
[.my2]
也许你该回家了。嗯？


I just, uh... need to piss 小便.
[.my2]
我只是，呃…需要撒尿。


Ok.
[.my2]
好的。


Great. Well, thanks for sharing 分享, uh, old guy.
[.my2]
太好了。嗯，谢谢分享，呃，老家伙。



-Glad he's gonna go piss 去小便. -Uh, sorry. You know.

[.my2]
-很高兴他要去撒尿了。 -呃，抱歉。你知道的。


He's still recovering 康复中.
[.my2]
他还在康复中。


Listen, just technically 从技术上讲,
[.my2]
听着，只是从技术上讲，


and I don't want to sound reductive 简单化的, Ken,
[.my2]
而且我不想听起来太简单粗暴，肯，


but... who's in charge 负责 right now?
[.my2]
但是…现在谁负责？


Me. I am.
[.my2]
我。是我。


Legally 法律上 and effectively 实际上.
[.my2]
法律上和实际上都是。


OK, Rick, thanks for that.
[.my2]
好的，里克，谢谢你（的提问）。


Thank you.
[.my2]
谢谢。


Very useful 有用. Thanks.
[.my2]
很有用。谢谢。


Fuck off 滚开.
[.my2]
滚蛋。


So, Greg, uh... listen.
[.my2]
所以，格雷格，呃…听着。


I just had a meeting with my private attorney 私人律师,
[.my2]
我刚和我的私人律师开了个会，


it seems I have been exposed to 暴露于 a virus 病毒.
[.my2]
看来我感染上了一种病毒。


Oh. Right.
[.my2]
哦。对。


Yeah.
[.my2]
是的。


Sit down.
[.my2]
坐下。


It's a deadly 致命的 virus.
[.my2]
这是一种致命的病毒。


and now... now I'm fucked 完蛋了!
[.my2]
而现在…现在我他妈完蛋了！


Forever 永远.
[.my2]
永远。


-It sounds bad 听起来很糟. -It is bad.

[.my2]
-听起来很糟。 -确实很糟。


It is. And, uh, I kind of need to share it 分享它.
[.my2]
是的。而且，呃，我有点需要把它分享出去。


But anyone I talk to, uh...
[.my2]
但是任何和我谈过的人，呃…


anyone I talk to, I effectively kill 实际上等于杀了.
[.my2]
任何和我谈过的人，我实际上就等于害死了他们。


Here.
[.my2]
给。


That's the death pit 死亡陷阱, Greg.
[.my2]
这就是那个死亡陷阱，格雷格。


Take a look 看一眼.
[.my2]
看看吧。


I... I mean, I feel like I might not like it in the death pit.
[.my2]
我…我是说，我觉得我可能不会喜欢死亡陷阱里的东西。


Go ahead 继续.
[.my2]
看吧。


You're family 一家人.
[.my2]
我们是一家人。


Thank you.
[.my2]
谢谢。


-It's complicated 复杂. -Kind of, yeah. But not really.

[.my2]
-事情很复杂。 -算是吧，但也不完全是。


For a number of years there was an unofficial 非官方的 company policy 公司政策
[.my2]
多年来，在邮轮业务上有一个非官方的公司政策，


on the cruise lines 邮轮业务 that if there was a serious criminal incident 严重刑事事件
[.my2]
就是如果发生了严重的刑事事件，


we would, if possible, sail 航行, not home,
[.my2]
我们会，如果可能的话，不驶回母港，


but to a Caribbean or South American port
[.my2]
而是驶向加勒比海或南美洲的一个港口，


where there were so-called "Friendly" Authorities 当局,
[.my2]
那里有所谓的“友好”当局，


and we could minimize the incident 最小化事件 to avoid negative PR 负面公关.
[.my2]
这样我们就可以把事件的影响降到最低，避免负面公关。


-Incidents like---Theft 盗窃. Sexual assault 性侵犯.

[.my2]
-比如像---盗窃。性侵犯。


Rape 强奸. Murder 谋杀.
[.my2]
强奸。谋杀。


OK. The bad ones 严重的那些.
[.my2]
好吧。那些严重的。


Yeah. There's hundreds in there.
[.my2]
是的。里面有成百上千件。


You know, the head of cruises himself, Lester,
[.my2]
你知道，邮轮业务负责人莱斯特本人，


would go on these entertainment tours 娱乐巡演,
[.my2]
会参加这些娱乐巡演，


meeting the dancers,
[.my2]
去见那些舞者，


and extending the contracts 延长合同 of the ones that would suck him off 为他口交.
[.my2]
然后延长那些愿意为他口交的舞者的合同。


Everyone we could, we paid off 付封口费, we hushed up 掩盖.
[.my2]
所有我们能搞定的人，我们都付了封口费，把事情压了下去。


But there are emails,
[.my2]
但是有电子邮件，


there's correspondence 通信记录... it's ready to blow 爆发.
[.my2]
有通信记录…随时可能爆发。


It's a fucking time bomb 定时炸弹.
[.my2]
这他妈就是个定时炸弹。


So, what are you... what are you gonna do?
[.my2]
所以，你打算…你打算怎么办？


I don't know! I don't know!
[.my2]
我不知道！我不知道！


Because anyone I ask for advice 寻求建议, I make complicit 使其成为同谋.
[.my2]
因为任何我向其寻求建议的人，我都会把他们拖下水。


If you know about this stuff 这些事情, you should tell.
[.my2]
如果你知道这些事，你就该说出来。

But you can't, because you're gonna spread the virus 传播病毒.
[.my2]
但你不能说，因为你会传播病毒。

So...
[.my2]
所以…

I have the virus, don't I?
[.my2]
我感染了病毒，对吧？

OK, Ken, uh...
[.my2]
好吧，肯，呃…

why don't you grab the Opalite material 资料?
[.my2]
你为什么不去拿一下Opalite的资料？

Uh, well, as I explained 解释, Dad,
[.my2]
呃，嗯，就像我解释过的，爸爸，

I think they're kind of snake oil salesmen 卖假药的骗子, you know?
[.my2]
我觉得他们有点像卖假药的骗子，你知道吗？

Like they're the people who you buy a refrigerator
[.my2]
就像你从他们那里买了个冰箱，

and their algorithm 算法 is sending you, like,
[.my2]
然后他们的算法就会给你发，比如，

30 ads for more fridges. Great algo 算法.
[.my2]
30个卖更多冰箱的广告。好算法。

Well, you're the business genius 商业天才 who sold me out 出卖 to this fucker,
[.my2]
嗯，你就是那个把我出卖给这个混蛋的商业天才，

so I'd like to hear Stewart's thoughts 想法.
[.my2]
所以我想听听斯图尔特的想法。

OK, I'll get Jess to...
[.my2]
好的，我让杰斯去…

It's a 30-fuckin'-second walkaway 走开半分钟的事, son.
[.my2]
这他妈就是走开半分钟的事，儿子。

Sure.
[.my2]
当然。

So, Stewart...
[.my2]
那么，斯图尔特…

Jess.
[.my2]
杰斯。

Hey, Jess?
[.my2]
嘿，杰斯？

Yeah?
[.my2]
怎么了？

Has anyone been...
[.my2]
有没有人…

Uh, your dad came in for like two minutes.
[.my2]
呃，你爸爸进来过，大概两分钟。

What the...
[.my2]
搞什么…

Oh, Jesus, fuck.
[.my2]
哦，天哪，妈的。

Just like gone in...
[.my2]
就这么进来了…

Hey.
[.my2]
嘿。

So, I think we're buyin' 购买.
[.my2]
所以，我觉得我们要买了。

Good with you, Stewart?
[.mymy2]
你同意吗，斯图尔特？
You're the boss 老板.
[.my2]
你是老板。

All good?
[.my2]
都没问题吧？

Stewart, are you goin' to the Sad Sack Wasp Trap tonight?
[.my2]
斯图尔特，你今晚去那个“穷酸白人佬聚会”吗？

-The... -He means the RECNY ball.
[.my2]
-那个… -他指的是RECNY慈善舞会。

Oh. Yes. I am. I'm sorry to hear that you're not gonna make it 参加.
[.my2]
哦。是的，我去。很遗憾听说你不参加了。

Oh, no, no, I'll be there.
[.my2]
哦，不，不，我会去的。

Well, I'm payin' for the fuckin' thing,
[.my2]
嗯，这玩意儿可是我他妈付的钱，

so I might as well go 不妨去一下.
[.my2]
所以我不妨去一下。

Yeah.
[.my2]
是啊。

You sure it was him?
[.my2]
你确定是他？

You think a lot of people come in here and take a piss 撒尿?
[.my2]
你觉得很多人会进来这里撒尿吗？

Maybe someone spilled something 洒了东西.
[.my2]
也许是有人洒了东西。

Yeah, maybe the massive fucking ice sculpture 冰雕
[.my2]
是啊，也许是我忘了的那个

I forgot about melted. It's urine 尿液.
[.my2]
巨大的他妈冰雕化了。这是尿。

This isn't a false flag 假旗行动, is it?
[.my2]
这不是假旗行动吧？

Did you piss on your own floor?
[.my2]
是你自己尿在自己地板上了吗？

Why are you looking like that? What... What if people knew?
[.my2]
你为什么是那种表情？什么…要是人们知道了怎么办？

-Gerri, you gotta talk to him. -What do you want me to say?

[.my2]
-格里，你得跟他谈谈。 -你想让我说什么？


Well, first tell him where to go pee-pee and poo-poo 尿尿和拉粑粑.
[.my2]
嗯，首先告诉他该去哪儿尿尿和拉粑粑。

He came in, he was talking to Stewy.
[.my2]
他进来了，他在和斯图威说话。


[.my1]
.案例

"pee-pee and poo-poo" 是儿语，指小便和大便。说话人用这种幼稚的词语来讽刺和贬低对方需要被像小孩一样指导基本行为，表达强烈的轻蔑和愤怒。
例句：
-The toddler is learning to use the potty for pee-pee and poo-poo. (这个幼儿正在学习用便盆尿尿和拉粑粑。)

-He mocked his opponent's argument as "pee-pee and poo-poo talk." (他嘲笑对手的论据是“尿尿拉粑粑”级别的谈话。)

好的，以下是按你要求的格式处理后的文本（包含词汇释义、翻译、讲解部分等），保持纯文本格式输出：

---

What's he gonna do next, start jizzing in my coffee?
jizzing 俚语，指“射精”，粗俗表达。
[.my2]
他接下来要干什么？往我的咖啡里射精吗？


[.my1]
.案例
====

“jizz” 是一个粗俗的俚语，表示“精液”或“射精”，常用于表达厌恶、夸张或愤怒的语气。
例句：He’s such a creep, I bet he’d jizz in your drink if he could. （他真恶心，我敢打赌他要是能的话就会往你饮料里射。）
====

Take a dump on my iPad?
take a dump 俚语，意为“拉屎”，比喻性表达。
[.my2]
要不要在我的 iPad 上拉屎？


[.my1]
.案例
====

“take a dump” 是非常口语化的粗俗短语，字面意思是“拉屎”。在这里用作比喻，表示对别人财物、尊严或工作成果的极端不尊重。
例句：He just took a dump on all our hard work.（他完全糟蹋了我们所有的努力。）
====

He's still in recovery mode.
recovery 恢复；康复。
mode 模式，状态。
[.my2]
他还处在恢复状态中。


[.my1]
.案例
===

“in recovery mode” 原本是计算机术语，表示“系统修复模式”。在这里是比喻用法，表示“某人还在恢复中、还没完全回到正常状态”。
例句：After the accident, he was still in recovery mode for weeks.（事故后，他花了好几个星期才恢复。）
=================================================================================

If he thinks he's OK to come back,
come back 返回，回归。
[.my2]
如果他认为自己可以回来了——


he should talk to you, Gerri,
talk to 与…交谈；谈话。
[.my2]
他应该和你谈谈，Gerri。


and the nominating committee,
nominating 提名的；nominate 提名，任命。
committee 委员会。
[.my2]
还有提名委员会。


and set a date. Right?
set a date 安排日期；确定时间。
[.my2]
并确定一个日期，对吧？


[.my1]
.案例
===

“set a date” 是常用短语，意思是“确定某个活动、会议、婚礼等的日期”。
例句：We haven’t set a date for the wedding yet.（我们还没定婚礼的日期。）
==========================================================

Well, technically, but it's kind of a gray area because...
technically 严格来说，从技术上讲。
gray area 灰色地带；模糊地带。
[.my2]
嗯，严格来说是这样，但这事有点模糊，因为……


[.my1]
.案例
====

1. “technically” 用于表达“从技术上或严格意义上说”，常暗示现实情况比定义复杂。
   例句：Technically, you’re right, but it’s not that simple.（严格来说你是对的，但事情没那么简单。）

2. “gray area” 指“界限不清、不易判断的情况”，可用于法律、伦理或组织政策中。
   例句：Online privacy laws are still a gray area.（网络隐私法仍然是个灰色地带。）
====


-He says he's coming tonight. -You're kidding 开玩笑.

[.my2]
-他说他今晚要来。 -你在开玩笑吧。


OK, well, that's a concern 担忧, because obviously
[.my2]
好吧，嗯，这是个担忧，因为显然


with major investors 主要投资者 and press 媒体 on hand 在场..
[.my2]
有主要投资者和媒体在场…


Yeah, I know. What if he freaks out 崩溃?
[.my2]
是啊，我知道。万一他崩溃了怎么办？


What if he falls asleep in his soup 汤?
[.my2]
万一他在汤里睡着了怎么办？


What if he starts shouting racist comments 种族主义言论?
[.my2]
万一他开始大喊种族主义言论怎么办？


Just another Saturday night 周六夜晚, baby.
[.my2]
不过是又一个周六夜晚罢了，宝贝。


We have a fiduciary duty 信托责任 not to let the company look, uh, nuts 疯癫的.
[.my2]
我们有信托责任不让公司看起来，呃，像个疯子。


What did you do, Kendall, when you realized he'd done this?
[.my2]
你做了什么，肯德尔，当你意识到他干了这事的时候？


-What did I do? -Yeah. How did you respond 回应?

[.my2]
-我做了什么？ -是的。你是怎么回应的？


I--I don't know, I didn't want to humiliate 羞辱 him.
[.my2]
我——我不知道，我不想羞辱他。


What?
[.my2]
什么？


This would be the third injection 注射 I've given you in a month.
[.my2]
这将是我一个月内给你打的第三针了。


He feels he needs to be there.
[.my2]
他觉得他需要到场。


You're only meant to have three in a year.
[.my2]
你一年本应只打三针。


No wonder 难怪 you're not sleeping.
[.my2]
难怪你睡不着觉。


You're risking long-term nerve damage 神经损伤.
[.my2]
你在冒长期神经损伤的风险。


Jab 注射. Not jabber 喋喋不休.
[.my2]
打针。不是废话。


Shut up and shoot up 注射.
[.my2]
闭嘴，打针。


Sweetie? Really do with some advice 建议.
[.my2]
亲爱的？真的需要些建议。


-Yeah? -So, look, I don't...

[.my2]
-嗯？ -所以，你看，我不…


I don't wanna get you into this 把你牵扯进来, but, um,
[.my2]
我不想把你牵扯进来，但是，嗯，


well, Bill told me, as part of the handover 交接,
[.my2]
嗯，比尔告诉我了，作为交接的一部分，


where some of the bodies 尸体 were buried 埋藏.
[.my2]
一些“尸体”埋在哪里。


And, uh, they're not very well-buried bodies,
[.my2]
而且，呃，这些尸体埋得并不好，


and they're not really even bodies, they're...
[.my2]
它们甚至不完全是尸体，它们是…


kind of zombies 僵尸?
[.my2]
有点像僵尸？


They're ready to rise up from the dead 死而复生 at any moment
[.my2]
它们随时准备从坟墓里爬出来


and kill me.
[.my2]
然后杀了我。


I'm worried that if... if it does come out 曝光,
[.my2]
我担心如果…如果它真的曝光了，


and it's sort of... it's kind of bound to come out 注定要曝光,
[.my2]
而且有点…它有点注定要曝光的，


and it's while I'm in charge 负责, I'm dead,
[.my2]
而且是在我负责期间，我就完蛋了，


because I know, and I'm not doing anything.
[.my2]
因为我知道，而我什么都没做。


But if I do do something, I've gotta, you know, do something.
[.my2]
但如果我真要做点什么，我得，你知道，采取行动。


-Right. -And I'd like to,

[.my2]
-对。 -而且我想，


you know, not... obviously not carry the can 背黑锅,
[.my2]
你知道，不…显然不是背黑锅，


but maybe do the right thing 做正确的事.
[.my2]
但也许是做正确的事。


Ok.
[.my2]
好吧。


And what is the right thing?
[.my2]
那什么是正确的事？


Well, what I'm thinking...
[.my2]
嗯，我在想…


is a press conference 新闻发布会.
[.my2]
是开个新闻发布会。


-Oh? OK. -Yeah. And tell...

[.my2]
-哦？好吧。 -是的。然后告诉…


Get everybody in, tell all the top execs 高管 and the law guys 律师,
[.my2]
把所有人都叫来，告诉所有高管和律师，


and we go public 公开.
[.my2]
然后我们公开。


Open investigation 公开调查, disinfectant of sunlight 阳光消毒,
[.my2]
公开调查，用阳光消毒，


and, you know, we pin the rap 归罪于
[.my2]
而且，你知道，我们把责任


on a tight group of naughty, rotten apples 烂苹果.
[.my2]
推给一小群调皮的、烂掉的苹果。


Oh. OK.
[.my2]
哦。好吧。


Well, that sounds brave 勇敢的.
[.my2]
嗯，听起来很勇敢。


Yes. Right. Is that good?
[.my2]
是的。对吧。这样好吗？


I'm sorry, can we circle back 回到刚才的话题?
[.my2]
抱歉，我们能回到刚才的话题吗？


I just... I gotta take this from Joyce.
[.my2]
我只是…我得接一下乔伊斯的电话。


Yeah?
[.my2]
嗯？


Look, I did what I can.
[.my2]
听着，我尽力了。


It's dropping down the running order 播出顺序.
[.my2]
它的播出顺序在下降。


But long-term 长期, you gotta ask yourself,
[.my2]
但长期来看，你得问问自己，


will your husband's dirty pink asshole
[.my2]
你丈夫那肮脏的粉红色屁眼


go nicely with that lovely white house on Pennsylvania Avenue?
[.my2]
和宾夕法尼亚大道上那栋可爱的白宫搭不搭调？


Wave 挥手, Roman!
[.my2]
挥手，罗曼！


Wait for me.
[.my2]
等等我。


Thank you.
[.my2]
谢谢。


-Wait, wait, wait. -I'm OK.

[.my2]
-等等，等等。 -我没事。


All right. OK.
[.my2]
好吧。好的。


You're OK?
[.my2]
你没事吧？


I don't think I can do this.
[.my2]
我觉得我做不到。


Yes, you can.
[.my2]
不，你能做到。


Vas-y 法语：上啊 and fuck them.
[.my2]
上啊，干翻他们。


OK. Let's go.
[.my2]
好的。我们走。


Wait a minute. Wait a minute.
[.my2]
等一下。等一下。


Excuse me!
[.my2]
打扰一下！


OK, what the hell is this?
[.my2]
好吧，这他妈是什么？


Uh, fork 叉子?
[.my2]
呃，叉子？


Forks are to be placed thusly 这样放置.
[.my2]
叉子应该这样放。


This is how they do it at a Dakota dude ranch 牧场.
[.my2]
这是达科他州牧场度假村的摆法。


This is how we do it at the RECNY ball.
[.my2]
这是我们在RECNY舞会上的摆法。


Now, please go check every other fork.
[.my2]
现在，请去检查其他所有的叉子。


It's unbelievable 难以置信.
[.my2]
真是难以置信。


Now, why is everyone standing on this side of the room?
[.my2]
现在，为什么每个人都站在房间的这一边？


The room is growing lopsided 不平衡.
[.my2]
房间变得不平衡了。


-Let's lead them 引导他们. -What?

[.my2]
-我们来引导他们。 -什么？


Like sheep 羊群, Willa, let's lead them like sheep.
[.my2]
像羊群一样，薇拉，我们像赶羊一样引导他们。


Go around this way and corral them 围住他们. Corral them this way, OK?
[.my2]
从这边绕过去，把他们围起来。往这边围，好吗？


-I'm gonna go this way. -OK. OK.

[.my2]
-我走这边。 -好的。好的。


Hello! Everyone!
[.my2]
大家好！各位！


-Everyone! Hi! -Come on, everybody,

[.my2]
-各位！嗨！ -来吧，各位，


I'm sorry to interrupt 打断, you all look fabulous 极好的,
[.my2]
抱歉打扰一下，你们看起来都棒极了，


I just want to say if you're
[.my2]
我只想说如果你们在那边


having trouble getting a drink over there,
[.my2]
拿饮料有困难，


identical bar 同样的酒吧 over here...
[.my2]
这边有个一模一样的酒吧…


If you could just go to this side.
[.my2]
如果可以的话请到这边来。


Enjoy the space 空间, there's acres of it 面积很大. So have a good time.
[.my2]
享受这个空间，面积很大。祝大家玩得开心。


The signature cocktail 招牌鸡尾酒? Too avant-garde 太前卫.
[.my2]
招牌鸡尾酒？太前卫了。


The servers 服务生 are creating bottlenecks 瓶颈.
[.my2]
服务生造成了拥堵。


They put pesto 香蒜酱 in the gin... it's a disaster 灾难.
[.my2]
他们在金酒里加了香蒜酱…简直是场灾难。


There's no flow 流动, Stephanie.
[.my2]
没有顺畅的流动，斯蒂芬妮。


The evening is congealing 凝固... there is no flow. OK?
[.my2]
晚会正在凝固…没有流动感。懂吗？


...Mark Morris, yeah, so my dad's first wife
[.my2]
…马克·莫里斯，是啊，所以我爸爸的第一任妻子


thought she was gonna, you know, empty the ghettos 贫民区
[.my2]
以为她能，你知道，清空贫民区，


and get everyone into ballet when they started this thing.
[.my2]
在他们开始这件事的时候让每个人都跳上芭蕾。


-Yeah. -So patronizing 居高临下的.

[.my2]
-是啊。 -太居高临下了。


What are you drinking?
[.my2]
你在喝什么？


Uh, a white wine 白葡萄酒.
[.my2]
呃，一杯白葡萄酒。


Can we get a white wine?
[.my2]
能给我们一杯白葡萄酒吗？


A couple of the kids who got into New York City Ballet
[.my2]
有几个进了纽约城市芭蕾舞团的孩子


still send us cards at Christmas,
[.my2]
圣诞节还会给我们寄卡片，


because that's nice or whatever.
[.my2]
因为这很好或什么的。


No, it's nice.
[.my2]
不，这很好。


Yeah. It's, uh...
[.my2]
是啊。这是，呃…


it's dumb 愚蠢的, but it's cool 酷的.
[.my2]
有点蠢，但很酷。


Can I have a bitters and soda 苦精苏打水?
[.my2]
我能要一杯苦精苏打水吗？


I'm actually kind of nervous about the speech 演讲.
[.my2]
其实我对演讲有点紧张。


-Are you? -Yeah.

[.my2]
-是吗？ -是的。


Maybe you can, uh, give me some pointers 指点.
[.my2]
也许你可以，呃，给我一些指点。


You're the ATN pro 专家, actually.
[.my2]
你才是ATN的专家，真的。


Good, good.
[.my2]
好，好。


Is that too wry 讽刺的?
[.my2]
这是不是太讽刺了？


About our good works 善行? Is that, like, snitty 刻薄的?
[.my2]
关于我们的善行？这是不是，有点刻薄？


Uh, well, there's all this,
[.my2]
呃，嗯，有这么一大堆，


like, three pages of, you know,
[.my2]
比如，三页纸的，你知道，


about you and the family, and the good works, and the big hearts 善心,
[.my2]
关于你和家族，还有善行，还有善心，


and on and on and on 没完没了.
[.my2]
没完没了的。


Excusing you 恕我直言, but I didn't ask for editorial comment 编辑评论.
[.my2]
恕我直言，但我没征求编辑意见。


Now it's into Kendall, OK,
[.my2]
现在轮到肯德尔了，好吧，


and he's all blah blah blah 喋喋不休.
[.my2]
他全是些废话连篇。


Hold on 等一下, pal 老兄. What is this?
[.my2]
等一下，老兄。这是什么？


Roll that back 倒回去. What is that?
[.my2]
倒回去。那是什么？


What?
[.my2]
什么？


-"Surprise Logan retirement announcement 退休声明." -Uh, yeah.

[.my2]
-“洛根惊喜退休声明”。 -呃，是的。


That came through late 来晚了. He said he'd just wing it 即兴发挥.
[.my2]
这个通知来晚了。他说他就即兴发挥。


Ok.
[.my2]
好吧。


Mr. Bond.
[.my2]
邦德先生。


I've been expecting you. How are ya?
[.my2]
我一直在等你。你好吗？


Where are you sitting, man?
[.my2]
你坐哪儿，老兄？


In the basement 地下室?
[.my2]
在地下室？


Out by the dumpsters 垃圾箱?
[.my2]
在垃圾箱旁边？


Maybe you... do you want to trade 交换?
[.my2]
也许你…你想交换吗？


Maybe you'll meet a wealthy widow 寡妇
[.my2]
也许你会遇到一个有钱的寡妇


and you can seduce 勾引 her with your sad eyes.
[.my2]
你可以用你悲伤的眼神勾引她。


She can keep you as a pet 宠物 in Westchester.
[.my2]
她可以在韦斯特切斯特把你当宠物养。


-Hi, guys. -Hey.

[.my2]
-嗨，各位。 -嘿。


-You look nice this evening. -As do you.

[.my2]
-你今晚看起来不错。 -你也是。


Thank you. So, Tom,
[.my2]
谢谢。那么，汤姆，


I hear you're thinking about holding a little press conference?
[.my2]
我听说你在考虑开个小新闻发布会？


-You know about that? -I don't know anything.

[.my2]
-你知道这事？ -我什么都不知道。


Right. I just think it's the
[.my2]
对。我只是觉得这是


-best thing to do... -Tom, you need to shut up 闭嘴.

[.my2]
-最好的做法… -汤姆，你需要闭嘴。


This isn't the time to get your conscience 良心 out and shout,
[.my2]
现在不是把你的良心掏出来大喊的时候，


"Hey, look at me! I cannot tell a lie 说谎!
[.my2]
“嘿，看我！我不会说谎！


I'm a good little boy, look at my ding-dong 阴茎."
[.my2]
我是个好孩子，看看我的小弟弟。”


OK, I don't think that's a fair characterization 描述 of what I'm...
[.my2]
好吧，我觉得那不是我…的公平描述…


Have you ever heard of the Sin Cake Eater 食罪者?
[.my2]
你听说过“食罪者”吗？


-No. -He would come to the funeral 葬礼

[.my2]
-没有。 -他会来到葬礼上，


and he would eat all the
[.my2]
他会吃掉所有


little cakes they laid out on the corpse 尸体...
[.my2]
摆在尸体上的小蛋糕…


he ate up all the sins 罪孽.
[.my2]
他吃掉了所有的罪孽。


And you know what? The Sin Cake Eater was very well paid.
[.my2]
你知道吗？食罪者报酬丰厚。


And so long as there was
[.my2]
只要在他死后


another one who came along after he died,
[.my2]
有另一个人接替，


it all worked out 顺利解决.
[.my2]
一切就都顺利解决了。


So, this may not be the best situation 最好的情况,
[.my2]
所以，这可能不是最好的情况，

but there are harder jobs 更艰难的工作, and you get a fuckload of 大量的 cake.
[.my2]
但还有更艰难的工作，而且你能得到一大堆蛋糕。

Can I ask you where you heard about this, please?
[.my2]
我能问问你是在哪儿听到这件事的吗？

Tom, it's tough to have to tell you like this,
[.my2]
汤姆，这样告诉你让我很难受，

but I'm in a sexual relationship 性关系 with your mother.
[.my2]
但我和你母亲有性关系。

She talks in her sleep 说梦话.
[.my2]
她说梦话。

Excuse me.
[.my2]
失陪一下。

Hey. Hey, Pa 爸爸, how ya doin'?
[.my2]
嘿。嘿，爸爸，你怎么样？

...Just wanted to check in on something 确认一下.
[.my2]
…只是想确认点事。

Just wanted to check that you're aware of 知道 Kendall announcing
[.my2]
只是想确认一下，你知道肯德尔今晚要宣布

your retirement this evening?
[.my2]
你退休的消息吗？

I mean, I'm sure you were,
[.my2]
我的意思是，我相信你知道，

but I just wanted to triple-check 再三确认.
[.my2]
但我只是想再三确认一下。

-What? -Yeah. Is that right?

[.my2]
-什么？ -是的。是这样吗？


-No. -No?

[.my2]
-不。 -不是？


Is it a mistake 错误? Because Kendall's gonna say it.
[.my2]
是搞错了吗？因为肯德尔准备说了。

It's on the teleprompter 提词器.
[.my2]
都在提词器上了。

There's been a change of plan 计划有变.
[.my2]
计划有变。

Kendall's not speaking.
[.my2]
肯德尔不发言了。

I am.
[.my2]
我来发言。

OK, good.
[.my2]
好的，很好。

Good evening, ladies and gentlemen.
[.my2]
晚上好，女士们先生们。

I'm your host 主持人, Mark Ravenhead,
[.my2]
我是你们的主持人，马克·雷文黑德，

and welcome to the RECNY ball.
[.my2]
欢迎来到RECNY慈善舞会。

The butter's too cold!
[.my2]
黄油太冷了！

The butter is too cold!
[.my2]
黄油太冷了！

The butter's all fucked 搞砸了! You're fuckwads 蠢货 and you fucked it!
[.my2]
黄油全他妈完了！你们这群蠢货搞砸了！

-There's dinner rolls 晚餐面包卷 ripping out there as we speak! -Connor!

[.my2]
-就在我们说话的时候，外面的晚餐面包卷都快被撕碎了！ -康纳！


-Connor. -I am a laughingstock 笑柄!

[.my2]
-康纳。 -我成了笑柄了！


There are always issues 问题 when you serve this many people,
[.my2]
招待这么多人总会出问题，

but I think, on the whole 总的来说,
[.my2]
但我认为，总的来说，

it's going very well.
[.my2]
进展非常顺利。

Complacent 自满的! You're fired 你被解雇了!
[.my2]
自满！你被解雇了！

You're all fired! Idiots 白痴!
[.my2]
你们全被解雇了！白痴！

Can't fuckin' believe it. Surrounded by imbeciles 低能儿!
[.my2]
真他妈不敢相信。被一群低能儿包围了！

Hey. Come with me. Come with me.
[.my2]
嘿。跟我来。跟我来。

Come on.
[.my2]
快点。

-You lump of fucking turducken 鸡肉卷. -Hi, T-Tom.

[.my2]
-你这坨该死的鸡肉卷。 -嗨，汤-汤姆。


-Did you squeal 告密? -What?

[.my2]
-你是不是告密了？ -什么？


Did you bitch me out 出卖我, pig man 猪头?
[.my2]
你出卖我了，猪头？

-As in... -You bleated about 告发 the fuckin' press conference.

[.my2]
-意思是… -你告发了那个该死的新闻发布会。


-No! -Yes, you did.

[.my2]
-没有！ -不，就是你。


-No, I did not! -Yes, you did,

[.my2]
-不，我没有！ -不，就是你，


you filthy piece of shit 肮脏的废物.
[.my2]
你这肮脏的废物。

I ought to drag you into the kitchens
[.my2]
我真该把你拖进厨房

and have them boil you until you're s...
[.my2]
让他们把你煮到…

My God, you just touch me, Greg?
[.my2]
我的天，你刚才碰我了，格雷格？

Tom, I'm sor... Your spittle 唾沫 was actually, like...
[.my2]
汤姆，我很抱…你的唾沫其实，好像…

This is extraordinary 非同寻常. What are we gonna do about this?
[.my2]
这太离谱了。我们该怎么办？

Are these assaults 攻击 going to be ongoing 持续?
[.my2]
这种攻击会持续下去吗？

-No! -You tell me you didn't do it?

[.my2]
-不会！ -你告诉我不是你干的？


I promise, I swear to God!
[.my2]
我保证，我对天发誓！

Then who the fuck did, then, Greg?
[.my2]
那他妈是谁干的，格雷格？

Because I only told you.
[.my2]
因为我只告诉了你。

Believe me, man...
[.my2]
相信我，老兄…

Fuck off.
[.my2]
滚开。

...revolutionizing 革命性改变 Internet radio
[.my2]
…从他革命性地改变网络电台

to his work with local children.
[.my2]
到他对本地儿童的工作。

Ladies and gentlemen, please welcome Juno Hernandez!
[.my2]
女士们先生们，有请朱诺·埃尔南德斯！

Hey, Dad.
[.my2]
嘿，爸爸。

Um, so I don't want to shit-talk 说坏话 Kendall, uh...
[.my2]
呃，所以我不想说肯德尔的坏话，呃…

he ain't up to the job 不能胜任工作...
[.my2]
他不能胜任这工作…

but, uh, I think I speak for everyone here
[.my2]
但是，呃，我想我代表这里的每一个人

when I say it's great to see you back.
[.my2]
说很高兴看到你回来。

Ah, thank you, son.
[.my2]
啊，谢谢你，儿子。

But one thing, um,
[.my2]
但有一件事，嗯，

and I don't mind 介意, it's fine,
[.my2]
我不介意，没关系，

but I do want to say that Frank is what to me, now?
[.my2]
但我确实想说，弗兰克现在对我来说算什么？

He's vice-chairman 副主席,
[.my2]
他是副主席，

and you're general advisor 总顾问.
[.my2]
而你是总顾问。

And why is that?
[.my2]
这是为什么？

What's the situation with the park numbers 园区数据?
[.my2]
园区数据情况怎么样？

Park numbers?
[.my2]
园区数据？

Attendances 出席人数 are good,
[.my2]
出席人数不错，

but the occupied room nights 客房入住夜数 are down on last year.
[.my2]
但客房入住夜数比去年下降了。

I'm just waiting for Tom to get his feet, like,
[.my2]
我只是在等汤姆，好比说，

fully under the table 完全上手.
[.my2]
能完全上手。

The guy is a flake 不靠谱的人, is actually the truth of it,
[.my2]
说实话，这家伙确实不靠谱，

but I'm on it 我在处理. I'm on it.
[.my2]
但我在处理了。我在处理。

When are you coming back in again?
[.my2]
你什么时候再回公司？

You need to soak up 吸收 Frank's experience.
[.my2]
你需要吸收弗兰克的经验。

OK, but what does that mean?
[.my2]
好的，但那是什么意思？

It means do what he fuckin' tells ya.
[.my2]
意思就是他妈的他让你干什么你就干什么。

So sorry about the butter, guys.
[.my2]
对黄油的事非常抱歉，各位。

There was a problem with the butter?
[.my2]
黄油有问题吗？

Frozen 冻住了.
[.my2]
冻住了。

So remember, texting 发短信 is encouraged tonight.
[.my2]
所以请记住，今晚鼓励发短信。

Please, no sexting 发色情短信,
[.my2]
请不要发色情短信，

uh, but texting is fine...
[.my2]
呃，但发普通短信可以…

Governor 州长.
[.my2]
州长。

Let's get those numbers in.
[.my2]
让我们把那些数字输进去。

I want to see everybody's name up on that screen,
[.my2]
我想看到每个人的名字都出现在那个屏幕上，

and on behalf of 代表 everyone here at RECNY,
[.my2]
我代表RECNY的全体成员，

thank you for your donation 捐款.
[.my2]
感谢你们的捐款。

Hold on 等一下.
[.my2]
等一下。

Thaaaank you.
[.my2]
谢——谢——你。

You stick around 别走开.
[.my2]
你待着别走。

Oh, I'm sorry, am I interrupting something 打扰了吗?
[.my2]
哦，抱歉，我打扰你们了吗？

If you like her so much,
[.my2]
如果你这么喜欢她，

why don't you just ask for her fuckin' number 电话号码?
[.my2]
你为什么不直接要她他妈的电话号码？

Rome 罗曼的昵称.
[.my2]
罗姆。

I mean you clearly want to, right?
[.my2]
我是说你显然想要，对吧？

Grace, would you like to give this man your number?
[.my2]
格蕾丝，你愿意给这位先生你的电话号码吗？

Yeah. I'd like to give him my number.
[.my2]
是的。我愿意给他我的号码。

Why don't you ask for her number, then?
[.my2]
那你为什么不问她要号码呢？

Can I get your number?
[.my2]
我能要你的号码吗？

Can I have a pen, please?
[.my2]
能给我一支笔吗？

Oh, OK. Here we go. Yeah. It's happenin' 要成了.
[.my2]
哦，好吧。来了。是的。要成了。

That's handy 方便的.
[.my2]
真方便。

That's actually her number.
[.my2]
那真的是她的号码。

Wait, wait, wait.
[.my2]
等等，等等。

And fetch 取来 another bottle, please. Thank you.
[.my2]
请再拿一瓶来。谢谢你。

Thanks, Brian. Thanks, Fritz. Good to see you.
[.my2]
谢谢，布莱恩。谢谢，弗里茨。很高兴见到你们。

-Nice work 干得好, bro. -What do you mean?

[.my2]
-干得好，兄弟。 -你什么意思？


You know, fuckin' the talent 搞上了那个有才的人.
[.my2]
你知道，搞上了那个妞。

-Hey. Come on. -No! It's cool It's cool.

[.my2]
-嘿。得了吧。 -不！这很酷。很酷。


You're fuckin' ATN, ATN's fuckin' me--
[.my2]
你他妈是ATN的，ATN又他妈跟我——

it's a little fucking clusterfuck 一团糟, yeah?
[.my2]
这他妈有点乱，是吧？

Everything good?
[.my2]
一切都好吗？

Yes, I'm having a lovely time.
[.my2]
是的，我玩得很开心。

Thanks.
[.my2]
谢谢。

So sorry about the butter.
[.my2]
对黄油的事非常抱歉。

And just so you know,
[.my2]
还有，让你知道一下，

apparently 显然, Dad's going to be doing the speech now,
[.my2]
显然，爸爸现在要发言了，

so late change of plans, I hope that's cool.
[.my2]
所以计划临时有变，希望你别介意。

-What... -Well, yeah, he just said.

[.my2]
-什么… -嗯，是的，他刚说了。


I guess that put a spoke in quite a few wheels 打乱了不少计划, huh?
[.my2]
我猜这打乱了不少人的计划吧，嗯？

Con 康纳的昵称. Con. He's in no fit state 状态不佳.
[.my2]
康。康。他状态不好。

Gotta go backstage 去后台.
[.my2]
得去后台了。

Uh, Gerri. Gerri. Can we talk?
[.my2]
呃，格里。格里。我们能谈谈吗？

Sure.
[.my2]
当然。

Over here.
[.my2]
这边。

Uh, Dad wants to do the speech.
[.my2]
呃，爸爸想发言。

OK. I did not know that.
[.my2]
好吧。我之前不知道。

Yeah. When he opens his mouth, anything could come out.
[.my2]
是啊。他一开口，什么话都可能说出来。

Drool 口水, anti-Semitism 反犹太主义,
[.my2]
口水，反犹太言论，

fucking string of silk handkerchiefs tied together.
[.my2]
他妈的一串连在一起的丝手帕。

if he fucks up 搞砸 publicly,
[.my2]
如果他公开搞砸了，

we have a major problem.
[.my2]
我们就有大麻烦了。

-Right. -You need to talk to him.

[.my2]
-对。 -你需要跟他谈谈。


OK. Got it.
[.my2]
好的。明白了。

Lasagna 千层面? Did you know they had some lasagna?
[.my2]
千层面？你知道他们有千层面吗？

-Would you like some? -Oh, yeah.

[.my2]
-你想来点吗？ -哦，是的。


-You good 你没事吧? -I'm good.

[.my2]
-你没事吧？ -我没事。


Great.
[.my2]
很好。

Good luck tonight.
[.my2]
今晚祝你好运。

Gonna knock it out of the park 大获成功.
[.my2]
肯定会大获成功的。

Thank you.
[.my2]
谢谢。

Good luck.
[.my2]
祝你好运。

Bon chance 法语：祝好运.
[.my2]
祝好运。

Best foot forward 尽力而为.
[.my2]
尽力而为。

You can do it.
[.my2]
你能做到。

-Good luck. -Thanks.

[.my2]
-祝你好运。 -谢谢。


-Nervous 紧张? -Not too bad.

[.my2]
-紧张吗？ -还行。


I had a thing with the butter, but... seems to be OK.
[.my2]
黄油出了点问题，但是…好像已经解决了。

-Where you from? -Bushwick.

[.my2]
-你从哪儿来？ -布什维克。


Indeed. Yes, indeed.
[.my2]
确实。是的，确实。

Well, wonderful. Great effort 很棒的努力.
[.my2]
嗯，太好了。很棒的努力。

Connor Roy.
[.my2]
康纳·罗伊。


People have a lot of preconceptions 先入为主的观念 about me, too.
[.my2]
人们对我也有许多先入为主的看法。

It's difficult 困难的.
[.my2]
这很难。

I mean, not... like I'm sure everything is for you,
[.my2]
我的意思是，不是…就像我确信所有事对你来说也一样，

See, I actually have this idea
[.my2]
你看，我其实有个想法

that social equality 社会平等 could be effected 实现
[.my2]
社会平等可以通过

by a complete eradication 根除 of federal support 联邦支持.
[.my2]
彻底根除联邦支持来实现。

Just people like you and I, doin' it together,
[.my2]
就靠像你我这样的人，一起努力，

-fighting it out 奋斗到底 without all the bullshit 废话... -OK, this is me.

[.my2]
-抛开所有废话，奋斗到底… -好了，我到了。


Great! Break a leg 祝你好运, my friend.
[.my2]
太棒了！祝你好运，我的朋友。

That was great.
[.my2]
刚才很棒。

Good job 干得好, Con 康纳的昵称.
[.my2]
干得好，康。

Best event of the fall 秋季.
[.my2]
今年秋季最棒的活动。

-Thanks, man. -Really.

[.my2]
-谢谢，老兄。 -真的。


Hey, terrific 极好的 evening, huh?
[.my2]
嘿，今晚很棒，是吧？

You really showed it to those cystic fibrosis 囊性纤维化 fuckheads 混蛋, huh?
[.my2]
你真是让那些囊性纤维化混蛋们见识到了，是吧？

Well, it's all about the charity 慈善. It's not about me, buddy 老兄.
[.my2]
嗯，这都是为了慈善。不是为了我，老兄。

-You're right. -OK, thanks.

[.my2]
-你说得对。 -好的，谢谢。


Hey! Hey, you guys!
[.my2]
嘿！嘿，你们！

You won't believe what people are saying out there.
[.my2]
你们不会相信外面的人都在说什么。

It's amazing 惊人的! We tore it up 大获成功.
[.my2]
太惊人了！我们大获成功。

We nailed it 搞定了, man! Score 得分, team RECNY!
[.my2]
我们搞定了，老兄！得分了，RECNY队！

You're awesome 了不起的, dude 老兄. You're awesome, awesome, awesome.
[.my2]
你真了不起，老兄。你了不起，了不起，了不起。

I love you so much. Everyone,
[.my2]
我太爱你们了。各位，

you're amazing and I love you so much.
[.my2]
你们太棒了，我太爱你们了。

Stephanie, my rock 依靠! Come on, bring it 拥抱一下.
[.my2]
斯蒂芬妮，我的依靠！来，抱一个。

Business mogul 大亨, philanthropist 慈善家,
[.my2]
商业大亨，慈善家，

and guy whose name is on all of my checks...
[.my2]
也是我所有支票上签名的那个家伙…

ladies and gentlemen,
[.my2]
女士们先生们，

it is my profound pleasure 深感荣幸
[.my2]
我深感荣幸

to introduce to you, on this most auspicious 吉祥的 of occasions...
[.my2]
在这个最吉祥的时刻向各位介绍…

in a change to advertised attractions 宣传的亮点,
[.my2]
作为对宣传亮点的临时变更，

the man, the legend 传奇...
[.my2]
这位男人，这位传奇…

Logan Roy!
[.my2]
洛根·罗伊！

Ooh. Elvis 猫王. I thought we were getting a supporting act 暖场表演.
[.my2]
哦。猫王。我还以为我们请的是暖场表演。

Keep going 继续.
[.my2]
继续。

Just get to Dan
[.my2]
就走到丹那里

and pretend you're talking 假装你在说话.
[.my2]
然后假装你在说话。

There's a $40 billion market cap 市值
[.my2]
有400亿的市值

waiting to see if he makes it 成功做到.
[.my2]
正等着看他能否成功。

If he falls 跌倒, I'm gonna lose one of my several houses,
[.my2]
如果他摔倒了，我就要失去我几栋房子中的一栋，

and you're gonna pay for the next one.
[.my2]
而你得赔我下一栋。

My God, he's really milking the walk 故意拖延走路.
[.my2]
天啊，他走路可真会拖时间。

Nearly there. Come on.
[.my2]
快到了。加油。

Thank you. Um...
[.my2]
谢谢。嗯…

uh... evening.
[.my2]
呃…晚上好。

First, I'd, uh,
[.my2]
首先，我，呃，

I'd like to thank my wife, Marcia, for, uh...
[.my2]
我想感谢我的妻子，玛西娅，为了，呃…

everything.
[.my2]
所有事。

Thank you.
[.my2]
谢谢你。

Uh, thanks,
[.my2]
呃，谢谢，

thanks to you all for coming,
[.my2]
谢谢大家的光临，

and thanks to those who have supported me
[.my2]
也感谢那些在我近期

during my recent
[.my2]
健康问题期间

health nonsense 健康问题.
[.my2]
支持我的人。

Head cold 头伤风.
[.my2]
头伤风。

Yeah, uh, yeah, that's, uh, yeah.
[.my2]
是啊，呃，是啊，那是，呃，是啊。

So...
[.my2]
所以…

personal n-news 个人消息.
[.my2]
个人消息。

Someone took advantage 利用
[.my2]
有人利用

of me being in the hospital,
[.my2]
我住院的机会，

to...
[.my2]
来…

propose 求婚...
[.my2]
向…

to my daughter.
[.my2]
我女儿求婚。

So I'd like to take this opportunity 机会
[.my2]
所以我想借此机会

to welcome her fiancé 未婚夫, Tom Wamsgans, to the family.
[.my2]
欢迎她的未婚夫，汤姆·瓦姆斯甘斯，加入这个家庭。

Welcome to the family, Tom.
[.my2]
欢迎来到这个家，汤姆。

It's so, so important
[.my2]
这是如此，如此重要

that children are supported and encouraged 鼓励.
[.my2]
孩子们需要得到支持和鼓励。

And, uh...
[.my2]
而且，呃…

everything I've done,
[.my2]
我所做的一切，

I've done for my children.
[.my2]
都是为了我的孩子们。

And I'm proud of the way
[.my2]
我为他们在我出事期间

that they've pulled together 齐心协力
[.my2]
齐心协力

during my issue 问题.
[.my2]
的方式感到骄傲。

And, in particular 特别,
[.my2]
而且，特别是，

my son... Kendall.
[.my2]
我的儿子…肯德尔。

Well done 干得好, Ken 肯德尔的昵称.
[.my2]
干得好，肯。

And now
[.my2]
现在

for one last announcement 宣布 of the night.
[.my2]
是今晚最后一个宣布。

I'm officially announcing...
[.my2]
我正式宣布…

...I'm back 回来了.
[.my2]
…我回来了。

You better believe 你最好相信, I'm back.
[.my2]
你最好相信，我回来了。

Full-time 全职...
[.my2]
全职…

better than ever 比以往更好.
[.my2]
比以往更好。

Thank you.
[.my2]
谢谢。

All right!
[.my2]
太好了！

Thank you!
[.my2]
谢谢！

-Get me out of here 带我离开这里. -Logan Roy, everybody!

[.my2]
-带我离开这儿。 -洛根·罗伊，各位！


Yeah, nice one 干得漂亮. Way to go 干得好, Dad.
[.my2]
是啊，干得漂亮。干得好，爸爸。

Why would you do that? Huh?
[.my2]
你为什么要那样做？嗯？

I see you 我懂你了.
[.my2]
我懂你了。

I spied you fuckin' out 监视你, son. Don't ever do that to me again.
[.my2]
我监视着你这混蛋，儿子。别再对我这么做了。

I have no idea what you're talking about.
[.my2]
我完全不知道你在说什么。

Retire me, shoot me like a dog in the street.
[.my2]
让我退休，像射杀街上的狗一样射杀我。

I heard about your little speech 演讲.
[.my2]
我听说了你那小小的演讲。

My speech? I was gonna do
[.my2]
我的演讲？我本来打算

one fuckin' joke about how you'd never retire.
[.my2]
开个他妈的玩笑说你永远不会退休。

Bullshit 胡说!
[.my2]
胡说！

Why didn't you just talk to me?
[.my2]
你为什么不直接跟我谈？

Fuck off 滚开.
[.my2]
滚开。

OK, OK. Pa 爸爸. You're all right 你没事吧.
[.my2]
好了，好了。爸爸。你没事吧。

OK. Thanks, Mark.
[.my2]
好的。谢谢，马克。

Here. Easy 小心, easy. Yeah.
[.my2]
这儿。小心，小心。是的。

You OK?
[.my2]
你没事吧？

Yeah. Oh! Hey, Connor.
[.my2]
没事。哦！嘿，康纳。

You did well tonight.
[.my2]
你今晚做得很好。

I'm really, really proud of you.
[.my2]
我真的，真的为你骄傲。

I can no longer obey 服从, Dad.
[.my2]
我不能再服从了，爸爸。

"I have tasted command 指挥, and I cannot give it up 放弃."
[.my2]
“我已尝过权力的滋味，无法放弃。”

A certain artillery cadet 炮兵学员 by the name of N. Bonaparte.
[.my2]
一位名叫N·波拿巴的炮兵学员说的。

Are you OK?
[.my2]
你没事吧？

-Let's go. -OK, let's go.

[.my2]
-我们走吧。 -好的，走吧。


Yeah. OK.
[.my2]
是啊。好的。

Good night. Good job.
[.my2]
晚安。干得好。

Thank you.
[.my2]
谢谢。

You know, look, Anna...
[.my2]
你知道，听着，安娜…

can I just ask...
[.my2]
我能问问…

is there something... going on here 发生?
[.my2]
是不是有什么…事发生？

-As in 意思是? -I don't know,

[.my2]
-你的意思是？ -我不知道，


is there an atmosphere 气氛? Did I say something to offend you 冒犯你?
[.my2]
是不是气氛不对？我说了什么冒犯你的话吗？

This has been a lovely evening.
[.my2]
这是个愉快的夜晚。

I was so happy to come.
[.my2]
我很高兴能来。

So, am I crazy 疯了吗?
[.my2]
所以，是我疯了吗？

I feel like I'm on a date 约会 with an app 应用程序.
[.my2]
我感觉像是在和某个应用约会。

Like there's this invisible bubble wrap 隐形气泡膜.
[.my2]
好像有一层看不见的气泡膜隔着。

Look, um...
[.my2]
听着，嗯…

off the record 非正式的,
[.my2]
私下说，

off off 非常私下的,
[.my2]
非常私下的，

you seem like a nice... guy 家伙.
[.my2]
你看起来像个不错的…家伙。

Thank you.
[.my2]
谢谢。

Eva told me to come.
[.my2]
是伊娃叫我来的。

Asked. I mean,
[.my2]
请求。我的意思是，

I asked her to just, you know, ask your people 你的人.
[.my2]
我请她，你知道的，就是问问你这边的人。

It's fine.
[.my2]
没关系。

I'm just seeing someone 正在和某人交往,
[.my2]
我只是在和人交往，

but y-you... you're the boss 老板.
[.my2]
但 你-你…你是老板。

No. No, no, no. I'm--I'm not that guy 那种人.
[.my2]
不。不，不，不。我——我不是那种人。

Yeah, sure. No. I'm...
[.my2]
是啊，当然。不。我…

But actually, you are the guy. Right now.
[.my2]
但实际上，你就是那种人。现在就是。

What did she say? Eva?
[.my2]
她说了什么？伊娃？

Nothing.
[.my2]
没什么。

Come on. Please, just--
[.my2]
拜托。请你，就——

To make sure that you had a really good time.
[.my2]
为了确保你玩得真的很开心。

Was she joking 开玩笑?
[.my2]
她是在开玩笑吗？

Sure.
[.my2]
当然。

OK, uh, and I'd prefer it if you didn't say anything 什么都别说.
[.my2]
好吧，呃，我希望你什么都别说。

Well, uh, I think I should.
[.my2]
嗯，呃，我觉得我应该说说。

Please don't.
[.my2]
请不要。

OK. Sure.
[.my2]
好的。当然。

Hey, come on, man. This is our charity.
[.my2]
嘿，得了吧，老兄。这是我们的慈善活动。

How much a plate 每人花费? You gotta get at least a blow job 口交.
[.my2]
每人花了多少钱？你至少得得到一次口交吧。

That's the law 法律.
[.my2]
这是法律。

That's not the law.
[.my2]
那不是法律。

Well, it's the ethical code 道德准则, then,
[.my2]
嗯，那这就是道德准则了，

and I hate to say this,
[.my2]
我讨厌这么说，

but she's behaved rather unethically 不道德地 here.
[.my2]
但她在这里的行为相当不道德。

Had a really good time.
[.my2]
玩得非常开心。

Good kid 孩子. Smart move 聪明的举动.
[.my2]
好孩子。聪明的举动。

Keep talking 继续说.
[.my2]
继续说。

I aim to please 旨在取悦, ma'am 女士.
[.my2]
我的目标是让您满意，女士。

Did you tell him to call?
[.my2]
是你叫他打电话的吗？

Don't wake him up 吵醒他.
[.my2]
别吵醒他。

Please close the door.
[.my2]
请关上门。

Keep driving 继续开车.
[.my2]
继续开。

I want him to sleep.
[.my2]
我想让他睡觉。




'''



