= 1151
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,151 – Working as a Street Performer.
This is English as a Second Language Podcast episode 1,151. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. The Learning Guide contains a complete transcript of everything we say. Take a look also at our ESL Podcast Store which has additional courses in Business and Daily English. And why not like us on Facebook? Go to facebook.com/eslpod.
On this episode, we’re going to listen to a dialogue between Giancarlo and Alana about someone who works out on the street performing in order to get money. Let’s get started.
[start of dialogue]
Giancarlo: Whoa, where are you going? I thought we were going to hang out.
Alana: I’m going to work.
Giancarlo: Work? I didn’t know you got a job.
Alana: I’m busking on Main Street.
Giancarlo: You mean you’re panhandling? That’s not working.
Alana: I’m not panhandling. I’m working for tips. I perform, try to draw a crowd, and then pass the hat.
Giancarlo: Can you really make money that way?
Alana: You’d be surprised. I got the idea from Danielle and her friends. A group of them do street theater and comedy routines. A friend of theirs juggles and does acrobatics. Another guy does magic tricks.
Giancarlo: And they do all this on the street? Don’t they get hassled by the cops?
Alana: The cops occasionally tell them to move along or tell the crowd to disperse, but if they’re respectful and nobody complains, they get left alone. Hey wait, where are you going?
Giancarlo: I’m going with you. I want to give this street performing a try.
Alana: What can you do?
Giancarlo: I’m a man of many talents.
Alana: Are you?
Giancarlo: Don’t look so surprised!
[end of dialogue]
Giancarlo begins our dialogue by using a common word in informal English, “Whoa.” “Whoa,” usually spelled (whoa), is a way of stopping someone or of expressing surprise about something. It’s an old expression that we usually associate with someone riding on a horse and wanting to stop the horse. Someone might say, “Whoa.” Well, nowadays we use it not to stop horses, but sometimes to stop people from saying something or going somewhere. That’s what Giancarlo is doing.
He says, “Whoa, where are you going? I thought we were going to hang out.” “To hang (hang) out” is a two-word phrasal verb that means to spend time with another person, usually in a lazy sort of way. You may go over to your friend’s house and, I don’t know, have a glass of wine, or a beer, or a cup of tea, and just relax and talk. You’re going to hang out. “To hang out” usually implies that you’re not going to do anything in particular, anything special. You’re just going to sort of talk and spend time enjoying yourselves without any specific plans to do anything.
Alana says, however, “I’m going to work.” Giancarlo says, “Work? I didn’t know you got a job.” Alana says, “I’m busking on Main Street.” “To busk” (busk) means to play music on a sidewalk or in another public place in the hopes that people will give you money for playing music. We’ve all seen people busking on a city street before or in a subway area or perhaps in a park. People play guitars or other musical instruments. Sometimes they sing in the hopes that people will give them money.
Giancarlo says, “You mean you’re panhandling? That’s not working.” “To panhandle” (panhandle) means to ask people for money, especially if you are sitting on a sidewalk or standing on the side of a road. Another verb meaning the same thing is “to beg” (beg). “To panhandle,” however, means specifically to beg in the street or in a public area.
Now, normally we don’t consider people who are busking, who are actually doing something like playing music, to be panhandling. “To panhandle” usually means you’re just asking someone for money. You’re not doing anything to get the person to give you money – other than, I suppose, asking in a nice way. You can see panhandlers in Los Angeles very easily by simply driving to any of the poorer areas of the city.
Alana says, “I’m not panhandling. I’m working for tips.” A “tip” (tip) is money that you normally give someone to thank him or her for good service or for a job well done. Normally in the United States we tip at a restaurant. We tip the server – the waitress or the waiter. We also tip at the hotel if someone takes our bags in. We may tip a taxi driver. Americans like to tip a lot more than people in other countries, and in fact, when Americans go to another country, people are sometimes surprised to see them tipping at places that the people who live in those countries don’t normally tip.
Alana says she’s just “working for tips,” meaning she’s just working for people giving her money because she’s doing a good job. “I perform,” she says, “try to draw a crowd, and then pass the hat.” “To draw (draw) a crowd (crowd)” means to attract many people to hear or to see something, to do something that people will want to come and hear or see. It could be a good thing. It could be a bad thing. Normally, “to draw a crowd” means to get people to pay attention to you because, perhaps, you’re performing.
“To pass the hat” means to take a hat, the kind of thing you wear on your head, and turn it over and ask people to put money in it. It’s a common way that street performers try to get people to give them money. They perform and then they take perhaps a hat, or sometimes it’s just a small bowl, and they give it to people and ask them to put money in it. Giancarlo says, “Can you really make money that way?” Alana says, “You’d be surprised,” meaning “Yes, even though you may not think so.”
She says, “I got the idea from Danielle and her friends. A group of them do street theater and comedy routines.” “Street theatre” is, just as it sounds, a group of people who perform small parts of a play or small dramatic performances on a public street – once again, in the hopes usually of getting tips, of getting people to give them money. A “comedy routine” (routine) is when someone stands up and tells jokes or does something funny to get people to laugh. Comedy routines usually involve one person telling jokes and making people laugh.
Alana continues, “A friend of theirs juggles and does acrobatics. Another guy does magic tricks.” Alana is mentioning other popular forms of street performance – the things that street performers do. One of them is “to juggle” (juggle). “To juggle” here means to keep several balls or other small items in the air by throwing them up into the air and, of course, catching them with your hands and then throwing them up in the air again.
In everyday English, we sometimes use the verb “to juggle” to mean to move things around, especially on your calendar, on your schedule. Someone may say, “I need to juggle my calendar in order to find time to meet with you.” I need to rearrange things. I need to move appointments on my calendar, on my schedule. But the other meaning of the verb “to juggle” – the, I guess you could say, “original meaning” – is to throw balls up into the air. I have a nephew who is a very good juggler. Unfortunately, it’s hard to make money juggling. I think he works at a grocery store now.
“To do acrobatics” (acrobatics) means to move your body in unusual ways, often using ropes and swings that are suspended in the air. Now, I’m not sure how you would do acrobatics as a street performer. Normally, we associate acrobatics with something like a circus. A “circus” (circus) is a performance for a large group of people that usually includes tricks with animals and doing things such as acrobatics where someone walks on a wire that is high up in the air. “Magic tricks” refer to any action that is surprising and entertaining. People often do magic tricks with cards, for example, or they appear to make things disappear suddenly.
Giancarlo then asks, “And they do all of this on the street? Don’t they get hassled by the cops?” “To get hassled” (hassled) is to get bothered by. The verb “to hassle” means to create problems or trouble for someone. The “cops” (cops) refers to the police. “Cop” is an informal term for a police officer – a policeman or a policewoman. Giancarlo wants to know if the street performers get “hassled” or bothered by the police.
Alana says, “The cops occasionally tell them to move along or tell the crowd to disperse.” “To move along” means to keep walking, to continue moving in a particular direction. “To disperse” (disperse) means to separate and to go in different directions. If a police officer disperses a crowd, the officer is getting people to no longer stand together, but to each go in a different direction so that there’s no longer a group of people in a single place.
Alana says, however, if the street performers are “respectful and nobody complains, they get left alone.” “To be left alone” means not to be bothered by other people, to be allowed to do what you want to do. Alana then says, “Hey wait, where are you going?” Giancarlo says, “I’m going with you. I want to give this street performing a try.” Alana says, “What can you do?” Giancarlo says, “I’m a man of many talents.”
The expression “I’m a man of many talents” (talents) would describe a person who is good at doing many different things. Giancarlo thinks that he has some talent, some ability that he can use to be a street performer. Alana is surprised. She’s asks, “Are you?” meaning are you really a person of many talents? Giancarlo says, “Don’t look so surprised,” meaning she shouldn’t be surprised that he has all of these different talents. Of course he does. Giancarlo think he’s very talented, apparently.
I have to say I’ve never worked as a street performer, although you can see street performers here in Los Angeles, even though Los Angeles is famous for people not walking on the streets. They take their cars, of course. Maybe I could try to teach English on the streets of Los Angeles and people will give me tips for that. I should try it.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Giancarlo: Whoa, where are you going? I thought we were going to hang out.
Alana: I’m going to work.
Giancarlo: Work? I didn’t know you got a job.
Alana: I’m busking on Main Street.
Giancarlo: You mean you’re panhandling? That’s not working.
Alana: I’m not panhandling. I’m working for tips. I perform, try to draw a crowd, and then pass the hat.
Giancarlo: Can you really make money that way?
Alana: You’d be surprised. I got the idea from Danielle and her friends. A group of them do street theater and comedy routines. A friend of theirs juggles and does acrobatics. Another guy does magic tricks.
Giancarlo: And they do all this on the street? Don’t they get hassled by the cops?
Alana: The cops occasionally tell them to move along or tell the crowd to disperse, but if they’re respectful and nobody complains, they get left alone. Hey wait, where are you going?
Giancarlo: I’m going with you. I want to give this street performing a try.
Alana: What can you do?
Giancarlo: I’m a man of many talents.
Alana: Are you?
Giancarlo: Don’t look so surprised!
[end of dialogue]
Our scriptwriter is a woman of many talents. I speak, of course, of the wonderful Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to hang out – to spend time with another person in an enjoyable, slightly lazy way, without any particular purpose or intention
* We need to get our children to spend less time hanging out with their friends and more time studying.
to busk – to play music on the sidewalk or in another public area in the hopes of receiving money from people who hear it
* Busking is a great way for musicians to practice playing in front of an audience and make money at the same time.
to panhandle – to ask people for money, especially while sitting on a sidewalk or standing on the side of a road; to beg
* The mayor wants to find a way to decrease the amount of panhandling that tourists experience when they visit the city.
tip – money paid to someone to thank him or her for good service or for a job well done, especially for food servers, taxi drivers, hotel porters, salon workers, and tour guides
* Customers normally leave a 15 to 20 percent tip for their hair stylist.
to draw a crowd – to attract many people to see or hear something; to do something that interests people enough to form an audience
* Walter was doing yoga in the park, when he suddenly realized that he was drawing a crowd.
to pass the hat – to turn a hat upside down and hold it out toward all the people in an informal audience, silently asking them to place money in it to support the performer
* We had about 70 people watching the dance, but as soon as we passed the hat, they all walked away.
street theater – dramatic performances that occur on public streets for the people who walk by, especially as a way to earn money
* With so many actors looking for work in Los Angeles, I bet there’s some great street theater on evenings and weekends.
comedy routine – a rehearsed (practiced) performance in which one tells jokes or makes funny observations in order to make other people laugh
* The comedy routine was funny to everybody in the audience because the jokes made fun of everyone.
to juggle – to keep several balls or other items in the air by repeatedly throwing them upward and between one’s hands
* Wow, that man is juggling three oranges and two apples!
acrobatics – the art and sport of moving one’s body in unusual ways, balancing on small wires or objects, and/or hanging from ropes or swings while moving through the air
* The acrobatics were amazing! She danced on a wire 20 feet above the ground!
magic trick – an action or movement that is surprising and entertaining, and appears to have been performed by magic (something that cannot be explained by science or logic)
* And now, for my last magic trick, I will use this saw to cut my assistant in two, and then put her back together again.
to hassle – to create problems or trouble for someone; to become involved in someone else’s business or activities in an unwanted way
* Why are the police hassling people about driving 10 miles per hour over the speed limit, when other people are driving much, much faster?
cop – a police officer; a policeman or policewoman
* What’s happening outside? The street is filled with cops and flashing lights.
to move along – to keep walking; to continue in a particular direction; to leave the place where one is
* Move along, there’s nothing more to see here.
to disperse – to separate and go in many different directions
* After the performance, the audience slowly dispersed, leaving behind used tickets and empty candy wrappers.
left alone – not bothered by other people; allowed to do what one wants, without interference or control
* I had a bad day at work and I just want to be left alone for a few hours.
street performing – performances that take place in public, without being in a theater or on a stage, and without a formal schedule or audience
* Liam was first discovered while he was street performing on a New York corner.
a man of many talents – a person who is good at doing many different things
* Craig is a man of many talents. He can speak five languages, create mobile phone apps, run marathons, play chess, and cook a gourmet meal.
Comprehension Questions
1. What does Giancarlo mean when he says, “I thought we were going to hang out”?
a) He thought they were going to spend some time together.
b) He thought they were going to exercise together.
c) He thought they were going to get some food to eat.
2. What is panhandling?
a) Earning money for one’s work.
b) Cooking and selling food.
c) Begging for money from other people.
Answers at bottom.
What Else Does It Mean?
to draw a crowd
The phrase “to draw a crowd,” in this podcast, means to attract many people to see or hear something, or do something that interests people enough to form an audience: “I bet we could draw a crowd if we printed up some colorful flyers.” The phrase “three’s a crowd” means that one wishes one person left, leaving only two friends or lovers alone: “Janet and Marcus let me stay at their place for a while, but I didn’t feel very comfortable. Three’s a crowd.” A “crowd pleaser” is someone or something that most people like: “Ivan is a crowd pleaser who has a great rapport with his audiences.” Finally, the “in-crowd” refers to the most popular people, especially high school students: “I was never part of the in-crowd in high school. Everyone thought of me as a nerd.”
to move along
In this podcast, the phrase “to move along” means to keep walking, to continue in a particular direction, or to leave the place where one is: “We tried to watch the movie stars arriving to the theater, but the security guards told us to move along.” The phrase “to come along” means to join someone on a trip or at an event: “We’re going to the dance club tonight. Would you like to come along?” The phrase “to bring/take (something) along” means to bring or take something with oneself to a place: “Please bring your photos along so we can look at them together.” Finally, the phrase “all along” means all the time, or since the beginning: “So you knew all along that I was going to be fired at the end of the year. Why didn’t you tell me?”
Culture Note
Music Under New York
Since 1985, the New York City “Metropolitan Transportation Authority” (city transportation department) has been operating the Music Under New York program, which “schedules” (arranges the time and place for) musical performances within the city’s “underground” (below the surface of the earth) “subway system” (system of underground trains used for local transportation).
According to local laws, anyone can perform music in public areas such as the subway system, regardless of whether they are participating in the program. However, musicians who perform through the Music Under New York program receive free “promotion” (advertisements; information and materials designed to encourage people to attend or do something) that increases their “visibility” (how well known someone or something is). They also have greater “access” (ability to have or do something) to the most popular, “high-traffic” (with a lot of people moving through the area) spots.
Music Under New York offers “transit riders” (people who use public transportation) more than 7,500 performances each year throughout the subway system, and represent a wide variety of “musical genres” (types of music), many of which “incorporate” (include) unusual musical instruments.
To become part of the Music Under New York program, musicians must participate in the annual “auditions” (performances containing a sample of one’s artistic work for others to evaluate) in Grand Central Terminal. More than 350 individual musicians and “ensembles” (a group of musicians or dancers who perform together) currently participate in the program. Many of the performers are famous, having performed at “prestigious” (important and greatly admired) locations, such as Carnegie Hall and Lincoln Center.
Comprehension Answers
1 - a
2 - c