= 1176
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,176 – Limits to Advancement at Work.
This is English as a Second Language Podcast episode 1176. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and take a look at our ESL Podcast Store with additional courses in Business and Daily English, and take a look at our ESL Podcast Blog as well.
On this episode, we’re going to hear a dialogue between Gloria and Sam about getting a better job at your company. Let’s get started.
[start of dialogue]
Gloria: Did you hear that Manuel is quitting? He took a job with another company.
Sam: I’m not surprised. He came up against the glass ceiling and he decided to jump ship.
Gloria: Really? I didn’t know he was bucking for promotion.
Sam: He’s been trying to become a manager for three years, but other people have been promoted over him or they’ve hired from outside the company.
Gloria: I didn’t know that. I was aware of the wage disparities within the company and the gender pay gap within each department, but this is news to me.
Sam: Haven’t you noticed that people who take extended leave to have children or try for some type of work-life balance are passed over for plum assignments, raises, and promotions? There are definite limits to advancement.
Gloria: I thought it was just favoritism on the part of the bosses. Their friends got promoted and other people didn’t.
Sam: That’s certainly true, but that’s only part of the story.
Gloria: Why are we still working for a company with such unfair policies?
Sam: Speak for yourself. I’m giving notice today.
[end of dialogue]
The title of this episode is “Limits to Advancement at Work.” “Advancement” would be getting a higher level or going to a higher level – in this case, getting a better job at the company where you work. Gloria begins by saying to Sam, “Did you hear that Manuel is quitting? He took a job with another company.” Sam says, “I’m not surprised. He came up against the glass ceiling and he decided to jump ship.” The term “glass ceiling” (ceiling) refers to a limit on how far you can go in your career, in your job, for reasons that have nothing to do with how good you are at your job.
In other words, it’s a limit that is unfair and imposed by or placed by someone else, perhaps the rules of the company or the culture of the company. The term was originally used to refer to the idea that women and some racial and ethnic minorities were not able to get better jobs because of some sort of discrimination against them. The “ceiling” of a room is the top of the room. A room has a floor, a ceiling, and typically four walls.
A “glass ceiling,” if you can imagine such a thing, would be one that you couldn’t see if you looked up because it’s made of glass – unless, I guess, the glass was dirty. But anyway, the idea is that you wouldn’t notice it. It wouldn’t be something you could see, but if you actually went up to the top of the room, you would hit the glass ceiling and wouldn’t be able to go any higher, any farther up. And that’s, you can see, the metaphor here for what might limit you in a company that discriminated against you for some reason related to your sex or your race or some other reason.
Sam says that Manuel “came up against the glass ceiling,” meaning apparently he had been discriminated against, “and he decided to jump ship.” “To jump ship” (ship) is a two-word phrasal verb meaning to quit your job or to leave an organization and to go to another job with another company or organization. You could also use this phrasal verb when you leave or quit some job or organization even if you don’t have another job. I guess I’ve heard it used more often in a case where someone has moved to a different company, say.
Gloria is surprised to hear that Manuel was having these problems. She says, “I didn’t know he was bucking for promotion.” “To buck (buck) for promotion” or “to buck for a promotion” is to work hard to try to get a better job within your company. Sam says, “He’s been trying to become a manager for three years, but other people have been promoted over him.” “To be promoted” (promoted) means to get a better job within a company. The verb is “to promote.”
Sam thinks that other people have been promoted over Manuel, meaning instead of Manuel getting the job, other people have gotten a job that Manuel wanted or the company has hired from outside their own company, finding someone from another company. Gloria says, “I didn’t know that.” Then she says, “I was aware of the wage disparities within the company.” “Wage” (wage) refers to how much you make per hour. A “disparity” (disparity) is a difference between two things or two people or two groups of people.
“Wage disparities” would refer to differences in how people are paid. The idea here, however, is that not only are people paid differently, but once again, they’re being paid differently for some reason that doesn’t seem fair, that might be discriminatory. Apparently, that’s what’s happening at this company where Sam and Gloria work. Gloria says she was aware of this, this case of wage disparities, “and the gender pay gap within each department.” A “gender pay gap” would be differences in how men and women are paid.
The word “gender” (gender) has changed meaning over the years. We used to use “gender” in talking just about languages such as French or Italian or Spanish, where the nouns have gender – feminine and masculine. However, more recently, the word “gender” has come to replace the word “sex” to refer to men and women. So, instead of talking about “sex discrimination,” people talk about “gender discrimination.”
There’s another political idea behind the change in the use of the word “gender,” which has to do with whether something called “gender” is the same as something called “sex” – biological sex – but I won’t go into that discussion here. For us, the important thing to know is that “gender pay gap” refers to differences in the way men and women are paid at a company based on whether they are men or women. That’s the idea. The word “gap” (gap) is a difference between two things – in this case, between the amount of money you’re getting paid by the company.
Gloria says she was aware of the wage disparities within the company and the gender pay gap within each department or part of the company, “but this is news to me” – that is, it’s news that Manuel was trying to get a job and that he was not successful. Then Sam adds, “Haven’t you noticed that people who take extended leave to have children or try some type of work-life balance are passed over for plum assignments, raises, and promotions? There are definite limits to advancement,” Sam says.
The word “extended” (extended) means long, or longer than normal. A “leave” (leave) is a period of time when you leave your job but you are planning on coming back. You may leave for a month or two months or maybe even longer, but the idea is that you’re not quitting your job – you’re going to come back and work for the company. You may be paid during your leave, or it may be an “unpaid leave,” where you don’t get any money from your company but you get your job back when your leave is over.
So, an “extended leave” would be when you stop working for your company, usually for several months. People may take an extended leave when they have children. A woman may take what is called a “maternity leave” – that is, when she has her baby, she may decide not to work for three months or six months or perhaps longer, and then go back to work. Fathers are also sometimes given leave in companies. We would call that a “paternity leave,” I guess. But you may take an extended leave for some other reason.
According to Sam, people who take extended leave to have children, “or try for some type of work-life balance are passed over for plum assignments.” A “work-life balance” is when you try to usually not work as hard so that you can enjoy your life more. It relates to the attempt by some people to have a good family life as well as a good work life.
He says, “People who take extended leaves for work-life balance are passed over for plum assignments.” “To be passed over” means that you are not given something but the next person is. Manuel apparently has been taking extended leave and is surprised that he’s being passed over for “plum assignments.” A “plum (plum) assignment” is a very good assignment, a very good job. Anything that is “plum” is good or attractive. “Plum” is also a kind of fruit, of course, but here it means a very good job, a very good assignment in the company.
These people who take these extended leaves are also being passed over for raises. A “raise” (raise) is when you get more money for doing the same amount of work. “There are definite limits to advancement,” Sam complains, and I should think there should be, if you’re taking extended leaves and then expecting to get paid the same as people who don’t get extended leaves, but maybe I’m crazy.
Gloria says, “I thought it was just favoritism on the part of the bosses.” “Favoritism” (favoritism) is when you like one kind of person or one particular person for reasons that don’t seem fair, that have nothing to do with that person’s qualifications. Gloria thought the reason some people were getting raises and promotions was because the bosses were promoting and giving raises to their friends.
Sam says, “Well, that’s certainly true, but that’s only part of the story,” meaning that’s not the only reason this has been happening. Gloria complains, “Why are we still working for a company with such unfair policies?” “Unfair” is not fair, not just, not treating everyone equally. A “policy” is the rules or the regulations that a company follows – the way that the company does business. Gloria is wondering why she and Sam are still working for this apparently unfair company.
Sam says, “Speak for yourself,” meaning he’s not going to continue working for this company. “I’m giving notice today.” “To give notice” means to tell your company that you are quitting, that you are no longer going to work there. I’m not sure if Gloria and Sam’s company will be all that disappointed to see them leave. But there you go.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Gloria: Did you hear that Manuel is quitting? He took a job with another company.
Sam: I’m not surprised. He came up against the glass ceiling and he decided to jump ship.
Gloria: Really? I didn’t know he was bucking for promotion.
Sam: He’s been trying to become a manager for three years, but other people have been promoted over him or they’ve hired from outside the company.
Gloria: I didn’t know that. I was aware of the wage disparities within the company and the gender pay gap within each department, but this is news to me.
Sam: Haven’t you noticed that people who take extended leave to have children or try for some type of work-life balance are passed over for plum assignments, raises, and promotions? There are definite limits to advancement.
Gloria: I thought it was just favoritism on the part of the bosses. Their friends got promoted and other people didn’t.
Sam: That’s certainly true, but that’s only part of the story.
Gloria: Why are we still working for a company with such unfair policies?
Sam: Speak for yourself. I’m giving notice today.
[end of dialogue]
There are no limits to your English if you continue to listen to the wonderful scripts by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Don’t take an extended leave from listening to ESL Podcast. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
glass ceiling – a limit to what one can achieve in one’s professional career, especially imposed by others in an artificial and unfair way
* At this bank, there seems to be a glass ceiling for women. All the top managers are men.
to jump ship – to abandon something, especially to quit a job or leave an organization
* Okay, you failed a big exam, but you can’t just jump ship and drop out of school. You’re study harder and do better next time.
to buck for promotion – to work very hard to get a better job with more responsibilities and higher pay
* Jorge is staying at the office until 8:00 p.m. most nights, because he’s bucking for a promotion and thinks that working long hours will impress the managers.
wage disparities – differences in how much people are paid, especially unfair differences
* How big are the wage disparities between first-year teachers and teachers who have been at the school for 20 years?
gender – female or male
* Do you want to know the baby’s gender, or are you waiting until the birth to find out?
pay gap – the difference between how much two people or groups of people are paid
* There’s a huge pay gap between surgeons and emergency room doctors at this hospital.
extended leave – a long period of time when one has permission to not be working as usual
* Last year, Marcia took extended leave while she was undergoing chemotherapy and other cancer treatments.
work-life balance – an balance between the demands and activities of one’s professional life and personal life; a healthy mixture of time and energy devoted to work and to oneself, friends, and family
* With two young children, Gregory wants to find a job that offers a good work-life balance.
to pass over – to skip someone or something, offering or doing something to the next person or thing
* Jerome thought he would be elected the next club president, but he was passed over and the job was given to the club owner’s son.
plum – very good or attractive, especially referring to something that pays well or has a lot of benefits
* How did you find such a plum apartment in Manhattan for so little rent?
raise – an increase in the amount of money that one is paid for one’s work
* When you ask your boss for a raise, it’s a good idea to have a list of all the things you’ve accomplished and all the ways you’ve helped the company increase profits.
limit – a minimum or maximum amount of something; the minimum or maximum allowable value or number
* The library has a three-week limit on books people check out.
advancement – promotion; upward movement within a company or within a career to better, more influential, more respected, and better-paying jobs
* Thalia’s advancement has been limited by her lack of a master’s degree.
favoritism – an unfair preference for a particular person or group of people
* The school doesn’t allow teachers to teach their own children, because it can result in favoritism.
unfair – not fair or just; not treating everyone equally
* It’s unfair to waive the requirements for some applicants, but not for others.
policy – an official description of how a particular business or institution does something, including its rules
* All new employees must be trained on our sexual harassment policy.
to give notice – to announce that one will be quitting one’s job and leaving a company
* Many businesses ask their employees to give at least two weeks’ notice before leaving to work at another company.
Comprehension Questions
1. Which of these is most similar to jumping ship?
a) Bucking for promotion
b) Being passed over for plum assignments
c) Giving notice
2. What happens if an employee comes up against a glass ceiling?
a) The employee does not have any opportunities for promotion.
b) The employee gets a raise.
c) The employee takes extended leave.
Answers at bottom.
What Else Does It Mean?
to jump ship
The phrase “to jump ship,” in this podcast, means to abandon something, especially to quit a job or leave an organization: “The company has been going though some hard times, but we can’t all jump ship now. This is when we need to work our hardest to turn things around.” The phrase “to run a tight ship” means to manage something very efficiently, or to control something very well: “As the head of household, Janet runs a tight ship.” Or, “We need to hire a new vice president who can run a tight ship and keep our plans moving forward.” Finally, the word “shipshape” describes something that is neat, clean, organized, and in good condition: “By the time I get back home, this bedroom had better be shipshape.”
raise
In this podcast, a “raise” is an increase in the amount of money that one is paid for one’s work: “We’re giving you a 5% raise in recognition of your significant accomplishments over this past year. Congratulations.” The related verb, “to rise,” means to increase in height or value: “Sales rose by 50%.” Or, “Everyone was pleased to see the stock price rise.” The verb “to rise” can also mean to stand up: “Please rise when the judge enters the courtroom.” The phrase “to rise to power” means to become powerful or successful, especially gaining a particular position: “It has been very interested to observe Senator Chu’s rise to power over the past few years.” Finally, the phrase “to rise above (something)” means to overcome a challenging or difficult situation: “She rose above poverty and became a bestselling author.”
Culture Note
Unfair Gender-based Work Practices
Unfair gender-based work practices are not officially “condoned” (accepted and allowed), but they are “commonplace” (found in many places; not unusual). For example, many companies have not only a glass ceiling, but also a “glass cliff,” which is a “phenomenon” (something that one can observe) in which women are most often promoted to leadership roles during periods of “crisis” (severe problems). For example, a woman might be “appointed” (named to a particular position) as the “CEO” (Chief Executive Office; highest-level manager) of a company that is experiencing a “downturn” (a period of time when there are many problems that are getting worse), which makes her less likely to succeed in her new role.
Many women are said to be on the “mommy track” if they “prioritize” (make more important) motherhood over their career. For example, they might decide not to “pursue” (try to get) or accept promotions or raises because they want to have extra time to spend with their children. These women might also request a “flexible schedule” (the ability to change which hours one works), a “telecommuting arrangement” (arrangements to work from home, not from the office), or “part-time hours” (less than 40 hours per week), but these arrangements rarely lead to professional advancement.
These gender-based work practices are not limited to the “private sector” (for-profit businesses). When these things happen in a religious institution, they are referred to as a “stained-glass ceiling.” (A “stained-glass window” is a window with many pieces of colored glass pieced together to create an image, often found in Christian churches.) The stained-glass ceiling prevents many women from filling leadership positions in a religious community, due to either “tradition” (how things have always been done) or “prohibition” (something not being allowed; something against the rules).
Comprehension Answers
1 - c
2 - a