= 1183
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,183 – Air and Water Pollution.
This is English as a Second Language Podcast episode 1,183, I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com today. When you do, be sure to become a member of ESL Podcast. When you become a member, you can download a Learning Guide for this episode that contains, among other many wonderful things, a complete transcript of everything we say. This episode is all about air and water pollution. Sounds like fun. Let’s get started.
[start of dialogue]
Julia: Stop poisoning us! Stop poisoning us!
Robert: Why are you picketing in front of this factory?
Julia: This factory is polluting our air and water. They’re responsible for contaminating the environment with dangerous chemicals and waste.
Robert: But your entire family works here. Aren’t you concerned you’ll cause trouble for them and the other workers?
Julia: What’s more important is their health. The air quality in and out of this factory is at toxic levels and it’s endangering their health, not to mention what it’s doing to the ozone.
Robert: That’s terrible. Maybe I should help you picket.
Julia: Here’s a sign.
Robert: Okay, but maybe picketing is taking things a little too far.
Julia: No way! Did you know that runoff from the factory has tainted the groundwater? Did you know that workers and people in the community are breathing in dangerous particulate matter?
Robert: I didn’t know that. Do you have proof of all that?
Julia: Of course I have proof. Environmental groups have done independent tests.
Robert: Then it’s actually dangerous for me to be standing here talking to you and breathing in this toxic air.
Julia: That’s true and your willingness to help me picket is really commendable. Hey, where are you going?
[end of dialogue]
Julia begins our dialogue by shouting – she’s shouting, saying in a very loud voice – “Stop poisoning us!” “ To poison” (poison) someone is to make someone sick or even kill them by exposing them or giving them some sort of dangerous chemicals. Robert asks Julia, “Why are you picketing in front of this factory?” A “factory” (factory) is a place where things are made.“To picket” (picket) means to stand in front of a building, usually carrying signs and shouting your disagreement about something that is going on inside the building. Another verb we might use here is “to demonstrate.”
Julia says, “This factory is polluting our air and water.” “To pollute” (pollute) means to make the air, the water, and/or the land dirty and unsafe, usually because you’re using some sort of unhealthy or harmful substance. We usually refer to polluting the “environment,” the world around us – the air, the land, the water that we have in our environment, in the area around us, in the place where we live.
Julia says, “They’re responsible for contaminating the environment with dangerous chemicals and waste.” “To contaminate” (contaminate) means to make something unsafe by mixing something in that doesn’t belong there – something harmful. It’s often used to mean the same as “to pollute.” Julia is complaining about the company contaminating the environment, the natural world, “with dangerous chemicals and waste.”
“Chemical” (chemical) here refers to some sort of substance or material that has been prepared artificially by man, by human beings, although the word “chemical” has a much broader definition. It could refer to things that you find in nature as well – in the human body, for example. “Waste” (waste) can mean garbage or trash. In general, it refers to things that you no longer are using anymore, or perhaps things that are produced when you are making something else that you can’t use and you want to get rid of.
Robert says to Julia, “But your entire family works here. Aren’t you concerned you’ll cause trouble for them and the other workers?” Robert is concerned that Julia is picketing a place where her own family members work. Julia is not. She says, “What’s more important is their health.” She’s saying their health is more important than any harm that could come to them, any trouble they could get into because she is there picketing.
“The air quality in and out of this factory is at toxic levels and it’s endangering their health, not to mention what it’s doing to the ozone.” “Air quality “refers to how clean the air is, if you want to think of it that way. Big cities like Los Angeles often have poor air quality, although the air quality in Los Angeles has gotten a lot better in the past 25 years or so. Julia thinks the air quality inside as well as outside of the factory is at “toxic levels.” “Toxic” (toxic) means poisonous, something that could harm you or kill you, like listening to Britney Spears, for example –definitely toxic.
Julia says the air quality is endangering her family’s health – the ones that work there at the factory. “To endanger” (endanger) means to put someone in a situation where they could get harmed or to put someone in a dangerous situation. Julia thinks that the factory is “endangering” the health of her family members, “not to mention,” which here means in addition to, “what it’s doing to the ozone” (ozone).“Ozone” is a gas, but here Julia is using “ozone “as a shorter form of “ozone layer,” which is gas that is high up in the atmosphere.
There is a concern that certain chemicals that we use here on Earth might damage the ozone layer, and that might cause us further problems here on Earth. Robert says, “That’s terrible. Maybe I should help you picket.” Julia says, “Here’s a sign” (sign).A “sign” is a thick piece of paper or cardboard or metal that has words or images on it in order to communicate a certain message. People picketing a company will often walk around with signs that are on sticks or pieces of metal, and they hold the signs up in the air so people can see them as they’re driving by or walking by.
Robert says, “Okay, but maybe picketing is taking things a little too far.” “To take something too far “means to go beyond the limit of what is acceptable or even what is a good idea in order to get what you want to get. Julia disagrees. She says, “No way. Did you know that runoff from the factory has tainted the groundwater?” “Runoff” (runoff) is water that drains away from or flows away from an area of land or a building.
The water could have other chemicals in it – other things that may pollute the water. If the water then goes into a lake or a river or down into the ground, it could pollute other water – water that you use to drink. That’s what Julia is concerned about here. She’s concerned about the “groundwater” (groundwater).Groundwater is water that is found far below the surface of the earth and that is sometimes used for drinking. Julia is concerned that the water coming from the factory has “tainted the groundwater.” “To taint” (taint)here means the same as “to contaminate.”
She says, “Did you know that workers and people in the community are breathing in dangerous particulate matter?” “Particulate (particulate) matter” are very small pieces of something. Robert says, “I didn’t know that. Do you have proof of all that?” “Proof” (proof) is evidence – something that demonstrates that something is true.
Julia says, “Of course I have proof. I read it on the Internet.” No, she doesn’t say that. She says, “I have proof. Environmental groups have done independent tests.” Something that is “independent” (independent) is separate from the things around it. It’s not connected to the things around it or the organizations around it. Here I’m guessing that she means that these environmental groups have done tests not in conjunction with, or perhaps even with, the approval of the company that is supposed to be polluting in our dialogue.
Don’t confuse the word “independent” with another term, “objective” (objective). “Objective “would refer to something that is just the facts, that only has the factual information or evidence and isn’t trying to give you a certain conclusion regardless of what the facts are.“Independent” just means it was done by someone not in the company, in this case. That person may still have their own particular biases, of course.
Robert says, “Then it’s actually dangerous for me to be standing here talking to you and breathing in this toxic air.” Robert realizes that if what Julia says is true, he shouldn’t even be there talking to her because the air is toxic. Julia says, “That’s true and your willingness to help me picket is really commendable.” “Commendable” (commendable) means admirable or worthy of praise – something that you would congratulate someone on because they are doing a good thing.
Julia is congratulating or thanking Robert for being there with her even though it’s dangerous. Then she realizes that Robert is not, in fact, going to stay there. She says, “Hey, where are you going?”meaning of course that Robert is now walking away from Julia. He’s not going to stand there if he is going to be in any danger.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Julia: Stop poisoning us! Stop poisoning us!
Robert: Why are you picketing in front of this factory?
Julia: This factory is polluting our air and water. They’re responsible for contaminating the environment with dangerous chemicals and waste.
Robert: But your entire family works here. Aren’t you concerned you’ll cause trouble for them and the other workers?
Julia: What’s more important is their health. The air quality in and out of this factory is at toxic levels and it’s endangering their health, not to mention what it’s doing to the ozone.
Robert: That’s terrible. Maybe I should help you picket.
Julia: Here’s a sign.
Robert: Okay, but maybe picketing is taking things a little too far.
Julia: No way! Did you know that runoff from the factory has tainted the groundwater? Did you know that workers and people in the community are breathing in dangerous particulate matter?
Robert: I didn’t know that. Do you have proof of all that?
Julia: Of course I have proof. Environmental groups have done independent tests.
Robert: Then it’s actually dangerous for me to be standing here talking to you and breathing in this toxic air.
Julia: That’s true and your willingness to help me picket is really commendable. Hey, where are you going?
[end of dialogue]
If you want proof about ESL Podcast and whether it works or not, listen to the wonderful scripts by our wonderful scriptwriter, Dr. Lucy Tse, and you’ll have all the proof you need.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to poison – to sicken or kill someone through exposure to dangerous chemicals or other toxins
* Young children sometimes poison themselves if they have access to cleaning supplies.
to picket – to demonstrate; to stand in front of a building, carrying signs and shouting statements in order to raise interest in and show support for changing a policy and/or improving social conditions in some way
* Why are people picketing in front of the mayor’s office today?
to pollute – to contaminate; to make air, land, or water dirty and unsafe through exposure to harmful substances
* The factory has been polluting the nearby river for years.
to contaminate – to make something, such as air, land, or water, impure or dirty and unsafe through exposure to harmful substances
* If you put that spoon in your mouth and then dip it into the jar of peanut butter, it contaminates the contents of the jar by spreading your germs.
environment – the natural world; the surroundings or conditions in which people, plants, and other living things live
* Blake wants to study how penguins, polar bears, and other arctic animals have adapted to their cold environment.
chemical – a substance that has been artificially prepared, usually used to clean or create other substances
* This housecleaning company specializes in cleaning without the use of harsh chemicals.
waste – garbage; trash
* The company is trying to find new ways to get rid of the increasing amount of production waste.
air quality – a measure of how clean the air is
* Cities in valleys often have poor air quality, because pollutants get trapped between the mountains.
toxic – poisonous; with chemicals that can cause harm or death
* We all need vitamins, but some of them are toxic at high doses.
to endanger – to put someone or something in danger; to place someone or something in harm’s way; to present a risk to one’s safety or security
* How could you endanger your six-year-old nephew by letting him ride the subway alone in New York City?
ozone – O3; a gas that is polluting near the ground, but forms a beneficial ozone layer in the atmosphere, protecting Earth and living things from the sun’s harmful ultraviolet rays
* Can photocopy machines can be a source of indoor ozone pollution?
sign – a thick piece of paper or a thin piece of metal with words and/or images that convey (show) a message
* According to that sign, this is the last gas station for the next 100 miles.
runoff – liquid, especially rainfall, that moves downward from one point toward a stream, river, lake, or ocean, especially taking soil (dirt) and chemicals with it
* The city is encouraging people to use professional car washes rather than washing their cars in their driveways, which leads to runoff problems.
groundwater – water that is found far below the surface of the earth in small spaces between soil (dirt) and rocks
* Will this mining operation pollute the groundwater?
particulate – with many very small pieces, especially dispersed in air
* This air is so dirty with particulate matter that it appears brown from a distance.
proof – evidence; something that demonstrates the presence, existence, or occurrence of something
* Do you have any proof that you were at home on the night of the murder?
independent – conducted separately, without the influence or involvement of other parties in an unbiased way
* Independent researchers have clearly demonstrated the health consequences of smoking, but the scientists employed by tobacco companies have reached different conclusions.
commendable – admirable and worthy of praise
* The detective’s efforts to identify the criminal are commendable.
Comprehension Questions
1. Which of these affects air quality?
a) Waste
b) Ozone
c) Runoff
2. What does Julia mean when she says, “Environmental groups have done independent tests”?
a) The tests were not conducted by the factory owners.
b) The tests were each conducted separately at different times.
c) There were no restrictions governing the tests.
Answers at bottom.
What Else Does It Mean?
waste
The word “waste,” in this podcast, means garbage or trash: “Many electronics manufacturers have programs to help consumers recycle their electronics waste, such as toner cartridges.” The word “waste” can also refer to money that is spent unnecessarily, with little or no benefit received in return: “The auditor was shocked by the amount of government waste.” The phrase “to go to waste” means to not be used and then spoil (become bad): “Let’s eat the grapes soon, so they don’t go to waste.” Finally, if something is “a waste of time,” it is not worthwhile: “Watching this stupid TV show is a waste of time. Why don’t you go outside and get some fresh air?”
runoff
In this podcast, the word “runoff” means liquid, especially rainfall, that moves downward from one point toward a stream, river, lake, or ocean, especially taking soil (dirt) and chemicals with it: “The farmers are concerned that their field runoff might contain dangerous levels of pesticides and fertilizer.” The phrase “to run off (something)” means to be powered by a particular source of energy: “These smoke detectors run off batteries.” Or, “This car runs off natural gas instead of gasoline.” The phrase “to run off with (someone)” means to secretly leave one’s family to start a romantic relationship with another person: “We were all shocked when Kris left his life and ran off with his secretary.” Finally, the phrase “to run (something) off” can mean to make a few photocopies of something: “Please run off 10 copies of this report before the meeting this afternoon.”
Culture Note
Energy Star
In 1992, the Environmental Protection Agency (EPA; the U.S. agency responsible for protecting the natural environment) and the Department of Energy created the Energy Star “designation” (special name and recognition that something meets certain standards) to make it easy for consumers to recognize products with high “energy efficiency” (minimal use of energy). The Energy Star is a “voluntary” program, meaning that manufacturers can choose whether they want to apply for the Energy Star designation.
Energy Star labels are “affixed” (attached) to many consumer products, including computers and “peripherals” (devices that work with a computer, such as printers and scanners), kitchen “appliances” (machines that perform a specific task in the kitchen, such as toasters and blenders), lighting, office equipment, and more. Products that have the Energy Star “label” (an image on packaging) usually use 20-30% less energy than the amount required by “federal” (national) standards.
The Energy Star program has expanded. Today, even new homes can receive the Energy Star designation if they use at least 15% less energy than typical new homes do. Builders earn this designation by using a lot of “insulation” (materials between walls, above ceilings, and below floors to maintain a constant temperature) and energy efficient HVAC (heating, ventilating, and air conditioning) systems.
Many large consumer electronics, such as freezers, furnaces, and televisions, also have an “EnergyGuide” label that indicates how much energy the product uses, as well as an “estimate” (approximate value) of how much the consumer will spend on energy to “operate” (run) the appliance. Unlike the Energy Star designation, the EnergyGuide label is required of all major appliances and equipment.
Comprehension Answers
1 - b
2 - a