= 1196
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,196 – Checking Facts and Figures.
This is English as a Second Language Podcast episode 1,196. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com and become a member of ESL Podcast. When you do, you can download the Learning Guide for this episode on our website. We also have additional courses in Business English and Daily English that I think you will enjoy. And like us on Facebook, if you haven’t already. Go to facebook.com/eslpod.
This dialogue is about making sure you have your facts correct, as well as numbers, that are part of your report or whatever it is you are working on. Let’s get started.
[start of dialogue]
Takagi: Before we disseminate this report, I need you to fact-check it. I don’t want a repeat of what happened last year.
Ellie: What happened last year? I wasn’t working here then.
Takagi: Last year’s report had a lot of small inaccuracies and a few major errors. We ended up having to issue a second version of the report.
Ellie: Okay, but I thought it had already been signed off on by the department heads.
Takagi: It has, but those are the same department heads who skimmed the report last year and didn’t catch all those problems. I want you to go through it with a fine-tooth comb.
Ellie: What should I check?
Takagi: Everything. I want you to verify the facts and figures and to flag anything that is outright wrong or even a little suspect.
Ellie: Okay, I’ll do that, but this will take some time.
Takagi: What are you doing this weekend?
Ellie: Nothing, now.
[end of dialogue]
Takagi begins our dialogue by saying to Ellie, “Before we disseminate this report, I need you to fact-check it. I don’t want a repeat of what happened last year.” “To disseminate” (disseminate) means to distribute, to give to a number of different people, to share information or copies of something with many different people. It’s a word you will hear sometimes in business English. It basically just means to give to a number of different people a piece of information, or in this case a report – a written document that describes or explains something.
“To fact-check” (fact-check) means to look at the specific information in a report, the details of something, to make sure that everything is correct, that everything is accurate, that all of the information you are giving is true. The verb “to fact-check” has become popular in recent years, especially in some American newspapers and websites that report on politics. When a politician says something, when someone involved in public life or policy says something, the newspapers or websites will try to make sure that what the person said is correct. They will “fact-check” it.
Unfortunately, most newspapers and websites have their own political biases, so to fact-check for them usually means to see if it agrees with their own political views, and if it doesn’t, they’ll find some reason to say that it was wrong. I don’t really rely very much on newspapers and websites that “fact-check” what politicians say. I don’t normally think they are telling the complete truth, but maybe that’s just me.
Takagi isn’t talking about politics. He’s talking about a report of information that he wants Ellie to fact-check, to look at carefully to make sure it is all correct. He says, “I don’t want a repeat of what happened last year.” A “repeat” would be when something happens again. In this case, it sounds like something bad happened last year and Takagi doesn’t want that to happen again.
Ellie asks, “What happened last year? I wasn’t working here then. Takagi answers, “Last year’s report had a lot of small inaccuracies and a few major errors.” “Inaccuracies” (inaccuracies) are things that are not correct, things that are wrong. “To be accurate” means to be correct. “To be inaccurate” means to be not correct, or wrong. So, “inaccuracies” are things that are wrong. Takagi says these were “small inaccuracies,” meaning not very important. However, there were also some “major,” or important or big, “errors” (errors). An “error” is something that is wrong, a mistake.
Takagi says, “We ended up,” meaning we had to, as a result – “We ended up having to issue a second version of the report.” “To issue” (issue) here means to publish or to officially present something to a group of people. Takagi had to issue “a second version” (version). Let’s say I have a web page. The first time I put up the web page, I’m happy with it, but a week later, I decide I want to make some changes. So I go in and I change the website – maybe I change the color or I add some photographs to the website. The original web page is my “first version.” After I make the changes, that’s my “second version.”
“Version,” then, refers to the form of something. You could write a report and then a month later decide you want to change the report. So you make the changes and then you give the report to your boss again. You say, “This is the second version of this report.” “Version” is used a lot in software, in computer applications. We talk about 1.0, 2.0, 3.0 – these are different versions of a computer application or an app that has improvements or changes to it. Takagi is talking about “issuing a second version of the report” – an update, a report that has been changed and corrected.
Ellie says, “Okay, but I thought it had already been signed off on by the department heads.” “To sign (sign) off on” something means to approve of something, to say something is okay. A “department” (department) is a part or section or division inside of a company. A “department head” (head) is the person who is the boss of that section or division of the company. Ellie is saying that she thought this report had already been approved by, signed off on by, the department heads.
Takagi says, “It has, but those are the same department heads who skimmed the report last year and didn’t catch all those problems.” Takagi is saying that yes, the department heads approved of this report, but they only “skimmed” the report last year. “To skim” (skim) means to read through something very quickly, not looking at every word in the report. Because the department heads only “skimmed” the report last year, the report had a bunch of mistakes, a bunch of errors. That’s why they didn’t “catch” (catch) all those problems. “To catch” here means to find or identify a mistake or an error.
Takagi says, “I want you to go through it with a fine-tooth comb.” The expression “to go through something with a fine (fine) – tooth (tooth) comb (comb)” means to look through something very carefully, to make sure that everything is correct. A “comb” is something you use to straighten your hair or to put your hair back into place – hair on the top of your head, that is. We call the little parts of a comb “teeth,” just like teeth in your mouth. “Fine-tooth combs” are combs where the teeth are very close together. The idea, then, is that you are looking at very small issues, very small details, to make sure that everything is correct.
Ellie says, “What should I check? Takagi says, “Everything. I want you to verify the facts and figures and to flag anything that is outright wrong or even a little suspect.” “To verify” (verify) means to make sure that it is correct, to look at it closely and make sure it is true, make sure it is accurate. “Verify” comes from the Latin word “veritas” (veritas), meaning truth. Takagi wants Ellie to verify the “facts” – that is, the information – and “figures” (figures). “Figures” refer to numbers.
The title of this episode, “Facts and Figures,” contains an expression we often use in talking about information that has both words and numbers to describe it. So, the “figures” here would be the numbers in the report. Takagi wants Ellie “to flag” (flag) anything that is outright wrong. “To flag” means to draw attention to something. In this case, it probably means to mark it with a pen or a pencil so that Takagi can find that information easily when he looks through the report. To flag something in general means to call attention to it, to say, “Hey, look at this. There might be a problem with this.”
Something that is “outright (outright) wrong” is something that is obviously wrong, something that you don’t even have to go and investigate. It is clearly wrong. Something that is a little “suspect” (suspect) is something that doesn’t seem right. It might be right. It might be wrong. You’re not exactly sure, but it looks like it might be incorrect. If you say something “looks a little suspect,” you’re saying it looks wrong but you’re not exactly sure.
Ellie says, “Okay, I’ll do that, but this will take some time.” Takagi says, “What are you doing this weekend?” He, of course, is implying that Ellie should work on this over the weekend. Ellie replies, “Nothing, now,” meaning, well, she won’t be able to do anything this weekend for fun on her own because now she’s going to be working on this report instead of relaxing as you should on the weekends.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Takagi: Before we disseminate this report, I need you to fact-check it. I don’t want a repeat of what happened last year.
Ellie: What happened last year? I wasn’t working here then.
Takagi: Last year’s report had a lot of small inaccuracies and a few major errors. We ended up having to issue a second version of the report.
Ellie: Okay, but I thought it had already been signed off on by the department heads.
Takagi: It has, but those are the same department heads who skimmed the report last year and didn’t catch all those problems. I want you to go through it with a fine-tooth comb.
Ellie: What should I check?
Takagi: Everything. I want you to verify the facts and figures and to flag anything that is outright wrong or even a little suspect.
Ellie: Okay, I’ll do that, but this will take some time.
Takagi: What are you doing this weekend?
Ellie: Nothing, now.
[end of dialogue]
Our dialogues don’t have any inaccuracies or major errors because they’re written by the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
to disseminate – to distribute; to share information or copies of something with many people
* We need to disseminate information about this new technique to as many nurses as possible.
report – a written document that describes or explains something, or provides an update
* Please write a three-page report summarizing your sales figures for the year and explaining why they are so much lower than our goals.
to fact-check – to check the details of something very carefully to make sure that everything is correct, accurate, and precise
* Our newspaper has a staff of editors who fact-checks any articles before they are published.
inaccuracy – something that is not correct; an error
* Any inaccuracies in your application will eliminate you from consideration.
error – a mistake or problem, especially an inaccuracy or something that does not work properly
* Why are there so many errors in this software? Didn’t the developers test it thoroughly before selling it?
to issue – to publish; to officially present something to an audience or the public
* The President is going to issue an official statement about this situation at 4:00 this afternoon.
version – draft; the document as it Is at one point in the writing process, but not necessarily the final document
* In the latest version of the proposed contract, there is no mention of any way to cancel for unsatisfactory work.
to sign off on (something) – to approve of something; to say that something is good enough; to issue or grant one’s approval
* We won’t start developing the website until the client has signed off on the page layout and design.
department head – the top manager or other leader of part of an organization
* The department heads for finance and marketing need to work together more closely.
to skim – to read something very quickly, paying attention only to headings and the most important key words
* If you don’t have time to read the full report before the meeting, try skimming it by reading the introduction, the headings, the first sentence of each paragraph, and the conclusion.
to catch – to find or identify a problem or error
* I can’t believe nobody caught that $1 million error in the financial statements!
to go through (something) with a fine-tooth comb – to review something very carefully, paying attention to all the small details so that nothing is missed
* We’re going to go through these papers with a fine-tooth comb, looking for anything that might help us determine what went wrong.
to verify – to review, check, and confirm that accuracy of something; to make sure that something is honest, true, and accurate
* Do reporters have a responsibility to verify politicians’ claims before they print them in newspaper articles?
figure – a number; numerical or quantitative data or information
* These figures don’t seem right. Could you please check your calculations?
to flag – to draw attention to something; to mark something so that one can return to it later to address or correct it
* That’s a difficult question. Let’s flag it for now, and we can come back to it later once we’ve answered the rest of the test questions.
outright – complete; blatant; obvious; entire; direct
* That’s an outright lie! Why would you say something like that?
suspect – suspicious; subject to question; possibly incorrect, wrong, or guilty
* At this point in the investigation, anyone who was in the building during the time of the theft is suspect.
Comprehension Questions
1. What will happen when they disseminate the report?
a) They will send it to the printer.
b) They will update it with new information.
c) They will share it with other people.
2. What did the department heads do when they skimmed the report?
a) They approved it.
b) They added content to it.
c) They read it very quickly.
Answers at bottom.
What Else Does It Mean?
to issue
The verb “to issue,” in this podcast, means to publish or to officially present something to an audience or the public: “The agency issues weekly updates on its activities.” The verb “to issue” can also mean to give something to someone: “The police officer issued 16 tickets to speeding drivers last night.” As a noun, an “issue” is one volume or edition of a magazine or journal: “Have you read the spring issue of The Journal of Childhood Psychology?” An “issue” can also be a problem or a challenging situation: “Two issues are contributing to the delays in the construction: heavy rain and a labor shortage.” Finally, the phrase “standard-issue” describes something that is given to all people and is always the same: “These pants and shirts are standard-issue for new military recruits.”
to flag
In this podcast, the verb “to flag” means to draw attention to something, or to mark something so that one can return to it later to address or correct it: “They put small pieces of tape on the walls to flag spots that the painters missed.” The verb “to flag (someone or something) down” can mean to wave one’s arms to get the attention of someone or something so that it stops: “Could you please help me flag down a taxi?” The verb “to flag” can also mean to become very tired, especially after a lot of activity or effort: “After a few hours of studying, we were all flagging and decided to go eat dinner before resuming.” Finally, a “red flag” is a warning, or an indication that something bad is happening: “Those suspicious travel reimbursements were a red flag that there was some corruption in our accounting department.”
Culture Note
New Journalism
“New Journalism” is a style of writing and of news reporting in which the “reporter” (the person who reports or presents the news) is less “objective” (unbiased; only reporting on the facts) than in other types of “journalism” (news reporting). In New Journalism, the reporter becomes “immersed” (completely surrounded by and focused on) the story being covered and may even “take on” (adopt; have) a role in the story. In contrast, more “conventional” (traditional; normal) journalism requires that the journalist avoid becoming too “involved” (with a role and/or an emotional connection) and that her or she be objective, reporting only the facts.
New Journalism “flourished” (became popular and grew) in the 1960s and 1970s, but it had almost disappeared by the early 1980s. Articles in the style of New Journalism were most often found in magazines rather than newspapers. The articles often read more like “fiction” (stories made up with one’s imagination, not based on facts in real life) than traditional news stories. “Fans” (people who like something) of New Journalism believed that it would “replace” (take the place of) or “complement” (add to something while being next to or alongside it) “novels” (stories in book form). The writers were using fiction “techniques” (ways of doing thing), such as character development, in their “non-fiction” (writing about facts and real events) reporting.
Although many people enjoyed reading articles in the New Journalism style, “critics” (people who analyze and criticize something) found that it put the journalist in the role of a “psychologist” (scientists or researchers studying the mind) or a “sociologist” (scientists or researchers studying society and its problems) rather than a reporter who simply wanted to share the news.
Comprehension Answers
1 - c
2 - c