

= 0021 Are test scores the backbone of meritocracy or the nexus of privilege?
:toc: left
:toclevels: 3
:sectnums:

'''


== Are test scores the backbone of meritocracy or the nexus of privilege?



[If they *significantly 有重大意义地；显著地；明显地 decreased (v.)使降低; 降低 the number of* successful applicants 申请人 from already disadvantaged 弱势的；社会地位低下的 groups], 主 *such a sacrifice 谓 would presumably 很可能；大概；想必是 not be justified* 证明…正确（或正当、有理） by *a minor gain* (n.)好处；利益；改进 in predictive (a.) power.

主 How institutions *judge (v.) this trade-off* (n.)（在需要而又相互对立的两者间的）权衡，协调 谓 depends on their mission, circumstances and the cohort （有共同特点或举止类同的）一群人，一批人 they want to attract.

*This goes to the heart of an age-old 古老的；已存在很久的 question*. Should universities *consider (v.) themselves primarily (ad.)主要地；根本地 as* centres of *academic excellence* (n.)优秀；杰出；卓越, and therefore strive (v.) to accept the students most likely *to excel (v.) 擅长；突出 academically*?

Or *should they accept a broader mission* to improve society, which could mean sacrificing (v.) some academic excellence(n.) *in the pursuit of* a different definition of equality?


[.my1]
.标题
====
.trade-off
(n.) ~ (between sth and sth) : the act of balancing two things that you need or want but which are opposed to each other （在需要而又相互对立的两者间的）权衡，协调


.cohort
⇒ co-, 强调。-hort, 围住，词源同yard, court.

.excellence
(n.) ~ (in sth) : the quality of being extremely good 优秀；杰出；卓越


.excel
~ (in/at sth/at doing sth) to be very good at doing sth 擅长；善于；突出

如果sat考试, 大大降低了那些来自贫困阶层的学生的入学成功率, 则sat即使能够带来更好的大学成绩预测能力, 这一点点的好处, 也不足以证明sat考试就应该存在下去. 大学机构如何权衡这种取舍, 取决于他们自身的使命, 他们所站立的背景, 以及他们想要吸引哪类人进大学.

这其实涉及到了一个古老的问题 — 大学, 应该视自己为最优秀的学术者的中心, 因此只接收那些学术能力最出色的学生. 还是说, 他们应该抱持着更广泛的造福社会的使命, 从而牺牲一些学术能力优秀的学生, 而去追求另一种概念的平等?
====


'''

== <pure> Are test scores the backbone of meritocracy or the nexus of privilege?

If they significantly decreased the number of successful applicants from already disadvantaged groups, such a sacrifice would presumably not be justified by a minor gain in predictive power. How institutions judge this trade-off depends on their mission, circumstances and the cohort they want to attract. This goes to the heart of an age-old question. Should universities [underline]#consider# themselves [underline]#primarily as# centres of academic excellence, and therefore strive to accept the students most likely to excel academically? Or should they accept a broader mission to improve society, which could mean sacrificing some academic excellence in the pursuit of a different definition of equality?


'''
