


= 0023  Youngsters’ job preferences and prospects are mismatched
:toc: left
:toclevels: 3
:sectnums:

'''

== Youngsters’ job preferences and prospects are mismatched


THE WORLD of work is changing. Are people ready for the new job outlook 前景；可能性?

主 A survey of 15-year-olds across 41 countries by the OECD 经济合作与发展组织, a club of mostly rich countries, 谓 found that teenagers *may have unrealistic (a.)不切实际的；不实事求是的 expectations 预期；盼望 about* the kind of work that will be available 可获得的；可购得的；可找到的.

Four of the five most popular choices were *traditional professional 职业的；专业的 roles*: doctors, teachers, business managers and lawyers.

Teenagers *clustered 群聚；聚集 around* the most popular jobs, with the top ten being chosen by 47% of boys and 53% of girls.

Those shares *were significantly higher than* when the survey was conducted 组织；安排；实施；执行 back in 2000.


[.my1]
.标题
====
.outlook :
~ (for sth) the probable future for sb/sth; what is likely to happen 前景；可能性

.OECD
Organization for Economic Cooperation and Development 经济合作与发展组织



职场正在发生变化。人们准备好迎接新的工作前景了吗? 经合组织(OECD)对41个国家的15岁青少年进行了一项调查，发现青少年可能对未来的工作, 有不切实际的期望。

在五个最受欢迎的选择中，有四个是传统的专业角色:医生、教师、企业经理, 和律师。青少年聚集在最受欢迎的工作周围，47%的男孩和53%的女孩, 选择了前十名。这比例明显高于2000年进行调查时的水平。
====


[In Britain] only *one in five* computer-science university students is a woman — a big problem at a time (when *the World Economic Forum* predicts that technology will create more than *a quarter of* all jobs in newly emerging professions).

Women *play a much bigger role* in *the health- and social-care sectors*, which *are also poised(a.) 处于准备状态；蓄势待发 for* 有充分准备；准备好；蓄势待发 expansion 扩张；扩展；扩大；膨胀.

The BLS 劳工统计局 forecasts that 主 eight of the 12 *fastest-growing jobs* in America *over the next few years* 系 will be in those areas, with roles ranging [from] *occupational-therapy 治疗；疗法 assistants* 助理；助手 [to] genetic 基因的；遗传学的 counsellors （尤指针对私人问题的）顾问；辅导顾问.

*The snag （尤指潜在的、意外的、不严重的）问题，困难，障碍 is that* some of these jobs *are not very well paid*. Home-health and *personal-care 个人护理 aides* （尤指从政者的）助手 (with the third- and fourth-fastest *growth rates* 增长率, respectively 分别地；各自地，独自地) *had median (a.)中间值的；中间的 annual salaries* in 2018 of just over $24,000.


[.my1]
.标题
====
.BLS :
劳工统计局 Bureau of Labor Statistics

.Occupational therapy
Occupational therapy  is a method /of helping people who have been ill or injured /to develop skills /or get skills back /by giving them certain activities to do. 职业疗法

.personal care
N help given to elderly or infirm people with essential everyday activities such as washing, dressing, and meals 个人护理; 给年迈体弱者提供的必要日常护理，如帮其洗衣、穿衣及照料饮食

英国，只有五分之一的计算机科学专业大学生, 是女性，这是一个大问题，因为世界经济论坛预测，在新兴职业中，技术将创造超过四分之一的就业机会。

妇女在保健和社会保健部门, 发挥着更大的作用，这些部门也准备扩大规模。劳工统计局预测，未来几年, 美国12个增长最快的工作中, 有8个将在这些领域，从职业治疗助理, 到基因顾问。问题是，其中一些工作的薪水并不高。家庭健康和个人护理助理(增长率分别位居第三和第四)2018年的平均年薪, 只略高于2.4万美元。
====



'''

== <pure> Youngsters’ job preferences and prospects are mismatched


THE WORLD of work is changing. Are people ready for the new job outlook? A survey of 15-year-olds across 41 countries by the OECD, a club of mostly rich countries, found that teenagers may have unrealistic expectations about the kind of work that will be available.

Four of the five most popular choices were traditional professional roles: doctors, teachers, business managers and lawyers. Teenagers clustered around the most popular jobs, with the top ten being chosen by 47% of boys and 53% of girls. Those shares were significantly higher than when the survey was conducted back in 2000.


In Britain only one in five computer-science university students is a woman — a big problem at a time (when the World Economic Forum predicts that technology will create more than a quarter of all jobs in newly emerging professions).

Women play a much bigger role in the health- and social-care sectors, which are also poised  for expansion. The BLS forecasts that eight of the 12 fastest-growing jobs in America over the next few years will be in those areas, with roles ranging [from] occupational-therapy assistants [to] genetic counsellors. The snag  is that some of these jobs are not very well paid. Home-health and personal-care aides  (with the third- and fourth-fastest growth rates, respectively) had median annual salaries in 2018 of just over $24,000.

'''

