
=  0078. Discussing Moral Issues: Important Structures and Terms 讨论道德问题：重要的结构和术语
:toc: left
:toclevels: 3
:sectnums:

'''

== Discussing Moral Issues: Important Structures and Terms 讨论道德问题：重要的结构和术语


Imagine that you want to talk about moral issues – your opinion about what is correct behavior and what is incorrect behavior.

Common positive adjectives include right, correct, appropriate  合适的；恰当的 or justified （做某事）有正当理由的,合乎情理.

Common negative adjectives include wrong, incorrect, terrible, or unjustified.

A person might say, “My decision was appropriate,” “their behavior was terrible,” “we were wrong,” and so on.


[.my1]
.案例
====
想象一下，您想谈论道德问题——您对什么是正确行为、什么是不正确行为的看法。

常见的积极形容词包括正确的、正确的、适当的或合理的。 +
常见的负面形容词包括错误的、不正确的、可怕的或不合理的。

一个人可能会说，“我的决定是正确的”，“他们的行为很糟糕”，“我们错了”，等等。
====


But there are many other ways a person can describe their opinion of an action.

Let’s listen to a few words from United States President Joe Biden’s recent *State of the Union* 国情咨文 speech.

Putin’s attack on Ukraine was premeditated (a.)(罪恶或恶行)预谋的；事先策划的 and totally unprovoked (a.)(尤指攻击)未受挑衅的；无缘无故的.

“Premeditated” (a.)(罪恶或恶行)预谋的；事先策划的 is an adjective that means done or made according to a plan. Legal cases 词讼，辞讼案例 often use this term. A person might be *convicted (v.) of* 定罪；宣判…有罪  premeditated murder, for example.


[.my1]
.案例
====
.unprovoked
(a.) ( especially of an attack 尤指攻击 ) not caused by anything the person being attacked has said or done 未受挑衅的；无端的 +
• an act of unprovoked aggression 无端的侵犯行为 +
• Her angry outburst was totally unprovoked. 她的暴跳如雷完全是无理取闹。

但人们还有很多其他方式, 可以描述他们对某一行为的看法。让我们听听美国总统乔·拜登最近发表的国情咨文演讲中的几句话。 +
普京对乌克兰的攻击是有预谋的，完全是无端的。

“预谋”是一个形容词，意思是按照计划完成或制作。法律案件经常使用这个术语。例如，一个人可能会被判犯有预谋谋杀罪。
====

Another key area of grammar that connects with discussions about moral issues is the idea of necessity – an action must or must not be done. English speakers use several structures to express necessity, but some of the important ones are “need to...” and “have got to …” or “have got to do....”

You might say, “You need to apologize to him,” or “he needs to apologize to you.”


[.my1]
.案例
====

与道德问题讨论相关的另一个语法关键领域, 是"必要性"的概念——某种行为必须或不可以做。英语使用者使用多种结构来表达必要性，但其中一些重要的结构是“need to...”和“have got to ...”或“have got to do...”

你可能会说，“你需要向他道歉”，或者“他需要向你道歉”。
====

You might also use “have got to...” to express a similar idea, as in “You have got to apologize to him.”


Let’s listen to UK *Prime Minister* 首相，总理 Boris Johnson use the structure “have got to do ...” to talk about what he believes is a correct course 方针；行动方向;（船或飞机的）航向，航线 of action.

We’ve got to do everything we can to change the heavy odds 不利条件；掣肘的事情；逆境 that Ukraine faces (v.).


[.my1]
.案例
====

你也可以使用“have had to...”来表达类似的想法，例如“你必须向他道歉”。

让我们听听英国首相鲍里斯·约翰逊用“必须做……”的结构来谈论他认为正确的行动方针。 +
我们必须尽一切努力改变乌克兰面临的困境。
====


'''

== Discussing Moral Issues: Important Structures and Terms


Imagine that you want to talk about moral issues – your opinion about what is correct behavior and what is incorrect behavior.

Common positive adjectives include right, correct, appropriate or justified.

Common negative adjectives include wrong, incorrect, terrible, or unjustified.

A person might say, “My decision was appropriate,” “their behavior was terrible,” “we were wrong,” and so on.




But there are many other ways a person can describe their opinion of an action.

Let’s listen to a few words from United States President Joe Biden’s recent State of the Union speech.

Putin’s attack on Ukraine was premeditated and totally unprovoked.

“Premeditated” is an adjective that means done or made according to a plan. Legal cases often use this term. A person might be convicted of premeditated murder, for example.


Another key area of grammar that connects with discussions about moral issues is the idea of necessity – an action must or must not be done. English speakers use several structures to express necessity, but some of the important ones are “need to...” and “have got to …” or “have got to do....”

You might say, “You need to apologize to him,” or “he needs to apologize to you.”


You might also use “have got to...” to express a similar idea, as in “You have got to apologize to him.”


Let’s listen to UK Prime Ministry Boris Johnson use the structure “have got to do ...” to talk about what he believes is a correct course of action.

We’ve got to do everything we can to change the heavy odds that Ukraine faces.



'''

