
= 0137. Are Ultra-Processed Foods Really all that Unhealthy? 超加工食品真的那么不健康吗？
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css

'''

== Are Ultra-Processed Foods Really all that Unhealthy? 超加工食品真的那么不健康吗？

Processed (a.) foods have been blamed for many health problems, but dietary 饮食的 research is tricky (a.)难办的；难对付的,狡猾的 and nuanced (a.)微妙的；具有细微差别的

[.my2]
加工食品被认为是许多健康问题的罪魁祸首，但饮食研究是棘手且微妙的

After decades of searching, many scientists believe they have finally pinned down the main problem with our modern diets—the factor driving ever-escalating rates of obesity, diabetes, heart disease and any number of other serious chronic conditions. The culprit isn’t saturated fats, trans fats or some new killer fat you haven’t of. It’s not cholesterol, carbs or sugars; dairy, gluten or meat. It isn’t a specific thing at all.

[.my2]
经过数十年的探索，许多科学家相信, 他们终于找到了现代饮食的主要问题——导致肥胖、糖尿病、心脏病, 和其他严重慢性疾病发病率不断上升的因素。罪魁祸首不是饱和脂肪、反式脂肪或一些你没有的新杀手脂肪。它不是胆固醇、碳水化合物或糖；而是胆固醇。乳制品、麸质或肉类。这根本不是一个具体的事情。

The problem, according to this increasingly popular argument, is that we’re eating lots of ultra-processed food or UPF. Traditionally, people used limited processing techniques such as cooking and pickling to preserve food or to make it more pleasant to eat. Modern food companies transform food much more extensively through techniques such as extrusion and molding, adding lab-derived components including flavorings, emulsifiers and preservatives. They use this additional processing to make foods that are cheaper, longer-lasting and more convenient.

[.my2]
根据这个日益流行的论点，问题在于我们正在吃大量的"超加工食品"或 UPF。传统上，人们使用烹饪和腌制等有限的加工技术, 来保存食物, 或使其味道更美味。现代食品公司通过挤压和成型等技术，添加调味剂、乳化剂, 和防腐剂等实验室衍生成分，对食品进行更广泛的改造。他们利用这种额外的加工, 来生产更便宜、更持久, 和更方便的食品。

There’s a long, formal scientific definition, but it can be boiled down to this: If it’s wrapped in plastic and has at least one ingredient that you wouldn’t find in your kitchen, it’s UPF.

[.my2]
有一个很长、正式的科学定义，但可以归结为：如果它用塑料包裹，并且至少含有一种你在厨房里找不到的成分，那么它就是 UPF.


Many researchers and nutritionists say this shift has been a costly one. They point to a series of studies suggesting that ultra-processed food is a major driver of obesity, heart disease, cancer and even neurodegenerative conditions like Alzheimer’s.

[.my2]
许多研究人员和营养学家表示，这一转变代价高昂。他们指出，一系列研究表明，超加工食品是肥胖、心脏病、癌症甚至阿尔茨海默氏症等神经退行性疾病的主要驱动因素。

“What makes ultra-processed foods so bad for your health?” probed The Economist in August.

[.my2]
“是什么让超加工食品对你的健康如此不利？”八月份对《经济学人》进行了调查。

Although there is good research raising concerns about ultra-processed food, we should be hesitant to declare it the primary scourge of the modern diet. The case against ultra-processed food isn’t as solid as the headlines and public outcry would lead us to believe. The research connecting these processed foods to health problems has limitations, and there is contradictory evidence as well. This is a classic example of how research doesn’t speak for itself: It must always be interpreted, by people, in the context of other, often conflicting evidence. “Are there really studies that show that ultra-processed foods are unhealthy? It’s pushing very weak data to make a case,” says Gunter Kuhnle, a nutrition researcher at the University of Reading.

[.my2]
尽管有很好的研究引起了人们对超加工食品的担忧，但我们应该犹豫是否将其宣布为现代饮食的主要祸害。反对超加工食品的理由, 并不像头条新闻和公众的强烈抗议让我们相信的那样可靠。将这些"加工食品"与"健康问题"联系起来的研究, 存在局限性，而且也存在相互矛盾的证据。这是一个典型的例子，说明研究本身并不说明问题：人们必须始终在其他常常相互矛盾的证据的背景下对其进行解释。 “真的有研究表明'超加工食品'不健康吗？它用非常弱的数据来证明这一点，”雷丁大学营养研究员冈特·库恩勒(Gunter Kuhnle)说。

The field of nutrition has a long history of overreacting to contemporary research trends, and we risk making the same mistake now with processing. “We’ve had that issue in the past, as with low-fat recommendations” that later turned out to be counterproductive, says Duane Mellor, a dietitian at Aston University in England. “We’ve messed up too many times. We need to make smarter changes more carefully.” The evidence on ultra-processed food, as is often the case in science, refuses to yield simple, black-or-white answers.

[.my2]
营养领域长期以来对当代研究趋势反应过度，现在我们在加工方面, 也面临着犯同样错误的风险。英国阿斯顿大学营养师杜安·梅勒 (Duane Mellor) 表示，“我们过去就遇到过这个问题，就像低脂建议一样”，但后来证明效果适得其反。 “我们已经搞砸了太多次了。我们需要更谨慎地做出更明智的改变。”正如科学中经常出现的情况一样，有关"超加工食品"的证据拒绝给出简单、非黑即白的答案。



But there is one key, well-known limitation of this kind of retrospective research: Correlation does not prove causation. In these studies, people who ate lots of ultra-processed food were usually in worse health—not much worse, as in the case of smoking, but somewhat worse. That could be interpreted to mean that ultra-processed foods cause health problems, but there are other factors, or confounders, that could also explain the correlation. People who eat lots of processed food might have unhealthier lifestyles overall, which could explain why they have worse outcomes. People who listen to public health advice about eating fresh foods might also choose to walk up stairs rather than use the elevator, an increase in physical activity that might well not show up in research surveys. Researchers try to correct for these confounders, but different categories of people are too complicated to be perfectly statistically measured and compared.

[.my2]
但这种回顾性研究, 有一个众所周知的关键局限性：**"相关性"并不能证明"因果关系"。**在这些研究中，食用大量超加工食品的人通常健康状况更差——并不像吸烟那样差多少，但有些更差。这可以解释为超加工食品会导致健康问题，**但还有其他因素或混杂因素(即第三方变量), 也可以解释这种"相关性"。**吃大量加工食品的人, 总体上可能有不健康的生活方式，这可以解释为什么他们的结果更糟糕。听取关于吃新鲜食物的公共卫生建议的人, 也可能会选择走楼梯, 而不是使用电梯，但这种体力活动的增加, 很可能不会出现在研究调查中。研究人员试图纠正这些混杂因素，但不同类别的人太复杂，无法进行完美的统计测量和比较。



Observational studies are also prone to an issue called reverse causality: Did diet soda make people gain weight, or did overweight people who wanted to shed some pounds start drinking diet soda? What’s more, there are major questions about how well people remember what they eat and therefore how accurately they can report it in observational studies.

[.my2]
观察性研究也容易出现一个称为反向因果关系的问题：无糖汽水是否会使人体重增加，或者想要减肥的超重人是否开始喝无糖汽水？更重要的是，人们对自己吃的东西的记忆力如何，以及他们在观察性研究中报告的准确性如何，还存在一些重大问题。


Some researchers have tried to get a better look at ultra-processed foods by running prospective studies, meaning that they gather a group of subjects, monitor their eating habits and lifestyles for some period, and compare their diets with their health outcomes, trying to correct for other factors besides diet. A 2019 French study that followed people for about seven years found that those who ate more ultra-processed food had a higher risk of mortality. For each 10% increase in the amount of UPF eaten, there was a 14% increase in the number of deaths, about half of which came from cancer and cardiovascular disease. A study of Spanish university students in the same year found that people who ate the most ultra-processed food were one-third more likely to develop depression over 10 years than people who ate the least.

[.my2]
一些研究人员试图通过进行"前瞻性研究", 来更好地了解"超加工食品"，这意味着他们收集了一组受试者，在一段时间内监测他们的饮食习惯和生活方式，并将他们的饮食, 与健康结果进行比较，试图纠正除了饮食之外的其他因素。 2019 年法国的一项研究, 对人们进行了约七年的跟踪发现，食用更多超加工食品的人, 死亡风险更高。 UPF摄入量每增加10%，死亡人数就会增加14%，其中约一半来自"癌症"和"心血管疾病"。同年对西班牙大学生的一项研究发现，食用超加工食品最多的人, 在 10 年内患"抑郁症"的可能性, 比食用最少的人高三分之一。



Prospective studies can show how people change over time and help reduce the problems of reverse causality and poorly measured diets, but they don’t eliminate the core entanglement: People who follow the well-known advice to eat fresh foods are likely different in many complicated ways from those who hit the drive-thru.
 The great majority of the evidence against ultra-processed food is of a circumstantial variety.

[.my2]
前瞻性研究可以揭示人们如何随着时间的推移而发生变化，并有助于减少反向因果关系和饮食测量不当的问题，但它们并不能消除核心纠葛：那些听从众所周知的建议, 吃新鲜食物的人, 可能在许多复杂的方面, 与那些去汽车餐厅吃饭的人不同。绝大多数反对超加工食品的证据都是间接的。


In 2019, NIH researcher Kevin Hall and a group of colleagues published a paper based on an experiment in which they kept 20 subjects in a hospital setting, giving half of them a UPF-heavy diet for two weeks followed by a diet based on minimal processing for two weeks, allowing them to eat as much food as they wanted at each meal. The other half had the diet with minimal processing first.

The researchers carefully arranged the two diets to be equivalent in terms of nutrients, energy density fiber and other attributes; they differed only in the percentage of processing. While subjects were on the ultra-processed food diet, they ate about 500 more calories per day, and in just two weeks they gained 2 pounds. During the time they ate fresh foods, they lost 2 pounds. Finally, there was direct evidence that ultra-processed foods could push people toward obesity.

[.my2]
2019 年，NIH 研究员 Kevin Hall 和一群同事, 发表了一篇基于一项实验的论文，其中他们将 20 名受试者, 留在医院环境中，让其中一半人接受为期两周的高 UPF 饮食，然后进行基于最低限度加工的饮食, 持续两周，让他们每餐, 想吃多少就吃多少。另一半则首先进行最少加工的饮食。 +
研究人员精心安排了两种饮食，使其在营养成分、能量密度纤维, 和其他属性方面相当；它们的区别仅在于处理的百分比。当受试者采用超加工食品饮食时，他们每天多摄入约 500 卡路里热量，并且在短短两周内, 体重增加了 2 磅。在吃新鲜食物期间，他们体重减轻了 2 磅。最后，有"直接证据"表明, 超加工食品可能会导致人们肥胖。

One paper, however, does not settle a complicated field. “It’s a very well-conducted study,” says Kuhnle. “But like all studies, there are limitations." For instance, the ultra-processed foods in the study didn’t have much fiber, so the researchers also gave people fiber supplements dissolved in water, but that may not be equivalent to eating fiber. Moreover, no single, small experiment could ever settle such a big nutritional question. “I’ve done studies of flavonols (compounds found in fruit, but also used in processing) with 20 or 50 people," Kuhnle says. “The response was always, ‘That’s a single study.’ We need more studies to understand this.”

[.my2]
然而，一篇论文并不能解决一个复杂的领域。 “这是一项进行得非常好的研究，”库恩勒说。 “但像所有研究一样，也存在局限性。”例如，研究中的超加工食品没有太多纤维，因此研究人员还给人们提供了溶解在水中的"纤维补充剂"，但这可能并不等同于吃"纤维". 此外，*任何单一的小型实验, 都无法解决如此大的营养问题*，“我对 20 或 50 人进行了黄酮醇（在水果中发现的化合物，但也用于加工）的研究。” “反应总是，​​‘这只是一项研究。’我们需要更多的研究来理解这一点。”


Hall readily acknowledges that this single, small study doesn’t provide a final verdict on ultra-processed food, partly because it didn’t represent real life. “It’s a very artificial environment, where we can completely take control over their food,” he says. He also points out that we can’t extrapolate life-long effects based on two weeks of data. “Of course, that (level of overeating) wouldn’t last forever,” he says.

[.my2]
霍尔欣然承认，这项单一的小型研究, 并没有对超加工食品提供最终结论，部分原因是它并不代表现实生活。 “这是一个非常人工的环境，我们可以完全控制他们的食物，”他说。他还指出，我们无法根据两周的数据推断出终生影响。 “当然，这种（暴饮暴食的程度）不会永远持续下去，”他说。

Another challenge is that not all ultra-processed foods are alike. In many cases, they are not more energy-dense than whole foods.

[.my2]
另一个挑战是, 并非所有的超加工食品都是一样的。在许多情况下，它们的能量密度并不比天然食品更高。


The research on ultra-processed food is picking up on something important, but it’s not clear that the category called “ultra-processed food” brings us closer to understanding the problem or ameliorating it. Some of those highly processed foods, such as sugary drinks and processed meats, can degrade health—but we’ve known that for years, through other nutrition research. Most people have gotten the message that they should be eating healthier fresh foods that they prepared themselves, rather than unnatural stuff that comes out of a sealed bag bearing a long list of unpronounceable ingredients. To little avail.

[.my2]
对超加工食品的研究正在发现一些重要的东西，但尚不清楚“超加工食品”这一类别, 是否能让我们更接近地理解问题或改善问题。其中一些高度加工的食品，如**含糖饮料和加工肉类，**可能**会降低健康**——但我们多年来通过其他营养研究已经知道这一点。**大多数人都得到这样的信息：他们应该吃自己准备的更健康的新鲜食物，而不是从密封袋中取出的不自然的东西，里面含有一长串难以发音的成分。**收效甚微。


我们已经掌握了一些关于哪些食物特别糟糕的证据，进一步的研究将告诉我们更多信息。我们现在的主要目标是弄清楚如何让人们更容易选择更健康的选择并避免真正的垃圾，无论我们是否称之为“超加工”，这个挑战都是一样的。更好的加工食品可以而且应该在替代危险食品方面发挥关键作用。“我认为市场上可能已经有大量健康的超加工食品，”霍尔说。 “我们应该制造更多这样的产品，并增加它们的可用性。”



'''


== (pure) Are Ultra-Processed Foods Really all that Unhealthy?



'''
