
= 0144. Why Kate Middleton and Other Cancer Patients Require More Than One Treatment 为什么凯特·米德尔顿和其他癌症患者需要不止一种治疗
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../myAdocCss.css


'''

== Why Kate Middleton and Other Cancer Patients Require More Than One Treatment  为什么凯特·米德尔顿和其他癌症患者需要不止一种治疗

WHY ARE SOME CANCERS TREATED WITH SURGERY BUT NOT OTHERS?

[.my2]
为什么有些癌症可以通过手术治疗，而其他癌症则不能？


There are many types of cancer treatment, including surgery, chemotherapy, radiotherapy, immunotherapy and hormonal therapy, among others. Sometimes doctors combine multiple types of treatment. Which is the best treatment approach depends on which organ the tumor originated from and how much the tumor has spread at the time of diagnosis.

[.my2]
癌症治疗有多种类型，包括手术、化疗、放疗、免疫疗法, 和激素疗法等。有时医生会结合多种治疗方法。哪种治疗方法最好, 取决于肿瘤起源于哪个器官, 以及诊断时肿瘤扩散的程度。


Broadly speaking, there are two types of cancers: solid tumors – or visible tumors that can be seen by the naked eye or through imaging – and liquid tumors, such as blood cancers. The primary treatment for solid cancers is surgery to physically remove the tumor, with the goal of getting rid of all tissues involved with the tumor.

[.my2]
**从广义上讲，有两种类型的癌症："实体瘤"（或肉眼或通过成像可以看到的可见肿瘤）, 和"液体肿瘤"，例如血癌。**实体癌的主要治疗方法, 是通过手术物理切除肿瘤，目的是清除与肿瘤相关的所有组织。

For example, in ovarian cancer, surgery often includes removing the ovaries, fallopian tubes and the uterus, along with any visible cancer tissue in the rest of the belly. Sometimes this requires removing the spleen or part of the small intestine or liver.

[.my2]
例如，对于卵巢癌，手术通常包括切除卵巢、输卵管和子宫，以及腹部其余部分任何可见的癌组织。有时这需要切除脾脏, 或部分小肠或肝脏。

For skin cancers such as melanoma, surgery involves removing both the tumor and a good margin of normal-looking skin with it to capture any remaining cancer cells that may not be visible in the surrounding healthy skin. Likewise, a surgeon may also remove nearby lymph nodes.

[.my2]
对于"黑色素瘤"等皮肤癌，手术需要切除肿瘤和正常皮肤的良好边缘，以捕获周围健康皮肤中可能不可见的任何剩余癌细胞。同样，外科医生也可能切除附近的淋巴结。

When solid cancer is diagnosed early, the success of treatment following surgery is typically high. For example, an estimated 91% of cervical cancerpatients who are diagnosed early are still alive at least five years after diagnosis. Endometrial cancer patients who are diagnosed early have an estimated five-year survival rate of 95%.

[.my2]
**当"实体癌"被早期诊断出来时，手术后治疗的成功率通常很高。**例如，据估计，早期诊断出的宫颈癌患者中, 有 91% 在诊断后至少五年内仍存活。早期诊断的"子宫内膜癌"患者的五年生存率, 估计为 95%。


WHY DO SOME CANCERS RECUR?

[.my2]
为什么有些癌症会复发？

Despite surgical removal, many tumors come back. Researchers don’t fully understand why cancers recur, but there are certain red flagsthat indicate the potential for recurrence.

[.my2]
尽管手术切除，许多肿瘤还是会复发。研究人员并不完全了解癌症复发的原因，但**有一些危险信号表明癌症有可能复发。**

One is how different the cancer cells look compared with healthy cells. The more different, the more aggressive the tumor. When a tumor is more aggressive, it’s more likely to invade neighboring tissues and spread to other parts of the body.

[.my2]
*一是"癌细胞"与"健康细胞"相比有何不同。差异越多，肿瘤就越具有侵袭性。当肿瘤更具侵袭性时，它更有可能侵入邻近组织, 并扩散到身体的其他部位。*

Another is the extent the cancer has spread at the time of diagnosis. This is what determines the stage of the cancer. For example, stage 1 cancer refers to a tumor that is confined to the organ it originally developed from. Stage 4 cancer refers to a tumor that has spread far from its origins to grow on other organs. The higher the stage, the higher the risk for a worse outcome.

[.my2]
*另一个是诊断时"癌症扩散"的程度。这决定了癌症的阶段。例如，第一阶段癌症, 是指仅限于其最初发展的器官的肿瘤。第四阶段癌症, 是指肿瘤已经远离其起源, 并在其他器官上生长。阶段越高，出现更糟糕结果的风险就越高。*

A third factor is the organ where the cancer first originated. For instance, pancreatic cancers tend to be fatal even when diagnosed early because these tumors don’t respond well to therapy. Ovarian cancer can have symptoms that are difficult to recognize, leading to late diagnoses. On the other hand, breast cancer and thyroid cancer tend to be less aggressive for longer periods of time, even when diagnosed at an advanced stage.

[.my2]
第三个因素是癌症最初起源的器官。例如，*即使早期诊断出来，"胰腺癌"也往往是致命的，因为这些肿瘤对治疗的反应不佳。"卵巢癌"可能有难以识别的症状，导致晚期诊断。另一方面，"乳腺癌"和"甲状腺癌"在较长时间内往往侵袭性较低，即使是在晚期诊断时也是如此。*

WHAT IS ADJUVANT AND NEOADJUVANT THERAPY?

[.my2]
什么是辅助治疗和新辅助治疗？


For patients with tumors that can be surgically removed, they often also receive chemotherapy or radiotherapy before or after the procedure. Doctors prescribe this additional, or adjuvant, treatment depending on the patient’s risk of recurrence.

[.my2]
**对于可以手术切除的肿瘤的患者，他们通常还会在手术前或手术后, 接受化疗或放疗。**医生根据患者的复发风险, 开出这种额外的或辅助治疗。

Recurrence typically happens when cancer cells escape from the tumor prior to or during surgical removal. Adjuvant chemotherapy or radiation after the procedure is aimed at killing these cells so they don’t settle down and grow somewhere else in the body later on.

[.my2]
*当癌细胞在手术切除之前或期间, 从肿瘤中逸出时，通常会发生复发。手术后的辅助化疗或放疗旨在杀死这些细胞，这样它们就不会在体内的其他地方定居并生长。*

In some cases, surgical removal is not feasible or not advisable. This could be because the cancer has spread so much that completely cutting it out is impossible or the risk of complications or disability from the surgery is high.

[.my2]
*在某些情况下，手术切除是不可行或不建议的。这可能是因为癌症已经扩散得太多，以至于不可能完全切除它，或者手术引起并发症, 或残疾的风险很高。*

For example, primary surgery often isn’t a good option for ovarian cancer, since most patients are diagnosed in advanced stages; complete surgical removal, even if possible, may involve removing important organs such as the rectum and colon. This can lead to the need for a colostomy or ileostomy, where stool is passed directly from the large or small intestine to a bag outside the belly. Surgical removal of breast cancer may mean losing the affected breast.

[.my2]
例如，*对于卵巢癌，初次手术通常不是一个好的选择，因为大多数患者在诊断时已处于晚期。即使可能，完全手术切除也可能涉及切除"直肠"和"结肠"等重要器官。这可能导致需要进行"结肠造口术"或"回肠造口术"，将粪便直接从大肠或小肠, 转移到腹部外的袋子中。手术切除"乳腺癌"可能意味着失去受影响的乳房。*

The risk of unwanted side effects from surgical removal can be reduced through neoadjuvant therapy, or administering chemotherapy or radiation before the procedure to shrink the tumor and reduce the amount of surgery required. Studies have shown that neoadjuvant therapy can help ovarian cancerpatients avoid colostomies after surgery and allow breast cancerpatients to opt for a procedure that conserves their breast.

[.my2]
通过新辅助治疗，或**在手术前进行化疗或放疗, 以缩小肿瘤并减少所需的手术量，可以降低手术切除产生不良副作用的风险。**研究表明，新辅助治疗可以帮助"卵巢癌"患者避免术后"结肠造口术"，并允许"乳腺癌"患者选择保留乳房的手术。

Neoadjuvant or adjuvant treatment can include chemotherapy, immunotherapy, hormonal therapy, radiation therapy or a combination of these treatments.

[.my2]
新辅助或辅助治疗, 可包括化疗、免疫治疗、激素治疗、放射治疗或这些治疗的组合。




'''

== (pure) Why Kate Middleton and Other Cancer Patients Require More Than One Treatment


WHY ARE SOME CANCERS TREATED WITH SURGERY BUT NOT OTHERS?



There are many types of cancer treatment, including surgery, chemotherapy, radiotherapy, immunotherapy and hormonal therapy, among others. Sometimes doctors combine multiple types of treatment. Which is the best treatment approach depends on which organ the tumor originated from and how much the tumor has spread at the time of diagnosis.



Broadly speaking, there are two types of cancers: solid tumors – or visible tumors that can be seen by the naked eye or through imaging – and liquid tumors, such as blood cancers. The primary treatment for solid cancers is surgery to physically remove the tumor, with the goal of getting rid of all tissues involved with the tumor.


For example, in ovarian cancer, surgery often includes removing the ovaries, fallopian tubes and the uterus, along with any visible cancer tissue in the rest of the belly. Sometimes this requires removing the spleen or part of the small intestine or liver.


For skin cancers such as melanoma, surgery involves removing both the tumor and a good margin of normal-looking skin with it to capture any remaining cancer cells that may not be visible in the surrounding healthy skin. Likewise, a surgeon may also remove nearby lymph nodes.


When solid cancer is diagnosed early, the success of treatment following surgery is typically high. For example, an estimated 91% of cervical cancerpatients who are diagnosed early are still alive at least five years after diagnosis. Endometrial cancer patients who are diagnosed early have an estimated five-year survival rate of 95%.



WHY DO SOME CANCERS RECUR?


Despite surgical removal, many tumors come back. Researchers don’t fully understand why cancers recur, but there are certain red flagsthat indicate the potential for recurrence.


One is how different the cancer cells look compared with healthy cells. The more different, the more aggressive the tumor. When a tumor is more aggressive, it’s more likely to invade neighboring tissues and spread to other parts of the body.


Another is the extent the cancer has spread at the time of diagnosis. This is what determines the stage of the cancer. For example, stage 1 cancer refers to a tumor that is confined to the organ it originally developed from. Stage 4 cancer refers to a tumor that has spread far from its origins to grow on other organs. The higher the stage, the higher the risk for a worse outcome.


A third factor is the organ where the cancer first originated. For instance, pancreatic cancers tend to be fatal even when diagnosed early because these tumors don’t respond well to therapy. Ovarian cancer can have symptoms that are difficult to recognize, leading to late diagnoses. On the other hand, breast cancer and thyroid cancer tend to be less aggressive for longer periods of time, even when diagnosed at an advanced stage.


WHAT IS ADJUVANT AND NEOADJUVANT THERAPY?


For patients with tumors that can be surgically removed, they often also receive chemotherapy or radiotherapy before or after the procedure. Doctors prescribe this additional, or adjuvant, treatment depending on the patient’s risk of recurrence.


Recurrence typically happens when cancer cells escape from the tumor prior to or during surgical removal. Adjuvant chemotherapy or radiation after the procedure is aimed at killing these cells so they don’t settle down and grow somewhere else in the body later on.


In some cases, surgical removal is not feasible or not advisable. This could be because the cancer has spread so much that completely cutting it out is impossible or the risk of complications or disability from the surgery is high.


For example, primary surgery often isn’t a good option for ovarian cancer, since most patients are diagnosed in advanced stages; complete surgical removal, even if possible, may involve removing important organs such as the rectum and colon. This can lead to the need for a colostomy or ileostomy, where stool is passed directly from the large or small intestine to a bag outside the belly. Surgical removal of breast cancer may mean losing the affected breast.


The risk of unwanted side effects from surgical removal can be reduced through neoadjuvant therapy, or administering chemotherapy or radiation before the procedure to shrink the tumor and reduce the amount of surgery required. Studies have shown that neoadjuvant therapy can help ovarian cancerpatients avoid colostomies after surgery and allow breast cancerpatients to opt for a procedure that conserves their breast.

Neoadjuvant or adjuvant treatment can include chemotherapy, immunotherapy, hormonal therapy, radiation therapy or a combination of these treatments.

'''