= 1063
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,063 – Preparing for a New Baby.
This is English as a Second Language Podcast episode 1,063. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast Store, which has some additional courses in Business and Daily English just for you.
This episode is a dialogue between Wanda and Enrique about someone who is expecting a new baby – a mother who is about to give birth to a new baby. Let’s get started.
[start of dialogue]
Wanda: Oh hi, I wasn’t expecting you today.
Enrique: We’ve been cleaning out our garage, and your sister said I should come by with a few things for your baby.
Wanda: That’s really sweet of you guys, but I’m not due for another six months.
Enrique: But you’ll need these things to get the baby’s room ready, right?
Wanda: Well, we don’t actually have a baby room set up yet.
Enrique: There’s no time like the present. Here’s a crib and the mattress. It just needs to be assembled. Oh, here are some bumper pads that go with it.
Wanda: Great.
Enrique: Here’s a changing table.
Wanda: Wow, that’s really big.
Enrique: Here are two car seats, one for infants and one for toddlers, and here’s a booster seat.
Wanda: That’s a lot of stuff. Are you sure you want to part with all this?
Enrique: Positive. Here’s a basic baby monitor and a video monitor so you can keep tabs on the little one.
Wanda: Whoa, what’s in all these bags?
Enrique: They’re baby and kids clothes. You’ll need more than you think.
Wanda: That’s really generous of both of you, but are you sure you want to give it all to me?
Enrique: Of course, you’re family and this will help you save a lot of money.
Wanda: And it’ll free up garage space for your new workshop?
Enrique: Well, why not kill two birds with one stone?
[end of dialogue]
Wanda begins our dialogue by saying to Enrique, “Oh hi, I wasn’t expecting you today” – I didn’t think you were coming today. Enrique says, “We’ve been cleaning out our garage, and your sister said I should come by with a few things for your baby.” “To clean out” means to clean completely or thoroughly. A “garage” is a place where you normally store your car, although many people use it to store other things, and that’s the case with Enrique and his wife. They have cleaned out their garage and are bringing some things for Wanda.
Wanda says, “That’s really sweet of you guys.” The word “sweet” here means nice or kind. “But,” Wanda continues, “I’m not due for another six months.” When we talk about when a mother is “due” (due), we mean when she expects to give birth to the baby. Enrique says, “But you’ll need these things to get the baby’s room ready, right?” Enrique is saying well, yes it’s six months, but you still need to get the room where the baby will be staying prepared and ready.
Wanda says, “Well, we don’t actually have a baby room set up yet.” “To set up” means to prepare, usually involving perhaps moving furniture around, in this case, or perhaps putting a place for the baby to sleep. That would be “setting up” a baby room. Enrique says, “There’s no time like the present.” This is an old expression – a cliché, really. “No time like the present” (present). It means that you should take advantage of an opportunity to do something immediately, right away, without waiting.
Enrique says, “Here’s a crib and the mattress.” A “crib” (crib) is a special place where babies sleep. It’s a bed that has high sides to it, almost like walls, that prevent the baby from falling out. A “mattress” (mattress) is a soft, comfortable surface that you sleep on. Enrique says to Wanda, “Here’s a crib and the mattress,” meaning the mattress that goes with the crib or inside of the crib.
He says, “It just needs to be assembled.” “To assemble” (assemble) means to put something together, especially when there are a lot of small parts. Many people buy furniture at a store such as IKEA, and when they bring it home, they have to assemble the furniture. This of course is sometimes almost impossible, in the same way that assembling children’s toys is sometimes impossible. But we hope it won’t be impossible for Wanda to assemble this crib.
Enrique continues, “Oh, here are some bumper pads that go with it.” “Bumper (bumper) pads (pads)” are cushions – soft material – that are placed against the walls of the cribs so that the baby doesn’t hit his or her head against the side of the crib. It’s sort of like a mattress, but it’s vertical so the baby doesn’t hit his or her head against the side of the crib and hurt him or herself.
Wanda says, “Great.” She means, “That’s wonderful. I’m very happy.” Enrique then says, “Here’s a changing table.” A “changing table” would be a special table that you use, on which you put the baby when you are changing the baby’s clothes – in particular changing the baby’s diapers, which is the part of the clothes the baby wears around its middle, because of course babies don’t get up and use the bathroom the way the rest of us do. I wish they did.
Wanda says, “Wow, that’s really big.” She’s referring to the changing table. Enrique, however, just continues on giving her things. He says, “Here are two car seats, one for infants and one for toddlers, and here’s a booster seat.” A “car seat” is a general term used to describe a special chair that you use in a car, into which you put a baby or young child.
In the United States – in most states, perhaps in all states – you must put a baby or a small child in a car seat. You can’t just hold the baby in your arms, for example. That’s against the law. The idea is, of course, to protect the baby or the small child should there be an accident. There are two kinds of car seats mentioned here. One is for “infants” (infants) and one is for “toddlers” (toddlers). An “infant” is a small baby, a very young baby. A “toddler” is a young child, usually one who has already learned how to walk. Those are the most dangerous kind.
So, there are car seats for infants. There are bigger car seats for toddlers. Enrique also gives Wanda a “booster (booster) seat.” A booster seat is a special seat – or small chair, I guess you could think of it as – that is used to keep a child, an older child, safe in a car by lifting his or her body high enough so that the seat belt crosses the body at the appropriate height. A “seat belt” is a special piece of material, a strap, that you put over your body to prevent your body from being thrown out of the car in case of an accident.
So, for older children who are too old for a car seat, there are booster seats that the older children can have underneath them. Wanda says, “That’s a lot of stuff” – that’s a lot of things. “Are you sure you want to part with all of this?” “To part with” something is a two-word phrasal verb meaning to get rid of something, to give something away, especially something that might have some sort of emotional or sentimental value, something that you like a lot.
Wanda asks Enrique if he’s sure that he wants to part with all of these things. Some parents, for example, like to keep all of the things that they used for their baby for many years. My mother never did that. There was always another baby that needed to use it. Although, I was the youngest, so I guess she got rid of it after me. Enrique says, “Positive,” meaning yes, he’s absolutely sure he wants to part with this stuff.
He continues, “Here’s a basic baby monitor and a video monitor so you can keep tabs on the little one.” A “baby monitor” is a small electronic device, one part of which is in the room where the baby is sleeping and the other is usually in the parents’ bedroom. You can hear the baby, so if the baby makes noise or wakes up, you can hear it on the baby monitor. It’s like a little radio between one room of the house and another room of the house, or that connects the two rooms together.
A “video monitor” would be the same sort of thing except it’s actually a video camera, and you can look and see your baby from another room. You use these “to keep tabs on” your baby. “To keep tabs (tabs) on” someone is to monitor someone or, we might say, to keep track of someone – to get information on someone so you know how he or she is doing. Wanda says, “Whoa, what’s in all these bags?” Enrique says, “They’re baby and kids clothes.” You’ll need more than you think.
Wanda says, “That’s really generous of both of you, but are you sure you want to give it all to me?” Enrique says, “Of course, you’re family,” meaning you’re part of our family (I’m guessing that Enrique is married to Wanda’s sister here). He says, “This will help you save a lot of money.” But Wanda sees that there’s another reason that Enrique is giving her all of these things, and she tells us at the end of the dialogue. She says, “And it will free up garage space for your new workshop?”
“To free up” is a two-word phrasal verb meaning to make something available, especially space or time. You can talk about “freeing up your schedule,” meaning canceling some of your appointments or arranging things so that you have time to do something special. A “workshop” (workshop) is a room or an area in a room where you build or fix things. Some people have a “wood workshop” in their garage where they cut wood and do things with wood. I don’t have any of these sorts of things in my house.
Enrique says, “Well, why not kill two birds with one stone?” Enrique is saying yes, I am also trying to make room for my workshop, and that’s why I’m giving you all of this stuff. He uses an old expression, “to kill two birds with one stone.” This means to solve two problems at once, with one action. If you can imagine a stone, a small rock, being thrown up into the air and killing not just one bird but two birds, then you get the idea that you can use one action in order to accomplish two different things or to achieve two different purposes.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Wanda: Oh hi, I wasn’t expecting you today.
Enrique: We’ve been cleaning out our garage, and your sister said I should come by with a few things for your baby.
Wanda: That’s really sweet of you guys, but I’m not due for another six months.
Enrique: But you’ll need these things to get the baby’s room ready, right?
Wanda: Well, we don’t actually have a baby room set up yet.
Enrique: There’s no time like the present. Here’s a crib and the mattress. It just needs to be assembled. Oh, here are some bumper pads that go with it.
Wanda: Great.
Enrique: Here’s a changing table.
Wanda: Wow, that’s really big.
Enrique: Here are two car seats, one for infants and one for toddlers, and here’s a booster seat.
Wanda: That’s a lot of stuff. Are you sure you want to part with all this?
Enrique: Positive. Here’s a basic baby monitor and a video monitor so you can keep tabs on the little one.
Wanda: Whoa, what’s in all these bags?
Enrique: They’re baby and kids clothes. You’ll need more than you think.
Wanda: That’s really generous of both of you, but are you sure you want to give it all to me?
Enrique: Of course, you’re family and this will help you save a lot of money.
Wanda: And it’ll free up garage space for your new workshop?
Enrique: Well, why not kill two birds with one stone?
[end of dialogue]
Listening to the scripts by our wonderful scriptwriter, Dr. Lucy Tse, kills two birds with one stone: you get to enjoy the dialogue and improve your English all at once.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
due – expecting to give birth to a baby on a particular date or during a particular week
* Did you hear that Yolanda is pregnant? She’s due in mid-April.
no time like the present – a phrase meaning that one should take advantage of an opportunity to do something right away, without waiting or delaying
* Why aren’t you studying? There’s no time like the present to start preparing for the final exam.
crib – a small bed with high walls, used to protect babies from falling as they sleep
* They bought a beautiful crib, but the baby refuses to sleep in it, so they’re all sleeping in the parents’ bed together.
mattress – the soft, comfortable surface that people sleep on in a bed
* Do you need a full-size mattress or a queen-size mattress to fit the bed frame?
to assemble – to put something together, especially when there are many small parts
* How long did it take you to assemble the kids’ swing set?
bumper pad – soft fabric or cushions that are placed against the walls of a crib so that a baby or young child does not hit his/her head against the wood
* Make sure you buy a bumper pad that has small holes, so that Chelsea will be able to breathe even if her nose and mouth are pressed against it.
changing table – a raised, flat surface that a baby lies down on while someone is changing his or her diaper
* Please wipe the changing table with disinfectant before and after changing the baby’s diaper.
car seat – a special chair designed to keep a baby or child safe in the car in case of an accident
* Can you help me install this car seat in the backseat of my car?
infant – a very young baby; newborn
* The hospital encourages new mothers to feed their infants breast milk.
toddler – a child who is learning to walk
* Why would you take a toddler on a three-mile hike? That’s too far for someone who’s just learning how to walk.
booster seat – a special seat designed to keep an older child safe in the car by lifting his or her body up higher so that the seat belt crosses the body at the appropriate height
* Without a booster seat, the seat belt would come across the little girl’s neck instead of her chest.
to part with – to get rid of something, especially something that has a lot of sentimental or emotional value
* Even though Grandpa died 20 years ago, we still can’t part with his stamp collection.
baby monitor – an electronic device with two parts, one where the baby is and one where the parent is, that allows the parent to hear all the noises in the baby’s room
* Heather often works in the garden while her son is sleeping, but she takes the baby monitor with her so she can hear if he wakes up.
video monitor – a baby monitor that allows the parent to see and hear the baby
* Some new parents are so worried about their baby that they use a video monitor so that they can watch the baby whenever they wake up at night.
to keep tabs on – to keep track of someone or something; to know the status of something; to know where something is, what it is doing, and how well or quickly it is progressing
* Janelle supervises 16 employees. How is she able to keep tabs on all of them?
to free up – to make something available, especially referring to time, space, or money
* Once Dani starts kindergarten, not having to pay for preschool will free up a lot of cash for our other expenses.
workshop – a room or area where one creates, builds, or fixes things
* Did you make all this furniture in your workshop?
to kill two birds with one stone – to solve two problems or address two purposes at once or with a single action
* If we drop off this paperwork when we go to the meeting, we’ll be able to kill two birds with one stone.
Comprehension Questions
2. What does Enrique mean when he says, “There’s no time like the present”?
a) He wants to do something right away.
b) He can’t wait to give Wanda her present.
c) He is going to keep his visit very short.
2. What is a baby supposed to sleep on?
a) A crib
b) A changing table
c) A car seat
Answers at bottom.
What Else Does It Mean?
to part with
The phrase “to part with,” in this podcast, means to get rid of something, especially something that has a lot of sentimental or emotional value: “You haven’t opened these textbooks since your college graduation more than 10 years ago. Don’t you think it’s time to part with them?” The phrase “to be parted” means to be physically separated from another person: “Jane has never been parted from her children for more than a few hours.” As a verb, “to part” means to arrange one’s hair so that it falls to two sides, leaving a line of skin showing: “Do you like to part your hair on the left or on the right?” Finally, “to part” can mean to separate two things, leaving space between them: “The actor parted the stage curtains and stood in front of the audience.”
to free up
In this podcast, the phrase “to free up” means to make something available, especially referring to time, space, or money: “Can you free up a half-hour for a meeting on Wednesday?” The phrase “free fall” describes falling through the sky from a high distance without a motor, wings, or anything to slow one down: “Sky jumpers enjoy free fall for about 60 seconds before they open their parachute.” The phrase “free will” describes the ability to make one’s own decisions, without having one’s decisions be predetermined by God: “Why did God let humans have free will if he knew they would make bad decisions?” Finally, the phrase “free verse” describes poetry that does not rhyme: “As a teenager, Steve liked poetry that rhymed, but now he prefers free verse.”
Culture Note
Baby Showers
A “baby shower” is a party “thrown” (organized and held) “in anticipation of” (while waiting for something to happen) the birth of a baby. The baby shower is usually “arranged” (organized) and hosted by a close friend of the “mother-to-be” (a woman who is pregnant) a few weeks before the “due date” (the day when the baby’s birth is expected).
Traditionally, only women attend baby showers, although this is changing. The women may be the friends, family members, and co-workers of the “guest of honor” (the person who is the reason for the party). They all bring gifts for the baby, such as baby clothing, toys, and diapers, or they might “chip in” (contribute to the cost by paying a small amount of money) to buy a larger item, like a crib or “stroller” (a basket that serves as a bed and/or chair for the baby, with wheels so that the mother can push it while walking).
Traditionally, the room is usually decorated with “pastel” (light colors) baby colors—pink for a girl and blue for a boy if the “gender” (sex) is known, or yellow and green if the gender is unknown. The guests “ooh and ahh” (make sounds of appreciation) while the woman is opens the gifts. They also play “baby shower games,” like guessing the date of the baby’s birth, competing to see who can change the diaper on doll most quickly, or trying to identify the taste of baby foods. And the guests also eat “finger foods” (small foods that can be eaten with one’s hands, without silverware) and cake.
Comprehension Answers
1 - a
2 - a