= 1074
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,074 – Becoming a Vegetarian.
This is English as a Second Language Podcast episode 1,074. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com.
This episode is a dialogue between Ashley and Paul about people who don’t eat meat. Let’s get started.
[start of dialogue]
Ashley: I’m thinking of becoming a vegetarian. I think it would be the ethical thing to do.
Paul: Are you going to eat eggs and dairy? If you’re doing this for ethical reasons, you really should avoid anything made with animal products or animal by-products.
Ashley: I guess you’re right.
Paul: Then you’re going to be a vegan. You won’t be able to eat any milk, butter, cheese, or yogurt.
Ashley: Really? I guess I’ll have to be a vegan then.
Paul: You’ll have to eat a varied diet so you don’t have a vitamin deficiency.
Ashley: Yes, I’ll have to guard against that.
Paul: Are you going to avoid buying things that are animal-derived, too? Like leather shoes and belts?
Ashley: I hadn’t thought of that. I suppose I should.
Paul: Are you having second thoughts?
Ashley: No, I just didn’t know there would be so many restrictions.
Paul: Just be glad you didn’t choose to become a fruitarian.
Ashley: What’s that?
Paul: You don’t want to know.
[end of dialogue]
Our dialogue begins with Ashley saying to Paul, “I’m thinking of becoming a vegetarian.” A “vegetarian” (vegetarian) is a person who doesn’t eat meat, the meat of animals such as cows or pigs or chickens. A vegetarian might not eat meat for a variety of reasons. In the case of Ashley in our story, it’s because she thinks it is “the ethical thing to do.” “Ethical” (ethical) refers to something that is good – the right or correct thing to do in a situation, the moral thing to do. That’s what Ashley thinks being a vegetarian is all about – being ethical.
Paul says, “Are you going to eat eggs and dairy?” “Dairy” (dairy) is something that is related to milk – milk itself, or other things that are made from milk. Paul is asking Ashley if she is going to eat eggs and milk, since those things come from animals even though they are not animals themselves. Paul says, “If you’re doing this for ethical reasons, you should really avoid anything made with animal products or animal by-products.”
There are two terms here to explain. The first is “animal products.” A “product” is something that comes from something else, something that is produced. “Animal products” would be anything that is made from one or more parts of an animal. “Animal by-products” (by-products) are things that are made from animal parts, usually created as a consequence of making something else.
For example, chicken farmers mainly try to get eggs from chickens, or they kill the chicken in order to sell the meat of the chicken, but one of the by-products of having chickens is that chickens, like most of us, create a certain waste product. They – well, to put it in the terms of a young child, they “poop” (poop). “Poop” is what you do when you go to the bathroom – well, at least one of the things.
Anyway, I’m not sure how we got on this topic. Oh yes, animal by-products are things that animals produce or that you get from an animal in the process of doing something else or making something else. I think that would be the general idea. So, in the case of chicken poop, it would be perhaps to make fertilizer – something you would put on the ground so that you could grow food more easily.
Ashley says, “I guess you’re right,” meaning that she agrees with Paul that she should probably not eat eggs or dairy. Paul says, “Then you’re going to be a vegan” (vegan). A “vegan,” if I understand correctly, is a person who doesn’t eat any animal products. That means that vegans not only don’t eat meat, they don’t eat eggs or use any dairy products.
Paul says, “You won’t be able to eat any milk, butter, cheese, or yogurt.” “Butter,” you may know, is something that is made in part from cream and has typically a lot of fat in it. “Cheese” is a solid food made from milk. We use cheese in all sorts of cooking. Lots of Italian pasta dishes, for example, have cheese in them. Paul also talks about “yogurt” (yogurt). Yogurt is also made from milk, often something that is sweetened with fruit or sugar, especially the kind of yogurt you buy at the store that has flavors like strawberry.
Ashley says, “Really? I guess I’ll have to be a vegan then.” Paul continues; he says, “You’ll have to eat a varied diet so you don’t have a vitamin deficiency.” A “diet” refers to the kinds of food that you eat. “Varied” means that you need to eat different kinds of things, and the reason Paul is telling Ashley she needs to eat different kinds of food is to avoid a “vitamin (vitamin) deficiency (deficiency).”
A “deficiency” is when you don’t have enough of something. So, a vitamin deficiency is when you don’t have enough vitamins. “Vitamins” are usually classified by a letter – vitamin A, vitamin C, vitamin D. There various different kinds of vitamin B. Vitamins are necessary for health, and they can be found in many different kinds of food, depending on the vitamin.
Ashley says, “Yes, I’ll have to guard against that.” “To guard (guard) against” something is a two-word phrasal verb meaning to prevent something from happening, to protect yourself from something dangerous that might happen. You can guard against something physical like someone trying to hit you, but more often than not, we use the expression “to guard against” when we’re talking about things that we want to avoid doing – things that we want to prevent from happening.
Paul says, “Are you going to avoid buying things that are animal-derived too?” The word “derived” (derived) comes from the verb “to derive.” “To derive” means to get something from somewhere else. We could talk about words in English that are “derived” from words in Latin or in French or in German. Here, the expression in the dialogue is “animal-derived,” which would mean that it comes from, or is made from, animals.
Paul says, “Like leather shoes and belts?” “Leather” (leather) is a material made from the skin of an animal, usually a cow. Paul is telling Ashley that she’s going to have to stop buying leather shoes and belts. A “belt” (belt) is what goes around the top of your pants to keep them from falling down. Ashley says, “I hadn’t thought of that. I suppose I should,” meaning “I suppose I should avoid buying things that are animal derived also.”
Paul then asks, “Are you having second thoughts?” If someone asks you if you’re having second thoughts about something, it means that they are asking you if you are doubting your decision, if you are thinking about changing your mind, because maybe now when you think about it a little more, you think you might have made the wrong decision. That’s “’having second thoughts.”
If you ask a young woman to marry you and she goes home and comes back and tells you that she’s having second thoughts about actually getting married to you, that’s usually not a good sign. You probably want to find a new girlfriend. Anyway, Ashley says “No,” meaning no, I’m not having second thoughts. I’m not doubting my decision. “I just didn’t know there would be so many restrictions.” “Restrictions” are limits on what you can do – rules or regulations that prevent you from doing certain things.
Paul then says, “Just be glad you didn’t choose to become a fruitarian.” A “fruitarian” (fruitarian) is a person who eats mainly fruit, usually fruit that falls off from a plant or a tree and that can be taken without harming the plant or tree. So, it’s not just fruit that you might find on a tree. Usually fruitarians, if I understand correctly, will only eat fruit that has fallen off of a tree – naturally, if you will. Are there really fruitarians in the world? Well, Dr. Lucy Tse thinks so, because she put the word in our dialogue.
Ashley says, “What’s that?” She doesn’t know what a fruitarian is. Paul says, “You don’t want to know.” When you hear that expression, “You don’t want to know,” the person is indicating that this information that you don’t know might be information that you don’t really want to know, because it will confuse you or make you angry or perhaps make you sad. When someone says, “You don’t want to know,” they’re saying that the information that you are asking about is something that is going to hurt you or perhaps upset you.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Ashley: I’m thinking of becoming a vegetarian. I think it would be the ethical thing to do.
Paul: Are you going to eat eggs and dairy? If you’re doing this for ethical reasons, you really should avoid anything made with animal products or animal by-products.
Ashley: I guess you’re right.
Paul: Then you’re going to be a vegan. You won’t be able to eat any milk, butter, cheese, or yogurt.
Ashley: Really? I guess I’ll have to be a vegan then.
Paul: You’ll have to eat a varied diet so you don’t have a vitamin deficiency.
Ashley: Yes, I’ll have to guard against that.
Paul: Are you going to avoid buying things that are animal-derived, too? Like leather shoes and belts?
Ashley: I hadn’t thought of that. I suppose I should.
Paul: Are you having second thoughts?
Ashley: No, I just didn’t know there would be so many restrictions.
Paul: Just be glad you didn’t choose to become a fruitarian.
Ashley: What’s that?
Paul: You don’t want to know.
[end of dialogue]
Thanks to our wonderful scriptwriter, Dr. Lucy Tse, who is not a fruitarian.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
vegetarian – a person who does not eat meat, usually for religious, moral, or health reasons
* Melissa is a vegetarian, so she eats a lot of beans and lentils.
ethical – related to what is good, moral, and the right thing to do
* It isn’t ethical to change the results of your research just because your funder doesn’t like the findings.
dairy – related to or made from milk
* Lucas is allergic to milk, so he can’t eat ice cream, cheese, yogurt, or any other dairy products.
animal products – anything made from one or more parts of an animal
* Early settlers used animal products for food, clothing, shelter, and tools.
by-products – materials made from animal parts, usually created as an unintended consequence of another process
* Some farmers are using animal by-products to generate extra income. For example, some chicken farmers are selling chicken excrement to other farmers, who use it as fertilizer.
vegan – a person who does not eat any animal products, avoiding meat, eggs, and milk
* It’s really hard to cook for Eric, because he’s a vegan and can’t have any eggs or milk, even if they are just ingredients in bread.
butter – a pale yellow, high-fat spread made from mixing cream for a long time
* Would you like butter, jam, or cream cheese on your bagel?
cheese – a solid food made from milk, especially that has been aged (left to sit for a period of time)
* Do you prefer cheddar cheese or Swiss cheese on sandwiches?
yogurt – a thick, pudding-like food made from slightly sour, fermented milk, often flavored with fruit and sugar
* Jake often has yogurt and granola for breakfast.
vitamin deficiency – a medical condition of not having enough of a particular vitamin (nutrient) in one’s body, so that one begins to experience health problems
* Eating lots of fruits and vegetables can prevent vitamin deficiencies.
to guard against – to protect oneself from some danger; to prevent something bad from happening
* The store has installed video cameras to guard against theft.
animal-derived – made from animals
* Wool sweaters, suede belts, and leather jackets are examples of animal-derived clothing.
leather – a material made from the skin of an animal, usually a cow
* Do you have a leather wallet, or a cloth wallet?
to have second thoughts – to doubt one’s decision; to wonder whether one has made the right decision; to consider changing one’s mind
* Is it normal to have second thoughts on your wedding day?
restriction – a limit on what one can do; a limitation
* The government places many restrictions on stores that sell alcohol.
fruitarian – a person who eats mainly fruit, usually fruit that falls off a plant or tree or that can be taken from it without harming it
* Fruitarians have a really high-fiber diet, but I bet they miss salty flavors.
Comprehension Questions
1. Why is Ashley thinking of becoming a vegetarian?
a) Because it will be less expensive.
b) Because many of her friends are vegetarians.
c) Because she thinks it is wrong to eat animals.
2. What does Paul mean when he asks, “Are you having second thoughts?”
a) He wants to know if she is reconsidering her decision.
b) He wants to know if she has thought about this deeply.
c) He wants to know if she hears an echo.
Answers at bottom.
What Else Does It Mean?
cheese
The word “cheese,” in this podcast, means a solid food made from milk, especially one that has been aged (left to sit for a period of time): “Mozzarella, parmesan, and ricotta cheese are common in Italian cuisine.” The word “cheesy” means with a lot of cheese: “This pizza is really cheesy!” Informally, “cheesy” means insincere and unpleasant: “He nervously told cheesy jokes, trying to keep people entertained as they waited.” And “cheesy” can also describe something that has poor quality and is inexpensive: “Why did those actors agree to be part of such a cheesy film?” Finally, people often say the word “cheese” immediately before they are photographed, because it makes their mouth form a smile: “The photographer asked the children to look at the camera and say ‘cheese.’”
to guard against
In this podcast, the phrase “to guard against” means to protect oneself from some danger, or to prevent something bad from happening: “The best way to guard against the common cold is to wash your hands many times throughout the day.” The verb “to guard” means to watch over a person or place to protect it and keep it safe: “Someone is always guarding the President of the United States.” Or, “Could you please guard my laptop computer while I go to the restroom?” Finally, the verb “to guard” can also mean to monitor a prisoner so that he or she behaves well and does not escape: “The prisoners are allowed to go outside for one hour each day, but they are heavily guarded by prison staff.”
Culture Note
Types of Vegetarianism
There are many types of vegetarianism, and some are considered easier to “adopt” (make part of one’s lifestyle) than others. For example, a “pescatarian” is someone who eats fish, but not other types of meat. So a pescatarian can eat salmon, tuna, and possibly “shellfish” (ocean animals like shrimp, clams, and oysters), but not beef, pork, or chicken. Many people first become pescatarians as they slowly “transition” (change from one thing to another) into becoming vegetarians or vegans.
A “flexitarian” or a “semi-vegetarian” is someone who eats as a vegetarian most of the time, but “occasionally” (sometimes, but not often) eats meat.
A “lacto-ovo-vegetarian” is what most people think of when they hear the word “vegetarian”: someone who does not eat meat, but does eat eggs and dairy products. A “lacto-vegetarian” eats dairy products, but not meat or eggs. An “ovo-vegetarian” eats eggs, but not meat or dairy products.
As discussed in today’s episode, a “vegan” is someone who does not eat any milk, eggs, dairy products, or anything derived from dairy products, including “gelatin” (a substances that thickens foods like pudding, jams, and Jello-O), because it is made from animal “collagen” (a substance found in connective tissues).
Finally, a “raw vegan” or someone who follows a “raw food diet” is a person who eats only “raw” (uncooked) foods. Raw vegans believe that the process of cooking foods removes some or all of the nutrition, or may even harm the body.
Comprehension Answers
1 - c
2 - a