= 1077
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,077 – Buying Travel Insurance.
This is English as a Second Language Podcast episode 1,077. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California, of course.
Visit our website at ESLPod.com. Become a member of ESL Podcast. You can also buy some premium courses on our website by going to the ESL Podcast Store.
On this episode, we’re going to hear a dialogue between Josette and Tae-jin about buying insurance before you take a trip. Let’s get started.
[start of dialogue]
Josette: I admit it. I’m a nervous traveler and I don’t like traveling internationally.
Tae-jin: You could get travel insurance. Doing that would make you feel more secure, wouldn’t it?
Josette: Maybe. What types of coverage are available?
Tae-jin: You could get insurance to cover mishaps on the trip, such as cancelled flights or missed connections and having your luggage lost, stolen, or damaged. It’ll even cover your losses if your trip is cancelled.
Josette: I guess that would help, but I’m more nervous about something happening to me while I’m in another country.
Tae-jin: In that case, you can get medical insurance to cover the costs of medical emergencies, even if you have to be medically evacuated in the event of serious injuries or illness.
Josette: Oh, you’re right. I could get really sick or injured.
Tae-jin: And if things go terribly wrong, there’s even insurance for if you become disabled or if there’s an accidental death. They’ll pay for repatriation of your remains or overseas funeral services.
Josette: Disabilities and death? Is that supposed to put my mind at ease?
Tae-jin: The whole point is to make you less worried about bad things happening while you travel.
Josette: Right, and right now the only insurance that seems to be foolproof is staying put!
[end of dialogue]
Our dialogue in this episode is about travel insurance. “Insurance” (insurance) is an agreement that you sign with some company – called an “insurance company,” of course – in which you give the company some money, and if something bad happens to you in the future, the company will pay for whatever bad happens to you.
So, for example, if you buy “car insurance,” you give the insurance company money every year, and if you have an accident, the insurance company will pay for most or all of the repairs that need to be done to your car. Why would the insurance company do this? Well, because most people don’t have accidents. And so, you’re paying the insurance company money, and usually you won’t get any of that money back, but if you do have an accident, well, then the insurance company will pay for it.
Insurance companies need lots of different people to buy insurance from them so that they can make money, since only a small percentage of people will actually need the insurance – only a small percentage of people will actually get money back from their insurance policy, their insurance agreement.
Our dialogue, then, begins with Josette saying, “I admit it. I’m a nervous traveler and I don’t like traveling internationally.” Tae-jin says, “You could get travel insurance.” “Travel insurance” is a special kind of insurance that will pay for any problems you might have while you are traveling. Tae-jin says that “Doing that” – that is, buying travel insurance – “would make you feel more secure, wouldn’t it?” “To feel secure” (secure) means to feel safe, to feel like you’re not in danger, that nothing bad will happen to you.
Josette says, “Maybe,” meaning “Well, maybe it will make me feel secure.” She then asks, “What types of coverage are available?” “Coverage” (coverage) refers to the kinds of things that the insurance will pay for – the kinds of “protection,” we might say, that are provided by the insurance policy or agreement. Tae-jin replies, “You could get insurance to cover mishaps on the trip, such as canceled flights or missed connections and having your luggage lost, stolen, or damaged.”
“Mishaps” (mishaps) are accidents – something negative or unfortunate that happens that usually you can’t avoid. A mishap is usually something not too serious that has happened. If someone dies, we probably wouldn’t call that a “mishap.” But if, for example, you fall on the ground and are not hurt to seriously, that might be considered a mishap. It’s an unlucky accident. Then we get a list of examples of mishaps. One would be “canceled flights,” meaning the airline, the company that owns all of the airplanes, decides that it’s not going to fly your plane to the place where you want to go.
“Missed connections” refers to when you are flying from one place to another but have to go to a third place before you arrive at your final destination. So, for example, if you are flying from Los Angeles, California, to New York City, you might have to first fly to Chicago and then get on another plane that flies you to New York. That second flight, that second plane, would be your connection. We would say, “You have to make a connection in Chicago.”
A “missed connection” would be a situation where your first plane arrives too late and you no longer are able to get onto the second plane. Losing your luggage is also a possible mishap that travel insurance might pay for. “Luggage” refers to your baggage – the suitcases that you bring with you that have your clothes and other items in them.
Tae-jin says that travel insurance even covers your losses if your trip is canceled. Your “losses” refers to the amount of money that you lose when something bad or unfortunate happens. If your flight is canceled – if the airline is not going to fly the plane as it said it would to your destination, to the place where you want to go – you might lose money on a hotel room that you already paid for and can’t get your money back on.
Josette says, “I guess that would help, but I’m more nervous about something happening to me while I’m in another country.” Tae-jin says, “In that case, you can get medical insurance to cover the costs of medical emergencies.” “Medical insurance” refers to insurance that pays for when you have an accident or when you’re sick.
“Medical emergencies” would be things that require immediate attention, serious situations related to your health. If you break your leg while skiing, for example, which happened to my brother-in-law not too long ago, that would be a medical emergency. He was in another country, and he had to go to the hospital. Someone has to pay for that, and if he had medical insurance, the insurance company would probably pay for most of that. (As, indeed, it did.)
Sometimes you need to leave the country and be brought back to your own country. This would be a case of a “medical evacuation.” The verb is “to evacuate” (evacuate). “To evacuate” someone means to move them from a dangerous place to a safer place. In this case, it may not be that the place where you are is dangerous. It may be instead that the place where you are doesn’t have the kind of medical services you need, so that you have to be taken to another hospital in another country.
Josette says, “Oh, you’re right. I could get really sick or injured.” Tae-jin says, “And if things go terribly wrong, there’s even insurance for if you become disabled or if there is an accidental death.” If something goes “terribly wrong,” it goes very wrong – something very bad happens. What could happen? Well, you could become disabled. “To be disabled” (disabled) means that you have something bad happen to your body so that you can no longer work, or perhaps even walk. That would be a case of being disabled or becoming disabled.
An “accidental death” would be when you die, not because someone murdered you or killed you, like your wife, but because there was some sort of accident – something unexpected happens. Tae-jin says that the insurance companies will pay for “repatriation of your remains or overseas funeral services.” “Repatriation” (repatriation) is when something is brought back to the country from which it originated – usually a person, or in this case, your dead body.
Your “remains” (remains) refer to what’s left of your body. Sometimes nowadays people have their body “cremated” – that is, burned. So, your remains would be what remains after they burn your body – which would be your ashes – or your remains could be your actual physical body, with your head and your arms and your legs and so forth.
The insurance companies, if you have travel insurance, could pay for “repatriation of your remains or overseas funeral services.” “Overseas” refers to in another country. “Funeral” (funeral) is some sort of ceremony or service that takes place when a person dies. Usually it involves your friends and family coming together to talk about you or to perform some sort of religious ceremony or participate in a religious ceremony.
Josette says, “Disabilities and death? Is that supposed to put my mind at ease?” Tae-jin, remember, was trying to make Josette feel calmer, more secure about traveling, and now he’s talking about her dying and being buried, having a funeral. Josette asks Tae-jin if what he is telling here is supposed to put her mind at ease. “To put your mind at ease” (ease) means to make you feel calmer and less worried – to make you feel as though nothing bad is going to happen.
Tae-jin says, “The whole point is to make you less worried about bad things happening while you travel.” Josette says, “Right,” meaning yes, that’s right, “and right now, the only insurance that seems to be foolproof is staying put.” “Foolproof” (foolproof) is something that cannot fail, that cannot go wrong – something that will work always, that will never cause any problems.
What Josette is saying here is that instead of buying insurance and traveling, the best way to be safe and secure is simply to stay put. “To stay put” is a phrasal verb meaning not to move, not to go anywhere.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Josette: I admit it. I’m a nervous traveler and I don’t like traveling internationally.
Tae-jin: You could get travel insurance. Doing that would make you feel more secure, wouldn’t it?
Josette: Maybe. What types of coverage are available?
Tae-jin: You could get insurance to cover mishaps on the trip, such as cancelled flights or missed connections and having your luggage lost, stolen, or damaged. It’ll even cover your losses if your trip is cancelled.
Josette: I guess that would help, but I’m more nervous about something happening to me while I’m in another country.
Tae-jin: In that case, you can get medical insurance to cover the costs of medical emergencies, even if you have to be medically evacuated in the event of serious injuries or illness.
Josette: Oh, you’re right. I could get really sick or injured.
Tae-jin: And if things go terribly wrong, there’s even insurance for if you become disabled or if there’s an accidental death. They’ll pay for repatriation of your remains or overseas funeral services.
Josette: Disabilities and death? Is that supposed to put my mind at ease?
Tae-jin: The whole point is to make you less worried about bad things happening while you travel.
Josette: Right, and right now the only insurance that seems to be foolproof is staying put!
[end of dialogue]
Our scriptwriter makes sure nothing goes terribly wrong with our scripts – that’s the wonderful Dr. Lucy Tse of whom I speak. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
travel insurance – a financial policy (agreement) purchased by a traveler so that he or she receives a large payment if certain bad things happen during a particular trip
* Will travel insurance reimburse my expenses if a trip is canceled due to war?
secure – safe from danger; not facing risk of injury or death
* Would the presence of armed guards make high school students feel more or less secure at school?
coverage – the types and amount of financial protection provided by an insurance policy
* This health insurance includes great coverage for medical expenses, but nothing for dental or vision care.
mishap – an accident; something negative or unfortunate that happens, especially as a result of chance and that may have been unavoidable
* Belinda traveled across the country and arrived without mishap.
missed connection – not getting onto a second or third flight in a journey, usually because one’s previous flight arrived later than expected
* Our flight to Denver was delayed due to bad weather conditions, and that resulted in a missed connection for our flight to San Juan, Puerto Rico.
loss – money that one loses; money lost by a business or organization
* The car manufacturer is reporting significant losses in the most recent quarter due to rising costs and falling sales
medical insurance – a financial policy (agreement) purchased by a individual so that he or she receives money to help cover the costs of medical expenses
* The medical insurance pays up to 100% of the cost of seeing an in-network doctor, but only 20% of the cost of seeing an out-of-network doctor.
emergency – a serious, urgent situation that could result in significant damage, pain, or death
* The governor declared a state of emergency due to the flooding.
evacuate – to move someone from a dangerous place to a safer place
* The police have issued orders to evacuate the building because they think a bomb might be inside.
to go terribly wrong – to proceed in an unplanned, negative way with very bad consequences
* They wanted to have a beautiful outdoor wedding in the forest, but everything went terribly wrong when it started snowing and a bear ate the wedding cake.
disabled – having a medical condition that limits the use of one’s body, especially so that one can no longer work
* When Kent became disabled in the car accident, they had to modify their home so that his wheelchair could get through doorways.
accidental death – an unexpected death caused by normal activities when something went wrong, but not a death caused by murder, war, illegal activities, or certain dangerous hobbies
* At first, everyone suspected a murder, but in the end, the investigators determined that it was an accidental death.
repatriation – the process of returning someone to his or her home country
* How can we speed up the repatriation of refugees from the war?
remains – what is left of a person’s body after death
* Police are using dental records to identify the remains found in the woods.
funeral – a ceremony that honors the memory of a dead person and allows others to say goodbye to that person, usually while burying (putting underground) the body
* Gregorio’s funeral was attended by friends, family members, co-workers, community leaders, and others.
to put (one’s) mind at ease – to make someone feel calmer and less worried; to provide reassurance
* Knowing that our neighbor will watch the house while we’re on vacation really put my mind at ease.
foolproof – unable to fail; unable to happen incorrectly or result in problems
* Do you think there will ever be a foolproof way to prevent hackers from accessing confidential information using the Internet?
to stay put – to stay where one is; to not move
* If you get lost, stay put and I’ll come back to find you.
Comprehension Questions
1. What is a missed connection?
a) When you can’t find the person you were supposed to meet
b) When you aren’t able to make a phone call at the right time
c) When you miss your next flight to continue your journey
2. When would funeral services be required?
a) In case of a missed connection
b) In case of a medical emergency
c) In case of an accidental death
Answers at bottom.
What Else Does It Mean?
loss
The word “loss,” in this podcast, means money that one loses, or money lost by a business or organization: “In the first years of business, they had losses of almost $80,000.” The word “loss” can also refer to the death of someone: “We’re so sorry for your loss.” Or, “She was devastated by the loss of her child.” In general, the word “loss” refers to the absence of something that one used to have: “Loss of appetite can be a side effect of this medication.” Or, “If a student shows a sudden loss of interest in school, it could be a sign of problems at home.” Finally, the phrase “to be at a loss” means to be confused or overwhelmed and not know what to do next: “We were at a loss about how to react to the announcement.”
remains
In this podcast, the word “remains” refers to what is left of a person’s body after death: “Investigators are analyzing the remains to estimate when the individual died.” Or, “Who picks up the remains of animals that are killed on the roads?” The word “remains” can also refer to anything that is left over after something else has been used or has otherwise disappeared: “Heather nibbled on the remains of her daughter’s cupcake.” Or, “It took them several weeks to clean up the remains of their burnt-down house.” Finally, the phrase “it remains to be seen” means that the results of something are unknown and will not be known until the future: “The ultimate success of the marketing campaign remains to be seen.”
Culture Note
Types of Travel Insurance
In addition to the travel insurance and medical insurance discussed in this podcast, many other types of travel insurance are available to travelers who are willing to pay the “premiums” (the amounts that must be paid in order to have an insurance policy). For example, “trip cancellation insurance,” also known as “trip interruption insurance,” provides coverage if the trip must be canceled either due to the traveler’s “circumstances” (situation), such as an illness, or due to weather-related issues. “Baggage insurance” provides “reimbursement” (money used to cover someone’s expenses or losses) if the traveler’s “baggage” (luggage; suitcases) are damaged or lost during the trip. And “flight insurance” is a type of life insurance that is “paid out” (money paid as a result of the policy) only if the insured individual dies in a “plane crash” (when an airplane has an accident and hits something).
Some types of travel insurance are “specific to” (designed for a specific purpose) certain “high-risk” (with a high probability of being injured) sports that are not covered by other types of travel insurance. For example, “ski travel insurance” covers the cost of replacing damaged ski equipment as well as travel mishaps like canceled flights and injuries or illnesses. “Adventure travel insurance” might provide coverage for risky activities like rock-climbing, “sky diving” (jumping out of airplanes), and more.
Other types of travel insurance provide coverage in dangerous countries. Most travel policies do not cover travel to countries for which a “travel advisory” or “travel warning” (an official government recommendation that people not travel to a particular place) has been issued. But “high-risk” travel insurance can provide coverage for people who must travel to those countries, such as journalists or security workers.
Comprehension Answers
1 - c
2 - c