= 1094
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,094 – Tracing One’s Genealogy.
This is English as a Second Language Podcast episode 1,094. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at ESLPod.com. Become a member of ESL Podcast. You will get a Learning Guide, if you do, for each and every one of our current episodes. The Learning Guide contains all of the vocabulary definitions, cultural notes, and a complete transcript of everything we say.
This episode is a dialogue about your genealogy – who your parents, grandparents, great-grandparents, and so forth are. Let’s get started.
[start of dialogue]
Aaron: Do you think you can help me trace my genealogy?
Corrie: Sure, I can try. We can get started by talking to your parents and grandparents. Oral interviews will give us some names of your relatives.
Aaron: I’ve already talked to them and I grew up hearing stories about my lineage on both sides of my family.
Corrie: That’s great. If you know of some of the people you’re descended from, we can start by looking at public records and historical records from the area. You’re from Tennessee, right?
Aaron: That’s right. There are a lot of people in Tennessee with my last name, though.
Corrie: Well, we can triangulate the information we get to zero in on your ancestors.
Aaron: What if I want proof positive that I’m related to someone?
Corrie: Then you can have a genetic analysis done. A DNA test is generally accepted proof.
Aaron: Good, it’s about time someone in my family established the blood connections.
Corrie: Blood connections to whom?
Aaron: Elvis, of course.
Corrie: Elvis?! You think you’re related to Elvis?
Aaron: His last name was Presley; my last name is Presley. My first name is Aaron; his middle name was Aaron. It can’t be a coincidence, especially considering my talent.
Corrie: Talent?
Aaron: Sure, listen: “Well, it’s one for the money, two for the show, three to get ready, now go, cat, go!”
Corrie: I consider that counterevidence!
[end of dialogue]
Aaron begins our dialogue by asking Corey, “Do you think you can help me trace my genealogy?” Your “genealogy” (genealogy) is a list or a description of the relatives that you have – your parents, your cousins, your grandparents, your uncles – all the way back to however far back you can trace your genealogy. The verb “to trace” (trace) here means to follow, to find out where something begins.
People often talk about being able to trace their genealogy back to medieval England or to the seventeenth century. Another term for genealogy is “family tree.” Your family tree is the same as your genealogy. It’s a list or description of all the people who are related to you, including all of those who came before you. Corrie says, “Sure, I can try” – I can try to help you trace your genealogy, she’s saying. “We can get started by talking to your parents and grandparents. Oral interviews will give us some names of your relatives.”
Your “relatives” (relatives) are the people who are related to you, who are part of your family, either as brothers, sisters, cousins, aunts, uncles, grandparents – any of those relationships refer to your “relatives.” Corrie suggests doing “oral interviews” – sitting down and talking to someone and either recording what they say or writing down what they say.
Of course, if you want to find out who your ancestors were – the people who came before you, your relatives from previous generations – you would need to or would be highly advised to talk to your grandparents and your parents to get started in finding out the names of the people who are related to you. Aaron says, “I’ve already talked to them,” meaning his parents and grandparents. “I grew up hearing stories about my lineage on both sides of my family,” he says. The term “lineage” (lineage) refers to a description of how you are related to someone in a previous generation or born before.
I use the term “generation” a couple of times here. Let me explain what I mean by that. You and your brothers and sisters and your cousins are all one generation. Your parents and your aunts and uncles are another generation. Your grandparents are another generation. You could create a diagram or a chart that shows these different generations as different lines on the chart or on the diagram.
Corrie says, “That’s great. If you know some of the people you’re descended from, we can start by looking at public records and historical records from the area.” The expression “to be descended (descended) from” someone means to be the child, grandchild, great-grandchild, and so forth of a person. So, I am descended from my parents, Patrick and Mary McQuillan. I’m also descended from my grandparents and my great-grandparents. These are people who came before me who are my relatives.
“Public records” refers to government records that anyone can go and look at. Not all the records or information that the government has are public, however. Some of it is not information you can look at, but a lot of information that the government collects is public – anyone can go and look at it. That has been made even easier now with the Internet. “Historical records” or “historical information” are written histories or written pieces of information about what happened in the past.
So, public records are also historical records in many cases, but historical records can refer to other documents, other information that is available, including perhaps a local history about the area from which your ancestors came. Corrie then asks Aaron, “You’re from Tennessee, right?” Aaron says, “That’s right,” meaning that’s correct. “There are a lot of people in Tennessee with my last name, though.” Corrie says, “Well we can triangulate the information we get to zero in on your ancestors.”
Aaron is saying that he’s from the state of Tennessee, which is located in the central-eastern part of the United States. However, there are many different people in Tennessee with his same last name. Therefore, if you are looking in the public records or in historical records, there will be a lot of people who have Aaron’s last name who may or may not be his relatives. Corrie says that they can “triangulate the information.” “To triangulate” (triangulate) can mean to measure something that is the length or height of something that you don’t know by using other measurements.
However, in a more general sense, “to triangulate” means to take different pieces of information in order to narrow down the options or in order to identify the relevant object or thing. In this case, it means to take other information about the people who have Aaron’s last name in Tennessee and use that other information to decide which of the people who have his last name are actually his relatives. That’s why Corrie says, “We can triangulate the information we get to zero in on your ancestors.”
“To zero (zero) in on” something is to focus your attention on something, to identify one thing. In this case, they are identifying Aaron’s ancestors – his relatives who came before him. Aaron then asks, “What if I want proof positive that I’m related to someone?” “Proof” (proof) is evidence, clear evidence that shows something is either true or false. So, “proof positive” would be clear evidence, detailed evidence that is absolutely certain, that tells you with certainty whether something is true or not.
Corrie says, “Then you can have a genetic analysis done. A DNA test is generally accepted proof.” A “genetic analysis” is a study of biological information that can help identify who your relatives are. The most common way is to use your DNA. Your DNA is the specific biological information that identifies you. “DNA” is the biological information inside your body’s cells, the smallest or one of the smallest units of your biological makeup. DNA determines a lot of different things about the individual human being and can be used to identify people who are related to you.
Aaron says, “Good. It’s about time someone in my family established the blood connections.” “It’s about time” is a phrase that we use to mean that we have been waiting for something for a long time, and now we are pleased or happy to learn that it has finally happened. “It’s about time someone in my family,” Aaron says, “established the blood connections,” meaning the biological relationship.
Corrie’s a little confused. She says, “Blood connections to whom?” – to what specific person are you talking about? Aaron says, “Elvis, of course.” He means the famous singer Elvis Presley. Corrie says, “Elvis?! You think you’re related to Elvis?” Aaron says, “His last name was Presley; my last name is Presley. My first name is Aaron; his middle name was Aaron. It can’t be a coincidence, especially considering my talent.” A “coincidence” is a somewhat surprising, unexpected set of events that happen at the same time or that are somehow related without any planning or apparent purpose.
In this case, Aaron is saying that he shares names with Elvis Presley and he also is talented like Elvis Presley. Corrie says, “Talent?” Aaron says, “Sure, listen,” and then he sings a line from one of Elvis Presley’s most famous songs: “Well, it’s one for the money, two for the show, three to get ready, now go, cat, go!” That, of course, is a line from “Blue Suede Shoes,” a song by Elvis Presley (sung very badly – I know).
Corrie says, “I consider that counterevidence.” In other words, she’s listened to Aaron sing, and she doesn’t think that the singing talent that Aaron has is anything like the singing talent that Elvis Presley had. That’s why she says that Aaron’s singing is “counterevidence.” Counterevidence would be some indication, some fact, that would show that what you are saying is not true or is not possible. Aaron’s bad singing shows, according to Corrie, that he’s probably not a relative of the great singer Elvis Presley.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Aaron: Do you think you can help me trace my genealogy?
Corrie: Sure, I can try. We can get started by talking to your parents and grandparents. Oral interviews will give us some names of your relatives.
Aaron: I’ve already talked to them and I grew up hearing stories about my lineage on both sides of my family.
Corrie: That’s great. If you know of some of the people you’re descended from, we can start by looking at public records and historical records from the area. You’re from Tennessee, right?
Aaron: That’s right. There are a lot of people in Tennessee with my last name, though.
Corrie: Well, we can triangulate the information we get to zero in on your ancestors.
Aaron: What if I want proof positive that I’m related to someone?
Corrie: Then you can have a genetic analysis done. A DNA test is generally accepted proof.
Aaron: Good, it’s about time someone in my family established the blood connections.
Corrie: Blood connections to whom?
Aaron: Elvis, of course.
Corrie: Elvis?! You think you’re related to Elvis?
Aaron: His last name was Presley; my last name is Presley. My first name is Aaron; his middle name was Aaron. It can’t be a coincidence, especially considering my talent.
Corrie: Talent?
Aaron: Sure, listen: “Well, it’s one for the money, two for the show, three to get ready, now go, cat, go!”
Corrie: I consider that counterevidence!
[end of dialogue]
If I were to zero in on the main reason these podcasts are successful, I would have to say that it is the scriptwriting by the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2015 by the Center for Educational Development.
Glossary
to trace – to track; to follow the path or development of something, especially to find where it began
* If we follow these tracks, we can trace the raccoon to its home.
genealogy – the study of the line of descent through generations; a detailed description of how one is related to a member of an earlier generation
* The family genealogy shows that they are related to King James III of Scotland.
oral interview – a spoken (not written or typed) conversation with one person asking questions and the other person answering them
* The candidates will be invited to participate in an oral interview over the phone, and the most-qualified individuals will be invited to come to the office for a face-to-face interview.
relative – a person in one’s family, whether connected by blood or marriage
* Most of our relatives live in Wyoming and Colorado, but we have a few cousins nearby.
lineage – one’s descent from an ancestor (a family member who lived long ago); a description of how one is related to someone in a previous generation
* We can’t follow our lineage very far back, because both of our parents were adopted.
to be descended from (someone) – to be the child, grandchild, great-grandchild, etc. of someone
* When Lilly was younger, she liked to put on fancy dresses and dream that she was a princess descended from royal kings and queens.
public records – official documents that have been stored with local or state government, especially about births, deaths, and marriages
* The public records don’t contain any marriage records for that name. Are you sure they were married in this county?
historical records – written history; written information about what happened in the past
* Biblical research would be a lot easier if there were more historical records, but many documents from that time have been lost or destroyed.
to triangulate – to measure an unknown length or height by knowing some other pieces of information, such as measuring the height of a building by knowing the length of its shadow and the angle of the sun
* The high school geometry teacher is teaching students how to triangulate by having them measure shadows all over the school.
to zero in on – to focus one’s attention and begin to identify something
* The police officers are starting to zero in on the identity of the thief.
ancestor – a person from whom one is descended; a direct relative who lived long ago, especially a great-grandparent, great-great-grandparent, etc.
* Our ancestors were hard-working people who built this farm with their own hands.
proof positive – clear evidence that something is true, without any doubt or hesitation
* The project manager wants proof positive that the idea will work, but we won’t know until we try to implement it.
genetic analysis – a detailed study of the biological information inside one’s cells (the very small parts of the body that one needs special equipment to see)
* Through genetic analysis, scientists can determine someone’s likelihood of getting certain types of cancers.
DNA test – a detailed study of the biological information inside one’s cells, specifically the deoxyribonucleic acid, often to determine whether one is related to a specific person
* The DNA test proved that the baby was his daughter.
it’s about time – a phrase meaning that one has been waiting for something a long time and is pleased or relieved that it has finally happened
* It’s about time you showed up! I’ve been waiting here for almost 40 minutes!
coincidence – a surprising, sometimes humorous instance where two or more things happen at the same time without any planning and with no apparent purpose
* What a coincidence! That’s my name, too!
counterevidence – facts that show something is not true or is not possible
* Most of the jurors thought the man was guilty, until his attorney produced some counterevidence that clearly showed he was nowhere near the crime scene that night.
Comprehension Questions
1. What could be found in the public records?
a) Recordings by famous local musicians.
b) Transcripts and academic reports cards.
c) Official reports of births and deaths.
2. Which of these could be one’s ancestor?
a) A great-great grandmother.
b) A half-brother.
c) A cousin.
Answers at bottom.
What Else Does It Mean?
to trace
The verb “to trace,” in this podcast, means to track or to follow the path or development of something, especially to find where it began: “They’re conducting research to trace the spread of malaria across the continent.” When talking about drawing, “to trace” means to copy a drawing by placing a semi-transparent (nearly see through) piece of paper over it and following the lines with one’s pen or pencil: “The copier broke, so we’ll have to try to trace the design by hand.” The verb “to trace” means to draw the shape of something by moving one’s pen or pencil around the edge of it: “The preschoolers traced their hands onto pink paper to make a Valentine’s Day card.” Finally, the phrase “to trace a call” means to use special equipment to determine from where a phone call is being made: “Next time he calls, the police officers will try to trace the call.”
to zero in on
In this podcast, the phrase “to zero in on” means to focus one’s attention and begin to identify something: “Some editors are good at zeroing in on mistakes and inconsistencies in drafts of books.” The phrase “ground zero” describes where a bomb explodes or where a deadly battle occurs: “The soldiers found themselves at ground zero, and many of them died.” The phrase “zero tolerance” describes a policy or law that treats everyone equally, giving everyone the same punishment with no exceptions: “The school has a zero-tolerance policy against students bringing weapons onto campus.” Finally, the phrase “a zero-sum game” describes a situation where one person loses exactly the same amount as another person wins: “Creating the budget is a zero-sum game, because no matter how many categories we create, the total amount of money doesn’t change.”
Culture Note
Genealogical Societies
The New England Historic Genealogical Society is the oldest and one of the best-known “genealogical societies” (organizations that help people trace their ancestry) in the United States. “Founded” (created) in 1845, it has 50 staff members and more than 25,000 members. The organization’s “purpose” (reason for existing) is to “advance (improve; increase; expand) the study of family history in America and beyond.” Although the name includes “New England” (the northeastern part of the United States), the organization’s research “spans” (covers) the entire country and “beyond” (even further).
The organization “maintains” (operates and keeps current) a website that allows visitors to search the organization’s “database” (a collection of digital information stored electronically) of more than 100 million names. The organization also publishes newsletters and “journals” (magazines with research-based articles) and has a large library of genealogical books, “manuscripts” (written, especially handwritten, documents that were later published), and more.
The Genealogical Society of Utah, founded in 1894, is not quite as old, but it is also well known. The organization is “affiliated with” (connected to) The Church of Jesus Christ of Latter-day Saints (LDS Church; see English Café 222). Members of the Church believe it is important to study genealogy to “seal” (connect) “family units” (groups of family members) together for “eternity” (forever; until the end of time). So the organization helps people identify their ancestors through its website, library, and other resources. The websites allows people to upload photos of their ancestors as well.
Comprehension Answers
1 - c
2 - a