= 0301
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 301: Buying a Men’s Suit.
This is English as a Second Language Podcast episode 301. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and take a look at our Learning Guides. You can also look at our ESL Podcast Store, which has several premium courses you may be interested in.
This episode is all about someone who is buying – a man, who is buying a suit, a formal piece of clothing that you would wear to a business meeting or a wedding, for example. There will also be vocabulary here more generally about buying clothes. Let’s get started.
[start of dialogue]
Sales clerk: Good afternoon. What can I help you find?
Bo: I’m looking for a suit for work.
Sales clerk: I’m sure we have something for you. Are you looking for a traditional or contemporary suit?
Bo: I’m not sure. I’d like to try on some different ones.
Sales clerk: That’s no problem. Let me show you a few over here. This is a two-button pinstripe suit that’s made of 100% wool and has a flat front. What do you think?
Bo: It looks nice. How about this one?
Sales clerk: Oh, this is a very fine suit. As you can see, it’s double-breasted and is fully lined. The pants are pleated. Would you like to try it on?
Bo: Sure.
Sales clerk: Just follow me to the dressing rooms in the back. Here you are. My name is Caroline. Just let me know if you need anything.
Bo [comes out of the dressing room wearing one of the suits]: I like this single-breasted one. I like the side vents. All of these suits need to be dry cleaned, is that right? I travel a lot in my job and I worry about my suits getting dirty on the road.
Sales clerk: Yes, they all need to be dry cleaned, but since both of these suits are a dark color, that shouldn’t be too big of a problem. How does that feel?
Bo: It’s a good fit and it’s very comfortable. Okay. I’ll take this one.
Sales clerk: Certainly. I’ll ring you up. Do you need anything else? A vest, suspenders, or a garment bag to store the suit?
Bo: No, thanks. I’ll just take the suit.
Sales clerk: No problem. Just follow me.
[end of dialogue]
Our dialogue begins with the sales clerk saying, “Good afternoon. What can I help you find?” The “sales clerk” is the person who works at the store who sells you things.
Bo says, “I’m looking for a suit for work.” A “suit,” for a man, usually has a jacket that you wear over a shirt, and pants. Usually they are made of the same what we would call “fabric” (fabric). “Fabric” is the material that you make clothing from. “Suit” has several meanings in English; take a look at our Learning Guide for some additional definitions.
The sales clerk says, “I’m sure we have something for you. Are you looking for a traditional or contemporary suit?” “Contemporary,” here, means modern (related to the present time). “Traditional” would be what people have worn in the past. Contemporary can also mean, for some people, a little too modern. Traditional would be a more conservative suit, a suit that would look like the suits that people have worn in the past. A contemporary suit might have a different look to it. We use that word “contemporary” when talking about all sorts of things (lots of things). You could have contemporary music, music made in the last 20-30 years, for example, or contemporary art.
Bo says he’s not sure what he is looking for. He says he’d like to try on some difference suits. To “try on” is a two-word, or phrasal verb, which means to put on a piece of clothing. A shirt, a jacket, shoes, pants, socks – all of those would be pieces of clothing you could try on. You put it on, or try it on, to see if you like it and you want to buy it.
The sales clerk says, “That’s no problem. Let me show you a few suits over here. This is a two-button pinstripe suit.” A “button” is a round piece of plastic or wood, maybe metal, that is put into, for example, a jacket. You have a button on one side and a buttonhole on the other, and the button goes into the hole to keep to keep the jacket together. We have buttons on shirts; you could have buttons on your pants.
This is a two-button pinstripe suit. The word “pinstripe” (pinstripe) refers to very thin, light colored lines that are put on a dark piece of fabric. The lines go vertically, from top to bottom. They’re very thin; they are used in making formal business suits, a “pinstripe suit” we call it. This is a two-button, so it has two buttons on the jacket – a two-button pinstripe suit that’s made of 100% wool and has a flat front. “Wool” (wool) is a fabric that is made from the hair of sheep, or possibly a goat; usually it is a sheep. And, wool is a very warm fabric; if you are cold, and you put on a wool jacket or sweater, you will become warmer. This suit has a flat front. A “flat front” means that there is no design or detail on the front. It is plain in front; it’s a flat front suit.
The sales clerk asks Bo, “What do you think?” meaning do you like it, do you dislike it. Bo says, “It looks nice. How about this one?” The sales clerk says, “Oh, this is a very fine suit.” Of course, the sales clerk thinks all of the suits are fine, as long you buy one! She says, “As you can see, it’s a double-breasted suit.” To say something is “double-breasted” (breasted) means the jacket has two front parts. Each part has buttons, so that when you close the jacket (when you put the front of the jacket together) one part goes over the other part, and there are two buttons showing. So it’s a little more complicated type of jacket, a double-breasted suit jacket.
The suit jacket is fully lined (lined). When we say something is “lined,” we mean that there is another layer of fabric inside the jacket, usually to make it look a little more professional, so that the front of the jacket (the outside of the jacket) looks a little different than the inside of the jacket. There are two pieces of fabric as part of the jacket.
Bo says that he wants to try on the double-breasted suit. The sales clerk also tells him that the pants are pleated (pleated). When something is “pleated,” we mean that there are folds that are sewn into the clothing, so it looks they have two or three small folds in the front of the pants. You can also have a pleated skirt, if you’re a woman – or a man who likes to wear skirts!
The sales clerk says to Bo, “Just follow me to the dressing rooms in the back.” The “dressing rooms” are small rooms, usually with a mirror, that you can go and put on clothing in a store. You can also have dressing rooms in a gymnasium, where two athletic teams are playing. They would go into the dressing room to put on the clothes they need to play the game. That’s also called a “dressing room.”
Bo comes out of the dressing room and says, “I like this single-breasted one.” A “single-breasted” jacket is a jacket that has buttons on only one side in the front, so that when you close the jacket one part goes over the other, and you have one line (or one column) of buttons that you can see. Bo says he also likes the side vents. A “side vent” (vent) is a long, thin opening at the side and the bottom of your shirt or jacket that allows you to move more easily.
Bo asks if all of the suits need to be dry cleaned. To “dry clean” (two words) means to wash certain kinds of fabric without using water. It’s done at a special cleaning business; we call them “dry cleaners.” And, if you have certain kinds of clothing that will not be able to be washed without changing them, or ruining them (harming them), you can bring it to a dry cleaner. The clerk says yes, these are all suits that need to be dry cleaned.
Bo says that the suit is a good fit. When we say something is a “good fit,” we mean it’s the correct size and shape for your body. Bo says he’ll “take this one,” meaning he’ll buy this suit.
The sales clerk says, “Certainly. I’ll ring you up (I will tell you how much money you need to give me). Do you need anything else? A vest, suspenders, or a garment bag?” A “vest” is a piece of clothing like a jacket, but it doesn’t have any sleeves for the arms. “Suspenders” are long, thin pieces of cloth that go on the front of your pants (a man’s pants, usually) and the back of your pants, and over your shoulders. So, they are used to prevent your pants from falling down. Suspenders are kind of old-fashioned. You don’t see a lot of men wearing suspenders; most just wear belts. But you will still see suspenders for some men, especially with a very formal suit. A “garment (garment) bag” is a piece of fabric or plastic that you use to hold clothing, to put clothing in so it doesn’t get dirty. On an airplane, sometimes you will see men or women with business suits that have a garment bag. It’s their clothing inside, and they use that so that it doesn’t get dirty or it doesn’t get folded – we would say it doesn’t get “wrinkled,” meaning the fabric has lines in it after you take it out the bag.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Sales clerk: Good afternoon. What can I help you find?
Bo: I’m looking for a suit for work.
Sales clerk: I’m sure we have something for you. Are you looking for a traditional or contemporary suit?
Bo: I’m not sure. I’d like to try on some different ones.
Sales clerk: That’s no problem. Let me show you a few over here. This is a two-button pinstripe suit that’s made of 100% wool and has a flat front. What do you think?
Bo: It looks nice. How about this one?
Sales clerk: Oh, this is a very fine suit. As you can see, it’s double-breasted and is fully lined. The pants are pleated. Would you like to try it on?
Bo: Sure.
Sales clerk: Just follow me to the dressing rooms in the back. Here you are. My name is Caroline. Just let me know if you need anything.
Bo [comes out of the dressing room wearing one of the suits]: I like this single-breasted one. I like the side vents. All of these suits need to be dry cleaned, is that right? I travel a lot in my job and I worry about my suits getting dirty on the road.
Sales clerk: Yes, they all need to be dry cleaned, but since both of these suits are a dark color, that shouldn’t be too big of a problem. How does that feel?
Bo: It’s a good fit and it’s very comfortable. Okay. I’ll take this one.
Sales clerk: Certainly. I’ll ring you up. Do you need anything else? A vest, suspenders, or a garment bag to store the suit?
Bo: No, thanks. I’ll just take the suit.
Sales clerk: No problem. Just follow me.
[end of dialogue]
The script for this podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
suit – professional clothing of a jacket and pants made from the same fabric
* I always wear my best suit to important business meetings.
contemporary – modern; related to the present time; not old-fashioned; not dated
* Shelly likes contemporary music, but her cousin prefers classical music by Bach and Mozart.
to try on – to put on a piece of clothing to see how well it fits and decide whether one likes it and wants to buy it
* Yvonne tried on the sweater, but it was too big, so she’s now looking for the same sweater in a smaller size.
button – a round piece of plastic, wood, metal, or glass, that is sewn onto a piece of fabric and goes through a hole in another part of the fabric, to keep the two pieces held together
* Do you prefer jackets with buttons or zippers?
pinstripe – very thin light-colored lines that are printed vertically (up and down) on dark fabric, often used for making business suits
* Should I wear this dark blue pinstripe suit or a plain black suit?
wool – fabric that is made from the hair of a sheep, goat, or similar animal
* Wool sweaters will keep you warm in cold weather, even if they get wet.
flat front – without any design or detailed sewing on the front; plain in the front
* Flat-front pants make you look thinner than do pants with lots of extra fabric.
double-breasted – a jacket that has two front parts, each with buttons, so that when the jacket is closed one part goes over the other part, and two columns (lines) of buttons are showing
* Since I’m big and tall, I look better in double-breasted jackets because the buttons cover my chest and stomach.
lined – having a layer of fabric sewn to the inside of one’s clothing to make it look more professional
* If you buy white pants, make sure that they’re lined so that people can’t see through the fabric.
pleated – having folds that are permanently sewn into a piece of clothing
* Pleated skirts used to be very popular, but now plain skirts are more common.
dressing room – a small room with a mirror in a store where one can put on clothing and see how it looks before deciding whether to buy it
* Please take only four pieces of clothing into the dressing room at a time.
single-breasted – a jacket that has buttons on only one side of the front, so that when the jacket is closed one part goes over the other part, and only one column (line) of buttons is showing
* Small women often wear single-breasted jackets with only one line of buttons.
side vent – a long, thin opening at the side and bottom of one’s shirt or jacket that allows one to move more easily
* Long jackets are easier to walk in if they have side vents.
to dry clean – to wash certain fabrics without using water done at a special cleaning business
* If you wash your silk fabrics at home, you may destroy them. Why don’t you take them to be dry cleaned instead?
fit – being the correct size and shape for one’s body
* This blouse isn’t a very good fit, but the pants are great.
vest – clothing that is like a jacket, but without sleeves; a sleeve-less shirt that buttons or zips in the front and is worn over another shirt
* Mr. Velazquez wore a gray suit with a white shirt and dark-blue vest.
suspenders – long, narrow pieces of cloth that attach to the front of one’s pants, go up over one’s shoulders, and attach to the back of one’s pants, to hold one’s pants up without using a belt
* Suspenders used to be very common, but now most men prefer to wear belts.
garment bag – a piece of fabric or plastic that zips around clothing on a hanger, to protect it from getting dirty or folded
* When Damian flew to his job interview, he carried his business clothes in a garment bag because he wanted to make sure they were in good condition when he arrived.
Comprehension Questions
1. Why does Bo try on different suits?
a) Because he doesn’t know what kind he wants.
b) Because he wants a contemporary and traditional suit.
c) Because he’s looking for a pinstripe suit.
2. How many columns of buttons are on the suit that Bo chooses to buy?
a) Zero.
b) One.
c) Two.
Answers at bottom.
What Else Does It Mean?
suit
The word “suit,” in this podcast, means professional clothing of a jacket and pants made from the same fabric: “Many bankers have to wear a suit every day.” A woman’s suit might include a skirt instead of pants. In general, a “suit” is a set of clothing. For example, a “swimsuit” is worn to swim, and a “wet suit” is worn to keep one warm while surfing or diving. Astronauts wear “spacesuits” when they fly into space. A “suit” is also one of the four sets of playing cards: “There are four suits in a deck of cards: hearts, diamonds, spades, and clubs.” Finally, a “suit” is short for “lawsuit,” or a legal complaint that one person or organization makes about another person or organization in court: “Gerald filed a suit against his employer.”
lined
In this podcast, the word “lined” means having a layer of fabric sewn to the inside of one’s clothing to make it look more professional: “This jacket is lined with wool, which makes it very warm.” The word “lined” also means having folds or lines. If one’s face is “lined,” one has wrinkles, or lines from old age: “As I get older, I can see that my face is more lined than it was 10 years ago.” If paper is lined, it has lightly-colored lines so that one can use them to write in a straight line: “If I don’t have lined paper, my writing always has a strange angle.” Finally, the word “lined” can mean having something along the edge or side: “They live on a beautiful tree-lined street.”
Culture Note
When men wear business suits, they can choose to wear many “accessories,” or small things that look good when they are worn with a suit. The most common accessory is a “tie,” or a long piece of fabric that is tied around a man’s neck and worn over a shirt, but under a suit jacket. Ties come in many colors and with many different designs or patterns. Many professionals choose “conservative” (traditional) ties that are one color or have only thin “stripes” (straight colored lines).
Some men choose to use a “tie clip” with their tie. A “tie clip” is a thin piece of metal that slides over one’s tie in front of one’s chest and “attaches” (connects) to one’s shirt, so that the tie can’t move very much. This helps to keep the tie from getting in one’s way while eating, working, or using office equipment.
Men can also wear “cuff links” with their suits. “Cuff links” are small pieces of metal with a special image that are used to close one’s “sleeve” (the fabric over one’s arm) around one’s “wrist” (the part of one’s body between one’s hand and arm). Some cufflinks are very expensive, made with diamonds and gold. Others have images related to sports teams or other things that are important to the men who wear them.
Finally, a “handkerchief” can be an accessory for a business suit. A “handkerchief” is a small, square piece of colored fabric that is folded and placed in one’s jacket pocket, on one’s chest. A small part of the handkerchief can be seen in the pocket, adding color to the suit. The handkerchief often “matches” (has the same color as) the tie.
Comprehension Answers
1 - a
2 - b