= 0311
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 311: A Mid-life Crisis.
This is English as a Second Language Podcast episode 311. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and take a look at our ESL Podcast Store that has some exciting new business and personal English courses for you. You can also download a Learning Guide for this episode to help you learn English even faster.
This episode is called “A Mid-life Crisis.” It’s a dialogue between a wife and a friend talking about the woman’s husband and how he is going through something we call a “mid-life crisis.” Let’s get started.
[start of dialogue]
Bella: I think my husband is going through a mid-life crisis.
Russell: What makes you think that?
Bella: He just traded in his car for a very expensive sports car, and he’s filling the house with gym equipment.
Russell: Uh oh, that’s a bad sign. Do you know what may have triggered this?
Bella: I’m not sure, but he was passed over for a promotion at work a couple of months ago, and his new boss is 15 years younger than he is.
Russell: That would do it.
Bella: What really worries me is that he’s been talking about quitting his job altogether and becoming a full-time writer. He always wanted to become a successful writer.
Russell: That’s sounds familiar. When my brother went through a mid-life crisis, he spent a lot of time reflecting on his life and regretting giving up music to get a full-time job. He saw himself as being washed up and he was fed up with everything.
Bella: What did he do?
Russell: Well, he’s probably not a good example of what your husband would do.
Bella: Don’t beat around the bush. Just tell me.
Russell: Well, if you must know, he got a divorce, married a woman half his age, and tried to start a rock band.
Bella: Oh, no! That’s just what I was afraid of.
Russell: I’m sure that won’t happen with your husband. You two have a great marriage.
Bella: I thought so, too, but you never know.
[end of dialogue]
This episode is called “A Mid-life Crisis.” “Mid-life” is the middle of your life; “mid” is short for “middle” here, so “mid-life” would be between perhaps 40 and 50, maybe 60 years old. A “crisis” is an emergency situation. So, a “mid-life crisis” is some sort of change – some emergency situation that takes place in your mid-life period. However, the term is usually referring to a period in a man’s life when he becomes unhappy because he’s getting older and he realizes he’s getting older. So, he sometimes does strange things to try to feel younger, like buy a new car. Or, start a podcast!
In the dialogue, Bella says to Russell, “I think my husband is going through a mid-life crisis.” Russell says, “What makes you think that?” – why do you think that? Bella said, “He just traded in his car for a very expensive sports car.” To “trade in” means to exchange one thing for another thing. This is especially common in the U.S. with your car. You have a car that’s maybe 5-10 years old and you want to buy a new one. You bring it to the people who sell cars – we would call them a “dealership” – and you give them your old car and they give you a certain amount of money for the old car as a discount off of your new car.
Well, Bella’s husband traded in his car for an expensive sports car. A “sports car” is usually a smaller car with a very powerful engine that moves very fast. That would be a “sports car.” In addition, Bella says that her husband is “filling the house with gym equipment.” “Gym equipment” are machines you can use for exercise such as a treadmill or weights. Some men, when they go through their mid-life crisis, will try to become more healthy – become more fit, get a younger car, if you will.
Russell says, “Oh, that’s a bad sign.” A “sign” is something that indicates what might happen in the future; it’s a signal, an indication. Russell says, “Do you know what may have triggered this?” To “trigger” (trigger) means to start something, to begin something, to make something happen. It’s often a small event that starts a much larger sequence of events. For example, many wars are triggered by small misunderstandings. Two countries may fight each other over what seems like a small thing; that small thing is the trigger.
Russell says, “Do you know what may have triggered this?” Bella says. “I’m not sure, but he was passed over for a promotion at work a couple of months ago.” To be “passed over” for something means not to receive something that you expected, especially at your work. You expected to get a better job, what we might call a “promotion,” and you didn’t get it; they gave it to someone else. In this case, they gave it to someone who’s 15 years younger than Bella’s husband. Russell says, “That would do it,” meaning that would be sufficient – that would be enough to start this mid-life crisis.
Bella continues, “What really worries me is that he’s been talking about quitting his job altogether (meaning completely, entirely – “altogether”) and becoming a full-time writer. He always wanted to be a successful writer,” she says.
Russell says, “That’s sounds familiar (that’s something I am familiar with). When my brother went through a mid-life crisis, he spent a lot of time reflecting on his life.” To “reflect on your life” is to think about – to think seriously and for a long time about something. To “reflect” has other meanings as well; take a look at our Learning Guide for some additional explanations.
Russell’s brother “spent a lot of time reflecting on his life, and regretting giving up music to get a full-time job.” To “regret” (regret) means to feel sad that you didn’t do something in the past, or that you did do something: “I regret not saying ‘I’m sorry’ to my friend last week,” or “I regret going to Phoenix, Arizona in the middle of the summertime” – because it’s a 120 degrees Fahrenheit there! That’s “regret.”
Russell says that his brother “saw himself (viewed himself) as being washed up,” and that “he was fed up with everything.” Here are a couple of two-word, or phrasal, verbs with the word “up” in them. To be “washed up” means to be no longer useful or no longer successful. To be “fed up” means to be tired or frustrated, unhappy, perhaps even bored with a situation. If you are waiting in line for one hour in order to talk to the manager of a store, you might get “fed up,” you might get frustrated.
Bella says, to Russell, what did your brother do in his mid-life crisis? Russell does not want to tell Bella. He says, “Well, he’s probably not a good example of what your husband would do” – he did something different than what your husband would probably do. Bella then uses a common idiom, “Don’t beat around the bush” (bush). To “beat around the bush” means to be indirect, to hesitate, not to say something directly but try to, we might also say, “talk around it” rather than directly about it: “Don’t beat around the bush.”
Russell says, “Well, if you must know,” meaning if you insist, if you really want me to tell you, even though you might not like it I will tell you. Russell says his brother “got a divorce,” which is the legal of a marriage, when a man and a woman are legally no longer husband and wife. He “married a woman half his age,” that’s something that men in their mid-life crises sometimes do, I hear, and he “tried to start a rock band.”
Bella says, “Oh, no! That’s just what I was afraid of.” Russell says, “I’m sure that won’t happen with your husband,” meaning your husband will be different. “You two have a great marriage.” Bella says, “I thought so, too, but you never know.” “You never know” is a phrase that means anything is possible, anything can happen. You never know, I might decide to take up football and become a football player here in the U.S. – you never know!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Bella: I think my husband is going through a mid-life crisis.
Russell: What makes you think that?
Bella: He just traded in his car for a very expensive sports car, and he’s filling the house with gym equipment.
Russell: Uh oh, that’s a bad sign. Do you know what may have triggered this?
Bella: I’m not sure, but he was passed over for a promotion at work a couple of months ago, and his new boss is 15 years younger than he is.
Russell: That would do it.
Bella: What really worries me is that he’s been talking about quitting his job altogether and becoming a full-time writer. He always wanted to become a successful writer.
Russell: That’s sounds familiar. When my brother went through a mid-life crisis, he spent a lot of time reflecting on his life and regretting giving up music to get a full-time job. He saw himself as being washed up and he was fed up with everything.
Bella: What did he do?
Russell: Well, he’s probably not a good example of what your husband would do.
Bella: Don’t beat around the bush. Just tell me.
Russell: Well, if you must know, he got a divorce, married a woman half his age, and tried to start a rock band.
Bella: Oh, no! That’s just what I was afraid of.
Russell: I’m sure that won’t happen with your husband. You two have a great marriage.
Bella: I thought so, too, but you never know.
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan – not going through a mid-life crisis! Thanks for listening. Come back and listen again next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
mid-life crisis – a period in a man’s life when he becomes unhappy that he is growing older and does strange things to try to feel younger
* When Brett went through his mid-life crisis, he bought a red Ferrari and tried to date women who were half his age.
to trade in – to exchange one thing (especially a car) for another thing
* Mindy traded in her old car for a $3,500 credit against the more expensive one that she wanted to buy.
sports car – a small car with a powerful engine that moves very quickly
* We went to the car show last weekend and saw some new sports cars to be released next year.
gym equipment – machines that one can use for exercise, either for aerobic/cardiovascular activities or for lifting weights
* Jake’s favorite piece of gym equipment is the treadmill because it lets him see how quickly he is running.
sign – something that shows what may happen in the future; an indication; a signal
* There was a big storm during the wedding, and some of the people saw it as a sign that the marriage will have bad luck in the future.
to trigger – to start something; to make something happen; to instigate something
* Many wars are triggered by small misunderstandings.
to be passed over for (something) – to not receive something (especially a promotion) that one expected, because it was given to someone who is less deserving
* Walter became very angry when he was passed over for the president’s position and it was given to someone who had worked at the company for only six months.
altogether – entirely; completely
* Thalia became so worried about the bad news on TV everyday that she decided to stop watching the news altogether.
to reflect on (something) – to think about something in a lot of detail; to think about something very carefully
* Gregory spends a lot of time reflecting on the meaning of his life.
to regret – to feel sad that one did or didn’t do something in the past; to feel sad about something that one did or didn’t do earlier in one’s life
* I regret that I didn’t tell my grandfather I loved him more often before he died.
washed up – used; no longer useful or strong; no longer successful; without potential for future success
* Many professional models feel that they are washed up by the time they’re 30 years old, and they have to start another career.
fed up – tired, frustrated, unhappy, and bored with a situation
* Vance is fed up with everyone asking him when he’s going to finish writing his book.
to beat around the bush – to be indirect; to delay or hesitate; to not say something directly
* Zoila felt uncomfortable asking Ulysses to pay back the money, so she started beating around the bush by first asking him about his family and his health.
if you must know – if you insist; a phrase used to show that one does not really want to say something, but will do so because the other person really wants to hear it
* I don’t normally talk about this, but if you must know, Theo and I are having problems in our marriage.
divorce – the legal end of a marriage
* Do you know what percentage of U.S. marriages end in divorce?
you never know – a phrase used to mean that anything is possible, or anything can happen
* Jessie always buys a lottery ticket because even though it’s unlikely that he’ll win, you never know.
Comprehension Questions
1. Which of these is not part of Bella’s husband’s mid-life crisis?
a) He bought a new car.
b) He wants to quit his job.
c) He’s starting a rock band.
2. What does it mean for Russell’s brother to feel washed up and fed up?
a) He was bathing and eating too much.
b) He was tired and frustrated with his life.
c) He was ready to get a divorce.
Answers at bottom.
What Else Does It Mean?
to be passed over
The phrase “to be passed over,” in this podcast, means to not receive something (especially a promotion) that one expected, because it is given to someone who is less deserving: “Randy decided to quit his job after he was passed over for the Sales Manager position.” The phrase “to pass away” is a polite way of saying “to die”: “His grandma passed away in 1994.” The phrase “to pass (something) down” means to give something to one’s children, grandchildren, or other young people so that they will continue to know or do something after one has died: “Gilda passed down her secret family recipes to her grandchildren.” Finally, the phrase “to pass (something) out” means to distribute something, or to have many things and to give one to each person: “The teacher asked the children to close their books, and then he passed out the tests.”
reflect
In this podcast, the verb “to reflect on (something)” means to think about something very carefully: “Beti took away her son’s toys and told him to reflect on what he had done and why it was bad.” The verb “to reflect” also means for a surface to show the image of something that is placed in front of it: “The mirror reflects light from the window and makes the room seem bigger.” Or, “The mountains are reflected in the water in the lake.” The verb “to reflect” can also mean for a surface to send back light, heat, or noise: “When the girls laughed loudly in the canyon, their voices were reflected back from the rock walls.” Finally, the verb “to reflect” can mean to show one’s opinion or thoughts: “Leslie didn’t like the movie, and her displeasure was reflected in the expression on her face.”
Culture Note
A “camp” is an experience where one stays in another place for a period of time, often outdoors. Many people participate in “summer camps” when they are children. Today, however, there are many types of “fantasy camps” that are “aimed at” (created for) adults. A “fantasy camp” is an opportunity to pretend that one is something one is not for a short period of time.
Many popular fantasy camps are related to sports. For example, at a basketball fantasy camp, people can play basketball with famous “NBA” (National Basketball Association) players and learn how to play better.
Music-related fantasy camps are also very popular. Many people regret that they didn’t “pursue” (try to get) a career in music. When they are older, sometimes they go to a “rock ‘n roll fantasy camp,” where they can play rock ‘n roll music with famous rock ‘n roll musicians. The camps usually “culminate” (end in an important way) with a rock ‘n roll concert for the campers’ families and friends. There are “jazz fantasy camps” and “country music fantasy camps,” too.
Some people want to participate in more active fantasy camps. They can go to a fantasy camp to learn to ride a “bull” (a large, male cow), fly an airplane, or be a “bodyguard” (a person who protects the president or other rich and important people). There are even “poker fantasy camps” where people can learn to play “poker” (a card game where players bet money on winning) from professionals and try to improve their skills.
The idea behind all of these fantasy camps is that campers can pretend to be someone else for a short period of time before returning to their regular lives.
Comprehension Answers
1 - c
2 - b