= 0340
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 340: Office Competition.
This is English as a Second Language Podcast episode 340. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. If you go there, you can download an 8 to 10 page Learning Guide that contains all of the vocabulary, sample sentences, additional definitions that we don’t discuss on the podcast, cultural notes, comprehension questions, and a complete transcript of everything we say on this episode.
This episode is called “Office Competition.” We’re going to listen to a story that uses a lot of vocabulary you might find in discussing a competition, or a contest, or when one person tries to do better than someone else. Let’s get started.
[start of story]
Okay, everybody. Listen up. We’re approaching the end of the month. Unless you’re new here, you know that we are in competition with our rival, the East Coast office, to have the most sales this period.
At the beginning of the month, we pulled ahead and it looked like we were finally going to turn the tables and defeat the East Coast office. But after the first 10 days of this month, we fell into a tie with them, and as of last Friday, we are still neck and neck.
We’re now coming up to crunch time and the last thing we want is to fall behind when it looks like we may be able to top the East Coast office for the first time in two years. I’m really proud of this office for outdoing itself to get us in a position to win, and there’s no reason we should suffer another loss now.
Okay, everybody, let’s put our noses to the grindstone and pull out this victory!
[end of story]
Our story begins by the boss, who is speaking here, saying to everyone “Okay, everybody,” he’s getting their attention. He’s getting them to stop talking perhaps, and listen to him. He then says, “Listen up.” “To listen up” is an informal way of telling people to pay attention, to listen to what you have to say. It’s something you would only do if you knew the people very well. You wouldn’t say to your boss, “Listen up boss!” Your boss, however, could use it with you. So, it’s an informal expression that we use to mean pay attention, listen to me.
He says, “We’re approaching the end of the month. Unless you’re new here (meaning unless you haven’t been working here very long), you know that we are in competition with our rival, the East Coast office.” “To be in competition” means that you are two teams – or two groups, or two people – who are trying to be the best, who are trying to be the most successful. A game such as American football, or baseball, or soccer are competitions; there are two groups of people, both of whom want to win. “To be in competition” means you are competing with someone else; the verb is “to compete.” Your “rival” (rival) is a person or a team against whom you are competing; it’s the other team. Here in Los Angeles, we have two large universities: the University of Southern California (USC) and the University of California at Los Angeles (UCLA). Those two teams – those two schools are rivals. I went to USC, so of course, I think USC is better.
These two offices – the East Coast office, the East Coast is the eastern part of the United States. Places like New York, Boston, Washington D.C., Philadelphia are on the East Coast. This office is probably on the West Coast – San Francisco, Seattle, Los Angeles, San Diego are some cities on the West Coast.
“At the beginning of the month,” he says, “we pulled ahead.” “To pull ahead” is a phrasal verb – a two-word verb – meaning to begin to do better than another team or another person in a competition. So, two teams are playing each other and one team scores a goal and the score is one to nothing, that team has “pulled ahead.” They have gotten a better score so they are leading – they are winning.
“It looked like we were finally going to turn the tables and defeat the East Coast office,” he says. “To turn the tables” is an idiom – an expression – that means to reverse positions in a competition. For example, if USC is playing UCLA in soccer and UCLA scores the first goal, then USC scores two goals, USC has turned the tables on UCLA. Now they are winning, whereas before, UCLA was winning. Well, in this case they want to “turn the tables and defeat the East Coast office.” “To defeat” means to win over another person. We also say, “to beat” another person: “USC beat UCLA” – they defeated them.
“After the first 10 days of the month,” however, “we fell into a tie with them.” “To fall into something” is to move into a different position, even if you didn’t plan it. Sometimes we say, “I fell into some money.” I wasn’t planning on finding $100, or I wasn’t planning or expecting my brother to give me $1,000, but he did: “I fell into some money,” or, “I came into some money.” Well here, they fall “into a tie” (tie). A “tie” is when two teams have the same score. So, USC is leading UCLA two to one in soccer, and then UCLA scores another goal and now it’s two to two; they’re tied. The word “tie” has several different meanings in English; take a look at our Learning Guide for some additional explanations.
The story continues that “as of last Friday (meaning on Friday – last Friday), we are still neck and neck.” The idiom “neck and neck,” like the neck on your body that connects your head to the rest of your body – at least for most people! “To be neck and neck” means to be in a very close competition; the game is very close – the scores are very close. So, in our game between USC and UCLA, it’s two to two – they’re “neck and neck.”
The story continues: “We’re now coming up to crunch time.” The expression “crunch (crunch) time” refers to a period of time immediately before a project is due or something is coming to an end; everyone has to work very hard. If you’re a student and you have a test in two hours, you need to study a lot in the next two hours; that would be “crunch time,” an important time before a certain event is about to end. He continues, “the last thing we want (meaning something that we do not want) is to fall behind.” “To fall behind” is a phrasal verb meaning to lose your winning position, to allow the other team to get a score that is higher than yours. So in our game, if UCLA scores a goal, USC “falls behind.” They lose their winning position, or their tied position, and now the other team seems to be winning. Don’t worry; the game isn’t over yet!
Well, the last thing they want “is to fall behind when it looks like we may be able to top the East Coast office for the first time in two years.” “To top” is another expression meaning to defeat, to beat, to win over another team or your rival. Two companies may compete against each other, and one company may try to top the other – to do better than the other. You have to be careful, however, that you are still following the law. In the culture note for today’s podcast, we talk about laws – business laws called “anti-trust laws.” Take a look at our Learning Guide for some more explanations of those.
Well, in this competition, the East Coast and the West Coast office are competing. The boss says, “I’m really proud of this office for outdoing itself to get us in a position to win” – to get us close to winning. “To outdo yourself” means to perform better than anyone else, to perform better than you, yourself, did previously. So, “outdoing yourself” means the office sold $1,000 last week; this week, they sell $2,000. They “outdid themselves,” they did better than they had in the past.
“There’s no reason,” the boss says, “we should suffer another loss now.” “To suffer a loss” means to lose; it’s the same as to lose. So, USC scores two more goals and beats UCLA, UCLA “suffers a loss.” That’s usually happens when USC plays UCLA!
At the end of the story, he says, “Okay, everybody, let’s put our noses to the grindstone and pull out this victory!” The idiom “to put your nose to the grindstone” means to work very hard at something, to really concentrate, really focus and work hard to accomplish something. They need to put their “noses to the grindstone and pull out (or accomplish – manage) this victory.” “Victory” is another word for success; when you win, you have a “victory.”
Now let’s listen to the story, this time at a normal speed.
[start of story]
Okay, everybody. Listen up. We’re approaching the end of the month. Unless you’re new here, you know that we are in competition with our rival, the East Coast office, to have the most sales this period.
At the beginning of the month, we pulled ahead and it looked like we were finally going to turn the tables and defeat the East Coast office. But after the first 10 days of this month, we fell into a tie with them, and as of last Friday, we are still neck and neck.
We’re now coming up to crunch time and the last thing we want is to fall behind when it looks like we may be able to top the East Coast office for the first time in two years. I’m really proud of this office for outdoing itself to get us in a position to win, and there’s no reason we should suffer another loss now.
Okay, everybody, let’s put our noses to the grindstone and pull out this victory!
[end of story]
Dr. Lucy Tse outdid herself by writing this script. Thank you Lucy!
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
listen up – an informal phrase used to get people to pay attention and listen to what one has to say
* Listen up! I’m going to explain the rules of the game.
competition – an event where people try to win by getting the best or highest score, usually in sports or school
* Their choir is singing at a music competition this weekend.
rival – a person or team against whom one is competing; a person or team who wants to win the same honor or prize that one wants to win
* Our rivals are very talented, but they don’t have very much experience, so I think we can win.
to pull ahead – to begin to do better than another team or person in a competition
* For the first mile of the race, Miguel was in fifth place, but in the second mile he pulled ahead of the other runners and now he is in the leading position!
to turn the tables – to reverse positions in a competition, so that the team or person that was losing becomes the team or person that is winning
* It would really turn the tables if that team won the tournament because it hasn’t won in more than 20 years!
to defeat – to beat; to win over another team or person in a competition or war
* Our soccer team defeated the city’s best team for the first time in 10 years.
tie – a moment when two teams or competitors have the same number of points, so that there is not a winner or loser
* The first game ended in a tie, so they decided to play again.
neck and neck – in very close competition; with very similar scores in a competition
* The two horses were neck and neck and no one knew which one would win the race.
crunch time – an important period of time immediately before a project has to be finished, when everyone needs to work very hard
* The week before final exams is crunch time for all the university students.
to fall behind – to lose one’s winning position; to allow another team or competitor to get a score that is higher than one’s own
* Claude was winning the bicycle race, but he fell behind when he had to stop to change his bicycle tire.
to top – to beat; to win over another team or competitor; to have a higher score than another team or competitor
* Joel topped all the other students by getting perfect grades in all his classes.
to outdo (oneself) – to perform better than anyone else; to do better than anyone else; to work extremely hard, more than anyone expected
* Grandma outdid herself by cooking a huge, delicious Thanksgiving dinner for everyone in the family.
to suffer a loss – to lose
* The team practiced every day for hours, because the players were determined not to suffer another loss.
to put (one’s) nose to the grindstone – to work very hard at something
* The new lawyer is putting his nose to the grindstone, working more than 14 hours every day.
victory – win; success in a game or competition
* The new president celebrated her election victory at a big party with family and friends.
Comprehension Questions
1. Why does he want to turn the tables?
a) Because they’ll be able to sell more tables if they’re turned.
b) Because turning the tables will increase sales.
c) Because he wants to finally beat the other office.
2. What is crunch time?
a) The time near the end of the competition.
b) The time when everyone eats crunchy food.
c) The time when fall leaves crunch on the ground.
Answers at bottom.
What Else Does It Mean?
tie
The word “tie,” in this podcast, means a moment when two teams or competitors have the same number of points, so that there is not a winner or loser: “There was a tie between two students, so the school is going to vote for its class president again.” A “tie” is also a long, colored piece of fabric that men wear around their necks so that it hangs in front of their shirts: “Do you think this shirt and suit would look better with a blue tie or a red tie?” A “tie” is often a connection between people, ideas, or places: “They have close ties with their cousins in Luxembourg.” Finally, a “tie” can be a small piece of string, rope, plastic, or wire that is used to close a bag: “The tie on this bag is really tight and I can’t open it.”
to fall behind
In this podcast, the phrase “to fall behind” means to lose one’s winning position, or to allow another team or competitor to get a score that is higher than one’s own: “The radio station fell behind its competitors in terms of the number of listeners that it has.” The phrase “to fall behind schedule” means to be delayed so that one will no longer be able to finish a project on time: “The construction project fell behind schedule due to bad weather.” The phrase “to fall back on (something)” means to use something for help, or ask someone for help, in a difficult situation: “If I can’t find a job as an accountant, I can always fall back on my secretarial skills.” Finally, the phrase “to fall for (something)” means to believe something that isn’t true: “Do you think anyone will fall for that silly story?”
Culture Note
The United States has many laws against businesses that do not compete “fairly” (in a way that is open to other businesses and not secretive). Specifically, there are many “antitrust laws” that “prevent” (do not allow) businesses to form “trusts,” where businesses “illegally” (against the law) work together to “minimize” (make something as small as possible) competition.
In the U.S., many people believe that free competition is important because it means lower prices and greater “selection” (variety of products and services) for “consumers” (people who buy products and services). When companies illegally create a trust, they become a “monopoly” (a business that is the only business offering a particular product or service) and are able to “charge” (ask for a specific price when selling something) as much as it wants. Monopolies often offer products and services with very low quality for very high prices.
U.S. antitrust laws “prohibit” (do not allow) “price fixing,” where different companies agree to charge the same price for their products and services. Antitrust law also prohibits “market allocation,” where different companies agree to sell their products and services only in a certain area, so that there is no competition among the companies. “Monopolization” (an effort to become a monopoly) is also not allowed, so the laws try to prevent companies from buying all of their competitors.
All of these antitrust laws were created to help the economy be as “efficient” (good at doing something quickly and inexpensively) as possible. By “maximizing” (making something as big as possible) competition, consumers have the largest number of buying choices at the lowest possible prices, and companies are “motivated” (want to do something) to make and sell the products and services that consumers want to buy.
Comprehension Answers
1 - c
2 - a