= 0350
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 350: A Movie Review.
This is English as a Second Language Podcast episode 350. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. That 8 to 10 page guide contains much information to help you improve your English even faster, including a complete transcript of this episode.
This episode is called “A Movie Review.” It’s a conversation between Sally and Marcus about a new, exciting movie that they saw. It includes a lot of vocabulary that you might read or hear about in a movie review. Let’s get started.
[start of dialogue]
Sally: Did you see the new movie, The McQuillan Story? I’m writing a movie review for the school paper.
Marcus: I went to the premiere last week. What did you think of it?
Sally: I liked it. I thought it was entertaining, although it wasn’t groundbreaking, by any means.
Marcus: You thought it was entertaining? I thought it was awful. I almost walked out. The acting was wooden and uninspired, and the direction was amateur.
Sally: Aren’t you being too critical? It was the director’s first movie and I thought his directorial debut wasn’t bad. If there was a problem, it was with the screenplay.
Marcus: Don’t get me started on the screenplay! The story was so predictable and the dialogue was pretentious. This movie is going to bomb for sure.
Sally: Oh, I don’t know. I think some people may enjoy it.
Marcus: If you want to do your readers a favor, you’d tell them to skip this movie and save their money!
[end of dialogue]
The dialogue begins with Sally saying to Marcus, “Did you see the new movie, The McQuillan Story?” Not a real movie, of course – although it should be! Sally says, “I’m writing a movie review for the school paper.” A “movie review” is an article in a newspaper or a magazine or a website, where someone gives their opinion about a movie – whether it was good or bad.
Marcus says, “I went to the premiere last week.” The “premiere” is the first time that a movie is shown to the public. In Los Angeles, there are many movies that have premieres. A few miles from where I live, there are movie theaters where the first time the movie is shown, in that particular theater, they have a big celebration outside of the theater. Usually in the premiere, the main actors – the stars of the movie – “show up,” they go to the premiere.
Sally said that she likes this movie. She said, “I thought it was entertaining, although it wasn’t groundbreaking, by any means.” She thought it was “entertaining,” meaning amusing – interesting, but it wasn’t “groundbreaking.” The adjective “groundbreaking” means new, or modern, or revolutionary – something completely different than how things were done in the past. She says “it wasn’t groundbreaking, by any means.” The expression “by any means” means at all – in any way. It has a couple of different meanings, this expression; take a look at our Learning Guide for some additional explanations.
Marcus said, “You thought it was entertaining?” meaning he doesn’t agree with her. “I thought it was awful” – it was terrible, it was horrible, it was very bad. Remember, Marcus is not very intelligent, however! He says, “I almost walked out.” “To walk out of something,” usually a movie or a play or some performance, means to leave the theater before it has ended, usually because it is so bad – it is not very good.
Marcus says, “The acting was wooden and uninspired, and the direction was amateur.” The “acting” is the way the actors talked and moved. When we say acting is “wooden” (wooden), we mean it’s without emotion. Another word we may use is “stiff,” when it’s not showing enough expression. When the actors are not showing enough emotion, that would be “wooden.” Marcus thought it was “wooden and uninspired.” “Uninspired” is the opposite of “inspired”; “uninspired” would mean dull, uninteresting, not exciting, not original. He says the direction for the movie “was amateur.” The “direction” is the actions that the director of the movie takes. The “director” is the person who tells the actors what to do and how to act, usually. Something that is “amateur” is something that is not professional; here, it means not very good.
Sally says, “Aren’t you being too critical?” “Critical,” here, means negative, always saying something bad about something. “Critical” has a couple of different meanings in English; take a look at the Learning Guide for some more explanation.
Sally continues, “It was the director’s first movie and I thought his directorial debut wasn’t bad.” “Directorial” is just an adjective from the word “director,” the person in charge of the movie, who’s telling people what to do in the movie. A “debut” (debut) is the first time that someone does something for the public – the first time you do something in front of other people if it’s a performance, for example. So, this is the first time the director has directed a movie; Sally thought it was pretty good.
“If there was a problem,” Sally says, “it was with the screenplay.” “Screenplay” (one word) is the script; it’s the words that are written down and the instructions that the writer of the movie has put on paper, and that the director uses and the actors use to “produce” – to make – the movie. Usually, the person who writes the screenplay is different than the person who is the director; sometimes it’s the same person. The joke here in Los Angeles is that everybody is writing a screenplay. When you go to the local cafés, you see people working on their laptop computers, and everyone seems to be writing a screenplay – including me!
Sally says that the problem was with the screenplay. Marcus says, “Don’t get me started on the screenplay,” meaning let’s not talk about that because I have even more negative things to say. When someone says “don’t get me started on (something),” they mean let’s not talk about it because I have bad things to say about it.
Marcus says, “The story was so predictable and the dialogue was pretentious.” Something that is “predictable” is something that you know is going to happen – it’s obvious, there aren’t any surprises in the movie. When we say something is “pretentious,” we mean that it’s trying to appear more important, or better, or bigger than it really is. It’s a negative adjective. When you say someone is “pretentious,” you are criticizing them; you are saying they’re trying to be more important than they really are.
Marcus says, “This movie is going to bomb for sure.” The verb “to bomb,” here, mean to fail – to be a disaster. In American English, we often use this to describe a movie or a play or a television show that is not successful – that does not do very well.
Marcus says, “If you want to do your readers a favor (meaning if you want to do something good for your readers Sally), you would tell them to skip this movie and save their money!” To “skip” something means to decide not to do something or see something. “I’m going to skip the news tonight” – I’m not going to watch it. Of course, if there were a movie called The McQuillan Story, it would probably be quite successful, so I think Marcus doesn’t really know what he’s talking about!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Sally: Did you see the new movie, The McQuillan Story? I’m writing a movie review for the school paper.
Marcus: I went to the premiere last week. What did you think of it?
Sally: I liked it. I thought it was entertaining, although it wasn’t groundbreaking, by any means.
Marcus: You thought it was entertaining? I thought it was awful. I almost walked out. The acting was wooden and uninspired, and the direction was amateur.
Sally: Aren’t you being too critical? It was the director’s first movie and I thought his directorial debut wasn’t bad. If there was a problem, it was with the screenplay.
Marcus: Don’t get me started on the screenplay! The story was so predictable and the dialogue was pretentious. This movie is going to bomb for sure.
Sally: Oh, I don’t know. I think some people may enjoy it.
Marcus: If you want to do your readers a favor, you’d tell them to skip this movie and save their money!
[end of dialogue]
The entertaining, groundbreaking, inspired script for this episode was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. We’ll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
movie review – an article in a newspaper, magazine, or website where the writer gives his or her opinion about whether a movie was good or bad
* According to the movie review, Planes, Trains, and Automobiles was a bad movie, but we thought it was really funny!
premiere – the first time that a movie or play is shown to the public
* The actors were nervous during the premiere, waiting to see how the audience would react.
entertaining – amusing and interesting; a good way to spend one’s time
* The professor tells a lot of jokes, so his classes are always interesting.
groundbreaking – new and modern; revolutionary; doing something differently than how things have been done in the past
* His groundbreaking research helped doctors develop a vaccine for polio.
by any means – at all; in any way
* The restaurant’s food isn’t gourmet by any means, but it is tasty and inexpensive.
awful – horrible; terrible; very bad
* They painted the store an awful orange color. It’s so ugly!
to walk out – to leave a movie, play, speech, or other performance before it has ended because it was very bad
* The play was terrible, so we walked out after the first scene.
acting – the way in which actors move their bodies and say their lines while performing
* The students’ acting was good, but their costumes were disappointing.
wooden – stiff; without emotion; not showing enough expression
* The criminal made wooden replies to the judge’s questions, not showing any emotion.
uninspired – dull; uninteresting; not exciting or interesting; not unique; not original
* Kaitlin eats an uninspired lunch of a ham sandwich and potato chips every day.
direction – leadership, especially in creating a movie or play; the instructions received from a movie or play director
* Steven Spielberg has received many awards for his exceptional direction in making movies.
amateur – not professional; not skilled
* She was an amateur ice skater for six years before she decided to go professional.
critical – negative and harsh; always saying something negative about something or someone
* My wife is so critical! No matter what I do, it’s never good enough for her.
debut – the first time that one does something for the public; the first time that one does something in front of other people
* His acting debut was in a soap commercial, but now he is a famous actor who has been in many movies and popular TV shows.
screenplay – script; the written words and instructions for making a movie
* Terrence wrote a screenplay about two men who rob a bank and then try to escape to Canada.
predictable – obvious; easy to know what is going to happen; without any surprises
* A good mystery novel should not be predictable. The reader should be surprised by the ending.
pretentious – trying to appear more important, better, or bigger than something really is
* Renaldo is so pretentious, always acting like he has more money and a better job than he really does.
to bomb – to fail; to be a disaster; to be a total failure
* Jackie bombed on the exam, getting only 14 out of 100 points.
to skip – to decide not to do, have, or see something
* Because they are both trying to lose weight, they decided to skip the ice cream after dinner and eat fruit salad instead.
Comprehension Questions
1. How would Sally describe the movie?
a) New and innovative.
b) Interesting and amusing.
c) Dull and with bad acting.
2. What does Marcus mean by saying, “The movie is going to bomb for sure”?
a) The movie has many exciting explosions.
b) The movie is going to be very popular.
c) The movie is going to fail very badly.
Answers at bottom.
What Else Does It Mean?
by any means
The phrase “by any means,” in this podcast, means at all or in any way: “Sharini isn’t a great guitar player by any means, but she enjoys playing and practicing.” The phrase “by all means” is used to invite someone to do something, or to show that one has no objection to one doing something: “May I help you get dinner ready?” – “Yes, please, by all means.” The phrase “by means of (something)” means with the use or help of something: “They traveled to the San Juan Islands by means of a large boat.” Finally, the phrase “a means to an end” is used to talk about something that isn’t interesting or important by itself, but is used to get something else: “For him, studying is a means to an end, because even though he dislikes school, he wants to have a good career.”
critical
In this podcast, the word “critical” means negative and harsh, or saying something negative about something or someone: “Don’t be so critical of Trey’s artwork. After all, he’s only six years old.” The word “critical” can also mean crucial or extremely important: “The president made a critical decision to expand the company’s sales in the Western United States.” The phrase “critical condition” is used to talk about one’s health when one is in danger of dying: “After the accident, she was in critical condition for almost a month.” Finally, the phrase “critical thinking” means the ability to evaluate all the facts and create one’s own opinion about something: “The teacher is trying to develop her students’ critical thinking skills by asking them to share their opinion about the ideas in the book.”
Culture Note
Movie “marketing” (the ways in which companies try to get people to buy something) has become very “intense” (strong and powerful). When new movies are “released” (shared with the public), they are accompanied by many advertisements, “trailers” (short pieces of the movie that are shown to the public to get people interested in seeing the full movie), and “product promotions” where, for example, images from the movie are shown on cereal boxes, or toys based on movie characters are given away at restaurants.
Movie reviews can either help or “hinder” (make something difficult or impossible) these marketing efforts. Most newspapers and magazines contain movie reviews, or “film reviews” and many people read those reviews to decide whether they want to see a movie. A movie review usually “summarizes” (states the most important points of something) the “plot” (storyline, or what happens in a book or movie) of the movie. Then the “reviewer” (the person who writes a review) states his or her opinion about the movie, including the acting, direction, costumes, and more. Sometimes a reviewer highly recommends a movie, but other times he or she says that it is horrible.
“Film companies” (companies that make movies) often invite reviewers to see their movies for free before their public debut so that the newspapers publish a review before the movie’s premiere. However, if the film company doesn’t believe that it has “produced” (made) a very good movie, sometimes it will not invite reviewers to see it ahead of time. In this way, the film company tries to minimize the damage of a bad review.
Many individuals like to “post” (share information with the public) their own reviews online. As a result, people now have more “options” (choices) for learning about whether movies are good or bad before they see them.
Comprehension Answers
1 - a
2 - c