= 1009
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,009 – Basic Military Commands.
This is English as a Second Language Podcast episode 1,009. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download a Learning Guide for this episode. The Learning Guide contains a complete transcript of everything we say, in addition to vocabulary terms, definitions, cultural notes, and sample sentences.
This episode is a dialogue between Marta and Bruno about giving commands as you would in the military. Let’s get started.
[start of dialogue]
Marta: What’s going on out here? What’s all that noise?
Bruno: I’m putting the troops through their drills.
Marta: Troops?!
Bruno: Watch this. Hey, I didn’t tell you you could be at ease. Attention! Fall in. Forward, march!
Marta: That’s great, but . . .
Bruno: I’m not done. Let me show you what else these troops can do. Halt! About face!
Marta: Don’t you think that it’s time to . . .?
Bruno: March, march! Double time!
Child: Wah! [Child crying loudly.]
Marta: Come here. Did you fall down and hurt yourself? It’s okay. Everything’s going to be okay.
Bruno: Hey, there’s no crying in the military. Don’t coddle the troops, Marta.
Marta: Bruno, your twins are five years old. Don’t you think they’re a little too young to be going to boot camp?
Bruno: No, it’s never too young to instill discipline. Okay troops, fall in. Mark time! Now march, march, march . . .
[end of dialogue]
Marta begins our dialogue by saying to Bruno, “What’s going on out here?” “What’s going on” means what’s happening. “Out here” usually would be used when we are talking about something outside of a building or outside of a house. Marta asks, “What’s all that noise?” Bruno says, “I’m putting the troops through their drills.” “Troops” (troops) are soldiers – an organized group of soldiers or organized groups of soldiers. “Drills” (drills) are exercises, things that you do over and over again to prepare you for something.
We might talk about drills, for example, in school when math teachers are trying to teach their students how to multiply numbers. They may give them exercises, and we may call those exercises “drills.” Bruno says that he’s “putting the troops through their drills,” meaning he’s making these soldiers do these exercises – and usually when we talk about military drills, we’re talking about physical activity, physical exercises.
Marta is very surprised by what Bruno is saying. She says, “Troops?” She’s asking a question, but is also clearly shocked, clearly surprised. Bruno says, “Watch this,” meaning pay attention and look at this. “Hey, I didn’t tell you you could be at ease. Attention! Fall in. Forward, march!” Bruno uses some common military terms here. He’s talking to Marta and telling Marta to watch what he is doing with his troops.
He then says to one of the (what we believe are) soldiers, “at ease.” “At ease” (ease) means to be relaxed, to be in a comfortable position. In the military, “at ease” is a command telling you that you don’t have to stand at attention. “To stand at attention” is to usually stand up straight and be very still, whereas “at ease” often is a position that you would take by putting your legs, say, one or two feet apart from each other – a more relaxed position, in other words.
But Bruno doesn’t want his troops to be at ease. He says, “Attention!” The word “attention,” when used in a classroom by a teacher, means that everyone needs to focus, everyone needs to pay attention. In the military, especially when the word is said the way I said it – the way Bruno said it – it means that you are to stand in a very formal position. You must stand up straight. That is to be “at attention.” It’s a sign of respect for your superior officer.
In the military, there is a certain hierarchy – that is, you have people who are in charge of other people. And so, if you are in the presence of someone who is at a higher level – what they would call a higher “rank” (rank) – then you must stand at attention, or least in certain situations you must stand at attention. Here, Bruno is telling his soldiers to stand at attention. Then he says, “Fall in.” “To fall in” means to take your place in line, the place where you’re supposed to be. Usually it is said before the troops begin to walk in an organized manner.
Walking in a certain organized way, walking in a certain pattern, is called “marching.” We use the verb “to march” (march) to mean to walk forward in a very organized – I guess what we may call “military” – way. If you’ve seen soldiers who are all walking down the street in a line, such as in a parade, then you know what marching is. “Forward, march” means to walk forward, to go forward. “Forward, march” is used to tell the soldiers that they should now start walking. Bruno is telling his soldiers to march.
Marta says, “That’s great, but . . .” Bruno then interrupts her and says, “I’m not done,” meaning I’m not finished. He says, “Let me show you what else these troops can do.” He then turns and talks to his troops. “Halt! About face!” “Halt” (halt) is a command meaning stop, especially when you’re talking to a soldier who is walking. If you tell someone to halt, you’re telling him or her to stop walking, to stop moving. Outside of the military, you won’t hear this word used very much anymore.
There’s an old expression, “Halt! Who goes there?” “Who goes there?” means “Who is there?” If it’s dark outside and you can’t see the face of the person who is walking toward you and you are afraid, you might say, “Halt! Who goes there?” Well, you actually wouldn’t say that anymore. It’s kind of an old-fashioned expression. “Halt” is used mainly now just in the military, and that’s the way Bruno is using it in our dialogue.
He says to his troops, “Halt!” – meaning stop walking – “About face.” “About face” means to turn around. If you are walking east, “about face” would be to turn around toward the west. It means to move 180 degrees from where you are now so that you are now facing or looking toward the opposite direction. Marta says, “Don’t you think it’s time to . . .?” She’s asking Bruno a question, but Bruno isn’t listening. He’s still talking to his troops.
He says, “March, march! Double time!” “Double time” is a phrase used in the military to mean “Walk twice as fast as you’re walking right now.” “Double time” means to do something twice as quickly as you would normally do it. Then we hear a child crying – who sounds a lot like me, actually. Marta then says, apparently to this child, “Come here. Did you fall down and hurt yourself? It’s okay. Everything is going to be okay.” Marta is talking to this child and asking if the child fell down and hurt himself. Then she says, “It’s okay,” and she tries to comfort the child – she tries to make the child feel better.
Bruno says, “Hey, there’s no crying in the military.” The “military” refers to the army, the navy, and the other, what we would call, “armed forces” for a given country. Bruno says, “Don’t coddle the troops, Marta.” “To coddle” (coddle) means to treat someone too kindly or too gently, especially when we’re talking about children. Bruno doesn’t want Marta to coddle his troops. Marta says, “Bruno, your twins are five years old.” Now we discover that these troops that Bruno has been ordering around are, in fact, his five-year-old children.
Marta says, “Don’t you think they’re a little too young to be going to boot camp?” “Boot (boot) camp” is typically where you go when you first join the military. It’s a place for getting you ready to be part of the army or the navy or the Marine Corps or whatever military service you’re joining. Boot camp is usually a very difficult period where you must do a lot of physical activities in order to get strong enough to be part of the military. Boot camp is also a place where you learn military discipline, and that’s what Bruno is interested in.
He says, “No, it’s never too young to instill discipline.” “Discipline” (discipline) is the practice of following some set of rules, some set of regulations or guidelines for behavior. “To instill (instill) discipline” means to train or to teach someone to follow these rules, these guidelines. Bruno says, “It’s never too young to instill discipline.” He means that even though his children are only five years old, they are old enough to learn this discipline.
Then he says to his troops. “Okay troops, fall in. Mark time! Now, march, march, march . . .” “To mark time” means to march without walking. So, what you’re doing is you’re walking in place. You’re lifting your legs up as though you were walking, but you’re not actually moving forward. That’s “marking time.” Again, it’s a command, an order, that you would hear in the military.
We may also use this expression “He’s marking time” to mean that he’s not really doing anything. He’s sort of wasting his time or he’s spending his time waiting for something to end – waiting, perhaps, for something more important to happen.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Marta: What’s going on out here? What’s all that noise?
Bruno: I’m putting the troops through their drills.
Marta: Troops?!
Bruno: Watch this. Hey, I didn’t tell you you could be at ease. Attention! Fall in. Forward, march!
Marta: That’s great, but . . .
Bruno: I’m not done. Let me show you what else these troops can do. Halt! About face!
Marta: Don’t you think that it’s time to . . .?
Bruno: March, march! Double time!
Child: Wah! [Child crying loudly.]
Marta: Come here. Did you fall down and hurt yourself? It’s okay. Everything’s going to be okay.
Bruno: Hey, there’s no crying in the military. Don’t coddle the troops, Marta.
Marta: Bruno, your twins are five years old. Don’t you think they’re a little too young to be going to boot camp?
Bruno: No, it’s never too young to instill discipline. Okay troops, fall in. Mark time! Now march, march, march . . .
[end of dialogue]
Our scriptwriter is never just marking time. She’s always working hard at writing the best scripts on the Internet. Thank you, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
troops – soldiers; organized groups of soldiers
* How many troops are actively fighting in the war?
drill – an exercise; something that is practiced repeatedly so that one is prepared for what might happen in a real event
* The students participate in fire drills at least once each semester.
at ease – relaxed; in a comfortable position
* You can be at ease during the presentation, but don’t slouch. Good posture is important for making a good impression.
attention – a phrase used to make other people focus on what one is doing and saying, ignoring other distractions
* Attention! I have an important announcement.
to fall in – to join a group or a line, especially a group of people who are moving in an organized way
* The hardest part of marching band is getting all the musicians to fall in at the same time.
forward, march – a phrase used to tell people to begin walking forward in a slow, steady way, especially when talking to soldiers
* We still have miles to go before we set up camp tonight. Forward, march!
to halt – to stop moving; to hold still
* We were jogging down the trail when all of a sudden someone called out, “Halt!”
about face – a phrase used to tell someone to turn around, especially in the military
* Bow to your dance partner. Now about face! Bow to the person on the other side of you.
double time – a phrase used to tell someone to do something twice as quickly as he or she was doing it before, especially when referring to how quickly someone in the military is moving
* We’re going to have to work double time to complete that big factory order.
military – the armed forces; the people and organizations that work together to defend a country and use force to promote its interests; the army, navy, air force, marines, coast guard, and other parts of a country’s security forces
* Is military service mandatory in your country?
to coddle – to treat too kindly or too gently, especially when talking about a child; to spoil someone
* If you coddle her every time she falls down and cries, she’ll never learn to be strong and resilient.
boot camp – military recruit training; a period of time when new members of the military receive basic training focused on physical strength and endurance, and developing skills needed to be a soldier
* By the end of boot camp, you’ll be able to hike for miles with a 100-pound backpack in tropical heat.
to instill discipline – to teach and train someone to obey and do what one is told without questioning it or rebelling against the person in charge
* What’s the best way to instill discipline in teenagers while still teaching them that their opinions are important?
to mark time – to march in one place, lifting one’s feet and legs repeatedly, but without moving forward
* Once the helicopter lands, the soldiers will mark time until the President reaches the stage.
Comprehension Questions
1. Which of these commands would make people move?
a) Halt!
b) Double time!
c) Mark time!
2. What would you expect to learn in boot camp?
a) How to tie your shoes.
b) How to make boots.
c) How to serve in the military.
Answers at bottom.
What Else Does It Mean?
drill
The word “drill,” in this podcast, means an exercise, or something that is practiced repeatedly so that one is prepared for what might happen in a real event: “During the earthquake drill, people are supposed to hide underneath their desks.” When talking about teaching, a “drill” is a technique that teachers use by having students repeat something many times in order to learn it: “These spelling drills are boring and not very effective.” When talking about tools, a “drill” is a machine that makes a hole in a hard surface: “Try to drill a small hole in the board before you pound the nail in.” Or, “The sound of the dentist’s drill made the patient extremely nervous.” Finally, the phrase “the drill” refers to how things are normally done: “By the end of your first week on the job, you’ll know the drill around here.”
about face
In this podcast, the phrase “about face” is used to tell someone to turn around, especially in the military: “About face! It’s time for inspection.” Outside of the military, an “about-face” is a complete change in one’s opinion or position on something: “Everyone was surprised when the politician made an about-face on the controversial policy.” The phrase “to keep a straight face” means to control oneself and not laugh even though something is very funny: “How could you possibly keep a straight face while she was telling that joke?” Finally, the phrase “on the face of it” means superficially, or as something appears, but not necessarily as it really is: “On the face of it, they seem to have our best interests at heart.”
Culture Note
Boot Camp
In the United States, the Army is “notorious” (famous in a bad way; famous for something bad) for the “excruciating” (very difficult and painful) boot camp that “recruits” (people who have recently joined an organization) must “go through” (complete; finish). The basic boot camp lasts for 10 weeks and “comprises” (is made up of; has) three phases.
During the first phase, the recruits’ actions are monitored and “aggressively” (with a lot of energy and strength) corrected by “drill sergeants” (an employee of the military who trains recruits). The first week is often called “Hell Week” because it is so “miserable” (extremely unpleasant). During this phrase, the recruits spend a lot of time marching, doing “push-ups” (exercises in which one lies on the floor and pushes one’s body up with the strength of one’s arms), and saying, “Yes, Sir!”
During the second phase, recruits begin “firing” (shooting) guns and learning to use other “weapons” (objects used to hurt or kill others), such as “grenades” (weapons that are thrown by hand and “detonate” (explode) “on impact” (when they hit something)). The recruits also have to learn to complete an “obstacle course” (a series of things that one must go over, under, or around) within a limited amount of time.
Finally, in the third phase, the recruits must pass tests of their physical training, proving that they have “sufficient” (enough) strength and “endurance” (the ability to do things over a long period of time). The recruits also participate in longer “simulations” (exercises that make people feel as if they are in an actual fighting situation).
Comprehension Answers
1 - b
2 - c