= 1031
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,031 – Following a High-Profile Court Case.
This is English as a Second Language Podcast episode 1,031. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Education Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Download a Learning Guide for this episode. Our Learning Guides contain complete transcripts of everything we say on the episode, in addition to vocabulary, sample sentences, cultural notes, and a whole lot more. Go to our website for more information. If you’re on Facebook, you can like us on Facebook. Go to facebook.com/eslpod.
This episode is a dialogue between Danny and Carol about what’s called a “court case,” a legal action involving a judge and lawyers. Sounds like fun. Sounds expensive. Let’s get started.
[start of dialogue]
Danny: Have you been following the Schirru case?
Carol: Yeah, I have. I think he’s guilty.
Danny: You’re kidding, right? He’s innocent and this is a show trial. The district attorney is conducting a witch-hunt for his own political ambitions.
Carol: No, he’s not. It is a high-profile case, but that’s only because he wants to make an example of Schirru. People like him should be off the streets. Putting him in jail sends a message to other criminals.
Danny: What kind of message?
Carol: The message that the government is cracking down.
Danny: I think it’s just grandstanding and Schirru is being made a sacrificial lamb.
Carol: You can believe what you like, but I think it’s great that the district attorney is taking a stand.
Danny: Yes, but he seems to be doing it at the expense of real justice.
Carol: Not from where I’m standing.
Danny: Then you need to find a new place to stand – preferably one without blind spots.
[end of dialogue]
Danny begins our dialogue by saying to Carol, “Have you been following the Schirru case?” Carol says, “Yeah, I have. I think he’s guilty.” If you say someone is “guilty” (guilty), you’re saying that they have done something wrong – that they have broken the law or perhaps broken some rule. Danny says, “You’re kidding, right?” meaning you’re joking. You’re not really serious.
“He’s innocent and this is a show trial.” To say someone is “innocent” (innocent) is to say that the person is not guilty, did not do the crime, did not break the law. So, “guilty” and “innocent” are the two possibilities if someone is arrested by the police and taken in front of the judge. The “judge,” of course, is the person, man or woman, who either decides someone is guilty or innocent, or more commonly runs the actual legal proceedings – runs what we would call the “trial.”
A “trial” (trial) is the actual event which involves the lawyers from the government and the lawyers from the defense getting together and arguing their case in front of a judge and typically in front of what’s called the “jury” (jury). A jury consists of six or, more commonly, 12 people who decide if a person is guilty or innocent of some criminal action.
Danny says that this is a “show trial.” A “show trial” would be one that is basically political. The government has already decided that this person is guilty and will be punished, but they have a trial just so it looks like they’re being fair. We usually associate this particular term with, for example, the show trials in the 1930s under Joseph Stalin in the former Soviet Union. But of course, the term could be used for any case in which the government has already made a decision, but wants people to think that the person is getting justice according to a fair legal proceeding.
Danny says, “The district attorney is conducting a witch-hunt for his own political ambitions.” In the United States, the district attorney is the government’s lawyer, usually the most important or the chief lawyer in any given area. The United States is broken up into different districts. In these districts, these regions or areas each have their own district attorney, and the district attorney is the government person, the government official, in charge of deciding who is going to get a trial and who isn’t.
The district attorney in the United States’ legal system has a lot of power to do a lot of different things, including deciding if someone is going to, we would use the expression, “stand trial,” meaning whether the person was going to have to go in front of a judge and a jury and defend himself. So, district attorneys are government attorneys who are responsible for representing the government in, in this case, a criminal trial.
Danny says that this trial is being conducted by a district attorney who’s on “a witch-hunt.” A “witch” (witch) is supposedly a woman who has magical powers. Someone who is “on a hunt” (hunt) is looking for something, often something to kill or something to catch, such as an animal. We talk about hunting deer or hunting cats. No, we don’t hunt cats, just kidding. The term “witch-hunt,” however, refers to the practice of looking for people to punish, not because they’ve done anything wrong, but because they are of a different opinion or act in a different way than you do.
The idea of a witch-hunt goes back, at least in the U.S., to the famous Salem witch trials, where several women were accused or were said to have been witches and were eventually arrested, and some of them killed. Nowadays, when someone talks about a witch-hunt, they’re usually talking about someone, especially the government, trying to find people who are guilty, even though they’re not really guilty.
A witch-hunt also has this notion of being politically motivated – that it is being done not for criminal reasons, if you will, but for political reasons. It’s not about a crime. It’s about politics and using criminal law, in this case, to promote a political position. Danny says the district attorney is doing this trial, conducting this witch-hunt, “for his own political ambitions.” Your “political ambitions” would be the things that you hope to accomplish in the world of politics. “Political ambition” refers to your desire to have a powerful career in politics.
Carol says, “No, he’s not,” meaning “No, the district attorney is not conducting a witch-hunt.” She says, “It’s a high-profile case.” The term “high-profile” (profile) means that it is getting a lot of attention. A lot of people are paying attention to it. It is in the news. It is in the newspaper. That would be something that is high-profile. A high-profile case would be a legal trial, a criminal trial, that a lot of people are paying attention to.
Carol says, “It’s a high-profile case, but that’s only because he,” meaning the district attorney, “wants to make an example of Schirru.” “To make an example of” someone is to make someone serve as a warning to other people. You may punish someone not necessarily because they’ve done something terribly wrong, but because you want other people to take this as a lesson – to see this as something that might happen to them if they’re not careful. So, making an example of someone is punishing one person to show the other people what will happen to them if they break the same rule or break the same law.
Carol says, “People like him,” now referring to Schirru, “should be off the streets,” meaning they should not be free. They should be in prison. “Putting him in jail” – in prison – “sends a message to other criminals,” she says. A “criminal” (criminal) is a person who has committed or done a crime, something against the law. Danny says, “What kind of message?”
Carol responds, “The message that the government is cracking down.” The phrasal verb “to crack (crack) down” is used when someone in authority, such as the government, decides to enforce the rules more strictly, decides that it is no longer going to let people break this law. So, if the police crack down on speeding in Los Angeles, they will start arresting more people. They will start giving more people penalties – “fines,” we would call them – if they drive too fast.
Danny says, “I think it’s just grandstanding.” “To grandstand” (grandstand) means to behave or to speak in a way that attracts attention, that other people pay attention to, in order to make yourself feel more important or more powerful. That’s what Danny says the district attorney is doing here.
Danny says, “Schirru is being made a sacrificial lamb.” A “sacrificial (sacrificial) lamb (lamb)” is a person who is put into a damaging position or harmed for the benefit of everyone else. A sacrificial lamb would be someone who is punished in order that everybody else is better off – in order to benefit other people.
Carol says, “You can believe what you like, but I think it’s great that the district attorney is taking a stand.” “To take a stand” (stand) is to tell people what your position is, what your opinion is, and not change it, not try to be persuaded by others. “To take a stand” is to decide that you are going to defend your position even if other people disagree with you.
Danny says, “Yes, but he” – the district attorney – “seems to be doing it at the expense of real justice.” If you do something “at the expense (expense) of” something else, you are causing harm to one thing in order to help another thing. Danny is saying that the district attorney is taking a stand, is giving his opinion, but at the expense of real justice. “Justice” (justice) here refers to fairness in the way people are treated, especially when we’re talking about the laws of a country or a place.
Carol says, “Not from where I’m standing.” This expression “from where I’m standing” is used to talk about your point of view, your perspective, your opinion about something. If someone says, “From where I’m standing, it sounds like a terrible idea,” the person is saying, “In my opinion,” from my perspective, “this is a bad idea.” Danny says, “Then you need to find a new place to stand, preferably one without blind spots.”
Danny is making sort of a joke here. He’s saying that Carol needs to have a new perspective, a new view of things, one that doesn’t have any “blind (blind) spots.” “Blind spots” are areas that you can’t see or that you can’t see clearly, often because there is something in your way preventing you from seeing it clearly. Here it’s used really to refer to someone who perhaps has certain biases or prejudices, and those biases don’t allow the person to see something accurately or fairly.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Danny: Have you been following the Schirru case?
Carol: Yeah, I have. I think he’s guilty.
Danny: You’re kidding, right? He’s innocent and this is a show trial. The district attorney is conducting a witch-hunt for his own political ambitions.
Carol: No, he’s not. It is a high-profile case, but that’s only because he wants to make an example of Schirru. People like him should be off the streets. Putting him in jail sends a message to other criminals.
Danny: What kind of message?
Carol: The message that the government is cracking down.
Danny: I think it’s just grandstanding and Schirru is being made a sacrificial lamb.
Carol: You can believe what you like, but I think it’s great that the district attorney is taking a stand.
Danny: Yes, but he seems to be doing it at the expense of real justice.
Carol: Not from where I’m standing.
Danny: Then you need to find a new place to stand – preferably one without blind spots.
[end of dialogue]
From where I’m standing, the best scriptwriter on the Internet is none other than our very own Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California. I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2014 by the Center for Educational Development.
Glossary
guilty – having committed a crime; not following the law; having broken one or more laws
* The judge found her guilty of robbery.
innocent – not having committed a crime; following the law; not having broken any laws
* He has been in prison for more than 10 years, but he still says that he’s innocent.
show trial – a legal trial that receives a lot of public attention, but is highly political, with a result that has practically already been decided, used to influence public opinion
* After the war, there were several major show trials of war criminals.
district attorney – a lawyer whose job is to represent the government in a legal matter and/or in court
* The district attorney filed a case against the polluting factory.
witch-hunt – the practice of looking for and punishing people who have a different opinion or different habits than most other people do
* The search for dangerous communist in the 1980s was, in most cases, a witch-hunt.
political ambition – wanting to have a powerful position in politics; a desire to have an important career in politics
* Sheila never had political ambitions when she was younger, but when she was 47, she suddenly decided to run for mayor.
high-profile – receiving a lot of attention and publicity; noticed and known by many people; with a lot of public attention
* What can we do to prevent this from becoming a high-profile scandal?
to make an example of (someone) – to shame someone and make his or her case serve as a warning to discourage others from doing the same thing
* The professor made an example of Hendric, kicking him out of the class for cheating on an exam.
criminal – a person who has broken the law; a person who has committed a crime
* What percentage of criminals complete their full prison sentence?
to crack down – to become very strict and enforce rule or laws without making exceptions
* Mall security guards are cracking down on shoplifters.
to grandstand – to behave or speak in a way that attracts attention and interest, especially to make oneself seem important or powerful
* Lorelai uses every meeting to grandstand, trying to make the managers think she’s the best worker in the office.
sacrificial lamb – a person who is harmed or put in a damaging position for the benefit of the larger group
* James wasn’t really to blame for the mistake, but became the sacrificial lamb when he didn’t defend himself as the others did.
to take a stand – to boldly state one’s position and not be swayed or persuaded by others
* Someone needs to take a stand and tell Heather that her behavior is unacceptable.
at the expense of – causing harm or neglect to someone or something while pursuing some other goal or action
* We can meet the deadline, but only at the expense of thoroughness and quality.
justice – fairness in how people are treated, especially under the law
* Gregorio became a judge because he is passionate about justice for all.
from where I’m standing – a phrase used to express one’s opinion while recognizing that other people may have different perspectives or opinions
* From where I’m standing, that sounds like a terrible idea, but I realize other people may disagree with me.
blind spot – an area where one’s view is obstructed (blocked) and one cannot see clearly, either literally or figuratively
* Their love for their daughter has created a blind spot where they can’t see or understand how bad her actions have become.
Comprehension Questions
1. What does Carol mean when she says, “I think he’s guilty”?
a) She thinks he committed the crime.
b) She doesn’t think he’s trustworthy.
c) She thinks he is dishonest.
2. What does it mean for the government to be cracking down?
a) It’s facing a lot of budget cuts.
b) It’s changing the laws to become tougher on crime.
c) It’s enforcing the laws more strictly.
Answers at bottom.
What Else Does It Mean?
to crack down
The word “to crack down,” in this podcast, means to become very strict and enforce rules or laws without making exceptions: “The auditors are cracking down on people not paying the taxes they owe.” The phrase “to crack up” means to laugh uncontrollably: “It’s so funny to watch little kids crack up over their own jokes.” The phrase “to crack (someone) up” means to make another person laugh: “Oh, he’s so funny. He cracks me up.” When a voice “cracks,” it temporarily sounds different, especially if the speaker is very emotional: “His voice cracked during his emotional speech.” Finally, the phrase “to crack (one’s) knuckles” means to make a loud, popping sound by bending one’s fingers backward: “Some piano players like to crack their knuckles before performing, because they think it makes their fingers move more quickly.”
at the expense of
In this podcast, the phrase “at the expense of” means causing harm or neglect to someone or something while pursuing some other goal or action: “You can’t use your savings to go on a fancy trip to Hawaii at the expense of having a secure retirement.” The phrase “at (someone’s) expense” means with someone else paying for one to do something: “They ate at five-star restaurants at the company’s expense.” When talking about travel, “all expenses paid” means having all travel, hotels, and meals paid for by someone else: “Congratulations! You’ve won an all-expenses-paid trip to Niagara Falls!” Finally, the phrase “out-of-pocket expenses” refers to small expenses that one pays with one’s own cash, but later is reimbursed (repaid) by the employer: “How can I request reimbursement for these out-of-pocket expenses?”
Culture Note
The People's Court
The People's Court is an American “reality TV show” (a show that films real people, not actors, without a script) that allows people to see “small claims” (lawsuits between private parties involving small amounts of money) being “arbitrated” (reaching a legal decision). The court uses “binding arbitration,” meaning that the decision is final and the parties cannot “appeal” (request a review and a different outcome) the decision. Although the “set” (where a show or movie is filmed) looks like a “courtroom” (government building where legal decisions are made), it actually is not part of the legal system.
The show began in 1981, had a four-year break in the mid-1990s, and continues to “air” (be shown on TV) today. Four “judges” (the people who issue the legal decision) have “presided” (been in charge of) the court room. Over the past 30 years, the show has presented more than 50,000 “litigants” (people who are suing or being sued in a lawsuit) and “witnesses” (people who have information that can help the judge make a decision). Researchers look for interested cases in small claims courts across the country and ask the litigants if they would like to have their case heard in The People’s Court.”
Why do people agree to take their case to The People’s Court? Some people probably like to be seen on TV, but others have a financial “motive” (reason for doing something). The parties receive an “appearance fee” (money paid for someone to be on a show). The losing party does not need to pay the “fine” (money paid as a punishment), because it is paid from a “fund” (an account with money saved for a particular purpose). However, the fine is deducted from the appearance fee, so the parties are still strongly motivated to win their case.
Comprehension Answers
1 - a
2 - c