= 1041
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,041 – Being Rescued.
This is English as a Second Language Podcast episode 1,041. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com – actually, it’s www.ESLPod.com. You can become a member of ESL Podcast. If you go to our website, you could also take a look at our ESL Podcast Blog where we have additional free English lessons every week. Just go to our website and click on the “Blog” link.
On this episode, we’re going to listen to a dialogue between Irma and Bert about being rescued – about people who get caught, trapped, in some place and need to have someone else to come and save them. Let’s get started.
[start of dialogue]
Irma: Do you really think we’ll be rescued? It’s been six hours and I’m losing hope.
Bert: It’s hard to say. I’m sure search and rescue teams are looking for us as we speak.
Irma: But what if they don’t come in time? We didn’t bring any provisions and we’re almost out of water.
Bert: You’re afraid of starvation and dying of thirst? I think we’d die from hypothermia or exposure to the elements first.
Irma: Thanks. I hadn’t thought of that until you mentioned it. Hey, I think that’s the sound of a helicopter.
Bert: You’re hearing things. That’s not a helicopter.
Irma: I think I hear search and rescue dogs. I think they’re onto our scent!
Bert: I think you’re starting to hallucinate. I don’t hear anything.
Irma: Can’t you just humor me? I’m trying to keep hope alive.
Bert: Oh, sure. Hey, I think I hear something.
Irma: You do?
Bert: Yeah, it’s Santa Claus on his sleigh.
[end of dialogue]
Our dialogue begins with Irma saying to Bert, “Do you really think we’ll be rescued?” “To be rescued” means to be saved from a difficult or dangerous situation. Irma says, “It’s been six hours and I’m losing hope.” “To lose hope” (hope) means to no longer believe something is possible. Irma doesn’t think that she and Bert will be rescued. Bert says, “It’s hard to say,” meaning I’m not sure.
“I’m sure,” he says, “search and rescue teams are looking for us as we speak.” “Search and rescue (rescue) teams” are groups of people that go out and try to find missing people, usually providing medical assistance and transportation so those people can get back to “safety,” we might say.
Irma says, “But what if they don’t come in time?” “In time” means while it is still useful – before something bad happens or before some specific deadline. “I need to get my application in to the office in time” – before the deadline – “so that I’m able to apply for this job” (or whatever it is that I’m submitting an application for). Irma is worried that the search and rescue teams will not arrive in time. We’re guessing that means before Irma and Bert die from this dangerous situation in which they find themselves.
Irma says, “We didn’t bring any provisions and we’re almost out of water.” “Provisions” (provisions) usually refers to food that you eat on a long journey, on a long trip. I suppose provisions could include other things as well, but usually it refers to food that you bring with you on a trip, especially when you are going somewhere where there isn’t any food for you to buy or to get easily.
Bert says, “You’re afraid of starvation and dying from thirst?” “Starvation” (starvation) is when you die because you don’t have enough food. This a pretty happy dialogue, isn’t it? Yeah! We have starvation and dying of thirst. “To die of thirst” (thirst) is to die because you don’t have enough water. “Starvation,” then, refers to not having enough food, and dying of thirst would mean to die because you don’t have any liquid, any water.
Bert says, “I think we’d die from hypothermia or exposure to the elements first.” “Hypothermia” (hypothermia) is a medical condition of having a very low body temperature. If you’re out in the cold for a very long time and your body temperature begins to fall – begins to drop, begins to go down – that could eventually kill you.
“Exposure (exposure) to the elements” refers to being harmed by and possibly even dying from the conditions of the weather in a very hot, or very cold, or very wet, or very dry place when you don’t have any clothing to protect you, or you don’t have the appropriate protection against those “elements” or parts of the weather. So if it is a very hot area and you don’t have anywhere to go to keep you cool, you could be hurt by that. You could become sick or you could even die. That’s what “exposure to the elements” is referring to.
Irma says, “Thanks, I hadn’t thought of that until you mentioned it.” She’s not really thanking Bert. She’s telling Bert that he has told her something even worse than what Irma had thought of in terms of what might happen if the search and rescue teams don’t arrive in time.
Irma says, “Hey, I think that’s the sound of a helicopter.” A “helicopter” (helicopter) is like a plane in that it flies in the air, but unlike a plane, it can go up and down – straight up and straight down. Helicopters have things on top called “propellers” that go around that allow it to go up and down in the air.
Irma thinks she hears the sound of a helicopter, but Bert says, “You’re hearing things.” If you say “I’m hearing things” or “You’re hearing things,” you mean that you think you hear a sound, but it’s not actually real. You’re hearing things that aren’t really there. If you’re a little crazy, you might hear things, and that is sometimes used almost as a joke – when someone says, “I hear something” and the other persons says, “Oh, you’re hearing things,” meaning you’re imagining it; it’s not really true.
“That’s not a helicopter,” Bert says. But Irma says, “I think I hear search and rescue dogs.” These would be dogs that are sent out to find someone who has gone missing. She says, “I think they’re onto our scent.” “To be onto” something means to be aware of something, to be following it, to be investigating it. “Scent” (scent) is a way that something or someone smells. That is, of course, how dogs find things or people that are missing. They have the scent of that person, and then they can use their power of smell to find the person.
Bert says, “I think you’re starting to hallucinate.” “To hallucinate” (hallucinate) means that you see or experience something that isn’t really there. This sometimes happens when people take certain kinds of drugs, but it can also happen if you, for example, haven’t had enough to drink – your mind can start to go a little crazy. Bert thinks Irma is hallucinating. He says, “I don’t hear anything.”
Irma says, “Can’t you just humor me?” “To humor” (humor) someone is to go along with someone’s idea or perhaps even some joke that someone is telling – to pretend that you agree with this person even though you don’t really agree with them or even though you don’t really think that his idea is something that is a good one. To humor someone would be to pretend that you agree or pretend that whatever they are saying is true.
Irma says “Can’t you just humor me? I’m trying to keep hope alive.” “To keep hope alive” means to continue to be positive, to continue to be optimistic even when bad things are happening, even when perhaps there is no good reason for you to be hopeful about the future. Bert says, “Oh, sure. Hey, I think I hear something.” Now Bert thinks he hears something. Irma says, “You do?”
Then Burt responds, “Yeah, it’s Santa Claus on his sleigh.” He’s actually joking. He says he hears something, and when Irma asks him what, he responds “Santa Claus on his sleigh.” Santa Claus is, of course, the symbol of Christmas, and in the popular belief – at least among children – Santa Claus delivers presents, gifts, to them every Christmas.
How does Santa Claus do this? Well he rides through the sky, not in a helicopter – though that would seem like a good idea – but in a “sleigh” (sleigh). A “sleigh” is another word for a large “sled” (sled). What’s a sled? A “sleigh” or a “sled” is something that moves over the snow and ice, usually pulled by an animal such as horse or perhaps even a reindeer. Sleighs are large sleds that people travel in, in cold places.
It’s not something really that you see very much of anymore. Usually it’s just done for entertainment nowadays, although there are still, in some places of the world, people who travel by sleigh because that’s the most efficient way of getting across snow or ice when you don’t have a helicopter.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Irma: Do you really think we’ll be rescued? It’s been six hours and I’m losing hope.
Bert: It’s hard to say. I’m sure search and rescue teams are looking for us as we speak.
Irma: But what if they don’t come in time? We didn’t bring any provisions and we’re almost out of water.
Bert: You’re afraid of starvation and dying of thirst? I think we’d die from hypothermia or exposure to the elements first.
Irma: Thanks. I hadn’t thought of that until you mentioned it. Hey, I think that’s the sound of a helicopter.
Bert: You’re hearing things. That’s not a helicopter.
Irma: I think I hear search and rescue dogs. I think they’re onto our scent!
Bert: I think you’re starting to hallucinate. I don’t hear anything.
Irma: Can’t you just humor me? I’m trying to keep hope alive.
Bert: Oh, sure. Hey, I think I hear something.
Irma: You do?
Bert: Yeah, it’s Santa Claus on his sleigh.
[end of dialogue]
If you feel lost in English, our scriptwriter – Dr. Lucy Tse – can rescue you with her wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2014 by the Center for Educational Development.
Glossary
to be rescued – to be saved from a difficult or dangerous situation
* I can’t believe your cat had to be rescued from the apple tree.
to lose hope – to no longer believe that something is possible
* Some environmentalists are losing hope, fearing that we’re running out of time to save many plants and animals from extinction.
search and rescue team – a group of people who look for missing people, provide medical assistance if needed, and take them out of dangerous situations
* Should search and rescue teams save people who didn’t listen to their warnings about storms and floods?
in time – before a deadline; while something is still relevant and useful
* Did you arrive in time to hear the President speak?
provisions – food, especially food that is used during a journey or in case of an emergency
* They filled their basement with provisions, like canned goods and bottled water, in case of an earthquake.
starvation – a slow death caused by a lack of food or nutrition; death from hunger
* How can you throw away uneaten food, knowing that people in other parts of the world are dying of starvation?
to die of thirst – to slowly die due to a lack of water and other fluids; to die from dehydration
* After eating an entire bag of salty potato chips, Jacques felt as if he were dying of thirst.
hypothermia – the medical condition of having a dangerously low body temperature that could lead to death
* When Giancarlo fell into the icy water, we were worried about hypothermia.
exposure to the elements – the condition of being in very cold/hot or wet/dry weather without appropriate shelter and/or clothing for protection
* The hikers have enough food and water for several days, but if we don’t find them soon, they might get sick or die due to exposure to the elements.
helicopter – a flying machine that can lift straight up from the ground, without first rolling forward to increase speed, and that has one or more propellers on the top, without long side wings
* Helicopters can be landed on the top of skyscrapers because they don’t need a long runway.
to hear things – to think that one has heard a sound that didn’t actually exist; to hear imaginary sounds
* Did someone knock on the door, or am I hearing things?
onto – aware of something that is hidden and following it or investigating it
* Do you think the police are onto us?
scent – odor; the way something smells
* These dogs are trained to recognize the scent of illegal drugs.
to hallucinate – to see and/or experience something that isn’t really there, especially as a result of using illegal drugs or being very dehydrated
* When people are lost in a desert, they start to hallucinate, seeing rivers and lakes where there’s really just sand.
to humor (someone) – to go along with someone’s idea or joke and pretend to agree with that person even if someone does not really agree with him/her; to agree to do something that seems silly or pointless to please someone else
* David makes some strange requests, but they’re harmless, so just humor him.
to keep hope alive – to continue to be positive and optimistic and think that something can happen, even if it is very unlikely
* The miners have been trapped underground for days, but rescuers and family members are trying to keep hope alive
sleigh – a sled; a large, open vehicle that has seats for the riders, and long flat parts for riding over snow, pulled by horses or reindeer
* The Christmas tree farm offers free sleigh rides to anyone who buys a tree.
Comprehension Questions
1. According to Bert, what is the greatest threat facing them?
a) A lack of oxygen.
b) A lack of food.
c) A lack of warm clothing.
2. What does Irma mean when she says, “Can’t you just humor me?”
a) She wants Bert to tell her a joke.
b) She wants Bert to laugh at her jokes.
c) She wants Bert to start agreeing with her.
Answers at bottom.
What Else Does It Mean?
provision
The word “provisions,” in this podcast, means food, especially food that is used during a journey or in case of an emergency: “Safety experts recommend keeping appropriate provisions in the trunk of your car in case of an earthquake or another natural disaster.” When talking about a legal contract, a “provision” is one clause, of part of the document that specifies what will happen under certain conditions: “The rental agreement includes a provision for ending the agreement if tenants don’t pay their rent.” Sometimes the word “provision” describes something that is being provided: “Tracy thinks the government should pay for the provision of basic childcare for all families.” Finally, the phrase “provision for (someone)” describes providing something for someone: The tax code makes special provisions for low-income workers.”
to hear things
In this podcast, the phrase “to hear things” means to hear a sound that didn’t actually exist, or to hear imaginary sounds: “I thought I heard someone calling my name, but that’s impossible. I must be hearing things. The phrase “Have you heard the one about (something)?” is used to ask if someone has already heard the joke that one wants to share: “Have you heard the one about why the chicken crossed the road?” The phrase “I’ve heard that one before” means that one doesn’t believe someone’s excuse or explanation: “Sheila tried to tell the teacher that the dog ate her homework, but he said, ‘I’ve heard that one before.’” Finally, the phrase “to never hear the end of (something)” means that people will continue to talk about something, especially an embarrassing thing, for a long time: “If this idea doesn’t work, I’ll never hear the end of it.”
Culture Note
Animals Used for Search and Rescue
Animals are often used for search and rescue “missions” (projects with a specific purposes), because they have certain abilities that are better than those of humans, or that “complement” (go together well with; match) humans’ abilities.
For examples, most dogs have a “keen” (sharp; very good) “sense of smell” (able to smell very faint (light) odors and identify them), so they are often used in search and rescue efforts. “Herding” (trained to chase sheep and control where they go) dogs like German shepherds and border collies are often trained for “airscenting” (detecting (finding) the scent of humans in the air) and used to find “missing persons” (people whose location is unknown). Other dogs are trained for “tracking,” where they look for missing people by following their scent over the ground. “Cadaver” (dead body) dogs are used to find the bodies of people who have died.
In a “mounted” (riding on the back of a four-footed animal) search-and-rescue mission, horses are used to transport human searchers and rescuers. The horses move more quickly over “rugged” (rough; uneven) “terrain” (land) than humans on foot, and they are able to reach places that are “inaccessible” (not able to be reached) by cars and other vehicles. Sometimes the horses are used only for transportation, but in other cases, the horses have been trained to “assist” (help) the rescuers in identifying missing persons. Horses have a keen sense of hearing, smell, and vision, so they can “point the rescuers to” (indicate where the rescuers should look for) “clues” (hints or ideas about something) to find the missing person.
Comprehension Answers
1 - c
2 - c