
= Top Influential Think Tanks Ranked for 2024
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css


'''

https://academicinfluence.com/inflection/study-guides/influential-think-tanks



== What is a think tank?

Often opinionated and even contentious, think tanks are a fixture of modern politics and public policy around the globe. Though focused intellectual groups have played an influential role in governance for centuries (royal courts, elite societies, and business clubs, for example), think tanks are a distinctly 20th century invention.


Think tanks are interest groups that pursue research and analysis to advance a set of values or ideas, often through political action and policy change, as well as through cultural and social influence. Some think tanks are truly non-partisan, regularly working with administrations of both main US political parties (we label them “centrist” in the list below), while others self-identify as non-partisan despite evidence to the contrary (we reserve the right to exercise our own judgment about such cases), and still others are explicitly or tacitly conservative, neo-conservative, libertarian, centrist, liberal, progressive, or socialist.

Some think tanks focus on domestic policy and some on foreign policy. Some pursue free-market capitalism and limited government, while others argue for increased taxes and social welfare spending. Still others debate revolution or monitor the growth of liberation movements in foreign countries. They wield influence by publishing reports and books, developing research tools, running media campaigns, holding events and conferences, directing lobbying action, and enlisting high-ranking and well-connected members. Some are broadly transparent about their sources of funding and support, while others are quite guarded about this information.

== Methodology

Our innovative ranking technology delivers a better way for important individuals and institutions to shine by capturing an essential metric: true influence. By “true influence,” we mean the level of attention and penetration an idea and/or entity achieves worldwide.

To do this, we:

- aggregate scholarly and academic citations;
- track the attention they receive;
- and weigh their merits against other information sources such as newspapers, magazines, and global media outlets.

Importantly, our machine learning technology doesn’t simply scrape the web for mentions. The artificial intelligence (AI) behind it digs deeply, by

- identifying entities and institutions,
- finding mentions of the institution across the web,
- mapping the people that make up an institution, including independent work done by those people and their affiliations with other institutions, and
- mapping institutional output by identifying ideas as entities for further tracking.


As this mapping develops and signals strengthen between these entities, we collect essential data for comparing the influence of organizations (in this case, think tanks). For added corroboration and results assurance, we employ web traffic analysis from third parties (including SEMrush and Ahrefs) to track the organic search traffic leading to the think tanks’ domains, each domain’s keyword footprint, the number of referring domains, and the authority of those referring domains.

In summary, our team of data scientists is confident this combination of web data aggregation, AI-driven data analysis, and independent web search monitoring yields an accurate, reliable measure of a think tank’s global influence.


== (01) Brookings Institution

Political bias: Liberal










