= 0952
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 952 – Dealing with Rising Production Costs.
This is English as a Second Language Podcast episode 952. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there. Become a member of ESL Podcast and download a Learning Guide for this episode.
This episode is a dialogue between Giovanni and Melanie. It's a business-related episode about the increasing cost of making things in a business. Let’s get started.
[start of dialogue]
Giovanni: There are no two ways about it. We have to raise prices.
Melanie: We can’t. We already raised prices earlier this year. Doing it again risks alienating our customers.
Giovanni: What else can we do? Our production costs have risen nearly 15 percent. We’ve tried absorbing them and offsetting them, but nothing has worked. Our profit margin continues to shrink and we don’t have any other choice.
Melanie: What about lowering the quality of our raw materials? We could use a cheaper supplier.
Giovanni: That’s a sure way to lose customers. If we start cutting corners on quality, our customers will leave in droves.
Melanie: What if we discontinue manufacturing some of the less popular items? That should save us some money.
Giovanni: Not enough. We either raise prices or stop production altogether.
Melanie: There is one other option.
Giovanni: What?
Melanie: We could reduce our workforce.
Giovanni: You mean fire people? That’s off the table!
[end of dialogue]
Our dialogue begins with Giovanni saying to Melanie, “There are no two ways about it.” This expression, “There are no two ways (ways) about it,” is used when you are telling someone there is only one answer or one solution to some problem that you have. There are no other options; there's only this one possibility. Giovanni says, “There are no two ways about it. We have to raise prices.” The “price” (price) of something is how much it costs. “To raise (raise) prices” means to increase prices. The opposite would be “to lower prices.”
Melanie, however, says, “We can't” – we cannot raise prices. “We already raised prices earlier this year. Doing it again risks alienating our customers.” “To risk” means to put in danger of, or to possibly cause a bad situation to happen. Melanie says if they raise their prices again, they may alienate their customers. “To alienate” (alienate) means to make someone feel unwelcome, to make someone feel excluded. “To alienate” someone, more generally, means to make someone mad, to make them angry, so angry that they don't want to be part of your group anymore – or in this case, they don't want to buy anything from you.
Giovanni says, “What else can we do? Our production costs have risen nearly 15 percent.” The “cost” of something is how much money you have to spend to do it. “Production” (production) comes from the verb “to produce,” which means to make something. “Production cost” refers to how much it costs to make usually a physical object, although it could also be something like a movie. We talk about “movie production costs” here in Los Angeles all the time. Well, I don't. Some people do.
Giovanni says that he and Melanie have tried “absorbing” these costs and “offsetting them,” but nothing has worked. “To absorb” (absorb) here means to take care of or to accept increased costs in a business without making the prices higher for the customers – without raising the prices. So, for example, if something that you need to make your product that you sell increases in price, you don't increase the price that you charge your customer; you absorb it. Basically, you're going to make less money.
Giovanni says they've tried “absorbing” the increasing production costs as well as “offsetting” them. “To offset” (offset) means to make up for – often, to do the opposite of something in order to have some sort of balance. In this case, it probably means that they've decreased the costs elsewhere in their company. They've tried to save money in another part of their business in order to make sure they can still make money on the product they're selling.
Giovanni says, “Our profit margin continues to shrink and we don't have any other choice.” Your “profit” (profit) is how much money you make. It's when you take in more money than you spend. When you receive more money from your customers, then you spend to produce what you are selling to your customers. Don't confuse this “profit” with (prophet). That sort of prophet is someone who predicts the future. You hear that term often in relation to the Bible.
But there's nothing biblical here. We’re talking business, and Giovanni is talking about profit margins. Your “profit margin” (margin) is the actual percentage that you make. Giovanni says, “Our profit margin continues to shrink.” “Shrink” (shrink) means to become smaller. In this case, it means to be lowered. The profit margin is less and less.
Melanie says, “What about lowering the quality of our raw materials?” “To lower the quality” means, basically, to use things that aren't as good as other things that you might be able to use. The quality of your product is how good it is, how well made it is. “Raw (raw) materials” are the things you use to make the product that you sell. If I am selling tables or chairs made of wood, the raw materials would be the wood itself, and nails, and perhaps paint, and anything else I use to make the chair. The final product is the chair, but the chair is made from raw materials.
“Raw” normally means not cooked. We talk about “raw meat.” That would be meat that has not yet been cooked – has not yet been put over a fire or placed in an oven. Here, however, it just means materials that are not in their final form. I was watching a program on television a few nights ago, and there was this young girl, maybe 15 years old, singing. She had a wonderful voice. Her singing wasn't perfect, but she had a lot of what we would describe as “raw talent,” “raw skill,” “raw ability.” It's something she needs to make better. It’s something she needs to work on to “refine” (refine) – to make it so that it is a final product.
Melanie says, “We could use a cheaper supplier.” “Cheaper” means less expensive – something that doesn't cost you as much money. A “supplier” (supplier) is someone who sells you raw materials or sells you things that you use in your business and helps you sell your product or make your product to sell. Giovanni disagrees with Melanie. He doesn't think they should use a cheaper supplier. He says, “That's a sure way to lose customers.” “That's a sure way to lose customers” means that's a guaranteed way, or that’s something that will definitely result in losing customers.
He says, “If we start cutting corners on quality, our customers will leave in droves.” “To cut corners” means to do something more quickly or less expensively – more cheaply, but at a lower quality. “To cut corners” means to do something in such a way that you're getting it done, but it is not as good as it could be or should be. “To leave in droves” (droves) means that many people will leave. “Droves” here refers to a large group of people. “To leave in droves” means that most of your customers are going to leave. That's what Giovanni says will happen if they cut corners on quality.
Melanie then asks, “What if we discontinue manufacturing some of the less popular items?” “To discontinue” (discontinue) means to stop doing something, to no longer do something. “Manufacturing” comes from the verb “to manufacture” (manufacture), which is another verb for “to produce,” “to make.” Melanie is suggesting they stop making some of the less popular items – the products they make that don't sell as much. “That would save us some money,” she says.
Giovanni says, “Not enough” – not enough money, he means. “We either raise prices or stop production altogether.” “Altogether” (altogether) means entirely or completely. Don't confuse that with two separate words, “all” (all) and “together.” When someone says, “We’re going to do this all together,” he means we’re going to do it all as a group. We are going to each do it at the same time. But “altogether” as one word, with one “l,” means completely, entirely.
Melanie says, “There is one other option.” Giovanni says, “What?” Melanie replies, “We could reduce our workforce.” “To reduce” means to lower the number of. “Workforce” (workforce) – one word – refers to the people who work for a company. Melanie is suggesting that they get rid of a few of their employees, basically. Giovanni says, “You mean fire people?” “To fire” means to tell someone they no longer have a job at your company.
Giovanni says, “That’s off the table!” The expression “to be off the table” (table) means it's not an option. It's not under consideration. We might say, “It's out of the question.” You're not even going to consider that as a possibility.
Now let's listen to the dialogue, this time at a normal speed.
[start of dialogue]
Giovanni: There are no two ways about it. We have to raise prices.
Melanie: We can’t. We already raised prices earlier this year. Doing it again risks alienating our customers.
Giovanni: What else can we do? Our production costs have risen nearly 15 percent. We’ve tried absorbing them and offsetting them, but nothing has worked. Our profit margin continues to shrink and we don’t have any other choice.
Melanie: What about lowering the quality of our raw materials? We could use a cheaper supplier.
Giovanni: That’s a sure way to lose customers. If we start cutting corners on quality, our customers will leave in droves.
Melanie: What if we discontinue manufacturing some of the less popular items? That should save us some money.
Giovanni: Not enough. We either raise prices or stop production altogether.
Melanie: There is one other option.
Giovanni: What?
Melanie: We could reduce our workforce.
Giovanni: You mean fire people? That’s off the table!
[end of dialogue]
A sure way to improve your English is to listen to the dialogues written by our wonderful scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
no two ways about it – a phrase used when there is only one answer or solution, and there are no other options or alternatives
* There are no two ways about it: we will need to sell our home to pay for Raquel’s medical treatment.
to raise prices – to increase the selling price of something so that customers have to pay more in order to buy it
* If the stores keep raising prices, soon we’ll be eating only beans and rice!
to alienate (someone) – to make someone feel unwelcome or excluded
* Sometimes teachers alienate their students by calling them by the wrong name.
production costs – the expense of creating something; the amount of money that must be paid for materials, labor, and other items in order to manufacture something
* What percentage of the movie’s production costs were for special effects?
to absorb – to accept a new or increased cost and pay for it without asking one’s customers to pay that additional amount, thereby reducing one’s profits
* When customers make payments on the utility’s website, the payment processor charges a small transaction fee, which the utility can absorb or pass onto the customer.
to offset – to counterbalance; to make up for; to do the opposite of something
* We could offset the increased cost of renting this facility for our meeting by order less food for the event.
profit margin – a percentage calculated by dividing a company’s net income (money received minus expenses) by total revenues (the total amount of money received)
* Restaurants often operate on small profit margins on food, but large profit margins on alcohol and other drinks.
to shrink – to become smaller; to be reduced in size
* If sales continue to shrink, we’ll have to close the store.
raw materials – basic materials, such as wood or metal, that are used to make a product
* Countries that export raw materials can make more money by processing those materials and exporting finished goods.
supplier – a company that sells materials that other companies need to make other goods and services
* We have great suppliers for oats and wheat, but we need to find a new supplier for soy.
sure way to – a very good way to do something; a way of doing something that always succeeds and has no chance of failure
* Studying for at last two hours every day is a sure way to improve your grades.
to cut corners – to do things more quickly or less expensively, but at a lower quality
* Book publishers are cutting corners by using less expensive paper, but now the books don’t last as long as they used to.
to leave in droves – to depart in large numbers; for many people to stop doing or using something
* When a lot of bees started buzzing around the park, families left in droves to avoid getting stung.
to discontinue – to stop doing something; to no longer continue to do something, especially to stop making a product
* When Millie found out they were going to discontinue making her favorite lipstick, she bought as many tubes as she could find.
to manufacture – to make or create many of the same items, especially in a factory
* In this factory, we manufacture components for digital cameras and smartphones.
altogether – entirely; completely
* After Mike hurt his foot, the doctor told him to stop running altogether for at least two weeks.
workforce – the people who are employed by a business or in an industry; labor; workers
* Our company’s success depends on having a highly educated and highly motivated workforce.
off the table – not under consideration; not an option; out of the question
* What do you mean you want to drop out of college? That’s off the table!
Comprehension Questions
1. According to Giovanni, what will happen if the company cuts corners on quality?
a) Customers will file complaints with government agencies.
b) Customers will complain and make a lot of noise.
c) Customers will stop buying the company’s products.
2. What does Giovanni mean when he says, “That’s off the table”?
a) He will not fire his employees.
b) He doesn’t have enough money to do what Melanie is suggesting.
c) Reducing the workforce would be illegal.
Answers at bottom.
What Else Does It Mean?
to absorb
The verb “to absorb,” in this podcast, means to accept a new or increased cost and pay for it without asking one’s customers to pay that additional amount, thereby reducing one’s profits: “The schools can’t absorb the rising prices of supplies, so they’ve started asking students and parents to bring items like paper and pencils.” The verb “to absorb” also means to soak up or to hold a certain amount of water: “According to the commercials, this brand of paper towels absorbs twice as much water as other brands.” Or, “We can’t find diapers that absorb enough to keep the baby dry all night long.” Finally, the verb “to absorb” can also mean to understand an idea or concept: “I had to read that chapter three times before I could really absorb everything the author was saying.”
table
In this podcast, the phrase “off the table” means not under consideration, not an option, or out of the question: “Tickets cost more than $1,000, so going to Hawaii for vacation is off the table.” The phrase “to pay (someone) under the table” means to pay someone in cash, illegally, without reporting it to the government, so that nobody has to pay taxes related to the transaction: “Have you ever paid your nanny under the table so that you don’t have to pay household employee taxes?” Finally, the phrase “to turn the tables on (someone)” means to completely change a situation so that the people involved are in opposite roles: “Lyle has wanted to date Carla for years, but when she finally said yes, he decided he wasn’t interested after all. He really turned the tables on her!”
Culture Note
The Use of “Table” in Parliamentary Procedure
“Parliamentary procedure” refers to the rules and guidelines that a group of people follow during a formal meeting, especially when they are making rules and laws. Parliamentary procedure “governs” (states and controls) who can speak, when they can speak, and how others can express whether they agree or disagree, as well as how the group makes a final decision.
The “terminology” (use of technical words) to describe parliamentary procedure can be confusing, because the word “table” has different meanings in American and British English. Groups “on both sides of the pond” (in North American and in Europe) talk about “tabling” an issue, or the idea of putting an issue on a “figurative” (not real) table, but the use and purpose of the “table” is different.
In American English, the “table” is like a shelf, where issues are placed until one is ready to deal with them. In contrast, in British English the “table” is a work surface where issues are placed when they need to be dealt with actively.
So, in parliamentary procedure, an individual may “lay an issue on the table.” An American would use that phrase to mean that he or she wants more time to research or discuss an issue, so no decisions should be made on it right now. In British English, to “lay an issue on the table” means to actively discuss an issue and work toward a decision or vote. That same idea in American English would be expressed as “to put an issue on the table” – to make an issue available for discussion and “debate” (talking about the arguments for and against something).
Comprehension Answers
1 - c
2 - a