= 0974
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 974 – Talking About Old Crimes.
This is English as a Second Language Podcast episode 974. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there and become a member of ESL Podcast and download a Learning Guide for this episode.
This episode is a dialogue between Paul and Della about vocabulary related to crimes, especially old crimes. Let’s get started.
[start of dialogue]
Paul: What are you watching?
Della: I’m watching a really good show about cold cases. They take unsolved crimes from decades ago and reconstruct them, trying to solve them once and for all.
Paul: But after all this time, isn’t the trail cold? How do they solve the crimes with no new leads?
Della: They go over the witness testimony and use scientific methods that didn’t exist many years ago.
Paul: Isn’t there a statute of limitations for most crimes?
Della: Yes, but not for murder.
Paul: I really doubt a TV show can solve crimes that the police couldn’t crack. Are any crimes really ever solved on the show?
Della: Yes, of course.
Paul: How? Through crack investigative methods or a keen eye for detail?
Della: Deathbed confessions.
Paul: Ah.
[end of dialogue]
Paul begins our dialogue by asking Della, “What are you watching?” Presumably – we can guess, that is, that Della is watching television. Della says, “I’m watching a really good show about cold cases.” A “cold case” is a criminal investigation that has not been solved and is not, at this time, trying to be solved by the police department. The police may investigate a crime for many months, sometimes even many years, and then they say, “Okay, there’s no sense trying to find out who did this because we haven’t been able to find out so far.” This crime then becomes a “cold case” – a cold investigation. It’s “cold” because it’s so old. Maybe that’s why I feel cold more often now than I used to.
Well, Della is watching a television show about crime, about cold cases. She says, “They take unsolved crimes from decades ago and reconstruct them.” “To solve (solve) a crime” is to figure out who is responsible for the crime – who “committed” the crime, we would say. “To solve a crime” is to find the person who is guilty of the crime. An “unsolved case” or an “unsolved crime” is one where the police have not figured out who the guilty person is. “Cold cases” are always unsolved crimes. Della says these that are being discussed on the television show are “from decades ago.”
A “decade” (decade) is a period of 10 years. So, “several decades ago” would mean 20, 30, 40, maybe even 50 years ago – a long time ago. “To reconstruct” something is to build it again. “To construct” is to build something, to assemble something. “To reconstruct” would be to take something that has perhaps fallen apart and build it again. However, here the verb really means to try to figure out everything that happened that is related to the crime. “To reconstruct a crime” would be to try to figure out exactly who committed the crime and all the different circumstances surrounding the crime.
The television show tries to solve these unsolved crimes “once and for all.” “Once and for all” is a phrase meaning that once you do it, you won’t have to do it again. It’s the last time you’ll have to look at this issue or try to do this thing. It will be completed. It will be finished.
Paul says, “But after all this time, isn’t the trail cold?” A “trail” (trail), in this case, leads to a series of clues that are used to try to solve a crime. A “clue” (clue) is evidence that indicates the answer to a problem or the solution to a problem. Paul is saying that the trail is cold on these cold cases, meaning it’s very difficult to try to follow the clues to figure out where the evidence is leading you.
He says, “How do they solve the crimes with no new leads?” A “lead” (lead) is the same as a clue. It’s a piece of information that gives you some idea about what happened, that helps you solve the mystery or the crime. Della says, “They go over the witness testimony and use scientific methods that didn’t exist many years ago.” A “witness” (witness) is someone who sees something, often something that is criminal or something that has gone wrong.
You could also have a witness, however, to – for example – your marriage. In the United States, in most places, if you get married, you have to sign an official government document, and there needs to be at least two people who witness you sign the document who say, “Yes, this person signed the document.” That’s also, of course, something that can go wrong – that is to say, getting married. But normally, a “witness” is someone who sees a crime or sees something bad happen.
“Testimony” (testimony) is a statement or statements that someone makes about what happened, about what they know about a certain topic. “Witness testimony” would be information that was provided by witnesses to some crime, about what they saw or what they heard or what they know.
Della also says the television show uses “scientific methods.” “Scientific methods” would be techniques, or ways of doing something, that would help you figure out who committed the crime – using, perhaps, some special analysis. Perhaps chemicals or some sort of laboratory analysis that would help you figure out who the criminal was. A lot of times, especially nowadays, there is DNA evidence, genetic evidence that is left at the place where the crime was committed – what we call the “scene (scene) of the crime.” Sometimes those kinds of methods can be used to solve old criminal cases as well.
Paul says, “Isn’t there a statute of limitations for most crimes?” A “statute” (statute) is the same as a law. “Statute of limitations” refers to a law that says that if you are not caught for a crime – if the police do not catch you for crime after a certain number of years – then you cannot be arrested. So, if you do something wrong that isn’t very serious, and the police don’t find out about it until many years later, usually they can’t do anything about it because the statute of limitations says the police have only so many years to find people guilty of these kinds of crimes.
“Murder,” however – when you kill someone – typically does not have any statute of limitations placed on it. That is, it doesn’t matter how long ago it was, the police can still arrest you and put you in prison. That’s what Della says here – that for murder there is not a statute of limitations. Paul says, “I really doubt a TV show can solve crimes that the police couldn’t crack.” Paul doesn’t think the TV shows can figure out who the criminal was if the police couldn’t figure it out. The verb “to crack” (crack) means to solve a difficult problem – especially, to solve a crime.
Paul then asked Della, “Are any crimes really ever solved on the show?” Della says, “Yes, of course.” Paul asks, “How? “Through crack investigative methods or a keen eye to detail?” “Investigative methods” would be ways that you try to get information about something – in this case, about who committed the crime. “Crack” (crack) here is used as an adjective. Just a second ago, we used it as a verb meaning to solve a crime.
As an adjective, “crack” can mean very sharp, very smart, very good at what you are doing. “I am a crack basketball player.” I can play basketball better than anyone else in my house – better than my wife, that is. That is one possible way of using “crack” as an adjective. “Crack investigative methods” would be very intelligent or smart ways of investigating a crime. “A keen eye for detail” means the ability to notice small things that other people perhaps would not notice. “A keen eye for detail” is the ability to see things that others cannot see.
Paul is asking if these are the ways that the television show solves crimes. However, Della says that that’s not how they solve the crimes when they do solve crimes. They do it, according to Della, by using “deathbed confessions.” A “confession” is a statement admitting that you did something wrong. Sometimes, when the police catch a person who committed the crime, the person will just confess. They will say, “Okay, yes, I did it.” “Confession” comes from the verb “to confess” (confess).
A “deathbed confession” is when you admit to doing something wrong as you are dying. Your “deathbed” is literally the place, the bed, where you are lying as you are dying, and right before you die, you say, “Oh, yes. I murdered this person,” or “I did this terrible thing many years ago.” Of course, it doesn’t take any investigative work by the police if someone confesses to a crime, and Della is saying here that this television show doesn’t really solve any crimes unless someone has confessed to them.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Paul: What are you watching?
Della: I’m watching a really good show about cold cases. They take unsolved crimes from decades ago and reconstruct them, trying to solve them once and for all.
Paul: But after all this time, isn’t the trail cold? How do they solve the crimes with no new leads?
Della: They go over the witness testimony and use scientific methods that didn’t exist many years ago.
Paul: Isn’t there a statute of limitations for most crimes?
Della: Yes, but not for murder.
Paul: I really doubt a TV show can solve crimes that the police couldn’t crack. Are any crimes really ever solved on the show?
Della: Yes, of course.
Paul: How? Through crack investigative methods or a keen eye for detail?
Della: Deathbed confessions.
Paul: Ah.
[end of dialogue]
I’d like to thank our crack scriptwriter, Dr. Lucy Tse, for her hard work.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
cold case – a criminal investigation that has not been solved and will no longer be actively investigated until more information becomes available
* The police officer received a mysterious call with details about a cold case.
unsolved crime – an instance of someone breaking the law but never being punished for it because investigators cannot determine who did it
* Their daughter’s murder is referred to as an unsolved crime, but they’ve never given up hope that the criminal will be found.
decade – a period of 10 years
* Wow, Lorraine and Benny been married for three decades!
to reconstruct – to put something together again, either a physical object or an idea
* City planners are trying to reconstruct the original train routes from 50 years ago to help determine the new train routes.
once and for all – a phrase used to show that something will happen definitely and not need additional attempts
* Just tell me the truth once and for all. Are you the person who stole my lunch?
trail – a series of clues that lead someone in a particular direction, especially toward solving a problem
* Researchers are on the trail toward finding a cure for AIDS.
lead – a clue; a piece of information that provides some idea about what happened or who did something
* The police are encouraging people to call if they have any leads about the robbery.
witness testimony – statements made by people who saw something happen and were present during a situation or crime
* The accident happened in daylight in the middle of Times Square, so they’ll definitely be able enough witness testimony.
scientific method – the accepted process of conducting investigations, using a defined and generally used system
* If they had been following the scientific method, they would have had a control group that didn’t receive the treatment.
statute of limitations – the maximum period of time after an event when legal action can be taken
* What is the statute of limitations on assult in cases where the victim was a child?
murder – the crime of killing a person
* The mayor has promised to reduce the number of murders in the city by 20%.
to crack – to solve a mystery or complete a difficult investigation that has been too challenging for other people
* Scientists have been trying to crack the secrets of the universe.
crack – very sharp; astute; very smart and good at what one is doing
* Pierre is a crack shot with that gun and can hit the middle of the target every time.
investigative method – a process for conducting research, especially to solve a crime
* Basic investigative methods include photographing the location of all objects before moving anything at a crime scene.
keen eye for detail – the ability to notice many small things that other people might not notice
* Interior designers have a keen eye for detail and color.
deathbed confession – a statement that one makes while dying, admitting to something bad or wrong that one did earlier in life
* Grandpa Henry made a deathbed confession that shocked his wife, but she never told anyone what it was.
Comprehension Questions
1. What does Paul mean when he asks, “Isn’t the trail cold?”
a) He doesn’t think any new information is available.
b) He doesn’t think people are interested in the crimes anymore.
c) He thinks the investigators found the wrong criminal.
2. Which of these things would not be useful when solving a crime?
a) Scientific methods.
b) Statue of limitations.
c) Investigative methods.
Answers at bottom.
What Else Does It Mean?
cold case
The phrase “cold case,” in this podcast, means a criminal investigation that has not been solved and will no longer be actively investigated until more information becomes available: “Periodically, the bureau assigns an investigator to review cold cases before filing them away.” The phrase “basket case” is an informal phrase that refers to a person who is crazy: “Spending too much time alone can turn anyone into a basket case.” The words “uppercase” and “lowercase” describe capital and non-capital words: “I hate it when people write in uppercase (LIKE THIS) because it seems like they’re shouting.” Finally, a “pencil case” is a small box or pouch used to carry pencils, pens, and erasers: “Each student has to bring a folder, paper, and a pencil case on the first day of school.”
trail
In this podcast, the word “trail” means a series of clues that lead someone in a particular direction, especially toward solving a problem: “Investigating financial crimes must be exciting when you’re following the trail of corruption.” When talking about nature, a “trail” is a path in a natural area or through a park or forest: “We walked along a four-mile trail to get to the lake.” The phrase “trail mix” refers to a snack food made from nuts, dried fruit, and often small pieces of chocolate, often eaten while hiking: “The simplest trail mix is just raisins and peanuts.” Finally, when talking about politics, a “campaign trail” is all the places someone visits to try to get people to vote for one while attempting to win an election: “The senator’s campaign trail includes every town in the state with more than 20,000 residents.”
Culture Note
Interesting Methods Used to Solve Cold Cases
In general, the older a crime is, the more difficult it becomes to solve, because witnesses become “forgetful” (not able to remember something well) or “pass away” (die) and “evidence” (proof; objects that show what happened) “rots” (decomposes; becomes ruined) over time. However people have “turned to” (begun to use) “innovative” (new) methods to solve cold cases.
For example, in 1979 a woman named Susan Schwarz was murdered near Seattle, Washington, but there was no “clear” (easily understood) evidence and the murder was considered a cold case for more than 30 years. But then some “detectives” (investigators who work for the police) distributed “playing cards” (sets of 52 cards with different shapes and numbers, used to play games) to “prisoners” (people who are kept in jail). The cards had the names, photographs, and other information about the “victims” (the people who are hurt by crimes) in cold cases, as well as the promise of a “reward” (money given in return for something) for any “tips” (clues; leads) that would help police solve the crime. A prisoner saw a card with Susan’s information and told the detectives who had committed the crime.
Another interesting way to solve cold cases is to use the Doe Network, a website that uses “crowdsourcing” (using the Internet to have many people working together on a task) to gather details about cold cases. When enough people participate, the resulting clues can help detectives “piece together” (put things together in a certain way to make connections and provide meaning) the details of the crime. The U.S. Department of Justice has recognized the Doe Network for its efforts, specifically because the information on that site has been “instrumental” (very important and useful) in solving 66 cold cases.
Comprehension Answers
1 - a
2 - b
Dialogue/Story
Slow Speed begins at: 1:13
Explanation begins at: 2:51
Normal Speed begins at: 15:51
Complete Transcript
Welcome to English as a Second Language Podcast number 974 – Talking About Old Crimes.
This is English as a Second Language Podcast episode 974. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Go there and become a member of ESL Podcast and download a Learning Guide for this episode.
This episode is a dialogue between Paul and Della about vocabulary related to crimes, especially old crimes. Let’s get started.
[start of dialogue]
Paul: What are you watching?
Della: I’m watching a really good show about cold cases. They take unsolved crimes from decades ago and reconstruct them, trying to solve them once and for all.
Paul: But after all this time, isn’t the trail cold? How do they solve the crimes with no new leads?
Della: They go over the witness testimony and use scientific methods that didn’t exist many years ago.
Paul: Isn’t there a statute of limitations for most crimes?
Della: Yes, but not for murder.
Paul: I really doubt a TV show can solve crimes that the police couldn’t crack. Are any crimes really ever solved on the show?
Della: Yes, of course.
Paul: How? Through crack investigative methods or a keen eye for detail?
Della: Deathbed confessions.
Paul: Ah.
[end of dialogue]
Paul begins our dialogue by asking Della, “What are you watching?” Presumably – we can guess, that is, that Della is watching television. Della says, “I’m watching a really good show about cold cases.” A “cold case” is a criminal investigation that has not been solved and is not, at this time, trying to be solved by the police department. The police may investigate a crime for many months, sometimes even many years, and then they say, “Okay, there’s no sense trying to find out who did this because we haven’t been able to find out so far.” This crime then becomes a “cold case” – a cold investigation. It’s “cold” because it’s so old. Maybe that’s why I feel cold more often now than I used to.
Well, Della is watching a television show about crime, about cold cases. She says, “They take unsolved crimes from decades ago and reconstruct them.” “To solve (solve) a crime” is to figure out who is responsible for the crime – who “committed” the crime, we would say. “To solve a crime” is to find the person who is guilty of the crime. An “unsolved case” or an “unsolved crime” is one where the police have not figured out who the guilty person is. “Cold cases” are always unsolved crimes. Della says these that are being discussed on the television show are “from decades ago.”
A “decade” (decade) is a period of 10 years. So, “several decades ago” would mean 20, 30, 40, maybe even 50 years ago – a long time ago. “To reconstruct” something is to build it again. “To construct” is to build something, to assemble something. “To reconstruct” would be to take something that has perhaps fallen apart and build it again. However, here the verb really means to try to figure out everything that happened that is related to the crime. “To reconstruct a crime” would be to try to figure out exactly who committed the crime and all the different circumstances surrounding the crime.
The television show tries to solve these unsolved crimes “once and for all.” “Once and for all” is a phrase meaning that once you do it, you won’t have to do it again. It’s the last time you’ll have to look at this issue or try to do this thing. It will be completed. It will be finished.
Paul says, “But after all this time, isn’t the trail cold?” A “trail” (trail), in this case, leads to a series of clues that are used to try to solve a crime. A “clue” (clue) is evidence that indicates the answer to a problem or the solution to a problem. Paul is saying that the trail is cold on these cold cases, meaning it’s very difficult to try to follow the clues to figure out where the evidence is leading you.
He says, “How do they solve the crimes with no new leads?” A “lead” (lead) is the same as a clue. It’s a piece of information that gives you some idea about what happened, that helps you solve the mystery or the crime. Della says, “They go over the witness testimony and use scientific methods that didn’t exist many years ago.” A “witness” (witness) is someone who sees something, often something that is criminal or something that has gone wrong.
You could also have a witness, however, to – for example – your marriage. In the United States, in most places, if you get married, you have to sign an official government document, and there needs to be at least two people who witness you sign the document who say, “Yes, this person signed the document.” That’s also, of course, something that can go wrong – that is to say, getting married. But normally, a “witness” is someone who sees a crime or sees something bad happen.
“Testimony” (testimony) is a statement or statements that someone makes about what happened, about what they know about a certain topic. “Witness testimony” would be information that was provided by witnesses to some crime, about what they saw or what they heard or what they know.
Della also says the television show uses “scientific methods.” “Scientific methods” would be techniques, or ways of doing something, that would help you figure out who committed the crime – using, perhaps, some special analysis. Perhaps chemicals or some sort of laboratory analysis that would help you figure out who the criminal was. A lot of times, especially nowadays, there is DNA evidence, genetic evidence that is left at the place where the crime was committed – what we call the “scene (scene) of the crime.” Sometimes those kinds of methods can be used to solve old criminal cases as well.
Paul says, “Isn’t there a statute of limitations for most crimes?” A “statute” (statute) is the same as a law. “Statute of limitations” refers to a law that says that if you are not caught for a crime – if the police do not catch you for crime after a certain number of years – then you cannot be arrested. So, if you do something wrong that isn’t very serious, and the police don’t find out about it until many years later, usually they can’t do anything about it because the statute of limitations says the police have only so many years to find people guilty of these kinds of crimes.
“Murder,” however – when you kill someone – typically does not have any statute of limitations placed on it. That is, it doesn’t matter how long ago it was, the police can still arrest you and put you in prison. That’s what Della says here – that for murder there is not a statute of limitations. Paul says, “I really doubt a TV show can solve crimes that the police couldn’t crack.” Paul doesn’t think the TV shows can figure out who the criminal was if the police couldn’t figure it out. The verb “to crack” (crack) means to solve a difficult problem – especially, to solve a crime.
Paul then asked Della, “Are any crimes really ever solved on the show?” Della says, “Yes, of course.” Paul asks, “How? “Through crack investigative methods or a keen eye to detail?” “Investigative methods” would be ways that you try to get information about something – in this case, about who committed the crime. “Crack” (crack) here is used as an adjective. Just a second ago, we used it as a verb meaning to solve a crime.
As an adjective, “crack” can mean very sharp, very smart, very good at what you are doing. “I am a crack basketball player.” I can play basketball better than anyone else in my house – better than my wife, that is. That is one possible way of using “crack” as an adjective. “Crack investigative methods” would be very intelligent or smart ways of investigating a crime. “A keen eye for detail” means the ability to notice small things that other people perhaps would not notice. “A keen eye for detail” is the ability to see things that others cannot see.
Paul is asking if these are the ways that the television show solves crimes. However, Della says that that’s not how they solve the crimes when they do solve crimes. They do it, according to Della, by using “deathbed confessions.” A “confession” is a statement admitting that you did something wrong. Sometimes, when the police catch a person who committed the crime, the person will just confess. They will say, “Okay, yes, I did it.” “Confession” comes from the verb “to confess” (confess).
A “deathbed confession” is when you admit to doing something wrong as you are dying. Your “deathbed” is literally the place, the bed, where you are lying as you are dying, and right before you die, you say, “Oh, yes. I murdered this person,” or “I did this terrible thing many years ago.” Of course, it doesn’t take any investigative work by the police if someone confesses to a crime, and Della is saying here that this television show doesn’t really solve any crimes unless someone has confessed to them.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Paul: What are you watching?
Della: I’m watching a really good show about cold cases. They take unsolved crimes from decades ago and reconstruct them, trying to solve them once and for all.
Paul: But after all this time, isn’t the trail cold? How do they solve the crimes with no new leads?
Della: They go over the witness testimony and use scientific methods that didn’t exist many years ago.
Paul: Isn’t there a statute of limitations for most crimes?
Della: Yes, but not for murder.
Paul: I really doubt a TV show can solve crimes that the police couldn’t crack. Are any crimes really ever solved on the show?
Della: Yes, of course.
Paul: How? Through crack investigative methods or a keen eye for detail?
Della: Deathbed confessions.
Paul: Ah.
[end of dialogue]
I’d like to thank our crack scriptwriter, Dr. Lucy Tse, for her hard work.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
cold case – a criminal investigation that has not been solved and will no longer be actively investigated until more information becomes available
* The police officer received a mysterious call with details about a cold case.
unsolved crime – an instance of someone breaking the law but never being punished for it because investigators cannot determine who did it
* Their daughter’s murder is referred to as an unsolved crime, but they’ve never given up hope that the criminal will be found.
decade – a period of 10 years
* Wow, Lorraine and Benny been married for three decades!
to reconstruct – to put something together again, either a physical object or an idea
* City planners are trying to reconstruct the original train routes from 50 years ago to help determine the new train routes.
once and for all – a phrase used to show that something will happen definitely and not need additional attempts
* Just tell me the truth once and for all. Are you the person who stole my lunch?
trail – a series of clues that lead someone in a particular direction, especially toward solving a problem
* Researchers are on the trail toward finding a cure for AIDS.
lead – a clue; a piece of information that provides some idea about what happened or who did something
* The police are encouraging people to call if they have any leads about the robbery.
witness testimony – statements made by people who saw something happen and were present during a situation or crime
* The accident happened in daylight in the middle of Times Square, so they’ll definitely be able enough witness testimony.
scientific method – the accepted process of conducting investigations, using a defined and generally used system
* If they had been following the scientific method, they would have had a control group that didn’t receive the treatment.
statute of limitations – the maximum period of time after an event when legal action can be taken
* What is the statute of limitations on assult in cases where the victim was a child?
murder – the crime of killing a person
* The mayor has promised to reduce the number of murders in the city by 20%.
to crack – to solve a mystery or complete a difficult investigation that has been too challenging for other people
* Scientists have been trying to crack the secrets of the universe.
crack – very sharp; astute; very smart and good at what one is doing
* Pierre is a crack shot with that gun and can hit the middle of the target every time.
investigative method – a process for conducting research, especially to solve a crime
* Basic investigative methods include photographing the location of all objects before moving anything at a crime scene.
keen eye for detail – the ability to notice many small things that other people might not notice
* Interior designers have a keen eye for detail and color.
deathbed confession – a statement that one makes while dying, admitting to something bad or wrong that one did earlier in life
* Grandpa Henry made a deathbed confession that shocked his wife, but she never told anyone what it was.
Comprehension Questions
1. What does Paul mean when he asks, “Isn’t the trail cold?”
a) He doesn’t think any new information is available.
b) He doesn’t think people are interested in the crimes anymore.
c) He thinks the investigators found the wrong criminal.
2. Which of these things would not be useful when solving a crime?
a) Scientific methods.
b) Statue of limitations.
c) Investigative methods.
Answers at bottom.
What Else Does It Mean?
cold case
The phrase “cold case,” in this podcast, means a criminal investigation that has not been solved and will no longer be actively investigated until more information becomes available: “Periodically, the bureau assigns an investigator to review cold cases before filing them away.” The phrase “basket case” is an informal phrase that refers to a person who is crazy: “Spending too much time alone can turn anyone into a basket case.” The words “uppercase” and “lowercase” describe capital and non-capital words: “I hate it when people write in uppercase (LIKE THIS) because it seems like they’re shouting.” Finally, a “pencil case” is a small box or pouch used to carry pencils, pens, and erasers: “Each student has to bring a folder, paper, and a pencil case on the first day of school.”
trail
In this podcast, the word “trail” means a series of clues that lead someone in a particular direction, especially toward solving a problem: “Investigating financial crimes must be exciting when you’re following the trail of corruption.” When talking about nature, a “trail” is a path in a natural area or through a park or forest: “We walked along a four-mile trail to get to the lake.” The phrase “trail mix” refers to a snack food made from nuts, dried fruit, and often small pieces of chocolate, often eaten while hiking: “The simplest trail mix is just raisins and peanuts.” Finally, when talking about politics, a “campaign trail” is all the places someone visits to try to get people to vote for one while attempting to win an election: “The senator’s campaign trail includes every town in the state with more than 20,000 residents.”
Culture Note
Interesting Methods Used to Solve Cold Cases
In general, the older a crime is, the more difficult it becomes to solve, because witnesses become “forgetful” (not able to remember something well) or “pass away” (die) and “evidence” (proof; objects that show what happened) “rots” (decomposes; becomes ruined) over time. However people have “turned to” (begun to use) “innovative” (new) methods to solve cold cases.
For example, in 1979 a woman named Susan Schwarz was murdered near Seattle, Washington, but there was no “clear” (easily understood) evidence and the murder was considered a cold case for more than 30 years. But then some “detectives” (investigators who work for the police) distributed “playing cards” (sets of 52 cards with different shapes and numbers, used to play games) to “prisoners” (people who are kept in jail). The cards had the names, photographs, and other information about the “victims” (the people who are hurt by crimes) in cold cases, as well as the promise of a “reward” (money given in return for something) for any “tips” (clues; leads) that would help police solve the crime. A prisoner saw a card with Susan’s information and told the detectives who had committed the crime.
Another interesting way to solve cold cases is to use the Doe Network, a website that uses “crowdsourcing” (using the Internet to have many people working together on a task) to gather details about cold cases. When enough people participate, the resulting clues can help detectives “piece together” (put things together in a certain way to make connections and provide meaning) the details of the crime. The U.S. Department of Justice has recognized the Doe Network for its efforts, specifically because the information on that site has been “instrumental” (very important and useful) in solving 66 cold cases.
Comprehension Answers
1 - a
2 - b