= 0979
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 979 – Types of Humor.
This is English as a Second Language Podcast episode 979. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Become a member of ESL Podcast by going to our website. You could also like us on Facebook at facebook.com/eslpod.
This episode is a dialogue between Kyle and Paulina about kinds of humor – things that make you laugh. Let’s get started.
[start of dialogue]
Kyle: Are you watching that sitcom again? It’s so stupid. There’s nothing witty or original about the humor.
Paulina: I don’t need highbrow jokes. I enjoy all kinds of comedy.
Kyle: You mean you like screwball and slapstick humor.
Paulina: Yes, so?
Kyle: So? It’s so juvenile.
Paulina: I know that it’s hard for people like you who like satire to appreciate the more wacky kinds of humor, but you might try getting off your high horse once in a while.
Kyle: I’m not snooty. I’m just discriminating. I like comedians with a dry sense of humor like that self-deprecating guy on that show I watch.
Paulina: That show is a snoozefest. That guy bores me to death.
Kyle: And this show does it for you?
Paulina: You bet.
Kyle: There’s no accounting for taste!
[end of dialogue]
Kyle begins our dialogue by saying to Paulina, “Are you watching that sitcom again? It’s so stupid.” A “sitcom” (sitcom) is a television show with a single group of characters, a single group of people, who do things that are supposed to be funny. If you remember the television show Friends, for example, which was popular in many countries around the world a few years ago, then you know what a sitcom is. “Sitcom” is actually short for “situation comedy” – a comedy where you have the same people in different situations each week.
Kyle thinks this sitcom is “stupid,” meaning it’s not very funny; it’s dumb. “There’s nothing witty or original about the humor,” Kyle says. “Witty” (witty) means funny, but in an intelligent way – not funny just because somebody falls down or just because somebody says something stupid. “Witty” is an adjective used to describe humor that is clever, that is intelligent. Kyle says, “There is nothing witty or original about the humor” – about the things that you are supposed to laugh at in the sitcom.
Paulina says, “I don’t need highbrow jokes. I enjoy all kinds of comedy.” A “joke” is something that is told to make you laugh – usually a short story, often just a sentence or two. “Highbrow” (highbrow) refers to something that is more intelligent or sophisticated than the average person or the average, in this case, joke. “Highbrow” refers to things that are very intellectual in nature, things that people think are very intelligent. Paulina says she does not need highbrow jokes.
She enjoys all kinds of “comedy” (comedy). “Comedy” is a category of movies or television shows or theatrical plays or anything, really, that makes you laugh. The category of comedy includes anything that is supposed to be funny. Kyle says, “You mean you like screwball and slapstick humor?” “Screwball” (screwball) is a somewhat old-fashioned term nowadays to refer to comedies that are silly. We might use also the adjective “goofy” (goofy) – the sorts of things that a child might laugh at. A lot of comedies by one of the great comedians of the twentieth century, Jerry Lewis, were screwball comedies – silly comedies.
“Slapstick (slapstick) humor” is humor that involves physical actions. Someone walking down the street and suddenly falling – that is slapstick humor. When you laugh at someone’s actions rather than what they are saying, especially if those actions involve falling down or doing something strange with their body, that would be slapstick humor.
Paulina says, “Yes” – she likes this kind of humor – “so?”
We use that word “so” as a question when we are saying to the other person that you don’t think there’s anything wrong with that. For example, you say to your wife, “This is the third time this week that we have had dinner at McDonald’s.” The idea behind this statement is that you’re not happy about that, or you think that this is strange. Your wife, however, may say, “So?” When she says that, she’s saying that there is no problem with that – that there should be no complaint related to that fact. You could also say, “So what?” meaning “Why is that important?” Paulina says, “Yes, so?”
Kyle says, “So?” The way that Kyle responds to Paulina’s “So?” by saying “So?” indicates that he’s surprised that she doesn’t think this is important. He’s surprised at the fact that she doesn’t think there’s anything wrong with what they were just talking about. Kyle says, “These comedies are so juvenile.” “To be juvenile” (juvenile) means to be immature – something you would expect out of a child or teenager, not from an adult.
Paulina says, “I know that it’s hard for people like you who like satire to appreciate the more wacky kinds of humor, but you might try getting off your high horse once in a while.” “Satire” (satire) is a type of humor that copies or exaggerates something else to make fun of it. It’s a kind of humor that sometimes can be done in a mean way, in a negative way, to make people laugh at something, but often to make them think about why this is a strange thing and why perhaps we should change it.
“Satire” is a kind of humor that is also a commentary on the way that we live our lives, often a negative commentary that is, of course, also meant to be funny. Paulina says that Kyle likes satire, which some people might consider a more intelligent kind of humor, but that she likes wacky kinds of humor. “Wacky” (wacky) is similar to screwball comedy. It’s comedy that is silly – the sort of thing that a young child might find funny. As an adjective, “wacky” also means crazy, weird, unpredictable, unexpected.
Paulina says that Kyle should try getting off his high horse once in a while. The expression “to get off your high horse” means to stop acting superior, to stop thinking that you are better than other people. If you can imagine someone on a horse riding by people who are walking, you get the idea that the person on the horse is higher, and perhaps thinks that he’s better than the people down below who are walking. Paulina is telling Kyle that he should not act so superior about what kind of humor he likes.
Kyle says, “I’m not snooty. I’m just discriminating.” “To be snooty” (snooty) means to be mean to others because you think you are better than they are. Another word we might use here is “snobby” (snobby). A “snob” (snob) is a person who thinks that they’re better than other people. A more informal way of saying this is “to be stuck (stuck) up.” “Stuck up” is an expression you would probably hear more often in high school among young people, but you could also use it in this case as well.
Kyle says he is “discriminating.” “To be discriminating” here means to be selective. “To discriminate” can be a positive thing: I am very picky, I’m very choosy, I’m very selective about the things that I like. I don’t like everything; I like only certain things. “Discriminate” can also be used in a negative way to refer to the treatment of someone based on perhaps the color of their skin or their sex (whether they’re male or female). That sort of “discriminating” is a bad thing, we usually believe. However, here it’s used to mean selective.
Kyle says, “I like comedians with a dry sense of humor like that self-deprecating guy on that show I watch.” A “dry (dry) sense of humor” is comedy that is considered perhaps a little bit more intellectual. A “dry sense of humor” would involve jokes that someone tells you in perhaps even a serious way. You have to then figure out that it’s supposed to be funny. That’s the general idea here.
Kyle says he likes a certain comedian who is self-deprecating. “To be self-deprecating” means to say bad things about yourself, but doing it in such a way that you are, in this case, being funny. “Self-deprecating” is usually considered a good quality in someone, not just someone who’s trying to be funny. If we say, “This man is self-deprecating,” we mean that he doesn’t think he is superior to other people. He understands that he’s not perfect. He recognizes his faults and problems.
Paulina says that this particular show that Kyle watches is “a snoozefest.” “To snooze” (snooze) means to sleep. “Fest” (fest) here relates to a festival, a celebration. However, when Paulina uses this word, combining “snooze” with “fest,” she’s making a joke. She’s saying this show is very boring. This show is not interesting. This show will make you fall asleep it’s so boring. In fact, the next thing Paulina says is, “That guy bores me to death.” “To bore (bore) someone to death” means to make someone feel very bored, to make someone feel very uninterested.
Kyle says, “And this show does it for you?” The expression “to do it for you” here means to satisfy you, to give you something that you are looking for. Some people, for example, like to go to Disneyland because they like to ride on the big rides. That doesn’t do it for me, meaning that’s not something I like to do. I last went to Disneyland when I was nine years old. It’s not something I enjoy doing. Paulina says, “You bet,” meaning yes, this show does it for me; I like this show.
Kyle then says, “There’s no accounting for taste.” This is an old expression. “There is no accounting (accounting) for taste (taste)” is used when another person has very different likes and dislikes from you. It’s used when another person likes certain things that you don’t like and that you don’t think anyone, perhaps, should like. However, you don’t want to continue talking about it, perhaps, or you don’t want to continue criticizing the other person. So you say, somewhat insultingly, really, “There’s no accounting for taste,” meaning everyone has things that they like and dislike and there, in a sense, is no real rational way for explaining why some people like some things and other people like other things.
However, when you say this expression, you are sort of insulting the other person. You’re saying, “Well, you have really bad taste” – that is, you have very bad preferences. You like things that you shouldn’t like, but there’s no way for me to explain that. That’s what’s meant by the phrase “there is no accounting for” something – there’s no way of trying to explain it, and so I won’t try.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Kyle: Are you watching that sitcom again? It’s so stupid. There’s nothing witty or original about the humor.
Paulina: I don’t need highbrow jokes. I enjoy all kinds of comedy.
Kyle: You mean you like screwball and slapstick humor.
Paulina: Yes, so?
Kyle: So? It’s so juvenile.
Paulina: I know that it’s hard for people like you who like satire to appreciate the more wacky kinds of humor, but you might try getting off your high horse once in a while.
Kyle: I’m not snooty. I’m just discriminating. I like comedians with a dry sense of humor like that self-deprecating guy on that show I watch.
Paulina: That show is a snoozefest. That guy bores me to death.
Kyle: And this show does it for you?
Paulina: You bet.
Kyle: There’s no accounting for taste!
[end of dialogue]
The writer of our witty, humorous dialogues is the one and only Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
sitcom – a situation comedy; a television show with a single group of characters in a different situation each week, designed to be funny and entertain people
* Friends and Seinfeld are two of my favorite sitcoms.
witty – clever, funny, and intelligent
* Matt is so witty, always saying things about current events that make the people around him laugh.
humor – things that make people laugh; things that are funny
* I was just joking! Don’t you have a sense of humor?
highbrow – acting superior to others, especially more intelligent or sophisticated
* Five-course meals and highbrow restaurants are fine, but every once in a while, it’s nice to just eat a hot dog.
joke – a short story or a question and answer that is told to make people laugh
* Did you hear the joke about why the chicken crossed the road?
comedy – a genre or category of movies, shows, and plays that entertain people and make the audience laugh
* The new movie is a cute comedy, but it didn’t make me laugh out loud.
screwball – goofy, silly, and irresponsible
* If the managers catch Yvonne doing any more screwball reports like that last one, she could lose her job!
slapstick – physical comedy, such as slipping on a banana peel; the use of absurd physical actions to make people laugh, especially in a movie, show, or play
* They’re trying to sell window cleaner through slapstick comedy, like showing someone walking into a window that’s so clean nobody can see it.
juvenile – immature; for children, not for adults
* Some people might think playing dodgeball is juvenile, but Jacques has always loved that game.
satire – a type of humor that copies or exaggerates something else to make fun of it, sometimes in a mean way, in order to make people laugh or think about something in a new way
* The play is a satire of the American healthcare system.
wacky – crazy and unexpected; weird and unpredictable
* The chef is trying some wacky combinations, like fish with strawberries, and ice cream with green beans.
to get off (one’s) high horse – to stop acting superior; to stop thinking that one is better than other people
* When Nolan lost his job, he had to get off his high horse and ask for help.
snooty – snobby; very proud and a little bit mean to others; stuck up
* Jo is snooty toward anyone who doesn’t make as much money as she does.
discriminating – picky; choosy; wanting and selecting only certain characteristics in something
* This wine is expensive, but it will please even the most discriminating taster.
dry sense of humor – an ability to produce or appreciate intellectual humor where the funny story or joke is told in a serious, quiet way and the listener has to think to realize why something is funny
* Do you prefer outlandish comics, or ones with a dry sense of humor?
self-deprecating – saying bad things about oneself, undervaluing one’s abilities, or saying that one is not good or important, often used for humor
* Even though Geoff makes a lot of self-deprecating comments, he actually has very high self-esteem.
snoozefest – something that is very boring and uninteresting and makes people want to fall asleep
* This seminar is a snoozefest. We’ve been here for three hours and we still haven’t heard anything we didn’t already know before.
to bore (someone) to death – to be very boring; to be very uninteresting
* That speaker bore us to death with all of those statistics!
to do it for (someone) – to meet someone’s needs; to satisfy someone; to give someone what he or she is looking for; to make someone feel content
* What do you do to relax? Does a massage really do it for you?
there’s no accounting for taste – a phrase meaning that one dislikes with what another person likes, but accepts that people are different and believes their preferences cannot be explained
* Cayden painted their living room bright orange and dark green. I think it’s ugly, but he loves it. There’s no accounting for taste.
Comprehension Questions
1. Which type of humor would be most likely to be witty?
a) Slapstick humor
b) Satire
c) Wacky humor
2. Why doesn’t Paulina like the show that Kyle likes?
a) Because she doesn’t find it interesting.
b) Because the comedian passed away.
c) Because it’s intended for young children.
Answers at bottom.
What Else Does It Mean?
juvenile
The word “juvenile,” in this podcast, means immature and for children, not for adults: “That artwork is so juvenile. Even my four-year-old daughter could paint like that.” The word “juvenile” also refers to people who are not viewed as adults by the government, usually because they are younger than 18 years old: “Do you think it’s right for juveniles to receive lighter fines and punishments than adults?” A “juvenile delinquent” is a young person who has been convicted of a crime, or who acts like a criminal: “Jesse doesn’t feel safe walking around downtown at night because there are so many juvenile delinquents on the streets.” Finally, when talking about animals, a “juvenile” is a young animal, not yet an adult: “The mature birds have red wings, but the juveniles are covered with white feathers.”
discriminating
In this podcast, the word “discriminating” means picky, choosy, and wanting and selecting only certain characteristics in something, especially when one is able to distinguish between good and poor types of something: “The salesperson said that these diamond earrings would be perfect for even the most discriminating woman.” As a verb, “to discriminate” means to differentiate between two things: “How can we discriminate between crocodiles and alligators?” Or, “Can you discriminate between the calls of blue whales and other types of whales?” Finally, the phrase “to discriminate against (someone)” means to treat a group of people differently and unfairly based on some characteristic, especially gender, age, religion, skin color, or sexual orientation: “The company was found guilty of discriminating against certain applicants in its hiring practices.”
Culture Note
The Mark Twain Prize for American Humor
Mark Twain (see English Café 34) was a famous American “novelist” (writer of stories that are book-length) and “humorist” (person who writes about things in a funny way). Each year since 1998, the John F. Kennedy Center for the Performing Arts has awarded “The Mark Twain Prize for American Humor” “in his honor” (to remember and admire someone’s contributions or work). The award is presented to an individual who has made significant contributions to American culture through humor.
The Kennedy Center sells tickets to the awards reception, and the “proceeds” (money earned) from ticket sales is an important “fundraiser” (an event or activity that makes money, especially for a nonprofit organization) for the organization. In 2003, a single ticket to the event cost $1,000, and special event packages cost up to $50,000. Many comedians and other “celebrities” (people who are famous, especially for singing, acting, or playing sports) attend the event to celebrate the “award recipient” (the person who receives the award). The event is recorded and “broadcasted” (shown on TV) for people who can’t “afford” (be able to pay) the “hefty” (significant; big) ticket price.
Award recipients receive a “bronze” (a reddish-colored metal) “bust” (a sculpture of a person showing the shoulders, neck, and head) of Mark Twain. But more importantly, they receive “recognition” (notice and admiration) from other people that the work is important and “appreciated” (liked and admired). Past award recipients have include Bill Cosby (see English Café 55), Steve Martin, Lily Tomlin, Tina Fey, Ellen DeGeneres, Will Ferrell, and Whoopi Goldberg. The 2013 award recipient was Carol Burnett, an actress and author who is best known for her “eponymous” (sharing the same name) TV show, The Carol Burnett Show.
Comprehension Answers
1 - b
2 - a