= 0983
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 983 – Breaking Bad Habits.
This is English as a Second Language Podcast episode 983. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. Our website is ESLPod.com. Go there. Become a member of ESL Podcast and download a Learning Guide for this episode. You can also like us on Facebook at facebook.com/eslpod.
This dialogue is about breaking bad habits – trying to stop doing things that you have been doing probably for a long time, but that are bad for you. Let’s get started.
[start of dialogue]
Counselor: Welcome, everybody. You’ve all joined this support group because you have some bad habits that you’d like to break. Would anyone like to introduce themselves and tell us about their bad habit?
Stu: Uh yeah, I’m Stu and my wife signed me up for this support group because she says I have some really bad habits. One of my worst is my nail biting. You can see that they’re pretty ragged.
Counselor: Thank you, Stu. Is there anyone else . . .?
Stu: Oh yeah, I also smack my gum. That drives my wife crazy, so I try not to do it in her presence.
Counselor: Well, thanks for sharing, Stu. If we could move on to . . .
Stu: I also tend to tap my fingers and crack my joints, which my wife says is really annoying, though her hair twirling is pretty annoying to me.
Counselor: Stu? Let’s let a few other people . . .
Stu: Oh yeah, I forgot to mention what my wife says is my most annoying bad habit.
Counselor: What is that?
Stu: I tend to interrupt people in conversation.
Counselor: Really? I hadn’t noticed.
[end of dialogue]
Our dialogue begins with the counselor – the person who is providing advice and guidance to people – welcoming everyone to this group. We’re in some sort of group counseling session, and so the leader of the group is called the “counselor” (counselor). Someone who is called a “counselor” in a situation like this typically will have some training in how to help people, but not quite as much as a regular psychologist or psychiatrist.
The counselor says, “Welcome everybody. You’ve all joined this support group because you have some bad habits that you’d like to break.” A “support group” is a group of people who have similar problems or challenges and who want help from other people in similar situations. Sometimes talking to other people who have the same problem or issue that you have can help you.
“Bad habits” are things that you do over and over again, often without thinking about it very much, that have negative consequences for you, that are bad for you. Some people might say smoking cigarettes is a bad habit. It’s a difficult habit to break, however. “To break (break) a habit” means to stop doing the habit – to no longer do it. Of course, you can also have “good habits,” things that you do every day or frequently that are good for you. Brushing your teeth and taking a shower, those are good habits – things that are good for you.
The whole idea of good habits and bad habits goes back at least to the time of the Greek philosopher Aristotle, who wrote a book called The Ethics, about the formation of good and bad habits – “moral habits” and “intellectual habits,” as he called them – but we’re not going to talk about Aristotle today. We’re going to talk about the support group that is helping people break bad habits.
The counselor says, “Would anyone like to introduce themselves and tell us about their bad habit?” Would anyone like to tell us their name and tell us what their bad habit is? Stu says, “Uh yeah, I’m Stu and my wife signed me up for this support group because she says I have some really bad habits.” Poor Stu. Stu doesn’t think, apparently, he has bad habits, but his wife thinks that he has some bad habits. So, his loving wife “signed him up” for this support group. “To sign someone up” is a phrasal verb meaning to put someone’s name on a list saying that they will participate in a certain activity. Another verb we could use here is “to enroll” (enroll).
Stu’s wife has signed him up for this support group because his wife thinks that he has “some really bad habits.” Of course, all wives think that their husbands have really bad habits. That’s part of being a wife. I’m just kidding, of course, honey. Stu says, “One of my worst” – meaning one of my worst habits – “is nail biting.” Your “nail” (nail) is a part of your hand. At the end of each finger, you have “nails” (nails). “To bite” (bite) means to use your teeth to eat or to break something.
In this case, Stu is biting his nails, which some people believe is a bad habit. People bite their fingernails, in particular. I guess you could bite your toenails also, but that would be very difficult for most people. Stu says, “You can see” – he’s showing the group his fingernails – “that they’re pretty ragged.” “To be ragged” (ragged) means to be uneven, to be not smooth. He’s showing the group his fingernails and indicating that yes, he does in fact bite his nails. The counselor says, “Thank you, Stu. Is there anyone else?” But Stu isn’t finished talking. Stu says, “Oh yeah, I also smack my gum. That drives my wife crazy, so I try not to do it in her presence.”
“Gum” (gum) refers to bubblegum or chewing gum, something you put in your mouth, that is usually flavored, and you chew it – you bite down on it, up and down with your teeth – to get the flavor out of the gum. “To smack (smack) your gum” means to make loud noises or sounds while you are chewing your gum. I don’t have any gum in my mouth right now, so I can’t demonstrate. Stu says that this smacking of his gum drives his wife crazy, meaning it makes his wife angry or upset. He tries not to smack his gum “in her presence,” meaning when his wife is there with him.
The counselor says, “Well, thanks for sharing, Stu.” “To share” (share) means to talk about something with other people, especially to talk about your experiences or your opinions about something. We sometimes use that verb sarcastically when someone is telling us something that we don’t really want to know, perhaps because it’s too personal. We might say to that person, “Thanks for sharing,” meaning I didn’t really want you to tell me that. It’s kind of an insulting thing to say.
Stu isn’t being insulted by the counselor. The counselor simply wants someone else to talk. That’s why she says, “If we could move on to . . .” “To move on to” something or someone means to go to someone else – in this case, to have someone else talk about their bad habits, not Stu. But Stu isn’t finished. He says, “I also tend to tap my fingers and crack my joints, which my wife says is really annoying. “To tend (tend) to” do something is to often do something, especially when you’re not thinking about it.
Stu tends “to tap” (tap) his fingers. “To tap your fingers” is to hit one or more of your fingers against a table or something else, usually several times, over and over again, making a small noise. People sometimes tap their fingers at a meeting when they’re bored, which is to say at almost every meeting. This is considered by some to be a bad habit.
Stu also cracks his joints. “To crack (crack) your joints (joints)” is to move or bend a part of your body that connects two bones. Usually we talk about cracking our “knuckles” (knuckles). Your knuckles are the parts of your hand that connect the fingers to the main part of your hand. “To crack your knuckles” – I’m not sure if I can do this anymore – is to bend your hands in such a way that they make a sound. Cracking your knuckles, or cracking your joints, is to move your bones in such a way that they make a noise – like that.
Stu’s wife finds this very annoying. Something that is “annoying” (annoying) is something that is irritating, something that bothers you, Stu says that his wife’s hair twirling is pretty annoying to him, as well. “To twirl (twirl) your hair” is to take a small section of your hair and move it around in circles with your finger, especially when you’re bored or distracted. It’s something that you usually will see with girls and women, because they typically have longer hair.
I remember when I was teaching high school many years ago. (Yes, I taught high school many years ago. It’s kind of scary.) The young girls in my classes would often twirl their hair because they were bored by my lectures, by my presentations, which I can understand. Stu’s wife twirls her hair, and that is annoying to Stu. The counselor says, “Stu, let’s let a few other people . . .” She’s about to say, “Let’s let a few other people talk,” but Stu doesn’t wait long enough for her to finish her sentence.
Stu continues talking. He says, “Oh yeah, I forgot to mention what my wife says is my most annoying habit.” The counselor says, “What is that?” Stu says, “I tend to interrupt people in conversation.” “To interrupt” (interrupt) is to speak when someone else is still speaking, before they have had a chance to finish what they want to say. That, of course, is exactly what Stu is doing here with the counselor.
The counselor then makes a joke at the end. She says, “Really? I hadn’t noticed,” meaning I didn’t even realize that you have this bad habit of interrupting. Of course, she did, and that’s why she’s saying this in a sarcastic way, in a joking way.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Counselor: Welcome, everybody. You’ve all joined this support group because you have some bad habits that you’d like to break. Would anyone like to introduce themselves and tell us about their bad habit?
Stu: Uh yeah, I’m Stu and my wife signed me up for this support group because she says I have some really bad habits. One of my worst is my nail biting. You can see that they’re pretty ragged.
Counselor: Thank you, Stu. Is there anyone else . . .?
Stu: Oh yeah, I also smack my gum. That drives my wife crazy, so I try not to do it in her presence.
Counselor: Well, thanks for sharing, Stu. If we could move on to . . .
Stu: I also tend to tap my fingers and crack my joints, which my wife says is really annoying, though her hair twirling is pretty annoying to me.
Counselor: Stu? Let’s let a few other people . . .
Stu: Oh yeah, I forgot to mention what my wife says is my most annoying bad habit.
Counselor: What is that?
Stu: I tend to interrupt people in conversation.
Counselor: Really? I hadn’t noticed.
[end of dialogue]
We’d like to thank our scriptwriter, Dr. Lucy Tse, for her scripts, which are always enjoyable and never annoying.
From Los Angeles, California, I’m Jeff McQuillan. I’m sometimes annoying, but I’d like to thank you for listening to us today. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
counselor – a person whose job is to provide advice and guidance, but without as much training as a psychologist
* The school counselor helps students evaluate their options as they apply for college.
support group – a group of people who have similar challenges or problems and meet regularly to help each other
* Ramiro met his new wife at a support group for single parents.
bad habit – something that one does repeatedly, without thinking about it and without being in control of it, and that has negative results or is harmful in some way
* Snacking between meals is a bad habit, because it can lead to weight gain.
to break – to stop doing something; to no longer have a habit
* How did you finally break your addiction to cigarettes?
to sign (someone) up – to enroll someone in a group or activity; to put someone’s name on a list of participants
* How many parents have signed their kids up for the volleyball team?
nail biting – the practice and bad habit of using one’s teeth to make one’s nails shorter, often as a result of being nervous or stressed
* Meghan must be stressed about exams, because she’s started nail biting again.
ragged – not smooth or even; uneven and irregularly shaped
* Why are the edges of this piece of paper so ragged?
to smack (one’s) gum – to make loud popping noises while chewing gum
* Chewing gum is never appropriate during an important business presentation, but it’s even worse if someone is smacking his or her gum.
in (one’s) presence – with another person nearby; where another person can hear and see one’s words and actions
* He never uses bad words in his mother’s presence.
to share – to talk about something with other people, especially to talk about one’s experiences, feelings, opinions, or beliefs
* Jeremiah has never shared his feelings about his mother’s death.
to move on to – to go to the next person or the next task; to finish one thing and begin the next thing
* Once this presentation is done, we’ll finally be able to move onto the next assignment.
to tend to – to have a tendency; to often do something, especially without thinking about it
* Jas tends to turn on the computer and check her email before she says “hi” to her co-workers in the morning.
to tap (one’s) fingers – to hit one’s fingers against a table or another surface repeatedly and rhythmically, making a small noise, especially when one feels bored or is concentrating on something
* Jesse tends to think better when he’s tapping his fingers, but all the other team members find it very distracting.
to crack (one’s) joints – to move or bend a body part that connects two bones in a certain way so that it makes a loud popping noise
* The chiropractor is really good at cracking patients’ joints and making them feel better.
annoying – irritating; bothersome; making other people feel frustrated because they dislike something that is happening
* I hate it when my little brother repeats everything I say. It’s so annoying!
hair twirling – the practice and bad habit of taking a small section of one’s long hair and moving it in circles repeatedly around one’s finger, especially when one is bored or distracted
* She seemed well qualified for the job, but we decided not to hire her because of all the hair twirling during the interview.
to interrupt – to speak when someone else is speaking, before he or she has finished; to not allow someone to continue what he or she is doing
* We interrupt this television broadcast with an emergency weather report.
Comprehension Questions
1. Which of these habits involve the mouth?
a) Smacking gum
b) Tapping fingers
c) Cracking joints
2. Why does the counselor want Stu to stop talking?
a) Because she wants to discuss more important topics.
b) Because she wants other people to have an opportunity to speak.
c) Because she wants him to pay more money.
Answers at bottom.
What Else Does It Mean?
to break
The verb “to break,” in this podcast, means to stop doing something or to no longer have a habit: “Getting a lot of phone calls breaks Mia’s concentration while she’s trying to study.” The phrase “to break (someone’s) heart” means to hurt someone’s feelings, especially by bringing the end to a romantic relationship: “James broke her heart and she didn’t go on another date for the next two years.” The phrase “to break the bank” means to cost a lot of money or to be very expensive: “Replacing the roof on the house really broke the bank.” Finally, the phrase “to break the silence” means to make a noise or begin talking after a period of no sound: “Nobody knew how to break the silence after Karly’s shocking announcement.”
to share
In this podcast, the verb “to share” means to talk about something with other people, especially to talk about one’s experiences, feelings, opinions, or beliefs: “Is there anything else you’d like to share with the team before the CEO comes in?” The verb “to share” also means to let someone use something that one has or owns: “It’s difficult for little kids to share their favorite toys.” The phrase “to share (someone’s) view” means to agree with someone: “Do your parents share your religious views?” Finally, the phrase “share and share alike” means that everyone should have the same amount of something or the same access to something: “Our company is based on the idea of share and share alike, so that employees are paid higher bonuses when we have a good year.”
Culture Note
Common Bad Habits in Conversation
Many people have bad habits in “conversation” (speaking with other people). For example, many people use “filler words,” or small words that have no meaning, but are “inserted into” (put into) sentences to avoid silence, especially while one is thinking. Words like “um” and “er” are common filler words, and are often “perceived” (seen as; thought to be) a sign of weakness or “insecurity” (not feeling self-confident). Many people who want to become “public speakers” (people who make presentations to large audiences) records their speeches and count the number of times they say “um” or “er” so that they can try to “reduce” (decrease; bring down) that number to zero.
Other people, especially young people, use “like” as a filler word. For example, they might say, “And she was like, okay, go ahead and do it, but then I was like, wait a minute, are you sure?” A speaker who uses “like” this way sounds immature and unprofessional. A similar bad habit is when people, especially young people, use the verb “to go” instead of “to say.” For example, someone could say, “So my teacher went, ‘Have you studied for the test?’ and I went, “Um, a little bit.’”
Finally, many young girls have a bad habit of using the wrong “intonation” (the tone or pitch of one’s words) at the end of sentences. Normally a sentence should end with a downward pitch, or with a lower note at the end of sentence. The lower pitch “indicates” (shows) that the sentence has ended. But many young girls instead use the intonation of a question, ending on a higher pitch. They might do this on even very simple statements, such as when answering “What’s your name?” as, “Wendy?” instead of “Wendy.” This, too, is perceived as immaturity and insecurity.
Comprehension Answers
1 - a
2 - b