= 0987
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 987 – Taking Prescription Drugs.
This is English as a Second Language Podcast episode 987. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
The website for this wonderful podcast is ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode.
This episode is a dialogue between Paula and Marcus about taking drugs – medicine that the doctor has given you to take. Let’s get started.
[start of dialogue]
Paula: Okay, I’m off to bed.
Marcus: Wait a second. Where are you going with all of those pill bottles?
Paula: My doctor prescribed a couple of medications to help me sleep.
Marcus: Let me see those. You have four different medications here. This is a painkiller, this is a sedative, this is a tranquilizer, and this is a stimulant.
Paula: I don’t take that last one when I go to bed.
Marcus: You mean you take the first three every night?
Paula: Not every night.
Marcus: I can’t believe that your doctor would prescribe all three of these medications just to help you sleep. This seems like overkill.
Paula: I saw more than one doctor. They each gave me a different prescription.
Marcus: How do you know they won’t interact and produce side effects?
Paula: A doctor prescribed each one. I’m sure they’re safe.
Marcus: Yes, but does the left hand know what the right hand is doing? I’m confiscating these until you can talk to a doctor or pharmacist to make sure you won’t overdose by taking all three of these at one time.
Paula: But how will I fall asleep until then?
Marcus: You’re always telling me how boring I am. I’ll just regale you with stories of my youth. Let’s start at the beginning. My earliest memory is . . .
[end of dialogue]
Paula begins our dialogue by saying to Marcus, “Okay, I’m off to bed,” meaning I’m going to go to sleep now. Marcus says, “Wait a second” – wait. “Where are you going with all of those pill bottles?” A “pill” (pill) is usually a small, often round object that is, in fact, medicine that you put in your mouth and swallow. That’s one of the most common ways of taking medicine. A “pill bottle,” then, would be a small bottle in which you keep your pills.
Paula says, “My doctor prescribed a couple of medications to help me sleep.” “To prescribe” (prescribe) is to write down a type of medication that a person should take. Doctors prescribe drugs. In fact, in the United States, only licensed doctors can prescribe drugs. There are certain kinds of drugs that you could only get if a doctor says it’s okay. These are called “prescription drugs.” “Prescription” comes from the verb “to prescribe.”
We also use this word “to prescribe” more generally, when people are talking about giving advice or recommendations to someone. “I prescribe three days of rest for you.” It’s as though you were a doctor and you were giving someone a prescription. You were telling them something that would be good for them to do. Paula’s doctor “prescribed a couple of medications” for her. “Medications” refers to drugs, medicine – in this case, pills. “Medication” is a general word for drugs that you are given to make you well.
Marcus says, “Let me see those. You have four different medications here. This as a pain killer, this is a sedative, this is a tranquilizer, and this is a stimulant.” There are four different kinds of drugs mentioned here. The first is a “painkiller” (painkiller) – one word. A painkiller is a medicine that, you can guess, helps reduce pain. Aspirin would be a painkiller. Codeine would be a painkiller. A “sedative” (sedative) is a medicine that calms you down. It calms you down in order to make you sleep. A sedative makes you sleepy.
A “tranquilizer” (tranquilizer) is a medicine that makes you feel calmer. It’s a medicine that is given to reduce your anxiety, to make you less worried. Tranquilizers are also used with animals to make them less aggressive, to quiet them down, to calm them down. My neighbor’s dog, for example, when he’s barking a little bit too much and my neighbors aren’t home, I give him a little tranquilizer. It keeps him calm. You know what I’m saying?
A “stimulant” (stimulant) is a drug that gives you more energy, that gets you more excited. One of the most common substances that we take in the United States as a stimulant would be coffee, caffeinated coffee, because “caffeine,” which is a substance in coffee, is a stimulant. It gets you more excited. So, people often have coffee, like I do, in the morning to wake them up. Paula says, “I don’t take that last one when I go to bed.” She’s saying she doesn’t take a stimulant when she’s going to bed because, of course, she wants to fall asleep, not wake up. Marcus says, “You mean you take the first three every night?” That is, the painkiller, the sedative, and the tranquilizer. Paula says, “Not every night.”
Marcus says, “I can’t believe that your doctor would prescribe all three of these medications just to help you sleep.” Marcus doesn’t understand why the doctor would give her three medicines to help her sleep. He says, “This seems like overkill.” “Overkill” (overkill) is too much of something. For example, if you are a man and you are going out on your first date with a woman, it would be overkill to buy her roses, buy her a new car, buy her dinner, and propose to marry her. That would be way too much. You would probably scare her away. So, guys, don’t do that. That’s an example of overkill.
Paula says, “I saw more than one doctor.” Now we understand how Paula got all these different prescriptions. She saw different doctors. Paula says, “They each gave me a different prescription” – each doctor. Marcus says, “How do you know they won’t interact and produce side effects?” When we talk about drugs “interacting,” we’re referring to how the two things will work together. Sometimes drugs will give you worse problems if you take them together. That’s why you need to tell your doctor all the different drugs you are taking if you are seeing more than one doctor, as is the case with Paula.
“Side effects” are other things that the drug does to your body that isn’t supposed to help you, but that sometimes can’t be avoided. So, for example, when people take certain drugs for their allergies, the drugs make them sleepy. This is a side effect. That’s not the reason you’re taking the drug. You’re taking the drug because of your allergies. But in addition, the drug may also have this side effect of making you sleepy. I’ve had a few parents email me to tell me that my podcast in English makes their children sleepy, even though the children don’t understand English. So, I guess I could be considered a tranquilizer. My wife certainly thinks so whenever I talk to her.
Paula says, “A doctor prescribed each one. I’m sure they are safe.” Paula thinks the drugs are safe because she got them from doctors, even though she got them from different doctors and didn’t tell the doctors that she was getting these different drugs.
Marcus says, “Yes” – meaning yes, they were prescribed by doctors – “but does the left hand know what the right hand is doing?”
This is an old expression meaning that one person is doing something, and another person is doing something else, and neither one knows what the other one is doing, so you could have some unexpected consequences – something bad could go wrong. The left hand has to know what the right hand is doing in an organization or any group. Everyone has to know what everyone else is doing, typically, otherwise you may cause problems for yourself.
Marcus says, “I’m confiscating these until you can talk to a doctor or pharmacist to make sure you don’t overdose by taking all three of these at one time.” Marcus is saying that he is going to “confiscate” (confiscate) these drugs. “To confiscate” something means to take something away from someone without the person’s permission. Usually, someone in authority can confiscate something from another person.
A teacher in a high school classroom might confiscate a student’s cell phone if the student is talking during class, or texting, or tweeting, or Instagramming, or whatever it is that high school students do nowadays. That is an example of the verb “confiscate.” The police might confiscate drugs from your car if they find them there. So, don’t put them in your car.
Marcus says he is going to confiscate these drugs from Paula until Paula “can talk to a doctor or pharmacist.” A “pharmacist” (pharmacist) is someone who prepares medicines, prepares drugs to give to people who have a prescription, who have permission from their doctors. A pharmacist used to be called a “druggist,” although we don’t use that term in the United States very much anymore.
“Overdose” (overdose) is when someone takes too much of a drug and dies, often because of taking too much of the drug. An overdose doesn’t necessarily kill you, but it can kill you, and it can be very dangerous if you take too many of a certain kind of drug or medicine. Unhappily, some famous celebrities here in Los Angeles sometimes overdose on illegal drugs.
Marcus doesn’t want Paula to overdose on these legal prescription drugs. Paula says, “But how will I fall asleep until then?” She’s wondering how she is going to be able to fall asleep from now until when she has the opportunity to talk to a pharmacist or doctor. Marcus says, “You’re always telling me how boring I am. I’ll just regale you with stories of my youth.” “To regale” (regale) here means to tell stories to someone in a funny and interesting way, or to provide some sort of amusement to someone by talking to them.
Marcus is joking, of course. He’s saying that Paula thinks he’s boring, so he’ll just tell Paula some stories about his youth. Your “youth” (youth) is the years when you were growing up as a child. Marcus says, “Let’s start at the beginning. My earliest memory is . . .” And then he, of course, starts telling Paula stories that are so boring that she will fall asleep. Pretty much what happens to my wife.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Paula: Okay, I’m off to bed.
Marcus: Wait a second. Where are you going with all of those pill bottles?
Paula: My doctor prescribed a couple of medications to help me sleep.
Marcus: Let me see those. You have four different medications here. This is a painkiller, this is a sedative, this is a tranquilizer, and this is a stimulant.
Paula: I don’t take that last one when I go to bed.
Marcus: You mean you take the first three every night?
Paula: Not every night.
Marcus: I can’t believe that your doctor would prescribe all three of these medications just to help you sleep. This seems like overkill.
Paula: I saw more than one doctor. They each gave me a different prescription.
Marcus: How do you know they won’t interact and produce side effects?
Paula: A doctor prescribed each one. I’m sure they’re safe.
Marcus: Yes, but does the left hand know what the right hand is doing? I’m confiscating these until you can talk to a doctor or pharmacist to make sure you won’t overdose by taking all three of these at one time.
Paula: But how will I fall asleep until then?
Marcus: You’re always telling me how boring I am. I’ll just regale you with stories of my youth. Let’s start at the beginning. My earliest memory is . . .
[end of dialogue]
If you want to improve your English, I prescribe listening to all of the dialogues written by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
pill bottle – a small bottle with a tight-fitting lid, used to hold medicine
* Pill bottles need to have child-proof caps so that little kids aren’t able to open them and take medicine that could be harmful to them.
to prescribe – for a doctor to write down the type of medication that a person should take, especially when that medicine is available only from a pharmacist with written instructions
* The doctor prescribed an antibiotic for Harvey’s sore throat.
medication – medicine; drug; a chemical substance that is used to make a sick or injured person feel better and/or get well
* Wouldn’t it be great if there were a medication that could cure cancer?
painkiller – a medicine that reduces or eliminates pain (severe physical discomfort)
* The doctor recommended taking these painkillers for at least three days after the surgery.
sedative – a medicine or another substance that makes people feel calmer, slower, and sleepier
* Do you think it’s safe to give your child a sedative before flying internationally?
tranquilizer – a medicine or another substances that makes people feel calmer, less worried, and less aggressive
* The scientists shot the lion with a tranquilizer so that they could approach it and try to determine what was wrong with its leg.
stimulant – a medicine or another substance that makes people feel more excited and energetic
* Coffee is a stimulant, so drinking it in the evening before bedtime might make it difficult for you to fall asleep.
overkill – too much of something; an extreme, especially a harmful one
* This semester, Randall is taking 24 credit hours while most students take just 15 or 18. Doesn’t that seem like overkill?
to interact – for two or more objects or people to act in a way that affects each other; to have an effect on something and be affected by it at the same time
* Sociologists are very interested in studying how human beings interact with each other and with institutions.
side effect – an unintended result of something, especially when talking about medicine
* The side effects of this medication include headaches, dizziness, and nausea.
the left hand doesn’t know what the right hand is doing – when one person in an organization does not know what another person is doing, so their actions overlap or affect each other in some unexpected way
* If you’re going to ask people to bring food to the party, tell them what type of food to bring. Otherwise the left hand doesn’t know what the right hand is doing and you might end up with 10 bowls of salad, but no entrees or dessert.
to confiscate – to take something away without the owner’s permission, especially when that person should not have the thing
* The school administrators are authorized to confiscate any drugs, alcohol, or weapons that students might bring to school.
pharmacist – a person whose job is to prepare medicines and give them to people who need them under a doctor’s orders; a druggist
* The pharmacist said I should take the pills with food twice a day for 10 days.
to overdose – to consume too much of a medicine or drug so that one becomes sick or dies
* Shane’s parents have tried to help him to stop using drugs because they are terrified that one day he’ll overdose on cocaine or heroin.
to regale – to be funny and entertaining by telling stories to someone; to provide amusement and entertainment to someone through one’s words
* The comedian regaled the audience with stories of her experience traveling overseas.
Comprehension Questions
1. Which of these things would help someone fall asleep?
a) A painkiller.
b) A sedative.
c) A stimulant.
2. Why is Marcus concerned about Paula’s medicine?
a) Because he thinks she should use organic, herbal treatments.
b) Because he thinks she’s spending too much money on medicine.
c) Because he thinks the combination of drugs might be dangerous.
Answers at bottom.
What Else Does It Mean?
pill
A “pill bottle,” in this podcast, is a small bottle with a tight-fitting lid, used to hold medicine: “Every Saturday evening, Hazel opens all her pill bottles and takes out the pills she’ll need to take during the coming week.” Although it is a little old-fashioned, the phrase “to be a pill” means to misbehave and be annoying: “Their son can be such a pill when he’s tired and hungry!” Finally, the phrase “a bitter pill to swallow” describes something that is very unpleasant or unfortunate: “Selling their home for less than they bought it for was a bitter pill to swallow.”
interact
In this podcast, the verb “to interact” means for two or more objects or people to act in a way that affects each other, or to have an effect on something and be affected by it at the same time: “The plant and animal life in this region is the complex result of thousands of plants and animals interacting over time.” When talking about people, “to interact” means to communicate and form relationships with other people: “Going to college presents a great opportunity to interact with people who have different socioeconomic and cultural backgrounds.” Or, “How have cell phones changed the ways in which people interact with each another?” Finally, the verb “to counteract” meant to act in opposition to or against something: “What can we do to counteract the rising crime rates?”
Culture Note
The Controlled Substance Act
In 1970, the United States “Congress” (law-making part of the government) and then-President Richard Nixon “enacted” (made into law) the Controlled Substance “Act” (law). Today, the Act “underlies” (forms the basis of) the country’s “drug policy” (how a country deals with medicines and illegal drugs). Specifically, it “regulates” (creates rules about and controls) how medicines and other drugs are “manufactured” (made for sale), “imported” (purchased and brought from other countries), “stored” (kept in a safe place until being used), “distributed” (given to people to use), and used.
The Act established five categories of “controlled substances” (things that must be closely regulated and controlled). These categories are based on how “addictive” (making people want to have more and more of something) the substances are, their “potential for” (likelihood of) “abuse” (misuse; use that causes harm or death), and what kind of medical treatments they are used for, among other things. Interestingly, the Controlled Substance Act does not directly deal with alcohol or “tobacco” (the substance smoked in cigarettes), even though those are the two most common drugs in the United States.
Two big parts of the U.S. government – The Food and Drug Administration (FDA) and the Drug Enforcement Administration (DEA) – are responsible for determining which drugs should be listed in each category. In addition, the DEA is responsible for “enforcing the law” (making sure people follow the law).
The Controlled Substances Act is important for international “treaties” (agreements between countries). For example, if the United Nations’ Commission on Narcotic Drugs changes how it classifies a particular drug, it might need to be moved from one U.S. category to another in order to keep the United States in “compliance” (following the rules) with its treaty “obligations” (what someone is required to do).
Comprehension Answers
1 - b
2 - c