
= 1 - Federalist 51
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

hey there welcome back to heimler's history. in this video we're continuing to look at the required foundational documents 必需的基础文献 for ap government and that means it's time to talk about federalist 51. so if you're ready to get the brain cows milk separation of power style （以权力分立的方式获取知识）, let's get to it. +

so right out of the gate 一开始 let's begin with the central and most famous passage in this essay written by james madison: "what is government itself but the greatest of all reflections on human nature. if men were angels, no government would be necessary. if angels were to govern men, neither external nor internal controls on government would be necessary." so here you get a real sense of madison's opinion of humankind 人类. like if people were angels we wouldn't even need a government -- everybody would just act right. but people are not angels. in madison's estimation 估计, human beings are a lot less like angels and more like selfish sentient turds （口语化表达，自私的有感知的家伙）dressed up in clothes. +

so in light of that 鉴于此, human beings need a government, and that government is there to protect the liberty of the people 人民的自由. and so supposing we agree on that, the next question is: how do we create a government that both has the power to protect liberty while at the same time does not have enough power to destroy liberty? madison says it this way: "in framing a government which is to be administered by men over men, the great difficulty lies in this: you must first enable the government to control the governed 被统治者, and in the next place oblige it to control itself." +

so what's the answer? how do you create a government that is both powerful and yet not too powerful? madison's answer: the separation of powers 权力分立 and checks and balances 制衡. "and this manner of restricting power 限制权力 cannot be imposed upon the branches of government externally 从外部施加于政府部门. rather, the defects must be supplied by so contriving 设计；谋划 the interior structure of the government as that its several constituent parts 组成部分 may, by their mutual relations, be the means of keeping each other in their proper places." so the different branches of government must be created in such a way that they balance and check each other's power 平衡和制衡彼此权力. +

so how would such a government look? well first madison says: "it is evident that each department should have a will of its own, and consequently should be so constituted 组成 that the members of each should have as little agency 作用；影响 as possible in the appointment of the members of the others." he says each branch needs as much power independent of the others as possible so they can't go around messing at each other's business 干涉彼此事务, and that that power needs to be basically equal between the three branches. +

but there is an objection 反对意见 here. if you look at the constitution, it's pretty clear that a disproportionate amount of power 不成比例的权力 is put into the hands of the legislative branch 立法部门 -- which is to say the congress 国会. and look, that's exactly as it should be since its congress which directly represents the voice of the people 人民的声音. so if we're wanting to keep things equal power wise 在权力方面保持平等, what are you going to do to this beefy legislature 强大的立法机构 over here? you're going to have to divide that power too: "the remedy for this inconveniency 不便之处 is to divide the legislature into different branches, and to render them by different modes of election 选举方式 and different principles of action 行动原则, as little connected with each other as the nature of their common functions 共同职能 and their common dependence on society will admit." +

so how do we keep the legislature from having too much power? you divide its power into two, which is exactly what the constitution did. congress is divided into a bicameral legislature 两院制立法机构 which is composed both of the house 众议院 and the senate 参议院, each of which holds a portion of the legislative power 立法权的一部分. if your heart is already beating fast at all that subdivision of power 权力细分, well then madison goes even further and keeps chopping: "in the compound republic of america, the power surrendered by the people 人民交出的权力 is first divided between two distinct governments 两个不同政府, and then the portion allotted to each 分配给每个政府的部分 subdivided among distinct and separate departments 再细分到不同的部门." +

so not only is the federal government's power divided among the branches, power is then further divided between the national government and the state governments -- which is a system of governance 治理体系 called federalism 联邦制. so with power divided in a portion to so many different actors 主体, liberty will necessarily be upheld 维护 even though the constitution is placing more power in the hands of the federal government than there was under the articles of confederation 邦联条例. +

but if you are not convinced that this division of power will keep the government's power in its proper bounds 适当范围, the constitution also provides a system of checks and balances through which each branch can check the power of the others. so for example, the executive branch 行政部门 can check the legislative branch 立法部门 by vetoing laws 否决法律. the legislative branch can check the executive branch by its powers of impeachment 弹劾 and removal from office 罢免职务. the judicial branch 司法部门 can check the other two branches by ruling on the constitutionality of laws and executive actions 判定法律和行政行为的合宪性. those are only a few examples, but the point is each branch has the power to restrain the power of the other branches 限制其他部门的权力, and that in madison's estimation provides what he calls a double security of protection for the liberty of the people 对人民自由的双重保障. +

and then madison spends the rest of his essay talking again -- like he did in federalist 10 -- about the dangers of factions 派别；派系. he returns to the same conclusion: the more factions there are, the less able any one of them will be to dominate the rest 主导其余派别. and so in the case of factions just like in the separation of powers in the government, a single principle prevails 适用: "ambition must be made to counteract ambition 野心必须相互制衡". in other words, we don't have angels governing us, nor are we ourselves angels. rather, people and governments always seek to preserve their own interests against the interests of everyone else 维护自身利益而不顾他人利益, and that means the best expedient 权宜之计 to liberty given our corrupted human nature 堕落的人性 is to set all our ambitions against each other 让所有野心相互对抗, and in that way tyranny cannot be entertained 无法形成暴政 because compromise and concession 妥协和让步 will be required to get anything done. +

okay that's what you need to know about federalist 51 for the ap government curriculum 课程. here's some more videos over here on the foundational documents, and if you need more help with the content of unit one you can watch these videos right here. click right here to grab my view packet 复习资料包 which will help you get an a in your class and a five on your exam in may. that's all i got. heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒历史课（Heimler's History）。在这个视频中，我们将继续研究美国大学预修课程政府学（AP Government）的必修基础文件，这意味着我们该谈谈《联邦党人文集》第51篇（Federalist 51）了。所以，如果你准备好以权力分立的方式汲取知识，那我们开始吧。 +

那么，一开始，让我们从詹姆斯·麦迪逊（James Madison）在这篇文章中最核心、最著名的段落讲起：“政府本身不就是对人性最深刻的反思吗？如果人是天使，就不需要政府了。如果天使来统治人，那么对政府无论是外部的还是内部的控制都没有必要了。” 所以在这里，你能真切地感受到麦迪逊对人类的看法。就像如果人们是天使，我们甚至都不需要政府——每个人都会行事正当。但人不是天使。在麦迪逊的估计中，人类远不像天使，更像是穿着衣服的自私的有感知的混蛋。 +

鉴于此，人类需要一个政府，而这个政府是为了保护人民的自由。那么，假设我们认同这一点，下一个问题是：我们如何创建一个既拥有保护自由的权力，同时又不会强大到破坏自由的政府呢？麦迪逊是这样说的：“在构建一个由人来管理人民的政府时，最大的困难在于：你必须首先让政府有能力控制被统治者，其次要迫使政府自我控制。” +

那么答案是什么呢？我们如何创建一个既强大又不会过于强大的政府呢？麦迪逊的答案是：权力分立和制衡。“而且，对权力的这种限制不能从外部强加于政府的各个分支。相反，必须通过设计政府的内部结构来弥补缺陷，使得政府的各个组成部分能够通过相互关系，将彼此置于合适的位置。” 所以，政府的不同分支必须以这样一种方式创建，即它们能够平衡和制衡彼此的权力。 +

那么这样的政府会是什么样子呢？嗯，首先麦迪逊说：“很明显，每个部门都应该有自己的意志，因此，其组成成员在任命其他部门成员时，应该尽可能少地参与其中。” 他说，每个分支都需要尽可能独立于其他分支拥有权力，这样它们就不能随意干涉彼此的事务，而且这三个分支的权力基本上应该是平等的。 +

但这里有一个反对意见。如果你看一下宪法，很明显，相当大一部分权力掌握在立法分支（也就是国会，Congress）手中。而且，你看，这正是应该的，因为国会直接代表了人民的声音。那么，如果我们想在权力方面保持平等，对于这个强大的立法机构，我们该怎么做呢？你必须也分割它的权力：“解决这个不便的办法是把立法机构分成不同的分支，并通过不同的选举方式和不同的行动原则，使它们之间的联系尽可能少，只要它们的共同职能的性质和它们对社会的共同依赖所允许的那样。” +

那么我们如何防止立法机构权力过大呢？你把它的权力一分为二，这正是宪法所做的。国会被分成一个两院制的立法机构，由众议院和参议院组成，它们各自拥有一部分立法权力。如果你已经对这种权力细分感到心跳加速，嗯，麦迪逊甚至更进一步，继续分割权力：“在美国这个复合共和制国家中，人民交出的权力首先在两个不同的政府之间划分，然后分配给每个政府的权力又在不同且独立的部门之间进行细分。” +

所以，不仅联邦政府的权力在各个分支之间进行了划分，而且权力还在国家政府和州政府之间进一步划分——这是一种被称为联邦制（federalism）的治理体系。所以，当权力被分配给这么多不同的行为主体时，即使宪法赋予联邦政府的权力比《邦联条例》（articles of confederation）下的权力更大，自由也必然会得到维护。 +

但如果你不相信这种权力划分能使政府权力保持在适当的范围内，宪法还提供了一种制衡体系，通过这个体系，每个分支都可以制衡其他分支的权力。例如，行政分支（executive branch）可以通过否决法律来制衡立法分支。立法分支可以通过弹劾和罢免的权力来制衡行政分支。司法分支（judicial branch）可以通过裁定法律和行政行为是否符合宪法来制衡另外两个分支。这些只是几个例子，但关键是每个分支都有权力约束其他分支的权力，而且在麦迪逊看来，这为人民的自由提供了他所说的双重安全保障。 +

然后，麦迪逊在文章的其余部分再次谈到了派系的危害，就像他在《联邦党人文集》第10篇（Federalist 10）中所做的那样。他得出了同样的结论：派系越多，任何一个派系就越不可能统治其他派系。所以，在派系的问题上，就像在政府的权力分立方面一样，有一个单一的原则占主导：“必须让野心与野心相互制衡。” 换句话说，我们没有天使来统治我们，我们自己也不是天使。相反，人们和政府总是试图维护自己的利益，而不顾其他人的利益，这意味着，鉴于我们堕落的人性，保障自由的最佳手段就是让我们的野心相互对抗，通过这种方式，暴政就无法存在，因为要做成任何事情都需要妥协和让步。 +

好的，这就是你需要了解的美国大学预修课程政府学中《联邦党人文集》第51篇的内容。这里还有一些关于基础文件的更多视频，如果你在第一单元的内容上需要更多帮助，你可以观看这里的这些视频。点击这里获取我的学习资料包，它将帮助你在课堂上取得A的成绩，并在五月份的考试中获得5分。我要说的就是这些。海姆勒（Heimler）退场。 +

'''

== pure

hey there welcome back to heimler's history. in this video we're continuing to look at the required foundational documents for ap government and that means it's time to talk about federalist 51. so if you're ready to get the brain cows milk separation of power style, let's get to it.

so right out of the gate let's begin with the central and most famous passage in this essay written by james madison: "what is government itself but the greatest of all reflections on human nature. if men were angels, no government would be necessary. if angels were to govern men, neither external nor internal controls on government would be necessary." so here you get a real sense of madison's opinion of humankind. like if people were angels we wouldn't even need a government -- everybody would just act right. but people are not angels. in madison's estimation, human beings are a lot less like angels and more like selfish sentient turds dressed up in clothes.

so in light of that, human beings need a government, and that government is there to protect the liberty of the people. and so supposing we agree on that, the next question is: how do we create a government that both has the power to protect liberty while at the same time does not have enough power to destroy liberty? madison says it this way: "in framing a government which is to be administered by men over men, the great difficulty lies in this: you must first enable the government to control the governed, and in the next place oblige it to control itself."

so what's the answer? how do you create a government that is both powerful and yet not too powerful? madison's answer: the separation of powers and checks and balances. "and this manner of restricting power cannot be imposed upon the branches of government externally. rather, the defects must be supplied by so contriving the interior structure of the government as that its several constituent parts may, by their mutual relations, be the means of keeping each other in their proper places." so the different branches of government must be created in such a way that they balance and check each other's power.

so how would such a government look? well first madison says: "it is evident that each department should have a will of its own, and consequently should be so constituted that the members of each should have as little agency as possible in the appointment of the members of the others." he says each branch needs as much power independent of the others as possible so they can't go around messing at each other's business, and that that power needs to be basically equal between the three branches.

but there is an objection here. if you look at the constitution, it's pretty clear that a disproportionate amount of power is put into the hands of the legislative branch -- which is to say the congress. and look, that's exactly as it should be since its congress which directly represents the voice of the people. so if we're wanting to keep things equal power wise, what are you going to do to this beefy legislature over here? you're going to have to divide that power too: "the remedy for this inconveniency is to divide the legislature into different branches, and to render them by different modes of election and different principles of action, as little connected with each other as the nature of their common functions and their common dependence on society will admit."

so how do we keep the legislature from having too much power? you divide its power into two, which is exactly what the constitution did. congress is divided into a bicameral legislature which is composed both of the house and the senate, each of which holds a portion of the legislative power. if your heart is already beating fast at all that subdivision of power, well then madison goes even further and keeps chopping: "in the compound republic of america, the power surrendered by the people is first divided between two distinct governments, and then the portion allotted to each subdivided among distinct and separate departments."

so not only is the federal government's power divided among the branches, power is then further divided between the national government and the state governments -- which is a system of governance called federalism. so with power divided in a portion to so many different actors, liberty will necessarily be upheld even though the constitution is placing more power in the hands of the federal government than there was under the articles of confederation.

but if you are not convinced that this division of power will keep the government's power in its proper bounds, the constitution also provides a system of checks and balances through which each branch can check the power of the others. so for example, the executive branch can check the legislative branch by vetoing laws. the legislative branch can check the executive branch by its powers of impeachment and removal from office. the judicial branch can check the other two branches by ruling on the constitutionality of laws and executive actions. those are only a few examples, but the point is each branch has the power to restrain the power of the other branches, and that in madison's estimation provides what he calls a double security of protection for the liberty of the people.

and then madison spends the rest of his essay talking again -- like he did in federalist 10 -- about the dangers of factions. he returns to the same conclusion: the more factions there are, the less able any one of them will be to dominate the rest. and so in the case of factions just like in the separation of powers in the government, a single principle prevails: "ambition must be made to counteract ambition." in other words, we don't have angels governing us, nor are we ourselves angels. rather, people and governments always seek to preserve their own interests against the interests of everyone else, and that means the best expedient to liberty given our corrupted human nature is to set all our ambitions against each other, and in that way tyranny cannot be entertained because compromise and concession will be required to get anything done.

okay that's what you need to know about federalist 51 for the ap government curriculum. here's some more videos over here on the foundational documents, and if you need more help with the content of unit one you can watch these videos right here. click right here to grab my view packet which will help you get an a in your class and a five on your exam in may. that's all i got. heimler out.

'''

