
= 1 - AP Government UNIT 1 REVIEW
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

hey there and welcome to heimler's History AP Government edition. in this video i'm going to review 复习；回顾 everything you need to know for AP Government unit 1. so in this video i'm going to cover 涵盖；包括 the foundations of american democracy 美国民主制度的基础, how we got our constitution, and how federalism 联邦制 works. so if you're ready to get them brain cows milked with them baby （形象表达，意为获取知识）, let's get to it. +

before we jump into 开始 this i should mention that this unit review is part of my AP Government review packet 复习资料包. not all the unit reviews are going to be here on youtube but they're all in that packet. and this packet has everything you need to get an A in your class and a five on your exam in may, including practice questions for every unit 每单元练习题, essential questions for the course 课程核心问题 and answers to check your work 答案以便核对作业, and full length practice exams 完整模拟考试 when you're ready for the exam. so you know if that's something you're into then get your clicky finger out and have a look （口语化表达，快去点击查看）. +

so let's begin with the foundations of american democracy and the first thing you absolutely need to know is the enlightenment 启蒙运动. so basically this was a european intellectual movement 欧洲思想运动 in the 18th century that had all kinds of influence on how the framers 制定者 of our constitution understood the principles of government 政府治理原则. so let's get nice and cozy with （熟悉；了解）a few of these enlightenment thinkers and their ideas. +

first was the idea of natural rights 自然权利 and this was basically the idea that people are born with certain rights that are given to them by their creator 造物主赋予. and that's important because that means those rights were not given to them by a monarch 君主 and therefore could not be taken away by a monarch. and related to this, enlightenment thinkers argued for a theoretical state of nature 自然状态理论 which comes before any kind of government, and in that state humans are free. and these ideas were exceedingly influential 极具影响力的 on the framers of the constitution. +

the second enlightenment idea you need to know -- and technically this is two ideas but you know they're very closely related so whatever -- it's popular sovereignty 人民主权 and the social contract 社会契约. the idea here is that by nature the power to govern is in the hands of the people -- that's the popular sovereignty part -- and that in order to protect their natural rights people willingly give some of that power away to a government -- and that's the social contract part. that means the state is the servant of the people and not the other way around. with respect to 关于 the social contract, the idea was that if the government violates the agreement it becomes a tyrannical turd （口语化，成为专制的坏蛋）, then the people's duty is to overthrow that government and switch it out for you know a non-turd government. +

the third enlightenment idea you need to know is republicanism 共和主义. so in a republican form of government people elect leaders to represent them and create laws in the public interest 公共利益. additionally 此外 to keep this government from becoming tyrannical 专制的, power ought to be separated between three branches: the executive 行政部门, the legislative 立法部门, and the judicial 司法部门. there are many other enlightenment ideas that influence the framers of the constitution but those are the major ones you need to know. and the sum of all of them taken together is basically this: that the best form of government is a limited government 有限政府 which by definition 从定义上讲 is a government that is prevented from tyranny 暴政 through a system of checks and balances 制衡机制 and the distribution of power 权力分配 among several acting members 多个机构成员. +

now hopefully as i went through some of those ideas they sounded kind of familiar. maybe not because you knew which thinkers were responsible for them or even if you knew the names, but because you have heard these ideas expressed in two of our foundational documents 基础文件: the declaration of independence 独立宣言 and the united states constitution 美国宪法. the declaration of independence provides the foundation for popular sovereignty, the social contract, and natural rights. and the enlightenment influence isn't that hard to spot: "we hold these truths to be self-evident 不证自明的, that all men are created equal, that they are endowed by their creator with certain unalienable rights 不可剥夺的权利, that among these are life, liberty, and the pursuit of happiness." and there you have a clear statement of natural rights -- although thomas jefferson the declaration's author substitute 替代 "a pursuit of happiness" for john locke's natural right of "life, liberty, and property" cause let's be honest big daddy government ain't got nearly enough hooch to go throwing around tracks of land to everybody like oprah -- you get some land, you get some land, you get some black... anyway, move on a little and you see the social contract in popular sovereignty: "that to secure these rights governments are instituted among men deriving their just powers from the consent of the governed 被统治者的同意". so you see the social contract like we establish governments to protect our natural rights, and then you see popular sovereignty that government gets its power from the people's consent. and then the constitution provides a blueprint 蓝图 for republicanism and the separation of powers which i'll talk more about later. +

for now let's shift 转换 and talk about the three main kinds of democracy and how they are present in our system today. you've got pluralist 多元主义的, elite 精英主义的, and participatory 参与式的. participatory democracy 参与式民主 emphasizes broad participation 广泛参与 in the political process by most if not all members of a society. pluralist democracy 多元主义民主 is a model in which groups of people associate with interest groups 利益集团 who then compete to influence public policy 公共政策. this model provides the people with a voice not really individually but in chunks （以群体形式）. elite democracy 精英主义民主 emphasizes more limited participation in policy making on the assumption 假设 that government is complicated and therefore the most educated people need to run it. now don't think of the us as embodying 体现 only one of these models. each of them exist depending on where you look. for example, participatory democracy shows up quite a bit more on local manifestations 地方表现形式 of government like town halls 市政厅会议 and small municipalities 小自治市. also on a larger scale, participatory democracy is present at the state level in initiatives 公民提案 and referenda 公民投票 which are ways that people can vote directly on legislation 立法 and keep their representatives accountable 问责. +

pluralist democracy on the other hand shows up in the many interest groups that exist in the us. and let me just give you a couple of examples that you've probably heard of: number one the naacp 全国有色人种协进会 which works for civil rights 民权, and number two the national rifle association 全国步枪协会 which works to promote second amendment rights 第二修正案权利. groups like these give people a voice and the bigger ones like i just mentioned wield 行使；运用 a disproportionate amount of power 不成比例的权力 over the political process. elite democracy was weakened by progressive era reforms 进步时代改革 like direct election of senators 参议员直接选举, but it still shows up in the electoral college 选举人团 where citizens get to vote but technically they're just voting for the electors 选举人 who really vote for the president. +

now we can also see the tension 矛盾；冲突 between these three models and three of our foundational documents: number one the constitution, number two federalist ten 联邦党人文集第十篇, and number three brutus one 布鲁图斯第一篇. in the constitution you can see elite democracy and the fact that elected representatives legislate 立法 on behalf of their people. then you can see pluralist democracy in the first amendment's freedom of assembly 集会自由 allowing political parties and interest groups to flourish 蓬勃发展. and you can see participatory democracy in things like the first amendment's freedom of speech and press 言论和新闻自由 that allow people to express their political opinions and also amendments 修正案 that expanded voting rights like the 15th and the 19th amendments prohibiting race and sex as barriers to voting. +

now this tension between the three forms of democracy is at the heart of the argument between federalist ten and brutus one. brutus championed 支持 a broad participatory model and feared the curtailment 限制 of personal liberties 个人自由 reflected in a larger republic like the united states. on the other hand, federalist 10 argued that with so many competing factions 派别 in a large republic, liberty would be upheld 维护 by their competition and that's an example of pluralist democracy. +

okay now since these are required documents let's go a little deeper into both of them. now both of these documents are part of a larger whole produced by competing groups. these groups were the federalists 联邦党人 and the anti-federalists 反联邦党人 and the main debate they were having was whether or not the state should ratify 批准 this new constitution. and by ratify it just means should the states accept this new constitution as law. and the big point of contention 争议点 between federalist 10 and brutus one is basically this: majority rule 多数统治 versus minority rights 少数群体权利. side note 旁注: in that day minority meant more like regional and economic minorities not ethnic categories 种族类别. so the debate was pretty simple: like in a republican form of government the majority will rule but the minority shouldn't just be tyrannized by the majority either. +

so in federalist 10, james madison took this on directly. he talked about the mischief of factions 派别的危害 in a republic and factions when being defined are basically groups of people who believe their interests are more important than any other interest. thank goodness those don't exist anymore. madison was specifically worried about factions that had interest actually opposed to the rights and interests of others. and so the problem is this: if the majority always prevailed 占上风 then the minority voice would never be represented. however if there were too many protections for the minority then the common good 公共利益 of the majority would be squashed 压制. so madison said there were basically two solutions here: either you take away the causes of factions or you try to manage their effects. taking away the causes of factions means you'd have to strip people of their liberty 剥夺人们的自由 so by madison's estimation 估计 the solution was worse than the problem. so therefore the only way to curb 遏制 the mischief of factions was to mitigate 减轻 their negative effects. he appealed to 诉诸；求助于 the size and diversity of the u.s population and said that with so many competing interests all of them would be set against each other and therefore none could prevail all the time. so a large republic would successfully deal with the threat of factions. additionally he argued that there was a double protection against the tyranny of factions provided by the separation of powers in the federal government and the sharing of power between the federal and state governments. so here you can see very plainly the arguments for a pluralist system 多元主义体系. +

now the anti-federalists who wrote the brutus essays were like son that argument is about as satisfying as a hair in a biscuit （习语，意为令人不满意）. you see they were exceedingly wary of 非常警惕 the new constitution because it invested the federal government with a lot more power than it had under the articles of confederation 在邦联条例下 under which most of the power belonged to the states. the anti-federalists were big participatory democracy folks and in brutus one the argument is about the dangers of a large centralized government 中央集权政府 and they were especially torqued up over （对……非常愤怒）the constitution's necessary and proper clause 必要且适当条款 and the supremacy clause 至上条款. we'll talk more about those later when we get into some supreme court cases but for now all you really need to know is that these two clauses gave more power to the federal government than the state government -- i mean potentially that's what they were arguing. brutus one essentially argued that a large centralized government could not adequately represent the views of the people because it would be largely separated from them. +

okay now there's a lot more to say about these documents but here you just need to understand how they represent the tension between the different models of democracy. so let's turn the corner 转换话题 now and talk about how we got our constitution and for that we need to start with the first constitution of the united states: the articles of confederation 邦联条例. now i already mentioned that under this document the federal government was very weak and the state governments were disproportionately strong 强得不成比例. it's not hard to understand why because the u.s still had kind of a monarchy hangover 君主制遗留影响 from being british subjects 英国臣民. and that's pretty much all the articles had going for it was that it avoided the tyranny of the centralized state. but oh baby were there some problems to be had with this form of government. +

first of all there was only one branch of the federal government namely congress. like there was no president, no federal court, and congress had no power to raise revenue 筹集收入 through taxes. like if they wanted money to fund their activities they just had to ask the states nicely and you could imagine how that went. additionally congress had no power to raise an army 组建军队 and even if they did -- see previous point about not having the money to pay an army. +

so you know there were lots of events that highlighted 凸显 the weaknesses of the articles but i'm only going to mention two. and first was regarding tax law enforcement 税收执法. at the end of the day congress just couldn't pay its bills and the states understood that this was a problem. so in 1782 a resolution 决议 was proposed by the stage which granted congress the power to collect a 5% tax on imported goods. 11 out of 13 states said yes but two said no. in under the articles you had to have all 13 agree in order to change the articles themselves and so congress remained weak and broke （没钱；衰弱）. +

but what displayed the weaknesses of the articles above all was a little event known as shay's rebellion 谢斯起义. you don't really need to know the details of this rebellion so it's enough to know that a bunch of revolutionary war veterans 美国独立战争退伍军人 were not getting paid by congress because again they had no money and yet congress still prosecuted them if they didn't pay their taxes. so because of this injustice 不公正 a bunch of them rose up 起义 in massachusetts and guess what there was no national army to come in and help. so even though the people of massachusetts did end up mustering a militia 召集民兵 to squash that rebellion 镇压起义, it made a lot of people realize that the federal government needed a lot more power in case these kinds of rebellions happened again. and judging by the sad state of the economy it wasn't that unlikely. +

so a constitutional convention 制宪会议 -- also known as the philadelphia convention -- was called in 1787. now the official goal of this convention was to modify 修订 the articles of confederation but they went ahead and ended up drafting 起草 an entirely new constitution. our boy george washington was presiding 主持. hamilton, madison, and the rest of what was called the grand committee 大委员会 were tasked with 负责 forging compromises 需要达成妥协 needed for a new governing document. as you can imagine this new governing document was the result of lots of heated and tense debate 激烈紧张的辩论. and so within the document itself you can see many of these compromises that were reached in order to pass it and you need to know four of them. +

first was the great compromise 大妥协. this was a compromise on how the people would be represented in the new congress. there were a couple of competing proposals 相互竞争的提议. first was the virginia plan 弗吉尼亚方案 which argued that congressional representatives should be apportioned 分配 by population. that's not hard to understand when you realize that virginia was a big state and under this plan big states would have more representatives and thus have more power. but the small states formally objected 正式反对 and said uh um and proposed the new jersey plan 新泽西方案. and this plan argued that each state should be represented equally with one vote per state. now if you're paying attention that would mean that small states have a disproportionate amount of power since small populations have the same power as large populations under this system. so what to do? well the compromise was the creation of a bicameral congress 两院制国会 which is to say there would be two houses. in the house of representatives 众议院 the people will be represented by population and in the senate 参议院 the states would be represented equally with two votes per state. +

another compromise was on how the president would be elected. various delegates 代表 argued that the people should elect the president, then others argued that the state should do it, and then still others that congress should do it. the compromise they came up with was the electoral college 选举人团. under this system each state is given a number of electors 选举人 that corresponds to 与……对应 the number of congressional representatives that they have and the state legislatures 州立法机构 have all the power to decide who those people are and it's those people who elect the president. +

all right now the last two compromises you need to know deal with slavery 奴隶制 which as you can imagine was the subject of some very intense debate 激烈辩论. first was the question of how enslaved people 被奴役的人 will be counted in terms of representation in congress. not surprisingly northern states thought enslaved people shouldn't be counted at all on account of 因为 the southerners were always justifying the institution 制度 by claiming their enslaved laborers 被奴役的劳工 were less than human. and if that's the case why would you count them? but southerners countered 反驳 and said uh we did not just fall off the turnip truck son that dog don't hunt （习语，意为那套说辞没用）. they wanted all the enslaved laborers to be counted and thus increased southern power in congress. and the compromise that solved this tension was known as the three-fifths compromise 五分之三妥协 and basically it just meant that three-fifths of the enslaved population would count towards representation 计入代表人数. +

and then there was the compromise on the importation of slaves 奴隶进口. this was a big one for southerners since their entire economy rose and fell on slavery 经济依赖奴隶制. essentially the compromise was that congress couldn't touch the slave trade 奴隶贸易 for 20 years after the constitution was ratified and after that the slave trade would be abolished 废除. +

now because these debates at the convention were so intense, the framers of the constitution included a process by which the document could be amended 修订 and you can find it in article 5. basically it's a two-stage process to amend the constitution: there's proposal 提议 and then there's ratification 批准. so an amendment 修正案 can be proposed either by congress or by the states at a special convention and then a two-thirds vote 三分之二多数票 is needed for the proposal to become official. then the amendment is sent to the states for ratification and for that to happen three quarters of state legislatures 州立法机构 or state ratifying conventions 州批准会议 need to agree and if they do that amendment becomes law. +

now ultimately despite all the conflict that i just mentioned the constitution was circulated to 分发到 the states and was ratified in june of 1788 and at that point became the governing document  governing document of the united states. at this point let us pause and high five a bald eagle. america. even so, the constitution has proven to be a very durable document 持久有效的文件 throughout the history of america and one of the main reasons is because it did such a good job of separating power and providing checks and balances to make sure that no branch becomes too powerful. +

let me just give you some examples. the legislative branch 立法部门 -- which is to say congress -- is basically responsible for proposing and making laws. no other branch can make laws and there are plenty of access points 途径 for people to speak into those laws. and just so you know those people are called stakeholders 利益相关者. people can write letters or emails to the representatives or if they're wanting to punish themselves they can watch c-span 美国公共事务有线电视频道 which are congressional proceedings 国会会议进程. i mean yes it's super boring but it is kind of an amazing thing that we can watch what our representatives are doing like this does not happen in more repressive countries 专制国家. and an example of the power of congress to check the other branches is the senate's power of advice and consent 参议院的建议和同意权. this means that any appointments that the president makes to the presidential cabinet 总统内阁 or the supreme court or any other federal office has to be approved by the senate. +

the executive branch 行政部门 is responsible for executing and enforcing the laws 执行和实施法律 and no other branch has that power. and here too stakeholders have multiple access points. i mean you can't just like call up the president but the agencies run by the executive branch can absolutely be accessed by average citizens 普通公民. if you're so inclined 有意愿的话 you can file a complaint 投诉 at one of these agencies or you can report crimes being committed 举报犯罪行为. and a good example of the executive branch's checking power 制衡权力 is the veto 否决权. if congress passes a law the president doesn't like the president can veto it and it becomes null and void 无效的 unless of course congress overrides that veto with a two-thirds vote 推翻否决. so you know much checking. +

the judicial branch 司法部门 is responsible for determining the constitutionality of laws 判定法律的合宪性 and no other branch has that power. and stakeholders can use the court system to challenge unjust and unconstitutional laws 挑战不公正和违宪的法律 as well as appeal wrongful convictions 上诉不当定罪. an example of the checking power of the judicial branch is the power of judicial review 司法审查权. now this power isn't technically in the constitution but it was developed out of the nature of the court 源于法院的性质. it basically means that it's the court's prerogative 特权 to judge the laws passed by congress and signed by the president on the merits of their constitutionality 依据合宪性对法律进行评判. and if the court finds a law to be unconstitutional you burn （此处意为法律失效）. +

okay so that's how we got our constitution. now let's turn the corner 转换话题 and talk about federalism. now look i know this video has already been long but you have to pay attention here because students always get confused by this term. when you hear federalism you think i'm about to say something about the federal government's power but that is not what federalism is. like crack those brain folds open （形象表达，意为认真理解）and get this down: federalism is the sharing of power between national governments and state governments 联邦政府与州政府之间的权力分享. that's all it is. it's just the sharing of power. +

now in order to understand this let's talk about the exclusive powers 专有权力, reserve powers 保留权力, and concurrent powers 共同权力. exclusive powers are those powers specifically delegated by the constitution to the federal government 宪法明确授予联邦政府的权力. for example only congress can make treaties with other sovereign nations 主权国家. alabama can't just say you know i think we're going to get into a trade agreement with bolivia you know just for funsies （口语化，开玩笑地）. no that is an exclusive power of the federal government. +

reserved powers are those powers kept by the states and this is explained in the 10th amendment. it says this: "the powers not delegated to the united states by the constitution, nor prohibited by it to the states, are reserved to the states" 宪法未授予合众国、也未禁止各州行使的权力，保留给各州. so traditionally these powers have included things like police powers 警察权力, hospitals, education, and a lot more. +

and then you have concurrent powers which are powers that are shared by both the federal and state governments 联邦和州政府共同拥有的权力. for example if you've ever had a job you know that both the federal and state governments pull taxes from your income 从收入中征税. +

now that's the basic idea of federalism. the federal government doesn't have all the power nor do the states. they share power. but over the course of the last century or so the way that federalism has been most prominently manifested 最显著体现 is through something called fiscal federalism 财政联邦制. and when you're talking about fiscal matters 财政事务 you're talking about the boom boom （此处指代资金）. so power has largely been shared through money. and what does that mean? well congress is able to establish national standards 国家标准 and then direct funds 拨款 to states that comply with those standards and then withhold funding 扣留资金 from states that do not. and that happens in several ways. +

first is through grants 拨款 and there are two kinds. first are categorical grants 专项拨款 and these are grants given to the states as long as the states comply with specific federal standards 符合特定的联邦标准. in other words big daddy government says to the states i got a bag full of money for you and you got to spend it the way i want you to （形象表达，联邦政府要求州按其规定使用资金）. these kind of grants were used as incentives 激励手段 to integrate schools and lyndon johnson's administration 林登·约翰逊政府时期. they were also used to raise the drinking age to 21. in that case the federal government offered categorical grants to states for the upkeep of their interstate highways 州际公路维护 and if they raised their drinking age they got the money if not no soup for you （口语化，否则得不到资金）. categorical grants are given to very specific needs of the states and congress decides how that money is going to be spent. +

but block grants 整笔拨款 on the other hand are a little different. they still come from congress to the states but there are far less strings attached 附加条件少得多. these grants are given to states for a relatively broad purpose 较宽泛的目的 and the states can spend that money as they see fit 自行决定如何使用. so in this case congress might give a state money for the prevention of crime 预防犯罪 and the state decides exactly how to spend that money in order to meet that requirement. maybe they hire more police officers maybe they invest in rehabilitation programs for inmates 囚犯康复项目. they can do whatever they want with it. the state has discretion 自由裁量权 in this kind of grant but there are still limits. for example they can't just spend money from a crime prevention grant on highway improvement 不能将预防犯罪拨款用于公路建设. +

another way fiscal federalism plays out 体现 is through mandates 命令. so mandates require states to follow federal directives 联邦指令 but often compliance with these directives is beyond a state's budget capacity 超出州的预算能力. so the federal government sets the rules and then provides money to help those states comply. so for example when congress passed the clean air act of 1970 1970年清洁空气法案 it mandated that all states work to reduce smog 烟雾, acid rain 酸雨, and the release of other pollutants 污染物排放. and these were national requirements and so the federal government provided funds to states to help them meet those mandates 满足这些要求. +

now there is such a thing as an unfunded mandate 无资金支持的命令 and that's exactly what it sounds like: the federal government issues the mandate and then provides no funding whatsoever to help the states achieve it 不提供任何资金帮助州执行. however these were largely struck down 废除 during the devolution revolution 权力下放革命 of the 1980s under president reagan. he championed 支持 the process of devolution 权力下放 or return of power to the states away from the federal government. later president clinton signed the unfunded mandates reform act 无资金支持命令改革法案 which denied congress the power to issue unfunded mandates. so if you wanted to put this on a spectrum 范围 -- and i know that you do -- states really like revenue sharing 收入分享 but really hate unfunded mandates and categorical and block grants are somewhere in the middle of their love hate spectrum 爱恨程度之间. +

okay so those are the basics of federalism and its chief manifestation fiscal federalism. now i probably don't need to tell you that there has always been an argument over the sharing of power between state and federal governments and the balance of that power has changed over time depending on the needs and situation of the nation. let me give you two examples. +

first regarding government surveillance 政府监控. after the terrorist attacks on september 11, 2001 congress responded with the usa patriot act 美国爱国者法案 in order to find and stop future terrorists. this act increased the ability of the federal agencies to gather intelligence 收集情报 by phone tapping 电话窃听 and monitoring emails. now that law passed with strong bipartisan support 两党大力支持 but it wasn't long before an outcry 强烈抗议 rose up among american citizens. they argued that such federal power was a violation of their fourth amendment rights 第四修正案权利 to be secure against unreasonable searches and seizures 免受不合理搜查和扣押. +

another example is in the domain of education 教育领域. historically education has been the prerogative 特权 of the states but in 2001 congress passed the no child left behind act 不让一个孩子掉队法案 and with this the federal government got all up in education 深度介入教育. basically the law said that in order to receive federal funding on which schools depend 学校依赖的联邦资金, schools had to meet certain criteria 标准 which were largely found to be unattainable 无法实现的 by a vast majority of schools. and if the schools did not meet those criteria they were slapped with sanctions 受到制裁. and this led to an outcry from the states that this law represented federal overreach 联邦权力过度扩张 into the dominion of state power 州权力范围. so yeah this argument is still going on today and will probably always be going on. +

at the very heart of that balancing act 权力平衡 between federal and state power are a few constitutional provisions 宪法条款 and two required supreme court cases 最高法院判例. first let's look at the constitution. the balance of power between the states and federal government is deeply affected by four parts of the constitution. first you need to know the 10th amendment and i already mentioned that just a minute ago. second the 14th amendment 第十四修正案 and we'll have a lot more to say about this one in unit 3 but for now all you really need to know is that this amendment applies the bill of rights 权利法案 -- or the first 10 amendments of the constitution -- to the states. remember the bill of rights originally protected citizens from the federal government but the 14th amendment empowers the federal government to make sure that citizens liberties are also upheld by the state 确保公民自由也得到州的维护. +

third you have the commerce clause 商业条款 which allows congress to regulate commerce among the states 监管州际贸易 and this one has been widely used by congress to bring states into submission to its will 使各州服从其意愿. and then fourth you have the necessary and proper clause 必要且适当条款 -- also known as the elastic clause 弹性条款. do you remember lo those many minutes ago when we talked about the exclusive powers of congress? well those are explicitly outlined 明确列出 in article 1 section 8 of the constitution but it ends by saying that congress can make any other law that is necessary and proper to the upholding of those powers that are explicitly listed 制定任何为维护明确列出权力所必要且适当的其他法律. this is how alexander hamilton justified the need for a national bank 为建立国家银行提供理由. article 1 section 8 says precisely nothing about congress having the power to establish a bank. however it does say that congress has the power to regulate interstate commerce and raise taxes and hamilton argued that it was therefore necessary and proper that the federal government have a bank to store all those funds 联邦政府有必要且适当地设立银行来存储资金. +

okay those are the constitutional provisions at the heart of federalism. and now let's have a look at two supreme court cases that have weighed in on 对……进行裁决 the balance of power. first is mcculloch versus maryland in 1819 麦卡洛克诉马里兰州案. this case is an example of the balance of power tipping in favor of federal power 权力天平向联邦政府倾斜. essentially the court ruled that the necessary and proper clause implied certain powers given to the federal government even if they were not explicitly mentioned in the constitution 即使宪法未明确提及，必要且适当条款也暗示联邦政府拥有某些权力. additionally the court argued that the supremacy clause in the constitution meant that where the two conflicted, federal law trumps state law 联邦法律优先于州法律. +

the second case you need to know is the united states versus lopez in 1995 美国诉洛佩兹案. now this case is an example of the balance of power tipping towards the states 权力天平向州政府倾斜. basically congress had used the commerce clause to ban guns on school property 禁止在校园携带枪支 and the court decided that carrying guns to school is in no way related to interstate commerce 与州际贸易毫无关联 and thus congress had overstepped its bounds 越权 into state authority 州政府权力范围 thus providing a win for state power. +

okay now let's get some examples of federalism in action 联邦制的实际例子 and i'm just going to give you two: environmental regulations 环境法规 and the legalization of marijuana 大麻合法化. and remember we're looking at both of these through the lens of federalism -- how state and federal governments share power. +

okay so environmental regulation. in 2015 president obama led the u.s into the paris agreement 巴黎协定 which was a worldwide effort to address climate change 应对气候变化. and there was a lot going on there but all you really need to know is that certain carbon emission regulations 碳排放法规 were imposed on states as a result of this agreement. now once president trump was in office he removed the u.s from the agreement but some states like california kept the standards 标准. so you know now if you're a factory owner in california and you want to emit a butt load of greenhouse gases 排放大量温室气体 even though federal limitations would permit it, state limitations will not 州的限制不允许. +

the second example of federalism in action is the legalization of marijuana. now this substance has been illegal by federal law 联邦法律 since the 1930s but in the 80s and 90s a lot of new research was emerging on the potential medical benefits of marijuana 大麻的潜在医疗益处. and so in 1996 california legalized medical marijuana 医用大麻合法化 by means of a statewide vote 全州投票. is that participatory democracy? i smell yes it is （口语化，意为明显是参与式民主）. anyway eventually several states followed suit 效仿. and by 2012 colorado legalized recreational use of marijuana 休闲大麻合法化. but wait a minute it's illegal federally but it's legal in the state. how does that work? well that's federalism baby. the obama administration which is generally favorable to the legalization stated that it would not use federal resources to enforce that federal law in colorado 不会动用联邦资源在科罗拉多执行该联邦法律. so was it still illegal federally? yeah. is the federal government going to do anything about it? no. and in that way states are like laboratories for democracy 民主实验室. we can see what works on a small scale 小规模 and what doesn't work and then potentially implement what works on a national scale 全国范围实施可行的做法. +

well okay that's what you need to know about unit 1 of ap government. if you want help getting an A in your class and a 5 on your exam may then click right here and grab that ultimate review packet 终极复习资料包 and watch all your dreams come true （夸张表达，实现梦想）. if this video helped you you want to send me the signal to keep making them then click that subscribe button and i shall oblige 照办. heimler out. +

'''

== 中文释义

嘿，欢迎来到海姆勒历史课的美国政府学版本。在这个视频中，我将回顾美国大学预修课程政府学第一单元你需要知道的所有内容。所以在这个视频里，我会涵盖美国民主的基础、我们是如何得到宪法的，以及联邦制是如何运作的。所以，宝贝，如果你准备好汲取知识了，那我们开始吧。 +

在我们深入这个内容之前，我得提一下，这个单元复习是我美国大学预修课程政府学复习资料包的一部分。不是所有的单元复习内容都会放在YouTube上，但它们都在那个资料包里。这个资料包包含了你在课堂上拿到A并且在五月份的考试中拿到5分所需要的所有东西，包括每个单元的练习题、课程的关键问题以及检查你作业的答案，还有当你准备考试时的全套模拟考试。所以，你知道的，如果这是你感兴趣的东西，那就伸出你的手指点击，看看吧。 +

那我们从美国民主的基础开始讲起，你绝对需要知道的第一件事是启蒙运动。基本上，这是18世纪欧洲的一场思想运动，它对我们宪法的制定者理解政府原则产生了各种各样的影响。所以，让我们好好了解一下这些启蒙思想家以及他们的思想。 +

第一个是自然权利的概念，基本上就是说人们生来就拥有某些由他们的造物主赋予的权利。这很重要，因为这意味着这些权利不是由君主赋予的，因此也不能被君主剥夺。与此相关的是，启蒙思想家主张一种先于任何政府的自然状态理论，在那种状态下，人类是自由的。这些思想对宪法的制定者产生了极其深远的影响。 +

你需要知道的第二个启蒙思想——严格来说这是两个思想，但它们紧密相关，所以无所谓啦——就是人民主权和社会契约。这里的观点是，从本质上讲，治理的权力掌握在人民手中——这就是人民主权的部分——并且为了保护他们的自然权利，人们心甘情愿地把一部分权力交给政府——这就是社会契约的部分。这意味着国家是人民的公仆，而不是反过来。关于社会契约，其观点是，如果政府违反了协议，变成了一个暴虐的存在，那么人民有责任推翻那个政府，然后换成一个不是暴虐的政府。 +

你需要知道的第三个启蒙思想是共和主义。在共和政体下，人们选举领导人来代表他们，并为了公共利益制定法律。此外，为了防止这个政府变得暴虐，权力应该在三个分支之间进行划分：行政分支、立法分支和司法分支。还有许多其他的启蒙思想影响了宪法的制定者，但这些是你需要知道的主要思想。所有这些思想加起来基本上就是：最好的政府形式是有限政府，根据定义，有限政府是通过制衡系统以及在几个运作成员之间分配权力来防止暴政的政府。 +

现在，希望当我阐述这些思想的时候，你觉得有点熟悉。也许不是因为你知道是哪些思想家提出了这些思想，甚至不是因为你知道这些思想的名字，而是因为你在我们的两份基础性文件中听到过这些思想的表达：《独立宣言》和《美国宪法》。《独立宣言》为人民主权、社会契约和自然权利提供了基础。并且启蒙思想的影响并不难发现：“我们认为这些真理是不言而喻的：人人生而平等，他们被他们的造物主赋予了某些不可剥夺的权利，其中包括生命权、自由权和追求幸福的权利。”在那里，你看到了自然权利的明确表述——尽管《独立宣言》的作者托马斯·杰斐逊用“追求幸福”取代了约翰·洛克的“生命、自由和财产”的自然权利，因为说实话，政府可没有足够的东西像奥普拉那样给每个人分配土地——你得到一些土地，你得到一些土地，你得到一些……不管怎样，继续看下去，你会在人民主权中看到社会契约：“为了保障这些权利，人们在他们之间建立政府，政府的正当权力来自被统治者的同意。”所以你看到了社会契约，就像我们建立政府来保护我们的自然权利，然后你看到了人民主权，即政府的权力来自人民的同意。然后《宪法》为共和主义和权力分立提供了蓝图，关于这一点我稍后会详细谈论。 +

现在，让我们转换一下话题，谈谈三种主要的民主形式，以及它们在我们的制度中是如何体现的。有多元主义民主、精英民主和参与式民主。参与式民主强调社会中大多数（如果不是全部）成员广泛参与政治进程。多元主义民主是一种模式，在这种模式下，人们组成的团体与利益集团联合起来，然后竞争以影响公共政策。这种模式为人们提供了一个发声的机会，但不是以个人的形式，而是以团体的形式。精英民主强调在政策制定中更有限的参与，其假设是政府很复杂，因此需要最有知识的人来管理它。现在，不要认为美国只体现了其中一种模式。根据不同的情况，这三种模式都存在。例如，参与式民主在地方政府的表现形式中出现得更多，比如市政厅会议和小型市政当局。而且在更大的范围内，参与式民主在州一级的倡议和公投中也有体现，通过这些方式，人们可以直接对立法进行投票，并让他们的代表承担责任。 +

另一方面，多元主义民主体现在美国存在的许多利益集团中。让我给你举几个你可能听说过的例子：第一是全国有色人种协进会（NAACP），它致力于争取公民权利；第二是全国步枪协会（National Rifle Association），它致力于促进第二修正案所赋予的权利。像这样的团体为人们提供了一个发声的机会，而且像我刚才提到的那些较大的团体，在政治进程中拥有不成比例的权力。精英民主因进步时代的改革而被削弱，比如参议员的直接选举，但它仍然体现在选举团制度中，在选举团制度下，公民进行投票，但从技术上讲，他们只是投票给那些真正为总统投票的选举人。 +

现在，我们也可以看到这三种模式与我们的三份基础性文件之间的紧张关系：第一是《宪法》，第二是《联邦党人文集》第十篇（Federalist ten），第三是《布鲁图斯》第一篇（Brutus one）。在《宪法》中，你可以看到精英民主，以及当选代表代表人民立法的事实。然后你可以在《第一修正案》中看到多元主义民主，《第一修正案》中的集会自由允许政党和利益集团蓬勃发展。你还可以在《第一修正案》中的言论和新闻自由等方面看到参与式民主，这些自由允许人们表达他们的政治观点，并且像第十五和第十九修正案这样扩大投票权的修正案，禁止将种族和性别作为投票的障碍。 +

现在，这三种民主形式之间的这种紧张关系是《联邦党人文集》第十篇和《布鲁图斯》第一篇争论的核心。《布鲁图斯》第一篇拥护广泛的参与式民主模式，并且担心像美国这样的大共和国会限制个人自由。另一方面，《联邦党人文集》第十篇认为，在一个大共和国中有如此多相互竞争的派别，自由会通过它们之间的竞争得到维护，这是多元主义民主的一个例子。 +

好的，既然这些是必读文件，那我们就更深入地了解一下它们。现在，这两份文件都是由相互竞争的团体所产生的更大整体的一部分。这些团体是联邦党人和反联邦党人，他们的主要争论点是各州是否应该批准这部新宪法。而“批准”的意思就是，各州是否应该接受这部新宪法作为法律。《联邦党人文集》第十篇和《布鲁图斯》第一篇之间的主要争议点基本上是：多数统治与少数权利。顺便说一下：在那个时候，“少数”更多地指的是地区和经济上的少数群体，而不是种族类别。所以这场争论很简单：就像在共和政体下，多数人将统治，但少数人也不应该仅仅被多数人暴虐地对待。 +

所以在《联邦党人文集》第十篇中，詹姆斯·麦迪逊（James Madison）直接谈到了这个问题。他谈到了在一个共和国中派系的危害，而派系被定义为基本上是那些认为自己的利益比其他任何利益都更重要的人群。谢天谢地，现在不存在这样的情况了。麦迪逊特别担心那些其利益实际上与他人的权利和利益相悖的派系。所以问题是这样的：如果多数人总是占上风，那么少数人的声音就永远不会被代表。然而，如果对少数人有太多的保护，那么多数人的共同利益就会被压制。所以麦迪逊说基本上有两个解决方案：要么消除派系的根源，要么努力控制它们的影响。消除派系的根源意味着你必须剥夺人们的自由，所以在麦迪逊看来，这个解决方案比问题本身更糟糕。所以，遏制派系危害的唯一方法是减轻它们的负面影响。他诉诸美国人口的规模和多样性，并说由于存在如此多相互竞争的利益，它们都会相互制衡，因此没有一个利益集团能一直占据上风。所以一个大共和国将成功地应对派系的威胁。此外，他认为，联邦政府的权力分立以及联邦政府和州政府之间的权力共享，为防止派系的暴政提供了双重保护。所以在这里，你可以清楚地看到支持多元主义体系的论点。 +

现在，撰写《布鲁图斯》系列文章的反联邦党人认为，这个论点就像饼干里的一根头发一样不令人满意。你看，他们对这部新宪法非常警惕，因为它赋予了联邦政府比《邦联条例》下多得多的权力，在《邦联条例》下，大部分权力属于各州。反联邦党人是大力支持参与式民主的人，在《布鲁图斯》第一篇中，争论的是一个大型中央政府的危险，他们对宪法中的“必要和适当条款”以及“最高权力条款”尤其感到不满。当我们讲到一些最高法院的案例时，我们会更多地谈论这些条款，但现在你真正需要知道的是，这两个条款赋予了联邦政府比州政府更多的权力——我的意思是，这就是他们争论的潜在点。《布鲁图斯》第一篇基本上认为，一个大型中央政府不能充分代表人民的观点，因为它在很大程度上与人民相分离。 +

好的，关于这些文件还有很多可以说的，但在这里你只需要理解它们是如何体现不同民主模式之间的紧张关系的。所以，现在让我们转换一下话题，谈谈我们是如何得到宪法的，为此我们需要从美国的第一部宪法《邦联条例》开始讲起。现在我已经提到过，根据这份文件，联邦政府非常软弱，而州政府则过于强大。不难理解为什么会这样，因为美国仍然有一些作为英国臣民时的君主制残余影响。《邦联条例》基本上只有一个优点，那就是它避免了中央集权国家的暴政。但是，哎呀，这种政府形式存在一些问题。 +

首先，联邦政府只有一个分支，即国会。比如，没有总统，没有联邦法院，而且国会没有权力通过税收来筹集资金。就像如果他们想要钱来资助他们的活动，他们只能友好地向各州要，你可以想象那会怎么样。此外，国会没有权力组建军队，即使他们想——看看前面提到的没有钱支付军队费用这一点就知道了。 +

所以，你知道有很多事件突出了《邦联条例》的弱点，但我只提两件事。第一件事是关于税法的执行。归根结底，国会无法支付它的账单，各州也明白这是个问题。所以在1782年，一个州提出了一项决议，授予国会对进口商品征收5%税收的权力。13个州中有11个州表示同意，但有两个州表示反对。根据《邦联条例》，要修改条例必须得到13个州的一致同意，所以国会仍然软弱且资金短缺。 +

但是，最能体现《邦联条例》弱点的是一个被称为谢斯起义（Shay's Rebellion）的小事件。你不需要真正了解这次起义的细节，你只需要知道一群美国独立战争的退伍军人没有得到国会的报酬，因为同样的原因，国会没有钱，然而如果他们不纳税，国会仍然会起诉他们。所以由于这种不公正，一群人在马萨诸塞州起义了，猜猜怎么着，没有国家军队来帮忙。所以，即使马萨诸塞州的人民最终召集了一支民兵来镇压这次起义，但这让很多人意识到，联邦政府需要更多的权力，以防类似的起义再次发生。而且从经济的糟糕状况来看，这种情况很有可能再次发生。 +

所以在1787年，召开了一次制宪会议——也被称为费城会议（Philadelphia convention）。这次会议的官方目标是修改《邦联条例》，但他们最终起草了一部全新的宪法。我们的乔治·华盛顿（George Washington）主持了这次会议。亚历山大·汉密尔顿（Hamilton）、詹姆斯·麦迪逊（Madison）以及所谓的大委员会的其他成员，肩负着为新的治理文件达成必要妥协的任务。正如你可以想象的那样，这部新的治理文件是许多激烈和紧张辩论的结果。所以在这份文件本身中，你可以看到为了通过它而达成的许多妥协，你需要知道其中的四个。 +

第一个是大妥协。这是关于人民在新国会中如何被代表的妥协。有几个相互竞争的提案。第一个是《弗吉尼亚方案》（Virginia Plan），它主张国会代表应该按人口分配。当你意识到弗吉尼亚州是一个大州，并且根据这个方案大州将有更多的代表，从而拥有更多的权力时，这并不难理解。但是小州正式提出了反对意见，然后提出了《新泽西方案》（New Jersey Plan）。这个方案主张每个州应该平等地被代表，每个州有一票。现在，如果你注意的话，这意味着小州拥有不成比例的权力，因为在这个系统下，人口少的州和人口多的州拥有相同的权力。那么该怎么办呢？嗯，妥协的结果是创建了一个两院制的国会，也就是说会有两个议院。在众议院，人民将按人口比例有代表；在参议院，各州将平等地有代表，每个州有两票。 +

另一个妥协是关于总统如何选举。不同的代表们争论说，人民应该选举总统，然后其他人争论说，各州应该选举总统，还有一些人说国会应该选举总统。他们达成的妥协是选举团制度。在这个制度下，每个州被赋予一定数量的选举人，选举人的数量与该州的国会代表数量相对应，并且州立法机构拥有决定这些选举人的全部权力，而正是这些选举人选举总统。 +

好的，现在你需要知道的最后两个妥协与奴隶制有关，你可以想象，这是一个非常激烈辩论的话题。第一个问题是，在国会代表权方面，奴隶将如何计算。毫不奇怪，北方各州认为奴隶根本不应该被计算在内，因为南方人总是声称他们的奴隶劳工不如人类，以此来为奴隶制制度辩护。如果是这样的话，为什么要计算他们呢？但是南方人反驳说，哎呀，我们可没那么好骗，儿子。他们希望所有的奴隶劳工都被计算在内，这样就能增加南方在国会的权力。解决这种紧张关系的妥协被称为“五分之三妥协”，基本上就是说，五分之三的奴隶人口将被计算在代表权内。 +

然后是关于奴隶进口的妥协。这对南方人来说是一个重要的问题，因为他们的整个经济兴衰都依赖于奴隶制。本质上，妥协的内容是，在宪法批准后的20年内，国会不能干涉奴隶贸易，20年后，奴隶贸易将被废除。 +

现在，由于制宪会议上的这些辩论非常激烈，宪法的制定者们纳入了一个修改宪法的程序，你可以在《宪法》第五条中找到它。基本上，修改宪法有两个阶段的过程：提出修正案和批准修正案。修正案可以由国会或各州在特别会议上提出，然后需要三分之二的票数才能使提案正式化。然后修正案被送到各州进行批准，要使修正案生效，需要四分之三的州立法机构或州批准会议同意，如果是这样，修正案就成为法律。 +

最终，尽管有我刚才提到的所有冲突，宪法还是被分发给各州，并在1788年6月获得批准，从那时起成为美国的治理文件。在这一点上，让我们停下来，和一只秃头鹰击个掌。美国。即便如此，在美国历史上，宪法被证明是一份非常持久的文件，其中一个主要原因是它在权力分立方面做得非常好，并提供了制衡机制，以确保没有一个分支变得过于强大。 +

让我给你举一些例子。立法分支——也就是国会——基本上负责提出和制定法律。没有其他分支可以制定法律，并且有很多途径让人们对这些法律发表意见。而且你要知道，这些人被称为利益相关者。人们可以给代表写信或发电子邮件，或者如果他们想惩罚自己，他们可以观看C-SPAN（美国公共事务电视网），那是国会的议事程序。我的意思是，是的，这超级无聊，但我们能够观看我们的代表在做什么，这是一件很了不起的事情，在更专制的国家可不会发生这样的事情。国会制衡其他分支的权力的一个例子是参议院的建议和同意权。这意味着总统对总统内阁、最高法院或任何其他联邦职位的任命都必须得到参议院的批准。 +

行政分支负责执行和实施法律，没有其他分支拥有这项权力。而且在这里，利益相关者也有多种途径参与。我的意思是，你不能直接给总统打电话，但行政分支管理的机构，普通公民绝对可以联系。如果你愿意，你可以向这些机构之一提出投诉，或者你可以举报犯罪行为。行政分支的制衡权力的一个很好的例子是否决权。如果国会通过了一项总统不喜欢的法律，总统可以否决它，除非国会以三分之二的票数推翻否决，否则该法律就会无效。所以你知道，有很多制衡机制。 +

司法分支负责确定法律的合宪性，没有其他分支拥有这项权力。利益相关者可以利用法院系统来挑战不公正和违宪的法律，以及对错误定罪提出上诉。司法分支的制衡权力的一个例子是司法审查权。从技术上讲，这项权力并不在宪法中，但它是从法院的性质中发展出来的。基本上，这意味着法院有权根据法律的合宪性来评判国会通过并由总统签署的法律。如果法院发现一项法律违宪，那就完了。 +

好的，这就是我们如何得到宪法的过程。现在让我们转换一下话题，谈谈联邦制。现在，我知道这个视频已经很长了，但你必须注意这里，因为学生们总是对这个术语感到困惑。当你听到“联邦制”时，你可能认为我要讲的是联邦政府的权力，但这不是联邦制的含义。打开你的思维，记住这一点：联邦制是国家政府和州政府之间的权力分享。就是这么简单，仅仅是权力分享而已。 +

现在，为了理解这一点，让我们谈谈专属权力、保留权力和共同权力。专属权力是宪法明确授予联邦政府的权力。例如，只有国会可以与其他主权国家签订条约。阿拉巴马州不能说，你知道吗，我觉得我们要和玻利维亚达成一项贸易协议，仅仅是为了好玩。不，那是联邦政府的专属权力。 +

保留权力是由各州保留的权力，这在第十修正案中有解释。它是这样说的：“宪法未授予合众国、也未禁止各州行使的权力，由各州各自保留。”所以，传统上这些权力包括警察权力、医院、教育等等。 +

然后是共同权力，这是联邦政府和州政府都拥有的权力。例如，如果你曾经有过一份工作，你就知道联邦政府和州政府都会从你的收入中征税。 +

这就是联邦制的基本概念。联邦政府并不拥有所有权力，各州也不是。它们分享权力。但是在过去的一个世纪左右，联邦制最突出的体现是通过一种叫做财政联邦制的方式。当你谈论财政问题时，你谈论的是钱。所以权力在很大程度上是通过金钱来分享的。这意味着什么呢？嗯，国会能够制定国家标准，然后将资金导向遵守这些标准的州，而对不遵守标准的州扣留资金。这通过几种方式实现。 +

首先是通过拨款，有两种拨款方式。第一种是专项拨款，这些拨款是在各州遵守特定的联邦标准的情况下给予各州的。换句话说，联邦政府对各州说，我有一袋钱给你们，但你们必须按照我想要的方式使用它。这些拨款被用作激励措施来实现学校的种族融合，以及林登·约翰逊政府时期的相关事务。它们也被用来将饮酒年龄提高到21岁。在那种情况下，联邦政府向各州提供专项拨款用于维护州际高速公路，如果各州提高饮酒年龄，他们就能得到这笔钱，否则就没有。专项拨款是针对各州非常具体的需求，并且由国会决定这些钱将如何使用。 +

但是，整笔拨款有点不同。它们仍然是由国会提供给各州的，但附带的条件要少得多。这些拨款是为了一个相对广泛的目的给予各州的，各州可以按照自己认为合适的方式使用这笔钱。所以在这种情况下，国会可能会给一个州钱用于预防犯罪，而这个州可以决定如何使用这笔钱来满足这一要求。也许他们会雇佣更多的警察，也许他们会投资于囚犯的康复项目。他们可以用这笔钱做任何他们想做的事情。在这种拨款中，各州有决定权，但仍然有一些限制。例如，他们不能把预防犯罪拨款的钱用于改善高速公路。 +

财政联邦制的另一种表现方式是通过指令。指令要求各州遵守联邦的指示，但通常遵守这些指示超出了各州的预算能力。所以联邦政府制定规则，然后提供资金来帮助各州遵守这些规则。例如，当国会通过1970年的《清洁空气法》时，它要求所有各州努力减少烟雾、酸雨和其他污染物的排放。这些是国家要求，所以联邦政府向各州提供资金来帮助它们满足这些指令。 +

还有一种无资金支持的指令，正如其名：联邦政府发布指令，但不提供任何资金来帮助各州实现它。然而，在里根总统时期的权力下放革命期间，这些无资金支持的指令在很大程度上被废除了。里根倡导权力下放的过程，也就是将权力从联邦政府下放到各州。后来，克林顿总统签署了《无资金支持的指令改革法案》，剥夺了国会发布无资金支持指令的权力。所以，如果你想把这放在一个范围内考虑——我知道你想——各州非常喜欢收入分享，但非常讨厌无资金支持的指令，而专项拨款和整笔拨款则处于他们喜欢和讨厌的中间状态。 +

好的，这些就是联邦制的基本内容以及它的主要表现形式财政联邦制。现在，我可能不需要告诉你，关于州政府和联邦政府之间的权力分享一直存在争论，并且这种权力平衡随着时间的推移而改变，这取决于国家的需求和情况。让我给你举两个例子。 +

第一个例子是关于政府监控。在2001年9月11日的恐怖袭击之后，国会通过了《美国爱国者法案》，以寻找并阻止未来的恐怖分子。这项法案增加了联邦机构通过电话窃听和监控电子邮件来收集情报的能力。这项法律在两党强大的支持下通过，但没过多久，美国公民就发出了抗议声。他们认为这种联邦权力侵犯了他们第四修正案所保障的权利，即免受不合理搜查和扣押的权利。 +

另一个例子是在教育领域。从历史上看，教育是各州的特权，但在2001年，国会通过了《不让一个孩子掉队法案》，通过这项法案，联邦政府全面介入了教育领域。基本上，这项法律规定，为了获得学校所依赖的联邦资金，学校必须满足某些标准，而绝大多数学校发现这些标准几乎无法达到。如果学校不满足这些标准，它们将受到制裁。这引发了各州的抗议，他们认为这项法律代表了联邦政府对州权力领域的过度干预。所以，是的，这场争论今天仍然在继续，而且可能会一直持续下去。 +

在联邦和州权力之间的这种平衡行为的核心是一些宪法条款和两个重要的最高法院案例。首先让我们看看宪法。州政府和联邦政府之间的权力平衡受到宪法四个部分的深刻影响。首先，你需要知道第十修正案，我刚才已经提到过它。其次是第十四修正案，我们将在第三单元对它有更多的讨论，但现在你真正需要知道的是，这项修正案将《权利法案》——也就是宪法的前十条修正案——应用于各州。记住，《权利法案》最初是保护公民免受联邦政府的侵害，但第十四修正案赋予联邦政府权力，以确保各州也维护公民的自由。 +

第三是“商业条款”，它允许国会规范各州之间的商业活动，国会广泛使用这项权力来让各州服从它的意志。第四是“必要和适当条款”——也被称为“弹性条款”。你还记得几分钟前我们谈到的国会的专属权力吗？嗯，这些权力在宪法第一条第八款中被明确列出，但它最后说，国会可以制定任何其他必要和适当的法律来维护那些明确列出的权力。这就是亚历山大·汉密尔顿为建立国家银行的必要性辩护的方式。宪法第一条第八款明确没有提到国会有权力建立银行。然而，它确实说国会有权力规范州际商业和征税，汉密尔顿认为，因此联邦政府有一个银行来储存所有这些资金是必要和适当的。 +

好的，这些就是联邦制核心的宪法条款。现在让我们看看两个最高法院案例，它们对权力平衡产生了影响。第一个案例是1819年的“麦卡洛克诉马里兰州案”（McCulloch versus Maryland）。这个案例是权力平衡向有利于联邦权力倾斜的一个例子。本质上，法院裁决“必要和适当条款”意味着联邦政府拥有一些即使在宪法中没有明确提到的权力。此外，法院认为宪法中的“最高权力条款”意味着，当两者发生冲突时，联邦法律优先于州法律。 +

你需要知道的第二个案例是1995年的“美国诉洛佩兹案”（United States versus Lopez）。这个案例是权力平衡向各州倾斜的一个例子。基本上，国会利用“商业条款”禁止在学校财产上携带枪支，而法院裁定，携带枪支上学与州际商业毫无关系，因此国会超越了它的权限进入了州的权力范围，这为州权力赢得了胜利。 +

好的，现在让我们看一些联邦制实际运作的例子，我将给你举两个例子：环境法规和大麻合法化。记住，我们从联邦制的角度来看待这两个例子——也就是州政府和联邦政府如何分享权力。 +

好的，先说环境法规。2015年，奥巴马总统带领美国加入了《巴黎协定》，这是一项解决气候变化问题的全球努力。这里面有很多内容，但你真正需要知道的是，由于这项协定，一些碳排放法规被强加给了各州。现在，特朗普总统上任后，他让美国退出了这项协定，但像加利福尼亚州这样的一些州保留了这些标准。所以，你知道，如果你是加利福尼亚州的一个工厂主，你想排放大量的温室气体，即使联邦限制允许这样做，州的限制也不会允许。 +

联邦制实际运作的第二个例子是大麻合法化。自20世纪30年代以来，根据联邦法律，大麻一直是非法的，但在80年代和90年代，出现了很多关于大麻潜在医疗益处的新研究。所以在1996年，加利福尼亚州通过全州投票使医用大麻合法化。这是参与式民主吗？我觉得是的。不管怎样，最终几个州也效仿了。到2012年，科罗拉多州将娱乐用大麻合法化。但是等一下，从联邦层面来看，大麻仍然是非法的，但在该州却是合法的。这是怎么回事呢？嗯，这就是联邦制，宝贝。奥巴马政府总体上支持大麻合法化，它表示不会使用联邦资源在科罗拉多州执行联邦关于大麻的法律。所以从联邦层面来看，大麻仍然是非法的吗？是的。联邦政府会对此采取行动吗？不会。从这个意义上说，各州就像民主的实验室。我们可以看到小规模下哪些行得通，哪些行不通，然后有可能在全国范围内实施行得通的做法。 +

好了，这些就是你需要了解的美国大学预修课程政府学第一单元的内容。如果你想在课堂上拿到A，在考试中拿到5分，那就点击这里获取终极复习资料包，然后看着你所有的梦想成真。如果这个视频对你有帮助，并且你想让我继续制作这样的视频，那就点击订阅按钮，我会照做的。海姆勒退场。 +

'''

== pure

hey there and welcome to heimler's history ap government edition. in this video i'm going to review everything you need to know for ap government unit 1. so in this video i'm going to cover the foundations of american democracy, how we got our constitution, and how federalism works. so if you're ready to get them brain cows milked with them baby, let's get to it.

before we jump into this i should mention that this unit review is part of my ap government review packet. not all the unit reviews are going to be here on youtube but they're all in that packet. and this packet has everything you need to get an a in your class and a five on your exam in may, including practice questions for every unit, essential questions for the course and answers to check your work, and full length practice exams when you're ready for the exam. so you know if that's something you're into then get your clicky finger out and have a look.

so let's begin with the foundations of american democracy and the first thing you absolutely need to know is the enlightenment. so basically this was a european intellectual movement in the 18th century that had all kinds of influence on how the framers of our constitution understood the principles of government. so let's get nice and cozy with a few of these enlightenment thinkers and their ideas.

first was the idea of natural rights and this was basically the idea that people are born with certain rights that are given to them by their creator. and that's important because that means those rights were not given to them by a monarch and therefore could not be taken away by a monarch. and related to this, enlightenment thinkers argued for a theoretical state of nature which comes before any kind of government, and in that state humans are free. and these ideas were exceedingly influential on the framers of the constitution.

the second enlightenment idea you need to know -- and technically this is two ideas but you know they're very closely related so whatever -- it's popular sovereignty and the social contract. the idea here is that by nature the power to govern is in the hands of the people -- that's the popular sovereignty part -- and that in order to protect their natural rights people willingly give some of that power away to a government -- and that's the social contract part. that means the state is the servant of the people and not the other way around. with respect to the social contract, the idea was that if the government violates the agreement it becomes a tyrannical turd, then the people's duty is to overthrow that government and switch it out for you know a non-turd government.

the third enlightenment idea you need to know is republicanism. so in a republican form of government people elect leaders to represent them and create laws in the public interest. additionally to keep this government from becoming tyrannical, power ought to be separated between three branches: the executive, the legislative, and the judicial. there are many other enlightenment ideas that influence the framers of the constitution but those are the major ones you need to know. and the sum of all of them taken together is basically this: that the best form of government is a limited government which by definition is a government that is prevented from tyranny through a system of checks and balances and the distribution of power among several acting members.

now hopefully as i went through some of those ideas they sounded kind of familiar. maybe not because you knew which thinkers were responsible for them or even if you knew the names, but because you have heard these ideas expressed in two of our foundational documents: the declaration of independence and the united states constitution. the declaration of independence provides the foundation for popular sovereignty, the social contract, and natural rights. and the enlightenment influence isn't that hard to spot: "we hold these truths to be self-evident, that all men are created equal, that they are endowed by their creator with certain unalienable rights, that among these are life, liberty, and the pursuit of happiness." and there you have a clear statement of natural rights -- although thomas jefferson the declaration's author substitute "a pursuit of happiness" for john locke's natural right of "life, liberty, and property" cause let's be honest big daddy government ain't got nearly enough hooch to go throwing around tracks of land to everybody like oprah -- you get some land, you get some land, you get some black... anyway, move on a little and you see the social contract in popular sovereignty: "that to secure these rights governments are instituted among men deriving their just powers from the consent of the governed." so you see the social contract like we establish governments to protect our natural rights, and then you see popular sovereignty that government gets its power from the people's consent. and then the constitution provides a blueprint for republicanism and the separation of powers which i'll talk more about later.

for now let's shift and talk about the three main kinds of democracy and how they are present in our system today. you've got pluralist, elite, and participatory. participatory democracy emphasizes broad participation in the political process by most if not all members of a society. pluralist democracy is a model in which groups of people associate with interest groups who then compete to influence public policy. this model provides the people with a voice not really individually but in chunks. elite democracy emphasizes more limited participation in policy making on the assumption that government is complicated and therefore the most educated people need to run it. now don't think of the us as embodying only one of these models. each of them exist depending on where you look. for example, participatory democracy shows up quite a bit more on local manifestations of government like town halls and small municipalities. also on a larger scale, participatory democracy is present at the state level in initiatives and referenda which are ways that people can vote directly on legislation and keep their representatives accountable.

pluralist democracy on the other hand shows up in the many interest groups that exist in the us. and let me just give you a couple of examples that you've probably heard of: number one the naacp which works for civil rights, and number two the national rifle association which works to promote second amendment rights. groups like these give people a voice and the bigger ones like i just mentioned wield a disproportionate amount of power over the political process. elite democracy was weakened by progressive era reforms like direct election of senators, but it still shows up in the electoral college where citizens get to vote but technically they're just voting for the electors who really vote for the president.

now we can also see the tension between these three models and three of our foundational documents: number one the constitution, number two federalist ten, and number three brutus one. in the constitution you can see elite democracy and the fact that elected representatives legislate on behalf of their people. then you can see pluralist democracy in the first amendment's freedom of assembly allowing political parties and interest groups to flourish. and you can see participatory democracy in things like the first amendment's freedom of speech and press that allow people to express their political opinions and also amendments that expanded voting rights like the 15th and the 19th amendments prohibiting race and sex as barriers to voting.

now this tension between the three forms of democracy is at the heart of the argument between federalist ten and brutus one. brutus championed a broad participatory model and feared the curtailment of personal liberties reflected in a larger republic like the united states. on the other hand, federalist 10 argued that with so many competing factions in a large republic, liberty would be upheld by their competition and that's an example of pluralist democracy.

okay now since these are required documents let's go a little deeper into both of them. now both of these documents are part of a larger whole produced by competing groups. these groups were the federalists and the anti-federalists and the main debate they were having was whether or not the state should ratify this new constitution. and by ratify it just means should the states accept this new constitution as law. and the big point of contention between federalist 10 and brutus one is basically this: majority rule versus minority rights. side note: in that day minority meant more like regional and economic minorities not ethnic categories. so the debate was pretty simple: like in a republican form of government the majority will rule but the minority shouldn't just be tyrannized by the majority either.

so in federalist 10, james madison took this on directly. he talked about the mischief of factions in a republic and factions when being defined are basically groups of people who believe their interests are more important than any other interest. thank goodness those don't exist anymore. madison was specifically worried about factions that had interest actually opposed to the rights and interests of others. and so the problem is this: if the majority always prevailed then the minority voice would never be represented. however if there were too many protections for the minority then the common good of the majority would be squashed. so madison said there were basically two solutions here: either you take away the causes of factions or you try to manage their effects. taking away the causes of factions means you'd have to strip people of their liberty so by madison's estimation the solution was worse than the problem. so therefore the only way to curb the mischief of factions was to mitigate their negative effects. he appealed to the size and diversity of the u.s population and said that with so many competing interests all of them would be set against each other and therefore none could prevail all the time. so a large republic would successfully deal with the threat of factions. additionally he argued that there was a double protection against the tyranny of factions provided by the separation of powers in the federal government and the sharing of power between the federal and state governments. so here you can see very plainly the arguments for a pluralist system.

now the anti-federalists who wrote the brutus essays were like son that argument is about as satisfying as a hair in a biscuit. you see they were exceedingly wary of the new constitution because it invested the federal government with a lot more power than it had under the articles of confederation under which most of the power belonged to the states. the anti-federalists were big participatory democracy folks and in brutus one the argument is about the dangers of a large centralized government and they were especially torqued up over the constitution's necessary and proper clause and the supremacy clause. we'll talk more about those later when we get into some supreme court cases but for now all you really need to know is that these two clauses gave more power to the federal government than the state government -- i mean potentially that's what they were arguing. brutus one essentially argued that a large centralized government could not adequately represent the views of the people because it would be largely separated from them.

okay now there's a lot more to say about these documents but here you just need to understand how they represent the tension between the different models of democracy. so let's turn the corner now and talk about how we got our constitution and for that we need to start with the first constitution of the united states: the articles of confederation. now i already mentioned that under this document the federal government was very weak and the state governments were disproportionately strong. it's not hard to understand why because the u.s still had kind of a monarchy hangover from being british subjects. and that's pretty much all the articles had going for it was that it avoided the tyranny of the centralized state. but oh baby were there some problems to be had with this form of government.

first of all there was only one branch of the federal government namely congress. like there was no president, no federal court, and congress had no power to raise revenue through taxes. like if they wanted money to fund their activities they just had to ask the states nicely and you could imagine how that went. additionally congress had no power to raise an army and even if they did -- see previous point about not having the money to pay an army.

so you know there were lots of events that highlighted the weaknesses of the articles but i'm only going to mention two. and first was regarding tax law enforcement. at the end of the day congress just couldn't pay its bills and the states understood that this was a problem. so in 1782 a resolution was proposed by the stage which granted congress the power to collect a 5% tax on imported goods. 11 out of 13 states said yes but two said no. in under the articles you had to have all 13 agree in order to change the articles themselves and so congress remained weak and broke.

but what displayed the weaknesses of the articles above all was a little event known as shay's rebellion. you don't really need to know the details of this rebellion so it's enough to know that a bunch of revolutionary war veterans were not getting paid by congress because again they had no money and yet congress still prosecuted them if they didn't pay their taxes. so because of this injustice a bunch of them rose up in massachusetts and guess what there was no national army to come in and help. so even though the people of massachusetts did end up mustering a militia to squash that rebellion, it made a lot of people realize that the federal government needed a lot more power in case these kinds of rebellions happened again. and judging by the sad state of the economy it wasn't that unlikely.

so a constitutional convention -- also known as the philadelphia convention -- was called in 1787. now the official goal of this convention was to modify the articles of confederation but they went ahead and ended up drafting an entirely new constitution. our boy george washington was presiding. hamilton, madison, and the rest of what was called the grand committee were tasked with forging compromises needed for a new governing document. as you can imagine this new governing document was the result of lots of heated and tense debate. and so within the document itself you can see many of these compromises that were reached in order to pass it and you need to know four of them.

first was the great compromise. this was a compromise on how the people would be represented in the new congress. there were a couple of competing proposals. first was the virginia plan which argued that congressional representatives should be apportioned by population. that's not hard to understand when you realize that virginia was a big state and under this plan big states would have more representatives and thus have more power. but the small states formally objected and said uh um and proposed the new jersey plan. and this plan argued that each state should be represented equally with one vote per state. now if you're paying attention that would mean that small states have a disproportionate amount of power since small populations have the same power as large populations under this system. so what to do? well the compromise was the creation of a bicameral congress which is to say there would be two houses. in the house of representatives the people will be represented by population and in the senate the states would be represented equally with two votes per state.

another compromise was on how the president would be elected. various delegates argued that the people should elect the president, then others argued that the state should do it, and then still others that congress should do it. the compromise they came up with was the electoral college. under this system each state is given a number of electors that corresponds to the number of congressional representatives that they have and the state legislatures have all the power to decide who those people are and it's those people who elect the president.

all right now the last two compromises you need to know deal with slavery which as you can imagine was the subject of some very intense debate. first was the question of how enslaved people will be counted in terms of representation in congress. not surprisingly northern states thought enslaved people shouldn't be counted at all on account of the southerners were always justifying the institution by claiming their enslaved laborers were less than human. and if that's the case why would you count them? but southerners countered and said uh we did not just fall off the turnip truck son that dog don't hunt. they wanted all the enslaved laborers to be counted and thus increased southern power in congress. and the compromise that solved this tension was known as the three-fifths compromise and basically it just meant that three-fifths of the enslaved population would count towards representation.

and then there was the compromise on the importation of slaves. this was a big one for southerners since their entire economy rose and fell on slavery. essentially the compromise was that congress couldn't touch the slave trade for 20 years after the constitution was ratified and after that the slave trade would be abolished.

now because these debates at the convention were so intense the framers of the constitution included a process by which the document could be amended and you can find it in article 5. basically it's a two-stage process to amend the constitution: there's proposal and then there's ratification. so an amendment can be proposed either by congress or by the states at a special convention and then a two-thirds vote is needed for the proposal to become official. then the amendment is sent to the states for ratification and for that to happen three quarters of state legislatures or state ratifying conventions need to agree and if they do that amendment becomes law.

now ultimately despite all the conflict that i just mentioned the constitution was circulated to the states and was ratified in june of 1788 and at that point became the governing document of the united states. at this point let us pause and high five a bald eagle. america. even so the constitution has proven to be a very durable document throughout the history of america and one of the main reasons is because it did such a good job of separating power and providing checks and balances to make sure that no branch becomes too powerful.

let me just give you some examples. the legislative branch -- which is to say congress -- is basically responsible for proposing and making laws. no other branch can make laws and there are plenty of access points for people to speak into those laws. and just so you know those people are called stakeholders. people can write letters or emails to the representatives or if they're wanting to punish themselves they can watch c-span which are congressional proceedings. i mean yes it's super boring but it is kind of an amazing thing that we can watch what our representatives are doing like this does not happen in more repressive countries. and an example of the power of congress to check the other branches is the senate's power of advice and consent. this means that any appointments that the president makes to the presidential cabinet or the supreme court or any other federal office has to be approved by the senate.

the executive branch is responsible for executing and enforcing the laws and no other branch has that power. and here too stakeholders have multiple access points. i mean you can't just like call up the president but the agencies run by the executive branch can absolutely be accessed by average citizens. if you're so inclined you can file a complaint at one of these agencies or you can report crimes being committed. and a good example of the executive branch's checking power is the veto. if congress passes a law the president doesn't like the president can veto it and it becomes null and void unless of course congress overrides that veto with a two-thirds vote. so you know much checking.

the judicial branch is responsible for determining the constitutionality of laws and no other branch has that power. and stakeholders can use the court system to challenge unjust and unconstitutional laws as well as appeal wrongful convictions. an example of the checking power of the judicial branch is the power of judicial review. now this power isn't technically in the constitution but it was developed out of the nature of the court. it basically means that it's the court's prerogative to judge the laws passed by congress and signed by the president on the merits of their constitutionality. and if the court finds a law to be unconstitutional you burn.

okay so that's how we got our constitution. now let's turn the corner and talk about federalism. now look i know this video has already been long but you have to pay attention here because students always get confused by this term. when you hear federalism you think i'm about to say something about the federal government's power but that is not what federalism is. like crack those brain folds open and get this down: federalism is the sharing of power between national governments and state governments. that's all it is. it's just the sharing of power.

now in order to understand this let's talk about the exclusive powers, reserve powers, and concurrent powers. exclusive powers are those powers specifically delegated by the constitution to the federal government. for example only congress can make treaties with other sovereign nations. alabama can't just say you know i think we're going to get into a trade agreement with bolivia you know just for funsies. no that is an exclusive power of the federal government.

reserved powers are those powers kept by the states and this is explained in the 10th amendment. it says this: "the powers not delegated to the united states by the constitution, nor prohibited by it to the states, are reserved to the states." so traditionally these powers have included things like police powers, hospitals, education, and a lot more.

and then you have concurrent powers which are powers that are shared by both the federal and state governments. for example if you've ever had a job you know that both the federal and state governments pull taxes from your income.

now that's the basic idea of federalism. the federal government doesn't have all the power nor do the states. they share power. but over the course of the last century or so the way that federalism has been most prominently manifested is through something called fiscal federalism. and when you're talking about fiscal matters you're talking about the boom boom. so power has largely been shared through money. and what does that mean? well congress is able to establish national standards and then direct funds to states that comply with those standards and then withhold funding from states that do not. and that happens in several ways.

first is through grants and there are two kinds. first are categorical grants and these are grants given to the states as long as the states comply with specific federal standards. in other words big daddy government says to the states i got a bag full of money for you and you got to spend it the way i want you to. these kind of grants were used as incentives to integrate schools and lyndon johnson's administration. they were also used to raise the drinking age to 21. in that case the federal government offered categorical grants to states for the upkeep of their interstate highways and if they raised their drinking age they got the money if not no soup for you. categorical grants are given to very specific needs of the states and congress decides how that money is going to be spent.

but block grants on the other hand are a little different. they still come from congress to the states but there are far less strings attached. these grants are given to states for a relatively broad purpose and the states can spend that money as they see fit. so in this case congress might give a state money for the prevention of crime and the state decides exactly how to spend that money in order to meet that requirement. maybe they hire more police officers maybe they invest in rehabilitation programs for inmates. they can do whatever they want with it. the state has discretion in this kind of grant but there are still limits. for example they can't just spend money from a crime prevention grant on highway improvement.

another way fiscal federalism plays out is through mandates. so mandates require states to follow federal directives but often compliance with these directives is beyond a state's budget capacity. so the federal government sets the rules and then provides money to help those states comply. so for example when congress passed the clean air act of 1970 it mandated that all states work to reduce smog, acid rain, and the release of other pollutants. and these were national requirements and so the federal government provided funds to states to help them meet those mandates.

now there is such a thing as an unfunded mandate and that's exactly what it sounds like: the federal government issues the mandate and then provides no funding whatsoever to help the states achieve it. however these were largely struck down during the devolution revolution of the 1980s under president reagan. he championed the process of devolution or return of power to the states away from the federal government. later president clinton signed the unfunded mandates reform act which denied congress the power to issue unfunded mandates. so if you wanted to put this on a spectrum -- and i know that you do -- states really like revenue sharing but really hate unfunded mandates and categorical and block grants are somewhere in the middle of their love hate spectrum.

okay so those are the basics of federalism and its chief manifestation fiscal federalism. now i probably don't need to tell you that there has always been an argument over the sharing of power between state and federal governments and the balance of that power has changed over time depending on the needs and situation of the nation. let me give you two examples.

first regarding government surveillance. after the terrorist attacks on september 11, 2001 congress responded with the usa patriot act in order to find and stop future terrorists. this act increased the ability of the federal agencies to gather intelligence by phone tapping and monitoring emails. now that law passed with strong bipartisan support but it wasn't long before an outcry rose up among american citizens. they argued that such federal power was a violation of their fourth amendment rights to be secure against unreasonable searches and seizures.

another example is in the domain of education. historically education has been the prerogative of the states but in 2001 congress passed the no child left behind act and with this the federal government got all up in education. basically the law said that in order to receive federal funding on which schools depend, schools had to meet certain criteria which were largely found to be unattainable by a vast majority of schools. and if the schools did not meet those criteria they were slapped with sanctions. and this led to an outcry from the states that this law represented federal overreach into the dominion of state power. so yeah this argument is still going on today and will probably always be going on.

at the very heart of that balancing act between federal and state power are a few constitutional provisions and two required supreme court cases. first let's look at the constitution. the balance of power between the states and federal government is deeply affected by four parts of the constitution. first you need to know the 10th amendment and i already mentioned that just a minute ago. second the 14th amendment and we'll have a lot more to say about this one in unit 3 but for now all you really need to know is that this amendment applies the bill of rights -- or the first 10 amendments of the constitution -- to the states. remember the bill of rights originally protected citizens from the federal government but the 14th amendment empowers the federal government to make sure that citizens liberties are also upheld by the state.

third you have the commerce clause which allows congress to regulate commerce among the states and this one has been widely used by congress to bring states into submission to its will. and then fourth you have the necessary and proper clause -- also known as the elastic clause. do you remember lo those many minutes ago when we talked about the exclusive powers of congress? well those are explicitly outlined in article 1 section 8 of the constitution but it ends by saying that congress can make any other law that is necessary and proper to the upholding of those powers that are explicitly listed. this is how alexander hamilton justified the need for a national bank. article 1 section 8 says precisely nothing about congress having the power to establish a bank. however it does say that congress has the power to regulate interstate commerce and raise taxes and hamilton argued that it was therefore necessary and proper that the federal government have a bank to store all those funds.

okay those are the constitutional provisions at the heart of federalism. and now let's have a look at two supreme court cases that have weighed in on the balance of power. first is mcculloch versus maryland in 1819. this case is an example of the balance of power tipping in favor of federal power. essentially the court ruled that the necessary and proper clause implied certain powers given to the federal government even if they were not explicitly mentioned in the constitution. additionally the court argued that the supremacy clause in the constitution meant that where the two conflicted, federal law trumps state law.

the second case you need to know is the united states versus lopez in 1995. now this case is an example of the balance of power tipping towards the states. basically congress had used the commerce clause to ban guns on school property and the court decided that carrying guns to school is in no way related to interstate commerce and thus congress had overstepped its bounds into state authority thus providing a win for state power.

okay now let's get some examples of federalism in action and i'm just going to give you two: environmental regulations and the legalization of marijuana. and remember we're looking at both of these through the lens of federalism -- how state and federal governments share power.

okay so environmental regulation. in 2015 president obama led the u.s into the paris agreement which was a worldwide effort to address climate change. and there was a lot going on there but all you really need to know is that certain carbon emission regulations were imposed on states as a result of this agreement. now once president trump was in office he removed the u.s from the agreement but some states like california kept the standards. so you know now if you're a factory owner in california and you want to emit a butt load of greenhouse gases even though federal limitations would permit it, state limitations will not.

the second example of federalism in action is the legalization of marijuana. now this substance has been illegal by federal law since the 1930s but in the 80s and 90s a lot of new research was emerging on the potential medical benefits of marijuana. and so in 1996 california legalized medical marijuana by means of a statewide vote. is that participatory democracy? i smell yes it is. anyway eventually several states followed suit and by 2012 colorado legalized recreational use of marijuana. but wait a minute it's illegal federally but it's legal in the state. how does that work? well that's federalism baby. the obama administration which is generally favorable to the legalization stated that it would not use federal resources to enforce that federal law in colorado. so was it still illegal federally? yeah. is the federal government going to do anything about it? no. and in that way states are like laboratories for democracy. we can see what works on a small scale and what doesn't work and then potentially implement what works on a national scale.

well okay that's what you need to know about unit 1 of ap government. if you want help getting an a in your class and a 5 on your exam may then click right here and grab that ultimate review packet and watch all your dreams come true. if this video helped you you want to send me the signal to keep making them then click that subscribe button and i shall oblige. heimler out.

'''

