
= 1.01 Ideals of DEMOCRACY
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there and welcome to a new year at Heimler's History. This year we're going through the AP Government curriculum 课程 topic by topic, and in this video we're starting at the beginning with the ideals 理想；理念 of democracy 民主. So we ain't got no time to waste. Get them brain cows ready to milk, and let's get to it. +
So what we're aiming to do in this video is simple: explain how democratic ideals are reflected in the Declaration of Independence and the Constitution. So when we're talking about democratic ideals, the main ideal is limited government 有限政府，which is exactly what it sounds like. People in democratic societies like ours admit the need for a government, but let's keep it as limited as possible. +
Now this idea of limited government didn't just spring out of the founders like Athena from Zeus's head. They were actually influenced by a European intellectual 智力的；知识的 movement called the Enlightenment 启蒙运动. And let me just tell you, it is hard to overstate 夸大其词；过分强调 how much Enlightenment thought influenced the founders of our fair nation. What's that? You want to hear more? I got you, boo. +
So when it comes to the democratic ideal of limited government, there are several subcategories 子类别 of Enlightenment ideas that you should be familiar with. First, let's talk about natural rights 自然权利. And this was basically the idea that people are born with certain rights that are given to them by their creator, and that is important because that means that those rights were not given to them by a monarch 君主 and therefore could not be taken away by a monarch. For this idea, you can think about our boys John Locke and Thomas Hobbes. +
Locke wrote in his Second Treatise on Civil Government that people are endowed 赋予，just by virtue of 由于 being born a human, with the rights of life, liberty, and property 财产. And both Locke and Hobbes argued for a theoretical 理论的 state of nature 自然状态 which comes before any kind of government, and in that state humans are free. Now for Hobbes, the state of nature was kind of a hot mess because without a government, everyone would be clamoring 吵吵嚷嚷；大声疾呼 all over each other to keep their rights secure, thus the need for a government. Locke had kind of a rosier 更乐观的 view of the state of nature. Like according to him, this was the state that everyone was born free and just walking around giving each other state of nature hugs. +
Regardless of the difference, these ideas were exceedingly 极其；非常 influential 有影响力的 on the writers of the Declaration of Independence and the Constitution. The second Enlightenment idea you need to know -- and you know technically this is two, but they're pretty closely related -- is popular sovereignty 人民主权 and the social contract 社会契约. The idea here is that by nature, the power to govern is in the hands of the people (that's the popular sovereignty part), and to protect their natural rights, people willingly give over some of that power to a government (that's the social contract part). That means the state is the servant of the people and not the other way around. And for these ideas, we can thank Jean-Jacques Rousseau and his treatise 论文；专题著作 called The Social Contract. +
Now with respect to the social contract, Rousseau also wrote that if the government violates 违反；违背 the agreement -- becomes a tyrannical 专制的；暴虐的 turd -- then the people's duty is to overthrow 推翻 that government and switch it out for a non-turd government. The third Enlightenment idea you need to know is republicanism 共和主义. And for this, we have the Baron de Montesquieu in his book The Spirit of the Laws to thank. He explained that a republican form of government means that the people elect leaders to represent them and create laws in the public interest 公共利益. Additionally, in order to keep this government from becoming tyrannical, he argued that power ought to be separated between three branches 分支；部门: the executive 行政部门，the legislative 立法部门，and the judicial 司法部门 (of which we'll have far more to say in Unit 2). +
Okay, so all of those ideas taken together provide the basis for our democratic ideal of limited government. Now those are the main Enlightenment ideas you need to know about, and the reason you need to know about them is because they had a metric buttload of influence on the founders of this nation. In order to see that influence, we need to look at two of our foundational 基础的；基本的 documents for this course. And by the way, when I say foundational documents, I mean that these are specifically mentioned in the curriculum as documents that you need to be familiar with. +
So let's see the influence of Enlightenment ideals on the first foundational document you need to know: the Declaration of Independence. The Declaration, of course, was the document that outlined 概述；概括 the reasons for the official break between the American colonies and the British Empire. It was written by Thomas Jefferson with editorial 编辑的 help from John Adams and Benjamin Franklin and some others. In this video, I'm only going to show you Enlightenment influences on the document, but I have another video that covers the document more extensively, so you're going to want to watch that so you know how to use it in your argumentative essays and your short answer questions. +
So the significant 重要的；有意义的 portions of the Declaration of Independence that demonstrate Enlightenment thought are as follows: "We hold these truths to be self-evident 不证自明的，that all men are created equal, that they are endowed by their Creator with certain unalienable 不可剥夺的 Rights, that among these are Life, Liberty and the pursuit of Happiness." Okay, if you've been paying attention, you should hear John Locke and natural rights all over that -- except Jefferson altered 改变 Locke's threefold 三重的 natural rights structure from "life, liberty, and property" to "life, liberty, and the pursuit of happiness." +
Then in the next sentence you hear this: "That to secure 保障；保护 these rights, Governments are instituted 建立；设立 among Men." There you have the social contract -- people create governments in order to protect their natural rights. And just to be clear where does the government get this power? "Deriving 获得；得到 their just powers from the consent 同意；准许 of the governed." That is the idea of popular sovereignty -- the power to govern is in the hands of the people. +
Now it's the Constitution, which is another foundational document, which provides the blueprint 蓝图 especially for the Enlightenment ideas of separation of powers 权力分立 and republicanism. Now the Constitution that we know was not the first constitution of the United States. The first constitution was the Articles of Confederation, but that'll get its own video. The short story is that the Articles as a governing document for this nation was about as effective as a dog trying to bury a turd in a frozen pond. And so delegates 代表 met at the Philadelphia Convention in 1787 (otherwise known as the Constitutional Convention) in order to draft 起草 a new constitution. +
George Washington presided over 主持 the convention, and it was a group of folks known as the Grand Committee which was tasked with 承担；负责 forging 形成；缔造 the compromises 妥协；折中 that were required to draft a new governing document. Our boy James Madison took the lead on writing it, and in doing so laid the foundation for republicanism and the separation of powers. +
Okay, let's talk about republicanism first. And that is reflected in the Constitution because the framers 制定者；创作者 created a representative republic 代议制共和国. That means that instead of the United States being a pure democracy in which everybody gets a vote, the people would vote into office representatives who would legislate 立法 on behalf of 代表 the people. You see, despite the fact that in everyday language people think of the United States as a democracy, by a strict definition 定义 it is not. The framers actually feared pure democracy because they had a pretty low opinion of most human beings, and they feared that democracy would lead to mob rule 暴民统治. So they created a republican system, which is not to be confused with the modern Republican Party -- not the same thing. We're talking about republicanism as a form of government. +
Second, the separation of powers is reflected in the Constitution because the framers took notes from our buddy Montesquieu and separated the powers of the federal government into three branches: the executive, the legislative, and the judicial. And it's important to know that each of those branches has the authority 权力；职权 to check 制衡 the power of the others so that none of them can grow too powerful. +
Well, that's Unit 1 Topic 1 of AP Government. If you need help getting an A in your class and a five on your exam in May, then click right over here and grab a review packet. And baby, it's got more sauce than a Texas barbecue. If you were helped by this video and you want me to keep making them, the way that you let me know that is by subscribing. Heimler out. +

'''

== 中文释义

嘿，欢迎来到海姆勒历史课的新一年。今年我们将逐 topic 地学习 AP 政府课程的内容，在这个视频中，我们将从民主理想开始讲起。所以我们没有时间可以浪费。准备好开动脑筋，让我们开始吧。 +

所以在这个视频中我们的目标很简单：解释"民主理想"是如何体现在《独立宣言》和《宪法》中的。所以**当我们谈论"民主理想"时，其主要理想是"有限政府"，**听名字就知道是什么意思。*在像我们这样的民主社会中，人们承认需要一个政府，但我们要尽可能地限制它的权力。* +

*"有限政府"这个理念,* 并不是像雅典娜从宙斯的脑袋中诞生那样，突然从建国者们的脑海中冒出来的。实际上，他们**受到了一场名为"启蒙运动"的欧洲思想运动的影响。**让我告诉你，很难夸大启蒙思想对我们这个美好国家的建国者们的影响。什么？你想了解更多？我懂你，亲爱的。 +

所以当谈到"有限政府"的民主理想时，有几个启蒙思想的子类别是你应该熟悉的。首先，让我们谈谈**"自然权利"。这基本上是指人们生来就拥有某些由他们的造物主赋予的权利，**这很重要，因为**这意味着这些权利不是由君主赋予的，因此也不能被君主剥夺。**对于这个理念，你可以想想约翰・洛克（John Locke）和托马斯・霍布斯（Thomas Hobbes）这两位人物。 +

洛克在他的《政府论（下篇）》中写道，**人们仅仅因为"生而为人"，就被赋予了生命、自由和财产的权利。**洛克和霍布斯都主张, 在任何政府之前存在一种理论上的自然状态，在那种状态下人类是自由的。对于霍布斯来说，**自然状态有点混乱，因为没有政府的话，每个人都会为了保障自己的权利而相互争斗，因此需要一个政府。**洛克对自然状态的看法则更乐观一些。按照他的说法，在那种状态下，每个人生来自由，彼此友好相处。 +

不管有什么差异，**这些思想对《独立宣言》和《宪法》的撰写者产生了极其深远的影响。**你需要了解的第二个启蒙思想 —— **严格来说这是两个思想，但它们紧密相关 —— 是"人民主权"和"社会契约"。**这里的理念是，**从本质上讲，治理的权力掌握在人民手中（这就是"人民主权"的部分），为了保护他们的"自然权利"，人们自愿将部分权力交给政府（这就是"社会契约"的部分）。这意味着国家是人民的公仆，而不是相反。**对于这些思想，我们要感谢让 - 雅克・卢梭（Jean-Jacques Rousseau）和他的著作《社会契约论》。 +

说到社会契约，卢梭还写道，**如果政府违反了协议，变成了一个暴虐的存在，那么人民有责任推翻那个政府，换成一个不暴虐的政府。**

你需要了解的**第三个启蒙思想是"共和主义"。**对于这一点，我们要感谢孟德斯鸠男爵（Baron de Montesquieu）在他的《论法的精神》一书中的阐述。他解释说，*"共和政体"意味着人民选举领导人来代表他们，并为了公共利益制定法律。此外，为了防止政府变得暴虐，他主张权力应该分为三个分支：行政、立法和司法*（关于这一点，我们在第 2 单元会有更多讨论）。 +

好的，*所有这些思想, 共同为我们"有限政府"的民主理想提供了基础*。这些就是你需要了解的主要启蒙思想，你需要了解它们的原因, 是**它们对这个国家(美国)的建国者产生了巨大的影响。**为了看到这种影响，我们需要看看本课程的两份基础文件。顺便说一下，*当我说基础文件时，我指的是课程中明确提到的你需要熟悉的文件。* +

所以让我们看看"启蒙理想"对我们需要了解的**第一份基础文件《独立宣言》**的影响。《独立宣言》当然是一份概述美国殖民地与大英帝国正式决裂原因的文件。它由托马斯・杰斐逊（Thomas Jefferson）撰写，并在约翰・亚当斯（John Adams）、本杰明・富兰克林（Benjamin Franklin）和其他一些人的编辑帮助下完成。在这个视频中，我只会展示启蒙思想对这份文件的影响，但我还有另一个视频更广泛地涵盖了这份文件，所以你可能会想看那个视频，这样你就知道如何在议论文和简答题中运用它了。 +

所以**《独立宣言》中体现启蒙思想的重要部分如下：“我们认为这些真理是不言而喻的：人人生而平等，他们被他们的造物主赋予某些不可剥夺的权利，其中包括生命、自由, 和追求幸福的权利。” **好吧，如果你一直在关注，你应该能从中听到约翰・洛克和自然权利的影子 —— 只是**杰斐逊将洛克的"三项自然权利"结构, 从 “生命、自由和财产” 改为了 “生命、自由和追求幸福”。** +

然后在下一句话中你会听到：**“为了保障这些权利，人们建立了政府。” 这里体现了"社会契约" —— 人们建立政府是为了保护他们的"自然权利"。**需要明确的是，*政府的权力从何而来呢？“政府的正当权力，来自被统治者的同意。” 这就是"人民主权"的理念 —— 治理的权力掌握在人民手中。* +

现在来说说**《宪法》，这是另一份基础文件，它尤其为"权力分立"和"共和主义"的启蒙思想提供了蓝图。**我们所知道的《宪法》并不是美国的第一部宪法。第一部宪法是《邦联条例》，不过关于它我会单独做一个视频。简单来说，《邦联条例》作为这个国家的治理文件，其有效性就如同一只狗试图在结冰的池塘里掩埋粪便一样（没什么效果）。所以**代表们在 1787 年齐聚"费城会议"（也被称为"制宪会议"），以起草一部新宪法。** +

乔治・华盛顿（George Washington）主持了这次会议，一个被称为 “大委员会” 的团体, 负责达成必要的妥协，以起草一份新的治理文件。我们的朋友詹姆斯・麦迪逊（James Madison）带头撰写这份文件，并且在此过程中,为"共和主义"和"权力分立"奠定了基础。 +

好的，让我们先来谈谈**"共和主义"。这在《宪法》中有所体现，因为制宪者们创建了一个"代议制共和国"。这意味着美国不是一个纯粹的民主国家（在纯粹民主国家中, 每个人都能投票），人民会选举代表，这些代表会代表人民进行立法。(即, 美国是"代议制民主", 而不是"直接民主".)**你看，尽管在日常用语中人们认为美国是一个民主国家，但严格来说，它不是。*制宪者们实际上害怕纯粹的民主，因为他们对大多数人评价不高，并且他们担心民主会导致"暴民统治"。所以他们创建了一个共和制体系，这和现代的"共和党"（Republican Party）不是一回事哦。我们这里说的"共和主义"是一种政府形式。* +

第二，**"权力分立"在《宪法》中有所体现，**因为**制宪者们借鉴了我们的朋友孟德斯鸠的思想，将联邦政府的权力分为三个分支：行政、立法和司法。**重要的是要知道，*#每个分支, 都有权制衡其他分支的权力，这样没有一个分支会变得过于强大。# +*

好了，这就是 AP 政府课程第 1 单元第 1 个 topic 的内容。如果你需要帮助在课堂上得 A 并且在五月份的考试中得 5 分，那么点击这里获取一份复习资料包。宝贝，它的内容可比德克萨斯烧烤还要丰富哦。如果你觉得这个视频对你有帮助，并且希望我继续制作更多这样的视频，那就订阅吧。海姆勒下线了。 +


'''

== pure

Hey there and welcome to a new year at Heimler's History. This year we're going through the AP Government curriculum topic by topic, and in this video we're starting at the beginning with the ideals of democracy. So we ain't got no time to waste. Get them brain cows ready to milk, and let's get to it.

So what we're aiming to do in this video is simple: explain how democratic ideals are reflected in the Declaration of Independence and the Constitution. So when we're talking about democratic ideals, the main ideal is limited government, which is exactly what it sounds like. People in democratic societies like ours admit the need for a government, but let's keep it as limited as possible.

Now this idea of limited government didn't just spring out of the founders like Athena from Zeus's head. They were actually influenced by a European intellectual movement called the Enlightenment. And let me just tell you, it is hard to overstate how much Enlightenment thought influenced the founders of our fair nation. What's that? You want to hear more? I got you, boo.

So when it comes to the democratic ideal of limited government, there are several subcategories of Enlightenment ideas that you should be familiar with. First, let's talk about natural rights. And this was basically the idea that people are born with certain rights that are given to them by their creator, and that is important because that means that those rights were not given to them by a monarch and therefore could not be taken away by a monarch. For this idea, you can think about our boys John Locke and Thomas Hobbes.

Locke wrote in his Second Treatise on Civil Government that people are endowed, just by virtue of being born a human, with the rights of life, liberty, and property. And both Locke and Hobbes argued for a theoretical state of nature which comes before any kind of government, and in that state humans are free. Now for Hobbes, the state of nature was kind of a hot mess because without a government, everyone would be clamoring all over each other to keep their rights secure, thus the need for a government. Locke had kind of a rosier view of the state of nature. Like according to him, this was the state that everyone was born free and just walking around giving each other state of nature hugs.

Regardless of the difference, these ideas were exceedingly influential on the writers of the Declaration of Independence and the Constitution. The second Enlightenment idea you need to know -- and you know technically this is two, but they're pretty closely related -- is popular sovereignty and the social contract. The idea here is that by nature, the power to govern is in the hands of the people (that's the popular sovereignty part), and to protect their natural rights, people willingly give over some of that power to a government (that's the social contract part). That means the state is the servant of the people and not the other way around. And for these ideas, we can thank Jean-Jacques Rousseau and his treatise called The Social Contract.

Now with respect to the social contract, Rousseau also wrote that if the government violates the agreement -- becomes a tyrannical turd -- then the people's duty is to overthrow that government and switch it out for a non-turd government. The third Enlightenment idea you need to know is republicanism. And for this, we have the Baron de Montesquieu in his book The Spirit of the Laws to thank. He explained that a republican form of government means that the people elect leaders to represent them and create laws in the public interest. Additionally, in order to keep this government from becoming tyrannical, he argued that power ought to be separated between three branches: the executive, the legislative, and the judicial (of which we'll have far more to say in Unit 2).

Okay, so all of those ideas taken together provide the basis for our democratic ideal of limited government. Now those are the main Enlightenment ideas you need to know about, and the reason you need to know about them is because they had a metric buttload of influence on the founders of this nation. In order to see that influence, we need to look at two of our foundational documents for this course. And by the way, when I say foundational documents, I mean that these are specifically mentioned in the curriculum as documents that you need to be familiar with.

So let's see the influence of Enlightenment ideals on the first foundational document you need to know: the Declaration of Independence. The Declaration, of course, was the document that outlined the reasons for the official break between the American colonies and the British Empire. It was written by Thomas Jefferson with editorial help from John Adams and Benjamin Franklin and some others. In this video, I'm only going to show you Enlightenment influences on the document, but I have another video that covers the document more extensively, so you're going to want to watch that so you know how to use it in your argumentative essays and your short answer questions.

So the significant portions of the Declaration of Independence that demonstrate Enlightenment thought are as follows: "We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit of Happiness." Okay, if you've been paying attention, you should hear John Locke and natural rights all over that -- except Jefferson altered Locke's threefold natural rights structure from "life, liberty, and property" to "life, liberty, and the pursuit of happiness."

Then in the next sentence you hear this: "That to secure these rights, Governments are instituted among Men." There you have the social contract -- people create governments in order to protect their natural rights. And just to be clear where does the government get this power? "Deriving their just powers from the consent of the governed." That is the idea of popular sovereignty -- the power to govern is in the hands of the people.

Now it's the Constitution, which is another foundational document, which provides the blueprint especially for the Enlightenment ideas of separation of powers and republicanism. Now the Constitution that we know was not the first constitution of the United States. The first constitution was the Articles of Confederation, but that'll get its own video. The short story is that the Articles as a governing document for this nation was about as effective as a dog trying to bury a turd in a frozen pond. And so delegates met at the Philadelphia Convention in 1787 (otherwise known as the Constitutional Convention) in order to draft a new constitution.

George Washington presided over the convention, and it was a group of folks known as the Grand Committee which was tasked with forging the compromises that were required to draft a new governing document. Our boy James Madison took the lead on writing it, and in doing so laid the foundation for republicanism and the separation of powers.

Okay, let's talk about republicanism first. And that is reflected in the Constitution because the framers created a representative republic. That means that instead of the United States being a pure democracy in which everybody gets a vote, the people would vote into office representatives who would legislate on behalf of the people. You see, despite the fact that in everyday language people think of the United States as a democracy, by a strict definition it is not. The framers actually feared pure democracy because they had a pretty low opinion of most human beings, and they feared that democracy would lead to mob rule. So they created a republican system, which is not to be confused with the modern Republican Party -- not the same thing. We're talking about republicanism as a form of government.

Second, the separation of powers is reflected in the Constitution because the framers took notes from our buddy Montesquieu and separated the powers of the federal government into three branches: the executive, the legislative, and the judicial. And it's important to know that each of those branches has the authority to check the power of the others so that none of them can grow too powerful.

Well, that's Unit 1 Topic 1 of AP Government. If you need help getting an A in your class and a five on your exam in May, then click right over here and grab a review packet. And baby, it's got more sauce than a Texas barbecue. If you were helped by this video and you want me to keep making them, the way that you let me know that is by subscribing. Heimler out.


'''

