
= 1.07 FEDERALISM - The Relationship Between STATES and FEDERAL Government
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History. We've been going through 经历；浏览 Unit 1 of the AP Government curriculum 课程体系, and in this video, it's time to talk about federalism 联邦制. So if you're ready to get them brain cows milked well （形象表达，激发思维、获取知识）, then let's get to it. +

So in this video, here's what we're trying to accomplish 完成；实现: Explain how societal needs 社会需求 affect the constitutional allocation 宪法分配 of power between the national and state governments. Okay, so the allocation of power between national and state governments -- and there is a word for that, and I need to introduce you to it now. The word for this sharing of power between state and national governments is federalism. +

Let's just pause here for a moment because this term "federalism" is an endless scourge 无尽的困扰 to AP Government students in all times and in all places. When your exam or your teacher or whatever asks you about federalism, you are going to be tempted 诱惑；引诱 -- oh, so tempted -- to believe that this is referring to the power of the federal government. I wouldn't blame you because that's what the word sounds like. And just like Jesus himself prayed for Peter that he might not fall into the temptation of the devil, I too pray that you would not fall into the temptation of believing such falsehoods 错误观念. +

Federalism is not about federal power. Federalism describes the sharing of power between national government and state government. That's it. Don't get confused 困惑. +

Now why am I laboring over 仔细阐述 this small detail 细节? It's because federalism is a very significant concept 重要概念 in this course, and if you don't understand what it's talking about, well... you burn （此处表示陷入困境）. +

Now, in order to understand the sharing of power, I need to introduce you to three terms which describe the relationship between state and national government power. First is exclusive powers 专有权力, which are powers delegated 授予；委派 by the Constitution to the federal government alone. For example, only the federal Congress can declare war 宣战 for the nation, and no state can do that -- because that would be kind of awkward 尴尬: +

*"Hey guys, Minnesota here. Just wanted to let you guys know that we just declared war with Canada. So..."*

Can't happen. Only the national government can declare war. +

Then there are the reserved powers 保留权力, and those are all the powers kept by the states. Now the justification 正当理由 for reserved powers comes in the 10th Amendment 第十修正案 to the Constitution, which reads: +

"The powers not delegated to the United States by the Constitution, nor prohibited by it to the states, are reserved to the states respectively, or to the people."

So if a power is not explicitly 明确地 given to the federal government and not prohibited 禁止 to the states, then that power belongs to the states. And over time, that's included things like policing 治安, hospitals, and education. +

And then there are concurrent powers 共同权力, which both national and state governments share. Taxation 税收 is an example of concurrent powers. And if you have a job where you get a paycheck 工资, you may have noticed that taxes are withheld 预扣 both for the federal government and your state government. +

Okay, so now that you understand what federalism is, we need to talk about how the sharing of that power shifts 转移 between the national government and the state government, and how the needs of society affect how that balance is struck 达成平衡 over time -- because it is not always the same. +

Now over the course of the last century, one of the most significant ways federalism has been manifested 体现；表现 is through something called fiscal federalism 财政联邦制 -- or federalism via dollars 通过资金实现的联邦制. And let me explain. So Congress can establish national standards 国家标准 and then direct funds 拨款 to states that comply with 遵守 those standards, and then withhold funding 扣留资金 from those who do not. And that happens in many ways through grants 拨款. +

The first kind of grant that illustrates 说明；阐明 fiscal federalism is called a categorical grant 专项拨款. These grants give federal money to the states as long as they comply with specific federal standards. In other words, if states accept that money, there are strings attached 有附加条件, and the state must use that money for the purpose and in the way that is stipulated 规定 by the federal government. +

For example, the first big step by the federal government into education was during the administration 执政；任期 of Lyndon B. Johnson. And remember, traditionally, education is the domain 领域 of the state. First came the Civil Rights Act of 1964, which -- among other things -- prohibited federal funds from being distributed 分配 to segregated schools 实行种族隔离的学校. Thus, if schools wanted federal money (which many of them desperately needed), they would have to comply with federal school integration laws 学校种族融合法律. +

Then came the Elementary and Secondary Education Act of 1965, which increased the federal government's control over public education by stipulating further requirements to be met if a school is going to receive federal dollars. So categorical grants were very much used to bring states into line with 使……一致 the federal education and civil rights agenda 教育和民权议程. +

Now as you can imagine, although many states gobbled up 大量接受 the money from these categorical grants, they weren't too happy with the growing power of the federal government. So in 1966, the first block grant 整笔拨款 was created, which was a move that returned some of the power back to the states. +

This kind of grant is like a categorical grant -- money given to the states by the federal government -- but in this case, there are far fewer strings attached. In the case of block grants, the federal government gives money to be spent in a broad category 广泛类别, but the states determine exactly how that money is to be spent within those boundaries 界限. +

So for example, Congress has established a Community Development Block Grant 社区发展整笔拨款 and gives that money to the states for the purpose of -- you know -- community development. But the states can decide exactly what kind of community development they want to do with that money. They can build sewage plants 污水处理厂 or redevelop abandoned homes 重建废弃房屋 or whatever. The point is, states like block grants a lot more than categorical grants because they have a lot more decision-making power 决策权 when it comes to spending the money. +

Okay, now another way fiscal federalism is played out 体现；展现 is through mandates 命令；指令. Mandates require states to follow federal directives 联邦指示, but in a lot of cases, the state's budget isn't nearly big enough to pay for such implementation 实施. So in this case, the federal government gives money toward the carrying out of 执行 these mandates. +

For example, when the Clean Air Act 清洁空气法案 was passed, it created national environmental standards 国家环境标准. So it put limits on the amount of carbon dioxide emissions 二氧化碳排放 that certain entities 实体 could emit 排放. And in order to comply with those standards, the states needed some boom-boom （此处表示资金等资源）to make it happen. So the federal government set the standards, and because of the Supremacy Clause 至上条款 in the Constitution, states were required to comply, and the feds gave money to the states in order to help them fall in line with 与……保持一致 the national standard. +

Now there is such a thing as an unfunded mandate 无资金支持的指令, and the states hate that worst of all. And it's exactly what it sounds like: The federal government sets the mandate and then provides no funds to help states comply. +

A good example of an unfunded mandate is the No Child Left Behind Act of 2001 2001年不让一个孩子掉队法案. It required states that received federal funding for education to give standardized tests 标准化考试 to students. And if those students were not improving year over year 逐年, then the law said that the schools must either hire or fire teachers or otherwise work to improve student scores on these tests. But -- and here's the kicker 关键；令人意外之处 -- it was the schools who had to pay for their improvement program 改进计划. +

So to put it mildly 委婉地说, this was not popular among the states. However, starting in the 1980s with Ronald Reagan's "devolution revolution" 权力下放革命 -- in which power was progressively 逐步地 returned to the states -- unfunded mandates became even more rare. And since that time, Congress has majored on 主要采用 block grants to give states more discretion 自由裁量权 on how to spend federal dollars. +

And then it was in 1995 that President Clinton signed the Unfunded Mandates Reform Act 无资金支持指令改革法案, which severely curtailed 大幅削减 the federal government's ability to issue 发布 unfunded mandates. +

So the point of all this is simple: Federalism is the sharing of power between state and national governments, and over time -- depending on the issues of the day -- that sharing of power has shifted back and forth 来回转移 between states and the federal government. +

Okay, that's what you need to know about Unit 1, Topic 7 of the AP Government curriculum. I wouldn't call it a mandate 命令；指令, but if you want help getting an A in your class and a 5 on your exam in May, then click right here and grab my review packet 复习资料包. If you want me to keep making these videos for you, then you can let me know that by subscribing 订阅. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒历史课。我们一直在学习AP政府课程的第一单元，在这个视频中，我们要谈谈联邦制。所以，如果你准备好开动脑筋获取知识，那我们就开始吧。 +

在这个视频中，我们要做到以下几点：解释社会需求如何影响国家政府与州政府之间权力的宪法分配。好的，国家政府和州政府之间的权力分配 —— 有一个专门的词来形容这个，现在我要给你介绍一下。州政府和国家政府之间的这种权力分享被称为联邦制（federalism）。 +

我们先在这里停一下，因为“联邦制”这个词对于各地的AP政府课程的学生来说，一直是个麻烦的概念。当你的考试或者你的老师等等问到你关于联邦制的问题时，你可能会忍不住 —— 非常想 —— 认为这个词指的是联邦政府的权力。我不会怪你，因为这个词听起来就是这样的。就像耶稣为彼得祈祷，让他不落入魔鬼的诱惑一样，我也祈祷你不要陷入这种错误的认知。 +

联邦制并不是关于联邦权力的。联邦制描述的是国家政府和州政府之间的权力分享。就是这样。不要搞混了。 +

那么我为什么要在这个小细节上费口舌呢？这是因为联邦制在本课程中是一个非常重要的概念，如果你不理解它的含义，嗯…… 你就麻烦了。 +

现在，为了理解权力分享，我要给你介绍三个术语，它们描述了州政府和国家政府权力之间的关系。首先是专有权力（exclusive powers），这是宪法仅赋予联邦政府的权力。例如，只有联邦国会（federal Congress）可以代表国家宣战，任何州都不能这么做 —— 因为那会很奇怪：

*“嘿，大家好，这里是明尼苏达州（Minnesota）。只是想告诉大家，我们刚刚向加拿大（Canada）宣战了。所以……”*

这种情况是不可能发生的。只有国家政府可以宣战。 +

然后是保留权力（reserved powers），这些是各州保留的所有权力。保留权力的依据来自宪法的第十修正案，其内容是：

“宪法未授予合众国、也未禁止各州行使的权力，由各州各自保留，或由人民保留。”

所以，如果一项权力没有明确授予联邦政府，也没有禁止各州行使，那么这项权力就属于各州。随着时间的推移，这些权力包括治安、医院和教育等方面。 +

接着是共享权力（concurrent powers），这是国家政府和州政府都拥有的权力。税收就是共享权力的一个例子。如果你有一份工作并能拿到薪水，你可能会注意到，税收既会交给联邦政府，也会交给州政府。 +

好的，现在你理解了联邦制是什么，我们需要谈谈这种权力分享在国家政府和州政府之间是如何变化的，以及社会需求如何影响这种权力平衡的达成 —— 因为这种平衡并非一成不变。 +

在过去的一个世纪里，联邦制最显著的体现方式之一是通过所谓的财政联邦制（fiscal federalism） —— 或者说是通过金钱来实现的联邦制。让我来解释一下。国会（Congress）可以制定国家标准，然后将资金导向遵守这些标准的州，而对不遵守的州则扣留资金。这通过多种方式以拨款的形式实现。 +

说明财政联邦制的第一种拨款被称为分类拨款（categorical grant）。这些拨款将联邦资金给予各州，条件是各州要遵守特定的联邦标准。换句话说，如果各州接受这笔资金，是有附加条件的，而且各州必须按照联邦政府规定的目的和方式使用这笔资金。 +

例如，联邦政府在林登·B·约翰逊（Lyndon B. Johnson）执政期间首次大规模涉足教育领域。记住，传统上，教育是州政府的职责范围。1964年的《民权法案》（the Civil Rights Act of 1964）规定，除其他事项外，禁止将联邦资金分配给实行种族隔离的学校。因此，如果学校想要联邦资金（很多学校都迫切需要），它们就必须遵守联邦的学校融合法律。 +

然后是1965年的《中小学教育法案》（the Elementary and Secondary Education Act of 1965），该法案通过规定如果学校要获得联邦资金就必须满足进一步的要求，增加了联邦政府对公共教育的控制。所以分类拨款在使各州与联邦的教育和民权议程保持一致方面被大量使用。 +

现在你可以想象，尽管许多州接受了这些分类拨款的资金，但它们对联邦政府权力的增长并不满意。所以在1966年，第一种整笔拨款（block grant）诞生了，这一举措将一些权力归还给了各州。 +

这种拨款类似于分类拨款 —— 即联邦政府给予各州的资金 —— 但在这种情况下，附加条件要少得多。对于整笔拨款，联邦政府给予资金用于一个广泛的类别，但各州可以决定在这些范围内如何确切地使用这笔资金。 +

例如，国会设立了社区发展整笔拨款（Community Development Block Grant），并将这笔资金给予各州用于社区发展。但各州可以决定用这笔钱进行何种社区发展。它们可以建造污水处理厂，或者重新开发废弃的房屋等等。关键是，各州更喜欢整笔拨款，因为在资金使用方面，它们拥有更多的决策权。 +

好的，财政联邦制的另一种体现方式是通过指令（mandates）。指令要求各州遵循联邦指示，但在很多情况下，州政府的预算根本不足以支付执行这些指示的费用。所以在这种情况下，联邦政府会提供资金来执行这些指令。 +

例如，《清洁空气法案》（the Clean Air Act）通过后，它制定了国家环境标准。所以它对某些实体的二氧化碳排放量进行了限制。为了遵守这些标准，各州需要一些资金来实现这一目标。所以联邦政府制定了标准，由于宪法中的最高权力条款（Supremacy Clause），各州必须遵守，并且联邦政府会给予各州资金，帮助它们符合国家标准。 +

还有一种情况是无资金支持的指令（unfunded mandate），各州最讨厌这种情况。它的意思就像其字面所表达的那样：联邦政府制定指令，但不提供资金帮助各州遵守。 +

无资金支持的指令的一个很好的例子是2001年的《不让一个孩子掉队法案》（the No Child Left Behind Act of 2001）。该法案要求接受联邦教育资金的各州对学生进行标准化测试。如果这些学生的成绩没有逐年提高，那么该法案规定，学校必须聘请或解雇教师，或者采取其他措施来提高学生在这些测试中的成绩。但是 —— 关键来了 —— 学校必须自己支付改进计划的费用。 +

所以委婉地说，各州并不喜欢这种情况。然而，从20世纪80年代罗纳德·里根（Ronald Reagan）的“权力下放革命”开始 —— 在这场革命中，权力逐渐归还给各州 —— 无资金支持的指令变得更加少见。从那时起，国会主要通过整笔拨款，给予各州在如何使用联邦资金方面更多的自由裁量权。 +

然后在1995年，克林顿总统签署了《无资金支持指令改革法案》（the Unfunded Mandates Reform Act），该法案严重限制了联邦政府发布无资金支持指令的能力。 +

所以所有这些的重点很简单：联邦制是国家政府和州政府之间的权力分享，随着时间的推移 —— 取决于当时的问题 —— 这种权力分享在各州和联邦政府之间来回转移。 +

好的，这就是AP政府课程第一单元第七个话题你需要知道的内容。我不会把这称为指令，但如果你需要帮助在课堂上得A并且在五月份的考试中得5分，那么点击这里获取我的复习资料包。如果你希望我继续为你制作这些视频，那么可以通过订阅来告诉我。海姆勒下线了。 +

'''

== pure

Hey there, and welcome back to Heimler's History. We've been going through Unit 1 of the AP Government curriculum, and in this video, it's time to talk about federalism. So if you're ready to get them brain cows milked well, then let's get to it.

So in this video, here's what we're trying to accomplish: Explain how societal needs affect the constitutional allocation of power between the national and state governments. Okay, so the allocation of power between national and state governments -- and there is a word for that, and I need to introduce you to it now. The word for this sharing of power between state and national governments is federalism.

Let's just pause here for a moment because this term "federalism" is an endless scourge to AP Government students in all times and in all places. When your exam or your teacher or whatever asks you about federalism, you are going to be tempted -- oh, so tempted -- to believe that this is referring to the power of the federal government. I wouldn't blame you because that's what the word sounds like. And just like Jesus himself prayed for Peter that he might not fall into the temptation of the devil, I too pray that you would not fall into the temptation of believing such falsehoods.

Federalism is not about federal power. Federalism describes the sharing of power between national government and state government. That's it. Don't get confused.

Now why am I laboring over this small detail? It's because federalism is a very significant concept in this course, and if you don't understand what it's talking about, well... you burn.

Now, in order to understand the sharing of power, I need to introduce you to three terms which describe the relationship between state and national government power. First is exclusive powers, which are powers delegated by the Constitution to the federal government alone. For example, only the federal Congress can declare war for the nation, and no state can do that -- because that would be kind of awkward:

*"Hey guys, Minnesota here. Just wanted to let you guys know that we just declared war with Canada. So..."*

Can't happen. Only the national government can declare war.

Then there are the reserved powers, and those are all the powers kept by the states. Now the justification for reserved powers comes in the 10th Amendment to the Constitution, which reads:

"The powers not delegated to the United States by the Constitution, nor prohibited by it to the states, are reserved to the states respectively, or to the people."

So if a power is not explicitly given to the federal government and not prohibited to the states, then that power belongs to the states. And over time, that's included things like policing, hospitals, and education.

And then there are concurrent powers, which both national and state governments share. Taxation is an example of concurrent powers. And if you have a job where you get a paycheck, you may have noticed that taxes are withheld both for the federal government and your state government.

Okay, so now that you understand what federalism is, we need to talk about how the sharing of that power shifts between the national government and the state government, and how the needs of society affect how that balance is struck over time -- because it is not always the same.

Now over the course of the last century, one of the most significant ways federalism has been manifested is through something called fiscal federalism -- or federalism via dollars. And let me explain. So Congress can establish national standards and then direct funds to states that comply with those standards, and then withhold funding from those who do not. And that happens in many ways through grants.

The first kind of grant that illustrates fiscal federalism is called a categorical grant. These grants give federal money to the states as long as they comply with specific federal standards. In other words, if states accept that money, there are strings attached, and the state must use that money for the purpose and in the way that is stipulated by the federal government.

For example, the first big step by the federal government into education was during the administration of Lyndon B. Johnson. And remember, traditionally, education is the domain of the state. First came the Civil Rights Act of 1964, which -- among other things -- prohibited federal funds from being distributed to segregated schools. Thus, if schools wanted federal money (which many of them desperately needed), they would have to comply with federal school integration laws.

Then came the Elementary and Secondary Education Act of 1965, which increased the federal government's control over public education by stipulating further requirements to be met if a school is going to receive federal dollars. So categorical grants were very much used to bring states into line with the federal education and civil rights agenda.

Now as you can imagine, although many states gobbled up the money from these categorical grants, they weren't too happy with the growing power of the federal government. So in 1966, the first block grant was created, which was a move that returned some of the power back to the states.

This kind of grant is like a categorical grant -- money given to the states by the federal government -- but in this case, there are far fewer strings attached. In the case of block grants, the federal government gives money to be spent in a broad category, but the states determine exactly how that money is to be spent within those boundaries.

So for example, Congress has established a Community Development Block Grant and gives that money to the states for the purpose of -- you know -- community development. But the states can decide exactly what kind of community development they want to do with that money. They can build sewage plants or redevelop abandoned homes or whatever. The point is, states like block grants a lot more than categorical grants because they have a lot more decision-making power when it comes to spending the money.

Okay, now another way fiscal federalism is played out is through mandates. Mandates require states to follow federal directives, but in a lot of cases, the state's budget isn't nearly big enough to pay for such implementation. So in this case, the federal government gives money toward the carrying out of these mandates.

For example, when the Clean Air Act was passed, it created national environmental standards. So it put limits on the amount of carbon dioxide emissions that certain entities could emit. And in order to comply with those standards, the states needed some boom-boom to make it happen. So the federal government set the standards, and because of the Supremacy Clause in the Constitution, states were required to comply, and the feds gave money to the states in order to help them fall in line with the national standard.

Now there is such a thing as an unfunded mandate, and the states hate that worst of all. And it's exactly what it sounds like: The federal government sets the mandate and then provides no funds to help states comply.

A good example of an unfunded mandate is the No Child Left Behind Act of 2001. It required states that received federal funding for education to give standardized tests to students. And if those students were not improving year over year, then the law said that the schools must either hire or fire teachers or otherwise work to improve student scores on these tests. But -- and here's the kicker -- it was the schools who had to pay for their improvement program.

So to put it mildly, this was not popular among the states. However, starting in the 1980s with Ronald Reagan's "devolution revolution" -- in which power was progressively returned to the states -- unfunded mandates became even more rare. And since that time, Congress has majored on block grants to give states more discretion on how to spend federal dollars.

And then it was in 1995 that President Clinton signed the Unfunded Mandates Reform Act, which severely curtailed the federal government's ability to issue unfunded mandates.

So the point of all this is simple: Federalism is the sharing of power between state and national governments, and over time -- depending on the issues of the day -- that sharing of power has shifted back and forth between states and the federal government.

Okay, that's what you need to know about Unit 1, Topic 7 of the AP Government curriculum. I wouldn't call it a mandate, but if you want help getting an A in your class and a 5 on your exam in May, then click right here and grab my review packet. If you want me to keep making these videos for you, then you can let me know that by subscribing. Heimler out.



'''

