
= 2 - Baker v Carr
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History. In this video, we're looking at another one of your required Supreme Court cases 最高法院案例 in the AP Government curriculum 课程, and that means it's time to look at Baker v. Carr. So if you're ready to get them brain cows milked, well then, let's get to it. +

Okay, first, as always, let's get the facts of the case. So this case was decided in 1962, and by that point, the state of Tennessee hadn't redrawn 重新划分 its legislative districts 立法选区 in over 60 years. In that time, Tennessee's urban populations 城市人口 had grown much faster than its rural populations 农村人口, and therefore, since the districts had not been redrawn to reflect those changes, rural voters 农村选民 had much more voting power 投票权 than did urban voters. +

Let me show you how that works using some basic numbers. If 100 people live in this urban district over here, and then five people live in this rural district over here, and both of them get one representative 代表 with one vote, then you can see that this group's vote counts for way more than this group's vote. +

So why had Tennessee been so negligent 疏忽的；粗心大意的 in their redistricting 重新划分选区? Well, the reasons are complicated, but one of the major reasons is that the Supreme Court had already decided that questions of redistricting were not justiciable 可由法院裁决的, which means that the court had no business ruling on such things. They argued that it was a political question, not a justice question. Snip snap, that's that, as nobody says. +

But in Baker v. Carr, that conclusion 结论 is going to change. So what was the constitutional principle 宪法原则 at stake 处于危险中 here? Well, it was the 14th Amendment 第十四修正案, and especially the Equal Protection Clause 平等保护条款. Remember that the 14th Amendment says that no state shall make or enforce any law which shall deny to any person within its jurisdiction 管辖范围 the equal protection of the laws. +

This amendment deals with state infringements 侵犯 upon liberty 自由, and the argument was that by refusing to redraw the districts and reapportion 重新分配 representatives, all citizens in Tennessee were patently 显然地 not equally protected under the law, and therefore, you bet your sweet bippy that this question is justiciable. +

Okay, so what was the decision? Well, first of all, I should probably tell you that this was an agonizing 痛苦的 decision for the court to make. In fact, biographers 传记作者 and historians argue that the stress of this case very much contributed to 导致 the poor health and ultimate demise 死亡 of one of the justices 法官. +

But regardless, the court decided that issues of reapportionment 重新分配 were in fact justiciable, and therefore, the Supreme Court did have authority 权力 to rule on questions of legislative reapportionment. +

Now, you're probably asking yourself why in the world this is such a big decision, and why did it kill a guy who was wrestling with it? Well, in order to answer that, let's talk about why this case matters. +

First of all, the case established the foundation of the one - person, one - vote doctrine 原则, in which states were required to apportion 分配 the representatives in a way that equally represented all the people, so that no votes counted any more than any other vote. +

Second, combined with several subsequent 随后的 decisions, Baker v. Carr fundamentally 根本地 altered 改变 the nature of political representation 政治代表制 across the United States. Following this decision, many states had to redraw their districts, and some of them more than once, in order to make sure that the rural votes were not more powerful than the urban votes. +

And third, this decision got the Supreme Court involved in an area where it had only been minimally 最低限度地；极少地 involved in the past -- namely, political questions like redistricting. That meant that there was a whole new set of questions that could potentially 可能地 be raised before the Supreme Court. +

However, I should mention that as a result of this decision, the court wasn't going to get involved in every political question. They established a six - part test 六项标准测试 in this decision that would help future justices decide when an issue before the court was only political in nature and thus should be avoided, and when an issue was justiciable and should thus be considered. +

Okay, that's what you need to know about Baker v. Carr. If you want more videos covering the required cases, then click right over here, and all your dreams will come true. If you want help getting an A in your class and a five on your exam, then click right here and grab the review packet. And finally, if this video helped you, and you want me to keep making them, then subscribe 订阅, and I shall oblige 答应. +

Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史课程。在这个视频中，我们要探讨美国大学预修课程（AP）政府课程中另一个最高法院的必学案例，也就是说，我们要研究 “贝克诉卡尔案”（Baker v. Carr）。所以，如果你准备好汲取知识，那么，我们开始吧。 +

好的，首先，和往常一样，让我们了解一下这个案件的事实。这个案件在1962年做出裁决，在那之前，田纳西州（Tennessee）已经六十多年没有重新划分立法选区了。在那段时间里，田纳西州的城市人口增长速度比农村人口快得多，因此，由于选区没有重新划分以反映这些变化，农村选民的投票权比城市选民的投票权大得多。 +

让我用一些基本数字给你展示一下这是怎么回事。如果这边这个城市选区有100人居住，而那边这个农村选区只有5人居住，并且他们都选出一名代表，每个代表有一票，那么你可以看到，这个（农村选区代表）的选票比这个（城市选区代表）的选票重要得多。 +

那么，为什么田纳西州在重新划分选区方面如此疏忽呢？嗯，原因很复杂，但其中一个主要原因是，最高法院已经判定选区重划问题不具有可诉性，这意味着法院无权对这类事情做出裁决。他们认为这是一个政治问题，而不是司法问题。很快地说，就是这样，虽然没人这么说。 +

但在 “贝克诉卡尔案” 中，这个结论将会改变。那么，这里涉及的宪法原则是什么呢？嗯，是第十四修正案（14th Amendment），特别是其中的平等保护条款（Equal Protection Clause）。记住，第十四修正案规定，任何州都不得制定或执行任何剥夺其管辖范围内任何人的平等法律保护的法律。 +

这个修正案处理的是州对自由的侵犯问题，并且有人认为，田纳西州拒绝重新划分选区和重新分配众议员名额，这显然使得该州的所有公民没有受到平等的法律保护，因此，可以肯定的是，这个问题是具有可诉性的。 +

好的，那么裁决是什么呢？嗯，首先，我可能应该告诉你，对法院来说，做出这个裁决是一件很痛苦的事情。事实上，传记作家和历史学家认为，这个案件带来的压力在很大程度上导致了一位大法官身体状况不佳并最终去世。 +

但不管怎样，法院判定，重新分配名额的问题实际上是具有可诉性的，因此，最高法院确实有权对立法选区重新分配的问题做出裁决。 +

现在，你可能在问自己，为什么这个裁决如此重要，为什么这个案件会导致一位大法官为此承受巨大压力呢？嗯，为了回答这个问题，让我们谈谈这个案件为什么重要。 +

首先，这个案件确立了 “一人一票” 原则（one-person, one-vote doctrine）的基础，根据这个原则，各州被要求以一种平等代表所有人民的方式来分配众议员名额，这样就不会有选票比其他选票更重要。 +

其次，与随后的几个裁决相结合，“贝克诉卡尔案” 从根本上改变了美国各地政治代表的性质。在这个裁决之后，许多州不得不重新划分选区，有些州甚至不止一次地重新划分，以确保农村选民的选票不会比城市选民的选票更有影响力。 +

第三，这个裁决使最高法院介入了一个它过去很少涉足的领域——也就是像选区重划这样的政治问题。这意味着有一整套新的问题可能会提交到最高法院。 +

然而，我应该提到，作为这个裁决的结果，法院并不会介入每一个政治问题。在这个裁决中，他们确立了一个由六个部分组成的测试标准，这个标准将帮助未来的大法官决定一个提交到法院的问题是否只是政治性的，从而应该被回避，以及一个问题是否具有可诉性，从而应该被考虑。 +

好的，这就是你需要了解的 “贝克诉卡尔案” 的相关内容。如果你想要更多涵盖必学案例的视频，那么点击这里，你所有的梦想都会实现。如果你想要在课堂上得A并且在考试中得5分，那么点击这里获取复习资料包。最后，如果这个视频对你有帮助，并且你希望我继续制作这样的视频，那么订阅吧，我会照做的。 +

海姆勒（Heimler）下线啦。 +

'''

== pure

Hey there, and welcome back to Heimler's History. In this video, we're looking at another one of your required Supreme Court cases in the AP Government curriculum, and that means it's time to look at Baker v. Carr. So if you're ready to get them brain cows milked, well then, let's get to it.

Okay, first, as always, let's get the facts of the case. So this case was decided in 1962, and by that point, the state of Tennessee hadn't redrawn its legislative districts in over 60 years. In that time, Tennessee's urban populations had grown much faster than its rural populations, and therefore, since the districts had not been redrawn to reflect those changes, rural voters had much more voting power than did urban voters.

Let me show you how that works using some basic numbers. If 100 people live in this urban district over here, and then five people live in this rural district over here, and both of them get one representative with one vote, then you can see that this group's vote counts for way more than this group's vote.

So why had Tennessee been so negligent in their redistricting? Well, the reasons are complicated, but one of the major reasons is that the Supreme Court had already decided that questions of redistricting were not justiciable, which means that the court had no business ruling on such things. They argued that it was a political question, not a justice question. Snip snap, that's that, as nobody says.

But in Baker v. Carr, that conclusion is going to change. So what was the constitutional principle at stake here? Well, it was the 14th Amendment, and especially the Equal Protection Clause. Remember that the 14th Amendment says that no state shall make or enforce any law which shall deny to any person within its jurisdiction the equal protection of the laws.

This amendment deals with state infringements upon liberty, and the argument was that by refusing to redraw the districts and reapportion representatives, all citizens in Tennessee were patently not equally protected under the law, and therefore, you bet your sweet bippy that this question is justiciable.

Okay, so what was the decision? Well, first of all, I should probably tell you that this was an agonizing decision for the court to make. In fact, biographers and historians argue that the stress of this case very much contributed to the poor health and ultimate demise of one of the justices.

But regardless, the court decided that issues of reapportionment were in fact justiciable, and therefore, the Supreme Court did have authority to rule on questions of legislative reapportionment.

Now, you're probably asking yourself why in the world this is such a big decision, and why did it kill a guy who was wrestling with it? Well, in order to answer that, let's talk about why this case matters.

First of all, the case established the foundation of the one-person, one-vote doctrine, in which states were required to apportion the representatives in a way that equally represented all the people, so that no votes counted any more than any other vote.

Second, combined with several subsequent decisions, Baker v. Carr fundamentally altered the nature of political representation across the United States. Following this decision, many states had to redraw their districts, and some of them more than once, in order to make sure that the rural votes were not more powerful than the urban votes.

And third, this decision got the Supreme Court involved in an area where it had only been minimally involved in the past -- namely, political questions like redistricting. That meant that there was a whole new set of questions that could potentially be raised before the Supreme Court.

However, I should mention that as a result of this decision, the court wasn't going to get involved in every political question. They established a six-part test in this decision that would help future justices decide when an issue before the court was only political in nature and thus should be avoided, and when an issue was justiciable and should thus be considered.

Okay, that's what you need to know about Baker v. Carr. If you want more videos covering the required cases, then click right over here, and all your dreams will come true. If you want help getting an A in your class and a five on your exam, then click right here and grab the review packet. And finally, if this video helped you, and you want me to keep making them, then subscribe, and I shall oblige.

Heimler out.

'''

