
= 2.06 Expansion of FEDERAL POWER
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there and welcome back to Heimlich History. In this video we're going to continue looking at unit 2 of the AP government curriculum 课程, specifically the expansion 扩张；扩大 of presidential 总统的 power over time. Since the time of Franklin Roosevelt, the power and role of the president has grown by roughly 13 or 14 metric butt loads, and we need to figure out how that happened and why. So if you're ready to get them brain cows milked, well then let's get to it. +

So in this video, here's our objective 目标；目的: explain how presidents have interpreted 解释；阐释 and justified 证明…有理；为…辩护 their use of formal 正式的 and informal 非正式的 powers. Now to begin, let me remind you of what I said in the last video about formal and informal powers of the executive 行政的 branch 部门. Formal powers are those powers granted 授予；同意 to the president explicitly 明确地 in article 2 of the constitution 宪法 -- things like the veto 否决权 or appointing 任命 federal judges 联邦法官. Informal powers are those powers that are not explicitly mentioned in the constitution but that the president exercises 行使；运用 nonetheless 尽管如此 -- things like bargaining 谈判；讨价还价 and persuasion 说服；劝说 and executive agreements 行政协定. +

Now all presidents have made use of their formal and informal powers, but over time the president has used more and more of both powers, and the end result has been a much more powerful executive than we had when the republic 共和国 began. Now let me remind you that this growth of power in the executive branch was one of the chief 主要的 fears that had anti-federalists pooping their broadcloth britches during the ratification 批准 debates of the constitution, and the answer to those fears was laid down by Alexander Hamilton in Federalist 70, which is one of your required documents. And here I'm just going to give you a summary 总结 -- if you want to look at this required document in more depth, I've got a whole video on it. +

Anyway, in Federalist 70, Hamilton argues for a single executive. Anti-federalists were arguing back that executive power needed to be divided among a few presidents so that the executive branch didn't become, in their own words, "the fetus of monarchy 君主制；君主政体." They were worried that if there was only one president, it would be far too likely that said president would consolidate 巩固；合并 too much power and become a tyrannical 专制的；暴虐的 turd. Not so, Hamilton argues. He says that a single executive is very much necessary, first because a single person can act more decisively 果断地 when required, second because a single executive will actually be a protection against the expansion of executive power, because if the president tries to grab at power, everybody knows exactly who to blame, and thus a single executive would be much more inclined 倾向于 to be careful with the power since they will be watched so closely. +

Now I happen to think that Hamilton's arguments are pretty sound 合理的；可靠的, but it's also true that presidential power has expanded significantly 显著地 over time, and that change largely has to do with how the president understands the role. We actually have illustrations 例证；说明 of two opposing 相反的 interpretations of the executive role, and the first is from president Teddy Roosevelt, who said this: "My view was that every executive officer, and above all every executive officer in high position, was the steward 管家；管理人 of the people, bound 受约束的 actively and affirmatively 肯定地 to do all he could for the people, and not to content himself with the negative merit of keeping his talents undamaged in a napkin. My belief was that it was not only his right but his duty to do anything that the needs of the nation demanded, unless such an action was forbidden 禁止 by the constitution or by the laws." In other words, Roosevelt is saying that the president ought to act on behalf of 代表 the people in every conceivable 可想象的 manner unless it is explicitly restricted 限制 by the constitution. +

The next president, William Howard Taft, had a different opinion of executive power. He said: "The true view of the executive functions is, as I conceive 认为；设想 it, that the president can exercise no power which cannot be fairly and reasonably traced to some specific grant of power or justly implied 暗示 and included within such express grant as proper and necessary to its exercise." In other words, Taft argued for a much more restricted 受限制的 understanding of executive power. Roosevelt said "do anything as long as it's not explicitly forbidden by the constitution," but Taft said "do nothing unless it is explicitly granted in the constitution." +

And over the course of American history, we can see how those two perspectives 观点；看法 were adopted 采纳；采用 by different presidents. Starting with George Washington, we can see that his conception 概念；观念 of executive power was basically to defer to 服从；听从 congress 国会, which was the people's branch. But then a huge shift 转变 in that role came with the presidency of Andrew Jackson. He believed himself to be the representative 代表 of the people, and therefore had a mandate 授权；命令 to carry out 执行 their will. Now think about that for just a second -- constitutionally 从宪法角度看, it's congress that represents the people's will, but Jackson took that mantle 职责；责任 upon himself. And you can see this change based solely on the number of vetoes 否决 enacted 颁布；制定法律 by Jackson. For comparison, Washington vetoed two bills 法案, John Adams zero, Thomas Jefferson zero, and then Jackson vetoed 12 bills. So Jackson certainly expanded executive power to match his conception of the role. +

Then executive power was further expanded under the administration 政府；管理 of Abraham Lincoln. Although he is generally forgiven 原谅 for that since, you know, he had a civil war 内战 to fight. He assumed 承担 executive powers to save the union 联邦 and to emancipate 解放 the enslaved 被奴役的 population of the confederacy 邦联. Additionally 此外, he suspended 暂停 the constitutional right of habeas corpus 人身保护令, which means that people could be arrested without a proper trial 审判. That's a heinous 极恶的；令人发指的 thing, but again, he's generally forgiven for it since, you know, civil war. But forgiven or not, Lincoln certainly expanded the power glove into which the presidential hand fits. +

But that glove would expand beyond all proportion 比例 in the administration of Franklin Roosevelt. Elected during the Great Depression 大萧条, Roosevelt made broad use of his executive powers in order to pass his New Deal 新政 legislation 立法 aimed at 旨在 rescuing Americans from their economic suffering. To this end, he was able to get scores of 大量的 New Deal policies passed. He created new agencies 机构, he spent butt loads of federal 联邦的 money to put people to work, and he made use of the veto more than any other president before him -- 635 times, to which I say "dang." Additionally, the man was elected no less than four times, breaking the two-term 两届的 tradition set by Washington, and he took his power so far that he tried to push out 排挤；逐出 supreme court 最高法院 judges who disagreed with him and replaced them with judges friendly to his policies. Now that didn't work, but he tried nonetheless. +

The thing is, despite Roosevelt being the poster boy 典型代表 for the anti-federalist fears of a tyrannical executive, he kind of proves Hamilton's point in Federalist 70. In the 1930s, the nation was in crisis 危机, and FDR came in and got to work quick, fast, and in a hurry to handle it. And whether you agree or disagree with Roosevelt's New Deal policies, nobody can disagree that he was an energetic 精力充沛的 executive. +

Now since FDR's presidency, presidential power has expanded and contracted 收缩 somewhat, but it has never gone back to the smaller scope 范围 of power that we had in a president like Washington. I think it's kind of funny how today Republicans and Democrats argue about how big or small the government should be. After FDR, the government was big -- full stop 到此为止, no equivocation 含糊其辞. What they're really arguing about today is whether there should be a smaller big government or a bigger big government. +

Anyway, despite this almost constant growth in the power of the presidential role, there are some checks 制约；限制 on that power that you should know. Just because the president has become more powerful doesn't mean the president is immune to 不受…影响 the checks and balances 制衡 of other branches. Case in point 例证；恰当的例子: president Donald Trump was impeached 弹劾 twice during his four years in office, joining the ranks of two other presidents who had been impeached -- Bill Clinton and Andrew Johnson. Now Trump was not removed from office, but the impeachments serve as a reminder that the president is not all-powerful. Additionally, another check you should know is that after Roosevelt's four terms in office, we ratified 批准 a new amendment 修正案, namely the 22nd amendment, which limited the president to two terms. +

Okay, that's what you need to know about unit two topic six of the AP government curriculum. You can click right here and grab review packet, which will help you get an A in your class and a five on your exam in May. I myself am invested with precisely zero executive power, but if you want me to keep making these videos, then you can let me know that by subscribing 订阅. Heimler out. +

'''

== 中文释义


嗨，欢迎回到“海姆勒历史”（Heimlich History）。在本视频中，我们将继续探讨美国大学预修课程（AP）政府课程的第二单元，特别是总统权力随时间的扩张。从富兰克林·罗斯福（Franklin Roosevelt）时代起，总统的权力和角色大致增长了13或14个数量级，我们需要弄清楚这是如何发生的以及为什么会发生。所以，如果你准备好汲取知识，那我们就开始吧。 +

在本视频中，我们的目标是：解释总统们是如何解释和证明他们对正式和非正式权力的使用是合理的。首先，让我提醒一下你们我在上一个视频中关于行政部门正式和非正式权力的内容。正式权力是指宪法第二条明确授予总统的权力，比如否决权或任命联邦法官的权力。非正式权力是指宪法中没有明确提及但总统仍在行使的权力，比如谈判、说服和行政协议等权力。 +

所有总统都利用了他们的正式和非正式权力，但随着时间的推移，总统对这两种权力的使用越来越多，最终结果是行政部门比共和国成立时强大得多。现在让我提醒你们，行政部门权力的增长是反联邦党人在宪法批准辩论期间极为担忧的问题之一，亚历山大·汉密尔顿（Alexander Hamilton）在《联邦党人文集》第70篇中对此做出了回应，这是你们需要阅读的文献之一。在此我只给你们一个总结——如果你们想更深入地了解这份必读文献，我有一个专门的视频讲解。 +

总之，在《联邦党人文集》第70篇中，汉密尔顿主张设立单一行政长官。反联邦党人反驳说，行政权力需要在几位总统之间分配，以免行政部门用他们的话说成为“君主制的雏形”。他们担心如果只有一位总统，这位总统很可能会巩固过多权力并成为一个专制的家伙。汉密尔顿认为并非如此。他说，单一行政长官是非常必要的，首先是因为一个人在必要时可以更果断地行动，其次是因为单一行政长官实际上会防止行政权力的扩张，因为如果总统试图夺权，每个人都清楚该指责谁，因此单一行政长官会更倾向于谨慎使用权力，因为他们会受到密切关注。 +

我碰巧认为汉密尔顿的论点相当合理，但总统权力随着时间的推移大幅扩张也是事实，而这种变化在很大程度上与总统如何理解其角色有关。实际上，我们有两种对行政角色相反解释的例子，第一个来自泰迪·罗斯福（Teddy Roosevelt）总统，他说：“我的观点是，每位行政官员，尤其是每位高级行政官员，都是人民的管家，有义务积极主动地为人民尽其所能，而不是满足于将自己的才能毫无损害地藏在餐巾里这种消极的优点。我相信，做国家需要的任何事情不仅是他的权利，也是他的责任，除非这种行动被宪法或法律禁止。”换句话说，罗斯福是在说，总统应该以各种可以想象的方式代表人民行事，除非受到宪法的明确限制。 +

下一任总统威廉·霍华德·塔夫脱（William Howard Taft）对行政权力有不同的看法。他说：“在我看来，对行政职能的正确看法是，总统不能行使任何无法公平合理地追溯到某些具体授权的权力，或者不能行使那些合理地隐含在这种明确授权中、对其行使是适当和必要的权力。”换句话说，塔夫脱主张对行政权力有更严格的理解。罗斯福说“只要宪法没有明确禁止，就可以做任何事情”，但塔夫脱说“除非宪法明确授予，否则什么都不做”。 +

在美国历史的进程中，我们可以看到不同总统是如何采纳这两种观点的。从乔治·华盛顿（George Washington）开始，我们可以看到他对行政权力的概念基本上是听从国会，因为国会是代表人民的部门。但随着安德鲁·杰克逊（Andrew Jackson）担任总统，这种角色发生了巨大转变。他认为自己是人民的代表，因此有责任执行人民的意愿。现在想一下——从宪法上讲，代表人民意愿的是国会，但杰克逊把这个责任揽到了自己身上。仅从杰克逊行使的否决权数量上，你就能看到这种变化。相比之下，华盛顿否决了两项法案，约翰·亚当斯（John Adams）零项，托马斯·杰斐逊（Thomas Jefferson）零项，而杰克逊否决了12项法案。所以杰克逊肯定是扩大了行政权力以符合他对总统角色的理解。 +

在亚伯拉罕·林肯（Abraham Lincoln）执政期间，行政权力进一步扩大。尽管人们通常原谅他这样做，因为他要打内战。他承担起行政权力以拯救联邦并解放邦联的奴隶人口。此外，他暂停了人身保护令这一宪法权利，这意味着人们可以在没有适当审判的情况下被逮捕。这是一件令人发指的事情，但同样，因为内战，人们通常原谅了他。但不管是否被原谅，林肯肯定是扩大了总统权力的范围。 +

但在富兰克林·罗斯福（Franklin Roosevelt）执政期间，这种权力范围的扩大会超出所有比例。罗斯福在大萧条时期当选，他广泛利用自己的行政权力来通过旨在将美国人从经济苦难中拯救出来的新政立法。为此，他设法使许多新政政策得以通过。他创建了新的机构，花费了大量联邦资金让人们就业，并且比他之前的任何总统都更多地使用否决权——635次，对此我只能说“哇”。此外，这个人当选了不少于四次，打破了华盛顿设定的两届任期传统，而且他将自己的权力运用到了极致，试图赶走与他意见不合的最高法院法官，并用对他的政策友好的法官取而代之。虽然这没有成功，但他还是尝试了。 +

问题是，尽管罗斯福是反联邦党人对专制行政长官恐惧的典型代表，但他在某种程度上证明了汉密尔顿在《联邦党人文集》第70篇中的观点。在20世纪30年代，国家处于危机之中，富兰克林·德拉诺·罗斯福（FDR）上任后迅速采取行动来应对。无论你是否同意罗斯福的新政政策，没有人能否认他是一位精力充沛的行政长官。 +

自富兰克林·德拉诺·罗斯福总统任期以来，总统权力有所扩张和收缩，但从未回到像华盛顿那样权力范围较小的状态。我觉得有趣的是，如今共和党人和民主党人争论政府应该多大或多小。在富兰克林·德拉诺·罗斯福之后，政府规模很大——句号，没有含糊其辞。他们现在真正争论的是应该有一个较小的大政府还是一个较大的大政府。 +

无论如何，尽管总统角色的权力几乎一直在增长，但你应该知道对这种权力也有一些制衡。仅仅因为总统变得更有权力并不意味着总统不受其他部门的制衡。例如：唐纳德·特朗普（Donald Trump）总统在其四年任期内被弹劾两次，加入了另外两位被弹劾总统的行列——比尔·克林顿（Bill Clinton）和安德鲁·约翰逊（Andrew Johnson）。现在特朗普没有被免职，但弹劾提醒人们总统并非全能。此外，你应该知道的另一个制衡是，在罗斯福四届任期之后，我们批准了一项新的修正案，即第22条修正案，该修正案将总统任期限制为两届。 +

好了，这就是你需要了解的美国大学预修课程（AP）政府课程第二单元第六个主题的内容。你可以点击这里获取复习资料，这将帮助你在课堂上得A，在五月的考试中得5分。我自己完全没有行政权力，但如果你希望我继续制作这些视频，那么你可以通过订阅来告诉我。海姆勒（Heimler）结束发言。 +

'''

== pure

hey there and welcome back to heimlich history. in this video we're going to continue looking at unit 2 of the ap government curriculum, specifically the expansion of presidential power over time. since the time of franklin roosevelt, the power and role of the president has grown by roughly 13 or 14 metric butt loads, and we need to figure out how that happened and why. so if you're ready to get them brain cows milked, well then let's get to it.

so in this video, here's our objective: explain how presidents have interpreted and justified their use of formal and informal powers. now to begin, let me remind you of what i said in the last video about formal and informal powers of the executive branch. formal powers are those powers granted to the president explicitly in article 2 of the constitution -- things like the veto or appointing federal judges. informal powers are those powers that are not explicitly mentioned in the constitution but that the president exercises nonetheless -- things like bargaining and persuasion and executive agreements.

now all presidents have made use of their formal and informal powers, but over time the president has used more and more of both powers, and the end result has been a much more powerful executive than we had when the republic began. now let me remind you that this growth of power in the executive branch was one of the chief fears that had anti-federalists pooping their broadcloth britches during the ratification debates of the constitution, and the answer to those fears was laid down by alexander hamilton in federalist 70, which is one of your required documents. and here i'm just going to give you a summary -- if you want to look at this required document in more depth, i've got a whole video on it.

anyway, in federalist 70, hamilton argues for a single executive. anti-federalists were arguing back that executive power needed to be divided among a few presidents so that the executive branch didn't become, in their own words, "the fetus of monarchy." they were worried that if there was only one president, it would be far too likely that said president would consolidate too much power and become a tyrannical turd. not so, hamilton argues. he says that a single executive is very much necessary, first because a single person can act more decisively when required, second because a single executive will actually be a protection against the expansion of executive power, because if the president tries to grab at power, everybody knows exactly who to blame, and thus a single executive would be much more inclined to be careful with the power since they will be watched so closely.

now i happen to think that hamilton's arguments are pretty sound, but it's also true that presidential power has expanded significantly over time, and that change largely has to do with how the president understands the role. we actually have illustrations of two opposing interpretations of the executive role, and the first is from president teddy roosevelt, who said this: "my view was that every executive officer, and above all every executive officer in high position, was the steward of the people, bound actively and affirmatively to do all he could for the people, and not to content himself with the negative merit of keeping his talents undamaged in a napkin. my belief was that it was not only his right but his duty to do anything that the needs of the nation demanded, unless such an action was forbidden by the constitution or by the laws." in other words, roosevelt is saying that the president ought to act on behalf of the people in every conceivable manner unless it is explicitly restricted by the constitution.

the next president, william howard taft, had a different opinion of executive power. he said: "the true view of the executive functions is, as i conceive it, that the president can exercise no power which cannot be fairly and reasonably traced to some specific grant of power or justly implied and included within such express grant as proper and necessary to its exercise." in other words, taft argued for a much more restricted understanding of executive power. roosevelt said "do anything as long as it's not explicitly forbidden by the constitution," but taft said "do nothing unless it is explicitly granted in the constitution."

and over the course of american history, we can see how those two perspectives were adopted by different presidents. starting with george washington, we can see that his conception of executive power was basically to defer to congress, which was the people's branch. but then a huge shift in that role came with the presidency of andrew jackson. he believed himself to be the representative of the people, and therefore had a mandate to carry out their will. now think about that for just a second -- constitutionally, it's congress that represents the people's will, but jackson took that mantle upon himself. and you can see this change based solely on the number of vetoes enacted by jackson. for comparison, washington vetoed two bills, john adams zero, thomas jefferson zero, and then jackson vetoed 12 bills. so jackson certainly expanded executive power to match his conception of the role.

then executive power was further expanded under the administration of abraham lincoln. although he is generally forgiven for that since, you know, he had a civil war to fight. he assumed executive powers to save the union and to emancipate the enslaved population of the confederacy. additionally, he suspended the constitutional right of habeas corpus, which means that people could be arrested without a proper trial. that's a heinous thing, but again, he's generally forgiven for it since, you know, civil war. but forgiven or not, lincoln certainly expanded the power glove into which the presidential hand fits.

but that glove would expand beyond all proportion in the administration of franklin roosevelt. elected during the great depression, roosevelt made broad use of his executive powers in order to pass his new deal legislation aimed at rescuing americans from their economic suffering. to this end, he was able to get scores of new deal policies passed. he created new agencies, he spent butt loads of federal money to put people to work, and he made use of the veto more than any other president before him -- 635 times, to which i say "dang." additionally, the man was elected no less than four times, breaking the two-term tradition set by washington, and he took his power so far that he tried to push out supreme court judges who disagreed with him and replaced them with judges friendly to his policies. now that didn't work, but he tried nonetheless.

the thing is, despite roosevelt being the poster boy for the anti-federalist fears of a tyrannical executive, he kind of proves hamilton's point in federalist 70. in the 1930s, the nation was in crisis, and fdr came in and got to work quick, fast, and in a hurry to handle it. and whether you agree or disagree with roosevelt's new deal policies, nobody can disagree that he was an energetic executive.

now since fdr's presidency, presidential power has expanded and contracted somewhat, but it has never gone back to the smaller scope of power that we had in a president like washington. i think it's kind of funny how today republicans and democrats argue about how big or small the government should be. after fdr, the government was big -- full stop, no equivocation. what they're really arguing about today is whether there should be a smaller big government or a bigger big government.

anyway, despite this almost constant growth in the power of the presidential role, there are some checks on that power that you should know. just because the president has become more powerful doesn't mean the president is immune to the checks and balances of other branches. case in point: president donald trump was impeached twice during his four years in office, joining the ranks of two other presidents who had been impeached -- bill clinton and andrew johnson. now trump was not removed from office, but the impeachments serve as a reminder that the president is not all-powerful. additionally, another check you should know is that after roosevelt's four terms in office, we ratified a new amendment, namely the 22nd amendment, which limited the president to two terms.

okay, that's what you need to know about unit two topic six of the ap government curriculum. you can click right here and grab review packet, which will help you get an a in your class and a five on your exam in may. i myself am invested with precisely zero executive power, but if you want me to keep making these videos, then you can let me know that by subscribing. heimler out.

'''

