
= 2.12 The Federal BUREAUCRACY
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there and welcome back to Heimler's History. Now we've been going through unit two of the AP government curriculum 课程, and that means it's time to talk about the federal bureaucracy 联邦官僚机构. So if you're ready to get them brain cows milked bureaucrat 官僚 style, then let's get to it. +

Okay, so in this video here's what we're trying to do: explain how the bureaucracy 官僚机构 carries out 执行 the responsibilities of the federal government. So let's begin in the beginning. What is the federal bureaucracy? Well, in addition to holding the title for the word I most frequently misspell in this curriculum, the bureaucracy consists of 由…组成 the millions of people who are employed to carry out the responsibilities of the federal government, and which falls under the authority of 受…管辖 the executive branch 行政部门. +

Remember, the executive branch of the government is there to enforce 执行 the laws passed by congress. In order to enforce those laws, it requires a metric butt load of 大量的 people. So in order to understand how the bureaucracy works, let's begin with its basic structure 基本结构. +

First, you've got the cabinet departments 内阁部门, of which there are 15. For example, you have the department of defense 国防部 and the department of education 教育部. We'll talk a lot more about those in the next video, but for now just know that all the folks that make up 组成 the president's cabinet are the heads of those departments. Now each of those departments are further subdivided into 细分为 agencies 机构, which all work together to accomplish 实现 the goals of the department. +

For example, the mission 使命 of the department of the treasury 财政部 is to "maintain a strong economy," and in order to get that done there are several agencies within that department that work to achieve that. For example, you have the internal revenue service 国内收入署, which is responsible for 负责 collecting taxes 收税 and deciding how and when that occurs, and you also have the united states mint 美国造币厂, which coins 铸造 and prints 印刷 all our money. +

Okay, then under the heading of bureaucracy we have independent regulatory commissions 独立监管委员会. They're independent because they operate somewhat apart from 与…有点不同 the president's authority, but they're still associated with 与…有关 the executive branch. And these commissions do what their names suggest -- they are created for the specific purpose of regulating 监管 some aspect of society. For example, we have the federal communications commission 联邦通信委员会, which is responsible (in addition to its many other responsibilities) for making sure potty mouth language 粗俗语言 doesn't end up on our television broadcast 电视广播. Thanks to the FCC, I could not go on television and say [Laughter], and I definitely could not talk about how... you know what I'm saying. +

Anyway, the final kind of bureaucratic entity 官僚实体 you should know about is the government corporation 政府公司. This is a kind of hybrid 混合体 between a government agency 政府机构 and a private business 私营企业. When there are services that the government wants to offer to the public, but the free market is the best way to do it, then a government corporation is created or acquired 获得. So the next time you go outside to check the mail, you can think about government corporations because one of the biggest of these is the U.S. Postal Service 美国邮政署. +

Okay, so that's the basic structure of the bureaucracy. Now let me briefly tell you about what these entities do in order to carry out the will of the executive branch. First, these organizations write and enforce regulations 制定并执行法规. For example, if you've ever seen closed captions 字幕 on a video or TV screen, that's because in the mid 90s the FCC made it a rule that closed captions be included for those with disabilities 残疾人. There are a few exceptions to the rule, but for the most part if you want to broadcast a show on TV and you don't include the closed captions, the FCC is going to get you. +

Which brings us to the next thing these organizations do, namely issue fines for non-compliance 对不遵守规定处以罚款. If you decide that the April 15th deadline for filing your taxes 报税截止日期 just doesn't appeal to you, then maybe the IRS is going to slap a fine on you quick, fast, and in a hurry. Or another example, if businesses don't abide by 遵守 the provisions 条款 of the Clean Air Act 清洁空气法案 and pollute the environment to their little hearts' content 随心所欲地污染环境, well the Environmental Protection Agency 环境保护署 is about to hit them with a fine. And that's what's known as compliance monitoring 合规监测. +

Now the third thing these bureaucratic organizations do is interact with 与…互动 congress. The department heads are often experts in their field, and they'll go to congressional committees 国会委员会 and testify 作证 on behalf of 代表 the dealings 事务 of that agency or their department. Now these bureaucratic agencies often work very closely with congressional committees and interest groups 利益集团, and when they do so, this relationship is called an iron triangle 铁三角. +

These three entities work together and rely on 依赖 one another's strength in order to make policy 制定政策. Bureaucrats 官僚 offer expertise 专业知识 to congressional committees with whom they are eager to cooperate, since it's congress who approves funding for their department. Committee members want to pay attention to interest groups because they often have policy experts who can inform them of the implications 影响 of certain policies. And interest groups can provide funding for congressional races 国会竞选. And if interest groups help these congress people get elected, then they will likely provide funding for a bureaucratic agency that will address the interests of the interest group. And on around the triangle we go. +

Now these days, iron triangles aren't as prevalent 普遍的 as they have been in the past, and that's partly because the number of competing interest groups have multiplied 增加 dramatically 显著地. Another reason is the prevalence of issue networks 问题网络, which have worked to weaken iron triangles. So for example, an iron triangle that formed around tobacco interest 烟草利益相关的铁三角 could be severely disrupted 严重破坏 by an issue network, which is a conglomeration 聚合体 of a bunch of folks who sometimes disagree about a lot of things, but they come together around one specific issue and seek to effect change 实现变革. If one of these issue networks is alarmed that so many Americans are using tobacco, then they have influence to break the triangle. +

Okay, we done got ourselves into the weeds of how the bureaucracy works, and now we need to finish by talking about how the efficiency 效率 of the bureaucracy has changed over time. And really this has to do with 与…有关 how people come to work in the bureaucracy. Back in the days of Andrew Jackson, getting a job in the bureaucracy was the result of something called the spoils system 分赃制. You know that saying "to the winner goes the spoils"? Well that's the idea of the spoils system. In Jackson's day, when the president won an election, that meant that he had hundreds of bureaucratic jobs to fill, and so he would give them to those who were not necessarily qualified for the jobs, but rather those who supported his candidacy 候选人资格. +

As you can imagine, such a system can go sideways 出问题 pretty quickly, as it did in 1881 in the assassination of President James Garfield. Just like every president before him, Garfield began his term by hearing from thousands of applicants for bureaucratic jobs -- people who had helped him get elected. And there were way more people applying than there were jobs to give out, so some people had to be told no. Well as it turns out, he told one particular guy named Charles Guiteau "no job for you," and in response, Guiteau found Garfield at a train station and went ahead and shot him. +

So that event created the occasion for reform in the way people got bureaucratic jobs, and the word for that is civil service reform 公务员制度改革. The result was the Pendleton Civil Service Act of 1883 1883年彭德尔顿公务员法, which created a merit-based system 基于功绩的制度 for applicants seeking jobs in the bureaucracy. Now jobs went to the people who were actually qualified for them, rather than people who just supported the candidate. So you know, good updates, and it helped increase the effectiveness 效力 of the bureaucracy since competent 有能力的 people were now working these jobs. +

All right, click right over here to grab review packet if you need help getting an A in your class and a five on your exam in May. That was everything you need to know about unit 2 topic 12 of the AP government curriculum, and I've got a lot more videos coming, so if you're not already subscribed, we'll go ahead and hop on that pony and click it, and I'll see in the next one. Heimler out. +

I don't know what that means -- "hop on that pony and click it" -- what is that?  +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史课程。我们一直在学习美国大学预修课程（AP）政府课程的第二单元，这意味着是时候谈谈联邦官僚机构了。所以，如果你准备好以官僚的风格汲取知识，那我们就开始吧。 +

好的，在这个视频中，我们要做的是：解释官僚机构是如何履行联邦政府的职责的。那我们从头开始。什么是联邦官僚机构呢？嗯，除了是我在这门课程中最常拼错的词之外，官僚机构由数百万受雇来履行联邦政府职责的人组成，并且它隶属于行政部门。 +

记住，政府的行政部门的职责是执行国会通过的法律。为了执行这些法律，需要大量的人员。所以，为了理解官僚机构是如何运作的，我们从它的基本结构开始讲起。 +

首先，有内阁部门，一共有15个。例如，有国防部（Department of Defense）和教育部（Department of Education）。我们将在下一个视频中更多地谈论这些部门，但现在只要知道，组成总统内阁的所有人都是这些部门的负责人。每个部门又进一步细分为各个机构，这些机构共同协作以实现部门的目标。 +

例如，财政部（Department of the treasury）的使命是 “维持强劲的经济”，为了实现这一目标，该部门内有几个机构为此努力。例如，有国税局（Internal Revenue Service），它负责收税并决定如何以及何时收税，还有美国铸币局（United States mint），它铸造和印制我们所有的货币。 +

好的，在官僚机构的范畴内，还有独立监管委员会。它们之所以独立，是因为它们在一定程度上独立于总统的权力运作，但它们仍然与行政部门相关联。这些委员会做着它们名字所暗示的事情——它们的设立是为了监管社会的某些方面。例如，有联邦通信委员会（Federal Communications Commission），它除了有许多其他职责外，还负责确保粗俗的语言不会出现在我们的电视广播中。多亏了联邦通信委员会，我不能在电视上说（笑声），而且我肯定不能谈论…… 你懂我的意思。 +

不管怎样，你应该了解的最后一种官僚实体是政府公司。这是一种介于政府机构和私人企业之间的组织。当政府想要向公众提供某些服务，而自由市场是提供这些服务的最佳方式时，就会创建或收购一家政府公司。所以，下次你出去查看邮件时，可以想想政府公司，因为美国邮政服务（U.S. Postal Service）就是其中最大的政府公司之一。 +

好的，这就是官僚机构的基本结构。现在让我简要地告诉你这些实体是如何执行行政部门的意愿的。首先，这些组织制定并执行规定。例如，如果你在视频或电视屏幕上看到过字幕，那是因为在90年代中期，联邦通信委员会规定要为残障人士提供字幕。这个规定有一些例外情况，但在大多数情况下，如果你想在电视上播放一个节目却不包含字幕，联邦通信委员会会找你麻烦。 +

这就引出了这些组织做的下一件事，即对不遵守规定的行为处以罚款。如果你觉得4月15日提交纳税申报单的截止日期对你没有约束力，那么国税局可能会迅速地对你处以罚款。再举个例子，如果企业不遵守《清洁空气法案》的规定，随心所欲地污染环境，那么环境保护署（Environmental Protection Agency）会对它们处以罚款。这就是所谓的合规监测。 +

这些官僚组织做的第三件事是与国会互动。部门负责人通常是各自领域的专家，他们会去国会委员会作证，代表他们的机构或部门进行事务陈述。这些官僚机构经常与国会委员会和利益集团密切合作，当他们这样做时，这种关系被称为 “铁三角”。 +

这三个实体共同协作，相互依赖各自的力量来制定政策。官僚们向渴望合作的国会委员会提供专业知识，因为是国会批准对他们部门的拨款。委员会成员会关注利益集团，因为利益集团通常有政策专家，这些专家可以告知他们某些政策的影响。利益集团可以为国会议员的竞选提供资金。如果利益集团帮助这些国会议员当选，那么他们可能会为一个能满足利益集团利益的官僚机构提供资金。然后就形成了这样一个循环。 +

如今，铁三角不像过去那么普遍了，部分原因是相互竞争的利益集团数量急剧增加。另一个原因是议题网络的盛行，议题网络削弱了铁三角。例如，围绕烟草利益形成的铁三角可能会被一个议题网络严重扰乱，议题网络是一群人的集合，他们有时在很多事情上存在分歧，但他们围绕一个特定的议题团结起来并寻求改变。如果其中一个议题网络对这么多美国人使用烟草感到担忧，那么他们有影响力打破这个铁三角。 +

好的，我们已经深入探讨了官僚机构是如何运作的，现在我们需要谈谈官僚机构的效率是如何随着时间变化的，以此来结束这个内容。这实际上与人们如何进入官僚机构工作有关。在安德鲁·杰克逊（Andrew Jackson）时代，在官僚机构中获得一份工作是所谓 “分赃制” 的结果。你知道那句 “战利品属于胜利者” 的说法吧？嗯，这就是分赃制的理念。在杰克逊时代，当总统赢得选举时，这意味着他有数百个官僚职位需要填补，所以他会把这些职位给那些不一定有资格任职的人，而是给那些支持他竞选的人。 +

你可以想象，这样的制度很快就会出问题，就像1881年詹姆斯·加菲尔德（James Garfield）总统遇刺事件那样。就像在他之前的每一位总统一样，加菲尔德在任期开始时听取了数千名申请官僚职位的人的意见——这些人是帮助他当选的人。申请的人远远多于可提供的职位，所以有些人会被告知得不到工作。结果，他对一个叫查尔斯·吉托（Charles Guiteau）的人说 “你没有工作机会”，作为回应，吉托在火车站找到了加菲尔德并开枪射杀了他。 +

所以这件事为人们获得官僚职位的方式带来了改革契机，这个改革被称为公务员制度改革。其结果是1883年的《彭德尔顿公务员法》（Pendleton Civil Service Act），该法案为申请官僚机构职位的人建立了一个基于功绩的制度。现在，工作会给那些真正有资格的人，而不是那些仅仅支持候选人的人。所以，这是很好的改进，而且由于有能力的人在这些岗位上工作，这有助于提高官僚机构的效率。 +

好的，如果你想在课堂上得A，在五月份的考试中得5分，点击这里获取复习资料包。这就是你需要了解的美国大学预修课程（AP）政府课程第二单元第12个主题的所有内容，我还有很多视频要发布，所以如果你还没有订阅，那就行动起来点击订阅吧，我们下一个视频再见。海姆勒（Heimler）结束发言。 +

我不知道 “hop on that pony and click it” 是什么意思——这是什么呢？ +

'''

== pure

hey there and welcome back to heimlich's history. now we've been going through unit two of the ap government curriculum, and that means it's time to talk about the federal bureaucracy. so if you're ready to get them brain cows milked bureaucrat style, then let's get to it.

okay, so in this video here's what we're trying to do: explain how the bureaucracy carries out the responsibilities of the federal government. so let's begin in the beginning. what is the federal bureaucracy? well, in addition to holding the title for the word i most frequently misspell in this curriculum, the bureaucracy consists of the millions of people who are employed to carry out the responsibilities of the federal government, and which falls under the authority of the executive branch.

remember, the executive branch of the government is there to enforce the laws passed by congress. in order to enforce those laws, it requires a metric butt load of people. so in order to understand how the bureaucracy works, let's begin with its basic structure.

first, you've got the cabinet departments, of which there are 15. for example, you have the department of defense and the department of education. we'll talk a lot more about those in the next video, but for now just know that all the folks that make up the president's cabinet are the heads of those departments. now each of those departments are further subdivided into agencies, which all work together to accomplish the goals of the department.

for example, the mission of the department of the treasury is to "maintain a strong economy," and in order to get that done there are several agencies within that department that work to achieve that. for example, you have the internal revenue service, which is responsible for collecting taxes and deciding how and when that occurs, and you also have the united states mint, which coins and prints all our money.

okay, then under the heading of bureaucracy we have independent regulatory commissions. they're independent because they operate somewhat apart from the president's authority, but they're still associated with the executive branch. and these commissions do what their names suggest -- they are created for the specific purpose of regulating some aspect of society. for example, we have the federal communications commission, which is responsible (in addition to its many other responsibilities) for making sure potty mouth language doesn't end up on our television broadcast. thanks to the fcc, i could not go on television and say [Laughter], and i definitely could not talk about how... you know what i'm saying.

anyway, the final kind of bureaucratic entity you should know about is the government corporation. this is a kind of hybrid between a government agency and a private business. when there are services that the government wants to offer to the public, but the free market is the best way to do it, then a government corporation is created or acquired. so the next time you go outside to check the mail, you can think about government corporations because one of the biggest of these is the u.s. postal service.

okay, so that's the basic structure of the bureaucracy. now let me briefly tell you about what these entities do in order to carry out the will of the executive branch. first, these organizations write and enforce regulations. for example, if you've ever seen closed captions on a video or tv screen, that's because in the mid 90s the fcc made it a rule that closed captions be included for those with disabilities. there are a few exceptions to the rule, but for the most part if you want to broadcast a show on tv and you don't include the closed captions, the fcc is going to get you.

which brings us to the next thing these organizations do, namely issue fines for non-compliance. if you decide that the april 15th deadline for filing your taxes just doesn't appeal to you, then maybe the irs is going to slap a fine on you quick, fast, and in a hurry. or another example, if businesses don't abide by the provisions of the clean air act and pollute the environment to their little hearts' content, well the environmental protection agency is about to hit them with a fine. and that's what's known as compliance monitoring.

now the third thing these bureaucratic organizations do is interact with congress. the department heads are often experts in their field, and they'll go to congressional committees and testify on behalf of the dealings of that agency or their department. now these bureaucratic agencies often work very closely with congressional committees and interest groups, and when they do so, this relationship is called an iron triangle.

these three entities work together and rely on one another's strength in order to make policy. bureaucrats offer expertise to congressional committees with whom they are eager to cooperate, since its congress who approves funding for their department. committee members want to pay attention to interest groups because they often have policy experts who can inform them of the implications of certain policies. and interest groups can provide funding for congressional races. and if interest groups help these congress people get elected, then they will likely provide funding for a bureaucratic agency that will address the interests of the interest group. and on around the triangle we go.

now these days, iron triangles aren't as prevalent as they have been in the past, and that's partly because the number of competing interest groups have multiplied dramatically. another reason is the prevalence of issue networks, which have worked to weaken iron triangles. so for example, an iron triangle that formed around tobacco interest could be severely disrupted by an issue network, which is a conglomeration of a bunch of folks who sometimes disagree about a lot of things, but they come together around one specific issue and seek to effect change. if one of these issue networks is alarmed that so many americans are using tobacco, then they have influence to break the triangle.

okay, we done got ourselves into the weeds of how the bureaucracy works, and now we need to finish by talking about how the efficiency of the bureaucracy has changed over time. and really this has to do with how people come to work in the bureaucracy. back in the days of andrew jackson, getting a job in the bureaucracy was the result of something called the spoils system. you know that saying "to the winner goes the spoils"? well that's the idea of the spoils system. in jackson's day, when the president won an election, that meant that he had hundreds of bureaucratic jobs to fill, and so he would give them to those who were not necessarily qualified for the jobs, but rather those who supported his candidacy.

as you can imagine, such a system can go sideways pretty quickly, as it did in 1881 in the assassination of president james garfield. just like every president before him, garfield began his term by hearing from thousands of applicants for bureaucratic jobs -- people who had helped him get elected. and there were way more people applying than there were jobs to give out, so some people had to be told no. well as it turns out, he told one particular guy named charles guiteau "no job for you," and in response, guiteau found garfield at a train station and went ahead and shot him.

so that event created the occasion for reform in the way people got bureaucratic jobs, and the word for that is civil service reform. the result was the pendleton civil service act of 1883, which created a merit-based system for applicants seeking jobs in the bureaucracy. now jobs went to the people who were actually qualified for them, rather than people who just supported the candidate. so you know, good updates, and it helped increase the effectiveness of the bureaucracy since competent people were now working these jobs.

now that reform continued into the 20th century in order to make the bureaucracy more professional and specialized and neutral. under jimmy carter's administration, congress passed the civil service reform act of 1978, which upheld the merit-based system already in place, but also further expanded opportunities for women to work in the bureaucracy and increase the efficiency of many departments.

all right, click right over here to grab review packet if you need help getting an a in your class and a five on your exam in may. that was everything you need to know about unit 2 topic 12 of the ap government curriculum, and i've got a lot more videos coming, so if you're not already subscribed, we'll go ahead and hop on that pony and click it, and i'll see in the next one. heimler out.

i don't know what that means -- "hop on that pony and click it" -- what is that?

'''

