
= 3 - Letter from a BIRMINGHAM JAIL
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History. In this video, we're going to consider another one of your required 必修的 foundational documents 基本文献 for the AP Government curriculum 课程大纲, namely Martin Luther King Jr.'s Letter from a Birmingham Jail. So if you're ready to get them brain cows milked（幽默说法：开动脑筋）, then let's get to it. +

So there are about 9,000 things I could say about this document, but for our purposes, the AP Government overlords 统治者；主宰（幽默或讽刺地指教育系统） just want you to understand this document as an illustration 说明，示例 of how the Equal Protection Clause 平等保护条款 of the 14th Amendment supported and motivated social movements 社会运动. The social movement in question here was the civil rights movement 民权运动 for the equality 平等 of black Americans in the 1950s and 1960s. One of the key leaders 主要领导人 of this movement was the Reverend Martin Luther King Jr., whose way of fighting for civil rights was altogether 完全地；总共 different. He taught a means of agitation 抗议；鼓动 defined by non-violent direct action 非暴力直接行动. That means the devotees 忠实信徒 of the civil rights movement would have to endure 忍受 suffering and imprisonment as they protested at segregated 种族隔离的 encounters 场所 for white people only. And he did this precisely because many state governments were failing to uphold the rights of black Americans under the Due Process Clause 正当法律程序条款 of the 14th Amendment. +

So in 1963, King led a campaign to desegregate 取消种族隔离 Birmingham, Alabama's downtown shopping district, and he did so with a series of boycotts 抵制, sit-ins 静坐抗议 and marches 游行. Long story short, the campaign got King and hundreds more arrested. In the midst of all that, a group of white clergy 神职人员 who were generally sympathetic to the cause of civil rights published an open letter 公开信 in the newspaper saying that such disruptive practices were not effective, and that black people in Birmingham needed to be patient 耐心的 and wait for the white folks to work through the courts and legislatures, and then they will have their rights. The Letter from a Birmingham Jail is King's response to their admonition 劝告，警告. +

And he opens by explaining why he's in Birmingham since he himself lived in Atlanta: "I am cognizant 知晓的；意识到的 of the interrelatedness 相互关联 of all communities and states. I cannot sit idly 无动于衷地；闲坐地 by in Atlanta and not be concerned about what happens in Birmingham. Injustice 不公 anywhere is a threat to justice everywhere. We are caught in an inescapable 无法逃避的 network of mutuality 相互关系, tied in a single garment 衣袍 of destiny 命运." +

He then goes on to justify 辩解；证明有理 the non-violent direct action that he and his followers had engaged in — like it wasn't thrown together at the last minute. He says it had been meticulously 一丝不苟地 planned, and the participants had been trained and prepared for the likely possibility of violence 暴力 and brutality 残忍. And the purpose of the movement in Birmingham was as follows: "Non-violent direct action seeks to create such a crisis 危机 and establish such creative tension 有建设性的紧张氛围 that a community that has consistently refused to negotiate 谈判 is forced to confront the issue. It seeks so to dramatize 戏剧化处理；突出 the issue that it can no longer be ignored." In other words, meaningful negotiation will never occur unless a crisis raises the stakes 利益；风险. +

And why do the stakes need upping? "We know through painful experience that freedom is never voluntarily 自愿地 given by the oppressor 压迫者. It must be demanded 要求 by the oppressed 被压迫者." And therefore the admonition 忠告 from the white clergy for King and his followers to be patient and wait could never be a reality for them. King says: "For years now I have heard the word 'wait.' It rings in the ear（习语）萦绕耳边 of every Negro with a piercing 刺耳的；深切的 familiarity 熟悉感. This 'wait' has almost always meant 'never.' It has been a tranquilizing 镇静的 thalidomide 沙利度胺（一种药物） relieving the emotional stress for a moment only to give birth to an ill-formed infant of frustration. We must come to see with the distinguished jurist 法学家 of yesterday that justice too long delayed 被拖延 is justice denied 被剥夺. We have waited for more than 340 years for our God-given and constitutional rights." +

So that's how King makes the case for the urgency 紧迫性 of their actions at the present moment. Like for him, the only way someone could rightly ask them to wait is because they themselves had never been on the receiving end of the humiliation 屈辱 and discrimination 歧视 in racial segregation. No, the time for them to act was at hand 迫在眉睫. +

And then he goes on to express his disappointment 失望 in the white clergy of Birmingham — not for their racism but for their moderation 温和；中庸. And buckle your seatbelts because this is astonishing 惊人的: "I must confess 承认 that over the last few years I have been gravely seriously 失望 with the white moderate 温和派. I've almost reached the regrettable conclusion that the Negro's great stumbling block 绊脚石 in the stride toward freedom is not the White Citizens' Counciler or the Ku Klux Klanner, but the white moderate who is more devoted to order 秩序 than to justice 正义." He says at least with the Ku Klux Klan, black people understood their intentions 意图 — they were clear. But for the white moderates who urged caution and restraint 克制 on black people because their actions would too much disrupt society, King had no patience: "We will have to repent 忏悔 in this generation not merely for the vitriolic 刻薄的；恶毒的 words and actions of the bad people but for the appalling 骇人的 silence 沉默 of the good people. We must come to see that human progress never rolls in on wheels of inevitability 必然性. It comes through the tireless 不知疲倦的 efforts and persistent 坚持不懈的 work of men willing to be co-workers with God." +

And so in light of that, King argues that their cause is a righteous 正义的 one. Now these white clergy also called King an extremist 极端分子, and he gladly embraces that moniker 名称. After all, he says, wasn't Jesus an extremist for love? And wasn't the Apostle Paul an extremist for the gospel? Wasn't Socrates an extremist for truth? And all of these men were martyred 为信仰或正义牺牲 for their extremism. And if King stood in a line of extremists like that, he was just fine with it. +

And so to end the letter, he brings the cause of civil rights for black Americans into the clouds and makes it shine until its brightness covers all: "Abused 受辱 and scorned 受轻视 though we may be, our destiny 命运 is tied up with the destiny of America. Before the pilgrims 清教徒 landed at Plymouth, we were here. Before the pen of Jefferson scratched across the pages of history the majestic 雄伟的 word of the Declaration of Independence, we were here. For more than two centuries, our foreparents 祖先 labored here without wages. They made cotton king, and they built the homes of their masters in the midst of brutal injustice and shameful humiliation. And yet out of a bottomless vitality 活力, our people continue to thrive and develop. If the inexpressible cruelties of slavery could not stop us, the opposition we now face will surely fail. We will win our freedom because the sacred heritage of our nation and the eternal will of God are embodied in our echoing demands." +

Okay, that's what you need to know about MLK's Letter from a Birmingham Jail. And you can click right here to grab my review packet 复习资料包 for AP Government, which is going to help you get an A in your class and a five on your exam in May. And if this video helped you, you can click right here and check out all my other videos on the other required documents. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史课程。在这个视频中，我们将探讨美国大学预修课程（AP）政府课程的另一份必学基础文件，即小马丁·路德·金（Martin Luther King Jr.）的《伯明翰监狱来信》（Letter from a Birmingham Jail）。所以，如果你准备好汲取知识，那么我们开始吧。 +

关于这份文件，我能说的内容大概有九千点之多，但就我们的学习目的而言，美国大学预修课程（AP）政府课程的主导要求是让你把这份文件理解为第十四修正案（14th Amendment）的平等保护条款支持并推动社会运动的一个例证。这里所讨论的社会运动是20世纪50年代和60年代为争取美国黑人平等权利的民权运动。这场运动的关键领导人之一是小马丁·路德·金牧师（Reverend Martin Luther King Jr.），他争取民权的方式截然不同。他倡导通过非暴力直接行动来进行鼓动。这意味着民权运动的追随者在抗议种族隔离（只针对白人的情况）时，必须忍受苦难和监禁。他这么做正是因为许多州政府未能依据第十四修正案的正当程序条款（Due Process Clause）维护美国黑人的权利。 +

所以在1963年，金领导了一场使阿拉巴马州（Alabama）伯明翰（Birmingham）市中心购物区取消种族隔离的运动，他通过一系列的抵制、静坐和游行来开展这场运动。长话短说，这场运动导致金和数百人被捕。在这一切发生的过程中，一群大体上同情民权事业的白人神职人员在报纸上发表了一封公开信，信中称这种具有破坏性的做法是无效的，并且伯明翰的黑人需要耐心等待白人通过法院和立法机构来解决问题，然后他们才能拥有自己的权利。《伯明翰监狱来信》就是金对他们的告诫的回应。 +

他在信的开头解释了自己住在亚特兰大（Atlanta）却来到伯明翰的原因：“我深知所有社区和州之间的相互关联。我不能在亚特兰大袖手旁观，而不关心伯明翰发生的事情。任何地方的不公正都是对所有地方公正的威胁。我们陷入了一张无法逃避的相互依存的网络，被系在命运的单一外衣上。” +

然后他接着为自己和追随者所进行的非暴力直接行动辩护——这可不是在最后一刻才仓促进行的。他说，这是经过精心策划的，参与者接受了训练，并为可能出现的暴力和野蛮行为做好了准备。伯明翰运动的目的如下：“非暴力直接行动旨在制造这样一场危机，并建立起创造性的紧张局势，迫使一直拒绝谈判的社区面对这个问题。它试图把这个问题戏剧化，使其再也无法被忽视。” 换句话说，除非危机提高了赌注，否则有意义的谈判永远不会发生。 +

为什么需要提高赌注呢？“我们通过痛苦的经历知道，自由永远不会被压迫者自愿给予。它必须由被压迫者去争取。” 因此，白人神职人员要求金和他的追随者耐心等待的告诫对他们来说永远不会成为现实。金说：“多年来，我一直听到‘等待’这个词。这个词在每个黑人耳边都无比熟悉且刺耳。这个‘等待’几乎总是意味着‘永远不会’。它就像一种镇静剂，暂时缓解了情感上的压力，却生出了一个充满挫折的畸形儿。我们必须像过去杰出的法学家那样明白，拖延太久的正义就是被剥夺的正义。我们为我们天赋的和宪法赋予的权利已经等待了340多年。” +

所以这就是金为他们当下行动的紧迫性所做的论证。对他来说，只有那些自己从未遭受过种族隔离带来的羞辱和歧视的人才会要求他们等待。不，他们采取行动的时刻已经到来。 +

然后他接着表达了对伯明翰白人神职人员的失望——不是因为他们的种族主义，而是因为他们的温和态度。系好安全带，因为接下来的内容令人震惊：“我必须承认，在过去几年里，我对白人温和派深感失望。我几乎得出了一个令人遗憾的结论，即黑人在迈向自由的道路上最大的绊脚石不是白人公民委员会成员或三K党成员，而是那些更热衷于秩序而非正义的白人温和派。” 他说，至少对于三K党，黑人明白他们的意图——他们的意图很明确。但是对于那些敦促黑人谨慎行事、克制自己，因为他们的行动会过度扰乱社会的白人温和派，金没有耐心：“我们这一代人不仅要为坏人的尖酸言辞和行为忏悔，也要为好人令人震惊的沉默忏悔。我们必须明白，人类的进步永远不会自然而然地到来。它来自那些愿意与上帝合作的人们不知疲倦的努力和坚持不懈的工作。” +

因此，鉴于此，金认为他们的事业是正义的。现在这些白人神职人员也称金为极端分子，而他欣然接受了这个称呼。毕竟，他说，耶稣难道不是一个充满爱的极端分子吗？使徒保罗（Apostle Paul）难道不是一个为福音而极端的人吗？苏格拉底（Socrates）难道不是一个为真理而极端的人吗？而所有这些人都因为他们的极端主义而殉道。如果金身处这样一群极端分子之中，他对此毫无异议。 +

所以在信的结尾，他将美国黑人争取民权的事业提升到了一个新的高度，让它闪耀光芒，直至光芒普照：“尽管我们可能会受到虐待和蔑视，但我们的命运与美国的命运紧密相连。在清教徒登陆普利茅斯（Plymouth）之前，我们就在这里。在杰斐逊（Jefferson）在历史的篇章上写下《独立宣言》（Declaration of Independence）那庄严的文字之前，我们就在这里。两个多世纪以来，我们的先辈在这里劳作却没有报酬。他们让棉花称王，在残酷的不公正和可耻的羞辱中为他们的主人建造家园。然而，凭借着无穷的生命力，我们的人民继续繁荣发展。如果奴隶制那难以言表的残酷都无法阻止我们，那么我们现在面临的反对肯定会失败。我们将赢得自由，因为我们国家神圣的遗产和上帝的永恒意志体现在我们回响的要求之中。” +

好的，这就是你需要了解的小马丁·路德·金的《伯明翰监狱来信》的相关内容。你可以点击这里获取我为美国大学预修课程（AP）政府课程准备的复习资料包，它将帮助你在课堂上得A，在五月份的考试中得5分。如果这个视频对你有帮助，你可以点击这里查看我关于其他必学文件的所有视频。海姆勒（Heimler）下线。 + 

'''

== pure

Hey there, and welcome back to Heimler's History. In this video, we're going to consider another one of your required foundational documents for the AP Government curriculum, namely Martin Luther King Jr.'s Letter from a Birmingham Jail. So if you're ready to get them brain cows milked, but then let's get to it.

So there are about 9,000 things I could say about this document, but for our purposes, the AP Government overlords just want you to understand this document as an illustration of how the Equal Protection Clause of the 14th Amendment supported and motivated social movements. The social movement in question here was the civil rights movement for the equality of black Americans in the 1950s and 1960s. One of the key leaders of this movement was the Reverend Martin Luther King Jr., whose way of fighting for civil rights was altogether different. He taught a means of agitation defined by non-violent direct action. That means the devotees of the civil rights movement would have to endure suffering and imprisonment as they protested at segregated encounters for white people only. And he did this precisely because many state governments were failing to uphold the rights of black Americans under the Due Process Clause of the 14th Amendment.

So in 1963, King led a campaign to desegregate Birmingham, Alabama's downtown shopping district, and he did so with a series of boycotts and sit-ins and marches. Long story short, the campaign got King and hundreds more arrested. In the midst of all that, a group of white clergy who were generally sympathetic to the cause of civil rights published an open letter in the newspaper saying that such disruptive practices were not effective, and that black people in Birmingham needed to be patient and wait for the white folks to work through the courts and legislatures, and then they will have their rights. The Letter from a Birmingham Jail is King's response to their admonition.

And he opens by explaining why he's in Birmingham since he himself lived in Atlanta: "I am cognizant of the interrelatedness of all communities and states. I cannot sit idly by in Atlanta and not be concerned about what happens in Birmingham. Injustice anywhere is a threat to justice everywhere. We are caught in an inescapable network of mutuality, tied in a single garment of destiny."

He then goes on to justify the non-violent direct action that he and his followers had engaged in -- like it wasn't thrown together at the last minute. He says but it had been meticulously planned, and the participants had been trained and prepared for the likely possibility of violence and brutality. And the purpose of the movement in Birmingham was as follows: "Non-violent direct action seeks to create such a crisis and establish such creative tension that a community that has consistently refused to negotiate is forced to confront the issue. It seeks so to dramatize the issue that it can no longer be ignored." In other words, meaningful negotiation will never occur unless a crisis raises the stakes.

And why do the stakes need upping? "We know through painful experience that freedom is never voluntarily given by the oppressor. It must be demanded by the oppressed." And therefore the admonition from the white clergy for King and his followers to be patient and wait could never be a reality for them. King says: "For years now I have heard the word 'wait.' It rings in the ear of every Negro with a piercing familiarity. This 'wait' has almost always meant 'never.' It has been a tranquilizing thalidomide, relieving the emotional stress for a moment only to give birth to an ill-formed infant of frustration. We must come to see with the distinguished jurist of yesterday that justice too long delayed is justice denied. We have waited for more than 340 years for our God-given and constitutional rights."

So that's how King makes the case for the urgency of their actions at the present moment. Like for him, the only way someone could rightly ask them to wait is because they themselves had never been on the receiving end of the humiliation and discrimination in racial segregation. No, the time for them to act was at hand.

And then he goes on to express his disappointment in the white clergy of Birmingham -- not for their racism but for their moderation. And buckle your seatbelts because this is astonishing: "I must confess that over the last few years I have been gravely disappointed with the white moderate. I've almost reached the regrettable conclusion that the Negro's great stumbling block in the stride toward freedom is not the White Citizens' Counciler or the Ku Klux Klanner, but the white moderate who is more devoted to order than to justice." He says at least with the Ku Klux Klan, black people understood their intentions -- they were clear. But for the white moderates who urged caution and restraint on black people because their actions would too much disrupt society, King had no patience: "We will have to repent in this generation not merely for the vitriolic words and actions of the bad people but for the appalling silence of the good people. We must come to see that human progress never rolls in on wheels of inevitability. It comes through the tireless efforts and persistent work of men willing to be co-workers with God."

And so in light of that, King argues that their cause is a righteous one. Now these white clergy also called King an extremist, and he gladly embraces that moniker. After all, he says, wasn't Jesus an extremist for love? And wasn't the Apostle Paul an extremist for the gospel? Wasn't Socrates an extremist for truth? And all of these men were martyred for their extremism. And if King stood in a line of extremists like that, he was just fine with it.

And so to end the letter, he brings the cause of civil rights for black Americans into the clouds and makes it shine until its brightness covers all: "Abused and scorned though we may be, our destiny is tied up with the destiny of America. Before the pilgrims landed at Plymouth, we were here. Before the pen of Jefferson scratched across the pages of history the majestic word of the Declaration of Independence, we were here. For more than two centuries, our foreparents labored here without wages. They made cotton king, and they built the homes of their masters in the midst of brutal injustice and shameful humiliation. And yet out of a bottomless vitality, our people continue to thrive and develop. If the inexpressible cruelties of slavery could not stop us, the opposition we now face will surely fail. We will win our freedom because the sacred heritage of our nation and the eternal will of God are embodied in our echoing demands."

Okay, that's what you need to know about MLK's Letter from a Birmingham Jail. And you can click right here to grab my review packet for AP Government, which is going to help you get an A in your class and a five on your exam in May. And if this video helped you, can click right here and check out all my other videos on the other required documents. Heimler out.

'''

