
= 3.02 The FIRST Amendment - Freedom of RELIGION
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History. Now we've been going through 学习；审查 Unit 3 of the AP Government curriculum 课程；教学大纲, and in this video it's time to start talking about the specific 具体的；明确的 amendments 修正案 in the Bill of Rights 《权利法案》. So I reckon 认为；估计 we ought to 应该 start by talking about the First Amendment 第一修正案 and religion 宗教. So if you're ready to get them brain cows milked (俚语幽默：动脑筋), separation of church and state 政教分离 style, then let's get to it 着手做；开始行动.
+

Okay, in this video here's what we're trying to do: explain 解释 the extent to which 在多大程度上 the Supreme Court 最高法院's interpretation 解释 of the First Amendment 第一修正案 reflects 反映；体现 a commitment 承诺；致力 to individual liberty 个人自由. So we're talking about how the court has interpreted 解释 the First Amendment over time 随着时间推移, and how that has impacted 影响 the ability 能力 of folks 人们 (非正式) like you and me to practice 实践；实施 our religious beliefs 宗教信仰. We really have to emphasize 强调 practicing our beliefs because all this really comes down to 归结为；本质是 practice and not belief. Like, you can believe any dang (俚语：强调语气，无礼) thing you want and nobody's gonna stop you. If your religion teaches that the world is governed by 被统治；管理 galactic 银河的 reptilian 蜥蜴的 overlords 霸主；主宰 who forgive your sins 罪孽 as long as you slap 打；掌掴 a zebra 斑马 in the face and then eat the hair right off of its tail 尾巴 in the light of the full moon 满月, that's fine — you do you, boo (俚语：你开心就好，亲爱的). But if you show up at the zoo and start trying to practice your religion, then the police are going to have something to say about it (表达不同意见；介入).
+

So the First Amendment's protection of religion 宗教保护 is extremely 极其；非常 important, but just like every other right we have, it is not absolute 绝对的；无条件的. There is a balance 平衡 to be had, and in this case the balance is always between the religious practice 宗教实践 of the majority 多数 and the free exercise 自由行使 of minority 少数 religious practice. So before we get into 开始处理 how the Supreme Court has sought to strike 寻求实现 this balance in a couple of required 必须了解的 cases 案例, let's make sure we understand the First Amendment itself 本身. The part of the First Amendment we're considering here reads as follows 如下： “Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof.”
+

Okay, now in that sentence there are two clauses 条款 you need to know. The first is the establishment clause 建立条款, which prohibits 禁止 Congress from establishing a national church 国家教会. The second is the free exercise clause 自由行使条款, which protects the rights of citizens 公民权利 to practice their religion without interference 干涉；妨碍 from the government 政府. Now you may have heard that phrase “the wall of separation between church and state 政教之间的隔离墙,” and that comes from a letter written by Thomas Jefferson giving his interpretation 解释 of the establishment and free exercise clauses. And he said this: “I contemplate 思考；考虑 with sovereign 极度的；至高的 reverence 敬畏 that act of the whole American people which declared 宣布；声明 that their legislature 立法机关 should make no law respecting an establishment of religion, or prohibiting the free exercise thereof, thus building a wall of separation between church and state.”
+

All right, now put that in your pocket (俚语：记住这点) — we’ll get back to that in a minute. Now over time, many different actors 行动者；参与方 have sought to strengthen 加强 that wall or to weaken 削弱 it, and a good example of the thickening 加厚 of that wall of separation is the Johnson Amendment 《约翰逊修正案》. This little amendment 修正案 was attached to 附加于 a 1954 tax bill 税收法案 by then-Senator Lyndon Johnson, and it said that if a church receives tax-exempt status 免税地位, then the pastors 牧师 and priests 神父 of those churches cannot endorse 支持；背书 political candidates 候选人 from their pulpits 布道台. Now to be clear, preachers 传教士 can endorse whomever they want if they’re not concerned about 担心；关心 their church paying taxes, but most churches very much are concerned about that, and so the Johnson Amendment holds their tongue 使其保持沉默；限制发言.
+

Now the Johnson Amendment has been the bane of 祸根；烦恼 conservatives 保守派 since it was passed, even all the way up to 一直到 the most recent 最近的 Republican 共和党人 president Donald Trump, who vowed 发誓；郑重宣告 to completely 完全地 overturn 推翻；废除 the Johnson Amendment so that preachers can have their free speech back. Now as students of AP Government, you will no doubt know that a president has precisely 精确地；确切地 zero constitutional 宪法上的 power to overturn an established 成文的；已确立的 law, but regardless 不管怎样；无论如何, the Johnson Amendment is an example of the battle 斗争；争论 over how thick or thin that wall of separation should be.
+

Okay, now that we've established 确立；阐明 what the freedom of religion 宗教自由 looks like according to 根据 the First Amendment, let's see how the Supreme Court has interpreted this freedom 自由 in two required 必须了解的 cases 案例. And as with every required case, I have a whole video on each going into the details 细节 and everything you need to know, so here I'm only going to talk about them in general 大致上；概括地.
+

The first case is Engel v. Vitale, which was decided 判决 in 1962, and it has everything to do with 是否 prayer in public schools 公立学校 is constitutional 合宪的. So basically 基本上 what happened is that the New York State Board of Regents 摄政委员会 authorized 批准；授权 a short non-sectarian 非宗派的 prayer 祈祷 to be recited 背诵；朗读 by school children at the beginning of each school day. You know, as far as 就…而言 non-sectarian prayers go, this was pretty 非常 non-sectarian — it just contained general language 普通用语 about God and asking for his blessing 祝福. And what’s more 此外；而且, the prayer was voluntary 自愿的；非强制的 — if kids or parents didn’t want to say it, they didn’t have to. But even so 尽管如此, the Supreme Court deemed 认为；裁定 this a violation 违反 of the establishment clause 建立条款 of the First Amendment, thus 从而；因此 ruling 判决 state-sponsored 由国家资助或组织的 prayer in schools unconstitutional 违宪的. And in his majority opinion 多数意见 on this case, Justice Hugo Black justified 证明…正当 by invoking 援引 Jefferson’s wall of separation 政教分离 language, saying that no government had any business 该做的事 writing prayers for its citizens to pray. So this case is very much an example of the Supreme Court upholding 维护；支持 individual religious liberty 宗教自由, especially 尤其 in this case parents who objected to 反对 prayer in schools.
+

All right, the second case you need to know is a case on the free exercise clause 自由行使条款 of the First Amendment, namely 即；也就是 Wisconsin v. Yoder, which was decided 判决 in 1972. So this case had to do with 涉及；与…有关 a group of Amish parents who were patently 明显地；无疑地 not fans of 不喜欢 Wisconsin's compulsory education law 强制教育法, which conflicted 冲突；矛盾 with the Amish practice 实践；行为 of removing their children from school after eighth grade 八年级. The Amish thought eighth grade was enough, and after that their children were better served 适合；对…更有利 through vocational training 职业培训 in their communities 社区. Therefore, they complained 抱怨；指控 that the Wisconsin law violated 侵犯；违背 the free exercise 自由行使 of their religion. And as it turned out 结果是, the court agreed that it was a violation of these Amish people’s right to free exercise 自由行使权 if they were required to keep their children in school — the children might be exposed to 接触；暴露于 influence 影响 that would be contrary to 与…相反 the community’s religious values 宗教价值观. So again, this is an example of the court upholding 维护 the individual liberty 自由 of free exercise of religion 宗教自由. +

However 然而, that trend 趋势；倾向 isn't always the case 并不总是如此. Like, what if your religion 宗教 demands 要求 a practice 实践；做法 that is illegal 违法的? Well, that was decided 判决 in 1990 in the non-required 非必修的；非强制掌握的 case Employment Division v. Smith, in which the court ruled 裁定；裁决 against the free exercise 自由行使 of two men who had used 使用 hallucinogenic 致幻的 drugs 毒品 as part of a Native American Church ritual 仪式；典礼. Like I said at the beginning, none of our liberties 自由 is absolute 绝对的；不受限制的 — there are limits 限制, and the court ruled that the free exercise of religion 宗教自由 could be restricted 限制 if that practice 行为；做法 was otherwise illegal 违法的.
+

All right, that's what you need to know about Unit 3 Topic 2 of the AP Government curriculum 教学大纲. Click right here to grab 抓取；获得 a review packet 复习资料包 which will help you get an A in your class and a 5 on your exam 考试 in May. And look, I will in no way 毫无疑问；绝不会 restrict 限制 your right of free exercise 自由行使权 to subscribe 订阅；关注 to my channel, and if you do that tells me you want me to keep making these videos 视频. So I'll see you in the next one. Heimler out.
+

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史课程。我们一直在学习美国大学预修课程（AP）政府课程的第三单元，在这个视频中，我们要开始讨论《权利法案》中的具体修正案。所以我认为我们应该从讨论第一修正案和宗教开始。所以，如果你准备好以政教分离的方式汲取知识，那么我们开始吧。 +

好的，在这个视频中，我们要做的是：解释最高法院对第一修正案的解释在多大程度上反映了对个人自由的承诺。所以我们要讨论随着时间的推移，法院是如何解释第一修正案的，以及这对像你我这样的人践行宗教信仰的能力有何影响。我们真的必须强调践行我们的信仰，因为这一切归根结底在于践行，而不是信仰。比如说，你可以相信任何你想相信的事情，没人会阻止你。如果你的宗教教导说，世界是由银河系的爬行动物领主统治的，只要你扇斑马的脸，然后在满月的光线下吃掉它尾巴上的毛发，你的罪恶就会被原谅，那也没关系 —— 你就按自己的方式来，宝贝。但如果你出现在动物园并开始践行你的宗教，那么警察就会对此说些什么。 +

所以第一修正案对宗教的保护极其重要，但就像我们拥有的其他权利一样，它不是绝对的。需要达成一种平衡，在这种情况下，平衡总是存在于多数人的宗教践行和少数人的宗教践行自由之间。所以在我们探讨最高法院在一些必学案例中是如何寻求达成这种平衡之前，让我们先确保理解第一修正案本身。我们这里考虑的第一修正案的部分内容如下：“国会不得制定关于确立宗教或禁止自由践行宗教的法律。” +

好的，在这句话中有两个条款你需要知道。第一个是确立条款，它禁止国会确立国教。第二个是自由践行条款，它保护公民在不受政府干涉的情况下践行宗教的权利。现在你可能听说过 “政教分离之墙” 这个短语，它来自托马斯·杰斐逊（Thomas Jefferson）写的一封信，信中给出了他对确立条款和自由践行条款的解释。他是这样说的：“我怀着至高的敬意思考全体美国人民的这一行为，即他们的立法机构不得制定关于确立宗教或禁止自由践行宗教的法律，从而建立起政教分离之墙。” +

好的，先记住这个 —— 我们一会儿还会提到它。随着时间的推移，许多不同的参与者试图加强或削弱这堵政教分离之墙，加强这堵墙的一个很好的例子是《约翰逊修正案》（Johnson Amendment）。这个小修正案是当时的参议员林登·约翰逊（Lyndon Johnson）附加到1954年的一项税收法案上的，它规定，如果一个教堂获得免税地位，那么这些教堂的牧师不能在讲坛上支持政治候选人。现在要明确的是，如果牧师不担心他们的教堂纳税，他们可以支持任何他们想支持的人，但大多数教堂非常在意这一点，所以《约翰逊修正案》让他们保持沉默。 +

自《约翰逊修正案》通过以来，它一直是保守派的心头大患，甚至一直到最近的共和党总统唐纳德·特朗普（Donald Trump），他发誓要彻底推翻《约翰逊修正案》，这样牧师们就能恢复他们的言论自由。现在作为美国大学预修课程（AP）政府课程的学生，你无疑知道总统在宪法上完全没有权力推翻一项已确立的法律，但无论如何，《约翰逊修正案》是关于政教分离之墙应该厚还是薄的斗争的一个例子。 +

好的，既然我们已经确定了根据第一修正案宗教自由是什么样的，让我们看看最高法院在两个必学案例中是如何解释这种自由的。和每个必学案例一样，我对每个案例都有一个完整的视频，讲解其中的细节以及你需要知道的一切，所以在这里我只做一个大概的讨论。 +

第一个案例是 “恩格尔诉维塔尔案”（Engel v. Vitale），该案于1962年做出裁决，它与公立学校的祈祷是否符合宪法的问题息息相关。基本上，事情是这样的：纽约州教育委员会（New York State Board of Regents）批准了一段简短的非教派祈祷词，让学童在每天上学开始时背诵。你知道，就非教派祈祷而言，这段祈祷词相当中立 —— 它只是包含了关于上帝的一般性表述并祈求他的祝福。而且，这段祈祷是自愿的 —— 如果孩子或家长不想背诵，他们可以不背。但即便如此，最高法院认为这违反了第一修正案的确立条款，因此裁定州政府支持的学校祈祷是违宪的。在这个案件的多数意见中，雨果·布莱克（Hugo Black）大法官援引杰斐逊的政教分离之墙的说法为这一裁定辩护，他说没有政府有权为公民编写祈祷词。所以这个案例是最高法院维护个人宗教自由的一个很好的例子，特别是在这个案例中，那些反对学校祈祷的家长的宗教自由得到了维护。 +

好的，你需要知道的第二个案例是关于第一修正案自由践行条款的一个案例，即 “威斯康星州诉约德案”（Wisconsin v. Yoder），该案于1972年做出裁决。这个案例与一群阿米什（Amish）家长有关，他们显然不喜欢威斯康星州（Wisconsin）的义务教育法，该法律与阿米什人在孩子八年级后让他们辍学的做法相冲突。阿米什人认为八年级的教育就足够了，在那之后，他们的孩子通过在社区接受职业培训能得到更好的发展。因此，他们抱怨威斯康星州的法律侵犯了他们自由践行宗教的权利。结果是，法院认为，如果要求这些阿米什人让他们的孩子继续上学，这侵犯了他们自由践行宗教的权利 —— 孩子们可能会受到与社区宗教价值观相悖的影响。所以，这又是一个法院维护个人自由践行宗教权利的例子。 +

然而，这种趋势并不总是如此。比如说，如果你的宗教要求一种违法的行为呢？这在1990年的 “就业部诉史密斯案”（Employment Division v. Smith，这不是必学案例）中得到了解决，在这个案件中，法院驳回了两个将致幻药物用于美洲原住民教会仪式的人的自由践行宗教的诉求。就像我一开始说的，我们的自由没有一项是绝对的 —— 是有界限的，法院裁定，如果一种宗教践行在其他方面是违法的，那么对宗教的自由践行可以受到限制。 +

好的，这就是你需要了解的美国大学预修课程（AP）政府课程第三单元主题2的内容。点击这里获取复习资料包，它将帮助你在课堂上得A，在五月份的考试中得5分。而且听着，我绝不会限制你订阅我频道的自由践行权利，如果你订阅了，那就告诉我你希望我继续制作这些视频。那么我们下一个视频再见。海姆勒（Heimler）下线。 + 

'''

== pure

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 3 of the AP Government curriculum, and in this video it's time to start talking about the specific amendments in the Bill of Rights. So I reckon we ought to start by talking about the First Amendment and religion. So if you're ready to get them brain cows milked separation of church and state style, then let's get to it.

Okay, in this video here's what we're trying to do: explain the extent to which the Supreme Court's interpretation of the First Amendment reflects a commitment to individual liberty. So we're talking about how the court has interpreted the First Amendment over time, and how that has impacted the ability of folks like you and me to practice our religious beliefs. We really have to emphasize practicing our beliefs because all this really comes down to practice and not belief. Like, you can believe any dang thing you want and nobody's gonna stop you. If your religion teaches that the world is governed by galactic reptilian overlords who forgive your sins as long as you slap a zebra in the face and then eat the hair right off of its tail in the light of the full moon, that's fine -- you do you, boo. But if you show up at the zoo and start trying to practice your religion, then the police are going to have something to say about it.

So the First Amendment's protection of religion is extremely important, but just like every other right we have, it is not absolute. There is a balance to be had, and in this case the balance is always between the religious practice of the majority and the free exercise of minority religious practice. So before we get into how the Supreme Court has sought to strike this balance in a couple of required cases, let's make sure we understand the First Amendment itself. The part of the First Amendment we're considering here reads as follows: "Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof."

Okay, now in that sentence there are two clauses you need to know. The first is the establishment clause, which prohibits Congress from establishing a national church. The second is the free exercise clause, which protects the rights of citizens to practice their religion without interference from the government. Now you may have heard that phrase "the wall of separation between church and state," and that comes from a letter written by Thomas Jefferson giving his interpretation of the establishment and free exercise clauses. And he said this: "I contemplate with sovereign reverence that act of the whole American people which declared that their legislature should make no law respecting an establishment of religion, or prohibiting the free exercise thereof, thus building a wall of separation between church and state."

All right, now put that in your pocket -- we'll get back to that in a minute. Now over time, many different actors have sought to strengthen that wall or to weaken it, and a good example of the thickening of that wall of separation is the Johnson Amendment. This little amendment was attached to a 1954 tax bill by then-Senator Lyndon Johnson, and it said that if a church receives tax-exempt status, then the pastors and priests of those churches cannot endorse political candidates from their pulpits. Now to be clear, preachers can endorse whomever they want if they're not concerned about their church paying taxes, but most churches very much are concerned about that, and so the Johnson Amendment holds their tongue.

Now the Johnson Amendment has been the bane of conservatives since it was passed, even all the way up to the most recent Republican president Donald Trump, who vowed to completely overturn the Johnson Amendment so that preachers can have their free speech back. Now as students of AP Government, you will no doubt know that a president has precisely zero constitutional power to overturn an established law, but regardless, the Johnson Amendment is an example of the battle over how thick or thin that wall of separation should be.

Okay, now that we've established what the freedom of religion looks like according to the First Amendment, let's see how the Supreme Court has interpreted this freedom in two required cases. And as with every required case, I have a whole video on each going into the details and everything you need to know, so here I'm only going to talk about them in general.

The first case is Engel v. Vitale, which was decided in 1962, and it has everything to do with whether prayer in public schools is constitutional. So basically what happened is that the New York State Board of Regents authorized a short non-sectarian prayer to be recited by school children at the beginning of each school day. You know, as far as non-sectarian prayers go, this was pretty non-sectarian -- it just contained general language about God and asking for his blessing. And what's more, the prayer was voluntary -- if kids or parents didn't want to say it, they didn't have to. But even so, the Supreme Court deemed this a violation of the establishment clause of the First Amendment, thus ruling state-sponsored prayer in schools unconstitutional. And in his majority opinion on this case, Justice Hugo Black justified it by invoking Jefferson's wall of separation language, saying that no government had any business writing prayers for its citizens to pray. So this case is very much an example of the Supreme Court upholding individual religious liberty, especially in this case parents who objected to prayer in schools.

All right, the second case you need to know is a case on the free exercise clause of the First Amendment, namely Wisconsin v. Yoder, which was decided in 1972. So this case had to do with a group of Amish parents who were patently not fans of Wisconsin's compulsory education law, which conflicted with the Amish practice of removing their children from school after eighth grade. The Amish thought eighth grade was enough, and after that their children were better served through vocational training in their communities. Therefore, they complained that the Wisconsin law violated the free exercise of their religion. And as it turned out, the court agreed that it was a violation of these Amish people's right to free exercise if they were required to keep their children in school -- the children might be exposed to influence that would be contrary to the community's religious values. So again, this is an example of the court upholding the individual liberty of free exercise of religion.

However, that trend isn't always the case. Like, what if your religion demands a practice that is illegal? Well, that was decided in 1990 in the non-required case Employment Division v. Smith, in which the court ruled against the free exercise of two men who had used hallucinogenic drugs as part of a Native American Church ritual. Like I said at the beginning, none of our liberties is absolute -- there are limits, and the court ruled that the free exercise of religion could be restricted if that practice was otherwise illegal.

All right, that's what you need to know about Unit 3 Topic 2 of the AP Government curriculum. Click right here to grab a review packet which will help you get an A in your class and a 5 on your exam in May. And look, I will in no way restrict your right of free exercise to subscribe to my channel, and if you do that tells me you want me to keep making these videos. So I'll see you in the next one. Heimler out.

'''

