
= 3.10 Social Movements and EQUAL Protection
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 3 of the AP Government curriculum 课程, and in this video it's time to turn the corner 转变方向 and start talking about civil rights 公民权利. So if you're ready to get them brain cows milked with, then let's get to it. +

So in this video, here's what we're trying to do: explain how constitutional provisions 宪法条款 have supported and motivated 推动 social movements 社会运动. Okay, now before we get into that, let me make a distinction 区分 that might help clear up 澄清 some confusion. Over the course of 在…期间 all these Unit 3 videos, we've been talking about civil liberties 公民自由 that are guaranteed to 保证给予 Americans via the Bill of Rights 权利法案. Those liberties include the right to free speech 言论自由 and free exercise of religion 宗教信仰自由, the right to a lawyer in court 法庭上获得律师帮助的权利, etc., etc. But in this video, we're going to be talking about civil rights, and that is not the same thing as civil liberties. +

So let me just say it simply: civil liberties are those rights guaranteed to every American citizen by the Constitution 宪法. Civil rights movements 公民权利运动 make sure that every American -- regardless of 不管；不顾 sex 性别, religion, or race 种族 -- has equal access to 平等享有 those liberties. The main way that civil rights activists 活动家 have attempted to apply those rights to everyone is through the due process 正当程序 and equal protection clauses 平等保护条款 of the 14th Amendment 第十四修正案. So whenever you're thinking about civil rights, you need to automatically connect that with the 14th Amendment. Get that neural pathway 神经通路 fixed and strong because you're going to need it for the exam. +

Okay, let's talk about civil rights movements. And although there have been many throughout the history of America, we're going to start in the 1950s with the movement from which all the others afterward got their inspiration 灵感 -- namely, the civil rights movement 民权运动 for the equality of black Americans 美国黑人平等. Now after the Civil War 南北战争, the 13th Amendment 第十三修正案 was passed which formally abolished 废除 slavery 奴隶制 in the United States, which meant that constitutionally 从宪法角度, every former enslaved laborer 前被奴役的劳动者 in the South was now a citizen of the United States. However, if you know anything about the history of those tumultuous 动荡的 years, you'll know that after the end of Reconstruction 重建时期 in 1877, southern states very much reverted to 恢复 the old racial hierarchy 种族等级制度 and oppression 压迫 that characterized the South before the war. +

Despite the fact that southern states were required to ratify 批准 the 14th Amendment in order to be readmitted into the Union 重新加入联邦, they found ways to disenfranchise 剥夺选举权 and marginalize 边缘化 black Southerners. This happened with the rise of restrictive rules 限制性规定 called black codes 黑人法典 and societal segregation 社会隔离 via Jim Crow laws 吉姆·克劳法. So despite the fact that the 13th, 14th, and 15th Amendments recognize black citizens as fully equal to white citizens, that's not really how it played out 发展；结果 in reality. +

So coming into the 1950s, a formal movement began to emerge, and one of the key figures 关键人物 of this movement was a preacher 牧师 from Georgia named Martin Luther King Jr. He made a name for himself 成名 during the Montgomery bus boycott 蒙哥马利公交车抵制运动 starting in 1955. King advocated 倡导 an approach to civil rights defined by non-violent protest 非暴力抗议, and many of his followers did so. Now to be fair, there were other more militant 激进的 black rights movements under the leadership of Malcolm X and the Black Panthers 黑豹党 which advocated for black separatism 黑人分离主义, but we're focusing on the civil rights movement under King's leadership because they argued for the rights of black Americans explicitly 明确地 on the basis of 根据 the Constitution. +

In fact, as I mentioned before, it was largely the 14th Amendment that spurred 激励 this group into action. Clearly, Jim Crow segregation 吉姆·克劳种族隔离制度 was an attempt to bypass 绕过 the equal protection clause of that amendment, and the devotees 拥护者 of the civil rights movement aimed to make that right. If you want a clear insight into 深入了解 King's non-violent philosophy 非暴力理念, then there's no better place to go than to one of your required documents 必读材料 for this course -- namely, "A Letter from a Birmingham Jail" 《伯明翰监狱来信》. Now as with every required document in this course, I have a whole video exploring the details of it, but for now just let me give you the gist of it 要点. +

On this occasion, King and some other leaders of the civil rights movement were arrested for parading 游行 without a permit 许可证 -- which they did in order to protest Birmingham's deep segregationist laws 种族隔离法. And while he was in jail, a group of white clergymen 白人牧师 who were -- to be fair -- sympathetic to 同情 the cause of civil rights published a letter in the newspaper saying that black protesters ought not be out parading like that. Instead, they should wait and allow sympathetic white folks to take up their cause for them. So King's letter from jail was his response to their admonition 告诫, and he said this: "Only those who have not been under the degrading lash of racism 种族主义的侮辱 can rightly say wait. The time for action is now." And while racist laws must be fought in court, they must also be protested on the streets because only in that way can they force the white majority to confront their racism 直面种族主义 and enter into a dialogue about long-term change. +

Now the civil rights movement earned some potent 重大的 victories, and that's what we're going to consider in the next video. But for now, let's just consider some of the other movements for civil rights that grew out of the soil of 源于 the movement for black equality. First, how about we talk about the women's rights movement 女权运动 in the 1960s and 1970s. So a huge victory for women was the ratification of the 19th Amendment 第十九修正案 in 1920 which formally recognized women's right to vote 选举权. But even so, there were still a lot of ways that women were marginalized 边缘化 in U.S. society. Like for example, courts could still seat all-male juries 全男性陪审团, and women were generally paid less for equal work 同工不同酬. +

And so in order to right some of these wrongs 纠正这些不公, the National Organization for Women (NOW) 全国妇女组织 was founded in 1966. Partly this group emerged because of a book called "The Feminine Mystique" 《女性的奥秘》 written by Betty Friedan and published in 1963. In that book, Friedan exposed -- through interviews with women -- the drudgery 单调乏味 and hopelessness 绝望 that came with constantly submitting to 屈从于 their predetermined 预先确定的 societal roles 社会角色 as nothing more than mothers and wives and homemakers whose greatest glory in life was making their husband a sandwich. Additionally, NOW was energized by 因…而活跃起来 the Civil Rights Act of 1964 1964年民权法案 which banned discrimination based on sex 性别歧视, but it was weakly enforced 执行不力 on that count. +

A major goal of the women's rights movement was to pass something called the Equal Rights Amendment 平等权利修正案, which said: "Equality of rights under the law shall not be denied or abridged 剥夺 by the United States or by any state on account of sex." However, thanks to the lobbying efforts 游说活动 of conservative women 保守派女性 represented by Phyllis Schlafly, the ERA fell short of 未达到 the required number of states necessary for ratification 批准所需的州数量. Even so, the women's rights movement did win a victory in the passage of the Education Amendments Act in 1962 1962年教育修正案法案, particularly Title IX of that act 该法案的第九条, which guaranteed that women would have the same opportunities as men in educational institutions 教育机构 that received federal funding 接受联邦资助. +

Then in the 1970s and 1980s, another civil rights movement sprang up 兴起 dealing with the rights of the LGBTQ community LGBTQ群体的权利. In those days, homosexuality 同性恋 was still defined as a mental illness 精神疾病, and many states had laws that discriminated against 歧视 gay men and women. For example, into the 90s, if you were gay you could not serve in the military 参军. Now President Clinton promised to reverse 废除 this in his campaign speeches 竞选演讲, but found that once he was elected his generals were very much against him on this count. So he instituted 制定 the "Don't Ask, Don't Tell" policy “不问不说”政策, which is exactly what it sounds like. Under this policy, gay men and women could serve in the military, but just don't tell anyone you're gay and we won't ask. That policy reigned 持续 until the presidency of Barack Obama who led Congress to do away with 废除 "Don't Ask, Don't Tell," and as a result, people of any sexual orientation 性取向 could now serve in the military. +

And then yet another civil rights movement sprang up in the 1970s -- the right-to-life movement 反堕胎运动 that opposed abortion 堕胎. This of course came in the wake of 在…之后 the Supreme Court's decision in Roe v. Wade 罗诉韦德案, on which I have a whole video, but for now you just need to know that the Roe decision made abortion on demand 按需堕胎 legal in the first trimester 怀孕前三个月 without restriction 不受限制 across the United States. And those who are members of the women's rights movement consider this a big victory, but a growing group of Catholics 天主教徒 and white evangelical Christians 白人福音派基督徒 rose up to oppose it. By 1980, these groups had melded 融合 their cause with the Republican Party's platform 共和党的纲领 against abortion, and their main argument was that from the moment of conception 受孕, that entity 实体 in a woman's womb 子宫 was actually in fact a human being, and as such that human baby ought to have equal protection of the laws just like any other American did. +

This group worked hard to reverse the effects of Roe v. Wade, and they did have some success, but not as much as they would like. One of the big pushes was for something called the Hatch Amendment 哈奇修正案, named after Senator Orrin Hatch who proposed it. Basically, this was a proposed amendment to the Constitution 宪法修正案 that would restrict abortion 限制堕胎. It would do so by mandating 规定 that whichever abortion law was more restrictive -- whether state or federal law -- that would be the binding law 有约束力的法律 in any given state. And despite much enthusiasm for the right-to-life movement regarding this amendment, it ultimately did not pass. +

So the point to all the movements that I've just mentioned is this: these civil rights movements are evidence of how the equal protection clause 平等保护条款 can support and motivate social movements for civil rights. Okay, well thanks for watching. Click right here to grab a review packet which is going to help you get an A in your class and a five on your exam in May. Additionally, if you were helped by this video and you want me to keep making them, then by all means subscribe 订阅 and I shall oblige 照办. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史课程。我们一直在学习美国大学预修课程（AP）政府课程的第三单元，在这个视频中，是时候转变一下话题，开始讨论公民权利了。所以，如果你准备好汲取知识，那我们开始吧。 +

所以在这个视频中，我们要做的是：解释宪法条款是如何支持并推动社会运动的。好的，在我们深入探讨之前，让我做一个区分，这可能有助于消除一些困惑。在所有这些第三单元的视频中，我们一直在讨论《权利法案》赋予美国人的公民自由。这些自由包括言论自由和宗教自由的权利、在法庭上获得律师帮助的权利等等。但在这个视频中，我们要讨论的是公民权利，这和公民自由可不是一回事。 +

所以让我简单地说：公民自由是宪法赋予每个美国公民的权利。公民权利运动确保每个美国人——无论性别、宗教或种族——都能平等地享有这些自由。公民权利活动家试图将这些权利应用于每个人的主要方式，是通过第十四修正案中的正当程序和平等保护条款。所以，每当你想到公民权利时，你需要自动将其与第十四修正案联系起来。把这条神经通路牢牢记住，因为考试时你会用到它。 +

好的，让我们谈谈公民权利运动。虽然在美国历史上有许多这样的运动，但我们要从20世纪50年代开始说起，从那场启发了后来所有运动的运动——即争取美国黑人平等的民权运动说起。美国内战后，第十三修正案通过，正式废除了美国的奴隶制，这意味着从宪法角度来说，南方的每一个前奴隶现在都是美国公民。然而，如果你对那些动荡岁月的历史有所了解，你就会知道，1877年重建时期结束后，南方各州很大程度上又恢复了战前南方的种族等级制度和压迫。 +

尽管南方各州为了重新加入联邦，被要求批准第十四修正案，但他们还是找到了剥夺南方黑人权利并将他们边缘化的方法。这体现在被称为黑人法典的限制性规则的出现，以及通过吉姆·克劳法实行的社会隔离。所以，尽管第十三、十四和十五修正案承认黑人公民与白人公民完全平等，但在现实中并非如此。 +

所以到了20世纪50年代，一场正式的运动开始兴起，这场运动的关键人物之一是来自佐治亚州的牧师小马丁·路德·金（Martin Luther King Jr.）。他在1955年开始的蒙哥马利公交车抵制运动中崭露头角。金倡导以非暴力抗议的方式争取公民权利，他的许多追随者也这样做。公平地说，还有其他更激进的黑人权利运动，由马尔科姆·X（Malcolm X）和黑豹党领导，他们主张黑人分离主义，但我们关注的是金领导的民权运动，因为他们明确地以宪法为基础来争取美国黑人的权利。 +

事实上，正如我之前提到的，很大程度上是第十四修正案促使这个团体采取行动。显然，吉姆·克劳种族隔离是试图绕过该修正案的平等保护条款，民权运动的追随者旨在纠正这种情况。如果你想清楚地了解金的非暴力哲学，那么有一份本课程的必学文件是最好的参考——即《来自伯明翰监狱的一封信》（“A Letter from a Birmingham Jail”）。和本课程的其他必学文件一样，我有一个完整的视频来探讨它的细节，但现在让我告诉你它的要点。 +

在那次事件中，金和民权运动的其他一些领导人因无证游行而被捕——他们游行是为了抗议伯明翰严重的种族隔离法律。他在监狱里的时候，一群同情民权事业的白人牧师在报纸上发表了一封信，说黑人抗议者不应该那样游行。相反，他们应该等待，让同情他们的白人来为他们争取权益。所以金在监狱里写的这封信是对他们告诫的回应，他说：“只有那些没有遭受过种族主义羞辱的人才能理直气壮地说等待。现在就是行动的时候。” 虽然种族主义法律必须在法庭上进行抗争，但也必须在街头进行抗议，因为只有这样，才能迫使占多数的白人正视他们的种族主义，并就长期变革展开对话。 +

现在，民权运动取得了一些有力的胜利，我们将在下一个视频中探讨这些胜利。但现在，让我们来看看其他一些从争取黑人平等运动中发展出来的公民权利运动。首先，我们来谈谈20世纪60年代和70年代的妇女权利运动。对女性来说，一个巨大的胜利是1920年第十九修正案的批准，它正式承认了女性的投票权。但即便如此，在美国社会中，女性仍然在很多方面被边缘化。例如，法庭仍然可以组成全是男性的陪审团，而且女性通常做同样的工作却得到更少的报酬。 +

所以为了纠正这些错误，全国妇女组织（National Organization for Women，NOW）于1966年成立。这个组织的出现部分是因为贝蒂·弗里丹（Betty Friedan）在1963年出版的一本书，名为《女性的奥秘》（“The Feminine Mystique”）。在那本书中，弗里丹通过对女性的采访，揭露了她们不断屈从于被预先设定的社会角色（仅仅作为母亲、妻子和家庭主妇，而她们人生最大的荣耀就是为丈夫做一个三明治）所带来的单调乏味和绝望。此外，全国妇女组织受到1964年《民权法案》的激励，该法案禁止性别歧视，但在这方面的执行力度很弱。 +

妇女权利运动的一个主要目标是通过一项名为《平等权利修正案》的法案，该修正案规定：“法律之下的平等权利，不得因性别而被美国或任何州剥夺或削减。” 然而，由于菲利斯·施拉夫利（Phyllis Schlafly）所代表的保守派女性的游说努力，《平等权利修正案》未能获得批准所需的州的数量。即便如此，妇女权利运动在1962年通过的《教育修正案法案》中取得了胜利，特别是该法案的第九条，它保证女性在接受联邦资助的教育机构中享有与男性相同的机会。 +

然后在20世纪70年代和80年代，又兴起了另一场公民权利运动，涉及男女同性恋、双性恋和跨性别者（LGBTQ）群体的权利。在那些日子里，同性恋仍然被定义为一种精神疾病，许多州都有歧视男女同性恋者的法律。例如，直到90年代，同性恋者不能在军队服役。当时克林顿总统在竞选演讲中承诺扭转这种情况，但他当选后发现，他的将军们在这个问题上非常反对他。所以他制定了 “不问不说” 政策，正如其名。根据这项政策，男女同性恋者可以在军队服役，但不要告诉任何人你是同性恋，我们也不会问。这项政策一直持续到巴拉克·奥巴马（Barack Obama）总统时期，他带领国会废除了 “不问不说” 政策，结果是任何性取向的人现在都可以在军队服役。 +

然后在20世纪70年代，又兴起了另一场公民权利运动——反对堕胎的 “生命权” 运动。这当然是在最高法院对 “罗诉韦德案”（Roe v. Wade）做出裁决之后，关于这个案子我有一个完整的视频，但现在你只需要知道，“罗诉韦德案” 的裁决使得在美国，在怀孕的前三个月按需堕胎是合法的。妇女权利运动的成员认为这是一个重大胜利，但越来越多的天主教徒和白人福音派基督徒站出来反对。到1880年，这些团体将他们的事业与共和党的反堕胎纲领结合起来，他们的主要论点是，从受孕的那一刻起，女性子宫里的那个实体实际上就是一个人，因此这个婴儿应该和其他美国人一样受到法律的平等保护。 +

这个团体努力想要扭转 “罗诉韦德案” 的影响，他们也取得了一些成功，但没有达到他们想要的程度。其中一个重大推动是一项名为 “哈奇修正案”（Hatch Amendment）的提案，以提出该修正案的参议员奥林·哈奇（Orrin Hatch）的名字命名。基本上，这是一项对宪法的修正案提案，旨在限制堕胎。它通过规定无论州法还是联邦法，只要是更具限制性的堕胎法律，就将其作为在任何一个州具有约束力的法律来实现这一目标。尽管 “生命权” 运动对这项修正案充满热情，但它最终没有通过。 +

所以我刚才提到的所有这些运动的重点是：这些公民权利运动证明了平等保护条款是如何支持并推动争取公民权利的社会运动的。好的，感谢观看。点击这里获取复习资料包，它将帮助你在课堂上得A，在五月份的考试中得5分。此外，如果你从这个视频中得到了帮助，并且希望我继续制作这样的视频，那就订阅吧，我会照做的。海姆勒（Heimler）下线。 + 

'''

== pure

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 3 of the AP Government curriculum, and in this video it's time to turn the corner and start talking about civil rights. So if you're ready to get them brain cows milked with, then let's get to it.

So in this video, here's what we're trying to do: explain how constitutional provisions have supported and motivated social movements. Okay, now before we get into that, let me make a distinction that might help clear up some confusion. Over the course of all these Unit 3 videos, we've been talking about civil liberties that are guaranteed to Americans via the Bill of Rights. Those liberties include the right to free speech and free exercise of religion, the right to a lawyer in court, etc., etc. But in this video, we're going to be talking about civil rights, and that is not the same thing as civil liberties.

So let me just say it simply: civil liberties are those rights guaranteed to every American citizen by the Constitution. Civil rights movements make sure that every American -- regardless of sex, religion, or race -- has equal access to those liberties. The main way that civil rights activists have attempted to apply those rights to everyone is through the due process and equal protection clauses of the 14th Amendment. So whenever you're thinking about civil rights, you need to automatically connect that with the 14th Amendment. Get that neural pathway fixed and strong because you're going to need it for the exam.

Okay, let's talk about civil rights movements. And although there have been many throughout the history of America, we're going to start in the 1950s with the movement from which all the others afterward got their inspiration -- namely, the civil rights movement for the equality of black Americans. Now after the Civil War, the 13th Amendment was passed which formally abolished slavery in the United States, which meant that constitutionally, every former enslaved laborer in the South was now a citizen of the United States. However, if you know anything about the history of those tumultuous years, you'll know that after the end of Reconstruction in 1877, southern states very much reverted to the old racial hierarchy and oppression that characterized the South before the war.

Despite the fact that southern states were required to ratify the 14th Amendment in order to be readmitted into the Union, they found ways to disenfranchise and marginalize black Southerners. This happened with the rise of restrictive rules called black codes and societal segregation via Jim Crow laws. So despite the fact that the 13th, 14th, and 15th Amendments recognize black citizens as fully equal to white citizens, that's not really how it played out in reality.

So coming into the 1950s, a formal movement began to emerge, and one of the key figures of this movement was a preacher from Georgia named Martin Luther King Jr. He made a name for himself during the Montgomery bus boycott starting in 1955. King advocated an approach to civil rights defined by non-violent protest, and many of his followers did so. Now to be fair, there were other more militant black rights movements under the leadership of Malcolm X and the Black Panthers which advocated for black separatism, but we're focusing on the civil rights movement under King's leadership because they argued for the rights of black Americans explicitly on the basis of the Constitution.

In fact, as I mentioned before, it was largely the 14th Amendment that spurred this group into action. Clearly, Jim Crow segregation was an attempt to bypass the equal protection clause of that amendment, and the devotees of the civil rights movement aimed to make that right. If you want a clear insight into King's non-violent philosophy, then there's no better place to go than to one of your required documents for this course -- namely, "A Letter from a Birmingham Jail." Now as with every required document in this course, I have a whole video exploring the details of it, but for now just let me give you the gist of it.

On this occasion, King and some other leaders of the civil rights movement were arrested for parading without a permit -- which they did in order to protest Birmingham's deep segregationist laws. And while he was in jail, a group of white clergymen who were -- to be fair -- sympathetic to the cause of civil rights published a letter in the newspaper saying that black protesters ought not be out parading like that. Instead, they should wait and allow sympathetic white folks to take up their cause for them. So King's letter from jail was his response to their admonition, and he said this: "Only those who have not been under the degrading lash of racism can rightly say wait. The time for action is now." And while racist laws must be fought in court, they must also be protested on the streets because only in that way can they force the white majority to confront their racism and enter into a dialogue about long-term change.

Now the civil rights movement earned some potent victories, and that's what we're going to consider in the next video. But for now, let's just consider some of the other movements for civil rights that grew out of the soil of the movement for black equality. First, how about we talk about the women's rights movement in the 1960s and 1970s. So a huge victory for women was the ratification of the 19th Amendment in 1920 which formally recognized women's right to vote. But even so, there were still a lot of ways that women were marginalized in U.S. society. Like for example, courts could still seat all-male juries, and women were generally paid less for equal work.

And so in order to right some of these wrongs, the National Organization for Women (NOW) was founded in 1966. Partly this group emerged because of a book called "The Feminine Mystique" written by Betty Friedan and published in 1963. In that book, Friedan exposed -- through interviews with women -- the drudgery and hopelessness that came with constantly submitting to their predetermined societal roles as nothing more than mothers and wives and homemakers whose greatest glory in life was making their husband a sandwich. Additionally, NOW was energized by the Civil Rights Act of 1964 which banned discrimination based on sex, but it was weakly enforced on that count.

A major goal of the women's rights movement was to pass something called the Equal Rights Amendment, which said: "Equality of rights under the law shall not be denied or abridged by the United States or by any state on account of sex." However, thanks to the lobbying efforts of conservative women represented by Phyllis Schlafly, the ERA fell short of the required number of states necessary for ratification. Even so, the women's rights movement did win a victory in the passage of the Education Amendments Act in 1962, particularly Title IX of that act, which guaranteed that women would have the same opportunities as men in educational institutions that received federal funding.

Then in the 1970s and 1980s, another civil rights movement sprang up dealing with the rights of the LGBTQ community. In those days, homosexuality was still defined as a mental illness, and many states had laws that discriminated against gay men and women. For example, into the 90s, if you were gay you could not serve in the military. Now President Clinton promised to reverse this in his campaign speeches, but found that once he was elected his generals were very much against him on this count. So he instituted the "Don't Ask, Don't Tell" policy, which is exactly what it sounds like. Under this policy, gay men and women could serve in the military, but just don't tell anyone you're gay and we won't ask. That policy reigned until the presidency of Barack Obama who led Congress to do away with "Don't Ask, Don't Tell," and as a result, people of any sexual orientation could now serve in the military.

And then yet another civil rights movement sprang up in the 1970s -- the right-to-life movement that opposed abortion. This of course came in the wake of the Supreme Court's decision in Roe v. Wade, on which I have a whole video, but for now you just need to know that the Roe decision made abortion on demand legal in the first trimester without restriction across the United States. And those who are members of the women's rights movement consider this a big victory, but a growing group of Catholics and white evangelical Christians rose up to oppose it. By 1980, these groups had melded their cause with the Republican Party's platform against abortion, and their main argument was that from the moment of conception, that entity in a woman's womb was actually in fact a human being, and as such that human baby ought to have equal protection of the laws just like any other American did.

This group worked hard to reverse the effects of Roe v. Wade, and they did have some success, but not as much as they would like. One of the big pushes was for something called the Hatch Amendment, named after Senator Orrin Hatch who proposed it. Basically, this was a proposed amendment to the Constitution that would restrict abortion. It would do so by mandating that whichever abortion law was more restrictive -- whether state or federal law -- that would be the binding law in any given state. And despite much enthusiasm for the right-to-life movement regarding this amendment, it ultimately did not pass.

So the point to all the movements that I've just mentioned is this: these civil rights movements are evidence of how the equal protection clause can support and motivate social movements for civil rights. Okay, well thanks for watching. Click right here to grab a review packet which is going to help you get an A in your class and a five on your exam in May. Additionally, if you were helped by this video and you want me to keep making them, then by all means subscribe and I shall oblige. Heimler out.

'''

