
= 4.01 American ATTITUDES About Government & Politics
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History, and furthermore welcome to the first video for Unit 4 of the AP Government curriculum 课程. This unit is all about how we as Americans develop our political beliefs 政治信仰, how we measure those beliefs, and then how we try to turn those beliefs into policy 政策. So in this video, we're going to start by talking about the core values 核心价值观 of Americans and how those affect the way we think about government and politics 政治. So if you're ready to get them brain cows milked, then oh baby, let's get to it. +

Okay, the objective 目标 for this video is as follows: explain the relationship between core beliefs of U.S. citizens and attitudes about the role of government 政府角色. Okay, now before we jump in, let me just give an honorable mention to 特别提及 my review packet 复习资料包. It's got exclusive videos 独家视频 that are not here on YouTube, and practice questions 练习题, and AP-style practice exams AP风格模拟考试, and basically everything you need to succeed in your class and do well on the exam. So if that's something you're into, you know, get your finger out and follow the link in the description 描述栏链接. +

Okay, so the core beliefs of Americans -- what are they? Well, as hard as it is to say every American believes in the same things, the following five values are generally shared by Americans of all stripes 各阶层的美国人: individualism 个人主义, equality of opportunity 机会平等, free enterprise 自由企业制度, rule of law 法治, and limited government 有限政府. Let me just define each of those quickly. +

Individualism 个人主义 is a value that places emphasis on 强调 self-reliance 自力更生 and independence 独立. Americans in general are less community-oriented 集体导向的 compared to various Eastern cultures which put community above the individual. No, here in America, it's the big cheese 重要人物 or no cheese, as nobody says. +

Equality of opportunity 机会平等 means that we believe that every American, regardless of 不管 their race 种族, ethnicity 民族, sex 性别, religion 宗教, or whatever, deserves equal footing 平等的地位 to go after life, liberty, and the pursuit of happiness 追求幸福. We believe that there are, or at least ought not be, special classes 特殊阶层 or hierarchies 等级制度 amongst us. We are not a people born with saddles on our backs, bent low for an aristocracy 贵族 to ride upon us with boots and spurs 马刺. +

Okay, then we have free enterprise 自由企业制度, which is a value that has to do with 与…有关 the government's intervention 干预 into the economy 经济. In general, Americans like it laissez-faire style 自由放任模式, which means that we want as little government intervention in the economy as possible. We get all giddy 兴奋的 when we're talking about the free market 自由市场 and the forces of supply and demand 供求关系. +

Fourth, we have the rule of law 法治. This means that we believe every citizen is equal under the law 法律面前人人平等 -- no one has any special privileges 特权. There's our boy John Adams, second president of the United States, who, summarizing various classical writers, said that ours is a government of laws, not of men 我们是法治政府，而非人治政府. In other words, from a poor farmer all the way up to the president, no one gets special treatment under the law. +

And fifth, we have the value of limited government 有限政府. This is a government whose limits are well defined 明确界定 and is restrained 约束 through the separation of powers 权力分立 in the system of checks and balances 制衡制度. +

Okay, so when I was listing all those out and defining them, you probably nodded along if you're an American because those are values that are baked into our DNA 融入我们的基因. But if you were paying attention, you were probably also going, "Well, yeah, but why?" Because even though many Americans agree on these values in principle 原则上, there are various competing interpretations 相互矛盾的解释 of them. +

Now it would be far beyond the scope of this video to outline all the competing interpretations, but for our purposes, it'll be enough to know how the interpretations of these values differ between conservatives 保守派 and liberals 自由派. And first, a definition of both is in order 有必要先定义一下. +

Conservatives 保守派 in general are those who cherish 珍视 established institutions 既定制度 and seek to preserve 维护 them for the good of society 社会利益. And that's why they're called conservatives -- they want to conserve 保存 the good things that have already been established. Anything that threatens to overturn 颠覆 those institutions is seen as a threat. Therefore, conservatives tend to emphasize 强调 smaller government which provides fewer services to the public 向公众提供较少服务. +

Liberals 自由派 in general are those who push for 推动 new reforms 改革 in order to make society more just and equitable 公平公正. And that's why they're called liberals, which is another word for free 自由. If conservatives want to tighten the reins on 控制 change in society, liberals want to let the reins out 放松控制, as long as those changes are going in the direction of increased justice and equity for all. +

So to illustrate 举例说明 this, let me just give you an example. During the women's rights movement 女权运动 in the 1960s and 1970s, women called for 呼吁 equal rights with men 与男性平等的权利. They wanted equal pay for equal work 同工同酬, for example, and no discrimination based on their sex 性别歧视 when it came to seeking jobs. Now conservatives, when they opposed this, did so for many reasons, but chief among them 其中最主要的是 was that encouraging women to work outside the home would destroy the traditional family structure 传统家庭结构 in which the man worked and the wife stayed home. So conservatives wanted to conserve the nuclear family structure 核心家庭结构 that had become standard among middle and upper classes in the 1950s. +

On the other hand, liberals saw this change as empowering to women 赋予女性权力 and breaking down 打破 unjust social structures 不公正的社会结构 that limited women's opportunities, and so they wanted to let the reins out on this one. So you can see, based on one little example, how conservatives and liberals view the world differently. +

Okay, now let's see how each of those sides interprets 解释 the five values that I listed earlier. When it comes to 关于 individualism, conservatives hold to 坚持 what's called self-centered individualism 以自我为中心的个人主义, which emphasizes the interest of the individual above the interests of society 个人利益高于社会利益. Liberals hold to what's called enlightened individualism 开明的个人主义, which emphasizes the interests of society above the interest of the individual 社会利益高于个人利益. +

So in the 1960s when President Lyndon Johnson was rolling out 推出 the Great Society programs 伟大社会计划 -- a chief component of which was the War on Poverty 向贫困宣战 -- conservatives hated it because it took taxpayer money 纳税人的钱 and redistributed 重新分配 it to the impoverished 贫困人口. That of course is a violation of 违反 self-centered individualism. Liberals on the other hand loved it because they believe that a government ought to take care of its poor 照顾穷人, even if it's at the expense of 以…为代价 those who have more. +

When it comes to equality of opportunity, conservatives believe in the power of meritocracy 精英统治制度, which is to say everyone rises in America based on their own toil and sweat 靠自己的辛勤劳动, and that's what conservatives would call the American dream 美国梦 -- everyone, no matter who you are, can make it 成功 as long as they work hard enough. Liberals on the other hand do agree with the idea of a meritocracy, but they believe that not all groups start that climb in the same place. +

So think about it like a race. Conservatives say that everyone ought to start at the same place, and whoever finishes first got there because they worked hard; they finished last, that's because they're lazy and they didn't work. Liberals would say, "Wait a minute, we're all starting at the starting line, but half of us have broken legs 有残疾的；处于不利地位的. Therefore, if it's going to be fair, the ones with the broken legs need to start closer to the end." Now I'm already getting myself into trouble with an explanation like that. Conservatives would probably look at them and say, "No, those aren't broken legs," and the liberals will say, "Yes they are." +

Now when it comes to free enterprise, conservatives want the government to stay out of the affairs of 不干涉 businesses and just let the free market determine what's best. Liberals on the other hand want the government to intervene with appropriate regulations 适当监管 to ensure the safety and equality of the workplace 工作场所的安全和平等. The classic example of this dichotomy 二分法；分歧 is how two different presidents approached the Great Depression 大萧条. The conservative Herbert Hoover, when the Great Depression began, basically just said, "You know, the market's going to correct itself eventually 最终自我修正, let's not intervene." But when liberal Franklin Roosevelt replaced him, he got busy quick, fast, in a hurry getting the government way involved in correcting the economy 大力干预经济复苏. +

All right, now when it comes to the rule of law, conservatives tend to see the laws themselves as embodying equality 体现平等, and therefore they emphasize the letter of the law 法律条文. Liberals in many cases agree that laws embody equality, but they emphasize the unequal application of those laws 法律的不平等适用, especially with regards to 关于 minority groups 少数群体. For example, consider the Civil Rights Act of 1964 1964年民权法案, which basically outlawed 禁止 all discrimination based on race, ethnicity, and gender 基于种族、民族和性别的歧视. Conservatives would say, "Look, we passed the law, and that embodies equality for everyone." Liberals would say, "Yeah, well we passed the law, but due to its unequal application, minorities are still not equal." +

And finally, when it comes to the value of limited government, conservatives want to define strong boundaries of federalism 联邦制的明确界限, which leads to less government interference with 减少政府对…的干涉 people's lives. Liberals, to a much greater degree, embrace the need for government intervention in society for the sake of the greater good 为了更大的利益. +

So yeah, all in all 总而言之, Americans agree that these five values are things that we all believe in, but depending on whether you're talking to a conservative or liberal, you will get a very different interpretation of those values. +

Okay, thanks for watching. Click right here to grab my ultimate review packet 终极复习资料包, which has everything you need to get an A in your class and a five on your exam in May. If this video helped you and you want me to keep making them, then by all means subscribe 订阅 and I shall oblige 照办. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史课程，此外，欢迎来到美国大学预修课程（AP）政府课程第四单元的第一个视频。这个单元主要讲述我们作为美国人是如何形成我们的政治信仰的，我们如何衡量这些信仰，以及我们如何努力将这些信仰转化为政策。所以在这个视频中，我们首先要讨论美国人的核心价值观，以及这些价值观是如何影响我们对政府和政治的看法的。所以，如果你准备好汲取知识，那么，宝贝，我们开始吧。 +

好的，这个视频的目标如下：解释美国公民的核心信仰与对政府角色的态度之间的关系。好的，在我们深入探讨之前，我要特别提一下我的复习资料包。它包含了一些在YouTube上没有的独家视频、练习题以及美国大学预修课程（AP）风格的模拟考试，基本上包含了你在课堂上取得成功以及在考试中取得好成绩所需要的一切。所以，如果你对此感兴趣，那么，行动起来，点击描述中的链接。 +

好的，那么美国人的核心信仰是什么呢？嗯，尽管很难说每个美国人都持有相同的信仰，但以下五个价值观是不同类型的美国人普遍共有的：个人主义、机会平等、自由企业、法治和有限政府。我快速地解释一下每一个价值观。 +

个人主义是一种强调自力更生和独立的价值观。与各种将集体置于个人之上的东方文化相比，一般来说，美国人的集体导向性较弱。不，在美国这里，就像没人会说的那样，要么做老大，要么一事无成。 +

机会平等意味着我们认为每个美国人，无论他们的种族、民族、性别、宗教或其他方面如何，都应该有平等的机会去追求生命、自由和幸福。我们认为，在我们当中不存在，或者至少不应该存在特殊的阶级或等级制度。我们不是那种生来就背上有鞍，甘愿被贵族用靴子和马刺骑在身上的人。 +

好的，接下来是自由企业，这是一种与政府对经济的干预有关的价值观。一般来说，美国人喜欢自由放任的方式，这意味着我们希望政府对经济的干预尽可能少。当我们谈论自由市场以及供求力量时，我们会非常兴奋。 +

第四，是法治。这意味着我们相信每个公民在法律面前都是平等的——没有人享有任何特权。美国第二任总统约翰·亚当斯（John Adams）总结了各种古典作家的观点，他说我们的政府是法治政府，而不是人治政府。换句话说，从一个贫穷的农民到总统，在法律面前没有人能得到特殊待遇。 +

第五，是有限政府的价值观。这是一个其权力界限明确，并通过制衡体系中的权力分立来加以约束的政府。 +

好的，所以当我列出并定义这些价值观时，如果你是美国人，你可能会点头认同，因为这些价值观已经融入了我们的基因。但如果你留意的话，你可能也会问：“好吧，但是为什么呢？” 因为即使许多美国人在原则上认同这些价值观，但对这些价值观存在各种不同的解读。 +

现在，要在这个视频中概述所有不同的解读远远超出了其范围，但就我们的目的而言，了解保守派和自由派在对这些价值观的解读上的差异就足够了。首先，我们来给这两个群体下定义。 +

一般来说，保守派是那些珍视既定制度，并为了社会的利益而努力维护这些制度的人。这就是为什么他们被称为保守派——他们想要保留已经建立起来的好东西。任何威胁要推翻这些制度的事物都被视为一种威胁。因此，保守派倾向于强调小政府，这种政府为公众提供的服务较少。 +

一般来说，自由派是那些推动新改革，以使社会更加公正和平等的人。这就是为什么他们被称为自由派，“自由” 是 “liberal” 的另一种说法。如果保守派想要对社会变革加以限制，自由派则希望放宽限制，只要这些变革朝着为所有人增加公正和平等的方向发展。 +

所以，为了说明这一点，我给你举个例子。在20世纪60年代和70年代的妇女权利运动中，女性呼吁与男性享有平等权利。例如，她们希望同工同酬，并且在求职时不受性别歧视。现在，保守派反对这一点有很多原因，但其中最主要的原因是，鼓励女性走出家庭工作会破坏传统的家庭结构，在这种结构中，男性工作，妻子待在家里。所以保守派想要保留在20世纪50年代成为中上层阶级标准的核心家庭结构。 +

另一方面，自由派认为这种变革能赋予女性权力，并打破限制女性机会的不公正社会结构，所以他们希望在这个问题上放宽限制。所以你可以看到，基于这一个小例子，保守派和自由派看待世界的方式是不同的。 +

好的，现在让我们看看双方是如何解读我之前列出的这五个价值观的。当涉及到个人主义时，保守派坚持所谓的以自我为中心的个人主义，这种个人主义强调个人利益高于社会利益。自由派则坚持所谓的开明个人主义，这种个人主义强调社会利益高于个人利益。 +

所以在20世纪60年代，林登·约翰逊（Lyndon Johnson）总统推出 “伟大社会” 计划时——该计划的一个主要组成部分是 “向贫困宣战”——保守派讨厌这个计划，因为它使用纳税人的钱，并将其重新分配给贫困人口。当然，这违反了以自我为中心的个人主义。另一方面，自由派喜欢这个计划，因为他们认为政府应该照顾穷人，即使这是以牺牲富人的利益为代价。 +

当涉及到机会平等时，保守派相信精英统治的力量，也就是说，在美国，每个人都可以通过自己的辛勤努力取得成功，这就是保守派所说的美国梦——每个人，无论你是谁，只要足够努力都能成功。另一方面，自由派也认同精英统治的理念，但他们认为并非所有群体都是从同一个起点开始攀登的。 +

所以可以把它想象成一场比赛。保守派说每个人都应该从同一个地方起跑，谁先到达终点是因为他们努力工作；谁最后到达，是因为他们懒惰，没有努力。自由派会说：“等一下，我们都站在起跑线上，但我们中有一半人腿是断的。因此，如果要公平的话，腿断的人需要从更靠近终点的地方起跑。” 我这样解释可能会给自己惹麻烦。保守派可能会看着他们说：“不，那些腿没断”，而自由派会说：“断了就是断了”。 +

当涉及到自由企业时，保守派希望政府不干涉企业事务，让自由市场来决定什么是最好的。另一方面，自由派希望政府通过适当的监管进行干预，以确保工作场所的安全和平等。这种二分法的经典例子是两位不同的总统对大萧条的处理方式。保守派赫伯特·胡佛（Herbert Hoover）在大萧条开始时基本上说：“你知道，市场最终会自我修正的，我们不要干预。” 但是当自由派富兰克林·罗斯福（Franklin Roosevelt）接替他时，他迅速采取行动，让政府深度参与纠正经济问题。 +

好的，现在当涉及到法治时，保守派倾向于认为法律本身就体现了平等，因此他们强调法律条文。在很多情况下，自由派也认同法律体现了平等，但他们强调法律在应用上的不平等，尤其是对少数群体而言。例如，考虑1964年的《民权法案》，该法案基本上禁止了基于种族、民族和性别的所有歧视。保守派会说：“看，我们通过了这项法律，它体现了对每个人的平等。” 自由派会说：“是的，我们通过了这项法律，但由于其不平等的应用，少数群体仍然没有实现平等。” +

最后，当涉及到有限政府的价值观时，保守派希望明确联邦制的强大界限，这会导致政府对人们生活的干预更少。而自由派在很大程度上认为，为了更大的利益，政府有必要对社会进行干预。 +

所以，总的来说，美国人都认同这五个价值观是我们共同相信的东西，但根据你是在和保守派还是自由派交流，你会得到对这些价值观截然不同的解读。 +

好的，感谢观看。点击这里获取我的终极复习资料包，它包含了你在课堂上得A以及在五月份的考试中得5分所需要的一切。如果这个视频对你有帮助，并且你希望我继续制作这样的视频，那么一定要订阅，我会照做的。海姆勒（Heimler）下线。 + 

'''

== pure

Hey there, and welcome back to Heimler's History, and furthermore welcome to the first video for Unit 4 of the AP Government curriculum. This unit is all about how we as Americans develop our political beliefs, how we measure those beliefs, and then how we try to turn those beliefs into policy. So in this video, we're going to start by talking about the core values of Americans and how those affect the way we think about government and politics. So if you're ready to get them brain cows milked, then oh baby, let's get to it.

Okay, the objective for this video is as follows: explain the relationship between core beliefs of U.S. citizens and attitudes about the role of government. Okay, now before we jump in, let me just give an honorable mention to my review packet. It's got exclusive videos that are not here on YouTube, and practice questions, and AP-style practice exams, and basically everything you need to succeed in your class and do well on the exam. So if that's something you're into, you know, get your finger out and follow the link in the description.

Okay, so the core beliefs of Americans -- what are they? Well, as hard as it is to say every American believes in the same things, the following five values are generally shared by Americans of all stripes: individualism, equality of opportunity, free enterprise, rule of law, and limited government. Let me just define each of those quickly.

Individualism is a value that places emphasis on self-reliance and independence. Americans in general are less community-oriented compared to various Eastern cultures which put community above the individual. No, here in America, it's the big cheese or no cheese, as nobody says.

Equality of opportunity means that we believe that every American, regardless of their race, ethnicity, sex, religion, or whatever, deserves equal footing to go after life, liberty, and the pursuit of happiness. We believe that there are, or at least ought not be, special classes or hierarchies amongst us. We are not a people born with saddles on our backs, bent low for an aristocracy to ride upon us with boots and spurs.

Okay, then we have free enterprise, which is a value that has to do with the government's intervention into the economy. In general, Americans like it laissez-faire style, which means that we want as little government intervention in the economy as possible. We get all giddy when we're talking about the free market and the forces of supply and demand.

Fourth, we have the rule of law. This means that we believe every citizen is equal under the law -- no one has any special privileges. There's our boy John Adams, second president of the United States, who, summarizing various classical writers, said that ours is a government of laws, not of men. In other words, from a poor farmer all the way up to the president, no one gets special treatment under the law.

And fifth, we have the value of limited government. This is a government whose limits are well defined and is restrained through the separation of powers in the system of checks and balances.

Okay, so when I was listing all those out and defining them, you probably nodded along if you're an American because those are values that are baked into our DNA. But if you were paying attention, you were probably also going, "Well, yeah, but why?" Because even though many Americans agree on these values in principle, there are various competing interpretations of them.

Now it would be far beyond the scope of this video to outline all the competing interpretations, but for our purposes, it'll be enough to know how the interpretations of these values differ between conservatives and liberals. And first, a definition of both is in order.

Conservatives in general are those who cherish established institutions and seek to preserve them for the good of society. And that's why they're called conservatives -- they want to conserve the good things that have already been established. Anything that threatens to overturn those institutions is seen as a threat. Therefore, conservatives tend to emphasize smaller government which provides fewer services to the public.

Liberals in general are those who push for new reforms in order to make society more just and equitable. And that's why they're called liberals, which is another word for free. If conservatives want to tighten the reins on change in society, liberals want to let the reins out, as long as those changes are going in the direction of increased justice and equity for all.

So to illustrate this, let me just give you an example. During the women's rights movement in the 1960s and 1970s, women called for equal rights with men. They wanted equal pay for equal work, for example, and no discrimination based on their sex when it came to seeking jobs. Now conservatives, when they opposed this, did so for many reasons, but chief among them was that encouraging women to work outside the home would destroy the traditional family structure in which the man worked and the wife stayed home. So conservatives wanted to conserve the nuclear family structure that had become standard among middle and upper classes in the 1950s.

On the other hand, liberals saw this change as empowering to women and breaking down unjust social structures that limited women's opportunities, and so they wanted to let the reins out on this one. So you can see, based on one little example, how conservatives and liberals view the world differently.

Okay, now let's see how each of those sides interprets the five values that I listed earlier. When it comes to individualism, conservatives hold to what's called self-centered individualism, which emphasizes the interest of the individual above the interests of society. Liberals hold to what's called enlightened individualism, which emphasizes the interests of society above the interest of the individual.

So in the 1960s when President Lyndon Johnson was rolling out the Great Society programs -- a chief component of which was the War on Poverty -- conservatives hated it because it took taxpayer money and redistributed it to the impoverished. That of course is a violation of self-centered individualism. Liberals on the other hand loved it because they believe that a government ought to take care of its poor, even if it's at the expense of those who have more.

When it comes to equality of opportunity, conservatives believe in the power of meritocracy, which is to say everyone rises in America based on their own toil and sweat, and that's what conservatives would call the American dream -- everyone, no matter who you are, can make it as long as they work hard enough. Liberals on the other hand do agree with the idea of a meritocracy, but they believe that not all groups start that climb in the same place.

So think about it like a race. Conservatives say that everyone ought to start at the same place, and whoever finishes first got there because they worked hard; they finished last, that's because they're lazy and they didn't work. Liberals would say, "Wait a minute, we're all starting at the starting line, but half of us have broken legs. Therefore, if it's going to be fair, the ones with the broken legs need to start closer to the end." Now I'm already getting myself into trouble with an explanation like that. Conservatives would probably look at them and say, "No, those aren't broken legs," and the liberals will say, "Yes they are."

Now when it comes to free enterprise, conservatives want the government to stay out of the affairs of businesses and just let the free market determine what's best. Liberals on the other hand want the government to intervene with appropriate regulations to ensure the safety and equality of the workplace. The classic example of this dichotomy is how two different presidents approached the Great Depression. The conservative Herbert Hoover, when the Great Depression began, basically just said, "You know, the market's going to correct itself eventually, let's not intervene." But when liberal Franklin Roosevelt replaced him, he got busy quick, fast, in a hurry getting the government way involved in correcting the economy.

All right, now when it comes to the rule of law, conservatives tend to see the laws themselves as embodying equality, and therefore they emphasize the letter of the law. Liberals in many cases agree that laws embody equality, but they emphasize the unequal application of those laws, especially with regards to minority groups. For example, consider the Civil Rights Act of 1964, which basically outlawed all discrimination based on race, ethnicity, and gender. Conservatives would say, "Look, we passed the law, and that embodies equality for everyone." Liberals would say, "Yeah, well we passed the law, but due to its unequal application, minorities are still not equal."

And finally, when it comes to the value of limited government, conservatives want to define strong boundaries of federalism, which leads to less government interference with people's lives. Liberals, to a much greater degree, embrace the need for government intervention in society for the sake of the greater good.

So yeah, all in all, Americans agree that these five values are things that we all believe in, but depending on whether you're talking to a conservative or liberal, you will get a very different interpretation of those values.

Okay, thanks for watching. Click right here to grab my ultimate review packet, which has everything you need to get an A in your class and a five on your exam in May. If this video helped you and you want me to keep making them, then by all means subscribe and I shall oblige. Heimler out.

'''

