
= 4.03 CHANGES in IDEOLOGY
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History. Now I've been going through Unit 4 of the AP Government curriculum 课程, and in this video that means it's time to talk about how our political beliefs 政治信仰 change as a result of generational and life cycle effects 代际和生命周期效应. So if you're ready to get them brain cows milked, then let's get to it. +

So in this video, here is what we're trying to do: explain how cultural factors 文化因素 influence political attitudes 政治态度 and socialization 社会化. If you saw the last video, we talked about the six main factors that influenced the way we come to hold differing political opinions 政治观点, and the term for that is political socialization 政治社会化. And we mentioned families, schools, peers 同龄人, media 媒体, civic and religious organizations 公民和宗教组织, and globalization 全球化. All of those factors affect the kinds of political opinions that we hold. +

So now let's talk about another factor that influences political ideology 政治意识形态, namely a person's generation 代际, and we'll talk about life cycle effects 生命周期效应, which can cause a person to change or modify 改变或调整 his or her political opinions. So let's begin with generational effects 代际效应. This basically means that a person's voting behavior 投票行为 and political ideology is very much influenced by the generation into which they're born. +

So let's briefly consider four major generations that are consistently analyzed by political scientists 政治学家, namely the Silent Generation 沉默的一代, Baby Boomers 婴儿潮一代, Generation X X一代, and Millennials 千禧一代. Now before I get into it, I should mention that everything I'm about to say here is a generalization 概括；归纳, and that in reality there is great variance 差异 of voting behavior and political ideology in each generation. But here we're only focusing on generalizations that can be made. +

So let's start with the Silent Generation, and this includes folks that were born before 1945. They came of age 成年 during the Great Depression 大萧条 and World War II 第二次世界大战, and many of them were young adults during the age of conformity 从众时代 during the 1950s. And as such, they tend to have a high value on 高度重视 religious belief 宗教信仰 and church attendance 参加教会活动. Furthermore, many folks of the Silent Generation adhered to 遵循 a social order 社会秩序 that attached rigid gender roles 严格的性别角色 to men and women. Thus, the folks in this generation are generally conservative 保守的. +

This leaning 倾向 led some of them to oppose the great cultural upheaval 文化剧变 in the 1960s with the counter-culture movement 反主流文化运动, the women's rights movement 女权运动, and the gay liberation movement 同性恋解放运动. After all, these movements tore apart 撕裂 the cultural fabric 文化结构 which these Silents grew up with. Now when it comes to foreign policy 外交政策, these people grew up in the midst of 在…之中 the Cold War 冷战, and thus generally supported American intervention abroad 美国海外干预 in order to stop the spread of communism 共产主义的传播, notably 尤其 in the Vietnam War 越南战争. +

Also, in general, the Silent Generation consistently votes for candidates who style themselves as 把自己塑造为 tough on crime and terrorism 对犯罪和恐怖主义采取强硬态度, which is generally a conservative position 保守立场. And one thing this generation can very much not understand is the push to legalize marijuana 大麻合法化. "Now why on God's green earth would you hippies 嬉皮士 want to legalize that wacky tobacco 古怪的烟草 anyway?" As a group, senior citizens 老年人 vote in higher numbers than any other group. +

Okay, now let's shift 转换话题 and talk about Baby Boomers 婴儿潮一代. These are folks who were born after World War II up till about the mid-60s. The prosperity 繁荣 of the 50s combined with men and women returning home from war meant that people were making babies like mad 拼命生孩子, and so this is a huge generation. They came of age during the tumultuous 动荡的 60s, and thus they learned to appreciate the changes better than their parents, and that meant they were slightly more liberal 更自由的 as a whole than the Silent Generation, though they still reliably voted conservative 保守派. +

Then came Generation X  X一代, who were born between the mid-60s and 1980s. These were folks who grew up with lots of divorce 离婚 and were the first to really use the internet as a generation. As a group, they were slightly more liberal than their parents in the Baby Boomer generation, partly because they're more ethnically diverse 种族更加多样化 than either of the two previous generations that I've spoken about. +

Then we get to the Millennials 千禧一代, who were born in the period 1981 to 1996, and this group is even more liberal than any of the previous generations that I've mentioned. Millennials are more ethnically diverse than Xers were, which is to say according to Pew Research 皮尤研究中心, about 40% of this group is not white, which is huge compared to the Silent Generation which was 79% white. As a result of this, Millennials have leaned hard into 大力支持 the liberal policies 自由政策 of the Democratic Party 民主党, and they're more likely than not to believe that racial discrimination 种族歧视 plays a big role in society. They're more favorable towards 更支持 immigrants 移民 than the previous generation, and in general they are more favorable towards what could be considered more socialist policies 社会主义政策 with significant government intervention 政府大规模干预. +

Now I spent all that time explaining some of these generational characteristics 代际特征 to you to make this point: the four generations of today's adults fit into a pretty tidy political pattern 政治模式. The older you are, the more likely you are conservative 保守的, and the younger you are, the more likely you are liberal 自由的. Since the Silent Generation, each succeeding generation 后续的每一代 has become more liberal than their parents. And a good example of this is a poll 民意调查 from Pew Research that compared each generation's opinion on conservative president Donald Trump's performance. You can see here that 46% of the conservative Silent Generation approved 支持, 44% of Boomers, 36% of Xers, and 20% of Millennials said that Trump was doing a good job. +

So classified into groups 分类, the four adult generations range from conservative to liberal 从保守到自由, and depending on what generation you find yourself in, you are more likely than not to agree with this group's political affinities 政治倾向. So all that to say, generational effects can determine how you think about politics. But there are also life cycle effects 生命周期效应 that contribute to 促成 political socialization 政治社会化 as well. And the idea here is that whatever stage of life a person is in will contribute to their political beliefs and behavior 政治信仰和行为. +

For example, if you were 18 years old and casting your first vote 投出第一张选票 during the 2020 presidential primaries 总统初选, you might have been very attracted to a candidate like Bernie Sanders who ran on a platform of 以…为竞选纲领 free college tuition 免费大学学费. At that stage in your life, that matters a lot to you, especially since college has gotten so expensive, and you're not interested in paying for your ceramics degree 陶瓷学位 until you're 73. But those in the Silent Generation who are not going to college and have adult children and grandchildren, they don't care as much about that, and they're thinking like, "Yeah, somebody has to pay for all of that." So they would in general be less attracted to that proposal 提议 because of where they are in their life. +

But then maybe you get married and you have kids, and at that stage in your life cycle 生命周期阶段, you're less interested in free college tuition than you are in pre-K legislation 学前教育立法 or lower taxes 减税 so you can better care for your family. And those commitments 责任；义务 might lead you to change your voting behavior 投票行为. So the point is, political socialization 政治社会化 happens as a result of your generational membership 所属代际, and it can change over time as you progress through different stages of life 随着人生阶段的推进. +

Okay, thanks for watching. Click right here to grab your review packet if you need help getting an A in your class and a five on your exam in May. If you're watching this and you're a Millennial -- and you probably are -- then you don't need me to tell you that subscribing 订阅 is the best way for you to let me know to keep making these videos. So I'll see you in the next one. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史课程。我们一直在学习美国大学预修课程（AP）政府课程的第四单元，在这个视频中，意味着是时候讨论我们的政治信仰如何因代际效应和生命周期效应而改变了。所以，如果你准备好汲取知识，那我们开始吧。 +

所以在这个视频中，我们要做的是：解释文化因素如何影响政治态度和政治社会化。如果你看过上一个视频，我们谈到了影响我们形成不同政治观点的六个主要因素，这个过程被称为政治社会化。我们提到了家庭、学校、同龄人、媒体、公民和宗教组织以及全球化。所有这些因素都影响着我们所秉持的政治观点。 +

所以现在让我们谈谈另一个影响政治意识形态的因素，也就是一个人的代际，并且我们会谈到生命周期效应，这种效应会导致一个人改变或调整他或她的政治观点。那么让我们从代际效应开始说起。这基本上意味着一个人的投票行为和政治意识形态在很大程度上受到他们出生的代际的影响。 +

所以让我们简要地考虑一下政治学家一直分析的四个主要代际，即沉默的一代（the Silent Generation）、婴儿潮一代（Baby Boomers）、X一代（Generation X）和千禧一代（Millennials）。在我深入探讨之前，我应该提到我在这里所说的一切都是一种概括，实际上，每一代的投票行为和政治意识形态都有很大差异。但在这里，我们只关注可以得出的一般性结论。 +

那么让我们从沉默的一代开始说起，这一代包括1945年之前出生的人。他们在大萧条和第二次世界大战期间成年，并且他们中的许多人在20世纪50年代从众的时代是年轻人。因此，他们往往非常重视宗教信仰和参加教堂活动。此外，沉默的一代中的许多人坚持一种给男性和女性附加了严格性别角色的社会秩序。因此，这一代的人通常是保守的。 +

这种倾向导致他们中的一些人反对20世纪60年代的重大文化动荡，包括反文化运动、妇女权利运动和同性恋解放运动。毕竟，这些运动撕裂了沉默的一代成长过程中所依赖的文化结构。当涉及到外交政策时，这些人在冷战期间长大，因此普遍支持美国的海外干预，以阻止共产主义的传播，特别是在越南战争中。 +

同样，一般来说，沉默的一代一直投票给那些标榜自己对犯罪和恐怖主义采取强硬态度的候选人，这通常是一种保守立场。这一代人非常不理解的一件事是推动大麻合法化。“说真的，你们这些嬉皮士为什么要让那种古怪的烟草合法化呢？” 作为一个群体，老年人的投票率比其他任何群体都高。 +

好的，现在让我们转而谈谈婴儿潮一代。这些人是在第二次世界大战后到大约20世纪60年代中期出生的人。20世纪50年代的繁荣，加上男性和女性从战争中返乡，意味着人们疯狂地生育，所以这是一个庞大的代际。他们在动荡的20世纪60年代成年，因此他们比他们的父母更能接受这些变化，这意味着作为一个整体，他们比沉默的一代稍微更自由一些，尽管他们仍然倾向于投票给保守派。 +

然后是X一代，他们出生于20世纪60年代中期到80年代之间。这一代人在父母大量离婚的环境中长大，并且是第一代真正使用互联网的人。作为一个群体，他们比婴儿潮一代的父母稍微更自由一些，部分原因是他们在种族上比我提到的前两代人更加多样化。 +

然后是千禧一代，他们出生于1981年到1996年期间，这一代人比我提到的任何前一代都更加自由。千禧一代在种族上比X一代更加多样化，也就是说，根据皮尤研究中心（Pew Research）的数据，这一群体中大约40% 不是白人，与沉默的一代中79% 是白人相比，这一比例是很大的。因此，千禧一代大力倾向于民主党的自由政策，并且他们更有可能相信种族歧视在社会中扮演着重要角色。他们比前一代更支持移民，并且一般来说，他们更倾向于那些可以被认为是具有重大政府干预的更社会主义的政策。 +

我花了这么多时间向你解释这些代际特征，是为了说明这一点：当今成年人的这四代人符合一个相当整齐的政治模式。你年龄越大，就越有可能是保守派；你年龄越小，就越有可能是自由派。自沉默的一代以来，每一代都比他们的父母更加自由。一个很好的例子是皮尤研究中心的一项民意调查，该调查比较了每一代对保守派总统唐纳德·特朗普（Donald Trump）表现的看法。你可以看到，46% 的保守的沉默的一代表示认可，婴儿潮一代中44% 的人、X一代中36% 的人以及千禧一代中20% 的人表示特朗普做得很好。 +

所以，按群体分类，这四代成年人从保守派到自由派不等，并且根据你所处的代际，你更有可能认同你所在群体的政治倾向。所以这么说吧，代际效应可以决定你对政治的看法。但也有生命周期效应也会对政治社会化产生影响。这里的观点是，一个人所处的人生阶段会影响他们的政治信仰和行为。 +

例如，如果你18岁，在2020年总统初选时进行首次投票，你可能会非常被伯尼·桑德斯（Bernie Sanders）这样的候选人吸引，他的竞选纲领包括免费的大学学费。在你人生的那个阶段，这对你来说很重要，特别是因为大学学费变得非常昂贵，而你不想在73岁之前为你的陶艺学位付费。但是沉默的一代中的那些不上大学并且有成年子女和孙子女的人，他们对此并不太在意，他们会想：“是啊，总得有人为这一切买单。” 所以，由于他们所处的人生阶段，他们一般对这个提议不太感兴趣。 +

但是，也许你结婚并有了孩子，在你人生的这个阶段，你对免费大学学费的兴趣不如对学前教育立法或降低税收的兴趣，这样你可以更好地照顾你的家庭。这些责任可能会导致你改变你的投票行为。所以重点是，政治社会化是由你所属的代际导致的，并且随着你经历不同的人生阶段，它会随着时间而改变。 +

好的，感谢观看。如果你需要帮助在课堂上得A，在五月份的考试中得5分，点击这里获取你的复习资料包。如果你正在观看这个视频并且你是千禧一代——很可能是这样——那么你不需要我告诉你，订阅是让我知道你希望我继续制作这些视频的最佳方式。所以我们下一个视频再见。海姆勒（Heimler）下线。 + 

'''

== pure

Hey there, and welcome back to Heimler's History. Now I've been going through Unit 4 of the AP Government curriculum, and in this video that means it's time to talk about how our political beliefs change as a result of generational and life cycle effects. So if you're ready to get them brain cows milked, then let's get to it.

So in this video, here is what we're trying to do: explain how cultural factors influence political attitudes and socialization. If you saw the last video, we talked about the six main factors that influenced the way we come to hold differing political opinions, and the term for that is political socialization. And we mentioned families, schools, peers, media, civic and religious organizations, and globalization. All of those factors affect the kinds of political opinions that we hold.

So now let's talk about another factor that influences political ideology, namely a person's generation, and we'll talk about life cycle effects, which can cause a person to change or modify his or her political opinions. So let's begin with generational effects. This basically means that a person's voting behavior and political ideology is very much influenced by the generation into which they're born.

So let's briefly consider four major generations that are consistently analyzed by political scientists, namely the Silent Generation, Baby Boomers, Generation X, and Millennials. Now before I get into it, I should mention that everything I'm about to say here is a generalization, and that in reality there is great variance of voting behavior and political ideology in each generation. But here we're only focusing on generalizations that can be made.

So let's start with the Silent Generation, and this includes folks that were born before 1945. They came of age during the Great Depression and World War II, and many of them were young adults during the age of conformity during the 1950s. And as such, they tend to have a high value on religious belief and church attendance. Furthermore, many folks of the Silent Generation adhered to a social order that attached rigid gender roles to men and women. Thus, the folks in this generation are generally conservative.

This leaning led some of them to oppose the great cultural upheaval in the 1960s with the counter-culture movement, the women's rights movement, and the gay liberation movement. After all, these movements tore apart the cultural fabric which these Silents grew up with. Now when it comes to foreign policy, these people grew up in the midst of the Cold War, and thus generally supported American intervention abroad in order to stop the spread of communism, notably in the Vietnam War.

Also, in general, the Silent Generation consistently votes for candidates who style themselves as tough on crime and terrorism, which is generally a conservative position. And one thing this generation can very much not understand is the push to legalize marijuana. "Now why on God's green earth would you hippies want to legalize that wacky tobacco anyway?" As a group, senior citizens vote in higher numbers than any other group.

Okay, now let's shift and talk about Baby Boomers. These are folks who were born after World War II up till about the mid-60s. The prosperity of the 50s combined with men and women returning home from war meant that people were making babies like mad, and so this is a huge generation. They came of age during the tumultuous 60s, and thus they learned to appreciate the changes better than their parents, and that meant they were slightly more liberal as a whole than the Silent Generation, though they still reliably voted conservative.

Then came Generation X, who were born between the mid-60s and 1980s. These were folks who grew up with lots of divorce and were the first to really use the internet as a generation. As a group, they were slightly more liberal than their parents in the Baby Boomer generation, partly because they're more ethnically diverse than either of the two previous generations that I've spoken about.

Then we get to the Millennials, who were born in the period 1981 to 1996, and this group is even more liberal than any of the previous generations that I've mentioned. Millennials are more ethnically diverse than Xers were, which is to say according to Pew Research, about 40% of this group is not white, which is huge compared to the Silent Generation which was 79% white. As a result of this, Millennials have leaned hard into the liberal policies of the Democratic Party, and they're more likely than not to believe that racial discrimination plays a big role in society. They're more favorable towards immigrants than the previous generation, and in general they are more favorable towards what could be considered more socialist policies with significant government intervention.

Now I spent all that time explaining some of these generational characteristics to you to make this point: the four generations of today's adults fit into a pretty tidy political pattern. The older you are, the more likely you are conservative, and the younger you are, the more likely you are liberal. Since the Silent Generation, each succeeding generation has become more liberal than their parents. And a good example of this is a poll from Pew Research that compared each generation's opinion on conservative president Donald Trump's performance. You can see here that 46% of the conservative Silent Generation approved, 44% of Boomers, 36% of Xers, and 20% of Millennials said that Trump was doing a good job.

So classified into groups, the four adult generations range from conservative to liberal, and depending on what generation you find yourself in, you are more likely than not to agree with this group's political affinities. So all that to say, generational effects can determine how you think about politics. But there are also life cycle effects that contribute to political socialization as well. And the idea here is that whatever stage of life a person is in will contribute to their political beliefs and behavior.

For example, if you were 18 years old and casting your first vote during the 2020 presidential primaries, you might have been very attracted to a candidate like Bernie Sanders who ran on a platform of free college tuition. At that stage in your life, that matters a lot to you, especially since college has gotten so expensive, and you're not interested in paying for your ceramics degree until you're 73. But those in the Silent Generation who are not going to college and have adult children and grandchildren, they don't care as much about that, and they're thinking like, "Yeah, somebody has to pay for all of that." So they would in general be less attracted to that proposal because of where they are in their life.

But then maybe you get married and you have kids, and at that stage in your life cycle, you're less interested in free college tuition than you are in pre-K legislation or lower taxes so you can better care for your family. And those commitments might lead you to change your voting behavior. So the point is, political socialization happens as a result of your generational membership, and it can change over time as you progress through different stages of life.

Okay, thanks for watching. Click right here to grab your review packet if you need help getting an A in your class and a five on your exam in May. If you're watching this and you're a Millennial -- and you probably are -- then you don't need me to tell you that subscribing is the best way for you to let me know to keep making these videos. So I'll see you in the next one. Heimler out.

'''

