
= 4.08 Ideology and POLICY MAKING
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 4 of the AP Government curriculum 课程, and in this video that means it's time to talk about how political ideologies 政治意识形态 affect policy making 政策制定. So if you're ready to get them brain cows milked, well then let's get to it. +

So in this video, here's what we're trying to do: explain how U.S. political culture 美国政治文化 -- for example, values 价值观, attitudes 态度, and beliefs 信仰 -- influences the formation 形成, goals 目标, and implementation 实施 of public policy 公共政策 over time. Or a simpler way to say it is this: how do our ideologies inform 影响 the kind of policy we make? +

If you'll remember in the last video, I talked about the differences between the characteristics 特点 of conservative 保守派的 and liberal ideology 自由派的意识形态, and I won't rehash 重复；赘述 that here. But for now, we just need to talk about how people who hold those ideologies get laws passed that reflect their beliefs. And probably it goes without saying 不言而喻, but hey, I'm going to say it anyway: that the policies that are made into law here in America reflect only the beliefs of the people who actually vote. All things being equal 在其他条件相同的情况下, if more people who hold liberal ideology vote, we're going to have more liberal policies, and vice versa 反之亦然 with conservative ideology. +

Okay, so with that established, let's consider two debates and two laws that illustrate 阐明 this point. First is the ongoing debate 持续的争论 over making English the official language 官方语言 of the United States. Just about every year, conservatives in Congress 国会 conservatives 保守派人士 propose 提议 such a policy, and every year it dies. Now conservatives want to do this because they believe it will unite Americans of all backgrounds 背景, and then additionally, they argue that such a law would save billions in federal and state spending 联邦和州政府开支. As it stands 目前的情况是, hospitals are mandated 强制；规定 to provide translators 翻译人员 for patients who need them, many schools must hire bilingual teachers and counselors 双语教师和辅导员, and some states spend millions out of their election budgets 选举预算 to print ballots 选票 in several languages. And it's true -- a nation's language is one of the most powerful cultural artifacts 文化产物 to bind people together 团结 in a shared heritage 共同的文化遗产. +

However, liberals reject 拒绝 the idea of making English the official language because they see it as a tool of oppression 压迫的工具 and in some cases straight up 完全地 racist 种族主义的. And precisely 恰恰 because language is such a powerful cultural artifact, liberals argue that to require immigrants 移民 to learn English at the expense of 以…为代价 their native language 母语 is tantamount to 等同于 an erasure 抹去 of their cultural heritage 文化遗产. Now this debate has been going on for decades, and it waxes and wanes 时强时弱 depending on -- not surprisingly -- the numbers of immigrants entering the nation. However, up till now it has been just a debate, and no official policy has been passed either way. But it is a good illustration of how ideology affects and informs policymaking 政策制定. +

The second debate is related to the first, namely the debate over multiculturalism 多元文化主义 versus 与…相对 assimilation 同化. The idea here is whether as Americans we should embrace 接受 multiculturalism, which values and upholds 维护 the distinct cultures 独特文化 of the people that live here, or whether there exists a normative 规范性的 set of American cultural values that all Americans should assimilate to 融入. And this debate has a long history, going all the way back to 追溯到 the U.S. policy concerning American Indians 美国印第安人政策. In many cases during the process of westward expansion 西进运动, American Indians were given the choice to be displaced from 被迫离开 their land or assimilate to American culture, which in those days meant to speak English, dress like Americans, and embrace Christianity 信奉基督教, etc., etc. And those debates are still happening today. Liberals tend to champion 支持 multiculturalism, while conservatives push for assimilation. And the crux 关键 of this debate is whether or not there are a set of universal normative American values by which every American should be measured 衡量. Conservatives tend to say yes, liberals tend to say no. +

Okay, those are two examples of ideological debates 意识形态争论 that have so far not resulted in concrete policy 具体政策. But now let's consider two examples of policies that illustrate how ideology makes its way into law 影响法律制定. First, on the conservative side, we can consider the Personal Responsibility and Work Opportunity Act of 1996 1996年个人责任与工作机会法案. This was a law addressing welfare policies 福利政策 which provided government funds to the poor. Ever since the policies of Lyndon Johnson's Great Society 林登·约翰逊的“伟大社会”计划, the welfare state 福利国家 in America was significantly expanded, and this was a triumph 胜利 for liberalism 自由主义. But starting in the 1980s, conservatives got all kinds of twitchy 不安的 about this legislation 立法 because, as they argued, the system of welfare trapped the poor in a cycle of poverty 贫困循环. The conservatives argued like this: if the poor were receiving welfare benefits 福利救济, they had no incentive 动力 to go to work, and that just means that they would sit at home while big daddy government paid all their bills. And so a Republican-dominated Congress 共和党主导的国会 passed the Personal Responsibility and Work Opportunity Act, which limited welfare payments to five years. And the result was that the numbers of those on welfare dropped precipitously 急剧下降, and conservatives considered this a win because to them it reasserted 重申 the American work ethic 职业道德. +

Now let's consider how liberal ideology resulted in legislation 立法, and for this we'll consider the DREAM Act 梦想法案, which addressed immigration 移民问题 and more specifically the situation of immigrants who entered the country illegally but were minors 未成年人 -- that means their parents immigrated illegally, but obviously the children had no choice in the matter 对此无能为力. The DREAM Act aimed to create a set of criteria 标准 through which those minors would not be deported 驱逐 but could become American citizens 美国公民. And initially 最初 this legislation was somewhat bipartisan 两党支持的, but not surprisingly it was more favored by liberal Democrats 自由派民主党人. The bill was introduced several times but it never passed. Republicans wanted stricter immigration limits in return for their cooperation 合作, but Democrats weren't willing to bend on that one 让步. But despite the failure of the bill, President Obama -- a Democrat -- took matters into his own hands 自行采取行动 and issued an executive order 行政命令 to address the situation. Basically, the executive order made the deportation of these immigrant minors impossible, and that essentially accomplished the same thing 达到同样的效果. But the problem with executive orders is that when there is a new executive, new orders can be made. Case in point 例如: President Trump, who styled himself tough on immigration 标榜自己对移民采取强硬态度, rescinded 撤销 this order and removed many of the protections offered in the DREAMers program 梦想者计划中的许多保护措施. +

So all in all 总而言之, you can see how ideology shapes 塑造 the kind of policy that we end up with 最终制定的政策, and that policy is always going to reflect the ideology of the people who actually vote. Okay, thanks for watching. Click right here to grab a review packet, which is going to help you get an A in your class and a five on your exam in May. No matter what your ideology, I want to keep making these videos to help you, so if that's what you want to, then you can cast your vote 投票；表示支持 by subscribing to the channel 订阅频道, and I shall oblige 照办. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史课程。我们一直在学习美国大学预修课程（AP）政府课程的第四单元，在这个视频中，意味着是时候讨论政治意识形态如何影响政策制定了。所以，如果你准备好汲取知识，那么我们开始吧。 +

所以在这个视频中，我们要做的是：解释美国的政治文化——例如价值观、态度和信仰——如何随着时间的推移影响公共政策的形成、目标和实施。或者更简单地说：我们的意识形态如何影响我们制定的政策类型？ +

如果你还记得上一个视频，我谈到了保守主义和自由主义意识形态的特点之间的差异，在这里我就不再赘述了。但现在，我们需要讨论持有这些意识形态的人如何使反映他们信仰的法律得以通过。也许这不言而喻，但不管怎样我还是要说：在美国，成为法律的政策只反映了实际投票的人的信仰。在其他条件相同的情况下，如果持有自由主义意识形态的人投票较多，我们将会有更多自由主义的政策，反之，保守主义意识形态的情况也是如此。 +

好的，既然已经明确了这一点，让我们考虑两个辩论和两项法律，它们说明了这一点。第一个是关于使英语成为美国官方语言的持续辩论。几乎每年，国会中的保守派都会提出这样的政策，但每年它都未能通过。保守派想要这样做是因为他们认为这将团结所有背景的美国人，此外，他们认为这样的法律将节省数十亿的联邦和州的开支。就目前的情况而言，医院被要求为有需要的病人提供翻译，许多学校必须聘请双语教师和辅导员，一些州从选举预算中花费数百万来用几种语言印制选票。而且确实，一个国家的语言是将人们团结在共同遗产中的最强大的文化产物之一。 +

然而，自由派拒绝使英语成为官方语言的想法，因为他们认为这是一种压迫的工具，在某些情况下简直就是种族主义。正是因为语言是如此强大的文化产物，自由派认为，要求移民以牺牲他们的母语为代价来学习英语，无异于抹去他们的文化遗产。这场辩论已经持续了几十年，并且随着进入这个国家的移民数量的变化而时起时落——这并不奇怪。然而，到目前为止，这只是一场辩论，无论哪种方式都没有官方政策得以通过。但这是意识形态如何影响和指导政策制定的一个很好的例证。 +

第二个辩论与第一个相关，即关于多元文化主义与同化的辩论。这里的观点是，作为美国人，我们是应该接受多元文化主义（它重视和维护居住在这里的人们的独特文化），还是存在一套规范的美国文化价值观，所有美国人都应该同化到这套价值观中。这场辩论有着悠久的历史，可以追溯到美国关于美洲印第安人的政策。在西进扩张的许多情况下，美洲印第安人被给予选择，要么离开他们的土地，要么同化到美国文化中，在那个时候，同化意味着说英语、穿得像美国人、信奉基督教等等。而且这些辩论在今天仍然存在。自由派倾向于支持多元文化主义，而保守派则推动同化。这场辩论的关键在于是否存在一套普遍的规范的美国价值观，每个美国人都应该以此来衡量自己。保守派倾向于认为存在，而自由派倾向于认为不存在。 +

好的，这些是两个意识形态辩论的例子，到目前为止这些辩论都没有产生具体的政策。但现在让我们考虑两个政策例子，它们说明了意识形态是如何融入法律的。首先，在保守派方面，我们可以看看1996年的《个人责任与工作机会法案》（Personal Responsibility and Work Opportunity Act）。这是一项解决福利政策的法律，它为穷人提供政府资金。自从林登·约翰逊（Lyndon Johnson）的“伟大社会”政策以来，美国的福利国家得到了显著扩展，这是自由主义的一个胜利。但从20世纪80年代开始，保守派对这项立法感到不安，因为他们认为，福利制度使穷人陷入了贫困循环。保守派这样认为：如果穷人接受福利救济，他们就没有工作的动力，这就意味着他们会坐在家里，而政府会支付他们所有的账单。所以由共和党主导的国会通过了《个人责任与工作机会法案》，该法案将福利支付限制在五年内。结果是接受福利救济的人数急剧下降，保守派认为这是一个胜利，因为对他们来说，这重申了美国的职业道德。 +

现在让我们看看自由主义意识形态是如何产生立法的，为此我们将考虑《梦想法案》（DREAM Act），该法案涉及移民问题，更具体地说，涉及非法进入该国但当时是未成年人的移民的情况——这意味着他们的父母非法移民，但显然孩子们在这件事情上别无选择。《梦想法案》旨在制定一套标准，根据这套标准，这些未成年人不会被驱逐，而是可以成为美国公民。最初，这项立法得到了两党的一定支持，但毫不奇怪，自由派民主党人更支持它。该法案被提出了几次，但从未通过。共和党人希望有更严格的移民限制作为他们合作的回报，但民主党人在这一点上不愿意让步。但是尽管该法案失败了，民主党总统奥巴马（Obama）采取了行动，发布了一项行政命令来解决这个问题。基本上，这项行政命令使得驱逐这些未成年移民变得不可能，这基本上达到了与法案相同的效果。但行政命令的问题在于，当有新的行政官员时，可能会发布新的命令。一个典型的例子是：自诩对移民采取强硬态度的特朗普（Trump）总统，撤销了这项行政命令，并取消了“梦想者”计划中提供的许多保护措施。 +

所以总的来说，你可以看到意识形态如何塑造我们最终制定的政策，并且政策总是会反映实际投票的人的意识形态。好的，感谢观看。点击这里获取复习资料包，它将帮助你在课堂上得A，在五月份的考试中得5分。无论你的意识形态是什么，我都想继续制作这些视频来帮助你，所以如果你希望这样，那么你可以通过订阅这个频道来表达你的支持，我会照做的。海姆勒（Heimler）下线。 + 

'''

== pure

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 4 of the AP Government curriculum, and in this video that means it's time to talk about how political ideologies affect policy making. So if you're ready to get them brain cows milked, well then let's get to it.

So in this video, here's what we're trying to do: explain how U.S. political culture -- for example, values, attitudes, and beliefs -- influences the formation, goals, and implementation of public policy over time. Or a simpler way to say it is this: how do our ideologies inform the kind of policy we make?

If you'll remember in the last video, I talked about the differences between the characteristics of conservative and liberal ideology, and I won't rehash that here. But for now, we just need to talk about how people who hold those ideologies get laws passed that reflect their beliefs. And probably it goes without saying, but hey, I'm going to say it anyway: that the policies that are made into law here in America reflect only the beliefs of the people who actually vote. All things being equal, if more people who hold liberal ideology vote, we're going to have more liberal policies, and vice versa with conservative ideology.

Okay, so with that established, let's consider two debates and two laws that illustrate this point. First is the ongoing debate over making English the official language of the United States. Just about every year, conservatives in Congress propose such a policy, and every year it dies. Now conservatives want to do this because they believe it will unite Americans of all backgrounds, and then additionally, they argue that such a law would save billions in federal and state spending. As it stands, hospitals are mandated to provide translators for patients who need them, many schools must hire bilingual teachers and counselors, and some states spend millions out of their election budgets to print ballots in several languages. And it's true -- a nation's language is one of the most powerful cultural artifacts to bind people together in a shared heritage.

However, liberals reject the idea of making English the official language because they see it as a tool of oppression and in some cases straight up racist. And precisely because language is such a powerful cultural artifact, liberals argue that to require immigrants to learn English at the expense of their native language is tantamount to an erasure of their cultural heritage. Now this debate has been going on for decades, and it waxes and wanes depending on -- not surprisingly -- the numbers of immigrants entering the nation. However, up till now it has been just a debate, and no official policy has been passed either way. But it is a good illustration of how ideology affects and informs policymaking.

The second debate is related to the first, namely the debate over multiculturalism versus assimilation. The idea here is whether as Americans we should embrace multiculturalism, which values and upholds the distinct cultures of the people that live here, or whether there exists a normative set of American cultural values that all Americans should assimilate to. And this debate has a long history, going all the way back to the U.S. policy concerning American Indians. In many cases during the process of westward expansion, American Indians were given the choice to be displaced from their land or assimilate to American culture, which in those days meant to speak English, dress like Americans, and embrace Christianity, etc., etc. And those debates are still happening today. Liberals tend to champion multiculturalism, while conservatives push for assimilation. And the crux of this debate is whether or not there are a set of universal normative American values by which every American should be measured. Conservatives tend to say yes, liberals tend to say no.

Okay, those are two examples of ideological debates that have so far not resulted in concrete policy. But now let's consider two examples of policies that illustrate how ideology makes its way into law. First, on the conservative side, we can consider the Personal Responsibility and Work Opportunity Act of 1996. This was a law addressing welfare policies which provided government funds to the poor. Ever since the policies of Lyndon Johnson's Great Society, the welfare state in America was significantly expanded, and this was a triumph for liberalism. But starting in the 1980s, conservatives got all kinds of twitchy about this legislation because, as they argued, the system of welfare trapped the poor in a cycle of poverty. The conservatives argued like this: if the poor were receiving welfare benefits, they had no incentive to go to work, and that just means that they would sit at home while big daddy government paid all their bills. And so a Republican-dominated Congress passed the Personal Responsibility and Work Opportunity Act, which limited welfare payments to five years. And the result was that the numbers of those on welfare dropped precipitously, and conservatives considered this a win because to them it reasserted the American work ethic.

Now let's consider how liberal ideology resulted in legislation, and for this we'll consider the DREAM Act, which addressed immigration and more specifically the situation of immigrants who entered the country illegally but were minors -- that means their parents immigrated illegally, but obviously the children had no choice in the matter. The DREAM Act aimed to create a set of criteria through which those minors would not be deported but could become American citizens. And initially this legislation was somewhat bipartisan, but not surprisingly it was more favored by liberal Democrats. The bill was introduced several times but it never passed. Republicans wanted stricter immigration limits in return for their cooperation, but Democrats weren't willing to bend on that one. But despite the failure of the bill, President Obama -- a Democrat -- took matters into his own hands and issued an executive order to address the situation. Basically, the executive order made the deportation of these immigrant minors impossible, and that essentially accomplished the same thing. But the problem with executive orders is that when there is a new executive, new orders can be made. Case in point: President Trump, who styled himself tough on immigration, rescinded this order and removed many of the protections offered in the DREAMers program.

So all in all, you can see how ideology shapes the kind of policy that we end up with, and that policy is always going to reflect the ideology of the people who actually vote. Okay, thanks for watching. Click right here to grab a review packet, which is going to help you get an A in your class and a five on your exam in May. No matter what your ideology, I want to keep making these videos to help you, so if that's what you want to, then you can cast your vote by subscribing to the channel, and I shall oblige. Heimler out.

'''

