
= 5.03 Political Parties
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 5 of the AP Government curriculum 课程, and in this video it's time to talk about political parties 政党. So if you're ready to get them brain cows milked linkage 联系 style, well then let's get to it. +

So in this video, we're going to try to do two things: describe linkage institutions 联系机构, and explain the function and impact of political parties on the electorate 选民 and government. So let's begin by talking about linkage institutions. +

A linkage institution is a societal structure 社会结构 that connects people to their government or the political process 政治进程. We often talk about how here in America we have a government by the people and for the people, but in case you haven't noticed, American citizens aren't jacked into the matrix 接入矩阵（俚语，意为直接连接到某种系统） so that their political preferences 政治偏好 are downloaded directly into a giant political mainframe 大型政治主机. Although maybe that would increase voter turnout 选民投票率... no, it's a terrible idea anyway. Short of straight download from our brains, how do our elected officials 当选官员 know what we want? How is it that we communicate with them and tell them "pass this law but don't pass that one"? Well, the answer is that we need mechanisms 机制 between us and our elected officials through which we can communicate with them, and those are called linkage institutions. These are structures that act as intermediaries 中介 between average people like you and me with the policy makers 政策制定者 in the federal, state, and local government. +

Now there are four linkage institutions that you need to know: political parties, interest groups 利益集团, elections 选举, and media 媒体. Each of these linkage institutions exist to allow we the people to communicate our preferences to policy makers. And since each of those are going to have its own video here in Unit 5, I'm only going to focus in this video on political parties as linkage institutions. +

So what is a political party? Well, it's pretty simple. A political party is an organization at least partially defined by a certain ideological belief 意识形态信仰 that puts forward candidates for election 推举候选人参加选举. Now in previous videos I covered the two major political parties in America and their ideological leanings 意识形态倾向, so here I'm just going to summarize: the Democratic Party 民主党 represents the more liberal ideology 自由派意识形态, while the Republican Party 共和党 represents a more conservative ideology 保守派意识形态. But whatever ideology each party holds to, the main goal for each party is to put forward candidates who will win elections. +

Now parties play a significant role in which candidates run for office 竞选公职 and in the drawing of legislative districts 划分立法选区 which ultimately benefit the candidates of the party. And like, the truth is anyone could run for office without the backing of a party, but as my southern brethren and sister 南方的兄弟姐妹们 are fond of saying 喜欢说, they're usually about as successful as a one-legged man in a butt-kicking contest （俚语，意为毫无成功希望）. +

Okay, so let's talk about what parties actually do. One of their first priorities 首要任务 is the mobilization and education of voters 动员和教育选民. The biggest goal any political party has, of course, is to win elections, and that means they have to expend a great deal of energy 花费大量精力 to get their party members and others who are sympathetic to their platform 支持其纲领的人 to the voting booth 投票站. To this end 为此, they can hold voter registration drives 选民登记活动 and even drive voters to the polls 投票站 who cannot otherwise drive themselves. And they do that by calling, emailing, texting, or showing up at people's doors and encouraging them to vote and educating them on their candidate's desirability 候选人的可取之处. During election seasons 选举季, parties organize huge canvassing campaigns 拉票活动. This is when a huge army of party volunteers calls people or shows up at people's homes with the goal of persuading people to vote for their candidate 说服人们投票给他们的候选人. If you've ever seen people with signs in their front yards endorsing a candidate 支持某位候选人, chances are that's a result of party canvassing effort 拉票努力的结果. +

The second thing parties do is write and publish a party platform 党纲. This is a formal set of principles and policy goals 原则和政策目标 written and endorsed by the party 由政党撰写并认可. In other words, the party platform lists the kind of policies the party will enact 制定 if their candidate is elected. Now if you read the platform of the Democratic Party, you're going to see lots of policies that reflect liberal ideology -- like universal healthcare 全民医保, rights for marginalized groups 边缘化群体的权利, and significant environmental regulations 严格的环境监管. If you read the platform for the Republican Party, you're going to see lots of policies that reflect conservative ideology -- like an America First foreign policy 美国优先外交政策, traditional family values 传统家庭价值观, and the deregulation of business 放松商业管制. So the platform is the party essentially saying like, "if this is the kind of America you want, then elect our candidates and we'll make it happen." +

Third, if parties are gonna win elections and implement their platform, then they need candidates who can win, and parties expend a great deal of energy finding quality candidates 优秀候选人. The ideal candidate for any party has a few characteristics 特点. First, a good candidate is likable 讨人喜欢的. Like, you know, nobody wants to elect a turd （俚语，无用之人）, so this is key. And you know, likable is very subjective 主观的. In 2016, Donald Trump polarized Americans 使美国民众两极分化 with his brash talk 鲁莽言论, especially around issues that were culturally taboo 文化禁忌 like immigration and race. However, there was clearly a large segment of the American population who found those qualities very likable. Second, a good candidate already has a significant following 大量追随者. Now a good following doesn't always equal the best candidate. For example, Abraham Lincoln was relatively unknown when he got the Republican nomination 共和党提名, and you know, I'd say he was a pretty decent president. And that leads me to the third qualification 条件 for a good candidate, namely that they can unite different segments of the party 团结党内不同派别. And that is why Abraham Lincoln ultimately earned the nomination -- he was able to unite the northern Democrats 北方民主党人 and the remainder of the Whig party 辉格党残余势力 and several other factions 派别. The fourth qualification for a good candidate is, ideally, money. As we'll see later in this unit, it's usually a metric buttload of hooch （俚语，大量的东西） that wins elections, not idealism 理想主义. And so a good candidate should be able to raise a bunch of money 筹集大量资金. +

Okay, now back to what parties do. The fourth thing that parties do is to provide campaign management support 竞选管理支持 for their candidates. Parties try to get their candidate elected by hosting fundraisers 举办筹款活动 and implementing targeted media strategies 实施有针对性的媒体策略 that are going to appeal to most voters 吸引大多数选民. And the party which does this best usually wins. +

So after all of that explanation, hopefully you can see how a political party acts as a linkage institution connecting average people like us to the political process 政治进程. Like, if you alone wanted to run a political campaign 开展政治竞选活动, you don't have that kind of money, you don't have the army of volunteers 志愿者队伍, you don't have the infrastructure 基础设施 to make that happen. But a party does. And so if you register with that party or even just align yourself with it 与它结盟, then the party links you to the political process. +

Okay, let me just say one last thing. Everything I've said so far about the influence of parties has been about the process before and during the election. But after a party's candidate is elected, the party continues to play a significant role. If you remember all the way back to Unit Two when we talked about Congress 国会, you'll remember that a politician's party membership 党派归属 determines committee chairs 委员会主席（supposing that they're in the majority party 假设他们属于多数党） and leadership roles in the legislature 立法机构中的领导角色 -- roles like Speaker of the House 众议院议长 and Senate majority and minority leaders 参议院多数党和少数党领袖. So the point is, political parties play a significant role in linking average Americans to the political process. +

Okay, thanks for watching. Click right here if you want to grab my review packet, which is going to help you get an A in your class and a five on your exam in May. If this video helps you and you want me to keep making them, then by all means subscribe 订阅 and I shall oblige 照办. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史频道。目前我们一直在学习美国大学预修课程（AP）政府课程的第五单元，在这个视频中，我们要谈谈政党。所以，如果你准备好以 “联动” 的方式激发自己的思维，那么我们就开始吧。 +

所以在这个视频中，我们要尝试做两件事：描述联动机构，并解释政党对选民和政府的功能与影响。那么我们先从谈论联动机构开始。 +

联动机构是一种将人民与他们的政府或政治进程联系起来的社会结构。我们经常说在美国我们拥有一个民有、民治的政府，但如果你没注意到的话，美国公民并没有接入某种系统，能把他们的政治偏好直接下载到一个巨大的政治主机中。虽然那样也许能提高选民投票率…… 不，不管怎样那都是个糟糕的主意。除了直接从我们的大脑中下载信息这种方式外，我们选出的官员要怎么知道我们想要什么呢？我们要如何与他们沟通并告诉他们 “通过这项法律，不要通过那项法律” 呢？嗯，答案是我们和我们选出的官员之间需要有一些机制，通过这些机制我们可以和他们交流，这些机制就叫做联动机构。这些机构是充当像你我这样的普通民众与联邦、州和地方政府的政策制定者之间的中介的结构。 +

现在有四种你需要知道的联动机构：政党、利益集团、选举和媒体。这些联动机构的存在是为了让我们人民能够将自己的偏好传达给政策制定者。由于在第五单元中每个联动机构都会有单独的视频讲解，在这个视频里我只关注作为联动机构的政党。 +

那么什么是政党呢？嗯，相当简单。政党是一个至少部分由某种意识形态信仰所定义的组织，这个组织会推举候选人参与选举。在之前的视频中我介绍过美国的两大政党以及它们的意识形态倾向，所以在这里我简单总结一下：民主党（Democratic Party）代表更偏向自由主义的意识形态，而共和党（Republican Party）代表更保守的意识形态。但不管每个政党秉持何种意识形态，每个政党的主要目标都是推举能够赢得选举的候选人。 +

现在，政党在决定哪些候选人参选以及划分立法选区方面扮演着重要角色，而划分选区最终是为了让本党的候选人受益。而且，事实上任何人都可以在没有政党支持的情况下参选，但就像我的南方兄弟姐妹们喜欢说的那样，没有政党支持的人在选举中通常就像一个独腿的人参加踢人比赛一样，成功的可能性微乎其微。 +

好的，那我们来谈谈政党实际做些什么。它们的首要任务之一是动员和教育选民。当然，任何一个政党的最大目标都是赢得选举，这意味着它们必须花费大量精力让本党成员以及其他支持本党纲领的人去投票。为此，它们会组织选民登记活动，甚至会开车送那些自己无法前往投票站的选民去投票。它们通过打电话、发电子邮件、发短信或者登门拜访的方式鼓励人们投票，并让人们了解本党候选人的优势。在选举季，政党会组织大规模的拉票活动。在拉票活动中，大批的政党志愿者会给人们打电话或者登门拜访，目的是说服人们投票给本党的候选人。如果你曾看到人们在前院挂着支持某个候选人的标牌，很可能这就是政党拉票活动的结果。 +

政党做的第二件事是撰写并公布政党纲领。政党纲领是一套由政党撰写并认可的正式原则和政策目标。换句话说，政党纲领列出了如果本党候选人当选，该党将实施的政策。如果你阅读民主党的纲领，你会看到许多反映自由主义意识形态的政策 —— 比如全民医保、对边缘化群体权利的保障以及严格的环境监管政策。如果你阅读共和党的纲领，你会看到许多反映保守主义意识形态的政策 —— 比如 “美国优先” 的外交政策、传统的家庭价值观以及对企业的放松管制。所以政党纲领本质上是政党在说：“如果你想要这样的美国，那就选举我们的候选人，我们会让它实现。” +

第三，如果政党想要赢得选举并实施其纲领，它们需要能赢得选举的候选人，而且政党会花费大量精力寻找优秀的候选人。任何一个政党的理想候选人都有几个特点。首先，一个好的候选人要讨人喜欢。你知道的，没人想选举一个糟糕的人，所以这一点很关键。而且，讨人喜欢是非常主观的。在2016年，唐纳德·特朗普（Donald Trump）因其鲁莽的言论使美国民众产生了分歧，尤其是在移民和种族等文化禁忌问题上。然而，显然有很大一部分美国民众觉得他的这些特质很讨人喜欢。其次，一个好的候选人已经有了大量的追随者。不过，有大量追随者并不一定意味着就是最好的候选人。例如，亚伯拉罕·林肯（Abraham Lincoln）在获得共和党提名时还相对不为人知，但我得说他是一位相当不错的总统。这就引出了一个好候选人的第三个条件，那就是他们能够团结党内不同的派别。这就是为什么亚伯拉罕·林肯最终获得了提名 —— 他能够团结北方民主党人、辉格党（Whig party）的剩余力量以及其他几个派别。一个好候选人的第四个条件，理想情况下，是要有钱。正如我们在本单元后面会看到的，通常赢得选举靠的是大量的资金，而不是理想主义。所以一个好的候选人应该能够筹集到大量资金。 +

好的，现在回到政党做的事情上。政党做的第四件事是为它们的候选人提供竞选管理支持。政党通过举办筹款活动以及实施有针对性的媒体策略来努力让本党的候选人当选，这些策略要能吸引大多数选民。而在这方面做得最好的政党通常会赢得选举。 +

在做了所有这些解释之后，希望你能明白政党是如何作为一种联动机构，将像我们这样的普通民众与政治进程联系起来的。比如说，如果你独自一人想要开展一场政治竞选活动，你没有那么多钱，没有大批的志愿者，也没有实现竞选的基础设施。但政党有。所以如果你加入某个政党，或者哪怕只是与某个政党结盟，那么这个政党就会把你与政治进程联系起来。 +

好的，我最后再说一点。到目前为止我所说的关于政党的影响都是关于选举前和选举期间的过程。但在一个政党的候选人当选之后，政党仍然发挥着重要作用。如果你还记得在第二单元我们谈论国会时的内容，你就会记得一个政治家的党派身份决定了他们是否能担任委员会主席（前提是他们属于多数党）以及在立法机构中的领导角色 —— 比如众议院议长（Speaker of the House）以及参议院多数党和少数党领袖。所以重点是，政党在将普通美国民众与政治进程联系起来方面扮演着重要角色。 +

好的，感谢观看。如果你想获取我的复习资料包，点击这里，它将帮助你在课堂上取得A的成绩，并在五月份的考试中获得5分。如果这个视频对你有帮助，并且你希望我继续制作这样的视频，那就一定要订阅，我会照办的。海姆勒，退出。 + 

'''

== pure

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 5 of the AP Government curriculum, and in this video it's time to talk about political parties. So if you're ready to get them brain cows milked linkage style, well then let's get to it.

So in this video, we're going to try to do two things: describe linkage institutions, and explain the function and impact of political parties on the electorate and government. So let's begin by talking about linkage institutions.

A linkage institution is a societal structure that connects people to their government or the political process. We often talk about how here in America we have a government by the people and for the people, but in case you haven't noticed, American citizens aren't jacked into the matrix so that their political preferences are downloaded directly into a giant political mainframe. Although maybe that would increase voter turnout... no, it's a terrible idea anyway. Short of straight download from our brains, how do our elected officials know what we want? How is it that we communicate with them and tell them "pass this law but don't pass that one"? Well, the answer is that we need mechanisms between us and our elected officials through which we can communicate with them, and those are called linkage institutions. These are structures that act as intermediaries between average people like you and me with the policy makers in the federal, state, and local government.

Now there are four linkage institutions that you need to know: political parties, interest groups, elections, and media. Each of these linkage institutions exist to allow we the people to communicate our preferences to policy makers. And since each of those are going to have its own video here in Unit 5, I'm only going to focus in this video on political parties as linkage institutions.

So what is a political party? Well, it's pretty simple. A political party is an organization at least partially defined by a certain ideological belief that puts forward candidates for election. Now in previous videos I covered the two major political parties in America and their ideological leanings, so here I'm just going to summarize: the Democratic Party represents the more liberal ideology, while the Republican Party represents a more conservative ideology. But whatever ideology each party holds to, the main goal for each party is to put forward candidates who will win elections.

Now parties play a significant role in which candidates run for office and in the drawing of legislative districts which ultimately benefit the candidates of the party. And like, the truth is anyone could run for office without the backing of a party, but as my southern brethren and sister are fond of saying, they're usually about as successful as a one-legged man in a butt-kicking contest.

Okay, so let's talk about what parties actually do. One of their first priorities is the mobilization and education of voters. The biggest goal any political party has, of course, is to win elections, and that means they have to expend a great deal of energy to get their party members and others who are sympathetic to their platform to the voting booth. To this end, they can hold voter registration drives and even drive voters to the polls who cannot otherwise drive themselves. And they do that by calling, emailing, texting, or showing up at people's doors and encouraging them to vote and educating them on their candidate's desirability. During election seasons, parties organize huge canvassing campaigns. This is when a huge army of party volunteers calls people or shows up at people's homes with the goal of persuading people to vote for their candidate. If you've ever seen people with signs in their front yards endorsing a candidate, chances are that's a result of party canvassing effort.

The second thing parties do is write and publish a party platform. This is a formal set of principles and policy goals written and endorsed by the party. In other words, the party platform lists the kind of policies the party will enact if their candidate is elected. Now if you read the platform of the Democratic Party, you're going to see lots of policies that reflect liberal ideology -- like universal healthcare, rights for marginalized groups, and significant environmental regulations. If you read the platform for the Republican Party, you're going to see lots of policies that reflect conservative ideology -- like an America First foreign policy, traditional family values, and the deregulation of business. So the platform is the party essentially saying like, "if this is the kind of America you want, then elect our candidates and we'll make it happen."

Third, if parties are gonna win elections and implement their platform, then they need candidates who can win, and parties expend a great deal of energy finding quality candidates. The ideal candidate for any party has a few characteristics. First, a good candidate is likable. Like, you know, nobody wants to elect a turd, so this is key. And you know, likable is very subjective. In 2016, Donald Trump polarized Americans with his brash talk, especially around issues that were culturally taboo like immigration and race. However, there was clearly a large segment of the American population who found those qualities very likable. Second, a good candidate already has a significant following. Now a good following doesn't always equal the best candidate. For example, Abraham Lincoln was relatively unknown when he got the Republican nomination, and you know, I'd say he was a pretty decent president. And that leads me to the third qualification for a good candidate, namely that they can unite different segments of the party. And that is why Abraham Lincoln ultimately earned the nomination -- he was able to unite the northern Democrats and the remainder of the Whig party and several other factions. The fourth qualification for a good candidate is, ideally, money. As we'll see later in this unit, it's usually a metric buttload of hooch that wins elections, not idealism. And so a good candidate should be able to raise a bunch of money.

Okay, now back to what parties do. The fourth thing that parties do is to provide campaign management support for their candidates. Parties try to get their candidate elected by hosting fundraisers and implementing targeted media strategies that are going to appeal to most voters. And the party which does this best usually wins.

So after all of that explanation, hopefully you can see how a political party acts as a linkage institution connecting average people like us to the political process. Like, if you alone wanted to run a political campaign, you don't have that kind of money, you don't have the army of volunteers, you don't have the infrastructure to make that happen. But a party does. And so if you register with that party or even just align yourself with it, then the party links you to the political process.

Okay, let me just say one last thing. Everything I've said so far about the influence of parties has been about the process before and during the election. But after a party's candidate is elected, the party continues to play a significant role. If you remember all the way back to Unit Two when we talked about Congress, you'll remember that a politician's party membership determines committee chairs (supposing that they're in the majority party) and leadership roles in the legislature -- roles like Speaker of the House and Senate majority and minority leaders. So the point is, political parties play a significant role in linking average Americans to the political process.

Okay, thanks for watching. Click right here if you want to grab my review packet, which is going to help you get an A in your class and a five on your exam in May. If this video helps you and you want me to keep making them, then by all means subscribe and I shall oblige. Heimler out.

'''

