
= 5.04 How and Why Political Parties CHANGE
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 5 of the AP Government curriculum 课程, and in this video it's time to talk about how political parties change over time and realign 重新调整 themselves to better reflect the attitudes and preferences 态度和偏好 of Americans. So if you're ready to get them brain cows milked, let's get to it. +

So here's our learning objective 学习目标 for this video: explain why and how political parties change and adapt 改变与适应. Okay, so in the last video we talked about how political parties act as linkage institutions 联系机构 that help average people engage in 参与 the political process. And in that video we had a look at the party platforms 党纲 for the Democratic and Republican parties. But those platforms and the way parties get their people elected have changed over time, so let's look at a few of those changes. +

First, the way parties interact with 与…互动 candidates has changed. It used to be that it was the party that mattered and the candidate was secondary 次要的, but now it's the candidate that matters and the party is secondary. A big part of this is new media technology 新媒体技术 which allows candidates to speak directly to their supporters and gather a following 追随者 around themselves. And that has had the effect of weakening 削弱 the party's role in nominating candidates 提名候选人. Now some people have criticized this new candidate-centered nomination process 以候选人为中心的提名程序 on account of 因为 it can lead to opposing factions 对立派别 within the party. But political scientists 政治学家 who have studied this have shown that certain candidates who build their own following can actually have a benefit to the party. And this is especially true of candidates who champion 支持 underrepresented opinions 代表性不足的观点 in the electorate 选民 -- like they have argued that even if the candidate doesn't win the nomination, their followers are still likely to engage in the political process of voting and supporting the winning candidate. +

Second, parties have changed their platforms over time in order to appeal to 吸引 a larger swath 一大片；大量 of the electorate. Now the changing platform will almost never contradict 与…矛盾 the larger ideology 意识形态 of the party -- like you're never going to hear the Republicans say, "You know a lot of people are saying that America was built on racism and that we ought to atone for 为…赎罪 those sins, so you know let's put it in the platform." You know, even if they don't contradict their ideology, parties have shifted emphasis 转移重点 in their platforms or even change their messaging 信息传达 in order to appeal to more voters. This is especially true when it comes to coalitions 联盟 of voters. +

Now a coalition is a demographic group 人口群体 -- like millennials 千禧一代 or retired persons 退休人员 or evangelical Christians 福音派基督徒 -- and if they vote as a block 作为一个团体投票, they can significantly alter 显著改变 the outcome of an election. Therefore, parties do everything they can to appeal to different coalitions. So when you see candidates giving speeches or debating other candidates, pay attention to the topics that they mention. There are a gajillion （非正式，极多的） things that they could talk about, but the topics that they choose say a lot about the coalitions that the politician is trying to win to his or her side. So if a candidate promises to uphold 支持 or even expand gun rights, they are appealing to a coalition mainly of conservative white males. On the other hand, if a candidate promises protections for immigrants and their families, they are appealing to America's large immigrant population. +

Okay, the third way parties have changed over time is by altering 改变 the entire party's structure 结构, and there are three main ways that this happens. First is party realignment 政党重组, and this is exactly what it sounds like -- the party realigns itself. And why would they do that? Well, usually this occurs after an election or a series of elections where the party is badly defeated. Like if the opposing party keeps winning and winning big, that is a sign to the losing party that their priorities compared to the general electorate's priorities are, to use the political science term, a wonky asset （政治学术语，不稳定因素）. +

So for example, the Democrats won big in the presidential elections of 1932 and 1936, as you can see here. This was in the midst of 在…期间 the Great Depression 大萧条, and while Republicans were criticizing Franklin Roosevelt's liberal policies 自由主义政策 and social programs to alleviate 减轻 the devastating effects 毁灭性影响 of the depression, apparently the average American was okay with it. "Okay, so should I uphold my principles or should I eat? Yeah, I'm gonna take a sandwich." And that led the Republican party to a major realignment of their future platforms and priorities. +

But realignment can also happen from the bottom up 自下而上. Now you'll recall that it was the Republican party with Abraham Lincoln at the helm 领导 that ultimately abolished slavery 废除奴隶制, and so for a long time much of the black American population were aligned with 与…结盟 the Republican party. However, starting in the 1920s, the Republicans' failure to pursue civil rights legislation 民权立法 on behalf of 代表 black Americans combined with the grinding poverty 极度贫困 caused by the Great Depression led a majority of black Americans to switch to 转向 the Democratic party, which had a lot going for it 有很多优势 in terms of alleviating poverty and fighting for civil rights -- at least more than the Republicans did. +

Okay, the second way party structure has changed is through changes to campaign finance laws 竞选资金法. Since the 1970s, campaign finance laws and Supreme Court decisions 最高法院裁决 have changed how much money can be lawfully given to candidates and parties. We're going to talk more about that in Topic 11, so I'm just going to leave it there for now. +

And the third way party structure has changed is because of changes in communication and data management technology 数据管理技术. As technology has advanced, so too has a party's ability to mine data 挖掘数据 on certain groups and use that data to win elections. I'm going to give you two examples, both from the 2012 presidential election. In that election, Republican candidate Mitt Romney's campaign developed what they called Project Orca 逆戟鲸计划, which was a web app 网络应用程序 which voters could use to let the campaign know that they voted. And so with this information, Romney's campaign could see in real time 实时地 the areas in which there was low voter turnout 选民投票率低, and they could engage in some last minute efforts 最后一刻的努力 to get those people to the polls 投票站. Hey, that sounds like a pretty good idea to me. But instead of being a killer whale 虎鲸, Project Orca turned out to be more like a beached whale 搁浅的鲸鱼 because the technology just didn't work. But whether it worked or not, the point is the thinking behind Project Orca was a massive shift 巨大转变 in how the party got their people to put their Doritos 多力多滋（一种零食） down, get off the couch, and go vote. +

Now Project Orca was in fact a response to Romney's opponent in that election, Barack Obama. Obama's campaign had developed some new technology under the name Project Narwhal 独角鲸计划. And just for poops and giggles （非正式，只是为了好玩）, you should know that the only natural predator 天敌 to the narwhal is the orca -- so you know, Romney, he's saucy （非正式，有趣的）. Anyway, Project Narwhal was a significant leap forward 重大进步 in canvassing techniques 拉票技巧. With this technology, Obama's campaign could target emails and text messages to people not only based on their demographics 人口统计数据 but also based on their psychographics 心理统计数据. Now demographics classify people according to their external traits 外部特征 -- like race, gender, age, and region. Psychographics, on the other hand, classify people according to their inner life 内心世界 -- like their personality, their attitudes, their aspirations 抱负, their desires 愿望. These traits explain why a voter votes the way that he or she does. You know, they can get this information from your online shopping habits 网上购物习惯 and the kinds of shows you watched, etc. As it turned out, Narwhal was far more successful than Orca. But again, who won and lost is less the emphasis here than on how this fundamentally changed how parties and campaigns try to convince people to vote. +

Okay, thanks for watching. Click right here to grab a review packet, which is going to help you get an A in your class and a five on your exam in May. Whether you're an Orca fan or a Narwhal fan, I got videos here on this channel for all. So if you want me to keep making them, then by all means subscribe 订阅 and I shall oblige 照办. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史频道。目前我们一直在学习美国大学预修课程（AP）政府课程的第五单元，在这个视频中，我们要谈谈政党是如何随着时间变化，以及如何调整自身以更好地反映美国人的态度和偏好的。所以，如果你准备好激发自己的思维，那我们就开始吧。 +

所以这个视频我们的学习目标是：解释政党为什么会改变以及如何改变和适应。好的，在上一个视频中我们谈到了政党是如何作为联动机构帮助普通民众参与政治进程的。在那个视频中，我们看了民主党（Democratic Party）和共和党（Republican Party）的政党纲领。但这些纲领以及政党让自己的人当选的方式随着时间已经发生了变化，所以我们来看看其中的一些变化。 +

首先，政党与候选人的互动方式发生了变化。过去，政党是重要的，候选人是次要的，但现在候选人是重要的，政党是次要的。其中很大一部分原因是新媒体技术，它让候选人能够直接与他们的支持者交流，并围绕自己聚集一批追随者。这产生了削弱政党在提名候选人方面作用的效果。现在有些人批评这种以候选人为中心的新提名过程，因为它可能会在党内导致对立的派别。但研究这个问题的政治学家表明，某些建立起自己追随者群体的候选人实际上对政党是有好处的。对于那些在选民中支持代表性不足观点的候选人来说尤其如此 —— 比如他们认为，即使候选人没有赢得提名，他们的追随者仍然可能参与投票的政治过程并支持获胜的候选人。 +

其次，政党随着时间改变了它们的纲领，以便吸引更广泛的选民群体。现在，变化后的纲领几乎永远不会与该党的主要意识形态相矛盾 —— 比如你永远不会听到共和党人说，“你知道很多人说美国是建立在种族主义之上的，我们应该为那些罪过赎罪，所以我们把这一点写进纲领里吧。” 你知道，即使纲领不与他们的意识形态相矛盾，政党也会在纲领中改变重点，甚至改变宣传内容，以吸引更多选民。在涉及选民联盟时尤其如此。 +

现在，联盟是一个人口群体 —— 比如千禧一代、退休人员或福音派基督徒 —— 如果他们作为一个团体投票，他们可以显著改变选举结果。因此，政党会尽一切努力吸引不同的联盟。所以当你看到候选人发表演讲或与其他候选人辩论时，注意他们提到的话题。他们可以谈论无数的事情，但他们选择的话题能充分说明这位政治家试图争取到自己这边的选民联盟。所以如果一个候选人承诺维护甚至扩大持枪权利，他们是在吸引主要由保守的白人男性组成的联盟。另一方面，如果一个候选人承诺保护移民及其家庭，他们是在吸引美国庞大的移民人口。 +

好的，政党随着时间改变的第三种方式是改变整个政党的结构，而这主要有三种方式。第一种是政党重新调整，这听起来就是字面意思 —— 政党重新调整自身。那他们为什么要这样做呢？嗯，通常这发生在一次或一系列选举中该党惨败之后。比如，如果对立的政党不断获胜，这对失败的政党来说是一个信号，表明与普通选民的优先事项相比，他们的优先事项，用政治学的术语来说，是有问题的。 +

举个例子，民主党在1932年和1936年的总统选举中取得了重大胜利，就像你在这里看到的。这是在大萧条（Great Depression）期间，当共和党批评富兰克林·罗斯福（Franklin Roosevelt）的自由主义政策和缓解大萧条毁灭性影响的社会项目时，显然普通美国人对此是认可的。“好吧，那我是坚持我的原则呢，还是要吃饭呢？没错，我要填饱肚子。” 这导致共和党对他们未来的纲领和优先事项进行了重大调整。 +

但重新调整也可能自下而上地发生。你还记得是亚伯拉罕·林肯（Abraham Lincoln）领导的共和党最终废除了奴隶制，所以在很长一段时间里，大部分美国黑人都支持共和党。然而，从20世纪20年代开始，共和党未能代表美国黑人推行民权立法，再加上大萧条造成的极度贫困，导致大多数美国黑人转而支持民主党，因为民主党在缓解贫困和争取民权方面有很多举措 —— 至少比共和党做得多。 +

好的，政党结构改变的第二种方式是通过竞选资金法的变化。自20世纪70年代以来，竞选资金法和最高法院的裁决改变了可以合法给予候选人和政党的资金数额。我们将在第11个话题中更多地讨论这个问题，所以现在我先说到这里。 +

政党结构改变的第三种方式是由于通信和数据管理技术的变化。随着技术的进步，政党挖掘特定群体数据并利用这些数据赢得选举的能力也提高了。我给你举两个例子，都来自2012年的总统选举。在那次选举中，共和党候选人米特·罗姆尼（Mitt Romney）的竞选团队开发了一个名为 “逆戟鲸计划（Project Orca）” 的项目，这是一个网络应用程序，选民可以用它让竞选团队知道他们投票了。有了这些信息，罗姆尼的竞选团队可以实时看到选民投票率低的地区，他们可以在最后时刻努力让这些人去投票。嘿，在我看来这听起来是个相当不错的主意。但 “逆戟鲸计划” 结果并不像逆戟鲸那么厉害，更像是搁浅的鲸鱼，因为这项技术根本不管用。但不管它是否有效，重点是 “逆戟鲸计划” 背后的思路是政党在如何让人们放下多力多滋（Doritos），从沙发上起身去投票方面的一个重大转变。 +

实际上，“逆戟鲸计划” 是对罗姆尼在那次选举中的对手巴拉克·奥巴马（Barack Obama）的回应。奥巴马的竞选团队开发了一些新技术，名为 “独角鲸计划（Project Narwhal）” 。只是为了找点乐子，你应该知道独角鲸唯一的天敌是逆戟鲸 —— 所以你懂的，罗姆尼的 “逆戟鲸计划” 还挺有意思的。不管怎样，“独角鲸计划” 在拉票技巧方面是一个重大的进步。有了这项技术，奥巴马的竞选团队不仅可以根据人口统计学特征，还可以根据心理统计学特征向人们发送电子邮件和短信。人口统计学是根据人们的外部特征对他们进行分类 —— 比如种族、性别、年龄和地区。而心理统计学则是根据人们的内心生活对他们进行分类 —— 比如他们的个性、态度、抱负和欲望。这些特征解释了为什么选民会以他们的方式投票。你知道，他们可以从你的网上购物习惯和你观看的节目等方面获取这些信息。事实证明，“独角鲸计划” 比 “逆戟鲸计划” 成功得多。但同样，在这里谁赢谁输不是重点，重点是这从根本上改变了政党和竞选活动试图说服人们投票的方式。 +

好的，感谢观看。点击这里获取复习资料包，这将帮助你在课堂上取得A的成绩，并在五月份的考试中获得5分。无论你是 “逆戟鲸计划” 的粉丝还是 “独角鲸计划” 的粉丝，我的频道里有关于这些内容的视频。所以如果你希望我继续制作视频，那就一定要订阅，我会照办的。海姆勒，退出。 + 

'''

== pure

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 5 of the AP Government curriculum, and in this video it's time to talk about how political parties change over time and realign themselves to better reflect the attitudes and preferences of Americans. So if you're ready to get them brain cows milked, let's get to it.

So here's our learning objective for this video: explain why and how political parties change and adapt. Okay, so in the last video we talked about how political parties act as linkage institutions that help average people engage in the political process. And in that video we had a look at the party platforms for the Democratic and Republican parties. But those platforms and the way parties get their people elected have changed over time, so let's look at a few of those changes.

First, the way parties interact with candidates has changed. It used to be that it was the party that mattered and the candidate was secondary, but now it's the candidate that matters and the party is secondary. A big part of this is new media technology which allows candidates to speak directly to their supporters and gather a following around themselves. And that has had the effect of weakening the party's role in nominating candidates. Now some people have criticized this new candidate-centered nomination process on account of it can lead to opposing factions within the party. But political scientists who have studied this have shown that certain candidates who build their own following can actually have a benefit to the party. And this is especially true of candidates who champion underrepresented opinions in the electorate -- like they have argued that even if the candidate doesn't win the nomination, their followers are still likely to engage in the political process of voting and supporting the winning candidate.

Second, parties have changed their platforms over time in order to appeal to a larger swath of the electorate. Now the changing platform will almost never contradict the larger ideology of the party -- like you're never going to hear the Republicans say, "You know a lot of people are saying that America was built on racism and that we ought to atone for those sins, so you know let's put it in the platform." You know, even if they don't contradict their ideology, parties have shifted emphasis in their platforms or even change their messaging in order to appeal to more voters. This is especially true when it comes to coalitions of voters.

Now a coalition is a demographic group -- like millennials or retired persons or evangelical Christians -- and if they vote as a block, they can significantly alter the outcome of an election. Therefore, parties do everything they can to appeal to different coalitions. So when you see candidates giving speeches or debating other candidates, pay attention to the topics that they mention. There are a gajillion things that they could talk about, but the topics that they choose say a lot about the coalitions that the politician is trying to win to his or her side. So if a candidate promises to uphold or even expand gun rights, they are appealing to a coalition mainly of conservative white males. On the other hand, if a candidate promises protections for immigrants and their families, they are appealing to America's large immigrant population.

Okay, the third way parties have changed over time is by altering the entire party's structure, and there are three main ways that this happens. First is party realignment, and this is exactly what it sounds like -- the party realigns itself. And why would they do that? Well, usually this occurs after an election or a series of elections where the party is badly defeated. Like if the opposing party keeps winning and winning big, that is a sign to the losing party that their priorities compared to the general electorate's priorities are, to use the political science term, a wonky asset.

So for example, the Democrats won big in the presidential elections of 1932 and 1936, as you can see here. This was in the midst of the Great Depression, and while Republicans were criticizing Franklin Roosevelt's liberal policies and social programs to alleviate the devastating effects of the depression, apparently the average American was okay with it. "Okay, so should I uphold my principles or should I eat? Yeah, I'm gonna take a sandwich." And that led the Republican party to a major realignment of their future platforms and priorities.

But realignment can also happen from the bottom up. Now you'll recall that it was the Republican party with Abraham Lincoln at the helm that ultimately abolished slavery, and so for a long time much of the black American population were aligned with the Republican party. However, starting in the 1920s, the Republicans' failure to pursue civil rights legislation on behalf of black Americans combined with the grinding poverty caused by the Great Depression led a majority of black Americans to switch to the Democratic party, which had a lot going for it in terms of alleviating poverty and fighting for civil rights -- at least more than the Republicans did.

Okay, the second way party structure has changed is through changes to campaign finance laws. Since the 1970s, campaign finance laws and Supreme Court decisions have changed how much money can be lawfully given to candidates and parties. We're going to talk more about that in Topic 11, so I'm just going to leave it there for now.

And the third way party structure has changed is because of changes in communication and data management technology. As technology has advanced, so too has a party's ability to mine data on certain groups and use that data to win elections. I'm going to give you two examples, both from the 2012 presidential election. In that election, Republican candidate Mitt Romney's campaign developed what they called Project Orca, which was a web app which voters could use to let the campaign know that they voted. And so with this information, Romney's campaign could see in real time the areas in which there was low voter turnout, and they could engage in some last minute efforts to get those people to the polls. Hey, that sounds like a pretty good idea to me. But instead of being a killer whale, Project Orca turned out to be more like a beached whale because the technology just didn't work. But whether it worked or not, the point is the thinking behind Project Orca was a massive shift in how the party got their people to put their Doritos down, get off the couch, and go vote.

Now Project Orca was in fact a response to Romney's opponent in that election, Barack Obama. Obama's campaign had developed some new technology under the name Project Narwhal. And just for poops and giggles, you should know that the only natural predator to the narwhal is the orca -- so you know, Romney, he's saucy. Anyway, Project Narwhal was a significant leap forward in canvassing techniques. With this technology, Obama's campaign could target emails and text messages to people not only based on their demographics but also based on their psychographics. Now demographics classify people according to their external traits -- like race, gender, age, and region. Psychographics, on the other hand, classify people according to their inner life -- like their personality, their attitudes, their aspirations, their desires. These traits explain why a voter votes the way that he or she does. You know, they can get this information from your online shopping habits and the kinds of shows you watched, etc. As it turned out, Narwhal was far more successful than Orca. But again, who won and lost is less the emphasis here than on how this fundamentally changed how parties and campaigns try to convince people to vote.

Okay, thanks for watching. Click right here to grab a review packet, which is going to help you get an A in your class and a five on your exam in May. Whether you're an Orca fan or a Narwhal fan, I got videos here on this channel for all. So if you want me to keep making them, then by all means subscribe and I shall oblige. Heimler out.

'''

