
= 5.05 Third Party Politics
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 5 of the AP Government curriculum 课程, and in this video that means it's time to talk about third-party politics 第三方政治. So if you're ready to get them brain cows milked, well then let's get to it. +

So in this video, here's what we're trying to do: explain how structural barriers 结构性障碍 impact third-party 第三方 and independent candidate 独立候选人 success. So over the course of the last few videos, we've been talking about political parties, and I've been focusing on the two big ones -- the Democrats 民主党 and the Republicans 共和党. And maybe you wondered, "Why aren't you talking about all the other political parties? Or about the Green Party 绿党 or the Constitution Party 宪法党 or the Libertarian Party 自由意志党 or the Pirate Party 海盗党?" Did he just say Pirate Party? I sure did -- it's a real party, look it up. +

Now here's the thing: I haven't really mentioned any of those parties till now because if I'm gonna be honest with you, they're never going to win an election. And I'm not just over here dropping hot takes （俚语：发表大胆观点） -- like, it's true. What we have here in America is a two-party system 两党制, and in a system like that, it is almost an impossibility 不可能的事 for a third party to win a major election. So pirates are gonna keep pirating, but they're not likely to do it in the national legislature 国家立法机构. +

Now the question is: why is that? Like, why don't third parties stand a chance 有机会 in a two-party system? Well, there are actually a lot of reasons, but I'm only gonna focus on the two big issues surrounding third parties: number one, winner-take-all voting districts 赢者通吃的选区制度, and number two, the incorporation 纳入 of third-party agendas 议程 into the two major parties' platforms 党纲. +

So first, winner-take-all voting districts. And let's use presidential elections 总统选举 to think about this and the electoral college system 选举人团制度. Whichever candidate wins the most popular votes 普选票 is awarded 授予 all of the electoral votes 选举人票 of that state. So here in Georgia, we currently have 16 electoral votes, and so when the next presidential election comes around, even if one candidate wins by only one single solitary vote 仅仅一票, all 16 of our electoral votes will go to that candidate. And that is a winner-take-all system 赢者通吃制度. +

Now what does this have to do with third parties? Well, when you consider the sheer girth 巨大规模 of the Republican and Democratic parties, they are able to appeal to 吸引 a metric butt load of （俚语：大量的） voters -- which is to say, the vast majority of Americans will find themselves agreeing with much of the respective platforms 各自的党纲 of the two major parties. So they are most likely to vote with the major parties. And if it's a winner-take-all system, that means the third party -- which is necessarily smaller, less funded 资金较少的, and newer -- can never hope to win a popular vote 普选 and thus will be awarded no electoral votes. And that further dooms 使注定失败 third-party candidates because people are less likely to vote for them since it feels like they're throwing away their vote 浪费选票. Like, if they have no chance in winning in the system, why would I even cast my vote that way 投票, even if I believe in their platform? +

Now the only thing that could really change the situation is to abolish 废除 the winner-take-all system in favor of 支持 what's known as a proportional system 比例代表制. And that's exactly what it sounds like: if you have candidates from 10 parties, and Party A receives 40% of the vote, then they get 40% of the seats 席位, and Party B receives 30% of the vote, they get 30% of the seats, and so on. And this is the system present in many European nations. And under a proportional system, the efforts of third-party candidates are rewarded in a way that they would never be in a two-party winner-take-all system. +

Now the second structural barrier standing in the way of 阻碍 third-party candidates is the incorporation of their agendas into the platforms of the two major parties. Third parties are often called the conscience of the nation 国家的良心 because they usually form around a narrower set of interests 更狭窄的利益范围 than do the major parties. For example, the Green Party emphasizes environmentalism 环保主义, or the Christian Liberty Party argues that the Bible should be the blueprint 蓝图 for political action 政治行动. So in both of these examples, you can see that third parties take on more extreme agendas 更极端的议程 and therefore appeal to fewer people than the major parties. +

However, if the third party is organized and well-funded, they can get the nation's attention. And if it turns out that a significant portion of Americans believe in one of the platforms of those parties, then that issue can rise to prominence 变得突出. And now you're thinking, in that situation maybe a third party has a chance. But here's where I tell you, uh-uh, no. Because often what happens is that the third party gains some traction 获得一些关注, and that's a signal to the major parties that they need to appeal to those people. So what they'll do is incorporate the third party's agenda into their own platform. So for all the people who are moved by that issue, now they see the Democrats taking it up 采纳, for example, and they vote Democrat, and the third-party candidate goes home and bites his pillow （比喻失意）. +

Now this is a pretty regular occurrence 经常发生的事, but one of the best examples of a third party's platform being incorporated into a major party's platform was the Populist Party 人民党 of the late 19th century. This party formed around upholding the interests of farmers 维护农民利益, and one of their chief agenda items 主要议程项目 was to push for 推动 the unlimited coinage of silver 白银的自由铸造. With this platform, the party got a lot of attention from the rural community 农村地区, and seeing this, the Democrats went ahead and incorporated the unlimited coinage of silver into their own platform, and those farmers in large measure 很大程度上 ended up voting for Democrats. +

So with the two-party system, two things will probably always be true: number one, third parties will never win because of the winner-take-all voting systems, and number two, third parties will continue to raise issues overlooked by the major parties 被大党忽视的问题, who will then bring those issues into their own platforms. +

Okay, thanks for watching. Click right here to grab a review packet, which is going to help you get an A in your class and a five on your exam in May. And if this video helped you and you want me to keep making them, then by all means subscribe 订阅 and I shall oblige 照办. Heimler out. +

'''

== 中文释义
嘿，欢迎回到海姆勒（Heimler）的历史频道。目前我们一直在学习美国大学预修课程（AP）政府课程的第五单元，在这个视频中，意味着我们要谈谈第三方政治。所以，如果你准备好激发自己的思维，那么我们就开始吧。 +

所以在这个视频中，我们要做的是：解释结构性障碍如何影响第三方及独立候选人的成功。在过去的几个视频中，我们一直在谈论政党，而且我一直关注两大政党 —— 民主党（Democrats）和共和党（Republicans）。也许你会想，“你为什么不谈谈所有其他政党呢？比如绿党（Green Party）、宪法党（Constitution Party）、自由意志党（Libertarian Party）或海盗党（Pirate Party）？” 我刚才确实提到了海盗党吧？没错，它是一个真实存在的政党，你可以去查一下。 +

事情是这样的：直到现在我都没有真正提到过这些政党，因为老实跟你说，它们永远不会赢得选举。我可不是在这里随便说说 —— 这是事实。在美国，我们实行的是两党制，在这样的制度下，第三方政党几乎不可能赢得一场重大选举。所以海盗们可以继续当海盗，但他们不太可能在国家立法机构中这样做。 +

现在的问题是：为什么会这样呢？比如，为什么第三方政党在两党制中没有机会呢？嗯，实际上原因有很多，但我只关注围绕第三方政党的两个主要问题：第一，赢者通吃的选区制度；第二，第三方政党的议程被纳入两大政党的纲领中。 +

首先，赢者通吃的选区制度。让我们以总统选举和选举团制度为例来思考这个问题。无论哪位候选人赢得最多的普选票，就能获得该州的所有选举人票。以佐治亚州（Georgia）为例，我们目前有16张选举人票，当下一次总统选举到来时，即使一位候选人仅以一票的优势获胜，我们的16张选举人票都会归这位候选人所有。这就是赢者通吃的制度。 +

这和第三方政党有什么关系呢？嗯，当你考虑到共和党和民主党的庞大规模时，它们能够吸引大量的选民 —— 也就是说，绝大多数美国人会发现自己在很大程度上认同两大政党各自的纲领。所以他们最有可能投票给两大政党。而在赢者通吃的制度下，这意味着第三方政党 —— 它们规模必然较小、资金较少且成立时间较短 —— 永远没有希望赢得普选，因此也不会获得选举人票。这进一步注定了第三方候选人的命运，因为人们不太可能投票给他们，因为感觉投票给他们就像浪费选票。比如，如果他们在这个制度下没有获胜的机会，即使我认同他们的纲领，我为什么还要那样投票呢？ +

现在，真正能改变这种情况的唯一办法是废除赢者通吃制度，转而采用所谓的比例代表制。这听起来很直白：如果有来自10个政党的候选人，A党获得40%的选票，那么他们就能获得40%的席位，B党获得30%的选票，他们就能获得30%的席位，以此类推。这就是许多欧洲国家采用的制度。在比例代表制下，第三方候选人的努力会得到回报，而在两党制的赢者通吃制度下则不会。 +

现在，阻碍第三方候选人的第二个结构性障碍是他们的议程被纳入两大政党的纲领中。第三方政党通常被称为国家的良心，因为它们围绕的利益范围通常比两大政党更窄。例如，绿党强调环保主义，或者基督教自由党认为《圣经》（Bible）应该成为政治行动的蓝图。所以在这两个例子中，你可以看到第三方政党的议程更加极端，因此吸引的选民比两大政党少。 +

然而，如果第三方政党组织有序且资金充足，它们就能引起全国的关注。如果事实证明很大一部分美国人认同这些政党的某个纲领，那么这个问题就会变得突出。现在你可能会想，在那种情况下，第三方政党也许有机会。但我要告诉你，不，并非如此。因为通常的情况是，第三方政党获得了一些支持，这向两大政党发出了一个信号，即它们需要吸引这些人。所以它们会把第三方政党的议程纳入自己的纲领中。所以对于所有被那个问题打动的人来说，比如说，现在他们看到民主党采纳了这个议程，然后他们就会投票给民主党，而第三方候选人只能失望而归。 +

这种情况相当常见，第三方政党的纲领被纳入主要政党纲领的一个很好的例子是19世纪后期的民粹党（Populist Party）。这个政党是为了维护农民的利益而成立的，他们的主要议程之一是推动白银的无限制铸造。凭借这个纲领，该党得到了农村社区的大量关注，看到这种情况，民主党继续将白银的无限制铸造纳入自己的纲领，而且很大程度上这些农民最终投票给了民主党。 +

所以在两党制下，有两件事可能永远是真的：第一，由于赢者通吃的投票制度，第三方政党永远不会获胜；第二，第三方政党会继续提出被主要政党忽视的问题，然后主要政党会把这些问题纳入自己的纲领中。 +

好的，感谢观看。点击这里获取复习资料包，这将帮助你在课堂上取得A的成绩，并在五月份的考试中获得5分。如果这个视频对你有帮助，并且你希望我继续制作这样的视频，那就一定要订阅，我会照办的。海姆勒，退出。 + 

'''

== pure

Hey there, and welcome back to Heimler's History. Now we've been going through Unit 5 of the AP Government curriculum, and in this video that means it's time to talk about third-party politics. So if you're ready to get them brain cows milked, well then let's get to it.

So in this video, here's what we're trying to do: explain how structural barriers impact third-party and independent candidate success. So over the course of the last few videos, we've been talking about political parties, and I've been focusing on the two big ones -- the Democrats and the Republicans. And maybe you wondered, "Why aren't you talking about all the other political parties? Or about the Green Party or the Constitution Party or the Libertarian Party or the Pirate Party?" Did he just say Pirate Party? I sure did -- it's a real party, look it up.

Now here's the thing: I haven't really mentioned any of those parties till now because if I'm gonna be honest with you, they're never going to win an election. And I'm not just over here dropping hot takes -- like, it's true. What we have here in America is a two-party system, and in a system like that, it is almost an impossibility for a third party to win a major election. So pirates are gonna keep pirating, but they're not likely to do it in the national legislature.

Now the question is: why is that? Like, why don't third parties stand a chance in a two-party system? Well, there are actually a lot of reasons, but I'm only gonna focus on the two big issues surrounding third parties: number one, winner-take-all voting districts, and number two, the incorporation of third-party agendas into the two major parties' platforms.

So first, winner-take-all voting districts. And let's use presidential elections to think about this and the electoral college system. Whichever candidate wins the most popular votes is awarded all of the electoral votes of that state. So here in Georgia, we currently have 16 electoral votes, and so when the next presidential election comes around, even if one candidate wins by only one single solitary vote, all 16 of our electoral votes will go to that candidate. And that is a winner-take-all system.

Now what does this have to do with third parties? Well, when you consider the sheer girth of the Republican and Democratic parties, they are able to appeal to a metric butt load of voters -- which is to say, the vast majority of Americans will find themselves agreeing with much of the respective platforms of the two major parties. So they are most likely to vote with the major parties. And if it's a winner-take-all system, that means the third party -- which is necessarily smaller, less funded, and newer -- can never hope to win a popular vote and thus will be awarded no electoral votes. And that further dooms third-party candidates because people are less likely to vote for them since it feels like they're throwing away their vote. Like, if they have no chance in winning in the system, why would I even cast my vote that way, even if I believe in their platform?

Now the only thing that could really change the situation is to abolish the winner-take-all system in favor of what's known as a proportional system. And that's exactly what it sounds like: if you have candidates from 10 parties, and Party A receives 40% of the vote, then they get 40% of the seats, and Party B receives 30% of the vote, they get 30% of the seats, and so on. And this is the system present in many European nations. And under a proportional system, the efforts of third-party candidates are rewarded in a way that they would never be in a two-party winner-take-all system.

Now the second structural barrier standing in the way of third-party candidates is the incorporation of their agendas into the platforms of the two major parties. Third parties are often called the conscience of the nation because they usually form around a narrower set of interests than do the major parties. For example, the Green Party emphasizes environmentalism, or the Christian Liberty Party argues that the Bible should be the blueprint for political action. So in both of these examples, you can see that third parties take on more extreme agendas and therefore appeal to fewer people than the major parties.

However, if the third party is organized and well-funded, they can get the nation's attention. And if it turns out that a significant portion of Americans believe in one of the platforms of those parties, then that issue can rise to prominence. And now you're thinking, in that situation maybe a third party has a chance. But here's where I tell you, uh-uh, no. Because often what happens is that the third party gains some traction, and that's a signal to the major parties that they need to appeal to those people. So what they'll do is incorporate the third party's agenda into their own platform. So for all the people who are moved by that issue, now they see the Democrats taking it up, for example, and they vote Democrat, and the third-party candidate goes home and bites his pillow.

Now this is a pretty regular occurrence, but one of the best examples of a third party's platform being incorporated into a major party's platform was the Populist Party of the late 19th century. This party formed around upholding the interests of farmers, and one of their chief agenda items was to push for the unlimited coinage of silver. With this platform, the party got a lot of attention from the rural community, and seeing this, the Democrats went ahead and incorporated the unlimited coinage of silver into their own platform, and those farmers in large measure ended up voting for Democrats.

So with the two-party system, two things will probably always be true: number one, third parties will never win because of the winner-take-all voting systems, and number two, third parties will continue to raise issues overlooked by the major parties, who will then bring those issues into their own platforms.

Okay, thanks for watching. Click right here to grab a review packet, which is going to help you get an A in your class and a five on your exam in May. And if this video helped you and you want me to keep making them, then by all means subscribe and I shall oblige. Heimler out.

'''

