
= 5.08 Electing the PRESIDENT
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Well, hey there, and welcome back to Heimler's History. Now, we've been going through unit 5 of the AP Government curriculum 课程, and in this video, that means it's time to talk about how we elect the president. So, if you're ready to get them brain cows milked, Electoral College 选举人团 style, well then let's get to it. So, in this video, here's what we're trying to do: explain how the different processes work in a U.S. presidential election 美国总统选举, and explain how the Electoral College facilitates 促进 and/or impedes 阻碍 democracy 民主. I hope you can already taste the sauce because it is spicy. And to be clear, even though what I'm about to tell you is pretty complex, I'm leaving a bunch of stuff out. It's even more complex than what I'm about to say, but this is what you need to know for your exams. Let's start with the process of electing the president. If someone's going to run for president, they first have to earn their party's nomination 提名, and this happens through primary election 初选. And primaries are elections in which members of a party vote on which candidate they want to represent them in the general election 大选, which is the actual election where a president is chosen. Now, these primary elections happen state by state, and when you know it, different states handle primaries in different ways. Some states hold open primaries 开放初选, which means that any registered voter 注册选民 can vote in either party's primary, but not both. So, for example, here in my fair state of Georgia, we hold open primaries. So, if I show up to the polls 投票站 on primary election day, the poll worker 投票站工作人员 is going to ask me whether I want a ballot 选票 for the Republican primaries or the Democratic primaries, and I can tell them whichever one I want. That's the idea of an open primary. But in other states, like New York for example, they hold closed primaries 封闭初选. That means that only people registered with the party 党内注册成员 can vote in those primaries. So, to sum up, here in Georgia, if I want to vote in the primary, they asked, "Hey, are you a registered voter?" And then in New York, they're going to ask me, "Are you registered with the party?" And to further confuse you, some states don't use primaries but instead hold caucuses 党团会议 in order to nominate their party's candidate. Now, a caucus is in principle 原则上 no different than a primary; it's people voting on their chosen nominee 被提名者 for the party. The only difference is that instead of using secret ballots 无记名投票 to cast their vote 投票, voters at a caucus discuss and debate together, and then they vote publicly 公开投票. So, in this first step, party members vote on their chosen candidate, and whoever wins that primary is presented as such at the party's national convention 全国代表大会, which is just a big party for the, you know, party. They present the winning candidate and their choice for vice president, and that's the beginning of the general election, where each party's chosen candidates run against each other to become president. +

Okay, now what I just said, you know, both parties putting forward candidates to run for president, is true only in some years. Remember that a president can serve only two four-year terms 任期. So, if a president has done that, then both parties will choose their candidate. However, if a president has only served one term, then the party usually keeps the sitting president 现任总统 as their nominee. So, for example, Barack Obama was the president for four years starting in 2008, and after that, he was still the Democratic Party's nominee for president in 2012. Donald Trump won the election in 2016, and so he was the party's nominee in 2020 as well. So, if a sitting president is running again, that candidate is known as the incumbent 现任者, and truth be told 说实话, the incumbent almost always has the advantage over the challenger 挑战者, a phenomenon known as the incumbency advantage 现任优势. The first and most obvious advantage the incumbent has is that he has already won an election, so he knows how it's done, or in the future, maybe she will know how it's done. The second advantage is that the incumbent is a known quantity 已知量, which is to say people already know how they're going to act as president. The third advantage is that the incumbent already has an army of volunteers and fundraisers 筹款人 ready to help with another campaign. And while this advantage is certainly helpful, it does not guarantee a victory. So, with all that done, we finally come to election day 选举日, which is always the first Tuesday in November. Everyone goes to the polls and votes for the candidate that they think will be the best president -- except kind of not really. So, yes, we all go out and vote, and on our ballots are the candidates' names, but we are not actually voting for those candidates because here in America, the people don't actually elect the president, to which I say, what? +

All right, now I get to tell you about the Electoral College 选举人团, which is the constitutional mechanism 宪法机制 by which we elect the president. The framers of the Constitution 宪法的制定者 weren't too keen on 不太热衷于 participatory democracy 参与式民主, especially when it came to electing the president. So, they devised a system 设计了一个系统 that would insulate 使隔绝 the ignorant mob of voters 无知的选民群体 from the election of the president, and that system is called the Electoral College. And here's how it works: each state has the same number of electors 选举人 as they have congressional representatives 国会议员. So, here in Georgia, we have 14 representatives in the House 众议院议员 and two senators 参议员, so we have 16 electors that cast their vote for president. But don't hate me, we actually have 32 electors, and here's why: our state chooses 16 electors for the Democratic candidate and 16 electors for the Republican candidate. So, when I go to the polls to vote, I'm not actually voting for the candidate; I'm voting for that candidate's slate of electors 选举人名单 who will then vote that candidate into office 当选就职. Now, in almost every state, whichever candidate wins the state, it's a winner-take-all system 赢者通吃制度 for electoral votes 选举人票. So, in my state, if the Republican candidate wins, all 16 electoral votes go to that candidate. However, you do need to know that in Maine and Nebraska, they have rules which allow them to split the electoral votes 分配选举人票, but in every other state, it's a winner-take-all system. It is possible for an elector to vote against the popular vote 普选结果, and if they do, they are called faithless electors 失信选举人. Now, that almost never happens, and some states even have laws against it, but it has happened now and then 时不时地发生. Now, in order to win the election, the candidate has to receive a minimum of 270 electoral votes, and whatever candidate does becomes the president. +

Okay, now the last thing I'll say about the Electoral College is this: it is as a system -- uh -- contention 争议 every four years when we have a presidential election. The debate over the Electoral College returns like the instinctive flocking 本能的聚集 of the salmon of Capistrano. For example, in the 2000 presidential election, Al Gore, the Democratic nominee, won about half a million more popular votes 普选票 than the Republican candidate George W. Bush. So, let me say that again: half a million more people voted for the Democratic candidate than the Republican candidate, but Bush ended up winning more electoral votes, and through a highly contested outcome 极具争议的结果 that ultimately had to be decided by the Supreme Court, he defeated Gore. Now, the same thing happened in 2016. Hillary Clinton won more of the popular vote than Donald Trump, but Trump won the election with a majority in the Electoral College. So, in light of that 鉴于此, you may be wondering why in the world do we do it this way? Well, proponents 支持者 of the Electoral College argue that this system requires candidates to campaign 竞选 in many more places throughout America rather than just focusing on a few highly populated states and cities. But the detractors 批评者 of the Electoral College would say that while that's true in theory, the system actually only requires candidates to spend time in a handful of swing states 摇摆州. If you don't know, swing states are those states which can really go either way on voting day 选举日. Even so, the Electoral College is the system we've been given in the Constitution, and short of a constitutional amendment 宪法修正案, it's the system we'll have in the future as well. And that is how we elect a president. +

Okay, thanks for watching. Click right here to grab my review packet, which is going to help you get an A in your class and a five on your exam in May. Here in my channel, we operate by popular vote 按多数票决定, so if you want me to keep making these videos, and you can vote for me to keep doing that by subscribing 订阅. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimler）的历史频道。目前，我们一直在学习美国大学预修课程（AP）政府课程的第五单元，在这个视频中，意味着我们要谈谈我们是如何选举总统的。所以，如果你准备好以选举人团（Electoral College）的方式激发自己的思维，那么我们就开始吧。所以，在这个视频中，我们要做的是：解释美国大选的不同流程是如何运作的，以及解释选举人团是如何促进或阻碍民主的。我希望你已经能感受到其中的精彩了，因为这内容很有意思。需要说明的是，尽管我要告诉你的内容相当复杂，但我还是省略了很多东西。实际情况比我要说的还要复杂，但这些是你考试需要知道的内容。让我们从选举总统的流程开始说起。如果有人要竞选总统，他们首先必须获得所在政党的提名，而这是通过初选来实现的。初选是指一个政党的成员投票选出他们希望在大选中代表该党的候选人，而大选才是真正选出总统的选举。现在，这些初选是逐州进行的，而且如你所知，不同的州处理初选的方式也不同。有些州举行开放初选，这意味着任何登记选民都可以在任何一个政党的初选中投票，但不能同时在两个政党的初选中投票。例如，在我所在的佐治亚州（Georgia），我们举行开放初选。所以，如果我在初选日去投票站，投票站工作人员会问我是想要共和党的选票还是民主党的选票，我可以告诉他们我想要的那一方的选票。这就是开放初选的概念。但在其他州，比如纽约州，他们举行封闭初选。这意味着只有登记为该政党的选民才能在这些初选中投票。总结一下，在佐治亚州，如果我想在初选中投票，他们会问：“嘿，你是登记选民吗？” 而在纽约州，他们会问我：“你是该政党的登记选民吗？” 更让人困惑的是，有些州不采用初选的方式，而是举行党团会议来提名他们党的候选人。现在，党团会议在原则上与初选没有区别，都是人们为他们选择的党内候选人投票。唯一的区别是，党团会议的选民不是通过无记名投票来投票，而是一起讨论和辩论，然后公开投票。所以，在这第一步中，党员为他们选择的候选人投票，在初选中获胜的人会在该党的全国代表大会上被提名，全国代表大会就是该党的一个大型集会。他们推出获胜的候选人以及他们选择的副总统候选人，这就是大选的开始，在大选中，每个政党选出的候选人相互竞争以成为总统。 +

好的，我刚才说的，也就是两个政党都推出候选人竞选总统，只是在某些年份是这样。要记住，一位总统只能连任两届，每届任期四年。所以，如果一位总统已经连任两届，那么两个政党都会选出他们的候选人。然而，如果一位总统只担任了一届，那么该党通常会让现任总统作为他们的候选人。例如，巴拉克·奥巴马（Barack Obama）从2008年开始担任了四年总统，之后，他在2012年仍然是民主党的总统候选人。唐纳德·特朗普（Donald Trump）在2016年赢得了大选，所以他在2020年也是共和党的候选人。所以，如果现任总统再次参选，这位候选人就被称为现任候选人，说实话，现任候选人几乎总是比挑战者更有优势，这种现象被称为现任优势。现任候选人的第一个也是最明显的优势是，他已经赢得过一次选举，所以他知道该怎么做，或者说未来，也许她也会知道该怎么做。第二个优势是，现任候选人是大家已经了解的人物，也就是说人们已经知道他们作为总统会怎么做。第三个优势是，现任候选人已经有一批志愿者和筹款人准备好帮助进行另一场竞选活动。虽然这种优势肯定有帮助，但并不能保证获胜。所以，在完成了所有这些之后，我们终于迎来了选举日，选举日总是在11月的第一个星期二。每个人都去投票，为他们认为最适合当总统的候选人投票 —— 但实际上又不是这样。是的，我们都出去投票，选票上有候选人的名字，但实际上我们不是在为这些候选人投票，说到这里我要说，这是为什么呢？ +

好的，现在我要告诉你关于选举人团的事情，选举人团是我们选举总统的宪法机制。美国宪法的制定者不太热衷于参与式民主，尤其是在选举总统这件事上。所以，他们设计了一个制度，将无知的选民群体与总统选举隔离开来，这个制度就叫选举人团。下面是它的运作方式：每个州的选举人数量与该州的国会议员数量相同。所以，在佐治亚州，我们有14名众议员和2名参议员，所以我们有16名选举人来为总统投票。但别误会我的意思，实际上我们有32名选举人，原因是这样的：我们州会为民主党候选人选出16名选举人，为共和党候选人也选出16名选举人。所以，当我去投票站投票时，我实际上不是在为候选人投票，我是在为该候选人的选举人团队投票，这些选举人随后会投票让该候选人当选。现在，几乎在每个州，无论哪个候选人在该州获胜，选举人票采用的是赢者通吃的制度。所以，在我的州，如果共和党候选人获胜，所有16张选举人票都会归该候选人所有。不过，你需要知道的是，在缅因州（Maine）和内布拉斯加州（Nebraska），他们有允许分配选举人票的规则，但在其他所有州，采用的都是赢者通吃的制度。选举人有可能投票反对普选结果，如果他们这样做了，他们就被称为失信选举人。现在，这种情况几乎从未发生过，而且有些州甚至有相关法律禁止这种行为，但这种情况还是偶尔会发生。现在，为了赢得选举，候选人必须至少获得270张选举人票，获得足够选举人票的候选人将成为总统。 +

好的，关于选举人团我要说的最后一点是：每四年举行总统选举时，这个制度都会引发争议。关于选举人团的争论就像卡皮斯特拉诺（Capistrano）的鲑鱼本能地聚集一样反复出现。例如，在2000年的总统选举中，民主党候选人阿尔·戈尔（Al Gore）比共和党候选人乔治·W·布什（George W. Bush）多获得了大约50万张普选票。所以，我再说一遍：投票给民主党候选人的人比投票给共和党候选人的人多50万，但布什最终赢得了更多的选举人票，而且这个极具争议的结果最终不得不由最高法院来裁决，布什击败了戈尔。同样的事情在2016年也发生了。希拉里·克林顿（Hillary Clinton）比唐纳德·特朗普赢得了更多的普选票，但特朗普在选举人团中以多数票赢得了大选。所以，鉴于这种情况，你可能会想，我们为什么要以这种方式选举总统呢？嗯，选举人团的支持者认为，这个制度要求候选人在美国更多的地方进行竞选活动，而不是只关注少数人口密集的州和城市。但选举人团的反对者会说，虽然理论上是这样，但这个制度实际上只要求候选人花时间在少数几个摇摆州。如果你不知道，摇摆州是指那些在选举日投票结果不确定的州。即便如此，选举人团是美国宪法规定的制度，除非修改宪法，否则未来我们仍然会采用这个制度。这就是我们选举总统的方式。 +

好的，感谢观看。点击这里获取我的复习资料包，这将帮助你在课堂上取得A的成绩，并在五月份的考试中获得5分。在我的频道里，我们通过大家的投票来决定，所以如果你希望我继续制作这样的视频，你可以通过订阅来支持我继续做下去。海姆勒，退出。 + 

'''

== pure

Well, hey there, and welcome back to Heimler's History. Now, we've been going through unit 5 of the AP Government curriculum, and in this video, that means it's time to talk about how we elect the president. So, if you're ready to get them brain cows milked, Electoral College style, well then let's get to it. So, in this video, here's what we're trying to do: explain how the different processes work in a U.S. presidential election, and explain how the Electoral College facilitates and/or impedes democracy. I hope you can already taste the sauce because it is spicy. And to be clear, even though what I'm about to tell you is pretty complex, I'm leaving a bunch of stuff out. It's even more complex than what I'm about to say, but this is what you need to know for your exams. Let's start with the process of electing the president. If someone's going to run for president, they first have to earn their party's nomination, and this happens through primary election. And primaries are elections in which members of a party vote on which candidate they want to represent them in the general election, which is the actual election where a president is chosen. Now, these primary elections happen state by state, and when you know it, different states handle primaries in different ways. Some states hold open primaries, which means that any registered voter can vote in either party's primary, but not both. So, for example, here in my fair state of Georgia, we hold open primaries. So, if I show up to the polls on primary election day, the poll worker is going to ask me whether I want a ballot for the Republican primaries or the Democratic primaries, and I can tell them whichever one I want. That's the idea of an open primary. But in other states, like New York for example, they hold closed primaries. That means that only people registered with the party can vote in those primaries. So, to sum up, here in Georgia, if I want to vote in the primary, they asked, "Hey, are you a registered voter?" And then in New York, they're going to ask me, "Are you registered with the party?" And to further confuse you, some states don't use primaries but instead hold caucuses in order to nominate their party's candidate. Now, a caucus is in principle no different than a primary; it's people voting on their chosen nominee for the party. The only difference is that instead of using secret ballots to cast their vote, voters at a caucus discuss and debate together, and then they vote publicly. So, in this first step, party members vote on their chosen candidate, and whoever wins that primary is presented as such at the party's national convention, which is just a big party for the, you know, party. They present the winning candidate and their choice for vice president, and that's the beginning of the general election, where each party's chosen candidates run against each other to become president. +

Okay, now what I just said, you know, both parties putting forward candidates to run for president, is true only in some years. Remember that a president can serve only two four-year terms. So, if a president has done that, then both parties will choose their candidate. However, if a president has only served one term, then the party usually keeps the sitting president as their nominee. So, for example, Barack Obama was the president for four years starting in 2008, and after that, he was still the Democratic Party's nominee for president in 2012. Donald Trump won the election in 2016, and so he was the party's nominee in 2020 as well. So, if a sitting president is running again, that candidate is known as the incumbent, and truth be told, the incumbent almost always has the advantage over the challenger, a phenomenon known as the incumbency advantage. The first and most obvious advantage the incumbent has is that he has already won an election, so he knows how it's done, or in the future, maybe she will know how it's done. The second advantage is that the incumbent is a known quantity, which is to say people already know how they're going to act as president. The third advantage is that the incumbent already has an army of volunteers and fundraisers ready to help with another campaign. And while this advantage is certainly helpful, it does not guarantee a victory. So, with all that done, we finally come to election day, which is always the first Tuesday in November. Everyone goes to the polls and votes for the candidate that they think will be the best president -- except kind of not really. So, yes, we all go out and vote, and on our ballots are the candidates' names, but we are not actually voting for those candidates because here in America, the people don't actually elect the president, to which I say, what? +

All right, now I get to tell you about the Electoral College, which is the constitutional mechanism by which we elect the president. The framers of the Constitution weren't too keen on participatory democracy, especially when it came to electing the president. So, they devised a system that would insulate the ignorant mob of voters from the election of the president, and that system is called the Electoral College. And here's how it works: each state has the same number of electors as they have congressional representatives. So, here in Georgia, we have 14 representatives in the House and two senators, so we have 16 electors that cast their vote for president. But don't hate me, we actually have 32 electors, and here's why: our state chooses 16 electors for the Democratic candidate and 16 electors for the Republican candidate. So, when I go to the polls to vote, I'm not actually voting for the candidate; I'm voting for that candidate's slate of electors who will then vote that candidate into office. Now, in almost every state, whichever candidate wins the state, it's a winner-take-all system for electoral votes. So, in my state, if the Republican candidate wins, all 16 electoral votes go to that candidate. However, you do need to know that in Maine and Nebraska, they have rules which allow them to split the electoral votes, but in every other state, it's a winner-take-all system. It is possible for an elector to vote against the popular vote, and if they do, they are called faithless electors. Now, that almost never happens, and some states even have laws against it, but it has happened now and then. Now, in order to win the election, the candidate has to receive a minimum of 270 electoral votes, and whatever candidate does becomes the president. +

Okay, now the last thing I'll say about the Electoral College is this: it is as a system -- uh -- contention every four years when we have a presidential election. The debate over the Electoral College returns like the instinctive flocking of the salmon of Capistrano. For example, in the 2000 presidential election, Al Gore, the Democratic nominee, won about half a million more popular votes than the Republican candidate George W. Bush. So, let me say that again: half a million more people voted for the Democratic candidate than the Republican candidate, but Bush ended up winning more electoral votes, and through a highly contested outcome that ultimately had to be decided by the Supreme Court, he defeated Gore. Now, the same thing happened in 2016. Hillary Clinton won more of the popular vote than Donald Trump, but Trump won the election with a majority in the Electoral College. So, in light of that, you may be wondering why in the world do we do it this way? Well, proponents of the Electoral College argue that this system requires candidates to campaign in many more places throughout America rather than just focusing on a few highly populated states and cities. But the detractors of the Electoral College would say that while that's true in theory, the system actually only requires candidates to spend time in a handful of swing states. If you don't know, swing states are those states which can really go either way on voting day. Even so, the Electoral College is the system we've been given in the Constitution, and short of a constitutional amendment, it's the system we'll have in the future as well. And that is how we elect a president. +

Okay, thanks for watching. Click right here to grab my review packet, which is going to help you get an A in your class and a five on your exam in May. Here in my channel, we operate by popular vote, so if you want me to keep making these videos, and you can vote for me to keep doing that by subscribing. Heimler out. +

'''

