
= 5.10 Modern Political CAMPAIGNS
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Hey there, and welcome back to Heimlich's History. Now we've been going through Unit 5 of the AP Government curriculum 课程, and this video is time to talk about modern campaigns 现代竞选活动 -- and it is a juicy 有趣的 one. So if you're ready to get them brain cows milked, then let's get to it. +

So in this video, here's what we're trying to do: explain how campaign organizations 竞选组织 and strategies 策略 affect the election process 选举过程. Now I should start by telling you that over time, political campaigns in America have increased in complexity 复杂性 by at least three metric buttloads （俚语，大量）. In fact, in the early days of the republic 共和国初期, it was considered uncouth 不礼貌的 to say anything about your own candidacy 候选人资格. George Washington was like, "If the people want me to preside 主持, they shall have to make that decision by their own wisdom and lights." But today, politicians and election seasons are like, "Hey, do you like me? Hey, look over here, look over here! Please say that you like me." +

And to be honest, I think I like the old system better. But unless we have a hot tub time machine （比喻穿越时空的方式）, we are not getting the old system back. So let's talk about how campaigns are run today. +

So let's talk about political fundraising 政治筹款, and I cannot express to you how much of an increase in spending 支出增长 has occurred on elections in the last 30 years. For example, in the 1996 presidential election between Bill Clinton and Bob Dole, a little over 87 million dollars was spent. Then in 2004, George W. Bush and John Kerry spent a combined total of 513 million. And you're like, "Dang, that's a lot of money." That is, until you compare it with the spending that occurred in the 2020 election between Donald Trump and Joe Biden. It was the most expensive campaign in history, ringing up a bill of 14.4 billion dollars 高达144亿美元. To which I say, what? +

Now, what on God's green earth （感叹，究竟） is costing so much? Well, there's a few things. First is the increasing length of the election cycle 选举周期. Like, in many countries, it's not unusual for campaign seasons 竞选季 to run 10 weeks or less, and that's because they have laws mandating 强制规定 it. But there are no such laws in the U.S., and with states competing for earlier and earlier primaries 初选 -- because, you know, those who go first often have a bump in tourism dollars 旅游收入增加 -- the election season has gradually gotten longer. For example, in 2015 when Joe Biden was asked if he would run for president in the 2016 election, he said no because it was too late to start campaigning. And that was 384 days before Election Day. Like, in his mind, starting over a year from the election left him with no chance of winning. So the longer campaigns become, the more expensive they are. +

Second is the increasing complexity of campaigns. Modern campaigns have become so complex that candidates now have to hire professional consultants 专业顾问 to run them. They hire a campaign manager 竞选经理, a public relations expert 公关专家, dedicated fundraiser 专职筹款人, social media consultants 社交媒体顾问, and on and on. These people are hyper-focused on 高度专注于 making sure that the candidate's messaging 信息传达 is clear and that the opponent 对手 is defined in less than favorable terms 以不利的方式被描述 and that the candidates perform well in televised debates 电视辩论, etc., etc. +

In addition to all of these experts, each candidate has an army of paid and volunteer positions 有偿和志愿岗位 for people who call and visit voters in order to raise funds for the candidate. And the term for that is canvassing 拉票. +

Now, another factor that has increased the complexity of modern campaigns is their reliance on 依赖 social media 社交媒体. Big social media platforms like Facebook have dedicated staff 专职人员 that help political candidates reach voters by helping them use the platform to its maximum benefit 最大限度地利用平台. And that's a nice way of saying that, because Facebook knows everything about all of its users, they know how to target political ads 投放政治广告 to people who will be receptive to them 容易接受广告的人群. +

Now, on that note 说到这, presidential candidates have always worked hard to exploit new communication technologies 利用新的通信技术 in order to communicate with their constituencies 选民. FDR used the radio, JFK used television, and it was Barack Obama in 2012 who was the first to use social media to its full extent 充分利用社交媒体. Using demographic information 人口统计信息 and psychographic information 心理统计信息, his campaign crafted highly targeted messages 精心制作高度针对性的信息 to the public through social media and, as a result, garnered massive amounts of donation 获得大量捐款. And while there were more factors than just his use of social media, this technology had a massive impact on his re-election 连任 in 2012. +

Anyway, back to the question: what are political candidates spending all of this money on? And let's get a little more specific. By far, the biggest chunk of 最大部分 a candidate's funds goes towards advertising 广告. And this can be anything from billboards 广告牌 to social media ads 社交媒体广告 to television ads 电视广告. And if you've been alive for one of these election cycles 选举周期, you know the ads I'm talking about. +

"What kind of person is Steve Heimler? His third cousin twice removed is a cannibal, and yet Heimler claims he's never eaten another person in his life. What is he hiding? This November, you have to ask yourself: do I want my child eaten by the president?" +

It is so worrisome 令人担忧的. And yet, the reason why we see many of those ads is that they work. I don't know what that says about the American people, but they work. +

So all this to say, modern campaigns have gotten way more complex and way more expensive, and they are not likely to decrease in complexity and cost anytime soon 短期内不太可能降低复杂性和成本. +

Okay, thanks for watching. Click right here to grab my review packet, which is gonna help you get an A in your class and a five on your exam in May. If this video helped you and you want to send me the signal to keep making them, then by all means, hit that subscribe button 订阅按钮, and I shall oblige 照办. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimlich 应为 Heimler）的历史频道。目前我们一直在学习美国大学预修课程（AP）政府课程的第五单元，在这个视频中，我们要谈谈现代竞选活动 —— 这可是很有意思的内容。所以，如果你准备好激发自己的思维，那么我们就开始吧。 +

所以在这个视频中，我们要做的是：解释竞选组织和策略是如何影响选举过程的。现在我得先告诉你，随着时间的推移，美国的政治竞选活动的复杂程度至少增加了很多。事实上，在共和国早期，谈论自己的候选人身份会被认为是不得体的。乔治·华盛顿（George Washington）曾说过，“如果人民希望我主持事务，他们应该凭借自己的智慧和判断来做决定。” 但如今，政治家和选举季就好像在说，“嘿，你喜欢我吗？嘿，看这边，看这边！请说你喜欢我。” +

老实说，我觉得我更喜欢旧的制度。但除非我们有一个 “时空热水浴缸机”（指能回到过去的工具），否则我们无法回到旧制度。所以，我们来谈谈如今的竞选活动是如何进行的。 +

我们来谈谈政治筹款，我都无法向你表达在过去30年里选举方面的支出增加了多少。例如，在1996年比尔·克林顿（Bill Clinton）和鲍勃·多尔（Bob Dole）的总统选举中，花费了略多于8700万美元。然后在2004年，乔治·W·布什（George W. Bush）和约翰·克里（John Kerry）的竞选总花费达到了5.13亿美元。你可能会想，“天啊，这钱可真多。” 然而，当你把它和2020年唐纳德·特朗普（Donald Trump）和乔·拜登（Joe Biden）竞选时的花费相比，情况就不同了。2020年的竞选是历史上最昂贵的竞选，花费达到了144亿美元。我想说，这是什么情况？ +

那么，到底是什么东西花了这么多钱呢？嗯，有几个方面。首先是选举周期越来越长。比如，在许多国家，竞选季持续10周或更短时间是很常见的，这是因为有法律强制规定。但在美国没有这样的法律，而且各州都在争取让初选时间越来越早 —— 因为，你知道，那些先举行初选的州往往能在旅游收入上有所增加 —— 选举季逐渐变长了。例如，在2015年，当乔·拜登被问到是否会参加2016年的总统竞选时，他说不参加，因为开始竞选已经太晚了，而那时距离选举日还有384天。在他看来，距离选举还有一年多的时间才开始竞选，他就没有机会获胜了。所以竞选活动持续的时间越长，花费就越高。 +

其次是竞选活动的复杂程度不断增加。现代竞选活动变得非常复杂，候选人现在必须聘请专业顾问来运作竞选。他们会聘请竞选经理、公关专家、专门的筹款人、社交媒体顾问等等。这些人高度专注于确保候选人传达的信息清晰明了，对手被描述得不太好，以及候选人在电视辩论中表现出色等等。 +

除了这些专家之外，每个候选人都有一批受薪和志愿人员，他们打电话并拜访选民，为候选人筹集资金。这个过程被称为拉票（canvassing）。 +

现在，另一个增加现代竞选活动复杂程度的因素是对社交媒体的依赖。像脸书（Facebook）这样的大型社交媒体平台有专门的工作人员，他们帮助政治候选人利用平台最大限度地接触选民。这么说比较委婉，因为脸书了解其所有用户的一切信息，他们知道如何将政治广告定位到会接受这些广告的人群。 +

说到这里，总统候选人一直都在努力利用新的通信技术与他们的选民沟通。富兰克林·德拉诺·罗斯福（FDR，即 Franklin Delano Roosevelt）使用广播，约翰·F·肯尼迪（JFK，即 John F. Kennedy）使用电视，而巴拉克·奥巴马（Barack Obama）在2012年是第一个充分利用社交媒体的人。通过人口统计学信息和心理统计学信息，他的竞选团队通过社交媒体向公众精心制作高度针对性的信息，结果获得了大量捐款。虽然除了使用社交媒体之外还有其他因素，但这项技术对他在2012年的连任产生了巨大影响。 +

不管怎样，回到这个问题：政治候选人把这些钱都花在什么地方了呢？让我们说得更具体一点。到目前为止，候选人资金的最大一部分都花在了广告上。这些广告可以是从广告牌到社交媒体广告再到电视广告的任何形式。如果你经历过其中一个选举周期，你就知道我在说哪种广告。 +

“史蒂夫·海姆勒（Steve Heimler）是怎样的人呢？他的远房表亲是个食人者，然而海姆勒声称他这辈子从来没有吃过人。他在隐瞒什么呢？今年11月，你得问问自己：我想让我的孩子被总统吃掉吗？” +

这真的很令人担忧。然而，我们看到这么多这类广告的原因是它们是有效果的。我不知道这能说明美国人民的什么情况，但它们确实有效果。 +

所以，这么说吧，现代竞选活动变得更加复杂，花费也更高了，而且短期内其复杂程度和花费不太可能降低。 +

好的，感谢观看。点击这里获取我的复习资料包，这将帮助你在课堂上取得A的成绩，并在五月份的考试中获得5分。如果这个视频对你有帮助，而且你想向我传达让我继续制作这类视频的信号，那么一定要点击订阅按钮，我会照办的。海姆勒，退出。 + 

'''

== pure

Hey there, and welcome back to Heimlich's History. Now we've been going through Unit 5 of the AP Government curriculum, and this video is time to talk about modern campaigns -- and it is a juicy one. So if you're ready to get them brain cows milked, then let's get to it.

So in this video, here's what we're trying to do: explain how campaign organizations and strategies affect the election process. Now I should start by telling you that over time, political campaigns in America have increased in complexity by at least three metric buttloads. In fact, in the early days of the republic, it was considered uncouth to say anything about your own candidacy. George Washington was like, "If the people want me to preside, they shall have to make that decision by their own wisdom and lights." But today, politicians and election seasons are like, "Hey, do you like me? Hey, look over here, look over here! Please say that you like me."

And to be honest, I think I like the old system better. But unless we have a hot tub time machine, we are not getting the old system back. So let's talk about how campaigns are run today.

So let's talk about political fundraising, and I cannot express to you how much of an increase in spending has occurred on elections in the last 30 years. For example, in the 1996 presidential election between Bill Clinton and Bob Dole, a little over 87 million dollars was spent. Then in 2004, George W. Bush and John Kerry spent a combined total of 513 million. And you're like, "Dang, that's a lot of money." That is, until you compare it with the spending that occurred in the 2020 election between Donald Trump and Joe Biden. It was the most expensive campaign in history, ringing up a bill of 14.4 billion dollars. To which I say, what?

Now, what on God's green earth is costing so much? Well, there's a few things. First is the increasing length of the election cycle. Like, in many countries, it's not unusual for campaign seasons to run 10 weeks or less, and that's because they have laws mandating it. But there are no such laws in the U.S., and with states competing for earlier and earlier primaries -- because, you know, those who go first often have a bump in tourism dollars -- the election season has gradually gotten longer. For example, in 2015 when Joe Biden was asked if he would run for president in the 2016 election, he said no because it was too late to start campaigning. And that was 384 days before Election Day. Like, in his mind, starting over a year from the election left him with no chance of winning. So the longer campaigns become, the more expensive they are.

Second is the increasing complexity of campaigns. Modern campaigns have become so complex that candidates now have to hire professional consultants to run them. They hire a campaign manager, a public relations expert, dedicated fundraiser, social media consultants, and on and on. These people are hyper-focused on making sure that the candidate's messaging is clear and that the opponent is defined in less than favorable terms and that the candidates perform well in televised debates, etc., etc.

In addition to all of these experts, each candidate has an army of paid and volunteer positions for people who call and visit voters in order to raise funds for the candidate. And the term for that is canvassing.

Now, another factor that has increased the complexity of modern campaigns is their reliance on social media. Big social media platforms like Facebook have dedicated staff that help political candidates reach voters by helping them use the platform to its maximum benefit. And that's a nice way of saying that, because Facebook knows everything about all of its users, they know how to target political ads to people who will be receptive to them.

Now, on that note, presidential candidates have always worked hard to exploit new communication technologies in order to communicate with their constituencies. FDR used the radio, JFK used television, and it was Barack Obama in 2012 who was the first to use social media to its full extent. Using demographic information and psychographic information, his campaign crafted highly targeted messages to the public through social media and, as a result, garnered massive amounts of donation. And while there were more factors than just his use of social media, this technology had a massive impact on his re-election in 2012.

Anyway, back to the question: what are political candidates spending all of this money on? And let's get a little more specific. By far, the biggest chunk of a candidate's funds goes towards advertising. And this can be anything from billboards to social media ads to television ads. And if you've been alive for one of these election cycles, you know the ads I'm talking about.

"What kind of person is Steve Heimler? His third cousin twice removed is a cannibal, and yet Heimler claims he's never eaten another person in his life. What is he hiding? This November, you have to ask yourself: do I want my child eaten by the president?"

It is so worrisome. And yet, the reason why we see many of those ads is that they work. I don't know what that says about the American people, but they work.

So all this to say, modern campaigns have gotten way more complex and way more expensive, and they are not likely to decrease in complexity and cost anytime soon.

Okay, thanks for watching. Click right here to grab my review packet, which is gonna help you get an A in your class and a five on your exam in May. If this video helped you and you want to send me the signal to keep making them, then by all means, hit that subscribe button, and I shall oblige. Heimler out.

'''

