
= fd 02 - Federalist 10
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Well hey there, and welcome back to Heimlich's History. In this video, we're continuing to look at the foundational documents 基础文献 for AP Government, and that means it's time to talk about Federalist Number 10 《联邦党人文集》第10篇. So if you're ready to get them brain cows milked violence of faction 派系暴力 style, well then let's get to it. +

So since this is our first document from the Federalist Papers 《联邦党人文集》, let me give you a quick introduction to what this series of essays 系列文章 was. During the ratification debates 批准辩论 over the new Constitution 宪法, John Jay, Alexander Hamilton, and James Madison -- who represented the Federalists 联邦党人 who were very much in favor of 支持 the new Constitution -- published essays in a New York newspaper in order to convince the public to ratify 批准. In doing so, they addressed 回应 the most common objections 反对意见 to this new form of government and gave a sense of how the nation would work under this new Constitution. +

Okay, so Federalist 10 is James Madison's attempt to answer the following question: how will the new Constitution protect the liberty 自由 of citizens against the tyranny of the majority 多数人的暴政? Now remember, the framers of the Constitution 宪法的制定者 were emphatically  emphatically 坚决地； emphatically  emphatically 强调地 not fans of pure democracy 纯粹民主, and in this case it's because in a pure democracy, the majority will always win out over 胜过 the minority 少数人, and thus there is no protection from minority views 少数派观点. And by the way, when I say minority here, I'm not talking about ethnic minorities 少数民族 but rather a smaller number of citizens -- like the opposite of majority. +

So Madison comes out of the gates 一开始 talking about the dangers of factions 派系, and that is a key word you need to associate with 与…联系起来 Federalist 10. He says, "Among the numerous advantages promised by a well-constructed union 构建良好的联盟, none deserves to be more accurately developed than its tendency to break and control the violence of faction." So factions are such a threat to liberty that Madison uses the word violence 暴力 to describe their actions. +

Now what does Madison mean by the word faction? Well he goes on to define it: "By a faction I understand a number of citizens, whether amounting to 达到 a majority or a minority of the whole, who are united and actuated 驱使 by some common impulse of passion or of interest adverse to 不利于 the rights of other citizens or to the permanent and aggregate interests 整体利益 of the community." In other words, a faction is a group of citizens whose desires to dominate government 掌控政府 so that they might impose 强加 their own interests on the whole society. And to Madison -- as well as to the Anti-Federalists 反联邦党人 -- this is a great danger. +

Now the Anti-Federalists would not agree with Madison's solution, and we'll see that in the video on Brutus 1. But for now, what is Madison's solution to the violence of faction? Well he proposes 提出 two possible solutions: "There are two methods of curing the mischiefs of faction 消除派系的危害: the one by removing its causes 消除其根源, the other by controlling its effects 控制其影响." So the two options available are: one, stop the factions from ever forming; and two, let them try to form and then limit their power. +

He says that if we're going with number one -- to remove the causes of factions -- that is a terrible option. Why? Because that will necessarily destroy liberty: "It could never be more truly said than of the first remedy 补救措施 that it was worse than the disease. Liberty is to faction what air is to fire, an ailment 疾病 without which it instantly expires 消亡. But it could not be less folly 愚蠢 to abolish liberty 废除自由, which is essential to political life 政治生活, because it nourishes faction 滋养派系 than it would be to wish the annihilation 消灭 of air, which is essential to animal life, because it imparts to fire its destructive agency 破坏力." To destroy liberty in service of controlling factions is worse than having factions in the first place. +

The other way to remove the causes of factions is to make sure that every citizen has the same opinions on everything. But as anyone who's been alive for more than five minutes knows, that is not possible. Madison tells us why: "As long as the reason of man continues fallible 易犯错的 and he is at liberty to exercise it 自由运用理性, different opinions will be formed." +

Okay, so removing the causes of faction won't work. So Madison suggests that the only protection against their tyranny 暴政 is to control their effects, and the best way to do that is through a republican-style government 共和制政府 as opposed to 而不是 a pure democracy: "A republic 共和国, by which I mean a government in which the scheme of representation 代议制 takes place, opens a different prospect 前景 and promises the cure for which we are seeking." +

Okay, so how does a republican-style government laid out 阐述 in the Constitution solve the problem of factions? Well it mainly has to do with 与…有关 the size and diversity 规模和多样性 of the nation. Madison says that as the nation grows in population, you take in 吸纳 a greater variety of parties and interests. You make it less probable 可能性更小 that a majority of the whole will have a common motive 共同动机 to invade the rights of other citizens. Or if such a common motive exists, it will be more difficult for all who feel it to discover their own strength and to act in unison with each other 一致行动. And so the result of that is: "The influence of factious leaders 派系领袖 may kindle a flame 点燃火焰 within their particular states but will be unable to spread a general conflagration 全面大火 to the other states." +

Now in case you didn't catch it, Madison's solution to the danger of factions is this: as more people are added to the nation, more and more factions will necessarily form, and that has two consequences 后果. First, with so many factions, their power will be diluted 削弱 so that no one faction can always get their way 随心所欲. And second, because they're all in competition with one another 相互竞争, they will be forced to compromise their interest 妥协利益 in order to pass legislation 立法 that considers the common good of society 社会公共利益 and not merely the interests of one group. +

Okay, well that's Federalist 10. If you need help getting an A in your class and a five on your exam, then click right here and grab my review packet and watch all your dreams come true. If you want me to keep making these videos, then by all means subscribe 订阅 and I shall continue. Heimler out. +

'''

== 中文释义

嘿，欢迎回到海姆勒（Heimlich 应为 Heimler）的历史频道。在这个视频中，我们将继续研究美国大学预修课程（AP）政府课程的基础文献，这意味着我们要谈谈《联邦党人文集》第十篇（Federalist Number 10）。所以，如果你准备好以 “派别暴力” 的方式激发自己的思维，那么我们就开始吧。 +

既然这是我们研究《联邦党人文集》（Federalist Papers）的第一篇文献，让我快速介绍一下这一系列文章。在关于新宪法的批准辩论中，约翰·杰伊（John Jay）、亚历山大·汉密尔顿（Alexander Hamilton）和詹姆斯·麦迪逊（James Madison）—— 他们代表着非常支持新宪法的联邦党人 —— 在纽约的一家报纸上发表文章，以说服公众批准新宪法。通过这样做，他们回应了对这种新政府形式最常见的反对意见，并阐述了在新宪法下国家将如何运作。 +

好的，《联邦党人文集》第十篇是詹姆斯·麦迪逊试图回答以下问题：新宪法将如何保护公民的自由，使其免受多数人的暴政？记住，宪法的制定者们明确表示不喜欢纯粹的民主，在这种情况下，是因为在纯粹的民主制度下，多数人总是会胜过少数人，因此少数人的观点得不到保护。顺便说一下，我这里说的少数人，不是指少数族裔，而是指数量较少的公民 —— 与多数人相对。 +

所以麦迪逊一开始就谈到了派别（factions）的危险，这是一个你需要与《联邦党人文集》第十篇联系起来的关键词。他说：“在一个构建良好的联盟所带来的众多好处中，没有什么比它在打破和控制派别暴力方面的倾向更值得深入探讨了。” 所以派别对自由构成了威胁，麦迪逊用 “暴力” 这个词来描述他们的行为。 +

那么麦迪逊所说的 “派别” 是什么意思呢？嗯，他接着对其进行了定义：“我所说的派别，是指一些公民，无论他们在全体公民中占多数还是少数，他们因为某种共同的激情冲动或利益而联合起来，这种激情或利益与其他公民的权利或社会的长远和整体利益相悖。” 换句话说，派别是一群公民，他们渴望控制政府，以便将自己的利益强加给整个社会。对麦迪逊以及反联邦党人来说，这是一个巨大的危险。 +

反联邦党人不同意麦迪逊的解决方案，我们将在关于《布鲁图斯》第一篇（Brutus 1）的视频中看到这一点。但就目前而言，麦迪逊对派别暴力的解决方案是什么呢？嗯，他提出了两种可能的解决方案：“有两种方法可以消除派别的危害：一种是消除其产生的原因，另一种是控制其影响。” 所以有两个选择：第一，阻止派别形成；第二，让派别形成，然后限制它们的权力。 +

他说，如果我们选择第一种方法 —— 消除派别的产生原因 —— 这是一个糟糕的选择。为什么呢？因为这必然会破坏自由：“对于第一种补救措施，再没有比这更确切的说法了，那就是它比问题本身更糟糕。自由对于派别来说就像空气对于火一样，没有自由，派别就会立刻消亡。但是，为了控制派别而废除对政治生活至关重要的自由，就如同希望消灭对动物生命至关重要的空气一样愚蠢，因为空气会赋予火以破坏力。” 为了控制派别而破坏自由，比一开始就存在派别还要糟糕。 +

消除派别产生原因的另一种方法是确保每个公民在所有事情上都有相同的意见。但任何在世超过五分钟的人都知道，这是不可能的。麦迪逊告诉我们原因：“只要人类的理性仍然容易犯错，并且人们有自由运用理性，就会形成不同的意见。” +

好的，所以消除派别产生的原因是行不通的。所以麦迪逊建议，防止派别暴政的唯一办法是控制它们的影响，而做到这一点的最佳方式是建立一个共和制政府，而不是纯粹的民主制政府：“我所说的共和制，是指一种实行代表制的政府，它展现出了不同的前景，并有望解决我们所面临的问题。” +

好的，那么宪法中所规定的共和制政府是如何解决派别问题的呢？嗯，这主要与国家的规模和多样性有关。麦迪逊说，随着国家人口的增长，会出现更多不同的政党和利益集团。这使得全体公民中的多数人有共同动机去侵犯其他公民权利的可能性降低。或者，如果存在这样的共同动机，那些有这种动机的人更难发现自己的力量，也更难相互协调行动。所以结果是：“派别领袖的影响力可能会在他们所在的特定州点燃一把火，但无法将大火蔓延到其他州。” +

万一你没有理解，麦迪逊对派别危险的解决方案是这样的：随着国家人口的增加，必然会形成越来越多的派别，这会产生两个后果。第一，派别众多，它们的权力会被稀释，这样就没有一个派别能够总是为所欲为。第二，因为它们彼此竞争，它们将被迫妥协自己的利益，以便通过考虑社会共同利益的立法，而不仅仅是某一个群体的利益。 +

好的，这就是《联邦党人文集》第十篇的内容。如果你想在课堂上取得A的成绩，并在考试中获得5分，那么点击这里获取我的复习资料包，然后见证你的梦想成真。如果你希望我继续制作这样的视频，那么一定要订阅，我会继续做下去的。海姆勒，退出。 + 

'''

== pure

Well hey there, and welcome back to Heimlich's History. In this video, we're continuing to look at the foundational documents for AP Government, and that means it's time to talk about Federalist Number 10. So if you're ready to get them brain cows milked violence of faction style, well then let's get to it.

So since this is our first document from the Federalist Papers, let me give you a quick introduction to what this series of essays was. During the ratification debates over the new Constitution, John Jay, Alexander Hamilton, and James Madison -- who represented the Federalists who were very much in favor of the new Constitution -- published essays in a New York newspaper in order to convince the public to ratify. In doing so, they addressed the most common objections to this new form of government and gave a sense of how the nation would work under this new Constitution.

Okay, so Federalist 10 is James Madison's attempt to answer the following question: how will the new Constitution protect the liberty of citizens against the tyranny of the majority? Now remember, the framers of the Constitution were emphatically not fans of pure democracy, and in this case it's because in a pure democracy, the majority will always win out over the minority, and thus there is no protection from minority views. And by the way, when I say minority here, I'm not talking about ethnic minorities but rather a smaller number of citizens -- like the opposite of majority.

So Madison comes out of the gates talking about the dangers of factions, and that is a key word you need to associate with Federalist 10. He says, "Among the numerous advantages promised by a well-constructed union, none deserves to be more accurately developed than its tendency to break and control the violence of faction." So factions are such a threat to liberty that Madison uses the word violence to describe their actions.

Now what does Madison mean by the word faction? Well he goes on to define it: "By a faction I understand a number of citizens, whether amounting to a majority or a minority of the whole, who are united and actuated by some common impulse of passion or of interest adverse to the rights of other citizens or to the permanent and aggregate interests of the community." In other words, a faction is a group of citizens whose desires to dominate government so that they might impose their own interests on the whole society. And to Madison -- as well as to the Anti-Federalists -- this is a great danger.

Now the Anti-Federalists would not agree with Madison's solution, and we'll see that in the video on Brutus 1. But for now, what is Madison's solution to the violence of faction? Well he proposes two possible solutions: "There are two methods of curing the mischiefs of faction: the one by removing its causes, the other by controlling its effects." So the two options available are: one, stop the factions from ever forming; and two, let them try to form and then limit their power.

He says that if we're going with number one -- to remove the causes of factions -- that is a terrible option. Why? Because that will necessarily destroy liberty: "It could never be more truly said than of the first remedy that it was worse than the disease. Liberty is to faction what air is to fire, an ailment without which it instantly expires. But it could not be less folly to abolish liberty, which is essential to political life, because it nourishes faction than it would be to wish the annihilation of air, which is essential to animal life, because it imparts to fire its destructive agency." To destroy liberty in service of controlling factions is worse than having factions in the first place.

The other way to remove the causes of factions is to make sure that every citizen has the same opinions on everything. But as anyone who's been alive for more than five minutes knows, that is not possible. Madison tells us why: "As long as the reason of man continues fallible and he is at liberty to exercise it, different opinions will be formed."

Okay, so removing the causes of faction won't work. So Madison suggests that the only protection against their tyranny is to control their effects, and the best way to do that is through a republican-style government as opposed to a pure democracy: "A republic, by which I mean a government in which the scheme of representation takes place, opens a different prospect and promises the cure for which we are seeking."

Okay, so how does a republican-style government laid out in the Constitution solve the problem of factions? Well it mainly has to do with the size and diversity of the nation. Madison says that as the nation grows in population, you take in a greater variety of parties and interests. You make it less probable that a majority of the whole will have a common motive to invade the rights of other citizens. Or if such a common motive exists, it will be more difficult for all who feel it to discover their own strength and to act in unison with each other. And so the result of that is: "The influence of factious leaders may kindle a flame within their particular states but will be unable to spread a general conflagration to the other states."

Now in case you didn't catch it, Madison's solution to the danger of factions is this: as more people are added to the nation, more and more factions will necessarily form, and that has two consequences. First, with so many factions, their power will be diluted so that no one faction can always get their way. And second, because they're all in competition with one another, they will be forced to compromise their interest in order to pass legislation that considers the common good of society and not merely the interests of one group.

Okay, well that's Federalist 10. If you need help getting an A in your class and a five on your exam, then click right here and grab my review packet and watch all your dreams come true. If you want me to keep making these videos, then by all means subscribe and I shall continue. Heimler out.
'''

