

= Chapter 4 - The Global Tapestry, c. 1200 to c. 1450
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 释义

'''

== pure

=== DEVELOPMENTS IN EAST ASIA (c. 1200 to c. 1450)

The original form, Theravada Buddhism, was less popular in East Asia than Mahayana Buddhism, which emphasizes more hope for eternal life.

By 1200, Neo-Confucianism had become popular in China. It blended concepts from Buddhism, the ancient Chinese Daoist beliefs, and Confucianism into one, making Neo-Confucianism more of a religion than only a philosophy.


=== DEVELOPMENTS IN DAR AL-ISLAM (c. 1200 to c. 1450)

Islam originated in Arabia in the 7th century.  Islam saw several political changes in the era c. 1200–c. 1450. See below.

Christianity retreated in the region of Turkey, supplanted by Islam, but gained in Spain, reasserting its dominance over Islam by c. 1450.

The Abbasid caliphate (i.e., a Muslim political state under religious rule) began declining before c. 1200 and then fell when Mongols sacked the capital city of Baghdad in 1258. Other Muslim governments rose in this era.

As the Abbasids declined, Turkish groups from Central Asia moved into Southwest Asia and formed the Muslim Ottoman Empire in Turkey in the late 13th century and rapidly expanded.


=== DEVELOPMENTS IN EUROPE (c. 1200 to c. 1450)


Historically, Europe was similar to South Asia in that it had rarely been unified under one government.

The pandemic bubonic plague known as the Black Death in Afro-Eurasia in the 14th century hit Western Europe the hardest. The political and cultural power of the Catholic Church in Western Europe was weakened.

The feudal system of lords, manors, and serfs began to break down, leading to the freeing of serfs by c. 1500.

The Hundred Years War between Britain and France contributed to the fall of feudalism, and strengthened the rise of a single monarch in each country.

The Holy Roman Empire in Central Europe continued as a loose union of several small kingdoms. Italy was politically fragmented as well.







'''




