

= UNIT 5 - Revolutions (c. 1750 to c. 1900)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''


== 释义






There were many types of revolutions in the era c. 1750–c. 1900: political, intellectual, and industrial, for starters. Ideas from European-based Enlightenment philosophies sparked revolutionary ideas founded on concepts of liberty and equality that remain vital today.

[.my2]
大约在1750年到1900年间，出现了多种类型的革命：政治革命、思想革命和工业革命等等。源自欧洲启蒙运动哲学的思想激发了革命性的理念，这些理念建立在自由和平等的概念之上，至今仍然至关重要。

=== I. NEW VIEWS ON NATURE AND HUMAN RELATIONSHIPS

[.my2]
关于自然与人际关系的新观点

The Enlightenment was an era of new ideas in Western thought about approaches to religion, art, government, science, and philosophy. The movement peaked in the 18th century in Europe, but because its culture spread globally during the Age of Imperialism , Enlightenment ideas did too.

[.my2]
启蒙运动是西方思想中关于宗教、艺术、政府、科学和哲学等领域出现新思想的时代。这场运动在 18 世纪的欧洲达到顶峰，但由于其文化在帝国主义时代传播到全球，启蒙思想也随之传播开来。

==== A. ENLIGHTENMENT

[.my2]
A.启蒙运动

Concepts from the Scientific Revolution  sparked European intellectuals to think that the human condition could be explained and improved if scientifically-based rational thought governed everyday life. Applied to politics, such ideals were labelled “classical liberalism.” For example:

[.my2]
科学革命的概念激发了欧洲知识分子的思考：如果以科学为基础的理性思维指导日常生活，人类的生存状况就能得到解释和改善。将这些理念应用于政治领域，就被称为“古典自由主义”。例如：

- 1. Individual equality. Enlightenment thinkers (philosophes, French for “philosophers”), such as the French writers Voltaire and Rousseau, advocated that all men were created equal—that no person deserved extra privileges over others just for being born. A king was not automatically “better” than a commoner. The U.S. Declaration of Independence reflects this belief.

[.my2]
个人平等。 启蒙思想家（法语为 philosophes ，意为“哲学家”），例如法国作家伏尔泰和卢梭，主张人人生而平等——任何人都不应仅仅因为出身就享有凌驾于他人之上的特权。国王并非天生就比平民“优越”。美国《独立宣言》体现了这一信念。

- 2. Individual liberty. This Enlightenment ideal says people should be free to make their own personal and economic decisions in life. Freedom of speech and religion were “natural rights” given by God, not man. Slavery should be abolished. Women should be treated as political equals to men.

[.my2]
个人自由。 这一启蒙思想认为，人们应该有权自由地做出个人和经济方面的决定。言论自由和宗教自由是上帝而非人赋予的“自然权利”。奴隶制应该被废除。女性应该享有与男性平等的政治权利。

- 3. Limited governments. Enlightenment thinkers Locke and Rousseau wrote that governments and the people had a “social contract” between them. If the leader of the government failed to serve the people well, the people had a right to revolt. Favored forms of government among Enlightenment thinkers included a constitution, freedom of thought, and divided powers between a king and a legislature. Other philosophes favored these ideas, but without a king. They sought a government led by a leader elected by popular vote.

[.my2]
有限政府。 启蒙思想家洛克和卢梭认为，政府与人民之间存在“社会契约”。如果政府领导人未能尽心为人民服务，人民有权反抗。启蒙思想家推崇的政府形式包括宪法、思想自由以及君主与立法机构的权力分立。其他一些哲学家也赞同这些理念，但他们主张建立由民众选举产生的领导人领导的政府。

==== B. NATIONALISM

[.my2]
民族主义

1.Nationalism arose from Enlightenment thought about personal liberties and choices. It inspired many to call for the creation of new nations out of large empires.

[.my2]
1.民族主义源于启蒙运动关于个人自由和选择的思想。它激励了许多人呼吁从庞大的帝国中建立新的国家。

2.Nationalism is defined as a sense of strong identity with others who share a common history, customs, religion, and/or language. This concept was a major factor in the independence movements in Latin America and Europe in the 19th century, and colonies worldwide in the 20th century.

[.my2]
2.民族主义被定义为对拥有共同历史、习俗、宗教和/或语言的其他群体的强烈认同感。这一概念是 19 世纪拉丁美洲和欧洲独立运动以及 20 世纪世界各地殖民地独立运动的重要因素。

=== II. NATIONALISM AND REVOLUTIONS FROM 1750 TO 1900: POLITICS IN THE ATLANTIC WORLD

[.my2]
1750年至1900年的民族主义与革命：大西洋世界的政治

==== A. AMERICAN REVOLUTION

[.my2]
美国革命

1.The first place these ideas about revolution were tried on a large scale was in the British colonies in America.

[.my2]
1. 这些关于革命的想法最早在英国的美洲殖民地进行了大规模的尝试。

2.The Declaration of Independence spelled out Enlightenment ideas of “life, liberty and the pursuit of happiness.” In the context of World History, the effects of the American Revolution were enormous.

[.my2]
2. 《独立宣言》阐述了启蒙运动关于“生命、自由和追求幸福”的思想。从世界历史的角度来看，美国革命的影响是巨大的。

3.The notion that a group of colonies could overthrow a European power and establish—on purpose, no less—a representative government based on Enlightenment principles, inspired revolutions around the world into the 21st century.

[.my2]
3. 一群殖民地能够推翻欧洲列强，并有目的地建立基于启蒙运动原则的代议制政府，这一想法激发了 21 世纪世界各地的革命。

==== B. FRENCH REVOLUTION AND AFTERMATH

[.my2]
B.法国大革命及其后果

1.In 1789, the French revolted against their king, Louis XVI, but unlike the American Revolution, the struggle was not with a colony but in the home country. In the spirit of Enlightenment ideas, the slogan of the French Revolution was, “Liberty, Equality, Fraternity (brotherhood).” The French Revolution expressed its roots in the Enlightenment in the civil rights document, “Declaration of the Rights of Man and the Citizen.”

[.my2]
1.1789 年，法国人民起义反抗国王路易十六，但与美国革命不同，这场斗争并非针对殖民地，而是针对本土。秉承启蒙思想，法国大革命的口号是“自由、平等、博爱”。法国大革命在民权文件《人权和公民权宣言》中体现了其启蒙思想的根基。

2.After failing to create a limited constitutional monarchy similar to Britain’s, French leaders established a republic. But they insisted on radically reshaping political and cultural traditions to fit their goals.

[.my2]
2.法国领导人建立类似英国的"有限君主立宪制"失败后，转而建立了共和国。但他们坚持彻底改造政治和文化传统，以适应自身的目标。

3.The French Republic was overthrown by Napoleon Bonaparte, a military dictator who restored order. Claiming to be a “child of the Enlightenment,” he did enact reforms, such as equality, before the law. But he was no supporter of republican government. After Napoleon’s defeat by a coalition of other European nations, European boundaries were reorganized which added new nations such as a new version of the Netherlands.

[.my2]
3.法兰西共和国被军事独裁者拿破仑·波拿巴推翻，他恢复了秩序。他自称是“启蒙运动的产物”，确实推行了一些改革，例如法律面前人人平等。但他并非共和政体的支持者。拿破仑被其他欧洲国家的联盟击败后，欧洲的版图重新划分，新增了一些国家，例如新版的荷兰。

==== C. HAITI AND LATIN AMERICA

[.my2]
C.海地和拉丁美洲

1.Haiti

[.my2]
1.海地

- The French Revolution’s first “child” was delivered in the early 19th century in its colony of Haiti, then known as Saint-Domingue. The vast majority of the residents were slaves. Led by Toussaint L’Ouverture, they revolted against their white French masters. An army sent by Napoleon to quell the rebellion was defeated.

[.my2]
法国大革命的第一个“产物”诞生于 19 世纪初的法国殖民地海地，当时被称为圣多明各。那里绝大多数居民都是奴隶。在杜桑·卢维杜尔的领导下，他们反抗了法国白人统治者的压迫。拿破仑派出的军队镇压了这场起义，但最终失败了。

- The result of this first successful slave revolt was the establishment of the second republic in the New World, after the U.S.

[.my2]
这次奴隶起义的成功，促成了继美国之后新大陆第二个共和国的建立。




2.Latin America

[.my2]
2.拉丁美洲

- By 1830, the successful Haitian revolution inspired the rest of Latin America’s colonies to rise against Spanish and Portuguese rule. Led by upper class “Creole elites”—most famously Simón Bolívar—one by one the colonies gained independence through military victories against the colonizers, hastening the decline of Spain as a world power. Bolívar wrote a Latin American “Declaration of Independence” known as “The Jamaica Letter.”

[.my2]
1830 年，海地革命的成功激励了拉丁美洲其他殖民地起来反抗西班牙和葡萄牙的统治。在以西蒙·玻利瓦尔为首的克里奥尔精英阶层的领导下，##**各殖民地通过军事胜利逐一战胜殖民者，赢得了独立 (还是要靠打仗，枪杆子里面出政权)，**##加速了西班牙作为世界强国的衰落。玻利瓦尔撰写了拉丁美洲的“独立宣言”，即著名的《牙买加信》。


==== D. “EUROPE IN FLAMES”

[.my2]
D.“欧洲燃起战火”

1.The nationalist revolutions in Latin America expelled the colonial powers. These successes inspired Europeans to use nationalism to replace governments thought to be “outside oppressors.” Greece broke away from the Ottoman Empire (1820). But in the vast Austrian empire, Poles, Italians, and Slavs, failed to break away and form their own nations in the early 19th century.  +
In 1848, so many nations experienced violence—in some cases civil war—that the phrase “Europe in flames” became popular. In the 1860s and 1870s, two new nations emerged, both forged with strong nationalist fervor: Italy and Germany.

[.my2]
1.**拉丁美洲的民族主义革命, 驱逐了殖民列强。这些胜利, 激励欧洲人利用"民族主义"来取代被认为是“外部压迫者”的政府。**希腊于 1820 年脱离奥斯曼帝国。但在幅员辽阔的奥匈帝国，波兰人、意大利人和斯拉夫人, 在 19 世纪初未能脱离奥匈帝国，建立自己的国家。 +
*1848 年，许多国家经历了暴力冲突——有些甚至爆发了内战*——以至于“战火纷飞的欧洲”一词广为流传。在 19 世纪 60 年代和 70 年代，两个在强烈的"民族主义"热情下诞生的新国家——意大利和德国——应运而生。

2.In 1830 and 1848, dissatisfied French rebels overthrew their governments. In the second of these revolutions, France established another short-lived republic.

[.my2]
2.1830 年和 1848 年，不满的法国叛军推翻了政府(枪杆子里面出政权)。在第二次革命中，法国建立了另一个短暂的共和国。



=== III. THE INDUSTRIAL REVOLUTION BEGINS

[.my2]
工业革命开始了

==== A. HISTORIC IMPACT

[.my2]
A.历史影响

1.In the era c. 1750–c. 1900, the greatest revolution since the Neolithic era (c. 8000 BCE) occurred: the Industrial Revolution. It fundamentally changed the human experience and continues to affect the world today.

[.my2]
1.**大约在公元 1750 年至 1900 年间，自新石器时代（约公元前 8000 年 ）以来最伟大的革命——工业革命——发生了。**它从根本上改变了人类的生存方式，并且至今仍在影响着世界。

2.The Industrial Revolution changed governments, family life, global and local economies, food production, migration, war, art and literature, the environment, transportation, communication, population growth, and rural and urban areas. It led to the Age of Imperialism, political revolutions, communism, World War I, women’s rights, multinational corporations, and the “traditional” Western family.

[.my2]
2.##**工业革命**##改变了政府、家庭生活、全球和地方经济、粮食生产、移民、战争、艺术和文学、环境、交通运输、通讯、人口增长以及城乡地区。##**它催生了帝国主义时代、**##政治革命、共产主义、第一次世界大战、妇女权利、跨国公司以及“传统”的西方家庭。


==== B. CAUSES OF THE INDUSTRIAL REVOLUTION

[.my2]
B.工业革命的原因

Why did the Industrial Revolution begin in Western Europe, and why specifically in Britain? Several factors contributed.

[.my2]
为什么工业革命始于西欧，而且特别在于英国？这其中有多种因素。

1.Government policies—As noted in previous chapters, Western Europe built political and economic empires in the New World. The flow of silver and gold from the New World into Europe’s treasuries made their societies the richest in the world. European governments—especially Britain—invested part of this income in the form of monetary prizes to individuals who invented more efficient ways to transport goods, grow crops, defeat enemies—anything that might significantly contribute to growing the nation’s slice of the global mercantilist pie.

[.my2]
1. 政府政策——如前几章所述，西欧在新大陆建立了政治和经济帝国。来自新大陆的白银和黄金流入欧洲国库，使欧洲社会成为世界上最富有的社会。**欧洲各国政府——尤其是英国——将部分收入以奖金的形式, 奖励给那些发明更高效的**货物运输、作物种植、击败敌人**等方法的人——任何可能显著增加英国在全球"重商主义"蛋糕中所占份额的事物.**

2.Geography—A major environmental cause was selecting the right type of natural resources to create the inventions.
2. 地理因素——一个重要的环境因素是选择合适的自然资源来创造发明。

i.Britain had coal, timber, and iron, rich soil, fast-moving rivers to turn waterwheels that powered machines, and many natural harbors to import raw materials from faraway colonies. Products manufactured from those raw materials were exported back to millions of colonial consumers and other markets around the globe.
英国拥有煤炭、木材和铁矿，肥沃的土壤，湍急的河流可以驱动水车，进而驱动机器运转，还有许多天然良港，可以从遥远的殖民地进口原材料。用这些原材料制造的产品被出口到数百万殖民地消费者以及世界各地的其他市场。

ii.Belgium, Germany, and France had similar favorable geographic conditions and were quick to follow Britain’s lead in developing industry.
ii. 比利时、德国和法国拥有类似的有利地理条件，并迅速效仿英国发展工业的做法。

3.Economic and Social Mobility
3. 经济和社会流动性

i.In Britain, and to a lesser degree in the rest of Western Europe, citizens could move up the economic and social ladder by developing a money-making invention. This incentive spurred Britain to become “a nation of tinkerers,” as one observer put it. Banks loaned money to entrepreneurs in whom they had faith.
在英国，以及在较小程度上在西欧其他地区，公民可以通过发明创造来赚钱，从而提升经济和社会地位。正如一位观察家所说 ， 这种激励机制促使英国成为“发明家之国”。银行会向他们信任的企业家提供贷款。

ii.European governments offered prizes for inventions that they considered helpful to their global economic and political goals. These conditions did not exist outside Europe at the beginning of this era.
二、 欧洲各国政府为那些他们认为有助于实现其全球经济和政治目标的发明设立了奖项。在这一时期之初，欧洲以外地区并不存在这样的条件。

4.Workforce
4. 劳动力

i.Britain had many workers skilled in operating metal tools. Those skills were necessary for the creation of the machines that would be used to develop its industry.
一、 英国拥有许多精通金属工具操作的工人。这些技能对于制造发展其工业所需的机器至关重要。

ii.Many British agricultural workers were forced off farmland by a government-approved policy called the Enclosure Movement. The landless peasants migrated to cities, forming a large potential workforce for factories.
二、 由于政府推行的圈地运动，许多英国农业工人被迫离开农田。这些无地农民涌入城市，为工厂提供了大量潜在劳动力。

C.BEGINNINGS OF THE INDUSTRIAL REVOLUTION
C. 工业革命的开端

1.Mechanization of Textile Production
1. 纺织品生产的机械化

i.British inventors developed machines that mass-produced cloth and thread. These muscle-powered wood-and-iron machines cranked out cloth faster and cheaper than handmade materials.
英国发明家们研制出了可以大规模生产布匹和线的机器。这些人力驱动的木制铁制机器生产布匹的速度比手工制作更快、成本更低。

ii.Bigger and quicker machines were developed and amassed into large buildings called factories. Waterwheels rotating in fast-moving streams provided power for the machines.
二、 更大更快的机器被研发出来，并集中到被称为工厂的大型建筑物中。在快速流动的水流中旋转的水车为这些机器提供动力。

2.Uses of steam engine
2. 蒸汽机的用途

i.By the 1760s, British inventors had developed the steam engine—one of the most revolutionary inventions of all time—and made water power obsolete. No longer did factories have to be anchored next to a stream; they could be located anywhere.
一、 到了 18 世纪 60 年代，英国发明家们研制出了蒸汽机——有史以来最具革命性的发明之一——使水力发电成为历史。工厂不再需要建在溪流旁；它们可以建在任何地方。

ii.Connecting cloth- and thread-making machines to steam engines increased production many times beyond what humans could do. Mass production of goods made machine-made clothing affordable to just about all Europeans.
二、 将制布机和制线机与蒸汽机连接起来，使产量比人工生产提高了数倍。商品的批量生产使得几乎所有欧洲人都能买得起机器制造的服装。

3.More inventions.
3. 更多发明。

i.The cotton gin removed seeds from cotton to prepare it for thread and cloth manufacturing. It operated many times faster than any human and when hooked to a steam engine, even faster.
一、 轧棉机从棉花中去除棉籽，为纺线和织布做准备。它的运转速度比人类快得多，如果连接到蒸汽机上，速度就更快了。

ii.Two early 19th-century inventions involving the steam engine drastically altered transportation. In the U.S., the first steamboat made sail power obsolete. In Britain, the steam-powered locomotives on railroads marked the beginning of the end of the age of the horse in modern societies.
二、 19 世纪初两项与蒸汽机相关的发明彻底改变了交通运输。在美国，第一艘汽船的出现使帆船时代终结。在英国，铁路上的蒸汽机车标志着现代社会中马匹时代的终结。

iii.The steamboat created more reliable, faster, and cheaper transoceanic travel. This caused a huge increase in the numbers of people migrating from one region to another, most significantly from Europe to the Americas.
三、 汽船的出现使得跨洋旅行更加可靠、快捷和便宜。这导致人口从一个地区迁移到另一个地区的数量大幅增加，其中最显著的是从欧洲到美洲的人口迁移。

IV.  四、

THE SPREAD OF INDUSTRIALIZATION
工业化的扩散

The Industrial Revolution spread from Britain to the U.S., then to Japan, Russia, Latin America, and India.
工业革命从英国传播到美国，然后传播到日本、俄罗斯、拉丁美洲和印度。

A.UNITED STATES
A. 美国

1.Thanks to the cotton gin, single-crop plantations in the South became highly profitable.
1. 由于轧棉机的发明，南方的单一作物种植园变得利润丰厚。

2.British-style factories that turned American cotton into textiles popped up in the Northeast. The South produced so much cotton that the surplus was sold to British factories. Slavery was abolished after the U.S. Civil War giving the industrial North an even bigger economic boost over the South.
2. 将美国棉花加工成纺织品的英式工厂在东北部如雨后春笋般涌现。南方棉花产量巨大，剩余部分被卖给了英国工厂。美国内战后废除奴隶制，使工业化的北方在经济上比南方获得了更大的发展。

3.Railroads sprang up, first in the Northeast, and soon connected to farming areas in the Midwest and South, speeding delivery of crops and farm animals to processing factories in Chicago and other Northern cities.
3. 铁路兴起，首先在东北部，很快与中西部和南部的农业区连接起来，加快了农作物和牲畜向芝加哥和其他北方城市的加工厂的运输速度。

4.By 1900, the U.S. was the world’s biggest steel producer. U.S. Steel Corporation became the first billion-dollar corporation.
4. 到 1900 年，美国已成为世界上最大的钢铁生产国。美国钢铁公司成为第一家市值达十亿美元的公司。

B.LATIN AMERICA
B. 拉丁美洲

1.Europeans invested heavily to jump-start industrialization in Latin America. Great expectations followed and some railroad routes were built, but overall, like Russia, Latin America remained largely an exporter of crops grown by peasant labor. Among their products were coffee, bananas, wheat, beef, and sugar. Industrialized nations sought Mexican copper.
欧洲人投入巨资，试图推动拉丁美洲的工业化进程。人们寄予厚望，一些铁路也建成通车，但总体而言，与俄罗斯一样，拉丁美洲仍然主要出口由农民种植的农作物。其产品包括咖啡、香蕉、小麦、牛肉和糖。工业化国家则觊觎墨西哥的铜矿资源。

C.INDIA
C. 印度

1.Britain established its rule (raj) over India early in the era c. 1750–c.1900.
1. 英国在公元前 1750 年至 1900 年左右早期就建立了对印度的统治（ 拉吉 ）。

2.India was a leading grower of cotton, and Britain eagerly imported the processed fabric for its textile mills. Under British authority, Indian textile factories began to produce machine-made cotton thread and cloth, and the production of handmade textiles began to decline.
2. 印度曾是棉花的主要产地，英国急于进口加工后的棉布供应其纺织厂。在英国的统治下，印度的纺织厂开始生产机制棉线和棉布，手工纺织品的生产开始衰落。

3.India’s age of rapid industrial growth, however, languished until the late 20th century.
3. 然而，印度的快速工业增长时代直到 20 世纪后期才开始。

D.INDUSTRIALIZATION IN OTHER REGIONS
D. 其他地区的工业化

1.The Ottoman Empire was slow in developing modern industries. Its leaders failed to recognize the extent to which industrialization was increasing the West’s political, economic, and military power. Unlike the Japanese, the Ottoman leadership was divided over following Western Europe’s industrial model.
1. 奥斯曼帝国发展现代工业的速度缓慢。其领导人未能认识到工业化对西方政治、经济和军事实力的巨大提升。与日本不同，奥斯曼帝国领导层在是否效仿西欧工业模式的问题上存在分歧。

2.Africa remained a provider of natural resources to the world’s industrial giants.
2. 非洲仍然是世界工业巨头的自然资源供应地。

i.The greatest export in terms of value were diamonds and gold from South Africa.
一、 按价值计算，南非最大的出口产品是钻石和黄金。

ii.In the Age of Imperialism (see Chapter 9), Europe’s governments and businesses kept its African colonies dependent on them.
二、 在帝国主义时代（见第 9 章 ），欧洲各国政府和企业使其非洲殖民地对它们保持依赖。

3.China rejected Western ideas in this era and remained largely out of the production end of the Industrial Revolution. Some foreign investment provided for railroads and steamships, but overall, the Middle Kingdom stuck with human labor to produce crops and hand-made items for export.
3. 这一时期，中国拒绝接受西方思想，并且基本上没有参与到工业革命的生产环节中。虽然一些外国投资促进了铁路和轮船的建设，但总体而言，中国仍然依靠人力生产农作物和手工艺品出口。



Questions comparing industrialization in the West and other regions will appear on the exam.
考试中会出现比较西方与其他地区工业化进程的问题。

V.  五、

TECHNOLOGY OF THE INDUSTRIAL AGE
工业时代的科技

A.FOSSIL FUELS FED INDUSTRY
A. 化石燃料驱动工业

1.Coal was the initial fuel for the early steam engines, but as the 19th century progressed, petroleum was increasingly used, especially after the development of the internal combustion (diesel and later, gasoline) engine. Both provided vastly greater amounts of energy than any previous form of power.
1. 煤炭是早期蒸汽机的初始燃料，但随着 19 世纪的发展，石油的使用日益增多，尤其是在内燃机（柴油机，后来是汽油机）发展之后。这两种燃料提供的能量都远远超过以往任何形式的动力。

B.STEEL BECOMES THE “KING OF METALS”
B. 钢铁成为“金属之王”

1.Advancements in steel processing led to mass production of this alloy that was stronger, lighter, and more flexible than iron. Factories were built in regions near iron and coal mines, materials vital to steel production. Western Europe again led the way, soon followed by the U.S., Japan, and Russia. Steel became the metal of the Industrial Age.
1. 钢铁加工技术的进步使得这种比铁更坚固、更轻便、更柔韧的合金得以大规模生产。工厂建在铁矿和煤矿附近，这些矿藏是钢铁生产的关键原材料。西欧再次引领潮流，随后美国、日本和俄罗斯也紧随其后。钢铁成为工业时代的标志性金属 。

C.THE “SECOND INDUSTRIAL REVOLUTION”
C. “第二次工业革命”

1.The pace of industrialization quickened and so did the number of inventions in the second half of the 19th century. This “Second Industrial Revolution” was different from the first. Instead of focusing on textile production and steam power, the Second Industrial Revolution ran on the internal combustion (gasoline or diesel) system. Also, more inventions were related to electrical systems, scientific discoveries, and medicine. Many had applications for the mechanization of warfare.
1. 19 世纪下半叶，工业化进程加快，发明创造的数量也随之激增。这场“第二次工业革命”与第一次工业革命截然不同。它不再侧重于纺织生产和蒸汽动力，而是以内燃机（汽油或柴油）系统为主导。此外，与电力系统、科学发现和医学相关的发明也越来越多。许多发明都应用于战争机械化领域。

2.Communications. The first major development was the American invention of the telegraph in the 1840s. By the late 1850s, a telegraph cable was extended under the Atlantic, linking the British Isles to Canada and the U.S. By the 1870s, communication across the Pacific was achieved, and by 1902, the entire global British empire was connected by telegraph.
2. 通信。第一个重大发展是美国人在 19 世纪 40 年代发明了电报。到 19 世纪 50 年代末，一条电报电缆铺设在大西洋海底，将不列颠群岛与加拿大和美国连接起来。到 19 世纪 70 年代，跨太平洋通信得以实现，到 1902 年，整个大英帝国都通过电报连接起来。

i.In 1876, the telephone was invented in the U.S. Its popularity was greater than the telegraph because the user needed no special training, making it a consumer product.
1876 年，电话在美国发明。由于用户无需接受特殊培训，电话成为消费品，因此比电报更受欢迎。

ii.The radio (or “wireless telegraph”) was being developed near the end of this era.
ii. 无线电（或“无线电报”）是在这个时代末期发展起来的。

3.Transportation. After the steamboat and steam train, the next major step in transportation was the electric trolley car and the subterranean transportation system, or subway.
3. 交通运输。继汽船和蒸汽火车之后，交通运输的下一个重大进步是电车和地下交通系统，即地铁。

i.Both the trolley and the subway were mass-transit systems, first used in large cities like London, Paris, and New York.
i. 有轨电车和地铁都是公共交通系统，最初在伦敦、巴黎和纽约等大城市中使用。

ii.The automobile was invented in Germany in the 1880s. In this era, it was mostly an experimental machine and an object of curiosity.
二、 汽车于 19 世纪 80 年代在德国发明。在那个时代，它主要是一种实验性机器和令人好奇的对象。

iii.Improved transportation such as ocean-crossing steamboats led to massive migrations, especially from Europe to the Americas in the late 19th and early 20th centuries.
三、 交通运输的改善，例如远洋汽船的出现，导致了大规模的人口迁徙，尤其是在 19 世纪末 20 世纪初，从欧洲到美洲的人口迁徙尤为显著。

VI.  六、

INDUSTRIALIZATION: GOVERNMENT’S ROLE
工业化：政府的角色

Most participants in the Industrial Revolution had governments that guided its development. The federal government’s power rose dramatically after the American Civil War, and it adopted a strong pro-industry attitude. The U.S. courts favored business development over workers’ rights. In 1869, the U.S. completed the east-to-west Transcontinental Railroad, the world’s longest at the time.
大多数工业革命的参与者都受到政府的指导。美国内战后，联邦政府的权力急剧上升，并采取了强烈的亲工业态度。美国法院倾向于商业发展而非工人权益。1869年，美国建成了横贯大陆的铁路，这是当时世界上最长的铁路。

A.MEIJI JAPAN
A. 明治日本

1.Using a show of industrial force, the American government sent navy ships to force open the trade door with Japan in the 1850s. The Japanese government responded not by resisting, like China, but by transforming its government, society, and industry.
1. 19 世纪 50 年代，美国政府利用工业力量，派遣海军舰艇强行打开与日本的贸易大门。日本政府的回应并非像中国那样进行抵抗，而是对其政府、社会和工业进行改革。

2.The Tokugawa Shogunate was replaced by the Meiji Restoration, with a Western-style constitutional monarchy. The Japanese built railroads, modernized their military, and constructed factories that specialized in silk textiles.
2. 德川幕府被明治维新所取代，日本建立了西方式的君主立宪制国家。日本修建了铁路，实现了军队现代化，并建造了专门生产丝绸纺织品的工厂。

3.One significant difference between Japanese and Western industrialization was that the Japanese government had close ties to factory corporations. The government built factories, then sold them to investors, but stayed actively involved in their finances and business decisions.
3. 日本工业化与西方工业化的一个显著区别在于，日本政府与工厂企业关系密切。政府建造工厂，然后将其出售给投资者，但始终积极参与工厂的财务和商业决策。

B.RUSSIA
B. 俄罗斯

1.Unlike Japan and the “West,” Russia’s industrial progress was limited. The government’s primary focus was on supporting the elite owners of large agricultural estates. Serfdom was still in place until the mid-19th century. The government freed the serfs, but unlike the U.S. and Japan, Russia was slow to shift to industrialization.
1. 与日本和“西方”不同，俄罗斯的工业发展有限。政府的主要重点是扶持拥有大型农业庄园的精英阶层。农奴制一直延续到 19 世纪中期。政府解放了农奴，但与美国和日本不同，俄罗斯向industrialization.转型的速度很慢。

2.Late in this era, the Russian government sought foreign investment in its industrial program. Russia became a top producer of steel, and built the Trans-Siberian Railway, surpassing the U.S. in boasting the world’s longest railroad. Despite these accomplishments, Russia’s economy remained largely mired in the 15th century. Peasant laborers grew mostly wheat and potatoes for export from the large estates still owned by friends of the czar.
2. 在这一时期后期，俄国政府寻求外国投资以推进其工业发展计划。俄国成为世界顶级钢铁生产国，并修建了西伯利亚铁路，其铁路长度超过美国，成为当时世界上最长的铁路。尽管取得了这些成就，俄国的经济在很大程度上仍然停留在 15 世纪的水平。农民主要种植小麦和土豆，出口到沙皇亲信拥有的大庄园。

C.EGYPT
C. 埃及

1.Under the leadership of Muhammad Ali, the Egyptian government attempted to jump start the Industrial Revolution by building railroads, dams, and cotton factories.
1. 在穆罕默德·阿里领导下，埃及政府试图通过修建铁路、水坝和棉纺厂来启动工业革命。

2.Egypt also agreed to let the French construct the Suez Canal connecting the Red Sea to the Mediterranean Sea, using human labor and steam shovels.
2. 埃及还同意让法国人使用人力和蒸汽铲修建连接红海和地中海的苏伊士运河。

VII.  七、

ECONOMIC DEVELOPMENTS IN THE INDUSTRIAL AGE
工业时代的经济发展

In the late 1700s, Scottish economist Adam Smith insisted that governments end their mercantilist policies, engage in free trade (drop tariffs on imports from other countries) and stay out of the way of the “natural” cycles of the economy of boom and bust. This economic theory is “laissez-faire” capitalism, and caught on big-time in Western Europe in the 19th century.
18世纪末，苏格兰经济学家亚当·斯密坚持认为，各国政府应该结束重商主义政策，实行自由贸易（降低进口关税），并且不要干预经济繁荣与衰退的“自然”周期。这种经济理论就是“自由放任”资本主义，并在19世纪的西欧广为流传。

A.Transnational corporations grew in number. With the ever-expanding global market for machine-made goods came businesses that operated on a global scale. Insurance companies, such as the British-based Lloyd’s of London, wrote policies around the world. HSBC is a multinational banking corporation, also based in Britain. U.S.-based United Fruit Corporation operated banana plantations throughout Central America, with its produce shipped to the U.S. and Europe.
A. 跨国公司数量不断增长。随着全球机械制造产品市场的不断扩张，涌现出许多在全球范围内运营的企业。例如，总部位于英国的伦敦劳合社等保险公司，其保单业务遍及世界各地。汇丰银行也是一家总部位于英国的跨国银行集团。总部位于美国的联合果品公司在中美洲各地经营香蕉种植园，其产品销往美国和欧洲。

B.Governments took legal steps to protect transnational businesses, such as limiting how much financial liability a corporation could face if sued by a consumer. These are called limited-liability corporations.
B. 各国政府采取法律措施保护跨国企业，例如限制企业在被消费者起诉时可能承担的财务责任。这类企业被称为有限责任公司。

C.The exchange of goods and money among the industrialized economies grew so fast that they established a “gold standard” for world currencies. An agreed-upon international price of gold became the measure by which nations determined the relative value of their money systems. Stock markets in major financial centers like London and New York encouraged investments of capital from the middle and wealthy classes.
C. 工业化经济体之间的商品和货币交换发展迅猛，以至于它们建立了世界货币的“金本位制”。各国商定的国际黄金价格成为衡量其货币体系相对价值的标尺。伦敦和纽约等主要金融中心的股票市场鼓励了中产阶级和富裕阶层的资本投资。



The growth of transnational corporations is a frequent topic on the AP ® World History: Modern exam.
跨国公司的发展是 AP® 世界历史：现代考试的常见考点。

VIII.  第八章

REACTIONS TO THE INDUSTRIAL ECONOMY
对工业经济的反应

A.WESTERN EUROPE AND THE U.S.
A. 西欧和美国

1.The Industrial Revolution resulted in more and larger cities. Seeking a steady income, people practically fled farm life and moved to cities to work in industrial jobs. With the boom in urban population came overcrowded living conditions, high levels of pollution, higher crime rates, and a poor and increasingly discontent working class. Pressures from these conditions led to proposals for sweeping changes in government policies, particularly in Europe and the U.S.
1. 工业革命催生了更多更大的城市。为了寻求稳定的收入，人们几乎放弃了农村生活，涌入城市从事工业工作。随着城市人口的激增，随之而来的是居住环境拥挤、污染严重、犯罪率上升以及贫困且日益不满的工人阶级。这些问题的压力促使人们提出对政府政策进行全面改革的建议，尤其是在欧洲和美国。

2.Pressures in cities and factories
2. 城市和工厂面临的压力

i.Overcrowded cities created many problems: a shortage of decent housing, disease, and unemployment to name a few.
一、 城市人口过密造成了许多问题：例如，缺乏体面的住房、疾病和失业等等。

ii.The lower classes suffered the most and discontent spilled into the streets of many major European cities. Poor working conditions in factories, including hazardous machinery, long hours, and low pay led to anger and resentment among the laboring classes.
二、 下层阶级遭受的苦难最为深重，不满情绪蔓延到欧洲许多主要城市的街头。工厂里恶劣的工作条件，包括危险的机械设备、长时间的工作和低工资，导致劳动阶级的愤怒和怨恨。

iii.Government leaders were often slow to respond to the calls for reform because they were either overwhelmed by or did not care about the numerous problems facing societies in the early years of the Industrial Revolution.
三、 政府领导人往往对改革的呼声反应迟缓，因为他们要么被工业革命初期社会面临的众多问题所淹没，要么根本不在乎这些问题。

iv.By the mid-19th century, however, political pressure from the increasingly important middle class stirred governments in Western and Central Europe to begin providing assistance to the urban working classes.
iv. 然而，到了 19 世纪中叶，日益重要的中产阶级的政治压力促使西欧和中欧各国政府开始向城市工人阶级提供援助。

3.Calls for change
3. 变革的呼声

i.From the 1820s through the 1840s, European activists rallied the urban poor to take to the streets. The middle class was urged to use its new voting power to call for political rights for working-class men, increased pay, and safer working conditions in factories.
一、 从 19 世纪 20 年代到 40 年代，欧洲的活动家们号召城市贫民走上街头。他们敦促中产阶级利用新获得的投票权，呼吁赋予工人阶级男性政治权利，提高工资，并改善工厂的工作条件。

ii.Only a few men and women lobbied for voting rights for women in the early 19th century.
二、 19 世纪初，只有少数男女为争取妇女的投票权而游说。

iii.Labor unions, representing the collective power of many workers began to form. The labor unions were illegal in most Western European nations until later in the 19th century.
三、 代表众多工人集体力量的工会开始形成。在 19 世纪后期之前，工会在大多数西欧国家都是非法的。

4.Karl Marx was considered the most radical activist among those calling for political change. In 1848, commenting on the plight of the working poor in London, Marx’s “Communist Manifesto” demanded overthrow of the “haves” (“bourgeoisie”) by the “have-nots” (“proletariat”). He envisioned the creation of a classless society where all people were politically, socially, and economically equal. At the time, the few people who read his materials thought these ideas had no chance of success.
4. 卡尔·马克思被认为是呼吁政治变革的最激进的活动家。1848 年，马克思针对伦敦贫苦劳动者的困境，发表了《共产党宣言》，要求“无产阶级”推翻“资产阶级”。他设想建立一个无阶级社会，人人享有政治、社会和经济上的平等。当时，少数阅读过他著作的人认为这些想法根本不可能实现。

5.Those in the new middle class did not take to the streets in support of the urban poor, but they did effect change with their new political rights. For example, they convinced government leaders to provide police services and cleaner drinking water in London, to build public housing in Paris, and to establish unemployment and social security benefits in the new nation of Germany.
5. 新兴中产阶级并没有走上街头声援城市贫民，但他们确实利用新获得的政治权利促成了变革。例如，他们说服政府领导人在伦敦提供警务服务和更清洁的饮用水，在巴黎建造公共住房，并在新成立的德国建立失业救济和社会保障制度。

B.REACTIONS BEYOND THE WEST
B. 西方以外的反应

1.The Ottoman Empire’s attempts to westernize and compete with Western Europe in the 19th century, consisted of a movement toward a constitutional government—the Tanzimat Reforms—and the purchase of modern weapons from European manufacturers.
1. 19 世纪，奥斯曼帝国为实现西化并与西欧竞争，采取了一系列措施，包括推行宪政改革（坦齐马特改革）以及从欧洲制造商处购买现代武器。

i.Tanzimat means “reorganization” and that is what the reforms did to the Ottoman government. A written constitution with guaranteed political and social rights, including freedom of religion, a modernized banking system, railroad construction, and reorganization and modernization of the army were some of the major changes.
坦齐马特 （Tanzimat） 意为“重组”，而这正是这些改革对奥斯曼政府所做的。其中一些主要变革包括：制定一部保障政治和社会权利（包括宗教自由）的成文宪法；建立现代化的银行体系；修建铁路；以及对军队进行重组和现代化。

ii.After 40 years under this first constitution, the Ottoman leader, the Sultan, canceled it and dissolved the legislature in 1876. He realized changes to the constitution called for limitations of his own powers.
二、 在第一部宪法实施 40 年后，奥斯曼帝国的统治者苏丹于 1876 年废除了这部宪法，并解散了立法机构。他意识到，对宪法的修改需要限制他自己的权力。

iii.Later, another reform movement came from within the military. The “Young Turks” were Western-educated young army officers in the early 20th century who sought revival and extension of the Tanzimat reforms. They succeeded, but after World War I, the 700-year-old empire collapsed and was divided into many nations.
三、 后来，另一场改革运动也来自军方内部。“青年土耳其党人”是 20 世纪初受过西方教育的年轻军官，他们寻求复兴和扩展坦齐马特改革。他们取得了成功，但第一次世界大战后，这个拥有 700 年历史的帝国崩溃瓦解，分裂成许多国家。

iv.Like the Russians, the Ottoman Empire had limited progress in developing modern industry in this era. The empire’s leaders failed to recognize the degree to which the Industrial Revolution was increasing the West’s political, economic, and military power. Unlike Japan’s leaders at this time, the Ottomans were divided over following Western Europe’s industrial model.
四、 与俄罗斯一样，奥斯曼帝国在这一时期发展现代工业的进程也十分有限。帝国的统治者未能认识到工业革命对西方政治、经济和军事实力的巨大提升。与当时的日本统治者不同，奥斯曼帝国内部对于是否效仿西欧的工业模式存在分歧。

2.The African continent remained a provider of natural resources to the world’s industrial giants. The greatest export in terms of cost were diamonds and gold from South Africa. In the Age of Imperialism (see Chapter 9), Europe’s governments and businesses preferred to keep its African colonies dependent on them.
2. 非洲大陆一直是世界工业巨头的自然资源供应地。南非出口的钻石和黄金价值最高。在帝国主义时代（见第九章 ），欧洲各国政府和企业更倾向于让其非洲殖民地继续依赖自身。

3.As you have learned, Qing China rejected most things Western in this era and remained largely out of the Industrial Revolution. Some foreign investment provided for railroads and steamships, but overall the Middle Kingdom stayed with human labor to produce crops and hand-made items for export. Western Europe, the U.S., Russia, and Japan took advantage of China’s weak government by forcing open exclusive trade regions—“Spheres of Influence”—in China. So Russia traded in one region of China, Britain in another, and France in yet another. At the end of this era, these nations accepted a U.S. proposal for an “Open Door Policy” in China, ending the “Spheres of Influence” and allowing open access to all of its markets.
3. 正如你所了解的，清朝在这一时期拒绝了西方的大部分事物，并且基本上没有参与工业革命。虽然一些外国投资促成了铁路和轮船的建设，但总体而言，中国仍然依靠人力生产农作物和手工艺品出口。西欧、美国、俄罗斯和日本利用中国政府的软弱，在中国强行划定了排他性的贸易区域——“势力范围”。因此，俄罗斯在中国的一个地区进行贸易，英国在另一个地区，法国又在另一个地区。在这一时期末期，这些国家接受了美国提出的“门户开放政策”，结束了“势力范围”，允许所有国家自由进入中国市场。

IX.  九、

SOCIETY AND THE INDUSTRIAL AGE
社会与工业时代

A.CAUSES OF CHANGES IN SOCIETIES
A. 社会变革的原因

1.In Western countries, the rapid changes that industrialization had on the economy affected everyday life as well. In Britain, the factory system demanded a great deal of labor so men, women, and children moved from farms to cities to work in textile and other kinds of factories. Another factor in the move from farms to cities was the loss of farm jobs due to the increased use of labor-saving devices in agriculture.
1. 在西方国家，工业化给经济带来的快速变革也影响了人们的日常生活。在英国，工厂制度需要大量劳动力，因此男女老少纷纷从农村涌向城市，在纺织厂和其他类型的工厂工作。促使人们从农村迁往城市的另一个因素是，由于农业中省力设备的广泛应用，导致农业工作岗位减少。

B.EFFECTS OF INDUSTRIALIZATION ON SOCIETIES
B. 工业化对社会的影响

1.Over time, wages rose so much that working outside the home became primarily a “man’s job.” As factories became more efficient, less human labor was required, so, for the most part, women and children left factory work. However, in many areas of the West, children continued to work in coal mines and in agricultural labor.
1. 随着时间的推移，工资大幅上涨，外出工作逐渐成为“男人的工作”。工厂效率提高后，所需的人力减少，因此，妇女和儿童大多离开了工厂。然而，在西部许多地区，儿童仍然在煤矿和农业部门工作。

2.As steady wages increased over time, a new social class arose in the industrial West: the middle class. This economic and social group between the rich and the poor had always existed, but in this era, it exploded in size and political power.
2. 随着工资水平的稳步增长，工业化的西方社会出现了一个新的社会阶层：中产阶级。这个介于富人和穷人之间的经济和社会群体一直存在，但在那个时代，它的规模和政治影响力都呈爆炸式增长。

3.As fewer children were needed for factory work because of increased efficiency of machinery, Western governments concerned about unsupervised, idle children passed laws requiring school attendance.
3. 由于机器效率的提高，工厂需要的童工越来越少，西方各国政府担心无人监管的闲散儿童，于是通过法律规定儿童必须上学。

4.Middle-class women were expected to marry and stay home to care for their families. These values created what we now call the “traditional family structure.” Urban families had fewer children than their rural counterparts. Single women increasingly found employment as teachers, replacing men. As the 20th century approached, women began to replace men in the business environment as secretaries and telephone operators. They were not allowed to vote in most Western societies until after World War I.
4. 中产阶级女性被期望结婚后留在家中照顾家庭。这些价值观塑造了我们今天所说的“传统家庭结构”。城市家庭的子女数量少于农村家庭。单身女性越来越多地从事教师工作，取代了男性。随着 20 世纪的临近，女性开始在商业领域取代男性，担任秘书和电话接线员等职位。在第一次世界大战之后，大多数西方社会才允许女性拥有投票权。



The AP ® World History: Modern exam has been known to ask questions about the effects of industrialization on Japanese society especially on the conditions young women endured who were sent from rural areas by their families to work in silk factories. Unhealthy working conditions and threats from male supervisors were the subject of songs and poems written by “factory girls.”
AP®世界历史：现代史考试曾多次涉及工业化对日本社会的影响，尤其关注那些被家人从农村送往丝绸厂做工的年轻女性所遭受的苦难。恶劣的工作环境和男性主管的威胁，也成为“工厂女工”创作歌曲和诗歌的主题。

5.The limited impact of the Industrial Revolution on Latin America meant that continuities in social structures and gender roles remained through this era. In another major social development, millions of Europeans migrated to Latin America seeking new economic opportunities. In an interesting parallel, thousands of Japanese immigrants poured into the west coast of South America, mostly to work as laborers. (See Chapter 9.)
5. 工业革命对拉丁美洲的影响有限，这意味着社会结构和性别角色在这一时期得以延续。在另一项重大的社会发展中，数百万欧洲人移居拉丁美洲，寻求新的经济机会。与之形成鲜明对比的是，成千上万的日本移民涌入南美洲西海岸，他们大多从事体力劳动。（参见第九章 。）

C.ART AND LITERATURE
C. 艺术与文学

The Industrial Revolution even affected art and literature. Is there anything it couldn’t do?!
工业革命甚至影响了艺术和文学。还有什么是它做不到的吗？！

1.Looking at the gritty life of overcrowded industrial cities, artists abandoned the optimism of the Romantic school of art of the early 19th century and shifted to Realism, painting dark scenes of city life, exemplified by locomotives belching black smoke.
1. 艺术家们观察了拥挤的工业城市残酷的生活，放弃了 19 世纪早期浪漫主义艺术流派的乐观主义，转而走向现实主义，描绘城市生活的黑暗场景，例如火车冒出滚滚黑烟。

i.One new invention was the camera, which artists feared would put them out of business.
一、 相机是一项新发明，艺术家们担心它会让他们失业。

ii.The artistic style called Impressionism was in direct contrast to photography’s graphic realism. Artists painted deliberately unfocused scenes of nature—their “impression” of the scene. French artists led the way in this school of art.
二、 印象派艺术风格与摄影的写实主义截然相反。艺术家们刻意描绘模糊的自然景象——这是他们对景象的“印象”。法国艺术家引领了这一艺术流派。

2.Writers also responded to the effects of the Industrial Revolution. Charles Dickens wrote stories about life among the struggling urban laboring classes in soot-covered London in the early 19th century in his classics A Christmas Carol and Oliver Twist.
2. 作家们也对工业革命的影响做出了回应。查尔斯·狄更斯在他的经典作品 《圣诞颂歌》 和 《雾都孤儿》 中，描写了 19 世纪初伦敦烟雾弥漫的城市劳动阶级的生活。

D.SCIENCE AND MEDICINE
D. 科学与医学

Enormous advances were made in the fields of scientific discoveries and medicine.
科学发现和医学领域取得了巨大进步。

1.The modern science of chemistry began in this era. Systematic studies of chemical compounds and the composition of different forms of matter gave scientists insights into how nature works. Toward the end of the era, scientists were developing chemical compounds in the lab; some were powerful fertilizers used to grow bigger crops (and thus more food, leading to more people) than ever before.
现代化学这门科学就起源于这个时代。对化合物和不同物质形态组成的系统研究 ， 使科学家们深入了解了自然界的运作方式。在这个时代的末期，科学家们在实验室里研制出了各种化合物；其中一些是强效肥料，用于种植比以往任何时候都更加茂盛的作物（从而生产出更多的食物，进而养活更多的人口）。

2.Advances in medicine included smallpox and rabies vaccinations, sterilization of surgical instruments, the use of anesthetics to “knock out” patients during surgery, and aspirin, to name a few. Governments oversaw programs that provided clean drinking water in cities. These and many other examples led to healthier, longer lives in the industrialized world.
2. 医学的进步包括天花和狂犬病疫苗的接种、手术器械的消毒、使用麻醉剂在手术中使患者失去知觉以及阿司匹林的问世等等。政府监管了为城市提供清洁饮用水的项目。这些以及其他诸多举措使工业化国家的人们拥有了更健康、更长寿的生活。

3.Scientific developments and faith crossed swords in Charles Darwin. His investigations of animals of the South Pacific led him to conclude that natural selection, not God, determined the viability of species on Earth. He also theorized that man and apes had similar characteristics, and must therefore have common ancestors. These pronouncements began furious debates about the nature of mankind and its place among fellow humans and animals in the world. His ideas about “survival of the fittest” in the animal kingdoms led some Europeans to transfer the concept to human civilizations. Social Darwinism—wherein the superior races must naturally defeat inferior ones—had enormous implications in the Age of Imperialism (see Chapter 9).
3. 科学发展与信仰在查尔斯·达尔文身上交锋。他对南太平洋动物的研究使他得出结论：决定地球物种生存的并非上帝，而是自然选择。他还提出人类和猿类具有相似的特征，因此必然拥有共同的祖先。这些论断引发了关于人类本质及其在人类和动物世界中地位的激烈辩论。他关于动物界“适者生存”的观点，促使一些欧洲人将这一概念应用于人类文明。 社会达尔文主义 ——即优等种族必然战胜劣等种族——在帝国主义时代产生了深远的影响（参见第九章 ）。

X.

CONTINUITY AND CHANGE IN THE INDUSTRIAL AGE
工业时代的延续与变革

This chapter has outlined the enormous changes brought to societies by the Industrial Revolution. However, as always, some things stayed the same. For example, patriarchy in society remained, although women in industrialized countries began to see some political and economic gains. In sub-Saharan Africa and much of Asia, the Industrial Revolution was non-existent. Most people still maintained a religious belief; in Europe and the Americas, Christianity was predominant while from West Africa to Central Asia, Islam remained the primary faith.
本章概述了工业革命给社会带来的巨大变革。然而，一如既往，有些事情依然如故。例如，父权制依然存在，尽管工业化国家的女性开始在政治和经济上取得一些进展。在撒哈拉以南非洲和亚洲大部分地区，工业革命尚未发生。大多数人仍然保持着宗教信仰；在欧洲和美洲，基督教占主导地位，而从西非到中亚，伊斯兰教仍然是主要信仰。

Make a chart that tracks similar and different reactions to the Industrial Revolution in Europe, Japan, the Ottoman Empire, and China. Explain those similarities and differences.
制作一张图表，记录欧洲、日本、奥斯曼帝国和中国对工业革命的异同。并解释这些异同。



'''

== pure




'''