

= UNIT 2 - Networks of Exchange (c. 1200 to c. 1450)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''


== 释义


As you proceed through this book, remember to continually apply the AP® skills: Comparison (similarities and differences), Continuity-and-Change-over-Time, and Causes and Effects. As you review these chapters, think, “How is this similar or different from another society?” “What caused this?” “What are some of its effects?” “What things are changing?” “What things are staying much the same?”

[.my2]
在阅读本书的过程中，请记住持续运用 AP®技能：比较（相似点和差异点）、历史的延续与变迁以及因果关系。在复习这些章节时，思考以下问题：“这与其他社会有何异同？”“是什么导致了这种情况？”“它产生了哪些影响？”“哪些方面正在发生变化？”“哪些方面基本保持不变？”


=== I. THE SILK ROADS

[.my2]
丝绸之路

==== A. TRADE CITIES AND INNOVATIONS

[.my2]
贸易城市与创新
|The increase in trade that took place along the Silk Roads led to stopping points (called caravanserai) along the routes. Some caravanserai developed into cities that expanded in importance in this era. Samarkand and Dunhuang are two examples of Silk Road trade cities. These cities were centers for exchanging goods.

[.my2]
丝绸之路贸易的增长促使沿途设立了许多驿站（称为商队驿站 ）。一些商队驿站发展成为城市，并在这一时期日益兴盛。撒马尔罕和敦煌就是丝绸之路贸易城市的两个例子。这些城市是商品交换中心.

Merchants and missionaries spread Islam, Buddhism, and Christianity as well as other faiths along trade routes.

[.my2]
商人和传教士沿着贸易路线传播伊斯兰教、佛教、基督教以及其他信仰。


==== NEW FORMS OF MONEY AND CREDIT
[.my2]
新型货币和信贷

Banks grew along the Silk Roads. They provided bills of exchange (like today’s bank-issued checks) to protect merchants’ money.

[.my2]
银行沿着丝绸之路发展起来。它们提供汇票（就像今天的银行支票一样）来保护商人的资金。

China’s exports were so strong, paper money (“flying cash”) was introduced as currency due to a shortage of metal for coins. The innovation grew in popularity along the Silk Roads after the Mongols conquered China.

[.my2]
由于中国出口强劲，金属铸币短缺，纸币（“飞钞”）应运而生。蒙古征服中国后，纸币沿丝绸之路迅速普及。




=== II. MONGOL EMPIRE AND MAKING OF THE MODERN WORLD
[.my2]
蒙古帝国与现代世界的形成

==== FROM THE 13th TO THE 15th CENTURIES, MONGOL RULE STRETCHED FROM EAST ASIA TO EASTERN EUROPE

[.my2]
从​​13 世纪到 15 世纪，蒙古的统治范围从东亚延伸到东欧。
|After merciless military campaigns that brought them to power, the Mongols in China made Beijing their capital and ended the Confucian examination system. The Mongols allowed foreigners, especially Arab Muslims, to administer the government.

[.my2]
蒙古人通过残酷的军事征服夺取了中国的政权，定都北京，废除了儒家科举制度。蒙古人允许外国人，特别是阿拉伯穆斯林，参与政府管理。

==== THE PAX MONGOLICA
[.my2]
蒙古治世

The Mongols accumulated goods from all over the world, so they made the Silk Road network as safe for merchants as possible. The routes were so free of bandits that historians refer to a Pax Mongolica (“Mongol peace”).

[.my2]
蒙古人从世界各地搜罗货物，因此他们尽可能地确保丝绸之路网络对商人的安全。这条路线几乎没有土匪，以至于历史学家称之为“蒙古和平”（Pax Mongolica）。

==== MONGOL EXPANSION
[.my2]
蒙古扩张

The Mongols’ advance westward was finally stopped in modern-day Israel by Mamluk warriors from Egypt.

[.my2]
蒙古人向西推进的步伐最终在今天的以色列境内被来自埃及的马穆鲁克战士所阻止。

The Russians called the Mongols “The Golden Horde.” After their destructive invasion, the Mongols reached an agreement with local Russian leaders who collected tribute to send to their Mongol masters. This tribute arrangement lasted 200 years until Ivan the Great, prince of Moscow, led a successful revolt against the Mongols in 1480.

[.my2]
俄罗斯人称蒙古人为“金帐汗国”。蒙古人入侵俄罗斯后，与当地俄罗斯统治者达成协议，由这些统治者收取贡品献给蒙古主子。这种贡赋安排持续了 200 年，直到 1480 年莫斯科大公伊凡三世领导起义成功推翻蒙古人的统治。

==== EFFECTS OF THE MONGOLS

[.my2]
蒙古人的影响
|Over time, the people in all Mongol khanates rebelled and ended their rule. But the Mongol legacy, the largest empire the world has ever seen, remained. They allowed freedom of religion in the areas they conquered. Technology and other innovations spread through the Mongol Empire and beyond: saddle stirrups, the compound bow, flying cash, and pasta, to name a few.

[.my2]
随着时间的推移，蒙古各汗国的人民最终都发动叛乱，结束了他们的统治。 但蒙古帝国留下的遗产——这个世界上历史上最庞大的帝国——却留了下来。他们在征服的地区允许宗教自由。科技和其他创新在蒙古帝国境内外传播开来：马镫、复合弓、飞钞、意大利面等等，不胜枚举。

Marco Polo returned to Italy from a long visit to China under Kublai Khan with noodle-making technology and enticing tales that inspired future generations of European explorers. However, because of the Pax Mongolica, increased trade resulted in the rapid spread of the Black Death all across the khanates and into western Europe.

[.my2]
马可·波罗在忽必烈汗统治时期结束了对中国的长期访问，返回意大利时带回了面条制作技术, 和引人入胜的故事，激励了后世的欧洲探险家。然而，由于蒙古治下的和平时期，贸易的增长导致黑死病迅速蔓延至各个汗国，并扩散到西欧。




=== III. EXCHANGE IN THE INDIAN OCEAN

[.my2]
印度洋的交流

==== EXPANSION OF INTERREGIONAL TRADE

[.my2]
区域间贸易的扩张
|Ships carried heavier bulk items (lumber and pottery) than could be conveyed on the Silk Roads. Seasonal monsoon winds aided sailing ships in the Indian Ocean.

[.my2]
船只运载的货物（木材和陶器）, 比丝绸之路所能运输的更重。季节性季风, 帮助印度洋上的帆船航行。

History’s greatest maritime expeditions passed through the Indian Ocean.

[.my2]
历史上最伟大的海上探险, 都途经印度洋。

==== INDIAN OCEAN TRADE AND GROWTH OF STATES
[.my2]
印度洋贸易与国家发展

The Islamic Sultanate of Malacca, in Southeast Asia, was a major player in Indian Ocean trade. It patrolled the vital Straits of Malacca (a route from China to the Indian Ocean) for pirates.

[.my2]
位于东南亚的伊斯兰苏丹国是印度洋贸易的重要参与者。它巡逻着至关重要的马六甲海峡（一条从中国通往印度洋的航线），以打击海盗。

In western India, the port of Gujarat, under Islamic control, was a trade center midway between Africa and East Asia.

[.my2]
在印度西部，古吉拉特港在伊斯兰教的控制下，是位于非洲和东亚之间的贸易中心。

Muslims also controlled the trading centers on the Swahili Coast of East Africa. Cities such as Kilwa, Lamu, and Zanzibar welcomed various merchants from Europe, the Arabian Peninsula, South Asia, Southeast Asia, and East Asia.

[.my2]
穆斯林还控制了东非斯瓦希里海岸的贸易中心。基尔瓦、拉穆和桑给巴尔等城市迎来了来自欧洲、阿拉伯半岛、南亚、东南亚和东亚的各种商人。

All this merchant activity meant there were sizable diasporic communities scattered all over Afro-Eurasia, especially Arabs and Persians in East Africa, Chinese in Southeast Asia (like Burma and modern-day Indonesia) and Malays in South Asia.

[.my2]
所有这些商业活动意味着在整个亚非欧大陆散布着相当规模的侨民社区，特别是东非的阿拉伯人和波斯人，东南亚（如缅甸和现代印度尼西亚）的中国人，以及南亚的马来人。

Jewish and Christian merchants also participated in the Indian Ocean network and established communities throughout the region.

[.my2]
犹太商人和基督教商人也参与了印度洋网络，并在整个地区建立了社区。





'''

== pure




'''