= 1233
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,233 – Improving
Flexibility and Mobility.
This is English as a Second Language Podcast episode 1,233. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com to get a look at our ESL Podcast Special Courses in Business and Daily English. Are you on Facebook? So are we! Go to facebook.com/eslpod and like us, because we like you.
In this episode, we’re going to hear a dialogue between Rashida and Phil about helping your body become more flexible – being able to move your arms and your legs in the way you’re supposed to. Let’s get started.
[start of dialogue]
Rashida: Hi, I’m Rashida and I’m your physical therapist. I’m here to help you regain flexibility and mobility after your accident.
Phil: I’m really not sure I need a physical therapist. I can move around pretty well right now.
Rashida: Aren’t you feeling stiffness in your arms and tightness in your shoulders?
Phil: Not really.
Rashida: Try lifting your arms over your head.
Phil: See? I’m fine.
Rashida: You can’t lift them above your shoulders. I can help you improve your range of motion. Now let’s check out your hips and legs.
Phil: There’s nothing wrong with my hips and legs!
Rashida: Can you bend at the waist and touch your toes? Are you able to squat?
Phil: I probably could if I stretched and limbered up.
Rashida: I think you need more than stretching. I’ll work you through some exercises that will strengthen your muscles and loosen scar tissue. You’ll be able to move more freely. Don’t you want that?
Phil: W . . . W . . . Will it hurt?
Rashida: Only a little. Let’s get started.
Phil: Ow, ow, ow!
Rashida: We haven’t started yet.
[end of dialogue]
Rashida begins our dialogue by saying to Phil, “Hi, I’m Rashida and I’m your physical therapist.” A “physical therapist” (therapist) is a person who helps people who are either sick or perhaps injured to improve their physical movements – the movements of their arms and their legs, principally – by using certain kinds of massages and exercises.
A physical therapist doesn’t use drugs or surgery, typically; rather, a physical therapist tries to help you regain, or once again have, the movement in your arms and your legs and the rest of your body that you’re supposed to have. So if you, for example, break your leg, you might need a physical therapist to help you get the muscles in your legs strong again so you can walk normally.
Rashida says that she is here to help Phil “regain flexibility and mobility” after his accident. “To regain” (regain) means to recover, or to get again, what you had before. So, if you used to be the number one person at a certain activity – say, a video game – and then you lose your position as number one, you will want to regain it. You will want to get it back again. You will want to be as good as you were before.
In the dialogue, we’re talking about regaining “flexibility” (flexibility). “Flexibility” is how you are able to move your body parts again, usually your arms and your legs. The flexibility you have allows you to move around the way you want to. “Mobility” (mobility) is related to flexibility, except “mobility” refers specifically to being able to move from one place to another, such as by walking.
Usually when we refer to “mobility,” we’re talking about the ability to walk.
“Flexibility” can refer simply to one’s ability to move one’s arms back and forth,
for example, or to be able to put both arms straight up in the air. The two concepts are related, but refer to slightly different things. Phil isn’t sure he needs a physical therapist. He says he can move around “pretty well,” meaning very well, “right now.”
Rashida says, “Aren’t you feeling stiffness in your arms and tightness in your shoulders?” “Stiffness” (stiffness) is a feeling of difficulty when you move your muscles, especially if you haven’t used your muscles in a long time, or perhaps you’ve overused your muscles. You know, when you, for example, get up one morning and your muscles are difficult to move, perhaps because you were doing some physical activity yesterday that you don’t normally do. That would be an example of “stiffness” in your muscles.
“Tightness” (tightness) is similar to “stiffness.” It refers to a feeling of not being able to move your arms and legs the way you should be able to. When you try to move them, you may feel pain, for example. “Tightness” in some ways is the opposite of “flexibility.” “To be flexible” means to be able to move without any pain or difficulty. Phil says he does not feel any stiffness in his arms or tightness in his shoulders. Your “shoulders” are, of course, where your arms meet your body.
Rashida says, “Try lifting your arms over your head.” “To lift” something means to raise it up in the air. Rashida is asking Phil to put his arms above his head. Phil says, “See? I’m fine.” He doesn’t have any difficulty doing that. Rashida says, however, “You can’t lift them above your shoulders.” So, Phil is not actually able to put his hands above where his shoulders are. She says, “I can help you improve your range of motion.”
“Motion” (motion) refers to movement – moving things. Your “range” is how far or how much you can move – in this case, how much you could move your arms and legs, I suppose. Rashida says, “Now let’s check your hips and legs.” Your “hips” (hips) refers to the area where your legs meet the rest of your body. Phil says, “There’s nothing wrong with my hips and legs!” Rashida then asks Phil, “Can you bend at the waist and touch your toes?” “To bend (bend) at the waist (waist)” means the same as to bend over – to stand, usually, and then try to touch the ground with your hands.
Rashida tells Phil to “bend at the waist” and touch his toes – with his hands, of course. Rashida then asks, “Are you able to squat?” (squat). “To squat” means to bend your knees in order to lower the rest of your body closer to the ground. It’s almost like sitting, but you’re not actually sitting on anything. You are instead bending your knees and bringing your body down towards the ground.
Phil claims that he could probably squat if he “stretched and limbered up.” “To stretch” (stretch) in this case refers to slowly extending the length of your muscles as part of warming up before exercising or participating in some sort of physical activity such as a sport. “Stretching” is very common among “athletes” – people who play sports. “To limber (limber) up” is a two-word phrasal verb that means something very similar to the expression “to stretch.” It can also mean the same as “to warm up,” which is to get your body ready, your muscles ready to do physical activity.
Rashida says, “I think you need more than stretching. I’ll work you through some exercises” – meaning I will direct you to do some exercises with me helping you – “that will strengthen your muscles and loosen scar tissue.” Your “muscles” are the parts of your body that move the bones of your body back and forth. “To strengthen” (strengthen) means to make something stronger, to make something more powerful.
Rashida wants to strengthen Phil’s muscles as well as “loosen (loosen) scar (scar) tissue (tissue).” “To loosen” something means to allow it to move freely. It means to make something less tight. “To tighten” is the opposite of “to loosen.” “Scar tissue” refers to thick, dense tissue which is a material in your body that sometimes is formed after you injure yourself, especially around your muscles.
Rashida tells Phil that if she is able to do these exercises with him, he’ll “be able to move more freely” (freely). “Freely” means without any limitations, without any restrictions in his movement. Rashida then asks Phil, “Don’t you want that?” meaning, “Is this something you want?” When we say, “Don’t you want that?” we’re assuming that the other person does want it. Phil, however, is afraid that it’s going to hurt. It is going to cause pain. Rashida says, “Only a little. Let’s get started.”
Immediately Phil starts to cry out in pain. Now remember, Phil seemed like such a tough guy, such a strong guy just a few minutes ago, but when Rashida says she’s going to start doing these exercises with Phil, Phil says, “Ow, ow!” “Ow,” usually spelled (ow), is the sound we make when we are in pain. Rashida says, “We haven’t started yet,” meaning she hasn’t even started doing the exercises and already Phil is complaining about the pain.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Rashida: Hi, I’m Rashida and I’m your physical therapist. I’m here to help you regain flexibility and mobility after your accident.
Phil: I’m really not sure I need a physical therapist. I can move around pretty well right now.
Rashida: Aren’t you feeling stiffness in your arms and tightness in your shoulders?
Phil: Not really.
Rashida: Try lifting your arms over your head.
Phil: See? I’m fine.
Rashida: You can’t lift them above your shoulders. I can help you improve your range of motion. Now let’s check out your hips and legs.
Phil: There’s nothing wrong with my hips and legs!
Rashida: Can you bend at the waist and touch your toes? Are you able to squat?
Phil: I probably could if I stretched and limbered up.
Rashida: I think you need more than stretching. I’ll work you through some exercises that will strengthen your muscles and loosen scar tissue. You’ll be able to move more freely. Don’t you want that?
Phil: W . . . W . . . Will it hurt?
Rashida: Only a little. Let’s get started.
Phil: Ow, ow, ow!
Rashida: We haven’t started yet.
[end of dialogue]
You can strengthen your English by listening to our wonderful scripts by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
physical therapist – a medical professional who helps patients improve their movements through the use of massage and exercises, not surgery or drugs * The physical therapist helped Rachel strengthen her neck muscles after the accident.
to regain – to recover what one had before; to reach or achieve one’s previous level of something
How can you expect to regain trust with someone who lied to you so many times?
flexibility – a measure of one’s ability to stretch and bend parts of the body * One of the easiest ways to measure flexibility is to ask people to touch their toes without bending their knees.
mobility – one’s ability to move freely and without any problems
The doctors said it would take months to recover full mobility after the skiing accident.
stiffness – feelings of difficulty moving one’s muscles, especially after they have not been used for a long period of time or after a period of time when they have been overused
Jaime felt some stiffness in his legs the morning after his long run.
tightness – a feeling of restricted movement and difficulty making movements, as if something does not stretch or move as easily as before
A feeling of tightness in your chest could be a sign of a heart attack. Are you experiencing any other symptoms?
to lift – to raise something upward into the air; to move something up to a higher position
Please help me lift this suitcase into the compartment above my seat.
range of motion – a measure of how far one can move or rotate; a measure of the distance between the limits of one’s motion in two or more directions
* The doctor says Sayeed will be able to walk again, but he will never recover his full range of motion.
to bend at the waist – to bend over; to fold one’s body in half while standing, so that one’s head is closer to one’s feet
The aerobics instructor had us bend at the waist to touch our toes, and then straighten up and reach for the sky several times.
to squat – to bend one’s knees to lower one’s body closer to the ground, almost in a sitting position, usually for exercise
The grass was too wet to sit on, so we squatted and rested on our heels.
to stretch – to slowly extend the length of one’s muscles by reaching as far as possible, usually as a warm-up before exercising
It’s important to stretch your leg muscles before you play basketball.
to limber up – to stretch and warm up in order to become more flexible so that movement because easier and less likely to result in injury
The coach needs to give the kids some exercises so they can limber up before they start kicking the ball around.
to strengthen – to make something stronger and more powerful
Will this shampoo really strengthen my hair and make it less likely to break?
muscle – a part of the body that has the ability to contract (become smaller) and
expand (become bigger) in order to produce movement
My muscles are really sore after spending so much time doing yardwork yesterday.
to loosen – to become looser; to become less tight; to become able to move more freely
To take this desk apart, we need to first loosen these screws.
scar tissue – thick, dense tissue that forms as an injury heals
The doctors tried to close the cuts on Judah’s face in a way that will produce minimal scar tissue.
freely – openly, without restrictions, control, or limitations
You can speak freely here. No one will try to control what you say.
Comprehension Questions
1. Which of these results in greater mobility?
a) Feeling stiffness and tightness
b) Improving range of motion
c) Forming more scar tissue
2. What does Rashida mean when she says, “Are you able to squat?”
a) Are you able to feel your hands and feet?
b) Are you able to move your head without pain?
c) Are you able to bend your knees and move into a nearly sitting position?
Answers at bottom.
What Else Does It Mean?
to lift
The verb “to lift,” in this podcast, means to raise something upward into the air or to move something up to a higher position: “He lifted his son into the air so that he could see the clown over the heads of the other people.” The phrase “to lift (one’s) head” means to look upward or to stop looking down: “You look so sad!
Lift your head and smile.” The phrase “to lift (one’s) eyes” means to look up: “Your speech would be more persuasive if you lifted your eyes and looked that the audience members.” The phrase “to not lift a finger” means to not do anything to help: “I’m tired of doing all the cooking and cleaning while you don’t lift a finger.” Finally, the phrase “to lift (someone’s) spirits” means to help someone feel happier or more cheerful: “We took Sarah to the zoo to try to lift her spirits.”
to squat
In this podcast, the verb “to squat” means to bend one’s knees to lower one’s body closer to the ground, almost in a sitting position, usually for exercise: “The coach makes all the players squat for a full minute at the start of each practice because it helps to strengthen their leg muscles.” Or, “The man squatted so that he would be at eye level with the children.” The phrase “to squat” sometimes means to live in a building without permission: “A lot of homeless people are squatting in the vacant buildings downtown.” When describing people or objects, “squat” means short and fat: “The witness described the robber as a squat man with red hair.” Finally, the informal word “squat” means nothing: “They didn’t pay us squat!” Or, “I don’t care squat about her opinions.”
Culture Note
Mary Lou Retton
Mary Lou Retton, often referred to as America’s “Sweetheart” (a term of endearment; a word used to show affection and love for someone), is an American “gymnast” (someone involved in the sport of gymnastics, a sport with different exercises showing one’s ability to move quickly, easily, and with power and coordination). She participated in the 1984 Summer Olympics, where she became the first American to win the “all-around” (overall; involving all events) “gold” (first place) “medal” (award). She also won two “silver” (second place) medals and a “bronze” (third place) medal at the same Summer Olympics.
These successes made her one of the most popular American athletes. She received many “endorsement deals” (agreements in which athletes or other celebrities receive money in exchange for promoting particular products) and she was the first woman “featured” (pictured; shown) on a “Wheaties box” (a brand of breakfast cereal that became well known for using photos of athletes in its advertisements). She was named the 1984 Sports Illustrated Woman of the Year, and in 1990 she was named one of the top ten “most admired” (liked by many people) “public figures” (people who are well known).
Since the Olympics, Mary Lou Retton has remained active and has tried to encourage young people to “stay fit” (remain healthy). She was the “star” (lead actor) of a television program called Mary Lou’s Flip Flop Shop, which encouraged children to be active. She was also a member of the President’s Council on Physical Fitness and Sports, and she travels as a “motivational speaker” (someone who gives paid speeches to encourage others), particularly to promote the benefits of good “nutrition” (the healthfulness of what one eats) and exercise.
Comprehension Answers
1 - b
2 - c