= 1235
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,235 – Joining a Secret Society.
This is English as a Second Language Podcast episode 1,235. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast Store with additional courses in Business and Daily English. This episode is a dialogue between Nathan and Mia about joining a secret group, a secret society. Let’s get started.
[start of dialogue]
Nathan: Can you keep a secret?
Mia: Sure.
Nathan: I’ve been initiated into a secret society at school. I’m one of the chosen few.
Mia: Is it supposed to be a big deal?
Nathan: Of course it is. It’s very exclusive. Not many people are invited to join.
Mia: But what’s the purpose of this secret society?
Nathan: Well, we have a secret handshake and we have some really mysterious rites and rituals.
Mia: What kinds of rites and rituals?
Nathan: I can’t tell you. I’ve been sworn to secrecy.
Mia: But what is the purpose of the society? Do you have some goal to accomplish, some reason for existence?
Nathan: The point is that the members are bound by an allegiance to each other and to the society.
Mia: You mean like you’d take a bullet for each other?
Nathan: Well, no.
Mia: Or protect each other at all costs, even by lying and cheating?
Nathan: No, at least I wouldn’t.
Mia: Then what does it all amount to?
Nathan: If anyone asks us about it, we deny its existence. We have a secret that no one else knows.
Mia: Not anymore.
[end of dialogue]
Nathan begins our dialogue by asking Mia a question: “Can you keep a secret (secret)?” “Secret” is information that you don’t tell anyone else, that you keep private. Mia says, “Sure. I can keep a secret,” meaning “I can get information and then not tell anyone else about it.” Nathan says, “I’ve been initiated into a secret society at school.” “To initiate” (initiate) means to formally or officially allow someone into an organization, usually with some sort of special ceremony, some sort of special set of actions.
Nathan says that he has been “initiated into,” or made a member of, “a secret society.” A “secret society” is an organization whose members don’t talk about what goes on inside of the organization. Sometimes a secret society isn’t known to very many people – that is, not very many people know about it – but in some cases a secret society can be well-known – that is, lots of people know that it exists, but only the people inside of this group or society know what happens in the group.
There are some universities that have secret societies. Most famously, Yale University has some secret societies. Nathan has been made a member of a secret society at his school. He says, “I’m one of the chosen few.” That expression “the chosen (chosen) few” refers to a small group of people who are better than others – who are chosen, who are selected, because they meet certain qualifications. We might also use the word “elite” (elite) to describe this concept.
Mia says, “Is it supposed to be a big deal?” meaning “Is this something important?” Nathan says, “Of course it is. It’s very exclusive.” Something that is “exclusive” (exclusive) is limited to a small number of people. There are only very few people who are allowed into this group. “Not many people are invited to join,” Nathan adds. Mia says, “But what’s the purpose of this secret society?” Nathan says, “Well, we have a secret handshake and we have some really mysterious rites and rituals.”
A “handshake” (handshake) is what happens when you put your hand in someone else’s hand. A “secret handshake” is a special way of holding or touching someone else’s hand when you meet them that only people in a secret society know. Nathan says his secret society has a secret handshake. So, when two members of this group meet each other, instead of just shaking hands as two people would normally, they do something special with their hands. I don’t know what, of course, because it’s secret.
Nathan says his group also has some “mysterious rites and rituals.” Something that is “mysterious” (mysterious) is something that many people wonder about or are interested in but don’t understand. A “rite” (rite) – notice the different spelling, not (right) – is one part of a larger ceremony, something that people do together as a group. The word “rite” is normally associated with a religious ceremony, a religious event, but here it’s associated with what happens in this secret society.
A “ritual” (ritual) is something that is done in a ceremony or celebration repeatedly, every time the ceremony takes place. A “ritual,” however, could also describe anything that someone does repeatedly as part of a larger event or process. The difference between “rite” and a “ritual” is that a rite is usually something that involves several different rituals and words, or speeches, or other kinds of actions.
A ritual is part of a rite, or could be part of a rite, but the word “rite” is usually used to describe a whole set of rituals or a group of rituals and texts that are part of some ceremony – often a religious ceremony, but not always religious as is seen in this example, because the secret society has rites as well. Mia is curious. She says, “What kinds of rites and rituals?” Nathan says correctly, “I can’t tell you.” Of course, if it’s a secret society you can’t tell anyone what goes on in the secret society.
Nathan says, “I’ve been sworn to secrecy.” “To be sworn (sworn) to secrecy” means to have made a promise to someone or some group of people not to talk about a certain topic, not to share secret information. Mia says, “But what is the purpose of the society? Do you have some goal to accomplish, some reason for existence?” That is, is there some reason why you have this group?
Nathan responds, “The point is that the members are bound by an allegiance to each other and to the society.” Nathan says the reason the society exists is that its members are “bound (bound) by an allegiance (allegiance).” An “allegiance” is loyalty or commitment to another person. If you are bound by something, you are obligated. You have to do it. So, “to be bound by an allegiance to each other” means you are committed to loyalty to helping other people – in this case, other people in your society. Mia then asks, “You mean like you’d take a bullet for each other?”
The expression “to take a bullet” (bullet) means to die in order to protect another person by getting in the way of a bullet from a gun that might be aimed at that person or heading towards that person. The most famous example of this would be the people who protect the president of the United States. These group of people are called the “Secret Service,” and their job is, in fact, to take a bullet for the president – that is, to protect the president even if it means getting in front of the president if someone is trying to shoot the president.
More generally, the expression means that you would die for another person in order to protect that person. Mia is asking if this secret society is about having each other protect each other even if it means death. Nathan says, “Well, no.” Mia says, “Or protect each other at all costs, even by lying and cheating?” “At all costs” (costs) means no matter what, in all circumstances or all situations. Nathan says no, the secret society doesn’t mean that you would protect other members at all costs. Nathan says he wouldn’t do that.
Mia then asks, “Then what does it all amount to?” She’s asking what is the value or purpose of this society. That’s what the expression “to amount to” means. What is its purpose? What is its importance? What is its significance? Nathan responds, “If anyone asks us about it,” meaning asks us about the secret society, “we deny its existence.”
“To deny” (deny) means to say that something does not exist – to reject or refuse something. Some people deny reality. They decide that even though something is obviously true or something obviously exists, they say, “Oh no, it isn’t true. It doesn’t exist.” That’s what Nathan means when he says that the members of his secret society deny the society’s existence. They say, “Oh no, there is no such thing as a secret society.”
He says, “We have a secret that no one else knows,” but of course Nathan has just told Mia about his secret society, which is why Mia says at the end of our dialogue, “Not anymore,” meaning “Well, it used to be secret, but because you told me about your secret society, it is no longer a secret because I know about it.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Nathan: Can you keep a secret?
Mia: Sure.
Nathan: I’ve been initiated into a secret society at school. I’m one of the chosen few.
Mia: Is it supposed to be a big deal?
Nathan: Of course it is. It’s very exclusive. Not many people are invited to join.
Mia: But what’s the purpose of this secret society?
Nathan: Well, we have a secret handshake and we have some really mysterious rites and rituals.
Mia: What kinds of rites and rituals?
Nathan: I can’t tell you. I’ve been sworn to secrecy.
Mia: But what is the purpose of the society? Do you have some goal to accomplish, some reason for existence?
Nathan: The point is that the members are bound by an allegiance to each other and to the society.
Mia: You mean like you’d take a bullet for each other?
Nathan: Well, no.
Mia: Or protect each other at all costs, even by lying and cheating?
Nathan: No, at least I wouldn’t.
Mia: Then what does it all amount to?
Nathan: If anyone asks us about it, we deny its existence. We have a secret that no one else knows.
Mia: Not anymore.
[end of dialogue]
It’s no secret that the best scriptwriter in the world, in my opinion, is Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
secret – information that one cannot, will not, or should not share with others
* Can you keep a secret? We’re planning a birthday party for Meghan, but don’t tell her about it!
to initiate – to formally admit (allow to enter) someone into an organization with a special ceremony
* In the past, fraternities initiated new members by making them perform silly pranks around campus.
secret society – an organization with few members and that very few people know about, especially one that is surrounded by a lot of mystery
* The only way to become a member of this secret society is to be invited by another member, because they never publish application forms or contact information.
the chosen few – the elite; a small group of people who meet certain qualifications for selection; a small group of people who seem to be better than others
* Congratulations! You are one of the chosen few among thousands of applicants.
exclusive – limited to only a small group of people, or available for only a short period of time; not for everyone
* This exclusive offer is available only to our returning members and is not transferable.
secret handshake – a special way of greeting another person by holding his or her hand in a particular way, used to identify another person as a member of a particular group
* Those boys were best friends in high school and even developed a secret handshake that nobody else could figure out.
mysterious – involving many unanswered questions and attracting other people’s interest and curiosity
* That old woman is so mysterious! She never says anything, and she always wears a black covering over her head.
rite – one part of a ceremony; something that the members of a particular group do regularly, often as part of a ceremony, celebration, or religious tradition
* Some Christian churches have a rite of baptism for new members.
ritual – something done in the same way repeatedly as part of a ceremony or celebration
* What rituals does your family have for celebrating Thanksgiving?
sworn to secrecy – having made a promise to not share secret information; having promised to keep a secret
* Sorry, but I can’t answer your questions. I’ve been sworn to secrecy.
existence – being; continued survival; life
* Do you think humans have some kind of spiritual existence after death?
bound – obligated; tied or connected to someone or something; with commitments
* As police officers, you are bound to protect the people of this community.
allegiance – loyalty; an ongoing commitment to a person or organization
* The king needs a way to test the allegiance of the soldiers in his army.
to take a bullet – to die in order to protect another person by stepping in front of him or her when another person is shooting a gun or similar weapon, so that bullet kills oneself, often used figuratively
* I admire the president, but I don’t think I would take a bullet for him.
at all costs – no matter what; regardless of the consequences; in any circumstances or under any conditions
* The activists are protesting and sending the message that we must avoid war at all costs.
to amount to – to develop into something with a particular value or end result; to have some measure of importance or significance
* She worked so hard to earn a college degree, but what did it amount to? She can’t find a job in her field.
to deny – to state that something does not exist; to reject or refuse
* The students are denying that they cheated on the test, but the teacher has proof.
Comprehension Questions
1. A secret handshake is an example of…
a) A secret society
b) A ritual
c) An allegiance
2. What does it mean to take a bullet for another person?
a) To accept another person’s punishment
b) To argue with another person
c) To put oneself at risk to protect another person
Answers at bottom.
What Else Does It Mean?
the chosen few
The phrase “the chosen few” or “the privileged few” means the elite, or a small group of people who meet certain qualifications for selection: “The president has many advisors, but only the chosen few will be invited to the most important meetings.” The phrase “to name a few” means that one could list additional items or members of a group, but is choosing not to: “To prevent cancer, try to eat more fresh vegetables, like broccoli, spinach, and kale, just to name a few.” The phrase “few and far between” means being very rare and difficult to find or obtain: “High-paying jobs with job security are few and far between.” Finally, the phrase “no fewer than” is used to emphasize a large number of something: “I had to ask her to clean up her room no fewer than eight times.”
to amount to
In this podcast, the verb “to amount to” means to develop into something with a particular value or end result, or to have some measure of importance or significance: “The program had a lot of potential, but it was plagued by poor management and never amounted to much.” Or, “All those promises don’t amount to much unless they are backed by actions.” An “amount” is a quantity of something that can be measured: “They donated a large amount of money to the campaign.” Finally, the phrase “no amount of (something) can/will do (something)” means that something is impossible, or that something has no effect: “Unfortunately, Harold is so stubborn that no amount of begging or persuasiveness will change his mind.”
Culture Note
The “Know Nothing” Movement
The “Know Nothing” “movement” (an organized effort to change society in some way) was an American “political party” (a group of people with similar values, beliefs, and goals who work together to elect candidates for government jobs who have similar values, beliefs, and goals) in the mid-1850s. Its real name was the Native American Party and in 1955 it was “renamed” (given a new name) the American Party. Part of the movement was very “secretive” (not wanting to share information). When members were asked a question, they were supposed to say, “I know nothing” – “hence” (from there) the “origin” (source) of the term “Know Nothing.”
The movement “grew out of” (arose from) fears about the “influx” (sudden increase) in the number of “immigrants” (people who come from another country to live). Specifically, people were worried about the large number of immigrants from Germany and Ireland. White “Protestant” (a branch of Christianity) men feared that Catholics from Ireland were controlled by the “Pope” (the leader of the Catholic Church) and were “hostile to” (opposing; against) their values. In California, the party primarily “opposed” (was against) Chinese immigrants. These men wanted to “purify” (make clean or pure) American society and politics by placing “restrictions” (limitations) on the “influence” (power and persuasiveness) of the immigrant groups.
The Know Nothing movement experienced great success in the 1854 elections and in just a few months its “membership” (the number of people involved in an organization) increased from 50,000 to more than one million. But by 1856, the party’s members were “conflicted” (disagreed; fought) over the issue of “slavery” (the practice of buying and selling people, and forcing them to work without pay) and the party “dissolved” (fell apart) soon after.
Comprehension Answers
1 - b
2 - c