= 1237
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,237 – Disagreements about Spending Money.
This is English as a Second Language Podcast episode 1,237. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com, please. When you do, you can take a look at our ESL Podcast Store that has additional courses in Business and Daily English. Isn’t that wonderful? I think it is. You can also check out our ESL Podcast Blog on that same web address.
This episode is a dialogue about how to spend money. Sounds like fun. Let’s get started.
[start of dialogue]
Ezra: Wait a minute. What happened to the $500 in our joint account?
Charlotte: I probably paid bills with it. You know that our paychecks barely cover our monthly expenses.
Ezra: I know, but I was counting on that $500 to pay for new tires for my car.
Charlotte: Do you really need new tires right now? The way I look at it, if there’s any balance in our account, I have dibs on it for some new shoes.
Ezra: Forget it. The tires are a necessity and your shoes are not. We’re each supposed to have $150 a month for discretionary spending for nonessentials, and new shoes definitely falls into that category.
Charlotte: You don’t need to spend $500 for a set of new tires. You just want to splash the cash for some fancy ones.
Ezra: Let’s stop arguing about who gets to spend the money and first figure out what happened to it. According to this, the money was withdrawn from our account for automatic contributions to our retirement accounts.
Charlotte: Our what?
Ezra: Our retirement accounts. Remember last month we decided to start saving money for retirement?
Charlotte: Whose harebrained idea was that? Do you think we can get the money back?
Ezra: I’m not sure, but if we can, I have dibs!
[end of dialogue]
Ezra begins our dialogue by saying to Charlotte, “Wait a minute,” meaning stop. “What happened to the $500 in our joint account?” A “joint (joint) account” is a bank account that two or more people share, which means that either person, if it’s a two-person account, can spend money from that bank account – or “withdraw money,” we would say.
Charlotte says, “I probably paid bills with it.” Charlotte says that she “probably paid bills” (bills) with this $500. “Bills” refer to obligations that you have to give other people money. You may have a “telephone bill.” The telephone company may send you a “bill” in the mail, a piece of paper telling you how much money you have to pay them for your telephone service.
Charlotte says, “You know that our paychecks barely cover our monthly expenses.” Your “paycheck” (paycheck) is money you get from your job every week or two weeks, perhaps every month, in exchange for working at your job. The verb “to cover” here refers to the ability to pay for something, to have enough money to pay for something. You have to have enough money “to cover your rent” – that is, to pay for your rent.
If we say something “barely (barely) covers” your “expenses,” what you have to pay to live, we mean you have enough but just enough. You may need $100 and you have $101. So, you barely have enough money. The money you have “barely covers” your monthly expenses. Again, “expenses” just refers to money that you have to spend in order to live or in order to do a certain thing.
Ezra says, “I know, but I was counting on that $500 to pay for new tires for my car.” Ezra understands that the paychecks that he and Charlotte get barely cover their monthly expenses, but he was “depending on,” or relying on – he says “counting on” – the $500 to buy new tires for his car. Charlotte says, “Do you really need new tires right now? The way I look at it” – meaning the way I see things, or in my opinion – “if there’s any balance in our account, I have dibs on it for some new shoes.” A “balance” (balance) refers to an amount of money that is in, in this case, your bank account.
Charlotte is saying that if they have extra money in their bank account, she has “dibs (dibs) on it.” “To have dibs on” something is to have the right to have or to do something before another person. It’s a somewhat informal expression often used in families, especially among children. Children will say, “I have dibs on that seat on the couch.” In other words, I am the person who gets to use that seat on the couch before anyone else. Another way of using this word “dibs” is “to call dibs.” “I called dibs on the last piece of cake.” In other words, that’s mine. No one else can have it.
Charlotte says she has dibs on any extra money in their bank account so she can buy some new shoes. Ezra disagrees. He says, “Forget it. The tires are a necessity and your shoes are not.” A “necessity” is something you need, something that is necessary or required. He says, “We’re each supposed to have $150 a month for discretionary spending for nonessentials, and new shoes definitely falls into that category.”
Ezra and Charlotte give themselves each $150 every month for “discretionary (discretionary) spending.” Spending that is “discretionary” is something that you control and that is not affected by any other rules or obligations. “Nonessentials” refers to things that are not essential. Something that is “essential” is something that is “necessary.” “Essential” and “necessity” here are related. “Nonessentials” are things that are not required, not necessary.
Ezra is saying that new shoes are “nonessentials.” He says they “fall into the category of nonessentials.” “To fall into” is a two-word phrasal verb meaning that it has the characteristics of a particular group or a particularly category. That’s why he says it “falls into” that category. It is to be classified or it is to be described as being, in this case, nonessential. Charlotte says, “You don’t need to spend $500 for a set of new tires.” You don’t need to spend five hundred dollars for four new tires, Charlotte is saying. “You just want to splash the cash for some fancy,” or nice, “ones.”
The expression “to splash (splash) the cash (cash)” means to spend money on something that causes other people to notice you, especially when you’re buying things that are expensive but aren’t necessary. It’s an informal expression, “to splash the cash.” If you go out and buy a new Mercedes-Benz or a new BMW car or a new Rolls Royce even if you don’t need one – and after all, who really needs that expensive of a car – we might say that you are “splashing the cash.” Perhaps you want to try to get a new girlfriend or perhaps you want your neighbors to think that you are very rich.
Ezra says, “Let’s stop arguing about who gets to spend the money and first figure out,” or determine, “what happened to it” – what happened to the $500. “According to this” – and we imagine that Ezra is looking at their bank statement, a piece of paper describing everything that happened in their bank account last month – “the money was withdrawn from our account for automatic contributions to our retirement accounts.” “Withdrawn” comes from the verb “to withdraw,” which means to take out of something.
When we’re talking about money and bank accounts, we refer to “depositing money” – putting money in – and “withdrawing money,” taking money out. The money was withdrawn from Ezra and Charlotte’s account for “automatic contributions.” Something that is “automatic” (automatic) is something that happens without you having to do anything or take any action yourself. A “contribution” is when you give money or something else to someone or to something.
In this case, we’re talking about putting money, or we would use the verb “contributing” money, to a “retirement account.” “Retirement” (retirement) describes what happens after you stop working, usually after the age of, say, 65 or 67. That’s called “retirement.” You are no longer working. But of course you still need money, and in the United States many people have what are called “retirement accounts” that you put money into while you are still working.
That money is then, we hope, invested in stocks or bonds or some other sort of financial instrument that allows you to make even more money with your money, so that when you stop working, you have money to live on. Yes, the government gives you money through a system we call “Social Security,” but often it isn’t very much.
So, this $500 that Charlotte and Ezra are talking about was actually taken or withdrawn from their account and put into their retirement accounts. In many companies, this happens automatically. You decide how much money you want to put into your retirement account, and every month the company takes part of your paycheck and puts it into a retirement account. That’s what happens here at CED.
Charlotte says, “Our what?” She seems confused. Ezra says, “Our retirement accounts. Remember last month we decided to start saving money for retirement?” Charlotte says, “Who’s harebrained idea was that?” “Harebrained” (harebrained) means stupid, foolish, something that was done without thinking about it very carefully. Charlotte is saying that having a retirement account is a “harebrained” idea.
She says, “Do you think we can get the money back?” She’s asking if you can then get that money back from your retirement account. By the way, the answer to that is usually no. The retirement accounts are often protected for tax reasons, and so you can’t just put money in and take it out whenever you want. You have to wait until you reach a certain age.
Charlotte wants to get the money back, however. Ezra says, “I’m not sure,” meaning I’m not sure if we can get the money back, “but if we can, I have dibs!” Notice once again the use of that word “dibs,” meaning Ezra gets to use the money if they can get it out of their retirement account – which as I mentioned, they probably can’t.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Ezra: Wait a minute. What happened to the $500 in our joint account?
Charlotte: I probably paid bills with it. You know that our paychecks barely cover our monthly expenses.
Ezra: I know, but I was counting on that $500 to pay for new tires for my car.
Charlotte: Do you really need new tires right now? The way I look at it, if there’s any balance in our account, I have dibs on it for some new shoes.
Ezra: Forget it. The tires are a necessity and your shoes are not. We’re each supposed to have $150 a month for discretionary spending for nonessentials, and new shoes definitely falls into that category.
Charlotte: You don’t need to spend $500 for a set of new tires. You just want to splash the cash for some fancy ones.
Ezra: Let’s stop arguing about who gets to spend the money and first figure out what happened to it. According to this, the money was withdrawn from our account for automatic contributions to our retirement accounts.
Charlotte: Our what?
Ezra: Our retirement accounts. Remember last month we decided to start saving money for retirement?
Charlotte: Whose harebrained idea was that? Do you think we can get the money back?
Ezra: I’m not sure, but if we can, I have dibs!
[end of dialogue]
We have no harebrained dialogues. Everything is thought out carefully and done to perfection by our own scriptwriter, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
joint account – a bank account that is shared by two or more people, so that either of them can spend the money and make other decisions about it
* One of the most diffficult parts of being married was learning how to manage a join account.
paycheck – a payment received from one’s employer for one’s work, typically once a week or twice a month
* Experts recommend trying to save 20% of each paycheck for retirement and unexpected expenses.
barely – hardly; almost not enough; almost not at all; without any extra
* We barely had enough food for all the unexpected guests.
to cover – to be able to pay for something; to have enough money to pay for what is needed
* When Ariana’s baby was born, she had to get a second job to pay for the cost of daycare.
monthly expenses – the amount of money that one spends each month, including details about the types of expenses
* Please create a budget showing your average monthly expenses for housing, utilities, transportation, food, and entertainment.
to count on – to depend on; to rely on and to look forward to
* We were counting on the volunteers, so it was very frustrating that some of them didn’t show up as planned.
the way I look at it – a phrase used to express one’s opinion or perspective, especially when one knows that the other person disagrees
* The way I look at it, saving money for college is the most important thing we can do for our daughter.
balance – the amount of money that is available in a bank account
* The balance shows that we still have a few hundred dollars, but remember that we mailed off a few checks earlier this week and those aren’t reflected in the balance yet.
dibs – the right to have or do something before another person
* I have dibs on the ice cream, but you can eat the pie.
necessity – something that one needs; something that one must have or do in order to survive
* Learning to cook basic things before you move out on your own is a necessity.
discretionary – something that is under one’s own control and is not established by an authority or by rules
* Justin thinks that haircuts and manicures are discretionary expenses, but his wife disagrees and says that she needs them for work.
nonessential – something that is not required for survival, but that is nice to have
* Mimi and Dave spent so much money on nonessentials like concert tickets and electronics that they didn’t have enough money left to pay their rent.
to fall into – to be categorized in a particular way; to have the qualifications or characteristics of a particular group
* New employees fall into two groups: those who welcome challenges and work hard to excel, and those who complain about the heavy workload.
to splash the cash – to spend a lot of money in a way that causes other people to notice, especially when buying items that are not necessary and that are expensive
* We were tempted to splash the cash on a new luxury car, but in the end, we decided to keep driving our old car for a few more years.
to withdraw – to take money out of a bank account; to deduct
* Please go to the bank and withdraw $200 from our account.
automatic contribution – an amount of money that is scheduled to be taken out of one’s bank account on the same date each month, without needing to make a new request each time
* Many nonprofit organizations encourage their members to make automatic contributions, rather than one-time donations.
retirement account – a special type of investment account that is used to manage money being saved for use in the future, when one is no longer working
* Please tell me about the tax benefits of putting money in a retirement account.
harebrained – foolish, rushed, and not well thought-out; a decision that was made too quickly with inadequate information
* Who came up with the harebrained idea to give my kids caffeine before bedtime? Now they’ll never fall asleep.
Comprehension Questions
1. What happened to the $500?
a) They forgot that they decided to save it.
b) They bought tires.
c) They bought new shoes.
2. What does Charlotte mean when she says, “I have dibs”?
a) She is very upset with Ezra.
b) She needs to find a higher-paying job.
c) She wants to be the person who spends the money.
Answers at bottom.
What Else Does It Mean?
barely
The word “barely,” in this podcast, means hardly, almost not enough, and without any extra: “What’s wrong? You’ve barely spoken to me all evening.” The word “barely” is also used to emphasize that a number or value is very low: “We barely made $70,000 in profits last year.” The word “bare” means naked and without any clothing or coverings: “Your bare arms are going to get sunburned if you don’t put on some sunscreen.” When talking about trees or bushes, “bare” means without any leaves: “It’s January, so all the trees are bare, but we’ll start to see new leaves in a few months.” Finally, the phrase “with (one’s) bare hands” means with one’s own hands, without using a tool: “Did you really catch that fish with your bare hands? That’s amazing!”
to splash the cash
In this podcast, the phrase “to splash the cash” means to spend a lot of money in a way that causes other people to notice, especially when buying items that are not necessary and that are expensive: “Why would you splash the cash on designer clothing when you can get similar items at a much lower price at regular department stores?” The phrase “to splash out” means to spend a lot of money on something: “We hated splashing out thousands of dollars for a new roof.” The phrase “to splash around” means to make water fly up in many different directions: “The children had so much fun splashing around in the pool.” Finally, the phrase “to splash across” means for a story or image to be highly visible on the front page of a newspaper: “It was so strange to see Dad’s face splashed across the newspaper.”
Culture Note
Types of Formal and Informal Bank Accounts
Banks offer two main types of formal accounts: “checking accounts” that are used for daily expenses, and “savings accounts” that are used to save money for the future. Individuals might “subdivide” (divide into smaller groups) those accounts into informal accounts, such as “emergency savings,” or money that they are saving to cover unexpected costs, such as a health emergency or situation where someone loses his or her job. The emergency savings probably aren’t in a separate account; the “funds” (money) are most likely in the savings account, but the “accountholder” (the person who owns the account and can access the money) has “mentally” (in his or her mind) “set that money aside” (designated something for a particular purpose).
Many people have “investment accounts” (ways to manage money placed in the stock market). These are often retirement accounts or “college savings accounts,” where money is being saved until the future when a child needs it to attend a university. And some investment accounts are simply used to hold money that “wealthy” (rich) people do not have an immediate need for, but can use to make more money.
Finally, a “flexible spending account” is a special type of account that holds money “deducted” (subtracted) from one’s paycheck to cover certain types of expenses, such as “daycare” (childcare) and “medical expenses” (the costs of healthcare services and medicines). When people pay for such expenses out of their flexible spending account, they do not have to pay taxes on that money, which can result in significant cost savings.
Comprehension Answers
1 - a
2 - c