

= Lesson 22
:toc: left
:toclevels: 3
:sectnums:

'''

https://www.kekenet.com/Article/201807/558819.shtml


== 国债债券

The Treasury Department announced today that it is lowering *the guaranteed 肯定的，保障的；（贷款）有担保的 interest rate* on some US *savings bonds* 储蓄债券. +
美国财政部今天宣布, 降低部分美国储蓄债券的保证利率。

.案例
====
.guaranteed interest
保本利息
====

NPR’s Barbara Mantell reports that the 1.5 point decline to 6% *came as no surprise to* investors. +
NPR 的芭芭拉·曼特尔 (Barbara Mantell) 报道称，投资者对这一比例下降 1.5 个百分点至 6% , 并不感到意外。

"The Treasury said *it is lowering (v.) the rate on savings bonds* to bring it *in line with* other *market interest rates* which have been falling all year. +
“财政部表示，将降低储蓄债券利率，使其与全年一直下降的其他市场利率, 保持一致。

For instance, money market *mutual 相互的；彼此的;共有的；共同的 funds* are now yielding 出产（作物）；产生（收益、效益等）；提供 just over 5%; five-year *treasury notes* (纸币) 国库券 are trading (v.)做买卖；做生意；从事贸易 at about 6.5%. +
例如，货币市场共同基金的收益率, 目前略高于 5%；五年期国债的交易价格约为 6.5%。

.案例
====
.mutual
(a.) +
1.used to describe feelings that two or more people have for each other equally, or actions that affect two or more people equally 相互的；彼此的 +
• *mutual respect/understanding* 相互的尊敬╱理解 +
• *mutual support/aid* 相互的支持╱帮助 +
• I don't like her, and I think the feeling is mutual (= she doesn't like me either) . 我不喜欢她，我觉得她也不喜欢我。 +

2.[ only before noun] shared by two or more people 共有的；共同的 +
• We met at the home of *a mutual friend*. 我们在彼此都认识的朋友家中会面。  +
• They soon discovered *a mutual interest* in music. 他们很快发现对音乐有着共同的兴趣。  +
====

So the government has been *paying* a premium 额外费用；附加费;额外费用；附加费 *to* people buying savings bonds, and *it’s turned out to be* an expensive way to finance (v.)提供资金 the public debt. +
因此，政府一直在向购买储蓄债券的人们支付溢价，事实证明这是一种昂贵的公共债务融资方式。

*The relatively generous 慷慨的；大方的；慷慨给予的 7.5% rate* on the bonds have made them very popular in the past few months. +
相对慷慨的7.5%利率, 使其在过去几个月非常受欢迎。

Since the beginning of August, sales have been about double (v.) the usual pace （移动的）速度；步速. +
自八月初以来，销售额约为平时的两倍。

And this week, the rush to buy savings bonds intensified (v.)（使）加强，增强，加剧 because of reports (n.) that *the Treasury* 财政部 was going to cut the rate *any day* 任何一天，任何时候, and people wanted to lock in the old rate. +
本周，由于有报道称, 财政部将随时降息，人们希望锁定旧利率，因此购买储蓄债券的热潮加剧。

Savings bonds *bought (v.) before tomorrow*, the day *the cut goes into effect*, will still yield 7.5%. I’m Barbara Mantell in New York."  +
明天之前购买的储蓄债券，也就是削减生效的那一天，收益率仍将达到 7.5%. 我是纽约的芭芭拉·曼特尔。”

'''

==

After a meeting today of southern Africa’s *front line states*, Zambian President Kenneth Kaunda said a number of front line leaders *hold* South Africa *directly responsible* for the plane crash that killed Mozambique President Samora Machel. +
今天在南部非洲前线国家举行会议后，赞比亚总统肯尼思·卡翁达表示，一些前线国家领导人认为, 南非对莫桑比克总统萨莫拉·马谢尔遇难的空难, 负有直接责任。

Kaunda said *there was circumstantial 按情况推测的；视情况而定的；间接的 evidence* linking South Africa to the crash, but he didn’t say what that evidence was. +
卡翁达表示，有间接证据表明南非与这起事故有关，但他没有透露这些证据是什么。

.案例
====
.circumstantial
(a.) +
( law 律) containing information and details *that strongly suggest that sth is true* but do not prove it 按情况推测的；视情况而定的；间接的 +
• circumstantial evidence 情况证据 +
• The case against him was *largely circumstantial*. 对他不利的案情, 大多为间接推测的。  +

2.( formal ) connected with particular circumstances 与特定条件（或环境、情况）有关的 +
• Their problems were *circumstantial* rather than personal. 他们的困难是环境而非个人所致。  +
====


He said it’s up to the Pretoria government to prove to the contrary. +
他说，需要比勒陀利亚政府证明事实并非如此。

Official Soviet radio said today all clues point to Soviet-South African complicity in the death of Machel.
苏联官方电台今天表示，所有线索都表明苏联和南非在马谢尔之死中串通一气。

President Reagan today named a black career diplomat to be US Ambassador to South Africa.
里根总统今天任命一名黑人职业外交官为美国驻南非大使。

Edward Perkins, now Ambassador to Liberia, would succeed retiring Ambassador Herman Nickel.
现任驻利比里亚大使爱德华·帕金斯将接替即将退休的赫尔曼·尼克尔大使。

NPR’s Phyllis Crockett has more: "Perkins is the third man President Reagan has considered in three months in his attempt to appoint a black to this sensitive post.
NPR 的菲利斯·克罗克特 (Phyllis Crockett) 报道了更多内容：“帕金斯是里根总统三个月内考虑任命黑人担任这一敏感职位的第三位人选。

North Carolina businessman, Robert Brown, turned down the job after questions were raised about his business dealings while he served in the Nixon Administration.
北卡罗来纳州商人罗伯特·布朗在尼克松政府任职期间，由于有人对他的商业交易提出质疑，他拒绝了这份工作。

Then Terrance Todman, Ambassador to Denmark, turned down the job, apparently because he disagrees with the Reagan Administration policy towards South Africa.
随后，驻丹麦大使特伦斯·托德曼拒绝了这份工作，显然是因为他不同意里根政府对南非的政策。

Perkins has been a foreign service officer for twenty-eight years.
珀金斯担任外交官员已经二十八年了。

He’s fifty-eight years old and has served in Taiwan, Thailand, Ghana and at the State Department before becoming Deputy Chief of the US Embassy in Liberia in 1981.
他现年 58 岁，曾在台湾、泰国、加纳和国务院任职，1981 年成为美国驻利比里亚大使馆副馆长。

He became Ambassador in 1985.
1985年出任大使。

Black and white South Africans as well as many in this country have said that naming a black ambassador is meaningless as long as US policy toward the white-ruled government remains the same.
南非黑人和白人以及该国许多人都表示，只要美国对白人统治的政府的政策保持不变，任命黑人大使就毫无意义。

I’m Phyllis Crockett in Washington." President Reagan today nominated a career foreign service officer to become the first black US ambassador to South Africa.
我是华盛顿的菲利斯·克罗克特。”里根总统今天提名了一名职业外交官员，成为第一位美国驻南非黑人大使。

The long expected move comes as the Senate get set to vote tomorrow on overriding President Reagan’s veto of a bill that would impose more economic sanctions on South Africa.
这一期待已久的举措出台之际，参议院将于明天投票推翻里根总统对一项对南非实施更多经济制裁的法案的否决。

The newly named envoy is Edward Perkins.
新任命的特使是爱德华·帕金斯。

He is now the American Ambassador to the west African nation of Liberia.
他现在是美国驻西非国家利比里亚大使。

NPR’s Phyllis Crockett has a report: It’s been three months since President Reagan first indicated his desire to appoint a black to this sensitive post.
NPR 的菲利斯·克罗克特 (Phyllis Crockett) 有一篇报道：距离里根总统首次表示希望任命一名黑人担任这一敏感职位已经过去了三个月。

Perkins is the President’s third choice.
帕金斯是总统的第三选择。

In July, the President had planned to name a black ambassador during a televised speech on South Africa.
七月，总统计划在关于南非的电视讲话中任命一名黑人大使。

But the man under consideration, businessman and former Nixon-aide Robert Brown, withdrew his name after questions were raised about his business dealings.
但正在考虑的人是商人、尼克松前助手罗伯特·布朗，在他的商业交易受到质疑后，他撤回了自己的名字。

Then, the administration’s next choice, Terrence Todman, Ambassador to Denmark, turned down the job, apparently because he disagrees with the Reagan Administration policy towards South Africa.
然后，政府的下一个选择，驻丹麦大使泰伦斯·托德曼拒绝了这份工作，显然是因为他不同意里根政府对南非的政策。

In contrast to the President’s plan to name his first choice in a national speech, today’s announcement came with no fanfare.
与总统计划在全国演讲中提名他的第一人选相反，今天的宣布并没有大张旗鼓。

There was no news conference, no press briefing, no opportunity for questions today.
今天没有新闻发布会，没有新闻发布会，没有提问的机会。

Instead, a notice was handed out to reporters at the White House that Perkins was the President’s choice.
相反，白宫向记者发出了一份通知，称帕金斯是总统的选择。

Apparently, the low key announcement was a response to the earlier embarrassment of some top White House officials who felt the first two names became public before adequate scrutiny.
显然，这一低调的宣布是对一些白宫高级官员早些时候感到尴尬的回应，他们认为前两个名字在充分审查之前就被公开了。

They expect Perkins to be easily confirmed by the Senate.
他们预计帕金斯将很容易获得参议院的批准。

Perkins has been a foreign service officer for twenty-eight years.
珀金斯担任外交官员已经二十八年了。

He has served in Taiwan, Thailand, Ghana and in Washington, D.C.
他曾在台湾、泰国、加纳和华盛顿特区任职。

In 1981, he became the 2nd in command at the US Embassy in Liberia.
1981年，他成为美国驻利比里亚大使馆二把手。

In 1985, he became Ambassador.
1985年出任大使。

He is fifty-eight years old.
他今年五十八岁。

His wife is Chinese.
他的妻子是中国人。

They have two children.
他们有两个孩子。

When President Reagan first indicated his intention to appoint a black ambassador, blacks and whites in South Africa said that naming a black will make little difference if US policy remains the same.
当里根总统首次表示打算任命一位黑人大使时，南非的黑人和白人表示，如果美国政策保持不变，任命黑人不会有什么影响。

The Perkins announcement comes one day after President Reagan offered to impose strong sanctions against the South African government if Congress drops its stronger sanctions.
帕金斯宣布这一消息的一天前，里根总统提出，如果国会放弃更严厉的制裁，他将对南非政府实施严厉制裁。

Secretary of State, George Shultz, told Republican senators today that a vote to override the President’s veto of a sanctions bill would undermine his negotiating position in next month’s summit meeting with Soviet leader Mikhail Gorbachev.
美国国务卿乔治·舒尔茨今天告诉共和党参议员，推翻总统对制裁法案否决的投票将损害他在下个月与苏联领导人米哈伊尔·戈尔巴乔夫举行的峰会上的谈判地位。

The House overrode the veto yesterday.
众议院昨天推翻了否决权。

The Senate is expected to take it up tomorrow.
预计参议院明天将对此进行审议。

I’m Phyllis Crockett in Washington.
我是华盛顿的菲利斯·克罗克特。

Fifty years ago, British aviator Beryl Markham became the first person to fly alone across the Atlantic Ocean, from east to west.
五十年前，英国飞行员贝里尔·马卡姆成为独自从东到西飞越大西洋的第一人。

Her achievement was marred, though, as were many of her accomplishments.
然而，她的成就和她的许多成就一样，受到了损害。

Markham had set out to fly from London to New York.
马卡姆原定从伦敦飞往纽约。

She ended up flying from London to Nova Scotia.
她最终从伦敦飞往新斯科舍省。

That flight and other aspects of her extraordinary life are told in Markham’s book West with the Night .
马卡姆的著作《夜西》讲述了那次飞行和她非凡生活的其他方面。

This week, many public television stations will broadcast a documentary about Markham called "World without Walls".
本周，多家公共电视台将播放一部关于万锦市的纪录片，名为《没有围墙的世界》。

NPR’s Susan Stanberg tells Beryl Markham’s story.
NPR 的苏珊·斯坦伯格讲述了贝丽尔·马卡姆的故事。

New York City, September 6th, 1936, a ticker-tape parade, and Mayor Fiorello LaGuardia greeting a tall, blond English woman who, just the day before, had completed a 21-hour-and-25-minute flight across the Atlantic, Ebbingdon, England to a nameless swamp, non-stop.
1936 年 9 月 6 日，纽约市，一场彩带游行，市长菲奥雷洛·拉瓜迪亚 (Fiorello LaGuardia) 向一位身材高大、金发碧眼的英国女士致意，她在前一天刚刚完成了 21 小时 25 分钟的横跨大西洋飞行，英格兰埃宾登到一片无名沼泽，马不停蹄。

"Miss Markham, may I, on behalf of the city of New York, extend to you, a sincere welcome and our congratulations on your splendid flight across the ocean." "Thank you so much.
“马卡姆小姐，我谨代表纽约市向您表示诚挚的欢迎，并祝贺您实现跨越大洋的精彩飞行。” “太感谢了。

I’m so happy to be here.
我很高兴来到这里。

Thank you so much." Nine years after Lindbergh, and going in the other direction, his Spirit of Saint Louis, soloed New York to Paris, Beryl Markham, thirty-four years old, had flown seventeen of the twenty-one and a half hours in fog and darkness, with no fuel gauge, no radio, no idea where she was most of the time, to crash land, after the engine of her monoplane died in a bog on Cape Breton Island, Nova Scotia.
非常感谢。” 林德伯格驾驶他的圣路易斯精神号从纽约飞往巴黎九年后，34 岁的贝里尔·马卡姆 (Beryl Markham) 飞了 21 架半中的 17 架。她的单翼飞机在新斯科舍省布雷顿角岛的沼泽中熄火，她在雾和黑暗中度过了几个小时，没有燃油表，没有收音机，大部分时间都不知道她在哪里，最终迫降。

The next day, she was being cheered in New York.
第二天，她在纽约受到欢呼。

"It was a hard battle against the elements above the ocean, fog and storm, but pluck and endurance crowned one of the most grueling flights on record." "I am so pleased to have got here; I only wish I could come in my own machine." "And now, onto a New York hotel, to be interviewed by a movie waker, Mrs.
“这是一场与海洋、大雾和风暴等因素的艰苦战斗，但勇气和耐力成为有记录以来最艰苦的飞行之一。” “我很高兴来到这里；我只希望我能乘坐自己的机器来。” “现在，在纽约的一家酒店，接受电影唤醒者的采访，夫人。

Markham, just what were you thinking about while flying through all that fog and storm?" "Well, my one thought and ambition was to get to America." "When above the sea, what did you eat or drink?" "I didn’t have anything until the last half hour when I had a taste of brandy." "Just one?" "No, two, I’m afraid." Aviation was very young then.
马卡姆，当你飞过那些大雾和暴风雨时，你在想什么？” “嗯，我的一个想法和野心就是去美国。” “当在海上时，你吃了什么或喝了什么？” “我没有直到最后半小时我尝到了白兰地的味道才吃任何东西。” “只有一杯？” “不，恐怕是两杯。” 那时航空业还很年轻。

Every single day without fail, there were two or three articles in the newspapers about people being killed in aircraft.
报纸上每天都会无一例外地刊登两三篇有关人员在飞机上丧生的文章。

It was completely new sport.
这是一项全新的运动。

Mary Lovell has just completed a biography of Beryl Markham.
玛丽·洛弗尔刚刚完成了贝丽尔·马卡姆的传记。

The book will be published next spring.
该书将于明年春天出版。

The engines were not very reliable.
发动机不太可靠。

All she had was a compass and some kind of direction-finding equipment that didn’t work very well.
她只有一个指南针和某种不太好用的测向设备。

She really didn’t know where she was for a long time.
她真的很长一段时间都不知道自己身在何处。

She had no idea how far off the coast she was, whether her fuel would last.
她不知道自己距离海岸有多远，也不知道她的燃料是否还能用。

I think the one time in her life she has been frightened was then.
我想她一生中唯一一次感到害怕就是那时。

For most of her eighty-three years, Beryl Markham was indeed fearless.
在贝丽尔·马卡姆八十三年的大部分时间里，她确实无所畏惧。

As a child growing up in Africa, she faced down a marauding lion.
作为一个在非洲长大的孩子，她曾面对过一头掠夺性的狮子。

As a trainer, she forced high-strung racehorses to obey her.
作为一名驯马师，她强迫高度紧张的赛马服从她。

As an old woman, she drove her car through a machine gun fire during an attempted coup in Kenya.
在肯尼亚的一次未遂政变中，作为一名老妇人，她驾驶着自己的汽车冲过机关枪的扫射。

She wanted to keep a luncheon date.
她想保留一个午餐约会。

It was simply her nature to confront danger.
面对危险只是她的本性。

"There’s a coolness to her.
“她有一种冷静。

She’s not a very trusting person." Writer Judith Theuman.
她不是一个很容易信任人的人。”作家朱迪思·休曼。

"I think any person who’s lived by her wits would probably have developed that coolness.
“我认为任何靠她的智慧生活的人都可能会发展出那种冷静。

Look at the astronauts.
看看宇航员。

I mean, it’s a quality that you see it in fliers.
我的意思是，你可以在传单中看到这种品质。

You see it in sailors, or you see it in hunters, and Beryl was of that stamp." There were other interpretations of Markham’s coolness.
你可以在水手身上看到这一点，或者在猎人身上看到这一点，而贝丽尔就是这样的人。”对于马卡姆的冷静还有其他的解释。

Some said she lacked the sense to be afraid.
有人说她缺乏害怕的意识。

People often said nasty things about Beryl Markham, especially other women.
人们经常说贝丽尔·马卡姆的坏话，尤其是其他女性。

It’s easy to figure out why.
很容易找出原因。

"She was beautiful.  “她很漂亮。

She was very seductive.
她非常迷人。

She was well born.
她出生得很好。

And she was strong and ambitious and fearless and smart.
她坚强、雄心勃勃、无所畏惧、聪明。

So, you know, it’s a lot to take." Ironically, recognition did come to Beryl Markham, but only in the last years of her life.
所以，你知道，这需要承受很多。”具有讽刺意味的是，贝丽尔·马卡姆确实得到了认可，但只是在她生命的最后几年。

Since West with the Night was reissued three years ago, it’s sold briskly.
《西与夜》自三年前重新发行以来，销量十分火爆。

There are 300,000 copies in print now, and royalties from the book gave much needed financial security.
目前已经印刷了 300,000 册，这本书的版税提供了急需的财务保障。

More recognition will come with the showing on public television this week, of the documentary about her.
本周有关她的纪录片在公共电视上播出后，将会获得更多认可。

More recognitions still, when Mary Lovell’s biography comes out next spring.
当玛丽·洛弗尔的传记明年春天出版时，还会获得更多认可。

And another biography is in the work for publication in a few years.
另一本传记即将在几年内出版。

So the story of the woman who flew west on that difficult, dangerous night in 1936 will be told and re-told.
因此，1936 年那个艰难、危险的夜晚，那位妇女向西飞行的故事将会被讲述和重述。

Through the darkness, wedged between extra fuel tanks that had been fitted into the cabin for the long journey, her small plane bucking fog and storms and headwinds, the Atlantic Ocean black beneath her, Beryl Markham flew west with the night, completely alone.
穿过黑暗，贝里尔·马卡姆（Beryl Markham）在为长途旅行而安装在机舱内的额外油箱之间，她的小飞机顶着雾气、暴风雨和逆风，下面是黑色的大西洋，贝里尔·马卡姆（Beryl Markham）在夜色中向西飞行，完全孤独。

"You can live a lifetime and, at the end of it, know more about other people than you know about yourself.
“你可以活一辈子，到最后，对别人的了解比对自己的了解还要多。

You learn to watch other people, but you never watch yourself because you strive against loneliness.
你学会观察别人，但你从不观察自己，因为你与孤独作斗争。

If you read a book or shuffle a deck of cards, or care for a dog, you are avoiding yourself.
如果你读一本书，洗一副牌，或者照顾一只狗，你就是在逃避自己。

The abhorrence of loneliness is as natural as wanting to live at all.
对孤独的厌恶就像对生活的渴望一样自然。

If it were otherwise, men would never have bothered to make an alphabet, nor to have fashioned words out of what were only animal sounds, nor to have crossed continents, each man to see what the other looked like.
如果不是这样，人类就不会费心去创造字母表，也不会用动物的声音来创造单词，也不会跨越大陆，互相看看对方长什么样。

Being alone in an aeroplane, for even so short a time as a night and a day, irrevocably alone, with nothing to observe but your instruments and your own hands in semi-darkness.
独自一人在飞机上，即使是短暂的一天一夜，也无法挽回地孤独，除了你的仪器和半黑暗中的双手之外，没有什么可观察的。

Nothing to contemplate but the size of your small courage.
除了你小小的勇气有多大之外，没有什么值得考虑的。

Nothing to wonder about but the beliefs, the faces and hopes rooted in your mind.
除了根植于你脑海中的信念、面孔和希望之外，没有什么值得好奇的。

Such an experience can be as startling as the first awareness of stranger walking by your side at night.
这种经历就像晚上第一次意识到陌生人在你身边走过一样令人震惊。

You are the stranger." Beryl Markham died in Kenya this past August.
你是陌生人。”Beryl Markham 今年八月在肯尼亚去世。

She was eighty-three.  她八十三岁了。

Her ashes were scattered from a light aircraft over the hills at Inguro—her beloved childhood home.
她的骨灰被一架轻型飞机撒在她心爱的童年故乡因古罗的山上。

In Washington, I’m Susan Stanberg.
在华盛顿，我是苏珊·斯坦伯格。

'''
