
= Lesson 34
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../+ 000 eng选/美国高中历史教材 American History ： From Pre-Columbian to the New Millennium/myAdocCss.css

'''

Today the Surgeon General unveiled a new pamphlet about AIDS, calling for sex education in the schools in an effort to slow the epidemic.

[.my2]
今天，卫生局局长公布了一本关于艾滋病的新小册子，呼吁在学校开展性教育，以减缓艾滋病的流行。

NPR’s Richard Harris has details.

[.my2]
NPR 的理查德·哈里斯 (Richard Harris) 提供了详细信息。

"Surgeon General C.Everett Coop has been closely affiliated with the Right to Life Movement, and other organizations that oppose sex education in schools.

[.my2]
“卫生局局长 C.埃弗雷特·库普 (C.Everett Coop) 与生命权运动和其他反对学校性教育的组织有着密切的联系。

Until today, the Surgeon General had made no major statement about AIDS; so his recommendations are somewhat of a departure.

[.my2]
直到今天，卫生局局长还没有就艾滋病发表任何重要声明；所以他的建议有些偏离。

'AIDS education must start at the lowest grade possible as part of any health or hygiene program.

[.my2]
作为任何健康或卫生计划的一部分，艾滋病教育必须尽可能从最低年级开始。

And there is no doubt that we need sex education in schools and that it includes information on sexual practices that may put our children at risk for AIDS.' He said the Federal Government should allocate more money for AIDS education.

[.my2]
毫无疑问，我们需要在学校进行性教育，其中包括有关可能使我们的孩子面临艾滋病风险的性行为的信息。他说联邦政府应该拨出更多资金用于艾滋病教育。

Coop also recommended the use of condoms.

[.my2]
Coop还建议使用安全套。

He said that even religious groups that oppose contraception agree that condoms are needed in the fight against AIDS.

[.my2]
他说，即使是反对避孕的宗教团体也认为，在对抗艾滋病方面需要使用安全套。

Coop added that quarantines and mass blood screening campaigns are unnecessary.

[.my2]
库普补充说，隔离和大规模血液筛查活动是不必要的。

His guidelines are published in a pamphlet available through the mail from the Department of Health and Human Services.

[.my2]
他的指导方针发表在一本小册子中，可通过卫生与公众服务部邮寄获取。

I’m Richard Harris in Washington.

[.my2]
我是华盛顿的理查德·哈里斯。

Attorney General Edward Meese today announced a nationwide crackdown on the pornography industry.

[.my2]
总检察长爱德华·米斯今天宣布在全国范围内打击色情业。

Meese said he is committed to redoubling the federal effort to pursue with a vengeance and prosecute to the hilt the criminal elements trafficking in obscenity.

[.my2]
米斯表示，他致力于加倍联邦努力，严厉追查并起诉贩运淫秽物品的犯罪分子。

The Attorney General also announced the formation of an obscenity task force of federal prosecutors and the creation of an information center to assist state and local authorities.

[.my2]
总检察长还宣布成立联邦检察官组成的淫秽特别工作组，并建立一个信息中心来协助州和地方当局。

Meese said legislation will be introduced next year to outlaw dial-a-porn services that are found to be obscene and attack obscene cable television programming .

[.my2]
米斯表示，明年将出台立法，取缔被发现淫秽和攻击淫秽有线电视节目的色情拨号服务。

Economic output was 2.4% higher in the third quarter.

[.my2]
第三季度经济产出增长2.4%。

The modest increase in the gross national product was spurred primarily by a 42 billion-dollar surge in consumer spending.

[.my2]
国民生产总值的小幅增长主要是由消费支出激增 420 亿美元推动的。

More than half of that is the result of increased car sales.

[.my2]
其中一半以上是汽车销量增加的结果。

Analysts warned that consumers may have spent more than expected last quarter, which could lead to weak demand in the next two quarters.

[.my2]
分析师警告称，消费者上季度的支出可能超出预期，这可能导致未来两个季度的需求疲软。

Real GNP in adjusted 1982 dollars rose to more than 3.5 trillion dollars.

[.my2]
1982 年调整后的实际国民生产总值 (GNP) 升至 3.5 万亿美元以上。

Today the Surgeon General of the United States made his first major public statement about AIDS.

[.my2]
今天，美国卫生局局长首次就艾滋病发表了重要的公开声明。

He called for sex education in schools, and he suggested more direct ways to prevent AIDS.

[.my2]
他呼吁在学校开展性教育，并建议采取更直接的方法来预防艾滋病。

Many public health officials have been making these same recommendations for years.

[.my2]
多年来，许多公共卫生官员一直在提出这些相同的建议。

But as NPR’s Richard Harris reports, the statements are something of a departure for the Surgeon General.

[.my2]
但正如美国国家公共广播电台 (NPR) 的理查德·哈里斯 (Richard Harris) 报道的那样，这些声明对卫生局局长来说有些不同。

When Dr. Everett Coop was appointed Surgeon General in 1981, critics were worried that his ties to fundamentalist religion and his involvement in the Pro-Life movement would interfere with his medical advice to the nation.

[.my2]
当博士埃弗雷特·库普 (Everett Coop) 于 1981 年被任命为卫生局局长，批评者担心他与原教旨主义宗教的联系以及他对反堕胎运动的参与会干扰他向国家提供的医疗建议。

But today, Coop risked offending that constituency as he released a report on AIDS.

[.my2]
但今天，库普冒着冒犯选民的风险发布了一份关于艾滋病的报告。

"AIDS education must start at the lowest grade possible as part of any health or hygiene program.

[.my2]
“作为任何健康或卫生计划的一部分，艾滋病教育必须尽可能从最低年级开始。

And there is no doubt that we need sex education in schools and that is includes information on sexual practices that may put out children at risk for AIDS." Coop’s report is in the form of a pamphlet.

[.my2]
毫无疑问，我们需要在学校进行性教育，其中包括有关可能使儿童面临艾滋病风险的性行为的信息。”库普的报告以小册子的形式呈现。

And in that pamphlet, sex education in school isn’t the only controversial issue Coop confronted.

[.my2]
在那本小册子中，学校性教育并不是库普面临的唯一有争议的问题。

The new pamphlet also speaks openly about homosexuality and avoids value judgments about it.

[.my2]
新的小册子还公开谈论同性恋，并避免对此进行价值判断。

The pamphlet recommends the use of condoms to prevent the spread of the disease.

[.my2]
该小册子建议使用避孕套来防止疾病传播。

"When I’m talking about condoms, I am talking as a health officer about the protection of a person through the passage of a virus in sexual contact.

[.my2]
“当我谈论安全套时，我是作为一名卫生官员谈论通过性接触传播病毒来保护人的。

The fact that those condoms are also used in other circumstances to prevent procreation and to practice birth control makes it a difficult subject.

[.my2]
事实上，这些避孕套也用于其他情况以防止生育和实行节育，这使其成为一个困难的话题。

But in talking with even religious groups that are concerned about the use of condoms for the prevention of procreation, they agree with me that the threat of AIDS to the health of this nation is sufficiently great so that we can suggest that this is an acceptable method of protection health." Alluding to a controversial ballot proposition in California, Coop also spoke out against quarantines and mass blood screenings.

[.my2]
但在与那些担心使用安全套预防生育的宗教团体交谈时，他们同意我的观点，即艾滋病对这个国家健康的威胁足够大，因此我们可以建议这是一种可以接受的方法库普还提到了加州一项有争议的投票提议，反对隔离和大规模血液筛查。

The pamphlet also reassures the public that AIDS isn’t spread by insects or through causal contact.

[.my2]
该小册子还向公众保证艾滋病不会通过昆虫或因果接触传播。

It discourages the use of illegal intravenous drugs, but it does speak to drug abusers and advises them to avoid sharing dirty needles.

[.my2]
它不鼓励使用非法静脉注射药物，但它确实与吸毒者进行了交谈，并建议他们避免共用肮脏的针头。

Coop said that the federal government will need to spend more money on education about AIDS, and he said his office has no budget to launch and education campaign.

[.my2]
库普表示，联邦政府将需要在艾滋病教育上投入更多资金，他表示，他的办公室没有预算来开展教育活动。

But when he was asked whether he had the support of the Secretary of Education, Coop replied, "Let’s say I have his ear." Surgeon General Coop said he hoped that his pamphlet will launch a new campaign to combat AIDS.

[.my2]
但当他被问及是否得到教育部长的支持时，库普回答说：“假设我听过他的意见。”卫生局局长库普表示，他希望他的小册子能够发起一场新的抗击艾滋病运动。

Copies are available from the Department of Health and Human Services.

[.my2]
副本可从卫生与公共服务部获取。

This is Richard Harris in Washington.

[.my2]
我是华盛顿的理查德·哈里斯。

There have been over the ages many models of the mind.

[.my2]
多年来，存在着许多心灵模型。

The mind is an empty vessel, waiting to be filled; or the mind is a machine, breaking down sometimes.

[.my2]
头脑是一个空的容器，等待被填充；或者头脑是一台机器，有时会崩溃。

Nowadays, the mind is often described as being a computer, processing information.

[.my2]
如今，头脑经常被描述为一台处理信息的计算机。

Writer and social theorist Theodore Rozak disputes that model in his book The Cult of Information .

[.my2]
作家兼社会理论家西奥多·罗扎克在他的著作《信息崇拜》中对这一模型提出了质疑。

He says that the word is over-used, and the mind works more by juggling ideas than sifting through information.

[.my2]
他说这个词被过度使用，大脑更多地通过思考想法而不是筛选信息来工作。

In fact, says Rozak, some of the most important ideas have no information at all. "The example I use most prominently in the book is one that should be of …​

[.my2]
事实上，罗扎克说，一些最重要的想法根本没有任何信息。 “我在书中最突出使用的例子应该是……​

familiar enough to all Americans: 'All men are created equal.' Very powerful idea, has absolutely no connection with information.

[.my2]
所有美国人都熟悉这句话：“人人生而平等。”非常强大的想法，与信息完全无关。

The people who developed that idea and used it for revolutionary purposes were not drawing upon some body of research, some facts and figures about the whole human race.

[.my2]
提出这个想法并将其用于革命目的的人们并没有借鉴一些关于整个人类的研究、事实和数据。

That’s not what that idea is based upon.

[.my2]
这不是这个想法的基础。

It’s based upon experience and upon moral vision.

[.my2]
它基于经验和道德愿景。

And there are so many ideas like that, and I try to remind people, in this critique, that most of what’s going through their mind when they’re thinking most of the time, the run of ideas that they’ve learned from the cradle on up, many of which are matters of wisdom, of judgment, of insight, of intuition that have nothing to do with facts and figures or with information." "You write on page 213, you say, 'What I am suggesting is that in little things and big, the mind works more by way of Gestalt than by algorithmic processes.

[.my2]
类似的想法有很多，我试图在这篇评论中提醒人们，当他们大部分时间思考时，他们脑子里想到的大部分内容是他们从摇篮中学到的一系列想法其中许多是智慧、判断、洞察力、直觉的问题，与事实、数字或信息无关。”“你在第 213 页上写道，‘我的建议是在小事情和大事情上，大脑更多地通过格式塔而不是算法过程来工作。

That is because our life as a whole is made up of the hierarchy of projects, some trivial and repetitive, some special and spectacular.

[.my2]
这是因为我们的生活作为一个整体是由一系列项目组成的，有些是琐碎和重复的，有些是特殊和壮观的。

Pondering choices, making projects: these are the mind’s first order of business.

[.my2]
思考选择、制定计划：这些是大脑的首要任务。

This is so obvious, so basic that perhaps we are only prompted to reflect upon it when a different idea about thinking is presented, such as that thought is connecting data points in formal sequences." "What I’m trying to defend is the idea that thinking takes place on many levels.

[.my2]
这是如此明显、如此基本，以至于也许只有当提出关于思维的不同想法时，我们才会被提示反思它，例如该想法正在以正式序列连接数据点。”“我试图捍卫的是这个想法这种思考发生在很多层面上。

And the lowest level of all is data processing or information processing.

[.my2]
其中最低级别是数据处理或信息处理。

And it worries me if we try to sell people on the idea, and especially kids in the classroom that what they are doing when they are thinking is essentially something that should be modeled upon what a computer does.

[.my2]
如果我们试图向人们推销这个想法，尤其是课堂上的孩子们，他们在思考时所做的事情本质上应该模仿计算机的行为，这会让我感到担忧。

Well, I think that’s a disaster because it is lowering the capacities of the human mind to the lowest levels of thinking rather than acquainting kids gracefully and critically with all the higher levels of thinking that we normally go through in the course of every day of our life." "All right.

[.my2]
嗯，我认为这是一场灾难，因为它将人类思维的能力降低到最低的思维水平，而不是让孩子们优雅地、批判性地熟悉我们每天都会经历的所有更高水平的思维。生活。” “好吧。

There are things that are subjective.

[.my2]
有些事情是主观的。

There are things like creativity and intuition.

[.my2]
有创造力和直觉之类的东西。

But suppose that our experience of those things that is what we experience on the subjective level; on another level, the level that scientists study, these things are in fact productions and outcomes of conscious computational processes." "As a hypothesis, it’s perfectly respectable.

[.my2]
但假设我们对这些事物的体验是我们在主观层面上所体验到的；在另一个层面上，即科学家研究的层面上，这些东西实际上是有意识的计算过程的产物和结果。”“作为一个假设，它是完全值得尊敬的。

The problem is that people working in the field of artificial intelligence have found themselves, willingly or not, linked to a piece of machinery, a computer which they use as their model.

[.my2]
问题是，在人工智能领域工作的人们发现自己，无论是否愿意，都与一台机器、一台他们用作模型的计算机联系在一起。

I think this has had a very corrupting influence upon people working in the academies, in the field of artificial intelligence.

[.my2]
我认为这对人工智能领域的学院工作人员产生了非常腐败的影响。

It links them with a massive vested economic interest in our society which is out to sell computers for every purpose you can think of, from string recipes in your kitchen at home to running the Star Wars anti-ballistic missile defensive system.

[.my2]
它将它们与我们社会中巨大的既得经济利益联系起来，我们的社会出售计算机，用于你能想到的各种用途，从家里厨房里的字符串食谱到运行星球大战反弹道导弹防御系统。

"And yet, if you muck about with people who are doing artificial intelligence, some of the discussions are the most fascinating discussions I’ve ever had in my life." "The people in artificial intelligence have been making promises of the highest level for a very long period of time and always telling us that the great breakthrough in their field is going to happen within the next few years, three years, five years, something of that sort.

[.my2]
“然而，如果你仔细观察从事人工智能研究的人，你会发现其中一些讨论是我一生中经历过的最有趣的讨论。” “很长一段时间以来，人工智能领域的人们一直在做出最高水平的承诺，并总是告诉我们，他们的领域的巨大突破将在未来几年、三年、五年之内发生。那种。

You know, my question to the people in that field is a very simple one, you know.

[.my2]
你知道，我向该领域的人们提出的问题非常简单。

Deliver the goods, show us that you can do it.

[.my2]
交付货物，向我们展示您可以做到。

And my suspicion is that it can’t be done, because they’re using the wrong model of the human mind.

[.my2]
我怀疑这是不可能做到的，因为他们使用了错误的人类思维模型。

Well, we could go on disputing that academically for a very long period of time.

[.my2]
好吧，我们可以在学术上继续争论很长一段时间。

The fact is they’re already involved in selling that idea to the public as a form of machinery out there in the world." Theodore Rozak is author of The Cult of Information : The Folklore of Computers and the True Art of Thinking .

[.my2]
事实上，他们已经将这一想法作为一种机器形式向世界各地的公众推销。”西奥多·罗扎克 (Theodore Rozak) 是《信息崇拜：计算机民间传说和思考的真正艺术》一书的作者。

'''
