
= Lesson 28
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../+ 000 eng选/美国高中历史教材 American History ： From Pre-Columbian to the New Millennium/myAdocCss.css

'''


President Reagan addresses the nation in about three hours to explain what happened during his meetings this weekend with Soviet leader Mikhail Gorbachev.

[.my2]
里根总统在大约三个小时内向全国发表讲话，解释他本周末与苏联领导人米哈伊尔·戈尔巴乔夫会面时发生的情况。

The meetings did not produce any arms control agreements, nor did they produce a date for another summit between the two leaders.

[.my2]
会议没有达成任何军控协议，也没有确定两国领导人再次举行峰会的日期。

America’s NATO allies were disappointed at the lack of an agreement, especially the failure to rid Europe of medium-range US and Soviet missiles.

[.my2]
美国的北约盟国对未能达成协议感到失望，尤其是未能让欧洲摆脱美国和苏联的中程导弹。

But they urged the two Superpowers to keep talking.

[.my2]
但他们敦促两个超级大国继续对话。

And British Foreign Office Minister Timothy Renton said he was surprised that the two leaders had made as much progress as they did, and said he didn’t agree that the meetings had ended in failure.

[.my2]
英国外交部长蒂莫西·伦顿表示，他对两位领导人取得如此大的进展感到惊讶，并表示他不同意会议以失败告终。

"I would regard what has happened in Iceland as by no manner of means the end of the play, but rather as one act in this extremely important, in this extremely important series of discussions.

[.my2]
“我认为冰岛发生的事情绝不是戏剧的结束，而是这一极其重要的一系列讨论中的一个举动。

There is now an interval between the acts.

[.my2]
现在，行为之间有一个间隔。

We hope that it will be a short interval and that the parties involved will resume and take up the next act very quickly." The next act will likely be in Geneva where Renton said he presumes that the material introduced in Iceland will be worked on and developed.

[.my2]
我们希望这将是一个短暂的间隔，相关各方将很快恢复并开始下一行动。”下一行动可能会在日内瓦举行，伦顿说，他认为冰岛引入的材料将得到处理，并且发达。

Some seventy thousand government workers in San Salvador returned to their jobs today just three days after an earthquake hit the city.

[.my2]
圣萨尔瓦多大约七万名政府工作人员今天在地震袭击该市三天后返回工作岗位。

El Salvador’s President Jose Napoleon Duarte said nearly nine hundred people were killed in the quake and more than two hundred thousand left homeless.

[.my2]
萨尔瓦多总统何塞·拿破仑·杜阿尔特表示，近九百人在地震中丧生，逾二十万人无家可归。

Duarte ordered civil servants back to work, although he said almost all public buildings suffered some kind of damage.

[.my2]
杜阿尔特命令公务员重返工作岗位，尽管他表示几乎所有公共建筑都遭受了某种程度的损坏。

Duarte estimates the earthquake caused two billion dollars worth of damage.

[.my2]
杜阿尔特估计地震造成了价值 20 亿美元的损失。

Damage is expected to total into the tens of millions of dollars after several days of flooding in south central Alaska.

[.my2]
阿拉斯加中南部发生几天的洪水后，预计损失总额将达到数千万美元。

But it’s believed no one has been hurt.

[.my2]
但据信没有人受伤。

Tim Wolston, of member station KSKA in Anchorage reports.

[.my2]
安克雷奇 KSKA 会员站蒂姆·沃尔斯顿 (Tim Wolston) 报道。

"As many as fifteen homes have been destroyed and hundreds more damaged in the town of Seward, southeast of Anchorage.

[.my2]
“在安克雷奇东南部的苏厄德镇，多达 15 所房屋被毁，数百所房屋受损。

The main road leading into Seward has been washed away, cutting off the town from outside.

[.my2]
通往苏厄德的主要道路已被冲毁，切断了该镇与外界的联系。

Mayor Harry Giesler says hundreds have been evacuated; others prefer to wait it out.

[.my2]
市长哈里·吉斯勒表示，数百人已被疏散；其他人则宁愿等待。

'You know, Alaskans are a very hearty bunch, and especially people that have things like dog teams and animals.

[.my2]
“你知道，阿拉斯加人是一群非常热情的人，尤其是那些拥有狗队和动物之类的人。

They are very, very reluctant to leave their home as long as it’s even there.' Rain is forecast to continue for at least another day in Seward.

[.my2]
只要家还在，他们就非常非常不愿意离开。”苏厄德预计降雨至少还会持续一天。

Meanwhile, north of Anchorage, two bridges have been washed away, and the Alaska Railroad, a major form of transportation between Anchorage and Fairbanks has been cut off, making it very difficult for residents in interior Alaska to get to Five.

[.my2]
与此同时，安克雷奇以北的两座桥梁被冲毁，安克雷奇和费尔班克斯之间的主要交通阿拉斯加铁路也被切断，阿拉斯加内陆的居民很难到达五号公路。

The governor has issued disaster declarations to free up state fund for emergency relief.

[.my2]
州长已发布灾难声明，以腾出国家资金用于紧急救援。

The state is hoping for federal assistance as well.

[.my2]
该州也希望得到联邦援助。

For National Public Radio, this is Tim Wolston in Anchorage, Alaska." Today was a day for sorting out the summit in Iceland.

[.my2]
我是国家公共广播电台的蒂姆·沃尔斯顿，阿拉斯加安克雷奇。”今天是安排冰岛峰会的日子。

How did it happen that the two most powerful men of earth stepped to the threshold of a dramatic arms control accord and then stepped back? The talks foundered on the President’s Strategic Defense Initiative, or SDI.

[.my2]
地球上最有权势的两个人是如何一步步迈出戏剧性军控协议的门槛，然后又退缩的呢？会谈因总统战略防御计划（SDI）而失败。

"While both sides seek reduction in the number of nuclear missiles and war heads threatening the world, the Soviet Union insisted that we sign an agreement that would deny to me and to future presidents for ten years the right to develop, test, and deploy a defense against nuclear missiles for the people of the free world.

[.my2]
“虽然双方都寻求减少威胁世界的核导弹和核弹头的数量，但苏联坚持要求我们签署一项协议，该协议将在十年内剥夺我和未来总统开发、测试和部署核导弹的权利。为自由世界人民防御核导弹。

This we could not and will not do." "The President insisted, until the end, on retaining for the United States the right to test, to have experiments and to test things relating to SDI not only in the laboratories but also out of laboratories, including in space.

[.my2]
我们不能也不会这样做。”“总统坚持直到最后，保留美国进行测试、进行实验以及测试与 SDI 相关的事物的权利，不仅在实验室，而且在实验室外，包括在太空中。

So who was going to accept that? It would have taken a madman to accept that." The translated remarks yesterday by Soviet leader Mikhail Gorbachev and remarks by President Reagan.

[.my2]
那么谁会接受呢？只有疯子才会接受这一点。”昨天翻译的苏联领导人米哈伊尔·戈尔巴乔夫的讲话和里根总统的讲话。

We’ll hear defenders and critics of SDI later in tonight’s program, but first NPR’s Jim Angle, just back from Iceland, joins us to discuss what the two leaders almost achieved.

[.my2]
我们将在今晚的节目中听到 SDI 的捍卫者和批评者，但首先是 NPR 的吉姆·安格 (Jim Angle)，他刚从冰岛回来，加入我们讨论两位领导人几乎取得的成就。

"It is really amazing when you look at what the two Superpowers were able to do really in a period of twenty-four hours beginning with the experts meetings on Saturday night.

[.my2]
“当你看到两个超级大国在从周六晚上的专家会议开始的二十四小时内真正能够做到的事情时，真是令人惊奇。

In that twenty-four-hour-period, the two sides agreed to the most sweeping arms control proposals in the history of negotiations between the US and the Soviet Union.

[.my2]
在那二十四小时内，双方同意了美苏谈判史上最全面的军控建议。

They agreed to fifty percent cuts in all offensive weapons, all offensive strategic weapons over five years, then went beyond that later on, in a proposal from President Reagan, to eliminate all offensive ballistic missiles at the end of a ten-year period.

[.my2]
他们同意在五年内削减所有进攻性武器和所有进攻性战略武器百分之五十，然后在里根总统的提议中进一步削减，在十年期结束时消除所有进攻性弹道导弹。

They also agreed on INF, or intermediate-range nuclear weapons, which are now both in Europe and in Asia.

[.my2]
他们还就 INF（中程核武器）达成一致，这些武器目前已部署在欧洲和亚洲。

In the Soviet case, they agreed to eliminate all intermediate-range nuclear weapons in Europe and to reduce those in Asia by eighty-five percent to one hundred warheads, leaving the US with one hundred warheads as well.

[.my2]
就苏联而言，他们同意消除欧洲的所有中程核武器，并将亚洲的中程核武器减少百分之八十五至一百枚弹头，从而使美国也拥有一百枚弹头。

These were the kind of cuts in nuclear weapons that no one anticipated when they came to Iceland.

[.my2]
当来到冰岛时，没有人预料到会出现这样的核武器削减。

At first the US did not expect the negotiations to be that detailed, nor did anyone anticipate that two sides would actually start moving that quickly on something that they had been talking about for so long and been unable to do." "Tell us more about what the mood was like in Hofdi House during the negotiations." "The arms control experts met all night.

[.my2]
起初美国并没有预料到谈判会如此详细，也没有人预料到双方会如此迅速地就他们已经谈论了很长时间但无法做到的事情开始采取行动。”谈判期间霍夫迪宫的气氛如何。” “军控专家开会了一整晚。

They began at 8 p.m., quit at 6:30 the next morning.

[.my2]
他们晚上8点开始，第二天早上6点30分结束。

The two leaders were briefed by their respective groups somewhere around 9 o’clock that morning and began meeting again at 10.

[.my2]
当天上午 9 点左右，两位领导人听取了各自小组的通报，并于 10 点再次开始会面。

Then they started moving very quickly on the negotiations.

[.my2]
然后他们开始快速进行谈判。

The Soviets came back, for instance, and quickly resolved the medium-range missiles issue after some argument for quite a while.

[.my2]
比如，苏联人回来后，经过一番争论，很快就解决了中程导弹问题。

At this point, the negotiators, the advisors on the US side, some of them said that what was happening was really breathtaking because they were beginning to sense that these things were falling together, that there was this enormous movement between the two sides, movement in both their positions, that no one had anticipated when they arrived in Iceland.

[.my2]
此时，谈判代表、美方顾问，他们中的一些人说，所发生的事情真是令人震惊，因为他们开始感觉到这些事情正在一起落到一起，双方之间发生了巨大的运动，运动在他们到达冰岛时，没有人预料到他们的立场。

At that point, even President Reagan apparently asked some of his advisors whether or not they were moving too fast, whether or not they were going too far.

[.my2]
在这一点上，甚至连里根总统也明显问过他的一些顾问，他们的行动是否太快，是否走得太远。

And they would re-examine positions to make sure that things weren’t moving so quickly that they didn’t realize the implications of what they were doing.

[.my2]
他们会重新审视立场，以确保事情进展不会太快，以至于他们没有意识到自己所做的事情的影响。

In fact, one advisor said on one particular issue President Reagan said, 'No.

[.my2]
事实上，一位顾问说，在一个特定问题上，里根总统说：“不。

That is too far.

[.my2]
那太远了。

We will not go with that opposition.' At the very end, the advisors did not know what was happening; in fact at one point, when the first meeting broke up on Sunday—it was supposed to be the last meeting—they were out in the motorcade in the cars until they found out President Reagan had told the media that they were meeting again.

[.my2]
我们不会接受这种反对。到最后，顾问们都不知道发生了什么；事实上，当周日第一次会议结束时——这应该是最后一次会议——他们曾在汽车车队中出去，直到他们发现里根总统告诉媒体他们将再次开会。

They got out of cars, went back into Hofdi House.

[.my2]
他们下了车，回到霍夫迪宅邸。

At the very end, they did not know what was happening in the talks.

[.my2]
到最后，他们也不知道会谈发生了什么。

They got word that the two leaders were finished, that they were going out of the building.

[.my2]
他们得到消息说两位领导人已经结束了，他们要离开大楼。

They went down the stairs, looked over the stairwell, had no idea at this point what the result of the discussions had been.

[.my2]
他们下了楼梯，看了看楼梯间，此时还不知道讨论的结果是什么。

And then officials in the back asked one official in the front who could see the two leaders, 'What did their faces look like?' That official said, 'They’re not smiling.' And at that point, they knew that nothing had been agreed to and they had come so close to such a major agreement and they had failed." "Well, everything fell apart at the last meeting because of the Strategic Defensive Initiative.

[.my2]
然后后面的官员问前面一位可以看到两位领导人的官员，“他们的脸是什么样子？”那位官员说：“他们没有微笑。”那时，他们知道没有达成任何协议，他们如此接近达成如此重大的协议，但他们失败了。”“好吧，由于战略防御倡议，一切在上次会议上都崩溃了。

What were the points of disagreement?" "Well, there were basically two.

[.my2]
分歧点是什么？” “嗯，基本上有两个。

The Soviets wanted to restrict SDI work to the laboratory which the US says is a more restrictive interpretation of the ABM Treaty, the Anti-Ballistic Missiles Treaty, than anyone has ever proposed.

[.my2]
苏联希望将 SDI 工作限制在实验室内，美国称这是对《反弹道导弹条约》和《反弹道导弹条约》的更严格的解释，比任何人提出的建议都要严格。

Also that at the end of ten years, the Soviets wanted to begin discussions about deployment; the Americans wanted, insisted that they had the right to deploy at the end of ten years.

[.my2]
此外，在十年结束时，苏联人想开始讨论部署问题；美国人想要并坚持认为他们有权在十年结束时进行部署。

Throughout three drafts of language on this, the Soviets continued to insist on limiting SDI to the laboratory; the Americans hoped that they would eventually drop it, as they do sometimes in negotiations.

[.my2]
在这方面的三份草案中，苏联继续坚持将 SDI 限制在实验室范围内。美国人希望他们最终会放弃它，就像他们在谈判中有时所做的那样。

But they did not.

[.my2]
但他们没有。

The interesting thing here is that the Soviets had sweetened the deal to such an extent, had laid out this amazing agreement between the two, that the two powers had come so close to this major agreement that this was, they hoped, the bait that would get President Reagan to adopt what people in the United States have called 'the grand compromise', which was to trade SDI for deproductions in offensive missies.

[.my2]
有趣的是，苏联已经把协议甜化到了如此程度，在两国之间达成了这一令人惊奇的协议，以至于两个大国如此接近达成了这一重大协议，以至于他们希望这是诱饵让里根总统采取美国人所说的“大妥协”，即用战略防御计划换取进攻性导弹的减产。

At the end, the President rejected that.

[.my2]
最终，总统拒绝了这一说法。

And American official think that they have not lost that deal.

[.my2]
美国官员认为他们并没有失去这笔交易。

And the question now is what will happen next.

[.my2]
现在的问题是接下来会发生什么。

What will US and the US and the Soviet Union agree to or fail to agree to in the Geneva arms talks?" "OK. Thank you. NPR’s Jim Angle."

[.my2]
美国和美国、苏联在日内瓦军备谈判中会同意或不同意什么？” “好的。谢谢。NPR 的吉姆·安格尔。”

For the next ninety minutes we will be questioning the candidates for president of the United States, following a format designed and agreed to by representatives of the two candidates.

[.my2]
在接下来的九十分钟里，我们将按照两位候选人代表设计并同意的格式询问美国总统候选人。

The candidates are Vice-President George Bush, the Republican nominee, Governor Michael Dukakis, the Democratic nominee.

[.my2]
候选人包括共和党候选人、副总统乔治·布什和民主党候选人、州长迈克尔·杜卡基斯。

Our questions this evening will be about equally divided between foreign and domestic policy matters.

[.my2]
今晚我们的问题将同样分为外交和国内政策问题。

The first question by agreement between the two candidates goes to Vice-president Bush.

[.my2]
两位候选人一致同意的第一个问题是向副总统布什提出的。

It is a domestic question.

[.my2]
这是一个国内问题。

You have two minutes for an answer, Sir.

[.my2]
先生，您有两分钟的时间回答。

The polls say the number one domestic issue to majority of voters is drugs.

[.my2]
民意调查显示，对大多数选民来说，首要的国内问题是毒品。

What is there about these times that drives or draws so many Americans to use drugs? "I think we’ve seen a deterioration of values.

[.my2]
在这个时代，是什么驱使或吸引如此多的美国人吸毒？ “我认为我们已经看到了价值观的恶化。

I think for a while as a nation we condoned those, those things we should have condemned for a while, as I recall, it even seems to me that there was talk of legalizing, eh, or decriminalizing, eh, marijuana and other drugs.

[.my2]
我认为，作为一个国家，我们曾一度纵容这些事情，那些我们应该谴责一段时间的事情，我记得，在我看来，甚至有人在谈论大麻和其他毒品的合法化，呃，或非刑事化，呃。

And I think that’s all wrong.

[.my2]
我认为这都是错误的。

So we’ve seen a deterioration in values.

[.my2]
所以我们看到了价值观的恶化。

And one of the things that I think we should do about it, in terms of cause, is to instill values into the young people in our schools.

[.my2]
就事业而言，我认为我们应该做的事情之一就是向我们学校的年轻人灌输价值观。

We’ve got away.

[.my2]
我们已经离开了。

We’ve got this feeling that the value-free education was a thing.

[.my2]
我们有这样的感觉：价值中立的教育是一回事。

And I don’t believe it at all.

[.my2]
我根本不相信。

I do believe there are fundamental rights and wrongs as far as youth.

[.my2]
我确实相信，对于年轻人而言，存在基本的对错。

And of course, as far as the …​
当然，就……​

how we make it better.

[.my2]
我们如何让它变得更好。

Yes, we can do better on interdiction.

[.my2]
是的，我们可以在拦截方面做得更好。

But we’ve got to do a lot better on inter-…​
但我们必须在国际比赛中做得更好……​

and we’ve got to do a lot better on education.

[.my2]
我们必须在教育方面做得更好。

And we have to do …​
我们必须做……​

be tougher on those who commit crimes.

[.my2]
对犯罪的人要更加严厉。

We’ve got to get after the users more.

[.my2]
我们必须更多地关注用户。

We have to change this whole culture.

[.my2]
我们必须改变整个文化。

You know, I saw a movie, Crocodile Dundee .

[.my2]
你知道，我看过一部电影，《鳄鱼邓迪》。

And I saw the cocaine scene treated with humor, as though this was a humorous little incident.

[.my2]
我看到可卡因的场景被幽默地处理，仿佛这是一个幽默的小事件。

It’s bad.  这不好。

Everybody ought to be in this thing, entertainment industry, people involved in the school’s education.

[.my2]
每个人都应该从事娱乐行业，参与学校教育。

And it isn’t a Republican or a Democrat or liberal problem.

[.my2]
这不是共和党、民主党或自由派的问题。

But we have got to instill values in these young people.

[.my2]
但我们必须向这些年轻人灌输价值观。

And …​  还有……​

ah, I have put forward a …​
啊，我提出了一个……​

many point drug program the includes what I would do as president of the United States in Terms of doing better on interdiction, in terms of doing better in the neighborhoods.

[.my2]
多点毒品计划包括我作为美国总统将在拦截方面做得更好、在社区方面做得更好方面要做的事情。

But I think we are all in this together.

[.my2]
但我认为我们都在一起。

And my plead to the American people is values in the schools." Governor, you have one minute to respond.

[.my2]
我向美国人民呼吁的是学校的价值观。”州长，你有一分钟​​的时间来回应。

"I agree with Mr. Bush that values are important.



But it’s important that our leaders demonstrate those values form the top.

[.my2]
但重要的是，我们的领导者必须展示来自高层的这些价值观。

That means those of us who are elected to positions of political leadership have to reflect those values ourselves.

[.my2]
这意味着我们这些当选政治领导职位的人必须自己反映这些价值观。

Here we are with a government that’s been dealing with the drug running petty dictator.

[.my2]
我们面对的是一个一直在与贩毒小独裁者打交道的政府。

We’ve been dealing with him.

[.my2]
我们一直在和他打交道。

He’s been dealing drugs to our kids.

[.my2]
他一直在向我们的孩子贩卖毒品。

Governors like me and others have been trying to do with the consequences.

[.my2]
像我和其他人这样的州长一直在努力应对后果。

I remember being in a high school in my own state as we were organizing something we called 'the Governors' Alliance against Drugs', and a young sixteen-year-old girl coming up to me, desperate, addicted, dependent, saying, 'Governor, I need help,' We are providing that young woman with help.

[.my2]
我记得当时在我所在州的一所高中，当时我们正在组织一个名为“州长反毒品联盟”的活动，一个十六岁的年轻女孩走到我面前，绝望、上瘾、依赖，说：“州长，我需要帮助。”我们正在为那位年轻女士提供帮助。

But I want to be a President of the United States who makes sure that we never again do business with the drug running petty dictator, that we never again funnel aid to the 'contras' and the convicted drug dealers.

[.my2]
但我想成为一名美国总统，确保我们不再与贩毒的小独裁者做生意，我们不再向“反派”和被定罪的毒贩提供援助。

Values begin at the top, in the White House.

[.my2]
价值观始于白宫高层。

Those are the values I want to be …​ bring to Presidency and White House beginning January 1989."

Governor, a follow-up question.

[.my2]
州长，一个后续问题。

You have two minutes to answer it.

[.my2]
你有两分钟的时间来回答。

Are you suggesting, sir, that President Reagan is one of causes of the drug problem in this country? "I’m saying that those of us who are elected to the position of political leadership, Jim, have a special responsibility, not only to come up with programs and I have outlined and detailed a very important, very strong program of enforcement as well as drug education of prevention.

[.my2]
先生，您是在暗示里根总统是这个国家毒品问题的根源之一吗？ “我是说，我们这些当选政治领导职位的人，吉姆，负有特殊的责任，不仅要制定计划，而且我还概述并详细说明了一个非常重要、非常强有力的执行计划如预防毒品教育。

And Mr.  还有先生。

Bush is right.  布什是对的。

The two go hand in hand.

[.my2]
两者齐头并进。

But if our government itself is doing business itself with people who, we know, are engaged in drug profiteering an drug trafficking, if we don’t understand that that sends out a very, very bad message to our young people, and it’s a little difficult for me to understand just how we can reach out to that youngster that I talked about and young people like her all over the country and say to them, 'We want to help you." "Now, I’ve outlined in great detail a program for being tough on enforcement home and abroad, doubling the number of drug enforcement agents, having a hemisphere’s summit.

[.my2]
但是，如果我们的政府本身正在与那些我们知道从事毒品牟利和贩毒的人做生意，如果我们不明白这会向我们的年轻人发出一个非常非常糟糕的信息，这有点我很难理解我们如何才能接触到我谈到的那个年轻人以及全国各地像她这样的年轻人，并对他们说，‘我们想帮助你。’”现在，我已经详细概述了一项对国内外实施严厉执法的计划，将缉毒人员的数量增加一倍，并召开半球峰会。

Soon after the twentieth of January, we’ll bring out democratic neighbors and allies together here in this hemisphere and go to work together.

[.my2]
一月二十号过后不久，我们将在这个半球召集民主邻国和盟友，一起去工作。

We also have to take demands seriously.

[.my2]
我们也必须认真对待要求。

You know we have 5% of the world’s population in this country.

[.my2]
你知道我们国家有世界人口的 5%。

We’re consuming 50% of the world’s cocaine.

[.my2]
我们消耗了世界上 50% 的可卡因。

And in my state, I’m proud to say we’ve organized a drug education prevention program which the Federal drug enforcement administration says is a model of the country.

[.my2]
在我所在的州，我很自豪地说我们已经组织了一项毒品教育预防计划，联邦缉毒局称其为国家典范。

We are helping youngsters.

[.my2]
我们正在帮助年轻人。

We’re reaching out to them.

[.my2]
我们正在联系他们。

And we’re beginning drug education, prevention, beginning in the early elementary grades and every elementary school in …​
我们正在开始毒品教育和预防，从小学低年级和每所小学开始……​

eh …​  呃……​

in our …​  在我们的……​

eh …​  呃……​

our state.  我们的国家。

And that’s the kind of help we need in every elementary school in the United States of America.

[.my2]
这就是我们美国每所小学都需要的帮助。

And we’ve got to begin early in the first, second and third grade before our youngsters begin to experiment with these very, very dangerous substances.

[.my2]
在我们的孩子开始尝试这些非常非常危险的物质之前，我们必须从一年级、二年级和三年级开始。

I guess the question I would ask of Mr.

[.my2]
我想我会问先生的问题

Bush is, how we instill those values? How we create this environment for the drug-free schools that we want of this country? If he or representatives of the administration…​ah…​are either dealing with and involving people like Noriega in our foreign policy, or don’t pursue that connection in a way that makes it possible for us to cut it off and to be an example to our kids all over this country." A minute to …​
布什，我们如何灌输这些价值观？我们如何为这个国家创造我们想要的无毒品学校的环境？如果他或政府代表……啊……要么与像诺列加这样的人打交道并将其纳入我们的外交政策，要么不以一种使我们有可能切断这种联系并成为一个人的方式来寻求这种联系。为我们全国各地的孩子树立榜样。”一分钟……​

eh …​  呃……​

rebut, Mr.  反驳先生

Vice-President.  副总裁。

"On the other day my opponent was given a briefing by the CIA.

[.my2]
“有一天，我的对手收到了中央情报局的简报。

I asked for and received the same briefing.

[.my2]
我要求并得到了同样的简报。

I’m very careful in public life about dealing with classified information.

[.my2]
在公共生活中，我对处理机密信息非常谨慎。

And what I’m about to say is unclassified.

[.my2]
我要说的内容是非机密的。

Seven administrations are dealing with Mr.

[.my2]
七个政府正在与先生打交道。

Noriega.  诺列加。

It was the Reagan-Buch Administration that brought this man to justice.

[.my2]
正是里根-布赫政府将这个人绳之以法。

And as the governor of Massachusetts knows there was no evidence that governor …​
正如马萨诸塞州州长所知，没有证据表明州长……​

that …​  那……​

that eh …​  那个呃……​

Mr.  先生。

Noriega was involved in drugs, no hard evidence until we indicted him.

[.my2]
诺列加涉毒，在我们起诉他之前没有确凿的证据。

And so I think it’s about time we get this Noriega matter in perspective.

[.my2]
所以我认为现在是我们正确看待诺列加问题的时候了。

Panama is a friendly country.

[.my2]
巴拿马是一个友好的国家。

I went down there and talked to the President of Panama about cleaning up their mon…​
我去那里与巴拿马总统讨论了清理他们的日常......​

money laundering.  洗钱。

And Mr.  还有先生。

Noriega was there.  诺列加就在那里。

But there was no evidence at that time.

[.my2]
但当时没有任何证据。

And when the evidence was there, we indicted him and we want to bring him to justice and so call up for those pickets-up there that are trying to tear down seven different administrations."
当证据到位时，我们起诉了他，我们想将他绳之以法，因此呼吁那些试图推翻七个不同政府的纠察队。”

'''
