
= Lesson 32
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../+ 000 eng选/美国高中历史教材 American History ： From Pre-Columbian to the New Millennium/myAdocCss.css

'''


The United States declared a truce today in its diplomatic expulsion war with the Soviet Union.

[.my2]
美国今天宣布与苏联的外交驱逐战休战。

State Department spokesman Charles Redman said, "We hope this set of issues can now be put behind us." Redman did say that any restrictions placed on temporary American workers in Moscow would be matched by limits on Soviet workers here.

[.my2]
美国国务院发言人查尔斯·雷德曼表示：“我们希望现在可以把这一系列问题抛在脑后。”雷德曼确实表示，对莫斯科临时美国工人的任何限制都将与对这里的苏联工人的限制相匹配。

He condemned the latest Soviet expulsion order, but said it’s time the two governments moved on to arms control and other issues taken up by President Reagan and Soviet leader Gorbachev at their meetings in Iceland two weeks ago.

[.my2]
他谴责苏联最新的驱逐令，但表示两国政府现在应该转向军备控制以及里根总统和苏联领导人戈尔巴乔夫两周前在冰岛举行的会议上讨论的其他问题。

President Reagan left the White House today for a two-day campaign trip.

[.my2]
里根总统今天离开白宫开始为期两天的竞选之旅。

The President hopes to boost Republican Senate candidates and his first stop was in Wisconsin, where he appeared on behalf of freshman Senator Robert Castan.

[.my2]
总统希望提振共和党参议员候选人，他的第一站是威斯康星州，代表新参议员罗伯特·卡斯坦出庭。

Mark Levine of member station WUWM reports from Milwaukee.

[.my2]
WUWM 会员站的马克·莱文 (Mark Levine) 来自密尔沃基的报道。

"President Reagan came here to endorse Senator Castan who’s in a close re-election race against Democrat Edward Garvey, the former chief of the National Football League Players' Union.

[.my2]
“里根总统来这里是为了支持参议员卡斯坦，他正在与民主党人、国家橄榄球联盟球员工会前主席爱德华·加维进行一场势均力敌的连任竞选。

In his speech at a GOP rally, Mr.

[.my2]
在共和党集会上的演讲中，先生。

Reagan said his name will never be on the ballot again.

[.my2]
里根表示，他的名字将永远不会再出现在选票上。

'So if you want to vote for me, vote for Bob Castan, so that we can have a Republican Senate that will work with me instead of against me and be around after I’m gone.

[.my2]
“所以，如果你想投票给我，就投票给鲍勃·卡斯坦，这样我们就能拥有一个共和党参议院，它将与我合作而不是反对我，并在我离开后继续存在。”

But I’m not, I’m not just asking that for me.

[.my2]
但我不是，我不只是为我自己要求这个。

Do it for yourself.

[.my2]
为自己做吧。

Do it for Wisconsin.

[.my2]
为威斯康星州做这件事。

Do it for America.' Recent polls showed Senator Castan narrowly leading Garvey.

[.my2]
为美国做这件事。最近的民意调查显示参议员卡斯坦以微弱优势领先加维。

Republicans here believe the President’s appearance will help Castan win re-election on November 4th.

[.my2]
这里的共和党人相信总统的露面将有助于卡斯坦在 11 月 4 日赢得连任。

For National Public Radio, this is Mark Levine in Milwaukee." The lawyer representing Eugene Hasenfus prepared today to enter a plea to charges that could send the captured flier to prison for thirty years.

[.my2]
国家公共广播电台的联系人是密尔沃基的马克·莱文。”尤金·哈森福斯的代表律师今天准备对指控进行抗辩，这些指控可能会让被俘飞行员入狱三十年。

Hasenfus is accused of committing a terrorist act and violating Nicaraguan security by taking part in a contra supply mission.

[.my2]
哈森福斯被指控参与反补给任务，犯有恐怖行为并侵犯尼加拉瓜安全。

Former US Attorney-Griffen Bell is expected to arrive today in Managua to aid in Hasenfus defense.

[.my2]
前美国检察官格里芬·贝尔预计将于今天抵达马那瓜协助哈森福斯的辩护。

Hasenfus met for two hours today with his Nicaraguan attorney.

[.my2]
哈森福斯今天与他的尼加拉瓜律师会面了两个小时。

For the past few weeks, the United States and the Soviet Union have been expelling each other’s diplomats almost on a daily basis.

[.my2]
过去几周，美国和苏联几乎每天都在驱逐对方的外交官。

Today, the US called a truce.

[.my2]
今天，美国宣布休战。

NPR’s Jim Angle reports. The United States called a halt today to week-long retaliatory exchange with the Soviet Union, leaving both sides searching for ways to deal with new restrictions on their respective diplomatic mission.

[.my2]
NPR 的吉姆·安格尔报道。美国今天暂停了与苏联为期一周的报复性交锋，双方都在寻找方法来应对各自外交使团受到的新限制。

The tit-for-tat retaliations ended abruptly as the State Department announced that it would match some minor restrictions by the Soviets on the number of visas given for temporary personnel.

[.my2]
随着国务院宣布将配合苏联对临时人员签证数量的一些小限制，针锋相对的报复行动突然结束。

But the administration did not expel any more Soviet diplomats, even though the Soviets in their last retaliation yesterday ordered the expulsion of five more Americans.

[.my2]
但美国政府没有再驱逐任何苏联外交官，尽管苏联在昨天的最后一次报复中下令驱逐另外五名美国人。

State Department spokesman Charles Redman made clear that as far as the US is concerned, the matter is over.

[.my2]
美国国务院发言人查尔斯·雷德曼明确表示，就美国而言，事情已经结束了。

"This is our response.

[.my2]
“这是我们的回应。

We hope that this set of issues can now be put behind us." Redman emphasized the most positive aspects of the retaliations and then sought to shift the focus of US-Soviet relations to more productive matters.

[.my2]
我们希望现在可以把这一系列问题抛在脑后。”雷德曼强调了报复行动最积极的方面，然后试图将美苏关系的焦点转向更有成效的问题。

"There seems to be common ground in the mutual acknowledgement of parity and reciprocity as the foundation of our diplomatic relationship.

[.my2]
“双方都承认平等和互惠是我们外交关系的基础，这似乎有共同点。

We need now to get on with resolution of the larger issues affecting US-Soviet relations and build on the progress made in the discussions at Reykjavik." The common ground on reciprocity went a good bit further than the US hoped.

[.my2]
我们现在需要继续解决影响美苏关系的更大问题，并在雷克雅未克讨论取得的进展的基础上再接再厉。”互惠方面的共同点比美国希望的要进一步深入。

The administration, responding to an expulsion of five Americans last Sunday, ordered out an equal number of Soviet diplomats on Tuesday.

[.my2]
美国政府针对上周日驱逐五名美国人的事件作出回应，并于周二下令驱逐同等数量的苏联外交官。

And at the same time, the US said that it was permanently reducing the size of the staff at the Soviet Embassy and Consulate in the US to equal the number of Americans now stationed in the Soviet Union.

[.my2]
与此同时，美国表示将永久削减苏联驻美使领馆的人员规模，使其与目前驻苏联的美国人人数相同。

And the administration expelled fifty Soviet diplomats to get the Soviet Union down to that level immediately.

[.my2]
政府驱逐了五十名苏联外交官，使苏联立即降到了这个水平。

American officials said all fifty-five Soviets expelled this week were spies, the same allegation the US made against the twenty-five Soviets it expelled from their UN mission in September.

[.my2]
美国官员表示，本周被驱逐的所有 55 名苏联人都是间谍，这与美国 9 月份从联合国代表团中驱逐的 25 名苏联人提出的指控相同。

The Soviets retaliated yesterday in a way that left the US no corresponding action to take.

[.my2]
苏联昨天进行了报复，美国没有采取相应行动。

They withdrew all the Soviet citizens working for the US Embassy in Moscow and the Consulate in Leningrad, a total, the Soviets said, of two hundred sixty.

[.my2]
他们撤回了在美国驻莫斯科大使馆和驻列宁格勒领事馆工作的所有苏联公民，苏联方面称，总数为两百六十人。

Those people are the maids, cooks, drivers, mechanics and translators for the Embassy staff in the Soviet Union.

[.my2]
这些人是驻苏联大使馆工作人员的女佣、厨师、司机、机械师和翻译。

The Soviets, by contrast, rely almost exclusively on Soviet citizens assigned to the US for the same kind of work.

[.my2]
相比之下，苏联几乎完全依赖派往美国从事同类工作的苏联公民。

State Department spokesman Redman acknowledged the Soviet action will make things more difficult for our diplomats in the Soviet Union.

[.my2]
美国国务院发言人雷德曼承认，苏联的行动将使我们驻苏联外交官的处境变得更加困难。

"We expect that there will have to be some fairly substantial changes in our staffing patterns, as we need personnel to take up the tasks previously performed by others.

[.my2]
“我们预计我们的人员配置模式将发生一些相当大的变化，因为我们需要人员来承担以前由其他人执行的任务。

And there will undoubtedly be some short-term adjustment problems.

[.my2]
而短期的调整无疑也会出现一些问题。

And over the long term we will have a different look in Moscow." The administration wanted to force a different look on the Soviet presence in the United States as well.

[.my2]
从长远来看，我们将对莫斯科有不同的看法。”美国政府也希望迫使人们对苏联在美国的存在也有不同的看法。

Officials yesterday said the US expulsions had decapitated Soviet intelligence in the United States.

[.my2]
官员们昨天表示，美国的驱逐行动已经削弱了苏联在美国的情报机构。

Said one official, "It was a crushing blow that eliminated the top leadership of Soviet intelligence here and means the end of an era for Soviet intelligence in the United States," Officials said reduction in Soviet diplomatic staff would also reduce the overall Soviet intelligence presence in the United States.

[.my2]
一位官员表示，“这是一次毁灭性的打击，消除了苏联情报机构的最高领导层，也意味着苏联情报机构在美国的时代结束了。”官员们表示，苏联外交人员的减少也将减少苏联情报机构的整体存在在美国。

And they said it would create dissension between the Soviet diplomatic ranks and the intelligence services as they compete for a shrinking number of positions in the US.

[.my2]
他们表示，这将在苏联外交队伍和情报部门之间争夺越来越少的美国职位时造成分歧。

But the Soviets showed yesterday they could force some equally difficult choices on the Americans.

[.my2]
但苏联人昨天表明，他们可以迫使美国人做出一些同样困难的选择。

The administration must now decide, for instance, whether it must displace some diplomats or intelligence officers in order to make room for maids and mechanics, jobs that were previously held by Soviets.

[.my2]
例如，政府现在必须决定是否必须取代一些外交官或情报官员，以便为女佣和机械师腾出空间，这些工作以前由苏联人担任。

Now they must be done by Americans who count toward the overall total of official Americans permitted to serve in the USSR.

[.my2]
现在，这些工作必须由美国人来完成，他们计入允许在苏联服役的官方美国人总数。

Charles Redman conceded that will have some impact on the US ability to keep track of things there.

[.my2]
查尔斯·雷德曼承认，这将对美国跟踪那里情况的能力产生一些影响。

"Without question, there’s going to be some change in our ability to monitor what happens in the Soviet Union.

[.my2]
“毫无疑问，我们监视苏联发生的事情的能力将会发生一些变化。

This is something that we foresaw as we went into this.

[.my2]
这是我们在研究这个问题时预见到的事情。

As a consequence, we’re prepared to cope with it." Other officials said yesterday the US Embassy in Moscow is now larger than it has ever been.

[.my2]
因此，我们已做好应对的准备。”其他官员昨天表示，美国驻莫斯科大使馆现在比以往任何时候都大。

"Historically," said one official, "the US staff in the Soviet Union has been somewhere between one hundred seventy-five and two hundred, but for a number of reasons," the official said, "it had grown recently to two hundred fifty-one." Sources denied that it was in anticipation of this week’s events, but suggested it will make the adjustment a little easier.

[.my2]
一位官员说：“从历史上看，美国在苏联的工作人员数量一直在一百七十五到两百人之间，但由于多种原因，”该官员说，“最近已增加到两百五十人。” -一。”消息人士否认这是对本周事件的预期，但暗示这将使调整变得更容易一些。

So as the dust settles, the Soviets are left with a substantially smaller presence in the United States, which administration officials say will make it a little easier to clamp down on Soviet intelligence activities.

[.my2]
因此，随着尘埃落定，苏联在美国的存在大大减少，政府官员表示，这将使压制苏联情报活动变得更容易一些。

But the administration, which has placed great value on being firm, if not tough, with the Soviets, found this week that is a two-way street.

[.my2]
但美国政府非常重视对苏联采取强硬态度（即使不是强硬态度），但本周却发现这是一条双向路。

US officials concerned with monitoring and combating Soviet intelligence activities think the trade-off of more difficult conditions for American diplomats in exchange for a more hostile environment for Soviet intelligence here is worth it.

[.my2]
关注监视和打击苏联情报活动的美国官员认为，为美国外交官提供更困难的条件来换取苏联情报机构更敌对的环境是值得的。

But it remains to be seen if the Soviet retaliation will have an equal impact on the United States.

[.my2]
但苏联的报复是否会对美国产生同样的影响还有待观察。

I’m Jim Angle in Washington.

[.my2]
我是华盛顿的吉姆·安格。

Who am I really? What is reality for that matter? In fact, what is matter, or time, or cause and effect? These are old questions asked and answered again and again by philosophers and scientists.

[.my2]
我究竟是谁？就此事而言，现实是什么？事实上，什么是物质、时间、因果？这些都是哲学家和科学家一次又一次提出和回答的老问题。

They were still asking them over the weekend at a Nature of Reality Conference at Colorado State University.

[.my2]
周末在科罗拉多州立大学举行的现实本质会议上，他们仍在询问这些问题。

They talked about quantum theory, relativity and the new physics, discoveries in atomic science that cast new light on old questions or maybe just add to the list.

[.my2]
他们谈论了量子理论、相对论和新物理学、原子科学的发现，这些发现为旧问题带来了新的曙光，或者可能只是添加了一些内容。

One speaker was Fritchoff Kapra.

[.my2]
弗里奇霍夫·卡普拉（Fritchoff Kapra）就是其中一位发言者。

A few year ago he wrote The Tao of Physics , a book which linked the findings of modern science with ancient eastern philosophies.

[.my2]
几年前，他写了《物理学之道》，这本书将现代科学的发现与古代东方哲学联系起来。

It set off a wave of interest in how our most common notions about reality break down in the world of the very small.

[.my2]
它引发了人们对我们关于现实的最常见观念如何在微小世界中崩溃的兴趣。

"Let’s talk about an electron which is sort of, you know, the smallest entity we know.

[.my2]
“让我们来谈谈电子，它是我们所知道的最小实体。

And we have the tendency of picturing it somewhat like a grain of sand.

[.my2]
我们倾向于把它想象成一粒沙子。

Well, this is very wrong.

[.my2]
嗯，这是非常错误的。

It’s not an isolated entity.

[.my2]
它不是一个孤立的实体。

It’s not a grain of sand.

[.my2]
它不是一粒沙子。

It cannot be said to exist even in a certain place at a definite time.

[.my2]
即使在某个时间、某个地点，也不能说它存在。

It’s a sort of, you know, very nebulous entity seemingly which requires a whole new set of concepts and ideas to be described.

[.my2]
你知道，它是一种看起来非常模糊的实体，需要一套全新的概念和想法来描述。

What emerged in the last fifteen years is that the new world view that came out of modern physics is in fact not limited to physics, but is emerging now also in the other sciences, in biology, in psychology, in the social sciences.

[.my2]
过去十五年出现的情况是，现代物理学产生的新世界观实际上不仅限于物理学，现在也在其他科学、生物学、心理学、社会科学中出现。

And it is best, it is best described by calling it a systems view." "Could you give us an example?" "Let’s talk about medicine, for instance.

[.my2]
最好的，最好的描述方式是称之为系统视图。” “你能给我们举个例子吗？” “让我们谈谈医学，例如。

Conventional Western medicine is based on Descartes' view of the human body as a machine, in fact, as a clock-work.

[.my2]
传统的西医基于笛卡尔的观点，认为人体是一台机器，实际上是一个发条机构。

And when a clock doesn’t function, you look for the single part that has broken down and you, by an act of intervention, you replace that part.

[.my2]
当时钟无法工作时，您会寻找损坏的单个部件，然后通过干预行为更换该部件。

This is what doctors do now, in terms of physical intervention through surgery or chemical intervention through drugs.

[.my2]
这就是医生现在所做的，通过手术进行物理干预或通过药物进行化学干预。

The new kind of view would be seeing the human organism as an integrated whole which has physical aspects, biological aspects, but also psychological aspects and which is imbedded in a natural environment and in a social and emotional environment." "Now going back to physics for one minute, what do we see on the atomic level that gets us to that same place?" "Nothing.

[.my2]
新的观点将把人类有机体视为一个完整的整体，它不仅具有物理方面、生物方面，而且还具有心理方面，并且植根于自然环境、社会和情感环境中。”“现在回到物理学。一分钟，我们在原子层面上看到了什么，让我们到达了同一个地方？” “什么也没有。

Physics cannot be used as the basis for the new world view.

[.my2]
物理学不能作为新世界观的基础。

You cannot understand a living organism in terms of physics alone.

[.my2]
你无法仅从物理学的角度来理解生命有机体。

Of course, it does satisfy the laws of physics, because it is also, you know, made of physical constituents like molecules and atoms.

[.my2]
当然，它确实满足物理定律，因为它也是由分子和原子等物理成分组成的。

But in order to understand life, and therefore in order to understand health, you have to have a broader framework." "Could you give just a couple of examples?" "The shift from the part to the whole was maybe the central development in quantum theory when physicists recognized that subatomic particles cannot be seen as isolated entities, but rather have to be seen as interconnections in a web of relationships.

[.my2]
但为了理解生命，进而理解健康，你必须有一个更广泛的框架。” “你能举几个例子吗？” “从部分到整体的转变也许是当物理学家认识到亚原子粒子不能被视为孤立的实体，而必须被视为关系网络中的互连时，量子理论就出现了。

The other one, a very dramatic development, was Einstein’s discovery that mass is nothing but a form of energy.

[.my2]
另一个非常引人注目的发展是爱因斯坦发现质量只不过是能量的一种形式。

Mass does not measure a certain material substance but measures activity or process, and therefore a very dramatic shift from thinking in terms of substance and structure to thinking in terms of process." "It seems to me that there are hundreds, thousand, tens of thousands of people on college campuses, going to conferences who are utterly fascinated by implications of some connection between the way we view the cosmos, between philosophy, between religion and physics.

[.my2]
质量并不衡量某种物质实体，而是衡量活动或过程，因此这是从物质和结构的思维到过程的思维的一个非常戏剧性的转变。”大学校园里成千上万的人参加会议，他们对我们看待宇宙的方式、哲学之间、宗教与物理学之间的某种联系的含义非常着迷。

But most of these people and most of their ideas in the mainstream society are considered somewhat on the fringe.

[.my2]
但这些人中的大多数以及他们的大多数想法在主流社会中都被认为有些边缘化。

Why is that?" "Einstein was very much considered on the fringe.

[.my2]
这是为什么呢？” “人们普遍认为爱因斯坦处于边缘。

Beethoven was considered on the fringe.

[.my2]
贝多芬被认为处于边缘。

Mozart was considered on the fringe.

[.my2]
莫扎特被认为处于边缘。

This always happens with new creative ideas, and the world view that emerged from modern physics is really something radically new and is something very disturbing." "What is the thought that is most uncomfortable?" "Even more disturbing to physicists than to people outside of science is the fact that there are no well defined isolated objects, that we are all imbedded in a network of relationships where what you call an object depends very much how you look at it.

[.my2]
这种情况总是发生在新的创造性想法中，而从现代物理学中产生的世界观确实是一种全新的东西，也是非常令人不安的。”“最不舒服的想法是什么？”“对物理学家来说比对外界的人更令人不安。”科学的一个事实是，不存在明确定义的孤立对象，我们都嵌入在一个关系网络中，在这个网络中，你所谓的对象很大程度上取决于你如何看待它。

Furthermore, that this network is not static, but is in continual process.

[.my2]
此外，该网络不是静态的，而是处于持续过程中。

So it is the relativity and the impermanence of existence.

[.my2]
所以这就是存在的相对性和无常性。

Now this is very disturbing, because it leads you to recognize the impermanence of your own existence, the illusion that we are a well defined, you know, isolated self that we have a well defined, isolated ego.

[.my2]
现在这是非常令人不安的，因为它让你认识到你自己的存在是无常的，我们是一个明确定义的、孤立的自我的幻觉，我们有一个明确定义的、孤立的自我。

And this is very disturbing to many people.

[.my2]
这让很多人感到非常不安。

It is not disturbing to people typically in spiritual traditions.

[.my2]
它不会对通常具有精神传统的人造成干扰。

To Buddhists, for instance, this is the very foundation of Buddhist thinking and Buddhist living.

[.my2]
例如，对于佛教徒来说，这是佛教思想和佛教生活的基础。

But to most Westerners, it is extremely disturbing." Physicist Firtchoff Kapra heads the Elmwood Institute in Berkeley, California.

[.my2]
但对于大多数西方人来说，这极其令人不安。”物理学家菲尔乔夫·卡普拉 (Firtchoff Kapra) 是加利福尼亚州伯克利市埃尔姆伍德研究所的负责人。

'''
