
= 09 INTERNATIONAL PUBLIC LAW: AN AMERICAN LAW PERSPECTIVE
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''


== 释义


9.INTERNATIONAL PUBLIC LAW: AN AMERICAN LAW PERSPECTIVE

The previous chapter discussed international business law, but what is international public law (IPL)? The traditional definition 定义 of IPL typically covered only states, which are broadly defined 界定；定义 as having a defined territory 领土, fixed population 人口, and a government. In contrast 相比之下, the post-1945 modern definition of IPL covers not only states, but also includes multinational corporations 跨国公司 (MNCs), individuals 个人, intergovernmental organizations 政府间组织 (IGOs), and nongovernmental organizations 非政府组织 (NGOs). The big picture 总体情况；大局 is that modern international law covers many more actors 主体；参与者 than traditional international law. The rationale 根本原因；理论依据 is that, in the post-1945 era 时代, actors like MNCs, individuals, IGOs, and NGOs possessed 拥有；具备 relatively 相对地 more potential 潜力；可能性 to both benefit 获益 as well as harm 损害 the global arena 领域；舞台.

[.my2]
上一章探讨了国际商法，那么什么是国际公法（IPL）呢？国际公法的传统定义通常仅适用于国家，而国家的广义界定标准是拥有确定的领土、固定的人口以及政府。相比之下，1945年之后的现代国际公法定义，不仅涵盖国家，还纳入了跨国公司（MNCs）、个人、政府间组织（IGOs）以及非政府组织（NGOs）。总体而言，现代国际法所涵盖的主体要远多于传统国际法。其根本原因在于，在1945年后的时代背景下，跨国公司、个人、政府间组织和非政府组织这类主体，拥有了相对更强的能力，既能够为全球领域带来益处，也可能对其造成损害。

---

=== The Modern View of International Public Law

The year 1945, and the end of World War II, marked 标志着 the beginning of modern international law. Before 1945, international law was traditionally viewed 看待；视为 as applying only to states.

[.my2]
1945年，也就是第二次世界大战结束的那一年，标志着现代国际法的开端。在1945年之前，国际法在传统意义上被认为仅适用于国家。

A state is defined as an entity 实体 that has the following:

[.my2]
一个国家的定义是满足以下条件的实体：

- A fixed population
- A defined territory
- A government that is capable of 能够 (a) governing 治理；管辖 its fixed population and defined territory and (b) entering into 缔结；建立 international relations 国际关系

[.my2]
- 固定的人口
- 确定的领土
- 一个有能力做到以下两点的政府：（1）治理其固定人口和确定领土；（2）开展国际关系

Following 1945, however, the purview 范围；权限 of international public law expanded 扩大；拓展 greatly into a modern definition of international law—specifically 具体而言, to include states, as well as international organizations 国际组织 (including both IGOs and NGOs), individuals, and MNEs. Arguably 可以说；可论证地, one of the most prominent 显著的；重要的 international public law institutions 机构 today is the United Nations, which is described 阐述；介绍 in the next section 章节.

[.my2]
然而，1945年之后，国际公法的适用范围大幅拓展，形成了现代国际法的定义——具体来说，其涵盖的主体包括国家、国际组织（含政府间组织和非政府组织）、个人以及跨国企业。可以说，当今最重要的国际公法机构之一便是联合国，下一节将对其进行详细介绍。

---

=== The United Nations

One of the most defining 具有决定性意义的；标志性的 institutions created 创立 following World War II was the United Nations (UN). The creation 创立；建立 of the UN was in response to 作为对……的回应 the many acts 行径 perpetrated 犯下；实施 during World War II that shocked the conscience 良知；道德心 of the international community 国际社会.

[.my2]
第二次世界大战后创立的最具标志性的机构之一便是联合国（UN）。联合国的成立，是为了回应二战期间发生的诸多令国际社会深感震惊的恶行。

The UN has the following four main purposes 宗旨；目的:

[.my2]
联合国具有以下四项主要宗旨：

1. Maintain peace throughout the world.
2. Develop friendly relations among nations.
3. Help nations work together 合作 to improve the lives of poor people, to conquer 战胜；克服 hunger 饥饿, disease 疾病, and illiteracy 文盲, and to encourage 鼓励 respect for each other’s rights 权利 and freedoms 自由.
4. Be a center for harmonizing 协调；调和 the actions of nations to achieve 实现 these goals 目标.

[.my2]
1.  维护全球和平。
2.  发展各国间的友好关系。
3.  协助各国开展合作，改善贫困人口的生活，战胜饥饿、疾病与文盲问题，并促进各国相互尊重彼此的权利与自由。
4.  成为协调各国行动的中心，以助力实现上述目标。

The UN’s constituent instrument 组成文件；宪章 is known as the UN Charter 联合国宪章. The UN Charter sets forth 阐明；规定, among other things 除其他事项外, the UN’s scope 范围 and duty 职责, procedural 程序的；程序性的 issues 问题, and membership qualifications 成员资格；入会条件. The UN Charter in effect 实际上；事实上 encapsulates 概括；包含 much of the body 主体；核心内容 and spirit 精神 of international public law. As of 截至 2014, the UN Charter has 193 signatory states 签署国, representing 代表 nearly every major region 地区 of the world. Because of the high number of state signatory parties 签约方, and the diverse 多样化的；多元的 composition 构成 of these state parties, the UN Charter signatory state number of 193 is viewed as a benchmark 基准；标杆 by which other international conventions 公约 and agreements 协议 are compared 对比；参照.

[.my2]
联合国的核心组成文件是《联合国宪章》。《联合国宪章》除其他内容外，还阐明了联合国的职责范围、程序性事项以及成员资格标准。实际上，《联合国宪章》涵盖了国际公法的大部分核心内容与精神内核。截至2014年，《联合国宪章》已有193个签署国，代表了全球几乎所有主要地区。鉴于签署国数量众多且构成多元，193个这一签署国数量，已成为衡量其他国际公约与协议的重要基准。

Much like 很像；正如 a large parent company 母公司, the UN also has several subsidiary-type 附属性质的 bodies 机构, known as UN organs 机关；机构. These UN organs include the Secretariat 秘书处 (the primary 主要的 public relations 公共关系 organ, which reviews 审议；审阅 reports 报告 and makes recommendations 提出建议), the General Assembly 联合国大会 (the primary legislative 立法的 body), the Security Council 安全理事会 (which has the authority 权力；权限 to use force 使用武力 to preserve 维护 peace and security 和平与安全), and the International Court of Justice 国际法院 (ICJ; the main judicial 司法的 organ).

[.my2]
如同大型母公司一般，联合国也设有多个附属性质的机构，即联合国机关。这些机关包括秘书处（主要的公共关系机构，负责审议报告并提出建议）、联合国大会（主要的立法机构）、安全理事会（拥有使用武力维护和平与安全的权力）以及国际法院（ICJ，主要的司法机构）。

---

=== When Is International Law Binding?

A common question that international law students pose 提出 is: When is international law binding 具有约束力的? The general rule 一般规则 is that international law is binding on those parties 当事方 that consent to 同意；接受 the jurisdiction 管辖权 of international law. For example, relating to 关于 the ICJ, generally only those member states that consent to the ICJ’s jurisdiction are bound by 受……约束 the rights 权利 and privileges 特权 of ICJ judicial decisions 司法裁决, although as with many aspects of law, exceptions 例外 exist 存在.

[.my2]
国际法专业学生常提出的一个问题是：国际法何时具有约束力？一般规则是，国际法仅对同意接受其管辖权的当事方具有约束力。例如，就国际法院而言，通常只有同意接受其管辖权的成员国，才需受国际法院司法裁决所赋予的权利与特权约束，不过和法律的诸多方面一样，这一规则也存在例外情况。

Because the ICJ is the main judicial organ of the UN, does this mean that all UN member states are deemed to 被认为；被视为 have automatically 自动地 consented to ICJ jurisdiction? The short answer 简短答案 is no. Consent to being a UN member state and consenting to ICJ jurisdiction are two separate 独立的 but related 相关的 issues. Put differently 换句话说, ICJ member states are a subset 子集；一部分 of the total population 总数 of UN member states. Another question may be: Why would states consent to ICJ jurisdiction? One reason is that states, acting rationally 理性地行事 in the furtherance of 为促进；为推进 their own self-interest 自身利益, would consent to ICJ jurisdiction based on 基于 the working assumption 可行假设 that they believe that the benefits 益处 outweigh 超过；大于 the costs 代价 of consenting to ICJ jurisdiction.

[.my2]
既然国际法院是联合国的主要司法机构，这是否意味着所有联合国成员国都被自动视为同意接受国际法院的管辖权呢？简短答案是否定的。同意成为联合国成员国与同意接受国际法院管辖权，是两个相互独立但又有关联的问题。换句话说，国际法院的成员国，只是联合国全体成员国中的一部分。可能有人会问：各国为何会同意接受国际法院的管辖权？其中一个原因是，国家为了追求自身利益而做出理性决策时，会基于一个可行假设——即认为接受国际法院管辖权所带来的益处大于其代价——从而同意接受该管辖权。

Benefits often include the ability to bring forth 提起 a cause of action 诉讼理由 (i.e., a lawsuit 诉讼) as plaintiff 原告 against another state. In some cases 某些情况下, this benefit would help smaller and/or weaker states 弱小国家. The costs, however, often include being a defendant 被告. Since the inception 成立；开端 of both the UN and ICJ following World War II, the United States has been a UN member state and originally 最初 consented to ICJ jurisdiction. However, in 1984, related to a seminal case 具有里程碑意义的案件, Nicaragua v. United States, the United States lost a case 败诉 to Nicaragua and subsequently 随后 chose to give notice of 发出通知 its withdrawal 退出 from ICJ jurisdiction. In other words 换句话说, as part of its calculations 考量；权衡, the United States may have perceived 认为；察觉 that the benefits no longer outweighed the costs of ICJ jurisdiction.

[.my2]
接受管辖权的益处通常包括，能够以原告身份对另一国提起诉讼（即发起法律诉讼）。在某些情况下，这一益处能够为弱小国家提供帮助。但与此同时，其代价往往包括可能成为被告。自二战后联合国与国际法院成立以来，美国一直是联合国成员国，且最初也同意接受国际法院的管辖权。然而，在1984年，一起具有里程碑意义的案件——尼加拉瓜诉美国案中，美国败诉，随后便选择发出通知，退出国际法院的管辖权。换句话说，经过权衡考量，美国可能认为，接受国际法院管辖权所带来的益处已不再大于其代价。

The practical effect 实际影响 of this decision 决定, and the subsequent withdrawal by the United States from the ICJ, is that the United States generally 通常 is no longer able to use the ICJ as a forum 法庭；平台 to sue 起诉 and be sued 被起诉. Another concern 担忧 is the signal 信号 that is being sent by the United States when withdrawing from the ICJ. Specifically 具体来说, it may become more difficult to compel 迫使；强制 other nations to reconstitute 重组；重建 their legal systems 法律体系 to international norms 国际准则 when the United States is not a party to 作为一方参与 arguably 可以说 the most notable 著名的；显著的 international public law tribunal 法庭. From the ICJ perspective 角度；视角, the withdrawal of U.S. consent to ICJ jurisdiction diminishes 削弱；降低 the ICJ’s credibility 公信力 within the international community, because many members of the international community view U.S. participation 参与 as a critical 关键的 credibility benchmark 公信力基准.

[.my2]
美国退出国际法院这一决定及其后续行动所产生的实际影响是，美国通常无法再将国际法院作为起诉他国或被他国起诉的平台。另一个值得担忧的点是，美国退出国际法院这一行为所释放的信号。具体而言，如果连美国都不参与这个堪称最具影响力的国际公法法庭，那么要迫使其他国家按照国际准则重组其法律体系，可能会变得更加困难。从国际法院的角度来看，美国退出其管辖权的行为，削弱了国际法院在国际社会中的公信力，因为国际社会的许多成员都将美国的参与视为衡量其公信力的关键基准。

The primary 主要的 tribunal discussed thus far 迄今为止 relating to the consent issue 管辖权同意问题 is the ICJ. However, apart from 除了 the ICJ, consent is also required for jurisdiction relating to other tribunals, such as arbitration panels 仲裁庭. Moreover 此外, municipal courts 国内法院, including U.S. courts, can establish 确立 jurisdiction in certain cases 某些案件 over parties that do not expressly 明确地 consent to its jurisdiction. One classic example 经典案例 of this scenario 情形 exists with a case, Filartiga v. Pena-Irala, whereby 在此案中 a U.S. court concluded 裁定 it had jurisdiction to hear 审理 a dispute 争端 relating to gross 严重的 human rights violations 人权侵犯 in which all litigants 诉讼当事人 were non-U.S. parties, whereby the defendant did not expressly consent to jurisdiction.

[.my2]
迄今为止，我们讨论的与管辖权同意问题相关的主要法庭是国际法院。然而，除国际法院外，其他法庭（如仲裁庭）的管辖权行使，同样需要当事方的同意。此外，国内法院（包括美国法院）在某些案件中，即便当事方未明确同意其管辖权，也可以确立对这些当事方的管辖权。费拉尔蒂加诉佩尼亚-伊拉拉案就是这一情形的经典案例。在该案中，涉案的所有诉讼当事人均非美国主体，且被告也未明确同意接受美国法院的管辖权，但美国法院依然裁定自身拥有审理这起严重侵犯人权争端案件的管辖权。

---

=== International Law Tribunal Types

Several international law tribunal 法庭；裁判庭 types exist. The main types are as follows:

- International Court of Justice (ICJ)
- International Criminal Court (ICC)
- International arbitration 仲裁 panels 专门小组
- Municipal courts 国内法院

[.my2]
国际法法庭存在多种类型，主要类型如下：
- 国际法院（ICJ）
- 国际刑事法院（ICC）
- 国际仲裁庭
- 国内法院

==== International Court of Justice

The International Court of Justice (ICJ) is the main judicial 司法的 organ 机关 of the United Nations. The practical effect 实际影响 is that the ICJ is used as one of the main UN organs to settle 解决 legal disputes 法律争端 between UN member states that have consented to 同意 ICJ jurisdiction 管辖权.

[.my2]
国际法院（ICJ）是联合国的主要司法机关。其实际作用是，作为联合国的主要机关之一，解决那些同意接受其管辖权的联合国成员国之间的法律争端。

The ICJ was formed 成立 in 1945, following the end of World War II, and was modeled after 模仿；以……为蓝本 the Permanent Court of International Justice 常设国际法院, which functioned as 充当；作为 the judicial organ of the League of Nations 国际联盟 from 1920 to 1939. The League of Nations was the pre-1945 predecessor 前身 to the UN. UN member states are generally members of the ICJ; however, ICJ member states may elect to 选择 fully consent to the ICJ’s jurisdiction or consent with reservations 附带保留条件, whereby 在此情况下 a state consents to ICJ jurisdiction in principle 原则上, but with certain exceptions 例外 and/or qualifications 限定条件. An ICJ member state may also choose to withdraw from 退出 ICJ jurisdiction, as in the U.S. case discussed earlier. The main constituent document 组成文件 that prescribe 规定；制定 the rules and regulations 规章制度 relating to the scope 范围 and internal procedures 内部程序 of the ICJ are set forth in 阐明于；规定于 the Statute of the International Court of Justice 国际法院规约 (ICJ Statute).

[.my2]
国际法院于1945年二战结束后成立，其蓝本是1920年至1939年期间担任国际联盟司法机关的常设国际法院。国际联盟是1945年之前联合国的前身。联合国成员国通常都是国际法院的成员；不过，国际法院成员国可选择完全同意接受其管辖权，也可选择附带保留条件地同意，即该国原则上同意接受国际法院管辖权，但会设定某些例外情形和/或限定条件。国际法院成员国也可选择退出其管辖权，正如前文提及的美国案例。规定国际法院管辖范围与内部程序相关规章制度的核心组成文件，载明于《国际法院规约》之中。

As the main judicial organ of the UN, the ICJ hears 审理 legal disputes between member states. The ICJ is composed of 由……组成 15 judges 法官. At first glance 乍一看, 15 ICJ judges may seem like an overly high number to hear a particular 特定的 dispute, but this high number helps ensure 确保 that the 193 UN signatories 签署国 are represented 代表 to the greatest extent possible 尽可能最大程度地.

[.my2]
作为联合国的主要司法机关，国际法院负责审理成员国之间的法律争端。国际法院由15名法官组成。乍一看，用15名法官审理一起特定争端似乎人数过多，但这一人数有助于确保193个联合国签署国能够获得尽可能最大程度的代表。

The ICJ Statute, as earlier mentioned 如前所述, is the main constituent instrument 组成文件 of the ICJ. In ICJ Statute Article 38(1), the sources 渊源 of international law are provided, which are as follows:

- International conventions 公约, which often encompasses 包含；涵盖 treaties 条约
- International customs 惯例, which often encompasses regional 区域的 customs
- General principles 原则 of law of “civilised nations” “文明国家”
- Scholars 学者 and noted authorities 知名权威人士 (“the most highly qualified publicists 法学家”)

[.my2]
如前所述，《国际法院规约》是国际法院的核心组成文件。该规约第38条第1款规定了国际法的渊源，具体如下：
- 国际公约（通常包含条约）
- 国际惯例（通常包含区域惯例）
- “文明国家”的一般法律原则
- 学者及知名权威人士（“最具资历的法学家”）

The ICJ provides two general types of international law remedies 补救措施；救济手段:

- Binding 具有约束力的, nonadvisory 非咨询性的 judicial decisions 司法裁决, based on the ICJ’s “contentious” jurisdiction 诉讼管辖权
- Nonbinding 不具有约束力的 advisory opinions 咨询意见, based on the ICJ’s “advisory” jurisdiction 咨询管辖权

[.my2]
国际法院提供两种基本类型的国际法救济手段：
- 基于国际法院“诉讼管辖权”作出的具有约束力的非咨询性司法裁决
- 基于国际法院“咨询管辖权”作出的不具有约束力的咨询意见

The ICJ generally only hears disputes between states, in what is known as the ICJ’s contentious jurisdiction. This also means that any nonstate actors 非国家主体, such as individuals 个人, IGOs, NGOs, or MNEs, could not directly bring suit 提起诉讼 in the ICJ. In other words 换句话说, MNE of State A could not directly sue 起诉 State B in the ICJ.

[.my2]
国际法院通常仅审理基于其诉讼管辖权的国家间争端。这也意味着，任何非国家主体，例如个人、政府间组织、非政府组织或跨国企业，都无法直接向国际法院提起诉讼。换句话说，A国的跨国企业不能直接在国际法院起诉B国。

This does not, however, automatically mean 自动意味着 that there is no possibility 可能性 for a wronged 受侵害的 individual, for example, to have his or her case heard in the ICJ. One legal solution 法律解决方案 exists through state sponsorship 国家支持；国家出面, which takes place when the state sponsors an individual, MNE, or other relevant entity 实体 that resides 居住 or is domiciled 定居, respectively 分别地, in that particular state. The net effect 实际效果 of state sponsorship is that the alleged 被指控的 injury 损害 to the individual or MNE of State A becomes an injury of State A as a result of 由于 the individual’s residency 居住权 or entity’s domicile 住所地 or presence 存在 in State A. Cases of state sponsorship are, however, more the exception than the general rule 例外多于常规；实属罕见, because more state sponsorship requests 申请 exist than can be given by any particular state.

[.my2]
不过，这并不自动意味着受侵害的个人等主体完全没有机会让其案件在国际法院得到审理。有一种法律解决方案是通过国家支持实现的，具体指当某国为居住或定居于该国的个人、跨国企业或其他相关实体出面支持时，相关案件即可提交国际法院。国家支持的实际效果是，由于相关个人的居住权或相关实体的住所地、存在地均在A国，针对A国个人或跨国企业的被指控损害，就会被视为对A国的损害。但国家支持的案件实属罕见，因为各国收到的相关申请数量远超其能够提供支持的数量。

==== International Criminal Court

The International Criminal Court (ICC) is an independent 独立的 international organization 组织 to the UN. The ICC was established 设立 by the Rome Statute of the International Criminal Court 《国际刑事法院罗马规约》 (Rome Statute). The ICC represents the first-ever permanent 永久性的, treaty-based 基于条约的, international criminal court created to ensure 确保 the rule of law 法治 relating to egregious 极其严重的；骇人听闻的 international crimes 罪行 that “shock the conscience 良知” of the international community 国际社会.

[.my2]
国际刑事法院（ICC）是独立于联合国的国际组织。该法院依据《国际刑事法院罗马规约》（《罗马规约》）设立，是有史以来首个永久性、基于条约的国际刑事法院，其设立目的是确保针对那些“令国际社会震惊”的极其严重的国际罪行的法治得以落实。

The ICC is distinguishable from 有别于；与……不同 the ICJ in three main respects 方面；层面. First, the ICC can hear cases related to nonstates. The most notable 显著的；著名的 example exists in that the ICC can hear complaints 指控 related to the criminal acts 犯罪行为 of individuals, such as the alleged 被指控的 acts of genocide 种族灭绝 and war crimes 战争罪 against Slobodan Milosevic. In other words, nonstate actors can be haled into 被强行传唤至 the ICC’s jurisdiction. Second, the ICC’s focus 关注点 deals with criminal cases related to genocide and war crimes, whereas 而 the ICJ’s purview 管辖范围 is much broader 更广泛的. Thus 因此, the ICC can hear disputes relating to broader subject matters 标的；事项. Third, the ICJ is the UN’s main judicial organ, whereas the ICC is technically 严格来说 independent of 独立于 the UN.

[.my2]
国际刑事法院与国际法院在三个主要方面存在区别。第一，国际刑事法院可审理涉及非国家主体的案件。最显著的例子是，该法院可审理针对个人犯罪行为的指控，例如针对斯洛博丹·米洛舍维奇被指控的种族灭绝罪和战争罪相关指控。换句话说，非国家主体可被强行传唤至国际刑事法院接受管辖。第二，国际刑事法院的关注点是与种族灭绝罪和战争罪相关的刑事案件，而国际法院的管辖范围则宽泛得多。因此，国际刑事法院能够审理涉及更广泛标的的争端。第三，国际法院是联合国的主要司法机关，而严格来说，国际刑事法院独立于联合国。

Much like 很像；正如 the ICJ Statute with respect to 关于；就……而言 the ICJ, the ICC’s Rome Statute sets out 阐明；规定 the ICC’s jurisdiction, structure 结构, and functions 职能. Any person who commits 实施 any of the crimes listed under 列入 the Rome Statute can be held liable for 对……承担责任 ICC prosecution 起诉；追诉. As of 截至 2014, 122 countries were state parties 缔约国 to the Rome Statute. Out of 在……之中 the 122 signatory states 签署国, 34 are from Africa, 18 are from the Asia-Pacific region 亚太地区, 18 are from Eastern Europe 东欧, 27 are from Latin America and the Caribbean 拉丁美洲和加勒比地区, and 25 are from Western Europe and other states 西欧及其他国家.

[.my2]
正如《国际法院规约》之于国际法院，《罗马规约》规定了国际刑事法院的管辖权、组织结构与职能。任何实施了《罗马规约》所列罪行的个人，都可能被国际刑事法院起诉并承担相应责任。截至2014年，已有122个国家成为《罗马规约》缔约国。在这122个签署国中，34个来自非洲，18个来自亚太地区，18个来自东欧，27个来自拉丁美洲和加勒比地区，25个来自西欧及其他国家。

The ICC can establish 确立 jurisdiction relating to crimes of genocide, crimes against humanity 危害人类罪, and war crimes, all of which are defined under 定义于 the Rome Statute. The ICC also has jurisdiction over 对……拥有管辖权 natural persons 自然人 aged 18 and older. Moreover 此外, official capacity 官方身份 as a head of state 国家元首, a member of a government or parliament 议会, an elected representative 民选代表, or a government official 政府官员 does not exempt 免除；豁免 a person from criminal responsibility 刑事责任 under the ICC. Commanders 指挥官 and superiors 上级 relating to military 军事的 and paramilitary 准军事的 regimes 政权 can potentially 可能 also be held liable for 对……承担责任 criminal offenses 刑事犯罪 committed by forces 部队 under their effective command and control 实际指挥控制 or effective authority and control 实际权力控制 under the ICC.

[.my2]
国际刑事法院可对《罗马规约》所定义的种族灭绝罪、危害人类罪和战争罪确立管辖权。该法院同时对年满18周岁的自然人拥有管辖权。此外，依据国际刑事法院相关规定，个人的官方身份——无论是国家元首、政府或议会成员、民选代表还是政府官员——均不能使其免除刑事责任。国际刑事法院还规定，军事及准军事政权的指挥官和上级，也可能需要对其实际指挥控制或实际权力控制下的部队所实施的刑事犯罪承担责任。

---

==== Other Tribunals: International Arbitration Panels and Municipal Courts

Apart from 除了 the ICJ and ICC, other international law tribunals 法庭 exist in both theory 理论 and practice 实践 in the form of 以……的形式 international arbitration 仲裁 panels 专门小组 and municipal courts 国内法院. International arbitration tribunals allow for 允许 litigants 诉讼当事人 to have a dispute 争端 heard by an impartial 公正的；中立的 third party 第三方, referred to as 被称为 the arbitrator 仲裁员. The arbitrator’s decision 裁决 is typically 通常 binding 具有约束力的. The main benefit 益处 of arbitration is less time, money, and reputational 声誉的 risk 风险, because the dispute is heard privately 私下地 among the parties 当事方, outside of 在……之外 the public court system 公共法院体系. The main downside 弊端 of arbitration is that the arbitration panel’s decision may, in certain circumstances 在某些情况下, be appealable 可上诉的. Furthermore 此外, arbitration panels can apply 适用 aspects 方面 of international law if relevant 相关的 issues 问题 exist, and if the parties consent 同意.

[.my2]
除国际法院和国际刑事法院之外，在理论和实践中还存在其他类型的国际法法庭，即国际仲裁庭和国内法院。国际仲裁庭允许诉讼当事人将争端交由一名被称为仲裁员的中立第三方审理。仲裁员作出的裁决通常具有约束力。仲裁的主要优势在于耗时更短、成本更低且声誉风险更小，因为争端是在当事方之间私下审理，不纳入公共法院体系。仲裁的主要弊端是，在某些情况下，仲裁庭作出的裁决可能可以上诉。此外，若存在相关问题且经当事方同意，仲裁庭可适用国际法的相关条款。

Municipal domestic courts 国内法院 represent 代表 another tribunal type that can apply 适用 international public law 国际公法. This concept 概念 may seem counterintuitive 违反直觉的, because the common perception 普遍看法 is that municipal courts apply only the law of their respective 各自的 jurisdiction 管辖权范围. Numerous 众多的 examples, however, exist in the form of case law 判例法, in which municipal courts apply aspects of international law. In fact 事实上, one notable 著名的 U.S. Supreme Court 美国最高法院 judge 法官 famously declared 宣称 that “international law is our [American] law.”

[.my2]
国内法院是另一种可适用国际公法的法庭类型。这一概念看似有违直觉，因为人们普遍认为国内法院仅适用其各自管辖范围内的法律。但在判例法中存在诸多国内法院适用国际法相关条款的案例。事实上，美国最高法院的一位著名法官就曾有过一句名言：“国际法就是我们（美国）的法律。”

---

=== International Public Law’s Global Impact

Modern IPL was beneficial 有益的 in that 因为 it helped address 应对；处理 the acts 行径 of Nazi Germany 纳粹德国 and Imperial Japan 日本帝国 during World War II, which were unanimously 一致地 viewed as 被视为 egregious 极其严重的, blatantly 公然地 counter to 违背 the peace 和平 and security 安全 of the world, and in gross violation of 严重违反 basic human rights 基本人权. Thus 因此, the international community 国际社会 came together 联合起来 in support of 支持 various 各类的 IPL tribunals to render 给予；伸张 justice 正义 for aggrieved 受侵害的 parties 当事方, namely 即 the Nuremberg Trials 纽伦堡审判 and the Tokyo War Crimes Trials 东京审判. The creation 设立 of tribunals and the subsequent 随后的 successful prosecution 起诉 of various involved war criminals 战犯 sent a clear and resounding 响亮的；明确的 message 信号 to the world that such acts would no longer be tolerated 容忍 under modern IPL.

[.my2]
现代国际公法的价值在于，它助力追究了二战期间纳粹德国和日本帝国的恶行，这些行径被一致认定为性质极其严重、公然违背世界和平与安全且严重侵犯基本人权。因此，国际社会联合起来，支持各类国际公法法庭为受侵害方伸张正义，这其中就包括纽伦堡审判和东京审判。这些法庭的设立，以及对相关战犯的成功起诉，向世界传递了一个明确且响亮的信号：此类行径在现代国际公法框架下将不再被容忍。

Another prime 主要的；典型的 example of the impact 影响 of IPL includes the trial 审判 of Slobodan Milosevic 斯洛博丹·米洛舍维奇. As background 背景信息, in 1992, Bosnia 波斯尼亚 declared 宣布 its independence 独立 from Yugoslavia 南斯拉夫. With the support of 在……的支持下 the Yugoslav army 南斯拉夫军队, Bosnian Serbs 波黑塞族 rebelled against 反抗 the secession 分裂；脱离, sparking 引发 a war among Bosnian Serbs, Muslims 穆斯林, and Croats 克罗地亚族 that resulted in 导致 the deaths of tens of thousands of 成千上万的 people. Afterward 此后, the International Criminal Tribunal for the former Yugoslavia 前南斯拉夫问题国际刑事法庭 charged 指控 Slobodan Milosevic, the former Serbian leader 前塞尔维亚领导人, with international human rights crimes 国际人权罪 for the deaths of about 7,500 Muslims by Bosnian Serbs. Evidence 证据 strongly suggested 表明 that the acts were part of a master plan 总体规划 of “ethnic cleansing 种族清洗,” designed 策划 and controlled 操控 by Milosevic, to create a pure 纯粹的 greater Serbia 大塞尔维亚 devoid of 没有；不含 non-Serbs 非塞尔维亚族人.

[.my2]
国际公法产生影响的另一个典型案例是对斯洛博丹·米洛舍维奇的审判。背景信息如下：1992年，波斯尼亚宣布脱离南斯拉夫独立。在南斯拉夫军队的支持下，波黑塞族发起叛乱反对分裂，引发了一场波黑塞族、穆斯林和克罗地亚族之间的战争，导致成千上万人丧生。此后，前南斯拉夫问题国际刑事法庭指控前塞尔维亚领导人斯洛博丹·米洛舍维奇犯有国际人权罪，罪名是波黑塞族造成约7500名穆斯林死亡。有充分证据表明，这些行径是米洛舍维奇策划并操控的“种族清洗”总体规划的一部分，其目的是建立一个纯粹的、没有非塞尔维亚族人的大塞尔维亚。

In the case 本案中, the prosecutor 检察官 argued 主张 that Milosevic’s acts constituted 构成 a gross violation of 严重违反 international human rights law 国际人权法, including (1) acts of genocide 种族灭绝罪 and (2) violations 侵犯 of fundamental freedoms 基本自由 of individuals 个人. Milosevic (defendant 被告), acting in his own defense 自行辩护 as a pro se litigant 自行诉讼的当事人, argued that he is not liable for 对……不承担责任 such acts because (1) the alleged 被指控的 acts of genocide of the Bosnian Serbs and its military 军队 were beyond his control 超出其控制范围; and (2) even assuming 即便假设 he was in control of 掌控 the Bosnian Serbs and its military, such acts were based on 基于 nationalism 民族主义 rather than 而非 racism 种族主义 or religious discrimination 宗教歧视; therefore 因此, according to Milosevic, no violations of fundamental freedoms existed 存在. The Milosevic case is an illustration 例证 of how alleged injustices 不公行径 to humankind 人类 are not only historic 历史性的 but are also ongoing 持续存在的 in the current day 当今. Thus, IPL clearly helps place a strong check and balance 制衡机制 on alleged violators 违法者 of international law before, during, and after the occurrence 发生 of egregious acts.

[.my2]
本案中，检察官主张米洛舍维奇的行径构成了对国际人权法的严重违反，具体包括（1）种族灭绝罪行径和（2）侵犯个人基本自由的行径。米洛舍维奇（被告）以自行诉讼当事人的身份为自己辩护，主张自己无需对这些行径承担责任，理由有两点：（1）波黑塞族及其军队被指控的种族灭绝行径超出了他的控制范围；（2）即便假设他掌控着波黑塞族及其军队，这些行径也是基于民族主义而非种族主义或宗教歧视，因此按照米洛舍维奇的说法，并不存在侵犯基本自由的行为。米洛舍维奇案例证了，被指控的危害人类的不公行径不仅存在于历史，在当今社会也依然持续。由此可见，国际公法在极其严重的恶行发生之前、发生期间和发生之后，都能有效对被指控的国际法违法者形成强有力的制衡。

Apart from 除了 gross human rights violations 严重侵犯人权行为 and infringements 侵害 of peace and security 和平与安全 are denial of justice 拒绝司法；司法不公 issues 问题. One of the more referred-to 被广泛引用的 cases relating to 涉及 the denial of justice is Chattin v. United Mexican States 查廷诉墨西哥合众国案. In Chattin 本案中, the Mexican court 墨西哥法院 majority 多数法官 applied 适用 international standards 国际标准 in concluding 认定 that certain acts by Mexico constituted 构成 a denial of justice to Mr. Chattin, a U.S. citizen 美国公民 employed in 受雇于 Mexico.

[.my2]
除了严重侵犯人权和危害和平安全的行径之外，司法不公问题也属于国际公法的规制范畴。与司法不公相关的一个被广泛引用的案例是查廷诉墨西哥合众国案。在本案中，墨西哥法院的多数法官适用了国际标准，认定墨西哥的某些行径构成了对受雇于墨西哥的美国公民查廷先生的司法不公。

Separate from 不同于 the denial of justice, IPL also helps address 应对 key 关键的 environmental law 环境法 issues. Two cases illustrate 例证 this point 这一点. The first case 第一个案例, United States v. Canada (the Trail Smelter Arbitration case 特雷尔冶炼厂仲裁案) involved 涉及 a dispute before an arbitration panel 仲裁庭 relating to 关于 the release 排放 of certain toxins 有毒物质 into the air 空气 and riverbeds 河床 from a Canadian city 加拿大城市 located just 10 miles north of the Canada–U.S. border 美加边境 to the U.S. border state of Washington 美国边境华盛顿州. The majority 多数仲裁员 in the Trail Smelter Arbitration case held for 作出有利于……的裁决 the U.S. (plaintiff 原告) and concluded 认定 that Canada (defendant 被告) was both liable for 对……承担责任 monetary damages 金钱赔偿, and, further 此外, was ordered 被责令 to refrain from 停止 releasing further pollutant emissions 污染物排放. In doing so 在此过程中, the arbitration tribunal 仲裁庭 held 裁定 that a duty 义务 existed for states to not infringe upon 侵犯 the sovereign rights 主权权利 of other states to a pollutant-free 无污染的 environment 环境, a landmark 具有里程碑意义的 holding 裁决 within environmental law at the time (from the 1930s to the early 1940s).

[.my2]
除司法不公问题外，国际公法还助力解决关键的环境法问题。有两个案例可以例证这一点。第一个案例是美国诉加拿大案（特雷尔冶炼厂仲裁案），本案的争端由仲裁庭审理，案件涉及一座位于美加边境以北仅10英里处的加拿大城市，向美国边境华盛顿州的空气和河床排放某些有毒物质的行为。特雷尔冶炼厂仲裁案的多数仲裁员作出了有利于美国（原告）的裁决，认定加拿大（被告）既要承担金钱赔偿责任，还被责令停止排放更多污染物。仲裁庭在此过程中裁定，各国均负有不侵犯他国享有无污染环境的主权权利的义务，这在当时（20世纪30年代至40年代初）是环境法领域一项具有里程碑意义的裁决。

The second seminal 具有里程碑意义的 case 第二个案例, Australia v. France (the Nuclear Tests case 核试验案), related to 涉及 the nuclear weapons tests 核武器试验 in 1972 and 1973 by France 法国 off of 离……不远的海域 a South Pacific French territory 法国南太平洋领地 near Australia 澳大利亚. Australia brought suit 提起诉讼 in the ICJ against France in 1973. In probable 很可能的 direct response 直接回应, France discontinued 终止 its nuclear tests in 1973, and the ICJ suit was not further pursued 进一步推进. These cases demonstrate 表明 that IPL has both theoretical 理论的 and practical 实践的 significance 意义 that forces 迫使 parties 当事方 to act in conformity with 遵守 IPL involving 涉及 some of the most serious issues facing humankind 人类面临的最严重问题.

[.my2]
第二个具有里程碑意义的案例是澳大利亚诉法国案（核试验案），本案涉及法国于1972年和1973年，在靠近澳大利亚的一块法国南太平洋领地附近海域进行的核武器试验。澳大利亚于1973年向国际法院对法国提起诉讼。很可能是对此的直接回应，法国在1973年终止了核试验，这起国际法院的诉讼也未再进一步推进。这些案例表明，国际公法兼具理论和实践意义，能够迫使当事方在涉及人类面临的一些最严重问题时，遵守国际公法的相关规定。

---

=== Summary

International public law is defined as 被定义为 the rules and regulations 规章制度 regarding 关于 activities 活动 between two or more states 两个或多个国家之间. The year 1945 marked 标志着 the end of World War II 第二次世界大战的结束 and the beginning of modern public international law 现代国际公法的开端. Under the modern view 现代观点 in the post-1945 period 1945年后的时期, international public law covers 涵盖 states, organizations 组织, multinational enterprises 跨国企业, and individuals 个人. The United Nations Charter 《联合国宪章》 embodies 体现 much of the spirit 精神 and substance 实质 underlying 构成……的基础 international public law. Moreover 此外, the International Court of Justice 国际法院 is one of the more visible 显著的；引人注目的 international public law tribunals, which seeks to 旨在 resolve 解决 disputes between states.

[.my2]
总结 +
国际公法被定义为规范两个或多个国家之间交往活动的规章制度。1945年标志着第二次世界大战的结束，也开启了现代国际公法的新纪元。在1945年后的现代观点下，国际公法的规制对象涵盖国家、组织、跨国企业和个人。《联合国宪章》体现了国际公法的大部分精神内核与实质内容。此外，国际法院是国际公法领域中较为引人注目的法庭之一，其宗旨是解决国家之间的争端。



'''


== pure

9.INTERNATIONAL PUBLIC LAW: AN AMERICAN LAW PERSPECTIVE

The previous chapter discussed international business law, but what is international public law (IPL)? The traditional definition of IPL typically covered only states, which are broadly defined as having a defined territory, fixed population, and a government. In contrast, the post-1945 modern definition of IPL covers not only states, but also includes multinational corporations (MNCs), individuals, intergovernmental organizations (IGOs), and nongovernmental organizations (NGOs). The big picture is that modern international law covers many more actors than traditional international law. The rationale is that, in the post-1945 era, actors like MNCs, individuals, IGOs, and NGOs possessed relatively more potential to both benefit as well as harm the global arena.

---

=== The Modern View of International Public Law

The year 1945, and the end of World War II, marked the beginning of modern international law. Before 1945, international law was traditionally viewed as applying only to states.

A state is defined as an entity that has the following:

- A fixed population
- A defined territory
- A government that is capable of (a) governing its fixed population and defined territory and (b) entering into international relations

Following 1945, however, the purview of international public law expanded greatly into a modern definition of international law—specifically, to include states, as well as international organizations (including both IGOs and NGOs), individuals, and MNEs. Arguably, one of the most prominent international public law institutions today is the United Nations, which is described in the next section.

---

=== The United Nations

One of the most defining institutions created following World War II was the United Nations (UN). The creation of the UN was in response to the many acts perpetrated during World War II that shocked the conscience of the international community.

The UN has the following four main purposes:

1. Maintain peace throughout the world.
2. Develop friendly relations among nations.
3. Help nations work together to improve the lives of poor people, to conquer hunger, disease, and illiteracy, and to encourage respect for each other’s rights and freedoms.
4. Be a center for harmonizing the actions of nations to achieve these goals.

The UN’s constituent instrument is known as the UN Charter. The UN Charter sets forth, among other things, the UN’s scope and duty, procedural issues, and membership qualifications. The UN Charter in effect encapsulates much of the body and spirit of international public law. As of 2014, the UN Charter has 193 signatory states, representing nearly every major region of the world. Because of the high number of state signatory parties, and the diverse composition of these state parties, the UN Charter signatory state number of 193 is viewed as a benchmark by which other international conventions and agreements are compared.

Much like a large parent company, the UN also has several subsidiary-type bodies, known as UN organs. These UN organs include the Secretariat (the primary public relations organ, which reviews reports and makes recommendations), the General Assembly (the primary legislative body), the Security Council (which has the authority to use force to preserve peace and security), and the International Court of Justice (ICJ; the main judicial organ).


---

=== When Is International Law Binding?

A common question that international law students pose is: When is international law binding? The general rule is that international law is binding on those parties that consent to the jurisdiction of international law. For example, relating to the ICJ, generally only those member states that consent to the ICJ’s jurisdiction are bound by the rights and privileges of ICJ judicial decisions, although as with many aspects of law, exceptions exist.

Because the ICJ is the main judicial organ of the UN, does this mean that all UN member states are deemed to have automatically consented to ICJ jurisdiction? The short answer is no. Consent to being a UN member state and consenting to ICJ jurisdiction are two separate but related issues. Put differently, ICJ member states are a subset of the total population of UN member states. Another question may be: Why would states consent to ICJ jurisdiction? One reason is that states, acting rationally in the furtherance of their own self-interest, would consent to ICJ jurisdiction based on the working assumption that they believe that the benefits outweigh the costs of consenting to ICJ jurisdiction.

Benefits often include the ability to bring forth a cause of action (i.e., a lawsuit) as plaintiff against another state. In some cases, this benefit would help smaller and/or weaker states. The costs, however, often include being a defendant. Since the inception of both the UN and ICJ following World War II, the United States has been a UN member state and originally consented to ICJ jurisdiction. However, in 1984, related to a seminal case, Nicaragua v. United States, the United States lost a case to Nicaragua and subsequently chose to give notice of its withdrawal from ICJ jurisdiction. In other words, as part of its calculations, the United States may have perceived that the benefits no longer outweighed the costs of ICJ jurisdiction.

The practical effect of this decision, and the subsequent withdrawal by the United States from the ICJ, is that the United States generally is no longer able to use the ICJ as a forum to sue and be sued. Another concern is the signal that is being sent by the United States when withdrawing from the ICJ. Specifically, it may become more difficult to compel other nations to reconstitute their legal systems to international norms when the United States is not a party to arguably the most notable international public law tribunal. From the ICJ perspective, the withdrawal of U.S. consent to ICJ jurisdiction diminishes the ICJ’s credibility within the international community, because many members of the international community view U.S. participation as a critical credibility benchmark.

The primary tribunal discussed thus far relating to the consent issue is the ICJ. However, apart from the ICJ, consent is also required for jurisdiction relating to other tribunals, such as arbitration panels. Moreover, municipal courts, including U.S. courts, can establish jurisdiction in certain cases over parties that do not expressly consent to its jurisdiction. One classic example of this scenario exists with a case, Filartiga v. Pena-Irala, whereby a U.S. court concluded it had jurisdiction to hear a dispute relating to gross human rights violations in which all litigants were non-U.S. parties, whereby the defendant did not expressly consent to jurisdiction.

---

=== International Law Tribunal Types

Several international law tribunal types exist. The main types are as follows:

- International Court of Justice (ICJ)
- International Criminal Court (ICC)
- International arbitration panels
- Municipal courts

==== International Court of Justice

The International Court of Justice (ICJ) is the main judicial organ of the United Nations. The practical effect is that the ICJ is used as one of the main UN organs to settle legal disputes between UN member states that have consented to ICJ jurisdiction.

The ICJ was formed in 1945, following the end of World War II, and was modeled after the Permanent Court of International Justice, which functioned as the judicial organ of the League of Nations from 1920 to 1939. The League of Nations was the pre-1945 predecessor to the UN. UN member states are generally members of the ICJ; however, ICJ member states may elect to fully consent to the ICJ’s jurisdiction or consent with reservations, whereby a state consents to ICJ jurisdiction in principle, but with certain exceptions and/or qualifications. An ICJ member state may also choose to withdraw from ICJ jurisdiction, as in the U.S. case discussed earlier. The main constituent document that prescribe the rules and regulations relating to the scope and internal procedures of the ICJ are set forth in the Statute of the International Court of Justice (ICJ Statute).

As the main judicial organ of the UN, the ICJ hears legal disputes between member states. The ICJ is composed of 15 judges. At first glance, 15 ICJ judges may seem like an overly high number to hear a particular dispute, but this high number helps ensure that the 193 UN signatories are represented to the greatest extent possible.

The ICJ Statute, as earlier mentioned, is the main constituent instrument of the ICJ. In ICJ Statute Article 38(1), the sources of international law are provided, which are as follows:

- International conventions, which often encompasses treaties
- International customs, which often encompasses regional customs
- General principles of law of “civilised nations”
- Scholars and noted authorities (“the most highly qualified publicists”)

The ICJ provides two general types of international law remedies:

- Binding, nonadvisory judicial decisions, based on the ICJ’s “contentious” jurisdiction
- Nonbinding advisory opinions, based on the ICJ’s “advisory” jurisdiction

The ICJ generally only hears disputes between states, in what is known as the ICJ’s contentious jurisdiction. This also means that any nonstate actors, such as individuals, IGOs, NGOs, or MNEs, could not directly bring suit in the ICJ. In other words, MNE of State A could not directly sue State B in the ICJ.

This does not, however, automatically mean that there is no possibility for a wronged individual, for example, to have his or her case heard in the ICJ. One legal solution exists through state sponsorship, which takes place when the state sponsors an individual, MNE, or other relevant entity that resides or is domiciled, respectively, in that particular state. The net effect of state sponsorship is that the alleged injury to the individual or MNE of State A becomes an injury of State A as a result of the individual’s residency or entity’s domicile or presence in State A. Cases of state sponsorship are, however, more the exception than the general rule, because more state sponsorship requests exist than can be given by any particular state.

==== International Criminal Court

The International Criminal Court (ICC) is an independent international organization to the UN. The ICC was established by the Rome Statute of the International Criminal Court (Rome Statute). The ICC represents the first-ever permanent, treaty-based, international criminal court created to ensure the rule of law relating to egregious international crimes that “shock the conscience” of the international community.

The ICC is distinguishable from the ICJ in three main respects. First, the ICC can hear cases related to nonstates. The most notable example exists in that the ICC can hear complaints related to the criminal acts of individuals, such as the alleged acts of genocide and war crimes against Slobodan Milosevic. In other words, nonstate actors can be haled into the ICC’s jurisdiction. Second, the ICC’s focus deals with criminal cases related to genocide and war crimes, whereas the ICJ’s purview is much broader. Thus, the ICC can hear disputes relating to broader subject matters. Third, the ICJ is the UN’s main judicial organ, whereas the ICC is technically independent of the UN.

Much like the ICJ Statute with respect to the ICJ, the ICC’s Rome Statute sets out the ICC’s jurisdiction, structure, and functions. Any person who commits any of the crimes listed under the Rome Statute can be held liable for ICC prosecution. As of 2014, 122 countries were state parties to the Rome Statute. Out of the 122 signatory states, 34 are from Africa, 18 are from the Asia-Pacific region, 18 are from Eastern Europe, 27 are from Latin America and the Caribbean, and 25 are from Western Europe and other states.

The ICC can establish jurisdiction relating to crimes of genocide, crimes against humanity, and war crimes, all of which are defined under the Rome Statute. The ICC also has jurisdiction over natural persons aged 18 and older. Moreover, official capacity as a head of state, a member of a government or parliament, an elected representative, or a government official does not exempt a person from criminal responsibility under the ICC. Commanders and superiors relating to military and paramilitary regimes can potentially also be held liable for criminal offenses committed by forces under their effective command and control or effective authority and control under the ICC.

==== Other Tribunals: International Arbitration Panels and Municipal Courts

Apart from the ICJ and ICC, other international law tribunals exist in both theory and practice in the form of international arbitration panels and municipal courts. International arbitration tribunals allow for litigants to have a dispute heard by an impartial third party, referred to as the arbitrator. The arbitrator’s decision is typically binding. The main benefit of arbitration is less time, money, and reputational risk, because the dispute is heard privately among the parties, outside of the public court system. The main downside of arbitration is that the arbitration panel’s decision may, in certain circumstances, be appealable. Furthermore, arbitration panels can apply aspects of international law if relevant issues exist, and if the parties consent.

Municipal domestic courts represent another tribunal type that can apply international public law. This concept may seem counterintuitive, because the common perception is that municipal courts apply only the law of their respective jurisdiction. Numerous examples, however, exist in the form of case law, in which municipal courts apply aspects of international law. In fact, one notable U.S. Supreme Court judge famously declared that “international law is our [American] law.”

---

=== International Public Law’s Global Impact

Modern IPL was beneficial in that it helped address the acts of Nazi Germany and Imperial Japan during World War II, which were unanimously viewed as egregious, blatantly counter to the peace and security of the world, and in gross violation of basic human rights. Thus, the international community came together in support of various IPL tribunals to render justice for aggrieved parties, namely the Nuremberg Trials and the Tokyo War Crimes Trials. The creation of tribunals and the subsequent successful prosecution of various involved war criminals sent a clear and resounding message to the world that such acts would no longer be tolerated under modern IPL.

Another prime example of the impact of IPL includes the trial of Slobodan Milosevic. As background, in 1992, Bosnia declared its independence from Yugoslavia. With the support of the Yugoslav army, Bosnian Serbs rebelled against the secession, sparking a war among Bosnian Serbs, Muslims, and Croats that resulted in the deaths of tens of thousands of people. Afterward, the International Criminal Tribunal for the former Yugoslavia charged Slobodan Milosevic, the former Serbian leader, with international human rights crimes for the deaths of about 7,500 Muslims by Bosnian Serbs. Evidence strongly suggested that the acts were part of a master plan of “ethnic cleansing,” designed and controlled by Milosevic, to create a pure greater Serbia devoid of non-Serbs.

In the case, the prosecutor argued that Milosevic’s acts constituted a gross violation of international human rights law, including (1) acts of genocide and (2) violations of fundamental freedoms of individuals. Milosevic (defendant), acting in his own defense as a pro se litigant, argued that he is not liable for such acts because (1) the alleged acts of genocide of the Bosnian Serbs and its military were beyond his control; and (2) even assuming he was in control of the Bosnian Serbs and its military, such acts were based on nationalism rather than racism or religious discrimination; therefore, according to Milosevic, no violations of fundamental freedoms existed. The Milosevic case is an illustration of how alleged injustices to humankind are not only historic but are also ongoing in the current day. Thus, IPL clearly helps place a strong check and balance on alleged violators of international law before, during, and after the occurrence of egregious acts.

Apart from gross human rights violations and infringements of peace and security are denial of justice issues. One of the more referred-to cases relating to the denial of justice is Chattin v. United Mexican States. In Chattin, the Mexican court majority applied international standards in concluding that certain acts by Mexico constituted a denial of justice to Mr. Chattin, a U.S. citizen employed in Mexico.

Separate from the denial of justice, IPL also helps address key environmental law issues. Two cases illustrate this point. The first case, United States v. Canada (the Trail Smelter Arbitration case) involved a dispute before an arbitration panel relating to the release of certain toxins into the air and riverbeds from a Canadian city located just 10 miles north of the Canada–U.S. border to the U.S. border state of Washington. The majority in the Trail Smelter Arbitration case held for the U.S. (plaintiff) and concluded that Canada (defendant) was both liable for monetary damages, and, further, was ordered to refrain from releasing further pollutant emissions. In doing so, the arbitration tribunal held that a duty existed for states to not infringe upon the sovereign rights of other states to a pollutant-free environment, a landmark holding within environmental law at the time (from the 1930s to the early 1940s).

The second seminal case, Australia v. France (the Nuclear Tests case), related to the nuclear weapons tests in 1972 and 1973 by France off of a South Pacific French territory near Australia. Australia brought suit in the ICJ against France in 1973. In probable direct response, France discontinued its nuclear tests in 1973, and the ICJ suit was not further pursued. These cases demonstrate that IPL has both theoretical and practical significance that forces parties to act in conformity with IPL involving some of the most serious issues facing humankind.

---

=== Summary

International public law is defined as the rules and regulations regarding activities between two or more states. The year 1945 marked the end of World War II and the beginning of modern public international law. Under the modern view in the post-1945 period, international public law covers states, organizations, multinational enterprises, and individuals. The United Nations Charter embodies much of the spirit and substance underlying international public law. Moreover, the International Court of Justice is one of the more visible international public law tribunals, which seeks to resolve disputes between states.
