
= 2-15 基督教制度演变
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


== 基督教出现 (1世纪)

In the first century CE, Christians joined this landscape. Christians generally disapproved of animal sacrifice and worship of the emperor.

公元一世纪，基督徒加入了这片土地(古罗马). 基督徒普遍不赞成动物祭祀和崇拜皇帝。

'''

==  教会改革

=== 教会从领主手中, 获得独立权

The chaotic aftermath of the collapse of the Carolingian Empire led to a complicated situation between secular rulers and the Christian Church. According to German law, lords had the right to control everything on their land, including churches and monasteries. This control even extended to the appointment of officeholders to church positions such as abbot or bishop. To ensure they had the loyalty of church officials, lords staffed these offices with their family members or even sold them to the highest bidder. The consequence was that those without religious vocations, or even familiarity with Christian doctrine, could be installed into church leadership. Even the position of the pope, the bishop of Rome, could come up for sale.

(中世纪的 法兰克)加洛林帝国崩溃后的混乱, 导致世俗统治者和基督教会之间的复杂关系。根据日耳曼法律，领主有权控制其领土上的一切，包括教堂和修道院。这种权力甚至延伸到能任命官员担任教会职务，例如修道院院长或主教。同时, 为了确保教会的忠诚，领主们在这些机构里配备了自己的家人，甚至将它们卖给出价最高的人。结果是，那些没有宗教使命感，甚至不熟悉基督教教义的人，都可以被任命为教会领导层。甚至罗马教皇、罗马主教的职位也,可能被出售。

Revulsion at this treatment of religious office led to a reform movement intended to remove the influence of secular lords from the management of the church. The movement is often associated with the monastery of Cluny in France, which managed to get independence from the local aristocrat.

对"宗教职务被这种待遇"的反感, 引发了一场改革运动，旨在消除世俗领主对教会管理的影响。该运动通常与法国克鲁尼修道院联系在一起，该修道院成功地从当地贵族手中获得了独立权。克吕尼 运动最终吸引了其他神职人员，他们希望教会能够独立于世俗影响, 来控制主教的选举。

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |Header 2

|-> 解决"买卖官职"的问题 → 非经正常途径选举出来者 , 直接开除.

|They condemned the sale of offices as a sin called simony and insisted that bishops should be elected by clergy, independent of a lord. Any clergy member who had bought an office or had it bought for them could be removed.

罗马主教谴责说, 1.主教应该由神职人员选举产生. 2.出售官职犯了”买卖圣职”罪. 任何买官的人, 都应被解雇.

|-> 解决教会体制内"父传子"的问题 → 让牧师无后代, 单身

|To end the practice of treating church positions like a fief to be passed on to the officeholder’s children, priests were told to practice celibacy and were forbidden to marry.

为了解决教会职位被”父传子”的问题, 规定牧师要禁婚, 单身, 就不会有儿子来继承了.

|-> 对想干涉”教会人事任命”的国王, 就将他驱逐出教会

|The church declared that a king who tried to appoint a bishop or asked for a bribe could be excommunicated (placed outside the church, its communion, and the sacraments, in hopes of reforming the offender). Excommunication could threaten the king’s position and lead to rebellions.

教会宣布，试图”任命主教”或”要求贿赂”的国王, 可以被逐出教会（被置于教会、圣餐和圣礼之外，希望能改造罪犯）。国王被逐出教会, 可能会威胁到他的地位, 并引发叛乱。
|===


The reform movement unintentionally made divisions sharper.

(教会)改革, 也无意中加剧了东西方教廷(即西欧和东罗马帝国)的分歧。(1054年大分裂)

=== 如何区分"(宗教)战争合法性"问题

The reformers were also interested in creating a thoroughly Christianized society by distinguishing between legitimate and illegitimate warfare. The church argued that Christian soldiers, especially knights, should obey a code of conduct that reflected the church’s values. These principles contributed to the ideals of chivalry.

改革者还希望通过区分合法战争和非法战争, 来创建一个彻底基督教化的社会。教会认为基督教士兵， 尤其是骑士，应该遵守反映教会价值观的行为准则。这些原则促成了”骑士精神”的理想.

'''

==  东西方基督教的分裂 (1054年大分裂) : 西方天主教, 东方东正教




[.small]
[options="autowidth" cols="1a,1a"]
|===
|the pope in Rome 罗马教皇 |the patriarch of Constantinople 君士坦丁堡宗主教

|- the church in the west operated in Latin

西方教会以拉丁语运作

|- The church in the east used Greek

东方教会使用希腊语

|- insisted on a celibate clergy

坚持神职人员独身

|- permitted priests to marry (although tradition held that bishops should be unmarried)

允许牧师结婚（尽管传统认为主教应该不婚）

|- elevated the pope as the final authority for all matters regarding the church everywhere.

将教皇提升为各地教会所有事务的最终权威。

|- believed other patriarchs were just as authoritative as the pope.

相信其他牧首, 与教皇一样具有权威。
|===


Following this Great Schism of 1054, the eastern church became known as the Eastern Orthodox Church, and the western half the Catholic Church.

在1054年的大分裂之后，东方的教会, 被称为东正教; 而西半部的, 则被称为天主教。

'''

==  罗马教皇为了促进宗教改革, 和建立自己的军事力量, 以与日耳曼国王竞争, 就借助”十字军东征”为达到这些目的的途径.

In 1095, facing invasion on all sides, the Byzantine ruler Alexios I sent ambassadors to plead for help from the pope and an opportunity for a reconciliation between the two churches. Urban answered the Byzantine emperor’s call for aid.

1095年，面对四面楚歌的入侵，拜占庭统治者阿莱克修斯一世派遣大使向罗马教皇请求帮助，并为两个教会提供了和解的机会。(东西两个教会已经在1054年时大分裂了). (罗马教皇)乌尔班回应了拜占庭皇帝的援助呼吁.

Urban’s goal at this point was to free the Holy Land from non-Christian rulers in defense of the Christians living there; it was not a blanket endorsement of violence against Muslims. 

These limitations were later eased, however, as the popes discovered the power of calling repeated crusades to promote the reforming goals of the church and to compete with political rivals in Europe, like the German emperors.

乌尔班此时的目标, 是将圣地从非基督教统治者手中解放出来，以保卫居住在那里的基督徒。

这并不是全面支持针对穆斯林的暴力行为。然而，这些限制后来得到了缓解，因为教皇发现了号召反复十字军东征具有这种力量: 能促进教会改革 (让教会独立于王权, 王权不能控制教会), 并与日耳曼国王等欧洲政治对手竞争.

The popes had no armies, and they often had to depend on the unreliable aristocracy for protection when disagreements over church policy resulted in armed conflict with the princes of Europe. If they were to maintain their control over the church in contests with kings and emperors, it would be useful to see what happened when a pope rallied common Christians to a religious cause as a test of faith.

教皇没有军队，当他们在教会政策上的分歧, 导致与欧洲诸侯的武装冲突时，他们经常不得不依赖不可靠的贵族的保护。如果他们要在与国王和皇帝的竞争中保持对教会的控制，那么看看当教皇将普通基督徒召集到宗教事业中, 以考验其信仰时, 会发生什么 (做试探)，将会很有用。

'''

== (14世纪) 教会和君主关系紧张动荡, 导致教皇权威削弱, 及教会内部分裂

In contrast to the stability that had defined much of the thirteenth century for the European Christian Church, it began experiencing significant destabilization in the beginning of the fourteenth century, when tensions between the pope and national monarchs led to a weakening of papal authority and division within the church.

欧洲基督教会, 在 13 世纪的大部分时间里保持稳定状态, 但与之相反的是，从14 世纪初开始, 教会就经历严重的不稳定，当时教皇和国家君主之间关系紧张, 导致教皇权威的削弱, 和教会内部的分裂。

'''

==  新教改革

=== 新教改革前, 教会的腐败状态

The Protestant Reformation began in 1517, but its seeds had been sown years earlier. Over the course of the Middle Ages, the Catholic Church had grown richer, and its higher clerical offices had become dominated by people motivated more by the desire for wealth and power than by spiritual concerns. Although Europe’s peasants remained devoutly attached to their faith, critics claimed that

- popes acted less like Christ’s representatives on earth and more like secular princes, intervening in European political affairs and even commanding armies.
- Members of the clergy often lived lavishly in palatial surroundings and dressed themselves in silks and furs.
- Some had mistresses and illegitimate children, who were often given positions in the church.
- Wealthy families often purchased church offices for their members,
- and some men held bishoprics (areas under the authority of a bishop) in more than one place at a time by hiring other men to perform their offices.

Secular rulers, kings, and princes jealous of the church’s power sometimes vied with the pope for control of the churches in their territory and welcomed opportunities to reject the church’s authority.

新教改革始于 1517 年，但其种子早在几年前就已播下。在中世纪的过程中，天主教会变得更加富有， 其高级教职职位, 已被更多出于"对财富和权力的渴望, 而不是精神关注"的人所主导。尽管欧洲农民仍然虔诚地信仰他们的信仰，但批评者声称:

- 教皇的行为不太像基督在地球上的代表，而更像世俗王子, 他们干预欧洲政治事务，甚至指挥军队。
- 神职人员经常生活在富丽堂皇的环境中，穿着丝绸和毛皮衣服。
- 有些人有情妇和私生子，他们经常在教会中担任职务。
- 富裕的家庭经, 常为其成员购买教堂办公室，
- 一些男子通过雇用其他男子履行职责，同时在多个地方拥有主教职位（主教管辖的地区）。

嫉妒教会权力的世俗统治者、国王和王子, 有时会与教皇争夺对其领土内教会的控制权，并欢迎"能拒绝教会权威"的任何机会。

'''

===  赎罪券

Indulgences were a way to reduce or even cancel the time after death during which people needed to suffer in purgatory to atone for their sins before reaching heaven. These rewards could be earned by performing actions of great religious merit, such as going on Crusade. However, the church also taught that the pope controlled a store of merit amassed by Jesus and the Christian saints, whose virtue was so great they had entered heaven with grace left over. The church could allot this “extra” virtue to someone else in the form of an indulgence.

赎罪券是一种减少甚至取消死后时间的方法，在这段时间里，人们在进入天堂之前, 需要在炼狱中受苦以赎罪。这些奖励, 可以通过执行具有重大宗教价值的行为来获得，例如参加十字军东征。然而，教会还教导说，教皇控制着耶稣和基督教圣徒积累的功德，他们的美德如此之大，以至于他们带着剩余的恩典进入了天堂。教会可以以"赎罪券"的形式将这种 “额外”的美德分配给其他人。

'''

===  (路德) 对"赎罪券"的批判, 论证

A German monk named Martin Luther began the Protestant Reformation. Luther was outraged at the selling of indulgences. He drafted ninety-five arguments explaining why the sale of indulgences was wrong.

一位名叫"马丁·路德"的德国僧侣, 开启了"新教改革"。路德对教廷出售"赎罪券"感到愤怒。他起草了九十五条论据, 来解释为什么出售"赎罪券"是错误的.




论证逻辑:

[.small]
[options="autowidth" cols="1a,1a"]
|===
|Header 1 |

|-> 有信仰就能超生, 而不在于行动 (*即"全由上帝决定,非人力可改变,命定论"*)
|- He believed only God could grant forgiveness and that humans could do nothing to ensure their salvation, which depended entirely upon God. This is known as the doctrine of justification by faith.

他(马丁·路德)相信只有上帝才能给予宽恕，凡人无法采取任何措施, 来确保他们的救赎，这完全取决于上帝。这被称为"因信称义"的教义。

The Catholic Church taught that salvation was achieved through a combination of religious faith and good works. Buying an indulgence was regarded as a good work because the money went to the church. Luther taught that faith alone was sufficient for salvation and that humans were unable to work toward their own redemption, which depended entirely upon God.

天主教会教导说，"救赎"是通过"宗教信仰"和"善行"的结合, 来实现的。"购买赎罪券"被认为是一件"善行"，因为钱都捐给了教堂。而路德教导说，只要有"信仰", 就足以获得救赎，而人类无法为自己得到救赎, 而做努力，这完全取决于上帝的意志。(*这其实剥夺了"人的主观能动性", 宣扬了"命定论".*)

|-> 圣经是唯一的指导内容, 而非后人添加的其他习俗
|- Luther also said the pope had no control over purgatory and that there was no foundation in the Bible for the belief that the merit amassed by Jesus and the saints could be given to others.

路德还表示，教皇无法控制"炼狱"，圣经中没有任何基础可以相信"耶稣和圣徒所积累的功德, 可以给予他人"。

- Furthermore, adherence to centuries’ worth of Catholic tradition was not necessary to be a good Christian. Luther contended that scripture alone should be the source of Christian belief and practice. His followers thus abandoned many traditional Catholic practices, including clerical celibacy.

此外，遵守几个世纪来的天主教传统, 并非是成为一名优秀基督徒的必要条件。路德认为，圣经本身, 就应该是基督教信仰和实践的(真正)源泉。因此，他的追随者放弃了许多"传统的天主教习俗"，包括神职人员的"独身"习惯。新教徒还呼吁废除"僧侣和修女的宗教秩序"。

|-> 人能否赎罪,不取决于"赎罪券"
|- Any truly repentant Christian has a right to full remission of penalty and guilt, even without indulgence letters.

任何真正悔改的基督徒, 都有权完全免除刑罚和罪责，即使没有赎罪券。

|-> "买赎罪券"不是真正的"善行"
|- Christians are to be taught that he who gives to the poor or lends to the needy does a better deed than he who buys indulgences.

Christians are to be taught that the pope would and should wish to give of his own money, even though he had to sell the basilica of St. Peter, to many of those from whom certain hawkers of indulgences cajole money.

基督徒应该被教导，施舍给穷人, 或借钱给有需要的人, 这些善行, 能比购买"赎罪券"的人, 做得更好。 +
基督徒应该被教导，教皇愿意, 而且应该愿意, 将自己的钱捐给众多那些被"赎罪券小贩"骗取金钱的人，即使他不得不卖掉圣彼得大教堂。

|->
|- Protestants also called for the abolition of religious orders of monks and nuns. A life in the clergy, which the Catholic Church had proclaimed the greatest of all callings, was considered no better than the pursuit of any other vocation in life.

天主教会宣称, 神职人员是所有职业中最伟大的. 但人们并不认为, "神职人员"比"生活中其他职业"更好。

|===


In 1521, he was excommunicated (excluded from participating in the life of the church).

1521年，他(路德)被逐出教会（被排除在教会生活之外）。

'''

===  (加尔文) 的观点 → 命定论

Another center of Protestant thought was the city of Geneva in what is now Switzerland. The city’s religious leader, John Calvin, espoused a doctrine known as predestination, which held that God had predetermined which souls would be granted salvation upon death and which were destined for hell. No person could ever know for certain whether they were saved or damned, and there was nothing they could do to ensure salvation. Calvinists embraced the doctrine, despite denying human agency.

新教思想的另一个中心, 是日内瓦，位于现在的瑞士。该市的宗教领袖约翰·加尔文(John Calvin ) 他的思想与马丁·路德的思想相似，但在一个关键方面有所不同。加尔文拥护一种被称为"预定论"的学说，该学说认为上帝已经预先确定了哪些灵魂将在死亡后获得救赎，哪些灵魂注定要下地狱。没有人能够确切地知道自己是得救了, 还是被诅咒了，而且他们也无法采取任何措施, 来确保得救(命定论)。它否认了人类的"能动性".

'''

===  路德 & 加尔文 理论的区别

'''

===  作为自救(反腐), 天主教的自我改革

The Catholic Reformation, also called the Counter-Reformation, was the Catholic Church’s effort to address Luther’s challenges as well as to effect other necessary reforms.

- Indulgences were retained, but their sale was forbidden.
- The council prohibited church officials from appointing relatives to church offices,
- limited bishops to holding office in only one bishopric,
- and took steps to improve the education of Catholic clergy and curb their luxurious habits.

天主教的宗教改革，也称为"反宗教改革"，是天主教会为解决路德的挑战, 以及实施其他必要的改革, 而做出的努力。

- 赎罪券被保留，但禁止出售。
- 该委员会禁止教会官员任命亲属担任教会职务，
- 限制主教只能在一个主教区担任职务，
- 并采取措施改善天主教神职人员的教育, 并遏制他们的奢侈习惯。

'''

==  英国国王(亨利八世) 摆脱教皇, 自立为英国国教首脑

Efforts to silence Martin Luther were unsuccessful, and the new form of Christianity called Protestantism spread throughout the German-speaking lands. Often the new religion was welcomed by rulers as a reason to reject the pope’s authority.

压制马丁·路德的努力没有成功，新教的基督教形式, 在整个德语区传播开来。通常，"新教"受到统治者的欢迎，能利用它作为武器, 来"拒绝教皇权威". (国王能利用”新教”来作为武器, 来对抗天主教教皇)

The English Reformation, however, was of a different character. In England, reform was initially imposed from the top down, not by a committed convert but by a king looking for an expedient way to exchange one queen for another.

然而，英国决定执行"宗教改革", 却具有不同的性质原因。在英格兰，改革最初是"自上而下"实施的，而非由坚定的皈依者(自下而上)实施的，只是作为国王寻求的一种权宜之计，来将自己的一位皇后, 换成另一位。(国王利用"新教",来实现私人的目的: 换老婆)

Henry VIII of England decided to remove himself from under the pope’s authority. Henry declared the English church no longer bound by the pope’s authority. In 1534, Parliament passed the Act of Supremacy, establishing the Church of England with the English monarch as its head.

Under Henry’s leadership, the Church of England (also known as the Anglican Church) remained largely Catholic in terms of both doctrine and ritual, but his failure to purge the English Church of all elements of Roman Catholicism did not sit well with many Protestants.

英国的亨利八世决定摆脱教皇的权威。亨利宣布"英国教会"不再受"教皇权威"的约束。 1534年，议会通过了《至高无上法案》 ，建立了"以英国君主为首脑"的英国国教。

在亨利的领导下，英格兰教会（也称为"英国国教"或"圣公会"）在教义和仪式方面, 基本上仍然保持了天主教的特点，但他未能将"英格兰教会"中的所有"罗马天主教元素"清除，这让许多"新教徒"感到不满。

'''

==  英国"清教徒"(加尔文派), 去往北美, 建立自己的理想宗教"山巅之城” (17世纪初)

During Elizabeth’s reign, English Calvinists, known as Puritans, attempted unsuccessfully to move the Church of England even further from the doctrine and ritual of the Catholic Church.

伊丽莎白期间，英国"加尔文主义者"(清教徒), 试图使英国国教进一步远离天主教会的教义和仪式，但没有成功。

By the 1570s and 1580s, Puritans had also come to oppose the structure of the Church of England, in which the monarch was the head of the church. They believed churches should be independent and governed by groups of elected elders instead of a king or queen. Elizabeth was unwilling to change the manner in which the Church of England was governed, however.

到了1570年代和1580年代，清教徒开始反对英国国教中的"君主是教会的领袖"制度。他们认为, 教会应该独立，并由选举产生的长老团体, 而不是国王或王后来管理。然而，伊丽莎白不愿意改变英国国教的治理方式。

During the reign of her successor James I, Puritans who wished to separate from the Church of England (known as Separatists) began to depart England for places, including mainland Europe and North America, where they believed they would be able to establish ideal Christian communities.

在她的继任者詹姆斯一世统治期间，希望脱离英国国教的清教徒 （称为分离主义者）, 开始离开英国, 前往欧洲大陆和北美等地，他们相信, 在那里能够建立理想的基督教社区。

'''

==  法国确立”天主教”为国教 (1598)

The transition from Catholicism to Protestantism in England was more peaceful than elsewhere. Outside England, the dispute over whether a kingdom should be Catholic or Protestant could be quite violent.

France officially issued the Edict of Nantes in 1598. The edict established Catholicism as the official religion of France.

在英国，从天主教到新教的过渡比其他地方更加和平。而在英格兰以外，关于"国王应该信奉天主教, 还是新教"的争论, 可能会相当激烈。

法国在1598年颁布"南特敕令"后, 确立"天主教为法国国教".

'''

==  西班牙 (国教: 天主教)

In the Spanish Netherlands, Philip II of Spain fought against Calvinist rebels. The seven northern provinces established their independence from Spain as the United Provinces of the Netherlands. The Netherlands was not the only place in which Philip II, who regarded himself and Spain as defenders of Catholicism, fought to maintain the church’s supremacy. In 1588, he launched a naval attack on England with the intent of restoring it to the Catholic Church and ending its support for Protestant rebels in the Spanish Netherlands. The invasion failed.

在西属尼德兰，西班牙的菲利普二世与加尔文派反叛者作战。北方的七个省从西班牙独立，成立了荷兰联合省。菲利普二世不仅在荷兰与反叛者作战，他还视自己和西班牙为天主教的捍卫者，努力维护教会的至高权力。1588年，他发起了一次对英格兰的海上攻击，企图使其重新归附天主教会，并结束其对西属尼德兰新教叛军的支持。此次入侵以失败告终。

'''

==  三十年战争 (新教和天主教之间的宗教战争)

The wars of religion continued into the seventeenth century. From 1618 to 1648, the Thirty Years’ War between Catholic and Protestant states raged in the Holy Roman Empire. As German Catholics, Lutherans, and Calvinists fought one another, other European countries entered the fray.

In the end, the German Protestants were victorious. The Peace of Westphalia, which ended the war in 1648, established the independence of each of the entities, numbering nearly one thousand, that had made up the Holy Roman Empire.

宗教战争一直持续到十七世纪。 1618年至1648年，神圣罗马帝国"天主教"国家, 与"新教"国家之间的三十年战争爆发。当德国境内的天主教徒、和(新教的)"路德"教徒和"加尔文"教徒, 互相争斗时，其他欧洲国家也加入了战斗。 +
最终，德国的新教徒一方取得了胜利. 1648 年结束战争的《威斯特伐利亚和约》, 确立了组成神圣罗马帝国的近千个实体的独立性。

'''

==  基督教, 是要兼容当地文化, 还是严守纯正基督教义的问题 (对中国清朝)

Kangxi tolerated other religions, including Christianity. The Jesuits’ efforts to learn the Chinese language and their respect for Chinese culture made them more successful at winning converts than the Dominicans and Franciscans. But members of these other orders grew jealous and complained to the Pope about the Jesuits’ willingness to accommodate Chinese practices. 

When the Vatican ruled that all church services must be conducted in Latin and that Chinese Christians must be ordered to abandon their ancestral rites, Kangxi decreed that missionaries who complied would have to leave China.

康熙容忍其他宗教，包括基督教。耶稣会士学习中文的努力, 和对中国文化的尊重, 使他们比"多米尼加"和"方济各会"更成功地赢得皈依。但其他修会的成员开始嫉妒，并向教皇抱怨"耶稣会士" 愿意迁就中国的做法。当梵蒂冈规定所有教堂仪式必须用拉丁语进行，并且必须命令中国基督徒放弃祖先仪式时，康熙下令, 遵守命令的传教士必须离开中国。

'''
