
= 重要地理交通基建建设=
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''


== (埃及) 苏伊士运河

Britain’s second area of interest in Africa was Egypt, an excellent source of cotton for its textile mills. The possibility of building a canal across the Isthmus of Suez, which divided Asia from Africa, had intrigued Europeans since the fifteenth century. Linking the Mediterranean and Red Seas would allow ships to reach the Indian and Pacific Oceans without sailing around the tip of Africa, greatly easing trade with South and East Asia. Construction began in 1859, and the Suez Canal opened to shipping in 1869.

英国对埃及感兴趣, 因为埃及的棉花能作为原材料, 供英国纺织厂使用.

另外, 希望修建一条从连通地中海和红海的”苏伊士运河”, 从15世纪以来欧洲人就一直想实现它. 这能令船只不需要绕行非洲南端, 就能直接通道印度洋和太平洋. 降低贸易成本.

苏伊士运河从1859年开始修建，1869年通航.

Britain had initially opposed the canal. It threatened British domination over the main water route to Asia, which passed the British Cape Colony, and it made its prized colony of India more accessible —and more vulnerable. Britain’s attitude changed, however.

In 1875, unable to pay his debts, Ismail Pasha sold Egypt’s shares in the Suez Canal to Britain. He was also forced to allow British and French officials to manage Egypt’s financial affairs.

英国最初是反对修建运河的. 因为运河经过了英属开普殖民地，并且让印度更容易到达, 威胁了英国的利益. 但后来英国改变了态度. 1875年，(埃及总督)伊斯梅尔帕夏由于无力偿还债务，将埃及在苏伊士运河的股份卖给了英国。他还被迫允许英国和法国官员管理埃及的金融事务。

'''