
= American Pageant - 041 (1865-present)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义

What's up 怎么了, APUSH people? Today we're breaking down 分解；剖析 the historical time periods 历史时期, trying to make sense of 理解 all these different periods in American history. We're going to focus on 关注 periods 6 to 9 -- roughly 大约 the 1860s all the way to contemporary 当代的 America.

So we start off 开始 with the Gilded Age 镀金时代. And keep in mind 记住 this kind of doesn't have a start date officially 正式地, but we're going from around the 1870s to 1900. And in the Gilded Age, on the surface 表面 everything appears to be really good and amazing -- you have industrialization 工业化 -- but there's lots of problems beneath the surface 表面之下. You know, you have Industrial Revolution 工业革命 going on that really kind of kicks off 开始 with the Civil War in the 1860s, which you have rapid economic transformation 经济转型 of American society. People like Carnegie and Rockefeller building up 建立 industries in steel and oil. This is the rise of industrial capitalism 工业资本主义 -- major industry -- and you have manufacturing 制造业 taking place at a much greater level than before. So manufacturing was replacing agriculture 农业, and you have lots of technological changes 技术变革 going on during the Industrial Revolution.

You have migrations 迁移 taking place -- people are moving to urban areas 城市地区. In fact, by 1920 you're going to have the majority 大多数 of Americans living in cities in urban areas. With these migrations, you have people coming into the United States -- huge increase in immigration 移民. And there's changes of who's coming to America. You have the rise of the new immigrants 新移民, especially in the 1890s, from Southern and Eastern European countries like Italy and Poland and Russia. And you have spikes 激增 in Asian immigration, especially from China.

With this change in immigration, you're going to have nativism 本土主义 increasing during the Gilded Age. And you're going to see this manifest itself 表现出来 in things like the Chinese Exclusion Act 排华法案 in the 1880s and efforts to ban or limit immigrants from Southern and Eastern Europe. And you're going to see that in the 1920s with the quotas 配额. You know, keep in mind during this time period you have workers are organizing into national labor unions 全国性工会. In all those areas you see in the pink and the red stars are going to be places where strikes 罢工 are going to take place and various unions will form.

You have the Knights of Labor 劳动骑士团 -- they focus on unskilled 非技术性的 and skilled workers 技术工人. They were much more welcoming to a variety of different types of workers, whereas the American Federation of Labor 美国劳工联合会 headed by Samuel Gompers was all about those skilled workers in bread and butter issues 生计问题. So workers are responding to the problems of industrialization during this Gilded Age period.

Farmers responded to mechanization 机械化 of agriculture and control of the railroad industry 铁路工业 as well. They're organizing and trying to fight back against some of these challenges. And the big movement is going to be in the 1890s -- The People's Party or more commonly referred to as the Populist Party 人民党/平民党. They wanted the farmers wanted a stronger government role in regulating 监管 the economic system. They want laws regulating railroad industry, they want the direct election 直接选举 of senators, they want free coinage of silver 自由铸造银币. And they're going to run your boy Thomas Watson for president. He's going to lose, but they're a major force at least in the 1890s.

So these are some of the big themes 主题 and events of the Gilded Age. You know, things look good but underneath the surface there's some challenges. The Industrial Revolution -- a couple more things you should know about is there is a common belief of laissez-faire 自由放任主义 -- the government should not attempt to control or regulate business. This was advocated obviously by the wealthy, the business elite 商业精英 -- they don't want government meddling 干预 in their pursuit of profits 追求利润. Many advocated ideas such as social Darwinism 社会达尔文主义 -- survival of the fittest 适者生存 -- and this justified the concentration of wealth 财富集中. The rich are getting richer because they're better -- they deserve to be wealthy. They took Darwin's theories of evolution 进化论 and applied them to the new industrial world. So make sure you know about social Darwinism.

There are some examples of regulation 监管 in this period. You have the beginnings of this -- you have the Interstate Commerce Act 州际商业法 in 1887 which regulated railroad rates 铁路费率. It was weak initially, but it's the beginning. And this is advocated by farmers. It's the beginning of government regulation of industry. You have the Sherman Antitrust Act 谢尔曼反托拉斯法 of 1890 -- how are we going to regulate these monopolies 垄断, these trusts 托拉斯? And once again in the beginning very weak, but it is the beginning of government regulation.

At the same time in this period -- 1870s to 1890 -- you have something called the New South 新南方. There is industrialization of the South. People are advocating we should switch over to 转向 a more industrialized economy. In spite of this advocacy, sharecropping 佃农制 and tenant farming 租佃制 remain the primary economic activity throughout the southern states. And you are going to see post-Reconstruction Jim Crow laws 吉姆·克劳法 reinforced and deemed constitutional 被认为合宪 by the Plessy versus Ferguson decision 普莱西诉弗格森案 throughout southern states.

Now during the same time, you're also having western expansion 西部扩张 take place. This is kind of a common theme 常见主题 in American history, but the western expansion we're talking about in this time period -- roughly the 1860s to 1890 -- is trans-Mississippi West 密西西比河以西. You're going to have larger numbers of migrants 移民 move to the West in search of land and economic opportunity 经济机会, frequently proving competition and violent conflict. And this is actually going to be encouraged by the US government by the federal government. They are going to encourage this western expansion.

An example of this federal government role is the Homestead Act 宅地法 in 1862 where the government is giving free or cheap land to settlers 定居者 to move out west. You have the Pacific Railroad Act 太平洋铁路法案 in 1862 which allows for government the route of the first transcontinental railroad 横贯大陆铁路. And a huge part of this is government subsidies 政府补贴 -- tax breaks 税收减免 to the railroad companies to build this railroad network you see on those maps.

Now important to note -- with this western expansion comes the destruction and assault 攻击 on Native life. And this is going to take many different forms. You are going to have the rapid decline of the bison 野牛 -- it's going to be systematically slaughtered 系统性地屠杀 in order to undermine Native American resistance 抵抗. You're going to have a series of Indian Wars 印第安战争 -- you can see on the map those red stars are some of the biggies. And of course the last of the major Indian Wars takes place at Wounded Knee 伤膝河 in 1890.

You're also going to have the Dawes Severalty Act 道斯土地分配法 passed by Congress in 1887 which effectively ended tribal ownership 部落所有权 of land. The goal of the US government was a policy of assimilation 同化政策 -- let's get Native Americans off of tribal land, off of communal land 公有土地, and get them onto private property 私有财产 and Americanize them. That was one of the goals of the Dawes Act. Make sure you know about this.

This guy Frederick Jackson Turner -- 1893 -- wrote The Significance of the Frontier in American History 边疆在美国历史上的重要性. He basically declared the frontier closed 宣布边疆关闭. You have the Indian Wars coming to a close, you have the continent settled from basically coast to coast. And this kind of idea of the frontier closing leads us to another period in American history -- that of US expansion. This is roughly 1890s to 1914.

Now I know what you're thinking -- America has always been expanding since its little 13 colony days along the Atlantic coast. This is different -- this is overseas expansion 海外扩张. One of the reasons -- one of the reasons this happens is this idea the frontier is closed in the 1890s, so the only place left to go is abroad is overseas. There's other reasons as well you should know about -- economic access to markets for goods and cheap raw materials 原材料. Remember the Industrial Revolution is going on -- how are we going to maintain this growth unless we find new markets and new cheap raw materials?

You also have political motives 政治动机 for US expansion -- we want to compete with other nations, you know especially European nations and also the rise of Japan around the globe. There's military reasons as well -- people like Alfred T. Mahan advocated for building up a strong navy 强大海军. So you're going to need islands for naval bases 海军基地 across the globe. And then finally there's also ideological reasons 意识形态原因 -- you know this idea of spreading Anglo-Saxon civilization 盎格鲁-撒克逊文明, spreading democracy, spreading Christianity.

There's a variety of forms this takes, but all of these different things including the closing of the frontier contributes to American expansion in the 1890s. Lots of examples you should know about -- you have the annexation 吞并 of Hawaii. And remember Hawaii geographically is going to be significant -- strategically significant 战略意义 -- but there's also economic motives for its annexation by William McKinley.

You have in China the Open Door Policy 门户开放政策 -- wanting access to trade, getting rid of European and Japanese spheres of influence 势力范围. You have the Spanish-American War 美西战争 -- hugely important in 1898 -- The Splendid Little War -- four months we fight Spain and we end up annexing not only Cuba, Puerto Rico, Guam and the Philippines. And you can see on the map some of those territories.

This is followed by a brutal war 残酷战争 against the Philippines led by the Filipino resistance 抵抗运动 by Emilio Aguinaldo. They don't want the US to take them over, and the Philippines fights back and it's a deadly brutal war. And of course you have Theodore Roosevelt with his big project -- the big Panama Canal 巴拿马运河 -- and he adds his Roosevelt Corollary 罗斯福推论 to the Monroe Doctrine 门罗主义 saying that we are going to be the policeman, the regulators of the Western Hemisphere.

Keep in mind not everyone agrees with this. You have debates between imperialists 帝国主义者 -- those in favor of expansion -- and the Anti-Imperialist League 反帝国主义联盟 who are opposed to this expansion and criticize US efforts abroad. Make sure you know that this expansion takes place during the administrations of not only McKinley, Roosevelt, but also William Howard Taft and Woodrow Wilson. They're going to play a more active role. They're going to do so in a variety of ways. So know some examples of US expansion during these years.

Which leads us to our next period in American history -- the Progressive Movement 进步主义运动, which really kind of begins in the 1890s to roughly 1920. This is happening at the same time some of these other events are going on, but this is really a domestic movement 国内运动. It's government power to regulate and improve society. There was a belief that there were numerous problems that needed to be addressed, and this was a rejection of the laissez-faire ideology -- the government needs to play a role.

You have various muckrakers 扒粪者 who start exposing problems. You have various movements that are happening. And ultimately this movement -- the Progressive Movement -- is going to result in reform 改革. Some economic examples is trust busting 反托拉斯 under Theodore Roosevelt and Taft and Wilson. They're going to start strengthening the Sherman Antitrust Act and breaking up the so-called bad trusts.

You're going to have the Meat Inspection Act 肉类检查法 regulating the meat industry, Pure Food and Drug Act 纯净食品和药品法 regulating both the drug and food industry, and the Wisconsin Idea 威斯康星理念 by Robert La Follette where we're going to regulate the railroad industry and other big business. There's also going to be efforts to expand democracy during the Progressive Movement. And that's you're going to see in the 17th Amendment 第十七修正案 providing for the direct election of senators and reforms like the recall 罢免, the initiative 创制权, the direct primary 直接初选. And of course a very active woman suffrage movement 妇女选举权运动 that had been going on for quite some time and picks up steam 获得动力 during the 1890s and the early 20th century.

Now keep in mind the Progressive Movement is a variety of movements -- so not everyone who fought for women's suffrage is fighting for these other areas. Women are going to play a huge role in the Progressive Movement, especially middle class white women and especially in cities, whereas the Populist movement was farmers -- the progressives are urban city dwellers 城市居民.

You're also going to have moral reform 道德改革 during the Progressive Movement. There was the Anti-Saloon League 反沙龙联盟 which advocated prohibition 禁酒令, and eventually they will get passage of the 18th Amendment 第十八修正案 banning alcohol. And of course the environmental movement 环保运动 -- and you're going to have various branches of that environmental movement -- the preservationists 保护主义者 who wanted to keep nature pure led by John Muir, and the conservationists 保育主义者 led by Theodore Roosevelt and Gifford Pinchot where we're going to kind of manage natural resources 自然资源 for future generations.

Once again 再次, the Progressive Movement 进步主义运动 is going to span 跨越 various presidential administrations 总统任期. So not only Theodore Roosevelt, but Taft and Wilson are all going to seek reform 寻求改革 at the national level 国家层面. They're going to have various degrees of success 不同程度的成功. And as you're going to see with Woodrow Wilson, they're reluctant 不情愿的 to support certain reforms such as women's suffrage 妇女选举权, and women have to put a lot of pressure 施加压力 on him to finally achieve that 19th Amendment 第十九修正案.

World War I 第一次世界大战 kind of interrupts 中断 this domestic reform movement 国内改革运动. The Progressive Era 进步时代 really begins in 1914 and will go until 1918. Make sure you know that in the beginning the US was pledged to neutrality 承诺中立. Wilson tried to keep the United States out of World War I, but we will ultimately enter the war in 1917 for a variety of reasons 多种原因. One is kind of ideological 意识形态的 -- Wilson wanted to be involved in the post-war negotiations 战后谈判. He wanted to make the world safe for democracy 使民主世界安全, and so he wants to be at the table 参与谈判 when the treaties are signed.

You have violations 违反 of American neutrality -- remember the sinking of the Lusitania 卢西塔尼亚号沉没, the British ship -- American lives are lost. You have the Zimmerman Telegram 齐默尔曼电报 where Germany's trying to hook up with 勾结 Mexico and declare war against the United States. And you have the fact that we were giving a lot of money to the Allies 协约国, and so we had an economic stake 经济利益 in their victory.

We do go to war, and eventually the US helps win that war. And Wilson is going to be heavily involved 深度参与 in post-war negotiations. Make sure you know about the 14 Points 十四点原则 -- his kind of plan for the future and his plan to try to prevent future wars. And a big part of that is the League of Nations 国际联盟 -- this international organization that will prevent future wars from occurring.

Ultimately though, Congress rejects 拒绝 the League of Nations. The Republican-controlled Congress had no desire to kind of move away from 背离 George Washington's warnings and his farewell address 告别演说, and so they say we're staying out of this. And this kind of for a lot of people marks a return to US isolationism 孤立主义 -- we want to stay out of European affairs or only be involved when we want to be involved.

The impact 影响 on the home front 后方 during World War I -- there's a couple important things that you should highlight. One is The Great Migration 大迁徙 -- there's a huge movement of African-Americans from the South to Northern cities like New York that happens actually before World War I, but World War I accelerates it. And then of course you have violations of civil liberties 公民自由 -- you have the Sedition Act 反煽动叛乱法 which basically really placed a lot of restrictions on freedom of speech 言论自由, and the Schenck versus the US case 申克诉美国案 which says speech can be restricted as long as that speech presents a clear and present danger 明显而现实的危险. So you have this theme again of civil liberties and security and the balance between those two.

When World War I ends, the Progressive Movement kind of peters out 逐渐消失 and you have this period that everyone loves to study -- the Roaring Twenties 咆哮的二十年代. And the Roaring Twenties has tremendous economic and cultural changes 经济文化巨变. It's a decade of lots of transformations 转型. You have new technologies like the radio, car and others that are becoming affordable or invented for the first time, and this dramatically improves the standard of living 生活水平 for a lot of Americans.

Not only that, you have mass consumption 大众消费 because people are able to buy things using new forms of payment like the installment plan 分期付款. And advertising and the growth of the advertising industry 广告业 allows people to kind of realize they want a bunch of things that they may not be able to afford now.

Another part of the 1920s you definitely need to know about are the conflicts -- a lot of different conflicts. You have conflicts between native born Americans 本土出生的美国人 and immigrants. Remember there's that reaction to those Southern and Eastern European immigrants. In fact, right after World War I you're going to have something called the Red Scare 红色恐慌 where everyone's freaking out 惊慌失措 that America's going to have a revolution and we're going to be overrun by Bolsheviks 布尔什维克 and communists and anarchists 无政府主义者 and all these things.

And the Palmer Raids 帕尔默搜捕 start rounding up 围捕 people whether or not they actually did anything wrong or not. You have the famous Sacco and Vanzetti trial 萨科与万泽蒂案 where those dudes don't get any kind of fair trial 公正审判 because they're Italian, they're anarchists, they're draft dodgers 逃避兵役者, and they're ultimately put to death. You have the Quota Acts 配额法案 that are passed -- the big one is in 1924 that basically says only 2% of the immigrants that came in 1890 could come, and that was intended to restrict and limit immigration from Southern and Eastern Europe.

Another conflict you see is conflict between religious fundamentalists 宗教原教旨主义者 who tended to be in rural areas and more modern thinking that tended to be in the cities. This manifest itself in all sorts of areas like the Scopes Trial 斯科普斯案 where a teacher gets in trouble for teaching evolution 进化论. You have the 18th Amendment which is not just an issue over religion, but many religious fundamentalists favored banning alcohol. And that doesn't go all that well as you see rising crime and people like Al Capone 阿尔·卡彭.

And then there's all sorts of other conflicts that you should kind of make yourself aware such as the rise of the KKK 三K党 -- that's connected to this anti-immigrant rise of nativism. You get The Lost Generation 迷惘的一代 -- a whole group of writers and artists who are disillusioned with 对...幻灭 the consumerism 消费主义 of the 1920s and the other things going on. And you get the Harlem Renaissance 哈莱姆文艺复兴 and this flowering of black culture and a celebration of being black in America. So the Roaring Twenties -- much more complicated decade than just flappers 时髦女郎 and drinking illegal alcohol.

Which leads us to the Great Depression 大萧条. Great Depression begins in 1929. Throughout the decade of the 1920s, the stock market 股市 was doing really well, and all that collapses 崩溃 on October 29th, 1929 -- Black Tuesday 黑色星期二. This is the start of the Great Depression. And there's a lot of reasons for the Great Depression -- the stock market is just one of those reasons.

Hoover tries to figure out what to do, doesn't do enough, and loses the election to Franklin Roosevelt. And in 1933 he takes office 就职, and this is kind of the period of the New Deal 新政. Franklin Roosevelt -- FDR -- believed in his New Deal program which he felt was going to provide relief 救济, recovery 复苏 and reform 改革 for the American people. This changed the role of the federal government and created the modern welfare state 福利国家.

You know, and they love to ask questions that compare and contrast 比较对比 the New Deal to the Progressive Movement. They share something in common which is a rejection of laissez-faire. Couple things that you should know -- some programs: FDIC -- the Federal Deposit Insurance Corporation 联邦存款保险公司 -- ensured people's bank deposits (still around today). The Social Security Administration 社会保障局 provided basically the modern-day safety net 安全网 -- the welfare state -- protecting the elderly, the unemployed, and women with dependent children.

You have the Wagner Act 瓦格纳法案 in 1935 which basically for the first time the federal government saying labor unions 工会 have a right to exist and the federal government is going to stand behind their right to bargain collectively 集体谈判. There is debate over the New Deal. You know there were people who wanted to limit it or kind of roll it back 撤销. The Supreme Court declares a couple New Deal programs unconstitutional -- the NRA and the AAA. Roosevelt tries his court packing plan 法院填塞计划 and suffers a rare political defeat.

Republicans and conservatives did not like the New Deal because they did not like this rise of liberalism 自由主义 -- this big government. And you had others who wanted to expand the New Deal -- people like Huey Long 休伊·朗 who wanted to kind of adopt kind of a socialist plan -- "Every Man a King," share our wealth. He's going to get shot, so that's not going to work out. But there were debates about the New Deal.

Keep in mind the impact is huge. There is a New Deal Democratic Coalition 新政民主党联盟 -- a group such as farmers, urban immigrants, union members and African-Americans and women start really voting for the Democratic party in huge numbers because of the New Deal policies under Franklin Roosevelt. It established the federal responsibility for society -- this idea of the safety net. This was not established in America until the New Deal. It is the beginning or the rise of liberalism during this time period represented by the Democratic party.

But keep in mind the New Deal does not end the Great Depression. It will ultimately be World War II which does that. This kind of period ends in around 1939 as the world's attention and the nation's attention turns to World War II, which is going to take place from 1939 to 1945.

In the beginning from 1939 to 1941, we're basically trying to stay the heck out of it 尽量不卷入 -- just as we did during World War I. There's a whole bunch of things that slowly kind of get us more and more involved. You have the Neutrality Acts 中立法案 where we're like not selling weapons to any country at war, we're not sailing on boats. But then England's in trouble as you can see in that political cartoon, so we start adopting policies like cash and carry 现购自运, lend lease 租借法案. We're slowly helping out the Allies because we don't want them to lose to these totalitarian governments 极权政府.

Well, neutrality will end with the attack on Pearl Harbor 珍珠港事件 by Japan on December 7th, 1941. We are now in World War II. The impact of World War II on the home front is huge -- make sure you know about it. The biggie is Japanese American and Japanese internment 日裔美国人拘禁 -- basically civil liberties denied. Japanese people of Japanese descent -- over 100,000 -- are sent to one of 10 internment camps 拘留营 throughout the country. This is a huge violation of their civil liberties and an embarrassment for America and American history.

There's a mass mobilization 大规模动员 during World War II -- all parts of society are mobilizing to help win the war -- US factories, labor unions and so on. And you have all sorts of social impacts of the war. You have the Double V campaign 双V运动 for African-Americans -- victory against tyranny abroad as well as victory against racism at home. You have women playing an active role symbolized by Rosie the Riveter 铆工罗茜. And you have something called the Bracero Program 临时劳工计划 where people -- Mexicans -- are brought into the United States to work to cover the labor shortage 劳动力短缺 in areas especially like agriculture. So know about the impacts of World War II on the home front.

Eventually of course the Allies will win. We roll deep, but of course the big ones were the Soviets, the United States and England. And there's a variety of reasons -- one is US industrial production -- we produce a huge amount of the weapons and the stuff that helps fight the Axis powers 轴心国. And you get new technology, and of course the big one is the Manhattan Project 曼哈顿计划 -- the secret program between England and the US that develops the A-bomb 原子弹 which will ultimately end World War II. And the importance of the Big Three Alliance 三巨头联盟 -- Churchill, Stalin and FDR and their relationship and collaboration will help bring down the Axis powers.

And important battles -- military success at places like D-Day Normandy 诺曼底登陆 and northern France -- the opening of the second front 第二战场. And island hopping 跳岛战术 where basically the United States is trying to get close enough to Japan to either invade or bomb the country. Ultimately it will be the atomic bomb which will end World War II -- hugely debated topic, different opinions on that issue. I highly suggest you kind of develop your own opinion.

But with the end of World War II -- big idea -- America becomes a superpower 超级大国. We emerge as one of the most dominant countries in the world. And that leads us to our next period -- the Cold War 冷战. There is no start date on the Cold War -- it's going to go from 1945 to 1991. And basically the Cold War is an ideological, political and military struggle between the US and the Soviet Union. It really starts to pick up some steam 获得动力 in 1947, and the US objective throughout the Cold War is contain communism 遏制共产主义.

Communism was already in Eastern Europe -- we were not liking that. Remember the Yalta agreement 雅尔塔协议 -- we thought Stalin was going to remove those troops -- he does not. And a guy by the name of George Kennan comes up with this containment policy 遏制政策. There are numerous examples of containment -- here are a few: the Truman Doctrine 杜鲁门主义 -- we're going to give money to Greece and Turkey to make sure they don't fall to the communists and they do not. The Marshall Plan 马歇尔计划 -- we're going to give a lot of money to Western Europe to help rebuild it so that those countries will not turn to communism -- they do not.

You're going to have NATO -- the North Atlantic Treaty Organization 北大西洋公约组织 -- which is an example of collective security 集体安全. All those countries in the green belong to NATO. That is our first permanent military alliance 永久军事同盟 and it is going to still be around to this day. Other examples of containment get a little messier. In Korea, we stop the North Korean advance on South Korea, therefore preserving South Korea's non-communist status. And we try to stop communism in Vietnam, but it's a little messy there because it's really kind of a mix of communism and a nationalist movement. They wanted to get rid of France and then they wanted to get rid of us, and ultimately the US is not going to do as well in Vietnam.


The US and the Soviets fluctuated 波动 between periods of confrontation 对抗 -- we got beef 冲突 all over the globe -- but we're also going to have periods of détente 缓和 or mutual coexistence 和平共处 or relaxation of tensions 紧张局势缓解. Some examples of conflict -- you have the Berlin Blockade 柏林封锁 where Truman stands up to 对抗 Stalin with the Berlin Airlift 柏林空运. The Cuban Missile Crisis 古巴导弹危机 -- the whole world nearly ended. Luckily Kennedy and Khrushchev -- cooler heads prevailed 冷静者占上风. But you're going to have these examples throughout the Cold War of us kind of thawing 解冻 or tensions relaxing -- Spirit of Geneva 日内瓦精神 under Eisenhower where we're starting to talk to one another, the SALT I treaty 第一阶段限制战略武器条约 with the Soviet Union under Nixon. And of course -- of course -- Nixon being the guy who opens up our relationship with China in the 1970s.

Few more things about the Cold War you should know about. During the Cold War, the US is going to at times support for undemocratic governments 非民主政府. For example, the CIA is going to overthrow 推翻 or help overthrow the government in Iran, in Guatemala in the 1950s under Eisenhower. And in both cases, new governments that take the place of the government we help get rid of are not exactly friendly to the local population or democratic. We support them though because they are non-communists. And there are other examples -- you're going to see this support for undemocratic governments also in South Vietnam as both Eisenhower and Kennedy supported the Diem administration in spite of its corruption 腐败 and lack of support from the general population.

Another important idea during the Cold War is this kind of battle between civil liberties 公民自由 versus security 安全. There is a fear during the Cold War that takes place -- in fact there's a second Red Scare 红色恐慌 in the late 40s, early 1950s. And this manifest itself in the House Un-American Activities Committee 众议院非美活动调查委员会 where they started investigating communist influence, and the rise of Senator Joseph McCarthy and McCarthyism 麦卡锡主义. There were in fact some communist spies -- you have Alger Hiss 阿尔杰·希斯 and the Rosenbergs 罗森堡夫妇 -- but this fear kind of becomes a paranoia 偏执 and a lot of people's civil liberties are violated in the process.

There is a debate over the arms race 军备竞赛. We are competing with the Soviet Union -- who can build up a bigger arsenal 武器库? And famously Eisenhower in his farewell address warns the nation about the military-industrial complex 军工复合体. And there is conscious fear of this proliferation 扩散 of these horrible weapons, and you're going to see arms control agreements 军控协议 taking place or at least attempted throughout the Cold War.

The Cold War is going to lead to some controversies 争议. You're going to have famously the anti-war protest 反战抗议 over the war in Vietnam. And this is going to pick up a huge amount after the Tet Offensive 春节攻势 in 1968 where people realized this war is nowhere near being over. And following revelations 揭露 of the secret bombing of Cambodia by the Nixon Administration, and ultimately this will... and ultimately one of these protests will end in a shooting at the University... Kent State University 肯特州立大学.

More protests will erupt following revelations of the secret bombing of Cambodia by the Nixon Administration. And during this wave of protest, you have the shooting that takes place at Kent State where people are shot by the National Guard 国民警卫队.

Quick look at some of the domestic things happening. The 1950s is often times kind of seen as this decade of conservative 保守的 or complacent 自满的. There's a lot of opportunity to compare it to the 1920s because you got a lot of things that are similar. Eisenhower is the president -- the hero of World War II. He is a moderate Republican 温和共和党人, so you're not going to see a big reform. There's no liberal huge agenda going on. But there's a lot of changes in America. It's an economically prosperous decade relatively speaking for many people -- but not all people.

And you're going to see the growth of the middle class 中产阶级. Post-World War II economy -- a huge growth in the middle class as the economy is transitioning. You got more and more white collar workers 白领 -- so people are not working in industrial factories but in more white collar type jobs. Post-World War II you also have this mass movement of people to the suburbs 郊区 -- the famous Levittowns 莱维敦. And you have a huge baby boom 婴儿潮 in the late 40s and early 50s. Credit cards are introduced in this decade which allows for an increase in consumerism 消费主义. Television became a common household item in the 1950s and kind of leads to the spread and growth of American culture.

But there are tensions in the 1950s that you should be aware of. And these are some of them. Betty Friedan writes The Feminine Mystique 女性的奥秘 -- it's actually published in 1960 but it really kind of condemns 谴责 the way women are treated in American society and the expectations of women playing the role of the happy suburban housewife 郊区家庭主妇. And you're going to see the growth of the women's movement in subsequent years.

The beatniks 垮掉的一代 -- a group of artists -- criticize the conformity 一致性 of the 1950s. And of course a big example of this decade not being one filled with complacency comes with the civil rights movement 民权运动 that really picks up a lot of energy in the 1950s. So let's take a quick look at the Civil Rights Movement.

You know there's no start date for this, but you know civil rights activists used legal challenges 法律挑战, nonviolence 非暴力 and direct action 直接行动 to achieve their goals and to try to overturn 推翻 the Jim Crow system that was in place. As you could see in that photo, you know there is no start movement -- World War II you see with the Double Victory campaign. You have organizations like the Congress of Racial Equality 种族平等大会 starting to rise up. And in the 1950s in 1954 you have Brown v. Board of Education 布朗诉教育委员会案 -- this overturned segregation 种族隔离 -- ruled school segregation inherently unequal 本质上不平等.

Other examples of nonviolence and direct action can be seen in the Montgomery Bus Boycott 蒙哥马利巴士抵制运动 in 1955 sparked by the arrest of Rosa Parks, the Freedom Rides 自由乘车运动 in 1961 under or during the Kennedy administration. And so this movement really kind of is energized in World War II, picks up steam in the '50s, and then explodes in the 1960s.

An important idea you should keep in mind is the three branches of the government eventually played a role in advancing the cause of civil rights. At first they're slow to do so, but with a lot of pressure eventually we start to see some change. An executive branch role in that change can be seen when Truman desegregated 废除种族隔离 the military in 1948 -- took a lot of heat 承受压力 for that. Judicial change can be seen with Brown v. Board of Education which overturned Plessy v. Ferguson. And legislative change could be seen with the Civil Rights Act of 1964 民权法案 and the Voting Rights Act of 1965 投票权法案 -- we'll cover both those in just a few moments -- signed by President Lyndon Johnson.

Civil rights movements -- there's a lot more movements than just African-American civil rights. But keep in mind there was fierce white resistance 白人强烈抵制 to these changes, especially in southern states. You have the Southern Manifesto 南方宣言 to the Brown decision where over 100 southern congressmen basically said the court -- the Supreme Court -- is abusing its power 滥用权力. You have the Little Rock Nine 小石城九人事件 blocked by Governor Orville Faubus -- he doesn't want to allow them into the schools.

And as this resistance takes place, there are debates over the tactics 策略 and the philosophies amongst civil rights leaders. They start to question what is the best path to achieve their goals. So you start to get more radical voices 激进声音 in the civil rights movements -- people like Stokely Carmichael associated with the Black Power movement 黑人权力运动, Malcolm X and the Nation of Islam 伊斯兰民族组织, and the Black Panthers 黑豹党 out in Oakland. They start to kind of be known as the black radicalism 黑人激进主义 -- the Black Power movement -- who call for much more aggressive action 更激进行动.

There are other civil rights movements which are inspired by the African-American civil rights movement. You have women taking on more vocal opposition 更强烈反对 -- kind of sparked with The Feminine Mystique's publication and then you get people like Betty Friedan forming organizations such as the National Organization for Women 全国妇女组织. You have the American Indian Movement 美国印第安人运动 and Latinos such as Cesar Chavez and the United Farm Workers Union 联合农场工人联盟. And the rise of the gay rights movement 同性恋权利运动 with the Stonewall Riots 石墙骚乱 in 1969. So make sure you know about the variety of civil rights movements taking place and especially how they played a role in the 1960s.

And you can't talk about the 1960s without talking about Lyndon Johnson's Great Society 伟大社会. This is really seen as the height of liberalism 自由主义高峰. And the Great Society dramatically increased the size and the scope 范围 of the federal government. In many ways, the Great Society is a continuation of the New Deal programs, but whereas the New Deal was primarily focused with ending the Great Depression, the Great Society is going to go much further. It was this idea -- this liberal idea -- that government power can be used to fix societal problems.

And you're going to see a variety of programs like Medicare 医疗保险 -- those over 65 could get health care. Medicaid 医疗补助 -- health care for the poor and disabled. Job Corps 职业培训团 -- vocational education 职业教育. A big act you should know about -- the Immigration and Nationality Act of 1965 移民与国籍法案 which basically wipes out those quotas from the 1920s which allows for people especially people from Latin America and Asia to come into the United States in much greater numbers.

The two other big ones are the Civil Rights Acts -- the Civil Rights Act of 1964 which basically declared segregation illegal in all public facilities, and the Voting Rights Act of 1965 which basically wiped out all of those things that were used to prevent African-Americans from voting in the South such as the literacy test 识字测试. So whereas the New Deal kind of ignored or overlooked race relations 种族关系, the Great Society made it a huge focus of its platform.

During this time you also have Earl Warren -- the Warren Supreme Court 沃伦法院 -- which are going to rule on a variety of cases which are going to expand democracy and individual liberty. There is of course a conservative reaction 保守派反弹. You could see that really in the election of 1964 with Barry Goldwater -- even though he gets his butt kicked 惨败 against Lyndon Johnson. And conservatives criticize the Great Society and other liberal programs as too costly, inefficient, too idealistic. They created dependency 依赖性 on people, and so they were very vocal.

Barry Goldwater kind of begins this modern conservative movement 现代保守主义运动. He loses the election, but that movement continues into the late '60s. You get Nixon winning in 1968, and although he's not a hardcore social conservative 强硬社会保守派, Nixon wins as a Republican in '68. And you're going to see the conservative movement grow in the '70s and eventually in the '80s.

Which leads us to the '70s. Few things you should know about -- there is a huge distrust of the government 政府信任危机 in the 1970s. And there's a lot of reasons for it. You know the failures of the Vietnam War -- like did we actually get attacked at the Gulf of Tonkin 东京湾事件? Why did they say the war is almost over and then the Tet Offensive have happened? Why is Nixon bombing Cambodia? And the revelation of some of these things in the Pentagon Papers 五角大楼文件 makes a lot of individuals distrust the federal government.

The Watergate scandal 水门事件 fuels that fire of government distrust where Nixon is found to be doing some things that are not exactly on the up and up 光明正大, and he is ultimately forced to resign 被迫辞职. And Gerald Ford becomes the first unelected president 非民选总统 in our nation's history. You have the Iran Hostage Crisis 伊朗人质危机 and Jimmy Carter's inability to handle that effectively. All of these things and others lead to a distrust of the government.

And of course in the '70s there is an economic slowdown 经济放缓. You have something called stagnation 停滞 and high inflation 高通胀 which becomes known as stagflation 滞胀. So the economy is kind of sputtering forward 艰难前行 in the 1970s which leads to a lot of unhappiness. And that leads us to the 1980s and the rise of the conservative movement.

There's a lot of reasons for it. You have the rise of the religious fundamentalists 宗教原教旨主义者 who are worried about all these social changes -- the rise of feminism 女权主义, the legalization of abortion 堕胎合法化. And religious fundamentalists start to organize. You got a lack of faith in government which we just mentioned. And then you got economic concerns -- they start rejecting the deficits 赤字 of the New Deal and the Great Society and other liberal programs. They don't trust the government to solve society's problems. And Reagan kind of rides this conservative movement to election in 1980.

There are some conservative victories under Reagan. He does initiate tax cuts 减税 especially for the wealthy -- this idea of trickle down economics 涓滴经济学 -- Reaganomics 里根经济学. There is the continued deregulation 放松管制 of many industries. And entitlement spending 福利支出 is decreased -- things on like welfare 福利 and food stamps 食品券 -- those programs are cut in the '80s.

There are limits to the conservative movement you should know about. You know programs such as Social Security 社会保障 from the New Deal days and Medicare during the Great Society remained. They were popular with voters, and nobody -- Republican or Democrat -- want to mess with them because the voters will be angry. And in spite of all this kind of criticism of big government, the government remained big under Reagan because of defense spending 国防开支 and tax cuts. So you have a huge federal deficit 联邦赤字 in the '80s.

Some foreign policy stuff you should know -- and we're almost done -- remember the Cold War ends in 1991. The Soviet Union basically falls apart 解体 for a lot of reasons for that. And the post-Cold War foreign policy environment is going to probably be even more complicated than the days of the big Soviet boogeyman 苏联威胁 being out there. And that is really kind of marked by the terrorist attacks on 9/11 911事件 in 2001. This begins the War on Terror 反恐战争.

Following the attacks on 9/11, you have a war that takes place in Afghanistan. You have a war in Iraq. And this has also impacts on the homefront. Congress passes the Patriot Act 爱国者法案 signed by President George Bush. And once again you have debates over the impact on civil liberties -- how far should we go to investigate potential terrorist attacks?

All right, APUSH friends. I try to make it quick, but I know that's a lot of information. There's a ton of review videos on the channel -- check them out. Check out our Period 6 through 9 review videos. Check out the website apushexplained.com -- it's the hottest site on Earth. Tons of chapter review videos, all sorts of review sheets, key concepts. And if you haven't already done so, subscribe to Jocz Productions. Good luck on your test in May -- you're going to rock it 表现出色. Remember -- take the test, don't let the test take you. If you would do me a solid 帮个忙, pay it forward 传递下去 until next year's APUSH crew. Check out Jocz Productions and APUSH Explained. Thank you for watching -- have a beautiful day. Peace.

'''


== 中文翻译

大家好，APUSH的同学们！今天我们来分析历史时期，试图理清美国历史中所有这些不同的时期。我们将重点关注第6至第9时期——大致从1860年代到当代美国。

我们首先从镀金时代开始。请记住，这并没有一个正式的开始日期，但我们指的是大约从1870年代到1900年。在镀金时代，表面上一切看起来都非常好和令人惊叹——你们有工业化——但在表面之下存在许多问题。你们知道，工业革命正在进行，这实际上在1860年代的内战中开始，美国社会经历了快速的经济转型。像卡内基和洛克菲勒这样的人在钢铁和石油领域建立了产业。这是工业资本主义的兴起——主要产业——制造业的水平比以前高得多。因此，制造业取代了农业，在工业革命期间发生了许多技术变革。

正在发生人口迁移——人们正在搬到城市地区。事实上，到1920年，大多数美国人将居住在城市地区。随着这些迁移，人们涌入美国——移民数量大幅增加。来美国的人的构成也发生了变化。你们看到了新移民的崛起，尤其是在1890年代，他们来自南欧和东欧国家，如意大利、波兰和俄罗斯。亚洲移民，特别是来自中国的移民也大幅增加。

随着移民构成的这种变化，在镀金时代，本土主义情绪将会增加。你们将看到这体现在1880年代的《排华法案》以及禁止或限制来自南欧和东欧移民的努力等事件中。你们将在1920年代的配额制度中看到这一点。你们知道，记住在这个时期，工人们正在组织成立全国性的工会。你们在粉红色和红色五角星标记的所有区域都将是罢工发生和各种工会成立的地方。

你们有劳工骑士团——他们关注非熟练和熟练工人。他们对各种不同类型的工人更加开放，而由塞缪尔·冈珀斯领导的美国劳工联合会则完全关注熟练工人的实际问题。因此，工人们正在应对镀金时代工业化带来的问题。

农民也对农业机械化和铁路行业的控制做出了反应。他们正在组织起来，试图反击其中的一些挑战。1890年代将出现一场大型运动——人民党，更常被称为民粹党。他们希望政府在监管经济体系方面发挥更强大的作用。他们想要监管铁路行业的法律，他们想要参议员的直接选举，他们想要自由铸造银币。他们将推举你们的朋友托马斯·沃森竞选总统。他将失败，但至少在1890年代，他们是一支重要的力量。

这些是镀金时代的一些主要主题和事件。你们知道，表面上看起来不错，但在表面之下存在一些挑战。关于工业革命，你们还应该了解几件事，那就是普遍存在着自由放任的信念——政府不应该试图控制或监管商业。这显然是富人和商业精英所倡导的——他们不希望政府干预他们对利润的追求。许多人倡导诸如社会达尔文主义——适者生存——这样的思想，这为财富的集中提供了理由。富人变得更富有是因为他们更优秀——他们理应富有。他们将达尔文的进化论应用于新的工业世界。所以确保你们了解社会达尔文主义。

这个时期有一些监管的例子。你们看到了它的开端——你们在1887年有了《州际商务法》，它监管铁路运费。最初它很弱，但这是一个开端。这是农民倡导的。这是政府开始监管工业的开端。你们在1890年有了《谢尔曼反托拉斯法》——我们如何监管这些垄断企业，这些托拉斯？再一次，最初非常弱，但这是政府监管的开端。

与此同时，在这个时期——1870年代到1890年代——你们有被称为新南方的东西。南方正在工业化。人们主张我们应该转向更工业化的经济。尽管有这种主张，分成制和佃农制仍然是南部各州主要的经济活动。你们将看到重建后的吉姆·克劳法在南部各州得到加强，并通过普莱西诉弗格森案的裁决被认为是合宪的。

现在，与此同时，你们也正在经历西进运动。这在美国历史上是一个常见的主题，但我们在这个时期谈论的西进运动——大约是1860年代到1890年代——是密西西比河以西的地区。你们将看到更多移民涌向西部，寻求土地和经济机会，这经常导致竞争和暴力冲突。这实际上将受到美国联邦政府的鼓励。他们将鼓励这种西进运动。

联邦政府作用的一个例子是1862年的《宅地法》，政府向西迁的定居者提供免费或廉价的土地。你们在1862年有了《太平洋铁路法》，该法案允许政府规划第一条横贯大陆铁路的路线。其中一个重要部分是政府补贴——给予铁路公司的税收减免，以建设你们在地图上看到的铁路网络。

现在重要的是要注意——随着西进运动而来的是对当地居民生活的破坏和侵犯。这将采取许多不同的形式。你们将看到野牛数量的迅速下降——为了削弱美洲原住民的反抗，它们将被系统地屠杀。你们将经历一系列印第安战争——你们可以在地图上看到那些红色五角星是一些主要的战争。当然，最后一次主要的印第安战争发生在1890年的伤膝河。

国会还在1887年通过了《道斯分配法》，该法案实际上结束了部落对土地的所有权。美国政府的目标是同化政策——让我们把美洲原住民从部落土地、公有土地上迁走，让他们拥有私有财产，并将他们美国化。这是《道斯法》的目标之一。确保你们了解这一点。

这个人弗雷德里克·杰克逊·特纳——1893年——写了《边疆在美国历史上的意义》。他基本上宣布边疆已经关闭。印第安战争即将结束，大陆基本上从东海岸到西海岸都已定居。这种边疆关闭的思想引领我们进入美国历史的另一个时期——美国扩张时期。这大约是1890年代到1914年。

我知道你们在想什么——自从大西洋沿岸那小小的13个殖民地时代以来，美国一直在扩张。但这不同——这是海外扩张。发生这种情况的原因之一——原因之一是1890年代边疆关闭了，所以唯一剩下的去处就是国外，就是海外。你们还应该了解其他原因——获得商品市场和廉价原材料的经济渠道。记住，工业革命正在进行——如果我们找不到新的市场和新的廉价原材料，我们如何维持这种增长？

美国扩张也有政治动机——我们想与其他国家竞争，特别是欧洲国家以及全球范围内日本的崛起。也有军事原因——像阿尔弗雷德·T·马汉这样的人主张建立一支强大的海军。因此，你们需要在全球范围内拥有岛屿作为海军基地。最后，还有意识形态方面的原因——你们知道，传播盎格鲁-撒克逊文明、传播民主、传播基督教的思想。

这采取了多种形式，但所有这些不同的因素，包括边疆的关闭，都促成了1890年代美国的扩张。你们应该了解许多例子——你们有夏威夷的吞并。记住，夏威夷在地理上将具有重要意义——战略意义——但威廉·麦金莱吞并它也有经济动机。

你们在中国有门户开放政策——想要获得贸易机会，摆脱欧洲和日本的势力范围。你们有1898年的美西战争——极其重要——辉煌的小战争——我们与西班牙作战四个月，最终吞并了古巴、波多黎各、关岛和菲律宾。你们可以在地图上看到其中的一些领土。

紧随其后的是一场针对菲律宾的残酷战争，由埃米利奥·阿吉纳尔多领导的菲律宾抵抗运动发起。他们不希望美国接管他们，菲律宾奋起反抗，这是一场致命的残酷战争。当然，你们还有西奥多·罗斯福和他的大项目——巴拿马运河——他还在门罗主义中加入了罗斯福推论，声称我们将成为西半球的警察和监管者。

记住，并非所有人都同意这一点。你们有帝国主义者（赞成扩张的人）和反帝国主义联盟（反对这种扩张并批评美国在国外的努力）之间的辩论。确保你们知道这种扩张不仅发生在麦金莱、罗斯福的政府时期，还发生在威廉·霍华德·塔夫脱和伍德罗·威尔逊的政府时期。他们将发挥更积极的作用。他们将以各种方式这样做。因此，了解这些年美国扩张的一些例子。

这引领我们进入美国历史的下一个时期——进步运动，它实际上大约从1890年代开始，一直到1920年左右。这与一些其他事件同时发生，但这是一个真正的国内运动。它是政府权力监管和改善社会。人们认为存在许多需要解决的问题，这是对自由放任意识形态的否定——政府需要发挥作用。

你们有各种各样的揭发记者开始揭露问题。你们有各种各样的运动正在发生。最终，这场运动——进步运动——将导致改革。一些经济方面的例子是西奥多·罗斯福、塔夫脱和威尔逊时期的反托拉斯行动。他们将开始加强《谢尔曼反托拉斯法》，并拆散所谓的“坏托拉斯”。

你们将有监管肉类工业的《肉类检验法》，监管药品和食品工业的《纯净食品和药品法》，以及罗伯特·拉福莱特的威斯康星理念，我们将监管铁路工业和其他大企业。在进步运动期间，还将努力扩大民主。你们将在为参议员直接选举提供保障的第17修正案以及像罢免、创制、直接初选等改革中看到这一点。当然，一场非常活跃的妇女选举权运动已经持续了相当长一段时间，并在1890年代和20世纪初获得了发展势头。

记住，进步运动是各种运动的集合——因此，并非所有争取妇女选举权的人都在争取其他这些领域。妇女将在进步运动中发挥巨大作用，特别是中产阶级白人妇女，尤其是在城市地区，而民粹主义运动是农民——进步人士是城市居民。

在进步运动期间，你们还将看到道德改革。存在着主张禁酒的反沙龙联盟，他们最终将通过禁止酒精的第18修正案。当然还有环境保护运动——你们将看到这场运动的各个分支——由约翰·缪尔领导的想要保持自然纯净的自然保护主义者，以及由西奥多·罗斯福和吉福德·平肖领导的保护主义者，我们将为后代管理自然资源。

再次强调，进步运动将跨越多个总统任期。因此，不仅是西奥多·罗斯福，塔夫脱和威尔逊都将在国家层面寻求改革。他们将取得不同程度的成功。正如你们将看到的伍德罗·威尔逊，他们不愿支持某些改革，例如妇女选举权，妇女必须对他施加很大的压力才能最终实现第19修正案。

第一次世界大战在某种程度上中断了这场国内改革运动。进步时代实际上始于1914年，并将持续到1918年。确保你们知道，最初美国承诺保持中立。威尔逊试图让美国置身于第一次世界大战之外，但由于各种原因，我们最终将在1917年参战。其中一个原因是意识形态方面的——威尔逊希望参与战后谈判。他想让世界对民主安全，因此他希望在条约签署时坐在谈判桌旁。

你们看到了对美国中立的侵犯——记住英国船只卢西塔尼亚号的沉没——美国人的生命丧生。你们看到了齐默曼电报，德国试图与墨西哥勾结并对美国宣战。而且我们向盟军提供了大量资金，因此我们在他们的胜利中拥有经济利益。

我们确实参战了，最终美国帮助赢得了那场战争。威尔逊将积极参与战后谈判。确保你们了解他的十四点原则——他对未来的规划以及他试图阻止未来战争的计划。其中一个重要部分是国际联盟——这个将阻止未来战争发生的国际组织。

然而，最终国会否决了国际联盟。共和党控制的国会不愿背离乔治·华盛顿的警告和告别演说，因此他们说我们要置身事外。这对许多人来说标志着美国孤立主义的回归——我们希望置身于欧洲事务之外，或者只在我们想参与时才参与。

第一次世界大战期间国内的影响——有几件重要的事情你们应该强调。一是大迁徙——非裔美国人从南方到像纽约这样的北方城市的大规模迁移实际上发生在第一次世界大战之前，但第一次世界大战加速了这一进程。然后当然是公民自由的侵犯——你们有《煽动叛乱法》，该法实际上对言论自由施加了很多限制，以及申克诉美国案，该案认为，只要言论构成明显的现实危险，就可以对其进行限制。因此，你们再次看到了公民自由和安全以及两者之间平衡的主题。

第一次世界大战结束后，进步运动逐渐消退，你们迎来了每个人都喜欢研究的时期——咆哮的二十年代。咆哮的二十年代经历了巨大的经济和文化变革。这是一个充满变革的十年。你们有了像收音机、汽车等新的技术，这些技术变得负担得起或首次被发明出来，这极大地提高了许多美国人的生活水平。

不仅如此，由于人们能够使用像分期付款这样的新的支付方式购买商品，因此出现了大众消费。广告和广告业的发展让人们意识到他们想要很多他们现在可能买不起的东西。

你们绝对需要了解1920年代的另一个方面是冲突——许多不同的冲突。你们有土生土长的美国人和移民之间的冲突。记住，人们对那些南欧和东欧移民有反感。事实上，在第一次世界大战结束后，你们将经历所谓的“红色恐慌”，每个人都非常害怕美国会发生革命，我们将被布尔什维克、共产主义者、无政府主义者和所有这些东西所淹没。

帕尔默突袭开始逮捕人们，不管他们是否真的做错了什么。你们有著名的萨科和凡泽蒂审判，那些家伙没有得到任何公正的审判，因为他们是意大利人，他们是无政府主义者，他们是逃兵，他们最终被处死。你们通过了配额法案——最重要的是1924年的法案，该法案基本上规定，只有1890年移民人数的2%可以入境，其目的是限制来自南欧和东欧的移民。

你们看到的另一个冲突是倾向于居住在农村地区的宗教原教旨主义者和倾向于居住在城市的更现代思想之间的冲突。这体现在各种领域，例如斯科普斯案，一名教师因教授进化论而惹上麻烦。你们有第18修正案，这不仅仅是一个宗教问题，但许多宗教原教旨主义者赞成禁止酒精。正如你们所见，犯罪率上升，像阿尔·卡彭这样的人出现，这并没有那么顺利。

然后还有各种各样的其他冲突，你们应该让自己有所了解，例如三K党的崛起——这与反移民的本土主义的兴起有关。你们有迷惘的一代——一群对1920年代的消费主义和其他正在发生的事情感到幻灭的作家和艺术家。你们有哈莱姆文艺复兴，这是黑人文化的繁荣和对在美国成为黑人的庆祝。因此，咆哮的二十年代——比仅仅是时髦女郎和饮用非法酒精的年代要复杂得多。

这引领我们进入大萧条时期。大萧条始于1929年。在整个1920年代，股市表现非常好，所有这些都在1929年10月29日——黑色星期二——崩溃了。这是大萧条的开始。大萧条有很多原因——股市只是其中之一。

胡佛试图找出解决办法，但做得不够，并在选举中输给了富兰克林·罗斯福。1933年他上任，这是新政时期。富兰克林·罗斯福——罗斯福总统——相信他的新政计划，他认为这将为美国人民提供救济、复苏和改革。这改变了联邦政府的角色，并创建了现代福利国家。

你们知道，他们喜欢问一些比较和对比新政与进步运动的问题。它们有一些共同之处，那就是都反对自由放任主义。你们应该了解几件事——一些项目：联邦存款保险公司——确保人们的银行存款（至今仍然存在）。社会保障管理局基本上提供了现代安全网——福利国家——保护老年人、失业者和有受抚养子女的妇女。

你们在1935年有了《瓦格纳法案》，该法案基本上首次规定联邦政府承认工会有存在的权利，并且联邦政府将支持他们集体谈判的权利。关于新政存在争议。你们知道，有些人想限制它或将其撤销。最高法院宣布一些新政项目违宪——全国复兴管理局和农业调整管理局。罗斯福试图推行他的“法院改组计划”，并遭遇了一次罕见的政治失败。

共和党人和保守派不喜欢新政，因为他们不喜欢自由主义的兴起——这个庞大的政府。还有一些人想扩大新政——像休伊·朗这样的人，他想采取某种社会主义计划——“人人为王”，分享我们的财富。他将被枪杀，所以这行不通。但关于新政存在争议。

记住，影响是巨大的。出现了一个新政民主联盟——一个由农民、城市移民、工会成员、非裔美国人和妇女等群体组成的联盟，由于富兰克林·罗斯福的新政政策，他们开始大规模地投票给民主党。它确立了联邦政府对社会的责任——这种安全网的思想。在美国，直到新政时期才确立这一点。这是民主党代表的自由主义在这个时期开始或兴起的标志。

但记住，新政并没有结束大萧条。最终是第二次世界大战结束了大萧条。这个时期大约在1939年结束，因为世界的注意力和国家的注意力都转向了1939年至1945年发生的第二次世界大战。

在1939年至1941年初，我们基本上试图置身事外——就像我们在第一次世界大战期间所做的那样。有一系列事情慢慢地让我们越来越深地卷入其中。你们有《中立法案》，我们不向任何交战国出售武器，我们也不乘坐他们的船只。但正如你们在那幅政治漫画中看到的，英国陷入困境，因此我们开始采取像“现金与运输”和“租借法案”这样的政策。我们慢慢地帮助盟军，因为我们不希望他们输给这些极权主义政府。

好吧，随着1941年12月7日日本袭击珍珠港，中立结束了。我们现在处于第二次世界大战中。第二次世界大战对国内的影响是巨大的——确保你们了解这一点。最重要的是日裔美国人和日本人的拘留——基本上公民自由被剥夺。超过10万日裔人士被送往全国各地的10个拘留营之一。这是对他们公民自由的严重侵犯，也是美国和美国历史的耻辱。

第二次世界大战期间发生了大规模的动员——社会各界都在动员起来帮助赢得战争——美国工厂、工会等等。战争对社会产生了各种各样的影响。你们有非裔美国人的“双重胜利”运动——在国外战胜暴政，在国内战胜种族主义。你们有女性在战争中发挥积极作用，罗斯ie the Riveter象征着这一点。你们还有所谓的“布雷塞罗计划”，墨西哥人被带到美国工作，以弥补尤其是在农业等领域的劳动力短缺。因此，了解第二次世界大战对国内的影响。

当然，最终盟军将获胜。我们实力雄厚，但当然最重要的是苏联、美国和英国。这有很多原因——一是美国的工业生产——我们生产了大量的武器和物资来帮助对抗轴心国。你们有了新技术，当然最重要的是曼哈顿计划——英国和美国之间的秘密计划，开发了原子弹，这将最终结束第二次世界大战。三大同盟——丘吉尔、斯大林和罗斯福及其关系和合作的重要性将有助于击败轴心国。

重要的战役——在诺曼底和法国北部D日等地的军事成功——第二战线的开辟。以及跳岛战术，基本上美国试图足够靠近日本，以便入侵或轰炸该国。最终将是原子弹结束第二次世界大战——一个备受争议的话题，对此问题有不同的看法。我强烈建议你们形成自己的观点。

但随着第二次世界大战的结束——一个重要的观点——美国成为一个超级大国。我们崛起成为世界上最具统治力的国家之一。这引领我们进入下一个时期——冷战。冷战没有开始日期——它将从1945年持续到1991年。基本上，冷战是美国和苏联之间意识形态、政治和军事的斗争。它真正开始在1947年升温，美国在整个冷战期间的目标是遏制共产主义。

共产主义已经在东欧存在——我们不喜欢那样。记住雅尔塔协定——我们认为斯大林会撤走那些军队——但他没有。一位名叫乔治·凯南的人提出了这项遏制政策。遏制有很多例子——这里有一些：杜鲁门主义——我们将向希腊和土耳其提供资金，以确保它们不会落入共产主义者手中，它们也没有。马歇尔计划——我们将向西欧提供大量资金以帮助重建，以便这些国家不会转向共产主义——它们也没有。

你们将拥有北约——北大西洋公约组织——这是集体安全的一个例子。所有绿色国家都属于北约。这是我们的第一个永久性军事联盟，并且至今仍然存在。其他遏制的例子变得有点混乱。在朝鲜，我们阻止了朝鲜对韩国的进攻，从而维护了韩国的非共产主义地位。我们试图阻止越南的共产主义，但这有点混乱，因为它实际上是共产主义和民族主义运动的混合体。他们想摆脱法国，然后他们想摆脱我们，最终美国在越南的表现并不好。

美国和苏联在对抗时期（我们在全球各地都有冲突）和缓和时期（或互相共存或紧张局势缓和）之间波动。一些冲突的例子——你们有柏林封锁，杜鲁门通过柏林空运对抗斯大林。古巴导弹危机——整个世界几乎毁灭。幸运的是，肯尼迪和赫鲁晓夫——更冷静的头脑占了上风。但在整个冷战期间，你们将看到我们关系缓和或紧张局势放松的例子——艾森豪威尔时期的日内瓦精神，我们开始互相交谈，尼克松时期与苏联的第一次削减战略武器条约。当然——当然——尼克松是在1970年代开启我们与中国关系的家伙。

关于冷战，你们还应该了解几件事。在冷战期间，美国有时会支持非民主政府。例如，中央情报局将在艾森豪威尔执政的1950年代推翻或帮助推翻伊朗和危地马拉的政府。在这两种情况下，取代我们帮助推翻的政府的新政府对当地人民或民主并不完全友好。然而，我们支持他们，因为他们是非共产主义者。还有其他例子——你们将在南越看到对非民主政府的支持，尽管迪姆政府腐败且缺乏民众支持，但艾森豪威尔和肯尼迪都支持该政府。

冷战时期的另一个重要思想是公民自由与安全之间的斗争。冷战期间存在一种恐惧——事实上，在40年代末和50年代初出现了第二次红色恐慌。这体现在众议院非美活动调查委员会开始调查共产主义影响，以及参议员约瑟夫·麦卡锡和麦卡锡主义的崛起。事实上，有一些共产主义间谍——你们有阿尔杰·希斯和罗森堡夫妇——但这种恐惧变成了一种偏执，许多人的公民自由在此过程中遭到侵犯。

关于军备竞赛存在争议。我们正在与苏联竞争——谁能建立更大的武库？艾森豪威尔在他的告别演说中著名地警告国家警惕军事工业复合体。人们有意识地担心这些可怕武器的扩散，你们将在整个冷战期间看到或至少试图达成军备控制协议。

冷战将导致一些争议。你们将看到著名的反对越南战争的反战抗议活动。在1968年春节攻势之后，这场抗议活动规模急剧扩大，人们意识到这场战争远未结束。在尼克松政府秘密轰炸柬埔寨的真相被揭露之后，最终这将……最终，其中一次抗议活动将以肯特州立大学的枪击事件告终。

在尼克松政府秘密轰炸柬埔寨的真相被揭露后，更多的抗议活动爆发了。在这场抗议浪潮中，国民警卫队在肯特州立大学向抗议者开枪。

快速看一下国内发生的一些事情。1950年代通常被视为保守或自满的十年。有很多机会将其与1920年代进行比较，因为你们会发现很多相似之处。艾森豪威尔是总统——二战英雄。他是一位温和的共和党人，所以你们不会看到大规模的改革。没有大规模的自由主义议程。但美国发生了很多变化。相对而言，对于许多人来说，这是一个经济繁荣的十年——但并非所有人。

你们将看到中产阶级的壮大。二战后经济——随着经济转型，中产阶级大幅增长。你们有了越来越多的白领工人——所以人们不再在工业工厂工作，而是从事更多白领类型的工作。二战后，你们还看到了人口大规模向郊区迁移——著名的莱维敦。在40年代末和50年代初，你们经历了巨大的婴儿潮。信用卡在这个十年被引入，这导致消费主义的增加。电视在1950年代成为常见的家庭用品，并在某种程度上导致了美国文化的传播和发展。

但你们应该意识到1950年代存在一些紧张局势。这些就是其中一些。贝蒂·弗里丹写了《女性的奥秘》——它实际上是在1960年出版的，但它确实谴责了女性在美国社会中受到的待遇以及女性扮演快乐郊区家庭主妇角色的期望。你们将在随后的几年里看到女权运动的发展。

垮掉的一代——一群艺术家——批评1950年代的顺从。当然，这个十年并非充满自满的一个重要例子是民权运动，它在1950年代真正获得了巨大的动力。所以让我们快速看一下民权运动。

你们知道，这没有一个确切的开始日期，但你们知道，民权活动家利用法律挑战、非暴力和直接行动来实现他们的目标，并试图推翻当时存在的吉姆·克劳制度。正如你们在那张照片中看到的，没有一个单一的开始——二战时期你们看到了“双重胜利”运动。像种族平等大会这样的组织开始兴起。在1950年代，1954年，你们有了布朗诉教育委员会案——这推翻了隔离——裁定学校隔离本质上是不平等的。

非暴力和直接行动的其他例子可以在1955年罗莎·帕克斯被捕引发的蒙哥马利巴士抵制运动，以及肯尼迪政府时期或在其领导下的1961年自由乘车运动中看到。因此，这场运动在二战中真正获得了动力，在50年代发展壮大，然后在60年代爆发。

你们应该记住的一个重要思想是，政府的三个部门最终都在推动民权事业方面发挥了作用。起初他们行动缓慢，但在巨大的压力下，我们最终开始看到一些变化。行政部门在这项变革中的作用可以追溯到1948年杜鲁门取消军队中的种族隔离——为此他承受了很大的压力。司法部门的变化可以在布朗诉教育委员会案中看到，该案推翻了普莱西诉弗格森案。立法部门的变化可以在1964年的《民权法案》和1965年的《投票权法案》中看到——我们将在稍后介绍这两项法案——这两项法案都由林登·约翰逊总统签署。

民权运动——不仅仅是非裔美国人民权运动，还有很多其他运动。但记住，尤其是在南部各州，对这些变革存在着强烈的白人抵制。你们有反对布朗裁决的南方宣言，其中100多名南方国会议员基本上表示法院——最高法院——滥用了权力。你们有小石城九人事件，州长奥维尔·福布斯阻止他们进入学校。

随着这种抵抗的发生，民权领袖之间在策略和哲学上存在着争论。他们开始质疑实现目标的最佳途径是什么。因此，民权运动中开始出现更激进的声音——像与黑人权力运动相关的斯托克利·卡迈克尔，马尔科姆·X和伊斯兰民族，以及奥克兰的黑豹党。他们开始被称为黑人激进主义——黑人权力运动——他们呼吁采取更激进的行动。

其他民权运动也受到非裔美国人民权运动的启发。女性开始发出更响亮的反抗声音——这在某种程度上是由《女性的奥秘》的出版引发的，然后你们看到了像贝蒂·弗里丹这样的人成立了像全国妇女组织这样的组织。你们有美国印第安人运动和像塞萨尔·查韦斯和联合农场工人联合会这样的拉丁裔。以及1969年石墙骚乱标志的同性恋权利运动的兴起。因此，确保你们了解正在发生的各种民权运动，特别是它们在1960年代发挥的作用。

如果不谈论林登·约翰逊的伟大社会，就无法谈论1960年代。这真正被视为自由主义的顶峰。伟大社会极大地增加了联邦政府的规模和范围。在许多方面，伟大社会是新政计划的延续，但新政主要关注结束大萧条，而伟大社会将走得更远。这是一种理念——一种自由主义的理念——认为政府权力可以用来解决社会问题。

你们将看到各种各样的项目，例如医疗保险——65岁以上的人可以获得医疗保健。医疗补助——为穷人和残疾人提供医疗保健。就业培训队——职业教育。你们应该了解一项重要的法案——1965年的《移民和国籍法》，该法案基本上废除了1920年代的配额制度，使得尤其是来自拉丁美洲和亚洲的人们能够以更大的数量进入美国。

另外两项重要的法案是《民权法案》——1964年的《民权法案》，该法案基本上宣布在所有公共设施中的种族隔离为非法，以及1965年的《投票权法案》，该法案基本上废除了所有那些过去用来阻止南方非裔美国人投票的手段，例如文化程度测试。因此，新政在某种程度上忽视或忽略了种族关系，而伟大社会则将其作为其纲领的一个重要重点。

在此期间，你们还有厄尔·沃伦——沃伦最高法院——他们将对各种案件作出裁决，这些裁决将扩大民主和个人自由。当然，存在保守派的反弹。你们可以在1964年巴里·戈德华特的选举中真正看到这一点——尽管他被林登·约翰逊击败了。保守派批评伟大社会和其他自由主义计划过于昂贵、效率低下、过于理想化。它们造成了人们的依赖性，因此他们非常直言不讳。

巴里·戈德华特在某种程度上开启了现代保守主义运动。他输掉了选举，但这场运动持续到60年代末。尼克松在1968年获胜，尽管他不是一个铁杆的社会保守主义者，但尼克松在1968年以共和党人的身份获胜。你们将看到保守主义运动在70年代发展壮大，并最终在80年代达到顶峰。

这引领我们进入70年代。你们应该了解几件事——在1970年代，人们对政府极度不信任。这有很多原因。你们知道越南战争的失败——比如我们在东京湾真的遭到袭击了吗？为什么他们说战争几乎结束了，然后发生了春节攻势？为什么尼克松轰炸柬埔寨？五角大楼泄密事件揭露了其中的一些事情，这让很多人不信任联邦政府。

水门丑闻火上浇油，加剧了人们对政府的不信任，尼克松被发现做了一些不正当的事情，他最终被迫辞职。杰拉尔德·福特成为我们国家历史上第一位未经选举产生的总统。你们经历了伊朗人质危机以及吉米·卡特未能有效处理此事。所有这些以及其他因素导致了对政府的不信任。

当然，在70年代，经济也出现下滑。你们经历了所谓的滞胀，即经济停滞和高通货膨胀并存。因此，1970年代的经济发展有些停滞不前，这导致了很多不满。这引领我们进入1980年代和保守主义运动的兴起。

这有很多原因。你们看到了宗教原教旨主义者的崛起，他们担心所有这些社会变革——女权主义的兴起，堕胎合法化。宗教原教旨主义者开始组织起来。我们刚才提到过，人们对政府缺乏信任。然后你们看到了经济方面的担忧——他们开始反对新政和伟大社会以及其他自由主义计划造成的赤字。他们不相信政府能够解决社会问题。里根在某种程度上借助这场保守主义运动在1980年当选总统。

在里根领导下取得了一些保守派的胜利。他确实推行了减税政策，尤其是针对富人——涓滴经济学——里根经济学。许多行业持续放松管制。福利支出减少了——例如福利和食品券——这些项目在80年代被削减。

你们应该了解保守主义运动的局限性。你们知道，新政时期的社会保障和伟大社会时期的医疗保险等项目仍然存在。它们受到选民的欢迎，没有人——共和党或民主党——愿意触动它们，因为选民会愤怒。尽管人们对大政府进行了各种批评，但在里根领导下，由于国防开支和减税，政府规模仍然很大。因此，你们在80年代面临巨大的联邦赤字。

你们应该了解一些外交政策方面的事情——我们快完成了——记住冷战在1991年结束。苏联基本上由于多种原因而解体。后冷战时期的外交政策环境可能比过去那个巨大的苏联恶棍存在的时代更加复杂。这实际上以2001年9月11日的恐怖袭击为标志。这开始了反恐战争。

在911袭击之后，你们看到了阿富汗战争。你们看到了伊拉克战争。这对国内也产生了影响。国会通过了由乔治·布什总统签署的《爱国者法案》。你们再一次就对公民自由的影响展开辩论——我们在调查潜在的恐怖袭击方面应该走多远？

好了，APUSH的朋友们。我尽量简短，但我知道信息量很大。频道上有很多复习视频——去看看吧。看看我们的第6到第9时期的复习视频。https://www.google.com/search?q=%E7%9C%8B%E7%9C%8B%E7%BD%91%E7%AB%99apushexplained.com——这是地球上最火的网站。大量的章节复习视频，各种复习资料，关键概念。如果你们还没有订阅，请订阅Jocz Productions。祝你们五月份的考试好运——你们会成功的。记住——参加考试，不要让考试控制你们。如果你们能帮我一个忙，请把这份帮助传递给明年的APUSH考生。看看Jocz Productions和APUSH Explained。感谢收看——祝你们度过美好的一天。再见。

'''


== pure

What's up, APUSH people? Today we're breaking down the historical time periods, trying to make sense of all these different periods in American history. We're going to focus on periods 6 to 9 -- roughly the 1860s all the way to contemporary America.

So we start off with the Gilded Age. And keep in mind this kind of doesn't have a start date officially, but we're going from around the 1870s to 1900. And in the Gilded Age, on the surface everything appears to be really good and amazing -- you have industrialization -- but there's lots of problems beneath the surface. You know, you have Industrial Revolution going on that really kind of kicks off with the Civil War in the 1860s, which you have rapid economic transformation of American society. People like Carnegie and Rockefeller building up industries in steel and oil. This is the rise of industrial capitalism -- major industry -- and you have manufacturing taking place at a much greater level than before. So manufacturing was replacing agriculture, and you have lots of technological changes going on during the Industrial Revolution.

You have migrations taking place -- people are moving to urban areas. In fact, by 1920 you're going to have the majority of Americans living in cities in urban areas. With these migrations, you have people coming into the United States -- huge increase in immigration. And there's changes of who's coming to America. You have the rise of the new immigrants, especially in the 1890s, from Southern and Eastern European countries like Italy and Poland and Russia. And you have spikes in Asian immigration, especially from China.

With this change in immigration, you're going to have nativism increasing during the Gilded Age. And you're going to see this manifest itself in things like the Chinese Exclusion Act in the 1880s and efforts to ban or limit immigrants from Southern and Eastern Europe. And you're going to see that in the 1920s with the quotas. You know, keep in mind during this time period you have workers are organizing into national labor unions. In all those areas you see in the pink and the red stars are going to be places where strikes are going to take place and various unions will form.

You have the Knights of Labor -- they focus on unskilled and skilled workers. They were much more welcoming to a variety of different types of workers, whereas the American Federation of Labor headed by Samuel Gompers was all about those skilled workers in bread and butter issues. So workers are responding to the problems of industrialization during this Gilded Age period.

Farmers responded to mechanization of agriculture and control of the railroad industry as well. They're organizing and trying to fight back against some of these challenges. And the big movement is going to be in the 1890s -- The People's Party or more commonly referred to as the Populist Party. They wanted the farmers wanted a stronger government role in regulating the economic system. They want laws regulating railroad industry, they want the direct election of senators, they want free coinage of silver. And they're going to run your boy Thomas Watson for president. He's going to lose, but they're a major force at least in the 1890s.

So these are some of the big themes and events of the Gilded Age. You know, things look good but underneath the surface there's some challenges. The Industrial Revolution -- a couple more things you should know about is there is a common belief of laissez-faire -- the government should not attempt to control or regulate business. This was advocated obviously by the wealthy, the business elite -- they don't want government meddling in their pursuit of profits. Many advocated ideas such as social Darwinism -- survival of the fittest -- and this justified the concentration of wealth. The rich are getting richer because they're better -- they deserve to be wealthy. They took Darwin's theories of evolution and applied them to the new industrial world. So make sure you know about social Darwinism.

There are some examples of regulation in this period. You have the beginnings of this -- you have the Interstate Commerce Act in 1887 which regulated railroad rates. It was weak initially, but it's the beginning. And this is advocated by farmers. It's the beginning of government regulation of industry. You have the Sherman Antitrust Act of 1890 -- how are we going to regulate these monopolies, these trusts? And once again in the beginning very weak, but it is the beginning of government regulation.

At the same time in this period -- 1870s to 1890 -- you have something called the New South. There is industrialization of the South. People are advocating we should switch over to a more industrialized economy. In spite of this advocacy, sharecropping and tenant farming remain the primary economic activity throughout the southern states. And you are going to see post-Reconstruction Jim Crow laws reinforced and deemed constitutional by the Plessy versus Ferguson decision throughout southern states.

Now during the same time, you're also having western expansion take place. This is kind of a common theme in American history, but the western expansion we're talking about in this time period -- roughly the 1860s to 1890 -- is trans-Mississippi West. You're going to have larger numbers of migrants move to the West in search of land and economic opportunity, frequently proving competition and violent conflict. And this is actually going to be encouraged by the US government by the federal government. They are going to encourage this western expansion.

An example of this federal government role is the Homestead Act in 1862 where the government is giving free or cheap land to settlers to move out west. You have the Pacific Railroad Act in 1862 which allows for government the route of the first transcontinental railroad. And a huge part of this is government subsidies -- tax breaks to the railroad companies to build this railroad network you see on those maps.

Now important to note -- with this western expansion comes the destruction and assault on Native life. And this is going to take many different forms. You are going to have the rapid decline of the bison -- it's going to be systematically slaughtered in order to undermine Native American resistance. You're going to have a series of Indian Wars -- you can see on the map those red stars are some of the biggies. And of course the last of the major Indian Wars takes place at Wounded Knee in 1890.

You're also going to have the Dawes Severalty Act passed by Congress in 1887 which effectively ended tribal ownership of land. The goal of the US government was a policy of assimilation -- let's get Native Americans off of tribal land, off of communal land, and get them onto private property and Americanize them. That was one of the goals of the Dawes Act. Make sure you know about this.

This guy Frederick Jackson Turner -- 1893 -- wrote The Significance of the Frontier in American History. He basically declared the frontier closed. You have the Indian Wars coming to a close, you have the continent settled from basically coast to coast. And this kind of idea of the frontier closing leads us to another period in American history -- that of US expansion. This is roughly 1890s to 1914.

Now I know what you're thinking -- America has always been expanding since its little 13 colony days along the Atlantic coast. This is different -- this is overseas expansion. One of the reasons -- one of the reasons this happens is this idea the frontier is closed in the 1890s, so the only place left to go is abroad is overseas. There's other reasons as well you should know about -- economic access to markets for goods and cheap raw materials. Remember the Industrial Revolution is going on -- how are we going to maintain this growth unless we find new markets and new cheap raw materials?

You also have political motives for US expansion -- we want to compete with other nations, you know especially European nations and also the rise of Japan around the globe. There's military reasons as well -- people like Alfred T. Mahan advocated for building up a strong navy. So you're going to need islands for naval bases across the globe. And then finally there's also ideological reasons -- you know this idea of spreading Anglo-Saxon civilization, spreading democracy, spreading Christianity.

There's a variety of forms this takes, but all of these different things including the closing of the frontier contributes to American expansion in the 1890s. Lots of examples you should know about -- you have the annexation of Hawaii. And remember Hawaii geographically is going to be significant -- strategically significant -- but there's also economic motives for its annexation by William McKinley.

You have in China the Open Door Policy -- wanting access to trade, getting rid of European and Japanese spheres of influence. You have the Spanish-American War -- hugely important in 1898 -- The Splendid Little War -- four months we fight Spain and we end up annexing not only Cuba, Puerto Rico, Guam and the Philippines. And you can see on the map some of those territories.

This is followed by a brutal war against the Philippines led by the Filipino resistance by Emilio Aguinaldo. They don't want the US to take them over, and the Philippines fights back and it's a deadly brutal war. And of course you have Theodore Roosevelt with his big project -- the big Panama Canal -- and he adds his Roosevelt Corollary to the Monroe Doctrine saying that we are going to be the policeman, the regulators of the Western Hemisphere.

Keep in mind not everyone agrees with this. You have debates between imperialists -- those in favor of expansion -- and the Anti-Imperialist League who are opposed to this expansion and criticize US efforts abroad. Make sure you know that this expansion takes place during the administrations of not only McKinley, Roosevelt, but also William Howard Taft and Woodrow Wilson. They're going to play a more active role. They're going to do so in a variety of ways. So know some examples of US expansion during these years.

Which leads us to our next period in American history -- the Progressive Movement, which really kind of begins in the 1890s to roughly 1920. This is happening at the same time some of these other events are going on, but this is really a domestic movement. It's government power to regulate and improve society. There was a belief that there were numerous problems that needed to be addressed, and this was a rejection of the laissez-faire ideology -- the government needs to play a role.

You have various muckrakers who start exposing problems. You have various movements that are happening. And ultimately this movement -- the Progressive Movement -- is going to result in reform. Some economic examples is trust busting under Theodore Roosevelt and Taft and Wilson. They're going to start strengthening the Sherman Antitrust Act and breaking up the so-called bad trusts.

You're going to have the Meat Inspection Act regulating the meat industry, Pure Food and Drug Act regulating both the drug and food industry, and the Wisconsin Idea by Robert La Follette where we're going to regulate the railroad industry and other big business. There's also going to be efforts to expand democracy during the Progressive Movement. And that's you're going to see in the 17th Amendment providing for the direct election of senators and reforms like the recall, the initiative, the direct primary. And of course a very active woman suffrage movement that had been going on for quite some time and picks up steam during the 1890s and the early 20th century.

Now keep in mind the Progressive Movement is a variety of movements -- so not everyone who fought for women's suffrage is fighting for these other areas. Women are going to play a huge role in the Progressive Movement, especially middle class white women and especially in cities, whereas the Populist movement was farmers -- the progressives are urban city dwellers.

You're also going to have moral reform during the Progressive Movement. There was the Anti-Saloon League which advocated prohibition, and eventually they will get passage of the 18th Amendment banning alcohol. And of course the environmental movement -- and you're going to have various branches of that environmental movement -- the preservationists who wanted to keep nature pure led by John Muir, and the conservationists led by Theodore Roosevelt and Gifford Pinchot where we're going to kind of manage natural resources for future generations.

Once again, the Progressive Movement is going to span various presidential administrations. So not only Theodore Roosevelt, but Taft and Wilson are all going to seek reform at the national level. They're going to have various degrees of success. And as you're going to see with Woodrow Wilson, they're reluctant to support certain reforms such as women's suffrage, and women have to put a lot of pressure on him to finally achieve that 19th Amendment.

World War I kind of interrupts this domestic reform movement. The Progressive Era really begins in 1914 and will go until 1918. Make sure you know that in the beginning the US was pledged to neutrality. Wilson tried to keep the United States out of World War I, but we will ultimately enter the war in 1917 for a variety of reasons. One is kind of ideological -- Wilson wanted to be involved in the post-war negotiations. He wanted to make the world safe for democracy, and so he wants to be at the table when the treaties are signed.

You have violations of American neutrality -- remember the sinking of the Lusitania, the British ship -- American lives are lost. You have the Zimmerman Telegram where Germany's trying to hook up with Mexico and declare war against the United States. And you have the fact that we were giving a lot of money to the Allies, and so we had an economic stake in their victory.

We do go to war, and eventually the US helps win that war. And Wilson is going to be heavily involved in post-war negotiations. Make sure you know about the 14 Points -- his kind of plan for the future and his plan to try to prevent future wars. And a big part of that is the League of Nations -- this international organization that will prevent future wars from occurring.

Ultimately though, Congress rejects the League of Nations. The Republican-controlled Congress had no desire to kind of move away from George Washington's warnings and his farewell address, and so they say we're staying out of this. And this kind of for a lot of people marks a return to US isolationism -- we want to stay out of European affairs or only be involved when we want to be involved.

The impact on the home front during World War I -- there's a couple important things that you should highlight. One is The Great Migration -- there's a huge movement of African-Americans from the South to Northern cities like New York that happens actually before World War I, but World War I accelerates it. And then of course you have violations of civil liberties -- you have the Sedition Act which basically really placed a lot of restrictions on freedom of speech, and the Schenck versus the US case which says speech can be restricted as long as that speech presents a clear and present danger. So you have this theme again of civil liberties and security and the balance between those two.

When World War I ends, the Progressive Movement kind of peters out and you have this period that everyone loves to study -- the Roaring Twenties. And the Roaring Twenties has tremendous economic and cultural changes. It's a decade of lots of transformations. You have new technologies like the radio, car and others that are becoming affordable or invented for the first time, and this dramatically improves the standard of living for a lot of Americans.

Not only that, you have mass consumption because people are able to buy things using new forms of payment like the installment plan. And advertising and the growth of the advertising industry allows people to kind of realize they want a bunch of things that they may not be able to afford now.

Another part of the 1920s you definitely need to know about are the conflicts -- a lot of different conflicts. You have conflicts between native born Americans and immigrants. Remember there's that reaction to those Southern and Eastern European immigrants. In fact, right after World War I you're going to have something called the Red Scare where everyone's freaking out that America's going to have a revolution and we're going to be overrun by Bolsheviks and communists and anarchists and all these things.

And the Palmer Raids start rounding up people whether or not they actually did anything wrong or not. You have the famous Sacco and Vanzetti trial where those dudes don't get any kind of fair trial because they're Italian, they're anarchists, they're draft dodgers, and they're ultimately put to death. You have the Quota Acts that are passed -- the big one is in 1924 that basically says only 2% of the immigrants that came in 1890 could come, and that was intended to restrict and limit immigration from Southern and Eastern Europe.

Another conflict you see is conflict between religious fundamentalists who tended to be in rural areas and more modern thinking that tended to be in the cities. This manifest itself in all sorts of areas like the Scopes Trial where a teacher gets in trouble for teaching evolution. You have the 18th Amendment which is not just an issue over religion, but many religious fundamentalists favored banning alcohol. And that doesn't go all that well as you see rising crime and people like Al Capone.

And then there's all sorts of other conflicts that you should kind of make yourself aware such as the rise of the KKK -- that's connected to this anti-immigrant rise of nativism. You get The Lost Generation -- a whole group of writers and artists who are disillusioned with the consumerism of the 1920s and the other things going on. And you get the Harlem Renaissance and this flowering of black culture and a celebration of being black in America. So the Roaring Twenties -- much more complicated decade than just flappers and drinking illegal alcohol.

Which leads us to the Great Depression. Great Depression begins in 1929. Throughout the decade of the 1920s, the stock market was doing really well, and all that collapses on October 29th, 1929 -- Black Tuesday. This is the start of the Great Depression. And there's a lot of reasons for the Great Depression -- the stock market is just one of those reasons.

Hoover tries to figure out what to do, doesn't do enough, and loses the election to Franklin Roosevelt. And in 1933 he takes office, and this is kind of the period of the New Deal. Franklin Roosevelt -- FDR -- believed in his New Deal program which he felt was going to provide relief, recovery and reform for the American people. This changed the role of the federal government and created the modern welfare state.

You know, and they love to ask questions that compare and contrast the New Deal to the Progressive Movement. They share something in common which is a rejection of laissez-faire. Couple things that you should know -- some programs: FDIC -- the Federal Deposit Insurance Corporation -- ensured people's bank deposits (still around today). The Social Security Administration provided basically the modern-day safety net -- the welfare state -- protecting the elderly, the unemployed, and women with dependent children.

You have the Wagner Act in 1935 which basically for the first time the federal government saying labor unions have a right to exist and the federal government is going to stand behind their right to bargain collectively. There is debate over the New Deal. You know there were people who wanted to limit it or kind of roll it back. The Supreme Court declares a couple New Deal programs unconstitutional -- the NRA and the AAA. Roosevelt tries his court packing plan and suffers a rare political defeat.

Republicans and conservatives did not like the New Deal because they did not like this rise of liberalism -- this big government. And you had others who wanted to expand the New Deal -- people like Huey Long who wanted to kind of adopt kind of a socialist plan -- "Every Man a King," share our wealth. He's going to get shot, so that's not going to work out. But there were debates about the New Deal.

Keep in mind the impact is huge. There is a New Deal Democratic Coalition -- a group such as farmers, urban immigrants, union members and African-Americans and women start really voting for the Democratic party in huge numbers because of the New Deal policies under Franklin Roosevelt. It established the federal responsibility for society -- this idea of the safety net. This was not established in America until the New Deal. It is the beginning or the rise of liberalism during this time period represented by the Democratic party.

But keep in mind the New Deal does not end the Great Depression. It will ultimately be World War II which does that. This kind of period ends in around 1939 as the world's attention and the nation's attention turns to World War II, which is going to take place from 1939 to 1945.

In the beginning from 1939 to 1941, we're basically trying to stay the heck out of it -- just as we did during World War I. There's a whole bunch of things that slowly kind of get us more and more involved. You have the Neutrality Acts where we're like not selling weapons to any country at war, we're not sailing on boats. But then England's in trouble as you can see in that political cartoon, so we start adopting policies like cash and carry, lend lease. We're slowly helping out the Allies because we don't want them to lose to these totalitarian governments.

Well, neutrality will end with the attack on Pearl Harbor by Japan on December 7th, 1941. We are now in World War II. The impact of World War II on the home front is huge -- make sure you know about it. The biggie is Japanese American and Japanese internment -- basically civil liberties denied. Japanese people of Japanese descent -- over 100,000 -- are sent to one of 10 internment camps throughout the country. This is a huge violation of their civil liberties and an embarrassment for America and American history.

There's a mass mobilization during World War II -- all parts of society are mobilizing to help win the war -- US factories, labor unions and so on. And you have all sorts of social impacts of the war. You have the Double V campaign for African-Americans -- victory against tyranny abroad as well as victory against racism at home. You have women playing an active role symbolized by Rosie the Riveter. And you have something called the Bracero Program where people -- Mexicans -- are brought into the United States to work to cover the labor shortage in areas especially like agriculture. So know about the impacts of World War II on the home front.

Eventually of course the Allies will win. We roll deep, but of course the big ones were the Soviets, the United States and England. And there's a variety of reasons -- one is US industrial production -- we produce a huge amount of the weapons and the stuff that helps fight the Axis powers. And you get new technology, and of course the big one is the Manhattan Project -- the secret program between England and the US that develops the A-bomb which will ultimately end World War II. And the importance of the Big Three Alliance -- Churchill, Stalin and FDR and their relationship and collaboration will help bring down the Axis powers.

And important battles -- military success at places like D-Day Normandy and northern France -- the opening of the second front. And island hopping where basically the United States is trying to get close enough to Japan to either invade or bomb the country. Ultimately it will be the atomic bomb which will end World War II -- hugely debated topic, different opinions on that issue. I highly suggest you kind of develop your own opinion.

But with the end of World War II -- big idea -- America becomes a superpower. We emerge as one of the most dominant countries in the world. And that leads us to our next period -- the Cold War. There is no start date on the Cold War -- it's going to go from 1945 to 1991. And basically the Cold War is an ideological, political and military struggle between the US and the Soviet Union. It really starts to pick up some steam in 1947, and the US objective throughout the Cold War is contain communism.

Communism was already in Eastern Europe -- we were not liking that. Remember the Yalta agreement -- we thought Stalin was going to remove those troops -- he does not. And a guy by the name of George Kennan comes up with this containment policy. There are numerous examples of containment -- here are a few: the Truman Doctrine -- we're going to give money to Greece and Turkey to make sure they don't fall to the communists and they do not. The Marshall Plan -- we're going to give a lot of money to Western Europe to help rebuild it so that those countries will not turn to communism -- they do not.

You're going to have NATO -- the North Atlantic Treaty Organization -- which is an example of collective security. All those countries in the green belong to NATO. That is our first permanent military alliance and it is going to still be around to this day. Other examples of containment get a little messier. In Korea, we stop the North Korean advance on South Korea, therefore preserving South Korea's non-communist status. And we try to stop communism in Vietnam, but it's a little messy there because it's really kind of a mix of communism and a nationalist movement. They wanted to get rid of France and then they wanted to get rid of us, and ultimately the US is not going to do as well in Vietnam.

The US and the Soviets fluctuated between periods of confrontation -- we got beef all over the globe -- but we're also going to have periods of détente or mutual coexistence or relaxation of tensions. Some examples of conflict -- you have the Berlin Blockade where Truman stands up to Stalin with the Berlin Airlift. The Cuban Missile Crisis -- the whole world nearly ended. Luckily Kennedy and Khrushchev -- cooler heads prevailed. But you're going to have these examples throughout the Cold War of us kind of thawing or tensions relaxing -- Spirit of Geneva under Eisenhower where we're starting to talk to one another, the SALT I treaty with the Soviet Union under Nixon. And of course -- of course -- Nixon being the guy who opens up our relationship with China in the 1970s.

Few more things about the Cold War you should know about. During the Cold War, the US is going to at times support for undemocratic governments. For example, the CIA is going to overthrow or help overthrow the government in Iran, in Guatemala in the 1950s under Eisenhower. And in both cases, new governments that take the place of the government we help get rid of are not exactly friendly to the local population or democratic. We support them though because they are non-communists. And there are other examples -- you're going to see this support for undemocratic governments also in South Vietnam as both Eisenhower and Kennedy supported the Diem administration in spite of its corruption and lack of support from the general population.

Another important idea during the Cold War is this kind of battle between civil liberties versus security. There is a fear during the Cold War that takes place -- in fact there's a second Red Scare in the late 40s, early 1950s. And this manifest itself in the House Un-American Activities Committee where they started investigating communist influence, and the rise of Senator Joseph McCarthy and McCarthyism. There were in fact some communist spies -- you have Alger Hiss and the Rosenbergs -- but this fear kind of becomes a paranoia and a lot of people's civil liberties are violated in the process.

There is a debate over the arms race. We are competing with the Soviet Union -- who can build up a bigger arsenal? And famously Eisenhower in his farewell address warns the nation about the military-industrial complex. And there is conscious fear of this proliferation of these horrible weapons, and you're going to see arms control agreements taking place or at least attempted throughout the Cold War.

The Cold War is going to lead to some controversies. You're going to have famously the anti-war protest over the war in Vietnam. And this is going to pick up a huge amount after the Tet Offensive in 1968 where people realized this war is nowhere near being over. And following revelations of the secret bombing of Cambodia by the Nixon Administration, and ultimately this will... and ultimately one of these protests will end in a shooting at the University... Kent State University.

More protests will erupt following revelations of the secret bombing of Cambodia by the Nixon Administration. And during this wave of protest, you have the shooting that takes place at Kent State where people are shot by the National Guard.

Quick look at some of the domestic things happening. The 1950s is often times kind of seen as this decade of conservative or complacent. There's a lot of opportunity to compare it to the 1920s because you got a lot of things that are similar. Eisenhower is the president -- the hero of World War II. He is a moderate Republican, so you're not going to see a big reform. There's no liberal huge agenda going on. But there's a lot of changes in America. It's an economically prosperous decade relatively speaking for many people -- but not all people.

And you're going to see the growth of the middle class. Post-World War II economy -- a huge growth in the middle class as the economy is transitioning. You got more and more white collar workers -- so people are not working in industrial factories but in more white collar type jobs. Post-World War II you also have this mass movement of people to the suburbs -- the famous Levittowns. And you have a huge baby boom in the late 40s and early 50s. Credit cards are introduced in this decade which allows for an increase in consumerism. Television became a common household item in the 1950s and kind of leads to the spread and growth of American culture.

But there are tensions in the 1950s that you should be aware of. And these are some of them. Betty Friedan writes The Feminine Mystique -- it's actually published in 1960 but it really kind of condemns the way women are treated in American society and the expectations of women playing the role of the happy suburban housewife. And you're going to see the growth of the women's movement in subsequent years.

The beatniks -- a group of artists -- criticize the conformity of the 1950s. And of course a big example of this decade not being one filled with complacency comes with the civil rights movement that really picks up a lot of energy in the 1950s. So let's take a quick look at the Civil Rights Movement.

You know there's no start date for this, but you know civil rights activists used legal challenges, nonviolence and direct action to achieve their goals and to try to overturn the Jim Crow system that was in place. As you could see in that photo, you know there is no start movement -- World War II you see with the Double Victory campaign. You have organizations like the Congress of Racial Equality starting to rise up. And in the 1950s in 1954 you have Brown v. Board of Education -- this overturned segregation -- ruled school segregation inherently unequal.

Other examples of nonviolence and direct action can be seen in the Montgomery Bus Boycott in 1955 sparked by the arrest of Rosa Parks, the Freedom Rides in 1961 under or during the Kennedy administration. And so this movement really kind of is energized in World War II, picks up steam in the '50s, and then explodes in the 1960s.

An important idea you should keep in mind is the three branches of the government eventually played a role in advancing the cause of civil rights. At first they're slow to do so, but with a lot of pressure eventually we start to see some change. An executive branch role in that change can be seen when Truman desegregated the military in 1948 -- took a lot of heat for that. Judicial change can be seen with Brown v. Board of Education which overturned Plessy v. Ferguson. And legislative change could be seen with the Civil Rights Act of 1964 and the Voting Rights Act of 1965 -- we'll cover both those in just a few moments -- signed by President Lyndon Johnson.

Civil rights movements -- there's a lot more movements than just African-American civil rights. But keep in mind there was fierce white resistance to these changes, especially in southern states. You have the Southern Manifesto to the Brown decision where over 100 southern congressmen basically said the court -- the Supreme Court -- is abusing its power. You have the Little Rock Nine blocked by Governor Orville Faubus -- he doesn't want to allow them into the schools.

And as this resistance takes place, there are debates over the tactics and the philosophies amongst civil rights leaders. They start to question what is the best path to achieve their goals. So you start to get more radical voices in the civil rights movements -- people like Stokely Carmichael associated with the Black Power movement, Malcolm X and the Nation of Islam, and the Black Panthers out in Oakland. They start to kind of be known as the black radicalism -- the Black Power movement -- who call for much more aggressive action.

There are other civil rights movements which are inspired by the African-American civil rights movement. You have women taking on more vocal opposition -- kind of sparked with The Feminine Mystique's publication and then you get people like Betty Friedan forming organizations such as the National Organization for Women. You have the American Indian Movement and Latinos such as Cesar Chavez and the United Farm Workers Union. And the rise of the gay rights movement with the Stonewall Riots in 1969. So make sure you know about the variety of civil rights movements taking place and especially how they played a role in the 1960s.

And you can't talk about the 1960s without talking about Lyndon Johnson's Great Society. This is really seen as the height of liberalism. And the Great Society dramatically increased the size and the scope of the federal government. In many ways, the Great Society is a continuation of the New Deal programs, but whereas the New Deal was primarily focused with ending the Great Depression, the Great Society is going to go much further. It was this idea -- this liberal idea -- that government power can be used to fix societal problems.

And you're going to see a variety of programs like Medicare -- those over 65 could get health care. Medicaid -- health care for the poor and disabled. Job Corps -- vocational education. A big act you should know about -- the Immigration and Nationality Act of 1965 which basically wipes out those quotas from the 1920s which allows for people especially people from Latin America and Asia to come into the United States in much greater numbers.

The two other big ones are the Civil Rights Acts -- the Civil Rights Act of 1964 which basically declared segregation illegal in all public facilities, and the Voting Rights Act of 1965 which basically wiped out all of those things that were used to prevent African-Americans from voting in the South such as the literacy test. So whereas the New Deal kind of ignored or overlooked race relations, the Great Society made it a huge focus of its platform.

During this time you also have Earl Warren -- the Warren Supreme Court -- which are going to rule on a variety of cases which are going to expand democracy and individual liberty. There is of course a conservative reaction. You could see that really in the election of 1964 with Barry Goldwater -- even though he gets his butt kicked against Lyndon Johnson. And conservatives criticize the Great Society and other liberal programs as too costly, inefficient, too idealistic. They created dependency on people, and so they were very vocal.

Barry Goldwater kind of begins this modern conservative movement. He loses the election, but that movement continues into the late '60s. You get Nixon winning in 1968, and although he's not a hardcore social conservative, Nixon wins as a Republican in '68. And you're going to see the conservative movement grow in the '70s and eventually in the '80s.

Which leads us to the '70s. Few things you should know about -- there is a huge distrust of the government in the 1970s. And there's a lot of reasons for it. You know the failures of the Vietnam War -- like did we actually get attacked at the Gulf of Tonkin? Why did they say the war is almost over and then the Tet Offensive have happened? Why is Nixon bombing Cambodia? And the revelation of some of these things in the Pentagon Papers makes a lot of individuals distrust the federal government.

The Watergate scandal fuels that fire of government distrust where Nixon is found to be doing some things that are not exactly on the up and up, and he is ultimately forced to resign. And Gerald Ford becomes the first unelected president in our nation's history. You have the Iran Hostage Crisis and Jimmy Carter's inability to handle that effectively. All of these things and others lead to a distrust of the government.

And of course in the '70s there is an economic slowdown. You have something called stagnation and high inflation which becomes known as stagflation. So the economy is kind of sputtering forward in the 1970s which leads to a lot of unhappiness. And that leads us to the 1980s and the rise of the conservative movement.

There's a lot of reasons for it. You have the rise of the religious fundamentalists who are worried about all these social changes -- the rise of feminism, the legalization of abortion. And religious fundamentalists start to organize. You got a lack of faith in government which we just mentioned. And then you got economic concerns -- they start rejecting the deficits of the New Deal and the Great Society and other liberal programs. They don't trust the government to solve society's problems. And Reagan kind of rides this conservative movement to election in 1980.

There are some conservative victories under Reagan. He does initiate tax cuts especially for the wealthy -- this idea of trickle down economics -- Reaganomics. There is the continued deregulation of many industries. And entitlement spending is decreased -- things on like welfare and food stamps -- those programs are cut in the '80s.

There are limits to the conservative movement you should know about. You know programs such as Social Security from the New Deal days and Medicare during the Great Society remained. They were popular with voters, and nobody -- Republican or Democrat -- want to mess with them because the voters will be angry. And in spite of all this kind of criticism of big government, the government remained big under Reagan because of defense spending and tax cuts. So you have a huge federal deficit in the '80s.

Some foreign policy stuff you should know -- and we're almost done -- remember the Cold War ends in 1991. The Soviet Union basically falls apart for a lot of reasons for that. And the post-Cold War foreign policy environment is going to probably be even more complicated than the days of the big Soviet boogeyman being out there. And that is really kind of marked by the terrorist attacks on 9/11 in 2001. This begins the War on Terror.

Following the attacks on 9/11, you have a war that takes place in Afghanistan. You have a war in Iraq. And this has also impacts on the homefront. Congress passes the Patriot Act signed by President George Bush. And once again you have debates over the impact on civil liberties -- how far should we go to investigate potential terrorist attacks?

All right, APUSH friends. I try to make it quick, but I know that's a lot of information. There's a ton of review videos on the channel -- check them out. Check out our Period 6 through 9 review videos. Check out the website apushexplained.com -- it's the hottest site on Earth. Tons of chapter review videos, all sorts of review sheets, key concepts. And if you haven't already done so, subscribe to Jocz Productions. Good luck on your test in May -- you're going to rock it. Remember -- take the test, don't let the test take you. If you would do me a solid, pay it forward until next year's APUSH crew. Check out Jocz Productions and APUSH Explained. Thank you for watching -- have a beautiful day. Peace.

'''
