
= American Pageant - 007 (1775-1783)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义

What's up 怎么了, everyone? Today we're taking a look at the American Revolution 美国独立战争. + 
 We finally are becoming the USA, and we're going to help you out with all of your history needs. + 


So remember, in April of 1775, the shots are fired at Lexington and Concord. + 
 And a little bit later, you have the Second Continental Congress 第二次大陆会议 meeting in Philadelphia in May of 1775. + 
 And really, the colonies are really working together. + 
 Remember, there's been this movement towards intercolonial unity 殖民地间团结, but keep in mind there still is no clear consensus 共识 for independence. + 
 There was division amongst the colonists as to whether or not to declare independence. + 
 This was still a radical idea 激进的想法, and most people at this point want to try to negotiate. + 


At the same time they're trying to negotiate though, they are organizing the Continental Army 大陆军, and they pick Mr. + 
 George Washington as their commander-in-chief 总司令. + 
 And even while they're negotiating, more battles take place. + 
 You have Bunker Hill in June of 1775. + 
 The British take the hill -- they take it from the colonists -- but the colonists hold their own 坚守阵地, and this really builds the confidence of the colonial cause 殖民事业. + 
 Like, we can hold our own against the most powerful military in the world. + 


At the same time, the colonists sought peace by sending the Olive Branch Petition 橄榄枝请愿书 to King George the Third. + 
 They pledge their loyalty 宣誓效忠. + 
 They said they want to work with Parliament. + 
 They see themselves as British, and they're really trying to negotiate and try to prevent a larger war from occurring. + 
 Now if you're wondering why they're doing this, remember loyalty is deeply ingrained 根深蒂固 in the colonists. + 
 They believe they're part of the British Empire. + 
 They see themselves as British. + 
 Colonial unity was poor for a very long time, so rebellion 叛乱 was dangerous. + 


Now King George III though dismisses the Olive Branch Petition and declared the colonies in rebellion. + 
 He also hires some German mercenaries 雇佣兵 to handle the situation. + 
 And it is important to note that in 1775, as the fights at Bunker Hill and Lexington and Concord have taken place, there still is no clear consensus for independence amongst members of the Continental Congress. + 


Deeper roots of the American Revolution even before these fights started taking place, and you really have to kind of understand the ideas of the Enlightenment 启蒙运动 from the 18th and 17th century. + 
 Ideas of people like John Locke and Rousseau were strongly influencing colonial thought. + 
 And Enlightenment ideas emphasize the individual over hereditary privilege 世袭特权. + 
 There was an emphasis on reason and science, and you can really see this in the writings of John Locke. + 
 He said -- Locke said -- everyone has natural rights 自然权利, and the power of government is derived from popular consent 民众同意. + 
 And these ideas were coming over to North America and really influencing colonial society. + 


And you see the Enlightenment ideas very much represented in Thomas Paine's pamphlet 小册子 Common Sense, which is published in January of 1776. + 
 And it makes the most clear, persuasive argument 有说服力的论点 for independence today. + 
 And what he says -- a very radical idea at the time -- is he calls for the creation of a republic 共和国, a representative government 代议制政府 based on natural rights of the people, based upon consent. + 
 He says the colonies should break away from England. + 
 He talks about a large continent cannot be run by an island -- by England. + 
 Paine's ideas are heavily influenced by the Enlightenment. + 
 He breaks them down in very simple language, and he says people could rebel against a government when it didn't protect their rights, and that's exactly what he's calling for. + 


And these ideas spread throughout the colonies. + 
 You get the final push for independence when Richard Henry Lee of Virginia issues a resolution 决议 saying the colonies should declare independence. + 
 Thomas Jefferson drafted 起草 the formal Declaration of Independence 独立宣言, and it has a couple of goals. + 
 One, you want to justify independence by listing the grievances 不满 against King George III. + 
 And you could see this if you read the Declaration of Independence -- there's a whole bunch of them. + 
 There was one that was taken out -- Jefferson wrote against slavery, ironically enough -- blaming the king and Parliament for that, and that was removed at the insistence of Southerners. + 


Another goal of the Declaration of Independence is to rally support 集结支持 amongst the colonists. + 
 Remember, not everyone favored independence. + 
 This was still a radical idea to be pursuing. + 
 They also want to get assistance from foreign nations. + 
 They want to rally them to the cause of the colonies -- get some help, some backup. + 
 And the most important part of the Declaration of Independence to this day is it is this broad appeal by declaring unalienable rights 不可剥夺的权利 -- these ideas of natural rights -- and that the power of government rests with the people. + 
 Popular sovereignty 人民主权 rests with the people. + 
 And you could see a lot of John Locke's influence throughout Jefferson's writing of the Declaration of Independence. + 


And by July of 1776, the Declaration of Independence is formally adopted 正式通过, and we America now. + 
 Before you break out the fireworks and the hot dogs and all that other good stuff that we celebrate on the 4th of July, you have to understand that colonial unity was really questionable at best. + 


On one side, you have the Patriots 爱国者. + 
 And these are the colonists who fought against the British. + 
 They supported the American Revolution, and the largest number of them were in the New England area around Boston. + 
 But they were never a majority of the population -- anywhere between 30 to 40% of people in the colonies were patriots. + 


On the other side were the Loyalists 保皇派. + 
 And these were, of course, colonists loyal to the British. + 
 They were opposed to independence. + 
 Numbers vary, but anywhere between 20 to 30% of people were loyalists. + 
 They were called Tories 托利党人 over in England, and they tended to be educated, wealthy, older, more conservative people who were connected to the monarchy 君主制 or members of the Anglican clergy 英国圣公会神职人员. + 
 They are going to have a hard time because they are going to be on the losing side. + 
 They're treated as traitors 叛徒 during and after the American Revolution. + 
 Their property was very often seized 没收, and they were harassed. + 
 And a lot of them are going to leave the United States during and after the war is over. + 


And it's important to note there's also a third group which are those people who were neutral or apathetic 冷漠的. + 
 They didn't really care. + 
 You know, they were more loyal to their colony or their state, their region. + 
 They just wanted to be on their farm. + 
 So they weren't really committed to the American independence cause. + 
 And this is anywhere between about a third of the people in the colonies. + 


It's important you also know that this battle between England versus America -- both were coming in with certain strengths and weaknesses. + 
 On England's side, Great Britain was militarily and economically superior to the colonies. + 
 They had the best army. + 
 They had a very, very developed manufacturing sector 制造业, so they were able to provide supplies, whereas the colonists were poorly trained, poorly supplied, and so on. + 


As we mentioned, there was considerable loyalist opposition in the colony. + 
 So not all the colonists supported the cause. + 
 That's going to be a strength for England and a weakness for the colonies. + 
 And of course, a big colonial weakness -- we'll break down next video -- is there was a weak government structure under the Continental Congress and eventually the first national government, the Articles of Confederation 邦联条例. + 
 You know, the government couldn't really get the economy going. + 
 They printed paper money which was worthless. + 
 So colonies are going to have a rough time. + 


In spite of this rough time, the colonies are going to have certain strengths. + 
 They had, of course, greater familiarity with the land 更熟悉地形. + 
 They're fighting on their home turf 主场. + 
 They had home field advantage 主场优势. + 
 They're fighting a defensive war 防御战, meaning all they have to do is not lose, and they would win the war. + 
 And they're going to use tactics such as guerilla warfare 游击战 where they're going to kind of attack when appropriate and engage in battles that are favorable to them. + 


They're going to have resilient military and political leadership 坚韧的军事和政治领导. + 
 They're fighting for a cause that they believe in. + 
 And you're going to see great leaders like George Washington, especially as he rallies the troops 集结部队 at Valley Forge during a low moment in the war. + 
 And it's important to not underestimate the ideological commitment 意识形态承诺. + 
 They're fighting once again for a purpose, whereas England's fighting to keep colonies that don't want to be with them. + 
 It doesn't really have as much passion attached to it. + 


And another big strength for the colonies is the eventual support from European allies 欧洲盟友, especially France following the Battle of Saratoga. + 
 Make sure you know that, which leads us to our next point -- why did France help out the colonists?

One factor was France hoped to regain its power in North America and Europe. + 
 And if you recall, they suffered a bad defeat in the Seven Years' War -- the French and Indian War -- where they lost all their territory in North America. + 
 So they want some payback 报复 against England. + 


But there's other reasons for France to support the colonists. + 
 If England is removed from the 13 colonies, this would mean an end of British mercantile policies 重商主义政策 like the Navigation Acts 航海条例 that said the colonies could only trade certain goods to England. + 
 And therefore, France would be able to freely trade with the colony. + 
 So there was an economic motive. + 


And some elements of French society were caught up in the idealism 理想主义 and the Enlightenment ideas. + 
 They want to support this revolutionary movement. + 
 Ben Franklin goes over to France -- you could see him getting his bald head tickled there in that painting -- to help negotiate the treaty. + 
 And France was actually giving the colonists secret aid prior to 1778, but nothing formal -- no formal alliance 正式联盟 until following the Battle of Saratoga. + 
 Once the colonists win that battle in 1778, France and America sign a treaty, and this provides the colonists with money, weapons, naval support 海军支持 -- which is hugely important because now they can have a navy on their side -- and soldiers. + 
 And really key to the American victory is going to be French assistance. + 


There are a lot of battles of the American Revolution. + 
 You don't need to be experts on them, but a quick rundown 快速概述 of some of the key ones: Lexington and Concord -- opening shots; Bunker Hill -- they technically lose -- the colonists lose -- but it kind of is a morale boost 士气提升. + 
 Hey, perhaps we can actually hold our own. + 


It's important to understand from 1775 to 1777, things are bad for the Patriot cause. + 
 The British are occupying New York. + 
 They're occupying Philadelphia. + 
 Things aren't going too swell. + 
 You do get another victory where Washington famously crosses the Delaware River and captures the German mercenary troops at the Battle of Trenton, followed up a week later by the Battle of Princeton -- another morale boost. + 
 Hey, we're getting a win. + 
 That's always key. + 


Battle of Saratoga -- the British surrender to the Americans, and this brings in French assistance. + 
 France joins the war on the side of the Americans. + 
 You might want to know that following this period, later on England focused their war effort on the southern colonies. + 
 And the reason for that is there's a lot of loyalists in that region, and there's a high slave population. + 
 So therefore, they're hoping that would work to their advantage -- perhaps cause tension within the colonies and disrupt their ability to fight the war. + 


And make sure you know about the Battle of Yorktown, which is the final major battle in October of 1781, when General Cornwallis surrenders to the Americans and the French troops. + 
 The French military plays a key role at Yorktown. + 
 They blockaded the sea 海上封锁 -- you could see that on the map -- and George Washington gets the victory along with his French homies. + 


Which leads us to the Treaty of Paris of 1783. + 
 And the Treaty of Paris is negotiated by Benjamin Franklin, John Adams, and John Jay. + 
 They headed to Paris to negotiate an end to the war. + 
 They never finish that painting -- fun story right there. + 
 And the Treaty of Paris, when it is all said and done and signed, does a couple of things. + 


One, England recognized the United States' independence. + 
 We are free. + 
 The boundary of the US would extend to the Mississippi River. + 
 You could see our before and after. + 
 We would go all the way up to the lakes. + 
 So England's still going to control Canada, and Spain will control Florida and the territory west of the Mississippi River. + 


The Americans do agree to do some things. + 
 They must respect the rights of the loyalists -- so property rights 财产权 and things like that. + 
 Debt should be repaid to not only the loyalists but also to British creditors 债权人. + 
 And following the war, there will be some conflicts in these different areas. + 


A question you often times see on the AP exam is the impacts of the American Revolution. + 
 So important to know why it started and then what are the outcomes. + 
 And one of the big impacts is going to be greater political democracy 政治民主 in the new state and national governments. + 
 You know, many state constitutions abolished many old European laws and traditions. + 
 And one example of this can be seen the restrictions on allowing titles of nobility 贵族头衔 to be granted in many state constitutions. + 


There's different ideas of what republicanism 共和主义 would mean -- how much or how democratic would this new nation be? There was increases in democracy, but there were limits to it. + 
 Many states eliminated property requirements 财产要求 from voting. + 
 So for example, the big one is Pennsylvania. + 
 They had a unicameral legislature 一院制立法机构 where most white men could vote and there was no governor. + 
 But not all states did this. + 


In spite of this democratization 民主化, it's important to note the colonial elite remained in power. + 
 Other states restricted political involvement -- meaning you had to own property in order to be eligible to vote 有投票资格. + 
 Most states did not have full democracy. + 
 It was not extended to African-Americans, women, Native Americans unfortunately. + 
 And so one of the things you're going to see throughout American history is this movement towards greater democratic participation. + 


The American Revolution inspired revolutions in France, Haiti, and in Latin America. + 
 And you're going to see revolutions take place, and very often they're going to be inspired by the words found in the Declaration of Independence. + 


Social impacts of the American Revolution -- you're really going to see this in the realm of women. + 
 They play a significant role. + 
 They maintained farms and businesses while the men were away fighting the war. + 
 Many women served as nurses and cooks following the Continental Army around. + 
 And even before the war, we saw the importance of women in the economic boycotts 经济抵制 with the Daughters of Liberty with the spinning bees 纺织集会. + 
 There's even one Massachusetts woman who dressed in men's clothing and served in the Army for 17 months. + 


Now as a result of these contributions, women began to demand greater rights. + 
 One important figure is Abigail Adams -- wifey of John Adams. + 
 She reminded her husband to "remember the ladies," and she called for greater rights for women as a result of women's experiences in the movement for independence and the formation of a new republic. + 


There was this ideal of Republican Motherhood 共和母亲主义 which called on women to teach republican values within the family. + 
 So women played a very important role in the new republic of raising the children of the home to be good citizens in this new nation. + 
 In spite of some of these changes, it's important to note women were still treated as second-class citizens 二等公民. + 
 Women were not able to vote. + 
 Married women could not own property or sign contracts. + 
 And there were numerous restrictions on the rights of women. + 


During the war, Native Americans often times fought on the side of the British. + 
 And the big reason for this is the British limited colonial settlement. + 
 Remember the Proclamation Line of 1763 -- you could see on the map -- had restricted the movement of white settlers into Native American land. + 
 So many Native Americans sided with the British. + 
 So when the war was over, this was a huge defeat for Native Americans because now white settlers were unchecked into Native American land. + 


Siding with the British wasn't always the case. + 
 For example, the Iroquois Confederation 易洛魁联盟 was divided over the issue. + 
 They tried to stay neutral in the beginning of the war, and then some tribes fought for the colonists and many others fought for the British. + 
 But for Native Americans, it's important to keep in mind their land is now opened up to the United States all the way to the Mississippi River. + 


The American Revolution had a lot of impacts on the African-American community. + 
 African-Americans eventually were allowed to fight in the Continental Army. + 
 And there were many African-Americans who fought for the revolutionary cause. + 
 But there were also African-Americans who fought for the British. + 
 The British royal governor of Virginia, Lord Dunmore, promised freedom to any slave who fought for the British against the colonists. + 
 Unfortunately for those individuals, the British lose, so that freedom was not granted. + 


Following the American Revolution, there was gradual emancipation 逐步解放 in the northern and middle states. + 
 You know, for many, there was a growing awareness of inequalities in societies -- the hypocrisy of "all men are created equal" and the fact that slavery was not economically profitable in those regions. + 
 All of those things lead to states in the North and the middle granting emancipation. + 
 You could see this on the map -- the years emancipation takes place -- and really famously with the Pennsylvania gradual emancipation law of 1780. + 
 This law said no more slaves could come into the state, and children born to slave parents would be considered free. + 
 So you're going to get the gradual disappearance of slavery in the North. + 


And the South -- in spite of slavery slowly kind of dying out in the middle states and the northern states, later on slavery will expand in the South and in the adjacent western lands. + 
 And what's going to happen is you're going to get distinct regional identities 鲜明地区特征 develop between the North and the South -- one slave, one free. + 
 This will, of course, create distinct regional attitudes towards slavery. + 
 Each area -- the North and the South and the West -- will have distinct regional identities, and this will ultimately lead into problems later on. + 


And as we will see in our next video, slavery will be protected in the Constitution. + 
 So even though it will end in some places, it will very much be a part of the fabric of American life. + 


That's going to do it for today. + 
 Hopefully you learned a whole lot, and if you did, click like on the video, tell your friends about the channel, and if you have any questions, post them in the comment section. + 
 Until next time, have a beautiful day. + 
 Peace!


'''

== 中文释义

大家好！今天我们来了解一下美国独立战争。我们终于要成为美利坚合众国了，我们将帮助你们满足所有的历史学习需求。

记住，**1775年4月，列克星敦和康科德响起了枪声。不久之后，"第二次大陆会议"于1775年5月在费城召开。**实际上，各个殖民地都在真正地合作。记住，一直存在着一种走向"殖民地间团结"的运动，*#但要记住，对于"独立"仍然没有明确的共识。殖民者在是否宣布独立的问题上存在分歧。这在当时仍然是一个激进的想法，大多数人此时都想尝试谈判。#*

**然而，在他们试图谈判的同时，他们也在组建"大陆军"，并挑选乔治·华盛顿先生为总司令。即使在他们谈判时，更多的战斗也发生了。**1775年6月发生了邦克山战役。英国人占领了山头——他们从殖民者手中夺取了它——但殖民者坚持了下来，这极大地增强了殖民事业的信心。就像，我们可以对抗世界上最强大的军队。

**与此同时，殖民者通过向乔治三世国王发送橄榄枝请愿书, 寻求和平。他们宣誓效忠。他们说他们想与议会合作。他们认为自己是英国人，并且他们真的在努力谈判，试图阻止更大规模的战争发生。如**果你想知道他们为什么这样做，记住忠诚深深地扎根于殖民者心中。*#他们相信自己是大英帝国的一部分。他们认为自己是英国人。殖民地间的团结在很长一段时间内都很差，所以叛乱是危险的。#*

**然而，乔治三世国王驳回了橄榄枝请愿书，并宣布殖民地处于叛乱状态。**他还雇佣了一些德国雇佣兵来处理局势。*重要的是要注意，在1775年，当邦克山、列克星敦和康科德的战斗发生时，大陆会议的成员之间仍然没有明确的独立共识。*

甚至在这些战斗开始之前，**美国独立战争就有着更深的根源，你真的需要理解18世纪和17世纪启蒙运动的思想。约翰·洛克和卢梭等人的思想, 强烈影响着殖民地的思想。启蒙思想强调"个人"而非"世袭特权"。它强调"理性"和"科学"，**你可以在约翰·洛克的著作中清楚地看到这一点。洛克说——*洛克说——##每个人都拥有自然权利，政府的权力来源于人民的同意。##这些思想传到了北美，并真正影响了殖民地社会。*

你可以在**托马斯·潘恩**于1776年1月出版**的小册子《常识》中, 看到启蒙思想的充分体现。它为今天的"美国独立"提出了最清晰、最有说服力的论证。他所说的是——在当时一个非常激进的想法——#他呼吁建立一个共和国，一个基于人民自然权利、基于人民同意的"代议制政府"。他说殖民地应该脱离英国。#**他谈到一个庞大的大陆不能由一个岛屿——英国——来统治。潘恩的思想, 深受启蒙运动的影响。他用非常简单的语言来阐述这些思想，他说**#当政府不保护人民的权利时，人民可以反抗政府，#**这正是他所呼吁的。

这些思想在整个殖民地传播开来。当弗吉尼亚的理查德·亨利·李提出一项决议，说殖民地应该宣布独立时，你得到了争取独立的最后推动力。*##托马斯·杰斐逊起草了正式的《独立宣言》，它有两个目标。第一，它想通过列举对乔治三世国王的控诉, 来证明"美国独立"的合理性。如果你阅读《独立宣言》，你会看到这一点——有很多控诉。##有一条被删掉了——具有讽刺意味的是，杰斐逊写了反对奴隶制的内容——指责国王和议会对此负责，但应南方人的坚持，这条被删掉了。*

**##《独立宣言》的另一个目标是争取殖民者之间的支持。记住，并非所有人都赞成独立。##追求独立仍然是一个激进的想法。他们还想获得外国的援助。**他们想争取他们支持殖民地的事业——获得一些帮助，一些后援。而**##《独立宣言》至今最重要的部分是，它通过宣布"不可剥夺的权利"——这些"自然权利"的思想——以及"政府的权力在于人民"这一观点，进行了广泛的呼吁。人民拥有主权。##你可以在杰斐逊撰写《独立宣言》的过程中看到约翰·洛克的许多影响。**

**#到1776年7月，《独立宣言》正式通过，我们现在是真正的美国了。#**在你燃放烟花、吃热狗以及庆祝7月4日的所有其他好东西之前，*你必须明白，殖民地间的团结充其量也令人怀疑。*

**一方面，你们有爱国者。**这些人是反抗英国人的殖民者。*##他们支持美国独立战争，##其中人数最多的是波士顿周围的新英格兰地区。#但他们从未占人口的大多数——殖民地人口中只有30%到40%是爱国者。#*

**##另一方面是效忠派。##这些人当然是效忠英国的殖民者。#他们反对独立。数字各不相同，但大约有20%到30%的人是效忠派。#**在英国，他们被称为托利党人，他们往往是受过教育、富有、年长、更保守的人，他们与王室有联系，或者是英国国教神职人员的成员。*他们将面临艰难的时期，因为他们将站在失败的一方。在美国独立战争期间和之后，他们被视为叛徒。他们的财产经常被没收，他们受到骚扰。许多人将在战争期间和结束后离开美国。*

*重要的是要注意，##还有第三个群体，即那些中立或冷漠的人。他们并不真正关心美国独立与否。##你知道，他们更忠于他们的殖民地或州，他们的地区。他们只想待在他们的农场里。所以他们并没有真正致力于美国的独立事业。#这大约占殖民地人口的三分之一。#*

你们还需要知道，英国与美国之间的这场战争——双方都有各自的优势和劣势。在英国方面，大不列颠在军事和经济上都优于殖民地。他们拥有最好的军队。他们拥有非常非常发达的制造业，所以他们能够提供补给，而**殖民者训练不足，补给不足等等。**

正如我们提到的，**殖民地内部存在相当大的效忠派反对势力。所以并非所有殖民者都支持独立事业。这对英国来说是一个优势，**对殖民地来说则是一个劣势。当然，*#殖民地的一个主要劣势#*——我们将在下一个视频中详细介绍——是在大陆会议以及最终的第一个国家政府，*##即邦联条例下，政府结构薄弱。你知道，政府无法真正推动经济发展。他们印制的纸币一文不值。##所以殖民地将面临艰难的时期。*

尽管面临着这段艰难的时期，殖民地仍然拥有某些优势。当然，他们更熟悉这片土地。他们是在自己的家园作战。他们拥有主场优势。他们打的是一场防御战，这意味着他们只需要不输，他们就能赢得战争。*他们将使用游击战等策略，在适当的时候发动袭击，并参与对他们有利的战斗。*

他们将拥有坚韧的军事和政治领导。他们为他们所信仰的事业而战。你们将看到像乔治·华盛顿这样的伟大领导人，尤其是在战争低谷时期，他在福吉谷集结军队时。而且，不要低估意识形态的承诺是很重要的。他们再次为目标而战，而英国则为保留"不愿与他们在一起的殖民地"而战。这并没有那么多的激情。

**殖民地的另一个巨大优势是, 最终得到了欧洲盟友的支持，尤其是在"萨拉托加战役"之后得到了法国的支持。确**保你们知道这一点，这引出了我们的下一个问题——*为什么法国帮助殖民者？*

**一个因素是法国希望重获其在北美和欧洲的权力。**如果你还记得**，他们在七年战争——法国-印第安战争——中遭受了惨重的失败，失去了在北美的所有领土。所以他们想报复英国。**

*但法国支持殖民者还有其他原因。#如果英国被逐出13个殖民地，这将意味着英国的"重商主义"政策，如《航海法案》（规定殖民地只能向英国出口某些商品）的终结。因此，法国将能够自由地与殖民地进行贸易。所以存在经济动机。#*

法国社会的一些人士, 也受到了理想主义和启蒙思想的影响。他们想支持这场革命运动。本杰明·富兰克林前往法国——你们可以在那幅画中看到他的光头被挠痒痒——以帮助谈判条约。**法国实际上在1778年之前, 就秘密援助殖民者，**但没有任何正式的——在萨拉托加战役之后才没有正式的联盟。*一旦##殖民者在1778年赢得那场战役，法国和美国就签署了一项条约，这为殖民者提供了金钱、武器、海军支持##——这非常重要，因为现在他们可以拥有自己的海军——和士兵。法国的援助将是美国胜利的关键。*

美国独立战争有很多战役。你们不需要成为专家，但快速回顾一下一些关键战役：列克星敦和康科德——第一枪；邦克山——他们技术上输了——殖民者输了——但这在某种程度上鼓舞了士气。嘿，也许我们真的能坚持住。

重要的是要理解，从1775年到1777年，对于爱国者事业来说，情况很糟糕。英国人占领了纽约。他们占领了费城。事情进展不顺利。你们确实取得了另一次胜利，华盛顿在那次著名的行动中横渡特拉华河，并在特伦顿战役中俘虏了德国雇佣军，一周后又取得了普林斯顿战役的胜利——又一次鼓舞了士气。嘿，我们赢了。这总是关键。

萨拉托加战役——英国人向美国人投降，这带来了法国的援助。法国加入了美国一方的战争。你们可能想知道，**##在此之后，英国后来将其战争努力集中在南方殖民地。原因是该地区有很多效忠派，##而且奴隶人口众多。**因此，他们希望这能对他们有利——也许会在殖民地内部造成紧张局势，并破坏他们进行战争的能力。

确保你们了解约克镇战役，这是1781年10月的最后一场主要战役，康沃利斯将军在那里向美国和法国军队投降。*法国军队在"约克镇"发挥了关键作用。他们封锁了海上*——你们可以在地图上看到——乔治·华盛顿和他的法国朋友们一起取得了胜利。

*这导致了1783年的《巴黎条约》。*《巴黎条约》由本杰明·富兰克林、约翰·亚当斯和约翰·杰伊谈判达成。他们前往巴黎谈判结束战争。他们从未完成那幅画——有趣的故事。而《巴黎条约》最终签署后，*达成了一些事项。*

**首先，英国承认美国的独立。**我们自由了。**美国的边界将延伸到密西西比河。**你们可以看到我们之前和之后的情况。*我们将一直延伸到五大湖地区。所以英国仍然控制加拿大，西班牙将控制佛罗里达和密西西比河以西的地区。*

*美国人同意做一些事情。他们必须尊重"效忠派的权利"——比如财产权等等。不仅要偿还效忠派的债务，还要偿还英国债权人的债务。战争结束后，这些不同地区将出现一些冲突。*

你们经常在AP考试中看到的一个问题是: **#美国独立战争的影响。#**所以重要的是要知道它为什么开始，以及结果是什么。其中一个重大影响是, 新的州和国家政府中更大的政治民主。你们知道，**#许多州宪法, 废除了许多旧的欧洲法律和传统。#**这方面的一个例子可以在"*许多州宪法中限制授予贵族头衔*"的规定中看到。

**#对于"共和主义"的含义, 有不同的看法——这个新国家会有多少或多民主？#民主有所增加，但也有局限性。许多州取消了投票的财产要求。**例如，宾夕法尼亚州就是一个重要的例子。他们有一个一院制立法机构，大多数白人男性都可以投票，而且没有州长。*但并非所有州都这样做。*

*#尽管出现了这种民主化，但重要的是要注意，殖民地的精英仍然掌握着权力。其他州限制了政治参与——这意味着你必须拥有财产, 才有资格投票。大多数州没有完全的民主。不幸的是，民主没有扩展到非裔美国人、妇女和美洲原住民。因此，你们将在整个美国历史上看到这种争取更大民主参与的运动。#*

**美国独立战争激发了法国、海地和拉丁美洲的革命。你**们将看到革命发生，而且**它们往往受到《独立宣言》中文字的启发。**

美国独立战争的社会影响——你们将在妇女领域真正看到这一点。她们发挥了重要作用。**当男人们外出打仗时，她们维持着农场和生意。许多妇女在大陆军周围担任护士和厨师。**甚至在战争之前，我们就看到了妇女在经济抵制中的重要性，自由之女的纺织聚会就是证明。甚至有一位马萨诸塞州的妇女穿着男人的衣服, 在军队服役了17个月。

**#由于这些贡献，妇女开始要求更多的权利。#**一位重要人物是阿比盖尔·亚当斯——约翰·亚当斯的妻子。她提醒她的丈夫“记住女士们”，并由于妇女在争取独立和建立新共和国的运动中的经历，她呼吁给予妇女更多的权利。

**有一种“共和母亲”的理想，呼吁妇女在家庭内部教授"共和主义价值观"。**因此，妇女在新共和国中发挥了非常重要的作用，她们抚养家中的孩子成为这个新国家的优秀公民。*尽管发生了一些变化，但重要的是要注意，妇女仍然被视为二等公民。#妇女没有投票权。已婚妇女不能拥有财产或签署合同。对妇女的权利有许多限制。#*

*战争期间，##美洲原住民常常站在英国一边作战。主要原因是英国限制了殖民地的扩张。##记住1763年的公告线——你们可以在地图上看到——它限制了白人定居者进入美洲原住民的土地。所以许多美洲原住民站在英国一边。#因此，当战争结束后，这对美洲原住民来说是一场巨大的失败，因为现在白人定居者可以不受限制地进入美洲原住民的土地。#*

原住民站在英国一边也并非总是如此。例如，**易洛魁联盟在这个问题上存在分歧。战争初期他们试图保持中立，然后一些部落为殖民者而战，许多其他部落为英国人而战。**但对于美洲原住民来说，重要的是要记住他们的土地现在向美国开放，一直延伸到密西西比河。

美国独立战争, 对非裔美国人社区产生了许多影响。**非裔美国人最终被允许在大陆军中作战。**许多非裔美国人为革命事业而战。**但也有一些非裔美国人为英国人而战。#弗吉尼亚的英国皇家总督邓莫尔勋爵承诺，任何为英国人对抗殖民者作战的奴隶都将获得自由。不幸的是，对于那些人来说，英国输了，所以自由没有被授予。#**

**美国独立战争后，北部和中部各州逐渐解放了奴隶。**你们知道，对许多人来说，"社会不平等"的意识日益增强——现实中奴隶制的存在,会显得“人人生而平等”的理念是虚伪的, 以及**奴隶制在这些地区经济上"不盈利"的事实。**所有这些都导致北部和中部各州给予解放。你们可以在地图上看到解放发生的年份——*最著名的是1780年宾夕法尼亚州"逐步解放法"。该法律规定不再允许奴隶进入该州，奴隶父母所生的孩子将被视为自由人。所以你们将看到北方奴隶制的逐渐消失。*

而南方——尽管奴隶制在中部和北部各州逐渐消亡，但后来奴隶制将在南方和邻近的西部地区扩张。将会发生的是，南北方之间将形成独特的地域认同——一个蓄奴，一个自由。这当然会对奴隶制产生截然不同的地域态度。每个地区——北方、南方和西部——都将拥有独特的地域认同，这最终将在以后导致问题。

正如我们将在下一个视频中看到的，奴隶制将在宪法中得到保护。所以即使它在一些地方会结束，它仍然将是美国生活结构中非常重要的一部分。

今天就到这里了。希望你们学到了很多东西，如果学到了，请点击视频的“赞”，告诉你的朋友们关于这个频道，如果你有任何问题，请在评论区提出来。下次再见，祝你们度过美好的一天。再见！

'''

== pure


What's up, everyone? Today we're taking a look at the American Revolution. We finally are becoming the USA, and we're going to help you out with all of your history needs.

So remember, in April of 1775, the shots are fired at Lexington and Concord. And a little bit later, you have the Second Continental Congress meeting in Philadelphia in May of 1775. And really, the colonies are really working together. Remember, there's been this movement towards intercolonial unity, but keep in mind there still is no clear consensus for independence. There was division amongst the colonists as to whether or not to declare independence. This was still a radical idea, and most people at this point want to try to negotiate.

At the same time they're trying to negotiate though, they are organizing the Continental Army, and they pick Mr. George Washington as their commander-in-chief. And even while they're negotiating, more battles take place. You have Bunker Hill in June of 1775. The British take the hill -- they take it from the colonists -- but the colonists hold their own, and this really builds the confidence of the colonial cause. Like, we can hold our own against the most powerful military in the world.

At the same time, the colonists sought peace by sending the Olive Branch Petition to King George the Third. They pledge their loyalty. They said they want to work with Parliament. They see themselves as British, and they're really trying to negotiate and try to prevent a larger war from occurring. Now if you're wondering why they're doing this, remember loyalty is deeply ingrained in the colonists. They believe they're part of the British Empire. They see themselves as British. Colonial unity was poor for a very long time, so rebellion was dangerous.

Now King George III though dismisses the Olive Branch Petition and declared the colonies in rebellion. He also hires some German mercenaries to handle the situation. And it is important to note that in 1775, as the fights at Bunker Hill and Lexington and Concord have taken place, there still is no clear consensus for independence amongst members of the Continental Congress.

Deeper roots of the American Revolution even before these fights started taking place, and you really have to kind of understand the ideas of the Enlightenment from the 18th and 17th century. Ideas of people like John Locke and Rousseau were strongly influencing colonial thought. And Enlightenment ideas emphasize the individual over hereditary privilege. There was an emphasis on reason and science, and you can really see this in the writings of John Locke. He said -- Locke said -- everyone has natural rights, and the power of government is derived from popular consent. And these ideas were coming over to North America and really influencing colonial society.

And you see the Enlightenment ideas very much represented in Thomas Paine's pamphlet Common Sense, which is published in January of 1776. And it makes the most clear, persuasive argument for independence today. And what he says -- a very radical idea at the time -- is he calls for the creation of a republic, a representative government based on natural rights of the people, based upon consent. He says the colonies should break away from England. He talks about a large continent cannot be run by an island -- by England. Paine's ideas are heavily influenced by the Enlightenment. He breaks them down in very simple language, and he says people could rebel against a government when it didn't protect their rights, and that's exactly what he's calling for.

And these ideas spread throughout the colonies. You get the final push for independence when Richard Henry Lee of Virginia issues a resolution saying the colonies should declare independence. Thomas Jefferson drafted the formal Declaration of Independence, and it has a couple of goals. One, you want to justify independence by listing the grievances against King George III. And you could see this if you read the Declaration of Independence -- there's a whole bunch of them. There was one that was taken out -- Jefferson wrote against slavery, ironically enough -- blaming the king and Parliament for that, and that was removed at the insistence of Southerners.

Another goal of the Declaration of Independence is to rally support amongst the colonists. Remember, not everyone favored independence. This was still a radical idea to be pursuing. They also want to get assistance from foreign nations. They want to rally them to the cause of the colonies -- get some help, some backup. And the most important part of the Declaration of Independence to this day is it is this broad appeal by declaring unalienable rights -- these ideas of natural rights -- and that the power of government rests with the people. Popular sovereignty rests with the people. And you could see a lot of John Locke's influence throughout Jefferson's writing of the Declaration of Independence.

And by July of 1776, the Declaration of Independence is formally adopted, and we America now. Before you break out the fireworks and the hot dogs and all that other good stuff that we celebrate on the 4th of July, you have to understand that colonial unity was really questionable at best.

On one side, you have the Patriots. And these are the colonists who fought against the British. They supported the American Revolution, and the largest number of them were in the New England area around Boston. But they were never a majority of the population -- anywhere between 30 to 40% of people in the colonies were patriots.

On the other side were the Loyalists. And these were, of course, colonists loyal to the British. They were opposed to independence. Numbers vary, but anywhere between 20 to 30% of people were loyalists. They were called Tories over in England, and they tended to be educated, wealthy, older, more conservative people who were connected to the monarchy or members of the Anglican clergy. They are going to have a hard time because they are going to be on the losing side. They're treated as traitors during and after the American Revolution. Their property was very often seized, and they were harassed. And a lot of them are going to leave the United States during and after the war is over.

And it's important to note there's also a third group which are those people who were neutral or apathetic. They didn't really care. You know, they were more loyal to their colony or their state, their region. They just wanted to be on their farm. So they weren't really committed to the American independence cause. And this is anywhere between about a third of the people in the colonies.

It's important you also know that this battle between England versus America -- both were coming in with certain strengths and weaknesses. On England's side, Great Britain was militarily and economically superior to the colonies. They had the best army. They had a very, very developed manufacturing sector, so they were able to provide supplies, whereas the colonists were poorly trained, poorly supplied, and so on.

As we mentioned, there was considerable loyalist opposition in the colony. So not all the colonists supported the cause. That's going to be a strength for England and a weakness for the colonies. And of course, a big colonial weakness -- we'll break down next video -- is there was a weak government structure under the Continental Congress and eventually the first national government, the Articles of Confederation. You know, the government couldn't really get the economy going. They printed paper money which was worthless. So colonies are going to have a rough time.

In spite of this rough time, the colonies are going to have certain strengths. They had, of course, greater familiarity with the land. They're fighting on their home turf. They had home field advantage. They're fighting a defensive war, meaning all they have to do is not lose, and they would win the war. And they're going to use tactics such as guerilla warfare where they're going to kind of attack when appropriate and engage in battles that are favorable to them.

They're going to have resilient military and political leadership. They're fighting for a cause that they believe in. And you're going to see great leaders like George Washington, especially as he rallies the troops at Valley Forge during a low moment in the war. And it's important to not underestimate the ideological commitment. They're fighting once again for a purpose, whereas England's fighting to keep colonies that don't want to be with them. It doesn't really have as much passion attached to it.

And another big strength for the colonies is the eventual support from European allies, especially France following the Battle of Saratoga. Make sure you know that, which leads us to our next point -- why did France help out the colonists?

One factor was France hoped to regain its power in North America and Europe. And if you recall, they suffered a bad defeat in the Seven Years' War -- the French and Indian War -- where they lost all their territory in North America. So they want some payback against England.

But there's other reasons for France to support the colonists. If England is removed from the 13 colonies, this would mean an end of British mercantile policies like the Navigation Acts that said the colonies could only trade certain goods to England. And therefore, France would be able to freely trade with the colony. So there was an economic motive.

And some elements of French society were caught up in the idealism and the Enlightenment ideas. They want to support this revolutionary movement. Ben Franklin goes over to France -- you could see him getting his bald head tickled there in that painting -- to help negotiate the treaty. And France was actually giving the colonists secret aid prior to 1778, but nothing formal -- no formal alliance until following the Battle of Saratoga. Once the colonists win that battle in 1778, France and America sign a treaty, and this provides the colonists with money, weapons, naval support -- which is hugely important because now they can have a navy on their side -- and soldiers. And really key to the American victory is going to be French assistance.

There are a lot of battles of the American Revolution. You don't need to be experts on them, but a quick rundown of some of the key ones: Lexington and Concord -- opening shots; Bunker Hill -- they technically lose -- the colonists lose -- but it kind of is a morale boost. Hey, perhaps we can actually hold our own.

It's important to understand from 1775 to 1777, things are bad for the Patriot cause. The British are occupying New York. They're occupying Philadelphia. Things aren't going too swell. You do get another victory where Washington famously crosses the Delaware River and captures the German mercenary troops at the Battle of Trenton, followed up a week later by the Battle of Princeton -- another morale boost. Hey, we're getting a win. That's always key.

Battle of Saratoga -- the British surrender to the Americans, and this brings in French assistance. France joins the war on the side of the Americans. You might want to know that following this period, later on England focused their war effort on the southern colonies. And the reason for that is there's a lot of loyalists in that region, and there's a high slave population. So therefore, they're hoping that would work to their advantage -- perhaps cause tension within the colonies and disrupt their ability to fight the war.

And make sure you know about the Battle of Yorktown, which is the final major battle in October of 1781, when General Cornwallis surrenders to the Americans and the French troops. The French military plays a key role at Yorktown. They blockaded the sea -- you could see that on the map -- and George Washington gets the victory along with his French homies.

Which leads us to the Treaty of Paris of 1783. And the Treaty of Paris is negotiated by Benjamin Franklin, John Adams, and John Jay. They headed to Paris to negotiate an end to the war. They never finish that painting -- fun story right there. And the Treaty of Paris, when it is all said and done and signed, does a couple of things.

One, England recognized the United States' independence. We are free. The boundary of the US would extend to the Mississippi River. You could see our before and after. We would go all the way up to the lakes. So England's still going to control Canada, and Spain will control Florida and the territory west of the Mississippi River.

The Americans do agree to do some things. They must respect the rights of the loyalists -- so property rights and things like that. Debt should be repaid to not only the loyalists but also to British creditors. And following the war, there will be some conflicts in these different areas.

A question you often times see on the AP exam is the impacts of the American Revolution. So important to know why it started and then what are the outcomes. And one of the big impacts is going to be greater political democracy in the new state and national governments. You know, many state constitutions abolished many old European laws and traditions. And one example of this can be seen the restrictions on allowing titles of nobility to be granted in many state constitutions.

There's different ideas of what republicanism would mean -- how much or how democratic would this new nation be? There was increases in democracy, but there were limits to it. Many states eliminated property requirements from voting. So for example, the big one is Pennsylvania. They had a unicameral legislature where most white men could vote and there was no governor. But not all states did this.

In spite of this democratization, it's important to note the colonial elite remained in power. Other states restricted political involvement -- meaning you had to own property in order to be eligible to vote. Most states did not have full democracy. It was not extended to African-Americans, women, Native Americans unfortunately. And so one of the things you're going to see throughout American history is this movement towards greater democratic participation.

The American Revolution inspired revolutions in France, Haiti, and in Latin America. And you're going to see revolutions take place, and very often they're going to be inspired by the words found in the Declaration of Independence.

Social impacts of the American Revolution -- you're really going to see this in the realm of women. They play a significant role. They maintained farms and businesses while the men were away fighting the war. Many women served as nurses and cooks following the Continental Army around. And even before the war, we saw the importance of women in the economic boycotts with the Daughters of Liberty with the spinning bees. There's even one Massachusetts woman who dressed in men's clothing and served in the Army for 17 months.

Now as a result of these contributions, women began to demand greater rights. One important figure is Abigail Adams -- wifey of John Adams. She reminded her husband to "remember the ladies," and she called for greater rights for women as a result of women's experiences in the movement for independence and the formation of a new republic.

There was this ideal of Republican Motherhood which called on women to teach republican values within the family. So women played a very important role in the new republic of raising the children of the home to be good citizens in this new nation. In spite of some of these changes, it's important to note women were still treated as second-class citizens. Women were not able to vote. Married women could not own property or sign contracts. And there were numerous restrictions on the rights of women.

During the war, Native Americans often times fought on the side of the British. And the big reason for this is the British limited colonial settlement. Remember the Proclamation Line of 1763 -- you could see on the map -- had restricted the movement of white settlers into Native American land. So many Native Americans sided with the British. So when the war was over, this was a huge defeat for Native Americans because now white settlers were unchecked into Native American land.

Siding with the British wasn't always the case. For example, the Iroquois Confederation was divided over the issue. They tried to stay neutral in the beginning of the war, and then some tribes fought for the colonists and many others fought for the British. But for Native Americans, it's important to keep in mind their land is now opened up to the United States all the way to the Mississippi River.

The American Revolution had a lot of impacts on the African-American community. African-Americans eventually were allowed to fight in the Continental Army. And there were many African-Americans who fought for the revolutionary cause. But there were also African-Americans who fought for the British. The British royal governor of Virginia, Lord Dunmore, promised freedom to any slave who fought for the British against the colonists. Unfortunately for those individuals, the British lose, so that freedom was not granted.

Following the American Revolution, there was gradual emancipation in the northern and middle states. You know, for many, there was a growing awareness of inequalities in societies -- the hypocrisy of "all men are created equal" and the fact that slavery was not economically profitable in those regions. All of those things lead to states in the North and the middle granting emancipation. You could see this on the map -- the years emancipation takes place -- and really famously with the Pennsylvania gradual emancipation law of 1780. This law said no more slaves could come into the state, and children born to slave parents would be considered free. So you're going to get the gradual disappearance of slavery in the North.

And the South -- in spite of slavery slowly kind of dying out in the middle states and the northern states, later on slavery will expand in the South and in the adjacent western lands. And what's going to happen is you're going to get distinct regional identities develop between the North and the South -- one slave, one free. This will, of course, create distinct regional attitudes towards slavery. Each area -- the North and the South and the West -- will have distinct regional identities, and this will ultimately lead into problems later on.

And as we will see in our next video, slavery will be protected in the Constitution. So even though it will end in some places, it will very much be a part of the fabric of American life.

That's going to do it for today. Hopefully you learned a whole lot, and if you did, click like on the video, tell your friends about the channel, and if you have any questions, post them in the comment section. Until next time, have a beautiful day. Peace!

'''