
= eco 2020 - (11-12)
:toc:

---


== 11. Different views of AI fuel distrust between China and America

Different views of AI *fuel*(`=to increase sth; to make sth stronger 增加；加强；刺激;/给…提供燃料`) distrust between China and America

The two countries *talk [past each other] 个自说个自的 about* its risks

中美对人工智能不同看法, 增加了两国间的互不信任感 +
两国在人工智能的风险问题上, 各持己见

Jan 18th 2020 |

IN THE DEPTHS(n.)(`=the deepest, most extreme or serious part of sth 最深处；深渊；极限`) of the cold war, American and Soviet arms-control negotiators 谈判代表；协商者 *pulled off*(`=*pull sth off* : to succeed in doing sth difficult 做成，完成（困难的事情）`) something remarkable(`=unusual or surprising in a way that causes people to take notice 非凡的；奇异的；显著的；引人注目的`): an agreement *[so]* grimly(ad.)(`=looking or sounding very serious 严肃的；坚定的；阴冷的;/unpleasant and depressing 令人不快的；令人沮丧的;严酷的`) logical *[that]* their mutual 相互的；彼此的 distrust *did not matter*.

The superpowers *pledged*(`=*~ sth (to sb/sth)* : to formally promise to give or do sth 保证给予（或做）；正式承诺`) *to stop* building(v.) new systems *to defend* their respective 分别的；各自的 homelands *against* nuclear missiles.

Their Anti-Ballistic 反弹道的；反飞弹的 Missile Treaty （国家之间的）条约，协定 *rested on* a theory of mutual deterrence(n.)(`=Deterrence is the prevention of something, especially war or crime, by having something such as weapons or punishment to use as a threat. 威慑`): the notion(`=an idea, a belief or an understanding of sth 观念；信念；理解`) that `主` the surest(`=sure的最高级`) path to nuclear-armed co-existence(n.)(`=The coexistence of one thing with another is the fact that they exist together at the same time or in the same place. 共存`) `谓` *lay 使处于特定状态（尤指困境） in* knowing(v.) that war *would lead to* catastrophe(n.)(`=a sudden event that causes many people to suffer 灾难；灾祸；横祸`) *for* both sides.

====
- respective =>  re-回,向后 + -spect-看 + -ive形容词词尾 → 各着眼点
====

在冷战最严重的时期，美国和苏联的军备控制谈判代表, 达成了一项了不起的协议: 这项协议的达成, 是建立在一个非常严峻的逻辑后果考量上, 以至于双方原有的互不信任, 也不再重要. 这两个超级大国承诺, 各自都停止建造防卫本国免受对方核导弹袭击的新系统。他们的反弹道导弹条约, 是建立在一项"互相威慑"的理论上: 即, 最可靠的保证两国核共存的路径是, 双方都认识到, 核战争会给彼此都造成毁灭性的灾难.


Today the rivalry(n.)(`=*~ (with sb/sth) (for sth) /~ (between A and B) (for sth)* :  a state in which two people, companies, etc. are competing for the same thing 竞争；竞赛；较量`) between America and China *is sliding into* its own ice age of suspicion.

Once again, new and unproved(a.)(`=If something is unproven, it has not definitely been proved to be true. 未经证实的`) technologies -- this time `主` computer systems *capable(a.) of* *performing*(v.) superhuman(a.)超出常人的；非凡的 tasks *using* machine learning and other forms of artificial intelligence (AI) -- `谓` *threaten* `宾` *to destabilise*(v.)(`=destabilize : to make a system, country, government, etc. become less firmly established or successful 使（制度、国家、政府等）动摇；使不安定；使不稳定`) the global “strategic balance” 战略平衡, by *seeming* to offer(v.) ways *to launch* a knockout(a.) 淘汰赛的；淘汰的;击败对手的一击；击倒对手获胜 blow（用手、武器等的）猛击(`=*a knockout blow* is one that hits sb so hard that they can no longer get up 击败对手的`) against a nuclear-armed adversary (辩论、战斗中的)敌手，对手, without triggering 引起；触发 an all-out(a.)(`=using or involving every possible effort and done in a very determined way 全力以赴的`) war.

====
- knockout : a. ( especially BrE ) *a knockout competition* is one in which the winning player/team at each stage competes in the next stage and the losing one no longer takes part in the competition 淘汰赛的；淘汰的 +
-> *the knockout stages* of the tournament 锦标赛的淘汰赛阶段
====

今天，美国和中国之间的竞争, 正在滑入彼此嫌疑的冰河时代。又一次，拥有了未经检验的新技术 -- 这次是计算机能借助机器学习和人工智能, 来执行非凡的任务 -- 这个新技术, 似乎提供了一些方法，可以在不引发全面战争的情况下，对拥有核武器的对手发动致命一击，从而改变全球“战略平衡”的稳定。

`主` A report *issued* in November by America’s National Security Commission 国家安全委员会 on Artificial Intelligence, a body *created by* Congress and *chaired 担任（会议、讨论等的）主席；主持（会议、讨论等） by* ① Eric Schmidt, a former boss of Google, and ② Robert Work, who *was* deputy 副手；副职；代理 defence secretary 国防部长 from 2014-17, `谓` *ponders*(`=*~ (about/on/over sth)* : ( formal ) to think about sth carefully for a period of time 沉思；考虑；琢磨`) how AI systems *may reshape* global balances of power, *as dramatically 显著地，剧烈地 as* electricity *changed* warfare(`=the activity of fighting a war, especially using particular weapons or methods 战；作战；战争`) and society in the 19th century.

Notably 尤其；特别, it *focuses on* the ability of AI *to “find* the needle in the haystack 干草堆；干草垛”(`=*a needle in a haystack* : a thing that is almost impossible to find 草垛里的针；几乎不可能找到的东西`), by *spotting*(`=to see or notice a person or thing, especially suddenly or when it is not easy to do so 看见；看出；注意到；发现`) patterns and anomalies(`=anomaly : *~ (in sth)* : a thing, situation, etc. that is different from what is normal or expected 异常事物；反常现象`) in vast pools of data.

====
- anomaly => 前缀an-, 无，没有。-om, 同homo-, 同same,此处h脱落。即不一样，反常。
====
去年11月, 美国国家安全委员人工智能领域部, 该机构由美国国会批准创立, 并由 谷歌前任老板 Eric Schmidt , 和 美国国防副部长 Robert Work 主持. 该部门发布了一份报告. 其中仔细考虑了 人工智能AI会如何重塑全球力量平衡, 就如同19世纪时的电力发明, 剧烈地改变了当时的战争和社会一样. 特别是, 该报告聚焦于AI的“大海捞针”能力, 能在海量数据中, 发现出模式规律, 和异常现象.

[In a medical setting(n.)(`=a set of surroundings; the place at which sth happens 环境；背景`)] AI *can find* tumours 肿瘤 that radiologists(`=a doctor who is trained in radiology 放射科医生；X光科的医生`) *miss*.

In a military context, it *may one day find* the stealthiest(a.)(`=stealthy : doing things quietly or secretly; done quietly or secretly 偷偷摸摸的；不声张的；秘密的`) nuclear-armed submarines, wherever they *lurk*.

The commission *is* blunt(a.)(`=very direct; saying exactly what you think without trying to be polite 嘴直的；直言的;/不锋利的；钝的`).

Nuclear deterrence(n.)威慑 *could be undermined* 逐渐削弱（信心、权威等）；使逐步减少效力; 从根基处破坏；挖…的墙脚 if AI-equipped systems *succeed* in *tracking 跟踪；追踪 and targeting* 把…作为攻击目标；把…作为批评的对象 previously invulnerable(a.)(`=*~ (to sth)* : that cannot be harmed or defeated; safe 不会受伤害的；打不败的；安全的`) military assets.

That in turn *could increase* incentives(n.)(`=*~ (for/to sb/sth) (to do sth)* : something that encourages you to do sth 激励；刺激；鼓励`) for states, in a crisis(`=a time of great danger, difficulty or confusion when problems must be solved or important decisions must be made 危机；危急关头`) 在危急时刻, *to launch* a devastating(a.)(`=causing a lot of damage and destruction 破坏性极大的；毁灭性的`) pre-emptive(a.)(`=done to stop sb taking action, especially action that will be harmful to yourself 先发制人的`) strike.

`主` China’s rise *as* an AI power `谓` *represents* the most complex strategic challenge 战略挑战 that America *faces*, the commission *adds*, because the two rivals’ tech sectors *are so entangled*(`=*~ sb/sth (in/with sth)* : to make sb/sth become caught or twisted in sth 使纠缠；缠住；套住`) *by* commercial, academic and investment ties(`= a strong connection between people or organizations 联系；关系；纽带;/ 绳子；金属丝；线`).

在医疗环境中，人工智能可以发现放射科医生忽略的肿瘤。在军事环境中，人工智能有一天就可能会发现最隐秘的核潜艇，无论它们潜伏在哪里。委员会的人很直率地表达道。如果配备人工智能的系统, 能够成功地跟踪到以前安全的军事财产, 并把它们当做袭击目标，则原来靠核威慑就能带来的安全保障, 就有可能会被削弱。这反过来又会增加各国的动机, 在危机时刻, 先发制人来进行毁灭性的打击. 该委员会补充称，中国崛起为人工智能强国，表明美国面临着最复杂的战略挑战，因为这两个竞争对手的科技领域, 已经在商业、学术和投资层面, 深深融合。

The good news *is that* China’s national-security  国家安全 establishment(`=an organization, a large institution or a hotel 机构；大型组织；企业；旅馆; /(usually *the Establishment*) [ sing.+sing./pl.v. ] (often disapproving) the people in a society or a profession who have influence and power and who usually do not support change （通常反对变革的）当权派，权势集团；（统称）权威人士`) *is also sobered*(`=to make sb behave or think in a more serious and sensible way; to become more serious and sensible （使）变得持重，变得冷静;/未醉`) *by* AI’s potential 潜力；潜质.

====
- establishment : (usually *the Establishment*) [ sing.+sing./pl.v. ] ( often disapproving ) *the people in a society or a profession who have influence and power and who usually do not support change* （通常反对变革的）当权派，权势集团；（统称）权威人士+
-> *the medical/military/political, etc. establishment* 医学界、军界、政界等当权派 +
-> young people rebelling against *the Establishment* 反对当权者的年轻人
====

*Drawing on*(`=*draw on/upon sth* : to use a supply of sth that is available to you 凭借；利用；动用`) the example of arms-control talks(n.)(`=*talks* [pl.] ~ (between A and B) (on/over sth) formal discussions between governments or organizations （政府或组织之间正式的）洽谈，会谈，谈判`) during the cold war, Chinese officials and scholars *have begun talking to* Americans and Europeans *about* its dangers.

With(`=because of; as a result of 因为；由于；作为…的结果;/because of sth and as it happens 由于；随着`) many government channels of communication *suspended*(`=to officially stop sth for a time; to prevent sth from being active, used, etc. for a time 暂停；中止；使暂停发挥作用（或使用等）`) *by* the Trump administration, much of the jaw-jaw(n.)长谈；冗长乏味的讨论 *involves* recently retired Americans 分词作状语 *meeting*(v.) serving(a.)在职服务的 and former Chinese intelligence 情报 and military officers, diplomats and scholars.

好消息是，中国的国家安全机构, 也意识到了人工智能的潜力。借鉴于冷战时期的军备控制谈判，中国官员和学者, 已经开始与美国和欧洲的同行, 探讨起人工智能的危险面。由于两国政府间的许多沟通渠道, 已经被特朗普政府暂停，所以很多这样的对话, 就邀请了最近退休的美国业内人士, 同中国情报界的现役的和前任的军事官员、外交官和学者来会面。
====
- With : +
(1) *because of; as a result of* 因为；由于；作为…的结果 +
-> She blushed *with embarrassment*. 她难为情得脸红了。 +
-> His fingers were numb *with cold*. 他的手指冻麻了。 +
(2) *because of sth and as it happens* 由于；随着 +
-> The shadows lengthened *with the approach of sunset*.
随着太阳西沉，影子越来越长。 +
-> Skill comes *with practice*. 熟能生巧。
====

Chaguan *was allowed to attend* one such dialogue recently *held* in Beijing and Shanghai.

The Americans *were led by* Mathew Burrows of the Atlantic Council 大西洋理事会(智库), a Washington-based think-tank. His previous career 生涯；职业 in the CIA *included* preparing(v.) forecasts of global trends for incoming presidents.

The Chinese organiser 组织者；发起人 *was* Xiang Lanxin of _the Graduate 学士学位获得者 Institute of International and Development Studies_ in Geneva 日内瓦（瑞士西南部城市）, who *also heads*(`=to lead or be in charge of sth 领导；主管`) the Shanghai-based Centre for _One Belt, One Road_ and Eurasian(`=of or connected with both Europe and Asia 欧亚的`) Security.

茶馆栏目, 被允许参加最近在北京和上海举行的这样一次对话。美方由华盛顿智库大西洋理事会(Atlantic Council)的 Mathew Burrows 率领。他之前在CIA的工作经历, 包括为即将上任的总统, 准备全球趋势的预测。中方的组织者, 是日内瓦国际与发展研究所的 Xiang Lanxin，他也是上海一带一路和欧亚安全中心的负责人。

Chinese views *are not* monolithic(a.)(`=If you refer to an organization or system as monolithic, you are critical of it because it is very large and very slow to change, and does not seem to have different parts with different characters. 大一统的;铁板一块的`).

Some officials *sound* gung-ho(a.)(`=too enthusiastic about sth, without thinking seriously about it, especially about fighting and war （尤指对战斗和战争）偏激的，狂热的，莽撞的`) about AI *as* a path to prosperity(n.)繁荣，成功 and development, with few qualms(n.)(`=qualm : *~ (about sth)* : a feeling of doubt or worry about whether what you are doing is right （对自己行为的）顾虑，不安`) about privacy or *lost jobs*.

====
- gung-ho => 来自汉语"工合"，即早期的"工业合作组织"。被西方人误解成一种激进的，偏激的组织或口号。
- qualm => 来自古英语cwealm,死亡，谋杀，折磨，*词源同 kill*, quell.引申词义有死亡危险的，恐惧的，后词义弱化为顾虑，不安。
====

Still, other Chinese *fret*(v.)(`=*~ (about/over sth)* ( especially BrE ) to be worried or unhappy and not able to relax 苦恼；烦躁；焦虑不安`) *about* AI that *might put* winning a war [*ahead of* global stability], like some game-playing 博弈 doomsday(n.)最后审判日，世界末日（基督教认为在这一天世人都将接受上帝的审判） machine.

Chinese officials *have studied* initiatives(n.)(`=a new plan for dealing with a particular problem or for achieving a particular purpose 倡议；新方案`) such as the “Digital Geneva Convention”(`=an official agreement between countries or leaders （国家或首脑间的）公约，协定，协议`) *drafted by* Microsoft, a technology giant.

This *would require* states *to forswear*(`=to stop doing or using sth; to make a promise that you will stop doing or using sth 放弃；发誓戒除`) cyber-attacks on *such* critical infrastructure *as* power grids 电力网, hospitals and international financial systems. AI would make *it* easier *to locate and exploit*(`=to treat a person or situation as an opportunity to gain an advantage for yourself 利用（…为自己谋利）`) vulnerabilities(`=vulnerability : 易损性；弱点`) in these.

====
- forswear => 1.发誓弃绝，来自来自for-, 完全的，swear, 发誓。 2.发伪誓，来自来自for-, 否定，相反，swear, 发誓。
====

中方参与人士的观点并不统一。一些官员听起来对人工智能充满热情，认为它是一条通向繁荣与发展的路径，而不担心AI会带来的隐私泄露和失业的问题. 然而, 也有一些中方人士担心, 人工智能可能会把赢得一场战争的优先度, 看得比保持全球稳定更重要，就像一些玩博弈的末日机器一样。中国的官员研究了科技巨头微软起草的《数字日内瓦公约》等倡议。它要求各国放弃对电网、医院和国际金融系统等关键基础设施的网络攻击。人工智能将使定位和利用这些设施的漏洞, 变得更容易实现。

The bad news *is that* `主` agreeing(v.) on rules for AI `系` *is* even harder than *wrangling*(`=wrangle : *~ (with sb) (over sth) /~ (between A and B)* : an argument that is complicated and continues over a long period of time （长时间的）争论，争吵`) *over* nuclear arsenals （统称）武器; 兵工厂,武器库.

One obstacle *is* physical. Warheads （导弹的）弹头 or missile defences *can be counted*(`=*~ (from sth) (to/up to sth)* to say numbers in the correct order （按顺序）数数`) by weapons inspectors(`=a person whose job is to visit schools, factories, etc. to check that rules are being obeyed and that standards are acceptable 检查员；视察员；巡视员`).

In contrast, rival powers *cannot safely show off*(`=to show people sb/sth that you are proud of 炫耀；卖弄；显示`) their most potent(`=powerful 强大的；强有力的`) algorithms, or even *describe* AI capabilities in a verifiable(`=Something that is verifiable can be proved to be true or genuine. 可证实的`) way.

====
- wrangle => 来自PIE wrengh,弯，转，来自PIE wergh的鼻音形式，词源同wring,wriggle。引申词义纠缠，扭打，争吵。
====

坏消息是，就人工智能的规则达成一致，甚至比就核武库的规则展开争论, 还要困难。其中一个障碍是物理上的。导弹弹头或导弹防御系统, 可由武器检查员统计数量。但相比之下，竞争对手不能安全地炫耀他们自己的最强大的AI的程序算法，甚至无法以可验证的方式来描述人工智能能力。

Other obstacles *are* philosophical 哲学的.

*Seeking* areas *for* co-operation, Chinese participants in the recent dialogue *cited*(`=*~ sth (as sth)* : to mention sth as a reason or an example, or in order to support what you are saying 提及（原因）；举出（示例）；列举`) counter-terrorism.

They *suggested*, for instance, *that* AI’s predictive(a.)(`=connected with the ability to show what will happen in the future 预测的；预言的；前瞻的`) powers *might direct*(`=to control or be in charge of sb/sth 管理；监督；指导;/*~ sb (to...)* : to tell or show sb how to get to somewhere or where to go 给（某人）指路；为（某人）领路`) American and Chinese agents *to* shipping(n.) containers 海运集装箱 hiding drugs, or *help* police *track* extremists(`=a person whose opinions, especially about religion or politics, are extreme, and who may do things that are violent, illegal, etc. for what they believe 极端主义者；极端分子；过激分子`) *lurking* among citizens *returned from* Syria, Iraq or other trouble-spots.

Both sides readily(`=in a way that shows you do not object to sth 欣然地；乐意地;/quickly and without difficulty 快捷地；轻而易举地；便利地`) *agree on* the need for co-operation in the search for smuggled 走私; 偷运 fentanyl 芬太尼; 止痛剂.

其他的障碍在于哲学上。在寻求合作领域时，中国在最近的对话中提到了反恐。例如，他们提出，人工智能的预测能力, 或许能够指导美国和中国的特工找到藏匿毒品的集装箱，或者帮助警方追踪那些极端分子 -- 他们会潜藏在从叙利亚、伊拉克或其他动乱地区返回的人民中。双方也一致同意, 有必要进行合作, 来发现走私的芬太尼毒品。
====
- fentanyl : 芬太尼. 它的药效比海洛因强50倍，已经迈进流行毒品的行列，受到政府的严格管制。 +
芬太尼的另一种衍生物, 叫卡芬太尼（carfentanil）, 更强效，药效是芬太尼的100倍，海洛因的5000倍，吗啡的10000倍。只要0.02克，就足以使一名成年人毙命。
====

But Western alarm bells 警钟 *quickly sound* over China’s enthusiasm for algorithms *trained* to finger(v.)(`=*~ sb (for sth) /~ sb (as sth)* ( informal ) ( especially NAmE ) to accuse sb of doing sth illegal and tell the police about it 告发；告密;/用手指触摸`) potential offenders(`=a person who commits a crime 犯罪者；违法者；罪犯`) before they *break the law*.

Westerners *worry especially about* so-called “black box” algorithms, powerful systems that *generate* seemingly accurate results but `主` whose reasoning(n.)(`=the process of thinking about things in a logical way; opinions and ideas that are based on logical thinking 推想；推理；理性的观点；论证`) `系` *is* a mystery *even to* their designers.

====
- reasoning : n. +
-> What is *the reasoning* behind this decision? 作出这个决定的依据是什么？ +
-> *This line(`=a method or way of doing or thinking about sth 方法；方式`) of reasoning* is faulty. 这样的思路有问题。
====

When machine learning *uses* past data *to predict* future actions, that *prompts*(`=to make sb decide to do sth; to cause sth to happen 促使；导致；激起`) soul-searching 反省；内省 about *entrenching*(v.)(`=to establish sth very firmly so that it is very difficult to change 使处于牢固地位；牢固确立`) prejudice 偏见；成见 via algorithm.


====
- entrench => en-, 进入，使。-trench, 砍，切，词源同trench, truncate. 即切进去，牢固树立。 +
-> Sexism *is deeply entrenched*(v.) in our society. 性别歧视在我们这个社会根深蒂固。 +
-> *entrenched attitudes*/interests/opposition 顽固的态度；固有的利益团体；顽固的反对
====
但西方国家很快就对中国热衷使用AI算法, 警惕起来，因为这些算法经过训练，能够将潜在的违法者, 在犯罪之前, 就将其识别出来。西方人尤其担心所谓的“黑盒”算法，这是一种强大的系统，可以产生看起来好像是精确的结果，但是该AI算法, 到底是怎么推理得出那些结论的, 甚至对其设计者来说都是一个谜。当机器学习, 使用过去的数据来预测未来的行为时，它的数据集, 可能会使算法产生具有"偏见"的结论. 人们已经对此进行自我反省。

Last year a hearing(n.)(`=an official meeting at which the facts about a crime, complaint, etc. are presented to the person or group of people who will have to decide what action to take 审讯；审理；听审；听证会`) in America’s Congress *weighed* the impact of facial-recognition technology on civil rights.

Yet China *shows* few such qualms(n.)(`=a feeling of doubt or worry about whether what you are doing is right （对自己行为的）顾虑，不安`) as it *rolls out*(`=to officially make a new product available or start a new political campaign 正式推出（新产品）；开展（新的政治运动）; / to make sth flat by pushing sth over it 将…轧平`) AI-powered surveillance(n.)（对犯罪嫌疑人或可能发生犯罪的地方的）监视 systems that *draw on* data sets （数学中的）集，集合 *filled with* past misdeeds(n.)(`=misdeed : a bad or evil act 恶行；不义之举`) and anti-social acts, or simple biases(`=bias : 偏见；偏心；偏向`).

Some *use* ethnic 种族的；人种的 profiling(n.)(`=the act of collecting useful information about sb/sth so that you can give a description of them or it （有关人或事物的）资料搜集`), most notoriously 众所周知地；声名狼藉地；恶名昭彰地 in the western region of Xinjiang, where Muslim minorities *are deemed* prone(a.) to “mistaken thinking”.

====
- misdeed => mis-,坏的，错的，不好的，deed,行为。
- profiling => 来自profile,画出轮廓，概括，-ing,名词后缀。特殊用法。
====

去年，美国国会举行了一场"关于面部识别技术对公民权利影响"的听证会。然而，中国在推出基于AI的监控系统时, 却对其后果很少有顾虑. 而这个监控系统, 利用的数据集, 是充满了每位公民过去曾经做过的不当行为, 反社会行为, 甚至就是简单的基于偏见的认识. 有些还使用种族相关的资料搜集, 最臭名昭著的就是用在新疆西部地区，那里的穆斯林少数民族, 被认为是容易产生“错误的想法”。


*Don’t trust, can’t verify*

不能相信，也无法验证

Repeatedly  反复地；再三地；屡次地, Chinese participants 参与者；参加者 in the dialogue *downplayed*(`=downplay : to make people think that sth is less important than it really is 对…轻描淡写；使轻视；贬低`) their country’s AI prowess(n.)(`=great skill at doing sth 非凡的技能；高超的技艺；造诣`).

One *said that* China’s military applications （尤指理论、发现等的）应用，运用 *were* ten or 20 years behind America’s. “If I *were* America, I *wouldn’t worry*,” he *chuckled*(`=*~ (at/about sth)* : to laugh quietly 低声轻笑；轻声地笑`).

There *were* many calls(n.)(`=*~ (for sth)* : a request, an order or a demand for sb to do sth or to go somewhere 要求；请求；呼吁`) for America *to remain open to* Chinese students and tech firms.

“Generally speaking, China *wants to learn from* the United States, while the US *sees* China *as* a rival,” a Chinese official *complained*.

[To hawks in Washington] such talk *is* a trick 诡计；花招；骗局；把戏: an appeal *to keep assisting*(`=assist : *~ (sb) (in/with sth) /~ (sb)* (in doing sth) to help sb to do sth 帮助；协助；援助; / to help sth to happen more easily 促进`) China’s mastery(n.)(`=*~ (of sth)* : great knowledge about or understanding of a particular thing 精通；熟练掌握; /*~ (of/over sb/sth)* : control or power 控制；驾驭；控制力量`) of AI, and *to forget* the risks.

Chinese AI experts *might protest*(`=*~ (about/against/at sth)* : to say or do sth to show that you disagree with or disapprove of sth, especially publicly （公开）反对；抗议; /to say firmly that sth is true, especially when you have been accused of sth or when other people do not believe you 坚决地表示；申辩`) *that* they *are damned*(`=to criticize sb/sth very strongly 强烈指责；谴责；狠狠批评`) if they *seek* co-operation with America, and *damned* if they *do not*. That, alas （表示悲伤或遗憾）哎呀，唉, *is* the logic of distrust.

====
- prowess => 来自prow,勇敢的，-ess,名词后缀。引申词义非凡的技能，造诣。
====

参与对话的中国官员, 一再淡化中国的人工智能的能力。有的说，中国的军事应用技术, 比美国落后10年或20年。“如果我是美国人，我就不会担心，”他笑着说。许多人呼吁美国对中国学生和科技公司保持开放。“一般来说，中国希望向美国学习，而美国则将中国视为竞争对手，”一位中国官员抱怨道。对华盛顿的鹰派来说，这样的解释, 只是一个诡计: 中国呼吁美国继续协助中国掌握人工智能，并忘掉其中的风险。对此, 中国的人工智能专家可能会反对称，他们去寻求与美国合作，会挨批; 不合作，也会挨批。唉，这种逻辑就是源于对中国的不信任。


---

== 11. Different views of AI fuel distrust between China and America 纯净版


The two countries *talk [past each other] about* its risks

Jan 18th 2020 |

IN THE DEPTHS of the cold war, American and Soviet arms-control negotiators *pulled off* something remarkable: an agreement *so* grimly logical *that* their mutual distrust did not matter. The superpowers *pledged* to stop building new systems *to defend* their respective homelands *against* nuclear missiles. Their Anti-Ballistic Missile Treaty *rested on* a theory of mutual deterrence: the notion (that the surest(a.) path to nuclear-armed co-existence *lay in* knowing that war *would lead to* catastrophe for both sides).

Today the rivalry between America and China *is sliding into* its own ice age of suspicion. Once again, new and unproved technologies -- [this time] `主` computer systems capable of *performing* superhuman tasks *using* machine learning and other forms of artificial intelligence (AI) -- `谓` *threaten* to destabilise(v.) the global “strategic balance”, by *seeming* to offer ways to launch a knockout blow against a nuclear-armed adversary, without *triggering* an all-out war.

`主` A report *issued* in November by America’s National Security Commission on Artificial Intelligence, a body *created by* Congress and *chaired by* Eric Schmidt, a former boss of Google, and Robert Work, who was deputy(a.) defence secretary from 2014-17, `谓` *ponders* how AI systems *may reshape* global balances of power, *as dramatically as* electricity *changed* warfare and society in the 19th century. Notably, it *focuses on* the ability of AI *to “find* the needle in the haystack”, by *spotting* patterns and anomalies *in* vast pools of data. [In a medical setting] AI *can find* tumours that radiologists *miss*. In a military context, it *may one day find* the stealthiest nuclear-armed submarines, wherever they *lurk*. The commission is blunt. Nuclear deterrence(n.) *could be undermined* if AI-equipped systems *succeed* in tracking(v.) and targeting(v.) previously invulnerable military assets. That in turn *could increase* incentives for states, in a crisis, *to launch* a devastating pre-emptive strike. China’s rise *as* an AI power *represents* the most complex strategic challenge that America *faces*, the commission *adds*, because the two rivals’ tech sectors *are* `表` *so entangled by* commercial, academic and investment ties.

The good news *is that* China’s national-security establishment *is also sobered* by AI’s potential. *Drawing on* the example of arms-control talks during the cold war, Chinese officials and scholars *have begun `宾` talking to* Americans and Europeans about its dangers. *With* many government channels of communication *suspended* by the Trump administration, much of the jaw-jaw *involves* recently retired Americans [*meeting*(v.) serving(a.) and former Chinese intelligence and military officers, diplomats and scholars]. Chaguan *was allowed* to attend(v.) one such dialogue *recently held* in Beijing and Shanghai. The Americans *were led* by Mathew Burrows of the Atlantic Council, a Washington-based think-tank. His previous career in the CIA *included* `宾` *preparing* forecasts of global trends *for* incoming presidents. The Chinese organiser *was* Xiang Lanxin of the Graduate Institute of International and Development Studies in Geneva, who also *heads* the Shanghai-based Centre for One Belt, One Road and Eurasian Security.

Chinese views *are not* monolithic(a.). Some officials *sound* gung-ho(a.) about AI as a path to prosperity and development, *with few qualms(n.) about* privacy or lost jobs. Still, other Chinese *fret(v.) about* AI that *might put* winning a war *ahead of* global stability, like some game-playing doomsday machine. Chinese officials *have studied* initiatives such as the “Digital Geneva Convention” *drafted by* Microsoft, a technology giant. This *would require* states *to forswear*(v.) cyber-attacks on *such* critical infrastructure *as* power grids, hospitals and international financial systems. AI would make *it* easier *to locate and exploit* vulnerabilities in these.

The bad news *is that* {*agreeing on* rules for AI *is* even harder [than *wrangling over* nuclear arsenals]}. One obstacle *is* physical. Warheads or missile defences *can be counted* by weapons inspectors. In contrast, rival powers *cannot safely show off* their most potent algorithms, or even *describe* AI capabilities in a verifiable way.

Other obstacles *are* philosophical. *Seeking* areas *for* co-operation, Chinese participants in the recent dialogue *cited* counter-terrorism. They *suggested*, for instance, *that* AI’s predictive powers *might direct* American and Chinese agents *to* shipping(n.) containers hiding drugs, or *help* police *track* extremists *lurking* among citizens *returned from* Syria, Iraq or other trouble-spots. Both sides *readily agree on* the need for co-operation in the search for smuggled fentanyl. But Western alarm bells *quickly sound* over China’s enthusiasm for algorithms *trained* to finger(v.) potential offenders [before they *break the law*]. Westerners *worry especially about* so-called “black box” algorithms, powerful systems that *generate* seemingly accurate results *but* whose reasoning *is* a mystery even to their designers. When machine learning *uses* past data *to predict* future actions, that *prompts* soul-searching about *entrenching* prejudice *via* algorithm. Last year a hearing in America’s Congress *weighed* the impact of facial-recognition technology *on* civil rights. Yet China *shows* few such qualms *as* it *rolls out* AI-powered surveillance systems that *draw on* data sets *filled with* past misdeeds and anti-social acts, or simple biases. Some *use* ethnic profiling, most notoriously in the western region of Xinjiang, where Muslim minorities *are deemed* prone(a.) to “mistaken thinking”.

*Don’t trust, can’t verify*

Repeatedly, Chinese participants in the dialogue *downplayed* their country’s AI prowess. One *said that* China’s military applications *were* ten or 20 years behind America’s. “If I *were* America, I *wouldn’t worry*,” he *chuckled*. There *were* many calls for America *to remain open to* Chinese students and tech firms. “Generally speaking, China *wants to learn from* the United States, while the US *sees* China *as* a rival,” a Chinese official *complained*. [To hawks in Washington] such talk *is* a trick: an appeal *to keep assisting* China’s mastery(n.) of AI, and *to forget* the risks. Chinese AI experts *might protest that* they *are damned* [if they *seek* co-operation with America], and *damned* [if they *do not*]. That, alas, *is* the logic of distrust.

---


== 12. Life is getting harder for foreign VCs(`=Venture Capital 风险投资`) in China

They *must contend with* mature homegrown(a.)(蔬菜、水果) 家种的; 本国产的 rivals *and* skittish(a.)(`=not very serious and with ideas and feelings that keep changing (人)轻浮的；易变的；反复无常的; /(of horses 马) easily excited or frightened and therefore difficult to control 易惊而难以驾驭的;/(business 商) ( especially NAmE ) likely to change suddenly 说变就变的；变幻莫测的`) American investors

====
- skittish => 来自古义 skit,轻快的跑，唐突无礼的女孩，引申词义轻浮的，易变的，比喻义（市场）变幻 莫测的。
====

外国风投在中国的日子越来越不好过了 +
他们必须与成熟的本土竞争对手, 和敏感的美国投资者, 竞争

Jan 11th 2020 | SHANGHAI

`主` THE FIRST “demo day” in Beijing last November of Y Combinator (YC) `谓` *hosted* two dozen local startups 新创办的小公司 *vying*(`=vie : *~ (with sb) (for sth)* : (formal) to compete strongly with sb in order to obtain or achieve sth 激烈竞争；争夺`) *for* the attention of high-profile(a.)(`=receiving or involving a lot of attention and discussion on television, in newspapers, etc. 经常出镜（或见报）的；高姿态的`) investors.

====
- combination : (1) two or more things joined or mixed together to form a single unit 结合体；联合体；混合体 +
(2) *the act of joining or mixing together two or more things to form a single unit* 结合；联合；混合 +
-> The firm is working on a new product *in combination with* several overseas partners. 这家公司与几家海外合伙人在联合开发新产品。

- Y Combinator : 是美国著名创业孵化器. 总部位于美国加州山景城.
====

It *marked*(`=to be a sign that sth new is going to happen 是…的迹象；成为…的征兆；表明`) the entrance into China of Silicon Valley’s most famous accelerator （汽车等的）加速装置，油门;（基本粒子）加速器, which *has helped* launch(v.) the likes(n.)(`=like : a person or thing that is similar to another 类似的人（或物）`) of Airbnb and Dropbox.

Then, days later,YC *abruptly announced* it *was pulling out of*(`=*pull out (of sth)* : to move away from sth or stop being involved in it 脱离；退出; / (of a train 火车) to leave a station 驶离车站；出站`) the country.

去年11月，Y Combinator (YC)在北京举办的首个“演示日”，吸引了20多家本土初创企业，它们争相吸引知名投资者的注意力。这标志着硅谷最著名的加速器进入中国，帮助推出了Airbnb和Dropbox等公司。几天后，YC突然宣布退出该国。

[In a statement] YC *said that* it *was returning*, under a new boss, *to investing in* startups [from its Californian base].

Its Chinese startups *will be nurtured*(`=to care for and protect sb/sth while they are growing and developing 养育；养护；培养`) *by* MiraclePlus, YC China’s new, fully localised 使地方化, 停留在一地方, 本地化 incarnation(`=a period of life in a particular form （某一段时间内的）化身`).

====
- YC撤出国内后，只带走了品牌。陆奇接过了本地团队，成立了 MiraclePlus (奇迹创坛). 他在加入YC中国时说过，“在目前的全球环境下，要真正实现我们‘建于中国(by China)、为了中国(for China)、属于中国(of China)’的初心，我们必需有能力掌握自己的命运。”. MiraclePlus 与美国 YC 没有任何关系.
====

Yet in the context of a deepening Sino-American rift(`=a serious disagreement between people that stops their relationship from continuing 分裂；分歧；严重不和; /断裂；裂缝；裂口`), the retreat *looks* ominous(a.)(`=suggesting that sth bad is going to happen in the future 预兆的；恶兆的；不吉利的`).

====
- ominous => 来自omen,预兆，预示，-ous,形容词后缀。即有预兆的，在早期也可指吉兆，现仅用来指凶兆，不祥的。
====

“Under the current global environment, *to realise*(`=realize : to achieve sth important that you very much want to do 实现；将…变为现实`) our mission -- By China, For China, Of China -- we *must have* the ability *to master*(`=to gain control of an animal or a person 控制（动物或人）;/控制（情绪）`) our own destiny,” *wrote* MiraclePlus in a social-media post, *citing* Lu Qi 陆奇, its boss, whom (YC *had hired*(`=to give sb a job 聘用；录用；雇用`) to set up its Chinese arm in 2018). (Mr Lu *declined*(`=to refuse politely to accept or to do sth 谢绝；婉言拒绝`) *to be interviewed* for this article.)

YC在一份声明中表示，在新老板的领导下，该公司将重新从其加州基地, 来投资美国的初创企业。而其中国的初创企业, 将由MiraclePlus 来培育，MiraclePlus 是YC中国的全新的, 完全本地化的化身(但与YC美国没有任何关系)。然而，在中美裂痕不断加深的背景下，这种撤退看起来是不祥的。“在目前的全球环境下，要真正实现我们‘建于中国(by China)、为了中国(for China)、属于中国(of China)’的初心，我们必需有能力掌握自己的命运。” MiraclePlus的社交媒体账号上写道, 该账号其实是引用了其老板陆奇的话语. 在2018年，YC聘请陆奇成立了中国分公司。(陆奇拒绝就本文接受采访。)

At first glance, YC’s fate *seems* at odds with(`=*BE AT ODDS (WITH STH)* : to be different from sth, when the two things should be the same （与…）有差异，相矛盾`) the broader 广大的；一片的(比较级) health of foreign venture(`=a business project or activity, especially one that involves taking risks （尤指有风险的）企业，商业，投机活动，经营项目`) capital (VC) in China, with its red-hot(a.)(`=so hot that it looks red  (金属或燃烧物) s炽热的；赤热的；热得发红的;/new, exciting and of great interest to people 热门的`) tech industry.

`主` The Chinese operations(`=the activity or work done in an area of business or industry （工商业）活动，业务`) of Sand Hill Road heavyweights(n.)(`=heavyweight : a very important person, organization or thing that influences others 有影响力的人（或组织、事物）`) such as Lightspeed Venture Partners 光速创投 and Sequoia 红杉 Capital -- whose fifth Chinese growth-stage 成长阶段 fund *raised* $1.8bn, twice as much as its last -- `谓` *are thriving*.

====
- Sand Hill Road : 沙山路. 硅谷一个普通地名, 它只有两三公里长，却有十几家大型风险投资公司. 其中最著名的包括红杉资本(SequoiaCapital，在中国称作红杉风投)、KPCB(Kleiner，Perkins，Caufield&Byers)、NEA(NewEnterpriseAssociates)、Mayfield等等。 +
如同美国的"华尔街"是"金融业"的代名词一样，硅谷的"沙山路"则是"风险投资公司"的代名词. 华尔街的投行投资的多为金融和传统产业，风投公司投资的多为高新技术企业。
====
乍一看，YC的命运, 似乎与外国的风险投资基金们, 在中国的普遍良好的财务健康度, 相矛盾, 因为中国的科技行业非常火爆。沙山路(Sand Hill Road)的重量级企业，如光速创投(Lightspeed Venture Partners)和红杉资本(Sequoia capital)的中国业务, 正在蓬勃发展。红杉资本的第五个中国成长基金, 募集了18亿美元，是上一个阶段的两倍。

Chinese founders （组织、机构等的）创建者，创办者，发起人 *have coveted*(v.)(`= to want sth very much, especially sth that belongs to sb else 渴望；贪求（尤指别人的东西）；觊觎`) attention *from* foreign funds, *seen as* the best route *to listing on* American exchanges(`=exchange : 交易所`) and keener(a.)(`=*keen on sb/sth/on doing sth* : ( BrE informal ) liking sb/sth very much; very interested in sb/sth 喜爱；（对…）着迷，有兴趣`) than Chinese counterparts *to back*(`=to give help or support to sb/sth 帮助；支持; /下赌注于（赛马、参赛队伍等）`) ideas that *take longer to make money*.

====
- covet => 来自拉丁词cupio, 渴求，词源同 Cupid(罗马爱神-丘比特), cupidity, hope.
====

Their dollar-denominated(v.)(`=to express an amount of money using a particular unit 以（某种货币）为单位`) funds *have* durations of ten years or more, whereas yuan 元（中国货币单位） investors *usually want* a return in five. (Most foreign VCs *now also raise* yuan funds, which *enable* exits(v.) on mainland stockmarkets and *investments in* more industries.)

Foreigners *offer*(v.) expertise 专门知识；专门技能；专长 [*on top of*(`=*on top of sth/sb* : in addition to sth 除…之外`) cheques 支票, especially *to* startups keen(a.) to expand(v.) overseas].

====
- *on top of sth/sb* : in addition to sth 除…之外 +
-> He *gets* commission *on top of* his salary. 他除了薪金之外还拿佣金。
====

中国的创始人特别希望获得外国风投基金的关注，因为这被视为, 能被列入美国上市排队名单的最佳方法. 并且, 外国风投也比他们中国的同行, 能更热衷于支持那些需要更长的时间才能赚钱的创业项目。他们的以美元来计价的基金, 投资持续期能达到10年或更长时间，而以人民币来投资的中国风投, 则希望在5年内就获得回报。(现在, 大多数外国风投公司, 也筹集人民币资金，这使它们能够从中国大陆的股市退出，并在更多行业进行投资。) 除了提供支票之外，外国的风投还会提供专业技能，尤其是针对那些渴望向海外扩张的中国初创企业。

For venture capitalists 资本家;资本主义者, China *used to be* a breeze(`=a thing that is easy to do 轻而易举的事;/微风；和风`), *notes* one (*based* in Shanghai).

“You *were dealing with* the entrepreneurs *directly*, *not with* the state. Partners *could parachute 跳伞；空投 in*, *do* some deals and *leave*.”

====
- parachute => para-,保护，防御，chute,下降，管道，词源同deciduous.即减弱下降力道的工具，引申词义降落伞。 +
-chute部分是词根cad-,cid-,cas-，表to fall down即落下（弱化为前缀时是cata-）。降落伞嘛，是为了抵抗（ward off）降落时的速度的。如法语单词parapluie（雨伞），词根pluv-表示雨水（冲刷）等。下雨天打伞，是为了“ward off the rain”。
====

Zhou Wei, who *worked for* Kleiner Perkins(`=KPCB 凯鹏华盈, 美国风险基金之一`), *says that* {life *was* especially rosy(a.)(`=likely to be good or successful 美好的；乐观的;/粉红色的；红润的`) in the “*copy to* China” years [after the first firms *arrived* around 2005]}.

But it *remained* pretty plush(a.)(`=very comfortable; expensive and of good quality 舒适的；豪华的`) for longer.

In 2018 China *overtook*(`=to go past a moving vehicle or person ahead of you because you are going faster than they are 超过；赶上`) America as the top country for VC returns (*measured by* current return on investment 投资回报率), *according to* eFront, a data firm.

[That year] seven of the world’s ten largest VC deals(n.)(`=an agreement, especially in business, on particular conditions for buying or doing sth 协议；（尤指）交易`) *involved* Chinese startups.

YC *called* China “an important missing(a.)(`=not included, often when it should have been 缺少的；未被包括在内的`) piece of our puzzle” and *dreamed of* `宾` *combining*(v.) “the best of Silicon Valley *and* China”.

====
- plush => 来自法语pluche,棉绒，丝绒，来自古法语peluchier,拔，扯，来自拉丁语pilus,头发，毛发，词源同pile,pluck.引申词义豪华的。
====


一位驻上海的风投人士指出，对于风险投资家来说，在中国盈利, 曾经是小菜一碟。“你直接同企业家打交道，而不是与政府打交道。合伙人可以空降，做完生意后, 就能离开。曾在凯鹏华盈(Kleiner Perkins)工作的 Zhou Wei 表示，在第一批外企风投于2005年前后进入中国的那几年，将美国创业公司的盈利模式“复制到中国”的日子, 尤其美好。即使在此之后, 外资风投依然享受了很长一段时间的舒适时光。数据公司eFront的数据显示，2018年，中国取代了美国, 成为风险投资回报(以当前的投资回报率来衡量)最高的国家。那一年，全球十大风投交易中，有七笔涉及中国初创企业。YC称, 中国是“我们拼图中缺失的重要一块”，并梦想着将“硅谷和中国最好的一面”结合起来。

[For many foreign firms] the glory(`=great beauty 壮丽；辉煌；灿烂`) days *are* over. They *must contend 竞争；争夺 with* homegrown rivals, a few thousand government-funded incubators(`=a machine like a box where eggs are kept warm until the young birds are born 孵化器;/（体弱或早产婴儿）恒温箱`) *doling*(`=*dole sth out (to sb)* : to give out an amount of food, money, etc. to a number of people in a group 发放，发给（食物、钱等）；施舍; /dole : 失业救济金`) *out* cash and free digs(n.)(`=digs : a room or rooms that you rent to live in 租住的住所；住处`) *to* budding(a.)(`=beginning to develop or become successful 开始发展的；崭露头角的;/ 萌芽的`) entrepreneurs, and China’s internet giants, with their voracious(a.)(`=eating or wanting large amounts of food 饭量大的；贪吃的；狼吞虎咽的;/wanting a lot of new information and knowledge （对信息、知识）渴求的；求知欲强的`) appetite 食欲；胃口;强烈欲望 for dealmaking(`=处理交易(deal-making)`).

====
- incubate => in-,进入，使，在上面，-cub,躺，词源同cubicle,succumb.即躺在上面，引申词义孵化，培养。
- digs => 来自dig的俚语义，简陋住所。
- voracious => 来自拉丁语 vorax,贪吃，词源同 devour,herbivore.
====
对于许多外国公司来说，光辉的日子已经过去了。他们必须与中国本土的竞争对手, 还有几千家政府资助的孵化器竞争, 后者向初创企业的创始人, 提供资金和免费办公空间的资助. 中国的互联网巨头, 对生意业务,也有贪婪的胃口。

In an interview with local media, Mr Lu *recalled from* his stint(n.)(`=*~ (as sth)* a period of time that you spend working somewhere or doing a particular activity 从事某项工作（或活动）的时间`) at YC that many Chinese entrepreneurs *put themselves through*(`=*PUT SB THROUGH STH* : to make sb experience sth very difficult or unpleasant 使经受（磨练、痛苦）；折磨`) tough(`=*~ (on/with sb/sth)* : demanding that particular rules be obeyed and showing a lack of sympathy for any problems or suffering that this may cause 严厉的；强硬的；无情的`) interviews *only to turn down*(`=*turn sb/sth down* :to reject or refuse to consider an offer, a proposal, etc. or the person who makes it 拒绝，顶回（提议、建议或提议人）`) foreign funds and *go*, with YC’s imprimatur(n.)(`= official approval of sth, given by a person in a position of authority 正式批准；认可；同意`), *to* deeper-pocketed 财力更雄厚的 Chinese investors.

在接受当地媒体的采访时，陆奇回忆起他在YC工作期间的经历：许多中国的企业家在经历了艰难的面试后，最后却拒绝了外国的风投基金，经过YC同意后，转而选择了财力更雄厚的中国风投投资者。
====
- *PUT STH THROUGH* : *to continue with and complete a plan, programme, etc*. 完成；达成；使成功 +
-> We managed *to put the deal through*. 我们设法做成了这笔生意。

- *PUT SB THROUGH STH* :  +
(1) *to make sb experience sth very difficult or unpleasant* 使经受（磨练、痛苦）；折磨 +
-> You *have put your family through a lot* recently. 最近你使你的家人受苦了。 +
(2) *to arrange or pay for sb to attend a school, college, etc.* 安排某人上（学）；供某人上（学） +
-> He *put all his children through college*. 他把子女都送进了大学。

- *PUT SB/STH THROUGH (TO SB/...)* : *to connect sb by telephone* 给…接通（电话）；把…接到
-> Could you *put me through to the manager*, please? 请帮我找经理接一下电话好吗？

- imprimatur => im-,进入，使，-prim,按，压，词源同 press,print.其原义为使出版，同意出版，后引申词义批准，同意。
====

William Bao Bean, a Shanghai-based partner at SOSV, an American firm, *says* `主` the kind of sums(`=A sum of money is an amount of money. (一) 笔 (钱)`) (that *the likes of*(`=*the likes of sb/sth* : ( informal ) used to refer to sb/sth that is considered as a type, especially one that is considered as good as sb/sth else （尤指被视为和某人或某事物一样好的）种类，类型`) YC *help raise*) `系` *are* “a rounding(`=a round figure or amount is one that is given as a whole number, usually one ending in 0 or 5 整数的；尾数是0（或5）的`) error” 舍零误差，舍入误差，化整误差，修整误差，取整误差 in the world’s most competitive VC market -- even in the midst(n.)(`=the middle part of sth 中部；中间`) of(`=*IN THE MIDST OF STH/OF DOING STH* : while sth is happening or being done; while you are doing sth 当某事发生时；在某人做某事时`) a “capital winter” that *has enveloped*(`=*envelop sb/sth (in sth)* : ( formal ) to wrap sb/sth up or cover them or it completely 包住；裹住；盖住`) China in the past 18 months and *caused* activity(`=a situation in which sth is happening or a lot of things are being done 活动；热闹状况；活跃`) in 2019 *to sink to* its lowest level in four years (see chart).

美国公司SOSV驻上海的合伙人 William Bao Bean 说, 像YC这样的公司能帮助筹集到的一笔资金数额, 对于世界上竞争最激烈的风投市场 -- 中国 -- 来说, 只是一个"零头舍入误差"的程度. 即使是在中国已经经历了18个月的“资本寒冬”, 导致2019年的投资活跃度处于最近四年来的最低潮时期, YC能提供的资金量, 对于中国初创企业来说, 也是微不足道的(见图表).

====
- *the likes of sb/sth* : ( informal ) used to refer to sb/sth that is considered as a type, especially one that is considered as good as sb/sth else （尤指被视为和某人或某事物一样好的）种类，类型 +
-> She didn't want to associate with *the likes of me*. 她不想与我这种类型的人交往。

- round : [ only before noun ] *a round figure or amount is one that is given as a whole number, usually one ending in 0 or 5* 整数的；尾数是0（或5）的 +
-> Make it *a round figure* -- say forty dollars. 凑个整数—就四十块钱吧。 +
-> Well, *in round figures* (= not giving the exact figures) we've spent twenty thousand so far. 嗯，说个约数吧，我们至今花了有两万了。

- envelop : v. *~ sb/sth (in sth)* : ( formal ) to wrap sb/sth up or cover them or it completely 包住；裹住；盖住 +
=> en-, 进入，使。-velop, 围，绕，词源同develop,wind. +
-> She *was enveloped in* a huge white towel. 她裹在一条白色大毛巾里。 +
-> Clouds *enveloped the mountain tops*. 云雾笼罩着山顶。
====

`主` *Poaching*(`=poach : *~ (sb/sth) (from sb/sth)* : to take and use sb/sth that belongs to sb/sth else, especially in a secret, dishonest or unfair way 盗用；挖走（人员等）;/（在他人地界）偷猎，偷捕`) savvy(a.)(`=having practical knowledge and understanding of sth; having common sense 有见识的；懂实际知识的；通情达理的`) Chinese partners `谓` *has become* harder, *says* Kuantai Yeh of Qiming Venture Partners, a big Chinese VC firm.

====
- poach => 词源不确定，可能来自法语pocher,装入口袋，词源同poach.或来自古法语pochier,刺，捅， 词源同poke.引申词义越界，偷猎，偷捕。
- savvy => 加勒比混杂英语，借自法语 savez-vous,是否知道，来自 savez,知道，词源同 savant,vous,你， 词源同 rendezvous.电影《加勒比海盗》中杰克船长口头禅。
====

The flow of talent *may have reversed* 颠倒；彻底转变；使完全相反. In 2017 Mr Zhou and others *left* the ailing(a.)(`=(of a business, government, etc. 企业、政府等) having problems and getting weaker 处境困难的；每况愈下的;/有病的；体弱的`) Chinese arm of Kleiner Perkins(`=KPCB 美国的风投基金`) *to form*(`=to start a group of people, such as an organization, a committee, etc.; to come together in a group of this kind 组织；建立`) China Creation Ventures(`=CCV 创世伙伴资本`).

====
- ailing => ail, 古英语eglan（使烦恼） 同源词：ailing（生病），ailment（小病）. 词源同awe, 敬畏，ugly, 丑陋。由恐惧衍生出敬畏，丑陋，忧患，病痛等。  +
趣味记忆：ail→谐音“哎呦”→病痛时的呻吟声→病痛、苦恼
====
中国大型风投公司启明创投(Qiming Venture partners)的叶冠泰(Kuantai Yeh)表示，外资想要挖走有见识的中国合作伙伴, 变得更加困难。人才的流动可能已经逆转。2017年，周炜等人离开了境况不佳的凯鹏华盈(Kleiner Perkins)中国分公司，成立了创世伙伴资本(China Creation Ventures)。

[The previous year] the team at New Enterprise Associates(`=同事；伙伴;合伙人`) 美国的恩颐投资 *peeled off*(`=*peel off* : to leave a group of vehicles, aircraft, etc. and turn to one side （车辆、飞机等）离队，转向一侧; /剥掉；揭掉；剥落  /*peel* :剥（水果、蔬菜等的）皮；去皮`) *to build* Long Hill Capital 长岭资本. (New Enterprise now *invests in* Chinese startups from Silicon Valley.)

====
- Long Hill Capital : 长岭资本的创始合伙人, 来自于恩颐投资(NEA) 的中国团队.
====

And Chinese startups *increasingly cater to*(`=*CATER TO SB/STH* : to provide the things that a particular type or person wants, especially things that you do not approve of 满足需要；迎合; /*cater (for sb/sth)* : to provide food and drinks for a social event （为社交活动）提供饮食，承办酒席`) idiosyncratic(a.)(`=If you describe someone's actions or characteristics as idiosyncratic, you mean that they are somewhat unusual. 怪异的; 另类的`) local tastes -- good luck *explaining* the value of a “mobile karaoke social network” *to* the head office 总公司,总部 in California, *says* Mr Zhou.

*No wonder* `主` 19 of China’s 30 best-performing VC and private-equity 私募股权；私人股本 firms in 2018 `系` *were* local, *according to* Forbes, a magazine.

前一年，美国风投 New Enterprise Associates 中的中国团队, 离开母公司, 并新创建了Long Hill Capital。(New Enterprise现在在硅谷投资中国初创企业。)周先生说，中国的初创公司, 也越来越多地开始迎合当地独特的品味——祝你好运，向加州总部解释“移动卡拉ok社交网络”的价值。《福布斯》杂志称，难怪2018年中国表现最好的30家风投和私募股权公司中, 有19家是本土公司。

The recent funding downturn （商业经济的）衰退，下降，衰退期 *has* a flipside 另一面；反面.

[By *squeezing*(`=squeeze : *~ (sb/sth) into, through, etc. sth /~ through, in, past, etc.* : to force sb/sth/yourself into or through a small space （使）挤入；挤过；塞入`) smaller domestic rivals] `主` it *may give* an edge(`=*~ (on/over sb/sth)* : a slight advantage over sb/sth （微弱的）优势`) *to* giant cash-rich funds, *including* foreign ones.

It is unclear they *will seize* the opportunity.

China *has become* “kryptonite”  氪（仅存在于超人等故事中的化学元素，超人若接近此元素即丧失超常能力） in Silicon Valley, *says* Mr Bean.

Silicon Dragon, a VC news(n.) tracker *based* in the valley, *predicts that* this year VC *will flow into* separate(a.)单独的；独立的；分开的 Chinese and American pots 锅;（盛食品的）罐，瓶，壶.

====
- kryptonite => 可能来自Krypton和meteorite的合成词。Krypton为漫画中超人所在的外星家园，可能因其充满气体氪, 或因其隐藏难发现, 而得名，meteorite,陨石。
- Silicon Dragon : 是一家专注于新兴市场以及科技报道的媒体平台。并定期在硅谷，伦敦，北京，上海，悉尼，香港，新加坡和班加罗尔举办论坛。
====

`主` Startups *backed by* cross-border 跨越国境的 investors `谓` *are bracing for*(`=*brace sb/yourself (for sth)* : to prepare sb/yourself for sth difficult or unpleasant that is going to happen （为困难或坏事）使作准备；使防备`) a cash crunch(n.)(`=a situation in which there is suddenly not enough of sth, especially money （突发的）不足，短缺；（尤指）缺钱;/压碎声；碎裂声`).

One veteran 经验丰富的人；老手;退伍军人；老兵 venture capitalist at a firm with foreign roots *says that* American investors *are asking* their VC firms’ investment committees: “*Do* we *need* to invest in China?” For some, the answer *will increasingly be* “no”.

最近的融资低迷也有另一面。通过挤压规模较小的国内竞争对手，它可能会给现金充裕的巨型基金带来优势，包括外国基金。目前还不清楚他们是否会抓住这个机会。宾先生说，中国已经成为硅谷的“氪星”。硅谷的专门关注于风投新闻的 Silicon Dragon公司预测，今年风投将分别流入中国和美国。由跨境投资者支持的初创企业, 要面对迎接现金短缺的情况。一家有外国根基的公司的一位资深风险投资家说，美国投资者正在问他们的风险投资公司的投资委员会：“我们需要在中国投资吗？”对一些人来说，答案将越来越多地是“不”。


---

== 12. Life is getting harder for foreign VCs in China 纯净版

They *must contend with* mature homegrown rivals and skittish American investors

Jan 11th 2020 | SHANGHAI

THE FIRST “demo day” in Beijing last November of Y Combinator (YC) *hosted* two dozen local startups *vying for* the attention of high-profile investors. It *marked* the entrance into China of Silicon Valley’s most famous accelerator, which *has helped launch* the likes of Airbnb and Dropbox. Then, days later, YC *abruptly announced* it *was pulling out of* the country.

[In a statement] YC *said that* it *was returning*, under a new boss, *to investing in* startups from its Californian base. Its Chinese startups *will be nurtured by* MiraclePlus, YC China’s new, fully localised incarnation. Yet in the context of a deepening Sino-American rift(n.), the retreat *looks* ominous. “Under the current global environment, *to realise* *our mission -- By China, For China, Of China -- we *must have* the ability *to master* our own destiny,” *wrote* MiraclePlus in a social-media post, *citing* Lu Qi, its boss, whom (YC *had hired `宾` to set up* its Chinese arm in 2018). (Mr Lu *declined* to be interviewed(v.) for this article.)

At first glance, YC’s fate *seems* at odds with the broader health of foreign venture capital (VC) in China, with its red-hot tech industry. `主` The Chinese operations of Sand Hill Road heavyweights(n.) such as Lightspeed Venture Partners and Sequoia Capital -- whose fifth Chinese growth-stage fund *raised* $1.8bn, *twice as much as* its last -- `谓` *are thriving*. Chinese founders *have coveted* attention from foreign funds, *seen as* the best route *to listing [on* American exchanges] and *keener*(a.) [than Chinese counterparts] *to back* ideas that take longer to make money. Their dollar-denominated funds *have* durations of ten years or more, whereas yuan investors *usually want* a return [in five]. (Most foreign VCs *now also raise* yuan funds, which *enable* exits on mainland stockmarkets and *investments in* more industries.) Foreigners *offer* expertise [*on* top of cheques], especially *to* startups (*keen(a.) to expand* overseas).

For venture capitalists, China *used to be* a breeze, *notes* one (based in Shanghai). “You *were dealing with* the entrepreneurs *directly*, *not with* the state. Partners *could parachute in*, *do* some deals /and *leave*.” Zhou Wei, who *worked for* Kleiner Perkins, *says that* {life *was especially rosy* in the “*copy to* China” years after the first firms *arrived* around 2005}. But it *remained* pretty plush for longer. [In 2018] China *overtook* America *as* the top country for VC returns (*measured by* current return on investment), *according to* eFront, a data firm. [That year] seven of the world’s ten largest VC deals *involved* Chinese startups. YC *called* China “an important missing piece of our puzzle” and *dreamed of* `宾` *combining* “the best of Silicon Valley *and* China”.


[For many foreign firms] the glory days *are* over. They *must contend with* homegrown rivals, a few thousand government-funded incubators *doling out* cash and free digs *to* budding entrepreneurs, and China’s internet giants, with their voracious appetite for dealmaking. In an interview with local media, Mr Lu *recalled from* his stint at YC *that* many Chinese entrepreneurs *put themselves through* tough interviews *only to turn down* foreign funds /and *go*, with YC’s imprimatur, *to* deeper-pocketed Chinese investors. William Bao Bean, a Shanghai-based partner at SOSV, an American firm, *says* `主` the kind of sums that the likes of YC *help raise* `系` *are* “a rounding error” [in the world’s most competitive VC market] -- even in the midst of a “capital winter” that *has enveloped* China in the past 18 months and *caused* activity in 2019 *to sink to* its lowest level in four years (see chart).

`主` *Poaching* savvy Chinese partners `谓` *has become* harder, *says* Kuantai Yeh of Qiming Venture Partners, a big Chinese VC firm. The flow of talent *may have reversed*. [In 2017] Mr Zhou and others *left* the ailing Chinese arm of Kleiner Perkins *to form* China Creation Ventures. [The previous year] the team at New Enterprise Associates *peeled off* *to build* Long Hill Capital. (New Enterprise *now invests in* Chinese startups from Silicon Valley.) And Chinese startups *increasingly cater to* idiosyncratic local tastes -- good luck *explaining* the value of a “mobile karaoke social network” *to* the head office in California, *says* Mr Zhou. *No wonder* `主` 19 of China’s 30 best-performing VC and private-equity firms in 2018 `系` *were* local, *according to* Forbes, a magazine.

The recent funding downturn *has* a flipside. [By *squeezing* smaller domestic rivals] it *may give an edge to* giant cash-rich funds, *including* foreign ones. *It is unclear* they *will seize* the opportunity. China *has become* “kryptonite” in Silicon Valley, *says* Mr Bean. `主` Silicon Dragon, a VC news tracker *based* in the valley, `谓` *predicts that* this year VC *will flow into* separate Chinese and American pots. `主` Startups *backed by* cross-border investors `谓` *are bracing for* a cash crunch. One veteran venture capitalist (at a firm with foreign roots) *says that* American investors *are asking* their VC firms’ investment committees: “*Do we need to invest in* China?” For some, the answer *will increasingly be* “no”.


---




