
= eco 2020.08
:toc:

---

== 08. The new red scare on American campuses

The new red scare(`=a situation in which a lot of people are anxious or frightened about sth 恐慌；恐惧`) on American campuses

Both their host 东道主；主办国（或城市、机构） government and their home government *increasingly view* Chinese students [*with suspicion*]

美国校园里新的红色恐慌 +
他们的东道国政府和本国政府, 都越来越怀疑中国学生

Jan 2nd 2020 | NEW YORK

[EARLY LAST autumn] Alex and Victor, two students from mainland China, *sat* in the back row of a packed auditorium 礼堂；会堂 at Columbia Law School, in New York.

They were there for a talk by Joshua Wong 黃之鋒, thrice(`=three times 三次；三倍`)-jailed young hero of the Hong Kong democracy movement, which the two students *support*.

They *applauded enthusiastically*  热心地；满腔热情地; they also *wore* blue face masks.

去年初秋，在纽约哥伦比亚大学法学院的座无虚席的礼堂中, 两名来自中国大陆的学生, 亚历克斯和维克多, 坐在后排。他们是来听Joshua Wong的讲座的, Joshua Wong是因香港民主运动而三次入狱的年轻的英雄。讲座上, 他们热情地鼓掌, 并且他们也戴着蓝色的口罩。

The masks *were* in part symbols of solidarity(n.)(`=*~ (with sb)* : support by one person or group of people for another because they share feelings, opinions, aims, etc. 团结；齐心协力；同心同德；相互支持`) with Mr Wong’s fellow protesters (half a world away).

But they *were* also a way of *hiding* their identities *from* face-recognition systems in China that *might be scanning* pictures of the audience, and *from* Chinese students in the hall (less in tune with(`=*be in/out of tune (with sb/sth)* : to be/not be in agreement with sb/sth; to have/not have the same opinions, feelings, interests, etc. as sb/sth （与…）协调╱不协调，一致╱不一致，融洽╱不融洽`) Mr Wong’s message) -- such as the ones who *sang* the national anthem 国歌；（组织或群体的）社歌，团歌 of the People’s Republic *in response to* the talk.

====
- anthem => 来自希腊词antiphona传入古英语的变体。前缀anti-, 相对。词根phone 即“sound”, 声音，歌。指对歌，神圣的音乐。后在英语里特指国歌。
====

Their names *are not*, in fact, Alex and Victor; they *asked* The Economist *to give them pseudonyms* 假名；化名；笔名 and *not to say* where in China they *came from*.

As they *talked*, other Chinese students *quietly observed* them, national flags in hand.

====
- pseudonym => pseudo-,假的，伪的，-onym,名字，词源同name,anonymous.
====

这些面罩, 在一定程度是源于为了与黃之鋒在地球另一边的同伴(抗议中国大陆者), 相呼应. 但同时也是为了不被摄影机拍下来, 而被中国的面部识别系统所认出身份. 同时, 也是为了防止被大堂里的反对黃之鋒的其他中国学生认出来. 这些中国学生以唱国歌, 来回应黃之鋒的发言.

这两个学生的真名, 当然不叫 Alex 和 Victor, 他们要求《经济学人》为他们匿名, 并且不要暴露他们来自中国的哪里. 当他们交谈时，其他手里拿着国旗的中国学生, 静静地观察着他们.

There are 19.8m university students in America, of whom just over a million *come from* other countries. `主` A bit less than a fifth of these foreigners `谓` *come [from* India], and 6% [*from* the European Union]. Fully a third *are* Chinese -- a much larger fraction(`=a small part or amount of sth 小部分；少量；一点儿;/分数；小数`) than [from anywhere else], and *more* students *than* China *sends to* all the other countries in the world put together.

At Columbia, half of the nearly 12,000 international students *are* from China. This is all very good for the students’ future prospects /and the universities’ coffers （政府、机构等的）金库，资金. But it *worries* the American government, the Chinese Communist Party (CCP) and some champions(`=a person who fights for, or speaks in support of, a group of people or a belief 斗争者；捍卫者；声援者；拥护者`) of academic freedom.

美国有1980万大学生，其中100多万来自其他国家。这些外国人中不到五分之一来自印度，6%来自欧盟。整整三分之一是中国人 -- 这一比例比其他任何地方都大得多，而且比中国派往世界上所有其他国家的学生总和还要多。在哥伦比亚大学，近12000名国际学生中有一半来自中国。这对学生的前途和大学的金库, 都是非常有利的。但这让美国政府、中国共产党, 和一些学术自由的捍卫者, 感到担忧。

The American government *thinks* some Chinese students and researchers *are responsible for* a great deal of intellectual-property theft.

The CCP *fears that* people like Alex and Victor *are contracting* dangerous levels of democratic idealism(`=the belief that a perfect life, situation, etc. can be achieved, even when this is not very likely 理想主义`).

And `主` China’s efforts *to curtail*(`=to limit sth or make it last for a shorter time 限制；缩短；减缩`) the room (such dissidence(n.) 异议;意见不同 *has to flourish*(`=to develop quickly and be successful or common 繁荣；昌盛；兴旺`) *in* (这个in, 呼应上面的room, flourish in the room)) `谓` *worries* people (who *care about* free expression on American campuses and beyond(`=on the other side; further on 在另一边；在（或向）更远处；以远`)).

====
- curtail => 来自PIE sker, 剪，切，词源同shear, short. -ault, 贬义后缀，词源同valiant, 勇敢的，顽固的。比较-ard, 贬义后缀，来自hard, 见bastard. 原指剪短尾巴的马，拼写受tail影响俗化。 +
-> Spending on books *has been severely curtailed*. 购书开支已被大大削减。 +
-> The lecture *was curtailed* by the fire alarm going off. 那次讲座被突然鸣响的火警中断了。
====

美国政府认为, 某些中国学生和研究人员, 要对大量的知识产权盗窃案负责。中共则担心像亚历克斯和维克多这样的人, 正在陷入危险的民主理想主义思想中。中国在努力限制会导致这些异议思想蓬勃发展的空间, 这让那些关心着美国校园内外言论自由的人, 感到担忧。

A special relationship

一种特殊的关系

The number of mainland Chinese students in America *grew by 276%* over the past decade (see chart 1) *as* China’s elite *sought to buy* excellent educations *for* their children /and American researchers *sought* talent. In 2018, the most recent year (for which figures *are available*), Chinese graduate students *received* 13% of all science and engineering doctorates(`=doctorate : the highest university degree 博士学位`) *awarded by* American universities.

在过去的十年中，在美国的中国大陆学生数量, 增长了276%(见表1)，因为中国的精英阶层, 寻求为他们的孩子购买优秀的教育，而美国的研究人员, 也寻求人才。2018年是有数据可查的最近的一年，来自中国的毕业生, 获得了美国大学授予的科学和工程博士学位中的13%。

`主` The rate at which researchers at the Massachusetts Institute of Technology (MIT) co-author （书或文章的）合著者 papers with colleagues at leading Chinese universities `谓` *has risen* tenfold [over the past decade] -- part of a trend (which *has seen* `主` collaborations 合作；协作 between American and Chinese researchers `谓` *become more* numerous *than* collaborations with any other country (see chart 2)).

Many Chinese researchers *have* significant(`=large or important enough to have an effect or to be noticed 有重大意义的；显著的`) resources *as well as* sharp minds; `主` some sorts of lab work(n.) `系` *are easier and cheaper* in China than in America. *It* is hardly surprising *that* `主` American researchers -- especially the growing number who *have* former pupils back in China -- `谓` *want to work with them*.

在过去的十年里，麻省理工学院(MIT)的研究人员与中国顶尖大学的同事合著论文的比率, 上升了十倍 -- 这是当前趋势的一部分，即美国和中国研究人员之间的合作, 比与任何其他国家的合作, 都要多(见表2)。许多中国的研究人员, 拥有丰富的资源和敏锐的头脑；某些实验室的工作, 在中国做要比在美国做更方便，成本也更低。越来越多的美国研究人员 -- 尤其是那些他们以前的中国学生, 最终回国的 -- 想要与中国人合作, 这种现象也就不足为奇了。


Not all of this collaboration *is* peer-to-peer(`=(of a computer system 计算机系统) in which each computer can act as a server for the others, *allowing* data *to be shared* without the need for a central server 对等的，点对点的（系统中的任何一台计算机均可用作服务器，允许文件共享）`).

Chinese companies *fund*(v.)为…提供资金；拨款给 an increasing amount of research [at American universities], including *into* areas (*prioritised*(`=prioritize :  to treat sth as being more important than other things 优先处理`) in the “Made in China 2025” industrial-policy initiative 倡议；新方案 -- a policy America’s Department of Justice *has referred to as* a “roadmap to [intellectual-property] theft”).

MIT, for example, *has* research partnerships with SenseTime, a Hong Kong company that *provides* facial(`=connected with a person's face; on a person's face 面部的`)-recognition technology *to* Chinese police, and iFlytek, a Chinese firm that *works on* voice recognition and which *has paid for* research at Princeton and Rutgers.

并不是所有的合作都是对等的。中国公司在美国大学里资助了越来越多的研究，包括在“中国制造2025”工业政策中优先考虑的领域。美国司法部称这一政策为“知识产权盗窃的路线图”。中国公司资助的美国大学研究项目, 例如有，麻省理工学院与SenseTime(一家为中国警察提供面部识别技术的香港公司)和科大讯飞(一家从事语音识别的中国公司)有研究伙伴关系。科大讯飞为普林斯顿大学和罗格斯大学的研究提供了资金。

The administration of President Donald Trump *worries about* all this.

In the past two years, `主` scrutiny(n.)(`=careful and thorough examination 仔细检查；认真彻底的审查`) of mainland Chinese on American campuses `谓` *has intensified*(`=intensify : to increase in degree or strength; to make sth increase in degree or strength （使）加强，增强，加剧`), and with it scrutiny(n.) of other students and researchers (who are ethnically 人种上；民族上 Chinese, including Chinese-Americans 美籍华人).

Some *see* this new scrutiny *as* testing(v.) American academia’s reputation for openness, international co-operation and the free exchange of ideas.

Christopher Wray, the director of the FBI, *believes* it *provides* a valuable counterweight(n.)(`=*~ (to sth)* : a thing that has an equal but opposite effect to sth else and can be used to limit the bad effects of sth 平衡抵消物；平衡重（或块、锤）; 平衡的行为（或提议）；平衡物`) to academic “naivety 无邪的行为；天真烂漫”.

唐纳德·特朗普(Donald Trump)总统的政府对这一切感到担忧。在过去的两年里，美国加强了对美国校园中的来自中国大陆资金的审查，并伴随着对包括华裔美国人在内的其他华人学生和研究人员的审查。一些人认为, 这种新的审查是在考验美国学术界在开放、国际合作和思想自由交流方面的声誉。但联邦调查局局长克里斯托弗·雷(Christopher Wray)认为，这提供了一种有价值的力量, 能平衡学术界的“天真想法”(即只考虑科学, 不考虑政治)。

[In 2018] Mr Wray *testified*(`=testify: *~ (against/for sb)~ (to/about sth)* : to make a statement that sth happened or that sth is true, especially as a witness in court （尤指出庭）作证`) *to* the Senate intelligence committee 参议院情报委员会 *that* {China *poses*(`=to create a threat, problem, etc. that has to be dealt with 造成（威胁、问题等）；引起；产生`) a “whole-of-society threat” *to* America, one which *demands* a “whole-of-society response”}.

[In Mr Wray’s analysis] `主` the fact that American researchers *collaborate so much with* Chinese researchers `系` *is* a cause(n.)(`=*~ (for sth)* : a reason for having particular feelings or behaving in a particular way 理由；动机；缘故`) for concern; such scientists and students *are* among the “non-traditional collectors” of an intelligence operation (he *has described as* “deep and diverse(a.)(`=very different from each other and of various kinds 不同的；相异的；多种多样的；形形色色的`) and wide and vexing(`=vex : to annoy or worry sb 使恼火；使烦恼；使忧虑`)”).

====
- *cause : ~ (for sth)* a reason for having particular feelings or behaving in a particular way 理由；动机；缘故 +
-> *There is no cause for concern* . 没有理由担忧。 +
-> The food was excellent -- *I had no cause for complaint* . 饭菜好极了，我没理由抱怨。
====
2018年，雷向参议院情报委员会(Senate intelligence committee)作证时表示，中国对美国构成了“全社会性的威胁”，因此需要“全社会性地回应”。在雷先生的分析中，美国研究人员与中国研究人员的合作是如此之多, 导致有理由令人担心; 这些中国科学家和学生, 被他描述为是在"深入地, 多种多样地, 广泛地, 令人恼火与担忧地"进行情报收集活动的 "非传统的"情报收集者.

[In 2018 and 2019] agents from the FBI’s 56 national field offices *contacted*(v.)联系，联络（如用电话或信件） hundreds, perhaps thousands, of students, researchers and professors (*with ties to* China) -- many of them from China or ethnically Chinese, *including* Chinese-Americans -- *to determine* whether they *might be working on behalf of* the Communist Party.

`主` The National Institutes of Health (NIH) 美国国立卫生研究院, Department of Energy /and other providers of federal grants （政府、机构的）拨款 `谓` *have urged* universities *to monitor*(`=to watch and check sth over a period of time in order to see how it develops, so that you can make any necessary changes 监视；检查；跟踪调查`) researchers for connections to Chinese institutions or “talent” 人才；天才 programmes which *seek* to attract(v.) scientists, often Americans of Chinese ethnicity, who *have gained* expertise 专门知识；专门技能；专长 (*deemed*(`=to have a particular opinion about sth 认为；视为；相信`) of value in China).

`主` China’s “Thousand Talents” programme, which in part *offers* scientists incentives(n.)(`=something that encourages you to do sth 激励；刺激；鼓励`) *to set up* labs in China, `谓` *was used to recruit*(`=被动态, 被用于`) at least 6,000 experts *from* overseas between 2008 to 2017.

在2018年和2019年，美国联邦调查局中的负责国家事务的56个工作人员, 联系了数百名，也许是数千名与中国有联系的学生、研究人员和教授，其中许多人来自中国或华裔，包括华裔美国人，以确定他们是否代表着共产党的利益来工作。美国国家卫生研究院(NIH)、能源部, 和其他能提供联邦资助金的机构, 敦促各大学, 对那些与中国机构或“人才”项目有联系的研究者, 进行监视. 中国的这些机构或项目, 旨在吸引那些掌握着被中国视为极有价值的技术知识的科学家(通常是华裔美国人)。中国的“千人计划”, 在2008年至2017年期间，从海外招募了至少6000名专家。该计划在一定程度上鼓励科学家们, 在中国境内设立实验室。

The NIH 美国国立卫生研究院 *says that* {it *has identified* 180 researchers (*to* whom it *has provided* grants （政府、机构的）拨款) who *may not have disclosed*(`=*~ sth (to sb)* : to give sb information about sth, especially sth that was previously secret 揭露；透露；泄露`) payments from, or other affiliations （与政党、宗教等的）隶属关系 with, Chinese institutions -- *including* some who *appear to have established* “shadow labs” in China *mirroring* their NIH-funded ones in America}.
====
- 这里最后的 mirroring, 显然是个分词, 作状语. +
 但你也可以将它看成是 adj. 用来修饰 前面的who. 这样理解起来更简单一点. 这样就是 who后面有两个定语, 一个是 appear to have done... 他在中国造了机器; 另一个定语是 mirroring... 他镜像了美国的机器.
====
美国国立卫生研究院表示，他们已经确定了有180名研究人员，这些研究人员曾获得过国家卫生研究院的资助，但他们可能没有披露他们也接受了来自中国机构的资助，他们也没有披露他们与中国的其他机构有隶属关系，其中包括一些似乎在中国有建立了“影子实验室”的研究人员，而这些影子实验室, 与美国国家卫生研究院资助的实验室如出一辙。

[In 2019] two research institutions -- MD Anderson, a cancer-research centre in Houston, and Emory University in Atlanta -- *cut ties with* five researchers, all of them ethnically Chinese, who *had taken money from China*.

[In December] federal authorities *arrested* a Chinese cancer researcher at Logan Airport in Boston after he allegedly 据称,据说 *tried to smuggle 走私；偷运 to China* vials (装香水、药物等的)小瓶 of biological material *taken from* a Harvard teaching hospital(`=A *teaching hospital* is a hospital that is linked with a medical school, where medical students and newly qualified doctors receive practical training. 教学医院`). (His Harvard-sponsored visa *has also been revoked*.)(`=to officially cancel sth so that it is no longer valid 取消；废除；使无效`)

2019年，两家研究机构 -- 休斯顿的癌症研究中心MD Anderson和亚特兰大的埃默里大学 -- 切断了与五名研究人员的联系，这些研究人员都是华裔，他们都接受了来自中国的资金。去年12月，联邦当局在波士顿洛根机场, 逮捕了一名中国癌症研究人员，据称他试图将从哈佛教学医院拿走的装有生物材料的小瓶子, 偷带进中国。(他的哈佛赞助签证也被吊销了。)。

But officials at some universities *say that* private briefings(`=a meeting in which people are given instructions or information 传达指示会；情况介绍会; /the detailed instructions or information that are given at such a meeting 详细指示；详情介绍`) from the FBI *have left* them *both* unconvinced(a.)(`=*~ (of sth) /~ (by sth) /~ (that...)* :  not believing or not certain about sth despite what you have been told 不信服的；未被说服的`) of the scope （题目、组织、活动等的）范围 of the problem *and* unclear(a.) what actions *need to be pursued*(`=to do sth or try to achieve sth over a period of time 追求；致力于；执行；贯彻`).

“What exactly Mr Wray *has* [in mind], where precisely he *sees* the threat -- this *is* all left frustratingly 令人泄气地；使人沮丧地 vague(a.)(`=not having or giving enough information or details about sth 不具体的；不详细的；粗略的`),” *says* an international-research administrator at an elite university (that *has been briefed*(v.)(`=brief : to give sb information about sth so that they are prepared to deal with it 给（某人）指示；向（某人）介绍情况`) by the FBI (and where the FBI *has also interviewed* visiting(a.) Chinese scholars)).

“Some of the guidance(n.)(`=*~ (on sth)* : help or advice that is given to sb, especially by sb older or with more experience 指导；引导；咨询`) *has been*, ‘*Be careful about* anything (*to do with* biotech  生物技术；生物科技).’ Well biotech *is* huge(`=extremely large in size or amount; great in degree 巨大的；极多的；程度高的`) … I *don’t even know* which faculty （高等院校中院、系的）全体教师 *to talk to* if you *don’t tell me more*.”

但一些大学的官员表示，联邦调查局的私人简报, 让他们既不相信问题的范围，也不清楚需要采取什么行动。“雷先生到底在想什么，他到底在哪里看到了威胁 -- 所有这些都是令人沮丧的模糊，” 一所精英大学的国际研究管理人员说，这所大学已经听取了联邦调查局的简报(联邦调查局也在那里采访了来访的中国学者)。“一些指导意见是，‘小心任何对生物技术下手的事情’。"嗯，生物技术的范围相当巨大…。如果你不告诉我更多信息，我甚至不知道该找哪位教员谈谈。"

Risk management

风险管理

*Faced with* such scepticism(`=an attitude of doubting that claims or statements are true or that sth will happen 怀疑态度；怀疑主义`), last summer `主` the National Security Council, the State Department, the Department of Justice (though not the FBI) and experts on Chinese influence operations `谓` *briefed*(`=brief : *~ sb (on/about sth)* : to give sb information about sth so that they are prepared to deal with it 给（某人）指示；向（某人）介绍情况`) some 15 university presidents, provosts(`=a senior member of the staff who organize the affairs of some universities （美国某些大学的）教务长`) and other senior administrators [in a two-day session(`=a period of time that is spent doing a particular activity 一场；一节；一段时间;/（法庭的）开庭，开庭期；（议会等的）会议，会期`) at St Michaels, Maryland].

One of those *giving* the briefings *noted that* `主` the idea of technology (*developed* on their campuses) (*aiding*(`=aid : *~ (sb/sth) (in sth/in doing sth) /~ sb (with sth)* :  ( formal ) to help sb/sth to do sth, especially by making it easier 帮助；援助`) China’s repression(`=the act of using force to control a group of people and restrict their freedom 压制；镇压`) of Uighurs 维吾尔人 in the western province of Xinjiang) `谓` *seemed* particularly salient(a.)(`=most important or noticeable 最重要的；显著的；突出的`) to the administrators （公司、机构的）管理人员，行政人员: `主` such links `谓` *could damage* their institutions’ reputations.

====
- salient  => 它的词根sal-表“跳跃”，所以它还有“跳跃的”之义；跳跃将身子抬高，可以更惹人注目，所以引申为“突出的”；同根词如assault（突袭）、sally（突围）、assail（猛烈攻击）等。它和excellent（杰出的）整体音似，可联想串记。 +
-> She pointed out *the salient features* of the new design. 她指出新设计的几个显著特征。 +
-> He summarized *the salient points* . 他对要点作了归纳。
====

This *is not* a purely theoretical(`=concerned with the ideas and principles on which a particular subject is based, rather than with *practice* and *experiment* 理论上的`) issue.

[In October] SenseTime and iFlytek, `主` the artificial-intelligence firms *with research partnerships* at MIT, `谓` *were blacklisted* by the American government *for* allegedly 据说，据称 *abetting*(`=abet : to help or encourage sb to do sth wrong 教唆；唆使；煽动；怂恿`) the abuses in Xinjiang.


面对这样的质疑，去年夏天，国家安全委员会、国务院、司法部(尽管不是联邦调查局), 和研究中国影响力运作的专家, 在马里兰州圣迈克尔, 举行了为期两天的会议，向大约15位大学校长、教务长, 和其他高级管理人员, 做了汇报。一位通报情况的人士指出，在他们的校园里开发的技术，对中国在西部省份新疆镇压维吾尔人的行动, 起到了帮助作用，这种想法对管理人员来说, 似乎特别突出: 这种联系可能损害他们所在机构的声誉。这不是一个纯粹的理论问题。10月，SenseTime和科大讯飞(iFlytek)，这两家与麻省理工学院有研究合作关系的人工智能公司，被美国政府列入了黑名单，原因是它们涉嫌助纣为虐新疆的虐囚行为。


As well as(`=in addition to sb/sth; too 除…之外；也；还`) *investigating*(v.) Chinese students and researchers already in America, the administration *has also looked at* ways *to make it harder for them to arrive* and *easier for them to be expelled*(`=to officially make sb leave a school or an organization 把…开除（或除名）; /to force sb to leave a country 驱逐出境`).

In 2018 some of Mr Trump’s aides （尤指从政者的）助手 *argued for*(`=*argue (for/against sth) /argue (for/against doing sth)* :  to give reasons why you think that sth is right/wrong, true/not true, etc., especially to persuade people that you are right 论证；说理；争辩`) severe restrictions on student visas for Chinese nationals （某国的）公民.

[Instead 而不是 the administration *curtailed*(`=to limit sth or make it last for a shorter time 限制；缩短；减缩`) five-year visas *for* foreign graduate students *in* certain fields of science and technology *such as* aviation and robotics]; `主` these students `谓` now *get* renewable 可延长有效期的；可展期的；可续订的 one-year visas.


The Department of Homeland Security *has also made it easier* 真主 *to declare*(`=to say sth officially or publicly 公布；宣布；宣告`) *that* foreign students *are overstaying*(`=to stay longer than the length of time you are expected or allowed to stay 停留过久,逾期滞留`) their visas.

Educators *report anecdotally*(`=based on anecdotes and possibly not true or accurate 逸事的；趣闻的；传闻的`) *that* {`主` invited(a.) Chinese scholars `谓` *are finding* it much harder *to get visas*, including short-term visas for academic conferences that in the past *were routinely 照例地  issued*}.

除了调查已经在美国的中国学生和研究人员外，奥巴马政府还考虑了一些办法, 让他们更难抵达美国、并更容易被驱逐。2018年，特朗普的一些助手, 主张对中国公民的学生签证进行严格限制。政府并未削减某些科技领域(如航空和机器人)的外国研究生的五年签证；而是给这些学生发放可续签的一年期签证。国土安全部也把"宣布外国学生签证过期"这件事, 变得更容易。教育工作者说，受邀的中国学者发现获得签证变得更加困难，包括过去定期发放的学术会议的短期签证。

`主` Concerns(n.) about what Chinese students *get up to*(`=*GET UP TO STH* : to be busy with sth, especially sth surprising or unpleasant 忙于，从事（尤指令人吃惊或不快的事）;/to reach a particular point 到达某一点`) `系` *are not unique to* the executive branch.

Marco Rubio, a Republican senator from Florida, and Mark Warner, a Democratic senator from Virginia, *have been* among the most prominent(`=important or well known 重要的；著名的；杰出的`) figures on Capitol Hill *warning* not just *of* Chinese intelligence operations at American universities, but also *of* those universities’ worrying dependence(n.)(`*=~ (on/upon sb/sth)* : the state of needing the help and support of sb/sth in order to survive or be successful （生存或成功必需的）依靠，依赖，依存`) on Chinese money *via* tuition （尤指大专院校的）学费 fees and research partnerships.

Pressure from senators and congressmen (尤指众议院的) 美国国会男议员 *is* one of the reasons why, since 2018, at least 15 universities *have closed* the Confucius Institutes, *paid for* by China, that *offer* Chinese language instruction and *arrange* cultural events.

`主` A new federal restriction (that *bars* universities (with Confucius Institutes) *from* Defence Department funding(n.)(`=money for a particular purpose; the act of providing money for such a purpose 基金；资金；提供基金；提供资金`) (for Chinese-language study)) `系` *has also been* a factor.

对中国的学生会做了些什么的担忧, 并不是行政部门所独有的。佛罗里达州共和党参议员马尔科·卢比奥(Marco Rubio)和弗吉尼亚州民主党参议员马克·华纳(Mark Warner), 是国会山最知名的人物之一，他们不仅警告中国在美国大学的情报活动，还警告这些大学通过学费和研究伙伴关系对中国资金的令人担忧的依赖。来自参议员和国会议员的压力是自2018年以来至少15所大学关闭孔子学院的原因之一，孔子学院由中国出资，提供中文教学和安排文化活动。一项新的联邦限制也是一个因素，该限制禁止拥有孔子学院的大学, 将从国防部获得的资助汉语学习的资金。(背景知识: 美国国防部将汉语列为战略语言，由联邦政府拨款从幼儿园至大学提供汉语普通话教学。)

Some university administrators, scientists and civil libertarians(n.)(`=a person who strongly believes that people should have the freedom to do and think as they like 自由论者`) *worry that* `主` the administration’s conception(`=the process of forming an idea or a plan 构思；构想；设想`) of the “China threat” `系` *is* [*so*] broad and vague [*that 如此...以致于*] `主` anyone with the slightest connection to China `谓` *can become* a target for *questioning* by the FBI -- a new Red Scare(`=a situation in which a lot of people are anxious or frightened about sth 恐慌；恐惧`).

Lee Bollinger, president of Columbia, *published* an op-ed(n.)(`=(also *op-ed page*) ( NAmE ) the page in a newspaper opposite the editorial page that contains comment on the news and articles on particular subjects （报章上与社论版位置相对的）评论版`) [in the Washington Post] *titled* “No, I *won’t start spying on* my foreign-born students”.


====
- Op-ed 是个常见的新闻媒体术语，其实，*op-ed是opposite the editorial page的简写*，而后者的意思是：编辑页的对页。在一份报纸上，*editorial page通常是报社编辑发表评论、表达观点的地方，即：社论。而Op-ed，则是一个独立的版面，位置与社论版相对，它是非编辑人员，如：读者、独立撰稿人、或公众人物发声之地。*  +
中文里，op-ed可以理解或翻译为：独立评论版面、公众观点版面、自由时评专栏。 +
除了表示报纸上的单个版面，*op-ed也可以指该版面中的一篇独立文章，表示：独立时评、独立观点等。* Op-ed在指单篇文章时，也可以说成是：an op-ed piece。 +
参考例句：The former governor penned *a scathing op-ed* about the presidential candidate.（这位前州长写了一篇抨击总统参选者的独立评论）
====


Rafael Reif, the president of MIT, *wrote* in an open letter *that* students and staff of Chinese ethnicity “*tell me that*, in their dealings with government agencies, they now *feel* unfairly scrutinised(v.)(`=scrutinize : to look at or examine sb/sth carefully 仔细查看；认真检查；细致审查`), stigmatised(v.)(`=stigmatize : to treat sb in a way that makes them feel that they are very bad or unimportant 使感到羞耻；侮蔑`) and *on edge*(`=*be on edge* : to be nervous, excited or bad-tempered 紧张不安；激动；烦躁`).”

Several groups of Chinese and Chinese-American scientists *published a letter* in Science, America’s leading scientific journal, *expressing* fears of “scapegoating(v.)(`=scapegoat 替罪羊；代人受过者;/ 使成为…的替罪羊`), stereotyping 模式化观念（或形象）；老一套；刻板印象  and racial profiling(`=*racial profiling* : the fact of police officers, etc. suspecting that sb has committed a crime based on the colour of their skin or their race rather than on any evidence 种族形象定性（指警察等因肤色或种族而不是证据, 来怀疑人犯罪）/*profile* : to give or write a description of sb/sth that gives the most important information 扼要介绍；概述；写简介`)”.

====
- stigmatize => 来自希腊语 stigmatos,所有格形式于 stigma,烙印，刺痕标记，-ize,使。引申词义打上耻辱标 记，使受耻辱等。
====

一些大学管理人员、科学家和公民自由主义者担心，奥巴马政府对“中国威胁”的概念太过宽泛和模糊，任何与中国稍有关联的人, 都可能成为美国联邦调查局(fbi)质疑的对象 —— 这是一场新的红色恐慌。哥伦比亚大学校长李•博林格(Lee Bollinger)在《华盛顿邮报》(the Washington Post)发表了一篇专栏文章，题为“不，我不会开始监视我在外国出生的学生”。麻省理工学院总统课程的拉斐尔•赖夫(Rafael Reif), 在一封公开信中写道，华裔学生和教职工“告诉我，在与政府机构打交道时，他们现在感到受到了不公平的审视、受到了不公平的歧视、感到不安”。几组中国和华裔科学家, 在美国领先的科学杂志《科学》(Science)上发表了一封信，表达了他们对“替罪羊、成见和种族定性”的担忧。

Communist Party figures *have been happy(a.) to see* the Trump administration’s spy-hunt *portrayed*(`=过去分词,表被动`)(`=*~ sb/sth (as sb/sth)* :  to describe or show sb/sth in a particular way, especially when this does not give a complete or accurate impression of what they are like 将…描写成；给人以某种印象；表现`) *as* a xenophobic(a.)(`= If you describe someone as xenophobic, you disapprove of them because they show strong dislike or fear of people from other countries. 排外的; 有恐外症的`) exercise(`=*~ (in sth)* : an activity that is designed to achieve a particular result （为达到特定结果的）活动`).

====
- 上面句子中, 有一个句子: see  ... portrayed. 其实就是一个句型: *see sth / sb done 表示“看见某人或某物处于某种状态”，其中 sth /sb 与后面的 done 之间存在"被动"关系。* +
see sb done, *其中的done是"过去分词"*, 是动词的非谓语形式,在see sb done 这个结构中作"宾补",即表示和宾语之间的"被动关系". +
而如果是 be done , 那这个就是"谓语动词"的被动形式了, 就不是"非谓语动词"的被动形式了.
====

[In December] Hua Chunying, a foreign ministry spokeswoman, *praised* the “courage” of Fareed Zakaria, an American commentator （电台、电视台或报刊的）评论员 who *belittled*(`=belittle : to make sb or the things that sb does seem unimportant 贬低；小看`) the administration’s concerns [in an article headlined “The New China Scare”].

====
- portray => 来自古法语portraire,描绘，描画，来自por-,向前，traire,拉，来自拉丁语trahere,拉，词源同draw,drawing,tract.字面意思即向前拉，延展，引申词义描绘，描画等。拼写可能受tray影响俗化。
====

中国的共产党人士一直乐于看到特朗普政府的追捕间谍行动, 被描绘成排外行动。去年12月，外交部发言人华春莹赞扬了美国评论员法里德·扎卡里亚(Fareed Zakaria)的“勇气”，扎卡里亚在一篇题为“新中国恐慌”的文章中贬低了政府的担忧。

Bubbling up

往上冒泡；沸腾

The Trump administration, for its part(`=*for my, his, their, etc. part* : speaking for myself, etc. 就我（或他、他们等）而言`), *has tried to have things both ways*(`=*have/want it both ways* : to have or want to have the advantages of two different situations or ways of behaving that are impossible to combine （想）两全其美`).

While happy(a.) *to be seen as* tough(`=*~ (on/with sb/sth)* : demanding that particular rules be obeyed and showing a lack of sympathy for any problems or suffering that this may cause 严厉的；强硬的；无情的`) [by those *to* whom toughness 韧性;坚韧;健壮 *appeals*], [in public] officials *say that* {Chinese students and scholars *are* as welcome as ever}.

====
- by those *to* whom toughness *appeals* : 这句话, 正常顺序其实是这样的: toughness *appeals to* whom(即 those)
====


White House officials *claim* only *to be concerned about* a tiny fraction of people on student visas who *may be operating as* spies.

Though Mr Trump *is reported to have said*, at a dinner with American corporate bosses, *that* “`主` almost every student that *comes over to*(`=*come over (to...)* : to come to a place, especially sb's house, to visit for a short time （尤指到某人家中）短暂造访; /*come over (to...) (from...)* : to travel from one place to another, usually over a long distance （通常远距离地）从…到，从…来`) this country [from China] `系` *is* a spy”, he *said* at the G-20 summit last June *that* {“we *want to have* Chinese students *come*”} and *that* {they are “tremendous(`=very great 巨大的；极大的;/extremely good 极好的；精彩的；了不起的`) assets 资产；财产” who *should be treated* “just like anybody else”}.

====
- tremendous : a. +
=> 来自拉丁语 tremere,颤抖，恐惧，词源同 tremble.-end,动名词格，-ous,形容词后缀。引申词 义巨大的，极大的。 +
-> *a tremendous(`=very great 巨大的；极大的`) explosion* 巨大的爆炸声 +
-> It was *a tremendous(`=extremely good 极好的；精彩的；了不起的`) experience*. 这是个了不起的经历。
====
就特朗普政府而言，它试图两全其美。虽然很高兴被那些被强硬所吸引的人, 视为是强硬的，但在公开场合，官员们表示，中国学生和学者一如既往地受到欢迎。白宫官员声称，他们只关心一小部分持学生签证的人，他们可能是间谍。尽管据报道，特朗普在与美国企业老板共进晚餐时表示，“几乎每个(从中国)来到这个国家(即美国)的学生, 都是间谍”，但他在去年6月的20国集团(G20)峰会上表示，“我们希望中国学生到来”，他们是“巨大的资产”，应该“像其他任何人一样被对待”。


`主` *Fears of* China’s espionage(n.)间谍活动；谍报活动；刺探活动 `系` *are not* new(`=only recently produced or developed 新近产生的；新开发的；时鲜的`).

====
- espionage => e-, 缓音字母。spy, 间谍。
====

[Since 2011] more than 90% of all American prosecutions(`=the process of trying to prove in court that sb is guilty of a crime (= of prosecuting them) ; the process of being officially charged with a crime in court （被）起诉，检举；诉讼`) for economic espionage 间谍活动；谍报活动；刺探活动 *have been linked to* China.

But that *does not mean* their increased prominence(n.)(`=the state of being important, well known or noticeable 重要；突出；卓越；出名`) *can be simply chalked*(`=chalk 用粉笔写（或画）: *chalk sth up to sth* : to consider that sth is caused by sth 把某事归因于; /*chalk up sth* : to achieve or record a success, points in a game, etc. 获得，取得（成功）；记下，记录（成就、比赛得分等）`) *down to* a hawkish(a.)(`=preferring to use military action rather than peaceful discussion in order to solve a political problem 鹰派的；主战的；强硬的`) change under Mr Trump.

====
- prominence : n. +
-> a young actor who *has recently risen to prominence* 最近崭露头角的一名年轻演员 +
-> The newspapers *have given undue(a.)不适当的；过分的；过度的 prominence to* the story. 报章对这件事的报道太多了。
====

China *has changed, too*. Both its ambitions and its authoritarianism(`=au-tho-ri-ta-ria-nism : Authoritarianism is the state of being authoritarian or the belief that people with power, especially the State, have the right to control other people's actions. 独裁主义`) *have become* more marked(a.)(`=easy to see 显而易见的；明显的；显著的`), especially since President Xi Jinping *abolished* the term limit on his presidency in 2018.

`主` ① The internment(`=Internment is the practice of putting people in prison for political reasons. 政治拘禁`) of more than 1m Uighurs 维吾尔人 in detention(`=the state of being kept in a place, especially a prison, and prevented from leaving 拘留；扣押；监禁`) centres, ② a severe crackdown(n.)(`=*~ (on sb/sth)* : severe action taken to restrict the activities of criminals or of people opposed to the government or sb in authority 严厉的打击；镇压`) on lawyers and activists(n.)(`=a person who works to achieve political or social change, especially as a member of an organization with particular aims 积极分子；活跃分子`) and ③ a hardline(a.)强硬的；不妥协的 response to protests in Hong Kong `谓` *have fatally undermined*(`=to make sth, especially sb's confidence or authority, gradually weaker or less effective 逐渐削弱（信心、权威等）；使逐步减少效力;/从根基处破坏；挖…的墙脚`) the old argument(n.)(`=*~ (for/against sth) /~ (that...)* : a reason or set of reasons that sb uses to show that sth is true or correct 论据；理由；论点`) that `主` Western engagement(`=*~ (with sb/sth)* : ( formal ) being involved with sb/sth in an attempt to understand them/it （与…的）密切关系；（对…的）了解`) with China `谓` *would see* it *liberalise*(`=to make sth such as a law or a political or religious system less strict 使自由化；放宽对…的限制`).

In the past *it* was possible *to argue that* Chinese students in the West *would return home* [with new ideas about *freedom of expression* and *individual dignity*(`=a sense of your own importance and value 自豪；自尊；自重;/尊严；高贵`) and *political agendas* to match(v.)](`=if two things match , or if one thing matches another, they have the same colour, pattern, or style and therefore look attractive together 般配；相配`).

Now *it* is clear *that*, in some cases [at least], their presence *is* an overseas  海外的，国外的 redoubt(`=a place or situation in which sb/sth is protected when they are being attacked or threatened 藏身之所；堡垒; 最后堡垒; 指没有人能够对其发起攻击，宁静不会被破坏的安全地带/掩体；防御工事`) for the CCP’s ideas about conformity(n.)(`=*~ (to/with sth)* : ( formal ) behaviour or actions that follow the accepted rules of society （对社会规则的）遵从，遵守`) and loyalty.

====
- redoubt => 来自 re-,向后，往回， -duct,拉，引导，词源同 conduct,reduction.拼写受 doubt 影响俗化。
====
对中国间谍活动的担忧并不新鲜。自2011年以来，超过90%的美国对经济间谍活动的起诉, 都与中国有关。但这并不意味着这些事情知名度的上升, 可以简单地归因于特朗普领导下的鹰派变化。中国也发生了变化。它的野心和威权主义都变得更加明显，特别是自2018年习近平主席取消主席任期限制以来。100多万维吾尔族人被关押在拘留中心，对律师和活动人士的严厉镇压，以及对香港抗议活动的强硬回应，都致命地削弱了这个观点理由 : 西方对中国的密切接触, 能够令中国变得自由化。在过去，人们可能会争辩说，在西方的中国学生回国后, 会带着关于言论自由、个人尊严, 和政治议程的新思想回国。现在很明显，至少在某些情况下，他们在美国的存在, 只是作为海外堡垒, 来遵循中国共产党关于顺从和忠诚的思想。

Some China-watchers *point to* Australia *as* a worrying exemplar(`=a person or thing that is a good or typical example of sth 模范；榜样；典型；范例`).

Australian officials *have warned* [for years] *of* China’s influence operations in the country, *including* at universities.

[In July] students from mainland China *threw punches 用拳猛击 at* other students (*demonstrating*(`=*~ (against sth) /~ (in favour/support of sth)* :  to take part in a public meeting or march, usually as a protest or to show support for sth 集会示威；游行示威`) in solidarity(n.)(`=*~ (with sb)* : support by one person or group of people for another because they share feelings, opinions, aims, etc. 团结；齐心协力；同心同德；相互支持`) with the Hong Kong protesters at the University of Queensland).

The consul(`=a government official who is the representative of his or her country in a foreign city 领事`)-general(`=a consul of the highest grade, usually stationed in a city of considerable commercial importance 总领事`) in Brisbane 布里斯班（澳大利亚东部城市）, `主` Xu Jie -- who `系` *is*, unusually for a senior Chinese diplomat, `表` an adjunct(n.)(`=a thing that is added or attached to sth larger or more important 附属物；附件`) lecturer((尤指英国大学的）讲师) 兼职讲师 at the university -- `谓` *praised* them *for* their “patriotic(a.)(`=having or expressing a great love of your country 爱国的`) behaviour”.

一些中国观察家指出，澳大利亚是一个令人感到担忧的受害者典型。澳大利亚官员多年来, 一直对中国在该国的影响力行动发出警告，包括在大学里。今年7月，昆士兰大学(University of Queensland)中的来自中国大陆的学生, 对其他支持香港抗议者, 并与其团结一致的示威学生, 拳打脚踢。驻布里斯班总领事, 赞扬了他们的“爱国行为”. 他一名中国高级外交官, 但不同寻常的是, 他还是该大学的兼职讲师.

*Talks by* Chinese dissidents 持不同政见者 *are* a particularly touchy(a.) (`=that may upset or offend people and should therefore be dealt with carefully 敏感性的；需要小心处理的；棘手的;/*~ (about sth)* : ( of a person 人) easily upset or offended 易烦恼；易生气；易怒`)) subject(`=a thing or person that is being discussed, described or dealt with 主题；题目；话题；题材；问题`).

In 2015 `主` Teng Biao, who *is* now an adjunct lecturer 兼职讲师 at Hunter College in New York, `系` *was* a visiting scholar at Harvard Law School.

In a report on Chinese influence at American universities *produced by* the Wilson Centre, a think-tank, in 2018, Mr Teng *described* how he *planned to invite* Chen Guangcheng, a blind lawyer who in 2012 *made* a daring 勇敢的；敢于冒险的 solo(a.)(`=done by one person alone, without anyone helping them 独自的；单独的`) escape from house arrest(`=*house arrest* : the state of being a prisoner in your own house rather than in a prison 软禁`) to the American Embassy in Beijing, *to give a talk* there. (这里的 to give a talk 其实是和上面的 to invite Chen Guangcheng 连成一句的, 即 : *to invite* Chen Guangcheng *to give a talk* there)

An “influential person” at the university *persuaded* him *that* {`主` hosting 主办，主持（活动）Mr Chen `谓` *would “reflect poorly on*(`=*REFLECT WELL, BADLY, ETC. ON SB/STH* : to make sb/sth appear to be good, bad, etc. to other people 使给人以好的（坏的或其他）印象`) Harvard”}: the university’s then-president, Drew Faust, *was [in Beijing] meeting* Mr Xi.

由中国异见人士来做会谈, 这种事特别敏感。Teng Biao(滕彪?) 如今是纽约亨特学院兼职讲师, 他在2015年时，是哈佛法学院的访问学者。2018年时, 智库威尔逊中心(Wilson Centre)发表的一份报告, 讨论了中国在美国大学的影响力情况. 在其中, Teng Biao 描述了他是如何计划邀请 Chen Guangcheng 来哈佛法学院做演讲的.  Chen Guangcheng 是是一名盲人律师，2012年时, 他从软禁中大胆地独自逃到了美国驻北京大使馆。 但是, 哈佛的一位“有影响力的人士”劝说他说, 接待Chen Guangcheng 将会“给哈佛带来负面影响”：因为当时的哈佛校长德鲁·福斯特(Drew Faust)正在北京会见习主席。

Mr Teng *is* still unwilling *to identify* the “powerful professor” who *warned him off*. He *thinks* it *could further damage* his prospects in the job market, where his position as a dissident 持不同政见者 *is* already a black mark(`=*black mark* : a note, either in writing on an official record, or in sb's mind, of sth you have done or said that makes people think badly of you （记录在案的或留在别人印象中的）污点`): “The pressure from the Chinese government *is* real and is strong.”

The Wilson Centre report *also documented*(v.)(`=to record the details of sth 记录，记载（详情）`) instances of what *appeared to be* blatant(a.)(`=done in an obvious and open way without caring if people are shocked 明目张胆的；公然的`) efforts by China *to influence* free expression, *including* freezing(v.) Chinese participation in lucrative(a.)(`=producing a large amount of money; making a large profit 赚大钱的；获利多的`) programmes *for* [such] offences 违法行为,犯罪,罪行;冒犯；搅扰；侮辱 [as](=`such...as...`) *inviting* the Dalai Lama *to speak* on campus.

====
- blatant => blat, 同bleat, 羊叫，拟声词。指明目张胆的说坏话。
====
那位警告他不要这么做的“有权势的教授”, 滕彪仍不愿透露出他的身份。他认为，这可能会进一步损害他在就业市场上的前景。在就业市场，他(应该只那位有权势的教授)作为持不同政见者的地位已经是一个污点：“来自中国政府的压力是真实的，而且是强大的。”  +
威尔逊中心的报告, 还记录了中国似乎公然影响言论自由的例子，包括比如因邀请达赖喇嘛在校园演讲等罪行, 而冻结该中国人参与有利可图的节目。


Beijing’s wishes in such matters *are often communicated* through the Chinese Students and Scholars Associations (CSSAS), that *are to be found* on more than 150 American campuses.

In 2019 `主` the CSSA at Purdue University in Indiana `谓` *asked* administrators *to cancel* a talk by Mr Chen.

[When the talk *went ahead* [with police protection] the organisation *circulated*(`=to send goods or information to all the people in a group 传送；传递；传阅`) an announcement (that such speaking events *provoke*(`= :v. to cause a particular reaction or have a particular effect 激起；引起；引发;/*~ sb (into sth/into doing sth)* to say or do sth that you know will annoy sb so that they react in an angry way 挑衅；激怒；刺激`)) “fierce controversy(n.)(`=public discussion and argument about sth that many people strongly disagree about, disapprove of, or are shocked by （公开的）争论，辩论，论战`) and dissatisfaction among Chinese students.”)

北京在这类问题上的愿望, 通常是通过中国学生学者联谊会(CSSA)传达的，该联谊会遍布150多所美国校园。2019年，印第安纳州普渡大学的CSSA, 要求校方管理人员取消陈先生的一次演讲。当谈话继续进行时(在警方的保护下)，该组织传阅了一份声明，称这样的演讲事件在“中国学生中, 引发了激烈的争议和不满”。

`主` Other manifestations(`=an event, action or thing that is a sign that sth exists or is happening; the act of appearing as a sign that sth exists or is happening 显示；表明；表示`) of Chinese influence `系` *are* more subtle 不易察觉的；不明显的；微妙的.

====
- manifestation : (1)~ (of sth) : an event, action or thing that is *a sign* that sth exists or is happening; *the act* of appearing as a sign that sth exists or is happening 显示；表明；表示 +
-> The riots are *a clear manifestation of* the people's discontent. 骚乱清楚地表明了人们的不满情绪 +
(2)  an appearance of a ghost or spirit （幽灵的）显现，显灵 +
-> The church is the site of *a number of supernatural manifestations*. 这座教堂是个鬼魂屡次出没的地方。
====


Columbia *shows off*(`=*show sb/sth off* : to show people sb/sth that you are proud of 炫耀；卖弄；显示`) a bust（石或金属的）半身像 of Vaclav Havel, `主` the dissident 持不同政见者 playwright(`=a person who writes plays for the theatre, television or radio SYN dramatist 剧作家`) who, after the fall of communism, `谓` *became* president of the Czech 捷克的；捷克人的 Republic; he *was* a guest of the university for some weeks in 2006.

But they *will not find* a bust of Liu Xiaobo, a Chinese writer who *won* the Nobel peace prize for his human rights activism(`=Activism is the process of campaigning in public or working for an organization in order to bring about political or social change. 行动主义`), *despite the fact that* he too *had been* a guest at the university, back in 1989. (`主` A request (*to place* such a bust), *made [on behalf of*(`=*ON BEHALF OF SB ON SB'S BEHALF* : as the representative of sb or instead of them 代表（或代替）某人; /because of sb; for sb 因为某人；为了某人`) his widow 寡妇；遗孀], `谓` *was rejected*.)

====
- bust => 衍生出“胸部”之意。 bust：n. [bʌst] n.半身雕像；胸部 busty：['bʌsti] adj.胸部丰满的，大胸脯的
- widow => 来自 PIE weidh,分开，词源同 wide,with,divide.用于指寡妇。
====

中国影响力的其他方面表现, 也更微妙。哥伦比亚大学展示了异见人士瓦茨拉夫·哈维尔(Vaclav Havel)的半身像，他是一位剧作家, 并在共产主义垮台后成为了捷克总统；2006年，他曾在该大学做客数周。但该大学中, 不会发现刘晓波的半身像，这位中国作家因其人权行动而获得诺贝尔和平奖，尽管他在1989年也曾是这所大学的嘉宾。(代表他的遗孀来提出的一项请求 -- 放置这样一尊半身像 -- 被拒绝了。)。


[In the curricula 课程 and cultural activities of Confucius Institutes] `主` language students `谓` *will find* no *more* mention(`=an act of referring to sb/sth in speech or writing 提及；说起；写上一笔`) of human-rights activists like Liu *than* they *will* of the Tiananmen Square protests in 1989 or the repression in Xinjiang.

在孔子学院的课程和文化活动中，语言专业的学生不会发现更多像刘这样的人权活动家，就像他们不会发现1989年的xx事件或新疆的镇压一样。


`主` Students from China `谓` often *refrain*(v.)(`=*~ (from sth/from doing sth)* : ( formal ) to stop yourself from doing sth, especially sth that you want to do 克制；节制；避免`) *from* discussing(v.) sensitive subjects [in front of other Chinese students].

A professor at one Ivy 常春藤 League 联盟；同盟 university *says that* {[after some students *asked* to submit(v.) written work (*touching on* human rights) [under a pseudonym 假名；化名；笔名]] he now *offers* that option *to* all}.

Alex and Victor *avoid* sensitive topics [when with their peers] and *keep* their distance *from* Columbia’s CSSA.

“[In China too] I *heard* so many stories about students *reporting on*(`=report : *~ sth (to sb) /~ sb (to sb) (for sth/for doing sth)* : to tell a person in authority about a crime, an accident, an illness, etc. or about sth bad that sb has done 举报；告发`) their professors because their professors *mentioned* Tiananmen in class,” Victor *says*. “These fellow students *would do this* in mainland China /and they *would do the same* abroad.”

来自中国的学生, 通常避免在其他中国学生面前讨论敏感话题。常春藤盟校的一位教授说，在一些学生要求用化名来提交涉及人权的书面作品后，他现在向所有人都提供了这个选择。亚历克斯和维克多, 与同龄人在一起时, 会避免敏感话题，并与哥伦比亚大学的CSSA保持距离。维克多说：“在中国，我也听说过很多关于学生告发教授的事，因为他们的教授在课堂上提到了天安门。”“这些同学在中国大陆会这样做，在国外同样也会这样做。”

Worlds within worlds

世界中的世界。

The number of Chinese students in America *is not yet dropping* [in response to any of this].

`主` The fact that it *has ceased* growing `谓` *may have* something *to do with* the tensions, or with worries about visas.

But some of those worries *are not* specific(`=existing only in one place or limited to one thing 特有的；独特的`) to China; numbers of students from elsewhere *are* down, too.

And other factors *are* at play 起作用. Foreign-exchange 外汇 controls *have tightened*; China’s economy *has slowed*.

`主` More Chinese families (now *sending* children abroad) `谓` *may opt*(`=*~ (for/against sth)* : to choose to take or not to take a particular course of action 选择；挑选`) *for* cheaper destinations 目的地；终点.

[Though America *is* still preferred(a.v.)], `主` enthusiasm(`=*~ (for sth/for doing sth)* : a strong feeling of excitement and interest in sth and a desire to become involved in it 热情；热心；热忱`) for it `谓` *is waning*(`=wane : to become gradually weaker or less important 衰落；衰败；败落；减弱`) while `主` enthusiasm for Britain `谓` *waxes*(`=wax : 给…上蜡；给…涂蜡; /*wax and wane* : to increase then decrease in strength, importance, etc. over a period of time （力量、重要性等）兴衰枯荣，盛衰；阴晴圆缺`).

====
- wane => 来自 Proto-Germanic wano,缺乏，空无，词源同 want,waste.引申词义衰弱。
====

作为对这一切的回应，在美国的中国学生人数并没有因此而减少。它停止增长的事实, 可能是与中美之间的紧张局势有关，也可能是与对签证的担忧有关。但其中一些担忧并不是中国特有的；来自其他地方的学生数量也在下降。而其他因素也在发挥作用。外汇管制收紧；中国经济放缓。如今越来越多的把孩子送到国外念书的中国家庭，他们可能会选择更便宜的目的地。尽管美国仍然是首选，但人们对美国的热情正在减弱，而对英国的热情却在上升。

But the boom *is* over -- and so *are* the hopes (that `主` it `谓` *might* [in and of itself(`=with respect to its inherent nature 就其本质而言;其内部及本身的`)] *bring* new amity(n.)(`=a friendly relationship between people or countries 和睦；友好`)).

`主` *Both* the greater number of Chinese students *and* the greater power of information technology `谓` *mean that* it is ever easier for them *to remain isolated* on campus, *mixing* little *with* their American peers 身份（或地位）相同的人；同龄人；同辈.

They *use* WeChat, a social-media app, [*both*] *to stay*(`=to continue to be in a particular state or situation 保持；继续是`) in touch with friends and family (back home) [*and*] *as*(=`和前面的use, 构成 use...as...用作为`) their sole source of news, much of which *reflects* their government’s view of their host country.

In 2018 `主` a Purdue University survey of a large midwestern university `谓` *found that* 42% of Chinese students *had* a less favourable(`=positive and showing your good opinion of sb/sth 肯定的；赞同的；支持的`) perception(`=an idea, a belief or an image you have as a result of how you see or understand sth 看法；见解`) of America *than* they *had* [when they arrived]; just 16% *said* {their impression *had improved*}.

Their study abroad *has not exactly built* a bridge [between the two countries].

`主` The intense(`=very great; very strong 很大的；十分强烈的; /serious and often involving a lot of action in a short period of time 严肃紧张的；激烈的`) scrutiny they *face* from both Beijing and Washington `谓` *threatens to widen* the divide.

但繁荣已经结束了，希望它能带来新的友好关系, 也已经结束。更多的中国学生和更强大的信息技术力量, 都意味着他们在校园里更容易保持孤立，很少与美国同龄人打成一片。他们使用社交媒体app微信，既是为了与国内的朋友和家人保持联系，也是他们唯一的新闻来源，其中的内容大部分都反映了他们的政府对东道国的看法。2018年，普渡大学(Purdue University)对中西部一所大型大学进行的一项调查发现，42%的中国学生对美国的印象, 比他们来美国时要差；只有16%的人表示他们的印象有所改善。他们在国外的学习, 并没有真正在两国之间架起一座桥梁。他们面临着来自北京和华盛顿的严格审查，这可能会扩大分歧。


---

== 08. The new red scare on American campuses 纯净版

`主` Both their host government and their home government `谓` *increasingly view* Chinese students [with suspicion]



Jan 2nd 2020 | NEW YORK

[EARLY LAST autumn] Alex and Victor, two students from mainland China, *sat* in the back row of a packed auditorium at Columbia Law School, in New York. They *were* there *for* a talk by Joshua Wong, thrice-jailed young hero of the Hong Kong democracy movement, which the two students *support*. They *applauded enthusiastically*; they also *wore* blue face masks.

The masks *were* [in part] symbols of solidarity with Mr Wong’s fellow protesters half a world away. But they *were* also a way of *hiding* their identities ① *from* face-recognition systems in China that *might be scanning* pictures of the audience, and ② *from* Chinese students in the hall (less in tune with Mr Wong’s message) -- such as the ones who *sang* the national anthem of the People’s Republic *in response to* the talk. Their names *are not*, in fact, Alex and Victor; they *asked* The Economist *to give* them pseudonyms and *not to say* where in China they came from. *As* they *talked*, other Chinese students *quietly observed* them, national flags in hand.

There are 19.8m university students in America, of whom just over a million *come from* other countries. A bit less than a fifth of these foreigners *come from* India, and 6% *from* the European Union. Fully a third *are* Chinese -- a much larger fraction *than* from anywhere else, and *more* students [*than* China *sends to* all the other countries in the world put together]. At Columbia, half of the nearly 12,000 international students *are* from China. This *is* all very good for the students’ future prospects and the universities’ coffers. But it *worries* the American government, the Chinese Communist Party (CCP) and some champions of academic freedom.

The American government *thinks* {some Chinese students and researchers *are responsible for* a great deal of intellectual-property theft}. The CCP *fears that* {people like Alex and Victor *are contracting* dangerous levels of democratic idealism}. And `主` China’s efforts *to curtail* the room (such dissidence *has to flourish* in) `谓` *worries* people who *care about* free expression on American campuses and beyond.

A special relationship



The number of mainland Chinese students in America *grew by 276%* over the past decade (see chart 1) *as* China’s elite *sought* to buy(v.) excellent educations *for* their children /and `主` American researchers *sought* talent. In 2018, the most recent year for which figures *are* available, Chinese graduate students *received* 13% of all science and engineering doctorates *awarded by* American universities.

The rate (at which researchers at the Massachusetts Institute of Technology (MIT) co-author papers with colleagues at leading Chinese universities) *has risen tenfold* over the past decade -- part of a trend (which *has seen* `主` collaborations between American and Chinese researchers `谓` *become* more numerous *than* collaborations with any other country (see chart 2)). Many Chinese researchers *have* significant resources *as well as* sharp minds; some sorts of lab work *are* easier and cheaper in China *than* in America. *It* is hardly surprising *that* `主` American researchers -- especially the growing number (who *have* former pupils back in China) -- `谓` *want to work with them*.



Not all of this collaboration *is* peer-to-peer. Chinese companies *fund* an increasing amount of research at American universities, *including* into areas (*prioritised* in the “*Made* in China 2025” industrial-policy initiative -- a policy (America’s Department of Justice *has referred to as* a “roadmap to [intellectual-property] theft”)). MIT, for example, *has* research partnerships with SenseTime, a Hong Kong company that *provides* facial-recognition technology *to* Chinese police, and iFlytek, a Chinese firm that *works on* voice recognition and which *has paid for* research at Princeton and Rutgers.

The administration of President Donald Trump *worries about* all this. In the past two years, `主` scrutiny of mainland Chinese on American campuses `谓` *has intensified*, and with it scrutiny of other students and researchers who are ethnically Chinese, *including* Chinese-Americans. Some *see* this new scrutiny *as* {*testing* American academia’s reputation for openness, international co-operation and the free exchange of ideas}. Christopher Wray, the director of the FBI, *believes* {it *provides* a valuable counterweight *to* academic “naivety”}.

In 2018 Mr Wray *testified to* the Senate intelligence committee *that* {China *poses* a “whole-of-society threat” *to* America, one (which *demands* a “whole-of-society response”)}. [In Mr Wray’s analysis] `主` the fact that American researchers *collaborate so much with* Chinese researchers `系` *is* a cause for concern; such scientists and students *are* among the “non-traditional collectors” of an intelligence operation (he *has described as* “deep and diverse and wide and vexing”).

[In 2018 and 2019] agents from the FBI’s 56 national field offices *contacted* hundreds, perhaps thousands, of students, researchers and professors (*with ties to* China) -- many of them from China or ethnically Chinese, *including* Chinese-Americans -- *to determine* whether they *might be working [on behalf of]* the Communist Party. The National Institutes of Health (NIH), Department of Energy and other providers of federal grants *have urged* universities *to monitor* researchers for connections to Chinese institutions or “talent” programmes which *seek to attract* scientists, often Americans of Chinese ethnicity, who *have gained* expertise (*deemed of* value in China). `主` China’s “Thousand Talents” programme, which in part *offers* scientists incentives *to set up* labs in China, `谓` *was used to recruit* at least 6,000 experts *from* overseas between 2008 to 2017.

The NIH *says that* it *has identified* 180 researchers (*to whom* it has *provided* grants) who *may not have disclosed* payments from, or other affiliations with, Chinese institutions -- *including* some (who *appear to have established* “shadow labs” in China *mirroring* their NIH-funded ones in America). In 2019 `主` two research institutions -- MD Anderson, a cancer-research centre in Houston, and Emory University in Atlanta -- `谓` *cut ties with* five researchers, all of them ethnically Chinese, who *had taken money from* China. [In December] federal authorities *arrested* a Chinese cancer researcher at Logan Airport in Boston [after he allegedly *tried to smuggle to China* vials of biological material *taken from* a Harvard teaching hospital]. (His Harvard-sponsored visa *has also been revoked*.)

But officials at some universities *say that* private briefings from the FBI *have left* them *[both]* unconvinced of the scope of the problem *[and]* unclear what actions *need to be pursued*. “What exactly Mr Wray *has* in mind, where precisely he *sees* the threat -- this *is all left* frustratingly vague,” *says* an international-research administrator at an elite university that *has been briefed by* the FBI (and where the FBI *has also interviewed* visiting(a.) Chinese scholars). “Some of the guidance *has been*, ‘*Be careful about* anything *to do with* biotech.’ Well biotech *is* huge … I *don’t even know* which faculty *to talk to* if you *don’t tell me* more.”

Risk management

*Faced with* such scepticism, last summer the National Security Council, the State Department, the Department of Justice (though not the FBI) and experts (on Chinese influence operations) *briefed* some 15 university presidents, provosts(n.) and other senior administrators in a two-day session at St Michaels, Maryland. `主` One of those (*giving* the briefings) `谓` *noted that* `主` the idea (of technology (*developed* on their campuses) (*aiding* China’s repression(n.) of Uighurs in the western province of Xinjiang)) `谓` *seemed* particularly salient(a.) to the administrators: such links *could damage* their institutions’ reputations. This *is not* a purely theoretical issue. [In October] `主` SenseTime and iFlytek, the artificial-intelligence firms with research partnerships at MIT, `谓` *were blacklisted by* the American government *for* allegedly *abetting* the abuses in Xinjiang.

[As well as *investigating*(v.) Chinese students and researchers already in America], the administration *has also looked at* ways (*to make it harder* for them *to arrive* /and *easier* for them *to be expelled*). In 2018 some of Mr Trump’s aides(n.) *argued for* severe restrictions on student visas for Chinese nationals. [*Instead* `主` the administration `谓` *curtailed* five-year visas for foreign graduate students in certain fields of science and technology such as aviation and robotics]; these students now *get* renewable one-year visas. The Department of Homeland Security has also made *it* easier *to declare that* foreign students *are overstaying* their visas. Educators *report anecdotally that* invited Chinese scholars *are finding* {*it* much harder *to get* visas}, *including* short-term visas for academic conferences that in the past *were routinely issued*.

`主` *Concerns about* what Chinese students *get up to* `系` *are not unique to* the executive branch. `主` Marco Rubio, a Republican senator from Florida, and Mark Warner, a Democratic senator from Virginia, `系` *have been* among the most prominent figures on Capitol Hill 分词作状语 *warning [not just] of* Chinese intelligence operations at American universities, *[but also] of* those universities’ worrying dependence on Chinese money *via* tuition fees and research partnerships. Pressure from senators and congressmen *is* one of the reasons why, since 2018, at least 15 universities *have closed* the Confucius Institutes, *paid for by* China, that *offer* Chinese language instruction /and *arrange* cultural events. `主` A new federal restriction (that *bars* universities (with Confucius Institutes) *from* Defence Department funding(n.) (*for* Chinese-language study)) `系` *has also been* a factor.

Some university administrators, scientists and civil libertarians *worry that* the administration’s conception of the “China threat” *is* [*so*] broad and vague [*that*] anyone with the slightest connection to China *can become* a target for *questioning by* the FBI -- a new Red Scare. Lee Bollinger, president of Columbia, *published* an op-ed in the Washington Post *titled* “No, I *won’t start spying on* my foreign-born students”. Rafael Reif, the president of MIT, *wrote* in an open letter *that* students and staff of Chinese ethnicity “*tell me that*, in their dealings with government agencies, they now *feel* unfairly scrutinised, stigmatised and on edge.” Several groups of Chinese and Chinese-American scientists *published* a letter *in* Science, America’s leading scientific journal, *expressing* fears of “scapegoating, stereotyping and racial profiling”.

Communist Party figures *have been happy to see* the Trump administration’s spy-hunt portrayed *as* a xenophobic exercise. [In December] Hua Chunying, a foreign ministry spokeswoman, *praised* the “courage” of Fareed Zakaria, an American commentator who *belittled* the administration’s concerns [*in* an article *headlined* “The New China Scare”].

*Bubbling up*

The Trump administration, for its part, *has tried to have* things both ways. While *happy to be seen as* tough(a.) [*by* those *to* whom toughness *appeals*], [in public] officials *say that* {Chinese students and scholars *are* as welcome as ever}. White House officials *claim* {only *to be concerned about* a tiny fraction of people on student visas who *may be operating as* spies}. Though Mr Trump *is reported to have said*, at a dinner with American corporate bosses, *that* “`主` almost every student that *comes over to* this country [from China] `系` *is* a spy”, he *said* at the G-20 summit last June *that* {“we *want to have* Chinese students *come*”} and *that* {they *are* “tremendous assets” who *should be treated* “just like anybody else”}.

`主` *Fears of* China’s espionage `系` *are not* new. [Since 2011] more than 90% of all American prosecutions for economic espionage *have been linked to* China. But *that does not mean* their increased prominence *can be simply chalked down to* a hawkish change under Mr Trump. China *has changed, too*. Both its ambitions and its authoritarianism *have become* more marked, especially since President Xi Jinping *abolished* the term limit on his presidency in 2018. `主` ① The internment of more than 1m Uighurs in detention centres, ② a severe crackdown on lawyers and activists and ③ a hardline response to protests in Hong Kong `谓` *have fatally undermined* the old argument that Western engagement with China *would see* it liberalise. [In the past] *it* was possible *to argue that* {Chinese students in the West *would return home* with new ideas about ① freedom of expression and ② individual dignity and ③ political agendas *to match*}. Now it is clear that, in some cases at least, their presence *is* an overseas redoubt for the CCP’s ideas about conformity and loyalty.

Some China-watchers *point to* Australia *as* a worrying exemplar. Australian officials *have warned* [for years] *of* China’s influence operations in the country, *including* at universities. [In July] students from mainland China *threw punches at* other students *demonstrating* [*in solidarity with* the Hong Kong protesters] at the University of Queensland. `主` The consul-general in Brisbane, Xu Jie -- who *is*, unusually for a senior Chinese diplomat, an adjunct lecturer at the university -- `谓` *praised* them *for* their “patriotic behaviour”.

`主` *Talks by* Chinese dissidents `系` *are* a particularly touchy subject. [In 2015] `主` Teng Biao, who *is* now an adjunct lecturer at Hunter College in New York, `谓` *was* a visiting scholar at Harvard Law School. [In a report on Chinese influence at American universities *produced by* the Wilson Centre, a think-tank, in 2018], Mr Teng *described* how he *planned to invite* Chen Guangcheng, a blind lawyer who in 2012 *made* a daring solo escape *from* house arrest *to* the American Embassy in Beijing, *to give a talk* there. An “influential person” at the university *persuaded* him *that* {`主` *hosting* Mr Chen `谓` *would* “reflect poorly on Harvard”: the university’s then-president, Drew Faust, *was* in Beijing *meeting* Mr Xi}.

Mr Teng *is still unwilling to identify* the “powerful professor” who *warned him off*. He *thinks* {it *could further damage* his prospects in the job market, where his position as a dissident *is* already a black mark}: “The pressure from the Chinese government *is* real and *is* strong.” The Wilson Centre report(n.) also *documented* instances of what *appeared to be* blatant efforts(n.) (by China) *to influence* free expression, *including* {freezing(v.) Chinese participation in lucrative programmes *for* *[such]* offences *[as]* *inviting* the Dalai Lama *to speak* on campus}.



Beijing’s wishes in such matters *are often communicated* [*through* the Chinese Students and Scholars Associations (CSSAS), that *are to be found* on more than 150 American campuses]. In 2019 the CSSA at Purdue University in Indiana *asked* administrators *to cancel* a talk by Mr Chen. [When the talk *went ahead* (with police protection)] the organisation *circulated* an announcement (that `主` such speaking events `谓` *provoke* “fierce controversy and dissatisfaction [among Chinese students].”)

Other manifestations of Chinese influence *are* more subtle. Columbia *shows off* a bust of Vaclav Havel, the dissident playwright who, after the fall of communism, *became* president of the Czech Republic; he *was* a guest of the university for some weeks in 2006. But they *will not find* a bust of Liu Xiaobo, a Chinese writer who *won* the Nobel peace prize for his human rights activism, *despite the fact that* he too *had been* a guest at the university, back in 1989. (`主` A request *to place* such a bust, *made [on behalf of]* his widow, `谓` *was rejected*.)

[In the curricula and cultural activities of Confucius Institutes] language students *will find* no *more* mention of human-rights activists like Liu *than* they will of the Tiananmen Square protests in 1989 or the repression in Xinjiang.

`主` Students from China `谓` *often refrain from* discussing(v.) sensitive subjects [in front of other Chinese students]. A professor at one Ivy League university *says that* {[after some students *asked to submit* written work *touching on* human rights [under a pseudonym]] he now *offers* that option *to* all}. Alex and Victor *avoid* sensitive topics [when with their peers] and *keep* their distance *from* Columbia’s CSSA. “[In China too] I *heard* so many stories about students *reporting on* their professors because their professors *mentioned* Tiananmen in class,” Victor *says*. “These fellow students *would do this* in mainland China /and they *would do the same* abroad.”

Worlds within worlds

The number of Chinese students in America *is not yet dropping* [*in response to* any of this]. `主` The fact (that it *has ceased* growing) `谓` *may have* something *to do with* the tensions, or *with* worries about visas. But some of those worries *are not specific to* China; numbers of students from elsewhere *are down, too*. And other factors *are* at play. Foreign-exchange controls(n.) *have tightened*; China’s economy *has slowed*. `主` More Chinese families now *sending* children abroad `谓` *may opt for* cheaper destinations. Though America *is* still preferred, enthusiasm for it *is waning* while enthusiasm for Britain *waxes*.

But the boom *is* over -- and so *are* the hopes (that `主` it `谓` *might* [in and of itself] *bring* new amity). `主` *Both* the greater number of Chinese students *and* the greater power of information technology `谓` *mean that* {*it* is ever easier for them *to remain isolated* on campus, *mixing* little *with* their American peers}. They *use* WeChat, a social-media app, *[both] to stay* in touch with friends and family back home [*and*] *as* their sole source of news, much of which *reflects* their government’s view of their host country. In 2018 `主` a Purdue University survey of a large midwestern university `谓` *found that* {42% of Chinese students *had* a less favourable perception of America *than* they *had* when they *arrived*; just 16% *said* their impression *had improved*}. Their study abroad *has not exactly built a bridge* between the two countries. `主` The intense scrutiny they *face from* both Beijing and Washington `谓` *threatens to widen* the divide.

---




