= 0256
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 256: Looking for Ideas.
This is English as a Second Language Podcast episode 256. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Remember to visit our website at eslpod.com for more information about this podcast and for a Learning Guide to this episode.
Our topic today is called “Looking for Ideas.” It is a conversation between two people, Sam and Ling, who are talking about new ideas for their company. Let's get started.
[start of story]
Ling: Ugh!
Sam: What’s the matter?
Ling: I’m trying to jot down some ideas for the meeting tomorrow but I’m drawing a blank.
Sam: When I’ve got a block, I usually step away from it for a while and come back to it later. Then I can look at it with a fresh perspective.
Ling: I don’t have time to take a break. I need to come up with something quick or I’ll have to go into that meeting empty-handed. I can’t let Danielle show me up again. At the last meeting, all of the department heads loved her ideas and they’re starting to think she walks on water.
Sam: Well, I don’t think it helps to sit around worrying about it. Nothing will come to you if you work yourself up too much.
Ling: You’re right. I’m too wound up to think straight. It’s like my brain is in a fog.
Sam: Come on. We’ll go take a quick walk. I’m sure that’ll do the trick. If it doesn’t, I’ll help you work on your resume.
Ling: Gee, thanks. I’ve known all along that you’re after my job.
Sam: Me? After your job? I wouldn’t touch your job with a 10-foot pole. I couldn’t take the pressure. I prefer being a lowly employee and giving you a hard time everyday.
Ling: Thanks a lot. Between you and Danielle, my days here are numbered.
Sam: Come on. Let’s go before you get even more depressed!
[end of story]
Our dialogue begins with Ling making a sound that indicates that she is having problems. Sam says, “What’s the matter,” meaning what is the problem. Ling says that she's “trying to jot down some ideas for the meeting tomorrow but” she's “drawing a blank.” To jot, “jot,” down something means to write something down quickly. Usually it is a note - a small message to yourself or to someone else. So, to write something down quickly or to note something quickly is to jot something down. Someone may call you and give you their telephone number; you would jot it down - you would write it down quickly as they were telling you.
To draw a blank, “blank,” means not to be able to think of a good idea or an answer to something. Someone says, “What is the capital of the state of Texas,” and you can say, “Oh, I'm drawing a blank; I can't think of it.” Ling is drawing a blank for the meeting that she has tomorrow; she needs to come up with - to create - some new ideas.
Sam says that when he has a block, he usually steps away from the project for a while and comes back to it later. A block, “block,” means that you are unable to think of something - you're not able to think of something. Someone may say, “I have a block; I can't think of the name of that singer I heard on the radio.” Block has a couple of meanings in English; take a look at the Learning Guide for more information.
The expression to step away from something means to stop what you are doing and to work on something else for a short period of time, and then go back again and work on it. So, if you're having a problem with something, sometimes it is best to stop working on the problem, go away, and then return and try working on it again. That's to step away from something.
So, Sam says when he has a block - when he can't think of some new ideas - he steps away from project. “Then,” he says, “I can look at it with a fresh perspective.” A fresh, “fresh,” perspective, “perspective,” is a new or creative way of looking at something. The word fresh is one we use, for example, for vegetables. You say, “The vegetables are fresh,” meaning they're not old - the opposite of being old, they're fresh - they're new. So, a fresh perspective is like a new way of looking at something.
Ling says that she doesn't have time to take a break. She needs to come up with - or create - something quickly, if she doesn't, she'll have to go to her meeting empty-handed. The expression empty, “empty-,” handed, “handed,” means unprepared - without having anything. You may go to someone's party, and your friend says to you, “Well, don't go empty-handed,” meaning you should bring something for other people to eat or drink at the party.
Ling says that she can't let - or allow - Danielle, a woman that she works with, show her up again, so she says, “I can’t let Danielle show me up again.” To show someone up means to do something better than someone else, it usually means to make the other person look bad by doing something better than them. It's typically a negative thing to say about a person - “He's trying to show me up” - he's trying to a better job so that I look bad.
Ling says, “At the last meeting, all of the department heads loved” Danielle's “ideas and they’re starting to think she walks on water.” So at the last meeting, all the people who were the bosses of the department - we would call them the department heads; a head of something can be the boss or leader of something - they loved Danielle's ideas and they think that she walks on water. The expression to walk on water means to be perfect - to be very good - to do everything perfectly.
The expression actually comes from a story in the Christian Bible, where Jesus, the leader of the Christian religion, walks on water during a storm when he is out with his fellow believers. And so, the idea of walking on water means to do something that is a miracle, “miracle.” A miracle is something that is extraordinary - that should not happen but does happen. Usually, the idea is that it is because God has created this miracle. So, that is the expression to walk on water; it's used in English to mean to be perfect.
Sam says that he doesn't think it will help Ling to sit around and worry about it. “Nothing will come to you,” meaning you won't think of anything, “if you work yourself up too much.” To work yourself up means to become very worried or anxious about something - to think about something so much that you become very nervous about it. “Don't work yourself up” - don't think about it so much so that you get nervous or anxious.
Ling says to Sam, “You’re right. I’m too wound up to think straight.” The expression to be wound, “wound,” up means to be nervous - to be anxious - to be stressed out, we would say. To be very stressed about something, that is being wound up.
She says, “It’s like my brain is in a fog.” Fog, “fog,” is something we have here a lot in Los Angeles, where the clouds come down to the ground and it's difficult to see in front of you - that's a fog. The expression to be in a fog means to be confused - to be unclear - you can't think straight - you can't see the problem correctly.
Sam says, “Come on. We’ll go take a quick walk. I’m sure that’ll do the trick.” To do the trick, “trick,” means to do what something is supposed to do - to work - to be successful. “If we go for a walk, that will do the trick” - that will help you in your problem.
“If it doesn’t,” he says, “I’ll help you work on your resume.” This is a joke, of course. Your resume is a list of your experience that you use for an interview when you need to get a new job. So he's joking, saying that if Ling doesn't come up with some good ideas, she will lose her job and will need to look for another one.
Ling says, “Gee, thanks,” but she's not serious, she's making a joke herself. She says that she has “known all along,” meaning for a long time, that Sam was after her job. To be after someone's job means to want someone else's job - to try to get another person's job.
Sam says, “Me? After your job?” He's surprised that Ling says this. He's joking too, of course. He says, “I wouldn’t touch your job with a 10-foot pole,” “pole.” This is a expression that means I don't want to be involved with that at all - I don't want to have anything to do with that. We use the expression “I wouldn't touch this with a 10-foot pole.” A pole, “pole,” is like a long, round piece of wood or metal. We are saying here that I don't want to be close to this problem - I don't want to be close to this thing.
So, Sam doesn't want Ling's job. He says that he could not “take the pressure,” “pressure.” Pressure means the very stressful feeling of having to do something - you're anxious or nervous because you have to do all this work. We often use the expression to be under pressure; it's a similar idea where you feel like you have lots of things you have to do and it is very stressful.
Sam says that he prefers “being a lowly employee and giving” Ling “a hard time everyday.” Lowly, “lowly,” means not very important - not in a high position but in a low position in the company.
To give someone a hard time means to make jokes about someone - to make things difficult for someone by making fun of them - by telling jokes about them. That's to give someone a hard time.
Ling says, “Thanks a lot,” again she's trying to be funny here. “Between you and Danielle,” she says, “my days here are numbered.” The expression to have one's days numbered means that you will not be here very long - that you are going to lose your job soon. “His days are numbered” means he will probably be fired - lose his job soon. My days are numbered here at ESL Podcast, I think!
Now let's listen to the dialogue at a normal rate of speech.
[start of story]
Ling: Ugh!
Sam: What’s the matter?
Ling: I’m trying to jot down some ideas for the meeting tomorrow but I’m drawing a blank.
Sam: When I’ve got a block, I usually step away from it for a while and come back to it later. Then I can look at it with a fresh perspective.
Ling: I don’t have time to take a break. I need to come up with something quick or I’ll have to go into that meeting empty-handed. I can’t let Danielle show me up again. At the last meeting, all of the department heads loved her ideas and they’re starting to think she walks on water.
Sam: Well, I don’t think it helps to sit around worrying about it. Nothing will come to you if you work yourself up too much.
Ling: You’re right. I’m too wound up to think straight. It’s like my brain is in a fog.
Sam: Come on. We’ll go take a quick walk. I’m sure that’ll do the trick. If it doesn’t, I’ll help you work on your resume.
Ling: Gee, thanks. I’ve known all along that you’re after my job.
Sam: Me? After your job? I wouldn’t touch your job with a 10-foot pole. I couldn’t take the pressure. I prefer being a lowly employee and giving you a hard time everyday.
Ling: Thanks a lot. Between you and Danielle, my days here are numbered.
Sam: Come on. Let’s go before you get even more depressed!
[end of story]
The script today podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
to jot down – to quickly write down something; to note something quickly
* Let me jot down your phone number before you leave, so I can call you next week.
to draw a blank – to not be able to think of a good idea or the answer to something
* Xiaofeng drew a blank on the test question about World War I, even though he had studied all night.
block – an inability to think of something; not being able to think of something
* Whenever this writer gets a block, she reads some new books to get ideas.
to step away from (something) – to stop what one is doing and to work on something else for a short period of time before returning to the first task
* Evelyn got so frustrated with the project that she had to step away from it and didn’t work on it again until the next day.
fresh perspective – a new and creative way of looking at things
* Everyone likes to work with Igor because he always brings a fresh perspective to the team.
empty-handed – without anything; unprepared
* Normally Maude brings a dessert when she visits friends, but last night, she didn’t have enough time to cook, so she went to the party empty-handed.
to show (someone) up – to do something better than someone else; to make someone else look bad by doing something better
* Jill was very happy that she got 95% on the test, but her roommate showed her up again by getting 100%.
to walk on water – to be perfect or excellent; to do everything well
* Randolph makes delicious cookies, cakes, and breads. It seems like he walks on water in the kitchen!
to work (oneself) up – to become agitated and worried about something; to think about something so much that one becomes very nervous about it
* Sam worked himself up for days before the presentation, and when it was time to actually do the presentation, he was so nervous that he could hardly speak.
wound up – tense; nervous; anxious; stressed out
* If you get wound up from work and school, it might help to talk about it with your friends.
in a fog – confused; unclear; blurry
* The medicine will make you feel like you’re in a fog for a few hours after taking it.
to do the trick – to do what something is supposed to do; to work; to be successful
* If you can’t fall asleep at night, sometimes drinking a glass of warm milk will do the trick.
to be after (one’s) job – to want someone else’s job; to try to get another person’s job
* I think Bert is after my job. He’s always telling my boss that he could do my work better and faster than I can.
(one) wouldn’t touch (something) with a 10-foot pole – doesn’t want to be involved with something at all; doesn’t want to have anything to do with something; wants to stay as far away from something as possible
* Lynn hates the taste of peas. She wouldn’t touch them with a 10-foot pole!
pressure – the stressful feeling of having to do something
* Elliot is under a lot of pressure to pass his medical exams next week.
lowly – not very important; not to have a very high position in an organization
* Many people think that secretaries are lowly employees, but without them, most managers wouldn’t be able to do their jobs.
to give (someone) a hard time – to make jokes and tease someone; to make things difficult for someone; to make fun of someone
* Her brother gave her a hard time about her driving skills when she accidentally hit a tree in the parking lot.
(one’s) days here are numbered – one will not be here for very much longer; one will lose his or her job soon
* Josh has the feeling that his days here are numbered, because the new boss doesn’t seem to like him very much.
Comprehension Questions
1. What is Ling doing when Sam asks her what is the matter?
a) She is drawing blanks on a piece of paper.
b) She is trying to write down good ideas.
c) She is taking a break.
2. Why does Sam suggest going for a walk?
a) Because it will help Ling think of new ideas.
b) Because they need to walk to the meeting.
c) Because Sam needs to learn to walk on water.
Answers at bottom.
What Else Does It Mean?
block
The word “block,” in this podcast, means an inability to think of something: “Sometimes exercise can help to clear your mental block.” A “block” is also a group of buildings that are in a square that is surrounded by streets on all four sides: “Our apartment building is on a block with a small grocery store and a movie theater.” A “block” can also be a cube of any type of material: “The child was using plastic blocks to build a house.” Or, “The small pieces of ice froze into one large block.” As a verb, “to block” means to stop something from moving through something else: “The accident blocked traffic for miles.” Or, “Putting too much toilet paper down the toilet can sometimes block the pipes.”
to show (someone) up
In this podcast, the phrase “to show (someone) up” means to do something better than someone else or to make someone else look bad by doing something better: “Courtney just bought a small apartment, but her brother showed her up by buying a very large four-bedroom house.” A similar phrase, “to show up,” means to attend or to come to an event: “What time did Francis finally show up at the party?” The phrase “to show (someone) the door” means to ask someone to leave a place: “The restaurant owner had to show the couple to the door because they were fighting very loudly and disturbing the other customers.” Finally, the phrase “to show (something) off” means to show people something that one is proud of: “Ivana likes to show off her wealth by wearing expensive clothes and lots of jewelry.”
Culture Note
“Writer’s block” happens whenever someone needs to write something but has difficulty deciding what to write. Many people stare at a “blank page” or a page with nothing on it for hours, trying to decide how to begin. In the United States, teachers and professional writers have many “suggestions” or recommendations for helping people “get over” writer’s block, or to find a way around the problem. Here are a few of those suggestions.
Many teachers and professional writers suggest thinking about what needs to be written and organizing one’s ideas before beginning to write. Another good suggestion is to avoid “perfectionism” or the need to write everything perfectly the first time. Good writing requires many “revisions,” meaning that the text that is written down first is almost always changed later. Also, many people have difficulty writing the first sentence, but it isn’t necessary to begin at the beginning. Try starting somewhere in the middle and finish the “introduction,” or first part, last.
Changing the physical “surroundings” or environment might also help. Try moving your desk to where there are fewer “distractions” or things that take you away from your writing. Turn off the phone and music, or turn on music if that helps you write. Also, going outside for a walk may help you concentrate better.
If you still have writer’s block, try reading some of your favorite writings or books for “inspiration” (ideas) for your own writing. Some people think it’s easier to speak than to write, so they might get over their writer’s block by “recording” their own voice while talking about the topic. Later, they can listen to themselves and write down the main ideas.
Comprehension Answers
1 - b
2 - a