= 0286
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 286: Describing Facial Features.
This is English as a Second Language Podcast number 286. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com, click on the name of this podcast and you can see the script for today’s dialogue. If you want the complete transcript, plus all of the vocabulary words, definitions, cultural notes and more, get a Learning Guide for this podcast. You can download that, also, on our website.
This episode is called “Describing Facial Features.” It’s going to be about a woman who was, unfortunately, robbed. She’s going to try to describe who the person was that stole her money. Let’s get started.
[start of story]
I was mugged while I was walking home last night. This morning, I was at the police station with a sketch artist to see if we could come up with a picture of what the thief looked like.
Sketch artist: Okay, you said that this was a man in his 40s. Can you tell me what shape his face was: thin, round, oval, or square?
Anna: His face was long and thin, I think.
Sketch artist: Were his eyes more round, bulging, or squinty?
Anna: Well, I think they were round, but not too round, and he had bushy eyebrows. He also had a pointed nose, not a hooked one.
Sketch artist: Take at look at this so far. Is this right?
Anna: His nose in the sketch is a little too turned up. It was more straight.
Sketch artist: What about his ears? Were they big or small? And his mouth? Did he have thin or thick lips?
Anna: His ears were average size and they didn’t stick out too much. His lips were more thin than thick.
Sketch artist: We’re almost done. What about his hair? Did he have long or short hair?
Anna: Oh, didn’t I tell you? He’s bald.
Sketch artist: Okay, then. I’m done. What do you think? Is this the guy?
Anna: Wow, you’ve done a great job. Yeah, that’s him. That’s the guy who stole my wallet.
Sketch artist: You know, he looks familiar. I have a feeling I’ve seen him before.
Anna: I hope so. Maybe you can help find him.
Sketch artist: Yeah, now if only I could remember where I’ve seen him before...
[end of story]
Our story begins with Anna saying that she was mugged while she was walking home last night. When she was walking back home, someone came and stole her money. “To be mugged” (mugged) means to be robbed, when someone forces you to give them your wallet or your purse, for example. When someone does this, we call it a “mugging” (mugging).
I’ve been mugged once, back in St. Paul. Many years ago, when I was still in high school, I had a couple of tickets that I was selling for a concert, and a couple of guys – teenagers like me, at the time – walked up to me, said they wanted to buy my tickets, and then they grabbed them from me – they stole them – and they ran away. So, I lost my tickets.
Many people, when they are mugged, however, are hurt by the person who steals their money. Anna was not hurt, but she was mugged. In the morning, she went to the police – to the police station, the place where the police are, the building – and she talked to a sketch artist. A “sketch (sketch) artist” is a person who usually works for the police, who draws the face of someone based on your description. So, you tell the person how the person – in this case, the criminal, the person who took your money – how that person looks. You describe them and they will make a picture; that is a “sketch artist.” A “sketch” is a picture, usually made with pencil.
The sketch artist says to Anna, “Okay, you said that this man was in his 40s. Can you tell me the shape of his face: thin, round, oval, or square?” So the sketch artist starts by asking Anna what the shape of the face was – how did it look. Did it look like a circle? We would say “round.” Did it look very thin? Long and narrow, not wide. Did it look oval? “Oval” is like a circle, but it’s longer, sort of like an egg. Or, someone’s face can be square, meaning the top, the bottom, and the two sides are about the same length; that’s a “square.” Anna says, “His face was long and thin, I think.”
The sketch artist then says, “Were his eyes more round, bulging, or squinty?” You can describe someone’s eyes as being “round.” “Bulging” (bulging) is when the eyes come out of the face a little; they, we would say, “stick out,” they come out of your face in a very round shape. Your eyes could also be “squinty” (squinty), this is when the eyes are “partially,” or partly, closed, so that you only see a small line of the eye. So, we have “round,” “bulging,” and “squinty.” “Squinty” comes from the verb “to squint,” which means to try to look at something that is difficult to see, perhaps because it is far away, or you have some problem with your eye. When you “squint,” you usually close your eyes a little to help you see a little better or more clearly.
Anna says that “Well, I think the eyes were round, but not too round.” She also says that the person who robbed her had bushy eyebrows. “Eyebrows” are the curved line of hair that is above your eye. So, it is on the bottom of your forehead. The adjective “bushy” (bushy) means you have a lot of hair, usually “disorganized,” or messy. So, “bushy eyebrows” would be big eyebrows that have a lot of hair on them. The word “bushy” is not related to any of the presidents of the United States, that’s completely different!
Anna describes the man as having a pointed nose. A “pointed” (pointed), or “pointy,” would be with a sharp end. It is sort of the opposite of “flat.” Someone’s nose is “pointy” if it looks like it comes to a single point, sort of like a pencil comes to a point. “Pointed” has a couple of meanings in English: take a look at our Learning Guide for additional explanations.
Anna says that the man’s nose was not hooked (hooked). If your nose is “hooked,” there’s a curve at the end of it. It bends; it comes down suddenly, or goes up suddenly. It’s sort of the opposite of “straight.” To be hooked is not straight; it bends, it curves. But the robber – the person who mugged her – does not have a hooked nose.
The sketch artist shows Anna what he has drawn. Anna says that the nose in the sketch – the drawing – is a little too turned up. “Turned up” means it goes up – it curves upwards. Again, not straight. We also have an expression, “to turn up your nose at something.” That means to decide that you are too good for something; that whatever it is, is not good enough for you – you turn up your nose. It’s a negative idea; that you think you are too important – too good to do something. In this case, “turned up” just means curving upwards.
The sketch artist asks about the ears and the mouth. He says, “Did he have thin or thick lips?” Your “lips” (lips) are what is around your mouth. They could be thick or thin. Anna says, “His ears were average size and they didn’t stick out too much.” The verb “to stick (stick) out” (two words) means that you could notice them easily because they were bigger or taller, larger perhaps; something that was different than normal – something “sticks out.” Take a look, again, at out Learning Guide for some additional definitions of that verb.
The sketch artist says, well “We’re almost done. What about the hair? Did he have long hair or short hair?” Anna says, “Oh, didn’t I tell you? He’s bald” (bald), meaning he doesn’t have any hair. Hmm, this guy looks just like me!
The sketch artist then says, “Okay, then. I’m done. What do you think? Is this the guy,” the man who robbed you? Anna says yes, “That’s the guy who stole my wallet.” Your “wallet” is usually a small, folded piece of leather or cloth you use to put your money, and your credit cards, and your identification in.
The sketch artist says, “You know, he looks familiar. I have a feeling I’ve seen him before.” “I have a feeling” means I think, but I’m not sure – I believe, I’m pretty sure.
Anna says, “I hope so. Maybe you can find him.”
The sketch artist says, “Yeah, now if only I could remember where I’ve seen him before…” I wonder, too!
Now let’s listen to the dialogue, this time at a normal speed.
[start of story]
I was mugged while I was walking home last night. This morning, I was at the police station with a sketch artist to see if we could come up with a picture of what the thief looked like.
Sketch artist: Okay, you said that this was a man in his 40s. Can you tell me what shape his face was: thin, round, oval, or square?
Anna: His face was long and thin, I think.
Sketch artist: Were his eyes more round, bulging, or squinty?
Anna: Well, I think they were round, but not too round, and he had bushy eyebrows. He also had a pointed nose, not a hooked one.
Sketch artist: Take at look at this so far. Is this right?
Anna: His nose in the sketch is a little too turned up. It was more straight.
Sketch artist: What about his ears? Were they big or small? And his mouth? Did he have thin or thick lips?
Anna: His ears were average size and they didn’t stick out too much. His lips were more thin than thick.
Sketch artist: We’re almost done. What about his hair? Did he have long or short hair?
Anna: Oh, didn’t I tell you? He’s bald.
Sketch artist: Okay, then. I’m done. What do you think? Is this the guy?
Anna: Wow, you’ve done a great job. Yeah, that’s him. That’s the guy who stole my wallet.
Sketch artist: You know, he looks familiar. I have a feeling I’ve seen him before.
Anna: I hope so. Maybe you can help find him.
Sketch artist: Yeah, now if only I could remember where I’ve seen him before...
[end of story]
The script for this podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
to be mugged – to be robbed; to be forced to give another person one’s money
* You’re more likely to be mugged on a lonely, dark street than on a bright street with lots of people walking around.
sketch artist – a person who draws a face, usually of a criminal, based on another person’s description
* Please tell the sketch artist everything you remember so that he can try to draw a picture of the man who stole your money.
thin – long and narrow; not wide
* Damian looks like his mother. He has a thin face with a very high forehead.
round – circular; in the shape of a wheel
* Have you seen how round Kelly’s face is? It’s almost a perfect circle!
oval – an elongated circle; shaped like an egg; similar to a rectangle, but with rounded corners
* Their new swimming pool has an oval shape, like a very large egg.
square – a shape with four equal sides and four 90° corners
* The bedroom is a square, with four walls that are each 20 feet long.
bulging – sticking out in a round shape; pressing against something to make a round shape
* The child drank a lot of water very quickly, so her stomach was bulging.
squinty – with eyes partially closed so that only a small horizontal line of the eye can be seen
* Our eyes are squinty in this photograph because the sun was very bright that day.
bushy – with a lot of hair, usually disordered or messy
* When I get older, I hope I don’t have bushy hair growing out of my ears like my father!
eyebrow – the curved line of short hair above one’s eye, at the bottom of one’s forehead
* Do women pluck (pull out) hairs to change the shape of their eyebrows in your country?
pointed – with a sharp end; not flat
* Be careful with that pencil! It’s pointed, and you almost hit me in the eye with it.
hooked – with a curve at the end; with an end that comes up or down suddenly; not straight
* Some birds have hooked beaks (mouths) that help them open nuts.
turned up – gently curving upwards; not straight
* Jenny’s hair is beautiful when it is turned up at the bottom.
lip – one of the two edges of the opening of one’s mouth, with darker or redder skin; the upper and lower part of the opening outside of the mouth
* Do you bite your lips when you’re nervous?
to stick out – to be easily noticed because something is taller, farther out, or different than the rest of something
* Sadat sticks out among the other students because he’s the tallest boy in his class.
bald – without hair on one’s head
* Javier became bald when he was only 22 years old.
wallet – a folded piece of leather or cloth that is used to hold one’s money, identification, and credit cards
* Most men keep their wallets in their pant pockets, but most women keep them in their purses.
I have a feeling – I think, but I’m not sure; I’m pretty sure; I believe
* I have a feeling that this is going to be a very good year for our business.
Comprehension Questions
1. Why is the sketch artist drawing a face?
a) Because he and Anna are playing a game.
b) Because he wants to make a drawing of the thief.
c) Because he knows what the thief looks like.
2. What kind of eyebrows are “bushy” eyebrows?
a) Very big, hairy eyebrows.
b) Small, straight eyebrows.
c) Dark brown eyebrows.
Answers at bottom.
What Else Does It Mean?
pointed
The word “pointed,” in this podcast, means with a sharp end, or not flat: “Many women like to wear pointed shoes, but Jules thinks they’re too uncomfortable.” Another meaning of “pointed” is a question, statement, or look that shows that one isn’t happy about something: “The mother gave her child a pointed look and he immediately stopped hitting the dog.” As a verb, “to point” means to hold one’s hand and index finger in the direction of something to show other people where something is: “The astronomy teacher pointed at Venus so that her students could find it in the night sky.” The verb “to point” can also mean to hold one’s hand and index finger to show someone where to go: “The librarian pointed to the section of the library with books about U.S. history.”
to stick out
In this podcast, the phrase “to stick out” means to be easily noticed because something is different than the rest of something: “Ron wore a red hat all morning that made him stick out among all the other people.” The phrase “to stick out” can also mean to make something come out or move forward: “The little girl stuck out her tongue at her brother because she was angry with him.” The phrase “to stick around” means to stay in a place: “After class, the students stuck around talking with each other for about 15 minutes.” Finally, the phrase “to stick with (something)” means to continue doing something: “Do you want to stick with the original plan to meet at 8 p.m., or would you prefer to meet earlier?”
Culture Note
When we describe someone’s facial features, we usually begin by talking about their eyes, nose, and mouth. But there are a lot of other facial features that we can describe when talking about what people look like.
For example, to describe noses, sometimes we talk about “nostrils,” which are the two holes in one’s nose that one breathes through. Someone might have very small nostrils, round nostrils, or hairy nostrils.
We can also talk about someone’s “forehead,” which is the top of one’s face, above one’s eyebrows and below one’s hair. Foreheads can be high or low. And many foreheads are “wrinkled,” meaning that there are lines in the skin.
A “chin” is at the bottom of one’s face, below one’s mouth and above one’s neck. If someone has a “jutting chin,” it means that his or her chin sticks out from the rest of the face. Fat people often have “double chins” meaning that there is extra skin under the face and above the neck, so that it looks like the person has two chins.
“Dimples” are small indentations that can appear on one’s “cheeks” (the areas on the sides of one’s face, to the right and left of the nose) or chin. Many children have dimples when they smile, and some adults have dimpled cheeks, too.
The skin covering one’s eye is known as an “eyelid.” If the skin under one’s eye is dark, usually because one hasn’t slept enough, we say that the person “has bags under his/her eyes,” or we say that the person “has dark circles under his/her eyes.”
Comprehension Answers
1 - b
2 - a