= 0299
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 299: An Old Love.
This is English as a Second Language Podcast episode 299. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. You can download a Learning Guide for this episode; you can also take a look at our special premium courses for business and personal English on our ESL Podcast Store.
This episode is called “An Old Love,” someone who was your boyfriend or girlfriend many years ago. It's a dialogue between Juan and Naomi about an old love. Let's get started.
[start of story]
Juan: You’ll never guess who I got an email from yesterday.
Naomi: Who?
Juan: Diana Shultz.
Naomi: Weren’t you two an item back in high school? So, you got an email from an old flame. Very interesting.
Juan: Well, that’s ancient history. We lost touch after we went off to college.
Naomi: What did she say in her email?
Juan: She said she was going to be in town next month and wanted to know if I wanted to get together for dinner.
Naomi: Are you going to go?
Juan: I don’t know. Her email came out of the blue.
Naomi: Aren’t you dying of curiosity? I know I would be. Maybe she still has feelings for you.
Juan: Stop it! It’s just dinner, and I’m sure she just wants to catch up on old times, nothing more.
Naomi: I wouldn’t be so sure. You’ll go, right?
Juan: I might as well. If I make an excuse, she might think I’m trying to avoid her.
Naomi: Good. Go and then tell me all about it afterwards. You know I have no social life, so I live vicariously through you.
Juan: Stop making things up. You date more than anyone I know. Okay, I’m going, so stop pestering me.
Naomi: All right, but I can’t wait to hear all about it!
[end of story]
Our dialogue begins with Juan saying to Naomi, “You’ll never guess who I got an email from yesterday.” “You'll never guess” means it's very difficult for you to think of the answer.
Naomi says, “Who?” And Juan says, “Diana Shultz.” Naomi says, “Weren’t you two an item back in high school?” The expression “an item” has a couple of different meanings. Here, it means a romantic couple – a romantic pair. You could say that “These two people are an item,” it means they are dating each other – they are romantically involved with each other. For example: “Did you hear that Jeff McQuillan and Jennifer Aniston are now an item?” Just an example, of course, Jennifer and I are no longer dating!
Naomi continues, “So, you got an email from an old flame.” An “old flame” is someone that you used to have a romantic relationship with, an ex-boyfriend or an ex-girlfriend. Jennifer Aniston is, for me, an “old flame,” for example.
Juan responds by saying, “that’s ancient history.” “Ancient history,” in this informal context, means something that happened very long ago and is no longer important – is no longer relevant. “Ancient history” usually refers to the history, for example, of the Greeks or the Romans in the western world, but here, when we use it in this way, we're just saying, “That's old news" – that is no longer true; it was a long time ago.
Juan says that he and his old flame, Diana Shultz, lost touch after they went off to college. To “lose touch” is when you no longer communicate with someone; someone you used to talk to, but then after several months or years you stopped talking to each other. That is to “lose touch.” Notice that Juan says that he and his girlfriend “went off to college.” They went to college, but “went off” means they were just starting. They were in high school, they graduated high school, and then they “went off to college” – they began going to college.
Naomi says, “What did she say in her email?” And Juan says that Diana is “going to be in town (in that city where Juan lives) next month,” and wants to know if he (Juan) wants to get together for dinner (to have dinner).
Naomi says, “Are you going to go?” And Juan says, “I don’t know. Her email came out of the blue.” Something that is “out of the blue” means it was unexpected. You didn't realize or think it would happen, and it happens very quickly, very suddenly; it was “out of the blue.” For some additional definitions of this expression take a look at the Learning Guide for this episode.
Naomi says, “Aren’t you dying of curiosity?” To be “dying of curiosity” means you are very anxious to know something; you are very impatient to know something; you really want to know. Some people are “dying of curiosity” about what happened to Harry Potter at the end of the last novel. I won't tell you, of course, because I don't know!
Naomi says are “you dying of curiosity,” meaning "Aren't you very curious, Juan, about what Naomi wants to talk about?" Naomi says, “Maybe she still has feelings for you.” To “have feelings” for someone is to still be romantically interested in that person, to want to start a romantic relationship with them.
Juan then interrupts her and says, “Stop it! It’s just dinner,” meaning they are only going out for dinner, it is nothing more serious than that. He says, “I’m sure she just wants to catch up on old times.” To “catch up on old times” means to talk to someone about things that happened in the past, someone that you haven't talked with for a very long time. So, you see a friend you haven't seen in 10 years, and then you “catch up on old times” – you talk about things that have happened in the last 10 years and so forth.
Naomi says, “I wouldn’t be so sure. You’ll go, right?” meaning I'm not sure if it's just to catch up on old times, Diana might have other interests. Juan says, “I might as well,” meaning I might as well go. When someone says you “might as well,” they mean there's no reason not to do something – there's no objection that you have to doing it. For example: “Even though you don't have a lot of experience, you might as well apply for the job” – there's no reason not to, even though you may not get the job. It won't hurt, “you might as well.”
Juan continues, “If I make an excuse, she might think I’m trying to avoid her.” To “make an excuse” means to give someone a reason for doing something or not doing something. Usually the idea is that what you are saying isn't actually true. “He's just making excuses” would mean he's not telling the truth – he's lying, he's giving reasons that aren't really true. That's how it is often used.
Juan says that Diana might think that he's trying to avoid her. To “avoid” someone means to try to not be near someone – to try to stay away from someone. Naomi says, “Good. Go and then tell me all about it afterwards,” meaning later – after the date is over. “You know I have no social life, so I live vicariously through you.” A “social life” would be participating in activities with other people – spending time with other people who are your friends. To “live vicariously (vicariously) through someone” means to listen to someone talk about his or her life and imagine that those things are happening to you because you don't have an interesting life. Perhaps this is one reason why news about famous people is so interesting to so many people. They “live vicariously through them,” meaning they don't have an interesting life perhaps, so they imagine that the things happening to someone else are also happening to them.
Juan finally says, “Stop making things up,” meaning stop inventing things – stop imagining things. “You date more than anyone I know” – you date more people than anyone I know. “Okay,” Juan says, “I’m going, so stop pestering me.” To “pester” (pester) someone means to bother someone – to annoy someone. To do things that make the other person feel very frustrated or that makes them angry; that's to “pester.” Parents may say that sometimes about their children: “Stop pestering me” – stop bothering me about wanting a new toy or wanting to go to Disneyland.
I'll stop pestering you now, and have us listen to the dialogue at a normal speed.
[start of story]
Juan: You’ll never guess who I got an email from yesterday.
Naomi: Who?
Juan: Diana Shultz.
Naomi: Weren’t you two an item back in high school? So, you got an email from an old flame. Very interesting.
Juan: Well, that’s ancient history. We lost touch after we went off to college.
Naomi: What did she say in her email?
Juan: She said she was going to be in town next month and wanted to know if I wanted to get together for dinner.
Naomi: Are you going to go?
Juan: I don’t know. Her email came out of the blue.
Naomi: Aren’t you dying of curiosity? I know I would be. Maybe she still has feelings for you.
Juan: Stop it! It’s just dinner, and I’m sure she just wants to catch up on old times, nothing more.
Naomi: I wouldn’t be so sure. You’ll go, right?
Juan: I might as well. If I make an excuse, she might think I’m trying to avoid her.
Naomi: Good. Go and then tell me all about it afterwards. You know I have no social life, so I live vicariously through you.
Juan: Stop making things up. You date more than anyone I know. Okay, I’m going, so stop pestering me.
Naomi: All right, but I can’t wait to hear all about it!
[end of story]
The script for this podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2007.
Glossary
an item – a romantic couple; a romantic pair
* When Paul and Emily became an item, all of the other high school students knew about it immediately.
old flame – someone with whom one used to have a romantic relationship; an ex-boyfriend or ex-girlfriend
* Carol is one of Miguel’s old flames, but now they’re just good friends.
ancient history – something that happened long ago and is no longer relevant or important
* Renee used to work as a financial analyst, but now she’s a professional actress and her old job is ancient history.
to lose touch – to no longer communicate with someone; to not talk or write to someone whom one used to be close to
* Veronica lost touch with many of her friends when she moved from Ohio to Alaska.
out of the blue – unexpectedly; suddenly; without being expected or planned
* We had planned to go to Maine for the holidays, but out of the blue, Greg said that he wanted to go to Paris instead.
to be dying of curiosity – to be very anxious to know something; to be filled with curiosity; to be impatient to learn something
* Yolanda is dying of curiosity to know what her husband bought her for her birthday.
to have feelings for (someone) – to be romantically interested in someone; to want to start a romantic relationship with someone
* If you have feelings for Terry, then ask him out on a date!
to catch up on old times – to talk about the past with someone whom you haven’t seen or spoken with in a long time
* Yesterday I met an old friend for lunch and we had fun catching up on old times, since we hadn’t talked in six years.
(one) might as well – there’s no reason not to do something; there’s no reason not to; one has no objection to doing something
* Even though you don’t have very much experience, you might as well apply for the job. The worst that can happen is that you won’t get it.
to make an excuse – to state a reason for doing (or not doing) something, especially when that reason isn’t true
* I need to make an excuse so that I don’t have to go to that party tonight.
to avoid (someone) – to try not to be near someone; to try to ignore someone; to try to stay away from someone
* I think Gerald is avoiding me. I know he saw me at the store, but he didn’t smile or say “hi.”
afterwards – later; then; after something else has happened
* First, they’re going to eat dinner together, and afterwards, they’re going to see a movie.
social life – participation in activities that let one interact with other people; spending time with other people for friendship
* Susan has a busy social life. This weekend, for example, she’s going to two parties and a wedding, and then she’s taking her nieces to the park!
to live vicariously through (someone) – to listen to someone talk about his or her life and imagine that those things are happening to oneself, because one has an uninteresting life
* Sometimes parents try to live vicariously though their children, but the children usually don’t like that very much.
to make things up – to imagine something; to pretend that something is happening
* When Becky was a child, she was always making things up, telling her friends that she was a princess, for example.
to pester (someone) – to bother someone; to annoy someone; to do things that make another person feel frustrated or angry
* Does your little brother pester you a lot?
Comprehension Questions
1. Who is Diana Shultz?
a) A person from a period in ancient history.
b) Juan’s ex-girlfriend from high school.
c) Someone who is moving to town.
2. According to Naomi, why did Diana send the email?
a) Because she’s feeling blue and depressed.
b) Because she’s dying of curiosity.
c) Because she’s romantically interested in Juan.
Answers at bottom.
What Else Does It Mean?
flame
The phrase “old flame,” in this podcast, means an ex-boyfriend or ex-girlfriend: “Have you ever tried to contact your old flames to learn about their lives?” Normally a “flame” is one line of the bright yellow or orange light and heat that comes from a fire: “Can you please lower the flame under that pot on the stove?” Or, “Charlie called the fire department when he saw flames coming from his neighbor’s house.” As a verb, “to flame” means to burn brightly: “The wood was flaming in the fireplace.” The verb “to flame” can also mean to write an insulting or offensive message about another person in an email or an electronic forum, such as a chat room or an online discussion group: “Dana posted a message on her blog saying how much she liked the new movie, but someone flamed her by posting a comment that she was stupid if she liked it.”
out of the blue
In this podcast, the phrase “out of the blue” means unexpectedly or suddenly: “His decision to run in a marathon came out of the blue.” The phrase “to feel blue” means to feel depressed, or to feel very sad, sometimes without any reason: “Nancy felt blue for months after her divorce.” The phrase “once in a blue moon” means very rarely: “I love to eat ice cream, but I eat it only once in a blue moon.” Finally, the phrase “to do something until (one) is blue in the face” means to try to do something for a very long time, but not be successful: “You can try to fly until you’re blue in the face, but it’s impossible and it’s never going to happen.”
Culture Note
“Public records” are types of information that have been “recorded” (officially written down) , by government agencies. Most public records are available to the public. “Access” (the ability to get something) to some public records is free, but to see other public records, you might need to pay a “fee” (an amount of money).
“Common” (typical) public records include “vital records,” such as certificates of birth and death, and “marriage records” about when people were married, and to whom. There are also “criminal records,” which are histories about people’s “crimes,” or the things that they have done that are against the law.
“Driving records” tell us how many times people have received “tickets” (had to pay money for breaking driving laws). “Real estate records” contain information about who buys a house or a piece of land, and how much it costs.
Today, we can use the Internet to access public records more easily than ever before. Many websites help people find public records and then print out copies.
However, many people are worried about “privacy” (the right to not have personal information shared with other people). In general, public records that contain private information are not available online. To access these public records, you will need to call the public agency that is responsible for “maintaining” (keeping) the specific type of public record that you are interested in.
Comprehension Answers
1 - b
2 - c