
= eco 2020-08-15
:toc:

---

== Raising the floor （工资或物价的）最低额，底价  词汇解说

(eco 2020-8-15 / Schools brief / Raising the floor: What harm do minimum wages do?)

What harm *do* minimum wages 最低工资 *do*?

Three decades of research *have led to a rethink*

Aug 15th 2020 |

提高（工资或物价的）最低额，底价 +
最低工资会造成什么危害? +
三十年的研究, 已经引起了人们的反思


[FOR A LONG TIME] `主` economists -- `主` whose median income, *according to* a survey of the American Economic Association (AEA), `系` *is* $104,000 a year -- `谓` *considered* minimum wages *to be harmful*. A survey of AEA members in 1992 *found that* 79% of respondents 回答问题的人；（尤指）调查对象 *agreed that* a minimum wage *increases* unemployment among young and low-skilled workers. In an often fractious(a.)暴躁的；易怒的；动辄烦躁的;捣乱的；表示不满的 field, that *is* about *as* close to a consensus  一致的意见；共识 view *as* can be found. Although many economists *recognised that* low pay *can indeed be* a real problem, they *argued that* no pay was worse.

- 长期以来，根据美国经济协会(AEA)的一项调查，经济学家的平均收入是104,000美元一年，他们认为最低工资是有害的。1992年对AEA成员的一项调查发现，79%的受访者同意, 最低工资会增加年轻和低技能工人的失业率。在一个经常难以相处的领域(指经济学上)，这几乎是可以找到的最接近共识的观点。尽管许多经济学家认识到，低工资确实是一个真正的问题，但他们辩称，没有工资更糟糕。

They *were not the only people* who thought(v.) so. The same argument *was used by* Republican politicians 共和党政客. In 1968, America’s federal minimum wage *stood at its highest level* since first being applied 使用；应用 in 1938. [During the following two decades] it *fell*, in real terms 扣除物价因素；按实质计算, by 44%. Though Jimmy Carter *raised the wage* in each of the four years he was president, *keeping pace with inflation*, Richard Nixon *raised it only twice* in six years and Ronald Reagan *not once* in eight. Some state and local politicians, mostly Democrats, *tried to offset(v.)抵消；弥补；补偿 the fall* by raising(v.) their minimum wages, *creating a patchwork* 拼凑之物;（不同图案杂色布块的）拼缝物；拼布工艺 of different levels. `主` The disparities （尤指因不公正对待引起的）不同，不等，差异，悬殊 (this created) `谓` *allowed detailed empirical 以实验（或经验）为依据的；经验主义的 research* on the policies’ effects, and *provided* the means (*by which* the economists’ consensus *would be undermined* 逐渐削弱（信心、权威等）；使逐步减少效力).

- 他们并不是唯一这样认为的人。共和党政客也使用了同样的论点。1968年，美国联邦最低工资达到1938年首次实施以来的最高水平。在接下来的20年里，按实际价值计算，它下降了44%。尽管吉米·卡特(Jimmy Carter)在担任总统的四年中每年都提高工资，与通胀同步，但理查德·尼克松(Richard Nixon)在六年内只提高了两次，罗纳德·里根在八年中一次也没有提高。一些州和地方政客(主要是民主党人)试图通过提高最低工资, 来抵消通胀的影响，创造了不同水平的最低工资的拼凑状态。这种差异存在, 使得经济学家对最低工资政策的效果来进行详细的实证研究, 成为可能，它也提供了一种方法, 可能会打破经济学家原本的共识(即认为"最低工资会增加年轻和低技能工人的失业率"的观点)。


Not only *did this see* `主` the conventional wisdom 传统观念;大多数人的看法；普遍信念 on minimum wages `谓` *challenged* in America; *it also saw* such policies spread(v.) elsewhere. Britain *introduced* a national minimum wage in 1998, and *has increased it* in recent years. Germany’s *came into effect* 生效；开始实施 in 2015. Around 90% of countries *have some sort of legal wage floor* （工资或物价的）最低额，底价, although enforcement 执行 *practices 实行 vary widely*. Economists now *have* lots of data *with which* to understand(v.) ① how minimum wages *affect(v.) the economy in practice* and, [*in the context of* a promise(n.) by Democratic presidential candidate, Joe Biden, *to raise* America’s federal minimum wage *to* $15], ② *to argue about* how high they can go.

- 这不仅使有关最低工资的传统观念, 在美国受到挑战; 这类最低工资政策, 也在其他地方蔓延开来。英国在1998年引入了"国家最低工资"政策，并在最近几年将其提高。德国于2015年生效最低工资。大约90%的国家都有某种形式的法定最低工资标准，尽管它们的执行方法各不相同。经济学家现在掌握了大量数据，可以用来理解最低工资在实践中, 如何影响经济，以及在民主党总统候选人乔·拜登(Joe Biden)承诺将美国联邦最低工资提高到15美元的背景下，经济学家能讨论最低工资可以提高到多高。

The concern that minimum wages destroy(v.) jobs *comes from* the most basic of economic models: supply and demand. If labour *is made more expensive*, employers *will probably want less of it*. Textbooks *state(v.) that*, *in the absence of* a minimum wage, a worker *is paid* his “marginal product of labour 劳动的边际产量”, which *means* the value of what he produces. *There is no room* to deviate(v.)背离；偏离；违背 from this wage [in either direction]. If an employer *tries to pay a worker less*, a rival firm *will poach 盗用；挖走（人员等） him*. If the government *imposes a minimum wage* that is higher than a worker’s marginal product, the firm *loses money* by employing him. He *is left jobless instead*.

- Marginal product of labor : MPL 劳动的边际产量. 是指其他条件不变时，每增加一单位劳动企业增加的产出量。

- 对于"最低工资会破坏工作机会"的担忧, 主要来自最基本的经济模型:供给和需求。如果劳动力价格上涨，雇主可能会减少劳动力需求。教科书上说，在没有最低工资的情况下，工人得到的报酬是他的“劳动的边际产量”，也就是他所生产的东西的价值。无论在哪个方向，都不存在偏离这一工资水平的余地。如果雇主试图降低工人的工资，竞争对手就会挖走他。如果政府规定的最低工资, 高于工人的边际产量，公司会亏损, 会导致工人反而失业。

Reality is more complex. Firms *do not know* how much each worker *contributes to* their revenues. Few workers *can find a new job [at the drop of a hat* 立即；毫不迟疑]. Yet the basic model *reveals* one important truth: `主` the workers (who *are most vulnerable to losing their job* as a result of the minimum wage) `系` *are* those whose productivity *is low* -- the very people *the policy is designed to help*.

- 现实要复杂得多。公司不知道每个工人为他们的收入贡献了多少。很少有工人能马上找到一份新工作。然而，这个基本模型揭示了一个重要的事实:最容易因最低工资而失去工作的工人，正是那些生产率较低的人——这项政策旨在帮助的, 正是这些人。


More sophisticated theorising(n.)从理论上说明；形成理论；理论化 about labour markets *recognises that* they *are not* perfectly competitive. There is no single wage (*at which* a worker *has* his pick 挑选；选择;选中的人（或物） of employers). As a result, firms *probably pay workers*(n.) less than their marginal revenue product. `主` How much less `谓` *depends on* negotiations and `主` *who does best there* `谓` *depends on* bargaining power. In this framework, the goal of the minimum wage *is [not]* to defy(v.)违抗；反抗；蔑视 market logic *[but]* to stop(v.) firms in a strong negotiating position *from* squeezing their workers.

- theorize : /ˈθiːəraɪz,ˈθɪraɪz/ v. [ VNV that ] *~ (about/on sth)* to suggest facts and ideas to explain sth; to form a theory or theories about sth 从理论上说明；形成理论；理论化

- 更复杂的劳动力市场理论认识到，劳动力市场并不是完全竞争的。没有一种工资水平可以让工人选择雇主。因此，公司付给工人的工资, 可能低于他们的边际产量。少多少,取决于谈判，谁在谈判中做得最好, 取决于讨价还价的能力。在这个框架下，最低工资的目标, 不是要违背市场逻辑，而是要阻止处于强势谈判地位的公司压榨他们的工人。


The upper bound 上界,上限 on the minimum wage *still applies*  使用；应用: firms *will not willingly employ workers [at a loss]*. But below that ceiling, the effect of the minimum wage *is ambiguous* 模棱两可的；含混不清的. It *depends on* a series of questions. *Can* a company *replace* its workers *with machines*? Can it *raise prices* and *make* its customers *pay(v.) for* the minimum wage? Does it *face* competition from foreign firms who *face* laxer 更宽松的;不严格的 rules overseas?

- 最低工资的上限仍然适用:公司不会愿意在亏本的情况下雇佣工人。但在亏本线之下，最低工资的效果就不明确了。这取决于一系列的问题。公司能用机器代替工人吗?它能提高价格，让顾客支付最低工资吗?它是否面临外国公司的竞争，而这些外国公司在海外面临更宽松的监管?

*Consider* a comparison 比较 between factories and restaurants. Logically, *there would be little scope* to increase(v.) manufacturing pay *using* minimum wages, because firms *face* stiff international competition, and jobs *are constantly automated 使自动化 away* （用于动词后）持续地，劲头十足地. By contrast, jobs in restaurants *are hard to automate* and *face(v.) no foreign competition*. `主` Any increase in costs *affecting* the whole sector `谓` *should be passed on to* 转交；（用后）递给，传给 consumers. Job losses 失业  *should be lower* -- especially if *it turns out  原来是；证明是；结果是 that* consumers *are willing to pay higher prices*. So *can* one minimum wage *do justice*(n.)公平；公正 by both sectors?

- away : ad. used after verbs to say that sth is done continuously or with a lot of energy （用于动词后）持续地，劲头十足地
.. *She was still writing away furiously* when the bell went. 铃声响时她还在不停地写着。
.. They *were soon chatting away* like old friends. 他们很快就像老朋友一样聊起天来。

- 考虑一下工厂和餐馆之间的比较。从逻辑上讲，使用最低工资来提高制造业工资的空间很小，因为公司面临着激烈的国际竞争，工作岗位不断被自动化。相比之下，餐馆的工作很难自动化，也不面临外国竞争。任何影响整个行业的成本增加, 都会转嫁到消费者身上。这样失业人数应该更少--特别是如果事实证明消费者愿意支付更高的价格。那么，如果两个行业都使用同一个最低工资水平, 这是公平的吗？


`主` The empirical 以实验（或经验）为依据的；经验主义的 study(n.) which *revitalised* 使有新的活力；使新生 the debate on minimum wages in the 1990s `系` *was* by David Card and Alan Krueger, both then at Princeton University. In 1992 New Jersey *increased its hourly wage floor* from $4.25 to $5.05. Neighbouring Pennsylvania *kept its own at $4.25*. *Thrilled 使非常兴奋；使非常激动 at* the prospect of a naturally occurring 自然发生的 case study 个案研究；专题研究；案例研究, the two economists *gathered information* of employment at fast-food restaurants in both states [before the April *increase* /and *again* several months later]. Fast food *seemed* *to offer* the ideal conditions *for* a study, *as* a homogenous [生物] 同质的；同类的 sector (*employing* unskilled workers).

- empirical : a.  /ɪmˈpɪrɪkl/ => em-, 进入，使。-pir, 尝试，冒险，词源同pirate, expert.字面意思即尝试过的，有经验的。

- 在上世纪90年代，重振"最低工资辩论"的实证研究, 是戴维•卡德(David Card)和艾伦•克鲁格(Alan Krueger)所做的，两人当时都在普林斯顿大学(Princeton University)工作。1992年，新泽西州将最低时薪从4.25美元提高到5.05美元。而邻近的宾夕法尼亚州, 则保持在4.25美元。这两位经济学家对这一自然发生的案例研究的前景, 感到兴奋，他们收集了4月份和几个月后的两州快餐店的就业情况信息。快餐似乎为一项研究提供了理想的条件，作为一个雇用非熟练工人的同质行业。


The increase in the wage floor *did not lead to* jobs *being lost* in New Jersey; `主` employment 就业;雇用 in the restaurants (they *looked at*) `谓` *went up* （价格、数量或水平）上涨，上升. *Nor did* the authors *find* any indication 迹象；象征 that the opening of future restaurants *would be affected*. *Looking at* the growth in the number of McDonald’s restaurants across America, *they saw no tendency* for fewer to open [where minimum wages *were higher*].

- 最低工资标准的提高, 并没有导致新泽西的失业;他们所关注的餐馆的就业率上升了。作者也没有发现任何迹象表明, 未来的餐馆开业会受到影响。他们观察了全美麦当劳餐厅数量的增长，发现在最低工资水平较高的地区，开设麦当劳餐厅的人数, 并没有减少的趋势。


Their book, “Myth 神话;谬见 and Measurement” (1995), *changed a lot of minds*. [By 2000] only 46% of AEA members *were certain that* a minimum wage *increased unemployment* among the young and low-skilled: [*to* the rest 其余者] `主` the textbook view -- that, *faced with* a rise in the cost of employing workers, firms *would use fewer of them* -- `系` *was wrong*. But why? [Over the past 20 years] a growing body of research *has shown that* a key consideration （作计划或决定时）必须考虑的事（或因素、原因） *is* the power (enjoyed by employers).

- 他们的著作《神话与衡量》(1995)改变了很多人的想法。到2000年，只有46%的AEA成员确信, 最低工资增加了年轻人和低技能人群的失业率:对其他人来说，教科书上的观点——面对雇佣工人成本的上升，公司将会减少雇佣工人——是错误的。但是为什么呢?在过去的20年里，越来越多的研究表明，一个关键的考虑因素是:雇主所享有的权力。


This `school of thought` 学派, 思想学派 *argues that* some labour markets *are characterised 以…为特征 by* a market structure *known as* monopsony 买方垄断. [Under a monopolistic 垄断的; 独占的 regime] one dominant supplier *sells to* many buyers, whereas under a monopsonic 单频道的,单声道 regime, one dominant buyer *purchases from many sellers*. Just as a monopolist 垄断者；专卖者；专营者 *can set prices* higher than *would be the case in a competitive market*, a monopsonist 独家垄断的买方 *can set prices artificially 人工地；人为地 lower*.

- monopsony : /məˈnɑːpsəni/ N a situation in which the entire market demand for a product or service consists of only one buyer 买方垄断. 一种产品或服务的整个市场需求, 只有一个买主的情况

- monopsonist : \ məˈnäpsənə̇st \  one who is a single buyer for a product or service of many sellers

- 这一学派认为，有些劳动力市场具有被称为"买方垄断"的特征, 在垄断性领域中, 一个具有支配力的供应商, 向许多买家进行销售; 而在一个单频道的领域, 一个具有影响力的买者, 向许多卖家进行采购。正如垄断者卖家可以将价格定得高于竞争市场中的价格一样，垄断者买家也可以人为地将价格压得更低。


Thus, though *it may sound counterintuitive*(a.) (想法、提议等)违反常理的;违反直觉的 for `a higher wage to lead to more employment`, *it makes sense* if `主` what the legislation 法规；法律 is doing `谓` *is pushing a wage* (*kept artificially low by* monopsony 买方垄断) *back to* where it *would be* in a market (where supply and demand *were matching each other freely*). `主` People (who *may not have bothered* to look for a job at $10 an hour) `谓` *may be drawn into* a job market (*offering* $15 an hour). *Push* the minimum wage *significantly beyond that point*, though, and jobs *will indeed be lost* 当 as companies *find* labour *too expensive to afford*.

- 因此，尽管"提高工资会导致更多就业", 听起来可能有悖常理，但如果法律做的是将被垄断者买方人为压低的支付(从而造成低工资), 回归到供需自由匹配的正常市场的情况下, 人们就不会烦恼于只能找到时薪10美元的工作了, 而会被时薪15美元的工作所吸引. 但当最低工资大幅提高到这一水平以上后，就业机会确实会减少, 因为企业会发现劳动力现在成本太高了.

Once the role of competition in the labour market *is accepted*, the debate on minimum wages *becomes more nuanced 微妙的；具有细微差别的 and more empirical* 以实验（或经验）为依据的；经验主义的. Gathering(v.) data *is not easy*. Researchers *must consider* whether *to track* jobs or workers, and whether *to study* certain groups, such as teenagers or the unskilled, or broader 更广泛的 sectors. And the job market *is affected by more than just minimum-wage rules*. Constructing(v.) reasonable counterfactuals 反事实的; 指在不同条件下有可能发生但违反现存事实的;虚拟的(陈述)  *is hard*.

- nuance :  /ˈnuːˌɑːnst/   N-VAR A nuance is a small difference in sound, feeling, appearance, or meaning. (声音、感觉、外貌或意义等方面的) 细微差别

- counterfactual : /ˌkaʊntərˈfæktʃuəl/
1. ADJ expressing what has not happened but could, would, or might under differing conditions 反事实的; 指在不同条件下有可能发生但违反现存事实的
2. N a conditional statement in which the first clause is a past tense subjunctive statement expressing something contrary to fact, as in 虚拟的(陈述)
.. if she had hurried she would have caught the bus

- 一旦劳动力市场中竞争的角色被接受，关于最低工资的辩论就变得更加微妙和更具经验性。收集数据并非易事。研究人员必须考虑是否去追踪工作或工人，以及是否研究某些群体，如青少年或非技术人员，或更广泛的行业。而且能影响就业市场的因素, 不仅仅是"最低工资"这一个。构建合理的反事实是很困难的。


Specific north-west

Consider(v.) an example from Seattle 西雅图（美国一港市）. The city *has been* at the forefront of the “*fight(v.) for* $15” campaign that *led to* Mr Biden’s pledge 保证；诺言；誓约, and its rapid wage rises(n.) *have made it* an attractive laboratory for economic studies, despite the fact, some *grumble*(v.)咕哝；嘟囔；发牢骚, that it is unrepresentative 不典型的；无代表性的. A paper by Ekaterina Jardim and others at the University of Washington, *published* in 2017, *found that* minimum-wage *increases in the city* in 2015 and 2016 *led to* employers *reducing hours [in low-paid sectors]*. The average low-paid worker *earned more per hour* but, because they *worked fewer hours*, their monthly earnings *dropped by $74* -- the equivalent of five hours’ pay.

- 考虑一个来自西雅图的例子。这座城市一直处于“争取15美元时薪”运动的最前沿，正是这一运动促成了拜登的承诺。该市工资的快速上涨, 使其成为了一个颇具吸引力的经济研究实验室，尽管有些人抱怨说，这一事实并不具有代表性。华盛顿大学(University of Washington)的叶卡捷琳娜•雅迪姆(Ekaterina Jardim)等人, 2017年发表的一篇论文发现，该市2015年和2016年最低工资的提高，导致低收入行业的雇主, 将员工的工作时间减少。虽然使得低收入工人的平均时薪更高了，但由于工作时间减少，他们的月收入实际减少了74美元——相当于5小时的工资。

That paper *used* aggregate(a.)总数的；总计的 data on hours and earnings(n.) by sectors. In a paper published in 2018, the same authors *used* administrative 管理的；行政的 data *to track* individual workers *rather than* looking at averages. This time *they found that* low-paid workers *saw* their weekly earnings *increase by $8-12 a week*. The majority of that gain, though, *was taken by* low earners(n.)挣钱者；挣工资者 with above-median experience levels(n.) and some of it *from* workers (*making up 凑足;补齐 lost hours* worked(v.) in Seattle) *with* additional hours (elsewhere in Washington state).

- 这篇论文使用了按行业划分的工时和收入的汇总数据。在2018年发表的一篇论文中，这些作者使用行政数据来跟踪单个员工，而不是只查看平均水平。这一次，他们发现, 低薪工人每周的收入增加了8-12美元。然而，大部分增长是由经验水平高于中位数的低收入者获得的，其中一些来自西雅图的工人是通过补足损失的工作时间来获得更多收入的; 还有那些来自华盛顿州的人, 是通过增加作时间(加班)来获得更多收入的。

In 2019 a review commissioned by the British government of more than 50 recent empirical studies into wage floors found the effect on employment to be generally muted, even with relatively ambitious increases. Yet some studies did find higher impacts. Arindrajit Dube, the author of the review, warned that the evidence base is still developing. It is, for instance, too soon to opine on South Korea’s 25% increase in its minimum wage between 2016 and 2018.

The effects of a wage floor can also be felt outside low-pay sectors. A preliminary study in 2019 of the impact of Germany’s minimum wage found it led to more reallocation of workers from smaller, lower-paying firms to larger, higher-paying ones. The same year an article in the Quarterly Journal of Economics found that the impact of minimum-wage laws on average earnings was amplified by small but important spillover effects higher up the earnings ladder. Employers tend to want to maintain some sort of wage differential for staff with more responsibility. So if the minimum wage boosts the pay of fast-food workers, then restaurants may also need to raise the pay of fast-food supervisors.

Who pays for the minimum wage? In theory a higher cost base could be passed on to consumers through higher prices, or absorbed by employers through lower profit margins. In reality the answer varies by market. In competitive sectors, such as fast food, research has found that a 10% increase in the wage floor pushes up burger prices by just 0.9%. In 2019 a study of supermarkets in Seattle found no impact on grocery prices from big increases.

Economists no longer think higher minimum wages are always bad. But that is not the same as saying they are always good. In 2018 a paper by Isaac Sorkin and others cautioned policymakers to take a longer-term view, rather than worry about short-term unemployment. Its authors found that if firms perceived a higher wage floor to be permanent and unlikely to be eroded by inflation, it could encourage them to automate more and decrease employment growth in the future. The idea that a minimum wage can sometimes lead to higher rather than lower employment does not mean it always will. When pushing up the floor, policymakers need to ensure they do not hit the ceiling.

---

== Raising the floor

What harm do minimum wages do?

Three decades of research have led to a rethink

Aug 15th 2020 |


FOR A LONG TIME economists—whose median income, according to a survey of the American Economic Association (AEA), is $104,000 a year—considered minimum wages to be harmful. A survey of AEA members in 1992 found that 79% of respondents agreed that a minimum wage increases unemployment among young and low-skilled workers. In an often fractious field, that is about as close to a consensus view as can be found. Although many economists recognised that low pay can indeed be a real problem, they argued that no pay was worse.

They were not the only people who thought so. The same argument was used by Republican politicians. In 1968, America’s federal minimum wage stood at its highest level since first being applied in 1938. During the following two decades it fell, in real terms, by 44%. Though Jimmy Carter raised the wage in each of the four years he was president, keeping pace with inflation, Richard Nixon raised it only twice in six years and Ronald Reagan not once in eight. Some state and local politicians, mostly Democrats, tried to offset the fall by raising their minimum wages, creating a patchwork of different levels. The disparities this created allowed detailed empirical research on the policies’ effects, and provided the means by which the economists’ consensus would be undermined.

Not only did this see the conventional wisdom on minimum wages challenged in America; it also saw such policies spread elsewhere. Britain introduced a national minimum wage in 1998, and has increased it in recent years. Germany’s came into effect in 2015. Around 90% of countries have some sort of legal wage floor, although enforcement practices vary widely. Economists now have lots of data with which to understand how minimum wages affect the economy in practice and, in the context of a promise by Democratic presidential candidate, Joe Biden, to raise America’s federal minimum wage to $15, to argue about how high they can go.

The concern that minimum wages destroy jobs comes from the most basic of economic models: supply and demand. If labour is made more expensive, employers will probably want less of it. Textbooks state that, in the absence of a minimum wage, a worker is paid his “marginal product of labour”, which means the value of what he produces. There is no room to deviate from this wage in either direction. If an employer tries to pay a worker less, a rival firm will poach him. If the government imposes a minimum wage that is higher than a worker’s marginal product, the firm loses money by employing him. He is left jobless instead.

Reality is more complex. Firms do not know how much each worker contributes to their revenues. Few workers can find a new job at the drop of a hat. Yet the basic model reveals one important truth: the workers who are most vulnerable to losing their job as a result of the minimum wage are those whose productivity is low—the very people the policy is designed to help.

More sophisticated theorising about labour markets recognises that they are not perfectly competitive. There is no single wage at which a worker has his pick of employers. As a result, firms probably pay workers less than their marginal revenue product. How much less depends on negotiations and who does best there depends on bargaining power. In this framework, the goal of the minimum wage is not to defy market logic but to stop firms in a strong negotiating position from squeezing their workers.

The upper bound on the minimum wage still applies: firms will not willingly employ workers at a loss. But below that ceiling, the effect of the minimum wage is ambiguous. It depends on a series of questions. Can a company replace its workers with machines? Can it raise prices and make its customers pay for the minimum wage? Does it face competition from foreign firms who face laxer rules overseas?

Consider a comparison between factories and restaurants. Logically, there would be little scope to increase manufacturing pay using minimum wages, because firms face stiff international competition, and jobs are constantly automated away. By contrast, jobs in restaurants are hard to automate and face no foreign competition. Any increase in costs affecting the whole sector should be passed on to consumers. Job losses should be lower—especially if it turns out that consumers are willing to pay higher prices. So can one minimum wage do justice by both sectors?

The empirical study which revitalised the debate on minimum wages in the 1990s was by David Card and Alan Krueger, both then at Princeton University. In 1992 New Jersey increased its hourly wage floor from $4.25 to $5.05. Neighbouring Pennsylvania kept its own at $4.25. Thrilled at the prospect of a naturally occurring case study, the two economists gathered information of employment at fast-food restaurants in both states before the April increase and again several months later. Fast food seemed to offer the ideal conditions for a study, as a homogenous sector employing unskilled workers.

The increase in the wage floor did not lead to jobs being lost in New Jersey; employment in the restaurants they looked at went up. Nor did the authors find any indication that the opening of future restaurants would be affected. Looking at the growth in the number of McDonald’s restaurants across America, they saw no tendency for fewer to open where minimum wages were higher.

Their book, “Myth and Measurement” (1995), changed a lot of minds. By 2000 only 46% of AEA members were certain that a minimum wage increased unemployment among the young and low-skilled: to the rest the textbook view—that, faced with a rise in the cost of employing workers, firms would use fewer of them—was wrong. But why? Over the past 20 years a growing body of research has shown that a key consideration is the power enjoyed by employers.



This school of thought argues that some labour markets are characterised by a market structure known as monopsony. Under a monopolistic regime one dominant supplier sells to many buyers, whereas under a monopsonic regime, one dominant buyer purchases from many sellers. Just as a monopolist can set prices higher than would be the case in a competitive market, a monopsonist can set prices artificially lower.

Thus, though it may sound counterintuitive for a higher wage to lead to more employment, it makes sense if what the legislation is doing is pushing a wage kept artificially low by monopsony back to where it would be in a market where supply and demand were matching each other freely. People who may not have bothered to look for a job at $10 an hour may be drawn into a job market offering $15 an hour. Push the minimum wage significantly beyond that point, though, and jobs will indeed be lost as companies find labour too expensive to afford.

Once the role of competition in the labour market is accepted, the debate on minimum wages becomes more nuanced and more empirical. Gathering data is not easy. Researchers must consider whether to track jobs or workers, and whether to study certain groups, such as teenagers or the unskilled, or broader sectors. And the job market is affected by more than just minimum-wage rules. Constructing reasonable counterfactuals is hard.

Specific north-west

Consider an example from Seattle. The city has been at the forefront of the “fight for $15” campaign that led to Mr Biden’s pledge, and its rapid wage rises have made it an attractive laboratory for economic studies, despite the fact, some grumble, that it is unrepresentative. A paper by Ekaterina Jardim and others at the University of Washington, published in 2017, found that minimum-wage increases in the city in 2015 and 2016 led to employers reducing hours in low-paid sectors. The average low-paid worker earned more per hour but, because they worked fewer hours, their monthly earnings dropped by $74—the equivalent of five hours’ pay.

That paper used aggregate data on hours and earnings by sectors. In a paper published in 2018, the same authors used administrative data to track individual workers rather than looking at averages. This time they found that low-paid workers saw their weekly earnings increase by $8-12 a week. The majority of that gain, though, was taken by low earners with above-median experience levels and some of it from workers making up lost hours worked in Seattle with additional hours elsewhere in Washington state.

In 2019 a review commissioned by the British government of more than 50 recent empirical studies into wage floors found the effect on employment to be generally muted, even with relatively ambitious increases. Yet some studies did find higher impacts. Arindrajit Dube, the author of the review, warned that the evidence base is still developing. It is, for instance, too soon to opine on South Korea’s 25% increase in its minimum wage between 2016 and 2018.

The effects of a wage floor can also be felt outside low-pay sectors. A preliminary study in 2019 of the impact of Germany’s minimum wage found it led to more reallocation of workers from smaller, lower-paying firms to larger, higher-paying ones. The same year an article in the Quarterly Journal of Economics found that the impact of minimum-wage laws on average earnings was amplified by small but important spillover effects higher up the earnings ladder. Employers tend to want to maintain some sort of wage differential for staff with more responsibility. So if the minimum wage boosts the pay of fast-food workers, then restaurants may also need to raise the pay of fast-food supervisors.

Who pays for the minimum wage? In theory a higher cost base could be passed on to consumers through higher prices, or absorbed by employers through lower profit margins. In reality the answer varies by market. In competitive sectors, such as fast food, research has found that a 10% increase in the wage floor pushes up burger prices by just 0.9%. In 2019 a study of supermarkets in Seattle found no impact on grocery prices from big increases.

Economists no longer think higher minimum wages are always bad. But that is not the same as saying they are always good. In 2018 a paper by Isaac Sorkin and others cautioned policymakers to take a longer-term view, rather than worry about short-term unemployment. Its authors found that if firms perceived a higher wage floor to be permanent and unlikely to be eroded by inflation, it could encourage them to automate more and decrease employment growth in the future. The idea that a minimum wage can sometimes lead to higher rather than lower employment does not mean it always will. When pushing up the floor, policymakers need to ensure they do not hit the ceiling.



2019年，英国政府委托进行的一项研究发现，尽管最低工资增幅相对较大，但它对就业的影响总体上是微弱的。然而，一些研究确实发现了更高的影响。该综述的作者Arindrajit Dube警告说，证据基础仍在发展中。例如，现在就对韩国在2016年至2018年将最低工资提高了25%发表意见还为时过早。
最低工资标准的影响也可以在低薪行业之外感受到。2019年对德国最低工资的影响进行的一项初步研究发现，最低工资导致工人更多地从收入较低的小型企业转移到收入较高的大型企业。同一年，《经济学季刊》(Quarterly Journal of Economics)的一篇文章发现，最低工资法对平均收入的影响被收入阶梯上较高阶层的小而重要的溢出效应放大了。雇主们往往希望为有更多责任的员工维持某种工资差别。因此，如果最低工资提高了快餐业工人的工资，那么餐厅可能也需要提高快餐业主管的工资。
谁支付最低工资?理论上，更高的成本基础可以通过更高的价格转嫁给消费者，或者通过降低利润率被雇主吸收。事实上，答案因市场而异。在竞争激烈的行业，比如快餐，研究发现最低工资10%的增长只会使汉堡价格上涨0.9%。2019年对西雅图超市的一项研究发现，食品价格大幅上涨对食品价格没有影响。
经济学家不再认为提高最低工资总是坏事。但这并不等于说它们总是好的。2018年，艾萨克•索尔金(Isaac Sorkin)等人发表的一篇论文告诫政策制定者要从更长远的角度看问题，而不是担心短期失业。该报告的作者发现，如果企业认为更高的最低工资是永久性的，不太可能被通货膨胀所侵蚀，这可能会鼓励它们更多地实现自动化，从而减少未来的就业增长。最低工资有时会导致更高的就业率而不是更低的就业率，这一观点并不意味着它总是会这样。在推高“地板”时，政策制定者需要确保它们不会触及“天花板”。




