= 002 European Exploration in the Americas (APUSH Period 1.3)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义


What's up, beautiful people? Today I'm taking a look at European exploration 探索；勘探 in the Americas.

Now, you are probably thinking this video is going to begin with the dude Christopher Columbus, but fun fact: Columbus was not the first European to reach the Americas. Viking explorers actually reached the Americas about 500 years before Columbus did in 1492. They even established 建立；设立 settlements 定居点.

In spite of 尽管 this fact, by the 15th century, Europeans did not know about the Americas. That stuff in the pink or orange is what Europeans knew about the world in 1492.

Before I go any further, when I was in school, I was always confused about what was meant when somebody said "15th century" or "20th century." So, you are not as big of a [dummy] as I was in my younger years. When we say "15th century," we mean the 1400s, and the "20th century" means the 1900s. Now, I know most of you probably already knew that, but the 1996 version of this dude didn't.

Advances 进步；进展 in navigation 航海；航行 technology made these early explorations possible. For example, the sextant 六分仪 was created, which was used to determine 确定；查明 latitude 纬度 and longitude 经度, and the caravel 卡拉维尔船（15世纪西班牙、葡萄牙的轻快帆船）ship was a small ship invented by the Portuguese. The ship was small enough that it was capable of 有能力做… traveling long distances for exploration of places such as Africa and eventually the Americas.

What is important about these and other items is that this new technology and innovations 创新；革新 made European exploration possible. We also need to understand why this European exploration takes place. Why not just be cool knowing about this stuff in the orange color?

If you need a simple way to remember the primary 主要的；首要的 motives 动机；原因 for European colonization 殖民；开拓殖民地 of the Americas, just think of the three G's: gold, glory, and God. Gold represents 代表；象征 the economic 经济的 motives. The big motive was the desire to seek new markets and the wealth that could be gained from these markets. They're trying to make some money. I believe the kiddos would say, "Europe trying to get that bread."

Another motivation 动机；推动因素 behind this age of exploration was trying to get access to 接近；进入 new trade routes 贸易路线. Attempting to trade with Asia back in the 14th and 15th century meant you had to deal with all sorts of middlemen 中间商 along the way. Much of the areas along the way to Asia were controlled by Muslims, and that ain't gonna go over so well with the largely Christian European nations.

By the end of the 15th century, Portugal and Spain sponsored 赞助；资助 expeditions 远征；探险 that would explore and colonize the coast of West Africa and eventually the Americas. They're looking for wealth, they're looking for trade routes, and they're also hoping to increase their nation's political and economic power.

So, in addition, economic and military 军事的 competition 竞争 between different European nations was another factor 因素；原因 for this age of exploration. As various powerful monarchies 君主制国家 consolidated 巩固；加强 power, they sought to compete with their European rivals 竞争对手.

As you can see on the map, Christians slowly took control over 控制；掌管 the Iberian Peninsula, and this and other events would lead to another cause of European exploration: the desire to spread Christianity.

Portugal gets a jump start on 开始做；启动 overseas 海外的；国外的 expansion 扩张；扩展. Prince Henry the Navigator began by trying to find a new route to Asia. In spite of Portugal's early exploration and success, Spain was the first European country to reach the Americas.

We all know in 1492, Christopher Columbus reaches what is today the Bahamas. Now, Columbus thought he had made it to Asia, thought he had discovered a new trade route to Asia. He's wrong. And in spite of what many people think, homeboy isn't even the first white guy to discover the Western Hemisphere 西半球.

And since I took Algebra 2 three times in high school, you know you can trust the math you see right here.

Nevertheless 然而；不过, the search for new sources of wealth will bring more Spanish expeditions and eventually lead to the establishment 建立；设立 of sugar plantations 种植园 throughout the Caribbean and conquistadors （16世纪的）西班牙征服者 such as Cortez and Pizarro conquering 征服；攻占 native people to obtain 获得；得到 wealth in the form of gold and silver.

As more explorers made the trek 长途跋涉 to the Western Hemisphere, the territory 领土；版图 of Spain increased rapidly. New sources of wealth were acquired 获得；取得, and more people were brought under the Spanish flag and would eventually serve as potential 潜在的；可能的 Catholic 天主教的 converts 皈依者；改信者.

In the next video, we are going to take a look at the impact 影响；作用 of the arrival of Columbus and other European explorers as we examine 考察；调查 the Columbian Exchange, Spanish exploration, and conquest 征服；控制. Until then, thank you so much for watching. Have a beautiful day. Peace!

'''


== 中文翻译

大家好，漂亮的人们！今天我将探讨欧洲在美洲的探险。

现在，你可能认为这个视频将从克里斯托弗·哥伦布这个人开始，但有趣的是：哥伦布并不是第一个到达美洲的欧洲人。维京探险家实际上在哥伦布于 1492 年到达美洲大约 500 年前就到达了美洲。他们甚至建立了定居点。

尽管如此，到了 15 世纪，欧洲人并不知道美洲的存在。粉红色或橙色区域显示的是 1492 年欧洲人所了解的世界。

在我进一步讲解之前，我在上学时总是对“15 世纪”或“20 世纪”的含义感到困惑。所以，你并不像我年轻时那么[笨蛋]。当我们说“15 世纪”时，我们指的是 1400 年代，“20 世纪”指的是 1900 年代。我知道你们大多数人可能已经知道了，但 1996 年的这位老兄并不知道。

航海技术的进步使得早期的这些探险成为可能。例如，六分仪被发明出来，用于确定纬度和经度，而卡拉维尔帆船是葡萄牙人发明的一种小型船只。这种船只体积小巧，能够进行长距离航行，探索非洲以及最终的美洲等地。

关于这些和其他物品，重要的是这些新技术和创新使得欧洲的探险成为可能。我们也需要理解为什么会发生这种欧洲的探险。为什么不满足于了解橙色区域的这些东西呢？

如果你需要一个简单的方法来记住欧洲殖民美洲的主要动机，只需记住“3G”：黄金（Gold）、荣耀（Glory）和上帝（God）。黄金代表经济动机。主要的动机是寻求新市场和从这些市场中获得的财富的渴望。他们试图赚钱。我相信孩子们会说：“欧洲想搞到钱。”

这次探险时代背后的另一个动机是试图获得新的贸易路线。在 14 和 15 世纪试图与亚洲进行贸易意味着你必须一路与各种中间商打交道。通往亚洲的许多地区都由穆斯林控制，这对于主要是基督教的欧洲国家来说是行不通的。

到 15 世纪末，葡萄牙和西班牙资助了探险活动，这些活动将探索并殖民西非海岸，并最终到达美洲。他们寻找财富，寻找贸易路线，并且还希望增加他们国家的政治和经济实力。

因此，此外，欧洲不同国家之间的经济和军事竞争也是这次探险时代的一个因素。随着各个强大的君主制巩固权力，他们寻求与他们的欧洲竞争对手竞争。

正如你在地图上看到的，基督徒逐渐控制了伊比利亚半岛，这和其他事件将导致欧洲探险的另一个原因：传播基督教的愿望。

葡萄牙在海外扩张方面取得了先机。航海家亨利王子首先试图寻找一条通往亚洲的新路线。尽管葡萄牙早期进行了探索并取得了成功，但西班牙是第一个到达美洲的欧洲国家。

我们都知道，1492 年，克里斯托弗·哥伦布到达了今天的巴哈马群岛。现在，哥伦布认为他已经到达了亚洲，认为他发现了一条通往亚洲的新贸易路线。他错了。尽管许多人认为如此，但这位老兄甚至不是第一个发现西半球的白人。

既然我在高中代数 2 考了三次，你就知道你可以相信你在这里看到的数学。

然而，对新财富来源的寻找将带来更多的西班牙探险，并最终导致在整个加勒比地区建立糖料种植园，以及科尔特斯和皮萨罗等征服者征服当地居民以获取黄金和白银形式的财富。

随着越来越多的探险家前往西半球，西班牙的领土迅速扩大。获得了新的财富来源，更多的人被置于西班牙的统治之下，并最终将成为潜在的天主教皈依者。

在下一个视频中，我们将考察哥伦布和其他欧洲探险家的到来所产生的影响，届时我们将探讨哥伦布大交换、西班牙的探险和征服。在那之前，非常感谢您的观看。祝您拥有美好的一天。再见！


'''


== pure

What's up, beautiful people? Today I'm taking a look at European exploration in the Americas.

Now, you are probably thinking this video is going to begin with the dude Christopher Columbus, but fun fact: Columbus was not the first European to reach the Americas. Viking explorers actually reached the Americas about 500 years before Columbus did in 1492. They even established settlements.

In spite of this fact, by the 15th century, Europeans did not know about the Americas. That stuff in the pink or orange is what Europeans knew about the world in 1492.

Before I go any further, when I was in school, I was always confused about what was meant when somebody said "15th century" or "20th century." So, you are not as big of a [dummy] as I was in my younger years. When we say "15th century," we mean the 1400s, and the "20th century" means the 1900s. Now, I know most of you probably already knew that, but the 1996 version of this dude didn't.

Advances in navigation technology made these early explorations possible. For example, the sextant was created, which was used to determine latitude and longitude, and the caravel ship was a small ship invented by the Portuguese. The ship was small enough that it was capable of traveling long distances for exploration of places such as Africa and eventually the Americas.

What is important about these and other items is that this new technology and innovations made European exploration possible. We also need to understand why this European exploration takes place. Why not just be cool knowing about this stuff in the orange color?

If you need a simple way to remember the primary motives for European colonization of the Americas, just think of the three G's: gold, glory, and God. Gold represents the economic motives. The big motive was the desire to seek new markets and the wealth that could be gained from these markets. They're trying to make some money. I believe the kiddos would say, "Europe trying to get that bread."

Another motivation behind this age of exploration was trying to get access to new trade routes. Attempting to trade with Asia back in the 14th and 15th century meant you had to deal with all sorts of middlemen along the way. Much of the areas along the way to Asia were controlled by Muslims, and that ain't gonna go over so well with the largely Christian European nations.

By the end of the 15th century, Portugal and Spain sponsored expeditions that would explore and colonize the coast of West Africa and eventually the Americas. They're looking for wealth, they're looking for trade routes, and they're also hoping to increase their nation's political and economic power.

So, in addition, economic and military competition between different European nations was another factor for this age of exploration. As various powerful monarchies consolidated power, they sought to compete with their European rivals.

As you can see on the map, Christians slowly took control over the Iberian Peninsula, and this and other events would lead to another cause of European exploration: the desire to spread Christianity.

Portugal gets a jump start on overseas expansion. Prince Henry the Navigator began by trying to find a new route to Asia. In spite of Portugal's early exploration and success, Spain was the first European country to reach the Americas.

We all know in 1492, Christopher Columbus reaches what is today the Bahamas. Now, Columbus thought he had made it to Asia, thought he had discovered a new trade route to Asia. He's wrong. And in spite of what many people think, homeboy isn't even the first white guy to discover the Western Hemisphere.

And since I took Algebra 2 three times in high school, you know you can trust the math you see right here.

Nevertheless, the search for new sources of wealth will bring more Spanish expeditions and eventually lead to the establishment of sugar plantations throughout the Caribbean and conquistadors such as Cortez and Pizarro conquering native people to obtain wealth in the form of gold and silver.

As more explorers made the trek to the Western Hemisphere, the territory of Spain increased rapidly. New sources of wealth were acquired, and more people were brought under the Spanish flag and would eventually serve as potential Catholic converts.

In the next video, we are going to take a look at the impact of the arrival of Columbus and other European explorers as we examine the Columbian Exchange, Spanish exploration, and conquest. Until then, thank you so much for watching. Have a beautiful day. Peace!

'''
