= 008 TransAtlantic Trade Topic 2.4 (APUSH Period 2)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义


What's up, beautiful people? Today we're taking a look at transatlantic trade 跨大西洋贸易. What are the impacts of all the exploration, colonization and Columbian exchanging we've been talking about thus far? It is the development of an Atlantic economy.

The term transatlantic trade can be kind of scary, but all it means is trade across the Atlantic Ocean — or as some might say, "across the pond." During the period of colonization we have been studying, that is trade that is conducted between Europe, the Americas and Africa. As a result of this trade, an Atlantic economy developed in which not only goods like tobacco, fur and sugar were exchanged between Europe, Africa and the Americas, but also — sadly — people, largely enslaved Africans.

We often refer to this exchange of goods and people between Europe, Africa and the Americas as the triangular trade 三角贸易, but the reality is these trade routes took a variety of patterns, and they end up looking like a triangle that would be drawn by my two-year-old daughter.

One example of the triangular trade can be seen as enslaved people were forcibly 强行地；强迫地 brought from Africa to the Western Hemisphere. Ships left from Europe to Africa, and those goods from Europe — things like textiles 纺织品, rum 朗姆酒 and manufactured goods — were used to trade for slaves that would be transported to the Western Hemisphere. The journey in between Africa and the Americas was known as the Middle Passage 中途航程（指从非洲将奴隶运往美洲的跨大西洋航程）, and crossing the Atlantic Ocean was horrific 极其可怕的 as ships were packed to capacity 满负荷 as they made the nearly two-month long voyage 航行；航海 to the New World.

While we don't have clear numbers, it is estimated that around 20% of those individuals forced to make this journey died even before arriving. Crappy fact of the day: even after ratification 批准；签署 of the Constitution, the importation 进口；引进 of slaves would continue for another 20 years, all the way up until 1808. Slavery, of course, would last a lot longer than that.

From the colonies went raw materials 原材料 that were not readily available in Europe. Items like sugar, fur, tobacco, rice and other raw materials were all items highly valued in Europe and transported from the Western Hemisphere to Europe.

Thinking about what is happening here — both the good and the horrible — in the 17th and 19th century, trade was taken on a global scale that it had never experienced before. Today we often talk about globalization 全球化 and the changes and challenges it brings to different communities. This process we're learning about here in the 17th and 18th centuries is a step towards that global economy.

All of the colonial powers — whether Spain, France or England — sought to incorporate 包含；吸收 their colonies into the mercantilist system 重商主义体系. The economic theory behind the establishment and development of the colonies was known as mercantilism 重商主义. The idea behind a mercantilist system was to maintain a favorable balance of trade 贸易顺差. You want to export more goods than you import, and in the process of doing so, you increase the share of your country's gold and silver.

Another reason for the colonies was to provide the mother country — for instance, Britain — with raw materials. Basically, mama country gotta eat. In addition, the idea behind mercantilism was also that the colonies would be markets for manufactured goods from Europe.

This process is not going to happen on its own, and as a result, the British government increasingly attempted to incorporate its North American colonies into a coherent 连贯的；一致的, hierarchical 等级制度的 and imperial 帝国的 structure in order to pursue mercantilist economic aims. To do this, laws such as the Navigation Acts 航海条例 were passed. The Navigation Acts did things like require trade from the 13 colonies to be conducted on British ships. In addition, certain goods could only be sent to British ports so they could be taxed, or could only be traded to Britain.

As a result, the Navigation Acts guaranteed England would have access to raw materials from the colonies, and the colonies would serve as a market for English manufactured products. The purpose of these laws and other mercantile 商业的；贸易的 laws were to ensure the colonies were going to continue to be profitable for the mother country. Remember, mama country gots to eat.

Another factor contributing to these mercantile laws was also to protect these trade networks from competing European powers. Britain does not want France or Spain messing with their colonies.

As a result of all this, developing port cities such as Boston and Charleston became very profitable, and a merging class of colonists emerged. However, this system was not exactly without flaws 缺点；缺陷. For one, the North American colonies were reliant on 依赖 imported manufactured goods from England. They're not really manufacturing goods in the colonies themselves. And you all know the famous saying: mo money, mo problems. Some colonists sought to trade with other European powers and found ways to avoid compliance with 遵守；服从 the mercantilist policies.

Luckily for the colonies, it was not until 1763 that the British would really seek to enforce 执行；实施 the laws on the colonists. 1763 is the time when the period known as salutary neglect 有益的忽视（指18世纪英国对其殖民地采取的宽松政策）comes to an end after the French and Indian War, in which England is in debt and they want the colonies to help pay for the empire. But we'll handle that on another day.

In our next video, I will take a look at interactions between American Indians and Europeans. Until next time, thank you so much for watching this Joe's Productions video. Have a beautiful day. Peace!

'''


== 中文翻译

大家好，漂亮的人们！今天我们来探讨跨大西洋贸易。到目前为止我们讨论过的所有探险、殖民和哥伦布大交换带来了什么影响？那就是大西洋经济的发展。

“跨大西洋贸易”这个词听起来可能有点吓人，但它指的仅仅是跨越大西洋的贸易——或者有些人可能会说，“跨过池塘”。在我们研究的殖民时期，这是在欧洲、美洲和非洲之间进行的贸易。由于这种贸易，一种大西洋经济发展起来，不仅烟草、毛皮和糖等商品在欧洲、非洲和美洲之间交换，而且——可悲的是——人口，主要是被奴役的非洲人也被交换。

我们经常将欧洲、非洲和美洲之间商品和人口的这种交换称为三角贸易，但事实是，这些贸易路线呈现出各种各样的模式，最终看起来就像我两岁的女儿画出的三角形。

三角贸易的一个例子是被奴役的人们被迫从非洲运往西半球。船只从欧洲驶往非洲，而来自欧洲的商品——如纺织品、朗姆酒和制成品——被用来换取将被运往西半球的奴隶。非洲和美洲之间的航程被称为“中间航程”，跨越大西洋的航行非常可怕，因为船只挤满了人，他们进行了近两个月的漫长航行前往新世界。

虽然我们没有确切的数字，但据估计，大约 20% 的被迫进行这次航行的人甚至在抵达之前就死亡了。今天令人不快的事实：即使在宪法批准后，奴隶的进口仍将持续 20 年，一直到 1808 年。当然，奴隶制持续的时间要长得多。

从殖民地运往欧洲的是欧洲不易获得的原材料。糖、毛皮、烟草、大米和其他原材料都是欧洲高度重视并从西半球运往欧洲的商品。

思考一下这里发生的事情——好的和坏的——在 17 和 19 世纪，贸易达到了前所未有的全球规模。今天我们经常谈论全球化及其给不同社区带来的变化和挑战。我们在这里学习的 17 和 18 世纪的这个过程是迈向全球经济的一步。

所有的殖民强国——无论是西班牙、法国还是英国——都试图将它们的殖民地纳入重商主义体系。殖民地的建立和发展背后的经济理论被称为重商主义。重商主义体系背后的思想是维持有利的贸易平衡。你希望出口的商品多于进口的商品，并且在这个过程中，增加你国家黄金和白银的份额。

殖民地的另一个原因是为宗主国——例如英国——提供原材料。基本上，宗主国需要资源。此外，重商主义背后的思想也是殖民地将成为欧洲制成品的市场。

这个过程不会自行发生，因此，英国政府越来越试图将其北美殖民地纳入一个连贯的、等级森严的帝国结构，以追求重商主义的经济目标。为此，通过了《航海法》等法律。《航海法》规定，例如，13 个殖民地的贸易必须由英国船只进行。此外，某些商品只能运往英国港口以便征税，或者只能与英国进行贸易。

因此，《航海法》保证了英国能够获得来自殖民地的原材料，而殖民地将成为英国制成品的市场。这些法律和其他重商主义法律的目的是确保殖民地将继续为宗主国带来利润。记住，宗主国需要资源。

促成这些重商主义法律的另一个因素是为了保护这些贸易网络免受竞争的欧洲强国的侵害。英国不希望法国或西班牙干涉他们的殖民地。

由于这一切，像波士顿和查尔斯顿这样发展中的港口城市变得非常有利可图，并且出现了一个新兴的殖民者阶级。然而，这个系统并非完全没有缺陷。首先，北美殖民地依赖于从英国进口的制成品。它们本身并没有真正制造商品。你们都知道那句名言：钱越多，问题越多。一些殖民者试图与其他欧洲强国进行贸易，并找到了避免遵守重商主义政策的方法。

幸运的是，直到 1763 年，英国才真正开始对殖民者强制执行这些法律。1763 年是七年战争（在北美被称为法国和印第安人战争）结束后，被称为“有益的忽视”时期结束的时间，英国负债累累，他们希望殖民地帮助支付帝国的开支。但我们将在另一天处理这个问题。

在我的下一个视频中，我将探讨美洲印第安人和欧洲人之间的互动。下次再见，非常感谢您观看乔氏制作的视频。祝您拥有美好的一天。再见！

'''


== pure

What's up, beautiful people? Today we're taking a look at transatlantic trade. What are the impacts of all the exploration, colonization and Columbian exchanging we've been talking about thus far? It is the development of an Atlantic economy.

The term transatlantic trade can be kind of scary, but all it means is trade across the Atlantic Ocean -- or as some might say, "across the pond." During the period of colonization we have been studying, that is trade that is conducted between Europe, the Americas and Africa. As a result of this trade, an Atlantic economy developed in which not only goods like tobacco, fur and sugar were exchanged between Europe, Africa and the Americas, but also -- sadly -- people, largely enslaved Africans.

We often refer to this exchange of goods and people between Europe, Africa and the Americas as the triangular trade, but the reality is these trade routes took a variety of patterns, and they end up looking like a triangle that would be drawn by my two-year-old daughter.

One example of the triangular trade can be seen as enslaved people were forcibly brought from Africa to the Western Hemisphere. Ships left from Europe to Africa, and those goods from Europe -- things like textiles, rum and manufactured goods -- were used to trade for slaves that would be transported to the Western Hemisphere. The journey in between Africa and the Americas was known as the Middle Passage, and crossing the Atlantic Ocean was horrific as ships were packed to capacity as they made the nearly two-month long voyage to the New World.

While we don't have clear numbers, it is estimated that around 20% of those individuals forced to make this journey died even before arriving. Crappy fact of the day: even after ratification of the Constitution, the importation of slaves would continue for another 20 years, all the way up until 1808. Slavery, of course, would last a lot longer than that.

From the colonies went raw materials that were not readily available in Europe. Items like sugar, fur, tobacco, rice and other raw materials were all items highly valued in Europe and transported from the Western Hemisphere to Europe.

Thinking about what is happening here -- both the good and the horrible -- in the 17th and 19th century, trade was taken on a global scale that it had never experienced before. Today we often talk about globalization and the changes and challenges it brings to different communities. This process we're learning about here in the 17th and 18th centuries is a step towards that global economy.

All of the colonial powers -- whether Spain, France or England -- sought to incorporate their colonies into the mercantilist system. The economic theory behind the establishment and development of the colonies was known as mercantilism. The idea behind a mercantilist system was to maintain a favorable balance of trade. You want to export more goods than you import, and in the process of doing so, you increase the share of your country's gold and silver.

Another reason for the colonies was to provide the mother country -- for instance, Britain -- with raw materials. Basically, mama country gotta eat. In addition, the idea behind mercantilism was also that the colonies would be markets for manufactured goods from Europe.

This process is not going to happen on its own, and as a result, the British government increasingly attempted to incorporate its North American colonies into a coherent, hierarchical and imperial structure in order to pursue mercantilist economic aims. To do this, laws such as the Navigation Acts were passed. The Navigation Acts did things like require trade from the 13 colonies to be conducted on British ships. In addition, certain goods could only be sent to British ports so they could be taxed, or could only be traded to Britain.

As a result, the Navigation Acts guaranteed England would have access to raw materials from the colonies, and the colonies would serve as a market for English manufactured products. The purpose of these laws and other mercantile laws were to ensure the colonies were going to continue to be profitable for the mother country. Remember, mama country gots to eat.

Another factor contributing to these mercantile laws was also to protect these trade networks from competing European powers. Britain does not want France or Spain messing with their colonies.

As a result of all this, developing port cities such as Boston and Charleston became very profitable, and a merging class of colonists emerged. However, this system was not exactly without flaws. For one, the North American colonies were reliant on imported manufactured goods from England. They're not really manufacturing goods in the colonies themselves. And you all know the famous saying: mo money, mo problems. Some colonists sought to trade with other European powers and found ways to avoid compliance with the mercantilist policies.

Luckily for the colonies, it was not until 1763 that the British would really seek to enforce the laws on the colonists. 1763 is the time when the period known as salutary neglect comes to an end after the French and Indian War, in which England is in debt and they want the colonies to help pay for the empire. But we'll handle that on another day.

In our next video, I will take a look at interactions between American Indians and Europeans. Until next time, thank you so much for watching this Joe's Productions video. Have a beautiful day. Peace!

'''
