= 018 The Influence of Revolutionary Ideals (APUSH 3.6)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义

What's up, beautiful people? Welcome to Joe's Productions. In this video, I'm going to quickly explain the influence of revolutionary 革命的 ideals 理想；理念.

First thing to note is the impact of the revolution will be felt both domestically 国内地 and there will be a global impact to the American Revolution. One thing that happened as a result of the American Revolution was an increased awareness of inequalities 不平等 in society. In particular, people will increasingly question the colonial elite 殖民地精英 and the power they had.

All this talk about natural rights 自然权利，consent of the governed 被统治者的同意，and individual rights made various individuals and groups question things beyond just the relationship between the colonies and Britain. For instance, following the American Revolution, there was a movement to abolish 废除 slavery -- at least in states outside the North. In many cases, the call to end slavery in northern states was inspired by the ideals of the American Revolution.

As you can see from this map, various states in the North began to gradually 逐渐地 abolish slavery. In the North, by 1800, slavery was pretty much gone from most northern states. In contrast, the invention of the cotton gin and southern reliance on cash crops 经济作物 and slave labor will mean that slavery will expand in the South. I wonder if this is going to be a problem -- foreshadowing 预示.

What is interesting to look at is the fact that an estimated 20,000 African-American soldiers fought for the British during the American Revolution. For these individuals, they saw liberty 自由 and independence on the side of the British, not the Patriot cause. One reason was Dunmore's Proclamation 邓莫尔公告 issued in 1775.

In 1775, British royal governor of Virginia John Murray, fourth Earl of Dunmore, promised freedom to enslaved people and indentured servants 契约仆人 who ran away and fought for the British. Many African-Americans fought for the British thinking it would be their best shot at freedom. But sadly, these promises would not be kept once the British lost the war.

In spite of the fact that more African-American soldiers would fight for the British side during the American Revolution, between five to eight thousand African-American soldiers fought for the Patriot cause as well. And while the ideas and arguments found in the Declaration of Independence 独立宣言 were not intended to be meant for many groups in American society, sadly, groups and individuals such as Frederick Douglass would use the ideals and arguments found in documents such as the Declaration of Independence in their struggle at advancing opportunities and rights in American society.

Another way the American Revolution impacted the new nation was by increasing calls for greater political democracy 政治民主 in the new state and national government. Each former colony had to create a new state constitution 宪法. Some state legislatures made it easier to vote -- for instance, in Pennsylvania, property requirements 财产要求 were eliminated for white male voters. In states such as Pennsylvania, not all states would do this, and many states would keep property requirements for voting even for the white dudes.

You can see in this graphic, many states would not abolish property requirements for voting until the 1820s and 1830s. But this democratization 民主化 will begin following the American Revolution as more and more white male citizens -- with or without property -- are able to vote. One thing that did happen in all states were states eliminated titles of nobility 贵族头衔. There would be no aristocrats 贵族 or nobility in the new republic. And freedom of religion 宗教自由 was a part of most, if not all, of the new state constitutions.

Remember, the Great Awakening dramatically increased the number of religious denominations 宗教教派，so no one religion was given priority over the others in the new republic. Not to mention, many state governments included limits to power, checks and balances 制衡，separation of powers 三权分立 -- all these things that you'll learn about in your government class.

The lives of women were also impacted by the American Revolution. You might recall women participated in various ways both before and during the American Revolution. Groups like the Daughters of Liberty 自由之女 were essential in supporting the non-importation agreements 不进口协议. These economic boycotts 抵制 of British goods were a powerful tool of colonial protest, and women were vital to their success.

During the war, women often assumed control of the home front 后方. Women ran the farm, the home, and the businesses. And women also played the role of helping supply the Continental Army. Women served as spies, camp followers 随军人员，bandaged wounds, and there were even a few women who dressed up like dudes and fought.

Enlightenment ideals and the appeals of women for expanded roles in the new nation also influenced life in post-revolution America. Women heard these calls for liberty, independence, and denouncements of tyranny 谴责暴政 and applied them to their own situation. Following the war, the ideal of republican motherhood 共和母亲身份 gained popularity.

Republican motherhood was the idea that women should teach republican values within the family -- well, at least to their sons, since they will be the ones who will eventually be able to vote in the new republic. The idea was that women, in their role as mothers, would teach their sons to be good citizens who were civic-minded 有公民意识的.

Now this may seem rather insignificant -- what, a woman's only purpose is to be a mother? But this idea of republican motherhood meant that women did have an elevated 提高的；高尚的 role in American political culture. At the very least, women needed access to education 教育 so that they can be better equipped to educate their children.

Quick side note: I think this painting might feature one of the first mullet haircuts in human history. In 1848, during the Seneca Falls Convention 塞尼卡福尔斯会议，women would use the rhetoric 修辞 of the American revolution to condemn the unlimited powers many husbands had over their wives and called for full equality for women -- not just the republican motherhood stuff.

Women reformers asked the very logical question: if kings and parliament shouldn't have unlimited power, why the heck should men and husbands? The fact that this meeting had to be held in 1848 demonstrates that the lives of women were not radically altered by the American Revolution. But there were changes in the lives of women nonetheless 尽管如此.

And as mentioned, it was not just in America that the revolution will have an impact. Both England and America had Georges -- while that's not important, what was amazing to many was the fact that the colonists did not create Europe 2.0. What was established after the American Revolution was a republic 共和国 -- not another monarchy.

Countries such as France, Haiti, and various other spots in Latin America were inspired by the ideals set forth in the Declaration of Independence and the colonial cause during the revolution. In many of these places, there would be independence movements or revolutions that will take place following 1783.

We will see the French Revolution 法国大革命 in 1789 using many of the same Enlightenment ideas to justify the overthrow of the monarch King Louis XVI. And the Declaration of the Rights of Man and of the Citizen 人权宣言 was inspired by Enlightenment thought and the statements found in the Declaration of Independence. Thomas Jefferson himself even helped with some of this document that helped state the values of the French Revolution -- things like inalienable rights 不可剥夺的权利，consent to be governed, all those things the cool kids were talking about.

The Haitian Revolution 海地革命 that began in 1791 would also be partially inspired by the American Revolution. You might remember when the French got kicked out of North America, they did still retain some colonies in the Western Hemisphere. Haiti was a French colony in which the majority of the people were enslaved. And in 1791, a revolt 起义 erupted. Toussaint L'Ouverture became a leader of this anti-colonial and anti-slave revolt. And in Haiti -- that little spot in the red -- would be the only slave uprising that would lead to the creation of a country that not only abolished slavery but would be run by non-white and formerly enslaved individuals.

Decolonization movements 非殖民化运动 around the world will utilize the language of the American Revolution and particularly the Declaration of Independence to justify their own independence movements. Throughout the early 19th century, various Latin American countries would declare their independence as well. Simón Bolívar was inspired by Enlightenment ideas and the American Revolution in his fight against Spanish control over various Central and South American countries.

And in our next video, I will take a look at our first national government -- the Articles of Confederation 邦联条例. Until next time, thank you so much for watching Joe's Productions. Have a beautiful day. Peace!


'''


== 中文翻译

大家好，漂亮的人们！欢迎来到乔氏制作。在这个视频中，我将快速解释一下革命理想的影响。

首先需要注意的是，革命的影响将在国内和全球范围内感受到。美国革命的一个结果是社会不平等意识的增强。特别是，人们将越来越质疑殖民地精英及其拥有的权力。

所有关于自然权利、被统治者的同意和个人权利的讨论，使得各种个人和群体开始质疑殖民地与英国之间关系以外的事情。例如，在美国革命之后，出现了一场废除奴隶制的运动——至少在北方各州之外。在许多情况下，北方各州呼吁结束奴隶制是受到美国革命理想的启发。

正如你从这张地图上看到的，北方各州开始逐步废除奴隶制。到 1800 年，奴隶制在大多数北方州几乎消失了。相比之下，轧棉机的发明以及南方对经济作物和奴隶劳动的依赖，意味着奴隶制将在南方扩张。我想知道这是否会成为一个问题——伏笔。

有趣的是，据估计，大约有 2 万名非裔美国士兵在美国革命期间为英国作战。对这些人来说，他们认为自由和独立站在英国一边，而不是爱国者一边。其中一个原因是 1775 年发布的邓莫尔宣言。

1775 年，英国弗吉尼亚皇家总督约翰·默里（第四代邓莫尔伯爵）承诺，逃跑并为英国作战的被奴役者和契约仆人将获得自由。许多非裔美国人为英国作战，认为这将是他们获得自由的最佳机会。但可悲的是，一旦英国输掉战争，这些承诺就不会兑现。

尽管在美国革命期间，为英国一方作战的非裔美国士兵人数更多，但也有五到八千名非裔美国士兵为爱国者事业而战。虽然《独立宣言》中的思想和论点并非旨在适用于美国社会的许多群体，但可悲的是，像弗雷德里克·道格拉斯这样的群体和个人将在他们争取在美国社会获得更多机会和权利的斗争中，利用《独立宣言》等文献中的理想和论点。这些开国文献的措辞将在整个美国历史上被使用。

美国革命影响新国家的另一种方式是，新州和国家政府中要求更大政治民主的呼声日益高涨。每个前殖民地都必须制定新的州宪法。一些州议会使得投票更加容易——例如，在宾夕法尼亚州，白人男性选民的财产要求被取消了。在像宾夕法尼亚州这样的州，并非所有州都会这样做，许多州即使对于白人男性也会保留财产要求。

你可以在这张图表中看到，许多州直到 1820 年代和 1830 年代才废除投票的财产要求。但这种民主化将在美国革命后开始，因为越来越多的拥有或没有财产的白人男性公民都能够投票。所有州都发生的一件事是，各州都废除了贵族头衔。在新共和国中将不会有贵族。宗教自由是大多数（如果不是全部）新州宪法的一部分。

记住，大觉醒运动极大地增加了宗教教派的数量，因此在新共和国中，没有任何一种宗教享有优先地位。更不用说，许多州政府都限制权力、实行制衡和三权分立——所有这些你将在政府课上学到的东西。

妇女的生活也受到美国革命的影响。你可能还记得，妇女在美国革命之前和期间以各种方式参与其中。“自由之女”等组织对于支持非进口协议至关重要。这些对英国商品的经济抵制是殖民地抗议的有力工具，妇女对它们的成功至关重要。

战争期间，妇女经常承担起家庭前线的控制权。妇女经营农场、家庭和企业。妇女还扮演着帮助大陆军供应物资的角色。妇女担任间谍、随军家属、包扎伤口，甚至还有一些妇女打扮成男人参战。

启蒙理想和妇女在新国家中争取更大作用的呼吁也影响了革命后美国的生活。“自由、独立和谴责暴政”的呼声被妇女们听到，她们将其应用于自身处境。战后，“共和母亲”的理想开始流行。

“共和母亲”的思想认为，妇女应该在家庭中教授共和价值观——好吧，至少是对她们的儿子，因为他们最终将能够在新的共和国中投票。这个想法是，妇女作为母亲，将教导她们的儿子成为有公民意识的好公民。

现在这似乎微不足道——什么，女人的唯一目的是当母亲？但“共和母亲”的思想意味着妇女在美国政治文化中确实拥有更高的地位。至少，妇女需要接受教育，以便她们能够更好地教育自己的孩子。

快速旁注：我认为这幅画可能描绘了人类历史上最早的鲻鱼发型之一。1848 年，在塞内卡瀑布会议期间，妇女们将利用美国革命的措辞谴责许多丈夫对其妻子拥有的无限权力，并呼吁妇女享有完全平等——而不仅仅是“共和母亲”那一套。

妇女改革者提出了一个非常合乎逻辑的问题：如果国王和议会不应该拥有无限的权力，那么男人和丈夫为什么应该拥有无限的权力呢？这次会议不得不于 1848 年举行这一事实表明，美国革命并没有从根本上改变妇女的生活。但妇女的生活确实发生了变化。

正如前面提到的，革命的影响不仅限于美国。英国和美国都有乔治国王——虽然这并不重要，但令许多人惊奇的是，殖民者并没有创造出“欧洲 2.0”。美国革命后建立的是一个共和国——而不是另一个君主制。

法国、海地以及拉丁美洲的许多其他地方都受到《独立宣言》和革命期间殖民事业所阐述的理想的启发。在许多这些地方，1783 年之后都将发生独立运动或革命。

我们将看到 1789 年的法国大革命，它使用了许多相同的启蒙思想来为推翻国王路易十六辩护。《人权和公民权宣言》受到了启蒙思想和《独立宣言》中声明的启发。托马斯·杰斐逊本人甚至参与了这份帮助阐述法国大革命价值观的文件——比如不可剥夺的权利、被统治者的同意，所有那些酷孩子们都在谈论的事情。

始于 1791 年的海地革命也在一定程度上受到了美国革命的启发。你可能还记得，当法国人被赶出北美洲时，他们仍然在西半球保留了一些殖民地。海地是法国的殖民地，那里的大多数人都是被奴役的。1791 年，一场起义爆发了。杜桑·卢维杜尔成为这场反殖民主义和反奴隶制起义的领导人。在海地——地图上那个红色的点——将是唯一一次导致一个不仅废除了奴隶制，而且由非白人和以前被奴役者管理的国家诞生的奴隶起义。

世界各地的非殖民化运动将利用美国革命的语言，特别是《独立宣言》的语言来为他们自己的独立运动辩护。在 19 世纪早期，拉丁美洲的各个国家也将宣布独立。西蒙·玻利瓦尔在他的反对西班牙控制中美洲和南美洲各国的斗争中，受到了启蒙思想和美国革命的启发。

在我们的下一个视频中，我将探讨我们的第一个国家政府——邦联条例。下次再见，非常感谢您观看乔氏制作。祝您拥有美好的一天。再见！

'''


== pure


What's up, beautiful people? Welcome to Joe's Productions. In this video, I'm going to quickly explain the influence of revolutionary ideals.

First thing to note is the impact of the revolution will be felt both domestically and there will be a global impact to the American Revolution. One thing that happened as a result of the American Revolution was an increased awareness of inequalities in society. In particular, people will increasingly question the colonial elite and the power they had.

All this talk about natural rights, consent of the governed, and individual rights made various individuals and groups question things beyond just the relationship between the colonies and Britain. For instance, following the American Revolution, there was a movement to abolish slavery -- at least in states outside the North. In many cases, the call to end slavery in northern states was inspired by the ideals of the American Revolution.

As you can see from this map, various states in the North began to gradually abolish slavery. In the North, by 1800, slavery was pretty much gone from most northern states. In contrast, the invention of the cotton gin and southern reliance on cash crops and slave labor will mean that slavery will expand in the South. I wonder if this is going to be a problem -- foreshadowing.

What is interesting to look at is the fact that an estimated 20,000 African-American soldiers fought for the British during the American Revolution. For these individuals, they saw liberty and independence on the side of the British, not the Patriot cause. One reason was Dunmore's Proclamation issued in 1775.

In 1775, British royal governor of Virginia John Murray, fourth Earl of Dunmore, promised freedom to enslaved people and indentured servants who ran away and fought for the British. Many African-Americans fought for the British thinking it would be their best shot at freedom. But sadly, these promises would not be kept once the British lost the war.

In spite of the fact that more African-American soldiers would fight for the British side during the American Revolution, between five to eight thousand African-American soldiers fought for the Patriot cause as well. And while the ideas and arguments found in the Declaration of Independence were not intended to be meant for many groups in American society, sadly, groups and individuals such as Frederick Douglass would use the ideals and arguments found in documents such as the Declaration of Independence in their struggle at advancing opportunities and rights in American society.

Another way the American Revolution impacted the new nation was by increasing calls for greater political democracy in the new state and national government. Each former colony had to create a new state constitution. Some state legislatures made it easier to vote -- for instance, in Pennsylvania, property requirements were eliminated for white male voters. In states such as Pennsylvania, not all states would do this, and many states would keep property requirements for voting even for the white dudes.

You can see in this graphic, many states would not abolish property requirements for voting until the 1820s and 1830s. But this democratization will begin following the American Revolution as more and more white male citizens -- with or without property -- are able to vote. One thing that did happen in all states were states eliminated titles of nobility. There would be no aristocrats or nobility in the new republic. And freedom of religion was a part of most, if not all, of the new state constitutions.

Remember, the Great Awakening dramatically increased the number of religious denominations, so no one religion was given priority over the others in the new republic. Not to mention, many state governments included limits to power, checks and balances, separation of powers -- all these things that you'll learn about in your government class.

The lives of women were also impacted by the American Revolution. You might recall women participated in various ways both before and during the American Revolution. Groups like the Daughters of Liberty were essential in supporting the non-importation agreements. These economic boycotts of British goods were a powerful tool of colonial protest, and women were vital to their success.

During the war, women often assumed control of the home front. Women ran the farm, the home, and the businesses. And women also played the role of helping supply the Continental Army. Women served as spies, camp followers, bandaged wounds, and there were even a few women who dressed up like dudes and fought.

Enlightenment ideals and the appeals of women for expanded roles in the new nation also influenced life in post-revolution America. Women heard these calls for liberty, independence, and denouncements of tyranny and applied them to their own situation. Following the war, the ideal of republican motherhood gained popularity.

Republican motherhood was the idea that women should teach republican values within the family -- well, at least to their sons, since they will be the ones who will eventually be able to vote in the new republic. The idea was that women, in their role as mothers, would teach their sons to be good citizens who were civic-minded.

Now this may seem rather insignificant -- what, a woman's only purpose is to be a mother? But this idea of republican motherhood meant that women did have an elevated role in American political culture. At the very least, women needed access to education so that they can be better equipped to educate their children.

Quick side note: I think this painting might feature one of the first mullet haircuts in human history. In 1848, during the Seneca Falls Convention, women would use the rhetoric of the American revolution to condemn the unlimited powers many husbands had over their wives and called for full equality for women -- not just the republican motherhood stuff.

Women reformers asked the very logical question: if kings and parliament shouldn't have unlimited power, why the heck should men and husbands? The fact that this meeting had to be held in 1848 demonstrates that the lives of women were not radically altered by the American Revolution. But there were changes in the lives of women nonetheless.

And as mentioned, it was not just in America that the revolution will have an impact. Both England and America had Georges -- while that's not important, what was amazing to many was the fact that the colonists did not create Europe 2.0. What was established after the American Revolution was a republic -- not another monarchy.

Countries such as France, Haiti, and various other spots in Latin America were inspired by the ideals set forth in the Declaration of Independence and the colonial cause during the revolution. In many of these places, there would be independence movements or revolutions that will take place following 1783.

We will see the French Revolution in 1789 using many of the same Enlightenment ideas to justify the overthrow of the monarch King Louis XVI. And the Declaration of the Rights of Man and of the Citizen was inspired by Enlightenment thought and the statements found in the Declaration of Independence. Thomas Jefferson himself even helped with some of this document that helped state the values of the French Revolution -- things like inalienable rights, consent to be governed, all those things the cool kids were talking about.

The Haitian Revolution that began in 1791 would also be partially inspired by the American Revolution. You might remember when the French got kicked out of North America, they did still retain some colonies in the Western Hemisphere. Haiti was a French colony in which the majority of the people were enslaved. And in 1791, a revolt erupted. Toussaint L'Ouverture became a leader of this anti-colonial and anti-slave revolt. And in Haiti -- that little spot in the red -- would be the only slave uprising that would lead to the creation of a country that not only abolished slavery but would be run by non-white and formerly enslaved individuals.

Decolonization movements around the world will utilize the language of the American Revolution and particularly the Declaration of Independence to justify their own independence movements. Throughout the early 19th century, various Latin American countries would declare their independence as well. Simón Bolívar was inspired by Enlightenment ideas and the American Revolution in his fight against Spanish control over various Central and South American countries.

And in our next video, I will take a look at our first national government -- the Articles of Confederation. Until next time, thank you so much for watching Joe's Productions. Have a beautiful day. Peace!

'''
