
= 005 独立战争对美国各人民的影响
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css


'''

== (解说) 独立战争对美国各人民的影响

The Revolution brought myriad consequences to the American social fabric. +
There was no REIGN OF TERROR as in the French Revolution. +
There was no replacement of the ruling class by workers' groups as in revolutionary Russia.

How then could the American Revolution be described as radical? Nearly every aspect of American life was somehow touched by the REVOLUTIONARY SPIRIT. +
From slavery to women's rights, from religious life to voting, American attitudes would be forever changed.

[.my2]
革命给美国社会结构带来了无数后果。没有像法国大革命那样的恐怖统治。没有像革命的俄罗斯那样，工人团体取代了统治阶级。那么美国革命怎么能被描述为激进呢？美国生活的几乎每个方面都或多或少地受到了革命精神的影响。从奴隶制到妇女权利，从宗教生活到投票，美国人的态度将永远改变。


Some changes would be felt immediately. +
Slavery would not be abolished for another hundred years, but the Revolution saw the dawn of an organized abolitionist movement. +
English traditions such as land inheritance laws were swept away almost immediately. +
The Anglican Church in America could no longer survive. +
After all, the official head of the Church of England was the British monarch. +
States experimented with republican ideas when drafting their own constitutions during the war. +
All these major changes would be felt by Americans before the dawn of the nineteenth century.

[.my2]
一些变化会立即感受到。奴隶制再过一百年才被废除，但革命带来了有组织的废奴运动的曙光。土地继承法等英国传统几乎立刻就被扫除了。美国圣公会再也无法生存。毕竟，英国国教的正式领袖是英国君主。战争期间，各国在起草自己的宪法时尝试了共和思想。所有这些重大变化在十九世纪初之前就已经被美国人感受到了。

The American Revolution produced a new outlook among its people that would have ramifications long into the future. +
Groups excluded from immediate equality such as slaves and women would draw their later inspirations from revolutionary sentiments. +
Americans began to feel that their fight for liberty was a global fight. +
Future democracies would model their governments on ours. +
There are few events that would shake the world order like the success of the American patriotic cause.

[.my2]
美国革命在其人民中产生了一种新的观点，这种观点将在很长一段时间内产生影响。奴隶和妇女等被排除在直接平等之外的群体后来会从革命情绪中汲取灵感。美国人开始觉得他们争取自由的斗争是一场全球性的斗争。未来的民主国家将会以我们的政府为榜样。很少有事件能像美国爱国事业的成功那样撼动世界秩序。

Life, liberty and the pursuit of happiness simply did not seem consistent with the practice of chattel slavery. +
How could a group of people feel so passionate about these unalienable rights, yet maintain the brutal practice of human bondage? Somehow slavery would manage to survive the revolutionary era, but great changes were brought to this PECULIAR INSTITUTION nevertheless.

[.my2]
生命、自由和对幸福的追求似乎与动产奴隶制的做法完全不一致。一群人怎么可能对这些不可剥夺的权利如此热衷，却又继续残酷地奴役人类呢？不知何故，奴隶制在革命时代得以幸存，但这个特殊的制度仍然发生了巨大的变化。

Many slaves achieved their freedom during the Revolution without formal EMANCIPATION. +
The British army, eager to debase the colonial economy, freed many slaves as they moved through the American South. +
Many slaves in the North were granted their freedom if they agreed to fight for the American cause. +
Although a clear majority of African Americans remained in bondage, the growth of free black communities in America was greatly fostered by the War for American Independence. +
Revolutionary sentiments led to the banning of the importation of slaves in 1807.

[.my2]
许多奴隶在革命期间获得了自由，但没有正式解放。英国军队渴望破坏殖民地经济，在许多奴隶穿越美国南部时释放了他们。如果北方的许多奴隶同意为美国的事业而战，他们就会获得自由。尽管绝大多数非裔美国人仍处于奴役状态，但美国独立战争极大地促进了美国自由黑人社区的发展。革命情绪导致 1807 年禁止进口奴隶。

During the colonial era, Americans were bound by British law. +
Now, they were no longer governed by the Crown or by colonial charter. +
INDEPENDENT, Americans could seek to eliminate or maintain laws as they saw fit. +
The possibilities were endless. +
REPUBLICAN revolutionary sentiment brought significant change during the immediate postwar years.

[.my2]
在殖民时代，美国人受到英国法律的约束。现在，他们不再受国王或殖民地宪章的管辖。独立后，美国人可以寻求废除或维持他们认为合适的法律。可能性是无限的。共和党的革命情绪在战后几年带来了重大变化。



Huge changes were made regarding land holding. +
English law required land to be passed down in its entirety from father to eldest son. +
This practice was known as PRIMOGENITURE. +
This kept land concentrated in the hands of few individuals, hardly consistent with revolutionary thinking. +
Within fifteen years of the Revolution, not a single state had a primogeniture law on the books.

[.my2]
土地持有方面发生了巨大变化。英国法律要求将全部土地从父亲传给长子。这种做法被称为“长子继承法”。这使得土地集中在少数人手中，这与革命思想几乎不相符。独立战争十五年之内，没有一个州制定了长子继承权法。

The fight for separation of church and state was on. +
In Virginia, it hardly seemed appropriate to support the Anglican Church of England with tax dollars. +
by 1833, all states abandoned the practice of a state-supported church.

[.my2]
争取政教分离的斗争正在进行。在弗吉尼亚州，用税收来支持英国圣公会似乎不太合适。到了 1833 年，所有州都放弃了国家支持的教会的做法。

Every society needs a set of rules by which to operate. +
After the colonies declared independence from Great Britain, they had to write their own constitutions. +
Impassioned with the republican spirit of the Revolution, political leaders pointed their ideals toward crafting "enlightened" documents. +
The result was thirteen republican laboratories, each experimenting with new ways of realizing the goals of the Revolution. +
In addition, representatives from all the colonies worked together to craft the ARTICLES OF CONFEDERATION, which itself provided the nascent nation with invaluable experience.

[.my2]
每个社会都需要一套运作规则。殖民地宣布脱离英国独立后，必须制定自己的宪法。政治领导人对革命的共和精神充满热情，他们的理想是制定“开明”的文件。结果是成立了十三个共和实验室，每个实验室都在尝试实现革命目标的新方法。此外，来自所有殖民地的代表共同制定了《邦联条款》，这本身就为这个新生国家提供了宝贵的经验。

The state constitutions had much in common with each other. +
Fearful of a strong monarch, the states were reluctant to grant sweeping powers to a new government. +
Most GOVERNORS were kept purposefully weak to deter an individual from aspiring to regal status or power. +
The legislative and judicial branches were elected regularly, so voters could hold them regularly accountable for their actions. +
Most states granted their people a BILL OF RIGHTS to protect treasured liberties from the threat of future despotism. +
Property requirements were still maintained, but in many cases they were lowered. +
Although the wealthy maintained a disproportionately large percentage of legislative seats, their influence was diminished. +
This is reflected in the post-Revolutionary transfer of state capitals from wealthy seaboard towns to the interior.

[.my2]
各州宪法彼此有很多共同点。由于害怕强大的君主，各州不愿向新政府授予广泛的权力。大多数州长都被故意保持弱势，以阻止个人渴望获得王室地位或权力。立法和司法部门定期选举，因此选民可以定期要求他们对其行为负责。大多数州授予其人民一项权利法案，以保护宝贵的自由免受未来专制主义的威胁。财产要求仍然维持不变，但在许多情况下降低了。尽管富人在立法席位中保持着不成比例的高比例，但他们的影响力却被削弱了。这反映在革命后州首府从富裕的沿海城镇向内陆的转移上。

Massachusetts developed an idea that would soon be implemented by the entire nation. +
They made any changes to their constitution possible only by constitutional convention. +
This inspired the nation's leaders to ratify changes in the Articles of Confederation the same way. +
Truly political ideals of equality were set into place in the states before the war even came to a close.


[.my2]
马萨诸塞州提出了一个很快就会被全国实施的想法。他们只有通过制宪会议才能对宪法进行任何修改。这促使国家领导人以同样的方式批准《邦联条例》的修改。真正的平等政治理想甚至在战争结束之前就在各州确立了。

As in the case of the abolition of slavery, changes for women would not come overnight. +
But the American Revolution ignited these changes. +
Education and respect would lead to the emergence of a powerful, outspoken middle class of women.

[.my2]
与废除奴隶制的情况一样，女性的改变也不会一蹴而就。但美国革命引发了这些变化。教育和尊重将导致强大、直言不讳的中产阶级女性的出现。


The United States was created as a result of the AMERICAN REVOLUTION, when thirteen colonies on the east coast of North America fought to end their membership in the British Empire. +
This was a bold, dangerous, and even foolish thing to do at the time, since Great Britain was the strongest country in the world. +
While American success in the Revolution seems obvious today, it wasn't at the time.

[.my2]
美国是美国革命的结果，当时北美东海岸的十三个殖民地为结束其在大英帝国的地位而奋斗。这在当时是一件大胆、危险、甚至愚蠢的事情，因为英国是世界上最强大的国家。虽然美国在革命中的成功在今天看来是显而易见的，但在当时却并非如此。

The war for American independence began with military conflict in 1775 and lasted at least until 1783 when the peace treaty with the British was signed. +
In fact, Native Americans in the west (who were allied with the British, but not included in the 1783 negotiations) continued to fight and didn't sign a treaty with the United States until 1795. +
The Revolution was a long, hard, and difficult struggle.

[.my2]
美国独立战争从 1775 年的军事冲突开始，至少持续到 1783 年与英国签署和平条约。事实上，西部的美洲原住民（他们与英国结盟，但没有参与 1783 年的谈判）继续战斗，直到 1795 年才与美国签署条约。艰难的斗争。

Even among Patriots there was a wide range of opinion about how the Revolution should shape the new nation. +
For example, soldiers often resented civilians for not sharing the deep personal sacrifice of fighting the war. +
Even among the men who fought, major differences often separated officers from ordinary soldiers. +
Finally, no consideration of the Revolution would be complete without considering the experience of people who were not Patriots. +
Loyalists were Americans who remained loyal to the British Empire. +
Almost all Native American groups opposed American Independence. +
Slaves would be made legally free if they fled Patriot masters to join the British Army, which they did in large numbers.

[.my2]
即使在爱国者中，对于革命应如何塑造新国家也存在广泛的意见。例如，士兵常常怨恨平民没有分担战争中巨大的个人牺牲。即使在参战的士兵中，军官与普通士兵之间也常常存在重大差异。最后，如果不考虑非爱国者的经历，对革命的考虑就不完整。保皇派是指仍然忠于大英帝国的美国人。几乎所有美洲原住民团体都反对美国独立。如果奴隶逃离爱国者主人并加入英国军队，他们将获得合法的自由，他们大量这样做了。


A constant question for our exploration, as well as for people at the time, is what does the Revolution mean and when did it end? Have the ideals of the Revolution been achieved even today? One of our challenges is to consider the meaning of the Revolution from multiple perspectives.

[.my2]
对于我们的探索以及当时的人们来说，一个永恒的问题是革命意味着什么以及它何时结束？革命的理想今天是否实现了？我们的挑战之一是从多个角度思考革命的意义。

'''

==== 独立宣言, 当初是"理性实用性", 大于"要改变人类社会的伟大抱负"性的

"When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation." So begins the DECLARATION OF INDEPENDENCE.

[.my2]
“在人类事件的过程中，一个民族有必要解散将他们与另一个民族联系在一起的政治束缚，并在地球的力量中承担自然法和自然法所具有的独立和平等的地位。大自然的上帝赋予他们权利，对人类意见的体面尊重要求他们必须宣布促使他们分离的原因。”独立宣言由此开始。


But what was the Declaration? Why do Americans continue to celebrate its public announcement as the birthday of the United States, July 4, 1776?

[.my2]
但宣言是什么？为什么美国人继续公开宣布 1776 年 7 月 4 日为美国生日来庆祝？

On the one hand, the Declaration was a formal LEGAL DOCUMENT that announced to the world the reasons that led the thirteen colonies to separate from the British Empire. +
Much of the Declaration sets forth a list of abuses that were blamed on King George III. +
One charge levied against the King sounds like a Biblical plague: "He has erected a multitude of New Offices, and sent hither swarms of Officers to harrass our people, and eat out their substance."

[.my2]
一方面，《宣言》是一份正式的法律文件，向世界宣布了导致十三个殖民地脱离大英帝国的原因。宣言的大部分内容列出了乔治三世国王的一系列虐待行为。对国王的一项指控听起来像是一场圣经瘟疫：“他设立了许多新的办公室，并派出大批官员到这里骚扰我们的人民，并吃掉他们的财产。”

The Declaration was not only legalistic, but practical too. +
Americans hoped to get financial or military support from other countries that were traditional enemies of the British. +
However, these legal and pragmatic purposes, which make up the bulk of the actual document, are not why the Declaration is remembered today as a foremost expression of the ideals of the Revolution.

[.my2]
该宣言不仅是法律性的，而且也是实用性的。美国人希望从其他与英国传统为敌的国家获得财政或军事支持。然而，构成实际文件大部分内容的这些法律和务实目的并不是宣言今天被铭记为革命理想的最重要表达的原因。

The Declaration's most famous sentence reads: "We hold these truths to be self-evident, THAT ALL MEN ARE CREATED EQUAL; that they are endowed by their Creator with certain unalienable rights; that among these are life, liberty, and the pursuit of happiness." Even today, this inspirational language expresses a profound commitment to human equality.

[.my2]
《宣言》最著名的一句话是：“我们认为这些真理是不言而喻的：人人生而平等；造物主赋予他们某些不可剥夺的权利；其中包括生命权、自由权和追求幸福的权利。”。即使在今天，这种鼓舞人心的语言仍然表达了对人类平等的深刻承诺。

The ideal of full human equality has been a major legacy (and ongoing challenge) of the Declaration of Independence. +
But the signers of 1776 did not have quite that radical an agenda.

[.my2]
人类完全平等的理想是《独立宣言》的主要遗产（也是持续的挑战）。但 1776 年的签署者并没有那么激进的议程。

Thomas Jefferson provides the classic example of the contradictions of the Revolutionary Era. +
Although he was the chief author of the Declaration, he also owned slaves, as did many of his fellow signers. +
They did not see full human equality as a positive social goal. +
Nevertheless, Jefferson was prepared to criticize slavery much more directly than most of his colleagues.

[.my2]
托马斯·杰斐逊提供了革命时代矛盾的典型例子。尽管他是该宣言的主要作者，但他也拥有奴隶，就像他的许多签署者一样。他们并不认为人类完全平等是一个积极的社会目标。尽管如此，杰斐逊准备比他的大多数同事更直接地批评奴隶制。


So what did the signers intend by using such idealistic language? Look at what follows the line, "We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are LIFE, LIBERTY AND THE PURSUIT OF HAPPINESS."

[.my2]
那么签署者使用这种理想主义语言的意图是什么？看看接下来的内容：“我们认为这些真理是不言而喻的，人人生而平等，造物主赋予他们某些不可剥夺的权利，其中包括生命权、自由权和追求幸福的权利。 ”

That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed, That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government, laying its foundation on such principles and organizing its powers in such form, as to them shall seem most likely to effect their Safety and Happiness.

[.my2]
为了确保这些权利，政府是在人类之间建立的，其正当权力来自被统治者的同意，每当任何形式的政府破坏这些目标时，人民都有权改变或废除它，并且建立新政府，以这样的原则为基础，以这样的形式组织权力，使他们看起来最有可能实现他们的安全和幸福。

These lines suggest that the whole purpose of GOVERNMENT is to secure the PEOPLE'S RIGHTS and that government gets its power from "the CONSENT OF THE GOVERNED." If that consent is betrayed, then "it is the right of the people to alter or abolish" their government. +
When the Declaration was written, this was a radical statement. +
The idea that the people could reject a monarchy (based on the superiority of a king) and replace it with a republican government (based on the consent of the people) was a revolutionary change.

[.my2]
这些线条表明政府的全部目的是保护人民的权利，政府的权力来自“被统治者的同意”。如果这种同意被背叛，那么“人民有权改变或废除”他们的政府。当宣言起草时，这是一个激进的声明。人民可以拒绝君主制（基于国王的优越性）并代之以共和政府（基于人民的同意），这是一个革命性的变化。

While the signers of the Declaration thought of "the people" more narrowly than we do today, they articulated principles that are still vital markers of American ideals. +
And while the Declaration did not initially lead to equality for all, it did provide an inspiring start on working toward equality.

[.my2]
虽然《宣言》的签署者对“人民”的理解比我们今天更加狭隘，但他们所阐述的原则仍然是美国理想的重要标志。尽管《宣言》最初并没有带来人人平等，但它确实为努力实现平等提供了一个鼓舞人心的开端。



'''

==== 对参军士兵的影响

Americans remember the famous battles of the American Revolution such as BUNKER HILL, SARATOGA, and Yorktown, in part, because they were Patriot victories. +
But this apparent string of successes is misleading.

[.my2]
美国人记得美国独立战争中的著名战役，如邦克山战役、萨拉托加战役和约克镇战役，部分原因是爱国者取得了胜利。但这一连串明显的成功具有误导性。


The Patriots lost more battles than they won and, like any war, the Revolution was filled with hard times, loss of life, and suffering. +
In fact, the Revolution had one of the highest casualty rates of any U.S. +
war; only the Civil War was bloodier.

[.my2]
爱国者队输掉的战斗比他们赢得的更多，而且像任何战争一样，革命充满了艰难时期、生命损失和痛苦。事实上，革命是美国历次战争中伤亡率最高的战争之一。只有内战更加血腥。

In the early days of 1776, most Americans were naïve when assessing just how difficult the war would be. +
Great initial enthusiasm led many men to join local militias where they often served under officers of their own choosing. +
Yet, these volunteer forces were not strong enough to defeat the BRITISH ARMY, which was the most highly trained and best equipped in the world. +
Furthermore, because most men preferred serving in the militia, the Continental Congress had trouble getting volunteers for General George Washington's CONTINENTAL ARMY. +
This was in part because, the Continental Army demanded longer terms and harsher discipline.

[.my2]
1776 年初，大多数美国人在评估战争的艰难程度时都很天真。最初的巨大热情促使许多人加入当地民兵，他们经常在自己选择的军官手下服役。然而，这些志愿军的实力还不足以击败世界上训练有素、装备最精良的英国军队。此外，由于大多数男人更喜欢在民兵中服役，大陆会议很难为乔治·华盛顿将军的大陆军找到志愿者。部分原因是大陆军要求更长的任期和更严格的纪律。

Washington correctly insisted on having a regular army as essential to any chance for victory. +
After a number of bad militia losses in battle, the Congress gradually developed a stricter military policy. +
It required each state to provide a larger quota of men, who would serve for longer terms, but who would be compensated by a signing bonus and the promise of free land after the war. +
This policy aimed to fill the ranks of the Continental Army, but was never fully successful. +
While the Congress authorized an army of 75,000, at its peak Washington's main force never had more than 18,000 men. +
The terms of service were such that only men with relatively few other options chose to join the Continental Army.

[.my2]
华盛顿正确地坚持拥有一支正规军对于任何胜利的机会都是至关重要的。在一些糟糕的民兵在战斗中损失惨重之后，国会逐渐制定了更严格的军事政策。它要求每个州提供更多的男性配额，这些人的任期更长，但他们将通过签约奖金和战后免费土地的承诺得到补偿。这项政策旨在填补大陆军的空缺，但从未完全成功。虽然国会授权军队人数为 75,000 人，但在鼎盛时期，华盛顿的主力部队从未超过 18,000 人。服役条款规定，只有其他选择相对较少的人才会选择加入大陆军。


Part of the difficulty in raising a large and permanent fighting force was that many Americans feared the army as a threat to the liberty of the new republic. +
The ideals of the Revolution suggested that the MILITIA, made up of local Patriotic volunteers, should be enough to win in a good cause against a corrupt enemy. +
Beyond this idealistic opposition to the army, there were also more pragmatic difficulties. +
If a wartime army camped near private homes, they often seized food and personal property. +
Exacerbating the situation was Congress inability to pay, feed, and equip the army.

[.my2]
组建一支庞大且常备的战斗部队的部分困难在于，许多美国人担心军队对新共和国的自由构成威胁。革命的理想表明，由当地爱国志愿者组成的民兵应该足以在正义事业中战胜腐败的敌人。除了对军队的理想主义反对之外，还存在更实际的困难。如果战时军队在私人住宅附近扎营，他们经常会夺取食物和个人财产。国会无力支付军队的费用、粮食和装备，使情况更加恶化。



As a result, soldiers often resented civilians whom they saw as not sharing equally in the sacrifices of the Revolution. +
Several MUTINIES occurred toward the end of the war, with ordinary soldiers protesting their lack of pay and poor conditions. +
Not only were soldiers angry, but officers also felt that the country did not treat them well. +
Patriotic civilians and the Congress expected officers, who were mostly elite gentlemen, to be honorably self-sacrificing in their wartime service. +
When officers were denied a lifetime pension at the end of the war, some of them threatened to conspire against the Congress. +
General Washington, however, acted swiftly to halt this threat before it was put into action.

[.my2]
因此，士兵们常常怨恨平民，他们认为平民没有平等地分享革命的牺牲。战争快结束时发生了几起兵变，普通士兵抗议他们的工资不足和条件恶劣。不仅士兵们愤怒，军官们也觉得国家待他们不好。爱国的平民和国会期望军官们（大多是精英绅士）在战时服务中光荣地自我牺牲。当战争结束时军官们被剥夺终身养老金时，他们中的一些人威胁要密谋反对国会。然而，华盛顿将军在这一威胁付诸行动之前迅速采取行动制止了这一威胁。

The Continental Army defeated the British, with the crucial help of French financial and military support, but the war ended with very mixed feelings about the usefulness of the army. +
Not only were civilians and those serving in the military mutually suspicious, but also even within the army soldiers and officers could harbor deep grudges against one another. +
The war against the British ended with the PATRIOT military victory at YORKTOWN in 1781. +
However, the meaning and consequences of the Revolution had not yet been decided.

[.my2]
在法国财政和军事支持的关键帮助下，大陆军击败了英国，但战争结束时，人们对军队的用处感到非常复杂。不但平民与军中相互猜疑，就连军中官兵之间也可能怀有深仇大恨。 1781 年，爱国者在约克敦取得军事胜利，对英战争结束。然而，革命的意义和后果尚未确定。


'''

==== 对"亲英国派"的影响

Any full assessment of the American Revolution must try to understand the place of LOYALISTS, those Americans who remained faithful to the British Empire during the war.

[.my2]
对美国革命的任何全面评估都必须试图了解保皇派的地位，即那些在战争期间仍然忠于大英帝国的美国人。

Although Loyalists were steadfast in their commitment to remain within the British Empire, it was a very hard decision to make and to stick to during the Revolution. +
Even before the war started, a group of Philadelphia QUAKERS were arrested and imprisoned in Virginia because of their perceived support of the British. +
The Patriots were not a tolerant group, and Loyalists suffered regular harassment, had their property seized, or were subject to personal attacks.

[.my2]
尽管效忠派坚定地承诺留在大英帝国境内，但在革命期间做出并坚持这一决定是一个非常艰难的决定。甚至在战争开始之前，一群费城贵格会成员就因为被认为支持英国而在弗吉尼亚州被捕并被监禁。爱国者不是一个宽容的团体，保皇派经常遭受骚扰，财产被没收，或者受到人身攻击。

The process of "TAR AND FEATHERING," for example, was brutally violent. +
Stripped of clothes, covered with hot tar, and splattered with feathers, the victim was then forced to parade about in public. +
Unless the British Army was close at hand to protect Loyalists, they often suffered bad treatment from Patriots and often had to flee their own homes. +
About one-in-six Americans was an active Loyalist during the Revolution, and that number undoubtedly would have been higher if the Patriots hadn't been so successful in threatening and punishing people who made their Loyalist sympathies known in public.

[.my2]
例如，“TAR AND FEATHERING”的过程是残酷暴力的。受害者被剥光衣服，浑身沾满热焦油，身上溅满羽毛，然后被迫在公共场合游行。除非英国军队近在咫尺保护效忠派，否则他们经常受到爱国者的虐待，常常不得不逃离自己的家园。大约六分之一的美国人在革命期间是积极的保皇派，如果爱国者没有如此成功地威胁和惩罚那些公开表示对保皇派同情的人，这个数字无疑会更高。


Perhaps the most interesting group of Loyalists were enslaved African-Americans who chose to join the British. +
The British promised to LIBERATE slaves who fled from their Patriot masters. +
This powerful incentive, and the opportunities opened by the chaos of war, led some 50,000 slaves (about 10 percent of the total slave population in the 1770s) to flee their Patriot masters. +
When the war ended, the British evacuated 20,000 formerly enslaved African Americans and resettled them as free people.

[.my2]
也许最有趣的保皇派群体是选择加入英国的被奴役的非裔美国人。英国人承诺解放逃离爱国者主人的奴隶。这种强大的动力，加上战争混乱带来的机会，导致大约 50,000 名奴隶（约占 1770 年代奴隶总数的 10%）逃离了他们的爱国者主人。战争结束后，英国撤离了 20,000 名以前被奴役的非裔美国人，并将他们作为自由人重新安置。

Along with this group of black Loyalists, about 80,000 other Loyalists chose to leave the independent United States after the Patriot victory in order to remain members of the British Empire. +
Wealthy men like Thomas Hutchinson who had the resources went to London. +
But most ordinary Loyalists went to Canada where they would come to play a large role in the development of Canadian society and government. +
In this way, the American Revolution played a central role shaping the future of two North American countries.

[.my2]
除了这群黑人效忠派之外，还有大约 80,000 名效忠派在爱国者胜利后选择离开独立的美国，以保留大英帝国的成员身份。像托马斯·哈钦森这样拥有资源的富人去了伦敦。但大多数普通效忠派都去了加拿大，他们将在加拿大社会和政府的发展中发挥重要作用。通过这种方式，美国革命在塑造两个北美国家的未来方面发挥了核心作用。

'''

==== 对奴隶的影响

The AMERICAN REVOLUTION, as an anti-tax movement, centered on Americans' right to control their own property. +
In the 18th century "property" included other human beings.

[.my2]
美国革命作为一场反税收运动，以美国人控制自己财产的权利为中心。 18世纪的“财产”包括"其他人"(即奴隶)。

In many ways, the Revolution reinforced American commitment to slavery. +
On the other hand, the Revolution also hinged on radical new ideas about "liberty" and "equality," which challenged slavery's long tradition of extreme human inequality. +
The changes to slavery in the REVOLUTIONARY ERA revealed both the potential for radical change and its failure more clearly than any other issue.


[.my2]
在许多方面，革命加强了美国对奴隶制的承诺。另一方面，革命也取决于关于“自由”和“平等”的激进新思想，这些思想挑战了奴隶制长期存在的人类极端不平等的传统。革命时代奴隶制的变化比任何其他问题都更清楚地揭示了彻底变革的潜力及其失败。

SLAVERY was a central institution in American society during the late-18th century, and was accepted as normal and applauded as a positive thing by many white Americans. +
However, this broad acceptance of slavery (which was never agreed to by black Americans) began to be challenged in the Revolutionary Era. +
The challenge came from several sources, partly from Revolutionary ideals, partly from a new evangelical religious commitment that stressed the equality of all Christians, and partly from a decline in the profitability of TOBACCO in the most significant slave region of Virginia and adjoining states.

[.my2]
奴隶制是 18 世纪末美国社会的一个中心制度，被许多美国白人视为正常现象并称赞为积极的事情。然而，这种对奴隶制的广泛接受（美国黑人从未同意这一点）在革命时代开始受到挑战。挑战来自多个来源，部分来自革命理想，部分来自强调所有基督徒平等的新福音派宗教承诺，部分来自弗吉尼亚州和邻近州最重要的奴隶地区烟草盈利能力的下降。

The decline of slavery in the period was most noticeable in the states north of Delaware, all of which passed laws outlawing slavery quite soon after the end of the war. +
However, these gradual emancipation laws were very slow to take effect — many of them only freed the children of current slaves, and even then, only when the children turned 25 years old. +
Although laws prohibited slavery in the North, the "PECULIAR INSTITUTION" persisted well into the 19th century.

[.my2]
这一时期奴隶制的衰落在特拉华州北部各州最为明显，所有这些州都在战争结束后不久就通过了取缔奴隶制的法律。然而，这些渐进式解放法律的生效速度非常缓慢——其中许多法律只解放了当前奴隶的孩子，而且即使如此，也只有在孩子年满 25 岁时才获得解放。尽管北方法律禁止奴隶制，但“特殊制度”一直持续到 19 世纪。

Even in the South, there was a significant movement toward freeing some slaves. +
In states where tobacco production no longer demanded large numbers of slaves, the free black population grew rapidly. +
By 1810 one third of the African American population in Maryland was free, and in Delaware free blacks outnumbered enslaved African Americans by three to one. +
Even in the powerful slave state of Virginia, the free black population grew more rapidly than ever before in the 1780s and 1790s. +
This major new free black population created a range of public institutions for themselves that usually used the word "African" to announce their distinctive pride and insistence on equality.

[.my2]
即使在南方，也出现了一场解放一些奴隶的重大运动。在烟草生产不再需要大量奴隶的州，自由黑人人口迅速增长。到 1810 年，马里兰州三分之一的非洲裔美国人获得了自由，而在特拉华州，自由黑人与被奴役的非洲裔美国人的数量之比为三比一。即使在强大的奴隶州弗吉尼亚，自由黑人人口的增长速度也比 1780 年代和 1790 年代任何时候都快。这个主要的新自由黑人群体为自己创建了一系列公共机构，这些机构通常使用“非洲”一词来宣布他们独特的自豪感和对平等的坚持。

'''

==== 对女性的影响

The Revolutionary rethinking of the rules for society also led to some reconsideration of the relationship between men and women. +
At this time, women were widely considered to be inferior to men, a status that was especially clear in the lack of legal rights for married women. +
The law did not recognize wives' independence in economic, political, or civic matters in Anglo-American society of the eighteenth century.

[.my2]
对社会规则的革命性重新思考也导致了对男女关系的重新思考。此时，女性被广泛认为不如男性，这种地位在已婚女性缺乏合法权利方面尤为明显。在十八世纪的英美社会，法律不承认妻子在经济、政治或公民事务上的独立性。



'''

==== 对美国原住民(如印第安人)的影响

While the previous explorations of African American and white female experience suggest both the gains and limitations produced in the Revolutionary Era, from the perspective of almost all NATIVE AMERICANS the American Revolution was an unmitigated disaster. +
At the start of the war Patriots worked hard to try and ensure Indian neutrality, for Indians could provide strategic military assistance that might decide the struggle. +
Gradually, however, it became clear to most native groups, that an independent America posed a far greater threat to their interests and way of life than a continued British presence that restrained American westward expansion.

[.my2]
虽然之前对非裔美国人和白人女性经历的探索表明了革命时代产生的收益和局限性，但从几乎所有美洲原住民的角度来看，美国革命是一场彻头彻尾的灾难。战争开始时，爱国者努力确保印度的中立，因为印度可以提供可能决定战局的战略军事援助。然而，大多数土著群体逐渐意识到，独立的美国对他们的利益和生活方式构成的威胁远大于英国的持续存在，这限制了美国向西扩张。


With remarkably few exceptions, Native American support for the British was close to universal.

[.my2]
除了极少数例外，美洲原住民几乎普遍支持英国人。



In spite of significant Native American aid to the British, the European treaty negotiations that concluded the war in 1783 had no native representatives. +
Although Ohio and Iroquois Indians had not surrendered nor suffered a final military defeat, the United States claimed that its victory over the British meant a victory over Indians as well. +
Not surprisingly, due to their lack of representation during treaty negotiations, Native Americans received very poor treatment in the diplomatic arrangements. +
The British retained their North American holdings north and west of the Great Lakes, but granted the new American republic all land between the Appalachian Mountains and the Mississippi River. +
In fact, this region was largely unsettled by whites and mostly inhabited by Native Americans.

[.my2]
尽管美洲原住民向英国提供了大量援助，但 1783 年结束战争的欧洲条约谈判却没有原住民代表。尽管俄亥俄州和易洛魁印第安人没有投降，也没有遭受最终的军事失败，但美国声称对英国的胜利也意味着对印第安人的胜利。毫不奇怪，由于在条约谈判中缺乏代表，美洲原住民在外交安排中受到的待遇非常差。英国保留了五大湖以北和以西的北美领土，但将阿巴拉契亚山脉和密西西比河之间的所有土地授予了新的美国共和国。事实上，这个地区主要居住着白人，大部分居住着美洲原住民。

'''

==== 对"自耕农"和"城市工匠"的影响


Two groups of Americans most fully represented the independent ideal in this republican vision for the new nation: yeomen farmers and urban artisans. +
These two groups made up the overwhelming majority of the white male population, and they were the biggest beneficiaries of the American Revolution.

[.my2]
两个美国人群体最充分地代表了这个新国家的共和愿景中的独立理想：自耕农和城市工匠。这两个群体占白人男性人口的绝大多数，是美国革命的最大受益者。

The YEOMEN FARMER who owned his own modest farm and worked it primarily with family labor remains the embodiment of the ideal American: honest, virtuous, hardworking, and independent.

[.my2]
自耕农拥有自己的小农场，主要靠家庭劳动来耕种，他们仍然是理想美国人的化身：诚实、善良、勤劳和独立。


While yeomen represented the largest number of white farmers in the Revolutionary Era, artisans were a leading urban group making up at least half the total population of seacoast cities. +
ARTISANS were skilled workers drawn from all levels of society from poor shoemakers and tailors to elite metal workers. +
they had contact with a broad range of urban society. +
These connections helped place artisans at the center of the Revolutionary movement and it is not surprising that the origins of the Revolution can largely be located in urban centers like Boston, New York, and Philadelphia, where artisans were numerous.

[.my2]
虽然自耕农代表了革命时期数量最多的白人农民，但工匠是主要的城市群体，占沿海城市总人口的至少一半。工匠是来自社会各个阶层的技术工人，从贫穷的鞋匠和裁缝到精英金属工人。他们与广泛的城市社会有接触。这些联系有助于将工匠置于革命运动的中心，毫不奇怪，革命的起源很大程度上位于波士顿、纽约和费城等城市中心，那里的工匠众多。

The representatives elected to the new republican state governments during the Revolution reflected the dramatic rise in importance of independent yeomen and artisans. +
A comparison of the legislatures in six colonies (New York, New Hampshire, New Jersey, Maryland, Virginia, and South Carolina) before the war reveals that 85 percent of the assemblymen were very wealthy, but by war's end in 1784, yeomen and artisans of moderate wealth made up the majority (62 percent) of elected officials in the three northern states, while they formed a significant minority (30 percent) in the southern states. +
The Revolution's greatest achievement, and it was a major change, was the expansion of formal politics to include independent workingmen of modest wealth.

[.my2]
革命期间选出的新共和州政府代表反映出独立自耕农和工匠的重要性急剧上升。对战前六个殖民地（纽约州、新罕布什尔州、新泽西州、马里兰州、弗吉尼亚州和南卡罗来纳州）立法机构的比较显示，85% 的议员非常富有，但到 1784 年战争结束时，自耕农和工匠的财富都减少了。在北部三个州，中等财富的人占民选官员的大多数（62%），而在南部各州，他们只占少数（30%）。革命的最大成就，也是一项重大变革，是扩大了正式政治范围，将拥有微薄财富的独立工人纳入其中。


'''

==== 革命的国际间比较

The American Revolution needs to be understood in a broader framework than simply that of domestic events and national politics. +
The American Revolution started a trans-Atlantic Age of Revolution.

[.my2]
美国革命需要在更广泛的框架内理解，而不仅仅是国内事件和国家政治。美国革命开启了跨大西洋革命时代。

The French Revolution surely sprung from important internal dynamics, but the connection between the French struggle that began in 1789 and the American Revolution was widely acknowledged at the time.

[.my2]
法国大革命无疑源于重要的内部动力，但 1789 年开始的法国斗争与美国革命之间的联系在当时得到了广泛认可。


In comparison to the French and Haitian Revolutions, the lack of radical change in the American Revolution is glaring. +
The benefits of the American Revolution for the poor, for women, and, perhaps most of all, for enslaved people, were very limited. +
Nevertheless, the American Revolution did transform American society in meaningful ways and it accomplished its changes with comparatively little bloody violence. +
Most notably of all, the American Revolution created new republican political institutions that proved to be remarkably stable and long lasting.

[.my2]
与法国革命和海地革命相比，美国革命缺乏根本性的变革是显而易见的。美国革命给穷人、妇女，也许最重要的是，给被奴役者带来的好处是非常有限的。尽管如此，美国革命确实以有意义的方式改变了美国社会，并且以相对较少的血腥暴力实现了这一变化。最值得注意的是，美国革命创建了新的共和政治制度，事实证明这些制度非常稳定和持久。

As ABRAHAM LINCOLN viewed it half a century later on the verge of the Civil War, the Union had to prevail so that "government of the people, by the people, for the people, shall not perish from the earth."

[.my2]
正如亚伯拉罕·林肯在半个世纪后在内战边缘所看到的那样，联邦必须获胜，这样“民有、民治、民享的政府才不会从地球上消失”。

For all its limitations, the American Revolution had also built a framework that allowed for future inclusion and redress of wrongs.

[.my2]
尽管有其局限性，美国革命也建立了一个框架基础，允许未来进一步的扩大包容, 和纠正错误。

'''



== pure

The Revolution brought myriad consequences to the American social fabric. There was no REIGN OF TERROR as in the French Revolution. There was no replacement of the ruling class by workers' groups as in revolutionary Russia.

How then could the American Revolution be described as radical? Nearly every aspect of American life was somehow touched by the REVOLUTIONARY SPIRIT. From slavery to women's rights, from religious life to voting, American attitudes would be forever changed.



Some changes would be felt immediately. Slavery would not be abolished for another hundred years, but the Revolution saw the dawn of an organized abolitionist movement. English traditions such as land inheritance laws were swept away almost immediately. The Anglican Church in America could no longer survive. After all, the official head of the Church of England was the British monarch. States experimented with republican ideas when drafting their own constitutions during the war. All these major changes would be felt by Americans before the dawn of the nineteenth century.

The American Revolution produced a new outlook among its people that would have ramifications long into the future. Groups excluded from immediate equality such as slaves and women would draw their later inspirations from revolutionary sentiments. Americans began to feel that their fight for liberty was a global fight. Future democracies would model their governments on ours. There are few events that would shake the world order like the success of the American patriotic cause.

Life, liberty and the pursuit of happiness simply did not seem consistent with the practice of chattel slavery. How could a group of people feel so passionate about these unalienable rights, yet maintain the brutal practice of human bondage? Somehow slavery would manage to survive the revolutionary era, but great changes were brought to this PECULIAR INSTITUTION nevertheless.

Many slaves achieved their freedom during the Revolution without formal EMANCIPATION. The British army, eager to debase the colonial economy, freed many slaves as they moved through the American South. Many slaves in the North were granted their freedom if they agreed to fight for the American cause. Although a clear majority of African Americans remained in bondage, the growth of free black communities in America was greatly fostered by the War for American Independence. Revolutionary sentiments led to the banning of the importation of slaves in 1807.

During the colonial era, Americans were bound by British law. Now, they were no longer governed by the Crown or by colonial charter. INDEPENDENT, Americans could seek to eliminate or maintain laws as they saw fit. The possibilities were endless. REPUBLICAN revolutionary sentiment brought significant change during the immediate postwar years.



Huge changes were made regarding land holding. English law required land to be passed down in its entirety from father to eldest son. This practice was known as PRIMOGENITURE. This kept land concentrated in the hands of few individuals, hardly consistent with revolutionary thinking. Within fifteen years of the Revolution, not a single state had a primogeniture law on the books.

The fight for separation of church and state was on. In Virginia, it hardly seemed appropriate to support the Anglican Church of England with tax dollars. by 1833, all states abandoned the practice of a state-supported church.

Every society needs a set of rules by which to operate. After the colonies declared independence from Great Britain, they had to write their own constitutions. Impassioned with the republican spirit of the Revolution, political leaders pointed their ideals toward crafting "enlightened" documents. The result was thirteen republican laboratories, each experimenting with new ways of realizing the goals of the Revolution. In addition, representatives from all the colonies worked together to craft the ARTICLES OF CONFEDERATION, which itself provided the nascent nation with invaluable experience.

The state constitutions had much in common with each other. Fearful of a strong monarch, the states were reluctant to grant sweeping powers to a new government. Most GOVERNORS were kept purposefully weak to deter an individual from aspiring to regal status or power. The legislative and judicial branches were elected regularly, so voters could hold them regularly accountable for their actions. Most states granted their people a BILL OF RIGHTS to protect treasured liberties from the threat of future despotism. Property requirements were still maintained, but in many cases they were lowered. Although the wealthy maintained a disproportionately large percentage of legislative seats, their influence was diminished. This is reflected in the post-Revolutionary transfer of state capitals from wealthy seaboard towns to the interior.

Massachusetts developed an idea that would soon be implemented by the entire nation. They made any changes to their constitution possible only by constitutional convention. This inspired the nation's leaders to ratify changes in the Articles of Confederation the same way. Truly political ideals of equality were set into place in the states before the war even came to a close.

As in the case of the abolition of slavery, changes for women would not come overnight. But the American Revolution ignited these changes. Education and respect would lead to the emergence of a powerful, outspoken middle class of women.


The United States was created as a result of the AMERICAN REVOLUTION, when thirteen colonies on the east coast of North America fought to end their membership in the British Empire. This was a bold, dangerous, and even foolish thing to do at the time, since Great Britain was the strongest country in the world. While American success in the Revolution seems obvious today, it wasn't at the time.

The war for American independence began with military conflict in 1775 and lasted at least until 1783 when the peace treaty with the British was signed. In fact, Native Americans in the west (who were allied with the British, but not included in the 1783 negotiations) continued to fight and didn't sign a treaty with the United States until 1795. The Revolution was a long, hard, and difficult struggle.

Even among Patriots there was a wide range of opinion about how the Revolution should shape the new nation. For example, soldiers often resented civilians for not sharing the deep personal sacrifice of fighting the war. Even among the men who fought, major differences often separated officers from ordinary soldiers. Finally, no consideration of the Revolution would be complete without considering the experience of people who were not Patriots. Loyalists were Americans who remained loyal to the British Empire. Almost all Native American groups opposed American Independence. Slaves would be made legally free if they fled Patriot masters to join the British Army, which they did in large numbers.


A constant question for our exploration, as well as for people at the time, is what does the Revolution mean and when did it end? Have the ideals of the Revolution been achieved even today? One of our challenges is to consider the meaning of the Revolution from multiple perspectives.

'''

==== 独立宣言, 当初是"理性实用性", 大于"要改变人类社会的伟大抱负"性的

"When in the Course of human events, it becomes necessary for one people to dissolve the political bands which have connected them with another, and to assume among the powers of the earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle them, a decent respect to the opinions of mankind requires that they should declare the causes which impel them to the separation." So begins the DECLARATION OF INDEPENDENCE.


But what was the Declaration? Why do Americans continue to celebrate its public announcement as the birthday of the United States, July 4, 1776?

On the one hand, the Declaration was a formal LEGAL DOCUMENT that announced to the world the reasons that led the thirteen colonies to separate from the British Empire. Much of the Declaration sets forth a list of abuses that were blamed on King George III. One charge levied against the King sounds like a Biblical plague: "He has erected a multitude of New Offices, and sent hither swarms of Officers to harrass our people, and eat out their substance."

The Declaration was not only legalistic, but practical too. Americans hoped to get financial or military support from other countries that were traditional enemies of the British. However, these legal and pragmatic purposes, which make up the bulk of the actual document, are not why the Declaration is remembered today as a foremost expression of the ideals of the Revolution.

The Declaration's most famous sentence reads: "We hold these truths to be self-evident, THAT ALL MEN ARE CREATED EQUAL; that they are endowed by their Creator with certain unalienable rights; that among these are life, liberty, and the pursuit of happiness." Even today, this inspirational language expresses a profound commitment to human equality.

The ideal of full human equality has been a major legacy (and ongoing challenge) of the Declaration of Independence. But the signers of 1776 did not have quite that radical an agenda.

Thomas Jefferson provides the classic example of the contradictions of the Revolutionary Era. Although he was the chief author of the Declaration, he also owned slaves, as did many of his fellow signers. They did not see full human equality as a positive social goal. Nevertheless, Jefferson was prepared to criticize slavery much more directly than most of his colleagues.


So what did the signers intend by using such idealistic language? Look at what follows the line, "We hold these truths to be self-evident, that all men are created equal, that they are endowed by their Creator with certain unalienable Rights, that among these are LIFE, LIBERTY AND THE PURSUIT OF HAPPINESS."

That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed, That whenever any Form of Government becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to institute new Government, laying its foundation on such principles and organizing its powers in such form, as to them shall seem most likely to effect their Safety and Happiness.

These lines suggest that the whole purpose of GOVERNMENT is to secure the PEOPLE'S RIGHTS and that government gets its power from "the CONSENT OF THE GOVERNED." If that consent is betrayed, then "it is the right of the people to alter or abolish" their government. When the Declaration was written, this was a radical statement. The idea that the people could reject a monarchy (based on the superiority of a king) and replace it with a republican government (based on the consent of the people) was a revolutionary change.

While the signers of the Declaration thought of "the people" more narrowly than we do today, they articulated principles that are still vital markers of American ideals. And while the Declaration did not initially lead to equality for all, it did provide an inspiring start on working toward equality.



'''

==== 对参军士兵的影响

Americans remember the famous battles of the American Revolution such as BUNKER HILL, SARATOGA, and Yorktown, in part, because they were Patriot victories. But this apparent string of successes is misleading.


The Patriots lost more battles than they won and, like any war, the Revolution was filled with hard times, loss of life, and suffering. In fact, the Revolution had one of the highest casualty rates of any U.S. war; only the Civil War was bloodier.

In the early days of 1776, most Americans were naïve when assessing just how difficult the war would be. Great initial enthusiasm led many men to join local militias where they often served under officers of their own choosing. Yet, these volunteer forces were not strong enough to defeat the BRITISH ARMY, which was the most highly trained and best equipped in the world. Furthermore, because most men preferred serving in the militia, the Continental Congress had trouble getting volunteers for General George Washington's CONTINENTAL ARMY. This was in part because, the Continental Army demanded longer terms and harsher discipline.

Washington correctly insisted on having a regular army as essential to any chance for victory. After a number of bad militia losses in battle, the Congress gradually developed a stricter military policy. It required each state to provide a larger quota of men, who would serve for longer terms, but who would be compensated by a signing bonus and the promise of free land after the war. This policy aimed to fill the ranks of the Continental Army, but was never fully successful. While the Congress authorized an army of 75,000, at its peak Washington's main force never had more than 18,000 men. The terms of service were such that only men with relatively few other options chose to join the Continental Army.


Part of the difficulty in raising a large and permanent fighting force was that many Americans feared the army as a threat to the liberty of the new republic. The ideals of the Revolution suggested that the MILITIA, made up of local Patriotic volunteers, should be enough to win in a good cause against a corrupt enemy. Beyond this idealistic opposition to the army, there were also more pragmatic difficulties. If a wartime army camped near private homes, they often seized food and personal property. Exacerbating the situation was Congress inability to pay, feed, and equip the army.



As a result, soldiers often resented civilians whom they saw as not sharing equally in the sacrifices of the Revolution. Several MUTINIES occurred toward the end of the war, with ordinary soldiers protesting their lack of pay and poor conditions. Not only were soldiers angry, but officers also felt that the country did not treat them well. Patriotic civilians and the Congress expected officers, who were mostly elite gentlemen, to be honorably self-sacrificing in their wartime service. When officers were denied a lifetime pension at the end of the war, some of them threatened to conspire against the Congress. General Washington, however, acted swiftly to halt this threat before it was put into action.

The Continental Army defeated the British, with the crucial help of French financial and military support, but the war ended with very mixed feelings about the usefulness of the army. Not only were civilians and those serving in the military mutually suspicious, but also even within the army soldiers and officers could harbor deep grudges against one another. The war against the British ended with the PATRIOT military victory at YORKTOWN in 1781. However, the meaning and consequences of the Revolution had not yet been decided.


'''

==== 对"亲英国派"的影响

Any full assessment of the American Revolution must try to understand the place of LOYALISTS, those Americans who remained faithful to the British Empire during the war.

Although Loyalists were steadfast in their commitment to remain within the British Empire, it was a very hard decision to make and to stick to during the Revolution. Even before the war started, a group of Philadelphia QUAKERS were arrested and imprisoned in Virginia because of their perceived support of the British. The Patriots were not a tolerant group, and Loyalists suffered regular harassment, had their property seized, or were subject to personal attacks.

The process of "TAR AND FEATHERING," for example, was brutally violent. Stripped of clothes, covered with hot tar, and splattered with feathers, the victim was then forced to parade about in public. Unless the British Army was close at hand to protect Loyalists, they often suffered bad treatment from Patriots and often had to flee their own homes. About one-in-six Americans was an active Loyalist during the Revolution, and that number undoubtedly would have been higher if the Patriots hadn't been so successful in threatening and punishing people who made their Loyalist sympathies known in public.


Perhaps the most interesting group of Loyalists were enslaved African-Americans who chose to join the British. The British promised to LIBERATE slaves who fled from their Patriot masters. This powerful incentive, and the opportunities opened by the chaos of war, led some 50,000 slaves (about 10 percent of the total slave population in the 1770s) to flee their Patriot masters. When the war ended, the British evacuated 20,000 formerly enslaved African Americans and resettled them as free people.

Along with this group of black Loyalists, about 80,000 other Loyalists chose to leave the independent United States after the Patriot victory in order to remain members of the British Empire. Wealthy men like Thomas Hutchinson who had the resources went to London. But most ordinary Loyalists went to Canada where they would come to play a large role in the development of Canadian society and government. In this way, the American Revolution played a central role shaping the future of two North American countries.

'''

==== 对奴隶的影响

The AMERICAN REVOLUTION, as an anti-tax movement, centered on Americans' right to control their own property. In the 18th century "property" included other human beings.

In many ways, the Revolution reinforced American commitment to slavery. On the other hand, the Revolution also hinged on radical new ideas about "liberty" and "equality," which challenged slavery's long tradition of extreme human inequality. The changes to slavery in the REVOLUTIONARY ERA revealed both the potential for radical change and its failure more clearly than any other issue.

SLAVERY was a central institution in American society during the late-18th century, and was accepted as normal and applauded as a positive thing by many white Americans. However, this broad acceptance of slavery (which was never agreed to by black Americans) began to be challenged in the Revolutionary Era. The challenge came from several sources, partly from Revolutionary ideals, partly from a new evangelical religious commitment that stressed the equality of all Christians, and partly from a decline in the profitability of TOBACCO in the most significant slave region of Virginia and adjoining states.

The decline of slavery in the period was most noticeable in the states north of Delaware, all of which passed laws outlawing slavery quite soon after the end of the war. However, these gradual emancipation laws were very slow to take effect — many of them only freed the children of current slaves, and even then, only when the children turned 25 years old. Although laws prohibited slavery in the North, the "PECULIAR INSTITUTION" persisted well into the 19th century.

Even in the South, there was a significant movement toward freeing some slaves. In states where tobacco production no longer demanded large numbers of slaves, the free black population grew rapidly. By 1810 one third of the African American population in Maryland was free, and in Delaware free blacks outnumbered enslaved African Americans by three to one. Even in the powerful slave state of Virginia, the free black population grew more rapidly than ever before in the 1780s and 1790s. This major new free black population created a range of public institutions for themselves that usually used the word "African" to announce their distinctive pride and insistence on equality.

'''

==== 对女性的影响

The Revolutionary rethinking of the rules for society also led to some reconsideration of the relationship between men and women. At this time, women were widely considered to be inferior to men, a status that was especially clear in the lack of legal rights for married women. The law did not recognize wives' independence in economic, political, or civic matters in Anglo-American society of the eighteenth century.



'''

==== 对美国原住民(如印第安人)的影响

While the previous explorations of African American and white female experience suggest both the gains and limitations produced in the Revolutionary Era, from the perspective of almost all NATIVE AMERICANS the American Revolution was an unmitigated disaster. At the start of the war Patriots worked hard to try and ensure Indian neutrality, for Indians could provide strategic military assistance that might decide the struggle. Gradually, however, it became clear to most native groups, that an independent America posed a far greater threat to their interests and way of life than a continued British presence that restrained American westward expansion.


With remarkably few exceptions, Native American support for the British was close to universal.



In spite of significant Native American aid to the British, the European treaty negotiations that concluded the war in 1783 had no native representatives. Although Ohio and Iroquois Indians had not surrendered nor suffered a final military defeat, the United States claimed that its victory over the British meant a victory over Indians as well. Not surprisingly, due to their lack of representation during treaty negotiations, Native Americans received very poor treatment in the diplomatic arrangements. The British retained their North American holdings north and west of the Great Lakes, but granted the new American republic all land between the Appalachian Mountains and the Mississippi River. In fact, this region was largely unsettled by whites and mostly inhabited by Native Americans.

'''

==== 对"自耕农"和"城市工匠"的影响


Two groups of Americans most fully represented the independent ideal in this republican vision for the new nation: yeomen farmers and urban artisans. These two groups made up the overwhelming majority of the white male population, and they were the biggest beneficiaries of the American Revolution.

The YEOMEN FARMER who owned his own modest farm and worked it primarily with family labor remains the embodiment of the ideal American: honest, virtuous, hardworking, and independent.


While yeomen represented the largest number of white farmers in the Revolutionary Era, artisans were a leading urban group making up at least half the total population of seacoast cities. ARTISANS were skilled workers drawn from all levels of society from poor shoemakers and tailors to elite metal workers. they had contact with a broad range of urban society. These connections helped place artisans at the center of the Revolutionary movement and it is not surprising that the origins of the Revolution can largely be located in urban centers like Boston, New York, and Philadelphia, where artisans were numerous.

The representatives elected to the new republican state governments during the Revolution reflected the dramatic rise in importance of independent yeomen and artisans. A comparison of the legislatures in six colonies (New York, New Hampshire, New Jersey, Maryland, Virginia, and South Carolina) before the war reveals that 85 percent of the assemblymen were very wealthy, but by war's end in 1784, yeomen and artisans of moderate wealth made up the majority (62 percent) of elected officials in the three northern states, while they formed a significant minority (30 percent) in the southern states. The Revolution's greatest achievement, and it was a major change, was the expansion of formal politics to include independent workingmen of modest wealth.


'''

==== 革命的国际间比较

The American Revolution needs to be understood in a broader framework than simply that of domestic events and national politics. The American Revolution started a trans-Atlantic Age of Revolution.

The French Revolution surely sprung from important internal dynamics, but the connection between the French struggle that began in 1789 and the American Revolution was widely acknowledged at the time.


In comparison to the French and Haitian Revolutions, the lack of radical change in the American Revolution is glaring. The benefits of the American Revolution for the poor, for women, and, perhaps most of all, for enslaved people, were very limited. Nevertheless, the American Revolution did transform American society in meaningful ways and it accomplished its changes with comparatively little bloody violence. Most notably of all, the American Revolution created new republican political institutions that proved to be remarkably stable and long lasting.

As ABRAHAM LINCOLN viewed it half a century later on the verge of the Civil War, the Union had to prevail so that "government of the people, by the people, for the people, shall not perish from the earth."

For all its limitations, the American Revolution had also built a framework that allowed for future inclusion and redress of wrongs.

'''
























































