= 0409
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 409: Describing a Musical Performance.
This is English as a Second Language Podcast episode 409. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download a Learning Guide for this episode, which will help you improve your English even faster.
This episode is called “Describing a Musical Performance.” It’s a dialogue between Janine and Calvin about a musical “performance,” when you go to listen to someone who is playing an instrument or singing. They’re going to use a lot of vocabulary we might use to describe music and someone performing music. The dialogue is actually between two people who are selecting, or deciding, who is going to be a member of the musical group that they are in charge of. So, they’re going to listen to people playing music and then decide if this person is good enough to be part of their group. Let’s get started.
[start of dialogue]
Janine: Okay, we need to find one more act for this year’s show. How many more people are waiting to audition?
Calvin: There are two more. Should I call in the first one?
Janine: Yup. Let’s get this over with.
...
Calvin: What did you think of that performance?
Janine: I thought she was flawless. She plays with a lot of passion.
Calvin: Yeah, that’s true, but I wouldn’t call her a virtuoso. The piece she played was pretty rudimentary.
Janine: True enough, but I still think she’s a winner.
Calvin: Let’s hear the next one.
...
Calvin: Well?
Janine: He certainly played with a lot of flair.
Calvin: He has amazing chops, I think. I haven’t seen anyone play with such artistry in a long time.
Janine: Nobody can fault him on mastery of the music, but don’t you think he lacked originality and expressiveness?
Calvin: No, I don’t. I think he’s a winner.
Janine: It’s clear that it’s a stalemate. I want the first performer and you want the second. What should we do?
Calvin: I think we should duke it out and the winner gets his or her choice.
Janine: I have a better idea. We add them both to the bill.
Calvin: That’s brilliant! That’s why they pay you the big bucks.
Janine: I would be flattered if we weren’t all volunteers!
[end of dialogue]
Our dialogue begins with Janine saying, “Okay, we need to find one more act for this year’s show.” They’re looking for one person or one group that can perform in a show with other musical groups, so there’s actually more than one group in this performance – this show. She says, “How many more people are waiting to audition?” To “audition” means to sing, or play a musical instrument, act, or dance for a short period of time so that someone can see and listen and decide if you are good enough to be part of this performance. So for example here in Los Angeles, in Hollywood, people go on auditions – and that’s the expression we use, “to go on an audition.” They go on an audition to be part of a movie or to be part of a television series and it’s usually quite short; it’s usually a minute, two minutes, maybe five or 10 minutes, not a long time. If you’re interested in this topic be sure to listen to English Café number 132, where we interview an actor here in Los Angeles.
So, Janine is asking how many people are waiting to audition. Calvin says, “There are two more. Should I call in the first one?” – should I tell the first person to come in now? Janine says, “Yup” (yup), which is a short, informal way of saying yes. She says, “Let’s get this over with.” To “get something over with” means to do something as fast as you can, often because it isn’t very pleasant. You’re trying to get something done that you really don’t want to do.
So, they listen to the musical performance and then they talk about it. Of course, we don’t actually get to hear the musical performance. Calvin says, “What did you think of that performance?” – what was your opinion? Janine says, “I thought she was flawless” (flawless). To be “flawless” means to be perfect. A “flaw” is an error or a mistake, so to be “flawless” means to have no mistakes, no errors. Janine says, “She plays with a lot of passion.” “Passion,” here, means enthusiasm, a very strong love of something, someone who really loves it and is enthusiastic about it.
Calvin says, “Yeah (meaning yes), that’s true, but I wouldn’t call her a virtuoso.” A “virtuoso” is a very good musician who plays very, very well. Yo-Yo Ma is a famous American virtuoso on the cello. Calvin says, “The piece she played was pretty rudimentary.” “Rudimentary” means basic and simple, not very advanced or difficult. Janine says, “True enough (meaning yes, that’s true, I agree), but I still think she’s a winner.” Calvin says, “Let’s hear the next one,” and of course, then they listen to the next performance. Afterwards, they come back and talk about it.
Calvin says, “Well?” meaning what is your opinion. Janine says, “He certainly played with a lot of flair.” “Flair” (flair), here, means with a lot of style, in a very interesting, perhaps unusual, way. “He has a lot of flair” – he does things in interesting and unusual ways. Calvin says, “He has amazing chops, I think.” “Chops” (chops), here, means ability or skill to do something. It’s often used to describe someone who is very good at music, but it could be used for anything. You could say, “He has great cooking chops,” meaning he has a lot of ability or skill or talent to do that thing. “Chop” has a number of different meanings in English; take a look at the Learning Guide for some additional explanations.
Calvin says, “I haven’t seen anyone play with such artistry in a long time.” “Artistry” means with a lot of talent – a lot of artistic talent, someone who has a lot of skills in music, for example, or singing, or acting, something in what we would call “the arts.” He has a lot of artistry.
Janine doesn’t really agree. She says, “Nobody can fault him on mastery of the music.” To “fault” someone means to say that someone did something wrong, to say that this person is not very good at something. You may say, “I won’t fault you for not knowing how to type” – I won’t blame you, I won’t say you did something wrong. She says no one “can fault him on mastery of the music.” “Mastery” (mastery) means expertise, having a full or complete knowledge of something or ability to do something. It’s another way of saying to be very good at something.
Janine says, “don’t you think he lacked originality and expressiveness?” She doesn’t think that this performer was very original. “He “lacked (or didn’t have) originality,” meaning he wasn’t different, he wasn’t unique, he didn’t do something that no one else has done before. “Expressiveness” is a word we would use to describe someone who has an ability to show you how they feel or think, usually through their art – through their music, their singing, their dance, their acting. Someone who is very expressive shows their emotions; you can feel what they are feeling.
Calvin says, “No. I think he’s a winner.” Janine says, “It’s clear that it’s a stalemate.” When you have a “stalemate” (stalemate – one word) you have a situation where neither person can win. It’s often used to describe a situation where two people cannot agree: “We’re at a stalemate,” or “We have a stalemate.”
Janine says, “I want the first performer and you want the second. What should we do?” So they don’t agree on which person should be the final act – the final performer in this show that they are putting on – that they are putting together, organizing. Calvin says, “I think we should duke it out and the winner gets his or her choice.” He’s joking here, because to “duke something out” means to fight someone in order to decide an argument. To actually hit them, that sort of fighting: “to duke it out.” “The two boxers duked it out” – they fought each other.
Well, of course, Calvin is just joking – we hope! Janine says, “I have a better idea. We add them both to the bill.” “Bill,” here, means a written list of who will be performing in a play or at a concert. “Bill” has many different meanings in English, but this one means a list of those who will be performing at a certain concert or play.
Calvin says, “That’s brilliant (that’s a great idea)! That’s why they pay you the big bucks.” When someone says, “They pay him the big bucks,” they mean they pay him a lot of money. A “buck” is another word for a dollar, “bucks” (plural) means money in general, and “big bucks” means a lot of money.
Janine says, “I would be flattered if we weren’t all volunteers!” To “be flattered” means to be happy that someone said something nice about you, to be happy that someone likes you or what you have done. A beautiful woman comes up to me and says, “May I have your telephone number?” Well, I’m flattered – I’m also, of course, married! Janine says, “I would be flattered if we weren’t all volunteers,” meaning we don’t get paid for this, if we did get paid for this, then I would be – conditional – I would be flattered. But of course, they don’t get paid anything.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Janine: Okay, we need to find one more act for this year’s show. How many more people are waiting to audition?
Calvin: There are two more. Should I call in the first one?
Janine: Yup. Let’s get this over with.
...
Calvin: What did you think of that performance?
Janine: I thought she was flawless. She plays with a lot of passion.
Calvin: Yeah, that’s true, but I wouldn’t call her a virtuoso. The piece she played was pretty rudimentary.
Janine: True enough, but I still think she’s a winner.
Calvin: Let’s hear the next one.
...
Calvin: Well?
Janine: He certainly played with a lot of flair.
Calvin: He has amazing chops, I think. I haven’t seen anyone play with such artistry in a long time.
Janine: Nobody can fault him on mastery of the music, but don’t you think he lacked originality and expressiveness?
Calvin: No, I don’t. I think he’s a winner.
Janine: It’s clear that it’s a stalemate. I want the first performer and you want the second. What should we do?
Calvin: I think we should duke it out and the winner gets his or her choice.
Janine: I have a better idea. We add them both to the bill.
Calvin: That’s brilliant! That’s why they pay you the big bucks.
Janine: I would be flattered if we weren’t all volunteers!
[end of dialogue]
The script today was by someone who has great writing chops, Dr. Lucy Tse!
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
to audition – to sing, play a musical instrument, act, or dance for a short period of time so that someone can see and listen and decide whether one should be selected for a real performance or participation in a group
* Mariah wants to audition for a role in a movie.
to get (something) over with – to do something that is unpleasant right away so that one doesn’t have to worry about it anymore
* I hate washing dishes, so I try to get it over with as soon as possible each evening.
flawless – perfect; without any mistakes or errors
* She spends a lot of time getting ready in the morning and her hair and make-up are always flawless.
passion – a very strong love of something; a lot of enthusiasm
* Food is his passion, so he’s always trying new recipes and buying new things for the kitchen.
virtuoso – a very good musician who plays very well
* Yo-Yo Ma is a famous virtuoso on the cello.
rudimentary – basic and simple; not advanced or difficult
* Those students have only a rudimentary knowledge of mathematics.
flair – style; in an interesting, unusual way
* Becca always dresses with a lot of flair, combining interesting colors and wearing unusual hats.
chops – ability, skill, or talent to do something that is considered difficult
* Oscar showed off his cooking chops by making a five-course dinner for everyone.
artistry – with a lot of artistic talent; with a lot of skill in the arts
* She paints with surprising artistry for her age.
to fault (someone) – to say that someone did something wrong; to say that someone is not very good at something
* Hans isn’t a very good baseball player, but no one can fault his basketball skills.
mastery – expertise; full knowledge of something and/or full ability to do something; being very good at doing something
* Please demonstrate your mastery of this software program by creating a graph from this data.
originality – uniqueness; creativity and imagination; ability to do something in a new way as no one else has done it before
* Kendall expresses his originality by wearing unusual clothes and dying his hair purple and pink.
expressiveness – the ability to show what one thinks or feels, often through writing, artwork, music, or dance
* Her music has so much expressiveness that sometimes it makes listeners cry.
stalemate – a situation where neither person can win; a situation where two people cannot agree
* When he wanted to go to an Italian restaurant and she wanted to go to a Chinese restaurant, they ended in a stalemate and ate at home that night.
to duke it out – to fight against someone to decide an argument
* When their cars hit each other, they couldn’t decide who should pay for the damages, so they started to duke it out in the middle of the street.
bill – a written list of who will be performing in a play or concert
* According to the bill, Nancy will be playing the role of Annie in tonight’s play.
big bucks – a lot of money, especially money that one is paid for working
* Tiffany has a lot of responsibility at work and has to make difficult decisions. That’s why they pay her the big bucks.
flattered – happy that someone has said something nice about oneself; happy to learn that someone likes oneself and/or what one has done
* Miguel was flattered when his daughter said that he was the best daddy in the whole world.
Comprehension Questions
1. How would a musician like to be described?
a) As a virtuoso.
b) As a rudimentary musician.
c) As a stalemate.
2. What is Janine’s idea?
a) To send a bill to both musicians.
b) To ask the musicians to pay the bill.
c) To include both musicians in the performance.
Answers at bottom.
What Else Does It Mean?
chops
The word “chops,” in this podcast, means having the ability, skill, or talent to do something difficult: “Dizzy Gillespie was famous for his musical chops.” “Chops” are also small pieces of meat, usually from a pig or sheep, which are still attached to the bone: “We’re having pork chops and applesauce for dinner.” As a verb, “to chop” means to cut something, especially food or wood, into smaller pieces: “Could you please chop the onions and carrots for me?” Or, “We need to chop more firewood for the fireplace.” Finally, the phrase “to chop (something) down” means to cut a tall thing at the bottom so that it falls down: “Why did they chop down all the beautiful old trees in the park?”
to fault (someone)
In this podcast, the phrase “to fault (someone)” means to say that someone did something wrong or to say that someone is not very good at something: “They faulted Gregorio for the company’s slow sales, saying that he wasn’t doing his job well.” If something is “someone’s fault,” it is a bad thing that happened because of something that person did or didn’t do: “Do you think it’s the parents’ fault if their children are overweight?” Or, “She is mad at me, but it isn’t my fault!” Finally, a “fault” can be something that doesn’t work correctly in a machine: “If there is a fault in your computer, you can take it back to the store where you bought it and ask for a different one.”
Culture Note
Most musical performances begin when the band or “orchestra” (a large group of people playing many different instruments) “warms up,” where each person plays his or her musical instrument for a short period of time to practice. Warming up also helps the musicians “tune” the instruments, making sure that they can all play the same note, at the same “pitch” (whether a sound is high or low). Sometimes warm-ups happen “backstage” (where the audience cannot see or hear), but orchestras often warm up where the audience can hear them.
Once the warm-up is finished, the “conductor” (a person who leads the orchestra by moving his or her arms) and/or the band members “take the stage,” coming onto the large area in the front of the theater or other area where people can see them. The audience usually “applauds” (claps, hitting hands together to make noise) or “cheers” (makes loud sounds to show pleasure and approval).
During the performance, audience members applaud or cheer for “solos” (short parts of songs that are performed by just one singer or musician). They also applaud or cheer after each “piece of music” (song) ends. People often shout “bravo” to show that they are pleased with a performance.
When all the songs are done, the audience applauds or cheers for a longer period of time, often standing up to show their “appreciation” (how much they liked the performance). If the audience really liked it and wants to hear more, people shout “encore,” meaning that they want the musicians to continue to perform. Most musicians will provide an encore of one or two songs that were not part of the original bill for the performance.
Comprehension Answers
1 - a
2 - c