= 0423
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 423: Reading Food Labels.
This is English as a Second Language Podcast episode 423. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode. You can also take a look at our ESL Podcast Store, as well as our ESL Podcast Blog.
This episode is a dialogue between Wendy and Ichirou. They are going to be talking about something that you will find in most American grocery stores (food stores), and that is food labels. The government requires that many, or most kinds of food have a label on them that gives you information about what is inside the food and other what we would call “nutritional information.” Let’s get started.
[start of dialogue]
I never read food labels until I started going out with Wendy. She’s studying to be a nutritionist. When we go grocery shopping, she reads every label.
________
Wendy: You’re not buying that, are you?
Ichirou: Well, I was thinking about it. Why?
Wendy: Each serving size has 30 grams of fat, and 10 of those are trans fat. The sodium level is through the roof, and it’s full of carbohydrates. Do you really want to put that in your body?
Ichirou: Um, I guess not.
Wendy: What are these cookies doing in the basket?
Ichirou: Those are my favorite. I always get them. I got the low-fat kind, see?
Wendy: Even so, they’re full of calories. They may be reduced fat, but they’re not low fat. You don’t eat this kind of cereal do you?
Ichirou: Yeah, I do.
Wendy: Look at the percent daily values. You get nearly no nutrients and no dietary fiber, and it’s full of sugar.
________
I really like Wendy, but I’m not sure how long I can take this. She has the best of intentions, but will my stomach ever forgive me if I keep going out with her? That’s the question.
[end of dialogue]
Our dialogue begins with Ichirou saying “I never read food labels until I started going out with Wendy.” A “food label” is a piece of paper that has written information about it on a piece of packaging for food. So, it’s on the outside of the food package where you will find the food label. He says he never read food labels until he started going out with (until he started dating) Wendy. Wendy’s been studying to be a nutritionist. A “nutritionist” is a person whose job it is to help people need better, so they get better food perhaps because they need to lose weight or for some medical reason.
He says, “When we go grocery shopping (when we go shopping for food), Wendy reads every (food) label.” Then we go into dialogue: Wendy says, “You’re not buying that, are you?” Obviously, Wendy doesn’t like what Ichirou is going to buy. He says, “Well, I was thinking about it (meaning yes, I was planning on it). Why?” Wendy says, “Each serving size has 30 grams of fat.” The “serving size” is the amount of a particular food that should be eaten by one person. Many foods are sold in large containers, so there’s more than one serving, more than enough needed for one person. There could be two, or three, or five or six servings in that package, meaning five or six people would have enough food to eat from that package.
“Each serving size,” Wendy says, “has 30 grams of fat.” A “gram” is a unit of measurement for weight. “Fat” is the oily part of foods; fat is a kind of food. Food has protein and carbohydrates, and it also can have fat. Certain kinds of fat are considered bad for your health, especially saturated fats and trans fat. Wendy says that there are 10 grams of trans fat in that particular package. Trans fat is now considered the most unhealthy kind of fat because it can increase (or raise) your risk of having a heart attack.
Wendy says, “The sodium level is through the roof.” “Sodium” is another word for salt; it’s the chemical element Na. “Through the roof” is an expression that means very high or a very large number. “The price of gasoline in the U.S. went through the roof last year” – it became very expensive, very high in price. So, the sodium level is very high in this piece of food and “it’s full of carbohydrates.” Remember, we talked about food having different elements (different parts). One element is carbohydrates. “Carbohydrate” is the part of a food that is used to make energy – that the body uses to make energy.
Well, Wendy says to Ichirou, “Do you really want to put that in your body?” Of course, he probably does, but because she is his girlfriend he wants to keep her happy, so he says, “Um, I guess not,” meaning no, I don’t. Wendy says, “What are these cookies doing in the basket?” meaning why did you put cookies in their shopping basket. A “shopping basket” is a container you use to put your food in in a store before you pay for it. It helps you move the food around the store.
Ichirou says, “Those are my favorite (my favorite cookies). I always get them. I got the low-fat kind, see?” When a food is called “low-fat” it means it has only a small amount of fat in it. Some people try to buy food that is low-fat because they think it is better for them. However, Wendy points out the cookies are still “full of calories.” A “calorie” is a measurement, technically, of the amount of energy in food. If you eat more calories you will gain more weight – if you eat too many calories, I should say. If you don’t eat enough calories, then you will lose weight. So, when Wendy says the food is full of calories, she means they have a lot of calories – too many calories. Wendy says, “They may be reduced fat, but they’re not low fat.” Food that is “low fat” has very little fat in it. Food that is “reduced fat” has less fat than normal, but more fat than low fat. So, it’s somewhere between normally and low fat.
Wendy says, “You don’t eat this kind of cereal do you?” “Cereal” is a food often eaten at breakfast. Usually it’s small, dry pieces of food made from grains, and you put them in a bowl with milk and you eat them with a spoon. I have cereal every day for breakfast. Wendy obviously doesn’t like the cereal that Ichirou eats. He says, “Yeah, I do,” meaning I do eat that kind of cereal. Wendy says, “Look at the percent daily values.” The “percent daily value” is the piece of information found on the food label that tells you the percentage of the recommended amount of something that people are supposed to eat every day that is in that particular food. So, it might say for example, this bread has a percent daily value of 20 percent for vitamin A. That means this food has about 20 percent of the vitamin A that you will need in any given day. A single serving, typically, has that percentage.
Wendy says, “You get nearly no nutrients.” “You get nearly no” means you get almost no nutrients. A “nutrient” is a vitamin, a mineral, or another part of the food that you eat that helps you become strong and keeps you healthy. So nutrients are good things. The food also has “no dietary fiber.” “Dietary fiber,” or simply “fiber,” is a kind of food or part of food then you eat but it cannot be used by the body (the fiber), but it helps keep the food moving through your body, and that is dietary fiber’s purpose. Salads, whole grains – these have, typically, a lot of dietary fiber. She says the cereal is “full of sugar.” “Sugar,” sometimes called “sucrose” or “glucose,” is the sweet tasting part of food. “Sugar” has a couple of different meanings in English, as does the word “fat.” Take a look at our Learning Guide for additional explanations of both of these terms.
Ichirou is not sure he wants to continue dating Wendy. He says, “I really like Wendy, but I’m not sure how long I can take this.” When we say we “can take” something, we mean we are able to continue doing this, listening to this, without becoming angry or upset. It means to tolerate something – to “take” something. “I can’t take this music” – I can’t tolerate this music, I cannot listen to this music anymore. He says Wendy “has the best of intentions, but will my stomach ever forgive me if I keep going out with her?” The expression “the best of intentions” means that the person wants to do something well; they want to do something that is good, but that’s not actually what they do. Your “intention” is your desire, what you want to happen, but sometimes our intentions are not the same as what we actually do. Wendy has the best of intentions, she “means well” we might also say, but poor Ichirou doesn’t think he can continue going out with her because she keeps criticizing the kind of food that he eats.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
I never read food labels until I started going out with Wendy. She’s studying to be a nutritionist. When we go grocery shopping, she reads every label.
________
Wendy: You’re not buying that, are you?
Ichirou: Well, I was thinking about it. Why?
Wendy: Each serving size has 30 grams of fat, and 10 of those are trans fat. The sodium level is through the roof, and it’s full of carbohydrates. Do you really want to put that in your body?
Ichirou: Um, I guess not.
Wendy: What are these cookies doing in the basket?
Ichirou: Those are my favorite. I always get them. I got the low-fat kind, see?
Wendy: Even so, they’re full of calories. They may be reduced fat, but they’re not low fat. You don’t eat this kind of cereal do you?
Ichirou: Yeah, I do.
Wendy: Look at the percent daily values. You get nearly no nutrients and no dietary fiber, and it’s full of sugar.
________
I really like Wendy, but I’m not sure how long I can take this. She has the best of intentions, but will my stomach ever forgive me if I keep going out with her? That’s the question.
[end of dialogue]
The script for this episode was written by someone who gives you 100 percent of your daily recommended English, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Please come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
food label – the written information on a bottle or box of food that tells one the nutritional value of that food
* According to this food label, one slice of bread has 130 calories.
nutritionist – a person whose job is to help people eat better so that they get the nutrition they need, often so that they can lose or gain weight or lower their cholesterol or blood pressure
* Each week, Maranda meets with a nutritionist who is helping her lose weight by changing what she eats.
serving size – the amount of a particular food that should be eaten by one person at one time
* The serving size for this ice cream is just ? cup, but I usually eat much more than that.
gram – a unit of measurement for weight; 0.03527 ounces
* How many grams of salt will I need to bake that bread?
fat – the oily part of foods; the greasy part of animal bodies
* Whole milk has much more fat than skim milk does.
trans fat – the most unhealthy kind of fat that a person can eat because it increases one’s cholesterol
* Many food companies are trying to lower the amount of trans fat in their products.
sodium – salt; the chemical element Na+
* Having too much sodium in our diet can increase our blood pressure.
through the roof – very high; with a very large number; extreme
* The price of corn went through the roof when many corn farms were damaged by the bad weather.
carbohydrate – the sugary part of foods that is used by the body to make energy
* Try to eat more good carbohydrates, like the ones found in whole-wheat bread and pasta, and less of the bad carbohydrates, like the ones found in soda and candy.
low-fat – with only a small amount of fat
* Do you buy regular yogurt or low-fat yogurt?
calorie – a measurement of the amount of energy in food
* An apple has about 100 calories.
reduced-fat – with less fat than usual; with less fat than the regular variety of a food product
* Do you make these crackers in a reduced-fat version?
cereal – a food that is normally eaten for breakfast, with small, dry pieces made from grains that are put in a bowl with milk and eaten with a spoon
* Do you want to put some raisins or bananas on top of your cereal?
percent daily value – the percentage of the recommended amount of something that people are supposed to eat every day that is provided by a particular food
* This bread has a percent daily value of 20% for Vitamin A.
nutrient – vitamins, minerals, and other parts of food that one needs to eat to be healthy and strong
* Fresh fruits and vegetables have a lot of nutrients.
dietary fiber – the part of food that one eats but that cannot be used by the body, which keeps food moving through one’s body quickly
* Eating a salad every day can help you get enough dietary fiber.
sugar – sucrose or glucose; the sweet-tasting part of food
* Some types of soda have more than 10 teaspoons of sugar in just one can!
to take (something) – to be able to tolerate something; to be able to continue doing or listening to something without becoming angry or upset
* The neighbors’ son is learning how to play the drums, but I can’t take the noise anymore!
the best of intentions – the desire to do something well or to do something that will be helpful, good, or useful
* I know she has the best of intentions and wants to help, but really she’s making things more difficult.
Comprehension Questions
1. Which of these might a nutritionist want you to eat more of?
a) Trans fat.
b) Dietary fiber.
c) Sugar.
2. What does he mean when he says, “She has the best of intentions”?
a) She is the best nutritionist.
b) She is trying to help him.
c) She is intent on being the best.
Answers at bottom.
What Else Does It Mean?
fat
The word “fat,” in this podcast, means the oily part of foods: “How much fat is in a hamburger?” The word “fat” can also be used to describe someone who is overweight, although it isn’t very polite: “Nobody likes sitting next to fat people on airplanes.” The phrase “baby fat” refers to the fat on a baby’s or child’s body that should go away with age: “Chelsea is 10 years old and is just starting to lose her baby fat.” The phrase “to chew the fat” means to have a friendly conversation for a long time: “They talk on the phone every day, chewing the fat for hours.” Or, “How many hours of each day do you guys chew the fat instead of working?”
sugar
In this podcast, the word “sugar” means the sweet-tasting part of food: “Do you drink your coffee with milk and sugar?” A “sugar cube” is a large piece of sugar, usually in the shape of a square that is put into a hot drink: “Would you like one sugar cube or two?” The word “sugar” is also used to talk to someone whom one loves or likes very much: “Hey, sugar, how was your day?” If something is “sugar-coated,” it is said in the nicest possible way so that it seems better than it actually is: “Can you think of a sugar-coated way to tell someone that he’s been fired?” Or, “You don’t have to sugar-coat it, doctor. Just tell me the bad news.” Finally, the phrase “give me some sugar” can be used to informally ask someone for a kiss: “There’s my beautiful wife! Give me some sugar.”
Culture Note
The Food and Drug Administration (FDA) is the part of the U.S. government that protects Americans’ health by “approving” (saying that something is okay) food and drugs. The FDA “requires” (says that something must happen) that all “prepared foods” (foods that are made from other foods) must have food labels that provide information about the nutritional content of the food. “Produce” (fruits and vegetables) do not need to have food labels.
Food labels must include a “statement of identity” that says what the food is and who made it. They also must include a “net quantity statement,” which says how much the food weighs without the “packaging” (the box, bottle, or other container that the food is in).
Prepared foods must have labels that state the serving size and the number of servings per package. Often these serving sizes are much smaller than the amounts that Americans usually eat. Food labels also must have nutrient information, including the percent daily values of each nutrient. The food label must list all the “ingredients” (the foods used to make something) that are in the food. These ingredients are listed in “decreasing order,” meaning that the ingredient used the most is listed first, and the ingredient used the least is listed last.
Many food labels also list the “potential” (possible) “allergens” (things that make certain people sick). For example, a food label might say, “Contains: milk, peanuts.” This would be a “warning” (a statement that something bad or dangerous might happen) that people who are “allergic” to milk or peanuts should not eat that food.
Comprehension Answers
1 - b
2 - b