= 0425
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 425: Serving Drinks and Cocktails.
This is English as a Second Language Podcast episode 425. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. On it you can find a Learning Guide for this episode to help you improve your English even faster.
This episode is a dialogue between Spencer and Heidi talking about making alcoholic, for the most part, drinks. They’ll use a lot of common vocabulary, and talk about some specific kinds of popular drinks in the U.S. Let’s get started.
[start of dialogue]
Spencer: I’m practicing making drinks for the party tonight. Do you want to try one?
Heidi: You’re the bartender? I didn’t know you knew how to mix drinks.
Spencer: I can hold my own. Okay, name it and I’ll make it – any mixed drink or cocktail.
Heidi: Okay, I’ll have a Screwdriver.
Spencer: A Screwdriver? Hmm…what’s in that?
Heidi: Aren’t you supposed to know, Mr. Bartender?
Spencer: I’ve never made one of those before, that’s all. Try something else.
Heidi: How about a Bloody Mary?
Spencer: A Bloody Mary, a Bloody Mary…do you want that on the rocks?
Heidi: Sure, that’ll be great.
Spencer: Here you are – a Bloody Mary in a highball. Enjoy!
Heidi: [Makes a gagging sound] This doesn’t taste like a Bloody Mary. It tastes like you poured an entire bottle of alcohol into this.
Spencer: Oh, come on. It’s not that bad. Here, I’ll add a little soda, and oh, I forgot the garnish.
Heidi: I don’t think that’s going to help. Can I give you some advice? Stick to shots and drinks served straight up.
Spencer: Ah, don’t lose faith in me. Let me make you one more drink.
Heidi: Okay, but make it virgin. My mouth is still on fire from the last one.
[end of dialogue]
Spencer begins our dialogue by telling Heidi “I’m practicing making drinks for the party tonight. Do you want to try one?” Heidi asks, “You’re the bartender?” The “bartender” is the person whose job it is to make alcoholic drinks at a party, or in a restaurant, or at a bar. Heidi says, “I didn’t know you knew how to mix drinks.” “Mix drinks,” here, to make special, usually alcoholic, drinks by mixing different kinds alcohol, soda, and, or perhaps, juice. Sometimes we refer those kind of drinks with the noun “mixed drinks.” But here, it’s used as a verb meaning to make the drinks, to prepare the drinks.
Spencer says, “I can hold my own.” To “hold your own” is an expression that means to be able to do something just as well as other people can do it. “I can hold my own” – I’m as good as other people. Spencer says, “Okay, name it,” meaning tell me what kind of drink you want. Both “to hold your own” and “name it” have a couple of different meanings in English; take a look at our Learning Guide for more information.
Spencer says, “I’ll make any mixed drink,” notice here it’s used as a noun: a mixed drink, “or cocktail.” A “cocktail” (cocktail) is just another name for a mixed drink; a mixed drink and cocktail are the same thing, people use both names.
Heidi says, “Okay, I’ll have a Screwdriver.” A “screwdriver” normally is a tool that you use with little pieces of metal called “screws.” But here, it’s an alcoholic drink, a popular one, that is made vodka and orange juice. Spencer says, “A Screwdriver? Hmm…what’s in that?” Well, Screwdriver is probably the easiest drink you can make; almost everyone knows what a Screwdriver is, at least anyone who goes to bars and restaurants. So, Spencer not knowing is a good indication that he’s not very good.
Heidi says, “Aren’t you supposed to know, Mr. Bartender?” – isn’t it your job to know? Notice she calls him “Mr. Bartender.” This is sometimes used as a joke when you call someone by their job or occupation, so you might say to me, “Mr. Podcaster.” It’s usually used sort of as a joke often when people say they know something but, in fact, they don’t.
Spencer says, “I’ve never made one of those (one of those Screwdrivers) before, that’s all. Try something else.” So Heidi gives him another drink: “How about a Bloody Mary?” A “Bloody Mary” is a drink made from vodka, tomato juice, and usually some spices to give it a certain flavor. But basically, vodka and tomato juice is a Bloody Mary, again, a very simple drink.
Spencer seems to know how to make it, and he asks Heidi if she wanted it on the rocks. The expression “on the rocks” (rocks) means with ice. We use this expression when we are talking about beverages (drinks). Some people, for example, like to drink whisky, and they like the whisky to be poured onto some ice cubes in a glass. That would be whisky on the rocks. If you don’t want ice in your drinks, you would tell the bartender you want it “straight up.” Straight up: “Give me a whisky straight up” – no ice, just the whisky.
Well, Spencer gives her the Bloody Mary on the rocks, and he says, “Here you go” or “Here you are – a Bloody Mary in a highball.” A “highball” is a type of glass, a tall glass that is often used for alcoholic beverages. In some parts of the country, a highball is a name of a drink. It’s a drink with brandy or whisky mixed with either some sort of soda or water, but here it just means a glass.
Heidi says, “This doesn’t taste like a Bloody Mary. It tastes like you poured (you put) an entire bottle of alcohol into this.” Spencer says, “Oh, come on.” That expression is used when you are telling somebody not to complain, or to stop saying what they are saying because it’s wrong or it’s exaggerated. He says, “Oh, come on. It’s not that bad” – it’s not very bad or as bad as you say. He says, “Here, I’ll add a little soda.” “Soda,” when you are talking about drinks, usually means “carbonated water,” that is water that has little bubbles in it. If you’re not talking about alcoholic drinks, soda can refer to what is called in some parts of the country “soda pop,” things like Coca-Cola or Pepsi. In Minnesota, where I’m from, everyone just says “pop,” so you’ll say “Can I have a pop?” Whereas here in California, and in most other places, you would ask for a soda if you wanted, say, a Coca-Cola or something similar. In making alcoholic drinks a soda, or what’s sometimes called “soda water,” is a carbonated water.
Spencer says, “oh, I forgot the garnish.” “Garnish” is something that’s used to decorate your plate of food or your drink. It isn’t really part of the drink; it’s just something that’s supposed to make it look nice.
Heidi says, “I don’t think that’s going to help.” She says, “Can I give you some advice? Stick to shots and drinks served straight up.” A “shot” is a small amount of alcohol. There are actually little glasses which we call “shot glasses,” where you can pour alcohol into. You can use it to measure the alcohol, or you can just drink the alcohol right from the shot glass; these are called “shots.” “Give me a shot of whisky.” Sometimes especially younger people when they are in a bar and perhaps not experienced with drinking, or want to get drunk, will “do shots,” that is they will drink a lot of shots of alcohol so they can get intoxicated. This has never happened to me, but I’ve seen other people do it. The expression “stick to” something means do something that is very basic, or do only this, continue doing that and don’t try to do anything more complicated. So, I do audio podcasts. If I were to start doing video podcasts (with the exception of our anniversary videos, of course), someone might say, “Jeff, you’re not very good at that. Stick to audio podcasts” – continue doing the simpler thing because you don’t know enough to do the more complicated thing. That’s what Heidi is saying to Spencer here.
Spencer says, “don’t lose faith in me,” meaning don’t stop having confidence in me, continue to believe in me. “Don’t lose faith in me. Let me make you one more drink,” he says. Heidi says, “Okay, but make it virgin. My mouth is still on fire (is still hot) from the last one.” A “virgin” drink is a drink without any alcohol, but it has all of the other ingredients. So it looks like a regular drink but, in fact, there is no alcohol in the drink. A “virgin,” here, means untouched. The term, of course, also refers to a woman or a man who has never had sexual relations.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Spencer: I’m practicing making drinks for the party tonight. Do you want to try one?
Heidi: You’re the bartender? I didn’t know you knew how to mix drinks.
Spencer: I can hold my own. Okay, name it and I’ll make it – any mixed drink or cocktail.
Heidi: Okay, I’ll have a Screwdriver.
Spencer: A Screwdriver? Hmm…what’s in that?
Heidi: Aren’t you supposed to know, Mr. Bartender?
Spencer: I’ve never made one of those before, that’s all. Try something else.
Heidi: How about a Bloody Mary?
Spencer: A Bloody Mary, a Bloody Mary…do you want that on the rocks?
Heidi: Sure, that’ll be great.
Spencer: Here you are – a Bloody Mary in a highball. Enjoy!
Heidi: [Makes a gagging sound] This doesn’t taste like a Bloody Mary. It tastes like you poured an entire bottle of alcohol into this.
Spencer: Oh, come on. It’s not that bad. Here, I’ll add a little soda, and oh, I forgot the garnish.
Heidi: I don’t think that’s going to help. Can I give you some advice? Stick to shots and drinks served straight up.
Spencer: Ah, don’t lose faith in me. Let me make you one more drink.
Heidi: Okay, but make it virgin. My mouth is still on fire from the last one.
[end of dialogue]
Our script today was written by someone who can hold her own here in Hollywood, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
bartender – a person whose job is to make alcoholic drinks at a party or in a restaurant or bar
* We trained our bartender to know when to stop making drinks for people who have had too much to drink.
to mix drinks – to make special alcoholic drinks by mixing many types of alcohol, soda, and/or juice
* When Dora wanted to learn how to mix drinks, she bought a book that had instructions for all the most popular ones.
to hold (one’s) own – to be able to do something just as well as other people can
* I’m not a professional swimmer, but I can hold my own in the pool.
name it – an expression used to ask a person to say what he or she wants with the understanding that one will help him or her get it
* - Can you help me with something?
* - Sure, name it!
mixed drink – a cocktail; a drink made from many types of alcohol, soda, and/or juice
* Her favorite mixed drink is made with vodka, orange juice, and lemon-lime soda.
cocktail – a mixed drink; a drink made from many types of alcohol, soda, and/or juice
* Would you prefer to have a cocktail or a beer?
Screwdriver – an alcoholic drink made from vodka and orange juice
* Whenever he has a difficult day at work, he drinks a Screwdriver to help him relax.
Bloody Mary – an alcoholic drink made from vodka, tomato juice, and spices (small plant leaves with a strong flavor and odor)
* A Bloody Mary might be one of the healthiest alcoholic drinks because it is made with tomatoes.
on the rocks – with ice (used when talking about beverages)
* On a hot day, he likes to drink bourbon on the rocks.
highball -– an alcoholic drink made by mixing brandy or whisky with soda or water
* After work, everyone went to the bar across the street and ordered highballs.
alcohol – the part of a drink like wine, beer, and liquor that makes people relax and act differently than they normally do
* How old were you the first time you tasted alcohol?
soda – carbonated water, with or without flavorings; water than has many small bubbles in it
* Plain soda water doesn’t taste very good because it doesn’t have any sugar in it like most sodas do.
garnish – something that is used to decorate a type of food on a plate or a beverage, usually a small piece of a vegetable or fruit
* The restaurant uses orange slices to garnish most of its plates.
to stick to (something) – to do something that is very basic; to continue doing something basic that one knows how to do well, without trying to do anything fancier or more complicated
* Chopin’s music is too difficult for me to play on the piano, so I’m going to stick to children’s music.
shot – a small amount of alcohol served in a very small glass that is drunk all at once, all in one swallow
* Kelly started coughing after she took a shot of whisky.
straight up – pure; without any water, ice, or other type of alcohol added to a drink
* Do you prefer tequila straight up or with a lime?
to lose faith in (someone or something) – to stop having confidence in someone or something; to no longer believe that one can do something
* Many people have lost faith in their government.
virgin – a drink that does not have any alcohol but is made to look like an alcoholic drink
* Rebah ordered a strawberry margarita for himself and a virgin strawberry margarita for his son.
Comprehension Questions
1. Which of these would you order if you wanted only alcohol?
a) A mixed drink.
b) A cocktail.
c) A drink made straight up.
2. What is a virgin drink?
a) A drink made with soda.
b) A drink without alcohol.
c) A drink without garnish.
Answers at bottom.
What Else Does It Mean?
to hold (one's) own
The phrase “to hold (one's) own,” in this podcast, means to be able to do something just as well as other people can: “Mariah can hold her own in the kitchen, making just about anything you may want to eat.” The phrase “to hold (one’s) head high” means to show that one is proud of oneself and not embarrassed about anything: “He comes from a poor family, but he always holds his head high and isn’t ashamed of it.” The phrase “to hold one’s tongue” means to stop talking or to not say anything in a particular situation: “It was difficult for me to listen to so many opinions that were different from my own, but I held my tongue and didn’t say anything.”
name it
In this podcast, the phrase “name it” is an expression used to ask a person to say what he or she wants with the understanding that one will help him or her get it: “I told you that you could have anything you wanted for your birthday, so just name it.” The phrase “to name names” means to say who did something wrong or to say who was involved in a bad situation: “Tammie knows who stole the money, but she is scared to name names.” The phrase “to name the date” means to pick a date for a wedding: “Congratulations on your engagement! Have you named the date yet?” Finally, the phrase “to name a few” is used after listing a few things to show that one could list many other things, too: “He likes basketball, baseball, football, and volleyball, to name a few.”
Culture Note
In the United States, there are many “restrictions” (limitations or rules) on buying and drinking alcohol. The “drinking age” (the minimum age for someone to drink alcohol legally) is a law that “prevents” (doesn’t allow) people from drinking if they are less than 21 years old. There are many other restrictions for people who are older than 21.
Most states have open “container” (bottle, box, or other packaging) laws. These laws prevent people from having or drinking out of an open container of alcohol in “vehicles” (cars) and public areas. This means, for example, that people who have a “picnic” (food eaten outdoors, usually in a park or a nice natural area) cannot have alcohol, although many people do it anyway.
Many cities and states also have “blue laws.” A blue law is a law that restricts the activities that people can do on Sunday. Specifically, blue laws don’t allow people to buy alcohol on Sunday, or sometimes just on Sunday morning. Other blue laws don’t allow alcohol to be sold after a certain time on Saturday afternoons, either. People who “advocate for” (think something is a good idea) these laws believe that by not selling alcohol on Sunday, people are more likely to spend the time with their families and/or in church. Of course, people might buy a lot of alcohol earlier in the week and then drink it on Sunday anyway.
There are also restrictions on where alcohol can be sold. Stores and restaurants that want to sell alcohol must have a “liquor” (alcohol) “license” (legal permission). When a store or restaurant “applies for” (asks for) a liquor license, the community is “notified” (informed) and has an opportunity to “comment on” (say what people think about) whether or not it should get a liquor license.
Comprehension Answers
1 - c
2 - b