= 0432
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 432: Using the Copier.
This is English as a Second Language Podcast episode 432. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there and download a Learning Guide for this episode that will help you improve your English even faster.
This episode is called “Using the Copier.” The “copier,” or the “photocopier,” is a machine that we use to make copies of pieces of paper – the things that are on the paper. We have a dialogue between Tim and Pam about some common problems – some common vocabulary you may encounter (you may hear) when talking about the copy machine. Let’s get started.
[start of dialogue]
Tim: Damn it!
Pam: What’s the matter?
Tim: It’s this copier. My original didn’t come out of the feeder and there’s a paper jam.
Pam: Let me see if I can clear it. This machine is really temperamental.
Tim: Tell me about it.
Pam: Okay, I found your original, but it’s stuck. I’m afraid if I pull too hard, it’ll tear.
Tim: Let me try. I got it! Okay, I need to shrink the first page and adjust the contrast so that it’s more readable. Then I need to enlarge the second page. After that, I need to make 20 collated copies.
Pam: Oh, oh, don’t look now, but the toner light is on. You’ll need to put in a new cartridge.
Tim: Is there anything else that can go wrong with this stupid copier?!
Pam: Don’t tempt fate. It could be worse. The whole thing could break down!
[end of dialogue]
Tim begins our dialogue by “swearing,” by saying a not very nice word. He says, “Damn it!” “Damn it” is an expression that you use when you’re angry at something or someone. It’s not something you would want to say in front of children or your boss, for example. Sometimes people simply say “damn.” If they want to say something that is not a swear word (not a bad word), they may say something like “darn it” or “darn,” although that can seem a little old-fashioned to some people nowadays.
Tim says, “Damn it!” and Pam asks, “What’s the matter?” meaning what’s the problem. Tim says, “It’s this copier.” The “copier” is the photocopy machine, what in many offices people call the “copy machine.” Tim says, “My original didn’t come out of the feeder and there’s a paper jam.” The “original” would be the document or other piece of paper that you are trying to make a copy of. The “feeder” (feeder) is the part of the copy machine where you put your paper into, the paper that you want to copy. For example, if you have 10 pages, you would put those 10 pages, all at once, into a feeder and the copy machine will take one page at a time and copy it. At least, most copy machines have feeders; not all of them do. A “jam” (jam) in this dialogue means a situation where a machine stops working because something inside of it is in the wrong position or the wrong place. We especially use this expression when we are talking about something that you put into a machine, for example, you’re putting paper into the copy machine and if the paper doesn’t go through correctly – if it gets “stuck,” we could say – if it stops moving inside the machine when it should continue to move, we will say that there is a jam – a paper jam. If you work with copy machines, you know this is a common problem, especially when they get very warm.
Pam says, “Let me see if I can clear it.” To “clear” something means, in this case, to fix the jam, to take out the thing that has caused the problem. Pam says, “This machine is really temperamental.” The word “temperamental” means something that only works some of the time, something that is difficult to operate correctly. It can also be used to describe someone who is perhaps a little unstable, someone who changes their mood very quickly. We might describe that person as being temperamental.
Tim says, “Tell me about it.” After Pam says machine is really temperamental, Tim uses an expression that shows that he agrees with Pam. It’s often something that you will say, this expression “tell me about it,” when it’s a negative thing and that you already know about it and you have a lot of, perhaps, experience with it.
Pam says, “Okay, I found your original, but it’s stuck.” We mentioned earlier that a paper jam is when paper gets stuck. “Stuck” means unable to move, something that is trapped in one place or position. Sometimes we use this expression when we’re trying to figure out a complicated problem. For example, a student is doing a math problem, let’s say an algebra problem, and he starts to solve the problem but after a few minutes he doesn’t know what to do. He might say, “I’m stuck” – I can’t move forward, I don’t know the answer. Here, the term refers to the paper that can’t move because it’s inside the machine. Pam says, “I’m afraid if I pull too hard, (the original – the paper) will tear (tear).” “Tear” means to be ripped into two or more pieces. This is a verb we use, for example, when you have a piece of paper and you do this [sound of paper being torn]. If you rip or tear the paper, the paper will now be in two different pieces. The word “tear,” like the word “feeder” that we mentioned earlier, has a couple of different meanings in English; take a look at our Learning Guide for some additional explanations.
Tim says, “Let me try,” meaning let me try to get the paper out of the machine. He then says, “I got it!” He was able to remove it. “Okay, I need to shrink the first page and adjust the contrast so that it is more readable.” To “shrink” means to make something smaller, to reduce the size. To “adjust the contrast” means to change the difference between two things, usually something that is white and black or light and dark. So, if you have a piece of paper where the writing isn’t very clear, you may increase the contrast so that the copier is able to copy more effectively. So, “contrast” is a difference between two things; when we’re talking about a copy machine, it refers to the black and the white on the page. Tim says, “Then I need to enlarge the second page.” To “enlarge” is the opposite of to reduce or to shrink; to “enlarge” means to make larger, to make something bigger. “After that,” Tim says, “I need to make 20 collated copies.” Something that is “collated” is something that is put into the correct order. So, if you have three pages that you are copying, and you need to make 10 copies for a meeting you’re going to, “collated copies” would be copies where the pages (one, two, and three) are in the correct order. Not 10 pages with page one, 10 pages with page two, 10 pages with page three; that would be un-collated.
Tim says that he needs 20 collated copies, but Pam says, “Oh, oh, don’t look now.” “Oh, oh” is when something wrong happens – something bad happens, and you are indicating that. The expression “don’t look now” is a phrase used to tell someone that there’s a problem that you know will make him or her angry or upset. Pam says, “don’t look now, but the toner light is on.” The “toner” (toner) is the “ink,” the black stuff or the colored stuff that is used in printers, fax machines, and copiers. Usually you can only get so many copies from one cartridge of toner. A “cartridge” is the package, the small, often plastic box where the ink (the toner) is kept. So, if your toner “runs out” (if there’s no more), you’ll have to put in a new toner cartridge.
Tim says, “Is there anything else that can go wrong with this stupid copier?!” Notice Tim says the “stupid copier,” we often say that about a thing when we are frustrated with it. Of course, the copier isn’t stupid; it isn’t anything at all, it’s not human. Maybe Tim’s the stupid one here!
Pam says, “Don’t tempt fate.” The expression “to tempt fate” means to take a risk or do something knowing that something bad may happen. Pam says, “It could be worse (the situation could be worse). The whole thing (the entire copy machine) could break down!” To “break down” is a two-word phrasal verb for a machine or a car to stop working, something that stops working and needs to be fixed. We use this verb in talking about a car: “My car broke down,” meaning something bad happened, something went wrong and the car needs to be fixed.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Tim: Damn it!
Pam: What’s the matter?
Tim: It’s this copier. My original didn’t come out of the feeder and there’s a paper jam.
Pam: Let me see if I can clear it. This machine is really temperamental.
Tim: Tell me about it.
Pam: Okay, I found your original, but it’s stuck. I’m afraid if I pull too hard, it’ll tear.
Tim: Let me try. I got it! Okay, I need to shrink the first page and adjust the contrast so that it’s more readable. Then I need to enlarge the second page. After that, I need to make 20 collated copies.
Pam: Oh, oh, don’t look now, but the toner light is on. You’ll need to put in a new cartridge.
Tim: Is there anything else that can go wrong with this stupid copier?!
Pam: Don’t tempt fate. It could be worse. The whole thing could break down!
[end of dialogue]
The script for this episode was written by the never temperamental Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
copier – a photocopy machine; a copy machine; a machine that makes a copy of the text or image on a piece of paper so that it appears on another piece of paper
* Can your copier make color copies or only black and white copies?
original – the document or other piece of paper that one wants to make copies of
* I accidentally left the original in the copier after I was done making copies.
feeder – the part of a copier that one puts papers into, so that the machine takes one piece of paper at a time and makes copies quickly
* This feeder can take up to 50 pieces of paper at a time.
jam – a situation where a machine stops working because something inside it is in the wrong position or in the wrong place
* The printer has a jam because it tried to take two pieces of paper at once.
to clear (something) – to fix a jam, taking out the thing that caused the problem so that the machine can work again
* They weren’t able to clear the papers out of the fax machine themselves, so they had to call someone to repair it.
temperamental – something that only works some of the time; something that is difficult to operate
* His car is temperamental, and if you don’t turn the key just right, the car won’t start.
stuck – not able to move; trapped in one place or position
* The little girl got her hand stuck inside a toy and had to ask her mother for help.
to tear – to be ripped into two or more pieces
* Her skirt tore when she accidentally closed the car door on it.
to shrink (something) – to make something become smaller
* Our clothes shrank when we washed them in very hot water.
contrast – the difference between two things, especially between white and black or between light and dark
* Could you please adjust the contrast on my computer screen so that it’s easier to read?
to enlarge (something) – to make something bigger
* That’s such a beautiful photo! We should enlarge it and hang it on the living room wall.
collated – put into the correct order, so that when making 3 copies of a 3-page document they are sorted as 123, 123, and 123, not 111, 222, and 333
* The copies are already collated, so you just need to staple them together.
don’t look now – a phrase used to tell someone that there is a problem when you know that it will make him or her angry or upset
* Don’t look now, but your son just came home and his hair is green!
toner – ink that is used in printers, fax machines, and copiers
* The documents aren’t printing well because we ran out of toner.
cartridge – the small plastic box that holds toner (ink) and is placed in a printer, fax machine, or copier so that it can print text or images onto pieces of paper
* This printer has one black-and-white cartridge and one color cartridge.
to tempt fate – to take a risk or do something knowing that something bad might happen
* You’ve already won more than $4,000. Don’t tempt fate by continuing to play. Stop now and take home the money before you lose it all.
to break down – for a machine or car to stop working and need to be fixed or replaced
* Their car broke down in the middle of the freeway and they had to call the police for help.
Comprehension Questions
1. What is wrong with the copier?
a) The papers got stuck.
b) The contrast isn’t readable.
c) The machine broke down.
2. What is inside a cartridge?
a) Jam.
b) Collated copies.
c) Toner.
Answers at bottom.
What Else Does It Mean?
feeder
The word “feeder,” in this podcast, means the part of a copier that one puts papers into, so that the machine takes one piece of paper at a time and makes copies quickly: “Why don’t you use the feeder instead of putting the papers in one at a time?” A “bird feeder” is something that holds seeds or other food for birds to eat: “They have five bird feeders hanging on trees in their backyard, because they really like to look at the birds that come to eat there.” Finally, a “feeder school” is an elementary or middle school where all the students go to a particular high school: “Laurelhurst Middle School is a feeder school for Grant High School, which is in the same neighborhood.”
tear
In this podcast, the verb “to tear” means to be ripped into two or more pieces: “The newspaper was torn while the little boys were playing with it.” The phrase “to tear (something) up” means to rip something into many small pieces, usually because one doesn’t want anyone else to see it: “It was such a horrible photo that she tore it up and threw it away.” The phrase “to tear (something) out of (something)” is used to talk about taking a piece of paper out of a binder, folder, notebook, or something similar: “She signed her name and then tore the check out of her checkbook.” The phrase “to be torn,” or “to be torn between (something) and (something)” means to not be able to decide between two things because they are both appealing for different reasons: “He’s torn between traveling the world and staying in school.”
Culture Note
Most offices in the United States have copiers, but the people who work with them often get “frustrated” (angry or upset because something is not the way that one wants it to be) when they don’t work “properly” (correctly, the way that something should be). Sometimes copiers “malfunction” (don’t work correctly) because people don’t know how to use the advanced “functions” (special things that a copier can do).
“Fancy” (very nice, with lots of options) copiers have many “paper trays,” where paper is kept for making copies. Often people choose the wrong paper tray, for example printing on “legal” (8.5”x14”) instead of “letter” (8.5”x11”) paper. Usually offices have paper trays with different sizes, types, and color paper. Sometimes a paper tray has “letterhead” (the official paper that a company uses for its documents, usually with the logo, address, and phone number at the top).
Most copiers can also make “double-sided copies” (papers that have text or images on both sides), either from “single-sided” or double-sided originals. When people try to do it “manually” (without a machine’s help), they often put the papers in “upside-down” (with the top side facing down and the bottom side facing up) or “backwards” (with the top at the bottom and the bottom at the top), so that the second side is accidentally printed on top of the text or images that were printed for the first side.
Finally, many copiers have “finishing options” for completing large documents. For example, an “automatic stapler” is the part of a machine that “staples” (puts a small piece of metal through many pages and folds the ends back so that the papers are held together). But the papers must be put in correctly, or else the staples will be in the wrong part of the page!
Comprehension Answers
1 - a
2 - c