= 0438
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 438: Renting an Apartment.
This is English as a Second Language Podcast number 438. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode, which contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension questions, and a transcript of this complete episode.
Today’s episode is a dialogue between Heather and Sam, talking about renting an apartment. Let’s get started.
[start of dialogue]
Heather: Hi, are you the apartment manager? I saw the vacancy sign outside and I’m looking for an apartment.
Sam: Yes, I’m Sam. We have one unit available right now. When are you looking to move in?
Heather: The lease on my apartment is up soon, so I’d like to move in the first of the month.
Sam: Okay, follow me and let me show you the unit. Each unit gets one parking space in the garage, and there are laundry facilities on the first floor. The landlord pays for the gas, but the tenant pays for all other utilities. Here’s the unit. Take a look around.
Heather: Oh, this is nice. Is this a furnished unit?
Sam: It can be furnished or unfurnished, your choice. Since it’s an end unit, there’s only one common wall.
Heather: This apartment is exactly what I’m looking for. How much is the rent?
Sam: It’s $900 a month and we require a 12-month lease. To move in, you’ll need to have the first and last month’s rent, plus a security deposit.
Heather: How much is the security deposit?
Sam: It’s $450.
Heather: Okay, I’ll think it over and get back to you. Thanks for your time.
Sam: These units go fast, so if you’re interested, I suggest that you jump on it.
Heather: Thanks, I’ll keep that in mind.
[end of dialogue]
Heather begins the dialogue by asking Sam, “Are you the apartment manager?” In an apartment building – which is, of course, a building with many different places for people to live – the manager is the person who takes care of the building, the person who takes care of problems in the building. Heather says, “I saw the vacancy sign outside and I’m looking for an apartment.” The “vacancy (vacancy) sign” is a sign that says that there is a room or rooms for rent – that are available. You will see a vacancy sign, for example, in front of a hotel; that means the hotel has rooms to rent. If it says “no vacancy,” it has no rooms to rent. For an apartment building, a vacancy sign means that there is at least one apartment that is available to rent.
Sam says, “Yes, I’m Sam. We have one unit available right now.” A “unit,” in this dialogue, means one of the apartments; it refers to an apartment. Sometimes people may even say an “apartment unit,” or just “the unit.” It’s a term that you will hear more from someone who works in the apartment business, like a manager, or someone who works in real estate. “Unit” has several different meanings in English; take a look at the Learning Guide for some additional explanations.
Sam says, “When are you looking to move in?” meaning when do you want to – when are you looking to move in. “To move in” means that you want to take all of your furniture and things, and bring them to the apartment to live. When do you want to start renting the apartment? Heather says, “The lease on my apartment is up soon.” A “lease” (lease) is a legal contract – a legal agreement – between, in this case, the person who owns the apartment building and you, the person renting the apartment. You can have a lease for a house; you can have a lease for a car. You can rent your car for a day or a week or several months. The lease on Heather’s apartment is up soon. “To be up,” in this case, means to end, to finish, to expire: “The president’s term is up in January of next year.” The term is up – the term is over; it is finished. Heather says, “I’d like to move in the first of the month,” meaning the first day of the month, so January 1st or February 1st, and so forth. In the U.S., it’s common for leases to begin at the first of the month; sometimes they begin on the 15th of the month, so halfway into the month.
Sam says, “Okay, follow me and let me show you the unit. Each unit gets one parking space in the garage,” meaning one place for you to park one car. He also says that there are laundry facilities on the first floor. “Laundry” is another word for clothes that you want to wash – dirty clothes. Someone says “I have to go do the laundry,” they mean “I have to go wash my clothes.” So, “laundry facilities” are washers and dryers for clothing. Many apartment buildings in the U.S. have laundry facilities in the building. If there is no laundry facility – place for you to wash your clothes – then you have to go to what’s called a “Laundromat,” which is a place separate from the building that anyone can come and wash their clothes and dry them.
Sam says, “The landlord pays for the gas, but the tenant pays for all other utilities.” The “landlord” is the person who actually owns the apartment building, or the house, or whatever is being rented. A business building would have a landlord, for example. The “manager” is the person who takes care of the problems – the day-to-day problems – the everyday problems in the building, but the landlord is the person who actually owns the building. The “tenant” (tenant) is the person who is renting the apartment or the house. So in this case, it would be Heather; she wants to rent the unit from the landlord.
So the landlord pays for the gas – the natural gas, but the tenant pays for all other utilities. The word “utilities,” when we’re talking about apartments or houses, refers to the water, the electricity, the gas, other things that a person needs to live on; things that are services provided by some company or by the government. So, for example, for my house we have a gas bill, we have an electricity bill; those are utilities. We also have a water bill and a bill for the garbage collection. So, these things must be paid for by Heather.
Sam says, “Here’s the unit. Take a look around.” Heather says, “Oh, this is nice. Is this a furnished unit?” When something is “furnished,” that means that it has furniture in there, that the landlord has put in a bed, and a sofa, and a table and chairs, and so forth. Most apartments in the U.S., however, are “unfurnished,” meaning they’re empty; you have to bring your own things into the apartment. Sam says, “It can be furnished or unfurnished, your choice.” Furnished is more common for apartments for students, who may not have things to move into the apartment – furniture – especially if they live in a different city from where they are renting.
Sam says, “Since it’s an end unit (meaning it’s at the edge of the building – there isn’t another apartment on the other side), there’s only one common wall.” A “common wall” is a wall that you share with another apartment. So, if you have an apartment on the first floor in between two other apartments, you probably have at least two common walls: one for the apartment on the right, one for the apartment on the left. Hopefully, the walls are thick so you don’t hear the person next to you. That’s sometimes a problem with apartments, especially the apartments I used to rent when I was renting back as a student.
Heather says, “This apartment is exactly what I’m looking for (it’s just what I want). How much is the rent (how much money do I have to pay each month)?” Sam says, “It’s $900 a month and we require a 12-month lease.” So she must agree to rent it for a whole year at $900 each month. “To move in,” Sam says, “you’ll need to have the first and last month’s rent, plus a security deposit.” That’s a very common policy in the U.S. If you are going to rent an apartment for one year, you have to pay the first and the last month’s rent right away, as well as a security deposit. A “security deposit” is money that you give the owner of the property – the landlord – to hold in case there are any problems, in case, for example, that you damage the apartment. The word “security,” here, doesn’t mean safety; it means something that I am holding of yours just to be sure that nothing goes wrong. So, the security deposit that Heather has to pay is $450. Security deposits are usually about half of the rent, sometimes less.
Heather says, “Okay, I’ll think it over (I’ll think about it) and get back to you.” “To get back to someone” means to give an answer to someone at a later time. Someone asks you to go to a party, and you say, “Well, I’ll get back to you on that. I’ll call you tomorrow.”
Sam says, “These units go fast (meaning they rent quickly), so if you’re interested, I suggest that you jump on it.” “To jump on it” means to do it right away, not to wait. Especially if you are talking about something you are going to buy or something that you have to pay for, if someone says “you should really jump on it,” it’s a good deal – it’s a good price. That is the meaning of the expression, to do it right away.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Heather: Hi, are you the apartment manager? I saw the vacancy sign outside and I’m looking for an apartment.
Sam: Yes, I’m Sam. We have one unit available right now. When are you looking to move in?
Heather: The lease on my apartment is up soon, so I’d like to move in the first of the month.
Sam: Okay, follow me and let me show you the unit. Each unit gets one parking space in the garage, and there are laundry facilities on the first floor. The landlord pays for the gas, but the tenant pays for all other utilities. Here’s the unit. Take a look around.
Heather: Oh, this is nice. Is this a furnished unit?
Sam: It can be furnished or unfurnished, your choice. Since it’s an end unit, there’s only one common wall.
Heather: This apartment is exactly what I’m looking for. How much is the rent?
Sam: It’s $900 a month and we require a 12-month lease. To move in, you’ll need to have the first and last month’s rent, plus a security deposit.
Heather: How much is the security deposit?
Sam: It’s $450.
Heather: Okay, I’ll think it over and get back to you. Thanks for your time.
Sam: These units go fast, so if you’re interested, I suggest that you jump on it.
Heather: Thanks, I’ll keep that in mind.
[end of dialogue]
The script for this episode was written by our very own Dr. Lucy Tse.
Well, our time is up. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
apartment manager – a person whose job is to take care of problems in an apartment building, collect the rent, and find people to live in the building
* When our toilet stopped working, we called the apartment manager.
vacancy – the availability of an apartment or hotel room; an empty apartment or hotel room
* Last weekend, so many people came to town for the university’s graduation ceremony that there were no vacancies in any of the hotels.
unit – one of many apartments in a building
* Are you interested in a one-bedroom or a two-bedroom unit?
to move in – to begin to live in a new place; to bring one’s furniture, clothes, and other things to the new place where one will be living
* Before moving into our new house, we need to pack all of our clothes and books.
lease – a legal agreement between the owner of a house, apartment, or other property and the person who is going to live there or use that property, paying a certain amount of money for a certain period of time
* According to their lease, they aren’t allowed to have a cat in their apartment.
to be up – to end; to finish; to expire
* His contract job is up at the end of the year and then he’ll have to find a new job.
the first of the month – the first day of a month (January 1, February 1, etc.)
* If they don’t pay their rent by the first of the month, they have to pay a $25 late fee.
laundry facilities – the place where there are washers and dryers, where people can wash their clothes
* This apartment doesn’t have a washer and dryer, but everyone who lives in this building can use the laundry facilities on the first floor.
landlord – a person who owns a home, apartment, or other property and lets someone else live there or use the space, who pays a certain amount of money for a certain period of time
* Xena is a great landlord because she always fixes things right away.
tenant – a person who lives in a home or apartment owned by another person, paying a certain amount of money for a certain period of time
* Most of the tenants in that apartment building are college students.
utilities – water, electricity, natural gas, and other things that a person needs to live and that must be paid each month
* Even though it’s really hot outside, we’re not using air conditioning because we want to save money on our utilities.
furnished/unfurnished – with or without furniture, especially in a room or apartment that is being rented to someone
* If you rent an unfurnished apartment, you’ll have to buy a couch, bed, dresser, table, and more. I suggest renting a furnished one instead.
end unit – an apartment that is at the edge of a building, without another apartment on one side
* I want to live in an end unit, because that way, I won’t have as many noisy neighbors.
common wall – a wall shared by two or more apartments or rooms; a wall between two apartments or rooms
* The common wall between our apartments is very thin, so we can hear almost everything our neighbors say to each other!
rent – the money paid every month so that one can live in a home or apartment owned by someone else
* Her landlord just raised the rent from $1,100 to $1,350, so she’s going to try to move to a less expensive part of the city.
security deposit – money that one gives to the owner of a property before moving in so that if there are problems or damage while one is living there the owner gets to keep the money, but if there are no problems or damage the money is given back to the renter
* To rent an apartment in that building, you have to pay a $350 security deposit, but you can get all of the money back when you move out if you’ve taken good care of the apartment.
to get back to (someone) – to give someone a response or answer after a certain period of time
* Let me check my calendar and get back to you once I know whether I’m available on Thursday.
to jump on (something) – to take advantage of an opportunity quickly, without waiting too long
* I don’t like my current job, so if a new one comes along, I’m going to jump on it.
Comprehension Questions
1. How much will Heather have to pay to move into the apartment?
a) $900.
b) $1,350.
c) $2,250.
2. Why does Sam suggest that Heather jump on it?
a) Because she needs to jump up and down to test the floors.
b) Because she needs to act quickly if she wants the apartment.
c) Because she needs to jump over the apartment’s common wall.
Answers at bottom.
What Else Does It Mean?
unit
The word “unit,” in this podcast, means one of many apartments in a building: “I know you’re on the third floor, but which unit do you live in?” A “unit” can also be a department, or a group of people working together on something: “The police force has a children’s unit that takes children out of dangerous family situations.” Or, “The hospital is going to build a bigger building for its cancer unit.” In a factory, a “unit” is one product that is made: “This factory makes 10,000 units each month.” Finally, the phrase “unit price” is the cost per piece of something: “A big box of diapers costs $33, but the unit price is low at just $0.17 per diaper.”
to be up
In this podcast, the phrase “to be up” means to end, finish, or expire: “The sale is up on Monday, so we need to go to the store this weekend if we want to buy an inexpensive refrigerator.” The phase “to be down” means to be depressed, or to feel very sad: “When I lost my job, I was down for months.” The phases “to be over” and “to be through” mean to be finished, especially when talking about a romantic relationship: “Their marriage is over. They’re getting a divorce next month.” Or, “That’s it! We’re through! I don’t want to date you anymore.” Finally, the phrase “to be away from (something)” means to be on vacation or out of the office for a period of time: “I’ll be away from my desk most of the afternoon because I have meetings on another floor.”
Culture Note
“Discrimination” is the practice of treating someone unfairly because of one or more “characteristics” (things that describe a person), such as “gender” (whether one is a man or a woman), “nationality” (what country one belongs to), “race” (skin color), “disability” (something that is wrong with one’s body) or “family status” (whether one is single, married, or divorced, or whether one has children). Discrimination is “illegal” (against the law) when “hiring” (giving someone a job), and it is also illegal when deciding who will live in an apartment or house.
The Fair Housing “Act” (law) “prohibits” (doesn’t allow) housing discrimination. According to the Act, a landlord cannot “deny” (say no to) a person’s “application” (written request) for housing based on the characteristics listed above. For example, a landlord cannot choose to let only white people live in an apartment building. A landlord cannot deny an application just because someone has children, either.
Sometimes people with disabilities need to have special “accommodations,” or things that are changed in a house or apartment so that, for example, a person in a “wheelchair” (a chair on wheels, used by someone who cannot walk) can live there. A landlord cannot deny a housing application from a disabled person if he or she is willing to make the necessary accommodations to the apartment or house.
People who believe that they are the “victims” (people who has been hurt by another person’s illegal action) of housing discrimination can “file” (submit) a “complaint,” or a document that describes the situation and says why they think the Fair Housing Act has been “violated” (not followed as the law requires). Then a government agency will “investigate” (research) the complaint.
Comprehension Answers
1 - c
2 - b