= 0441
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 441: Preparing Food for Cooking.
This is English as a Second Language Podcast episode 441. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. You can download a Learning Guide for this episode, an 8 to 10 page guide that will help you improve your English even faster.
This episode is called “Preparing Food for Cooking.” It’s going to describe a lot of common vocabulary we use in English to talk about cooking food. Let’s get started.
[start of dialogue]
Marissa: How can I help?
Juan Carlos: Um...why don’t you iron the tablecloth and set the table?
Marissa: I already did that. I want to help with the cooking.
Juan Carlos: Okay, you can scrub these potatoes, peel the carrots, and rinse these grapes.
Marissa: All right, I’ll do that, but I think you’re just giving me the scut work. I want to do some real cooking.
Juan Carlos: Well okay, I guess you could cut up this chicken and then chop these vegetables. After that, you can sauté the vegetables in this pan.
Marissa: Great! Now, how do you sauté? I’ve never done it before.
Juan Carlos: What?! Forget it. You can steam the vegetables instead.
Marissa: Okay, just show me how.
Juan Carlos: Never mind. Here, just beat these eggs and slice these onions. When you’re done, you can toss that salad.
Marissa: But I want to whip up some gourmet dishes. When can I cook?
Juan Carlos: That’s a good question. Ask me again when you’ve learned how!
[end of dialogue]
The dialogue between Marissa and Juan Carlos begins by Marissa saying, “How can I help you,” which is a polite way of someone saying in what way can I be of assistance – how can I help you with what you are doing. Juan Carlos says, “Um...why don’t you iron the tablecloth and set the table?” Juan Carlos is cooking the food and his wife, I guess, is asking if she can help him. Juan Carlos says, “why don’t you iron the tablecloth?” “To iron” means to take a piece of clothing or a piece of fabric and put a hot object on it so that it is straight and smooth; it does not have any what we would call “wrinkles,” or lines in it. “To iron” is a verb; there’s also the noun “iron,” which is the thing that you heat up, usually nowadays by plugging it in. It’s an electrical device. The “tablecloth” is a large cloth – a large piece of fabric that you put over a table, usually for some sort of formal dining situation. If you go to a nice restaurant they will usually have tablecloths. Juan Carlos also suggests that she set the table. “To set the table” means to put the plates, cups, napkins, spoons, forks, knives – all of those sorts of things that you need to eat on the table. Usually, this is something you do before the person brings out the food to eat. In my family, growing up, it was always my job to set the table for dinner. Probably because that’s the easiest thing for a child to do, and not being the brightest person, my parent’s didn’t want me to make any mistakes!
So, Juan Carlos is asking Marissa to help him. Marissa says, “I already did that. I want to help with the cooking.” Juan Carlos says, “Okay, here, you cook the rest of the meal” – no, he doesn’t say that! He actually says, “Okay, you can help, you can scrub these potatoes.” “To scrub” (scrub) means to move your hand or use some sort of tool and move it back and forth against something quickly in order to clean it. So, scrubbing the vegetables is putting them under water, rubbing them so that the dirt comes off of them. Juan Carlos is asking Marissa to scrub the potatoes, peel the carrots, and rinse these grapes. “To peel” (peel) is a verb we use in cooking to talk about removing the skin from a fruit or vegetable, to remove the outside of something usually with a small knife. So, to peel the carrots would mean to use a small knife or a sharp object that we would call a “peeler” to take off the outer layer – the outer skin of the carrot. A “carrot” is a long, orange-colored vegetable. “Rinsing” the grapes means cleaning them by running water over them. “Grapes” are, of course, small pieces of fruit from which we make wine – or one way of making wine, anyway. You can use that same verb, “to rinse,” when you are talking about, for example, washing your hair. I could say, “I rinsed my hair this morning when I took a shower.” I could say that, but I don’t have any hair so that would be a lie!
Marissa says, “All right, I’ll do that, but I think you’re just giving me the scut work.” “Scut (scut) work” means work that is the most unpleasant to do, the worst job. Someone who gives you scut work is giving you something that is usually easy but it’s not very pleasant – it’s not very fun to do. Marissa says, “I want to do some real cooking.” Juan Carlos says, “Well okay, I guess you could cut up this chicken.” “To cut something up,” or “to cut up something” is a two-word phrasal verb meaning to cut something into smaller pieces, usually with a knife. “Cut” has several different meanings in English; take a look at our Learning Guide for some additional explanations.
Juan Carlos also asks Marissa to chop these vegetables. “To chop” (chop) also means to cut something into smaller pieces, usually with a knife, and with a very quick motion – quick, “repetitive,” we would say, motion; you repeat the same thing over and over again. So, if you have an onion and you want the onion to be in very small, little pieces, you would use a knife and you would chop the onion; you would move the knife up and down quickly several times, using the same motion to cut the onion. “Chop” usually means that you are making something into very small pieces – you are cutting it into small pieces.
Juan Carlos says, “After that, you can sauté the vegetables in this pan.” “To sauté” (sauté – with an accent over the “e” because it’s a word that comes originally from French) means to cook something, often vegetables or meat, in hot oil or butter until it is either soft if it’s vegetables, or browned if it’s meat. Sauté is usually done in a “pan,” which is the thing you put on top of the fire in order to cook food. Sautéing is usually something that is done very quickly in the pan.
Marissa says, “Great! Now, how do you sauté,” meaning how does one sauté – how does someone who cooks sauté. “I’ve never done it before.” Juan Carlos says, “What?! Forget it,” meaning he can’t believe Marissa doesn’t know how to sauté. He says, “You can steam the vegetables instead.” “To steam” (steam) something means to cook something by putting it over boiling water. It isn’t in the water; it’s in something else, but the heat from the boiling water – the vapor – comes up into the food and cooks it, into the pan or whatever it is that you are using to put the food in. But, “steaming” means that you don’t put it in water, but the heat of the water cooks the food. We often steam vegetables, for example. You could also steam fish.
Juan Carlos is asking Marissa to steam the vegetables, and Marissa says, “Okay, just show me how” – tell me how to do it. Juan Carlos says, “Never mind,” meaning forget it, don’t worry about it, I don’t want you to do it. He says, “Here, just beat these eggs and slice these onions.” “To beat” an egg, or to beat anything in cooking means to stir something very quickly; to mix it very quickly, often in order to put more air into the food. “Beat” has several different meanings in English; take a look at the Learning Guide for some additional explanations.
Juan Carlos wants Marissa also to “slice these onions.” “To slice” (slice) is another verb we use to refer to cutting something. This is when you cut something into very thin, flat pieces. So, you might slice the bread. You have a piece of bread, what we would call a “loaf” (loaf) of bread, and then you slice it – you cut it so that it is in thin, flat pieces. “When you’re done,” Juan Carlos says, “you can toss that salad.” “To toss” (toss) something is to mix things together – mix different pieces of food together, to stir them together. When you toss a salad, you take all of the elements – all of the ingredients, the food that makes up the salad, and you mix them together.
Marissa says, “But I want to whip up some gourmet dishes. When can I cook?” “To whip up” is a two-word phrasal verb meaning to make something to eat very quickly, in very little time. Someone says, “Oh, I’ll whip up some food for dinner,” they mean they will cook food very quickly or get dinner ready very quickly. “Gourmet” (gourmet) means very good tasting, delicious, high quality food. “Gourmet dishes” refer to the food that you are cooking. A “dish” is one type of cooked or prepared food. At Thanksgiving in the United States, we have different dishes: turkey, potatoes, pumpkin pie – these are dishes.
Marissa wants to whip up some gourmet dishes. Juan Carlos says, “Ask me again when you’ve learned how!” because Marissa doesn’t know how to do even the most basic things in cooking – kind of like me!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Marissa: How can I help?
Juan Carlos: Um...why don’t you iron the tablecloth and set the table?
Marissa: I already did that. I want to help with the cooking.
Juan Carlos: Okay, you can scrub these potatoes, peel the carrots, and rinse these grapes.
Marissa: All right, I’ll do that, but I think you’re just giving me the scut work. I want to do some real cooking.
Juan Carlos: Well okay, I guess you could cut up this chicken and then chop these vegetables. After that, you can sauté the vegetables in this pan.
Marissa: Great! Now, how do you sauté? I’ve never done it before.
Juan Carlos: What?! Forget it. You can steam the vegetables instead.
Marissa: Okay, just show me how.
Juan Carlos: Never mind. Here, just beat these eggs and slice these onions. When you’re done, you can toss that salad.
Marissa: But I want to whip up some gourmet dishes. When can I cook?
Juan Carlos: That’s a good question. Ask me again when you’ve learned how!
[end of dialogue]
The script for this episode was whipped up by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2009, by the Center for Educational Development.
Glossary
to iron – to flatten out a piece of fabric so that it is not wrinkled (does not have lines) by moving a hot, flat piece of metal over the top of it
* My shirt would look much better if I ironed it.
tablecloth – a large piece of fabric placed over a dining table for decoration and to protect the table
* She was very embarrassed when she spilled a glass of red wine onto the white tablecloth at her friend’s house.
to set the table – to put silverware, napkins, plates, cups, and other things on the table before people eat
* Please set the table for six people tonight.
to scrub – to move one’s hand or a tool against something quickly and with a lot of strength to clean it
* The pot was so dirty that he had to scrub it for almost 10 minutes.
to peel – to remove the skin from a fruit or vegetable; to remove the outer layer of something, usually by using a small knife or a special tool
* Do you peel peaches or do you eat them with the skin?
to rinse – to clean something by running water over it
* We ran out of hot water while I was shampooing, so I had to rinse my hair in cold water.
scut work – the worst work; the most unpleasant things to do
* Why do you get to do all the interesting things while I have to do the scut work, like making photocopies?
to cut up (something) – to cut something into smaller pieces, usually using a knife
* Please cut up the banana so that we can put the pieces on top of our cereal.
to chop – to cut something into many smaller pieces, usually using a knife and a quick, repetitive motion
* Please chop the nuts into very small pieces.
to sauté – to cook something, usually vegetables, in hot butter or oil until it is soft
* The first step in making the sauce is to sauté onions and mushrooms in butter.
to steam – to cook something by putting it over boiling water so that it does not touch the water, but is heated by the water vapor
* For dinner tonight, let’s grill some chicken, cook a pot of rice, and steam some broccoli.
to beat – to stir something very quickly, mixing a lot of air with it
* Will you use an electric mixer or will you beat the mixture for the cake by hand?
to slice – to cut something into flat, thin pieces
* Does the bakery slice the bread or do you have to do it by yourself?
to toss – to stir something lightly so that pieces are distributed evenly
* He tossed the pasta with olive oil, garlic, salt, pepper, and Parmesan cheese.
to whip up – to make something to eat in a very little time
* On busy weeknights, she can whip up a meal for her family in just 15 minutes.
gourmet – related to very delicious, high-quality food
* I prefer going to gourmet restaurants but my wife prefers to eat home-cooked food.
dish – one type of cooked or prepared food
* Roasted turkey, mashed potatoes, and pumpkin pie are typical dishes for Thanksgiving in the United States.
Comprehension Questions
1. Which of these jobs is scut work?
a) Sautéing vegetables.
b) Whipping up gourmet dishes.
c) Setting the table.
2. Which of these foods might need to be peeled?
a) Potatoes.
b) Chicken.
c) Salad.
Answers at bottom.
What Else Does It Mean?
to cut up
The phrase “to cut up,” in this podcast, means to cut something into smaller pieces, usually using a knife: “I always start crying whenever I cut up onions.” The phrase “to cut a deal” means to make a business transaction, selling or buying something: “The singer cut a deal with the record company to record her first CD.” The phrase “to cut (someone) a check” means to write a check to someone: “After the flood, the insurance company cut them a check for $4,600 to repair the damage in their house.” Finally, the phrase “to cut corners” means to do something quickly or inexpensively by skipping steps, even if the thing is not done well as a result: “The inspectors said that the building wasn’t safe, because the architects cut corners when designing it.”
beat
In this podcast, the verb “to beat” means to stir something very quickly, mixing a lot of air with it: “We had to beat 10 egg whites to make that lemon pie.” The verb “to beat” also means to hit someone or something very hard and repeatedly: “The judge said: ‘A man should never beat his wife.’” The verb “to beat” can mean to win when playing or competing against another person or team: “The boys were really happy when they beat the other school’s football team.” Finally, the phrase “to beat (something)” means to do something better or faster than it had previously been done: “Yesterday, Jason beat his old personal record of running one mile in 5:03.” Or, “Do you think anyone will ever beat that score in the video game?”
Culture Note
Americans often complain that they don’t have enough time to cook, so “grocery stores” (stores where food is sold) sell many “prepared foods,” or foods that are already made and often just need to be “heated up” (warmed) and “served” (given to people to eat).
In the “produce” (fruits and vegetables) section, there are many “packaged” (in bags, boxes, or cans) salads where the lettuce or spinach leaves have already been washed and cut. There are also containers of cut-up fruit and vegetables. In the meat section, people can buy pre-cooked and pre-cut chicken breasts. And in the frozen foods “aisle” (one row in a store with shelves on either side), people can get many “frozen dinners,” which are small boxes with enough frozen food for one person to put in the oven or microwave.
Many grocery stores have “deli counters,” or a part of the store where meats and cheeses are cut for customers. Often these deli counters offer warm cooked food that people can buy, take home, and eat without even having to heat it up first. Many deli counters have “rotisserie” (cooked while moving in a circle over a fire) chickens, “fried” (cooked in hot oil) chicken, and potatoes. Gourmet grocery stores have even more prepared foods, including pasta salads, fish, meats, vegetables, desserts, and almost everything else a person could want to eat. Some of these stores have “salad bars,” too, where people can fill a container with different kinds of vegetables and then pay based on how much the container weighs.
Prepared foods are more expensive than “staples” (basic foods) that people buy and cook with at home, but many Americans are willing to pay for the “convenience” (the ease of doing something).
Comprehension Answers
1 - c
2 - a