= 0445
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 445: Problems with Drugs and Medical Devices.
This is English as a Second Language Podcast episode 445. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download a Learning Guide for this episode, an 8- to 10-page guide that contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension questions, and, best of all, a complete transcript of everything we say on this episode.
This episode is called “Problems with Drugs and Medical Devices.” It’s a conversation between Suzanne and Abdul using a lot of vocabulary that we might find in a hospital or in a medical situation. Let’s get started.
[start of dialogue]
Suzanne: Don’t take that! I’m reading an article in the newspaper about all of the drugs and medical devices that have been recalled in the past year and you wouldn’t believe how long this list is.
Abdul: I’m just taking something for my headache. I’m sure this medicine is fine.
Suzanne: Don’t be so sure. I’m just reading about this drug that was contaminated and before it was recalled, it caused 13 deaths.
Abdul: Contaminated drugs are one in a million. Now can I take my medicine?
Suzanne: Listen to this. Over 400 people had terrible side effects before this drug was recalled, and a drug recalled six months ago causes birth defects. Here’s a medical device for people with heart problems that’s defective and eight people died as a result.
Abdul: Okay, I’ve heard enough.
Suzanne: No, wait, there’s more. You’ve got to see this list of alerts that the government issued warning people against over-the-counter drugs like the one you’re about to take. You’d better check to see if it’s on this list.
Abdul: Don’t be ridiculous. I’ve been taking this for months. If there were something wrong with it, don’t you think the pharmaceutical company would have taken out full-page ads in the papers?
Suzanne: I doubt it. Do you think they want to encourage litigation?
Abdul: Here, you check it against that list. If you find it on there, you can say you’ve saved my life!
[end of dialogue]
Our dialogue begins with Suzanne telling Abdul, “Don’t take that!” What she is talking about here is a pill that Abdul is about to swallow. We usually talk about drugs using the verb “to take” – “to take drugs,” “to take your drugs.” This means to, usually, to swallow a pill. Suzanne says to Abdul, “Don’t take that! I’m reading an article in the newspaper about all of the drugs and medical devices that have been recalled in the past year.” “Drugs,” as you probably know, is just another word for medicine, usually chemical substances that you swallow to make you feel better, although drugs can also refer to things that you get, for example, in a shot, when the doctor takes a needle and puts it into your arm or other parts of your body. “Medical devices” is a general term referring to a piece of electronics or other equipment that helps you do better in terms of your health. For example, if you have a bad heart, you may have a “pacemaker,” which is a small electronic device they put into your body to help your heart. That’s a medical device. To “recall,” in this case, means for a company to say that there is some problem with their drug, or some problem with their medical device, or whatever they sell, and you need to bring it back to where you bought it and get a new one or get your money back. These so-called “recalls” are not too common, but it does happen when a company makes something that they discover later is not safe. They will do a recall – they will recall the item. “Recall” has a couple of different meanings in English; take a look at our Learning Guide for some additional explanations.
Well, Suzanne is worried about the drugs and medical devices that have been recalled in the past year; she says, “you won’t believe how long this list is.” The expression “you won’t believe” is often used when you are telling someone something that you think is surprising. Abdul, however, says, “I’m just taking something for my headache. I’m sure this medicine is fine.” “Medicine,” again, is another word for drugs. Suzanne says, “Don’t be so sure,” meaning maybe you are wrong. “I’m just reading about this drug that was contaminated and before it was recalled, it caused 13 deaths.” To be “contaminated” means that there is something dirty, something impure, or perhaps even poisonous in a food or a drug. If a drug is contaminated it could hurt you, even kill you.
Abdul says, “Contaminated drugs are one in a million.” The expression “one in a million” means very unusual, very rare, uncommon. Abdul says, “Now can I take my medicine?” Suzanne says, “Listen to this. Over 400 people had terrible side effects before this drug was recalled.” A “side effect” (two words) is an unintended consequence of something, that is to say, something that happens that you didn’t mean to happen, especially when we are talking about drugs and medicine. So for example, some drugs, when you take them, you become sleepy – you want to sleep. Even though the drug isn’t designed to make you sleep, that is one of the side effects – one of the things that happens in addition to what the drug is supposed to do. Suzanne says, “a drug recalled six months ago causes birth defects.” “Birth” is when you are born, when a little baby comes out of his or her mother. A “defect” is something that is wrong, something that is not right with a person or a thing. Usually defects are things that we refer to when we are talking about objects: “The chair has a defect in it, one of the legs is too short.” But, a “birth defect” is something that a baby is born with, some sort of health problem. Suzanne says, “Here’s a medical device for people with heart problems that’s defective and eight people died as a result,” or because of the device. “Defective” comes from the word “defect,” it means with a problem, not working correctly.
Abdul says, “Okay, I’ve heard enough,” meaning stop telling me this. Suzanne, of course, says, “No, wait, there’s more (there’s more information I have to tell you). You’ve got to see this list of alerts that the government issued warning people against over-the-counter drugs.” An “alert” (alert) is a warning, a notification, an important message usually about a problem. A “warning” is similar to an alert; the verb is “to warn,” meaning to tell someone about something bad or dangerous that might happen. The expression “over-the-counter” refers to drugs that are sold in a store without permission from a doctor, without what we would call a “prescription,” which is when the doctor has to give you specific permission to take a drug. Some drugs, like for example aspirin, do not require a prescription; they are over-the-counter drugs. The United States has a lot of over-the-counter drugs, and every country is different in terms of the number of over-the-counter drugs you might find. One doctor from a European country told me that the U.S. has a lot more over-the-counter drugs than other countries, but each country is different.
Suzanne says to Abdul, “You’d better check to see if it’s on the list.” Abdul says, “Don’t be ridiculous. I’ve been taking this for months. If there were something wrong with it, don’t you think the pharmaceutical company would have taken out full-page ads in the papers?” A “pharmaceutical company” is a company that makes drugs – that makes medicine. Abdul is saying that if there was a problem with the drug he is taking for his headache, the company that makes the drug would have told people by, for example, taking out an advertisement in the newspaper. Suzanne says, “I doubt it. Do you think they want to encourage litigation?” “Litigation” is legal action, a lawsuit. When someone does something wrong to you and you try to get money from them, that would be an example of litigation, something involving the courts and a judge.
Abdul says, “Here, you check it against that list.” He’s asking Suzanne to look and see if the drug he is going to take is on the list. To “check something against something” means to look for something on a list, to see if it is on the list. Abdul says, “If you find it there, you can say you’ve saved my life!”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Suzanne: Don’t take that! I’m reading an article in the newspaper about all of the drugs and medical devices that have been recalled in the past year and you wouldn’t believe how long this list is.
Abdul: I’m just taking something for my headache. I’m sure this medicine is fine.
Suzanne: Don’t be so sure. I’m just reading about this drug that was contaminated and before it was recalled, it caused 13 deaths.
Abdul: Contaminated drugs are one in a million. Now can I take my medicine?
Suzanne: Listen to this. Over 400 people had terrible side effects before this drug was recalled, and a drug recalled six months ago causes birth defects. Here’s a medical device for people with heart problems that’s defective and eight people died as a result.
Abdul: Okay, I’ve heard enough.
Suzanne: No, wait, there’s more. You’ve got to see this list of alerts that the government issued warning people against over-the-counter drugs like the one you’re about to take. You’d better check to see if it’s on this list.
Abdul: Don’t be ridiculous. I’ve been taking this for months. If there were something wrong with it, don’t you think the pharmaceutical company would have taken out full-page ads in the papers?
Suzanne: I doubt it. Do you think they want to encourage litigation?
Abdul: Here, you check it against that list. If you find it on there, you can say you’ve saved my life!
[end of dialogue]
The script for this episode was written by a one in a million scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2009, by the Center for Educational Development.
Glossary
drug – medicine; a chemical substance that is swallowed to make a sick or injured person feel better or to make one healthier
* Are you taking any drugs to lower your blood pressure?
medical device – a piece of electronics or other equipment that helps one’s body perform better, usually because one’s body can no longer do something
* Some people have pacemakers, which are medical devices that help the heart beat regularly.
to recall (something) – for a company to officially say that one of its products is dangerous and should no longer be sold, and to take back those products from people who have already bought them, usually giving them a replacement product or returning their money
* If we buy a used heater, we need to call the manufacturer to make sure that it hasn’t been recalled.
medicine – drug; a chemical substance that is swallowed to make a sick or injured person feel better or to make one healthier
* Which medicine do you use to treat your allergies?
contaminated – with an impurity; with something that is dirty, full of germs, or poisonous; not pure or clean
* The river is contaminated with chemical waste from the factories.
one in a million – very rare, unusual, or uncommon
* Your chances of being struck by lightning are about one in a million, so stop worrying about it!
side effect – an unintended consequence of doing something, especially of taking a medicine; something unexpected that happens as a result of doing something else
* The doctor warned me that the side effects of taking this medicine might include headaches, nausea, and dizziness.
birth defect – something that is wrong with a baby when he or she is born, often caused by a genetic problem or by the mother’s health while she was pregnant
* Ramon’s daughter has a birth defect and cannot hear.
defective – not working correctly; with a problem
* Max bought a new camera, but it was defective, so he had to take it back to the store and get a new one.
alert – notification; warning; an important message, usually about a problem
* The television program was interrupted by an alert about a dangerous storm that was coming to the area.
to warn (someone) – to tell someone about something bad or dangerous that will or might happen
* I warned you that there would be a lot of traffic, but you didn’t listen to me.
over-the-counter – sold in a store without a prescription (written permission from a doctor)
* He usually takes an over-the-counter medicine for his headaches, but this one is really bad so he’s going to ask his doctor for something stronger.
pharmaceutical – related to making and selling medicines
* The pharmaceutical company is trying to find a cure for AIDS.
litigation – legal action; lawsuits; the process of deciding in a court whether someone has done something against the law
* A few years ago, there was a lot of litigation between tobacco companies and people with lung cancer.
to check (something) against (something) – to look for something on a list
* Please check the names of the participants against this list to see how many people didn’t come today.
Comprehension Questions
1. Which of these might be contaminated?
a) Medicine.
b) A medical device.
c) A pharmaceutical company.
2. Why doesn’t Abdul want to read the recall list?
a) Because his headache hurts too badly.
b) Because his medicine isn’t an over-the-counter drug.
c) Because he doesn’t think it’s likely that his medicine has been recalled.
Answers at bottom.
What Else Does It Mean?
recall
The phrase “to recall (something),” in this podcast, means for a company to officially say that one of its products is dangerous and should no longer be sold, and to take back those products from people who have already bought them, usually giving them a replacement product or returning their money: “A house fire was caused by an electric heater that wasn’t working properly, so the manufacturer had to recall the units.” The verb “to recall” also means to remember: “I don’t recall what he was wearing.” Or, “Do you recall the first time we met?” Finally, the verb “to recall” can mean to be similar to something, or to make one think of something else: “That music recalls a happier time in our life.”
alert
In this podcast, the word “alert” means a notification or warning: “The university issued a bomb alert, but no bomb was ever found.” An “AMBER Alert” happens when the U.S. government sends messages to radio and television stations, police stations, email accounts, cell phones, and more to warn people that a child has been taken away from his or her parents and to ask people for help in finding the child. The phrase “to be on the alert” means to be aware of one’s surroundings and to be looking for something that is wrong or dangerous: “The police are on the alert for drunk drivers on New Year’s Eve.” The phrase “on high alert” means completely ready to fight or deal with a serious problem: “The army is on high alert, ready to fight if the enemy begins shooting.”
Culture Note
In the United States, the Consumer Product Safety “Commission” (agency) tries to “protect” (keep from danger) Americans from “injury” (getting hurt) or death from “consumer products” (things that are sold to individuals, not businesses). CPSC’s website says that in the past 30 years its work has led to a 30% decrease in the injuries and deaths caused by consumer products.
When someone is injured by a consumer product, it is reported to the CPSC. CPSC does an “investigation” (researches the problem) and works with the “manufacturer” (the company that makes the product). If a serious problem is found, then CPSC announces a recall. It “distributes” (sends to many people and places) “press releases,” which are short articles that organizations use to share news with newspapers and television and radio stations. Americans usually hear about recalls when they watch the news or read the newspaper.
Some companies ask buyers to complete a “product registration card” (a form that asks for the buyer’s name and contact information) when they buy a product. That way, if the product is recalled later, the company can contact the buyers and ask them to return the product. This has happened in the past with “strollers” (special seats on wheels for moving babies young children around), “cribs” (special beds for babies and young children), and “car seats” (special seats to keep babies and young children safe in a car).
People who buy “second-hand” (used) products often want to know if those products have been recalled. They can go to the CPSC website at www.cpsc.gov, enter the name of the manufacturer and the “model number” (a number that identifies the product type), and search for recalls. The website also has information about what consumers should do if they own a product that has been recalled.
Comprehension Answers
1 - a
2 - c