= 0446
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 446: Going to a Home Improvement Store.
This is English as a Second Language Podcast episode 446. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. You can download a Learning Guide for this episode, an 8- to 10-page PDF guide that will help you improve your English even faster.
This episode is called “Going to a Home Improvement Store.” It’s a place where you buy things to fix your home. The dialogue is between Paige and Vern, they’re going to talk about something things would typically find in a store like this to fix up or to repair your home. Let’s get started.
[start of dialogue]
Paige: I think we can get everything we need to fix up the house in one trip. What do you think?
Vern: We can try. It seems like everybody had the same thought when they woke up this morning: Go to the home improvement store!
Paige: Yeah, it’s a little crowded, but I still think we can get all we need today.
Vern: To do that, I think we need to split up. Let’s look at our list and divvy it up.
Paige: Okay, we need to get some wiring to install the new lights. I’ll go to the electrical department for that.
Vern: All right. We need lumber for the new fence, so I’ll go to the building materials department.
Paige: What about the pipes and fixtures we need for the bathroom? Can you go to the plumbing department for those, while I go to the hardware department for the tools?
Vern: Okay, I can do that, but aren’t you feeling tired already? I know I am.
Paige: Come on. How are we supposed to be weekend warriors if we can’t even do some simple shopping? We’ll meet in the garden department afterwards, okay?
Vern: Whatever you say.
Paige: Ready, set, go!
[end of dialogue]
Paige begins the dialogue by saying, “I think we can get everything we need to fix up the house in one trip.” To “fix up” is a two-word phrasal verb meaning to improve something, to make something better, or, if it is broken, to fix (or repair) something. “Fix up” has a couple of different meanings in English; go to the Learning Guide for today to find out more about what this verb means. Paige says, “we can fix up the house in one trip,” meaning one time going to the store; we don’t need to go back again and again. Paige says, “What do you think?”
Vern says, “We can try. It seems like everybody had the same thought when they woke up this morning,” meaning everybody else is also going to the store. “Go to the home improvement store!” Vern says. Home improvement stores are popular in the United States. There are two very large companies that have stores where you can buy things to fix (or repair) your home.
Paige says, “Yeah, it is a little crowded (meaning there are a lot of people here), but I still think we can get all we need today.” Vern says, “To do that (in order to do that), I think we need to split up.” To “split up” is another two-word phrasal verb meaning for two people to go in different directions, to different places. If there are two of you in the store and you say, “let’s split up,” you mean you go and buy some things; I’ll go and buy other things. To “split up” can also mean to end a romantic relationship: “My girlfriend and I split up.” It was probably a good idea, since I’m married!
Vern says, “Let’s look at our list and divvy it up.” To “divvy (divvy) something up” means to divide something between two or more people, to give part of something to each person in the group. If you have a cake and you decide to divvy it up, you’re going to give everyone a piece of the cake that’s present (that is there).
Paige says, “Okay, we need to get some wiring to install the new lights.” “Wiring,” in this case, refers to long, thin pieces of metal that are usually covered in plastic, and they’re used to move electricity or other electronic energy from one point to another. We sometimes call them “cables,” depending on how they’re used. Paige says, “we need some wiring to install the new lights.” To “install” something means to put a piece of equipment into a home or another building, usually connecting it to electricity but not always. Someone may say, “I am going to install new lights in this room,” they mean I am going to put in new lights and I will connect them up so that they work. Paige says, “I’ll go to the electrical department for that.” The “electrical department” is the part of the store that sells cables (wiring, that is), other things that are used for putting electricity in your house or building.
Vern says, “All right (okay). We need lumber for the new fence.” “Lumber” (lumber) are pieces of wood that have been cut usually in standard (or very common) sizes that you use for building things. So, if you are going to put up a fence between you and your neighbor, you would buy some “lumber,” long pieces of wood that you would use to build your fence. Vern says, “I’ll go to the building materials department.” The “building materials department” is the part of a home improvement store that sells things like wood, or things to put on your roof, or the floor; things that you would use to build things, especially houses or other buildings.
Paige says, “What about the pipes and fixtures we need for the bathroom?” A “pipe” (pipe) is a long, round, piece of plastic or metal that’s usually used to carry water from one part of the house to another. A “fixture” is something – anything that you attach to the wall of a home or to the ceiling of the home. It’s something that you would leave when you sell the house; it’s permanently attached, that is, to the wall or to the ceiling of your house. Paige says, “Can you go to the plumbing department for those, while I go to the hardware department for the tools?” The “plumbing department” is the part of the home improvement store that sells things related to how water is used in your home. So, toilets and showers and pipes; all of these would be sold in the plumbing department. The “hardware department” is the part of the store that sells tools and things you need to make things. Hammers, nails, screws; these are all things found in a hardware department. “Tools” are things you use usually to do something else, and they’re usually some things that are held in your hand. It’s a general term referring to things like hammers, saws, screwdrivers; all of these are tools. “Tool” has a couple of different meanings in English; take a look at the Learning Guide for some additional explanations.
Vern says, “Okay, I can do that, but aren’t you feeling tired already? I know I am.” Vern is already feeling tired. Paige says, “Come on (meaning let’s go). How are we supposed to be weekend warriors if we can’t even do some simple shopping?” A “weekend warrior” is someone who works a lot on their house on the weekend; it can also refer to someone who does a lot of exercise or plays sports on the weekend. But here, it refers to someone who works on their house every weekend in order to make it better. Paige says, “We’ll meet in the garden department afterwards (after we are finished shopping).” The “garden department” is the part of the store that sells plants and other things for improving your garden outside of your house.
Vern says, “Whatever you say.” This is a phrase that says that you will agree to whatever the other person is proposing – whatever they are suggesting. It doesn’t mean that you think it will be successful. Sometimes this is a phrase used when someone says something that isn’t necessarily correct. You may just say, “Oh, well, whatever,” meaning if you say so; that means I don’t necessarily believe you. But here, Vern uses the expression to mean I’ll do whatever you tell me to even though I’m not 100 percent convinced.
Paige says, “Ready, set, go!” These three words, “ready, set, go,” are used to start a race. You’re telling all of the participants, for example, who may be running in a race to get ready, and then when you say the word “go,” they start the race. Paige is making a little joke here about what they are going to do now when they shop.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Paige: I think we can get everything we need to fix up the house in one trip. What do you think?
Vern: We can try. It seems like everybody had the same thought when they woke up this morning: Go to the home improvement store!
Paige: Yeah, it’s a little crowded, but I still think we can get all we need today.
Vern: To do that, I think we need to split up. Let’s look at our list and divvy it up.
Paige: Okay, we need to get some wiring to install the new lights. I’ll go to the electrical department for that.
Vern: All right. We need lumber for the new fence, so I’ll go to the building materials department.
Paige: What about the pipes and fixtures we need for the bathroom? Can you go to the plumbing department for those, while I go to the hardware department for the tools?
Vern: Okay, I can do that, but aren’t you feeling tired already? I know I am.
Paige: Come on. How are we supposed to be weekend warriors if we can’t even do some simple shopping? We’ll meet in the garden department afterwards, okay?
Vern: Whatever you say.
Paige: Ready, set, go!
[end of dialogue]
The script for this episode was written by the wonderful Dr. Lucy Tse. Thank you Lucy!
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2009, by the Center for Educational Development.
Glossary
to fix up – to improve something; to make something better; to repair something; to correct what is broken or needs to be updated
* We’re going to fix up the office with some new paint and furniture.
home improvement store – a large store that sells the things people need to repair their homes and make them more beautiful and more comfortable
* That home improvement store has more than 30 kinds of toilets to choose from!
to split up – to go in two different ways or directions; to begin doing something independently, without another person
* We can clean the house more quickly if we split up. You clean the bathrooms and bedrooms, and I’ll clean the kitchen and living room.
to divvy (something) up – to divide something between two or more people; to give a part of something to each person
* Let’s divvy up the toys among the children so that they won’t fight over them.
wiring – cables; long, thin pieces of metal that are covered in plastic and are used to move electricity or data from one place to another
* There is a lot of wiring behind her desk, connecting the computer, monitor, printer, scanner, Internet service, fax machine, and more.
to install – to put a piece of equipment into a home or another building and connect it to electricity or other pieces of electronics so that it is ready to be used
* How long will it take to install speakers in the living room?
electrical department – the part of a store that sells cables, outlets, and other things that are needed to move electricity through a building so that electronics can be used
* I’m going to go to the electrical department to see if I can find a new light switch.
lumber – pieces of wood that have been cut into standard sizes, used for building things
* I need a piece of lumber that is five feet long and four inches wide.
building materials department – the part of a store that sells things that are needed to build something, such as wood, roofing materials, flooring, and more
* The building materials department has everything we need to create a new hardwood floor in the dining room.
pipe – a long, round, hollow piece of plastic or metal that is usually used to carry water from one place to another
* There’s a hole in the pipe and water is leaking under the sink.
fixture – something that is attached to and sold with a house
* I love the light fixtures and ceiling fans in this house!
plumbing department – the part of a store that sells things related to the use of water in a home, such as pipes, faucets, and sinks
* When they decided to build a new bathroom in their home, they had to spend a lot of money in the plumbing department.
hardware department – the part of a store that sells tools needed to build things, such as hammers, nails, screws, saws, and more
* Could you please go to the hardware department and buy some screws?
tool – something that is used to do something else, usually something that is held in one’s hands
* I need to get some garden tools, like a shovel and a rake.
weekend warrior – a person who does a lot of work on the weekend, usually either doing a lot of exercise or playing sports, or by working on one’s home
* Last weekend, I was a weekend warrior, cleaning up the yard and painting our house.
garden department – the part of a store that sells plants and things needed to improve one’s yard or garden
* The garden department is having a sale on rose bushes.
whatever you say – a phrase used to show that one will agree to whatever another person is proposing, but that one doesn’t believe it will be successful
* When the little boy said that he would be a millionaire by the time he was 20 years old, I smiled and said, “Whatever you say.”
ready, set, go – a phrase used to start a race, telling all the participants to prepare to begin running, also used when one wants to show that an activity or project is beginning
* Let’s try to clean the whole house in just an hour. Ready, set, go!
Comprehension Questions
1. Where might you find a door for sale?
a) In the electrical department.
b) In the building materials department.
c) In the plumbing department.
2. What does Vern want to do with the list?
a) Tear it up.
b) Work together to find everything.
c) Separate it into two parts.
Answers at bottom.
What Else Does It Mean?
to fix up
The phrase “to fix up,” in this podcast, means to improve or repair something, or to make something better: “They bought an old home and they plan to fix it up and resell it to make a lot of money.” The phrase “to fix (someone) up with (someone)” means to help someone find a romantic partner or begin a romantic relationship: “Joanne fixed me up with her cousin last month and now we’re dating.” The phrase “to fix (someone) (something)” means to make something for a person, especially something to eat or drink: “Can I fix you a sandwich?” Or, “Please fix us a glass of iced tea.” Finally, the phrase “to fix (one’s) eyes on (something)” means to stare at something, or to look at something intently: “The little girl fixed her eyes on the ice cream cone.”
tool
In this podcast, the word “tool” means something that is held in one’s hand and used to do something else: “Do you have the right tools to fix the car?” A “power tool” is a tool that uses electricity: “Her Dad has a garage full of saws and other power tools because he works as a carpenter.” A “tool shed” is a large room outside where tools are kept and things are built, and a “toolbox” is a large box where small tools are kept: “You can find my toolbox inside the tool shed, next to the door.” Finally, if someone is “a tool of (someone),” he or she is being used unfairly or is being tricked by another person: “Some people think that food given to other countries is a tool of the U.S. government, used to control those people.”
Culture Note
Many Americans like to fix up their homes, but even more Americans like to watch TV shows about home improvement. In the past, there were many TV shows where people could learn how to make basic home repairs. Probably the most popular “classic” (old, but well-known and popular) show was This Old House.
“Nowadays” (in current times), Americans are more interested in home “makeovers” (transformations that show how something or someone looked before and after), where professional “contractors” (people who build and/or improve homes) and “interior designers” (people who decorate homes to make them beautiful) change an old home in a very short period of time.
In one popular show called Trading Spaces, people fix up each other’s homes, but the owners aren’t allowed to see the home until it is done. The owners of home “A” work with a professional designer to change the “look and feel” (appearance and the way that one feels when one is inside a home) of home “B,” while the owners of home “B” work with a different designer to change the look and feel of home “A.” The owners have only a few days and a very “limited budget” (a small amount of money) to do their work.
Another show, Extreme Makeover: Home Edition, chooses a “deserving family” (a family that needs help because it is in a difficult situation) and completely changes their home, often making it much larger and more beautiful. Again, it is a “race against time” (something that needs to be done quickly) and the TV show lets people see how difficult it is to make so many changes so quickly.
Comprehension Answers
1 - b
2 - c