= 0449
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 449 – Using an Instruction Manual.
This is English as a Second Language Podcast number 449. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode that contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, comprehension checks, and a complete transcript of everything we say on this episode.
This episode is called “Using an Instruction Manual.” It’s going to talk about some common vocabulary in using common machines and electronics that you would find in your average home. Let’s get started.
[start of dialogue]
Aretha: Oh, here’s the instruction manual. I’ll read you the section on “getting started.”
Carl: No, you don’t need to do that. I know how to do the installation.
Aretha: But don’t you want to hear about the different functions and specifications?
Carl: There’ll be time for that after everything is hooked up and we program the machine.
Aretha: Okay, but the manual says that you shouldn’t plug in the power supply until you’re done with the installation.
Carl: I won’t. Hmm…where is the port for this cord?
Aretha: Do you want me to look it up in the manual? There’s a troubleshooting section.
Carl: No, I can figure it out myself.
Aretha: Look at this. It’s a diagram of the controls and this section has illustrations on how to use the different modes. Do you want me to read it to you while you’re hooking it up?
Carl: No. Now give me that manual. I work alone.
[end of dialogue]
Our dialogue begins with Aretha saying, “Oh, here’s the instruction manual,” the small book that comes with many machines that gives you “instructions,” tells you how to use the machine. Aretha says, “I’ll read the section (or the part) on ‘getting started.’” Carl says, “No, you don’t need to do that. I know how to do the installation.” “Installation” is when you have to take the machine and connect it perhaps to another machine or do something with it so that it will be ready for you to use. Some people like to try to do things by themselves, without the instruction manual; other people like to read the manual first before trying to connect the machine, or use the machine. I am one of those that likes to read the manual completely before I use something; my wife is the opposite, she likes to just start using it and figure it out on her own.
Aretha says to Carl, “But don’t you want to hear about the different functions and specifications?” A “function” is something that a machine or a program on a computer does; it’s what it does. For example, the function of a camera is to take pictures. Cameras can have special functions for taking pictures when there isn’t a lot of light in the picture. “Specifications” refer to detailed information about a product, usually measurements of some sort: how tall it is, how wide it is, how much power it uses, and so forth. Specifications for a computer would tell you how much memory it has, how fast the processor is, how big the screen is if it has a screen, and so forth.
Carl says, “There’ll be time for that after everything is hooked up.” He’s saying that he can look at the instruction book after he has the machine hooked up. To “hook up” a machine is a two-word phrasal verb meaning to connect it, to plug the cables or other connections that it requires. Usually you need to give it power so you need to connect it to some sort of power source, plugging it into the wall, for example, to get electricity. There are other parts of hooking things up. If you are hooking up a computer, you may connect it to a printer or to a monitor (a screen that you can look at). The verb “to hook up” has several different meanings in English; take a look at our Learning Guide for some additional explanations.
Carl says that they can program the machine. To “program” means, specifically for a piece of electronics, to provide instructions to the machine about how you want it to operate. For example, if you buy a video recorder you may have to program the time for your local time so that it will record television programs when you want it to.
Carl says that there’ll be time for looking at the manual after everything is hooked up and we program the machine. Aretha says, “Okay, but the manual says that you shouldn’t plug in the power supply until you’re done with the installation.” To “plug in” is a two-word phrasal verb, usually referring to providing electricity for an electronic machine or device. So, in most places – houses and buildings – there are what we call electrical “outlets” (outlets), and those are places where you can plug in a machine. The actual outlet is different in different countries. Europe, for example, uses a different kind of electrical outlet than the United States. It also uses, in many countries, a different power setting. So if you try to plug in your machines, say an electronic toothbrush, into a wall in Europe you might ruin your machine because the electricity is different – the kind of electricity that is provided. This is what I did once when I visited another country and I ruined my electric toothbrush, so I speak from experience!
The “power supply” is a source of electricity for a piece of electronics – an electrical machine. Often, computers will have special “transformers,” an electrical device that makes sure that the machine is getting the exact correct amount of power. Notice that Aretha is reading the instructions and, of course, Carl isn’t interested. He says, “I won’t,” meaning I won’t plug in the power supply until he’s finished with the installation. Carl then says, “where is the port for this cord?” A “port” (port) here refers to a small hole where you put a certain cord, cable, or wire into. It’s the place where you connect a cable to a machine. “Port” has a couple of different meanings in English however, so take a look at the Learning Guide for a complete definition of this word. A “cord” is just another name for a “cable,” a long wire that connects two things together. Usually, when we are talking about the power supply, we refer to that as the “cord.” When you plug something into the wall to an outlet, that’s usually called the “electrical cord.” The wires that connect different parts of the computer, or your computer to your printer for example, that would be called a “cable.”
Aretha asks Carl, “Do you want me to look it up in the manual? There’s a troubleshooting section.” “Troubleshooting” refers to giving people help, solving their problems, usually technical problems that they have with a machine or a computer program. Carl says, “No, I can figure it out myself” – I can get the answer by myself; I don’t need the manual.
Aretha says, “Look at this. It’s a diagram of the controls and this section has illustrations on how to use the different modes.” Aretha is showing Carl the instruction manual, and in the manual there is a diagram. A “diagram” is a drawing, usually that shows you where things are or where things are supposed to go, which cable goes to which port, for example. The section in the instruction manual also has illustrations. “Illustrations,” again, are a kind of drawing that gives you specific information, a picture of what it is that you should be doing with your machine. A diagram is more like a set of lines that show where things are connected. An illustration is usually something more three dimensional, a picture of something. It is, however, usually a drawing; it’s not an actual photograph.
Aretha says there are illustrations on how to use the different modes (modes). A “mode” is one way that you can use a piece of machinery – a piece of electronic machinery. Aretha asks, “Do you want me to read it to you while you’re hooking it up?” Carl, of course, doesn’t; he says, “No. Give me that manual. I work alone” – I don’t work with other people. I’m this way, as are many people; I find it difficult to work on something such as a computer or a machine with someone else trying to help me – I work alone.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Aretha: Oh, here’s the instruction manual. I’ll read you the section on “getting started.”
Carl: No, you don’t need to do that. I know how to do the installation.
Aretha: But don’t you want to hear about the different functions and specifications?
Carl: There’ll be time for that after everything is hooked up and we program the machine.
Aretha: Okay, but the manual says that you shouldn’t plug in the power supply until you’re done with the installation.
Carl: I won’t. Hmm…where is the port for this cord?
Aretha: Do you want me to look it up in the manual? There’s a troubleshooting section.
Carl: No, I can figure it out myself.
Aretha: Look at this. It’s a diagram of the controls and this section has illustrations on how to use the different modes. Do you want me to read it to you while you’re hooking it up?
Carl: No. Now give me that manual. I work alone.
[end of dialogue]
I don’t work alone on this podcast. The script for this episode was written by Dr. Lucy Tse, and of course, there are other people who help us in producing the podcast.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2009, by the Center for Educational Development.
Glossary
instruction manual – a small book that gives step-by-step instructions about how to do something, usually to use a new product for the first time
* The instruction manual for this software program is more than 500 pages long!
section – a part of a long document or book, usually separated from the rest of the text with a special heading (title)
* Your proposal needs to have a section that talks about the community impact of your project.
installation – a piece of electronics or another object that needs to be placed in a home or office and connected to other things so that one can begin using it
* If you buy the equipment here, we’ll provide free installation.
function – something that a machine or program does or is able to do
* This camera has a special function for taking pictures in cloudy weather.
specifications – detailed information about the features or characteristics of a product, including how big or heavy it is, how quickly it works, how much memory it has, and more
* Her brother-in-law is a computer scientist, so she asked him for a list of the specifications that she should look for when buying a new computer.
to hook up – to connect something with cables or wires
* Which cable should I use to hook up the printer?
to program – to provide instructions for a piece of electronics to work correctly
* They programmed their heater to turn on automatically at 6:45 each day.
to plug in – to place the end of a power cord or cable into a special small hole in the wall or another machine so that it has electrical power and/or can exchange information with another piece of electronics
* I was mad that the toaster wasn’t working, but then I realized that I had forgotten to plug it in.
power supply – the source of electricity for a piece of electronics
* The hospital needs an alternative power supply in case the city loses electricity in a storm.
port – the small hole in a piece of electronics that a cord, cable, or wire connects to
* If we want to download the photos from our digital camera, we need to use this port on the back of our computer.
cord – cable; a long wire that is wrapped in plastic and used to move electricity or information between pieces of electronics
* The phone cord isn’t long enough, so she can’t sit at her desk while she takes calls.
troubleshooting – related to helping people solve problems or answer questions when they are trying to do something
* Before contacting customer support, the website instructions say to try using the troubleshooting section of the website to see if I can find the answer to my question.
diagram – a drawing showing the location and names of things and how they work together, especially for a product or system
* We bought a chair that we had to put together, and the diagram showed that we would need six screws, but there were only four in the box.
illustration – a drawing that explains something, helps one understand something, or shows one how to do something
* Some people understand things more easily if they can look at an illustration instead of reading instructions.
mode – one way for a machine or a piece of electronics to work
* She prefers to take pictures with her camera in black-and-white mode.
to work alone – to work independently and by oneself, without help from other people
* The artist likes to work alone because he is less creative when he is around other people.
Comprehension Questions
1. Which of these might you find in an instruction manual?
a) A power supply.
b) A port.
c) A diagram.
2. Where might you plug in a cord?
a) In an illustration.
b) In a port.
c) In a mode.
Answers at bottom.
What Else Does It Mean?
to hook up
The phrase “to hook up,” in this podcast, means to connect something with cables or wires: “Do you know how to hook up our new speakers to the stereo?” The informal phrase “to hook up with (someone)” can mean to find someone and communicate with him or her: “I hadn’t seen Johann all week, but we finally hooked up on our way home from work a few hours ago.” The same phrase can also mean to start a sexual relationship with someone: “Did you hear that Max and Stacy hooked up over the weekend?” Finally, the phrase “to hook (someone) up with (something)” means to help someone get or have something: “Can you hook me up with tickets to the concert?” Or, “I need to get hooked up with a new cell phone.”
port
In this podcast, the word “port” means the small hole in a piece of electronics that a cord, cable, or wire connects to: “How many USB ports does your computer have?” Or, “Which port should I plug the memory card into?” A “port” is also a place on land next to the ocean or a large lake where boats can come to leave or pick up items: “How many pounds of salmon leave Alaska’s ports each year?” A city or town that many ships come to can also be called a port: “Have you ever been to the Port of Seattle?” Finally, “port” is a sweet, dark-red wine from Portugal that people drink after a meal: “A glass of port would be delicious with this dessert.”
Culture Note
Most instruction manuals and similar “documentation” (official written materials) are written by “technical writers,” or people whose job is to take complex, detailed, technical, and confusing information and explain it to “laypeople” (people who are not experts in a particular field of study) as clearly as possible. Good technical writing has little or no “jargon” (words that are specific to an industry and generally are not known by people outside of that industry) and is very “concise” (uses as few words as possible).
A lot of technical writing is published in instruction manuals or “online help menus” (parts of a website where people can go to get information about how to use a particular website). Other technical writing appears in reports, papers, “proposals” (ideas or suggestions for doing something in the future), and “contracts” (legal agreements between two or more people or organizations).
Many technical writers study in special programs to earn a “certificate” (a piece of paper stating that one has completed a special course or training) in technical writing. Other people begin their “careers” (the jobs that one has) in engineering or science before deciding to become technical writers. Many technical writers specialize in a specific “field” (area of work) such as medicine, engineering, or computer science.
Technical writers must have good writing abilities, but they must also be able to understand technical information. Most technical writers have good interviewing skills, too, so that they can speak to scientists, engineers, and technicians to learn about the products, understand what they are told, and then explain it to laypeople using more common language.
Comprehension Answers
1 - c
2 - b