
= eco 2020 - 15
:toc:

---

== 15. Back pain is a massive problem which is badly treated

Back pain *is* a massive(`=extremely large or serious 巨大的；非常严重的`)  problem which *is badly treated* 医疗；医治；治疗

Why `系` *are* `主` better approaches to helping sufferers `表` *so slow to spread*?

背部疼痛是一个严重的问题，但却治疗不当 +
能帮助患者的更好的治疗方法, 为什么其传播速度却如此缓慢?

Jan 18th 2020 | +
eco 2020.01.18 / Briefing / Chronic pain: Backs to the future

PETE MOORE *was* 43 when he *woke up* one autumn morning *with* back pain [*so*] excruciating(a.)(`=extremely painful or bad 极痛苦的；极坏的；糟糕透顶的`) *[that]* he *struggled to dress*(`=*~ (sb) (in sth)* : to put clothes on yourself/sb 穿衣服；给（某人）穿衣服`) himself.

His doctor in Romford, an English town, *referred* him *to* hospital for an MRI(`=*magnetic resonance imaging* (a method of using a strong magnetic field to produce an image of the inside of a person's body) 磁共振成像；核磁共振成像`) scan;

this *showed that* some of the spongelike 海绵样的,海绵状的 discs(`=disc : a structure made of cartilage between the bones of the back 椎间盘;背部骨骼之间由软骨构成的结构`) that *separate* the spine’s 脊柱，脊椎 vertebrae(`=Vertebrae are the small circular bones that form the spine of a human being or animal. 椎骨`) *were bulging*(`=bulge : to stick out from sth in a round shape 凸出；鼓胀`) *out of* the slots （投放或插入东西的）窄缝，扁口 (*into* which they *customarily 通常，习惯上 fit*(`=to be of the right size, type or number to go somewhere （大小、式样、数量适合）可容纳，装进`)).

Such “slipped” 滑动 discs *can be caused by* an injury; but they *are* also the sort of thing which *can just happen* with increasing age.

====
- excruciating => ex-, 向外。-cruc, 十字，折磨，词源同cross, crucifix.

- resonance : *the sound or other vibration produced in an object by sound or vibrations of a similar frequency from another object* 共鸣；共振；谐振

- *MRI (Magnetic Resonance Imaging)* : (核)磁共振成像. 它利用"磁共振现象"从人体中获得电磁信号,并重建出人体信息。
====
一个秋天的早晨，43岁的皮特·摩尔(PETE MOORE)一觉醒来，背部疼痛难忍，连自己穿衣服都很费劲。他在英国小镇罗姆福德的医生, 建议他去医院做核磁共振扫描；扫描结果显示，一些分隔脊椎的海绵状椎间盘, 正在从通常容纳它们的狭缝中凸出。这种“滑动”的椎间盘问题, 可能是由受伤引起的，但也是那种随着年龄的增长而可能发生的事情。

Mr Moore *received* a prescription 处方；药方 for opioids(n.)(`=opioid : any of a group of substances that resemble morphine in their physiological or pharmacological effects, esp in their pain-relieving properties 类鸦片活性肽; 一组在生理或药理作用上类似吗啡的物质，尤指其镇痛作用`) *to help* him *cope with* the pain; but the pain *persisted*, and he *found* himself becoming loopy(a.)(`=not sensible; strange 失去理智的；疯狂的；奇怪的；怪异的; /very angry 很生气的；十分愤怒的`).

====
- loopy => 来自loop,圈，环，即多圈的，多环的，后用于比喻义把人逼疯的，发疯的。
====

*Unable to work* or *do* much else, Mr Moore, who *had been* a painter, *sank into* depression. Three years into his ordeal(n.)(`=*~ (of sth/of doing sth)* : a difficult or unpleasant experience 磨难；折磨；煎熬；严酷的考验`), he *says*, he *was “thinking of* ending(v.) it all”.

====
- ordeal => 字面意思就是“deal out by gods”（由神灵来施加惩罚）。现在引申为“严峻的考验”。
====

摩尔接受了阿片类药物的处方，以帮助他应对疼痛;但是疼痛仍然持续着，他发现自己变得快失去理智了。由于不能工作，也不能做其他的事情，曾经是画家的穆尔陷入了抑郁。他说，在经历了三年的磨难后，他“想要结束这一切”。

Back pain *does not*, in and of itself 就其本身而言,固有地，内在地, *kill* people. But it *makes* a huge number of lives(n.) 宾补 a misery(n.)(`=great suffering of the mind or body 痛苦；悲惨`).

In most countries (for which there *are* reliable figures), whether rich or poor, back pain *is* the top cause of disability 残疾;（指状态、身心、学习等方面的）缺陷，障碍, *measured by* the aggregate 总数的；总计的 number of years (*lived* in poor health). That burden *is decreasing* (see chart) but only *very slowly*.

背痛本身并不会致人死亡。但它让很多人的生活变得痛苦。在大多数有着可靠统计数据的国家，无论是富国还是穷国，背痛是导致残疾的首要原因，以健康状况不佳的总年数来衡量。虽然这种背痛导致的残疾负担正在减少(见图表)，但速度却非常缓慢。

The costs, however, *have been rising quite quickly* -- and *are* enormous. In 2013, *according to* one study, $88bn *was spent on* medical treatments *for* back and neck pain in America, *not far(ad.) (问到或谈及距离时说)有多远，远（至） short of* 仅略少于;离…不远 the $115bn *spent on* cancer (more recent figures *have not been analysed* in a comparable way). A great deal of this money *seems, sadly, to do* little good.

然而，治疗成本却一直在快速上升，而且是巨大的。根据一项研究，2013年，美国用于治疗背部和颈部疼痛的医疗支出, 为880亿美元，与用于治疗癌症的1150亿美元相差不远(最近的数据, 没有以可比的方式进行分析)。可悲的是，这些钱的大部分, 似乎没有产生有效益的用处。

Doctors *used to think that* back pain *was* almost entirely the result of mechanical damage to tissue *beyond* the capacity of X-rays *to detect*.

The advent of MRI scans *showed* {this *was not* true}. A definitive(a.)(`=final; not able to be changed 最后的；决定性的；不可更改的`) physical cause -- *such as* a fracture, a tumour 肿瘤；肿块, pressure on a nerve, infection or arthritis 关节炎 -- *is found* in 5-15% of people with back pain.

The rest(`=the remaining part of sth 剩余部分；残留；其余`) *is all labelled 贴标签于；用标签标明 as* “non-specific”(`=not definite or clearly defined; general 不明确的；非特定的；泛泛的; /(of pain, a disease, etc. 疼痛、疾病等) with more than one possible cause 不止一种病因的；有多种致病可能的`), and there *is increasing* evidence that *it is not* mechanical in origin.

====
- *mechanical damage* : 机械损伤. 是指人体同某种致伤物接触，因机械运动作用, 所造成的机体正常组织的破坏, 或器官的机能性障碍。可分为钝器伤、锐器伤、枪弹伤、火器伤等类。机械性损伤的基本征象有: 表皮剥脱、皮下出血、创伤、骨折、内脏破裂, 肢体断离, 六种。

- non-specific : a. *not definite or clearly defined; general* 不明确的；非特定的；泛泛的 +
-> The candidate's speech *was non-specific*. 这位候选人的讲话只是泛泛之谈。
====
医生们过去认为，背部疼痛几乎完全是组织受到机械损伤的结果，超出了x光检测的能力。核磁共振扫描的出现, 表明事实并非如此。5-15%的背痛患者, 都有明确的生理原因，如骨折、肿瘤、神经压迫、感染或关节炎。其余的都被贴上了“非单一原因导致的”的标签，而且越来越多的证据表明, 机械损伤并非是它的病因。

Back pain, *like* all pain, *is experienced* [in the brain] *not* the body; `主` nerves (*coming in*) `谓` *tell* the brain *that* something *is* amiss(a.)(`=wrong; not as it should be 不对；不正常`), and `主` the brain `谓` *projects*(`=to send or throw sth up or away from yourself 投掷；抛射；发送; /*~ sth (on/onto sth)* : to make light, an image, etc. fall onto a flat surface or screen 放映；投射；投影`) an appropriate 合适的；恰当的 sensation 感觉；知觉 of pain.

====
- project : v. (1) *~ sth (on/onto sth)* : to make light, an image, etc. fall onto a flat surface or screen 放映；投射；投影 +
-> Images *are projected onto* the retina of the eye. 影像被投射到眼睛的视网膜上。 +
(2) *to send or throw sth up or away from yourself* 投掷；抛射；发送 +
-> Actors must learn *to project their voices*. 演员必须学会放开声音。
( figurative ) +
-> the powerful men *who would project him into The White House* 能使他平步进入白宫的有力人士
====

`主` Researchers who *specialise in* pain `谓` *increasingly believe that*, in most cases, chronic pain *means that* the system *has become damaged* [in some way] that *keeps* it *switched on*(`=switch off/on; switch sth off/on 关╱开（电灯、机器等）)

“It’s *like* a fire alarm that *goes off*(`=if an alarm, etc. *goes off* , it makes a sudden loud noise （警报器等）突然发出巨响`) after the fire *has been extinguished* 熄灭；扑灭,” *says* Lucie Knight, a psychologist 心理学家 at a pain clinic in St Thomas’ Hospital, in London.

Back pain *may also be related to* other aspects of a person’s life *not going well*.

背部疼痛就像其他疼痛一样，是被大脑而不是被身体感知到; 传入的神经信号告诉大脑, 你身体的某些地方出了问题，大脑就会反射产生适当的痛觉。专门研究疼痛的研究者, 越来越相信，在大多数情况下，慢性疼痛意味着身体系统受到了某种程度的损伤，从而使疼痛持续。伦敦圣托马斯医院(St Thomas’s Hospital)的疼痛诊所的心理学家露西•奈特(Lucie Knight)表示:“这就像火灾被扑灭后, 依然响起的火警信号。”背痛还可能与一个人生活中其他方面的问题有关。

`主` *Taking* this view *seriously* `谓` *throws into doubt* `主` a great deal of the medical treatment of back pain -- much of which, in effect, `谓` *seeks* to silence(v.)(`=to make sb/sth stop speaking or making a noise 使安静；使不说话`) the maddening(a.)(`=it makes you feel angry, irritated, or frustrated. 使人恼火的`) sound of the fire alarm *by putting out a fire* that isn’t there.

But it *does not offer* an obvious medical alternative.

Some pain medicines, such as paracetamol(`=a drug used to reduce pain and fever 醋氨酚；扑热息痛`), *do not work at all* for back pain.

Opioids 类鸦片活性肽, for all their reputed(a.)(`=*~ (to be sth/to have done sth)* : generally thought to be sth or to have done sth, although this is not certain 所谓；普遍认为；号称`) analgesic 止痛药；镇痛剂 potency(`=the power that sb/sth has to affect your body or mind 影响力；支配力；效力;/he ability of a man to have sex （男子）性能力，性机能`), *offer* back-pain relief [*little*] [*if any* 如果有的话; 假如有，即使有 better than options such as ibuprofen](n.)(`=a drug used to reduce pain and inflammation 布洛芬，异丁苯丙酸（镇痛消炎药）`).

`主` Their continued use `谓` *often makes pain worse* rather than better, and *is highly likely to cause* addiction 上瘾.

====
- paracetamol => 化学药品名，缩写自para-acetyl aminophenol,来自para-,辅助，准，acet-,乙酸，-yl,基，amino-,氨，phen-,酚，ol-,醇。

 - reputed : a. *~ (to be sth/to have done sth)* : generally thought to be sth or to have done sth, although this is not certain 所谓；普遍认为；号称 +
-> *He is reputed(a.) to be* the best heart surgeon in the country. 他号称是这个国家最好的心脏外科医生。 +
-> She sold her share of the company *for a reputed(a.) ￡7 million*. 她的公司股份据说卖了700万英镑。
====

认真对待这一观点，会让人们对治疗背痛的大量方法产生怀疑——实际上，很多方法都是试图通过扑灭一场并不存在的火灾，来平息令人发狂的火灾警报声。但它并没有提供一个明显的医学替代方案。一些止痛药，如扑热息痛，对背部疼痛完全不起作用。阿片类药物，尽管被认为具有镇痛作用，但与布洛芬等药物相比，几乎不能缓解背痛。他们的持续使用, 经常会使疼痛加剧而不是好转，并且很可能导致上瘾。


`主` Drugs (that *worked better* and *did less harm*) `系` *would be* a boon(n.)(`=*~ (to/for sb)* : something that is very helpful and makes life easier for you 非常有用的东西；益处`).

But they *have proved* hard to develop. `主` The mechanisms in the nervous system and brain which *generate pain* `系` *are* complex, and *can [doubtless] go wrong* in a variety of ways, *says* Steve McMahon of King’s College London.

He *thinks that* `主` the development of drugs for chronic pain `谓` *has a poor record* because `主` the people *they are tried on*(`=*try sb/sth out (on sb)* : to test or use sb/sth in order to see how good or effective they are 试用（某人）；测试；试验`) `谓` *have* a range of different problems.

====
- boon => 词源同bonus.  助记窍门：boon→谐音“布恩”→恩惠

- *try sb/sth out (on sb)* : to test or use sb/sth in order to see how good or effective they are 试用（某人）；测试；试验 +
-> *They're trying out* a new presenter *for* the show. 他们正在为这个节目试用一名新的主持人。
====
疗效更好、危害更小的药物, 将是一种福音。但事实证明，它们很难研发。伦敦大学国王学院的史蒂夫·麦克马洪说，神经系统和大脑产生疼痛的机制很复杂，毫无疑问会以各种方式出错。他认为，治疗慢性疼痛的药物的研发记录不佳，因为试验对象有一系列不同的问题。

Evidence of ineffectiveness 无效；不起作用 *has not stopped* doctors *from* writing(v.) prescriptions 处方; 处方药 for the drugs they have.

The prevalence 流行；普遍；广泛 of chronic back pain *provided* a huge expanse 一大片，广阔，宽广，浩瀚（尤指陆地或海洋） of fertile 肥沃的；富饶的 ground *for* the deceptive(a.)欺骗性的；误导的；骗人的 marketing and poor 劣质的；差的；次的 prescription behind America’s opioid epidemic(n.)（迅速的）泛滥，蔓延 (see Bartleby).

[In many countries] doctors also *frequently prescribe* 给…开（药）；让…采用（疗法）；开（处方） painkillers 止痛药 *called* gabapentinoids(`=gabapentin : an antiepileptic drug that is also used to control neurological pain 加巴喷丁; 一种抗癫痫药物`), despite strong evidence from trials （对能力、质量、性能等的）试验，试用 (that, *as far as* treating back pain *goes*(`=*as/so far as sb/sth is concerned; as/so far as sb/sth goes* : used to give facts or an opinion about a particular aspect of sth 就…而言`), they *offer* no benefits).

那些药物在治疗背痛方面是无效的, 这个证据, 并没有阻止医生为他们所拥有的药物继续开处方。慢性背痛的流行, 为美国阿片类药物泛滥背后的欺骗性营销和不良处方, 提供了广阔的沃土。在许多国家，医生还经常开一种叫做加巴喷丁的止痛药，尽管从试验中得到的有力证据表明，就治疗背痛而言，这种药没有任何好处。

There *are* also a lot of treatments *for* the back itself. Spines *are injected with* cement-like mixtures 混合物 or *fitted*(`=to put or fix sth somewhere 安置，安装（在某处）`) *with* various types of medical hardware.

Vertebrae 椎骨，脊椎 *are fused* （使）融合，熔接，结合 together, discs *excised*(v.)(`=*~ sth (from sth)* : ( formal ) to remove sth completely 切除；删除`) or *tampered with*(`=*TAMPER WITH STH* : to make changes to sth without permission, especially in order to damage it 篡改，擅自改动，胡乱摆弄（尤指有意破坏）`) in various ways.

Yet -- unsurprisingly, if it *is* largely the pain mechanism (which *is* the problem) -- there *is* a growing body of evidence that `主` the benefits (all this *offers to* most patients) `系` *are* limited or non-existent(a.)(`=not existing; not real 不存在的；不真实的`).

====
- excise => ex-, 向外。-cis, 砍，切，词源同decide, circumcise.
====

背部本身也有很多治疗方法。脊椎被注入水泥样的混合物, 或安装各种类型的医疗硬件。椎骨被融合在一起，椎间盘以各种方式切除或改动。然而——毫不奇怪，如果主要的问题其实是在疼痛机制上，那么越来越多的证据表明，所有这些疗法对大多数患者的益处, 是有限的, 或根本不存在的。

`主` Even just *looking at*(`=*look at sth* : to examine sth closely （仔细）察看，检查`) the back `谓` *causes* problems.

Only 1-5% of people with back pain *have* a problem that *requires* urgent 紧急的；紧迫的；迫切的 treatment, *such as* an infection or a tumour; [in such cases] the pain *will tend to be accompanied 伴随；与…同时发生 by* other symptoms 症状 too, *such as* weight loss, fever or incontinence(`=the lack of ability to control the bladder(膀胱) and bowels(内脏（尤指人的肠）) 失禁`).

====
- incontinence => in-,不，非，continence,控制，节制。即无法控制的，后多用于指人的大小便失禁。
====

[In America and western Europe] guidelines 指导方针；指导原则 *say that* it is [only when such red flags 红旗；危险信号 *are present*] that a patient *presenting* with back pain *should promptly be given* an x-ray or an MRI scan.
====
- 这里的 it is [only when...] that... 是强调句.
====

[Yet] general practitioners （尤指医学或法律界的）从业人员 and hospitals routinely 例行地; 常规性地 *ignore* this, *sending* 40-60% of people with back pain *to be scanned* -- far more than they did 20 years ago.

[*According to* Jan Hartvigsen of the University of Southern Denmark] there *is* a broad consensus 共识 that about 80% of such scans *are* useless.

====
- practitioner => pract做,从事 + -ition名词词尾 + -er名词词尾,人
====

即使只是看背部, 也会引起问题。只有1-5%的背痛患者, 存在需要进行紧急治疗的疾病，如感染或肿瘤; 在这种情况下，疼痛往往会伴随着其他症状，如体重减轻，发烧, 或大小便失禁。在美国和西欧，指南说，只有当这些危险信号出现时，出现背痛的病人才应该立即进行x光或MRI扫描。然而，全科医生和医院经常忽视这一点，让40-60%的背痛患者接受检查——这比20年前要严重得多。根据南丹麦大学的Jan Hartvigsen的说法，人们普遍认为80%的扫描是无用的。

That *might be* fine [if the scans *were* sometimes helpful and never harmful].

But few bodies *are* completely normal, and `主` *learning of* your particular “abnormalities”(n.)(`=abnormality : a feature or characteristic in a person's body or behaviour that is not usual and may be harmful, worrying or cause illness （身体、行为等）不正常，反常，变态，畸形`) [in a medical setting(n.)(`=a set of surroundings; the place at which sth happens 环境；背景`) and while suffering] `谓` *is* alarming(a.)(`=causing worry and fear 使人惊恐的；令人惊慌的；引起恐慌的`) even if a healthy back *might look just as* odd.

Disc “degeneration”(`=the process of becoming worse or less acceptable in quality or condition 蜕化；衰退；堕落`) *is seen* [*in* roughly half of young and middle-aged adults with back pain], but also *in* a third 三分之一 of those with no pain at all.

Some 40% of people with back pain *have* disc protrusion(`=a thing that sticks out from a place or surface; the fact of doing this 突出物；凸起；伸出`), a form of “slipped” disc; but *so do* nearly 20% of people who *are* pain-free(a.)(`=无痛的；轻松的，不费力的（同 painless）`).

如果扫描有时是有帮助的，而不是有害的，那可能是好的。但很少有身体是完全正常的，即使健康的背部可能看起来同样奇怪，但在医疗环境和痛苦中得知你特殊的“异常”是令人震惊的。椎间盘“变性”出现在大约一半患有背部疼痛的年轻人和中年人身上，但也有三分之一的人根本没有疼痛。大约40%的背部疼痛患者患有椎间盘突出症，这是一种“滑脱”的椎间盘突出症；但近20%的无痛患者也是如此。

Both patients and doctors, though （用于主句后，引出补充说明，使语气变弱）不过，可是，然而, *tend to think that* {[if they *can see* something] they *should do* something}.

Some sufferers ① *catastrophise*(v.)(`=catastrophize : 小题大做，把事情复杂化`) the news *into* the idea that they *have* a broken, fragile back and ② *start avoiding* normal physical activity -- not least(`=*not least* : especially 特别；尤其`), *says* Ms Knight of St Thomas’, because doctors *often fail to explain to them ① that* {`主` abnormalities(n.)(`=abnormality : a feature or characteristic in a person's body or behaviour that is not usual and may be harmful, worrying or cause illness （身体、行为等）不正常，反常，变态，畸形`) `系` *are*, in fact, quite normal}, and ② *that* {degeneration(`=the process of becoming worse or less acceptable in quality or condition 蜕化；衰退；堕落`) *can basically 总的说来；从根本上说 be* wear and tear(`=*Wear and tear* is the damage or change that is caused to something when it is being used normally. 损耗`)}.

然而，病人和医生都倾向于认为，如果他们看到了什么，他们就应该做些什么。 +
圣托马斯医院的奈特女士说，一些患者将他们从扫描中看到的信息, 小题大做, 以为他们有了一个骨折的, 脆弱的背部，并开始避免正常的身体活动，尤其是, 因为医生经常未能向他们解释，这种异常, 实际上是很正常的，身体机能的退化, 基本上源于年龄所导致的身体器官的磨损。

`主` The stiffness(n.)僵硬；坚硬 and weakening(n.) （使）虚弱，衰弱；减弱；削弱 of the muscles (this inactivity 不做任何事，不活动 *brings*) `谓` *often makes* things *worse*.

And doctors *may take* abnormalities(n.)异常 (尤指人的身体或行为中令人担忧或危险性的特征) *as* a cue 暗示；提示；信号 for further medical attention.

Many studies *have confirmed （尤指提供证据来）证实，证明，确认 that* `主` patients who *receive* unwarranted(a.)(`= not reasonable or necessary; not appropriate 不合理的；不必要的；无正当理由的；不适当的`) imaging(n.)(`=the process of capturing, storing and showing an image on a computer screen 成像`) in the first few weeks of back pain `系` *are more likely* to have surgery 外科手术；外科学 and unnecessary follow-up 后续行动；后续事物 tests *than* similar patients *spared*(`=*~ sb/yourself (from) sth* : to save sb/yourself from having to go through an unpleasant experience 省得；免去`) the scans -- but that they *enjoy* no benefits *in terms of*(`=*IN TERMS OF STH / IN...TERMS* : used to show what aspect of a subject you are talking about or how you are thinking about it 谈及；就…而言；在…方面`) pain reduction or lessened(`=lessen : to become or make sth become smaller, weaker, less important, etc. （使）变小，变少，减弱，减轻`) disability(`=a physical or mental condition that means you cannot use a part of your body completely or easily, or that you cannot learn easily （某种）缺陷，障碍`).

而你如果不活动的话, 带来的肌肉僵硬和身体虚弱, 反而往往会令情况变得更糟。而医生可能会将你的健康异常, 解释为需要进一步的医疗护理的信号。 +
许多研究已经证实，与没有接受扫描的类似患者相比，在背痛的头几周就接受不适当的成像扫描的患者, 更有可能会去接受手术, 和进行不必要的后续检查 -- 但这对他们在减轻疼痛或减轻残疾方面, 没有任何好处。

In 2011 `主` Cigna 信诺（美国一保险公司）, an American insurance company, `谓` *ran* a follow-up(n.)(`=an action or a thing that continues sth that has already started or comes after sth similar that was done earlier 后续行动；后续事物`) study on patients who *had undergone* procedures(`=a medical operation 手术;/（正常）程序，手续，步骤`) in which vertebrae 椎骨 *are stitched*(`=*~ sth (up)* : to sew the edges of a wound together 缝合（伤口）`) *together with* implanted 将…移植入 bolts 螺钉 and braces 箍子；夹子；支架.

“Spinal fusion” 脊柱融合术；脊柱制动术 of this type *is* a frequently used surgical response to back pain that *is associated 有关联的；相关的;有联系的 with* the degeneration of spinal discs; in 2015 there *were* roughly 85,000 such surgeries in America.

The company *found that* [two years after treatment 治疗；疗法；诊治] 87% of customers *were* still in pain severe(a.)严峻的；严厉的 enough for medication 药；药物 or some other treatment; 15% *had* more surgery 外科手术.

2011年，美国保险公司信诺(Cigna)进行了一项后续研究，研究对象是那些接受过脊椎手术的患者, 他们的椎骨被植入了螺钉和支架。 +
这种“脊柱融合”手术, 是一种常见的处理背痛的外科手段, 该背痛与理椎间盘退变有关系; 2015年，美国大约做了8.5万例这样的手术。但Cigna保险公司发现，治疗两年后，87%的患者仍然感到疼痛严重，以至于需要再接受药物或其他治疗; 15%的人, 还接受了更多的手术。

This is going to hurt

这会很疼的

It all *sounds* depressing. It *need not be* so. There *are* ways of *dealing with back pain* that(`=指ways`) *waste* much less money and *leave* patients *less distressed*(a.)(`=suffering pain; in a poor physical condition 痛苦的；身体虚弱的`) and *with a greater sense of* their own agency.

这一切听起来令人沮丧。不必如此。有很多方法可以减少背部疼痛带来的对金钱的浪费，并减轻患者的痛苦，增强患者的自我感觉。

`主` Mr Moore, the patient ([*with whom*] this story *began*), `谓` *tried to come to terms with*(`=*COME TO TERMS (WITH SB)* : to reach an agreement with sb; to find a way of living or working together （与某人）达成协议，妥协;/*COME TO TERMS WITH STH* :to accept sth unpleasant by learning to deal with it 迁就顺从；接受（令人不快的事物）；适应（困难的处境）`) his disabling pain *by starting* a support group for fellow sufferers.

`主` A psychologist from St Thomas’, which *has* the biggest pain clinic in Europe, `谓` *came to talk to* them *about* ① “graded （按难度、大小等）分级的 exercise” and ② the importance of *pacing* 踱步；缓慢而行 themselves [when *going out and about*].

“Nobody *had told* me {I *could do* these things},” *says* Mr Moore.

In 1996, three years after back pain *had come to dominate* his existence, `主` a two-week residential(`=(of a job, a course, etc. 工作、课程等) requiring a person to live at a particular place; offering living accommodation 需要在某地居住的；提供住宿的`) programme at the pain clinic `谓` *taught* him 双宾 what it *teaches* people today: ① *exercise daily*; ② *accept* flare-ups(n.)(`=flare-up :(of an illness 疾病) a sudden painful attack, especially after a period without any problems or pain 突发；（尤指）复发`) *as* temporary setbacks(n.)挫折；阻碍; ③ *don’t get fixated(a.) on*(`=*fixated (on sb/sth)* : always thinking and talking about sb/sth in a way that is not normal （对…）异常依恋，固恋`) the pain.

`主` *Learning to keep going [this way]* `谓` “*saved* my life”, Mr Moore says.

摩尔先生，我们故事开头的那个病人，尝试与病痛妥协, 他建立一个为其他患者提供支持的小组。圣托马斯医院拥有欧洲最大的疼痛治疗诊所，该医院的一位心理学家, 前来为他们介绍了“按自己的病情条件来逐级锻炼”, 以及外出走动时, 要缓步而行的重要性。“没有人告诉我可以做这些事情，”摩尔先生说。1996年，在被背部疼痛支配了三年后，疼痛诊所的一个为期两周的住院项目, 教会了他今天人们所学到的东西：每天锻炼；将突发的疾病, 视为是暂时的挫折；不要专注于疼痛。摩尔说，学会这样做, “救了我的命”。

The programme, *explains* Ms Knight, *aims* *[not]* to reduce pain [*so much as*] to add to life.

====
- *not A so much as B / not so much A as B : 与其说A, 倒不如说B / 是B,而不是A*. 即, *轻前, 重后* +
A和B是两个被比较的平行结构，如同为介词短语、动词不定式、名词短语或其他平行结构。 +
- Science moves forward, they say, *not so much* through the insights of great men of genius *as* because of more ordinary things like improved techniques and tools. +
他们说，科学的发展与其说源于天才伟人的真知灼见，不如说源于改进了的技术和工具等更为普通的东西。

- The great use of a school education is *not so much* to teach you things *as* to teach you the art of learning. +
学校教育的伟大作用不在于教会你多少东西，而在于教会你学习的技巧。
====


People *naturally struggle against* the pain, which *means* they *are burdened （使）担负（沉重或艰难的任务、职责等） with* the pain and the struggle too.

“If you *can drop*(`=to stop doing or discussing sth; to not continue with sth 停止；终止；放弃`) the struggle,” *says* Ms Knight, “then you *have your hands free* to do more.”

Patients *are taught* how *to gradually overcome* their fears of exercise and daily activities (that *can cause* some pain).

`主` The goals that they *start [with]* `系` *can be* as simple as *calling* a friend /and *meeting for* a coffee, or *attending* a wedding.

In a typical class of ten people, Ms Knight *says*, one or two *decide that* the approach *is not* what they want, and *may drop out*(`=*drop out (of sth)* : to no longer take part in or be part of sth 不再参加；退出；脱离`).

Most of them *take away* at least some skills which *add to* their quality of life. One or two, *like* Mr Moore, *find* the programme life-changing(a.)改变人生的.

奈特女士解释说，这个项目的目的, 与其说是减轻病痛，不如说是为了增加生命的质量。人们会自然地与痛苦作斗争，这意味着他们也背负起了疼痛和斗争。奈特表示:“如果你能放下这种挣扎，那么你就能腾出双手去做更多的事情。”“患者被教导如何逐渐克服他们对锻炼和日常活动的恐惧，虽然这些行动可能会带来一些身体上的疼痛。他们可以从一些简单的活动开始做起, 比如打一个电话给朋友，约见面喝杯咖啡，或者参加一个婚礼。奈特女士说，在一个典型的有十人的班级里，会有一两个病友认为这种方式不是他们想要的，而可能退出。但班里的大多数人, 至少会学到一些机能, 能给他们的生活质量带来提高。班里会有一两个人, 就像摩尔先生一样，会发现这个项目能改变他们的人生。

Various(`=several different 各种不同的；各种各样的`) countries *have tried to encourage* people with back pain *to stay active*, with(`=because of; as a result of 因为；由于；作为…的结果`) promising 有希望的；有前途的 effects.

One such campaign 运动（为社会、商业或政治目的而进行的一系列有计划的活动）, in Australia, *is reckoned* 被普遍认为是；被看作是;估算；估计；计算 *to have led to* a 15% reduction in the number of doctor visits(n.) for back pain /and a 20% decrease in related medical costs.

Such campaigns *appear to work best* [when they *provide* practical(`=(of an idea, a method or a course of action 想法、方法或行动) right or sensible; likely to be successful 切实可行的`) advice *on* `宾`  how *to stay active* and *at work* [*despite* the pain]], and [when *as well as*(`=*as well (as sb/sth)* : in addition to sb/sth; too 除…之外；也；还`) *speaking to* the afflicted 折磨] they *enroll*(v.)（使）加入；注册；登记 employers, clinicians 临床医生 and unions *as* partners.

====
- *as well (as sb/sth)* : in addition to sb/sth; too 除…之外；也；还
-> Are they coming [*as well*]? 他们也来吗？ +
-> She is a talented musician *as well as* being a photographer. 她不但是个摄影师, 而且还是个天才的音乐家。 +
*as well as使用就远一致原则,也就是跟第一个主语一致.* 例如：I *as well as* my parents *am* fond of music.
====

许多国家都试图鼓励背痛患者保持运动，这带来了良好的效果。一个在澳大利亚的此类活动，效果被认为, 使因背痛而看医生的次数, 减少了15%，并使相关的医疗费用也减少了20%。 +
当患者能被提供关于"如何在病痛中保持活力和进行工作"的实用建议时, 并且当把患者的雇主、临床医生和工会, 也加入进同患者的交谈活动时, 这种活动看起来效果最好. (机翻 : 以及当他们除了与受灾者交谈外，还将患者的雇主、临床医生和工会, 也作为合作伙伴时，这种活动似乎效果才最好。)

Activity *is not* a panacea(`=~ (for sth) something that will solve all the problems of a particular situation 万灵药；万能之计`), and if *leading* an active life with pain *is better than* withdrawing from the world, it *is still not* ideal.

But interventions 干预,介入,干涉;介入治疗 like this *seem to offer* people more succour(n./v.)(`=help that you give to sb who is suffering or having problems 救助；救援；帮助`) *than* highly medicalised  用医学方法处理 approaches.

Unfortunately, medical schools, patient expectations 期望；预期 and the policies of insurers(`=insurer : a person or company that provides people with insurance 承保人；保险公司`) and governments *all sustain* 支撑；承受住 the latter(a.)（刚提及的两者中）后者的；（系列中）最后的，末尾的.

====
- panacea => 来源于希腊语形容词pas, pasa, pan(全部的)和名词akos(治疗)。 词根词缀： pan-全 + acea治疗
- succor => suc-,在下，向上，-cor,跑，词源同 current,course.即跑过来，引申词义帮助，救助，救援等。
====

进行活动, 当然不是万灵药，如果要带着痛苦过一种积极的生活, 虽然要比隐居世界要好，那还是不理想的。但这类"干预型的疗法", 看起来要比"高度医疗化的治疗方法", 更能给人们给予帮助。但不幸的是，医学院、病人自己的期望, 以及保险公司和政府, 都支持后者(即医学疗法)。

All around the world, family doctors *are* woefully(`=very bad or serious; that you disapprove of 糟糕的；严重的；不合意的;/very sad 悲惨的；忧伤的`) undertrained(a.)训练不够的，练习不够的 *to treat* common, unglamorous(`=not attractive or exciting; dull 无魅力的；不刺激的；枯燥的`) conditions （因不可能治愈而长期患有的）疾病 such as bad backs.

====
- woeful : a. *very bad or serious; that you disapprove of* 糟糕的；严重的；不合意的 +
=>  woe : 感叹词。
-> She displayed *a woeful ignorance of* the rules. 她对这些条例表现出可悲的无知。

- condition :  an illness or a medical problem that you have for a long time because it is not possible to cure it （因不可能治愈而长期患有的）疾病 +
-> *a medical condition* 疾病 +
-> He suffers from *a serious heart condition* . 他患有严重的心脏病。
====

[In most medical curricula 课程;总课程] `主` musculoskeletal(a.)(`=of or relating to the skeleton and musculature taken together 骨骼肌的`) conditions （因不可能治愈而长期患有的）疾病, like back pain, `系` *are* a minor feature （报章、电视等的）特写，专题节目.

Back pain *is “not* sexy” for medical students, *says* Chris Maher of the University of Sydney.

[Even if they *are going to be* family doctors] they still *want to hear about* cures for cancer and impressive forms of surgery, *rather than* humdrum(a.)(`=boring and always the same 乏味的；单调的`) stuff （事物名称不详、无关紧要或所指事物明显时用）东西，物品，玩意儿 like back pain /or *preventing falls* in older people.

====
- humdrum => hum,嗡嗡叫，-drum,由hum杜撰出来的同韵词。引申义乏味的，单调的。
====
遗憾的是，在世界各地，家庭医生在治疗常见的、乏味的病症(如背伤)方面, 训练不足。在大多数医学课程中，肌肉骨骼疾病，如背痛，是次要的主题。悉尼大学的Chris Maher说，对于医科学生来说，治疗背痛, 并“不性感”。即使他们将成为家庭医生，他们仍然希望听到关于癌症的治疗方法和令人印象深刻的手术形式，而不是像背部疼痛或防止老年人摔倒这样的无聊的东西。

Spinal 脊的；脊柱的；脊髓的 surgeons, for their part 就……而论;就……来说, often *take a dim*(`=*take a dim view of sb/sth* : to disapprove of sb/sth; to not have a good opinion of sb/sth 对…持不赞成（或怀疑）态度；对…没有好感; / dim : not giving any reason to have hope; not good 不明朗的；不乐观的;/暗淡的；昏暗的；微弱的`) *view* of evidence that `主` what they *do* `系` *may be* ineffective 无效果的；不起作用的；不奏效的.

Surgical training *is based on* an apprenticeship(`=a period of time working as an apprentice ; a job as an apprentice 学徒期；学徒工作`) model.

====
- apprenticeship => 前缀ap-同ad-. -prend, 来自prehend的缩写，见apprehend. 即抓住知识，学徒。
====

“You *learn from* a master, a great guru 专家；权威；大师;古鲁（印度教或锡克教的宗教导师或领袖）, and you *do* what they taught you. You *don’t learn from* a paper in the British Medical Journal,” *says* Andrew Carr, who *heads* the department of orthopaedic (关节和脊柱)矫形的 surgery at Oxford University.

Surgeons *generally consider* an operation 宾补 successful [if ① the incision(`=a sharp cut made in sth, particularly during a medical operation; the act of making a cut in sth 割口；（尤指手术的）切口；切开`) *is* small, ② things(`= the general situation, as it affects sb 形势；局面；情况；事态`) *heal*(v.)治愈（病人）；使又愉快起来 nicely and ③ there *are* no complications 并发症], *says* Maurits van Tulder from Vrije University in Amsterdam.

If they *ever hear back* from patients, that *is* usually from those ([*for whom*] the operation *worked*) --  which *leads* surgeons *to believe that* it *works* [most of the time].

就脊柱外科医生而言，他们常常对那些"他们传统的医疗做法可能是无效的"证据, 持抗拒态度。外科训练是以学徒制为基础的。“你向一位大师学习，一位伟大的专家，然后按照他们教你的去做。你不会从《英国医学杂志》上的一篇论文中学到东西。阿姆斯特丹自由大学(Vrije University)的毛里茨·范·图尔德(Maurits van Tulder)说，外科医生通常认为，如果切口小、愈合良好、没有并发症，手术就是成功的。如果他们曾经收到过病人的反馈，那通常也只是来自于那些一部分手术起了作用的病人的反馈，这却让外科医生误以为手术在大多数情况下都是有效的。

Though research on surgical outcomes(n.)(`=outcome : the result or effect of an action or event 结果；效果`) *is becoming* a lot more widespread(a.), it *is* still hard *to convince* 使确信；使相信；使信服 surgeons *that* `主` what they *have been doing for* most of their careers `系` *is* ineffective, *says* Dr Carr.

It *is* also hard *to convince* patients *that*, when it *comes to* treatment(n.) 治疗；疗法；诊治, less *may be* more.

*Told that* `主` the best thing *they can do about* back pain `系` *is* `宾` *exercise* their body /and their patience, they *often think* they *are being fobbed off*(`=*fob sb off (with sth)* : （用不实之词）搪塞，欺骗;/（把劣质的或不想要的商品）骗售给`); `主` a deluge 涌现的事物；蜂拥而至的事物;暴雨；大雨；洪水 of online marketing for ineffective treatments `谓` *does not help*.

====
- *fob sb off (with sth)* : (1) *to try to stop sb asking questions or complaining [by telling them sth that is not true]* （用不实之词）搪塞，欺骗 +
-> Don't let him *fob you off [with* any more excuses]. 别让他再以任何借口哄骗你了。 +
(2) *to give sb sth (that is not what they want) or ((省略了that) is of worse quality than they want)* （把劣质的或不想要的商品）骗售给
-> He was unaware that *he was being fobbed off [with* out-of-date stock]. 他没有意识到对方正向他骗售过期存货。

- deluge => de-, 向下，离开。-lug, 冲洗，喷流，词源同lava, dilute.
====

Some *harangue*(`=to speak loudly and angrily in a way that criticizes sb/sth or tries to persuade people to do sth 呵斥；大声谴责；慷慨激昂地劝说`) their doctors *for* scans or injections 注射, or *find* a new more biddable(a.)(`= (of people 人) willing to obey and to do what they are told to 顺从的；听话的`) one.

For a busy doctor, *says* Rachelle Buchbinder of Monash University in Australia, “*it*’s easier *to prescribe* 给…开（药）；让…采用（疗法）；开（处方） an x-ray *than* explain(v.) why you don’t need one.”

====
- harangue => 来自中古法语harangue,来自意大利语aringo,公共广场，词源同ring,环，圈。由广场引申词义慷慨陈词，长篇演讲，后用于指广场批斗，呵斥，大声谴责。
====
卡尔博士说，尽管对手术结果的研究, 越来越广泛，但仍然很难让外科医生相信，他们在职业生涯的大部分时间里所做的工作, 都是无效的。也很难让病人相信，在治疗方面, 少即是多。当患者被告知, 他们对背痛能做的最好的事情, 就是锻炼身体和保持耐心时，他们经常认为自己被骗了；网上的对无效治疗方法的铺天盖地式营销推广, 对患者没有好处。一些患者喋喋不休地要求医生对他们进行扫描或注射，或者就找一种更听话的医生来做这些事。澳大利亚莫纳什大学的Rachelle Buchbinder说，对于一个忙碌的医生来说，“给患者开处方, 让他们去做x光扫描, 比向他们解释为什么不需要这样做, 更容易。”

Once pain *becomes* chronic, `主` *persuading* sufferers *that* the cause *is not* a fixable physical defect(n.)(`=a fault in sth or in the way it has been made which means that it is not perfect 缺点；缺陷；毛病`) `谓` *becomes* much harder.

Graeme Wilkes, a British doctor, *says that* he *might spend* an hour *telling* a patient *that* the things seen on his MRI 核磁共振成像 *may not be* the reasons for his back pain, and *that* a spinal injection *is* unlikely to help.

“`主` The reason they’*ve got* back pain `系` ① *is that* they *have* financial problems, marital problems, disabled 有残疾的 children, they *are not sleeping* at night -- ② *not* those changes in their MRI scan,” *says* Dr Wilkes.

“And they *go home* and *someone says* ‘Oh, that’s absolute rubbish that you *can’t get* an injection, because my mate 朋友；伙伴 at work(`=*at work* : having an effect on sth 起作用`) *had it* /and he *was* much better afterwards. *Don’t listen to* them, *go back to* your GP(`=a doctor who is trained in general medicine and who works in the local community, not in a hospital. (abbreviation for 'general practitioner' ) 全科医生，普通医师（全写为 *general practitioner*，在社区而非在医院工作）`) and *get referred*’.”(`=refer : to look at sth or ask a person for information 查阅；参考；征询`)

一旦疼痛变得慢性，说服患者相信原因是"不可修复的身体缺陷"(*原文中是双重否定, 那我们就直接翻译成肯定*), 就变得困难得多。英国医生格雷姆·威尔克斯(Graeme Wilkes)说，他可能会花一个小时告诉病人，他的核磁共振成像上看到的东西可能不是他背部疼痛的原因，脊椎注射不太可能有帮助。威尔克斯博士说：“他们背部疼痛的原因是他们有经济问题，婚姻问题，残疾的孩子，或他们晚上睡不着觉，而不是核磁共振扫描中显示的那些变化。”“他们回到家，有人说‘哦，你不能打针完全是胡说八道，因为我的同事打了针，他后来好多了。别听他们的，回你的全科医生那里去咨询吧。'"

But `主` the biggest reason why so many people with back pain *get* the wrong treatments `系` *is that* governments and insurance plans *pay for* them.

[In America, Australia and the Netherlands] health plans *pay for* back operations that *cost* $25,000-100,000 apiece(`=having, costing or measuring a particular amount each 每人；每个；各`).

American plans *often support* the alternative therapy(`=the treatment of a physical problem or an illness 治疗；疗法`) (*offered by* chiropractors 脊椎推拿治疗者).

There *is* some evidence that this *may do* some good in back pain, but the research *is* patchy(a.)(`=not complete; good in some parts, but not in others 不完整的；参差不齐的;/existing or happening in some places and not others 零散的；散落的；分布不匀的`) and any benefits `表` small and short-lived 短暂的.

====
- patchy => 来自patch,补丁。即打补丁的，零散的。 +
-> The grass *was dry and patchy*(a.)(`=existing or happening in some places and not others 零散的；散落的；分布不匀的`). 草都干了，东一片西一片的。 +
-> It was *a patchy*(`=(NAmE also also *spotty*) not complete; good in some parts, but not in others 不完整的；参差不齐的`) *performance*. 那是一场素质不齐的演出。
====

Yet the same plans *typically offer* little support *for* physiotherapy(n.)(`=the treatment of disease, injury or weakness in the joints or muscles by exercises, massage and the use of light and heat 物理治疗法；理疗; 通过锻炼、按摩和使用光和热来治疗疾病、损伤或关节或肌肉无力`) to the same end(`=an aim or a purpose 目的；目标`).

[If a therapy 治疗；疗法 *has been accepted* by an insurance company, or a government scheme like America’s Medicare 医疗保障制度，老年保健医疗制度（美国政府向65岁以上的人提供的医疗保险）], *it* is very hard *to get* it *removed*, even if `主` evidence for effectiveness 有效性;效力 `谓` persistently 反复地; 一直 *fails to turn up*(`=*turn up* : (of a person 人) to arrive 到达；来到；露面; / (of an opportunity 机会) to happen, especially by chance 偶然出现；到来 `).

“Once they are in, *it* is hard *to take them out*(`=*take sth out* : 切除，摘除（人体内的一部分）`),” *says* Dan Cherkin from the Kaiser Permanente Washington Health Research Institute.

The manufacturers 制造商 of medical devices *are very good at* lobbying(v.) *to get* them *covered as* treatments. They *are* also “incredibly effective” in *marketing*(v.)推销；促销 their wares *to* doctors, *says* Richard Deyo of Oregon 俄勒冈州 Health and Science University.

但是，这么多背痛患者接受错误治疗的最大原因是, 政府和保险计划会为他们买单。在美国、澳大利亚和荷兰，医疗计划会支付背部手术的费用，每个手术的费用在25，000-100，000美元之间。美国的计划通常会由支持脊椎按摩师提供的替代疗法。有一些证据表明，这可能会对背部疼痛有一些好处，但这项研究参差不齐，任何好处都很小，而且是短暂的。然而，同样的计划, 却通常为同样目的的物理治疗法, 提供的支持很少。如果一种疗法已经被保险公司或像美国联邦医疗保险(Medicare)这样的政府计划接受，即使它们"有效性"的证据一直没有出现过，也很难将其移除。来自凯撒永久华盛顿健康研究所的丹·切尔金说：“一旦它们被包含进来，就很难把它们删除出去。”医疗器械制造商非常善于游说，希望将它们纳入医疗计划的覆盖范围。俄勒冈健康与科学大学的理查德·德约(Richard Deyo)说，他们在向医生推销产品方面, 也“令人难以置信地有效”。


Back pain *is* big business for many surgeons, doctors and chiropractors(`=a person whose job involves treating some diseases and physical problems by pressing and moving the bones in a person's spine or joints 手疗法医师；脊骨神经科医生`).

“If we *stop doing* low-value care, some entire professions （需要专门技能，尤指需要较高教育水平的某一）行业，职业 *have to change fundamentally* what they do,” *says* Lorimer Moseley of the University of South Australia after *enumerating* 列举; 枚举 a long list of ineffective treatments.

[In some systems] cupidity(n.)贪心；贪婪 *encourages* such things.

In America, where procedures 手术 *are* more lucrative(a.)(`=producing a large amount of money; making a large profit 赚大钱的；获利多的`) *than* talking to patients, an unscrupulous(`=without moral principles; not honest or fair 不道德的；无道德原则的；不诚实的；不公正的`) doctor *might prefer(v.) to spend* a 15-minute appointment 约会；预约；约定 *giving* a patient an injection *rather than* some education, *just as* a harried(`=If someone harries you, they keep bothering you or trying to get something from you. (不断)骚扰; 纠缠`) one *might*.

====
- cupidity => 爱神丘比特（Cupid）, 丘比特的名字Cupid来自拉丁文Cupido，意思是“欲望、爱”，等于英语中的desire、love。英语单词cupidity与它同源，表示“贪婪、贪欲”。
- scruple => 来自拉丁语 scrupulus,顾忌，顾虑，良心不安，来自 scrupus,小石子，碎屑，可能来自 PIE*sker, 砍，切，词源同 scar,scree,scrap.比喻用法。
====
对于许多外科医生、医生和脊椎指压按摩师来说，背痛是一项大生意。南澳大利亚大学的Lorimer Moseley在列举了一长串无效的治疗方法后说:“如果我们停止做低价值的治疗，一些行业就整个必须从根本上改变他们所做的事情。” 在某些体系中，贪婪助长了这种事情。在美国，做手术比与病人交谈更有利可图，一个无道德的医生,可能更愿意花15分钟的预约时间给病人打针，而不是像一个饱受折磨的医生那样对病人来做教育。

Other countries *have had* some success(n.) with an approach *called* “*Choosing Wisely* 明智地；聪明地；精明地”, in which doctors *explain to* patients the evidence on the effectiveness of various treatment options /and *decide together* what *is* best [*given* 考虑到；鉴于 each patient’s personal goals (which *could range [from]* simply *wanting to be able to* play with their grandchildren *[to]* cycling or running)].

In Britain there *has been* a determined(a.)(`=showing a person's determination to do sth 坚定的；坚决的；果断的;/决心；决定；决意`) move(n.) towards triage(n.)(`=the process of deciding how seriously ill/sick or injured a person is, so that the most serious cases can be treated first 患者鉴别分类；伤员鉴别分类；治疗类选法; 决定一个人的病情有多严重的过程，这样最严重的病例可以先得到治疗`) which *assigns* 分派；指派 back-pain patients *to* more or less intensive(`=involving a lot of work or activity done in a short time 短时间内集中紧张进行的；密集的`) treatment *depending on* the complexity  复杂，复杂性 of their problems.

====
- triage => 来自 try,甄选，选出，尝试，审理，-age,名词后缀。后在一战中指对伤员根据受伤情况进行 分类。
====

In Australia some emergency 突发事件；紧急情况 rooms 急诊室 *have started* *sending* some back-pain patients (*brought in* by ambulance 救护车) *[straight 直接；径直；立即] to* physiotherapists 物理治疗师；理疗师, which *avoids* a significant(`=large or important enough to have an effect or to be noticed 有重大意义的；显著的`) amount of hospitalisation(n.)(`=住院治疗（等于hospitalization）`).

其他国家已经在一种名为“明智的选择”的方法上取得了一些成功，医生会向患者介绍各种疗法选项的有效性程度, 并共同决定哪种疗法是最好的选择. 这个共同的决定, 会考虑进每位患者的各人目标, 范围包括, 从最简单的想要和他们的孙子孙女一起玩耍，到更高程度的能够骑自行车或跑步.  +
在英国，已经有了一项坚定的分流措施，根据背痛患者所面临问题的复杂程度，来分类对他们进行或多或少的强化治疗。 +
在澳大利亚，一些急诊室已经开始将一些由救护车送来的背痛患者, 直接送到理疗师那里，这样就避免了大量人都住院治疗。


*Choosing poorly*(`=in a way that is not good enough 糟糕地；不如意；不足`)

糟糕的选择

But [when professional associations 专业人员协会 in America *urged* doctors *to take up*(`=*take sth up* : to start or begin sth such as a job 开始从事`) the Choosing Wisely model] their campaign  运动（为社会、商业或政治目的而进行的一系列有计划的活动） *made almost no difference to*(`=*MAKE A, NO, SOME, ETC. DIFFERENCE (TO/IN SB/STH)* : to have an effect/no effect on sb/sth 有（或没有、有些等）作用，关系，影响`) back-pain treatment -- perhaps because doctors *were* under no obligation 义务；职责；责任 to change, *says* Dr Deyo.

====
- *MAKE A, NO, SOME, ETC. DIFFERENCE (TO/IN SB/STH)* : to have an effect/no effect on sb/sth 有（或没有、有些等）作用，关系，影响 +
-> Changing schools *made a big difference to* my life. 转学对我的一生有着重大影响。 +
-> *What difference will it make* if he knows or not? 他知不知道有什么关系吗？
====

Nor *has* `主` a change (in the advice (*provided by* the American College of Physicians)) `谓` *had* any great effect [as yet 到目前为止,迄今为止].

In 2017 the college *stopped recommending* medication 药物；药物治疗 *as* an initial response to back pain, *suggesting [instead]* acupuncture （中医）针刺疗法，针灸, yoga 瑜伽, tai-chi and psychological therapies 心理疗法 *aimed at* reducing(v.) stress, all of which *have been shown*(`=to prove that you can do sth or are sth 证明；表明`) to reduce(v.) pain-related disability.

Insurers 保险公司 *have taken note*(`=*take note (of sth)* : to pay attention to sth and be sure to remember it 注意到；将…铭记在心`), with *some* (now *covering* some or more of these alternatives).

That will make *it* easier for doctors *moved*(`=to take action; to do sth 采取行动；做（事）`) *to change* their practice to do so.

====
- acupuncture =>  -acu-尖,刺 + -punct-刺 + -ure名词词尾
====

但是当美国的专业协会, 敦促医生采取这个"明智的选择"模式时，他们发起的这个运动, 对背痛治疗行业, 几乎没有产生什么效果 ——也许是因为医生们没有义务去改变，Deyo博士说。 +
美国医师学会(American College of Physicians)建议的改变, 迄今也没有产生任何重大影响。 2017年，该学会不再将药物治疗作为背痛的首选应对方式，而是建议采用针灸、瑜伽、太极和旨在减轻压力的心理疗法，这些疗法都已被证明可以减少与疼痛相关的残疾。保险公司已经注意到了这一点，其中一些公司现在已经覆盖了这些疗法中的部分或更多数量的替代疗法。这将使医生更容易改变他们的传统做法。

Another approach *might be* to nudge(v.)(`= to push sb/sth gently or gradually in a particular direction （朝某方向）轻推，渐渐推动;/（用肘）轻推，轻触`) doctors incrementally 逐渐地，逐步地；递增地, rather than *to change* their practices [*once and for all*(`=*once and for all* : now and for the last time; finally or completely 最终地；最后地；彻底地；一次了结地`)].

`主` *Tweaking* the interface of the electronic systems (doctors *use* to order(v.)(`=to use your position of authority to tell sb to do sth or say that sth must happen 命令；指挥；要求`) MRIs) *so that* it *takes* them *longer* to place(v.)(`=to give instructions about sth or make a request for sth to happen 下指示；请求`) an order(n.) `谓` *has been shown* to reduce(v.) the number of unnecessary scans.

`主` *Adding* a pop-up reminder (*explaining* `主` why imaging 成像 `系` *is* frequently unnecessary) `谓` *has also shown* effects.

====
- place : v. *to give instructions about sth or make a request for sth to happen* 下指示；请求 +
-> *to place a bet/an order* 下注；下订单 +
-> We *placed an advertisement for a cleaner* in the local paper. 我们在当地报纸上登了广告，招一名清洁工。
====

另一种方法可能是循序渐进地推动医生，而不是一劳永逸地改变他们的做法。研究表明，调整核磁共振成像的电子系统的界面, 让其对医生下达的指令, 反应间更长，可以减少不必要的扫描次数。添加一个弹出式提醒，解释为什么扫描成像经常是不必要的，也显示出拥有效果。


Disability-benefit 福利费（政府对失业者、病人等提供的补助金） systems *matter* a lot, too.

[In many countries] benefit systems *give* ① people (*signed off* 签字认可；签名赞同 with back pain) 双宾 few incentives 激励；刺激；鼓励 *to improve*, and ② their erstwhile(a.)以前的；先前的；过去的；往昔的 employers 雇主 双宾 no incentive *to encourage them back* rather than(`=肯前否后`) *find* someone else.

====
- erstwhile => erst, 最早的，ere最高级。
- ... and their erstwhile employers *no* incentive to encourage them back *rather than* find someone else. +
-> *这句里面, rather than 表示"宁愿...而不愿...". 照理是"肯前否后". 但因为本句中前面一半中有"no", 就导致整个句子意思反过来了, 变成"否前肯后".* +

- 注意：*rather than 后接不定式时，不定式可以带to，也可以不带to*, 如: +
-> I decided to write *rather than* (to) telephone. 我决定写信而不打电话。 +
*但rather than位于句首时，则只能接不带to 的不定式*。如： +
-> *Rather than* allow the vegetables *to go bad*, he sold them at half price. 他唯恐蔬菜烂掉，把它们以半价卖掉了。 

- 注意: *rather than* 与 *would rather than* 是不同的! +
=> *"would rather...than...”句式，意思是“宁愿……而不愿……”，表示主观愿望，即在两者之中选择其一。* 例如： +
-> She'*d rather* die *than* lose the children. 她宁愿死也不愿失去孩子们。  +
=> *而 rather than 不与would连用时，表示客观事实，意为“是……而不是……；与其……不如……”。* 它连接的并列成分可以是名词、代词、形容词、介词(短语)、动名词、分句、不定式、动词等。 +
-> We should help him *rather than* he should help us. 是我们应该帮助他而不是他应该帮助我们。  +

更多的 rather than 用法小结, 见本页尾.
====

In the Netherlands, though, this *has changed*.

`主` Medical assessment 评定；核定；判定 for disability benefits `谓` *does not kick in*(`=*kick in* :to begin to take effect 开始生效（或见效）`)  for two years [after a patient *reports* sick], and [during this time] employers *must pay* the sick employee 双宾 70-100% of their wages.

Employers and employees *are also required* by law *to agree* a return-to-work 重返工作岗位 plan.

After the country *switched to* this system, in 2006, the total number of sick days (for back pain) *fell* by a third.

The return-to-work rate [after a three-to-four-month sick leave due to back pain] *is* now 62% in the Netherlands. [In neighbouring Germany] it *is* only 22%.

残疾福利制度也很重要。在许多国家，福利制度对背痛患者提供的激励很少，也没有对患者以前的雇主给予激励, 让他们鼓励背痛患者回来上班, 而不是重新另雇他人。然而，在荷兰，这种情况已经改变。伤残津贴的医疗评估, 在患者报告他们生病后的两年内不会生效，在此期间，雇主必须向生病的员工支付工资的70%-100%。法律还要求雇主和雇员就重返工作计划达成一致。 +
2006年，在这个国家改用这一制度后，因背痛而请病假的总天数, 减少了三分之一。在荷兰，由于背部疼痛而休完三到四个月病假后的返岗率, 目前为62%。而在邻国德国，这一比例仅为22%。

`主` Drivers 驱动因素 for such change `系` *are* hard *to come by*(`=*come by sth* : to manage to get sth 设法得到（或获得）;/to receive sth 收到；得到;/*come by* :（为看望某人）作短暂拜访`) in part because, *as* Dr Maher *says*, back pain *is* largely invisible.

====
- *come by sth* : +
(1) *to manage to get sth* 设法得到（或获得） +
-> Jobs are hard *to come by* these days. 如今找工作很难。 +
(2) *to receive sth* 收到；得到 +
-> How did you *come by that scratch* on your cheek? 你脸颊上的抓伤是怎么来的？
====

People *do not die from* it /and there *are* no “back-pain survivors” 幸存者 *to spearhead*(`=to begin an activity or lead an attack against sb/sth 做…的先锋；带头做；领先突击`) lapel （西服上衣或夹克上部胸前的）翻领-ribbon （用于捆绑或装饰的）带子；丝带;绶带；勋带 campaigns for change.

Few national medical plans *even mention* back pain.

Sufferers *are often viewed as* impostors 冒名顶替者；冒名行骗者, or *told that* it *is* all [in their heads].

Though other aspects of a patient’s life *do impede*(`=to delay or stop the progress of sth 阻碍；阻止`) recovery(n.) from back pain, many people *cannot easily take control over* the context of their life, *still less* 更不用说；更何况 the content of their heads.

The lack of a lobby 游说团体 *accounts [in part] for*(`=to be the explanation or cause of sth 是…的说明（或原因）;/解释；说明`) the absence of more impressive projects *to move beyond* medical devices and drugs.

====
- impede => im-向内 + -ped-足 + -e → 插一脚进去 → 阻碍
====

这种改变的驱动力很难获得，部分原因是，正如马赫博士所说，背部疼痛在很大程度上是看不见的。人们不会死于此病，也没有“背痛幸存者”带头发起变革的运动。很少有国家医疗计划提到背部疼痛。患者经常被视为冒名顶替者，或者被告知这一切都是他们自己头脑中的想法。尽管患者生活的其他方面, 确实会阻碍他们从背痛中恢复过来，但许多人无法轻易地掌控自己生活的内容，更不用说他们头脑中的内容了。游说团体的缺乏，在一定程度上也导致了除了医疗设备和药物之外，没有更多令人印象深刻的疗法项目。

[In 2018] Dr Buchbinder *was* one of the authors of a series of studies on back pain *published in* the Lancet （医生用的）柳叶刀，小刀 which they *pitched*(`=to throw sb/sth with force 用力扔；投；抛;/ *~ sth (at sb) /~ sth (as sth)* : to aim or direct a product or service at a particular group of people （使产品或服务）针对，面向；确定销售对象（或目标市场）`) *to* the journal *in the hope that* `主` summarising(v.)(`=summarize : to give a summary of sth (= a statement of the main points) 总结；概括；概述`) the debacle(n.)(`=an event or a situation that is a complete failure and causes embarrassment 大败；崩溃；垮台；灾祸`) in rich countries `谓` *would warn* developing countries *not to follow suit*(`=follow suit : 跟着做；学样;鹦鹉学舌`).

====
- debacle => de-, 不，非，使相反。 -bacle, 杆，棍，支撑，词源同 bachelor, bacteria.即移除支撑，引申义崩溃。
- *follow suit* : follow是跟随的意思，而suit，可以指扑克牌四种花色里的任意一种，两个词连起来follow suit，跟着出同样的花色，引伸为“效仿，跟着做”。
====

But when the researchers *began* to compile 编写（书、列表、报告等）；编纂 the data, she says, they *discovered that* in poor countries the horse *had already bolted* （马等受惊）脱缰;跑开；（尤指）逃跑.

[In India, Brazil, China, Nepal, Iran and other developing countries] doctors *are already prescribing* drugs, injections and X-rays *for* simple back pain.

[In some urban areas of India and Africa] opioids 阿片类药物 *can be easily bought* from the roadside chemists 药房；（通常也出售肥皂、化妆品等的）药店 where many poor people *go [first] for* aches and pains.

2018年，布赫宾德博士是“柳叶刀”上发表的一系列关于背部疼痛研究的作者之一，他们向该杂志推销这些研究，希望, 总结富裕国家的崩溃, 能警告发展中国家不要效仿。但她说，当研究人员开始汇编数据时，他们发现在贫穷国家，马已经脱缰。在印度、巴西、中国、尼泊尔、伊朗和其他发展中国家，医生已经开始为单纯的背痛开药、注射和拍x光片。在印度和非洲的一些城市地区，阿片类药物可以很容易地从路边的药店买到，许多穷人首先去那里治疗疼痛。

Mr Moore, for his part, *has not taken* pain medication 药；药物 since 1997. *To keep* his pain at a manageable level, he *starts* his day *with* stretching(v.) at home for half an hour, *followed by* an hour and a half at the gym. And he *leads* a full life.

就摩尔而言，他自1997年以来就没有服用过止痛药。为了将疼痛控制在可控范围内，他每天都会先在家做半个小时的伸展运动，然后去健身房锻炼一个半小时。他的生活很充实.

Correction (January 16th 2020): An earlier version of this article *stated incorrectly that* Mr Moore’s doctor *was* in Peterborough and *that* he *was given* steroid 甾族化合物；类固醇 injections.

更正(2020年1月16日):这篇文章的早期版本错误地指出摩尔先生的医生在彼得伯勒，并给他注射了类固醇。



---

== 15. Back pain is a massive problem which is badly treated 纯净版

Why `系` *are* `主` better approaches *to helping* sufferers `表` so slow to spread?

Jan 18th 2020 |

PETE MOORE *was* 43 when he *woke up* one autumn morning with back pain *so* excruciating *that* he struggled to dress(v.) himself. His doctor in Romford, an English town, *referred* him *to* hospital for an MRI scan; this *showed that* some of the spongelike discs that separate the spine’s vertebrae *were bulging out of* the slots (*into* which they *customarily fit*). Such “slipped” discs *can be caused by* an injury; but they *are* also the sort of thing which *can just happen* with increasing age.

Mr Moore *received* a prescription for opioids to help him cope with the pain; but the pain *persisted*, and he *found* himself becoming loopy. *Unable to work* or *do much else*, Mr Moore, who had been a painter, *sank into* depression. Three years into his ordeal(n.), he *says*, he *was “thinking of* ending(v.) it all”.


Back pain *does not, in and of itself, kill* people. But it *makes* a huge number of lives a misery. In most countries (for which there *are* reliable figures), whether rich or poor, back pain *is* the top cause of disability, *measured by* the aggregate number of years (*lived in* poor health). That burden *is decreasing* (see chart) but only very slowly.

The costs, however, *have been rising* quite quickly -- and are enormous. In 2013, according to one study, $88bn *was spent on* medical treatments for back and neck pain in America, *not far short of* the $115bn spent on cancer (more recent figures *have not been analysed* in a comparable way). A great deal of this money *seems*, sadly, to do little good.

Doctors *used to think that* back pain *was* almost entirely the result of mechanical damage to tissue *beyond* the capacity of X-rays to detect. The advent of MRI scans *showed* this was not true. `主` A definitive physical cause -- such as a fracture, a tumour, pressure on a nerve, infection or arthritis -- `谓` *is found* in 5-15% of people with back pain. `主` The rest ``谓` *is all labelled as* “non-specific”, and there *is* increasing evidence that it is not mechanical in origin.

Back pain, *like* all pain, *is experienced* in the brain *not* the body; `主` nerves (coming in) `谓` *tell* the brain *that* something is amiss, and the brain *projects* an appropriate sensation of pain. Researchers who specialise in pain *increasingly believe that*, in most cases, chronic pain *means that* the system *has become damaged* [in some way] that *keeps it switched on*. “It’s like a fire alarm that *goes off* after the fire has been extinguished,” says Lucie Knight, a psychologist at a pain clinic in St Thomas’ Hospital, in London. Back pain *may also be related to* other aspects of a person’s life not going well.

`主` *Taking this view seriously* `谓` *throws into doubt* a great deal of the medical treatment of back pain -- much of which, in effect, *seeks* *to silence*(v.) the maddening sound of the fire alarm *by putting out a fire* that isn’t there. But it *does not offer* an obvious medical alternative. Some pain medicines, such as paracetamol, *do not work at all* for back pain. `主` Opioids, for all their reputed(a.) analgesic potency, `谓` *offer* back-pain relief [*little*] [*if any* better than options such as ibuprofen]. Their continued use(n.) *often makes* pain worse *rather than* better, and *is highly likely* to cause addiction.

`主` Drugs (that *worked better* and *did less harm*) `系` *would be* a boon. But they *have proved* hard to develop. `主` The mechanisms in the nervous system and brain which *generate* pain `系` *are* complex, and *can doubtless go wrong* in a variety of ways, says Steve McMahon of King’s College London. He *thinks that* the development of drugs for chronic pain *has* a poor record because `主` the people they are tried on `谓` *have* a range of different problems.

Evidence of ineffectiveness *has not stopped* doctors *from* writing(v.) prescriptions for the drugs they have. `主` The prevalence of chronic back pain `谓` *provided* a huge expanse of fertile ground *for* the deceptive(a.) marketing and poor prescription (behind America’s opioid epidemic(n.)) (see Bartleby). [In many countries] doctors also *frequently prescribe* painkillers (called gabapentinoids), despite strong evidence from trials that, *[as far as]* treating back pain *[goes]*, they *offer* no benefits.

There *are* also a lot of treatments for the back itself. Spines *are injected with* cement-like mixtures /or *fitted* with various types of medical hardware. Vertebrae *are fused together*, discs *excised* /or *tampered with* [in various ways]. Yet -- unsurprisingly, if *it is* largely the pain mechanism (which is the problem) -- there *is* a growing body of evidence that `主` the benefits (all this *offers to* most patients) `系` *are* limited or non-existent.

`主` Even *just looking at* the back `谓` *causes* problems. Only 1-5% of people with back pain *have* a problem that *requires* urgent treatment, such as an infection or a tumour; [in such cases] the pain *will tend to be accompanied by* other symptoms too, such as weight loss, fever or incontinence. [In America and western Europe] guidelines *say that* it is [only when such red flags *are present*] that a patient presenting with back pain *should promptly be given* an x-ray or an MRI scan. Yet general practitioners and hospitals *routinely ignore* this, *sending* 40-60% of people with back pain *to be scanned* -- far more than they did 20 years ago. [According to Jan Hartvigsen of the University of Southern Denmark] there is a broad consensus that `主` about 80% of such scans `系` are useless.

That *might be* fine [if the scans *were* sometimes helpful and never harmful]. But few bodies *are* completely normal, and `主` *learning of* your particular “abnormalities” [in a medical setting and while suffering] `系` *is* alarming(a.) [even if a healthy back *might look just as* odd]. Disc “degeneration” *is seen* [in roughly half of young and middle-aged adults with back pain], but also [in a third of those with no pain at all]. Some 40% of people with back pain *have* disc protrusion, a form of “slipped” disc; but *so do* nearly 20% of people who are pain-free.

Both patients and doctors, though, *tend to think that* if they can see something they should do something. Some sufferers *catastrophise*(v.) the news *into* the idea that they *have* a broken, fragile back and *start avoiding* normal physical activity -- not least, says Ms Knight of St Thomas’, because doctors *often fail to explain to them that* `主` abnormalities `系` *are*, in fact, quite normal, and *that* `主` degeneration `系` *can basically be* wear and tear. `主` The stiffness and weakening of the muscles (this inactivity *brings*) `谓` *often makes* things worse. And doctors *may take* abnormalities *as* a cue(n.) for further medical attention. Many studies *have confirmed that* `主` patients who *receive* unwarranted imaging [in the first few weeks of back pain] `系` *are more likely* to have surgery and unnecessary follow-up tests *than* similar patients (*spared* the scans) -- but that they *enjoy* no benefits [*in terms of* pain reduction or lessened disability].

In 2011 Cigna, an American insurance company, *ran* a follow-up study on patients who *had undergone* procedures (*in which* `主` vertebrae `谓` *are stitched together [with* implanted bolts and braces]). “Spinal fusion” of this type *is* a frequently used surgical *response to* back pain that *is associated with* the degeneration of spinal discs; in 2015 there *were* roughly 85,000 such surgeries in America. The company *found that* [two years after treatment] 87% of customers *were* still in pain (severe(a.) enough for medication or some other treatment); 15% *had* more surgery.

This *is going to hurt*

It all *sounds* depressing. It *need not be* so. There *are* ways of *dealing with* back pain that *waste* much less money and *leave* patients less distressed and *with a greater sense of* their own agency.

Mr Moore, the patient (*with whom* this story *began*), *tried to come to terms with* his disabling pain *by starting* a support group *for* fellow sufferers. `主` A psychologist from St Thomas’, which *has* the biggest pain clinic in Europe, `谓` *came to talk to them about* “graded exercise” and the importance of *pacing* themselves when *going out and about*. “Nobody *had told me* I could do these things,” says Mr Moore. In 1996, three years after back pain *had come to dominate* his existence, a two-week residential programme at the pain clinic *taught* him what it teaches people today: *exercise daily*; *accept* flare-ups *as* temporary setbacks; *don’t get fixated(a.) on* the pain. *Learning to keep going [this way]* “saved my life”, Mr Moore says.

The programme, *explains* Ms Knight, *aims not* to reduce pain *so much as* to add to life. People *naturally struggle against* the pain, which *means* they *are burdened with* the pain and the struggle too. “If you *can drop* the struggle,” says Ms Knight, “then you *have your hands free* to do more.” Patients *are taught* how to gradually *overcome* their fears of exercise and daily activities that *can cause* some pain. The goals that they start with *can be* as simple as calling a friend and meeting for a coffee, or attending a wedding. In a typical class of ten people, Ms Knight says, one or two *decide that* the approach is not what they want, and *may drop out*. Most of them *take away* at least some skills which *add to* their quality of life. One or two, like Mr Moore, *find* the programme *life-changing*.

Various countries *have tried to encourage* people with back pain *to stay active*, with promising effects. One such campaign, in Australia, *is reckoned* to have led to a 15% reduction [in the number of doctor visits(n.) for back pain] and a 20% decrease [in related medical costs]. Such campaigns *appear to work best* when they *provide* practical advice *on* how to stay active and at work [*despite* the pain], and [when as well as *speaking to* the afflicted] they *enroll* employers, clinicians and unions *as* partners.

Activity *is not* a panacea, and if *leading* an active life with pain *is better than* withdrawing from the world, it *is still not* ideal. But `主` interventions like this `谓` *seem to offer people* more succour *than* highly medicalised approaches. Unfortunately, `主` medical schools, patient expectations and the policies of insurers and governments `谓` *all sustain* the latter.

All around the world, family doctors *are* woefully undertrained(a.) *to treat* common, unglamorous conditions such as bad backs. [In most medical curricula] `主` musculoskeletal conditions, like back pain, `系` *are* a minor feature. Back pain *is “not* sexy” for medical students, says Chris Maher of the University of Sydney. [Even if they *are going to be* family doctors] they *still want to hear about* cures for cancer and impressive forms of surgery, *rather than* ① humdrum stuff like back pain or ② *preventing falls* in older people.

Spinal surgeons, for their part, often *take a dim view of* evidence that `主` what they do `系` *may be* ineffective. Surgical training *is based on* an apprenticeship model. “You *learn from* a master, a great guru, and you *do* what they taught you. You *don’t learn from* a paper in the British Medical Journal,” says Andrew Carr, who *heads* the department of orthopaedic surgery at Oxford University. Surgeons *generally consider* an operation successful [if the incision *is* small, things *heal nicely* and there are no complications], says Maurits van Tulder from Vrije University in Amsterdam. If they ever *hear back from* patients, that *is* usually from those (*for whom* the operation *worked*) -- which *leads* surgeons *to believe that* it *works* most of the time.

Though research on surgical outcomes *is becoming* a lot more widespread(a.), it *is* still hard *to convince* surgeons *that* `主` what they have been doing [for most of their careers] `系` *is* ineffective, says Dr Carr. It *is* also hard *to convince* patients *that*, when it *comes to* treatment, less *may be* more. *Told that* `主` the best thing they can do about back pain `系` *is* exercise(v.) their body and their patience, they *often think* they *are being fobbed off*; a deluge of online marketing for ineffective treatments *does not help*. Some *harangue* their doctors for scans or injections, or *find* a new more biddable one. For a busy doctor, says Rachelle Buchbinder of Monash University in Australia, “*it*’s easier *to prescribe* an x-ray *than* explain(v.) why you don’t need one.”

Once pain *becomes* chronic, *persuading* sufferers *that* `主` the cause is not a fixable physical defect `系` *becomes* much harder. Graeme Wilkes, a British doctor, *says that* he *might spend* an hour *telling* a patient *that* `主` the things *seen* on his MRI `系` *may not be* the reasons for his back pain, and *that* a spinal injection *is unlikely* to help. “The reason they’ve got back pain *is that* they have financial problems, marital problems, disabled children, they are not sleeping at night -- *not* those changes in their MRI scan,” says Dr Wilkes. “And they go home and someone says ‘Oh, that’s absolute rubbish that you can’t get an injection, because my mate at work *had it* /and he was much better afterwards. Don’t listen to them, go back to your GP and *get referred*’.”

But `主` the biggest reason why so many people with back pain *get* the wrong treatments `系` *is that* governments and insurance plans *pay for* them. [In America, Australia and the Netherlands] health plans *pay for* back operations that *cost* $25,000-100,000 apiece. American plans *often support* the alternative therapy *offered by* chiropractors. There *is* some evidence that this *may do* some good in back pain, but the research *is* patchy /and any benefits small and short-lived. Yet the same plans *typically offer little support for* physiotherapy (to the same end). [If a therapy *has been accepted by* an insurance company, or a government scheme like America’s Medicare], *it* is very hard *to get it removed*, even if evidence for effectiveness *persistently fails to turn up*. “Once they are in, *it* is hard *to take them out*,” says Dan Cherkin from the Kaiser Permanente Washington Health Research Institute. The manufacturers of medical devices *are* very good at *lobbying* to get them covered as treatments. They *are* also “incredibly effective” in *marketing*(v.) their wares *to* doctors, says Richard Deyo of Oregon Health and Science University.

Back pain *is* big business for many surgeons, doctors and chiropractors. “If we *stop doing* low-value care, some entire professions *have to change fundamentally* what they do,” says Lorimer Moseley of the University of South Australia [after *enumerating* a long list of ineffective treatments]. [In some systems] cupidity *encourages* such things. In America, where procedures *are* more lucrative(a.) *than* talking to patients, an unscrupulous doctor *might prefer to spend* a 15-minute appointment *giving* a patient an injection *rather than* some education, *just as* a harried one *might*.

Other countries *have had* some success(n.) with an approach *called* “Choosing Wisely”, in which doctors *explain to* patients the evidence on the effectiveness of various treatment options /and *decide together* what is best [given each patient’s personal goals] (which *could range from* simply wanting to be able to play with their grandchildren *to* cycling or running). In Britain there *has been* a determined move(n.) towards triage(n.) which *assigns* back-pain patients *to* more or less intensive treatment *depending on* the complexity of their problems. [In Australia] some emergency rooms *have started* sending(v.) some back-pain patients (*brought in by* ambulance) *straight to* physiotherapists, which *avoids* a significant amount of hospitalisation.

Choosing poorly

But [when professional associations in America *urged* doctors *to take up* the Choosing Wisely model] their campaign *made* almost no difference to back-pain treatment -- perhaps because doctors *were under no obligation* to change, says Dr Deyo. Nor *has* a change in the advice (*provided by* the American College of Physicians) *had* any great effect [as yet]. [In 2017] the college *stopped recommending* medication *as* an initial response to back pain, *suggesting* [instead] acupuncture, yoga, tai-chi and psychological therapies *aimed at* reducing(v.) stress, all of which *have been shown* to reduce pain-related disability. Insurers *have taken note*, with some [now] *covering* some or more of these alternatives. That will make *it* easier for doctors *moved* to change their practice to do so.

Another approach *might be* to nudge(v.) doctors incrementally, rather than *to change* their practices [*once and for all*]. `主` *Tweaking* the interface of the electronic systems (doctors *use* to order(v.) MRIs) *so that* it *takes* them longer *to place an order* `谓` *has been shown* to reduce(v.) the number of unnecessary scans. `主` *Adding* a pop-up reminder *explaining* why imaging is frequently unnecessary `谓` *has also shown* effects.


Disability-benefit systems *matter* a lot, too. [In many countries] benefit systems *give* people (*signed off* with back pain) few incentives to improve, and their erstwhile employers no incentive *to encourage them back* rather than *find someone else*. In the Netherlands, though, this *has changed*. Medical assessment for disability benefits *does not kick in* for two years [after a patient *reports* sick], and [during this time] employers *must pay* the sick employee 70-100% of their wages. Employers and employees *are also required by law* to agree a return-to-work plan. After the country *switched to* this system, in 2006, the total number of sick days for back pain *fell* by a third. The return-to-work rate [after a three-to-four-month sick leave *due to* back pain] *is* now 62% in the Netherlands. [In neighbouring Germany] it is only 22%.

`主` Drivers(n.) for such change `系` *are* hard *to come by* [in part] because, as Dr Maher says, back pain *is* largely invisible. People *do not die from it* /and there *are* no “back-pain survivors” *to spearhead* lapel-ribbon campaigns for change. Few national medical plans *even mention* back pain. Sufferers *are often viewed as* impostors, or *told that* it is all in their heads. Though other aspects of a patient’s life *do impede* recovery *from* back pain, many people *cannot easily take control over* the context of their life, still *less* the content of their heads. `主` The lack of a lobby `谓` *accounts [in part] for* the absence of more impressive projects *to move beyond* medical devices and drugs.

[In 2018] Dr Buchbinder *was* one of the authors of a series of studies on back pain (*published* in the Lancet which they *pitched to* the journal *in the hope that* `主` summarising(v.) the debacle in rich countries `谓` *would warn* developing countries *not to follow suit*). But when the researchers *began to compile* the data, she says, they *discovered that* {[in poor countries] the horse *had already bolted*}. [In India, Brazil, China, Nepal, Iran and other developing countries] doctors *are already prescribing* drugs, injections and X-rays *for* simple back pain. [In some urban areas of India and Africa] opioids *can be easily bought from* the roadside chemists where many poor people *go first for* aches and pains.

Mr Moore, for his part, *has not taken* pain medication since 1997. *To keep* his pain [at a manageable level], he *starts* his day *with* stretching(v.) at home for half an hour, *followed by* an hour and a half at the gym. And he *leads* a full life. ■

Correction (January 16th 2020): An earlier version of this article *stated incorrectly that* Mr Moore’s doctor *was* in Peterborough /and *that* he *was given* steroid injections.


---



rather than 用法小结  

rather than
rather than与would连用时，构成would rather ...than ...句式，意思是宁愿...而不愿...
例如：
She'd rather die than lose the children. 她宁愿死也不愿失去孩子们。

rather than 不与would连用时，表示客观事实，意为“是……而不是……；与其……不如……”。它连接的并列成分可以是名词、代词、形容词、介词(短语)、动名词、分句、不定式、动词等。现分述如下：
(1) 连接两个名词或代词
He is an explorer rather than a sailor. 与其说他是一个海员，不如说他是一个探险者。
You rather than I are going to go camping. 是你而不是我要去要野营。
注意：rather than 连接两个名词或代词作主语时，谓语动词应与rather than 前面的名词或代词在人称和数上保持一致。
(2) 连接两个形容词
The sweater she bought was beautiful rather than cheap. 与其说她买的这件羊毛衫便宜不如说它漂亮。
(3) 连接两个介词(短语)或动名词
We will have the meeting in the classroom rather than in the great hall. 我们是在教室里开会，不是在大厅里。
She enjoys singing rather than dancing. 她喜欢唱歌，而不喜欢跳舞。
(4) 连接两个分句
We should help him rather than he should help us. 是我们应该帮助他而不是他应该帮助我们。
(5) 连接两个不定式
I decided to write rather than (to) telephone. 我决定写信而不打电话。

注意：rather than 后接不定式时，不定式可以带to，也可以不带to, 如上句。但rather than位于句首时，则只能接不带to 的不定式。如：Rather than allow the vegetables to go bad, he sold them at half price. 他唯恐蔬菜烂掉，把它们以半价卖掉了。
(6) 连接两个动词
He ran rather than walked. 他是跑来的，而不是走来的。
注意：这里rather than 后用了walked，而没有用walk，表示客观事实，而不是主观愿望。如果换成walk，则作“宁愿……而不愿 ……”解。

would rather的用法
一、would rather意思是“宁愿、宁可、更、最好、还是为好”，后接动词原形,常省略为’d rather，表示优先选择的一种方式
其否定形式是would rather not do sth。would rather没有人称和数的变化，所有的人称一律用would rather。
“would rather+动词原形”是英语中常见的一个惯用句式，美国英语中多用had rather。would (had)在此决无“过去”之意，它是一个情态助动词，且无词性、时态变化。
例
Mr Li would rather not listen to rock music. 李先生不愿意听摇滚音乐。

If you’d rather be alone, we’ll all leave here.
如果你宁愿独自呆着，那我们都离开这儿。

He’d rather work in the countryside. 她宁可到农村去工作。

You would rather stay at home and do some reading this evening.
今晚你最好呆在家中读点书。

二、如果在两者中进行取舍，表示“宁愿……而不愿……，与其……宁可……”的意思时，则可用would rather…than…或would…rather than…的句型
例
I would rather watch TV at home than go to the cinema.
我宁可在家看电视而不愿去看电影。

The children would walk there rather than take a bus.
孩子们宁愿步行去那里而不愿乘公共汽车。

请注意
1） would rather…than…/would…rather than…也可以颠倒为：rather than…would…。
Would(rather)和than后都接不带to的动词不定式，若选用的动词相同，那么than 后的动词可以省略。
例 :
I would rather have noodles than rice. 我宁愿吃面条也不吃米饭。
He would rather drink wine than beer． 他喜欢喝红葡萄酒而不喜欢喝啤酒。

*Rather than work in such bad condition, he would give up. *
与其在这样差的条件下工作，他宁愿放弃。

2)使用would rather…than…句型时要注意“平行结构”，即在than 的前后要用两个同类的词或词组，如两个名词、两个不定式、两个介词短语等。
例:
I would rather go to work by bike than by bus. 我宁愿骑自行车也不愿乘公共汽车去上班。
I would rather talk with his mother than with his father. 我宁愿和他妈说话而不愿和他爸说话。

三、在疑问句式中，would rather 与would rather…than…中的would要放在主语之前
例
Would you rather stay here or go home? 你愿意呆在这里，还是回家？
Which would you rather have, apples or bananas? 你喜欢吃苹果还是香蕉？
Would you rather read a novel than read a poem?你宁愿看小说而不愿朗读诗歌吗？

四、would rather+从句，是一个常用的虚拟语气句型 Would rather+从句,谓语一般用过去时来表示现在或将来。其意为“宁愿……,还是…… 好些”“一个人宁愿另一个人做某事”。引导从句的that常省略。在谈到过去的动作时，谓语则用过去完成时。
例 John wants to see me today.
I would rather he came to tomorrow than today.
约翰今天想去看我。我宁愿他明天来看我而不是今天。
We’d rather he paid us the money tomorrow. 我们宁愿他明天付给我们那笔钱。
Don’t come tomorrow. I’d rather you came next weekend. 明天别来。我希望你下周末来。

请注意
1） 如果谈到过去的动作，也就是表示过去已经发生的事情。此时，主句一般为I had rather ,其（that）从句则用过去完成时。 例 Would rather you had not done that. 我真希望你没有做那件事。

2）如果只涉及主语本人而不涉及另一个人，则would rather之后不接that从句而接have done结构。
例 I would rather have gone to the theatre than stayed home night. 我真希望昨天晚上去看了戏而不是呆在家里。 He would rather be poor than have got money by dishonest methods． 他宁可穷也不愿意用不诚实的手段获取金钱。
Henry would rather that his girlfriend worked in the same department as he does．
亨利希望他的女朋友和他在一个部门工作。

五、would rather/sooner和prefer/would prefer的区别 would rather和would sooner之间一般没有区别，但经常接触到的是would rather。
例
Tom would rather/sooner read than talk． 汤姆宁可读书而不愿聊天。
Tom prefers reading to talking．汤姆喜欢读书而不喜欢谈天。

请注意
1）would rather后跟不带to的不定式+than+不带 to的不定式，
而prefer后跟动名词+to+动名词。有时prefer后面也可跟名词，而在would rather之后要求只带动词原形。
例
He prefers wine to beer．= He would rather drink wine than beer．
他喜欢喝红葡萄酒而不喜欢喝啤酒。

I prefer tennis to golf．= I’d rather play tennis than golf．
我喜欢打网球而不喜欢打高尔夫球。

2）某些 prefer+名词的情况不能用 would rather完全确切地表达出来：
He prefers dogs to cats．他喜欢狗而不喜欢猫。
He would rather have dogs than cats．他宁可养狗而不愿养猫。
很明显，这两句的意思并不完全相同。

3） would rather+不带to的不定式有时可代替 would prefer+带 to的不定式。
例
I’d rather fly than go by sea．=I’d prefer to fly．
我宁愿乘飞机也不愿乘船。 这两个结构后面带名词时情况也一样：

4 例
—Would you like some gin？
—I’d prefer a coffee．=I’d rather have coffee than gin．
—您想喝点杜松子酒吗？ —我想喝点咖啡。/我想喝点咖啡，不想喝杜松子酒。

4）would rather/sooner和would prefer后面都可跟完成式，但后者带to。
例 We went by sea but I’d rather have gone by air=I’d prefer to have gone by air．
我们是乘船去的，可我本想乘飞机去。（我愿意乘飞机去，可我的愿望未能实现。）这和 would like+不定式的完成式有点相似，would like+带to 的不定式的完成式也表示未能实现的愿望。