= 010 Slavery in the British Colonies (APUSH Period 2, 2.6)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义


What's up, beautiful people? Today we're covering slavery 奴隶制；奴役 in the British colonies. Like other European empires in the Americas that participated in the Atlantic slave trade, the English colonies developed a system of slavery that reflected the specific economic, demographic 人口结构的 and geographic characteristics of those colonies. Regardless, all of the British colonies participated in the Atlantic slave trade.

Now to be clear, slavery was much more important to some regions than others. But to be even clearer, every colony in North America had slavery. So what were the reasons the institution 制度；机构 of slavery developed? There was an abundance 大量；充裕 of land in the colonies, and over time indentured servants 契约仆役 were not meeting the labor needs of the colonies. As things slightly improved in Europe, fewer people were coming over to North America as indentured servants.

Events such as Bacon's Rebellion worried the colonial elite 上层集团；精英. Former indentured servants and formerly enslaved people were starting to make demands — crazy stuff like land that was promised, fair taxes, better treatment. And it seemed so much easier to switch to a labor source that was permanent, race-based, and treated the laborers as property. Add to all this there was a growing demand in Europe for colonial goods, and as a result slavery will develop in the British colonies.

As slavery developed throughout the British colonies, it differed in the various British colonial regions. In the New England colonies, a small number of enslaved laborers were used on small farms, and more were used in port cities to complete various tasks. Slavery was much more a part of the economic and social system of the Chesapeake and southern colonies, as large numbers of people were enslaved in these regions, serving as the primary labor source in the tobacco plantations 种植园 of Virginia and rice plantations of South Carolina. And as we've seen, in the case of South Carolina, enslaved people made up the majority of the population.

While slavery was a fact of life in the 13 colonies, the great majority of enslaved Africans would not be brought into the 13 colonies. The majority of enslaved people in the British colonies would be sent to the West Indies, and a large number of slaves would be sent to the Spanish Caribbean colonies as well, and to the Portuguese colony of Brazil.

Now we know 1619 marked the year in which enslaved people were brought into the British colonies for the first time in Virginia. And in the colonies, the form of slavery that developed was known as chattel slavery 动产奴隶制（将奴隶视为个人财产的制度）. Chattel slavery means that the enslaved person is legally rendered the personal property — or chattel 动产 — of the slave owner.

As chattel slavery became the dominant labor system in many southern colonies, new laws created a strict racial system. Examples of such laws include those that prohibit 禁止 interracial relationships, laws that define the descendants 后代 of African-American mothers (fancy way of saying children) as black and enslaved in perpetuity 永久地 — and by perpetuity we mean forever.

While indentured servants were not treated especially well, poor indentured servants did have certain rights. They couldn't be forced to work forever. Laws had been fought for in Europe protecting those individuals. On the other hand, no laws protected African people forcibly brought over. Laws such as bans on interracial unions, ensuring a child born to a person and slave was also born a slave, and the fact that enslaved people were considered chattel purposefully created a strict racial system.

But race is not real. The idea of race was created by people in power to justify 证明…有理 policies that made some folks a lot of money, and to justify the horrific institution of slavery. And in spite of how some history books tried to portray slavery — notice the enslaved person on the ship is wearing a suit and shaking hands as they're about to make some sort of business deal — I mean, talk about an intentional misrepresentation 歪曲；误传 of the reality of the dehumanizing 使失去人性的 institution that was slavery and the Middle Passage. Slavery was freaking awful.

In response to the dehumanizing nature of slavery, enslaved people resisted in both covert 隐蔽的 and overt 公开的 ways. Most resistance to slavery was covert — or rather concealed or hidden. For instance, many enslaved people continued to practice their cultural beliefs, spoke their native language, and incorporated elements of their African identity into this new society. Enslaved people also formed extended families, participated in work slowdowns, faked being sick, and various other methods of resistance to the institution of slavery.

Overt forms of resistance were not as common since various laws kept enslaved people under strict control, and open resistance could result in a person being physically punished, sold away from their family, or even killed. But there are examples of this form of resistance being utilized. Running away was a method of overt resistance with many risks, but was done. And perhaps the most threatening of the forms of resistance was in fact open rebellion 叛乱；反抗.

The Stono Rebellion of 1739 was the largest uprising 起义；暴动 of enslaved people in the North American colonies. Weapons were stolen by a small group of enslaved men near the Stono River in South Carolina. Some white folks were killed, other enslaved individuals joined the rebellion, but after about 20 white people were killed, the South Carolinian militia 民兵组织 eventually rolled up and crushed this rebellion. Ultimately, over 50 enslaved people lost their lives trying to rebel with the hopes of gaining their freedom in Spanish Florida.

While the Stono Rebellion did fail though, the fact that it even took place reveals that the "happy slave" narrative pushed by defenders of slavery — and even some textbooks like you see right there — is complete garbage. And while you may think that the days of school textbooks minimizing the inhumanity 不人道 of slavery like you see right there are long gone, this children's book that was being sold in 2016 depicts enslaved people of George Washington happily baking him a cake for his birthday.

In our next video, we will take a quick look at colonial society and culture — see what all these people were thinking and doing at this time. But until next time, thank you so much for watching this Joe's Productions video. Have a beautiful day. Peace!

'''


== 中文翻译

大家好，漂亮的人们！今天我们来探讨英国殖民地的奴隶制。像美洲其他参与大西洋奴隶贸易的欧洲帝国一样，英国殖民地发展出了一套奴隶制度，该制度反映了这些殖民地特定的经济、人口和地理特征。然而，所有的英国殖民地都参与了大西洋奴隶贸易。

现在要明确的是，奴隶制对某些地区的重要性远超其他地区。但更明确地说，北美洲的每个殖民地都有奴隶制。那么，奴隶制这种制度发展起来的原因是什么呢？殖民地拥有大量的土地，随着时间的推移，契约仆人无法满足殖民地的劳动力需求。随着欧洲的情况略有好转，作为契约仆人来到北美洲的人越来越少。

像培根叛乱这样的事件让殖民地精英感到担忧。以前的契约仆人和以前被奴役的人开始提出要求——一些疯狂的要求，比如承诺的土地、公平的税收、更好的待遇。而且，转向一种永久的、基于种族的并将劳工视为财产的劳动力来源似乎要容易得多。再加上欧洲对殖民地商品的需求不断增长，因此奴隶制将在英国殖民地发展起来。

随着奴隶制在整个英国殖民地发展起来，它在不同的英国殖民地区有所不同。在新英格兰殖民地，少量被奴役的劳工被用于小型农场，更多的人被用于港口城市完成各种任务。奴隶制在切萨皮克和南部殖民地的经济和社会体系中占据了更重要的地位，因为这些地区有大量的人被奴役，他们是弗吉尼亚烟草种植园和南卡罗来纳水稻种植园的主要劳动力来源。正如我们所见，就南卡罗来纳而言，被奴役的人口占多数。

虽然奴隶制是 13 个殖民地的事实，但绝大多数被奴役的非洲人不会被带到这 13 个殖民地。英国殖民地的大多数被奴役的人将被送到西印度群岛，大量奴隶也将被送到西班牙的加勒比殖民地以及葡萄牙的巴西殖民地。

我们知道 1619 年标志着被奴役的人首次被带到弗吉尼亚的英国殖民地。在这些殖民地，发展起来的奴隶制形式被称为动产奴隶制。动产奴隶制意味着被奴役的人在法律上被视为奴隶主的个人财产——或动产。

随着动产奴隶制成为许多南部殖民地的主要劳动制度，新的法律建立了一个严格的种族制度。此类法律的例子包括禁止跨种族关系的法律，将非裔美国母亲的后代（委婉地说就是孩子）定义为永远的黑人和奴隶的法律——“永远”的意思是永远。

虽然契约仆人的待遇并不特别好，但贫困的契约仆人确实享有某些权利。他们不能被迫永远工作。欧洲曾为保护这些人而斗争争取法律。另一方面，没有任何法律保护被强行带过来的非洲人。禁止跨种族结合、确保奴隶所生的孩子也是奴隶，以及将被奴役的人视为动产等法律，有目的地建立了一个严格的种族制度。

但种族并不是真实的。种族的概念是由当权者创造的，目的是为使某些人赚取大量金钱的政策以及为可怕的奴隶制制度辩护。尽管一些历史书试图描绘奴隶制——注意船上的被奴役者穿着西装，握着手，好像要进行某种商业交易——我的意思是，这简直是对奴隶制和中间航程这种非人化制度的现实的故意歪曲。奴隶制极其可怕。

为了回应奴隶制的非人化本质，被奴役的人们以隐蔽和公开的方式进行抵抗。大多数对奴隶制的抵抗是隐蔽的——或者说是隐藏的。例如，许多被奴役的人继续信奉他们的文化信仰，说他们的母语，并将他们的非洲身份的元素融入这个新的社会。被奴役的人们还组成了大家庭，参与了怠工、装病以及其他各种抵抗奴隶制制度的方法。

公开的抵抗形式并不常见，因为各种法律严格控制着被奴役的人，公开的抵抗可能导致一个人受到体罚、与家人分离甚至被杀害。但是，也有使用这种抵抗形式的例子。逃跑是一种高风险的公开抵抗方法，但确实有人这样做。也许最具威胁性的抵抗形式实际上是公开的反叛。

1739 年的斯托诺叛乱是北美殖民地被奴役人民最大规模的起义。在南卡罗来纳州斯托诺河附近，一小群被奴役的男子偷走了武器。一些白人被杀，其他被奴役的人加入了叛乱，但在大约 20 名白人被杀后，南卡罗来纳州的民兵最终赶来镇压了这次叛乱。最终，超过 50 名被奴役的人在试图反叛、希望在西班牙佛罗里达获得自由的过程中丧生。

虽然斯托诺叛乱确实失败了，但它竟然发生这一事实表明，奴隶制捍卫者——甚至像你看到的一些教科书——所宣扬的“快乐的奴隶”的说法完全是垃圾。虽然你可能认为像你看到的那样，学校教科书淡化奴隶制非人性的日子早已过去，但这本 2016 年出售的儿童读物却描绘了乔治·华盛顿的奴隶们快乐地为他烤生日蛋糕。

在我们的下一个视频中，我们将快速了解殖民地的社会和文化——看看当时所有这些人都在想什么和做什么。但在下次之前，非常感谢您观看乔氏制作的视频。祝您拥有美好的一天。再见！

'''


== pure

What's up, beautiful people? Today we're covering slavery in the British colonies. Like other European empires in the Americas that participated in the Atlantic slave trade, the English colonies developed a system of slavery that reflected the specific economic, demographic and geographic characteristics of those colonies. Regardless, all of the British colonies participated in the Atlantic slave trade.

Now to be clear, slavery was much more important to some regions than others. But to be even clearer, every colony in North America had slavery. So what were the reasons the institution of slavery developed? There was an abundance of land in the colonies, and over time indentured servants were not meeting the labor needs of the colonies. As things slightly improved in Europe, fewer people were coming over to North America as indentured servants.

Events such as Bacon's Rebellion worried the colonial elite. Former indentured servants and formerly enslaved people were starting to make demands -- crazy stuff like land that was promised, fair taxes, better treatment. And it seemed so much easier to switch to a labor source that was permanent, race-based, and treated the laborers as property. Add to all this there was a growing demand in Europe for colonial goods, and as a result slavery will develop in the British colonies.

As slavery developed throughout the British colonies, it differed in the various British colonial regions. In the New England colonies, a small number of enslaved laborers were used on small farms, and more were used in port cities to complete various tasks. Slavery was much more a part of the economic and social system of the Chesapeake and southern colonies, as large numbers of people were enslaved in these regions, serving as the primary labor source in the tobacco plantations of Virginia and rice plantations of South Carolina. And as we've seen, in the case of South Carolina, enslaved people made up the majority of the population.

While slavery was a fact of life in the 13 colonies, the great majority of enslaved Africans would not be brought into the 13 colonies. The majority of enslaved people in the British colonies would be sent to the West Indies, and a large number of slaves would be sent to the Spanish Caribbean colonies as well, and to the Portuguese colony of Brazil.

Now we know 1619 marked the year in which enslaved people were brought into the British colonies for the first time in Virginia. And in the colonies, the form of slavery that developed was known as chattel slavery. Chattel slavery means that the enslaved person is legally rendered the personal property -- or chattel -- of the slave owner.

As chattel slavery became the dominant labor system in many southern colonies, new laws created a strict racial system. Examples of such laws include those that prohibit interracial relationships, laws that define the descendants of African-American mothers (fancy way of saying children) as black and enslaved in perpetuity -- and by perpetuity we mean forever.

While indentured servants were not treated especially well, poor indentured servants did have certain rights. They couldn't be forced to work forever. Laws had been fought for in Europe protecting those individuals. On the other hand, no laws protected African people forcibly brought over. Laws such as bans on interracial unions, ensuring a child born to a person and slave was also born a slave, and the fact that enslaved people were considered chattel purposefully created a strict racial system.

But race is not real. The idea of race was created by people in power to justify policies that made some folks a lot of money, and to justify the horrific institution of slavery. And in spite of how some history books tried to portray slavery -- notice the enslaved person on the ship is wearing a suit and shaking hands as they're about to make some sort of business deal -- I mean, talk about an intentional misrepresentation of the reality of the dehumanizing institution that was slavery and the Middle Passage. Slavery was freaking awful.

In response to the dehumanizing nature of slavery, enslaved people resisted in both covert and overt ways. Most resistance to slavery was covert -- or rather concealed or hidden. For instance, many enslaved people continued to practice their cultural beliefs, spoke their native language, and incorporated elements of their African identity into this new society. Enslaved people also formed extended families, participated in work slowdowns, faked being sick, and various other methods of resistance to the institution of slavery.

Overt forms of resistance were not as common since various laws kept enslaved people under strict control, and open resistance could result in a person being physically punished, sold away from their family, or even killed. But there are examples of this form of resistance being utilized. Running away was a method of overt resistance with many risks, but was done. And perhaps the most threatening of the forms of resistance was in fact open rebellion.

The Stono Rebellion of 1739 was the largest uprising of enslaved people in the North American colonies. Weapons were stolen by a small group of enslaved men near the Stono River in South Carolina. Some white folks were killed, other enslaved individuals joined the rebellion, but after about 20 white people were killed, the South Carolinian militia eventually rolled up and crushed this rebellion. Ultimately, over 50 enslaved people lost their lives trying to rebel with the hopes of gaining their freedom in Spanish Florida.

While the Stono Rebellion did fail though, the fact that it even took place reveals that the "happy slave" narrative pushed by defenders of slavery -- and even some textbooks like you see right there -- is complete garbage. And while you may think that the days of school textbooks minimizing the inhumanity of slavery like you see right there are long gone, this children's book that was being sold in 2016 depicts enslaved people of George Washington happily baking him a cake for his birthday.

In our next video, we will take a quick look at colonial society and culture -- see what all these people were thinking and doing at this time. But until next time, thank you so much for watching this Joe's Productions video. Have a beautiful day. Peace!

'''
