= 012 Would you EAT a Human？ ( Jamestown Explained )
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义


What's up, beautiful people? In this video series, I'm going to cover things I wish I learned in high school. In this episode, I asked the question: would you eat another human? Jamestown explained.

There are lots of interesting things to know about Jamestown. It is the oldest permanent 永久的 British colony in the Americas. John Smith established military discipline 纪律 in the colony and underwent a radical makeover by Disney — as did Pocahontas — and ultimately the cash crop 经济作物 tobacco would be the resource that would save the colony from failure. But the colonists of Jamestown face some very difficult conditions.

Our story begins when 104 male colonists set sail on three ships in late December of 1606. You heard that right — the first set of colonists were all dudes. They reached the Chesapeake Bay in April of 1607, and on May 13, 1607, they landed on a narrow peninsula (virtually an island) and established the colony of Jamestown along the James River. Well, the local American Indians called it the Powhatan River, but the colonists named the river in honor of King James, who granted a charter 宪章；特许状 to the Virginia Company to form the settlement in North America. Fun fact: this is a portrait of James as a boy. There is so much to unpack here.

In total, the journey took them four months to cross the Atlantic Ocean, but the hard part was just about to begin. Of the 104 original settlers, only 38 people survived the first nine months in Jamestown. Things that killed this first group were starvation (the settlers who arrived were not accustomed to 习惯于 doing hard agricultural work — they were hoping to find gold or silver like Spain did in their colonies — that ain't happening). The timing also sucked for these colonists when they arrived — the area was experiencing one of the worst droughts 干旱 in centuries, and diseases such as dysentery 痢疾, typhoid 伤寒, and my favorite to say, scurvy 坏血病, killing them off one by one.

Now I admit being a farmer is hard. I tried growing food once, COVID hit, and all I got was two oddly shaped and sized cucumbers. And the folks in Jamestown found out how hard things were on a whole other level. The only thing that kept the remaining 38 people alive was trade with local Native American people. This trade happened for a short period of time thanks to Captain John Smith's ability to broker 促成 a truce 休战；停战 by early 1608 with the local tribe. The tribe provided the colonists with gummy corn that kept them alive.

By 1609 though, the situation went from bad to worse. The drought was still going on. The colonists caught beef with the local Powhatan Confederacy. Setters pissed off the local tribe when they began to take food by force. In response, the Powhatans retaliated 报复；反击 by attacking the colony. With enemies all around them, the colonists could not leave their fort — therefore they could not go get fresh water, hunt or fish. Clearly they had overstayed their welcome. And there is also a strong likelihood 可能性 that the colonists were drinking water with extremely high salinity 盐度 levels.

This period is known as the starving time, and the colonists faced some tough choices when it came to their survival. We know through excavations 发掘 of the site and from primary sources that the colonists ate dogs, cats and horses. We also know by reading a primary source from one of the leaders of Jamestown that they also ate mice, rats and leather boots. Yummy. And we now know that the colonists also resorted to 诉诸；依靠 cannibalism 食人肉.

Teams of anthropologists 人类学家 have been researching the Jamestown site for years, and in 2012 they discovered the remains of a girl that when examined revealed numerous signs that this person had been eaten by other people. They took the bones to a lab and did all sorts of sciency stuff — yes, science. As a result, the team created a 3D facial reconstruction 重建；重构, and based upon the data examined, it was determined that the skeletal remains were that of a female around 14 years old. This estimate 估计 of the age was based upon the size of her molars 臼齿. Cut marks on the jaw, face and forehead were determined to be signs of cannibalism. Experts concluded the purpose of these cuts were to remove the brain for human consumption. The brain would likely have been eaten first because it decomposes 分解 very rapidly after death.

We don't know who took her to dinner — I mean ate her for dinner — but we do know cannibalism did take place in the founding of the first permanent American colony. Look, I love food — my nickname was Donut Boy in middle school — but I wonder: is cannibalism wrong under any circumstance? Out of curiosity, if you were stuck in a life or death situation, would you eat another human? And while there is no evidence that the cannibalism at Jamestown was connected to a murder, would you kill another person and eat them in order to survive? And if yes, which part would you eat and how would you prepare it?

That's going to do it. Go ahead and answer my questions in the comments and see what kind of weirdos are watching this video with you. Thank you so much for watching. Have a beautiful day. Peace!

'''


== 中文翻译

大家好，漂亮的人们！在这个视频系列中，我将介绍一些我希望在高中学到的东西。在这一集中，我提出了一个问题：你会吃另一个人吗？詹姆斯敦的故事。

关于詹姆斯敦有很多有趣的事情值得了解。它是美洲最古老的永久性英国殖民地。约翰·史密斯在殖民地建立了军事纪律，并在迪士尼的改编中经历了彻底的形象改造——宝嘉康蒂也是如此——最终，经济作物烟草将成为拯救该殖民地免于失败的资源。但詹姆斯敦的殖民者面临着非常艰难的条件。

我们的故事始于 1606 年 12 月下旬，104 名男性殖民者乘坐三艘船起航。你没听错——第一批殖民者全是男人。他们于 1607 年 4 月抵达切萨皮克湾，并于 1607 年 5 月 13 日登陆一个狭窄的半岛（实际上是一个岛屿），沿詹姆斯河建立了詹姆斯敦殖民地。当地的美洲印第安人称之为波瓦坦河，但殖民者以詹姆斯国王的名字命名这条河，詹姆斯国王向弗吉尼亚公司授予特许状，以在北美建立定居点。有趣的事实：这是詹姆斯小时候的画像。这里有很多东西需要解读。

他们总共花了四个月的时间才跨越大西洋，但艰难的时期才刚刚开始。在最初的 104 名定居者中，只有 38 人在詹姆斯敦度过了最初的九个月。导致第一批人死亡的原因是饥饿（到达的定居者不习惯从事艰苦的农业劳动——他们希望像西班牙在他们的殖民地那样找到黄金或白银——但这并没有发生）。他们到达的时间对这些殖民者来说也很糟糕——该地区正经历几个世纪以来最严重的干旱之一，而痢疾、伤寒以及我最喜欢说的坏血病等疾病正在一个接一个地夺走他们的生命。

现在我承认当农民很辛苦。我曾经尝试种食物，新冠疫情爆发了，我只收获了两根形状和大小都很奇怪的黄瓜。而詹姆斯敦的人们则发现事情的艰难程度完全是另一个层次的。唯一让剩下的 38 人活下来的就是与当地美洲原住民的贸易。由于约翰·史密斯船长在 1608 年初与当地部落达成了停战协议，这种贸易持续了很短的时间。该部落向殖民者提供了让他们活命的黏玉米。

然而到了 1609 年，情况变得越来越糟。干旱仍在持续。殖民者与当地的波瓦坦联盟发生了冲突。当定居者开始强行夺取食物时，他们激怒了当地部落。作为回应，波瓦坦人袭击了殖民地。周围都是敌人，殖民者无法离开他们的堡垒——因此他们无法去取淡水、狩猎或捕鱼。显然他们不受欢迎了。而且很可能殖民者饮用的水盐度极高。

这段时期被称为“饥饿时期”，殖民者在生存方面面临着艰难的选择。我们通过对该遗址的挖掘以及原始资料了解到，殖民者吃了狗、猫和马。我们还通过阅读詹姆斯敦一位领导人的原始资料了解到，他们还吃了老鼠、皮革靴子。真好吃。而我们现在知道，殖民者甚至开始同类相食。

多年来，人类学家团队一直在研究詹姆斯敦遗址，2012 年，他们发现了一个女孩的遗骸，经检查显示出许多迹象表明这个人曾被其他人吃掉。他们将骨头带到实验室进行了各种科学研究——是的，科学。结果，该团队创建了一个 3D 面部重建模型，根据检查的数据，确定骨骼遗骸属于一名大约 14 岁的女性。这个年龄的估计是基于她的臼齿的大小。下巴、脸部和前额上的切痕被确定为同类相食的迹象。专家得出结论，这些切口的目的是取出大脑供人食用。大脑很可能最先被吃掉，因为它死后腐烂得非常快。

我们不知道是谁请她“吃晚餐”——我的意思是吃了她当晚餐——但我们确实知道，在第一个永久性美国殖民地的建立过程中确实发生了同类相食。听着，我热爱食物——我中学时的绰号是“甜甜圈男孩”——但我想知道：在任何情况下，同类相食都是错误的吗？出于好奇，如果你陷入生死攸关的境地，你会吃另一个人吗？虽然没有证据表明詹姆斯敦的同类相食与谋杀有关，但你会为了生存而杀死另一个人并吃掉他吗？如果会，你会吃哪个部位，又会怎么烹饪呢？

就到这里了。请在评论中回答我的问题，看看和你一起观看这个视频的都是些什么怪人。非常感谢您的观看。祝您拥有美好的一天。再见！

'''


== pure

What's up, beautiful people? In this video series, I'm going to cover things I wish I learned in high school. In this episode, I asked the question: would you eat another human? Jamestown explained.

There are lots of interesting things to know about Jamestown. It is the oldest permanent British colony in the Americas. John Smith established military discipline in the colony and underwent a radical makeover by Disney -- as did Pocahontas -- and ultimately the cash crop tobacco would be the resource that would save the colony from failure. But the colonists of Jamestown face some very difficult conditions.

Our story begins when 104 male colonists set sail on three ships in late December of 1606. You heard that right -- the first set of colonists were all dudes. They reached the Chesapeake Bay in April of 1607, and on May 13, 1607, they landed on a narrow peninsula (virtually an island) and established the colony of Jamestown along the James River. Well, the local American Indians called it the Powhatan River, but the colonists named the river in honor of King James, who granted a charter to the Virginia Company to form the settlement in North America. Fun fact: this is a portrait of James as a boy. There is so much to unpack here.

In total, the journey took them four months to cross the Atlantic Ocean, but the hard part was just about to begin. Of the 104 original settlers, only 38 people survived the first nine months in Jamestown. Things that killed this first group were starvation (the settlers who arrived were not accustomed to doing hard agricultural work -- they were hoping to find gold or silver like Spain did in their colonies -- that ain't happening). The timing also sucked for these colonists when they arrived -- the area was experiencing one of the worst droughts in centuries, and diseases such as dysentery, typhoid, and my favorite to say, scurvy, killing them off one by one.

Now I admit being a farmer is hard. I tried growing food once, COVID hit, and all I got was two oddly shaped and sized cucumbers. And the folks in Jamestown found out how hard things were on a whole other level. The only thing that kept the remaining 38 people alive was trade with local Native American people. This trade happened for a short period of time thanks to Captain John Smith's ability to broker a truce by early 1608 with the local tribe. The tribe provided the colonists with gummy corn that kept them alive.

By 1609 though, the situation went from bad to worse. The drought was still going on. The colonists caught beef with the local Powhatan Confederacy. Setters pissed off the local tribe when they began to take food by force. In response, the Powhatans retaliated by attacking the colony. With enemies all around them, the colonists could not leave their fort -- therefore they could not go get fresh water, hunt or fish. Clearly they had overstayed their welcome. And there is also a strong likelihood that the colonists were drinking water with extremely high salinity levels.

This period is known as the starving time, and the colonists faced some tough choices when it came to their survival. We know through excavations of the site and from primary sources that the colonists ate dogs, cats and horses. We also know by reading a primary source from one of the leaders of Jamestown that they also ate mice, rats and leather boots. Yummy. And we now know that the colonists also resorted to cannibalism.

Teams of anthropologists have been researching the Jamestown site for years, and in 2012 they discovered the remains of a girl that when examined revealed numerous signs that this person had been eaten by other people. They took the bones to a lab and did all sorts of sciency stuff -- yes, science. As a result, the team created a 3D facial reconstruction, and based upon the data examined, it was determined that the skeletal remains were that of a female around 14 years old. This estimate of the age was based upon the size of her molars. Cut marks on the jaw, face and forehead were determined to be signs of cannibalism. Experts concluded the purpose of these cuts were to remove the brain for human consumption. The brain would likely have been eaten first because it decomposes very rapidly after death.

We don't know who took her to dinner -- I mean ate her for dinner -- but we do know cannibalism did take place in the founding of the first permanent American colony. Look, I love food -- my nickname was Donut Boy in middle school -- but I wonder: is cannibalism wrong under any circumstance? Out of curiosity, if you were stuck in a life or death situation, would you eat another human? And while there is no evidence that the cannibalism at Jamestown was connected to a murder, would you kill another person and eat them in order to survive? And if yes, which part would you eat and how would you prepare it?

That's going to do it. Go ahead and answer my questions in the comments and see what kind of weirdos are watching this video with you. Thank you so much for watching. Have a beautiful day. Peace!

'''
