= 0916
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 916 – Being Forced out of a Position.
This is English as a Second Language Podcast episode 916. I'm your host, Doctor Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at ESLPod.com and become a member of ESL Podcast.
This episode is a dialogueue between Julianna and Hugo about someone being forced out or forced to leave their position. Let's get started.
[start of dialogue]
Julianna: Ha ha! The wicked witch is dead!
Hugo: What are you talking about?
Julianna: Bettina is stepping down as chairperson of the committee. I thought this day would never come.
Hugo: That’s a big surprise. I never thought I’d live to see the day when Bettina would willingly give up her position.
Julianna: It wasn’t her choice exactly. The rest of the committee forced her out, saying they couldn’t work with her anymore. Oh how the mighty have fallen!
Hugo: But I thought she had the support of the higher-ups and they wanted her in the position.
Julianna: Well, she’s somehow fallen from grace and they can’t wait to see the back of her. It’s nice to see her get her comeuppance – finally!
Hugo: Maybe we’re not getting the full story. Maybe she had personal reasons for leaving.
Julianna: Whatever the reason, we’ll be rid of her once and for all. Hallelujah!
Hugo: How do you know the next chairperson won’t be worse?
Julianna: Bite your tongue!
[end of dialogue]
Our dialogue begins with Julianna saying, “Ha ha! The wicked witch is dead!” The “wicked (wicked) witch (witch)” is a reference to a famous movie from the 1930’s called The Wizard of Oz. In the movie, there was an evil or bad character who was called the “Wicked Witch.” A “witch” is a woman who is said to have magical powers. “To be wicked” means to be bad. It's an old word for someone who is bad.
So, a “wicked witch” would be an evil witch, in this case, an evil woman. Now, one of the lines in the movie, I don't want to tell you what happens at the end of the movie, but one of the lines in the movie is “The wicked witch is dead!” We're guessing that Julianna is referring to someone who is not a witch, and is probably not dead, but in this case, is no longer in their position. And that's what Hugo asks her about.
Hugo says “What are you talking about?” Julianna says, “Bettina is stepping down as chairperson of the committee.” “To step down” is a two-word phrasal verb, meaning to voluntarily leave your position. You could be the president of a company and then decide to “step down,” to resign, to leave your position.
Julianna says that “Bettina is stepping down as chairperson of the committee.” We’re not sure what the committee is, but the Bettina is the chairperson. Since Bettina is a woman, we could also call her the “chairwoman.” Julianna says, “I thought this day would never come.” That expression, “I thought this day would never come,” means you have difficulty believing that something has actually happened. You wanted it to happen for a very long time and now it happens, and you're surprised.
Hugo says, “That's a big surprise. I never thought I'd live to see the day when Bettina would willingly give up her position.” The expression, “I never thought I'd live to see the day,” is similar to the previous expression, “I thought this day would never come.” You're saying that you are very surprised that something has actually happened because, again, you were waiting for it for a long time and now it has happened.
Hugo says that he never thought he'd see the day when Bettina would willingly, that is, voluntarily, not like being forced, give up her position. “To give up something” is a two-word phrasal verb meaning to decide no longer to use it, or to stop using something. “I'm going to give up drinking coffee in the mornings.” I'm going to stop drinking coffee in the mornings. When we use the verb that way, there is this notion of a sacrifice. I'm going to sacrifice voluntarily and give up a certain activity. Here, it means basically to no longer be in a position, to resign, to step down.
Julianna says, “It wasn't her choice exactly.” That means it wasn't voluntary – completely, anyway. That's what Julianna means when she says, “It wasn't her choice exactly.” “The rest of the committee” – the other members of the committee – “forced her out, saying they couldn't work with her anymore.” “To force someone out” is to make someone leave a position either in business or in politics, or in, perhaps, some other position of authority.
When a politician is forced out of office, he is made to resign or leave his position by people who don't want him there. Bettina was forced out of her position as chairwoman of the committee. Julianna says, “Oh, how the mighty have fallen!” This is an old expression that refers to a verse or a sentence in the Bible describing how someone who was very strong and powerful suddenly loses their power. “To fall” here means to no longer be powerful, to no longer be in your position. “Mighty” (mighty) describes someone who is powerful, who is strong. So, the expression, “Oh, how the mighty have fallen” means that someone who is very powerful is now suddenly not powerful.
Hugo says, “But I thought she had the support of the higher-ups.” The expression “the higher-ups” refers to people who are at the top of an organization in terms of the management, the people who are the leaders or the bosses. Those of the “higher-ups.” Hugo says he thought Bettina had the support of the higher-ups, of the bosses, and that they wanted her in the position.
Julianna says, “Well, she's somehow fallen from grace and they can't wait to see the back of her.” “To fall from grace” is to do something that makes other people unhappy with you. Another way of saying this would be “to fall out of favor” (favor). “To fall from grace,” or “to fall out of favor,” is to be in a high position, or a position where you are respected and everyone likes you, to a position where you do something bad, and now nobody likes you, and perhaps you've lost your power or your position.
Julianna says that the “higher-ups” – the bosses – “can't wait to see the back of her.” When you “can't wait to” do something, you very much want to do it. You are eager to do it. You want to do it right away, if possible. In this case, the bosses can't wait to see the back of Bettina. “To see the back of someone” means to want to see someone leave. If someone leaves, they turn around and walk away from you and what do you see? You see the back of that person. So, the expression “they can't wait to see the back of her” means they are very eager for her to leave. They want her to leave as soon as possible.
Julianna says, “It's nice to see her get her comeuppance – finally!” This is a somewhat unusual word, “comeuppance” (comeuppance). “Comeuppance” is a punishment for something that you did wrong. It's something that you deserve because you've been doing something wrong, and therefore need to be punished. It's typically used in referring to people who think they are superior to everyone else, who think they're better than everyone else, and then they do something wrong and they lose their power, or they “fall from grace,” we might say. That would be getting your “comeuppance.” You have some sort of punishment for doing something wrong after having thought that you were better than everyone else.
Hugo says, “Maybe we're not getting the full story.” The “full story” here means the entire truth, the entire story, everything that could be known about the situation. Hugo says, “Maybe she had personal reasons for leaving.” “Personal reasons” would be perhaps some problem with her family, or she was sick, or something like that, something that was not related to her job performance.
Julianna says, “Whatever the reason, we’ll be rid of her once and for all.” “To be rid (rid) of someone” means to no longer have someone, or it could also be used to mean to no longer have something, especially something that you don't like. “We are now rid of the neighbor next door who had a loud, barking dog.” The neighbor moved out, left, and now we are “rid of” them. We no longer have to have them next to us.
“Once and for all” means finally and completely. We use this phrase when something has happened that you have been waiting for, or anticipating, for a long time, and that is now complete and over – “once and for all.” Julianna says, “We’ll be rid of Bettina once and for all. Hallelujah!” “Hallelujah” (hallelujah) is an old phrase, an old word to express joy, happiness, when something very good happens. You'll often see this word used in a religious context. “Hallelujah” is wonderful, great, that's what Juilianna means by it.
Hugo says, “How do you know the next chairperson won't be worse?” – in other words, the person who comes after Bettina could be worse than Bettina. Julianna says, “Bite your tongue.” That expression, “bite (bite) your tongue,” means “Stop talking immediately.” We say this when someone is saying something bad that we don't want to hear, or someone is predicting something bad that will happen, and you don't want them to talk about it anymore because you don't want it to happen. The phrase can also be used simply to mean to be quiet, to not say something, even though you could say something. “I'm going to bite my tongue when my sister-in-law comes over.” I'm not going to say the things I want to say that might make her angry, or might make my wife angry. That's more important.
Now let's listen to the dialogue, this time at a normal speed.
[start of dialogue]
Julianna: Ha ha! The wicked witch is dead!
Hugo: What are you talking about?
Julianna: Bettina is stepping down as chairperson of the committee. I thought this day would never come.
Hugo: That’s a big surprise. I never thought I’d live to see the day when Bettina would willingly give up her position.
Julianna: It wasn’t her choice exactly. The rest of the committee forced her out, saying they couldn’t work with her anymore. Oh how the mighty have fallen!
Hugo: But I thought she had the support of the higher-ups and they wanted her in the position.
Julianna: Well, she’s somehow fallen from grace and they can’t wait to see the back of her. It’s nice to see her get her comeuppance – finally!
Hugo: Maybe we’re not getting the full story. Maybe she had personal reasons for leaving.
Julianna: Whatever the reason, we’ll be rid of her once and for all. Hallelujah!
Hugo: How do you know the next chairperson won’t be worse?
Julianna: Bite your tongue!
[end of dialogue]
We hope she never steps down from her position as scriptwriter here on ESL Podcast. I speak, of course, of the wonderful Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan, thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
wicked witch – a woman with magical powers used for evil (doing bad things), a reference to the movie The Wizard of Oz
* Shelby’s new boss is a wicked witch who does everything she can to make life miserable for the employees.
to step down – to voluntarily leave a position of responsibility, allowing someone else to have that role
* As Orlando got older, he began thinking about stepping down from his position as CEO to let a younger executive gain leadership experience.
to think this day would never come – to have trouble believing that something has actually happened, because one has wanted it to happen for a very long time, but did not know whether it was possible
* Can you believe Amman and Hannah are getting married tomorrow? I thought this day would never come.
to live to see the day – to still be alive when an event finally happens, because one has been waiting for it for a very long time and was doubting whether it would happen in one’s lifetime
* I hope I never live to see the day when the company values making money more than it values employees.
willingly – voluntarily; agreeing to do something without being forced to do it
* Why would you willingly pay more in taxes than you’re required to pay?
to give up – to relinquish; to step down from a position or let go of something so that another person can have it
* After years of trying to get acting jobs, Jenna had to give up her dreams of becoming a professional actress.
to force (someone) out – to make someone leave a position, especially in business and politics
* Bryan tried to force out the other manager to give himself more power.
how the mighty have fallen – a reference to a Biblical verse, “How the mighty have fallen in battle!” describing how someone who was very strong and powerful suddenly loses that strength or power, and/or has something taken away
* Just five years ago, Acme was the market leader, but today it has a market share of less than 10 percent. Oh, how the mighty have fallen!
higher-up – an executive, a top manager, or a decision-maker; someone who has a lot of influence and decision-making power in an organization
* The higher-ups are in a meeting to discuss the merger.
to fall from grace – to fall out of favor; to do something that makes other people unhappy and think less of a person
* Our Senator used to be very popular, but he voted in ways that led him to fall from grace in the eyes of the people.
to not be able to wait to see the back of (someone) – to be very eager for someone to leave and no longer be involved in something
* Joey was a terrible team member, and throughout the whole project, we couldn’t wait to see the back of him.
comeuppance – a punishment that someone deserves; a negative consequence of bad behavior, especially when one has been acting in a superior or negative way toward others
* Justin spent the past few months bragging about his new job, so when he was fired, it was his comeuppance.
full story – the whole truth; the entire truth, without any parts left out; a story that incorporates the perspectives of everyone who is involved
* At first, we all blamed Jesse for the divorce, but once we heard the full story, we realized that Monica was equally at fault.
to be rid of – to no longer have someone or something, especially an unpleasant person or thing
* It feels great to finally be rid of all that junk that was in the garage!
once and for all – finally and completely; a phrase used when something has happened that one has been anticipating for a long time, and that thing is definite and final
* Why do we keep arguing about the same things over and over again? Let’s really talk about it and get things cleared up once and for all.
hallelujah – a phrase used in worship or to express joy, happiness, and appreciation; a cheer used to show one’s happiness or enthusiasm
* Did you hear that Quentin and Elena are getting married? Hallelujah!
to bite (one’s) tongue – to stop talking immediately, especially when one has been saying bad things
* Bite your tongue! I never want to hear you say anything like that again.
Comprehension Questions
1. According to Julia, what is happening?
a) Bettina has decided to stop serving as the chairperson.
b) Bettina is being forced to leave her position.
c) Bettina is being fired.
2. Why does Julia say, “Bite your tongue”?
a) Because she wants Hugo to speak more quietly.
b) Because she feels like Hugo isn’t supporting her.
c) Because she doesn’t like what Hugo said and she wants him to stop talking.
Answers at bottom.
What Else Does It Mean?
to step down
The phrase “to step down,” in this podcast, means to voluntarily leave a position of responsibility, allowing someone else to have that role: “Nicholas is stepping down from his management position so that he can spend more time with his family.” The phrase “to step up” means to agree to do something when one is not required to do it, or to take responsibility for something when others don’t want to: “Who is going to step up and lead our fundraising efforts?” The phrase “to side-step” means to avoid something: “Stop side-stepping the issue! We need to talk about this.” Or “What can we do to side-step these problems in the future?” Finally, the phrase “to overstep (one’s) bounds” means to go beyond the limits of what is acceptable: “You aren’t the company’s spokesperson, so you really overstepped your bounds when you talked to that reporter.”
to be rid of
In this podcast, the phrase “to be rid of” means to no longer have someone or something, especially an unpleasant person or thing: “It’s going to feel great once we’re finally rid of all our credit card debt.” The phrase “to get rid of” means to take some action to give something away or throw it away: “Nobody is going to buy that old couch. You’ll have to give it away for free if you want to get rid of it.” As a verb, “to rid” means to get rid of something: “We’re so glad she rid herself of that boyfriend.” Finally, the phrase “good riddance” is said when one is happy that something is gone or done: “I can’t believe those uninvited houseguests stayed for three weeks. Good riddance!”
Culture Note
Golden Parachutes
A “golden parachute” is an agreement between an employer and an employee that states that the employee will receive certain benefits if he or she is “terminated” (fired; told to leave the job). A “parachute” is a large piece of fabric that slows down one’s fall through the air, as when a person jumps out of an airplane or when a “space shuttle” (vehicle that travels into space) returns to earth. In a similar way, a “golden parachute” provides a “soft landing” (low impact) when an employee is terminated. “In effect” (in reality; what actually happens), the employer pays the employee if he or she is terminated.
Golden parachutes can provide many different types of “compensation” (payments). They could provide simple cash payments, but more complicated arrangements could offer “stock options” (the possibility of buying stock in the future at a given price, no matter how much stock is actually worth at that time, usually allowing the recipient to buy stock at much less than it is worth).
“Supporters” (people who like something) of golden parachutes argue that they make it easier for companies to hire “talented” (very good at what they do) “executives” (top managers and decision-makers in a business) and that they help executives make less “biased” (favoring one person or organization) decisions during mergers and acquisitions that might result in them losing their job. In contrast, “opponents” (people who do not like something) of golden parachutes argue that they are unfair, because executives needs to accept the “risk” (the likelihood that a bad things might happen) of losing their job just like everyone else.
Comprehension Answers
1 - b
2 - c