= 0940
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 940 – Ending Excessive Spending.
This is English as a Second Language Podcast episode 940. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at ESLPod.com and become a member of ESL Podcast. When you do that, you help support this podcast and get a Learning Guide for this episode.
On this episode, we’re going to listen to a dialogue between Raphael and Kelly about spending too much money. Let's get started.
[start of dialogue]
Raphael: Sorry to be a buzzkill, but this gravy train we’ve been on is about to end.
Kelly: What do you mean?
Raphael: There have been a lot of complaints about our department’s spending on extraneous things, and to quell the masses, the department head is making some major changes.
Kelly: Like what?
Raphael: Like no more frivolous and excessive spending on travel and entertainment at conferences.
Kelly: But those are the only things that make this job bearable. Those perks are part and parcel of working for a government agency – at least that’s what I used to think.
Raphael: Well, once the press got wind of some of our spending practices, they started to question our budget allocations. The long and short of it is that those days are about to end.
Kelly: And I was planning to take you and few other employees to St. Lucia for a retreat in the spring.
Raphael: I think you’d better change those plans, at least the venue. You’d have better luck getting it approved if you picked Cleveland!
[end of dialogue]
Our dialogue begins with Raphael saying to Kelly, “Sorry to be a buzzkill.” A “buzzkill” (buzzkill) is a person who spoils or ruins everyone else's fun. Basically, a “buzzkill” is a person who does something to stop other people from having fun while they're in the middle of having fun. They do something or say something that makes everyone no longer enjoy themselves. That's a “buzzkill.” There's an older term, a little less common nowadays, for this same idea, which is a “party pooper” (pooper). A “party pooper” is the same as a buzzkill. The word “buzz” is sometimes used to mean excitement – a certain atmosphere in a situation or place. That's probably the origin of this term “buzzkill.”
Raphael says he's sorry to be a buzzkill, “but this gravy train we've been on is about to end.” “Gravy (gravy) train (train)” is a situation where you have a lot of money, or people are able to make a lot of money very easily. A gravy train would be a really good situation financially – something either that is making you a lot of money or that is allowing you to spend a lot of money. Raphael talks about being on a gravy train just like you would be on a regular train or on a bus or another form of transportation.
Unfortunately, the gravy train “is about to end,” Raphael says.
Kelly says, “What do you mean?” He says, “There have been a lot of complaints about our department's spending on extraneous things.” A “complaint” is an objection to something that is going on that you don't like. You can have a complaint at a restaurant if your food is bad. Here, people are complaining – notice the verb “to complain” – “about our department’s spending on extraneous things.” “Spending” is the money that you pay for something. “Extraneous” (extraneous) means extra and unnecessary. Something that is “extraneous” is something that is more than what is needed. It's too much. It's not required.
Raphael and Kelly's department has been spending money on extraneous things, “and to quell the masses, the department head is making some major changes.” The “department head” would be the person who is the top boss, top manager, in a department in a company. A “department” is just one part of a larger company – one division, perhaps, of a company. The department head is making some major, or very important or large, changes.
He's doing this “to quell the masses.” This is an interesting expression. “To quell (quell) the masses (masses)” means to try to make people feel calmer, to try to do things that will address or answer people's concerns or complaints. The “masses” refers to a large group of people. “To quell” here means to quiet down, to make happy, people who are unhappy because of a bad situation.
Kelly says, “Like what?” meaning “What are these major changes?” Raphael says, “Like no more frivolous and excessive spending on travel and entertainment at conferences.” Something that is “frivolous” (frivolous) is not very important, silly. Something that is “frivolous” is not worth paying close attention to. “Excessive” means too much. This department has been spending too much on travel and entertainment at conferences. A “conference” is a large meeting where people who have similar interests come together and talk to each other.
Many kinds of work have conferences where once a year or perhaps twice a year you can go and learn more about your particular area. It might be a business conference. It might be an academic conference with university professors. It might be a conference for people who work in the government. There are conferences all over the United States – all over the world – for lots of different kinds of interests and activities. In fact, in most cities in the United States – in most big cities in the United States – you will find “conference centers.” These are places that are built especially for these kinds of large group meetings.
Kelly says, “But those are [the only] things that make this job bearable.” “To be bearable” (bearable) means to be tolerable – something that you can put up with. Something that is “bearable” is something that is not so terrible that you want to quit or stop doing whatever it is you're doing. Kelly says that going to these conferences, for example, is one of the things that makes her job “bearable.” It might not be a very good job, but it's okay because she can go to these conferences and spend a lot of money. That's kind of how I felt about my university job.
Kelly says, “Those perks are part and parcel of working for a government agency – at least that's what I used to think.” A “perk” (perk) is a benefit, especially a benefit from working at a certain place from your job. It might be something like free parking at the building, or you get a free lunch every day. There are companies here in California that give their employees lunch for free every day. It's one of the perks of the job. Of course, they do that so that people will stay in the building and work more.
Kelly says these perks are “part and parcel” (parcel). “Part and parcel” is an old expression meaning a necessary part of something – something that you have to do or something that cannot be avoided. We learned that Kelly and Raphael work for the government, which is why they have so much money to spend. Raphael says, “Well, once the press got wind of some of our spending practices, they started to question our budget allocations.” The “press” here refers to the media: newspapers, magazines, television stations, and so forth – people who work in the area of journalism, of reporting the news.
“To get wind of something” is an expression that means to find out about, to hear about something. “Spending practices” just refers to the things that you spend money on, the way that you spend your money. “Budget allocations” refers to your plans about how you're going to spend your money. A “budget” (budget) is a plan for spending money. “Allocations” are the things that you actually spend the money on. The press got wind of the spending practices of this department and they “started to question” – they started to ask questions about and to complain about, really, these budget allocations.
Raphael says, “The long and the short of it is that those days are about to end.” “The long and the short of it” is a phrase we use to give someone the most important point about a difficult or complex situation. It's a way of introducing the conclusion or the most important thing you want to say to someone. If you're telling someone a long, complicated story, you may try to summarize everything by saying, “The long and short of it is . . .”
Kelly says, “And I was planning to take you and a few other employees to St. Lucia for a retreat in the spring.” St. Lucia is an island in the Caribbean. A “retreat” (retreat) is usually a long meeting that you have outside of your offices, at a hotel or at a very nice resort somewhere away from where you work. Usually, a retreat lasts two or three days, and it's a time for leaders in a company or an organization to come together and talk about their plans for the future. That's a typical topic at a retreat.
There are also religious retreats were people go away for a couple of days in order to pray and participate in religious activities. But Kelly isn’t thinking of anything religious here when she talks about this retreat, since St. Lucia is one of the most expensive islands to go to in the Caribbean. Raphael says, “I think you'd better change those plans, at least the venue.” The “venue” (venue) is the place where some event is held. It’s the location where you, in this case, would be having your meeting.
Raphael says, “You'd have better luck getting it approved if you picked Cleveland.” Raphael is saying to Kelly that she will have a better chance of getting her plan approved to have a retreat if she has it in Cleveland rather than St. Lucia. Cleveland is a city in the eastern part of the United States, in the state of Ohio. The reason that Raphael says Cleveland is that it's not a very nice city to visit. I’ve been to Cleveland. It seems okay. But it's not a place where people would go in order to have a vacation, and a lot of times these retreats are places that are nice, that are places where you would go on a vacation, like Hawaii or St. Lucia.
Now let's listen to the dialogue, this time at a normal speed.
[start of dialogue]
Raphael: Sorry to be a buzzkill, but this gravy train we’ve been on is about to end.
Kelly: What do you mean?
Raphael: There have been a lot of complaints about our department’s spending on extraneous things, and to quell the masses, the department head is making some major changes.
Kelly: Like what?
Raphael: Like no more frivolous and excessive spending on travel and entertainment at conferences.
Kelly: But those are the only things that make this job bearable. Those perks are part and parcel of working for a government agency – at least that’s what I used to think.
Raphael: Well, once the press got wind of some of our spending practices, they started to question our budget allocations. The long and short of it is that those days are about to end.
Kelly: And I was planning to take you and few other employees to St. Lucia for a retreat in the spring.
Raphael: I think you’d better change those plans, at least the venue. You’d have better luck getting it approved if you picked Cleveland!
[end of dialogue]
There’s nothing frivolous about our scripts here on ESL Podcast. That’s because they’re written by the wonderful Dr. Lucy Tse.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2013 by the Center for Educational Development.
Glossary
buzzkill – a party pooper; someone who spoils everyone’s fun; someone who ends a good or enjoyable situation
* Whenever Serena comes to a party, she’s such a buzzkill! She only wants to talk about her classes and exam scores.
gravy train – a situation where there is a lot of money or people make a lot of money very easily
* I didn’t expect our business to become a gravy train right away, but I also never thought it would be this hard to make a profit!
spending – expenses; money paid in exchange for goods and services
* We have to reduce our spending, or we’ll never be able to save enough money to retire.
extraneous – extra and unnecessary; more than is needed or wanted
* Employees have to learn to identify and discard extraneous information so that they can focus on the most important issues.
to quell the masses – to appease people; to do or say something that addresses others’ concerns and makes them feel calmer or less upset
* When people were worried about inflation, the government gave everyone free rice to try to quell the masses.
department head – the top manager of a division or a group of people working together within a larger business or organization
* The department head has requested funding for three new positions.
frivolous – silly and unimportant; not worthy of serious attention or consideration
* As the executive assistant, Amanda’s job is to handle all frivolous requests and inquiries so that her boss can focus on the more important problems.
excessive – too much of something; more than is needed or normal
* Don’t you think the punishment you gave the kids was excessive?
bearable – tolerable; manageable; not so difficult that one can’t stand something
* The pain should be bearable, but if it becomes too intense, we can give you some more medication.
perks – benefits one receives in a job in addition to one’s pay or salary
* Some of the perks of working here include a company car, an expense account, and discounts at the gym.
part and parcel – a necessary part of something; a part that is separate, but cannot be avoided
* Learning how to paint and fix leaking faucets are part and parcel of being a homeowner.
to get wind of – to hear about something; to hear a rumor; to become aware of something
* If anyone gets wind of her involvement in the scandal, her career will be ruined.
spending practices – spending habits; how one typically spends money
* Did you read that article about the spending practices of millionaires?
budget allocation – a plan for how and when money will be spent, usually within a company or an organization
* Voters clearly support greater budget allocations for education and healthcare.
the long and short of it – a phrase used to present the most important point or a conclusion about something that is complex
* I could show you graphs and charts full of data all day long, but the long and short of it is that our company is losing market share.
retreat – a long meeting held outside of the office where people normally work, often for strategic planning or teambuilding, and often with opportunities for relaxation and enjoyment
* Each summer, the managers go on a three-day retreat to set goals for the coming year.
venue – the place where an event is held; location
* Does Springfield have any venues that can accommodate a conference with 500 participants?
Comprehension Questions
1. What does Kelly mean when she says, “Those perks are part and parcel of working for a government agency”?
a) The perks are the best part of working for the government.
b) The perks were the reasons she accepted the job.
c) The perks are a standard part of having a government job.
2. How does Raphael suggest changing the plans for a retreat?
a) He thinks the retreat should be held somewhere else.
b) He thinks the retreat should be delayed for a while.
c) He thinks the retreat should involve fewer participants.
Answers at bottom.
What Else Does It Mean?
perk
The word “perk,” in this podcast, means a benefits one receives in a job in addition to pay or salary: “Getting to use the corporate jet is a really nice perk.” Or, “We can’t offer you a higher salary, but let me tell you about some of the perks of working here.” The phrase “to perk up” means to become more cheerful or active and alert: “Perk up! The workday is almost done.” Or, “A cup of coffee will help you perk up.” The phrase “to perk (something) up” means to make something more interesting or lively: “Some fresh herbs can perk up any salad.” Finally, a person who is “perky” is confident, happy, and extroverted: “Our customer service representatives need to be perky, but not annoying.”
retreat
In this podcast, the word “retreat” means a long meeting held outside of the office where people normally work, often for strategic planning or teambuilding, and often with opportunities for relaxation and enjoyment: “This year’s faculty retreat will be held the weekend before school starts.” When talking about an army, a “retreat” is a backward movement of troops (soldiers) who are losing a battle: “After hundreds of soldiers were killed, the survivors went into full retreat.” The phrase “to beat a retreat” means to leave a place very quickly: “When the police started arriving, the teenagers beat a retreat.” Finally, a “retreat” can also be when someone changes his or her mind because other people disliked an idea: “Voters made it clear that the politician would need to retreat from his position, or risk losing his elected position.”
Culture Note
The Government Accountability Office
The U.S. Government Accountability Office (GAO) is part of the U.S. “Congress” (legislative or law-making body) responsible for “auditing” (conducting a careful review to determine whether something is being done properly) and “investigating” (researching) the use of “public funds” (money received from the public and/or owned by the government). The GAO was created in 1921 by the Budget and Accounting “Act” (law).
The “mission” (purpose) of the GAO is to “support” (help; assist) the Congress in meeting its “constitutional” (relating the Constitution, the country’s most important legal document) responsibilities and to help improve the performance and ensure the “accountability” (responsibility for one’s actions, words, and decisions) of the federal government for the benefit of the American people. The GAO “engages” (is involved) in not only “financial audits” (reviews of how money is spent), but also “performance audits” (reviews of whether organizations are doing what they are supposed to be doing, and how efficiently).
Today, the GAO has almost 3,000 employees and an annual budget of $533 million. The GAO “releases” (shares with the public) an audit report on the “financial statements” (documents that analyze the financial well-being of a business or organization) of the federal government and also publishes the Federal Fiscal “Outlook” (anticipation of what something will be like in the future) Report, which “addresses” (deals with) long-term “implications” (results of one’s actions) of the government’s operations.
The GAO also conducts “technology assessments” that analyze the benefits, risks, and consequences of new technological “innovations” (developments and progress) on society, the environment, and the economy.
Comprehension Answers
1 - c
2 - a