= 1859
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 554.
This is English as a Second Language Podcast’s English Café episode 554. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. You can also check out our ESL Podcast Store, with additional courses in Business and Daily English. And why not like us on Facebook, at facebook.com/eslpod.
On this Café, we’re going to talk about the Manhattan Project, the project that produced the nuclear bomb in World War II. We’re also going to talk about a famous song, “Give My Regards to Broadway.” And as always, we’ll also answer a few of your questions. Let’s get started.
In 1938, a scientist at Columbia University, located in the Manhattan section of New York City, encouraged a newly arrived Italian scientist by the name of Enrico Fermi to meet with the U.S. government to discuss the possibility of developing a weapon that used the process of nuclear fission. The newly arrived Italian scientist was Enrico Fermi..
The following year, in 1939, other scientists encouraged perhaps the most famous scientists of the twentieth century, Albert Einstein, to write a letter to the president of the United States, Franklin D. Roosevelt, saying that the United States should get involved immediately in developing a weapon from this new nuclear technology because Germany was already working on this new understanding of the atom.
An “atom” (atom) is the smallest amount of substance that can exist by itself. That’s not the best scientific definition, I know, but the important thing for our story is that scientists had learned to split the atom, and that by splitting the uranium atom, an amazing amount of energy could be released. This was something that could be used in a weapon such as a bomb, and many scientists feared that Germany would develop such a weapon before the United States and those who were the “allies,” or friends of the United States.
Of course, this was a period in which Nazi Germany and its allies were starting a war in Europe, and many people feared it would become a world war, which in fact it did. Einstein and the other scientists who were encouraging him to contact the president knew that this atomic bomb could be a very powerful weapon and that the U.S. needed to start working on it immediately.
President Roosevelt agreed and gave $6,000 to begin research into creating this bomb. This amount of money was increased dramatically beginning in 1941, when the United States joined World War II after the bombing of Pearl Harbor in Hawaii. By the end of 1945, the United States along with its allies, including Canada and Great Britain, spent more than two billion dollars in building an atomic bomb. In today’s money, that would be more than 25 billion dollars. More than 100,000 people were involved in what later became known as the Manhattan Project.
Why was it called the Manhattan Project? Well, remember that the first scientists who started to get interested in this project were at Columbia University, which is located in Manhattan. More importantly, the U.S. government knew it needed to build a lot of new buildings for this project, and it asked the Corps of Engineers – the part of the military in charge of building buildings such as this – to take charge of that part of the project. They used the offices of the Corps of Engineers located in Manhattan, and therefore it got the name of the Manhattan Project.
I should explain that a “corps” (corps) is a group of people who work together for a common purpose. The name of the army organization is the “Corps of Engineers.” These are the people who are responsible for building the buildings for the U.S. military, especially the U.S. Army, and the army was of course involved in developing this weapon.
The U.S. wasn’t the only country working on creating an atomic bomb. The U.S. also contacted scientists in England and in Canada to help with the project. Of course, Germany was also working on this idea of an atomic bomb. So things had to move very quickly if the U.S. and its allies were going to be successful. From 1940 to 1943, several of the scientists – including the great Enrico Fermi, Niels Bohr, and the American, J. Robert Oppenheimer – spent a great deal of time trying to figure out how they were going to find a safe way of splitting the uranium and plutonium atoms.
They started working on the actual bomb beginning in 1943. Much of this work in creating the bomb itself was done in a location in New Mexico, near the city of Los Alamos. New Mexico is located in the southern part of the U.S., the southwestern part of the U.S. Important work on the bomb was also done at the University of Chicago, located in the state of Illinois, in the central part of the U.S. As I said before, more than 30 different locations were used as part of the development of the new atomic bomb.
Finally, in 1945, the Manhattan Project was ready to test one of the three atomic bombs it had created. On July 16th, 1945, at 5:30 in the morning, they exploded a bomb at a military base in a small town of New Mexico called Alamogordo. There were no people nearby the bomb, of course. The closest people were at least nine kilometers away, in what we would call “bunkers.” A “bunker” (bunker) is an underground or mostly underground building that is built for military purposes.
The bomb exploded successfully on that morning of July 16th. The scientists knew then that their project had been a success. They had created the world’s first atomic bomb. By the time of the first successful test of the bomb, the war in Europe was over. In fact, the very next day, on the 17th of July, the so-called Potsdam Conference began. The leaders of the Soviet Union, Great Britain, and the United States met to talk about the future of Europe. But the war in the Pacific, the war against Japan, was still going on.
The allied leaders at the Potsdam Conference told Japan that it needed to surrender. Japan said no. The United States, under President Truman’s leadership, decided it would use these atomic bombs on Japan. And so, just a little more than three weeks after the first atomic bomb had been exploded successfully, bombs were dropped on Hiroshima and Nagasaki in early August of 1945. The war with Japan ended soon after, as you all know.
There are many different stories that could be told about the Manhattan Project. Interestingly, the development of the bomb would never have been possible if it were not for some of the leading scientists from Germany and Italy coming to the Allied countries before the war started and helping the U.S. government develop the bomb, including Enrico Fermi, Einstein himself, and several others.
Another interesting part of this Manhattan Project story was the level of secrecy that was needed to prevent Nazi Germany from finding out about this bomb, or at least finding out how the bomb was developed. The U.S. government wasn’t just concerned about Germany finding out about the bomb. It also wanted to prevent one of its allies from finding out about the bomb. That being, of course, the Soviet Union.
The Soviet Union itself sent spies to the U.S. to try to get information about the atomic bomb, and although the U.S. tried to prevent the Soviet Union from finding out about the bomb, the Soviet Union was in fact successful with some of its spies in getting information about the atomic bomb to help it create its own atomic bomb. One of the developers of the bomb, the American scientist Robert Oppenheimer, said that one of the professors at Berkeley had approached him and asked him to give secrets to the Soviet Union about the bomb. He did not.
However, another man working on the project in Los Alamos – Klaus Fuchs, a British citizen at this time – did in fact work for the Soviet Union and gave them information. Fuchs was later discovered as a spy and served nine years in a British prison. People disagree about whether the information he provided the Soviet Union at the time was valuable or not in the long run, but certainly it was true that the U.S. government tried to keep the program as secret as possible, but wasn’t entirely successful.
Our next topic is somewhat happier: a song. In 1904, one of the great American songwriters of the twentieth century, George M. Cohan, wrote a song called “Give My Regards to Broadway.” “Broadway” is a famous street in New York City. It’s a street where you’ll find a lot of theaters, and some of the best plays are performed in these theaters on Broadway, including “musicals” – plays that have songs and dancing in them. When people talk about Broadway nowadays, they’re usually referring to the theaters on Broadway and the performances on Broadway.
“To give your regards” (regards) to someone means to say hello to that person, to let the person know you are thinking of him. I could say to you, “Give my regards to your wife.” That means “Say hello to your wife.” Tell her I say hello. Of course, you have to be careful about telling a man to give his regards to his wife on your behalf. He might interpret that the wrong way. Well, no one interpreted George M. Cohan the wrong way. His song “Give My Regards to Broadway” was written as a way of recognizing the importance of Broadway in the American theater.
Cohan grew up traveling around the United States with his parents, who were also performers. He himself didn’t enjoy the traveling life, but he did enjoy music and began writing songs early on in his life. He wrote a musical, a play with singing, called Little Johnny Jones, which was first performed in New York City in 1904. The musical told the story of an American jockey who traveled to England to be part of a horse race. A “jockey” (jockey) is the person who rides a horse in a race.
In Cohan’s play, the jockey gets in trouble with some criminals and is not allowed to return to the United States. As he watches the ship leave England, the ship he is supposed to be on, he sings this song “Give My Regards to Broadway.” The first time he sings the song he’s sad and unhappy, of course, because he can’t return to the United States.
He sings the song again, however, at the end of the musical when everything has changed and he is happy again. This is the version of the song that most people know. It’s what we might describe as an “upbeat” version of the song. “Upbeat” (upbeat) means very happy, with lots of energy. The first verse of the song is the one that most people know. It begins with the name of the song, “Give My Regards to Broadway.”
The second line is, “Remember me to Herald Square.” This use of “remember,” as in “remember me to,” is not used very much. It’s a bit poetic. It’s basically saying the same thing – say hello from me to Herald Square, which is another area in New York City. Remember, this is a man who is missing his city, his friends, and family back in the United States.
The next line is “Tell all the gang at 42nd street that I will soon be there.” A “gang” in this case is an informal term for a group of people you spend a lot of time with. It could be a group of people at your work. It could be a group of your friends. “Gang” has other meanings as well in English, but in this case it’s just referring to a group of people.
“Tell all the gang at 42nd Street.” “42nd Street” is another large, important street in New York City. There are lots of businesses and restaurants there. If you’ve been to New York City, to Manhattan, you’ll know that 42nd Street and Broadway is where Times Square is, the famous gathering place in the center part of New York. 42nd Street was also the name of a movie in the 1930s, and later a musical.
The singer continues, “Whisper of how I’m yearning to mingle with the old time throng.” “Whisper” normally means to speak in a very low voice. This person wants the person he’s singing to, to tell his old friends that he’s “yearning (yearning) to mingle (mingle).” “To yearn” to do something means to want to do it very much. “To mingle” means to mix, but here it means to spend time with other people in a relaxed social setting such as at a party. If you “mingle” at a party, you go around and you talk to different people at the party. You get to know them.
He wants to “mingle with the old time throng (throng).” “Old time” here just means people he’s known for a long time. A “throng” is a large group of people usually standing close together. So, you can imagine a large party where you have lots of people you know, and you would want to mingle with them. You would want to go around and talk to all of them.
Finally, the last line of this verse or part of the song is “Give my regards to old Broadway, and tell them I’ll be there ere long.” “Ere” (ere) is an old way of saying “before long,” meaning I’ll be there soon. I’ll be there before long.
The song was immediately popular, not just from the George M. Cohan musical, but was also popular because famous singers began to record the song and sing it. One of those singers was a very famous performer by the name of Billy Murphy. We’re going to listen now to a recording from 1905, just one year after the song was written, by Billy Murphy of this famous verse. It’s a little hard to hear but you’ll be able to understand most of it, I think. Here we go.
Although the song is very old, it didn’t really become popular with the average American until 1942. In that year, Hollywood made a movie about the life of George M. Cohan called Yankee Doodle Dandy, which was the name of another song that Cohan wrote for this same musical in which “Give My Regards to Broadway” appeared, Little Johnny Jones.
If you search the Internet, the version of the song you’ll probably hear is the one sung in this movie by the great James Cagney. In fact, Cagney won the Academy Award for Best Actor for his role in this movie. I remember my father singing this song when I was growing up. He, of course, was a young man when the song became famous in 1942. He probably heard it somewhere in Europe where he was serving in the U.S. Army in World War II.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Ann (Ann) in Russia. Ann wants to know the meaning of three verbs, “to propose,” “to suggest,” and “to offer.” “To propose” (propose) means to ask someone to think about or consider a certain plan or theory. If you “propose” a plan to do something, you are saying to other people, “Here is an idea. Think about it. Maybe you want to do it.” You may be asking them to approve it. You’ll often hear the verb “to propose” followed by the conjunction “that.” “I propose that we go to the movies today.”
“To propose” is somewhat of a formal verb, however. You would normally hear it in a business context or in a more formal context or situation. “To propose” is also the verb we use when you ask someone to marry you. Typically the man would “propose” to the woman. “I propose to you.” I am asking you to marry me. Well, not you who are listening. I’m already married.
“To suggest” (suggest) is a much more common verb that can be used in a couple of different ways. One way is to give advice to someone or to give someone an idea that you think might be a good one for that person to carry out. For example, “I suggest you get some water. You look very hot.” You are giving the person advice. You are giving the person an idea that you think the person should put into action, a plan that the person should carry out. Once again, you will often hear this verb with the conjunction “that” after it. “I suggest that you do this thing.” I’m advising you to do this thing.
“Suggest” can also be used when we’re talking about people. If your company is looking for, say, a new person as an accountant. You could say, “Well, I suggest Bob Smith.” Bob Smith is the person you think should be selected or chosen. “Suggest” can also be used to mean to indicate something is probably true. If you come to me and you seem not to be able to speak very clearly, and I can smell alcohol on your breath and on your clothing, I might say, “That suggests to me that you have been drinking.” “The evidence suggests that you have been drinking.” It indicates, it gives evidence, that something is true.
Finally, we can also use “suggest” to mean to say something in an indirect way. Sometimes, when you don’t want to say something directly or “explicitly” (explicitly), you might instead “suggest” that it’s true – say it indirectly. If your boss says that he thought he heard a lot of noise coming from your office, noise that sounded like music, your boss might be suggesting to you that you were not working or that you weren’t working very hard. He doesn’t say it directly but, he is telling you in an indirect way that you should probably stop listening to Lady Gaga and instead start working.
Finally, “to offer” (to offer) means a couple of different things. It can mean to give someone the opportunity or the option to accept something or to take something. “The company is offering me a job.” They’re giving me the opportunity to work at their company. That might be one use of the verb “to offer.” It could also be used when you are buying something. “I’m offering you $10,000 for your car.” I’m giving you the opportunity to take $10,000 in exchange for your car. That is, you’re going to give me your car if I give you $10,000.
“To offer” can also mean to say that you are willing to do something. “I am offering you a ride to the airport.” “I am offering you.” I am telling you I am willing to give you a ride – that is, to drive you – to the airport. There are cases when you could use these three verbs more or less interchangeably. You could “propose” a plan. You could “suggest” a plan. You could “offer” a plan. In all three cases, you’re basically doing the same thing.
Kris (Kris) in Poland wants to know the meanings of the three verbs “to disclose,” “to uncover,” and “to divulge.”
“To disclose” (disclose) is to make something known to other people or to the public. Usually it’s something that only a few people knew, or perhaps something that was secret. It’s a rather formal verb. A company might “disclose” how much money it made last year, or the head of the company might “disclose” that there was a problem with their production last year of a certain product. “Disclose” usually means that the information was secret and is often used when the information is negative in some way, though that’s not always the case.
“To uncover” (uncover) is to find something or become aware of something that was previously secret or unknown. “I’m going to uncover the truth” means I’m going to find the real truth – the truth that is hiding because someone doesn’t want me to find it, because it is hidden.
Finally, “to divulge” (divulge) means something similar to “disclose,” which is to make private or secret information known to others. Unlike “to disclose,” however, “to divulge” almost always involves private or secret information that might be what we would characterize as “sensitive” (sensitive). “Sensitive information” is information that could be damaging to someone if other people found out about it.
Finally, Muha (Muha) in Iran wants to know the meaning of the phrase “To stick it to” someone. “To stick it to” someone means to be very unkind to someone – to treat someone in an unfair way, usually so that you can get some sort of advantage, or sometimes just because you’re mad at the other person. You’re going to do something bad to another person because that person did something bad to you. That is the meaning of “to stick it to” someone. “My brother stole my money so I’m going to stick it to him. I’m going to steal his girlfriend.” Although, I would rather just have my money back.
Don’t confuse the phrase “to stick it to” someone with another vulgar expression in English, which is simply “stick it.” “You can stick it.” That’s a short form of a much more vulgar expression – “to stick it up your ***” (and you would put the thing that you sit on as the last word in that expression). You know what I mean. So, there’s a difference between telling someone “to stick it” and “sticking it to” someone. You would never want to see tell anyone “to stick it.” You might get into a fight, or if you said it to your boss, you’d probably lose your job, and I don’t want that to happen.
If you have questions or comments, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Hey, thanks for listening. Why don’t you come back and listen to us again, right here on the English Café?
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
atom – in science, the smallest amount of a substance that can exist by itself
* Two atoms of hydrogen and one atom of oxygen combine to create one molecule of water.
atomic bomb – a weapon that creates an extremely powerful explosion when atoms are split apart
* During the Cold War, the United States and the Soviet Union built more and more atomic bombs.
corps – a group of people who work together for a common purpose
* After the hurricane, a corps of volunteers began cleaning up the city streets and helping people dig through their damaged homes.
bunker – a strongly built underground structure, typically used for safety
* Everyone went down into the bunker to stay safe while the tornado ripped through the town.
regards – one’s affections; one’s warm, friendly feelings
* If you see Zayan when you’re visiting Paris, please give him my regards.
jockey – a person who rides a horse in a horse race
* The jockeys used their whips to encourage the horses to run as fast as they could near the finish line.
upbeat – energetic, happy, and excited
* The DJ at the party played mostly upbeat music so people could dance.
gang – an informal group of people one spends a lot of time with
* Let’s get the whole gang together from high school for a reunion.
to whisper – to say something very quietly so that it is almost impossible to hear
* Jean didn’t want speak loudly during the movie so she whispered to her friend.
to yearn – to want to have or to do something very much
* Michelle had thought that she would enjoy living abroad for the rest of her life, but after 10 years, she began to yearn for the familiar comforts of home.
to mingle – to spend time talking with a group of people in a social situation, such as a party
* The conference began with a small party at a bar where everyone could mingle and get to know each other before the lectures began.
throng – a large group of people or animals close together; a crowd of people or animals
* How were you able to stay together in the throng of people after the concert?
to propose – to suggest something to a person or group of people to consider, usually a plan or a theory; to ask someone to marry one
* The children proposed getting two puppies, but their parents thought one was enough.
to suggest – to mention something as possible to be done, used, thought about, or considered; to say that someone or something is good or deserves to be selected
* Can anyone suggest a good place for dinner near the airport?
to offer – to give someone the opportunity or option to accept or take something; to say that one is willing to do something
* Karl offered to replace our leaky pipe so we wouldn’t have to call a plumber.
to disclose – to make something known to other people or to the public
* Are employers allowed to disclose employees’ ages and salaries?
to uncover – to find or become aware of something that was previously a secret or unknown
* The reporter uncovered several instances of government officials taking large bribes.
to divulge – to make private or secret information known to others; to give secret information to someone
* Our employees sign a contract stating that they will not divulge company secrets.
to stick it to (someone) – to treat someone harshly or unfairly especially in order to get something for oneself, often for revenge or gain
* My boss doesn’t like me and frequently sticks it to me by making me work weekends.
What Insiders Know
Betsy Ross and the American Flag
Most Americans believe that the U.S. flag was created by a woman named Betsy Ross. Although this has been mostly “discredited” (shown to not be true) by “historians” (people who study the past), this continues to be taught in U.S. schools.
“Legend” (stories about something that never actually happened) says that, in 1776, Betsy Ross was “sewing” (making things from fabric) in her store, when Colonel Washington (who would later become the first President of the United States) came into her store with some other men. They asked if she would be willing to create a flag for the new country. The gentlemen showed her their “sketch” (a simple drawing) for the new flag, which included six-pointed stars. Betsy Ross said that a five-pointed star would be better, and “impressed” (made someone take notice) the gentlemen with her ability to fold a piece of paper and cut a five-pointed star with a single “snip” (one movement of the scissors). The flag that she “supposedly” (what many people think, but without proof) created became known as the “Star-Spangled Banner” (a patriotic American song).
The U.S. flag has gone through many “iterations” (versions), but the one with a circle of thirteen stars in the blue background in the upper left-hand corner is known as the Betsy Ross flag.
The flag was “adopted” (begun to be used) on June 14, 1777, when the “Continental Congress” (the group of men who wrote the U.S. Constitution) stated:
“Resolved” (decided): that the flag of the United States be thirteen stripes, “alternate” (first one and then the other) red and white; that the union be thirteen stars, white in a blue “field” (background), representing a new “constellation” (a group of stars thought to form an image or drawing of something).