= 1857
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 552.
This is English as a Second Language Podcast’s English Café episode 552. I am your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. “California, here I come, right back where I started from.” You know that song? No? That’s okay.
Just go to our website at ESLPod.com and you can become a member of ESL Podcast. All the cool kids are doing it nowadays. When you do become a member, you can download the Learning Guide for this episode that contains a complete transcript of everything we say, along with a complete list of vocabulary terms, definitions, sample sentences, and more. Go to ESLPod.com also to take a look at our Special Courses in Business and Daily English. And if you’re on Facebook, you won’t want to miss our Facebook page. Go to facebook.com/eslpod.
On this Café, we’re going to talk about the 44th president of the United States, Barack Obama. We’re also going to talk about the song “Anchors Aweigh.” And as always, we’ll answer a few of your questions. Let’s get started.
Barack Hussein Obama II was born (it is absolutely clear) on August fourth, 1961, in Honolulu, Hawaii. Obama’s father was from Kenya, and at the time was studying in the United States at the University of Hawaii. Barack Obama’s father’s name was also Barack Hussein Obama.
Normally, in the United States – and I understand also in Kenya – if a father gives his son the exact same name, you use the term “junior” after it. So, my father, for example, was named Patrick Dean McQuillan, and one of my brothers was named Patrick Dean McQuillan Jr. It is possible, although not very common, to use the number “two” instead of “junior” in naming your son. Normally you would use the number “two” when you are naming your son after another relative – that is, not giving your son your exact name.
But in any case, Barack Obama’s father was studying in the U.S., married to an American woman – Barack Obama’s mother, of course. His mother was originally from Kansas, whose family had moved to Hawaii. Hawaii is the only island state in the U.S., and Barack Obama is the first president to come from that state. Hawaii is also our newest state, the 50th state, having joined the U.S. only two years before Barack Obama was born in 1959.
When Obama was just two years old, his father left Hawaii to continue his studies at Harvard University. The Obamas divorced when he was only four years old. After his father left, Obama only saw him once before his father died in a car accident in Kenya when he was still relatively young, in 1982. Barack Obama’s mother remarried when he was six years old to a man from Indonesia, and together the two of them had a daughter by the name of Maya.
Shortly, after Maya was born, the family moved to Jakarta, Indonesia. There, Barack Obama went to a government-run school for about four years before returning to Hawaii to live with his grandparents. His mother travelled back and forth between Jakarta and Honolulu when she finished her doctoral degree – an advanced college degree which you can earn after your bachelor’s and master’s degree. I believe her doctoral degree was in anthropology.
In any case, Obama graduated from high school from a very good, expensive private high school in Honolulu in 1979. He later came to Los Angeles for two years, studying at a college called Occidental, a small private college here in L.A. After two years, he transferred – he moved universities – going to one of the better universities in the U.S., Columbia University in New York City in 1983.
He worked in New York, after finishing his degree, for two years and then moved to Chicago in 1985 where he became a community organizer. A “community” is a group of people who either live together or share common interests. When I say “live together,” I mean they live in the same area, the same neighborhoods. A community organizer, however, is a person whose job it is to try to get people to come together in order to supposedly improve the neighborhood in which they live or the community in which they live.
A community organizer often “engages in,” or takes part in, political activities on behalf of the community. It isn’t a job that pays very much money. It is a job, however, that gives you experience in local politics. Obama was a community organizer for a couple of years in a poor area in Chicago. In 1987, he left Chicago and decided to become a lawyer, attending law school at Harvard University – one of the best, if not the best law school in the country.
He graduated from Harvard Law in 1991 and did very well in his courses. In fact, he was the first African American to be the head of one of the student publications at Harvard – the Harvard Law Review. After he graduated, he returned to Chicago and married another lawyer by the name of Michelle Robinson, with whom he had worked in a summer job at a Chicago law firm, or law business, in 1989. The two eventually had two daughters, Sasha and Malia.
After returning to Chicago, Obama started teaching classes in law at the University of Chicago Law School. He also worked as what we would call a “civil rights attorney.” “Civil (civil) rights” refer to laws that are supposed to protect people and make sure they are treated fairly and equally regardless of their condition or their, in this case, race or sex. He organized a project to get more people to vote, specifically more African Americans in Chicago.
A few years later, in 1996, Barack Obama decided he would go directly into politics and become an elected official. In this case, he became a Illinois state senator. Most states have senators and representatives, just as the U.S. as a country has senators and representatives. Obama was a senator for the Illinois State Senate. One of the things that Obama got interested in was healthcare for people who didn’t have very much money.
“Healthcare” (healthcare) refers to the medical services that people get for their illnesses and diseases. It’s an issue that he would eventually become famous for when he became president, as we’ll see. In 2004, Barack Obama became an even more important politician in the state of Illinois; he was elected to the United States Senate. Each state in the U.S. gets two senators to send to our national legislature, what we call our “Congress.” And Barack Obama was elected as a senator from the state of Illinois.
In that same year, 2004, Barack Obama was invited to give an address – that is, to give a speech – at the Democratic National Convention, a meeting of all the members of the Democratic Party in which they decide who they are going to select as their presidential candidate for the election that year. A “candidate” (candidate) is the person who is chosen by a political party to be the representative of that party in an election.
The speech that Obama gave at the convention was shown on television and immediately made him a popular person, not just in his party, but in the United States. He became what some people called “a rising star.” A “rising (rising) star” is a person who is becoming popular very quickly because he is talented or he has something that people think will make him, in this case, a good candidate.
After his speech, one of the books that Obama wrote back in 1995, Dreams of My Father, became very popular. He wrote another book, called The Audacity of Hope, in 2006, and that also became popular. In his first book, Dreams of My Father, Obama talked about what it meant to be a biracial man in the United States. “Biracial” (biracial) refers to someone who is a member of two or more races – someone who is, for example, Asian and white, or in the case of Barack Obama, black and white, since his father was black and his mother was white.
Usually, when people run for the presidency of the United States, they have been in politics for many years with a lot of experience. But Barack Obama changed that pattern. In 2007, he announced that he was going to run for the 2008 presidential election. He decided that even though there was already someone with a lot of experience who wanted to be the Democratic nominee, a woman by the name of Hillary Clinton, he wanted to try to become that nominee, that candidate.
He came up with a very good campaign slogan, called “Yes We Can.” A “campaign slogan” (slogan) is a phrase that is easy to remember. Political campaigns or political attempts to win elections often use slogans or sayings that people will remember. In the case of Barack Obama, it was “Yes We Can.”
Obama’s campaign was also different in other ways, not just because he didn’t have a lot of national political experience. He also had a different campaign in the sense that he relied very heavily on a grassroots organization for his campaign. “Grassroots” (grassroots) – one word – refers to an organization in which the majority of people are not politically powerful or rich. They’re ordinary people who organize this particular movement themselves without relying on a lot of help from people, in this case, in the higher or more powerful parts of the political party.
The grassroots campaign that Barack Obama organized “consisted of,” or was made up of, many people who gave small amounts of money, often through the Internet. This is how the Obama campaign or the Obama effort to become president began, although eventually other people, especially rich people here in California – celebrities, actors, and musicians – gave many more millions of dollars to the Obama campaign to help him get elected. Obama won the nomination, beating Hillary Clinton, and went on to win the presidency in 2008, defeating John McCain.
One of the things that Obama promised before he was elected was to try to get “polarized groups” in the United States, in American politics, to work together. “Polarized” (polarized) means “clearly divided” – when two groups have very different beliefs or goals. Although, as I record this episode, the Obama presidency is still going on in its second term in 2016, most people would agree that he was not very successful in getting the polarized groups in the United States to work with each other.
One thing he was successful at doing, however, was passing a law in the year 2010 that changed the healthcare system in the United States. Remember, I mentioned how Obama was interested in our healthcare system, in doing something about it. In 2010, with the help of the Democrats in the U.S. Congress, he signed what was called the “Affordable Healthcare Act.” “Affordable” (affordable) means reasonably priced, not expensive.
The idea behind the law was to help make healthcare more affordable so that more people could get it. The law later became called “Obamacare,” because it was Obama who was the person most responsible for getting it made into law. We’re not sure whether it has really been that successful. It’s too early to say. Some people say yes and some people say no.
Obama won re-election in 2012, defeating again the Republican candidate – this time it was a man by the name of Mitt Romney. Since we are still in the Obama administration at the time of this recording, it’s difficult to try to give any sort of evaluation of his presidency either in terms of what has happened in other countries – in terms of what we would call “foreign policy” – or in the policies here in the U.S. That will have to wait for future historians to decide.
There’s no question that Barack Obama, however, will be remembered, if for no other reason than being the first African American president of the United States.
Now let’s turn to our second topic, a popular song called “Anchors Aweigh.” An “anchor” (anchor) is a heavy object that you attach to or connect to a rope or chain. You use an anchor on a boat so that the boat doesn’t move. You take this heavy anchor and you throw it into the water. The anchor is connected to the boat by a rope or a chain and it will help keep the boat from moving around.
The term “anchors aweigh” was used, especially in the U.S. Navy, to describe when the ships of the Navy were beginning their trips. They would bring the anchor out of the water. That’s what the word “aweigh” (aweigh) means. After they brought the anchor “aweigh,” or out of the water, then they could begin their trip or journey. The “navy” (navy) is the part of a military or part of the military forces of a government that is responsible for the ships and boats on oceans and other bodies of water controlled by that country. The United States has a navy as part of its military.
A man by the name of Charles Zimmerman, who was the leader of the U.S. Naval Academy Band, or group of musicians, wrote the song “Anchors Aweigh” in 1906. The Naval Academy is basically the college or university that teaches men and women who are going to become part of the U.S. Navy’s leadership. Zimmerman wrote the music to the song, and a student at the Naval Academy by the name of Alfred Miles wrote the original words, or lyrics, to the song.
To this day, the song is still sung by members of the U.S. Navy, and it’s known to most Americans, who have heard it at one time or another. The song was actually first performed in 1906 at a football game, an American football game between the team of the Naval Academy and the team of the U.S. Army Academy, which we commonly call “West Point.” The original lyrics or words to the song are mostly about football and beating the Army football team.
However, the lyrics were changed later to talk more about the U.S. Navy in general and what happens when they are getting ready to leave on a trip – when they are “anchors aweigh.” The song was later recorded and made popular in the 1920s. It became even more popular during World War II, especially at the end of World War II, because of a 1945 movie called “Anchors Aweigh” starring Gene Kelly and Frank Sinatra. That was a movie about two members of the Navy. We would call them “sailors” (sailors) here in Los Angeles.
The words of the song have been changed most recently in 1997. The most famous verse, or part, of the song, says “Anchors aweigh, my boys. Anchors aweigh. Farewell to foreign shores.” “Farewell” means goodbye. “Shores” (shores) refers to the part of the land that is right next to water. So, “Farewell to foreign shores” means that you are leaving a foreign country, presumably coming back to the United States. The song continues, “We sail” (sail) – that is, we go in our ship – “at break of day” – that is, at the beginning of the day, when the sun comes up.
“Through our last night ashore” – that is, the last night that we are at a particular place, on the shore of some particular country – “drink to the foam until we meet once more.” “Drink to the foam” (foam) probably refers to drinking something like beer. “Beer” often has a white substance at the top of it, on the top of the glass of beer, called “foam.” “Here’s wishing you a happy voyage home.” A “voyage” (voyage) is a long trip, a long journey. Here’s a recording of the U.S. Naval Band playing one part of “Anchors Aweigh” to give you a little idea of how the music sounds.
Thanks to the U.S. Naval Band - thanks, guys! - for coming here and playing the song for us right here in our beautiful studios.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Ivan (Ivan) from Russia – specifically, Siberia. Ivan wants to know the meanings of the words “diffidence,” “timidity,” and “shyness.” Let’s start with the third word, “shyness” (shyness), which is the most common of the three. “Shyness” is when you feel nervous and perhaps uncomfortable about meeting and talking to people. “Timidity” (timidity) is different from shyness. “Timidity” is when you don’t have courage or confidence to do something. We more often hear this word as an adjective, “timid” (timid).
If someone is “timid,” someone is a little bit afraid, someone is lacking confidence. They don’t have courage to do something. “I’m timid in talking to beautiful women.” I’m lacking confidence. I don’t have the courage to do it because I’m afraid they won’t like me. That’s “timid.” “Shyness” is when you don’t like talking to anyone – when you are uncomfortable talking to people in general. “Timidity,” or “being timid,” is when you lack courage or confidence in doing something – not just in speaking to someone, but in carrying out any sort of action that might require courage.
“Diffidence” (diffidence) is the least common of these three terms. “Diffidence” is being shy because you lack confidence. So, it’s in some ways a combination of these two ideas of “shyness” and “timidity.” If you do hear this word, you’ll probably hear it in the adjective form, “diffident.” “Shyness” isn’t necessarily a bad thing. It’s not a negative way to describe someone’s personality. “Timid,” on the other hand, is usually considered something of a criticism of a person who lacks confidence or courage – similarly with the word “diffident” or “diffidence.”
Arthur (Arthur) in Brazil wants to know the difference between “receipt” and “reception.”
“Receipt” (receipt) can mean a couple of different things. It can mean a piece of paper that you get after you buy something. When you go to the store and buy something, usually the store will give you a “receipt.” It’s a piece of paper that says how much you paid for the item and usually the name of what you bought.
“Receipt” can also mean the act of receiving something. You could say, for example, “I am in receipt” – notice the preposition “in” – “of your letter.” That would be a very formal way of saying, “I have received your letter.” You might read on a website, “Upon receipt of this item, please email us,” meaning when you get it, when you receive it, please email us.
The word “reception” (reception) also has a couple of different meanings that are related, as is the word “receipt,” to the verb “to receive” but are somewhat different in terms of how we actually use them in context. One meaning of “reception” is the kind of welcome that someone is given. You could say, for example, that “I received a very kind reception when I visited my friend.” That means my friend, when I arrived there – when he “received” me, you could say – treated me very well. He gave me some food. He offered me some wine and so forth. It was a very nice “reception” by my friend.
The word “reception” can also describe a group of people getting together to celebrate something or simply to meet and talk after an event. “There was a concert followed by a reception.” That means first you went to listen to some music, and then the people who were at the concert, perhaps also with the musicians, got together and drank coffee and talked. That would be another meaning of the word “reception.”
“Reception” can also refer to the party that you have after a wedding. A “wedding reception” is the party that you have after someone gets married. Notice we don’t call that a “wedding party.” A wedding party” actually refers to the people who are part of the wedding ceremony – the bride and groom, the woman and man getting married, along with the best man and the maid or maiden of honor, plus any other groomsmen or bridesmaids that are part of that group. That’s the “wedding party.” The actual party/celebration after a wedding is called the “reception.”
We also use the word “reception” to describe how well you are able to receive television or radio signals. You could talk about your television having “poor reception.” That means it isn’t able to get the electronic signals well enough in order to be able to watch a television program without problems. Nowadays, of course, many people have cable television, so they have wires that go to their house that provides them with television service.
You could also have “satellite television,” as I do, and there you could talk about “satellite reception.” If there’s a tree in front of your satellite receiver, your satellite dish, you might get poor reception. You can’t get the radio signal from the satellite that is above the earth.
Yet another meaning of “reception” is to describe an area in a hotel or an office building that is right when you walk into or enter the building. It’s the first place you go into as a visitor to that building or that hotel. You could think of it as the place where the building “receives” you, where you come into as you enter.
Finally, Thai (Thai) in Vietnam wants to know how we use the responses in English “Not at all” and “No problem,” especially when you hear the word “Sorry” or the expression “Thank you.”
If someone says “Thank you” to you, the most formal way of replying or responding to that is to say “You’re welcome.” However, informally, especially in American English, people sometimes say things like “No problem” or “Not at all” or perhaps “Don’t mention it.” Those are also ways of responding to someone who says “Thank you” to you. If you give someone a gift or if you help someone in some way, that person may say “Thank you” to you and you could say “No problem” or “Not at all.”
Personally, I prefer people say the more formal “You’re welcome,” but that’s just me. Sometimes you will hear these expressions “Not at all” or “No problem” when someone says “Sorry” to you. For example, if you are on a busy bus, a crowded bus, and someone accidentally hits you, someone bumps into you, that person may say “Sorry” or “Excuse me” or “I’m sorry.” You could say “No problem” or “Not at all” in those cases as well.
If you’re saying “Sorry” for something more serious – say, for example, you hit someone’s car and you damaged it – if you said “Sorry” in that case, the person is probably not going to respond “Not at all” or “No problem.” You might hear them say, “Oh, it’s fine. It’s okay. Don’t worry about it.” The person might also be very angry with you and say, “Sorry? Sorry? What do you mean you’re sorry? You ruined my car!” But let’s assume the person is a little nicer than that.
In that case, in a more serious case of the use of “Sorry,” when you’ve really done something wrong, you probably won’t hear someone say “Not at all” or “No problem.” So it depends on the context of the use of the word “Sorry” or “I’m sorry.” For something not very important, for something “minor” (minor), then, “Not at all” or “No problem” might be the most common response.
There are other ways of using “Sorry” that aren’t related to asking for forgiveness. In those other cases you would not use these expressions, either. For example, if someone says something to you and you don’t hear the person, you might actually say “Sorry?” or “Excuse me?” When “Sorry” means “Excuse me” in those cases, the other person naturally is not going to say “Not at all” or “No problem” – the other person is going to repeat what he said to you. So it all depends on the context, the way in which the word is used.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
community organizer – a person whose job is to organize activities for people who live in a specific area to improve the area
* There were no neighborhood parks, so the community organizer helped residents to get the city government to build one.
healthcare – the medical services available for people to help them become physically and mentally healthy
* Our hospital provides healthcare for anyone regardless of the ability to pay.
candidate – a person who is chosen by a political party to run for a political office
* Usually there are two main candidates who run for office in the United States – one from the Republican Party and one from the Democratic Party.
rising star – a person who is quickly becoming popular or important
* Jules was a rising star on the team and soon played in every match.
biracial – involving two different racial groups; involving two groups with different backgrounds, cultures, appearances, and histories
* Some American soldiers stationed in Japan and South Korea in the 1940s to 1960s married Japanese or Korean women and had biracial children.
campaign slogan – a short phrase that is easy to remember used by politicians when they run for office
* Dwight D. Eisenhower used the campaign slogan “Peace and Prosperity” in his 1956 presidential campaign.
grassroots – an organization or movement where ordinary people make up the majority of the group, making decisions and taking action
* The neighbors knew that if they wanted to make their streets safer, they would have to do it themselves so they organized a grassroots movement.
polarized – divided into two clear groups with very different beliefs and goals
* The Martinez family was polarized during the Championship, with Maria and Joaquin supporting Mexico and Juan and Sonia rooting for Germany.
affordable – not expensive; reasonably priced
* In many cities it is hard to find an affordable apartment in a safe neighborhood.
anchor – a heavy object attached to a rope or chain that is thrown into the water in order to keep a boat or ship in one position
* The captain dropped the anchor into the water when they reached the harbor.
ashore – on land and not on the sea
* After spending the day on a sailboat, everyone was happy to go ashore.
foam – the group of small white bubbles that form on a liquid when the liquid is moved or stirred
* Do you like a lot of foam on your coffee with steamed milk?
diffidence – being modest or shy because of a lack in confidence; not feeling comfortable around people because of self-doubt
* Julia’s diffidence makes it hard for her to contradict her boss.
timidity – feeling or showing a lack of courage or confidence; easily scared
* We want students to overcome any timidity and ask questions in class.
shyness – feeling nervous and uncomfortable about meeting and talking to people
* Carl’s shyness prevents him from talking to people, especially women.
receipt – the act of receiving something; a piece of paper on which the things one buys or the services one pays for are listed with the total amount paid
* Please call the New York office to notify them of our receipt of their documents.
reception – the kind of welcome that someone or something is given; a social gathering to celebrate something or to welcome someone
* News that salaries would be cut didn’t get a good worker reception.
no problem – a polite response to “thanks” or “thank you”; used to express agreement
* A: “Thanks for giving me a ride home.”
B: “No problem.”
not at all – a polite response to “thanks” or “thank you”; by no means
* A: “You’ve helped me so much in filing out these forms.”
B: “Not at all.”
no big deal – used to indicate that something is not difficult or troublesome
* A: “Sorry for waking you up so early in the morning.”
B: “No big deal.”
What Insiders Know
The Navy SEALs
The United States Navy’s Sea, Air, and Land Forces, most commonly referred to as the Navy SEALs, are “elite” (the best of the best) soldiers who receive expert training for the most “challenging” (very difficult and complex) situations. The SEALs were “established” (created) by former President John F. Kennedy in 1962, in response to a clear need seen in World War II for a better “amphibious” (on water and land) wartime “force” (group of trained police or soldiers).
The SEALs specialize in “unconventional” (not usual or traditional) “warfare” (fighting). They “conduct missions” (carry out plans) on land, sea, and air, especially “clandestine” (secretive and confidential) missions. They capture “enemy soldiers” (people fighting on the other side of a war) and “terrorists” (people and organizations that try to create fear among the public through violence) and collect “intelligence” (secret information about another nation’s plans and military). Often the SEALs “go in” (enter an area) to perform “reconnaissance” (military observations about an area, including the number of weapons or people) and destroy “obstacles” (things that block one’s path) to make possible “amphibious landings” (when soldiers arrive by sea and then move onto land).
The minimum physical requirements for SEALs are much more “demanding” (strict; harsh) than those for other types of Navy soldiers. For example, they must be able to swim 500 yards (450 meters) in 12 minutes and 30 seconds and run 1.5 miles (2.4 kilometers) in 10 minutes and 30 seconds. They must also be able to complete 50 “push-ups” (lying one’s stomach and raising one’s body by using the muscles in one’s arms), 50 “sit-ups” (lying on one’s back and sitting up without using one’s arms), and 10 “pull-ups” (hanging from a bar and bringing one’s chin above that bar), each within a two-minute period.