= 1863
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 558.
This is English as a second Language Podcast’s English Café episode 558. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website, ESLPod.com. Download this episode’s Learning Guide, an eight- to ten-page guide we provide for all of our current episodes that gives you additional help in improving your English.
Are you on Facebook? Hey, so are we. Go to facebook.com/eslpod and like us. On this Café, we’re going to talk about one of the most famous television shows – and later, movie franchises – Star Trek. We’re also going to talk about a very important law in the middle of the nineteenth century that changed the way the United States grew as a country, something called the Homestead Act of 1862. And as always, we’ll answer a few of your questions. Let’s get started.
[Star Trek theme music]
Star Trek was a science fiction show that was on American television from 1966 to 1969. The word “trek” (trek) means a long and difficult journey, a long and difficult trip. The show Star Trek was about a starship, a vessel that took a long trip into outer space sometime in the future.
Star Trek is an example of a “science fiction” show – a show that describes how people and societies will be or could be affected by scientific developments in the future. Science fiction is not just for television, of course. There are science fiction novels and science fiction movies, and I guess science fiction video games, nowadays.
Star Trek was a science fiction television show that told the story of a spaceship and its crew that traveled through outer space. A “crew” (crew) is a group of people who operate a ship, an airplane, or a train. You may hear that word, for example, on an airplane. The captain of the airplane may talk about the “flight crew” – the people who work on the airplane. Well, we’re talking about the crew of a spaceship called the USS Enterprise.
“Enterprise” (enterprise) is usually a word we use to describe a project or a plan that is going to be difficult or that requires a lot of work. You could talk about a “difficult enterprise” for your company. You can see how this is a good name for this spaceship, since the USS Enterprise is going to be going on a long trek, a long journey, and it’s going to take a lot of effort.
Now, the particular journey or trip that the USS Enterprise is on is called a “mission” (mission). A “mission” is another word that you could use in business English to talk about the purpose for doing something, but when we talk about a mission in a military sense, we’re talking about a journey or a job or task that is being given to a person or a group of people.
You may know of another television show, Mission Impossible, that also became a series of movies. There again the word “mission” is used to mean a task or a job that is given to someone to do. The mission of the USS Enterprise is explained in the introduction to the show. It is “to seek out new life and new civilizations, to boldly go where no man has gone before.” “To seek out” is a two-word phrasal verb meaning “to look for,” but to look for in an active way – to really try to find something. “New life and new civilizations” are the things that the USS Enterprise is seeking out.
It is going to “boldly (boldly) go where no man has gone before.” “To boldly” do something is to do it without being afraid to do it, even though there may be danger involved. The USS Enterprise is going “to boldly go where no man” – or no one, no person – “has gone before.” The leader of the USS Enterprise’s crew is the captain, and his name is James T. Kirk. On the original Star Trek television show, the captain was “played by” – that is, the name of the actor was – William Shatner.
The first officer, or second most important person on the ship, was named Mr. Spock, and he was played by the actor Leonard Nimoy. Kirk was human, but Spock was only partly human. He was from a different planet called “Vulcan.” He was half human and half Vulcan (Vulcan being another species, another kind of living being). His mother, I believe, was human, and his father was Vulcan.
In any case, also on the ship was the doctor. His name on the show was Leonard McCoy, although he had the nickname “Bones.” Also part of the crew were the engineer, Mr. Scott (or “Scottie,” as he was called), Lieutenant Uhura, and Ensign Chekov. All of the members of the crew were part of what was called “Starfleet,” which was basically the military part of the United Federation of Planets that was, I guess you could call it, sort of like the modern-day European Union, but for planets instead of countries.
During the three years that the show was on American television in the late 1960s, the crew of the enterprise met many different alien peoples. An “alien” (alien) is someone who comes from a different planet, although we also use it sometimes to refer to people from another country. So, if you come to the United States, you are technically an alien.
You may read in the American papers or see on the internet stories about “illegal” or “legal” aliens in the United States. We’re not talking about Vulcans or people from other planets – although you know, my neighbor has some really weird ears. It’s possible that he’s Vulcan. It’s possible. I’m not saying he is. I’m just saying it’s possible.
Well, the aliens on Star Trek really were from other planets, and the Starship Enterprise would meet these different aliens. Some of them would be friendly and some of them were not friendly. And so each show was about usually meeting a new group of aliens and the adventures that they had with this group of aliens.
Star Trek was cancelled in 1969 – that is, they stopped producing new shows because it just wasn’t very popular with a large group of people. But there were a smaller group of people that were fans, that really loved the show. These fans became known in English, depending on who you talk to, as either “trekkies” or “trekkers.” These were fans of Star Trek.
The number of fans of Star Trek, interestingly enough, increased during the 1970s and 1980s because even though the show was no longer being produced, many television channels had the show on the air in what we call “reruns” (reruns). A “rerun” is when they show an old television program again. I grew up in the 1970s watching Star Trek reruns and became a fan of the show, as did millions of other Americans who never saw it when it was originally on in the late 1960s.
By the late 1970s, the movie studios got interested in the Star Trek story, and they made a movie about Star Trek using the same group of actors and the same basic story. It was called – what else? – Star Trek: The Motion Picture. Motion picture is another term for a movie. It was released in 1979. There followed several other Star Trek movies in the early and mid 1980s based on the show. You may have seen some of them.
Because the Star Trek movies were popular, the television studios decided hey, maybe we should make another television series about the Star Trek story but do it a little bit differently – do it as what is called a “spin-off.” A “spin-off” (spin-off) is when you have a television show or a movie that is related to a previous television show or movie. Typically when you take some part of the story, or even some characters that were in the original story, and you make a new story, a new television show, or a new movie.
In Star Trek, they decided to create a sequel to the original television series where we would follow the adventures of a new crew of the USS Enterprise that lived later on, after the original USS Enterprise crew had finished their journeys. In other words, it was a similar story but later in time, more into the future. In 1989 this new television show, called Star Trek: Next Generation, was aired on American television.
The new captain of the Enterprise was Jean Luc Picard, and of course there was a new first officer, a new engineer, and so forth – a whole new crew. But the ship was still called the USS Enterprise and they still went on adventures seeking out new life and new civilizations. The actor that played the captain was a British actor by the name of Patrick Stewart.
This new Star Trek series – which fans of the show often called by its initials TNG, for “The Next Generation” – continued on American television until 1994 and is still shown in reruns, as is the original Star Trek series, on many television stations in the U.S. In 1993, even before the end of Star Trek: The Next Generation, they started another Star Trek spin-off, called Star Trek: Deep Space Nine.”
Later, in 1995, there was Star Trek: Voyager, and in 2001, Star Trek: Enterprise. The television shows were successful enough that they also made more Star Trek movies, this time with the new crew of the USS Enterprise, including Patrick Stewart playing the Captain Picard role.
By 2005, Star Trek was no longer on American television except in reruns, but Americans and those around the world who became fans of Star Trek still wanted more of the story, and so they started making a new set of movies in 2009. These were what we would call “prequels” to the original Star Trek story. A “prequel” (prequel) is a story that takes place before the original story.
In the prequel Star Trek movies, we see the young James T. Kirk and the young Spock when they first began as the crew of the USS Enterprise. So, it takes place before the original Star Trek TV series did, in time. Of course, we’re talking about the future here. This is all science fiction after all.
I am a fan of Star Trek. I’ve seen all of the original shows and all of The Next Generation series of shows. I didn’t like some of the other spin-off TV shows. I didn’t watch those. I have seen all of the movies. And if you haven’t seen Star Trek movies, I think you might enjoy them, as well as, in particular, the TNG series.
Now let’s turn to our second topic, the Homestead Act of 1862. The word “homestead” has a couple of related meanings. One meaning of “homestead” is simply your house and the land that your house is on, including any other buildings on that land. However, when we’re talking about U.S. history, the word “homestead” usually refers to land that is used for farming – a piece of land that is used for farming – and a farmhouse and other buildings that are on that land. It’s this second definition of “homestead” that is referred to in the Homestead Act of 1862.
In 1862, you may remember, the United States was in the middle of a civil war. Nevertheless, the government was concerned about making sure that the new territories that were part of the United States, most especially the areas in the western part of the United States, would be settled by people from the United States. The American government encouraged people to go out into these new states and territories and live there and start creating communities there.
To do this, to encourage people to move out from the eastern part of the United States into the western part of the United States, they gave them land – free land. They gave them land that they could use for farms. This area of land, what we would call this “plot” of land, was called a “homestead.”
Before 1862, all of the land in the United States that didn’t belong to an individual person or to a company belonged to the government. You could still say that’s true. If you wanted to buy land from the government, it was somewhat expensive. The land cost about a dollar an acre. An “acre” (acre) is .4 hectares for those of you on the metric system. This may not sound like a lot, but one dollar in 1800 was equal to about 14 dollars today.
In addition, people had to buy at least 640 acres in order to get land from the U.S. government during the period before the Homestead Act. This was too much money for most people, and so people didn’t go out and buy land, and didn’t moved to these new Western territories and states. Nevertheless, there were many people who wanted to own land and to build farms and to cultivate crops in these new territories. They just didn’t have the money to do so. “To cultivate” (cultivate) means to prepare land to grow food. A “crop” (crop) is a plant that you use either for food or to make something else – or nowadays, here in California, to smoke.
Many people began to argue that the government should give land to people so that they could go out and settle on the land and build farms. Until about 1860, most politicians from the southern United States were against the idea of giving land to people for free.
Now, why were people in the South not interested in giving land for free in these new western territories and states? Well, of course, because they themselves in the South had farms and they didn’t want competition. They didn’t want other people going out and growing food and other crops that might compete with the crops that they were growing in the South.
In 1861, the U.S. Civil War began, and the Southern states no longer were voting in the national government in Washington, D.C. And since those senators and representatives were no longer in Washington, D.C., the representatives and senators from the Northern states who wanted to pass a law like this did so, and they did, calling it the Homestead Act of 1862. The law said that anyone who wanted to go out to these Western territories and states could get 160 acres of land for free. All they had to do was pay a small application fee, or charge.
Most of this land was located west of the Mississippi River, between the Mississippi River and the Pacific Coast out here in California. But it also included other areas including Ohio, Indiana, Illinois, and some of the Southern states that were then fighting against the Northern states – states like Mississippi, Alabama, and Florida. A person who took this land, however, had to agree to live there for five years, build a house, and cultivate the land.
After five years, the person could go back to the government and the government would give that person a “deed” for the land. A “deed” (deed) is a legal document that proves that you own a piece of property. I own a piece of property: my house and the land my house is on here in Los Angeles. I have a deed for my land that proves that I am the owner of that land. Well, my wife and I, technically.
Now it wasn’t easy, of course, to go out to these lands where there were no people and start a farm and start cultivating crops. In fact, it was quite difficult. You were out basically by yourself. There weren’t any Starbucks. There weren’t any grocery stores. You had to build your own house. Many of these people who took the government land didn’t know a lot about farming, so you had to learn very quickly if you were going to survive on one of these homesteads.
Many people who went out and took the land were not able to stay for five years, and so the government took the land back because the people didn’t stay for the five years required in order to get possession of the land. But many people were successful, and those people, especially in the late 1860s and 1870s, were able to take advantage of this great opportunity to get, basically, free land.
The government began building railroads out into the western United States, and this helped the people on these homesteads sell the food that they were growing on their homesteads and make money. In many ways, the Homestead Act of 1862 was responsible for populating the western United States, or at least many areas of it. I had relatives who were homesteaders in North Dakota back in the 1860s and 1870s. They went up to North Dakota, which is located next to the state of Minnesota, and started a farm on a homestead.
The Homestead Act was the law in the United States for more than 100 years. It wasn’t until 1976 that the government repealed, or got rid of, the Homestead Act and put a new act, or new law, into its place. By this time, of course, we didn’t need people moving out into the western parts of the U.S. In fact, if you live in Los Angeles, you would probably want fewer people here, not more.
Now let’s answer some of the questions you have sent to us.
Our first question comes from David in an unknown country, a secret country, a country so secret, I can’t even tell you what it is. David wants to know the meanings of “medicine,” “medication,” and “drug.” All three of these words are closely related. Let’s start with the most common of the three words, which is “drug” (drug). A “drug” is some substance that is used to help your body, usually to either make you less sick or to keep you from becoming sick.
In American English, there are “legal drugs” – drugs that the government allows you to take and to sell – and “illegal drugs.” When you read in the newspaper the word “drugs,” sometimes it refers to legal drugs and sometimes it refers to illegal drugs. If you don’t see the word “legal” or “illegal” in front of the term, it probably refers to illegal drugs like cocaine, heroin, and in most places, marijuana. If your mother says to you, “Don’t take drugs,” she means illegal drugs, because there is sometimes this confusion over what kind of drugs a person may be talking about.
There are other terms for the substances we use to make you healthy or to keep you from getting sick. One of those words is “medication” (medication). “Medication” is a substance specifically for treating a disease or making you feel better, such as relieving or lessening your pain. Medication is almost always, a legal drug that a doctor gives you. The plural of “medication” is “medications.” Sometimes we shorten the word “medications” to “meds.” You might talk about the “meds” (meds) that you take for some illness or disease.
The word “medicine” (medicine) can refer to substances that are used to help with medical problems. In other words, the word “medicine” can also be used to mean the same as “medication” or legal drugs. However, “medicine” also is the word we describe the general science or practice of helping people stay healthy or get cured of a disease. Someone who’s going to become a doctor studies “medicine.” That’s what they study. That’s the science or branch of knowledge they study.
So “medicine” can refer to the science or field of study, as well as to drugs that you take to help you with some medical problem. Of course, some people believe that some drugs – that is, “illegal substances” – are also good as medications. And we have in some places in the U.S., including here in California, what is called “medical marijuana.” Some states have laws that allow you to take medical marijuana, but that’s a whole nother story.
Josue (Josue) in the Dominican Republic wants to know the meaning of two terms. The first is “wild card” and the second is “K9.” A “wild (wild) card,” in a game of cards such as poker, is a card that can represent any other card in the game.
So, if you are playing a game like poker, you have these little rectangular pieces of paper called “cards.” The whole group of cards, 52 of them, is called a “deck (deck) of cards.” A “deck of cards,” or a “deck of playing cards,” has different colors, numbers, and figures on them. Sometimes in a game of cards such as poker, you decide that one of these 52 cards is going to be a “wild card,” meaning it can “represent,” or you can say it is, any of the other cards’ value.
The term “wild card” is also used in regular conversation to refer to something or some person whose actions we can’t anticipate, we don’t know, we’re unsure about. If you have a group of people in your company who are going to work together as a team, and four of you know each other very well but there’s a fifth person whom you don’t know very well, we might describe that fifth person as a “wild card” because you’re not sure how that person is going to react or how that person is going to work with the rest of you.
When you have a person or a thing whose influence you’re not really sure of or whose impact you can’t predict easily, we might refer to that as being a “wild card.” The word “wild card” is also used in sporting competitions to refer to a team that doesn’t have the best record, that hasn’t won the most games, but is still allowed to participate in some sort of final tournament or competition.
“K9” is a term that refers to a military or police dog that is used for military or police purposes. The term “K9” is usually spelled with the letter “K” and the number “9,” but it represents a word in English, “canine,” spelled (canine). “Canine” refers to a dog. It’s an adjective referring to a dog, but “K9” with the letter “K” and the number “9” refers to dogs that are used in the service of the police or of the military.
Finally Lenur (Lenur) in Russia wants to know the meaning of the phrase “to lay it on thick.” If someone says, “He’s laying it on a little too thick,” what does that mean? “To lay it on thick” (thick) is to exaggerate your praise of someone, to say someone is better than they really are, usually because you want to influence that person in some way. You want that person to do something for you or you want that person to think better of you.
So, I may say to you, “Oh, you are the world’s best piano player. You’re the best pianist in the entire world. I’ve never heard of anyone play the piano as good as you.” That’s “laying it on a little thick,” saying you are the best in the world. Even though you might be very good, you’re probably not the best in the world, right? I’m exaggerating my praise for you. I’m making it more than what is really the case.
Husbands sometimes lay it on thick with their wives when their wives are angry at them and they want the wives to forgive them for something they did (and husbands, of course, are always doing something wrong). So they may say, “Oh honey, you’re the most beautiful woman in the world. I love everything you do. That was a wonderful meal that you cooked me.” Even though your wife knows you’re “laying it on thick,” it might be just what you need to do in order to get her to forgive you. I guess I’m talking a little bit too personally here.
If you have a question or comment, especially one that isn’t too personal, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I am Jeff McQuillan – and you are, dear listener, the world’s greatest podcast listener. We love you. We think you are the best in the world. Come back and listen to us again then, won’t you? Right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
trek – a long and often difficult journey
* The trek up Mount Everest usually takes about two months, but it can take longer in bad weather.
science fiction – stories about how people and societies are affected by imaginary scientific developments in the future
* In this science fiction novel, everyone owns a robot that looks like a human and helps around the house.
crew – the group of people who operate a ship, airplane, or train
* The airplane’s crew included two pilots and six flight attendants.
enterprise – a project or plan that is difficult and that requires a lot of effort
* This is an ambitious enterprise requiring a lot of money and commitment.
mission – a task or job that someone is given to do, often involving travel
* The chef’s mission was to cook a five-course gourmet meal in less than an hour and serve it to a group of food critics.
alien – someone who comes from a different country or planet
* Do you believe aliens will someday arrive in a spaceship to take over the Earth?
spin-off – a product that is associated with an existing television show, film, or book, often including some of the same characters or a similar setting
* When the television show ended, a spin-off was created with one of the minor characters in the lead role.
homestead – a person’s house, especially a farm with all of its outbuildings, such as a barn where the animals are kept or a shed where tools are stored
* The Montoya family had a 200-acre homestead where they raised sheep.
to cultivate – to prepare the land and to grow food or other crops
* Jean loves gardening and prides himself on the big red tomatoes he is able to cultivate each year.
crop – a plant that is grown in large amounts, usually for food or to be made into useful products
* Corn is one of the major crops in the Midwest region of the United States.
deed – a legal document that proves that one owns a piece of property
* When will we get the deed for the land we purchased?
to repeal – to undo or take away a law that exists
* In the 1920s, the United States had a law that prohibited the production and sale of alcohol but it was repealed in 1933.
medicine – a substance that is used to treat medical problems or to relieve pain, often in the form of a pill or liquid; the science or field that deals with preventing, curing, and treating diseases
* Many children can’t swallow pills, so doctors prescribe medicine in liquid form.
medication – a substance used to treat disease or relieve pain
* This medication needs to be taken with food, or you may get an upset stomach.
drug – a substance that is used as a medicine; an illegal substance that people take for pleasure, such as heroine or cocaine
* Researchers are working on a new drug to treat throat infections.
wild card – a playing card that can represent any other card in a game; a person or thing that could affect a situation in a way that cannot be anticipated; a player or team chosen to fill a place in a competition after the regularly qualified players or teams have all been decided
* In this game, the aces and kings are wild cards.
K9 – a trained police or military dog
* K9s are trained to detect illegal drugs and used at airports to examine luggage.
to lay it on thick – to exaggerate praise; to give praise or make excuses that are greater, bigger, or better than it is
* You don’t need to lay it on so thick about my new car. I know you want me to take you on a ride, so let’s go.
What Insiders Know
The Hugo Awards
The Hugo Awards are given to authors “in recognition of” (giving attention and respect to) the best “science fiction” (related to how humans might interact with science and technology in the future) or “fantasy” (related to imaginary worlds) novels each year. They have been awarded since 1953, although they were previously called the Science Fiction Achievement Awards. The name was changed in 1993 to honor Hugo Gernsback, who created the popular science fiction magazine Amazing Stories. Many people consider him to be “the father of” (an early leader in) the science fiction “genre” (type of writing).
The Hugo Awards are “widely considered” (thought by many people) to be the “preeminent” (most important or distinguished) award for science fiction and fantasy writers. The awards are selected by members of the World Science Fiction Convention, and anyone can become a member. In 2015, the winners were selected by 5,950 “ballots” (pieces of paper on which people indicate their voting preferences).
Today, there are many categories for the Hugo Award. These include awards for the best “fan magazines” (magazines for people who are passionately interested in something), “audiovisual” (using something you can both see and hear) presentations, short stories, editors, and more.
“Award recipients” (the people who receive the award) do not receive any “remuneration” (money), but they do receive a “trophy” (a small statue that can be placed on a shelf for display) in the shape of a “rocket” (something that flies into outer space). In addition, the authors’ books are labeled with the Hugo Awards logo, which can help to “boost sales” (increase the number of copies that are sold).