= 1881
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 576.
This is English as a Second Language Podcast’s English Café episode 576. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to ESLPod.com. Why? Because you can take a look at our ESL Podcast Store if you do. In it, you’ll find all sorts of interesting English courses to help you improve your fluency even faster.
On this Café, we’re going to talk about the American writer James Baldwin. We’re also going to talk about a popular song from the twentieth century, “High Hopes.” And as always, we’ll answer a few of your questions. Let’s get started.
James Arthur Baldwin was born in August of 1924 in New York City. He was the oldest of nine children and grew up in the neighborhood of New York City which is still to this day associated with the African American community: Harlem. At the time, Harlem was an area that was almost exclusively or solely lived in by blacks, or African Americans.
Baldwin did not grow up with his biological father. In fact, his mother never told him the name of his father. Instead, he was raised by the man his mother married after he was born, a man who was a preacher by the name of David Baldwin. A “preacher” (preacher) is a person who gives religious talks – we might call them “religious speeches” or “homilies” – in a public place, often in a church but not always.
The Baldwin family was very poor, and David Baldwin was very strict with his children. “To be strict” (strict) means often to have a lot of rules and to require people to follow those rules exactly. If we describe a parent as being “strict” with his or her children, we mean the parent usually requires the child to follow the rules perfectly, or nearly so. When Baldwin was growing up, during the 1920s and ’30s, African Americans, as you know, were certainly not treated the same as whites, or perhaps we could say even worse than today.
Baldwin had many negative experiences, especially with police officers, that made him an angry young man. He joined a church, however, when he was 14 and decided to become, very briefly, a preacher himself. He was very good at giving these sermons, these religious talks, and became very popular even though he was only a teenager. He did this for about two years and then decided that he didn’t want to be a religious person anymore. In fact, he stopped believing in God completely. He left the church and preaching, and decided to focus instead on writing.
When he was 15 years old, he finished high school early and moved to an area in New York City south of Harlem – considerably south, on the island of Manhattan – called Greenwich Village. Now Greenwich Village, you may know, is a neighborhood in New York City that is known for its artists. Even to this day it has that association, but especially during the early and mid-twentieth century. Baldwin got interested in writing. He worked in a lot of different places, enough to make money so that he could continue writing.
In 1948, not unlike other African American artists during the mid-twentieth century, Baldwin moved to France – in particular to Paris, France. He said he was tired of being treated as a person unequal to whites in his own country. He was tired of the discrimination against African Americans during this period. He lived in France until 1956, and during that time he became friends with both American and French artists – writers, painters, and so forth. He also wrote his most famous novel – some would say it’s his best novel – called Go Tell It on the Mountain.
That expression “Go tell it on the mountain” is actually from an old religious hymn, or religious song. The idea is that you would go up on top of a mountain or a high place and announce this wonderful news. The wonderful news is that Jesus Christ is born.
Go tell it on a mountain
that Jesus Christ is born.
It’s a famous, what we would call “spiritual,” or traditional African American religious song that Baldwin surely learned as a child and was known to most people, and is still known today and sung in churches. The book is basically an autobiography, or based on the life of Baldwin himself growing up in Harlem, growing up poor with a strict father and preaching in church. I say he grew up with a strict father, but it wasn’t his biological father. It was what we would call his “step (step) father.” Your “stepfather” is the man who is legally your father, but wasn’t actually there, well, nine months before you were born.
In any case, Go Tell It on the Mountain was based on Baldwin’s life – that is, it was taken from the real events of his own life. This is not unusual for a first time novelist, to use his own experiences. F. Scott Fitzgerald’s first novel is partially autobiographical – that is, it’s partly based on his own experiences growing up in my hometown of St. Paul, Minnesota. That novel was This Side of Paradise, by the way. Baldwin’s novel is still read in American schools and is considered by some to be a “classic” one of the better novels written in the twentieth century.
In 1956, Baldwin published another book that was much more controversial – that is, that people thought perhaps was a little too extreme or perhaps talked about things that many people would disagree with. The book told the story of a young gay man, a man who preferred or was romantically attracted to other men. This book, called Giovanni’s Room, talked about something that was not commonly talked about in American novels during this time, what we would nowadays call “sexual orientation” (orientation). “Sexual orientation” refers to one’s preferences, sexually, in terms of men and women.
Baldwin said that he himself was attracted to other men, and to talk about this in a novel was certainly controversial at the time. Baldwin returned to the United States from France in 1957 and became active in the civil rights movement of that period. The “civil rights movement” was about getting African Americans equality before the law – ending laws that discriminated against African Americans.
Baldwin himself was not in favor of using violence in order to get the civil rights that he believed African Americans deserved. Although, he was not exactly “on the same page,” we might say – that is, not completely in agreement – with Martin Luther King and his nonviolent approach. He was himself a socialist and believed in certain social changes as well as in changes that would affect the status of African Americans before the law. He was, then, in addition to being in favor of civil rights, also something of a radical in terms of his other political views.
Baldwin wasn’t just a novelist; he was also a journalist. He wrote essays, poems, and other writings about what was going on in American society during this period. He continued to publish novels. He published a new novel every year from 1961 to 1963, and a play in 1964. Baldwin was never completely happy with the changes that took place during the 1960s in America, and so he decided in 1970 to return to France, this time living in a small town in the southeastern part of France. And there he remained pretty much for the rest of his life until his death in 1987.
Baldwin is remembered now both for his original novel – his first novel, I should say – as well as for some of his essays. His other books I would say are less read than Go Tell It on the Mountain but can still be easily found.
We turn now to a famous song from the twentieth century, “High Hopes.” The expression “high (high) hopes (hopes)” refers to having expectations about something good that will happen in the future. When you feel that something good will happen, you have “high hopes.” We often use the proposition “for” (for). “I have high hopes for” a certain thing. I have high hopes for the Los Angeles Dodgers to win the World Series of baseball this year. I have high hopes. I expect it. I am “optimistic,” we might say, about it.
The song “High Hopes” was written by Jimmy Van Heusen and Sammy Cahn for a movie called A Hole in the Head. The song was sung by Frank Sinatra. Sinatra in the movie plays a father, and he sings the song to his son in the movie, who is played by the young actor Eddie Hodges. The song is meant to tell the son to keep trying even when things are hard, even when things are difficult. The song begins:
Next time you’re found
With your chin on the ground
There is a lot to be learned
So look around
The expression “to have your chin (chin) on the ground” means to be very sad or to be what we might describe as “discouraged” (discouraged). “To be discouraged” means you don’t have hope. You don’t think good things will happen in the future. By the way, the word “chin” describes that part of your face that is the lower part of your mouth. We sometimes talk about people having a “long face.” “To have a long face” means to be sad. So, if you had a really long face, I guess your chin would be on the ground, and that perhaps is where the expression comes from.
We can now understand, then, the first verse or part of the song: “Next time you’re found with your chin on the ground, there’s a lot to be learned, so look around” – look about you and see that you shouldn’t be sad. What should you look for? Well, the song tells us. It says:
Just what makes that little old ant
Think he’ll move that rubber tree plant
Anyone knows that ant can’t
Move a rubber tree plant
Well, what’s all that about? An “ant” (ant) is a very small little insect that lives on the ground and usually with lots of other little ants. Now, sometimes a whole group of ants is able to move a large amount of, say, dirt by working together. A “rubber tree plant” is a plant that grows a kind of flexible strong material called “rubber.” You’ll find rubber tree plants or trees in South America, for example.
Now, we wouldn’t expect a little ant to be able to move a whole tree, and of course one small ant cannot. The idea of the song is that little ants, even though they are small, are able to move a lot of things, do much more than it looks like they can do, because they are able to work together. So even though it seems as though the little ant cannot move anything as large as a rubber tree plant, you can have high hopes that the ant will be able to do it, and that’s the next most famous part of the song:
But he’s got high hopes
He’s got high hopes
He’s got high apple pie
in the sky hopes
So, the little ant has high hopes. How high? He goes “high apple pie in the sky hopes.” Well, that’s another weird expression. The expression “pie (pie) in the sky (sky)” means unrealistic. Someone who has “pie in the sky ideas” is someone who is dreaming about things that could never happen or things that are impossible. Well, the little ant, according to this song, has “pie in the sky hopes.” The song actually says, “he’s got high apple pie in the sky hopes.” The original expression doesn’t have “apple” in it, but it kind of makes it funny. The little ant has “high apple pie in the sky hopes.”
The rest of the song is, “So any time you’re getting low” – that is, any time you feel sad – “instead of letting go” – instead of giving up – “just remember that ant” – think about the little ant and how much it is able to do even though it is small. Then the song ends with a line that is also famous: “Oops, there goes another rubber tree plant.”
“Oops” (oops) is an expression – we would call it an “interjection” – when you are surprised about something or when you make a mistake. In this case, it indicates surprise. “Oops, there goes another rubber tree plant” refers to the idea that the little ants are moving this rubber tree plant, and you are watching it go by even though it seems impossible that an ant can move a rubber tree plant.
Oops, there goes another rubber tree
Oops, there goes another rubber tree
Oops, there goes another rubber tree plant
Although most Americans just know that first part of the song, the original song sung by Frank Sinatra continues on, giving another example of another animal, a “ram” (ram), which is able to do things you would not expect it to be able to do. The song was so popular that in 1960 it won an Oscar, an Academy Award, for the best song in a movie for that year. It also became one of Frank Sinatra’s most famous songs.
In fact, it was so famous that one of the men who was running for president that year, in 1960, John F. Kennedy, asked Sinatra to create a version of the song that could be used for his campaign as his campaign song. A “campaign” (campaign) is the process of trying to get elected to public office. It’s that period of time and the activities involved in a person trying to win an election to get the most votes – in this case, to become president.
Frank Sinatra did in fact write a version of the song for Kennedy. The Kennedy version, of course, went a little differently. The Kennedy song said: “Everyone is voting for Jack” – Jack was the nickname for John Kennedy – “’cause he’s got what all the rest” – all the other people – “lack” (lack). “To lack” means you don’t have something, you’re missing something. “Everyone wants to back Jack.” “To back” (back) someone means to support someone. So, everyone is supporting Jack.
“Jack,” the song continues, “is on the right track” (track). The expression “to be on the right track” means that you are doing the right things or moving in the right direction in order to achieve some objective or reach some goal. So, “Everyone is voting for Jack, cause he’s got all the rest lack. Everyone wants to back Jack. Jack is on the right track.”
The song then continues, “’Cause he’s got high hopes,” meaning John Kennedy has high hopes, “He’s got high hopes, 1960’s the year for his high hopes. Come on and vote for Kennedy. Vote for Kennedy. We’ll come out on top.” “To come out on top” means to win, to be victorious, to beat everyone else. Of course, the Kennedy campaign wants to elect Jack Kennedy and so they want to win the election. They want to come out on top.
Then the song ends with “Oops, there goes the opposition – KERPLOP!” The “opposition” refers to the people you are trying to beat, or in this case Richard Nixon, who was the Republican candidate whom, in fact, Jack Kennedy did beat in the 1960 election.
“Kerplop” (kerplop) is an unusual word. You don’t hear it very often anymore. It’s basically the sound that is made when something falls or drops. I don’t know what we would say instead nowadays – probably not “kerplop,” but that word was more common in the middle of the twentieth century and it was also part of the original song in a different verse we didn’t talk about.
So, Kennedy won the election probably not because of that song. In fact, he barely won the election. It was a very close election, but he did defeat Richard Nixon and win the 1960 election.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Martin (Martin) in Argentina. Martin wants to know the difference between “homeless” (homeless) and “destitute” (destitute).
“To be homeless” means to be without a place to live. The suffix “-less” (less) usually means “without.” So, if you are, for example, “penniless,” you don’t even have a penny. You don’t have any money. If you are “homeless,” you don’t have a home, a place to live. “Destitute” means that you are very poor, so poor that you don’t have enough money for your basic needs – perhaps you don’t have enough money to eat or you don’t have enough money to buy clothing.
“Destitute” isn’t necessarily the same as “homeless,” although people who are destitute are also often homeless. The word “homeless” is often used as a noun to describe people who do not have a place to live, a permanent place to live. “Destitute” is a little less common of a word, of an adjective. You don’t hear that as much, at least in common conversation. We talk about people who are very poor or living in poverty, but “destitute” is a word you are more likely to see in a novel or in a book.
Our next question comes from Tais (Tais) in Brazil. The question has to do with the word “odd” (odd) versus “odds” (odds). The word “odd” has a couple of different meanings. Normally, it’s an adjective used to describe something or someone who is strange or unusual – different from what you would expect, usually in a bad way. If you say to someone, “You look odd,” you’re saying there is something unusual about the person, but also something wrong with the person. There’s something that doesn’t look right, that looks strange.
“Odd” can also be used to describe different kinds of things that are not all part of the same class or category. If, for example, you have two different socks, but they are different colors, you would say, “I have an odd pair of socks.” They don’t match. They don’t go together.
“Odd” can also be used in math to be the opposite of “even.” An “odd number” is one, three, five, seven, nine, eleven, and so forth. An “even number” can be divided by two, so two, four, six, eight, ten are “even numbers.” Those that are not even are “odd numbers.” You’ll sometimes hear people say, “I have an odd number of chairs.” That means I have five chairs instead of four chairs, or seven chairs instead of six chairs.
The word “odds” with an (s) at the end refers to probability and statistics. “Odds” is normally used to describe the possibility that something will happen. We talk about having “good odds” and “bad odds.” “Good odds” means that it is likely that you will win or that you will be successful or that something will happen in the future. We may say, “The odds are that he will win.” That means it is likely or it is probable that he will win.
There’s another expression we have, “against all odds.” To say someone was successful or succeeded “against all odds” means that he succeeded in very difficult circumstances, in a very difficult situation. No one thought he was going to be successful because it was likely or probable the odds were that he would not be successful, but “against all odds” he succeeded. That would be another use of that word “odds.”
You can specify or give the actual mathematical or “statistical odds” of something happening. You will sometimes hear people say, “The odds are five to one that this team will win the next game.” And in many places you can actually go and give money to someone, place what we call a “bet” (bet) that something, someone, some team will win or not win. That ratio of “five to one” is called “the odds.”
There is one other expression with “odds,” which is “at odds.” If you are “at odds with” another person, you disagree with another person. “My boss and I are at odds with each other.” We don’t agree about something.
Finally, Behmaz (Behmaz) in Iran wants to know the meaning of the expression “a has-been.” A “has (has) – been (been)” is a person who was once popular or successful but is no longer popular or successful. You can think of a famous singer perhaps from 20 years ago who everyone loved and who was very popular, but now no one listens to his music. He’s not popular anymore. He’s a “has-been” – someone who was once good at something or once popular but is no longer good at that thing or no longer popular.
There isn’t a common expression in English for the opposite of that, or for someone who perhaps might be popular in the future. We don’t really say he’s a “will-be,” although someone might write that as a way of contrasting with the idea of a has-been, but the expression that you will hear most of the time is “a has-been” to describe a person who is no longer successful or popular.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2016 by the Center for Educational Development.
Glossary
preacher – a person who gives speeches in churches or other public places about religion
* On Sunday morning, the preacher stood in front of the people in church and talked about the importance of being kind to one another.
strict – having many rules and requiring others to obey or follow them without exception
* The school has strict rules about students using drugs, and any student found using drugs is immediately expelled.
to base something on – to form or develop something by using something else as a starting point
* The movie was based on the bestselling book of the same name.
sexual orientation – a person’s identity regarding which gender he or she is romantically and sexually attracted to
* As a teenager, he was confused about his sexual orientation and dated both boys and girls.
civil rights – the basic moral and social behaviors and privileges that people are given, regardless of their gender, race, or ethnicity
* Many people believe that access to good education and healthcare are basic civil rights.
high hopes – strong feelings that something good will happen or become true
* She had high hopes that she’d finish all of her work early and be able to start her weekend early.
discouraged – without hope that something good will happen; losing confidence or eagerness and enthusiasm
* After being rejected from five companies, he felt discouraged and began wondering if he would ever get a job.
ant – a small insect that lives in large groups and is known for working hard
* The ants swarmed around the tiny piece of bread that the child had dropped on the ground.
campaign song – a song used by people running for political office to promote themselves and to help people remember his or her name
* When the campaign song began playing over the speakers, everyone knew that the candidate would soon appear on stage to give a speech.
to be on the right track – to be in the process of doing something correctly and well
* I think you’re on the right track. Just remember to carefully follow the remaining instructions.
to back – to support another person’s plan or efforts; to support a candidate for public office
* Which candidates are you going to back?
opposition – the person, group, or team that one is fighting or competing against
* Part of a team’s success comes from knowing the strengths and weaknesses of the opposition.
homeless – having no place to live; having no home
* Major economic problems resulted in more homeless families in the inner city.
destitute – extremely poor and without the basic things one needs to live
* Linda has a gambling problem. As a result, she lost her house, car, and all of her money, leaving her destitute.
odds – the possibility that something will happen; the chance that one thing will happen instead of a different thing; conditions that make it difficult for something to happen
* What are the odds that our team will win for a third year in a row?
has-been – a person, such as an actor or singer, who is no longer popular or successful
* Danny thinks his career will improve soon and doesn’t consider himself a has-been.
What Insiders Know
The Baldwin Locomotive Works
The Baldwin Locomotive Works was a Pennsylvania-based company that built “railroad locomotives” (train engines). Founded in 1825, the company had a lot of success building “steam engines” (engines that operated by burning wood or coal to generate heat that would boil water and produce “steam” (water vapor) for power). However, the company was not as good at manufacturing “diesel locomotives” (locomotives powered by burning oil products), and it went out of business in 1972 when diesel locomotives had clearly “outpaced” (become more popular than; grown more quickly than) steam locomotives. “All told” (in all; in total), the company produced more than 70,000 locomotives.
Beginning in the 1850s, the company began paying its workers on a “piece rate,” paying them a “set” (fixed; not changing) amount for each piece of work that they completed. This “aligned” (matched; made the same) workers’ incentives and the company’s goals, and “efficiency and productivity” (how much, how quickly, and how well someone can do something with a set amount of resources) increased “dramatically’ (significantly), allowing the company to continue to “fulfill orders” (provide the products that people committed to buy) as “demand” (desire to buy) grew.
The company made important contributions to “the war effort” (society’s efforts to win a war) by supplying locomotives during the Civil War and World War I, but business “declined” (became less; slowed) after that as diesel engines began to “dominate” (have the most important role) the railroads.
Many Baldwin locomotives have been “preserved” (saved) and are “on display” (where things can be seen by the public) at museums and railroad “yards” (places where railroad trains are kept) around the country, including the Smithsonian Institution in Washington, DC.