= 1848
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 543.
This is English as a Second Language Podcast’s English Café episode 543. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit ESLPod.com. Download the Learning Guide for this episode and follow along with the transcript of everything we say. You can also take a look at our ESL Podcast Store, with additional courses in Business and Daily English.
On this Café, we’re going to talk about the Jason Bourne films. We’re also going to talk about the American president who came after Abraham Lincoln, Andrew Johnson. And as always, we’ll answer a few of your questions. Let’s get started.
In the summer of 2002, a new action film hit theaters. “To hit” here means to be released or to open in movie theaters. The film was called The Bourne Identity, and it was based on a book that had been published 22 years earlier by a well-known American author, Robert Ludlum, called The Bourne Identity – the same name, although the story is slightly different in the original movie.
The film The Bourne Identity tells the story of a man named Jason Bourne who wakes up and cannot remember who he is. I should mention that “identity” (identity) refers to the qualities and characteristics that make a person who he is. Well, Jason Bourne has something called “amnesia” and he can’t remember who he is. “Amnesia” (amnesia) is when you lose your memory, when you can’t remember anything about yourself. Usually amnesia is a result of some injury to the brain.
Jason has been shot and left to die in the ocean but was saved by a group of fishermen on a boat. Once he gets back on land, Jason Bourne must find out who he is, where he came from, and why – more importantly – someone shot him. As he tries to learn about his past, he realizes that he is in danger again and is being followed.
When we say someone is “being followed,” we mean there is at least one other person who is going behind you or following after you, going wherever you go but not indicating, usually, that he is watching you or going the same place as you’re going. This happens all the time in the movies, of course. People are followed by the police and by private detectives, or by bad guys – bad people.
Jason Bourne is being followed, and he discovers, as he realizes he is in danger, that he has all these very special skills that he didn’t realize he had. He can fight very well and he can speak many languages. But he wants to know how he learned these things and who is following him. With the help of a German woman named Marie, Bourne tries to understand his real identity and who made him the way he is. The story is what we would call a “thriller.” It’s a very exciting movie. You never know what’s going to happen next but you want to find out.
The Bourne Identity was a very successful movie, and it launched what we would call a “movie franchise” – a whole series of movies that were based loosely on the books by Robert Ludlum. Interestingly enough, my sister used to read these books in the early 1980s when they were first published and I remember them. So, when the movie came out, I recognized, more or less, the story of this mysterious person Jason Bourne, who apparently worked for the U.S. government.
The Bourne Identity and the movies that followed were much more successful than the books. The movie made over $214 million worldwide when it was released in 2002. Audiences loved the action scenes and story. They were interested in this troubled character of Jason Bourne. Personally, I loved the movie when it came out and I’ve seen it several times because they show it on TV all the time.
I say that Jason Bourne was “troubled” (troubled), meaning he had a lot of problems. He had a lot of problems to worry about. He was a man who knew he had to learn who he really was. But at the same time, he was worried that he might not like what he found out. The actor Matt Damon played the role of Jason Bourne. Damon was already a popular movie actor by 2002, but the Jason Bourne character made him much more popular. He became a worldwide star. The film also starred another actress, by the name of Julia Styles, who had also starred in some other movies prior to this.
The Bourne Identity was so popular that they made two more Bourne movies. The Bourne Supremacy in 2004 was released and was also amazingly successful, making $289 million when it was in the theaters – that is, when it was being shown. The title The Bourne Supremacy refers to the quality of having more power or authority than anyone else. The word “supremacy” (supremacy) comes from the word “supreme,” meaning highest. Here in the U.S., we have the Supreme Court of the United States. That is the highest legal body.
In the film, Bourne continues on his journey to learn about his true past. We are introduced to a new character in The Bourne Supremacy, Pamela Landry, who is played by the very excellent actress Joan Allen. It took three more years for the movie studio to make another Bourne movie. The Bourne Ultimatum was released in 2007. An “ultimatum” (ultimatum) is a demand or a final decision that will either end in agreement or the complete end of a relationship.
The Bourne Ultimatum takes us to the final part of Jason Bourne’s story. The movie takes place in seven different countries and made even more money than the previous two movies. It made $443 million. It also won three Academy Awards, or what we call “Oscars.” Two of those were for editing and for sound. After the three Jason Bourne movies, people continued to be interested in the story, and in 2008 they created a video game called “The Bourne Conspiracy” for PlayStation. A “conspiracy” (conspiracy) is a secret plan made by two or more people to do something that is either harmful or illegal.
Because people were so interested in the Bourne story, the movie studios had to make another movie, and in 2012 they released The Bourne Legacy. This movie does not star Matt Damon, but is about the story of another man similar to Jason Bourne. He was also, however, very popular with audiences, and once again the movie studio knew that people wanted to see more of these Jason Bourne movies even if Matt Damon, the original actor, wasn’t in the movie.
There have been rumors that Matt Damon might in fact return for a fourth Jason Bourne movie, but as I record this in early 2016, it’s still just a rumor – a story or piece of information that people have talked about but has not proven to be true. There are some people who say that Jeff McQuillan might be in the fourth Jason Bourne movie, playing, of course, a younger Jason Bourne – but once again, it’s just a rumor.
Our second topic today is our 17th president of the United States, Andrew Johnson. Andrew Johnson was born in 1808 in the state of North Carolina, which is on the eastern coast of the United States, in the southern part of the U.S. Johnson’s father died when he was only three years old and left the family poor. His mother had to earn a living to try and support the family – that is, to get enough money to feed her family.
For this reason, Johnson grew up very poor. He was unable to go to school, and instead learned to become a “tailor” (tailor). A tailor is a person who makes and repairs clothing. He started working as a tailor when he was only 14 years old. Because he didn’t go to school, he had to teach himself how to read and write, which he did. Later, when he was 17 years old, he opened his own business – a tailor shop or store in Greenville, Tennessee, which is about 430 miles southwest of Washington, D.C., in the state of Tennessee, of course.
He married a young woman by the name of Eliza McCardle, and McCardle helped Johnson become a better reader. One of the things that Johnson did in order to improve his own education is he had someone read to him while he was working. Nowadays we have audio books. Well, Johnson had his own audio reader who would read to him the famous speeches of that era, of that time, and from those speeches Johnson learned a great deal of history.
He also had a friend of his read him the Constitution of the United States. He read to him so many times that Johnson memorized the Constitution, and it gave him a real interest in politics. After he got married, his wife, who knew how to read and write better than Johnson, improved Johnson’s reading and writing as well as his math skills – remembering, of course, that Johnson never went to school.
He got interested in politics as a way of protecting the poor community of Greenville since he himself was poor at one time. He decided to get involved in government, and at the age of 21, he was elected mayor of Greenville, Tennessee. A “mayor” (mayor) is the top elected official of a city – the leader of a city, we might say.
Six years later, Johnson was again elected, this time to the state legislature – the law-making part of the government of the state of Tennessee. He went on to become a member of the United States Congress, both in the House of Representatives and later in the Senate. Before becoming a senator, however, he was elected governor of Tennessee in 1853. The “governor” is the leader of the individual state.
As you probably know, during the 1850s, the United States was trying to deal with the difficult issue of slavery. Johnson was a member of the Democratic Party, one of the two major political parties during this period. The other major political party was a new one called the Republican Party. The leader of the Republican Party during the late 1850s was Abraham Lincoln. Lincoln was a Republican.
Johnson was a Democrat, and like most Democrats, he was in support of slavery. He wasn’t against slavery, especially in the Southern states. However, everything changed for Johnson when, in 1861, some of the Southern states decided that they were going to secede from the United States. “To secede” (secede) means to separate yourself from the country to which you belong and create, in effect, another country.
The Southern states of the United States, what are technically the southeastern states now of the United States, decided to secede from the Union – that is, from the rest of the United States, from the Northern states. This caused a major constitutional crisis. Almost all of the Democrats in the South, however, supported the secession of the Southern states, all but Andrew Johnson.
Johnson had been elected to the U.S. Senate in 1856, and he disagreed with the other Democrats. He disagreed about the constitutionality of this act. “Constitutionality” refers to whether something is in agreement with the laws that are stated in the U.S. Constitution, which is our highest government document, our highest law. Remember, Johnson was a great lover of the Constitution, better than anyone.
Johnson stayed in the Senate and was eventually appointed as the military governor of the state of Tennessee after the Northern army was able to take control of the state again. He supported Abraham Lincoln, which is quite unusual because Lincoln, remember, was a Republican, an anti-slavery Republican, and Johnson originally was a pro-slavery Democrat. Because Abraham Lincoln wanted to get more support for the Republican Party, and knowing that eventually the North would win the Civil War, he asked Johnson to be his vice-presidential candidate in the election of 1864.
Johnson and Lincoln won their election and Johnson became the new vice president. However, things didn’t start our very well with Johnson. The day that he officially took office – we call that day the “inauguration” – Johnson had a little bit too much to drink because he was trying to get over the effects of a cold. And so when he actually got up and gave a speech, apparently it didn’t go very well and many people thought that he was a drunk.
He was not well loved by many of the Republicans because he was a Democrat, after all, and they were not very happy to see him as the vice president. Only five weeks after Lincoln began his second term of office, his second four years, he was assassinated. He was killed on April 14, 1865, and on that day, Andrew Johnson became our 17th president.
Even though he had not supported the Southern states during the Civil War, Johnson wanted the Southern states to be readmitted to the Union – to return to the United States and not to be overly punished. The Republicans, especially a group from the Republican Party known as the Radical Republicans, disagreed with Johnson’s approach. They wanted the Southern states not only to be punished, but they wanted to give blacks – African Americans – rights that they did not have before the Civil War. In fact, they wanted to give them rights that they didn’t even have in the Northern states.
Now, it’s important to remember that the Northern politicians, although they were against slavery, were not pro-African American in the sense that they wanted African Americans in their own states or in their own cities. There was a lot of discrimination against blacks in the Northern states as well, but since almost all African Americans lived in the Southern states, it was rather easy for them politically to say that they wanted equal rights for African Americans in the Southern states, knowing that this wouldn’t really affect their own states.
Nevertheless, the Republican Party did not get along with Andrew Johnson during this period, which is sometimes called “Reconstruction.” The period after the Civil War in U.S. history is called “Reconstruction” because the country was putting itself back together again, and in particular the Southern states, who had lost the Civil War and who had suffered more damage than any other area of the United States, needed to be reconstructed, to be rebuilt.
The Congress disagreed with Johnson so much that they decided to pass some laws that would give civil rights – that will give voting rights, among other things – to African Americans, that Johnson didn’t want to give. Johnson then decided to veto the law. “To veto” (veto) means to say no to something. The president of the United States can say no to laws that the Congress passes. Now, Congress can, if it has two-thirds of the members of Congress agreeing, override a veto.
“To override” (override) means to say even though the president says no to this proposal, this bill, this bill or proposal will become a law if two-thirds of Congress vote for it to become a law. That’s called “overriding a veto.” It’s part of a system of government we have in the United States called “checks and balances,” where the different parts of government, the three major parts of government, each have a certain amount of power over the other. And if one gets too powerful, the other can override it, can use its own power to reduce the power of another part of government.
It often happens in U.S. history that one part of the government becomes stronger than the other, and there’s always this tension, this political battle among the three major parts or what we call “branches” of government in the U.S. Because the Republicans in Congress disagreed with Johnson, and because they had so many more votes than Johnson, they decided to not only override his veto but introduce a series of changes to the Constitution that would put into law their ideas about how the country should be reconstructed.
This included, most importantly, the 14th Amendment to the Constitution, which said that anyone who was born in the United States was a citizen – a person who legally belonged to this country and had the rights and protections of this country. The 14th Amendment also guaranteed what is called “due (due) process,” where everyone had to be treated fairly before the law.
Previously, this Congress had passed the 13th Amendment, which had changed the Constitution’s formula for the U.S. House of Representatives. It later, after Johnson left office, passed a 15th Amendment, which gave everyone the right to vote. Well, every man the right to vote, black or white.
Johnson made so many enemies in Congress that Congress decided to do something it had never done before. It decided to get rid of the president. Now, there is a way in our Constitution to get rid of the president. It requires two things. First, it requires that one part of our Congress, called the House of Representatives, impeach the president. “To impeach” (impeach) means to accuse a public official – in this case, the president – of doing something wrong.
If the House of Representatives impeaches the president or other elected official, then the case, if you will, goes to the U.S. Senate. The Senate then has an official trial, just as you would in front of a judge except the members of the Senate vote whether the person is guilty or not, and if they vote the person is guilty, the person is removed from office.
Johnson was, in fact, the first president to be impeached by the U.S. House of Representatives. However, the U.S. Senate did not vote to remove him from office. He won by only one vote. If one more person voted, Johnson would have been removed from office. So, Johnson was successful, we might say, however he was never again to be a successful president.
He returned to his home state of Tennessee after he finished his four years in office and he tried to rebuild his reputation; he tried to rebuild the opinion that other people had about him. However, he wasn’t very successful, although in 1875 he did get elected to the Senate, but he died in July of that year, just before he was to have started again as the senator from Tennessee.
Johnson never did rebuild his reputation and nowadays is considered something of a failed president who tried to protect his vision of the Constitution but failed. By the way, there was one other president who was impeached by the U.S. House of Representatives, and that was William Jefferson Clinton. And like Johnson, Clinton was not found guilty by the U.S. Senate and remained president, although a much more successful president than Andrew Johnson.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Sergey (Sergey), originally from Russia, now living somewhere here in California. And he has a very good question for a person living in California. He wants to know the meanings of the words “shiver,” “trouble,” “quiver,” and most importantly, “shake.” All of these words refer to something that moves or movement.
Let’s start with the word “shiver” (shiver). A person who “shivers” is someone who is very cold, usually, whose body is beginning to move involuntarily – even though you don’t want it to move, it begins to move because you are so cold. It’s the way your body reacts to the cold. It starts to move because of the cold. You can also shiver if you are very afraid, if you are very scared of something. Your arms or your hands might begin to move involuntarily.
“To tremble” (tremble) is similar to shivering but it is when you are afraid or nervous or excited. You could tremble because you are so excited. You move your hands or your arms very quickly back and forth in a small movement because you are excited or because you’re nervous or, once again, because you are afraid. So you could shiver from being afraid or you could tremble from being afraid. But you can also tremble from being nervous or excited, whereas “shiver” would only be if you are afraid or if you are cold.
There’s one more important use of “tremble,” and that refers to the ground, to the earth. You could talk about the earth “trembling.” The earth would tremble during something called an “earthquake.” And here in California, we have lots of earthquakes, especially in southern California, but all throughout the state there are earthquakes where the earth suddenly starts to move, and houses move, and buildings move, and cars move as the ground moves underneath. That could also be another use of the verb “to tremble.” “The earth trembled.”
“To quiver” (quiver) can mean the same as “to tremble.” A person could “quiver” in fear or another strong emotion, but you could also make a thing quiver, or you could describe, say, the branches of a tree, the smaller parts of the tree, as “quivering” – moving rapidly back and forth.
While you will hear “shiver,” “tremble,” and “quiver” in conversational English sometimes, the most common verb is “to shake” (shake). “To shake” can mean to move yourself or move another person, or perhaps for a thing to move. Shaking involves a back and forth quick movement. You could shake from the cold. You could shake from fear. The earth could shake. A branch could shake. You could shake someone else by grabbing onto them – moving them back and forth. You shouldn’t do that. That’s a dangerous thing, especially for a child.
But we often shake objects, for example. You may decide to shake a bottle of medicine before opening it up to make sure that all of the ingredients are mixed together – the contents are mixed together well. There was a terrible song back in the ’70s called “Shake Your Booty” (booty). “Booty” is a slang word for your butt. “To shake your booty” meant to dance by moving your body back and forth. I will not shake my booty here on the Café, thank you very much.
Our next question comes from Liette – I’m probably mispronouncing that (Liette) – from an unknown country. The question has to do with the expression “at-risk students.” “What does it mean to be at (at) – risk (risk)”? “At-risk” means that you are in danger of something bad happening.
In some American schools, they use the term “at-risk” to describe students who are not doing very well or perhaps come from a family situation that may give them problems in succeeding in school. Perhaps they don’t have the same preparation as other students, or perhaps they don’t have the same resources available to them in order to succeed or be successful in school. We might describe students as being “at-risk” and needing extra help because if they don’t get extra help, they may fail at school.
Finally, Rustan (Rustan) in Uzbekistan – we don’t get too many questions from Uzbekistan. What’s up, Uzbekistan? How’s it going over there? Can you hear me? Well, you don’t ask very many questions, but now you have one. We’ve probably had one before, maybe. Anyway, the question has to do how we pronounce numbers that are decimal fractions.
Now, a “decimal” is a point or a dot that goes after a number, and the numbers after that tell you what fraction or percentage of something that that number is. So, we have for example “one half,” which would be represented by “0.5.” How do we pronounce that? Well, I just did: 0.5. We use the word “point” to describe that little dot on a piece of paper or on your computer that separates the numbers before and after the decimal. 2.34, for example, would be the same as 2 and the fraction 34/100. 34.75 would be the same as 34 and 75/100 (or you can use the fraction 3/4).
So, decimal fractions are pronounced by using the word “point” to stand for the decimal. Normally we would read the numbers out after the decimal point. You could say “2.34,” but it would be more common to say “two point three four.” You would say 1,000,735.736. You wouldn’t say “point seven thirty-six” or “seven thirty-six.” You pronounce each number: “seven, three, six.” That’s normally the way it’s done after a decimal point. If the fraction was 1/10 it would be .1 or .10 – “point one O,” we might say.
It depends on the speaker. Some people use “O” and some people use “zero” when pronouncing numbers – either one is correct. You could pick, say, “1.035,” or you could say, “one point O three five.” Both pronunciations of zero are correct. Notice, however, if we are talking about the number in isolation, the number 0, we don’t say “the number O.” We say “zero.”
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California – sorry this has run so long – I’m Jeff McQuillan. Thank you for listening, if you are still listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational Development.
Glossary
identity – the qualities and characteristics that make a person who he or she is
* Being strong and athletic was an important part of his identity, so it was very difficult for Max not to be able to play sports after his accident.
amnesia – a loss of memory, usually due to some kind of brain injury
* Jean Pierre hit his head in the car accident and had a mild case of amnesia that lasted three days.
troubled – having many problems on one’s mind; being worried about one’s difficulties
* He was a troubled young man who began using drugs as a way of forgetting his difficult homelife.
supremacy – having more power or authority than anyone else; being the best, most, highest, or greatest in some activity or contest
* In the late 1800s and early 1900s, the British Empire had supremacy over many countries and regions around the world.
ultimatum – a demand for a final decision that will result either in agreement or complete destruction of a relationship
* The girl’s mother presented an ultimatum: Clean up her room or not be allowed to go out to the movies later with her friends.
rumor – a story or piece of information that is passed from one person to another without evidence that it is true
* The gossip magazine reported that the actress was pregnant with the child of her husband’s best friend, but that was just a rumor.
tailor – a person whose job is to make and repair clothing designed for a specific person
* The woman needed her dress shortened so she took it to a tailor who was able to make the length adjustment.
to secede – to separate from a nation or state and become an independent nation or region
* In 2011, South Sudan seceded from Sudan to become a new and independent nation in Africa.
to veto – for a person in power to decide against allowing something, usually used to prevent a new law from being made
* The children all wanted French fries with dinner, but their parents vetoed the idea and prepared salads instead.
citizen – a person who legally belongs to a country and who has the rights and protections of that country
* American citizens are able to get U.S. passports, allowing them to travel to many countries without a visa.
to impeach – to accuse a public official of committing a crime while in office, usually intended to remove him or her from the job
* President Bill Clinton was impeached in 1998 for perjury, or lying to the judge.
reputation – the opinion that others have about someone or something
* He had a reputation for being an honest businessman, which is why so many people recommended him to their friends.
to shiver – to shake slightly because one is cold or afraid
* Standing outside on a cold night makes me shiver from head to toe.
to tremble – to shake slightly because one is afraid, nervous, or excited
* The students knew they were in trouble when they were called to the principal’s office and trembled in fear as they waited outside her office.
to quiver – for something to shake or move slightly with a rapid motion
* Look closely. You can see the quivering of a bird’s wings as it prepares to fly.
to shake – to move oneself, another person, or something, perhaps violently, back and forth or up and down with short, quick movements
* Leaving the beach, I stopped to shake the sand out of my shoes.
at-risk student – a student who may be at risk of failing and requires additional supervision or help to succeed in school
* Our school gives counseling and tutoring services to at-risk students who have emotional or behavioral problems and/or who have poor grades.
What Insiders Know
Get Smart
Get Smart is a U.S. television series that “satirizes” (makes fun of) the “genre” (type of film, TV show, or book) of “secret agents” (spies; people who secretly work for the government to find out information about other governments). The “comedy” (a show that makes people laugh) was “on air” (shown) from 1965 to 1970, with 138 episodes.
The co-creator, Mel Brooks, once described the show as “an ‘insane’ (crazy) combination of James Bond and Mel Brooks comedy." It “follows the story of” (shows the experiences of) a “bumbling” (clumsy and awkward) special agent named Maxwell Smart, also called Agent 86. He and his female partner, known only as Agent 99, work for a secret U.S. “intelligence” (with the responsibility of discovering secret information) agency. They make a lot of mistakes, but “in the end” (by the end of the show or story), they always “save the day” (become heroes by finding a solution).
The show uses many “gags” (funny, memorable things), such as phones that are “concealed” (hidden) in unusual places. Agent 86 places secret calls, holding a shoe up to his ear because there is a phone in the “under sole” (the inside, bottom part of a shoe). Other phones are concealed in a “necktie” (a piece of long fabric worn around a man’s neck in formal wear), a “comb” (small tools used to straighten and untangle hair), a watch, a clock, a “compact” (a small mirror held in the hand used for applying makeup), and even Agent 99’s fingernail.
The show “inspired” (was the reason for the creation of) three films: The “Nude” (Naked) Bomb (1980), Get Smart, Again!(1989), and Get Smart (2008). It also had a big “impact” (influence; effect) on “pop culture” (popular culture) when people “adopted” (began to use) the show’s “catchphrases” (phrases repeated many times), such as “Sorry about that, Chief,” and “I asked you not to tell me that.”