= 1839
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 534.
This is English as a Second Language Podcast’s English Café episode 534. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. You know that song? Me neither.
Visit our website at ESLPod.com. Download a Learning Guide for this episode right after you become a member of ESL Podcast. Our Learning Guides include complete transcripts of everything we say plus a complete glossary with vocabulary words, definitions, sample sentences, and a whole lot more. Go also to our Facebook page at facebook.com/eslpod and like us. Why? Because we like you.
On this Café, we’re going to talk about a famous American painter, James Whistler. We’re also going to talk about one of the most well-known American songs, “Moon River” – one of my favorites. And as always, we’ll answer a few of your questions. Let’s get started.
James McNeill Whistler was born in the United States, but actually spent most of his life in Europe where he became really famous, more famous than he was in the United States during his lifetime. He was born in 1834 in Lowell, Massachusetts. Massachusetts is a state on the East Coast of the United States, in what we call the northeastern part or New England area of the U.S.
As a child, James Whistler and his family lived in other countries. They lived in Russia for a while. They lived in England for a while, mostly because his father’s work required them to move. His father was an engineer and he worked on railroads. Railroads were, of course, becoming very popular during the nineteenth century, and his father went around designing and helping to build these railroads.
The family moved back to the United States in 1849 after Whistler’s father died. James Whistler joined the army and went to the U.S. Military Academy at West Point, New York. Usually we refer to this military school as simply “West Point.” It’s the place where all of the army officers typically go.
Unfortunately, Whistler was not a very good student. He had always been interested in art, and so he didn’t do very well in his military classes or in some of the other classes, such as science. He also had difficulty following the typically strict military lifestyle. “Strict” (strict) means having many rules that must be followed and followed very carefully. Whistler eventually left the academy, left West Point, in 1854 and moved to Paris to study art.
Whistler loved Paris, as have many artists throughout the years. He studied painting and made friends with other artists. He also began living what could be described as a “Bohemian lifestyle.” A “lifestyle” describes the way in which someone lives – the things that one does, the manners and morals that one has. Whistler’s lifestyle was very much a “Bohemian” one.
“Bohemian” (bohemian) lifestyles refer to ways of living that don’t follow traditional rules of society. It may involve doing things that other people would not traditionally do. It may refer to the way you dress, the way you act, the kinds of things you do to make money – all of these might be part of a different lifestyle. The Bohemian lifestyle was popular during the time that Whistler lived in Paris.
Beginning in the 1860s, Whistler began to spend time both in Paris and in England. He also spent a lot of time on the coast of France, the part of France near the ocean, in particular the area of Brittany. In 1863, Whistler moved to London. The year 1863, you may recall, was during the middle of the U.S. Civil War. Here we have Whistler, who studied at the military academy, not participating in the war at all but spending his time in Europe. In any case, he went to London and began becoming an artist there – or better yet, continuing his career as an artist.
He continued painting but also began doing etchings. An “etching” (etching) is a picture that is made from a piece of metal that has a picture carved into it. You take that metal and you put ink on it and then you put it against a piece of paper. At least, that’s what I think it is. Whistler began producing these etchings that became very popular, and he became well known in London for his art. He would often do etchings of the River Thames, which is the main river that goes through the city of London.
In addition to his etchings, Whistler continued to paint. One of his paintings – which had the name of “Symphony in White, No. 1,” although it was also called “The White Girl” – was put into a famous art show in Paris in 1863. A “symphony” (symphony) is a long piece of music, usually written for an orchestra, that typically has four parts or what are called four “movements” in English. The painting by Whistler was, of course, not music but a piece of art you looked at, but he used the word “symphony.” Whistler continued to be popular in Europe, but again, not as well known here in the United States.
In the 1870s, Whistler began adding certain styles of painting that he took from Japanese painting. He used this particular style of painting and people began to notice. His work really began to stand out in terms of its style. “To stand out” means to be different, to be noticeable. You can see the addition of Japanese painting styles in Whistler’s work in a series of paintings he did of London at night called “The London Nocturnes.”
Once again, Whistler used a musical term to give a title to his paintings. A “nocturne” (nocturne) is a piece of classical music that is usually written in something of, I guess we would call, a dreamy, perhaps slightly dark style. It was associated with romantic music. We think for example of the famous nocturnes of Chopin.
Whistler began painting portraits at this time as well. His most famous portrait, the portrait that is still his most famous painting here in the U.S., was called “Arrangement in Grey and Black, No. 1.” The other name given to the painting was “The Artist’s Mother,” although it eventually became known by the name that most Americans know it by, which is simply, not “The Artist’s Mother,” but “Whistler’s Mother.”
A “portrait,” you probably know, is a painting or a photograph that shows a person’s face and sometimes the upper part of the person’s body. Sometimes it shows the entire body. This particular painting, “Arrangement in Grey and Black, No. 1,” shows Whistler’s mother sitting in a chair, and it is done, not surprisingly, in grey, black, and white. Whistler did another painting with a similar title called “Arrangement in Grey and Black, No. 2.” This one was not of his mother, but rather of a famous Scottish philosopher and historian by the name of Thomas Carlyle.
Today you can see “Whistler’s Mother” (or “Arrangement in Grey and Black, No. 1: The Artist’s Mother”) not in an American museum, but in a museum in Paris – the Musée d’Orsay (my apologies for my bad French). It’s interesting because many Americans who go to Paris will go to this museum – which, by the way, is a wonderful museum. The Louvre in Paris is amazing, but one of my favorite museums in Paris, at least the one time I’ve been there, was this particular museum.
Many Americans will go and they will look at this painting, and it has a certain connection to them because it’s the one painting of Whistler that they really know. The irony here, the odd thing here, is that of course Whistler was by most definitions much more European than he was American, and yet Americans – because they know this painting and because Whistler himself was an American – feel a certain connection to it.
Whistler, although he was a successful artist, did not make a lot of money. He loved to have parties. He was very popular with other artists, and perhaps he spent a little bit too much money. In 1879, he was so poor that he had to declare bankruptcy. “To declare bankruptcy” (bankruptcy) means to say that you don’t have enough money to pay your debts – the money that you owe to other people. This is a way of legally protecting yourself. You’re saying to the people to whom you owe money, “I’m sorry. I don’t have any money anymore.” That’s what Whistler did.
Well, he wasn’t poor, exactly. He did later move to Venice, but eventually moved back to London in 1880. His most productive period as a painter, however, had ended by this time. By “productive” (productive), I mean the period in which he was painting the most. His style of painting with colors like blue, grey, and white was not as popular anymore. People got more interested in, well, more colorful paintings – the kind of painting that was becoming popular among, say, the Impressionists and other styles of painting popular in the late nineteenth century.
Whistler was well known not only in the art scene in Europe, but also among writers and other intellectuals. He was well known for having a certain friendship with Oscar Wilde, the famous British writer who was considered one of the cleverest, funniest writers of his generation. Whistler and Wilde would often exchange what were called “witticisms,” which would be simply clever sentences or sayings. Some people say that Wilde actually used some of the things that Whistler said to him in his own conversations with other people.
In 1888, Whistler finally married, after many years of not being married. He married a woman by the name of Beatrix Godwin and the two of them moved to Paris. They continued to have their parties and be popular with a group of artists living there at that time. Beatrix died only a few years later in 1896, and it was said that Whistler never really recovered from her death, from the sadness of her death. He moved back to London and himself died in 1903 at the age of 69.
Despite being an American artist, it’s no surprise, now that we know his story, that most of Whistler’s paintings and etchings are not in the United States but in Europe. They are hung in famous museums such as the Tate Modern and the British National Collection in London, and of course in the Musée d’Orsay in Paris. Some of his work has returned, if you will, to the United States. You can see some of it at the greatest museum in the U.S., the Metropolitan Museum of Art in New York.
We turn now to our second topic, which is the famous song “Moon River.” “Moon River” was written by one of the most popular American composers of music, Henry Mancini. It was co-written by Johnny Mercer. The song was written in 1961 for a very famous movie, Breakfast at Tiffany’s. Henry Mancini wrote the music and Mercer wrote the words. Mancini wrote the music for many popular movies during this period.
The song was written especially for the star of Breakfast at Tiffany’s, which if you are a fan of old movies you will know was the wonderful, beautiful Audrey Hepburn. Hepburn, however, was not a great singer. So Mancini had to write a song that she would be able to sing well. He did, and the song became so popular and well liked that it won the Academy Award for Best Original Song in 1961. The Academy Award is the same as the Oscars. It is the award that is given to the best movies, directors, and songs of that year.
“Moon River” is a very short song. It was, according to the writer of the lyrics of the song, the words of the song, Johnny Mercer, inspired by a moon shining on a river near the place where Mercer grew up in Savannah, Georgia. Georgia is located in the southeast part of the United States. When I say a moon was “shining” on the river, I mean you could look into the river and see the reflection of the moon, the image of the moon, in the river.
The song, as I say, is quite short and – should I sing it? Should I? You think? Yeah? Okay, I will. Everybody here thinks I should. Of course, I’m the only one here. Anyway, here it goes . . .
Moon River, wider than a mile,
I’m crossing you in style some day.
Oh, dream maker, you heartbreaker,
wherever you’re going I’m going your way.
That’s the first verse of the song – the first part of the song. “Moon River,” as I mentioned earlier, refers to the river with the moon reflecting in it. You can see an image of the moon in the river. The song goes on to talk about how the singer promises to visit the river again someday. He says, “Moon River, wider than a mile. I’m crossing you in style someday.” “To cross a river” means to go from one side of the river to the other. So, he’s promising to cross the river again “in style.”
To do something “in style” (style) means to do it in such a way that you have a certain class. You do it in a way that is appealing – to do it in perhaps the very best or even most expensive possible way. If someone says, “I’m going to fly to the United States in style,” he may be referring to flying first class – the most expensive seat on the airplane. That would be to do something “in style” – in great comfort, perhaps even with great expense. This person in the song is going to cross Moon River again “in style someday.”
The singer then is talking to this river, Moon River, and saying, “Oh dream maker, you heartbreaker.” Someone or something that “makes dreams” would be a person or a thing who brings something wonderful to your life, perhaps, or a thing or a person who can give you your dreams, who can make real your dreams. A “heartbreaker” (heartbreaker) is in some ways the opposite of a dream maker. If someone breaks your heart, someone makes you very sad, usually because that person doesn’t love you the way you love him or her.
A heartbreaker is a person who perhaps is so beautiful that everyone falls in love with him or her, and therefore breaks a lot of hearts, disappoints a lot of people, because he or she can only love so many people. I have never been a heartbreaker, but we might describe a very handsome man, for example, a very good-looking man as being a heartbreaker, or a very beautiful woman, since many people will fall in love with that person. The singer of the song is saying that the river is a heartbreaker.
Nevertheless, he says, or she says, “Wherever you’re going, I’m going your way,” meaning I’m going to follow you nevertheless, even though you are a heartbreaker. The next part of the song talks about “two drifters off to see the world.” A “drifter” (drifter) is someone who travels around without a specific destination. A drifter doesn’t have a particular place he wants to go.
Often we use the word “drifter” to mean a person who doesn’t have a permanent home – perhaps a poor person who can’t afford a home, who is going from town to town, moving around, perhaps sleeping in a park, or someone who is otherwise homeless. But here, the word simply means a person who doesn’t have a destination, a specific place to go.
Oddly, the second verse of the song is really about how the Moon River and the singer of the song are similar in that they are seeking or trying to get the same thing. It talks about how the singer and the river are “after the same rainbow’s end.” The “rainbow’s end” here is a poetic way of describing the goal, but really something wonderful, something amazing. The old story, the old belief, is that at the end of a rainbow, there is a “pot (pot) of gold,” a big container of gold. A “rainbow” (rainbow) is a half-circle of different colors that appears in the sky sometimes after it rains.
So, the song is about how both the singer and Moon River are after the same goal. The song is slow and really kind of sad. It’s about people who are looking for something or perhaps trying to get something back that they lost and will never be able to get again. “Moon River” was a very popular song when it was released in 1961. The most popular version of the song is by a famous American singer that I remember hearing growing up, by the name of Andy Williams. In fact, I think he even had a television show on for a brief period of time.
It was popular for some reason in the late ’60s, early ’70s for famous singers to have their own television shows. The Smothers Brothers were singers, and Sonny and Cher were singers, Tony Orlando and Dawn was a group of singers, and all of them had their own television show. It was very strange. It was a weird time, the 1970s, for those of you too young to remember – well, a weird time in American television, let’s put it that way.
But no American is too young to remember the song “Moon River,” since it is still popular. And Andy Williams’ version is probably the most popular of them all.
Now let’s answer a few of the questions you have sent to us.
Our first question comes from Samuel (Samuel) in the mystery country called “Mystery” – Mystery, the country. Sounds like the name of a movie. Anyway, Samuel says he wants to know the difference between “to bungle” (bungle) and “to blunder” (blunder). The two words have related, similar meanings.
“To bungle” something is to make a lot of mistakes when you are trying to do something, to do something very poorly, or to be very unsuccessful at a certain task. If your boss gives you a project and you make all sorts of mistakes and you don’t do it correctly, she may say to you, “You’ve bungled this project. You’re fired. Get out of here. You’re no longer working here.” Well, I hope she doesn’t say that, but she could if you bungle everything she gives you.
“To blunder” means to try to do something without sufficient knowledge or without really understanding something, and because of that, you make a lot of stupid mistakes. So, “bungling” means to do something poorly, even if you know how to do it. “To blunder” means to do something poorly without really understanding it. So, you didn’t have sufficient knowledge or perhaps you were just too dumb, too stupid, to understand how to do it correctly. It’s a slight difference.
There’s an old expression, a “blundering idiot” – someone who makes lots of mistakes because he’s not very intelligent. He’s not very smart. There’s a noun “blunder,” which describes a stupid mistake that you might make. There are also the adverb forms of these words, “bunglingly” and “blunderingly” – kind of difficult to say – which could be used to describe certain actions that had the characteristics of “bungle” and “blunder.” Although I have to say, I don’t often hear or read the adverb forms of those two words.
Mario (Mario) – maybe related to Super Mario, I’m not sure – Mario from Brazil wants to know the meaning of the word “comparable.” “Comparable” (comparable) comes from the verb “to compare” (compare). “To compare” two things means to look at them and see the similarities between them, the things that are similar – or you could compare three things and look at the things that are similar. There’s another verb, “contrast” (contrast). “To contrast” two or more things means to look at the differences.
In everyday conversational English, however, people will often use “compare” and “contrast” basically to mean the same thing. They may use “compare” to talk about similarities and differences, or “contrast” to do the same thing. “Comparable,” however, means that two different things or two or more things are very similar. We might talk about “comparable hotels” – two hotels that are similar in quality. We might talk about “comparable houses” – houses that are about the same.
In fact, when you buy or sell a house in the United States, the person who helps you do that – a “real estate agent,” we would call that person – usually goes out and finds comparable houses that you’re interested in buying or that are similar to the house you want to sell, and they often will describe these as “comps” (comps). They’re comparable houses – similar houses that will give you an idea about the price that you should either be looking to pay for a house or be willing to sell your house.
There’s another word that is somewhat similar, which is “compatible” (compatible). However, “compatible” doesn’t mean similar. “Compatible” means that two different things or two different people are able to get along together. They are similar enough, perhaps, that they can work together. If someone says, “You and I are just not compatible,” that person is telling you that our personalities – rather, your personalities or your, I don’t know, ways of thinking and talking – are not similar enough that the two of you can be together.
You want your roommate to be “compatible.” You want someone with whom you can live who is similar enough to you that you are able to be able to get along. This is different than “comparable.” “Comparable” refers to the similarities between two or more things. “Compatible” refers to the ability of two or more things to get along – to go together, perhaps.
Finally, Ann (Ann) in China wants to know what we mean – what I mean – when I spell things and say something like “uppercase” (uppercase) and “lowercase” (lowercase). What does it mean, for example, if I spell my name by saying, “Uppercase J, lowercase e, f, f?” “Uppercase” refers to what we also call, in English, a “capital letter.” It’s what we would say, to a young child, a “big letter” or a “large letter.” In the Roman alphabet that is used to spell English, to write English, there are large letters and small letters. There are uppercase letters and lowercase letters.
You will, more often hear the word “capital” in front of a word that is “uppercase,” and nothing in front of a word that is “lowercase.” In other words, the assumption, when you’re spelling a word, is that all of the letters are small, or “lowercase,” letters. You would only say “capital” when there is an exception to that. For example, “California” is spelled capital C, a, l, i, f, o, r, n, i, a. The first letter of that word is “capitalized,” or written as an uppercase letter. The rest of the letters of that word are written as lowercase, or small, letters.
My last name is spelled capital M, c, capital Q, u, i, l, l, a, n. I have a last name that has two capital letters, which is a little bit uncommon. Scottish and Irish names often have two capital letters because of the form “Mc” or “Mac” which often comes at the beginning of a name. It basically just means “son of.” That’s why in other countries you’ll see a lot of words that end in “son” (son) – “Johnson” and “Anderson.” These are the son of John and the son of Ander, I guess.
Anyway, thanks for your question, Ann, which we would spell uppercase A, lowercase n, n – or more commonly, capital A, n, n. What would we do if all of the letters were capitalized, were uppercase? We might say something like “all capital letters A, N, N,” or after the word we might say, “A, N, N – all capital letters” or “all capitalized.” You get the idea.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
This is Jeff McQuillan from Los Angeles, California. Thanks for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational Development.
Glossary
strict – requiring that rules about behavior be followed closely and without exception
* Yuko grew up in a strict home where each child had to finish her homework and do all of her chores before she could go out and play.
bohemian lifestyle – a way of living that does not follow the traditional rules of society, often adopted by artists and writers
* Henri enjoyed his bohemian lifestyle where he slept all day and stayed up all night writing music or drinking and dancing with his friends.
etching – a picture made by putting ink on a piece of metal, glass, or stone with an image carved on it and then pressing paper on top of the metal
* These etchings of lake scenes are so detailed that they look a little like photos.
symphony – a long piece of music written for an entire orchestra, often with four movements or parts
* Annette listened to her favorite recording of Beethoven’s Fifth Symphony.
to stand out – to be different and noticeable in a group
* The basketball player stands out in a crowd because he is nearly eight feet tall.
to declare bankruptcy – to legally state that one does not have enough money to pay back the money that one owes
* The company was forced to declare bankruptcy after sales dropped dramatically as a result of the company president’s unpopular words.
productive – creating or doing a lot
* It’s difficult to be productive when my neighbor is having a loud party.
to reflect – to show an image of something on the surface of something else, such as a mirror, piece of glass, or the surface of water
* The mirror reflected his tired and haggard face.
in style – doing something in an impressive or luxurious way
* The actress arrived in style in a luxury car driven by a uniformed driver.
heartbreaker – someone whom many people fall in love with, but who may be careless of other people’s feelings
* She is smart and beautiful and I hope she doesn’t become a heartbreaker when she grows up!
drifter – a person who wanders from place to place without a specific destination in mind
* After losing his job, James became a drifter and traveled the world, working a little here and there to earn enough money for food.
rainbow – a curved line of different colors that appears in the sky after it rains
* After the huge thunderstorm, a beautiful rainbow appeared in the sky.
bunglingly – doing something poorly and unsuccessfully, make many mistakes
* In her rush, she mixed the ingredients bunglingly, not measuring them properly.
blunderingly – trying to do something without knowledge or the ability to understand, making stupid or careless mistakes; moving clumsily
* The new manager made decisions blunderingly, without considering the existing information or the likely consequences.
comparable – describing two or more things as being very similar, or being of similar quality or worth
* The drugstore no longer carried the brand of vitamins Joel takes, so the clerk recommended another brand that is comparable.
compatible – able to exist together without any problems or conflicts; for two things to go together well
* This cable isn’t compatible with your type of TV. You’ll need to buy another one.
uppercase – capital letters; a letter used at the beginning of a sentence or a proper noun, such as A, B, C, rather than a, b, c
* The name of the company is spelled in uppercase letters: BYTECH.
lowercase – small letters, for example, a, b, c and not A, B, C; not capital letters
* My name is misspelled on the new business cards, with my last name all in lowercase letters.
capital letter – a letter used at the beginning of a sentence or a proper noun, such as a name
* The question “How are you?” begins with a capital letter.
What Insiders Know
Moonshine
“Moonshine” is a “colloquial” (language used by ordinary people, not formal) term for alcohol that has been produced illegally, usually by an individual or a very small group of people in a hidden, secretive way. Moonshine “got its name” (was named a particular way) from the fact that people made it at night, by the light of the moon, when they were less likely to be “caught” (discovered to be doing something wrong; arrested).
Moonshine became extremely important during Prohibition (see English Café 288), the period from 1920 to 1933 when alcohol was “banned” (not allowed; became illegal) in the United States. People who wanted to continue to drink alcohol during that time didn’t have any legal “options” (choices), so they had to “turn to” (rely on; decide to have or use) moonshine. During this time, moonshine was an important source of “income” (the money that one earns from work) for many people, especially in “rural” (in the country, not in the cities) areas.
Many rural “farmers” (people who grow crops (plants for food) and raised animals) made moonshine from their own corn. It was generally a very “strong drink” (with a lot of alcohol), but sometimes it was “contaminated” (dirty; impure) and even “poisonous” (making someone very sick or even killing someone). This was because the materials used to make the “stills” (containers and machines used for making alcohol) were sometimes “toxic” (with poisons).
For example, some people used “radiators” (the part of a car that cools the engine) to make moonshine, but these had “traces” (small amounts) of “lead” (a heavy metal that can be dangerous to people’s health) and “antifreeze” (a substance that lowers the temperature at which a liquid freezes), which are poisonous. People soon learned to burn a spoonful of the moonshine, because they thought they could determine whether it was poisonous by studying the color of the “flame” (fire).
Complete Transcript
You’re listening to ESL Podcast’s English Café number 534.
This is English as a Second Language Podcast’s English Café episode 534. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California. You know that song? Me neither.
Visit our website at ESLPod.com. Download a Learning Guide for this episode right after you become a member of ESL Podcast. Our Learning Guides include complete transcripts of everything we say plus a complete glossary with vocabulary words, definitions, sample sentences, and a whole lot more. Go also to our Facebook page at facebook.com/eslpod and like us. Why? Because we like you.
On this Café, we’re going to talk about a famous American painter, James Whistler. We’re also going to talk about one of the most well-known American songs, “Moon River” – one of my favorites. And as always, we’ll answer a few of your questions. Let’s get started.
James McNeill Whistler was born in the United States, but actually spent most of his life in Europe where he became really famous, more famous than he was in the United States during his lifetime. He was born in 1834 in Lowell, Massachusetts. Massachusetts is a state on the East Coast of the United States, in what we call the northeastern part or New England area of the U.S.
As a child, James Whistler and his family lived in other countries. They lived in Russia for a while. They lived in England for a while, mostly because his father’s work required them to move. His father was an engineer and he worked on railroads. Railroads were, of course, becoming very popular during the nineteenth century, and his father went around designing and helping to build these railroads.
The family moved back to the United States in 1849 after Whistler’s father died. James Whistler joined the army and went to the U.S. Military Academy at West Point, New York. Usually we refer to this military school as simply “West Point.” It’s the place where all of the army officers typically go.
Unfortunately, Whistler was not a very good student. He had always been interested in art, and so he didn’t do very well in his military classes or in some of the other classes, such as science. He also had difficulty following the typically strict military lifestyle. “Strict” (strict) means having many rules that must be followed and followed very carefully. Whistler eventually left the academy, left West Point, in 1854 and moved to Paris to study art.
Whistler loved Paris, as have many artists throughout the years. He studied painting and made friends with other artists. He also began living what could be described as a “Bohemian lifestyle.” A “lifestyle” describes the way in which someone lives – the things that one does, the manners and morals that one has. Whistler’s lifestyle was very much a “Bohemian” one.
“Bohemian” (bohemian) lifestyles refer to ways of living that don’t follow traditional rules of society. It may involve doing things that other people would not traditionally do. It may refer to the way you dress, the way you act, the kinds of things you do to make money – all of these might be part of a different lifestyle. The Bohemian lifestyle was popular during the time that Whistler lived in Paris.
Beginning in the 1860s, Whistler began to spend time both in Paris and in England. He also spent a lot of time on the coast of France, the part of France near the ocean, in particular the area of Brittany. In 1863, Whistler moved to London. The year 1863, you may recall, was during the middle of the U.S. Civil War. Here we have Whistler, who studied at the military academy, not participating in the war at all but spending his time in Europe. In any case, he went to London and began becoming an artist there – or better yet, continuing his career as an artist.
He continued painting but also began doing etchings. An “etching” (etching) is a picture that is made from a piece of metal that has a picture carved into it. You take that metal and you put ink on it and then you put it against a piece of paper. At least, that’s what I think it is. Whistler began producing these etchings that became very popular, and he became well known in London for his art. He would often do etchings of the River Thames, which is the main river that goes through the city of London.
In addition to his etchings, Whistler continued to paint. One of his paintings – which had the name of “Symphony in White, No. 1,” although it was also called “The White Girl” – was put into a famous art show in Paris in 1863. A “symphony” (symphony) is a long piece of music, usually written for an orchestra, that typically has four parts or what are called four “movements” in English. The painting by Whistler was, of course, not music but a piece of art you looked at, but he used the word “symphony.” Whistler continued to be popular in Europe, but again, not as well known here in the United States.
In the 1870s, Whistler began adding certain styles of painting that he took from Japanese painting. He used this particular style of painting and people began to notice. His work really began to stand out in terms of its style. “To stand out” means to be different, to be noticeable. You can see the addition of Japanese painting styles in Whistler’s work in a series of paintings he did of London at night called “The London Nocturnes.”
Once again, Whistler used a musical term to give a title to his paintings. A “nocturne” (nocturne) is a piece of classical music that is usually written in something of, I guess we would call, a dreamy, perhaps slightly dark style. It was associated with romantic music. We think for example of the famous nocturnes of Chopin.
Whistler began painting portraits at this time as well. His most famous portrait, the portrait that is still his most famous painting here in the U.S., was called “Arrangement in Grey and Black, No. 1.” The other name given to the painting was “The Artist’s Mother,” although it eventually became known by the name that most Americans know it by, which is simply, not “The Artist’s Mother,” but “Whistler’s Mother.”
A “portrait,” you probably know, is a painting or a photograph that shows a person’s face and sometimes the upper part of the person’s body. Sometimes it shows the entire body. This particular painting, “Arrangement in Grey and Black, No. 1,” shows Whistler’s mother sitting in a chair, and it is done, not surprisingly, in grey, black, and white. Whistler did another painting with a similar title called “Arrangement in Grey and Black, No. 2.” This one was not of his mother, but rather of a famous Scottish philosopher and historian by the name of Thomas Carlyle.
Today you can see “Whistler’s Mother” (or “Arrangement in Grey and Black, No. 1: The Artist’s Mother”) not in an American museum, but in a museum in Paris – the Musée d’Orsay (my apologies for my bad French). It’s interesting because many Americans who go to Paris will go to this museum – which, by the way, is a wonderful museum. The Louvre in Paris is amazing, but one of my favorite museums in Paris, at least the one time I’ve been there, was this particular museum.
Many Americans will go and they will look at this painting, and it has a certain connection to them because it’s the one painting of Whistler that they really know. The irony here, the odd thing here, is that of course Whistler was by most definitions much more European than he was American, and yet Americans – because they know this painting and because Whistler himself was an American – feel a certain connection to it.
Whistler, although he was a successful artist, did not make a lot of money. He loved to have parties. He was very popular with other artists, and perhaps he spent a little bit too much money. In 1879, he was so poor that he had to declare bankruptcy. “To declare bankruptcy” (bankruptcy) means to say that you don’t have enough money to pay your debts – the money that you owe to other people. This is a way of legally protecting yourself. You’re saying to the people to whom you owe money, “I’m sorry. I don’t have any money anymore.” That’s what Whistler did.
Well, he wasn’t poor, exactly. He did later move to Venice, but eventually moved back to London in 1880. His most productive period as a painter, however, had ended by this time. By “productive” (productive), I mean the period in which he was painting the most. His style of painting with colors like blue, grey, and white was not as popular anymore. People got more interested in, well, more colorful paintings – the kind of painting that was becoming popular among, say, the Impressionists and other styles of painting popular in the late nineteenth century.
Whistler was well known not only in the art scene in Europe, but also among writers and other intellectuals. He was well known for having a certain friendship with Oscar Wilde, the famous British writer who was considered one of the cleverest, funniest writers of his generation. Whistler and Wilde would often exchange what were called “witticisms,” which would be simply clever sentences or sayings. Some people say that Wilde actually used some of the things that Whistler said to him in his own conversations with other people.
In 1888, Whistler finally married, after many years of not being married. He married a woman by the name of Beatrix Godwin and the two of them moved to Paris. They continued to have their parties and be popular with a group of artists living there at that time. Beatrix died only a few years later in 1896, and it was said that Whistler never really recovered from her death, from the sadness of her death. He moved back to London and himself died in 1903 at the age of 69.
Despite being an American artist, it’s no surprise, now that we know his story, that most of Whistler’s paintings and etchings are not in the United States but in Europe. They are hung in famous museums such as the Tate Modern and the British National Collection in London, and of course in the Musée d’Orsay in Paris. Some of his work has returned, if you will, to the United States. You can see some of it at the greatest museum in the U.S., the Metropolitan Museum of Art in New York.
We turn now to our second topic, which is the famous song “Moon River.” “Moon River” was written by one of the most popular American composers of music, Henry Mancini. It was co-written by Johnny Mercer. The song was written in 1961 for a very famous movie, Breakfast at Tiffany’s. Henry Mancini wrote the music and Mercer wrote the words. Mancini wrote the music for many popular movies during this period.
The song was written especially for the star of Breakfast at Tiffany’s, which if you are a fan of old movies you will know was the wonderful, beautiful Audrey Hepburn. Hepburn, however, was not a great singer. So Mancini had to write a song that she would be able to sing well. He did, and the song became so popular and well liked that it won the Academy Award for Best Original Song in 1961. The Academy Award is the same as the Oscars. It is the award that is given to the best movies, directors, and songs of that year.
“Moon River” is a very short song. It was, according to the writer of the lyrics of the song, the words of the song, Johnny Mercer, inspired by a moon shining on a river near the place where Mercer grew up in Savannah, Georgia. Georgia is located in the southeast part of the United States. When I say a moon was “shining” on the river, I mean you could look into the river and see the reflection of the moon, the image of the moon, in the river.
The song, as I say, is quite short and – should I sing it? Should I? You think? Yeah? Okay, I will. Everybody here thinks I should. Of course, I’m the only one here. Anyway, here it goes . . .
Moon River, wider than a mile,
I’m crossing you in style some day.
Oh, dream maker, you heartbreaker,
wherever you’re going I’m going your way.
That’s the first verse of the song – the first part of the song. “Moon River,” as I mentioned earlier, refers to the river with the moon reflecting in it. You can see an image of the moon in the river. The song goes on to talk about how the singer promises to visit the river again someday. He says, “Moon River, wider than a mile. I’m crossing you in style someday.” “To cross a river” means to go from one side of the river to the other. So, he’s promising to cross the river again “in style.”
To do something “in style” (style) means to do it in such a way that you have a certain class. You do it in a way that is appealing – to do it in perhaps the very best or even most expensive possible way. If someone says, “I’m going to fly to the United States in style,” he may be referring to flying first class – the most expensive seat on the airplane. That would be to do something “in style” – in great comfort, perhaps even with great expense. This person in the song is going to cross Moon River again “in style someday.”
The singer then is talking to this river, Moon River, and saying, “Oh dream maker, you heartbreaker.” Someone or something that “makes dreams” would be a person or a thing who brings something wonderful to your life, perhaps, or a thing or a person who can give you your dreams, who can make real your dreams. A “heartbreaker” (heartbreaker) is in some ways the opposite of a dream maker. If someone breaks your heart, someone makes you very sad, usually because that person doesn’t love you the way you love him or her.
A heartbreaker is a person who perhaps is so beautiful that everyone falls in love with him or her, and therefore breaks a lot of hearts, disappoints a lot of people, because he or she can only love so many people. I have never been a heartbreaker, but we might describe a very handsome man, for example, a very good-looking man as being a heartbreaker, or a very beautiful woman, since many people will fall in love with that person. The singer of the song is saying that the river is a heartbreaker.
Nevertheless, he says, or she says, “Wherever you’re going, I’m going your way,” meaning I’m going to follow you nevertheless, even though you are a heartbreaker. The next part of the song talks about “two drifters off to see the world.” A “drifter” (drifter) is someone who travels around without a specific destination. A drifter doesn’t have a particular place he wants to go.
Often we use the word “drifter” to mean a person who doesn’t have a permanent home – perhaps a poor person who can’t afford a home, who is going from town to town, moving around, perhaps sleeping in a park, or someone who is otherwise homeless. But here, the word simply means a person who doesn’t have a destination, a specific place to go.
Oddly, the second verse of the song is really about how the Moon River and the singer of the song are similar in that they are seeking or trying to get the same thing. It talks about how the singer and the river are “after the same rainbow’s end.” The “rainbow’s end” here is a poetic way of describing the goal, but really something wonderful, something amazing. The old story, the old belief, is that at the end of a rainbow, there is a “pot (pot) of gold,” a big container of gold. A “rainbow” (rainbow) is a half-circle of different colors that appears in the sky sometimes after it rains.
So, the song is about how both the singer and Moon River are after the same goal. The song is slow and really kind of sad. It’s about people who are looking for something or perhaps trying to get something back that they lost and will never be able to get again. “Moon River” was a very popular song when it was released in 1961. The most popular version of the song is by a famous American singer that I remember hearing growing up, by the name of Andy Williams. In fact, I think he even had a television show on for a brief period of time.
It was popular for some reason in the late ’60s, early ’70s for famous singers to have their own television shows. The Smothers Brothers were singers, and Sonny and Cher were singers, Tony Orlando and Dawn was a group of singers, and all of them had their own television show. It was very strange. It was a weird time, the 1970s, for those of you too young to remember – well, a weird time in American television, let’s put it that way.
But no American is too young to remember the song “Moon River,” since it is still popular. And Andy Williams’ version is probably the most popular of them all.
Now let’s answer a few of the questions you have sent to us.
Our first question comes from Samuel (Samuel) in the mystery country called “Mystery” – Mystery, the country. Sounds like the name of a movie. Anyway, Samuel says he wants to know the difference between “to bungle” (bungle) and “to blunder” (blunder). The two words have related, similar meanings.
“To bungle” something is to make a lot of mistakes when you are trying to do something, to do something very poorly, or to be very unsuccessful at a certain task. If your boss gives you a project and you make all sorts of mistakes and you don’t do it correctly, she may say to you, “You’ve bungled this project. You’re fired. Get out of here. You’re no longer working here.” Well, I hope she doesn’t say that, but she could if you bungle everything she gives you.
“To blunder” means to try to do something without sufficient knowledge or without really understanding something, and because of that, you make a lot of stupid mistakes. So, “bungling” means to do something poorly, even if you know how to do it. “To blunder” means to do something poorly without really understanding it. So, you didn’t have sufficient knowledge or perhaps you were just too dumb, too stupid, to understand how to do it correctly. It’s a slight difference.
There’s an old expression, a “blundering idiot” – someone who makes lots of mistakes because he’s not very intelligent. He’s not very smart. There’s a noun “blunder,” which describes a stupid mistake that you might make. There are also the adverb forms of these words, “bunglingly” and “blunderingly” – kind of difficult to say – which could be used to describe certain actions that had the characteristics of “bungle” and “blunder.” Although I have to say, I don’t often hear or read the adverb forms of those two words.
Mario (Mario) – maybe related to Super Mario, I’m not sure – Mario from Brazil wants to know the meaning of the word “comparable.” “Comparable” (comparable) comes from the verb “to compare” (compare). “To compare” two things means to look at them and see the similarities between them, the things that are similar – or you could compare three things and look at the things that are similar. There’s another verb, “contrast” (contrast). “To contrast” two or more things means to look at the differences.
In everyday conversational English, however, people will often use “compare” and “contrast” basically to mean the same thing. They may use “compare” to talk about similarities and differences, or “contrast” to do the same thing. “Comparable,” however, means that two different things or two or more things are very similar. We might talk about “comparable hotels” – two hotels that are similar in quality. We might talk about “comparable houses” – houses that are about the same.
In fact, when you buy or sell a house in the United States, the person who helps you do that – a “real estate agent,” we would call that person – usually goes out and finds comparable houses that you’re interested in buying or that are similar to the house you want to sell, and they often will describe these as “comps” (comps). They’re comparable houses – similar houses that will give you an idea about the price that you should either be looking to pay for a house or be willing to sell your house.
There’s another word that is somewhat similar, which is “compatible” (compatible). However, “compatible” doesn’t mean similar. “Compatible” means that two different things or two different people are able to get along together. They are similar enough, perhaps, that they can work together. If someone says, “You and I are just not compatible,” that person is telling you that our personalities – rather, your personalities or your, I don’t know, ways of thinking and talking – are not similar enough that the two of you can be together.
You want your roommate to be “compatible.” You want someone with whom you can live who is similar enough to you that you are able to be able to get along. This is different than “comparable.” “Comparable” refers to the similarities between two or more things. “Compatible” refers to the ability of two or more things to get along – to go together, perhaps.
Finally, Ann (Ann) in China wants to know what we mean – what I mean – when I spell things and say something like “uppercase” (uppercase) and “lowercase” (lowercase). What does it mean, for example, if I spell my name by saying, “Uppercase J, lowercase e, f, f?” “Uppercase” refers to what we also call, in English, a “capital letter.” It’s what we would say, to a young child, a “big letter” or a “large letter.” In the Roman alphabet that is used to spell English, to write English, there are large letters and small letters. There are uppercase letters and lowercase letters.
You will, more often hear the word “capital” in front of a word that is “uppercase,” and nothing in front of a word that is “lowercase.” In other words, the assumption, when you’re spelling a word, is that all of the letters are small, or “lowercase,” letters. You would only say “capital” when there is an exception to that. For example, “California” is spelled capital C, a, l, i, f, o, r, n, i, a. The first letter of that word is “capitalized,” or written as an uppercase letter. The rest of the letters of that word are written as lowercase, or small, letters.
My last name is spelled capital M, c, capital Q, u, i, l, l, a, n. I have a last name that has two capital letters, which is a little bit uncommon. Scottish and Irish names often have two capital letters because of the form “Mc” or “Mac” which often comes at the beginning of a name. It basically just means “son of.” That’s why in other countries you’ll see a lot of words that end in “son” (son) – “Johnson” and “Anderson.” These are the son of John and the son of Ander, I guess.
Anyway, thanks for your question, Ann, which we would spell uppercase A, lowercase n, n – or more commonly, capital A, n, n. What would we do if all of the letters were capitalized, were uppercase? We might say something like “all capital letters A, N, N,” or after the word we might say, “A, N, N – all capital letters” or “all capitalized.” You get the idea.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
This is Jeff McQuillan from Los Angeles, California. Thanks for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2015 by the Center for Educational Development.
Glossary
strict – requiring that rules about behavior be followed closely and without exception
* Yuko grew up in a strict home where each child had to finish her homework and do all of her chores before she could go out and play.
bohemian lifestyle – a way of living that does not follow the traditional rules of society, often adopted by artists and writers
* Henri enjoyed his bohemian lifestyle where he slept all day and stayed up all night writing music or drinking and dancing with his friends.
etching – a picture made by putting ink on a piece of metal, glass, or stone with an image carved on it and then pressing paper on top of the metal
* These etchings of lake scenes are so detailed that they look a little like photos.
symphony – a long piece of music written for an entire orchestra, often with four movements or parts
* Annette listened to her favorite recording of Beethoven’s Fifth Symphony.
to stand out – to be different and noticeable in a group
* The basketball player stands out in a crowd because he is nearly eight feet tall.
to declare bankruptcy – to legally state that one does not have enough money to pay back the money that one owes
* The company was forced to declare bankruptcy after sales dropped dramatically as a result of the company president’s unpopular words.
productive – creating or doing a lot
* It’s difficult to be productive when my neighbor is having a loud party.
to reflect – to show an image of something on the surface of something else, such as a mirror, piece of glass, or the surface of water
* The mirror reflected his tired and haggard face.
in style – doing something in an impressive or luxurious way
* The actress arrived in style in a luxury car driven by a uniformed driver.
heartbreaker – someone whom many people fall in love with, but who may be careless of other people’s feelings
* She is smart and beautiful and I hope she doesn’t become a heartbreaker when she grows up!
drifter – a person who wanders from place to place without a specific destination in mind
* After losing his job, James became a drifter and traveled the world, working a little here and there to earn enough money for food.
rainbow – a curved line of different colors that appears in the sky after it rains
* After the huge thunderstorm, a beautiful rainbow appeared in the sky.
bunglingly – doing something poorly and unsuccessfully, make many mistakes
* In her rush, she mixed the ingredients bunglingly, not measuring them properly.
blunderingly – trying to do something without knowledge or the ability to understand, making stupid or careless mistakes; moving clumsily
* The new manager made decisions blunderingly, without considering the existing information or the likely consequences.
comparable – describing two or more things as being very similar, or being of similar quality or worth
* The drugstore no longer carried the brand of vitamins Joel takes, so the clerk recommended another brand that is comparable.
compatible – able to exist together without any problems or conflicts; for two things to go together well
* This cable isn’t compatible with your type of TV. You’ll need to buy another one.
uppercase – capital letters; a letter used at the beginning of a sentence or a proper noun, such as A, B, C, rather than a, b, c
* The name of the company is spelled in uppercase letters: BYTECH.
lowercase – small letters, for example, a, b, c and not A, B, C; not capital letters
* My name is misspelled on the new business cards, with my last name all in lowercase letters.
capital letter – a letter used at the beginning of a sentence or a proper noun, such as a name
* The question “How are you?” begins with a capital letter.
What Insiders Know
Moonshine
“Moonshine” is a “colloquial” (language used by ordinary people, not formal) term for alcohol that has been produced illegally, usually by an individual or a very small group of people in a hidden, secretive way. Moonshine “got its name” (was named a particular way) from the fact that people made it at night, by the light of the moon, when they were less likely to be “caught” (discovered to be doing something wrong; arrested).
Moonshine became extremely important during Prohibition (see English Café 288), the period from 1920 to 1933 when alcohol was “banned” (not allowed; became illegal) in the United States. People who wanted to continue to drink alcohol during that time didn’t have any legal “options” (choices), so they had to “turn to” (rely on; decide to have or use) moonshine. During this time, moonshine was an important source of “income” (the money that one earns from work) for many people, especially in “rural” (in the country, not in the cities) areas.
Many rural “farmers” (people who grow crops (plants for food) and raised animals) made moonshine from their own corn. It was generally a very “strong drink” (with a lot of alcohol), but sometimes it was “contaminated” (dirty; impure) and even “poisonous” (making someone very sick or even killing someone). This was because the materials used to make the “stills” (containers and machines used for making alcohol) were sometimes “toxic” (with poisons).
For example, some people used “radiators” (the part of a car that cools the engine) to make moonshine, but these had “traces” (small amounts) of “lead” (a heavy metal that can be dangerous to people’s health) and “antifreeze” (a substance that lowers the temperature at which a liquid freezes), which are poisonous. People soon learned to burn a spoonful of the moonshine, because they thought they could determine whether it was poisonous by studying the color of the “flame” (fire).