= 1806
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 501.
This is English as a Second Language Podcast’s English Café episode 501. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Go to our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. Are you on Facebook? Hey, so are we. Go to facebook.com/eslpod and like us. (We like you, too.)
On this Café, we’re going to talk about one of the most famous movies from the early 1980s, Raiders of the Lost Ark. We’re also going to talk about a famous hotel here in California called the Hotel del Coronado, near San Diego. And as always, we’ll answer a few of your questions. Let’s get started.
Raiders of the Lost Ark is the first story in the Indiana Jones film series. In this very famous set of films, the main character, the main person, is called Dr. Henry “Indiana” Jones. Indiana is a state in the United States, and it is the nickname of Dr. Jones. A “nickname” (nickname) is either a shorter name or a name that someone goes by instead of their real name.
Dr. Jones is an archaeologist – a scientist who looks for things, usually in the ground, that will tell him about the past. Indiana Jones is an archaeologist and professor at a college called the Mitchell College, which is a made-up college. It was created for the movie. Indiana’s friends call him Indy. “Indy” is short for “Indiana,” so it’s a nickname of a nickname, in a way. His enemies call him Dr. Jones.
When he isn’t teaching, Indy travels around the world looking for relics. A “relic” (relic) is an object from a long time ago that has some historical or religious value. Now, there is a more restricted definition of this term “relic.” In, for example, the Catholic Church, a relic is something related to a holy person, a saint, including part of the body of that saint. But more generally, “relic” is used to describe something that is very old and very valuable from some historical or religious perspective.
When Indy goes looking for relics, he always wears a certain jacket and a hat, and carries a whip to defend himself against anyone who wants to steal the treasures, the relics, that he finds. A “whip” (whip) is a long thin piece of leather or other material that is attached to a handle. It’s often used as an instrument of punishment to hurt someone.
The movie Raiders of the Lost Ark begins in 1936 in South America. Indiana Jones is looking for an idol. An “idol” (idol) is a statue that is used for religious purposes. Indy and his assistant find the idol in a cave and are barely able to escape the cave before it collapses. “To collapse” (collapse) means to fall apart suddenly. So, as Indy and his assistant are running through the jungle, through the trees, with the idol, his assistant turns on Indy and steals the idol, leaving Indy to die in the jungle. “To turn on” someone means to betray that person – to hurt that person after promising to help him or her.
Indy chases his assistant and gets the idol back only to have it stolen again by one of his other enemies, a French archeologist by the name of Dr. Rene Belloq. Belloq runs off with the idol and Indy, fortunately, is rescued by a friend. When I say he’s “rescued,” I mean he is saved from harm or death. So, Indiana is able to get out of this jungle, but he loses the idol that he had found. Indiana returns to Marshall College and is, of course, very angry about losing the idol. He tries to find a way to get the idol back from the man who stole it from him.
As he’s planning to get the idol back, another one of Indy’s friends arrives to tell him that the U.S. Army wants to talk to him. Why? The army, we learn, has found out that the Nazis from Germany – remember, this is during the 1930s – are apparently digging in the desert in Egypt and the American Army wants to know why. Indy knows immediately that the Nazis must have found an ancient city called Tanis. Tanis is where supposedly a very famous artifact, a very famous object, is buried. That object is called the “Ark of the Covenant.”
What is the “Ark (ark) of the Covenant (covenant)”? The “ark” was basically a box. A “covenant” is an agreement. In this case, it was an agreement between God and the Jewish people. The Ark of the Covenant was where the holiest things of the Jewish people were kept, including the Ten Commandments – the ten laws, moral laws, that God gave Moses in the desert in the story of the Old Testament of the Bible.
Indy and many other archeologists believe in the movie that the ark was placed in this city, this city called Tanis. Indy believes that the Nazis are looking for the ark because they believe the ark is supposed to give people superhuman powers. “Superhuman” just means stronger than the average person. Well, Indy goes to find a former, an ex-girlfriend of his named Marion Ravenwood. He knows that Marion has an important relic that will tell him exactly where the ark is buried. Wow! That’s really convenient.
But Marion refuses to help him because she is still angry with him for ending their relationship. Remember, guys – women never forget. Marion says no. Indy leaves, but then he comes back, and it’s a good thing that he does because the Nazis are trying to get Marion, and Indy saves Marion. So, Marion and Indy fly to Egypt to find the ark. They meet up with Indy’s friend Sallah who helps them and tells them that the mean French archaeologist Belloq – Indy’s enemy – is working with the Nazis, of course.
When the Nazis learn that Marion and Indy are in Egypt, they try to capture them. They try to get a hold of them and hold them in a prison or in some place so that they can’t interfere with the Nazis’ search for the ark. Marion in fact does get captured, but Indy does not. So, Indy and Sallah try to save Marion and, of course, find the ark. They realize that the Nazis are digging in the wrong place – I guess they didn’t have Google Maps to find the ark – but Indy and Sallah are smart and they find the ark.
But of course the Nazis find them before they are able to escape. They bring Marion where Indy is and leave the two of them in a pit in the ground. A “pit” (pit) is a large hole. This pit begins filling with snakes, which is the only thing that Indy is afraid of, of course. What will happen at the end of the movie? Will the two of them die? I can’t tell you that. But if you’ve ever seen a movie – an American movie made here in beautiful Los Angeles, California, also known as Hollywood – I think you know how the movie is going to end.
Raiders of the Lost Ark was an immediate success in the movie theaters. Audiences – people who went to see the movie – most of them loved the hero, Indiana Jones. He was sort of a traditional Hollywood hero, a what we might describe as a “swashbuckling hero.” “Swashbuckling” is an old term used to describe a person who goes on adventures and finds romance and, of course, danger in his journey.
There were many classic movies made in the 30s, 40s, and 50s with swashbuckling heroes – men, brave men who would go out and have these wonderful adventures and, of course, wonderful romances with the beautiful women. This is a classic Hollywood hero, and one of the things that the director of this movie, Steven Spielberg, did was sort of bring this old traditional hero back to the American movie theater – and of course, internationally as well.
The movie was written and produced by another famous director by the name of George Lucas, who you probably know also produced the Star Wars movies. Raiders of the Lost Ark was a huge success. It was nominated for eight Oscars, eight Academy Awards, in 1982. It won four of those. None of the big awards. It didn’t win for Best Picture or Best Director. It did win for the art, sound, editing, and visual effects.
Lucas and Spielberg worked on three more Indiana Jones movies. Of course, if a movie is popular, Hollywood likes to make another movie very similar to the one that was popular. Each of these movies continued the story of Indiana Jones, the professor, archaeologist, hero, and of course, lover. Because of the success of the movies, Indiana Jones became what we might describe as an “iconic image” or figure in American film. “Iconic” (iconic) here means widely known and recognized. All of the Indiana Jones movies were very successful and made millions and millions and millions of dollars.
Now, I went to see Raiders of the Lost Ark the very first weekend when it was first released to the American public in the movie theaters. In fact, I think I went to see it on the very first night that it was shown. I didn’t know anything about the movie. I was in high school at the time. I went with a large group of friends of mine. After the movie, we all came out of the movie theater and, of course, we started talking about the movie. Everyone in my group loved this movie. All of my friends thought this was amazing, and I thought it was absolutely horrible. I thought it was the worst movie I had seen in many, many years! Of course, I was only 17 years old, so I hadn’t seen that many movies, but I thought this was a terrible movie. I absolutely hated it. I didn’t understand why everyone loved it. That makes me one of five people in the world who didn’t like Raiders of the Lost Ark.
Now, I did eventually start to like the Indiana Jones movies. I did see some of the other movies, and I will say that I did like them, but the original movie – for whatever reason – when I was 17, I thought it was absolute garbage, but of course that just shows you how little I know about what makes a successful movie.
Our second topic is a famous hotel here in California called the Hotel del Coronado, also known either as “The Hotel Del” or simply “The Del.” The hotel is located on an island near the city of San Diego. The island is called Coronado Island, and it is therefore called the Hotel del Coronado. “Del” means “of” here, in Spanish. So it is the “Coronado Hotel,” basically.
The businesspeople who built the hotel wanted it to be the talk of the Western world back in the late nineteenth century when it was built. When we say something is the “talk of” something, we mean it’s going to be very popular and well known. The businesspeople who started the hotel actually bought the entire island of Coronado and began building the hotel in 1887.
Unfortunately, this was not a good time for the American economy. So, the original founders of this hotel, the original investors in the hotel, had to go and find other people to give the money to help build this beautiful hotel. When the construction was finished, it cost about a million dollars in total to build and decorate, which of course is quite a bit of money for the late nineteenth century.
The Hotel Del opened to guests in January of 1888 and was considered one of the most luxurious hotels of this period. “Luxurious” means very comfortable, with lots of expensive things. It’s a beautiful hotel. The architecture of the hotel is very beautiful – I’ve been there a couple of times – and it immediately became a popular place for people to go for vacation, to get married, and even to make movies.
Much later, in the late 1950s, Marilyn Monroe made a movie that was filmed largely at the hotel. The movie was called Some Like It Hot. The scenes in the movie that take place outside were all shot there at the Hotel Del. When I say they were “shot,” I mean that’s where they were filmed. That’s where they actually had the actors and actresses standing. The main actors in the film were Marilyn Monroe, Tony Curtis, and Jack Lemmon, and all of them of course stayed at the hotel during the filming.
There was another famous movie made at the Hotel Del, in 1977, called The Stunt Man. And once again, you can see the hotel if you watch the movie. The hotel is mostly famous for being a place where a lot of famous people have stayed. At least 15 American presidents have stayed at the hotel, including Franklin Delano Roosevelt, John F. Kennedy, Richard Nixon, Ronald Reagan, Bill Clinton, and George W. Bush.
King Edward VIII of England also stayed there, and the story is – I don’t know if this is true – that it was at this hotel that he met Wallace Simpson, the American woman who he eventually married and had to give up his throne for. Part of their story is told in another famous movie of a few years ago called The King’s Speech. Hotel Del also has a connection to another great American movie called The Wizard of Oz. The author of The Wizard of Oz, L. Frank Baum, stayed at the Hotel Del, they say, while writing some of his books.
Some people believe, in fact, that the hotel was the inspiration for one of the most famous places in his Wizard of Oz books, Emerald City. When I say it was an “inspiration for,” I mean it was the thing that gave him the idea. If you remember The Wizard of Oz, there was a famous city where the Wizard of Oz lives. Some people think the architecture of the hotel inspired Baum when he was writing about this place in his book, Emerald City.
Another famous person who stayed at the hotel was Kate Morgan. Now, why is Kate Morgan considered famous? Well, because in November of 1892, Morgan, after checking into the hotel, was found dead on one of the hotel staircases. She was dead because she had been shot with a gun.
At the time, the police in San Diego thought that she had killed herself – that she had committed suicide – but many people didn’t believe it. It is said today that Kate Morgan’s ghost still haunts the hotel. A “ghost” (ghost) is an appearance of a person who has died. And “to haunt” (haunt) means to continue to live in a place even after you’re dead.
If you go to San Diego, you can stay at the Hotel del Coronado, or at least you can visit it. It has almost 700 guest rooms and 11 restaurants and has consistently been rated as one of the best hotels – not only in the United States, but in the world – for its beauty and its excellent service. I stayed there back in the 1990s for a couple of nights. I was there for a conference, an academic meeting. Fortunately, the university paid for my room, because it’s somewhat of an expensive hotel to stay in.
When I go down to San Diego, which is only about two hours from where I live, I often will go out to Coronado Island to take a look at the hotel and perhaps to eat in one of its very excellent restaurants. So, if you’re in San Diego, the southernmost city in California, and you’re looking for something to do, I can definitely recommend going out and seeing, if not staying in, the Hotel del Coronado.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Genie (Genie) in Malaysia. Genie wants to know the meanings of the words “to forfeit,” “to nullify,” and “to revoke.” Let’s start with “to forfeit” (forfeit). “To forfeit” something means to lose the right to something, especially as a result of an error that you have made or because you have done something wrong.
For example, if you are on a basketball team or a soccer team, and you are supposed to play another team, but you never go to the game. Well, the other team will be considered the winner of the game because you have “forfeited” the game. You have lost the game because, in this case, you didn’t go to the game. Sometimes here in the United States, when people break the law – when they do something illegal – they may “forfeit” certain pieces of their property. They may have to give up things that they own because they have broken the law.
The second term here is “to nullify” (nullify). “To nullify” is a little different. It means to cause something to no longer be in effect, or to in some cases lose its value. Usually you will hear this term in a legal context when we’re talking about the law. “To nullify” something is to say this law or this rule is no longer going to be enforced. It’s no longer going to be considered a law or a rule that you have to follow.
The third verb is “to revoke” (revoke). Once again, this word is usually used in a legal context. “To revoke” means to cancel the power or effect of something, such as a law or a license or an agreement. So, let’s say that you and I sign a contract, an official agreement, and you don’t do what you’re supposed to do. I may decide to revoke the contract, revoke the agreement – say, “You know what, I’m no longer going to be part of this contract or this agreement.”
Often this verb is used when people have a certain license, certain permission from the government, and the government decides to take away the license, to end that permission. For example, if you have a driver’s license to drive in California, and then you are arrested for drinking while driving, the state government may revoke your driver’s license. It may say, “You know what, you no longer have the right to drive in California. We’re going to, in effect, take your license back from you.”
Our second question comes from Ivy (Ivy) in China. Ivy wants to know the difference between “nevertheless” and “nonetheless.” As a general rule, the two adverbs mean the same thing and can be used in the same places. Notice that these are compound words – they are words that are made up of other words put together. “Nonetheless” (nonetheless) is one word, even though you can find three words inside of it. The same is true for “nevertheless” (nevertheless).
Both of these adverbs mean “in spite of what has just been said” or “in spite of some fact.” They are perhaps best defined through examples. “My girlfriend didn’t call me last night, which is a good thing because I’m married. Nevertheless, she did send me some flowers.” “Nevertheless” means even though she didn’t call me – in spite of that fact – she did send me some flowers.
You could also say, “My girlfriend didn’t call me last night. Nonetheless, she sent me some flowers.” You could also put the adverb at the end of the sentence. You could say, “My girlfriend didn’t call me last night. She sent me some flowers, nonetheless.” “Nonetheless” and “nevertheless” are used in a situation where you have two different things happening that seem to be opposite or perhaps contradictory or that you might think wouldn’t go together, but they do – or they do in this situation.
Let me give you another example. “The acting in this movie is not very good, but I enjoyed it nevertheless” (or “nevertheless, I enjoyed it”). You would think that because the acting was bad I would not enjoy it, but I’m saying that I did enjoy it, so it’s something of a surprise. It’s not expected from what you learned in the first part of the sentence or in the first clause.
Now, there will be people who will tell you that there are slight differences in how these adverbs are used, and while that’s probably true, as a general rule you can use “nonetheless” in the same situations that you use “nevertheless.” There are some very, very small differences, but probably too complicated to try to explain. So as a general rule, the two words mean the same.
Finally, Pierre (Pierre) on the beautiful island of Martinique. I would love to go to Martinique someday. Pierre, if you have an extra room, let me know. Pierre wants to know the difference between the verb “to live” (live) and the adjective – and sometimes adverb – “live” (live). You will notice that the two words are spelled the same but pronounced differently depending on whether you use it as a verb or as an adjective or adverb. Let’s start with the verb “to live.”
“To live” means to exist. It is the opposite of the state of being dead. It can also be considered, I guess, the opposite of the verb “to die.” “To die” means your life ends. “To live” means your life continues. You are still breathing. You still have a heartbeat. You are living.
So, “live” can also mean to have your home in a certain place. We might also use the verb “to reside” (reside). “I live in Los Angeles.” That’s where my home is. “I live in California.” “I live in the United States.” “I live in a house.” All of those are possible sentences with related meanings of “this is the place where I am located.”
The adjective “live” means having life. We can talk about a “live chicken.” This would be a chicken that is not in your refrigerator, ready to eat. This is a chicken that is still walking around and making noise. It is a live chicken. We also use this adjective “live” to refer to a wire that is carrying electric current or electricity. We talk about a “live wire” (live wire). A “live wir would be a long string of metal that is inside of or connects to an electronic device, that is carrying an electric current, and if you touch it, you might hurt yourself.
Finally, we use “live” in the world of television and radio to describe a broadcast that is taking place right now. These podcasts are recorded; they’re not “live.” You’re not listening to this right now as I’m recording it. You’re listening to it later. But if you watch the news on television tonight, you will watch a “live broadcast” – a live show where the people are actually talking as you are listening to them.
“Live” can also be used in this sense as an adverb. We can talk about something being broadcast “live.” As an adjective, it would go before a noun. So, you could talk about a “live show” – that is “live” as an adjective, or you could use it as an adverb: “It is being televised live.”
If you have a question or comment, you can email me at eslpod@eslpod.com.
From Los Angeles California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Cafe.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2015 by the Center for Educational Development.
Glossary
relic – an object from a long time ago that has historical or religious value
* The church has a museum with some of the oldest relics found in the country.
idol – a small statue that is used for religious purposes, often in the form of a god or other important religious figure
* The golden idol of the god sat on top of the altar so that all of the people who came to pray could see it.
to collapse – to fall apart suddenly; to fall to the ground suddenly and in many pieces
* After the fire, the house was unstable and the roof collapsed.
to turn on (someone) – to betray someone or to try to hurt someone after promising one’s help or support
* Benedict Arnold was a general in the American military during the Revolutionary War who turned on his countrymen and started fighting for their enemy, the British.
superhuman – stronger or better than the average person; having incredible powers or skills
* Liesl has such good hearing that her parents often jokes that it is superhuman.
to capture – to trap or to grab and hold someone or something by force
* After chasing his dog around the neighborhood for an hour, Amir was finally able to capture the animal and bring it home.
swashbuckling – describing a person who goes on dangerous adventures and finds romance along the way, usually found in films or books
* Everyone is excited about the new movie because it has a swashbuckling hero who fights off pirates and bad guys in order to save a beautiful princess.
iconic – widely known and recognized as being important or very good, or as representative of a type of thing
* On the Road by Jack Kerouac is one of the iconic novels of the beat generation and helped to define a way of life and a way of looking at the world.
to be the talk of – to be very popular and well-known, usually for a short period of time
* Anastasia and Pietro’s engagement was the talk of the dinner party because all of their friends and family members were so excited for them.
to shoot – to film a movie or television show
* Some of the most famous television shows supposedly taking place in New York City were actually shot in Los Angeles.
to be the inspiration for – to be the reason or source of an idea for a person to do something or to create something
* Many people have tried to solve the mystery of exactly which woman was the inspiration for DaVinci’s painting “Mona Lisa.”
to haunt – for a memory that causes one pain or sadness to be difficult to forget; to continue to live in or visit a place often, usually by ghosts
* Radha was so haunted by the memory of her ex-boyfriend that she moved out of town and started a new life across the country.
to forfeit – to give up or lose the right to something, especially as a result of an error or having done something wrong or against the law
* Students forfeit the right to a free education at this college if they cheat.
to nullify – to cause something to lose its value or to have no effect
* The new law nullifies old, outdated laws about voting rights.
to revoke – to officially cancel the power or effect of something, such as a law, license, or agreement; to make something no longer valid
* If you get too many traffic tickets, your driver’s license may be revoked.
nonetheless – in spite of what has just been said
* Monica always tells bad jokes, but I like her nonetheless.
nevertheless – in spite of the facts; however
* Jada heard the warnings about traveling to that country, but she’s going there nevertheless.
to live – to be alive; to exist; to have one’s home in a place; to reside
* The surgeon said the operation was successful and Ming is expected to live.
live – having life; alive; not taped, filmed, or recorded; carrying an electric current or with electricity going through it
* The president’s speech will be shown live on television tonight.
What Insiders Know
The Song “Hotel California”
In 1977, the popular rock band the Eagles “released” (made available for use and/or purchase) the “single” (a song that is particularly popular on an album) “Hotel California.” This song has become one of the most popular and best-known songs in American music history.
Hotel California was written by Don Felder, Don Henley, and Glenn Frey of the Eagles. It reached the “top” (number 1) of the Billboard Hot 100 singles “chart” (listing based on popularity) in May 1977. In “just” (only) three months after the song’s release, it was “certified” (officially recognized as) “Gold” by the Recording Industry Association of America (RIAA), an organization which “monitors” (watches and records) music sales. When a song is certified Gold, it means that the song has sold over 1,000,000 copies. Hotel California also won the 1977 Grammy Award for Record of the Year at the 20th Grammy Awards in 1978. The Grammy Awards are the most respected music awards in the U.S.
The song’s “lyrics” (words) describe the journey of a traveler. He “checks into” (registers at) a “luxury” (very nice, expensive, and lavish) hotel that appeared inviting and tempting. He later finds out that the hotel is “nightmarish” and is a very frightening or unpleasant place. In fact, it is a place where “you can ‘check out’ (pay one’s bill at a hotel and prepare to leave) anytime but you can never leave.” In the 2013 documentary, History of the Eagles, Don Henley, one of the band members, explains that the song was about a journey from “innocence” (being pure and without bad intentions) to experience.
Hotel California continues to be popular today, with the song appearing on many lists of the best or most influential songs in rock history. In 2009, “Hotel California” was certified “Platinum” by the RIAA for selling 1,000,000 “digital” (electronic) “downloads” (the copying of an electronic file from a website to one’s computer or other device).