= 1035
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,035 – Using a Self- Checkout Machine.
This is English as a Second Language Podcast episode 1,035. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. You can also take a look at our ESL Podcast courses on our website.
This episode is a dialogue between Claudia and Raul about buying things from the store without ever really talking to anyone. Let’s get started.
[start of dialogue]
Claudia: We’re done, right? Let’s get in this cashier line.
Raul: No need. This store has self-checkout machines.
Claudia: I don’t know. I think it would be easier going through a cashier line.
Raul: Using the self-checkout will be much quicker. Let me show you. All you have to do is scan the bar codes on each grocery item.
Claudia: There are no bar codes on fruits and vegetables.
Raul: All you have to do is put them on the scale and find the product on the touch screen.
Claudia: You look. I’ll start bagging.
Raul: Wait! You’re supposed to wait until everything is scanned before removing items from the bagging area to put in bags. Oh no, now there’s a “see attendant” message on the screen.
Claudia: What do we do now?
Raul: We wait for the attendant to clear the error and void the transaction. Then we start again.
Claudia: Great. You’re right. This is much faster.
Raul: It is if you know what you’re doing.
Claudia: I’ll tell you what. I’ll take half of our groceries and stand in line and you use the self-checkout. We’ll see which is faster.
Raul: That’s a sucker bet. I have no doubt that I’ll be done before you are.
Claudia: I’m not worried. The last one out the door makes dinner.
Raul: You’re on. Just remember that I like my steak well done.
[end of dialogue]
Claudia begins our dialogue by asking Raul, “We’re done, right?” meaning “We agree that we are done now” or “I understand that we are now finished. Is that correct?” “Let’s get in this cashier line.” A “cashier” (cashier) is someone who takes your money at a store when you want to buy something. A “cashier line” would be a line of people waiting to buy things from the store – people who are waiting for the cashier to finish with the person in front of them so they can then purchase what they came to the store to buy.
However, Raul says, “No need,” meaning we don’t need to stand in the cashier line. “This store has self-checkout machines.” The verb “to check out” means to give your money to someone from the store in order to buy what you want to buy. “Self-checkout” is a new system in many American stores where you don’t have to give your money to a cashier, a person, a live human being. Instead, you can give your money to a machine. You basically stand in front of the machine and the machine reads the information from the packaging and tells you how much you have to pay.
Claudia says, “I don’t know.” What Claudia means here is she’s not sure she wants to use the self-checkout machines. She is hesitant. She’s doubting whether this is a good idea. She says, “I think it would be easier to go through a cashier line.” She thinks it’s easier just to talk to human being and have them do all of the necessary things in order to figure out how much money you give them. Raul says, “Using the self-checkout will be much quicker. Let me show you.” Let me demonstrate how you do this. So, Raul now is going to show Claudia how the self-checkout machine works.
He says, “All you have to do is scan the bar codes on each grocery item.” Claudia and Raul are in a grocery store. A “grocery store” is a store that sells food. A “bar code” (bar code) is a little square with a bunch of black and white lines on it that is used by a computer to identify the specific thing that you are buying. Most things in American stores, including grocery stores, have these little squares that have lines that are black and white, and usually some numbers on the bottom. We call these “bar codes.”
What do you do with the bar code? Well, you have to put it in front of a machine, and the machine will scan it. “To scan” (scan) basically means the machine looks at the code and “reads” it to determine what you are buying. However, there’s a small problem with this system at a grocery store, and Claudia lets us know what that is in the very next sentence. She says, “There are no bar codes on fruits and vegetables.”
Because each person picks his or her own fruits and vegetables, there aren’t bar codes on the bags. You put them in your own little bags, and you take them and usually the cashier will look at it and then put in the right item and amount. However, if you’re using a self-checkout machine, you need to do something a little different. And Raul tells us.
He says, “All you have to do is put them on the scale and find the product on the touch-screen.” Notice that Raul starts this sentence by using the phrase “all you have to do.” That’s what he said earlier in the dialogue. It’s a very common phrase when you are explaining something to someone and indicating that it isn’t difficult – it’s very easy. It’s not complicated.
Raul says, “You need to put the fruits and vegetables on this scale (scale).” A “scale” is a device, a machine, that tells you how heavy something is. It weighs the thing or the person. The verb we use when a person weighs himself is “step on.” “He stepped on the scale to find out how fat he was.” (Or how skinny – let’s be optimistic.)
Raul says that after you put the fruits and/or vegetables on the scale, you have to find them on the touch-screen. The “touch-screen” is a flat computer screen that, when you touch it, something happens. It’s sort of like what we now have – tablets like iPads – where you can touch the screen and something happens. They have these touch-screens with the self-checkout machines in order to make things quicker. You don’t have to type anything with a keyboard.
Claudia says, “You look,” meaning you look for the name of this item, “I’ll start bagging.” “To bag” (bag), as a verb, means to put things into a container which is called, confusingly, a “bag.” A “bag” can be made of plastic or paper or some other material, and we use bags to carry things around. When you go to a grocery store in the United States, they usually give you either a paper or a plastic bag. Sometimes they charge you money for the bags, however, so many people bring their own bags from home. So, “to bag” means to put something in a bag.
Raul says, “Wait! You’re supposed to wait until everything is scanned before removing items from the bagging area to put in bags.” The way the self-checkout machines work is that you put things on a flat surface, like a little table, called the “bagging area.” After you scan something, you then put it on this small table, but the table itself is connected to the machine, and it can tell how much weight you are putting on the machine. It’s a way, I guess, for the grocery store company to make sure you’re not cheating. You can’t put things into bags until you finished scanning all of your items. That’s what Raul says.
He says, “Oh no, now there’s a ‘see attendant’ message on the screen.” An “attendant” (attendant) is a person who works for, in this case, a store to help customers find things. The attendant here is helping customers use the self-checkout machine. So yes, although you don’t talk to anyone, you do everything yourself in self-checkout, there will be an employee from the store, an attendant, who will help you if you need help with the machine.
What happened is that Claudia made a mistake, and the machine stopped and put a message on the screen which said “see attendant,” meaning you have to talk to the employee. Claudia says, “What do we do now?” Raul says, “We wait for the attendant to clear the error and void the transaction then we start again.” “To clear” (clear) means to delete or to erase something. “To void (void) a transaction” means basically to undo a sale – make something as though it had never happened.
So, let’s say you’re buying something at the store and the cashier makes a mistake, or you make a mistake, you give the cashier the wrong thing. You can then say, “Oh no, no, I don’t want that.” The cashier can “void the transaction.” A “transaction” is just, in this case, another word for the sale of something. The cashier voids the transaction as though it had never existed. You delete it. You get rid of it. You erase it.
Claudia is not very happy that she now has to wait for the attendant. She says, “Great. You’re right. This is much faster.” Claudia is being sarcastic here. She’s making a joke. She doesn’t think it’s much faster. She thinks the self-checkout is taking them longer than it would if they had used a cashier. Raul says, “It is” – meaning it is faster – “if you know what you’re doing.” Raul is saying that had Claudia not made a mistake, it would’ve been faster.
Claudia says, “I’ll tell you what. I’ll take half of our groceries and stand in line, and you use the self-checkout. We’ll see which is faster.” The expression “I’ll tell you what” is an informal one used to present or propose an idea to someone. You are giving someone an idea usually that has some sort of “If you do this, then that will happen.” “I’ll tell you what. If you give me $20, I will give you a free English lesson.” “I’ll tell you what” is a way of introducing a proposal, something that I will do for you if you do something for me.
Here, it’s about Claudia and Raul each doing something different. Claudia is going to go to the cashier, the human being, to buy half of the groceries, half of the food that they are purchasing. Raul is going to take the other half and go through the self-checkout machine, then they’ll see who gets finished first – who “gets through the line,” if you will, or who checks out first.
Raul says, “That’s a sucker bet. I have no doubt that I’ll be done before you are.” A “sucker (sucker) bet (bet)” is a gambling offer that only someone who perhaps is inexperienced or not very intelligent would accept. The word “sucker” is used to describe someone who is a fool, someone who is easily deceived, someone who other people, we would say, “take advantage of.” A sucker bet would be a bet that only a stupid person would accept.
Claudia says, “I’m not worried. The last one out the door makes dinner.” “The last one out the door” means the person who finishes last, the person who gets through the checkout process last, has to make dinner. Raul says, “You’re on.” When you challenge someone to do something or you bet someone, one common way of replying is to say, “You’re on.” So, I say to you, “If you give me $20, I will teach you English.” You say, “You’re on,” meaning “Yes, I’ll do that.” Normally, however, it’s when you’re betting about something.
Raul says, “Just remember that I like my steak well done.” Raul is assuming that he’s going to win the bet, and he’s already telling Claudia how he wants his steak cooked. He wants his steak, which is a thick piece of beef, “well done,” meaning there isn’t any redness inside of the meat.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Claudia: We’re done, right? Let’s get in this cashier line.
Raul: No need. This store has self-checkout machines.
Claudia: I don’t know. I think it would be easier going through a cashier line.
Raul: Using the self-checkout will be much quicker. Let me show you. All you have to do is scan the bar codes on each grocery item.
Claudia: There are no bar codes on fruits and vegetables.
Raul: All you have to do is put them on the scale and find the product on the touch-screen.
Claudia: You look. I’ll start bagging.
Raul: Wait! You’re supposed to wait until everything is scanned before removing items from the bagging area to put in bags. Oh no, now there’s a “see attendant” message on the screen.
Claudia: What do we do now?
Raul: We wait for the attendant to clear the error and void the transaction. Then we start again.
Claudia: Great. You’re right. This is much faster.
Raul: It is if you know what you’re doing.
Claudia: I’ll tell you what. I’ll take half of our groceries and stand in line and you use the self-checkout. We’ll see which is faster.
Raul: That’s a sucker bet. I have no doubt that I’ll be done before you are.
Claudia: I’m not worried. The last one out the door makes dinner.
Raul: You’re on. Just remember that I like my steak well done.
[end of dialogue]
Our scripts are always well done. That’s because they’re done by the wonderful Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
cashier line – a group of people who are standing one behind the other to wait for the store employee to become available to help them make their purchase
* The woman at the front of the cashier line had to run back to the aisles to find something that she forgot to buy, so the rest of us had to keep waiting.
self-checkout – a process or machine designed to allow people to purchase items or process their own transaction before leaving a store, without help from an employee
* The self-checkout area is constantly monitored to make sure that nobody steals items without paying for them.
machine – an electronic device that performs some task, especially to save time, effort, and/or money for humans
* When will someone invent a machine that folds laundry?
to scan – to have a computer “read” or get information
* The airport has special machines that scan luggage tags and send the luggage to the correct airplane.
barcode – a series of wide and narrow parallel (running in the same direction) lines with numbers on the bottom, read by computers, and used as a label to identify a product or another item
* The store employee couldn’t find the barcode on the box to find out the price.
grocery – related to food and other household items that are sold in stores
* Can you pick up some milk and bananas at the grocery store on your way home from work?
scale – balance; a device that measures the weight of a person or object
* According to this scale, I’ve gained 14 pounds. That can’t be right!
touch-screen – a flat, digital screen that allows the user to provide information by touching certain parts of the screen, without needing to type anything
* The ATM uses a touch-screen interface, so you can just tap here if you want to make a deposit, or here if you want to make a withdrawal.
to bag – to place groceries or other purchased items into paper, plastic, or cloth bags so that they can be carried out of the store
* Janine always bags her groceries in reusable bags, but yesterday, she accidentally left her bags at home.
bagging area – the place in a store where purchased items are placed and then picked up and put into bags so that they can be taken out of the store
* It’s important to organize the bagging area so that you can pack up the heavy items first and leave the fragile items like bread and eggs for the last bag.
attendant – a person who provides service to customers, meeting their needs
* The flight attendant offered the passengers a variety of drinks.
to clear – to erase or delete something so that it is no longer visible, relevant, or applicable
* How can I paste this text, but clear the formatting?
to void a transaction – to undo a sale before it is final, making it as if it had never happened; to cancel a sale
* Please present your coupons first. Otherwise I’ll have to void the transaction and re-enter everything.
I’ll tell you what – an informal phrase used to propose something or present an idea
* I don’t really like that paint color, but I’ll tell you what. You can paint the dining room that color if I can pick out the paint color for the living room.
sucker bet – a gambling offer that only a na?ve, inexperienced person is likely to accept, because the investment or risk is higher than the reward or benefit
* That was a sucker bet. Why did Kile agree to it? They really tricked him.
well done – a way of cooking a piece of meat, especially beef, so that it is very thoroughly cooked, with no red or pink parts showing
* My grandfather always said that steaks are best served medium rare and juicy, not well done and dry.
Comprehension Questions
1. Why does Raul want to use the self-checkout machine?
a) Because he thinks it will be faster than standing in line.
b) Because he’s training to be a cashier in the grocery store.
c) Because he expects to pay lower prices that way.
2. Why is there a “see attendant” message on the screen?
a) Because the store will give the buyers a discount.
b) Because the machine thinks they’re stealing something.
c) Because a human needs to correct a problem before proceeding.
Answers at bottom.
What Else Does It Mean?
scale
The word “scale,” in this podcast, means a balance, or a device that measures the weight of a person or object: “Joanna used a small kitchen scale to measure how much flour and sugar to put into the bowl.” When talking about a fish or reptile, a “scale” is one of many small, flat, hard pieces of skin: “Please remove all the scales before you cook the trout.” When talking about music, a “scale” is a series of musical notes placed in order from low to high, or high to low: “Please play two octaves of the A major scale.” Finally, when talking about maps or models, the “scale” is an indication of the size of something: “Please draw a map of your neighborhood with a scale of 1:15,000.”
to bag
In this podcast, the verb “to bag” means to place groceries or other purchased items into paper, plastic, or cloth bags so that they can be carried out of the store: “If you bag all your canned goods together, you might not be strong enough to lift the bag!” The phrase “to bag (something) up” means to put things into bags: “Please bag up the children’s old clothing and we’ll donate it to the local homeless shelter.” A “bag lady” is a rude term for a homeless woman who carries her belonging with her: “He bought coffee and a doughnut for the bag lady down the street.” Finally, a “doggy bag” is a small bag or box used to take home food that remains uneaten after a meal at a restaurant: “Could you please bring us a doggy bag for the rest of this pasta?
Culture Note
History of the Use of Barcodes
The earliest barcode was invented in 1948 and “patented” (officially registered for protection) in 1952, but the idea did not “take off” (become popular and common) until years later. One of the first “applications” (uses) was in the railway system, where companies tries to use early barcodes to identify the owner and “contents” (what’s held inside) of railroad cars. Unfortunately, dirt and “wear” (reduced quality or poor condition caused by use and age) weakened the system. Then a “toll bridge” (a bridge that requires drivers to pay if they want to cross it) in New Jersey began using barcodes to identify which cars had purchased a “monthly pass” (permission to do something for an entire month). And then the post office began using an early barcode system, too.
But barcodes really “found their niche” (discovered where they were needed and what they were capable of) in grocery stores. The first “UPC” (universal product code) was used on a package of “chewing gum” (a substance placed in the mouth and chewed for a long period of time, but never swallowed) in 1974. Today, UPC barcodes are “ubiquitous” (found everywhere and on everything) in stores.
Barcodes are also found on patients’ identification “bracelets” (objects worn around the “wrist” (the body part between the hand and the arm)), rental cars, factory equipment, luggage, “certified mail” (mail that is tracked for delivery confirmation), and more.
In recent years, “QR codes” (quick response codes; a set of black squares on a white background) have begun appearing as a replacement for UPC barcodes, because they can present more information in less space. QR codes were originally used in the automotive industry, but now that “smart phones” can scan them, they are appearing on materials for consumers, too.
Comprehension Answers
1 - a
2 - c