= 1001
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast episode 1,001 – Practicing Yoga.
This is English as a Second Language Podcast episode 1,001. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download the Learning Guide for this episode. This episode is a dialogue between Victor and Rosaria about something I don’t know very much about and have never done, but I’m happy to talk about, and that is practicing yoga. Let’s get started.
[start of dialogue]
Victor: Humph!
Rosaria: What’s the matter?
Victor: I just got back from my first yoga class and I was sorely disappointed.
Rosaria: I’ve heard that yoga is very good low-impact exercise and helps with stress relief. It’s supposed to calm the mind and strengthen the body.
Victor: Yeah, right.
Rosaria: It sounds like you had a bad experience. Did you have a bad teacher?
Victor: The teacher was fine. I learned about mantras and chakras, I learned breathing techniques, and I tried a few basic poses.
Rosaria: That all sounds right from my own experience, such as it is. But, there are a lot of different types of yoga. Maybe you need to try a different kind.
Victor: The problem wasn’t the kind of yoga being practiced. It was the class.
Rosaria: Were the mats uncomfortable?
Victor: No.
Rosaria: Was it too cramped?
Victor: No.
Rosaria: Then what was the problem?
Victor: There was too much testosterone in the room.
Rosaria: You mean you were in a class with just men?
Victor: Yeah.
Rosaria: And that was a problem?
Victor: Do you think I would be taking a yoga class if I weren’t trying to meet women?!
[end of dialogue]
This dialogue is about “yoga” (yoga), which has been very popular in the United States over the last 25 years or so. It is especially popular here in Los Angeles, or at least it used to be. Yoga is something different to different people. When most people in the U.S. talk about yoga, they’re really talking about the program of exercise that you do, usually following some sort of leader in a class.
There are lots of places here in Los Angeles where you can go to a yoga class, and you do certain exercises for your physical health – and some say also for your mental health and relaxation. Our dialogue begins with Victor sounding disappointed. He says, “Humph!” Rosaria says, “What’s the matter?” He says, “I just got back from” – I just returned from – “my first yoga class, and I was sorely disappointed.” The word “sorely” (sorely) means very much, or greatly. Victor was really disappointed.
Rosaria says, “I’ve heard that yoga is very good low-impact exercise.” “Low-impact (impact) exercise” is exercise that doesn’t require a lot of hard, sudden movements with your body. You’re getting exercise, but it isn’t going to hurt your knees or your legs or some other part of your body. Rosaria says that she heard that yoga “helps with stress relief.” “Stress” (stress) is anxiety, tension. A “stressful situation” is a situation in which you have or experience this tension and/or anxiety, which can affect your body as well as your mind.
Rosaria uses the term “stress relief” (relief). If you get “relief” from something, you no longer suffer from that thing. We usually use the word “relief” when we’re talking about someone who is ill or sick and needs to feel better or wants to get better. You may give that person some drugs to give them relief from the pain, for example. In fact, we call those kinds of drugs “pain relievers,” similar to “relief.”
Rosaria says that she heard that “yoga is supposed to calm the mind and strengthen the body.” “To calm (calm) the mind” means to make you stop worrying about things, to stop you from having these stressful thoughts so that you are more relaxed. “To strengthen (strengthen) the body” means to make the body stronger – to perhaps exercise your muscles in such a way that you are physically stronger.
Victor, however, doesn’t seem to agree. He says, “Yeah, right.” When we use that expression, “Yeah, right,” with that sort of intonation, that sort of tone, we are indicating that we don’t agree. It’s very confusing, because normally if someone says, “Right,” they mean “Correct,” or “I agree.” But if you say it in this way – “Yeah, right” – that means that you don’t agree. You think that is wrong.
Rosaria says, “It sounds like you had a bad experience. Did you have a bad teacher?” Victor says, “The teacher was fine” – the teacher was okay. Remember I mentioned that in most yoga classes there’s someone who’s leading the class, just like any class, and we call that person the “teacher.” Victor says, “I learned about mantas and chakras, I learned breathing techniques, and I tried a few basic poses.”
A “mantra” (mantra) is a sound, a word, or a phrase that is used often for people who are meditating or perhaps praying. It’s a word that’s often associated with yoga, although there are some other traditions, other practices, of meditation and prayer that use that same term outside of the “world of yoga,” we could say. A mantra is typically a word or a sound that is used to help you relax or to meditate.
A “chakra” (chakra) is apparently one of several centers of what is called “spiritual thought” or energy in the body. Not exactly sure what all that means, but that’s the definition anyway, and it is something that is important in the practice of yoga. Victor says, “I learned breathing techniques.” A “technique” (technique) is a way of doing something, a method for doing something. “Breathing techniques,” then, would be techniques to help you breathe – probably in such a way that would allow you to relax – or to do some sort of exercise without, we would use the term, “getting winded.”
Singers and musicians often use breathing techniques to help them perform, to help them do what they want to do. In yoga, breathing techniques might be used as a form of relaxation – techniques to help you relax. Victor also says he “tried a few basic poses.” A “pose” (pose) is a position, and yoga has different positions that you put your body into as part of the practice of yoga.
Rosaria says, “That all sounds right from my own experience, such as it is.” That phrase “such as it is” is used to indicate that you don’t have very much experience in this area, for example. It could also be used to indicate that you realize what you just said may not be very useful or valuable to the person you’re talking to. It’s similar to another expression, “for what it’s worth.”
If you’re giving someone advice about something that you don’t know very much about (for me, for example, yoga) you would probably use a phrase such as this – “for what it’s worth” or “such as it is” – to indicate that you really don’t know what you’re talking about, which is typical for me. Rosaria says, “That all sounds right from my own experience, such as it is, but there are a lot of different types of yoga. Maybe you need to try a different kind” – a different kind of yoga.
Victor says, “The problem wasn’t the kind of yoga being practiced. It was the class.” The word “practice” here means participate or engage in something. So, Victor wasn’t concerned about the kind of yoga. He says, “The problem was the class.” Rosaria says, “Were the mats uncomfortable?” A “mat” (mat) here means a soft piece of material, usually rectangular in shape, that you put on the floor so you can do your exercises without touching the floor directly and without hurting yourself on the floor if the floor is hard.
In yoga it’s very common, I’m told, to use mats in the class. So, when you see people going to yoga classes here in Los Angeles, they’ll often be carrying a little mat. Victor says the mats were not uncomfortable. Rosaria says, “Was it” – meaning the class – “too cramped?” “Cramped” (cramped) here means crowded, when you have too many people in too small of a space. Victor says, “No.” Rosaria says, “Then what was the problem?” Victor says, “There was too much testosterone in the room.”
“Testosterone” is a hormone, a substance in your body that controls certain functions in your body, that is typically associated with males – with men. When people use the word “testosterone,” they’re usually referring to men, but men acting – how should I say it – very manly, being very tough. “I’m a man.” That sort of thing. Sort of John Wayne, if you remember who John Wayne was, the famous movie actor, or maybe Bruce Willis from Die Hard, right? He’s being very masculine, very male. We could talk about there being a lot of testosterone in that movie.
Well, that’s the problem Victor had with the yoga class, which is sort of funny because normally, at least here in Los Angeles, yoga is more associated with women. You’ll see women going to yoga classes a lot more often than men. But this was a class, according to Victor, that was just men. Rosaria says, “That was a problem?” She’s confused.
Victor then asks her a question that indicates the real problem he had with the class: “Do you think I would be taking a yoga class if I weren’t trying to meet women?!” You see, the reason Victor took the yoga class was to meet women, because in a typical yoga class, it’s mostly women who are there, and that was why Victor was taking the class. So, when the class was all men, he was of course disappointed.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Victor: Humph!
Rosaria: What’s the matter?
Victor: I just got back from my first yoga class and I was sorely disappointed.
Rosaria: I’ve heard that yoga is very good low-impact exercise and helps with stress relief. It’s supposed to calm the mind and strengthen the body.
Victor: Yeah, right.
Rosaria: It sounds like you had a bad experience. Did you have a bad teacher?
Victor: The teacher was fine. I learned about mantras and chakras, I learned breathing techniques, and I tried a few basic poses.
Rosaria: That all sounds right from my own experience, such as it is. But, there are a lot of different types of yoga. Maybe you need to try a different kind.
Victor: The problem wasn’t the kind of yoga being practiced. It was the class.
Rosaria: Were the mats uncomfortable?
Victor: No.
Rosaria: Was it too cramped?
Victor: No.
Rosaria: Then what was the problem?
Victor: There was too much testosterone in the room.
Rosaria: You mean you were in a class with just men?
Victor: Yeah.
Rosaria: And that was a problem?
Victor: Do you think I would be taking a yoga class if I weren’t trying to meet women?!
[end of dialogue]
We would sorely miss our scriptwriter if she didn’t continue to write our scripts. I speak of the wonderful Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2014 by the Center for Educational Development.
Glossary
yoga – an exercise for physical and mental health and relaxation that uses self-control of one’s breathing and thoughts while putting one’s body into certain postures (shapes)
* Yoga classes are a great way to improve flexibility and posture, as well as to improve one’s overall health.
sorely – very much; greatly
* They sorely underestimated how difficult it would be to find an apartment to rent in the city at the price they can afford.
low-impact exercise – a type of physical movement designed to increase health and strength without damaging one’s body, especially by avoiding hard, sudden movements that can have a negative impact on some part of one’s body
* If running hurts your knees, consider trying a low-impact exercise like swimming.
stress relief – a reduction in one’s feelings of anxiety and worry; lowering one’s tenseness
* The company brought exercise equipment into the office to encourage employees to seek stress relief through exercise.
to calm the mind – to make one stop worrying and stop having a lot of thoughts, so that one can be relaxed and peaceful
* Ahmed has a hard time calming his mind and falling asleep at night after a busy day at work.
to strengthen – to make something stronger; to make something able to bear (carry) more weight
* We could strengthen the wall by adding a few more supporting beams.
mantra – a sound, word, or phrased used while meditating or praying, especially during yoga
* “Ummm” is probably the mantra that’s most widely associated with yoga, but there are many other, more meaningful mantras.
chakra – one of several centers of spiritual thought or energy in the body
* Do you really believe that aligning the chakras in your body will help you achieve your goals and lead a more fulfilling life?
breathing technique – a way of controlling one’s breath for some purpose, usually for singing, playing a musical instrument, or for exercise or sport
* Most hospitals teach breathing techniques to pregnant women and their partners so that they can remain calm during childbirth.
pose – a way of positioning one’s body and holding it in that position temporarily
* How do the soldiers maintain that pose for such a long time without moving?
such as it is – for what it’s worth; to a certain degree; a phrase meaning that one recognizes that what one has just said may have little value or usefulness
* Here are my ideas for the new sales campaign, such as they are.
to practice – to engage or participate in some activity
* How often do you practice random acts of kindness?
mat – a soft, rectangular material placed on the floor so that one can do exercises without making direct content with the hard floor, and then rolled up so that it can be transported easily
* Remember to clean the exercise mat after each workout, or it will start to smell bad.
cramped – crowded; with a lot of people or things in a small space, not giving one as much room as one would like
* We can fit 150 people in this meeting room, but since it’s intended for only 120, it will be cramped.
testosterone – a hormone (substance in the human body that controls certain functions) involved in the production of the physical and behavioral characteristics of males
* Is it true that men with higher levels of testosterone are more aggressive and competitive?
Comprehension Questions
1. Which of these things is associated with strengthening the body?
a) Mantras.
b) Chakras.
c) Poses.
2. Which of these things was one of Rosaria’s guesses about why Victor didn’t like the class?
a) Too many participants were in the room.
b) The class was too expensive.
c) The other participants had more experience.
Answers at bottom.
What Else Does It Mean?
pose
The word “pose,” in this podcast, means a way of positioning one’s body and holding it in that position temporarily: “The painter asked the model to hold her pose for almost an hour so that he could capture the image.” The verb “to pose” sometimes means to exist in a problematic or dangerous way: “Transporting oil on trains poses many environmental risks.” The phrase “to pose as (someone)” means to pretend to be someone else in order to trick or fool other people: “For months, the police officers have been posing as gang members to try to get secret information from the gangs.” Finally, the phrase “to pose a question” means to ask a question, especially a more complex question: “After the presentation, audience members will have an opportunity to pose questions for the speaker.”
mat
In this podcast, the word “mat” means a soft, rectangular material placed on the floor so that one can do exercises without making direct content with the hard floor, and then rolled up so that it can be transported easily: “Wrestlers try to force their opponents down to the mat.” A “door mat” is a heavy rectangular piece of materials placed on the ground in front of a door so that people can clean their shoes before entering a room: “Please wipe your feet on the door mat before you come inside.” Finally, a “bath mat” is a piece of soft, absorbent material placed on the floor of the bathrooms to absorb water from the shower, bathtub, or sink: “The kids splashed so much water out of the tub during their bath that the bath mat was soaked.”
Culture Note
Fitness Trends
People who exercise often know that doing “the same old routine” (the same thing done the same way each time, without any excitement or interest) every day makes “workouts” (sessions of exercise) boring and difficult to “stick with” (continue to do). So they often try to “change things up” (change the way something has done to make it more interesting and exciting) by selecting a different type of workout.
And each year, some of these new forms of exercise “spread in popularity” (become popular among many people over a large area). These are often known as “fitness trends.” Here are two recent fitness trends.
Yoga has been popular in the United States for a long time, but the latest trend is “Stand-Up Paddleboard” or “SUP” yoga, where people perform traditional yoga poses while standing on a board that floats in the water, or a similar board that “simulates” (creates an environment similar to; imitates; copies) the movement of a floating board. SUP yoga requires even greater balance than traditional yoga, so major muscles are “engaged” (used) even more.
Another important fitness trend is “high-intensity interval training” or “H.I.I.T.” This type of exercise requires performing short but “intense” (involving a lot of energy, effort, and concentration) “bursts” (something that begins suddenly and lasts for a short period of time) of physical activity. “Advocates” (people who think something is a good idea and want others to do it) of H.I.I.T. argue that the exercise allows people to achieve greater health benefits in less time than they do with traditional exercise programs.
Comprehension Answers
1 - c
2 - a