= 1003
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast episode 1003 – Describing Duration.
This is English as a Second Language Podcast episode 1003. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is ESLPod.com. Become a member of ESL Podcast by going to our website. If you do, you can download an 8- to 10-page PDF guide to this episode called the “Learning Guide.”
This episode is a dialogue between Kathryn and Martin about describing how long things are. Let’s get started.
[start of dialogue]
Kathryn: Are you still watching that movie? It’s been over three hours!
Martin: Yeah, it’s a little long for a feature film.
Kathryn: A little long?! It’s interminable. How can you continue to watch it?
Martin: Well, the first half was interesting and moved at a clip. The middle section did drag a little, but it’s picked up again. It’s nearly over.
Kathryn: I would’ve turned it off long before this. I like movies that are short and sweet. After about 90 minutes, my mind starts to wander, and after two hours, I check out.
Martin: It depends on the movie. Sometimes I watch a movie and it’s so engrossing that time zips by. With other movies, though, time moves at a snail’s pace. This movie is somewhere in between.
Kathryn: Hey, the credits are rolling. You missed the ending.
Martin: No big loss. I knew how it was going to end after the first hour.
Kathryn: Then why did you stick it out and watch the rest of the movie?
Martin: One word: procrastination.
Kathryn: Ah, enough said.
[end of dialogue]
Kathryn begins the dialogue by asking Martin, “Are you still watching that movie? It’s been over three hours!” Martin says, “Yeah, it’s a little long for a feature film.” A “feature (feature) film” is a regular movie – the kind of movie you would go to a movie theater to see. Feature films are normally between 90 and perhaps 200 minutes. It depends on the movie, but somewhere between an hour and a half and two and a half hours, though sometimes movies are longer than that.
Kathryn says, “A little long?! It’s interminable.” Kathryn thinks this movie, which has been going for more than three hours now, is not just a little long – it’s really long. In fact, she calls it “interminable” (interminable). Something that is interminable goes on forever, or it seems to never end. I’ve been on some dates like that – when you go out with someone romantically, and the evening isn’t going very well, and then it seems interminable, like it’s never going to end. It does end eventually, however.
Kathryn says, “How can you continue to watch it?” How can you continue to watch this long movie? Martin says, “Well, the first half” – meaning the first 50 percent of the movie – “was interesting and moved at a clip.” “To move at a clip” (clip), or “to move along at a clip,” means to advance very quickly, to move very rapidly. If a movie is moving quickly, a lot of things are happening in the movie.
The middle section of the movie, according to Martin, “did drag a little, but it’s picked up again.” “To drag” (drag) means to go very slowly, too slowly – so slow that it is a little boring. Martin says the movie has “picked up again.” “To pick (pick) up” is a phrasal verb meaning to increase in speed, to start to go faster. Martin says the movie is “nearly over,” meaning it’s almost over. “It’s nearly (nearly) over.”
Kathryn says, “I would’ve turned it off long before this.” Kathryn means that if she had been watching the movie, she would have turned the movie off a long time ago. She would not have continued watching it for this long. She says, “I like movies that are short and sweet.” The expression “to be short and sweet” means to not take very long and to be pleasant. Usually we use this expression “short and sweet” when we want someone to get to the point right away, or to not go on for very long. “Let’s keep this short and sweet,” meaning let’s do this very quickly and not waste a lot of time.
Kathryn says, “After about 90 minutes, my mind starts to wander, and after two hours, I check out.” If you say your mind “starts to wander” (wander), you mean that you cannot concentrate or focus on something. Your mind begins to think of other things. If you are sitting in a meeting at work, and the person who’s speaking is very boring or is going on for a very long time, your mind might start to wander. You might start thinking about what you’re going to have for dinner that night or where you’re going to go on vacation next summer. You’re not focusing or concentrating on what you are supposed to be focusing on.
Kathryn says after two hours of watching a movie, she checks out. “To check (check) out” is a two-word phrasal verb meaning to stop paying attention to something, to no longer focus on what you’re supposed to focus on. Martin says, for him, “It depends on the movie. Sometimes I watch a movie and it’s so engrossing that time zips by.” “To be engrossing” (engrossing) means to be very interesting, to be so interesting that you can’t focus on anything else. If you’re reading an engrossing novel, you don’t want to put it down.
Often, when you are really interested in something, you go into what psychologists sometimes described as a “state of flow” (flow). “To be in flow” means to be so completely focused and concentrated on something that you don’t realize how much time you’re spending on it. That’s why Martin says that if the movie is engrossing, “time zips by.” “To zip (zip) by” means to go very quickly. A more common expression would be “time flies.” There’s an expression, “Time flies when you’re having fun,” and that’s exactly what we’re talking about here.
Martin says, “With other movies, though, time moves at a snail’s pace.” The opposite of time flying by or zipping by is for it to move at a “snail’s (snail’s) pace (pace).” The “pace” of something is how fast or slow it’s going. A “snail” is a small animal that moves very, very slowly. If you say something is moving at a “snail’s pace,” you mean it is moving very slowly.
Martin says this movie – the movie he’s watching now – is somewhere in between. If something is “somewhere in between,” it is in the middle. It is not at one end or the other. In this case, it isn’t moving very quickly, but it isn’t moving very slowly, either. Kathryn says, “Hey, the credits are rolling.” At the end of a movie, there are typically a few minutes where they tell you who participated in the movie – who the actors were, who the director was, and so forth. These are called the “credits” (credits). To say “the credits are rolling” means the credits are showing on the screen.
Kathryn says, “You missed the ending.” The “ending” is the very end of the movie. Martin doesn’t seem too concerned. He says, “No big loss.” That expression, “no big loss,” is an informal one that means that it isn’t a very important. You don’t need to worry about it. Martin says, “I knew how it” – the movie – “was going to end after the first hour.” Kathryn asks, “Then why did you stick it out and watch the rest of the movie?” “To stick something out” is a phrasal verb meaning to not give up, to continue doing something even though it might be difficult.
Kathryn wants to know why, if Martin knew the end of the movie after the first hour, he continued to watch it. Martin says, “One word: procrastination.” “Procrastination” (procrastination) is when you wait to do something later instead of doing it now. We might also use the phrasal verb “to put off” something. “Never do today what you can put off until tomorrow.” That means don’t do anything today that you can wait and do tomorrow. To wait to do things – usually because you’re lazy or you don’t want to work very hard – is called “procrastination.”
Kathryn understands completely what Martin is saying here. She says, “Ah, enough said.” When you say, “enough said,” you’re indicating that you understand completely what the other person is telling you, so much so that the other person doesn’t have to finish explaining it. You already understand what they’re saying. You’re saying to the person, “You don’t need to say any more. You don’t need to explain anything else. I understand it. I get it.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Kathryn: Are you still watching that movie? It’s been over three hours!
Martin: Yeah, it’s a little long for a feature film.
Kathryn: A little long?! It’s interminable. How can you continue to watch it?
Martin: Well, the first half was interesting and moved at a clip. The middle section did drag a little, but it’s picked up again. It’s nearly over.
Kathryn: I would’ve turned it off long before this. I like movies that are short and sweet. After about 90 minutes, my mind starts to wander, and after two hours, I check out.
Martin: It depends on the movie. Sometimes I watch a movie and it’s so engrossing that time zips by. With other movies, though, time moves at a snail’s pace. This movie is somewhere in between.
Kathryn: Hey, the credits are rolling. You missed the ending.
Martin: No big loss. I knew how it was going to end after the first hour.
Kathryn: Then why did you stick it out and watch the rest of the movie?
Martin: One word: procrastination.
Kathryn: Ah, enough said.
[end of dialogue]
We would like to thank Dr. Lucy Tse for her always-engrossing scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
feature film – a full-length movie, usually between 70 and 210 minutes long
* The theater showed six previews before the feature film began.
interminable – seemingly unending; boring and lasting a very long time
* The drive was interminable on the busy freeways, but we finally got back home.
to move at a clip – to advance very quickly; to move rapidly
* The soldiers were ordered to move at a clip.
to drag – to move or advance slowly; to seem to move slowly because something is boring or uninteresting
* The meetings used to drag, but then our manager decided that nobody would be allowed to sit down. Now everyone wants the meetings to be as short as possible, because they don’t want remaining standing for a long time.
to pick up – to increase the speed or rhythm of something; to increase noticeably
* Business really picked up after the holidays.
short and sweet – not taking very long, and being pleasant and enjoyable
* This book is short and sweet. You can probably read it in one sitting.
(one’s) mind starts to wander – one loses concentration and begins daydreaming or thinking about something else, not what one should be focusing on
* As Brett looked out the window of his office, his mind started to wander to his plans for the weekend.
to check out – to stop paying attention to something; to no longer focus on what one is supposed to be concentrating on
* The students all look bored. I think most of them checked out a few minutes after the professor started speaking.
engrossing – very interesting, demanding one’s full attention and involvement
* Jenna finds her work in the lab so engrossing that she often forgets to eat lunch.
to zip by – to proceed very quickly; for something to appear to occur quickly and for time to pass quickly
* Their one week vacation zipped by, but they had a great time.
to move at a snail’s pace – to go very slowly, almost seeming to have stopped
* The kids move at a snail’s pace when they’re supposed to be putting on their pajamas and brushing their teeth to go to bed.
somewhere in between – in the middle; between two extremes; not at one end or the other when referring to a range of things
* Khalid’s older brother always got perfect grades and his younger brother almost failed, but he was somewhere in between.
the credits are rolling – a phase used to describe the text that appears on the screen at the beginning and/or end of a movie or TV show, listing the name of people who helped to create the movie or TV show, such as the producer and the director
* At the end of a movie, most people get up and start to leave when the credits are rolling, but Jacques likes to wait until the very end of a film.
no big loss – an informal phrase meaning that something is unimportant and that one does not regret it or feel bad about it
* When the toy broke, it was no big loss, because she has several others.
to stick (something) out – to be persistent and not give up; to continue seeing or doing something all the way to the end, especially when doing so is challenging
* Medical school is difficult, but if you stick it out, it’s all worth it.
procrastination – the act of waiting to do something later instead of doing it now; the act of putting something off or waiting until the last minute to complete it
* Procrastination is one of the worst habits of many college students. They wait until the night before an exam to begin studying for it.
enough said – a phrase used to show that one understands another person’s idea even though he or she has not finished explaining it fully
* A: The dinner party is going to include a lot of our married friends.
B: Enough said. I understand. You don’t want me there because I’m single.
Comprehension Questions
1. What did Kathryn mean when she says, “After two hours, I check out.”
a) She isn’t able to concentrate on the movie.
b) She falls asleep by accident.
c) She prefers renting long movies over buying them.
2. Why did Martin watch the entire movie?
a) Because he is lazy and didn’t want to get off the couch.
b) Because he was waiting to do the things he was supposed to do.
c) Because he is studying to become a filmmaker.
Answers at bottom.
What Else Does It Mean?
to drag
The verb “to drag,” in this podcast, means to move or advance slowly: “Time drags when waiting in a long line to get service.” The verb “to drag” also means to pull something behind oneself as it rests on the ground: “You’ll ruin your jacket if you keep dragging it on the ground like that.” The phrase “to drag (oneself) away from something” means to make a great effort to stop doing something that one would like to continue doing: “Can you drag yourself away from the computer screen long enough to have dinner with the family?” Finally, the phrase “to drag (someone) down” means to make someone feel very sad and depressed: “Trenton seems to be dragged down by his divorce.”
to zip by
In this podcast, the phrase “to zip by” means to proceed very quickly or to appear to happen very fast: “She couldn’t believe her daughter was graduating from college. Her childhood seemed to have zipped by.” The phrase “to zip (something) open/shut” means to open or close a bag by moving the zipper around the edge: “Shane had to sit on the suitcase in order to zip it shut.” The informal phrases “zip it” and “zip your lips” are used to tell someone to be quiet and not share secret information: “This is top-secret information, so zip your lips!” Finally, the phrase “to zip up” means to hold two pieces of fabric together with a zipper: “Could you please help me zip up my jacket?”
Culture Note
Intermission
“Intermission” is a short “break” or “recess” during a long play, opera, or concert. It gives the audience members an opportunity to “stretch their legs” (move around and walk after sitting for a long period of time), “relieve themselves” (use the bathroom), and “find refreshments” (eat and drink). In a “live show” (a show with living actors, not a performance that has been recorded), intermission gives the performers a chance to rest and prepare for the next “scene” (one part of a longer performance) while the “stagehands” (people whose job is to help set up a performance stage) move the “props” (the objects that performers interact with one stage).
Intermissions are “generally” (usually) highly “profitable” (making a lot of money) for theaters and performance halls. Audience members go to the “concession stands” (small areas where food and drink are sold) inside the theater, where “finger foods” (snack-like foods that can be eaten with one’s hands, without silverware) are sold, usually at high prices. Theaters with bars make even more money by selling beer, wine, and other alcoholic beverages to theater “patrons” (people who support an activity by attending it or giving money to it).
In the past, long movies used to have intermissions, because the theaters needed time to “change the reels”: When films were recorded on long strips, they were “wound around” (stored in a circle around another object) “reels” (large wheel-shaped objects), and when the film on one reel had been seen, the theater employees needed to remove one reel to place the next reel on the “projector” (the machine that uses light to put an image on a wall or screen).
Comprehension Answers
1 - a
2 - b