= 1029
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,029 – Types of Vandalism.
This is English as a Second Language Podcast episode 1,029. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Become a member of ESL Podcast and download a Learning Guide for this and all of our current episodes. You can also like us on Facebook at facebook.com/eslpod. This episode is a dialogue about vandalism – when someone does something to damage someone else’s property. Let’s get started.
[start of dialogue]
Jim: Did you hear what happened to the Romeros?
Helene: No, what?
Jim: They went on vacation for a week and vandals broke a couple of windows in the back of their house and tagged their living room walls with graffiti.
Helene: That’s terrible! There are always punks who like to egg houses in this neighborhood for fun, but this is much more serious.
Jim: I think things are getting out of hand. Every week or two, we hear of incidents of people having their tires slashed or their cars keyed.
Helene: And the Jamisons had their flowerbeds trampled and a small fire set on their lawn three weeks ago. This neighborhood is really going downhill.
Jim: What should we do about it?
Helene: What do you mean?
Jim: I think we should start patrolling the streets at night.
Helene: You mean organize a neighborhood watch? Wouldn’t that be dangerous?
Jim: If you’re worried, when you see something suspicious, call the police.
Helene: And you think they’ll come in time to catch them? The police aren’t known for quick response times in this neighborhood.
Jim: Then we’ll go after them ourselves.
Helene: You mean be vigilantes? I’m not sure that would be wise.
Jim: Why not? If Clint Eastwood can do it, so can I. Go ahead, punk, make my day!
[end of dialogue]
Our dialogue begins with Jim saying to Helene, “Did you hear what happened to the Romeros?” The “Romeros” refers to a family with the last name of “Romero.” Notice we put an “s” at the end. That’s very common if you are referring to an entire family. So, my family might be referred to as the “McQuillans,” with an “s” at the end. You could also say “the McQuillan family.”
Helene says, “No, what?” What happened? Jim says, “They went on vacation for a week and vandals broke a couple of windows in the back of their house and tagged their living room walls with graffiti. The Romeros went on a vacation, and while they were gone, “vandals broke a couple of windows.” A “vandal” (vandal) is a criminal who destroys or damages someone’s property, something that belongs to someone else.
These vandals broke a couple of windows in the back of the Romeros’ house and “tagged” their living room walls with graffiti. “To tag” (tag) here refers to painting your name or your organization’s name or symbol on a wall. This is something that, unfortunately, you see a lot in big cities all around the world, usually young men who go around with paint cans and put their name – or, often, strange symbols – on public walls or the walls of buildings.
“Graffiti” (graffiti) refers to either writing or drawing that is placed illegally or without permission on someone’s wall. It could be also on someone’s vehicle – on your car, for example. Helene says, “That’s terrible. There are always punks who like to egg houses in this neighborhood for fun, but this is much more serious.”
The word “punk” (punk) here refers to a young person – again, often young men or young boys who break the law and do other things to bother people around them. It’s a negative way of describing someone. “Punk” also refers, of course, to a kind of music from the late 1970s, when I was in high school.
Helene says, “There are always punks who like to egg houses.” “To egg” (egg) means to throw eggs at a building. You’re obviously throwing raw eggs – eggs that have not been cooked – and of course, if you throw an egg against the wall, it’s going to break and make a mess. So, the verb “to egg” means to throw eggs, but not in a good way (although I’m not sure if there is a good way to throw eggs at something) but rather in order to create a mess and to damage the wall.
Sometimes, not that often, young people as a joke will egg someone’s house. It’s a very bad thing to do. The other thing that young people do sometimes – although I, of course, have never done this – is to TP someone’s house. “To TP” means to take toilet paper – which is also called “TP paper” – and throw it on someone’s house, or often on a tree or a bush around someone’s house. Helene says this is much more serious than just egging someone’s house, because they actually broke into the house.
Jim says, “I think things are getting out of hand.” The expression “to get out of hand” means to become out of control or to become a serious problem. We use this expression when a situation seems to be slowly getting worse until such a point where the problem becomes serious. Jim says, “Every week or two, we hear of incidents of people having their tires slashed or their cars keyed.” An “incident” is a case of, an event.
In this case, we’re talking about cases of people having their tires “slashed.” “To have your tires slashed” (slashed) is to have someone take a knife or some sharp object and punch a hole in your tire so that you don’t have any air left in your tire. “To key (key) someone’s car” is to take a key, any key, and walk along the side of the car and scrape the paint off of the car. Of course, both slashing tires and keying cars would damage a car. It’s certainly not something nice to do. You are, in fact, ruining the property of the person.
Helene says, “And the Jamisons had their flowerbeds trampled and a small fire set on their lawn three weeks ago.” A “flower bed” is an area in your lawn or in your garden where there are flowers. “To trample” (trample) means to step on something, especially a plant, and in doing so kill the plant or at least flatten the plant so that it is no longer sticking up out of the ground.
Helene continues, “This neighborhood is really going downhill.” The expression “to go downhill” (downhill) means to become worse. When you’re talking about a situation going downhill, you are referring to a situation that is becoming worse, that is deteriorating. “To deteriorate” means the same as to go downhill – to become worse. Jim then asks, “What should we do about it?” Helene says, “What do you mean?”
Jim says, “I think we should start patrolling the streets at night.” “To patrol” (patrol) means to either walk or drive around an area to make sure that no one is causing any problems – to look for dangerous or illegal activities. Normally, we talk about the police patrolling an area to make sure that it is safe. In fact, we call the cars that police drive around “patrol cars” because they are out patrolling. They’re out looking to make sure that the area is safe. Jim is suggesting that they start patrolling the streets at night.
Helene says, “You mean organize a neighborhood watch?” A “neighborhood” is an area within a city. “To watch,” of course, means to look at, to see. A “neighborhood watch,” however, is a group of people in a certain neighborhood that agree to pay attention, if nothing else, to the area in which they live, and if they see anything that looks wrong – that might be illegal or suspicious – they call the police.
A lot of big American cities have organizations called “neighborhood watches” that basically try to make everyone in the neighborhood aware of who lives there and who doesn’t and to report any problems immediately to the police. I mentioned that you look for things that are suspicious, and that’s exactly what Jim is talking about. Jim says, “If you’re worried, when you see something suspicious, call the police.” “Suspicious” (suspicious) is something that makes you think that it may be illegal or harmful, even though you’re not exactly sure.
Helene says, “And you think they’ll come in time to catch them?” Helene doubts that the police would arrive in time in order to arrest or investigate any problems that she reports. Helene says, “The police aren’t known for quick response times in this neighborhood.” A “response time” would be the amount of time needed for someone to react to something, especially when we’re talking about the time from which you make a request for police or an ambulance and the time that the police or the ambulance arrives at your house. That would be the response time.
Jim says, “Then we’ll go after them ourselves.” “To go after” someone is a phrasal verb meaning to run after or to pursue someone with the idea of catching the person and holding them and perhaps even punishing them. “To go after,” more generally, can mean to attack. But here, it really means to run after a person and try to catch that person. Helene says, “You mean be vigilantes? I’m not sure that would be wise.”
Helene doesn’t think it’s wise or a good idea to become “vigilantes.” A “vigilante” (vigilante) is someone who is not a member of the police who tries to catch and punish criminals even though the person doesn’t have the legal authority to do that. Jim says, “Why not?” meaning why shouldn’t we become vigilantes? “If Clint Eastwood can do it, so can I.” Clint Eastwood, as some of you may remember, starred in some movies where he played a vigilante. These were movies back in the 1970s. I’m thinking especially of the movie called, in English, Dirty Harry.
Jim finishes our dialogue by using one of the expressions, the famous lines, from the Clint Eastwood movie: “Go ahead, punk, make my day!” When you say “go ahead,” you are inviting the other person to do something, but sometimes you’re saying it when you don’t really want the person to do something but you’re not going to stop the person from doing it if he wants to. The expression “make my day” is used to challenge someone to a fight.
So, if I have a gun, and you want to punch me with your fist, I may say, “Go ahead, make my day,” meaning if you punch me, I will, in this case, shoot you with my gun. “Make my day” normally means to make you happy, to do something that makes your day better, but obviously we’re using it here in a somewhat different way. We’re saying that the opportunity to punish you would make me happy – and that, of course, is the way a vigilante might feel, since a vigilante is trying to punish criminals even though he doesn’t have the authority to do so.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Jim: Did you hear what happened to the Romeros?
Helene: No, what?
Jim: They went on vacation for a week and vandals broke a couple of windows in the back of their house and tagged their living room walls with graffiti.
Helene: That’s terrible! There are always punks who like to egg houses in this neighborhood for fun, but this is much more serious.
Jim: I think things are getting out of hand. Every week or two, we hear of incidents of people having their tires slashed or their cars keyed.
Helene: And the Jamisons had their flowerbeds trampled and a small fire set on their lawn three weeks ago. This neighborhood is really going downhill.
Jim: What should we do about it?
Helene: What do you mean?
Jim: I think we should start patrolling the streets at night.
Helene: You mean organize a neighborhood watch? Wouldn’t that be dangerous?
Jim: If you’re worried, when you see something suspicious, call the police.
Helene: And you think they’ll come in time to catch them? The police aren’t known for quick response times in this neighborhood.
Jim: Then we’ll go after them ourselves.
Helene: You mean be vigilantes? I’m not sure that would be wise.
Jim: Why not? If Clint Eastwood can do it, so can I. Go ahead, punk, make my day!
[end of dialogue]
There’s nothing suspicious or illegal about our scripts (I hope). That’s because they’re written by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
vandal – a criminal who destroys or damages public property, or private property that belongs to other people
* Some vandal knocked over our mailbox last night.
to tag – to paint the name of a person or organization on a wall or similar surface illegally
* Rival gangs are competing to see which one can tag more buildings.
graffiti – large, colorful paintings, sometimes with words, placed on walls, buildings, and vehicles illegally by people who do not own the property
* The students were suspended for putting graffiti in the school bathrooms.
punk – a rebellious young person who breaks the law and does other things that people dislike
* I don’t care if you dress like a punk, but don’t pierce your nose or do anything else that’s permanent.
to egg – to throw raw eggs at a building or vehicle that belongs to someone else, so that they break open and make a mess
* The teenagers thought it would be funny to egg their teacher’s house on Halloween night.
to get out of hand – to become out of control and become a problem, especially if something started gradually and continues to worsen
* We don’t mind if employees occasionally check their email at work, but lately, their personal use of computers has been getting out of hand.
to have (one’s) tires slashed – for the wheels of one’s car to be cut with a knife so that the air is let out and the car cannot be driven
* They left their car on the street in a bad neighborhood for just a few minutes, but when they got back, they found that their tires had been slashed.
to key a car – to scrape away some of the exterior paint on the side of a car in order to cause damage
* Someone keyed our car while we were grocery shopping. Do you think we’d be able to see who did it on the store’s surveillance video?
to trample – to step on something repeatedly and heavily so that it is flat, especially a plant
* The deer ate all the lettuce and trampled the carrots in our garden.
to go downhill – to deteriorate; to become worse
* Our sales are going downhill. How can we find new customers?
to patrol – to walk or drive through an area to observe what is happening and look for dangerous or illegal activities
* In response to the increased crime rate, more police officers are patrolling the area at night.
neighborhood watch – a group of people who agree to work together to watch and pay attention to what is happening to improve the safety and security of the area where they live, calling the police when necessary
* A well-organized neighborhood watch has a list of the email addresses and phone numbers of everyone who lives in the area, as well as information about when people are going to be out of town.
suspicious – making one think that something illegal or harmful is happening, even though one does not actually have proof
* Who ate the cookies? Your breath smells like chocolate, and that makes me suspicious.
response time – the amount of time needed for someone to react to something, especially the amount of time that passes between when a request is made for emergency assistance and when the ambulance or police car arrives
* It’s hard for ambulances to have a good response time when there is so much traffic on the roads.
to go after – to pursue or chase and try to catch someone
* The police went after the shoplifter, but they weren’t able to catch her.
vigilante – a civilian (not a member of the military or the police force) who tries to catch and punish criminals without the legal authority to do so
* The border towns have vigilantes who volunteer to look for illegal immigrants.
go ahead – an invitation for someone to do something, often used sarcastically when one does not really want someone to do something, but will not do anything to stop that person from doing it
* Go ahead and drive without insurance. See what happens.
make my day – a phrase used to challenge someone to a physical fight when one believes one will win the fight
* Do you want to fight? Try to punch me. Make my day.
Comprehension Questions
1. What happened to the Jamisons’ flowerbeds?
a) The flowers and other plants were ripped out of the ground.
b) The flowers and other plants were stolen.
c) The flowers and other plants were stepped on repeatedly.
2. What does Helene mean when she says, “The police aren’t known for quick response times in this neighborhood”?
a) It takes the police too long to arrest criminals.
b) It takes the police too long to investigate a crime.
c) It takes the police too long to arrive at the site of a crime.
Answers at bottom.
What Else Does It Mean?
to egg
The verb “to egg,” in this podcast, means to throw raw eggs at a building or vehicle that belongs to someone else, so that they break open and make a sticky mess: “Egging a house in the winter is bad enough, but egging a house in the summer is even worse, because then the yolks cook onto the surfaces in the sunshine.” The phrase “to egg (someone) on” means to encourage someone to do something, especially something that he or she should not do: “All the other kids were egging him on, telling him to steal the answers to the test from the teacher’s desk.” Finally, the phrase “to have egg on (one’s) face” means to be embarrassed and appear foolish or stupid: “The politician had egg on her face when the newspapers reported that she lied about her education.”
to go after
In this podcast, the phrase “to go after” means to pursue or chase and try to catch someone: “Quick! Go after that thief!” The phrase “to go after” also means to pursue one’s goals or dreams: “His aunt encouraged him to go after his dream of becoming an astronaut.” The phrase “to go before” means to precede, or to happen before something else: “We are indebted to the hundreds of researchers who have gone before us.” The phrase “to go before (someone)” can mean to be considered or evaluated by decision-makers: “This proposal will go before the committee next week.” Finally, the phrase “to go along with (someone)” means to agree with someone and do what he or she wants: “Whatever happens, just go along with me and pretend it was all part of our plan.”
Culture Note
Killroy Was Here
The phrase “Killroy was here” is an “expression” (something that is said commonly by many people) that became popular during the Second World War. The phase is “printed” (written by hand) underneath a simple drawing of a “bald” (without hair) man with a long nose and the fingers of each hand hanging over a wall, but sometimes the man is drawn with a few hairs. It looks like someone is “peeking” (trying to see something briefly) over a wall.
Nobody knows exactly where or how the drawing originated, although many think it was created and “popularize” (made popular) by U.S. “servicemen” (men who are serving in the military). They often left “Killroy was here” images on walls, camps, toilets, and more. However, other people say that a similar Australian image, “Foo was here” “predates” (comes before; appeared earlier than) “Killroy was here” and was in use during the First World War. Today, similar drawings are found it many different countries under different names, such as “Chad” in the United Kingdom and “Julito” in Peru.
Some people “interpret” (understand the meaning of something in a particular way) the image as representing “omniscience,” or the ability to know everything. As Killroy peeks over the wall, he may be seeing things that would otherwise be hidden. But other people just find the image entertaining and enjoy putting it in “surprising” (unexpected) places. It is often found in graffiti, such as in train stations and schools. In most “instances” (occurrences) it is considered to be “humorous” (funny) and “harmless” (not causing damage or hurt).
Comprehension Answers
1 - c
2 - c