= 1045
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast episode 1,045 – Being Infatuated with Someone.
This is English as a Second Language Podcast episode 1,045. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. Take a look at our ESL Podcast Blog that has additional free lessons in English every week. You can also like us on Facebook at facebook.com/eslpod. And hey – why not follow us on Twitter? Our Twitter handle is @eslpod, of course.
This episode is a dialogue between Marcel and Fiona about someone who is infatuated with another person. Let’s get started.
[start of dialogue]
Marcel: What is this on your wall?
Fiona: It’s my tribute to Del Gordon, my favorite player.
Marcel: This isn’t a tribute. It’s a shrine!
Fiona: It’s not a shrine. I just have a few pictures of him taped on my wall.
Marcel: You have poster-size pictures of him covering three walls of your room. This goes beyond being a fan. You’re obsessed with him.
Fiona: No, I’m not obsessed. I admit that I’m a little infatuated with him, but it’s a healthy kind of adulation.
Marcel: You’ve definitely gotten carried away.
Fiona: Just a little. I’m devoted to watching him play in every game and I try to find out as much as I can about him, but it’s because I admire him. It’s not like I’m stalking him or something.
Marcel: Then why do you have all of this equipment?
Fiona: That’s in case there’s a sighting of him in this city.
Marcel: A sighting?
Fiona: Yes, there’s a network of fans that keeps tabs on him, and if I learn that he’s in town, I can try to get a photo with him.
Marcel: And what are those handcuffs for?
Fiona: I only have those in case he doesn’t cooperate.
Marcel: You’re right. Your infatuation is completely healthy!
[end of dialogue]
Marcel begins our dialogue by asking Fiona, “What is this on your wall?” Fiona has something hanging on her wall, something attached to her wall. Fiona says, “It’s my tribute to Del Gordon, my favorite player. Del Gordon appears to be an athlete of some sort. Fiona says it’s her “tribute to Del Gordon.” A “tribute” is something that you do or say that shows that you honor and respect another person. It could be a speech that you give to a group of people. It could be a party that you have in honor of this person. In the case of Fiona, it’s something that she has on her wall.
Marcel says, “This isn’t a tribute. It’s a shrine!” A “shrine” (shrine) is normally considered a holy place, a place of prayer where people worship God. So, to call this a “shrine” means that it is more than just a simple little photograph or tribute of some sort – it is instead something bigger, something that it looks like it could be a shrine. People do sometimes have small shrines in their homes for religious reasons, but this is not something religious; this is what we might call an “infatuation,” which I’ll define in a minute.
Fiona says, “It’s not a shrine. I just have a few pictures of him taped on my wall.” They’re attached to her wall – probably not by tape, although they might be. Marcel says, “You have poster-size pictures of him covering three walls of your room.” A “poster” (poster) is a large piece of paper, typically, that is used to advertise a movie or perhaps a rock band or even a sports star. People often have posters – especially young people – in their rooms of their favorite athlete or musician or actor.
Posters can be quite large – usually two- or three-feet tall – and that’s what Marcel is referring to when he says that Fiona has “poster-size pictures,” meaning the photographs are as big as posters. “This goes beyond being a fan,” Marcel says, “You’re obsessed with him.” A “fan” (fan) is someone who likes an athlete, musician, actor, or perhaps a type of sport or a type of music or even a podcast. (Why not?)
Marcel says that Fiona is obsessed with Del Gordon. “To be obsessed” (obsessed) means that you are only able to think about one thing. The adjective is “obsessive.” Someone who is obsessive is always thinking about one thing. Sometimes this can be an indication of some sort of mental illness. Here, it refers to Fiona’s love of this particular athlete. She’s obsessed with this athlete. She can’t think of anything else.
Fiona says, “No, I’m not obsessed.” She disagrees with Marcel. She says, “I admit that I’m a little infatuated with him, but it’s a healthy kind of adulation.” She says “I admit,” meaning I will confess or I will say something that is true, even though it isn’t something I may be proud of. She says she’s a little “infatuated” with Gordon. “To be infatuated (infatuated) with” someone is to basically be in love with this person, but usually only for a short time.
When you are attracted to, for example, a beautiful woman or a handsome man, you might become infatuated with that person. You may think of nothing but that person and think that perhaps you are even in love with that person, even if you’ve only seen them on the street. That happens to everyone, I suppose (not after you get married, though).
Fiona is infatuated with Del Gordon, but she says “it’s a healthy kind of “adulation.” “Adulation” (adulation) is showing a lot of love and admiration for someone or for something, usually to an extreme extent. You’re doing it too much. Marcel says, “You’ve definitely gotten carried away.” “To get carried away” means to do too much of something, anything.
You could get carried away with exercising. You could go to the gym four hours every day – unless you’re a professional athlete, that’s probably getting carried away. That’s what has happened to Fiona. She’s gotten carried away with her love of Del Gordon, her favorite player. Fiona says, “Just a little,” meaning she’s only gotten a little carried away.
“I’m devoted to watching him play in every game, and I try to find out as much as I can about him, but it’s because I admire him.” Fiona says she’s “devoted” (devoted). “To be devoted to” something means that you are strongly committed to this person or this thing, almost with feelings of love for whatever the activity is. The activity here is watching Del Gordon play in every game. That’s what Fiona is devoted to.
She says that she “admires” him. “To admire” (admire) is to think that someone or something is very good and deserves a lot of respect. You can admire a person without being in love with them, of course, or even being infatuated with them. You can admire a politician, although I’m not sure why you would, but you could. You could admire a leader of a company or a religious group. Lots of possibilities. Therefore, “admiration,” which is the noun that comes from the verb “to admire.”
Next Fiona says, “It’s not like I’m stalking him or something.” “It’s not like” means this is not what I am doing. I am not stalking him. “To stalk” (stalk) someone is to follow someone in a secret, hidden way that is usually considered dangerous. Perhaps you want to hurt the person. Perhaps you even want to kill the person.
We have stalkers of celebrities here in Los Angeles – people who follow celebrities, famous people, around. This is, depending on how you do it, potentially illegal, and you could get arrested for following someone around, especially if it seems as though you might do something hurtful or damaging to that person. But Fiona says she’s not stalking Del Gordon. Marcel says, “Then why do you have all of this equipment?” We’re not sure what equipment Marcel is referring to.
Fiona says, “That’s in case there is a sighting of him in this city.” “In case” means if something happens, in this particular situation. A “sighting” (sighting) is when you see someone or something, often something that is very rare. Here in L.A., people talk about “star sightings” – seeing famous celebrities, famous people. Have I seen famous people here in Los Angeles? Sure. You see them at the grocery store. You see them at the mall. You see them on the street. If you live in the city of Los Angeles, you’re going to see some famous people eventually.
Marcel then asks, “A sighting?” Fiona says, “Yes, there’s a network of fans that keeps tabs on him, and if I learn that he is in town, I can try to get a photo with him.” A “network” is a group of people who are all connected in some way and who are communicating with each other. A “network” can also refer to a group of computers that are connected to each other for some common purpose. The phrase “to keep tabs (tabs) on” someone means to know the location of someone – to know where someone is or what they are doing.
Fiona says there are people in this network of fans who keep tabs on Del Gordon. If Fiona learns that her favorite athlete is “in town,” meaning in the city right now, she can try to get a photo with him. Notice we say “in town” when someone is physically present in the city where you are. The opposite would be “out of town.” If you are “out of town,” you are not in the city where you are normally – the place where you live, say.
Marcel says, “And what are those handcuffs for?” “Handcuffs” (handcuffs) are two metal rings that go around your wrists. The rings are attached by a short chain. Police use handcuffs in order to arrest someone, to make sure the person doesn’t try to escape. Fiona has a pair of handcuffs. Why? She says, “I only have those in case he doesn’t cooperate.”
In other words, she has these handcuffs in case she sees her favorite player and asks the favorite player for a photograph and the player says no. If that happens, then she can put handcuffs around him and make him take a photograph with her. Of course, this is not something you can do. It’s illegal to do that sort of thing. And it’s also a sign that Fiona really is obsessed with this person.
Marcel says sarcastically – jokingly – “You’re right. Your infatuation is completely healthy,” meaning there’s nothing wrong with this infatuation with this person. He means, of course, just the opposite. You can tell by the way he says it that he’s being sarcastic. He’s joking. “Sarcasm” means saying one thing but meaning another in order to make a joke.
Now let’s listen to the dialogue, this time at a normal speed
[start of dialogue]
Marcel: What is this on your wall?
Fiona: It’s my tribute to Del Gordon, my favorite player.
Marcel: This isn’t a tribute. It’s a shrine!
Fiona: It’s not a shrine. I just have a few pictures of him taped on my wall.
Marcel: You have poster-size pictures of him covering three walls of your room. This goes beyond being a fan. You’re obsessed with him.
Fiona: No, I’m not obsessed. I admit that I’m a little infatuated with him, but it’s a healthy kind of adulation.
Marcel: You’ve definitely gotten carried away.
Fiona: Just a little. I’m devoted to watching him play in every game, and I try to find out as much as I can about him, but it’s because I admire him. It’s not like I’m stalking him or something.
Marcel: Then why do you have all of this equipment?
Fiona: That’s in case there’s a sighting of him in this city.
Marcel: A sighting?
Fiona: Yes, there’s a network of fans that keeps tabs on him, and if I learn that he’s in town, I can try to get a photo with him.
Marcel: And what are those handcuffs for?
Fiona: I only have those in case he doesn’t cooperate.
Marcel: You’re right. Your infatuation is completely healthy!
[end of dialogue]
We all admire the wonderful scriptwriter of ESL Podcast, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2014 by the Center for Educational Development.
Glossary
tribute – something that one does or says to demonstrate honor and respect for another person
* The city erected a statue as a tribute to the men and women who died in the war.
shrine – a place that people visit to worship God or a holy event or person
* In some cultures, it’s common for families to have a small shrine in part of their home.
poster-size – the size of a large piece of paper that is put on a wall for decoration, usually the size of at least four regular pieces of paper placed next to each other
* The optometrist has a poster-size chart with letters, and patients have to say which letters they can read without the help of corrective lenses.
fan – someone who likes an athlete, musician, actor, type of sport, or type of music very much and regularly participates in related activities
* Adam is a huge soccer fan who always goes to see games at the stadium.
obsessed – able to think about only one thing; overly interested in one thing
* James is obsessed with making the world’s most delicious barbeque ribs.
infatuated – in love with someone intensely, but usually for a short time; to be very attracted to an idea for a short time
* Gregorio is infatuated with Heidi, but he still hasn’t figured out how to ask her out on a date.
adulation – showing too much love and admiration for someone or something
* Don’t get used to all that adulation. Pretty soon your children will become teenagers and they’ll realize that you aren’t perfect.
to get carried away – to do too much of something; to take something to an extreme; to go beyond the regular limits of something
* Painting the walls pink would have been enough, but don’t you think you’re getting carried away now that the carpet, bedding, ceiling, and lamps are pink too?
devoted – strongly committed to someone or something, especially with feelings of love
* Wendy is devoted to her pets, even more than most people are devoted to their children.
to admire – to think that someone or something is very good and deserves a lot of respect
* I really admire the way Sheila has kept a positive attitude throughout her divorce.
to stalk – to follow someone in a secret, hidden way that is perceived as a dangerous threat
* When Noemi’s ex-boyfriend started stalking her at home, at work, and wherever she went, she immediately reported it to the police.
in case – if something happens; to be prepared for a particular situation or set of circumstances
* They always have extra food prepared in case someone visits unexpectedly.
sighting – an instance where someone or something is seen, especially if it is very rare
* Scientists were surprised by reports of a sighting of a butterfly that they thought was extinct.
network – a group of people or machines that are connected in some way and communicate with each other
* Our bank has the largest network of ATMs in the country.
to keep tabs on (someone or something) – to know the location and condition of someone or something at all times
* How do Susanna and Ovid keep tabs on their 12 children?
handcuffs – two metal rings that are attached by a short chain, so that when the rings are placed around a prisoner’s wrists, he or she has a limited ability to use his or her hands
* The police told the criminal to put his hands behind his back, and then they put handcuffs on him.
Comprehension Questions
1. What does Marcel mean when he says, “You’ve definitely gotten carried away”?
a) He is teasing Fiona for being in love with Del.
b) He thinks Fiona has spent too much money on pictures of Del.
c) He thinks Fiona is overly interested in Del.
2. What will Fiona use the handcuffs for?
a) To place a sensor on Del so she always knows where he is
b) To pay Del for an autographed photo
c) To keep Del from running away from her
Answers at bottom.
What Else Does It Mean?
fan
The word “fan,” in this podcast, means someone who likes an athlete, musician, actor, type of sport, or type of music very much and regularly participates in related activities: “Craig is a huge fan of the band, so we bought him concert tickets as a birthday present.” The word “fan” also refers to a machine that blows air to help people feel cooler: “We don’t have air conditioning, but this fan might help you feel better.” A “fan” can also be a piece of stiff paper that is held in one’s hand and moved back and forth to make the air move: “The children folded paper into a fan and used it to blow the hot air away from their skin.” Finally, when talking about literature, “fan fiction” is stories that fans write, using the characters and settings from their favorite books.
sighting
In this podcast, the word “sighting” means an instance where someone or something is seen, especially if it is very rare: “Police are asking local residents to call with any sightings of the murder suspect.” Or, “Do you believe these stories about people who are reporting sightings of UFOs?” The phrase “to see the sights” means to visit the popular tourist destinations in an area: “How many days will we need to see the sights in Chicago?” Buying something “sight unseen” means buying it without seeing it first: “Did you really buy the apartment sight unseen from across the country?” Finally, the phrase “to not let (someone) out of one’s sight” means to be very careful not to lose someone: “If you take our daughter downtown, don’t let her out of your sight!”
Culture Note
Fanzines
“Fanzines” are unofficial magazines that are created by the fans of a particular show, movie, book, or band. Some of them are printed, but “nowadays” (in modern times) most are produced online. These online fanzines are sometimes called “webzines.” The “contributors” (people who contribute stories and artwork) usually are not paid for their “submissions” (the materials that are sent for publication), and the fanzines themselves are usually made available to other fans for free or for a “nominal fee” (a very small payment).
A lot of fanzines cover “science fiction” (books, shows, and movies about what might happen in the future, especially related to outer space), but others “cover” (are about) comics, “horror flicks” (movies intended to scare viewers), rock music, local music, role-playing games, video games, sports, and more.
Although fanzines are “amateur” (not professional) publications, they can be awarded the annual Hugo Awards. The Hugo Awards are given each year for the best “works” (artistic productions) in science fiction and fantasy, and the Hugo Award for Best Fanzine has been awarded almost every year since 1955. The biggest winners have been fanzines called Locus, Mimosa, File 770, Ansible, and Science Fiction Review. The “nominees” (fanzines that are considered for the award) have to meet certain “criteria” (requirements) that “distinguish” (differentiate) the publications from professional and “semi-”(partially) professional magazines.
Fanzines should not “be confused with” (be mistaken for) “fan magazines,” which are professionally produced publications that are sold to fans. With fanzines, fans produce material for the enjoyment of other fans, usually without a “profit motive” (a strong desire to make money).
Comprehension Answers
1 - c
2 - c