

= 给豆包的指令
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css




'''

== 1

我有一些托福英语单词表, 内容类似下面这样的:

　　plateau n 高原，台地，高地

　　portable a 可搬运的;便于携带的;手提式的，轻便的

　　precipitate v 促成，促使，使沉淀;使(水蒸气)凝结

　　primary "1 a 第一的，最初的

　　2 a 主要的，第一位的"

　　tough "1 a 强韧的，弯折不断的([opp]weak)

　-　2 a 不屈不挠的，坚强的;顽固的，固执的"


比如 "portable a 可搬运的;便于携带的;手提式的，轻便的", 里面包含单词本身, 它的词性(a就是 adj. , v 就是 verb, n 就是 noun,  之类), 后面还有中文解释. 因为同一个英文单词可能有多个词性, 也可能有多个不同的意思, 所以这些中文解释也是包括多个不同的意思的.

现在, 你来执行以下操作: 我会输入一批如上的托福单词表, 因为我想背单词, 但我想通过词组或短语的方式来记忆. 所以你把上面的每个单词, 根据单词表中给出的词性和意思数量, 生成托福中可能会有的词组. 改造生成如下的格式样子:

(数字编号)→ 单词

.. 包含该单词的词组  +
(该单词在此处的词性, 该单词在"牛津高阶英汉双解辞典"中的第一种英文意思, 中文意思, 词根词缀解释) +
.. 包含该单词的词组  +
(该单词在此处的词性, 该单词在"牛津高阶英汉双解辞典"中的第二种英文意思, 中文意思,, 词根词缀解释) +
等等



例如, 你会生成(如果下面的例子中有错误, 请忽略,我只是举个例子, 你在生成时, 要保证英语正确):

(0001)→ plateau

.. plateau climate  +
高原气候 ((n.) an area of flat land that is higher than the land around it 高原，台地，高地 ▶ 来自法语plateau,高原，平地，来自plat,平的，展开，词源同plate,plan.-eau,小词后缀，对应-ille.引申词义水平，稳定期，停滞期等。)  +

'''

(0002)→ portable

.. a portable pension  +
可转移养老金 ((a.) that is easy to carry or to move 便携式的；手提的；轻便的 ▶ -port-运输,携带 + -able形容词词尾,被动意义)  +
.. a portable TV  +
手提电视机  +

'''

(0003)→ precipitate

.. to precipitate a systematic crisis  +
引发系统性危机 ((v.) 促成，促使 ▶ pre-,在前，-cip,头，词源同cap,captain,-ate,形容词后缀。即使头在前的，一头栽下的，引申 词义鲁莽的，仓促的。)  +
.. precipitate the country into war  +
杀使国家骤然陷入战争状态 ((v.) 使突然陷入（某种状态）)  +

'''


注意:
1.如果某个单词种的某种意思, 你给出了多个例句, 只要在第一个词组后面写上中英文释义等(即小括号里的内容)就行了, 不需要所有的词组后面都重复这个小括号.  换言之, 必须是不同的意思, 才需要后面跟小括号的内容

2.如我过给出的单词表中的原始中文意思,有错误或不精确,不合适, 你可以改成更精确, 更正确的中文翻译.

3.数字编号, 从0001开始递进, 0002, 0003, ... 0100, 1001, 9999, 这样输出. 即一开始前面要有三个0的占位符.

4.虽然我上面的例子中, 单词的每一种意思, 只给出了1到2个例句, 但你生成时, 要让每种意思至少有2到3个例句. 即, 如果一个单词有两种意思, 就是每种意思各给出2个例句, 即一共最多会有4个例句. 如果一个单词有4种意思, 就是一共会有最多8个例句.

5.注意, 有些动词的用法是有固定搭配的, 比如interest 有这种固定搭配 :interest sb/yourself (in sth) , 像这种常用的固定搭配, 也要在例句和词典的中英文释义中体现出来, 讲解清楚.

6.用纯文本输出( → , .. , ''' ) 这些符号, 不需要渲染成css样式.

现在, 请对下面的单词表, 进行改造, 编号紧跟上面输出的最后一个延续下去:





'''

== 2


对我上传的 .adoc 格式的文本文件, 进行改造.


只要修改 以 .. 符号开始, 和以 + 符号结尾的行, 例如:

.. come to an abrupt stop +

.. an abrupt change in the weather +

类似上面这样的行.

而其他的行, 不做任何更改, 按原始内容保留即可.



对以 .. 符号开始, 和以 + 符号结尾的行, 改造要求如下:

1. 给英文原文中的难点单词, 加上单词释义.  注意: 简单的小学, 初中英语单词, 就不需要加上释义了.

比如原文是: ① Talking peace suddenly means talking about places like this—this lunar landscape, a titanium mine struggling under the Russian bombardment of Ukraine’s power grid, sometimes with only three hours of power a day.

请你变成这样: ② Talking peace 谓 suddenly means talking about places like this — this lunar 月球的；月亮的 landscape 景观, a titanium 钛 mine 矿，矿井 struggling under the Russian bombardment 轰炸；炮击 of Ukraine’s power grid 电网, sometimes with only three hours of power 电力 a day.

即在英文原文里,把里面的重要单词 (比如托福词汇, 雅思词汇, gre词汇, 专业术语), 惯用语(比如 make a big deal of sth), 短语(比如 go through, take part in 这样的短语动词等等), 后面直接跟上牛津高阶双语学习词典中的中文解释. 即把上面的 ①, 变成 ② 这样的形式. 在原文中这样展示就行了.

注意: 某单词的中文释义, 如果只用一个中文词组来解释, 意思不精确的话, 你就用多个中文词组来解释. 比如 tactic 单词, 中文释义需要多个词组来解释成"策略；手段；招数", 你就不要只给出仅一个"策略"的释义, 而要写全这些多个中文词组来释义. 即不要只写为"tactic 策略", 而要写成"tactic 策略；手段；招数". 单词的中文解释不需要用小括号括起来. 也不需要再在文章最后单独列出每个单词的释义.


3. 执行上面的改造操作时, 注意不要遗漏任何英文原文. 一定要记住这一点, 不要遗漏任何英文原文的内容.

4.我给出的英文, 里面带有asciidoc代码符号, 比如 ==, -, ., * 符号等等, 保留所有这些符号! 不要删掉!

5.输出的内容不要做格式上的渲染, 即不要有加粗, 斜体等存在, 就普通纯文本格式输出就行了.

将最终的内容, 另存为一个文本文件让我下载



