= 1282
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,282 – Working in a Scientific Field.
This is English as a Second Language Podcast episode 1,282. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
This episode is a dialogue between Shirley and Ira about working in a job related to science.
Let’s get started.
[start of dialogue]
Ira: It’s amazing that everybody in your family works in the sciences.
Shirley: Yeah, my parents are both in the social sciences. My father is a psychologist and my mother is an economist.
Ira: And your sister Shonda?
Shirley: She’s an astronomer. She initially wanted to study physics, but changed her mind. Her partner is a geologist.
Ira: Is your brother also in astronomy?
Shirley: No, he’s a biologist and his wife does chemistry research.
Ira: How about your other brother? What does he do?
Shirley: Um, we don’t . . . I mean he’s not involved in the social sciences, life sciences, or physical sciences.
Ira: If I remember correctly, he was always good at math and liked computers. Is he in computer science?
Shirley: No, he’s not. All right, he’s a writer, but we have every confidence that he’ll grow out of it.
[end of dialogue]
Ira starts our dialogue by saying, “It’s amazing that everybody in your family works in the sciences.” The word “sciences” (sciences) – in the plural form – usually refers to different areas, what we call “fields (fields) of study,” including areas of the academic or research world that look at natural and physical sciences. Shirley says, “Yeah,” which is an informal way of saying yes. “My parents are both in the social sciences.”
Now, I just defined “the sciences” as relating to the physical and natural world. Part of the natural world includes people, of course, and that means that the sciences also includes the study of human beings and how they interact with each other. The “social (social) sciences” are sciences that study human beings and their interactions, things that would include sociology and psychology, anthropology – some people perhaps would also include history, although history, according to some people, is more like another area of study called “the humanities,” which would include the study of art and literature.
In any case, the social sciences includes things such as psychology and economics. Shirley says, “My father is a psychologist,” someone who studies the human mind, and her mother “is an economist,” someone who studies the way money is made and the way that human beings relate to each other when it comes to selling and buying things. Ira says, “And your sister Shonda?” Shirley replies that her sister is an “astronomer” (astronomer). An astronomer is a person who studies the planets and the stars and other objects out in what we would call “outer space” – the area beyond the Earth.
Shirley says that her sister “initially,” meaning at the beginning, perhaps at the beginning of her studies, “wanted to study physics, but changed her mind.” “Physics” (physics) is the study of physical objects and how they move and are influenced by natural forces such as gravity and magnetism. Her sister “changed her mind,” meaning she changed her opinion. She decided to do something different, in this case.
“Her partner is a geologist,” Shirley says. A “partner” (partner) can mean someone with whom you run a business. A “business partner” is a person with whom you have a share of or share responsibility in a business. More recently, the word “partner” has been used to describe someone with whom you are in a romantic relationship with. I’m not sure if this originally came from British English. I used to notice it in British English a few years ago. It has become more popular in American English more recently.
A “partner” is a general term for either your boyfriend, your girlfriend, your husband, or your wife. I don’t think there are any other possibilities there, at least within the human race. In any case, that’s a “partner.” Not one of my favorite words. I prefer people just say what they mean. If you mean your boyfriend, then say your boyfriend. Anyway, that’s my own personal complaint.
A “geologist” (geologist) is a person who studies the earth – what the earth is made of, things inside of the earth like rocks. I had a good friend from high school who wanted to be a geologist. He even started a master’s program in geology, but he decided not to continue studying it. This was back in the late 1980s, the mid-1980s – 1986, 1987. He decided there wasn’t any money in geology and so he changed his focus to computers.
Now, I think if he were to make the same decision again he might continue in his studies of geology. Geologists, at least in the United States, are often employed, or given jobs, in the new oil industry – the oil businesses that have grown so much in the past 20 years in the U.S. In any case, Shirley’s sister’s boyfriend, girlfriend, husband, or wife is a geologist.
Ira says, “Is your brother also in astronomy?” Shirley says, “No, he’s a biologist and his wife does chemistry research.” A “biologist” (biologist) is a scientist who studies living organisms – plants and animals, for example. When I first moved to California, I lived with a couple of biologists who were getting their PhD in biology from Claremont College – Claremont University or something. I don’t remember very well. It was a long time ago.
Anyway, in our story, Shirley’s brother’s wife – that would make her Shirley’s sister-in-law – works in the field or the area of “chemistry” (chemistry). “Chemistry” is the study of what materials are made of and how the elements of the materials interact and relate to each other. Chemistry studies things like small molecules, and what’s inside the molecules, and what the molecules are made of – how the different elements react to each other. Ira says, “How about your other brother?” meaning tell me about your other brother. “What does he do?”
Shirley says, “Um, we don’t . . . I mean he’s not involved in the social sciences, life sciences, or physical sciences.” Shirley doesn’t want to talk about the other brother she has. I guess because he’s not in “the social sciences, life (life) sciences,” or physical sciences. “Life sciences” are those fields that study any kind of life. That would include biology, zoology, botany, biochemistry, microbiology – those are all life sciences. The physical sciences are things like chemistry and geology and physics and astronomy.
Ira says, “If I remember correctly, he” -– meaning Shirley’s brother – “was always good at math and liked computers.” “Math” (math) is a short form of the word “mathematics.” In British English, they put an “s” at the end. They say “maths,” but we say “math” without the “s.” Ira asks, “Is he,” meaning your brother, “in computer science?” “Computer science” is of course the study of computers. Shirley says, “No he’s not.”
Then she says, “All right,” in a way that indicates that she didn’t really want to talk about him but now she will. “All right, he’s a writer,” she says. A “writer” (writer) is, of course, a person whose job is to create things by writing them – by typing them or writing them down. Nowadays, of course, everyone does it on a computer. A writer could be someone who writes fiction, such as stories, or poetry. A writer could be someone who writes for a newspaper or writes books about things that are real.
Shirley says, “We,” meaning she and her family, “have every confidence that he’ll grow out of it.” Shirley says that she and her family hope that their brother will “grow out of it.” That’s what she means when she says they have “every confidence” (confidence). “To have every confidence of” something, or “to have every confidence that” something, means that you have no doubts – that you are sure something will happen in the future.
What Shirley and her family are sure of is that the brother, who is a writer, will “grow out of it.”
The expression “to grow out of” something means to become older and wiser, or more mature, so that you’re no longer interested in this particular area or that you no longer have certain problems that we normally associate with, or think are related to, someone’s young age. As we grow older, we grow out of some of the things that we liked when we were children. Shirley and her family don’t believe that being a writer is a very good thing, and that’s why they hope that the brother in the family will grow out of his love of writing, I guess.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Ira: It’s amazing that everybody in your family works in the sciences.
Shirley: Yeah, my parents are both in the social sciences. My father is a psychologist and my mother is an economist.
Ira: And your sister Shonda?
Shirley: She’s an astronomer. She initially wanted to study physics, but changed her mind. Her partner is a geologist.
Ira: Is your brother also in astronomy?
Shirley: No, he’s a biologist and his wife does chemistry research.
Ira: How about your other brother? What does he do?
Shirley: Um, we don’t . . . I mean he’s not involved in the social sciences, life sciences, or physical sciences.
Ira: If I remember correctly, he was always good at math and liked computers. Is he in computer science?
Shirley: No, he’s not. All right, he’s a writer, but we have every confidence that he’ll grow out of it.
[end of dialogue]
We hope our writer never grows out of her love of writing dialogues. Thanks to Dr. Lucy Tse for today’s dialogue.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2016 by the Center for Educational Development.
Glossary
sciences – fields of study to learn about the natural and physical world based on observation and testing
* In the sciences, developing experiments with control groups help to determine the true effects of what is being studied.
social sciences – fields of study related to how people interact with each other and society
* The social sciences include history, anthropology, politics, sociology, and more.
psychologist – a scientist and counselor who studies the human mind and how it affects behavior
* Maybe we should send our son to a psychologist to try to determine why he’s behaving this way.
economist – a person who studies supply, demand, money, production, and systems that allow buyers and sellers to interact
* Economists are trying to understand how people value higher education.
astronomer – a person who studies planets, stars, and other objects in outer space
* Astronomers used to think Pluto was a planet, but now they consider it a dwarf planet.
physics – the science that studies physical objects and how they move when influenced by physical forces such as gravity and magnetism
* The laws of physics govern how quickly an apple falls from a tree.
partner – a person with whom one has a romantic relationship and commitment, but may or may not be married
* Byron has lived with his partner for almost 10 years, but they have no plans to get married.
geologist – a scientist who studies Earth, what it is made of, how the pieces move and interact, and its structure
* Piotr is fascinated by rocks, earthquakes, and volcanoes, so he’s thinking of becoming a geologist.
biologist – a scientist who studies living organisms (plants and animals)
* As a biologist, Kyle is fascinated by all forms of life.
chemistry – the study of what materials are made of and how those elements interact, combine, and change
* Anyone who has taken a chemistry class knows that water is made from two molecules of hydrogen and one molecule of oxygen.
life sciences – all the sciences that study forms of life
* The life sciences include biology, microbiology, zoology, botany, and biochemistry.
physical sciences – all the sciences that study non-living things and phenomena
* The physical sciences department offers courses in geology, chemistry, physics, astronomy, climatology, and more.
math – mathematics; the study of numbers, functions, and shapes, including arithmetic, algebra, geometry, trigonometry, and calculus
* In math class, we’re studying the Pythagorean theorem.
computer science – the study of computers, including how to build and operate them and write programs for them
* People who work in computer science must continue learning as technology quickly changes.
writer – a person whose job is to create text, documents, and other written materials
* Can you call yourself a writer if your work has never been published?
to have every confidence – to be very confident; to have no doubts, hesitation, or uncertainty
* We have every confidence that we’ll be able to sell the house within 60 days.
to grow out of (something) – to become older and more mature so that one is no longer interested in something or no longer has a problem
* How old were you when you grew out of playing with dolls?
Comprehension Questions
1. Which of these is an example of the life sciences?
a) Astronomy
b) Biology
c) Chemistry
2. What does Shirley mean when she says “he’ll grow out of it”?
a) He’ll become more interested in being a writer.
b) He’ll realize that writers are unimportant.
c) His interests will change when he gets older.
Answers at bottom.
What Else Does It Mean?
partner
The word “partner,” in this podcast, means a person with whom one has a romantic relationship and commitment, but may or may not be married: “Are you going to bring your partner to Harriet’s wedding?” A “partner” can also be someone with whom one does business: “Trent is a managing partner who owns 45% of the business.” A “silent partner” is someone who owns part of a business, but does not actively manage or operate it: “I would never want to be a silent partner. If I invest money in a business, I want to make some of the decisions.” Finally, the phrase “partners in crime” is used humorously to describe two or more people who planned and did something bad or mischievous together: “When they were growing up, our cousins were partners in crime, always getting in trouble.”
to have every confidence
In this podcast, the phrase “to have every confidence” means to be very confident and to have no doubts, hesitation, or uncertainty: “I have every confidence that this expansion will double our profits.” The phrase “to shake (someone’s) confidence” means to make someone question or doubt his or her beliefs: “When his girlfriend ended the relationship, it really shook his confidence.” The phrase “in strict confidence” means secretly and with the understanding that someone will not share the information with anyone else: “I told you that in strict confidence! Why did you repeat it to your brother?” Finally, a “vote of no confidence” is a formal process in which people show that they no longer support an elected government official: “The board of directors passed a vote of no confidence in the CEO.”
Culture Note
The Best Exhibits/Highlights of the Top Science Museums
The United States has many “science museums” (places where people can go to learn about science and interact with experiments), and many of them are “famous” (well known to many people) for their “impressive” (causing people to admire something) “exhibits” (displays and other objects that people can view and interact with, especially with some shared theme or idea).
The National Air and Space Museum in Washington, DC, has many important airplanes, rockets, “spacesuits” (protective clothing worn by “astronauts” (people who fly into outer space)), and “moon rocks” (rocks brought from the moon back to Earth). It also has many exhibits about the “mechanics” (how something works) of flight and “space exploration” (efforts to travel to and understand other parts of outer space).
The Exploratorium in San Francisco, California, has a “Tactile Dome,” which is a completely “dark” (without light) exhibit in which visitors must learn to “see” by using their sense of “touch” (feeling things with one’s hands). And the Tech Museum of Innovation in San Jose, California, allows visitors to become technology inventors as they learn about digital music, and “virtual world technology” (tools that make people think they are experiencing another reality).
Many science museums have special exhibits for children, and some science museums are “entirely” (completely; 100%) for children. The Hands-On! Regional Museum in Johnson City, Tennessee, for example, lets children conduct experiments and learn through “hands-on” (using one’s hands to move or handle objects, not watching other people do it) activities. And the Franklin Institute in Philadelphia, Pennsylvania, teaches children about science through storytelling and “superheroes” (fictional characters with special powers).
Comprehension Answers
1 - b
2 - c