= 1288
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,288 – Being a Job-Hopper.
This is English as a Second Language Podcast episode 1,288. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
This episode is a dialogue between Simon and Maggie about a person who doesn’t work at one job for very long. Let’s get started.
[start of dialogue]
Simon: Hey Maggie, I just stopped by to say good-bye. This is my last week.
Maggie: What? You’re leaving? You’re not being fired, are you?
Simon: No, I have another job lined up. It’s with a bigger company.
Maggie: But you’ve worked here for less than a year. You’re quitting?
Simon: Yeah, I’ve been putting out feelers for the past couple of months. I’m ready for a change.
Maggie: Are you sure this is the right move? You don’t want to be labeled as a job-hopper.
Simon: I appreciate your concern, but I’m not a lifer, that’s for sure.
Maggie: But you’ve moved three times in the past three years. Aren’t you afraid of being considered unstable or disloyal? It’s normally considered career suicide to move from job to job.
Simon: I know that some people spend 20 years in the same company, climbing the corporate ladder and working toward their pension, but that’s just not me.
Maggie: Aren’t you afraid companies won’t invest in you because they’re afraid you’ll jump ship?
Simon: Nope. It hasn’t happened yet.
Maggie: Well, then I wish you all the best. Maybe I’ll cross paths with you again in your twentieth or thirtieth job.
[end of dialogue]
This episode is about a “job-hopper” (hopper). A “job-hopper” is someone who moves jobs frequently, who doesn’t stay at any one job for a very long time. Simon begins our dialogue by saying, “Hey Maggie, I just stopped by to say good-bye.” The phrasal verb “to stop by” (by) means to visit somewhere or to go somewhere for a very short time, usually for an informal visit with someone. “I’m going to stop by at my brother’s house on my way to work just to say hello.”
Often we use this phrasal verb when we aren’t planning on doing something in advance, but decide perhaps at the last minute or on very short notice to do something. That’s not always the way this phrasal verb is used, however. It could be something that we also planned. You could say, “I’m going to stop by the grocery store to buy some milk on my way to my brother’s house.” So, “to stop by” can also be used when we are going to stop or go more than one place before we reach our destination, before we go to the final place we are planning on going.
Simon is saying good-bye to Maggie because this is his “last week” – his last week of work. Maggie is surprised. She says, “You’re not being fired, are you?” “To be fired” (fired) means to lose your job because your boss or your company says you can no longer work there. There are two ways to stop working somewhere. One is to “quit” (quit), which is when you decide that you don’t want to work at a place. The other way to end your employment is “to be fired.” That’s when your company says, “We don’t want you working here anymore.”
Simon is not being fired. He says, “I have another job lined up.” “To be lined (lined) up” means to be ready to use or waiting for you to use. In this case, it means that Simon has another job that he is going to move to. He says this other job is with a bigger, a larger, company. Maggie says, “But you’ve worked here for less than a year. You’re quitting?”
Simon says, “Yeah,” meaning yes. “I’ve been putting out feelers for the past couple of months,” he says. The phrase “to put out feelers” (feelers) means to ask other people or to tell other people about something that you have that you think they may want, to see if they are interested. “To put out feelers” means to determine whether other people, in this case, are interested in giving you a job.
You may mention to your friend who works at another company, for example, that you are interested in leaving your company. You want to find out if your friend’s company may be interested in hiring you – that is, in giving you a job. That would be an example of “putting out feelers.” You don’t necessarily go to the company directly, but you tell people about your situation to see if someone may be interested in hiring you.
Simon says he’s ready for a change. Maggie asks, “Are you sure this is the right move?” meaning this is the correct decision or the right thing to do. “You don’t want to be labeled as a job-hopper,” she says. “To be labeled” (labeled) as something means to be seen in a certain way, especially something that perhaps you don’t want to be seen as. If you are labeled as a lazy person, that means people think you are lazy, and of course you don’t want people to think you are lazy, normally.
Maggie is concerned that Simon will be considered or labeled as a “job-hopper,” someone who doesn’t stay at a job very long. Many people think this is a bad thing, that a person who is considered a job-hopper will have difficulty finding jobs because no one will want to hire that person knowing the person will leave in a few months, say. Simon says, “I appreciate your concern,” meaning I thank you for being worried about me, “but I’m not a lifer, that’s for sure.” The term “lifer” (lifer) refers to a person who works for one company his entire career or his entire life. Simon says he’s not a lifer.
Maggie says, “But you’ve moved three times in the past three years,” meaning he’s had three different jobs in three years. “Aren’t you afraid of being considered unstable or disloyal?” “To be unstable” (unstable) means to be not stable. That prefix “un” means “not,” usually. “To be not stable” means that you aren’t reliable. You are not dependable. You’re not steady or consistent. If someone is “unstable,” someone may change next week or a month from now. “To be disloyal” (disloyal) means to be not loyal. The prefix “dis” is often used like the prefix “un” to mean “not.”
So if you are “disloyal,” you are not loyal. “To be loyal” means to be committed to a person, to defend a person, or to stay with that person – or in this case, a company – for a long time. Maggie is saying that Simon will be considered disloyal if he continues to job-hop. “It’s normally considered career suicide to move from job to job,” she says. “Career” (career) refers to your job history or your work life, what you do to make money. “Suicide” (suicide) normally means to kill yourself. “Career suicide,” then, is a phrase that means to ruin your chances of having a good career, of having good jobs.
Simon says, “I know that some people spend 20 years in the same company, climbing the corporate ladder and working toward their pension, but that’s just not me.” The expression “to climb (climb) the corporate (corporate) ladder (ladder)” means to work in a single company, going from one job to the next, each time getting a better job, but doing it slowly.
So you begin in one job, and then you get another job in the same company that is better paying and has more responsibility, and then you get another job a few years later in the same company, higher up in the company. That would be “climbing the corporate ladder.” A “pension” (pension) is money that the company gives you after you retire, money that you will live on after you retire. Maggie says, “Aren’t you afraid companies won’t invest in you because they’re afraid you’ll jump ship?”
“To invest” (invest) in a person, in someone, means to spend money and time on a person, perhaps giving that person more skills or training so that that person will be a better employee, a better worker for you. Maggie is saying that if companies think he’s not going to stay very long, they won’t invest in him. They won’t give him a lot of extra training. They’ll be afraid that he will “jump (jump) ship (ship).” The expression “to jump ship” means to leave a company or an organization and move to a different one, often when the company is having a difficult time.
If you can imagine a ship out on the ocean, a large boat, and the boat is beginning to sink, beginning to go down into the water, the first thing you would want to do is jump to another ship. You would want to move to another ship that was not sinking. A person who moves from a failing company, from a company that doesn’t seem to be doing very well, to a more successful company could be said to be “jumping ship” – to be moving to the better company. Simon is not afraid that companies will be afraid to invest in him. He says, “It hasn’t happened yet.”
Maggie says, “Well, then I wish you all the best,” meaning good luck. “Maybe I’ll cross paths with you again in your twentieth or thirtieth job.” Maggie is making a joke, saying that Simon may end up having twenty or thirty jobs if he keeps moving all the time. She says, “Maybe I’ll cross paths with you.” “To cross (cross) paths (paths)” means to meet someone in the future by chance, by luck, not by planning it. If you tell someone, “Perhaps our paths will cross in the future someday,” you mean “Maybe someday you and I will see each other again even when we don’t plan on it.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Simon: Hey Maggie, I just stopped by to say good-bye. This is my last week.
Maggie: What? You’re leaving? You’re not being fired, are you?
Simon: No, I have another job lined up. It’s with a bigger company.
Maggie: But you’ve worked here for less than a year. You’re quitting?
Simon: Yeah, I’ve been putting out feelers for the past couple of months. I’m ready for a change.
Maggie: Are you sure this is the right move? You don’t want to be labeled as a job-hopper.
Simon: I appreciate your concern, but I’m not a lifer, that’s for sure.
Maggie: But you’ve moved three times in the past three years. Aren’t you afraid of being considered unstable or disloyal? It’s normally considered career suicide to move from job to job.
Simon: I know that some people spend 20 years in the same company, climbing the corporate ladder and working toward their pension, but that’s just not me.
Maggie: Aren’t you afraid companies won’t invest in you because they’re afraid you’ll jump ship?
Simon: Nope. It hasn’t happened yet.
Maggie: Well, then I wish you all the best. Maybe I’ll cross paths with you again in your twentieth or thirtieth job.
[end of dialogue]
It’s a good idea to invest in yourself by improving your English by listening to the wonderful scripts written by our wonderful scriptwriter, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2017 by the Center for Educational Development.
Glossary
to stop by – to make an informal, unscheduled, and brief visit
* I hope I’m not interrupting anything. I just stopped by to drop off these books you asked to borrow.
to be fired – to lose one’s job; for one’s employer to end one’s employment
* If profits continue to fall, many of our employees will be fired.
lined up – prepared and ready for use; waiting for one’s use
* They had childcare arrangements lined up weeks before Sheila went back to work.
to quit – to decide to no longer work in a particular job; to end one’s relationship with an employer
* This is the worst job ever! The pay is low and I’m treated badly. I quit!
to put out feelers – to determine whether there is any interest in something; to ask around; to measure other people’s attitudes, opinions, or feelings about something, especially related to a job opportunity
* Gregorio has started putting out feelers for consulting opportunities.
to be labeled as – to be perceived and categorized in a particular way, especially in a way that one does not agree with
* The students in this program are sometimes labeled as bad students, but they’re struggling with major learning disabilities.
job-hopper – a person who has held many different jobs in a short period of time; a person who changes jobs very often and shows little or no loyalty to employers
* Craig developed a reputation as a job-hopper when he worked for seven companies in just three years.
lifer – a person who continues to work for a single company throughout his or her entire career
* Joey was a lifer who worked at the company for nearly 50 years!
unstable – not steady or consistent; unreliable and not dependable
* In the first months of a new business, income is often unstable, with some good sales months and some poor ones.
disloyal – not loyal or faithful; not showing a full commitment to a person or thing
* Willie was disloyal to his employer when he shared corporate secrets with a competitor.
career suicide – one or more acts that make one seem unprofessional, unreliable, or otherwise unprepared for success in the workplace, making it extremely difficult or impossible to get a good job
* Jenny committed career suicide by texting messages to colleagues while she was drunk criticizing her bosses and the company she worked for.
to climb the corporate ladder – to perform a series of jobs with increasing responsibility and importance within a company, moving from low-level jobs into management, and eventually to the highest-level jobs
* Randall has exceptional skills that will make it easy for him to climb the corporate ladder.
pension – money received each month during retirement from one’s former employer
* In the past, many companies provided pensions for their employees, but now, only government workers can look forward to receiving a reliable pension.
to invest in (someone) – to spend money, time, and other resources to help someone improve or develop particular skills
* They’re investing in their children by putting them in language classes, music classes, and sports.
to jump ship – to quit; to leave a position, job, or company, especially during challenging times
* A lot of employees jumped ship when our company was experiencing financial difficulty.
to cross paths – to meet or encounter someone by chance, without having planned it ahead of time
* It’s so uncomfortable to cross paths with an ex-girlfriend. I never know how I should act or what I should say to her.
Comprehension Questions
1. What does Simon mean when he says, “I’ve been putting out feelers”?
a) He has become increasingly dissatisfied with his job.
b) He has been asking about new job opportunities.
c) He has been asking for a raise.
2. Why is Maggie concerned about Simon’s decision?
a) She thinks he won’t be able to find a better job.
b) She thinks he needs to demonstrate loyalty to his employer.
c) She thinks he’ll miss her and other co-workers.
Answers at bottom.
What Else Does It Mean?
lined up
The phrase “lined up,” in this podcast, means prepared and ready for use: “We have some great speakers lined up for this year’s conference.” If a piece of clothing is “lined,” it has a thin layer covering the interior for extra warmth or coverage: “All of the high-quality wool suits are lined with silk.” A “lined face” is a wrinkled face: “We were shocked when we saw his white hair and lined face. When did he get so old?” “Lined paper” is paper that has faintly colors lines printed horizontally, used to keep one’s writing straight: “Without lined paper, my handwriting always angles upward to the right.” Finally, a “tree-lined street” is a street that has many trees on both sides: “They live on a beautiful tree-lined street in the Franklin neighborhood.”
to jump ship
In this podcast, the phrase “to jump ship” means to quit or to leave a position, job, or company: “Shortly after we hired that new manager, many of the team members began complaining and then jumped ship.” The phrase “to abandon ship” means to leave a ship that is sinking: “We’ve hit an iceberg! Abandon ship!” The phrase “to run a tight ship” means to manage a company, team, or classroom with many rules and discipline, but very effectively: “The teachers at that military school run a tight ship.” Finally, the phrase “shape up or ship out” is used to tell someone that he or she must improve quickly or will be told to leave an organization, team, or job: “Your behavior has become unacceptable. Shape up or ship out.”
Culture Note
Common Resume Problems and How to Solve Them
Most job “applicants” (people who are applying for a job) must “submit” (officially present and provide) a “resume” (a single page that has information about one’s education and professional experience). “Recruiters” (people whose job is to hire others to fill job openings) review resumes to identify applicants who are well qualified for the job and should be “brought in” (asked to come to the company) for an interview.
Having a large “gap” (open space in time or position) is usually viewed as a resume problem. People who list jobs that are separated in time by more than a few months need to be prepared to explain what they were doing during that time. The recruiter might “assume” (believe that something is true even though one does not have information about it) that the applicant was unemployed and unable to find a job because he or she is poorly qualified. The best way to address such a gap on a resume is to indicate what one was doing during that time, such as traveling, writing a book, or taking care of family. Sometimes this information can be presented on the resume, but in other cases, it needs to be explained in the “cover letter” (a one-page letter written to the company and submitted with the resume).
Another common resume problem is when the applicant does not have the “degree” (academic qualification) that the employer is “seeking” (looking for). In this case, the applicant might need to “de-emphasize” (reduce the focus on) the type of degree that was received, and list any certifications or experience that fits into the requested field. Some employers will view such certifications and experience as “the equivalent of” (the same as) having earned a degree in the desired field.
Comprehension Answers
1 - b
2 - b