= 1297
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,297 – Types of Neighborhoods.
This is English as a Second Language Podcast episode 1,297. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
This episode is a dialogue between Shari and Ron about different kinds of neighborhoods, or sections in a city, and what we call them. Let’s get started.
[start of dialogue]
Shari: Okay, ready to see more homes? I’ve lined up several for you to view this afternoon.
Ron: Yes, I’m ready. It’s hard finding just the right type of neighborhood to move to.
Shari: Yes, it’s been difficult, hasn’t it? How long have I been showing you homes?
Ron: About three months.
Shari: That’s right. First we looked at homes in planned and gated communities and in the bedroom communities around the city, as you requested.
Ron: That’s right. At first, I thought I wanted a quiet place to live in my retirement.
Shari: That’s why I also showed you homes in retirement communities.
Ron: Yes, but once I saw them, I changed my mind. I’m retired, but I’m not dead. I decided I wanted a livelier neighborhood, someplace with more action.
Shari: That’s why I showed you homes in the historic district and in the redeveloped waterfront area, both of which are very pedestrian-friendly.
Ron: Yes, but the more I thought about it, the more I wanted to be in the middle of the action.
Shari: That’s why, today, I’m taking you to the urban core. We’ll look at homes in the downtown area, the arts district, and a couple of ethnic enclaves. We’ll visit some high-priced neighborhoods and some up-and-coming.
Ron: Great! I think house-hunting has given me a new lease on life. This is fun! I could look at home after home after home.
Shari: That’s what I’m afraid of.
[end of dialogue]
Shari begins by saying to Ron, “Okay, ready to see more homes? I’ve lined up several for you to view this afternoon.” “To line up” or “to have lined up” means to plan and make ready or to schedule. In this case, we have Shari, who we learn is a real estate agent. She’s a person responsible for finding homes for someone to buy or rent. She has “organized” or scheduled some houses to show to Ron, who is looking for a house to buy or rent. I think he’s buying a house.
Ron says, “I’m ready.” I’m ready to view or look at the houses that Shari has lined up for him to see. He says, “It’s hard finding just the right type of neighborhood to move to.” A “neighborhood” is an area within a city. Most large cities have several different sections, parts, or what we would call “neighborhoods” – areas that usually are given a name. For example, here in Los Angeles, Hollywood is actually a neighborhood within the city of Los Angeles. It’s not its own city. It’s part of the larger city. Venice is a neighborhood in Los Angeles, and there are many different neighborhoods here.
Well, Ron is finding it difficult to know what kind of neighborhood he wants to move to. He’s been looking for a house for three months now. We learn from Shari that first, she and Ron looked at homes in “planned and gated communities and in the bedroom communities around the city.” A “community” is another word for a neighborhood or area.
Sometimes “community” is used in a larger, more general sense to refer to a large group of people who have similar backgrounds or live in a similar area, but here it refers to an area in a city. Although, it could also be used to refer to a single city. Here in Southern California, there are “planned communities” that are their own city. Irvine, California, which is in the southern part of Southern California, if that makes any sense, is a “planned community.”
A planned community is one where someone has sat down and decided where everything is going to be. In other words, it wasn’t a small town that grew little by little over many years. Instead, there was someone who had a plan who drew out were all the streets were going to be, and where the houses were going to be, and the parks, and the schools, and so on. Planned communities are often built at once – that is, the entire area, neighborhood, or even city is built all over a short period of time, a couple of years even.
There are planned communities inside of cities. There are also “gated (gated) communities.” A gated community is usually a group of homes that is surrounded by a fence or a wall to provide protection and security for the people who live in that neighborhood. There is often a gate, an entrance that you have to stop at and get permission in order to continue driving into the community. The gate is typically on one of the larger streets that go into that community.
We have gated communities here in Los Angeles, especially where very rich people live. There are gated communities just north of where I live. I live where the poor people live, and the rich people live up in the gated communities. Hollywood stars, movie stars, those sorts of folks are the ones that live in the gated communities here in L.A.
Shari also refers to “bedroom (bedroom) communities.” The “bedroom” is the area or the room in the house where you sleep, where you have your bed of course. “Bedroom communities,” however, refer to small towns that are next to a large city, where many people move to when they don’t want to live in the city itself – perhaps because the city is too expensive, or maybe it’s not safe, or perhaps the schools aren’t very good in the cities – and so people who work in the city live outside of the city in what are called “bedroom communities.”
These are often simply called “suburbs,” although a suburb could be another city with something more than just houses. Bedroom communities are areas where there are mainly houses. There isn’t a lot of business that you will find in a bedroom community. Los Angeles has lots of bedroom communities – towns that are outside of the city of Los Angeles where you will find mostly homes. There aren’t a lot of large businesses there. Ron says that he thought he wanted a quiet place to live “in his retirement.” “Retirement” is the period after you leave your job, usually when you are older.
Shari says, “That’s why I also showed you homes in retirement communities.” Yes, there are actually areas in the city, or in fact entire cities, that have mostly retired people in them. This concept, this idea, became very popular in the 1970s, I guess 1980s also, where in the southern, especially southwestern United States, as well as in Florida, in the southeast part of the country, there were small cities built mostly for retired people, for older people, who wanted a place where it would be quiet.
Ron says he thought he wanted to live in a retirement community, but once he saw them, he changed his mind – that is, he decided he was wrong and had a different idea. He says, “I’m retired, but I’m not dead. I decided I wanted to live in a livelier neighborhood, someplace with more action.” “Livelier” (livelier) comes from the adjective “lively,” which means there are perhaps a lot of people there, or there are things going on. There are small businesses and restaurants and cafes. That would be a “livelier area” of the city, or a “livelier neighborhood.”
Shari says, “That’s why I showed you homes in the historic district and in the redeveloped waterfront area, both of which are very pedestrian-friendly.” “Historic (historic) district (district)” refers to an area in a city or town that is important for some reason. Often it’s the older part of town. A historic part of Los Angeles is the area near downtown where the first Spanish settlers came back many hundreds of years ago. That’s the historic part of the city. The word “district” simply refers to an area within the city or within a town.
Shari also showed Ron the “redeveloped waterfront area.” The “waterfront” (waterfront) is obviously an area in the city next to some water. It could be a river. It could be a lake. It could be the ocean. “Redeveloped” means that it was an area that was perhaps old and had old buildings, or buildings that people weren’t using anymore, and someone came and put new buildings there or they fixed up, they repaired, the old buildings so that people could now live and work there. Many cities have redeveloped their waterfront areas, especially those in the older cities in the eastern part of the U.S.
Shari says that these areas that she showed Ron – the historic district and the waterfront area – are both very “pedestrian (pedestrian) – friendly (friendly).” “Pedestrian” is a word we use to describe someone who walks, or someone who is walking along the street. So “pedestrian-friendly” would be an area where it’s easy to walk up and down. There are some parts of the city that are not pedestrian friendly, especially here in Los Angeles, but nobody walks in Los Angeles anyway so it doesn’t really matter.
Ron says, “Yes, the more I thought about it, the more I wanted to be in the middle of the action.” “In the middle of the action” means where lots of things are happening – an area, in this case, where there are a lot of people, a lot of excitement perhaps. Shari says, “That’s why, today, I’m taking you to the urban core” (core). “Urban” (urban) refers to the city. The “urban core” of the city would be the main or central part of a large city, not the bedroom communities, not the suburbs. The opposite of that.
“We’ll look at homes in the downtown area,” Shari says, “the arts district, and a couple of ethnic enclaves.” “Downtown” refers to the main, central, usually business section of the city. It’s often, but not always, the older part of the city. The downtown area in Los Angeles is in fact the oldest part of the city.
Shari’s also going to show Ron houses in the “arts (arts) district.” In some American cities, there are areas where there are a lot of artists who live, perhaps because the rents are cheaper, since artists normally don’t make a lot of money. The arts district is often an area that has cheaper places to stay but is also an exciting area because there are a lot of artists there – painters and sculptors and other people who call themselves artists.
Shari’s also going to show Ron houses in a few “ethnic (ethnic) enclaves (enclaves).” An “enclave” is a small area within the city with people who come from the same country, cultural background, or perhaps speak the same language. These are often areas with “immigrants” – people who’ve come from other countries, since the United States is, for the most part, a nation of immigrants.
“Ethnic” is an interesting word. “Ethnic” refers often to the country or region of the world from which you come or your ancestors – the people who first came to the United States – were from. So, I have Irish ethnicity. I would say that’s my ethnic group. And there were, especially in cities such as Boston, New York, Chicago, and my hometown, St. Paul, ethnic areas where the Irish lived. There were other “ethnic enclaves” where the Germans lived. So the word “ethnic” means national origin or sometimes regional origin.
Interestingly, the word “ethnic” has changed over the years when we talk about politics. Back in the late ’70s, early 1980s, when people talked about the “ethnic vote,” they were referring mainly to southern and eastern European voters or those who are descendants of immigrants from those countries. Nowadays we tend to use the term to refer more to, say, those who are from Latin America or from Asia. But the term is a general one that can apply to any nationality.
Shari says, “We’ll visit some high-priced neighborhoods and some up-and-coming.” The expression “up-and-coming” means that the area is getting more popular, more people are moving there. Ron says, “Great! I think house-hunting has given me a new lease on life.” “House-hunting” refers to the process of looking for a house, usually to buy. The expression “a new lease (lease) on life” means a new reason to feel happy to live, especially perhaps after you’ve had a difficult time in your life, or perhaps you’ve lost someone or simply have grown older.
“A new lease on life” would give you a feeling of excitement, some new reason to live. Ron thinks that this is fun, this house-hunting. He says, “I could look at home after home after home.” In other words, he would love to continue just looking at houses, not actually buying one.” Shari says, “That’s what I’m afraid of.” Remember, Shari is a real estate agent. Her job is to find a house for Ron, but she doesn’t want to continue showing him houses forever. She wants to get paid, and she only gets paid when Ron actually buys a house.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Shari: Okay, ready to see more homes? I’ve lined up several for you to view this afternoon.
Ron: Yes, I’m ready. It’s hard finding just the right type of neighborhood to move to.
Shari: Yes, it’s been difficult, hasn’t it? How long have I been showing you homes?
Ron: About three months.
Shari: That’s right. First we looked at homes in planned and gated communities and in the bedroom communities around the city, as you requested.
Ron: That’s right. At first, I thought I wanted a quiet place to live in my retirement.
Shari: That’s why I also showed you homes in retirement communities.
Ron: Yes, but once I saw them, I changed my mind. I’m retired, but I’m not dead. I decided I wanted a livelier neighborhood, someplace with more action.
Shari: That’s why I showed you homes in the historic district and in the redeveloped waterfront area, both of which are very pedestrian-friendly.
Ron: Yes, but the more I thought about it, the more I wanted to be in the middle of the action.
Shari: That’s why, today, I’m taking you to the urban core. We’ll look at homes in the downtown area, the arts district, and a couple of ethnic enclaves. We’ll visit some high-priced neighborhoods and some up-and-coming.
Ron: Great! I think house-hunting has given me a new lease on life. This is fun! I could look at home after home after home.
Shari: That’s what I’m afraid of.
[end of dialogue]
If you want to be in the middle of the action when it comes to improving your English, you should stay right here with ESL Podcast and the wonderful scripts written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2017 by the Center for Educational Development.
Glossary
lined up – prepared, planned, and ready; scheduled
* Zafir has several interviews lined up over the next two weeks.
planned community – a neighborhood where the homes, stores, parks, schools, and more are built at the same time, designed to make a nice lifestyle for the people who move there
* In this planned community, we’ll reduce traffic by making sure that everyone can go to the grocery store, library, and coffee shop on foot, without needing to drive.
gated community – a group of homes that are surrounded by a fence that provides protection and security so that people may walk or drive in only with a password or key
* They want to live in a gated community because they’re worried about crime in the city
bedroom community – a small town near a large city, where most of the people who live in that town work in the large city, but return to the town on evenings and weekends
* Living in a bedroom community would be peaceful, but we’d have to drive into the city for work each day.
retirement community – a neighborhood for older people who no longer work
* People must be at least 62 years old in order to live in this retirement community.
redeveloped waterfront – an area in a city and near a river where there used to be many warehouses and factories, but they have been converted (changed) into or replaced by modern apartments, condos, and stores
* Portland, Oregon has a redeveloped waterfront with luxurious condos and fancy restaurants.
pedestrian-friendly – meeting the needs of people who walk, not drivers; designed to make an area safe and convenient for walkers rather than focusing on cars
* A pedestrian-friendly street needs to have slow traffic, wide sidewalks, and good lighting.
in the middle of the action – where things are happening; in an area with a lot of people, movement, and excitement
* We went to New York City and visited Times Square, where we knew we’d be in the middle of the action.
urban core – the central part of a large city, not the outskirts or the surrounding area
* What can we do to make schools in the urban core just as good as schools in the surrounding areas?
downtown – the central part of a large city, especially where there are many skyscrapers (very tall buildings)
* Each morning, thousands of people in business suits go downtown to their office jobs.
arts district – a part of a large city where there are many artists, art galleries, and performance spaces
* Let’s go the arts district to visit some art galleries with modern art.
ethnic enclave – a neighborhood in a large city where there are many immigrants from one country or culture living together
* Chinatown and Little Italy are the best-known ethnic enclaves in this city.
up-and-coming – improving and becoming very popular, especially with young people, attracting a lot of money, businesses, and investments
* We bought our home in an inexpensive part of the city 15 years ago, but now it’s an up-and-coming neighborhood and the value of our home is going up quickly.
house-hunting – the process of looking for a home to buy
* They expected to spend a lot of time house-hunting, but they ended up making an offer on the first home they saw.
a new lease on life – a feeling of excitement, enthusiasm, and enjoyment; a new reason to feel happy to live
* Ramona had been very sick and depressed, but seeing her first grandchild gave her a new lease on life, and her health improved quickly.
Comprehension Questions
1. Which of these is furthest from the urban core?
a) A bedroom community
b) The downtown area
c) The arts district
2. Which of these neighborhoods would have an age restriction for residents?
a) A retirement community
b) A historic district
c) An ethnic enclave
Answers at bottom.
What Else Does It Mean?
planned community
The phrase “planned community,” in this podcast, refers to a neighborhood where the homes, stores, parks, schools, and more are built at the same time, designed to make a nice lifestyle for the people who move there: “Do you know if that new planned community will have a high school?” The phrase “planned obsolescence” refers to the way in which some products are designed to have a short lifetime and be replaced by other products that are more fashionable or advanced: “Companies that do not have strong competition can use planned obsolescence to increase sales of their products.” Finally, “Planned Parenthood” is a well-known organization that offers medical assistance related to healthcare and pregnancy: “Planned Parenthood provides education and healthcare, especial to women.”
new lease on life
In this podcast, the phrase “a new lease on life” means a feeling of excitement, enthusiasm, and enjoyment: “This surgery could restore Hannah’s eyesight and give her a new lease on life.” The phrase “to roar into life” means for a machine to suddenly begin working: “The mechanic adjusted a few screws and the car roared into life.” The phrase “to put some life into (something)” means to make something more exciting or interesting: “Adding more dialogue would put some life into your story.” Finally, the phrase “this is the life” is used when one is very happy, content, and relaxed, doing something that one enjoys: “Ah, this is the life! A beautiful beach, a good book, and a nice, cool drink—what could be better?”
Culture Note
Famous Urban Renewal Projects
The United States has many famous “urban renewal projects” that have improved the “atmosphere” (how something feels) and “quality of life” (the health, comfort, and happiness that one feels) in “dilapidated” (old, worn down, and not well cared for) sections of large cities.
Portland, Oregon; Louisville, Kentucky; and Baltimore; Maryland are just a few of the U.S cities that have “transformed” (changed in a significant way) “industrial” (related to manufacturing, usually with factories and warehouses) areas into parks, modern apartment buildings, and attractive business districts. These urban renewal projects have “attracted” (brought in) many young professionals and new businesses.
Las Vegas, Nevada, also has several urban renewal projects, but they aren’t focused on transforming a dilapidated area. Rather, the project “aims” (intends; is trying to do) to create an “entrepreneurial” (related to people who are willing to take risks, try new things, and open new businesses) “hub” (a center of activity) in the downtown area, encouraging “investment” (putting money into something) and “innovation” (trying new things; doing things that no one has done before, or doing things better than they have been done before). One of the most interesting “focal points” (areas of focus) is that the city is using old “shipping containers” (large rectangular boxes that are filled with products for transportation by ship and train) as restaurants and stores.
Washington, DC, also has “notable” (worth noticing; interesting) urban renewal project. The city is redeveloping its waterfront, ensuring that the new buildings are “environmentally responsible” (having less negative impact on the natural environment).
Comprehension Answers
1 - a
2 - a