= 1299
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 1,299 – Trading Insults.
This is English as a Second Language Podcast episode 1,299. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful – and I do mean beautiful – Los Angeles, California.
This episode is all about insulting or saying bad things about other people. This is going to be fun. Let’s get started.
[start of dialogue]
Alan: Look at you! Did you get a haircut or did your head get stuck in a weed whacker?
Doris: Look who’s talking. Maybe you should do something different with your hair, like wash it.
Alan: Oh, burn. That would have been a nice comeback if it weren’t so dumb. Who taught you your one-liners? A friend? Oh, I forgot. You don’t have any.
Doris: I think you’ve confused me with someone else – you!
Alan: You couldn’t come up with your own put-down so you had to borrow mine? How humiliating for you.
Doris: Not as humiliating as having to walk around with that face. I have something that’ll improve it: a paper bag!
Alan: Oh, clever. I knew better insults when I was six years old.
Doris: You mean the same mental age you are now?
Alan: Give it up. Nobody can one-up me in trading insults. Your brain is no match for mine.
Doris: You’re right. You’re a person of rare intelligence. You rarely show any!
[end of dialogue]
We begin our dialogue with Alan saying to Doris, “Look at you!” “Look at you” is used when we are trying to say something about someone’s physical appearance, about the way he looks. Alan says, “Look at you! Did you get a haircut or did your head get stuck in a weed whacker?” A “haircut” (haircut) is when, you can probably guess, the length of the hair on your head is made shorter by someone cutting it with a scissors or some electronic device. We would call it a “razor” (razor). I don’t need to get a haircut anymore because I shave my head. I use a razor on the top of my head to get rid of the little hair I have left. But enough about me – back to our dialogue.
Alan asks Doris – not seriously, but as a way of insulting her or saying something bad about her – if she got a haircut or if her head got “stuck in a weed whacker.” “To get stuck” (stuck) is a two-word phrasal verb meaning to be put into a place or a position and unable to move or to get yourself out of that position or situation. Here in Los Angeles, we often talk about getting stuck in traffic – that is, being unable to move very fast in our car because there are so many other cars on the road or the freeway.
You could get your hands stuck, for example, in a small jar. Let’s say you are putting your hand into a small container or jar to get something out and then you can’t get your hand out of the jar or the container. Your hand is stuck. You’re unable to move it. Alan is jokingly asking Doris if her hair got stuck in a “weed whacker.” “Weeds” (weeds) are small plants that grow that you don’t want, that you want to get rid of. A “weed whacker” (weed whacker) is a machine that is used to cut grass, especially at the end of a certain area of grass. It’s a machine that is also used to quickly remove tall grass from an area in your lawn or outside of a building. The verb “to whack” (whack) here means to cut.
We sometimes use a weed whacker for small areas that we need to cut the lawn or to cut weeds down where we can’t use a regular, what we would call a “lawn mower,” which is a machine you use to cut grass. I should mention that you should be careful with this word “weed.” Weed” in the singular is sometimes used informally to mean “marijuana,” that kind of plant that you smoke that can cause you to change your attitude or mood, that is illegal in many places. A “weed whacker” has nothing to do with marijuana.
Now, why is Alan asking Doris if she had her head stuck in a weed whacker? Well, he’s saying that her haircut isn’t very good. It looks as though someone did it as if they were cutting a lawn or cutting down weeds. Doris responds to Alan by saying, “Look who’s talking.” That expression “Look who’s talking” is used to say that another person who is criticizing you actually has the same problem or the same situation. So if someone says to you, for example, “Boy, you are looking very tired,” and the person is saying that as a way of insulting you, you might say, “Well, look who’s talking. You look even more tired than I am.”
Doris, in other words, is insulting Alan right back by saying that there is a problem with his hair. She says, “Maybe you should do something different with your hair, like” – or such as – “wash it.” Doris’s saying that Alan hasn’t washed his hair, and so his hair doesn’t look very good either. Alan responds by recognizing or acknowledging that Doris has insulted him in a clever or funny way. He says, “Oh, burn.” “Burn” (burn) here means insult – words that you use to insult – but he’s using it in a funny way, to be funny.
He says, however, “That would have been a nice comeback if it weren’t so dumb.” A “comeback” (comeback) is something you say right after another person insults you or says something bad about you. A “comeback” is supposed to be funny, or we would say “witty” (witty). “Witty” is funny in an intelligent way, in a clever way. Alan doesn’t think that Doris’s insult to him was very clever. It wasn’t a good comeback. That’s why he says, “That would have been a nice comeback if it weren’t so dumb.” He’s saying that it was a dumb comeback.
“Who taught you your one-liners?” A “one – liner” (liner) is a joke that is only one, maybe two sentences long. Technically a “one-liner” should just be one sentence, but it is often two or maybe even three sentences. Alan is saying that Doris isn’t very funny. He says, “Who taught you your one-liners? A friend?” Then he says, “Oh, I forgot. You don’t have any,” meaning “You don’t have any friends” – which is, of course, another insult.
Doris says, “I think you’ve confused me with someone else – you!” Doris means here that Alan is really talking about himself. Alan says, “You couldn’t come up with your own put-down so you had to borrow mine?” Doris didn’t come up with a very good comeback and Alan recognizes that. “To come up with” is a phrasal verb or expression meaning to invent or to think of something, especially in a creative way. A “put-down” is another word for an insult or another term for saying something bad about another person.
Alan says, “How humiliating for you.” “To be humiliating” (humiliating) means to feel ashamed or embarrassed. Doris says, “Not as humiliating as having to walk around with that face. I have something that will improve it: A paper bag.” Alan says it’s humiliating for Doris to not be able to be clever or original. Doris responds that it’s more humiliating for Alan to be so ugly. That’s what she means by saying “walking around with that face.” She says she has something that will improve Alan’s face: a paper bag. Doris is saying that Alan is so ugly he should put a bag over his head.
Alan says, “Oh, clever.” “Clever” (clever) means funny, creative, very smart in an unexpected way, in this case. But Alan here is being sarcastic – that is, he doesn’t really think Doris is clever. He’s saying that to mean the opposite, in fact, that she isn’t very clever. He says, “I knew better insults when I was six years old,” meaning he was better or could do better insults, funnier insults, when he was a child.
Doris says, “You mean the same mental age you are now?” Your “mental (mental) age” is how old your mind is, which really means how intelligent you are. Your body can be a certain physical age, but if you have problems in your brain, your mental age – that is, your intelligence – might be much lower. That is, you’re not as smart as your body age, I guess you could say.
Alan then says to Doris, “Give it up.” The expression “to give it up” means to stop, especially to stop trying when something is too difficult. Alan then says, “Nobody can one-up me.” “To one-up” someone means to do something better than another person, usually right after that person does it. So you, for example, make a wonderful meal, and then your friend decides to one-up you. He’s going to cook a meal even better than you did.
Alan tells Doris that no one can one-up him in “trading insults.” “To trade” (trade) here means to exchange something. So, I insult you and you insult me. Alan says, “Your brain is no match for mine.” The expression “not to be a match” (match) for something or someone means it’s not as good as something else or someone else. If I say, “Your team is no match for my team,” I mean that my team is better than your team. Your team is worse than my team. Alan says that Doris’s brain is no match for his brain.
Doris says, “You’re right. You’re a person of rare intelligence.” “Intelligence” is how smart you are. “Rare” (rare) means unusual or not very common. Doris then says, “You rarely show any!” meaning you very infrequently, or not very often, have any intelligence. So Doris is trying to insult Alan back by saying that he is not very smart.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Alan: Look at you! Did you get a haircut or did your head get stuck in a weed whacker?
Doris: Look who’s talking. Maybe you should do something different with your hair, like wash it.
Alan: Oh, burn. That would have been a nice comeback if it weren’t so dumb. Who taught you your one-liners? A friend? Oh, I forgot. You don’t have any.
Doris: I think you’ve confused me with someone else – you!
Alan: You couldn’t come up with your own put-down so you had to borrow mine? How humiliating for you.
Doris: Not as humiliating as having to walk around with that face. I have something that’ll improve it: a paper bag!
Alan: Oh, clever. I knew better insults when I was six years old.
Doris: You mean the same mental age you are now?
Alan: Give it up. Nobody can one-up me in trading insults. Your brain is no match for mine.
Doris: You’re right. You’re a person of rare intelligence. You rarely show any!
[end of dialogue]
Our scriptwriter is a woman of rare intelligence. I speak, of course, of the wonderful Dr. Lucy Tse, who always comes up with wonderful scripts.
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us again right here on ESL Podcast.
English as a Second Language Podcast was written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2017 by the Center for Educational Development.
Glossary
haircut – when the length of one’s hair is shortened with scissors or an electric razor, often in a new style
* I don’t want long hair anymore. I’m going to get a haircut.
to get stuck – to become trapped and unable to move or unable to remove oneself from a particular situation
* During the power outage, a group of people got stuck in the elevator for hours.
weed-whacker – a large machine that is held in the hands and has a plastic string that moves in circles very quickly to cut grass or other plants, especially next to a sidewalk or fence where a lawn mower cannot be used
* We’ll need to use a weed-whacker to clear those overgrown hills.
look who’s talking – a phrase used to show that what another person said about another person actually applies to him or herself, often used jokingly as an insult
* A: That color looks horrible on you.
B: Oh, yeah? Look who’s talking! You look even worse in that color.
burn – insult; words that are a sign of disrespect toward another person, often used humorously
* That burn was supposed to make everybody laugh. I didn’t know it would make Hermione cry.
comeback – a clever, witty, or funny statement made immediately after another person made a joke or shared an insult
* I wasn’t able to think of a good comeback until late at night when I was almost asleep, so it was too late.
one-liner – a very short joke or funny insult, with just one or two short sentences
* Here’s a great one-liner: “No, you’re not useless. You can always serve as a bad example.”
to come up with – to think of something; to have a creative or interesting idea
* The company offers rewards to those who come up with the next great product.
put-down – an insult; something that makes another person feel bad about himself or herself, but often used in a humorous way
* Pierre grew up with an abusive father and heard so many put-downs that he started to believe them.
humiliating – making one feel embarrassed or ashamed
* Falling down on stage in front of all those people was humiliating!
clever – very smart, quick, creative, funny, and unexpected
* If you’re so clever, why don’t you know how to fix this problem?
insult – something that is done or said to shame another person or to say something bad about that person; a way to offend someone intentionally
* Refusing to eat the food that Rosie made was an insult to her.
mental age – a measure of one’s maturity and ability to think clearly and behave as an adult
* Trenton has developmental delays. He is 16 years old, but he has the mental age of a four-year-old child, and he will need someone to take care of him for the rest of his life.
give it up – a phrase used to tell someone to stop trying to have or do something because it isn’t possible or because it is too difficult or challenging for that person
* Pierre trained for the Olympics for years, but injuries kept him away from the competition. Now he finally believes that it’s time to give it up.
to one up – to do something better than another person can, raising the competition to the next level
* Becca is always trying to one up her neighbors. If they buy a new car, she buys a fancier car. If they get new couch, she buys a more expensive one.
to trade – to exchange; to take turns doing something with another person; to give something to someone and receive a something else from that same person
* We trade pet-sitting services with our neighbors when we travel. They take care or our dog when we leave town, and we take care of their cat when they travel.
no match for – inferior; not as good as; unable to do something as well as another person or thing
* That old desktop computer is no match for this new laptop
rare intelligence – uncommonly smart; significantly more intelligent than most people
* Magnum has a rare intelligence, and his teachers recommend that he applies to the universities with the best science programs in the country.
rarely – not very often; infrequently
* They like to cook, so they rarely go to restaurants.
Comprehension Questions
1. What does Alan mean when he asks, “Did your head get stuck in a weed-whacker?”
a) He wants Doris to know that she has weeds and dirt in her hair.
b) He wants Doris to know that her new haircut is unattractive.
c) He wants Doris to know that she hasn’t been listening to him.
2. What does Doris suggest that Alan do with a paper bag?
a) She wants him to put his one-liners in a paper bag so he doesn’t forget them.
b) She wants him to put a paper bag over his ugly face to hide it.
c) She wants him to ask strangers to put money into a paper bag for him.
Answers at bottom.
What Else Does It Mean?
burn
The word “burn,” in this podcast, means an insult or words that are a sign of disrespect toward another person, often used humorously: “Oh, burn! I think he just said you’re too dumb to pass the test!” The phrase “to burn out” means to work too hard so that one becomes extremely tired and unable to work anymore: “What can we do to prevent young teachers from burning out?” The phrase “to burn (someone) up” means to make someone very angry: “Seeing people steal from small business owners really burns me up!” The phrase “to be burning up” means to have a high fever: “The baby is burning up! We need to take him to the hospital.” Finally, the phrase “to get burned” means to lose a lot of money, usually in a business deal: “We really got burned with those investments my brother recommended.”
one
In this podcast, the phrase “to one up” means to do something better than another person can, raising the competition to the next level, or to beat someone at something: “The twins are extremely competitive and always try to one up each other with their professional accomplishments.” The phrase “to have had one too many” means to be drunk and under the influence of alcohol: “I think you’ve had one too many. Give me your car keys.” The phrase “one-off” means happening only once, not as part of a series: “Is this a one-off presentation, or a monthly event?” Finally, the phrase “to have a one-track mind” means to think about only one thing: “That man has a one-track mind. Football is all he’s interested in!”
Culture Note
Elements of a Comedy Club Performance
People who go to a “comedy club” (a bar where comedians perform to entertain the audience and make people laugh) are “accustomed to” (used to; expecting) certain things. For example, they know that there’s probably a “two-drink minimum,” meaning that they must agree to pay for at least two drinks in order to be in the comedy club. That’s how the bar “guarantees” (makes sure something happens) a minimum income for the evening.
Once the “patrons” (customers of a restaurant or bar) “take their seats” (sit down), there’s usually an “opening act” in which a “lesser-known” (not as famous as others) comedian tries to “warm up the crowd” (get the audience ready for the main show). Then the main comedian will come out to give the first of a few “sets” (performances).
Most audience members are there to be entertained and will “give the comedian a chance” (allow someone to have an opportunity to succeed), but sometimes there are “hecklers,” or people who make loud, “disruptive” (causing interruptions and distractions) noises to “annoy” (bother) the comedian.
If the comedian isn’t very good, more and more people might begin to heckle him or her. If the performance continues to be really bad, the comedian might even get “booed off the stage” (with audience members making loud, low “boo” noises so that the performer has to stop performing and leave). Anyone who has that experience is probably going to “get the hook” (be told that he or she no longer has a job and should not come back).
Comprehension Answers
1 - b
2 - b