= 0507
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 507: Guarding One’s Privacy.
This is English as a Second Language Podcast episode 507. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode. It contains all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of this episode, of everything we say.
This episode is called “Guarding One’s Privacy.” It’s a dialogue between Dan and Mina talking about people who want to keep their personal information private or secret. Let’s get started.
[start of dialogue]
I went to visit my old friend, Mina, whom I hadn’t seen in several years. It was one of the strangest afternoons of my life!
Dan: Hi, Mina, it’s really good to see you.
Mina: Dan, come in. Hurry!
Dan: Uh, okay. Why do you have four locks on your door, and why are all of the curtains drawn?
Mina: I like my privacy. And anyway, I think there’s a peeping Tom around this apartment building and I don’t want him to get a peek into my apartment.
Dan: Oh, okay. I noticed that your name isn’t on your mailbox. I wasn’t sure I had the right apartment number.
Mina: Do you think I would voluntarily give people that information? They are constantly trying to invade my privacy. All I want is anonymity, but I have to be on guard all of the time. These days, I only give out personal information on a need-to-know basis.
Dan: No offense, but isn’t that a little paranoid? You act as though everybody is out to get you.
Mina: Aren’t they? Haven’t you noticed? We constantly have to disclose our most personal information on forms and to anyone who comes to our door. If I didn’t know you were coming today, I wouldn’t have opened my door at all.
Dan: You mean you live here in seclusion, like a hermit?
Mina: Of course not! I have plenty of friends. Come and meet them all.
Dan: Wow, you must have 10 birds and 20 cats!
Mina: Yes, that’s right. But, rest assured, none of them will breathe a word of what you say here today!
[end of dialogue]
Our story begins with Dan saying that he went to visit his old friend, Mina, whom he hadn’t seen in several years. “It was one of the strangest afternoons of my life!” he says.
Dan says, “Hi, Mina, it’s really good to see you.” Mina says, “Dan, come in. Hurry!” Dan is obviously at Mina’s house, he knocks on her door [sound of knocking], and she tells him to hurry up and come in. Dan says, “Uh, okay. Why do you have four locks on your door, and why are all of the curtains drawn?” A “lock” is something that you use to prevent other people from opening a door; Mina has four locks on her door. She also has her curtains drawn. “Curtains” are pieces of fabric that cover a window so you can’t see inside. “To be drawn” means, in this case, to be closed. We use this word in talking about curtains, sometimes we use the word “drapes.” Curtains or drapes are drawn when they are closed. “Drawn,” however, has a couple of different meanings in English, so be sure to look at the Learning Guide for this episode for some additional explanation of that.
Mina says, “I like my privacy.” “Privacy” is the ability to be alone, to keep your personal information secret so that other people don’t know about you or what you are doing. Privacy has become very important, especially on the Internet. Mina says, “I think there’s a peeping Tom around this apartment building and I don’t want him to get a peek into my apartment.” The expression “a peeping Tom” refers to a person – a man, typically – who is looking through the windows trying to watch women, especially when women are taking their clothes off. It’s, obviously, a very negative expression to use about someone; in fact, you could probably get arrested by the police for being a peeping Tom. I’m not sure why the name Tom is used; I’m glad it isn’t a peeping Jeff! Well, Mina says that she wants to make sure that this peeping doesn’t get a “peek” (peek) into her apartment. “To peek at (something)” means to look quickly at something, especially if it is difficult to see or if you’re not supposed to see it. So, “taking a peek” means taking a quick look.
Dan says, “Oh, okay. I noticed that your name isn’t on your mailbox,” the small box where the mail carrier (the person from the, usually, government agency that delivers mail to your house) puts your mail; the mailbox is the place where the mail is put. Mina, however, does not have her name on her mailbox; Dan says, “I wasn’t sure I had the right apartment number.” Mina says, “Do you think I would voluntarily give people that information?” “Voluntarily” means willingly, when you want to do something. She’s saying “I would not voluntarily (of my own free will) give people my information,” such as her name. She says, “They are constantly trying to invade my privacy.” They – we’re not sure who they are – are trying to invade her privacy. “To invade (someone’s) privacy” is to learn something about another person that they want to be secret, that they don’t want to tell you. If someone sends you a personal letter and your friend opens the letter and reads it without telling you or without you giving them permission, that would be an “invasion of privacy,” he would be invading your privacy. “Invasion” is the noun from the verb “to invade.” Normally, this verb “to invade” refers to an army going into another country. The ancient Roman army invaded Greece back in the second century B.C., I believe.
Well, Mina doesn’t want anyone to invade her privacy, she says, “All I want is anonymity, but I have to be on guard all the time.” “Anonymity” is to be anonymous; that is, to be in a situation where no one knows who you are or what you are doing. “Anonymity” is a noun coming from the idea of “anonymous,” which is unknown, so nobody knows about you. She says, however, that she has to be on guard all the time. “To be on guard” is an expression meaning to be very careful or cautious, to prevent something from happening; to be alert, this means to be on guard. “Guard” has a couple of different meanings in English however, so take a look at that Learning Guide for some more explanations.
She says, “These days, I only give out personal information on a need-to-know basis.” The expression “need-to-know basis” is used to describe a situation where people are only given information that they absolutely must have, and only that very necessary information is shared or given to them. It’s an expression you would probably hear in the government or in the military, talking about secrets that the military has or that a country has. It’s not normally used in daily conversation, but of course, Mina, here, is what we would call a little bit “paranoid.” She’s very worried that other people are going to hurt her or that other people are trying to follow her. To be paranoid is considered a negative description; it’s to be too worried, to be worried without any good reason.
In fact, Dan says, “No offense (meaning I don’t want to hurt you by saying this, by insulting you), but isn’t that a little paranoid?” Dan says, “You act as though everyone is out to get you.” “To be out to get (someone)” means to be trying to do something to somebody, usually something bad. If you say your boss is out to get you, you’re saying your boss is trying to hurt you or harm you in some way. There are actually two expressions here: “To be out to do (something)” means to try to do something; “to get (someone)” means to attack, hurt, or perhaps even kill someone. So to say someone “is out to get you” means that someone is trying to harm you.
Mina says, “Aren’t they? Haven’t you noticed? We constantly have to disclose our most personal information on forms and to anyone who comes to our door. If I didn’t know you were coming today, I wouldn’t have opened my door at all.” “To disclose” means to share or to give some secret or private information to someone else. So, Mina thinks that everyone is trying to invade her privacy by asking her for all this personal information.
Dan then says to Mina, “You mean you live here in seclusion, like a hermit?” “To be in seclusion” means to be alone, without talking to other people or seeing other people. A “hermit” is a person who lives alone and doesn’t speak to anyone else. This was originally a religious idea among the early Christians. They were men who would go out into the desert by themselves, and live by themselves, and spend the whole day praying. That was to be a hermit, to be alone. Women, also, sometimes were hermits, and there are, even today, people who are hermits for religious purposes. But Dan, here, is talking about Mina being by herself, and so he’s using the term “hermit” almost as an insult.
Mina says, “Of course not (of course I don’t live like a hermit)! I have plenty of friends. Come and meet them all.” Dan says, “Wow, you must have 10 birds and 20 cats!” Her friends are animals. Mina says, “Yes, that’s right. But, rest assured, none of them will breathe a word of what you say here today!” The phrase “rest assured” means don’t worry; there is no problem, there is no reason to worry. She says none of these animals will breathe a word of what you say. “To breathe a word” is an expression that means to say something, especially to tell someone something that is personal, private, or secret. Of course, the animals won’t breathe a word; in fact, they can’t talk, so it’s a pretty safe environment. Obviously, Mina needs some help!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
I went to visit my old friend, Mina, whom I hadn’t seen in several years. It was one of the strangest afternoons of my life!
Dan: Hi, Mina, it’s really good to see you.
Mina: Dan, come in. Hurry!
Dan: Uh, okay. Why do you have four locks on your door, and why are all of the curtains drawn?
Mina: I like my privacy. And anyway, I think there’s a peeping Tom around this apartment building and I don’t want him to get a peek into my apartment.
Dan: Oh, okay. I noticed that your name isn’t on your mailbox. I wasn’t sure I had the right apartment number.
Mina: Do you think I would voluntarily give people that information? They are constantly trying to invade my privacy. All I want is anonymity, but I have to be on guard all of the time. These days, I only give out personal information on a need-to-know basis.
Dan: No offense, but isn’t that a little paranoid? You act as though everybody is out to get you.
Mina: Aren’t they? Haven’t you noticed? We constantly have to disclose our most personal information on forms and to anyone who comes to our door. If I didn’t know you were coming today, I wouldn’t have opened my door at all.
Dan: You mean you live here in seclusion, like a hermit?
Mina: Of course not! I have plenty of friends. Come and meet them all.
Dan: Wow, you must have 10 birds and 20 cats!
Mina: Yes, that’s right. But, rest assured, none of them will breathe a word of what you say here today!
[end of dialogue]
It’s no secret that this script was written by our very own Dr. Lucy Tse.
If you’d like to support us here at ESL Podcast, consider becoming a Learning Guide member or sending a small donation. Go to eslpod.com to find out more information.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
drawn – closed, used when talking about curtains or drapes
* They always sleep with the curtains drawn.
privacy – the ability to be alone and keep one’s personal information and actions secret, so that other people do not know about oneself or one’s activities
* She goes into her room and closes the door whenever she wants a few minutes of privacy.
peeping Tom – a person who looks through windows to watch women when they undress
* I heard a noise at the window and thought it was a cat, but when I went looked outside, I found a peeping Tom!
to peek – to quickly look at something, especially if it is difficult to see or if one is not supposed to see it
* The little boy carefully opened the wrapping paper so he could peek at the present, even though his birthday wouldn’t be for another three days.
voluntarily – willingly; meaning or wanting to do something; with a specific intention or desire
* Why would you voluntarily offer to clean the bathrooms? That’s my least favorite thing to do.
to invade (one’s) privacy – to learn something about another person or his or her activities, especially when that person would like to keep those things secret
* Is it an invasion of my daughter’s privacy if I go into her bedroom and look through her closet and drawers when she isn’t home?
anonymity – used to describe a situation where other people do not know who one is or what one is doing
* Clarke hates the anonymity of moving to a new city, so he’s working hard to meet people and make friends.
to be on guard – to be alert; to be very careful or cautious, especially to prevent something from happening
* Xena has dangerous allergic reactions, so she’s always on guard against bees.
need-to-know basis – a phrase used to describe a situation where people are given only the information that they absolutely must have, and no additional unnecessary information is shared
* The United States government lets people view classified data only on a need-to-know basis.
paranoid – too worried, believing that other people want to hurt oneself, or that other people are looking for oneself
* The mental hospital is full of paranoid patients who think other people are trying to kill them.
to be out to (do something) – to be trying to do something
* All of the players are out to win the most important game of the year.
to get (someone) – to attack, hurt, or kill someone
* The young men are creating a plan to get the other gang’s leader.
to disclose – to share secret or private information
* Interviewers should never ask job candidates to disclose their marital status.
seclusion – living alone, without seeing or speaking to other people; keeping oneself alone, away from other people
* They spent their vacation far away in the mountains, seeking seclusion where they knew there wouldn’t be other people.
hermit – a person who lives alone and doesn’t speak to anyone else
* One of her uncles is a hermit who lives in a house in the mountains and hasn’t spoken to anyone in more than eight years.
rest assured – a phrase used to tell another person not to worry, or that there is no problem and everything is under control
* Rest assured, we have enough money in the bank to pay our bills for months, even if we both lose our jobs.
to breathe a word – to say something, especially to share a secret
* Our boss told us not to breathe a word of anything discussed at the meeting.
Comprehension Questions
1. What does Mina mean by saying that she has to be “on guard” all the time?
a) She has to be very careful about what she says and does.
b) She has to hire a security guard for safety.
c) She has to keep her apartment locked all day long.
2. Why does Dan ask Mina if she’s living as a hermit?
a) Because she is living without other people.
b) Because she is living with too many pets.
c) Because she is living with paranoia.
Answers at bottom.
What Else Does It Mean?
drawn
The word “drawn,” in this podcast, is used to talk about curtains or drapes that are closed: “On hot summer days, they keep the curtains drawn so that their house doesn’t get too warm.” When talking about a person’s appearance, someone who is “drawn” has a light-colored thin face, possibly because he or she is sick, worried, or very tired: “Quinton looked drawn after spending all night in the hospital with his sick wife.” Something that is “drawn-out” is taking too long, or taking more time than one had hoped: “That movie was too drawn-out! It was more than three hours long, but they could easily have told the same story in just 90 minutes.” Finally, the word “drawn” is the past participle of the verb “to draw”: “Everyone admired the pretty pictures that the children had drawn.”
to be on guard
In this podcast, the phrase “to be on guard” means to be alert or to be very careful, especially to prevent something from happening: “This street is dangerous, so be on guard and look out for cars that are driving too fast.” The phrase “to catch/throw (someone) off guard” means to surprise someone, or to ask someone to do or say something when he or she is not prepared: “The teacher’s question caught the student off guard.” The phrase “to be on guard” means to be on duty, or to be working to protect someone or a group of people: “Who was on guard at the prison that night?” Finally, the phrase “to be under guard” means to be watched by a group of people so that one cannot run away: “The criminal was under guard as he walked to the courtroom.”
Culture Note
Americans normally need to show “acceptable” (meeting certain minimum requirements for approval) forms of “personal identification” (written proof of who one is) to request government services or documents. The United States doesn’t have a national “ID” (identification) card like many other countries do, so instead government agencies accept combinations of other documents.
For example, to apply for a “replacement” (a copy that one can use when the original is lost, stolen, or damaged) “social security card” (a small piece of paper with one’s personal tax number), Americans can present different combinations of documents. A “birth certificate” (a piece of paper stating when and where one was born, and one’s parents’ names) and a “passport” (a document used for international travel) can be used as personal identification and proof of citizenship. A “driver’s license” (a small card that shows one has permission to drive) can also be used for identification.
When one needs to show “proof of residence” (documents showing where one lives), sometimes a driver’s license is “sufficient” (enough). At other times, Americans need to “present” (show) a “lease” (a legal agreement allowing one to live in an apartment or house) or a “utility bill” (a bill for gas, electricity, or water) with one’s name and current address.
Sometimes agencies require “original” (not copied) documents. Other agencies will accept “certified copies” (copies that have been marked by an agency to show that they are “valid” (real) copies).
Comprehension Answers
1 - a
2 - a