= 0519
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast episode 519: Describing Family Relations.
This is English as a Second Language Podcast episode 519. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, in California.
Our website is eslpod.com. You can download a Learning Guide for this episode. It contains all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of everything we say. If you like this podcast and would like to support it, please consider becoming a member of ESL Podcast.
This is dialogue about family relations. It’s going to use a lot of vocabulary you might use in talking about the way members of your family get along, or don’t get along. Let’s get started.
[start of dialogue]
Eri: What’s that?
James: It’s an invitation to a family reunion. Once every five years or so, someone in the family organizes one.
Eri: Are you going?
James: I’m not sure. It’s always a little awkward seeing extended family. Did you know that there used to be a big feud between my father and his brother?
Eri: No, what happened?
James: I’m not sure, but it was something that happened before they got married. My father held a grudge for years. Then, about eight years ago, they made up. There’s still no love lost between their wives, but at least there are no hard feelings between the two of them any longer.
Eri: So you’ll go to the reunion?
James: I’m not sure. My mother’s side of the family has always looked down on my father’s. She comes from old money and they didn’t approve of her marrying my father. It was really hard on my mother. She really looked up to her mother and they were really close before my father came along.
Eri: But that’s ancient history, isn’t it? Considering how things turned out, your grandmother can’t hold it against your mother for marrying your father.
James: You’ve never met my grandmother. One thing everyone knows about her is this: She doesn’t know the words to forgive and forget.
[end of dialogue]
Our dialogue begins with Eri saying, “What’s that?” James says, “It’s an invitation to a family reunion.” A “reunion” is when people who used to be together come together again. After you graduate from high school, usually 10 or 20 years after the year you graduate they have a high school reunion, where everyone gets together again. I’ve never gone to my high school reunion, probably never will. “Family reunion” is when you get together with members of your family, usually cousins, people who perhaps live in a different part of the country even, might travel to a family reunion. When I was growing up, we had family reunions that we went to usually in the summertime. But, of course, just my own family, what we would call my “immediate family,” had more than 40 people, so didn’t really need the cousins to have a big party.
James says, “Once every five years or so, someone in the family organizes a family reunion.” So his friend asks, “Are you going?” James says, “I’m not sure. It’s always a little awkward (a little strange) seeing extended family.” “Extended family” are family that are not in your what we call – and what I just called – “immediate family.” Your immediate family is your father, your mother, your brothers, your sisters, their husbands and wives, and probably their children – your nieces and nephews. Your extended family could include your grandparents, your cousins, your aunts, your uncles, and so forth. Everybody has a slightly different definition of what is “immediate” and what is “extended” in terms of family.
James says, “Did you know that there used to be a big feud between my father and his brother?” A “feud” (feud) is a long, serious argument between two people or two groups of people. It usually is something that goes on for a very long time, and sometimes it can even be violent. But here, I don’t think we’re talking about any violence, just his father and his uncle don’t get along.
Eri said, “No, what happened?” James says, “I’m not sure, but it was something that happened before they got married (the father and the mother, presumably). My father held a grudge for years.” “To hold a grudge” (grudge) means to continue to be angry about something that happened a long time ago, especially in a situation where you don’t really have a good reason to be angry still. James says, “about eight years ago, they (his father and uncle) made up.” “To make up” means to end an argument and become friendly again. A husband and wife could be arguing and disagreeing about something and they both get mad at each other, but then they make up; they decide they’ll be friendly again with each other. The past tense of “make” is “made,” so James says, “eight years ago, they made up. There’s still no love lost between their wives,” however. The expression “there’s no love lost” means there’s no of love or affection, respect or friendship between two people. Someone says, “Well, there’s no love lost between me and my neighbor,” that means that you don’t get along with – you don’t like your neighbor; you certainly don’t love each other. James says there’s no love lost between his mother and his aunt. He says, “at least there’s no hard feelings between the two of them any longer.” “The two of them” meaning the father and the uncle. “Hard feelings” is anger and resentment, usually because of an argument you had many years ago; it’s very similar to a “grudge.” In fact, sometimes after people have an argument and they make up, they may say, “No hard feelings,” meaning let’s not continue to be angry at each other.
James’ friend asks him if he’s going to go to the reunion, “So you’ll go to the reunion?” Eri says. James says, “I’m not sure. My mother’s side of the family has always looked down on my father’s.” “To look down on (someone)” means not to like someone because you don’t think they’re as good as you; you think you’re better than them; you disapprove of them. You should never look down on people who have less money than you, because you’re not necessarily any better than they are. But unfortunately, the mother of James – her “side of the family,” meaning her relatives, have always looked down on James’ father’s side of the family. “Look,” by the way, has many different definitions in English, as you probably know. Take a look at the Learning Guide for some additional explanations.
James says that his mother comes from old money. The expression “old money” refers to a very rich family that has had a lot of money for many years, maybe even many generations – 50, 60, 100 years. The opposite of “old money” would be “new money”; usually we use the French expression “nouveau riche” to refer to people who have recently made money, but there’s a very negative connotation to that – a very negative idea. When you say “nouveau riche” you’re usually looking down on those people, saying that they’re trying to be part of rich society; they’re trying too hard to be accepted by old money. In any case, I don’t have either old money or new money, so it doesn’t really matter to me!
James says that his mother comes from old money and her family didn’t approve of her marrying his father. “To approve of” means you think it’s a good idea; you support it. So, James says that his mother had a very difficult time. “It was really hard on my mother,” he says, “She really looked up to her own mother and they were really close before my father came along.” So he’s saying that his mother looked up to his grandmother. “To look up to” is the opposite of “to look down on.” “To look up to” means to admire, to respect, to think that someone is a very good person, someone that you want to be like. So, his mother and his grandmother got along very well, “they were really close,” meaning they had a lot of affection, a lot of love for each other; they would talk to each other a lot. They were really close before his father came along. To say he “came along” means that he became part of the situation, he came into the life of James’ mother. “Close” is another word that has many meanings in English, so again take a look at our Learning Guide for some more information on that.
Eri says, “But that’s ancient history, isn’t it?” “Ancient history,” when used in a conversation, means something that happened a long time ago, that most people don’t think is important or don’t even remember anymore. “Ancient history,” if you are talking about a subject in school, would refer to ancient civilizations: the ancient Greeks, the ancient Romans in Western Europe, for example. But here, if someone says, “Oh, that’s ancient history,” they mean nobody remembers that, that was a long time ago and is no longer important. She says, “Considering how things turned out, your grandmother can’t hold it against your mother for marrying your father.” The expression “to turn out,” or the verb “to turn out” means to happen or to end in a somewhat unexpected way, especially after a long period of time. It isn’t always, however, unexpected. You may be watching a football game or a baseball game and then you have to leave before it’s over; later, you may ask your friend, “How did the game turn out?” What was the result? So here, she’s saying that considering the result – considering how things turned out, your grandmother can’t hold it against your mother. “To hold (something) against (someone)” means to blame someone for something, to think that something bad that happened is some particular person’s fault. In this case, the grandmother is angry at James’ father for marrying James’ mother.
James says, “You’ve never met my grandmother (you don’t know my grandmother). One thing everyone knows about her is this: She doesn’t know the words to forgive and forget.” This is an old expression, “to forgive and forget.” The idea is that you should not blame people or be angry with people for things that happened in the past – bad things. Instead, you should forgive them; say, “Oh, that’s okay,” and then forget about it, not think about it anymore. When James says “she doesn’t know the words,” he means she has never heard – or more importantly here, she doesn’t believe in the expression “to forgive and forget.” She will never forget.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Eri: What’s that?
James: It’s an invitation to a family reunion. Once every five years or so, someone in the family organizes one.
Eri: Are you going?
James: I’m not sure. It’s always a little awkward seeing extended family. Did you know that there used to be a big feud between my father and his brother?
Eri: No, what happened?
James: I’m not sure, but it was something that happened before they got married. My father held a grudge for years. Then, about eight years ago, they made up. There’s still no love lost between their wives, but at least there are no hard feelings between the two of them any longer.
Eri: So you’ll go to the reunion?
James: I’m not sure. My mother’s side of the family has always looked down on my father’s. She comes from old money and they didn’t approve of her marrying my father. It was really hard on my mother. She really looked up to her mother and they were really close before my father came along.
Eri: But that’s ancient history, isn’t it? Considering how things turned out, your grandmother can’t hold it against your mother for marrying your father.
James: You’ve never met my grandmother. One thing everyone knows about her is this: She doesn’t know the words to forgive and forget.
[end of dialogue]
Today’s dialogue turned out pretty well, I think, thanks to Dr. Lucy Tse, who wrote it.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
family reunion – an event where relatives meet, usually for a few days, to reconnect and strengthen their relationships with one another
* Last summer, we went to our family reunion and met a lot of cousins for the first time.
extended family – relatives who are not in one’s immediate family; relatives who are not one’s parents, children, brothers, or sisters
* Her extended family includes six uncles and more than 20 cousins.
feud – a very serious, long argument between two people or groups of people; an argument that lasts for a very long time
* The two sisters have had a five-year feud over who should get their great-grandmother’s paintings.
to hold a grudge – to continue to be angry about something that happened a long time ago, especially if the other person has already apologized or if there is no real reason to still be angry
* Siegen is still holding a grudge against me for hitting his car, even though it happened more than 10 years ago.
to make up – to end an argument and become friendly again
* You and your brother haven’t spoken to each other in days. It’s time to tell him you’re sorry and make up.
no love lost – without feelings of love, affection, respect, or friendship
* There’s no love lost between Maude and Gretchen. They try to stay as far away from each other as possible.
hard feelings – resentment and anger, especially because of an argument or something that happened in the past
* I hope you don’t have hard feelings about me getting the job that we both applied for.
to look down on – to disapprove of; to not like, especially because one thinks one is better, more important, or more valuable
* Ophelia looks down on her neighbor because he’s a garbage collector and she thinks it’s an unimportant job.
old money – a rich family that has always had a lot of money and power, that is passed down from one generation to the next
* How many U.S. presidents have come from old money?
to approve of – to think that something is a good idea and support it
* What percentage of the population approves of the president’s plan for national health care?
to look up to – to admire and respect; to think that someone is a very good person and try to be like him or her
* I’ve always looked up to Galina. She’s such a smart, strong woman.
close – with an intimate relationship; with a lot of affection or love
* Marlene has been a close friend since we were in the third grade.
ancient history – something that happened so long ago that most people have forgotten about it and it doesn’t seem very important anymore
* Most people think it’s ancient history, but Kimberly is still really angry that her first-grade teacher didn’t think she had a good singing voice.
to turn out – to happen or end in an unexpected way, especially after a long period of time
* Everyone thought the business would fail, but it turned out to be the most successful store in the city!
to hold it against (someone) – to blame someone for something; to think that something bad that happened is the fault of a particular person
* Jose Antonio holds it against his parents that he wasn’t able to go to college. If they had saved more money, they could have helped him pay for school.
to forgive and forget – the idea that one should not blame people for bad things that they have done in the past, and that one should even forget the bad things that were done, because they are no longer important
* Everyone told us we should forgive and forget, but we’re still really angry that our neighbors stole our lawnmower.
Comprehension Questions
1. Who would be part of your extended family?
a) Your parents.
b) Your sisters.
c) Your cousins.
2. What does James mean when he says there’s “no love lost” between his aunts?
a) They look down on each other.
b) They look up to each other.
c) They don’t like each other.
Answers at bottom.
What Else Does It Mean?
to look up to
The phrase “to look up to (someone),” in this podcast, means to admire and respect someone, or to think that someone is a very good person and try to be like him or her: “Most young children look up to their parents.” The phrase “to look the other way” means to ignore something bad that is happening and not try to stop it: “Most people knew about the accounting problems, but they just decided to look the other way and not say anything.” The phrase “look what you’ve done” is used when one is very angry about something bad that another person has done: “Look what you’ve done! You spilled red wine all over the carpet.” Finally, the phrase “just looking” is used in a store to tell a salesperson that one doesn’t need help: “A: Do you need help finding anything, ma’am? B: No thank you, I’m just looking.”
close
In this podcast, the word “close” means with an intimate relationship, or with a lot of affection or love: “I feel very close to you, so I’m going to tell you a secret.” The phrase “close, but no cigar” is used to talk about something that almost happened or almost worked correctly, but didn’t: “Our team lost 6-7. Close, but no cigar.” The phrase “too close for comfort” is used to describe something bad or dangerous that almost happened, making one scared or frightened: “That tornado was too close for comfort! We’re going to move to a part of the country with fewer windstorms.” Finally, the phrase “close quarters” is used to describe things that happen in a small space with many other people: “I’d go crazy if I had to live in such close quarters all the time.”
Culture Note
Family reunions are often “attended by” (with the participation of) relatives who haven’t seen each other in years, or perhaps have never met. That’s why a typical family reunion begins with “icebreakers,” or social activities that are designed to help people introduce themselves and feel comfortable speaking to other people for the first time.
After doing icebreakers, the people at a family reunion often play games. These might be “board games” (games played on a table), card games, or sports, like baseball and volleyball. There is usually a lot of “storytelling,” where people “reminisce” (talk about things that happened long ago) and share family stories.
Sometimes people share their old family photographs, asking relatives to help them “identify” (find the name of) who the people are and tell stories about them. Older family members may have more information about when photos were taken and how those individuals “fit into” (had a place in) the family. People who are interested in “genealogy” (the study of a family’s past relations) might ask the oldest relatives to share everything they know about the family’s history.
Family members might try to make a “family tree,” or a large drawing showing how people are related to each other. Similarly, a “family map” can be used to show where family members live.
Many people take photos at family reunions, and sometimes there is a “photography session,” where a professional photographer is hired to take pictures of everyone there. These photos are saved “for posterity” (for future generations).
Other family reunions are “less structured” (with fewer plans or activities), and people just spend their time eating, talking, and playing together. No two family reunions are “alike” (the same), because no two families are alike!
Comprehension Answers
1 - c
2 - c