= 0542
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 542: Renting a Movie.
This is English as a Second Language Podcast episode 542. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
You can support this podcast by becoming a member of ESL Podcast. Go to our website at eslpod.com to find out what you get for being a member, it includes our Learning Guide for each and every episode we currently produce. You can also support this podcast by making a small donation on our website as well.
This episode is called “Renting a Movie.” It is a dialogue between Brenda and Jang, talking about renting movies to watch at home. Let’s get started.
[start of dialogue]
Brenda: I have to return these movies in the drop box today or I’ll have late fees. Can I get you anything while I’m out?
Jang: Are you still renting movies from the video store? I use a service that delivers the movies to my mailbox. There are never any late fees.
Brenda: I’ve thought about subscribing to one of those services, but I think I would really miss browsing at the video store. I like checking out the new releases and staff picks, and you never know what you’ll find to buy in the bargain bins.
Jang: Renting movies online is so much quicker and easier. I can browse the titles quickly, read the descriptions, read reviews, and sometimes even watch a trailer. Then, all I need to do is put the movie in my queue, and as soon as I mail one movie back, they send me another one. It’s that simple.
Brenda: It does sound easy, but not everything that’s easy is better. Some of us like to take our time to make our selections.
Jang: Whatever. If you want to spend your time looking for movies rather than watching them, that’s your prerogative.
Brenda: Are you really going to let me off so easily? I thought I was in for another one of your lectures.
Jang: You can lead a horse to water, but you can’t make it drink.
[end of dialogue]
Our dialogue begins when Brenda says, “I have to return these movies in the drop box today or I’ll have late fees.” A “drop box” (two words) is a large box – a large square container that has an opening were you can put things into it, usually to return something to a store; it could also be a public library. Most libraries, as well as video rental stores, have boxes that you can put the movie into and you don’t have to go in and talk to anyone. You just return the movie by putting it into the drop box. There’s another verb “to drop off,” a two-word phrasal verb, which means to leave something for someone else. So, you can drop off your movies in a drop box when you’re finished watching them. Brenda says she needs to return the movies or she’ll have late fees. A “late fee” is an amount of money that you pay as a penalty for bringing something back late. So if you rent a movie, and you return it three days late, you’ll probably have to pay a late fee: maybe 5 dollars maybe 10 dollars, it depends on the store. For the libraries, you may have to pay a quarter, you may have to pay a dollar; again, it depends on the library. But, those are late fees; they could also be called a “fine” or a “penalty.”
Brenda then asks Jang, “Can I get you anything while I’m out?” Jang says, “Are you still renting movies from the video store?” “To rent,” as you probably know, means to pay to use something for a short period of time. You can rent a car; you can rent a house; you can rent a movie. I read somewhere that in some places you can also rent a dog or a cat. I’m not sure why anyone would do that. But if you want to, this is America, you can do whatever you want, they say. Anyway, Jang asks Brenda, “Are you still renting movies from the video store?” The “video store” is the place that you rent, nowadays, DVDs. I guess in some video stores, you can still rent the old VHS cassette tapes. Jang says, “I use a service that delivers the movies to my mailbox,” meaning the movies are mailed to his house or apartment. “There are never any late fees.”
Brenda says, “I’ve thought about subscribing to one of those services, but I think I would really miss browsing at the video store.” “To subscribe” means to pay for a service each month. Usually you pay a little bit every week or every month to continue having a certain service. If you have satellite or cable television, you have to subscribe. You have to pay a monthly fee in order to get that service; it could be anywhere from 25 to 125 dollars. Brenda says that she doesn’t want to subscribe to one of these services because she thinks she would miss browsing. “To browse” (browse) means to looks slowly at what is available in a store, to look and see if there’s anything new or interesting. It’s when you are not necessarily looking for one specific thing, but you just sort of want to see what is available. Brenda says, “I like checking out the new releases and staff picks, and you never know what you’re going to find to buy in the bargain bins.” She says she likes checking out. “To check out” is a two-word phrasal verb meaning to look at something, to see something. Sometimes this expression is used between people. If you say, “The man was checking out the woman walking down the street,” that means that he was looking at her in some sort of romantic or perhaps sexual way. But here, in general “to check out” just means to find out, to investigate, to look at something in this case. “New releases” are things that have just been published. When a DVD movie is first released, meaning you can first get it – first made available, that would be called a new release. “Staff picks” are when the people who work at the video store recommend movies to other people. So there’s usually a separate section, and below are the names of someone who works at the store who recommends movies. The idea being that someone who works at the video store may know a lot about movies; that isn’t always true. Brenda says she likes to check out the new releases and staff picks, “and you never know what you’ll find to buy in the bargain bins.” A “bin” is a large box. A “bargain” is something that is cheap, something has a low price or a good price for what it is worth. A “bargain bin,” then, is a big box that has things in it that are cheap – cheap to buy. In a video store, the bargain bin would be movies – DVDs that the store was selling, not just renting.
Jang says that renting movies online is so much quicker and easier. He says, “I can browse the titles quickly, read the descriptions, read reviews, and sometimes even watch a trailer.” A “review,” in this case, is a written opinion that somebody has about the movie. The word “review” has several different meanings however; take a look at our Learning Guide for additional explanations. A “trailer” is a short video advertisement for the movie. It’s like a movie commercial that tells you a little bit about the movie and what it is about. Jang says, “Then, all I need to do is put the movie in my queue, and as soon as I mail one movie back, they send me another one. It’s that simple.” A “queue” (queue) is a list of things, in a particular order, that are being waited for – things that you are waiting for. Or, if you are waiting for something yourself in a line, that could also be called a queue. That use of the word is a little more common in British English; here we would just say, “I was waiting in line.” I was standing in line. “Queue,” in this dialogue, means the list of movies that you want to rent. So if you rent movies online, you can pick the movies you want, and then they will send them to you when you send a movie that you already rented back. What happens is they mail you, usually, two or three movies at a time, and you can only have two or three movies rented at one time. You have to return – that is, mail your DVD back to the company, and they will mail you a new movie, the next movie on your queue.
Brenda says, “It does sound easy, but not everything that’s easy is better. Some of us like to take our time to make our selections.” “To make your selection” is just another way of saying to select, to choose. Jang says, “Whatever.” “Whatever,” in this case, is used to show that you either don’t believe what a person is telling you or you don’t agree with what another person has said. It’s an informal expression; it’s a negative expression. You wouldn’t want to say it to anyone that was in authority over you, like your boss, certainly not to someone that you don’t know – unless you don’t like the person anyway, I’m not sure. “Whatever” can mean other things as well; once again, the Learning Guide will give you more information about how to use this word.
Jang says, “If you want to spend your time looking for movies rather than watching them, that’s your prerogative.” A “prerogative” is your right, something that you are allowed to do. Brenda says, “Are you really going to let me off so easily? I thought I was in for another one of your lectures.” “To let (someone) off easily” means not to fight someone. You could argue with them, you could fight with them but you decide, eh, it’s not worth your trouble. You decide to let them off easily. Brenda says that she thought she was going to get another one of Jang’s lectures. A “lecture” is normally a speech that a professor would give to his students – a presentation. But when you use it in an informal sense, it’s almost always a negative description of someone who is telling you what you should do, as if they were your professor. Teenagers might complain that their parents are always lecturing them; they’re always giving them lessons, usually about the things that they’re doing wrong. But of course, teenagers do a lot of things wrong, so it’s hard to blame the parents!
Jang says, “You can lead a horse to water, but you can’t make it drink.” This is an old expression. It means that you can tell a person what to do, and give him or her opportunities to do it, but you can’t force someone to do something. They have to want to do it. So, you can lead a horse to water – you can bring a horse, the animal, to a bucket of water, say – but you can’t force the horse to drink. So, this is an old expression. What Jang is saying is that he has given Brenda the information she needs about renting online, if she doesn’t want to use it then that’s her decision – that’s her problem.
Now let’s listen to the dialogue again, this time at a normal speed.
[start of dialogue]
Brenda: I have to return these movies in the drop box today or I’ll have late fees. Can I get you anything while I’m out?
Jang: Are you still renting movies from the video store? I use a service that delivers the movies to my mailbox. There are never any late fees.
Brenda: I’ve thought about subscribing to one of those services, but I think I would really miss browsing at the video store. I like checking out the new releases and staff picks, and you never know what you’ll find to buy in the bargain bins.
Jang: Renting movies online is so much quicker and easier. I can browse the titles quickly, read the descriptions, read reviews, and sometimes even watch a trailer. Then, all I need to do is put the movie in my queue, and as soon as I mail one movie back, they send me another one. It’s that simple.
Brenda: It does sound easy, but not everything that’s easy is better. Some of us like to take our time to make our selections.
Jang: Whatever. If you want to spend your time looking for movies rather than watching them, that’s your prerogative.
Brenda: Are you really going to let me off so easily? I thought I was in for another one of your lectures.
Jang: You can lead a horse to water, but you can’t make it drink.
[end of dialogue]
This new release of ESL Podcast was written by Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2009 by the Center for Educational Development.
Glossary
drop box – a large box or an opening in a wall where one can return things, like rented movies or library books
* The library has a drop box right next to the parking lot, so people can return books without getting out of their car.
late fee – an amount of money paid as a penalty for returning something later than one should have returned it, or for paying a bill later than one should have paid it
* Each time we miss the deadline for paying our credit card bill, we’re charged a $39 late fee, plus interest.
to rent – to pay for the use of something for a short period of time
* We’re going to rent some power tools from the hardware store so that we can build a new fence without buying all the expensive equipment.
video store – a business that owns many DVDs and/or VHS tapes and lets people pay to borrow them for a short period of time
* Ever since we got cable movie channels, we haven’t been going to the video store because it’s easier just to watch movies on television.
to subscribe – to pay for a service each month; to pay a little each week or month for a continuing service
* Do you subscribe to any news magazines?
to browse – to slowly look at what is available in a store, looking to see what is new or interesting, but not searching for something specific
* - Welcome to our store. Can I help you find something?
* - No thanks. I’m just browsing. You have some beautiful things here.
to check out – to look at something; to see something; to find out what is available
* Check out these photographs! They’re really interesting.
new release – something that has just been published or made available for sale
* All the new releases are at the front of the music store.
staff pick – a product that is recommended by the people who work at the store where it is sold
* Our bookstore always has staff picks on display, so as a new employee, you’ll need to pick one book each week that you’d recommend to our customers.
bargain bin – a large box in a store that is filled with products whose price has been reduced a lot
* Can you believe she found that gorgeous sweater for just $6 in a bargain bin?
review – a written opinion about the quality of a book, movie, or TV show, often read by other people who are trying to decide whether they want to read or watch a particular thing
* All the reviews said that movie was wonderful, but I didn’t really like it.
trailer – a short video advertising a movie, showing several scenes from that movie and telling viewers what the movie is about
* Jimmy saw a trailer for a new animated movie last week, and he can’t stop talking about it! We’ll definitely need to take him to see it when it’s in the theaters.
queue – a list of things that are being waited for in a particular order, so that the first item in the queue is the first thing used or done
* This email program puts all outgoing emails in a queue and sends them out in that order.
to make (one’s) selection – to select; to choose
* Once you’ve made your selection, put $0.50 in the machine and then you’ll hear your song.
whatever – a word used to show that one does not believe or agree with what another person has said
* - If you become a vegetarian, you’ll feel great and have so much energy!
* - Whatever. I’m going to get a hamburger.
prerogative – a right or advantage; something that a person is allowed to do
* If you want to get a dog, that’s your prerogative, but don’t expect anyone to help you take care of it.
to let (one) off easily – to not fight against a person’s opinion or decision
* When Rivero decided to drop out of school, his parents let him off too easily. They should have told him “no.”
you can lead a horse to water, but you can’t make it drink – a phrase meaning that one can tell a person what to do and give him or her opportunities to do it, but ultimately one cannot force that person to do something
* He bought her a new suit and helped her prepare for the interview, but at the last minute, she decided not to interview for the job. You can lead a horse to water, but you can’t make it drink.
Comprehension Questions
1. Why does Brenda like checking out the staff picks?
a) Because she likes to have the employees pick out a movie for her.
b) Because she likes to know what other people have enjoyed watching.
c) Because she wants to know whether there’s an opening on staff.
2. Why does Jang like renting movies online?
a) Because he can get them right away.
b) Because he can learn a lot about the movies.
c) Because he can find good bargains.
Answers at bottom.
What Else Does It Mean?
review
The word “review,” in this podcast, means a written opinion about the quality of a book, movie, or TV show, often read by other people who are trying to decide whether they want to read or watch a particular thing: “Jurgen always reads the reviews before buying a new book.” The word “review” also means an examination of something, especially to decide whether it is good or bad: “The federal government is conducting a review of its healthcare policies.” Sometimes a “review” is a written report: “Is anyone writing a review of the recent research on the housing market?” Finally, a “review” can be a section in a chapter or book that reminds readers of what they have read or studied, especially so that they can prepare for a test: “It’s a good idea to study the chapter review before class, because the professor always asks questions from that section.”
whatever
In this podcast, the word “whatever” is used to show that one does not believe or agree with what another person has said: “When Holly told Gregory that she never lies, he said, ‘Whatever. And I suppose you can walk on water, too.’” The word “whatever” can also be used to show that one does not have a preference, and will do what the other person wants: “‘Do you want to go to the movies or the circus?’ ‘Whatever. You decide.’” The phrase “whatever you do” is used to warn a person not to do something, no matter what else happens: “Whatever you do, don’t open that door!” Finally, the phrase “or whatever,” is used at the end of a list to mean any other similar thing: “We can go hiking, fishing, camping, or whatever.”
Culture Note
“Movie studios” (large companies that product movies) make millions of dollars in “ticket sales” (money made when people buy tickets to see a movie in a movie theater), but DVD sales can also be a major “moneymaker” (something that makes a lot of money for a person, business, or organization) for them.
Most Americans have a DVD player in their home, and they often enjoy buying DVDs of their favorite movies, so that they can watch them over and over again. Many DVDs have “bonus features” (things that are not included in the original movie). These include “commentaries,” where the director or an actor “narrates” (says) what is happening or shares information about how the movie was made. Other bonus features are “deleted scenes” (acting that was filmed and edited, but not included in the final movie) and “bloopers” (funny mistakes that the actors made while they were being recorded). There are also many “making-of” features, where people can learn more about how the movie was made.
Sometimes studios create “special edition releases” of old movies. For example, they might take an old black-and-white movie and add color, or improve the “soundtrack” (the quality of the voices, music, and other sounds included in a movie) so that they can sell it on DVD. Some of these become “collector’s items” (things that people want to have because they are special and only a limited number of them are available).
Some DVDs are made for movies that never “made it to” (arrived at) the theaters. These are often “low-budget films” (made without a lot of money) known as “direct-to-video” or “straight-to-DVD” films. People see these films only by watching them at home on DVD, because they aren’t shown in the theaters.
Comprehension Answers
1 - b
2 - b