= 0601
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 601: Paying an Unexpected Visit.
This is English as a Second Language Podcast episode 601. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
If you’d like to support our podcast and keep these audio files coming, you can become a member of ESL Podcast. If you become a member, you also will get our Learning Guides, an 8- to 10-page guide we provide for all our current episodes that will help you improve your English even faster.
This episode is called “Paying an Unexpected Visit.” It’s a dialogue between Lorraine and Terrance using a lot of vocabulary that we might associate with or hear for someone who is visiting someone else. Let’s get started.
[start of dialogue]
Lorraine: Hi, this is a surprise. To what do I owe this pleasure?
Terrance: Can’t I just drop in on my little sister unannounced to see how she is? I was just in this neck of the woods and thought I would pay you a visit.
Lorraine: Sure you were. Of course, I’m glad to see you, but this is just a little out of the blue.
Terrance: What do you mean?
Lorraine: I haven’t seen you in over five months, and you just happened to be in the neighborhood?
Terrance: Well, I wasn’t exactly in the neighborhood, but I wanted to see my favorite sister.
Lorraine: Your only sister. Okay, out with it. What are you doing here?
Terrance: Uh, well, I was thinking of taking a year off from school to pursue my art. I really feel I need to devote some time to my painting to see if I can make it as an artist.
Lorraine: Mom and Dad are not going to like that.
Terrance: I know and that’s where you come in.
Lorraine: You want me to run interference for you with Mom and Dad.
Terrance: Yeah, they would take it a lot better coming from you, don’t you think?
Lorraine: No, I don’t.
Terrance: You’ve always been the responsible one…I’m just saying…
Lorraine: And I’m just saying that I’m not going to do your dirty work for you!
[end of dialogue]
Lorraine says at the beginning of our dialogue, “Hi, this is a surprise. To what do I owe this pleasure?” “To what do I owe (owe) this pleasure?” is a very formal expression meaning why are you here and how can I help you, or what are you doing here. It’s usually something you would say if you weren’t expecting someone, and it is often used sarcastically. That is, the person is making a joke; they don’t really think that you being here is a pleasure.
Terrance says, realizing that Lorraine is joking with him and, in some ways, saying that she doesn’t really want him there, “Can’t I just drop in on my little sister unannounced to see how she is?” “To drop in” is a two-word phrasal verb meaning to come for a short, informal visit without letting the person know ahead of time. So you don’t call them on the phone or email them; you just go over to their house, knock on their door, and visit them. Many people don’t like that, especially in the United States you usually don’t drop in on people. Well, that’s what Terrance is doing to Lorraine. The verb “drop” has several other meanings in English; you can find those in the Learning Guide for this episode.
Terrance is dropping in on his little (meaning in this case his younger) sister unannounced. “Unannounced” means without letting someone know that you are doing something or that something will happen. It’s another way of saying “unexpected.” Terrance says, “I was just in this neck of the woods and thought I would pay you a visit.” The expression “neck (neck) of the woods (woods)” means the general area where that person is living; we might also say “in the neighborhood.” I was just in the neighborhood – I was just driving near your house is the idea – and I decided I would come and pay you a visit. “To pay (someone) a visit” means the same as to visit someone, to come and see someone at his or her home or office.
Lorraine doesn’t believe Terrance. She says, “Sure you were,” but she says it in such a way that she is communicating the opposite, meaning I don’t believe you were. She says, “Of course, I’m glad to see you, but this is just a little out of the blue.” Something that is “out of the blue” is something that is unexpected, something that you were not warned about, that you didn’t realize was going to happen. Terrance says, “What do you mean?” Lorraine responds, “I haven’t seen you in over five months, and you just happened to be in the neighborhood?” “Happened to be” means by chance, accidentally, without planning it ahead of time. Terrance says, “Well, I wasn’t exactly in the neighborhood (meaning I wasn’t exactly close to your house), but I wanted to see my favorite sister.” Lorraine says, “Your only sister.” Of course, Terrance, since he has only one sister, can only have her as the favorite one. Then she says, “Okay, out with it. What are you doing here?” The expression “out with it” is used when you are telling someone to say what they are thinking or to give you the answer directly, not to hide anything or to keep delaying the answer – tell you right away: “out with it.” It’s an informal expression. There are lots of different expressions with “out,” some of them can be found in the Learning Guide for this episode.
Terrance says, “Uh, well, I was thinking of taking a year off from school (meaning stop studying in college for a year) to pursue my art.” “To pursue” (pursue) means to do something for a long time, usually when you are trying to achieve something or get something. People pursue their Ph.D.s – their doctorates. They go back to college for many years and pursue that degree. Terrance wants to quit school and pursue his art, whatever that is. He says, “I really feel I need to devote some time to my painting to see if I can make it as an artist.” “To devote” means to spend a lot of time, money, or other resources for a particular purpose. “I devote 40 hours a week to my job,” that’s what I commit, that’s what I spend. Or, “We’re going to devote 100 dollars to buying a present for my brother,” that’s what I’m going to commit, that’s what I’m going to promise. Terrance wants to devote time to his painting to see – to determine if he can make it as an artist. “To make it” means to be successful in a particular job or field, or to become famous. Many people come to Los Angeles to make it in the movie industry or to make it in the music industry, to become a star of the movies or to become a popular singer. Most of them end up working as waiters and waitresses. Here in Los Angeles, we have the most talented waiters and waitresses in America!
Lorraine says, “Mom and Dad are not going to like that.” They’re not going to like the idea that Terrance is quitting school to devote time to painting. Terrance says, “I know and that’s where you come in.” The expression “that’s where you come in” is used to emphasize how another person is involved in something. When you’re explaining something to someone and you are asking for them to help you, you get to the part where you explain what they’re going to do. “That’s where you come in,” Terrance says.
Lorraine says, “You want me to run interference for you with Mom and Dad.” “To run interference” means to help someone do something by being what we might call a “mediator,” that is, someone who is in between the two people who are trying to communicate. You might share information with this other person. Usually you are trying to avoid problems. If the other person would deal with the third party – the third person directly, there might be problems, so you’re in between them and you’re trying to prevent those problems. That’s what Terrance wants Lorraine to do.
Terrance then says, “Yeah, they would take it a lot better coming from you, don’t you think?” “To take it” means – or “to take (something)” means to react to something, to deal with something, or to accept something. “How did she take the news?” How did she take it? The idea here is how did she react, how did she accept it: was she upset, was she angry, was she happy, and so forth. Terrance thinks that if Lorraine tells their parents that Terrance wants to become an artist, the parents will take it better hearing it from her.
Lorraine says, “I don’t.” She doesn’t agree the parents will take it better from her. Terrance says, “You’ve always been the responsible one…I’m just saying…” This expression is used a lot nowadays in American English: “I’m just saying.” We use it when you want to emphasize that what you have just said was only an opinion. You don’t want the other person to get angry or offended, and if you think that they might, or that you see they are getting angry you might use this expression. You’re saying that it’s just your opinion.
Lorraine then says, “And I’m just saying that I’m not going to do your dirty work for you!” “Dirty work” is something that a person does not want to do because it is difficult or unpleasant, something you try to get someone else to do, often times when it is something that is perhaps involving some deception or lying to another person. Here, we’re not talking about lying to another person, but we are talking about something that Terrance doesn’t want to do so he is trying to get his sister to do it for him. He’s trying to get his sister to do his dirty work.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Lorraine: Hi, this is a surprise. To what do I owe this pleasure?
Terrance: Can’t I just drop in on my little sister unannounced to see how she is? I was just in this neck of the woods and thought I would pay you a visit.
Lorraine: Sure you were. Of course, I’m glad to see you, but this is just a little out of the blue.
Terrance: What do you mean?
Lorraine: I haven’t seen you in over five months, and you just happened to be in the neighborhood?
Terrance: Well, I wasn’t exactly in the neighborhood, but I wanted to see my favorite sister.
Lorraine: Your only sister. Okay, out with it. What are you doing here?
Terrance: Uh, well, I was thinking of taking a year off from school to pursue my art. I really feel I need to devote some time to my painting to see if I can make it as an artist.
Lorraine: Mom and Dad are not going to like that.
Terrance: I know and that’s where you come in.
Lorraine: You want me to run interference for you with Mom and Dad.
Terrance: Yeah, they would take it a lot better coming from you, don’t you think?
Lorraine: No, I don’t.
Terrance: You’ve always been the responsible one…I’m just saying…
Lorraine: And I’m just saying that I’m not going to do your dirty work for you!
[end of dialogue]
Our scriptwriter devoted a lot of time to today’s episode. I’m, of course, referring to Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
To what do I owe this pleasure? – A formal phrase meaning, “What are you doing here?” or “Why have you come to see me and how can I help you?” often used sarcastically
* Oh! It’s you! To what do I owe this pleasure? Last time we talked, you said you never wanted to see me again.
to drop in – to come for an informal, usually short visit without letting someone know about it ahead of time
* Our neighbors have invited us to drop in for a cup of coffee anytime.
unannounced – without prior notice; without letting one know that something will happen; unexpectedly
* It’s really rude to go to a wedding unannounced. Guests are supposed to be invited.
neck of the woods – neighborhood; the general area where a person lives or works; the surrounding area
* You left your sunglasses at our house last night, but I’ll return them to you the next time we’re in your neck of the woods.
to pay (someone) a visit – to visit someone; to come see someone in his or her home or office
* How often do you pay your grandmother a visit?
out of the blue – unexpectedly; without warning or advance notice
* Out of the blue, he asked her to marry him. What a surprise!
to happen to be – to do something by chance and accidentally, without planning it ahead of time
* It’s great that you just happened to be walking by when that man needed your help!
out with it – a phrase used to ask someone to say what he or she wants to say directly, without delaying or hiding anything
* Come on, out with it! How much money do you need to borrow from me?
to pursue – to engage in an activity over a long period of time, trying to achieve or get something
* Bryan has decided to pursue a Ph.D. in quantum physics.
to devote – to commit to using one’s time, money, or other resources for a particular purpose
* How many hours are you willing to devote to your job each week?
to make it – to be successful or to become famous in a particular field or occupation
* What percentage of new restaurants really make it and are still in business five years after they open?
that’s where you come in – a phrase used to emphasize how, when, and where another person will become involved in something
* I need to call a client in China, but I don’t speak Chinese, so that’s where you come in. I need you to interpret for me.
to run interference – to be a mediator; to help someone do something by sharing information or messages with people who might otherwise create problems or difficulty
* Mindy and her mother have never gotten along very well, but Mindy’s brothers and sisters try to run interference whenever the family gets together.
to take (something) – to react to something; to accept, handle, or deal with something in a particular way
* How did your husband take it when you told him you’d wrecked the new car?
I’m just saying… – a phrase used when one is slightly defensive and wants to emphasize that what one has just said was only an opinion, often used when the other person is angered or offended by what one has just said
* I’m just saying, it might be a good idea to think carefully before dropping out of college to become a clown in a circus.
dirty work – something a person does not want to do because it is difficult, uncomfortable, or unpleasant, and tries to get another person to do instead
* Don’t ask me to call tech support about your cell phone. You do your own dirty work.
Comprehension Questions
1. What does Lorraine mean when she says that the visit “is just a little out of the blue”?
a) She’s feeling depressed.
b) She is very, very happy to see him.
c) She wasn’t expecting to see him.
2. Why did Terrance come to see his sister?
a) Because he missed her a lot.
b) Because he wants her opinion on whether he should be an artist.
c) Because he wants her to talk to their parents for him.
Answers at bottom.
What Else Does It Mean?
to drop in
The phrase “to drop in,” in this podcast, means to come for an informal, usually short visit without letting someone know about it ahead of time: “On our way to Los Angeles, let’s drop in on the Chansons.” The phrase “to drop it” means to stop talking about a subject, usually because it is uncomfortable or is making someone angry: “I’m so tired of hearing you complain about what happened! Just drop it, okay?” The phrase “to drop dead” means to die very quickly and is used when one is very angry with another person: “I hate you! I wish you’d drop dead!” Finally, the phrase “to drop a hint” means to tell someone something indirectly, hoping he or she will understand one’s meaning: “Shannon keeps dropping hints about how much she likes flowers, hoping her boyfriend will understand and buy her some roses.”
out with it
In this podcast, the phrase “out with it” is used to ask someone to say what he or she wants to say directly, without delaying or hiding anything: “Why is it so hard for you to come out with it and say what you want?” The phrase “to be out of it” means to be confused or distracted and to not understand or be aware of what is happening around oneself: “Could you please repeat the question? I was out of it and didn’t hear you.” The phrase “to be out to do (something)” means to plan or intend to do something: “It seems like the boss is out to fire Percy.” Finally, the phrase “out there” is used to describe some other place, not here: “Tammy knows her true love is out there somewhere, waiting for her.”
Culture Note
Traditionally, “college-bound” (planning to go to college) Americans “enroll” (begin a program) in a university in August or September, in the same year they graduate from high school. However, in recent years, more and more American teenagers are choosing to take a “gap year,” or use one year to travel or have an interesting life experience before they go to college.
For many students, a gap year involves traveling through other countries. Some of them simply travel to “see the sights” (visit important landmarks) in other countries. Others travel while “volunteering” (working without pay) in a community or studying a foreign language. They argue that a year spent “overseas” (in another country) helps them “broaden” (widen) their “perspective” (way of understanding and looking at things) on the world while helping them better identify their interests and decide what they want to study in college.
Other people take a gap year for more practical reasons, and not necessarily because they have a choice. Many high school graduates have to work for a few years to “earn” (make money) enough money to pay for tuition. Some people work full-time to save as much money as possible. Others try to attend college part-time while they are working.
Parents often worry that a gap year will make their children less likely to go to college. However, many “prestigious” (well known and respected) universities are encouraging applicants to take a gap year, because they believe the experience makes students more “well-rounded” (with diverse interests) and “mature” (with the ability to be responsible, make good decisions, and act like adults).
Comprehension Answers
1 - c
2 - c