= 0602
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 602: Calling for an Ambulance.
This is English as a Second Language Podcast episode 602. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Download a Learning Guide for this episode. It will give you all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of everything we say.
This episode is called “Calling for an Ambulance.” An “ambulance” is a special truck or car that takes sick people from where they are to a hospital. Let’s get started.
[start of dialogue]
Brad: Are you all right?
Lydia: What…what happened?
Brad: You lost consciousness and someone called 911. My name is Brad and I’m a paramedic. Can you answer a few questions for me?
Lydia: I’ll try.
Brad: Have you ever blacked out before?
Lydia: No, I don’t think so.
Brad: Do you have a history of medical problems? Do you have any allergies to medication?
Lydia: Not that I know of.
Brad: Okay. Where are you hurt? Are you in any pain?
Lydia: I think I hit my head when I fell down. Oh, it’s bleeding. Oh my God, I’m bleeding!
Brad: Stay calm and let me examine the wound.
Lydia: Oh my God, I’m going to bleed to death!
Brad: Try to stay still. The wound doesn’t look too serious, but we’ll get you to the hospital to get checked out. We’ll get a stretcher so we can get you into the ambulance and take you to the emergency room. Try to stay calm.
Lydia: Calm? How can I stay calm when I’m bleeding to death? I need a helicopter to take me to the hospital right away. Call medivac!
Brad: Ma’am, you don’t need a helicopter. I’m just going to give you a little injection to help you with the pain and to help you relax.
Lydia: I’m going to die…I’m going to…
Brad: Phew!
[end of dialogue]
Our dialogue begins with Brad asking Lydia, “Are you all right (are you okay)?” Lydia says, “What…what happened?” She seems confused. Brad says, “You lost consciousness and someone called 911. My name is Brad and I’m a paramedic. Can you answer a few questions for me?” Brad is a paramedic (paramedic). A “paramedic” is a person whose job it is to provide emergency medical services and treatment, but who is not a doctor or a nurse. They are usually people who go out when there’s an accident, for example, and someone is hurt or injured. The paramedic will go in the “ambulance,” which is a special car or truck that we use to transport – to move people who are sick and injured in an emergency to the hospital. With the ambulance, then, the paramedic will try to help the person who is hurt or injured, and that’s what Brad is doing here.
He says to Lydia, “You lost consciousness.” “To lose consciousness” means to become unaware of where you are for some period of time, often because you have been hit on the head or perhaps you have been drinking too much alcohol. Another way of saying “to lose consciousness,” a little more common, is “to faint” (faint), or “to black out.” Brad says, “someone called 911.” In the United States if you have an emergency, something that you need help with, either medical help or police help, you pick up any phone and you dial 911. Everywhere in the United States that is the emergency telephone number.
Brad asks Lydia if she can answer some questions for him. Lydia says, “I’ll try.” Brad says, “Have you ever blacked out before?” “To black out” is a two-word phrasal verb that we just defined; it means to lose consciousness, to become unaware of where you are. The word “black” has several different meanings in English; take a look at our Learning Guide for some additional explanations. Lydia says, “No, I don’t think so (I don’t think I have ever blacked out before).” I don’t think I’ve ever blacked out either – or maybe I did and I don’t remember.
Brad says, “Do you have a history of medical problems?” A “history of” here means past occurrences, past events, a record of things that happened in the past. “My father had a history of heart attacks,” meaning he had several heart attacks in the past. Or, you could say, “She has a history of mental illness,” she’s not thinking correctly; she’s a little crazy. That would describe my neighbor! Brad says, “Do you have any allergies to medication?” “Medication” is just another word for medicine or drugs. “Allergies” are physical reactions that occur – that happen when you eat something or touch something, or in this case, take some sort of medicine. Some people have allergies to certain plants, some people have allergies to cats, some people just don’t like cats, it just depends on who you are.
Lydia says that she doesn’t know of any allergies that she has. She says, “Not that I know of,” meaning no, I don’t think so. We use “not that I know of” when we don’t think it’s true but we may not know for sure. Brad says, “Okay. Where are you hurt? Are you in any pain?” Lydia says, “I think I hit my head when I fell down. Oh, it’s bleeding.” “To bleed” (bleed) means to lose blood. Your red blood comes out of your skin and you are, therefore, bleeding. If you cut yourself, for example, you will bleed.
Lydia says, “Oh my God, I’m bleeding!” She’s getting very excited now that she knows that she’s been bleeding. Brad tells her to stay calm, don’t get excited. He asks her to let him examine the wound (wound). A “wound” is an injury, when you hurt yourself, especially if your skin has been cut and you are bleeding. That is often what we mean when say someone has a wound. “Wound” can also be a verb: “to wound (someone)” means to hurt them.
Lydia says again, “Oh my God, I’m going to bleed to death!” meaning I’m going to lose so much blood that I will die. Lydia is panicking; she is not staying calm. Brad says, “Try to stay still,” meaning don’t move, stay in this position. “Try to stay still. The wound doesn’t look too serious, but we’ll get you to the hospital to get checked out.” “To get checked out,” in this case, means to be examined, to be searched for problems or anything unusual. Here, it means the doctor is going to examine her to make sure she is okay. Brad then says, “We’ll get a stretcher so we can get you into the ambulance and take you to the emergency room.” A “stretcher” is a special bed on wheels that they use in hospitals to move people who cannot walk on their own. They’re going to put her on a stretcher and put her into the ambulance, and then go to the emergency room. The “emergency room” is the part of the hospital where people go when they need to be treated right away. If they are shot or cut or having a heart attack, you would take someone to the emergency room.
Brad then says, again, to Lydia, “Try to stay calm.” Lydia says, “Calm? How can I stay calm when I’m bleeding to death? I need a helicopter to take me to the hospital right away.” A “helicopter” is something like an airplane, a machine, but it goes straight up in the air and is able to fly. Lydia is asking for a helicopter to take her to the hospital, she thinks she is seriously hurt. She says, “Call medivac!” “Medivac” stands for medical evacuation; it’s an emergency service that moves people very quickly using helicopters, usually because they are a long way from the hospital. This is not a situation where you need a helicopter, but Lydia is panicking and so that’s what she says.
Brad says, “Ma’am, you don’t need a helicopter. I’m just going to give you a little injection to help you with the pain and to help you relax.” An “injection” is also called a “shot,” it’s when a doctor or a nurse puts a piece of metal into you, what we would call a “needle,” and uses that to “inject,” or put into your body medicine or drugs.
Lydia is very excited. Brad calms her down by giving her something to relax her and to help her with the pain. She says, “I’m going to die…I’m going to…” and then she falls asleep, and Brad expresses relief – happiness; he says, “Phew!”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Brad: Are you all right?
Lydia: What…what happened?
Brad: You lost consciousness and someone called 911. My name is Brad and I’m a paramedic. Can you answer a few questions for me?
Lydia: I’ll try.
Brad: Have you ever blacked out before?
Lydia: No, I don’t think so.
Brad: Do you have a history of medical problems? Do you have any allergies to medication?
Lydia: Not that I know of.
Brad: Okay. Where are you hurt? Are you in any pain?
Lydia: I think I hit my head when I fell down. Oh, it’s bleeding. Oh my God, I’m bleeding!
Brad: Stay calm and let me examine the wound.
Lydia: Oh my God, I’m going to bleed to death!
Brad: Try to stay still. The wound doesn’t look too serious, but we’ll get you to the hospital to get checked out. We’ll get a stretcher so we can get you into the ambulance and take you to the emergency room. Try to stay calm.
Lydia: Calm? How can I stay calm when I’m bleeding to death? I need a helicopter to take me to the hospital right away. Call medivac!
Brad: Ma’am, you don’t need a helicopter. I’m just going to give you a little injection to help you with the pain and to help you relax.
Lydia: I’m going to die…I’m going to…
Brad: Phew!
[end of dialogue]
Our script was written by someone who always stays calm, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
to lose consciousness – to faint; to black out; to become unaware of where one is and what is happening around oneself for a period of time, often because one has been hit on the head or has had too much to drink
* Have you ever had so much alcohol that you lost consciousness?
911 – an emergency number that can be dialed on any telephone in the United States to be connected with emergency services (police, ambulance services, firefighters, poison control center, etc.)
* When Jackie heard strange sounds in the middle of the night, she called 911 and asked them to send a police officer to her home.
paramedic – a person whose job is to provide emergency medical services to stabilize a patient, but is not a doctor or nurse
* The paramedics made sure the little girl continued to breathe on the way to the hospital.
to black out – to lose consciousness; to faint; to become unaware of where one is and what is happening around oneself for a period of time, often because one has been hit on the head or has had too much to drink
* Sheila blacked out when the baseball hit her on the head, but she was fine within a few minutes.
a history of – past events; records of things that have happened in the past
* His father has a history of heart attacks, but the last one was almost 10 years ago.
allergy – a physical reaction that occurs when one eats or touches something, usually causing breathing problems or red, itchy skin
* Angel has an allergy to cats, so whenever he comes to visit, we have to put our cats outside and vacuum really well.
to bleed – to lose blood; for a warm, sticky, red liquid to come out of a cut or other opening in one’s skin
* Your dog bit my son, and now he’s bleeding!
wound – an injury, especially when the skin has been cut or otherwise opened
* Many animals lick their wounds until they stop hurting.
to stay still – to not move; to remain in one position
* It seems like it’s impossible for two-year-olds to stay still for more than a few seconds!
to get checked out – to be examined; to be searched for problems or anything unusual
* It’s a good idea to get a used car checked out by a professional mechanic before deciding to buy it.
stretcher – a special bed on wheels, used in hospitals to move people who cannot walk for medical reasons
* The doctors used a stretcher to move the unconscious patient from the operating room to the recovery room.
ambulance – a large vehicle used to move people from where they were hurt to a hospital, with room for the patient to lie down, full of medical instruments, equipment, and medicine
* Did you ride an ambulance to our hospital, or did your wife drive you here?
emergency room – the part of a hospital where people can go when they are having a medical emergency and must be seen by a doctor right away, without making an appointment ahead of time
* If your child has a temperature of more than 105 degrees, take him or her to the emergency room.
helicopter – a flying machine that is smaller than an airplane and does not have wings, but instead has one large propeller on the top that moves around to keep the device in the air
* The news channel uses a helicopter to take pictures of the cars on major streets and highways and to find out which roads are the busiest during rush hour.
medivac – medical evacuation; an emergency service that moves injured people very quickly from where they were hurt to a hospital, usually by helicopter
* The rock climber fell down a cliff and was taken by medivac to a hospital, where doctors tried to save her life.
injection – shot; medication or a vaccination that is pushed into one’s veins (tubes that carry blood through the body) by a sharp needle
* Many people are scared of injections, even though they don’t hurt very much.
Comprehension Questions
1. What happens when a patient blacks out?
a) He or she stops breathing.
b) His or her skin becomes darker from a lack of oxygen.
c) He or she loses consciousness.
2. In most cases, which of these is the fastest way to get to a hospital?
a) In an ambulance.
b) On a stretcher.
c) By medivac.
Answers at bottom.
What Else Does It Mean?
to black out
The phrase “to black out,” in this podcast, means to lose consciousness or to become unaware of where one is and what is happening around oneself for a period of time: “Max felt dizzy and thought he was going to black out, but he felt fine after sitting down and drinking some water.” The phrase “to black (something) out” means to draw a thick, black line through the words printed on a page so that they cannot be read by other people: “After re-reading what she had written, she blacked out almost all the words on the page.” Finally, the phrase “to blacklist (someone or something)” means to put someone or something on a list of things that are bad and should not be used or supported: “If you fight against the labor unions, you’ll be blacklisted and you’ll never find a job in this town again.”
wound
In this podcast, the word “wound” means an injury, especially when the skin has been cut or otherwise opened: “After the earthquake, doctors had to treat hundreds of patients with minor wounds.” The phrase “to open old wounds” means to remind someone of something very painful or hurtful that happened in the past: “Let’s not open old wounds by talking about what happened after Dad died.” The phrase “to rub salt into the wound” means to make a bad situation worse for someone: “Getting a divorce was bad enough, but then my mother rubbed salt into the wound by saying it was my fault.” Finally, the phrase “to lick (one’s) wounds” means to think about something bad that has happened and feel sad about it: “Give her some time to lick her wounds. I’m sure she’ll give you a call when she’s ready to be around friends again.”
Culture Note
In the United States, “EMTs” (“emergency medical technicians”) are “healthcare providers” (people who provide medical care) who help sick and injured people before they can get to a hospital, or while they are “en route” (traveling; on their way) to a hospital.
EMTs are usually the “first responders” (first people to react or arrive) to emergency calls. Doctors and nurses generally don’t travel to the “site” (location) of emergencies, but instead wait for EMTs to bring the patients to them. EMTs work to “stabilize” (put something in a steady, unchanging condition, out of danger) patients and transport them to a hospital. EMTs can “perform” (do) some medical procedures. For example, they can provide “CPR” (cardiopulmonary resuscitation; assisted breathing and heart pumping), “immobilize” (not allow movement of) the body, and “splint” (use materials to hold part of the body still) broken bones.
Some EMTs work for ambulance companies. Other EMTs work for hospitals, fire departments, police departments, or even universities that want to provide emergency medical services for their students. EMTs can “achieve” (get, earn) different levels of certification depending on how much training and experience they have. Training can last anywhere between two weeks and two years.
EMT certifications “vary” (are different) by state, but they all have to meet certain national “standards” (requirements). Some EMTs choose to get specialized certifications for specific areas of medicine, such as “wilderness” (related to undeveloped natural areas) EMTs and flight EMTs. EMTs with the highest level of certification are known as “paramedics.” Each level of certification allows EMTs to perform more medical procedures than EMTs with lower levels of certification.
Comprehension Answers
1 - c
2 - c