= 0630
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 630: Making a Medical Diagnosis.
This is English as a Second Language Podcast episode 630. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download a Learning Guide for this episode, an 8- to 10-page guide that gives you the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of this entire episode.
This episode is called “Making a Medical Diagnosis,” when you go to a doctor and he or she tells you what your medical problem is. Let’s get started.
[start of dialogue]
Terrell: Where have you been?
Sally: At the hospital, again. My doctor is putting me through another battery of tests.
Terrell: She still hasn’t been able to zero in on the cause of your pain and make a diagnosis?
Sally: No, she hasn’t. Part of the problem is that my symptoms are intermittent, and they seem to flare up only when I’m not under observation. The symptoms themselves are ambiguous, so finding the root cause hasn’t been easy.
Terrell: I can see how that would be mystifying and frustrating. Are you still in a lot of pain?
Sally: The mild pain in my legs seems to be chronic, but the severe pain in my back is occasional.
Terrell: I guess you’re not up for going out tonight.
Sally: After a day of being poked and prodded like a guinea pig, all I want to do is to curl up with a hot cup of tea and a good book!
[end of dialogue]
Terrell begins by asking Sally, “Where have you been?” Sally says, “At the hospital, again. My doctor is putting me through another battery of tests.” Her doctor is putting her through, meaning making her do some things that are perhaps not very pleasant, not very nice, or require a lot of work. What she needs to go through – what her doctor is putting her through is another battery (battery) of tests. A “battery” is a series of things, a group of things. It’s often used with the word “test.” A battery of tests could be used to determine which classes you will take at an English language school. They may give you a speaking test, a writing test, a listening test; we would call those a “battery of tests.” This is a battery of medical tests. A few years ago I went to the doctor because I was having problems with my allergies. My nose would start to run, my eyes would water, my throat would sometimes make me cough; all of these things were related to allergies. So my doctor put me through a battery of allergy tests to determine what the problem was. You can tell today that I still have allergies because my voice is what we would say a little “hoarse” (hoarse). When your voice is hoarse you don’t sound normal; your voice is often lower, more difficult perhaps to understand.
That’s enough of my medical problems! Now back to the dialogue: Sally has gone through a battery of tests. Terrell says, “She (meaning her doctor) still hasn’t been able to zero in on the cause of your pain and make a diagnosis?” “To zero in on (something)” means to identify one thing, one explanation that solves a problem or that gives you an answer, eliminating all of the other possibilities. The doctor is supposed to zero in on the cause of Sally’s pain and make a diagnosis. “To make a diagnosis,” or simply “to diagnose” as a verb, is when a doctor identifies what your illness or medical problem is. Sally’s doctor has not been able to make a diagnosis. Sally says, “No, she hasn’t (she hasn’t zeroed in on the cause yet). Part of the problem is that my symptoms are intermittent, and they seem to flare up only when I’m not under observation.” A “symptom” (symptom) is some usually physical sign that shows you have some illness or disease. So for example if your head starts to hurt and you start to get a fever, where the temperature of your body goes up, that is a symptom perhaps that you have some illness – some disease. Sally’s symptoms are intermittent. Something that is “intermittent” comes and it goes; it’s not constant. It will happen sometimes but then sometimes it won’t happen, so it’s difficult to determine what is going on. “To flare up” is a two-word phrasal verb meaning for a disease or an illness to become worse, often without any warning. Suddenly my nose starts to run, I start to sneeze, I might say my allergies are flaring up; they’re getting worse suddenly. The word “flare” has several meanings in English, some of those are found in your Learning Guide for this episode.
Sally’s symptoms seem to flare up – get worse – only when she’s not “under observation,” meaning only when she isn’t being watched carefully. She isn’t being monitored, we might say. So when the doctor isn’t looking, basically, her symptoms get worse. “The symptoms themselves,” she continues, “are ambiguous.” Something that is “ambiguous” has more than one possible explanation. It’s also a word we use to describe something that is confusing, unclear, difficult to understand. Often when something could have more than one meaning and it isn’t clear which meaning is meant, we say that thing is ambiguous. A question could be ambiguous, for example. Sally’s symptoms are ambiguous – it’s hard to tell what they mean, so finding the root cause hasn’t been easy. The “root (root) cause” of something is the main cause, the main reason why something is happening.
Terrell says, “I can see how that would be mystifying and frustrating.” When something is “mystifying” it is related the idea of a mystery, something we don’t understand. In more general terms, something that is confusing, something that is not clear to you. Terrell asks, “Are you still in a lot of pain?” Sally says, “The mild pain in my legs seems to be chronic, but the severe pain in my back is occasional.” We have two different kinds of pain: we have “mild” pain, which is not strong, not too bad, not serious; and we have “severe” pain, which is very strong, very serious, the opposite of mild. We also have two different descriptions of when this pain occurs – when it happens. “Chronic” (chronic) pain continues for a long time, especially when it is related to a disease that doesn’t have a cure – there’s no way to make the illness go away. “Occasional” pain is pain that happens every once in a while. Maybe once a day, twice a day, maybe every other day, that would be occasional pain.
Sally says, “The mild pain in my legs seems to be chronic, but the severe pain in my back is occasional. Terrell says, “I guess you’re not up for going out tonight.” A couple of phrasal verbs there: “to be up for (something)” means to have the energy to do something, to be interested in doing something. “To go out” means to leave your house and have a good time: go a movie, go to a nice restaurant, have fun with someone outside your house.
Sally says, “After a day of being poked and prodded like a guinea pig, all I want is to curl up with a hot cup of tea and a good book!” “To be poked (poked) and prodded (prodded)” means that you are being touched many times, usually by a doctor or someone who’s examining you for some medical problem. It could be part of a test that they are doing; they could be taking your blood, they could be checking your temperature, lots of things that would require that you are touched many times. The idea of “poked and prodded” is that it is somewhat painful, although it isn’t always necessarily that way. It’s usually used in talking about medical exams that require a lot of tests and that require that you be at the doctor’s office or the hospital for a long time. A “guinea pig” is a small animal; it’s like a hamster. It’s used here, however, because guinea pigs traditionally have been used in medical experiments and biological experiments. It’s now a general term to talk about people who are being used to test something new, especially a new kind of medicine. It’s often used in a negative way, meaning that the person who is giving them this medicine or doing something to them is using them without really knowing whether that thing is going to work or not; it’s an experiment.
Sally says, “After a day of being poked and prodded like a guinea pig, all I want is to curl up with a hot cup of tea and a good book!” “To curl up with” here means to relax comfortably, sitting on a couch or a sofa perhaps with a book or a magazine and/or something to drink. “I want to curl up with a good book” is a common expression meaning I want to go home, sit in a comfortable chair, and read a good book.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Terrell: Where have you been?
Sally: At the hospital, again. My doctor is putting me through another battery of tests.
Terrell: She still hasn’t been able to zero in on the cause of your pain and make a diagnosis?
Sally: No, she hasn’t. Part of the problem is that my symptoms are intermittent, and they seem to flare up only when I’m not under observation. The symptoms themselves are ambiguous, so finding the root cause hasn’t been easy.
Terrell: I can see how that would be mystifying and frustrating. Are you still in a lot of pain?
Sally: The mild pain in my legs seems to be chronic, but the severe pain in my back is occasional.
Terrell: I guess you’re not up for going out tonight.
Sally: After a day of being poked and prodded like a guinea pig, all I want to do is to curl up with a hot cup of tea and a good book!
[end of dialogue]
There’s nothing mystifying about who the scriptwriter is. You know, Dr. Lucy Tse. Thank you, Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here at ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
battery – a series of things; a group of many similar things
* Applicants have to pass a battery of tests before they are admitted to this special school.
to zero in on – to identify one object or explanation among many, usually by eliminating or removing the other options
* What are the police doing to zero in on the criminal?
to make a diagnosis – for a doctor to identify someone’s illness or other medical problem
* Before making a diagnosis, I want to consult with some other doctors who are specialists in this area.
symptom – a physical problem that shows one has an illness or disease
* A high fever can be a symptom of a bacterial infection.
intermittent – coming and going; not constant; present at some times, but not present at other times
* As they were driving through the mountains, the cell phone signal was intermittent.
to flare up – for a disease to become worse, often with no warning
* Omid’s acne flares up whenever he uses sunscreen.
under observation – being seen, monitored, or tracked; being watched carefully
* We’re going to keep your son under observation overnight to see how he responds to the medication.
ambiguous – with more than one possible explanation; confusing and unclear; difficult to understand
* That was a horrible test! The questions were so ambiguous that we didn’t even know what the professor was really asking.
root cause – the main reason why something is happening
* What do you think is the root cause of the recent increase in crime?
mystifying – confusing, unclear, and strange; leaving one wondering about something
* Her ability to always know what I’m thinking is mystifying.
mild – not very strong or serious; not severe
* The weather report says today will be sunny with mild wind.
chronic – continuing for a long time, especially when talking about a disease that does not have a cure
* Nigel has had chronic asthma ever since he was a little boy.
severe – very strong and serious; not mild
* When Kenneth came to work with a severe sore throat, all his colleagues got sick, too.
occasional – happening only once in a while, not regularly, often, or frequent
* We get the occasional letter from friends, but normally the mailman just delivers bills.
poked and prodded – touched many times, in many ways, often as part of a test, experiment, or medical exam
* The artifact was poked and prodded by scientists who were trying to determine when it was made.
guinea pig – a small animal like a large hamster that is often used in biological or medical experiments, used to talk about people who are being used to test something
* Now that we’ve finished the first version of the software, we need to find some guinea pigs who will use it and tell us what they do and don’t like about it.
to curl up with – to relax comfortably, often on a couch or sofa, perhaps with a blanket, book, magazine, TV show, movie, and/or drink
* Terry loves curling up in front of the window with a warm blanket and a cup of hot chocolate to watch the snow as it falls outside.
Comprehension Questions
1. What is most painful for Sally?
a) Her intermittent symptoms.
b) Her chronic, mild leg pain.
c) Her occasional, severe back pain.
2. Why can’t the doctor find the root cause of Sally’s symptoms?
a) Because she hasn’t been able to observe the symptoms.
b) Because she isn’t a very good doctor.
c) Because she’s spending too much time with the guinea pigs.
Answers at bottom.
What Else Does It Mean?
battery
The word “battery,” in this podcast, means a series of things, or a group of many similar things: “Is it difficult to pass the battery of tests needed to become an FBI agent?” The word “battery” more commonly refers to a small object that generates electricity: “We should replace the batteries in our smoke detectors every year.” Or, “The flashlight doesn’t work because the batteries are dead.” The phrase “assault and battery” refers to the crime that occurs when someone hits another person: “When Chuck drank too much, he hit another customer at the bar and was arrested for assault and battery.” Finally, the phrase “to recharge (one’s) batteries” means to spend time relaxing after one has been working very hard, so that one has energy to continue working: “Once this case is finished, she’ll take a week off to recharge her batteries before accepting a new case.”
to flare up
In this podcast, the phrase “to flare up” means for a disease to become worse, often with no warning: “Jerry’s arthritis flares up in cold, wet weather.” The phrase “to flare up” also means for people to suddenly become angry or upset, or for a situation to become worse: “Tensions between the two countries flared up when a hospital was bombed accidentally.” The phrase can also mean for a fire to burn more brightly: “The campfire flared up in the wind.” When pants or skirts “flare out,” it means that they become much wider at the bottom: “I like the way this skirt flares out around the knees.” Finally, when someone’s “nostrils flare,” it means that the openings at the end of the nose become wider, usually because one is angry: “When Lawry is mad, his face turns red and his nostrils flare.”
Culture Note
When Americans “see” (have an appointment with) their doctor, the “medical assistant” (the person whose job is to help the doctor) usually takes several standard or normal “measurements” (attempts to see how big, small, fast, slow, hot, or cold something is), no matter what the patient is being seen for.
The first measurement is usually the patient’s weight. The medical assistant asks the patient to take off his or her shoes and “step onto” (begin to stand on) the “scale” (a piece of equipment that measures how heavy something is). The medical assistant “records” (writes down) the patient’s weight for the doctor to review.
Then, the medical assistant may take the patient into the “exam room” (a small, private room where the doctor examines the patient) and measures his or her “blood pressure” (how much pressure is placed against the veins as the heart beats). The medical assistant puts a “blood pressure cuff” (a piece of fabric that folds around the arm and is used to measure blood pressure) around the patient’s upper arm while touching the patient’s “wrist” (the part of the arm immediately above the hand) to feel the “pulse” (the rhythmic pushing of blood through veins). The medical assistant records the patient’s blood pressure and “pulse rate” (how many times the heart beats each minute). The medical assistant might also use a “thermometer” to “take the patient’s temperature” (find out how hot or cold someone is).
Then, the medical assistant leaves and the patient waits for the doctor to enter the exam room to begin his or her medical exam.
Comprehension Answers
1 - c
2 - a