= 0632
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 632: Negotiating a Business Deal.
This is English as a Second Language Podcast episode 632. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in – guess where? That’s right, beautiful Los Angeles, California.
Our website is eslpod.com. Consider becoming a member of ESL Podcast to support this effort. You can go to our website, and by becoming a member also download the Learning Guide for all of our current episodes.
This episode is called “Negotiating a Business Deal” (a business agreement). It’s a dialogue between Gia and Logan. Let’s get started.
[start of dialogue]
Gia: Why are the negotiations on this deal taking so long? I thought we would be putting the finishing touches on it by now.
Logan: The other side is holding out for more concessions. I don’t know what they’re thinking. They made some pretty big demands at the start and I think we’ve given in to most of them. Now they’re countering with even more demands.
Gia: They probably know that they have us over a barrel. After all of the time and money we’ve put into this deal, they know that we don’t want to walk away.
Logan: That’s true and that’s why we’re still at the table, but they may be pushing too hard. In the end, I don’t think we’ll cave on those additional concessions.
Gia: So the entire thing is touch-and-go right now?
Logan: That’s how I would characterize it. If I were you, I wouldn’t make any long-term plans.
Gia: Duly noted. I won’t run out and buy that new house and those three new cars.
[end of dialogue]
Gia begins by asking, “Why are the negotiations on this deal taking so long?” “Negotiation” is the process of trying to reach an agreement – trying to agree with another person or another business, when each side “compromises,” that is, each side gives in a little. For example I want to buy a new car and the person selling it says, “It’s 20,000 dollars,” and I say, “Oh, that’s too much. How about 18,000 dollars?” and the person selling – the seller – says, “Oh, no. I could only go as low as 19,000 dollars,” and you say, “I’ll give you 18,500 cash. I have the money with me,” and he says, “Okay, I’ll take it.” That’s a negotiation. Negotiations are always about time, power, and knowledge. That is, if you have a long time to wait or you need something done right away, if you have knowledge about what the other person wants, and finally if you have some other sort of influence or power over that person, all those things will affect your negotiation.
Gia wants to know why the negotiations on this deal (this agreement) are taking so long – are lasting such a long time. She says, “I thought we would be putting the finishing touches on it by now.” The expression “to put the finishing (or final) touches on (something)” means to be making small changes in order to finish something so that it’s perfect. The idea is that most of the important work has already been completed.
Logan says, “The other side (the people they are negotiating with) is holding out for more concessions.” “To hold out” is a two-word phrasal verb meaning to delay agreeing to something because you are waiting to receive something more; usually we say you “hold out for” something. For example, someone wants to offer you a job and they offer you 50,000 dollars a year, and you say, “Uh, I’m not too sure. Let me think about it,” and you wait, and you wait. You are holding out for more money. The boss may call you back and say, “Well, I’m sorry. I need to make a decision, it’s been a week,” and you say, “Just one more day,” and he says, “Okay. Just one more day.” As time goes on the boss becomes more and more desperate. He need to hire someone, and so you may get what you want because you have made him wait; you have used time to your advantage in the negotiation. The same is true when you go to buy, for example, a new car at a place that sells a lot of cars. The more time you can take with the salesperson, the more likely they will be to negotiate with you. Because they’ve spent all that time with you they don’t want to have you walk away, and they having wasted an hour for example on trying to sell you a car. Well, the other side is holding out for concessions. “Concessions” are things that you agree to do in order to reach an agreement. It’s like a compromise; you say, “Well, okay. I can’t give you more than 50,000 dollars (as the boss), but I can give you an extra week of vacation time.” That would be a concession.
Logan says, “I don’t know what they’re thinking (the other side). They made some pretty big demands at the start and I think we’ve given in to most of them.” “Some pretty big demands” means some very large demands, where “demand” is something that you say you must have – I cannot do this deal without it. Logan says their company has already given in to most of their demands. By the way, the word “demand” has a couple of different meanings; the other meanings you can find in our Learning Guide. “To give in” is a two-word phrasal verb meaning to agree to do what someone else wants you to do even though you don’t really want to do it. So the parent who has a child who says, “Mommy, Mommy, I want to go to the store! I want to go to the store! I want to! I want to! I want to! I want to!” Mommy can either say, “No, go to your room. I’m not letting you go to the store,” or she can give in; she can say, “Okay. You can go to the store.” Nowadays, most parents just give in, or so it seems – so it appears to me. You know, when I was young…oh, never mind!
Logan says the other side is countering with even more demands. “To counter” is when someone makes you a proposal: “I will sell you this car for 20,000 dollars,” and you say, “No. I…I only want to pay 18,000 dollars.” Your proposal is a counter proposal: he says 20,000; you say something different. That something different that the other person says is their counter proposal. The verb is “to counter,” to offer something else instead of the original proposal.
Gia says, “They probably know that they have us over a barrel.” The expression “to have (someone) over a barrel” (barrel) means to be in a situation where someone is very uncomfortable, or to be in a situation where you can beat the other person or take advantage of them knowing that you will win. For example, you live in an apartment and the person who owns the apartment raises your rent, but if you don’t have anywhere else to go or if you need to stay in that apartment he has you over a barrel; he has you in a situation where he can get what he wants because you don’t have the power to move. In this case, the other side has knowledge about the situation of Gia and Logan’s company, and they have power – they have them over a barrel.
Gia says, “After all of the time and money we’ve put into this deal, they know that we don’t want to walk away.” This is the idea I was talking about earlier. Gia and Logan’s company has spent a lot of time and money negotiating this agreement, so they don’t want to waste that time and money – they don’t want to walk away. “To walk away” is a two-word phrasal verb meaning to stop the negotiations, to end the discussion.
Logan says, “That’s true and that’s why we’re still at the table.” “To be at the table” means to be continuing to participate in the negotiations – to continue to talk to them. Logan says, “they may be pushing too hard (meaning they may be trying to do too much – trying to get too much). In the end, I don’t think we’ll cave on those additional concessions.” “To cave” (cave) as a verb means to agree to do what the other person wants you to do just so you can reach an agreement; “to give in” or “to give up” are also ways of saying same thing. Gia says, “So the entire thing (the entire negotiation) is touch-and-go right now?” “Touch-and-go” is something that could fall apart at any time; it’s something, we would say, that is very fragile. “To be fragile” means you could break it easily. Well, the negotiations are fragile – they’re touch-and-go.
Logan says, “That’s how I would characterize it (meaning that’s how I would describe it). If I were you, I wouldn’t make any long-term plans (plans into the future).” Gia says, “Duly noted.” That phrase, “duly (duly) noted,” is used to show that you have heard and understood what the other person has said and will think about it. We use this phrase especially if we need to make a decision about something. Gia says, “Duly noted. I won’t run out and buy that new house and those three new cars.” “I won’t run out” means I won’t go immediately and buy a new house and three new cars. She’s joking, of course. She’s saying that she will not spend a lot of money because they still don’t know how the negotiations are going to end up; that is, how they are going to come to a final result, what that result will be.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Gia: Why are the negotiations on this deal taking so long? I thought we would be putting the finishing touches on it by now.
Logan: The other side is holding out for more concessions. I don’t know what they’re thinking. They made some pretty big demands at the start and I think we’ve given in to most of them. Now they’re countering with even more demands.
Gia: They probably know that they have us over a barrel. After all of the time and money we’ve put into this deal, they know that we don’t want to walk away.
Logan: That’s true and that’s why we’re still at the table, but they may be pushing too hard. In the end, I don’t think we’ll cave on those additional concessions.
Gia: So the entire thing is touch-and-go right now?
Logan: That’s how I would characterize it. If I were you, I wouldn’t make any long-term plans.
Gia: Duly noted. I won’t run out and buy that new house and those three new cars.
[end of dialogue]
I would characterize our scriptwriter as amazing. That’s because it’s our own Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
negotiation – the process of trying to reach an agreement with another person or organization where each side is willing to give up a little bit of something to meet the other side’s needs
* They found a house they’d like to buy, but now they’re in negotiations over who will pay for the new roof.
deal – an agreement, especially involving a sale or exchange of goods or services
* Did you get a good deal on the new car?
to put the finishing touches on (something) – to make the last small adjustments or changes to finish something well, when most of the work has already been done
* They’ve almost finished remodeling their kitchen, and now they’re just putting the finishing touches on it by painting the walls and changing the handles on the cupboards.
to hold out – to delay agreeing to something because one is waiting until one receives something else
* We’re almost ready to accept their offer, but we’re still holding out for a little more money.
concession – something that one agrees to let another person have or do in order to reach an agreement or end an argument
* The company can be flexible with your vacation time, but we simply cannot make concessions on salary.
demand – something that one insists on having; something that one says one must have or do in order for something else to happen
* They’ll never agree to your demands for such a large expense account.
to give in – to agree to do something that another person wants, even though one doesn’t really want to; to let another person win
* If we’re persistent, at some point they’ll give in just because they’re tired of arguing with us.
to counter – to make a proposal in response to another person’s proposal
* Randy initially offered just $200 for our boat, but we countered with $300.
to have (someone) over a barrel – to be in a situation where someone is in a very difficult, uncomfortable, or impossible situation and one can take advantage of that, knowing that one will win
* The landlord raised the rent again and the apartment is too expensive for us now, but he has us over a barrel, because we don’t have anywhere else to go.
to walk away – to end discussions and stop negotiations because one is no longer interested in something, usually because the other side is asking for too much
* Don’t be too greedy! If you keep asking for more and more, they might just walk away and leave you with nothing.
at the table – in discussions; continuing to participate in negotiations
* They spent many hours at the table before they agreed on the terms of the merger.
to cave – to give in; to give up; to agree to the other side’s demands just to reach an agreement, usually because one is tired of arguing or negotiating
* The Jamisons were so desperate to find renters for their home that they caved and agreed to let the new tenants have pets in the home, even though they really don’t like the idea.
touch-and-go – fragile and hesitant; something that could fall apart or fail at any moment
* The business is touch-and-go right now, and if the economy doesn’t improve, it will probably have to close.
to characterize (something) – to describe something in a particular way
* How would you characterize the play? Is it a comedy or a tragedy?
duly noted – a phrase used to show that one has heard and understood what another person has said and will think about it, especially when one needs to make a decision
* Your complaints have been duly noted and we will share them with the store manager.
Comprehension Questions
1. What does Logan mean when he says, “we’re still at the table”?
a) We’re eating while talking.
b) We’re still discussing things.
c) We’re ready to sign the documents.
2. What does Gia mean when she says everything is “touch-and-go”?
a) They’re waiting for a final handshake.
b) The negotiations may or may not succeed.
c) The parties aren’t allowed to touch each other.
Answers at bottom.
What Else Does It Mean?
demand
The word “demand,” in this podcast, means something that one insists on having, or something that one says one must have or do in order for something else to happen: “Management will never agree to the workers’ demands for cheaper health insurance.” In economics, the word “demand” refers to how much of a good or service people want to have at a particular price: “For most products and services, demand increases as the price decreases.” The phrase “on demand” means whenever someone wants something, without having a set schedule: “Lynn often pays a few extra dollars to watch her favorite movies on demand, instead of waiting for them to appear on the TV schedule.” Finally, the phrase “due to popular demand” means happening because many people have asked for something: “The chef is putting apple pie back on the menu due to popular demand.”
to walk away
In this podcast, the phrase “to walk away” means to end discussions and stop negotiations because one is no longer interested in something, usually because the other side is asking for too much: “If they won’t lower the price, we can always walk away.” The phrase “to walk away from (something)” means to leave a bad situation without trying to fix it: “Once you’re married, you can’t just walk away from the relationship if you have problems.” The phrase “to walk (something) off” means to go on a long walk when one isn’t feeling well so that one will feel better: “Una had a headache, but she decided to walk it off and not take medicine.” Finally, the phrase “to walk out” means to leave because someone doesn’t like something: “The actors were horrified to see their audience members walking out during the play.”
Culture Note
Before “investing” (putting money or other resources into something, hoping to make more money or see results) money in anything, it is important to “conduct” (do) “due diligence,” learning as much as one can about something and making sure it is “legitimate” (real) and “legal” (following the laws). This is true for business “transactions” (buying and selling) and “philanthropy” (giving money to nonprofit organizations).
In a business transaction, due diligence is usually related to a company’s “financial situation” (how much money a company has, how it is managed, and how profitable it is), as well as legal and tax “considerations” (concerns; worries). Conducting due diligence requires reading the company’s annual reports and “financial statements” (documents with financial information) and “verifying” (making sure something is true) that information by conducting an “audit” (the process of testing many transactions or accounting entries to make sure things are done correctly). Due diligence might also involve making sure the company has all the “requisite” (required; necessary) “licenses” and “permits” (official permission to do something) and checking with the city and state to see if any complaints have been “filed” (submitted) against the company.
In philanthropy, “prospective” (possible; considering doing something) “donors” (people who give money to organizations) conduct due diligence “much as they would” (similarly; in a similar way) for a business transaction. They learn as much as they can about the organization and review its annual reports and financial statements. They review the organization’s tax filings and study how the organization spends its money. Donors also want to understand the organization’s “impact” (effects; results) on the “beneficiaries” (people who benefit from something) so that they know their money will be used to do good things.
Comprehension Answers
1 - b
2 - c