= 0638
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 638: Fire and Firefighters.
This is English as a Second Language Podcast episode 638. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You can go there and download a Learning Guide for this episode. The Learning Guide contains all of the vocabulary, definitions, sample sentences, additional definitions, culture notes, comprehension questions, and – yes there’s more – and a complete transcript of everything we say on this episode.
This episode is about fire and the people who try to put fires out – to extinguish fires, as we’ll learn. Those are firefighters. Let’s get started.
[start of dialogue]
Rebecca: Look, there’s smoke coming from six stories up.
Hugh: Yes, I know. Didn’t you hear the fire alarm go off upstairs a few minutes ago?
Rebecca: No, but I’m really glad there’s a fire station only a few blocks away. Hey look, there’s the fire engine. Here come the firefighters!
Hugh: Yeah, let’s get back to work. I’m sure they’ll have the blaze under control pretty quickly.
Rebecca: How can you work with all of this excitement? Maybe I should get the fire extinguisher from the hallway and go upstairs to help.
Hugh: I think that’s a really bad idea. You can see for yourself that the firefighters are getting ready to fight the fire. They’re getting the ladder out and attaching the fire hose to the hydrant. Anyway, it’s probably just a false alarm.
Rebecca: If the smoke detector went off then I’m sure there’s a fire. We’ll know if we start to see something burning near a window or ashes coming down.
Hugh: I’ve never seen you like this before. Why are you so excited?
Rebecca: I wanted to be a firefighter when I grew up. I’ve always had a fascination with fire.
Hugh: Ah, that explains it. Would it make you feel better if I lit up a cigarette?
[end of dialogue]
Rebecca begins by saying to Hugh, “Look, there’s smoke coming from six stories up.” “Smoke” is the gray or black air that comes from something that is burning; it’s something that comes from a fire typically. “Where there’s smoke, there’s fire” is an old expression that means if you see some evidence of something it’s very likely that that something actually exists. Typically, it refers to something bad that might be happening. Well here, the smoke is coming from the fire in a real way – literally. The fire is in a building, and the building has six stories. A “story” here means a floor or a level of a building. “Story” has other meanings, of course, in English, and those can be found in this episode’s Learning Guide.
Hugh says, “Yes, I know. Didn’t you hear the fire alarm go off upstairs a few minutes ago?” A “fire alarm” is a loud sound, sometimes with flashing lights, that is used to tell people – to let people know that there is a fire in the building and they should leave. When I was growing up, and still I’m sure, in schools there are “fire drills.” These are practice exercises of what to do, where to go if there is a fire. And so, the school would turn on the fire alarm, and that would tell teachers and students that they needed to get up and leave the building. This fire alarm is in a building, and Hugh says it goes off. He said, “Didn’t you hear the fire alarm go off?” “To go off” is a two-word phrasal verb, here meaning for an alarm to begin making noise. A fire alarm is just one kind of alarm. Many of us have an alarm that helps us wake up in the morning: a sound that comes from your clock or clock radio. That’s also an alarm. My alarm goes off at 5:45 in the morning. This is a fire alarm, and so the fire alarm went off. Notice the past tense. “To go off” can also be used with the preposition “on,” meaning to start yelling at or to get mad at: “I don’t want you going off on your brother.” I don’t want you getting mad at your brother. Or, “He went off on his wife for forgetting to buy his favorite food for dinner.” He, of course, is someone who will not be sleeping in his regular bed this evening!
Rebecca says, “No (she didn’t hear the fire alarm go off), but I’m really glad there’s a fire station only a few blocks away.” A “fire station” is a large building where firefighters stay, and where there are large machines – large trucks really, that are called “fire engines.” And these fire engines go and try to put out – to extinguish, to get rid of – fires. Rebecca says, “Hey look, there’s the fire engine.” As I said, it’s also called a “fire truck,” usually it’s red in color. She says, “Here come the firefighters!” “Firefighters” are people whose job it is to put out fires. We used to call them simply “firemen,” but some people wanted a term that did not have the word “man” in it – we won’t talk about that issue here – so now they’re called more commonly “firefighters.”
The firefighters are coming. Hugh says, “Yeah, let’s get back to work (meaning let’s return to our jobs). I’m sure they’ll have the blaze under control pretty quickly.” A “blaze” (blaze) is a large fire, especially a big and dangerous one. Hugh says that the firefighters will have the blaze “under control,” meaning they will be able to manage it, they will be able to make sure that it doesn’t get any bigger. They’ll have it under control pretty, or very, quickly.
Rebecca says, “How can you work with all of this excitement? Maybe I should get the fire extinguisher from the hallway and go upstairs to help.” A “fire extinguisher” is a metal, typically round container that you hold in your hands, and you press a button and it sprays out a chemical that helps put out a fire – a small fire, like in your kitchen for example. “Extinguisher” comes from the verb “to extinguish,” which means to get rid of or put out a fire. A fire extinguisher, of course, won’t really help in this situation; you need something larger.
Hugh says, “I think that’s a really bad idea. You can see for yourself that the firefighters are getting ready to fight the fire.” We use that verb, “to fight,” when we are talking about putting out a fire. “They’re getting the ladder out and attaching the fire hose to the hydrant.” A “ladder” (ladder) allows you to climb up high, for example to the top of a building. A ladder has two long pieces of metal or wood that are vertical – they go up and down, and then they are connected by smaller horizontal pieces of wood or metal, and those are the ones you use to step on to go up to a higher level. Fire engines have ladders that can allow the firefighters to go up high to help fight the fires.
They are getting the ladder out, meaning they are getting it ready, and attaching, or connecting, the fire hose to be hydrant. A “hydrant” (hydrant) is something that you will find near the road – near a street. It is usually painted red, sometimes orange, maybe yellow. It is connected to the water pipes underneath the street, and firefighters can open the hydrant and water will come out and they use that water to put out the fire. They use a “fire hose,” which is a long, flexible usually plastic tube that carries the water from the hydrant to the place of the fire.
Hugh says, “Anyway, it’s probably just a false alarm.” A “false alarm” is when people think there’s a fire, but there really isn’t. It can also be used to talk about a situation where people think there’s a big problem, but there really isn’t: “I thought my friend was having a heart attack, but he wasn’t. It was a false alarm.”
Rebecca says, “If the smoke detector went off then I’m sure there’s a fire.” The “smoke detector” is a small device that you find in buildings and homes that makes a very loud noise when there is smoke in the air, letting people know that there may be a fire. Remember, where there’s smoke, there’s fire! Well, this smoke detector “detects,” or figures out whether there is smoke in the air, and makes a loud sound. Rebecca says, “If the smoke detector went off (remember, we talked about “to go off” earlier) then I’m sure there’s a fire. We’ll know if we start to see something burning near a window or ashes coming down.” “Burning” comes from the verb “to burn,” which is when something is damaged or destroyed by fire. “Ashes” (ashes) are gray or black pieces of powder that are left after something burns, especially wood or paper, you get lots of ashes.
Hugh says, “I’ve never seen you like this before.” I guess Hugh was very excited, ‘cause his voice went up there! “Why are you so excited?” Rebecca says, “I wanted to be a firefighter when I grew up.” Okay. “I’ve always had a fascination with fire.” “To have a fascination with (something)” means that you are very interested in something; you spend a lot of time thinking about something.
Hugh says, “Ah, that explains it.” Traditionally, we think about boys thinking about becoming firemen when they grow up. That’s kind a classic, at least in the United States, dream that some young boys have, but Rebecca said she wanted to be a firefighter when she was growing up. Hugh says, “Ah, that explains it (that tells me the reason why you are excited).” Then he tries to make a joke; he says, “Would it make you feel better if I lit up a cigarette?” “Lit up” comes from “to light up” (“light” is the present tense). You can also say “lighted up,” both are correct: “lit” or “lighted.” “To light up a cigarette” means to burn a small fire at the end of a cigarette so that you can smoke it. Now, the interesting thing here is that Hugh wants to go back to work even though there is a fire in the same building where he is working at, six floors up. I guess Hugh really love his job!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Rebecca: Look, there’s smoke coming from six stories up.
Hugh: Yes, I know. Didn’t you hear the fire alarm go off upstairs a few minutes ago?
Rebecca: No, but I’m really glad there’s a fire station only a few blocks away. Hey look, there’s the fire engine. Here come the firefighters!
Hugh: Yeah, let’s get back to work. I’m sure they’ll have the blaze under control pretty quickly.
Rebecca: How can you work with all of this excitement? Maybe I should get the fire extinguisher from the hallway and go upstairs to help.
Hugh: I think that’s a really bad idea. You can see for yourself that the firefighters are getting ready to fight the fire. They’re getting the ladder out and attaching the fire hose to the hydrant. Anyway, it’s probably just a false alarm.
Rebecca: If the smoke detector went off then I’m sure there’s a fire. We’ll know if we start to see something burning near a window or ashes coming down.
Hugh: I’ve never seen you like this before. Why are you so excited?
Rebecca: I wanted to be a firefighter when I grew up. I’ve always had a fascination with fire.
Hugh: Ah, that explains it. Would it make you feel better if I lit up a cigarette?
[end of dialogue]
If you have a fascination with English, you should definitely listen to the scripts that are written by our own Dr. Lucy Tse, like this episode’s.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2010 by the Center for Educational Development.
Glossary
smoke – the smelly gray or black air that appears when something is burning; the dark gas that comes from a fire
* It was really rude when Boyce blew smoke in his father’s face.
story – a floor or level in a building
* This skyscraper is more than 50 stories tall.
fire alarm – a loud sound and/or bright flashing light used to let people know that there is a fire in the building and they should leave
* When the school tests its fire alarm, students leave their classroom with their teacher while the administrators see how long it takes to get everyone out of the building.
to go off – for an alarm to begin making noise
* Bernice’s alarm clock goes off at 5:45 a.m. each morning so that she can get ready for work.
fire station – a large building that houses people and equipment for putting out fires
* The nearest fire station is more than one hour’s drive away, so if there’s a fire here, we’ll probably have to put it out ourselves.
fire engine – fire truck; a large red or yellow truck that carries hoses, ladders, and other equipment for putting out fires
* If you see a fire engine with its lights on, you should pull over and let it drive by quickly.
firefighter – a person whose job is to put out fires
* Firefighters come from all over the state to fight the large forest fires each summer.
blaze – a large flame; a fire, especially a big and dangerous one
* The investigators think the blaze started with an electrical problem.
fire extinguisher – a metal container that is held in one’s hands and sprays out chemicals to put out a fire
* It’s a good idea to keep a fire extinguisher in the kitchen, just in case there’s a fire.
ladder – a piece of equipment that allows a person to climb high, with two long pieces of metal or wood and many shorter pieces of metal or wood between them, leaned against a wall to be almost like a staircase
* They used a ladder to reach that kitten that got stuck high up in the tree.
fire hose – a long, flexible fabric or plastic tube that carries water from one place to another, used to put out fires
* That fire hose is so heavy that at least three strong firemen are needed to carry it.
hydrant – a large piece of metal, usually painted red, orange, or yellow, placed on the side of the street and connected to water pipes under the street, so that firefighters can connect a fire hose to it and have water to put out a fire
* It’s illegal to park in front of a fire hydrant, because you car might make it impossible for firefighters to get the water they need to put out a fire.
false alarm – a situation where people believe there is a problem, but actually everything is fine
* We thought Anita was having a heart attack, but the doctors said it was a false alarm and she was just experiencing stomach problems.
smoke detector – a device that makes a loud sound when smoke is in the air, letting people know there is a fire somewhere
* The smoke detector in the kitchen goes off almost every time Kirby cooks, because he burns everything!
to burn – to be consumed by fire; to be damaged or destroyed by fire; to be in flames
* Tyler and his wife cried as they watched their house burn.
ashes – the grey or black powder that is left after something has burned
* If you light a fire in the fireplace, be sure to clean up all the ashes.
to have a fascination with (something) – to be very interested in something; to spend a lot of time thinking about something
* Bud has always had a fascination with outer space, so it was easy for him to decide to study astronomy in college.
to light up – to put a small fire at the end of a cigar or cigarette so that one can smoke it
* Please don’t light up around the baby. The smoke isn’t good for her.
Comprehension Questions
1. Which of these would you expect to smell when there is a fire?
a) Smoke.
b) Blaze.
c) Ashes.
2. Which of these things moves water to a fire?
a) A fire engine.
b) A ladder.
c) A fire hose.
Answers at bottom.
What Else Does It Mean?
story
The word “story,” in this podcast, means a floor or level in a building: “His office is on the top story of the office building, so he enjoys great views of the city.” A “story” is also an entertaining description of something that happens, either fictional (invented; not true) or true: “This book is based on the true story of the author’s life.” Or, “Her parents always tell her a bedtime story before she falls asleep.” A “news story” is one report, or one section of a TV news program or one article in a newspaper: “Did you watch the news story about the earthquake?” Finally, the phrase “It’s a long story” is used when one does not want to share all the details that would be needed to answer someone’s question: A: “Why did you and Gerald break up?” B: “It’s a long story.”
blaze
In this podcast, the word “blaze” means a large flame or fire, especially a big and dangerous one: “We thought it was just a small kitchen fire and we didn’t realize how big the blaze was until we got out of the house and saw that most of the roof was on fire.” The word “blaze” can also describe a very bright color or a very bright light: “Each fall, the forests are a beautiful blaze of red, orange, and yellow leaves.” The phrase “blaze of glory” refers to something that is very successful and admirable: “Her career was a blaze of glory, before she died at the young age of 35.” Finally, the phrase “What the blazes” is used when one is very annoyed or upset and wants to know what has happened: “What the blazes did you do to make her cry?”
Culture Note
“Hazardous materials” (HAZMAT) are any substances that can harm people and the environment. They can be “chemical” (made from dangerous chemicals), “biological” (dangerous bacteria or viruses), “corrosive” (very acidic, damaging skin and surfaces), highly “flammable” (burning easily), or even “radioactive” (sending out dangerous radiation). HAZMAT requires special “handling” (the way something is transported and treated) by trained HAZMAT teams.
There are legal “restrictions” (limitations) on who can create, transport, sell, and buy hazardous materials, but “nevertheless” (even thought that is true) accidents happen. In the United States, when there is a HAZMAT “spill” (when something accidentally falls out of its container), a HAZMAT team is “called to the scene” (asked to come to the place where something has happened). Most U.S. fire departments have at least one HAZMAT team.
The HAZMAT team members arrive in special “HAZMAT suits” (protective clothing and other coverings to prevent contact with the hazardous materials), often covered “from head to toe” (over one’s entire body) in brightly colored plastic. The HAZMAT team first focuses on “containing the spill” (not letting the spill continue or spread). Then, they try to clean up the spill, removing the hazardous materials and “disposing of them” (throwing them away) properly. If the spill “presents” (has; shows) a “threat” (risk of danger or death) to human health, the media is “alerted” (told about the problem) and people in the local area may be asked to “evacuate” (leave an area).
The person or business responsible for the HAZMAT spill is often responsible for paying for the clean-up efforts.
Comprehension Answers
1 - a
2 - c