= 0650
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 650: Buying TV Programs and Movies.
This is English as a Second Language Podcast episode 650. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode that will help you improve your English faster – and, make you a happier human being!
This episode is a dialogue between Cameron and James. It’s all about buying TV programs and movies to watch at home. Let’s get started.
[start of dialogue]
Cameron: What did you get for Christmas?
James: I got a box set of my favorite TV show of all time, the McQ Files. It contains all five seasons of the show, deleted scenes, and outtakes. I can’t wait to watch it all!
Cameron: Didn’t you see the entire series when it was shown on TV?
James: I did, but the bonus features make it a must-have for a big fan like me.
Cameron: I just don’t see why people spend good money buying shows they’ve already seen.
James: Hey, wait a second. Didn’t you run out and buy the Podinator trilogy box set when it went on sale last month?
Cameron: Uh, yeah, but that’s different. Those are movies, not TV shows. The Podinator box set had the director’s cut and commentary, not to mention never-before-released scenes.
James: Hadn’t you seen all three movies when they were shown in the theaters?
Cameron: Yes, but…
James: And don’t you own all three movies on video already?
Cameron: Well, maybe I do but…
James: Then I don’t see why you needed to buy the box set. I think it’s best that you give it to me.
Cameron: Touché.
[end of dialogue]
Cameron begins by asking James, “What did you get for Christmas?” What gifts; what presents did you get for Christmas? James says, “I got a box set of my favorite TV show of all time, the McQ Files.” A “box set” is a group of related CDs (compact discs), DVDs, videotapes, books, or some other material, usually a video or a print material that is sold together. For example, you might want to see all three of the Godfather movies from the early 70s: The Godfather, The Godfather II, The Godfather III. Well, you can buy a box set of those three movies. They come together in DVD form in a little box that often contains other information about whatever it is that you’re buying.
James got a box set of his favorite TV show of all time. The expression “of all time” means the same as ever, throughout the existence of something. If you say, “This is the best book of all time,” you mean there has never been a better book than this one. James says that the box set contains all five seasons of the show, deleted scenes, and outtakes. The verb “to contain” means to have, to include as part of something. “My book contains a lot of violence.” It has a lot of violence in it. “Contain” has a couple of different meanings, and those can be found in our Learning Guide.
James says that the box set contains all five seasons of the show – of the TV program. A “season,” when we are talking about a television program, is the group of programs that are shown usually in a period of six to eight months. In the United States, typically most of the new TV shows begin in September. And then, during this summer, they don’t have the show on the air. That is, you can’t watch it on television or you can only watch old episodes, and then they start a new season in the fall, in September the following year.
Well, this show, the McQ Files, has five seasons. The box set also contains deleted scenes and outtakes. When you buy a DVD, for example, of a TV program or a movie often they will include on the DVD things that were not part of the original movie or the original television show. Something that is “deleted” is something that is removed. So, “deleted scenes” are parts of the story that were taken out for the final version, for what you saw on TV. But when you buy the box set you get to see some of these scenes – some of these parts of the TV show or movie that no one else has seen. Well, no one else who has not bought the box set! An “outtake” (outtake – one word) is a small section of a movie that is usually removed because there was a problem with it, often there’s a mistake. In many box set DVDs you’ll find outtakes from a movie that are funny, when the actors or actresses make a mistake. That’s typically what outtakes are.
James says that he can’t wait to watch it all – watch all of the programs in this TV series. Cameron says, “Didn’t you see the entire series when it was shown on TV?” That is, when you could watch it on the regular television. James said, “I did, but the bonus features make it a must-have for a big fan like me.” Something that is a “bonus” (bonus) is something that is extra. A “feature” in this case is just a characteristic of something, some part of something. So, a “bonus feature” are things that you get extra when you buy the DVD box set. A “must-have” is something that you want and feel that you absolutely need to have. James says that getting the box set with the bonus features is a must-have for a “big fan” – that is, someone who likes this TV series a lot – like me.
Cameron says, “I just don’t see why people spend good money buying shows they’ve already seen.” The expression “to spend good money” is an informal one that’s used to show your disapproval, how you don’t like the way someone is choosing to spend their money. You think it’s on unimportant or unnecessary things. Some people might say, “You shouldn’t spend good money on buying a fancy car. All you need is something that will take you from here to there.” That would be an example of using this expression “to spend good money.” I, for example, will not spend good money on some expensive shampoo, since I don’t really need it!
Cameron doesn’t think James should spend good money on buying television shows – DVDs of shows he’s already seen. James says, “Hey, wait a second. Didn’t you run out and buy the Podinator trilogy box set when it went on sale last month?” “Wait a second” means hold on; stop; don’t go any farther. James asks Cameron, “Didn’t you run out and buy,” meaning you were very excited and so you went to the store immediately, as soon as it was available to buy it. “Didn’t you run out and buy the Podinator trilogy box set?” A “trilogy” (trilogy) is a group of three related books or movies typically. The Lord of the Rings was a trilogy; The Godfather series was a trilogy, and so forth
Cameron says, “Uh, yeah, but that’s different. Those are movies, not TV shows. The Podinator box set had the director’s cut and commentary, not to mention never-before-released scenes.” When you buy a movie on DVD sometimes they will include a special version of the movie called the “director’s cut.” The “director” is the person who is in charge of the movie when it is being filmed. Often, the director takes things out of the movie in order to be able to sell it to the movie companies – the movie studios. When they have a chance to sell the DVD, then the director will often put in that original cut – that is, that original version of the movie. Often, movies will have “commentary.” That is, there’ll be the director, maybe the producer, possibly the lead actor talking through the movie, giving you descriptions of what was happening or giving you the story behind this particular part of the movie. And, when you buy a DVD with commentary you can turn the commentary on so that you can hear them talking literally over the movie. “Never-before-released” means that it has not been shown to anyone until now. It’s sort of like deleted scenes. “Release” has a couple of different meanings however; take a look at the Learning Guide for some additional explanations.
James says, “Hadn’t you seen all three movies when they were shown in the theaters (in the movie theater)?” Cameron says, “Yes, but…” “And don’t you own all three movies on video already?” That is, Cameron already has copies of this movie, perhaps on an old videocassette tape. Cameron says, “Well, maybe I do but…” James continues, “Then I don’t see why you needed to buy the box set. I think it’s best that you give it to me.” He’s joking, of course. James is saying you should give me the box set because you already own these three movies. Cameron, of course, realizes that James is criticizing her for the same reason that she criticized him. So the last word of the dialogue is “Touché.” “Touché” (touché – with an accent over it) is a French word that in English we use to show that you agree with what another person has said, and that there’s something somewhat funny about it. We’re acknowledging that the other person said something that was true and that perhaps we didn’t realize until they said it. For example, someone could say to you, “If you are trying to save money, why don’t you stop buying so many expensive books (books that cost a lot of money) about saving money?” And, you would say, “Ah, touché.” In other words, you are accepting, in a sense, this criticism – this observation about something that is somewhat funny, something that perhaps shows that you didn’t think about the situation as completely as you should have.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Cameron: What did you get for Christmas?
James: I got a box set of my favorite TV show of all time, the McQ Files. It contains all five seasons of the show, deleted scenes, and outtakes. I can’t wait to watch it all!
Cameron: Didn’t you see the entire series when it was shown on TV?
James: I did, but the bonus features make it a must-have for a big fan like me.
Cameron: I just don’t see why people spend good money buying shows they’ve already seen.
James: Hey, wait a second. Didn’t you run out and buy the Podinator trilogy box set when it went on sale last month?
Cameron: Uh, yeah, but that’s different. Those are movies, not TV shows. The Podinator box set had the director’s cut and commentary, not to mention never-before-released scenes.
James: Hadn’t you seen all three movies when they were shown in the theaters?
Cameron: Yes, but…
James: And don’t you own all three movies on video already?
Cameron: Well, maybe I do but…
James: Then I don’t see why you needed to buy the box set. I think it’s best that you give it to me.
Cameron: Touché.
[end of dialogue]
Who is the greatest podcast scriptwriter of all time? I think you know the answer: Dr. Lucy Tse! Thank you. Lucy.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
box set – a group of related books, CDs, DVDs, video tapes, or similar materials that are sold together, often with special packaging, although they can also be bought separately
* For her birthday, Margot asked for a box set of albums by her favorite rock group.
of all time – ever; throughout the existence of something
* That was the best song of all time! I can’t imagine anyone ever recording something better.
to contain – to have; to include as a part of something; to encompass
* That diary contains all of his most personal thoughts and secrets.
season – the episodes of a particular television show that are shown during a particular time of year, most often in the fall
* How many seasons of The Simpsons have been produced?
deleted scene – a recording of some action or conversation that was meant to be part of a movie or show, but was taken out of the final version and not seen by viewers, usually because the producer decided it isn’t an important part of the story
* Watching the deleted scenes can provide a lot of insight into the characters’ motivations.
outtake – a small section of a movie or show that is removed from the final version, often because it has a mistake in it
* There’s a really funny outtake where the actors couldn’t stop laughing as they were trying to say their lines.
bonus feature – something that is included in a DVD, but not included in the movie as it was shown in theaters, and that makes the DVD more desirable or more valuable
* This DVD has an interactive video game as a bonus feature.
must-have – something one wants to have very badly and feels as if he or she needs to have it
* Bright red-colored nail polish is the must-have item this season in the fashion industry.
to spend good money – an informal phrase used to show disapproval for how other people are choosing to spend their money on unimportant or unnecessary things
* Why would anyone spend good money on fancy jewelry?
to run out and buy – to be very excited to buy something, going to the store without thinking about it ahead of time, often as soon as it becomes available
* As soon as I saw that commercial, I wanted to run out and buy a new camera.
trilogy – a group of three related things, usually three movies or three books with the same characters
* Marcos thinks The Lord of the Rings is one of the best trilogies ever.
director’s cut – the version of a movie approved by a director, but different from the one shown in theaters, which must be approved by the film studio
* The director’s cut was almost 20 minutes longer than the version of the film that was shown in theaters.
commentary – spoken comments, usually from the director, producer, or lead actor, that are heard throughout a movie as he or she comments on what the viewer is seeing and hearing
* It’s interesting to listen to the main actor’s commentary about what he was thinking while acting in certain scenes.
never-before-released – being shared with the public for the first time
* This album contains never-before-released songs that the singer recorded before her death.
touché – used to show that one agrees with what another person has said in a discussion or argument and that it is very true in a slightly funny way
* - If you’re trying to save money, why don’t you stop buying so many expensive books about living on a budget?
* - Ah, touché.
Comprehension Questions
1. Which of these things could be a bonus feature?
a) A box set.
b) A season.
c) An outtake.
2. What does Cameron mean when he says, “I just don’t see why people spend good money buying shows they’ve already seen”?
a) He thinks the shows are too expensive.
b) He thinks people forget what they have seen too easily.
Answers at bottom.
What Else Does It Mean?
contain
The verb “to contain,” in this podcast, means to have or to include as a part of something: “This box contains all the photographs I have of my mother.” Or, “So many kids are allergic to peanuts that the school has started asking parents not to send any snacks to school that contain nuts.” The verb “to contain” can also mean to control one’s feelings: “Therese couldn’t contain her happiness, so she just laughed and smiled.” Or, “Some people try to count to 10 in order to contain their anger.” When talking about a disease or a problem, “to contain” means to control or limit the spread of something: “The agency didn’t work quickly enough to contain the problem, so now it has spread throughout the country.”
released
In this podcast, the phrase “never-before-released” means being shared with the public for the first time: “In these never-before-released journal entries, you can read Maxim’s most secret thoughts.” A “release” can also be a new song, album, movie, show, or book that has just been made available to the public: “Have you heard the singer’s newest release?” A “press release” is a short document that describes an important event or decision for a business or organization, and that is sent to the media for publication: “They write a new press release every time the company starts selling a new product.” The phrase “work release” refers to a program that lets prisoners work outside of the jail: “If your good behavior continues, you might be eligible for our work release program.”
Culture Note
Box sets are an easy way for product manufacturers to increase sales of their products. Americans purchase box sets not only of DVDs, but also of many other types of products.
For example, many books are sold in box sets. These are normally “series” (a group of books or shows with the same characters), such as a Harry Potter box set or a Nancy Drew box set. Popular trilogies such as The Lord of the Rings can also be purchased as box sets. Sometimes these box sets include special features, such as a DVD of a related movie or TV show, or stickers or jewelry related to the main character.
Other box sets might include all the “works” (things someone has created) of a particular author or musician. For example, there is a box set of four CDs featuring the music of Elton John. These box sets are often released “shortly” (soon) after an individual’s death or any other event that makes the individual “rise to prominence” (become famous; become talked about), such as a decision to give a special award to that individual.
Even some foods are sold as box sets, and are often given as “impersonal” (not close or intimate) gifts. For example, a box set of tea might include a few “teabags” (small filter-paper bags filled with tea leaves, placed in a mug so hot water can be poured over them to make one serving) for each “variety” (type) of tea sold by the manufacturer. “Spice” (plant products used to flavor food) manufacturers also sell box sets so that people can “sample” (try) many of the spices the company sells.
Comprehension Answers
1 - c
2 - c