
= AP Euro Unit 1 - AP Euro Unit 1 REVIEW (Everything You NEED to Know)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

All right, if you need a review of the whole dang 完全的；十足的 first unit of AP Euro, then you are in the right place. So if you're ready to get them brain cows milked （一种形象说法，可理解为充分激发脑力）, let's get to it 开始吧. +

Now, the first thing we need to talk about is the Renaissance 文艺复兴. And it's a word that means rebirth 重生, and that means that something which has died has come back to life. So what died and what was being resurrected 复活？Well, it was the classical texts 经典文本 and ideas from the Romans and the Greeks. +

Now, throughout the Middle Ages 在整个中世纪 -- which is to say before the Renaissance -- much of this teaching was forgotten by Europeans, at least those who didn't sit around a monk 僧侣 all day. But thanks to Islamic scholars 伊斯兰学者 who had translated the works of ancient Greece and Rome into Arabic 阿拉伯语 and Latin 拉丁语, and thanks to the increasing contact 接触 Europeans had with Islamic people during the Crusades 十字军东征, Europeans started gaining access 获得机会；得以接触 again to these ancient ideas. And the recovery 恢复 of these texts and ideas essentially 本质上；基本上 led to the Renaissance, which began in Italy, by the way 顺便说一句. +

If you want note guides 笔记指南 for this video, you can check out my AP European History Ultimate Review Packet 终极复习资料包, which is linked in the description 描述中链接. +

Now, the first major player 重要人物 in this regard 就这方面而言 was a guy named Petrarch 彼特拉克. Although technically 严格意义上 he preceded 先于 the Renaissance, it doesn't matter. Petrarch laid out 阐述；规划 a lot of the groundwork 基础工作 for Renaissance ideas, and his philosophy 哲学 was called humanism 人文主义. And this is important -- like, so important. Write it down, tattoo 刺青 it on your forehead if you need to. Humanism was a philosophy that focused on the unlimited potential 无限潜力 of human beings as an end in themselves 目的本身. +

In Petrarch's analysis 分析, human beings were the bee's knees （非正式用语）出类拔萃的人, as nobody says. There was unlimited potential in these fleshy little organisms 生物体. And so humanism, along with individualism 个人主义 -- which emphasizes 强调 the triumph 胜利 of the individual -- would become the main mode of thought 思维模式 for much of the Renaissance. +

Now, one of Petrarch's great discoveries was the writings of the Roman orator 演说家 Cicero 西塞罗, whose magnificent 宏伟的；出色的 Latin compositions 作品 Petrarch thought ought to be the model 典范 for the Latin language. In other words, Cicero's Latin. Noice （非正式用语）很棒. Anyway, Petrarch was especially moved by Cicero's eloquent 雄辩的 support of the Roman Republic 罗马共和国 -- not the empire 帝国, the republic. That's important. And Petrarch was further moved by Cicero's opposition 反对 to the tyrannical 专制的；暴虐的 Julius Caesar's usurpation of power 篡权. Those are themes 主题 that will become very important throughout the Renaissance. +

Now, also during the Renaissance, we saw the development of new philological 文献学的 approaches to texts. Philological? Now, philology 文献学 is the study of the history and development of languages. And maybe that sounds about as interesting to you as painting a wall two shades of gray 两种灰色色调 and watching it to see which dries first. But in the Renaissance, new philological methods 方法 were kind of a big deal 重要的事. +

Case in point 例证: Lorenzo Valla 洛伦佐·瓦拉 made philological headlines 成为文献学领域的头条新闻 in 1440 when he demonstrated 证明 that an authoritative document 权威文件 of the Roman Catholic Church 罗马天主教会 was a forgery 伪造品. No? Oh yes. It was supposedly 据说 written by the Roman Emperor Constantine 罗马皇帝君士坦丁 in the 4th century, but Valla demonstrated that the structure of the Latin in Constantine's document did not conform to 符合 4th-century Latin standards 标准. Therefore, not authoritative 权威的. Throw it out 扔掉. +

And that's a good illustration 例证 of a major theme 主题 of the Renaissance, namely 即 the move away from religious authority 宗教权威 to secular authority 世俗权威. To be fair 公平地说, many Renaissance thinkers 思想家 were still Christians, but the movement in general was away from the revealed authority of the Bible 圣经的启示权威 and the dogmas 教条 of the church to more scientific modes of inquiry 探究方式. +

And another important shift 转变 in thought was from the communal understandings 集体理解 of humanity 人类 to individualistic conceptions 个人主义观念 of humanity. All these new ideas were largely confined to 局限于 a handful of 少数 elite folks 精英人士 in the beginning. But in the 1440s, with the invention of the movable-type printing press 活字印刷术, the ideas spread widely and with great speed 迅速地 -- so much so that these ideas started challenging the institutional power 机构权力 of universities and other centers of power 权力中心. +

Now, more on the printing press 印刷术 later, but for now, let's see how this worked out 产生效果；发展 in education. +

Now, scholars 学者 in the Middle Ages were primarily concerned about 主要关注 theological questions 神学问题. But with the growing interest in classical texts and the establishment of humanistic reasoning 人文主义推理 during the Renaissance, education underwent a massive transformation 经历巨大变革. And Renaissance scholars introduced the humanities 人文学科 into the curriculum 课程, which emphasized 强调 history, moral philosophy 道德哲学, poetry 诗歌, etc. -- all of it based on classical texts 经典文本. +

And as humanists, this emphasis on the humanities was intended to expand the humanity 人性 and unlimited potential of the human being. Because, you know, humanism. +

Now, one of the key thinkers 关键思想家 in this regard was Baldassare Castiglione 巴尔达萨雷·卡斯蒂廖内, whose book *The Courtier*《廷臣论》 was a guide for how an educated young man should behave in courtly society 宫廷社会 -- namely, to be a gentleman 绅士. He argued 主张 that a gentleman should be skilled in all the humanistic disciplines 学科, like write and speak with eloquence 雄辩地写作和说话, be physically strong 身体强壮, and most of all, mentally awake 思维敏捷. +

Now, these new ideas also affected civic and political institutions 公民和政治机构, beginning with the Italian city-states 意大利城邦. Now, remember, during this time, Italy wasn't a unified country 统一的国家 like we know of today. Rather 相反, it was a bunch of regional kingdoms 地区王国 and self-governing communities 自治社区. +

When these humanistic ideas worked their way into 逐渐进入 politics and civics 公民事务, the result was called civic humanism 公民人文主义, which was basically the idea that educated men should be active and engaged in 积极参与 local politics 地方政治. And I reckon 认为 we ought to talk about a couple of examples. +

First, Leonardo Bruni 莱昂纳多·布鲁尼. He argued that the republicanism 共和主义 of ancient Rome was the best form of government 政府形式 and that rule by an enlightened individual 开明的个人统治 was best. Now, this was a massive shift 巨大转变 from the feudalistic government structure 封建政府结构 of the Middle Ages. +

Second, you got our boy Niccolò Machiavelli 尼可罗·马基雅维利. He wrote a little book called *The Prince*《君主论》, in which he argued that the basic function 基本职能 of a ruler 统治者 is to maintain power 维持权力 at all costs 不惜一切代价. Thus 因此, a prince 君主 ought to behave in whatever way helps him to fulfill those ends 实现那些目的. If benevolence 仁慈 helps him reach those ends, then be benevolent. If being a tyrannical turret 专制统治者 helps you reach those ends, then be a tyrannical turret. +

However, Machiavelli argued that there is a limit to the Turkish tyranny 专制. The prince must strike an enlightened balance 达成明智的平衡. You must use whatever means necessary 必要手段 to establish order and security 建立秩序和安全, but do not act in such ways to make your people hate you. Or, to put it in Machiavelli's own words 用马基雅维利自己的话来说: "It is much safer for the prince to be feared than loved, but he ought to avoid making himself hated." +

But at the end of the day 归根结底, Machiavelli argued that a ruler should maintain power, even if it meant making selfish decisions 自私的决定 that disregard 无视 ethical and moral beliefs 伦理和道德信仰. And that was a huge departure from 与…大相径庭 the Middle Ages, when the character 品格 of a European ruler was defined by biblical virtues 圣经中的美德 like prudence 谨慎 and wisdom 智慧. +

Okay, now let's turn the corner 换个话题. We can't talk about the Renaissance without talking about the new birth of art 艺术的新生 as well. If you already know anything about the Renaissance, it's probably the art. +

Now, artists in the Middle Ages portrayed 描绘 almost exclusively 几乎完全地 religious themes 宗教主题, rich with symbolism 充满象征意义, but they were flat 平面的 and didn't really conform to reality 符合现实. Renaissance artists, on the other hand 另一方面, emphasized naturalism 自然主义, which was more realistic 现实的, portraying the world as it was and not in the mysteries of symbolic figures 象征人物的神秘之中. +

Now, Italian Renaissance artists leaned more on 更倾向于 the idealistic side 理想主义方面 of naturalism, while Northern Renaissance artists -- on whom more in a moment 稍后详述 -- employed naturalism to depict 描绘 the scenes of everyday life 日常生活场景. There were also masters of new techniques in geometric perspective 几何透视法, by which artists sought to add depth and realism 增加深度和真实感 to their paintings. +

Now, Renaissance artists did continue to portray religious themes in their work, but they also took up 开始关注 personal and political and classical themes 个人、政治和古典主题 as well. You're going to need to know a couple of these artists, so let's meet them. +

First is Michelangelo 米开朗基罗. Here you can see a sculpture 雕塑 of the biblical figure 圣经人物 David 大卫. And notice the humanist philosophy coming through 体现出来. This is the perfect specimen 完美典范 of a human man, but sculpted in the image of a Greek god 以希腊神的形象雕刻. So additionally 此外, notice the detail of David's musculature 肌肉结构 and the features of his face 面部特征. This is the naturalism and the idealism 理想主义 of Renaissance art. +

Second, let's meet Raphael 拉斐尔. Here you can see one of his most famous paintings, *The School of Athens*《雅典学院》. It's an example of a Renaissance artist taking up classical themes, which were at the heart of the Renaissance. In the middle, you've got the classical heroes Plato 柏拉图 and Aristotle 亚里士多德. And also notice the way he uses geometric perspective to make his structure feel real 使画面结构显得真实. +

And third, let's look at some architecture 建筑. And for that, let me introduce you to Filippo Brunelleschi 菲利波·布鲁内莱斯基. He was the architect 建筑师 on the rebuilding of the church of San Lorenzo in Florence 佛罗伦萨的圣洛伦佐教堂重建工程. Notice how he tossed out 摒弃 the Gothic conventions 哥特式传统 of medieval cathedrals 中世纪大教堂 and built the church with Roman columns 罗马柱 and arches 拱门. +

His most famous work was the dome 圆顶 on the Florence Cathedral 佛罗伦萨大教堂. Now, it may not look like much to you, but this was a genius feat of engineering 工程学上的天才之作, since the flying buttresses 飞扶壁 of medieval cathedrals were so Middle Ages. Brunelleschi built this dome to stand on its own 独立支撑 without any outside support 外部支撑. +

Now, the last thing you should know about Renaissance art is this: Most of these artists were patronized by 受…赞助 wealthy individuals 富人和 rulers 统治者 and popes 教皇. Was that because those folks just loved the arts and wanted to see beautiful works of human genius born into the world? Uh, no. These leaders patronized the arts in order to enhance their public prestige 提升公众威望. "Hey, you like that new Michelangelo? I paid for that." +

And the most notable 著名的 of these patrons 赞助人 was the Medici family 美第奇家族 -- on whom more later. +

Okay, so as I said, the Renaissance started in Italy, but it soon spread to other parts of Europe as well. With the help of the printing press, the ideas of the Italian Renaissance spread to the rest of Europe north of the Italian Alps 阿尔卑斯山. And when it took root 扎根, we call that the Northern Renaissance 北方文艺复兴. +

However, as the ideas spread northward 向北传播, the main foundation 基础 of humanism and the revival of the classics 古典文化复兴 stayed the same, but some of the emphases 重点；强调的方面 changed. And the main change was that it developed a more religious -- which is to say, Christian -- focus than the more secular 世俗的 Italian Renaissance. +

So as the Renaissance spread to the Low Countries 低地国家 and France and Germany and England, people took pains to 努力 synthesize 融合 humanism with Christian ideas. And the result was Christian humanism 基督教人文主义. What they aimed to do was combine the best elements of humanist thought 人文主义思想精华 with scriptural authority 圣经权威. And that led to a heavy emphasis on 高度重视 social reform 社会改革. +

And the name I want you to associate with Christian humanism is Desiderius Erasmus 德西德里乌斯·伊拉斯谟. Now, Erasmus believed that education in the classics and the Bible is the foundation of true societal reform 社会改革 and that renewal 复兴 should be based on the philosophy of Christ 基督的教义. +

The work you should know from Erasmus is called *In Praise of Folly*《愚人颂》. It was a satire 讽刺作品 that sought to undermine 削弱 corrupt political and social institutions 腐败的政治和社会机构 and criticize the corrupt aspects of religious hierarchies 宗教等级制度的腐败方面 as well. +

Now, the Italian Renaissance had their artists, and so did the Northern Renaissance. However, Northern Renaissance artists retained a more religious, Christian focus than the more secular Italian Renaissance artists did. Their art was still naturalistic 自然主义的, but it was more human-centered 以人为本 and considered everyday objects and people more appropriate for objects of art 艺术表现对象, as opposed to 与…相反 Italian artists, whose lofty subjects 崇高的主题 were sometimes otherworldly 超现实的. +

For example, let's talk about Pieter Bruegel the Elder 老彼得·勃鲁盖尔 of the Dutch and Flemish Renaissance 荷兰和佛兰德斯文艺复兴. Here's his painting titled *The Peasant Wedding*《农民的婚礼》. You know, the subject matter 题材 here isn't something massive like the six days of creation 创世六日, but instead, you see ordinary people 普通人 in celebration of a wedding 庆祝婚礼, eating normal food 吃普通食物. But still, you can see the emphasis on naturalism. The features of the people look real 人物特征看起来很真实. +

Okay, and then there's Rembrandt 伦勃朗 of the Dutch Renaissance. And oh, his work is tasty 出色的. He was famous for his ability to paint light and shade 光影, as you can see here in his work titled *The Return of the Prodigal Son*《浪子回头》. It's a scene from a parable of Jesus 耶稣的寓言故事, and you can almost sense the deep emotion 深厚情感 in the painting. For Rembrandt, it was very important to him not merely to reproduce a picture 复制画面 but to inhabit the narrative of scripture 融入圣经故事 as he did so. +

Okay, so that was the Northern Renaissance. +

Now, I've mentioned already the role that printing had in the spread of Renaissance and humanist ideas, but now we need to consider that head-on 正面探讨. The printing press was a massive deal 大事. Like, I cannot emphasize enough 再怎么强调也不为过. It is impossible to overemphasize the role that printing played in this period of history. +

Now, before the printing press, important books were copied by hand 手工抄写. And if you've ever been on Spaceship Earth at Epcot （一种主题公园设施）, you know this. This process was laborious 费力的 and very expensive. And that meant that there weren't many books available 可得的, and what books were available were either kept by churches 教堂 or in the libraries of the wealthy who could afford to have their own copies 拥有自己的副本. +

Not to mention 更不用说, most of the books were written in Latin, which meant that only priests 牧师 and monks could read them. Anyway, but all that changed in the 1440s when several German metalsmiths 金属工匠 developed the technology of the printing press, which allowed printed works to be copied and published at a speed and volume 速度和数量 previously unthinkable 难以想象的. +

And the smith most associated with this technology was Johannes Gutenberg 约翰内斯·古登堡. The printing press was able to produce books quickly and cheaply because of a new innovation 创新 called movable type 活字印刷, in which metal letters 金属字母 were slid into rows 排成行, blotted with ink 蘸墨, and pressed upon a piece of paper 压在纸上. +

Thanks to Chinese paper-making technology 造纸技术 that had spread into Europe, the abundance of paper 纸张充足 made mass printing 大规模印刷 a feasible reality 可行的现实. Now, Gutenberg's first major work published on the press was the Gutenberg Bible 古登堡圣经 in 1456. And then, within 50 years, a metric buttload of 大量 books were published all throughout Europe -- somewhere between 10 and 20 million books.

So with this new technology, ideas written in books and pamphlets 小册子 could spread rapidly 迅速地. And that is exactly what happened. By 1515, all the major classical authors -- like Plato 柏拉图 and Aristotle 亚里士多德 and Pliny 普林尼, etc. -- were all in print 已出版 and spreading rapidly. +

The printing press 印刷机 also played a massive role 重要作用 in the Protestant Reformation 新教改革. Martin Luther 马丁·路德, who claimed 声称 that the Catholic Church 天主教会 had devolved into 退化为 heresies 异端邪说 and corrupt practice 腐败行为, was able to spread his ideas far and wide 广泛传播 thanks to movable type 活字印刷 and deal a serious blow to 给予沉重打击 the church hierarchy 教会等级制度. +

But we're going to talk a lot more about the Protestant Reformation in the next unit, so we'll leave it there for now. +

And the press also created demand for vernacular literature 白话文学, which is literature written not in Latin 拉丁语 but in the language of the common people 普通人的语言 -- whether it be English or Spanish or French. And when books were printed in a people's native language 母语 and they began reading them together, it created the occasion for 为…创造条件 the development of national cultures 民族文化 to emerge 出现. +

For example, during the Protestant Reformation, Martin Luther produced a vernacular Bible 白话圣经 in German, which is kind of a big deal 重要的事 because prior to this 在这之前, people only heard the Bible in Latin. But in doing so, Luther created a standard 标准 for the German language, which fundamentally 从根本上 shaped 塑造 their national culture. +

Okay, I reckon 认为 we ought to talk about some politics. This period saw some pretty significant developments 重大发展 in how kings exercised 行使 and consolidated 巩固 their power. +

Now, back in the Middle Ages, kings didn't have as much power as you might think. You know how when you watch a movie set in medieval times 在中世纪, and the king is all-powerful 全能的 and like telling everybody what to do? Yeah, that's not how it actually was. It was the nobles 贵族 that held much of the power. +

But during this period, monarchs 君主 and princes 王子 started taking power from the nobility 贵族阶级 and organizing it squarely under themselves. And one of the results of that shift 转变 was top-down 自上而下的 religious and moral reform 宗教和道德改革. +

So in light of that 鉴于此, I reckon I ought to introduce you to Henry VIII of England 英格兰的亨利八世. He actually opposed 反对 the new religious developments of the Protestant Reformation against the Catholic Church. In fact, he pooh-poohed 对…不屑一顾 the Reformation so hard that the pope 教皇 named Henry "Defender of the Faith 信仰捍卫者". +

But then Henry started having a little trouble with the Catholics 天主教徒. His wife of 20 years failed to produce a male heir 男性继承人, and so he did what any self-respecting 有自尊心的, self-sacrificial 自我牺牲的 Christian man would do: he asked the pope for an annulment 婚姻无效判决. Classy guy 好家伙. +

But it just so happened that 碰巧 she was the daughter of Ferdinand and Isabella of Catholic Spain 西班牙天主教的费迪南德和伊莎贝拉, and they put the pressure on 施加压力 the pope to deny Henry the annulment. And they were successful. But then Henry's mistress 情妇, Anne Boleyn 安妮·博林, became pregnant 怀孕, and so Henry went ahead and divorced 离婚 his wife and married Anne. +

The pope, unsurprisingly 不出所料地, declared 宣布 the marriage illegal 非法的, so Henry denounced 谴责 the pope, and the Parliament 议会 passed a law making Henry the head of the newly formed Church of England 英格兰教会, which was patently 明显地 not under the authority of Rome 罗马的权威. +

Now, many English people remained committed Catholics 虔诚的天主教徒, but remember, we're talking about top-down religious reform here. To that end 为此, Henry got the Treason Act 叛国法案 passed, which made it punishable by death 判处死刑 to refuse to recognize the Church of England as the state religion 国教. +

Okay, now let me tell you about a descendant 后代 of Henry, namely Elizabeth the First 伊丽莎白一世. She rose to the throne 登上王位 after Henry's daughter, Mary Tudor's reign 统治. Now, Mary attempted to restore Catholicism 恢复天主教 to England and earned the nickname "Bloody Mary 血腥玛丽" for hacking to death 砍死 any Anglican bishop 英国圣公会主教 that opposed her. +

Anyway, Elizabeth steered 带领 England back to Anglicanism 英国国教 and ended the persecution 迫害 of the dissenters 持不同政见者. And again, she did this from the top down. She had the Act of Uniformity 统一法案 passed, which mandated 强制规定 that English subjects 英国臣民 had to attend an Anglican church -- and that's just another name for the Church of England -- and they had to do that once a week or be fined 罚款. +

Okay, so that's how a couple of these new monarchs engaged in 参与 top-down religious and moral reform. +

Now, let's look at how a few other of these new monarchs laid the foundation for 为…奠定基础 the modern state 现代国家 by doing a few things, namely 即: establishing monopolies on tax collection 建立税收垄断, employing military force 动用军事力量 and dispensing justice 司法, and gaining the right to determine the religion of their subjects 臣民. +

Let's start in Spain with Ferdinand and Isabella. Ferdinand was from the Spanish region of Aragon 阿拉贡, which was powerful and well-organized. Isabella was from the region of Castile 卡斯蒂利亚, which was kind of a hot mess 一团糟. Their marriage began the process of the unification of Spain 西班牙统一 and the consolidation of monarchical power 君主权力的巩固. +

So what did they do with all that power? Well, they raised revenue 筹集收入 through a series of national taxes 国家税收 on the sale and exchange of property 财产的买卖和交换. They established an elaborate bureaucracy 复杂的官僚机构 that collected taxes and decided questions of justice 司法问题 in the name of the monarchs 以君主的名义. +

And they went ahead and completed what was called the Reconquista 收复失地运动, by which they drove out 驱逐 Muslims 穆斯林 and Jews 犹太人 from the Iberian Peninsula 伊比利亚半岛 and established Catholicism as the official religion 官方宗教 of Spain. +

Alright, let's see how this played out 发展；产生结果 over in France. Their monarchs used similar methods of consolidating power, namely national taxes and a complex bureaucracy. Now, France was also a Catholic country, and to that end, you should know the Concordat of Bologna 博洛尼亚协约 in 1516. +

This is an agreement between King Francis the First 弗朗西斯一世 and Pope Leo the Tenth 利奥十世, by which two things happened: the pope got the right to collect income 收取收入 from the French Catholic Church, and Francis retained the right to appoint 任命 French Catholic Church leaders, thus restricting 限制 their right to communicate with the pope directly. +

What does all that mean? More power for the king. +

Now, these new monarchs also began to claim the right to determine the religion of their subjects. The Peace of Augsburg 奥格斯堡和约 in 1555 gave individual leaders in the Holy Roman Empire 神圣罗马帝国 the right to decide whether their subjects would be Catholic or Lutheran 路德宗的. +

And this wasn't, of course, just a religious decision on the part of the Habsburg rulers 哈布斯堡统治者. The power to choose the religion of their subjects was also a means of consolidating power. After all 毕竟, if a monarch's people -- or even just a minority of them -- believed contrary doctrines 相反的教义 to their monarch, that could weaken their sway over 对…的影响力 the people. +

Now, I would be a liar if I told you that it was only monarchs who were gaining power during this period. Commercial and professional groups 商业和专业团体 gained power as well and played a greater role in political affairs 政治事务. Chief among these groups were merchants 商人 and bankers 银行家, especially in the Italian and German states. +

And I know your heart is crying out for 渴望 a couple of examples here, so far be it for me to deny your deep desires 满足你的愿望. The Medici family 美第奇家族 basically established the banking industry 银行业 in Italy, and the Fugger family 富格尔家族 basically did the same in Augsburg 奥格斯堡, Germany. +

And the result of these folks building a tremendous amount of boom-boom in their vaults 金库 was this: with the rise of the money economy 货币经济 and a close alliance 紧密联盟 of these groups with the monarch, it allowed them to exercise increased political power 行使更多政治权力 in their respective areas of influence 各自的影响范围. +

Now, another major theme 主题 of this time period is European exploration 欧洲探险. Europeans were no longer content to 满足于 remain on their entire continent 整个大陆, so some of them started shoving out into ships 乘船出发 to find other places to live and trade. +

Now, first, we probably ought to talk about why Europeans went out exploring, and for that, I've got three words for you: gold, God, and glory 荣耀. And let's look at each of those in turn 依次. +

Now, Europeans were first motivated 受到驱使 to start their maritime exploration 海上探险 because of God. We've already established that during this period, Europeans could be pretty spicy about 热衷于 the religion of their people, so why not crank up the spice 加大力度 and go find other people to convert 皈依？+

Case in point 例证: Spain. They, of course, wanted to spread Catholicism 传播天主教 as far as they could. As I already mentioned, by 1492, they had completed the Reconquista and driven Jews and Muslims from their land. And by the time of the Protestant Reformation, there was a desire to see Catholicism in the ascended position 占据优势 over Protestantism 新教. +

As they found their way to the New World 新大陆, they sent Jesuit missionaries 耶稣会传教士 to convert the indigenous people 原住民. However, many Europeans thought of the indigenous people as lesser humans 低等人类 and thus suitable for forced labor 强迫劳动. In that way, Christianity 基督教 became an instrument for control and subjugation 控制和征服的工具. +

However, I must hasten to add 赶紧补充 that not all Spaniards saw indigenous Americans that way. For example, the Spanish priest Bartolomé de las Casas 巴托洛梅·德拉斯·卡萨斯 worked to establish a Catholic presence 天主教势力 in the Americas and also fought for the dignity 尊严 of the peoples in the Americas. +

Okay, now the second motivation for exploration was gold. And for this, I need to introduce you to mercantilism 重商主义, which was the dominant economic system 主导经济体系 of Europe during this period. +

The main thing you need to understand about mercantilism is that it's a system that argued that there was only a finite amount of wealth 有限的财富 in the world and that wealth could be measured in gold and silver 金银. And you know, if that's how you measure wealth, then yeah, there's only a finite amount of gold and silver in the world. +

And so a mercantilist nation 重商主义国家 wanted to get as much gold and silver as they could, which is to say, the country with the most gold wins. To that end 为此, mercantilism demanded what was called a favorable balance of trade 贸易顺差, which essentially means that a country needed more exports than imports 出口大于进口. +

When you think about it, that's easy to understand why. If a country is exporting goods 出口商品, that means gold and silver is coming in. And if they are importing goods from other countries 从其他国家进口商品, that means their gold and silver are going out. Remember, the state with the most gold wins, so that's why they wanted less imports and more exports. +

On a related note 相关地, under the mercantilist mindset 思维模式, the establishment of colonies 建立殖民地 was almost a necessity 必要之事 because those far-off lands 遥远的土地 could provide the motherland 母国 not only with more mineral wealth 矿产财富 like gold and silver but with raw materials 原材料 to be used in manufacturing goods for sale 制造商品出售, which would then bring in more gold. +

You smelling what I'm stepping in here? +

Okay, let me give you an example of how mercantilism motivated exploration and the policies 政策 of France's Controller General 总督查, Jean-Baptiste Colbert 让 - 巴蒂斯特·科尔贝. Colbert believed, like any good mercantilist, that a country's wealth should serve the state 为国家服务. +

In order to create a favorable balance of trade, Colbert proposed policies mandating 要求 French industry to create everything the people needed so that they didn't have to import goods. Furthermore 此外, Colbert aimed to claim 占领 as much of North America as possible, and the major accomplishments 主要成就 on that front were Quebec 魁北克 and the Louisiana Territory 路易斯安那地区 in North America. +

Now, one more thing under this heading: Europeans were motivated to explore because of the increasing demand for luxury goods 奢侈品 from Asia. But they had a problem: the Muslim Ottoman Empire 奥斯曼帝国 controlled all the land routes 陆路通道 between Europe and Asia, and therefore, Europeans had to pay even more exorbitant prices 过高的价格 for those goods. +

So what do we do? Well, why don't we put some ships in the shark's house and see what happens? +

Okay, now the third motivation for exploration was glory. Once the colony game 殖民竞赛 was started, it created a bitter rivalry 激烈竞争 among European powers 欧洲列强 to grab as many colonial possessions 殖民地 as possible. Like, if colonial possession is going to be the path to dominance 统治地位, then each regional power 地区势力 sought to win such a game. +

Okay, so those were the major motivations for exploration. Now, let's take a moment to consider the new and repurposed 重新利用的 navigational technology 航海技术 that enabled 使能够 them to go exploring. +

First, there were advances in cartography 制图学, which is to say, map-making 地图制作. These maps were more detailed 详细的, and printing made them widely accessible 广泛可得 across the continent 大陆. +

Second, we saw new kinds of ships. For example, we saw the Spanish and Portuguese developed the caravel 卡拉维尔帆船, which was fast and highly navigable 适航性强. And one of the chief reasons it was fast was because of the lateen sail 三角帆, which could take wind from any side 从任何方向迎风, as opposed to 与…相反 square sails 横帆, which could only take wind from behind 从后面迎风. +

They also made use of the compass 指南针, which helped establish direction 确定方向, and the astrolabe 星盘, which gave an accurate reckoning of latitude 精确计算纬度 from Chinese and Muslim navigators 中国和穆斯林航海家. +

You probably like, "Lateen sail? Astrolabe? Who cares?" But trust me when I tell you, these were massive innovations 重大创新. Like, if Steve Jobs lived 500 years ago, he would come out on stage in a mock turtleneck 高领毛衣 saying, "This is the most triangular sail 三角帆 we have ever made." Then everyone would give a standing ovation 起立鼓掌 and lose their minds. "Look how triangular it is!" +

So these technologies? Big deal 重要的事. +

Now, as I mentioned, this new wave of exploration caused a pretty significant rivalry to erupt 爆发 among European nations 国家. So let's talk first about colonial empires 殖民帝国 themselves and second, how those empires affected relationships between those powers. +

And since they were first on the exploration scene 探险舞台, let's start with Portugal 葡萄牙. They were the first Europeans to actively seek 积极寻找 a sea route to Asia, and they did this by sailing around Africa 绕非洲航行. +

As they made their way around the African coast 非洲海岸, the Portuguese didn't take large colonial holdings 殖民地, which were costly to establish and maintain 建立和维持成本高昂, but instead established trading posts 贸易站 all around the coast, which is why their empire is known as a trading post empire 贸易站帝国. +

Eventually 最终, they made their way all the way into the Indian Ocean 印度洋, where, over time, they dominated trade 主导贸易 all the way to Southeast Asia 东南亚. +

Next, we have Spain 西班牙, whose monarchs Ferdinand and Isabella commissioned 委托 an Italian sailor named Christopher Columbus 克里斯托弗·哥伦布 to find a sea route to Asia as well. But instead of sailing around Africa, Columbus decided to sail west across the Atlantic Ocean 大西洋 to connect them with the Asian spice trade 亚洲香料贸易. +

And as you probably know, there were a couple of giant continents 大陆 that got in his way that no one in Europe knew about. So Columbus landed in the Bahamas 巴哈马群岛 and eventually claimed 宣称拥有 much of the Caribbean 加勒比地区 and Central America 中美洲, North America 北美洲, and the coastline of South America 南美洲海岸线 for Spain. +

And look, as men were able to gain so much territory 领土 largely because of the deadly diseases 致命疾病 like smallpox 天花 and measles 麻疹 that they brought with them -- on which more in a moment. +

And then France 法国 jumped into the exploration party. They ended up claiming large parts of North America and Canada 加拿大. Mainly, they were interested in trading 贸易, especially in fur 毛皮. Therefore, they didn't establish many proper colonial settlements 殖民地. +

And let's not forget about England 英格兰. They sailed west and claimed parts of Canada, the Caribbean, and the eastern coast of North America. And the English built settler colonies 移民殖民地, which is to say, people went there to make a new life 开始新生活, to build homes 建造家园, and not just trade. +

The Netherlands forced their way into the party as well. The Dutch were mainly interested in trade, and to that end, established a few colonies in the Americas but focused mainly on dominating trade in Southeast Asia.  +

Now, how did this scramble for colonies 争夺殖民地 affect the relationships between these European powers 欧洲列强? Well, it got nasty 变得恶劣. And when the tension 紧张局势 arose, there were basically two ways that they could settle it.  +

First was diplomacy and negotiation 外交与谈判. For example, Spain and Portugal entered an agreement called the Treaty of Tordesillas 托德西利亚斯条约 in 1494. It was mediated by 由…调解 Pope Alexander VI 教皇亚历山大六世, and both parties agreed to divide the Americas by this line of demarcation 分界线: Spain got everything to the left, Portugal everything to the right. Hey, that's nice.  +

But the second way the nations handled rivalry 处理竞争 was a little more saucy 激烈, namely coercion 胁迫 and war 战争. Since the Treaty of Tordesillas essentially divided the world in half in terms of colonial territories 殖民领地, that would lead to some armed conflict 武装冲突 later.  +

Since all of North America fell squarely in the Spanish half of the world, that is going to lead to rivalry 竞争 in the next period between Spain and England, who wanted to claim some of those tasty colonies 诱人的殖民地.  +

Eventually, in the next period, France, Spain, and England -- along with some other states -- are going to fight the War of Spanish Succession 西班牙王位继承战争 over colonial possessions 殖民地 in the New World. But we'll save that story for when we get there.  +

What you really need to remember about these growing tensions and rivalries 紧张局势和竞争 is this: at stake 处于危险之中 for all the European nations was the balance of power 权力平衡. Nobody wanted any one European power to have all the cake -- or even most of the cake. As long as everyone was equally powerful, roughly speaking 大致来说, all was well.  +

Okay, now with all this contact between the Old World -- which is to say, Europe -- and the New World -- the Americas -- something massively important happened, namely the Columbian Exchange 哥伦布大交换.  +

By definition 从定义上讲, the Columbian Exchange was the global exchange 全球交换 of goods 商品, flora 植物, fauna 动物, cultural practices 文化习俗, and disease 疾病 between the Old World and the New World. So as Europeans established colonies and trading ports 贸易港口 in the Americas and Africa, the great exchange occurred. And when it did, it transformed 改变 the society, economy, and environment on all three continents 大陆.  +

So let's talk about five major exchanges that occurred.  +

First, disease 疾病. The Spanish got real thirsty for colonial holdings 殖民地 in the Americas, and when they got their hands on these lands and peoples, they sought to remake 重塑 the Americas into their own image 按照自己的样子. But their ships only held a few hundred sailors at best 最多, so how did they conquer 征服 so many people? Mainly by disease -- and more specifically, smallpox 天花.  +

You have to understand that Africans, Europeans, and Asians had all been in contact with one another for millennia 千年 and therefore had been exposed to 接触 each other's nasty germs 有害病菌 and had therefore built up some immunity 免疫力.  +

The indigenous peoples 原住民 of the Americas, though, had been completely isolated from 与…完全隔离 such germs and therefore had no immunity. So, for example, when the Spanish landed on the island of Hispaniola 伊斯帕尼奥拉岛, both the Arawak 阿拉瓦克人和 the Taino 泰诺人 populations were devastated 摧毁 to the tune of about 300,000 dead by smallpox.  +

Spanish conquistador 征服者 Hernán Cortés 埃尔南·科尔特斯 defeated the massive Aztec empire 阿兹特克帝国 with relatively few men -- again, because of the introduction of smallpox and measles 麻疹. So, Hernán, chill your fluffy collar out 冷静点. You're not that great.  +

Second, food was exchanged 交换. You should probably know a couple examples. Food that travels from the Americas to Europe included high-yielding 高产的 and nutrient-packed 营养丰富的 foods like maize 玉米, tomatoes 西红柿, potatoes 土豆, and cacao 可可豆.  +

Food that traveled from Europe and Africa to the Americas included rice 大米, wheat 小麦, soybeans 大豆, rye 黑麦, oats 燕麦, lemons 柠檬, oranges 橙子. And it was especially those grain crops 谷物作物 that transformed the American population because they diversified 使多样化 their diet 饮食 and led, in many cases, to longer lifespans 寿命.  +

Third, animals were transferred 转移 too. Europeans introduced horses 马, pigs 猪, chickens 鸡, and cattle 牛 to the Americas. Pigs and cattle transformed the diet of Native Americans 美洲原住民. Horses revolutionized 彻底改变 farming and warfare 农业和战争. And chickens made it possible for our nation to later indulge in 尽情享受 giant buckets of KFC.  +

Oh man, I got the chicken sweats 想吃炸鸡了. Thanks, Columbian Exchange.  +

Fourth, minerals 矿物 were exchanged. And here, I'm really talking about gold and silver 金银. After the Incan 印加 and Aztec empires were conquered 征服, Europeans plundered 掠夺 their lands for vast quantities of 大量 gold and silver. And that made Spain wealthy beyond belief 难以置信地富有.  +

If it weren't for this wealth, it's likely that European colonizers 殖民者 would not have kept returning. But as the old conquistador saying goes, "As long as there's boom-boom 财富, we go vroom-vroom 出发". That's a rough translation 粗略翻译.  +

Anyway, not only did this wealth transform the Americas by attracting large amounts of European colonizers, but it transformed Europe as well. Starting a little after 1500, Europe -- and more to the point 更确切地说, Western Europe -- experienced unprecedented economic growth 前所未有的经济增长.  +

The social, political, and economic system 社会、政治和经济制度 previous to this period was feudalism 封建主义, and that was a system where peasants 农民 lived and worked on the land of a noble 贵族 in exchange for 以换取 armed protection 武装保护. But this influx of wealth 财富涌入 hastened the end of that system 加速了该制度的终结.  +

And what replaced it? Well, an early form of capitalism 资本主义, which was an economic system based on 基于 private ownership 私有制 and free, open exchange of goods 商品自由交换 between property owners 所有者.  +

And the fifth kind of transfer 转移 during the Columbian Exchange was people. The chief thing to know here is the African slave trade 非洲奴隶贸易, by which millions of Africans were forcibly removed 强行带走 from their land and shipped across the Atlantic 大西洋 in order to work the plantations 种植园 of European colonies 殖民地.  +

We'll talk about that more in a moment, so just take that, stick it in your pocket, and we will come back.  +

For now, let's finish this section by talking about how the Columbian Exchange impacted 影响 Europe.  +

First of all, the influx of mineral wealth 矿产财富涌入 and the establishment of trading empires 贸易帝国的建立 shifted the center of economic power 经济权力中心 in Europe from the Mediterranean 地中海 to the Atlantic states 大西洋沿岸国家 and brought them squarely into the global economy 全球经济.  +

Previously, Mediterranean seaports 海港 like Venice 威尼斯 were the center of economic power and trade, but not anymore. During the globalization of the economy and exploration, one of the primary trading ports 主要贸易港口 became Antwerp 安特卫普 in the Netherlands, which grew exceedingly prosperous 极其繁荣 due to its central location 中心位置 to Spanish, Portuguese, French, and English trading routes 贸易路线.  +

Over time, Amsterdam 阿姆斯特丹 grew to ascendancy 优势地位 as the major trading port of Europe, replacing Antwerp. Then others followed, like London 伦敦 and Bristol 布里斯托尔. But the point is, whereas economic power used to be concentrated here during the Age of Exploration 探索时代, it was now concentrated here.  +

The second impact concerns the subjugation of people 对人民的征服. The Spanish created a completely new societal structure 社会结构 in the Americas. Before Columbus left for the last time, he introduced the encomienda system 委托监护制 in the Caribbean 加勒比地区, which spread throughout the Spanish settlements 定居点 in the Americas.  +

It was a system in which leading men -- called encomenderos 监护主 -- were granted a portion of land 土地. All the natives 当地人 who lived on that land became the unpaid laborers 无偿劳动者 who did the farming or the mining 采矿. It was a brutal system 残酷的制度 that was justified on religious grounds 以宗教理由为借口.  +

Remember, one of the motivations for Spanish exploration was the spread of Christianity. So how did this work out? Well, Ferdinand and Isabella issued 发布 a legal document 法律文件 called the Requerimiento 要求书, which established the basis for 为…奠定基础 the encomienda system.  +

And in it, the pope granted the Spanish monarchs authority to claim lands 宣称拥有土地 and proselytize 传教. Therefore, priests had the protection of the crown 王室保护. If natives submitted to 服从 this system, they were granted protection. Also, if not, they forfeited 丧失 the protection of the crown and could be subjugated or killed 征服或杀害.  +

You know, just like Jesus would have done.  +

Now, we need to talk about the African slave trade, and it's connected to the encomienda system. And under that system, the natives of America were subjected to 遭受 forced labor 强迫劳动 on Spanish plantations.  +

When colonies were established in the Americas, one of the first things colonizers 殖民者 did was begin looking for mineral wealth 矿产财富. But it soon became apparent that with the warm climate -- especially in the Caribbean and South America and North America -- that planting 种植 would be a much more prominent source of wealth 财富来源.  +

Goods like sugar 糖, coffee 咖啡, etc., which were once luxury items 奢侈品, became cheaper and more accessible to the middle class 中产阶级, and therefore, demand for these goods spiked 激增. And so too did the demand for labor 劳动力需求.  +

But there were two problems with this arrangement according to the Spanish. The first is that because the natives knew the land better than the Spanish did, they were able to escape the harsh conditions 恶劣条件 relatively easily.  +

Second, the natives were rude enough to keep dying in large numbers from European diseases. Therefore, this, in turn 反过来, caused a spike in demand for enslaved African labor 非洲奴隶劳动力 in the Americas.  +

Africans had been in contact with Europe and their diseases for millennia and thus had some degree of immunity 一定程度的免疫力. Also, they didn't know the land and were less likely to escape 逃跑. And so forced African labor gradually replaced 逐渐取代 forced indigenous labor 原住民劳动力.  +

And the life of these workers was harsh and very difficult. Their journey to the Americas began on the Middle Passage 中间航程. Depending on the weather, it could take something like one to six months to cross the Atlantic, and the conditions on board the ships were inhuman 不人道的.  +

To the slave traders 奴隶贩子, the more goods they could pack onto a ship, the more profit they stood to earn 赚取利润. So Africans were malnourished 营养不良, treated shamefully 受到恶劣对待, frequently died of disease 死于疾病. And if they even made it alive to the New World, a life of brutal plantation slavery 残酷的种植园奴隶制 awaited them.  +

So yeah, we mark this one in the column of egregious sins 严重罪行 of the Age of Exploration.  +

Okay, now the last thing we need to talk about in this unit is the Commercial Revolution 商业革命. I already mentioned how the new economic realities 经济现实 during this period brought feudalism to an end 终结 and started to replace mercantilism 重商主义 with capitalism 资本主义.  +

Now, to be clear 明确地说, mercantilism wouldn't fully recede 完全消退 for another century or so after this period ends, but the beginnings of that recession 衰退 are here.  +

So the Commercial Revolution describes the great increase in global commerce 全球贸易增长 during this period that changed the face of economics 经济面貌 in Europe. And there were a few ingredients 因素 in this revolution.  +

First were changes in banking and finance 银行和金融领域 and especially the rise of the money economy 货币经济. This means that goods, services, wages, and investments were now made with cash 现金 instead of gold and silver. This replaced the economy in which people grew or made most of their resources 资源.  +

As a result, we saw the rise of great banking centers 银行中心 in Genoa 热那亚, Amsterdam, and London. And there are a couple of economic innovations 创新 here that you should know about.  +

First, double-entry bookkeeping 复式记账法. This was a detailed ledger 账簿 kept of all debits and credits 借方和贷方, and in order for an account to be balanced 平衡, debits had to be equal to credits. And look, you don't necessarily need to understand how this system worked, but you should know that the need for such a system like this indicated that metric buttloads of money 大量资金 were being handled in these banking centers.  +

A second innovation that promoted the growth of the money economy was the joint-stock company 股份公司, in which investors bought stock 股票 in a company's profits, raising large amounts of capital 资本. So you need to understand that this was, in many places, a private enterprise 私人企业 as opposed to 与…相反 a state-driven mercantilist enterprise 国家主导的重商主义企业.  +

A good example is the Dutch East India Company 荷兰东印度公司, formed in 1602 to finance trade 为贸易提供资金 in Asia.  +

Okay, we should also talk about how all this affected social hierarchies 社会等级制度. Now, I said just a little earlier that the economic changes during this period brought this system of feudalism to an end, but here's where I complicate that a little.  +

On a grand scale 从宏观层面, that's true, but when you zoom in 放大 and focus on local communities 当地社区, many of the tenets 原则 of feudalism still remained. This was the system in which a king granted land 授予土地 to nobles who farmed the land and protected it. Nobles employed the peasantry 农民 -- which is to say, serfs 农奴 bound to the land 依附于土地 -- to work the land and knights 骑士 to protect it.  +

Therefore, life was largely oriented around 围绕…展开 the manor 庄园, which was the agricultural estate 农业庄园 under noble's control, or the seasons 季节, or the village 村庄. In that way, subsistence agriculture 自给农业 was the rule 普遍现象 in most places in Europe, and that just means a family grew what they needed to subsist or survive 生存.  +

And to survive, families had to plant lots of different crops 作物, as opposed to 与…不同 the cash crop system 经济作物种植体系 that prevailed on the plantations in the Americas, where they only grew a single crop 单一作物 for export 出口 on the market.  +

And for those whose lives depended on the land, soil exhaustion 土壤耗竭 was a constant threat 持续威胁. If you're not a farmer, you probably won't know, but don't worry, I'm about to tell you that if you plant the same crops in the same soil year after year, the nutrients 养分 in that soil will eventually be leached dry 耗尽.  +

So for example, let's say for simplicity that a particular plot of soil 地块 has nutrients A through F within it, and let's further suppose that wheat 小麦 needs A through C to grow well. If you keep planting wheat in a field, eventually there will be no more A through C nutrients in that soil, and it will be exhausted 耗尽肥力.  +

That's a problem because, you know, we got to eat. So the solution to this problem? Crop rotation 作物轮作.  +

In Mediterranean Europe, they employed what was called the two-field system 两田制. That means that half of the land lay fallow 休耕 for a period of time in order to replenish the nutrients 补充养分 while the other half was planted and harvested 种植和收割.  +

In Northern Europe, they developed the three-field system 三田制. They divided their fields into three sections 部分, and crops were planted in one and two in the fall 秋季, and then different crops planted in one and two in the spring 春季, and then section three was left fallow that year. Then the next year, rotate 轮换.  +

The point is, two-thirds of the land was productive 可耕种的 during planting season 种植季节 while one-third was left fallow to replenish its nutrients.  +

Okay, now the Commercial Revolution was caused by the Price Revolution 价格革命. With the influx of Spanish silver and gold to the European economy, along with greater circulation of money 货币流通 and population growth 人口增长, all this caused the prices of food and necessities 生活必需品 to rise over an extended period of time 长时间上涨.  +

This inflation 通货膨胀 contributed to 促成 the growth of commerce known as the Price Revolution, and this was critical 关键的 in the commercialization of agriculture 农业商业化. So large landowners 大地主 and capitalist investors 资本家 began to see the open-field system 敞田制 as wasteful 浪费的 and desired to increase available land 可利用土地 so that crop yields 农作物产量 would increase.  +

Therefore, legislation 立法 was passed in England, for example, that allowed investors to purchase public land 公共土地. This land was known as the commons 公地, and it was a critical piece of land for the peasantry 农民 because it was the only place they could bring their livestock 牲畜 to graze 放牧. But this increasing need for land by commercial farmers led to what's called the enclosure movement 圈地运动. In other words, the land that was previously available to all was being enclosed 围起来 and therefore shrinking 缩小 smaller and smaller. +
Not surprisingly, this movement benefited large landowners with stupid amounts of profits 巨额利润，but it very much disrupted norms 破坏常规 and life for the peasantry and therefore led to increased poverty 贫困加剧. +
Now, the results of the enclosure movement we're going to consider more in the next unit, but here it's enough to know that it caused a massive migration movement 大规模迁徙 of the landless poor 无地贫民 into cities to look for work. And the word for that is urbanization 城市化. +
However, nobles also moved into the cities in some cases, and the influx 涌入 of both led to the resentment 怨恨 of the urban merchant classes 城市商人阶层. And the problem of housing 住房问题 was particularly acute 严重的，but we'll pick that up in the next unit. +
Okay, that's Unit 1. You can click right here to grab my Ultimate Review Packet 终极复习资料包，which is going to help you get an A in your class and a 5 on your exam in May. +
If this video helped you and you want me to keep making them, then by all means 务必，click the subscribe button 订阅按钮，and I shall oblige 照办. +
Heimler out. +


'''

== 中文释义

好的，如果你需要复习AP欧洲历史的整个第一单元，那么你来对地方了。所以，如果你准备好让大脑运转起来，那我们就开始吧。 +

现在，我们首先要谈论的是文艺复兴。**“文艺复兴” 这个词意味着重生，也就是说一些曾经消逝的东西又复活了。**那么，是什么消逝了，又**是什么重生了呢？嗯，是来自罗马和希腊的经典文本和思想。** +

**在整个中世纪——也就是文艺复兴之前——欧洲人大多遗忘了这些学说，**至少那些不是整天和僧侣在一起的人是这样。**但##多亏了伊斯兰学者, 将古希腊和罗马的著作翻译成阿拉伯语和拉丁语，也多亏了在十字军东征期间欧洲人与伊斯兰教徒接触增多，欧洲人开始重新接触到这些古老的思想。##这些文本和思想的重现基本上促成了文艺复兴，**顺便说一下，*文艺复兴始于意大利。* +

如果你想要这个视频的笔记指南，你可以查看我的AP欧洲历史终极复习资料包，描述中提供了链接。 +

在这方面的第一个关键人物是一个叫"彼特拉克"（Petrarch）的人。虽然严格来说他在文艺复兴之前，但这并不重要。**彼特拉克为文艺复兴思想奠定了许多基础，他的哲学被称为人文主义。**这很重要——非常重要。把它写下来，如果需要的话，甚至可以把它纹在你的额头上。*人文主义是一种哲学，它把人类无限的潜力本身当作目的来关注。* +

**在彼特拉克的分析中，人类是最了不起的，**尽管没人这么说。*这些小小的肉身有机体有着无限的潜力。所以人文主义，连同强调"个人胜利"的个人主义，成为了文艺复兴时期大部分时间的主要思维模式。* +

彼特拉克的一个重大发现是罗马演说家西塞罗（Cicero）的著作，彼特拉克认为西塞罗华丽的拉丁语作品, 应该成为拉丁语的典范。换句话说，就是西塞罗式的拉丁语。不错。总之，彼特拉克尤其被"西塞罗对罗马共和国的有力支持"所打动——不是罗马帝国，是共和国。这一点很重要。而且彼特拉克还被"西塞罗反对暴君尤利乌斯·恺撒（Julius Caesar）篡夺权力"的行为所打动。这些主题在整个文艺复兴时期都非常重要。 +

同样在文艺复兴时期，我们看到了对文本的新的"语文学"研究方法的发展。语文学？嗯，**语文学是对语言的历史和发展的研究。**也许这听起来就像把墙刷成两种灰色调，然后看着它先干哪一块一样无趣。但在文艺复兴时期，新的语文学方法可是件大事。 +

举个例子：洛伦佐·瓦拉（Lorenzo Valla）在1440年因**证明"罗马天主教会的一份权威文件是伪造的"(犹如中国的考据学),** 而成为语文学界的头条新闻。不信？哦，是真的。**这份文件据说是公元4世纪罗马皇帝君士坦丁（Constantine）所写，但瓦拉证明了君士坦丁文件中的拉丁语结构, 不符合4世纪的拉丁语标准。**所以，这份文件不具权威性。把它扔了吧。 +

这很好地说明了**文艺复兴的一个主要主题，即从"宗教权威"转向"世俗权威"。**公平地说，许多文艺复兴时期的思想家仍然是基督徒，但总体而言，这场运动是从《圣经》的启示权威, 和教会的教义, 转向更多科学的探究模式。 +

另一个重要的思想转变, 是从"对人类的集体理解", 转向"个人主义的人类观念"。*起初，所有这些新思想, 在很大程度上只局限于少数精英阶层。但在1440年代，随着活字印刷术的发明，这些思想得以广泛且迅速地传播*——传播得如此之广，*以至于这些思想开始挑战大学和其他权力中心的制度权力。(所以独裁国家才会这么害怕启蒙书籍的传播, 才会封杀思想, 禁书, 禁言)*  +

关于印刷术，我们稍后再详细说，但现在，让我们看看它在教育方面是如何发挥作用的。 +

**中世纪的学者主要关注"神学"问题。**但随着文艺复兴时期对经典文本的兴趣日益浓厚, 以及人文主义推理的建立，教育经历了巨大的变革。*文艺复兴时期的学者将"人文学科"引入课程，这些学科强调历史、道德哲学、诗歌等等*——所有这些都基于经典文本。 +

作为人文主义者，**对人文学科的强调, 旨在拓展人类的人性和无限潜力。**因为，你懂的，这就是人文主义。 +

在这方面的一个关键思想家是巴尔达萨雷·卡斯蒂廖内（Baldassare Castiglione），他的著作《廷臣论》（The Courtier）是关于一个受过教育的年轻人, 在宫廷社会中应该如何表现的指南——也就是说，成为一名绅士。**他认为，一个绅士应该精通所有人文学科，比如能雄辩地写作和演讲，**身体强壮，*最重要的是，精神清醒(理性有逻辑)。* +

这些新思想也影响了公民和政治机构，这从意大利的城邦开始。记住，*#在这个时期，意大利并不像我们现在所知道的那样是一个统一的国家。相反，它是由一群地区王国和自治社区组成的。#* +

**#当这些人文主义思想, 渗透到政治和公民领域时，其结果被称为"公民人文主义"，基本上就是说"受过教育的人, 应该积极参与地方政治"。#**我想我们应该举几个例子。 +

首先是莱昂纳多·布鲁尼（Leonardo Bruni）。*他认为古罗马的"共和主义"是最好的政府形式，由开明的个人统治是最好的。这与中世纪的"封建政府结构"相比是一个巨大的转变。* +

其次，还有我们的尼可罗·_马基雅维利_（Niccolò Machiavelli）。他写了一本名为《君主论》（*The Prince*）的小书，在书中**他认为, 统治者的基本职能是不惜一切代价维护权力。因此，君主应该以任何有助于实现这些目标的方式行事(为达目的,不择手段)。如果仁慈有助于他达到目的，那就仁慈。如果成为一个暴君有助于达到目的，那就做一个暴君。** +

**然而，马基雅维利认为**土耳其式的**暴政是有限度的。君主必须达成一种开明的平衡。**你必须使用一切必要的手段来建立秩序和安全，但不要以让人民讨厌你的方式行事。或者，用马基雅维利自己的话说：“*对君主来说，被人畏惧,比被人爱戴更安全，但他应该避免让自己被人憎恨。*” +

**但归根结底，马基雅维利认为, 统治者应该维护权力，**即使这意味着做出自私的决定，*而不顾道德和伦理信仰。这与中世纪大不相同，在中世纪，欧洲统治者的品格, 是由诸如谨慎和智慧等《圣经》中的美德来定义的。* +

好的，现在让我们换个话题。如果不谈论艺术的新生，我们就无法谈论文艺复兴。如果你对文艺复兴有所了解，很可能了解的是它的艺术。 +

*##中世纪的艺术家几乎只描绘宗教主题，充满了象征意义，##但这些作品是平面的，不太符合现实。另一方面，##文艺复兴时期的艺术家强调自然主义，这更具"现实性"，描绘的是世界的真实面貌，##而不是象征性人物的神秘之处。* +

*意大利文艺复兴时期的艺术家, 更倾向于"自然主义"的"理想主义"一面，而"北方文艺复兴"时期的艺术家*——我们稍后会详细介绍他们——**运用"自然主义"来描绘日常生活场景。**还有**一些大师掌握了"几何透视"的新技术，**艺术家们通过这种技术, 试图为他们的画作增添深度和真实感。 +

**文艺复兴时期的艺术家, 确实在他们的作品中继续描绘宗教主题，但他们也涉及个人、政治和经典主题。**你需要了解一些这些艺术家，所以让我们认识一下他们。 +

首先是米开朗基罗（Michelangelo）。在这里你可以看到一尊圣经人物**大卫（David）的雕塑。注意其中体现的"人文主义哲学"。这是人类的完美典范，但却按照希腊神的形象雕刻而成。此外，注意大卫肌肉的细节和他脸部的特征。这就是文艺复兴艺术的自然主义和理想主义。** +

其次，让我们认识一下拉斐尔（Raphael）。在这里你可以看到他最著名的画作之一《雅典学院》（The School of Athens）。这是文艺复兴时期的艺术家采用"经典主题"的一个例子，**"经典主题"是文艺复兴的核心。**在画作中间，有经典英雄柏拉图（Plato）和亚里士多德（Aristotle）。还要注意他运用几何透视法使画作的结构看起来很真实的方式。 +

第三，让我们看看**一些建筑。**为此，让我给你介绍菲利波·布鲁内莱斯基（Filippo Brunelleschi）。他是佛罗伦萨"圣洛伦佐教堂"（church of San Lorenzo）重建的建筑师。*注意他摒弃了中世纪大教堂的哥特式传统，用罗马柱和拱门建造了这座教堂。* +

他最著名的作品是"佛罗伦萨大教堂"（Florence Cathedral）的穹顶。现在，这可能在你看来没什么，但这是一项天才的工程壮举，因为**中世纪大教堂的飞扶壁太具有中世纪风格了。布鲁内莱斯基建造的这个穹顶可以独立支撑，不需要任何外部支撑。** +

关于文艺复兴艺术，你最后需要知道的是：**这些艺术家, 大多受到富人和统治者以及教皇的资助。**这是因为这些人热爱艺术，希望看到人类天才的美丽作品诞生吗？呃，不是的。*这些领导人资助艺术是为了提高他们的公众威望*。“嘿，你喜欢那幅新的米开朗基罗的作品吗？是我出资的。” +

这些资助者中最著名的是"美第奇家族"（Medici family）——我们稍后会详细介绍他们。 +

好的，正如我所说，文艺复兴始于意大利，但很快也传播到了欧洲其他地区。*在印刷术的帮助下，意大利文艺复兴的思想, 传播到了意大利阿尔卑斯山以北的欧洲其他地区。当这些思想在北方扎根时，我们称之为"北方文艺复兴"。* +

**然而，随着这些思想向北传播，**人文主义的主要基础和"经典的复兴"保持不变，但一些重点发生了变化。主要的变化是，*与更加世俗的意大利文艺复兴相比，它发展出了更多的宗教——也就是说，基督教——倾向。* +

*##所以, 当文艺复兴传播到低地国家、法国、德国和英国时，人们努力将"人文主义"与"基督教思想"融合。其结果就是"基督教人文主义"。##他们的目标是将"人文主义思想"的最佳元素, 与《圣经》权威结合起来。这导致了对"社会改革"的高度重视。* +

**与"基督教人文主义"相关的一个名字, 是**德西德里乌斯·伊拉斯谟（Desiderius Erasmus）。**伊拉斯谟认为，**对经典和《圣经》的教育, 是真正"社会改革"的基础，*复兴应该基于基督的哲学。* +

你应该了解伊拉斯谟的作品《愚人颂》（*In Praise of Folly*）。这是一部讽刺作品，旨在削弱腐败的政治和社会机构，并批评"宗教等级制度"的腐败方面。 +

意大利文艺复兴有他们的艺术家，北方文艺复兴也有。然而，*"北方文艺复兴"时期的艺术家, 比更加世俗的"意大利文艺复兴"时期的艺术家, 更具有宗教、基督教的倾向。他们的艺术仍然是自然主义的，但更加以人为中心，认为日常物品和人更适合作为艺术的对象，而意大利艺术家的崇高主题有时是超世俗的。* +

例如，让我们谈谈荷兰和佛兰德斯文艺复兴时期的老彼得·勃鲁盖尔（Pieter Bruegel the Elder）。这是他的画作《农民的婚礼》（The Peasant Wedding）。你知道，**这里的主题不像《创世纪》那样宏大，相反，你看到的是普通人在庆祝婚礼，吃着普通的食物。**但仍然，你可以看到对自然主义的强调。人物的特征看起来很真实。 +

好的，然后是荷兰文艺复兴时期的伦勃朗（Rembrandt）。哦，他的作品太棒了。他以描绘光影的能力而闻名，正如你在他的作品《浪子回头》（The Return of the Prodigal Son）中看到的那样。这是耶稣寓言中的一个场景，你几乎能感受到画作中深刻的情感。对伦勃朗来说，不仅仅是复制一幅画，而是在作画时融入《圣经》的叙事，这一点非常重要。 +

好的，这就是北方文艺复兴。 +

我已经提到了印刷术在文艺复兴和人文主义思想传播中的作用，但现在我们需要正面探讨一下。印刷术是一件大事。我怎么强调它在这段历史时期所起的作用都不为过。 +

**在印刷术出现之前，重要的书籍都是手写复制的。**如果你去过艾波卡特中心的 “地球号宇宙飞船”，你就知道这一点。这个过程既费力又昂贵。*这意味着书籍数量不多，而且仅有的书籍要么被教堂保存，要么被那些买得起书籍副本的富人收藏在图书馆里。* +

**更不用说，大多数书籍都是用拉丁语写的，这意味着只有牧师和僧侣才能阅读。**总之，一切在1440年代发生了变化，当时几位德国金属工匠开发了印刷术，这使得印刷作品能够以以前无法想象的速度和数量被复制和出版。 +

与这项技术联系最紧密的工匠是约翰内斯·谷登堡（Johannes Gutenberg）。由于一种名为活字印刷的新发明，印刷术能够快速且廉价地生产书籍。在活字印刷中，金属字母被排列成行，蘸上墨水，然后压在一张纸上。 +

多亏了传播到欧洲的中国造纸技术，纸张的大量供应, 使大规模印刷成为可行的现实。1456年，谷登堡在印刷机上出版的第一部重要作品是《谷登堡圣经》（Gutenberg Bible）。然后，在50年内，欧洲出版了大量书籍——大约在1000万到2000万册之间。 +

有了这项新技术，书籍和小册子中所写的思想能够迅速传播。实际情况也正是如此。到1515年，*所有主要的经典作家——比如柏拉图、亚里士多德和普林尼等等——的作品都被印刷出来并迅速传播。* +

**印刷术在"新教改革"中也发挥了重要作用。**马丁·路德（Martin Luther）声称天主教会已经堕落为异端和腐败的机构，*多亏了活字印刷术，他的思想得以广泛传播(广泛开启民智)，并对教会等级制度造成了严重打击。* +

但我们将在下一单元中更多地谈论"新教改革"，所以现在先讲到这里。 +

*印刷术也创造了对vernacular literature（通俗文学，即不是用拉丁语, 而是用普通人的语言——比如英语、西班牙语或法语——写成的文学作品）的需求。##当书籍用人们的"母语"印刷出来，##人们一起阅读时，#这为"民族文化"的发展创造了条件。#* +

例如，**在"新教改革"期间，马丁·路德制作了德语版的《圣经》，**这可是件大事，因为在此之前，人们只能听到拉丁语版的《圣经》。但这样做，路德为德语创造了一个标准，*从根本上塑造了德国的民族文化。* +

好的，我想我们应该谈谈一些政治方面的内容。在这个时期，国王在行使和巩固权力的方式上, 出现了一些非常重要的发展。 +

回到**#中世纪，国王的权力并不像你想象的那么大。#**你知道，当你看一部以中世纪为背景的电影时，国王似乎拥有绝对权力，对每个人发号施令？是的，但实际情况并非如此。*#当时大部分权力掌握在贵族手中。#* +

**但在这个时期，君主和王子们开始从贵族手中夺取权力，并将权力牢牢掌握在自己手中。**这种转变的一个结果是自上而下的宗教和道德改革。 +

鉴于此，我想我应该给你介绍一下英国的亨利八世（Henry VIII）。他实际上反对"新教改革"对天主教会带来的新宗教发展。事实上，他非常反对改革，以至于教皇授予亨利 “信仰的捍卫者” 的称号。 +

但后来亨利与天主教徒产生了一些矛盾。他结婚20年的妻子未能生下男性继承人，所以他做了任何一个有自尊心、自我牺牲的基督徒会做的事情：他向教皇请求废除婚姻。真是个 “高尚” 的人。 +

但碰巧的是，他的妻子是天主教西班牙的费迪南德（Ferdinand）和伊莎贝拉（Isabella）的女儿，他们向教皇施压，拒绝了亨利废除婚姻的请求。他们成功了。但后来亨利的情妇安妮·博林（Anne Boleyn）怀孕了，所以亨利干脆与妻子离婚，娶了安妮。 +

不出所料，*教皇宣布这段婚姻非法，于是##亨利谴责教皇，议会通过了一项法律，使亨利成为新成立的英格兰教会（Church of England）的领袖，而"英格兰教会"显然不受罗马的管辖。##* +

许多英国人仍然是虔诚的天主教徒，但记住，我们这里谈论的是"自上而下"的宗教改革。为此，亨利通过了《叛国罪法案》，拒绝承认英格兰教会为国教的人, 将被判处死刑。 +

好的，现在让我告诉你亨利的一个后代的事情，即**伊丽莎白一世（Elizabeth the First）。在亨利的女儿玛丽·都铎（Mary Tudor）统治之后，她登上了王位。玛丽试图在英国恢复天主教，并且因为将任何反对她的"圣公会"主教砍头, 而获得了 “血腥玛丽” 的绰号。** +

不管怎样，**伊丽莎白使英国重新回归"圣公会"，并结束了对持不同政见者的迫害。**同样，她是自上而下地进行这项改革的。她通过了《统一法案》，规定英国臣民必须参加"圣公会"教堂的活动——圣公会就是"英格兰教会"的另一个名字——而且他们必须每周参加一次，否则将被罚款。 +

好的，这就是几位新君主进行"自上而下"的宗教和道德改革的方式。 +

现在，让我们看看**其他一些新君主, 是如何通过做一些事情, 为"现代国家"奠定基础的，这些事情包括：建立税收垄断权、动用军事力量, 和实施司法，以及获得"决定臣民宗教信仰的权利"。** +

让我们从西班牙的费迪南德和伊莎贝拉开始。费迪南德来自西班牙的阿拉贡地区，这个地区强大且组织有序。伊莎贝拉来自卡斯蒂利亚地区，那里有点混乱。*他们的婚姻开启了"西班牙统一"和"君主权力巩固"的进程。* +

那么他们是如何运用这些权力的呢？嗯，他们通过"对财产销售和交换, 征收一系列国家税", 来增加收入。他们建立了一个精心设计的官僚机构，以君主的名义征税, 并裁决司法问题。 +

他们还推进并完成了所谓的 “收复失地运动”（Reconquista），将穆斯林和犹太人赶出伊比利亚半岛，*并将"天主教"确立为西班牙的官方宗教。* +

好的，让我们看看在法国是如何发展的。法国的君主们使用了类似的权力巩固方法，即"国家税收"和复杂的官僚机构。**法国也是一个天主教国家，**为此，你应该了解1516年的《博洛尼亚协约》（Concordat of Bologna）。 +


这是**法国国王弗朗索瓦一世（Francis the First）和教皇利奥十世（Leo the Tenth）之间的一项协议，产生了两个结果：#教皇获得了"从法国天主教会,收取收入"的权利，而弗朗索瓦保留了"任命法国天主教会领袖"的权利，从而限制了他们与教皇直接沟通的权利。(即法国国王给教皇一笔钱, 作为交换, 教皇没有对法国教会的人事任免权. 人事权掌握在法国国王手里.)#** +
*这一切意味着什么呢？意味着国王的权力更大了。* +

**现在，这些新君主也开始声称, 有权决定他们臣民的宗教信仰。**1555年的**《奥格斯堡和约》（Peace of Augsburg）赋予了"神圣罗马帝国"的个别领导人,决定他们的臣民是"天主教徒"还是"路德教徒"的权利。** +

当然，这不仅仅是"哈布斯堡统治者"在宗教方面的决定。**选择臣民宗教信仰的权力, 也是巩固权力的一种手段。**毕竟，如果一个君主的人民——甚至只是其中的少数人——相信"与君主相悖的其他宗教教义"，这可能会削弱君主对人民的影响力。 +

如果我说在**这个时期**只有君主在获取权力，那我就是在说谎。*#商业和专业团体也获得了权力，并在政治事务中发挥了更大的作用 (即将迈入资本主义的前夜)。其中主要是商人和银行家，特别是在意大利和德国的一些邦国。#* +

我知道你很想知道一些例子，所以我就满足你的愿望。**美第奇家族基本上在意大利建立了银行业，**而富格尔家族在德国的奥格斯堡也做了类似的事情。 +

这些人在他们的金库中积累了大量财富，其结果是：*随着货币经济的兴起, 以及这些团体与君主的紧密联盟，他们在各自的影响范围内, 行使了更大的政治权力。* +

现在，*这个时期的另一个主要主题, 是欧洲的探索。欧洲人不再满足于待在他们的大陆上，所以他们中的一些人开始乘船去寻找其他地方居住和贸易。* +

首先，我们可能需要谈谈**#欧洲人进行探索的原因，#**对此，**我##用三个词来概括：黄金、上帝和荣耀。##**让我们依次看看这些原因。 +

首先，欧洲人开始海上探索的动机是上帝。我们已经确定在这个时期，*欧洲人对他们人民的宗教非常热衷，那么为什么不更加积极地去寻找其他人来皈依呢？* +

举个例子：**西班牙。他们当然想尽可能广泛地传播天主教。**正如我已经提到的，到1492年，他们完成了收复失地运动，把犹太人和穆斯林赶出了他们的土地。在新教改革时期，他们希望看到天主教相对于新教占据主导地位。 +

*当他们找到了通往新世界的路后，他们派遣耶稣会传教士, 去让当地的原住民皈依天主教。然而，许多欧洲人认为原住民是低等人类，因此适合从事强迫劳动。就这样，基督教成为了控制和征服的工具。* +

然而，我必须赶紧补充一点，并不是所有西班牙人都这样看待美洲原住民。例如，西班牙牧师巴托洛梅·德拉斯·卡萨斯（Bartolomé de las Casas）努力在美洲建立天主教的影响力，并且为美洲人民的尊严而斗争。 +

好的，**探索的第二个动机是黄金。**为此，我需要给你介绍**"重商主义"（mercantilism），这是这个时期欧洲占主导地位的经济思想和经济体系。** +

关于**#重商主义#，**你需要理解的主要一点是，**这是一种##认为世界上的财富是有限的，并且财富可以用黄金和白银来衡量##的体系。**你知道，*#如果用这种方式(如果只是用黄金)来衡量财富，那么是的，世界上的黄金和白银是有限的(这个理论延伸, 那么财富就是零和博弈了, 你拥有的黄金多, 我得到的就会少. 那时的人还不知道世界经济总量可以通过国际贸易, 来将蛋糕做大#*.)。 +

所以一个信奉"重商主义"的国家, 就想要尽可能多地获取黄金和白银，也就是说，*#拥有最多黄金的国家就是赢家。所以，重商主义会追求实现所谓的"贸易顺差"，这基本上意味着一个国家的出口,要多于进口。#* +

仔细想想，这很容易理解为什么。*##如果一个国家出口商品，那就意味着黄金和白银会流入。而如果他们从其他国家进口商品，那就意味着他们的黄金和白银会流出。##记住，他们以为拥有最多黄金的国家会赢，所以这就是他们想要减少进口、增加出口的原因。* +

与此相关的是，*#在"重商主义"的思维模式下，建立"殖民地"几乎是必要的，因为那些遥远的土地, 不仅可以为母国提供更多像黄金和白银这样的矿产财富，还可以提供用来制造"可销售商品"的原材料，而这(将最终产品卖出去)又会带来更多的黄金。#* +

你明白我的意思吗？ +

好的，让我给你举个例子，说明"重商主义"是如何激发探索, 以及法国财政总监让-巴蒂斯特·柯尔贝尔（Jean-Baptiste Colbert）的政策的。柯尔贝尔像任何优秀的"重商主义者"一样，认为一个国家的财富应该为国家服务。 +

**为了实现"贸易顺差"，柯尔贝尔提出了一些政策，要求法国工业生产人民所需的一切，这样他们就不必进口商品 (让国内有完整的产业链, 可以内循环)。**此外，柯尔贝尔的目标, 是尽可能多地宣称对北美地区的所有权，在这方面的主要成就是魁北克, 和北美的路易斯安那领地。 +

在这个标题下还有一件事：*#欧洲人进行探索的动机, 还包括对来"自亚洲的奢侈品"的需求不断增加。但他们有一个问题：穆斯林奥斯曼帝国控制了欧洲和亚洲之间的所有陆路，因此欧洲人不得不为这些商品支付极其高昂的价格 (有中间商赚差价. 欧洲想直接和原厂家接触, 直接进货, 跳过中间商)。#* +

那么他们该怎么办呢？嗯，*为什么不派一些船只进入奥斯曼帝国的势力范围(去鲨鱼家看看)，看看会发生什么呢？* +

好的，*探索的第三个动机是荣耀。一旦殖民游戏开始，欧洲列强之间就产生了激烈的竞争，都想尽可能多地夺取殖民地。也就是说，如果殖民地是走向统治的途径，那么每个地区的强国都试图在这个游戏中获胜。* +

好的，这些就是探索的主要动机。现在，让我们花点时间考虑一下**使他们能够进行探索的原因 -- 新的和改良的航海技术。** +

**首先，在制图学（也就是地图制作）方面取得了进步。**这些地图更加详细，**并且印刷术**使它们在整个大陆都能广泛传播。 +

其次，出现了新型的船只。例如，西班牙和葡萄牙开发了卡拉维尔帆船（caravel），这种船速度快且易于航行。它速度快的一个主要原因是**"三角帆"（lateen sail），它可以从任何方向获取风力，而不像"方形帆"那样只能从后面获取风力。** +

他们还使用了指南针（compass），这有助于确定方向，以及星盘（astrolabe），它是从中国和穆斯林航海家那里获得的，可以准确计算纬度。 +

你可能会想，“三角帆？星盘？谁在乎呢？” 但相信我，这些都是巨大的创新。就好比如果史蒂夫·乔布斯生活在500年前，他会穿着高领毛衣站在舞台上说，“这是我们制作的最棒的三角帆。” 然后所有人都会起立鼓掌，为之疯狂。“看看它多么像三角形啊！” +

所以这些技术是非常重要的。 +

现在，正如我提到的，**这股新的探索浪潮, 在欧洲国家之间引发了相当激烈的竞争 (犹如如今 AI人工智能还在发展中, 中美对其的激烈研究竞争)。**所以让我们首先谈谈殖民帝国本身，然后再谈谈这些帝国是如何影响列强之间的关系的。 +

由于**#葡萄牙是最早进行探索的国家#，**我们就从葡萄牙开始吧。*#他们是最早积极寻找通往亚洲海路的欧洲人，他们通过环绕非洲航行来实现这一目标。#* +

*#当他们沿着非洲海岸航行时，葡萄牙人没有占据大量的"殖民地"，因为建立和维持殖民地成本很高，相反，他们在海岸沿线建立了"贸易站"，这就是为什么他们的帝国被称为"贸易站帝国"。#* +

*##最终，他们一路进入了印度洋，##随着时间的推移，他们在通往东南亚的贸易中占据了主导地位。* +

**#接下来是西班牙，#**西班牙的君主费迪南德和伊莎贝拉委托一位名叫克里斯托弗·哥伦布（Christopher Columbus）的意大利水手, 也去寻找通往亚洲的海路。但**##哥伦布没有环绕非洲航行，而是决定向西横渡大西洋，以便与亚洲的香料贸易建立联系。##** +

正如你可能知道的，有几个巨大的大陆挡在了他的路上，而欧洲人之前并不知道这些大陆的存在。所以哥伦布登陆了巴哈马群岛，*并最终为西班牙宣称了加勒比海、中美洲、北美洲的大部分地区, 以及南美洲的海岸线(势力范围)。* +

你看，*人们能够获得如此多的领土，很大程度上是因为他们为美洲带来了像天花和麻疹这样致命的疾病*——我们稍后会详细讨论这个问题。 +

*#然后法国也加入了探索的行列。他们最终宣称对"北美的大部分地区"和"加拿大"拥有主权。主要是，他们对贸易很感兴趣，尤其是毛皮贸易。因此，他们没有建立很多正规的"殖民地定居点"。#* +

我们也不要忘记**#英国。他们向西航行，宣称对加拿大的部分地区、加勒比海地区, 以及"北美的东海岸"拥有主权。英国人建立了"定居殖民地"，也就是说，人们去那里开始新的生活，建造家园，而不仅仅是进行贸易。# **+

*#荷兰也强行加入了这场探索。荷兰人主要对贸易感兴趣，为此，他们在美洲建立了一些殖民地，但主要专注于在"东南亚"的贸易中占据主导地位。#* +

那么，*这场对殖民地的争夺, 是如何影响这些欧洲强国之间的关系的呢？嗯，情况变得很糟糕。当紧张局势出现时，他们基本上有两种解决方式。* +

**第一种是"外交和谈判"。**例如，西班牙和葡萄牙在**1494年签订了《托尔德西里亚斯条约》（Treaty of Tordesillas）。这是由教皇亚历山大六世（Pope Alexander VI）调解的，双方同意以这条分界线来划分美洲：西班牙得到分界线左边的一切，葡萄牙得到右边的一切。**嘿，这还不错。 +

但国家间处理竞争的**第二种方式**就有点激烈了，那**就是"胁迫和战争"。**由于《托尔德西里亚斯条约》基本上将世界的殖民领土一分为二，这在后来引发了一些武装冲突。 +

*由于北美的大部分地区, 都落在了西班牙的势力范围内，这在接下来的时期, 引发了西班牙和英国之间的竞争，因为英国也想宣称对那些诱人的殖民地拥有主权。* +

最终，**在接下来的时期，#法国、西班牙和英国——以及其他一些国家——为了争夺新世界的殖民地, 而爆发了"西班牙王位继承战争"#（War of Spanish Succession）。**但我们会在讲到那个时期的时候再详细讨论这个故事。 +

关于这些不断加剧的紧张局势和竞争，你真正需要记住的是：**##对所有欧洲国家来说，关键是"权力平衡"(势力均衡)。没有人希望任何一个欧洲强国独占所有好处——或者说，占据大部分好处。##大致来说，只要大家的实力相当，一切就相安无事。 **+


好的，现在**随着旧世界（也就是欧洲）和新世界（美洲）之间的接触增多，**一件极其重要的事情发生了，那就是"哥伦布大交换"（Columbian Exchange）。 +

从定义上来说，**"哥伦布大交换"是旧世界和新世界之间, 在商品、植物、动物、文化习俗, 和疾病方面的全球交换。**所以当欧洲人在美洲和非洲建立"殖民地"和"贸易港口"时，大规模的交换发生了。*而这次交换, 改变了三大洲的社会、经济和环境 (时代变了, 旧时光已经回不去了)。* +

所以让我们谈谈发生的**五类交换。** +

**首先是疾病。**西班牙非常渴望在美洲拥有殖民地，当他们掌控了这些土地和人民后，他们试图按照自己的形象重塑美洲。但他们的船只最多只能搭载几百名水手，那么他们是如何征服这么多人的呢？主要是通过疾病——更具体地说，是天花。 +

你必须明白，非洲人、欧洲人和亚洲人已经相互接触了几千年，因此接触到了彼此的有害病菌，从而建立了一定的免疫力。 +

然而，美洲的原住民完全没有接触过这些病菌，因此没有免疫力。例如，当西班牙人登陆伊斯帕尼奥拉岛时，阿拉瓦克人和泰诺人的人口因天花死亡约30万人。 +

**西班牙征服者埃尔南·科尔特斯（Hernán Cortés）用相对较少的人, 就击败了庞大的阿兹特克帝国——同样是因为引入了天花和麻疹。**所以，埃尔南，收敛一下你的傲慢吧。你并没有那么伟大。 +

其次是**食物的交换。**你可能需要知道一些例子。*从美洲传到欧洲的食物, 包括高产且营养丰富的食物，如玉米、西红柿、土豆和可可。* +

*从欧洲和非洲传到美洲的食物包括: 大米、小麦、大豆、黑麦、燕麦、柠檬、橙子。特别是那些谷物作物改变了美洲人口的饮食，因为它们使饮食多样化，并且在很多情况下延长了人们的寿命。* +

第三是**动物的转移。**欧洲人把马、猪、鸡和牛引入了美洲。猪和牛改变了美洲原住民的饮食。马革新了农业和战争方式。鸡使得我们国家后来能够尽情享用大量的肯德基。 +

哦，天哪，我想到鸡肉就流口水了。感谢哥伦布大交换。 +

第四是**矿物的交换。**这里，我主要说的是黄金和白银。*在征服了印加帝国和阿兹特克帝国后，欧洲人掠夺了他们的土地，#获取了大量的黄金和白银。这使得西班牙变得无比富有 (都不用做生意了, 重商主义本来就是为了获取黄金, 这里直接抢就行了. 不过, 这也会造成国内黄金贬值,通货膨胀)。#* +

如果不是因为这些财富，欧洲殖民者很可能不会不断地回到美洲。但就像老征服者们说的那样，“只要有财富，我们就会蜂拥而至。” 这是一个大致的翻译。 +

不管怎样，这些财富不仅吸引了大量欧洲殖民者，改变了美洲，也改变了欧洲。**从1500年之后开始，**欧洲——更确切地说，是**西欧——经历了前所未有的经济增长。** +

**在这个时期之前的社会、政治和经济体系, 是封建主义，**在这个体系中，农民在贵族的土地上生活和劳作，以换取武装保护。*但##这些财富的涌入, 加速了欧洲"封建主义体系"的终结。##* +

*那么##取代它的是什么呢？##嗯，##是早期形式的资本主义，##这是一种基于私有制和财产所有者之间自由、开放的商品交换的经济体系。* +

哥伦布大交换中的第五种转移是**人口的转移。**这里你需要知道的主要事情是: 非洲奴隶贸易，通过这个贸易，数百万非洲人被强行从他们的土地上带走，被运往大西洋彼岸，为欧洲殖民地的种植园劳作。 +

我们稍后会更多地谈论这个问题，所以先记住这个，我们还会再讲到。 +

现在，让我们通过谈论"哥伦布大交换"对欧洲的影响, 来结束这一部分。 +

首先，*#金银矿物财富的涌入, 和贸易帝国的建立, 将欧洲的经济权力中心, 从地中海地区, 转移到了大西洋沿岸国家，并使这些国家正式融入了全球经济。#* +

**##以前，像"威尼斯"这样的地中海海港, 是经济权力和贸易的中心，但现在不再是了。##在经济全球化和探索的过程中，一个主要的贸易港口, 是荷兰的"安特卫普"，由于它处于**西班牙、葡萄牙、法国和英国**贸易路线的中心位置，变得极其繁荣。** +

*随着时间的推移，"阿姆斯特丹"崛起, 成为欧洲的主要贸易港口，取代了"安特卫普"。然后其他城市也相继崛起，比如"伦敦"和"布里斯托尔"。但关键是，#在探索时代之前，经济权力集中在地中海地区，而现在集中在大西洋沿岸地区。#* +

第二个影响是对人民的征服。**西班牙在美洲创建了一个全新的社会结构。**在哥伦布最后一次出发之前，他**#在加勒比地区引入了"委托监护制"（encomienda system），这个制度传播到了西班牙在美洲的各个定居点。#** +

在这个制度中，被称为委托监护主（encomenderos）的主要人物被授予一部分土地。生活在这片土地上的所有原住民都成为了无偿的劳动力，从事农业或采矿工作。这是一个残酷的制度，并且以宗教为理由来为其辩护。 +

记住，西班牙探索的动机之一是传播基督教。那么这个制度是如何运作的呢？嗯，费迪南德和伊莎贝拉**发布了一份名为《要求书》（Requerimiento）的法律文件，为"委托监护制"奠定了基础。** +

*#在这份文件中，教皇授予西班牙君主"宣称土地"和"传教"的权力。因此，牧师得到了王室的保护。如果原住民服从这个制度，他们也会得到保护。否则，他们就会失去王室的保护，可能会被征服或杀害。#* +

你知道，就像耶稣会做的那样（这里是反讽）。 +

现在，我们需要谈谈非洲奴隶贸易，它与"委托监护制"有关。在这个制度下，美洲的原住民在西班牙的种植园里被迫劳动。 +

*#当在美洲建立殖民地时，殖民者首先做的事情之一, 就是寻找矿物财富(金银)。但很快就发现，由于温暖的气候——尤其是在加勒比地区、南美洲和北美洲——种植经济作物成为了更重要的财富来源。#* +

像糖、咖啡等曾经的奢侈品，变得更便宜，中产阶级也能消费得起，*因此对这些商品的需求激增。对劳动力的需求也随之增加。* +

但对西班牙人来说，这种安排**有两个问题。第一个问题是，因为原住民比西班牙人更了解这片土地，他们相对容易地逃离了恶劣的条件。** +

*第二个问题是，#原住民大量死于欧洲的疾病，这进一步加剧了对非洲奴隶劳动力的需求。#* +

*非洲人已经与欧洲接触了几千年，并且接触了他们的疾病，因此有一定的免疫力。而且他们不了解这片土地，不太可能逃跑。所以，非洲的强迫劳动, 逐渐取代了原住民的强迫劳动。* +

这些工人的生活非常艰苦。他们前往美洲的旅程始于 “中间航道”（Middle Passage）。**根据天气情况，横渡大西洋可能需要一到六个月的时间，**船上的条件惨无人道。 +

对奴隶贩子来说，他们在船上装载的货物(奴隶人数)越多，就能赚取更多的利润。所以非洲人营养不良，受到恶劣的对待，经常死于疾病。即使他们活着到达了新世界，等待他们的也是残酷的种植园奴隶制生活。 +

所以，是的，我们把这一点记在探索时代的严重罪行一栏里。 +

好的，现在我们在这个单元需要谈论的最后一件事, 是**"商业革命"**（Commercial Revolution）。我已经提到了**这个时期新的经济现实, 如何结束了"封建主义"，并开始用"资本主义"取代"重商主义"。** +

现在，*需要明确的是，"重商主义"在这个时期结束后的大约一个世纪里, 才完全消退，但它衰退的开始, 就在这个时期。* +

所以**"商业革命"描述的是这个时期"全球商业的大幅增长"，这改变了欧洲的经济面貌。**这场革命有几个因素。 +

**首先是银行业和金融业的变革，尤其是"货币经济"的兴起。这意味着商品、服务、工资和投资, 现在都用"现金"进行，而不是用黄金和白银。**这取代了人们种植或制造大部分资源的经济模式。 +

**结果，我们看到热那亚、阿姆斯特丹, 和伦敦等伟大的银行中心的崛起。**这里有几个你应该了解的经济创新。 +


首先是**"复式记账法"。这是一种详细记录所有借方和贷方的账本，为了使账户平衡，借方必须等于贷方。**听着，你不一定要理解这个系统是如何运作的，但**你应该知道，#对这样一个系统的需求表明, 这些银行中心处理着大量的资金。#**

其次，促进货币经济增长的创新,是"股份制公司"。*在##股份制公司##中，投资者购买公司利润的股份，从而筹集大量资金。所以你要明白，#在很多地方，这是一种"私营企业"，而不是国家驱动的重商主义企业。#*

一个很好的例子是**"荷兰东印度公司"，它成立于1602年，为亚洲的贸易提供资金。**

好的，我们也应该谈谈这一切是如何影响"社会等级制度"的。我刚才说, *这个时期的经济变革结束了封建制度，但这里我要稍微深入一下。*

*从宏观层面来说，这是真的，但当你把目光聚焦到当地社区时，封建制度的许多原则仍然存在。##在封建制度下，国王将土地授予贵族，##贵族耕种土地并进行保护。##贵族雇佣农民（也就是被束缚在土地上的农奴）劳作，##雇佣骑士进行保护。*

*##因此，生活在很大程度上以"庄园"为中心，庄园是贵族控制下的农业领地，##或者以季节、村庄为中心。这样，#"自给农业"在欧洲的大多数地方占据主导，这意味着一个家庭种植他们生存所需的东西。#*

*#为了生存，家庭必须种植许多不同的作物，这与美洲"种植园"盛行的经济作物系统不同，在美洲种植园,只种植单一作物用于市场出口。#*

**对于那些生活依赖土地的人来说，土壤耗竭是一个持续的威胁。**如果你不是农民，你可能不知道，但别担心，我来告诉你，*如果你年复一年在同一块土地上种植相同的作物，土壤中的养分最终会被耗尽。*

例如，为了简单起见，*假设某块土地含有养分A到F，再假设小麦生长需要A到C养分。如果你在一块土地上持续种植小麦，最终这块土地就没有A到C这些养分了，土地就会耗尽。*

这是个问题，因为，你知道，我们得吃饭。那么**#这个问题的解决方案是什么呢？作物轮作。#**

*在地中海欧洲，他们采用了所谓的##"两田制"。这意味着一半的土地,休耕一段时间以补充养分，而另一半土地,进行种植和收获。##*

*在北欧，他们发展出了"三田制"。他们把田地分成三个部分，秋季在其中两个部分,种植作物，春季在这两个部分种植不同的作物，然后第三部分在当年休耕。然后第二年进行轮作。*

*关键是，在种植季节，三分之二的土地是"生产性"的，而三分之一的土地"休耕",以补充养分。*

好的，商业革命是由价格革命引起的。*随着西班牙的黄金和白银流入欧洲经济(相当于印钞, 通货膨胀了. 因为实物生产数量, 没有跟着金银货币数量同比增长. 一个国家金银太多, 实物太少, 导致每个实物分摊到的金银数量上升, 物价就上升)，再加上货币流通量增加,和人口增长，所有这些导致食品和生活必需品的价格, 在很长一段时间内上涨。*

**#这种通货膨胀#,**促进了被称为"价格革命"的商业增长，这对农业的商业化至关重要。所以**##大地主和资本主义投资者##开始认为,**开放田地系统是浪费的，并**#希望增加可利用的土地，以提高作物产量 (一方面是物价高, 生产这些物资销售就有利可图. 另一方面是提高产量, 让"实物产出量"和"货币增加量"匹配, 就能将通货膨胀压下去)。#**

*#因此，例如在英国通过了一些立法，允许投资者购买公有土地。这些土地被称为"公地"，对农民来说这是至关重要的土地，因为这是他们可以放牧牲畜的唯一地方。#*

但是商业农民,*对土地的需求不断增加，导致了所谓的"圈地运动"。换句话说，以前可供所有人使用的土地(公共土地)被圈起来了，因此土地面积越来越小。*

毫不奇怪，*这场运动让大地主获得了巨额利润，但它极大地扰乱了农民的生活规范，导致贫困加剧。*

现在，我们将在下一单元更深入地探讨"圈地运动"的结果，但在这里你只要知道，*#它(圈地运动)导致大量无地的穷人迁移到城市寻找工作。这个现象被称为"城市化"。#*

然而，在某些情况下，贵族也搬到了城市，贵族和穷人的涌入, 引起了城市商人阶级的不满。住房问题尤其严重，但我们将在下一单元讨论这个问题。

好的，这就是第一单元的内容。你可以点击这里获取我的终极复习资料包，它将帮助你在课堂上取得好成绩，并在五月份的考试中获得5分。

如果这个视频对你有帮助，并且你希望我继续制作这样的视频，那么一定要点击订阅按钮，我会继续制作的。

海姆勒（Heimler）下线啦。

'''

== pure


All right, if you need a review of the whole dang first unit of AP Euro, then you are in the right place. So if you're ready to get them brain cows milked, let's get to it.

Now, the first thing we need to talk about is the Renaissance. And it's a word that means rebirth, and that means that something which has died has come back to life. So what died and what was being resurrected? Well, it was the classical texts and ideas from the Romans and the Greeks.

Now, throughout the Middle Ages -- which is to say before the Renaissance -- much of this teaching was forgotten by Europeans, at least those who didn't sit around a monk all day. But thanks to Islamic scholars who had translated the works of ancient Greece and Rome into Arabic and Latin, and thanks to the increasing contact Europeans had with Islamic people during the Crusades, Europeans started gaining access again to these ancient ideas. And the recovery of these texts and ideas essentially led to the Renaissance, which began in Italy, by the way.

If you want note guides for this video, you can check out my AP European History Ultimate Review Packet, which is linked in the description.

Now, the first major player in this regard was a guy named Petrarch. Although technically he preceded the Renaissance, it doesn't matter. Petrarch laid out a lot of the groundwork for Renaissance ideas, and his philosophy was called humanism. And this is important -- like, so important. Write it down, tattoo it on your forehead if you need to. Humanism was a philosophy that focused on the unlimited potential of human beings as an end in themselves.

In Petrarch's analysis, human beings were the bee's knees, as nobody says. There was unlimited potential in these fleshy little organisms. And so humanism, along with individualism -- which emphasizes the triumph of the individual -- would become the main mode of thought for much of the Renaissance.

Now, one of Petrarch's great discoveries was the writings of the Roman orator Cicero, whose magnificent Latin compositions Petrarch thought ought to be the model for the Latin language. In other words, Cicero's Latin. Noice. Anyway, Petrarch was especially moved by Cicero's eloquent support of the Roman Republic -- not the empire, the republic. That's important. And Petrarch was further moved by Cicero's opposition to the tyrannical Julius Caesar's usurpation of power. Those are themes that will become very important throughout the Renaissance.

Now, also during the Renaissance, we saw the development of new philological approaches to texts. Philological? Now, philology is the study of the history and development of languages. And maybe that sounds about as interesting to you as painting a wall two shades of gray and watching it to see which dries first. But in the Renaissance, new philological methods were kind of a big deal.

Case in point: Lorenzo Valla made philological headlines in 1440 when he demonstrated that an authoritative document of the Roman Catholic Church was a forgery. No? Oh yes. It was supposedly written by the Roman Emperor Constantine in the 4th century, but Valla demonstrated that the structure of the Latin in Constantine's document did not conform to 4th-century Latin standards. Therefore, not authoritative. Throw it out.

And that's a good illustration of a major theme of the Renaissance, namely the move away from religious authority to secular authority. To be fair, many Renaissance thinkers were still Christians, but the movement in general was away from the revealed authority of the Bible and the dogmas of the church to more scientific modes of inquiry.

And another important shift in thought was from the communal understandings of humanity to individualistic conceptions of humanity. All these new ideas were largely confined to a handful of elite folks in the beginning. But in the 1440s, with the invention of the movable-type printing press, the ideas spread widely and with great speed -- so much so that these ideas started challenging the institutional power of universities and other centers of power.

Now, more on the printing press later, but for now, let's see how this worked out in education.

Now, scholars in the Middle Ages were primarily concerned about theological questions. But with the growing interest in classical texts and the establishment of humanistic reasoning during the Renaissance, education underwent a massive transformation. And Renaissance scholars introduced the humanities into the curriculum, which emphasized history, moral philosophy, poetry, etc. -- all of it based on classical texts.

And as humanists, this emphasis on the humanities was intended to expand the humanity and unlimited potential of the human being. Because, you know, humanism.

Now, one of the key thinkers in this regard was Baldassare Castiglione, whose book *The Courtier* was a guide for how an educated young man should behave in courtly society -- namely, to be a gentleman. He argued that a gentleman should be skilled in all the humanistic disciplines, like write and speak with eloquence, be physically strong, and most of all, mentally awake.

Now, these new ideas also affected civic and political institutions, beginning with the Italian city-states. Now, remember, during this time, Italy wasn't a unified country like we know of today. Rather, it was a bunch of regional kingdoms and self-governing communities.

When these humanistic ideas worked their way into politics and civics, the result was called civic humanism, which was basically the idea that educated men should be active and engaged in local politics. And I reckon we ought to talk about a couple of examples.

First, Leonardo Bruni. He argued that the republicanism of ancient Rome was the best form of government and that rule by an enlightened individual was best. Now, this was a massive shift from the feudalistic government structure of the Middle Ages.

Second, you got our boy Niccolò Machiavelli. He wrote a little book called *The Prince*, in which he argued that the basic function of a ruler is to maintain power at all costs. Thus, a prince ought to behave in whatever way helps him to fulfill those ends. If benevolence helps him reach those ends, then be benevolent. If being a tyrannical turret helps you reach those ends, then be a tyrannical turret.

However, Machiavelli argued that there is a limit to the Turkish tyranny. The prince must strike an enlightened balance. You must use whatever means necessary to establish order and security, but do not act in such ways to make your people hate you. Or, to put it in Machiavelli's own words: "It is much safer for the prince to be feared than loved, but he ought to avoid making himself hated."

But at the end of the day, Machiavelli argued that a ruler should maintain power, even if it meant making selfish decisions that disregard ethical and moral beliefs. And that was a huge departure from the Middle Ages, when the character of a European ruler was defined by biblical virtues like prudence and wisdom.

Okay, now let's turn the corner. We can't talk about the Renaissance without talking about the new birth of art as well. If you already know anything about the Renaissance, it's probably the art.

Now, artists in the Middle Ages portrayed almost exclusively religious themes, rich with symbolism, but they were flat and didn't really conform to reality. Renaissance artists, on the other hand, emphasized naturalism, which was more realistic, portraying the world as it was and not in the mysteries of symbolic figures.

Now, Italian Renaissance artists leaned more on the idealistic side of naturalism, while Northern Renaissance artists -- on whom more in a moment -- employed naturalism to depict the scenes of everyday life. There were also masters of new techniques in geometric perspective, by which artists sought to add depth and realism to their paintings.

Now, Renaissance artists did continue to portray religious themes in their work, but they also took up personal and political and classical themes as well. You're going to need to know a couple of these artists, so let's meet them.

First is Michelangelo. Here you can see a sculpture of the biblical figure David. And notice the humanist philosophy coming through. This is the perfect specimen of a human man, but sculpted in the image of a Greek god. So additionally, notice the detail of David's musculature and the features of his face. This is the naturalism and the idealism of Renaissance art.

Second, let's meet Raphael. Here you can see one of his most famous paintings, *The School of Athens*. It's an example of a Renaissance artist taking up classical themes, which were at the heart of the Renaissance. In the middle, you've got the classical heroes Plato and Aristotle. And also notice the way he uses geometric perspective to make his structure feel real.

And third, let's look at some architecture. And for that, let me introduce you to Filippo Brunelleschi. He was the architect on the rebuilding of the church of San Lorenzo in Florence. Notice how he tossed out the Gothic conventions of medieval cathedrals and built the church with Roman columns and arches.

His most famous work was the dome on the Florence Cathedral. Now, it may not look like much to you, but this was a genius feat of engineering, since the flying buttresses of medieval cathedrals were so Middle Ages. Brunelleschi built this dome to stand on its own without any outside support.

Now, the last thing you should know about Renaissance art is this: Most of these artists were patronized by wealthy individuals and rulers and popes. Was that because those folks just loved the arts and wanted to see beautiful works of human genius born into the world? Uh, no. These leaders patronized the arts in order to enhance their public prestige. "Hey, you like that new Michelangelo? I paid for that."

And the most notable of these patrons was the Medici family -- on whom more later.

Okay, so as I said, the Renaissance started in Italy, but it soon spread to other parts of Europe as well. With the help of the printing press, the ideas of the Italian Renaissance spread to the rest of Europe north of the Italian Alps. And when it took root, we call that the Northern Renaissance.

However, as the ideas spread northward, the main foundation of humanism and the revival of the classics stayed the same, but some of the emphases changed. And the main change was that it developed a more religious -- which is to say, Christian -- focus than the more secular Italian Renaissance.

So as the Renaissance spread to the Low Countries and France and Germany and England, people took pains to synthesize humanism with Christian ideas. And the result was Christian humanism. What they aimed to do was combine the best elements of humanist thought with scriptural authority. And that led to a heavy emphasis on social reform.

And the name I want you to associate with Christian humanism is Desiderius Erasmus. Now, Erasmus believed that education in the classics and the Bible is the foundation of true societal reform and that renewal should be based on the philosophy of Christ.

The work you should know from Erasmus is called *In Praise of Folly*. It was a satire that sought to undermine corrupt political and social institutions and criticize the corrupt aspects of religious hierarchies as well.

Now, the Italian Renaissance had their artists, and so did the Northern Renaissance. However, Northern Renaissance artists retained a more religious, Christian focus than the more secular Italian Renaissance artists did. Their art was still naturalistic, but it was more human-centered and considered everyday objects and people more appropriate for objects of art, as opposed to Italian artists, whose lofty subjects were sometimes otherworldly.

For example, let's talk about Pieter Bruegel the Elder of the Dutch and Flemish Renaissance. Here's his painting titled *The Peasant Wedding*. You know, the subject matter here isn't something massive like the six days of creation, but instead, you see ordinary people in celebration of a wedding, eating normal food. But still, you can see the emphasis on naturalism. The features of the people look real.

Okay, and then there's Rembrandt of the Dutch Renaissance. And oh, his work is tasty. He was famous for his ability to paint light and shade, as you can see here in his work titled *The Return of the Prodigal Son*. It's a scene from a parable of Jesus, and you can almost sense the deep emotion in the painting. For Rembrandt, it was very important to him not merely to reproduce a picture but to inhabit the narrative of scripture as he did so.

Okay, so that was the Northern Renaissance.

Now, I've mentioned already the role that printing had in the spread of Renaissance and humanist ideas, but now we need to consider that head-on. The printing press was a massive deal. Like, I cannot emphasize enough. It is impossible to overemphasize the role that printing played in this period of history.

Now, before the printing press, important books were copied by hand. And if you've ever been on Spaceship Earth at Epcot, you know this. This process was laborious and very expensive. And that meant that there weren't many books available, and what books were available were either kept by churches or in the libraries of the wealthy who could afford to have their own copies.

Not to mention, most of the books were written in Latin, which meant that only priests and monks could read them. Anyway, but all that changed in the 1440s when several German metalsmiths developed the technology of the printing press, which allowed printed works to be copied and published at a speed and volume previously unthinkable.

And the smith most associated with this technology was Johannes Gutenberg. The printing press was able to produce books quickly and cheaply because of a new innovation called movable type, in which metal letters were slid into rows, blotted with ink, and pressed upon a piece of paper.

Thanks to Chinese paper-making technology that had spread into Europe, the abundance of paper made mass printing a feasible reality. Now, Gutenberg's first major work published on the press was the Gutenberg Bible in 1456. And then, within 50 years, a metric buttload of books were published all throughout Europe -- somewhere between 10 and 20 million books.

So with this new technology, ideas written in books and pamphlets could spread rapidly. And that is exactly what happened. By 1515, all the major classical authors -- like Plato and Aristotle and Pliny, etc. -- were all in print and spreading rapidly.

The printing press also played a massive role in the Protestant Reformation. Martin Luther, who claimed that the Catholic Church had devolved into heresies and corrupt practice, was able to spread his ideas far and wide thanks to movable type and deal a serious blow to the church hierarchy.

But we're going to talk a lot more about the Protestant Reformation in the next unit, so we'll leave it there for now.

And the press also created demand for vernacular literature, which is literature written not in Latin but in the language of the common people -- whether it be English or Spanish or French. And when books were printed in a people's native language and they began reading them together, it created the occasion for the development of national cultures to emerge.

For example, during the Protestant Reformation, Martin Luther produced a vernacular Bible in German, which is kind of a big deal because prior to this, people only heard the Bible in Latin. But in doing so, Luther created a standard for the German language, which fundamentally shaped their national culture.

Okay, I reckon we ought to talk about some politics. This period saw some pretty significant developments in how kings exercised and consolidated their power.

Now, back in the Middle Ages, kings didn't have as much power as you might think. You know how when you watch a movie set in medieval times, and the king is all-powerful and like telling everybody what to do? Yeah, that's not how it actually was. It was the nobles that held much of the power.

But during this period, they were considering monarchs and princes started taking power from the nobility and organizing it squarely under themselves. And one of the results of that shift was top-down religious and moral reform.

So in light of that, I reckon I ought to introduce you to Henry VIII of England. He actually opposed the new religious developments of the Protestant Reformation against the Catholic Church. In fact, he pooh-poohed the Reformation so hard that the pope named Henry "Defender of the Faith."

But then Henry started having a little trouble with the Catholics. His wife of 20 years failed to produce a male heir, and so he did what any self-respecting, self-sacrificial Christian man would do: he asked the pope for an annulment. Classy guy.

But it just so happened that she was the daughter of Ferdinand and Isabella of Catholic Spain, and they put the pressure on the pope to deny Henry the annulment. And they were successful. But then Henry's mistress, Anne Boleyn, became pregnant, and so Henry went ahead and divorced his wife and married Anne.

The pope, unsurprisingly, declared the marriage illegal, so Henry denounced the pope, and the Parliament passed a law making Henry the head of the newly formed Church of England, which was patently not under the authority of Rome.

Now, many English people remained committed Catholics, but remember, we're talking about top-down religious reform here. To that end, Henry got the Treason Act passed, which made it punishable by death to refuse to recognize the Church of England as the state religion.

Okay, now let me tell you about a descendant of Henry, namely Elizabeth the First. She rose to the throne after Henry's daughter, Mary Tudor's reign. Now, Mary attempted to restore Catholicism to England and earned the nickname "Bloody Mary" for hacking to death any Anglican bishop that opposed her.

Anyway, Elizabeth steered England back to Anglicanism and ended the persecution of the dissenters. And again, she did this from the top down. She had the Act of Uniformity passed, which mandated that English subjects had to attend an Anglican church -- and that's just another name for the Church of England -- and they had to do that once a week or be fined.

Okay, so that's how a couple of these new monarchs engaged in top-down religious and moral reform.

Now, let's look at how a few other of these new monarchs laid the foundation for the modern state by doing a few things, namely: establishing monopolies on tax collection, employing military force and dispensing justice, and gaining the right to determine the religion of their subjects.

Let's start in Spain with Ferdinand and Isabella. Ferdinand was from the Spanish region of Aragon, which was powerful and well-organized. Isabella was from the region of Castile, which was kind of a hot mess. Their marriage began the process of the unification of Spain and the consolidation of monarchical power.

So what did they do with all that power? Well, they raised revenue through a series of national taxes on the sale and exchange of property. They established an elaborate bureaucracy that collected taxes and decided questions of justice in the name of the monarchs.

And they went ahead and completed what was called the Reconquista, by which they drove out Muslims and Jews from the Iberian Peninsula and established Catholicism as the official religion of Spain.

Alright, let's see how this played out over in France. Their monarchs used similar methods of consolidating power, namely national taxes and a complex bureaucracy. Now, France was also a Catholic country, and to that end, you should know the Concordat of Bologna in 1516.

This is an agreement between King Francis the First and Pope Leo the Tenth, by which two things happened: the pope got the right to collect income from the French Catholic Church, and Francis retained the right to appoint French Catholic Church leaders, thus restricting their right to communicate with the pope directly.

What does all that mean? More power for the king.

Now, these new monarchs also began to claim the right to determine the religion of their subjects. The Peace of Augsburg in 1555 gave individual leaders in the Holy Roman Empire the right to decide whether their subjects would be Catholic or Lutheran.

And this wasn't, of course, just a religious decision on the part of the Habsburg rulers. The power to choose the religion of their subjects was also a means of consolidating power. After all, if a monarch's people -- or even just a minority of them -- believed contrary doctrines to their monarch, that could weaken their sway over the people.

Now, I would be a liar if I told you that it was only monarchs who were gaining power during this period. Commercial and professional groups gained power as well and played a greater role in political affairs. Chief among these groups were merchants and bankers, especially in the Italian and German states.

And I know your heart is crying out for a couple of examples here, so far be it for me to deny your deep desires. The Medici family basically established the banking industry in Italy, and the Fugger family basically did the same in Augsburg, Germany.

And the result of these folks building a tremendous amount of boom-boom in their vaults was this: with the rise of the money economy and a close alliance of these groups with the monarch, it allowed them to exercise increased political power in their respective areas of influence.

Now, another major theme of this time period is European exploration. Europeans were no longer content to remain on their entire continent, so some of them started shoving out into ships to find other places to live and trade.

Now, first, we probably ought to talk about why Europeans went out exploring, and for that, I've got three words for you: gold, God, and glory. And let's look at each of those in turn.

Now, Europeans were first motivated to start their maritime exploration because of God. We've already established that during this period, Europeans could be pretty spicy about the religion of their people, so why not crank up the spice and go find other people to convert?

Case in point: Spain. They, of course, wanted to spread Catholicism as far as they could. As I already mentioned, by 1492, they had completed the Reconquista and driven Jews and Muslims from their land. And by the time of the Protestant Reformation, there was a desire to see Catholicism in the ascended position over Protestantism.

As they found their way to the New World, they sent Jesuit missionaries to convert the indigenous people. However, many Europeans thought of the indigenous people as lesser humans and thus suitable for forced labor. In that way, Christianity became an instrument for control and subjugation.

However, I must hasten to add that not all Spaniards saw indigenous Americans that way. For example, the Spanish priest Bartolomé de las Casas worked to establish a Catholic presence in the Americas and also fought for the dignity of the peoples in the Americas.

Okay, now the second motivation for exploration was gold. And for this, I need to introduce you to mercantilism, which was the dominant economic system of Europe during this period.

The main thing you need to understand about mercantilism is that it's a system that argued that there was only a finite amount of wealth in the world and that wealth could be measured in gold and silver. And you know, if that's how you measure wealth, then yeah, there's only a finite amount of gold and silver in the world.

And so a mercantilist nation wanted to get as much gold and silver as they could, which is to say, the country with the most gold wins. To that end, mercantilism demanded what was called a favorable balance of trade, which essentially means that a country needed more exports than imports.

When you think about it, that's easy to understand why. If a country is exporting goods, that means gold and silver is coming in. And if they are importing goods from other countries, that means their gold and silver are going out. Remember, the state with the most gold wins, so that's why they wanted less imports and more exports.

On a related note, under the mercantilist mindset, the establishment of colonies was almost a necessity because those far-off lands could provide the motherland not only with more mineral wealth like gold and silver but with raw materials to be used in manufacturing goods for sale, which would then bring in more gold.

You smelling what I'm stepping in here?

Okay, let me give you an example of how mercantilism motivated exploration and the policies of France's Controller General, Jean-Baptiste Colbert. Colbert believed, like any good mercantilist, that a country's wealth should serve the state.

In order to create a favorable balance of trade, Colbert proposed policies mandating French industry to create everything the people needed so that they didn't have to import goods. Furthermore, Colbert aimed to claim as much of North America as possible, and the major accomplishments on that front were Quebec and the Louisiana Territory in North America.

Now, one more thing under this heading: Europeans were motivated to explore because of the increasing demand for luxury goods from Asia. But they had a problem: the Muslim Ottoman Empire controlled all the land routes between Europe and Asia, and therefore, Europeans had to pay even more exorbitant prices for those goods.

So what do we do? Well, why don't we put some ships in the shark's house and see what happens?

Okay, now the third motivation for exploration was glory. Once the colony game was started, it created a bitter rivalry among European powers to grab as many colonial possessions as possible. Like, if colonial possession is going to be the path to dominance, then each regional power sought to win such a game.

Okay, so those were the major motivations for exploration. Now, let's take a moment to consider the new and repurposed navigational technology that enabled them to go exploring.

First, there were advances in cartography, which is to say, map-making. These maps were more detailed, and printing made them widely accessible across the continent.

Second, we saw new kinds of ships. For example, we saw the Spanish and Portuguese developed the caravel, which was fast and highly navigable. And one of the chief reasons it was fast was because of the lateen sail, which could take wind from any side, as opposed to square sails, which could only take wind from behind.

They also made use of the compass, which helped establish direction, and the astrolabe, which gave an accurate reckoning of latitude from Chinese and Muslim navigators.

You probably like, "Lateen sail? Astrolabe? Who cares?" But trust me when I tell you, these were massive innovations. Like, if Steve Jobs lived 500 years ago, he would come out on stage in a mock turtleneck saying, "This is the most triangular sail we have ever made." Then everyone would give a standing ovation and lose their minds. "Look how triangular it is!"

So these technologies? Big deal.

Now, as I mentioned, this new wave of exploration caused a pretty significant rivalry to erupt among European nations. So let's talk first about colonial empires themselves and second, how those empires affected relationships between those powers.

And since they were first on the exploration scene, let's start with Portugal. They were the first Europeans to actively seek a sea route to Asia, and they did this by sailing around Africa.

As they made their way around the African coast, the Portuguese didn't take large colonial holdings, which were costly to establish and maintain, but instead established trading posts all around the coast, which is why their empire is known as a trading post empire.

Eventually, they made their way all the way into the Indian Ocean, where, over time, they dominated trade all the way to Southeast Asia.

Next, we have Spain, whose monarchs Ferdinand and Isabella commissioned an Italian sailor named Christopher Columbus to find a sea route to Asia as well. But instead of sailing around Africa, Columbus decided to sail west across the Atlantic Ocean to connect them with the Asian spice trade.

And as you probably know, there were a couple of giant continents that got in his way that no one in Europe knew about. So Columbus landed in the Bahamas and eventually claimed much of the Caribbean and Central America, North America, and the coastline of South America for Spain.

And look, as men were able to gain so much territory largely because of the deadly diseases like smallpox and measles that they brought with them -- on which more in a moment.

And then France jumped into the exploration party. They ended up claiming large parts of North America and Canada. Mainly, they were interested in trading, especially in fur. Therefore, they didn't establish many proper colonial settlements.

And let's not forget about England. They sailed west and claimed parts of Canada, the Caribbean, and the eastern coast of North America. And the English built settler colonies, which is to say, people went there to make a new life, to build homes, and not just trade.

The Netherlands forced their way into the party as well. The Dutch were mainly interested in trade, and to that end, established a few colonies in the Americas but focused mainly on dominating trade in Southeast Asia.

Now, how did this scramble for colonies affect the relationships between these European powers? Well, it got nasty. And when the tension arose, there were basically two ways that they could settle it.

First was diplomacy and negotiation. For example, Spain and Portugal entered an agreement called the Treaty of Tordesillas in 1494. It was mediated by Pope Alexander VI, and both parties agreed to divide the Americas by this line of demarcation: Spain got everything to the left, Portugal everything to the right. Hey, that's nice.

But the second way the nations handled rivalry was a little more saucy, namely coercion and war. Since the Treaty of Tordesillas essentially divided the world in half in terms of colonial territories, that would lead to some armed conflict later.

Since all of North America fell squarely in the Spanish half of the world, that is going to lead to rivalry in the next period between Spain and England, who wanted to claim some of those tasty colonies.

Eventually, in the next period, France, Spain, and England -- along with some other states -- are going to fight the War of Spanish Succession over colonial possessions in the New World. But we'll save that story for when we get there.

What you really need to remember about these growing tensions and rivalries is this: at stake for all the European nations was the balance of power. Nobody wanted any one European power to have all the cake -- or even most of the cake. As long as everyone was equally powerful, roughly speaking, all was well.

Okay, now with all this contact between the Old World -- which is to say, Europe -- and the New World -- the Americas -- something massively important happened, namely the Columbian Exchange.

By definition, the Columbian Exchange was the global exchange of goods, flora, fauna, cultural practices, and disease between the Old World and the New World. So as Europeans established colonies and trading ports in the Americas and Africa, the great exchange occurred. And when it did, it transformed the society, economy, and environment on all three continents.

So let's talk about five major exchanges that occurred.

First, disease. The Spanish got real thirsty for colonial holdings in the Americas, and when they got their hands on these lands and peoples, they sought to remake the Americas into their own image. But their ships only held a few hundred sailors at best, so how did they conquer so many people? Mainly by disease -- and more specifically, smallpox.

You have to understand that Africans, Europeans, and Asians had all been in contact with one another for millennia and therefore had been exposed to each other's nasty germs and had therefore built up some immunity.

The indigenous peoples of the Americas, though, had been completely isolated from such germs and therefore had no immunity. So, for example, when the Spanish landed on the island of Hispaniola, both the Arawak and the Taino populations were devastated to the tune of about 300,000 dead by smallpox.

Spanish conquistador Hernán Cortés defeated the massive Aztec empire with relatively few men -- again, because of the introduction of smallpox and measles. So, Hernán, chill your fluffy collar out. You're not that great.

Second, food was exchanged. You should probably know a couple examples. Food that travels from the Americas to Europe included high-yielding and nutrient-packed foods like maize, tomatoes, potatoes, and cacao.

Food that traveled from Europe and Africa to the Americas included rice, wheat, soybeans, rye, oats, lemons, oranges. And it was especially those grain crops that transformed the American population because they diversified their diet and led, in many cases, to longer lifespans.

Third, animals were transferred too. Europeans introduced horses, pigs, chickens, and cattle to the Americas. Pigs and cattle transformed the diet of Native Americans. Horses revolutionized farming and warfare. And chickens made it possible for our nation to later indulge in giant buckets of KFC.

Oh man, I got the chicken sweats. Thanks, Columbian Exchange.

Fourth, minerals were exchanged. And here, I'm really talking about gold and silver. After the Incan and Aztec empires were conquered, Europeans plundered their lands for vast quantities of gold and silver. And that made Spain wealthy beyond belief.

If it weren't for this wealth, it's likely that European colonizers would not have kept returning. But as the old conquistador saying goes, "As long as there's boom-boom, we go vroom-vroom." That's a rough translation.

Anyway, not only did this wealth transform the Americas by attracting large amounts of European colonizers, but it transformed Europe as well. Starting a little after 1500, Europe -- and more to the point, Western Europe -- experienced unprecedented economic growth.

The social, political, and economic system previous to this period was feudalism, and that was a system where peasants lived and worked on the land of a noble in exchange for armed protection. But this influx of wealth hastened the end of that system.

And what replaced it? Well, an early form of capitalism, which was an economic system based on private ownership and free, open exchange of goods between property owners.

And the fifth kind of transfer during the Columbian Exchange was people. The chief thing to know here is the African slave trade, by which millions of Africans were forcibly removed from their land and shipped across the Atlantic in order to work the plantations of European colonies.

We'll talk about that more in a moment, so just take that, stick it in your pocket, and we will come back.

For now, let's finish this section by talking about how the Columbian Exchange impacted Europe.

First of all, the influx of mineral wealth and the establishment of trading empires shifted the center of economic power in Europe from the Mediterranean to the Atlantic states and brought them squarely into the global economy.

Previously, Mediterranean seaports like Venice were the center of economic power and trade, but not anymore. During the globalization of the economy and exploration, one of the primary trading ports became Antwerp in the Netherlands, which grew exceedingly prosperous due to its central location to Spanish, Portuguese, French, and English trading routes.

Over time, Amsterdam grew to ascendancy as the major trading port of Europe, replacing Antwerp. Then others followed, like London and Bristol. But the point is, whereas economic power used to be concentrated here during the Age of Exploration, it was now concentrated here.

The second impact concerns the subjugation of people. The Spanish created a completely new societal structure in the Americas. Before Columbus left for the last time, he introduced the encomienda system in the Caribbean, which spread throughout the Spanish settlements in the Americas.

It was a system in which leading men -- called encomenderos -- were granted a portion of land. All the natives who lived on that land became the unpaid laborers who did the farming or the mining. It was a brutal system that was justified on religious grounds.

Remember, one of the motivations for Spanish exploration was the spread of Christianity. So how did this work out? Well, Ferdinand and Isabella issued a legal document called the Requerimiento, which established the basis for the encomienda system.

And in it, the pope granted the Spanish monarchs authority to claim lands and proselytize. Therefore, priests had the protection of the crown. If natives submitted to this system, they were granted protection. Also, if not, they forfeited the protection of the crown and could be subjugated or killed.

You know, just like Jesus would have done.

Now, we need to talk about the African slave trade, and it's connected to the encomienda system. And under that system, the natives of America were subjected to forced labor on Spanish plantations.

When colonies were established in the Americas, one of the first things colonizers did was begin looking for mineral wealth. But it soon became apparent that with the warm climate -- especially in the Caribbean and South America and North America -- that planting would be a much more prominent source of wealth.

Goods like sugar, coffee, etc., which were once luxury items, became cheaper and more accessible to the middle class, and therefore, demand for these goods spiked. And so too did the demand for labor.

But there were two problems with this arrangement according to the Spanish. The first is that because the natives knew the land better than the Spanish did, they were able to escape the harsh conditions relatively easily.

Second, the natives were rude enough to keep dying in large numbers from European diseases. Therefore, this, in turn, caused a spike in demand for enslaved African labor in the Americas.

Africans had been in contact with Europe and their diseases for millennia and thus had some degree of immunity. Also, they didn't know the land and were less likely to escape. And so was that forced African labor gradually replaced forced indigenous labor.

And the life of these workers was harsh and very difficult. Their journey to the Americas began on the Middle Passage. Depending on the weather, it could take something like one to six months to cross the Atlantic, and the conditions on board the ships were inhuman.

To the slave traders, the more goods they could pack onto a ship, the more profit they stood to earn. So Africans were malnourished, treated shamefully, frequently died of disease. And if they even made it alive to the New World, a life of brutal plantation slavery awaited them.

So yeah, we mark this one in the column of egregious sins of the Age of Exploration.

Okay, now the last thing we need to talk about in this unit is the Commercial Revolution. I already mentioned how the new economic realities during this period brought feudalism to an end and started to replace mercantilism with capitalism.

Now, to be clear, mercantilism wouldn't fully recede for another century or so after this period ends, but the beginnings of that recession are here.

So the Commercial Revolution describes the great increase in global commerce during this period that changed the face of economics in Europe. And there were a few ingredients in this revolution.

First were changes in banking and finance and especially the rise of the money economy. This means that goods, services, wages, and investments were now made with cash instead of gold and silver. This replaced the economy in which people grew or made most of their resources.

As a result, we saw the rise of great banking centers in Genoa, Amsterdam, and London. And there are a couple of economic innovations here that you should know about.

First, double-entry bookkeeping. This was a detailed ledger kept of all debits and credits, and in order for an account to be balanced, debits had to be equal to credits. And look, you don't necessarily need to understand how this system worked, but you should know that the need for such a system like this indicated that metric buttloads of money were being handled in these banking centers.

A second innovation that promoted the growth of the money economy was the joint-stock company, in which investors bought stock in a company's profits, raising large amounts of capital. So you need to understand that this was, in many places, a private enterprise as opposed to a state-driven mercantilist enterprise.

A good example is the Dutch East India Company, formed in 1602 to finance trade in Asia.

Okay, we should also talk about how all this affected social hierarchies. Now, I said just a little earlier that the economic changes during this period brought this system of feudalism to an end, but here's where I complicate that a little.

On a grand scale, that's true, but when you zoom in and focus on local communities, many of the tenets of feudalism still remained. This was the system in which a king granted land to nobles who farmed the land and protected it. Nobles employed the peasantry -- which is to say, serfs bound to the land -- to work the land and knights to protect it.

Therefore, life was largely oriented around the manor, which was the agricultural estate under noble's control, or the seasons, or the village. In that way, subsistence agriculture was the rule in most places in Europe, and that just means a family grew what they needed to subsist or survive.

And to survive, families had to plant lots of different crops, as opposed to the cash crop system that prevailed on the plantations in the Americas, where they only grew a single crop for export on the market.

And for those whose lives depended on the land, soil exhaustion was a constant threat. If you're not a farmer, you probably won't know, but don't worry, I'm about to tell you that if you plant the same crops in the same soil year after year, the nutrients in that soil will eventually be leached dry.

So for example, let's say for simplicity that a particular plot of soil has nutrients A through F within it, and let's further suppose that wheat needs A through C to grow well. If you keep planting wheat in a field, eventually there will be no more A through C nutrients in that soil, and it will be exhausted.

That's a problem because, you know, we got to eat. So the solution to this problem? Crop rotation.

In Mediterranean Europe, they employed what was called the two-field system. That means that half of the land lay fallow for a period of time in order to replenish the nutrients while the other half was planted and harvested.

In Northern Europe, they developed the three-field system. They divided their fields into three sections, and crops were planted in one and two in the fall, and then different crops planted in one and two in the spring, and then section three was left fallow that year. Then the next year, rotate.

The point is, two-thirds of the land was productive during planting season while one-third was left fallow to replenish its nutrients.

Okay, now the Commercial Revolution was caused by the Price Revolution. With the influx of Spanish silver and gold to the European economy, along with greater circulation of money and population growth, all this caused the prices of food and necessities to rise over an extended period of time.

This inflation contributed to the growth of commerce known as the Price Revolution, and this was critical in the commercialization of agriculture. So large landowners and capitalist investors began to see the open-field system as wasteful and desired to increase available land so that crop yields would increase.

Therefore, legislation was passed in England, for example, that allowed investors to purchase public land. This land was known as the commons, and it was a critical piece of land for the peasantry because it was the only place they could bring their livestock to graze.

But this increasing need for land by commercial farmers led to what's called the enclosure movement. In other words, the land that was previously available to all was being enclosed and therefore shrinking smaller and smaller.

Not surprisingly, this movement benefited large landowners with stupid amounts of profits, but it very much disrupted norms and life for the peasantry and therefore led to increased poverty.

Now, the results of the enclosure movement we're going to consider more in the next unit, but here it's enough to know that it caused a massive migration movement of the landless poor into cities to look for work. And the word for that is urbanization.

However, nobles also moved into the cities in some cases, and the influx of both led to the resentment of the urban merchant classes. And the problem of housing was particularly acute, but we'll pick that up in the next unit.

Okay, that's Unit 1. You can click right here to grab my Ultimate Review Packet, which is going to help you get an A in your class and a 5 on your exam in May.

If this video helped you and you want me to keep making them, then by all means, click the subscribe button, and I shall oblige.

Heimler out.


'''