
= 5.5 - REACTIONS to the FRENCH REVOLUTION
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

So with an event as monumental 极重要的；意义深远的 as the French Revolution, which we talked about in the last video, you bet your sweet bippy （非正式，用于强调肯定）there was going to be some strong reactions to it across Europe and the world. And that is what we're going to talk about in this video. So if you're ready to get them brain cows milked, let's get to it. +

So there were two main reactions that you need to know, and the first was the conservative 保守的；守旧的 reaction against the French Revolution in Europe and elsewhere. I mean, for a lot of the Enlightenment-style 启蒙运动风格的 intellectuals 知识分子, the calls for liberty 自由 in France and the overturning 推翻 of aristocratic 贵族的 privilege 特权 was a good and right thing. But as the revolution grew more radical 激进的 and people started getting their heads cut off by the metric butt-loads （非正式，大量地）, some of these thinkers like Thomas Jefferson over in America decided that things had gone too far. +

And there was, of course, dissent 异议；反对 from within France as well. Joseph de Maistre was a big critic 批评者 of the Enlightenment, especially its emphasis 强调 on the right of the people to govern 统治；管理 themselves. Maistre was a monarchy 君主制 man through and through 完全地；彻头彻尾地, and he justified 证明…有理；为…辩护 that belief on the grounds of 以…为理由 the divine right of kings 君权神授. By his reckoning 估计；推断, the chaos 混乱 and the violence 暴力 of the French Revolution was proof 证据 of the damage Enlightenment thought could do. +

And so Maistre advocated 提倡；主张 endlessly for a return to the divinely ordained 神命定的 monarchy in France. This is one of the few conservative critics under the new regime 政权 in France that did not get himself a play date with a guillotine 断头台, because he ended up fleeing 逃离 France and hurling 猛烈抨击 his commentary 评论 from afar 从远处. +

And from outside of France, the best-known conservative reaction against the French Revolution was from the English writer Edmund Burke. Now, while many European nations first praised 赞扬 the revolution because at least it was weakening their political rivals 对手, some saw the democratizing 民主化 of France as a threat 威胁. +

There was a strong fear from other nations that their people would be inspired by these new ideas established in the French Revolution and seek 寻求 them in their own state. In England, conservative Edmund Burke wrote Reflections on the Revolution in France, in which he cautioned 告诫；警告 the British people against the excesses 过度；无节制 of the French Revolution. And he even wrote this before the Reign of Terror 恐怖统治 began. +

He defended 捍卫 hereditary 世袭的 privileges and waxed eloquent about 滔滔不绝地谈论 Britain's unrepresentative 无代表性的 Parliament 议会 -- like he thought all of this was great. If the British people demanded what the French had secured 获得, Burke argued, the results would be chaos. Then the Reign of Terror broke out 爆发, and Burke was like, "I told y'all." +

Therefore, a radical overturning of established norms 惯例；规范 in England did not occur as it did in France. +

Now, that was the reaction to the French Revolution from the think-you-thinking conservatives. But across the globe, there was a more violent reaction in the Caribbean. +

By the beginning of the French Revolution, conditions in the French Caribbean -- specifically 具体地；确切地 Saint-Domingue -- were getting intense 紧张的；激烈的. The island was made up of 由…组成 several social groups, including French officials 官员, plantation owners 种植园主, merchants 商人, free people of color, and enslaved 被奴役的 African laborers 劳工. And this latter 后者的 group made up about 90 percent of the population 人口. +

To make things worse, the French government had granted 授予 various levels of rights to the different groups, and not surprisingly, the enslaved Africans were at the bottom of the pile 处于最底层 with almost no rights to speak of 值得一提的. But don't worry, France, I'm sure that's not going to cause any trouble. +

Anyway, the conditions for the enslaved laborers on the island were brutally 残忍地 vicious 恶劣的. In fact, the plantation owners on the island -- for whom coffee and sugar crops 作物 had made them exceedingly 极其地 wealthy 富有的 -- had figured out 弄清楚 that simply by working a slave to death and then buying new slaves, that was a more profitable 盈利的 system than treating them kindly. +

But it's okay, because once the French Revolution began, the National Assembly 国民议会 took over 接管. I'm sure that they're going to extend 扩大；延伸 the liberal 自由的 reforms 改革 made in France to all their colonies 殖民地 as well. Wouldn't that be hilarious 滑稽的；可笑的 if they did that? +

No. The National Assembly ended up passing a series of 一系列的 decrees 法令 and laws that alienated 使疏远 almost every group on the island. Especially angered were the enslaved workers, who heard the cries for "Liberty, Equality, and Fraternity" 自由、平等、博爱 in the streets of France and thought that those principles 原则 would extend to all places in the French Empire 帝国. +

But when the National Assembly refused to recognize 承认 the enslaved population's rights, the island was ripe for 时机成熟，准备好 revolution. +

So by 1791, the slaves on the island -- who had witnessed 目睹 the clashes 冲突 between whites and free people of color -- began meeting under the cover of night 趁夜色掩护 to plan a mass rebellion 大规模起义. In August, the rebellion broke out 爆发 and grew rapidly, and not long after, hundreds of coffee and sugar plantations 种植园 were destroyed. +

And remember, this was France's most profitable colony, so these rebels 造反者 weren't just destroying land -- they were actively 积极地 diminishing 减少 profits in France. And messing with 干扰；损害 money is the one thing you do not do in a large colonial empire like France. +

So as the rebellion went on, some complicating 使复杂化的 factors 因素 were introduced, and those complications 复杂情况 were named Spain and Britain. See, this half of the island was actually part of the Spanish Empire, and seeing the opportunity to weaken the French, they jumped at the opportunity 迫不及待地抓住机会 to support the slave rebellion. +

The British, also sensing 察觉；意识到 an opportunity in the chaos 混乱, blockaded 封锁 the island with their navy and then invaded 入侵 the land and took some territory 领土 for themselves. +

So because their most valuable colony was in danger from all sides, the National Assembly in France issued 发布 a decree that any slave who fought for the French cause would win their freedom. But the rebels looked at each other and were like, "Well, that's cute, but in case you haven't noticed, we already freed ourselves. So what else you got?" +

At which point, the National Assembly abolished 废除 slavery in all of its territory 领土. +

But the real tide of the war turned in favor of 转向有利于… the French with the rise of a brilliant 杰出的 soldier named Toussaint Louverture. He was born a slave on the island and then later freed, and at the beginning of the insurrection 起义, the Spanish recruited 招募 Louverture to fight for them against the French, which he did and easily proved his brilliance. +

But after several years of fighting, Louverture abandoned 抛弃 the Spanish and switched sides 改变立场 and led an army of four thousand against the Spanish and the British. By 1796, Louverture's efforts had resulted in 导致 France regaining 重新获得 control of their colony. +

So the National Assembly installed 任命 Louverture as the commander 指挥官 of the colony, and he defeated his rivals 对手 to the south to maintain 维持 control over all of Saint-Domingue. But he began making more and more decisions independently of 独立于 France, and by this time, Napoleon was in power 掌权, and that was not going to work for him. +

So Napoleon, wanting to regain 重新控制 control over Saint-Domingue, decided it was time to get Louverture out of power 下台 and re-establish 重新建立 slavery on the island. So a delegation 代表团 was sent to arrest 逮捕 Louverture, and he was deported 驱逐 back to France, where he died shortly thereafter 此后不久. +

But at the prospect of 面临…的前景 the return of slavery and French oppression 压迫, Louverture's lieutenant 副官, Jean-Jacques Dessalines, rallied 召集 the resistance 抵抗力量 and handily 轻易地 defeated the French and proclaimed 宣布 independence 独立 in 1804. They officially renamed 重新命名 their country Haiti, which had been its name before the arrival of the French. +

Okay, click here to keep reviewing for Unit 5 of AP Euro. If you need more help getting an A in your class and a five on your exam in May, then click right here and grab my AP Euro review pack, which is going to make all your dreams come true. Hey, I'll catch you on the flip-flop. Heimler out. +

'''

== 中文释义


既然"法国大革命"是如此具有里程碑意义的事件（我们在上一个视频中谈到过），可以肯定的是，欧洲乃至全世界, 都会对它产生强烈的反应。这就是我们在这个视频中要讨论的内容。所以，如果你准备好充实自己的知识，那我们开始吧。  +

有两种主要的反应, 是你需要了解的，第一个是, 欧洲及其他地区对"法国大革命"的保守派反应。我的意思是，对于许多具有"启蒙思想"的知识分子来说，法国对自由的呼吁, 以及对贵族特权的推翻, 是一件正确且有益的事情。*但随着革命变得更加激进，人们开始大量被断头，像美国的托马斯·杰斐逊（Thomas Jefferson）这样的思想家, 认为事情做得太过火了。*  +

当然，法国国内也有不同意见。约瑟夫·德·迈斯特（Joseph de Maistre）是对"启蒙运动"的强烈批评者，尤其是启蒙运动对"人民自治权利"的强调。迈斯特是一个彻头彻尾的"君主制"拥护者，他以"君权神授"为理由, 来为自己的信仰辩护。在他看来，法国大革命的混乱和暴力, 证明了"启蒙思想"可能造成的危害。  +

所以迈斯特不断主张法国恢复神授的君主制。他是法国新政权下, 少数几个没有把自己送上断头台的保守派批评者之一，因为他最终逃离了法国，并从远处发表他的评论。  +

在法国之外，对法国大革命最著名的保守派反应, 来自英国作家埃德蒙·伯克（Edmund Burke）。**许多欧洲国家最初赞扬这场革命，因为至少它削弱了他们的政治对手，**但也有一些国家认为, 法国的民主化是一种威胁。  +

**#其他国家非常担心他们的人民会受到"法国大革命"所确立的新思想的启发，并在自己的国家寻求同样的变革。#**在英国，保守派埃德蒙·伯克写了《对法国革命的反思》（Reflections on the Revolution in France），在书中他告诫英国人民要警惕"法国大革命"的过激行为。而且他甚至在恐怖统治开始之前, 就写下了这本书。  +

他为"世袭特权"辩护，并滔滔不绝地称赞英国"不具代表性的议会"——他认为这一切都很棒。伯克认为，如果英国人民要求得到法国人民所争取到的东西，结果将是混乱。然后"恐怖统治"爆发了，伯克说：“我早就告诉过你们。”  +

因此，*英国没有像法国那样, 发生对"既定规范"的激进颠覆。*  +

这就是保守派思想家对法国大革命的反应。但**在全球范围内，加勒比地区的反应更为激烈。**  +

在"法国大革命"开始时，法属加勒比地区——特别是圣多明戈（Saint-Domingue）——的局势变得紧张起来。这个岛屿上有几个社会群体，包括法国官员、种植园主、商人、有色自由人, 以及被奴役的非洲劳工。而最后这个群体约占人口的90%。  +

更糟糕的是，法国政府给予不同群体不同程度的权利，毫不奇怪，被奴役的非洲人处于最底层，几乎没有什么权利可言。但别担心，法国，我相信这不会引发任何麻烦。  +

不管怎样，岛上被奴役劳工的处境极其恶劣。事实上，岛上的种植园主——咖啡和甘蔗种植让他们变得非常富有——发现，让奴隶累死然后再购买新奴隶，比善待奴隶更有利可图。  +

但没关系，因为**法国大革命开始后，"国民议会"接管了政权。我相信他们会把法国的自由改革推广到所有殖民地。**如果他们真的这么做，那不是很有趣吗？  +

**不。"国民议会"最终通过了一系列法令和法律，几乎疏远了岛上的所有群体。被奴役的劳工尤其愤怒，他们听到了法国街头“自由、平等、博爱”的呼声，**并认为这些原则会推广到法兰西帝国的所有地方。  +

*但当"国民议"会拒绝承认被奴役人口的权利时，这个岛屿已经具备了革命的条件。*  +

所以到了1791年，岛上的奴隶——他们目睹了白人和有色自由人之间的冲突——开始在夜色掩护下集会，策划一场大规模起义。8月，起义爆发并迅速发展，不久之后，数百个咖啡和甘蔗种植园被摧毁。  +

记住，这是法国最赚钱的殖民地，所以这些起义者不仅摧毁了土地——他们还极大地减少了法国的利润。而在像法国这样的大型殖民帝国中，动钱是绝对不行的。  +

随着起义的进行，一些复杂因素出现了，这些因素来自西班牙和英国。要知道，*这个岛屿的一半, 实际上是西班牙帝国的一部分，看到削弱法国的机会，他们抓住机会支持奴隶起义。*  +

英国也在混乱中看到了机会，他们用海军封锁了这个岛屿，然后入侵并占领了一些领土。  +

**由于他们最有价值的殖民地四面受敌，法国"国民议会"颁布法令，任何为法国而战的奴隶, 都将赢得自由。**但起义者面面相觑，心想：“好吧，这很有意思，但你们可能没注意到，我们已经解放了自己。那你们还有什么别的办法？”  +

*在这种情况下，"国民议会"废除了其所有领土上的奴隶制。*  +

但战争的真正转折点, 是一位才华横溢的士兵杜桑·卢维杜尔（Toussaint Louverture）的崛起，这对法国有利。他出生时是岛上的奴隶，后来获得了自由，在起义开始时，西班牙招募卢维杜尔为他们对抗法国，他照做了，并且轻松证明了自己的才华。  +

但经过几年的战斗，卢维杜尔放弃了为西班牙作战，转而支持法国，并率领一支四千人的军队对抗西班牙和英国。到1796年，卢维杜尔的努力, 使法国重新控制了殖民地。  +

所以"国民议会"任命卢维杜尔为殖民地的指挥官，他击败了南方的对手，维持了对整个圣多明戈的控制。但他开始越来越独立于法国做决策，而此时拿破仑（Napoleon）掌权了，这对他来说可不行。  +

所以**拿破仑想要重新控制"圣多明戈"，**他决定是时候让卢维杜尔下台，并在岛上重新恢复奴隶制。于是派了一个代表团去逮捕卢维杜尔，他被遣返回法国，不久后死在了那里。  +

**但鉴于奴隶制的恢复, 和法国的压迫，卢维杜尔的副手让 - 雅克·德萨林（Jean-Jacques Dessalines）集结了抵抗力量，轻松击败了法国，并在1804年宣布独立。**他们正式将自己的**国家重新命名为海地**（Haiti），这是法国到来之前这个地方的名字。  +

好的，点击这里继续复习美国大学预修课程欧洲历史第五单元。如果你需要更多帮助，想在课堂上得A，并在五月份的考试中得5分，那就点击这里获取我的美国大学预修课程欧洲历史复习资料包，它会让你实现所有梦想。嘿，我们下次再见。海姆勒下线了。  +

'''

== pure

So with an event as monumental as the French Revolution, which we talked about in the last video, you bet your sweet bippy there was going to be some strong reactions to it across Europe and the world. And that is what we're going to talk about in this video. So if you're ready to get them brain cows milked, let's get to it.

So there were two main reactions that you need to know, and the first was the conservative reaction against the French Revolution in Europe and elsewhere. I mean, for a lot of the Enlightenment-style intellectuals, the calls for liberty in France and the overturning of aristocratic privilege was a good and right thing. But as the revolution grew more radical and people started getting their heads cut off by the metric butt-loads, some of these thinkers like Thomas Jefferson over in America decided that things had gone too far.

And there was, of course, dissent from within France as well. Joseph de Maistre was a big critic of the Enlightenment, especially its emphasis on the right of the people to govern themselves. Maistre was a monarchy man through and through, and he justified that belief on the grounds of the divine right of kings. By his reckoning, the chaos and the violence of the French Revolution was proof of the damage Enlightenment thought could do.

And so Maistre advocated endlessly for a return to the divinely ordained monarchy in France. This is one of the few conservative critics under the new regime in France that did not get himself a play date with a guillotine, because he ended up fleeing France and hurling his commentary from afar.

And from outside of France, the best-known conservative reaction against the French Revolution was from the English writer Edmund Burke. Now, while many European nations first praised the revolution because at least it was weakening their political rivals, some saw the democratizing of France as a threat.

There was a strong fear from other nations that their people would be inspired by these new ideas established in the French Revolution and seek them in their own state. In England, conservative Edmund Burke wrote Reflections on the Revolution in France, in which he cautioned the British people against the excesses of the French Revolution. And he even wrote this before the Reign of Terror began.

He defended hereditary privileges and waxed eloquent about Britain's unrepresentative Parliament -- like he thought all of this was great. If the British people demanded what the French had secured, Burke argued, the results would be chaos. Then the Reign of Terror broke out, and Burke was like, "I told y'all."

Therefore, a radical overturning of established norms in England did not occur as it did in France.

Now, that was the reaction to the French Revolution from the think-you-thinking conservatives. But across the globe, there was a more violent reaction in the Caribbean.

By the beginning of the French Revolution, conditions in the French Caribbean -- specifically Saint-Domingue -- were getting intense. The island was made up of several social groups, including French officials, plantation owners, merchants, free people of color, and enslaved African laborers. And this latter group made up about 90 percent of the population.

To make things worse, the French government had granted various levels of rights to the different groups, and not surprisingly, the enslaved Africans were at the bottom of the pile with almost no rights to speak of. But don't worry, France, I'm sure that's not going to cause any trouble.

Anyway, the conditions for the enslaved laborers on the island were brutally vicious. In fact, the plantation owners on the island -- for whom coffee and sugar crops had made them exceedingly wealthy -- had figured out that simply by working a slave to death and then buying new slaves, that was a more profitable system than treating them kindly.

But it's okay, because once the French Revolution began, the National Assembly took over. I'm sure that they're going to extend the liberal reforms made in France to all their colonies as well. Wouldn't that be hilarious if they did that?

No. The National Assembly ended up passing a series of decrees and laws that alienated almost every group on the island. Especially angered were the enslaved workers, who heard the cries for "Liberty, Equality, and Fraternity" in the streets of France and thought that those principles would extend to all places in the French Empire.

But when the National Assembly refused to recognize the enslaved population's rights, the island was ripe for revolution.

So by 1791, the slaves on the island -- who had witnessed the clashes between whites and free people of color -- began meeting under the cover of night to plan a mass rebellion. In August, the rebellion broke out and grew rapidly, and not long after, hundreds of coffee and sugar plantations were destroyed.

And remember, this was France's most profitable colony, so these rebels weren't just destroying land -- they were actively diminishing profits in France. And messing with money is the one thing you do not do in a large colonial empire like France.

So as the rebellion went on, some complicating factors were introduced, and those complications were named Spain and Britain. See, this half of the island was actually part of the Spanish Empire, and seeing the opportunity to weaken the French, they jumped at the opportunity to support the slave rebellion.

The British, also sensing an opportunity in the chaos, blockaded the island with their navy and then invaded the land and took some territory for themselves.

So because their most valuable colony was in danger from all sides, the National Assembly in France issued a decree that any slave who fought for the French cause would win their freedom. But the rebels looked at each other and were like, "Well, that's cute, but in case you haven't noticed, we already freed ourselves. So what else you got?"

At which point, the National Assembly abolished slavery in all of its territory.

But the real tide of the war turned in favor of the French with the rise of a brilliant soldier named Toussaint Louverture. He was born a slave on the island and then later freed, and at the beginning of the insurrection, the Spanish recruited Louverture to fight for them against the French, which he did and easily proved his brilliance.

But after several years of fighting, Louverture abandoned the Spanish and switched sides and led an army of four thousand against the Spanish and the British. By 1796, Louverture's efforts had resulted in France regaining control of their colony.

So the National Assembly installed Louverture as the commander of the colony, and he defeated his rivals to the south to maintain control over all of Saint-Domingue. But he began making more and more decisions independently of France, and by this time, Napoleon was in power, and that was not going to work for him.

So Napoleon, wanting to regain control over Saint-Domingue, decided it was time to get Louverture out of power and re-establish slavery on the island. So a delegation was sent to arrest Louverture, and he was deported back to France, where he died shortly thereafter.

But at the prospect of the return of slavery and French oppression, Louverture's lieutenant, Jean-Jacques Dessalines, rallied the resistance and handily defeated the French and proclaimed independence in 1804. They officially renamed their country Haiti, which had been its name before the arrival of the French.

Okay, click here to keep reviewing for Unit 5 of AP Euro. If you need more help getting an A in your class and a five on your exam in May, then click right here and grab my AP Euro review pack, which is going to make all your dreams come true. Hey, I'll catch you on the flip-flop. Heimler out.

'''