
= 6.7 IDEOLOGIES of Change & Reform Movements
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Now while the Industrial Revolution is changing dang near 几乎 everything in Europe, and the conservative Age of Metternich is in full force 充分发挥作用, lots of new political ideologies 意识形态 are beginning to spring up 涌现 in the 19th century. And in this video we're going to talk all about it. So if you're ready to get them brain cows milked, let's get to it. By the way, if you want to fill in note guides to go along with this video, then check the link in the description. +

Now it is hard to underestimate 低估 just how much social and political disruption 混乱；扰乱 Europe experienced at the end of the 18th century and into the 19th century. Part of it was due to the massive shift in power and social structures that came along with the Industrial Revolution, and part of it was due to the significant rupture 破裂；断裂 in the status quo 现状 caused by the French Revolution. +

And yet another part of it was caused by the suppression 镇压；压制 of nationalist revolts 起义 by states during the conservative Age of Metternich. And there are more causes as well, but you just need to understand that as the social and political ground under Europeans' feet began shifting significantly, many of them started cooking up 策划；编造 and embracing 接受；拥护 new ideologies that demanded change. +

And the first ideology I want to mention is liberalism 自由主义. Now liberalism didn't arise out of nothing during this period -- it was very much an Enlightenment 启蒙运动 idea. You have to get out of your head all the contemporary connotations 内涵；含义 you have with liberalism in America. They're not the same thing. +

Classical liberalism emphasizes 强调 the individual and their natural rights. Additionally 此外, it emphasizes popular sovereignty 人民主权, which teaches that the power to govern is in the hands of the people. To that end, liberalism wants a limited government -- which is to say, not an all-powerful one. +

Liberalism also emphasized enlightened self-interest 开明的利己主义, which means that a person acting in the interests of society is ultimately 最终；最后 acting in his or her own interests. +

Let me give you a couple names to associate with liberalism. First, the British philosopher Jeremy Bentham. Now Bentham did his work before the period we're talking about right now, but his ideas very much set the stage for 为…做好准备 liberalism's flourishing 繁荣；兴旺 in the 19th century. +

He developed a philosophy called utilitarianism 功利主义, which argued that actions should be judged based on whether they increase the happiness of those affected by the action. This was a significant departure from 背离 Christian morality 道德, which established actions as right or wrong based on scriptural sanctions 圣经的制裁. +

For example, according to the Bible it's always wrong to kill a person, but under the rubric of 依据；在…的范畴内 utilitarianism, if killing that person benefited society and increased people's happiness, well, kill away. +

Now a second name to associate with liberalism is John Stuart Mill, who was kind of a disciple 追随者；信徒 of Bentham and built on his work. Mill softened the edges of Bentham's utilitarianism and emphasized acting not only for the happiness of individuals but for the society as a whole. +

Now for the most part, liberals debated how far their principles should reach, and more specifically to whom. In many places, liberalism shifted to the elite 精英 class who prized 珍视；重视 it because it kept government regulations out of their business. +

And as such, they argued that fundamental 基本的；根本的 rights like the right to vote should be limited to those who own land, because they were the ones with the real stake 利害关系 in society. In response to this, a movement in England known as Chartism 宪章运动 pushed back 抵制；反对. +

They demanded universal male suffrage 普选权 and full citizenship without respect to wealth, title, or property ownership. Although their movement fizzled out 失败；告终 despite their great efforts by the mid-19th century, many of the reforms for which they fought would be won by other groups later in the century. +

Additionally, women seldom showed up in liberals' minds as being worthy of their reform. However, John Stuart Mill bucked 反抗；抵制 this trend with his book "The Subjection of Women," in which he argued that women ought to stand upon equal ground with men. +

He argued that women should have the right to vote, the right to hold property, the right to work in professional careers. Over in France, a woman named Flora Tristan worked for the rights of workers and laid the foundations for 为…奠定基础 extending suffrage to women as well. +

In other words, women weren't only good for making their husbands sandwiches -- which was the prevailing 普遍的；流行的 view of the age. +

Okay, now another ideology springing up 涌现 during this time was socialism 社会主义, which when being defined as an ideology that demands that a society's means of production 生产资料 should be owned by the community as a whole, not by private individuals. Essentially 本质上；基本上 a call for a redistribution 重新分配 of a society's wealth. +

And this one emerged right out of the Industrial Revolution. For all the potential good it did, the Industrial Revolution made a few people fabulously 极其地；难以置信地 wealthy and left the majority of people scratching out a bare living 勉强维持生计 in factories earning low wages. And so socialism popping up 涌现 in this context is not hard to understand. +

Now there are a couple of species 种类 of socialism you need to know, and the first is utopian socialism 空想社会主义. And the name to associate with that one is Henri de Saint-Simon. +

He taught that society ought to be given to the workers and taken from what he called the parasites 寄生虫；不劳而获者 -- namely 即；也就是 the aristocracy 贵族 and the church -- who produced nothing of value for the world. If the world's institutions were in the hands of the workers, he argued, they would organize just societies in which there were no longer any poor. +

Now the reason this is called utopian socialism is because the ideas were just a little too grand to ever work in reality, and Saint-Simon never led an attempt to do it. However, his writings were immensely 非常；极其 popular and provided at least a template 模板 for later socialist movements. +

Even so, two of Saint-Simon's disciples 追随者；信徒 -- namely Charles Fourier and Robert Owen -- did attempt to put these ideas into practice by creating what they called intentional communities 意向社群. Their prototype 原型 community was established in Scotland, and its members enjoyed eight-hour work days, shared property, and free education for the children. +

Despite the relative success of that community, the idea really never caught on 流行起来 in the rest of Europe. +

Now the second species of socialism you need to know is called scientific socialism 科学社会主义, which was the brainchild 心血结晶；独创的观念 of Karl Marx. Now Marx had some goals in common with the utopian socialists. He also was deeply distressed at 对…深感忧虑 the injustice 不公正；不公平 of the society where there was such a large gap between the rich and the poor class. +

However, Marx believed that the utopian socialist solutions failed because they didn't really understand how capitalism 资本主义 -- that great enemy of the people -- worked. Therefore, he aimed to produce a socialism that was developed according to the same rigor 严谨；严密 and standards that scientists use in their description of the natural world. +

So Marx, along with Friedrich Engels, published these ideas in an influential 有影响力的 book known as "The Communist Manifesto." +

In order to understand what these men presented, you have to understand their view of history. According to Marx and Engels, history obeys laws just as the physical world obeys the laws of physics. Therefore, they argue that history moved through patterns and stages until one day it would reach its ultimate goal. +

To them, the driving force of history is class struggle 阶级斗争 over economic wealth. Industrialization had exacerbated 加剧；恶化 the division between the two classes -- the bourgeoisie 资产阶级 and the proletariat 无产阶级 -- and thus a new societal arrangement 社会安排 was necessary. +

The bourgeoisie owned the means of production and thus exploited 剥削 the proletariat for their own benefit. Once the proletariat became conscious of this arrangement, they would rise up in a cataclysmic 大变动的；灾难的 movement of revolution and overthrow 推翻；打倒 the bourgeoisie. That would mark the end of class struggle. +

Now part and parcel of 重要部分 scientific socialism was equal rights for men and women. Thus, some women became significant Marxist leaders during this time. In Germany, Clara Zetkin led the charge against 带头反对 the privileges 特权 of the bourgeoisie and worked on reform on behalf of 代表 women. +

Then over in Poland, Rosa Luxemburg worked to secure 争取；获得 rights for the working class and even led a revolution -- you know, a failed one, but a revolution nonetheless 尽管如此. +

And the final ideology for change that you need to know is anarchism 无政府主义. The idea here is that all forms of governmental authority 政府权力 were unnecessary and should be overthrown 推翻 or replaced with a society based on voluntary cooperation 自愿合作. +

Over in Russia, Mikhail Bakunin became the poster boy 典型人物 for anarchism. He was a Russian revolutionary who argued that secret societies ought to lead revolutionary movements to destroy the state and replace it with self-governing workplaces and communes 公社. +

Over in France, Georges Sorel worked along a similar vein 类似地. He taught that once people rose up and destroyed the governing authorities, that all property should then be transferred to labor unions 工会. And the French word for labor union is syndicate 辛迪加, which is to say Sorel's teaching became known as syndicalism 工团主义. +

Okay, click right here to keep reviewing for unit 6 of AP Euro, or click right here to get my AP Euro review pack if you need help getting an A in your class and a five on your exam in May. I'll catch you on the flip-flop. Heimler out. +

'''

== 中文释义

当工业革命几乎改变了欧洲的一切，梅特涅的保守时代正全面展开时，**19世纪, 许多新的政治意识形态开始涌现。**在这个视频中，我们将详细讨论这些内容。所以，如果你准备好充实自己的知识，那我们开始吧。顺便说一下，如果你想要与这个视频配套的填空笔记，查看描述中的链接。  +

*很难低估欧洲在18世纪末到19世纪所经历的社会和政治动荡。部分原因是"工业革命"带来的权力和社会结构的巨大转变，部分原因是"法国大革命"对现状造成的重大冲击 (在经济上和思想上, 欧洲都经历了重大进步)。*  +

还有部分原因是在梅特涅的保守时代，各国对民族主义起义的镇压。当然还有更多原因，但你只需明白，当欧洲人脚下的社会和政治基础, 开始大幅变动时，许多人开始酝酿, 并接受要求变革的新意识形态。  +

我想提到的**第一个意识形态是"自由主义"**（liberalism）。在这个时期，自由主义并非凭空产生——它在很大程度上是一种启蒙思想。*你必须抛开你对美国自由主义的所有当代内涵的认知。它们不是一回事。*  +

*#"古典自由主义"强调个人及其自然权利。此外，它强调"人民主权"，即统治权掌握在人民手中。为此，自由主义主张"有限政府"——也就是说，不是一个拥有绝对权力的政府。#*  +

*"自由主义"还强调"开明的利己主义"，这意味着一个人为社会利益行动，最终也是在为自己的利益行动。*  +

让我给你介绍几个与自由主义相关的人物。首先是英国哲学家**杰里米·边沁**（Jeremy Bentham）。边沁在我们现在谈论的这个时期之前, 就开展了他的工作，但**他的思想为19世纪"自由主义"的蓬勃发展奠定了基础。**  +

**#他发展了一种名为"功利主义"（utilitarianism）的哲学，该哲学认为，行动应该根据"它们是否增加了受其影响者的幸福"来评判。#**这与基督教道德有很大不同，基督教道德根据圣经的约束来判定行动的对错。  +

例如，*根据《圣经》，杀人总是错误的，但在"功利主义"的框架下，如果杀死那个人有利于社会并增加了人们的幸福感，那么就可以这么做。*  +

另一个与"自由主义"相关的人物, 是约翰·斯图尔特·密尔（John Stuart Mill），他在某种程度上是边沁的追随者，并在边沁的工作基础上进行了拓展。*密尔缓和了边沁"功利主义"的极端性，强调行动不仅要为了个人的幸福，也要为了整个社会的幸福。*  +

**在很大程度上，自由主义者争论的, 是他们的原则应该应用到什么程度，更具体地说，应用到哪些人身上。**在许多地方，自由主义转向了精英阶层，精英阶层珍视自由主义，因为它使政府监管远离他们的事务。  +

因此，他们认为像"选举权"这样的基本权利, 应该仅限于那些拥有土地的人，因为他们是在社会中有真正利害关系的人。作为回应，英国的一场名为"宪章运动"（Chartism）的运动进行了反抗。  +

他们要求男性普选权，以及不论财富、头衔或财产所有权的完全公民权。尽管他们的运动在19世纪中期付出巨大努力后失败了，但他们为之奋斗的许多改革, 在那个世纪后期被其他团体实现了。  +

此外，女性很少被"自由主义者"认为值得进行改革。然而，约翰·斯图尔特·密尔在他的《妇女的屈从地位》（“The Subjection of Women”）一书中打破了这种趋势，他在书中主张女性应该与男性处于平等地位。  +

他认为女性应该有选举权、拥有财产的权利, 以及从事职业工作的权利。在法国，一位名叫弗洛拉·特里斯坦（Flora Tristan）的女性, 为工人的权利而努力，也为女性获得选举权奠定了基础。  +

换句话说，女性不仅仅是为丈夫做三明治的（当时普遍这么认为），她们还有更多价值。  +

好的，现在另一个在这个时期兴起的意识形态, 是"社会主义"（socialism），*##社会主义##被定义为一种意识形态，##它要求社会的生产资料, 应该由整个社会所拥有(国有化)，而不是由私人个体拥有。##本质上是呼吁对社会财富进行重新分配。*  +

这种意识形态直接源于工业革命。尽管工业革命有其潜在的好处，但它让少数人变得极其富有，而大多数人在工厂里靠低工资勉强维持生计。所以在这种背景下"社会主义"的出现并不难理解。  +

你需要了解社会主义的几个种类，第一种是"空想社会主义"（utopian socialism）。与之相关的人物是亨利·德·圣西门（Henri de Saint-Simon）。  +

他教导说，社会应该归工人所有，从他所称的“寄生虫”——即贵族和教会——手中夺过来，这些人没有为世界生产任何有价值的东西。他认为，如果世界的机构掌握在工人手中，他们将组织起没有穷人的公正社会。  +

之所以被称为"空想社会主义"，是因为这些想法在现实中有点过于宏大, 而无法实现，而且圣西门从未尝试去实践这些想法。然而，他的著作非常受欢迎，至少为后来的社会主义运动提供了一个模板。  +

即便如此，圣西门的两个追随者——即夏尔·傅立叶（Charles Fourier）和罗伯特·欧文（Robert Owen）——确实试图将这些想法付诸实践，他们创建了所谓的“理想社区”。他们的原型社区在苏格兰建立，其成员享受每天八小时工作制、财产共享, 以及儿童免费教育。  +

尽管那个社区取得了相对的成功，但这个想法在欧洲其他地方并没有流行起来。  +

你需要了解的**社会主义的第二种类型, 是"科学社会主义"（scientific socialism），这是卡尔·马克思（Karl Marx）的创想。**马克思与空想社会主义者有一些共同的目标。他也对贫富差距巨大的社会的不公正深感忧虑。  +

然而，马克思认为"空想社会主义"的解决方案失败了，因为他们并不真正了解资本主义——人民的大敌——是如何运作的。因此，他旨在提出一种社会主义，这种社会主义是按照科学家描述自然世界时所使用的严格标准, 来发展的。  +

所以马克思与弗里德里希·恩格斯（Friedrich Engels）一起，在一本有影响力的名为《共产党宣言》（“The Communist Manifesto”）的书中发表了这些想法。  +

为了理解这些人所提出的观点，你必须了解他们的历史观。*#根据马克思和恩格斯的观点，历史就像物理世界遵循"物理定律"一样, 遵循着一定的规律。因此，他们认为历史通过一定的模式和阶段发展，直到有一天达到其最终目标。(这个逻辑就相当于说, 未来是可以预测的一样.)#*  +

**对他们来说，历史的驱动力, 是围绕"经济财富"的阶级斗争。**工业化加剧了两个阶级——资产阶级（bourgeoisie）和无产阶级（proletariat）——之间的分化，因此一种新的社会安排是必要的。  +

资产阶级拥有生产资料，因此为了自身利益, 剥削无产阶级。一旦无产阶级意识到这种安排，他们就会在一场灾难性的革命运动中崛起，推翻资产阶级。这将标志着阶级斗争的结束。  +

"科学社会主义"的一个重要部分, 是男女平等权利。因此，在这个时期一些女性成为了重要的马克思主义领导人。在德国，克拉拉·蔡特金（Clara Zetkin）带头反对资产阶级的特权，并为女性改革而努力。  +

在波兰，罗莎·卢森堡（Rosa Luxemburg）为工人阶级争取权利，甚至领导了一场革命——你知道，虽然失败了，但那确实是一场革命。  +

你需要了解的最后一种变革意识形态, 是**"无政府主义"（anarchism）。其核心观点是，所有形式的政府权威都是不必要的，应该被推翻，取而代之的是一个基于自愿合作的社会。**  +

在俄罗斯，米哈伊尔·巴枯宁（Mikhail Bakunin）成为了无政府主义的代表人物。他是一位俄罗斯革命者，他认为秘密社团应该领导革命运动，摧毁国家，用自治的工作场所和公社来取代它。  +

在法国，乔治·索雷尔（Georges Sorel）也有类似的观点。他教导说，一旦人们起来摧毁统治当局，所有财产应该转移到工会手中。法语中“工会”的单词是“syndicate”，这就是为什么索雷尔的学说被称为工团主义（syndicalism）。  +

好的，点击这里继续复习美国大学预修课程欧洲历史第六单元，或者如果你需要帮助，想在课堂上得A，并在五月份的考试中得5分，点击这里获取我的美国大学预修课程欧洲历史复习资料包。我们下次再见。海姆勒下线了。  +

'''

== pure

Now while the Industrial Revolution is changing dang near everything in Europe, and the conservative Age of Metternich is in full force, lots of new political ideologies are beginning to spring up in the 19th century. And in this video we're going to talk all about it. So if you're ready to get them brain cows milked, let's get to it. By the way, if you want to fill in note guides to go along with this video, then check the link in the description.

Now it is hard to underestimate just how much social and political disruption Europe experienced at the end of the 18th century and into the 19th century. Part of it was due to the massive shift in power and social structures that came along with the Industrial Revolution, and part of it was due to the significant rupture in the status quo caused by the French Revolution.

And yet another part of it was caused by the suppression of nationalist revolts by states during the conservative Age of Metternich. And there are more causes as well, but you just need to understand that as the social and political ground under Europeans' feet began shifting significantly, many of them started cooking up and embracing new ideologies that demanded change.

And the first ideology I want to mention is liberalism. Now liberalism didn't arise out of nothing during this period -- it was very much an Enlightenment idea. You have to get out of your head all the contemporary connotations you have with liberalism in America. They're not the same thing.

Classical liberalism emphasizes the individual and their natural rights. Additionally, it emphasizes popular sovereignty, which teaches that the power to govern is in the hands of the people. To that end, liberalism wants a limited government -- which is to say, not an all-powerful one.

Liberalism also emphasized enlightened self-interest, which means that a person acting in the interests of society is ultimately acting in his or her own interests.

Let me give you a couple names to associate with liberalism. First, the British philosopher Jeremy Bentham. Now Bentham did his work before the period we're talking about right now, but his ideas very much set the stage for liberalism's flourishing in the 19th century.

He developed a philosophy called utilitarianism, which argued that actions should be judged based on whether they increase the happiness of those affected by the action. This was a significant departure from Christian morality, which established actions as right or wrong based on scriptural sanctions.

For example, according to the Bible it's always wrong to kill a person, but under the rubric of utilitarianism, if killing that person benefited society and increased people's happiness, well, kill away.

Now a second name to associate with liberalism is John Stuart Mill, who was kind of a disciple of Bentham and built on his work. Mill softened the edges of Bentham's utilitarianism and emphasized acting not only for the happiness of individuals but for the society as a whole.

Now for the most part, liberals debated how far their principles should reach, and more specifically to whom. In many places, liberalism shifted to the elite class who prized it because it kept government regulations out of their business.

And as such, they argued that fundamental rights like the right to vote should be limited to those who own land, because they were the ones with the real stake in society. In response to this, a movement in England known as Chartism pushed back.

They demanded universal male suffrage and full citizenship without respect to wealth, title, or property ownership. Although their movement fizzled out despite their great efforts by the mid-19th century, many of the reforms for which they fought would be won by other groups later in the century.

Additionally, women seldom showed up in liberals' minds as being worthy of their reform. However, John Stuart Mill bucked this trend with his book "The Subjection of Women," in which he argued that women ought to stand upon equal ground with men.

He argued that women should have the right to vote, the right to hold property, the right to work in professional careers. Over in France, a woman named Flora Tristan worked for the rights of workers and laid the foundations for extending suffrage to women as well.

In other words, women weren't only good for making their husbands sandwiches -- which was the prevailing view of the age.

Okay, now another ideology springing up during this time was socialism, which when being defined as an ideology that demands that a society's means of production should be owned by the community as a whole, not by private individuals. Essentially a call for a redistribution of a society's wealth.

And this one emerged right out of the Industrial Revolution. For all the potential good it did, the Industrial Revolution made a few people fabulously wealthy and left the majority of people scratching out a bare living in factories earning low wages. And so socialism popping up in this context is not hard to understand.

Now there are a couple of species of socialism you need to know, and the first is utopian socialism. And the name to associate with that one is Henri de Saint-Simon.

He taught that society ought to be given to the workers and taken from what he called the parasites -- namely the aristocracy and the church -- who produced nothing of value for the world. If the world's institutions were in the hands of the workers, he argued, they would organize just societies in which there were no longer any poor.

Now the reason this is called utopian socialism is because the ideas were just a little too grand to ever work in reality, and Saint-Simon never led an attempt to do it. However, his writings were immensely popular and provided at least a template for later socialist movements.

Even so, two of Saint-Simon's disciples -- namely Charles Fourier and Robert Owen -- did attempt to put these ideas into practice by creating what they called intentional communities. Their prototype community was established in Scotland, and its members enjoyed eight-hour work days, shared property, and free education for the children.

Despite the relative success of that community, the idea really never caught on in the rest of Europe.

Now the second species of socialism you need to know is called scientific socialism, which was the brainchild of Karl Marx. Now Marx had some goals in common with the utopian socialists. He also was deeply distressed at the injustice of the society where there was such a large gap between the rich and the poor class.

However, Marx believed that the utopian socialist solutions failed because they didn't really understand how capitalism -- that great enemy of the people -- worked. Therefore, he aimed to produce a socialism that was developed according to the same rigor and standards that scientists use in their description of the natural world.

So Marx, along with Friedrich Engels, published these ideas in an influential book known as "The Communist Manifesto."

In order to understand what these men presented, you have to understand their view of history. According to Marx and Engels, history obeys laws just as the physical world obeys the laws of physics. Therefore, they argue that history moved through patterns and stages until one day it would reach its ultimate goal.

To them, the driving force of history is class struggle over economic wealth. Industrialization had exacerbated the division between the two classes -- the bourgeoisie and the proletariat -- and thus a new societal arrangement was necessary.

The bourgeoisie owned the means of production and thus exploited the proletariat for their own benefit. Once the proletariat became conscious of this arrangement, they would rise up in a cataclysmic movement of revolution and overthrow the bourgeoisie. That would mark the end of class struggle.

Now part and parcel of scientific socialism was equal rights for men and women. Thus, some women became significant Marxist leaders during this time. In Germany, Clara Zetkin led the charge against the privileges of the bourgeoisie and worked on reform on behalf of women.

Then over in Poland, Rosa Luxemburg worked to secure rights for the working class and even led a revolution -- you know, a failed one, but a revolution nonetheless.

And the final ideology for change that you need to know is anarchism. The idea here is that all forms of governmental authority were unnecessary and should be overthrown or replaced with a society based on voluntary cooperation.

Over in Russia, Mikhail Bakunin became the poster boy for anarchism. He was a Russian revolutionary who argued that secret societies ought to lead revolutionary movements to destroy the state and replace it with self-governing workplaces and communes.

Over in France, Georges Sorel worked along a similar vein. He taught that once people rose up and destroyed the governing authorities, that all property should then be transferred to labor unions. And the French word for labor union is syndicate, which is why Sorel's teaching became known as syndicalism.

Okay, click right here to keep reviewing for unit 6 of AP Euro, or click right here to get my AP Euro review pack if you need help getting an A in your class and a five on your exam in May. I'll catch you on the flip-flop. Heimler out.

'''