
= 7.7 Imperialism's GLOBAL EFFECTS
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

All right, if you were here for the last video, we talked about the second wave of European imperialism. Now in part two, we need to talk about the effects that wave of imperialism had on Europe itself and the African and Asian peoples they went out to conquer. So I hope you can already taste the sauce, and if you're ready to get them brain cows milked, let's get to it. +

So once industrialized European states set their sights on 把目光投向；以……为目标 Africa as the object of their imperialistic 帝国主义的 impulses 冲动, they got to carving up 瓜分 the continent quick, fast, and in a hurry. And they did this, as I mentioned in the last video, so that they could gain access to 获得；接近 more raw materials to feed their factories and to find new markets for their manufactured goods. But the greatness of these imperial nations was on the line 处于危险中 too. The slogan 口号 of the era might as well have been "he who dies with the biggest empire wins." +

And so the race to colonize 殖民 Africa, known as the Scramble for Africa 非洲争夺战, ended up creating significant tension between European states who all wanted the biggest piece of the African pie for themselves. And this tension seemed as if it would lead to war at any moment. Therefore, starting in 1884, Otto von Bismarck called the Berlin Conference, which was a series of meetings in which the imperial powers 帝国主义列强 of Europe could carve Africa up peacefully through discussion and negotiation 谈判；协商. +

You know, it actually worked. Like after the Berlin Conference, almost the entire continent of Africa was claimed by one of the European imperial powers, and they did it peacefully. Well done, Otto, you made everybody happy -- except the entire continent of Africans whom you did not invite to the conference, who might have, you know, objected 反对. But you didn't think everybody lived happily ever after, did you? Don't be crazy. +

Like even though the boundaries 边界 of African colonies were agreed upon at the Berlin Conference, it didn't take long before those tensions between European states flared up 爆发；突然加剧 again. Like it did, for example, in the Fashoda Crisis. Both Britain and France wanted to connect their African empires via railroad, but there was a big fat problem for both of them, namely Fashoda, which was owned by neither of them. Like if either of them were going to connect their railways, this was a key location. +

Both nations ended up sending military forces into Fashoda and were on the brink of war 处于战争边缘. However, the French knew that they were very much outnumbered 人数上占劣势的 and outgunned 火力上占劣势的 by the British, and so they withdrew 撤退, conceding 承认；让步 the territory to Britain. Now the French did this not only because they were outnumbered, but also they could see the growing influence of Germany in Africa and in Europe. And in that way, France very much needed a friend in Britain to fend off 抵御；抵抗 potential future conflicts with Germany. +

So France and Britain signed the Entente Cordiale 友好协定 in 1904, which established friendly relations between those two nations. And there were also the Moroccan Crises. Like if France thought that they needed to buddy up 结盟；联合 with Britain to fend off German aggression 侵略, turns out they were right. At the Berlin Conference, it was decided that France would control most of North Africa, including Morocco. But the Germans weren't too keen on 对……热衷 this, and so in 1905 and 1911, the Germans backed 支持 native Moroccan rebellions 叛乱 against the French. +

As a result, it smelled like war was in the air. But remember, France and Britain hugged it out in the Entente Cordiale, and so Germany, without the support of their allies, decided it was a bad move to test the strength of that alliance. And ultimately, the conflict was solved through diplomacy 外交手段, in which France retained 保留 control of Morocco. But what this crisis demonstrated 表明；证明 was the increasing bond 纽带；联系 between France and Britain and the increasing antagonism 对抗；敌对 between them and Germany, which is going to come back around in World War I. +

Now while all this is going on in Africa between the heads of European states, there was a growing objection 反对 among some Europeans about whether imperialism was a good thing at all. Now to be clear, this was not a majority voice. Most Europeans saw precisely 恰好；正是 nothing wrong with imperialism. But there were some who objected, and that objection gave rise to 引起；导致 an increasingly tense debate 辩论；争论 over imperial ventures 帝国主义冒险活动. +

The first objectors 反对者 you should know were artists. British writer Joseph Conrad traveled to the Belgian Congo, which was arguably 可以说 the most brutal 残酷的；野蛮的 of all the European colonial ventures, and he witnessed firsthand 亲眼；亲身 the degrading 有辱人格的 and violent policies put in place there by King Leopold II of Belgium. The Congo was a different kind of colony because Leopold kept it for himself, not for Belgium, and thus he enacted 制定；颁布 exceedingly 极其；非常 savage 野蛮的；残酷的 and cruel policies against the Congolese in order to enrich himself. +

So deeply disturbed by what he saw, Joseph Conrad returned and wrote his novel "Heart of Darkness," which laid out 阐述；说明 in graphic detail the kinds of abuses the Congolese were experiencing under the imperial rule of Leopold. And though it was a work of fiction, Conrad's criticism 批评；批判 of the system of coerced labor 强制劳动 and brutality 残酷；野蛮 was apparent 明显的. +

And since we're talking about objections to brutality in the Congo, you should know another British man, Edmund Morel, formed the Congo Reform Association to address violence in the Congo. He gathered many notable 著名的；知名的 writers of the era and outlined Leopold's violent policies in the Congo. And as a result, these writers flooded 充斥；充满 the European consciousness 意识 with arguments against Leopold's imperial venture. And ultimately, they forced Leopold to transfer imperial rights of the Congo to Belgium itself. +

Another manifestation 表现；显示 of the debate over imperialism was concerned with the economics of the practice. Economist J.A. Hobson published a paper arguing that imperialism was ultimately a detrimental 有害的；不利的 economic system in the long run 从长远来看 because it depended on markets that were inherently 本质上；内在地 unstable. In other words, imperialism was a drag on capitalism 资本主义. +

Over in Russia, Vladimir Lenin, who was certainly no friend of capitalism, found himself at least in partial agreement with Hobson. But while Hobson thought imperialism was an aberration 偏差；反常 of capitalism, Lenin argued that it was the fulfillment 实现；完成 of capitalism, and thus both imperialism and capitalism ought to be thrown out. +

Now as non-Europeans who found themselves under imperial rule went to colonial schools and learned Western values, they began challenging European imperialism in various ways. And in order to understand that, let's begin in Africa. In their colonies Natal and Zululand, the British had forced the native Zulus into working diamond mines, which was hard and dangerous work. +

Eventually, a nationalist 民族主义的 wave took hold among the Zulus as well, and they gathered an army of 40,000. The British attacked them, and for about 6 months the Zulus scored many victories. But all it took was time, and eventually the British were successful in crushing 镇压；粉碎 that rebellion. +

But over in Ethiopia, it was a different outcome. When Italy claimed Ethiopia, the Ethiopian king was like, "Oh heck no." And remember that one of the main reasons Europeans were so successful in subduing 征服；镇压 the African continent was because of their superior weaponry 先进的武器. So knowing this, the king of Ethiopia, Menelik II, purchased industrial-grade weapons from France and Russia. So when the Italians came traipsing in 大摇大摆地走进 to conquer, they were met with stiff resistance 顽强的抵抗, and the Ethiopians were successful in throwing them off and remained an independent African state. +

Okay, click here to keep reviewing unit 7 of AP Euro, and click here to get my AP Euro review pack, which has everything you need to get an A in your class and a five on your exam in May. And I'll catch you on the flip-flop. Tim out. +

'''

== 中文释义


好的，如果你看过上一个视频，我们谈到了欧洲帝国主义的第二次浪潮。现在，在第二部分，我们需要谈谈这股帝国主义浪潮对欧洲自身, 以及他们试图征服的非洲和亚洲人民所产生的影响。所以我希望你已经能感受到其中的意味了，如果你准备好充实自己的知识，那我们开始吧。  +

所以，一旦**工业化的欧洲国家, 将非洲**视为其帝国主义冲动的目标，它们就迅速、快速且急切地开始**瓜分这个大陆。**正如我在上一个视频中提到的，**#它们这样做, 是为了获取更多的原材料, 来供应它们的工厂，并为其制成品找到新的市场。#**但这些帝国主义国家之间也存在着激烈的竞争。这个时代的口号可以说是“拥有最大帝国者获胜”。  +

因此，对非洲的殖民竞赛，也就是所谓的“非洲争夺战（Scramble for Africa）”，最终在欧洲各国之间引发了严重的紧张局势，**这些国家都想为自己在非洲这块蛋糕上分得最大的一块。这种紧张局势似乎随时可能引发战争。**因此，从1884年开始，奥托·冯·俾斯麦（Otto von Bismarck）召集了**柏林会议**（Berlin Conference），这是一系列的会议，*#在这些会议上，欧洲的帝国主义列强, 可以通过讨论和谈判, 和平地瓜分非洲。#*  +

你知道，这实际上是起作用的。**#在"柏林会议"之后，几乎整个非洲大陆, 都被欧洲的帝国主义列强所占领，而且它们是和平地完成了瓜分。#**干得好，奥托，你让每个人都开心了—**—除了整个非洲大陆的人民，你们没有邀请他们参加会议，**而他们可能会有所反对。*#但你不会认为此后大家就过上了幸福的生活吧，别天真了。#*  +

即使非洲殖民地的边界在"柏林会议"上达成了协议，但欧洲各国之间的紧张局势, 没过多久就再次爆发了。例如在法绍达危机（Fashoda Crisis）中就是如此。*英国和法国都想通过铁路连接他们在非洲的帝国，但对他们来说有一个大问题，那就是法绍达（Fashoda），这个地方不属于他们任何一方。如果他们任何一方想要连接他们的铁路，这里就是一个关键地点。*  +

两国最终都向"法绍达"派遣了军事力量，并且处于战争的边缘。然而，**法国**知道他们在人数和武器装备上都远远不如英国，所以他们撤退了，**把这块领土让给了英国。**法国这样做不仅是因为他们在人数上处于劣势，还**#因为他们看到了德国在非洲和欧洲日益增长的影响力。从这个角度来看，法国非常需要英国这个盟友, 来抵御未来与德国的潜在冲突。#**  +

所以法国和英国在1904年签署了《友好协约》（Entente Cordiale），在两国之间建立了友好关系。还有摩洛哥危机（Moroccan Crises）。就像法国认为他们需要与英国结盟, 来抵御德国的侵略一样，事实证明他们是对的。*在"柏林会议"上，决定由法国控制包括摩洛哥（Morocco）在内的大部分北非地区。但德国人对此不太满意，所以在1905年和1911年，德国人支持摩洛哥本土的反叛势力对抗法国。*  +

结果，战争的气息弥漫开来。但要记住，**法国和英国通过《友好协约》紧密结盟，所以德国在没有盟友支持的情况下，认为挑战这一联盟的实力, 是一个糟糕的举动。**最终，这场冲突通过外交手段得以解决，法国保留了对摩洛哥的控制权。但**这场危机表明，法国和英国之间的联系日益紧密，而它们与德国之间的对抗也日益加剧，这种情况在"第一次世界大战"中还会再次出现。**  +

当欧洲各国的领导人在非洲的这些事情发生时，**#一些欧洲人, 对"帝国主义是否是一件好事", 提出了越来越多的反对意见。需要明确的是，这并不是大多数人的声音。大多数欧洲人认为"帝国主义"并没有什么错。#**但确实有一些人表示反对，这种反对引发了关于帝国主义冒险行为的日益激烈的辩论。  +

你应该知道的第一批反对者是作家,艺术家。英国作家约瑟夫·康拉德（Joseph Conrad）前往比利时刚果（Belgian Congo），可以说这是所有欧洲殖民冒险中最残酷的地方，他亲眼目睹了比利时国王利奥波德二世（King Leopold II）在那里实施的, 有辱人格和暴力的政策。刚果是一个不同类型的殖民地，因为利奥波德是为了自己占有这块殖民地，而不是为了比利时，因此他对比利时刚果人实施了极其野蛮和残酷的政策, 来使自己致富。  +

约瑟夫·康拉德对他所看到的情况深感不安，他回国后写了小说《黑暗之心》（"Heart of Darkness"），详细地描绘了刚果人在利奥波德的帝国统治下, 所遭受的种种虐待。尽管这是一部小说，但康拉德对强迫劳动和残暴制度的批判, 是显而易见的。  +

既然我们在谈论对比利时刚果残暴行为的反对，你应该知道另一个英国人埃德蒙·莫雷尔（Edmund Morel）, 成立了"刚果改革协会"（Congo Reform Association）, 来解决刚果的暴力问题。他召集了那个时代的许多著名作家，概述了利奥波德在刚果的暴力政策。结果，这些作家向欧洲人的意识中, 灌输了反对"利奥波德帝国主义冒险行为"的观点。最终，他们迫使利奥波德将刚果的统治权, 移交给比利时政府。  +

关于帝国主义的辩论的另一个表现, 是对这种行为的"经济方面"的关注。经济学家J.A.霍布森（J.A. Hobson）发表了一篇论文，认为从长远来看，帝国主义最终是一个有害的经济体系，因为它依赖于本质上不稳定的市场。换句话说，帝国主义是资本主义的拖累。  +

在俄罗斯，弗拉基米尔·列宁（Vladimir Lenin）当然不是资本主义的朋友，他发现自己至少在部分上同意霍布森的观点。但霍布森认为, 帝国主义是资本主义的一种畸变，而列宁则认为, 帝国主义是资本主义的必然结果，因此帝国主义和资本主义都应该被摒弃(结果, 斯大林的苏联成了帝国主义)。  +

现在，那些处于帝国主义统治下的非欧洲人, 进入殖民学校，学习西方的价值观，他们开始以各种方式挑战欧洲的帝国主义。为了理解这一点，让我们从非洲开始说起。在他们的殖民地纳塔尔（Natal）和祖鲁兰（Zululand），英国强迫当地的祖鲁人（Zulus）进入钻石矿工作，这是艰苦而危险的工作。  +

最终，一股民族主义浪潮在祖鲁人中兴起，他们集结了一支4万人的军队。英国对他们发动了攻击，在大约6个月的时间里，祖鲁人取得了许多胜利。但随着时间的推移，最终英国成功地镇压了这场叛乱。  +

但在埃塞俄比亚（Ethiopia），结果却不同。当意大利声称对埃塞俄比亚拥有主权时，埃塞俄比亚国王说：“哦，绝对不行。” 要记住，**欧洲人能够成功征服非洲大陆的一个主要原因, 是他们拥有先进的武器装备。所以埃塞俄比亚国王孟尼利克二世（Menelik II）从法国和俄罗斯购买了工业级别的武器 (以夷制夷)。**所以当意大利人前来征服时，他们遭到了顽强的抵抗，埃塞俄比亚人成功地将他们赶走，保持了自己作为一个独立的非洲国家的地位。  +

好的，点击这里继续复习美国大学预修课程欧洲历史第七单元，点击这里获取我的美国大学预修课程欧洲历史复习资料包，里面有你在课堂上得A以及在五月份的考试中得5分所需要的一切。我们下次再见。蒂姆结束。  +

'''

== pure

All right, if you were here for the last video, we talked about the second wave of European imperialism. Now in part two, we need to talk about the effects that wave of imperialism had on Europe itself and the African and Asian peoples they went out to conquer. So I hope you can already taste the sauce, and if you're ready to get them brain cows milked, let's get to it.

So once industrialized European states set their sights on Africa as the object of their imperialistic impulses, they got to carving up the continent quick, fast, and in a hurry. And they did this, as I mentioned in the last video, so that they could gain access to more raw materials to feed their factories and to find new markets for their manufactured goods. But the greatness of these imperial nations was on the line too. The slogan of the era might as well have been "he who dies with the biggest empire wins."

And so the race to colonize Africa, known as the Scramble for Africa, ended up creating significant tension between European states who all wanted the biggest piece of the African pie for themselves. And this tension seemed as if it would lead to war at any moment. Therefore, starting in 1884, Otto von Bismarck called the Berlin Conference, which was a series of meetings in which the imperial powers of Europe could carve Africa up peacefully through discussion and negotiation.

You know, it actually worked. Like after the Berlin Conference, almost the entire continent of Africa was claimed by one of the European imperial powers, and they did it peacefully. Well done, Otto, you made everybody happy -- except the entire continent of Africans whom you did not invite to the conference, who might have, you know, objected. But you didn't think everybody lived happily ever after, did you? Don't be crazy.

Like even though the boundaries of African colonies were agreed upon at the Berlin Conference, it didn't take long before those tensions between European states flared up again. Like it did, for example, in the Fashoda Crisis. Both Britain and France wanted to connect their African empires via railroad, but there was a big fat problem for both of them, namely Fashoda, which was owned by neither of them. Like if either of them were going to connect their railways, this was a key location.

Both nations ended up sending military forces into Fashoda and were on the brink of war. However, the French knew that they were very much outnumbered and outgunned by the British, and so they withdrew, conceding the territory to Britain. Now the French did this not only because they were outnumbered, but also they could see the growing influence of Germany in Africa and in Europe. And in that way, France very much needed a friend in Britain to fend off potential future conflicts with Germany.

So France and Britain signed the Entente Cordiale in 1904, which established friendly relations between those two nations. And there were also the Moroccan Crises. Like if France thought that they needed to buddy up with Britain to fend off German aggression, turns out they were right. At the Berlin Conference, it was decided that France would control most of North Africa, including Morocco. But the Germans weren't too keen on this, and so in 1905 and 1911, the Germans backed native Moroccan rebellions against the French.

As a result, it smelled like war was in the air. But remember, France and Britain hugged it out in the Entente Cordiale, and so Germany, without the support of their allies, decided it was a bad move to test the strength of that alliance. And ultimately, the conflict was solved through diplomacy, in which France retained control of Morocco. But what this crisis demonstrated was the increasing bond between France and Britain and the increasing antagonism between them and Germany, which is going to come back around in World War I.

Now while all this is going on in Africa between the heads of European states, there was a growing objection among some Europeans about whether imperialism was a good thing at all. Now to be clear, this was not a majority voice. Most Europeans saw precisely nothing wrong with imperialism. But there were some who objected, and that objection gave rise to an increasingly tense debate over imperial ventures.

The first objectors you should know were artists. British writer Joseph Conrad traveled to the Belgian Congo, which was arguably the most brutal of all the European colonial ventures, and he witnessed firsthand the degrading and violent policies put in place there by King Leopold II of Belgium. The Congo was a different kind of colony because Leopold kept it for himself, not for Belgium, and thus he enacted exceedingly savage and cruel policies against the Congolese in order to enrich himself.

So deeply disturbed by what he saw, Joseph Conrad returned and wrote his novel "Heart of Darkness," which laid out in graphic detail the kinds of abuses the Congolese were experiencing under the imperial rule of Leopold. And though it was a work of fiction, Conrad's criticism of the system of coerced labor and brutality was apparent.

And since we're talking about objections to brutality in the Congo, you should know another British man, Edmund Morel, formed the Congo Reform Association to address violence in the Congo. He gathered many notable writers of the age and outlined Leopold's violent policies in the Congo. And as a result, these writers flooded the European consciousness with arguments against Leopold's imperial venture. And ultimately, they forced Leopold to transfer imperial rights of the Congo to Belgium itself.

Another manifestation of the debate over imperialism was concerned with the economics of the practice. Economist J.A. Hobson published a paper arguing that imperialism was ultimately a detrimental economic system in the long run because it depended on markets that were inherently unstable. In other words, imperialism was a drag on capitalism.

Over in Russia, Vladimir Lenin, who was certainly no friend of capitalism, found himself at least in partial agreement with Hobson. But while Hobson thought imperialism was an aberration of capitalism, Lenin argued that it was the fulfillment of capitalism, and thus both imperialism and capitalism ought to be thrown out.

Now as non-Europeans who found themselves under imperial rule went to colonial schools and learned Western values, they began challenging European imperialism in various ways. And in order to understand that, let's begin in Africa. In their colonies Natal and Zululand, the British had forced the native Zulus into working diamond mines, which was hard and dangerous work.

Eventually, a nationalist wave took hold among the Zulus as well, and they gathered an army of 40,000. The British attacked them, and for about 6 months the Zulus scored many victories. But all it took was time, and eventually the British were successful in crushing that rebellion.

But over in Ethiopia, it was a different outcome. When Italy claimed Ethiopia, the Ethiopian king was like, "Oh heck no." And remember that one of the main reasons Europeans were so successful in subduing the African continent was because of their superior weaponry. So knowing this, the king of Ethiopia, Menelik II, purchased industrial-grade weapons from France and Russia. So when the Italians came traipsing in to conquer, they were met with stiff resistance, and the Ethiopians were successful in throwing them off and remained an independent African state.

Okay, now another nationalist rebellion occurred in British India. Now in India, where the British East India Company ruled, a private military was established comprised of both British officers and sepoys, which were Indian soldiers that were either Hindu or Muslim. Because of the rapid Westernization occurring in India and the feeling that their native traditions and cultures were being lost or degraded, a surge of nationalism led the sepoys to rebel in an event known as the Sepoy Mutiny in 1857.

Once the rebellion began, it spread rapidly across India, which indicated that the Indians were not too happy with British colonial rule. And at first, the British only had a few troops to crush the mutiny, but eventually they did. And the major consequence of this rebellion is that possession of the colony was transferred from the British East India Company and squarely into the hands of the British government.

Okay, click here to keep reviewing unit 7 of AP Euro, and click here to get my AP Euro review pack, which has everything you need to get an A in your class and a five on your exam in May. And I'll catch you on the flip-flop. Tim out.

'''