
= 8.10 Cultural, Intellectual, & Artistic Developments, Early 20th Century
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 释义

So now it's time to close Unit 8 /and consider the cultural and intellectual 文化和知识的 developments /that occurred throughout the 20th century, and baby, they were profound 深远的；意义重大的. So if you're ready to get them brain cows milked, let's get to it. +

When the 20th century began, there was a widespread belief in the inevitability 必然性；不可逃避 of progress, which was brought forward 提出,呈现 from the 19th century. Starting with the Scientific Revolution 科学革命 and into the Enlightenment 启蒙运动, science had solved so many of _our collective problems_ as human beings 科学解决了我们人类的许多共同问题, and so /_at the turn of_ the century, we were basically _on the precipice 悬崖；绝壁；险境;边缘 of_ a utopian 乌托邦的；理想国的 civilization. The 20th century is going to be great (20世纪将是伟大的), y'all 你们大家,各位. But then Europe went ahead /and plunged 使陷入；使遭受 itself into World War One, and all that sweet-smelling 芬芳的 optimism 乐观；乐观主义 disappeared (v.) like a fart 放屁 in the wind. +

[.my1]
.案例
====
.precipice
-> pre-,在前，-cip,头，词源同cap,captain.即头在前，一头栽下，引申词义陡坡，陡崖，悬崖等。
====

Now to be fair, `主` this shattering 粉碎；摧毁 of belief in progress `谓` had started before World War One, but it was mainly confined (v.) to 局限于；限制于 artists and a handful of 少量的；一小部分 elite folks 精英人士. But once the war began, people could see /`主` what all this progress 后定说明 in science and culture `谓` gave us.

`主` Scientific breakthroughs (n.)突破，重大进展 in chemistry /`谓` gave us chlorine (n.)  gas 氯气 and mustard 芥末黄；褐黄色 gas 芥子气, which choked (v.)使窒息 and killed hundreds of thousands /on the battlefield.  +
Breakthroughs in mechanical engineering 机械工程 gave us the machine gun 机枪, which mercilessly (adv.)氯,无情地 *mowed  (v.)（用机器等）刈草，割草 down* 扫射；扫倒 millions of Europe's young men.  +
Scientific breakthroughs /that occurred in medicine /with the widespread use of vaccines 疫苗 and sanitation 卫生设施, but those were just used /to send men to the slaughter 屠杀 /and then *care for* them in their wrecked 失事的；遇难的；毁坏的 state. +

[.my2]
需要说明的是，这种对进步信念的彻底崩塌, 早在第一次世界大战之前就已经开始，但当时主要局限于艺术家和一小部分精英人士当中。然而，一旦战争爆发，人们便能够看到科学与文化领域所有这些进步, 给我们带来了什么。 +
化学领域的重大突破, 为我们带来了氯气和芥子气，这些物质在战场上夺走了数十万人的生命。 +
机械工程领域的突破, 让我们有了机关枪，这种武器无情地扫射了欧洲数百万年轻人的生命。 +
医学领域的重大突破, 得益于疫苗和卫生设施的广泛应用，但这些只是被用来将人们送上战场，然后在他们伤痕累累的状态下,进行救治而已。

[.my1]
.案例
====
.merciless
-> mercy,宽大，怜悯，仁慈，-less,无，没有。引申词义无情的，残忍的。


====

So the point is, after World War One had ended, `主` that disillusionment 幻灭；失望 about the notion 概念，想法 /that humanity was progressing (v.)  toward perfection 完美；完善 /`谓` filtered  过滤 down from the elite circles 精英圈子 /and spread (v.) more generally to everyone else. Now it wasn't only two World Wars /that had people questioning (v.) their beliefs about reality. Scientists made new discoveries during this time /and helped people realize that /their grasp 理解；掌握 on reality was not as firm as they thought. +

[.my2]
所以关键在于，第一次世界大战结束后，人们对"人类正朝着完美方向进步"这一观念的失望情绪, 从精英阶层蔓延开来，并逐渐影响到了更多的人。如今，让人们质疑对现实的认知的，并不仅仅是两次世界大战。在这段时间里，科学家们取得了新的发现，并帮助人们认识到, 他们对现实的把握, 并不像自己认为的那样牢固。

Now remember /_what a triumphant 成功的；胜利的 moment it was_ when 300 years prior, Isaac Newton had published his _laws of physics_ 物理学定律, and all of a sudden /we knew _how the world worked_. Nature was governed by immutable 不可改变的 laws /that could never be changed.  +
And then remember /_how great it was_ in the early 19th century /when chemist John Dalton had articulated 阐述；明确表达 his theory of atoms 原子理论 -- how _there were these hard bits of matter_ /that constituted (v.)构成 the basic building blocks 基本组成部分 of all that exists. So we finally figured out _how everything works_, and now we can *focus on* other problems. +

[.my2]
请记住，300年前，艾萨克·牛顿发表了他的物理学定律，那一刻是多么令人振奋啊！突然间，我们明白了世界的运行原理。自然界遵循着永恒不变的法则，这些法则永远不会改变。然后，请回想一下，在19世纪初，化学家约翰·道尔顿阐述了他的原子理论——原来存在着这些坚硬的物质粒子，它们构成了世间万物的基本构成单元。于是，我们终于弄清楚了万物运行的规律，现在我们可以把精力放在其他问题上去了。



But in the early and mid 20th century, a group of new scientists came along 取得进展,出现 and shattered (v.)（使）破碎，碎裂 all those illusions 幻想；错觉.  +
First was Albert Einstein, `主` whose work `谓` helped us to see that /time and space are not fixed realities 固定的现实 at all. Instead, in his theory of relativity 相对论, Einstein discovered that /time and space are actually relative to 相对于 the observer 观察者. In other words, _the faster_ a person moves (v.) through space, Einstein argued, _the slower_ time would move.

And then came Werner Heisenberg, who built on the work of previous physicists /who had discovered that /the atom was not _in fact_ the smallest unit of reality. They discovered subatomic  亚原子的；原子内的 particles 亚原子粒子 like electrons 电子, but still everyone believed that /electrons behaved (v.)  predictably 可预测地. But Heisenberg was like, "Oh, that's so cute." What he discovered is that /`主` #the act# of _observing (v.) an electron with light_ 用光观察电子的行为 -- which is, you know, how you observe (v.) an electron -- `谓` #changes# (v.) the behavior of the electron. So in that way, *we have no stinking 发恶臭的；（非正式）令人讨厌的；愤怒不已的 idea* 完全不知道 _how subatomic particles move_ /because they change (v.)  *based on* how we observe them. +

[.my2]
他发现用光观察电子的行为——你知道，就是你观察电子的方式——改变了电子的行为。这样一来，我们根本不知道亚原子粒子是如何运动的，因为它们是根据我们的观察而变化的。

[.my1]
.案例
====
.we have no stinking idea
- *"have no idea"*​​： 最基本的表达，意思是“*完全不知道*”。
- *"stinking"​​： 字面意思是“发臭的”，在这里作为​​加强语气的粗俗副词​​（vulgar intensifier），类似于中文里的“屁”、“鬼”、“毛”，用来表达厌恶、 frustration（挫败）或强调。*
- "have no stinking idea"​​ = ​​“根本屁都不知道”​​、​​“完全搞不懂”​​、​​“压根没有一点头绪”​​。
====

Then came the work of Enrico Fermi and Niels Bohr 然后是恩里科·费米和尼尔斯·玻尔的研究, both of whom were able to harness 利用 the explosive power of splitting (v.) atoms 分裂原子. And that discovery *led to* the development of the atomic bomb 原子弹, which killed hundreds of thousands of Japanese people /at the end of World War II /and created a right mess 一团糟 in international relations 国际关系 during the Cold War 冷战. +

And then there was a developing science 发展中的科学 of people's interior world 内心世界 with the rise of psychology 心理学. We human beings *like to think that* 我们人类喜欢这么想 we act (v.) according to our rational nature 理性本质 /*and that* we commonly *reason (v.)推理，逻辑思考；推论出，推断出 out* 推断出；想出 what to do next /when *presented 使发生；使经历 with* stimuli (n.)刺激；刺激物 from the world. +
Nothing came along 取得进展 like Sigmund Freud 弗洛伊德, who argued that /under the surface, human beings are completely irrational 不理性的. *Instead of* making decisions *based on* reasoned analysis 理性分析, Freud argued that /we actually behave (v.) mostly on unknown impulses 冲动 后定说明 deep within our psyche (n.)心灵；精神;灵魂；心智. +

[.my1]
.案例
====
.present
(v.) *~ sb with sth | ~ sth* :to cause sth to happen /or be experienced 使发生；使经历 +
•Your request shouldn't present us with any problems. 你的请求应该不会给我们造成任何问题。 +
•Use of these chemicals may present a fire risk. 使用这些化学品可能有失火的危险。

.psyche
( formal ) the mind; your deepest feelings and attitudes 灵魂；心灵；精神；心态 +
•the human psyche 人的心灵 +
•She knew, at some deep level of her psyche, that what she was doing was wrong. 她在内心深处, 还是知道自己当时正在做错误的事。 +
====

So whether it was _our understanding of how the world worked_ /or _how human beings themselves worked_, `主` the emerging science of the 20th century `谓` was undermining 逐渐削弱；破坏 all our beliefs about a certain and predictable universe. +

[.my2]
因此，无论是我们对世界运行方式的理解，还是对人类自身运作机制的认识，20世纪新兴的科学都在瓦解我们关于“宇宙是确定且可预测”的所有信念。

Also *thanks to* World War One, `主` a whole generation of those /who *came of age* 成年 during the war /`谓` were saddled (v.)给……装马鞍；承受；使负担 with 背负；肩负 disillusionment  幻灭；醒悟. It was writer Gertrude Stein /who called them _The Lost Generation_ 迷惘的一代. All of a sudden /they felt adrift (a.)漂泊的；迷茫的 in a post-war culture. `主` Values and mores 道德观念；习俗 that they had inherited 继承 from their parents `谓` no longer seemed to work (v.) in the world /that the war had created. You can see this /especially in the writings of Ernest Hemingway 海明威 and F. Scott Fitzgerald. +



Additionally, women experienced a profound change in the 20th century. Hundreds of thousands of women joined the military to serve (v.) in auxiliary positions 辅助职位 like nurses and office workers. In addition, because the men had to go off 离开，离去 and fight the war, they took up 拿起 domestic jobs 家庭工作 as well, many of them in factories /during both world wars. `主` This newfound (a.)新发现的；新得到的 liberty 自由 outside of the home `谓` led to a rise /in the efforts of women 在女性的努力下 /to gain the right to vote 选举权. And though it would take another 30 years /after the close of World War II /for all European women to gain the franchise 选举权 in democratic countries 民主国家, slowly but surely *it did occur* (v.). +

Okay, that's the end of Unit 8. And click here if you're studying for an exam -- it's my AP Euro review pack, which will help you get an A in your class and a five on your exam in May. If you want to keep reviewing for Unit 8, then click here, and this playlist will make all your dreams come true. I'll catch you on the flip-flop. I'm out. +

'''

== 中文释义

所以现在是时候结束第8单元的内容了，我们来看看在整个20世纪发生的文化和知识方面的发展，伙计，这些发展意义深远。所以，如果你准备好获取知识，那就开始吧。 +

**#20世纪初，人们普遍相信进步是必然的，这种信念是从19世纪延续而来的。#从科学革命开始，一直到启蒙运动，科学解决了我们人类共同面临的许多问题，所以在世纪之交，我们基本上处于一种乌托邦文明的边缘。大家都觉得20世纪会很棒。但后来欧洲却陷入了第一次世界大战，所有美好的乐观情绪都像风中的屁一样消散了。##** +

公平地说，对"进步的信念"被打破, 在第一次世界大战之前就开始了，但主要局限于艺术家和少数精英人群。但战争一旦爆发，人们就看到了科学和文化方面的这些进步带给我们的东西。化学方面的科学突破带来了氯气和芥子气，这些毒气在战场上使数十万人窒息而死。机械工程方面的突破带来了机关枪，它无情地扫射死了数百万欧洲的年轻人。医学方面的科学突破带来了疫苗的广泛使用和卫生设施的进步，但这些却被用来把人们送上战场，然后在他们受伤时照顾他们。 +

所以关键是，**##第一次世界大战结束后，对"人类正朝着完美进步"这一观念的幻灭, ##从精英阶层逐渐蔓延到了普通大众。**而且，让人们质疑他们对现实的信念的, 不只是两次世界大战。在这个时期，科学家们有了新的发现，让人们意识到, 他们对现实的理解, 并不像他们以为的那样牢固。 +

还记得300年前，艾萨克·牛顿（Isaac Newton）发表了他的物理学定律，那是一个多么伟大的时刻，突然间我们知道了世界是如何运转的。大自然受着不可改变的定律支配。然后想想19世纪初，化学家约翰·道尔顿（John Dalton）阐述了他的原子理论，这是多么了不起的事情 —— 我们知道了有这些坚硬的物质构成了所有存在事物的基本组成部分。所以我们最终弄清楚了一切是如何运转的，现在我们可以关注其他问题了。 +

但在20世纪上半叶，一群新的科学家出现了，打破了所有这些幻想。首先是阿尔伯特·爱因斯坦（Albert Einstein），他的研究让我们明白"时间"和"空间"根本不是固定不变的现实。相反，在他的"相对论"中，爱因斯坦发现, 时间和空间实际上是相对观察者而言的。换句话说，**爱因斯坦认为，一个人在空间中移动得越快，时间流逝得就越慢。**然后维尔纳·海森堡（Werner Heisenberg）出现了，他在之前物理学家的研究基础上发现，原子实际上并不是现实的最小单位。人们发现了像电子这样的亚原子粒子，但大家仍然认为电子的行为是可预测的。但海森堡可不这么认为。他发现，用光线观察电子的行为 —— 这是我们观察电子的方式 —— 会改变电子的行为。所以从这个角度看，*我们根本不知道"亚原子粒子"是如何运动的，因为它们会根据我们的观察而改变。* +

接着恩里科·费米（Enrico Fermi）和尼尔斯·玻尔（Niels Bohr）的研究成果出现了，他们能够利用原子分裂的爆炸力。这一发现导致了原子弹的研制，在第二次世界大战末期，原子弹造成了数十万日本人死亡，并且在冷战期间给国际关系带来了一团糟的局面。 +

随着心理学的兴起，人们对人类内心世界的科学认识(心理学)也在不断发展。我们人类喜欢认为我们的行为是基于理性的，当面对来自外界的刺激时，我们通常会理性地思考下一步该做什么。但西格蒙德·弗洛伊德（Sigmund Freud）的观点却截然不同，他认为在表面之下，人类是完全不理性的。弗洛伊德认为，我们的行为大多是基于我们内心深处未知的冲动，而不是基于理性分析来做决定。 +

所以，无论是我们对世界如何运转的理解，还是对人类自身如何运转的理解，20世纪新兴的科学都在动摇我们对一个确定且可预测的宇宙的所有信念。 +

同样**由于第一次世界大战，在战争期间成年的整整一代人都沉浸在幻灭之中。作家格特鲁德·斯泰因（Gertrude Stein）称他们为 “迷惘的一代”（The Lost Generation）。突然间，他们在战后文化中感到漂泊无依。他们从父母那里继承的价值观和道德观念，在战争创造的世界里似乎不再适用。**这一点在欧内斯特·海明威（Ernest Hemingway）和F. 斯科特·菲茨杰拉德（F. Scott Fitzgerald）的作品中尤为明显。 +

此外，*20世纪女性的情况也发生了深刻的变化。成千上万的女性加入了军队，担任护士和办公室职员等辅助职位。而且，因为男性要去参战，在两次世界大战期间，女性也承担起了国内的工作，很多人在工厂工作。这种在家庭之外获得的新自由，推动了女性为争取选举权而做出的努力。尽管在第二次世界大战结束后又过了30年，欧洲民主国家的所有女性才获得选举权，但这一目标还是缓慢而坚定地实现了。* +

好了，第8单元的内容就到这里。如果你正在为考试做准备，点击这里 —— 这是我的AP欧洲史复习资料包，它能帮助你在课堂上得A，在五月的考试中得5分。如果你想继续复习第8单元，点击这里，这个播放列表会让你梦想成真。回头见。我走了。 +

'''

== pure

So now it's time to close Unit 8 and consider the cultural and intellectual developments that occurred throughout the 20th century, and baby, they were profound. So if you're ready to get them brain cows milked, let's get to it.

When the 20th century began, there was a widespread belief in the inevitability of progress, which was brought forward from the 19th century. Starting with the Scientific Revolution and into the Enlightenment, science had solved so many of our collective problems as human beings, and so at the turn of the century, we were basically on the precipice of a utopian civilization. The 20th century is going to be great, y'all. But then Europe went ahead and plunged itself into World War One, and all that sweet-smelling optimism disappeared like a fart in the wind.

Now to be fair, this shattering of belief in progress had started before World War One, but it was mainly confined to artists and a handful of elite folks. But once the war began, people could see what all this progress in science and culture gave us. Scientific breakthroughs in chemistry gave us chlorine gas and mustard gas, which choked and killed hundreds of thousands on the battlefield. Breakthroughs in mechanical engineering gave us the machine gun, which mercilessly mowed down millions of Europe's young men. Scientific breakthroughs that occurred in medicine with the widespread use of vaccines and sanitation, but those were just used to send men to the slaughter and then care for them in their wrecked state.

So the point is, after World War One had ended, that disillusionment about the notion that humanity was progressing toward perfection filtered down from the elite circles and spread more generally to everyone else. Now it wasn't only two World Wars that had people questioning their beliefs about reality. Scientists made new discoveries during this time and helped people realize that their grasp on reality was not as firm as they thought.

Now remember what a triumphant moment it was when 300 years prior, Isaac Newton had published his laws of physics, and all of a sudden we knew how the world worked. Nature was governed by immutable laws that could never be changed. And then remember how great it was in the early 19th century when chemist John Dalton had articulated his theory of atoms -- how there were these hard bits of matter that constituted the basic building blocks of all that exists. So we finally figured out how everything works, and now we can focus on other problems.

But in the early and mid 20th century, a group of new scientists came along and shattered all those illusions. First was Albert Einstein, whose work helped us to see that time and space are not fixed realities at all. Instead, in his theory of relativity, Einstein discovered that time and space are actually relative to the observer. In other words, the faster a person moves through space, Einstein argued, the slower time would move. And then came Werner Heisenberg, who built on the work of previous physicists who had discovered that the atom was not in fact the smallest unit of reality. They discovered subatomic particles like electrons, but still everyone believed that electrons behaved predictably. But Heisenberg was like, "Oh, that's so cute." What he discovered is that the act of observing an electron with light -- which is, you know, how you observe an electron -- changes the behavior of the electron. So in that way, we have no stinking idea how subatomic particles move because they change based on how we observe them.

Then came the work of Enrico Fermi and Niels Bohr, both of whom were able to harness the explosive power of splitting atoms. And that discovery led to the development of the atomic bomb, which killed hundreds of thousands of Japanese people at the end of World War II and created a right mess in international relations during the Cold War.

And then there was a developing science of people's interior world with the rise of psychology. We human beings like to think that we act according to our rational nature and that we commonly reason out what to do next when presented with stimuli from the world. Nothing came along like Sigmund Freud, who argued that under the surface, human beings are completely irrational. Instead of making decisions based on reasoned analysis, Freud argued that we actually behave mostly on unknown impulses deep within our psyche.

So whether it was our understanding of how the world worked or how human beings themselves worked, the emerging science of the 20th century was undermining all our beliefs about a certain and predictable universe.

Also thanks to World War One, a whole generation of those who came of age during the war were saddled with disillusionment. It was writer Gertrude Stein who called them The Lost Generation. All of a sudden they felt adrift in a post-war culture. Values and mores that they had inherited from their parents no longer seemed to work in the world that the war had created. You can see this especially in the writings of Ernest Hemingway and F. Scott Fitzgerald.

Additionally, women experienced a profound change in the 20th century. Hundreds of thousands of women joined the military to serve in auxiliary positions like nurses and office workers. In addition, because the men had to go off and fight the war, they took up domestic jobs as well, many of them in factories during both world wars. This newfound liberty outside of the home led to a rise in the efforts of women to gain the right to vote. And though it would take another 30 years after the close of World War II for all European women to gain the franchise in democratic countries, slowly but surely it did occur.

Okay, that's the end of Unit 8. And click here if you're studying for an exam -- it's my AP Euro review pack, which will help you get an A in your class and a five on your exam in May. If you want to keep reviewing for Unit 8, then click here, and this playlist will make all your dreams come true. I'll catch you on the flip-flop. I'm out.

'''