
= 8.3 The RUSSIAN Revolution
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Oh my goodness, the Russian Revolution is upon us. I don't think I'm overselling it when I say that this is a massive honking deal in European history -- a massive honking deal that's going to set us up for major consequences in the rest of this course. So if you're ready to get them brain cows milked Bolshevik 布尔什维克的 style, then let's get to it. +

So as with any revolution we've considered in European history, the Russian Revolution was preceded by a few glaring 明显的 problems, and it was Russia's participation in World War One that blew these problems up to massive proportions 规模. First, there was the problem of political stagnation 政治停滞. Remember from unit six that Russia had experienced the revolution of 1905 because the people began demanding liberal reforms 自由主义改革 from the turd tsarist government 沙皇政府. I won't go into all that here, but the short version is some liberal reforms were enacted 颁布, and then they were taken away, and then the revolution of 1905 was largely a failure. +

Now by the time World War One rolled around, Nicholas II was the Tsar, and in order to quell 镇压；平息 further discontent, very much leaned on his military and bureaucracy 官僚机构 to bolster 支持；加强 his regime. And since Russia had lost millions of men to the war effort by this point, Nicholas made the really dumb decision to go into the field and lead his armies personally. I know that sounds heroic, but he was pretty incompetent 无能力的；不称职的, and that led to more discontent with his leadership. +

The second problem in Russia was social inequality 社会不平等. Though serfdom 农奴制 was abolished in 1861, the landed elites 土地贵族 in many places still maintained a great deal of power. And then add to that the increasing gap between the wealthy and the poor, and people were not happy. And all of this, as I mentioned, was only worsened by Russia's involvement in World War One. +

And then the third problem they were contending with 处理；应对 was incomplete industrialization 不完全的工业化. Though significant gains had been made to industrialize Russia in prior decades, World War One showed how deficient 缺乏的；不足的 they really were. Russian troops didn't have enough guns -- like not enough ammunition 弹药 -- and some of them lacked adequate clothing and footwear 鞋类. And these are like the basics that any state is going to need to do well in a war. +

And finally, the fourth problem they were enduring in Russia was food and land distribution 食物和土地分配. Again, despite the abolition of serfdom, most peasants were landless, and food shortages 食物短缺 were common. And it was food shortages that led to the first rumblings 迹象；预兆 of the Russian Revolution in March of 1917 in an event that became known as the March Revolution 二月革命. +

The March Revolution: Factory workers, many of whom were women, took to the streets protesting the soaring 急剧上升的 cost of their staple food items 主食, most notably bread. Czar Nicholas was absent from events -- that is, the domestic turmoil 国内动荡 that was unfolding -- while he was busy commanding his own troops in the field of a global war. So he commanded his troops at home to subdue 镇压；征服 the uprising 起义 and then told them to go ahead and start shooting if necessary. +

But what Nicholas did not expect was for many of his troops to feel sympathetic to the cause of these women and actually join in their protest, which many of them did. And so with Nicholas rapidly losing control, the Russian legislature 立法机构 known as the Duma 杜马 gathered and took control of Russia, and on the same day Nicholas abdicated the throne 退位. +

Now while this provisional government 临时政府 had control, they faced a lot of difficulties, particularly from the lower class. The provisional government was largely influenced by the interests of the middle class, but they increasingly had to contend with councils 委员会 that represented working-class interests known as Soviets 苏维埃, who on the majority were made up of socialists 社会主义者. +

Now one of the major movers and shakers 有影响力的人物 among the Soviets were the members of the Marxist Social Democratic party 马克思主义社会民主党, who were not surprisingly devoted to the communist ideals 共产主义理想 of Karl Marx. In 1903, the party effectively split into two factions 派别. The first, known as the Mensheviks 孟什维克, wanted a socialist state, but they were willing to install a parliamentary democracy 议会民主制 in the meantime. The more radical 激进的 faction on the other hand devoted themselves to a violent overthrow 暴力推翻 not only of the tsarist regime but also of Western capitalist values 西方资本主义价值观. +

The Bolsheviks 布尔什维克 were led by Marx devotee 信徒 Vladimir Lenin, who in 1917 saw an opportunity for the Bolsheviks to overthrow the provisional government. He publishes the April Theses 四月提纲, which outlined 概述 the steps for revolution based on Marxist reasoning 马克思主义推理. Now to be clear, these steps to communism weren't pure Marx, but they were Marx's ideas filtered through Lenin's own brain. Lenin essentially thought that Marx's prescribed 规定的 steps toward a socialist state would take too long, and therefore Lenin thought Russia could, you know, skip a few steps. +

Anyway, the three slogans of the April Theses summed up Lenin's program succinctly 简洁地:
Peace, land, and bread. By peace he meant Russia's withdrawal 撤出 from World War One. By land he meant equal redistribution 重新分配 of land to all. And by bread he meant, you know, bread.
Worker control of production as opposed to elite and bourgeois control 工人对生产的控制，而不是精英和资产阶级的控制.
All power to the Soviets.
And so in November of 1917, Lenin saw his opportunity and led Bolshevik forces to overthrow the provisional government, which turned out to be a surprisingly bloodless 不流血的 and easy task. And at that point, the Bolsheviks -- now renamed the Communists -- were in control of Russia, which later became known as the Soviet Union 苏联. +

And by March of 1918, Lenin had negotiated a settlement that would remove Russia from World War One by giving up a metric buttload of Russian territory in Eastern Europe. But that didn't matter much to Lenin because the goal was for Soviet communism to spread over the entire world, so you know, a small setback 挫折. +

So yes, Lenin didn't make good on the promise for peace in the April Theses, but that's about the time Russia itself got involved in the Civil War 内战. You didn't think everybody in Russia was going to welcome the socialist state with fists in the air and smiles on their faces, did you? You're so crazy. No, remember this was a revolution of the working class, and now their interests reign supreme 至高无上的. But in case you forgot, the working class wasn't the only class that existed. +

And so because of the bitterness 怨恨 this new forced arrangement 强制安排 caused among the aristocracy 贵族 and the anti-Leninists, along with several other now marginalized groups 被边缘化的群体, Russia degenerated into Civil War. The anti-communist forces were aided by several Western powers who were none too excited about seeing a communist government installed in Russia. By all counts, this was a force that probably should have overwhelmed the Bolshevik Army 布尔什维克军队. +

However, under the leadership of Lenin's right-hand man Leon Trotsky, the Communist Army became phenomenally 惊人地 disciplined 纪律严明的 and organized. Not only that, Lenin and Trotsky were able to generate Russian nationalist sentiment 俄罗斯民族主义情绪 against these Western interlopers 闯入者, and that had a way of getting people to fight. The war ended in 1922 with the victory going to Lenin and the Communists, and that's when we officially get the transformation of Russia into the Soviet Union. +


image:/img/svg 俄国共产党夺权.svg[,100%]



Okay, now remember what I said before, namely that Lenin wanted to skip steps in order to get a full-on communist state, and the New Economic Policy 新经济政策 was a shining example. He thought that by cutting corners 走捷径 and introducing only a smidge 少量 of capitalism in order to shore up 支撑；巩固 the economy, that afterward he could chuck 抛弃 it and move right along to communism. But that did not work, and that's important to understand because when people say that communism has never worked where it has been tried, the response is, well, you know, it's never actually been tried, and Lenin is the case in point 恰当的例子. +

All right, click here to grab my AP Euro review pack, which is everything you need to get an A in your class and a five on your exam in May, and click here to keep reviewing Unit 8 of AP European History. I'll catch you on the flip-flop. I'm out. +




'''

== 中文释义

哦，天哪，俄国革命来临了。我觉得这么说并不过分，这在欧洲历史上是一件极其重大的事情——这一重大事件将为我们在本课程后续内容中带来重大影响。所以，如果你准备好以布尔什维克的方式充实自己的知识，那就开始吧。  +

就像我们在欧洲历史中探讨过的任何一场革命一样，**#俄国革命之前, 其国内就已经存在一些明显的问题，而俄国参与第一次世界大战, 使这些问题被放大到了极其严重的程度。首先是政治停滞问题。#**还记得在第六单元中提到，**俄国在1905年经历了一场革命，因为人们开始要求腐朽的沙皇政府进行自由主义改革。**我在这里就不详细阐述了，*简而言之，一些自由主义改革得以实施，但随后又被取消，1905年的革命在很大程度上是失败的。*  +

当第一次世界大战爆发时，尼古拉二世（Nicholas II）是沙皇，为了平息进一步的不满情绪，他大力依靠军队和官僚机构来巩固自己的政权。*由于俄国在战争中已经损失了数百万人，尼古拉做出了一个非常愚蠢的决定，他亲自到前线指挥军队。我知道这听起来很英勇，但他相当无能，这导致人们对他的领导更加不满。*  +

**俄国的第二个问题是社会不平等。**尽管农奴制在1861年被废除，但许多地方的地主精英仍然拥有很大的权力。再加上贫富差距日益加大，人们对此很不满意。正如我提到的，俄国参与第一次世界大战使所有这些问题变得更加严重。  +

俄国面临的**第三个问题是工业化不完全。**尽管在之前的几十年里，俄国在工业化方面取得了重大进展，但**第一次世界大战暴露了他们的严重不足。**俄国军队没有足够的枪支——比如弹药不足——而且一些士兵缺乏足够的衣物和鞋子。而这些是任何一个国家在战争中取得良好表现所需要的基本条件。  +

最后，俄国面临的**第四个问题是食物和土地分配问题。**同样，*尽管农奴制被废除，但大多数农民没有土地，食物短缺现象很普遍。#食物短缺引发了1917年3月俄国革命的最初动荡，这一事件被称为“二月革命（March Revolution）”。#*  +

*##二月革命：工厂工人，其中很多是女性，走上街头抗议主食（尤其是面包）价格飞涨。##沙皇尼古拉二世不在国内处理这些事件——也就是说，国内正在发生的动荡——因为他忙着在全球战争的战场上指挥自己的军队。所以他命令国内的军队镇压起义，并告诉他们如有必要就开枪。*  +

*但尼古拉没有想到的是，他的##许多士兵同情这些女性的诉求，实际上还加入了她们的抗议活动，##而且很多士兵确实这么做了。#随着尼古拉迅速失去对局势的控制，被称为"杜马"（Duma）的俄国立法机构聚集起来, 并控制了俄国，同一天尼古拉二世退位。#*  +

**#当这个"临时政府"掌权时，他们面临着很多困难，尤其是来自"下层阶级"的压力。临时政府在很大程度上受到"中产阶级"利益的影响，但他们越来越多地不得不应对代表"工人阶级"利益的苏维埃（Soviets），苏维埃中的大多数人是社会主义者。# ** +

在苏维埃中，主要的推动者和变革者之一, 是**马克思主义社会民主党**（Marxist Social Democratic party）的成员，毫不奇怪，他们致力于卡尔·马克思（Karl Marx）的共产主义理想。*1903年，#该党实际上分裂成了两个派别。第一个派别被称为孟什维克#（Mensheviks），他们想要建立一个社会主义国家，但他们##愿意在此期间建立一个"议会民主制"。##另一方面，更激进的派别致力于不仅推翻沙皇政权，而且推翻西方资本主义价值观。*  +

布尔什维克（Bolsheviks）由马克思的追随者弗拉基米尔·列宁（Vladimir Lenin）领导，**1917年，列宁看到了"布尔什维克"推翻"临时政府"的机会。他**发表了《四月提纲（April Theses）》，提纲基于马克思主义推理概述了革命的步骤。需要明确的是，这些通往共产主义的步骤, 并非纯粹的马克思主义，而是经过列宁思考过滤后的马克思主义思想。*列宁基本上认为，马克思所规定的建立"社会主义国家"的步骤耗时太长，所以列宁认为俄国可以跳过一些步骤。(俄国还没经过成熟的资本主义, 就想着要跳往社会主义.)*  +

无论如何，*《四月提纲》的三个口号简洁地总结了列宁的纲领：
和平、土地和面包。他所说的和平, 是指俄国退出"第一次世界大战"。土地是指:将土地平等地重新分配给所有人。面包就是字面意义上的面包。
工人控制生产，而不是由精英和资产阶级控制。
一切权力归苏维埃。*  +

*所以在1917年11月，列宁看到了机会，他带领布尔什维克力量推翻了"临时政府"，结果这是一项出奇地没有流血且轻松的任务。从那时起，布尔什维克——后来改名为"共产党"*——控制了俄国，俄国后来被称为苏联（Soviet Union）。  +

*1918年3月，##列宁通过谈判达成了一项协议，俄国放弃了东欧的大量领土，从而退出了"第一次世界大战"。但这对列宁来说并不重要，因为目标是让苏联共产主义传播到全世界，##所以这只是一个小挫折。*  +

是的，**列宁没有兑现《四月提纲》中关于和平的承诺，但就在那时俄国陷入了内战。**你不会认为俄国的每个人都会高举拳头、面带微笑地欢迎"社会主义"国家的建立吧？别天真了。不，*记住这是一场工人阶级的革命，现在他们的利益至高无上。但##别忘了，工人阶级并不是俄国唯一存在的阶级。##*  +

由于这种新的强制安排, 在贵族和反列宁主义者, 以及其他几个被边缘化的群体中, 引起了不满，俄国陷入了内战。**反共产主义力量得到了几个西方大国的支持，**这些西方大国对俄国建立共产主义政府可不太高兴。从各方面来看，这股力量本应能够打败布尔什维克军队。  +

然而，在列宁的得力助手列夫·托洛茨基（Leon Trotsky）的领导下，共产党军队变得纪律严明、组织有序。不仅如此，**列宁和托洛茨基还激发了俄罗斯"民族主义"情绪, 来对抗这些西方干涉者，**这让人们有了战斗的动力。1922年，战争以列宁和共产党的胜利而告终，就在那时，俄国正式转变为苏联。  +

然而，甚至**在内战结束之前，列宁就敏锐地意识到俄国的经济状况很糟糕。为了纠正这些困难，列宁采取了一些有限的资本主义政策，这一政策在1921年被称为"新经济政策"（New Economic Policy）。根据这个计划，农民不再需要把农产品上交给国家，而是可以在公开市场上出售。此外，列宁允许小商业和农场的私有制，同时他保留了对大型商业机构的控制权。**  +

好的，记住我之前说的，列宁想要跳过一些步骤来建立一个全面的共产主义国家，"新经济政策"就是一个明显的例子。**他认为通过走捷径并引入一点"资本主义"来支撑经济，之后他就可以抛弃资本主义，直接走向共产主义。但这并没有成功，**理解这一点很重要，因为当人们说"共产主义在尝试过的地方都没有成功"时，回应是，嗯，*实际上共产主义从未真正得到过尝试，列宁的例子就是如此。*  +

好的，点击这里获取我的美国大学预修课程欧洲历史复习资料包，它包含了你在课堂上得A以及在五月份的考试中得5分所需要的一切，点击这里继续复习美国大学预修课程欧洲历史第八单元。我们下次再见。  +

'''

== pure

Oh my goodness, the Russian Revolution is upon us. I don't think I'm overselling it when I say that this is a massive honking deal in European history -- a massive honking deal that's going to set us up for major consequences in the rest of this course. So if you're ready to get them brain cows milked Bolshevik style, then let's get to it.

So as with any revolution we've considered in European history, the Russian Revolution was preceded by a few glaring problems, and it was Russia's participation in World War One that blew these problems up to massive proportions. First, there was the problem of political stagnation. Remember from unit six that Russia had experienced the revolution of 1905 because the people began demanding liberal reforms from the turd tsarist government. I won't go into all that here, but the short version is some liberal reforms were enacted, and then they were taken away, and then the revolution of 1905 was largely a failure.

Now by the time World War One rolled around, Nicholas II was the Tsar, and in order to quell further discontent, very much leaned on his military and bureaucracy to bolster his regime. And since Russia had lost millions of men to the war effort by this point, Nicholas made the really dumb decision to go into the field and lead his armies personally. I know that sounds heroic, but he was pretty incompetent, and that led to more discontent with his leadership.

The second problem in Russia was social inequality. Though serfdom was abolished in 1861, the landed elites in many places still maintained a great deal of power. And then add to that the increasing gap between the wealthy and the poor, and people were not happy. And all of this, as I mentioned, was only worsened by Russia's involvement in World War One.

And then the third problem they were contending with was incomplete industrialization. Though significant gains had been made to industrialize Russia in prior decades, World War One showed how deficient they really were. Russian troops didn't have enough guns -- like not enough ammunition -- and some of them lacked adequate clothing and footwear. And these are like the basics that any state is going to need to do well in a war.

And finally, the fourth problem they were enduring in Russia was food and land distribution. Again, despite the abolition of serfdom, most peasants were landless, and food shortages were common. And it was food shortages that led to the first rumblings of the Russian Revolution in March of 1917 in an event that became known as the March Revolution.

The March Revolution: Factory workers, many of whom were women, took to the streets protesting the soaring cost of their staple food items, most notably bread. Czar Nicholas was absent from events -- that is, the domestic turmoil that was unfolding -- while he was busy commanding his own troops in the field of a global war. So he commanded his troops at home to subdue the uprising and then told them to go ahead and start shooting if necessary.

But what Nicholas did not expect was for many of his troops to feel sympathetic to the cause of these women and actually join in their protest, which many of them did. And so with Nicholas rapidly losing control, the Russian legislature known as the Duma gathered and took control of Russia, and on the same day Nicholas abdicated the throne.

Now while this provisional government had control, they faced a lot of difficulties, particularly from the lower class. The provisional government was largely influenced by the interests of the middle class, but they increasingly had to contend with councils that represented working-class interests known as Soviets, who on the majority were made up of socialists.

Now one of the major movers and shakers among the Soviets were the members of the Marxist Social Democratic party, who were not surprisingly devoted to the communist ideals of Karl Marx. In 1903, the party effectively split into two factions. The first, known as the Mensheviks, wanted a socialist state, but they were willing to install a parliamentary democracy in the meantime. The more radical faction on the other hand devoted themselves to a violent overthrow not only of the tsarist regime but also of Western capitalist values.

The Bolsheviks were led by Marx devotee Vladimir Lenin, who in 1917 saw an opportunity for the Bolsheviks to overthrow the provisional government. He publishes the April Theses, which outlined the steps for revolution based on Marxist reasoning. Now to be clear, these steps to communism weren't pure Marx, but they were Marx's ideas filtered through Lenin's own brain. Lenin essentially thought that Marx's prescribed steps toward a socialist state would take too long, and therefore Lenin thought Russia could, you know, skip a few steps.

Anyway, the three slogans of the April Theses summed up Lenin's program succinctly:

Peace, land, and bread. By peace he meant Russia's withdrawal from World War One. By land he meant equal redistribution of land to all. And by bread he meant, you know, bread.
Worker control of production as opposed to elite and bourgeois control.
All power to the Soviets.
And so in November of 1917, Lenin saw his opportunity and led Bolshevik forces to overthrow the provisional government, which turned out to be a surprisingly bloodless and easy task. And at that point, the Bolsheviks -- now renamed the Communists -- were in control of Russia, which later became known as the Soviet Union.

And by March of 1918, Lenin had negotiated a settlement that would remove Russia from World War One by giving up a metric buttload of Russian territory in Eastern Europe. But that didn't matter much to Lenin because the goal was for Soviet communism to spread over the entire world, so you know, a small setback.

So yes, Lenin didn't make good on the promise for peace in the April Theses, but that's about the time Russia itself got involved in the Civil War. You didn't think everybody in Russia was going to welcome the socialist state with fists in the air and smiles on their faces, did you? You're so crazy. No, remember this was a revolution of the working class, and now their interests reign supreme. But in case you forgot, the working class wasn't the only class that existed.

And so because of the bitterness this new forced arrangement caused among the aristocracy and the anti-Leninists, along with several other now marginalized groups, Russia degenerated into Civil War. The anti-communist forces were aided by several Western powers who were none too excited about seeing a communist government installed in Russia. By all counts, this was a force that probably should have overwhelmed the Bolshevik Army.

However, under the leadership of Lenin's right-hand man Leon Trotsky, the Communist Army became phenomenally disciplined and organized. Not only that, Lenin and Trotsky were able to generate Russian nationalist sentiment against these Western interlopers, and that had a way of getting people to fight. The war ended in 1922 with the victory going to Lenin and the Communists, and that's when we officially get the transformation of Russia into the Soviet Union.

However, even before the war was over, Lenin was smart enough to see that Russia was in a bad way economically. So in order to correct these difficulties, Lenin got down and dirty and engaged in some limited capitalistic policies, which became known as the New Economic Policy in 1921. Under this plan, peasant farmers were no longer required to send their produce to the state but rather could sell them on the open market. Also, Lenin permitted private ownership of small businesses and farms, even while he retained control of larger institutions in business.

Okay, now remember what I said before, namely that Lenin wanted to skip steps in order to get a full-on communist state, and the New Economic Policy was a shining example. He thought that by cutting corners and introducing only a smidge of capitalism in order to shore up the economy, that afterward he could chuck it and move right along to communism. But that did not work, and that's important to understand because when people say that communism has never worked where it has been tried, the response is, well, you know, it's never actually been tried, and Lenin is the case in point.

All right, click here to grab my AP Euro review pack, which is everything you need to get an A in your class and a five on your exam in May, and click here to keep reviewing Unit 8 of AP European History. I'll catch you on the flip-flop. I'm out.

'''