
= 8.4 The Treaty of Versailles
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Okay, so World War One is over, and as much of Europe has been reduced to a smoking pile of rubble 废墟, the powers involved in the war have to figure out a peace settlement 和平解决方案 -- a settlement which, as it turns out, was far from peaceful. So let's talk about it, and if you're ready to get them brain cows milked self-determination 自决权 style, let's get to it. +

In order to understand the Versailles Peace Conference 凡尔赛和平会议, you really have to understand that the victorious powers 战胜国 did not at all agree on how peace should be administered 管理. And the big three involved in this tension were the United States, Great Britain, and France. Let's begin with the United States. +

So despite the fact that the U.S. military played a comparatively 相对地 small role in the victory of World War One, U.S. President Woodrow Wilson played a comparatively large role in the peace settlement. And the words you need to associate with Wilson's vision for European peace is idealist 理想主义者. Wilson really wanted to create a perfect world in which nations would no longer go to war with each other, which as we'll see was a little... uh... idealist. And if you liked that joke -- and let's be honest, how could you not -- then you'll love my AP Euro review pack, which does everything you need to get an A in your class and a five on your exam in May. Link in description. +

Now in order to guide the peace settlement according to his vision, Wilson presented what he called the 14 Points 十四点原则, which were to guide the administration of peace. The 14 Points included a provision 条款 for the reduction of arms 军备裁减 among nations, open diplomatic relationships 公开外交关系 rather than secretive treaties 秘密条约, and most important of all, the right of self-determination 自决权 among nations. This idea hit at the heart of long-standing imperial traditions 长期存在的帝国传统 of European power. He said no one else gets to determine the nation's future except that nation themselves, at which point everyone living in Asia, Africa, and the Middle East was like, "Say what now?" and all the European imperial powers were like, "Say what now?" +

And maybe the most ambitious provision of the 14 Points was the creation of a League of Nations 国际联盟, which would be an international body 国际组织 devoted to the prevention of war. Now spoiler alert 剧透警告: the League of Nations was indeed formed, but it was doomed from the beginning. Much to Wilson's chagrin 懊恼, the United States didn't even join. The United States Senate, which was responsible for ratifying 批准 such treaties, squarely 明确地 voted no because they feared that a binding agreement 有约束力的协议 like that would drag the U.S. into a war without congressional approval 国会批准. Add to that, Germany and Russia didn't participate in the league either, and therefore the league really could not succeed. But I get ahead of myself -- we're talking about tensions at the peace conference. +

So that was Wilson's idealism, but apparently Britain and France were not smelling what Wilson was stepping in, you know what I mean? Britain's new Prime Minister David Lloyd George won his office by campaigning on a platform to punish Germany for the war, and he won, so you know, got to punish Germany. France's premier Georges Clemenceau likewise wanted to punish Germany for all the destruction in France, and his main goal was to uphold 维护 the national security of France against future German aggression 侵略. To that end, Clemenceau pushed for Germany to be demilitarized 非军事化, for them to pay reparations 赔款 for the war, and to create a geographic buffer zone 地理缓冲区 in the Rhineland 莱茵兰 to prevent Germany from ever attacking France again. Woodrow Wilson heard all this and he was like, "Guys, this is not the way to peace," which Britain and France responded, "Shut up, Woodrow, go sit in the corner and eat your happy meal." That's what they said. +

And further adding tension to the mix was the strained relationship 紧张关系 with Russia. Remember, they had dropped out of the war to have themselves a communist revolution 共产主义革命, and now that they were very much communist, Western European powers distrusted them. As a result, the powers at the peace table bolstered 支持 the states neighboring Russia like Poland and Czechoslovakia. These states, along with other states like Hungary and Yugoslavia, became known as democratic successor states 民主继承国 because they were newly formed out of the rubble of larger empires. The point is, these states were enlarged and strengthened at Germany and Russia's expense, and that caused a great deal more tension. +

Okay, now there were several different treaties signed at the peace conference, but the one we want to focus on is the peace treaty with Germany. There are two very important provisions in this treaty that you got to remember. First was the War Guilt Clause 战争罪责条款, which placed the entire blame for the war on Germany and Austria too, but mostly on Germany. And the reason that clause is significant is because it humiliated 羞辱 and defeated Germany on the world stage, and was precisely that humiliation that's going to give rise to fascism 法西斯主义 in the decades after the war, and later, you know, World War II. +

The second part of the treaty you need to remember is the provision, as I mentioned earlier, for Germany to pay reparations for the damage done during the war. This also is going to create a significant cause for World War II because the amount of money Germany is going to be forced to pay will end up ruining them economically. Now these two problems within the treaty, along with the mandated German demilitarization 强制德国非军事化 and land cessions 割地, would make it very difficult for the new post-war government known as the Weimar Republic 魏玛共和国 to flourish 繁荣. And despite some early flourishing, the Weimar began to crumble 崩溃 in the 1930s, but we'll save that story for another video. +

Now finally, we need to talk about the actions of the League of Nations and their establishment of the mandate system 委任统治制度. First, you have to understand that the Treaty of Versailles essentially redrew the map of Europe, especially Eastern Europe. The Russian Empire lost significant territory, and the Austro-Hungarian Empire disappeared entirely, as did the Ottoman 奥斯曼帝国. And what's more, several of the new borders drawn for the states that emerged from these broken down empires were drawn by the victorious powers of the war with precisely no consideration for the ethnic minorities 少数民族 who lived in them. In some cases, borders were drawn to split a unified ethnic people, and in other cases, borders were closed around rival ethnic groups. And all of that is going to cause a great deal of trouble. +

But back to the League of Nations and the mandates. In order to gain support for their cause, the allied powers 协约国 in the war promised several Arab nations ruled by the Ottomans that they would recognize their independence. But those European powers had been building worldwide empires for centuries at that point, and the itch to control other people was too tempting not to scratch. And add to that the prodigious 大量的 amount of oil under the sands of those Middle Eastern states, and the opportunity was just too tempting. So under the authority of the League of Nations, France took control of Lebanon and Syria, while Britain took control of Iraq and Palestine. You know, technically France and Britain weren't colonizing these nations -- they were just mandates administered by these countries for the League of Nations -- but you know, if it walks like a duck and it quacks like a duck, it's probably imperialism 帝国主义. +

Okay, click here to keep reviewing for Unit 8 of AP European History, and click here to grab my AP Euro review pack, which does everything you need to get an A in your class and a five on your exam in May. I'll catch you on the flip-flop. I'm out. +

'''

== 中文释义

好的，**第一次世界大战结束了，**欧洲大部分地区沦为一片焦土废墟，**参战各国不得不商讨出一个和平解决方案——但事实证明，这个解决方案远称不上和平。**所以，咱们来聊聊这个话题，如果你准备好以 “民族自决” 的方式获取知识，那就开始吧。 +

要理解"凡尔赛和平会议"（the Versailles Peace Conference），你必须明白，**战胜国在如何实现和平这一问题上, 根本无法达成一致。其中矛盾冲突的三大主要国家是美国（the United States）、英国（Great Britain）和法国（France）。**我们先从美国说起。 +
**
尽管美国军队在"第一次世界大战"的胜利中, 发挥的作用相对较小，但美国总统伍德罗·威尔逊（Woodrow Wilson）在和平解决方案中, 却发挥了相对重要的作用。**说到**威尔逊**对"欧洲和平"的设想，你需要记住 *“理想主义者”* 这个词。**威尔逊真的想创造一个完美的世界，让各国不再相互开战，不过我们之后会发现，这想法有点……呃……太理想化了。**如果你喜欢这个玩笑——说实话，你怎么会不喜欢呢——那么你一定会喜欢我的AP欧洲史复习资料包，它能满足你在课堂上得A、在五月考试中得5分的所有需求。资料链接在简介里哦。 +

为了按照自己的设想指导和平解决方案，**威尔逊提出了他所谓的 “十四点原则”（the 14 Points），用以指导和平管理。“十四点原则” 包括各国裁减军备、##开展"公开外交关系"而非"签订秘密条约"，##最重要的是，##各国拥有民族自决权。这一理念直击欧洲长期以来的帝国主义传统核心。##他表示，除了国家自身，其他任何势力都无权决定这个国家的未来。**听到这话，亚洲、非洲和中东地区的所有人都懵了：“这说的啥？” **所有欧洲帝国主义列强也都惊了：“这怎么行？” **+

或许 “十四点原则” 中最雄心勃勃的条款, 是**#成立"国际联盟"（the League of Nations），这将是一个致力于防止战争的国际组织。#**剧透一下：**国际联盟确实成立了，但从一开始就注定失败。让威尔逊懊恼的是，##美国甚至都没有加入。负责批准此类条约的美国参议院, 明确投了反对票，因为他们担心这样一项具有约束力的协议, 会让美国在"未经国会批准"的情况下卷入战争。此外，德国和俄罗斯也没有加入该联盟，##因此国际联盟根本无法成功。**但我有点说远了——我们正在讨论和平会议上的紧张局势。 +

**这就是威尔逊的理想主义，但显然英国和法国并不买账，**你懂我的意思吧？*英国新任首相大卫·劳合·乔治（David Lloyd George）凭借在竞选时承诺"惩罚德国", 而赢得了职位，既然当选了，那就得惩罚德国。法国总理乔治·克列孟梭（Georges Clemenceau）同样想让德国为"法国遭受的所有破坏"付出代价，他的主要目标是维护法国国家安全，抵御德国未来的侵略。为此，克列孟梭推动德国裁军，要求德国支付战争赔款，并在莱茵兰（Rhineland）地区建立地理缓冲区，以防止德国再次进攻法国。伍德罗·威尔逊听到这些后说：“伙计们，这不是实现和平的方式。*” 而英国和法国回应道：“闭嘴，伍德罗，一边儿待着去，吃你的开心乐园餐吧。” 他们就是这么说的。 +

而与俄罗斯关系的紧张，更是加剧了这种矛盾。记住，俄罗斯为了进行"共产主义革命"而退出了战争，现在它成为了共产主义国家，西欧列强对其充满不信任。因此，**在和平会议上，各国大力扶持波兰（Poland）和捷克斯洛伐克（Czechoslovakia）等俄罗斯周边国家。这些国家，连同匈牙利（Hungary）和南斯拉夫（Yugoslavia）等其他国家，被称为 “民主继承国”，**因为它们是在庞大帝国的废墟上刚刚成立的。关键在于，*这些国家的扩张和加强, 是以牺牲德国和俄罗斯为代价的，这引发了更多的紧张局势。* +

**在"和平会议"上签署了多项不同的条约，但我们要重点关注的是与德国签订的和平条约。**这个条约中有两项非常重要的条款，你必须记住。第一条是 “战争罪责条款”（the War Guilt Clause），该条款将战争的全部责任归咎于德国，奥地利也有份，但主要是德国。这个条款之所以重要，是因为它让德国在世界舞台上蒙羞并遭受重创，而正是这种屈辱，在战后几十年催生了法西斯主义，并在后来引发了第二次世界大战。 +

你需要记住的条约第二部分，正如我之前提到的，是规定: 德国必须为战争期间造成的损失, 支付赔款。这也将成为第二次世界大战爆发的一个重要原因，因为**德国被迫支付的巨额赔款, 最终会使其经济崩溃。**现在，条约中的这两个问题，再加上强制德国裁军和割让土地，将使战后新成立的"魏玛共和国"（the Weimar Republic）很难繁荣发展。**尽管"魏玛共和国"在早期有过一段繁荣时期，但在20世纪30年代开始走向崩溃，**不过这个故事我们留到下次视频再说。 +

最后，我们需要谈谈国际联盟的行动, 以及他们建立的 “委任统治” 制度（the mandate system）。首先，你必须明白，*##《凡尔赛条约》（the Treaty of Versailles）从根本上重新绘制了欧洲地图，尤其是东欧地区。##俄罗斯帝国（the Russian Empire）失去了大片领土，奥匈帝国（the Austro-Hungarian Empire）彻底消失，奥斯曼帝国（the Ottoman）也是如此。#更重要的是，战胜国为这些从衰败帝国中诞生的新国家, 划定的几条新边界，在划定过程中, 完全没有考虑生活在那里的少数民族。在某些情况下，边界划分将原本统一的民族分割开来；在另一些情况下，敌对的民族被划在了同一边界内。而所有这些都将引发巨大的麻烦。#* +

回到"国际联盟"和 “委任统治” 制度。**为了获得支持，战争中的"协约国"曾向"奥斯曼帝国"统治下的几个阿拉伯国家承诺，会承认它们的独立。**但当时欧洲列强已经构建全球帝国长达几个世纪，控制他国的欲望实在难以抗拒。再加上中东国家地下蕴藏着大量石油资源，这个机会实在太诱人了。因此，*在国际联盟的授权下，法国控制了黎巴嫩（Lebanon）和叙利亚（Syria），而英国控制了伊拉克（Iraq）和巴勒斯坦（Palestine）。从技术层面上讲，法国和英国并不是在殖民这些国家——它们只是为国际联盟对这些国家进行 “委任统治”*——但你懂的，这明摆着就是帝国主义那一套。 +

好啦，点击这里继续复习AP欧洲历史第8单元的内容，点击这里获取我的AP欧洲史复习资料包，它能满足你在课堂上得A、在五月考试中得5分的所有需求。回头见！

'''

== pure

Okay, so World War One is over, and as much of Europe has been reduced to a smoking pile of rubble, the powers involved in the war have to figure out a peace settlement -- a settlement which, as it turns out, was far from peaceful. So let's talk about it, and if you're ready to get them brain cows milked self-determination style, let's get to it.

In order to understand the Versailles Peace Conference, you really have to understand that the victorious powers did not at all agree on how peace should be administered. And the big three involved in this tension were the United States, Great Britain, and France. Let's begin with the United States.

So despite the fact that the U.S. military played a comparatively small role in the victory of World War One, U.S. President Woodrow Wilson played a comparatively large role in the peace settlement. And the words you need to associate with Wilson's vision for European peace is idealist. Wilson really wanted to create a perfect world in which nations would no longer go to war with each other, which as we'll see was a little... uh... idealist. And if you liked that joke -- and let's be honest, how could you not -- then you'll love my AP Euro review pack, which does everything you need to get an A in your class and a five on your exam in May. Link in description.

Now in order to guide the peace settlement according to his vision, Wilson presented what he called the 14 Points, which were to guide the administration of peace. The 14 Points included a provision for the reduction of arms among nations, open diplomatic relationships rather than secretive treaties, and most important of all, the right of self-determination among nations. This idea hit at the heart of long-standing imperial traditions of European power. He said no one else gets to determine the nation's future except that nation themselves, at which point everyone living in Asia, Africa, and the Middle East was like, "Say what now?" and all the European imperial powers were like, "Say what now?"

And maybe the most ambitious provision of the 14 Points was the creation of a League of Nations, which would be an international body devoted to the prevention of war. Now spoiler alert: the League of Nations was indeed formed, but it was doomed from the beginning. Much to Wilson's chagrin, the United States didn't even join. The United States Senate, which was responsible for ratifying such treaties, squarely voted no because they feared that a binding agreement like that would drag the U.S. into a war without congressional approval. Add to that, Germany and Russia didn't participate in the league either, and therefore the league really could not succeed. But I get ahead of myself -- we're talking about tensions at the peace conference.

So that was Wilson's idealism, but apparently Britain and France were not smelling what Wilson was stepping in, you know what I mean? Britain's new Prime Minister David Lloyd George won his office by campaigning on a platform to punish Germany for the war, and he won, so you know, got to punish Germany. France's premier Georges Clemenceau likewise wanted to punish Germany for all the destruction in France, and his main goal was to uphold the national security of France against future German aggression. To that end, Clemenceau pushed for Germany to be demilitarized, for them to pay reparations for the war, and to create a geographic buffer zone in the Rhineland to prevent Germany from ever attacking France again. Woodrow Wilson heard all this and he was like, "Guys, this is not the way to peace," which Britain and France responded, "Shut up, Woodrow, go sit in the corner and eat your happy meal." That's what they said.

And further adding tension to the mix was the strained relationship with Russia. Remember, they had dropped out of the war to have themselves a communist revolution, and now that they were very much communist, Western European powers distrusted them. As a result, the powers at the peace table bolstered the states neighboring Russia like Poland and Czechoslovakia. These states, along with other states like Hungary and Yugoslavia, became known as democratic successor states because they were newly formed out of the rubble of larger empires. The point is, these states were enlarged and strengthened at Germany and Russia's expense, and that caused a great deal more tension.

Okay, now there were several different treaties signed at the peace conference, but the one we want to focus on is the peace treaty with Germany. There are two very important provisions in this treaty that you got to remember. First was the War Guilt Clause, which placed the entire blame for the war on Germany and Austria too, but mostly on Germany. And the reason that clause is significant is because it humiliated and defeated Germany on the world stage, and was precisely that humiliation that's going to give rise to fascism in the decades after the war, and later, you know, World War II.

The second part of the treaty you need to remember is the provision, as I mentioned earlier, for Germany to pay reparations for the damage done during the war. This also is going to create a significant cause for World War II because the amount of money Germany is going to be forced to pay will end up ruining them economically. Now these two problems within the treaty, along with the mandated German demilitarization and land cessions, would make it very difficult for the new post-war government known as the Weimar Republic to flourish. And despite some early flourishing, the Weimar began to crumble in the 1930s, but we'll save that story for another video.

Now finally, we need to talk about the actions of the League of Nations and their establishment of the mandate system. First, you have to understand that the Treaty of Versailles essentially redrew the map of Europe, especially Eastern Europe. The Russian Empire lost significant territory, and the Austro-Hungarian Empire disappeared entirely, as did the Ottoman. And what's more, several of the new borders drawn for the states that emerged from these broken down empires were drawn by the victorious powers of the war with precisely no consideration for the ethnic minorities who lived in them. In some cases, borders were drawn to split a unified ethnic people, and in other cases, borders were closed around rival ethnic groups. And all of that is going to cause a great deal of trouble.

But back to the League of Nations and the mandates. In order to gain support for their cause, the allied powers in the war promised several Arab nations ruled by the Ottomans that they would recognize their independence. But those European powers had been building worldwide empires for centuries at that point, and the itch to control other people was too tempting not to scratch. And add to that the prodigious amount of oil under the sands of those Middle Eastern states, and the opportunity was just too tempting. So under the authority of the League of Nations, France took control of Lebanon and Syria, while Britain took control of Iraq and Palestine. You know, technically France and Britain weren't colonizing these nations -- they were just mandates administered by these countries for the League of Nations -- but you know, if it walks like a duck and it quacks like a duck, it's probably imperialism.

Okay, click here to keep reviewing for Unit 8 of AP European History, and click here to grab my AP Euro review pack, which does everything you need to get an A in your class and a five on your exam in May. I'll catch you on the flip-flop. I'm out.

'''