
= 8.5 The GLOBAL Economic Crisis Between World Wars
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

So World War One 第一次世界大战 is finally 最终；终于 over, and we know that there's another world war coming in about 30 years. But at least in those interwar 两次世界大战之间的 years, everyone in Europe can rest 休息；歇息 and live prosperously 富裕地；繁荣地；成功地. And I'm getting word that that is in fact not how the interwar years played out 展开；发生；发展. In fact, Europeans suffered profoundly 深刻地；极大地 because of a worldwide 遍及全球的；全世界的 economic 经济的；经济上的 crisis 危机；紧要关头. That's a bummer 令人失望的事；令人不快的局面. Anyway, I reckon 认为；估计；猜想 we ought to 应该；应当 talk about it. So if you're ready to get them brain cows milked 挤奶；开发（比喻用法，意为“榨出想法”）, let's get to it. +

Okay, now things didn't go straight down the toilet 一落千丈；彻底失败 after World War One. There were actually a few years when Europe seemed to be recovering from the war and all was well. We call that in the Treaty of Versailles 凡尔赛条约, which ended World War One, that Germany was made to pay for all the damage caused in the war, which is to say they had to pay reparations 赔款；赔偿. First year after the war, Germany paid what they owed, but the next year they were like, "Yeah, we broke." The German policy from that point on was just to print paper money like crazy, a situation which led them into severe hyperinflation 恶性通货膨胀. +

You know, you don't need to know these numbers, but just to give you a taste of how bad it got: in 1914, the first year of the war, one dollar was equal to about four German marks. By November of 1923, one dollar was worth 4.2 trillion marks. To which I say, "Hey, I'm Larry. I thought you said all was well for a few years after the war. That sounds pretty bleak 暗淡的；不景气的." Well, my dear interlocutor 对话者；谈话者, by 1924, realizing the German situation was deteriorating 恶化；变坏 profoundly 深刻地；严重地, an international commission cobbled together 拼凑；临时拼凑出 something called the Dawes Plan 道威斯计划, which did two very significant things. First, it decreed 裁定；判决 that Germany pay only the reparations it could afford to pay, and second, it invested a metric buttload of U.S. dollars into German recovery. And all this work to keep Germany from imploding 崩溃；瓦解 actually led them to some economic stability. +

Oh, by the way, if you need help studying for your class exams or your national AP Euro exam, then check out 查看；检查 all the study materials I have in my AP Euro review pack, which is linked in the description. Anyway, as a result, Europe experienced a season of upward recovery and prosperity 繁荣；兴旺. It may be the chief illustration 例证；实例 of how good everyone in Europe was feeling during this time was the signing of the Kellogg-Briand Pact 凯洛格-白里安公约, which essentially renounced 放弃；摒弃 war as an instrument of foreign policy. "Everything is going great. We're never gonna go to war again." You want to tell them, or should I? +

So if everything is going so great, how did it all fall apart 崩溃；瓦解? Well, I've got four reasons that European economic recovery gave way to 让位于；被……取代 the Great Depression 大萧条. First was the problem of war debt. I already mentioned Germany's struggle with war debt, but all major powers involved in the war had borrowed money to finance 为……提供资金 their participation in World War One, and that became a significant economic burden. Second was the problem of nationalistic tariff 关税 policies. Remember that a tariff is a tax on imported goods. Many nations put high tariffs in place in order to protect their own domestic industries, but in cutting off 切断；中断 the flow of free trade among nations, unemployment rose significantly. +

The third problem was overproduction 生产过剩. Since World War One was a total war 全面战争, many industries in any given state ramped up 增加；提高 their production to meet demand for wartime necessity. But when the war ended in 1918, farmers -- and you know this was especially true for farmers -- they didn't decrease their production, and thus saturated 使饱和；使充满 the market with goods for which there were no buyers. And that reality drove prices way down and caused significant economic suffering in the farming industry before the great economic collapse arrived. +

Now the fourth problem was speculation 投机；投机活动. This was a problem that happened in the United States but soon had global implications 影响；后果. For the most part, the 1920s was a prosperous decade for the United States, and as a result, many people borrowed money to buy into the stock market, a practice known as speculation. And borrowing that money to pay for stocks was a good bet 赌注；打赌 since stock prices were continually rising, which meant that whatever you borrowed, you could pay back. But then something disastrous 灾难性的；悲惨的 happened in 1929 that flushed the world economy right down the toilet. +

Now remember, much of the economic recovery and prosperity Europe was experiencing from 1924 to 1929 was due in no small part to 很大程度上归因于 monetary 货币的；金融的 investment from the United States. There was already trouble on the horizon 在不久的将来 in the late '20s when American investors began diverting 转移；转向 money from European recovery -- and especially German recovery -- to invest in the U.S. stock market. But then in October of 1929, for many interrelated 相互关联的 reasons, the U.S. stock market crashed. And when the market didn't rebound 反弹；回升 like everyone thought it would, the Great Depression officially began in the United States. But since the U.S. all of a sudden lacked the extra money to invest in European recovery, the Great Depression soon spread to Europe as well. +

As economies collapsed across Europe, unemployment rose significantly. By 1932, 25 percent of the labor force in Great Britain was unable to find work, and almost 40 percent of German workers could find no job. And in case you're not fluent in unemployment statistics, those are gigantic 巨大的；庞大的 numbers. Now interestingly, those numbers were more skewed toward 偏向；倾斜 male workers, but women were in general more able to find work in low-paying jobs than men were. So in some cases, this led to a reversal 颠倒；反转 of the domestic gender roles -- a reversal that many men resented 怨恨；愤恨. +

Now Western democracies did their best to remedy 补救；纠正 this problem. One of the major economic innovations 创新；革新 during this period came from British economist John Maynard Keynes. The Keynesian system of economics argued that government spending is the mechanism 机制；机理 which will increase consumer demand and thus lift an economy out of a depression. And that's the key to this system: the government is responsible for spending money in order to correct the economy, and it should do so even if it racks up 积累；累计 ginormous 巨大的；庞大的 budget deficits 预算赤字. Now this system did not take hold 确立；生根 in Keynes's native Britain, but it certainly did in the United States under the leadership of President Franklin Roosevelt. There, the federal government spent a metric buttload of money to put Americans to work on government projects. Historians debate how effective these policies were in rescuing the economy, but the point here is that this was one new way of thinking about government involvement in economics in order to solve the problem of the Great Depression. +

All right, another method of dealing with the effects of the Great Depression was through cooperative social action, and this happened mainly in the Scandinavian states. In the decades before World War One, socialist parties had gained an increasing amount of influence. In the years between the world wars, socialists came to power in the Scandinavian states of Sweden, Norway, and Finland. These socialist governments created favorable conditions for the development of cooperative enterprises 合作企业. These were kind of a middle way between communism and capitalism -- or maybe better to say a kind of mixture between the two -- that sought to avoid the pitfalls 陷阱；隐患 of both. And in addition to that, Scandinavian states greatly expanded their welfare state 福利国家, which was paid for by higher taxes and created social safety nets 社会保障体系 for their citizens. +

There were also political alliances 联盟；同盟 that formed to respond to the ravages 破坏；蹂躏 of the Great Depression. In Great Britain, the national government was an alliance between the conservative and liberal parties who, if you'll remember, had previously been bitter enemies. Now they didn't really stop hating each other, but in the 1930s they united in the national government to cooperate on solving the unemployment problems and other national crises. And to be fair, they were somewhat successful. +

Another political alliance that arose was the Popular Front 人民阵线 in France. The few years following the war, France did better than anyone else, but by 1932 the effects of the Great Depression hit them as well. And into the economic and political chaos, the leftist parties of France joined together and created the Popular Front government. In this government, you had a mixture of socialists and champions 拥护者；捍卫者 of democracy, but the one thing that they could agree on is that France could not be taken over by right-wing folks who were advocating for fascist policy. While the Popular Front did make some gains, they ultimately failed to solve France's economic crisis, and France was thus left vulnerable 易受伤害的；脆弱的 to deal with Germany to the east -- on which more in the next video. There's also a Popular Front government in Spain who had similar goals, but that's all you need to know for now. +

Okay, click here to keep reviewing for Unit 8 of AP European History. Click here to get my AP Euro review pack, which will help you get an A in your class and a five on your exam in May. I'll catch you on the flip-flop. Heimler out. +


'''

== 中文释义

**第一次世界大战终于结束了，我们知道大约30年后还会爆发另一场世界大战。**但至少在两次世界大战之间的那些年里，欧洲人可以休养生息，过上富足的生活。不过我得到的消息显示，两次世界大战之间的那些年并非如此。事实上，**由于一场全球性的经济危机，欧洲人遭受了深重的苦难。**这太糟糕了。不管怎样，我觉得我们应该聊聊这个话题。所以，如果你准备好获取知识，那就开始吧。 +

一战结束后，情况并没有立刻变得一团糟。实际上，有那么几年，欧洲似乎正在从战争中恢复，一切都还不错。我们在结束第一次世界大战的《凡尔赛条约》（the Treaty of Versailles）中规定，德国必须为战争造成的所有破坏进行赔偿，也就是说，他们必须支付战争赔款。*战后第一年，德国支付了欠款，但第二年他们就表示：“我们破产了”。从那时起，德国的政策就是疯狂印钞，这导致他们陷入了严重的恶性通货膨胀。* +

你不需要记住这些数字，但我可以让你感受一下情况有多糟糕：1914年，战争的第一年，1美元大约兑换4德国马克（German marks）。到1923年11月，1美元可兑换4.2万亿马克。这时我要说：“嘿，我是拉里。你之前不是说战后有几年一切都还不错吗？这听起来可太惨淡了。” 好吧，亲爱的听众，到了**1924年，由于意识到德国的情况正在急剧恶化，一个国际委员会拼凑出了一个名为 “道威斯计划”（the Dawes Plan）的方案，该方案做了两件非常重要的事情。第一，它规定德国只需支付其有能力支付的赔款；第二，它向德国的经济复苏投入了大量美元。所有这些防止德国经济崩溃的努力，实际上使德国的经济实现了一定程度的稳定。** +

哦，顺便说一下，如果你在准备课堂考试或全国AP欧洲史考试时需要帮助，那就看看我AP欧洲史复习资料包里的所有学习材料吧，链接在简介里。不管怎样，结果是欧洲经历了一段经济复苏和繁荣的时期。这一时期欧洲人良好状态的主要例证，或许就是**《凯洛格 - 白里安公约》（the Kellogg-Briand Pact）的签署，该公约实质上宣布"放弃将战争作为外交政策的手段"。**“一切都进展得很顺利。我们再也不会打仗了。” 你想告诉他们真相，还是我来说？ +

那么，*如果一切都那么好，怎么最后又全搞砸了呢？嗯，欧洲"经济复苏"最终让位于 “大萧条”*（the Great Depression），我认为**有四个原因。第一个是战争债务问题。**我已经提到过德国在战争债务上的困境，但**所有参与战争的主要国家, 都曾借款来为其一战参战提供资金，这成了一个巨大的经济负担。**第二个**是民族主义关税政策问题。**记住，关税（tariff）是对进口商品征收的税。*许多国家设置高关税以保护本国国内产业，但在切断国家间自由贸易流动的同时，失业率也大幅上升。* +

第三个问题是**生产过剩。**由于第一次世界大战是一场全面战争，许多国家的众多产业都加大生产以满足战时需求。但当1918年战争结束时，农民——尤其是农民——他们并没有减少产量，因此市场上充斥着无人购买的商品。在经济大崩溃来临之前，这种情况导致价格大幅下跌，给农业带来了严重的经济困境。 +

第四个问题是**投机。**这个问题首先出现在美国，但很快就产生了全球性影响。在很大程度上，*20世纪20年代对美国来说是繁荣的十年，因此，许多人借钱投资股市，这种做法被称为投机*（speculation）。由于股票价格不断上涨，借钱买股票是个不错的选择，这意味着你借的任何钱都能还上。但1929年，一些灾难性的事情发生了，世界经济因此一落千丈。 +

请记住，**#1924年至1929年欧洲经历的经济复苏和繁荣，在很大程度上得益于美国的资金投入。20世纪20年代后期，美国投资者开始将资金, 从欧洲的经济复苏项目#——尤其是德国的复苏项目——#转移，转而投资美国股市，#**那时危机就已经初现端倪。但在1929年10月，由于诸多相互关联的原因，**美国股市崩盘。**当市场没有像所有人预期的那样反弹时，美国正式进入大萧条时期。但**#由于美国突然没有多余资金投资欧洲的经济复苏，大萧条很快也蔓延到了欧洲。#** +

随着欧洲各地经济崩溃，失业率大幅上升。到1932年，英国25%的劳动力找不到工作，德国近40%的工人失业。如果你不太了解失业统计数据，那我告诉你，这些数字非常庞大。有趣的是，这些数字更多地偏向男性工人，但总体而言，女性比男性更容易找到低薪工作。所以在某些情况下，这导致了家庭中性别角色的颠倒——这种颠倒让许多男性感到不满。 +

西方民主国家尽最大努力解决这个问题。这一时期的一项重大经济创新, 来自英国经济学家约翰·梅纳德·凯恩斯（John Maynard Keynes）。**"凯恩斯主义经济学"体系认为，政府支出是增加消费者需求、从而使经济摆脱萧条的机制。**这个体系的关键在于：**政府有责任通过支出资金来纠正经济，即使这会导致巨额预算赤字也应如此。**这个体系在凯恩斯的祖国英国并未得到推行，但在美国富兰克林·罗斯福（Franklin Roosevelt）总统的领导下, 却得到了实施。在那里，**联邦政府投入大量资金，让美国人参与政府项目工作。**历史学家们对于这些政策在拯救经济方面的有效性存在争议，但重点是，*这是一种关于"政府干预经济"以解决大萧条问题的新思路。* +

好吧，**应对大萧条影响的另一种方法, 是通过合作性的社会行动，这主要发生在斯堪的纳维亚国家。**在第一次世界大战前的几十年里，社会党获得了越来越大的影响力。在两次世界大战之间的几年里，社会主义者在瑞典、挪威和芬兰这些"斯堪的纳维亚国家"掌权。这些社会主义政府为"合作企业"的发展创造了有利条件。**这是一种介于共产主义和资本主义之间的中间道路——或者更确切地说，是两者的某种混合——旨在避免两者的弊端。**除此之外，*斯堪的纳维亚国家大幅扩大了福利国家制度，这通过提高税收来提供资金，为其公民建立了社会保障体系。* +

为应对大萧条的破坏，还形成了一些政治联盟。在英国，国家政府是保守党和自由党之间的联盟，如果你还记得的话，它们之前可是死对头。现在它们并没有停止相互厌恶，但在20世纪30年代，它们在国家政府中联合起来，合作解决失业问题和其他国家危机。公平地说，它们取得了一定的成功。 +

另一个出现的政治联盟是法国的 “人民阵线”（the Popular Front）。战后的几年里，法国的情况比其他任何国家都好，但到了1932年，大萧条的影响也波及到了法国。**在经济和政治混乱中，法国的"左翼政党"联合起来，成立了"人民阵线政府"。在这个政府中，有社会主义者和民主拥护者，但他们唯一能达成共识的是，法国不能被鼓吹"法西斯政策"的右翼分子掌控 (意识形态的三国鼎立: 民主派, 社会主义派, 法西斯派. 彼此看不顺眼, 要消灭对方)。虽然人民阵线取得了一些成果，但最终未能解决法国的经济危机，**因此法国在应对东部德国的问题上变得十分脆弱——我们将在下一个视频中详细探讨这个问题。西班牙也有一个有着类似目标的人民阵线政府，但目前你知道这些就够了。 +

好的，点击这里继续复习AP欧洲历史第8单元。点击这里获取我的AP欧洲史复习资料包，它将帮助你在课堂上得A，在五月的考试中得5分。回头见。海姆勒下线。 +

'''

== pure

So World War One is finally over, and we know that there's another world war coming in about 30 years. But at least in those interwar years, everyone in Europe can rest and live prosperously. And I'm getting word that that is in fact not how the interwar years played out. In fact, Europeans suffered profoundly because of a worldwide economic crisis. That's a bummer. Anyway, I reckon we ought to talk about it. So if you're ready to get them brain cows milked, let's get to it.

Okay, now things didn't go straight down the toilet after World War One. There were actually a few years when Europe seemed to be recovering from the war and all was well. We call that in the Treaty of Versailles, which ended World War One, that Germany was made to pay for all the damage caused in the war, which is to say they had to pay reparations. First year after the war, Germany paid what they owed, but the next year they were like, "Yeah, we broke." The German policy from that point on was just to print paper money like crazy, a situation which led them into severe hyperinflation.

You know, you don't need to know these numbers, but just to give you a taste of how bad it got: in 1914, the first year of the war, one dollar was equal to about four German marks. By November of 1923, one dollar was worth 4.2 trillion marks. To which I say, "Hey, I'm Larry. I thought you said all was well for a few years after the war. That sounds pretty bleak." Well, my dear interlocutor, by 1924, realizing the German situation was deteriorating profoundly, an international commission cobbled together something called the Dawes Plan, which did two very significant things. First, it decreed that Germany pay only the reparations it could afford to pay, and second, it invested a metric buttload of U.S. dollars into German recovery. And all this work to keep Germany from imploding actually led them to some economic stability.

Oh, by the way, if you need help studying for your class exams or your national AP Euro exam, then check out all the study materials I have in my AP Euro review pack, which is linked in the description. Anyway, as a result, Europe experienced a season of upward recovery and prosperity. It may be the chief illustration of how good everyone in Europe was feeling during this time was the signing of the Kellogg-Briand Pact, which essentially renounced war as an instrument of foreign policy. "Everything is going great. We're never gonna go to war again." You want to tell them, or should I?

So if everything is going so great, how did it all fall apart? Well, I've got four reasons that European economic recovery gave way to the Great Depression. First was the problem of war debt. I already mentioned Germany's struggle with war debt, but all major powers involved in the war had borrowed money to finance their participation in World War One, and that became a significant economic burden. Second was the problem of nationalistic tariff policies. Remember that a tariff is a tax on imported goods. Many nations put high tariffs in place in order to protect their own domestic industries, but in cutting off the flow of free trade among nations, unemployment rose significantly.

The third problem was overproduction. Since World War One was a total war, many industries in any given state ramped up their production to meet demand for wartime necessity. But when the war ended in 1918, farmers -- and you know this was especially true for farmers -- they didn't decrease their production, and thus saturated the market with goods for which there were no buyers. And that reality drove prices way down and caused significant economic suffering in the farming industry before the great economic collapse arrived.

Now the fourth problem was speculation. This was a problem that happened in the United States but soon had global implications. For the most part, the 1920s was a prosperous decade for the United States, and as a result, many people borrowed money to buy into the stock market, a practice known as speculation. And borrowing that money to pay for stocks was a good bet since stock prices were continually rising, which meant that whatever you borrowed, you could pay back. But then something disastrous happened in 1929 that flushed the world economy right down the toilet.

Now remember, much of the economic recovery and prosperity Europe was experiencing from 1924 to 1929 was due in no small part to monetary investment from the United States. There was already trouble on the horizon in the late '20s when American investors began diverting money from European recovery -- and especially German recovery -- to invest in the U.S. stock market. But then in October of 1929, for many interrelated reasons, the U.S. stock market crashed. And when the market didn't rebound like everyone thought it would, the Great Depression officially began in the United States. But since the U.S. all of a sudden lacked the extra money to invest in European recovery, the Great Depression soon spread to Europe as well.

As economies collapsed across Europe, unemployment rose significantly. By 1932, 25 percent of the labor force in Great Britain was unable to find work, and almost 40 percent of German workers could find no job. And in case you're not fluent in unemployment statistics, those are gigantic numbers. Now interestingly, those numbers were more skewed toward male workers, but women were in general more able to find work in low-paying jobs than men were. So in some cases, this led to a reversal of the domestic gender roles -- a reversal that many men resented.

Now Western democracies did their best to remedy this problem. One of the major economic innovations during this period came from British economist John Maynard Keynes. The Keynesian system of economics argued that government spending is the mechanism which will increase consumer demand and thus lift an economy out of a depression. And that's the key to this system: the government is responsible for spending money in order to correct the economy, and it should do so even if it racks up ginormous budget deficits. Now this system did not take hold in Keynes's native Britain, but it certainly did in the United States under the leadership of President Franklin Roosevelt. There, the federal government spent a metric buttload of money to put Americans to work on government projects. Historians debate how effective these policies were in rescuing the economy, but the point here is that this was one new way of thinking about government involvement in economics in order to solve the problem of the Great Depression.

All right, another method of dealing with the effects of the Great Depression was through cooperative social action, and this happened mainly in the Scandinavian states. In the decades before World War One, socialist parties had gained an increasing amount of influence. In the years between the world wars, socialists came to power in the Scandinavian states of Sweden, Norway, and Finland. These socialist governments created favorable conditions for the development of cooperative enterprises. These were kind of a middle way between communism and capitalism -- or maybe better to say a kind of mixture between the two -- that sought to avoid the pitfalls of both. And in addition to that, Scandinavian states greatly expanded their welfare state, which was paid for by higher taxes and created social safety nets for their citizens.

There were also political alliances that formed to respond to the ravages of the Great Depression. In Great Britain, the national government was an alliance between the conservative and liberal parties who, if you'll remember, had previously been bitter enemies. Now they didn't really stop hating each other, but in the 1930s they united in the national government to cooperate on solving the unemployment problems and other national crises. And to be fair, they were somewhat successful.

Another political alliance that arose was the Popular Front in France. The few years following the war, France did better than anyone else, but by 1932 the effects of the Great Depression hit them as well. And into the economic and political chaos, the leftist parties of France joined together and created the Popular Front government. In this government, you had a mixture of socialists and champions of democracy, but the one thing that they could agree on is that France could not be taken over by right-wing folks who were advocating for fascist policy. While the Popular Front did make some gains, they ultimately failed to solve France's economic crisis, and France was thus left vulnerable to deal with Germany to the east -- on which more in the next video. There's also a Popular Front government in Spain who had similar goals, but that's all you need to know for now.

Okay, click here to keep reviewing for Unit 8 of AP European History. Click here to get my AP Euro review pack, which will help you get an A in your class and a five on your exam in May. I'll catch you on the flip-flop. Heimler out.

'''