
= 8.7 CAUSES of World War II
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Now I haven't mentioned in my previous videos, but World War One was first known as the Great War or the war to end all wars. But the fact that we know it as World War One makes the spoiler 剧透；泄露 pretty obvious -- there was in fact a World War II. Now we're going to deal with that war in the next video, but in this one, let's look at the factors that made the war to end all wars just an appetizer 开胃菜；前菜 to the next great one. So if you're ready to get them brain cows milked appeasement 绥靖；姑息 style, then let's get to it. +

Coming out of World War One, there were a lot of complex factors that allowed fascist states both to re-arm 重新武装 themselves and expand their terror. Now remember, Germany was on the losing side of World War One, and part of the Treaty of Versailles 凡尔赛条约 mandated 强制；命令 that Germany demilitarized 非军事化 and another part shrank 缩小；缩减 their territory. So reversing 推翻；撤销 either of those realities was a violation 违反；违背 of the treaty, and if Germany violated that treaty, it would likely lead to another war. And yet, under the leadership of Adolf Hitler, Germany significantly rearmed itself and began conquering 征服；占领 territory like a madman. So how did he do it? +

The first reason this could happen was because of the policy of appeasement towards Germany. Britain and France were the main appeasers 绥靖者. As I mentioned in the video on World War One, the human and capital cost of that war was staggering 令人震惊的；难以想象的 to all involved. So when Hitler began publicly re-arming Germany in 1935 and taking territory thereafter, Britain and France were not too eager to start another war to stop him. The policy of appeasement essentially became: let Hitler do whatever he wants because we're not destroying ourselves in another cataclysmic 灾难性的 battle yet again. In other words, Hitler faced no consequences for breaking the provisions 条款；规定 in the Treaty of Versailles that kept Germany powerless in the interwar period. +

Now the second reason Germany was able to re-arm and start expanding was because of the growing antagonism 对抗；敌对 and distrust between the Soviet Union and the Western European states slash 斜线；和 the United States. Recall 回想；回忆起 that the Soviet Union was an authoritarian 独裁的；专制的 communist state, and that was diametrically opposed to 与……截然相反 the U.S. and Western Europe, which represented capitalist democracy 资本主义民主. We'll get more into that antagonism and distrust in Unit 9 during the Cold War, but for now, all you have to know is that these two entities 实体；实体组织 were so opposed to one another that they could not work together to present a united front 统一战线 against expanding fascist states. And I say states plural 复数的 because even though I've only been referring to Germany, fascist Italy was expanding too. And you know, let's talk about that. +

Okay, and here we need to talk about the specific actions that led to World War II. First, let's get specific with territorial expansion 领土扩张. In 1935, Italy invaded Ethiopia, which happened to be only one of two African states that had never been colonized by Europeans. If you've been around since we talked about the Scramble for Africa 非洲争夺战, then you know that is a big deal. Anyway, Italy was ultimately successful in conquering Ethiopia, and that victory made Britain a little sweaty because it threatened their control of the Suez Canal 苏伊士运河 in Egypt. And remember, nobody wants to start another war, and so the only reprisal 报复；复仇 Mussolini faced for this attack was a few lame 无力的；无价值的 economic sanctions 经济制裁 imposed by the League of Nations. +

But Germany's territorial expansion made Italy's efforts look like child's play 轻而易举的事；儿戏. Hitler began by re-militarizing the Rhineland 莱茵兰, which is this little strip of land right here. This act was kind of like an experiment for Hitler. The Treaty of Versailles specifically prohibited 禁止；阻止 German armament 武装；军备 of this territory, so Hitler wanted to see if Britain and France were up for fighting. So in 1936, Hitler sent troops to occupy the Rhineland, and because of the policy of appeasement that I mentioned earlier, all he heard from Britain and France was, "Hitler, stop." Upon seeing that Britain and France would do nothing to enforce 执行；实施 the treaty, Hitler was like, "Oh, it's on." +

Next, in 1938, Hitler annexed 吞并；兼并 Austria, a move known as Anschluss 德奥合并 on account of 因为；由于 all the Germans living in Austria. And once German troops came into Austria, they decided to hold a little vote to hear from the Austrians whether or not they wanted to be absorbed into the German Reich. And wouldn't you know it, like 99% of Austrians voted yes to the annexation. Hold on, you're trying to tell me that an independent nation in the age of self-determination 自决权 decided by a margin of 99% that they wanted to be taken over? Does that smell funky 可疑的；有问题的 to anybody else? I mean, think about it: when have you ever heard of 99% of people in any country in any age in any part of the world agreeing on something? That does not happen. +

So that vote did indeed smell funky, and here's why. First of all, look at this ballot 选票；投票. You don't even have to speak German to know that the "yes" circle is a little out of proportion to 与……不成比例 the "no" circle. Second, this was not a secret ballot. In order to vote, you had to hand it to a German military officer who would then place it in the box. So it was a rigged 操纵的；作弊的 vote without a doubt. But Hitler was successful nonetheless 尽管如此；仍然. And then he went on to take over the Sudetenland 苏台德地区 and a few states in Czechoslovakia 捷克斯洛伐克 as well. And in all of this, Britain and France essentially did nothing to stop it. But what they did do is gather at a meeting and create the Munich Agreement 慕尼黑协定, in which Britain and France agreed to all of Hitler's territorial demands but made him promise that he would take no more. And Hitler was like, "Yeah, sure." +

Additionally, Hitler made peace with the Soviet Union in something called the Nazi-Soviet Non-Aggression Pact 纳粹-苏联互不侵犯条约, in which they agreed to two stipulations 条款；规定: first, neither would attack the other for a decade following the agreement; second, they agreed to split Poland between the two powers. And that second stipulation gave Hitler the confidence to invade Poland, knowing that the Soviet Union would not oppose him. In 1939, that is exactly what Hitler did. And why wouldn't he? Even though he committed in the Munich Agreement that he would not seek any more territory, he had been taking territory all over Europe and no one was stopping him. So why would it be any different in Poland? +

But here's where I tell you that it was different in Poland, because that invasion was the last straw 最后一根稻草；忍无可忍的事 for Britain and France. So as a result of that invasion, Britain and France declared war on Germany, and that is how you get World War II. +

Okay, click here to keep reviewing for Unit 8 of AP Euro, and click here to grab my AP Euro review pack, which is going to help you get an A in your class and a five on your exam in May. I'll catch you on the flip-flop. I'm out. +

'''

== 中文释义

在我之前的视频里我没提过，但第一次世界大战最初被称为“大战”或者“终结所有战争的战争”。但我们现在称它为“第一次世界大战”，这就很明显地剧透了 —— 实际上还有第二次世界大战（World War II）。我们将在下一个视频中探讨第二次世界大战，但在这个视频里，咱们来看看是什么因素让这场“终结所有战争的战争”仅仅成了下一场大战的开胃菜。所以，如果你准备好以“绥靖政策”的视角来获取知识，那就开始吧。 +

第一次世界大战结束后，有许多复杂的因素, 使得法西斯国家得以重新武装并扩张其恐怖统治。记住，德国是第一次世界大战的战败国，*《凡尔赛条约》*（Treaty of Versailles）的部分条款强制要求德国裁军，另一部分条款则使其领土缩减。所以，**改变这些既定事实中的任何一个, 都算是违反条约，如果德国违反条约，很可能会引发另一场战争。然而，在阿道夫·希特勒（Adolf Hitler）的领导下，德国大力重整军备，开始像疯子一样占领领土。**那他是怎么做到的呢？ +

*这种情况发生的第一个原因, 是对德国的"绥靖政策"*（policy of appeasement）。**英国和法国是主要推行"绥靖政策"的国家。**正如我在关于第一次世界大战的视频中提到的，那场战争给所有参战国带来的人员和资本损失是惊人的。所以当希特勒在1935年开始公开为德国重新武装，并在此后占领领土时，英国和法国并不太愿意发动另一场战争来阻止他。绥靖政策本质上变成了：随希特勒怎么做吧，因为我们不想再在另一场灾难性的战争中自我毁灭。换句话说，**希特勒违反《凡尔赛条约》中那些**在两次世界大战之间**削弱德国的条款，却没有受到任何惩罚。** +

**德国能够重新武装并开始扩张的第二个原因, 是"苏联"与"西欧国家以及美国"之间日益加剧的敌对和不信任。**回想一下，苏联是一个专制的共产主义国家，这与代表"资本主义民主"的美国和西欧截然对立。我们将在第9单元冷战时期的内容中, 深入探讨这种敌对和不信任，但现在你只需要知道，**这两个阵营彼此对立，无法携手组成统一战线来对抗扩张的法西斯国家。**我说“国家”是复数形式，因为尽管我一直只提到德国，但法西斯意大利也在扩张。我们来聊聊这个。 +

好，现在我们需要谈谈**导致第二次世界大战的具体事件。**首先，我们具体说说领土扩张。**1935年，意大利入侵埃塞俄比亚（Ethiopia），埃塞俄比亚恰好是仅有的两个从未被欧洲人殖民过的非洲国家之一。**如果你从我们讨论“瓜分非洲”（Scramble for Africa）的时候就在关注的话，就会知道这是一件大事。总之，**#意大利最终成功征服了埃塞俄比亚，这次胜利让英国有些不安，因为这威胁到了他们对埃及苏伊士运河（Suez Canal）的控制。#**而且记住，*没人想再发动一场战争，所以墨索里尼（Mussolini）因这次侵略行为所面临的唯一报复，只是"国际联盟"（League of Nations）实施的一些无力的经济制裁。* +

但德国的领土扩张相比之下，让意大利的所作所为就像小孩子过家家。**希特勒首先让莱茵兰（Rhineland）重新军事化，**就是这边的这条狭长地带。**这一举动对希特勒来说有点像一次试探。《凡尔赛条约》明确禁止德国在该地区驻军，所以希特勒想看看英国和法国是否会为此开战。于是在1936年，希特勒派兵占领莱茵兰，**由于我之前提到的绥靖政策，他只听到英国和法国说：“希特勒，住手。” **看到英国和法国不会采取任何行动来执行条约，**希特勒心想：“哦，机会来了。” +

接下来，1938年，**希特勒吞并了奥地利（Austria），由于奥地利有很多德国人，这一行动被称为“德奥合并”（Anschluss）。一旦德国军队进入奥地利，他们决定举行一次小投票，询问奥地利人是否愿意被并入德意志帝国（German Reich）。你猜怎么着，大概99%的奥地利人投票赞成吞并。**等一下，你是想告诉我，**在民族自决的时代，一个独立国家以99%的比例决定被接管？**其他人不觉得这很可疑吗？我是说，*想想看：你什么时候听说过世界上任何时代、任何国家的99%的人能在某件事上达成一致？这根本不可能。* +
所以这次投票确实有问题，原因如下。首先，**看看这张选票。你甚至不需要懂德语，就能看出“赞成”的圈比“反对”的圈大得不成比例。**其次，这不是无记名投票。**为了投票，你必须把选票交给一名德国军官，然后由他放入投票箱。所以这无疑是一场被操纵的投票。**但不管怎样，*希特勒成功了。* +

*然后他又继续占领了苏台德地区（Sudetenland）和捷克斯洛伐克（Czechoslovakia）的几个州。在这一系列事件中，英国和法国基本上没有采取任何行动来阻止。但他们做的是召开会议并签署了《慕尼黑协定》（Munich Agreement），在协定中，英国和法国同意了希特勒所有的领土要求，但让他承诺不再索取更多领土。希特勒说：“当然可以。”* +

此外，*希特勒与苏联签署了《纳粹 - 苏联互不侵犯条约》*（Nazi-Soviet Non-Aggression Pact），**达成了两项规定：第一，双方在条约签署后的十年内, 互不攻击；第二，他们同意瓜分波兰（Poland）。**第二项规定让希特勒有了入侵波兰的底气，因为他知道苏联不会反对。1939年，希特勒正是这么做的。他为什么不呢？*尽管他在《慕尼黑协定》中承诺不再寻求更多领土，但他一直在欧洲各地占领领土，却没有人阻止他。所以在波兰这件事上，又怎么会有不同呢？* +

但我要告诉你，*#在波兰这件事上情况确实不同了，因为这次入侵, 成了压垮英国和法国的最后一根稻草。因此，作为这次入侵的结果，英国和法国向德国宣战，第二次世界大战就这样爆发了。#* +

好的，点击这里继续复习AP欧洲历史第8单元，点击这里获取我的AP欧洲史复习资料包，它能帮助你在课堂上得A，在五月的考试中得5分。回头见。我撤了。 +

'''

== pure

Now I haven't mentioned in my previous videos, but World War One was first known as the Great War or the war to end all wars. But the fact that we know it as World War One makes the spoiler pretty obvious -- there was in fact a World War II. Now we're going to deal with that war in the next video, but in this one, let's look at the factors that made the war to end all wars just an appetizer to the next great one. So if you're ready to get them brain cows milked appeasement style, then let's get to it.

Coming out of World War One, there were a lot of complex factors that allowed fascist states both to re-arm themselves and expand their terror. Now remember, Germany was on the losing side of World War One, and part of the Treaty of Versailles mandated that Germany demilitarized and another part shrank their territory. So reversing either of those realities was a violation of the treaty, and if Germany violated that treaty, it would likely lead to another war. And yet, under the leadership of Adolf Hitler, Germany significantly rearmed itself and began conquering territory like a madman. So how did he do it?

The first reason this could happen was because of the policy of appeasement towards Germany. Britain and France were the main appeasers. As I mentioned in the video on World War One, the human and capital cost of that war was staggering to all involved. So when Hitler began publicly re-arming Germany in 1935 and taking territory thereafter, Britain and France were not too eager to start another war to stop him. The policy of appeasement essentially became: let Hitler do whatever he wants because we're not destroying ourselves in another cataclysmic battle yet again. In other words, Hitler faced no consequences for breaking the provisions in the Treaty of Versailles that kept Germany powerless in the interwar period.

Now the second reason Germany was able to re-arm and start expanding was because of the growing antagonism and distrust between the Soviet Union and the Western European states slash the United States. Recall that the Soviet Union was an authoritarian communist state, and that was diametrically opposed to the U.S. and Western Europe, which represented capitalist democracy. We'll get more into that antagonism and distrust in Unit 9 during the Cold War, but for now, all you have to know is that these two entities were so opposed to one another that they could not work together to present a united front against expanding fascist states. And I say states plural because even though I've only been referring to Germany, fascist Italy was expanding too. And you know, let's talk about that.

Okay, and here we need to talk about the specific actions that led to World War II. First, let's get specific with territorial expansion. In 1935, Italy invaded Ethiopia, which happened to be only one of two African states that had never been colonized by Europeans. If you've been around since we talked about the Scramble for Africa, then you know that is a big deal. Anyway, Italy was ultimately successful in conquering Ethiopia, and that victory made Britain a little sweaty because it threatened their control of the Suez Canal in Egypt. And remember, nobody wants to start another war, and so the only reprisal Mussolini faced for this attack was a few lame economic sanctions imposed by the League of Nations.

But Germany's territorial expansion made Italy's efforts look like child's play. Hitler began by re-militarizing the Rhineland, which is this little strip of land right here. This act was kind of like an experiment for Hitler. The Treaty of Versailles specifically prohibited German armament of this territory, so Hitler wanted to see if Britain and France were up for fighting. So in 1936, Hitler sent troops to occupy the Rhineland, and because of the policy of appeasement that I mentioned earlier, all he heard from Britain and France was, "Hitler, stop." Upon seeing that Britain and France would do nothing to enforce the treaty, Hitler was like, "Oh, it's on."

Next, in 1938, Hitler annexed Austria, a move known as Anschluss on account of all the Germans living in Austria. And once German troops came into Austria, they decided to hold a little vote to hear from the Austrians whether or not they wanted to be absorbed into the German Reich. And wouldn't you know it, like 99% of Austrians voted yes to the annexation. Hold on, you're trying to tell me that an independent nation in the age of self-determination decided by a margin of 99% that they wanted to be taken over? Does that smell funky to anybody else? I mean, think about it: when have you ever heard of 99% of people in any country in any age in any part of the world agreeing on something? That does not happen.

So that vote did indeed smell funky, and here's why. First of all, look at this ballot. You don't even have to speak German to know that the "yes" circle is a little out of proportion to the "no" circle. Second, this was not a secret ballot. In order to vote, you had to hand it to a German military officer who would then place it in the box. So it was a rigged vote without a doubt. But Hitler was successful nonetheless. And then he went on to take over the Sudetenland and a few states in Czechoslovakia as well. And in all of this, Britain and France essentially did nothing to stop it. But what they did do is gather at a meeting and create the Munich Agreement, in which Britain and France agreed to all of Hitler's territorial demands but made him promise that he would take no more. And Hitler was like, "Yeah, sure."

Additionally, Hitler made peace with the Soviet Union in something called the Nazi-Soviet Non-Aggression Pact, in which they agreed to two stipulations: first, neither would attack the other for a decade following the agreement; second, they agreed to split Poland between the two powers. And that second stipulation gave Hitler the confidence to invade Poland, knowing that the Soviet Union would not oppose him. In 1939, that is exactly what Hitler did. And why wouldn't he? Even though he committed in the Munich Agreement that he would not seek any more territory, he had been taking territory all over Europe and no one was stopping him. So why would it be any different in Poland?

But here's where I tell you that it was different in Poland, because that invasion was the last straw for Britain and France. So as a result of that invasion, Britain and France declared war on Germany, and that is how you get World War II.

Okay, click here to keep reviewing for Unit 8 of AP Euro, and click here to grab my AP Euro review pack, which is going to help you get an A in your class and a five on your exam in May. I'll catch you on the flip-flop. I'm out.

'''