
= 8.8 World War II
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 释义

So World War One was not _the war to end (v.) all wars_ like everyone wanted it to be. There was in fact a World War II, and in this video /we're going to look at it _straight in the face_ 直面. So if you're ready to get them brain cows milked, let's get to it. +

Now in the last video, I mentioned _all the precipitating (a.)使…突然降临；加速（坏事的发生）;促成的；引发的 factors_ 后定说明 that led to the war, so here /let's just *jump straight into* the fight. There were essentially two theaters 战场；战区 of the war: there was the European theater 战场；战区 and the Pacific theater. When I say _theater of war_ -- maybe you don't know that terminology 术语；专业用语 -- but it's not that hard to understand 这并不难理解. Basically it means that /there were two stages /upon which the events of World War II unfolded: one stage here /and one stage here. +

So the war essentially began in the Pacific theater first, and *for* that /we have Japan *to thank*.  +
Since the last part of the 19th century, continued into the early decades of the 20th century 从19世纪后半叶开始，一直持续到20世纪初, Japan had risen to dominance (n.)优势，支配地位 in the Eastern world 日本已崛起为东方世界的主宰. Driven by _policies of aggressive (a.) expansionism_ (扩张主义) 侵略性扩张主义的政策, Japan had won (v.) victories against China and then against Russia, and then *gobbled 狼吞虎咽地吃 up* 吞并；吞噬 many territories in Southeast Asia. Because Japan was also gripped 紧握；紧抓 by fascist leadership, there was a natural affinity (n.)喜好，喜爱；类同，密切关系；吸引力 between them and Germany and Italy.  +
But anyway, the war on the Pacific essentially began in 1937 /when the Chinese and Japanese forces (n.) clashed (v.)冲突；交战 over the Japanese seizure (n.)占领；夺取 of Manchuria 满洲. +


By the way, if you want help reviewing 回顾；复习 for all of this /and for the national exam coming up, then check out 查看；查阅 my AP Euro review pack /which has everything you need to get an A in your class /and a five on your exam in May. Link in description. +

Anyway, over in the European theater of World War II 在二战的欧洲战场上, the war was triggered 引发；触发 by Adolf Hitler's invasion of Poland in 1939. Now you might recall 回想起 from the last video that /Britain and France had been abiding by 遵守；信守 the policy of appeasement 绥靖政策 with regards to 关于；至于 Hitler's expansionism across Europe. But the invasion of Poland was the last straw 最后一根稻草；忍无可忍的事, and with that, Britain and France *declared war* on Germany. And baby, you got another world war /on your hands. +

[.my1]
.案例
====
.you got another world war /on your hands.
字面意思是 ​​“你手上又多了一场世界大战”​​， +
实际含义是：​​“这下可好，又一场世界大战爆发了！”​
====

Now once the war started, there were two opposing sides. _The Allied Powers_ 同盟国 included Britain, France, and the Soviet Union, and then later the United States would join (v.) as well. _The Axis powers_ 轴心国 essentially included Germany, Italy, and Japan. And the truth is, early in the war, the Axis powers seemed to *be dunking （吃前将食物放入液体中）浸一浸，泡一泡 on* 打败；击败(在篮球比赛中扣篮得分, 并且将球砸在对手头上以示嘲讽或挑衅) the Allied powers profoundly 极大地，深刻地；严重地，完全地. And `主` _no small 不小的 part_ of said dunking `系` was #due# (a.)由于；因为;应支付；应给予；应归于 -- in the European theater -- #to# Hitler's method of attack /known as blitzkrieg 闪电战；突然袭击. It literally means (v.) lightning war /because when the Germans showed up, it was like, "And we're dead." It was called this because it was a tactic 战术；策略 designed to crush an enemy at an incredible speed using a combination of air power, tanks, and ground troops. German forces plowed through 突破；冲破 the enemy lines and then went on to terrorize 恐吓；使恐惧 the civilian populations of these countries. +

[.my1]
.案例
====
.blitzkrieg
-> blitz, 闪电，来自PIE *bhel, 照耀，闪光，词源同blank. krieg, 战争。
====

Not only did this work in Eastern European countries like Poland, Yugoslavia, and Greece, but it also worked in the West too. In 1941, Hitler invaded France with these same tactics, and they were positively dazed 目瞪口呆的；眩晕的 by the Nazi attack. It wasn't long before France fell to Germany, and Mussolini over in Italy rushed to France as well to grab a piece of that sweet French pie. Now the northern part of France was under direct occupation 占领 by Germany, while a Nazi puppet government 傀儡政府 known as Vichy France 维希法国 was established in the south. +

Then in June of 1941, Hitler turned his sights on 把目光转向 the Soviet Union. You may remember in the last video I talked about the non-aggression pact 互不侵犯条约 that Hitler signed with Joseph Stalin, the leader of the Soviet Union. It was an agreement that they would not attack each other. But Hitler never really intended to honor this pact -- it was just an agreement to buy him some time to conquer the rest of Europe without interference from those pesky 讨厌的；麻烦的 Soviets. But in 1941, Hitler launched Operation Barbarossa 巴巴罗萨行动 in which he sought to conquer the Soviet Union, which he needed for all the natural resources bound up in that land. Hitler won some early victories in this campaign, but ultimately the Soviets rallied 重整旗鼓；振作起来 and made any further gains very difficult. In fact, Hitler's troops got so bogged down 陷入困境 that they were stationed there through winter -- which, if Hitler had bothered to consult Napoleon on, he would know that was a bad idea. Anyway, Germans were able to hold some Soviet territory, but they were never able to fully conquer it. +

Case in point 例如: the siege of Stalingrad 斯大林格勒保卫战 during this campaign. Soviet civilians and military endured brutal 残酷的；残忍的 conditions but would not surrender, and ultimately the Germans endured three quarters of a million casualties 伤亡人员 and were never able to control the Soviet stronghold 据点；要塞. So all that to say, the Axis powers -- in particular Germany -- came out strong in the beginning, but eventually the tides 形势；趋势 began to turn. +

Now by 1940, the only real threat to Hitler that was left on the continent was Britain. Like, no other Western state was opposing him. And under the leadership of Prime Minister Winston Churchill, the British people rallied to the cause. Hitler assumed that bombing campaigns aimed at British civilian populations would so demoralize 使士气低落；使丧失信心 the British that they would beg their government to surrender. But those bombing raids 空袭 had the opposite effect. Thanks to the bulldoggish tenacity 顽强；坚韧 of Churchill, he organized the resistance and gave moving speeches that roused 激起；唤起 the British people to continue the resistance. +

Now I said that Britain was standing alone, but that's not entirely accurate. More accurately, Britain was the only Western country that had officially declared war on Germany that was continuing the resistance. But there was another Western country who was undeclared in war that was handily 便利地；轻易地 supporting the British cause, namely the United States. After World War One, Americans essentially turned into an isolationist 孤立主义的 nation with regard to European conflicts. They just needed a little me-time after the great European war. However, U.S. President Franklin D. Roosevelt could see that if Britain fell to the Germans, that would be a bad situation for the United States. So the U.S. had been supplying the British with weapons of war through their Cash and Carry program 现金自运计划 and their Destroyers for Bases programs 驱逐舰换基地计划, etc. So even though the United States wasn't officially a belligerent 交战国；交战方 in the war, it was clear to the whole world where their sympathies led. +

This loyalty was abundantly clear to Japan, who realized that America's friendship with Britain would eventually bring the industrial giant into the war, and they wanted to prevent it. And so on December 7, 1941, Japanese planes bombed the U.S. naval base at Pearl Harbor 珍珠港 in Hawaii. And with that kind of aggression, the United States declared war on Japan. Germany went ahead and declared war on the United States, and now we're in. +

And thanks to the fantastic industrial capacity of the United States, factories of all kinds were transformed almost overnight into factories for producing weapons of war. The amount of planes and guns and tanks and everything else the U.S. was able to muster 聚集；集合 in a short amount of time had a significant effect on the war. Additionally, a joint British-U.S. invasion of France on D-Day 诺曼底登陆日 proved a turning point for the war in the West. After having deceived 欺骗；误导 the Germans into thinking that the invasion was coming from another place, on June 6, 1944, the British and Americans executed the largest amphibious invasion 两栖登陆 in world history on the beaches of Normandy. And though they suffered heavy casualties for the effort, eventually they were successful in liberating France from Nazi occupation. +

The tide began to turn in Eastern Europe thanks to the all-out effort from the Soviet Union. As I already mentioned in the siege of Stalingrad, the tide of war changed in the Pacific theater at the Battle of Midway 中途岛战役, in which American forces dominated the Japanese Navy and then engaged in an island-hopping campaign 跳岛战术 to cut off Japanese supply lines. Ultimately, the Allies closed in on 逼近；包围 Berlin more and more, and Hitler moved his anti-semitic 反犹主义的 hind parts 后部 into a bunker 地堡, still casting blame on the Jews for all the misfortunes that Germany had suffered. Hiding down in his bunker instead of admitting defeat, he committed suicide instead. And on May 7, the German government surrendered. It became known as VE Day -- or Victory in Europe Day 欧洲胜利日 -- in the European theater. It was close. +

But in order to talk about how the Pacific theater was closed, we need to talk about some new technology that was employed in this war. Now after the war was over, everyone counted their dead and realized that more people had died in this war than any other war -- World War One not being excepted. And a large part of that death toll 死亡人数 was the new and devastating 毁灭性的 war technology employed, and I'll tell you about two of them. +

First was the introduction of incendiary bombs 燃烧弹. These were bombs that were casing wood housing that were meant not only to explode but to start fires. In the firebombing of Tokyo carried out by the U.S. Air Force, 16 square miles of Tokyo were burned in the fire, and a hundred thousand people were left dead. And then British and American planes did the same thing to Dresden in Germany, and though only about a quarter of that number died there, it was still absolutely devastating. +

But perhaps the most devastating technology introduced in World War II was the atomic bomb 原子弹. This was a bomb created by the Americans that was able to destabilize 使不稳定 atoms 原子 and release the destructive energy that came as a result of that destabilization. A single nuclear bomb was capable of delivering the explosive force of about 20,000 tons of dynamite 炸药. And so in order to close the Pacific theater of war, the United States dropped two of these bombs on Japan: one in Hiroshima 广岛 and the other in Nagasaki 长崎. And between the two of these bombs, both cities were destroyed, and somewhere between a hundred thousand to two hundred thousand were killed. Several days after the second bomb was dropped, Japan surrendered in what became known as VJ Day -- or Victory in Japan Day 日本胜利日. +

Now don't get me wrong, it was great that the war was over. But in truth, the introduction of nuclear weapons is going to cause a lot of trouble going forward. But for that, we'll have to wait for Unit Nine. +

Okay, click here to keep reviewing for Unit 8 of AP European History. Click here to grab my AP Euro review pack which will help you get an A in your class and a five on your exam in May. I'll catch you on the flip-flop. I'm out. +

'''

== 中文释义

所以第一次世界大战并非如人们所期望的那样，是一场终结所有战争的战争。事实上，后来还有第二次世界大战，在这个视频中，我们将直面这场战争。所以，如果你准备好获取知识，那就开始吧。 +

在上一个视频中，我提到了导致这场战争的所有促成因素，所以在这里，我们直接进入战斗环节。**这场战争本质上有两个战区：欧洲战区和太平洋战区。**当我说“战区”时 —— 也许你不了解这个术语 —— 但这并不难理解。基本上，这意味着第二次世界大战的事件在两个“舞台”上展开：一个在这儿，一个在那儿。 +

所以**这场战争本质上首先在太平洋战区爆发，这得“归功于”日本。**从19世纪后期到20世纪的头几十年，日本在东方世界崛起并占据主导地位。在侵略扩张主义政策的驱动下，日本先是战胜了中国，然后又战胜了俄罗斯，接着吞并了东南亚的许多领土。因为日本也由法西斯势力领导，所以它与德国和意大利有着天然的“亲近感”。不管怎样，太平洋战争实际上始于1937年，当时中日军队因日本对满洲（Manchuria）的占领而发生冲突。 +

顺便说一下，如果你想在复习这部分内容以及即将到来的全国考试时得到帮助，那就看看我的AP欧洲史复习资料包吧，它包含了你在课堂上得A以及在五月考试中得5分所需要的一切。简介里有链接。 +

不管怎样，在第二次世界大战的**欧洲战区，战争是由阿道夫·希特勒（Adolf Hitler）1939年入侵波兰（Poland）引发的。**你可能还记得上一个视频中提到的，英国和法国对希特勒在欧洲的扩张主义一直奉行"绥靖政策"。但入侵波兰成了压垮骆驼的最后一根稻草，因此，英国和法国向德国宣战。这下，又一场世界大战爆发了。 +

战争一旦爆发，就有了两个对立的阵营。同盟国（Allied Powers）包括英国、法国和苏联，后来美国也加入了。轴心国（Axis powers）主要包括德国、意大利和日本。事实上，在战争初期，轴心国似乎狠狠地“教训”了同盟国。在欧洲战区，这种“教训”在很大程度上要归因于希特勒的攻击策略，也就是闪电战（blitzkrieg）。这个词字面意思是“闪电战”，因为当德国人出现时，就好像在说：“我们死定了。”之所以叫闪电战，是因为这是一种结合了空中力量、坦克和地面部队，以惊人的速度击溃敌人的战术。德国军队突破了敌人的防线，然后开始恐吓这些国家的平民百姓。 +

这种战术不仅在波兰、南斯拉夫（Yugoslavia）和希腊等东欧国家奏效，在西方也同样有效。1941年，希特勒用同样的战术入侵法国，纳粹的攻击让法国彻底懵了。没过多久，法国就向德国投降了，意大利的墨索里尼（Mussolini）也赶紧跑到法国，想分一杯羹。法国北部被德国直接占领，而在南部建立了一个名为维希法国（Vichy France）的纳粹傀儡政府。 +

**然后在1941年6月，希特勒把目光转向了苏联。**你可能还记得上一个视频中我提到的，**希特勒与苏联领导人约瑟夫·斯大林（Joseph Stalin）签署的互不侵犯条约。**这是一个双方互不攻击的协议。**但希特勒从来没打算遵守这个条约 —— 这只是一个为他争取时间，以便在不受讨厌的苏联干扰的情况下征服欧洲其他地区的协议。但在1941年，希特勒发动了“巴巴罗萨行动”（Operation Barbarossa），试图征服苏联，因为他需要苏联土地上的所有自然资源。**希特勒在这场战役初期取得了一些胜利，但最终苏联进行了反击，让德军很难再取得进一步的进展。事实上，希特勒的军队深陷其中，还在那儿度过了冬天 —— 如果希特勒事先咨询过拿破仑，他就会知道这是个糟糕的主意。不管怎样，德国人虽然占领了一些苏联领土，但始终未能完全征服苏联。 +

一个典型的例子就是这场战役中的"斯大林格勒（Stalingrad）保卫战"。苏联的平民和军队忍受着残酷的条件，但绝不投降，最终德军伤亡达75万人，却始终无法控制苏联的这个据点。所以这么说吧，轴心国 —— 尤其是德国 —— 在战争初期来势汹汹，但最终局势开始逆转。 +

到了1940年，欧洲大陆上对希特勒唯一真正的威胁是英国。其他西方国家都没有反抗他。在首相温斯顿·丘吉尔（Winston Churchill）的领导下，英国人民团结起来抵抗。希特勒认为，针对英国平民的轰炸行动, 会让英国人士气低落，从而乞求政府投降。但这些轰炸行动却适得其反。多亏了丘吉尔顽强的韧性，他组织了抵抗力量，并发表了激动人心的演讲，鼓舞英国人民继续抵抗。 +

我说英国是孤军奋战，但这并不完全准确。更准确地说，英国是唯一一个正式向德国宣战并持续抵抗的西方国家。但还有另一个未正式宣战的西方国家，大力支持英国，那就是美国。**第一次世界大战后，美国在欧洲冲突问题上, 基本上变成了一个孤立主义国家。**在那场伟大的欧洲战争之后，他们只是想给自己一些“独处”的时间。然而，美国总统富兰克林·D·罗斯福（Franklin D. Roosevelt）明白，如果英国向德国投降，对美国来说将是个糟糕的局面。所以美国通过“现购自运”计划（Cash and Carry program）和“以驱逐舰换基地”计划（Destroyers for Bases programs）等，向英国提供战争武器。所以，*尽管美国没有正式参战，但全世界都清楚他们支持哪一方。* +

日本也清楚美国对英国的这种忠诚，他们意识到美国与英国的友好关系, 最终会让这个工业巨头卷入战争，他们想阻止这种情况发生。于是在1941年12月7日，日本飞机轰炸了美国在夏威夷（Hawaii）的海军基地珍珠港（Pearl Harbor）。面对这种侵略行为，*美国向日本宣战。德国也紧接着向美国宣战，这下大家都参战了。* +

多亏了美国强大的工业能力，各种各样的工厂几乎在一夜之间, 就转型为生产战争武器的工厂。美国在短时间内调集的飞机、枪支、坦克以及其他各种武器，对战争产生了重大影响。此外，**英美在诺曼底登陆日（D-Day）对法国的联合入侵，成为了西线战争的转折点。**他们成功地让德国人误以为入侵会从另一个地方发起，然后在1944年6月6日，英美在诺曼底（Normandy）海滩上发动了世界历史上规模最大的两栖登陆行动。尽管他们为此付出了惨重的伤亡代价，但**最终成功地把法国从纳粹占领下解放了出来。** +

**由于苏联的全力以赴，东欧的局势开始扭转。**就像我之前提到的斯大林格勒保卫战一样，**##太平洋战区的战争局势在"中途岛海战"（Battle of Midway）中发生了改变，美国##军队**在这场海战中击败了日本海军，**##然后展开了跳岛作战，##切断了日本的补给线。**最终，盟军不断逼近柏林，希特勒带着他的反犹思想躲进了地堡，还在把德国遭受的所有不幸都归咎于犹太人。他没有承认失败，而是选择了自杀。*1945年5月7日，德国政府投降。这一天在欧洲战区被称为"欧洲胜利日"*（VE Day，Victory in Europe Day）。战争接近尾声。 +

但为了说明太平洋战区是如何结束的，我们需要谈谈这场战争中使用的一些新技术。战争结束后，人们统计了死亡人数，意识到这场战争的死亡人数比其他任何一场战争都多 —— 第一次世界大战也不例外。而死亡人数如此之多，很大程度上是因为使用了新的、具有毁灭性的战争技术，我来给你们介绍其中的两种。 +

第一种是"燃烧弹"的使用。这些炸弹被用来攻击木质房屋，不仅会爆炸，还会引发火灾。美国空军对东京进行的燃烧弹轰炸中，东京16平方英里的区域被大火烧毁，造成10万人死亡。然后英美飞机对德国的德累斯顿（Dresden）也做了同样的事，虽然那里的死亡人数只有东京的四分之一左右，但仍然具有极大的破坏力。 +

但也许第二次世界大战中引入的最具毁灭性的技术, 是原子弹。这是美国人制造的一种炸弹，它能够破坏原子的稳定性，并释放由此产生的破坏性能量。一枚核弹的爆炸力相当于约20000吨炸药。所以，为了结束太平洋战区的战争，美国向日本投下了两颗原子弹：一颗投在了广岛（Hiroshima），另一颗投在了长崎（Nagasaki）。两颗原子弹让这两座城市都被摧毁，造成了10万到20万人死亡。在第二颗原子弹投下几天后，日本投降，这一天被称为"日本胜利日"（VJ Day，Victory in Japan Day）。 +

别误会，战争结束是件好事。但事实上，核武器的出现将在未来引发很多麻烦。关于这一点，我们要等到第9单元再讲。 +

好的，点击这里继续复习AP欧洲历史第8单元。点击这里获取我的AP欧洲史复习资料包，它能帮助你在课堂上得A，在五月的考试中得5分。回头见。我走了。 +

'''

== pure

So World War One was not the war to end all wars like everyone wanted it to be. There was in fact a World War II, and in this video we're going to look at it straight in the face. So if you're ready to get them brain cows milked, let's get to it.

Now in the last video, I mentioned all the precipitating factors that led to the war, so here let's just jump straight into the fight. There were essentially two theaters of the war: there was the European theater and the Pacific theater. When I say theater of war -- maybe you don't know that terminology -- but it's not that hard to understand. Basically it means that there were two stages upon which the events of World War II unfolded: one stage here and one stage here.

So the war essentially began in the Pacific theater first, and for that we have Japan to thank. Since the last part of the 19th century in the early decades of the 20th century, Japan had risen to dominance in the Eastern world. Driven by policies of aggressive expansionism, Japan had won victories against China and then against Russia, and then gobbled up many territories in Southeast Asia. Because Japan was also gripped by fascist leadership, there was a natural affinity between them and Germany and Italy. But anyway, the war on the Pacific essentially began in 1937 when the Chinese and Japanese forces clashed over the Japanese seizure of Manchuria.

By the way, if you want help reviewing for all of this and for the national exam coming up, then check out my AP Euro review pack which has everything you need to get an A in your class and a five on your exam in May. Link in description.

Anyway, over in the European theater of World War II, the war was triggered by Adolf Hitler's invasion of Poland in 1939. Now you might recall from the last video that Britain and France had been abiding by the policy of appeasement with regards to Hitler's expansionism across Europe. But the invasion of Poland was the last straw, and with that, Britain and France declared war on Germany. And baby, you got another world war on your hands.

Now once the war started, there were two opposing sides. The Allied Powers included Britain, France, and the Soviet Union, and then later the United States would join as well. The Axis powers essentially included Germany, Italy, and Japan. And the truth is, early in the war, the Axis powers seemed to be dunking on the Allied powers profoundly. And no small part of said dunking was due -- in the European theater -- to Hitler's method of attack known as blitzkrieg. It literally means lightning war because when the Germans showed up, it was like, "And we're dead." It was called this because it was a tactic designed to crush an enemy at an incredible speed using a combination of air power, tanks, and ground troops. German forces plowed through the enemy lines and then went on to terrorize the civilian populations of these countries.

Not only did this work in Eastern European countries like Poland, Yugoslavia, and Greece, but it also worked in the West too. In 1941, Hitler invaded France with these same tactics, and they were positively dazed by the Nazi attack. It wasn't long before France fell to Germany, and Mussolini over in Italy rushed to France as well to grab a piece of that sweet French pie. Now the northern part of France was under direct occupation by Germany, while a Nazi puppet government known as Vichy France was established in the south.

Then in June of 1941, Hitler turned his sights on the Soviet Union. You may remember in the last video I talked about the non-aggression pact that Hitler signed with Joseph Stalin, the leader of the Soviet Union. It was an agreement that they would not attack each other. But Hitler never really intended to honor this pact -- it was just an agreement to buy him some time to conquer the rest of Europe without interference from those pesky Soviets. But in 1941, Hitler launched Operation Barbarossa in which he sought to conquer the Soviet Union, which he needed for all the natural resources bound up in that land. Hitler won some early victories in this campaign, but ultimately the Soviets rallied and made any further gains very difficult. In fact, Hitler's troops got so bogged down that they were stationed there through winter -- which, if Hitler had bothered to consult Napoleon on, he would know that was a bad idea. Anyway, Germans were able to hold some Soviet territory, but they were never able to fully conquer it.

Case in point: the siege of Stalingrad during this campaign. Soviet civilians and military endured brutal conditions but would not surrender, and ultimately the Germans endured three quarters of a million casualties and were never able to control the Soviet stronghold. So all that to say, the Axis powers -- in particular Germany -- came out strong in the beginning, but eventually the tides began to turn.

Now by 1940, the only real threat to Hitler that was left on the continent was Britain. Like, no other Western state was opposing him. And under the leadership of Prime Minister Winston Churchill, the British people rallied to the cause. Hitler assumed that bombing campaigns aimed at British civilian populations would so demoralize the British that they would beg their government to surrender. But those bombing raids had the opposite effect. Thanks to the bulldoggish tenacity of Churchill, he organized the resistance and gave moving speeches that roused the British people to continue the resistance.

Now I said that Britain was standing alone, but that's not entirely accurate. More accurately, Britain was the only Western country that had officially declared war on Germany that was continuing the resistance. But there was another Western country who was undeclared in war that was handily supporting the British cause, namely the United States. After World War One, Americans essentially turned into an isolationist nation with regard to European conflicts. They just needed a little me-time after the great European war. However, U.S. President Franklin D. Roosevelt could see that if Britain fell to the Germans, that would be a bad situation for the United States. So the U.S. had been supplying the British with weapons of war through their Cash and Carry program and their Destroyers for Bases programs, etc. So even though the United States wasn't officially a belligerent in the war, it was clear to the whole world where their sympathies led.

This loyalty was abundantly clear to Japan, who realized that America's friendship with Britain would eventually bring the industrial giant into the war, and they wanted to prevent it. And so on December 7, 1941, Japanese planes bombed the U.S. naval base at Pearl Harbor in Hawaii. And with that kind of aggression, the United States declared war on Japan. Germany went ahead and declared war on the United States, and now we're in.

And thanks to the fantastic industrial capacity of the United States, factories of all kinds were transformed almost overnight into factories for producing weapons of war. The amount of planes and guns and tanks and everything else the U.S. was able to muster in a short amount of time had a significant effect on the war. Additionally, a joint British-U.S. invasion of France on D-Day proved a turning point for the war in the West. After having deceived the Germans into thinking that the invasion was coming from another place, on June 6, 1944, the British and Americans executed the largest amphibious invasion in world history on the beaches of Normandy. And though they suffered heavy casualties for the effort, eventually they were successful in liberating France from Nazi occupation.

The tide began to turn in Eastern Europe thanks to the all-out effort from the Soviet Union. As I already mentioned in the siege of Stalingrad, the tide of war changed in the Pacific theater at the Battle of Midway, in which American forces dominated the Japanese Navy and then engaged in an island-hopping campaign to cut off Japanese supply lines. Ultimately, the Allies closed in on Berlin more and more, and Hitler moved his anti-semitic hind parts into a bunker, still casting blame on the Jews for all the misfortunes that Germany had suffered. Hiding down in his bunker instead of admitting defeat, he committed suicide instead. And on May 7, the German government surrendered. It became known as VE Day -- or Victory in Europe Day -- in the European theater. It was close.

But in order to talk about how the Pacific theater was closed, we need to talk about some new technology that was employed in this war. Now after the war was over, everyone counted their dead and realized that more people had died in this war than any other war -- World War One not being excepted. And a large part of that death toll was the new and devastating war technology employed, and I'll tell you about two of them.

First was the introduction of incendiary bombs. These were bombs that were casing wood housing that were meant not only to explode but to start fires. In the firebombing of Tokyo carried out by the U.S. Air Force, 16 square miles of Tokyo were burned in the fire, and a hundred thousand people were left dead. And then British and American planes did the same thing to Dresden in Germany, and though only about a quarter of that number died there, it was still absolutely devastating.

But perhaps the most devastating technology introduced in World War II was the atomic bomb. This was a bomb created by the Americans that was able to destabilize atoms and release the destructive energy that came as a result of that destabilization. A single nuclear bomb was capable of delivering the explosive force of about 20,000 tons of dynamite. And so in order to close the Pacific theater of war, the United States dropped two of these bombs on Japan: one in Hiroshima and the other in Nagasaki. And between the two of these bombs, both cities were destroyed, and somewhere between a hundred thousand to two hundred thousand were killed. Several days after the second bomb was dropped, Japan surrendered in what became known as VJ Day -- or Victory in Japan Day.

Now don't get me wrong, it was great that the war was over. But in truth, the introduction of nuclear weapons is going to cause a lot of trouble going forward. But for that, we'll have to wait for Unit Nine.

Okay, click here to keep reviewing for Unit 8 of AP European History. Click here to grab my AP Euro review pack which will help you get an A in your class and a five on your exam in May. I'll catch you on the flip-flop. I'm out.

'''