
= 8.9 The Holocaust
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 释义

Now one of the more devastating 毁灭性的 outcomes 结果，效果 of World War II was the Nazi policy of the mass extermination 大规模灭绝 of the Jews, and what became known as the Holocaust 大屠杀. And in this video, we're going to look at why it happened and its results. +

So when Adolf Hitler came to power in Germany, he made no attempt to hide the racialist 种族主义的 motivations 动机 /that drove (v.) his actions. You see, Hitler came to find great comfort /in the fact that `主` modern Germans `系` were the descendants 后代；后裔 of an ancient group of Germanic-speaking peoples known as the Aryans (雅利安人). 你看，希特勒在现代德国人是古代讲日耳曼语的雅利安人的后裔这一事实中,找到了极大的安慰。 `主` Hitler and the rest /who thought (v.) like him `谓` believed the Aryans were the master race 优等种族 of the earth, and thus the master race ought to claim (v.) its place of ascendancy 优势；支配地位 in the world.

[.my1]
.案例
====
希特勒认为的“**现代德国人是古代雅利安人的后裔，**因此是优等民族”，**在科学上是完全不属实的，并且没有任何可靠的历史或遗传学依据。**这是希特勒和纳粹党为推行其种族主义意识形态而捏造的伪科学理论。


“雅利安人”的真实起源： +
**“雅利安人”（Aryan）这个词的本意, 是指古代印欧语系民族的一支，主要生活在古印度和古伊朗地区。**他们是印欧语系中的印度-伊朗语族群的祖先，**与现代德国人所使用的日耳曼语族没有直接的、血缘上的联系。**语言学和考古学研究表明，日耳曼民族和印度-伊朗民族都属于广义的印欧语系，但他们在数千年前就分化了，各自发展。因此，说现代德国人是古代雅利安人的后裔，就如同说现代意大利人是古汉人的后裔一样，在遗传学和历史学上都是荒谬的。

种族主义的伪科学： +
在19世纪末到20世纪初，**一些欧洲学者错误地将“雅利安语系”等同于“雅利安种族”，并臆造出一种金发碧眼的“原始雅利安种族”，认为其是所有高贵文明的创造者。希特勒正是借用了这种伪科学理论，**并将其极端化，用于支持其纳粹意识形态。

*希特勒之所以认为雅利安人是最优等的民族，没有任何科学依据，其“依据”完全是基于其种族主义和政治目的。*

意识形态需求：
纳粹主义的核心是一种极端民族主义和种族主义**。为了给德国的侵略和种族灭绝政策寻找“合法性”，希特勒需要一个强大的、优越的民族身份来凝聚德国人民，并为他的行动提供道德借口。**他将德国人与虚构的“雅利安超人”联系起来，**创造了一种“天选之民”的幻觉。**
====


And Hitler trained his mind to believe that /`主` the most virulent (a.)恶毒的；恶性的 threat 威胁，恐吓 to the flourishing 繁荣；兴旺 of the modern master race 现代优等种族 `系` was the Jewish population of Europe. And so /once Hitler had come to power, he began implementing 实施；执行 policies (n.) to establish (v.) this new racial order 种族秩序. +

So starting in 1935, Hitler's anti-Jewish policies were mild *compared to* what they would later become 希特勒的反犹太政策,与后来的情况相比是温和的. The first major iteration 版本；迭代 of this plan `谓` came _in the form of_ the Nuremberg Laws 纽伦堡法案, which put Hitler's racialist ideology 意识形态 into law. `主` The first law `谓` established that /`主` only people of pure German blood `谓` could be citizens, and thus Jews were stripped of 剥夺 their citizenship. The second law made it illegal /for _pureblood Germans_ to intermarry (v.)不同种族（或国家、教派）间通婚;近族通婚；近亲结婚 with Jews. +

[.my1]
.案例
====
.纽伦堡法案
1935年9月15日，有两项法律被呈交德国国会通过，合称《纽伦堡法案》：

- 《保护德国血统和德国荣誉法》 +
禁止“德国人”（指具有德意志民族血统者，下同）与犹太人结婚, 或有婚外性行为。 +
禁止犹太家庭, 雇用45岁以下的德国女性为家庭佣工。 +

- 《帝国公民权法》 +
*宣布只有德国人或有相关血统者, 有资格成为德国公民，褫夺“非德国人”的德国公民权。* +
其后的补充法令, 为“犹太人”一词下定义，如果一个人的祖父母, 四人中全部, 或三个是犹太人，则该人在法律上即属于犹太人。如果一个人的祖父母中, 仅有两个或一个是犹太人，则该人属于“混血儿”（Mischling）。

所有的祖父母是否为“犹太人”, 则会根据其是否为犹太教社群的成员, 而自动定义，无论他们是否真正认同犹太教信仰。

**二战后"纽伦堡审判"明确规定，#纳粹德国时期颁布的法令, 为“恶法”，而恶法本身就是非法行为(恶法非法)，#**因此在纽伦堡审判, 以及以色列对阿道夫·艾希曼的审判中, *驳回了被告人依据“纽伦堡法案”上诉的可能性。*
====

And then in 1939, Hitler's policy shifted (v.) towards Jewish emigration 移民（移出）. Remember, emigration 移居外国，迁移出境 is when people leave a country; immigration 移民（移入）（入境）  is when people come into a country. Now `主` _the most robust 详尽的；周全的 plan_ coming out of this idea `系` was *to ship* (v.) all the Jews *to* the African island of Madagascar 马达加斯加岛. However, when World War II started, Hitler no longer had the time or attention /to manage (v.) the complexities 复杂性；错综复杂的事物 of his Jewish emigration plans, and that's when things turned much darker. +

In 1942, something called _the Wannsee 万塞（德国柏林西南部地区） Conference_ 万湖会议 was held /in which Nazi leaders Reinhard Heydrich, Heinrich Himmler, and Hitler articulated (v.)明确表达；清楚说明 what became known as the Final Solution 最终解决方案 to the Jewish problem. And the Final Solution was *not* the emigration of Jews, *but rather* their complete extermination 消灭；根绝. +

[.my1]
.案例
====
.Wannsee Conference
万湖会议（德语：Wannseekonferenz），又译万塞会议，是纳粹德国官员关于讨论“犹太人问题最终解决方案”召开的会议。

这次会议由帝国安全总局局长、党卫军中队长莱因哈德·海德里希召集，目的是确保各政府部门行政领导人, 合作实施犹太人问题的最终解决方案. 会议参与者包括来自多个政府部门的代表，包括外交部、司法部、内政部和国家部的国务秘书，以及党卫军代表。 +
**根据该方案 ，德国占领区欧洲的大多数犹太人, 将被驱逐到被占领的波兰, 并被杀害。**
在会议过程中，海德里希概述了如何将欧洲犹太人围捕, 并送往总督府 （波兰被占领区）的灭绝营 ， 在那里他们将遭到杀害 。

海德里希强调，*一旦驱逐程序完成，被驱逐者的命运, 将成为党卫军职权范围内的内部事务。次要目标是对"谁是犹太人"做出定义 。*

1933 年 1 月纳粹夺取政权后，德国立即开始合法化歧视犹太人。 纳粹主义意识形态汇集了反犹主义、 种族卫生和优生学等元素，*并将它们与##"泛日耳曼主义"##(类似##"泛斯拉夫主义"##?)和"领土扩张主义"结合起来，目的是为日耳曼民族获取更多的生存空间。 #纳粹德国试图通过入侵波兰和苏联来获取这片新领土，意图驱逐或消灭生活在那里的"犹太人"和"斯拉夫人" ，因为他们被视为低于雅利安人优等民族 。#*

当时，##**欧洲大部分地区对犹太人的歧视由来已久，但这种歧视并没有明确写入法律规定中。**##1933 年 1 月 30 日##**纳粹夺取政权后，德国立即将这种歧视纳入法典。**##

- 同年 4 月 7 日通过的 《恢复专业公务员制度法》 将大多数犹太人排除在法律职业和公务员队伍之外。类似的立法很快又剥夺了其他犹太人从事其职业的权利 。  +

- 政权使用暴力和经济压力, 迫使犹太人离开该国。 犹太企业被拒绝进入市场，禁止在报纸上做广告，并被剥夺了获得政府合同的机会。公民们受到骚扰，遭到暴力袭击，他们的企业还遭到抵制。

- 1935 年 9 月， **"纽伦堡法案"颁布，禁止犹太人与日耳曼血统的人通婚，**禁止犹太人与德国人发生婚外性关系 ，禁止雇用 45 岁以下的德国妇女在犹太家庭担任家佣。

- *《公民法》规定，只有具有德国血统或相关血统的人才被定义为公民；因此，犹太人和其他少数群体被剥夺了德国国籍。*

- 11 月颁布的一项补充法令, 将有三名犹太祖父母或两名祖父母（如果信奉犹太教）的人, 定义为犹太人。

*到 1939 年欧洲第二次世界大战爆发时，德国 43.7 万犹太人中, 约有 25 万移民到美国、英国托管地巴勒斯坦 、英国和其他国家。*

====

Now even before the Wannsee Conference, the Nazis had been building death camps 死亡集中营 to put Jews to death. And to be fair 公平地说, it wasn't only Jews -- and we'll talk more about those other groups in a moment 立即,一会儿,马上. Now `主` #the death camps# -- `主` the most notorious (a.)臭名昭著的 of which `系` were Auschwitz 奥斯威辛集中营 and Dachau 达豪集中营 -- `系` #were# the Nazis' way of systematizing (v.)使系统化,；使成体系；使条理化, *making* _more efficient_ (a.) *the process* of mass extermination. +

[.my2]
如今那些死亡集中营——其中最著名的就是奥斯威辛和达豪集中营——是纳粹用来将"大规模灭绝行动"系统化、使其效率更高的手段。

So essentially 本质上，根本上；大体上，基本上, whenever Germany occupied a territory 占领领土 in the war, they *rounded up* 将…聚拢起来；使聚集;围捕；集合 all the Jews in that area, packed 塞满 them tightly into train cars (火车车厢) 把他们紧紧地塞进火车车厢, and then shipped them to the death camp. Once they arrived, each one of them had a brief medical examination. About 20 to 30% of them -- mostly men -- were sent to work (v.) in the camp /on behalf of 因为某人；为了某人;为帮助某人 the German war effort 为德国的"战争努力"工作, and the other 70 to 80% were murdered (v.) shortly thereafter 不久之后. +

The group who did not *make the cut* 达到标准,成功入选,被选中,通过选拔,晋级,符合要求 were told that /they would be showered (v.) and deloused (v.)除虱. So they were made 被强迫,被逼迫,被命令 to remove their clothes /and then forced into a massive concrete box 混凝土箱  with shower heads 淋浴花洒. Sometimes they understood what was happening /and they resisted 抵制；抵抗，回击, but other times they did not. But once they arrived in that box, the doors were closed /and it was pumped (v.)用泵送；打气 full of hydrogen cyanide (氰化物) 氰化氢, and five minutes later /they were dead. And in this way, around 6 million Jews were murdered by the Nazis. +

[.my1]
.案例
====
.make the cut
"Make the cut" 是一个源自体育（如比赛选拔）或日常筛选的习语，意思是 ​​“达到标准”、“成功入选”、“被选中”​​。 +
- 500 people applied for the job, but only 50 *made the cut*.（500人申请了这份工作，但只有50人被选中。）
====

And Hitler's dedication 献身；奉献;专注；执着 to this atrocity 暴行 was so great /that `主` the transportation 运输，运送 of Jews to the death camps `谓` always took priority (n.)优先；优先权 on the rail lines, even if there was a desperate need 迫切需要 on the warfront 前线. +

[.my1]
.案例
====
.atrocity
-> 来自PIE*火。-oc, 同词根op, 眼睛，见optic, 光学的。指发狂，暴行，眼睛射出火。
====

Now in addition to the Jews, Nazis targeted (v.) other groups for extermination 消灭；根绝 as well, and as a result 因此,作为结果 /another four to five million people were killed *in addition to* 除了……之外 the Jews. The Roma people 罗姆人 were also judged to be an inferior race 劣等种族, and for that -- although the number is debated -- up to 1.5 million of them were exterminated. Additionally, the Nazis targeted (v.) homosexuals 同性恋者, Slavic people 斯拉夫人, and people with disabilities 残疾人 to be killed (最好改成 for killing) in the death camps. +

All right, that's it. If you need more help with Unit 8, click right here. Thanks for sticking with me through this difficult video, and I will see you in the next one. +

'''

== 中文释义

实际上，第二次世界大战一个极其具有毁灭性的后果是纳粹大规模灭绝犹太人的政策，也就是人们熟知的大屠杀（Holocaust）。在这个视频中，我们将探讨它发生的原因以及造成的后果。 +

阿道夫·希特勒（Adolf Hitler）在德国掌权后，丝毫不掩饰驱使他行动的种族主义动机。要知道，希特勒认为现代德国人是一个被称为雅利安人（Aryans）的古代日耳曼语系民族的后裔，这让他感到无比宽慰。希特勒以及和他想法一致的人认为, 雅利安人是地球上的优等种族，因此优等种族理应在世界上占据主导地位。希特勒洗脑自己，坚信对现代优等种族的繁荣构成最致命威胁的, 是欧洲的犹太人群体。所以希特勒掌权后，就开始实施政策, 来建立这种新的种族秩序。 +

从1935年开始，希特勒的"反犹政策"相较于后来的情况还算温和。这个计划的第一个重大版本以**《纽伦堡法案》（Nuremberg Laws）的形式出现，该法案将希特勒的"种族主义"意识形态写入法律。第一条法律规定，##只有拥有纯正德国血统的人才能成为公民，因此犹太人被剥夺了公民身份。##第二条法律规定，纯种德国人与犹太人通婚是非法的。** +

**到了1939年，希特勒的政策转向让犹太人移民。**记住，“emigration”（移民出境）指的是人们离开一个国家；“immigration”（移民入境）指的是人们进入一个国家。基于这个想法，最全面的计划是把所有犹太人运往非洲的马达加斯加岛（Madagascar）。*然而，第二次世界大战爆发后，希特勒没有时间和精力去处理犹太人移民计划中的复杂问题，从那时起，情况变得更加黑暗。* +

*1942年，召开了一次名为"万湖会议"*（Wannsee Conference）的会议，纳粹领导人莱因哈德·海德里希（Reinhard Heydrich）、海因里希·希姆莱（Heinrich Himmler）和希特勒**阐述了后来被称为解决犹太人问题的“最终方案”（Final Solution）。这个“最终方案”不是让犹太人移民，而是将他们彻底灭绝。** +

实际上，在万湖会议之前，纳粹就已经在建造死亡集中营来处决犹太人。公平地说，受害者不只是犹太人 —— 我们一会儿会更多地谈到其他群体。这些死亡集中营 —— 其中最臭名昭著的是奥斯威辛集中营（Auschwitz）和达豪集中营（Dachau） —— 是纳粹将大规模灭绝系统化、提高灭绝效率的手段。 +

基本上，德国在战争中占领一个地区后，就会围捕该地区的所有犹太人，把他们紧紧地塞进火车车厢，然后运往死亡集中营。他们到达后，每个人都要进行简短的体检。大约20%到30%的人 —— 主要是男性 —— 被送去集中营为德国的战争努力工作，另外70%到80%的人随后不久就被杀害了。 +

那些不符合工作条件的人, 被告知他们要去洗澡和除虱。于是他们被迫脱掉衣服，然后被赶进一个装有淋浴喷头的巨大混凝土房间。有时他们明白即将发生什么并进行反抗，但有时他们并不清楚。但一旦他们进入那个房间，门就会关上，然后往里面注入氰化氢，五分钟后他们就死了。通过这种方式，大约600万犹太人被纳粹杀害。 +

希特勒对这一暴行极为执着，以至于将犹太人运往死亡集中营的运输, 在铁路运输中总是优先进行，即使在战争前线急需运输物资的时候也是如此。 +

除了犹太人之外，纳粹还将其他群体列为灭绝对象，结果除了犹太人之外，又有四五百万的人被杀害。罗姆人（Roma people）也被判定为劣等种族，为此 —— 尽管具体数字存在争议 —— 多达150万的罗姆人被灭绝。此外，*纳粹还将同性恋者、斯拉夫人（Slavic people）和残疾人送往死亡集中营处决。* +

好了，就讲到这里。如果你在第8单元需要更多帮助，点击这里。感谢你坚持看完这个沉重的视频，我们在下个视频再见。 +

'''

== pure

Now one of the more devastating outcomes of World War II was the Nazi policy of the mass extermination of the Jews, and what became known as the Holocaust. And in this video, we're going to look at why it happened and its results.

So when Adolf Hitler came to power in Germany, he made no attempt to hide the racialist motivations that drove his actions. You see, Hitler came to find great comfort in the fact that modern Germans were the descendants of an ancient group of Germanic-speaking peoples known as the Aryans. Hitler and the rest who thought like him believed the Aryans were the master race of the earth, and thus the master race ought to claim its place of ascendancy in the world. And Hitler trained his mind to believe that the most virulent threat to the flourishing of the modern master race was the Jewish population of Europe. And so once Hitler had come to power, he began implementing policies to establish this new racial order.

So starting in 1935, Hitler's anti-Jewish policies were mild compared to what they would later become. The first major iteration of this plan came in the form of the Nuremberg Laws, which put Hitler's racialist ideology into law. The first law established that only people of pure German blood could be citizens, and thus Jews were stripped of their citizenship. The second law made it illegal for pureblood Germans to intermarry with Jews.

And then in 1939, Hitler's policy shifted towards Jewish emigration. Remember, emigration is when people leave a country; immigration is when people come into a country. Now the most robust plan coming out of this idea was to ship all the Jews to the African island of Madagascar. However, when World War II started, Hitler no longer had the time or attention to manage the complexities of his Jewish emigration plans, and that's when things turned much darker.

In 1942, something called the Wannsee Conference was held in which Nazi leaders Reinhard Heydrich, Heinrich Himmler, and Hitler articulated what became known as the Final Solution to the Jewish problem. And the Final Solution was not the emigration of Jews, but rather their complete extermination.

Now even before the Wannsee Conference, the Nazis had been building death camps to put Jews to death. And to be fair, it wasn't only Jews -- and we'll talk more about those other groups in a moment. Now the death camps -- the most notorious of which were Auschwitz and Dachau -- were the Nazis' way of systematizing, making more efficient the process of mass extermination.

So essentially, whenever Germany occupied a territory in the war, they rounded up all the Jews in that area, packed them tightly into train cars, and then shipped them to the death camp. Once they arrived, each one of them had a brief medical examination. About 20 to 30% of them -- mostly men -- were sent to work in the camp on behalf of the German war effort, and the other 70 to 80% were murdered shortly thereafter.

The group who did not make the cut were told that they would be showered and deloused. So they were made to remove their clothes and then forced into a massive concrete box with shower heads. Sometimes they understood what was happening and they resisted, but other times they did not. But once they arrived in that box, the doors were closed and it was pumped full of hydrogen cyanide, and five minutes later they were dead. And in this way, around 6 million Jews were murdered by the Nazis.

And Hitler's dedication to this atrocity was so great that the transportation of Jews to the death camps always took priority on the rail lines, even if there was a desperate need on the warfront.

Now in addition to the Jews, Nazis targeted other groups for extermination as well, and as a result another four to five million people were killed in addition to the Jews. The Roma people were also judged to be an inferior race, and for that -- although the number is debated -- up to 1.5 million of them were exterminated. Additionally, the Nazis targeted homosexuals, Slavic people, and people with disabilities to be killed in the death camps.

All right, that's it. If you need more help with Unit 8, click right here. Thanks for sticking with me through this difficult video, and I will see you in the next one.

'''