
= 9.12 Controversial MEDICAL Technology in the 20th Century
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

So in the 20th and 21st century, there are a whole host of 大量的 medical theories and technologies that cured diseases, gave people more control over their bodies, and extended the European lifespan 寿命. Well, that sounds pretty great, right? But here's -- here's where I tell you that despite these advances, there were some serious moral and religious debates surrounding them, and I reckon 认为 we ought to talk about it. So if you're ready to get them brain cows milked, let's get to it. +

So to begin, let me just give you a taste of some of these new technologies, and then afterward we'll look at the social and moral questions that they poke. The first medical technology we'll consider is the birth control pill 避孕药. It was developed in large part by the funding and support of American feminist Margaret Sanger, and pretty quickly came to Europe. And it really was a revolution for women. The pill contained hormones 荷尔蒙 that, when ingested 摄入；吞食, could keep a woman from getting pregnant -- or at least decrease the likelihood 可能性 drastically 大幅地. As I mentioned in my video on second wave feminism, many women heralded 欢呼；宣称 this pill as a means by which they could gain control over their reproductive organs 生殖器官. +

The second medical technology we'll consider is the increasing safety of the abortion procedure 堕胎手术. Now abortion 堕胎 itself was of course a very ancient practice and was in no way new, but what was new was the scientific precision 科学精准度 with which the procedure could be done. With antiseptic tools 消毒工具 and antibiotics 抗生素 that could guard against infection 防止感染, abortion became a far safer procedure for those women who chose to elect it. +

The third medical technology we'll consider is fertility treatment 生育治疗. For much of European history, if a woman was unable for whatever reason to have a child, it was considered a kind of judgment from God. It was God who opened the womb 子宫 and God who closed it. But in the 20th century, scientists began to understand the causes of infertility 不孕不育 and develop medical procedures to address it. Probably the most revolutionary was a procedure called in vitro fertilization 体外受精. Now "in vitro" is Latin for "in glass," and the idea here is that through the use of highly technical equipment, an egg and a sperm 精子 could be united outside a woman's body -- which is to say in a glass test tube 试管. That's why these babies were often called test tube babies, the first of which was born in England in 1978. +

And finally, the fourth technology to consider is genetic engineering 基因工程. Now to be fair, genetic engineering so to speak has also had a long history -- like when farmers decided to breed 培育 their best cows or you know whatever so that good cows would be born, that's technically genetic engineering. But in the 20th century, scientists discovered that they could actually alter 改变 the genetic code 遗传密码 of the DNA of organisms 生物体. Now in some cases, the scientists were able to cure certain genetic diseases, but it was not without controversy 争议. +

And speaking of which, let's go on to the objections 反对意见 people had about these new medical technologies in theory. Now in addition to the medical technologies I already mentioned, there were metric buttloads of other medical interventions 医疗干预 that caused people to have longer lives, and you would think that would be great -- and it is -- but these medical treatments caused some significant questions about society. For example, remember what I said in another Unit 9 video, namely that in the post-war era many European countries became welfare states 福利国家, which is to say they provided medical care to their populations from cradle to grave 从摇篮到坟墓. So the problem with people living longer lives is that they end up costing more money to care for medically, and remember that states paid for the medical care through taxes. And so as people began living longer, more taxes were required to continue offering health care, and if history has taught us anything, ain't nobody want to pay more taxes. +

So that was an example of a social question that arose because of new medical interventions. But now let's get to those juicy moral questions and debates. As far as birth control and abortion went, the main moral objector 道德反对者 here was the Roman Catholic Church 罗马天主教会. The church continued to hold the belief that God opened and closed the womb, and thus to forcibly close the womb with the pill was essentially acting as if you were God himself. And in terms of abortion, Catholics believe that life began at the moment of conception 受孕；受精 -- like as soon as the sperm fertilized the egg you had a human being. According to the Bible, human beings are made in the image of God, and more to the point by the agency of God. Therefore, by their reckoning 据他们估计, to abort a child was tantamount to 等同于 murder 谋杀. +

The Catholic Church also strongly protested in vitro fertilization for similar reasons -- if God closes the womb, who are we to forcibly open it with a test tube? And then in terms of genetic engineering, a big objection had to do with eugenics 优生学, which is essentially the process for weeding out 淘汰 the undesirables 不受欢迎的人或事物 in society and encouraging the multiplication 繁衍 of the desirables 合意的人或事物. Not to put too fine a point on it, but Hitler's Final Solution 希特勒的最终解决方案 was considered an experiment in eugenics because he wanted to eliminate 消除 whole races of people and leave behind only the inheritors of Aryan genealogy 雅利安血统的继承者. But now with genetic engineering, scientists could alter human characteristics 特征 at the level of the fertilized egg 受精卵, and that was scary to a lot of people. +

All right, click here to keep reviewing for Unit 9. Since that national exam is coming up, click here to grab my AP Euro review pack, which has everything you need to get a five on that exam. I'll catch you on the flip-flop. I'm Laura. +

'''

== 中文释义

在20世纪和21世纪，出现了大量的医学理论和技术，它们治愈了疾病，让人们对自己的身体有了更多的掌控，还延长了欧洲人的寿命。听起来相当不错，对吧？但这正是我要告诉你的，尽管有这些进步，围绕它们还是产生了一些严重的道德和宗教方面的争论，我觉得我们应该谈谈这个。所以，如果你准备好获取知识，那就开始吧。 +

首先，让我先给你介绍一些这些新的技术，然后我们再看看它们引发的社会和道德问题。我们要考虑的第一项医学技术是避孕药。它在很大程度上是在美国女权主义者玛格丽特·桑格（Margaret Sanger）的资助和支持下研发出来的，并且很快传到了欧洲。这对女性来说真是一场革命。这种药丸含有荷尔蒙，服用后可以防止女性怀孕 —— 或者至少大幅降低怀孕的可能性。就像我在关于第二次女权运动的视频里提到的，许多女性把这种药丸视为一种让她们能够掌控自己生殖器官的手段。 +

我们要考虑的第二项医学技术, 是"堕胎手术"安全性的提高。堕胎本身当然是一个非常古老的行为，并不是什么新鲜事，但新的是进行堕胎手术的科学精准度。有了防腐工具和可以预防感染的抗生素，对于那些选择堕胎的女性来说，堕胎手术变得安全多了。 +

我们要考虑的第三项医学技术, 是生育治疗。在欧洲历史的大部分时间里，如果一个女性因为某种原因无法生育孩子，这被认为是上帝的审判。是上帝决定是否让女性怀孕。但在20世纪，科学家们开始了解不孕不育的原因，并开发出治疗的医学程序。最具革命性的可能是一种叫做**"体外受精"（in vitro fertilization）的程序。“in vitro” 是拉丁语，意思是 “在玻璃器皿中”，这个技术的理念是通过使用高科技设备，卵子和精子可以在女性体外结合 —— 也就是说在一个玻璃试管中。这就是为什么这些婴儿通常被称为试管婴儿，**第一个试管婴儿于1978年在英国诞生。 +

最后，我们要考虑的第四项技术是"基因工程"。公平地说，基因工程也有着悠久的历史 —— 比如当农民决定培育他们最好的奶牛时，从技术上来说，这就是基因工程。但在20世纪，科学家们发现他们实际上可以改变生物体DNA的遗传密码。在某些情况下，科学家们能够治愈某些遗传疾病，但这并非没有争议。 +

说到这里，让我们接着谈谈人们在理论上, 对这些新医学技术的反对意见。除了我已经提到的医学技术外，还有大量其他的医学干预措施, 延长了人们的寿命，你可能会觉得这很棒 —— 确实很棒 —— 但这些医学治疗, 引发了一些关于社会的重大问题。例如，还记得我在第9单元的另一个视频里说过，*战后许多欧洲国家变成了福利国家，也就是说它们为民众提供从出生到死亡的医疗保健。所以##人们寿命延长带来的问题是，医疗护理的成本更高了，而且要记住，国家是通过税收来支付医疗费用的。##所以随着人们寿命的延长，需要更多的税收来继续提供医疗保健，而历史告诉我们，#没人愿意多交税。#* +

这就是新的医学干预措施, 引发的社会问题的一个例子。但现在, 让我们来谈谈那些引人关注的道德问题和争论。就避孕药和堕胎而言，主要的道德反对者是罗马天主教会（the Roman Catholic Church）。教会仍然认为是上帝决定是否让女性怀孕，所以通过避孕药强行阻止怀孕，本质上就像是在扮演上帝。就堕胎而言，天主教徒认为, 生命从受孕的那一刻开始 —— 也就是说，精子使卵子受精的那一刻就有了一个人。根据《圣经》，人类是按照上帝的形象创造的，更关键的是由上帝主宰。因此，按照他们的观点，堕胎就等同于谋杀。 +

天主教教会也基于类似的原因, 强烈抗议"体外受精" —— 如果是上帝决定是否让女性怀孕，那我们又有什么权力用试管强行打开子宫呢？然后就基因工程而言，一个重大的反对意见与"优生学"有关，"优生学"本质上是一种淘汰社会中不受欢迎的人, 并鼓励受欢迎的人繁衍的过程。说得直白一点，希特勒的 “最终解决方案” 被认为是"优生学"的一个实验，因为他想消灭整个种族，只留下雅利安血统的继承者。但现在有了基因工程，科学家们可以在受精卵的层面上改变人类的特征，这让很多人感到恐惧。 +

好的，点击这里继续复习第9单元。由于全国性考试即将到来，点击这里获取我的AP欧洲史复习资料包，它包含了你在考试中得5分所需的一切。回头见。我是劳拉（Laura）。 +

'''

== pure

So in the 20th and 21st century, there are a whole host of medical theories and technologies that cured diseases, gave people more control over their bodies, and extended the European lifespan. Well, that sounds pretty great, right? But here's -- here's where I tell you that despite these advances, there were some serious moral and religious debates surrounding them, and I reckon we ought to talk about it. So if you're ready to get them brain cows milked, let's get to it.

So to begin, let me just give you a taste of some of these new technologies, and then afterward we'll look at the social and moral questions that they poke. The first medical technology we'll consider is the birth control pill. It was developed in large part by the funding and support of American feminist Margaret Sanger, and pretty quickly came to Europe. And it really was a revolution for women. The pill contained hormones that, when ingested, could keep a woman from getting pregnant -- or at least decrease the likelihood drastically. As I mentioned in my video on second wave feminism, many women heralded this pill as a means by which they could gain control over their reproductive organs.

The second medical technology we'll consider is the increasing safety of the abortion procedure. Now abortion itself was of course a very ancient practice and was in no way new, but what was new was the scientific precision with which the procedure could be done. With antiseptic tools and antibiotics that could guard against infection, abortion became a far safer procedure for those women who chose to elect it.

The third medical technology we'll consider is fertility treatment. For much of European history, if a woman was unable for whatever reason to have a child, it was considered a kind of judgment from God. It was God who opened the womb and God who closed it. But in the 20th century, scientists began to understand the causes of infertility and develop medical procedures to address it. Probably the most revolutionary was a procedure called in vitro fertilization. Now "in vitro" is Latin for "in glass," and the idea here is that through the use of highly technical equipment, an egg and a sperm could be united outside a woman's body -- which is to say in a glass test tube. That's why these babies were often called test tube babies, the first of which was born in England in 1978.

And finally, the fourth technology to consider is genetic engineering. Now to be fair, genetic engineering so to speak has also had a long history -- like when farmers decided to breed their best cows or you know whatever so that good cows would be born, that's technically genetic engineering. But in the 20th century, scientists discovered that they could actually alter the genetic code of the DNA of organisms. Now in some cases, the scientists were able to cure certain genetic diseases, but it was not without controversy.

And speaking of which, let's go on to the objections people had about these new medical technologies in theory. Now in addition to the medical technologies I already mentioned, there were metric buttloads of other medical interventions that caused people to have longer lives, and you would think that would be great -- and it is -- but these medical treatments caused some significant questions about society. For example, remember what I said in another Unit 9 video, namely that in the post-war era many European countries became welfare states, which is to say they provided medical care to their populations from cradle to grave. So the problem with people living longer lives is that they end up costing more money to care for medically, and remember that states paid for the medical care through taxes. And so as people began living longer, more taxes were required to continue offering health care, and if history has taught us anything, ain't nobody want to pay more taxes.

So that was an example of a social question that arose because of new medical interventions. But now let's get to those juicy moral questions and debates. As far as birth control and abortion went, the main moral objector here was the Roman Catholic Church. The church continued to hold the belief that God opened and closed the womb, and thus to forcibly close the womb with the pill was essentially acting as if you were God himself. And in terms of abortion, Catholics believe that life began at the moment of conception -- like as soon as the sperm fertilized the egg you had a human being. According to the Bible, human beings are made in the image of God, and more to the point by the agency of God. Therefore, by their reckoning, to abort a child was tantamount to murder.

The Catholic Church also strongly protested in vitro fertilization for similar reasons -- if God closes the womb, who are we to forcibly open it with a test tube? And then in terms of genetic engineering, a big objection had to do with eugenics, which is essentially the process for weeding out the undesirables in society and encouraging the multiplication of the desirables. Not to put too fine a point on it, but Hitler's Final Solution was considered an experiment in eugenics because he wanted to eliminate whole races of people and leave behind only the inheritors of Aryan genealogy. But now with genetic engineering, scientists could alter human characteristics at the level of the fertilized egg, and that was scary to a lot of people.

All right, click here to keep reviewing for Unit 9. Since that national exam is coming up, click here to grab my AP Euro review pack, which has everything you need to get a five on that exam. I'll catch you on the flip-flop. I'm Laura.

'''