
= 9.6 Post-WWII DEMOCRACIES in Europe
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义

Okay, so we've talked extensively about how states in the Soviet Bloc fared 进展；遭遇 during the post-war years, but you didn't think we weren't going to talk about Western democracies and how they fared, did you? You so crazy. So if you're ready to get them brain cows milked democratically, then let's get to it. +

Now, back at the beginning of this unit, we talked about how right after World War II ended, Western Europe was in a bad way economically. But then came along those sweet American dollars in the form of the Marshall Plan 马歇尔计划, which invested 13 billion dollars into Western Europe's reconstruction 重建. All of those states that accepted Marshall Plan dollars enjoyed more or less a drastic 急剧的；激烈的 increase in prosperity 繁荣 during the 1950s and 1960s. +

Now to be clear, it wasn't only the Marshall Plan that led to this unprecedented 前所未有的 growth in European economies -- though it certainly helped to get it off the ground quickly. In addition, many European governments made strong policy decisions that put economic recovery 经济复苏 at the forefront  forefront. And mainly, this is because these states saw what happened after the First World War. You remember that global economic crisis called the Great Depression 大萧条? Yeah, they did too. And so these Western states put forward economic policies to avoid a repeat of that disaster. +

So for the most part, Western European states after the war embraced liberal democratic principles 自由民主原则 and Keynesian economics 凯恩斯主义经济学. If you don't remember what that is from Unit 8, let me explain it up real nice for you. Keynesian economics basically comes down to the idea that it's the government's job to stimulate the economy 刺激经济, and it does that by increasing government spending 政府支出. So during the 1950s and 1960s, Western democratic states increased their government spending by roughly a metric buttload. +

And one of the significant effects of governments taking a major role in the economy is that they began offering significant welfare benefits 社会福利 to their population. Now when we're talking about governments offering these kinds of social programs 社会项目 to their people, the term for that is welfare state 福利国家. So many Western European nations now became welfare states during this period. And let me show you how that worked out. +

But hold on, I said "now became welfare states" as if this is a new phenomenon, but that needs to be qualified 限定；修饰. The welfare state had its roots in Bismarck's Germany in the second half of the 19th century. He implemented insurance for people who got injured in their jobs and old age pensions 养老金 for those too old to work. So the newness that I'm referring to is how widespread this idea of the welfare state became in the post-war era. +

Now it was Great Britain who led the way in establishing a welfare state, and many other European nations followed suit 效仿. In Britain, they established low-cost or no-cost universities, subsidized health care benefits 补贴医疗福利, and unemployment insurance 失业保险 -- just to name a few. These programs were implemented by the Liberal Labour Party 自由工党, whose goal was to create a "cradle to grave" 从摇篮到坟墓 social welfare state. Now maybe that sounds great -- from the time they're born till the time they die -- but if the government is going to be responsible for all of this, that money has to come from somewhere. And where it came from was higher taxes 更高的税收. +

And for the most part, these programs were popular, and people didn't mind the higher taxes just as long as the economy was good. But when two recessions 经济衰退 hit -- one from 1973 to 1975 and the other in 1979 to 1983 -- tax revenue 税收 decreased in Britain and across Western Europe as well, and the high level of government spending was difficult to maintain. In fact, so pronounced 明显的 was the problem that economists had to invent a new term to describe it, namely stagflation 滞胀. It was a combination of two terms -- stagnant 停滞的 and inflation 通货膨胀. So the economies of Western Europe were no longer growing (that's the stagnant part), but prices were rising like mad (and that's the inflation part). +

Even so, many Western governments still spent hefty amounts 大量的 on their newly minted 新创造的 social welfare programs -- precisely because they were so popular. It's just that they had to continue that spending by running up budget deficits 预算赤字 instead of paying for them with tax income. +

Okay, click here to keep reviewing Unit 9 of AP Euro, and then click here to grab my AP Euro review pack, which is everything you need to get an A in your class and a five on your exam in May. And I'll catch you on the flip-flop. I'm Laura. +

'''

== 中文释义

好的，我们已经广泛讨论了苏联阵营中的国家在战后的情况，但你肯定不会认为我们不会讨论西方民主国家以及它们的情况，对吧？你可真会这么想啊。所以，如果你准备好以民主的视角来获取知识，那就开始吧。 +

现在，回到本单元开头，我们谈到了第二次世界大战结束后，西欧的经济状况很糟糕。但后来，美国通过马歇尔计划（the Marshall Plan）, 投入了130亿美元用于西欧的重建。在20世纪50年代和60年代，所有接受马歇尔计划资金的国家, 或多或少都实现了繁荣的大幅增长。 +

现在要明确的是，并非只有马歇尔计划导致了欧洲经济前所未有的增长 —— 不过它确实帮助欧洲经济迅速起步。此外，许多欧洲政府做出了强有力的政策决策，将经济复苏放在首位。这主要是因为这些国家看到了第一次世界大战后的情况。你还记得那场全球性的经济危机 “大萧条”（the Great Depression）吧？没错，他们也记得。所以这些西方政府提出了经济政策，以避免那场灾难的重演。 +

所以在战后，大多数西欧国家接受了自由民主原则, 和凯恩斯主义经济学（Keynesian economics）。如果你不记得第8单元中关于凯恩斯主义经济学的内容，我来好好给你解释一下。凯恩斯主义经济学的基本观点是，政府的职责是刺激经济，而刺激经济的方式是增加政府支出。所以在20世纪50年代和60年代，西方民主国家大幅增加了政府支出。 +

政府在经济中发挥主要作用的一个重要影响是，它们开始为民众提供大量的福利。现在，当我们谈到政府为民众提供这类社会项目时，有个术语叫 “福利国家”（welfare state）。所以在这个时期，许多西欧国家变成了福利国家。我来给你讲讲这是怎么回事。 +

但是等等，我说 “变成了福利国家”，好像这是一个新现象，但这需要进一步说明。**福利国家的根源可以追溯到19世纪后半叶俾斯麦（Bismarck）统治下的德国。他为工作中受伤的人, 实施了"保险制度"，并为那些年老无法工作的人, 提供了养老金。**所以我所说的新现象, 是指福利国家的理念在战后变得如此广泛。 +

**现在，英国率先建立了福利国家，许多其他欧洲国家也纷纷效仿。**在英国，他们建立了低成本或免费的大学，提供了补贴的医疗保健福利和失业保险 —— 这只是其中一些措施。**这些项目是由"自由工党"（the Liberal Labour Party）实施的，该党的目标是创建一个 “从摇篮到坟墓” 的社会福利国家。**也许这听起来很棒 —— 从出生到死亡都有保障 —— *但如果政府要承担这一切费用，钱从哪里来呢？答案是更高的税收。* +

在大多数情况下，这些项目很受欢迎，*只要经济状况良好，人们并不介意更高的税收。但当两场经济衰退来袭时* —— 一场是1973年至1975年，另一场是1979年至1983年 —— 英国以及整个西欧的**税收收入都减少了，**而且高水平的政府支出也难以维持。事实上，这个问题非常突出，经济学家不得不发明一个新术语来描述它，即 “*滞胀*”（stagflation）。这个词是 “停滞”（stagnant）和 “通货膨胀”（inflation）两个词的结合。*所以西欧的经济不再增长（这是 “停滞” 的部分），但物价却疯狂上涨（这是 “通货膨胀” 的部分）。* +

即便如此，许多西方政府仍然在新建立的"社会福利项目"上投入了大量资金 —— 恰恰是因为这些项目太受欢迎了。只是**#他们不得不通过增加预算赤字, 来维持这些福利支出，而不是用税收收入来支付。#** +

好的，点击这里继续复习AP欧洲史第9单元，然后点击这里获取我的AP欧洲史复习资料包，它包含了你在课堂上得A，在五月的考试中得5分所需的一切。回头见。我是劳拉（Laura）。 +

'''

== pure

Okay, so we've talked extensively about how states in the Soviet Bloc fared during the post-war years, but you didn't think we weren't going to talk about Western democracies and how they fared, did you? You so crazy. So if you're ready to get them brain cows milked democratically, then let's get to it.

Now, back at the beginning of this unit, we talked about how right after World War II ended, Western Europe was in a bad way economically. But then came along those sweet American dollars in the form of the Marshall Plan, which invested 13 billion dollars into Western Europe's reconstruction. All of those states that accepted Marshall Plan dollars enjoyed more or less a drastic increase in prosperity during the 1950s and 1960s.

Now to be clear, it wasn't only the Marshall Plan that led to this unprecedented growth in European economies -- though it certainly helped to get it off the ground quickly. In addition, many European governments made strong policy decisions that put economic recovery at the forefront. And mainly, this is because these states saw what happened after the First World War. You remember that global economic crisis called the Great Depression? Yeah, they did too. And so these Western states put forward economic policies to avoid a repeat of that disaster.

So for the most part, Western European states after the war embraced liberal democratic principles and Keynesian economics. If you don't remember what that is from Unit 8, let me explain it up real nice for you. Keynesian economics basically comes down to the idea that it's the government's job to stimulate the economy, and it does that by increasing government spending. So during the 1950s and 1960s, Western democratic states increased their government spending by roughly a metric buttload.

And one of the significant effects of governments taking a major role in the economy is that they began offering significant welfare benefits to their population. Now when we're talking about governments offering these kinds of social programs to their people, the term for that is welfare state. So many Western European nations now became welfare states during this period. And let me show you how that worked out.

But hold on, I said "now became welfare states" as if this is a new phenomenon, but that needs to be qualified. The welfare state had its roots in Bismarck's Germany in the second half of the 19th century. He implemented insurance for people who got injured in their jobs and old age pensions for those too old to work. So the newness that I'm referring to is how widespread this idea of the welfare state became in the post-war era.

Now it was Great Britain who led the way in establishing a welfare state, and many other European nations followed suit. In Britain, they established low-cost or no-cost universities, subsidized health care benefits, and unemployment insurance -- just to name a few. These programs were implemented by the Liberal Labour Party, whose goal was to create a "cradle to grave" social welfare state. Now maybe that sounds great -- from the time they're born till the time they die -- but if the government is going to be responsible for all of this, that money has to come from somewhere. And where it came from was higher taxes.

And for the most part, these programs were popular, and people didn't mind the higher taxes just as long as the economy was good. But when two recessions hit -- one from 1973 to 1975 and the other in 1979 to 1983 -- tax revenue decreased in Britain and across Western Europe as well, and the high level of government spending was difficult to maintain. In fact, so pronounced was the problem that economists had to invent a new term to describe it, namely stagflation. It was a combination of two terms -- stagnant and inflation. So the economies of Western Europe were no longer growing (that's the stagnant part), but prices were rising like mad (and that's the inflation part).

Even so, many Western governments still spent hefty amounts on their newly minted social welfare programs -- precisely because they were so popular. It's just that they had to continue that spending by running up budget deficits instead of paying for them with tax income.

Okay, click here to keep reviewing Unit 9 of AP Euro, and then click here to grab my AP Euro review pack, which is everything you need to get an A in your class and a five on your exam in May. And I'll catch you on the flip-flop. I'm Laura.

'''