= 1347
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to English as a Second Language Podcast’s English Café Number 42.
This is English as a Second Language Podcast English Café. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the beautiful city of Los Angeles, California.
On today's Café we're going to talk about online dating, people who find their romantic partner on the Internet - talk about some popular services here in the United States for that. We're also going to talk about the most famous prize for writing in the United States, the Pulitzer Prize. And as always, we'll answer a few of your questions.
Well, our first topic on the Café today is an interesting one, I think. It's about online dating, people who find a romantic partner on the Internet. Now, many years ago when I was much younger, back in the 1920s, there was a certain stigma about using the Internet for dating. A stigma, "stigma," it's a Greek word originally, and in English it means that people don't think it's very nice, people think that there's something wrong with it. That expression…that word rather, a stigma, is often connected with the verb attach. We say, "There's a stigma attached to online dating." There's a…it's like a bad reputation, a bad opinion that people have of it. But, things have changed in the last ten years and now many people, especially in big cities, like Los Angeles and New York, use these online dating services. There are many possible reasons why that is. Many people say that people today are not as close, the communities and families are not as close, so the opportunities to meet people, for young people, is not as great as it used to be. And so, online dating is what we call using the Internet as a matchmaker. A matchmaker, "matchmaker," all one word, is or was traditionally a person who helps find someone for you, a romantic partner for you. So, I may know a friend of mine, who's looking for a girlfriend, and I know a woman, who's looking for a boyfriend; I introduce the two people; I'm a matchmaker.
Now, in some places the matchmaker is a professional. And, you pay this person to help you meet other people. Well, the Internet has become an electronic matchmaker for these online dating services. And, there was an article in the Voice of America website about some of these dating services, and they're very sophisticated, that is, they use a lot of very complicated formulas. They ask people many different questions, and then they try to match your answers with answers that other people give. Many psychologists, professional psychologists, work with these companies to help them ask good questions and to figure out how to match people. It's a very, we would say, it's a very lucrative business. Lucrative, "lucrative," is a business that you make a lot of money at, and because there are so many people who want to find love, who want to find romance, they are…these companies make a lot of money.
Usually, when you join one of these companies, you go on to their website and you fill-out a survey. To fill-out, "fill-out," means to complete. You put your answers in; how old you are, what's your height, what's your weight; usually they'll ask for a picture, and then they'll ask you, sometimes, two or three hundred questions about all the different things you may like or not like, and these questions you have to fill-out. First, you have to answer these questions and then you send it to the computer and then computer tries to match you with someone.
I don't know the exact cost. Most of these services, I think, charge you anywhere between 30 and 50 dollars every month to use them, and there are millions of people who use these websites. One of the most popular here in the United States is called Match.com, "Match.com." And, “match,” of course, is a verb - means to put two people - in this case, to put two people together, to put something together. And, they have more than 15 million members in a couple of hundred different countries. It says in the article 240 different countries, and it is in 18 different languages. So, Match.com is a worldwide operation and you may have heard of it in your own country, if you are not listening here in the United States. Well, according to Match.com, 60,000 people join every day - 60,000 people every day! And if you imagine each of those persons paying even 25 or 30 dollars, that's a very lucrative business.
Well, the article that I got this information from interviews someone who uses the service, and she says that she was skeptical of meeting men on the Internet. To be skeptical, "skeptical," means that you have doubts, that you're not sure, that you don't think this is a good idea, you're not exactly sure, you doubt something. She said she was skeptical because she prefers traditional dating, meaning places where you would find someone, at a party or through a friend, or perhaps at a bar. She goes on to say that, "At bars, you look at someone, you smile, you wink, but not much ever seems to come out of it." The expression you wink, "wink," means that you close one of your eyes quickly. You open and close it quickly, that's to wink, "wink." She says that "you smile, you wink, but not much ever seems to come of it." The expression "to come of" here, means to result in something, nothing happens. And, she is saying she goes to bars and she may smile at a guy, and a man might smile at her, but that's it, nothing happens. And, the reason is because most men are afraid of asking women out on a date. They're afraid of asking them if they would like to go on a date, for them. I know I was, and that is a problem that you don't have in Internet dating. In Internet dating, you find someone you're interested in, they're interested in you, you meet them. Of course, after you meet them, you may hate them and decide you don't want to see them again, but at least you had a chance to meet them.
There are now, what we would call, specialty dating sites in the United States. Specialty, "specialty," is you may guess, something that is for a specific, or special interest. So, one of these sights is called “Date My Pet.” Date My Pet, "pet," like your cat or your dog, and this is for people who like dogs and cats and want to date other people who like dogs and cats. That would not be a website I would use personally. There's also one called Grapedate, "Grapedate." Grapedate.com is for people who like wine, and there are others like this.
Well, in addition to Internet dating, there's also something that has become popular in the last 10 years,15 years, called speed dating. Speed, "speed," dating. And, speed dating is when you have two groups of people, usually men and women, let's say ten in each group, and they come together for a couple of hours, and you get five or ten minutes to talk to each person, and then after that, they ring a bell and then you move to another person. So, in one night, you get to talk to 10 or 15 people. There is a website called Hurry Date, "Hurrydate," Hurrydate. To hurry means to go quickly, to go fast. And in the Hurrydate website, you can pay 35 dollars for an evening of ten minute dates, so you get to talk to a woman or a man for ten dates, for ten minutes, and then the person blows a whistle and goes, "All right everybody, next person," and then you go to the next person. Sounds kind of crazy, but many people like it. It's a way of meeting other people. Some people think that ten minutes is not enough time to really know whether you're interested in that person. I think that's probably true, but a lot of people you are able to tell, you are able to understand very quickly whether you're going to like that person or not. In fact, there's an interesting book by a writer here, who works for the magazine New Yorker, and he wrote a book called Blink, "Blink." It's by Malcolm Gladwell, "Gladwell," very good writer in English, very clear writer. And, his book is about how people are able to make decisions very quickly when they have just a little bit of information.
Well, those are some ways that dating has changed in the United States. One of my best friends from high school met his wife on one of these dating services. They met, they dated for a couple of years and they got married, and now have two children. So, sometimes, it works.
The second topic for today's Café is the Pulitzer Prize for writing. This is the most famous prize in the United States for writing. Pulitzer is "Pulitzer." There's an organization that gives these prizes every year. They have many different prizes, some go to newspapers and magazines, they go to individual writers, who do very good stories. Some of the awards go people who write plays and some of them go to people who write books, both literature, what we would call fiction, things that aren't true, as well as nonfiction, books that are about things that are true, like Malcolm Gladwell's book Blink. And, by the way, “blink,” I didn't explain. To blink is very similar to wink. "Blink," to blink usually means to open and close both of your eyes at the same time, and wink is usually just one eye.
Well, in either case, what we have in the Pulitzer Prizes is an award, or some awards, for writers. And, if you look at a list of the Pulitzer Prizes, the Pulitzer Prize winners, especially in fiction, in literature, you will see some of the best writers in the 20th century. This award began in 19…I believe it was 1917, so it's almost, not quite, 90 years old and it's, as I say, considered the most important prize. If you write a book and it wins a Pulitzer Prize in the United States, everyone will know, or least everyone who reads will know about your book.
Some of the famous authors that have won the Pulitzer Prize in the United States - and it's for American writers, or writers publishing in the United States. Let's see, some of the famous authors here - John Steinbeck. John Steinbeck won in 1940 for Grapes of Wrath, and that's a novel about people during the Great Depression. The Great Depression, "depression," is that time, from the late 1920s until 1940 - 41, where the whole world had a very difficult economic times. Many countries had many people who did not have jobs, who did not have work. And, that novel, The Grapes of Wrath, is about the people who had difficulty during that time. “Grapes,” you know, is what you get wine from, and wrath, "wrath," here it means something like anger, when you are mad, your wrath is something bad you're going to do someone else because you are angry.
Other famous writers include Ernest Hemingway. Ernest Hemingway won in 1953 for his novel The Old Man and the Sea. It's a very short novel, if you looking for a short, not too difficult novel, that's a good one. Another famous writer is Harper Lee, "Lee," and she wrote one great book called To Kill a Mockingbird. "To Kill a Mockingbird," a mockingbird is a type of bird. And, she won the prize in 1961. Her novel was later made into a movie, which was very famous in the United States. You may have seen it. It was…it had Gregory Peck, "Peck," a famous American actor. And, it's about a lawyer in the Southern United States, who is trying to protect black people, African-Americans, from people who are racist, people who don't like them because they are black. It's a very powerful story. It's a novel that many students read in high school. You might enjoy that book if you like reading in English, which I hope you do because that's an excellent way to help you in your English.
Some other readers in last 25, rather writers, some other writers in the last 25 years include Norman Mailer. Norman Mailer, "Mailer," he wrote a book called The Executioner's Song, The Executioner's Song back in 1980. Executioner is "executioner." An executioner is someone from, usually from the government, who is…who kills people for…who are prisoners, people who are…who are supposed to die because they did something very wrong. Here, in the United States, you may know that we still have the death penalty. The death, "death," penalty, "penalty," says that if you commit a very serious crime - murder - you could be killed yourself, and the novel, The Executioner's Song, is about a famous case of that in the late 1970s. Many people, of course, don't like the death penalty. Many Americans are trying to stop the death penalty, but it is still here, and in California and in Texas and in some other states. It is, they are, every year there are some people who are executed, would be the verb, and that's a very powerful book, Norman Mailer's book.
Another famous author is Toni Morrison. Toni Morrison won for a novel called Beloved. Beloved, "beloved." And she is also a very good writer. So, you can go on to the Google, or your search engine, and look for Pulitzer Prizes, and you will have their list of some of the best books written in American English in the last 90 years or so. Now let's answer a few questions.
Our first question comes from Rosella, "Rosella," Rosella from Italy. Rosella wants to know the meaning the expression "sitting duck." Sitting, "sitting," duck, "duck." Well, a duck is an animal that in a lake…on a lake or a pond. It's a bird, and you can eat duck. Many people like to eat duck. You can hunt ducks in the United States. In some states you can get a gun and go and kill a duck and take it home and eat it. I don't normally do that, but some people do, and it's popular in some states. The expression, "a sitting duck," is actually a, comes originally from this idea of hunting ducks, going out to kill ducks. If you find a duck on a lake, sitting on a lake, and they do not, the ducks do not know that you are there, it's very easy to shoot them with a rifle, "rifle," a rifle is a gun that you use to shoot when you are hunting. It's very easy to shoot the ducks, and you might call them sitting ducks because they're not trying to escape, they're not trying leave.
Usually, that expression, sitting duck, refers to someone who is very easy to attack, or someone who is very easy to hurt because they don't…they're out in an area where they don't have any protection. So, if you are a soldier, for example, in a war and you are in the desert, and you don't have a car or a tank or anything, and you are there just by yourself and someone who doesn't like you, someone from the other side in the war, comes to you with a gun, you are a sitting duck. You don't have any defense. You are very easy to attack or to hurt. And, that is an expression that we use for those sorts of situations, someone is a sitting duck when they are going to be hurt or something bad is going to happen to them because they are without any protection.
Our next question comes from Brazil, from Beto, "Beto," and his question has to do with pronunciation. His first question has to do with pronouncing words with an "ea" or "ee" in them, and words with an "i" in them. He gives some examples here, the first one would be cheap, "cheap," which means inexpensive, and chip, "chip," which could be a couple of things. A "chip" could be like a potato chip, a piece of baked or fried potato. Well, there isn't a good general rule, normally "ea" is pronounced "e" in words such as cheap and leap. The "ee" in the middle of a word is also usually pronounced "e," what we would say a long "e," so words like sheep or sleep, those are words that have that long "e" sound.
If there's an "i" in the middle of a word, it could be either a long "i" or a short "i." It depends on what else is in the word. For example, in the word "chip," there's only one vowel, the "i," and that is a short "i." But, if we were to put an "e" at the end of that word, "chipe," that's not a real word, but as an example, we would probably pronounce that made up word, that invented word, chipe, "chipe." It's that "e" at the end, which you don't pronounce, makes the "i" a long "i." An example of that, for two real words, would be strip, "strip," and stripe, "stripe." The "e" at the end makes that "i" sound like a long "i," so "strie" instead of "stri," stripe and strip.
Beto also has a question about the "th" sound, which is difficult for some speakers of other languages. The difference between “thank” and “tank.” And, he says he has a difficulty, a difficult time hearing the difference, and I agree, especially when people speak quickly in English, it is sometimes difficult to hear the "h." But, there is a difference, the "th" sound in thank is made by putting your tongue in between your teeth, whereas the word tank, "tank," which is - could be a big container, something you put water in could be called a tank. A tank, the tongue is not in between the teeth, it's up on the top of your mouth. So, thank and tank sometimes sound the same, but there is a difference between them.
Next question now comes from China, and this is Bobby, "Bobby," in China. And, the question has to do with the expression "to cross your fingers." To cross, "cross," your fingers. To cross your fingers means to hope for or to wish for good luck or good fortune. "I'm going to cross my fingers that I win the lottery." Notice we used the word that after the expression. “Cross your fingers that we win” means hope that we win, you should try to wish that we win. We use this expression in a couple of different ways. Someone can say, "I have my fingers crossed," means I'm hoping for a good result, I'm hoping for luck. Or, you can tell someone, "Cross your fingers," means hope that it will happen; you should hope that it will happen. So, that is the expression to cross, to cross, "cross," your fingers, means to put one finger in front of the other finger, so that it is like an x, like the letter "x," that's to cross your fingers. You can cross your legs also, and that's something you do when you sit down, particularly a woman, who is wearing a dress, will usually, or often, cross her legs, put one leg in front of the other. That's also an expression, but that does not mean good luck. It's just a way that someone decides to sit. Well, thank you Bobby, for that question.
That's all we have time for on this English Café. Be sure to visit our website at eslpod.com for more information about this podcast.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on English Café.
ESL Podcast’s English Cafe is written and produced by Dr. Jeff McQuillan. This podcast is copyright 2006, by the Center for Educational Development.
Glossary
stigma – a negative opinion people have about a something, some action, or activity; to be thought of in a negative way
* In the past, there was a stigma attached to being a single mother in the United States.
matchmaker – a person who finds a romantic partner (boyfriend, girlfriend) for you
* My cousin was my matchmaker. She introduced me to my new girlfriend at a party.
lucrative – an activity or business that makes a lot of money
* Being a teacher in the United States is not as lucrative as being a doctor or a lawyer.
to fill out a survey – to answer questions or complete a form asking for information or your opinions about something
* After I completed my meal at the restaurant, the manager asked me to fill out a survey about the food and the waiter who served me.
skeptical – adjective used to describe a situation or idea that you find difficult to believe; doubt about the truth of someone or something
* I’m skeptical about what you said last night about the moon. I don’t really believe that it is made of cheese, like you do.
to wink – to close and open one eye quickly; sometimes used to indicate that you like someone; can also be used to indicate to someone that what you are saying is a joke or is a secret
* I think that beautiful woman looked at me and winked, but I’m not sure.
specialty – some skill or area of specialization; a very specific talent or area of interest
* I wanted to find a specialty dating website for people who like Star Wars.
speed dating – a meeting where you get to talk to several possible romantic partners for a short amount of time to see if you want to date any of them
* My friend Roy met his girlfriend at a speed dating night.
to hurry – to go quickly
* I have to hurry so I won’t be late for my dentist’s appointment.
to blink – to close and open both eyes quickly; sometimes used to mean a very short amount of time
* I blinked and suddenly, she was gone.
executioner – a person who kills a prisoner with the permission of the government
* The executioners in the French Revolution killed the family of the king and queen.
sitting duck – used to describe someone who is easy to attack; someone without any defense against enemies
* The president usually has people who guard and protect her. If she went somewhere without the police, she would be a sitting duck.
rifle – a gun used to hunt animals or used by soldiers in a war
* My brother-in-law is going to go deer hunting with his new rifle next week.
to cross your fingers – to wish for good luck or good fortune
* I am crossing my fingers that I will pass my exam.
What Insiders Know
ENGLISH LEARNING TIPS
Listening to podcasts is a good way to improve your English listening and speaking ability. Some Internet news websites provide special programs for people who are trying to learn English. One of these is called Voice of America’s (VOA) Special English. VOA’s Special English uses easy vocabulary to talk about different news stories in the United States and in other countries. These stories are easier to read and understand than regular news stories in English. Everyday, the VOA also has an audio podcast with that day’s news. These news stories on their podcast are read at a slow rate, like ESL Podcast, so that you can understand them more easily. Although there are no explanations like you find on ESL Podcast, they are still a good way to listen to more comprehensible English.
Another website that provides special English help is the British Broadcast Company, or BBC. The BBC has a special section on its website to help people learn English through the news. The BBC website has stories written in easy language, with definitions of difficult words after some of their stories. You can read the story and listen to an audio file of someone reading the story to you.
Websites:
http://www.voanews.com/specialenglish/index.cfm
http://www.bbc.co.uk/worldservice/learningenglish/