= 1323
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You’re listening to ESL Podcast’s English Café number 18.
This is English as a Second Language Podcast’s English Café episode 18. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at ESLPod.com. On this Café, we’re going to talk about the Getty Museums in Los Angeles. We’re also going to talk about Mardi Gras and how it is celebrated in the United States. And as always, we’ll answer a few of your questions. Let’s get started.
On a previous Café, I talked about stolen art in the United States as it related in particular to one museum here in Los Angeles – the Getty Museum. I thought I would talk a little bit more, not about stolen art, but about the museum here in Los Angeles and in particular the person who paid for and founded the museum, since he himself is a very interesting man and his story tells us a little bit about the nature of American business in the twentieth century.
The Getty Museums – I’m going to use the plural because really there are two of them – were founded by a man named John Paul Getty. “To found” (found) here means to create or establish something. When John Paul Getty (who’s typically called J. Paul Getty) died, he left most of his money – that’s 1.2 billion dollars – to the museum.
Who was J. Paul Getty? He was born in December of 1892 in Minneapolis, Minnesota. Minnesota is, as some of you may know, also my home state. I was born in St Paul, Minnesota, which is right next door to the city of Minneapolis. Minnesota, if you don’t know, is located in the northern central part of the United States. Getty didn’t remain too long in Minnesota. When he was a child, his father moved here to Los Angeles and became involved in the oil business.
Many people, when they think of Los Angeles, don’t think of oil, but in fact there was, and always has been for a long time, an oil business here. In fact, there’s still an oil business. You can go to different parts of Los Angeles and see what are called “oil rigs.” These are machines that go into the ground in order to get the oil out. J. Paul Getty was from, then, a wealthy family – a family that had money. He attended the University of Oxford in England and graduated in 1913. So, he was a very bright young man.
He returned to the United States and began working in the oil business with his father. Within a very short amount of time, in a couple of years, he had made his first million dollars, and he continued to make millions of dollars working with his father at the Getty Oil Company over the next 14 years. His father died in 1930, and when he did, J. Paul Getty took over control of Getty Oil.
He went on to control a number of other oil companies and became a very, very rich man. By the middle of the 1950s, Getty had become what we would call a “billionaire” – someone who has a billion dollars or more. Getty, in addition to being a successful businessman, was also an avid art collector. “Avid” (avid) means enthusiastic or very interested in something. Getty was very interested in collecting and buying art.
In fact, he collected art from all over the world, but he was particularly interested in European art from the Renaissance and Baroque periods. This would be roughly from the fourteenth to the eighteenth centuries. Getty purchased paintings, drawings, sculpture, and furniture from this period. In 1953, J. Paul Getty decided to found or establish the Getty Trust. A “trust” (trust) is an organization that is typically managed by a group of people according to some specific purpose or instructions.
The purpose of the trust was to create a museum that would show Getty’s art to the world, but which would also pay for art education, art research, and art conservation. “Conservation” (conservation) here refers to repairing and protecting the works of art. We also use the word “conservation” when we’re talking about the environment. We try to, for example, “conserve energy” – not use too much. But when we’re talking about art, “conservation” refers to repairing and protecting it.
In 1954, the first Getty Museum opened to the public. The museum displayed, or had available for people to see, Getty’s art, and it was located in a very rich part of Southern California called Malibu. In fact, it was in a section of Getty’s own home in Malibu. Malibu is a very rich part of Los Angeles. It is right next to some of the most interesting and beautiful scenes of the ocean or views of the ocean. Getty continued to collect art, but part of the early 1970s, it was clear that Getty had too much art for his home, and so it was decided that he would build a new building that would hold the art.
Now, because Getty was such a rich man and had at this time become interested in ancient art as well, he decided to build this new museum as a replica, or a copy, of a large Roman home, a particular home called “Villa dei Papiri.” “Villa” (villa) refers to a very large home that is typically located in the country. Malibu is not exactly in the country, but it is outside of the main city of Los Angeles, and the area where Getty built the home is, in fact, fairly uninhabited. The area immediately around the home doesn’t have any other houses.
Getty then decided he would build this Roman home and use it as a museum, and he called it, of course, the Getty Villa. Unfortunately for J. Paul Getty, he never got to see the Getty Villa open as a museum or even see it when it was finally completed in June of 1976. Getty died of a heart attack in England. When he died, he left, as I mentioned previously, a large amount of his money, a large percentage of his money, to the Getty Trust. He also left money to his children.
Getty had been married and divorced five times and had five sons with four different wives, although only three of them were lucky enough to be alive at the time of Getty’s death in 1976. In addition to receiving more than a billion dollars from Getty’s estate, the Getty Trust also received part of the profits from the sale of Getty Oil to another large company called Texaco in 1984. By the early 1990s, the Getty Trust had over four billion dollars to use to run the museums and to work on the programs of art, education, and conservation.
With all this money sitting in the bank, the Getty Trust decided to open a second museum, called the Getty Center. This was to be a six-building museum built on the very top of one of the largest hills that is immediately next to the city of Los Angeles. The Getty Center was designed to hold pieces of art from the European collection, the more modern collection of J. Paul Getty. The Getty Villa would continue to have art in it, but it would be ancient art – in particular, ancient Greek and Roman art.
The new Getty Center was also to have a special building for studying art, the history of art, as well as a building dedicated to, or for the purpose of, conservation. The Getty Museum opened in the late 1990s, and when it did, it was one of the most popular tourist attractions in Southern California. In fact, it was so popular that it was almost impossible to get a ticket into the museum during the first year that it was open.
Many people went to the museum not just to see the art – which to be honest is not the greatest when it comes to museums in the United States – but rather because of the beautiful architecture, the beautiful buildings, as well as the fact that the museum is located on a hill such that if you look to the west you can see the ocean. And if you look to the east you can see the downtown area of Los Angeles – so that’s a beautiful view as well as a beautiful museum.
After the Getty Center opened – not too long after the Center opened – the Getty Trust, the Getty Museum organization, decided to close the Getty Villa and renovate it. “To renovate” (renovate) means to repair or change something, especially a building or a house. The Getty Villa was renovated. It was closed for a few years and then reopened and now holds all of the Greek and Roman art of the Getty collection.
The Getty Museum is famous not just here in Los Angeles. It’s also famous in other places because it specializes in art conservation. Pieces of art are often sent to the Getty Center to be repaired, to be fixed, to be cleaned. The Getty Museum also owns a large digital or electronic collection of images that you can go on their website and look at. If you come to the beautiful city of Los Angeles, you should try to visit the Getty Villa and/or the Getty Center. I’m sure you will enjoy it.
Now let’s turn to our second topic, Mardi Gras. Mardi Gras is an annual celebration. It’s sort of a Christian “holiday,” we might call it, that takes place on the Tuesday before Ash Wednesday. I say it’s a “Christian holiday.” It’s not officially a holiday in most churches, but it is a day that Christians in some traditions celebrate. Why are they celebrating on Mardi Gras? Well, because it takes place on the Tuesday before another important day, Ash Wednesday.
Ash Wednesday is the beginning of an approximately 40-day period of Lent in some of the Christian churches, including the Catholic Church. “Lent” (lent) is a time of prayer, a time of denying yourself certain pleasures in order to prepare yourself for the great feast in the Christian calendar, which is Easter. Many Christians, especially Catholics, fast during this period. They only eat smaller amounts of food and/or they abstain, or don’t eat certain kinds of food. This is also true in many of the Orthodox churches.
Now, if you’re going to be fasting and abstaining from certain foods during a period of 40 days, you might want to, just before you started that period, eat a little bit more, drink a little bit more, get your last taste, if you will, of certain kinds of food before the beginning of this 40-day Lenten period. This is, in fact, the origin of what we call “Mardi Gras.” The words “Mardi Gras” mean, in French, “Fat Tuesday.”
Basically it refers to a time where people often drink to excess. To drink “to excess” (excess) means to drink (or eat) too much. In some cultures, this day or the period before Lent is also called “Carnival.” Mardi Gras celebrations are quite common. Some people say that the original celebrations that were similar to Mardi Gras actually go back to pagan festivals. “Pagan” (pagan) describes any religious practice that is not related to the major religions of the world – that is, Christianity, Judaism, Islam, and other major religions.
I’m not quite sure if this story is true about pagan origins of Mardi Gras, but it is true that it is a popular celebration in certain parts of the United States, in particular in areas that the French settled when they came here back in the seventeenth – sixteenth and seventeenth centuries.
One particular area that has a very strong influence of French culture is the state of Louisiana, which is located in the south-central part of the U.S. There’s a strong tradition of French culture, or at least French-influenced culture, in Louisiana. In particular, one of the largest cities in Louisiana – New Orleans – has a tradition of celebrating Mardi Gras each year.
The first celebration of Mardi Gras in New Orleans was back in 1781, and it continues to be celebrated every year. The celebration in New Orleans is much longer than just the one day of Tuesday before Ash Wednesday. In fact, it can go on as long as two weeks. If you go to New Orleans during the two weeks before Ash Wednesday, you will see lots of celebrations, lots of parties, and a huge parade where people dress up and walk down the street.
The parade is sponsored by a group called the “School of Design.” “To sponsor” (sponsor) means to pay for a certain activity or an event. In the parade, you’ll also see floats. “Floats” (floats) are large, decorated vehicles that people ride on during a parade. You see floats in all sorts of parades in the United States, not just in the Mardi Gras parade, but the Mardi Gras parade is famous for its floats. The floats are made and paid for by different private clubs and organizations, called “Krewes” (Krewes).
Many people think that Mardi Gras is only celebrated in New Orleans, but of course the celebration of Mardi Gras takes place in many different cities in the U.S. – but it’s most famous in the city of New Orleans. If you’re planning to go to New Orleans during the spring of the year, during the time period in which Mardi Gras is celebrated, you certainly want to look at your calendar. It will be much more expensive and much more crowded during the weeks of Mardi Gras. So, you just need to keep that in mind.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Ritesh (Ritesh). Ritesh wants to know the difference between two expressions, “have to” and “need to.” When we say we “have (have) to” do something, how is that different than saying we “need (need) to” do something?
Well, really they mean the same thing. If you say you have to buy some new shoes, you mean the same as if you had said, “I need to buy some new shoes.” Both of these mean that it is necessary that you do this thing. There is some reason you must do it. They’re both equally common, I think – maybe “have to” is a little more common than “need to” in conversational English – but really they mean the same thing and you can use either one to mean the same thing.
Our next question comes from Guillain (Guillain). Guillain is from France. The question has to do with the word “hype” (hype). “Hype” refers to excited or enthusiastic discussion about something, usually an excitement or an enthusiasm that is more than what you really should be feeling about this particular thing. “Hype” is often used to talk about publicity and advertisement – when a company tries to get everyone excited about its new product.
Often hype is used in a negative way to refer to exaggerated claims about the product. When the company says, “Oh, it will make your life wonderful. You’ll be beautiful and find a beautiful woman if you use this product,” well, that would be considered “hype” – exaggeration regarding the product itself.
Our next question comes from Jean Luca (Jean Luca) from Italy. The question is about an expression, “no-brainer.” “No-brainer” (brainer) means that you don’t have to think about it. It’s a noun describing a situation where the conclusion is obvious or what you should do is obvious. If it’s raining and you have an umbrella that is used to protect you from the rain, it’s a no-brainer that you take the umbrella with you so that you don’t get wet. You don’t even have to think about it. It’s very obvious. “That’s a no-brainer.”
Notice that you can’t say the opposite. You can’t say, “It’s a brainer.” We would never say that. You can only say it’s a “no-brainer,” meaning it doesn’t require the use of your mind, your brain, your head because it’s so obvious.
Finally we have a question from Benjamin (Benjamin), who I believe is also from France. Benjamin wants to know some of the meanings of the word “would” (would). I could talk a long time about the uses of the word “would,” but let me just focus on two of the most common ones.
The first is the use of “would” as a conditional. A “conditional” refers to an action that relies on another action to take place first. For example, “If he gave me money, I would go to the store.” Under the condition of him giving me the money, I would go to the store, but only if that happened. The use of a conditional also implies what we might call a “hypothetical.” He may not give me any money and I may not go to the store, but if he gave me money, then I would go to the store.
“Would” is also used sometimes in describing an activity in the past that happened over and over again. If someone says, “When I was in high school, I would go to the football game every Friday night,” that means that repeatedly, over and over again, I went to a football game when I was in high school. The “would,” then, is used to mean the same thing as another expression, “used to.” “I used to go to the football game.” “I would go to the football game.” If we’re referring to something in the past, those expressions mean the same thing.
If you have a question or comment you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on ESL Podcast.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. This podcast is copyright 2006 by the Center for Educational Development.
Glossary
to reopen – to open something again after having closed it; to make a place, service, or business available again after closing it for a period of time
* The bookstore closed down last year, but the owner decided to reopen it once a new investor offered money to start the business up again.
museum – a building where valuable or important objects, like artwork or historical items, are kept and displayed for visitors to see
* Shae went to the art museum to look at the new Van Gogh exhibit.
renovation – the act of changing a room or entire building to make it better; the process of changing an old room or building so that it looks new and updated
* Bill and Maritza had an old kitchen with peeling wallpaper, chipped floor tile, and appliances that barely worked, so they decided on a kitchen renovation.
to tear down – to remove something so that no part of it is left; to destroy something until nothing remains
* Adam tore down the old shed in his backyard to create more space.
villa – a country estate; a large house located in a quiet location away from large cities and a lot of people, usually where a wealthy family lives
* During the summer, Rosalyn’s family stayed in a villa in France.
courtyard – an open space partially or fully surrounded by walls; a small area, usually with grass and flowers, that is fully or partly surrounded by walls
* Remi walked out into the courtyard so that he could eat his lunch outside.
to house – to store something inside of a structure or container; to provide someone or something with a place to stay or a place to live
* The hollow tree housed a family of squirrels.
antiquities – very old or ancient art objects; customs, traditions, artwork, writings, or other cultural items from a culture that existed many years ago
* Lakita is fascinated by ancient Persian culture and enjoys studying antiquities from this period of history.
Mardi Gras – a week-long celebration that ends on the Tuesday immediately before the 40 days of Lent begin, during which people treat themselves to fancy foods and entertaining activities
* Sydney observed Mardi Gras every year by eating “king cake,” but he had never been to New Orleans to celebrate it.
Lent – a period of 40 days observed by Catholics and other Christians, during which one gives up something that is usually greatly enjoyed but unnecessary
* Regina gave up sweets and coffee for Lent.
to fast – to not eat or drink, usually for religious reasons
* When Graham’s mother fell seriously ill, he prayed and fasted for two days in an attempt to better understand God’s purpose.
Ash Wednesday – the first day of the 40-day religious period known as Lent, on which Christians attend a church service during which a cross is drawn on the forehead using the ashes of burnt palm leaves
* Pat attended the Ash Wednesday mass at Saint Mary’s Church.
to sacrifice – to give something up, usually for the sake of someone or something else
* Aiko sacrificed her hard-earned money to pay for a medication that her sister’s pet dog needed.
hurricane – a severe storm with very fast winds that cause large waves of water to overflow or crash onto dry land, often causing a lot of damage
* The hurricane passed through the town, destroying most of the houses along the coast.
to have to – to need to; to do something that must be done or is necessary
* Dwayne has to go to the doctor because he’s in a lot of pain.
to need to – to have to; to do something that must be done or is necessary
* Melissa needs to finish the assignment by 9:00 a.m on Friday morning.
hype – excited or enthusiastic discussion about something; popularity as a result of people talking about it or a lot of advertisements
* There was a lot of hype about singer’s latest release, but Clint couldn’t understand what was so great about it.
no brainer – a problem or issue with a solution so simple that one does not need to think much to realize it; an obvious or clear course of action
* If you have the money, buying a house instead of renting is a no brainer.
conditional – an action that relies on another action being done in order for the first action to take place; a verb tense used to explain what one will do if something specific happens
* More funding for the program is conditional on the results from last year.
What Insiders Know
Lesser-Known Museums in Los Angeles
As a major U.S. city, Los Angeles has many museums that visitors may want to see, including the Getty Villa mentioned in this English Cafe. However, while many smaller museums may get less “press” (attention; notice), they are still worth “checking out” (seeing).
One museum that “focuses on” (gives its major attention to) western and movie history is the Autry Museum of Western Heritage named after the famous radio, television, and movie star Gene Autry, also known as the “Singing Cowboy.” (A “cowboy” is a man who rides a horse and whose job is to move “cattle” (cows) and other “livestock” (animals raised for food and other products) from one place to another.) The museum has information about people living in the western states when it was first “being settled” (for homes and towns to be built there) by Americans and “artifacts” (items from history) used during that period. You can see how people dressed, lived, played, and worked. The museum also included TV and “movie memorabilia” (objects collected from past movies) of well-known shows and movies made about the Old West.
Visitors may also be interested in the Page Museum and the La Brea Tar Pits, a place where “fossils” (very, very old bones and other remains of living things) of animals, insects, and other living things from 10,000 to 40,000 years ago have been found. The “tar pits” (deep holes in the ground with a dark, thick liquid that can be lit on fire) acted as a “trap” (something that catches people or animals) for living things, “preserving” (keeping in its original condition) their “remains” (what is left of people/animals after they die). There are fossils of animals most people have never seen before, and many they may not even have heard of. The museum is a place to display these finds, but also continues to be a laboratory for “excavating” (digging to take out of the ground) fossils.