= 1331
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 26.
This is English as a Second Language Podcast’s English Café episode 26. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we’re going to talk about political parties in the United States – what they are called and what they believe in. We’re also going to talk about how you should begin an email in English. And, as always, we’ll answer some of your questions. Let's get started.
We normally don’t talk about politics here on the English Café, but I have gotten lots of questions about the political parties or groups in the United States, so I thought I’d spend a few minutes talking about what these are and what they do. A “political (political) party (party)” is an organization made up of people who tend to believe in and support the same political ideas. In the United States, the two most important and well-known political parties are the “Democratic Party” and the “Republican Party.”
Someone who is a member of the Democratic Party is called a “Democrat” (Democrat). There have been lots of famous Democratic presidents, such as Barack Obama, Bill Clinton, and John F. Kennedy. Someone who is a member of the Republican Party is called a “Republican” (Republican). Some recent Republican presidents include George W. Bush, his father, George Herbert Walker Bush, Ronald Reagan, and Dwight D. Eisenhower.
Generally speaking, the Democratic Party is more liberal in its politics. The word “liberal” (liberal) means different things in different countries. In United States politics, the word “liberal” usually refers to someone who wants more government action, more government spending, and more federal government involvement in different problems. The Republican Party is more “conservative” (conservative), which means that they want less involvement from the federal government, more state and local involvement, and less government spending in general. Those are some very general differences between the two parties.
We also use the terms “left-wing” and “right-wing” when talking about U.S. political parties. A member of a “left-wing” (left-wing) party – also just called “the Left” – would be a member of a very liberal political party. You might also hear people use “left” and “right” to describe how liberal or conservative a person is. For example, you might hear, “He’s to the left of this other person,” meaning he has more liberal ideas than the other person. Similarly, a member of a “right-wing” (right-wing) party – or “the Right” – would be someone with more conservative ideas. That person might say, “I am a member of the right-wing.” Most Democrats are liberal, and most Republicans are conservative, but there are are some conservative Democrats and some liberal Republicans, but not very many.
There are also what we call “third parties” in the United States. A “third party” is any party besides the two main parties, besides the Democratic and Republican parties. There are actually lots of third parties in the U.S., but you don’t often hear very much about them. Some of them are very liberal and some of them are very conservative. One of the most famous ones is a left-wing party called the “Green Party.” The Green Party is very concerned about the environment, and that’s one of their main issues, one of their beliefs. The Green Party recently had a presidential candidate named Ralph Nader who got a large number of votes. Ralph Nader is famous in the United States for being a “consumer advocate.” A “consumer” (consumer) is someone who buys things, and an “advocate” (advocate) is someone who tries to protect or help people. So, a consumer advocate helps protect the rights of consumers. Like most third-party candidates in the U.S., he lost.
A politician can also be an “independent,” meaning he or she is not affiliated with, or connected with, any political party at all. But even though we have third parties and independents, the majority of politicians in our government are still either Democrats or Republicans. It is very difficult to get elected, to win an election, if you are not a member of the Republican Party or the Democratic Party. This is because politicians need a lot of money to run a campaign and win an election, and the big political parties have much more money to spend than the smaller parties.
Our next topic is about how to begin an email. I get lots and lots of email from our listeners, and the people writing in often ask me if they began their email correctly. It’s actually not very complicated in English.
If it’s a formal email – for example, an email to someone you don’t know – it’s very much like writing a formal letter. You would write, “Dear” (Dear) and then the title of the person and the person’s name. A “title” (title) is either “Mr.” (Mr.) for a man or “Ms.” (Ms.) for a woman. You can also use “Mrs.” (Mrs.) for a woman if you know she is married, and “Miss” (Miss) if she is not, but it is much less common nowadays to see those two titles, especially in the business world. Other titles you might use would be “Doctor” (Dr.) for a doctor, “Father” (Fr.) for a father or Christian priest, and “Reverend” (Rev.) for a religious minister or leader. There are other titles you might see as well, but these are the most common ones.
After the title, we usually just put the person’s last name. So, if the person’s name is Ben Johnson, we would write, “Dear Mr. Johnson.” But we would never write, “Dear Mr. Ben.” We never use the title in front of a first name only. That’s very important to remember. You can, however, use a title in front of someone’s first and last name when introducing someone, when speaking to another person. You can say “I’d like you to meet Dr. Ben Johnson” or “We’re pleased to welcome Mr. Ben Johnson.” But when beginning a letter or an email, when we are writing, we usually just put, “Dear Mr. Johnson,” never “Dear Mr. Jeff McQuillan.” In fact, if you get an email or letter that says “Dear Mr. Ben Johnson,” it is probably generated or made by a computer that is sending out thousands of emails to people on a list somewhere.
If it’s a very formal letter or email, we often use a colon – two vertical dots – instead of a comma after the name. For more informal letters and emails, a simple comma is enough. For an informal email or letter, you can just use the person’s first name with no title: “Dear Ben” followed by a comma.
It might be possible to write, “Hi!” (Hi) with an exclamation point, but only with someone you know very well. It’s really not very common, even for informal emails. In fact, I find it very strange to get an email from someone I don’t really know very well that begins with “Hi!” or “Hey!” which is now used to mean the same as “Hi.” When in doubt, always be more formal rather than less formal with people you don’t know very well. No one dislikes being called “Mr. Johnson” or “Ms. Lawler,” and if they want you to use their first name only in the future, they’ll often say something to you, such as “Please, call me ‘Ben’” or “’Ben,’ please.”
If you know a person well, you can also drop or omit or not use the word “Dear.” You can just write, “Ben,” – just the first name of the person without a “Dear” in front of it. So, if you send me an email, you can write, “Dear Jeff,” or “Dear Dr. McQuillan,” but “Dear Jeff,” is probably better because we already know each other. We’ve been together for a while, many of us, right?
Now let’s answer some of the questions you have sent to us.
Our first question comes from Martin (Martin). Martin wants to know the meanings of the words “even” and “odd.” These words are used for numbers. “Even” (even) is used for any number that you can divided evenly by the number two. So, two, four, six, eight, ten, twelve, 156, 2,528 – those are all even numbers. An “odd” (odd) number is a number that cannot be divided evenly by the number two, such as one, three, five, seven, 269, or 5,781. Those are all “odd” numbers.
But the words “even” and “odd” also have other meanings. “Even” is used sometimes to mean that things are the same, or equal. For example, if you do something wrong to someone, that person may be angry with you and do something wrong to you in return. This is called “getting even.” We can also use the word “revenge” (revenge) in this case. The expression “to get even,” then, means to get revenge on someone, to hurt someone, just like that person hurt you. And when you succeed in doing that, you might say, “Now we’re even,” meaning now we are equal – I have hurt you just like you hurt me. You can also “be even” for something that isn’t related to doing wrong. If you pay for your friend’s lunch this week, next week she may say to you, “I’ll pay for today, and then we’re even,” meaning that neither of you owe the other one anything. Of course, normally you don’t pay for someone’s lunch or dinner expecting they’ll pay for yours someday.
We also can use “even” as an adverb, either to put emphasis or to point out something that’s very unusual or strange or surprising. “Even the girls wanted to watch the baseball game.” If you think that most girls don’t like baseball – which, of course, is not true – then you might use the word “even” here. Or, “Even my father wants to go to the opera.” Normally, he wouldn’t go to the opera, so it’s surprising that he would want to go.
The word “odd” can also be used to describe something that is strange. “This is very odd” means this is very strange. A person who is “odd” is someone who is a bit strange or weird or unusual. To say that something or someone is odd means there’s something a little bit wrong with that thing or that person. So thank you, Martin, for that odd question. I’m kidding - no, it wasn’t odd. It was a good question.
Our next question comes from Kimi (Kimi) in Japan. Kimi would like to know more about the word “unless.” We use the word “unless” (unless) to express a conditional situation – a situation in which one thing cannot happen without something else happening first. “I can’t go to the movies tonight unless I finish my homework.” I’m saying that if I don’t finish my homework, then I can’t go to the movies tonight. I can’t go unless I finish.
“Unless” can also be used at the beginning of a sentence. For example, “Unless you give me some money, I will not be able to buy dinner.” If you do not give me some money, I will not be able to buy my dinner. There is also an informal phrase similar to “unless,” which is “except if.” “Except (except) if” is used when there is an exception to something that is expected or usually true. “We don’t have to go out tonight except if you want to.”
Our final question comes from Quan (Quan) in Vietnam. Quan wants to know what the expression “six feet under” means. “Six (six) feet (feet) under (under)” means “dead.” Traditionally, when someone dies and needs to be buried, they dig a hole for the body that is at least six feet deep, or “six feet under” the ground. So, the expression “six feet under” is just another way of saying that someone is dead. If someone says, “I will not rest until I’m six feet under,” it means “I will not rest until I am dead.”
There was actually a television show on one of the cable channels called “Six Feet Under” about a family that runs a funeral home. A “funeral (funeral) home” is the place where they prepare the bodies of the dead to be buried. I heard it was a very good television show, although I never actually watched it. Perhaps I’ll have more time to watch it when I’m six feet under.
If you have a question or comment, you can email us before you’re six feet under. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2006 by the Center for Educational Development.
Glossary
political party – a group or organization made up of members or people who share similar political ideas and goals
* Josefina’s political beliefs do not match with the beliefs of any major political party, so she is not a registered member of either one.
Democrat – one of two main political parties, whose members usually have liberal or left-wing beliefs
* Bill Clinton and Barack Obama are both Democrats.
Republican – one of two main political parties, whose members usually have conservative or right-wing beliefs
* Ronald Reagan and George W. Bush are both Republicans.
liberal – a set of political beliefs, including that the government should help people in need and that social change is desirable
* Jerald votes for liberal politicians who support welfare programs for the poor.
conservative – a set of political beliefs, including that the national government should spend less money and to have less involvement in people’s lives
* Layla votes for conservative politicians who support lowering tax rates for both big and small businesses.
third party – any political party that is not one of the two major parties, Democrats and Republicans
* Eduardo did not like any of the candidates from the two major parties, so he decided to vote for a third party candidate instead.
consumer advocate – a person or organization that is dedicated or committed to creating rules that protect people who buy products and services and punishing companies who break these rules or treats its buyers poorly
* After being cheated by an online company, Shira sought advice from a consumer advocate.
title – a term that describes someone's rank, level of qualification, or position, often used before that person’s name
* After earning his Ph.D., Jackson Yost started using the title “Dr.”
colon – a punctuation mark made of with two dots, one above the other (:), usually used to split a sentence into two parts or to introduce a list
* Tomasa began her letter with “Dear Mr. Nakamura:”.
comma – a punctuation mark (,), which is usually used to show a pause in the sentence, to split the sentence into multiple parts, to separate items in a list, or to separate one word or section of a sentence from the rest of the sentence
* Each item on the shopping list that Luciano received from his wife was separated by a comma, and since she wrote down “coffee, creamer,” he knew that she wanted both coffee and creamer instead of just coffee creamer.
even – numbers that can be divided by two, such as 2, 4, 6, 8, 10, 12, 14, and so on; equal, balanced, fair, or the same
* After Michelle paid her friend back for dinner, they considered the debt between them even.
odd – numbers that cannot be divided by two, such as 1, 3, 5, 7, 9, 11, 13, 15, and so on; strange, weird, uncommon, or unusual
* Che heard an odd noise, so he went outside to check it out.
unless – except if; a term used to mean that someone is making an exception and doing something that is not usually done or is not usually true
* Awilda will not be going to the concert unless she recovers from the flu soon.
to mind – to be bothered or upset by something; to be concerned or interested in something, often in a troubled or unhappy way
* Mario arrived to his girlfriend’s house late, but since he had a good excuse, she didn’t mind too much.
six feet under – dead; dead and buried, meant to suggest that the body of the dead person is buried in a hole that is at least six feet deep underground
* Gerald said that only when he’s six feet under will he allow his children to have control of his money.
funeral home – a business that prepares dead bodies to be buried; a business that prepares someone who has died for funeral services and burial
* After her father passed away, Hisako contacted the funeral home to make arrangements for his burial.
What Insiders Know
What Ex-Presidents Do
It is the “dream” (goal) of many American “politicians” (elected representatives) to win the “ultimate” (highest) prize in American government: the presidency. Many of the more recent American presidents have been young enough to live long lives after leaving the “White House” (the presidency). What exactly do “ex-presidents” (former presidents) do?
There are no “official” (legal) duties of an ex-president. They can do “pretty much” (almost) anything they want to do. Some write “memoirs” or “autobiographies” – stories of their own lives. Most work on their “presidential library” – a place where their documents are kept and where “scholars” (researchers) can go to study their time as president.
Oftentimes, ex-presents are sent by the current president on some “diplomatic mission” (activity involving talking to or working with another government) or to help with some particular cause. Some ex-presidents, like Jimmy Carter and Bill Clinton, start charitable organizations to help people “in need” (who need help).
In the past, a few ex-presidents have “gone into” (become a member of) another “branch” (part) of government. After leaving the presidency in 1829, for example, John Quincy Adams became a member of the U.S. House of Representatives. (He had also been a U.S. Senator before being elected president). President William Taft (1909-1913) was later the Chief Justice of the United States (1921 – 1930), “head” (leader) of the United State “Supreme Court,” the highest and most powerful court in the country.