= 1355
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to English as a Second Language Podcast’s English Café number 50.
You're listening to English Café episode 50. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in the beautiful City of Los Angeles, California.
Our topic today is going to be a big one, so we're actually going to spend the entire first part talking about just one topic, and that's baseball, the sport of baseball. But, we're not going to talk about just the sport, we're also going to talk about some very common expressions that we use in everyday life that originally come from the game of baseball. And, at the end, as always, we'll answer a few questions. Now, let's play ball!
We're talking about baseball, which is sometimes called the national sport in the United States. It's also called the national pastime. A pastime, “pastime,” is an activity, something that you do when you have extra time; we might say in your free time. It can be a hobby. It can be a sport. In this case, it's the sport of baseball.
We're going to start talking a little bit about what the baseball game consists of. What is a baseball game? Many of you have probably seen a game, but maybe not have understood everything that goes on in the game, so we're going to talk about the rules for the game. We're also going talk about some common expressions that we use that originally come from the game of baseball.
Baseball is a game between two teams. There is a offensive team and a defensive team. The term, offensive, “offensive,” in sports means the team that is in a position to score, to get points. The defensive, “defensive,” team is the team that prevents, or tries to prevent the offensive team from scoring, from getting points. In baseball, the defensive teams stands out in what we would call the playing field, “field,” that's the place where you play baseball. It's sometimes called a baseball diamond, “diamond,” because the bases in a baseball game are in the shape a diamond. I'll talk about that in a minute.
Baseball has nine people on the defensive team. The most important people are the pitcher, “pitcher,” he's the person that throws the ball, and the catcher, “catcher,” he's the person that catches the ball. There are also seven other people on the playing field. Usually there's one person on the first base, one person on the second base and one person on the third base: the first baseman, the second baseman, the third baseman. There's a fourth player called the shortstop, “shortstop,” all one word, that also plays near the second and third bases, and there are three players that are in what's called the outfield, “outfield,” all one word. The outfield is the space that's at the very end of the field, divided into three sections: the left, center and right field. There's an expression, “to be out in left field” means to be a little crazy, to have ideas that are not normal. That's to be out in left field, and in baseball there are these three fields, or three parts of the outfield.
Now, I talk about bases. A base, “base,” is a small square that you have to, as the person who is hitting the ball and running, you have to go to each of the bases, which are on this big diamond. You have to run to each of the bases before you can score a point. So, there's the first base, the second base, the third base, and then you go back to where you began, and that is called the home base. And, that expression, “home base,” is often used by people to describe their headquarters or the place where they have their main operations or main business.
We've talked about the defensive team. These are the people who are out on the field trying to prevent the offensive team from scoring. Well, the offensive team has what we call batters. And a batter, “batter,” is someone who hits the ball with a bat. A bat, “bat,” is the long piece of usually wood, or sometimes aluminum, that the batter swings to hit the ball. And, the purpose of baseball is to have the batter hit the ball and be able to run around the three bases and back home to score a point. So, the batter has to hit the ball, and to hit the ball we often use the verb to swing, “swing.” They take the bat and it goes from behind them and they swing it very quickly to it's in front of them and, we hope, they hit the ball, at least the offensive team does.
The pitcher tries to throw the ball so that the batter won't be able to hit it. When the pitcher throws the ball, there are two things that can happen: the ball can be either a ball or a strike. It's a little confusing because the word ball is used to describe the round object that you hit. It's also used to describe a type of pitch.
There are balls and strikes in baseball. A strike is when the batter swings at the ball and misses or when the pitcher throws the ball into what's called the strike zone and the batter doesn't swing at it and hit it. The strike zone is an area - you can think of it between the knees of the player and his chest. That area, roughly, is the strike zone, and if the pitcher is able to throw the ball into that area and the batter does not swing at it, or does not swing at it and hit it, then that's a strike, “strike.” If the batter swings at it and misses it, or doesn't swing when the ball is in the strike zone, we say the batter is out after three strikes. And, there's a very common expression, “three strikes and you're out.” In baseball it means that you've swung at the ball - swung is the past tense of the verb to swing - you've swung at the ball three times and missed, or you have not swung at it and the pitcher has put the ball into the strike zone area.
You get three chances, in other words, and if you miss those three chances you are out, and then you have to go back to the area where your team is sitting. It's called the dugout, “dugout.” That's the place where the teams sit waiting to play and the other players that are not on the field sit. It's also where the coach is. We call the coach, the person that is the boss of the team is usually called in professional baseball the manager – the manager, “manager.”
Well, each team gets to have three batters in each inning that can come to the home base - what we would call the home plate, “plate” - and they have...they can get three outs. Now of course, not every ball that the pitcher throws is a strike. Sometimes the pitcher will throw a ball that is outside of the strike zone - that is too high or too low, and those are called - that type of pitch is called a ball. If a pitcher throws four balls - four pitches that are outside the strike zone, then we say that the player, the batter, from the offensive team gets a walk, “walk,” and they get to go to the first base, and then another batter comes up. Of course, if the next batter comes up and hits the ball very far and it's not caught by any of the defensive team, then the players can go to second base and third base and eventually come to home plate, to the home base, and they score a point.
If they hit the ball and one of the players catches the ball before it hits the ground, the batter is automatically out. If a defensive team player gets the ball after it has hit the ground, and runs to the base and puts his foot on it before the batter, or the runner arrives at the base, the runner is also out. A runner, “runner,” is a player that is on one of the bases and runs to the next base.
So, each team gets three outs, and after their three outs, then the other team has a chance to become the offensive team. The defensive team then has a chance to bat, and the offensive team that was at the beginning of the inning then goes out and becomes the defensive team. The teams switch, in other words, and each inning has three outs for each team.
After nine innings, whoever has the most points, who scored the most runs, “runs” - to score a run means that you get a point, and you get one point for each run - each player that goes around all three bases and comes back to home plate. The team with the most runs wins the game. Now, if the score is tied we go into what are called extra innings, additional innings, until somebody scores a point. It's actually a little more complicated than that, but that's the general idea.
Every baseball game in the United States usually begins with the National Anthem, or our national song. You've heard it, I'm sure: “Oh, say can you see, by the dawn's early light,” I won't sing it all for you! We'll do another podcast on the National Anthem. But, they have a singer who sings and everyone in the crowd who's watching it, the fans, will often sing. Our National Anthem is actually very difficult to sing, and many people don't sing it very well, but - including me! The...after the National Anthem, then usually the announcer will say, “Play ball,” meaning let's begin the game.
There's one more rule that I should tell you about in baseball. When the batter hits the ball a very long distance and it goes beyond the playing field, outside of the playing field, we call that a home run. A home, “home,” run, two words, and that means that the batter gets to go through all three bases and come back home and scores automatically a point. And, anyone else, any other runners that were on base, that is that were at either the first second or third base , or stops where you have to go, they also score a point.
Let's talk a little bit about some expressions that we get from the game of baseball. One most common expression is to strike out. You know that if you get three strikes you're out, or you have to go back to the dugout. To strike out also means in general conversation to fail at something, to try something and to fail. We sometimes use this with men who are trying to get a woman to go on a date with them, and the guy will try to call the girl and she'll say no, and we say he struck out. Struck, “struck,” is the past tense of strike.
That's a very common expression. Another common expression is a ballpark estimate. The ballpark, "ballpark," all one word, is the place where you play the game. It's the stadium, usually for professional baseball. A ballpark estimate, however, is a term that means a rough estimate - an approximate guess at something. So, someone may say, "Well, how much does it cost to buy a house in Los Angeles? Give me a ballpark estimate." You would say, "Well, the average price is about 500,000 dollars," that's a ballpark estimate.
Another expression that we get from baseball, and there are lots of them, is to throw a curve ball. To throw a curve, “curve,” ball. A curve ball is when the pitcher throws the ball and it bends, it curves, it goes in a different direction. The expression, to throw someone a curve ball, means to give them something unexpected, something that they didn't think would happen that causes you problems or causes you trouble. So, you might say, “My boss came to me and said that I have to go to New York City for two weeks. He really threw me a curve ball.” I wasn't expecting to have to go to New York City, and I don't want to go. That would be to throw someone a curve ball, to confuse them or to give them something that's unexpected.
Well, we probably will come back to the game of baseball. It is very popular in the United States, maybe the most popular national sport, much more popular than soccer, probably more popular than football. In a couple of weeks we will actually be having the national championship game, we call it the World Series. Of course, it's not the world series because it's just teams in the United States and a couple in Canada, one in Canada actually, so we should really change that name from World Series, but we call it the World Series. We call professional baseball Major League Baseball - Major, “Major,” League, “League,” Baseball.
That's also an expression, by the way. To be playing in the major leagues means that you are playing in the most important teams, the biggest teams. The opposite of that would be the minor leagues, “minor,” the minor leagues. And, those are teams that are professional, but they don't get the same amount of attention. When people think of baseball, they usually think of professional baseball as Major League Baseball.
Now let's answer a few of your questions, not related to baseball. Our first question comes from Leonid, “Leonid,” in Russia. Leonid wants to know the meaning of the word gangsta, “gangsta.” This is a slang term that comes from the word gangster, “gangster.” A gangster is usually someone who is part of a group, and we call that group a gang, “gang,” and gangs are usually young people between the ages of, I suppose, 12 and 30, who are involved in criminal activity, usually, doing something wrong: stealing, perhaps even killing people, selling drugs. That's the image that people have when they think of gangs. And, the word gangsta comes from that idea of people who are in a gang. It generally refers to the music and the way that the gangsters dress and their language. All of that is part of what we would call a subculture, or a culture within the larger American culture, and other countries. A subculture is a smaller culture, and this is a whole culture, the gangsta culture. And, it's a type of lifestyle, we would say, a type of...a way of people living. And, it's very popular especially in music to have songs about people who are in gangs. The most common type of music is rap, “rap,” music. There's a term gangsta rap, which is rap songs about this sort of activity. So, thank you Leonid for that question.
Our next question comes from Vincent, in Spain. Vincent wants to know the difference between a “compromise” and a “commitment.” A compromise means that you disagree with someone about something, and you decide that, “Well, I'll change my idea a little bit, you change your idea a little bit, and we'll compromise.” We'll agree on something that neither of us wanted originally, but we decide that's it's okay if we don't get everything we wanted. That's a compromise, as a noun. The verb, to compromise, means to talk to someone and come to an agreement.
A commitment is when you say I'm going to do something, you promise to do something. You say, “Yes, I will definitely do that” - that's, as a noun, a commitment. The verb is to commit, “commit.” So, thank you Vincent for that question.
That's all we have time for on today's Café. We've talked a lot about baseball. I hope not too much! I like baseball. It's maybe the only sport that I like to watch all the time, as much as I can. I watch the National League team here in Los Angeles called the Los Angeles Dodgers. So, go Dodgers! - we would say.
From Los Angeles, California, I'm Jeff McQuillan. Thanks for listening. We'll see you next time on the English Café.
ESL Podcast’s English Café is written and produced by Dr. Jeff McQuillan. This podcast is copyright 2006, by the Center for Educational Development.
Glossary
pastime – hobby; something people do for fun
* I only want to play volleyball as a pastime. I don’t want to become a professional player.
offensive – the players in a sports game who are trying to score points
* As soon as the offensive players got on the field, they scored two points.
defensive – the players in a sports game who are trying to prevent the other team from scoring points
* The defensive players did everything they could but the other team was unstoppable.
pitcher – in baseball, the player who throws the balls for other players to try to hit
* This pitcher throws the best fastballs in the league.
home base – in baseball, the place where players must reach to score a point; your home or the headquarters of your business
* She travels to about five cities each month, but her home base is Chicago.
to swing – in baseball, to use a bat (a wooden or aluminum stick) to try to hit the ball
* Keep your eye on the ball when you swing and the ball will be easier to hit.
runner – in baseball, the player who successfully hits the ball and who is running around to all of the bases to try to score a point
* There were two runners on the field when it started to rain.
to strike out – to be unsuccessful
* At the club, I asked three different women to dance but I struck out each time.
to be out in left field – strange or mistaken; to be a little crazy or very unexpected
* In the past, Dave has had some good ideas about improving business, but this one was out in left field.
ballpark estimate – a rough guess, usually involving a number
* A ballpark estimate for fixing the damage to house is around $800.
to throw someone a curveball – to do something that is unexpected or that is meant to trick someone
* Sinead threw her boyfriend a curveball when she finally told him that she had been married twice before.
home run – a complete success
* We hit a home run with that advertising campaign and I’m sure the clients will want to renew their contract with us.
gangsta – slang for gangster, someone who is a member of a gang; a culture or lifestyle that uses gangster images and language
* You look great and so gangsta in those loose pants.
compromise – an agreement between two sides, where each side gives to the other something the other side wants
* People say that every successful relationship requires a lot of compromise on both sides.
commitment – a promise to do something
* I can’t make a commitment to buy your car right now because I don’t know if I’ll have enough money by the end of the month.
What Insiders Know
David Letterman’s Top 10 List
The television show, “The Late Show with David Letterman,” is a popular show that is shown every weekday, Monday through Friday, on U.S. TV. It is a “late night show,” which means that it “airs,” or is shown, after the evening news, usually at 10:30 or 11:30 p.m. This is a “talk show,” where the host—David Letterman—talks to guests, usually famous celebrities, on the show.
Every night on the show, David Letterman reads a “top 10 list,” usually on a topic that the people in the audience know something about. For example, topics of his recent top 10 lists have been: “Top 10 Mistakes the President Made While Visiting Europe” and “Top 10 Ways New Yorkers Stay Cool in the Heat.” The answers are always “made up,” or not true, but they are usually very funny. The list always begins at 10, and “counts down” or goes down by 1 until it gets to the number 1 reason.
Here is a Top 10 list for ESL Podcast listeners.
Top 10 Reasons Dr. Lucy Tse Has Never Shown Her Face to Listeners
10. She has two heads.
9. There’s no need. She looks exactly like Dr. Jeff McQuillan.
8. She’s too busy getting Dr. McQuillan’s tea and washing his car.
7. The police are looking for her…again.
6. She’s not allowed to come out of her office until she finishes the scripts and Learning Guides for the rest of the year.
5. She will be on a famous reality show soon using a fake (not true) name and she doesn’t want anyone to know her real one.
4. No one is willing to take her picture. You’d understand if you’ve ever seen her.
3. Her picture is all over the website. Haven’t you seen them? Keep looking.
2. If listeners see her picture, she won’t be able to tell them she looks like Angelina Jolie anymore.
1. There is no such person as Dr. Lucy Tse. It’s what Dr. McQuillan likes other people to call him sometimes.