= 1335
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
You're listening to ESL Podcast’s English Café number 30.
This is English as a Second Language Podcast’s English Café episode 30. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we’ll be talking about people getting their news from the Internet. Then we’ll explain a little bit about opinion polls and specifically about the Gallup Poll. Finally, we’ll talk about what Americans think and feel about their environment. And, as always, we’ll answer a few of your questions. Let’s get started!
I’m going to talk a little today about the Internet and people getting their news on the Internet. There has been an increase in the number of people who get their news only from the Internet. They don’t subscribe to a newspaper and they don’t watch the national news shows that are on every evening.
There are at least three big national news shows on television every day in the United States, usually a half hour long, and 30 or 40 years ago, most people would watch the news on television every day. But now things have changed, and more people are getting their news from the Internet. A recent article on this topic quotes someone as saying, “Television is never going away, I don’t suspect, but people are going to be watching a lot of content on the Internet.” “To go away” here means to leave, and the phrase “television is never going away,” means that television is never going to leave or die or no longer exist. “Television is never going away” means that television is going to remain, to stay.
The expression “I don’t suspect” is used to emphasize that this is the speaker’s personal opinion. “I don’t suspect” is the opposite of “I suspect.” You would only use “I don’t suspect” with a negative statement, such as “It’s not going to rain, I don’t suspect.” It’s an informal phrase that often (but not always) comes at the end of a sentence. So, you could say, “The Los Angeles Dodgers won’t win the World Series this year, I don’t suspect,” meaning I personally don’t think that they will win the World Series. The World Series is the national championship in baseball in the United States, by the way.
He then says that “people are going to be watching a lot of content on the Internet,” especially what we might call ‘high-powered users.” “Content” (content) here refers to the material that you are listening to or watching, the actual information. There is a lot of content on the Internet, on websites and in podcasts and in blogs. A “blog” (blog), which is short for “web log,” is a website where someone will post information and opinions every day or every week.
Many people are what we might call “high-powered users” of the Internet. “High-powered” (high-powered) describes someone who is an expert in a certain field, often someone who is very influential or powerful. We might refer to someone as a “high-powered lawyer” or “a high-powered doctor,” meaning they’re very important in their professions and probably very wealthy and influential. So, a “high-powered user” of the Internet would be someone who is an expert and does a lot of things on the Internet. It’s the same here as “highly skilled” or “expert.” I mentioned this idea of a “high-powered” user because that’s precisely the sort of person who will probably get their news from the Internet. Actually, nowadays, I would guess that most people are getting their news from the Internet.
People also used to get their news from newspapers. I subscribe to three newspapers, the local one and two national ones. The local paper is The Los Angeles Times, which I get on Sundays, and the national papers are The Wall Street Journal, which I get Monday through Saturday, and The New York Times, which I get on Sundays. I like to read the newspapers, but I also get news from different websites online.
Some people get their news from the Internet because they believe that the national newspapers and television news programs dumb down the news. “To dumb (dumb) down (down)” something means to make something overly simple, to make it so simple that important information is left out.
This phrase is often used to describe what is being taught in the schools. Some people complain that schools are “dumbing down” the curriculum – what is being taught – meaning simplifying it to the point of making it too simple. And some people think that the national newspapers and news programs dumb down the news, and that the Internet is a better source of information.
I’m not sure if that’s true. In fact, the opposite might be true, since people will often only spend a very short amount of time reading things on the web, and so the stories have to be shorter and therefore contain less information than what you may be able to find in a newspaper or magazine. So that’s a little bit of information on news sources that Americans use.
Our next topic is about opinion polls. I often get emails from people asking me what Americans think about some particular issue or event. “What do Americans think about the president?” or “What do Americans think about the situation in the Middle East?” and so forth. It’s very common for me to get questions like these, but it’s difficult for me to answer these questions because everyone has their own opinion about these subjects. So, it’s difficult to say what the general opinion is. But one way you can find out what Americans think about different subjects or topics is to look at an “opinion poll.”
An “opinion (opinion) poll (poll)” is when a company – a newspaper or a private company – asks a large number of people for their opinions on a particular subject. Usually, the people will be given a question and then asked to choose which answer they agree with. This is usually done by a “random sample” over the telephone. A “random (random) sample (sample)” is a number of people who are chosen from a larger group of people. The larger group may have 300 million people, but you can’t call 300 million people, so you pick maybe one or two thousand people at random who will represent the opinions of the bigger group.
The most famous poll in the United States is called the “Gallup Poll.” Gallup (Gallup) is a poll company that was started by George Gallup many years ago. There is usually a Gallup Poll in the news every week or couple of weeks on a different topic. Today we’ll look at a recent Gallup Poll about the environment, since there has been a lot of interest in the environment lately, especially with the droughts and hurricanes and other strange weather that we have been experiencing in North America in recent years. Many people are very concerned about the environment and what is happening to it.
People were asked in this particular Gallup Poll, which is now a few years old, what they thought were some of the most important environmental problems. One of the most important problems that people mentioned was “water pollution,” or the pollution of our drinking water. “Pollution” (pollution) is the contamination or spoiling of something that was once clean and pure. Water pollution refers to water that was once clean but is now dirty in some ways. Water can be “polluted” by chemicals or by an oil spill or by many other things. Polluted water can make people sick if they drink it, which is why people are very concerned about water pollution.
Another big environmental concern for many people, both here in the United States and in other countries, is “global warming.” “Global (global) warming (warming)” is the increase in temperature of the Earth’s atmosphere. The Earth is getting hotter, if you will. According to a recent poll, 68 percent of Americans believe that global warming is a serious problem, and that the federal government should be doing more to stop it. The government doesn’t always agree with the majority of the people on every issue, however, so the position of the government or of the president on certain issues isn’t always necessarily the same as the position of the majority of Americans.
In the United States, there is one political party called the Green Party that is very concerned with the environment. Protecting the environment is one of their most important issues, one of their most important positions. The Green Party in the United States is not very large; probably less than 5 percent of the people vote for the Green Party when there is an election. Most people have heard of it, however, and there are a lot of people who are interested in and concerned about the environment, but who aren’t necessarily politically active.
A popular thing to do for the environment these days is to recycle. “To recycle” (recycle) means to use a material more than once. For example, used aluminum cans can be recycled to make new cans, old newspapers can be recycled to make new paper, and so forth. In most big cities in the United States, when the city comes by every week to pick up your garbage, your trash, they will also pick up your recycling – your items to be recycled. Usually there will be a separate bin or container for recycled goods like cans and bottles and newspapers. That’s how we do it here in Los Angeles. So, many people are interested in helping the environment without necessarily being involved politically.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Kai (Kai) in Germany. There is a movie about a famous American writer from the 1960s named Truman Capote (Capote), and the writer’s last name is also the name of the movie about him: Capote. Kai’s question is: “Why isn’t this pronounced Capote?” In other words, why do we pronounce the final “e”? In English, the “e” at the end of a word is usually what we call “silent,” meaning you do not pronounce it. But in “Capote,” you do. There are some other words like this as well.
For example, the name of the famous running shoe company is pronounced “Nike” (Nike). It’s not “Nike.” It’s “Nike” with what we call a long “e.” There’s also a software company named “Adobe” (Adobe) in which we pronounce the final “e.” We say “Adobe,” not “Adobe.” Usually, however, we do not pronounce the final “e,” but there are these exceptions.
Sometimes people will decide that they want to pronounce the “e” at the end of their names or at the end of their company’s name. Names are what are called “proper nouns,” and generally in English people are allowed to pronounce their names however they want. Sometimes two people whose last names are the same will pronounce their last names differently, even if they are spelled exactly the same way. It can get very confusing, even for Americans.
Also, many words come from other languages, and so are pronounced differently than what is usual for English. The word “Nike” is an example of this. “Nike” was an ancient Greek word long before it was the name of a company. In ancient Greek mythology, “Nike” was the goddess of victory. So, these are a few reasons why words are sometimes pronounced differently than we expect.
Next, Kristoff (Kristoff) in France wants to know the difference between “to think of something” and “to think about something.” Sometimes these two phrases mean almost the same thing. For example, “I’m thinking of the beach” means the same as “I’m thinking about the beach.” They both can mean that the beach is what is in my mind at the moment.
However, “to think of something” can also have a different meaning, which is to come up with a reason or an idea. For example, “I need to think of a good excuse not to go to dinner tonight” means I need to come up with or to invent a good reason why I can’t go to dinner. So, sometimes the expression “to think of something” means to create a reason or new idea about something. But usually, “to think of something” and “to think about something” mean basically the same thing.
Our next question comes “X Snake” in China – that’s the letter “X” followed by the word “Snake” (Snake). I’m not sure if X Snake is a man or a woman, or even a real human being, but X Snake has a question about a term that he or she or it saw while reading something recently, and that term is “think tank.” What is a “think tank”? A “think (think) tank (tank)” is an organization that does research and tries to come up with new ideas about certain topics. It’s usually a political organization that writes reports and has conferences about certain topics. The members of the “think tank” are experts in their fields, and their job is to think about certain social and political issues.
There are lots of political think tanks in Washington D.C and in other parts of the United States. There are politically conservative think tanks, like the Heritage Foundation and the American Enterprise Institute, and there are liberal think tanks, like the Brookings Institute. But you can have a think tank about almost anything. Again, a think tank is a group of people who are experts on certain topics, and they research and write papers and reports and give speeches about particular topics, often political or social issues. Thanks for that question, X Snake, whoever or whatever you are.
Next, we have a question from Alesia (Alesia), who we know for sure is in Torino, Italy. Alesia wants to know at what time of day we should use the expressions “Good morning,” “Good afternoon,” “Good evening,” and “Goodnight.” “Good morning” is used from the time that the sun comes up – five or six o’clock in the morning – until noon, or twelve o’clock in the afternoon. Even though the hours after midnight are technically the very early morning, we usually don’t say “Good morning” until the sun is up.
After twelve o’clock in the afternoon, you would say, “Good afternoon,” and you can use “Good afternoon” until about six o’clock – six p.m. At around six o’clock, you might use either “Good afternoon” or “Good evening.” And after six o’clock, you would say, “Good evening.” So, if you were walking down the street after six o’clock at night and saw someone, you would say, “Good evening.” Actually, you probably wouldn’t say anything at all – people don’t usually say hello to each other just because they’re both walking down the same street, at least not here in Los Angeles. But “Good evening” is what you would say after six p.m.
“Goodnight” is only used when you going to bed or when you are saying goodbye to someone after six o’clock in the evening. So if it’s ten o’clock at night and you are leaving someone’s house, you would say, “Goodnight.” You would not say “Good evening.” “Good evening” is usually only used when you are greeting someone, not when you are leaving.
Finally, Frederick (Frederick) in France has a question about an abbreviation he saw: “COB.” What does it mean when someone says, “I need something COB”? Well, Frederick, it’s not a very common abbreviation, but it means “close of business,” meaning at the end of the business day. So, if someone says, “I need something Friday COB,” that means they need it before the office closes at the end of the day on Friday. But it’s not that common of an expression here. Thank you for your question, Frederick.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2006 by the Center for Educational Development
Glossary
to go away – to leave; to stop being popular and to die or stop existing because of that loss in popularity
* Cassette tapes went away after CDs became popular, and video tapes went away after DVDs took over.
I don't suspect – I don't believe; an expression used to say that one does not believe or think that something is going to happen
* The city won’t have power after the big windstorms pass through, I don’t suspect.
blog – web log; a diary or journal that is posted online, on which a writer frequently shares his or her newest opinions, experiences, beliefs, or other thoughts
* Marietta writes a food blog and posts comments about new recipes she tries.
content – the words or ideas being expressed by something; information that is provided in speech, writing, music, or art
* Jamaal disagreed with the content of the presentation because he thought that the speaker did not provide enough evidence for his conclusions.
high-powered – having a lot of power or money; being stronger or more able than normal
* The sports car had a high-powered engine that allowed it to move very fast.
to dumb down (something) – to make something so simple that important details or information is kept out and missed; to make something too simple or simpler than it should be
* Leanne felt insulted by the way that her tutor dumbed down the lesson.
opinion poll – survey; a set of questions, which a company or organization asks people randomly or by chance so that the company can determine what people believe or think about a specific topic
* Before the big election, many organizations were taking opinion polls to find out which politician had the better chance of being elected.
random sample – a group of people who are chosen by chance to represent the opinions or actions of a larger group that they belong to
* A random sample of college students was asked a series of questions about campus life.
pollution – harmful or dangerous elements, such as chemicals or other substances, that are introduced into a previously clean environment
* Before the environmental regulations were put in place, pollution from the factory would contaminate the nearby river.
global warming – the idea that the overall temperature of the Earth's atmosphere or air is rising due to human actions, leading to problems in the environment and in the lives of humans, animals, and plants
* Terrence is concerned about global warming, so he tries to conserve energy by driving a hybrid car and driving less.
to recycle – to reuse something; to take something old that no longer has a use or purpose to a special factory or organization that can form that object into something new
* Serena recycles her metal cans and plastic bottles, which are collected by the city every week and taken to the recycling plant.
to think of (something) – to have thoughts about something; to plan, invent, or come up with something using one's mind
* Manuel thought of a new plan to save his company money.
to think about (something) – to have thoughts about something; to have something on one's mind or to be thinking thoughts concerning a certain topic
* When she left on a business trip, Angelina missed her husband and thought about him constantly.
think tank – a group of experts who discuss and find solutions to specific topics or problems, often about policies or the government
* The politician consulted with powerful think tanks to determine what his next move should be.
close of business – at the end of the business day; before an office or business closes on a certain day
* The payment was due by close of business on Wednesday.
What Insiders Know
State Nicknames Related to Trees and Flowers
Each one of the 50 U.S. states has a nickname that can be related to anything that the state is known for or connected to. Several states have nicknames related to trees and flowers. The most well known nickname in this category is probably the Buckeye State, given to the state of Ohio, which is located in the eastern, central part of the United States, just west of Pennsylvania. A “buckeye” is a large tree that grows in this region of the country. It is said that the buckeye was the first kind of tree “felled” (cut down) by one of the earliest white “settlers” (people who arrive from another country or region to live or “settle” in an unpopulated area) of Ohio. The name was later applied to anyone from the state. For example, we could say that William Henry Harrison, our ninth president, was a Buckeye. The Ohio State University uses Buckeye as the name of their sports teams.
Kansas, located in the central part of the U.S., is often called the Sunflower State, because this colorful plant grows there. Kansas is also known for producing a lot of wheat, a plant used in making flour for bread and baking, and is therefore sometimes known as “America’s breadbasket.” A “basket” is a container used to carry something, and so a breadbasket is a container for carrying bread. Kansas is also famous for being the home of Dorothy in the movie, The Wizzard of Oz.
If you have ever seen the popular 1980s Julia Roberts movie, Steel Magnolias, then you know that southern state of Mississippi is associated with this beautiful tree, the magnolia. The movie, a classic “chick flick” (move popular with women), begins with an argument about magnolias.
If you don’t watch a lot of movies, then perhaps you listen to music, in which case you may have heard of bluegrass music. “Bluegrass” is a type of grass you can find in cool, “moist” (wet) areas, including the eastern state of Kentucky, which is known as the Bluegrass State. Bluegrass music originally comes from the Appalachian Mountains of Kentucky, and started as a type of traditional folk music mixing Irish, Scottish, English, and African American musical styles.
Complete Transcript
You're listening to ESL Podcast’s English Café number 30.
This is English as a Second Language Podcast’s English Café episode 30. I'm your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
On this Café, we’ll be talking about people getting their news from the Internet. Then we’ll explain a little bit about opinion polls and specifically about the Gallup Poll. Finally, we’ll talk about what Americans think and feel about their environment. And, as always, we’ll answer a few of your questions. Let’s get started!
I’m going to talk a little today about the Internet and people getting their news on the Internet. There has been an increase in the number of people who get their news only from the Internet. They don’t subscribe to a newspaper and they don’t watch the national news shows that are on every evening.
There are at least three big national news shows on television every day in the United States, usually a half hour long, and 30 or 40 years ago, most people would watch the news on television every day. But now things have changed, and more people are getting their news from the Internet. A recent article on this topic quotes someone as saying, “Television is never going away, I don’t suspect, but people are going to be watching a lot of content on the Internet.” “To go away” here means to leave, and the phrase “television is never going away,” means that television is never going to leave or die or no longer exist. “Television is never going away” means that television is going to remain, to stay.
The expression “I don’t suspect” is used to emphasize that this is the speaker’s personal opinion. “I don’t suspect” is the opposite of “I suspect.” You would only use “I don’t suspect” with a negative statement, such as “It’s not going to rain, I don’t suspect.” It’s an informal phrase that often (but not always) comes at the end of a sentence. So, you could say, “The Los Angeles Dodgers won’t win the World Series this year, I don’t suspect,” meaning I personally don’t think that they will win the World Series. The World Series is the national championship in baseball in the United States, by the way.
He then says that “people are going to be watching a lot of content on the Internet,” especially what we might call ‘high-powered users.” “Content” (content) here refers to the material that you are listening to or watching, the actual information. There is a lot of content on the Internet, on websites and in podcasts and in blogs. A “blog” (blog), which is short for “web log,” is a website where someone will post information and opinions every day or every week.
Many people are what we might call “high-powered users” of the Internet. “High-powered” (high-powered) describes someone who is an expert in a certain field, often someone who is very influential or powerful. We might refer to someone as a “high-powered lawyer” or “a high-powered doctor,” meaning they’re very important in their professions and probably very wealthy and influential. So, a “high-powered user” of the Internet would be someone who is an expert and does a lot of things on the Internet. It’s the same here as “highly skilled” or “expert.” I mentioned this idea of a “high-powered” user because that’s precisely the sort of person who will probably get their news from the Internet. Actually, nowadays, I would guess that most people are getting their news from the Internet.
People also used to get their news from newspapers. I subscribe to three newspapers, the local one and two national ones. The local paper is The Los Angeles Times, which I get on Sundays, and the national papers are The Wall Street Journal, which I get Monday through Saturday, and The New York Times, which I get on Sundays. I like to read the newspapers, but I also get news from different websites online.
Some people get their news from the Internet because they believe that the national newspapers and television news programs dumb down the news. “To dumb (dumb) down (down)” something means to make something overly simple, to make it so simple that important information is left out.
This phrase is often used to describe what is being taught in the schools. Some people complain that schools are “dumbing down” the curriculum – what is being taught – meaning simplifying it to the point of making it too simple. And some people think that the national newspapers and news programs dumb down the news, and that the Internet is a better source of information.
I’m not sure if that’s true. In fact, the opposite might be true, since people will often only spend a very short amount of time reading things on the web, and so the stories have to be shorter and therefore contain less information than what you may be able to find in a newspaper or magazine. So that’s a little bit of information on news sources that Americans use.
Our next topic is about opinion polls. I often get emails from people asking me what Americans think about some particular issue or event. “What do Americans think about the president?” or “What do Americans think about the situation in the Middle East?” and so forth. It’s very common for me to get questions like these, but it’s difficult for me to answer these questions because everyone has their own opinion about these subjects. So, it’s difficult to say what the general opinion is. But one way you can find out what Americans think about different subjects or topics is to look at an “opinion poll.”
An “opinion (opinion) poll (poll)” is when a company – a newspaper or a private company – asks a large number of people for their opinions on a particular subject. Usually, the people will be given a question and then asked to choose which answer they agree with. This is usually done by a “random sample” over the telephone. A “random (random) sample (sample)” is a number of people who are chosen from a larger group of people. The larger group may have 300 million people, but you can’t call 300 million people, so you pick maybe one or two thousand people at random who will represent the opinions of the bigger group.
The most famous poll in the United States is called the “Gallup Poll.” Gallup (Gallup) is a poll company that was started by George Gallup many years ago. There is usually a Gallup Poll in the news every week or couple of weeks on a different topic. Today we’ll look at a recent Gallup Poll about the environment, since there has been a lot of interest in the environment lately, especially with the droughts and hurricanes and other strange weather that we have been experiencing in North America in recent years. Many people are very concerned about the environment and what is happening to it.
People were asked in this particular Gallup Poll, which is now a few years old, what they thought were some of the most important environmental problems. One of the most important problems that people mentioned was “water pollution,” or the pollution of our drinking water. “Pollution” (pollution) is the contamination or spoiling of something that was once clean and pure. Water pollution refers to water that was once clean but is now dirty in some ways. Water can be “polluted” by chemicals or by an oil spill or by many other things. Polluted water can make people sick if they drink it, which is why people are very concerned about water pollution.
Another big environmental concern for many people, both here in the United States and in other countries, is “global warming.” “Global (global) warming (warming)” is the increase in temperature of the Earth’s atmosphere. The Earth is getting hotter, if you will. According to a recent poll, 68 percent of Americans believe that global warming is a serious problem, and that the federal government should be doing more to stop it. The government doesn’t always agree with the majority of the people on every issue, however, so the position of the government or of the president on certain issues isn’t always necessarily the same as the position of the majority of Americans.
In the United States, there is one political party called the Green Party that is very concerned with the environment. Protecting the environment is one of their most important issues, one of their most important positions. The Green Party in the United States is not very large; probably less than 5 percent of the people vote for the Green Party when there is an election. Most people have heard of it, however, and there are a lot of people who are interested in and concerned about the environment, but who aren’t necessarily politically active.
A popular thing to do for the environment these days is to recycle. “To recycle” (recycle) means to use a material more than once. For example, used aluminum cans can be recycled to make new cans, old newspapers can be recycled to make new paper, and so forth. In most big cities in the United States, when the city comes by every week to pick up your garbage, your trash, they will also pick up your recycling – your items to be recycled. Usually there will be a separate bin or container for recycled goods like cans and bottles and newspapers. That’s how we do it here in Los Angeles. So, many people are interested in helping the environment without necessarily being involved politically.
Now let’s answer some of the questions you have sent to us.
Our first question comes from Kai (Kai) in Germany. There is a movie about a famous American writer from the 1960s named Truman Capote (Capote), and the writer’s last name is also the name of the movie about him: Capote. Kai’s question is: “Why isn’t this pronounced Capote?” In other words, why do we pronounce the final “e”? In English, the “e” at the end of a word is usually what we call “silent,” meaning you do not pronounce it. But in “Capote,” you do. There are some other words like this as well.
For example, the name of the famous running shoe company is pronounced “Nike” (Nike). It’s not “Nike.” It’s “Nike” with what we call a long “e.” There’s also a software company named “Adobe” (Adobe) in which we pronounce the final “e.” We say “Adobe,” not “Adobe.” Usually, however, we do not pronounce the final “e,” but there are these exceptions.
Sometimes people will decide that they want to pronounce the “e” at the end of their names or at the end of their company’s name. Names are what are called “proper nouns,” and generally in English people are allowed to pronounce their names however they want. Sometimes two people whose last names are the same will pronounce their last names differently, even if they are spelled exactly the same way. It can get very confusing, even for Americans.
Also, many words come from other languages, and so are pronounced differently than what is usual for English. The word “Nike” is an example of this. “Nike” was an ancient Greek word long before it was the name of a company. In ancient Greek mythology, “Nike” was the goddess of victory. So, these are a few reasons why words are sometimes pronounced differently than we expect.
Next, Kristoff (Kristoff) in France wants to know the difference between “to think of something” and “to think about something.” Sometimes these two phrases mean almost the same thing. For example, “I’m thinking of the beach” means the same as “I’m thinking about the beach.” They both can mean that the beach is what is in my mind at the moment.
However, “to think of something” can also have a different meaning, which is to come up with a reason or an idea. For example, “I need to think of a good excuse not to go to dinner tonight” means I need to come up with or to invent a good reason why I can’t go to dinner. So, sometimes the expression “to think of something” means to create a reason or new idea about something. But usually, “to think of something” and “to think about something” mean basically the same thing.
Our next question comes “X Snake” in China – that’s the letter “X” followed by the word “Snake” (Snake). I’m not sure if X Snake is a man or a woman, or even a real human being, but X Snake has a question about a term that he or she or it saw while reading something recently, and that term is “think tank.” What is a “think tank”? A “think (think) tank (tank)” is an organization that does research and tries to come up with new ideas about certain topics. It’s usually a political organization that writes reports and has conferences about certain topics. The members of the “think tank” are experts in their fields, and their job is to think about certain social and political issues.
There are lots of political think tanks in Washington D.C and in other parts of the United States. There are politically conservative think tanks, like the Heritage Foundation and the American Enterprise Institute, and there are liberal think tanks, like the Brookings Institute. But you can have a think tank about almost anything. Again, a think tank is a group of people who are experts on certain topics, and they research and write papers and reports and give speeches about particular topics, often political or social issues. Thanks for that question, X Snake, whoever or whatever you are.
Next, we have a question from Alesia (Alesia), who we know for sure is in Torino, Italy. Alesia wants to know at what time of day we should use the expressions “Good morning,” “Good afternoon,” “Good evening,” and “Goodnight.” “Good morning” is used from the time that the sun comes up – five or six o’clock in the morning – until noon, or twelve o’clock in the afternoon. Even though the hours after midnight are technically the very early morning, we usually don’t say “Good morning” until the sun is up.
After twelve o’clock in the afternoon, you would say, “Good afternoon,” and you can use “Good afternoon” until about six o’clock – six p.m. At around six o’clock, you might use either “Good afternoon” or “Good evening.” And after six o’clock, you would say, “Good evening.” So, if you were walking down the street after six o’clock at night and saw someone, you would say, “Good evening.” Actually, you probably wouldn’t say anything at all – people don’t usually say hello to each other just because they’re both walking down the same street, at least not here in Los Angeles. But “Good evening” is what you would say after six p.m.
“Goodnight” is only used when you going to bed or when you are saying goodbye to someone after six o’clock in the evening. So if it’s ten o’clock at night and you are leaving someone’s house, you would say, “Goodnight.” You would not say “Good evening.” “Good evening” is usually only used when you are greeting someone, not when you are leaving.
Finally, Frederick (Frederick) in France has a question about an abbreviation he saw: “COB.” What does it mean when someone says, “I need something COB”? Well, Frederick, it’s not a very common abbreviation, but it means “close of business,” meaning at the end of the business day. So, if someone says, “I need something Friday COB,” that means they need it before the office closes at the end of the day on Friday. But it’s not that common of an expression here. Thank you for your question, Frederick.
If you have a question or comment, you can email us. Our email address is eslpod@eslpod.com.
From Los Angeles, California, I'm Jeff McQuillan. Thank you for listening. Come back and listen to us again right here on the English Café.
ESL Podcast’s English Café was written and produced by Dr. Jeff McQuillan and Dr. Lucy Tse. Copyright 2006 by the Center for Educational Development
Glossary
to go away – to leave; to stop being popular and to die or stop existing because of that loss in popularity
* Cassette tapes went away after CDs became popular, and video tapes went away after DVDs took over.
I don't suspect – I don't believe; an expression used to say that one does not believe or think that something is going to happen
* The city won’t have power after the big windstorms pass through, I don’t suspect.
blog – web log; a diary or journal that is posted online, on which a writer frequently shares his or her newest opinions, experiences, beliefs, or other thoughts
* Marietta writes a food blog and posts comments about new recipes she tries.
content – the words or ideas being expressed by something; information that is provided in speech, writing, music, or art
* Jamaal disagreed with the content of the presentation because he thought that the speaker did not provide enough evidence for his conclusions.
high-powered – having a lot of power or money; being stronger or more able than normal
* The sports car had a high-powered engine that allowed it to move very fast.
to dumb down (something) – to make something so simple that important details or information is kept out and missed; to make something too simple or simpler than it should be
* Leanne felt insulted by the way that her tutor dumbed down the lesson.
opinion poll – survey; a set of questions, which a company or organization asks people randomly or by chance so that the company can determine what people believe or think about a specific topic
* Before the big election, many organizations were taking opinion polls to find out which politician had the better chance of being elected.
random sample – a group of people who are chosen by chance to represent the opinions or actions of a larger group that they belong to
* A random sample of college students was asked a series of questions about campus life.
pollution – harmful or dangerous elements, such as chemicals or other substances, that are introduced into a previously clean environment
* Before the environmental regulations were put in place, pollution from the factory would contaminate the nearby river.
global warming – the idea that the overall temperature of the Earth's atmosphere or air is rising due to human actions, leading to problems in the environment and in the lives of humans, animals, and plants
* Terrence is concerned about global warming, so he tries to conserve energy by driving a hybrid car and driving less.
to recycle – to reuse something; to take something old that no longer has a use or purpose to a special factory or organization that can form that object into something new
* Serena recycles her metal cans and plastic bottles, which are collected by the city every week and taken to the recycling plant.
to think of (something) – to have thoughts about something; to plan, invent, or come up with something using one's mind
* Manuel thought of a new plan to save his company money.
to think about (something) – to have thoughts about something; to have something on one's mind or to be thinking thoughts concerning a certain topic
* When she left on a business trip, Angelina missed her husband and thought about him constantly.
think tank – a group of experts who discuss and find solutions to specific topics or problems, often about policies or the government
* The politician consulted with powerful think tanks to determine what his next move should be.
close of business – at the end of the business day; before an office or business closes on a certain day
* The payment was due by close of business on Wednesday.
What Insiders Know
State Nicknames Related to Trees and Flowers
Each one of the 50 U.S. states has a nickname that can be related to anything that the state is known for or connected to. Several states have nicknames related to trees and flowers. The most well known nickname in this category is probably the Buckeye State, given to the state of Ohio, which is located in the eastern, central part of the United States, just west of Pennsylvania. A “buckeye” is a large tree that grows in this region of the country. It is said that the buckeye was the first kind of tree “felled” (cut down) by one of the earliest white “settlers” (people who arrive from another country or region to live or “settle” in an unpopulated area) of Ohio. The name was later applied to anyone from the state. For example, we could say that William Henry Harrison, our ninth president, was a Buckeye. The Ohio State University uses Buckeye as the name of their sports teams.
Kansas, located in the central part of the U.S., is often called the Sunflower State, because this colorful plant grows there. Kansas is also known for producing a lot of wheat, a plant used in making flour for bread and baking, and is therefore sometimes known as “America’s breadbasket.” A “basket” is a container used to carry something, and so a breadbasket is a container for carrying bread. Kansas is also famous for being the home of Dorothy in the movie, The Wizzard of Oz.
If you have ever seen the popular 1980s Julia Roberts movie, Steel Magnolias, then you know that southern state of Mississippi is associated with this beautiful tree, the magnolia. The movie, a classic “chick flick” (move popular with women), begins with an argument about magnolias.
If you don’t watch a lot of movies, then perhaps you listen to music, in which case you may have heard of bluegrass music. “Bluegrass” is a type of grass you can find in cool, “moist” (wet) areas, including the eastern state of Kentucky, which is known as the Bluegrass State. Bluegrass music originally comes from the Appalachian Mountains of Kentucky, and started as a type of traditional folk music mixing Irish, Scottish, English, and African American musical styles.