= 0224
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome to EnglishPod.
My name is Marco.
My name is Catherine and we've got an upper intermediate level lesson for you guys today.
This one is all about a crime scene.
That's right.
So we are going to be at a crime scene.
We are with the police officers and we're going to take a look at some very, very interesting and specific vocab to like police and a crime and all that.
That's right.
So if you are a fan of the TV show CSI or you like some of these investigation police work TV shows, this is a lesson for you.
That's right.
So why don't we go and listen to the dialogue for the first time.
Alright, Officer McGraw.
Give it to me straight.
What are we looking at here?
Detective McGee, we're glad to see you.
We could sure use your expertise on this one.
It's a break in, but nothing seems to have been stolen.
We received a call from the Baer family at around 1030 this morning.
They'd gone out for a walk before breakfast and came home to this mess.
Broken chairs and porridge all over the place.
Apparently Mama Baer had made the porridge a little too hot you see.
They were waiting for it to cool down.
Okay then, let's start examining the evidence.
Have the forensics team been in yet?
Yes sir.
They found some fingerprints on the bowls and are analyzing them back at the lab as we speak.
Hopefully they will be able to identify the burglar soon.
Hmm.
Aha!
What's this?
A strand of golden hair.
This is a very important piece of trace evidence, McGraw.
It tells me the suspect has long golden hair and very few men have long golden hair.
So our criminal could be a woman.
A woman?
Was she working alone?
Did she have an accomplice?
An accomplice?
No.
No, McGraw.
She was definitely working alone.
See here there are footprints in the porridge.
Here on the floor, small footprints.
This tells me that our suspect is small and could possibly be a child.
A child?
Surely not, sir.
We must follow the clues, McGraw.
The evidence doesn't lie.
Now let's reconstruct the crime.
The suspect came in, sat in each chair breaking the smallest one into little pieces.
Next, the porridge, she obviously tried to eat it and because it was so hot she dropped it on the floor.
Making this mess, hmm, interesting.
These footprints seem to lead upstairs.
McGraw, did your officers clear the scene?
Well there was no one down here and maybe we forgot to check upstairs.
Hey, what's with all the noise?
I'm trying to sleep up here.
There she is!
Get her!
Alright, we're back.
So a lot of interesting phrases there.
They are obviously investigating a break-in.
Okay, a break-in, yeah.
So someone broke into this family's house.
So they have to investigate the evidence and some of the things that were left behind.
So now why don't we take a look on language takeaways, some of the specific words they used.
Language takeaway.
Alright, the first word that we have is forensics, the forensics team.
Forensics team.
So a forensics team is a team at a police department or police station that studies the things that are left behind after a crime.
Mm-hmm.
All right, so that team goes and collects the evidence.
So you could look at hair or fingerprints or footprints, things like that.
A forensics team is kind of like a team that puts together puzzle pieces trying to figure out what the story was.
Mm-hmm, so as you said the the TV show CSI, the whole show revolves around, follows a group of forensic scientists who go to crime scenes and look at blood and different pieces of evidence that are left behind.
Very cool, so one piece of evidence that a forensics team might look at is a fingerprint.
That's right, a fingerprint or in the dialogue we found fingerprints, the plural form.
Okay, so for example if you go to a police station because the police think that you have committed a crime, the police will take your fingerprints.
That means they'll put your finger, that means they'll put your fingers into ink and they will, they will make you push your fingers onto a piece of paper to see what your your fingers look like.
That's right, so our fingerprints have a unique pattern.
Everyone has different fingerprints.
There are no two fingerprints alike in the world, right?
Right, so it's kind of like a form of identification.
Mm-hmm, very good.
That's right, so that is your fingerprint.
So moving on, we talked about fingerprints now the and the scientists who are investigating the crime scene and they are talking about a very important piece of trace evidence.
Okay, well let's look first at the second word there.
We've got the word evidence.
So evidence is something that is usually physical like a piece of clothing or hair that can be used against someone when we're trying to prove that they have committed a crime.
Right, so for example a weapon or fingerprints, all that is evidence.
Okay, so Marco, what's the difference between evidence and trace evidence?
Well as you'd notice you have the specific word there trace and to trace means to to follow or connect maybe to connect right?
So what you're doing here is you are taking this evidence to follow or connect the person that committed the crime.
So for example fingerprints lets you know who committed the crime.
Okay, or maybe if you have blood you can find out who did this crime.
Right, but what about like a broken window?
Well that's just evidence that just lets you know how the crime was committed maybe how they got into the house but not who did it.
Okay, so trace evidence helps you connect the crime to the person who committed the crime.
And well moving on we found that very important piece of trace evidence which was a piece of or a strand of golden hair and the police officer said well this tells me that the suspect has long golden hair so a suspect.
Okay this word is it looks exactly the same as the word to suspect but be careful because we say these two words in different in different ways.
So to suspect that's a verb.
That's right so I suspect Marco did it.
So that means I think or I imagine.
Right, whereas a suspect a noun a suspect is a person so the person who we think or the person who the police think committed a crime.
Okay, okay so for example we're talking about some trace evidence like long blonde hair that means the suspect is probably a woman and is probably blonde.
Very good and it's interesting that you use the verb to suspect and a suspect all because you're not sure yet so this person may have committed the crime or may not.
That's right so we have to wait until the trial we have to wait until we prove this person is guilty before we can say that they actually committed the crime.
Very good okay and well you have a suspect and usually you also have somebody who is an accomplice to the crime or to the suspect.
Okay so a suspect as we said is a person it's a noun so is an accomplice.
So accomplice is a suspect's helper.
Right so basically if you're robbing a bank and I wait outside in the car right while you're robbing the bank then I am an accomplice.
That's right and under most laws you could be sentenced to jail.
Right so the accomplice usually doesn't commit the crime right you robbed the bank but I just waited outside in the car to drive you out so I didn't rob the bank.
Right but sometimes accomplices do also have guns and shoot people or knives so an accomplice is basically just the helper of the criminal but they can get in trouble too.
Right so basically it's a person that helps out and knows about the crime but didn't tell the police about it.
Exactly.
That's a really important aspect.
Okay so a lot of interesting words there all related to crimes.
Why don't we move on now to a couple of different phrases that we have prepared for you on Fluency Builder.
Fluency Builder.
Okay I like this this first phrase it's a it's a phrase you might hear a lot actually in police shows.
Mm-hmm.
Give it to me straight.
Give it to me straight.
Actually also you can use it when you're just talking to someone and they're like hesitant right like I don't know how to tell you this but I'm not so sure I don't think you're gonna like what I have to say.
So I can just say okay come on just give it to me straight.
Okay I don't like your shirt.
No I'm just kidding that's a nice shirt but what you're basically asking for is the person to say be honest with me.
Be direct.
Be direct.
Straight can mean both of those things.
Honest or straightforward or quick you don't want someone to go around and around and say lots of different things.
So I guess yeah that does make sense give it to me straight maybe comes from straightforward.
So to be straightforward is to not hesitate to just say something directly and honestly.
Exactly.
Okay so moving on to our next phrase McGraw is talking about the bowls and he said well they are analyzing them back at the lab as we speak.
As we speak okay so this is actually a phrase that refers to time.
So in this instance what he's basically saying is right now they're being analyzed right now or in this moment.
So it's a way of indicating that something is happening at this very moment.
Exactly so I could say did you know that the president is giving a speech as we speak.
Okay so that means the president is talking right now.
Exactly.
As we speak.
Okay very good phrase.
Now moving on to our third phrase Detective McGee was talking about reconstructing the crime.
He said let's reconstruct the crime.
Okay so I don't know if any of you watch these crime TV shows like Dexter or CSI.
This is my favorite part because they tell you exactly what they believe happened.
So to reconstruct means to build again or to recreate to create again.
So basically they start at the beginning and they pretend to follow what happened during the crime.
So that's basically the the verb to reconstruct to rebuild recreate.
Okay reconstruct the crime.
Very good and what about our last phrase.
Okay so our last phrase is again a very typical police phrase.
You hear this a lot when there's been a crime or on TV when they're talking about the scene of the crime that means the place where the crime happened and the police say we need to clear the scene or did the officers clear the scene.
So to clear means to empty out.
Right but they're not talking about emptying out the evidence or removing everything from the house.
They're just saying to remove people right.
Right.
Or obstructions.
Exactly and why is it that a police officer would want to make all the people go away.
Well because you don't want people stepping on the evidence or maybe putting their fingerprints all over the place.
Right so it's very important that the officers the police officers clear the scene so that they can start their investigation.
Right very good a lot of interesting phrases there.
I think we should go back why don't we listen to the dialogue for the last time and we'll come back and talk a little bit more this and we'll come back and talk a little bit more about this really interesting topic.
Alright officer McGraw give it to me straight.
What are we looking at here?
Detective McGee glad to see you.
We could sure use your expertise on this one.
It's a break-in but nothing seems to have been stolen.
We received a call from the Baer family at around 1030 this morning.
They'd gone out for a walk before breakfast and came home to this mess.
Broken chairs and porridge all over the place.
Apparently Mama Baer had made the porridge a little too hot you see.
They were waiting for it to cool down.
Okay then let's start examining the evidence.
Have the forensics team been in yet?
Yes sir they found some fingerprints on the bowls and are analyzing them back at the lab as we speak.
Hopefully they will be able to identify the burglar soon.
Hmm.
Aha!
What's this?
A strand of golden hair.
This is a very important piece of trace evidence McGraw.
It tells me the suspect has long golden hair and very few men have long golden hair.
So our criminal could be a woman.
A woman?
Was she working alone?
Did she have an accomplice?
An accomplice?
No no McGraw she was definitely working alone.
See here there are footprints in the porridge.
Here on the floor small footprints.
This tells me that our suspect is small and could possibly be a child.
A child?
Surely not sir.
We must follow the clues McGraw.
The evidence doesn't lie.
Now let's reconstruct the crime.
The suspect came in sat in each chair breaking the smallest one into little pieces.
Next the porridge she obviously tried to eat it and because it was so hot she dropped it on the floor making this mess.
Hmm interesting.
These footprints seem to lead upstairs.
McGraw did your officers clear the scene?
Well there was no one down here and maybe we forgot to check upstairs.
Hey what's with all the noise?
I'm trying to sleep up here.
There she is!
Get her!
So you mentioned a couple of different shows such as Dexter and CSI.
Do you watch any of these shows?
I do.
I'm a big fan of Dexter.
Dexter.
And Dexter as you know works at a police station in Miami and his character is in forensics.
He analyzes blood.
Right he's like a blood expert.
But it's interesting because he is actually he commits crimes himself so he uses his knowledge to help him to not get caught.
Right so he's both a criminal and he's a police officer.
But he's kind of like a superhero criminal right because he doesn't kill for fun or pleasure he just takes out people who kind of deserve it right?
Yes but he does kind of do it for pleasure because he's obsessed he can't not kill.
So instead of killing good people he decides he will only ever kill bad people.
It's a really good show I've watched a couple of episodes and it's very very good the same as CSI.
There are a couple of different versions there CSI Miami New York and Las Vegas but my favorite is Las Vegas very very good.
And also Law and Order.
I've watched a couple of episodes of Law and Order it's pretty good.
Yeah they often talk about forensics because they they have both parts they have the police part and the law part with the lawyers who have to use the evidence in court.
Very interesting.
And there's also well forensic scientists they take a look at the evidence but I think also they examine the body back at the at the morgue right?
That's right they look at the body to find out what happened to the body.
This is all a part of reconstructing the crime.
So this person is also sometimes called a coroner right?
Okay the person who analyzes the body.
It's pretty scary though if you think if you think about it having to you know to analyze a body.
I don't know it's.
You have to I think you have to be very experienced.
It's a very interesting I don't know I don't even know how somebody becomes a forensic scientist for example.
Oh yeah they have lots of forensic programs.
I think I saw in Discovery Channel they have a reality TV show about you know students forensic students and they're actually taken to real crime scenes and then they get eliminated one by one.
I'll have to look it up.
Well I'm curious to know have you ever heard of this before forensic science or forensic anthropology?
There are lots of people who study this and who do this as a job and if you're not interested in that maybe you could tell us about what kind of crime drama TV shows you like because we certainly love them here.
Our website is EnglishPod.com.
All right we'll see everyone there.
Bye. +
