= 0225
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../../myAdocCss.css

'''


 Hello everyone and welcome to EnglishPod.
My name is Marco.
My name is Katherine and today we are here with an advanced level lesson.
That means that we're going to listen to a pretty long and exciting dialogue and then we'll talk a little bit about what you've heard and some of these cool interesting phrases.
That's right.
Today we have a lesson about planning a crime or planning a bank robbery.
Oh, my favorite.
There have been lots of movies about this topic, very fun movies.
From the beginning of movie making till now, it's a very popular topic.
That's right and on this occasion, as Katherine said, it's a nice fun dialogue and we're going to have a lot of colloquial terms so maybe you won't really understand a couple of different phrases because they're very colloquial, they're very American terms.
And the accents are also, they're a little bit from like Boston, kind of like New Jersey maybe or something.
Right, so keep an ear out for some of these strange or unusual phrases.
We will be talking about them in a moment, but don't worry if you don't understand this dialogue the first time, you'll be hearing it again later.
All right, let's run through this one more time from the top.
I will be positioned here, across from the bank on this park bench.
Now according to the intel we got from Jimmy.
Oh, who's Jimmy?
Geez Ralph, pay attention will ya?
Jimmy's our mole, you know?
The guy on the inside?
He's been snooping and passing on the info to us so we can pull this heist off.
Yeah Ralph, clean the mothballs out of your ears and listen up.
This here's important.
We don't want to end up back in the slammer, do ya?
Your role is pretty important here, we're dependent on you man.
Okay, okay, I'm listening.
Mothballs.
All righty then, where was I?
Oh yeah, okay.
So I'll be on the lookout, sitting here on the bench across from the bank.
Nobody moves until I give the go ahead, all right?
And what's the go ahead Ralph?
You um, you uh, oh yeah, you'll take off your hat and scratch your head.
Right, when I take my hat off and scratch my head, you do what?
I get in the box.
Right, you get in the box.
I'll make sure it's all sealed and then posing as the delivery guy, I'll drop off a special package for the manager.
Now according to Jimmy, the bank manager is leaving early on Tuesday because it's his wedding anniversary.
He and the wife are having a romantic rendezvous in the country, so any packages delivered will be left unopened in his office until he gets back late on Wednesday.
Which gives us access to his office for at least 12 hours.
Okay Ralph, this is where you come in.
Where are you?
I'm standing right next to you Sammy.
Oh, sorry Sam, I'm in the box, right here, in that box.
And what do you do once I deliver you to the manager's office?
I stay in the box until the bank is closed, and then I get out of the box.
And then?
What next Ralph?
Oh for Pete's sake, this is never going to work.
Hey, give me a chance here fellas.
I crack the safe and then, then I take the money, and then I um, I get back in the box.
Atta boy Ralph, in the morning I come back to the bank, say there's been a mix up with the delivery I made, and take the special package back here.
Alright, let's get some sleep.
It's a big day tomorrow fellas.
A perfect plan Sammy, it went off without a hitch.
Let's open this up and get Ralph out of here so we can start counting the money.
Phew, I sure am glad to see you guys.
I was sure getting lonely with no one to talk.
That's nice, okay, how much?
Uh, really?
Really really really glad.
Money Ralph, money!
Oh man, I knew I forgot something.
Dammit.
Alright we're back, so um, obviously this guy Ralph, I don't know why, always the one robber whose name is Ralph is not very clever.
No, it doesn't mean that Ralphs are generally not smart people, but yeah I think you're right, there's usually...
Like in bank robberies or something, like for example in the old movies, always Ralph was the one messing things up.
Oh Ralph, well let's find out what Ralph screwed up today.
First of all we've got the guys Sammy, Ralph, and Frankie who are talking about the plan.
And Sammy mentions that he had the intel from Jimmy.
So when we talk about intel, we're talking about information right?
That's right, so intel is a word that's short for intelligence, or facts, or information.
That's right, so you can talk about intelligence as maybe you're very smart, you're very intelligent, but when we talk about intelligence, we talk about gathering information in order to help us accomplish an objective.
For example, in movies about the CIA, we often hear them talk about gathering intel.
That means collecting facts.
Right, very good.
So they had intel from Jimmy about the bank and the layout, and well they were like, who's Jimmy?
And Sammy says that well, he's our mole, you know, the guy on the inside.
A mole.
So mole is an animal, but in cases of intelligence, or maybe in this case a bank robbery, spying, a mole is a person who's basically stealing information.
So for example, if I work in the CIA, but I'm selling information from the CIA to the French government, I'm a mole.
Right, so you're basically like a spy.
You're a person on the inside, and that's what they mean when he says, he's our guy on the inside, you're inside the enemy's territory, or you're inside their organization.
Exactly.
So for example, have you seen the show 24?
Yeah, with Jack Bauer.
Well, they often have this problem of moles inside the organization, so maybe the terrorists have a guy on the inside.
That's right.
He's a mole.
So they have somebody that has penetrated their organization.
Exactly.
Okay, so they talk about the mole and how they are going to pull this heist off.
Okay, so the phrase here is to pull off a heist.
First of all, what's a heist?
Well, a heist is a robbery, basically a robbery.
Yeah, it's another word for robbery.
It's kind of old though, you don't really say it anymore, right?
No, you can say it's a heist movie, or it's a movie about a heist.
It's almost like a genre.
There's a basic storyline where they plan the robbery, they do the robbery, something goes wrong, what's going to happen, so that's a heist.
Very good.
So a heist is something that was planned out, like a robbery that's planned out.
It's not really if you come up to someone and say, give me your wallet.
That's not really a heist.
No, that's a stick up.
Right.
But a heist is something that you pull off.
So to pull off is to succeed.
To accomplish.
To accomplish.
So I pulled it off.
I was able to do it.
So you pulled off the heist.
Very good.
And well, they were talking about if they do it, they don't want to get caught because they don't want to go back to the slammer.
The slammer.
Yeah, well, I don't blame them.
I wouldn't want to go to the slammer either.
So what is the slammer?
The slammer.
The big house.
Right.
Lockup, the slammer, the big house.
All these are colloquial synonyms for prison, for jail.
Jail.
So normally we say prison or jail, like it's a maximum security prison.
Like Prison Break, the TV show.
Right.
But in colloquial English, we often say slammer.
Okay.
The slammer or the big house.
Okay.
So they were talking that they don't want to go back to the slammer.
And now when they were actually planning out the crime, he says, well, you wait until I give you the go ahead.
Okay.
So this is the plan.
He's going to wait for a sign.
The go ahead means a sign that indicates that it's time to do something.
Okay.
So for example, so in this case, what is that sign?
The go ahead is he'll take off his hat and scratch his head.
Okay.
So that's a sign that means it's okay to proceed.
It's okay to continue.
Right.
So you can also say, okay, when we're ready to go, Marco, I'll give you the go ahead.
Okay.
Just wait for me to wave.
Okay.
Very good.
So that's the go ahead.
The signal.
Exactly.
All right.
Very good.
Now moving on, we have a French word here, but that's used very commonly in English.
And they said, okay, we have a rendezvous.
Okay.
So a rendezvous is a meetup or a time or place where people are connecting together.
So for example, in a heist, you could say we're going to rob the bank and then we will rendezvous at our favorite restaurant in two hours.
Okay.
So rendezvous is to meet up, to get together.
Right.
But in this case, they're talking about a romantic rendezvous.
So this means a trip with a lover.
So it's a little bit different, right?
He and his wife are having a romantic rendezvous in the country.
Okay.
That means that they're going to have a romantic meeting.
Okay.
Very good.
And now this next phrase is very, very interesting.
It's very common to hear it as well.
I think like moms say it a lot.
Oh, for Pete's sake.
Oh, for Pete's sake.
Well, I don't know who Pete is, honestly.
But this means my gosh, or come on, or I'm so tired of this.
So you're a little bit exasperated.
Maybe you're a little bit irritated.
Oh, for Pete's sake, Marco, stop giving me examples.
I'm done hearing them.
So there are a lot of other ways to say this, right?
Yeah.
So you could say for goodness sake.
For goodness sake.
Or, oh, for heaven's sake.
For heaven's sake.
And finally, for God's sake.
But this one you have to be careful because some people who are religious might be offended if you use it.
So if that's the case, then you would just rather go with Pete's sake, heaven's sake, or goodness sake.
Okay, for goodness sake.
It's a very common phrase.
And as you say, it's for when you're a little bit irritated.
It's like, oh, for goodness sake, stop complaining.
Exactly.
Right?
Okay.
And now for our last word, you may have seen the word fellas.
Fellas.
Fellas.
So this comes from the word fellow, person, man.
But oftentimes in these kind of movies or stories about heists or, you know, crimes, the men talk to each other using the word fella or fellas.
So come on, fellas, let's go.
That means come on, guys, come on, everyone.
Okay, yeah.
So this is always about men.
Not like a group of women would use this.
And it's something that's a little bit older.
We don't really say this like, oh, me and my fellas, we're going to go to the store.
You would say this more in old time English.
Yeah, you can see it maybe in some movies when somebody comes up and greets other people, other guys, he would say, hey, fellas.
Exactly.
Or there's a mafia movie.
It's about the American mafia called Goodfellas.
Very good.
It's a very famous one.
So it kind of gives you that feeling of an older English like the 1940s to the 1970s.
Okay, very good.
A lot of interesting things going on in this bank robbery.
Why don't we go back, listen to the dialogue one last time, and we'll be back in a little bit.
All right, let's run through this one more time from the top.
I will be positioned here across from the bank on this park bench.
Now according to the intel we got from Jimmy.
Oh, who's Jimmy?
Geez, Ralph, pay attention, will ya?
Jimmy's our mole, you know?
The guy on the inside.
He's been snooping and passing on the info to us so we can pull this heist off.
Yeah, Ralph, clean the mothballs out of your ears and listen up.
This here's important.
We don't want to end up back in the slammer, do ya?
Your role is pretty important here.
We're dependent on you, man.
Okay, okay, I'm listening.
Mothballs.
All righty then.
Where was I?
Oh yeah, okay.
So I'll be on the lookout, sitting here on the bench across from the bank.
Nobody moves until I give the go-ahead, all right?
And what's the go-ahead, Ralph?
You um, you uh, oh yeah, you'll take off your hat and scratch your head.
Right.
When I take my hat off and scratch my head, you do what?
I get in the box.
Right, you get in the box.
I'll make sure it's all sealed and then posing as the delivery guy, I'll drop off a special package for the manager.
Now according to Jimmy, the bank manager's leaving early on Tuesday because it's his wedding anniversary.
He and the wife are having a romantic rendezvous in the country, so any packages delivered will be left unopened in his office until he gets back late on Wednesday.
Which gives us access to his office for at least 12 hours.
Okay Ralph, this is where you come in.
Where are you?
I'm standing right next to you, Sammy.
Oh, sorry, Sam.
I'm in the box, right here, in that box.
And what do you do once I deliver you to the manager's office?
I stay in the box until the bank is closed.
And then I get out of the box.
And then?
What next, Ralph?
Oh, for Pete's sake, this is never going to work.
Hey, give me a chance here, fellas.
I crack the safe and then, then I take the money.
And then I, um, I get back in the box.
Atta boy, Ralph.
In the morning I come back to the bank, say there's been a mix-up with the delivery I made and take the special package back here.
Alright, let's get some sleep.
It's a big day tomorrow, fellas.
A perfect plan, Sammy.
It went off without a hitch.
Let's open this up and get Ralph out of here so we can start counting the money.
Phew, I sure am glad to see you guys.
I was sure getting lonely with no one to talk.
That's nice.
Okay, how much?
Uh, really?
Really, really, really glad.
Money, Ralph, money!
Oh man, I knew I forgot something.
Ahhh!
Dammit.
Okay, so, someone proclaimed at the end of the dialogue that everything went off without a hitch.
Mm-hmm.
Is this true?
No.
What does it mean if something went without a hitch?
It went off without a hitch means there was not even one problem.
It went off, it went perfectly.
Smoothly.
Smoothly, yes.
Okay.
And it didn't because, well, these robbers didn't actually rob anyone.
Right, he forgot to get the money.
Right, so he's kind of an idiot.
Right, but there are actually a lot of good movies.
I think the most recent one about bank robberies is Oceans 11, Oceans 12, Oceans 13.
Yeah, that's right, those are all about big heists.
Big heists.
And I think they mentioned the word heist a couple of times in that movie.
Yeah, definitely.
So there was a movie with Clive Owen a few years ago called The Inside Man that was maybe one of the best heist movies I've seen in a long time.
Ah, yeah, that was a really good movie.
I think also Swordfish was a pretty good movie with John Travolta.
Yeah, I remember that one too.
Yeah, I like it when the bad guys win.
Uh-huh.
You know, because it's a little bit more interesting.
Yeah, I guess you could say that.
I don't think the public likes this.
Um, well, in The Inside Man, the bad guy is kind of a good guy, but he wins.
Uh-huh.
Yeah, I like that.
Yeah, so, but it's a very interesting topic and I don't know, I haven't really heard of many bank robberies nowadays anymore.
Not so much, I think security in banks is pretty good, but I'd be very curious to hear from our users if they have any favorite heist stories or movies, real or fake, both are okay.
You can let us know on our website, EnglishPod.com.
That's right.
All right, we'll see everyone there.
Bye.
Bye. +
