
= 251-300 句
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: myAdocCss.css

'''

== 释义


- 251. The broad language of the amendment strongly suggests that its framers were proposing to write into the Constitution—not a laundry list 一长串 of specific civil rights but a principle of equal citizenship that forbids organized society from treating any individual as a member of an inferior class. +

- 252. This was largely due to the enterprise 事业心 of Watteau's friends who, soon after his death, organized the printing of engraved reproductions 雕刻复制品 of the great bulk of his work—both his paintings and his drawings—so that Watteau's total artistic output 艺术作品 became and continued to be more accessible than that of any other artist until the twentieth-century advent 出现 of art monographs 专题著作 illustrated with photographs. +

- 253. This is not because such an interpretation necessarily stiffens into a thesis (although rigidity 僵化 in any interpretation of this or of any novel is always a danger), but because Wuthering Heights has recalcitrant 难驾驭的 elements of undeniable power that, ultimately, resist inclusion in an all-encompassing 包罗万象的 interpretation. +

- 254. Even the “radical” critiques 批判 of this mainstream research model, such as the critique developed in Divided Society, attach 把……联系起来 the issue of ethnic assimilation 民族同化 too mechanically to factors of economic and social mobility and are thus unable to illuminate 阐明 the cultural subordination 文化从属 of Puerto Ricans as a colonial minority. +

- 255. While Hume's history was generally seen as being less objectionable 令人反感的 as his philosophy, there were widespread doubts about his moral soundness 道德可靠性 even as a historian by the time that Hanway was writing, and Gibbon's perceived tendency to celebrate classical paganism 异教信仰 sparked controversy 引发争议 from the first appearance of his history of Rome. +

- 256. Open acknowledgement 公开承认 of the existence of women's oppression 压迫 was too radical for the United States in the fifties, and Beauvoir's conclusion, that change in women's economic condition, though insufficient 不足的 by itself, “remains the basic factor” in improving women's situation, was particularly unacceptable. +

- 257. This was largely due to the enterprise 事业心 of Watteau's friends who, soon after his death, organized the printing of engraved reproductions 雕刻复制品 of the great bulk of his work—both his paintings and his drawings—so that Watteau's total artistic output 艺术作品 became and continued to be more accessible than that of any other artist until the twentieth-century advent 出现 of art monographs 专题著作 illustrated with photographs. +

- 258. This is not because such an interpretation necessarily stiffens into a thesis (although rigidity 僵化 in any interpretation of this or of any novel is always a danger), but because Wuthering Heights has recalcitrant 难驾驭的 elements of undeniable power that, ultimately, resist inclusion in an all-encompassing 包罗万象的 interpretation. +

- 259. Even the “radical” critiques 批判 of this mainstream research model, such as the critique developed in Divided Society, attach 把……联系起来 the issue of ethnic assimilation 民族同化 too mechanically to factors of economic and social mobility and are thus unable to illuminate 阐明 the cultural subordination 文化从属 of Puerto Ricans as a colonial minority. +

- 260. While Hume's history was generally seen as being less objectionable 令人反感的 as his philosophy, there were widespread doubts about his moral soundness 道德可靠性 even as a historian by the time that Hanway was writing, and Gibbon's perceived tendency to celebrate classical paganism 异教信仰 sparked controversy 引发争议 from the first appearance of his history of Rome. +

- 261. Open acknowledgement 公开承认 of the existence of women's oppression 压迫 was too radical for the United States in the fifties, and Beauvoir's conclusion, that change in women's economic condition, though insufficient 不足的 by itself, “remains the basic factor” in improving women's situation, was particularly unacceptable. +

- 262. The nonstarters were considered the ones who wanted stability, a strong referee 裁判 to give them some position in the race, a regulative 监管的 hand to calm manic speculation 疯狂投机; an authority that can call things to a halt, begin things again from compensatorily 补偿性地 staggered “starting lines.” +

- 263. “Reform” in America has been sterile 无效的 because it can imagine no change except through the extension of this metaphor 隐喻 of a race, wider inclusion of competitors, “a piece of the action,” as it were, for the disenfranchised 被剥夺权利的人. +

- 264. The enclosed seas 内海 are an important feature of the earth's surface, and seriously require explanation because, in addition to the enclosed seas that are developing at present behind island arcs 岛弧, there are a number of older ones of possibly similar origin, such as the Gulf of Mexico, the Black Sea, and perhaps the North Sea. +

- 265. Furthermore, neutrinos 中微子 carry with them information about the site and circumstances of their production: therefore, the detection of cosmic neutrinos could provide new information about a wide variety of cosmic phenomena and about the history of the universe. +

- 266. The factors favoring unionization drives 工会组织运动 seem to have been either the presence of large numbers of workers, as in New York City, to make it worth the effort, or the concentration of small numbers in one or two locations, such as a hospital, to make it relatively easy. +

- 267. If the competitor can prove injury from the imports—and that the United States company received a subsidy 补贴 from a foreign government to build its plant abroad—the United States company's products will be uncompetitive in the United States, since they would be subject to duties 关税. +

- 268. Increasingly, historians are blaming diseases imported from the Old World for the staggering disparity 惊人的差异 between the indigenous population 土著人口 of America in 1492—new estimates of which soar 猛增 as high as 100 million, or approximately one-sixth of the human race at that time—and the few million full-blooded Native Americans alive at the end of the nineteenth century. +

- 269. He noted that the wavelengths 波长 of the radiation emitted by a gas would change as the gas cooled, so that as the gas flowed into the galaxy and became cooler, it would emit not x-rays, but visible light, like that which was captured in the photographs. +

- 270. Transported outside the nucleus to the cytoplasm 细胞质, the mRNA is translated into the protein it encodes by an organelle 细胞器 known as a ribosome 核糖体, which strings together amino acids 氨基酸 in the order specified by the sequence of elements in the mRNA molecule. +

- 271. Although he regrets that some Western intellectuals demand more democracy from polyarchies 多头政治 than is possible, and is cautious about the possibility of further democratization, he nevertheless ends his book by asking what changes in structures and consciousness might make political life more democratic in present polyarchies. +

- 272. Steeped as they were in the English political language, these colonials failed to observe that their experience in America had given the words a significance quite different from what accepted by the English with whom they debated; in fact, they claimed that they were more loyal to the English political tradition than were the English in England. +

- 273. However, as they gained cohesion 凝聚力, the Bluestockings came to regard themselves as a women's group and to possess a sense of female solidarity 女性团结 lacking in the salonnieres, who remained isolated from one another by the primacy 首位 each held in her own salon. +

- 274. The historian Frederick J. Turner wrote in the 1890's that the agrarian discontent 农民不满 that had been developing steadily in the United States since about 1870 had been precipitated 引发 by the closing of the internal frontier—that is, the depletion 耗尽 of available new land needed for further expansion of the American farming system. +

- 275. In its final section, by declaring the resolution is not intended to alter the constitutional authority 宪法权威 of either Congress or the President, the resolution asserts that congressional involvement in decisions to use armed force is in accord with 符合 the intent and spirit of the Constitution. +

- 276. Thus, women in education are more likely to become teachers than school administrators, whose more conventional full-time work schedules do not correspond to 与……一致 the schedules of school-age children, while female lawyers are more likely to practice law in trusts and estates 信托与遗产, where they can control their work schedules, than in litigation 诉讼, where they cannot. +

- 277. Steeped as they were in the English political language, these colonials failed to observe that their experience in America had given the words a significance quite different from what accepted by the English with whom they debated; in fact, they claimed that they were more loyal to the English political tradition than were the English in England. +

- 278. However, as they gained cohesion 凝聚力, the Bluestockings came to regard themselves as a women's group and to possess a sense of female solidarity 女性团结 lacking in the salonnieres, who remained isolated from one another by the primacy 首位 each held in her own salon. +

- 279. The historian Frederick J. Turner wrote in the 1890's that the agrarian discontent 农民不满 that had been developing steadily in the United States since about 1870 had been precipitated 引发 by the closing of the internal frontier—that is, the depletion 耗尽 of available new land needed for further expansion of the American farming system. +

- 280. In its final section, by declaring the resolution is not intended to alter the constitutional authority 宪法权威 of either Congress or the President, the resolution asserts that congressional involvement in decisions to use armed force is in accord with 符合 the intent and spirit of the Constitution. +

- 281. Thus, women in education are more likely to become teachers than school administrators, whose more conventional full-time work schedules do not correspond to 与……一致 the schedules of school-age children, while female lawyers are more likely to practice law in trusts and estates 信托与遗产, where they can control their work schedules, than in litigation 诉讼, where they cannot. +

- 282. The discrepancy 矛盾 between historical fact and artistic vision, useful in refuting 反驳 the extreme deterministic position, merely forced these writers to seek a new formula that allowed them to preserve the desired identity between image and reality, this time a rather suspiciously psychic 心灵的 one: Watteau did not record the society he knew, but rather “foresaw” a society that developed shortly after his death. +

- 283. Besides the normal economic risk that accompanies such enterprises, investors face the additional risk that the host government may attempt unilaterally 单方面地 to change in its favor the terms of the agreement or even to terminate 终止 the agreement altogether and appropriate 挪用 the project for itself. +

- 284. Gray marketing 灰色营销, the selling of trademarked products through channels of distribution not authorized by the trademark holder, can involve distribution of goods either within a market region or across market boundaries. +

- 285. After thirty years of investigation into cell genetics, researchers made startling discoveries in the 1960s and early 1970s which culminated in 最终导致 the development of processes, collectively known as recombinant deoxyribonucleic acid (rDNA) technology 重组脱氧核糖核酸技术, for the active manipulation 操纵 of a cell's genetic code. +

- 286. The term deconstruction 解构主义 implies that the text has been put together like a building or a piece of machinery, and that it is in need of being taken apart, not so much in order to repair it as to demonstrate underlying inadequacies 缺陷, false assumptions, and inherent contradictions 内在矛盾. +

- 287. Instead, they determined to improve tribal life by lobbying for 游说 federal monies for postsecondary education, for the improvement of drainage on tribal lands, and for the building of a convalescent home 疗养院 for tribal members. +

- 288. However, they guided solely by the speeches prepared for the parties by professional pleaders 辩护人 and by the quotations of laws or decrees 法令 within the speeches, rather than by their own access to any kind of document or book. +

- 289. More than a century of government under written constitutions convinced these colonists of the necessity for and efficacy 效力 of protecting their liberties against governmental encroachment 侵犯 by explicitly defining all governmental powers in a document. +

- 290. Were there something peculiarly efficient about the free market and inefficient about price-fixing, the countries that have avoided the first and used the second would have suffered drastically in their economic development. +

- 291. Fallois proposed that Proust had tried to begin a novel in 1908, abandoned it for what was to be a long demonstration of Saint-Beuve's blindness to the real nature of great writing, found the essay giving rise to 引发 personal memories and fictional developments, and allowed these to take over in a steadily developing novel. +

- 292. While the new doctrine seems almost certainly correct, the one papyrus fragment 纸莎草碎片 raises the specter 幽灵 that another may be unearthed, showing, for instance, that it was a posthumous production 遗作 of the Danaid tetralogy 四部曲 which bested Sophocles, and throwing the date once more into utter confusion. +

- 293. Because the potential hazards pollen grains are subject to as they are transported over long distances are enormous, wind-pollinated plants have, in the view above, compensated for 补偿 the ensuing loss of pollen through happenstance 偶然 by virtue of 由于 producing an amount of pollen that is one to three orders of magnitude 数量级 greater than the amount produced by species pollinated by insects. +

- 294. For example, the spiral arrangement 螺旋排列 of scale-bract complexes 鳞苞复合体 on ovule-bearing pine cones 带胚珠的松果, where the female reproductive organs of conifers 针叶树 are located, is important to the production of airflow patterns that spiral over the cone's surfaces, thereby passing airborne pollen from one scale to the next. +

- 295. As a consequence, it may prove difficult or impossible to establish for a successful revolution a comprehensive and trustworthy picture of those who participated, or to answer even the most basic questions one might pose concerning the social origins of the insurgents 叛乱者. +

- 296. But the recent discovery of detailed similarities in the skeletal structure 骨骼结构 of the flippers 鳍状肢 in all three groups undermines 削弱 the attempt to explain away superficial resemblance as due to convergent evolution 趋同进化—the independent development of similarities between unrelated groups in response to similar environmental pressures. +

- 297. While the new doctrine seems almost certainly correct, the one papyrus fragment 纸莎草碎片 raises the specter 幽灵 that another may be unearthed, showing, for instance, that it was a posthumous production 遗作 of the Danaid tetralogy 四部曲 which bested Sophocles, and throwing the date once more into utter confusion. +

- 298. Because the potential hazards pollen grains are subject to as they are transported over long distances are enormous, wind-pollinated plants have, in the view above, compensated for 补偿 the ensuing loss of pollen through happenstance 偶然 by virtue of 由于 producing an amount of pollen that is one to three orders of magnitude 数量级 greater than the amount produced by species pollinated by insects. +

- 299. For example, the spiral arrangement 螺旋排列 of scale-bract complexes 鳞苞复合体 on ovule-bearing pine cones 带胚珠的松果, where the female reproductive organs of conifers 针叶树 are located, is important to the production of airflow patterns that spiral over the cone's surfaces, thereby passing airborne pollen from one scale to the next. +

- 300. As a consequence, it may prove difficult or impossible to establish for a successful revolution a comprehensive and trustworthy picture of those who participated, or to answer even the most basic questions one might pose concerning the social origins of the insurgents 叛乱者. +

'''

== pure

- 251. The broad language of the amendment strongly suggests that its framers were proposing to write into the Constitution +4not a laundry list of specific civil rights but a principle of equal citizenship that forbids organized society from treating any individual as a member of an inferior class.

- 252. This was largely due to the enterprise of Watteau's friends who, soon after his death, organized the printing of engraved reproductions of the great bulk of his work—both his paintings and his drawings—so that Watteau's total artistic output became and continued to be more accessible than that of any other artist until the twentieth-century advent of art monographs illustrated with photographs.

- 253. This is not because such an interpretation necessarily stiffens into a thesis (although rigidity in any interpretation of this or of any novel is always a danger), but becauseWuthering Heightshas recalcitrant elements of undeniable power that, ultimately, resist inclusion in an all-encompassing interpretation.

- 254. Even the “radical” critiques of this mainstream research model, such as the critique developed inDivided Society, attach the issue of ethnic assimilation too mechanically to factors of economic and social mobility and are thus unable to illuminate the cultural subordination of Puerto Ricans as a colonial minority.

- 255. While Hume's history was generally seen as being less objectionable as his philosophy, there were widespread doubts about his moral soundness even as a historian by the time that Hanway was writing, and Gibbon's perceived tendency to celebrate classical paganism sparked controversy from the first appearance of his history of Rome.

- 256. Open acknowledgement of the existence of women's oppression was too radical for the United States in the fifties, and Beauvoir's conclusion, that change in women's economic condition, though insufficient by itself, “remains the basic factor” in improving women's situation, was particularly unacceptable.

- 257. This was largely due to the enterprise of Watteau's friends who, soon after his death, organized the printing of engraved reproductions of the great bulk of his work—both his paintings and his drawings—so that Watteau's total artistic output became and continued to be more accessible than that of any other artist until the twentieth-century advent of art monographs illustrated with photographs.

- 258. This is not because such an interpretation necessarily stiffens into a thesis (although rigidity in any interpretation of this or of any novel is always a danger), but becauseWuthering Heightshas recalcitrant elements of undeniable power that, ultimately, resist inclusion in an allencompassing interpretation.

- 259. Even the “radical” critiques of this mainstream research model, such as the critique developed inDivided Society, attach the issue of ethnic assimilation too mechanically to factors of economic and social mobility and are thus unable to illuminate the cultural subordination of Puerto Ricans as a colonial minority.

- 260. While Hume's history was generally seen as being less objectionable as his philosophy, there were widespread doubts about his moral soundness even as a historian by the time that Hanway was writing, and Gibbon's perceived tendency to celebrate classical paganism sparked controversy from the first appearance of his history of Rome.

- 261. Open acknowledgement of the existence of women's oppression was too radical for the United States in the fifties, and Beauvoir's conclusion, that change in women's economic condition, though insufficient by itself, “remains the basic factor” in improving women's situation, was particularly unacceptable.

- 262. The nonstarters were considered the ones who wanted stability, a strong referee to give them some position in the race, a regulative hand to calm manic speculation; an authority that can call things to a halt, begin things again from compensatorily staggered “starting lines.”

- 263. “Reform” in America has been sterile because it can imagine no change except through the extension of this metaphor of a race, wider inclusion of competitors, “a piece of the action,” as it were, for the disenfranchised.

- 264. The enclosed seas are an important feature of the earth's surface, and seriously require explanation because, in addition to the enclosed seas that are developing at present behind island arcs, there are a number of older ones of possibly similar origin, such as the Gulf of Mexico, the Black Sea, and perhaps the North Sea.

- 265. Furthermore, neutrinos carry with them information about the site and circumstances of their production: therefore, the detection of cosmic neutrinos could provide new information about a wide variety of cosmic phenomena and about the history of the universe.

- 266. The factors favoring unionization drives seem to have been either the presence of large numbers of workers, as in New York City, to make it worth the effort, or the concentration of small numbers in one or two locations, such as a hospital, to make it relatively easy.

- 267. If the competitor can prove injury from the imports—and that the United States company received a subsidy from a foreign government to build its plant abroad—the United States company's products will be uncompetitive in the United States, since they would be subject to duties.

- 268. Increasingly, historians are blaming diseases imported from the Old World for the staggering disparity between the indigenous population of America in 1492—new estimates of which soar as high as 100 million, or approximately one-sixth of the human race at that time—and the few million full-blooded Native Americans alive at the end of the nineteenth century.

- 269. He noted that the wavelengths of the radiation emitted by a gas would change as the gas cooled, so that as the gas flowed into the galaxy and became cooler, it would emit not x-rays, but visible light, like that which was captured in the photographs.

- 270. Transported outside the nucleus to the cytoplasm, the mRNA is translated into the protein it encodes by an organelle known as a ribosome, which strings together amino acids in the order specified by the sequence of elements in the mRNA molecule.

- 271. Although he regrets that some Western intellectuals demand more democracy from polyarchies than is possible, and is cautious about the possibility of further democratization, he nevertheless ends his book by asking what changes in structures and consciousness might make political life more democratic in present polyarchies.

- 272. Steeped as they were in the English political language, these colonials failed to observe that their experience in America had given the words a significance quite different from what accepted by the English with whom they debated; in fact, they claimed that they were more loyal to the English political tradition than were the English in England.

- 273. However, as they gained cohesion, the Bluestockings came to regard themselves as a women's group and to possess a sense of female solidarity lacking in the salonnieres, who remained isolated from one another by the primacy each held in her own salon.

- 274. The historian Frederick J. Turner wrote in the 1890's that the agrarian discontent that had been developing steadily in the United States since about 1870 had been precipitated by the closing of the internal frontier—that is, the depletion of available new land needed for further expansion of the American farming system.

- 275. In its final section, by declaring the resolution is not intended to alter the constitutional authority of either Congress or the President, the resolution asserts that congressional involvement in decisions to use armed force is in accord with the intent and spirit of the Constitution.

- 276. Thus, women in education are more likely to become teachers than school administrators, whose more conventional full-time work schedules do not correspond to the schedules of school-age children, while female lawyers are more likely to practice law in trusts and estates, where they can control their work schedules, than in litigation, where they cannot.

- 277. Steeped as they were in the English political language, these colonials failed to observe that their experience in America had given the words a significance quite different from what accepted by the English with whom they debated; in fact, they claimed that they were more loyal to the English political tradition than were the English in England.

- 278. However, as they gained cohesion, the Bluestockings came to regard themselves as a women's group and to possess a sense of female solidarity lacking in the salonnieres, who remained isolated from one another by the primacy each held in her own salon.

- 279. The historian Frederick J. Turner wrote in the 1890's that the agrarian discontent that had been developing steadily in the United States since about 1870 had been precipitated by the closing of the internal frontier—that is, the depletion of available new land needed for further expansion of the American farming system.

- 280. In its final section, by declaring the resolution is not intended to alter the constitutional authority of either Congress or the President, the resolution asserts that congressional involvement in decisions to use armed force is in accord with the intent and spirit of the Constitution.

- 281. Thus, women in education are more likely to become teachers than school administrators, whose more conventional full-time work schedules do not correspond to the schedules of school-age children, while female lawyers are more likely to practice law in trusts and estates, where they can control their work schedules, than in litigation, where they cannot.

- 282. The discrepancy between historical fact and artistic vision, useful in refuting the extreme deterministic position, merely forced these writers to seek a new formula that allowed them to preserve the desired identity between image and reality, this time a rather suspiciously psychic one: Watteau did not record the society he knew, but rather “foresaw” a society that developed shortly after his death.

- 283. Besides the normal economic risk that accompanies such enterprises, investors face the additional risk that the host government may attempt unilaterally to change in its favor the terms of the agreement or even to terminate the agreement altogether and appropriate the project for itself.

- 284. Gray marketing, the selling of trademarked products through channels of distribution not authorized by the trademark holder, can involve distribution of goods either within a market region or across market boundaries.

- 285. After thirty years of investigation into cell genetics, researchers made startling discoveries in the 1960s and early 1970s which culminated in the development of processes, collectively known as recombinant deoxyribonucleic acid (rDNA) technology, for the active manipulation of a cell's genetic code.

- 286. The term deconstruction implies that the text has been put together like a building or a piece of machinery, and that it is in need of being taken apart, not so much in order to repair it as to demonstrate underlying inadequacies, false assumptions, and inherent contradictions.

- 287. Instead, they determined to improve tribal life by lobbying for federal monies for postsecondary education, for the improvement of drainage on tribal lands, and for the building of a convalescent home for tribal members.

- 288. However, they guided solely by the speeches prepared for the parties by professional pleaders and by the quotations of laws or decrees within the speeches, rather than by their own access to any kind of document or book.

- 289. More than a century of government under written constitutions convinced these colonists of the necessity for and efficacy of protecting their liberties against governmental encroachment by explicitly defining all governmental powers in a document.

- 290. Were there something peculiarly efficient about the free market and inefficient about price-fixing, the countries that have avoided the first and used the second would have suffered drastically in their economic development.

- 291. Fallois proposed that Proust had tried to begin a novel in 1908, abandoned it for what was to be a long demonstration of Saint-Beuve's blindness to the real nature of great writing, found the essay giving rise to personal memories and fictional developments, and allowed these to take over in a steadily developing novel.

- 292. While the new doctrine seems almost certainly correct, the one papyrus fragment raises the specter that another may be unearthed, showing, for instance, that it was a posthumous production of the Danaid tetralogy which bested Sophocles, and throwing the date once more into utter confusion.

- 293. Because the potential hazards pollen grains are subject to as they are transported over long distances are enormous, wind pollinated plants have, in the view above, compensated for the ensuing loss of pollen through happenstance by virtue of producing an amount of pollen that is one to three orders of magnitude greater than the amount produced by species pollinated by insects.

- 294. For example, the spiral arrangement of scale-bract complexes on ovule-bearing pine cones, where the female reproductive organs of conifers are located, is important to the production of airflow patterns that spiral over the cone's surfaces, thereby passing airborne pollen from one scale to the next.

- 295. As a consequence, it may prove difficult or impossible to establish for a successful revolution a comprehensive and trustworthy picture of those who participated, or to answer even the most basic questions one might pose concerning the social origins of the insurgents.

- 296. But the recent discovery of detailed similarities in the skeletal structure of the flippers in all three groups undermines the attempt to explain away superficial resemblance as due to convergent evolution—the independent development of similarities between unrelated groups in response to similar environmental pressures.

- 297. While the new doctrine seems almost certainly correct, the one papyrus fragment raises the specter that another may be unearthed, showing, for instance, that it was a posthumous production of the Danaid tetralogy which bested Sophocles, and throwing the date once more into utter confusion.

- 298. Because the potential hazards pollen grains are subject to as they are transported over long distances are enormous, wind pollinated plants have, in the view above, compensated for the ensuing loss of pollen through happenstance by virtue of producing an amount of pollen that is one to three orders of magnitude greater than the amount produced by species pollinated by insects.

- 299. For example, the spiral arrangement of scale-bract complexes on ovule-bearing pine cones, where the female reproductive organs of conifers are located, is important to the production of airflow patterns that spiral over the cone's surfaces, thereby passing airborne pollen from one scale to the next.

- 300. As a consequence, it may prove difficult or impossible to establish for a successful revolution a comprehensive and trustworthy picture of those who participated, or to answer even the most basic questions one might pose concerning the social origins of the insurgents.
