
= 301-350 句
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 释义

- 301. But the recent discovery of detailed similarities in the skeletal structure of the flippers in all three groups undermines the attempt to explain away superficial resemblance as due to convergent evolution—the independent development of similarities between unrelated groups in response to similar environmental pressures.

[.my1]
.案例
====
- 301. But the recent discovery of detailed similarities in the skeletal structure 骨骼结构 of the flippers 鳍状肢 in all three groups undermines 削弱 the attempt to explain away superficial resemblance 表面相似 as due to convergent evolution 趋同进化—the independent development of similarities between unrelated groups in response to similar environmental pressures.

====

- 302. In addition, the style of some Black novels, like Jean Toomer'sCane, verges on expressionism or surrealism; does this technique provide a counterpoint to the prevalent theme that portrays the fate against which Black heroes are pitted, a theme usually conveyed by more naturalistic modes of expression?

[.my1]
.案例
====
- 302. In addition, the style of some Black novels, like Jean Toomer's Cane, verges on 接近 expressionism 表现主义 or surrealism 超现实主义; does this technique provide a counterpoint 对立面 to the prevalent 盛行的 theme that portrays the fate against which Black heroes are pitted, a theme usually conveyed by more naturalistic modes of expression?

====

- 303. Studies by Hargrave and Geen estimated natural community grazing rates by measuring feeding rates of individual zooplankton species in the laboratory and then computing community grazing rates for field conditions using the known population density of grazers.

[.my1]
.案例
====
- 303. Studies by Hargrave and Geen estimated natural community grazing rates by measuring feeding rates of individual zooplankton 浮游动物 species in the laboratory and then computing community grazing rates for field conditions using the known population density of grazers 食草动物.

====

- 304. Historians such as Le Roy Ladurie have used the documents to extract case histories, which have illuminated the attitudes of different social groups (these attitudes include, but are not confined to, attitudes toward crime and the law) and have revealed how the authorities administered justice.

[.my1]
.案例
====
- 304. Historians such as Le Roy Ladurie have used the documents to extract case histories, which have illuminated 阐明 the attitudes of different social groups (these attitudes include, but are not confined to 不仅限于, attitudes toward crime and the law) and have revealed how the authorities administered justice 执行司法.

====

- 305. The idea of an autonomous discipline called “philosophy” distinct from and sitting in judgment on such pursuits as theology and science turns out, on close examination, to be of quite recent origin.

[.my1]
.案例
====
- 305. The idea of an autonomous 自主的 discipline called “philosophy” distinct from and sitting in judgment on 评判 such pursuits as theology 神学 and science turns out, on close examination, to be of quite recent origin.

====

- 306. Yet Walzer's argument, however deficient, does point to one of the most serious weaknesses of capitalism—namely, that it brings to predominant positions in a society people who, no matter how legitimately they have earned their material rewards, often lack those other qualities that evoke affection or admiration.

[.my1]
.案例
====
- 306. Yet Walzer's argument, however deficient 不足的, does point to one of the most serious weaknesses of capitalism—namely 即, that it brings to predominant 主导的 positions in a society people who, no matter how legitimately 合法地 they have earned their material rewards, often lack those other qualities that evoke 唤起 affection or admiration.

====

- 307. More probable is bird transport, either externally, by accidental attachment of the seeds to feathers, or internally, by the swallowing of fruit and subsequent excretion of the seeds.

[.my1]
.案例
====
- 307. More probable is bird transport, either externally, by accidental attachment of the seeds to feathers, or internally, by the swallowing of fruit and subsequent excretion 排泄 of the seeds.

====

- 308. Shaw's revolutionary “open-system” view recognizes a continuum between terrestrial and extraterrestrial dynamics, whereas modern plate tectonic theory, like the classical geology developed during the nineteenth century, is founded on the view that Earth's geological features have changed through gradual, regular processes intrinsic to Earth, without reference to unique catastrophic events.

[.my1]
.案例
====
- 308. Shaw's revolutionary “open-system” view recognizes a continuum 连续体 between terrestrial 地球的 and extraterrestrial 地外的 dynamics, whereas modern plate tectonic theory 板块构造理论, like the classical geology developed during the nineteenth century, is founded on 建立在……基础上 the view that Earth's geological features have changed through gradual, regular processes intrinsic to 固有的 Earth, without reference to 参考 unique catastrophic events.

====

- 309. How explicit and consistent the symbolizing process was intended to be is a much thornier matter, but anyone who has more familiarity than a passing acquaintance with Dutch literature or with the kinds of images used in illustrated books (above all emblem books) will know how much less pervasive was the habit of investing ordinary objects than of investing scenes with meaning that go beyond their surface and outward appearance.

[.my1]
.案例
====
- 309. How explicit and consistent the symbolizing process was intended to be is a much thornier 棘手的 matter, but anyone who has more familiarity than a passing acquaintance with Dutch literature or with the kinds of images used in illustrated books (above all emblem books 象征主义书籍) will know how much less pervasive 普遍的 was the habit of investing ordinary objects than of investing scenes with meaning that go beyond their surface and outward appearance.

====

- 310. Japanese automakers chose to make small-lot production feasible by introducing several departures from United States practices, including the use of flexible equipment that could be altered easily to do several different production tasks and the training of workers in multiple jobs.

[.my1]
.案例
====
- 310. Japanese automakers chose to make small-lot production feasible by introducing several departures from 背离 United States practices, including the use of flexible equipment that could be altered easily to do several different production tasks and the training of workers in multiple jobs.

====

- 311. Moreover, the rationale for Herbert's emphasis on the social and political realities that Impressionist paintings can be said to communicate rather than on their style is finally undermined by what even Herbert concedes was the failure of Impressionist painters to serve as particularly conscientious illustrators of their social milieu.

[.my1]
.案例
====
- 311. Moreover, the rationale 基本原理 for Herbert's emphasis on the social and political realities that Impressionist 印象派 paintings can be said to communicate rather than on their style is finally undermined by what even Herbert concedes 承认 was the failure of Impressionist painters to serve as particularly conscientious 尽责的 illustrators of their social milieu 社会环境.

====

- 312. Because his work concentrates on the nineteenth century, McLaughlin unfortunately overlooks earlier sources of influence, such as eighteen-century White resident traders and neighbors, thus obscuring the relative impact of the missionaries of the 1820s in contributing to both acculturalization and resistance to it among the Cherokee.

[.my1]
.案例
====
- 312. Because his work concentrates on 专注于 the nineteenth century, McLaughlin unfortunately overlooks earlier sources of influence, such as eighteenth-century White resident traders and neighbors, thus obscuring 掩盖 the relative impact of the missionaries of the 1820s in contributing to both acculturalization 文化适应 and resistance to it among the Cherokee.

====

- 313. Although iridium is extremely rare on the Earth's surface, the lower regions of the Earth's mantle have roughly the same composition as meteorites and contain large amounts of iridium, which in the case of a diapir eruption would probably be emitted as iridium hexafluoride, a gas that would disperse more uniformly in the atmosphere than the iridium-containing matter thrown out from a meteorite impact.

[.my1]
.案例
====
- 313. Although iridium 铱 is extremely rare on the Earth's surface, the lower regions of the Earth's mantle 地幔 have roughly the same composition as meteorites 陨石 and contain large amounts of iridium, which in the case of a diapir eruption 底辟火山喷发 would probably be emitted as iridium hexafluoride 六氟化铱, a gas that would disperse 扩散 more uniformly in the atmosphere than the iridium-containing matter thrown out from a meteorite impact.

====

- 314. 3. One reason is the historical tendency, which has persisted into the twentieth century, to view scientific discovery as resulting from momentary flashes of individual insight rather than from extended periods of cooperative work by individuals with varying levels of knowledge and skill.

[.my1]
.案例
====
- 314. One reason is the historical tendency, which has persisted into the twentieth century, to view scientific discovery as resulting from momentary flashes of individual insight rather than from extended periods of cooperative work by individuals with varying levels of knowledge and skill.

====

- 315. These historians seem to find allies in certain philosophers of science who argue that scientific views are not imposed by reality but are free inventions of creative minds, and that scientific claims are never more than brave conjectures, always subject to inevitable future falsification.

[.my1]
.案例
====
- 315. These historians seem to find allies 盟友 in certain philosophers of science who argue that scientific views are not imposed by reality but are free inventions of creative minds, and that scientific claims are never more than brave conjectures 猜想, always subject to 易受……影响 inevitable future falsification 证伪.

====

- 316. By the middle of eighteenth century, all of these colonies except four were headed by Royal Governors appointed by the King and perceived as bearing a relation to the people of the colony similar to that of the King to the English people.

[.my1]
.案例
====
- 316. By the middle of eighteenth century, all of these colonies except four were headed by Royal Governors appointed by the King and perceived as bearing a relation to the people of the colony similar to that of the King to the English people.

====

- 317. Because his work concentrates on the nineteenth century, McLaughlin unfortunately overlooks earlier sources of influence, such as eighteen-century White resident traders and neighbors, thus obscuring the relative impact of the missionaries of the 1820s in contributing to both acculturalization and resistance to it among the Cherokee.

[.my1]
.案例
====
- 317. Because his work concentrates on 专注于 the nineteenth century, McLaughlin unfortunately overlooks earlier sources of influence, such as eighteenth-century White resident traders and neighbors, thus obscuring 掩盖 the relative impact of the missionaries of the 1820s in contributing to both acculturalization 文化适应 and resistance to it among the Cherokee.

====

- 318. Although iridium is extremely rare on the Earth's surface, the lower regions of the Earth's mantle have roughly the same composition as meteorites and contain large amounts of iridium, which in the case of a diapir eruption would probably be emitted as iridium hexafluoride, a gas that would disperse more uniformly in the atmosphere than the iridium-containing matter thrown out from a meteorite impact.

[.my1]
.案例
====
- 318. Although iridium 铱 is extremely rare on the Earth's surface, the lower regions of the Earth's mantle 地幔 have roughly the same composition as meteorites 陨石 and contain large amounts of iridium, which in the case of a diapir eruption 底辟火山喷发 would probably be emitted as iridium hexafluoride 六氟化铱, a gas that would disperse 扩散 more uniformly in the atmosphere than the iridium-containing matter thrown out from a meteorite impact.

====

- 319. One reason is the historical tendency, which has persisted into the twentieth century, to view scientific discovery as resulting from momentary flashes of individual insight rather than from extended periods of cooperative work by individuals with varying levels of knowledge and skill.

[.my1]
.案例
====
- 319. One reason is the historical tendency, which has persisted into the twentieth century, to view scientific discovery as resulting from momentary flashes of individual insight rather than from extended periods of cooperative work by individuals with varying levels of knowledge and skill.

====

- 320. These historians seem to find allies in certain philosophers of science who argue that scientific views are not imposed by reality but are free inventions of creative minds, and that scientific claims are never more than brave conjectures, always subject to inevitable future falsification.

[.my1]
.案例
====
- 320. These historians seem to find allies 盟友 in certain philosophers of science who argue that scientific views are not imposed by reality but are free inventions of creative minds, and that scientific claims are never more than brave conjectures 猜想, always subject to 易受……影响 inevitable future falsification 证伪.

====

- 321. By the middle of eighteenth century, all of these colonies except four were headed by Royal Governors appointed by the King and perceived as bearing a relation to the people of the colony similar to that of the King to the English people.

[.my1]
.案例
====
- 321. By the middle of eighteenth century, all of these colonies except four were headed by Royal Governors appointed by the King and perceived as bearing a relation to the people of the colony similar to that of the King to the English people.

====

- 322. They posit that biological distinctions between the sexes result in a necessary sexual division of labor in the family and throughout society and that women's procreative labor is currently undervalued by society, to the disadvantage of women.

[.my1]
.案例
====
- 322. They posit 假定 that biological distinctions between the sexes result in a necessary sexual division of labor in the family and throughout society and that women's procreative labor 生育劳动 is currently undervalued 低估 by society, to the disadvantage of women.

====

- 323. His thesis works relatively well when applied to discrimination against Blacks in the United States, but his definition of racial prejudice as “racially-based negative prejudgments against a group generally accepted as a race in any given region of ethnic competition,” can be interpreted as also including hostility toward such ethnic groups as the Chinese in California and the Jews in medieval Europe.

[.my1]
.案例
====
- 323. His thesis works relatively well when applied to discrimination against Blacks in the United States, but his definition of racial prejudice 种族偏见 as “racially-based negative prejudgments against a group generally accepted as a race in any given region of ethnic competition,” can be interpreted as also including hostility toward such ethnic groups as the Chinese in California and the Jews in medieval Europe.

====

- 324. If one begins by examining why ancients refer to Amazons, it becomes clear that ancient Greek descriptions of such societies were meant not so much to represent observed historical fact—real Amazonian societies—but rather to offer “moral lessons” on the supposed outcome of women's rule in their own society.

[.my1]
.案例
====
- 324. If one begins by examining why ancients refer to Amazons, it becomes clear that ancient Greek descriptions of such societies were meant not so much to represent observed historical fact—real Amazonian societies—but rather to offer “moral lessons” on the supposed outcome of women's rule in their own society.

====

- 325. Unless they succeed, the yield gains of the Green Revolution will be largely lost even if the genes in legumes that equip those plants to enter into a symbiosis with nitrogen fixers are identified and isolated, and even if the transfer of those gene complexes, once they are found, becomes possible.

[.my1]
.案例
====
- 325. Unless they succeed, the yield gains of the Green Revolution 绿色革命 will be largely lost even if the genes in legumes 豆科植物 that equip those plants to enter into a symbiosis 共生关系 with nitrogen fixers 固氮生物 are identified and isolated, and even if the transfer of those gene complexes, once they are found, becomes possible.

====

- 326. A critique of Handlin's interpretation of why legal slavery did not appear until the 1660s suggests that assumptions about the relation between slavery and racial prejudice should be reexamined, and that explanations for the different treatment of Black slaves in North and South America should be expanded.

[.my1]
.案例
====
- 326. A critique 批判 of Handlin's interpretation of why legal slavery did not appear until the 1660s suggests that assumptions about the relation between slavery and racial prejudice should be reexamined, and that explanations for the different treatment of Black slaves in North and South America should be expanded.

====

- 327. There have been attempts to explain these taboos in terms of inappropriate social relationships either between those who are involved and those who are not simultaneously involved in the satisfaction of a bodily need, or between those already satiated and those who appear to be shamelessly gorging.

[.my1]
.案例
====
- 327. There have been attempts to explain these taboos 禁忌 in terms of inappropriate social relationships either between those who are involved and those who are not simultaneously involved in the satisfaction of a bodily need, or between those already satiated 饱足的 and those who appear to be shamelessly gorging 狼吞虎咽.

====

- 328. Traditionally, pollination by wind has been viewed as a reproductive process marked by random events in which the vagaries of the wind are compensated for by the generation of vast quantities of pollen, so that the ultimate production of new seeds is assured at the expense of producing much more pollen than is actually used.

[.my1]
.案例
====
- 328. Traditionally, pollination 授粉 by wind has been viewed as a reproductive process marked by random events in which the vagaries 变幻莫测 of the wind are compensated for 补偿 by the generation of vast quantities of pollen 花粉, so that the ultimate production of new seeds is assured at the expense of 以……为代价 producing much more pollen than is actually used.

====

- 329. It was not the change in office technology, but rather the separation of secretarial work, previously seen as an apprenticeship for beginning managers, from administrative work that in the 1880's created a new class of “dead-end” jobs, thenceforth considered “women's work.”

[.my1]
.案例
====
- 329. It was not the change in office technology, but rather the separation of secretarial work, previously seen as an apprenticeship 学徒期 for beginning managers, from administrative work that in the 1880's created a new class of “dead-end” jobs, thenceforth 从那时起 considered “women's work.”

====

- 330. With regard to this last question, we might note in passing that Thompson, while rightly restoring laboring people to the stage of eighteen-century English history, has probably exaggerated the opposition of these people to the inroads of capitalist consumerism in general: for example, laboring people in eighteen-century England readily shifted from home-brewed beer to standardized beer produced by huge, heavily capitalized urban breweries.

[.my1]
.案例
====
- 330. With regard to this last question, we might note in passing 顺便提及 that Thompson, while rightly restoring laboring people to the stage of eighteenth-century English history, has probably exaggerated the opposition of these people to the inroads 侵袭 of capitalist consumerism 资本主义消费主义 in general: for example, laboring people in eighteenth-century England readily shifted from home-brewed beer to standardized beer produced by huge, heavily capitalized urban breweries.

====

- 331. It can be inferred from the passage that a historian who wished to compare crime rates per thousand in a European city in one decade of the fifteenth century with crime rates in another decade of that century would probably be most aided by better information about which of the following?

[.my1]
.案例
====
- 331. It can be inferred from the passage that a historian who wished to compare crime rates per thousand in a European city in one decade of the fifteenth century with crime rates in another decade of that century would probably be most aided by better information about which of the following?

====

- 332. 1. If she defines feminist criticism as objective and scientific—a valid, verifiable, intellectual method that anyone, whether man or woman, can perform—the definition not only precludes the critic-as-artist approach, but may also impede accomplishment of the utilitarian political objectives of those who seek to change the academic establishment and its thinking, especially about sex roles.

[.my1]
.案例
====
- 332. If she defines feminist criticism as objective and scientific—a valid, verifiable 可验证的, intellectual method that anyone, whether man or woman, can perform—the definition not only precludes 排除 the critic-as-artist approach, but may also impede 阻碍 accomplishment of the utilitarian 功利主义的 political objectives of those who seek to change the academic establishment and its thinking, especially about sex roles.

====

- 333. Even the requirement that biomaterials processed from these materials be nontoxic to host tissue can be met by techniques derived from studying the reactions of tissue cultures to biomaterials or from short-term implants.

[.my1]
.案例
====
- 333. Even the requirement that biomaterials 生物材料 processed from these materials be nontoxic to host tissue 宿主组织 can be met by techniques derived from studying the reactions of tissue cultures to biomaterials or from short-term implants 植入物.

====

- 334. 3. This doctrine has broadened the application of the Fourteenth Amendment to other nonracial forms of discrimination, for while some justices have refused to find any legislative classification other than race to be constitutionally disfavored, most have been receptive to arguments that at least some nonracial discriminations, sexual discrimination in particular, are “suspect” and deserve this heightened scrutiny by the courts.

[.my1]
.案例
====
- 334. This doctrine 学说 has broadened the application of the Fourteenth Amendment to other nonracial forms of discrimination, for while some justices have refused to find any legislative classification other than race to be constitutionally disfavored, most have been receptive to 接受 arguments that at least some nonracial discriminations, sexual discrimination in particular, are “suspect” and deserve this heightened scrutiny 严格审查 by the courts.

====

- 335. The isotopic composition of lead often varies from one source of common copper ore to another, with variations exceeding the measurement error; and preliminary studies indicate virtually uniform is isotopic composition of the lead from a single copper-ore source.

[.my1]
.案例
====
- 335. The isotopic composition 同位素组成 of lead often varies from one source of common copper ore 铜矿石 to another, with variations exceeding the measurement error; and preliminary studies indicate virtually uniform isotopic composition of the lead from a single copper-ore source.

====

- 336. It is not known how rare this resemblance is, or whether it is most often seen in inclusions of silicates such as garnet, whose crystallography is generally somewhat similar to that of diamond; but when present, the resemblance is regarded as compelling evidence that the diamonds and inclusions are truly co-genetic.

[.my1]
.案例
====
- 336. It is not known how rare this resemblance is, or whether it is most often seen in inclusions 包裹体 of silicates 硅酸盐 such as garnet 石榴石, whose crystallography 晶体学 is generally somewhat similar to that of diamond; but when present, the resemblance is regarded as compelling evidence 有力证据 that the diamonds and inclusions are truly co-genetic 同成因的.

====

- 337. If she defines feminist criticism as objective and scientific—a valid, verifiable, intellectual method that anyone, whether man or woman, can perform—the definition not only precludes the critic-as-artist approach, but may also impede accomplishment of the utilitarian political objectives of those who seek to change the academic establishment and its thinking, especially about sex roles.

[.my1]
.案例
====
- 337. If she defines feminist criticism as objective and scientific—a valid, verifiable 可验证的, intellectual method that anyone, whether man or woman, can perform—the definition not only precludes 排除 the critic-as-artist approach, but may also impede 阻碍 accomplishment of the utilitarian 功利主义的 political objectives of those who seek to change the academic establishment and its thinking, especially about sex roles.

====

- 338. Even the requirement that biomaterials processed from these materials be nontoxic to host tissue can be met by techniques derived from studying the reactions of tissue cultures to biomaterials or from short-term implants.

[.my1]
.案例
====
- 338. Even the requirement that biomaterials 生物材料 processed from these materials be nontoxic to host tissue 宿主组织 can be met by techniques derived from studying the reactions of tissue cultures to biomaterials or from short-term implants 植入物.

====

- 339. This doctrine has broadened the application of the Fourteenth Amendment to other nonracial forms of discrimination, for while some justices have refused to find any legislative classification other than race to be constitutionally disfavored, most have been receptive to arguments that at least some nonracial discriminations, sexual discrimination in particular, are “suspect” and deserve this heightened scrutiny by the courts.

[.my1]
.案例
====
- 339. This doctrine 学说 has broadened the application of the Fourteenth Amendment to other nonracial forms of discrimination, for while some justices have refused to find any legislative classification other than race to be constitutionally disfavored, most have been receptive to 接受 arguments that at least some nonracial discriminations, sexual discrimination in particular, are “suspect” and deserve this heightened scrutiny 严格审查 by the courts.

====

- 340. The isotopic composition of lead often varies from one source of common copper ore to another, with variations exceeding the measurement error; and preliminary studies indicate virtually uniform is isotopic composition of the lead from a single copper-ore source.

[.my1]
.案例
====
- 340. The isotopic composition 同位素组成 of lead often varies from one source of common copper ore 铜矿石 to another, with variations exceeding the measurement error; and preliminary studies indicate virtually uniform isotopic composition of the lead from a single copper-ore source.

====

- 341. It is not known how rare this resemblance is, or whether it is most often seen in inclusions of silicates such as garnet, whose crystallography is generally somewhat similar to that of diamond; but when present, the resemblance is regarded as compelling evidence that the diamonds and inclusions are truly co-genetic.

[.my1]
.案例
====
- 341. It is not known how rare this resemblance is, or whether it is most often seen in inclusions 包裹体 of silicates 硅酸盐 such as garnet 石榴石, whose crystallography 晶体学 is generally somewhat similar to that of diamond; but when present, the resemblance is regarded as compelling evidence 有力证据 that the diamonds and inclusions are truly co-genetic 同成因的.

====

- 342. Portrayals of the folk of Mecklenburg County, North Carolina, whom he remembers from early childhood, of the jazz musicians and tenement roofs of his Harlem days, of Pittsburgh steelworkers, and his reconstruction of classical Greek myths in the guise of the ancient Black kingdom of Benin, attest to this.

[.my1]
.案例
====
- 342. Portrayals 描绘 of the folk of Mecklenburg County, North Carolina, whom he remembers from early childhood, of the jazz musicians and tenement roofs 公寓屋顶 of his Harlem days, of Pittsburgh steelworkers, and his reconstruction 重构 of classical Greek myths in the guise of 以……形式 the ancient Black kingdom of Benin, attest to 证明 this.

====

- 343. The hydrologic cycle, a major topic in this science, is the complete cycle of phenomena through which water passes, beginning as atmospheric water vapor, passing into liquid and solid form as precipitation, thence along and into the ground surface, and finally again returning to the form of atmospheric water vapor by means of evaporation and transpiration.

[.my1]
.案例
====
- 343. The hydrologic cycle 水文循环, a major topic in this science, is the complete cycle of phenomena through which water passes, beginning as atmospheric water vapor, passing into liquid and solid form as precipitation 降水, thence along and into the ground surface, and finally again returning to the form of atmospheric water vapor by means of evaporation 蒸发 and transpiration 蒸腾作用.

====

- 344. A recent generation of historians of science, far from portraying accepted scientific views as objectively accurate reflections of a natural world, explain the acceptance of such views in terms of the ideological biases of certain influential scientists or the institutional and rhetorical power such scientists wield.

[.my1]
.案例
====
- 344. A recent generation of historians of science, far from portraying accepted scientific views as objectively accurate reflections of a natural world, explain the acceptance of such views in terms of the ideological biases 意识形态偏见 of certain influential scientists or the institutional and rhetorical power such scientists wield 掌握.

====

- 345. Galvanized by the human and monetary cost of those hostilities and showing a new determination to fulfill its proper role, Congress enacted the War Powers Resolution of 1973, a statute designed to ensure that the collective judgment of both Congress and the President would be applied to the involvement of United States troops in foreign conflicts.

[.my1]
.案例
====
- 345. Galvanized by 受……激励 the human and monetary cost of those hostilities 敌对行动 and showing a new determination to fulfill its proper role, Congress enacted 颁布 the War Powers Resolution of 1973, a statute 法规 designed to ensure that the collective judgment of both Congress and the President would be applied to the involvement of United States troops in foreign conflicts.

====

- 346. For example, in Maria Campbell's account of growing up as a Canadian Metis who was influenced strongly, and often negatively, by the non-Native American world around her, one learns a great deal about the life of Native American women, but Campbell's individual story, which is told to us directly, is always the center of her narrative.

[.my1]
.案例
====
- 346. For example, in Maria Campbell's account of growing up as a Canadian Metis who was influenced strongly, and often negatively, by the non-Native American world around her, one learns a great deal about the life of Native American women, but Campbell's individual story, which is told to us directly, is always the center of her narrative 叙述.

====

- 347. In recent years the early music movement, which advocates performing a work as it was performed at the time of its composition, has taken on the character of a crusade, particularly as it has moved beyond the sphere of medieval and baroque music and into music from the late eighteenth and early nineteenth centuries by composers such as Mozart and Beethoven.

[.my1]
.案例
====
- 347. In recent years the early music movement, which advocates performing a work as it was performed at the time of its composition, has taken on the character of a crusade 运动, particularly as it has moved beyond the sphere of medieval and baroque music and into music from the late eighteenth and early nineteenth centuries by composers such as Mozart and Beethoven.

====

- 348. But the answer to why the Johnsons left that area where they had labored so long may lie in their realization that their white neighbors were already beginning the transition from a largely white indentured labor force to reliance on a largely black slave labor force, and that the institution of slavery was threatening their descendants' chances for freedom and success in Virginia.

[.my1]
.案例
====
- 348. But the answer to why the Johnsons left that area where they had labored so long may lie in their realization that their white neighbors were already beginning the transition from a largely white indentured labor force 契约劳动力 to reliance on a largely black slave labor force, and that the institution of slavery was threatening their descendants' chances for freedom and success in Virginia.

====

- 349. This change in sea level might well have been the result of a distortion in the Earth's surface that resulted from the movement of diapirs upward toward the Earth's crust, and the more cataclysmic extinction of the dinosaurs could have resulted from the explosive volcanism that occurred as material from the diapirs erupted onto the Earth's surface.

[.my1]
.案例
====
- 349. This change in sea level might well have been the result of a distortion 扭曲 in the Earth's surface that resulted from the movement of diapirs 底辟向上 toward the Earth's crust 地壳, and the more cataclysmic 大变动的 extinction of the dinosaurs could have resulted from the explosive volcanism 火山活动 that occurred as material from the diapirs erupted onto the Earth's surface.

====

- 350. It is refreshing to read a book about our planet by an author who does not allow facts to be overshadowed by politics: well aware of the political disputes about the effects of human activities on climate and biodiversity, this author does not permit them to eclipse his comprehensive description of what we know about our biosphere.

[.my1]
.案例
====
- 350. It is refreshing to read a book about our planet by an author who does not allow facts to be overshadowed by politics: well aware of the political disputes about the effects of human activities on climate and biodiversity 生物多样性, this author does not permit them to eclipse 掩盖 his comprehensive description of what we know about our biosphere 生物圈.

====


'''

== pure

- 301. But the recent discovery of detailed similarities in the skeletal structure of the flippers in all three groups undermines the attempt to explain away superficial resemblance as due to convergent evolution—the independent development of similarities between unrelated groups in response to similar environmental pressures.

- 302. In addition, the style of some Black novels, like Jean Toomer'sCane, verges on expressionism or surrealism; does this technique provide a counterpoint to the prevalent theme that portrays the fate against which Black heroes are pitted, a theme usually conveyed by more naturalistic modes of expression?

- 303. Studies by Hargrave and Geen estimated natural community grazing rates by measuring feeding rates of individual zooplankton species in the laboratory and then computing community grazing rates for field conditions using the known population density of grazers.

- 304. Historians such as Le Roy Ladurie have used the documents to extract case histories, which have illuminated the attitudes of different social groups (these attitudes include, but are not confined to, attitudes toward crime and the law) and have revealed how the authorities administered justice.

- 305. The idea of an autonomous discipline called “philosophy” distinct from and sitting in judgment on such pursuits as theology and science turns out, on close examination, to be of quite recent origin.

- 306. Yet Walzer's argument, however deficient, does point to one of the most serious weaknesses of capitalism—namely, that it brings to predominant positions in a society people who, no matter how legitimately they have earned their material rewards, often lack those other qualities that evoke affection or admiration.

- 307. More probable is bird transport, either externally, by accidental attachment of the seeds to feathers, or internally, by the swallowing of fruit and subsequent excretion of the seeds.

- 308. Shaw's revolutionary “open-system” view recognizes a continuum between terrestrial and extraterrestrial dynamics, whereas modern plate tectonic theory, like the classical geology developed during the nineteenth century, is founded on the view that Earth's geological features have changed through gradual, regular processes intrinsic to Earth, without reference to unique catastrophic events.

- 309. How explicit and consistent the symbolizing process was intended to be is a much thornier matter, but anyone who has more familiarity than a passing acquaintance with Dutch literature or with the kinds of images used in illustrated books (above all emblem books) will know how much less pervasive was the habit of investing ordinary objects than of investing scenes with meaning that go beyond their surface and outward appearance.

- 310. Japanese automakers chose to make small-lot production feasible by introducing several departures from United States practices, including the use of flexible equipment that could be altered easily to do several different production tasks and the training of workers in multiple jobs.

- 311. Moreover, the rationale for Herbert's emphasis on the social and political realities that Impressionist paintings can be said to communicate rather than on their style is finally undermined by what even Herbert concedes was the failure of Impressionist painters to serve as particularly conscientious illustrators of their social milieu.

- 312. Because his work concentrates on the nineteenth century, McLaughlin unfortunately overlooks earlier sources of influence, such as eighteen-century White resident traders and neighbors, thus obscuring the relative impact of the missionaries of the 1820s in contributing to both acculturalization and resistance to it among the Cherokee.

- 313. Although iridium is extremely rare on the Earth's surface, the lower regions of the Earth's mantle have roughly the same composition as meteorites and contain large amounts of iridium, which in the case of a diapir eruption would probably be emitted as iridium hexafluoride, a gas that would disperse more uniformly in the atmosphere than the iridium-containing matter thrown out from a meteorite impact.

- 314. 3. One reason is the historical tendency, which has persisted into the twentieth century, to view scientific discovery as resulting from momentary flashes of individual insight rather than from extended periods of cooperative work by individuals with varying levels of knowledge and skill.

- 315. These historians seem to find allies in certain philosophers of science who argue that scientific views are not imposed by reality but are free inventions of creative minds, and that scientific claims are never more than brave conjectures, always subject to inevitable future falsification.

- 316. By the middle of eighteenth century, all of these colonies except four were headed by Royal Governors appointed by the King and perceived as bearing a relation to the people of the colony similar to that of the King to the English people.

- 317. Because his work concentrates on the nineteenth century, McLaughlin unfortunately overlooks earlier sources of influence, such as eighteen-century White resident traders and neighbors, thus obscuring the relative impact of the missionaries of the 1820s in contributing to both acculturalization and resistance to it among the Cherokee.

- 318. Although iridium is extremely rare on the Earth's surface, the lower regions of the Earth's mantle have roughly the same composition as meteorites and contain large amounts of iridium, which in the case of a diapir eruption would probably be emitted as iridium hexafluoride, a gas that would disperse more uniformly in the atmosphere than the iridium-containing matter thrown out from a meteorite impact.

- 319. One reason is the historical tendency, which has persisted into the twentieth century, to view scientific discovery as resulting from momentary flashes of individual insight rather than from extended periods of cooperative work by individuals with varying levels of knowledge and skill.

- 320. These historians seem to find allies in certain philosophers of science who argue that scientific views are not imposed by reality but are free inventions of creative minds, and that scientific claims are never more than brave conjectures, always subject to inevitable future falsification.

- 321. By the middle of eighteenth century, all of these colonies except four were headed by Royal Governors appointed by the King and perceived as bearing a relation to the people of the colony similar to that of the King to the English people.

- 322. They posit that biological distinctions between the sexes result in a necessary sexual division of labor in the family and throughout society and that women's procreative labor is currently undervalued by society, to the disadvantage of women.

- 323. His thesis works relatively well when applied to discrimination against Blacks in the United States, but his definition of racial prejudice as “racially-based negative prejudgments against a group generally accepted as a race in any given region of ethnic competition,” can be interpreted as also including hostility toward such ethnic groups as the Chinese in California and the Jews in medieval Europe.

- 324. If one begins by examining why ancients refer to Amazons, it becomes clear that ancient Greek descriptions of such societies were meant not so much to represent observed historical fact—real Amazonian societies—but rather to offer “moral lessons” on the supposed outcome of women's rule in their own society.

- 325. Unless they succeed, the yield gains of the Green Revolution will be largely lost even if the genes in legumes that equip those plants to enter into a symbiosis with nitrogen fixers are identified and isolated, and even if the transfer of those gene complexes, once they are found, becomes possible.

- 326. A critique of Handlin's interpretation of why legal slavery did not appear until the 1660s suggests that assumptions about the relation between slavery and racial prejudice should be reexamined, and that explanations for the different treatment of Black slaves in North and South America should be expanded.

- 327. There have been attempts to explain these taboos in terms of inappropriate social relationships either between those who are involved and those who are not simultaneously involved in the satisfaction of a bodily need, or between those already satiated and those who appear to be shamelessly gorging.

- 328. Traditionally, pollination by wind has been viewed as a reproductive process marked by random events in which the vagaries of the wind are compensated for by the generation of vast quantities of pollen, so that the ultimate production of new seeds is assured at the expense of producing much more pollen than is actually used.

- 329. It was not the change in office technology, but rather the separation of secretarial work, previously seen as an apprenticeship for beginning managers, from administrative work that in the 1880's created a new class of “dead-end” jobs, thenceforth considered “women's work.”

- 330. With regard to this last question, we might note in passing that Thompson, while rightly restoring laboring people to the stage of eighteen-century English history, has probably exaggerated the opposition of these people to the inroads of capitalist consumerism in general: for example, laboring people in eighteen-century England readily shifted from home-brewed beer to standardized beer produced by huge, heavily capitalized urban breweries.

- 331. It can be inferred from the passage that a historian who wished to compare crime rates per thousand in a European city in one decade of the fifteenth century with crime rates in another decade of that century would probably be most aided by better information about which of the following?

- 332. 1. If she defines feminist criticism as objective and scientific—a valid, verifiable, intellectual method that anyone, whether man or woman, can perform—the definition not only precludes the critic-as-artist approach, but may also impede accomplishment of the utilitarian political objectives of those who seek to change the academic establishment and its thinking, especially about sex roles.

- 333. Even the requirement that biomaterials processed from these materials be nontoxic to host tissue can be met by techniques derived from studying the reactions of tissue cultures to biomaterials or from short-term implants.

- 334. 3. This doctrine has broadened the application of the Fourteenth Amendment to other nonracial forms of discrimination, for while some justices have refused to find any legislative classification other than race to be constitutionally disfavored, most have been receptive to arguments that at least some nonracial discriminations, sexual discrimination in particular, are “suspect” and deserve this heightened scrutiny by the courts.

- 335. The isotopic composition of lead often varies from one source of common copper ore to another, with variations exceeding the measurement error; and preliminary studies indicate virtually uniform is isotopic composition of the lead from a single copper-ore source.

- 336. It is not known how rare this resemblance is, or whether it is most often seen in inclusions of silicates such as garnet, whose crystallography is generally somewhat similar to that of diamond; but when present, the resemblance is regarded as compelling evidence that the diamonds and inclusions are truly co-genetic.

- 337. If she defines feminist criticism as objective and scientific—a valid, verifiable, intellectual method that anyone, whether man or woman, can perform—the definition not only precludes the critic-as-artist approach, but may also impede accomplishment of the utilitarian political objectives of those who seek to change the academic establishment and its thinking, especially about sex roles.

- 338. Even the requirement that biomaterials processed from these materials be nontoxic to host tissue can be met by techniques derived from studying the reactions of tissue cultures to biomaterials or from short-term implants.

- 339. This doctrine has broadened the application of the Fourteenth Amendment to other nonracial forms of discrimination, for while some justices have refused to find any legislative classification other than race to be constitutionally disfavored, most have been receptive to arguments that at least some nonracial discriminations, sexual discrimination in particular, are “suspect” and deserve this heightened scrutiny by the courts.

- 340. The isotopic composition of lead often varies from one source of common copper ore to another, with variations exceeding the measurement error; and preliminary studies indicate virtually uniform is isotopic composition of the lead from a single copper-ore source.

- 341. It is not known how rare this resemblance is, or whether it is most often seen in inclusions of silicates such as garnet, whose crystallography is generally somewhat similar to that of diamond; but when present, the resemblance is regarded as compelling evidence that the diamonds and inclusions are truly co-genetic.

- 342. Portrayals of the folk of Mecklenburg County, North Carolina, whom he remembers from early childhood, of the jazz musicians and tenement roofs of his Harlem days, of Pittsburgh steelworkers, and his reconstruction of classical Greek myths in the guise of the ancient Black kingdom of Benin, attest to this.

- 343. The hydrologic cycle, a major topic in this science, is the complete cycle of phenomena through which water passes, beginning as atmospheric water vapor, passing into liquid and solid form as precipitation, thence along and into the ground surface, and finally again returning to the form of atmospheric water vapor by means of evaporation and transpiration.

- 344. A recent generation of historians of science, far from portraying accepted scientific views as objectively accurate reflections of a natural world, explain the acceptance of such views in terms of the ideological biases of certain influential scientists or the institutional and rhetorical power such scientists wield.

- 345. Galvanized by the human and monetary cost of those hostilities and showing a new determination to fulfill its proper role, Congress enacted the War Powers Resolution of 1973, a statute designed to ensure that the collective judgment of both Congress and the President would be applied to the involvement of United States troops in foreign conflicts.

- 346. For example, in Maria Campbell's account of growing up as a Canadian Metis who was influenced strongly, and often negatively, by the non-Native American world around her, one learns a great deal about the life of Native American women, but Campbell's individual story, which is told to us directly, is always the center of her narrative.

- 347. In recent years the early music movement, which advocates performing a work as it was performed at the time of its composition, has taken on the character of a crusade, particularly as it has moved beyond the sphere of medieval and baroque music and into music from the late eighteenth and early nineteenth centuries by composers such as Mozart and Beethoven.

- 348. But the answer to why the Johnsons left that area where they had labored so long may lie in their realization that their white neighbors were already beginning the transition from a largely white indentured labor force to reliance on a largely black slave labor force, and that the institution of slavery was threatening their descendants' chances for freedom and success in Virginia.

- 349. This change in sea level might well have been the result of a distortion in the Earth's surface that resulted from the movement of diapirs upward toward the Earth's crust, and the more cataclysmic extinction of the dinosaurs could have resulted from the explosive volcanism that occurred as material from the diapirs erupted onto the Earth's surface.

- 350. It is refreshing to read a book about our planet by an author who does not allow facts to be overshadowed by politics: well aware of the political disputes about the effects of human activities on climate and biodiversity, this author does not permit them to eclipse his comprehensive description of what we know about our biosphere.
