

=  001-050
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../myAdocCss.css

'''

== 释义



- (001.) That sex ratio will be favored which maximizes the number of descendants an individual will have and hence the number of gene copies transmitted.

[.my1]
.案例
====

- (001.) That sex ratio will be favored which maximizes the number of descendants an individual will have and hence the number of gene copies transmitted.

那种能使个体后代数量最大化、从而使基因副本传递数量最大化的性别比例，将会受到青睐。
====

- (002.) Hardy’s weakness derived from his apparent inability to control the comings and goings of these divergent impulses and from his unwillingness to cultivate and sustain the energetic and risky ones.

[.my1]
.案例
====
- (002.) Hardy’s weakness derived from his apparent inability to control the comings and goings of these divergent impulses and from his unwillingness to cultivate and sustain the energetic and risky ones.

哈代的弱点源于他显然无法控制这些不同冲动的来去，也源于他不愿培养和维持那些充满活力且具有风险的冲动。
====

- (003.) Virginia Woolf’s provocative statement about her intentions in writing Mrs. Dalloway has regularly been ignored by the critics, since it highlights an aspect of her literary interests very different from the traditional picture of the “poetic” novelist concerned with examining states of reverie and vision and with following the intricate pathways of individual consciousness.

[.my1]
.案例
====
- (003.) Virginia Woolf’s provocative statement about her intentions in writing Mrs. Dalloway has regularly been ignored by the critics, since it highlights an aspect of her literary interests very different from the traditional picture of the “poetic” novelist concerned with examining states of reverie and vision and with following the intricate pathways of individual consciousness.

弗吉尼亚·伍尔夫关于她创作《达洛维夫人》意图的挑衅性陈述，一直被评论家们忽视，因为它凸显了她文学兴趣的一个方面，而这个方面与传统上“诗意”小说家（关注审视梦幻与幻象状态并追随个体意识复杂路径的作家）的形象大相径庭。
====

- (004.) As she put it in The Common Reader, “It is safe to say that not a single law has been framed or one stone set upon another because of anything Chaucer said or wrote; and yet, as we read him, we are absorbing morality at every pore.”

[.my1]
.案例
====
- (004.) As she put it in The Common Reader, “It is safe to say that not a single law has been framed or one stone set upon another because of anything Chaucer said or wrote; and yet, as we read him, we are absorbing morality at every pore.”

正如她在《普通读者》中所说：“可以肯定地说，没有哪一条法律的制定，也没有哪一块砖石的堆砌，是由于乔叟所言所写；然而，当我们阅读他时，我们正全身心地汲取着道德。”
====

- (005.) With the conclusion of a burst of activity, the lactic acid level is high in the body fluids, leaving the large animal vulnerable to attack until the acid is reconverted, via oxidative metabolism, by the liver into glucose, which is then sent (in part) back to the muscles for glycogen resynthesis.

[.my1]
.案例
====
- (005.) With the conclusion of a burst of activity, the lactic acid level is high in the body fluids, leaving the large animal vulnerable to attack until the acid is reconverted, via oxidative metabolism, by the liver into glucose, which is then sent (in part) back to the muscles for glycogen resynthesis.

随着一阵活动的结束，体液中的乳酸水平升高，这使得大型动物容易受到攻击，直到乳酸通过氧化代谢被肝脏转化回葡萄糖，然后（部分）葡萄糖被送回肌肉用于糖原再合成。
====

- (006.) Although Gutman admits that forced separation by sale was frequent, he shows that the slaves’ preference, revealed most clearly on plantations where sale was infrequent, was very much for stable monogamy.

[.my1]
.案例
====
- (006.) Although Gutman admits that forced separation by sale was frequent, he shows that the slaves’ preference, revealed most clearly on plantations where sale was infrequent, was very much for stable monogamy.

尽管古特曼承认通过买卖强制分离的现象很常见，但他表明，奴隶们（尤其是在买卖不频繁的种植园中表现最清楚的）非常偏好稳定的 monogamy。
====

- (007.) Gutman argues convincingly that the stability of Black family encouraged the transmission of--and so was crucial in sustaining--the Black heritage of folklore, music, and religious expression from one generation to another, a heritage that slaves were continually fashioning out of their African and American experiences.

[.my1]
.案例
====
- (007.) Gutman argues convincingly that the stability of the Black family encouraged the transmission of--and so was crucial in sustaining--the Black heritage of folklore, music, and religious expression from one generation to another, a heritage that slaves were continually fashioning out of their African and American experiences.

古特曼令人信服地论证道，黑人家庭的稳定促进了黑人民间传说、音乐和宗教表达等遗产的传承——因此在维持这些遗产方面至关重要——而这些遗产是奴隶们根据其非洲和美洲的经历不断塑造而成的。
====

- (008.) This preference for exogamy, Gutman suggests, may have derived from West African rules governing marriage, which, though they differed from one tribal group to another, all involved some kind of prohibition against unions with close kin.

[.my1]
.案例
====
- (008.) This preference for exogamy, Gutman suggests, may have derived from West African rules governing marriage, which, though they differed from one tribal group to another, all involved some kind of prohibition against unions with close kin.

古特曼认为，这种对外婚制的偏好可能源于西非的婚姻规则，这些规则尽管因部落群体而异，但都包含某种禁止与近亲结合的规定。
====

- (009.) His thesis works relatively well when applied to discrimination against Blacks in the United States, but his definition of racial prejudice as “racially-based negative prejudgments against a group generally accepted as a race in any given region of ethnic competition,” can be interpreted as also including hostility toward such ethnic groups as the Chinese in California and the Jews in medieval Europe.

[.my1]
.案例
====
- (009.) His thesis works relatively well when applied to discrimination against Blacks in the United States, but his definition of racial prejudice as “racially-based negative prejudgments against a group generally accepted as a race in any given region of ethnic competition,” can be interpreted as also including hostility toward such ethnic groups as the Chinese in California and the Jews in medieval Europe.

他的论点应用于美国对黑人的歧视时相对有效，但他将种族偏见定义为“在任何特定民族竞争区域，基于种族对某个普遍被接受为种族的群体所作的负面预判”，这也可以被解读为包括对加州的华人以及中世纪欧洲的犹太人等族裔群体的敌意。
====

- (010.) Such variations in size, shape, chemistry, conduction speed, excitation threshold, and the like as had been demonstrated in nerve cells remained negligible in significance for any possible correlation with the manifold dimensions of mental experience.

[.my1]
.案例
====
- (010.) Such variations in size, shape, chemistry, conduction speed, excitation threshold, and the like as had been demonstrated in nerve cells remained negligible in significance for any possible correlation with the manifold dimensions of mental experience.

神经细胞中已显示的尺寸、形状、化学性质、传导速度、兴奋阈值等方面的变异，对于其与心理经验的多重维度之间可能存在的任何关联来说，其重要性仍然微不足道。
====

- (011.) It was possible to demonstrate by other methods refined structural differences among neuron types; however, proof was lacking that the quality of the impulse or its condition was influenced by these differences, which seemed instead to influence the developmental patterning of the neural circuits.

[.my1]
.案例
====
- (011.) It was possible to demonstrate by other methods refined structural differences among neuron types; however, proof was lacking that the quality of the impulse or its condition was influenced by these differences, which seemed instead to influence the developmental patterning of the neural circuits.

通过其他方法，可以证明神经元类型之间存在精微的结构差异；然而，缺乏证据表明脉冲的质量或其状况受到这些差异的影响，这些差异反而似乎影响了神经回路的发育模式。
====

- (012.) Although qualitative variance among nerve energies was never rigidly disproved, the doctrine was generally abandoned in favor of the opposing view, namely, that nerve impulses are essentially homogeneous in quality and are transmitted as “common currency” throughout the nervous system.

[.my1]
.案例
====
- (012.) Although qualitative variance among nerve energies was never rigidly disproved, the doctrine was generally abandoned in favor of the opposing view, namely, that nerve impulses are essentially homogeneous in quality and are transmitted as “common currency” throughout the nervous system.

尽管神经能量之间的质性差异从未被严格驳斥，但这一学说普遍被放弃，转而支持相反的观点，即神经冲动在本质上是同质的，并以“通用货币”的形式在整个神经系统中传递。
====

- (013.) Other experiments revealed slight variations in the size, number, arrangement, and interconnection of the nerve cells, but as far as psychoneural correlations were concerned, the obvious similarities of these sensory fields to each other seemed much more remarkable than any of the minute differences.

[.my1]
.案例
====
- (013.) Other experiments revealed slight variations in the size, number, arrangement, and interconnection of the nerve cells, but as far as psychoneural correlations were concerned, the obvious similarities of these sensory fields to each other seemed much more remarkable than any of the minute differences.

其他实验揭示了神经细胞在大小、数量、排列和相互连接方面的细微差异，但就心理神经关联而言，这些感觉区域彼此之间明显的相似性，似乎比任何微小的差异都更引人注目。
====

- (014.) Although some experiments show that, as an object becomes familiar, its internal representation becomes more holistic and the recognition process correspondingly more parallel, the weight of evidence seems to support the serial hypothesis, at least for objects that are not notably simple and familiar.

[.my1]
.案例
====
- (014.) Although some experiments show that, as an object becomes familiar, its internal representation becomes more holistic and the recognition process correspondingly more parallel, the weight of evidence seems to support the serial hypothesis, at least for objects that are not notably simple and familiar.

尽管一些实验表明，随着一个物体变得熟悉，其内部表征变得更加整体化，识别过程也相应地更加并行，但现有证据似乎支持序列假说，至少对于那些并非特别简单和熟悉的物体而言。
====

- (015.) In large part as a consequence of the feminist movement, historians have focused a great deal of attention in recent years on determining more accurately the status of women in various periods.

[.my1]
.案例
====
- (015.) In large part as a consequence of the feminist movement, historians have focused a great deal of attention in recent years on determining more accurately the status of women in various periods.

很大程度上是由于女权运动的影响，近年来历史学家们投入了大量精力，旨在更准确地确定不同时期女性的地位。
====

- (016.) If one begins by examining why ancient writers refer to Amazons, it becomes clear that ancient Greek descriptions of such societies were meant not so much to represent observed historical fact--real Amazonian societies--but rather to offer “moral lessons” on the supposed outcome of women’s rule in their own society.

[.my1]
.案例
====
- (016.) If one begins by examining why ancient writers refer to Amazons, it becomes clear that ancient Greek descriptions of such societies were meant not so much to represent observed historical fact--real Amazonian societies--but rather to offer “moral lessons” on the supposed outcome of women’s rule in their own society.

如果我们从考察为什么古代作家会提及亚马逊人开始，就会清楚地发现，古希腊对这类社会的描述与其说旨在呈现观察到的历史事实——真实的亚马逊社会——不如说旨在就女性在他们自己社会中统治的所谓结果提供“道德教训”。
====

- (017.) Thus, for instance, it may come as a shock to mathematicians to learn that the Schrodinger equation for the hydrogen atom is not a literally correct description of the atom, but only an approximation to a somewhat more correct equation taking account of spin, magnetic dipole, and relativistic effects; and that this corrected equation is itself only an imperfect approximation to an infinite set of quantum field-theoretical equations.

[.my1]
.案例
====
- (017.) Thus, for instance, it may come as a shock to mathematicians to learn that the Schrodinger equation for the hydrogen atom is not a literally correct description of the atom, but only an approximation to a somewhat more correct equation taking account of spin, magnetic dipole, and relativistic effects; and that this corrected equation is itself only an imperfect approximation to an infinite set of quantum field-theoretical equations.

因此，举例来说，数学家们可能会震惊地得知，氢原子的薛定谔方程并非对原子字面意义上完全正确的描述，而只是一个稍更正确方程的近似，后者考虑了自旋、磁偶极子和相对论效应；而且这个经过修正的方程本身也只是无限量子场论方程组的一个不完美的近似。
====

- (018.) The physicist rightly dreads precise argument, since an argument that is convincing only if it is precise loses all its force if the assumptions on which it is based are slightly changed, whereas an argument that is convincing though imprecise may well be stable under small perturbations of its underlying assumptions.

[.my1]
.案例
====
- (018.) The physicist rightly dreads precise argument, since an argument that is convincing only if it is precise loses all its force if the assumptions on which it is based are slightly changed, whereas an argument that is convincing though imprecise may well be stable under small perturbations of its underlying assumptions.

物理学家理所当然地惧怕精确的论证，因为一个只有在精确时才令人信服的论证，一旦其基于的假设稍有改变便会失去所有力量；而一个尽管不精确但仍具说服力的论证，却很可能在对其基本假设进行微小扰动时保持稳定。
====

- (019.) However, as they gained cohesion, the Bluestockings came to regard themselves as a women’s group and to possess a sense of female solidarity lacking in the salonnieres, who remained isolated from one another by the primacy each held in her own salon.

[.my1]
.案例
====
- (019.) However, as they gained cohesion, the Bluestockings came to regard themselves as a women’s group and to possess a sense of female solidarity lacking in the salonnieres, who remained isolated from one another by the primacy each held in her own salon.

然而，随着她们凝聚力的增强，蓝袜子社的成员们开始将自己视为一个女性团体，并拥有沙龙女主人所缺乏的女性团结意识，而沙龙女主人则因各自在自己沙龙中的主导地位而彼此孤立。
====

- (020.) As my own studies have advanced, I have been increasingly impressed with the functional similarities between insect and vertebrate societies and less so with the structural differences that seem, at first glance, to constitute such an immense gulf between them.

[.my1]
.案例
====
- (020.) As my own studies have advanced, I have been increasingly impressed with the functional similarities between insect and vertebrate societies and less so with the structural differences that seem, at first glance, to constitute such an immense gulf between them.

随着我研究的深入，我越来越被昆虫社会和脊椎动物社会之间的功能相似性所打动，而对那些乍看之下似乎在两者之间构成巨大鸿沟的结构差异则不那么在意了。
====

- (021.) Although fiction assuredly springs from political circumstances, its authors react to those circumstances in ways other than ideological, and talking about novels and stories primarily as instruments of ideology circumvents much of the fictional enterprise.

[.my1]
.案例
====
- (021.) Although fiction assuredly springs from political circumstances, its authors react to those circumstances in ways other than ideological, and talking about novels and stories primarily as instruments of ideology circumvents much of the fictional enterprise.

尽管虚构作品无疑源于政治环境，但其作者对这些环境的反应方式并非意识形态性的，而主要将小说和故事视为意识形态工具来谈论，则规避了虚构事业的大部分。
====

- (022.) Is this a defect, or are the authors working out of, or trying to forge, a different kind of aesthetic?

[.my1]
.案例
====
- (022.) Is this a defect, or are the authors working out of, or trying to forge, a different kind of aesthetic?

这是一种缺陷吗？抑或是作者们正在探索，或试图开创一种不同类型的审美？
====

- (023.) In addition, the style of some Black novels, like Jean Toomer’s Cane, verges on expressionism or surrealism; does this technique provide a counterpoint to the prevalent theme that portrays the fate against which Black heroes are pitted, a theme usually conveyed by more naturalistic modes of expression?

[.my1]
.案例
====
- (023.) In addition, the style of some Black novels, like Jean Toomer’s Cane, verges on expressionism or surrealism; does this technique provide a counterpoint to the prevalent theme that portrays the fate against which Black heroes are pitted, a theme usually conveyed by more naturalistic modes of expression?

此外，一些黑人小说的风格，如让·图默的《甘蔗》，接近表现主义或超现实主义；这种技巧是否为流行主题（该主题描绘了黑人英雄所对抗的命运，通常通过更自然主义的表达方式来传达）提供了一个对位？
====

- (024.) Black Fiction surveys a wide variety of novels, bringing to our attention in the process some fascinating and little-known works like James Weldon Johnson’s Autobiography of an Ex-colored Man.

[.my1]
.案例
====
- (024.) Black Fiction surveys a wide variety of novels, bringing to our attention in the process some fascinating and little-known works like James Weldon Johnson’s Autobiography of an Ex-colored Man.

《黑人小说》考察了各种各样的小说，在此过程中，它向我们介绍了詹姆斯·韦尔登·约翰逊的《一个前有色人种的自传》等一些引人入胜且鲜为人知的作品。
====

- (025.) Although these molecules allow radiation at visible wavelengths, where most of the energy of sunlight is concentrated, to pass through, they absorb some of the longer-wavelength, infrared emissions radiated from the Earth’s surface, radiation that would otherwise be transmitted back into space.

[.my1]
.案例
====
- (025.) Although these molecules allow radiation at visible wavelengths, where most of the energy of sunlight is concentrated, to pass through, they absorb some of the longer-wavelength, infrared emissions radiated from the Earth’s surface, radiation that would otherwise be transmitted back into space.

尽管这些分子允许可见波长的辐射（太阳光大部分能量集中于此）穿过，但它们会吸收一些从地球表面辐射出的长波红外线，而这些辐射原本会返回太空。
====

- (026.) The role those anthropologists ascribe to evolution is not of dictating the details of human behavior but one of imposing constraints--ways of feeling, thinking, and acting that “come naturally” in archetypal situations in any culture.

[.my1]
.案例
====
- (026.) The role those anthropologists ascribe to evolution is not of dictating the details of human behavior but one of imposing constraints--ways of feeling, thinking, and acting that “come naturally” in archetypal situations in any culture.

那些人类学家归因于进化的作用，不是决定人类行为的细节，而是施加限制——即在任何文化的原型情境中，那些“自然而然”产生的感受、思考和行动方式。
====

- (027.) Which of the following most probably provides an appropriate analogy from human morphology for the “details” versus “constraints” distinction made in the passage in relation to human behavior?

[.my1]
.案例
====
- (027.) Which of the following most probably provides an appropriate analogy from human morphology for the “details” versus “constraints” distinction made in the passage in relation to human behavior?

下列哪一项最有可能从人类形态学中，为文中就人类行为所作的“细节”与“限制”区分，提供一个恰当的类比？
====

- (028.) A low number of algal cells in the presence of a high number of grazers suggested, but did not prove, that the grazers had removed most of the algae.

[.my1]
.案例
====
- (028.) A low number of algal cells in the presence of a high number of grazers suggested, but did not prove, that the grazers had removed most of the algae.

藻类细胞数量少而捕食者数量多，这表明但并未证明，捕食者已经清除了大部分藻类。
====

- (029.) Perhaps the fact that many of these first studies considered only algae of a size that could be collected in a net (net phytoplankton), a practice that overlooked the smaller phytoplankton (nannoplankton) that we now know grazers are most likely to feed on, led to a deemphasis of the role of grazers in subsequent research.

[.my1]
.案例
====
- (029.) Perhaps the fact that many of these first studies considered only algae of a size that could be collected in a net (net phytoplankton), a practice that overlooked the smaller phytoplankton (nannoplankton) that we now know grazers are most likely to feed on, led to a deemphasis of the role of grazers in subsequent research.

也许是这样一个事实导致了后续研究中对捕食者作用的低估：许多早期研究只考虑了可以用网收集的藻类（网状浮游植物），这种做法忽略了我们现在知道捕食者最可能捕食的更小的浮游植物（纳米浮游植物）。
====

- (030.) Studies by Hargrave and Geen estimated natural community grazing rates by measuring feeding rates of individual zooplankton species in the laboratory and then computing community grazing rates for field conditions using the known population density of grazers.

[.my1]
.案例
====
- (030.) Studies by Hargrave and Geen estimated natural community grazing rates by measuring feeding rates of individual zooplankton species in the laboratory and then computing community grazing rates for field conditions using the known population density of grazers.

哈格雷夫和吉恩的研究通过测量实验室中单个浮游动物物种的摄食率，然后利用已知的捕食者种群密度计算野外条件下的群落捕食率，从而估算了自然群落的捕食率。
====

- (031.) In the periods of peak zooplankton abundance, that is, in the late spring and in the summer, Haney recorded maximum daily community grazing rates, for nutrient-poor lakes and bog lakes, respectively, of 6.6 percent and 114 percent of daily phytoplankton production.

[.my1]
.案例
====
- (031.) In the periods of peak zooplankton abundance, that is, in the late spring and in the summer, Haney recorded maximum daily community grazing rates, for nutrient-poor lakes and bog lakes, respectively, of 6.6 percent and 114 percent of daily phytoplankton production.

在浮游动物数量达到高峰的时期，即晚春和夏季，哈尼记录的每日最大群落捕食率分别为：对于营养贫乏的湖泊是每日浮游植物产量的6.6%，对于沼泽湖泊则是114%。
====

- (032.) The hydrologic cycle, a major topic in this science, is the complete cycle of phenomena through which water passes, beginning as atmospheric water vapor, passing into liquid and solid form as precipitation, thence along and into the ground surface, and finally again returning to the form of atmospheric water vapor by means of evaporation and transpiration.

[.my1]
.案例
====
- (032.) The hydrologic cycle, a major topic in this science, is the complete cycle of phenomena through which water passes, beginning as atmospheric water vapor, passing into liquid and solid form as precipitation, thence along and into the ground surface, and finally again returning to the form of atmospheric water vapor by means of evaporation and transpiration.

水文循环，作为这门科学的一个主要课题，是水所经历的完整现象循环：它以大气水蒸气的形式开始，通过降水转变为液态和固态，然后沿着地表或渗入地下，最终通过蒸发和蒸腾作用再次回到大气水蒸气的形式。
====

- (033.) Only when a system possesses natural or artificial boundaries that associate the water within it with the hydrologic cycle may the entire system properly be termed hydrogeologic.

[.my1]
.案例
====
- (033.) Only when a system possesses natural or artificial boundaries that associate the water within it with the hydrologic cycle may the entire system properly be termed hydrogeologic.

只有当一个系统拥有自然或人工边界，将其中的水与水文循环联系起来时，整个系统才能被恰当地称为水文地质系统。
====

- (034.) The historian Frederick J. Turner wrote in the 1890’s that the agrarian discontent that had been developing steadily in the United States since about 1870 had been precipitated by the closing of the internal frontier--that is, the depletion of available new land needed for further expansion of the American farming system.

[.my1]
.案例
====
- (034.) The historian Frederick J. Turner wrote in the 1890’s that the agrarian discontent that had been developing steadily in the United States since about 1870 had been precipitated by the closing of the internal frontier--that is, the depletion of available new land needed for further expansion of the American farming system.

历史学家弗雷德里克·J·特纳在19世纪90年代写道，自大约1870年以来在美国稳步发展的农业不满情绪，是由内部边疆的关闭所引发的——即，用于美国农业系统进一步扩张的可利用新土地的枯竭。
====

- (035.) In the early 1950’s, historians who studied preindustrial Europe (which we may define here as Europe in the period from roughly 1300 to 1800) began, for the first time in large numbers, to investigate more of the preindustrial European population than the 2 or 3 percent who comprised the political and social elite: the kings, generals, judges, nobles, bishops, and local magnates who had hitherto usually filled history books.

[.my1]
.案例
====
- (035.) In the early 1950’s, historians who studied preindustrial Europe (which we may define here as Europe in the period from roughly 1300 to 1800) began, for the first time in large numbers, to investigate more of the preindustrial European population than the 2 or 3 percent who comprised the political and social elite: the kings, generals, judges, nobles, bishops, and local magnates who had hitherto usually filled history books.

在20世纪50年代早期，研究前工业化欧洲（我们在此可定义为大约1300年至1800年间的欧洲）的历史学家们，首次大量开始调查前工业化欧洲人口中，除了构成政治和社会精英的2%或3%以外的更多群体：这些精英包括国王、将军、法官、贵族、主教以及迄今为止通常占据历史书籍的地方显贵。
====

- (036.) Historians such as Emmanuel Le Roy Ladurie have used the documents to extract case histories, which have illuminated the attitudes of different social groups (these attitudes include, but are not confined to, attitudes toward crime and the law) and have revealed how the authorities administered justice.

[.my1]
.案例
====
- (036.) Historians such as Emmanuel Le Roy Ladurie have used the documents to extract case histories, which have illuminated the attitudes of different social groups (these attitudes include, but are not confined to, attitudes toward crime and the law) and have revealed how the authorities administered justice.

像伊曼纽尔·勒华·拉杜里这样的历史学家利用这些文献提取了案例史，这些案例史阐明了不同社会群体的态度（这些态度包括但不限于对犯罪和法律的态度），并揭示了当局如何施行司法。
====

- (037.) It can be inferred from the passage that a historian who wished to compare crime rates per thousand in a European city in one decade of the fifteenth century with crime rates in another decade of that century would probably be most aided by better information about which of the following?

[.my1]
.案例
====
- (037.) It can be inferred from the passage that a historian who wished to compare crime rates per thousand in a European city in one decade of the fifteenth century with crime rates in another decade of that century would probably be most aided by better information about which of the following?

从文章中可以推断出，一位希望比较15世纪欧洲城市某个十年与该世纪另一个十年的千人犯罪率的历史学家，最有可能通过以下哪一项的更好信息而获得帮助？
====

- (038.) My point is that its central consciousness--its profound understanding of class and gender as shaping influences on people’s lives--owes much to that earlier literary heritage, a heritage that, in general, has not been sufficiently valued by most contemporary literary critics.

[.my1]
.案例
====
- (038.) My point is that its central consciousness--its profound understanding of class and gender as shaping influences on people’s lives--owes much to that earlier literary heritage, a heritage that, in general, has not been sufficiently valued by most contemporary literary critics.

我的观点是，其核心意识——即它对阶级和性别作为塑造人们生活的影响因素的深刻理解——很大程度上归功于早期的文学遗产，而这份遗产总的来说并未得到大多数当代文学评论家的充分重视。
====

- (039.) Even the requirement that biomaterials processed from these materials be nontoxic to host tissue can be met by techniques derived from studying the reaction of tissue cultures to biomaterials or from short-term implants.

[.my1]
.案例
====
- (039.) Even the requirement that biomaterials processed from these materials be nontoxic to host tissue can be met by techniques derived from studying the reaction of tissue cultures to biomaterials or from short-term implants.

即使是要求从这些材料中加工出的生物材料对宿主组织无毒，也可以通过研究组织培养物对生物材料的反应或通过短期植入物获得的技术来满足。
====

- (040.) But achieving necessary matches in physical properties across interfaces between living and non-living matter requires knowledge of which molecules control the bonding of cells to each other--an area that we have not yet explored thoroughly.

[.my1]
.案例
====
- (040.) But achieving necessary matches in physical properties across interfaces between living and non-living matter requires knowledge of which molecules control the bonding of cells to each other--an area that we have not yet explored thoroughly.

但要在生命物质与非生命物质之间的界面上实现物理性质的必要匹配，需要了解是哪些分子控制着细胞间的结合——这是一个我们尚未彻底探索的领域。
====

- (041.) Islamic law is a phenomenon so different from all other forms of law--notwithstanding, of course, a considerable and inevitable number of coincidences with one or other of them as far as subject matter and positive enactment are concerned--that its study is indispensable in order to appreciate adequately the full range of possible legal phenomena.

[.my1]
.案例
====
- (041.) Islamic law is a phenomenon so different from all other forms of law--notwithstanding, of course, a considerable and inevitable number of coincidences with one or other of them as far as subject matter and positive enactment are concerned--that its study is indispensable in order to appreciate adequately the full range of possible legal phenomena.

伊斯兰法是一种与其他所有法律形式如此不同的现象——当然，就其主题和实证立法而言，它与其中一种或另一种法律存在相当多且不可避免的巧合——以至于研究它对于充分理解所有可能的法律现象是不可或缺的。
====

- (042.) Both Jewish law and canon law are more uniform than Islamic law. Though historically there is a discernible break between Jewish law of the sovereign state of ancient Israel and of the Diaspora (the dispersion of Jewish people after the conquest of Israel), the spirit of the legal matter in later parts of the Old Testament is very close to that of the Talmud, one of the primary codifications of Jewish law in the Diaspora.

[.my1]
.案例
====
- (042.) Both Jewish law and canon law are more uniform than Islamic law. Though historically there is a discernible break between Jewish law of the sovereign state of ancient Israel and of the Diaspora (the dispersion of Jewish people after the conquest of Israel), the spirit of the legal matter in later parts of the Old Testament is very close to that of the Talmud, one of the primary codifications of Jewish law in the Diaspora.

犹太法和教会法都比伊斯兰法更统一。尽管从历史上看，在古代以色列主权国家的犹太法律与散居地（犹太人在以色列被征服后的分散）的犹太法律之间存在一个可辨别的断裂，但《旧约》后期部分的法律精神与《塔木德》（散居地犹太法律的主要法典之一）的精神非常接近。
====

- (043.) Islam, on the other hand, represented a radical breakaway from the Arab paganism that preceded it; Islamic law is the result of an examination, from a religious angle, of legal subject matter that was far from uniform, comprising as it did the various components of the laws of pre-Islamic Arabia and numerous legal elements taken over from the non-Arab peoples of the conquered territories.

[.my1]
.案例
====
- (043.) Islam, on the other hand, represented a radical breakaway from the Arab paganism that preceded it; Islamic law is the result of an examination, from a religious angle, of legal subject matter that was far from uniform, comprising as it did the various components of the laws of pre-Islamic Arabia and numerous legal elements taken over from the non-Arab peoples of the conquered territories.

另一方面，伊斯兰教代表着与此前阿拉伯异教的彻底决裂；伊斯兰法律是对远非统一的法律主题进行宗教角度审视的结果，因为它包含前伊斯兰阿拉伯地区的各种法律组成部分，以及从被征服的非阿拉伯民族那里吸纳的众多法律元素。
====

- (044.) One such novel idea is that of inserting into the chromosomes of plants discrete genes that are not a part of the plants’ natural constitution: specifically, the idea of inserting into nonleguminous plants the genes, if they can be identified and isolated, that fit the leguminous plants to be hosts for nitrogen-fixing bacteria. Hence, the intensified research on legumes.

[.my1]
.案例
====
- (044.) One such novel idea is that of inserting into the chromosomes of plants discrete genes that are not a part of the plants’ natural constitution: specifically, the idea of inserting into nonleguminous plants the genes, if they can be identified and isolated, that fit the leguminous plants to be hosts for nitrogen-fixing bacteria. Hence, the intensified research on legumes.

一个这样新颖的构想是，将不属于植物自然构成部分的离散基因插入植物的染色体中：具体而言，就是将那些如果能够识别和分离出来，能使非豆科植物成为固氮细菌宿主的基因，插入到非豆科植物中。因此，对豆科植物的研究也得到了加强。
====

- (045.) It is one of nature’s great ironies that the availability of nitrogen in the soil frequently sets an upper limit on plant growth even though the plants’ leaves are bathed in a sea of nitrogen gas.

[.my1]
.案例
====
- (045.) It is one of nature’s great ironies that the availability of nitrogen in the soil frequently sets an upper limit on plant growth even though the plants’ leaves are bathed in a sea of nitrogen gas.

这是一个自然界中巨大的讽刺：尽管植物的叶子浸浴在氮气海洋中，但土壤中氮的有效性却常常限制了植物的生长。
====

- (046.) Unless they succeed, the yield gains of the Green Revolution will be largely lost even if the genes in legumes that equip those plants to enter into a symbiosis with nitrogen fixers are identified and isolated, and even if the transfer of those gene complexes, once they are found, becomes possible.

[.my1]
.案例
====
- (046.) Unless they succeed, the yield gains of the Green Revolution will be largely lost even if the genes in legumes that equip those plants to enter into a symbiosis with nitrogen fixers are identified and isolated, and even if the transfer of those gene complexes, once they are found, becomes possible.

除非他们成功，否则即使识别并分离出豆科植物中使其能够与固氮生物共生的基因，并且即使一旦发现这些基因复合体，其转移也变得可能，绿色革命的产量增益仍将大半丧失。
====

- (047.) Its subject (to use Maynard Mack’s categories) is “life-as-spectacle,” for readers, diverted by its various incidents, observe its hero Odysseus primarily from without; the tragic Iliad, however, presents “life-as-experience”: readers are asked to identify with the mind of Achilles, whose motivations render him not a particularly likable hero.

[.my1]
.案例
====
- (047.) Its subject (to use Maynard Mack’s categories) is “life-as-spectacle,” for readers, diverted by its various incidents, observe its hero Odysseus primarily from without; the tragic Iliad, however, presents “life-as-experience”: readers are asked to identify with the mind of Achilles, whose motivations render him not a particularly likable hero.

它的主题（借用梅纳德·麦克的分类）是“生活即奇观”，因为读者被其各种事件所吸引，主要从外部观察其英雄奥德修斯；然而，悲剧的《伊利亚特》呈现的是“生活即体验”：读者被要求认同阿喀琉斯的内心，而他的动机使他并非一个特别讨人喜欢的英雄。
====

- (048.) Most striking among the many asymmetries evident in an adult flatfish is eye placement: before maturity one eye migrates, so that in an adult flatfish both eyes are on the same side of the head.

[.my1]
.案例
====
- (048.) Most striking among the many asymmetries evident in an adult flatfish is eye placement: before maturity one eye migrates, so that in an adult flatfish both eyes are on the same side of the head.

成年比目鱼身上众多明显不对称之处中最引人注目的是眼睛的位置：在成熟之前，一只眼睛会发生迁移，因此在成年比目鱼身上，两只眼睛都位于头部的同一侧。
====

- (049.) A critique of the Handlins’ interpretation of why legal slavery did not appear until the 1660s suggests that assumptions about the relation between slavery and racial prejudice should be reexamined, and explanations for the different treatment of Black slaves in North and South America should be expanded.

[.my1]
.案例
====
- (049.) A critique of the Handlins’ interpretation of why legal slavery did not appear until the 1660s suggests that assumptions about the relation between slavery and racial prejudice should be reexamined, and explanations for the different treatment of Black slaves in North and South America should be expanded.

一项对汉德林夫妇关于为何法律奴隶制直到17世纪60年代才出现的解释所作的批判指出，关于奴隶制与种族偏见之间关系的假设应重新审视，并且对北美和南美黑奴不同待遇的解释应予扩展。
====

- (050.) The best evidence for the layered mantle thesis is the well-established fact that volcanic rocks found on oceanic islands, islands believed to result from mantle plumes arising from the lower mantle, are composed of material fundamentally different from that of the midocean ridge system, whose source, most geologists contend, is the upper mantle.

[.my1]
.案例
====
- (050.) The best evidence for the layered mantle thesis is the well-established fact that volcanic rocks found on oceanic islands, islands believed to result from mantle plumes arising from the lower mantle, are composed of material fundamentally different from that of the midocean ridge system, whose source, most geologists contend, is the upper mantle.

地幔分层理论的最佳证据是这样一个公认的事实：在海洋岛屿上发现的火山岩（这些岛屿被认为是地幔柱从下地幔上升形成的），其物质组成与洋中脊系统（大多数地质学家认为其源自上地幔）的物质根本不同。
====


'''

== pure

- (001.) That sex ratio will be favored which maximizes the number of descendants an individual will have and hence the number of gene copies transmitted.

- (002.) Hardy’s weakness derived from his apparent inability to control the comings and goings of these divergent impulses and from his unwillingness to cultivate and sustain the energetic and risky ones.

- (003.) Virginia Woolf’s provocative statement about her intentions in writing Mrs. Dalloway has regularly been ignored by the critics, since it highlights an aspect of her literary interests very different from the traditional picture of the “poetic” novelist concerned with examining states of reverie and vision and with following the intricate pathways of individual consciousness.

- (004.) As she put it in The Common Reader, “It is safe to say that not a single law has been framed or one stone set upon another because of anything Chaucer said or wrote; and yet, as we read him, we are absorbing morality at every pore.”

- (005.) With the conclusion of a burst of activity, the lactic acid level is high in the body fluids, leaving the large animal vulnerable to attack until the acid is reconverted, via oxidative metabolism, by the liver into glucose, which is then sent (in part) back to the muscles for glycogen resynthesis.

- (006.) Although Gutman admits that forced separation by sale was frequent, he shows that the slaves’ preference, revealed most clearly on plantations where sale was infrequent, was very much for stable monogamy.

- (007.) Gutman argues convincingly that the stability of Black family encouraged the transmission of--and so was crucial in sustaining--the Black heritage of folklore, music, and religious expression from one generation to another, a heritage that slaves were continually fashioning out of their African and American experiences.

- (008.) This preference for exogamy, Gutman suggests, may have derived from West African rules governing marriage, which, though they differed from one tribal group to another, all involved some kind of prohibition against unions with close kin.

- (009.) His thesis works relatively well when applied to discrimination against Blacks in the United States, but his definition of racial prejudice as “racially-based negative prejudgments against a group generally accepted as a race in any given region of ethnic competition,” can be interpreted as also including hostility toward such ethnic groups as the Chinese in California and the Jews in medieval Europe.

- (010.) Such variations in size, shape, chemistry, conduction speed, excitation threshold, and the like as had been demonstrated in nerve cells remained negligible in significance for any possible correlation with the manifold dimensions of mental experience.

- (011.) It was possible to demonstrate by other methods refined structural differences among neuron types; however, proof was lacking that the quality of the impulse or its condition was influenced by these differences, which seemed instead to influence the developmental patterning of the neural circuits.

- (012.) Although qualitative variance among nerve energies was never rigidly disproved, the doctrine was generally abandoned in favor of the opposing view, namely, that nerve impulses are essentially homogeneous in quality and are transmitted as “common currency” throughout the nervous system.

- (013.) Other experiments revealed slight variations in the size, number, arrangement, and interconnection of the nerve cells, but as far as psychoneural correlations were concerned, the obvious similarities of these sensory fields to each other seemed much more remarkable than any of the minute differences.

- (014.) Although some experiments show that, as an object becomes familiar, its internal representation becomes more holistic and the recognition process correspondingly more parallel, the weight of evidence seems to support the serial hypothesis, at least for objects that are not notably simple and familiar.

- (015.) In large part as a consequence of the feminist movement, historians have focused a great deal of attention in recent years on determining more accurately the status of women in various periods.

- (016.) If one begins by examining why ancient writers refer to Amazons, it becomes clear that ancient Greek descriptions of such societies were meant not so much to represent observed historical fact--real Amazonian societies--but rather to offer “moral lessons” on the supposed outcome of women’s rule in their own society.

- (017.) Thus, for instance, it may come as a shock to mathematicians to learn that the Schrodinger equation for the hydrogen atom is not a literally correct description of the atom, but only an approximation to a somewhat more correct equation taking account of spin, magnetic dipole, and relativistic effects; and that this corrected equation is itself only an imperfect approximation to an infinite set of quantum field-theoretical equations.

- (018.) The physicist rightly dreads precise argument, since an argument that is convincing only if it is precise loses all its force if the assumptions on which it is based are slightly changed, whereas an argument that is convincing though imprecise may well be stable under small perturbations of its underlying assumptions.

- (019.) However, as they gained cohesion, the Bluestockings came to regard themselves as a women’s group and to possess a sense of female solidarity lacking in the salonnieres, who remained isolated from one another by the primacy each held in her own salon.

- (020.) As my own studies have advanced, I have been increasingly impressed with the functional similarities between insect and vertebrate societies and less so with the structural differences that seem, at first glance, to constitute such an immense gulf between them.

- (021.) Although fiction assuredly springs from political circumstances, its authors react to those circumstances in ways other than ideological, and talking about novels and stories primarily as instruments of ideology circumvents much of the fictional enterprise.

- (022.) Is this a defect, or are the authors working out of, or trying to forge, a different kind of aesthetic?

- (023.) In addition, the style of some Black novels, like Jean Toomer’s Cane, verges on expressionism or surrealism; does this technique provide a counterpoint to the prevalent theme that portrays the fate against which Black heroes are pitted, a theme usually conveyed by more naturalistic modes of expression?

- (024.) Black Fiction surveys a wide variety of novels, bringing to our attention in the process some fascinating and little-known works like James Weldon Johnson’s Autobiography of an Ex-colored Man.

- (025.) Although these molecules allow radiation at visible wavelengths, where most of the energy of sunlight is concentrated, to pass through, they absorb some of the longer-wavelength, infrared emissions radiated from the Earth’s surface, radiation that would otherwise be transmitted back into space.

- (026.) The role those anthropologists ascribe to evolution is not of dictating the details of human behavior but one of imposing constraints--ways of feeling, thinking, and acting that “come naturally” in archetypal situations in any culture.

- (027.) Which of the following most probably provides an appropriate analogy from human morphology for the “details” versus “constraints” distinction made in the passage in relation to human behavior?

- (028.) A low number of algal cells in the presence of a high number of grazers suggested, but did not prove, that the grazers had removed most of the algae.

- (029.) Perhaps the fact that many of these first studies considered only algae of a size that could be collected in a net (net phytoplankton), a practice that overlooked the smaller phytoplankton (nannoplankton) that we now know grazers are most likely to feed on, led to a deemphasis of the role of grazers in subsequent research.

- (030.) Studies by Hargrave and Geen estimated natural community grazing rates by measuring feeding rates of individual zooplankton species in the laboratory and then computing community grazing rates for field conditions using the known population density of grazers.

- (031.) In the periods of peak zooplankton abundance, that is, in the late spring and in the summer, Haney recorded maximum daily community grazing rates, for nutrient-poor lakes and bog lakes, respectively, of 6.6 percent and 114 percent of daily phytoplankton production.

- (032.) The hydrologic cycle, a major topic in this science, is the complete cycle of phenomena through which water passes, beginning as atmospheric water vapor, passing into liquid and solid form as precipitation, thence along and into the ground surface, and finally again returning to the form of atmospheric water vapor by means of evaporation and transpiration.

- (033.) Only when a system possesses natural or artificial boundaries that associate the water within it with the hydrologic cycle may the entire system properly be termed hydrogeologic.

- (034.) The historian Frederick J. Turner wrote in the 1890’s that the agrarian discontent that had been developing steadily in the United States since about 1870 had been precipitated by the closing of the internal frontier--that is, the depletion of available new land needed for further expansion of the American farming system.

- (035.) In the early 1950’s, historians who studied preindustrial Europe (which we may define here as Europe in the period from roughly 1300 to 1800) began, for the first time in large numbers, to investigate more of the preindustrial European population than the 2 or 3 percent who comprised the political and social elite: the kings, generals, judges, nobles, bishops, and local magnates who had hitherto usually filled history books.

- (036.) Historians such as Emmanuel Le Roy Ladurie have used the documents to extract case histories, which have illuminated the attitudes of different social groups (these attitudes include, but are not confined to, attitudes toward crime and the law) and have revealed how the authorities administered justice.

- (037.) It can be inferred from the passage that a historian who wished to compare crime rates per thousand in a European city in one decade of the fifteenth century with crime rates in another decade of that century would probably be most aided by better information about which of the following?

- (038.) My point is that its central consciousness--its profound understanding of class and gender as shaping influences on people’s lives--owes much to that earlier literary heritage, a heritage that, in general, has not been sufficiently valued by most contemporary literary critics.

- (039.) Even the requirement that biomaterials processed from these materials be nontoxic to host tissue can be met by techniques derived from studying the reaction of tissue cultures to biomaterials or from short-term implants.

- (040.) But achieving necessary matches in physical properties across interfaces between living and non-living matter requires knowledge of which molecules control the bonding of cells to each other--an area that we have not yet explored thoroughly.

- (041.) Islamic law is a phenomenon so different from all other forms of law--notwithstanding, of course, a considerable and inevitable number of coincidences with one or other of them as far as subject matter and positive enactment are concerned--that its study is indispensable in order to appreciate adequately the full range of possible legal phenomena.

- (042.) Both Jewish law and canon law are more uniform than Islamic law. Though historically there is a discernible break between Jewish law of the sovereign state of ancient Israel and of the Diaspora (the dispersion of Jewish people after the conquest of Israel), the spirit of the legal matter in later parts of the Old Testament is very close to that of the Talmud, one of the primary codifications of Jewish law in the Diaspora.

- (043.) Islam, on the other hand, represented a radical breakaway from the Arab paganism that preceded it; Islamic law is the result of an examination, from a religious angle, of legal subject matter that was far from uniform, comprising as it did the various components of the laws of pre-Islamic Arabia and numerous legal elements taken over from the non-Arab peoples of the conquered territories.

- (044.) One such novel idea is that of inserting into the chromosomes of plants discrete genes that are not a part of the plants’ natural constitution: specifically, the idea of inserting into nonleguminous plants the genes, if they can be identified and isolated, that fit the leguminous plants to be hosts for nitrogen-fixing bacteria. Hence, the intensified research on legumes.

- (045.) It is one of nature’s great ironies that the availability of nitrogen in the soil frequently sets an upper limit on plant growth even though the plants’ leaves are bathed in a sea of nitrogen gas.

- (046.) Unless they succeed, the yield gains of the Green Revolution will be largely lost even if the genes in legumes that equip those plants to enter into a symbiosis with nitrogen fixers are identified and isolated, and even if the transfer of those gene complexes, once they are found, becomes possible.

- (047.) Its subject (to use Maynard Mack’s categories) is “life-as-spectacle,” for readers, diverted by its various incidents, observe its hero Odysseus primarily from without; the tragic Iliad, however, presents “life-as-experience”: readers are asked to identify with the mind of Achilles, whose motivations render him not a particularly likable hero.

- (048.) Most striking among the many asymmetries evident in an adult flatfish is eye placement: before maturity one eye migrates, so that in an adult flatfish both eyes are on the same side of the head.

- (049.) A critique of the Handlins’ interpretation of why legal slavery did not appear until the 1660s suggests that assumptions about the relation between slavery and racial prejudice should be reexamined, and explanations for the different treatment of Black slaves in North and South America should be expanded.

- (050.) The best evidence for the layered mantle thesis is the well-established fact that volcanic rocks found on oceanic islands, islands believed to result from mantle plumes arising from the lower mantle, are composed of material fundamentally different from that of the midocean ridge system, whose source, most geologists contend, is the upper mantle.

'''


== 带单词翻译的句子


- (001.) That sex ratio 性别比例 will be favored which maximizes 使最大化 the number of descendants 后代；后裔 an individual will have and hence 因此；所以 the number of gene copies 基因拷贝 transmitted 传递；传播. +

- (002.) Hardy’s weakness derived from 源于；来自 his apparent inability to control the comings and goings of these divergent 不同的；相异的 impulses 冲动 and from his unwillingness to cultivate 培养；培育 and sustain 维持；保持 the energetic and risky ones. +

- (003.) Virginia Woolf’s provocative 挑衅的；煽动性的 statement about her intentions in writing *Mrs. Dalloway* has regularly been ignored by the critics, since it highlights 强调；突出 an aspect of her literary interests very different from the traditional picture of the “poetic” novelist concerned with examining states of reverie 幻想；白日梦 and vision and with following the intricate 复杂的；错综复杂的 pathways of individual consciousness 意识. +

- (004.) As she put it in *The Common Reader*, “It is safe to say that not a single law has been framed 制定；拟定 or one stone set upon another because of anything Chaucer said or wrote; and yet, as we read him, we are absorbing morality 道德；伦理 at every pore 毛孔；气孔.” +

- (005.) With the conclusion of a burst of activity, the lactic acid 乳酸 level is high in the body fluids 体液, leaving the large animal vulnerable to 易受……伤害的 attack until the acid is reconverted 再转化, via 经由；通过 oxidative metabolism 氧化代谢, by the liver into glucose 葡萄糖, which is then sent (in part) back to the muscles for glycogen 糖原 resynthesis 再合成. +

- (006.) Although Gutman admits that forced separation 分离；分开 by sale was frequent, he shows that the slaves’ preference, revealed most clearly on plantations 种植园 where sale was infrequent, was very much for stable monogamy 一夫一妻制. +

- (007.) Gutman argues convincingly 有说服力地 that the stability of Black family encouraged the transmission 传播；传递 of--and so was crucial 至关重要的 in sustaining--the Black heritage 遗产；传统 of folklore 民间传说, music, and religious expression 宗教表达 from one generation to another, a heritage that slaves were continually fashioning 塑造；形成 out of their African and American experiences. +

- (008.) This preference for exogamy 异族通婚, Gutman suggests, may have derived from West African rules governing 支配；管理 marriage, which, though they differed from one tribal group 部落群体 to another, all involved some kind of prohibition 禁止；禁令 against unions with close kin 亲属；亲人. +

- (009.) His thesis 论点；论文 works relatively well when applied to discrimination 歧视 against Blacks in the United States, but his definition of racial prejudice 种族偏见 as “racially-based negative prejudgments 预先判断 against a group generally accepted as a race in any given region of ethnic competition 种族竞争,” can be interpreted as also including hostility 敌意；敌视 toward such ethnic groups 族群 as the Chinese in California and the Jews in medieval Europe. +

- (010.) Such variations 变化；差异 in size, shape, chemistry, conduction speed 传导速度, excitation threshold 兴奋阈值, and the like as had been demonstrated in nerve cells remained negligible 微不足道的；可忽略的 in significance for any possible correlation 关联；相关性 with the manifold 多样的；多方面的 dimensions of mental experience. +

- (011.) It was possible to demonstrate by other methods refined 精确的；细微的 structural differences among neuron 神经元 types; however, proof was lacking that the quality of the impulse 脉冲 or its condition was influenced by these differences, which seemed instead to influence the developmental patterning 模式形成 of the neural circuits 神经回路. +

- (012.) Although qualitative variance 质的差异 among nerve energies was never rigidly 严格地；强硬地 disproved 反驳；证明……错误, the doctrine 学说；教义 was generally abandoned in favor of 转而支持 the opposing view, namely 即；也就是, that nerve impulses are essentially homogeneous 同质的；同类的 in quality and are transmitted as “common currency 通用货币” throughout the nervous system 神经系统. +

- (013.) Other experiments revealed slight variations in the size, number, arrangement 排列；布置, and interconnection 相互连接 of the nerve cells, but as far as psychoneural correlations 心理神经关联 were concerned, the obvious similarities of these sensory fields 感觉区域 to each other seemed much more remarkable than any of the minute 微小的；细微的 differences. +

- (014.) Although some experiments show that, as an object becomes familiar, its internal representation 表征；表现 becomes more holistic 整体的 and the recognition process correspondingly 相应地 more parallel 并行的, the weight of evidence seems to support the serial hypothesis 序列假说, at least for objects that are not notably simple and familiar. +

- (015.) In large part as a consequence of 由于；作为……的结果 the feminist movement 女权运动, historians have focused a great deal of attention in recent years on determining more accurately the status 地位；身份 of women in various periods. +

- (016.) If one begins by examining why ancient writers refer to Amazons 亚马逊女战士, it becomes clear that ancient Greek descriptions of such societies were meant not so much to represent observed historical fact--real Amazonian societies--but rather to offer “moral lessons 道德教训” on the supposed outcome 结果；后果 of women’s rule in their own society. +

- (017.) Thus, for instance, it may come as a shock to mathematicians to learn that the Schrodinger equation 薛定谔方程 for the hydrogen atom 氢原子 is not a literally correct description of the atom, but only an approximation 近似值 to a somewhat more correct equation taking account of 考虑到 spin 自旋, magnetic dipole 磁偶极子, and relativistic 相对论的 effects; and that this corrected equation is itself only an imperfect approximation to an infinite set of quantum field-theoretical equations 量子场论方程. +

- (018.) The physicist 物理学家 rightly dreads 惧怕；担心 precise argument, since an argument that is convincing only if it is precise loses all its force if the assumptions 假设；假定 on which it is based are slightly changed, whereas 然而；反之 an argument that is convincing though imprecise may well be stable under small perturbations 扰动；干扰 of its underlying assumptions. +

- (019.) However, as they gained cohesion 凝聚力；团结, the Bluestockings 蓝袜社成员 came to regard themselves as a women’s group and to possess a sense of female solidarity 团结；凝聚力 lacking in the salonnieres 沙龙女主人, who remained isolated from one another by the primacy 首要地位 each held in her own salon 沙龙. +

- (020.) As my own studies have advanced, I have been increasingly impressed with the functional similarities between insect and vertebrate 脊椎动物的 societies and less so with the structural differences that seem, at first glance 乍一看, to constitute 构成；组成 such an immense 巨大的；极大的 gulf 鸿沟 between them. +

- (021.) Although fiction 小说 assuredly 无疑地；确定地 springs from 源于；来自 political circumstances, its authors react to those circumstances in ways other than ideological 意识形态的, and talking about novels and stories primarily as instruments of ideology 意识形态 circumvents 规避；绕过 much of the fictional enterprise 事业；事业体. +

- (022.) Is this a defect 缺陷；缺点, or are the authors working out of, or trying to forge 创造；塑造, a different kind of aesthetic 美学；审美? +

- (023.) In addition, the style of some Black novels, like Jean Toomer’s *Cane*, verges on 接近；近乎 expressionism 表现主义 or surrealism 超现实主义; does this technique provide a counterpoint 对比；衬托 to the prevalent 盛行的；普遍的 theme that portrays the fate against which Black heroes are pitted 使……与……对立, a theme usually conveyed by more naturalistic 自然主义的 modes of expression? +

- (024.) *Black Fiction* surveys 审视；考察 a wide variety of novels, bringing to our attention in the process some fascinating and little-known works like James Weldon Johnson’s *Autobiography of an Ex-colored Man*. +

- (025.) Although these molecules 分子 allow radiation 辐射 at visible wavelengths 波长, where most of the energy of sunlight is concentrated 集中；聚集, to pass through, they absorb 吸收 some of the longer-wavelength, infrared emissions 红外辐射 radiated from the Earth’s surface, radiation that would otherwise be transmitted 传送；传递 back into space. +

- (026.) The role those anthropologists 人类学家 ascribe to 归因于；归属于 evolution is not of dictating 命令；支配 the details of human behavior but one of imposing constraints 施加限制--ways of feeling, thinking, and acting that “come naturally” in archetypal 典型的；原型的 situations in any culture. +

- (027.) Which of the following most probably provides an appropriate analogy 类比；类推 from human morphology 形态学 for the “details” versus “constraints” distinction 区别；差异 made in the passage in relation to human behavior? +

- (028.) A low number of algal 藻类的 cells in the presence of a high number of grazers 食草动物 suggested, but did not prove, that the grazers had removed most of the algae 藻类. +

- (029.) Perhaps the fact that many of these first studies considered only algae of a size that could be collected in a net (net phytoplankton 浮游植物), a practice that overlooked 忽视；忽略 the smaller phytoplankton (nannoplankton 微型浮游生物) that we now know grazers are most likely to feed on, led to a deemphasis 不强调；淡化 of the role of grazers in subsequent 随后的；后来的 research. +

- (030.) Studies by Hargrave and Geen estimated natural community grazing rates 摄食率 by measuring feeding rates of individual zooplankton 浮游动物 species in the laboratory and then computing community grazing rates for field conditions using the known population density 种群密度 of grazers. +

- (031.) In the periods of peak zooplankton abundance 丰度；数量, that is, in the late spring and in the summer, Haney recorded maximum daily community grazing rates, for nutrient-poor lakes 贫营养湖 and bog lakes 沼泽湖, respectively 分别地；各自地, of 6.6 percent and 114 percent of daily phytoplankton production 浮游植物生产力. +

- (032.) The hydrologic cycle 水文循环, a major topic in this science, is the complete cycle of phenomena through which water passes, beginning as atmospheric water vapor 水蒸气, passing into liquid and solid form as precipitation 降水, thence along and into the ground surface, and finally again returning to the form of atmospheric water vapor by means of evaporation 蒸发 and transpiration 蒸腾作用. +

- (033.) Only when a system possesses natural or artificial boundaries 边界；界限 that associate the water within it with the hydrologic cycle may the entire system properly be termed hydrogeologic 水文地质的. +

- (034.) The historian Frederick J. Turner wrote in the 1890’s that the agrarian discontent 农民的不满 that had been developing steadily in the United States since about 1870 had been precipitated by 由……促成 the closing of the internal frontier 内陆边疆--that is, the depletion 耗尽；枯竭 of available new land needed for further expansion of the American farming system. +

- (035.) In the early 1950’s, historians who studied preindustrial 工业化前的 Europe (which we may define here as Europe in the period from roughly 1300 to 1800) began, for the first time in large numbers, to investigate more of the preindustrial European population than the 2 or 3 percent who comprised 组成；构成 the political and social elite 精英：the kings, generals, judges, nobles, bishops, and local magnates 巨头；权贵 who had hitherto 迄今；到目前为止 usually filled history books. +

- (036.) Historians such as Emmanuel Le Roy Ladurie have used the documents to extract 提取；提炼 case histories 个案史, which have illuminated 阐明；揭示 the attitudes of different social groups (these attitudes include, but are not confined to 不限于, attitudes toward crime and the law) and have revealed how the authorities administered justice 执法；司法. +

- (037.) It can be inferred from the passage that a historian who wished to compare crime rates 犯罪率 per thousand in a European city in one decade of the fifteenth century with crime rates in another decade of that century would probably be most aided by better information about which of the following? +

- (038.) My point is that its central consciousness--its profound 深刻的；深远的 understanding of class and gender as shaping influences on people’s lives--owes much to 归功于 that earlier literary heritage 文学遗产, a heritage that, in general, has not been sufficiently valued by most contemporary literary critics. +

- (039.) Even the requirement that biomaterials 生物材料 processed from these materials be nontoxic 无毒的 to host tissue 宿主组织 can be met by techniques derived from studying the reaction of tissue cultures 组织培养 to biomaterials or from short-term implants 植入物. +

- (040.) But achieving necessary matches in physical properties across interfaces 界面 between living and non-living matter requires knowledge of which molecules control the bonding 结合；键合 of cells to each other--an area that we have not yet explored thoroughly 彻底地；全面地. +

- (041.) Islamic law 伊斯兰法 is a phenomenon 现象 so different from all other forms of law--notwithstanding 尽管；虽然, of course, a considerable and inevitable number of coincidences 巧合 with one or other of them as far as subject matter 主题；内容 and positive enactment 制定法 are concerned--that its study is indispensable 必不可少的；必需的 in order to appreciate adequately 充分地 the full range of possible legal phenomena. +

- (042.) Both Jewish law 犹太法 and canon law 教会法 are more uniform 统一的；一致的 than Islamic law. Though historically there is a discernible 可辨别的；可识别的 break between Jewish law of the sovereign 主权的；独立的 state of ancient Israel and of the Diaspora 大流散 (the dispersion 分散；离散 of Jewish people after the conquest of Israel), the spirit of the legal matter in later parts of the *Old Testament*《旧约全书》is very close to that of the *Talmud*《塔木德》, one of the primary codifications 法典编纂 of Jewish law in the Diaspora. +

- (043.) Islam, on the other hand, represented a radical 彻底的；激进的 breakaway from the Arab paganism 阿拉伯异教 that preceded 先于；在……之前 it; Islamic law is the result of an examination, from a religious angle 角度, of legal subject matter that was far from uniform, comprising 包含；包括 as it did the various components of the laws of pre-Islamic Arabia and numerous legal elements taken over from the non-Arab peoples of the conquered territories 被征服的领土. +

- (044.) One such novel 新颖的 idea is that of inserting into the chromosomes 染色体 of plants discrete 离散的；独立的 genes that are not a part of the plants’ natural constitution 构造；组成: specifically, the idea of inserting into nonleguminous 非豆科的 plants the genes, if they can be identified and isolated 分离；提取, that fit the leguminous 豆科的 plants to be hosts for nitrogen-fixing bacteria 固氮细菌. Hence, the intensified 加强的；深入的 research on legumes 豆科植物. +

- (045.) It is one of nature’s great ironies 讽刺；反语 that the availability of nitrogen 氮 in the soil frequently sets an upper limit 上限 on plant growth even though the plants’ leaves are bathed in 沉浸在 a sea of nitrogen gas 氮气. +

- (046.) Unless they succeed, the yield gains 产量增益 of the Green Revolution 绿色革命 will be largely lost even if the genes in legumes that equip those plants to enter into a symbiosis 共生关系 with nitrogen fixers 固氮生物 are identified and isolated, and even if the transfer of those gene complexes 基因复合体, once they are found, becomes possible. +

- (047.) Its subject (to use Maynard Mack’s categories) is “life-as-spectacle 人生如景观,” for readers, diverted by 被……转移注意力 its various incidents 事件, observe its hero Odysseus primarily from without; the tragic *Iliad*《伊利亚特》, however, presents “life-as-experience 人生如经历”: readers are asked to identify with 与……产生共鸣 the mind of Achilles, whose motivations 动机 render 使成为 him not a particularly likable hero. +

- (048.) Most striking among the many asymmetries 不对称现象 evident in an adult flatfish 比目鱼 is eye placement 眼睛位置: before maturity 成熟期 one eye migrates 迁移, so that in an adult flatfish both eyes are on the same side of the head. +

- (049.) A critique 批评；评论 of the Handlins’ interpretation of why legal slavery 合法奴隶制 did not appear until the 1660s suggests that assumptions about the relation between slavery and racial prejudice should be reexamined 重新审视, and explanations for the different treatment of Black slaves in North and South America should be expanded 扩展；扩充. +

- (050.) The best evidence for the layered mantle 地幔分层 thesis 论点；假说 is the well-established fact that volcanic rocks 火山岩 found on oceanic islands 海洋岛屿, islands believed to result from mantle plumes 地幔柱 arising from the lower mantle, are composed of material fundamentally different from that of the midocean ridge system 大洋中脊系统, whose source, most geologists contend 主张；认为, is the upper mantle 上地幔. +


