= 0401
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 401: Giving Warnings and Cautions.
This is English as a Second Language Podcast episode 401. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. You can go there to download a Learning Guide, an 8 to 10 page guide we provide for all our current episodes. It contains all of the vocabulary, definitions, sample sentences, additional definitions not discussed on the audio episode, cultural notes, comprehension checks, and a complete transcript of every word we say on this episode so you can follow along as well.
This episode is called “Giving Warnings and Cautions.” It is a dialogue between Brett and his mom. They’re going to be talking about Brett’s new apartment, and some problems in the apartment. Let’s get started.
[start of dialogue]
Brett: Hi, Mom. Come in. Welcome to my new place. My roommates aren’t here right now or I’d introduce you.
Mom: Hi, dear. This is…uh…nice.
Brett: It is, isn’t it? I know you were a little worried about me moving out and into a house with five roommates. But as you can see, this is a nice place. Let me give you a tour.
Mom: Oh, okay. Isn’t it a little cramped in the house with six people?
Brett: No way! Come on. I’ll show you the rest of the house. Let’s go this way to the kitchen. Watch out for that hole in the floor. I don’t want you to trip. And don’t worry about the “Do Not Cross – Police Line” tape. It’s just a joke.
Mom: This is the kitchen? Why are all of your dishes on the floor? What do you keep in your cupboards?
Brett: Be careful opening them! We’re short on closet space so some of the guys keep their clothes and shoes in them. You never know what you’ll find if you open one. We just have to watch our step when we walk around the kitchen. Come on, I’ll show you the bathroom.
Mom: You only have one bathroom for six people?
Brett: We’re guys so we don’t really need more than one bathroom. I just have to pay attention to when people take showers if I want enough hot water for my own shower. Watch your head!
Mom: Too late for the heads up! Something just fell on my head.
Brett: Oh, it’s nothing. It’s just a little problem with the ceiling.
Mom: Look out! I think the ceiling is falling down! This place is dangerous!
Brett: It’s nothing. Don’t worry. As long as we stay alert, this is a great place to live.
[end of dialogue]
Our dialogue begins with Brett saying, “Hi, Mom. Come in.” His mother probably knocked on the door and he opened the door and said, “Come in” – come into my place. He says, “Welcome to my new place. My roommates aren’t here right now or I’d introduce them.” He means “if my roommates were here, I would introduce you to them, but they’re not.”
Mom says, “Hi, dear. This is…uh…nice.” You can tell Mom doesn’t really like Brett’s new place. Brett says, however not understanding that, “It is, isn’t it?” He thinks it’s nice! “I know you were a little worried about me moving out and into a house with five roommates,” he says. To “move out” means to leave the place where you are living and begin living in a new place. So, if you are living in an apartment and you move out, you take all of your things and you put them in a different apartment or house. So, Brett has moved out from where ever he was living before to this new house with five “roommates,” people who live with you.
Brett says, “Let me give you a tour” – Mom, let me show you the house. Mom says, “Oh, okay. Isn’t it a little cramped in the house with six people?” “Cramped” (cramped) means crowded, without very much space to move around. The word “cramp” has a couple of different meanings in English; take a look at our Learning Guide for some additional explanations.
Brett disagrees with his mother’s question; his mother is saying it’s too small, it’s too crowded; it’s too cramped in the house. Brett says, “No way!” meaning not at all, absolutely not. Then he says, “Come on. I’ll show you the rest of the house. Let’s go this way to the kitchen.” Then he says, “Watch out for that hole in the floor.” If somebody says “watch out for” something, that’s a warning to let people know they may be in danger or there may be something they need to be careful about. A parent may tell their child, “Watch out for the cars when you cross the street” – when you walk across the street, be looking and be careful so that you don’t get hurt.
Brett says to his mom, “Watch out for that hole in the floor.” That, of course, is our first indication that Brett’s house is not very nice. He says to her, “I don’t want you to trip.” As a verb, in this case, “to trip” means to accidentally hit your foot against something so that you fall down or almost fall down. “Trip” has a couple of different meanings, also, in English; take a look at our Learning Guide for some more information on that.
Brett continues, “And don’t worry about the ‘Do Not Cross – Police Line’ tape. It’s a joke.” When there’s a crime, when someone does something illegal, and the police come to where the crime took place – we would call it “the scene of the crime” – they usually have an investigation, and they put a long piece of thin plastic that says “Do Not Cross.” It’s telling people they cannot come into this area. For example, if there’s a murder and they find a body, they would put police tape, this long, thin piece of plastic that says “Do Not Cross” – do not come in. There’s a popular television show on American television called CSI: Crime Scene Investigation, so you may have seen these “Do Not Cross – Police Line” tapes.
Brett says, “It’s just a joke.” Mom says, “This is the kitchen? Why are all your dishes on the floor? What do you keep in your cupboards?” So, Mom walks into the kitchen and sees dishes on the floor, not in the cupboards. The “cupboards” are large wooden boxes that have doors on them, where you can put your dishes inside of or where you can put pans inside of. We call those the “cupboards” (cupboards – one word).
Brett says, “Be careful opening them!” He’s warning his mother to take care when she opens the door of the cupboard; that’s what “be careful” means. Brett says, “We’re short on closet space so some of the guys keep their clothes and shoes in them.” To be “short on” something means to be without something, to be lacking something that you need. So, some of the boys who live with Brett are putting their clothing where the dishes would go in the kitchen, because they are “short on closet space.” A “closet” is a place in your bedroom where you normally put your clothes.
Brett says, “You never know what you’ll find if you open one (if you open one of the cupboards). We just have to watch our step when we walk around the kitchen.” To “watch your step” means to be aware of where you are walking – where you are putting your feet – usually because there’s something dangerous there. So if someone spills some water on the floor, you may say, “Watch your step” – be careful as you walk through here because there’s water on the floor.
Brett then says, “Come on, I’ll show you the bathroom.” Mom says, “You only have one bathroom for six people?” Brett says, “We’re guys (we’re men) so we don’t really need more than one bathroom. I just have to pay attention to when people take showers if I want enough hot water for my own shower.” To “pay attention” means to notice something, to be aware of something. It’s also something you would say to someone when you want them to be aware. A teacher may say to her student, “Pay attention when I am talking to you.” In other words you need to listen carefully, in that case. This is something I could never do in school; the teachers were always saying, “Pay attention McQuillan!”
Brett says, “Watch your head!” This, again, is another warning that you would give someone. We talked about “watch your step” when you have to be careful where you are walking; now Brett says, “Watch your head,” meaning look above to make sure you’re not going to hit your head on something. Mom says, “Too late for the heads up! Something just fell on my head.” A “heads up” means a warning, when you tell someone about something that’s going to happen that they may need to be careful of or pay attention to. Someone may say to you, “I want to give you the heads up (or a heads up) the new project the manager is asking us to work on tomorrow.” They’re giving you a warning; they’re telling you something you need to know so you’re prepared.
Brett says, “Oh, it’s nothing,” meaning what fell on his mother’s head was not anything important. “It’s just a little problem with the ceiling,” he says. The “ceiling” is the top of the room. So Brett is saying, “Well, things are falling from the ceiling, but it’s not a big problem.” His mother then says, “Look out! I think the ceiling is falling down! This place is dangerous!” “Look out” is another way of warning people; we use this when something bad is about happen and the person needs to protect themselves – to get out of the way. For example, if one of your neighbor children – some of the children who live next to you are hitting golf balls and these golf balls are hitting the side of your house, and they might even hit you, the child may say, “Look out!” or, “Look out for that ball!” meaning you have to be careful that you don’t get hit. Of course, if this happens to you, then you take all of the balls and you throw them back at the children – well, that’s what I do!
Mom says, “This place is dangerous” – this place is unsafe, not safe. Brett says, “It’s nothing. Don’t worry,” meaning it’s not a problem. “As long as we stay alert, this is a great place to live.” To be “alert” means to be aware of what is happening around you, to be paying attention. Of course, there are a lot of problems with the house, so if you are not alert you could get hurt.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Brett: Hi, Mom. Come in. Welcome to my new place. My roommates aren’t here right now or I’d introduce you.
Mom: Hi, dear. This is…uh…nice.
Brett: It is, isn’t it? I know you were a little worried about me moving out and into a house with five roommates. But as you can see, this is a nice place. Let me give you a tour.
Mom: Oh, okay. Isn’t it a little cramped in the house with six people?
Brett: No way! Come on. I’ll show you the rest of the house. Let’s go this way to the kitchen. Watch out for that hole in the floor. I don’t want you to trip. And don’t worry about the “Do Not Cross – Police Line” tape. It’s just a joke.
Mom: This is the kitchen? Why are all of your dishes on the floor? What do you keep in your cupboards?
Brett: Be careful opening them! We’re short on closet space so some of the guys keep their clothes and shoes in them. You never know what you’ll find if you open one. We just have to watch our step when we walk around the kitchen. Come on, I’ll show you the bathroom.
Mom: You only have one bathroom for six people?
Brett: We’re guys so we don’t really need more than one bathroom. I just have to pay attention to when people take showers if I want enough hot water for my own shower. Watch your head!
Mom: Too late for the heads up! Something just fell on my head.
Brett: Oh, it’s nothing. It’s just a little problem with the ceiling.
Mom: Look out! I think the ceiling is falling down! This place is dangerous!
Brett: It’s nothing. Don’t worry. As long as we stay alert, this is a great place to live.
[end of dialogue]
The script for this episode was written by someone who is never short on good ideas for scripts, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
to move out – to leave the place where one has been living and begin living in a new place, especially when one leaves one’s parents’ home
* Many Americans move out on their own when they are 18 years old.
cramped – crowded; without very much space to move around
* Their little economy car began to get more and more cramped as their family grew.
watch out for (something) – a warning to let people know that there is a danger and they need to be careful
* Watch out for the cars when you cross the street! They drive too quickly here.
to trip – to accidentally hit one’s foot against something so that one almost falls down
* Carolina didn’t see the step there and she tripped over it.
do not cross – a warning printed on yellow ribbons, put in places where the police do not want people to go to the other side of those yellow ribbons
* After the murder, the apartment’s front door was covered with Do Not Cross tape because no one but the police was allowed to enter.
cupboard – a large wooden box with a door that is hung on a kitchen or bathroom wall to hold things
* In which cupboard do you keep the flour and sugar?
be careful – a warning to let people know that there is a danger and they need to be cautious when doing or not doing something
* Be careful when you open that can of soda because it was moving around a lot in the car and it might explode.
short on (something) – lacking; without enough of something; without as much of something as one needs
* The hikers were short on water, so they decided to limit themselves to one small bottle every two hours.
to watch (one’s) step – to be aware of where one is walking and where one puts one’s feet, usually because there is something dangerous about the area where one is walking
* Watch your step! There are a lot of dogs around here and I don’t want you to get your new shoes dirty.
to pay attention – to notice something; to be attentive to something; to be aware of something
* Do you pay attention to the international news, or just the local news?
watch your head – a warning to let people know that there is a danger and they need to be careful or else they might hit their head on something
* Watch your head! The ceilings are very low here and tall people sometimes hit their head on them.
heads up – a warning; telling someone about something before it happens
* Didn’t anyone give you the heads up about how difficult it can be to work for Beatrix?
look out – a warning to let people know that there is a danger and they need to be careful
* Look out! That dog bites people who get too close to it.
dangerous – unsafe; causing physical harm
* It is dangerous to drive long distances without enough sleep.
alert – aware of what is happening around oneself
* He thinks that drinking coffee every morning makes him more alert at the office.
Comprehension Questions
1. Why do some of the roommates keep their clothes in the kitchen?
a) Because there aren’t enough closets in the house.
b) Because all the cupboards are in the kitchen.
c) Because the kitchen has the best closets.
2. Why is Brett’s Mom worried about the apartment?
a) Because it is too big for six people.
b) Because it is not in good condition.
c) Because it is short on closet space.
Answers at bottom.
What Else Does It Mean?
cramped
The word “cramped,” in this podcast, means crowded, without very much space to move around: “The office became very cramped when the company hired three new employees and didn’t have empty space for them to work in.” When we talk about writing, “cramped” means a style of handwriting that is difficult to read because it is too small or the letters are too close together: “His writing is so cramped that no one can read it.” A “cramp” can also be a painful problem in part of one’s body when a muscle gets very tight and won’t relax: “After wearing high-heeled shoes all day, she had horrible cramps in her feet and couldn’t walk for 10 minutes after taking them off.” Finally, the phrase “to cramp (someone’s) style” means to interfere with someone’s life so that he or she cannot do what he or she would like to do: “George doesn’t want to live with his parents because they cramp his style.”
to trip
In this podcast, the verb “to trip” means to accidentally hit one’s foot against something so that one almost falls down: “Teo’s toys were all over the floor and visitors were tripping on them.” As a noun, a “trip” is usually a visit or a period of time spent traveling: “Did you enjoy your trip to Venice Beach?” A “trip” can also be the experience that one has when using illegal drugs: “They’re addicted to the trip that they get from taking heroin.” The phrase “to be on an ego trip” means that one thinks that he or she is better than other people: “After her song was played on the radio, she went on an ego trip and started thinking that she was the best singer in the world.”
Culture Note
The United States Department of Homeland Security is a part of the U.S. government that was created to protect Americans. It has made an “advisory system” (a way to warn people about dangers) for the country. The advisory system is “color-coded,” meaning that each “threat level” (the strength of the warning) has a different color. There are five colors in the advisory system.
The lowest threat level is green, which means low risk. Homeland Security recommends that Americans have a family “emergency plan” (an idea of what a family will do if there is danger), but when the advisory system is green, there are no “pressing” (important) threats.
The next threat level is blue, which means “guarded” (moderate; medium) risk. When the advisory system is blue, Homeland Security recommends that Americans get their “disaster supplies” (the things that one will need if there is danger) ready and report any “suspicious behavior” (actions that seem wrong or dangerous).
The yellow threat level means “elevated” (higher) risk. At this level, Homeland Security wants Americans to begin using different “routes” (ways of going somewhere) to go between home, school, and work. That way, if one route is closed they can still get home.
An orange threat level means high risk. Homeland Security wants Americans to be extremely careful when there is an orange threat level. At this threat level, there may be more “delays” (things taking longer than they should) at airports and train stations because security is higher.
Finally, the last threat level is red, which means “severe” (extremely strong) risk. This threat level is used when there is a very dangerous problem. Americans are supposed to watch TV and listen to the radio for instructions and be ready to “evacuate” (leave) their homes if necessary.
Comprehension Answers
1 - a
2 - b