= 0406
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 406: Participating in Internet Discussion Groups.
This is English as a Second Language Podcast episode 406. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com and download a Learning Guide for this episode. The Learning Guides contains all of the vocabulary, definitions, sample sentences, additional definitions, comprehension questions, cultural notes, and a complete transcript of everything we say on this episode. All that is on our website with our Learning Guides.
This episode is a conversation between Dale and Jessie talking about something which is very popular, Internet forums, or Internet discussion groups. I’ll talk about some vocabulary that you will commonly find when you are talking about these kinds of Internet groups. Let’s get started.
[start of dialogue]
Dale: I didn’t know you read that forum. What’s your screen name?
Jessie: It’s “jessiegirl,” but I don’t post very often. I like to lurk and follow the different threads, but I prefer to keep a low profile.
Dale: Really? I post all the time. I just put my new web address on my profile, and check this out. It’s my new avatar.
Jessie: That’s cool. I’ve been trying to figure out how to upload a picture for my avatar. Are there instructions in the FAQs?
Dale: I’m not sure, but I can show you how to do it. Have you been following the thread about the presidential campaign?
Jessie: Yeah, I had been...until today.
Dale: Why’s that?
Jessie: I stopped reading when this one guy, “bigman,” started to flame everybody, saying that anyone who didn’t agree with him is an idiot.
Dale: Oh, really?
Jessie: Yeah, he started posting replies, writing in all caps and letting people have it. He quoted people out of context and attacked them. What a jerk!
Dale: Yeah, that guy sounds like a jerk.
Jessie: Hey, what did you say your screen name is?
Dale: Never mind.
[end of dialogue]
Our dialogue begins with Dale saying, “I didn’t know you read that forum. What’s your screen name?” A “forum” is another name for an Internet discussion group, where people write on a website and communicate about a particular topic. Your “screen name” is usually a short name or a combination of letters and numbers that someone uses to identify him or herself. Many people don’t want to use their real names, so they come up with these screen names that they use instead.
Jessie responds by saying, “It’s ‘jessiegirl,’” meaning her screen name is “jessiegirl.” She says, “I don’t post very often.” To “post means to put text, or photographs, or video, or something else on a website. For example, I post to our blog – our ESL Podcast Blog about once a week. You can post a comment to our blog posts whenever you’d like. The word “post” has several different meanings in English; take a look at our Learning Guide for some additional explanations.
Jessie says, “I like to lurk (lurk) and follow different threads.” To “lurk” (lurk) in a forum or a discussion group means that you go to the forum – you go to the website and you read what other people have written but you don’t participate yourself; you don’t post anything – any messages yourself. To lurk, in general, means to be sort of hiding so that no one can see you, but you’re observing. This is a case where we use that verb to mean you read, but you don’t reply – you don’t post. A “thread” (thread) in an Internet forum is a group of messages that are responses to each other; they’re a group of related messages. We can also use this word more generally, for example someone says, “I don’t quite follow the thread of your conversation,” meaning I don’t quite understand the meaning, how different things are connected to each other. “Thread,” as a noun, is what you use in clothing to keep the clothing together – to keep different parts of the clothing together. For example, on a shirt there are sleeves that go over the arms, and those are probably connected or attached to the rest of the shirt using thread. But “thread,” here, means a group of connected messages.
Jessie says that she prefers to keep a low profile. To “keep a low profile” means to act in a way so that other people don’t pay very much attention to you – don’t notice you. I’m going to keep a low profile – I’m going to make sure people don’t interest themselves in me.
Dale says, “Really? I post all the time. I just put my new web address on my profile, and check this out. It’s my new avatar.” So, Dale says he posts a lot; he put his new website – his web address on his profile. A “profile” is a small collection of information about a person, or perhaps a company. In many websites you can see other people’s profiles; you can see what they’ve said about themselves, perhaps their age, where they live, and so forth. An “avatar” (avatar) is a small picture that represents a person on a website, usually something that you create or you select. And so, you’ll see your name and then underneath you’ll see an avatar. Most forums don’t require an avatar, but people like to put pictures of themselves or their cats or other imaginary beings as their avatar. I don’t think I’ve ever used an avatar, but it’s popular among many people on Internet forums.
Jessie says, “That’s cool. I’ve been trying to figure out how to upload a picture for my avatar.” To “upload” means to transfer files from your computer to a website. Jessie says, “Are there instructions in the FAQs (or the frequently asked questions)?” Most websites have an “FAQ,” or frequently asked questions page; it’s a list of the most common questions that people ask about a website or a product that is on the website, and it gives the answers. It’s the first place you look on a website for help if there’s something you don’t understand.
Dale says, “I’m not sure (I’m not sure if there are instructions in the FAQs), but I can show you how to do it. Have you been following the thread about the presidential campaign?” Notice the use of the verb “follow” – to follow the thread. We said earlier that you could use that in a conversation: “I’m not following the threat of your conversation.” We also use it in Internet discussion groups. To “follow a thread” means to be reading all of the messages about a particular topic that are related to each other.
Jessie says, “Yes, I had been (I was following it)...until today.” Dale says, “Why’s that?” meaning what is the reason why. Jessie says, “I stopped reading when this one guy, (with the screen name) ‘bigman,’ started to flame everybody, saying that anyone who didn’t agree with him is an idiot.” This is what I think; of course, it’s what we all think, that we’re right about everything! To “flame” (flame) means to send a message or post a note that is considered rude, impolite, angry. It’s a not very nice thing you say about someone else; often it’s a personal attack on a person. “Flame” has a couple of different meanings in English; take a look at our Learning Guide for some additional explanations.
So, Jessie stopped following this thread because there was someone who was flaming everybody. Dale says, “Oh, really?” Jessie says, “Yeah, he started posting replies, writing in all caps and letting people have it.” A “reply” is a response, an answer to a message. “Caps” (caps) refers to capital letters, what we sometimes call “upper case” letters. Usually you just use caps, or a capital letter to begin a sentence or a name. But if you type in all caps, many people on the Internet think that’s like shouting. Instead of using upper and lower case letters, you use all capital letters – all upper case letters – all caps, it’s considered a little angry or impolite on an Internet forum. “To let people have it” – “to let someone have it” means to show someone that you are angry with him or her, usually by yelling or shouting. “I let him have it” means I shouted at him, I yelled at him, I told him I was angry.
Jessie says this person “quoted people out of context and attacked them. What a jerk!” To “quote” someone means to repeat what someone else has said; that’s very common on Internet forums. “Out of context,” here, means taking information and eliminating, or leaving out the surrounding information, the information that tells you what it really means. So, you take one small thing a person said and you remove it from the comments around it that would make it seems sensible or logical, and you use that quote to attack someone, to imply that they have a different meaning.
Dale says, “Yeah, that guy sounds like a jerk” – a bad guy. Jessie says, “Hey, what did you say your screen name was?” Jessie’s wondering what Dale’s screen name was, and Dale says, “Never mind.” “Never mind” is a phrase used to show that something is not important and should be forgotten. Of course, perhaps Dale is this “bigman,” this person who was flaming other people, and he didn’t want to admit that to his friend Jessie.
I certainly hope you don’t flame anyone on your Internet forums, if you participate in them. I don’t generally participate in Internet forums, but some people really love them and find they are a good way to connect to other people.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Dale: I didn’t know you read that forum. What’s your screen name?
Jessie: It’s “jessiegirl,” but I don’t post very often. I like to lurk and follow the different threads, but I prefer to keep a low profile.
Dale: Really? I post all the time. I just put my new web address on my profile, and check this out. It’s my new avatar.
Jessie: That’s cool. I’ve been trying to figure out how to upload a picture for my avatar. Are there instructions in the FAQs?
Dale: I’m not sure, but I can show you how to do it. Have you been following the thread about the presidential campaign?
Jessie: Yeah, I had been...until today.
Dale: Why’s that?
Jessie: I stopped reading when this one guy, “bigman,” started to flame everybody, saying that anyone who didn’t agree with him is an idiot.
Dale: Oh, really?
Jessie: Yeah, he started posting replies, writing in all caps and letting people have it. He quoted people out of context and attacked them. What a jerk!
Dale: Yeah, that guy sounds like a jerk.
Jessie: Hey, what did you say your screen name is?
Dale: Never mind.
[end of dialogue]
The script for this episode was by Dr. Lucy Tse, who likes to keep a low profile!
From Los Angeles, California, I’m Jeff McQuillan. Thanks for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
forum – a group of people who communicate through writing on a website about a particular topic
* Ilia found a great forum for Albanians living in New York City.
screen name – the short combination of letters and numbers that a person uses as his or her name or identification when writing online
* Her real name is Taisha Mulan, but her screen name is “peace23.”
to post – to put text, a photograph, a video, or something else on a website
* How often do you post videos on this website?
to lurk – to go to a website and read what other people have written, but not participate by writing anything
* About 100 people participate on this website, and we think there are another 60 or so who lurk, reading what’s there but never contributing.
thread – groups of messages that are responses to each other; groups of related messages
* This website has an interesting thread about how to give large dogs a bath.
to keep a low profile – to act in ways so that other people do not pay very much attention to oneself; to try to not be noticed by other people
* For safety, the government tells Americans to keep a low profile when they travel to other countries.
profile – a small collection of information about a person or company, often shown online
* Kyon’s profile shows his name, birthday, where he went to school, where he works, and his personal interests, like golf and reading.
avatar – a small picture that represents a person using a website, created by the user
* Have you ever created an avatar for the websites you go to?
to upload – to transfer files from one’s computer to a website
* Could you please teach me how to upload photos to my webpage?
FAQs – frequently asked questions; a list of the most common questions that people have about a website or product, with answers
* If you can’t find the answer to your question in our FAQs, please call to speak with a customer service representative.
to flame – to send a message that is rude (impolite) or angry to other people on a website
* Many people started flaming Jonathan after he wrote a message saying that only women should cook and clean.
reply – response; an answer to another message; something that one writes after reading another message, commenting on it
* We posted a job ad on the Internet and received more than 75 replies.
caps – capital letters; uppercase letters; letters that are normally used to start sentences and names (ABC, not abc)
* Please write your name in caps so that it will be easier to read.
to let (someone) have it – to show someone that one is angry with him or her; to yell or shout in anger at someone
* When her husband was more than four hours late coming home, she really let him have it.
to quote (someone) – to repeat what someone else has said
* Herbie started his speech by quoting President Theodore Roosevelt: “Do what you can, with what you have, where you are.”
out of context – without the surrounding information; without information about when and where something was said, which might change the meaning
* They took what I said out of context, and it completely changed the meaning.
never mind – a phrase used to show that something is not important and should be forgotten
* - Did you say something?
* - Yes, but never mind. It wasn’t important.
Comprehension Questions
1. Someone who is trying to keep a low profile would:
a) Read message threads.
b) Have a new avatar.
c) Flame other forum users.
2. Which of these things would be in a message thread?
a) Forum.
b) Screen name.
c) FAQs.
Answers at bottom.
What Else Does It Mean?
to post
The verb “to post,” in this podcast, means to put text, a photograph, a video, or something else on a website: “Which websites will you post your vacation photographs on?” Similarly, the verb “to post” means to put a piece of paper on a bulletin board where many people can see it: “She posted a picture of her lost dog and her phone number on the community bulletin board.” The verb “to post” can also mean to send someone to work in another country or in a particular job: “Did you hear that Renee has been posted to work in Sudan?” Or, “We’re posting the new employee to work at the reception desk for a few weeks.” Finally, a “post” is a long, thick piece of wood or metal put into the ground standing up which is used as support for something else: “In front of the store is a post where customers can put their bicycles while they shop.”
to flame
In this podcast, the verb “to flame” means to send a message that is rude (impolite) or angry to other people on a website: “The website owner deletes messages in which people are flaming each other.” Normally the verb “to flame” means to burn or to be on fire: “The big fire was flaming under the night sky.” A “flame” is the orange light and heat that one sees when something is burning: “Be careful not to let your shirt touch the flame, or it might catch on fire.” Finally, an “old flame” is someone that one used to be in love with and/or had a romantic relationship with: “Gabe became jealous when he met his wife’s old flame from high school.”
Culture Note
Participating in an online forum can be fun, interesting, and a good way to meet new people, but there are many “guidelines” (things that one should do) and rules about how to “behave” (act) in a forum.
Most users try to be “respectful” (thinking about other people and not hurting them) of other users, and not post angry, “rude” (impolite), or “insulting” (offensive) messages. Most forums do not allow messages that have “foul language” (bad words), “racist remarks” (negative comments about skin color), or “personal attacks” (saying many bad things about a person).
Forum users are encouraged to make “meaningful” posts, or posts that make sense and are related to the topic of the forum. “Irrelevant” posts (posts that are not related to the topic) are often “deleted” (erased or thrown away). Users should also give their messages meaningful titles, not using general titles like “hello” or “help.” Once a message is written, it has to be posted in the right “section” (part) of the website. And users need to make sure that a similar message hasn’t already been posted “elsewhere” (in another place).
Forum users don’t like it when people write in ALL CAPS, because they think this is the same as shouting. On many forums, “storage space” (space to keep large files) is “limited” (there isn’t as much as people want), so users are told not to send messages with large attachments. Instead, it is standard to provide a link to the file on another website.
Each forum has at least one “moderator.” The moderator reads all the messages posted on the site and deletes the ones that are “inappropriate” (should not be there) and do not follow the rules.
Comprehension Answers
1 - a
2 - b