= 0418
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 418: Getting Bad Service.
This is English as a Second Language Podcast episode 418. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there and download a Learning Guide for this episode that contains all of the vocabulary, definitions, sample sentences, additional definitions, cultural notes, and a complete transcript of this episode.
This episode is called “Getting Bad Service.” It’s a dialogue between two people talking about the bad customer service they received at a coffee house (or a coffee shop) that they went to. Let’s get started.
[start of dialogue]
Buck: I’m never going to that coffee house again!
Star: Why? What happened?
Buck: It’s the third time in a week that I’ve had lousy service. I don’t expect five-star treatment, but I do expect service industry employees to be at least civil.
Star: What happened this time?
Buck: I walked in and went up to the counter to place my order. The woman working there was talking to her friend, another customer. I stood there, clearly needing to be waited on and she couldn’t have cared less.
Star: You mean she didn’t even acknowledge you?
Buck: Are you kidding? She didn’t stop talking for one second. When she finally took a breath, I told her my order. She gave me a dirty look and finally turned around to get my coffee. She practically threw it at me!
Star: Well, maybe she was having a bad day. At least you got your coffee.
Buck: I got a cup of coffee, but not the kind I ordered. When I realized it, I went back to the counter and she was still talking to her friend. I interrupted her and told her that I got the wrong order. She had the chutzpah to try to tell me that I had made a mistake in telling her my order. Not only did she not take responsibility for her mistake, she tried to tell me that it was my fault!
Star: That’s really infuriating. What are you going to do?
Buck: One good thing about her talking with her friend for so long is that I got her name. I’ll be calling the manager to complain.
Star: Aren’t you overreacting?
Buck: No, I’m not. She’s lucky I didn’t pour the coffee over her head!
[end of dialogue]
Our dialogue begins with Buck saying to his friend Star, “I’m never going to that coffee house again!” – that café where they serve coffee. Star says, “Why? What happened?” Buck says, “It’s the third time in a week that I’ve had lousy service.” “Lousy” (lousy) means bad, not very good, poor quality. So, “lousy service” is bad service.
He says, “I didn’t expect five-star treatment, but I do expect service industry employees to at least be civil.” “Five-star treatment” would be very good customer service, service that makes you feel like an important person. So when you go to a restaurant and the waiter is nice to you and gives you good service, helps you, that would be, possibly, five-star treatment. “Service industry” refers to businesses who provide services to other companies or to other people. Hotels and restaurants are both part of the service industry. So, Buck is saying here that he expects people (employees who work in the service industries) to be at least civil or to at least be civil. “Civil” means polite, formal, not necessarily friendly. Someone can be polite to you but not be friendly to you, that’s called being “civil.” The word “civil” has several different meanings in English; take a look at our Learning Guide for some additional explanations.
Star says, “What happened this time?” Buck says, “I walked in and went up to the counter to place my order.” A “counter” in a store or a business is usually a long, flat surface like a table, where the customer stands on one side and the employee stands on the other side. Often if you are going to buy something, you would go up to the counter (or the sales counter) and the employee would take your money or your credit card.
So, Buck goes up to the counter of this coffee shop and the woman working there was talking to her friend, another customer. He says, “I stood there, clearly needing to be waited on and she couldn’t have cared less.” The expression “to be waited on” means that you are helped or served by an employee; to have an employee ask, for example, what you want to buy or how they can help you. Buck says, “I stood there (meaning I stood waiting there) clearly needing to be waited on and she (the employee) couldn’t have cared less.” The expression “I couldn’t have cared less” means to show that something is extremely unimportant (or not important) to you; something is less important than everything else. For example: “I thought my professor would be mad when I arrived at the classroom late, but he couldn’t have cared less,” meaning he didn’t care at all; it wasn’t important to him. You will also hear native speakers say, “I could have cared less,” but they mean “I couldn’t have cared less.” There’s some confusion now and some people say, “I could have cared less,” but the original expression is “I couldn’t have cared less.” That’s what makes sense in this case.
Star says, “You mean she didn’t even acknowledge you?” To “acknowledge” someone means to recognize that someone is there, usually by looking into their eyes and saying “hello,” even if you don’t have time to speak with them. So the employee might look at you and nod her head and smile so that you know that she knows that you are waiting. But apparently, this employee didn’t even acknowledge Buck. Buck says, “Are you kidding? She didn’t stop talking (to her friend) for one second (she kept talking to her). When she finally took a breath, I told her my order.” To “take a breath” (breath) means to stop speaking for a short period of time so that you can breathe in. I need to do this when I am recording the podcast; I need to stop sometimes and take a breath. Here, it means a short amount of time.
So, when she stopped talking for short amount of time Buck told her his “order,” what he wanted to buy. The employee gave him a dirty look. A “dirty look” is when you change your face so that the other person knows you are not happy or you are angry. If you walk into a library and you are talking loudly or laughing, the people working there (the librarians) may give you a dirty look. I do this all the time when I’m in a restaurant and someone starts yelling on their cell phone (their mobile phone) in the table next to me. I turn and I give them a dirty look, because, of course, it’s not polite to have your telephone conversation in someone else’s ear. You should step outside the restaurant and continue your phone call. Well, that’s the way it should work, but this is Los Angeles and it doesn’t work that way very often.
Buck says that the employee gave him “a dirty look and finally turned around to get my coffee. She practically threw it at me!” “Practically,” here, means almost, virtually, nearly. “Practically” can mean in a practical way, but here, when someone says “she practically kicked me,” or, “he practically killed me,” you mean they almost, nearly but not quite. So, when the employee practically threw the coffee at Buck, she didn’t actually throw it but it was something like that.
Star says, “Well, maybe she was having a bad day. At least you got your coffee.” Buck says, “I got a cup of coffee, but not the kind I ordered. When I realized (this mistake), I went back to the counter and she was still talking to her friend. I interrupted her...” that is, I began speaking even though she was still speaking to someone else so that she would stop and listen to me. “I interrupted her and told her that I got the wrong order. She had the chutzpah to try to tell me that I had made a mistake in telling her my order. “Chutzpah,” spelled C-H-U-T-Z-P-A-H, is a Yiddish word meaning courage or confidence to do something that other people probably wouldn’t do, usually because they may be scared to do it. Another word we could use here is “nerve”: “She had the nerve.” Chutzpah can be a good thing; some people, in some circumstances, may make it a bad thing, doing that something that someone else doesn’t want or would not do. So, “She had the chutzpah to say that I made a mistake in telling her my order. Not only did she not take responsibility for her mistake, she tried to tell me it was my fault!” To “take responsibility” for something means to agree that something is your fault, to accept the consequences of your actions: “Yes, I made a mistake.”
Star says to Buck, “That’s really infuriating.” Something that is “infuriating” makes you very angry or mad. Star says, “What are you going to do?” Buck says, “One good thing about her talking with her friend for so long is that I got her name,” meaning I remembered or I figured out – I was able to get this piece of information, namely her name. Buck says, “I’ll be calling the manager to complain.” To say that you are unhappy about something is to “complain.”
Star says, “Aren’t you overreacting?” To “overreact” means to respond to something too strongly, to make something more important than it really is. So, if your waiter forgets to bring French fries with your hamburger, and you start yelling at the waiter and getting on your feet and pounding your fist on the table, that would be “overreacting,” getting too emotional, too excited about something.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Buck: I’m never going to that coffee house again!
Star: Why? What happened?
Buck: It’s the third time in a week that I’ve had lousy service. I don’t expect five-star treatment, but I do expect service industry employees to be at least civil.
Star: What happened this time?
Buck: I walked in and went up to the counter to place my order. The woman working there was talking to her friend, another customer. I stood there, clearly needing to be waited on and she couldn’t have cared less.
Star: You mean she didn’t even acknowledge you?
Buck: Are you kidding? She didn’t stop talking for one second. When she finally took a breath, I told her my order. She gave me a dirty look and finally turned around to get my coffee. She practically threw it at me!
Star: Well, maybe she was having a bad day. At least you got your coffee.
Buck: I got a cup of coffee, but not the kind I ordered. When I realized it, I went back to the counter and she was still talking to her friend. I interrupted her and told her that I got the wrong order. She had the chutzpah to try to tell me that I had made a mistake in telling her my order. Not only did she not take responsibility for her mistake, she tried to tell me that it was my fault!
Star: That’s really infuriating. What are you going to do?
Buck: One good thing about her talking with her friend for so long is that I got her name. I’ll be calling the manager to complain.
Star: Aren’t you overreacting?
Buck: No, I’m not. She’s lucky I didn’t pour the coffee over her head!
[end of dialogue]
The script for this episode was written by someone who never complains, Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. This podcast is copyright 2008.
Glossary
lousy – poor quality; bad; not very good
* That’s a lousy movie. I saw it last week and I’m sure you won’t like it.
five-star treatment – very good customer service that makes one feel like a very important person
* Our hotel is the best in the city, always giving five-star treatment to all our guests.
service industry – the businesses and people who work by providing services to other people
* Hair salons, restaurants, and hotels are all examples of businesses in the service industry.
civil – polite and formal but not friendly
* Even though we don’t like our neighbor, we need to be civil to her.
counter – a long, flat surface like a table where the customer stands on one side and the employee stands on the other side and where things are bought and sold
* Jarrod put the milk and eggs on the counter and waited for the cashier to tell him how much they would cost.
to be waited on – to be served by an employee; to have an employee ask what one wants to buy and bring that thing to oneself
* At the restaurant last night, we were waited on by a young waiter with pink hair.
couldn’t have cared less – a phrase used to show that something is extremely unimportant to oneself, less important than anything else
* I thought the professor would be mad that I was coming late to class, but he couldn’t have cared less.
to acknowledge (someone) – to recognize that someone is there, looking into one’s eyes and/or saying hello, even if one does not have time to speak with or help that person
* The secretary was on the phone when I walked into the office, but he acknowledged me by looking up and smiling.
to take a breath – to stop speaking for a short period of time so that one can breathe in air
* The children are trying to say the long poem without taking a breath.
dirty look – scowl; a way of moving one’s eyes, nose, and mouth to change one’s facial expression and show that one is angry or not pleased about something
* The librarian gave us a dirty look when we were making too much noise in the quiet library.
practically – almost; virtually; nearly
* We practically had to sell everything we owned to have enough money to pay for food last month.
to interrupt – to begin speaking while someone else is speaking; to suddenly stop someone from speaking before he or she is finished
* I’m sorry to interrupt your conversation, but do you know where the bathroom is?
chutzpah – nerve; the courage or confidence to do something that other people probably wouldn’t do, usually because they would be scared to do it
* You showed a lot of chutzpah when you told that man to stop smoking on the bus.
to take responsibility for (something) – to agree that something was one’s own fault and accept the consequences (the things that happen as a result)
* I drove too quickly and now I need to take responsibility for it by paying for the ticket that the police gave me.
infuriating – something that makes one very angry and upset; very annoying
* That woman is so infuriating! I hate listening to her give her opinions.
to complain – to say that one is unhappy about something and wants it to be changed
* The new camera we bought on the Internet didn’t work, so we called the store to complain.
to overreact – to react to something too strongly; to act like something is more important than it really is
* When Chrissy got 70% on her math test, her parents overreacted, telling her that she couldn’t go out with her friends for four months and making her study math for two hours every afternoon.
Comprehension Questions
1. Which of these is an example of lousy service?
a) Giving the customer five-star treatment.
b) Acknowledging the customer.
c) Giving the customer a dirty look.
2. Why does Buck want to call the manager?
a) To tell him about the woman’s chutzpah.
b) To tell him that he was unhappy with the service.
c) To take responsibility for his mistake.
Answers at bottom.
What Else Does It Mean?
civil
The word “civil,” in this podcast, means polite and formal but not friendly: “Those two girls are always civil toward each other, but they never spend time together as friends.” A“civil ceremony” is a marriage ceremony that doesn’t happen in a church: “Did you get married in the church or did you have a civil ceremony?” A “civil servant” is a person who works in the government: “He has been a civil servant at the U.S. State Department for more than 30 years.” A “civil engineer” is a person who makes plans for building roads and bridges: “How many civil engineers are working on that bridge project?”
counter
In this podcast, the word “counter” means a long, flat surface like a table where the customer stands on one side and the employee stands on the other side and where things are bought and sold: “There was a long line of people waiting in front of the counter at the bank.” A “counter” is also a long, flat surface in a kitchen or bathroom: “Please clean the kitchen counter after you finish washing the dishes.” A “bean counter” is an informal and impolite name for an accountant, or a person who records how much money is received and spent by a company: “He’s a bean counter, so he spends all day working with numbers.” Finally, on a website a “counter” is something that counts how many people come to a website: “According to the counter, more than one million people have visited this website.”
Culture Note
Americans expect good “customer service” (the way that customers are treated by a company’s employees). When they do not get good customer service, they often complain to the manager, who “addresses” (responds to) their complaint. Usually the manager “apologizes” (says that he or she is sorry) and sometimes offers to give the customer something for free to make sure that there are “no hard feelings,” making sure that the customer won’t continue to be angry and tell his or her friends about the bad customer service.
In the United States, people who eat at a restaurant are expected to leave a “tip,” or extra money for the person who waited on them. A normal tip is 15%. If the waiter or waitress does a very good job, then customers might leave a 20% tip. But if the customer service is bad, the customer might leave a much smaller tip or no tip at all.
When people receive extremely bad service, or when they think that a business is using “deceptive” (not truthful) “practices” (ways of doing business), they might “file” (make; register) a complaint with the Better Business Bureau (BBB). This is a U.S. organization that records complaints about many different businesses and organizations and then shares that information with other people. If you want to know whether a business is good, you can get a “report” (a written document with information about something) from the BBB to learn about other people’s experiences while they were customers of that company.
Most companies want to provide “exceptional” (very good) customer service, because they know that people who are happy with a company often give “referrals” (recommendations) to their friends and family members. Companies want those people to become their customers, too.
Comprehension Answers
1 - c
2 - b