= 0444
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 444: Planning for Retirement.
This is English as a Second Language Podcast episode 444. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode to help you improve your English even faster.
This episode is called “Planning for Retirement.” It’s a dialogue between Paulina and Carlos, and it uses some vocabulary that is common in the United States when talking about paying for your retirement years. Let’s get started.
[start of dialogue]
Paulina: Did you get your social security statement? I just got mine in the mail. If I keep working at this rate for the next 20 years, between Social Security and my savings, I should be sitting pretty for retirement.
Carlos: Yeah, I should be okay when I retire, too. I’ve been contributing to a 401(k) through my work for years, and my company gives a matching contribution.
Paulina: Really? I never bothered with a 401(k).
Carlos: A 401(k) really adds up over time. I also have an IRA, which is tax-deferred, and I have my money in a portfolio that is split between stocks and bonds. All of these investments are for the long haul, of course. How about you? What’s your retirement plan?
Paulina: I have money stashed away in a nice little nest egg.
Carlos: Where do you have your money invested?
Paulina: It’s safe and sound, don’t you worry.
Carlos: [Laughs] You make it sound like you have it stashed under your mattress.
Paulina: A mattress is a very safe place for your money!
[end of dialogue]
Our dialogue begins with Paulina asking Carlos, “Did you get your Social Security statement?” “Social Security” is a U.S. government program that allows you to get money after you stop working, when you retire. You pay taxes every year when you work, and those taxes are given back to you when you stop working. A Social Security statement is a piece of paper the government sends you every year that tells you how much money you have spent, or rather, how much money you have paid the government – the government is the one that spends the money! Paulina says, “I just got (or received) mine in the mail. If I keep working at this rate for the next 20 years, between Social Security and my savings, I should be sitting pretty for retirement.” Paulina says, “If I keep working at this rate (“at this rate” means at this pace, working the same number of hours each week) for the next 20 years.” She says, “between Social Security and my savings.” The word “between” normally means in the middle of two things, but here the use is a little bit different. It means together, combined, both. So she’s saying if I take both my Social Security money and my savings (the money that she put in a bank and saved) she should be sitting pretty for retirement. To be “sitting pretty” means to be in a good situation, a good position. You don’t have any problems or worries, especially financially. “Retirement” is the period of time after you stop working. In the United States, it’s usually at age 62 or 65.
Carlos says, “Yeah (yes), I should be okay when I retire, too. I’ve been contributing (I’ve been putting money in) to a 401(k).” A “401(k)” is a special type of U.S. retirement account that the employer (the person who you work for, or the company you work for) gives money to the workers for their retirement. The workers also give money, or put money into the 401(k). In some companies, the worker is the only one that puts money into the 401(k), but in some companies – in most companies both the company and the employee (the person working at the company) “contribute,” or put money into this account, and you invest that money. You put it in stocks or other financial “instruments,” as they’re called – other financial investments, and you hope you will have more money when you retire. 401(k)s are usually accounts that you don’t have to pay taxes on when you put the money in. You have to pay taxes, typically, when you take the money out when you retire.
So, Carlos has a 401(k); he says, “my company gives me a matching contribution.” A “matching contribution” is what the company gives or puts into your retirement account. “Matching” means usually they put in the same amount as you do. “Contribution” just means what you give to someone or something.
Paulina says, “Really? I never bothered with a 401(k).” “I never bothered” means I have never done that, it seemed like too much trouble so I never did it.
Carlos says, “A 401(k) really adds up over time.” To “add up,” here, means to accumulate, to get more and more, to total. “Add up” has a couple of different meanings in English; take a look at the Learning Guide for some additional explanation. Here, it’s a two-word phrasal verb meaning to accumulate, to grow. Carlos says, “I also have an IRA.” “IRA” stands for (or means) individual retirement account. This is another special account – retirement account that you can have in the United States. It is also one that you don’t have to pay taxes on when you put the money into your IRA account. Carlos says that his IRA is tax-deferred. To “defer” means to do something later, at a later time. So, “tax-deferred” means you don’t pay taxes now, but you’ll pay it later. You’ll pay the government taxes on the money when you take the money out after you retire.
Carlos says that he has his money in a portfolio that is split between stocks and bonds. A “portfolio” is a word that describes all of your investments, especially stocks and bonds. “Stocks” are partial ownership that you have in a company. They are sold in something called “shares.” You buy shares in a company, that means you’re buying a certain small percentage of the company. You own part of the company when you buy stock. A “bond” (bond) is an agreement where the company or a government borrows money from you and agrees to pay you back with interest at a future date. “Bond” has a couple of different meanings in English; take a look at the Learning Guide, again, for some additional explanations.
Carlos says that his portfolio is split between stocks and bonds. “Split,” here, just means divided, when you have more than one part of something. Carlos says that all of these investments are for the long haul, of course. The “long haul” (haul) means for the long-term, over the long period of time, not immediately. If someone says, “We’re here for the long haul,” they mean we are here for a long time, we’re not going to worry about what happens in the next year or two years; we are worried about or we are concerned about only what happens after many years. Another word for “long haul” is “long run.” The economist John Maynard Keynes once said, “In the long run, we’re all dead,” meaning if you worry too much about only what happens after many years, you may not be alive!
Carlos says that he has his investments, and they are for the long haul. Then he asks Paulina, “How about you? What’s your retirement plan?” Paulina says, “I have my money stashed away in a nice little nest egg.” To “stash (stash) away” something means to hide something, to put it in a secret place. A “nest egg” is money that you are going to use, in this case, for retirement. Money that you save for your retirement when you stop working, that’s called a “nest (nest) egg.” Carlos says, “Where do you have your money invested?” Where did you put your money – stocks, bonds, etc.? Paulina says, “It’s safe and sound, don’t you worry.” The expression “to be safe and sound” means to be secure, without any danger, without any worry. Whenever there’s a big fire here in Los Angeles, or an earthquake, some members of my family – the ones who still love me! – will call me and ask if I am okay, and I will tell them I am “safe and sound,” I am fine.
Carlos laughs at Paulina and says, “You make it sound like (you are giving me the impression that) you have your money stashed under your mattress.” Your “mattress” is what you sleep on – what most of us sleep on at night. Paulina says, “A mattress is a very safe place for your money!” suggesting that she doesn’t have her money invested anywhere or in a bank, but she has it in her house underneath her mattress. Putting some money underneath (or below) your mattress is a traditional way of saving your money – of keeping your money. But, of course, it’s not a very good investment, although nowadays, perhaps, it is the safest one!
Now let’s listen to the dialogue again, this time at a normal speed.
[start of dialogue]
Paulina: Did you get your Social Security statement? I just got mine in the mail. If I keep working at this rate for the next 20 years, between Social Security and my savings, I should be sitting pretty for retirement.
Carlos: Yeah, I should be okay when I retire, too. I’ve been contributing to a 401(k) through my work for years, and my company gives a matching contribution.
Paulina: Really? I never bothered with a 401(k).
Carlos: A 401(k) really adds up over time. I also have an IRA, which is tax-deferred, and I have my money in a portfolio that is split between stocks and bonds. All of these investments are for the long haul, of course. How about you? What’s your retirement plan?
Paulina: I have money stashed away in a nice little nest egg.
Carlos: Where do you have your money invested?
Paulina: It’s safe and sound, don’t you worry.
Carlos: [Laughs] You make it sound like you have it stashed under your mattress.
Paulina: A mattress is a very safe place for your money!
[end of dialogue]
The script for this episode was written by Dr. Lucy Tse, who we hope will always be safe and sound.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us next time on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan. Copyright 2009, by the Center for Educational Development.
Glossary
social security – a program of the U.S. government that gives money to working people after they reach the age of 65
* Kyon started getting social security benefits when he turned 65 years old.
savings – money that one has saved for use in the future; money put into a savings account in a bank
* He used some of his savings to buy a new car.
sitting pretty – in a good, comfortable position or situation, especially financially or professionally
* After she sold her business for $1 million, she was sitting pretty.
retirement – the period of time when one has stopped working, usually after age 65
* She dreams of spending her retirement living on the beach and meeting friends each morning.
401(k) – a special type of account sponsored by an employer where workers save money for retirement
* For the past eight years, she has put 7% of each paycheck into her 401(k).
matching contribution – money that a company puts into an employee’s 401(k) each month, equal to the amount of money that the employee puts into it each month
* After you have worked here for one month, the company will start to make a matching contribution, so the more you save, the more you get.
to add up – to total; to calculate the sum; to accumulate
* The cashier is adding up the cost of all the things we’re buying.
IRA – individual retirement account; a special type of account where a person can save money for retirement without paying any taxes on the money until later
* Larry opened an IRA when he was just 18 years old, so he’ll have a lot of money when he retires.
tax-deferred – with taxes not needing to be paid until later; with taxes being paid when money is taken out of an account and not when it is put into an account
* We should take advantage of tax-deferred savings opportunities because we don’t have to pay any taxes on the money until we start using it in retirement.
portfolio – all of a person’s investments, especially stocks and bonds
* Enrique’s portfolio includes a lot of stocks in energy companies.
split – divided; with more than one part or piece; not whole
* She doesn’t like the way her time is split between her work and her family.
stock – one share in a company; part ownership of a company that is bought and sold to make money
* Jung bought stock in Sony years ago, and he has made a lot of money as a result.
bond – an agreement where a company or the government borrows money from an individual for a certain period of time and agrees to pay it back with interest on a future date
* You might not make as much money with bonds as you can with stocks, but at least you can’t lose any money.
long haul – long term; over a long period of time; not immediate
* It was a long haul before women got the right to vote in most countries.
stashed away – hidden, safe, and secret; in a secret, safe place
* Mindy stashed away the chocolate candies so that her children wouldn’t find them.
nest egg – money that one plans to use in retirement; money that one has saved for retirement
* When the economy started having problems, many people were sad to see that their nest egg had lost a lot of money.
to invest – to buy something with the expectation that it will increase in value so that one can sell it later and make money
* They bought a home last year for $210,000 and invested about $50,000 in repairs, and now, they’re trying to sell it for $295,000.
safe and sound – secure; without any danger, fear, or worry
* Please call us from the airport to let us know that you’ve arrived safe and sound.
Comprehension Questions
1. Which of these would not be part of a nest egg?
a) A 401(k).
b) An IRA.
c) A long haul.
2. What does Paulina mean when she says, “I have my money stashed away in a nice little nest egg”?
a) She has invested her money in a chicken farm.
b) She has enough money for retirement saved in a safe place.
c) She keeps her money in a bird’s nest.
Answers at bottom.
What Else Does It Mean?
to add up
The phrase “to add up,” in this podcast, means to total or to calculate the sum: “Your order adds up to $48.92.” The phrase “to not add up” means to not provide a good explanation for something: “He said he couldn’t go to the party because he has to take care of his little sister that night, but that doesn’t add up because his sister is 24 years old.” The phrase “to add (something) in” means to include something with something else: “Don’t forget to add in sales tax when you make a sale.” Finally, the phrase “to add (something) on” means to create something additional, especially when building something: “They’re going to add on a fourth bedroom at the west end of their home.”
bond
In this podcast, the word “bond” means an agreement where a company or the government borrows money from an individual for a certain period of time and agrees to pay it back with interest on a future date: “If you don’t like to take risks, you can invest your money in bonds.” A “bond” is also a connection or a relationship between two people: “He shares a strong bond with his brothers and they call each other almost every day.” As a verb, “to bond” refers to the process of two people building a closer relationship: “He started working fewer hours so that he could bond with his son.” Finally, the verb, “to bond” means to be glued together or stuck together: “We bonded the two pieces of wood together with glue.”
Culture Note
In the United States, most people plan to retire when they are 65 years old. However, some people retire much earlier, either because they want to or because they have to.
“Early retirement” happens when someone retires before the age of 65. Sometimes people are able to have an early retirement because they have been very successful in their career. They don’t need any more money, and they don’t want to work anymore, so they decide to retire early. This might happen if someone sells a business.
Some people go into “early retirement” when they lose their job. Their company might tell them that they are going to be “fired” (told not to work anymore), but offer them a choice, so that if they retire instead of being fired they will receive some money. This can be a very attractive “option” (choice) for people who are “approaching” (almost at) retirement age.
“Mandatory retirement” happens when someone is no longer allowed to continue working in a particular job because he or she is too old. Some people think that mandatory retirement is illegal because it is a type of “age discrimination” (the practice of treating people unfairly and differently because of their age), but in some “cases” (situations) it makes sense. For example, a soldier probably won’t fight very well by the time he or she is 70 years old.
Sometimes people are old and tired of working, but don’t yet have enough money to “fully” (completely) retire. These people might start a “semi-retirement,” where they “quit” (stop working) their regular job and begin working part-time in a very easy job, maybe just for a few hours each week. People in semi-retirement might work part-time at a coffee shop or a store, just to have some extra money.
Comprehension Answers
1 - c
2 - b