
= step 2 - Lesson 31
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../+ 000 eng选/美国高中历史教材 American History ： From Pre-Columbian to the New Millennium/myAdocCss.css

'''

Lesson 31




== part 1

Denise: On the contrary, I don’t agree at all with people who say graphology is all nonsense. I think that at last it is beginning to be taken seriously as a proper science and not as some kind of fairground entertainment.

[.my2]
丹尼斯：恰恰相反，我完全不同意那些说笔迹学完全是胡说八道的人。我认为它终于开始被认真地视为一门真正的科学，而不是某种游乐场娱乐。

Leo: How did you start to become interested in graphology?
Leo：你是怎么开始对笔迹学产生兴趣的？

Denise: I’ve always been fascinated by people and what they are like, and then one day I was just looking at a book about different styles of handwriting and I got to thinking that it must all mean something, because we all have a different and individual style of our own. So that’s how I began.

[.my2]
丹尼斯：我一直对人和他们的样子很着迷，有一天我正在看一本关于不同风格的笔迹的书，我开始想这一定意味着什么，因为我们都有不同的笔迹以及我们自己的个人风格。我就是这样开始的。

Leo: What exactly is the connection between the way we write and the way we are?

[.my2]
利奥：我们的写作方式和我们的生活方式之间到底有什么联系？

Denise: If you think about it, our handwriting, and our doodling too, are all products of our brain — a kind of extension of ourselves on paper, so, consciously or unconsciously, we are giving a kind of 'computer printout' of what we think or feel when we write. As the brain is where our thoughts and feelings lie, there is every reason to assume that our character is transmitted into our handwriting.

[.my2]
丹尼斯：如果你想一想，我们的笔迹和涂鸦都是我们大脑的产物——一种我们自己在纸上的延伸，因此，有意识或无意识，我们正在提供一种“计算机打印输出”当我们写作时，我们会思考或感受。由于大脑是我们思想和感情的所在地，因此我们有充分的理由假设我们的性格会传递到我们的笔迹中。

Leo: Now I know that a number of European firms have used graphology to evaluate potential employees for some time now, but I believe it’s catching on in America too.
Leo：现在我知道许多欧洲公司已经使用笔迹学来评估潜在员工一段时间了，但我相信它在美国也正在流行。

Denise: I’m now running my own San Francisco-based consultancy firm, which I started a decade ago, and now over two hundred firms come to me for advice on would-be employees.

[.my2]
丹尼斯：我现在在旧金山经营自己的咨询公司，该公司是我十年前创办的，现在有超过 200 家公司向我寻求有关未来员工的建议。

Leo: How does it work out, then? Do they show you samples of an applicant’s handwriting?

[.my2]
狮子座：那结果如何呢？他们会向您展示申请人的笔迹样本吗？

Denise: Yes, most companies nowadays require their new job applicants to provide at least a one-page writing sample which is then passed over to me for interpretation.

[.my2]
丹尼斯：是的，现在大多数公司都要求新求职者提供至少一页的写作样本，然后交给我进行解释。

Leo: How long does it take you to analyse a sample?
Leo：您分析一个样本需要多长时间？

Denise: Oh, anything from three to eight hours, depending on the amount of detail required by the client.

[.my2]
丹尼斯：哦，三到八小时不等，具体取决于客户所需的详细信息量。

Leo: And what can you tell from the sample you get?
Leo：从你得到的样本中你能看出什么？

Denise: A whole range of personality traits can be assessed, such as enthusiasm, ambition, imagination, diligence, sincerity, secretiveness — just about everything, in fact.

[.my2]
丹尼斯：一系列的人格特质都可以被评估，比如热情、野心、想象力、勤奋、真诚、神秘——事实上，几乎一切。

Leo: Can you give us some tell-tale clues about the way we write? I’m sure our listeners will all be dying to hear something.
Leo：你能给我们一些关于我们写作方式的线索吗？我相信我们的听众都会渴望听到一些东西。

Denise: OK, you just write the letter 't', not a capital but an ordinary 't', please, Leo.

[.my2]
丹尼斯：好的，你只写字母“t”，不是大写字母，而是普通的“t”，Leo。

Leo: All right. There you are. Now what can you tell me from that?

[.my2]
利奥：好吧。你在这。现在你能从中告诉我什么？

Denise: Mmm …​ well, the 't' you’ve written, which is more or less straight up and crossed with a diagonal stroke from south-west to north-east, as it were, indicates an optimistic kind of character to me. Would you describe yourself in that way?

[.my2]
丹尼斯：嗯……嗯，你写的“t”，或多或少是笔直向上的，并用对角线从西南到东北交叉，可以说，对我来说，它表明了一种乐观的性格。你会这样描述自己吗？

Leo: Mmm, yes, I think so. Can you describe any other kinds of 't' for the benefit of our listeners?
Leo：嗯，是的，我想是的。您能为我们的听众描述任何其他类型的“t”吗？

Denise: Yes, of course. If, for example, you had written a 't' but crossed it only with a stroke on the left of the vertical stem, which didn’t even reach it in fact, that would indicate a procrastinating character, someone who puts things off until tomorrow. Inefficiency can be identified by a 't' where there are two vertical strokes in the stem, reaching up to a rounded point, and then crossed right through. Mmm, what else can I say? A thick cross on the left of the stem, tapering to a point on the right of the stem, tells me that the writer is a sarcastic kind of person. Another thing is that a very practical sort of person always crosses his 't' halfway down the letter, whereas a 't' crossed high up the stem shows a dreamer. The letters 'm' and 'n' are also indicative of personality, depending on whether they are rounded or wedge-shaped.

[.my2]
丹尼斯：是的，当然。例如，如果你写了一个“t”，但只在垂直词干的左侧划了一个笔画，实际上甚至没有到达它，这将表明一个拖延的性格，一个把事情拖到最后的人。明天。效率低下可以通过“t”来识别，其中词干中有两个垂直笔画，达到圆形点，然后直接穿过。嗯，我还能说什么？茎左侧有一个粗大的十字，在茎右侧逐渐变细，告诉我作者是一个讽刺的人。另一件事是，一个非常实际的人总是在字母的中间交叉他的“t”，而在词干高处交叉的“t”则表明他是一个梦想家。字母“m”和“n”也代表个性，具体取决于它们是圆形还是楔形。

Leo: I see. That’s most interesting.

[.my2]
利奥：我明白了。这是最有趣的。

Denise: One little success story of mine, which I must tell you about, concerns Royal Office Products of New York. They once took a big chance on my analysis of an applicant’s writing. His name was Harry Benson, in fact, and he was after an executive job, and he was a person they would never have taken on otherwise …​ because he came across very badly orally and in his appearance. However, on the strength of my interpretation of his writing they took him on, and now, only a few years later, he’s already President of the company.

[.my2]
丹尼斯：我必须告诉你的一个小成功故事是关于纽约皇家办公产品的。他们曾经在我对申请人写作的分析上冒了很大的风险。事实上，他的名字叫哈里·本森，他正在寻找一份行政职位，否则他们永远不会接受他……因为他的口头和外表都给人留下了非常糟糕的印象。然而，根据我对他作品的解读，他们接受了他，现在，仅仅几年后，他已经成为公司总裁。

Leo: I’d like now to turn to doodling because most of us doodle away merrily, quite absentmindedly, and hear what you have to say about that.
Leo：我现在想谈谈涂鸦，因为我们大多数人都在快乐地、心不在焉地涂鸦，听听你对此有何看法。

Denise: Oh, you can tell a great deal about people from their doodles as well as their handwriting. The doodle, to my mind, is a message straight from the subconscious. The reason you are feeling the way you are is always written in your doodles.

[.my2]
丹尼斯：哦，你可以从人们的涂鸦和笔迹中了解很多关于他们的信息。在我看来，涂鸦是直接来自潜意识的信息。你的感受总是写在你的涂鸦中。

Leo: Can you give us some indication of what you mean?
Leo：您能告诉我们您的意思吗？

Denise: Take, for example, very angular or tangled horizontal lines …​ Now, if a person when doodling does a lot of them, it is very indicative of hidden anger and frustration. Arrows, when drawn, stand for ambition, and when they are aimed in a lot of different directions, this will mean confusion in reaching goals.

[.my2]
丹尼斯：以非常有棱角或纠结的水平线为例......现在，如果一个人在涂鸦时画了很多这样的线，则非常表明隐藏的愤怒和沮丧。绘制的箭头代表野心，而当它们瞄准许多不同的方向时，这将意味着实现目标的混乱。

Leo: Before we started the programme, I happened to be doodling on this pad here. What does that tell you about me? — that’s if you can repeat it! (Laughs).
Leo：在我们开始节目之前，我碰巧在这块本子上涂鸦。这告诉你关于我的什么？ ——如果你能重复的话！ （笑）。

Denise: Well, let me see. You have drawn a very detailed and symmetrical design which tells me, superficially at any rate, that you are a very orderly and rather precise person — a conformist, if you like — who doesn’t like chaos and has to have everything planned.

[.my2]
丹妮丝：好吧，让我看看。你画了一个非常详细和对称的设计，至少从表面上看，它告诉我，你是一个非常有秩序和相当精确的人——如果你愿意的话，是一个墨守成规的人——不喜欢混乱，必须把一切都计划好。

Leo: Yes, well, you’re right to some extent. I’ve got one or two others here done by people in the studio. What can you say about them?

[.my2]
狮子座：是的，嗯，在某种程度上你是对的。我还有一两个由工作室里的人完成的作品。对于他们你有什么想说的？

Denise: This one here, which has lots of little stars on it — now, they generally represent hope. And here, on this one, somebody has drawn a human eye, which is indicative of a suspicious or distrustful nature.

[.my2]
丹尼斯：这个，上面有很多小星星——现在，它们通常代表着希望。在这里，在这上面，有人画了一只人类的眼睛，这表明了可疑或不信任的本质。

Leo: I’d better not tell you who is the artist, then!
Leo：那我最好不要告诉你艺术家是谁！

Denise: Now, in this one, somebody has drawn a little human figure, which probably means they make friends very easily — and enemies too, incidentally.

[.my2]
丹尼斯：现在，在这幅画中，有人画了一个小人物，这可能意味着他们很容易交朋友——顺便说一句，也很容易交敌人。

Leo: Does everybody doodle?
Leo：每个人都涂鸦吗？

Denise: Most people do it because they are bored, but some do it more than others. Creative people like architects or fashion designers do a great deal of aimless doodling, whereas writers, on the other hand, do very little because they have a way of expressing themselves in words. I think probably people with disabilities are the best doodlers, because their normal outlets are blocked.

[.my2]
丹尼斯：大多数人这样做是因为他们感到无聊，但有些人这样做的次数比其他人多。像建筑师或时装设计师这样的创意人士会进行大量漫无目的的涂鸦，而作家则很少做，因为他们有一种用语言表达自己的方式。我认为残疾人可能是最好的涂鸦者，因为他们正常的出路被堵住了。

Leo: What about actual writing implements, does it make any difference what you choose to write with?
Leo：那么实际的书写工具呢？你选择什么书写工具有什么不同吗？

Denise: Indeed, yes. If you give people a choice of writing implements — say a pencil, a felt tip or an ordinary pen — the middle-of-the-roaders will go for the ordinary pen, those who want to leave the biggest impression with the least amount of work will take the felt tip. As for pencils, I won’t say it’s true in every case, some pencil users aren’t very honest; pencils can be erased, you see, so it’s a way of leaving no traces. Criminals will almost always choose a pencil, although of course I’m not suggesting that all pencil users are criminals, of course.

[.my2]
丹妮丝：确实，是的。如果你让人们选择书写工具——比如铅笔、毡尖笔或普通笔——中间人会选择普通笔，那些想用最少的笔留下最大印象的人工作将采取毡尖。至于铅笔，我不会说在所有情况下都是如此，有些铅笔使用者不太诚实；你看，铅笔可以擦掉，所以这是一种不留痕迹的方法。犯罪分子几乎总是会选择铅笔，当然我并不是说所有铅笔使用者都是犯罪分子。

Leo: Well, thank you very much, Denise. That was very interesting, and I’m sure from now on we’ll all be careful not to leave our doodles lying around.

[.my2]
利奥：嗯，非常感谢你，丹妮丝。这非常有趣，我相信从现在开始我们都会小心，不要把涂鸦随处可见。

2. part 2. 部分
The number of adult smokers in the United States keeps going down, down, down, almost twenty percent in the past decade, according to a new survey by the American Cancer Society. Their report based on the government’s statistics shows that, while more and more women are taking up the smoking habit, more than enough men are quitting to make up for it. But that news about the women troubles Dr Ervin Mann, an obstetrician at Paxtang, Pennsylvania and he decided to do something about it. If you are a pregnant woman and if you smoke cigarettes, then Dr Mann will make you an offer that he hopes you can’t refuse.

[.my2]
根据美国癌症协会的一项新调查，在过去十年中，美国成年吸烟者的数量持续下降、下降、下降，几乎百分之二十。他们基于政府统计数据的报告显示，虽然越来越多的女性养成了吸烟的习惯，但有足够多的男性正在戒烟以弥补这一缺陷。但有关这些女性的消息让宾夕法尼亚州帕克斯坦的产科医生欧文·曼博士感到困扰，他决定对此采取一些措施。如果您是一名孕妇并且吸烟，那么曼恩博士将为您提供一个他希望您无法拒绝的提议。

"What we will do is, if you will not smoke throughout your pregnancy, then we’ll offer you one hundred dollars off the obstetric bill."

[.my2]
“我们要做的是，如果您在整个怀孕期间不吸烟，那么我们将为您提供一百美元的产科费用减免。”

"And how much is the typical bill, so how big is this discount going to be?"

[.my2]
“一般的账单是多少，那么这个折扣有多大呢？”

"Basically the obstetric bill is one thousand two hundred dollars. So it’s a little less than ten percent."

[.my2]
“基本上，产科费用是一千二百美元。所以略低于百分之十。”

"What inspired you to try this hundred-dollar rebate?"

[.my2]
“是什么促使你尝试这个百元回扣？”

"We know that smoking during pregnancy results in lower birthrate incense. In other words because of smoking babies are small at birth. And that’s the one thing we really know. There have been other things that’ve been implicated that there is increasing birth defects in smoking women."

[.my2]
“我们知道怀孕期间吸烟会导致出生率降低。换句话说，因为吸烟，婴儿出生时很小。这是我们真正知道的一件事。还有其他一些事情表明出生缺陷增加吸烟的女性。”

"You should explain to me, explain to our listeners why that is of a concern to a doctor, or to a mother and her baby?"

[.my2]
“你应该向我解释，向我们的听众解释为什么这会引起医生或母亲和她的孩子的关注？”

"We know that smaller weight babies have more difficulty in thriving in an early life, so that it takes both babies who are light in weight at the time of birth, will take at least a year of good care before they will come up to the standards."

[.my2]
“我们知道，体重较小的婴儿在生命早期成长起来会更加困难，因此出生时体重较轻的婴儿至少需要一年的精心照顾才能达到正常水平。标准”。

"So what are the results, does money talk in this case, or are women in your practice buying the idea?"

[.my2]
“那么结果是什么？在这种情况下，金钱是万能的吗？还是说，在你的实践中，女性是否认同这个想法？”

"Well, money partially talks. We have had seventy-five women who have completed their pregnancy who have previously smoked. And of these seventy-five women, thirty-five of them have gone without smoking during the pregnancy."

[.my2]
“好吧，金钱是万能的。我们有 75 名完成怀孕的女性以前吸烟过。在这 75 名女性中，有 35 人在怀孕期间没有吸烟。”

"Ah, so they’re getting the hundred dollars."

[.my2]
“啊，所以他们得到了一百美元。”

"They are getting the hundred dollars back. Certainly we haven’t had any low birth weight children in that group of patients."

[.my2]
“他们正在拿回一百美元。当然，我们这组患者中没有低出生体重的孩子。”

"How do you know for sure that those thirty-five women have indeed not smoked at all? Maybe they’re misleading you."

[.my2]
“你怎么确定那三十五个女人确实根本没有抽烟？也许她们误导了你。”

"It’s all an honor system. Each time they come for an examination they reaffirm their refusal to smoke. And certainly we trust those patients and feel that they are following it. Other patients, of course, have stated they have started smoking again. So I think it’s a pretty good cross section."

[.my2]
“这都是一种荣誉制度。每次他们来接受检查时，他们都会重申拒绝吸烟。当然，我们信任这些患者，并觉得他们正在遵守它。当然，其他患者也表示他们又开始吸烟了。所以我认为这是一个非常好的横截面。”

"And just one more thing. When, if we come back to you in a year from now, how much do you think…​"

[.my2]
“还有一件事。如果一年后我们再来找你，你觉得……​”

"I can improve those figures."

[.my2]
“我可以改善这些数字。”

"Let me ask you this though, How much do you think you will be paying women to stop smoking?"

[.my2]
“让我问你一个问题，你认为你会付给女性多少钱来戒烟？”

"Well, we’ll probably be raising it up to two-hundred or two-hundred-fifty-dollar range, I would think."

[.my2]
“嗯，我想我们可能会将其提高到两百或两百五十美元的范围。”

Ervin Mann is an obstetrician at Paxtang, Pennsylvania.

[.my2]
欧文·曼 (Ervin Mann) 是宾夕法尼亚州帕克斯坦的一名产科医生。



== 3. Marriage Customs

婚俗

Today we are going to look at the social custom of marriage from a sociological point of view. All societies make provisions for who may mate with whom. The benefits of the social recognition of marriage for children are obvious. It gives them an identity, membership of a socially recognized group and some indication of who must support them and their mother.

[.my2]
今天我们就从社会学的角度来看看婚姻的社会习俗。所有社会都对谁可以与谁交配作出规定。社会承认婚姻对孩子的好处是显而易见的。它赋予他们身份、社会认可群体的成员资格，以及谁必须支持他们和他们的母亲的一些指示。

Now almost all societies have marriage, but there are wide variations in marriage systems. I will give three of the important areas of variation, and some details of each area. The three areas I shall deal with are: firstly, the number of mates each marriage partner may have; secondly, the locality of the marriage (that is, where do the newly married partners set up home?); and thirdly, what arrangements there are for the transfer of wealth after the marriage. Let me deal with each of these in turn.

[.my2]
现在几乎所有社会都有婚姻，但婚姻制度却存在很大差异。我将给出三个重要的变化领域，以及每个领域的一些细节。我要讨论的三个方面是：第一，每个婚姻伴侣可以拥有的配偶数量；其次，婚姻所在地（即新婚双方的家在哪里？）；第三，婚后财产转移有哪些安排。让我依次处理这些问题。

First, how many mates? In existing human societies there are three possibilities. Most societies recognize POLYGYNY, and that’s spelt P-O-L-Y-G-Y-N-Y, POLYGYNY, or the right of a man to take more than one wife. In a few societies (not in Africa) there is POLYANDRY, and that’s spelt P-O-L-Y-A-N-D-R-Y, POLYANDRY, in which a woman is married to two or more men at the same time. Finally, especially in Europe and societies of European origin, there is MONOGAMY, and that’s spelt M-O-N-O-G-A-M-Y, MONOGAMY. Monogamy limits one man to one wife and vice-versa.

[.my2]
首先，有几个伙伴？现有的人类社会存在三种可能性。大多数社会都承认 POLYGYNY，拼写为 P-O-L-Y-G-Y-N-Y、POLYGYNY，即男人娶多个妻子的权利。在一些社会（非洲除外）存在一夫多妻制，拼写为 P-O-L-Y-A-N-D-R-Y，POLYANDRY，即一名妇女同时与两名或两名以上男子结婚。最后，特别是在欧洲和欧洲血统的社会中，存在一夫一妻制，拼写为 M-O-N-O-G-A-M-Y，MONOGAMY。一夫一妻制限制一个男人只能拥有一个妻子，反之亦然。

The second area of variation is, as we have said, the locality of the marriage. Here there seem to be three possibilities: at the husband’s home, at the wife’s home, or in some new place. The old term for the arrangement when a wife moves to her husband’s family’s household is a PATRILOCAL marriage, and that’s spelt P-A-T-R-I-L-O-C-A-L, PATRILOCAL; a more modern term is VIRILOCAL, and we spell that V-I-R-I-L-O-C-A-L, VIRILOCAL. The opposite, when the man moves, is termed MATRILOCAL, and we spell that M-A-T-R-I-L-O-C-A-L, MATRILOCAL, or UXORILOCAL, and that’s spelt U-X-O-R-I-L-O-C-A-L, UXORILOCAL marriage. The third possibility when they set up a new household somewhere else is called NEOLOCAL marriage, and that’s spelt N-E-O-L-O-C-A-L, NEOLOCAL.

[.my2]
正如我们所说，第二个变化领域是婚姻的地点。这里似乎有三种可能：在丈夫家，在妻子家，或者在某个新地方。妻子搬到丈夫家的安排的旧称是父权婚姻，拼写为 P-A-T-R-I-L-O-C-A-L，PATRILOCAL；更现代的术语是 VIRILOCAL，我们拼写为 V-I-R-I-L-O-C-A-L，VIRILOCAL。相反，当男人移动时，称为MATRILOCAL，我们拼写为M-A-T-R-I-L-O-C-A-L、MATRILOCAL或UXORILOCAL，拼写为U-X-O-R-I-L-O-C-A-L，UXORILOCAL婚姻。当他们在其他地方建立新家庭时的第三种可能性称为新本地婚姻，拼写为 N-E-O-L-O-C-A-L，NEOLOCAL。

The last area of variation is transfer of wealth on marriage. Here, once more, we seem to have three possibilities. Firstly we have BRIDEWEALTH, and that’s spelt B-R-I-D-E-W-E-A-L-T-H, BRIDEWEALTH. In this system wealth is transferred by the husband or his relatives to the bride’s family.

[.my2]
最后一个变化领域是婚姻时的财富转移。在这里，我们似乎再次面临三种可能性。首先我们有 BRIDEWEALTH，拼写为 B-R-I-D-E-W-E-A-L-T-H，BRIDEWEALTH。在这种制度下，财富由丈夫或其亲属转移到新娘的家庭。

This, of course, is the system familiar in Africa. We should remember that the bridewealth may take the form of the husband’s labour services to his father-in-law rather than giving cattle or money. In some other societies the opposite system prevails and the wife brings with her a portion or DOWRY, and that’s spelt D-O-W-R-Y, DOWRY, in the form of money or other wealth such as land. This was the system of, for example, traditional European societies, and is still practised in the Irish countryside. The third possibility is for the transfer of wealth to take the form of gifts to help the young couple set up the new household. This system is associated with the neolocal type of marriage. In England, these gifts are called wedding-presents. The near kin, that is, the near relatives, of both bride and groom contribute and so do friends, neighbours and workmates. The presents customarily take the form of useful household goods, such as saucepans, tea sets or blankets.

[.my2]
当然，这是非洲熟悉的制度。我们应该记住，彩礼可以采取丈夫向岳父提供劳务的形式，而不是给予牛或金钱。在其他一些社会中，盛行相反的制度，妻子会带来一部分或嫁妆，拼写为 D-O-W-R-Y，DOWRY，以金钱或其他财富（例如土地）的形式存在。例如，这是传统欧洲社会的制度，并且在爱尔兰乡村仍在实行。第三种可能性是以礼物的形式转移财富，帮助年轻夫妇组建新家庭。该系统与新地方婚姻类型相关。在英国，这些礼物被称为结婚礼物。新娘和新郎的近亲（即近亲）以及朋友、邻居和同事也都捐款。礼物通常采用有用的家庭用品的形式，例如平底锅、茶具或毯子。

'''
