
= step 2 - Lesson 15
:toc:


---



Lesson 15



== 1

A: Did you hear on the news today about that ... uh ... murderer who was executed?


B: I can't believe it.


A: Yeah. That's the first time in ten years that they've used capital punishment.


B: I just can't believe in our society today that they would actually kill another human being. Nobody has the right to take another person's life.


A: Oh, I don't agree. Listen, I think capital punishment is — it's about time it came back. I think that's exactly what killers deserve.


B: No, they don't deserve that. Because once you're killing a killer, you're the killer, too. You become a killer as well.


A: No, listen. You take a life, you have to be willing to give up your own. And also, I think that if you have a death penalty it will prevent other people from killing. I think it's a good deterrent.


B: I don't think it's a good deterrent at all. My goodness gracious. I mean, first of all, are you sure the person you've convicted to death is really guilty?


A: Well, I think that's a very rare ... very rare incidence.


B: I don't think it's rare, (I don't think it's ...) with all the cracker jack lawyers we have today, (Well, no ... I ...) and the judicial system the way it is.


A: I think it's a rare incidence, and I think it's more important to get rid of the ... the bad seed, you know?


B: But you don't get rid of it. You rehabilitate somebody like that. (Oh ...) You don't eliminate, you rehabilitate.


A: Listen, studies show that criminals are never really rehabilitated. When they're ... when they come out of prison they just go back to a life of crime, and they're hardened by that crime.


B: Because the rehabilitation process has to be more than just what's in jail. I mean, (Oh ... well.) when you're in jail you do have to work, but when you're out of jail there has to be an extensive program. We have to expand on the idea till it works.


A: I don't agree. Listen — and, anyway, the jails and the prisons are already very crowded, and we have to pay, the taxpayers. Our money goes to maintaining murderers' (I ...) lives.


B: I agree with you. That's why it's important to look at the problem on a much larger scale. The real problem is a social problem. (What ... no ...) There are other problems that cause people to kill. Look at poverty, drugs, discrimination.


A: Some people are just bad. They're just evil and there's nothing you can do.


B: No, there ... it is ... no, it isn't true. There's rehabilitation. (No.) And they ... we're all responsible it ... for ... to humanity. That's one of the reasons ...


A: Well, but in the meantime you have to take care of the people who have already committed ...


B: I agree with you there.


A: Preventative is different, but ...


B: I agree with you there.

A：你今天在新闻中听说过那个……呃……凶手被处决了吗？


B：我简直不敢相信。


答：是的。这是十年来他们第一次使用死刑。


B：我简直不敢相信我们今天的社会他们真的会杀死另一个人。任何人都没有权利夺取他人的生命。


答：哦，我不同意。听着，我认为死刑是——现在是时候回归了。我认为这正是杀手应得的。


B：不，他们不应该这样。因为一旦你杀死了一个杀手，你就是杀手了。你也会成为杀手。


答：不，听着。你夺走了一条生命，你必须愿意放弃自己的生命。而且，我认为如果判处死刑，就会防止其他人杀人。我认为这是一个很好的威慑。


B：我认为这根本不是一个很好的威慑力。我的天啊，仁慈的。我的意思是，首先，你确定被你判处死刑的人真的有罪吗？


答：嗯，我认为这种情况非常罕见……​非常罕见。


B：我不认为这很罕见，（我不认为这是……​）我们今天拥有的所有出色的杰克律师，（嗯，不……我……​）以及司法系统的现状。


答：我认为这种情况很少见，而且我认为更重要的是摆脱......坏种子，你知道吗？


B：但你并没有摆脱它。你让这样的人康复。 （噢……​）你不是消灭，而是恢复。


答：听着，研究表明罪犯永远不会真正改过自新。当他们......当他们出狱时，他们只是回到犯罪生活，并且他们因犯罪而变得坚强。


B：因为改造过程不只是监狱里的事情。我的意思是，（哦……好吧。）当你在监狱里时，你确实必须工作，但当你出狱时，必须有一个广泛的计划。我们必须扩展这个想法，直到它发挥作用。


答：我不同意。听着——无论如何，看守所和监狱已经非常拥挤，我们必须付钱给纳税人。我们的钱用于维持凶手（我……​）的生命。


B：我同意你的看法。这就是为什么从更大的范围来看待问题很重要。真正的问题是社会问题。 （什么…​不…​）还有其他问题导致人们杀人。看看贫困、毒品、歧视。


答：有些人就是很坏。他们只是邪恶的，你无能为力。


B：不，那里……是……不，这不是真的。有康复。 （不。） 他们……我们都对……对人类负责。这就是原因之一……​


答：嗯，但与此同时，你必须照顾那些已经做出承诺的人……​


B：我同意你的观点。


答：预防措施有所不同，但是……​


B：我同意你的观点。




---

== 2

Announcer: On 'TV Magazine' tonight we're looking at people who have given up regular jobs and high salaries to start a new way of life. First of all, we have two interviews with people who decided to leave the 'rat race'. Nicola Burgess spoke to them.


Nicola: This is the Isle of Skye. Behind me you can see the croft belonging to Daniel and Michelle Burns, who gave up their jobs to come to this remote area of Scotland. Daniel was the sales manager of Hi-Vita, the breakfast cereal company, and Michelle was a successful advertising executive. Michelle, can you tell us what made you give up everything to come here?


Michelle: Everything? That's a matter of opinion. A big house and two cars isn't everything! Dan and I both used to work long hours. We had to leave so early in the morning and we came home so late at night, that we hardly ever saw each other. We should have come here years ago, but we were earning such big salaries that we were afraid to leave our jobs. In the end we had so little time together that our marriage was breaking up. So two years ago, we took a week's holiday in the Scottish Highlands. We saw this place and we both fell in love with it. It was for sale, and we liked it so much that we decided to give up our jobs, and here we are!


Nicola: How do you earn a living? If you don't mind me asking.


Michelle: We don't need very much. We keep sheep and goats, grow our own vegetables. We've got a few chickens. It's a very simple life, and we're not in it for profit. We're still so busy that we work from five in the morning until eight at night, but we're together. We're happier than we're ever been and we're leading a natural life.


Nicola: There must be some things you miss, surely.


Michelle: I don't know. We knew such a lot of people in London, but they weren't real friends. We see our neighbours occasionally and there's such a lot to do on the farm that we don't have time to feel lonely. At least we see each other now.


Nicola: The motor-bike I'm sitting on is a very special one. Special because it's been all the way round the world. It belongs to Luke Saunders, who has just returned to England after a three year motor-cycle journey. Luke, what led you to leave your job and make this trip?


Luke: I worked in a car factory on the assembly line. All I had to do was put four nuts on the bolts that hold the wheels on. It's done by robots now, and a good thing too! The job was so routine that I didn't have to think at all. I bought this Triumph 750 cc bike second-hand, fitted two panniers on the back and just set off for Australia.


Nicola: What did you do for money?


Luke: I had a bit of money to start with, but of course it didn't last long and I had to find work where I could. I've done so many different things — picked fruit, washed up, worked as a mechanic.


Nicola: How did people react to you? In India, for example.


Luke: Everywhere I went, the people were so friendly that problems seemed to solve themselves. There was such a lot of interest in the bike that it was easy to start a conversation. You know, often you can communicate without really knowing the language.


Nicola: Did you ever feel like giving up, turning round and coming home?


Luke: Only once, in Bangladesh. I became so ill with food poisoning that I had to go to hospital. But it didn't last long.


Nicola: You've had such an exciting time that you'll find it difficult to settle down, won't you?


Luke: I'm not going to. Next week I'm off again, but this time I'm going in the opposite direction! See you in about three years' time!

播音员：在今晚的“电视杂志”中，我们正在关注那些放弃正常工作和高薪开始新生活方式的人。首先，我们采访了两次决定退出“激烈竞争”的人。尼古拉·伯吉斯与他们交谈。


尼古拉：这是斯凯岛。在我身后，你可以看到属于丹尼尔·伯恩斯和米歇尔·伯恩斯的小农场，他们放弃了工作来到苏格兰的这个偏远地区。丹尼尔是早餐麦片公司 Hi-Vita 的销售经理，米歇尔是一位成功的广告主管。米歇尔，你能告诉我们是什么让你放弃一切来到这里吗？


米歇尔：一切？这是一个见仁见智的问题。一个大房子和两辆车还不是一切！丹和我过去都工作很长时间。我们早上很早就要离开，晚上很晚才回家，所以我们几乎没有见过面。我们几年前就应该来这里，但我们的薪水如此之高，以至于我们不敢离开工作。最后，我们在一起的时间太少了，我们的婚姻破裂了。两年前，我们在苏格兰高地度过了一周的假期。我们看到了这个地方，我们都爱上了它。它正在出售，我们非常喜欢它，以至于我们决定放弃我们的工作，我们就在这里！


尼古拉：你靠什么谋生？如果你不介意我问的话。


米歇尔：我们不需要太多。我们饲养绵羊和山羊，自己种植蔬菜。我们有几只鸡。这是一种非常简单的生活，我们并不是为了盈利。我们仍然很忙，从早上五点工作到晚上八点，但我们在一起。我们比以往任何时候都幸福，我们过着自然的生活。


尼古拉：肯定有一些事情你想念。


米歇尔：我不知道。我们在伦敦认识很多人，但他们都不是真正的朋友。我们偶尔会见到邻居，农场里有很多事情要做，所以我们没有时间感到孤独。至少我们现在见面了。


尼古拉：我坐的摩托车是一辆非常特别的摩托车。特别是因为它已经遍布世界各地。它属于卢克·桑德斯 (Luke Saunders)，他刚刚结束三年的摩托车之旅回到英国。卢克，是什么促使您辞去工作并进行这次旅行？


卢克：我在一家汽车厂的装配线上工作。我所要做的就是在固定车轮的螺栓上安装四个螺母。现在已经由机器人完成了，这也是一件好事！这项工作是如此例行公事，我根本不需要思考。我买了这辆二手 Triumph 750 cc 自行车，在后面装了两个包，然后就出发去澳大利亚了。


尼古拉：你为了钱做了什么？


卢克：我一开始有一点钱，但当然这并没有维持多久，我必须尽可能地找到工作。我做过很多不同的事情——摘水果、洗衣服、当机械师。


尼古拉：人们对你有何反应？以印度为例。


卢克：无论我走到哪里，人们都非常友好，问题似乎可以自行解决。大家对自行车很感兴趣，很容易就开始交谈。您知道，通常您无需真正了解语言即可进行交流。


尼古拉：你有没有想过放弃、转身回家？


卢克：只有一次，在孟加拉国。我因食物中毒而病得很重，不得不去医院。但这种情况并没有持续多久。


尼古拉：你度过了如此激动人心的时光，以至于你会发现很难安定下来，不是吗？


卢克：我不会。下周我又要出发了，不过这次我要往相反的方向走！大约三年后见！




---

== 3

Here is an extract from a radio talk on the work of Sigmund Freud by Professor Eric Watkis:





Sigmund Freud developed his system of psychoanalysis while he was studying cases of mental illness. By examining details of the patient's life, he found that the illness could often be traced back to some definite problem or conflict within the person concerned. But he discovered, too, that many of the neuroses observed in mentally ill patients were also present, to a lesser degree, in normal persons. This led him to the realization that the borderline between the normal and the neurotic person is not nearly as clearly marked as was once believed.





In 1914 he published a book called The Psychopathology of Everyday Life. This book goes a long way towards explaining some of the strange behaviour of normal, sane people.





A glance at Freud's chapter headings will indicate some of the aspects of behaviour covered by the book:





Forgetting of proper names





Forgetting of foreign words





Childhood and concealing memories





Mistakes in speech





Mistakes in reading and writing





Broadly, Freud demonstrates that there are good reasons for many of the slips and errors that we make. We forget a name because, unconsciously, we do not wish to remember that name. We repress a childhood memory because that memory is painful to us. A slip of the tongue or of the pen betrays a wish or a thought of which we are ashamed.





In these days when every would-be doctor or writer has access to Freud's accounts of his research, it is worth pausing and remembering the remarkable scope and originality of his ideas.




以下是埃里克·沃特基斯教授关于西格蒙德·弗洛伊德作品的广播演讲的摘录：


西格蒙德·弗洛伊德在研究精神疾病病例时发展了他的精神分析系统。通过检查病人的生活细节，他发现疾病往往可以追溯到当事人内部的某些明确的问题或冲突。但他也发现，在精神病患者身上观察到的许多神经症在正常人身上也存在，但程度较轻。这使他意识到正常人和神经症患者之间的界限并不像曾经认为的那样清晰。


1914年，他出版了一本名为《日常生活的精神病理学》的书。这本书在很大程度上解释了正常、理智的人的一些奇怪行为。


扫一眼弗洛伊德的章节标题就可以看出该书涵盖的行为的一些方面：


忘记专有名称


忘记外来词


童年和隐藏的记忆


  言语错误


阅读和写作中的错误


总的来说，弗洛伊德证明我们犯下的许多失误和错误都是有充分理由的。我们忘记一个名字是因为我们无意识地不想记住这个名字。我们压抑童年记忆，因为那段记忆对我们来说是痛苦的。口误或笔误泄露了我们感到羞耻的愿望或想法。


如今，当每个想成为医生或作家的人都可以接触到弗洛伊德对其研究的描述时，值得停下来并记住他思想的非凡范围和独创性。



---

== 4

Cheese is one of those foods that we tend to take for granted as always having been with us, and it's odd to think that someone somewhere must have discovered the process that takes place when micro-organisms get into milk and bring about changes in its physical and biochemical structure.





Obviously, we don't know who discovered the process, but it's thought that it came from South-West Asia about 8,000 years ago.





Early cheese was probably rather unpalatable stuff, tasteless and bland in the case of the so-called 'fresh cheeses', which are eaten immediately after the milk has coagulated, and rough tasting and salty in the case of the 'ripened' cheeses, which are made by adding salt to the soft fresh cheese and allowing other biochemical processes to continue so that a stronger taste and a more solid texture result.





The ancient Romans changed all that. They were great pioneers in the art of cheese-making, and the different varieties of cheese they invented and the techniques for producing them spread with them to the countries they invaded. This dissemination of new techniques took place between about 60 BC and 300 AD. You can still trace their influence in the English word 'cheese', which comes ultimately from the Latin word 'caseus', that's C-A-S-E-U-S.





Well, things went on quietly enough after the Roman period with the cheese producers in the different countries getting on with developing their own specialities. It's amazing the variety of flavours you can get from essentially the same process.





At this stage in history, people weren't aware in a scientific way of the role of different micro-organisms and enzymes in producing different types of cheese. But they knew from experience that if you kept your milk or your 'pre-cheese' mixture at a certain temperature or in a certain environment, things would turn out in a certain way. The Roquefort caves in France are an example of a place that was used for centuries for the ripening of a certain sort of cheese, before people knew exactly why they produced the effect they did.





In the nineteenth century, with the increasing knowledge about micro-organisms, there came the next great step forward in cheese-making. Once it was known exactly which micro-organisms were involved in the different stages of producing a cheese, and how the presence of different micro-organisms affected the taste, it was possible to introduce them deliberately, and to industrialize the process.





Cheese started being made on a large scale in factories, although the small producer working from his farm dairy continued to exist and still exist today. Cheese-making moved very much into the world of technology and industrial processes, although, because the aim is still to produce something that people like to eat, there's still an important role for human judgement. People still go round tasting the young cheese at different stages to see how it's getting on, and may add a bit of this or that to improve the final taste. Whatever the scale of production, there is still room for art alongside the technology.

奶酪是我们理所当然地认为一直伴随着我们的食物之一，奇怪的是，认为某个地方的某个人一定已经发现了微生物进入牛奶并导致其物理变化时发生的过程，这很奇怪。和生化结构。


显然，我们不知道是谁发现了这个过程，但人们认为它来自大约 8000 年前的西南亚。


早期的奶酪可能是相当难吃的东西，对于所谓的“新鲜奶酪”来说，它无味且乏味，在牛奶凝固后立即食用，而对于“成熟”奶酪来说，味道粗糙且咸。是通过在柔软的新鲜奶酪中添加盐并让其他生化过程继续进行而制成的，从而产生更浓郁的味道和更坚实的质地。


古罗马人改变了这一切。他们是奶酪制作艺术的伟大先驱，他们发明的不同品种的奶酪及其生产技术随着他们传播到了他们入侵的国家。新技术的传播大约发生在公元前 60 年至公元 300 年之间。您仍然可以在英语单词“cheese”中追踪它们的影响，该单词最终源自拉丁语单词“caseus”，即 C-A-S-E-U-S。


好吧，罗马时期之后，事情进展得很平静，不同国家的奶酪生产商都在开发自己的特色奶酪。令人惊奇的是，您可以通过基本相同的过程获得多种口味。


在历史的这个阶段，人们并没有以科学的方式意识到不同微生物和酶在生产不同类型奶酪中的作用。但他们从经验中知道，如果你将牛奶或“奶酪预制”混合物保持在一定的温度或特定的环境中，事情就会以某种方式发生。法国的羊乳干酪洞穴就是一个例子，在人们确切知道为什么它们会产生这种效果之前，几个世纪以来，这个地方一直被用来催熟某种奶酪。


十九世纪，随着对微生物的了解不断增加，奶酪制作又向前迈出了一大步。一旦确切地知道哪些微生物参与了奶酪生产的不同阶段，以及不同微生物的存在如何影响味道，就可以有意地引入它们，并使该过程工业化。


奶酪开始在工厂大规模生产，尽管在农场乳制品厂工作的小生产商仍然存在，并且至今仍然存在。奶酪制作在很大程度上进入了技术和工业流程的世界，尽管如此，因为目的仍然是生产人们喜欢吃的东西，所以人类的判断仍然发挥着重要作用。人们仍然会在不同阶段品尝新鲜的奶酪，看看它的进展情况，并可能添加一些这样或那样的东西来改善最终的味道。无论生产规模如何，艺术与技术一起仍然有发展的空间。




---

== 5

1. All cultures change, even modern ones. As a matter of fact, change occurs most rapidly in modern cultures, since science brings us so many new discoveries every day. It is rather difficult to follow these changes clearly, since they happen so fast. The civilization that I will discuss today is easier to observe.


2. No formal history was written for these early Indians, but Navajo Indians who came along later found evidence of their great civilization. The Navajos called these prehistoric people 'the Anasazi', which means, 'the Ancient Ones'.


3. Descendants of the Anasazi still live in the Southwest, and many aspects of their culture are similar to ancient times. Today these people are called Pueblo Indians.


4. There are four different time periods in the development of the Anasazi. Scientists have looked for the one most important theme in this story, a kind of unifying idea to organize all the facts. The most critical and influential improvement in their lives was the way they used containers to cook, store, and carry food and water.


5. The most important job of the man in this society was to learn, teach, and perform the religious ceremonies associated with farming. Women worked in the fields and prepared all the food. Women also wove baskets out of yucca fibers.


6. We don't know what the final problem was. It might have been enemy attack, sickness, lack of rain, or over-farmed soil. But in the year 1300 the last of the Anasazi left the cliff dwellings, never to return again. They left behind their beautiful pueblos, which still stand as a monument to them.

所有文化都会发生变化，即使是现代文化。事实上，现代文化中的变化发生得最快，因为科学每天都给我们带来许多新发现。清楚地跟踪这些变化相当困难，因为它们发生得太快了。我今天要讨论的文明更容易观察。


没有为这些早期印第安人写下正式的历史，但后来出现的纳瓦霍印第安人发现了他们伟大文明的证据。纳瓦霍人称这些史前民族为“阿纳萨齐人”，意思是“古代人”。


阿纳萨齐人的后裔仍然生活在西南部，他们的文化的许多方面与古代相似。今天这些人被称为普韦布洛印第安人。


阿纳萨齐的发展经历了四个不同的时期。科学家们一直在寻找这个故事中最重要的主题，即一种组织所有事实的统一思想。他们生活中最关键和最有影响力的改进是他们使用容器来烹饪、储存和携带食物和水的方式。


在这个社会中，男人最重要的工作是学习、教授和执行与农业相关的宗教仪式。妇女们在田里干活并准备所有的食物。妇女还用丝兰纤维编织篮子。


我们不知道最后的问题是什么。可能是敌人的攻击、疾病、缺雨或过度耕种的土壤。但在 1300 年，最后一批阿纳萨齐人离开了悬崖住宅，再也没有回来。他们留下了美丽的普韦布洛，这些普韦布洛至今仍然矗立着，作为他们的纪念碑。

---
