
= step 2 - Lesson 21
:toc:
:sectnums:

---



Lesson 21



== part


Stuart: What did you do last night then? Did you work all night?


Judy: Yes, I did some work (Yes) but erm ... I watched a bit of TV ... (Uh-huh) got to relax, you know.


Stuart: Did you watch the football?


Judy: No, no I didn't. I can't bear football.


Stuart: Really?


Judy: Yes. I really hate it. (Yes) Well, actually, just before the football came on, I switched over (Yes) just to ... just to protest.


Stuart: What did you see then?


Judy: Well, I saw the programme before ... just the end of a film (Uh-huh) that was on before the football. It looked quite good actually. It's a shame I didn't erm ... switch on earlier. It was some kind of love story ... with Dustin Hoffman, you know, the erm ...


Stuart: The Graduate?


Judy: That's it. The Graduate.


Stuart: Yes. I know. I've seen that. (Yes) Yes, good ... good film.


Judy: Yes, and nice music. (Mm-mm) And then, when the football came on I turned over.


Stuart: Terrible, terrible!


Judy: I hate it! I really can't stand it.


Stuart: It was a great game!


Judy: Yes? (What did) Who was playing?


Stuart: England of course. (Oh) What did you see then that was more important than football?


Judy: Foxes. Yes, a good programme on foxes. (Uh-huh) Yes, they spent ages watching these foxes in a house. (Yes) They were watching them all night and these little baby foxes ... it was tremendous.


Stuart: Yes, sounds all right.


Judy: Yes, it was good; better than football ... and then, then I turned over, back to the other channel (Mm-mm) to see who won the football, but I missed it and I just saw the beginning of the News and packed up and went to bed.


Stuart: Well, I'm sorry you missed it. It was a good game.


Judy: Yes? Who did win?


Stuart: England, of course. Who do you think? (Ah) Six nil. (Yes) Yes.


Judy: Must have been quite good then!


Stuart: Yes, it was good, actually. It was very good. (Mm)


斯图尔特：那你昨晚做了什么？你工作了一整夜吗？


朱迪：是的，我做了一些工作（是的）但是呃……我看了一点电视……（嗯嗯）必须放松，你知道。


斯图尔特：你看足球赛了吗？


朱迪：不，不，我没有。我无法忍受足球。


 斯图尔特：真的吗？


朱迪：是的。我真的很讨厌它。 （是的）嗯，实际上，就在足球比赛开始之前，我切换了（是的）只是为了……​只是为了抗议。


斯图尔特：然后你看到了什么？


朱迪：嗯，我之前看过这个节目……只是足球比赛之前播放的电影的结尾（嗯嗯）。实际上看起来相当不错。很遗憾我没有早点打开。这是某种爱情故事……与达斯汀霍夫曼，你知道，呃……​


  斯图尔特：毕业生？


朱迪：就是这样。研究生。


斯图尔特：是的。我知道。我已经看到了。 （是的）是的，好……好电影。


朱迪：是的，还有美妙的音乐。 （嗯嗯）然后，当足球比赛开始时，我翻了个身。


斯图尔特：太可怕了，太可怕了！


朱迪：我讨厌它！我实在是受不了了。


斯图尔特：这是一场很棒的比赛！


朱迪：是吗？ （做了什么）谁在玩？


斯图尔特：当然是英格兰。 （哦）你当时看到什么比足球更重要？


朱迪：狐狸。是的，关于狐狸的好节目。 （嗯哼）是的，他们花了很长时间在房子里观察这些狐狸。 （是的）他们整晚都在看着这些小狐狸……太棒了。


斯图尔特：是的，听起来不错。


朱迪：是的，很好；比足球更好......然后，然后我翻了个身，回到另一个频道（嗯嗯）看看谁赢得了足球，但我错过了，我只看到了新闻的开头，然后收拾好东西上床睡觉。


斯图尔特：嗯，很抱歉你错过了。这是一场精彩的比赛。


朱迪：是吗？谁赢了？


斯图尔特：当然是英格兰。你认为是谁？ （啊）六零。 （是的是的。


朱迪：当时一定很不错吧！


斯图尔特：是的，实际上很好。非常好。 （毫米）



---

== part

Commentator: It's Carter to serve — he needs just one more point. He serves. AND SMITH MISSES! WHAT A GREAT SERVE! ... So the championship goes to 19-year-old Harry Carter. Who d've believed it a week ago? Poor old Smith just shakes his head in bewilderment. Well, well! What a way to finish it off! ... And now I'll hand you over to Peter Plumber, who's on court waiting to interview the two finalists.


Plumber: Thank you, David. Well Harry, congratulations on a marvellous victory. You were on tremendous form.


Carter: Thank you, Peter. Nice of you to say so. You know, well, I think I won because, well, I just knew all along I was in with a good chance.


Plumber: Yes, you certainly were pretty convincing today, but what about the earlier rounds? Any nervous moments?


Carter: Well, you know, I was a bit nervous against Jones when he took the lead in the second set, but then ... er ...


Plumber: Yes, that was in the quarter-finals, wasn't it? And of course you met Gardener in the next round, didn't you? Er ... the score was ... er ... 6-4, 7-5, wasn't it?


Carter: Yes, that was quite a tough match, I suppose, but ... er ...


Plumber: Anything else you'd like to add?


Carter: Well, I would like to say how sorry I am for John Fairlight not making it past the quarter-finals. He's unbeatable, you know, on his day, and ... er ... I'd also like to say what a terrific job the officials here have done you know, the ballboys and linesmen and umpires and so on. You know ... er ... lots of players have been complaining, but ... er ...


Plumber: Well, that's great. Harry, Well done again. And now let's have a quick word with the runner-up to the title, Mark Smith. If you just stand over here, Mark ... that's right ... Well, bad luck, Mark. It wasn't really your day, was it? I mean, what a terrible final set! Anyway, the less said about that the better, as I'm sure you'll agree.


Smith: Yeah, but you know, I did pretty well to beat Hutchins in the semis and ... er ... what's his name? ... Brown in the quarter-finals. And, I mean, what a terrible umpire, eh? I mean, half of Carter's points were on ... er ... doubtful decisions, weren't they?


Plumber: Well, that's probably a bit of an exaggeration, but anyway it's time for us to leave the tournament now at the end of a tremendously exciting week, and I hand you back to the studio in London.

评论员：卡特发球——他只需要再拿一分。他服侍。史密斯失手！多么棒的服务啊！ ……​所以冠军归属于 19 岁的哈利·卡特。一周前谁会相信呢？可怜的老史密斯只是困惑地摇摇头。好吧！这是多么好的一种方式来结束它啊！ ......现在我将把你们交给彼得·普鲁伯（Peter Plumber），他正在法庭上等待采访两位决赛入围者。


水管工：谢谢你，大卫。好吧，哈利，祝贺你取得了惊人的胜利。你的状态非常好。


卡特：谢谢你，彼得。你能这么说真是太好了。你知道，我想我赢了，因为，我一直都知道我有很好的机会。


水管工：是的，你今天确实很有说服力，但是前几轮呢？有紧张的时刻吗？


卡特：嗯，你知道，当琼斯在第二盘取得领先时，我对他有点紧张，但后来……呃……​


水管工：是的，那是在四分之一决赛中，不是吗？当然，你在下一轮中遇到了加德纳，不是吗？呃……比分是……呃……6-4、7-5，不是吗？


卡特：是的，我想那是一场相当艰难的比赛，但是……呃……​


水管工：您还有什么要补充的吗？


卡特：嗯，我想说我对约翰·费尔莱特没有进入四分之一决赛感到非常遗憾。你知道，在他的日子里，他是无与伦比的，而且……呃……我还想说，这里的官员们做了多么出色的工作，你知道，球童、边裁和裁判员等等。你知道……呃……很多玩家一直在抱怨，但是……呃……​


水管工：嗯，那太好了。哈利，又干得好。现在让我们与亚军马克·史密斯简单聊聊。如果你只是站在这里，马克……那就对了……好吧，运气不好，马克。这真的不是你的日子，不是吗？我的意思是，最后一盘多么糟糕啊！不管怎样，对此说得越少越好，我相信你会同意的。


史密斯：是的，但是你知道，我在半决赛​​中击败哈钦斯表现得很好，而且……呃……他叫什么名字？ ......布朗在四分之一决赛中。而且，我的意思是，多么糟糕的裁判啊，嗯？我的意思是，卡特一半的观点是关于……呃……可疑的决定，不是吗？


水管工：嗯，这可能有点夸张，但无论如何，在令人兴奋的一周结束后，我们现在是时候离开比赛了，我会把你带回伦敦的工作室。



---

== part

Chairman: Good afternoon, ladies and gentlemen, I declare the meeting open, and I take it you all have a copy of the agenda, so we'll take the minutes of our last meeting as read and get straight down to business. Now, the proposal before you is that we should see if we can reduce the size of the Olympic Games in any way and thereby ease the burden placed on the host city. We all know that each time we hold the Games this burden increases because of the vast undertaking it is to host them. Today, however, I only want to sound out your opinion of this proposal, so this is really no more than an exploratory meeting.


Mrs. Armstrong: Could I say something straight away, Mr. Chairman?


Chairman: Yes, Mrs. Armstrong.


Mrs. Armstrong: I can't accept your proposal at all on the grounds that I feel that to reduce the size of the Olympic Games would seriously damage their character, detract from their universal appeal and penalize certain countries if we start arbitrarily throwing things out before ...


Herr Müller: Yes, Mrs. Armstrong, if I may interrupt you for a moment. I think we all sympathize with your point of view, but we mustn't overlook the main point of this meeting put forward by the Chairman, which is to see if we can cut down the programme a bit, without in any way damaging the overall appeal of the Games, so let's not reject the proposal out of hand before we've had a chance to discuss it.


Mrs. Armstrong: Very well, Herr Müller, but I'd like to state here and now that I'm totally opposed to any reduction in the number of events in the Games.


Chairman: Your objections will be noted, Mrs. Armstrong, but to get back to the point of the meeting, could I hear from the rest of you what you feel? Sr. Cordoba, for example, what's your opinion?


Sr. Cordoba: Reluctant as I am to alter the composition of the Olympic Games, I can see the point that in terms of space and financial demands, the host city is subjected to a lot of difficulty. The costs seem to soar phenomenally every time we stage the Olympics, so we might be able to make one or two savings here and there. There is, for instance, quite a strong lobby against boxing because of its apparently violent nature so I did wonder if ...


Mrs. Armstrong: But that is one of the most popular sports in the world, and one of the oldest.


Sr. Cordoba: Agreed, but people get a lot of boxing on their television screens all the year round, so I was just thinking that we might be able to drop that from the programme. Football, too, is another thing which already enjoys a lot of television coverage, and as it takes up a lot of space accommodating all the football pitches, mightn't we also perhaps consider dropping that too?


Mrs. Patel: Mr. Chairman ...


Chairman: Yes, Mrs. Patel.


Mrs. Patel: I wholeheartedly endorse what Sr. Cordoba said about boxing and football. In my opinion we should concentrate on some of the more unusual sports which are rarely seen on our screens such as fencing and archery, for a change, since it is on TV that the majority of people watch the Games.


Herr Müller: Perhaps we could cut out hockey along with football because, relatively speaking, that too takes up a lot of space, as measured against its universally popular appeal.


Mrs. Patel: I can see your point, Herr Müller, and as one of the basic tenets of the Olympic Games is individual excellence, I feel we ought to concentrate on those sports which really are a true test of the individual, I, therefore, suggest we cut out — that is, if we go ahead with this idea — the team games such as basketball, volleyball, football and hockey.


Mrs. Armstrong: But then you're sacrificing some of the most interesting items in the programme. People like to watch team games as well as take part in them; it'll be very dull without them.


Chairman: I think Mrs. Armstrong has made a very valid point. We ought to keep some of the team games, although I am inclined to agree with what has been said about football.


Sr. Cordoba: There's one thing I would like to say about this and that is to suggest that we could remove from the programme sports like sailing and canoeing and possibly the equestrian events, where the test is not so much of the stamina of the competitor but of his skill in handling the boat or whatever.


Mrs. Armstrong: What about the pentathlon, then? Riding is one part of that, so we are going to need facilities to cater for that in any case, so why not use them for horse-riding as well — or do you think we should axe that too?


Chairman: Well, let's not get too heated about it, as this is only a preliminary discussion about possibilities and we are not yet in a position to make any final decisions. I will, however, briefly summarize what has been said so far, as I understand it. Mrs. Armstrong is totally opposed to reducing the size of the Games in any way at all. There is one body of opinion in favour of removing from the Games those sports which are already well represented in other international contests and in the media. Another strand of thought is that we should concentrate on individual excellence by cutting out the team games featured in the programme, and Mrs. Patel suggested we ought to focus attention on the more unusual sports in the programme which do not normally gain so much international attention. Sr. Cordoba also brought up the idea that we could drop boxing because of its seemingly violent nature. There was also an opinion voiced that we might exclude events where the skills of a competitor in handling a horse or yacht, for example, were being tested, rather than the stamina of the individual himself, as is the case with, say, athletics. Well, it is quite clear that we shall need to discuss this further, but in the meantime I think we'd better move on to something else ...



主席：下午好，女士们、先生们，我宣布会议开始，我想你们都已经拿到了议程副本，所以我们将宣读上次会议的记录，然后直接进入正题。现在，摆在你们面前的建议是，我们应该看看是否可以以某种方式缩小奥运会的规模，从而减轻主办城市的负担。我们都知道，每次举办奥运会，由于主办奥运会的任务艰巨，这种负担都会增加。但今天我只是想听听大家对这个建议的看法，所以这实际上只是一次探索性的会议。


阿姆斯特朗夫人：主席先生，我可以马上说些什么吗？


主席：是的，阿姆斯特朗夫人。


阿姆斯特朗夫人：我根本不能接受你的建议，因为我觉得缩小奥运会的规模会严重损害奥运会的性质，削弱其普遍吸引力，如果我们开始随意丢弃东西，还会对某些国家造成惩罚之前……​


穆勒先生：好的，阿姆斯特朗夫人，请允许我打扰一下。我想我们都同意你的观点，但是我们不能忽视主席提出的这次会议的要点，就是看看我们是否可以在不损害整体的情况下，把计划削减一点。奥运会的吸引力，所以在我们有机会讨论之前，我们不要立即拒绝该提议。


阿姆斯特朗夫人：很好，穆勒先生，但我现在想在此声明，我完全反对减少奥运会比赛项目的数量。


主席：阿姆斯特朗夫人，我们会注意到您的反对意见，但回到会议的重点，我能听听你们其他人的感受吗？例如，科尔多瓦先生，您有何看法？


科尔多瓦先生：虽然我不愿意改变奥运会的构成，但我看到主办城市在空间和资金需求方面遇到了很多困难。每当我们举办奥运会时，成本似乎都会大幅飙升，因此我们也许可以在这里或那里节省一两笔费用。例如，有一个相当强大的游说团体反对拳击，因为它具有明显的暴力性质，所以我确实想知道……​


阿姆斯特朗夫人：但这是世界上最受欢迎的运动之一，也是最古老的运动之一。


科尔多瓦先生：同意，但是人们一年四季都会在电视屏幕上看到很多拳击比赛，所以我只是想我们也许可以从节目中删除它。足球也是另一件已经得到大量电视报道的项目，由于它占用了所有足球场的大量空间，我们是否也可以考虑放弃它？


帕特尔夫人：主席先生……​


主席：是的，帕特尔女士。


帕特尔夫人：我完全赞同科尔多瓦先生关于拳击和足球的言论。在我看来，我们应该专注于一些在我们的屏幕上很少看到的更不寻常的运动，例如击剑和射箭，以进行改变，因为大多数人是通过电视观看奥运会的。


穆勒先生：也许我们可以把曲棍球和足球一起取消，因为相对而言，与它普遍受欢迎的吸引力相比，曲棍球也占据了很大的空间。


帕特尔夫人：我明白你的观点，穆勒先生，由于奥运会的基本原则之一是个人卓越，我认为我们应该专注于那些真正考验个人的运动，因此，我，建议我们取消——也就是说，如果我们继续这个想法——篮球、排球、足球和曲棍球等团体比赛。


阿姆斯特朗夫人：但是这样你就牺牲了节目中一些最有趣的项目。人们喜欢观看团队比赛，也喜欢参与其中；没有它们就会很乏味。


主席（以英语发言）：我认为阿姆斯特朗夫人的观点非常有道理。我们应该保留一些团队比赛，尽管我倾向于同意关于足球的说法。


科尔多瓦先生：对此我想说一件事，那就是建议我们可以从项目中删除帆船和皮划艇等运动项目，可能还包括马术项目，这些项目不太考验运动员的耐力。而是他操纵船或其他什么的技巧。


阿姆斯特朗夫人：那么五项全能呢？骑马是其中的一部分，所以无论如何我们都需要设施来满足这一需求，所以为什么不将它们也用于骑马——或者你认为我们也应该砍掉它呢？


主席：好吧，我们不要太激烈，因为这只是对可能性的初步讨论，我们还不能做出任何最终决定。不过，我将根据我的理解，简要总结一下到目前为止所讲的内容。阿姆斯特朗夫人完全反对以任何方式缩小奥运会的规模。有一种观点赞成将那些已经在其他国际比赛和媒体中得到充分体现的体育项目从奥运会中删除。另一种想法是，我们应该通过取消节目中的团队比赛来专注于个人卓越，帕特尔夫人建议我们应该将注意力集中在节目中更不寻常的运动上，这些运动通常不会获得如此多的国际关注。科尔多瓦修女还提出了我们可以放弃拳击运动的想法，因为它看似暴力。还有一种观点认为，我们可能会排除那些测试参赛者操控马匹或游艇的技能的赛事，而不是测试个人自身耐力的赛事，例如田径比赛。嗯，很明显我们需要进一步讨论这个问题，但与此同时我认为我们最好转向其他事情......​



---

== part

1. The houses they lived in were not meant to be permanent dwellings; as a matter of fact, we have no remaining evidence of their houses. Probably in the summertime they lived up on the mesa top near their fields, in temporary structures made of poles and brush. In winter they most likely moved down to the caves in the cliffs for warmth and protection against the snow.


2. People were experimenting and changing their methods of potting; the broken pieces are evidence of the steps in the process.





The first attempt at pottery came as women mixed clay, a kind of dirt, with water to make pots. When the clay dried, however, it crumbled and fell apart. Clearly this would not work.





The second idea was to add extra material to bind the clay together: grass, straw, or pieces of bark. This held the pot together very well until it was set on the fire. Then the binding material burned up, leaving a pot full of holes.





Again the Anasazi women tried to find the secret of success. They added sand or volcanic grit to the clay to make it harder, and they baked the pots before using them. This final step proved to be successful, and it is the basic method which is still used today.


3. The pots which the women made this way were far superior to baskets for carrying, cooking, and storing food and water. Now the people could add beans, a rich source of protein, to their diet. Water could be stored safely over long periods. Life became much easier, and so effort could now be spent on other developments.


4. Their culture developed to its height, and the main improvement was in housing. The earlier pit houses were modified to one-story row houses, made with pieces of stone. Several separate buildings stood near each other like a small village. Some villages were as large as several hundred rooms and could contain as many as a thousand people. The name for this kind of house and for these Indians is "Pueblo", which is the Spanish word for "village".

他们居住的房子并不是永久性的住所；事实上，我们没有留下他们房屋的证据。可能在夏天，他们住在田地附近的台地上，住在用柱子和灌木丛搭建的临时建筑里。在冬天，它们很可能会搬到悬崖上的洞穴取暖和防雪。


人们正在尝试并改变他们的盆栽方法；碎片是该过程中步骤的证据。


第一次尝试陶器时，妇女们将粘土（一种泥土）与水混合来制作陶器。然而，当粘土干燥时，它就会碎裂并散开。显然这是行不通的。


第二个想法是添加额外的材料将粘土粘合在一起：草、稻草或树皮片。这将锅很好地固定在一起，直到它被放在火上。然后粘合材料就烧掉了，留下一个满是洞的锅。


阿纳萨齐妇女再次试图寻找成功的秘诀。他们在粘土中添加沙子或火山砂以使其变得更硬，并在使用之前烘烤罐子。这最后一步被证明是成功的，并且是至今仍在使用的基本方法。


妇女们用这种方法制作的锅在携带、烹饪、储存食物和水方面远远优于篮子。现在人们可以在饮食中添加富含蛋白质的豆类。水可以安全地长期储存。生活变得更加轻松，因此现在可以将精力花在其他发展上。


他们的文化发展到了顶峰，主要的进步是在住房方面。早期的坑屋被改造成单层排屋，用石头建造。几栋独立的建筑毗邻而立，就像一个小村庄。有的村子大到有几百个房间，最多能容纳上千人。这种房屋和这些印第安人的名字是“Pueblo”，在西班牙语中是“村庄”的意思。

---
