
= step 2 - Lesson 16
:toc:


---




Lesson 16



== 1

BBC interviewer: It's probably true to say that women have been affected more than men by recent changes in the way we actually live. Over a hundred years ago people began to question whether men were really so much wiser, stronger, altogether more sensible and simply better than women as the laws of the country made out. In the end women got the vote, and very recently — in 1975 — the Sex Discrimination Act was passed.





 But it's doubtful whether legislation has changed the way we women actually think. A lot is heard about the dilemma of women's two roles. How can a woman be a wife and mother and have a full-time job as well?





In this new series we are going to try to find out what people are really thinking and feeling about this problem, and how it affects their personal lives. In the studio with me today is Mrs. Marina Spiden, who recently experienced the problem of having too much to do at home. With Mrs. Spiden are her husband Brian, her mother Mrs. Vera Cresswell and Mr. Tom Penman, their local newsagent. Mrs. Spiden ... tell us what happened will you?


Mrs. Spiden: Well ... you just said it ... the problem of having too much to do at home. I do an afternoon job so I have to get the housework and shopping ... er ... done in the morning. And one morning you see ... er ... I just couldn't stand it no more. The ... the baby was bawling her head off. Jimmy — that's my little boy ... he's two — had thrown the radio out of the window ...


Interviewer: Really!


Mrs. Spiden: Yes really ... The dog ... you know ... had made a ... a mess on the carpet. And there was Brian — my husband — there he was snoring a way on the settee. Didn't lift a finger he didn't ... not a finger to help me.


Mr. Spiden: Now now love ... Don't get all her up about it again ... I mean that's your side of the story ...


Interviewer: Of course Mr. Spiden ... We'd like to hear your side later. So ... what did you do about it?


Mrs. Spiden: Well ... What do you do when you've got something you're fed up with or ... or ... you don't want like ... You put them up for sale don't you? And that's exactly what I did do. Put the whole damn lot of 'em up for sale.


Interviewer: The family you mean.


Mrs. Spiden: Yes ... the family ... including the dog.


Mr. Penman: She came into my shop that very day and 'Tom', she says, 'I've just about had enough of it. I'm sick of slaving for a husband what sleeps all day. So here you are,' she says. And she gives me an advert on a card to put up in the window of the paper shop.


Interviewer: What did it say?


Mr. Penman: I've got it here.


Interviewer: Read it for us will you?


Mr. Penman: 'For Sale — One house-trained dog, one reasonably trained boy of two years, one baby girl of two weeks and one man that needs training. Any offers considered. Apply within.'


Interviewer: And were there any offers?


Mrs Cresswell: It was me what wrote that advert. You see ... I live with Marina and Brian ...


Mr Spiden: She and her dog ...


Mr. Penman: Oh yes. Caused quite a stir it did. I should say I had inquiries from ... from about a couple of dozen housewives in all.


Interviewer: And what offers did they make?


Mr. Penman: Well one woman offered 25p. She said that's all a man was worth.


Interviewer: What about you Mr. Spiden? What was your reaction to the advertisement?


Mr. Spiden: Well ... you can imagine ... My wife told me about it but I thought she was joking. Little did I realize ... I was bloody furious when I saw it there. It wasn't till next morning. We live upstairs of the paper shop and when I come down to go on my milk round ...


Interviewer: Yes of course ... you're a milkman ...


Mrs. Spiden: That's right. I often have a dekko at the adverts Tom puts up. And when I saw that one sort of ... staring me in the face ... I nearly blew me top.


Interviewer: What did you do?


Mrs. Cresswell: I'll tell you what he did. He came and blamed me for everything.


Mr. Spiden: Well it was you ... wannit ... that egged her on. It was you that wrote the advert.


Mr. Penman: It was a big joke really. Just that Brian took it all the wrong way. Know what he did? When he come off his milk round he barges into the shop and he says, 'Take that bloody advert out and put one in for me. Ask some kind taxi-driver or someone to come and take my mother-in-law back to Birmingham.'


Mr. Spiden: But it's all blown over now ... innit. It's done us a world of good in a way. We're the best of friends again. Even the dog started to ...

BBC 采访者：可以这么说，最近我们实际生活方式的变化对女性的影响比男性更大。一百多年前，人们开始质疑男性是否真的像国家法律所规定的那样比女性更聪明、更坚强、更明智、更好。最终，女性获得了投票权，并且最近（1975 年）《性别歧视法案》获得通过。


但立法是否改变了我们女性的实际思维方式值得怀疑。关于女性两种角色的困境，人们耳熟能详。一个女人怎样才能既为人妻为人母，又能有一份全职工作呢？


在这个新系列中，我们将尝试找出人们对这个问题的真实想法和感受，以及它如何影响他们的个人生活。今天和我一起在工作室的是玛丽娜·斯皮登女士，她最近遇到了家里有太多事情要做的问题。与斯皮登夫人在一起的还有她的丈夫布莱恩、她的母亲维拉·克雷斯韦尔夫人和当地的报刊经销商汤姆·彭曼先生。斯皮登夫人……告诉我们发生了什么，好吗？


斯皮登夫人：嗯……你刚才说了……家里有太多事情要做的问题。我下午工作，所以我必须在早上完成家务和购物……呃……​。有一天早上，你看到……呃……我再也无法忍受了。 ……婴儿正在嚎啕大哭。吉米——那是我的小男孩……他两岁了——把收音机扔出了窗外……​


  采访者：真的！


斯皮登夫人：是的，真的……那只狗……你知道……把地毯弄得……一片狼藉。布莱恩——我的丈夫——坐在长椅上打呼噜。他没有举起一根手指……没有一根手指来帮助我。


斯皮登先生：现在，现在爱……别再让她为这件事生气……我的意思是，这就是你的故事……​


采访者：当然，斯皮登先生……我们想稍后听听您的看法。那么……你对此做了什么？


斯皮登夫人：嗯……当你有一些你厌倦了的东西，或者……或者……你不想要的东西时，你会怎么做……你把它们拿出来出售，不是吗？这正是我所做的。把所有该死的东西都拿出来出售。


采访者：你指的是家庭。


斯皮登夫人：是的……家人……包括狗。


彭曼先生：那天她来到我的店里，‘汤姆'，她说，‘我已经受够了。我厌倦了为一个整天睡觉的丈夫做奴隶。所以你来了，”她说。她给了我一张卡片上的广告，让我张贴在造纸店的橱窗里。


采访者：上面写了什么？


彭曼先生：我这里有。


采访者：你读给我们听好吗？


彭曼先生：“待售——一只经过家庭训练的狗，一只经过适当训练的两岁男孩，一只两周大的女婴和一名需要训练的男人。考虑任何优惠。内申请。


面试官：有收到offer吗？


克雷斯韦尔夫人：那则广告是我写的。你看……我和玛丽娜和布莱恩住在一起……​


斯皮登先生：她和她的狗……​


彭曼先生：哦，是的。确实引起了不小的轰动。我应该说我收到了来自......总共大约几十名家庭主妇的询问。


采访者：他们提出了哪些报价？


Penman 先生：嗯，一位女士出价 25 便士。她说这就是一个男人的全部价值。


采访者：斯皮登先生，你呢？您对广告有何反应？


斯皮登先生：嗯……你可以想象……我的妻子告诉了我这件事，但我认为她在开玩笑。我几乎没有意识到……当我在那里看到它时，我非常愤怒。直到第二天早上。我们住在造纸店的楼上，当我下来去喝牛奶时……​


采访者：是的，当然……​你是一名送奶工……​


斯皮登夫人：没错。我经常在汤姆贴的广告上看到 dekko。当我看到那种……盯着我的脸时……我几乎要崩溃了。


采访者：你做了什么？


克雷斯韦尔夫人：我会告诉你他做了什么。他来了，把一切都归咎于我。


斯皮登先生：嗯，是你……想要……怂恿她。广告是你写的。


彭曼先生：这真是一个天大的笑话。只是布赖恩完全错误地理解了这一切。知道他做了什么吗？当他喝完牛奶后，他闯进商店说：‘把那该死的广告拿掉，给我贴一个。请好心的出租车司机或其他人来接我岳母回伯明翰。”


斯皮登先生：但现在一切都烟消云散了……没错。在某种程度上，它为我们带来了一个美好的世界。我们又成了最好的朋友了。就连狗也开始……​




---

== 2

Interviewer: I'm going to talk to you now about the suffragette movement. Were you yourself ever a suffragette?


Mrs. Bruce: No, I did not approve of suffragettes. I did not want to have the vote. I felt the man of the house should be in charge of that section. And the woman, of course, to look after the home and the children. I think that voting was unnecessary, at that time. But I'm not going to say now, that perhaps it has had its advantages.


Interviewer: How common was your attitude at the time that the suffragettes were being militant?


Mrs. Bruce: Oh, I was very much against them. I'd be highly insulted if anybody called me a suffragette. I remember walking with my governess down Downing Street just past Number 10 and they chained themselves to the railings. Of course, I had a good laugh but I thought it wasn't going to be me.


Interviewer: Were they a popular movement in their day?


Mrs. Bruce: Well, with a certain number of course. And they tried very hard and eventually they got the vote, er through their efforts, so I suppose their efforts were good in quite a lot of ways. Er, I think women in Parliament — there aren't many, but those that've been there have done a lot of good.


Interviewer: So you think in the long term ...


Mrs. Bruce: In the long term, no harm was done. As long as their demonstrations were peaceful.


Interviewer: Do you think it would matter very much if women didn't, hadn't achieved the vote, if they hadn't got the vote at all and still didn't have it?


Mrs. Bruce: I don't think it would've made a great deal of difference, no, but there are certain things they've done — those that've been Members of Parliament — that have been very useful in helping women in their jobs, in other vocations. I think it's good that it happened. But I wish it happened a little bit more peacefully, perhaps.


Interviewer: What sort of things can you remember, what other sorts of demonstrations do you remember?


Mrs. Bruce: Marching, they were marching. But of course those were much more peaceful days, nobody interfered with their marches. There were a few boos here and there and a lot of clapping. Yes.


Interviewer: Did you, did you actually know any suffragettes yourself?


Mrs. Bruce: Well, my friends, my close friends, were not suffragettes but I had one or two friends, not very close friends, that were. And we used to have great arguments and I used to say I didn't want the vote, I don't want to vote.


Interviewer: How did they react to that?


Mrs. Bruce: They didn't like that. They said I ought to join the movement but I said, no I don't want to vote.


Interviewer: But, and yet you've done so many exciting things. You've done so many things that in your day, were probably the exclusive preserve of the man


Mrs. Bruce: Well, yes. But voting didn't make any difference because that's a political thing, voting, I never, I don't care about women entering into politics particularly. Ah, no harm's been done with the few that have entered the House of Commons but, in fact, some have done a great deal of good. But that's quite different to beating men at their own job. Now that's nothing to do with votes. Now, for instance, I always got a great thrill on the race track at Brooklands, if I could beat, well, Sir Henry Seagrave, for instance, in a race, I never did beat him but I did beat Frazer Nash, a famous racing driver in a race, and I was thrilled to death. I thought that was super.


Interviewer: So you don't mind actually joining men in their world of work and sport but you're happy to leave politics to them.


Mrs. Bruce: No. I would rather really leave politics to them.

采访者：我现在要和你谈谈妇女参政运动。您自己曾经是妇女参政论者吗？


布鲁斯夫人：不，我不赞成妇女参政权论。我不想投票。我觉得这部分应该由男主人负责。当然，女人还要照顾家庭和孩子。我认为当时投票是没有必要的。但我现在不会说，也许它有它的优点。


采访者：当时您对妇女参政论者激进的态度有多普遍？


布鲁斯夫人：哦，我非常反对他们。如果有人称我为妇女参政论者，我会受到极大的侮辱。我记得我和我的家庭女教师沿着唐宁街散步，刚过了十号，他们就把自己锁在栏杆上。当然，我笑得很开心，但我认为那不会是我。


采访者：他们在当时是一个流行的运动吗？


布鲁斯夫人：嗯，当然有一定数量。他们非常努力，最终他们得到了选票，呃通过他们的努力，所以我认为他们的努力在很多方面都是好的。呃，我认为议会中的女性人数不多，但那些曾经在那里的人做了很多好事。


采访者：所以你认为从长远来看……​


布鲁斯夫人：从长远来看，没有造成任何伤害。只要他们的示威是和平的。


采访者：你认为如果女性没有、没有获得投票权、如果她们根本没有获得投票权并且仍然没有投票权，这会很重要吗？


布鲁斯夫人：我不认为这会产生很大的影响，不，但是他们所做的某些事情——那些曾经担任过议会议员的人——在帮助妇女实现这一目标方面非常有用。他们的工作，其他职业。我认为这件事发生了很好。但我希望事情能更和平地进行，也许吧。


采访者：你能记得什么样的事情，你还记得哪些其他类型的示威？


布鲁斯夫人：游行，他们在游行。但当然，那些日子要和平得多，没有人干扰他们的游行。到处都是一些嘘声和很多鼓掌声。是的。


采访者：您自己真的认识妇女参政论者吗？


布鲁斯夫人：嗯，我的朋友，我的亲密朋友，都不是妇女参政论者，但我有一两个朋友，不是很亲密的朋友。我们曾经有过激烈的争论，我曾经说过我不想投票，我不想投票。


采访者：他们对此有何反应？


布鲁斯夫人：他们不喜欢那样。他们说我应该加入这场运动，但我说，不，我不想投票。


采访者：但是，你还是做了很多令人兴奋的事情。你做过的事情太多了，在你那个时代，这些事情可能都是男人的专属


布鲁斯夫人：嗯，是的。但投票没有任何区别，因为这是一件政治事情，投票，我从来不，我不特别关心女性进入政治。啊，进入下议院的少数人并没有造成什么坏处，但事实上，有些人做了很多好事。但这与在自己的工作中殴打男性是完全不同的。现在这与选票无关。现在，例如，在布鲁克兰的赛道上，我总是感到非常兴奋，如果我能在一场比赛中击败亨利·西格雷夫爵士，我从未击败过他，但我确实击败了著名的弗雷泽·纳什。赛车手在比赛，我激动得要死。我觉得那太棒了。


采访者：所以你并不介意真正加入男人的工作和体育世界，但你很高兴把政治留给他们。


布鲁斯夫人：不。我宁愿把政治留给他们。




---

== 3

Jan: Changes are very gradual. They're too slow. I mean if you sit under a tree long enough the apple'll fall off and you can eat it but sometimes you've got to stand up and do something. You've got to ... Um, I think the law is there to protect people. Because women were being discriminated against, it was necessary for the law to stop that, um, at least to some extent. But you can't change the way people think.


Duncan: People's discrimination is based on the fact ... a lot of it, that they don't think women are capable of making decisions or have any intelligence at all. I mean a lot of people believe that ... and if that ... provided ... once that's proved wrong, that removes the valid grounds for the discrimination and you know you ... the belief is then unjustified. You've got to stamp it out. I mean, it's as simple as that.


Keith: But just in the same way that if I want to become a managing director, I have to look at the company in which I work and prove certain elements of my behaviour or ... or my skills to these people, so must women.


Jan: Yes, but if they're not given the chance, then how can they? I mean it's very sad that the law has to be there at all. I mean that you have to say to somebody who's employing someone you must give ... you must interview men and women ... it, it seems a great shame ... you have to tell people to do that. It's also a great shame that you have to tell people not to go around murdering other people. I mean, the law's there because people do stupid things.


Duncan: As I say, the law is ... is not that you have to sort of ... I mean you basically all you have to do is give women the right to apply and the right to be considered in the same way as everybody else and if the law was effective as it should be, there'd be nothing wrong with that. I mean, what's wrong with giving women the chance to apply for a job and giving them the right to be considered on equal terms with men.


Keith: Women could always ... women could always apply.


Duncan: That's not true, though. I mean there are employers who just would not consider them.


David: A woman would not apply if the job was ... if the job advertisement was couched in such terms.


Keith: I mean ... the leading example ...


Duncan: I mean the whole point about the ... an advertisement asking for a draughtsman being against the terms of the act, is that it gives the imp ... it's implied that only men will be considered and that's why that would be a legal advertisement if you put at the bottom, um, applications from men and women will be considered ... the same with postmen and all the other jobs.


David: Interesting point. How important is the language, Jan, do you think?


Jan: I ... it's symbolic. Um, I personally don't find it particularly important. Er, if you have a meeting and you call the man or the woman who chairs the meeting the chairman, it just doesn't matter I don't think at all.


Jan：变化是非常渐进的。他们太慢了。我的意思是，如果你坐在树下足够长的时间，苹果就会掉下来，你可以吃它，但有时你必须站起来做点什么。你必须……嗯，我认为法律是为了保护人们。因为女性受到歧视，所以法律有必要制止，嗯，至少在某种程度上。但你无法改变人们的思维方式。


邓肯：人们的歧视是基于这样的事实……​很多时候，他们认为女性没有能力做出决定或根本没有任何智慧。我的意思是，很多人相信......并且如果......提供......一旦被证明是错误的，那就消除了歧视的有效理由，你知道你......那么这种信念是不合理的。你必须把它消灭掉。我的意思是，就这么简单。


基思：但就像我想成为董事总经理一样，我必须审视我工作的公司，并向这些人证明我的行为或……​或我的技能的某些要素，女性也必须如此。


Jan：是的，但是如果他们没有机会，那他们怎么能有机会呢？我的意思是，法律必须存在，这是非常可悲的。我的意思是，你必须对雇用某人的人说，你必须给予……你必须采访男人和女人……这似乎是一个很大的耻辱……你必须告诉人们这样做。你必须告诉人们不要四处谋杀他人，这也是一个巨大的耻辱。我的意思是，法律的存在是因为人们做了愚蠢的事情。


邓肯：正如我所说，法律是......并不是你必须......我的意思是你基本上所要做的就是给予女性申请的权利以及以与其他人相同的方式被考虑的权利如果法律能够发挥其应有的效力，那就没有什么问题了。我的意思是，给予女性申请工作的机会并给予她们与男性平等对待的权利有什么问题。


基思：女性总是可以……女性总是可以申请。


邓肯：但这不是真的。我的意思是有些雇主不会考虑他们。


大卫：如果这份工作……如果招聘广告是这样表述的，那么女性就不会申请。


基思：我的意思是……最典型的例子……​


邓肯：我的意思是……一则要求绘图员的广告违反了该法案的条款，它给人一种印象……这意味着只有男性才会被考虑，这就是为什么这将是一个合法的广告如果你把它放在底部，嗯，男性和女性的申请都会被考虑……与邮递员和所有其他工作一样。


大卫：有趣的一点。 Jan，你认为语言有多重要？


Jan：我……​这是象征性的。嗯，我个人觉得不是特别重要。呃，如果你开会，你把主持会议的男人或女人称为主席，我根本不认为这没关系。




---

== 4

1. When a teacher or lecturer recommends a student to read a book it's usually for a particular purpose. The book may contain useful information about the topic being studied or it may be invaluable for the ideas or views that it puts forward, and so on. In many cases, the teacher doesn't suggest that the whole book should be read. In fact, he may just refer to a few pages which have a direct bearing on the matter being discussed.


2. On Many occasions, however, the student does not come to the library to borrow a book, or even to consult a book from the shelves. He may well come to the library because it provides a suitable working environment, which is free of charge, spacious, well-lit and adequately heated.


3. Learners of English usually find that writing is the most difficult skill they have to master. The majority of native speakers of English have to make an effort to write accurately and effectively even on those subjects which they know very well. The non-native learner, then, is trying to do something that the average native speaker often finds difficult himself.


4. Students, however, often work out a sentence in their own language and then try to translate it in this way. The result is that very often the reader simply cannot understand what the student has written. The individual words, or odd phrases, may make sense but the sentence as a whole makes nonsense. The student should, therefore, always try to employ sentence patterns he knows are correct English.


5. Many students seem to think that simplicity is suspect. It is, on the contrary, a quality which is much admired in English. Most readers understand that a difficult subject can only be written up 'simply' if the writer understands it very well. A student should, therefore, organize all his points very carefully before he starts to write.


6. Non-native speakers of English, like their native counterparts, usually find that the opportunity to participate in group discussions is one of the most valuable aspects in their whole academic programme. But in order to obtain full value from this type of activity the student must be proficient in asking questions. If he isn't, then any attempt to resolve his difficulties may lead to further confusion, if not considerable embarrassment.

当老师或讲师推荐学生读书时，通常是出于特定目的。这本书可能包含有关正在研究的主题的有用信息，或者它提出的想法或观点可能非常宝贵，等等。很多时候，老师并不建议读整本书。事实上，他可能只是参考了与所讨论的问题有直接关系的几页。


然而，在很多情况下，学生来图书馆并不是为了借书，甚至不是为了从书架上查阅书籍。他很可能会来图书馆，因为图书馆提供了一个合适的工作环境，免费、宽敞、光线充足、供暖充足。


英语学习者通常发现写作是他们必须掌握的最难的技能。大多数以英语为母语的人都必须努力准确有效地写作，即使是他们非常熟悉的主题。那么，非母语学习者正在尝试做一些普通母语者自己经常觉得困难的事情。


然而，学生经常用自己的语言写出一个句子，然后尝试用这种方式翻译它。结果是，读者常常根本无法理解学生所写的内容。单个单词或奇怪的短语可能有意义，但整个句子却毫无意义。因此，学生应该始终尝试使用他知道的正确英语句型。


许多学生似乎认为这种简单性值得怀疑。相反，这是一种在英语中备受推崇的品质。大多数读者都明白，一个困难的主题只有在作者非常理解的情况下才能“简单”地写出来。因此，学生在开始写作之前应该非常仔细地组织他的所有观点。


非英语母语的人，就像他们的母语同行一样，通常发现参加小组讨论的机会是他们整个学术课程中最有价值的方面之一。但为了从此类活动中获得全部价值，学生必须熟练提问。如果他不这样做，那么任何解决他的困难的尝试都可能会导致进一步的混乱，甚至相当尴尬。

---
