
= step 2 - Lesson 29
:toc:
:sectnums:

---



Lesson 29 +

== part



Linda: Oh, yes, I remember. We were conducting a survey into the, the needs of disabled people in the borough (Yes) in which I work in London. And we got a request from an old man to go along and, and see him in connection with this survey. Well, some of the people that I'd seen on the survey before were really quite poor and lived in very bad housing conditions. (Yes) They were also ... tended to be elderly and to really have some quite bad disabilities, so I was quite prepared for, for anything I thought that I might meet. Anyway, I went along to, to this house and it was not at all what I'd expected. It was a, a large house and really had an air of fa, faded gentility about it. It was in a part of the borough which had (Really?) once been quite fashionable. Er, I knocked at the door and the old man, Mr. Sinclair, came to, to let me in and showed me into a back room, which he lived in. The rest of the house, I think, must have been shut up and he was just living in one or two rooms. (How extraordinary!) Anyway, we started the interview which I had to, to conduct with him and he was very, very willing to talk but he never stopped grumbling. He grumbled about ... young people, about the rising cost of living, about the government, about how the area had gone down, and so on and so forth. He didn't seem to have a good word to say for anybody at all. (S ... ) +
Janet: Got a real chip on his shoulder? +
Linda: Well, he was. He was a really grumpy old man and not very likeable with it. But he was ... rather frail and in his eighties and ... I just accepted that perhaps, you know, he'd had a hard life in, in some way an, and hadn't really resolved it. Anyway, I left the, er, the house and went back to the office, wrote up the interview and didn't think any more about it. And then about a week later, I got a phone call from him saying that he thought he'd left out some important things about himself (Really?) that I should know, and would I go and see him again. So I explained that it was a survey that we were doing and that it wasn't really very usual to go back and see somebody a second time, but if he felt it was really important then, of course, I would go. (Yeah) So I went along and exactly the same thing happened as had happened before. He showed me into the back room and he started grumbling again and this went on for about half an hour and I began to wonder why on earth he'd asked me to go back a second time. +
Janet: He didn't tell you anything new about himself? +
Linda: Well, he ... after about half an hour he started. He said, 'I, I expect you wonder why I've asked you to come back,' (Quite) and I said, 'Well, as a matter of fact, yes I do.' So he said, 'Well, I think I should tell you a bit about myself and perhaps explain why I, I seem to have a chip on my shoulder,' which took me aback, back a bit, you know. Anyway, apparently, he had come from a, a family which was ... really quite well-to-do but not spectacularly rich and his father had a, a small grocery business and had supported his mother and, and his two sisters. Well, his mother and father both died quite early on in his life and he took over the business (Yes) and it fell to him, of course, to support his two sisters. (Yes) Well, gradually the, the business began to, to flourish. He opened up new lines in the shops, he bought in some foreign foods and he (He ... ) acquired new premises. +
Janet: He really built the whole thing up. +
Linda: Well yes. He didn't become a multimillionaire or anything like that, but he was certainly very comfortably off. Anyway, he ... one of his sisters got married and the other sister emigrated to Australia but he himself never, never married. +
Janet: He just stayed on in the house by himself? +
Linda: He stayed on in, in this house which had been the family house for a number of years. +
Janet: Completely alone? +
Linda: Completely alone, yes. And he ... really cut himself off from his friends, or friends of the family, because he was giving all day, every day, to the growth of his business. So he kept going for a number of years but eventually, of course, he began to, to grow older and with age came arthritis (Oh dear) and ... gradually the, the condition worsened and he became more and more in pain, more and more frail but he still battled on, I think, for a number of years (Yes) but eventually he was forced to give up. And it left him completely alone. He was still, of course, well off, (Yes) but that wasn't in itself enough, and while he was telling me this he was, he was so upset because he'd remembered when telling me the excitement and the thrill he'd felt (Yes) when he was completing these transactions, of what it m, meant to be both powerful, respected and really somebody of note (Yes) in the area, whereas now he was old, (H...) frail, in pain. +
Janet: He'd lost everything. +
Linda: Yes, he had. His, his neighbours were very good to him, but it wasn't that that he wanted. (No) And I felt so ... helpless because it wasn't that he needed more money, it wasn't that he really needed visitors — he didn't particularly want visitor. (No) What he wanted was to be, to be young again and to be in a position of, of building something up and seeing the results (Yes) from it. +
Janet: Oh, what a sad story!
 +


琳达：哦，是的，我记得。我们正在对我在伦敦工作的行政区（是的）残疾人的需求进行一项调查。我们收到一位老人的请求，希望我们能一起去见见他，以完成这项调查。嗯，我之前在调查中看到的一些人确实很穷，居住条件也很差。 （是的）他们也……往往年纪较大，而且确实有一些非常严重的残疾，所以我对我认为可能遇到的任何事情都做好了准备。不管怎样，我还是去了，去了这所房子，这根本不是我所期望的。那是一栋大房子，确实有一种法式的气息，但也有一种褪色的绅士风度。它位于该行政区的一部分，（真的吗？）曾经非常时尚。呃，我敲了敲门，老人辛克莱先生过来了，让我进去，并带我进入他住的后面的房间。我想，房子的其余部分一定是关着的他只住在一两个房间里。 （多么非凡！）无论如何，我们开始了我必须与他进行的采访，他非常非常愿意说话，但他从未停止抱怨。他抱怨……年轻人、生活成本上升、政府、该地区的衰落等等。他似乎根本没有对任何人说好话。 （S…​）

珍妮特：他的肩膀上真的受伤了吗？

琳达：嗯，他是。他是一个脾气暴躁的老人，不太讨人喜欢。但他……相当虚弱，已经八十多岁了……我只是接受了这一点，也许，你知道，他在某种程度上过着艰难的生活，而且还没有真正解决这个问题。不管怎样，我离开了，呃，房子，回到办公室，写下了采访，没有再想它。大约一周后，我接到他的电话，说他认为他遗漏了一些我应该知道的关于自己的重要事情（真的吗？），我会再去见他吗？所以我解释说，这是我们正在进行的一项调查，第二次回去见某人并不常见，但如果他觉得这真的很重要，那么我当然会去。 （是的）所以我就跟着去了，结果发生了和以前一模一样的事情。他带我到后面的房间，他又开始抱怨，这种情况持续了大约半个小时，我开始想知道他到底为什么要我第二次回去。

珍妮特：他没有告诉你任何关于他自己的新事吗？

琳达：嗯，他……大约半小时后他开始了。他说，“我，我希望你想知道为什么我要你回来，”（相当）我说，“嗯，事实上，是的，我想知道。”所以他说，“好吧，我想我应该告诉你一些关于我自己的事情，或许还可以解释一下为什么我，我的肩膀上似乎有一种不满，”这让我大吃一惊，后退了一点，你知道。不管怎样，显然，他来自一个……非常富裕但不是特别富有的家庭，他的父亲有一家小杂货店，养活了他的母亲和两个姐妹。好吧，他的母亲和父亲在他生命的早期就去世了，他接管了生意（是的），当然，养活他的两个姐妹的责任就落在了他的身上。 （是）嗯，逐渐的，生意开始，蓬勃发展。他在商店里开辟了新的生产线，购买了一些外国食品，并且他（他......）购买了新的场所。

珍妮特：他真的把整个事情都建立起来了。

琳达：嗯，是的。他没有成为百万富翁或类似的人物，但他的生活确实非常舒适。不管怎样，他……他的一个姐姐结婚了，另一个姐姐移民到了澳大利亚，但他自己却从未结婚。

珍妮特：他就一个人呆在家里？

琳达：他一直住在这栋房子里，这栋房子多年来一直是他家的房子。

珍妮特：完全孤独吗？

琳达：完全孤独，是的。他……真的与他的朋友或家人的朋友隔绝了，因为他整天、每一天都在为他的生意的发展付出努力。所以他坚持了很多年，但最终，当然，他开始变老，随着年龄的增长，关节炎（哦，天哪）……​逐渐地，病情恶化，他变得越来越痛苦，越来越痛苦。而且更加虚弱，但我认为他仍然奋斗了很多年（是的），但最终他被迫放弃。这让他完全孤独了。当然，他仍然很富裕，（是的）但这本身还不够，当他告诉我他是这样的时候，他很沮丧，因为他记得当他告诉我他的兴奋和激动时当他完成这些交易时，他感觉到（是的），它意味着什么，意味着在该地区既强大，受人尊敬，又真正是值得注意的人（是的），而现在他老了，（H…​）虚弱，在疼痛。

珍妮特：他失去了一切。

琳达：是的，他有。他的，他的邻居对他很好，但是这不是他想要的。 （不）我感到很……无助，因为并不是他需要更多的钱，也不是他真的需要访客——他并不特别想要访客。 （不）他想要的是，再次年轻，处于一个位置，建立一些东西并从中看到结果（是）。

珍妮特：哦，多么悲伤的故事啊！

---

== part

Los Angeles police yesterday added a new name to the list of victims of what they believe is a new serial killer. Like the first four victims Joseph Griffin was a homeless man shot on the head while sleeping alone. NPR's Salas Wason reports from Los Angeles. +
 +

Early this month the police department sent notices to every homeless shelter about the transient killer. Staff member Marcotte Tears reads from the Xerox post near the check-in window at the Union Rescue Mission down town. +
 +
 "Four men have been shot in the head in the last three weeks. The men were all transients and sleeping alone at the time of the killings. Please tell everyone in this chapel and those along the streets to come indoors at night to any of the missions or shelters. When they are full please tell the men to group together, not to be alone at night, but huddle for safety. The lives of the men may depend upon their following these instructions." +
 +

Since that notice was distributed, police have searched their records and added five more victims to the list. Except for the victim added yesterday they are not transients, but they were all shot while out on the streets in the early morning hours. Commander William Booth, a spokesman for the police department, won't confirm it, but reportedly all the men were shot with a small caliber gun. So far Booth said the task force working on the case doesn't have many clues and only a little bit of information about the murderer. +
 +

"Frankly not nearly enough. We have a brief description: a male black, who is tall, slim, a hundred fifty to a hundred and seventy pounds, twenty-five to thirty years old. With a medium to large Afro haircut." +


The first victim was shot on September 4th, the most recent October 7th. The crime took place in several Los Angeles neighborhoods. All five homeless men killed were sleeping outside downtown. Not in the skid road area, but nearby. Although the city's transients have been urged to sleep in shelters, there are thousands more men than beds are available. And not all the homeless choose to stay in the shelters. Still most of the men at the Union Rescue Mission know about the transient killer and admit to some concern. +
 +

Los Angeles police are still looking for another serial murderer. This outside slayer is suspected of killing seventeen women, mostly prostitutes during the past three years. I'm Salas Wason in Los Angeles.


洛杉矶警方昨天在他们认为是新连环杀手的受害者名单中添加了一个新名字。与前四名受害者一样，约瑟夫·格里芬也是一名无家可归者，他在独自睡觉时头部中弹。 NPR 的萨拉斯·沃森从洛杉矶报道。


本月初，警察局向每个无家可归者收容所发出了有关这名临时杀手的通知。市中心联合救援团的工作人员 Marcotte Tears 正在看报到窗口附近复印的帖子。


“过去三周内，有四名男子头部中弹。这些人在杀戮发生时都是过路人，独自睡觉。请告诉教堂里的每个人和街上的人，晚上到室内去任何一个地方。” “任务或避难所。当他们满员时，请告诉人们聚集在一起，晚上不要独自一人，而是为了安全而挤在一起。这些人的生命可能取决于他们是否遵守这些指示。”


自该通知发出以来，警方搜查了他们的记录，并在名单上增加了五名受害者。除了昨天补充的受害者外，他们都不是过路人，但他们都是在凌晨在街上被枪杀的。警察局发言人、指挥官威廉·布斯(William Booth)不愿证实这一点，但据报道，所有男子都是被小口径枪射杀的。布斯表示，到目前为止，侦办此案的专案组还没有太多线索，只有一点点关于凶手的信息。


“坦率地说还不够。我们有一个简短的描述：一个黑人男性，身材高大，苗条，一百五十到一百七十磅，二十五到三十岁。留着中到大的非洲式发型。”

第一个受害者于 9 月 4 日被枪杀，最近一次是在 10 月 7 日。这起犯罪事件发生在洛杉矶的几个街区。所有被杀的五名无家可归者都在市中心外睡觉。不是在防滑路区域，而是在附近。尽管该市的临时住民被要求睡在避难所里，但人数仍多于数千人，无法提供床位。并非所有无家可归者都选择留在避难所。尽管如此，联邦救援团的大多数人都知道这名短暂杀手的存在，并承认有些担忧。


洛杉矶警方仍在寻找另一名连环杀人犯。这位外来杀手涉嫌在过去三年内杀害了十七名妇女，其中大部分是妓女。我是洛杉矶的萨拉斯·沃森。

---

== How to Present a Seminar Paper +


In this talk, I am going to give some advice on how to present a seminar paper. +

At one time, most university teaching took the form of giving formal lectures. Nowadays, many university teachers try to involve their students more actively in the learning process. One of the ways in which this is done is by conducting seminars. In a seminar, what usually happens is this. One student is chosen to give his ideas on a certain topic. These ideas are then discussed by the other students (the participants) in the seminar. +

What I'd like to discuss with you today is the techniques of presenting a paper at a seminar. As you know, there are two main stages involved in this. One is the preparation stage which involves researching and writing up a topic. The other stage is the presentation stage when you actually present the paper to your audience. It is this second stage that I am concerned with now. Let us therefore imagine that you have been asked to lead off a seminar discussion and that you have done all the necessary preparation. In other words you have done your research and you have written it up. How are you going to present it? +


There are two ways in which this can be done. +

The first method is to circulate copies of the paper in advance to all the participants. This gives them time to read it before the seminar, so that they can come already prepared with their own ideas about what you have written. The second method is where there is no time for previous circulation, or there is some other reason why the paper cannot be circulated. In that case, of course, the paper will have to read aloud to the group, who will probably make their own notes on it while they are listening. +

In this talk, I am going to concentrate on the first method, where the paper is circulated in advance, as this is the most efficient way of conducting a seminar; but most of what I am going to say also applies to the second method; and indeed may be useful to remember any time you have to speak in public. +
 +

You will probably be expected to introduce your paper even if it has been circulated beforehand. There are two good reasons for this. One is that the participants may have read the paper but forgotten some of the main points. The second reason is that some of the participants may not in fact have had time to read your paper, although they may have glanced through it quickly. They will therefore not be in a position to comment on it, unless they get some idea of what it is all about. +

When you are introducing your paper, what you must not do is simply read the whole paper aloud. This is because: +
 +

Firstly, if the paper is a fairly long one, there may not be enough time for discussion. From your point of view, the discussion is the most important thing. It is very helpful for you if other people criticize your work: in that way you can improve it. +
 +

Secondly, a lot of information can be understood when one is reading. It is not so easy to pick up detailed information when one is listening. In other words, there may be lack of comprehension or understanding. +
 +

Thirdly, it can be very boring listening to something being read aloud. Anyway some of your audience may have read your paper carefully and will not thank you for having to go through all of it again. +
 +

Therefore, what you must do is follow the following nine points: +


 1. Decide on a time limit for your talk. Tell your audience what it is. Stick to your time limit. This is very important. +


 2. Write out your spoken presentation in the way that you intend to say it. This means that you must do some of the work of writing the paper again, in a sense. You may think that this is a waste of time, but it isn't. If a speaker tries to make a summary of his paper while he is standing in front of his audience, the results are usually disastrous. +


 3. Concentrate only on the main points. Ignore details. Hammer home the essence of your argument. If necessary, find ways of making your basic points so that your audience will be clear about what they are.

 4. Try to make your spoken presentation lively and interesting. This doesn't necessarily mean telling jokes and anecdotes. But if you can think of interesting or amusing examples to illustrate your argument, use them. +

 5. If you are not used to speaking in public, write out everything you have to say, including examples, etc. Rehearse what you are going to say until you are word perfect. +
 +

 6. When you know exactly what you are going to say, reduce it to outline notes. Rehearse your talk again, this time from the outline notes. Make sure you can find your way easily from the outline notes to the full notes, in case you forget something. +

 7. At the seminar, speak from the outline notes. But bring both sets of notes and your original paper to the meeting. Knowing that you have a full set of notes available will be good for your self-confidence. +

 8. Look at your audience while your are speaking. The technique to use is this. First read the appropriate parts of your notes silently (if you are using outline notes, this won't take you long). Then look up at your audience and say what you have to say. Never speak while you are still reading. While you are looking at your audience, try to judge what they are thinking. Are they following you? You will never make contact with your audience if your eyes are fixed on the paper in front of you. +

 9. Make a strong ending. One good way of doing this is to repeat your main points briefly and invite questions or comments. +

Perhaps I can sum up by saying this. Remember that listening is very different from reading. Something that is going to be listened to has therefore got to be prepared in a different way from something that is intended to be read.


如何提交研讨会论文

在本次演讲中，我将就如何提交研讨会论文提出一些建议。

曾经，大多数大学教学都采取正式讲座的形式。如今，许多大学教师试图让学生更积极地参与学习过程。实现这一目标的方法之一是举办研讨会。在研讨会上，通常会发生这样的情况。选择一名学生就某个主题发表自己的想法。然后研讨会上的其他学生（参与者）讨论这些想法。

今天我想和大家讨论的是在研讨会上发表论文的技巧。如您所知，这涉及两个主要阶段。一是准备阶段，涉及研究和撰写主题。另一个阶段是演示阶段，当你实际向观众展示论文时。我现在关心的是第二阶段。因此，让我们想象一下，您被要求主持一场研讨会讨论，并且您已经完成了所有必要的准备。换句话说，你已经完成了你的研究并且已经把它写下来了。你打算如何展示它？

有两种方法可以做到这一点。

第一种方法是提前将论文副本分发给所有参与者。这让他们有时间在研讨会之前阅读它，这样他们就可以对你所写的内容有自己的想法。第二种是之前没有时间传阅，或者有其他原因无法传阅的情况。当然，在这种情况下，论文必须向小组大声朗读，他们可能会在听的时候自己做笔记。

在这次演讲中，我将重点讨论第一种方法，即提前分发论文，因为这是举办研讨会最有效的方法；但我要说的大部分内容也适用于第二种方法；事实上，任何时候你必须在公共场合演讲时记住这一点可能会很有用。


即使您的论文已经事先分发过，您也可能需要介绍它。这有两个很好的理由。一是参与者可能已经阅读了论文，但忘记了一些要点。第二个原因是，一些参与者实际上可能没有时间阅读你的论文，尽管他们可能很快地浏览了一遍。因此，除非他们了解事情的全部内容，否则他们无法对此发表评论。

当你介绍你的论文时，你绝对不能只是大声朗读整篇论文。这是因为：


首先，如果论文相当长，可能没有足够的时间进行讨论。从你的角度来看，讨论是最重要的。如果其他人批评你的工作，这对你非常有帮助：这样你就可以改进它。


其次，阅读时可以理解很多信息。当一个人在听的时候，要获取详细的信息并不是那么容易的。换句话说，可能缺乏理解或理解。


第三，听大声朗读的内容可能会很无聊。不管怎样，你的一些读者可能已经仔细阅读了你的论文，并且不会感谢你必须再次阅读所有内容。


因此，你必须做到以下九点：

确定演讲的时间限制。告诉你的听众这是什么。遵守你的时间限制。这个非常重要。

按照您想要的方式写下您的口头演讲。从某种意义上来说，这意味着你必须重新做一些写论文的工作。您可能认为这是浪费时间，但事实并非如此。如果演讲者试图在听众面前总结他的论文，结果通常是灾难性的。

只关注要点。忽略细节。锤炼你的论点的本质。如有必要，想办法阐述你的基本观点，以便你的听众清楚这些观点是什么。

尽量让你的演讲生动有趣。这并不一定意味着讲笑话和轶事。但如果你能想出有趣的例子来说明你的论点，那就使用它们。

如果您不习惯在公共场合演讲，请写下您要说的所有内容，包括示例等。排练您要说的话，直到您的单词完美为止。
+

当你确切知道自己要说什么时，将其简化为大纲笔记。再次排练你的演讲，这次是根据大纲笔记。确保您可以轻松地从大纲笔记到完整笔记，以防您忘记某些内容。

在研讨会上，根据大纲笔记进行发言。但请携带两套笔记和原始论文参加会议。知道你有一整套可用的笔记将有利于你的自信。

演讲时看着听众。使用的技术是这样的。首先默读笔记的适当部分（如果您使用大纲笔记，这不会花费您很长时间）。然后抬头看着你的听众并说出你要说的话。阅读时切勿说话。当你看着你的听众时，试着判断他们在想什么。他们在跟踪你吗？如果你的眼睛盯着面前的纸，你将永远无法与观众接触。

做出一个强有力的结局。这样做的一个好方法是简短地重复您的要点并邀请问题或评论。

也许我可以这样总结。请记住，听力与阅读有很大不同。因此，要听的东西必须以与要读的东西不同的方式准备。

---
