=  English pod 001-020
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''


== 001  Customer 顾客；主顾；客户 (B0001)


A: Good evening. My name is Fabio, I’ll be your waiter for tonight. May I take your order?  +
B: No, I’m still working on it. This menu is not even in English. What’s good here?  +
A: For you sir, I would recommend spaghetti and meatballs.  +
B:  Does it come with coke and fries?  +
A:It comes with either soup or salad and a complimentary glass of wine, Sir. +
B: I’ll go with the spaghetti and meatballs, salad and the wine.  +
A: Excellent choice, your order will be ready soon.  +
B: How soon is soon?  +
A: Twenty minutes?  +
B: You know what? I’ll just go grab a burger across the street.  +

'''

==== 001 释义



A: Good evening. My name is Fabio, I’ll be
your waiter for tonight. May I take your
order 您要点菜吗 ?

B: No, I’m still working on it 持續(仍然在)進行某項工作，正在 (努力) 處理某些工作. This menu is not even in English. What’s good here?

[.my2]
这个菜单甚至都不是英文的。这里有什么好东西？

A: For you sir, I would recommend 推荐，介绍 spaghetti 意大利式细面条
and meatballs  肉丸；笨蛋.

B: Does it come with 与…一起供给,伴随…发生 coke 可口可乐 and fries 薯条?

A:It comes with either soup 汤 or salad 沙拉  /and a
complimentary 免费赠送的 glass of wine, Sir.

[.my1]
.案例
====
.complimentary
-> 来自compliment, 恭贺，道贺。现该词主要用于在基本服务基础上的免费升级，如免费升舱，免费早餐等。
====

B: I’ll go with 同意；接受（某事物） the spaghetti and meatballs,
salad and the wine.

A: Excellent 极好的，卓越的 choice, your order will be ready
soon.

B: How soon is soon?

A: Twenty minutes?

B: You know what? I’ll just go grab a burger 汉堡包，夹心牛肉饼
across the street.

'''

== 002 Elementary ‐ Calling In Sick 打电话请病假 (B0002)


A: Hello, Daniel speaking, how may I help you?  +
B: Hi, Daniel, Julie here.  +
A: Hi, Julie, how are you?  +
B: Actually, I’m feeling quite ill today.  +
A: I’m sorry to hear that. What’s wrong?  +
B: I think I’m coming down with the flu. I have a headache, a sore throat a runny nose and I’m feeling slightly feverish.  +
A: I see... so you’re calling in sick?  +
B: Yes, I was hoping to take the day off to recover.  +
A: OK, then. Try and get some rest.  +

'''

==== 002 释义


A: Hello, Daniel speaking, how may I help
you?

B: Hi, Daniel, Julie here.

A: Hi, Julie, how are you?

B: Actually, I’m feeling quite ill 有病的，不舒服的 today.

A: I’m sorry to hear that. What’s wrong?

B: I think I’m coming down with 染上（疾病） the flu. I
have a headache, a sore (a.)（发炎）疼痛的，酸痛的 throat a runny (a.)流鼻涕的；水分过多的 nose
/and I’m feeling slightly feverish  (a.)发烧的，发热的.

A: I see... so you’re *calling in sick* 打电话请病假?

B: Yes, I was hoping *to take the day off* 请一天假,休一天假 to
recover.

A: OK, then. Try and get some rest.


'''


== 003 Elementary ‐Daily Life ‐ Hotel Upgrade (C0003)

A: Good afternoon. What can I do for you?  +
B: I’d like to check in please. I have a reservation under the name Anthony Roberts.  +
A: All right R.O.B.E.R.T.S... Oh, Mr. Roberts we’ve been expecting you& and here is your keycard to the presidential suite.  +
B: But there must be some mistake; my reservation was for a standard room.  +
A: Are you sure? Let me double check.  +
B: Yeah&Here, this is my confirmation number.  +
A: You’re right Mr. Roberts, there seems to be a mixup, unfortunately we’re overbooked at the moment .  +
B: So&  +
A: Not to worry. We’re pleased to offer you a complimentary upgrade.  +
B: Presidential suite baby!  +

'''

==== 003 释义



A: Good afternoon. What can I do for you?

B: I’d like *to check in* 办理入住手续 please. I have a
reservation 预订；预约 under the name Anthony
Roberts.

A: All right R.O.B.E.R.T.S... Oh, Mr. Roberts
we’ve been expecting 期待；企盼 you /and here is your
keycard 门卡；门禁卡 to the presidential suite 套房，套间.

B: But there must be some mistake; my
reservation was for a standard room.

A: Are you sure? Let me *double check* 仔细检查.

B: Yeah & Here, this is my _confirmation 确认，确定 number_.

A: You’re right Mr. Roberts, there seems to
be a mixup 混合；混合物;混杂;搞糊涂, unfortunately we’re overbooked (v.)超额预订（飞机座位或旅馆客房）
at the moment .

[.my1]
.案例
====
.overbook
(v.)to sell more tickets on a plane or reserve (v.) more rooms in a hotel than there are places （尤指占用或空着的）座位，位置，泊位 available 超额预订（飞机座位或旅馆客房） +
[ VN] +
•The flight was heavily overbooked (v.). 该班机售票, 大大超出机位数量。
====

B: So &

A: Not to worry. We’re pleased (a.)高兴的，满意的 to offer (v.) you a
complimentary upgrade 免费升级.

B: _Presidential suite_ baby!

'''

== 004 Elementary ‐The Office ‐ I need an assistant 助理，助手；店员，售货员! (C0004)


A: ...like I told you before, we just don’t have the resources to hire you an assistant.  +
B: I understand that, but the fact is we’re understaffed.  +
A: The timing is just not right. The economy is bad, and it’s too risky to take on new staff.  +
B: Yeah, I guess you’re right.... here’s an idea, what if we hire an intern? She would take some of the weight off my shoulders.  +
A: She?  +
B: Yeah, you know, a recent graduate. She could give me a hand with some of these projects and we could keep our costs down.  +
A:
That sounds reasonable... let me see what I can do.  +
 +
A:
Tony, I’d like to introduce you to your new assistant.  +
B: OK, great! Let’s meet her!  +
C: Hi, I’m Adam.  +
B: Oh... hi... I’m Tony...  +

'''

==== 004 释义

A: ...like I told you before, we just don’t
have the resources 资源；财力 to hire 租用，聘用，录用 you an assistant.

B: I understand that, but the fact is /we’re
understaffed (a.)人手不足的；人员不足的.

A: The timing is just not right. The economy
is bad, and it’s too risky *to take on* 雇佣 new staff.

B: Yeah, I guess you’re right.... here’s an
idea, what
if we hire an intern 实习生? She would *take* some of
the weight *off* my shoulders 减轻一些负担.

A: She?

B: Yeah, you know, a recent (a.)最近的，最新的 graduate 大学毕业生. She
could *give me a hand with* some of these
projects /and we could keep our costs down 控制成本.

A: That sounds (v.) reasonable... let me see /what
I can do.

A: Tony, I’d like to introduce you to your new
assistant.

B: OK, great! Let’s meet her!
C: Hi, I’m Adam.

B: Oh... hi... I’m Tony...

'''

== 005 Elementary ‐Daily Life ‐ Cut In Line 插队 (C0005)

A: I can’t believe it took us two hours to get
here. The traffic in New York is unbelievable.
 +
B: Yeah, but just relax honey, we’re here and
we’re going on vacation. In a few hours we’ll
be in Hawaii, and you’ll be on the golf
course.
 +
A: Oh no!Look at that line! It must be a mile
long!
There’s no way I’m waiting for another two
hours.
 +
B: Honey... don’t...
 +
C: Hey man, the end of the line is over there.
 +
A: Yeah...
 +
C: No seriously, I was here first, and you
can’t cut in line like this.
 +
A: Says who?
 +
C: I do!
 +
A: So sue me!  +
C: Alright...that’s it....  +

'''

==== 005 释义


A: I can’t believe /it took us two hours to get
here. The traffic in New York is unbelievable 难以置信的，特别的；极其糟糕的.

B: Yeah, but just relax (v.) honey, we’re here /and
we’re going on vacation 度假. In a few hours 几小时后,个小时内 /we’ll
be in Hawaii, and you’ll be on the golf
course 比赛场地；跑道.

[.my1]
.案例
====
.we’re going on ... 我们去...  +
“going on”在这里是一个短语动词，表示“进行；去”。 +
- We're Going on a Bear Hunt
我们要去猎熊 +
- We're Going On A Rocket Ship
我们要乘坐火箭飞船
====

A: Oh no! Look at that line! It must be a mile
long! 它一定有一英里长！
There’s no way 绝不可能,绝对不会 I’m waiting for another two
hours.

[.my2]
我绝对不可能再等两个小时。

B: Honey... don’t... +
C: Hey man, the end of the line is over there. 队伍的尽头在那边

A: Yeah... +
C: No seriously 不是开玩笑的,我是认真的, I was here first, and you
can’t *cut in line* like this.

A: Says who? 谁说的？ +
C: I do!

A: So *sue (v.)控告；提起诉讼 me*!  +
C: Alright...that’s it....

[.my2]
那你去告我啊！ +
好吧…够了… (这句话通常表示忍无可忍，表明说话人已经失去了耐心，准备采取行动。)

'''

== 006 Elementary ‐ The Weekend ‐ Road Trip 公路旅行 (C0006)


A: So, are we all ready to go?  +
B: Yup, I think so. The car’s packed; we have munchies and music, and the map’s in the car.  +
A: Did you get the camera?  +
B: Got it! Did you fill up the tank?  +
A: Yup, it’s all set.  +
B: You’re sure we’re not forgetting anything?  +
A: I’m sure... we’ve got all our bases covered.  +
B:  Well& let’s get going then! I love road trips!  +
 +
B:  Um... do you think we can make a pit stop?  +
A: But we’ve only been on the road for ten minutes.  +
B: I know, but I forgot to go to the bathroom before we left.  +

'''

==== 006 释义


A: So, are we all ready to go?

B: Yup 是的（等于 yes）, I think so. The car’s packed (v.)把……打包；包装;(a.)挤满人的，非常拥挤的；充满的，装满的；收拾妥当的，收拾好了的; we have
munchies 快餐；小吃 and music, and the map’s in the
car.

A: Did you get the camera?

B: Got it 拿到了,搞定了! Did you *fill up* 加满 the tank （贮放液体或气体的）箱，槽，罐?

A: Yup, it’s all set (a.)安排好的；确定的；固定的;  一切已经准备就绪.

B: You’re sure /we’re not forgetting anything?

A: I’m sure... we’ve got all our bases
covered. 我们已经面面俱到, 所有方面都考虑到了

[.my1]
.案例
====

“All our bases covered” 是一个惯用表达，意思是“我们已经面面俱到”或“所有方面都考虑到了”。它源自棒球术语，指的是确保所有垒位都被防守到位，以防对手得分。
====

B: Well & let’s *get going* 开始行动；出发 then! I love road
trips!

[.my1]
.案例
====
.let’s get going then!
“*get going*”是一个短语动词，表示“*开始行动；出发*”。

*不能去掉get,* 因为“let’s going then!”在语法上是不正确的。**“let's”是一个固定短语，其后需要动词原形。**而不是动词的进行时态。因此, 你只能说成 “let’s go then!”或者“let’s get going then!”。

两者的区别是:
虽然“let’s *go* then!”和“let’s *get going* then!”在意思上非常接近，都表示“让我们出发吧”。 但是:

- “let’s *get going* then!”在语气上可能**稍微更加强调“开始行动”的动态感，更具有一种推动力。**
- “let's *go*” *只是单纯的走，出发。*

即 “let's get going” 更加强调"开始行动"的这个过程。
====

B: Um... do you think we can *make a pit
stop* 短暂停留,中途休息?

[.my2]
“Pit stop” 的意思是“短暂停留”或“中途休息”。这个词来源于赛车术语，指赛车在比赛中, 短暂停靠维修站加油、更换轮胎, 或进行快速维修。但在日常对话中，它通常用于比喻，指在旅途中为了加油、上厕所、买零食等做的短暂停留。 +
在句子 “Do you think we can make a pit stop?” 中，意思是：
“你觉得我们可以稍微停一下吗？” 可能是为了休息或处理一些事情。

A: But we’ve only been on the road for ten
minutes.

B: I know, but I forgot to go to the bathroom 浴室;卫生间，厕所
before
we left.

'''

== 007 Elementary ‐ The Office ‐ Virus! (C0007)

A: Oh great! This stupid computer froze again! Thats the third time today! Hey Samuel, can you come take a look at my PC? It’s acting up again. It must have a virus or something.  +
B:
Just give me a second; I’ll be right up.  +
 +
B:
I ran a virus scan on your computer, and it turns out that you have a lot of infected files!  +
A: But I’m quite careful when I’m browsing the internet, I have no idea how I could have picked up a virus.  +
B: Well, you have to make sure that your anti-virus software is updated regularly; yours wasn’t up to date, that’s probably what was causing your problems.  +
A: Ok. Anything else?  +
B: Yeah, try not to kick or hit the computer!  +
A: Um yeah& Sorry about that.  +

'''

==== 007 释义


A: Oh great! This stupid computer froze (v.)（屏幕）冻结,死机
again! That's the third time today! Hey
Samuel, can you come /take a look at my PC?
It’s *acting up* 功能失常，出毛病 again. It must have a virus or
something.

B: Just give me a second; I’ll be right up 马上就上去,立刻就到.

[.my2]
在这里，“right up” 的意思是“马上就上去”或者“立刻就到”。 +
“right” 用来强调动作的迅速或及时性，表示“马上”或“立即”。 +
“up” 指的是移动到某个更高的地方，比如楼上、台阶上，或者是与说话者的物理位置相关的方向。 +
整句意思是：“稍等一下，我马上就上去（到你那儿）。”

B: I ran a _virus scan_ (n.) on your computer, and
*it turns out that* you have _a lot of_ infected （身体部位或伤口）受感染的
files!

A: But I’m quite careful /when I’m browsing (v.)
the internet, I have no idea /how I could have
*picked up* （偶然）得到，听到，学会;得；感染；得到 a virus.

[.my2]
====
- 带有 “could” 的句子: +
“how I could have picked up a virus” +
“could have” 表示一种可能性或怀疑，强调说话人对过去发生的事情**感到困惑或无法理解。**
这种表达带有推测或假设的语气，意思是“我不知道我怎么可能感染了病毒”。
它反映了说话人觉得感染病毒的可能性很低，甚至难以置信。

- 没有 “could” 的句子
“how I have picked up a virus” +
没有 “could” 时，句子更直接，表示一种事实陈述：说话人确认自己感染了病毒，但不知道具体是怎么发生的。
这种表达更倾向于说明结果，而**不是表达困惑或怀疑。**
====


B: Well, you have to make sure that /your
anti-virus software is updated regularly;
yours wasn’t *up to date* 最新的, that’s probably /what
was causing your problems.

A: Ok. Anything else?

B: Yeah, try not to 尽量不要做 kick or hit the computer!

A: Um yeah & Sorry about that.

'''

== 008.  Elementary ‐ Daily Life ‐ What’s your name again? (C0008)

A: Nick! How’s it going?  +
B: Oh, hey...  +
A: What are you doing in this neighbourhood? Do you live around here?  +
B: Actually, my office is right around the corner.  +
A: It was great to meet you last week at the conference. I really enjoyed our conversation about foreign investment.  +
B: Yeah, yeah, it was really interesting. You know, I’m in a bit of a hurry, but here’s my card. We should definitely meet up again and continue our discussion.  +
A: Sure, you still have my contact details, right?  +
B: You know what, this is really embarrassing, but your name has just slipped my mind. Can you remind me?  +
A: Sure, my name is Ana Ferris. Don’t worry about it; it happens to me all the time. I’m terrible with names too.  +


'''

==== 008 释义


A: Nick! How’s it going? 近来如何

B: Oh, hey...

A: What are you doing in this
neighbourhood? Do you live around here? 你住在这附近吗？

B: Actually, my office is right around the
corner. 就在拐角处

A: It was great 美妙的；好极的；使人快乐的 to meet you last week at the
conference （大型、正式的）会议，研讨会. I really enjoyed our conversation
about foreign investment.

B: Yeah, yeah, it was really interesting. You
know, I’m in a bit of a hurry, but here’s my
card. We should definitely  肯定地，当然；明确地，确定地 *meet up* （按照安排）见面，会面;相约见面 again /and
continue (v.) our discussion.

[.my2]
我有点赶时间，这是我的名片。我们一定要再见面继续讨论。

A: Sure, you still have my contact details 联系方式,
right?

B: You know what 你知道吗, this is really
embarrassing, but your name has just
slipped my mind 被遗忘. Can you remind me?

[.my2]
You know what
你知道吗：用于引起某人的注意，然后宣布某事。

A: Sure, my name is Ana Ferris. Don’t worry
about it; it happens to me _all the time_ 我经常遇到这种事. I’m
*terrible with* 在某方面很糟糕, 对某事很不擅长 names too.

'''

== 009. Elementary ‐ The Weekend ‐ Silence please! (C0009)

A: Those people in front of us are making so much noise. It’s so inconsiderate!  +
B: Dont worry about it; it’s not such a big deal.  +
A: Oh... I cant hear a thing! Excuse me, can you keep it down?  +
C: Sure, sorry ’bout that!  +
A: Someone’s phone is ringing!  +
B: Honey, I think it’s your phone. Did you forget to switch it off?  +
A: Oh, no! You’re right. That’s so embarrassing!  +
C: Do you mind keeping it down? I’m trying to watch a movie here!  +

'''

==== 009 释义

A: Those people in front of us `谓` are making so
much noise. It’s so inconsiderate 不为别人着想的；不体谅别人的；考虑不周的!

B: Don't worry about it; it’s not such a big
deal. 这没什么大不了的。

A: Oh... I can't hear a thing! Excuse me, can
you keep it down 保持安静,小声点?
C: Sure, sorry ’bout that!

A: Someone’s phone is ringing!

B: Honey, I think it’s your phone. Did you
forget to switch it off 关掉它?

A: Oh, no! You’re right. That’s so
embarrassing! +

C: Do you mind keeping it down 保持安静? I’m trying
to watch a movie here!

'''

== 010. Elementary ‐ The Office ‐ Driving (v.) Sales 驱动销售 (C0010)

A: All right, people. We’re holding this meeting today because we’ve got to do something about our sales, and we need to do it NOW! I want concrete solutions. How do you intend to drive sales... Roger?  +
B: Well, in fact, we’re the most expensive in the market, so maybe we need to lower our prices to match the competitors?  +
A: Lower our prices? Not very creative. It’ll never fly with Swan. What kind of thinking is that? Geez. Anybody else have a better plan? Natalie?  +
C: Um, perhaps, um, a sales promotion.
Maybe a two-for-one offer, or something like
that!
 +
A: What? That’s the same thing. Bad idea.
Really bad idea. Dammit people come on!
Think! The CEO will be here any minute.
 +
 +
D: Do we have any ideas yet?
 +
C: Yes Mr. Swan, we were kind of considering
a two-for-one offer to get more competitive.
 +
D: A two-for-one promotion? Hmm. I kind of
like the sound of that. It sounds like
something we should consider.
 +
A: Yeah, exactly. Just what I was thinking! In
fact, that’s a brilliant idea! I’m glad we
thought of that.
Very creative.
 +

'''

==== 010 释义


A: All right, people. We’re holding this
meeting today /because we’ve got to 不得不，必须 do
something about our sales, and we need to
do it NOW! I want concrete  (a.)确实的，具体的；实在的，有形的；混凝土的；物质的 solutions 解决办法. How do
you intend *to drive (v.) sales* 你打算如何推动销售... Roger?

B: Well, in fact, we’re the most expensive in
the market, so maybe we need to lower (v.) our
prices /to match 使等同于；使优于;相同；相似；相一致 the competitors 竞争对手?

A: Lower (v.) our prices? Not very creative. It’ll
never fly with Swan. _What kind of thinking_ is
that? Geez. 这是什么想法？天啊。 Anybody else have a better plan?
Natalie?

[.my1]
.案例
====

"Fly with Swan" 在这里是一个比喻，意思是这种想法或计划, 不符合Swan的期望或标准。可以理解为，这个计划不会被Swan接受或批准。
====

C: Um, perhaps, um, a sales promotion 促销活动.
Maybe a _two-for-one offer_ 买一送一, or something like
that!

[.my2]
"Two-for-one offer" 是一种促销活动，意思是消费者购买一个商品时，可以免费获得另一个相同或相似的商品。换句话说，支付一个价格就能得到两个商品。

A: What? That’s the same thing. Bad idea.
Really bad idea. Dammit （非正式）（表示厌烦、失望等）该死，真他妈的 /people come on!
Think! The CEO will be here *any minute* 任何时刻（现在）;随时可能发生，即将发生.

[.my2]
"Dammit people come on" 是一种表达 frustration（沮丧）或 impatience（不耐烦）的方式。在这里，A 对于大家提出的建议感到失望或恼火，急切地希望其他人能提出更好、更有创意的方案。"Dammit" 加强了 A 的情绪，而 "come on" 则是催促大家加快思考或行动的意思。

D: Do we have any ideas yet?

C: Yes Mr. Swan, we were kind of 在某种程度上；更或少地 considering
a _two-for- one  offer_ 买一送一 to get more competitive.

D: A two-for-one promotion? Hmm. I kind of
like the sound 声音 of that. It *sounds like*
something 后定 we should consider. 听起来我们应该考虑一下。

A: Yeah, exactly. Just what I was thinking! In
fact, that’s a brilliant idea! I’m glad we
*thought (v.) of* 想出；构思出 that.
Very creative.

'''

== 011. Elementary ‐ Daily Life ‐ New Guy in Town (C0011)

A: Oh, I don’t know if you heard, but someone moved into that old house down the road.  +
B: Yeah, I know. I met the owner of the house yesterday as he was moving in. His name is Armand.  +
A: Really? What’s he like? You have to fill me in.  +
B: Actually, he’s a bit strange. I don’t know... I’ve got a bad feeling about him.  +
A: Really? Why?  +
B: Well, yesterday I brought over a housewarming gift,but Armand started acting really weird, and then he practically kicked me out! I tried to, sort of, peek into his house, but everything was so dark inside that I couldn’t really get a good look.  +
A: Well, you’ll never guess what I saw this morning. A delivery truck pulled into his driveway, and it dropped off a long, rectangular box. It almost looked like a coffin!  +
B: You see! Why would he...  +
C: Hello ladies...  +
B: Ah, Armand! You scared the heck out of me! This is my friend Doris.  +
C: A pleasure to meet you...If you are not doing anything tonight, I would like to have you both for dinner.I mean...I would like to have you both over for dinner.  +
 +

'''

==== 011 释义


A: Oh, I don’t know if you heard, but
someone moved into that old house _down
the road_.

[.my2]
不知道你听说了没有，有人搬进了路那头的老房子。

B: Yeah, I know. I met the owner of the
house yesterday /as he was moving in. His
name is Armand.

A: Really? What’s he like? You have *to fill* 向…提供（情况） me
*in*.

[.my1]
.案例
====
fill (v.) sb ˈin (on sth) +
to tell sb about sth that has happened 向…提供（情况）
====

B: Actually, he’s a bit strange. I don’t know...
I’ve got a bad feeling about him.

A: Really? Why?

B: Well, yesterday I *brought over* 把...带到某地 a
housewarming 乔迁庆宴,乔迁聚会 gift, but Armand started acting (v.)
really weird (a.)奇怪的，不寻常的；怪异的, and then he practically  几乎，差不多；实事求是地，实际地 kicked
me out! I tried to, sort of, peek (v.)偷看，窥视 into his
house, but everything was *so* dark inside
/*that* I couldn’t really get a good look 好好看一看.

[.my2]
昨天我带了一份乔迁礼物过来，但是阿曼德开始表现得很奇怪，然后他几乎把我赶出去了！我试着偷看他的房子，但里面太黑了，我看不清楚。

[.my1]
.案例
====
bring over :   +
(PHRASAL VERB [TRANSITIVE]) : to take someone or something from one place to the place where someone else is, especially their home.
Bring over（短语动词[及物]）：将某人或某物从一个地方带到另一个人所在的地方，尤其是他们的家。

- I’ll *bring* my holiday photos *over* when I come.
我来的时候, 会把我的假期照片带过来。
====

A: Well, you’ll never guess 你绝对猜不到 what I saw this
morning.
A delivery 递送，投递 truck pulled into 进站停靠;驶向路边（或某处）停靠 his driveway 私人车道, and
it *dropped off* 中途卸客；中途卸货 a long, rectangular 长方形的，矩形的 box. It
almost looked like a coffin 棺材!

[.my2]
一辆送货卡车停在他的车道上，送来了一个长方形的长盒子。它看起来几乎像一口棺材！

B: You see! Why would he...
C: Hello ladies...

B: Ah, Armand! You scared (v.)使惊恐，吓唬；受惊吓，害怕 the heck 该死; 见鬼(表示稍感恼怒、吃惊等) out of
me! 你吓死我了 This
is my friend Doris.

[.my2]
"Scared the heck out of me" 是一种表达害怕或惊吓的口语方式，意思是“把我吓得要命”或“把我吓得很厉害”。"Heck" 是 "hell" 的委婉说法，用来强调强烈的情感或反应。


C: A pleasure to meet you...If you are not
doing anything tonight, I would like to have
you both for dinner. I mean...I would like to
have you both *over* for dinner.

[.my2]
====
- "To have you both for dinner" 直译是“*把你们俩当晚餐*”，这听起来像是字面上的意思，暗示把人当作食物，通常在这种情况下是一个幽默的错误或不合适的说法。这个表达可能会引起误解，给人一种威胁或幽默的感觉。

- "To have you both *over* for dinner" 是一种常见的邀请说法，意思是“*请你们俩来我家吃晚餐*”。这里的**“over”表示邀请别人到自己家中聚餐。**

所以，第二个表达是正确的且常用的，第一种则因为没有 "over" 可能会引起误解。
====

'''

== 012. Elementary ‐ Daily Life ‐ Cleaning the House (C0012)

A: Honey, the house is such a mess! I need
you to help me tidy up a bit. My boss and her
husband are coming over for dinner and the
house needs to be spotless!
 +
B: I’m in the middle of something right now.
I’ll be
there in a second.
 +
A: This can’t wait! I need your help now!
 +
B: Alright, alright. I’m coming.
 +
A: Ok, here’s a list of chores we need to get
done. I’ll do the dishes and get all the
groceries for tonight. You can sweep and
mop the floors. Oh, and the furniture needs
to be dusted.
 +
B: You know what, I have to pick something
up at the mall, so why don’t you clean the
floors and Ill go to the supermarket and get
all the groceries.
 +
A: Sure that’s fine. Here is the list of all the
things you need to get. Dont forget anything!
And can
you pick up a bottle of wine on your way
home?
 +
B: Hey, honey I’m back. Wow, the house
looks really
good!
 +
A: Great! Can you set the table?
 +
B: Just a sec I’m just gonna vacuum this rug
real fast
 +
A: Wait! Don’t turn it on...

'''

==== 012 释义


A: Honey, the house is such a mess! I need
you to help me *tidy up* 整理、收拾,清理 a bit. My boss and her
husband are coming over （尤指到某人家中）短暂造访 for dinner 正餐，晚餐 /and the
house needs to be spotless 极清洁的；非常洁净的;无可挑剔的；无瑕疵的；纯洁的!

[.my1]
.案例
====
.spotless
-> spot,斑点，污迹，-less,无，没有。
====

B: I’m in the middle of something 中途忙于做某事 right now.
I’ll be
there in a second 立刻，马上.

A: This can’t wait! I need your help now!

B: Alright, alright. I’m coming.

A: Ok, here’s a list of chores 日常事务；例行工作;令人厌烦的任务；乏味无聊的工作 we need to get
done 我们需要完成. I’ll do the dishes 洗碗;洗餐具 and get all the
groceries 食品杂货 for tonight. You can sweep and
mop (v.)用拖把擦干净 the floors. Oh, and the furniture needs
to be dusted 擦去……的灰尘.

[.my1]
.案例
====
.chore
-> 来自PIE*sker, 转，打转，词源同charlady, ring. 即在外围打杂的人。
====

B: You know what, I have to *pick* something
*up* at the mall 我得去商场买点东西, so why don’t you clean the
floors /and I'll go to the supermarket and get
all the groceries.

A: Sure /that’s fine. Here is the list of all the
things you need to get. Don't forget anything!
/And can
you pick up a bottle of wine on your way
home?

B: Hey, honey I’m back. Wow, the house
looks really
good!

A: Great! Can you *set the table* 摆好餐具?

B: Just a sec /I’m just gonna *vacuum (v.)用真空吸尘器打扫 this rug* 小地毯，垫子
real (ad.)很，非常地 fast 快的，迅速的.

[.my2]
等一下，我要用吸尘器吸一下地毯

A: Wait! Don’t turn it on... 不要打开它

'''

== 013. Elementary ‐ The Office ‐ Out Of Control Spending 支出失控 (C0013)

A: OK, so now the last point on our agenda.
Jill, let’s
go over the profit and loss statement.
 +
B: Great. Well, the main issue here, as you
can see,
is that our expenses are through the roof.
 +
A: Let’s see... These numbers are off the
charts!
What’s going on here!
 +
 +
B: Well, um, sir, the company expenditures on entertainment and travel are out of control. Look at these bills for example. Just this month we’ve paid over twenty thousand dollars for hotel charges!  +
A: OK, thank you. I’ll look into it.  +
B: The list goes on and on. Here, this is a bill for five thousand dollars for spa treatments!  +
A: Thank you; that will be all. I’ll take care of it.  +
B: Look at this one sir, eight thousand dollars were spent in one night at a place called ”Wild Things”?!  +
A: OK, I get it!! Thank you for your very thorough analysis!  +

'''

==== 013 释义

A: OK, so now the last point on our agenda.
Jill, let’s
go over 从一处到（另一处）;切换到另一人物（或地点） _the profit 利润，盈利 and loss statement_.

[.my2]
现在是我们议程上的最后一点. 让我们看一下损益表。

B: Great. Well, the main issue here, as you
can see,
is that /our expenses 花钱的东西；开销 are _through the roof_ 冲破屋顶, 暴涨.

[.my2]
我们的开支高得离谱。

A: Let’s see... These numbers are _off the charts_  (图表；排行榜) 處於極高水準的;破纪录,好极了, 超过正常水平!
What’s going on here! 这是怎么回事！


B: Well, um, sir, `主` the company expenditures (n.)开支,支出
on entertainment and travel `系` are out of
control. Look at these bills 账单 for example. Just
this month /we’ve *paid* over twenty thousand
dollars *for* hotel charges 费用!

[.my2]
公司在娱乐和旅游上的开支失控了。

A: OK, thank you. I’ll *look into* 调查；审查 it.

B: The list *goes on and on* (不停地持续发生) 这样的例子不胜枚举. Here, this is a bill
for five
thousand dollars for spa treatments 水疗护理!

[.my1]
.案例
====
.spa
1.a place where water with minerals in it, which is considered to be good for your health, comes up naturally out of the ground; the name given to a town that has such a place and where there are, or were, places where people could drink the water 矿泉疗养地；矿泉城 +
• Leamington Spa 利明顿矿泉城 +
• spa waters 矿泉水

2.a place where people can relax and improve their health, with, for example, a swimming pool 休闲健身中心 +
• a superb health spa which includes sauna, Turkish bath and fitness rooms 内设桑拿浴室、土耳其浴室和健身房的第一流的休闲健身中心

3.( especially NAmE )
= Jacuzzi 水流按摩浴缸
====

A: Thank you; that will be all. I’ll take care of 照顧，照料, 處理；負責
it.

B: Look at this one sir, eight thousand dollars
were spent _in one night_ at a place called
”Wild Things”?!

[.my2]
看看这个，先生，在一个叫“野生动物”的地方，一晚上花了八千美元？

A: OK, I get it 我明白了,我懂了!! Thank you for your very
thorough (a.)彻底的；完全的；深入的；细致的 analysis!

'''

== 014. Elementary ‐ I’m in Debt 负债,欠债 (B0014)


