
= American Pageant - 031 (1920-1932)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义

What's going down 怎么回事, APUSH people? Today we're taking a look at politics of the 1920s, and we're also going to start the Great Depression 大萧条. So if you're studying either of those topics, this video is going to help you out.

Politics of the 20s was defined by 以……为特点 really kind of the opposite of the Progressive Era 进步时代. The Progressive Era reforms 进步时代改革 of the previous period -- the administrations 政府任期 of Roosevelt, Taft and Wilson -- are going to be pretty much abandoned 抛弃 in the 1920s. You're not going to see the power of the presidency 总统权力 being used to try to reform society. Instead, you're going to see business and government are going to be intimately linked 紧密相连 during the 1920s.

In fact, all three presidents of the 20s are Republicans 共和党人, and they tend to be relatively conservative 保守的. In 1920 you get the election of Warren G. Harding 沃伦·G·哈定. During his campaign 竞选期间 he promises voters a return to normalcy 回归常态. The country had just finished World War I, we had the Red Scare 红色恐慌, and just kind of wants to get the country back to normal.

We're also going to meet Calvin Coolidge 卡尔文·柯立芝 today, Herbert Hoover 赫伯特·胡佛, and all of these guys are going to be Republicans. And a key part of their presidency 总统任期 is handling business 处理商业事务. In fact, these Republican presidents favor high tariffs 高关税 throughout the decade. And not just high tariffs, but other pro-business policies 亲商政策 -- cutting of corporate tax rates 削减公司税率, and the taxes on the wealthy 富人税 will be lowered. There's going to be a lack of enforcement 执行不力 of Progressive Era antitrust laws 进步时代反垄断法.

One of the first thing Harding does as president early on is the increase of the tariff 关税 in 1922. And all of these -- especially Calvin Coolidge and Herbert Hoover -- are going to favor an economic theory 经济理论 called trickle-down economics 涓滴经济学. And we'll talk about that in just a few more minutes.

In response to 回应 the high U.S. tariffs of the decade, Europe reacts and raises their own tariffs. And this basically slows down 减缓 global trade 全球贸易 because countries are basically having tariff wars 关税战 with one another, reducing the amount of trade going on between nations.

This close relationship with business led to some scandals 丑闻 and corruption 腐败. And most famously under the administration of Warren G. Harding, the Teapot Dome scandal 茶壶山丑闻 occurs. Under Harding and his Secretary of the Interior 内政部长 Albert Fall accepted bribes 受贿 in exchange for 以……交换 leasing 出租 government land to oil companies. So he's profiting 获利 by giving away 出让 government land to these oil companies.

Unfortunately for Warren G. Harding, his administration was plagued with 饱受……困扰 a lot of corruption even though he himself was not corrupt. And in August of 1923, he dies while in office 在职期间 and Calvin Coolidge becomes president.

Quick little story about Calvin Coolidge -- his nickname 绰号 was Silent Cal. One person came up to him once and said, "Mr. Coolidge, I've made a bet 打赌 against a fellow who said it was impossible to get more than two words out of you." And Coolidge replied, "You lose." Get it? Two words.

Quick rundown 简要概述 of Calvin Coolidge and Herbert Hoover. Calvin Coolidge continued the pro-business policies 亲商政策 of Harding. In fact one of the most remarkable things about Coolidge is that campaign sign 竞选标语 -- not much else is happening under Coolidge. His famous quote 名言: "The business of America is business." He also is the guy who signs the National Origins Act of 1924 1924年《国家 Origins 法案》 which keeps out 阻止……进入 immigrants from Southern and Eastern Europe.

He easily wins the election of 1924. However, you'll notice in the green there is a third party 第三方政党 -- Robert La Follette runs as a Progressive Party candidate 进步党候选人, and he does surprisingly well especially amongst farmers and workers. So there is some frustration 不满 from voters over these conservative economic times 保守的经济时期.

Coolidge will not run again in 1928, choosing to step aside 让位. But it's important you keep in mind that the decade of the Roaring 20s did not roar economically 经济繁荣 for all groups -- especially when it comes to farmers and unions 工会.

In fact, union membership 工会会员人数 declined 下降 throughout the 1920s. Workers' wages did rise, but union membership declines. And really this is a result of many companies favoring an open shop 开放工厂（指不强制工人加入工会的工厂） -- which means jobs are open to non-union workers 非工会工人. There was a general anti-union sentiment 反工会情绪 throughout the 1920s. Events such as the Red Scare, the Palmer Raids 帕尔默突袭行动 had turned public opinion 公众舆论 further against labor unions 工会.

Some companies practiced what was known as welfare capitalism 福利资本主义 where they were voluntarily offering 自愿提供 higher wages and benefits 福利 in the hopes that this would reduce the interest of workers in joining a union 加入工会的意愿. Henry Ford famously used this approach 方法.

Farmers are also having a difficult time, especially once World War I ends. Because following World War I, there was less demand for crops 农作物需求减少 from not only domestic markets 国内市场 but also international markets. The farmers were growing a huge amount of stuff during the war, taking out loans 贷款 to increase production, and when the war ends that demand shrinks 缩减.

Advances in technology 技术进步 also cause problems for farmers because as technology became more efficient 高效, this led to a huge increase in production 产量大幅增加. And if you have too much supply 供应过剩, it leads to lower prices 价格下跌. And farmers throughout the decade are going to be deeply in debt 深陷债务 as a result.

Hoover is a key figure 关键人物 in the 1920s. He runs in the election of 1928 as Calvin Coolidge steps aside. The Republican Party nominates 提名 Hoover. If you recall, he was the guy during World War I -- he ran the U.S. Food Administration 美国食品管理局, and he served under not only the administrations of Wilson but also Harding and Coolidge.

He runs against a Democrat 民主党人 from New York -- the governor of New York Alfred Smith. And Smith had a few things going against him 对他不利. One was his religion 宗教信仰. His religion plays a role in the campaign 竞选活动, and in this cartoon 漫画 you can see that people are afraid that the pope 教皇 would have some sort of influence over American politics 美国政治. So there was open prejudice 公开的偏见 during the campaign amongst some Protestants 新教徒 because of Alfred Smith's religion.

Smith also opposed prohibition 禁酒令, which made him popular amongst immigrants but also people in urban areas 城市地区. But it did not matter because in 1928 Hoover easily wins the presidency 总统职位.

Another important thing to keep in mind in the 1920s is international affairs 国际事务. And there's this perception 看法 that the United States -- because we said no, we rejected the League of Nations 国际联盟 -- that somehow we were completely isolationist 孤立主义的. And this is not entirely true.

In the 1920s the U.S. does not entirely withdraw from 完全退出 world affairs. Many people in America were disillusioned with 对……失望 World War I -- it seemed like a pointless war 无意义的战争. But America is still going to pursue American interests 追求美国利益 in the world where they see fit 在认为合适的地方.

One of the most significant 重要的 foreign policy events 外交政策事件 of the 1920s is the Washington Naval Arms Conference 华盛顿海军军备会议 in 1921. And this agreement 协议 between different nations was calling for 呼吁 the reduction of naval battleships 海军战舰 in the world. And there's two goals here: one to promote peace 促进和平 especially in the Pacific in Asia, but also there's a need -- or a desire rather -- to reduce defense spending 削减国防开支 especially amongst conservative Republican presidents.

There's a series of treaties 一系列条约 -- there's the Five-Power Treaty 五国条约, the Four-Power Treaty 四国条约 and the Nine-Power Treaty 九国条约. You can hit pause 暂停 and kind of read what they do, but just know they all come out of this naval arms conference.

The Kellogg-Briand Pact 凯洛格 - 白里安公约 is kind of one of these silly things that gets agreed upon 达成一致 in 1928. And basically what this is is many nations sign this agreement which outlaws war 宣布战争为非法. However, there's some problems here: one you can't really enforce it 执行, and two it allowed for defensive wars 自卫战争. So the chances of this thing actually working are not very good.

One of the key things America does do when it comes to foreign policy 外交政策 and the 1920s is in the area of international finance 国际金融. Following World War I, the U.S. becomes a creditor nation 债权国 for the first time in our history. We loan large amounts of money 大量贷款 to European countries that are recovering from World War I. Previously we're a debtor nation 债务国, now we're loaning out the money.

However, European nations were slow to recover from World War I and to repay the war debts 偿还战争债务 to the United States. And this really causes deep concern 深切担忧 in the U.S. And it is further complicated by 进一步复杂化 the fact that high tariffs weakened and slowed down international trade 国际贸易.

Germany could not pay its war reparations 战争赔款 to France and England. Germany was bankrupt 破产 and inflation 通货膨胀 was a major problem which further hurt the international economic situation 国际经济形势. And so under U.S. leadership, the Dawes Plan 道威斯计划 was developed in 1924. And this plan adjusted German reparations payments 调整德国赔款支付. And here's what it did: American banks would loan money to Germany to help them rebuild and help pay reparations to England and France. And the idea here is Germany would then be able to pay England and France who would then use their reparations payments from Germany to pay back loans to the United States.

So the Dawes Plan reschedules 重新安排 the German reparation loans, and it's intended to improve the economic situation in Europe. However, this plan ends with the stock market crash 股市崩盘 in 1929 as not only the United States but the entire world spirals into 陷入 an economic depression 经济大萧条.

It's important you know how the Great Depression begins. And really most people know it's the stock market crash in October of 1929 that begins this. What was happening is there was tremendous speculation 投机买卖 in the prices of stocks 股票价格. People were buying on margin 保证金交易 where they would take out loans 贷款 to buy stock with the hopes that the price would go up and then they would be able to sell and make a quick buck 快速赚钱.

However, what happens is on October 29th, 1929 -- Black Tuesday 黑色星期二 -- over 16 million shares of stock 股票份额 are sold and the price of stock plummets 暴跌. This is really the start of the Great Depression. Important to note this is an economic collapse 经济崩溃 in both the U.S. and abroad.

Massive unemployment 大规模失业 is going to take place. By 1933, 25% of the nation is unemployed. Thousands of banks fail 倒闭 following this stock market crash. People's savings literally vanishes 消失. Foreclosures 止赎 of homes and farms become quite common 常见. And it's only with the help of soup kitchens 施粥所 and bread lines 领救济面包的队伍 that people get any sense of relief 得到一点救济 at all. In fact, many people lived in shanty towns 棚户区 that they nickname Hoovervilles 胡佛村 once they lost their home and farm.

However, it's not just the stock market that causes this Great Depression. There in fact were deeper roots 深层根源 that are important to understand. One of the big causes of the Great Depression was the overproduction 生产过剩 in both agriculture 农业 and industry 工业. The nation was producing more goods than could be consumed 消费. One of the reasons for this was increased productivity 提高的生产力 allowed for things to be produced much more efficiently than in the past.

But adding to this problem was the fact that workers' wages did not increase enough. There was an uneven distribution of wealth 财富分配不均 throughout the decade. The economic roar 经济繁荣 wasn't equally felt by all. Corporate profits skyrocketed 飙升, but workers could not afford the goods that industry was producing.

And with that, you see throughout the decade of the 1920s there was an overreliance on credit 过度依赖信贷. The installment plan 分期付款计划 -- buying things on credit -- overstimulated consumer buying 过度刺激消费. And once people accumulated too much debt 累积太多债务 and could not pay back these loans 偿还贷款, you have the defaults on loans 贷款违约 causing bank failures 银行倒闭. And since there were no regulations 监管 kind of keeping the whole system in check 控制整个系统, this becomes a huge economic depression.

Add to this the international economic problems of war reparations, the fact that England and France could not pay back war debts or were reluctant to 不愿偿还, and the high tariffs of the Republican administrations which slow down trade. All of these things contributed to 导致 the beginnings of the Great Depression.

So what's Hoover's response going to be? He did not cause the Great Depression, but the American people are looking to him as the president to somehow address this crisis 应对危机. Initially Hoover was a rugged individualist 坚定的个人主义者 and he opposed government intervention 政府干预. He believed in individual industry 个人勤奋, thrift 节俭, hard work and self-reliance 自力更生.

He does do something in the beginning stages which is actually really bad for the economy -- it's the Hawley-Smoot Tariff of 1930 1930年霍利 - 斯穆特关税法. It's the highest peacetime protective tariff 和平时期最高保护性关税. And European nations reply to our high tariff by creating their own high tariffs. And this once again worsens the depression 加剧大萧条 in both America and abroad. It further slows down trade 减缓贸易.

As the economic problems continue, Hoover decides he needs to take some sort of federal action 联邦行动 -- that this was not just going to correct itself 自行解决. And one of the most important things under Hoover is the Reconstruction Finance Corporation 复兴金融公司 of 1932. The RFC gives federal money 联邦资金 to struggling businesses 陷入困境的企业 in the hope that the benefits would then trickle down to 涓滴到 the rest of the economy. In effect, the federal government would provide money to banks, railroads and other financial institutions 金融机构 to prop them up 支撑, and the idea that money would then trickle down to the workers and the rest of the economy. These businesses by getting this federal money would stabilize wages 稳定工资, reduce layoffs 减少裁员 and other things which would help limit the impacts of the Great Depression.

Important to note under the RFC is that individuals would not be getting money from the government -- it would be going to business. This is the idea of trickle-down economics 涓滴经济学. However by 1932, things continued to be a hot mess 一团糟 in the United States. Millions of people were unemployed. Many farmers were losing their farms. And veterans of World War I -- like many other Americans -- were suffering a great deal 遭受巨大痛苦.

And a group of people known as the Bonus Expeditionary Force 补助金远征军 -- nicknamed the Bonus Army 补助金大军 -- about 20,000 veterans of World War I march 游行 from across the country to Washington D.C. to demand an immediate payment of their bonus 立即支付补助金. They were supposed to get a bonus in 1945 as a way of supporting them in old age 养老. And in 1932 they say we need it now -- government pay us.

They set up temporary housing 临时住所 around D.C. known as Hoovervilles -- named after the president who many people blamed 归咎于. And after some time, Hoover sends the Army in to clear out 清除 the veterans -- to get rid of them. He did not think it would go down as aggressively as it did. But basically Hoover -- led by a guy by the name of Douglas MacArthur 道格拉斯·麦克阿瑟 -- will break up 驱散 the Hoovervilles and force the veterans to go home. Tear gas 催泪瓦斯 and bayonets 刺刀 and violence breaks out 爆发. And this further tarnishes the reputation 损害声誉 of President Hoover.

And in 1932, Hoover is going to have to run against Franklin Roosevelt 富兰克林·罗斯福. And we'll see how that election turns out next time.

That's going to do it for today. If the video helped you out, click like 点赞. If you haven't already done so, subscribe 订阅. And make sure you tell all your classmates. Keep studying for APUSH. If you have any questions, post them in the comment section 评论区. And have a beautiful day. Peace 再见.

'''


== 中文翻译

APUSH的同学们，大家好！今天我们要探讨1920年代的政治，并且开始介绍大萧条。所以，如果你正在学习这两个主题中的任何一个，这个视频将对你有所帮助。

20年代的政治的特点实际上与进步时代截然相反。进步时代前一时期——罗斯福、塔夫脱和威尔逊政府的改革——在1920年代基本上被抛弃了。你们不会看到总统权力被用来试图改革社会。相反，你们会看到在1920年代，商业和政府将紧密地联系在一起。

事实上，20年代的三位总统都是共和党人，他们往往相对保守。1920年，沃伦·G·哈丁当选总统。在他的竞选期间，他向选民承诺回归常态。国家刚刚结束第一次世界大战，我们经历了红色恐慌，国家只想恢复正常。

今天我们还将认识卡尔文·柯立芝和赫伯特·胡佛，他们都是共和党人。他们总统任期的关键部分是处理商业。事实上，这些共和党总统在整个十年中都支持高关税。不仅是高关税，还有其他亲商业政策——削减公司税率，富人的税收也将降低。进步时代的《反托拉斯法》的执行将会松懈。

哈丁总统上任之初所做的第一件事就是在1922年提高关税。所有这些——尤其是卡尔文·柯立芝和赫伯特·胡佛——都将支持一种称为涓滴经济学的经济理论。我们将在几分钟后讨论这个问题。

为了回应美国十年来的高关税，欧洲采取行动，提高了他们自己的关税。这基本上减缓了全球贸易，因为各国基本上都在进行关税战，减少了国家之间的贸易额。

这种与商业的密切关系导致了一些丑闻和腐败。最著名的是在沃伦·G·哈丁政府时期发生的茶壶山丑闻。在哈丁及其内政部长阿尔伯特·福尔的领导下，他们接受贿赂以换取将政府土地租赁给石油公司。因此，他通过将政府土地赠送给这些石油公司而获利。

不幸的是，对于沃伦·G·哈丁来说，他的政府充斥着许多腐败行为，尽管他本人并不腐败。1923年8月，他在任上去世，卡尔文·柯立芝成为总统。

关于卡尔文·柯立芝的一个小故事——他的绰号是“沉默的卡尔”。有一次有人走到他面前说：“柯立芝先生，我和一个人打赌，他说你不可能说出两个以上的词。”柯立芝回答说：“你输了。”明白了吗？两个词。

卡尔文·柯立芝和赫伯特·胡佛的简要概述。卡尔文·柯立芝延续了哈丁的亲商业政策。事实上，关于柯立芝最引人注目的一件事就是那个竞选标语——在柯立芝的领导下，并没有发生太多其他事情。他的名言是：“美国的事务就是商业。”他也是签署1924年《国家起源法案》的人，该法案阻止了来自南欧和东欧的移民。

他轻松赢得了1924年的选举。然而，你们会注意到绿色部分有一个第三方——罗伯特·拉福莱特以进步党候选人的身份参选，并且他表现出人意料的好，尤其是在农民和工人中。因此，选民对这些保守的经济时期感到一些不满。

柯立芝在1928年不会再次参选，他选择退居幕后。但重要的是你们要记住，咆哮的二十年代并非所有群体都在经济上咆哮——尤其是在农民和工会方面。

事实上，整个1920年代，工会会员人数都在下降。工人的工资确实上涨了，但工会会员人数却下降了。这实际上是许多公司倾向于开放式商店的结果——这意味着工作对非工会工人开放。整个1920年代普遍存在反工会情绪。“红色恐慌”和“帕尔默搜查”等事件进一步恶化了公众对工会的看法。

一些公司实行所谓的福利资本主义，自愿提供更高的工资和福利，希望这能减少工人加入工会的兴趣。亨利·福特就以这种做法而闻名。

农民也面临困境，尤其是在第一次世界大战结束后。因为第一次世界大战结束后，不仅国内市场而且国际市场对农产品的需求都减少了。战争期间，农民种植了大量的农产品，贷款增加了产量，而战争结束后，需求萎缩了。

技术的进步也给农民带来了问题，因为随着技术变得更加高效，这导致了产量的巨大增加。如果供应过多，就会导致价格下跌。因此，整个十年，农民都将深陷债务之中。

胡佛是1920年代的关键人物。在卡尔文·柯立芝退居幕后之后，他参加了1928年的选举。共和党提名了胡佛。如果你们还记得，他是第一次世界大战期间负责美国食品管理局的人，他不仅在威尔逊政府，而且在哈丁和柯立芝政府中都任职。

他与一位来自纽约的民主党人——纽约州州长阿尔弗雷德·史密斯竞争。史密斯有一些不利因素。其中之一是他的宗教信仰。他的宗教信仰在竞选中发挥了作用，在这幅漫画中你们可以看到，人们担心教皇会对美国政治产生某种影响。因此，在竞选期间，一些新教徒因为阿尔弗雷德·史密斯的宗教信仰而公开抱有偏见。

史密斯也反对禁酒令，这使他在移民和城市居民中很受欢迎。但这并不重要，因为在1928年，胡佛轻松赢得了总统职位。

1920年代另一个需要记住的重要事情是国际事务。有一种看法认为，美国因为拒绝加入国际联盟，所以某种程度上完全是孤立主义的。这并不完全正确。

在1920年代，美国并没有完全退出世界事务。许多美国人对第一次世界大战感到失望——这似乎是一场毫无意义的战争。但美国仍然会在他们认为合适的地方追求美国的全球利益。

1920年代最重要的外交政策事件之一是1921年的华盛顿海军军备会议。不同国家之间的这项协议呼吁削减世界范围内的海军战列舰。这里有两个目标：一是促进和平，尤其是在亚洲的太平洋地区；二是需要——或者更确切地说，是渴望——削减国防开支，尤其是在保守的共和党总统领导下。

有一系列条约——《五国条约》、《四国条约》和《九国条约》。你们可以暂停一下阅读它们的内容，但要知道它们都来自这次海军军备会议。

《凯洛格-白里安条约》有点像是1928年达成的一项愚蠢的协议。基本上，许多国家签署了这项宣布战争为非法的协议。然而，这里存在一些问题：一是你无法真正执行它，二是它允许防御性战争。因此，这项协议真正奏效的可能性不大。

美国在外交政策和1920年代所做的关键事情之一是国际金融领域。第一次世界大战后，美国首次成为我们历史上的债权国。我们向正在从第一次世界大战中恢复的欧洲国家提供了大量贷款。以前我们是债务国，现在我们是贷款国。

然而，欧洲国家从第一次世界大战中恢复缓慢，未能偿还对美国的战争债务。这在美国引起了深切关注。而高关税削弱并减缓了国际贸易，进一步加剧了这种情况。

德国无法向法国和英国支付战争赔款。德国破产了，通货膨胀是一个主要问题，这进一步损害了国际经济形势。因此，在美国的领导下，1924年制定了《道威斯计划》。该计划调整了德国的赔款支付。具体做法是：美国银行向德国提供贷款，帮助他们重建并向英国和法国支付赔款。其想法是，德国然后能够向英国和法国支付款项，英国和法国将利用从德国获得的赔款偿还对美国的贷款。

因此，《道威斯计划》重新安排了德国的赔款贷款，旨在改善欧洲的经济状况。然而，随着美国乃至全世界陷入经济萧条，这项计划随着1929年的股市崩盘而结束。

重要的是你们要知道大萧条是如何开始的。实际上，大多数人都知道，1929年10月的股市崩盘是这一切的开端。当时的情况是，股票价格存在巨大的投机行为。人们进行保证金购买，即贷款购买股票，希望价格上涨，然后他们能够出售并快速获利。

然而，1929年10月29日——黑色星期二——发生了超过1600万股的股票被抛售，股票价格暴跌。这实际上是大萧条的开始。重要的是要注意，这是美国和国外的经济崩溃。

大规模失业将会发生。到1933年，全国25%的人口失业。股市崩盘后，数千家银行倒闭。人们的储蓄几乎消失殆尽。房屋和农场的止赎变得非常普遍。只有通过救济厨房和面包队伍，人们才能获得一丝缓解。事实上，许多人在失去家园和农场后，住在他们戏称为“胡佛村”的棚户区里。

然而，不仅仅是股市导致了大萧条。事实上，还有更深层次的根源需要理解。大萧条的主要原因之一是农业和工业的生产过剩。国家生产的商品超过了消费能力。其中一个原因是生产力的提高使得生产效率远高于过去。

但加剧这个问题的是工人工资没有足够增长的事实。整个十年，财富分配不均。经济的咆哮并非所有人都平等感受到。公司利润飙升，但工人却买不起工业生产的商品。

由此可见，在整个1920年代，人们过度依赖信贷。分期付款——信贷消费——过度刺激了消费者的购买行为。一旦人们积累了过多的债务而无法偿还这些贷款，贷款违约就会导致银行倒闭。由于没有监管来控制整个系统，这演变成了一场巨大的经济萧条。

此外，还有战争赔款带来的国际经济问题，英国和法国无法或不愿偿还战争债务，以及共和党政府的高关税减缓了贸易。所有这些都促成了大萧条的开始。

那么胡佛的反应是什么呢？他并没有导致大萧条，但美国人民指望他这位总统能够以某种方式解决这场危机。最初，胡佛是一个坚定的个人主义者，他反对政府干预。他信奉个人奋斗、节俭、努力工作和自力更生。

他在初期确实采取了一些对经济非常不利的措施——1930年的《霍利-斯姆特关税法》。这是和平时期最高的保护性关税。欧洲国家通过建立他们自己的高关税来回应我们的高关税。这再次加剧了美国和国外的萧条，进一步减缓了贸易。

随着经济问题的持续，胡佛决定他需要采取某种联邦行动——这场危机不会自行解决。胡佛领导下的最重要的措施之一是1932年的复兴金融公司（RFC）。RFC向陷入困境的企业提供联邦资金，希望这些好处能够涓滴到经济的其他领域。实际上，联邦政府将向银行、铁路和其他金融机构提供资金以支持它们，其想法是资金然后会涓滴到工人和其他经济领域。这些企业通过获得联邦资金将稳定工资，减少裁员以及采取其他有助于限制大萧条影响的措施。

重要的是要注意，在RFC的领导下，个人不会从政府那里获得资金——资金将流向企业。这就是涓滴经济学的理念。然而，到1932年，美国的情况仍然一团糟。数百万人失业。许多农民失去了他们的农场。像许多其他美国人一样，第一次世界大战的退伍军人遭受了巨大的痛苦。

一群被称为“奖励远征军”（绰号“奖励军”）的人——大约2万名第一次世界大战的退伍军人从全国各地游行到华盛顿特区，要求立即支付他们的奖励金。他们本应在1945年获得这笔奖励金，作为晚年生活的一种支持。而在1932年，他们说我们现在就需要——政府付钱给我们。

他们在华盛顿特区周围搭建了临时住所，被称为“胡佛村”——以许多人指责的总统的名字命名。过了一段时间，胡佛派军队去清理退伍军人——把他们赶走。他认为情况不会像后来那样激烈。但基本上，在道格拉斯·麦克阿瑟的领导下，胡佛将解散“胡佛村”并强迫退伍军人回家。催泪瓦斯、刺刀和暴力事件爆发。这进一步损害了胡佛总统的声誉。

1932年，胡佛将不得不与富兰克林·罗斯福竞争。我们将在下次看到选举结果如何。

今天就到这里。如果这个视频对你有帮助，请点赞。如果你还没有订阅，请订阅。并确保告诉你的所有同学。继续为APUSH学习。如果你有任何问题，请在评论区留言。祝你度过美好的一天。再见。


'''


== pure

What's going down, APUSH people? Today we're taking a look at politics of the 1920s, and we're also going to start the Great Depression. So if you're studying either of those topics, this video is going to help you out.

Politics of the 20s was defined by really kind of the opposite of the Progressive Era. The Progressive Era reforms of the previous period -- the administrations of Roosevelt, Taft and Wilson -- are going to be pretty much abandoned in the 1920s. You're not going to see the power of the presidency being used to try to reform society. Instead, you're going to see business and government are going to be intimately linked during the 1920s.

In fact, all three presidents of the 20s are Republicans, and they tend to be relatively conservative. In 1920 you get the election of Warren G. Harding. During his campaign he promises voters a return to normalcy. The country had just finished World War I, we had the Red Scare, and just kind of wants to get the country back to normal.

We're also going to meet Calvin Coolidge today, Herbert Hoover, and all of these guys are going to be Republicans. And a key part of their presidency is handling business. In fact, these Republican presidents favor high tariffs throughout the decade. And not just high tariffs, but other pro-business policies -- cutting of corporate tax rates, and the taxes on the wealthy will be lowered. There's going to be a lack of enforcement of Progressive Era antitrust laws.

One of the first thing Harding does as president early on is the increase of the tariff in 1922. And all of these -- especially Calvin Coolidge and Herbert Hoover -- are going to favor an economic theory called trickle-down economics. And we'll talk about that in just a few more minutes.

In response to the high U.S. tariffs of the decade, Europe reacts and raises their own tariffs. And this basically slows down global trade because countries are basically having tariff wars with one another, reducing the amount of trade going on between nations.

This close relationship with business led to some scandals and corruption. And most famously under the administration of Warren G. Harding, the Teapot Dome scandal occurs. Under Harding and his Secretary of the Interior Albert Fall accepted bribes in exchange for leasing government land to oil companies. So he's profiting by giving away government land to these oil companies.

Unfortunately for Warren G. Harding, his administration was plagued with a lot of corruption even though he himself was not corrupt. And in August of 1923, he dies while in office and Calvin Coolidge becomes president.

Quick little story about Calvin Coolidge -- his nickname was Silent Cal. One person came up to him once and said, "Mr. Coolidge, I've made a bet against a fellow who said it was impossible to get more than two words out of you." And Coolidge replied, "You lose." Get it? Two words.

Quick rundown of Calvin Coolidge and Herbert Hoover. Calvin Coolidge continued the pro-business policies of Harding. In fact one of the most remarkable things about Coolidge is that campaign sign -- not much else is happening under Coolidge. His famous quote: "The business of America is business." He also is the guy who signs the National Origins Act of 1924 which keeps out immigrants from Southern and Eastern Europe.

He easily wins the election of 1924. However, you'll notice in the green there is a third party -- Robert La Follette runs as a Progressive Party candidate, and he does surprisingly well especially amongst farmers and workers. So there is some frustration from voters over these conservative economic times.

Coolidge will not run again in 1928, choosing to step aside. But it's important you keep in mind that the decade of the Roaring 20s did not roar economically for all groups -- especially when it comes to farmers and unions.

In fact, union membership declined throughout the 1920s. Workers' wages did rise, but union membership declines. And really this is a result of many companies favoring an open shop -- which means jobs are open to non-union workers. There was a general anti-union sentiment throughout the 1920s. Events such as the Red Scare, the Palmer Raids had turned public opinion further against labor unions.

Some companies practiced what was known as welfare capitalism where they were voluntarily offering higher wages and benefits in the hopes that this would reduce the interest of workers in joining a union. Henry Ford famously used this approach.

Farmers are also having a difficult time, especially once World War I ends. Because following World War I, there was less demand for crops from not only domestic markets but also international markets. The farmers were growing a huge amount of stuff during the war, taking out loans to increase production, and when the war ends that demand shrinks.

Advances in technology also cause problems for farmers because as technology became more efficient, this led to a huge increase in production. And if you have too much supply, it leads to lower prices. And farmers throughout the decade are going to be deeply in debt as a result.

Hoover is a key figure in the 1920s. He runs in the election of 1928 as Calvin Coolidge steps aside. The Republican Party nominates Hoover. If you recall, he was the guy during World War I -- he ran the U.S. Food Administration, and he served under not only the administrations of Wilson but also Harding and Coolidge.

He runs against a Democrat from New York -- the governor of New York Alfred Smith. And Smith had a few things going against him. One was his religion. His religion plays a role in the campaign, and in this cartoon you can see that people are afraid that the pope would have some sort of influence over American politics. So there was open prejudice during the campaign amongst some Protestants because of Alfred Smith's religion.

Smith also opposed prohibition, which made him popular amongst immigrants but also people in urban areas. But it did not matter because in 1928 Hoover easily wins the presidency.

Another important thing to keep in mind in the 1920s is international affairs. And there's this perception that the United States -- because we said no, we rejected the League of Nations -- that somehow we were completely isolationist. And this is not entirely true.

In the 1920s the U.S. does not entirely withdraw from world affairs. Many people in America were disillusioned with World War I -- it seemed like a pointless war. But America is still going to pursue American interests in the world where they see fit.

One of the most significant kind of foreign policy events of the 1920s is the Washington Naval Arms Conference in 1921. And this agreement between different nations was calling for the reduction of naval battleships in the world. And there's two goals here: one to promote peace especially in the Pacific in Asia, but also there's a need -- or a desire rather -- to reduce defense spending especially amongst conservative Republican presidents.

There's a series of treaties -- there's the Five-Power Treaty, the Four-Power Treaty and the Nine-Power Treaty. You can hit pause and kind of read what they do, but just know they all come out of this naval arms conference.

The Kellogg-Briand Pact is kind of one of these silly things that gets agreed upon in 1928. And basically what this is is many nations sign this agreement which outlaws war. However, there's some problems here: one you can't really enforce it, and two it allowed for defensive wars. So the chances of this thing actually working are not very good.

One of the key things America does do when it comes to foreign policy and the 1920s is in the area of international finance. Following World War I, the U.S. becomes a creditor nation for the first time in our history. We loan large amounts of money to European countries that are recovering from World War I. Previously we're a debtor nation, now we're loaning out the money.

However, European nations were slow to recover from World War I and to repay the war debts to the United States. And this really causes deep concern in the U.S. And it is further complicated by the fact that high tariffs weakened and slowed down international trade.

Germany could not pay its war reparations to France and England. Germany was bankrupt and inflation was a major problem which further hurt the international economic situation. And so under U.S. leadership, the Dawes Plan was developed in 1924. And this plan adjusted German reparations payments. And here's what it did: American banks would loan money to Germany to help them rebuild and help pay reparations to England and France. And the idea here is Germany would then be able to pay England and France who would then use their reparations payments from Germany to pay back loans to the United States.

So the Dawes Plan reschedules the German reparation loans, and it's intended to improve the economic situation in Europe. However, this plan ends with the stock market crash in 1929 as not only the United States but the entire world spirals into an economic depression.

It's important you know how the Great Depression begins. And really most people know it's the stock market crash in October of 1929 that begins this. What was happening is there was tremendous speculation in the prices of stocks. People were buying on margin where they would take out loans to buy stock with the hopes that the price would go up and then they would be able to sell and make a quick buck.

However, what happens is on October 29th, 1929 -- Black Tuesday -- over 16 million shares of stock are sold and the price of stock plummets. This is really the start of the Great Depression. Important to note this is an economic collapse in both the U.S. and abroad.

Massive unemployment is going to take place. By 1933, 25% of the nation is unemployed. Thousands of banks fail following this stock market crash. People's savings literally vanishes. Foreclosures of homes and farms become quite common. And it's only with the help of soup kitchens and bread lines that people get any sense of relief at all. In fact, many people lived in shanty towns that they nickname Hoovervilles once they lost their home and farm.

However, it's not just the stock market that causes this Great Depression. There in fact were deeper roots that are important to understand. One of the big causes of the Great Depression was the overproduction in both agriculture and industry. The nation was producing more goods than could be consumed. One of the reasons for this was increased productivity allowed for things to be produced much more efficiently than in the past.

But adding to this problem was the fact that workers' wages did not increase enough. There was an uneven distribution of wealth throughout the decade. The economic roar wasn't equally felt by all. Corporate profits skyrocketed, but workers could not afford the goods that industry was producing.

And with that, you see throughout the decade of the 1920s there was an overreliance on credit. The installment plan -- buying things on credit -- overstimulated consumer buying. And once people accumulated too much debt and could not pay back these loans, you have the defaults on loans causing bank failures. And since there were no regulations kind of keeping the whole system in check, this becomes a huge economic depression.

Add to this the international economic problems of war reparations, the fact that England and France could not pay back war debts or were reluctant to, and the high tariffs of the Republican administrations which slow down trade. All of these things contributed to the beginnings of the Great Depression.

So what's Hoover's response going to be? He did not cause the Great Depression, but the American people are looking to him as the president to somehow address this crisis. Initially Hoover was a rugged individualist and he opposed government intervention. He believed in individual industry, thrift, hard work and self-reliance.

He does do something in the beginning stages which is actually really bad for the economy -- it's the Hawley-Smoot Tariff of 1930. It's the highest peacetime protective tariff. And European nations reply to our high tariff by creating their own high tariffs. And this once again worsens the depression in both America and abroad. It further slows down trade.

As the economic problems continue, Hoover decides he needs to take some sort of federal action -- that this was not just going to correct itself. And one of the most important things under Hoover is the Reconstruction Finance Corporation of 1932. The RFC gives federal money to struggling businesses in the hope that the benefits would then trickle down to the rest of the economy. In effect, the federal government would provide money to banks, railroads and other financial institutions to prop them up, and the idea that money would then trickle down to the workers and the rest of the economy. These businesses by getting this federal money would stabilize wages, reduce layoffs and other things which would help limit the impacts of the Great Depression.

Important to note under the RFC is that individuals would not be getting money from the government -- it would be going to business. This is the idea of trickle-down economics. However by 1932, things continued to be a hot mess in the United States. Millions of people were unemployed. Many farmers were losing their farms. And veterans of World War I -- like many other Americans -- were suffering a great deal.

And a group of people known as the Bonus Expeditionary Force -- nicknamed the Bonus Army -- about 20,000 veterans of World War I march from across the country to Washington D.C. to demand an immediate payment of their bonus. They were supposed to get a bonus in 1945 as a way of supporting them in old age. And in 1932 they say we need it now -- government pay us.

They set up temporary housing around D.C. known as Hoovervilles -- named after the president who many people blamed. And after some time, Hoover sends the Army in to clear out the veterans -- to get rid of them. He did not think it would go down as aggressively as it did. But basically Hoover -- led by a guy by the name of Douglas MacArthur -- will break up the Hoovervilles and force the veterans to go home. Tear gas and bayonets and violence breaks out. And this further tarnishes the reputation of President Hoover.

And in 1932, Hoover is going to have to run against Franklin Roosevelt. And we'll see how that election turns out next time.

That's going to do it for today. If the video helped you out, click like. If you haven't already done so, subscribe. And make sure you tell all your classmates. Keep studying for APUSH. If you have any questions, post them in the comment section. And have a beautiful day. Peace.

'''
