
= American Pageant - 046 (1844-1877)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义

What up APUSH people? 怎么了，美国历史课程（APUSH）的同学们？Today we're going to take a look at 看一看 period 5 key concept 5.1, and the key idea for this concept 5.1 is the idea of manifest destiny 天定命运论 and the movement West 西进运动 will have a variety of economic, political, and social consequences 后果.

You know, in this period -- in the 1840s all the way up until the 1870s -- you have huge amount of Irish immigrants 爱尔兰移民 coming into the country, and they're leaving Ireland because of a potato crop failure 马铃薯歉收 and severe famine 严重饥荒, especially in the 1840s. They're largely going to settle in 定居于 cities like New York and Boston, and they're going to be working in unskilled laborer type jobs 非技术性劳工工作. And as a result of this, there's going to be a tremendous amount of competition 巨大的竞争 with African-Americans, which is going to lead to 导致 racial tensions 种族紧张局势 in Northern cities.

Politically, the Irish are going to be very important because they are going to largely support the Democratic party 民主党. In fact, by the 1870s and 1880s, the political machine 政治集团 Tammany Hall 坦慕尼协会 in New York is going to be heavily influenced by 深受……影响 Irish voters 爱尔兰选民.

The second biggest group of immigrants coming into the United States during this time period are the Germans, and they're very diverse group of people 多样化的人群. Germany is not a unified nation 统一的国家 yet by this time. There's a mix of German immigrants coming in -- a mix of religions: Protestants 新教徒, Catholics 天主教徒, Jews 犹太人. They're coming from a variety of social classes 社会阶层: lower, middle income, and wealthy. Different occupations 职业. And unlike the Irish, the Germans are going to largely settle in the old Northwest 旧西北地区 and in the frontier 边疆 on homesteads 农庄, and they're going to develop these very tight-knit German communities 紧密团结的德国社区.

As a result of this change of who's coming to America -- these Irish and German immigrants -- you have a rise in nativist 本土主义者的 or anti-immigrant feelings 反移民情绪. And there's a variety of reasons and motives 动机. One, there's this feeling especially the Irish are taking jobs from native-born white Americans 土生土长的美国白人 because they're willing to work for such low wages 低工资. There's also this concern that they're going to somehow outvote 投票数超过 or take over American politics 掌控美国政治, as you see that being expressed in the political cartoon 政治漫画. There's this belief that they're going to ruin American Anglo-Saxon culture 盎格鲁 - 撒克逊文化 with their inferior racial makeup 劣等的种族构成. And of course, especially for the Irish, there's a huge concern because many of them are Catholics 天主教徒, and there's this fear that somehow they're going to ruin this idea of a Protestant white Anglo-Saxon America 新教白人盎格鲁 - 撒克逊美国.

There's going to be political groups that are going to form -- the Order of the Star-Spangled Banner 星条旗勋章会, later on forming a political group called the Know-Nothing party 一无所知党. They're a group of American nativists 美国本土主义者, and they're going to advocate for 倡导 restrictions on immigration 移民限制 throughout this period. And an important concept to keep in mind though is America was becoming more and more ethnically and racially diverse 种族多样化的 -- new people are coming into America.

Another key concept to keep in mind is this enthusiasm for 对……的热情 territorial expansion 领土扩张, and this has been a reality of American history way before the 1840s, but it increases and it's based upon 基于 economic, national security interest 国家安全利益, and claims of US racial and cultural superiority 美国种族和文化优越性的主张. And really the big belief in the 1840s is this idea of manifest destiny -- this idea that it was America's destiny 命运 to conquer 征服 and civilize 使文明 the entire continent all the way to the Pacific Ocean 太平洋. This idea is heavily built upon a belief of white superiority 白人优越论 -- that we are somehow going to civilize. You could see that in that painting called American Progress 《美国的进步》.

A lot of examples of American expansion 美国扩张 during this period: 1846 a treaty 条约 is signed by James K. Polk establishing US occupation of Oregon Country 俄勒冈地区 at the 49th parallel 北纬49度线. During the election of 1844, there was these threats of "54-40 or fight." No fight needed, and Oregon would be under US command 在美国控制下. Texas is annexed 吞并 in 1845 by John Tyler just as Polk is getting elected. And of course the big one is the Mexican-American War 美墨战争 which will end in 1848 with the Treaty of Guadalupe Hidalgo 瓜达卢佩 - 伊达尔戈条约, and Mexico is going to lose a huge chunk of 一大块 its territory 领土 to the United States.

Big idea that you also need to keep in mind is new territories 领土 were brought into the Union 联邦 which forced the issue of slavery 奴隶制问题 into the center of national politics 国家政治的核心. They've been trying to compromise 妥协 and avoid it, and inevitably 不可避免地 this is going to lead to a rise in sectionalism 地方主义 which we're going to cover in the lecture on key concept 5.2. In fact, if you click that pony, you'll be transported to that lecture on sectionalism.

Now the other part of this kind of period is this idea of western expansion 西进扩张, and you can see on this map that expansion is taking place over time in the 1850s, '60s, '70s and so on. We've already seen this -- for example, the Mormons 摩门教徒 were seeking religious refuge 宗教避难 from intolerance 不容忍 towards their faith 信仰. In 1847, they settle in Utah territory 犹他地区. In 1848, there's the California Gold Rush 加利福尼亚淘金热 which brings a ton of people into the area, and you get the rise of calls for California to enter into the Union as a free state 自由州.

And a big idea you need to keep in mind when studying this period is that new economic opportunities 经济机会 and religious refuge 宗教避难 out in the west were a key factor in bringing people -- not just white Americans but African-Americans, Asian immigrants from China and all over the world.

Another important idea is this idea of the federal government actively promoting 积极推动 economic development 经济发展 and the movement West 西进运动. You know, there's this idea that a lot of people have that these cowboys got on these stagecoaches 驿马车 and headed west -- this rugged individualism 粗犷的个人主义 -- and this is not entirely true. In fact, economic activities out in the west were largely driven by 很大程度上由……推动 federal government policies 联邦政府政策. For example, in 1862, the Pacific Railroad Act 太平洋铁路法案 was passed during the Civil War 内战 which authorized 授权 the building of the transcontinental railroad 横贯大陆的铁路 along a northern route 北部路线. And you can see those red lines are railroad construction 铁路建设 in the period 1870 to 1890 -- so mass building of the railroad out into the west. And the federal government is going to provide money and land subsidies 补贴 to the railroad companies to construct this development. And the transcontinental railroad is going to play an important role of linking California with the rest of the Union, therefore creating a national market 全国市场.

Another kind of key part of the economic development of the West is the mining booms 矿业热潮 that take place throughout the West. We already talked about in 1848 the California Gold Rush which kind of brings San Francisco up in its population. But similarly, you also have the Comstock Lode 康斯托克矿脉 in Nevada which leads to the growth of cities such as Virginia City 弗吉尼亚城. But you could see whether it be Colorado or future territory of Idaho, mining booms are going to take place throughout this period, and it's going to bring people once again not only from the eastern part of the United States but from other nations such as China and so forth 等等.

Another key part of the economic growth of the West is the movement of people to the trans-Mississippi West 密西西比河以西地区 to start farms 开办农场. You know, when you say the trans-Mississippi West, we're talking about west of the Mississippi all the way to the West Coast 西海岸. And a big part of this was also driven by the federal government. You can see the different crops and agricultural items being developed in this region, but the Homestead Act 宅地法 plays a key role -- once again passed during the Civil War in 1862 -- and it offers public land 公有土地 up to 160 acres 英亩 to any person or family who farmed that land for 5 years. They could buy it for a very small fee 费用, and you get a huge number of people moving west seeking this economic opportunity that was presented and encouraged by the federal government with the Homestead Act.

Now inevitably with this movement West, you're going to have a dramatic environmental impact 巨大的环境影响, and dramatic environmental changes will take place as a result of western expansion 西进扩张. And the biggest example is the huge population decline 数量下降 of the buffalo 野牛. It is killed for a number of reasons: one, to make way for 为……让路 the building of the railroad -- the big large buffalo herds 牛群 got in the way of 妨碍 the railroad operation 铁路运营; to undermine 削弱 Native American resistance 美洲原住民的抵抗 -- if you kill an important part of the Native American society and culture, the buffalo, it's going to hurt the Native Americans' ability to resist white expansion; and of course there's this huge demand for buffalo hide 牛皮 out in the eastern markets 东部市场. And those two images -- the one at the top shows you that drastic decline 急剧下降, and the one at the bottom shows buffalo skulls having been slaughtered 屠宰.

Another key environmental change is the removal of grass 铲除青草 to develop these homesteads on the Great Plains 大平原 -- that area in the light blue -- will lead to soil erosion 土壤侵蚀 and the degradation of the land 土地退化. So the land is going to be used up 耗尽 because it's going to be overplanted 过度种植.

And then finally, the biggest impact will take place on the lives of the Native Americans in the trans-Mississippi West. And there's a whole bunch of different environments out in the west, and Native Americans had adapted to 适应 those environments over many, many years. And it is going to unfortunately lead to brutal conflict 残酷冲突 between American settlers 定居者 and the native people who had called this home for many, many years. The two circled ones are the ones we're going to cover for period five -- we cover the others in period six.

And the expansion of the US leads to conflict with Native Americans. Two examples: Sand Creek Massacre 桑德克里克大屠杀 in 1864 -- a Colorado militia 民兵组织 attack and kill over 100 native people, and it truly is a massacre 大屠杀 because about two-thirds of the victims 受害者 were women and children killed by the militia. And you could see that in the image right there. Another famous example of this conflict takes place at the Battle of Little Bighorn 小大角羊战役 there on the map in 1876. Members of the tribe 部落 inspired by one of their leaders Sitting Bull 坐牛 kill a US Army officer -- General Custer 卡斯特将军 and his men in the Seventh Cavalry 第七骑兵团 are killed. This famous event known as Custer's Last Stand 卡斯特的最后抵抗. So it's a rare defeat 罕见的失败 for the Americans, but shortly after that, the American Army will come in and crush native resistance 镇压原住民抵抗 in the Dakotas 达科他州 and in Montana 蒙大拿州.

And then finally, Native Americans were expected to assimilate into 融入 white society 白人社会 or forced onto reservations 保留地 during this time period. So you're going to see both those things happen unfortunately increasingly throughout the late part of the 19th century.

And another key aspect 方面 is following the Treaty of Guadalupe Hidalgo in 1848, the Californios -- the Hispanic residents 西班牙裔居民 of the area -- you see were guaranteed 保障 under the treaty property and citizenship rights 财产和公民权利. And unfortunately very often those rights would not be respected 尊重, and their land would be lost by court actions 法律诉讼 or by forced sale 强制出售 by the Anglo settlers 盎格鲁定居者 coming into the Southwest 西南部. And although that did take place, there will be the preservation of Latino Hispanic culture 拉丁裔西班牙文化 throughout the Southwest although the land was conquered 征服 and taken over 接管.

One last thing that's important for key concept 5.1 is also the US interest in expanding trade 扩大贸易 led to economic, diplomatic 外交的, and cultural initiatives 举措 westward to Asia 向西至亚洲. You get the clipper ships 快速帆船 which allow for faster travel and a boost to 促进 US trade with Asia. You have a treaty in 1844 which is the first diplomatic agreement 外交协议 between the US and China, and its goal was to promote trade 促进贸易 between the two nations. And as a result, many missionaries -- Christian missionaries from the United States -- are going to China trying to spread Christianity 传播基督教. And Japan as well is seen as a place for economic relationship. In Japan opens up which had been isolated for over 200 years, and President Fillmore sends Commodore Matthew Perry 马修·佩里准将 in 1852 to Japan to open up relations 建立关系 between the two nations.

Thanks for checking out key concept 5.1 explained. If you haven't done so, subscribe to Joe's Productions. Tell all the homies and homegirls out in the world to check out these videos to help them with APUSH. If you like the video, click like. If you didn't like it, click like. And as always, thanks for watching. Peace!


'''


== 中文翻译

大家好，APUSH的同学们！今天我们来看一下第五时期的关键概念5.1，这个概念5.1的核心思想是昭昭天命和西进运动将带来各种经济、政治和社会后果。

你们知道，在这个时期——从1840年代一直到1870年代——有大量的爱尔兰移民涌入这个国家，他们离开爱尔兰是因为马铃薯作物歉收和严重的饥荒，尤其是在1840年代。他们主要定居在纽约和波士顿等城市，从事非熟练的体力劳动。结果，与非裔美国人之间将存在巨大的竞争，这将导致北方城市的种族紧张。

在政治上，爱尔兰人将非常重要，因为他们将主要支持民主党。事实上，到1870年代和1880年代，纽约的政治机器坦慕尼协会将受到爱尔兰选民的严重影响。

在此期间进入美国的第二大移民群体是德国人，他们是一个非常多样化的群体。到那时，德国尚未成为一个统一的国家。涌入的德国移民混杂着各种宗教信仰的人：新教徒、天主教徒、犹太人。他们来自不同的社会阶层：下层、中等收入和富裕阶层。职业也各不相同。与爱尔兰人不同，德国人将主要定居在旧西北地区和边疆的宅地上，他们将发展这些非常紧密的德裔社区。

由于来到美国的移民群体发生了变化——这些爱尔兰和德国移民——你们看到了本土主义或反移民情绪的兴起。这有各种各样的原因和动机。第一，尤其有一种感觉，爱尔兰人正在抢走本土白人美国人的工作，因为他们愿意接受如此低的工资。还有一种担忧，他们会以某种方式在选举中胜出或控制美国政治，正如你们在政治漫画中看到的那样。有一种信念，他们将用其劣等的种族构成来破坏美国的盎格鲁-撒克逊文化。当然，特别是对于爱尔兰人来说，存在着巨大的担忧，因为他们中的许多人是天主教徒，人们担心他们会以某种方式破坏这个新教白人盎格鲁-撒克逊美国的理念。

将形成一些政治团体——星条旗会，后来形成了一个名为一无所知党的政治团体。他们是一群美国本土主义者，他们将在整个时期倡导限制移民。然而，一个重要的概念要记住的是，美国正变得越来越具有民族和种族多样性——新的人们正在来到美国。

另一个需要记住的关键概念是对领土扩张的热情，这在1840年代之前很久就是美国历史的现实，但它在经济、国家安全利益以及美国种族和文化优越性的主张的基础上有所增加。1840年代真正的主流信念是昭昭天命——这种认为美国注定要征服和文明整个大陆，一直到太平洋的想法。这种想法很大程度上建立在白人优越论之上——我们不知何故要进行文明化。你们可以在那幅名为《美国进步》的画作中看到这一点。

这一时期美国扩张的许多例子：1846年，詹姆斯·K·波尔克签署了一项条约，确立了美国在北纬49度对俄勒冈地区的占领。在1844年的选举中，曾有“五十四度四十分，否则就开战”的威胁。无需战斗，俄勒冈将置于美国控制之下。1845年，约翰·泰勒在波尔克即将当选时吞并了德克萨斯。当然，最重要的是美墨战争，这场战争将于1848年以《瓜达卢佩-伊达尔戈条约》结束，墨西哥将失去其大片领土给美国。

你们还需要记住的一个重要思想是，新的领土被纳入联邦，这迫使奴隶制问题成为国家政治的中心。他们一直在试图妥协和避免这个问题，但不可避免地，这将导致地区主义的兴起，我们将在关于关键概念5.2的讲座中讨论这一点。事实上，如果你们点击那匹小马，你们将被带到关于地区主义的讲座。

这一时期的另一部分是西进运动的思想，你们可以在这张地图上看到，扩张在1850年代、60年代、70年代及以后随着时间的推移而发生。我们已经看到了这一点——例如，摩门教徒正在寻求宗教庇护，以躲避对他们信仰的不容忍。1847年，他们定居在犹他地区。1848年，加利福尼亚淘金热吸引了大量人口涌入该地区，你们看到了要求加利福尼亚以自由州身份加入联邦的呼声。

在学习这一时期时，你们需要记住的一个重要思想是，西部新的经济机会和宗教庇护是吸引人们——不仅是白人美国人，还有非裔美国人、来自中国和世界各地的亚洲移民——的关键因素。

另一个重要的思想是联邦政府积极促进经济发展和西进运动。你们知道，很多人都有这样一种想法，那些牛仔们坐着驿站马车向西而去——这种坚韧的个人主义——但这并不完全正确。事实上，西部地区的经济活动很大程度上是由联邦政府的政策驱动的。例如，1862年，内战期间通过了《太平洋铁路法案》，该法案授权沿北部路线修建横贯大陆的铁路。你们可以看到那些红线是1870年至1890年期间的铁路建设——大规模的铁路向西部延伸。联邦政府将向铁路公司提供资金和土地补贴以进行这项建设。横贯大陆的铁路将在连接加利福尼亚州与联邦其他地区方面发挥重要作用，从而创建一个全国市场。

西部经济发展的另一个关键部分是遍及西部的矿业繁荣。我们已经讨论过1848年的加利福尼亚淘金热，这使得旧金山的人口大幅增加。但类似地，你们在内华达州也有康斯托克矿脉，这导致了弗吉尼亚城等城市的增长。但你们可以看到，无论是科罗拉多州还是未来的爱达荷州地区，矿业繁荣将在整个时期发生，这将再次吸引人们，不仅来自美国东部，还来自中国等其他国家。

西部经济增长的另一个关键部分是人们向密西西比河以西地区迁移，开始农场。你们知道，当你们说密西西比河以西地区时，我们指的是密西西比河以西一直到西海岸的地区。这在很大程度上也是由联邦政府推动的。你们可以看到该地区正在开发的各种作物和农产品，但《宅地法》发挥了关键作用——该法案再次于1862年内战期间通过——它向任何在该土地上耕种5年的人或家庭提供高达160英亩的公共土地。他们可以以非常低的费用购买它，你们看到了大量的人向西迁移，寻求联邦政府通过《宅地法》提供和鼓励的这种经济机会。

不可避免地，随着这种西进运动，你们将看到巨大的环境影响，西进运动将导致巨大的环境变化。最显著的例子是野牛数量的急剧下降。野牛被杀害的原因有很多：第一，为修建铁路让路——庞大的野牛群妨碍了铁路的运营；第二，削弱美洲原住民的抵抗——如果你们摧毁了美洲原住民社会和文化的重要组成部分——野牛，这将损害美洲原住民抵抗白人扩张的能力；当然，东部市场对野牛皮的需求巨大。那两张图片——顶部的图片显示了急剧的下降，底部的图片显示了被屠杀的野牛头骨。

另一个关键的环境变化是为在大平原（浅蓝色区域）开发宅基地而清除草地，这将导致土壤侵蚀和土地退化。由于过度种植，土地将被耗尽。

最后，最大的影响将发生在密西西比河以西的美洲原住民的生活中。西部有各种不同的环境，美洲原住民多年来已经适应了这些环境。不幸的是，这将导致美国定居者和多年来一直将此地视为家园的当地人民之间发生残酷的冲突。圈出的两个是我们将在第五时期讨论的，我们在第六时期讨论其他的。

美国的扩张导致了与美洲原住民的冲突。两个例子：1864年的沙溪大屠杀——科罗拉多州民兵袭击并杀害了100多名当地人，这确实是一场大屠杀，因为大约三分之二的受害者是妇女和儿童，他们被民兵杀害。你们可以在那张图片中看到这一点。另一个著名的冲突例子发生在地图上1876年的小比格霍恩战役。受其领导人坐牛鼓舞的部落成员杀死了一名美国陆军军官——卡斯特将军和他的第七骑兵团士兵被杀。这一著名事件被称为卡斯特的最后抵抗。这对美国人来说是一次罕见的失败，但此后不久，美国军队将进入并镇压达科他州和蒙大拿州的当地抵抗力量。

最后，在此期间，美洲原住民被期望融入白人社会或被迫进入保留地。因此，不幸的是，你们将在19世纪后期越来越多地看到这两种情况发生。

另一个关键方面是，在1848年《瓜达卢佩-伊达尔戈条约》签订后，加利福尼亚人——该地区的西班牙裔居民——你们看到该条约保证了他们的财产和公民权。不幸的是，这些权利经常得不到尊重，他们的土地将通过诉讼或被涌入西南地区的盎格鲁定居者强行出售而丧失。尽管发生了这种情况，但拉丁裔西班牙文化将在整个西南地区得到保留，尽管土地被征服和占领。

对于关键概念5.1来说，最后一件重要的事情是美国对扩大贸易的兴趣也导致了向亚洲的经济、外交和文化倡议。你们有了快速帆船，这加快了旅行速度，促进了美国与亚洲的贸易。1844年签订了一项条约，这是美国和中国之间的第一个外交协议，其目的是促进两国之间的贸易。结果，许多来自美国的基督教传教士将前往中国，试图传播基督教。日本也被视为建立经济关系的地方。日本开放了，此前它已经与世隔绝了200多年，菲尔莫尔总统于1852年派遣海军准将马修·佩里前往日本，以建立两国之间的关系。

感谢收看关键概念5.1的解释。如果你们还没有订阅乔氏制作频道，请订阅。告诉世界各地的同学们观看这些视频，以帮助他们学习APUSH。如果你们喜欢这个视频，请点赞。如果你们不喜欢，也请点赞。一如既往，感谢观看。再见！

'''


== pure

What up APUSH people? Today we're going to take a look at period 5 key concept 5.1, and the key idea for this concept 5.1 is the idea of manifest destiny and the movement West will have a variety of economic, political, and social consequences.

You know, in this period -- in the 1840s all the way up until the 1870s -- you have huge amount of Irish immigrants coming into the country, and they're leaving Ireland because of a potato crop failure and severe famine, especially in the 1840s. They're largely going to settle in cities like New York and Boston, and they're going to be working in unskilled laborer type jobs. And as a result of this, there's going to be a tremendous amount of competition with African-Americans, which is going to lead to racial tensions in Northern cities.

Politically, the Irish are going to be very important because they are going to largely support the Democratic party. In fact, by the 1870s and 1880s, the political machine Tammany Hall in New York is going to be heavily influenced by Irish voters.

The second biggest group of immigrants coming into the United States during this time period are the Germans, and they're very diverse group of people. Germany is not a unified nation yet by this time. There's a mix of German immigrants coming in -- a mix of religions: Protestants, Catholics, Jews. They're coming from a variety of social classes: lower, middle income, and wealthy. Different occupations. And unlike the Irish, the Germans are going to largely settle in the old Northwest and in the frontier on homesteads, and they're going to develop these very tight-knit German communities.

As a result of this change of who's coming to America -- these Irish and German immigrants -- you have a rise in nativist or anti-immigrant feelings. And there's a variety of reasons and motives. One, there's this feeling especially the Irish are taking jobs from native-born white Americans because they're willing to work for such low wages. There's also this concern that they're going to somehow outvote or take over American politics, as you see that being expressed in the political cartoon. There's this belief that they're going to ruin American Anglo-Saxon culture with their inferior racial makeup. And of course, especially for the Irish, there's a huge concern because many of them are Catholics, and there's this fear that somehow they're going to ruin this idea of a Protestant white Anglo-Saxon America.

There's going to be political groups that are going to form -- the Order of the Star-Spangled Banner, later on forming a political group called the Know-Nothing party. They're a group of American nativists, and they're going to advocate for restrictions on immigration throughout this period. And an important concept to keep in mind though is America was becoming more and more ethnically and racially diverse -- new people are coming into America.

Another key concept to keep in mind is this enthusiasm for territorial expansion, and this has been a reality of American history way before the 1840s, but it increases and it's based upon economic, national security interest, and claims of US racial and cultural superiority. And really the big belief in the 1840s is this idea of manifest destiny -- this idea that it was America's destiny to conquer and civilize the entire continent all the way to the Pacific Ocean. This idea is heavily built upon a belief of white superiority -- that we are somehow going to civilize. You could see that in that painting called American Progress.

A lot of examples of American expansion during this period: 1846 a treaty is signed by James K. Polk establishing US occupation of Oregon Country at the 49th parallel. During the election of 1844, there was these threats of "54-40 or fight." No fight needed, and Oregon would be under US command. Texas is annexed in 1845 by John Tyler just as Polk is getting elected. And of course the big one is the Mexican-American War which will end in 1848 with the Treaty of Guadalupe Hidalgo, and Mexico is going to lose a huge chunk of its territory to the United States.

Big idea that you also need to keep in mind is new territories were brought into the Union which forced the issue of slavery into the center of national politics. They've been trying to compromise and avoid it, and inevitably this is going to lead to a rise in sectionalism which we're going to cover in the lecture on key concept 5.2. In fact, if you click that pony, you'll be transported to that lecture on sectionalism.

Now the other part of this kind of period is this idea of western expansion, and you can see on this map that expansion is taking place over time in the 1850s, '60s, '70s and so on. We've already seen this -- for example, the Mormons were seeking religious refuge from intolerance towards their faith. In 1847, they settle in Utah territory. In 1848, there's the California Gold Rush which brings a ton of people into the area, and you get the rise of calls for California to enter into the Union as a free state.

And a big idea you need to keep in mind when studying this period is that new economic opportunities and religious refuge out in the west were a key factor in bringing people -- not just white Americans but African-Americans, Asian immigrants from China and all over the world.

Another important idea is this idea of the federal government actively promoting economic development and the movement West. You know, there's this idea that a lot of people have that these cowboys got on these stagecoaches and headed west -- this rugged individualism -- and this is not entirely true. In fact, economic activities out in the west were largely driven by federal government policies. For example, in 1862, the Pacific Railroad Act was passed during the Civil War which authorized the building of the transcontinental railroad along a northern route. And you can see those red lines are railroad construction in the period 1870 to 1890 -- so mass building of the railroad out into the west. And the federal government is going to provide money and land subsidies to the railroad companies to construct this development. And the transcontinental railroad is going to play an important role of linking California with the rest of the Union, therefore creating a national market.

Another kind of key part of the economic development of the West is the mining booms that take place throughout the West. We already talked about in 1848 the California Gold Rush which kind of brings San Francisco up in its population. But similarly, you also have the Comstock Lode in Nevada which leads to the growth of cities such as Virginia City. But you could see whether it be Colorado or future territory of Idaho, mining booms are going to take place throughout this period, and it's going to bring people once again not only from the eastern part of the United States but from other nations such as China and so forth.

Another key part of the economic growth of the West is the movement of people to the trans-Mississippi West to start farms. You know, when you say the trans-Mississippi West, we're talking about west of the Mississippi all the way to the West Coast. And a big part of this was also driven by the federal government. You can see the different crops and agricultural items being developed in this region, but the Homestead Act plays a key role -- once again passed during the Civil War in 1862 -- and it offers public land up to 160 acres to any person or family who farmed that land for 5 years. They could buy it for a very small fee, and you get a huge number of people moving west seeking this economic opportunity that was presented and encouraged by the federal government with the Homestead Act.

Now inevitably with this movement West, you're going to have a dramatic environmental impact, and dramatic environmental changes will take place as a result of western expansion. And the biggest example is the huge population decline of the buffalo. It is killed for a number of reasons: one, to make way for the building of the railroad -- the big large buffalo herds got in the way of the railroad operation; to undermine Native American resistance -- if you kill an important part of the Native American society and culture, the buffalo, it's going to hurt the Native Americans' ability to resist white expansion; and of course there's this huge demand for buffalo hide out in the eastern markets. And those two images -- the one at the top shows you that drastic decline, and the one at the bottom shows buffalo skulls having been slaughtered.

Another key environmental change is the removal of grass to develop these homesteads on the Great Plains -- that area in the light blue -- will lead to soil erosion and the degradation of the land. So the land is going to be used up because it's going to be overplanted.

And then finally, the biggest impact will take place on the lives of the Native Americans in the trans-Mississippi West. And there's a whole bunch of different environments out in the west, and Native Americans had adapted to those environments over many, many years. And it is going to unfortunately lead to brutal conflict between American settlers and the native people who had called this home for many, many years. The two circled ones are the ones we're going to cover for period five -- we cover the others in period six.

And the expansion of the US leads to conflict with Native Americans. Two examples: Sand Creek Massacre in 1864 -- a Colorado militia attack and kill over 100 native people, and it truly is a massacre because about two-thirds of the victims were women and children killed by the militia. And you could see that in the image right there. Another famous example of this conflict takes place at the Battle of Little Bighorn there on the map in 1876. Members of the tribe inspired by one of their leaders Sitting Bull kill a US Army officer -- General Custer and his men in the Seventh Cavalry are killed. This famous event known as Custer's Last Stand. So it's a rare defeat for the Americans, but shortly after that, the American Army will come in and crush native resistance in the Dakotas and in Montana.

And then finally, Native Americans were expected to assimilate into white society or forced onto reservations during this time period. So you're going to see both those things happen unfortunately increasingly throughout the late part of the 19th century.

And another key aspect is following the Treaty of Guadalupe Hidalgo in 1848, the Californios -- the Hispanic residents of the area -- you see were guaranteed under the treaty property and citizenship rights. And unfortunately very often those rights would not be respected, and their land would be lost by court actions or by forced sale by the Anglo settlers coming into the Southwest. And although that did take place, there will be the preservation of Latino Hispanic culture throughout the Southwest although the land was conquered and taken over.

One last thing that's important for key concept 5.1 is also the US interest in expanding trade led to economic, diplomatic, and cultural initiatives westward to Asia. You get the clipper ships which allow for faster travel and a boost to US trade with Asia. You have a treaty in 1844 which is the first diplomatic agreement between the US and China, and its goal was to promote trade between the two nations. And as a result, many missionaries -- Christian missionaries from the United States -- are going to China trying to spread Christianity. And Japan as well is seen as a place for economic relationship. In Japan opens up which had been isolated for over 200 years, and President Fillmore sends Commodore Matthew Perry in 1852 to Japan to open up relations between the two nations.

Thanks for checking out key concept 5.1 explained. If you haven't done so, subscribe to Joe's Productions. Tell all the homies and homegirls out in the world to check out these videos to help them with APUSH. If you like the video, click like. If you didn't like it, click like. And as always, thanks for watching. Peace!

'''
