
= American Pageant - 021 (1863-1877)
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 释义

What up, APUSH people? Today we are going to take a look at the period known as Reconstruction 重建 in American history. + 
 If you're using any APUSH textbook, this lecture will help you as long as you're studying Reconstruction. + 
 And keep in mind, there's a whole bunch of issues the nation has to deal with after the Civil War is over. + 
 The Civil War dealt with the issue of slavery 奴隶制 and secession 脱离；退出, but you got some key challenges 挑战 facing the nation. + 


For instance, how do we bring back the Southern States into the Union 联邦? How do we have reunification 重新统一 and reconciliation 和解? Another issue is how do we rebuild the South after its destruction 破坏 during the war? The third thing is - and a very important one and a very contentious 有争议的 one - how do we integrate 使融入 and protect newly emancipated 解放的 black freedmen and women? And then fourth, what branch 分支 of government is going to control this process of reconstruction? Should it be Congress 国会? Should it be the president? And you're going to see disagreement 分歧 over that issue as well. + 


And even things like - what do you do with the former Confederate 邦联的（指南北战争时期南方邦联）leaders? People like Robert E. + 
 Lee and Jefferson Davis - should they be punished 惩罚? Should they be forgiven 原谅? What should happen to them? And one of the earliest problems Lincoln, and even before the war was over, had to address 处理 was the problem of these now freed people who are largely unskilled 无技能的, illiterate 文盲的, without property 财产 or money. + 
 How are you going to help them out?

And Congress addresses this in March of 1865, and they create something called the Freedmen's Bureau 自由民局. + 
 And this was to act as kind of a welfare agency 福利机构 for former slaves and also poor Southern whites who were impacted 影响 by the war or suddenly found themselves free. + 
 And it was supposed to give food, shelter 住所, and basic medical care to those impacted by the war. + 
 But its greatest area of success was in that of education. + 
 The Freedmen's Bureau creates something like 3,000 schools throughout the South, and it's estimated 估计 taught over 200,000 African-Americans how to read. + 
 So it was a huge achievement 成就 in that regard. + 


But there is shortcomings 缺点 to it and in Reconstruction in general. + 
 You know there was this idea talked about about this idea of "40 acres and a mule" - that land should be given to the former slaves so that they can become economically independent 独立的. + 
 And the reality 现实 is this almost never happened. + 
 And as a result, many of the former slaves remain economically vulnerable 易受伤害的；脆弱的. + 
 And you're going to see how that turns out during this video. + 


Now Reconstruction really begins - and there's different phases 阶段 to it - but it begins even before the war is over with Lincoln in his Proclamation of Amnesty and Reconstruction 大赦与重建宣言 in 1863. + 
 And this is kind of known as wartime reconstruction because the war is going on. + 
 And Lincoln, his plan was intended 旨在 to try to shorten the war and to give the South an incentive 激励；刺激 to quit the fighting. + 
 And as a result, the plan was really simple and lenient 宽容的. + 
 Southern states may rejoin 重新加入 the Union once 10% of state voters - those who voted in the election of 1860 - pledge 发誓；保证 their loyalty 忠诚 to the Union. + 
 And the idea would be they have to accept emancipation 解放 - no more slavery - and once that 10% goes and gives their oath 誓言 to the Constitution and the Union creates new state constitutions, they could be accepted back into the Union. + 
 And it was easy on the South. + 


But not all Northerners agreed with Lincoln. + 
 In fact, Congress comes up with its own plan called the Wade-Davis Bill 韦德 - 戴维斯法案, named after its two chief architects 设计者. + 
 And their plan was a little bit more strict 严格的. + 
 It said basically Southerners had to have 50% of the voters from the election of 1860 take an ironclad 坚定不移的 oath of allegiance 忠诚. + 
 And if you were a Southerner who helped out the Confederacy, you are excluded 排除 from these new governments. + 
 And this plan was much more strict, but it was pocket vetoed 搁置否决 by Lincoln - meaning he doesn't sign it so it doesn't go into law. + 


Now many historians disagree what would have happened next, but we don't know what Lincoln would have done because he is assassinated 暗杀 in the days shortly after the war ends. + 
 And his vice president, a former Democrat from the state of Tennessee, becomes the president of the United States. + 
 And everyone's wondering - what is his Reconstruction approach 方法 going to be? And basically he accepts Lincoln's plan, and he recognizes the 10% governments that were established in the Confederacy. + 
 He does do something though - he disenfranchises 剥夺选举权 former Confederate leaders and anybody who owned more than $20,000 of taxable property 应税财产. + 
 But they could apply for a pardon 赦免, and he ends up pardoning 赦免 most of those who apply. + 


Something else though that they had to do under Andrew Johnson's plan is they must ratify 批准 at this point the 13th Amendment 修正案 which abolished 废除 slavery. + 
 But what ends up happening - and this really angers 激怒 many in the North, especially Republicans - is Johnson ends up pardoning most of the former Confederate leaders. + 
 And what occurs 发生 is Southern planters start reestablishing 重建 political control of Southern politics. + 
 And the most famous example is the former Confederate vice president Alexander Stephens is elected senator 参议员 of Georgia. + 
 And Northerners are outraged 愤怒的. + 


A key idea though you need to keep in mind is this: the 13th Amendment abolished slavery, bringing about the war's most dramatic 巨大的；引人注目的 social and economic change. + 
 This is huge, people. + 
 But the exploitive 剥削的 and soil-intensive 依赖土地的 sharecropping system 佃农制度 endured 持续 for several generations 代. + 
 And what do I mean by that? Southern defiance 反抗. + 
 Johnson welcomes back the Southerners relatively easily, and Southerners begin their resistance 抵抗 to Reconstruction with something called the Black Codes 黑人法典. + 


And the Black Codes - the purpose 目的 of them was to guarantee 保证 a stable 稳定的 labor supply 劳动力供应 now that blacks are emancipated. + 
 What are they going to do now that they don't have their slaves? And Southerners really are hoping with these Black Codes to restore 恢复 the pre-emancipation system of race relations 种族关系. + 
 Here are some examples of what these Black Codes did: it prohibited 禁止 African-Americans from renting land or borrowing money to buy land. + 
 It also required 要求 that African-Americans were forced to sign labor contracts 劳动合同. + 
 If you did not have a contract, there was a penalty 惩罚 for leaving before the contract expired 到期 or not having one. + 
 And African-Americans could not serve on a jury 陪审团 or vote 投票 in most Southern states. + 


And as a result, many African-Americans find themselves forced to become sharecroppers 佃农. + 
 And the idea was really simple - it allowed you to use the land in exchange for 以……交换 giving a percent of the crop to the owner of the land. + 
 And for many Northerners, just this looked like a new form of slavery. + 
 And as a result, you see this anger in the North, and Congress splits 分裂 with President Johnson. + 


By 1866, Northern Republicans in Congress are angry when former Southern Confederate officials are returned to office. + 
 And as a result, there are calls for a stricter 更严格的 version of Reconstruction. + 
 And this is going to be known as Congressional Reconstruction 国会重建. + 
 Congress is going to take over 接管. + 
 And it is important for those of you studying for APUSH to know the transition 过渡 of Reconstruction between Lincoln, President Johnson, in the executive 行政的, legislative 立法的, and the judicial 司法的 branches. + 


And Congress breaks with the president and begins to take over Reconstruction when a couple of things happen. + 
 When the Southern Congressional delegates 代表 hope to come back into Congress under the Johnson Plan, they are flat out 直截了当地 denied that right. + 
 In February of 1866, President Johnson vetoes 否决 the extension 延长 of the Freedmen's Bureau. + 
 And Congress overrides 推翻 his veto and passes it anyway. + 
 Same thing happened again when Congressional Republicans in Congress passed the Civil Rights Bill of 1866 1866年民权法案. + 
 This is a huge civil rights bill because it gives citizenship 公民身份 to African-Americans - remember Dred Scott said no they're not citizens - and it sought to get rid of 废除 the Black Codes. + 
 Johnson vetoes that bill as well, and both of them are passed over Johnson's veto by Congress. + 


And what you see happening is it becomes a priority 优先事项 majority of Congress - how do we prevent Southern states from overturning 推翻 laws passed during Reconstruction? For instance, the Civil Rights Bill of 1866. + 
 That leads to the 14th Amendment being created. + 
 And it does a couple of things: it declares 宣布 all persons born in the US are citizens of the United States, including African-Americans - and forget you Dred Scott. + 
 States not just the federal government but states must protect rights and provide equal protection of the law and due process 正当程序. + 
 That piece of the 14th Amendment is going to have huge consequences 影响 in the 20th century for women, minority groups 少数群体, and many many others. + 
 It prevented former Confederates from holding political offices, and Southern states would be punished for denying the right to vote to its black citizens. + 


And what you see happening is in Congressional Reconstruction, Congress is setting the rules. + 
 And there was debate 辩论 amongst Republicans in Congress - radicals 激进分子 wanted to go much further with Reconstruction, whereas the moderates 温和派 were more measured 慎重的 or cautious 谨慎的 in their approach. + 
 But the key thing happens when the Reconstruction Act of 1867 1867年重建法案 is passed. + 
 And it divides 划分 the South into five military districts 军区 controlled by Union generals 将军. + 
 It is military occupation 军事占领 of the South to make sure Reconstruction is being followed. + 
 And this is a hugely important phase in Reconstruction because you have federal power 联邦权力 being brought into the South to bring about social and economic change. + 


Southern former Confederates were disenfranchised. + 
 All of those Lincoln and Johnson governments - the 10% governments - were ruled invalid 无效的. + 
 And to be readmitted 重新接纳, Southern states had to create a new constitution that included the right of black suffrage 选举权 for black men. + 
 This is going to be controversial 有争议的 - women's groups are going to be quite disappointed when women are not included. + 
 And Southern states must ratify the 13th and 14th Amendments. + 


Now Johnson really kind of sees how weak he is when he is impeached 弹劾 - the first president in our nation's history. + 
 In 1867, Congress passes a very political bill called the Tenure of Office Act 任职期限法案. + 
 And it had two goals: one, reduce presidential power, and two, to protect Republican Reconstruction cabinet members 内阁成员 left over from Lincoln. + 
 And what it basically said is that the Senate must approve any presidential dismissal 免职 of a cabinet official or a general. + 
 And Johnson violates 违反 this Tenure of Office Act when he removes Secretary of State Edwin Stanton. + 
 And this basically brings on impeachment. + 


The House of Representatives 众议院 immediately votes to impeach President Johnson. + 
 A trial 审判 takes place in the US Senate, and Johnson narrowly 勉强地 avoids removal from office by one vote short of the two-thirds required. + 
 But at this point, Johnson is weakened. + 
 Congress is in the driver's seat 处于主导地位. + 
 And it's important you keep in mind the three Reconstruction amendments: the 13th - all about freedom - it abolishes slavery; the 14th - which is about citizenship - guaranteeing citizenship, the protection of the rights of citizens with equal protection and due process; and of course the 15th which was eventually ratified which gives universal male suffrage 普选权 - the right to vote could not be denied on account of 由于 race, color, or previous condition of servitude 奴役. + 


And what you see happening is under Congressional or Radical Reconstruction - as it sometimes referred to - the South is temporarily 暂时地 experiencing a social and political revolution 革命. + 
 African-American men are voting. + 
 In fact in the South, you see Republicans taking states in presidential elections such as in 1868 and 1872. + 
 Kind of symbolic 象征性的 of this revolution is Hiram Revels who was elected in 1870 to the seat that Jefferson Davis, the former president of the Confederacy, used to hold. + 
 So you got groups of African-American senators and congressmen taking power in the South. + 


And a big part of these Reconstruction governments was the fact that you have this whole new electorate 选民 after African-American men as a result of the 15th Amendment and the process of Reconstruction. + 
 Grant's going to win Southern states as a Republican candidate in 1868. + 
 And this Republican coalition 联盟 is a mixture of African-American male voters, scalawags - which were cooperating Southern whites - they wanted economic development and wanted peace, but they were often times hated by other Southerners - the so-called carpetbaggers 投机分子 who were Northerners who went to the South - some were looking to profit 获利 and to benefit their own personal economic interest, but others just wanted to help out and transform 改变 Southern life. + 


But eventually Reconstruction will slowly fall apart 瓦解, and it's important you know why. + 
 The KKK 三K党 is established in 1868, and its sole purpose 唯一目的 is to secure 确保 white supremacy 白人至上 and to resist the Reconstruction governments. + 
 The government tries to deal with this resistance by passing the Force Acts of 1870 and 1871 1870年和1871年强制法案, which was to stop this resistance by putting federal troops 联邦军队 into the South. + 
 But unfortunately, as time goes on - for instance, the Civil Rights Act of 1875 1875年民权法案 guarantees equal access to public places, protects the right to serve on juries - but as time goes on, the Civil Rights Act of 1875 would be rarely enforced 执行 and eventually overturned by the Supreme Court 最高法院 in 1883. + 


And by the late 1870s - mid to late 1870s - Congress and the president, even Republicans in the North, are going to be unwilling to use federal government's power to monitor 监督 Southern society. + 
 And as a result, Reconstruction is slowly going to come to an end. + 
 And finally, the end of it will be following the election of 1876 with the Compromise of 1877 1877年妥协案 - we'll cover that in another video. + 


Some key things about Reconstruction before we close out: federal intervention 干预 in Southern society under Congressional reconstruction yielded 产生 some short-term success. + 
 It reunited the Union, opened up political opportunities for former slaves, and temporarily rearranged 重新安排 the relationships between white and black people in the South. + 
 The Civil War ended slavery and the idea of a divisible 可分割的 Union, but it left largely unchanged the social and economic patterns 模式. + 
 You're going to see the rise of sharecropping and Jim Crow laws 吉姆·克劳法 throughout the South. + 


Although citizenship, equal protection of the laws, and voting rights were granted 授予 to African-Americans in the 14th and 15th Amendments, these rights were progressively 逐渐地 stripped away 剥夺 through segregation 种族隔离, violence 暴力, Supreme Court decisions, and local political tactics 策略. + 
 But the Reconstruction amendments establish judicial principles 司法原则 that were stalled 停滞 for many decades but eventually became the basis for court decisions upholding 支持 rights in the 20th century. + 


That's going to do it for today. + 
 Thanks for watching. + 
 Make sure if you haven't done so, subscribe to Joe Productions. + 
 Click like on the video. + 
 If you have any questions, post them in the comments, and we'll see you next time right here same place same channel. + 
 Peace. + 



'''


== 中文翻译

各位APUSH的同学们，大家好！今天我们要探讨美国历史上被称为重建的时期。如果你正在使用任何APUSH教材，只要你学习重建时期，这次讲座都会对你有所帮助。记住，内战结束后，国家需要处理很多问题。内战解决了奴隶制和分裂的问题，但国家面临着一些关键的挑战。

例如，我们如何将南方各州带回联邦？我们如何实现统一和和解？另一个问题是，在战争破坏之后，我们如何重建南方？第三件事是——一个非常重要且极具争议的问题——我们如何整合和保护新解放的黑人男女自由民？第四，政府的哪个部门将控制这个重建过程？应该是国会吗？应该是总统吗？你们也会看到关于这个问题存在分歧。

甚至还有一些问题，比如——如何处置前邦联领导人？比如罗伯特·E·李和杰斐逊·戴维斯——他们应该受到惩罚吗？他们应该被原谅吗？他们应该得到怎样的对待？林肯，甚至在战争结束之前，就必须解决的最早的问题之一是这些现在获得自由的人，他们大多缺乏技能、不识字、没有财产或金钱。你打算如何帮助他们？

国会在1865年3月解决了这个问题，他们创建了一个叫做“自由民事务局”的机构。这个机构旨在为以前的奴隶以及受战争影响或突然获得自由的贫困南方白人提供某种福利机构的作用。它应该为那些受战争影响的人提供食物、住所和基本的医疗保健。但其最大的成功领域在于教育。自由民事务局在南方各地建立了大约3000所学校，据估计教会了超过20万非裔美国人阅读。因此，在这方面这是一项巨大的成就。

但它以及整个重建时期都存在缺点。你们知道，当时有一种关于“四十英亩和一头骡子”的想法——土地应该给予以前的奴隶，以便他们能够实现经济上的独立。但现实是，这几乎从未发生过。结果，许多以前的奴隶仍然在经济上很脆弱。你们将在这段视频中看到结果如何。

重建实际上始于——它有不同的阶段——但它甚至在战争结束之前就开始了，林肯在1863年发布了《特赦与重建宣言》。这有点被称为战时重建，因为战争仍在进行。林肯的计划旨在缩短战争，并给南方一个停止战斗的动机。因此，该计划非常简单和宽大。南方各州一旦有10%的州选民——那些在1860年选举中投票的人——宣誓效忠联邦，就可以重新加入联邦。其想法是他们必须接受解放——不再有奴隶制——一旦这10%的人宣誓效忠宪法和联邦，并创建新的州宪法，他们就可以被接纳回联邦。这对南方来说很容易。

但并非所有北方人都同意林肯的观点。事实上，国会提出了自己的计划，称为韦德-戴维斯法案，以其两位主要设计者的名字命名。他们的计划稍微严格一些。它基本上规定，南方人必须有1860年选举中50%的选民宣誓效忠联邦。如果你是帮助过邦联的南方人，你将被排除在这些新政府之外。这个计划要严格得多，但被林肯搁置否决了——这意味着他没有签署，所以它没有成为法律。

现在许多历史学家对接下来会发生什么意见不一，但我们不知道林肯会怎么做，因为他在战争结束后不久就被暗杀了。他的副总统，一位来自田纳西州的前民主党人，成为了美国总统。每个人都在想——他的重建方针会是什么？基本上他接受了林肯的计划，并承认了在邦联建立的10%政府。但他确实做了一些事情——他剥夺了前邦联领导人和任何拥有超过2万美元应税财产的人的公民权。但他们可以申请赦免，而他最终赦免了大多数申请者。

然而，在安德鲁·约翰逊的计划下，他们必须做的另一件事是，他们必须在这个时候批准废除奴隶制的第十三修正案。但最终发生的事情——这真的激怒了许多北方人，特别是共和党人——是约翰逊最终赦免了大多数前邦联领导人。结果是南方种植园主开始重新确立对南方政治的政治控制。最著名的例子是前邦联副总统亚历山大·斯蒂芬斯当选为佐治亚州参议员。北方人对此感到愤怒。

然而，你们需要记住一个关键的想法：第十三修正案废除了奴隶制，带来了战争中最剧烈的社会和经济变革。这非常重要，各位。但是，剥削性的、土地密集型的分成制农业系统持续了几代人。这是什么意思呢？南方人的反抗。约翰逊相对容易地接纳了南方人回来，而南方人开始通过一种叫做“黑人法典”的东西来抵制重建。

黑人法典——其目的是在黑人获得解放后，保证稳定的劳动力供应。既然他们没有了奴隶，他们现在要做什么？南方人真的希望通过这些黑人法典来恢复解放前的种族关系体系。以下是这些黑人法典所做的一些事情的例子：它禁止非裔美国人租用土地或借钱购买土地。它还要求非裔美国人被迫签署劳动合同。如果你没有合同，在合同到期前离开或没有合同就会受到惩罚。而且，在大多数南方州，非裔美国人不能担任陪审员或投票。

结果，许多非裔美国人发现自己被迫成为佃农。其想法非常简单——它允许你使用土地，以换取将一定比例的收成交给土地所有者。对于许多北方人来说，这看起来就像一种新的奴隶制形式。结果，你们看到了北方人的愤怒，国会与约翰逊总统决裂。

到1866年，当南方前邦联官员重返职位时，国会中的北方共和党人非常愤怒。结果，出现了要求采取更严格的重建方式的呼声。这将被称为国会重建。国会将接管。对于那些正在学习APUSH的人来说，了解林肯、约翰逊总统在行政、立法和司法部门之间重建的转变非常重要。

当发生几件事时，国会与总统决裂并开始接管重建。当南方国会代表希望根据约翰逊计划重返国会时，他们被断然拒绝了这项权利。1866年2月，约翰逊总统否决了延长自由民事务局的议案。但国会否决了他的否决，并最终通过了该议案。当国会共和党人在国会通过1866年《民权法案》时，同样的事情再次发生。这是一项重要的民权法案，因为它赋予了非裔美国人公民身份——记住德雷德·斯科特案裁定他们不是公民——并且旨在废除黑人法典。约翰逊也否决了该法案，但这两项法案都被国会推翻了约翰逊的否决而通过。

你们看到，国会的大多数人优先考虑的是——我们如何阻止南方各州推翻在重建时期通过的法律？例如，1866年的《民权法案》。这导致了第十四修正案的制定。它做了几件事：它宣布所有在美国出生的人都是美国公民，包括非裔美国人——忘了德雷德·斯科特案吧。各州（不仅是联邦政府，而是各州）必须保护权利，并提供法律的平等保护和正当程序。第十四修正案的这一部分将在20世纪对妇女、少数群体和许多其他人产生巨大的影响。它阻止了前邦联分子担任政治职务，而南方各州如果剥夺黑人公民的投票权将受到惩罚。

你们看到，在国会重建时期，国会正在制定规则。国会中的共和党人之间存在争论——激进派希望在重建方面走得更远，而温和派则采取更谨慎或保守的态度。但关键的事情发生在1867年《重建法案》通过时。该法案将南方划分为五个由联邦将军控制的军事区。这是对南方的军事占领，以确保重建得到执行。这是重建时期一个极其重要的阶段，因为联邦权力被带入南方以带来社会和经济变革。

南方的前邦联分子被剥夺了公民权。所有林肯和约翰逊政府——10%政府——都被裁定无效。为了重新被接纳，南方各州必须制定一部新的宪法，其中包括黑人男性享有选举权的权利。这将引起争议——妇女团体将对妇女未被包括在内感到非常失望。南方各州必须批准第十三和第十四修正案。

当约翰逊被弹劾时——我们国家历史上的第一位总统——他真正看到了自己的软弱。1867年，国会通过了一项极具政治性的法案，称为《官员任期法》。它有两个目标：一是削弱总统权力，二是保护林肯时期遗留下来的共和党重建内阁成员。它基本上规定，参议院必须批准总统解雇任何内阁官员或将军。当约翰逊解除了国务卿埃德温·斯坦顿的职务时，他违反了《官员任期法》。这基本上导致了弹劾。

众议院立即投票弹劾约翰逊总统。美国参议院进行了审判，约翰逊以一票之差，险些被免职，离所需的三分之二票还差一票。但此时，约翰逊的权力被削弱了。国会占据了主导地位。重要的是，你们要记住三项重建修正案：第十三修正案——完全关于自由——它废除了奴隶制；第十四修正案——关于公民身份——保障公民身份，以平等保护和正当程序保护公民权利；当然还有最终获得批准的第十五修正案，该修正案赋予了普遍男性选举权——不得因种族、肤色或以前的奴役状况而剥夺投票权。

你们看到，在国会或激进重建时期——有时被称为这样——南方暂时经历了一场社会和政治革命。非裔美国男性正在投票。事实上，在南方，你们看到共和党人在总统选举中赢得了一些州，比如1868年和1872年。这种革命的一个象征是海勒姆·雷维尔斯，他于1870年当选为杰斐逊·戴维斯（前邦联总统）曾经担任的席位。所以你们看到一群非裔美国参议员和众议员在南方获得了权力。

这些重建政府的一个重要组成部分是，由于第十五修正案和重建进程，你们拥有了全新的选民群体，即非裔美国男性。格兰特在1868年以共和党候选人的身份赢得了南方各州。这个共和党联盟由非裔美国男性选民、南方白人中的“可憎之人”（他们与北方合作——他们想要经济发展和和平，但经常被其他南方人憎恨）以及所谓的“地毯商人”（他们是前往南方的北方人——有些人是为了牟利和促进自己的经济利益，但另一些人只是想帮助和改变南方生活）组成。

但最终，重建将慢慢瓦解，重要的是你们要知道为什么。三K党成立于1868年，其唯一目的是确保白人至上，并抵抗重建政府。政府试图通过颁布1870年和1871年的《强制法案》来应对这种抵抗，该法案旨在通过向南方派遣联邦军队来阻止这种抵抗。但不幸的是，随着时间的推移——例如，1875年的《民权法案》保障了平等进入公共场所的权利，保护了担任陪审员的权利——但随着时间的推移，1875年的《民权法案》很少被执行，并最终在1883年被最高法院推翻。

到1870年代末——1870年代中期到后期——国会和总统，甚至北方的共和党人，都不愿意利用联邦政府的权力来监督南方社会。结果，重建将慢慢走向终结。最终，它的结束将是在1876年选举之后，通过1877年妥协案——我们将在另一段视频中介绍这一点。

在我们结束之前，关于重建的一些关键点：在国会重建时期，联邦政府对南方社会的干预取得了一些短期成功。它重新统一了联邦，为以前的奴隶开放了政治机会，并暂时重新安排了南方白人和黑人之间的关系。内战结束了奴隶制和联邦不可分割的观念，但在很大程度上没有改变社会和经济模式。你们将看到南方各地佃农制和吉姆·克劳法的兴起。

尽管第十四和第十五修正案赋予了非裔美国人公民身份、法律的平等保护和投票权，但这些权利通过隔离、暴力、最高法院的判决和地方政治策略逐渐被剥夺。但重建修正案确立了司法原则，这些原则被搁置了数十年，但最终成为20世纪支持权利的法院判决的基础。

今天就到这里。感谢观看。如果你还没有这样做，请务必订阅乔氏制作。点击视频的点赞按钮。如果你有任何问题，请在评论中提出，我们下次将在同一地点同一频道再见。再见。


'''


== pure

What up, APUSH people? Today we are going to take a look at the period known as Reconstruction in American history. If you're using any APUSH textbook, this lecture will help you as long as you're studying Reconstruction. And keep in mind, there's a whole bunch of issues the nation has to deal with after the Civil War is over. The Civil War dealt with the issue of slavery and secession, but you got some key challenges facing the nation.

For instance, how do we bring back the Southern States into the Union? How do we have reunification and reconciliation? Another issue is how do we rebuild the South after its destruction during the war? The third thing is - and a very important one and a very contentious one - how do we integrate and protect newly emancipated black freedmen and women? And then fourth, what branch of government is going to control this process of reconstruction? Should it be Congress? Should it be the president? And you're going to see disagreement over that issue as well.

And even things like - what do you do with the former Confederate leaders? People like Robert E. Lee and Jefferson Davis - should they be punished? Should they be forgiven? What should happen to them? And one of the earliest problems Lincoln, and even before the war was over, had to address was the problem of these now freed people who are largely unskilled, illiterate, without property or money. How are you going to help them out?

And Congress addresses this in March of 1865, and they create something called the Freedmen's Bureau. And this was to act as kind of a welfare agency for former slaves and also poor Southern whites who were impacted by the war or suddenly found themselves free. And it was supposed to give food, shelter, and basic medical care to those impacted by the war. But its greatest area of success was in that of education. The Freedmen's Bureau creates something like 3,000 schools throughout the South, and it's estimated taught over 200,000 African-Americans how to read. So it was a huge achievement in that regard.

But there is shortcomings to it and in Reconstruction in general. You know there was this idea talked about about this idea of "40 acres and a mule" - that land should be given to the former slaves so that they can become economically independent. And the reality is this almost never happened. And as a result, many of the former slaves remain economically vulnerable. And you're going to see how that turns out during this video.

Now Reconstruction really begins - and there's different phases to it - but it begins even before the war is over with Lincoln in his Proclamation of Amnesty and Reconstruction in 1863. And this is kind of known as wartime reconstruction because the war is going on. And Lincoln, his plan was intended to try to shorten the war and to give the South an incentive to quit the fighting. And as a result, the plan was really simple and lenient. Southern states may rejoin the Union once 10% of state voters - those who voted in the election of 1860 - pledge their loyalty to the Union. And the idea would be they have to accept emancipation - no more slavery - and once that 10% goes and gives their oath to the Constitution and the Union creates new state constitutions, they could be accepted back into the Union. And it was easy on the South.

But not all Northerners agreed with Lincoln. In fact, Congress comes up with its own plan called the Wade-Davis Bill, named after its two chief architects. And their plan was a little bit more strict. It said basically Southerners had to have 50% of the voters from the election of 1860 take an ironclad oath of allegiance. And if you were a Southerner who helped out the Confederacy, you are excluded from these new governments. And this plan was much more strict, but it was pocket vetoed by Lincoln - meaning he doesn't sign it so it doesn't go into law.

Now many historians disagree what would have happened next, but we don't know what Lincoln would have done because he is assassinated in the days shortly after the war ends. And his vice president, a former Democrat from the state of Tennessee, becomes the president of the United States. And everyone's wondering - what is his Reconstruction approach going to be? And basically he accepts Lincoln's plan, and he recognizes the 10% governments that were established in the Confederacy. He does do something though - he disenfranchises former Confederate leaders and anybody who owned more than $20,000 of taxable property. But they could apply for a pardon, and he ends up pardoning most of those who apply.

Something else though that they had to do under Andrew Johnson's plan is they must ratify at this point the 13th Amendment which abolished slavery. But what ends up happening - and this really angers many in the North, especially Republicans - is Johnson ends up pardoning most of the former Confederate leaders. And what occurs is Southern planters start reestablishing political control of Southern politics. And the most famous example is the former Confederate vice president Alexander Stephens is elected senator of Georgia. And Northerners are outraged.

A key idea though you need to keep in mind is this: the 13th Amendment abolished slavery, bringing about the war's most dramatic social and economic change. This is huge, people. But the exploitive and soil-intensive sharecropping system endured for several generations. And what do I mean by that? Southern defiance. Johnson welcomes back the Southerners relatively easily, and Southerners begin their resistance to Reconstruction with something called the Black Codes.

And the Black Codes - the purpose of them was to guarantee a stable labor supply now that blacks are emancipated. What are they going to do now that they don't have their slaves? And Southerners really are hoping with these Black Codes to restore the pre-emancipation system of race relations. Here are some examples of what these Black Codes did: it prohibited African-Americans from renting land or borrowing money to buy land. It also required that African-Americans were forced to sign labor contracts. If you did not have a contract, there was a penalty for leaving before the contract expired or not having one. And African-Americans could not serve on a jury or vote in most Southern states.

And as a result, many African-Americans find themselves forced to become sharecroppers. And the idea was really simple - it allowed you to use the land in exchange for giving a percent of the crop to the owner of the land. And for many Northerners, just this looked like a new form of slavery. And as a result, you see this anger in the North, and Congress splits with President Johnson.

By 1866, Northern Republicans in Congress are angry when former Southern Confederate officials are returned to office. And as a result, there are calls for a stricter version of Reconstruction. And this is going to be known as Congressional Reconstruction. Congress is going to take over. And it is important for those of you studying for APUSH to know the transition of Reconstruction between Lincoln, President Johnson, in the executive, legislative, and the judicial branches.

And Congress breaks with the president and begins to take over Reconstruction when a couple of things happen. When the Southern Congressional delegates hope to come back into Congress under the Johnson Plan, they are flat out denied that right. In February of 1866, President Johnson vetoes the extension of the Freedmen's Bureau. And Congress overrides his veto and passes it anyway. Same thing happened again when Congressional Republicans in Congress passed the Civil Rights Bill of 1866. This is a huge civil rights bill because it gives citizenship to African-Americans - remember Dred Scott said no they're not citizens - and it sought to get rid of the Black Codes. Johnson vetoes that bill as well, and both of them are passed over Johnson's veto by Congress.

And what you see happening is it becomes a priority majority of Congress - how do we prevent Southern states from overturning laws passed during Reconstruction? For instance, the Civil Rights Bill of 1866. That leads to the 14th Amendment being created. And it does a couple of things: it declares all persons born in the US are citizens of the United States, including African-Americans - and forget you Dred Scott. States not just the federal government but states must protect rights and provide equal protection of the law and due process. That piece of the 14th Amendment is going to have huge consequences in the 20th century for women, minority groups, and many many others. It prevented former Confederates from holding political offices, and Southern states would be punished for denying the right to vote to its black citizens.

And what you see happening is in Congressional Reconstruction, Congress is setting the rules. And there was debate amongst Republicans in Congress - radicals wanted to go much further with Reconstruction, whereas the moderates were more measured or cautious in their approach. But the key thing happens when the Reconstruction Act of 1867 is passed. And it divides the South into five military districts controlled by Union generals. It is military occupation of the South to make sure Reconstruction is being followed. And this is a hugely important phase in Reconstruction because you have federal power being brought into the South to bring about social and economic change.

Southern former Confederates were disenfranchised. All of those Lincoln and Johnson governments - the 10% governments - were ruled invalid. And to be readmitted, Southern states had to create a new constitution that included the right of black suffrage for black men. This is going to be controversial - women's groups are going to be quite disappointed when women are not included. And Southern states must ratify the 13th and 14th Amendments.

Now Johnson really kind of sees how weak he is when he is impeached - the first president in our nation's history. In 1867, Congress passes a very political bill called the Tenure of Office Act. And it had two goals: one, reduce presidential power, and two, to protect Republican Reconstruction cabinet members left over from Lincoln. And what it basically said is that the Senate must approve any presidential dismissal of a cabinet official or a general. And Johnson violates this Tenure of Office Act when he removes Secretary of State Edwin Stanton. And this basically brings on impeachment.

The House of Representatives immediately votes to impeach President Johnson. A trial takes place in the US Senate, and Johnson narrowly avoids removal from office by one vote short of the two-thirds required. But at this point, Johnson is weakened. Congress is in the driver's seat. And it's important you keep in mind the three Reconstruction amendments: the 13th - all about freedom - it abolishes slavery; the 14th - which is about citizenship - guaranteeing citizenship, the protection of the rights of citizens with equal protection and due process; and of course the 15th which was eventually ratified which gives universal male suffrage - the right to vote could not be denied on account of race, color, or previous condition of servitude.

And what you see happening is under Congressional or Radical Reconstruction - as it sometimes referred to - the South is temporarily experiencing a social and political revolution. African-American men are voting. In fact in the South, you see Republicans taking states in presidential elections such as in 1868 and 1872. Kind of symbolic of this revolution is Hiram Revels who was elected in 1870 to the seat that Jefferson Davis, the former president of the Confederacy, used to hold. So you got groups of African-American senators and congressmen taking power in the South.

And a big part of these Reconstruction governments was the fact that you have this whole new electorate after African-American men as a result of the 15th Amendment and the process of Reconstruction. Grant's going to win Southern states as a Republican candidate in 1868. And this Republican coalition is a mixture of African-American male voters, scalawags - which were cooperating Southern whites - they wanted economic development and wanted peace, but they were often times hated by other Southerners - the so-called carpetbaggers who were Northerners who went to the South - some were looking to profit and to benefit their own personal economic interest, but others just wanted to help out and transform Southern life.

But eventually Reconstruction will slowly fall apart, and it's important you know why. The KKK is established in 1868, and its sole purpose is to secure white supremacy and to resist the Reconstruction governments. The government tries to deal with this resistance by passing the Force Acts of 1870 and 1871, which was to stop this resistance by putting federal troops into the South. But unfortunately, as time goes on - for instance, the Civil Rights Act of 1875 guarantees equal access to public places, protects the right to serve on juries - but as time goes on, the Civil Rights Act of 1875 would be rarely enforced and eventually overturned by the Supreme Court in 1883.

And by the late 1870s - mid to late 1870s - Congress and the president, even Republicans in the North, are going to be unwilling to use federal government's power to monitor Southern society. And as a result, Reconstruction is slowly going to come to an end. And finally, the end of it will be following the election of 1876 with the Compromise of 1877 - we'll cover that in another video.

Some key things about Reconstruction before we close out: federal intervention in Southern society under Congressional reconstruction yielded some short-term success. It reunited the Union, opened up political opportunities for former slaves, and temporarily rearranged the relationships between white and black people in the South. The Civil War ended slavery and the idea of a divisible Union, but it left largely unchanged the social and economic patterns. You're going to see the rise of sharecropping and Jim Crow laws throughout the South.

Although citizenship, equal protection of the laws, and voting rights were granted to African-Americans in the 14th and 15th Amendments, these rights were progressively stripped away through segregation, violence, Supreme Court decisions, and local political tactics. But the Reconstruction amendments establish judicial principles that were stalled for many decades but eventually became the basis for court decisions upholding rights in the 20th century.

That's going to do it for today. Thanks for watching. Make sure if you haven't done so, subscribe to Joe Productions. Click like on the video. If you have any questions, post them in the comments, and we'll see you next time right here same place same channel. Peace.

'''
