= 0705
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 705: An Exclusive Guest List.
This is English as a Second Language Podcast episode 705. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development – I almost forgot there – in beautiful Los Angeles, California.
Our website is www.eslpod.com. Go there and become a member of ESL Podcast and help support this podcast. By becoming a member you will also receive a Learning Guide, an 8- to 10-page guide we provide for each episode of the podcast.
This episode is called “An Exclusive Guest List.” A “guest list” is a list of people you are going to invite to a party. Let’s get started.
[start of dialogue]
Catherine: Do you have a draft of the guest list? We need to get the invitations out next week.
Ralph: It’s not quite done yet. I keep going back and forth about a few people I’m not sure about, like Lacy Say.
Catherine: Lacy Say? She’s a has-been. She hasn’t been in a movie for years. We only want people on the A-list at this party.
Ralph: What about Jess McGillan? I’m on the fence about him.
Catherine: He’s definitely a D-lister. This party is very exclusive and we don’t want any D-listers rubbing elbows with VIPs.
Ralph: I understand that, but what if we don’t get enough A-listers to come?
Catherine: That will not happen. This party has to be a success!
Ralph: And if we don’t have enough guests because we’ve excluded so many D-list celebrities?
Catherine: There will always be gatecrashers. We can let in a few to buff up the numbers, if push comes to shove.
Ralph: What happens to the exclusivity of the party if that happens?
Catherine: If that happens, this party has bombed and I don’t care if we even let in podcasters!
[end of dialogue]
Catherine begins our dialogue by saying to Ralph, “Do you have a draft of the guest list?” A “draft” (draft) of a list or a letter or any other document is an early version of something; it’s not complete, it’s not final. In school you often, especially in a literature class, will have to write essays and papers. Usually you start with a first draft; you start writing it and then you go and you change it, that’s your second draft, and maybe even a third draft and so forth until you get to the final draft. So Catherine is asking Ralph if he has a draft of the guest list. A “guest list” is a list of people that you are inviting to a party. I should mention that “draft” has some other meanings in English as well; take a look at our Learning Guide for some additional explanations.
Catherine says, “We need to get the invitations out next week,” we need to mail or send the invitations next week. An “invitation” is a card or a letter asking you to come to a party. It could be for a wedding, it could be because someone is graduating, or just because you’re having a party – you’re a party kind of person, you like to party. Well, Catherine’s a real partier. Ralph says, “It’s not quite done yet (meaning the guest list is not finished yet). I keep going back and forth about a few people I’m not sure about, like Lacy Say.” “To go back and forth” means to be unable to make a decision, or to think that something is right and then later to change your mind and think that it’s wrong; constantly or continually going back and forth. Is it right? Is it wrong? Should I invite him? Should I not invite him? That’s going back and forth.
Ralph is going back and forth about inviting a woman named Lacy Say. Catherine says, “Lacy Say? She’s a has-been.” A “has-been” (been) is someone who was well known and popular a long time ago, but is not popular or is not important anymore. It’s an insulting way of referring to someone. Catherine says Lacy Say is a has-been, “She hasn’t been in a movie for years,” so she’s obviously an actress. She says, “We only want people on the A-list at this party.” The “A-list” would be the most popular, the best-known performers, especially actors and singers. The “B-list” would be actors and singers who aren’t very good, and so forth.
Ralph says, “What about Jess McGillan? I’m on the fence about him.” “To be on the fence” means to be unable to make a decision because you see the good and the bad of each possibility.
So, Ralph is on the fence about Jess McGillan. Catherine says, “He’s definitely a D-lister.” To be a “D-lister” is to be someone on the D-list, meaning an actor or singer who isn’t very well-known, who no one has ever heard of – and who has ever heard of Jess McGillan anyway? Catherine says, “This party is very exclusive and we don’t want any D-listers rubbing elbows with VIPs.” When you say something is “exclusive” you mean that it is available for only a small group of people, people who are famous or rich or popular. That would be something exclusive, only a small number of people can go or be a part of that event.
Catherine says, “we don’t want any D-listers rubbing elbows with VIPs.” “To rub (rub) elbows with (someone)” means to spend time at a party or some event with someone who is famous, rich, and/or powerful. I was at a Starbucks near one of the movie studios, and when you go there to drink coffee or tea you can sometimes rub elbows with famous actors and actresses, because they come in and get their coffee there. When I go there, I can rub elbows with famous actors. Unfortunately, I don’t recognize actors very well, so when they come in I don’t know who they are. So, I’ve never really rubbed elbows, although once I did meet a actress who I did not recognize, but someone else told me who she was. I think that was Neve Campbell, who was a television star in the 1990s here in the United States. Anyway, moving on. Catherine doesn’t want any of these less important rubbing elbows or talking and meeting with VIPs. A “VIP” is a very important person, someone with a lot of power or influence.
Ralph says, “I understand that, but what if we don’t get enough A-listers to come?” What if we can’t get enough people to our party? Catherine says, “That will not happen. This party has to be (must be) a success!” Ralph says, “And if we don’t have enough guests because we’ve excluded so many D-list celebrities?” “To exclude” is related to the word “exclusive.” “To exclude” means not to allow someone to come to your party or participate in something. It’s the opposite of “include,” which means to allow someone to be part of your group or to do something. Ralph is worried that they will not have enough people to come to the party if they exclude a lot of D-listers, the less famous actors and celebrities. A “celebrity” is just anyone who’s very famous, especially a singer or an actor or a podcaster. Those three are usually what we talk about when we refer to celebrities!
So, Catherine says, “There will always be gatecrashers.” A “gatecrasher” is a person who goes to a party even though they were not invited; they just go to the party and show up. They arrive, and even without an invitation, they go into the party. She says, “We can let in a few (a few gatecrashers; a few people who weren’t invited) to buff up the numbers, if push comes to shove.” “To buff (buff) up” is a phrasal verb meaning to improve something, to make it slightly better; when we’re talking about numbers, to increase the numbers of something. Catherine talks about buffing up the numbers, meaning the number of people at the party. They can do this if push comes to shove. This is an old expression; “if push comes to shove” indicates that you will do something if the situation becomes very bad or difficult, and it becomes necessary to do it even if you don’t want to. You might say, “I’m going to buy something at the store and I want to use my credit card. But if I have a problem with my credit card, if push comes to shove, I can also pay with cash.” So Catherine is saying if push comes to shove they can buff up their numbers by letting in gatecrashers.
Ralph says, “What happens to the exclusivity of the party if that happens?” Then the party won’t be exclusive anymore. Catherine says, “If that happens, this party has bombed.” “To bomb,” as a verb, here means to fail very badly, to do a very poor job. We especially use this when talking about a performance; we might say, “The latest movie by Tom Cruise bombed,” or “That new song by Jennifer Lopez bombed.” It did not do very well; it was not very popular. Catherine says if the party is not exclusive it will have bombed, and I don’t care if that happens – “I don’t care if we even let in podcasters!” meaning that would be the lowest, least popular person that we would want to come to our party. Obviously they’re not talking about all podcasters. I think Catherine here is referring to the less popular podcasters. I think that’s what – I think that’s what the scriptwriter meant!
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Catherine: Do you have a draft of the guest list? We need to get the invitations out next week.
Ralph: It’s not quite done yet. I keep going back and forth about a few people I’m not sure about, like Lacy Say.
Catherine: Lacy Say? She’s a has-been. She hasn’t been in a movie for years. We only want people on the A-list at this party.
Ralph: What about Jess McGillan? I’m on the fence about him.
Catherine: He’s definitely a D-lister. This party is very exclusive and we don’t want any D-listers rubbing elbows with VIPs.
Ralph: I understand that, but what if we don’t get enough A-listers to come?
Catherine: That will not happen. This party has to be a success!
Ralph: And if we don’t have enough guests because we’ve excluded so many D-list celebrities?
Catherine: There will always be gatecrashers. We can let in a few to buff up the numbers, if push comes to shove.
Ralph: What happens to the exclusivity of the party if that happens?
Catherine: If that happens, this party has bombed and I don’t care if we even let in podcasters!
[end of dialogue]
She’s no has-been; she’s an A-lister when it comes to scriptwriters here in Hollywood, that’s our own Dr. Lucy Tse I’m talking about.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
draft – an early version of a written document that is incomplete and/or has many errors and needs to be edited and changed at least one time before the final version if ready to be shared with other people
* How many drafts did you write before trying to get your novel published?
guest list – the names of all the people one expects to come to a party or event
* The guest list includes the bride and groom’s relatives and closest friends.
invitation – a written card or letter asking someone to come to a party or event and providing all the important information like the date, time, and place, as well as what the person should wear and bring
* We received an invitation for a summer barbeque, and it says we should bring our own beer.
to go back and forth – to be unable to make a decision; to believe something is right or correct and then change one’s mind and believe another thing is right or correct, repeating the process many times without being able to decide or choose
* Yolanda keeps going back and forth about that dress, because she likes it a lot, but she doesn’t really have enough money to buy something that expensive.
has-been – someone who was well-known, popular, and powerful in the past, but is not important or influential anymore
* He had some success early in his career, but he hasn’t done anything worthwhile in the past 10 years. He’s a has-been.
A-list – the most popular and wealthiest performers, especially actors and singers
* Movies can make a lot more money if they have A-list actors.
on the fence – unable to make a decision about something because one can see reasons for and against making a particular choice
* Isaiah is on the fence about whether he should accept the job offer, because it seems like a great opportunity, but he would have to move across the country.
D-lister – an actor who is not well-known or popular
* I’ve never met any celebrities – not even a D-lister!
exclusive – something that is desirable and available to only a small group of people, because not everyone is popular, beautiful, powerful, or rich enough to have or do it
* Only members of the club can take advantage of this exclusive offer.
to rub elbows with (someone) – to spend time with famous, rich, and powerful people, especially at parties or important events
* This conference will be a great opportunity to rub elbows with industry leaders.
VIP – a very important person; someone who has a lot of power and influence and is treated with respect for that reason
* The best parking spaces are reserved for the company’s VIPs.
to exclude – to not include someone; to not allow someone to have, do, or participate in something
* People who make more than $40,000 per year are excluded from our financial assistance programs.
celebrity – a person who is very famous, especially an actor or singer
* When they were in Los Angeles, they went on a tour to see celebrity homes in Hollywood.
gatecrasher – a person who goes to a party even though he or she was not invited
* That’s going to be the best party of the year! Even if I don’t get an invitation, I’ll go as a gatecrasher.
to buff up – to improve or polish something; to make something slightly better
* You’d be much more likely to get a job offer if you buffed up your appearance for interviews.
if push comes to shove – a phrase used to indicate that one will do something if the situation becomes very bad or difficult and that action becomes necessary
* I think most parents would steal to feed their children, if push comes to shove.
to bomb – to fail very badly; to a very poor job
* Their first album bombed, but their second album is a huge success.
Comprehension Questions
1. What does Ralph mean when he says, “I’m on the fence about him”?
a) He’s waiting to hear back from him.
b) He’s trying to find his contact information.
c) He hasn’t decided whether or not to invite him.
2. What does Catherine mean when she says, “this party has bombed”?
a) The party is very disappointing.
b) There was a bomb threat.
c) There were too many guests at the party.
Answers at bottom.
What Else Does It Mean?
draft
The word “draft,” in this podcast, means an early, incomplete version of a written document: “When you write your first draft, try not to worry too much about specific words and phrases. You can always edit what you’ve written later.” A “draft” can also refer to a breeze or wind that comes through a crack in a wall, door, or window: “Do you believe you can get sick by sitting in a draft while your hair is wet?” In sports, “the draft” is the process teams use to pick new players: “Who do you think will be picked first in the draft?” Finally, “the draft” is the process where the government tells people they must fight in a war: “Normally U.S. military service is voluntary, but during a war, all young men must participate in the draft.”
to buff up
In this podcast, the phrase “to buff up” means to improve or polish something, or to make something slightly better: “Gracie is taking a class in public speaking to buff up her presentation skills.” The phrase “to buff up” can also mean to make one’s muscles larger and more defined or toned by lifting weights: “He spends hours every day at the gym, trying to buff up.” The verb “to buff” means to rub something with a cloth to make it clean and shiny: “If you buff this silver vase, it will look like new again.” Finally, an old-fashioned children’s game called “blind man’s bluff” is played by having one child cover his or her eyes and then try to catch the other children who are running around him or her.
Culture Note
Famous Gatecrashers
Probably the most “infamous” (famous for doing something bad or wrong) gatecrashers “in recent history” (in the past few years) are Michaele and Tareq Salahi. They are a married couple from the state of Virginia who attended a “state dinner” (an official meal organized for the leaders of two or more countries to meet) at the “White House” (the home and offices of the U.S. President) without an invitation.
The state dinner was held on November 24, 2009 for Indian Prime Minister Manmohan Singh. “Somehow” (without being able to explain the reasons) the Salahis were able to “pass through” (walk through or past) the “security checkpoints” (places where security guards stop unauthorized people from entering and authorized people from bringing prohibited items) to enter the White House, where they met President Obama, Prime Minister Singh, and other “high-profile” (important and well-known) politicians and businesspeople.
At the time, Michaele Salahi was being “filmed” (recorded on video) for a “reality TV show” (a show recording the actions of real people in their real lives, not actors) called The Real Housewives of Washington, D.C. Many people believe she and her husband crashed the state dinner because they wanted to “raise the profile” (become more well-known) of themselves and the TV show.
The White House and the “media” (newspapers, news TV shows, reporters, etc.) were “shocked” (very surprised) that the Salahis had been able to pass through the security checkpoints. Since that time, they have “cracked down on” (become more strict and more serious about) security and their efforts to “prevent” (not let something happen) other gatecrashers from attending official White House events without invitations.
Comprehension Answers
1 - c
2 - a