= 0717
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 717: Starting a New School Year.
This is English as a Second Language Podcast episode 717. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Our website is eslpod.com. Go there to download a Learning Guide for this episode and for all of our current episodes that will help you improve your English faster than ever.
This episode is a dialogue between a mother and her son, Paul. They’re talking about things that a young student would need when they begin their school year. Let’s get started.
[start of dialogue]
Mom: It’s your first day at a new school. I’m worried about you.
Paul: Mom, I’ll be fine.
Mom: Do you have all of your books and supplies in your backpack? Oh and I’ve packed you a lunch already.
Paul: You didn’t have to do that, Mom. I was going to buy lunch at school.
Mom: Now you won’t have to. I hope you make some new friends. It’s no fun being a loner. It’s not that you have to be popular. I just don’t want you to feel left out.
Paul: I’ll be fine, Mom. I’d better go, or I’ll be late.
Mom: Do you think the school will do something special to kick off the new school year? I hope your teachers aren’t too strict. Oh, your backpack weights a ton! But you can leave most of your books in your locker, right?
Paul: They don’t have lockers at my new school, but I’ll be fine.
Mom: I hope the teachers don’t already have seating plans. I know you like to sit near the back of the classroom. And I hope you won’t have too much homework on the first day…
Paul: Mom, stop fussing. Everything will be fine.
Mom: You’re my baby and I’m worried about you.
Paul: Mom, I’m not starting kindergarten. I’m starting college, remember?
[end of dialogue]
Mom begins by saying to Paul, “It’s your first day at a new school. I’m worried about you.” Paul says, “Mom, I’ll be fine.” I’ll be okay; don’t worry about me. Mom says, “Do you have all of your books and supplies in your backpack?” The word “supplies” means all of the things that you need for a particular purpose, for a specific thing that you are going to do, especially in school or in an office. Office supplies would include pens, paper, notebooks, uh…paperclips, that sort of thing – things you use in an office. School supplies would be things that students typically use in school, often things that you use up, or consume, so that you need to get more in the future. A “backpack” (one word) is a usually cloth or leather bag that you wear on your back; it has something so that you can put it on both of your shoulders. It’s common in many schools for children – students – to have backpacks to carry their books and supplies from class to class. It wasn’t very common when I was in school, maybe because we didn’t study very much so we didn’t have very many books! I’m not sure. But I didn’t have a backpack in high school; I did have a backpack in college, and at the university it’s very common to see backpacks. In many high schools you have a place where you keep your books that’s called a “locker” (locker); it’s a little space for each student. I’m not sure if schools still have lockers; I think many of them do, but it’s something you would find in a high school. At the university, you would have to have a backpack, or if you were in elementary or grade school as a younger student. It’s interesting, backpacks are considered for children in some countries, but in the United States you will find them mostly at the university.
Mom continues by saying, “Oh and I’ve packed you a lunch already.” “To pack (someone) a lunch” means usually to put some food – a sandwich, an apple, perhaps a candy bar – into a small bag so they can take it with them. You might pack a lunch if you are going on a trip in your car and don’t want to stop to eat. Packing a lunch is common for people going to work who don’t want to spend money buying food at a restaurant.
Paul, I guess, has a lot of money because he says, “You didn’t have to do that, Mom. I was going to buy lunch at school.” Mom says, “Now you won’t have to. I hope you make some new friends.” Remember, it’s a new school for Paul. She says, “It’s no fun being a loner.” A “loner” (loner) is a person who is very quiet, who doesn’t have a lot of friends, who sits by him or herself. That would be a loner. “It’s not that you have to be popular,” Mom says, “I just don’t want you to feel left out.” “To be popular” means to be liked by many other people. “Popular” has some other meanings as well; take a look at our Learning Guide for those. “To feel left out” means to feel that or think that you don’t belong to any group, that people are not accepting you, that they did not invite you to do something with them. Paul says, “I’ll be fine, Mom. I’d better go, or I’ll be late.” I should go, he’s saying, because if I don’t I will be late.
Mom says, “Do you think the school will do something special to kick off the new school year?” “To kick off” is a phrasal verb that here means to start something, especially with a lot of enthusiasm. “We’re going to kick off our celebration by singing and dancing.” We’re going to begin it; we’re going to start it. “Kick” has a number of different meanings; take a look at our Learning Guide for some additional ones. The “school year” is sometimes called the “academic year.” In most American schools it begins in late August-early September and ends in May or June, depending on the school. Mom continues, “I hope your teachers aren’t too strict.” “To be strict” (strict) means to follow all of the rules and make sure that you follow all of the rules, that you obey the rules. So, a strict teacher would be someone, for example, who doesn’t allow anyone to talk in class, and if they do they would be punished. Of course, the teacher can talk and the teacher can ask students to answer questions. But, a strict teacher would follow the rules and be very serious about them and punish people who don’t follow the rules.
So, Mom is asking or hoping that the teachers that Paul has won’t be too strict. She says, “Oh, your backpack weights a ton!” A “ton” (ton) is a unit of measurement equal to 2,000 pounds. But the expression “to weigh a ton” means that something is very heavy, that it weighs a lot. It doesn’t actually weigh a ton, but it’s very heavy. Mom says, “But you can leave most of your books in your locker, right?” I mentioned earlier that in American high schools many of them have lockers (lockers). These are basically little storage places that each student has; they’re given one were they can put their books and lunch and other supplies. In most schools, you need to lock your locker; you need to bring or to buy a lock; the school usually doesn’t give you a lock. You have to get one yourself, with a key or a combination lock. Lockers are popular in high schools, in some junior high schools, and elementary schools. If you’ve watched almost any movie about American high schools, you will know what lockers are. Students often spend time at them in between their classes talking. It’s popular in many schools to put pictures inside of your locker; girls often put pictures of attractive actors and singers, that sort of thing. I don’t think I ever put a picture of anyone in my locker. I did remember having a calendar in my last year of school, where I would at the end of each day cross off – put an “X” on the calendar for that day, counting the number of days left of school. You can tell I really loved my high school!
Anyway, Paul says that his new school doesn’t have lockers. Mom says, “I hope the teachers don’t already have seating plans.” A “seating plan” is when a teacher decides where each student will sit. Sometimes teachers will put students in alphabetical order, so if your last name begins with “A” you sit in the front and if your last name begins with “Z” you sit in the back. Other teachers make seating plans based on other criteria – other reasons. I used to have a seating plan. I would let students sit where they wanted to – this is when I was a high school teacher many years ago, 20 years ago – and then after the first day I would write their names down, where they were, and that’s where they had to stay unless they caused problems, in which case I would move them to a different seat. That’s a seating plan, and it’s very popular in high schools and elementary schools.
Mom says, “I know you like to sit near the back of the classroom.” The “classroom” is the room where the students sit and the teacher stands in front and gives the lesson. I, personally, always liked to sit in the back of the classroom. Mom says, “And I hope you won’t have too much homework on the first day.” “Homework” are things that students have to do outside of school for their class; we might call them “school assignments.”
Paul then says, “Mom, stop fussing.” This is a good word. “To fuss” (fuss) means to worry about many things that other people don’t think are very important. You’re worrying about small things, things that aren’t important, but you are acting as if they were important; this is to fuss. It’s a criticism to say someone is fussing, and Paul is criticizing his mother by saying “stop fussing.” “Everything will be fine,” he says. Mom says, “You’re my baby and I’m worried about you.” Paul says, “Mom, I’m not starting kindergarten.” “Kindergarten” is school for young children, usually five years old. In many places you go to kindergarten first. It’s not required, but many schools offer a kindergarten program for five-year-olds, and then when you’re six years old you begin first grade – the first grade of elementary school. Before kindergarten there is what’s called “preschool.” When I was a child, I think I went to preschool for a half a day for at least a few months. It was not at a regular school; it was at a public building – a park actually. And then, kindergarten was also half-day; that is, I didn’t go the whole day, I went in the morning and then came home in the afternoon. That’s when I was five years old. Anyway, as interesting as my life may be, let’s finish up the story here. Paul says, “I’m not starting kindergarten. I’m starting college, remember?” And that, of course, is the joke. Mom is treating Paul as if he were a young child, when in fact his new school is the university.
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Mom: It’s your first day at a new school. I’m worried about you.
Paul: Mom, I’ll be fine.
Mom: Do you have all of your books and supplies in your backpack? Oh and I’ve packed you a lunch already.
Paul: You didn’t have to do that, Mom. I was going to buy lunch at school.
Mom: Now you won’t have to. I hope you make some new friends. It’s no fun being a loner. It’s not that you have to be popular. I just don’t want you to feel left out.
Paul: I’ll be fine, Mom. I’d better go, or I’ll be late.
Mom: Do you think the school will do something special to kick off the new school year? I hope your teachers aren’t too strict. Oh, your backpack weights a ton! But you can leave most of your books in your locker, right?
Paul: They don’t have lockers at my new school, but I’ll be fine.
Mom: I hope the teachers don’t already have seating plans. I know you like to sit near the back of the classroom. And I hope you won’t have too much homework on the first day…
Paul: Mom, stop fussing. Everything will be fine.
Mom: You’re my baby and I’m worried about you.
Paul: Mom, I’m not starting kindergarten. I’m starting college, remember?
[end of dialogue]
We never want our scriptwriter to feel left out. That’s because it’s the wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
supplies – things that are needed for a particular purpose, especially for use in an office or school
* Victor is ordering some pens, binders, nametags, and other office supplies.
backpack – a cloth or leather bag worn on one’s back while hanging from two straps, one over each shoulder, usually with many zippered pockets
* Whenever you go on a hike, be sure your backpack contains water, food, a flashlight, warm clothes, and a whistle.
to pack (someone) a lunch – to put food in a small bag for another person so that he or she can eat lunch away from home without needing to buy food in a restaurant
* Sean tries to reduce the family’s expenses by packing his wife a lunch each morning before she goes to work.
loner – a quiet person who spends a lot of time alone and does not have friends
* As a child, Ilesa was always a loner, preferring to spend her time reading books rather than being around other children her age.
popular – very well liked by many people
* Movies often show that the head cheerleader and the quarterback on the football team are the most popular kids in high school. Is that really true?
to feel left out – to feel that one does not belong in a group, although one would like to; to perceive that one is not truly accepted by another group of people and is not welcome to do what they do
* Desiree felt left out at the party. Everyone else was talking, laugh, and having a great time while she just sat on the couch and sipped her drink.
to kick off – to start something, especially with a lot of enthusiasm
* The festival kicks off with a big show with a lot of local celebrities.
school year – the academic year, usually from early September to early June.
* Trent wakes up early every day during the school year, but during summer vacation, he prefers to sleep in until noon.
strict – following the rules and insisting that other people follow the rules; inflexible
* Alexey’s parents are very strict and they never let him stay out past 10:00 p.m.
to weigh a ton – to be very heavy
* These boxes weigh a ton! Can you please help me move them?
locker – one of many tall metal cupboards that stand next to each other and are attached to the wall at many high schools, with individual doors that can be locked, used to store books, jackets, bags, and other items
* In our high school, the school principal randomly checks students’ lockers for drugs and alcohol.
seating plan – a map showing which seats are for which people; a drawing that assigns individuals to specific seats
* Are you going to create a seating plan for your wedding reception, or will you let people sit wherever they want to?
classroom – a room where a teacher presents information and students learn
* In elementary school, we were in just one classroom all day. Now that we’re older, we move to different classrooms for different subjects.
homework – school assignments; tasks that students must complete in the evening outside of their regular class time
* I have so much homework! I have to write two essays, solve 20 math problems, summarize six chapters, and read this short story by the end of the week.
to fuss – to worry about many things that do not seem important to other people; to treat something as being more important than it actually is
* Melanie spent hours fussing in front of the mirror while getting ready for her date.
Comprehension Questions
1. Why is Paul’s mom fussing?
a) Because she thinks he’ll get lost on the way to school.
b) Because she thinks he won’t understand what the teachers say.
c) Because she thinks he won’t have any friends.
2. What did Paul’s mom put in his backpack?
a) Books.
b) Supplies.
c) Food.
Answers at bottom.
What Else Does It Mean?
popular
The word “popular,” in this podcast, means very well liked by many people: “Which smart phone is the most popular, and why?” Or, “Who is the most popular girl in school?” The word “popular” can also refer to something many people do: “The government changed its policy according to the popular opinion of voters.” The word “popular” also refers to things that are related to ordinary people: “Popular literature tends to be considered less sophisticated than the classics.” Or, “The English Café episodes can give you insight into American popular culture.” Finally, the phrase “popular belief” refers to something that many people believe: “According to popular belief, eating carrots can improve your eyesight.” Sometimes this is shortened to “pop”: “This radio station specializes in pop music.”
to kick off
In this podcast, the phrase “to kick off” means to start something, especially with a lot of enthusiasm: “Let’s kick off summer vacation by taking a trip to the beach!” The phrase “to kick (someone) off (something)” means to take someone off a team or out of a group: “The cyclist was kicked off the team for using steroids and other drugs.” The phrase “to kick up (one’s) heels” means to have a great time and enjoy oneself: “After a long week at work, Wendy was ready to kick up her heels and have fun with her friends.” Finally, the phrase “to kick the bucket” is used in humorous ways to mean to die: “What do you want to do in life before you kick the bucket?”
Culture Note
Events to Start a New School Year
American schools “hold” (organize and arrange) many special events to kick off the new school year. They hope to “motivate” (give someone energy and enthusiasm) students and teachers for the year “to come” (ahead; in the future).
Many schools have an “open house” at the end of the summer. This is an opportunity for new students and their families to “tour” (see all parts of something) the school, meet “faculty” (teachers) and “staff” (administrators and executives), and get answers to their questions. During an open house, “incoming” (starting for the first time) students might be sent to their new classroom to meet with their new teacher and learn what to expect during the year. Sometimes new students can “register” (sign up) during the open house and pay any fees for “extra-curricular” (outside of the school) activities, such as participation in sports, music, or drama.
Once the school year has begun, many schools have one or more “pep rallies.” Pep rallies often happen in a gym or “auditorium” (a room with a stage, designed for performances) that is large enough for all the students to sit on “bleachers” (long wooden or metal benches with lower rows in the front and higher rows in the back). Often the band plays, “cheerleaders” (people, usually girls, who wear uniforms, repeat phrases, and dance, especially during sports games) “cheer” (shout phrases to make people feel energetic and excited), and the principal or other individuals give short speeches to try to increase the energy and enthusiasm of all the students and faculty and staff members. Pep rallies are often held for sports teams at other times of the year, too, to build student interest and support for those teams
Comprehension Answers
1 - c
2 - c