= 0726
:toc: left
:toclevels: 3
:sectnums:
:stylesheet: ../../../myAdocCss.css

'''

== 

Complete Transcript
Welcome to English as a Second Language Podcast number 726: Taking the Driving Test.
This is English as a Second Language Podcast episode 726. I’m your host, Dr. Jeff McQuillan, coming to you from the Center for Educational Development in beautiful Los Angeles, California.
Visit our website at eslpod.com. Download this episode’s Learning Guide, an 8- to 10-, maybe 12-page Learning Guide that gives you additional help in improving your English. Trust me, it will help!
This episode is called “Taking the Driving Test,” about taking a test to get your driver’s license for a car. Let’s get started.
[start of dialogue]
Cesar: I just took the driving test. See this? That’s my new license.
May: You have to give me the play-by-play. I’m taking the test next week and I’m freaking out.
Cesar: There’s nothing to worry about. It was easy.
May: I’m not worried about the written test. It’s the driving test I’m worried about. I haven’t had a lot of practice. What did you have to do?
Cesar: Well, we got into the car and I fastened my seat belt. The examiner had me drive around the block, checking to see that I stopped at the stop signs and traffic signals.
May: That sounds okay. Did you have to drive on the freeway?
Cesar: Yeah, I went on the onramp and merged into traffic. She had me change lanes and accelerate to pass another driver. Just don’t forget to signal and don’t go over the speed limit.
May: Did you have to parallel park? That’s what I’m most worried about.
Cesar: Yeah, I parallel parked, but it was easy. Why are you so worried about the test?
May: I told you. I haven’t had very much practice.
Cesar: Exactly how many times have you been behind the wheel?
May: Well, a few times…maybe two times, and that was around a parking lot.
Cesar: Wow, you’d better get more practice if you’re going to take the test next week.
May: Could you…?
Cesar: Uh, sorry, but I’ve got someplace to be.
[end of dialogue]
We begin with Cesar saying to May, “I just took the driving test,” meaning I took the test recently. A “driving test” is an examination that you have to take in order to get your driving license. In most U.S. states, you need to take two exams or two tests. One is written; these are questions about the rules of the road, the laws of driving in that state. Each state has slightly different laws, but they’re basically the same. The second test is what we call a “behind the wheel test,” where you actually have to go out with someone who gives you your score. You have to do certain thing driving on the street, and if you do everything correct then you get your license – or most things correct. If you don’t hit another car or kill anyone, then you’ll probably get your license in most places. Cesar just took his driving test; we assume it’s the behind the wheel test. He says, “See this? That’s my new license.” That’s his legal permission to drive, that’s what a “license” is. “License” has some other meanings in English; take a look at our Learning Guide for those.
May says, “You have to give me the play-by-play.” “Play-by-play” is a detailed description of what happened. In a sports game you have different plays – different parts of the game. Each little part of the game can be called a “play,” and on the television or radio the person who describes everything that is happening in the game is giving the play-by-play, a detailed description. We use the expression more generally, outside of the sports world, to mean a detailed description of something that happened.
May says, “I’m taking the test (the driving test) next week and I’m freaking out.” “To freak (freak) out” is a two-word phrasal verb used informally to mean get very worried or nervous about something, so much that it is controlling all of your thoughts and emotions. Cesar says, “There’s nothing to worry about. It was easy.” May says, “I’m not worried about the written test. It’s the driving test I’m worried about.” So here, “driving test” refers to I called before the “behind the wheel test.” Why do we call it “behind the wheel”? Well, we are talking about the round wheel that you use to direct the car, what we would say “to steer” the car; in fact, it’s called a “steering wheel.” So, “behind the wheel” means you are sitting there with the wheel in front of you, which means you are actually in the car driving.
Anyway, poor May is freaking out; she’s worried about the driving test or the behind the wheel driving test. She says, “I haven’t had a lot of practice. What did you have to do?” Describe what you had to do. Cesar says, “Well, we got into the car and I fastened my seat belt.” So he and the person – we would call him or her the “examiner,” probably – got into the car and the first thing Cesar did was fasten his seat belt. The “seat belt” is a long piece of material – of fabric – that goes across your chest and your waist to keep you in your seat. You wear a seat belt on an airplane when you are taking off – leaving, or landing – coming down onto the ground. You wear a seat belt in a car. In most states, perhaps in all of them, you are required to wear a seat belt. If you don’t wear a seat belt you can be fined; you will have to pay money if the police see you not wearing a seat belt. It’s also, of course, just common sense; it’s good for your safety to wear a seat belt. So Cesar fastened his seat belt. “To fasten” (fasten) usually means to connect two things together so that they will stay together. You are usually fastening things that can also easily come apart. We usually use it when we are talking about rope or, in this case, a seat belt, which is a long, narrow piece of material. “The examiner had me drive around the block, checking to see that I stopped at the stop signs and traffic signals.” In a city, a “block” is a square area surrounded by four crossing streets.
Cesar drove around the block so the examiner could check to see that he stopped at the stop signs and traffic signals. A “stop sign” is, in the United States, a red, eight-sided sign with the word “STOP” in white letters. That’s a stop sign; it tells you you must stop before going forward. A “traffic signal” – sometimes called a “semaphore,” only by me I think – means a box with three lights – one is red, one is yellow, one is green – that tells you if you need to stop, that’s the red color, of course. If you can go, that’s the green color, or if you need to prepare to stop, which would be the yellow color. Well, we have traffic signals usually where two streets cross, what we would call an “intersection,” where they come at right angles to each other. Sometimes you can have a traffic signal in front of what’s called a “pedestrian crossing,” where people are allowed to walk across the street. That could be in the middle of a long block, and that might also have a traffic signal in some places. But usually a traffic signal would be at an intersection, where two streets cross.
May says, “That sounds okay. Did you have to drive on the freeway?” The “freeway” is a wide road, with usually more than two “lanes,” two places where the cars can drive, and they drive very quickly without stopping. Cesar says, “Yeah, I went on the onramp and merged into traffic.” The “onramp” (one word) is a little road that leads from the street to the freeway; it’s how you get on a freeway. The opposite would be an “offramp.” Cesar says that he had to merge into traffic. “To merge” (merge) is when two lanes of traffic have to come together, so you have to either go in front of the car near you or behind the car that is near you. Cesar says that the examiner had him change lanes and accelerate to pass another driver. “To change lanes” means to move your car from one lane on a freeway or on a street to another, but going in the same direction. “To accelerate” means to drive faster, to increase your speed. Then Cesar gives May some advice, “Just don’t forget to signal and don’t go over the speed limit.” “To signal” (signal) here means to use the lights of your car to indicate that you are going to move into another lane or you are going to turn onto another street. You have a right signal and a left signal in most cars. The “speed limit” is the maximum allowed speed on a road. In the United States for a freeway in the city it’s usually 55 or 65 miles per hour; out in the country, away from the big cities, it can be as high as 70 or 75 miles an hour. The word “signal,” I should mention, has some other meanings in English. You can find those in the Learning Guide.
May says, “Did you have to parallel park?” “To parallel park” means to park your car between two other cars, where you have to back your car up – go in reverse in order to get into a parking space in between two other cars. That’s often a very difficult thing for a beginning driver to do. May says, “That’s what I’m most worried about.” Cesar says, “Yeah, I parallel parked, but it was easy. Why are you so worried about the test?” May says, “I told you. I haven’t had very much practice.” Cesar says, “Exactly how many times have you been behind the wheel?” That is, how many times have you been out driving? May says, “Well, a few times…maybe two times, and that was around a parking lot,” a place where you park your car. Cesar says, “Wow, you’d better get more practice if you’re going to take the test next week,” meaning you have to go and drive more so that you are ready to take the driving test. May says, “Could you…?” She doesn’t finish her question, but she seems to be asking Cesar if Cesar would take her out driving to give her some practice. That, of course, is a difficult thing to do since the beginning driver doesn’t always know what they are doing and it can be a little dangerous for the person driving, as well as you. In the United States, if you pass the written test you can then practice behind the wheel with someone who has a driver’s license, who, the idea is will help you, tell you what to do and not to do. Cesar says, “Uh, sorry, but I’ve got someplace to be.” The expression “I’ve got someplace to be” is a phrase you use to tell the person that you are busy, you have another appointment, but you don’t give them any details. We often use this when we are lying and simply don’t want to do what the other person is asking us to do. You may say, for example, “Can you watch my dog and cat while I’m on vacation?” and I will say, “Oh, I’m sorry. I’ve got someplace to be for the next two weeks.”
Now let’s listen to the dialogue, this time at a normal speed.
[start of dialogue]
Cesar: I just took the driving test. See this? That’s my new license.
May: You have to give me the play-by-play. I’m taking the test next week and I’m freaking out.
Cesar: There’s nothing to worry about. It was easy.
May: I’m not worried about the written test. It’s the driving test I’m worried about. I haven’t had a lot of practice. What did you have to do?
Cesar: Well, we got into the car and I fastened my seat belt. The examiner had me drive around the block, checking to see that I stopped at the stop signs and the traffic signals.
May: That sounds okay. Did you have to drive on the freeway?
Cesar: Yeah, I went on the onramp and merged into traffic. She had me change lanes and accelerate to pass another driver. Just don’t forget to signal and don’t go over the speed limit.
May: Did you have to parallel park? That’s what I’m most worried about.
Cesar: Yeah, I parallel parked, but it was easy. Why are you so worried about the test?
May: I told you. I haven’t had very much practice.
Cesar: Exactly how many times have you been behind the wheel?
May: Well, a few times…maybe two times, and that was around a parking lot.
Cesar: Wow, you’d better get some practice if you’re going to take the test next week.
May: Could you…?
Cesar: Uh, sorry, but I’ve got someplace to be.
[end of dialogue]
Her dialogues give us a play-by-play of life in the United States. That’s our own wonderful Dr. Lucy Tse.
From Los Angeles, California, I’m Jeff McQuillan. Thank you for listening. Come back and listen to us again here on ESL Podcast.
English as a Second Language Podcast is written and produced by Dr. Lucy Tse, hosted by Dr. Jeff McQuillan, copyright 2011 by the Center for Educational Development.
Glossary
driving test – an exam that must be passed to receive permission to drive, where one drives a car while the examiner sits in the passenger seat, giving instructions and observing how well one drives
* Nick hit a stop sign during his driving test and didn’t pass.
license – legal permission to do or have something
* How long have you had a license to carry a gun?
play-by-play – detailed information, describing what is happening as it occurs or every step in a process
* Teenage girls love to share the play-by-play of their dates with each other.
to freak out – to be very worried or nervous about something, thinking about it all the time and not being able to control one’s emotions and/or actions
* If the client doesn’t sign the contract soon, our boss is going to freak out.
to fasten (one’s) seat belt – to pull the long piece of fabric across one’s chest and upper legs while sitting in a car or an airplane and connect the metal piece on the end with the metal piece attached to the seat so that one is attached to the car or airplane and will not move very much
* Karina refuses to start the car until everyone has fastened their seat belt.
block – in a city, the square area and all the buildings in it surrounded by four crossing streets
* The pharmacy is on the same block as the library.
stop sign – a red 8-sided sign with the word “STOP” printed on it in white letters, letting drivers know they need to stop before going through an intersection (two crossing streets)
* Did you see that other car? The driver didn’t stop at the stop sign and drove right through the intersection. She could have killed someone!
traffic signal – a box with lights that tell drivers when they can drive through an intersection (two crossing streets) and when they need to stop, usually with a red light, a yellow light, and a green light
* Is this traffic signal working? It seems like we’ve been stopped here with a red light forever.
freeway – a wide road with many lanes where cars drive very quickly and do not need to stop because there are no intersections (two crossing streets)
* Normally cars move quickly on this freeway, but yesterday there was an accident, so everyone had to drive really slowly.
onramp – a short road that joins a freeway at an angle so that cars can increase their speed until they are going the same speed as the cars on the freeway and then they can enter the freeway lanes and drive with the rest of the cars
* If an onramp is too short, it can be difficult for drivers to make their cars go fast enough before they reach the faster cars on the freeway.
to merge – for two lanes to join, so that drivers have to make room for each other so that all the cars can be in one lane
* In rural areas, drivers are more likely to slow down and make room for other cars to merge onto the freeway.
to change lanes – to move one’s car from one lane to another one going in the same direction, usually so that one can drive more quickly or more slowly
* If you want to go faster, change lanes and drive in the passing lane.
to accelerate – to increase one’s speed; to make something go faster
* Can electric cars accelerate as quickly as gasoline-powered cars?
to signal – to make colored lights on the front and back of one’s car turn on and off repeatedly to show other drivers that one wants to turn or change direction
* According to the law, we’re supposed to signal about 100 feet before we make a turn.
speed limit – the maximum allowed speed; the fastest speed one can legally drive at
* The speed limit on many residential streets is just 20 or 25 miles per hour.
to parallel park – to park on the side of a street so that one is parallel to the cars that are moving, with one car in front and another car behind, so that one has to drive backward and forward several times to fit into the space
* Teraz hates parallel parking, so he spends a lot of time looking for parking lots with standard parking spaces that he can turn into.
behind the wheel – driving a car; sitting in the driver’s seat of a car
* Do you think most 16-year-olds are responsible enough to be behind the wheel?
to have (got) someplace to be – a phrase used to show that one should be somewhere else at a certain time, without providing any details, often used when one is lying and simply does not want to do whatever the other person is talking about
* - Can you watch the kids tonight?
* - Uh, no, sorry, I’ve got someplace to be.
Comprehension Questions
1. Why is May worried about the driving test?
a) Because she doesn’t have enough money to pay for it.
b) Because she doesn’t have enough experience driving.
c) Because she doesn’t know anyone who has passed it.
2. When should a driver signal?
a) When fastening his or her seat belt.
b) When stopping at a stop sign.
c) When changing lanes.
Answers at bottom.
What Else Does It Mean?
license
The word “license,” in this podcast, means legal permission to have or do something: “How much does a fishing license cost?” Or, “Is it difficult to get a business license from the city?” Sometimes the word “license” refers to the small card or other piece of paper that proves one is allowed to do something: “Maria had to show a copy of their marriage license when she wanted to change her last name.” When talking about software, a “license” is permission for one person to use the software: “The software company charges an upfront cost of $15,000, plus a license fee of $45 per user.” Finally, the phrase “poetic license” or “artistic license” refers to one’s ability to use imagination and change the truth a little bit for artistic or creative reasons: “Francesca writes historical fiction, but she takes some artistic license to make the stories more interesting.”
to signal
In this podcast, the verb “to signal” means to make colored lights on the front and back of one’s car turn on and off repeatedly to show other drivers that one wants to turn or change direction: “Norman got a ticket for turning without signaling first.” The verb “to signal” can also mean to indicate or imply that something is true: “Rising food prices can signal inflation.” The verb “to signal” can also mean to communicate something without words: “At an airport, workers use colored sticks and flags to signal when it is safe for pilots to move airplanes closer to the gate.”
Culture Note
Common Reasons for Failing the Driving Test
Most people who study their state’s “driver’s manual” (a small book describing all the laws for driving in a particular state) are able to pass the written test without too much trouble, but some of them “struggle” (have difficulty) to pass the “driving test” (an exam where one drives a car while someone sits in the front seat and observes how well or poorly one drives).
Sometimes people “fail” (do not pass) the driving test because they are not “observant” (watching and paying attention to what is happening around oneself). They might not use the “side-view” (mirrors on each side of the car) and “rear-view” (a mirror on the windshield inside the car) mirrors enough to be aware of the cars around them, or they might not be looking in all directions before passing through an “intersection” (where two or more streets meet or cross).
Other people fail the driving test because they “speed” (drive more quickly than allowed by law). Sometimes the speed limit isn’t “posted” (written on a sign for drivers to see), but drivers are expected to know the maximum speed limit for “residential” (in an area with many homes) and “commercial” (in an area with many businesses and office buildings) “zones” (areas). Some people fail when they drive through a “school zone” (the area around a school) without slowing down to 15 or 20 miles per hour, as is required by law.
Finally, some people fail their driving test because they cannot follow the examiner’s specific instructions. For example, if the driver is not able to parallel park well, the examiner might think that the driver does not have enough experience to have a driver’s license.
Comprehension Answers
1 - b
2 - c